Cataclysm BN: src/achievement.cpp File Reference
achievement.cpp File Reference
#include "achievement.h"
#include <cassert>
#include <cstdlib>
#include <set>
#include <tuple>
#include <utility>
#include "color.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_statistics.h"
#include "generic_factory.h"
#include "json.h"
#include "stats_tracker.h"
#include "string_formatter.h"
Classes
struct achievement_requirement
class requirement_watcher
Namespaces
namespace anonymous_namespace{achievement.cpp}
namespace io
Functions
template<>
std::string io::enum_to_string< achievement_comparison > (achievement_comparison data)
template<>
std::string io::enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
static nc_color color_from_completion (achievement_completion comp)
static time_point epoch_to_time_point (achievement::time_bound::epoch e)
static std::string text_for_requirement (const achievement_requirement &req, const cata_variant &current_value)
template<>
std::string io::enum_to_string< achievement_completion > (achievement_completion data)
Variables
generic_factory< achievement > anonymous_namespace{achievement.cpp}::achievement_factory ("achievement")
Function Documentation
color_from_completion()
static nc_color color_from_completion (achievement_completion comp) static
Definition at line 106 of file achievement.cpp.
{
    switch( comp ) {
        case achievement_completion::pending:
            return c_yellow;
        case achievement_completion::completed:
            return c_light_green;
        case achievement_completion::failed:
            return c_light_gray;
        case achievement_completion::last:
            break;
    }
    debugmsg( "Invalid achievement_completion" );
    abort();
}
References abort, c_light_gray, c_light_green, c_yellow, completed, debugmsg, failed, last, and pending.
Referenced by achievement::time_bound::ui_text(), achievement_tracker::ui_text(), and achievement_state::ui_text().
epoch_to_time_point()
static time_point epoch_to_time_point (achievement::time_bound::epoch e) static
Definition at line 179 of file achievement.cpp.
{
    switch( e ) {
        case achievement::time_bound::epoch::cataclysm:
            return calendar::start_of_cataclysm;
        case achievement::time_bound::epoch::game_start:
            return calendar::start_of_game;
        case achievement::time_bound::epoch::last:
            break;
    }
    debugmsg( "Invalid epoch" );
    abort();
}
References abort, achievement::time_bound::cataclysm, debugmsg, achievement::time_bound::game_start, achievement::time_bound::last, calendar::start_of_cataclysm, and calendar::start_of_game.
Referenced by achievement::time_bound::target().
text_for_requirement()
static std::string text_for_requirement (const achievement_requirement & req, const cata_variant & current_value) static
Definition at line 351 of file achievement.cpp.
{
    bool is_satisfied = req.satisifed_by( current_value );
    nc_color c = is_satisfied ? c_green : c_yellow;
    int current = current_value.get<int>();
    int target;
    std::string result;
    if( req.comparison == achievement_comparison::anything ) {
        target = 1;
        result = string_format( _( "Triggered by " ) );
    } else {
        target = req.target;
        result = string_format( _( "%s/%s " ), current, target );
    }
    result += req.statistic->description().translated( target );
    return colorize( result, c );
}
References _, anything, c, c_green, c_yellow, colorize(), achievement_requirement::comparison, cata_variant::get(), achievement_requirement::satisifed_by(), achievement_requirement::statistic, string_format(), and achievement_requirement::target.
Referenced by requirement_watcher::ui_text(), and achievement_state::ui_text().