Cataclysm BN: src/activity_item_handling.cpp File Reference
activity_item_handling.cpp File Reference
#include "activity_handlers.h"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <list>
#include <memory>
#include <numeric>
#include <set>
#include <sstream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "avatar.h"
#include "avatar_action.h"
#include "calendar.h"
#include "character.h"
#include "character_functions.h"
#include "clzones.h"
#include "colony.h"
#include "construction.h"
#include "construction_partial.h"
#include "creature.h"
#include "debug.h"
#include "drop_token.h"
#include "enums.h"
#include "field.h"
#include "field_type.h"
#include "fire.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "iexamine.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "optional.h"
#include "output.h"
#include "pickup.h"
#include "pickup_token.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "trap.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
#include "weather.h"
Namespaces
namespace pickup
Functions
static const std::string flag_BUTCHER_EQ ("BUTCHER_EQ")
static const std::string flag_DIG_TOOL ("DIG_TOOL")
static const std::string flag_FISHABLE ("FISHABLE")
static const std::string flag_FISH_GOOD ("FISH_GOOD")
static const std::string flag_FISH_POOR ("FISH_POOR")
static const std::string flag_GROWTH_HARVEST ("GROWTH_HARVEST")
static const std::string flag_PLANT ("PLANT")
static const std::string flag_PLANTABLE ("PLANTABLE")
static const std::string flag_PLOWABLE ("PLOWABLE")
static const std::string flag_TREE ("TREE")
static const std::string flag_UNSAFE_CONSUME ("UNSAFE_CONSUME")
void cancel_aim_processing ()
static bool same_type (const std::list< item > &items)
static void put_into_vehicle (Character &c, item_drop_reason reason, const std::list< item > &items, vehicle &veh, int part)
static void pass_to_ownership_handling (item obj, Character &c)
static void stash_on_pet (const std::list< item > &items, monster &pet, Character &who)
void drop_on_map (Character &c, item_drop_reason reason, const std::list< item > &items, const tripoint &where)
void put_into_vehicle_or_drop (Character &c, item_drop_reason reason, const std::list< item > &items)
void put_into_vehicle_or_drop (Character &c, item_drop_reason reason, const std::list< item > &items, const tripoint &where, bool force_ground)
static std::list< pickup::act_item > convert_to_items (Character &p, const drop_locations &drop, std::function< bool(item_location loc)> filter)
std::list< act_item > pickup::reorder_for_dropping (Character &p, const drop_locations &drop)
static bool pickup::try_rebuild_if_needed (item_location &loc)
std::list< item > pickup::obtain_and_tokenize_items (player &p, std::list< act_item > &items)
static void debug_drop_list (const std::list< pickup::act_item > &list)
static void debug_tokens (const std::list< item > &items)
static std::list< item > obtain_activity_items (Character &who, std::list< pickup::act_item > &targets)
void activity_on_turn_wear (player_activity &act, player &p)
static double get_capacity_fraction (int capacity, int volume)
static int move_cost_inv (const item &it, const tripoint &src, const tripoint &dest)
static int move_cost_cart (const item &it, const tripoint &src, const tripoint &dest, const units::volume &capacity)
static int move_cost (const item &it, const tripoint &src, const tripoint &dest)
static bool vehicle_activity (player &p, const tripoint &src_loc, int vpindex, char type)
static void move_item (player &p, item &it, const int quantity, const tripoint &src, const tripoint &dest, vehicle *src_veh, int src_part, const activity_id &activity_to_restore=activity_id::NULL_ID())
std::vector< tripoint > route_adjacent (const player &p, const tripoint &dest)
static activity_reason_info find_base_construction (const std::vector< construction_id > &list_constructions, player &p, const inventory &inv, const tripoint &loc, const cata::optional< construction_id > &part_con_id, const construction_id id, std::set< construction_id > &used)
static std::string random_string (size_t length)
static bool are_requirements_nearby (const std::vector< tripoint > &loot_spots, const requirement_id &needed_things, player &p, const activity_id &activity_to_restore, const bool in_loot_zones, const tripoint &src_loc)
static bool has_skill_for_vehicle_work (const std::map< skill_id, int > &required_skills, player &p)
static activity_reason_info can_do_activity_there (const activity_id &act, player &p, const tripoint &src_loc, const int distance=ACTIVITY_SEARCH_DISTANCE)
static void add_basecamp_storage_to_loot_zone_list (zone_manager &mgr, const tripoint &src_loc, player &p, std::vector< tripoint > &loot_zone_spots, std::vector< tripoint > &combined_spots)
static std::vector< std::tuple< tripoint, itype_id, int > > requirements_map (player &p, const int distance=ACTIVITY_SEARCH_DISTANCE)
static bool construction_activity (player &p, const zone_data *, const tripoint &src_loc, const activity_reason_info &act_info, const activity_id &activity_to_restore)
static bool tidy_activity (player &p, const tripoint &src_loc, const activity_id &activity_to_restore, const int distance=ACTIVITY_SEARCH_DISTANCE)
static bool fetch_activity (player &p, const tripoint &src_loc, const activity_id &activity_to_restore, const int distance=ACTIVITY_SEARCH_DISTANCE)
static bool butcher_corpse_activity (player &p, const tripoint &src_loc, const do_activity_reason &reason)
static bool chop_plank_activity (player &p, const tripoint &src_loc)
void activity_on_turn_move_loot (player_activity &act, player &p)
static bool mine_activity (player &p, const tripoint &src_loc)
static bool chop_tree_activity (player &p, const tripoint &src_loc)
static void check_npc_revert (player &p)
static zone_type_id get_zone_for_act (const tripoint &src_loc, const zone_manager &mgr, const activity_id &act_id)
static std::unordered_set< tripoint > generic_multi_activity_locations (player &p, const activity_id &act_id)
Determine all locations for this generic activity.
static requirement_check_result generic_multi_activity_check_requirement (player &p, const activity_id &act_id, activity_reason_info &act_info, const tripoint &src, const tripoint &src_loc, const std::unordered_set< tripoint > &src_set, const bool check_only=false)
Check if this activity can not be done immediately because it has some requirements.
static bool generic_multi_activity_do (player &p, const activity_id &act_id, const activity_reason_info &act_info, const tripoint &src, const tripoint &src_loc)
Do activity at this location.
bool generic_multi_activity_handler (player_activity &act, player &p, bool check_only)
static cata::optional< tripoint > find_best_fire (const std::vector< tripoint > &from, const tripoint &center)
static bool has_clear_path_to_pickup_items (const tripoint &from, const tripoint &to)
static cata::optional< tripoint > find_refuel_spot_zone (const tripoint &center)
static cata::optional< tripoint > find_refuel_spot_trap (const std::vector< tripoint > &from, const tripoint &center)
bool find_auto_consume (player &p, const bool food)
void try_fuel_fire (player_activity &act, player &p, const bool starting_fire)
Variables
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_BUTCHER_FULL ("ACT_BUTCHER_FULL")
static const activity_id ACT_CHOP_LOGS ("ACT_CHOP_LOGS")
static const activity_id ACT_CHOP_PLANKS ("ACT_CHOP_PLANKS")
static const activity_id ACT_CHOP_TREE ("ACT_CHOP_TREE")
static const activity_id ACT_CHURN ("ACT_CHURN")
static const activity_id ACT_FETCH_REQUIRED ("ACT_FETCH_REQUIRED")
static const activity_id ACT_FISH ("ACT_FISH")
static const activity_id ACT_JACKHAMMER ("ACT_JACKHAMMER")
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const activity_id ACT_MULTIPLE_BUTCHER ("ACT_MULTIPLE_BUTCHER")
static const activity_id ACT_MULTIPLE_CHOP_PLANKS ("ACT_MULTIPLE_CHOP_PLANKS")
static const activity_id ACT_MULTIPLE_CHOP_TREES ("ACT_MULTIPLE_CHOP_TREES")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const activity_id ACT_MULTIPLE_FARM ("ACT_MULTIPLE_FARM")
static const activity_id ACT_MULTIPLE_FISH ("ACT_MULTIPLE_FISH")
static const activity_id ACT_MULTIPLE_MINE ("ACT_MULTIPLE_MINE")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_TIDY_UP ("ACT_TIDY_UP")
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const activity_id ACT_VEHICLE_DECONSTRUCTION ("ACT_VEHICLE_DECONSTRUCTION")
static const activity_id ACT_VEHICLE_REPAIR ("ACT_VEHICLE_REPAIR")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_nausea ("nausea")
static const itype_id itype_battery ("battery")
static const itype_id itype_detergent ("detergent")
static const itype_id itype_log ("log")
static const itype_id itype_soap ("soap")
static const itype_id itype_soldering_iron ("soldering_iron")
static const itype_id itype_water ("water")
static const itype_id itype_water_clean ("water_clean")
static const itype_id itype_welder ("welder")
static const trap_str_id tr_firewood_source ("tr_firewood_source")
static const trap_str_id tr_unfinished_construction ("tr_unfinished_construction")
static const zone_type_id zone_type_source_firewood ("SOURCE_FIREWOOD")
static const zone_type_id zone_type_CHOP_TREES ("CHOP_TREES")
static const zone_type_id zone_type_CONSTRUCTION_BLUEPRINT ("CONSTRUCTION_BLUEPRINT")
static const zone_type_id zone_type_FARM_PLOT ("FARM_PLOT")
static const zone_type_id zone_type_FISHING_SPOT ("FISHING_SPOT")
static const zone_type_id zone_type_LOOT_CORPSE ("LOOT_CORPSE")
static const zone_type_id zone_type_LOOT_IGNORE ("LOOT_IGNORE")
static const zone_type_id zone_type_LOOT_IGNORE_FAVORITES ("LOOT_IGNORE_FAVORITES")
static const zone_type_id zone_type_MINING ("MINING")
static const zone_type_id zone_type_LOOT_UNSORTED ("LOOT_UNSORTED")
static const zone_type_id zone_type_LOOT_WOOD ("LOOT_WOOD")
static const zone_type_id zone_type_VEHICLE_DECONSTRUCT ("VEHICLE_DECONSTRUCT")
static const zone_type_id zone_type_VEHICLE_REPAIR ("VEHICLE_REPAIR")
static const zone_type_id z_camp_storage ("CAMP_STORAGE")
static const quality_id qual_AXE ("AXE")
static const quality_id qual_BUTCHER ("BUTCHER")
static const quality_id qual_DIG ("DIG")
static const quality_id qual_FISHING ("FISHING")
static const quality_id qual_SAW_M ("SAW_M")
static const quality_id qual_SAW_W ("SAW_W")
static const quality_id qual_WELD ("WELD")
const int ACTIVITY_SEARCH_DISTANCE = 60
Function Documentation
activity_on_turn_move_loot()
void activity_on_turn_move_loot (player_activity & act, player & p)
Definition at line 2137 of file activity_item_handling.cpp.
{
    enum activity_stage : int {
        //Initial stage
        INIT = 0,
        //Think about what to do first: choose destination
        THINK,
        //Do activity
        DO,
    };
    int &stage = act.index;
    //Prepare activity stage
    if( stage < 0 ) {
        stage = INIT;
        //num_processed
        act.values.push_back( 0 );
    }
    int &num_processed = act.values[ 0 ];
    map &here = get_map();
    const auto abspos = here.getabs( p.pos() );
    auto &mgr = zone_manager::get_manager();
    if( here.check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    if( stage == INIT ) {
        act.coord_set = mgr.get_near( zone_type_LOOT_UNSORTED, abspos, ACTIVITY_SEARCH_DISTANCE );
        stage = THINK;
    }
    if( stage == THINK ) {
        //initialize num_processed
        num_processed = 0;
        const auto &src_set = act.coord_set;
        // sort source tiles by distance
        const auto &src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
        for( auto &src : src_sorted ) {
            act.placement = src;
            act.coord_set.erase( src );
            const auto &src_loc = here.getlocal( src );
            if( !here.inbounds( src_loc ) ) {
                if( !here.inbounds( p.pos() ) ) {
                    // p is implicitly an NPC that has been moved off the map, so reset the activity
                    // and unload them
                    p.cancel_activity();
                    p.assign_activity( ACT_MOVE_LOOT );
                    p.set_moves( 0 );
                    g->reload_npcs();
                    return;
                }
                std::vector<tripoint> route;
                route = here.route( p.pos(), src_loc, p.get_pathfinding_settings(),
                                    p.get_path_avoid() );
                if( route.empty() ) {
                    // can't get there, can't do anything, skip it
                    continue;
                }
                stage = DO;
                p.set_destination( route, act );
                p.activity.set_to_null();
                return;
            }
            // skip tiles in IGNORE zone and tiles on fire
            // (to prevent taking out wood off the lit brazier)
            // and inaccessible furniture, like filled charcoal kiln
            if( mgr.has( zone_type_LOOT_IGNORE, src ) ||
                here.get_field( src_loc, fd_fire ) != nullptr ||
                !here.can_put_items_ter_furn( src_loc ) ) {
                continue;
            }
            //nothing to sort?
            const cata::optional<vpart_reference> vp = here.veh_at( src_loc ).part_with_feature( "CARGO",
                    false );
            if( ( !vp || vp->vehicle().get_items( vp->part_index() ).empty() )
                && here.i_at( src_loc ).empty() ) {
                continue;
            }
            bool is_adjacent_or_closer = square_dist( p.pos(), src_loc ) <= 1;
            // before we move any item, check if player is at or
            // adjacent to the loot source tile
            if( !is_adjacent_or_closer ) {
                std::vector<tripoint> route;
                bool adjacent = false;
                // get either direct route or route to nearest adjacent tile if
                // source tile is impassable
                if( here.passable( src_loc ) ) {
                    route = here.route( p.pos(), src_loc, p.get_pathfinding_settings(),
                                        p.get_path_avoid() );
                } else {
                    // impassable source tile (locker etc.),
                    // get route to nearest adjacent tile instead
                    route = route_adjacent( p, src_loc );
                    adjacent = true;
                }
                // check if we found path to source / adjacent tile
                if( route.empty() ) {
                    add_msg( m_info, _( "%s can't reach the source tile.  Try to sort out loot without a cart." ),
                             p.disp_name() );
                    continue;
                }
                // shorten the route to adjacent tile, if necessary
                if( !adjacent ) {
                    route.pop_back();
                }
                // set the destination and restart activity after player arrives there
                // we don't need to check for safe mode,
                // activity will be restarted only if
                // player arrives on destination tile
                stage = DO;
                p.set_destination( route, act );
                p.activity.set_to_null();
                return;
            }
            stage = DO;
            break;
        }
    }
    if( stage == DO ) {
        const tripoint &src = act.placement;
        const tripoint &src_loc = here.getlocal( src );
        bool is_adjacent_or_closer = square_dist( p.pos(), src_loc ) <= 1;
        // before we move any item, check if player is at or
        // adjacent to the loot source tile
        if( !is_adjacent_or_closer ) {
            stage = THINK;
            return;
        }
        // the boolean in this pair being true indicates the item is from a vehicle storage space
        auto items = std::vector<std::pair<item *, bool>>();
        vehicle *src_veh, *dest_veh;
        int src_part, dest_part;
        //Check source for cargo part
        //map_stack and vehicle_stack are different types but inherit from item_stack
        // TODO: use one for loop
        if( const cata::optional<vpart_reference> vp = here.veh_at( src_loc ).part_with_feature( "CARGO",
                false ) ) {
            src_veh = &vp->vehicle();
            src_part = vp->part_index();
            for( auto &it : src_veh->get_items( src_part ) ) {
                if( !it.is_owned_by( p, true ) ) {
                    continue;
                }
                it.set_owner( p );
                items.push_back( std::make_pair( &it, true ) );
            }
        } else {
            src_veh = nullptr;
            src_part = -1;
        }
        for( auto &it : here.i_at( src_loc ) ) {
            if( !it.is_owned_by( p, true ) ) {
                continue;
            }
            it.set_owner( p );
            items.push_back( std::make_pair( &it, false ) );
        }
        //Skip items that have already been processed
        for( auto it = items.begin() + num_processed; it < items.end(); ++it ) {
            ++num_processed;
            item &thisitem = *it->first;
            // skip unpickable liquid
            if( thisitem.made_of( LIQUID ) ) {
                continue;
            }
            // skip favorite items in ignore favorite zones
            if( thisitem.is_favorite && mgr.has( zone_type_LOOT_IGNORE_FAVORITES, src ) ) {
                continue;
            }
            // Only if it's from a vehicle do we use the vehicle source location information.
            vehicle *this_veh = it->second ? src_veh : nullptr;
            const int this_part = it->second ? src_part : -1;
            const zone_type_id id = mgr.get_near_zone_type_for_item( thisitem, abspos,
                                    ACTIVITY_SEARCH_DISTANCE );
            // checks whether the item is already on correct loot zone or not
            // if it is, we can skip such item, if not we move the item to correct pile
            // think empty bag on food pile, after you ate the content
            if( mgr.has( id, src ) ) {
                continue;
            }
            const std::unordered_set<tripoint> &dest_set = mgr.get_near( id, abspos, ACTIVITY_SEARCH_DISTANCE,
                    &thisitem );
            for( const tripoint &dest : dest_set ) {
                const tripoint &dest_loc = here.getlocal( dest );
                //Check destination for cargo part
                if( const cata::optional<vpart_reference> vp = here.veh_at( dest_loc ).part_with_feature( "CARGO",
                        false ) ) {
                    dest_veh = &vp->vehicle();
                    dest_part = vp->part_index();
                } else {
                    dest_veh = nullptr;
                    dest_part = -1;
                }
                // skip tiles with inaccessible furniture, like filled charcoal kiln
                if( !here.can_put_items_ter_furn( dest_loc ) ||
                    static_cast<int>( here.i_at( dest_loc ).size() ) >= MAX_ITEM_IN_SQUARE ) {
                    continue;
                }
                units::volume free_space;
                // if there's a vehicle with space do not check the tile beneath
                if( dest_veh ) {
                    free_space = dest_veh->free_volume( dest_part );
                } else {
                    free_space = here.free_volume( dest_loc );
                }
                // check free space at destination
                if( free_space >= thisitem.volume() ) {
                    move_item( p, thisitem, thisitem.count(), src_loc, dest_loc, this_veh, this_part );
                    // moved item away from source so decrement
                    if( num_processed > 0 ) {
                        --num_processed;
                    }
                    break;
                }
            }
            if( p.moves <= 0 ) {
                return;
            }
        }
        //this location is sorted
        stage = THINK;
        return;
    }
    // If we got here without restarting the activity, it means we're done
    add_msg( m_info, _( "%s sorted out every item possible." ), p.disp_name( false, true ) );
    if( p.is_npc() ) {
        npc *guy = dynamic_cast<npc *>( &p );
        guy->revert_after_activity();
    }
    p.activity.set_to_null();
}
References _, act, ACT_MOVE_LOOT, Character::activity, ACTIVITY_SEARCH_DISTANCE, add_msg(), Character::assign_activity(), map::can_put_items_ter_furn(), Character::cancel_activity(), map::check_vehicle_zones(), item::count(), Character::disp_name(), item_stack::empty(), fd_fire, map::free_volume(), g, map::get_field(), zone_manager::get_manager(), get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), map::i_at(), map::inbounds(), item::is_favorite, player::is_npc(), item::is_owned_by(), LIQUID, m_info, item::made_of(), MAX_ITEM_IN_SQUARE, move_item(), Creature::moves, optional_vpart_position::part_with_feature(), map::passable(), Character::pos(), npc::revert_after_activity(), map::route(), route_adjacent(), Character::set_destination(), Creature::set_moves(), item::set_owner(), player_activity::set_to_null(), item_stack::size(), square_dist(), map::veh_at(), vehicle::vehicle(), item::volume(), zone_type_LOOT_IGNORE, zone_type_LOOT_IGNORE_FAVORITES, and zone_type_LOOT_UNSORTED.
Referenced by activity_handlers::move_loot_do_turn().
activity_on_turn_wear()
void activity_on_turn_wear (player_activity & act, player & p)
Definition at line 698 of file activity_item_handling.cpp.
{
    // ACT_WEAR has item_location targets, and int quantities
    while( p.moves > 0 && !act.targets.empty() ) {
        item_location target = std::move( act.targets.back() );
        int quantity = act.values.back();
        act.targets.pop_back();
        act.values.pop_back();
        if( !target ) {
            debugmsg( "Lost target item of ACT_WEAR" );
            continue;
        }
        // Make copies so the original remains untouched if wearing fails
        item newit = *target;
        item leftovers = newit;
        // Handle charges, quantity == 0 means move all
        if( quantity != 0 && newit.count_by_charges() ) {
            leftovers.charges = newit.charges - quantity;
            if( leftovers.charges > 0 ) {
                newit.charges = quantity;
            }
        } else {
            leftovers.charges = 0;
        }
        if( p.wear_item( newit ) ) {
            // If we wore up a whole stack, remove the original item
            // Otherwise, replace the item with the leftovers
            if( leftovers.charges > 0 ) {
                *target = std::move( leftovers );
            } else {
                target.remove_item();
            }
        }
    }
    // If there are no items left we are done
    if( act.targets.empty() ) {
        p.cancel_activity();
    }
}
References act, Character::cancel_activity(), item::charges, item::count_by_charges(), debugmsg, avatar_action::move(), Creature::moves, item_location::remove_item(), and Character::wear_item().
Referenced by activity_handlers::wear_do_turn().
add_basecamp_storage_to_loot_zone_list()
static void add_basecamp_storage_to_loot_zone_list (zone_manager & mgr, const tripoint & src_loc, player & p, std::vector< tripoint > & loot_zone_spots, std::vector< tripoint > & combined_spots) static
Definition at line 1609 of file activity_item_handling.cpp.
{
    if( npc *const guy = dynamic_cast<npc *>( &p ) ) {
        map &here = get_map();
        if( guy->assigned_camp &&
            mgr.has_near( z_camp_storage, here.getabs( src_loc ), ACTIVITY_SEARCH_DISTANCE ) ) {
            std::unordered_set<tripoint> bc_storage_set = mgr.get_near( zone_type_id( "CAMP_STORAGE" ),
                    here.getabs( src_loc ), ACTIVITY_SEARCH_DISTANCE );
            for( const tripoint &elem : bc_storage_set ) {
                loot_zone_spots.push_back( here.getlocal( elem ) );
                combined_spots.push_back( here.getlocal( elem ) );
            }
        }
    }
}
References ACTIVITY_SEARCH_DISTANCE, get_map(), zone_manager::get_near(), map::getabs(), map::getlocal(), zone_manager::has_near(), and z_camp_storage.
Referenced by generic_multi_activity_check_requirement(), and requirements_map().
are_requirements_nearby()
static bool are_requirements_nearby (const std::vector< tripoint > & loot_spots, const requirement_id & needed_things, player & p, const activity_id & activity_to_restore, const bool in_loot_zones, const tripoint & src_loc) static
Definition at line 1191 of file activity_item_handling.cpp.
{
    zone_manager &mgr = zone_manager::get_manager();
    inventory temp_inv;
    units::volume volume_allowed = p.volume_capacity() - p.volume_carried();
    units::mass weight_allowed = p.weight_capacity() - p.weight_carried();
    static const auto check_weight_if = []( const activity_id & id ) {
        return id == ACT_MULTIPLE_FARM ||
               id == ACT_MULTIPLE_CHOP_PLANKS ||
               id == ACT_MULTIPLE_BUTCHER ||
               id == ACT_VEHICLE_DECONSTRUCTION ||
               id == ACT_VEHICLE_REPAIR ||
               id == ACT_MULTIPLE_CHOP_TREES ||
               id == ACT_MULTIPLE_FISH ||
               id == ACT_MULTIPLE_MINE;
    };
    const bool check_weight = check_weight_if( activity_to_restore ) || ( !p.backlog.empty() &&
                              check_weight_if( p.backlog.front().id() ) );
    bool found_welder = false;
    for( item *elem : p.inv_dump() ) {
        if( elem->has_quality( qual_WELD ) ) {
            found_welder = true;
        }
        temp_inv += *elem;
    }
    map &here = get_map();
    for( const tripoint &elem : loot_spots ) {
        // if we are searching for things to fetch, we can skip certain things.
        // if, however they are already near the work spot, then the crafting / inventory functions will have their own method to use or discount them.
        if( in_loot_zones ) {
            // skip tiles in IGNORE zone and tiles on fire
            // (to prevent taking out wood off the lit brazier)
            // and inaccessible furniture, like filled charcoal kiln
            if( mgr.has( zone_type_LOOT_IGNORE, here.getabs( elem ) ) ||
                here.dangerous_field_at( elem ) ||
                !here.can_put_items_ter_furn( elem ) ) {
                continue;
            }
        }
        for( const auto &elem2 : here.i_at( elem ) ) {
            if( in_loot_zones && elem2.made_of( LIQUID ) ) {
                continue;
            }
            if( check_weight ) {
                // this fetch task will need to pick up an item. so check for its weight/volume before setting off.
                if( in_loot_zones && ( elem2.volume() > volume_allowed ||
                                       elem2.weight() > weight_allowed ) ) {
                    continue;
                }
            }
            temp_inv += elem2;
        }
        if( !in_loot_zones ) {
            if( const cata::optional<vpart_reference> vp = here.veh_at( elem ).part_with_feature( "CARGO",
                    false ) ) {
                vehicle &src_veh = vp->vehicle();
                int src_part = vp->part_index();
                for( auto &it : src_veh.get_items( src_part ) ) {
                    temp_inv += it;
                }
            }
        }
    }
    // use nearby welding rig without needing to drag it or position yourself on the right side of the vehicle.
    if( !found_welder ) {
        for( const tripoint &elem : here.points_in_radius( src_loc, PICKUP_RANGE - 1 ) ) {
            const optional_vpart_position vp = here.veh_at( elem );
            if( vp ) {
                vehicle &veh = vp->vehicle();
                const cata::optional<vpart_reference> weldpart = vp.part_with_feature( "WELDRIG", true );
                if( weldpart ) {
                    item welder( itype_welder, calendar::start_of_cataclysm );
                    welder.charges = veh.fuel_left( itype_battery, true );
                    welder.set_flag( "PSEUDO" );
                    temp_inv.add_item( welder );
                    item soldering_iron( itype_soldering_iron, calendar::start_of_cataclysm );
                    soldering_iron.charges = veh.fuel_left( itype_battery, true );
                    soldering_iron.set_flag( "PSEUDO" );
                    temp_inv.add_item( soldering_iron );
                }
            }
        }
    }
    return needed_things.obj().can_make_with_inventory( temp_inv, is_crafting_component );
}
References ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_MULTIPLE_MINE, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, inventory::add_item(), Character::backlog, requirement_data::can_make_with_inventory(), map::can_put_items_ter_furn(), item::charges, map::dangerous_field_at(), vehicle::fuel_left(), vehicle::get_items(), zone_manager::get_manager(), get_map(), map::getabs(), zone_manager::has(), map::i_at(), int_id< T >::id(), Character::inv_dump(), is_crafting_component(), itype_battery, itype_soldering_iron, itype_welder, LIQUID, string_id< T >::obj(), optional_vpart_position::part_with_feature(), PICKUP_RANGE, map::points_in_radius(), qual_WELD, item::set_flag(), calendar::start_of_cataclysm, map::veh_at(), vehicle::vehicle(), Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), Character::weight_carried(), and zone_type_LOOT_IGNORE.
Referenced by generic_multi_activity_check_requirement(), and requirements_map().
butcher_corpse_activity()
static bool butcher_corpse_activity (player & p, const tripoint & src_loc, const do_activity_reason & reason) static
Definition at line 2093 of file activity_item_handling.cpp.
{
    map &here = get_map();
    map_stack items = here.i_at( src_loc );
    for( auto &elem : items ) {
        if( elem.is_corpse() && !elem.has_var( "activity_var" ) ) {
            const mtype corpse = *elem.get_mtype();
            if( corpse.size >= MS_MEDIUM && reason != do_activity_reason::NEEDS_BIG_BUTCHERING ) {
                continue;
            }
            elem.set_var( "activity_var", p.name );
            p.assign_activity( ACT_BUTCHER_FULL, 0, true );
            p.activity.targets.emplace_back( map_cursor( src_loc ), &elem );
            p.activity.placement = here.getabs( src_loc );
            return true;
        }
    }
    return false;
}
References ACT_BUTCHER_FULL, Character::activity, Character::assign_activity(), corpse, get_map(), map::getabs(), map::i_at(), MS_MEDIUM, Character::name, NEEDS_BIG_BUTCHERING, player_activity::placement, and player_activity::targets.
Referenced by generic_multi_activity_do().
can_do_activity_there()
static activity_reason_info can_do_activity_there (const activity_id & act, player & p, const tripoint & src_loc, const int distance = ACTIVITY_SEARCH_DISTANCE) static
Definition at line 1290 of file activity_item_handling.cpp.
{
    // see activity_handlers.h cant_do_activity_reason enums
    p.invalidate_crafting_inventory();
    zone_manager &mgr = zone_manager::get_manager();
    std::vector<zone_data> zones;
    map &here = get_map();
    if( act == ACT_VEHICLE_DECONSTRUCTION ||
        act == ACT_VEHICLE_REPAIR ) {
        std::vector<int> already_working_indexes;
        vehicle *veh = veh_pointer_or_null( here.veh_at( src_loc ) );
        if( !veh ) {
            return activity_reason_info::fail( do_activity_reason::NO_ZONE );
        }
        // if the vehicle is moving or player is controlling it.
        if( std::abs( veh->velocity ) > 100 || veh->player_in_control( g->u ) ) {
            return activity_reason_info::fail( do_activity_reason::NO_ZONE );
        }
        for( const npc &guy : g->all_npcs() ) {
            if( &guy == &p ) {
                continue;
            }
            // If the NPC has an activity - make sure they're not duplicating work.
            tripoint guy_work_spot;
            if( guy.has_player_activity() && guy.activity.placement != tripoint_min ) {
                guy_work_spot = here.getlocal( guy.activity.placement );
            }
            // If their position or intended position or player position/intended position
            // then discount, don't need to move each other out of the way.
            if( here.getlocal( g->u.activity.placement ) == src_loc ||
                guy_work_spot == src_loc || guy.pos() == src_loc || ( p.is_npc() && g->u.pos() == src_loc ) ) {
                return activity_reason_info::fail( do_activity_reason::ALREADY_WORKING );
            }
            if( guy_work_spot != tripoint_zero ) {
                vehicle *other_veh = veh_pointer_or_null( here.veh_at( guy_work_spot ) );
                // working on same vehicle - store the index to check later.
                if( other_veh && other_veh == veh && guy.activity_vehicle_part_index != -1 ) {
                    already_working_indexes.push_back( guy.activity_vehicle_part_index );
                }
            }
            if( g->u.activity_vehicle_part_index != -1 ) {
                already_working_indexes.push_back( g->u.activity_vehicle_part_index );
            }
        }
        if( act == ACT_VEHICLE_DECONSTRUCTION ) {
            // find out if there is a vehicle part here we can remove.
            std::vector<vehicle_part *> parts = veh->get_parts_at( src_loc, "", part_status_flag::any );
            for( vehicle_part *part_elem : parts ) {
                const vpart_info &vpinfo = part_elem->info();
                int vpindex = veh->index_of_part( part_elem, true );
                // if part is not on this vehicle, or if its attached to another part that needs to be removed first.
                if( vpindex == -1 || !veh->can_unmount( vpindex ) ) {
                    continue;
                }
                // this is the same part that somebody else wants to work on, or already is.
                if( std::find( already_working_indexes.begin(), already_working_indexes.end(),
                               vpindex ) != already_working_indexes.end() ) {
                    continue;
                }
                // don't have skill to remove it
                if( !has_skill_for_vehicle_work( vpinfo.removal_skills, p ) ) {
                    continue;
                }
                item base( vpinfo.item );
                if( base.is_wheel() ) {
                    // no wheel removal yet
                    continue;
                }
                const int max_lift = p.best_nearby_lifting_assist( src_loc );
                const int lvl = std::ceil( units::quantity<double, units::mass::unit_type>( base.weight() ) /
                                           TOOL_LIFT_FACTOR );
                const bool use_aid = max_lift >= lvl;
                const bool use_str = p.can_lift( base.lift_strength() );
                if( !( use_aid || use_str ) ) {
                    continue;
                }
                const auto &reqs = vpinfo.removal_requirements();
                const inventory &inv = p.crafting_inventory( false );
                const bool can_make = reqs.can_make_with_inventory( inv, is_crafting_component );
                p.set_value( "veh_index_type", vpinfo.name() );
                // temporarily store the intended index, we do this so two NPCs don't try and work on the same part at same time.
                p.activity_vehicle_part_index = vpindex;
                if( !can_make ) {
                    return activity_reason_info::fail( do_activity_reason::NEEDS_VEH_DECONST );
                } else {
                    return activity_reason_info::ok( do_activity_reason::NEEDS_VEH_DECONST );
                }
            }
        } else if( act == ACT_VEHICLE_REPAIR ) {
            // find out if there is a vehicle part here we can repair.
            std::vector<vehicle_part *> parts = veh->get_parts_at( src_loc, "", part_status_flag::any );
            for( vehicle_part *part_elem : parts ) {
                const vpart_info &vpinfo = part_elem->info();
                int vpindex = veh->index_of_part( part_elem, true );
                // if part is undamaged or beyond repair - can skip it.
                if( part_elem->is_broken() || part_elem->damage() == 0 ||
                    part_elem->info().repair_requirements().is_empty() ) {
                    continue;
                }
                if( std::find( already_working_indexes.begin(), already_working_indexes.end(),
                               vpindex ) != already_working_indexes.end() ) {
                    continue;
                }
                // don't have skill to repair it
                if( !has_skill_for_vehicle_work( vpinfo.repair_skills, p ) ) {
                    continue;
                }
                const auto &reqs = vpinfo.repair_requirements();
                const inventory &inv = p.crafting_inventory( src_loc, PICKUP_RANGE - 1, false );
                const bool can_make = reqs.can_make_with_inventory( inv, is_crafting_component );
                p.set_value( "veh_index_type", vpinfo.name() );
                // temporarily store the intended index, we do this so two NPCs don't try and work on the same part at same time.
                p.activity_vehicle_part_index = vpindex;
                if( !can_make ) {
                    return activity_reason_info::fail( do_activity_reason::NEEDS_VEH_REPAIR );
                } else {
                    return activity_reason_info::ok( do_activity_reason::NEEDS_VEH_REPAIR );
                }
            }
        }
        p.activity_vehicle_part_index = -1;
        return activity_reason_info::fail( do_activity_reason::NO_ZONE );
    }
    if( act == ACT_MULTIPLE_MINE ) {
        if( !here.has_flag( "MINEABLE", src_loc ) ) {
            return activity_reason_info::fail( do_activity_reason::NO_ZONE );
        }
        std::vector<item *> mining_inv = p.items_with( []( const item & itm ) {
            return ( itm.has_flag( flag_DIG_TOOL ) && !itm.type->can_use( "JACKHAMMER" ) ) ||
                   ( itm.type->can_use( "JACKHAMMER" ) && itm.ammo_sufficient() );
        } );
        if( mining_inv.empty() ) {
            return activity_reason_info::fail( do_activity_reason::NEEDS_MINING );
        } else {
            return activity_reason_info::ok( do_activity_reason::NEEDS_MINING );
        }
    }
    if( act == ACT_MULTIPLE_FISH ) {
        if( !here.has_flag( flag_FISHABLE, src_loc ) ) {
            return activity_reason_info::fail( do_activity_reason::NO_ZONE );
        }
        std::vector<item *> rod_inv = p.items_with( []( const item & itm ) {
            return itm.has_flag( flag_FISH_POOR ) || itm.has_flag( flag_FISH_GOOD );
        } );
        if( rod_inv.empty() ) {
            return activity_reason_info::fail( do_activity_reason::NEEDS_FISHING );
        } else {
            return activity_reason_info::ok( do_activity_reason::NEEDS_FISHING );
        }
    }
    if( act == ACT_MULTIPLE_CHOP_TREES ) {
        if( here.has_flag( flag_TREE, src_loc ) || here.ter( src_loc ) == t_trunk ||
            here.ter( src_loc ) == t_stump ) {
            if( p.has_quality( qual_AXE ) ) {
                return activity_reason_info::ok( do_activity_reason::NEEDS_TREE_CHOPPING );
            } else {
                return activity_reason_info::fail( do_activity_reason::NEEDS_TREE_CHOPPING );
            }
        } else {
            return activity_reason_info::fail( do_activity_reason::NO_ZONE );
        }
    }
    if( act == ACT_MULTIPLE_BUTCHER ) {
        std::vector<item> corpses;
        int big_count = 0;
        int small_count = 0;
        for( const auto &i : here.i_at( src_loc ) ) {
            // make sure nobody else is working on that corpse right now
            if( i.is_corpse() && !i.has_var( "activity_var" ) ) {
                const mtype corpse = *i.get_mtype();
                if( corpse.size >= MS_MEDIUM ) {
                    big_count += 1;
                } else {
                    small_count += 1;
                }
                corpses.push_back( i );
            }
        }
        bool b_rack_present = false;
        for( const tripoint &pt : here.points_in_radius( src_loc, 2 ) ) {
            const inventory &inv = p.crafting_inventory();
            if( here.has_flag_furn( flag_BUTCHER_EQ, pt ) || inv.has_item_with( []( const item & it ) {
            return it.has_flag( "BUTCHER_RACK" );
            } ) ) {
                b_rack_present = true;
            }
        }
        if( !corpses.empty() ) {
            if( big_count > 0 && small_count == 0 ) {
                const inventory &inv = p.crafting_inventory();
                if( !b_rack_present || !( here.has_nearby_table( src_loc, PICKUP_RANGE ) ||
                inv.has_item_with( []( const item & it ) {
                return it.has_flag( "FLAT_SURFACE" );
                } ) ) ) {
                    return activity_reason_info::fail( do_activity_reason::NO_ZONE );
                }
                if( p.has_quality( quality_id( qual_BUTCHER ), 1 ) ) {
                    return activity_reason_info::ok( do_activity_reason::NEEDS_BIG_BUTCHERING );
                } else {
                    return activity_reason_info::fail( do_activity_reason::NEEDS_BIG_BUTCHERING );
                }
            }
            if( ( big_count > 0 && small_count > 0 ) || ( big_count == 0 ) ) {
                // there are small corpses here, so we can ignore any big corpses here for the moment.
                if( p.has_quality( qual_BUTCHER, 1 ) ) {
                    return activity_reason_info::ok( do_activity_reason::NEEDS_BUTCHERING );
                } else {
                    return activity_reason_info::fail( do_activity_reason::NEEDS_BUTCHERING );
                }
            }
        }
        return activity_reason_info::fail( do_activity_reason::NO_ZONE );
    }
    if( act == ACT_MULTIPLE_CHOP_PLANKS ) {
        //are there even any logs there?
        for( auto &i : here.i_at( src_loc ) ) {
            if( i.typeId() == itype_log ) {
                // do we have an axe?
                if( p.has_quality( qual_AXE, 1 ) ) {
                    return activity_reason_info::ok( do_activity_reason::NEEDS_CHOPPING );
                } else {
                    return activity_reason_info::fail( do_activity_reason::NEEDS_CHOPPING );
                }
            }
        }
        return activity_reason_info::fail( do_activity_reason::NO_ZONE );
    }
    if( act == ACT_TIDY_UP ) {
        if( mgr.has_near( zone_type_LOOT_UNSORTED, here.getabs( src_loc ), distance ) ||
            mgr.has_near( z_camp_storage, here.getabs( src_loc ), distance ) ) {
            return activity_reason_info::ok( do_activity_reason::CAN_DO_FETCH );
        }
        return activity_reason_info::fail( do_activity_reason::NO_ZONE );
    }
    if( act == ACT_MULTIPLE_CONSTRUCTION ) {
        zones = mgr.get_zones( zone_type_CONSTRUCTION_BLUEPRINT,
                               here.getabs( src_loc ) );
        const partial_con *part_con = here.partial_con_at( src_loc );
        cata::optional<construction_id> part_con_idx;
        if( part_con ) {
            part_con_idx = part_con->id;
        }
        const map_stack stuff_there = here.i_at( src_loc );
        // PICKUP_RANGE -1 because we will be adjacent to the spot when arriving.
        const inventory pre_inv = p.crafting_inventory( src_loc, PICKUP_RANGE - 1 );
        for( const zone_data &zone : zones ) {
            const blueprint_options &options = dynamic_cast<const blueprint_options &>( zone.get_options() );
            const construction_id index = options.get_index();
            if( !stuff_there.empty() ) {
                return activity_reason_info::build( do_activity_reason::BLOCKING_TILE, false, index );
            }
            std::set<construction_id> used_idx;
            const activity_reason_info act_info = find_base_construction(
                    constructions::get_all_sorted(), p, pre_inv, src_loc, part_con_idx, index, used_idx
                                                  );
            return act_info;
        }
    } else if( act == ACT_MULTIPLE_FARM ) {
        zones = mgr.get_zones( zone_type_FARM_PLOT,
                               here.getabs( src_loc ) );
        for( const zone_data &zone : zones ) {
            if( here.has_flag_furn( flag_GROWTH_HARVEST, src_loc ) ) {
                // simple work, pulling up plants, nothing else required.
                return activity_reason_info::ok( do_activity_reason::NEEDS_HARVESTING );
            } else if( here.has_flag( flag_PLOWABLE, src_loc ) && !here.has_furn( src_loc ) ) {
                if( p.has_quality( qual_DIG, 1 ) ) {
                    // we have a shovel/hoe already, great
                    return activity_reason_info::ok( do_activity_reason::NEEDS_TILLING );
                } else {
                    // we need a shovel/hoe
                    return activity_reason_info::fail( do_activity_reason::NEEDS_TILLING );
                }
            } else if( here.has_flag_ter_or_furn( flag_PLANTABLE, src_loc ) &&
                       warm_enough_to_plant( src_loc ) ) {
                if( here.has_items( src_loc ) ) {
                    return activity_reason_info::fail( do_activity_reason::BLOCKING_TILE );
                } else {
                    // do we have the required seed on our person?
                    const plot_options &options = dynamic_cast<const plot_options &>( zone.get_options() );
                    const itype_id seed = options.get_seed();
                    // If its a farm zone with no specified seed, and we've checked for tilling and harvesting.
                    // then it means no further work can be done here
                    if( seed.is_empty() ) {
                        return activity_reason_info::fail( do_activity_reason::ALREADY_DONE );
                    }
                    std::vector<item *> seed_inv = p.items_with( []( const item & itm ) {
                        return itm.is_seed();
                    } );
                    for( const auto elem : seed_inv ) {
                        if( elem->typeId() == itype_id( seed ) ) {
                            return activity_reason_info::ok( do_activity_reason::NEEDS_PLANTING );
                        }
                    }
                    // didn't find the seed, but maybe there are overlapping farm zones
                    // and another of the zones is for a seed that we have
                    // so loop again, and return false once all zones done.
                }
            } else {
                // can't plant, till or harvest
                return activity_reason_info::fail( do_activity_reason::ALREADY_DONE );
            }
        }
        // looped through all zones, and only got here if its plantable, but have no seeds.
        return activity_reason_info::fail( do_activity_reason::NEEDS_PLANTING );
    } else if( act == ACT_FETCH_REQUIRED ) {
        // we check if its possible to get all the requirements for fetching at two other places.
        // 1. before we even assign the fetch activity and;
        // 2. when we form the src_set to loop through at the beginning of the fetch activity.
        return activity_reason_info::ok( do_activity_reason::CAN_DO_FETCH );
    }
    // Shouldn't get here because the zones were checked previously. if it does, set enum reason as "no zone"
    return activity_reason_info::fail( do_activity_reason::NO_ZONE );
}
References act, ACT_FETCH_REQUIRED, ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_CONSTRUCTION, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_MULTIPLE_MINE, ACT_TIDY_UP, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, Character::activity_vehicle_part_index, ALREADY_DONE, ALREADY_WORKING, item::ammo_sufficient(), any, Character::best_nearby_lifting_assist(), BLOCKING_TILE, activity_reason_info::build(), CAN_DO_FETCH, player::can_lift(), vehicle::can_unmount(), itype::can_use(), corpse, Character::crafting_inventory(), item_stack::empty(), activity_reason_info::fail(), detail::find(), find_base_construction(), flag_BUTCHER_EQ(), flag_DIG_TOOL(), flag_FISH_GOOD(), flag_FISH_POOR(), flag_FISHABLE(), flag_GROWTH_HARVEST(), flag_PLANTABLE(), flag_PLOWABLE(), flag_TREE(), g, constructions::get_all_sorted(), zone_manager::get_manager(), get_map(), vehicle::get_parts_at(), zone_manager::get_zones(), map::getabs(), map::getlocal(), item::has_flag(), map::has_flag(), map::has_flag_furn(), map::has_flag_ter_or_furn(), map::has_furn(), visitable< T >::has_item_with(), map::has_items(), zone_manager::has_near(), map::has_nearby_table(), visitable< T >::has_quality(), has_skill_for_vehicle_work(), map::i_at(), partial_con::id, vehicle::index_of_part(), Character::invalidate_crafting_inventory(), is_crafting_component(), player::is_npc(), item::is_seed(), item::is_wheel(), vpart_info::item, visitable< T >::items_with(), itype_log, item::lift_strength(), MS_MEDIUM, vpart_info::name(), NEEDS_BIG_BUTCHERING, NEEDS_BUTCHERING, NEEDS_CHOPPING, NEEDS_FISHING, NEEDS_HARVESTING, NEEDS_MINING, NEEDS_PLANTING, NEEDS_TILLING, NEEDS_TREE_CHOPPING, NEEDS_VEH_DECONST, NEEDS_VEH_REPAIR, NO_ZONE, activity_reason_info::ok(), PATH_INFO::options(), map::partial_con_at(), PICKUP_RANGE, vehicle::player_in_control(), map::points_in_radius(), qual_AXE, qual_BUTCHER, qual_DIG, vpart_info::removal_requirements(), vpart_info::removal_skills, vpart_info::repair_requirements(), vpart_info::repair_skills, iuse::seed(), Creature::set_value(), t_stump, t_trunk, map::ter(), TOOL_LIFT_FACTOR, tripoint_min, tripoint_zero, item::type, map::veh_at(), veh_pointer_or_null(), vehicle::velocity, warm_enough_to_plant(), item::weight(), z_camp_storage, zone_type_CONSTRUCTION_BLUEPRINT, zone_type_FARM_PLOT, and zone_type_LOOT_UNSORTED.
Referenced by generic_multi_activity_handler().
cancel_aim_processing()
void cancel_aim_processing ()
Definition at line 1928 of file advanced_inv.cpp.
{
    uistate.transfer_save.re_enter_move_all = ENTRY_START;
}
References ENTRY_START, advanced_inv_save_state::re_enter_move_all, uistatedata::transfer_save, and uistate.
Referenced by pickup_activity_actor::do_turn().
check_npc_revert()
static void check_npc_revert (player & p) static
Definition at line 2466 of file activity_item_handling.cpp.
{
    if( p.is_npc() ) {
        npc *guy = dynamic_cast<npc *>( &p );
        if( guy ) {
            guy->revert_after_activity();
        }
    }
}
References player::is_npc(), and npc::revert_after_activity().
Referenced by generic_multi_activity_check_requirement(), and generic_multi_activity_handler().
chop_plank_activity()
static bool chop_plank_activity (player & p, const tripoint & src_loc) static
Definition at line 2114 of file activity_item_handling.cpp.
{
    item *best_qual = p.best_quality_item( qual_AXE );
    if( !best_qual ) {
        return false;
    }
    if( best_qual->type->can_have_charges() ) {
        p.consume_charges( *best_qual, best_qual->type->charges_to_use() );
    }
    map &here = get_map();
    for( auto &i : here.i_at( src_loc ) ) {
        if( i.typeId() == itype_log ) {
            here.i_rem( src_loc, &i );
            int moves = to_moves<int>( 20_minutes );
            p.add_msg_if_player( _( "You cut the log into planks." ) );
            p.assign_activity( ACT_CHOP_PLANKS, moves, -1 );
            p.activity.placement = here.getabs( src_loc );
            return true;
        }
    }
    return false;
}
References _, ACT_CHOP_PLANKS, Character::activity, player::add_msg_if_player(), Character::assign_activity(), Character::best_quality_item(), itype::can_have_charges(), itype::charges_to_use(), Character::consume_charges(), get_map(), map::getabs(), map::i_at(), map::i_rem(), itype_log, player_activity::placement, qual_AXE, and item::type.
Referenced by generic_multi_activity_do().
chop_tree_activity()
static bool chop_tree_activity (player & p, const tripoint & src_loc) static
Definition at line 2442 of file activity_item_handling.cpp.
{
    item *best_qual = p.best_quality_item( qual_AXE );
    if( !best_qual ) {
        return false;
    }
    int moves = iuse::chop_moves( p, *best_qual );
    if( best_qual->type->can_have_charges() ) {
        p.consume_charges( *best_qual, best_qual->type->charges_to_use() );
    }
    map &here = get_map();
    const ter_id ter = here.ter( src_loc );
    if( here.has_flag( flag_TREE, src_loc ) ) {
        p.assign_activity( ACT_CHOP_TREE, moves, -1, p.get_item_position( best_qual ) );
        p.activity.placement = here.getabs( src_loc );
        return true;
    } else if( ter == t_trunk || ter == t_stump ) {
        p.assign_activity( ACT_CHOP_LOGS, moves, -1, p.get_item_position( best_qual ) );
        p.activity.placement = here.getabs( src_loc );
        return true;
    }
    return false;
}
References ACT_CHOP_LOGS, ACT_CHOP_TREE, Character::activity, Character::assign_activity(), Character::best_quality_item(), itype::can_have_charges(), itype::charges_to_use(), iuse::chop_moves(), Character::consume_charges(), flag_TREE(), Character::get_item_position(), get_map(), map::getabs(), map::has_flag(), player_activity::placement, qual_AXE, t_stump, t_trunk, map::ter(), and item::type.
Referenced by generic_multi_activity_do().
construction_activity()
static bool construction_activity (player & p, const zone_data * , const tripoint & src_loc, const activity_reason_info & act_info, const activity_id & activity_to_restore) static
Definition at line 1909 of file activity_item_handling.cpp.
{
    // the actual desired construction
    if( !act_info.con_idx ) {
        debugmsg( "no construction selected" );
        return false;
    }
    const construction &built_chosen = act_info.con_idx->obj();
    std::list<item> used;
    // create the partial construction struct
    partial_con pc;
    pc.id = built_chosen.id;
    pc.counter = 0;
    map &here = get_map();
    // Set the trap that has the examine function
    if( here.tr_at( src_loc ).loadid == tr_null ) {
        here.trap_set( src_loc, tr_unfinished_construction );
    }
    // Use up the components
    for( const std::vector<item_comp> &it : built_chosen.requirements->get_components() ) {
        std::list<item> tmp = p.consume_items( it, 1, is_crafting_component );
        used.splice( used.end(), tmp );
    }
    pc.components = used;
    here.partial_con_set( src_loc, pc );
    for( const std::vector<tool_comp> &it : built_chosen.requirements->get_tools() ) {
        p.consume_tools( it );
    }
    p.backlog.push_front( activity_to_restore );
    p.assign_activity( ACT_BUILD );
    p.activity.placement = here.getabs( src_loc );
    return true;
}
References ACT_BUILD, Character::activity, Character::assign_activity(), Character::backlog, partial_con::components, activity_reason_info::con_idx, player::consume_items(), player::consume_tools(), partial_con::counter, debugmsg, requirement_data::get_components(), get_map(), requirement_data::get_tools(), map::getabs(), construction::id, partial_con::id, is_crafting_component(), trap::loadid, map::partial_con_set(), player_activity::placement, construction::requirements, map::tr_at(), tr_null, tr_unfinished_construction, and map::trap_set().
Referenced by generic_multi_activity_do().
convert_to_items()
static std::list< pickup::act_item > convert_to_items (Character & p, const drop_locations & drop, std::function< bool(item_location loc)> filter) static
Definition at line 411 of file activity_item_handling.cpp.
{
    std::list<pickup::act_item> res;
    for( const drop_location &rec : drop ) {
        const item_location loc = rec.loc;
        const int count = rec.count;
        if( !filter( loc ) ) {
            continue;
        } else if( !p.is_worn( *loc ) && !p.is_wielding( *loc ) ) {
            // Special case. After dropping the first few items, the remaining items are already separated.
            // That means: `drop` already contains references to each of the items in
            // `p.inv.const_stack`, and `count` will be 1 for each of them.
            // If we continued without this check, we iterate over `p.inv.const_stack` multiple times,
            // but each time stopping after visiting the first item.
            // In the end, we would add references to the same item (the first one in the stack) multiple times.
            if( count == 1 ) {
                res.emplace_back( loc, 1, loc.obtain_cost( p, 1 ) );
                continue;
            }
            int obtained = 0;
            for( const item &it : p.inv.const_stack( p.get_item_position( &*loc ) ) ) {
                if( obtained >= count ) {
                    break;
                }
                const int qty = it.count_by_charges() ? std::min<int>( it.charges, count - obtained ) : 1;
                obtained += qty;
                item_location loc( p, const_cast<item *>( &it ) );
                res.emplace_back( loc, qty, loc.obtain_cost( p, qty ) );
            }
        } else {
            res.emplace_back( loc, count, p.is_wielding( *loc ) ? 0 : loc.obtain_cost( p ) );
        }
    }
    return res;
}
References inventory::const_stack(), detail::count(), Character::get_item_position(), Character::inv, Character::is_wielding(), Character::is_worn(), and item_location::obtain_cost().
Referenced by pickup::reorder_for_dropping().
debug_drop_list()
static void debug_drop_list (const std::list< pickup::act_item > & list) static
Definition at line 646 of file activity_item_handling.cpp.
{
    if( !debug_mode ) {
        return;
    }
    std::string res( "Items ordered to drop:\n" );
    for( const auto &ait : list ) {
        res += string_format( "Drop %d %s for %d moves\n",
                              ait.count, ait.loc->display_name( ait.count ), ait.consumed_moves );
    }
    popup( res, PF_GET_KEY );
}
References debug_mode, PF_GET_KEY, popup(), and string_format().
Referenced by obtain_activity_items().
debug_tokens()
static void debug_tokens (const std::list< item > & items) static
Definition at line 660 of file activity_item_handling.cpp.
{
    if( !debug_mode ) {
        return;
    }
    std::stringstream ss;
    ss << "Item tokens:\n";
    for( const item &it : items ) {
        ss << it.display_name() << ": " << *it.drop_token << '\n';
    }
    popup( ss.str(), PF_GET_KEY );
}
References debug_mode, PF_GET_KEY, and popup().
Referenced by obtain_activity_items().
drop_on_map()
void drop_on_map (Character & c, item_drop_reason reason, const std::list< item > & items, const tripoint & where)
Definition at line 306 of file activity_item_handling.cpp.
{
    if( items.empty() ) {
        return;
    }
    map &here = get_map();
    const std::string ter_name = here.name( where );
    const bool can_move_there = here.passable( where );
    if( same_type( items ) ) {
        const item &it = items.front();
        const int dropcount = items.size() * it.count();
        const std::string it_name = it.tname( dropcount );
        switch( reason ) {
            case item_drop_reason::deliberate:
                if( can_move_there ) {
                    c.add_msg_player_or_npc(
                        vgettext( "You drop your %1$s on the %2$s.",
                                  "You drop your %1$s on the %2$s.", dropcount ),
                        vgettext( "<npcname> drops their %1$s on the %2$s.",
                                  "<npcname> drops their %1$s on the %2$s.", dropcount ),
                        it_name, ter_name
                    );
                } else {
                    c.add_msg_player_or_npc(
                        vgettext( "You put your %1$s in the %2$s.",
                                  "You put your %1$s in the %2$s.", dropcount ),
                        vgettext( "<npcname> puts their %1$s in the %2$s.",
                                  "<npcname> puts their %1$s in the %2$s.", dropcount ),
                        it_name, ter_name
                    );
                }
                break;
            case item_drop_reason::too_large:
                c.add_msg_if_player(
                    vgettext( "There's no room in your inventory for the %s, so you drop it.",
                              "There's no room in your inventory for the %s, so you drop them.", dropcount ),
                    it_name
                );
                break;
            case item_drop_reason::too_heavy:
                c.add_msg_if_player(
                    vgettext( "The %s is too heavy to carry, so you drop it.",
                              "The %s is too heavy to carry, so you drop them.", dropcount ),
                    it_name
                );
                break;
            case item_drop_reason::tumbling:
                c.add_msg_if_player(
                    m_bad,
                    vgettext( "Your %1$s tumbles to the %2$s.",
                              "Your %1$s tumble to the %2$s.", dropcount ),
                    it_name, ter_name
                );
                break;
        }
    } else {
        switch( reason ) {
            case item_drop_reason::deliberate:
                if( can_move_there ) {
                    c.add_msg_player_or_npc(
                        _( "You drop several items on the %s." ),
                        _( "<npcname> drops several items on the %s." ),
                        ter_name
                    );
                } else {
                    c.add_msg_player_or_npc(
                        _( "You put several items in the %s." ),
                        _( "<npcname> puts several items in the %s." ),
                        ter_name
                    );
                }
                break;
            case item_drop_reason::too_large:
            case item_drop_reason::too_heavy:
            case item_drop_reason::tumbling:
                c.add_msg_if_player( m_bad, _( "Some items tumble to the %s." ), ter_name );
                break;
        }
    }
    for( auto &it : items ) {
        here.add_item_or_charges( where, it );
        pass_to_ownership_handling( it, c );
    }
}
References _, map::add_item_or_charges(), c, item::count(), deliberate, get_map(), m_bad, map::name(), pass_to_ownership_handling(), map::passable(), same_type(), item::tname(), too_heavy, too_large, tumbling, and vgettext().
Referenced by butchery_drops_harvest(), move_items_activity_actor::do_turn(), extract_or_wreck_cbms(), and put_into_vehicle_or_drop().
fetch_activity()
static bool fetch_activity (player & p, const tripoint & src_loc, const activity_id & activity_to_restore, const int distance = ACTIVITY_SEARCH_DISTANCE) static
Definition at line 1999 of file activity_item_handling.cpp.
{
    map &here = get_map();
    if( !here.can_put_items_ter_furn( here.getlocal( p.backlog.front().coords.back() ) ) ) {
        return false;
    }
    const std::vector<std::tuple<tripoint, itype_id, int>> mental_map_2 = requirements_map( p,
            distance );
    int pickup_count = 1;
    auto items_there = here.i_at( src_loc );
    vehicle *src_veh = nullptr;
    int src_part = 0;
    if( const cata::optional<vpart_reference> vp = here.veh_at( src_loc ).part_with_feature( "CARGO",
            false ) ) {
        src_veh = &vp->vehicle();
        src_part = vp->part_index();
    }
    const units::volume volume_allowed = p.volume_capacity() - p.volume_carried();
    const units::mass weight_allowed = p.weight_capacity() - p.weight_carried();
    // TODO: vehicle_stack and map_stack into one loop.
    if( src_veh ) {
        for( auto &veh_elem : src_veh->get_items( src_part ) ) {
            for( auto elem : mental_map_2 ) {
                if( std::get<0>( elem ) == src_loc && veh_elem.typeId() == std::get<1>( elem ) ) {
                    if( !p.backlog.empty() && p.backlog.front().id() == ACT_MULTIPLE_CONSTRUCTION ) {
                        move_item( p, veh_elem, veh_elem.count_by_charges() ? std::get<2>( elem ) : 1, src_loc,
                                   here.getlocal( p.backlog.front().coords.back() ), src_veh, src_part, activity_to_restore );
                        return true;
                    }
                }
            }
        }
    }
    for( auto item_iter = items_there.begin(); item_iter != items_there.end(); item_iter++ ) {
        item &it = *item_iter;
        for( auto elem : mental_map_2 ) {
            if( std::get<0>( elem ) == src_loc && it.typeId() == std::get<1>( elem ) ) {
                // construction/crafting tasks want the required item moved near the work spot.
                if( !p.backlog.empty() && p.backlog.front().id() == ACT_MULTIPLE_CONSTRUCTION ) {
                    move_item( p, it, it.count_by_charges() ? std::get<2>( elem ) : 1, src_loc,
                               here.getlocal( p.backlog.front().coords.back() ), src_veh, src_part, activity_to_restore );
                    return true;
                    // other tasks want the tool picked up
                } else if( !p.backlog.empty() && ( p.backlog.front().id() == ACT_MULTIPLE_FARM ||
                                                   p.backlog.front().id() == ACT_MULTIPLE_CHOP_PLANKS ||
                                                   p.backlog.front().id() == ACT_VEHICLE_DECONSTRUCTION ||
                                                   p.backlog.front().id() == ACT_VEHICLE_REPAIR ||
                                                   p.backlog.front().id() == ACT_MULTIPLE_BUTCHER ||
                                                   p.backlog.front().id() == ACT_MULTIPLE_CHOP_TREES ||
                                                   p.backlog.front().id() == ACT_MULTIPLE_FISH ||
                                                   p.backlog.front().id() == ACT_MULTIPLE_MINE ) ) {
                    if( it.volume() > volume_allowed || it.weight() > weight_allowed ) {
                        continue;
                    }
                    item leftovers = it;
                    if( pickup_count != 1 && it.count_by_charges() ) {
                        // Reinserting leftovers happens after item removal to avoid stacking issues.
                        leftovers.charges = it.charges - pickup_count;
                        if( leftovers.charges > 0 ) {
                            it.charges = pickup_count;
                        }
                    } else {
                        leftovers.charges = 0;
                    }
                    it.set_var( "activity_var", p.name );
                    const std::string item_name = it.tname();
                    p.i_add( it );
                    if( p.is_npc() ) {
                        if( pickup_count == 1 ) {
                            add_msg( _( "%1$s picks up a %2$s." ), p.disp_name(), item_name );
                        } else {
                            add_msg( _( "%s picks up several items." ),  p.disp_name() );
                        }
                    }
                    items_there.erase( item_iter );
                    // If we didn't pick up a whole stack, put the remainder back where it came from.
                    if( leftovers.charges > 0 ) {
                        here.add_item_or_charges( src_loc, leftovers );
                    }
                    return true;
                }
            }
        }
    }
    // if we got here, then the fetch failed for reasons that werent predicted before setting it.
    // nothing was moved or picked up, and nothing can be moved or picked up
    // so call the whole thing off to stop it looping back to this point ad nauseum.
    p.set_moves( 0 );
    p.activity = player_activity();
    p.backlog.clear();
    return false;
}
References _, ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_CONSTRUCTION, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_MULTIPLE_MINE, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, Character::activity, map::add_item_or_charges(), add_msg(), Character::backlog, map::can_put_items_ter_furn(), item::charges, item::count_by_charges(), Character::disp_name(), vehicle::get_items(), get_map(), map::getlocal(), Character::i_add(), map::i_at(), player::is_npc(), move_item(), Character::name, optional_vpart_position::part_with_feature(), requirements_map(), Creature::set_moves(), item::set_var(), item::tname(), item::typeId(), map::veh_at(), vehicle::vehicle(), item::volume(), Character::volume_capacity(), Character::volume_carried(), item::weight(), Character::weight_capacity(), and Character::weight_carried().
Referenced by generic_multi_activity_do().
find_auto_consume()
bool find_auto_consume (player & p, const bool food)
Definition at line 3136 of file activity_item_handling.cpp.
{
    // return false if there is no point searching again while the activity is still happening.
    if( p.is_npc() ) {
        return false;
    }
    if( p.has_effect( effect_nausea ) ) {
        return true;
    }
    static const std::string flag_MELTS( "MELTS" );
    static const std::string flag_EDIBLE_FROZEN( "EDIBLE_FROZEN" );
    const tripoint pos = p.pos();
    map &here = get_map();
    zone_manager &mgr = zone_manager::get_manager();
    zone_type_id consume_type_zone( "" );
    if( food ) {
        consume_type_zone = zone_type_id( "AUTO_EAT" );
    } else {
        consume_type_zone = zone_type_id( "AUTO_DRINK" );
    }
    if( here.check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    const std::unordered_set<tripoint> &dest_set = mgr.get_near( consume_type_zone, here.getabs( pos ),
            ACTIVITY_SEARCH_DISTANCE );
    if( dest_set.empty() ) {
        return false;
    }
    for( const tripoint loc : dest_set ) {
        if( loc.z != p.pos().z ) {
            continue;
        }
        const optional_vpart_position vp = here.veh_at( g->m.getlocal( loc ) );
        std::vector<item *> items_here;
        if( vp ) {
            vehicle &veh = vp->vehicle();
            int index = veh.part_with_feature( vp->part_index(), "CARGO", false );
            if( index >= 0 ) {
                vehicle_stack vehitems = veh.get_items( index );
                for( item &it : vehitems ) {
                    items_here.push_back( &it );
                }
            }
        } else {
            map_stack mapitems = here.i_at( here.getlocal( loc ) );
            for( item &it : mapitems ) {
                items_here.push_back( &it );
            }
        }
        for( item *it : items_here ) {
            item &comest = p.get_consumable_from( *it );
            if( comest.is_null() || comest.is_craft() || !comest.is_food() ||
                p.fun_for( comest ).first < -5 ) {
                // not good eatings.
                continue;
            }
            if( !p.can_consume( *it ) ) {
                continue;
            }
            if( food && p.compute_effective_nutrients( comest ).kcal < 50 ) {
                // not filling enough
                continue;
            }
            if( !p.will_eat( comest, false ).success() ) {
                // wont like it, cannibal meat etc
                continue;
            }
            if( !it->is_owned_by( p, true ) ) {
                // it aint ours.
                continue;
            }
            if( !food && comest.get_comestible()->quench < 15 ) {
                // not quenching enough
                continue;
            }
            if( comest.has_flag( flag_UNSAFE_CONSUME ) ) {
                // Unsafe to drink or eat
                continue;
            }
            if( !food && it->is_watertight_container() && it->contents_made_of( SOLID ) ) {
                // its frozen
                continue;
            }
            p.mod_moves( -pickup::cost_to_move_item( p, *it ) * std::max( rl_dist( p.pos(),
                         here.getlocal( loc ) ), 1 ) );
            item_location item_loc;
            if( vp ) {
                item_loc = item_location( vehicle_cursor( vp->vehicle(), vp->part_index() ), &comest );
            } else {
                item_loc = item_location( map_cursor( here.getlocal( loc ) ), &comest );
            }
            avatar_action::eat( g->u, item_loc );
            // eat() may have removed the item, so check its still there.
            if( item_loc.get_item() && item_loc->is_container() ) {
                item_loc->on_contents_changed();
            }
            return true;
        }
    }
    return false;
}
References ACTIVITY_SEARCH_DISTANCE, zone_manager::cache_vzones(), Character::can_consume(), map::check_vehicle_zones(), Character::compute_effective_nutrients(), item::contents_made_of(), pickup::cost_to_move_item(), avatar_action::eat(), effect_nausea, flag_UNSAFE_CONSUME(), Character::fun_for(), g, item::get_comestible(), Character::get_consumable_from(), item_location::get_item(), vehicle::get_items(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), map::getabs(), map::getlocal(), Creature::has_effect(), item::has_flag(), map::i_at(), item::is_container(), item::is_craft(), item::is_food(), player::is_npc(), item::is_null(), item::is_owned_by(), item::is_watertight_container(), nutrients::kcal, Creature::mod_moves(), item::on_contents_changed(), vehicle::part_with_feature(), Character::pos(), rl_dist(), SOLID, map::veh_at(), Character::will_eat(), and tripoint::z.
Referenced by player_activity::do_turn().
find_base_construction()
static activity_reason_info find_base_construction (const std::vector< construction_id > & list_constructions, player & p, const inventory & inv, const tripoint & loc, const cata::optional< construction_id > & part_con_id, const construction_id id, std::set< construction_id > & used) static
Definition at line 1049 of file activity_item_handling.cpp.
{
    const construction &build = id.obj();
    //already done?
    map &here = get_map();
    const furn_id furn = here.furn( loc );
    const ter_id ter = here.ter( loc );
    if(
        ( !build.post_terrain.is_empty() && build.post_terrain.id() == ter ) ||
        ( !build.post_furniture.is_empty() && build.post_furniture.id() == furn )
    ) {
        return activity_reason_info::build( do_activity_reason::ALREADY_DONE, false, id );
    }
    //if there's an appropriate partial construction on the tile, then we can work on it, no need to check inventories.
    const bool has_skill = p.meets_skill_requirements( build );
    if( part_con_id && *part_con_id == id ) {
        if( !has_skill ) {
            return activity_reason_info::build( do_activity_reason::DONT_HAVE_SKILL, false, id );
        }
        return activity_reason_info::build( do_activity_reason::CAN_DO_CONSTRUCTION, true, id );
    }
    //can build?
    const bool cc = can_construct( build, loc );
    const bool pcb = player_can_build( p, inv, build );
    if( !has_skill ) {
        return activity_reason_info::build( do_activity_reason::DONT_HAVE_SKILL, false, id );
    }
    if( cc ) {
        if( pcb ) {
            return activity_reason_info::build( do_activity_reason::CAN_DO_CONSTRUCTION, true, id );
        }
        //can't build with current inventory, do not look for pre-req
        return activity_reason_info::build( do_activity_reason::NO_COMPONENTS, false, id );
    }
    // there are no pre-requisites.
    // so we need to potentially fetch components
    if( build.pre_terrain.is_empty() && build.pre_furniture.is_empty() && build.pre_special( loc ) ) {
        return activity_reason_info::build( do_activity_reason::NO_COMPONENTS, false, id );
    } else if( !build.pre_special( loc ) ) {
        return activity_reason_info::build( do_activity_reason::BLOCKING_TILE, false, id );
    }
    // can't build it
    // maybe we can build the pre-requisite instead
    // see if the reason is because of pre-terrain requirement
    /*
    if( !build.pre_terrain.empty() &&
        ( ( build.pre_is_furniture &&
            furn_id( build.pre_terrain ) == furn ) ||
          ( !build.pre_is_furniture &&
            ter_id( build.pre_terrain ) == ter ) ) ) {
        // the pre-req is already built, so the reason is due to lack of tools/components
        return activity_reason_info::build( do_activity_reason::NO_COMPONENTS, false, idx );
    }
    */
    //we can't immediately build it, looking for pre-req
    used.insert( id );
    cata::optional<do_activity_reason> reason;
    construction_id pre_req_idx( -1 );
    //first step: try only constructions with the same group
    //second step: try all constructions
    for( int try_num = 0; try_num < 2; ++try_num ) {
        for( const construction_id &pre_build : list_constructions ) {
            //skip if already checked this one
            if( pre_build == id || used.find( pre_build ) != used.end() ) {
                continue;
            }
            //skip unknown
            /*
            if( pre_build.post_terrain.empty() ) {
                continue;
            }
            //skip if it is not a pre-build required or gives the same result
            if( pre_build.post_terrain != build.pre_terrain &&
                pre_build.post_terrain != build.post_terrain ) {
                continue;
            }
            */
            //at first step, try to get building with the same group
            if( try_num == 0 &&
                pre_build->group != build.group ) {
                continue;
            }
            activity_reason_info act_info_pre = find_base_construction( list_constructions,
                                                p, inv, loc, part_con_id, pre_build, used );
            if( act_info_pre.can_do ) {
                return activity_reason_info::build( do_activity_reason::CAN_DO_PREREQ, true,
                                                    *act_info_pre.con_idx );
            }
            //find first pre-req failed reason
            if( !reason ) {
                reason = act_info_pre.reason;
                pre_req_idx = *act_info_pre.con_idx;
            }
            if( act_info_pre.reason == do_activity_reason::ALREADY_DONE ) {
                //pre-req is already here, but we still can't build over it
                reason.reset();
                break;
            }
        }
    }
    //have a partial construction which is not leading to the required construction
    if( part_con_id ) {
        return activity_reason_info::build( do_activity_reason::BLOCKING_TILE, false, id );
    }
    //pre-req failed?
    if( reason ) {
        if( *reason == do_activity_reason::NO_COMPONENTS ) {
            return activity_reason_info::build( do_activity_reason::NO_COMPONENTS_PREREQ, false, pre_req_idx );
        }
        return activity_reason_info::build( *reason, false, pre_req_idx );
    }
    if( !pcb ) {
        return activity_reason_info::build( do_activity_reason::NO_COMPONENTS, false, id );
    }
    //only cc failed, no pre-req
    return activity_reason_info::build( do_activity_reason::BLOCKING_TILE, false, id );
}
References ALREADY_DONE, BLOCKING_TILE, activity_reason_info::build(), can_construct(), activity_reason_info::can_do, CAN_DO_CONSTRUCTION, CAN_DO_PREREQ, activity_reason_info::con_idx, DONT_HAVE_SKILL, find_base_construction(), map::furn(), get_map(), construction::group, string_id< T >::id(), string_id< T >::is_empty(), Character::meets_skill_requirements(), NO_COMPONENTS, NO_COMPONENTS_PREREQ, player_can_build(), construction::post_furniture, construction::post_terrain, construction::pre_furniture, construction::pre_special, construction::pre_terrain, activity_reason_info::reason, cata::optional< T >::reset(), and map::ter().
Referenced by can_do_activity_there(), and find_base_construction().
find_best_fire()
static cata::optional< tripoint > find_best_fire (const std::vector< tripoint > & from, const tripoint & center) static
Definition at line 3064 of file activity_item_handling.cpp.
{
    cata::optional<tripoint> best_fire;
    time_duration best_fire_age = 1_days;
    map &here = get_map();
    for( const tripoint &pt : from ) {
        field_entry *fire = here.get_field( pt, fd_fire );
        if( fire == nullptr || fire->get_field_intensity() > 1 ||
            !here.clear_path( center, pt, PICKUP_RANGE, 1, 100 ) ) {
            continue;
        }
        time_duration fire_age = fire->get_field_age();
        // Refuel only the best fueled fire (if it needs it)
        if( fire_age < best_fire_age ) {
            best_fire = pt;
            best_fire_age = fire_age;
        }
        // If a contained fire exists, ignore any other fires
        if( here.has_flag_furn( TFLAG_FIRE_CONTAINER, pt ) ) {
            return pt;
        }
    }
    return best_fire;
}
References center, map::clear_path(), fd_fire, fire(), map::get_field(), get_map(), map::has_flag_furn(), PICKUP_RANGE, and TFLAG_FIRE_CONTAINER.
Referenced by try_fuel_fire().
find_refuel_spot_trap()
static cata::optional< tripoint > find_refuel_spot_trap (const std::vector< tripoint > & from, const tripoint & center) static
Definition at line 3120 of file activity_item_handling.cpp.
{
    const auto tile = std::find_if( from.begin(), from.end(), [center]( const tripoint & pt ) {
        // Hacky - firewood spot is a trap and it's ID-checked
        return get_map().tr_at( pt ).id == tr_firewood_source
               && has_clear_path_to_pickup_items( center, pt );
    } );
    if( tile != from.end() ) {
        return *tile;
    }
    return {};
}
References center.
Referenced by try_fuel_fire().
find_refuel_spot_zone()
static cata::optional< tripoint > find_refuel_spot_zone (const tripoint & center) static
Definition at line 3099 of file activity_item_handling.cpp.
{
    const zone_manager &mgr = zone_manager::get_manager();
    map &here = get_map();
    const tripoint center_abs = here.getabs( center );
    const std::unordered_set<tripoint> &tiles_abs_unordered =
        mgr.get_near( zone_type_source_firewood, center_abs, PICKUP_RANGE );
    const std::vector<tripoint> &tiles_abs =
        get_sorted_tiles_by_distance( center_abs, tiles_abs_unordered );
    for( const tripoint &tile_abs : tiles_abs ) {
        const tripoint tile = here.getlocal( tile_abs );
        if( has_clear_path_to_pickup_items( center, tile ) ) {
            return tile;
        }
    }
    return {};
}
References center, zone_manager::get_manager(), get_map(), zone_manager::get_near(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), has_clear_path_to_pickup_items(), PICKUP_RANGE, and zone_type_source_firewood.
Referenced by try_fuel_fire().
flag_BUTCHER_EQ()
static const std::string flag_BUTCHER_EQ ("BUTCHER_EQ") static
Referenced by can_do_activity_there().
flag_DIG_TOOL()
static const std::string flag_DIG_TOOL ("DIG_TOOL") static
Referenced by can_do_activity_there(), and mine_activity().
flag_FISH_GOOD()
static const std::string flag_FISH_GOOD ("FISH_GOOD") static
Referenced by can_do_activity_there().
flag_FISH_POOR()
static const std::string flag_FISH_POOR ("FISH_POOR") static
Referenced by can_do_activity_there().
flag_FISHABLE()
static const std::string flag_FISHABLE ("FISHABLE") static
Referenced by can_do_activity_there().
flag_GROWTH_HARVEST()
static const std::string flag_GROWTH_HARVEST ("GROWTH_HARVEST") static
Referenced by can_do_activity_there(), and generic_multi_activity_do().
flag_PLANT()
static const std::string flag_PLANT ("PLANT") static
Referenced by generic_multi_activity_locations().
flag_PLANTABLE()
static const std::string flag_PLANTABLE ("PLANTABLE") static
Referenced by can_do_activity_there(), and generic_multi_activity_do().
flag_PLOWABLE()
static const std::string flag_PLOWABLE ("PLOWABLE") static
Referenced by can_do_activity_there(), and generic_multi_activity_do().
flag_TREE()
static const std::string flag_TREE ("TREE") static
Referenced by can_do_activity_there(), and chop_tree_activity().
flag_UNSAFE_CONSUME()
static const std::string flag_UNSAFE_CONSUME ("UNSAFE_CONSUME") static
Referenced by find_auto_consume().
generic_multi_activity_check_requirement()
static requirement_check_result generic_multi_activity_check_requirement (player & p, const activity_id & act_id, activity_reason_info & act_info, const tripoint & src, const tripoint & src_loc, const std::unordered_set< tripoint > & src_set, const bool check_only = false) static
Check if this activity can not be done immediately because it has some requirements.
Definition at line 2636 of file activity_item_handling.cpp.
{
    map &here = get_map();
    const tripoint abspos = here.getabs( p.pos() );
    zone_manager &mgr = zone_manager::get_manager();
    bool &can_do_it = act_info.can_do;
    const do_activity_reason &reason = act_info.reason;
    const zone_data *zone = mgr.get_zone_at( src, get_zone_for_act( src_loc, mgr, act_id ) );
    const bool needs_to_be_in_zone = act_id == ACT_FETCH_REQUIRED ||
                                     act_id == ACT_MULTIPLE_FARM ||
                                     act_id == ACT_MULTIPLE_BUTCHER ||
                                     act_id == ACT_MULTIPLE_CHOP_PLANKS ||
                                     act_id == ACT_MULTIPLE_CHOP_TREES ||
                                     act_id == ACT_VEHICLE_DECONSTRUCTION ||
                                     act_id == ACT_VEHICLE_REPAIR ||
                                     act_id == ACT_MULTIPLE_FISH ||
                                     act_id == ACT_MULTIPLE_MINE ||
                                     ( act_id == ACT_MULTIPLE_CONSTRUCTION &&
                                       !here.partial_con_at( src_loc ) );
    // some activities require the target tile to be part of a zone.
    // tidy up activity doesn't - it wants things that may not be in a zone already - things that may have been left lying around.
    if( needs_to_be_in_zone && !zone ) {
        can_do_it = false;
        return SKIP_LOCATION;
    }
    if( can_do_it ) {
        return CAN_DO_LOCATION;
    }
    if( reason == do_activity_reason::DONT_HAVE_SKILL ||
        reason == do_activity_reason::NO_ZONE ||
        reason == do_activity_reason::ALREADY_DONE ||
        reason == do_activity_reason::BLOCKING_TILE ||
        reason == do_activity_reason::UNKNOWN_ACTIVITY ) {
        // we can discount this tile, the work can't be done.
        if( reason == do_activity_reason::DONT_HAVE_SKILL ) {
            p.add_msg_if_player( m_info, _( "You don't have the skill for this task." ) );
        } else if( reason == do_activity_reason::BLOCKING_TILE ) {
            p.add_msg_if_player( m_info, _( "There is something blocking the location for this task." ) );
        }
        return SKIP_LOCATION;
    } else if( reason == do_activity_reason::NO_COMPONENTS ||
               reason == do_activity_reason::NO_COMPONENTS_PREREQ ||
               reason == do_activity_reason::NO_COMPONENTS_PREREQ_2 ||
               reason == do_activity_reason::NEEDS_PLANTING ||
               reason == do_activity_reason::NEEDS_TILLING ||
               reason == do_activity_reason::NEEDS_CHOPPING ||
               reason == do_activity_reason::NEEDS_BUTCHERING ||
               reason == do_activity_reason::NEEDS_BIG_BUTCHERING ||
               reason == do_activity_reason::NEEDS_VEH_DECONST ||
               reason == do_activity_reason::NEEDS_VEH_REPAIR ||
               reason == do_activity_reason::NEEDS_TREE_CHOPPING ||
               reason == do_activity_reason::NEEDS_FISHING || reason == do_activity_reason::NEEDS_MINING ) {
        // we can do it, but we need to fetch some stuff first
        // before we set the task to fetch components - is it even worth it? are the components anywhere?
        requirement_id what_we_need;
        std::vector<tripoint> loot_zone_spots;
        std::vector<tripoint> combined_spots;
        for( const tripoint &elem : mgr.get_point_set_loot( abspos, ACTIVITY_SEARCH_DISTANCE,
                p.is_npc() ) ) {
            loot_zone_spots.push_back( elem );
            combined_spots.push_back( elem );
        }
        for( const tripoint &elem : here.points_in_radius( src_loc, PICKUP_RANGE - 1 ) ) {
            combined_spots.push_back( elem );
        }
        add_basecamp_storage_to_loot_zone_list( mgr, src_loc, p, loot_zone_spots, combined_spots );
        if( ( reason == do_activity_reason::NO_COMPONENTS ||
              reason == do_activity_reason::NO_COMPONENTS_PREREQ ||
              reason == do_activity_reason::NO_COMPONENTS_PREREQ_2 ) &&
            act_id == ACT_MULTIPLE_CONSTRUCTION ) {
            if( !act_info.con_idx ) {
                debugmsg( "no construction selected" );
                return SKIP_LOCATION;
            }
            // its a construction and we need the components.
            const construction &built_chosen = act_info.con_idx->obj();
            what_we_need = built_chosen.requirements;
        } else if( reason == do_activity_reason::NEEDS_VEH_DECONST ||
                   reason == do_activity_reason::NEEDS_VEH_REPAIR ) {
            const vehicle *veh = veh_pointer_or_null( here.veh_at( src_loc ) );
            // we already checked this in can_do_activity() but check again just incase.
            if( !veh ) {
                p.activity_vehicle_part_index = 1;
                return SKIP_LOCATION;
            }
            const vpart_info &vpinfo = veh->part_info( p.activity_vehicle_part_index );
            requirement_data reqs;
            if( reason == do_activity_reason::NEEDS_VEH_DECONST ) {
                reqs = vpinfo.removal_requirements();
            } else if( reason == do_activity_reason::NEEDS_VEH_REPAIR ) {
                reqs = vpinfo.repair_requirements();
            }
            const std::string ran_str = random_string( 10 );
            const requirement_id req_id( ran_str );
            requirement_data::save_requirement( reqs, req_id );
            what_we_need = req_id;
        } else if( reason == do_activity_reason::NEEDS_MINING ) {
            what_we_need = requirement_id( "mining_standard" );
        } else if( reason == do_activity_reason::NEEDS_TILLING ||
                   reason == do_activity_reason::NEEDS_PLANTING ||
                   reason == do_activity_reason::NEEDS_CHOPPING ||
                   reason == do_activity_reason::NEEDS_BUTCHERING ||
                   reason == do_activity_reason::NEEDS_BIG_BUTCHERING ||
                   reason == do_activity_reason::NEEDS_TREE_CHOPPING ||
                   reason == do_activity_reason::NEEDS_FISHING ) {
            std::vector<std::vector<item_comp>> requirement_comp_vector;
            std::vector<std::vector<quality_requirement>> quality_comp_vector;
            std::vector<std::vector<tool_comp>> tool_comp_vector;
            if( reason == do_activity_reason::NEEDS_TILLING ) {
                quality_comp_vector.push_back( std::vector<quality_requirement> { quality_requirement( qual_DIG, 1, 1 ) } );
            } else if( reason == do_activity_reason::NEEDS_CHOPPING ||
                       reason == do_activity_reason::NEEDS_TREE_CHOPPING ) {
                quality_comp_vector.push_back( std::vector<quality_requirement> { quality_requirement( qual_AXE, 1, 1 ) } );
            } else if( reason == do_activity_reason::NEEDS_PLANTING ) {
                requirement_comp_vector.push_back( std::vector<item_comp> { item_comp( itype_id( dynamic_cast<const plot_options &>
                                                   ( zone->get_options() ).get_seed() ), 1 )
                                                                          } );
            } else if( reason == do_activity_reason::NEEDS_BUTCHERING ||
                       reason == do_activity_reason::NEEDS_BIG_BUTCHERING ) {
                quality_comp_vector.push_back( std::vector<quality_requirement> { quality_requirement( qual_BUTCHER, 1, 1 ) } );
                if( reason == do_activity_reason::NEEDS_BIG_BUTCHERING ) {
                    quality_comp_vector.push_back( std::vector<quality_requirement> { quality_requirement( qual_SAW_M, 1, 1 ), quality_requirement( qual_SAW_W, 1, 1 ) } );
                }
            } else if( reason == do_activity_reason::NEEDS_FISHING ) {
                quality_comp_vector.push_back( std::vector<quality_requirement> {quality_requirement( qual_FISHING, 1, 1 )} );
            }
            // ok, we need a shovel/hoe/axe/etc.
            // this is an activity that only requires this one tool, so we will fetch and wield it.
            requirement_data reqs_data = requirement_data( tool_comp_vector, quality_comp_vector,
                                         requirement_comp_vector );
            const std::string ran_str = random_string( 10 );
            const requirement_id req_id( ran_str );
            requirement_data::save_requirement( reqs_data, req_id );
            what_we_need = req_id;
        }
        bool tool_pickup = reason == do_activity_reason::NEEDS_TILLING ||
                           reason == do_activity_reason::NEEDS_PLANTING ||
                           reason == do_activity_reason::NEEDS_CHOPPING ||
                           reason == do_activity_reason::NEEDS_BUTCHERING ||
                           reason == do_activity_reason::NEEDS_BIG_BUTCHERING ||
                           reason == do_activity_reason::NEEDS_TREE_CHOPPING ||
                           reason == do_activity_reason::NEEDS_VEH_DECONST ||
                           reason == do_activity_reason::NEEDS_VEH_REPAIR ||
                           reason == do_activity_reason::NEEDS_MINING;
        // is it even worth fetching anything if there isn't enough nearby?
        if( !are_requirements_nearby( tool_pickup ? loot_zone_spots : combined_spots, what_we_need, p,
                                      act_id, tool_pickup, src_loc ) ) {
            p.add_msg_if_player( m_info, _( "The required items are not available to complete this task." ) );
            if( reason == do_activity_reason::NEEDS_VEH_DECONST ||
                reason == do_activity_reason::NEEDS_VEH_REPAIR ) {
                p.activity_vehicle_part_index = -1;
            }
            return SKIP_LOCATION;
        } else {
            if( !check_only ) {
                p.backlog.push_front( act_id );
                p.assign_activity( ACT_FETCH_REQUIRED );
                player_activity &act_prev = p.backlog.front();
                act_prev.str_values.push_back( what_we_need.str() );
                act_prev.values.push_back( static_cast<int>( reason ) );
                // come back here after successfully fetching your stuff
                if( act_prev.coords.empty() ) {
                    std::vector<tripoint> local_src_set;
                    for( const tripoint &elem : src_set ) {
                        local_src_set.push_back( here.getlocal( elem ) );
                    }
                    std::vector<tripoint> candidates;
                    for( const tripoint &point_elem : here.points_in_radius( src_loc, PICKUP_RANGE - 1 ) ) {
                        // we don't want to place the components where they could interfere with our ( or someone else's ) construction spots
                        if( !p.sees( point_elem ) || ( std::find( local_src_set.begin(), local_src_set.end(),
                                                       point_elem ) != local_src_set.end() ) || !here.can_put_items_ter_furn( point_elem ) ) {
                            continue;
                        }
                        candidates.push_back( point_elem );
                    }
                    if( candidates.empty() ) {
                        p.activity = player_activity();
                        p.backlog.clear();
                        check_npc_revert( p );
                        return SKIP_LOCATION;
                    }
                    act_prev.coords.push_back( here.getabs( candidates[std::max( 0,
                                                                      static_cast<int>( candidates.size() / 2 ) )] ) );
                }
                act_prev.placement = src;
            }
            return RETURN_EARLY;
        }
    }
    return SKIP_LOCATION;
}
References _, ACT_FETCH_REQUIRED, ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_CONSTRUCTION, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_MULTIPLE_MINE, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, Character::activity, ACTIVITY_SEARCH_DISTANCE, Character::activity_vehicle_part_index, add_basecamp_storage_to_loot_zone_list(), player::add_msg_if_player(), ALREADY_DONE, are_requirements_nearby(), Character::assign_activity(), Character::backlog, BLOCKING_TILE, activity_reason_info::can_do, CAN_DO_LOCATION, map::can_put_items_ter_furn(), check_npc_revert(), activity_reason_info::con_idx, player_activity::coords, debugmsg, DONT_HAVE_SKILL, detail::find(), zone_manager::get_manager(), get_map(), zone_data::get_options(), zone_manager::get_point_set_loot(), plot_options::get_seed(), zone_manager::get_zone_at(), get_zone_for_act(), map::getabs(), map::getlocal(), player::is_npc(), m_info, NEEDS_BIG_BUTCHERING, NEEDS_BUTCHERING, NEEDS_CHOPPING, NEEDS_FISHING, NEEDS_MINING, NEEDS_PLANTING, NEEDS_TILLING, NEEDS_TREE_CHOPPING, NEEDS_VEH_DECONST, NEEDS_VEH_REPAIR, NO_COMPONENTS, NO_COMPONENTS_PREREQ, NO_COMPONENTS_PREREQ_2, NO_ZONE, vehicle::part_info(), map::partial_con_at(), PICKUP_RANGE, player_activity::placement, map::points_in_radius(), Character::pos(), qual_AXE, qual_BUTCHER, qual_DIG, qual_FISHING, qual_SAW_M, qual_SAW_W, random_string(), activity_reason_info::reason, vpart_info::removal_requirements(), vpart_info::repair_requirements(), construction::requirements, RETURN_EARLY, requirement_data::save_requirement(), Character::sees(), SKIP_LOCATION, string_id< T >::str(), player_activity::str_values, UNKNOWN_ACTIVITY, player_activity::values, map::veh_at(), and veh_pointer_or_null().
Referenced by generic_multi_activity_handler().
generic_multi_activity_do()
static bool generic_multi_activity_do (player & p, const activity_id & act_id, const activity_reason_info & act_info, const tripoint & src, const tripoint & src_loc) static
Do activity at this location.
Returns true if this multi activity may be processed further
Definition at line 2837 of file activity_item_handling.cpp.
{
    // If any of the following activities return without processing
    // then they MUST return true here, to stop infinite loops.
    zone_manager &mgr = zone_manager::get_manager();
    const do_activity_reason &reason = act_info.reason;
    const zone_data *zone = mgr.get_zone_at( src, get_zone_for_act( src_loc, mgr, act_id ) );
    map &here = get_map();
    // something needs to be done, now we are there.
    // it was here earlier, in the space of one turn, maybe it got harvested by someone else.
    if( reason == do_activity_reason::NEEDS_HARVESTING &&
        here.has_flag_furn( flag_GROWTH_HARVEST, src_loc ) ) {
        iexamine::harvest_plant( p, src_loc, true );
    } else if( reason == do_activity_reason::NEEDS_TILLING && here.has_flag( flag_PLOWABLE, src_loc ) &&
               p.has_quality( qual_DIG, 1 ) && !here.has_furn( src_loc ) ) {
        p.assign_activity( ACT_CHURN, 18000, -1 );
        p.backlog.push_front( act_id );
        p.activity.placement = src;
        return false;
    } else if( reason == do_activity_reason::NEEDS_PLANTING &&
               here.has_flag_ter_or_furn( flag_PLANTABLE, src_loc ) ) {
        std::vector<zone_data> zones = mgr.get_zones( zone_type_FARM_PLOT,
                                       here.getabs( src_loc ) );
        for( const zone_data &zone : zones ) {
            const itype_id seed =
                dynamic_cast<const plot_options &>( zone.get_options() ).get_seed();
            std::vector<item *> seed_inv = p.items_with( [seed]( const item & itm ) {
                return itm.typeId() == itype_id( seed );
            } );
            // we don't have the required seed, even though we should at this point.
            // move onto the next tile, and if need be that will prompt a fetch seeds activity.
            if( seed_inv.empty() ) {
                continue;
            }
            iexamine::plant_seed( p, src_loc, itype_id( seed ) );
            p.backlog.push_front( act_id );
            return false;
        }
    } else if( reason == do_activity_reason::NEEDS_CHOPPING && p.has_quality( qual_AXE, 1 ) ) {
        if( chop_plank_activity( p, src_loc ) ) {
            p.backlog.push_front( act_id );
            return false;
        }
    } else if( reason == do_activity_reason::NEEDS_BUTCHERING ||
               reason == do_activity_reason::NEEDS_BIG_BUTCHERING ) {
        if( butcher_corpse_activity( p, src_loc, reason ) ) {
            p.backlog.push_front( act_id );
            return false;
        }
    } else if( reason == do_activity_reason::CAN_DO_CONSTRUCTION ||
               reason == do_activity_reason::CAN_DO_PREREQ ) {
        if( here.partial_con_at( src_loc ) ) {
            p.backlog.push_front( act_id );
            p.assign_activity( ACT_BUILD );
            p.activity.placement = src;
            return false;
        }
        if( construction_activity( p, zone, src_loc, act_info, act_id ) ) {
            return false;
        }
    } else if( reason == do_activity_reason::CAN_DO_FETCH && act_id == ACT_TIDY_UP ) {
        if( !tidy_activity( p, src_loc, act_id, ACTIVITY_SEARCH_DISTANCE ) ) {
            return false;
        }
    } else if( reason == do_activity_reason::CAN_DO_FETCH && act_id == ACT_FETCH_REQUIRED ) {
        if( fetch_activity( p, src_loc, act_id, ACTIVITY_SEARCH_DISTANCE ) ) {
            if( !p.is_npc() ) {
                // Npcs will automatically start the next thing in the backlog, players need to be manually prompted
                // Because some player activities are necessarily not marked as auto-resume.
                activity_handlers::resume_for_multi_activities( p );
            }
            return false;
        }
    } else if( reason == do_activity_reason::NEEDS_TREE_CHOPPING && p.has_quality( qual_AXE, 1 ) ) {
        if( chop_tree_activity( p, src_loc ) ) {
            p.backlog.push_front( act_id );
            return false;
        }
    } else if( reason == do_activity_reason::NEEDS_FISHING && p.has_quality( qual_FISHING, 1 ) ) {
        p.backlog.push_front( act_id );
        // we don't want to keep repeating the fishing activity, just piggybacking on this functions structure to find requirements.
        p.activity = player_activity();
        item *best_rod = p.best_quality_item( qual_FISHING );
        p.assign_activity( ACT_FISH, to_moves<int>( 5_hours ), 0,
                           0, best_rod->tname() );
        p.activity.targets.push_back( item_location( p, best_rod ) );
        p.activity.coord_set = g->get_fishable_locations( ACTIVITY_SEARCH_DISTANCE, src_loc );
        return false;
    } else if( reason == do_activity_reason::NEEDS_MINING ) {
        // if have enough batteries to continue etc.
        p.backlog.push_front( act_id );
        if( mine_activity( p, src_loc ) ) {
            return false;
        }
    } else if( reason == do_activity_reason::NEEDS_VEH_DECONST ) {
        if( vehicle_activity( p, src_loc, p.activity_vehicle_part_index, 'o' ) ) {
            p.backlog.push_front( act_id );
            return false;
        }
        p.activity_vehicle_part_index = -1;
    } else if( reason == do_activity_reason::NEEDS_VEH_REPAIR ) {
        if( vehicle_activity( p, src_loc, p.activity_vehicle_part_index, 'r' ) ) {
            p.backlog.push_front( act_id );
            return false;
        }
        p.activity_vehicle_part_index = -1;
    }
    return true;
}
References ACT_BUILD, ACT_CHURN, ACT_FETCH_REQUIRED, ACT_FISH, ACT_TIDY_UP, Character::activity, ACTIVITY_SEARCH_DISTANCE, Character::activity_vehicle_part_index, Character::assign_activity(), Character::backlog, Character::best_quality_item(), butcher_corpse_activity(), CAN_DO_CONSTRUCTION, CAN_DO_FETCH, CAN_DO_PREREQ, chop_plank_activity(), chop_tree_activity(), construction_activity(), player_activity::coord_set, fetch_activity(), flag_GROWTH_HARVEST(), flag_PLANTABLE(), flag_PLOWABLE(), g, zone_manager::get_manager(), get_map(), zone_data::get_options(), zone_manager::get_zone_at(), get_zone_for_act(), zone_manager::get_zones(), map::getabs(), iexamine::harvest_plant(), map::has_flag(), map::has_flag_furn(), map::has_flag_ter_or_furn(), map::has_furn(), visitable< T >::has_quality(), player::is_npc(), visitable< T >::items_with(), mine_activity(), NEEDS_BIG_BUTCHERING, NEEDS_BUTCHERING, NEEDS_CHOPPING, NEEDS_FISHING, NEEDS_HARVESTING, NEEDS_MINING, NEEDS_PLANTING, NEEDS_TILLING, NEEDS_TREE_CHOPPING, NEEDS_VEH_DECONST, NEEDS_VEH_REPAIR, map::partial_con_at(), player_activity::placement, iexamine::plant_seed(), qual_AXE, qual_DIG, qual_FISHING, activity_reason_info::reason, activity_handlers::resume_for_multi_activities(), iuse::seed(), player_activity::targets, tidy_activity(), item::tname(), item::typeId(), vehicle_activity(), and zone_type_FARM_PLOT.
Referenced by generic_multi_activity_handler().
generic_multi_activity_handler()
bool generic_multi_activity_handler (player_activity & act, player & p, bool check_only)
Definition at line 2950 of file activity_item_handling.cpp.
{
    map &here = get_map();
    const tripoint abspos = here.getabs( p.pos() );
    // NOLINTNEXTLINE(performance-unnecessary-copy-initialization)
    activity_id activity_to_restore = act.id();
    // Nuke the current activity, leaving the backlog alone
    if( !check_only ) {
        p.activity = player_activity();
    }
    // now we setup the target spots based on which activity is occurring
    // the set of target work spots - potentially after we have fetched required tools.
    std::unordered_set<tripoint> src_set = generic_multi_activity_locations( p, activity_to_restore );
    // now we have our final set of points
    std::vector<tripoint> src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
    // now loop through the work-spot tiles and judge whether its worth traveling to it yet
    // or if we need to fetch something first.
    for( const tripoint &src : src_sorted ) {
        const tripoint &src_loc = here.getlocal( src );
        if( !here.inbounds( src_loc ) && !check_only ) {
            if( !here.inbounds( p.pos() ) ) {
                // p is implicitly an NPC that has been moved off the map, so reset the activity
                // and unload them
                p.assign_activity( activity_to_restore );
                p.set_moves( 0 );
                g->reload_npcs();
                return false;
            }
            const std::vector<tripoint> route = route_adjacent( p, src_loc );
            if( route.empty() ) {
                // can't get there, can't do anything, skip it
                continue;
            }
            p.set_moves( 0 );
            p.set_destination( route, player_activity( activity_to_restore ) );
            return false;
        }
        activity_reason_info act_info = can_do_activity_there( activity_to_restore, p,
                                        src_loc, ACTIVITY_SEARCH_DISTANCE );
        // see activity_handlers.h enum for requirement_check_result
        const requirement_check_result req_res = generic_multi_activity_check_requirement( p,
                activity_to_restore, act_info, src, src_loc, src_set, check_only );
        if( req_res == SKIP_LOCATION ) {
            continue;
        } else if( req_res == RETURN_EARLY ) {
            return true;
        }
        if( square_dist( p.pos(), src_loc ) > 1 ) {
            std::vector<tripoint> route = route_adjacent( p, src_loc );
            // check if we found path to source / adjacent tile
            if( route.empty() ) {
                check_npc_revert( p );
                continue;
            }
            if( !check_only ) {
                if( p.moves <= 0 ) {
                    // Restart activity and break from cycle.
                    p.assign_activity( activity_to_restore );
                    return true;
                }
                // set the destination and restart activity after player arrives there
                // we don't need to check for safe mode,
                // activity will be restarted only if
                // player arrives on destination tile
                p.set_destination( route, player_activity( activity_to_restore ) );
                return true;
            }
        }
        // we checked if the work spot was in darkness earlier
        // but there is a niche case where the player is in darkness but the work spot is not
        // this can create infinite loops
        // and we can't check player.pos() for darkness before they've traveled to where they are going to be.
        // but now we are here, we check
        if( activity_to_restore != ACT_TIDY_UP &&
            activity_to_restore != ACT_MOVE_LOOT &&
            activity_to_restore != ACT_FETCH_REQUIRED &&
            !character_funcs::can_see_fine_details( p ) ) {
            p.add_msg_if_player( m_info, _( "It is too dark to work here." ) );
            return false;
        }
        if( !check_only ) {
            if( !generic_multi_activity_do( p, activity_to_restore, act_info, src, src_loc ) ) {
                // if the activity was succesful
                // then a new activity was assigned
                // and the backlog was given the multi-act
                return false;
            }
        } else {
            return true;
        }
    }
    if( !check_only ) {
        if( p.moves <= 0 ) {
            // Restart activity and break from cycle.
            p.assign_activity( activity_to_restore );
            p.activity_vehicle_part_index = -1;
            return false;
        }
        // if we got here, we need to revert otherwise NPC will be stuck in AI Limbo and have a head explosion.
        if( p.backlog.empty() || src_set.empty() ) {
            check_npc_revert( p );
            // tidy up leftover moved parts and tools left lying near the work spots.
            if( player_activity( activity_to_restore ).is_multi_type() ) {
                p.assign_activity( ACT_TIDY_UP );
            }
        }
        p.activity_vehicle_part_index = -1;
    }
    // scanned every location, tried every path.
    return false;
}
References _, act, ACT_FETCH_REQUIRED, ACT_MOVE_LOOT, ACT_TIDY_UP, Character::activity, ACTIVITY_SEARCH_DISTANCE, Character::activity_vehicle_part_index, player::add_msg_if_player(), Character::assign_activity(), Character::backlog, can_do_activity_there(), character_funcs::can_see_fine_details(), check_npc_revert(), g, generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_locations(), get_map(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), string_id< T >::id(), map::inbounds(), m_info, Creature::moves, Character::pos(), RETURN_EARLY, route_adjacent(), Character::set_destination(), Creature::set_moves(), SKIP_LOCATION, and square_dist().
Referenced by activity_handlers::chop_trees_do_turn(), npc::do_player_activity(), activity_handlers::fetch_do_turn(), npc::find_job_to_perform(), activity_handlers::multiple_butcher_do_turn(), activity_handlers::multiple_chop_planks_do_turn(), activity_handlers::multiple_construction_do_turn(), activity_handlers::multiple_farm_do_turn(), activity_handlers::multiple_fish_do_turn(), activity_handlers::multiple_mine_do_turn(), activity_handlers::tidy_up_do_turn(), activity_handlers::vehicle_deconstruction_do_turn(), and activity_handlers::vehicle_repair_do_turn().
generic_multi_activity_locations()
static std::unordered_set< tripoint > generic_multi_activity_locations (player & p, const activity_id & act_id) static
Determine all locations for this generic activity.
Returns locations
Definition at line 2518 of file activity_item_handling.cpp.
{
    bool dark_capable = false;
    std::unordered_set<tripoint> src_set;
    zone_manager &mgr = zone_manager::get_manager();
    const tripoint localpos = p.pos();
    map &here = get_map();
    const tripoint abspos = here.getabs( localpos );
    if( act_id == ACT_TIDY_UP ) {
        dark_capable = true;
        tripoint unsorted_spot;
        std::unordered_set<tripoint> unsorted_set = mgr.get_near( zone_type_LOOT_UNSORTED, abspos,
                ACTIVITY_SEARCH_DISTANCE );
        if( !unsorted_set.empty() ) {
            unsorted_spot = here.getlocal( random_entry( unsorted_set ) );
        }
        bool found_one_point = false;
        bool found_route = true;
        for( const tripoint &elem : here.points_in_radius( localpos,
                ACTIVITY_SEARCH_DISTANCE ) ) {
            // There's no point getting the entire list of all items to tidy up now.
            // the activity will run again after pathing to the first tile anyway.
            // tidy up activity has no requirements that will discount a square and
            // have the requirement to skip and scan the next one, ( other than checking path )
            // shortcircuiting the need to scan the entire map continuously can improve performance
            // especially if NPCs have a backlog of moves or there is a lot of them
            if( !found_route ) {
                found_route = true;
                continue;
            }
            if( found_one_point ) {
                break;
            }
            for( const item &stack_elem : here.i_at( elem ) ) {
                if( stack_elem.has_var( "activity_var" ) && stack_elem.get_var( "activity_var", "" ) == p.name ) {
                    const furn_t &f = here.furn( elem ).obj();
                    if( !f.has_flag( flag_PLANT ) ) {
                        src_set.insert( here.getabs( elem ) );
                        found_one_point = true;
                        // only check for a valid path, as that is all that is needed to tidy something up.
                        if( square_dist( p.pos(), elem ) > 1 ) {
                            std::vector<tripoint> route = route_adjacent( p, elem );
                            if( route.empty() ) {
                                found_route = false;
                            }
                        }
                        break;
                    }
                }
            }
        }
        if( src_set.empty() && unsorted_spot != tripoint_zero ) {
            for( const item *inv_elem : p.inv_dump() ) {
                if( inv_elem->has_var( "activity_var" ) ) {
                    // we've gone to tidy up all the things lying around, now tidy up the things we picked up.
                    src_set.insert( here.getabs( unsorted_spot ) );
                    break;
                }
            }
        }
    } else if( act_id != ACT_FETCH_REQUIRED ) {
        zone_type_id zone_type = get_zone_for_act( tripoint_zero, mgr, act_id );
        src_set = mgr.get_near( zone_type_id( zone_type ), abspos, ACTIVITY_SEARCH_DISTANCE );
        // multiple construction will form a list of targets based on blueprint zones and unfinished constructions
        if( act_id == ACT_MULTIPLE_CONSTRUCTION ) {
            for( const tripoint &elem : here.points_in_radius( localpos, ACTIVITY_SEARCH_DISTANCE ) ) {
                partial_con *pc = here.partial_con_at( elem );
                if( pc ) {
                    src_set.insert( here.getabs( elem ) );
                }
            }
            // farming activities encompass tilling, planting, harvesting.
        } else if( act_id == ACT_MULTIPLE_FARM ) {
            dark_capable = true;
        }
    } else {
        dark_capable = true;
        // get the right zones for the items in the requirements.
        // we previously checked if the items are nearby before we set the fetch task
        // but we will check again later, to be sure nothings changed.
        std::vector<std::tuple<tripoint, itype_id, int>> mental_map = requirements_map( p,
                ACTIVITY_SEARCH_DISTANCE );
        for( const auto &elem : mental_map ) {
            const tripoint &elem_point = std::get<0>( elem );
            src_set.insert( here.getabs( elem_point ) );
        }
    }
    // prune the set to remove tiles that are never gonna work out.
    const bool pre_dark_check = src_set.empty();
    for( auto it2 = src_set.begin(); it2 != src_set.end(); ) {
        // remove dangerous tiles
        const tripoint set_pt = here.getlocal( *it2 );
        if( here.dangerous_field_at( set_pt ) ) {
            it2 = src_set.erase( it2 );
            // remove tiles in darkness, if we aren't lit-up ourselves
        } else if( !dark_capable && !character_funcs::can_see_fine_details( p, set_pt ) ) {
            it2 = src_set.erase( it2 );
        } else if( act_id == ACT_MULTIPLE_FISH ) {
            const ter_id terrain_id = here.ter( set_pt );
            if( !terrain_id.obj().has_flag( TFLAG_DEEP_WATER ) ) {
                it2 = src_set.erase( it2 );
            } else {
                ++it2;
            }
        } else {
            ++it2;
        }
    }
    const bool post_dark_check = src_set.empty();
    if( !pre_dark_check && post_dark_check ) {
        p.add_msg_if_player( m_info, _( "It is too dark to do this activity." ) );
    }
    return src_set;
}
References _, ACT_FETCH_REQUIRED, ACT_MULTIPLE_CONSTRUCTION, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_TIDY_UP, ACTIVITY_SEARCH_DISTANCE, player::add_msg_if_player(), character_funcs::can_see_fine_details(), map::dangerous_field_at(), flag_PLANT(), map::furn(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), get_zone_for_act(), map::getabs(), map::getlocal(), map_data_common_t::has_flag(), map::i_at(), Character::inv_dump(), m_info, Character::name, int_id< T >::obj(), map::partial_con_at(), map::points_in_radius(), Character::pos(), random_entry(), requirements_map(), route_adjacent(), square_dist(), map::ter(), TFLAG_DEEP_WATER, tripoint_zero, and zone_type_LOOT_UNSORTED.
Referenced by generic_multi_activity_handler().
get_capacity_fraction()
static double get_capacity_fraction (int capacity, int volume) static
Definition at line 825 of file activity_item_handling.cpp.
{
    // fraction of capacity the item would occupy
    // fr = 1 is for capacity smaller than is size of item
    // in such case, let's assume player does the trip for full cost with item in hands
    double fr = 1;
    if( capacity > volume ) {
        fr = static_cast<double>( volume ) / capacity;
    }
    return fr;
}
Referenced by move_cost_cart(), and move_cost_inv().
get_zone_for_act()
static zone_type_id get_zone_for_act (const tripoint & src_loc, const zone_manager & mgr, const activity_id & act_id) static
Definition at line 2476 of file activity_item_handling.cpp.
{
    zone_type_id ret = zone_type_id( "" );
    if( act_id == ACT_VEHICLE_DECONSTRUCTION ) {
        ret = zone_type_VEHICLE_DECONSTRUCT;
    }
    if( act_id == ACT_VEHICLE_REPAIR ) {
        ret = zone_type_VEHICLE_REPAIR;
    }
    if( act_id == ACT_MULTIPLE_CHOP_TREES ) {
        ret = zone_type_CHOP_TREES;
    }
    if( act_id == ACT_MULTIPLE_CONSTRUCTION ) {
        ret = zone_type_CONSTRUCTION_BLUEPRINT;
    }
    if( act_id == ACT_MULTIPLE_FARM ) {
        ret = zone_type_FARM_PLOT;
    }
    if( act_id == ACT_MULTIPLE_BUTCHER ) {
        ret = zone_type_LOOT_CORPSE;
    }
    if( act_id == ACT_MULTIPLE_CHOP_PLANKS ) {
        ret = zone_type_LOOT_WOOD;
    }
    if( act_id == ACT_MULTIPLE_FISH ) {
        ret = zone_type_FISHING_SPOT;
    }
    if( act_id == ACT_MULTIPLE_MINE ) {
        ret = zone_type_MINING;
    }
    if( src_loc != tripoint_zero && act_id == ACT_FETCH_REQUIRED ) {
        const zone_data *zd = mgr.get_zone_at( get_map().getabs( src_loc ) );
        if( zd ) {
            ret = zd->get_type();
        }
    }
    return ret;
}
References ACT_FETCH_REQUIRED, ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_CONSTRUCTION, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_MULTIPLE_MINE, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, get_map(), zone_data::get_type(), zone_manager::get_zone_at(), cata::hash64_detail::ret, tripoint_zero, zone_type_CHOP_TREES, zone_type_CONSTRUCTION_BLUEPRINT, zone_type_FARM_PLOT, zone_type_FISHING_SPOT, zone_type_LOOT_CORPSE, zone_type_LOOT_WOOD, zone_type_MINING, zone_type_VEHICLE_DECONSTRUCT, and zone_type_VEHICLE_REPAIR.
Referenced by generic_multi_activity_check_requirement(), generic_multi_activity_do(), and generic_multi_activity_locations().
has_clear_path_to_pickup_items()
static bool has_clear_path_to_pickup_items (const tripoint & from, const tripoint & to) inline static
Definition at line 3091 of file activity_item_handling.cpp.
{
    map &here = get_map();
    return here.has_items( to ) &&
           here.accessible_items( to ) &&
           here.clear_path( from, to, PICKUP_RANGE, 1, 100 );
}
References map::accessible_items(), map::clear_path(), get_map(), map::has_items(), and PICKUP_RANGE.
Referenced by find_refuel_spot_zone().
has_skill_for_vehicle_work()
static bool has_skill_for_vehicle_work (const std::map< skill_id, int > & required_skills, player & p) static
Definition at line 1279 of file activity_item_handling.cpp.
{
    for( const auto &e : required_skills ) {
        bool hasSkill = p.get_skill_level( e.first ) >= e.second;
        if( !hasSkill ) {
            return false;
        }
    }
    return true;
}
References Character::get_skill_level().
Referenced by can_do_activity_there().
mine_activity()
static bool mine_activity (player & p, const tripoint & src_loc) static
Definition at line 2395 of file activity_item_handling.cpp.
{
    map &here = get_map();
    std::vector<item *> mining_inv = p.items_with( []( const item & itm ) {
        return ( itm.has_flag( flag_DIG_TOOL ) && !itm.type->can_use( "JACKHAMMER" ) ) ||
               ( itm.type->can_use( "JACKHAMMER" ) && itm.ammo_sufficient() );
    } );
    if( mining_inv.empty() || p.is_mounted() || p.is_underwater() || here.veh_at( src_loc ) ||
        !here.has_flag( "MINEABLE", src_loc ) ) {
        return false;
    }
    item *chosen_item = nullptr;
    bool powered = false;
    // is it a pickaxe or jackhammer?
    for( item *elem : mining_inv ) {
        if( chosen_item == nullptr ) {
            chosen_item = elem;
            if( elem->type->can_use( "JACKHAMMER" ) ) {
                powered = true;
            }
        } else {
            // prioritise powered tools
            if( chosen_item->type->can_use( "PICKAXE" ) && elem->type->can_use( "JACKHAMMER" ) ) {
                chosen_item = elem;
                powered = true;
                break;
            }
        }
    }
    if( chosen_item == nullptr ) {
        return false;
    }
    int moves = to_moves<int>( powered ? 30_minutes : 20_minutes );
    if( !powered ) {
        moves += ( ( MAX_STAT + 4 ) - std::min( p.str_cur, MAX_STAT ) ) * to_moves<int>( 5_minutes );
    }
    if( here.move_cost( src_loc ) == 2 ) {
        // We're breaking up some flat surface like pavement, which is much easier
        moves /= 2;
    }
    p.assign_activity( powered ? ACT_JACKHAMMER : ACT_PICKAXE, moves );
    p.activity.targets.push_back( item_location( p, chosen_item ) );
    p.activity.placement = here.getabs( src_loc );
    return true;
}
References ACT_JACKHAMMER, ACT_PICKAXE, Character::activity, item::ammo_sufficient(), Character::assign_activity(), itype::can_use(), flag_DIG_TOOL(), get_map(), map::getabs(), item::has_flag(), map::has_flag(), Character::is_mounted(), Creature::is_underwater(), visitable< T >::items_with(), MAX_STAT, map::move_cost(), player_activity::placement, Character::str_cur, player_activity::targets, item::type, and map::veh_at().
Referenced by generic_multi_activity_do().
move_cost()
static int move_cost (const item & it, const tripoint & src, const tripoint & dest) static
Definition at line 899 of file activity_item_handling.cpp.
{
    if( g->u.get_grab_type() == OBJECT_VEHICLE ) {
        tripoint cart_position = g->u.pos() + g->u.grab_point;
        if( const cata::optional<vpart_reference> vp = get_map().veh_at(
                    cart_position ).part_with_feature( "CARGO", false ) ) {
            const vehicle &veh = vp->vehicle();
            size_t vstor = vp->part_index();
            units::volume capacity = veh.free_volume( vstor );
            return move_cost_cart( it, src, dest, capacity );
        }
    }
    return move_cost_inv( it, src, dest );
}
References vehicle::free_volume(), g, get_map(), move_cost_cart(), move_cost_inv(), OBJECT_VEHICLE, and vehicle::vehicle().
Referenced by Character::attack_cost(), vehicle::autodrive_controller::compute_next_nodes(), dump_requirements(), player::gun_value(), iuse::handle_ground_graffiti(), Character::melee_attack(), npc::move_away_from(), move_cost_cart(), move_cost_inv(), move_item(), Character::perform_technique(), player::reach_attack(), iuse::robotcontrol(), iexamine::shrub_wildveggies(), smash(), ranged::throw_cost(), player::throw_item(), and game::vertical_move().
move_cost_cart()
static int move_cost_cart (const item & it, const tripoint & src, const tripoint & dest, const units::volume & capacity) static
Definition at line 871 of file activity_item_handling.cpp.
{
    // to prevent potentially ridiculous number
    const int MAX_COST = 500;
    // cost to move item into the cart
    const int pickup_cost = pickup::cost_to_move_item( g->u, it );
    // cost to move item out of the cart
    const int drop_cost = pickup_cost;
    // typical flat ground move cost
    const int mc_per_tile = 100;
    // only free cart capacity
    const int cart_capacity = units::to_milliliter( capacity );
    const int item_volume = units::to_milliliter( it.volume() );
    const double fr = get_capacity_fraction( cart_capacity, item_volume );
    // approximation of movement cost between source and destination
    const int move_cost = mc_per_tile * rl_dist( src, dest ) * fr;
    return std::min( pickup_cost + drop_cost + move_cost, MAX_COST );
}
References pickup::cost_to_move_item(), g, get_capacity_fraction(), move_cost(), rl_dist(), units::to_milliliter(), and item::volume().
Referenced by move_cost().
move_cost_inv()
static int move_cost_inv (const item & it, const tripoint & src, const tripoint & dest) static
Definition at line 839 of file activity_item_handling.cpp.
{
    // to prevent potentially ridiculous number
    const int MAX_COST = 500;
    // it seems that pickup cost is flat 100
    // in function pick_one_up, variable moves_taken has initial value of 100
    // and never changes until it is finally used in function
    // remove_from_map_or_vehicle
    const int pickup_cost = 100;
    // drop cost for non-tumbling items (from inventory overload) is also flat 100
    // according to convert_to_items (it does contain todo to use calculated costs)
    const int drop_cost = 100;
    // typical flat ground move cost
    const int mc_per_tile = 100;
    // only free inventory capacity
    const int inventory_capacity = units::to_milliliter( g->u.volume_capacity() -
                                   g->u.volume_carried() );
    const int item_volume = units::to_milliliter( it.volume() );
    const double fr = get_capacity_fraction( inventory_capacity, item_volume );
    // approximation of movement cost between source and destination
    const int move_cost = mc_per_tile * rl_dist( src, dest ) * fr;
    return std::min( pickup_cost + drop_cost + move_cost, MAX_COST );
}
References g, get_capacity_fraction(), move_cost(), rl_dist(), units::to_milliliter(), and item::volume().
Referenced by move_cost().
move_item()
static void move_item (player & p, item & it, const int quantity, const tripoint & src, const tripoint & dest, vehicle * src_veh, int src_part, const activity_id & activity_to_restore = activity_id::NULL_ID()) static
Definition at line 978 of file activity_item_handling.cpp.
{
    item leftovers = it;
    if( quantity != 0 && it.count_by_charges() ) {
        // Reinserting leftovers happens after item removal to avoid stacking issues.
        leftovers.charges = it.charges - quantity;
        if( leftovers.charges > 0 ) {
            it.charges = quantity;
        }
    } else {
        leftovers.charges = 0;
    }
    map &here = get_map();
    // Check that we can pick it up.
    if( !it.made_of( LIQUID ) ) {
        p.mod_moves( -move_cost( it, src, dest ) );
        if( activity_to_restore == ACT_TIDY_UP ) {
            it.erase_var( "activity_var" );
        } else if( activity_to_restore == ACT_FETCH_REQUIRED ) {
            it.set_var( "activity_var", p.name );
        }
        put_into_vehicle_or_drop( p, item_drop_reason::deliberate, { it }, dest );
        // Remove from map or vehicle.
        if( src_veh ) {
            src_veh->remove_item( src_part, &it );
        } else {
            here.i_rem( src, &it );
        }
    }
    // If we didn't pick up a whole stack, put the remainder back where it came from.
    if( leftovers.charges > 0 ) {
        if( src_veh ) {
            if( !src_veh->add_item( src_part, leftovers ) ) {
                debugmsg( "SortLoot: Source vehicle failed to receive leftover charges." );
            }
        } else {
            here.add_item_or_charges( src, leftovers );
        }
    }
}
References ACT_FETCH_REQUIRED, ACT_TIDY_UP, vehicle::add_item(), map::add_item_or_charges(), item::charges, item::count_by_charges(), debugmsg, deliberate, item::erase_var(), get_map(), map::i_rem(), LIQUID, item::made_of(), Creature::mod_moves(), move_cost(), Character::name, put_into_vehicle_or_drop(), vehicle::remove_item(), and item::set_var().
Referenced by activity_on_turn_move_loot(), iexamine::elevator(), fetch_activity(), tidy_activity(), and try_fuel_fire().
obtain_activity_items()
static std::list< item > obtain_activity_items (Character & who, std::list< pickup::act_item > & targets) static
Definition at line 674 of file activity_item_handling.cpp.
{
    debug_drop_list( targets );
    std::list<item> res = pickup::obtain_and_tokenize_items( *who.as_player(), targets );
    debug_tokens( res );
    return res;
}
References Creature::as_player(), debug_drop_list(), debug_tokens(), and pickup::obtain_and_tokenize_items().
Referenced by drop_activity_actor::do_turn(), and stash_activity_actor::do_turn().
pass_to_ownership_handling()
static void pass_to_ownership_handling (item obj, Character & c) static
Definition at line 276 of file activity_item_handling.cpp.
{
    obj.handle_pickup_ownership( c );
}
References c, and int_id< T >::obj().
Referenced by drop_on_map(), and stash_on_pet().
put_into_vehicle()
static void put_into_vehicle (Character & c, item_drop_reason reason, const std::list< item > & items, vehicle & veh, int part) static
Definition at line 162 of file activity_item_handling.cpp.
{
    if( items.empty() ) {
        return;
    }
    const tripoint where = veh.global_part_pos3( part );
    map &here = get_map();
    const std::string ter_name = here.name( where );
    int fallen_count = 0;
    int into_vehicle_count = 0;
    // can't use constant reference here because of the spill_contents()
    for( auto it : items ) {
        if( pickup::handle_spillable_contents( c, it, here ) ) {
            continue;
        }
        if( veh.add_item( part, it ) ) {
            into_vehicle_count += it.count();
        } else {
            if( it.count_by_charges() ) {
                // Maybe we can add a few charges in the trunk and the rest on the ground.
                auto charges_added = veh.add_charges( part, it );
                it.mod_charges( -charges_added );
                into_vehicle_count += charges_added;
            }
            here.add_item_or_charges( where, it );
            fallen_count += it.count();
        }
        it.handle_pickup_ownership( c );
    }
    const std::string part_name = veh.part_info( part ).name();
    if( same_type( items ) ) {
        const item &it = items.front();
        const int dropcount = items.size() * it.count();
        const std::string it_name = it.tname( dropcount );
        switch( reason ) {
            case item_drop_reason::deliberate:
                c.add_msg_player_or_npc(
                    vgettext( "You put your %1$s in the %2$s's %3$s.",
                              "You put your %1$s in the %2$s's %3$s.", dropcount ),
                    vgettext( "<npcname> puts their %1$s in the %2$s's %3$s.",
                              "<npcname> puts their %1$s in the %2$s's %3$s.", dropcount ),
                    it_name, veh.name, part_name
                );
                break;
            case item_drop_reason::too_large:
                c.add_msg_if_player(
                    vgettext(
                        "There's no room in your inventory for the %s, so you drop it into the %s's %s.",
                        "There's no room in your inventory for the %s, so you drop them into the %s's %s.",
                        dropcount ),
                    it_name, veh.name, part_name
                );
                break;
            case item_drop_reason::too_heavy:
                c.add_msg_if_player(
                    vgettext( "The %s is too heavy to carry, so you drop it into the %s's %s.",
                              "The %s are too heavy to carry, so you drop them into the %s's %s.", dropcount ),
                    it_name, veh.name, part_name
                );
                break;
            case item_drop_reason::tumbling:
                c.add_msg_if_player(
                    m_bad,
                    vgettext( "Your %s tumbles into the %s's %s.",
                              "Your %s tumble into the %s's %s.", dropcount ),
                    it_name, veh.name, part_name
                );
                break;
        }
    } else {
        switch( reason ) {
            case item_drop_reason::deliberate:
                c.add_msg_player_or_npc(
                    _( "You put several items in the %1$s's %2$s." ),
                    _( "<npcname> puts several items in the %1$s's %2$s." ),
                    veh.name, part_name
                );
                break;
            case item_drop_reason::too_large:
            case item_drop_reason::too_heavy:
            case item_drop_reason::tumbling:
                c.add_msg_if_player(
                    m_bad, _( "Some items tumble into the %1$s's %2$s." ),
                    veh.name, part_name
                );
                break;
        }
    }
    if( fallen_count > 0 ) {
        if( into_vehicle_count > 0 ) {
            c.add_msg_if_player(
                m_warning,
                vgettext( "The %s is full, so something fell to the %s.",
                          "The %s is full, so some items fell to the %s.", fallen_count ),
                part_name, ter_name
            );
        } else {
            c.add_msg_if_player(
                m_warning,
                vgettext( "The %s is full, so it fell to the %s.",
                          "The %s is full, so they fell to the %s.", fallen_count ),
                part_name, ter_name
            );
        }
    }
}
References _, vehicle::add_charges(), vehicle::add_item(), map::add_item_or_charges(), c, item::count(), deliberate, get_map(), vehicle::global_part_pos3(), pickup::handle_spillable_contents(), m_bad, m_warning, vpart_info::name(), map::name(), vehicle::name, vehicle::part_info(), same_type(), item::tname(), too_heavy, too_large, tumbling, and vgettext().
Referenced by put_into_vehicle_or_drop().
put_into_vehicle_or_drop() [1/2]
void put_into_vehicle_or_drop (Character & c, item_drop_reason reason, const std::list< item > & items)
Definition at line 394 of file activity_item_handling.cpp.
{
    return put_into_vehicle_or_drop( c, reason, items, c.pos() );
}
References c, and put_into_vehicle_or_drop().
Referenced by player::add_or_drop_with_msg(), Character::apply_damage(), crafting::complete_disassemble(), veh_interact::complete_vehicle(), player::consume(), damage_item(), Character::dispose_item(), drop_activity_actor::do_turn(), move_items_activity_actor::do_turn(), Character::drop_invalid_inventory(), wash_activity_actor::finish(), move_item(), put_into_vehicle_or_drop(), vehicle::reload_seeds(), and tidy_activity().
put_into_vehicle_or_drop() [2/2]
void put_into_vehicle_or_drop (Character & c, item_drop_reason reason, const std::list< item > & items, const tripoint & where, bool force_ground)
Definition at line 399 of file activity_item_handling.cpp.
{
    map &here = get_map();
    const cata::optional<vpart_reference> vp = here.veh_at( where ).part_with_feature( "CARGO", false );
    if( vp && !force_ground ) {
        put_into_vehicle( c, reason, items, vp->vehicle(), vp->part_index() );
        return;
    }
    drop_on_map( c, reason, items, where );
}
References c, drop_on_map(), get_map(), optional_vpart_position::part_with_feature(), put_into_vehicle(), and map::veh_at().
random_string()
static std::string random_string (size_t length) static
Definition at line 1177 of file activity_item_handling.cpp.
{
    auto randchar = []() -> char {
        static constexpr char charset[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "abcdefghijklmnopqrstuvwxyz";
        static constexpr size_t num_chars = sizeof( charset ) - 1;
        return charset[rng( 0, num_chars - 1 )];
    };
    std::string str( length, 0 );
    std::generate_n( str.begin(), length, randchar );
    return str;
}
References rng().
Referenced by generic_multi_activity_check_requirement().
requirements_map()
static std::vector< std::tuple< tripoint, itype_id, int > > requirements_map (player & p, const int distance = ACTIVITY_SEARCH_DISTANCE) static
Definition at line 1626 of file activity_item_handling.cpp.
{
    std::vector<std::tuple<tripoint, itype_id, int>> requirement_map;
    if( p.backlog.empty() || p.backlog.front().str_values.empty() ) {
        return requirement_map;
    }
    const requirement_data things_to_fetch = requirement_id( p.backlog.front().str_values[0] ).obj();
    const activity_id activity_to_restore = p.backlog.front().id();
    // NOLINTNEXTLINE(performance-unnecessary-copy-initialization)
    requirement_id things_to_fetch_id = things_to_fetch.id();
    std::vector<std::vector<item_comp>> req_comps = things_to_fetch.get_components();
    std::vector<std::vector<tool_comp>> tool_comps = things_to_fetch.get_tools();
    std::vector<std::vector<quality_requirement>> quality_comps = things_to_fetch.get_qualities();
    zone_manager &mgr = zone_manager::get_manager();
    const bool pickup_task = p.backlog.front().id() == ACT_MULTIPLE_FARM ||
                             p.backlog.front().id() == ACT_MULTIPLE_CHOP_PLANKS ||
                             p.backlog.front().id() == ACT_MULTIPLE_BUTCHER ||
                             p.backlog.front().id() == ACT_MULTIPLE_CHOP_TREES ||
                             p.backlog.front().id() == ACT_VEHICLE_DECONSTRUCTION ||
                             p.backlog.front().id() == ACT_VEHICLE_REPAIR ||
                             p.backlog.front().id() == ACT_MULTIPLE_FISH ||
                             p.backlog.front().id() == ACT_MULTIPLE_MINE;
    // where it is, what it is, how much of it, and how much in total is required of that item.
    std::vector<std::tuple<tripoint, itype_id, int>> final_map;
    std::vector<tripoint> loot_spots;
    std::vector<tripoint> already_there_spots;
    std::vector<tripoint> combined_spots;
    std::map<itype_id, int> total_map;
    map &here = get_map();
    tripoint src_loc = here.getlocal( p.backlog.front().placement );
    for( const tripoint &elem : here.points_in_radius( src_loc,
            PICKUP_RANGE - 1 ) ) {
        already_there_spots.push_back( elem );
        combined_spots.push_back( elem );
    }
    for( const tripoint &elem : mgr.get_point_set_loot( here.getabs( p.pos() ), distance,
            p.is_npc() ) ) {
        // if there is a loot zone that's already near the work spot, we don't want it to be added twice.
        if( std::find( already_there_spots.begin(), already_there_spots.end(),
                       elem ) != already_there_spots.end() ) {
            // construction tasks don't need the loot spot *and* the already_there/combined spots both added.
            // but a farming task will need to go and fetch the tool no matter if its near the work spot.
            // whereas the construction will automatically use what's nearby anyway.
            if( pickup_task ) {
                loot_spots.push_back( elem );
            } else {
                continue;
            }
        } else {
            loot_spots.push_back( elem );
            combined_spots.push_back( elem );
        }
    }
    add_basecamp_storage_to_loot_zone_list( mgr, src_loc, p, loot_spots, combined_spots );
    // if the requirements aren't available, then stop.
    if( !are_requirements_nearby( pickup_task ? loot_spots : combined_spots, things_to_fetch_id, p,
                                  activity_to_restore, pickup_task, src_loc ) ) {
        return requirement_map;
    }
    // if the requirements are already near the work spot and its a construction/crafting task, then no need to fetch anything more.
    if( !pickup_task &&
        are_requirements_nearby( already_there_spots, things_to_fetch_id, p, activity_to_restore,
                                 false, src_loc ) ) {
        return requirement_map;
    }
    // a vector of every item in every tile that matches any part of the requirements.
    // will be filtered for amounts/charges afterwards.
    for( const tripoint &point_elem : pickup_task ? loot_spots : combined_spots ) {
        std::map<itype_id, int> temp_map;
        for( const item &stack_elem : here.i_at( point_elem ) ) {
            for( std::vector<item_comp> &elem : req_comps ) {
                for( item_comp &comp_elem : elem ) {
                    if( comp_elem.type == stack_elem.typeId() ) {
                        // if its near the work site, we can remove a count from the requirements.
                        // if two "lines" of the requirement have the same component appearing again
                        // that is fine, we will choose which "line" to fulfill later, and the decrement will count towards that then.
                        if( !pickup_task &&
                            std::find( already_there_spots.begin(), already_there_spots.end(),
                                       point_elem ) != already_there_spots.end() ) {
                            comp_elem.count -= stack_elem.count();
                        }
                        temp_map[stack_elem.typeId()] += stack_elem.count();
                    }
                }
            }
            for( std::vector<tool_comp> &elem : tool_comps ) {
                for( tool_comp &comp_elem : elem ) {
                    if( comp_elem.type == stack_elem.typeId() ) {
                        if( !pickup_task &&
                            std::find( already_there_spots.begin(), already_there_spots.end(),
                                       point_elem ) != already_there_spots.end() ) {
                            comp_elem.count -= stack_elem.count();
                        }
                        if( comp_elem.by_charges() ) {
                            // we don't care if there are 10 welders with 5 charges each
                            // we only want the one welder that has the required charge.
                            if( stack_elem.ammo_remaining() >= comp_elem.count ) {
                                temp_map[stack_elem.typeId()] += stack_elem.ammo_remaining();
                            }
                        } else {
                            temp_map[stack_elem.typeId()] += stack_elem.count();
                        }
                    }
                }
            }
            for( std::vector<quality_requirement> &elem : quality_comps ) {
                for( quality_requirement &comp_elem : elem ) {
                    const quality_id tool_qual = comp_elem.type;
                    const int qual_level = comp_elem.level;
                    if( stack_elem.has_quality( tool_qual, qual_level ) ) {
                        if( !pickup_task &&
                            std::find( already_there_spots.begin(), already_there_spots.end(),
                                       point_elem ) != already_there_spots.end() ) {
                            comp_elem.count -= stack_elem.count();
                        }
                        temp_map[stack_elem.typeId()] += stack_elem.count();
                    }
                }
            }
        }
        for( const auto &map_elem : temp_map ) {
            total_map[map_elem.first] += map_elem.second;
            // if its a construction/crafting task, we can discount any items already near the work spot.
            // we don't need to fetch those, they will be used automatically in the construction.
            // a shovel for tilling, for example, however, needs to be picked up, no matter if its near the spot or not.
            if( !pickup_task ) {
                if( std::find( already_there_spots.begin(), already_there_spots.end(),
                               point_elem ) != already_there_spots.end() ) {
                    continue;
                }
            }
            requirement_map.push_back( std::make_tuple( point_elem, map_elem.first, map_elem.second ) );
        }
    }
    // Ok we now have a list of all the items that match the requirements, their points, and a quantity for each one.
    // we need to consolidate them, and winnow it down to the minimum required counts, instead of all matching.
    for( const std::vector<item_comp> &elem : req_comps ) {
        bool line_found = false;
        for( const item_comp &comp_elem : elem ) {
            if( line_found || comp_elem.count <= 0 ) {
                break;
            }
            int quantity_required = comp_elem.count;
            int item_quantity = 0;
            auto it = requirement_map.begin();
            int remainder = 0;
            while( it != requirement_map.end() ) {
                tripoint pos_here = std::get<0>( *it );
                itype_id item_here = std::get<1>( *it );
                int quantity_here = std::get<2>( *it );
                if( comp_elem.type == item_here ) {
                    item_quantity += quantity_here;
                }
                if( item_quantity >= quantity_required ) {
                    // it's just this spot that can fulfil the requirement on its own
                    final_map.push_back( std::make_tuple( pos_here, item_here, std::min<int>( quantity_here,
                                                          quantity_required ) ) );
                    if( quantity_here >= quantity_required ) {
                        line_found = true;
                        break;
                    } else {
                        remainder = quantity_required - quantity_here;
                    }
                    break;
                }
                it++;
            }
            if( line_found ) {
                while( true ) {
                    // go back over things
                    if( it == requirement_map.begin() ) {
                        break;
                    }
                    if( remainder <= 0 ) {
                        line_found = true;
                        break;
                    }
                    tripoint pos_here2 = std::get<0>( *it );
                    itype_id item_here2 = std::get<1>( *it );
                    int quantity_here2 = std::get<2>( *it );
                    if( comp_elem.type == item_here2 ) {
                        if( quantity_here2 >= remainder ) {
                            final_map.push_back( std::make_tuple( pos_here2, item_here2, remainder ) );
                            line_found = true;
                        } else {
                            final_map.push_back( std::make_tuple( pos_here2, item_here2, remainder ) );
                            remainder -= quantity_here2;
                        }
                    }
                    it--;
                }
            }
        }
    }
    for( const std::vector<tool_comp> &elem : tool_comps ) {
        bool line_found = false;
        for( const tool_comp &comp_elem : elem ) {
            if( line_found || comp_elem.count < -1 ) {
                break;
            }
            int quantity_required = std::max( 1, comp_elem.count );
            int item_quantity = 0;
            auto it = requirement_map.begin();
            int remainder = 0;
            while( it != requirement_map.end() ) {
                tripoint pos_here = std::get<0>( *it );
                itype_id item_here = std::get<1>( *it );
                int quantity_here = std::get<2>( *it );
                if( comp_elem.type == item_here ) {
                    item_quantity += quantity_here;
                }
                if( item_quantity >= quantity_required ) {
                    // it's just this spot that can fulfil the requirement on its own
                    final_map.push_back( std::make_tuple( pos_here, item_here, std::min<int>( quantity_here,
                                                          quantity_required ) ) );
                    if( quantity_here >= quantity_required ) {
                        line_found = true;
                        break;
                    } else {
                        remainder = quantity_required - quantity_here;
                    }
                    break;
                }
                it++;
            }
            if( line_found ) {
                while( true ) {
                    // go back over things
                    if( it == requirement_map.begin() ) {
                        break;
                    }
                    if( remainder <= 0 ) {
                        line_found = true;
                        break;
                    }
                    tripoint pos_here2 = std::get<0>( *it );
                    itype_id item_here2 = std::get<1>( *it );
                    int quantity_here2 = std::get<2>( *it );
                    if( comp_elem.type == item_here2 ) {
                        if( quantity_here2 >= remainder ) {
                            final_map.push_back( std::make_tuple( pos_here2, item_here2, remainder ) );
                            line_found = true;
                        } else {
                            final_map.push_back( std::make_tuple( pos_here2, item_here2, remainder ) );
                            remainder -= quantity_here2;
                        }
                    }
                    it--;
                }
            }
        }
    }
    for( const std::vector<quality_requirement> &elem : quality_comps ) {
        bool line_found = false;
        for( const quality_requirement &comp_elem : elem ) {
            if( line_found || comp_elem.count <= 0 ) {
                break;
            }
            const quality_id tool_qual = comp_elem.type;
            const int qual_level = comp_elem.level;
            for( auto it = requirement_map.begin(); it != requirement_map.end(); ) {
                tripoint pos_here = std::get<0>( *it );
                itype_id item_here = std::get<1>( *it );
                item test_item = item( item_here, calendar::start_of_cataclysm );
                if( test_item.has_quality( tool_qual, qual_level ) ) {
                    // it's just this spot that can fulfil the requirement on its own
                    final_map.push_back( std::make_tuple( pos_here, item_here, 1 ) );
                    line_found = true;
                    break;
                }
                it++;
            }
        }
    }
    for( const std::tuple<tripoint, itype_id, int> &elem : final_map ) {
        add_msg( m_debug, "%s is fetching %s from x: %d y: %d ", p.disp_name(),
                 std::get<1>( elem ).str(), std::get<0>( elem ).x, std::get<0>( elem ).y );
    }
    return final_map;
}
References ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_FARM, ACT_MULTIPLE_FISH, ACT_MULTIPLE_MINE, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, add_basecamp_storage_to_loot_zone_list(), add_msg(), are_requirements_nearby(), Character::backlog, Character::disp_name(), detail::find(), requirement_data::get_components(), zone_manager::get_manager(), get_map(), zone_manager::get_point_set_loot(), requirement_data::get_qualities(), requirement_data::get_tools(), map::getabs(), map::getlocal(), visitable< T >::has_quality(), map::i_at(), requirement_data::id(), player::is_npc(), m_debug, string_id< T >::obj(), PICKUP_RANGE, map::points_in_radius(), Character::pos(), and calendar::start_of_cataclysm.
Referenced by fetch_activity(), and generic_multi_activity_locations().
route_adjacent()
std::vector< tripoint > route_adjacent (const player & p, const tripoint & dest)
Definition at line 1024 of file activity_item_handling.cpp.
{
    auto passable_tiles = std::unordered_set<tripoint>();
    map &here = get_map();
    for( const tripoint &tp : here.points_in_radius( dest, 1 ) ) {
        if( tp != p.pos() && here.passable( tp ) && !here.obstructed_by_vehicle_rotation( dest, tp ) ) {
            passable_tiles.emplace( tp );
        }
    }
    const auto &sorted = get_sorted_tiles_by_distance( p.pos(), passable_tiles );
    const auto &avoid = p.get_path_avoid();
    for( const tripoint &tp : sorted ) {
        auto route = here.route( p.pos(), tp, p.get_pathfinding_settings(), avoid );
        if( !route.empty() ) {
            return route;
        }
    }
    return std::vector<tripoint>();
}
References get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), map::obstructed_by_vehicle_rotation(), map::passable(), map::points_in_radius(), Character::pos(), and map::route().
Referenced by activity_on_turn_move_loot(), activity_handlers::find_mount_do_turn(), generic_multi_activity_handler(), and generic_multi_activity_locations().
same_type()
static bool same_type (const std::list< item > & items) static
Definition at line 155 of file activity_item_handling.cpp.
{
    return std::all_of( items.begin(), items.end(), [&items]( const item & it ) {
        return it.type == items.begin()->type;
    } );
}
Referenced by drop_on_map(), Character::mutate_towards(), and put_into_vehicle().
stash_on_pet()
static void stash_on_pet (const std::list< item > & items, monster & pet, Character & who) static
Definition at line 281 of file activity_item_handling.cpp.
{
    units::volume remaining_volume = pet.storage_item->get_storage() - pet.get_carried_volume();
    units::mass remaining_weight = pet.weight_capacity() - pet.get_carried_weight();
    map &here = get_map();
    for( const item &it : items ) {
        if( it.volume() > remaining_volume ) {
            add_msg( m_bad, _( "%1$s did not fit and fell to the %2$s." ), it.display_name(),
                     here.name( pet.pos() ) );
            here.add_item_or_charges( pet.pos(), it );
        } else if( it.weight() > remaining_weight ) {
            add_msg( m_bad, _( "%1$s is too heavy and fell to the %2$s." ), it.display_name(),
                     here.name( pet.pos() ) );
            here.add_item_or_charges( pet.pos(), it );
        } else {
            pet.add_item( it );
            remaining_volume -= it.volume();
            remaining_weight -= it.weight();
        }
        // TODO: if NPCs can have pets or move items onto pets
        pass_to_ownership_handling( it, who );
    }
}
References _, monster::add_item(), map::add_item_or_charges(), add_msg(), monster::get_carried_volume(), monster::get_carried_weight(), get_map(), m_bad, map::name(), pass_to_ownership_handling(), monster::pos(), monster::storage_item, and monster::weight_capacity().
Referenced by stash_activity_actor::do_turn().
tidy_activity()
static bool tidy_activity (player & p, const tripoint & src_loc, const activity_id & activity_to_restore, const int distance = ACTIVITY_SEARCH_DISTANCE) static
Definition at line 1945 of file activity_item_handling.cpp.
{
    auto &mgr = zone_manager::get_manager();
    map &here = get_map();
    tripoint loot_abspos = here.getabs( src_loc );
    tripoint loot_src_lot;
    const auto &zone_src_set = mgr.get_near( zone_type_LOOT_UNSORTED, loot_abspos, distance );
    if( !zone_src_set.empty() ) {
        const auto &zone_src_sorted = get_sorted_tiles_by_distance( loot_abspos, zone_src_set );
        // Find the nearest unsorted zone to dump objects at
        for( auto &src_elem : zone_src_sorted ) {
            if( !here.can_put_items_ter_furn( here.getlocal( src_elem ) ) ) {
                continue;
            }
            loot_src_lot = here.getlocal( src_elem );
            break;
        }
    }
    if( loot_src_lot == tripoint_zero ) {
        return false;
    }
    auto items_there = here.i_at( src_loc );
    vehicle *dest_veh;
    int dest_part;
    if( const cata::optional<vpart_reference> vp = here.veh_at(
                loot_src_lot ).part_with_feature( "CARGO",
                        false ) ) {
        dest_veh = &vp->vehicle();
        dest_part = vp->part_index();
    } else {
        dest_veh = nullptr;
        dest_part = -1;
    }
    for( auto &it : items_there ) {
        if( it.has_var( "activity_var" ) && it.get_var( "activity_var", "" ) == p.name ) {
            move_item( p, it, it.count(), src_loc, loot_src_lot, dest_veh, dest_part,
                       activity_to_restore );
            break;
        }
    }
    // we are adjacent to an unsorted zone, we came here to just drop items we are carrying
    if( mgr.has( zone_type_LOOT_UNSORTED, here.getabs( src_loc ) ) ) {
        for( item *inv_elem : p.inv_dump() ) {
            if( inv_elem->has_var( "activity_var" ) ) {
                inv_elem->erase_var( "activity_var" );
                put_into_vehicle_or_drop( p, item_drop_reason::deliberate, { *inv_elem }, src_loc );
                p.i_rem( inv_elem );
            }
        }
    }
    return true;
}
References map::can_put_items_ter_furn(), item::count(), deliberate, zone_manager::get_manager(), get_map(), get_sorted_tiles_by_distance(), item::get_var(), map::getabs(), map::getlocal(), item::has_var(), map::i_at(), Character::i_rem(), Character::inv_dump(), move_item(), Character::name, optional_vpart_position::part_with_feature(), put_into_vehicle_or_drop(), tripoint_zero, map::veh_at(), vehicle::vehicle(), and zone_type_LOOT_UNSORTED.
Referenced by generic_multi_activity_do().
try_fuel_fire()
void try_fuel_fire (player_activity & act, player & p, const bool starting_fire)
Definition at line 3241 of file activity_item_handling.cpp.
{
    const tripoint pos = p.pos();
    std::vector<tripoint> adjacent = closest_points_first( pos, PICKUP_RANGE );
    adjacent.erase( adjacent.begin() );
    cata::optional<tripoint> best_fire = starting_fire ? act.placement : find_best_fire( adjacent,
                                         pos );
    map &here = get_map();
    if( !best_fire || !here.accessible_items( *best_fire ) ) {
        return;
    }
    cata::optional<tripoint> refuel_spot = find_refuel_spot_zone( pos );
    if( !refuel_spot ) {
        refuel_spot = find_refuel_spot_trap( adjacent, pos );
        if( !refuel_spot ) {
            return;
        }
    }
    // Special case: fire containers allow burning logs, so use them as fuel if fire is contained
    bool contained = here.has_flag_furn( TFLAG_FIRE_CONTAINER, *best_fire );
    fire_data fd( 1, contained );
    time_duration fire_age = here.get_field_age( *best_fire, fd_fire );
    // Maybe TODO: - refueling in the rain could use more fuel
    // First, simulate expected burn per turn, to see if we need more fuel
    map_stack fuel_on_fire = here.i_at( *best_fire );
    for( item &it : fuel_on_fire ) {
        it.simulate_burn( fd );
        // Unconstrained fires grow below -50_minutes age
        if( !contained && fire_age < -40_minutes && fd.fuel_produced > 1.0f && !it.made_of( LIQUID ) ) {
            // Too much - we don't want a firestorm!
            // Move item back to refueling pile
            // Note: move_item() handles messages (they're the generic "you drop x")
            move_item( p, it, 0, *best_fire, *refuel_spot, nullptr, -1 );
            return;
        }
    }
    // Enough to sustain the fire
    // TODO: It's not enough in the rain
    if( !starting_fire && ( fd.fuel_produced >= 1.0f || fire_age < 10_minutes ) ) {
        return;
    }
    // We need to move fuel from stash to fire
    map_stack potential_fuel = here.i_at( *refuel_spot );
    for( item &it : potential_fuel ) {
        if( it.made_of( LIQUID ) ) {
            continue;
        }
        float last_fuel = fd.fuel_produced;
        it.simulate_burn( fd );
        if( fd.fuel_produced > last_fuel ) {
            int quantity = std::max( 1, std::min( it.charges, it.charges_per_volume( 250_ml ) ) );
            // Note: move_item() handles messages (they're the generic "you drop x")
            move_item( p, it, quantity, *refuel_spot, *best_fire, nullptr, -1 );
            return;
        }
    }
}
References map::accessible_items(), act, item::charges, item::charges_per_volume(), closest_points_first(), fd_fire, find_best_fire(), find_refuel_spot_trap(), find_refuel_spot_zone(), fire_data::fuel_produced, map::get_field_age(), get_map(), map::has_flag_furn(), map::i_at(), LIQUID, item::made_of(), move_item(), PICKUP_RANGE, Character::pos(), item::simulate_burn(), and TFLAG_FIRE_CONTAINER.
Referenced by player_activity::do_turn(), and activity_handlers::start_fire_do_turn().
vehicle_activity()
static bool vehicle_activity (player & p, const tripoint & src_loc, int vpindex, char type) static
Definition at line 919 of file activity_item_handling.cpp.
{
    map &here = get_map();
    vehicle *veh = veh_pointer_or_null( here.veh_at( src_loc ) );
    if( !veh ) {
        return false;
    }
    int time_to_take = 0;
    if( vpindex >= veh->part_count() ) {
        // if parts got removed during our work, we can't just carry on removing, we want to repair parts!
        // so just bail out, as we don't know if the next shifted part is suitable for repair.
        if( type == 'r' ) {
            return false;
        } else if( type == 'o' ) {
            vpindex = veh->get_next_shifted_index( vpindex, p );
            if( vpindex == -1 ) {
                return false;
            }
        }
    }
    const vpart_info &vp = veh->part_info( vpindex );
    if( type == 'r' ) {
        const vehicle_part part = veh->part( vpindex );
        time_to_take = vp.repair_time( p ) * part.damage() / part.max_damage();
    } else if( type == 'o' ) {
        time_to_take = vp.removal_time( p );
    }
    p.assign_activity( ACT_VEHICLE, time_to_take, static_cast<int>( type ) );
    // so , NPCs can remove the last part on a position, then there is no vehicle there anymore,
    // for someone else who stored that position at the start of their activity.
    // so we may need to go looking a bit further afield to find it , at activities end.
    for( const auto pt : veh->get_points( true ) ) {
        p.activity.coord_set.insert( here.getabs( pt ) );
    }
    // values[0]
    p.activity.values.push_back( here.getabs( src_loc ).x );
    // values[1]
    p.activity.values.push_back( here.getabs( src_loc ).y );
    // values[2]
    p.activity.values.push_back( point_zero.x );
    // values[3]
    p.activity.values.push_back( point_zero.y );
    // values[4]
    p.activity.values.push_back( -point_zero.x );
    // values[5]
    p.activity.values.push_back( -point_zero.y );
    // values[6]
    p.activity.values.push_back( veh->index_of_part( &veh->part( vpindex ) ) );
    p.activity.str_values.push_back( vp.get_id().str() );
    // values[7]
    p.activity.values.push_back( here.getabs( src_loc ).z );
    // this would only be used for refilling tasks
    item_location target;
    p.activity.targets.emplace_back( std::move( target ) );
    p.activity.placement = here.getabs( src_loc );
    p.activity_vehicle_part_index = -1;
    return true;
}
References ACT_VEHICLE, Character::activity, Character::activity_vehicle_part_index, Character::assign_activity(), player_activity::coord_set, vehicle_part::damage(), vpart_info::get_id(), get_map(), vehicle::get_next_shifted_index(), vehicle::get_points(), map::getabs(), vehicle::index_of_part(), vehicle_part::max_damage(), avatar_action::move(), vehicle::part(), vehicle::part_count(), vehicle::part_info(), player_activity::placement, point_zero, vpart_info::removal_time(), vpart_info::repair_time(), string_id< T >::str(), player_activity::str_values, player_activity::targets, type, player_activity::values, map::veh_at(), veh_pointer_or_null(), point::x, tripoint::x, point::y, tripoint::y, and tripoint::z.
Referenced by generic_multi_activity_do().
Variable Documentation
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by construction_activity(), and generic_multi_activity_do().
ACT_BUTCHER_FULL
const activity_id ACT_BUTCHER_FULL("ACT_BUTCHER_FULL") ("ACT_BUTCHER_FULL") static
Referenced by butcher_corpse_activity().
ACT_CHOP_LOGS
const activity_id ACT_CHOP_LOGS("ACT_CHOP_LOGS") ("ACT_CHOP_LOGS") static
Referenced by chop_tree_activity().
ACT_CHOP_PLANKS
const activity_id ACT_CHOP_PLANKS("ACT_CHOP_PLANKS") ("ACT_CHOP_PLANKS") static
Referenced by chop_plank_activity().
ACT_CHOP_TREE
const activity_id ACT_CHOP_TREE("ACT_CHOP_TREE") ("ACT_CHOP_TREE") static
Referenced by chop_tree_activity().
ACT_CHURN
const activity_id ACT_CHURN("ACT_CHURN") ("ACT_CHURN") static
Referenced by generic_multi_activity_do().
ACT_FETCH_REQUIRED
const activity_id ACT_FETCH_REQUIRED("ACT_FETCH_REQUIRED") ("ACT_FETCH_REQUIRED") static
Referenced by can_do_activity_there(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_zone_for_act(), and move_item().
ACT_FISH
const activity_id ACT_FISH("ACT_FISH") ("ACT_FISH") static
Referenced by generic_multi_activity_do().
ACT_JACKHAMMER
const activity_id ACT_JACKHAMMER("ACT_JACKHAMMER") ("ACT_JACKHAMMER") static
Referenced by mine_activity().
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
Referenced by activity_on_turn_move_loot(), and generic_multi_activity_handler().
ACT_MULTIPLE_BUTCHER
const activity_id ACT_MULTIPLE_BUTCHER("ACT_MULTIPLE_BUTCHER") ("ACT_MULTIPLE_BUTCHER") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), get_zone_for_act(), and requirements_map().
ACT_MULTIPLE_CHOP_PLANKS
const activity_id ACT_MULTIPLE_CHOP_PLANKS("ACT_MULTIPLE_CHOP_PLANKS") ("ACT_MULTIPLE_CHOP_PLANKS") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), get_zone_for_act(), and requirements_map().
ACT_MULTIPLE_CHOP_TREES
const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES") ("ACT_MULTIPLE_CHOP_TREES") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), get_zone_for_act(), and requirements_map().
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
Referenced by can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), generic_multi_activity_locations(), and get_zone_for_act().
ACT_MULTIPLE_FARM
const activity_id ACT_MULTIPLE_FARM("ACT_MULTIPLE_FARM") ("ACT_MULTIPLE_FARM") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), generic_multi_activity_locations(), get_zone_for_act(), and requirements_map().
ACT_MULTIPLE_FISH
const activity_id ACT_MULTIPLE_FISH("ACT_MULTIPLE_FISH") ("ACT_MULTIPLE_FISH") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), generic_multi_activity_locations(), get_zone_for_act(), and requirements_map().
ACT_MULTIPLE_MINE
const activity_id ACT_MULTIPLE_MINE("ACT_MULTIPLE_MINE") ("ACT_MULTIPLE_MINE") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), get_zone_for_act(), and requirements_map().
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
Referenced by mine_activity().
ACT_TIDY_UP
const activity_id ACT_TIDY_UP("ACT_TIDY_UP") ("ACT_TIDY_UP") static
Referenced by can_do_activity_there(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), and move_item().
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
Referenced by vehicle_activity().
ACT_VEHICLE_DECONSTRUCTION
const activity_id ACT_VEHICLE_DECONSTRUCTION("ACT_VEHICLE_DECONSTRUCTION") ("ACT_VEHICLE_DECONSTRUCTION") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), get_zone_for_act(), and requirements_map().
ACT_VEHICLE_REPAIR
const activity_id ACT_VEHICLE_REPAIR("ACT_VEHICLE_REPAIR") ("ACT_VEHICLE_REPAIR") static
Referenced by are_requirements_nearby(), can_do_activity_there(), fetch_activity(), generic_multi_activity_check_requirement(), get_zone_for_act(), and requirements_map().
ACTIVITY_SEARCH_DISTANCE
const int ACTIVITY_SEARCH_DISTANCE = 60
Definition at line 153 of file activity_item_handling.cpp.
Referenced by activity_on_turn_move_loot(), add_basecamp_storage_to_loot_zone_list(), find_auto_consume(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), and generic_multi_activity_locations().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by find_auto_consume().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by stash_activity_actor::do_turn().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by are_requirements_nearby().
itype_detergent
const itype_id itype_detergent("detergent") ("detergent") static
Referenced by wash_activity_actor::finish().
itype_log
const itype_id itype_log("log") ("log") static
Referenced by can_do_activity_there(), and chop_plank_activity().
itype_soap
const itype_id itype_soap("soap") ("soap") static
Referenced by wash_activity_actor::finish().
itype_soldering_iron
const itype_id itype_soldering_iron("soldering_iron") ("soldering_iron") static
Referenced by are_requirements_nearby().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by wash_activity_actor::finish().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by wash_activity_actor::finish().
itype_welder
const itype_id itype_welder("welder") ("welder") static
Referenced by are_requirements_nearby().
qual_AXE
const quality_id qual_AXE("AXE") ("AXE") static
Referenced by can_do_activity_there(), chop_plank_activity(), chop_tree_activity(), generic_multi_activity_check_requirement(), and generic_multi_activity_do().
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static
Referenced by can_do_activity_there(), and generic_multi_activity_check_requirement().
qual_DIG
const quality_id qual_DIG("DIG") ("DIG") static
Referenced by can_do_activity_there(), generic_multi_activity_check_requirement(), and generic_multi_activity_do().
qual_FISHING
const quality_id qual_FISHING("FISHING") ("FISHING") static
Referenced by generic_multi_activity_check_requirement(), and generic_multi_activity_do().
qual_SAW_M
const quality_id qual_SAW_M("SAW_M") ("SAW_M") static
Referenced by generic_multi_activity_check_requirement().
qual_SAW_W
const quality_id qual_SAW_W("SAW_W") ("SAW_W") static
Referenced by generic_multi_activity_check_requirement().
qual_WELD
const quality_id qual_WELD("WELD") ("WELD") static
Referenced by are_requirements_nearby().
tr_firewood_source
const trap_str_id tr_firewood_source("tr_firewood_source") ("tr_firewood_source") static
tr_unfinished_construction
const trap_str_id tr_unfinished_construction("tr_unfinished_construction") ("tr_unfinished_construction") static
Referenced by construction_activity().
z_camp_storage
const zone_type_id z_camp_storage("CAMP_STORAGE") ("CAMP_STORAGE") static
Referenced by add_basecamp_storage_to_loot_zone_list(), and can_do_activity_there().
zone_type_CHOP_TREES
const zone_type_id zone_type_CHOP_TREES("CHOP_TREES") ("CHOP_TREES") static
Referenced by get_zone_for_act().
zone_type_CONSTRUCTION_BLUEPRINT
const zone_type_id zone_type_CONSTRUCTION_BLUEPRINT("CONSTRUCTION_BLUEPRINT") ("CONSTRUCTION_BLUEPRINT") static
Referenced by can_do_activity_there(), and get_zone_for_act().
zone_type_FARM_PLOT
const zone_type_id zone_type_FARM_PLOT("FARM_PLOT") ("FARM_PLOT") static
Referenced by can_do_activity_there(), generic_multi_activity_do(), and get_zone_for_act().
zone_type_FISHING_SPOT
const zone_type_id zone_type_FISHING_SPOT("FISHING_SPOT") ("FISHING_SPOT") static
Referenced by get_zone_for_act().
zone_type_LOOT_CORPSE
const zone_type_id zone_type_LOOT_CORPSE("LOOT_CORPSE") ("LOOT_CORPSE") static
Referenced by get_zone_for_act().
zone_type_LOOT_IGNORE
const zone_type_id zone_type_LOOT_IGNORE("LOOT_IGNORE") ("LOOT_IGNORE") static
Referenced by activity_on_turn_move_loot(), and are_requirements_nearby().
zone_type_LOOT_IGNORE_FAVORITES
const zone_type_id zone_type_LOOT_IGNORE_FAVORITES("LOOT_IGNORE_FAVORITES") ("LOOT_IGNORE_FAVORITES") static
Referenced by activity_on_turn_move_loot().
zone_type_LOOT_UNSORTED
const zone_type_id zone_type_LOOT_UNSORTED("LOOT_UNSORTED") ("LOOT_UNSORTED") static
Referenced by activity_on_turn_move_loot(), can_do_activity_there(), generic_multi_activity_locations(), and tidy_activity().
zone_type_LOOT_WOOD
const zone_type_id zone_type_LOOT_WOOD("LOOT_WOOD") ("LOOT_WOOD") static
Referenced by get_zone_for_act().
zone_type_MINING
const zone_type_id zone_type_MINING("MINING") ("MINING") static
Referenced by get_zone_for_act().
zone_type_source_firewood
const zone_type_id zone_type_source_firewood("SOURCE_FIREWOOD") ("SOURCE_FIREWOOD") static
Referenced by find_refuel_spot_zone().
zone_type_VEHICLE_DECONSTRUCT
const zone_type_id zone_type_VEHICLE_DECONSTRUCT("VEHICLE_DECONSTRUCT") ("VEHICLE_DECONSTRUCT") static
Referenced by get_zone_for_act().
zone_type_VEHICLE_REPAIR
const zone_type_id zone_type_VEHICLE_REPAIR("VEHICLE_REPAIR") ("VEHICLE_REPAIR") static
Referenced by get_zone_for_act().