Cataclysm BN: src/activity_handlers.h File Reference
activity_handlers.h File Reference
#include <functional>
#include <list>
#include <map>
#include <string>
#include <unordered_set>
#include <vector>
#include "optional.h"
#include "type_id.h"
Classes
struct activity_reason_info
struct butchery_setup
Namespaces
namespace activity_handlers
namespace activity_handlers::repair_activity_hack
Macros
#define CATA_SRC_ACTIVITY_HANDLERS_H
Enumerations
enum requirement_check_result : int { SKIP_LOCATION = 0 , CAN_DO_LOCATION , RETURN_EARLY }
enum butcher_type : int {
BUTCHER , BUTCHER_FULL , F_DRESS , SKIN ,
QUARTER , DISMEMBER , DISSECT
}
enum class do_activity_reason : int {
CAN_DO_CONSTRUCTION , CAN_DO_FETCH , CAN_DO_PREREQ , CAN_DO_PREREQ_2 ,
NO_COMPONENTS , NO_COMPONENTS_PREREQ , NO_COMPONENTS_PREREQ_2 , DONT_HAVE_SKILL ,
NO_ZONE , ALREADY_DONE , UNKNOWN_ACTIVITY , NEEDS_HARVESTING ,
NEEDS_PLANTING , NEEDS_TILLING , BLOCKING_TILE , NEEDS_CHOPPING ,
NEEDS_TREE_CHOPPING , NEEDS_BIG_BUTCHERING , NEEDS_BUTCHERING , ALREADY_WORKING ,
NEEDS_VEH_DECONST , NEEDS_VEH_REPAIR , NEEDS_MINING , NEEDS_FISHING
}
enum class butchery_possibility : int { yes = 0 , need_confirmation , never , not_this }
enum class item_drop_reason { deliberate , too_large , too_heavy , tumbling }
Functions
std::vector< tripoint > get_sorted_tiles_by_distance (const tripoint &abspos, const std::unordered_set< tripoint > &tiles)
std::vector< tripoint > route_adjacent (const player &p, const tripoint &dest)
butchery_setup consider_butchery (const item &corpse_item, player &u, butcher_type action)
int butcher_time_to_cut (const inventory &inv, const item &corpse_item, butcher_type action)
void activity_on_turn_drop ()
void activity_on_turn_move_loot (player_activity &act, player &p)
bool generic_multi_activity_handler (player_activity &act, player &p, bool check_only=false)
void activity_on_turn_fetch (player_activity &, player *p)
void activity_on_turn_wear (player_activity &act, player &p)
bool find_auto_consume (player &p, bool food)
void try_fuel_fire (player_activity &act, player &p, bool starting_fire=false)
void put_into_vehicle_or_drop (Character &c, item_drop_reason, const std::list< item > &items)
void put_into_vehicle_or_drop (Character &c, item_drop_reason, const std::list< item > &items, const tripoint &where, bool force_ground=false)
void drop_on_map (Character &c, item_drop_reason reason, const std::list< item > &items, const tripoint &where)
bool activity_handlers::resume_for_multi_activities (player &p)
void activity_handlers::burrow_do_turn (player_activity *act, player *p)
activity_do_turn functions:
void activity_handlers::craft_do_turn (player_activity *act, player *p)
void activity_handlers::fill_liquid_do_turn (player_activity *act, player *p)
void activity_handlers::pickaxe_do_turn (player_activity *act, player *p)
void activity_handlers::drop_do_turn (player_activity *act, player *p)
void activity_handlers::stash_do_turn (player_activity *act, player *p)
void activity_handlers::pulp_do_turn (player_activity *act, player *p)
void activity_handlers::game_do_turn (player_activity *act, player *p)
void activity_handlers::generic_game_do_turn (player_activity *act, player *p)
void activity_handlers::churn_do_turn (player_activity *act, player *p)
void activity_handlers::start_fire_do_turn (player_activity *act, player *p)
void activity_handlers::vibe_do_turn (player_activity *act, player *p)
void activity_handlers::hand_crank_do_turn (player_activity *act, player *p)
void activity_handlers::multiple_chop_planks_do_turn (player_activity *act, player *p)
void activity_handlers::oxytorch_do_turn (player_activity *act, player *p)
void activity_handlers::wear_do_turn (player_activity *act, player *p)
void activity_handlers::eat_menu_do_turn (player_activity *act, player *p)
void activity_handlers::consume_food_menu_do_turn (player_activity *act, player *p)
void activity_handlers::consume_drink_menu_do_turn (player_activity *act, player *p)
void activity_handlers::consume_meds_menu_do_turn (player_activity *act, player *p)
void activity_handlers::move_items_do_turn (player_activity *act, player *p)
void activity_handlers::multiple_farm_do_turn (player_activity *act, player *p)
void activity_handlers::multiple_fish_do_turn (player_activity *act, player *p)
void activity_handlers::multiple_construction_do_turn (player_activity *act, player *p)
void activity_handlers::multiple_mine_do_turn (player_activity *act, player *p)
void activity_handlers::multiple_butcher_do_turn (player_activity *act, player *p)
void activity_handlers::vehicle_deconstruction_do_turn (player_activity *act, player *p)
void activity_handlers::vehicle_repair_do_turn (player_activity *act, player *p)
void activity_handlers::chop_trees_do_turn (player_activity *act, player *p)
void activity_handlers::fetch_do_turn (player_activity *act, player *p)
void activity_handlers::move_loot_do_turn (player_activity *act, player *p)
void activity_handlers::travel_do_turn (player_activity *act, player *p)
void activity_handlers::adv_inventory_do_turn (player_activity *act, player *p)
void activity_handlers::armor_layers_do_turn (player_activity *act, player *p)
void activity_handlers::atm_do_turn (player_activity *act, player *p)
void activity_handlers::fish_do_turn (player_activity *act, player *p)
void activity_handlers::cracking_do_turn (player_activity *act, player *p)
void activity_handlers::repair_item_do_turn (player_activity *act, player *p)
void activity_handlers::butcher_do_turn (player_activity *act, player *p)
void activity_handlers::pry_nails_do_turn (player_activity *act, player *p)
void activity_handlers::hacksaw_do_turn (player_activity *act, player *p)
void activity_handlers::chop_tree_do_turn (player_activity *act, player *p)
void activity_handlers::jackhammer_do_turn (player_activity *act, player *p)
void activity_handlers::find_mount_do_turn (player_activity *act, player *p)
void activity_handlers::tidy_up_do_turn (player_activity *act, player *p)
void activity_handlers::build_do_turn (player_activity *act, player *p)
void activity_handlers::fill_pit_do_turn (player_activity *act, player *p)
void activity_handlers::fertilize_plot_do_turn (player_activity *act, player *p)
void activity_handlers::try_sleep_do_turn (player_activity *act, player *p)
void activity_handlers::operation_do_turn (player_activity *act, player *p)
void activity_handlers::robot_control_do_turn (player_activity *act, player *p)
void activity_handlers::tree_communion_do_turn (player_activity *act, player *p)
void activity_handlers::spellcasting_do_turn (player_activity *act, player *p)
void activity_handlers::study_spell_do_turn (player_activity *act, player *p)
void activity_handlers::read_do_turn (player_activity *act, player *p)
void activity_handlers::wait_stamina_do_turn (player_activity *act, player *p)
void activity_handlers::burrow_finish (player_activity *act, player *p)
activity_finish functions:
void activity_handlers::butcher_finish (player_activity *act, player *p)
void activity_handlers::firstaid_finish (player_activity *act, player *p)
void activity_handlers::fish_finish (player_activity *act, player *p)
void activity_handlers::forage_finish (player_activity *act, player *p)
void activity_handlers::hotwire_finish (player_activity *act, player *p)
void activity_handlers::longsalvage_finish (player_activity *act, player *p)
void activity_handlers::pulp_finish (player_activity *act, player *p)
void activity_handlers::make_zlave_finish (player_activity *act, player *p)
void activity_handlers::pickaxe_finish (player_activity *act, player *p)
void activity_handlers::reload_finish (player_activity *act, player *p)
void activity_handlers::start_fire_finish (player_activity *act, player *p)
void activity_handlers::train_finish (player_activity *act, player *p)
void activity_handlers::milk_finish (player_activity *act, player *p)
void activity_handlers::shear_finish (player_activity *act, player *p)
void activity_handlers::vehicle_finish (player_activity *act, player *p)
void activity_handlers::start_engines_finish (player_activity *act, player *p)
void activity_handlers::churn_finish (player_activity *act, player *p)
void activity_handlers::plant_seed_finish (player_activity *act, player *p)
void activity_handlers::oxytorch_finish (player_activity *act, player *p)
void activity_handlers::cracking_finish (player_activity *act, player *p)
void activity_handlers::lockpicking_finish (player_activity *act, player *p)
void activity_handlers::repair_item_finish (player_activity *act, player *p)
void activity_handlers::mend_item_finish (player_activity *act, player *p)
void activity_handlers::gunmod_add_finish (player_activity *act, player *p)
void activity_handlers::toolmod_add_finish (player_activity *act, player *p)
void activity_handlers::clear_rubble_finish (player_activity *act, player *p)
void activity_handlers::meditate_finish (player_activity *act, player *p)
void activity_handlers::read_finish (player_activity *act, player *p)
void activity_handlers::wait_finish (player_activity *act, player *p)
void activity_handlers::wait_weather_finish (player_activity *act, player *p)
void activity_handlers::wait_npc_finish (player_activity *act, player *p)
void activity_handlers::wait_stamina_finish (player_activity *act, player *p)
void activity_handlers::socialize_finish (player_activity *act, player *p)
void activity_handlers::try_sleep_finish (player_activity *act, player *p)
void activity_handlers::operation_finish (player_activity *act, player *p)
void activity_handlers::vibe_finish (player_activity *act, player *p)
void activity_handlers::hand_crank_finish (player_activity *act, player *p)
void activity_handlers::atm_finish (player_activity *act, player *p)
void activity_handlers::eat_menu_finish (player_activity *act, player *p)
void activity_handlers::washing_finish (player_activity *act, player *p)
void activity_handlers::hacksaw_finish (player_activity *act, player *p)
void activity_handlers::pry_nails_finish (player_activity *act, player *p)
void activity_handlers::chop_tree_finish (player_activity *act, player *p)
void activity_handlers::chop_logs_finish (player_activity *act, player *p)
void activity_handlers::chop_planks_finish (player_activity *act, player *p)
void activity_handlers::jackhammer_finish (player_activity *act, player *p)
void activity_handlers::fill_pit_finish (player_activity *act, player *p)
void activity_handlers::play_with_pet_finish (player_activity *act, player *p)
void activity_handlers::shaving_finish (player_activity *act, player *p)
void activity_handlers::haircut_finish (player_activity *act, player *p)
void activity_handlers::unload_mag_finish (player_activity *act, player *p)
void activity_handlers::robot_control_finish (player_activity *act, player *p)
void activity_handlers::mind_splicer_finish (player_activity *act, player *p)
void activity_handlers::spellcasting_finish (player_activity *act, player *p)
void activity_handlers::study_spell_finish (player_activity *act, player *p)
void activity_handlers::try_sleep_query (player_activity *act, player *p)
void activity_handlers::repair_activity_hack::patch_activity_for_vehicle_welder (player_activity &activity, const tripoint &veh_part_position, const vehicle &veh, int interact_part_idx)
void activity_handlers::repair_activity_hack::patch_activity_for_furniture (player_activity &activity, const tripoint &furniture_position)
Variables
const std::map< activity_id, std::function< void(player_activity *, player *)> > activity_handlers::do_turn_functions
const std::map< activity_id, std::function< void(player_activity *, player *)> > activity_handlers::finish_functions
Macro Definition Documentation
CATA_SRC_ACTIVITY_HANDLERS_H
#define CATA_SRC_ACTIVITY_HANDLERS_H
Definition at line 3 of file activity_handlers.h.
Enumeration Type Documentation
butcher_type
enum butcher_type : int
Enumerator
BUTCHER
BUTCHER_FULL
F_DRESS
SKIN
QUARTER
DISMEMBER
DISSECT
Definition at line 35 of file activity_handlers.h.
                  : int {
    BUTCHER,        // quick butchery
    BUTCHER_FULL,   // full workshop butchery
    F_DRESS,        // field dressing a corpse
    SKIN,           // skinning a corpse
    QUARTER,        // quarter a corpse
    DISMEMBER,      // destroy a corpse
    DISSECT         // dissect a corpse for CBMs
};
butchery_possibility
enum class butchery_possibility : int strong
Enumerator
yes
need_confirmation
never
not_this
Definition at line 101 of file activity_handlers.h.
                                : int {
    yes = 0,
    need_confirmation,
    never,
    not_this
};
do_activity_reason
enum class do_activity_reason : int strong
Enumerator
CAN_DO_CONSTRUCTION
CAN_DO_FETCH
CAN_DO_PREREQ
CAN_DO_PREREQ_2
NO_COMPONENTS
NO_COMPONENTS_PREREQ
NO_COMPONENTS_PREREQ_2
DONT_HAVE_SKILL
NO_ZONE
ALREADY_DONE
UNKNOWN_ACTIVITY
NEEDS_HARVESTING
NEEDS_PLANTING
NEEDS_TILLING
BLOCKING_TILE
NEEDS_CHOPPING
NEEDS_TREE_CHOPPING
NEEDS_BIG_BUTCHERING
NEEDS_BUTCHERING
ALREADY_WORKING
NEEDS_VEH_DECONST
NEEDS_VEH_REPAIR
NEEDS_MINING
NEEDS_FISHING
Definition at line 45 of file activity_handlers.h.
                              : int {
    CAN_DO_CONSTRUCTION,    // Can do construction.
    CAN_DO_FETCH,           // Can do fetch - this is usually the default result for fetch task
    CAN_DO_PREREQ,          // for constructions - can't build the main construction, but can build the pre-req
    CAN_DO_PREREQ_2,        // Can do the second pre-req deep below the desired one.
    NO_COMPONENTS,          // can't do the activity there due to lack of components /tools
    NO_COMPONENTS_PREREQ,   // need components to build the pre-requisite for the actual desired construction
    NO_COMPONENTS_PREREQ_2, // need components to the second pre-req deep.
    DONT_HAVE_SKILL,        // don't have the required skill
    NO_ZONE,                // There is no required zone anymore
    ALREADY_DONE,           // the activity is done already ( maybe by someone else )
    UNKNOWN_ACTIVITY,       // This is probably an error - got to the end of function with no previous reason
    NEEDS_HARVESTING,       // For farming - tile is harvestable now.
    NEEDS_PLANTING,         // For farming - tile can be planted
    NEEDS_TILLING,          // For farming - tile can be tilled
    BLOCKING_TILE,           // Something has made it's way onto the tile, so the activity cannot proceed
    NEEDS_CHOPPING,         // There is wood there to be chopped
    NEEDS_TREE_CHOPPING,    // There is a tree there that needs to be chopped
    NEEDS_BIG_BUTCHERING,   // There is at least one corpse there to butcher, and it's a big one
    NEEDS_BUTCHERING,       // THere is at least one corpse there to butcher, and there's no need for additional tools
    ALREADY_WORKING,        // somebody is already working there
    NEEDS_VEH_DECONST,       // There is a vehicle part there that we can deconstruct, given the right tools.
    NEEDS_VEH_REPAIR,       // There is a vehicle part there that can be repaired, given the right tools.
    NEEDS_MINING,           // This spot can be mined, if the right tool is present.
    NEEDS_FISHING           // This spot can be fished, if the right tool is present.
};
item_drop_reason
enum class item_drop_reason strong
Enumerator
deliberate
too_large
too_heavy
tumbling
Definition at line 129 of file activity_handlers.h.
{
    deliberate,
    too_large,
    too_heavy,
    tumbling
};
requirement_check_result
enum requirement_check_result : int
Enumerator
SKIP_LOCATION
CAN_DO_LOCATION
RETURN_EARLY
Definition at line 29 of file activity_handlers.h.
                              : int {
    SKIP_LOCATION = 0,
    CAN_DO_LOCATION,
    RETURN_EARLY       //another activity like a fetch activity has been started.
};
Function Documentation
activity_on_turn_drop()
void activity_on_turn_drop ()
activity_on_turn_fetch()
void activity_on_turn_fetch (player_activity & , player * p)
activity_on_turn_move_loot()
void activity_on_turn_move_loot (player_activity & act, player & p)
Definition at line 2137 of file activity_item_handling.cpp.
{
    enum activity_stage : int {
        //Initial stage
        INIT = 0,
        //Think about what to do first: choose destination
        THINK,
        //Do activity
        DO,
    };
    int &stage = act.index;
    //Prepare activity stage
    if( stage < 0 ) {
        stage = INIT;
        //num_processed
        act.values.push_back( 0 );
    }
    int &num_processed = act.values[ 0 ];
    map &here = get_map();
    const auto abspos = here.getabs( p.pos() );
    auto &mgr = zone_manager::get_manager();
    if( here.check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    if( stage == INIT ) {
        act.coord_set = mgr.get_near( zone_type_LOOT_UNSORTED, abspos, ACTIVITY_SEARCH_DISTANCE );
        stage = THINK;
    }
    if( stage == THINK ) {
        //initialize num_processed
        num_processed = 0;
        const auto &src_set = act.coord_set;
        // sort source tiles by distance
        const auto &src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
        for( auto &src : src_sorted ) {
            act.placement = src;
            act.coord_set.erase( src );
            const auto &src_loc = here.getlocal( src );
            if( !here.inbounds( src_loc ) ) {
                if( !here.inbounds( p.pos() ) ) {
                    // p is implicitly an NPC that has been moved off the map, so reset the activity
                    // and unload them
                    p.cancel_activity();
                    p.assign_activity( ACT_MOVE_LOOT );
                    p.set_moves( 0 );
                    g->reload_npcs();
                    return;
                }
                std::vector<tripoint> route;
                route = here.route( p.pos(), src_loc, p.get_pathfinding_settings(),
                                    p.get_path_avoid() );
                if( route.empty() ) {
                    // can't get there, can't do anything, skip it
                    continue;
                }
                stage = DO;
                p.set_destination( route, act );
                p.activity.set_to_null();
                return;
            }
            // skip tiles in IGNORE zone and tiles on fire
            // (to prevent taking out wood off the lit brazier)
            // and inaccessible furniture, like filled charcoal kiln
            if( mgr.has( zone_type_LOOT_IGNORE, src ) ||
                here.get_field( src_loc, fd_fire ) != nullptr ||
                !here.can_put_items_ter_furn( src_loc ) ) {
                continue;
            }
            //nothing to sort?
            const cata::optional<vpart_reference> vp = here.veh_at( src_loc ).part_with_feature( "CARGO",
                    false );
            if( ( !vp || vp->vehicle().get_items( vp->part_index() ).empty() )
                && here.i_at( src_loc ).empty() ) {
                continue;
            }
            bool is_adjacent_or_closer = square_dist( p.pos(), src_loc ) <= 1;
            // before we move any item, check if player is at or
            // adjacent to the loot source tile
            if( !is_adjacent_or_closer ) {
                std::vector<tripoint> route;
                bool adjacent = false;
                // get either direct route or route to nearest adjacent tile if
                // source tile is impassable
                if( here.passable( src_loc ) ) {
                    route = here.route( p.pos(), src_loc, p.get_pathfinding_settings(),
                                        p.get_path_avoid() );
                } else {
                    // impassable source tile (locker etc.),
                    // get route to nearest adjacent tile instead
                    route = route_adjacent( p, src_loc );
                    adjacent = true;
                }
                // check if we found path to source / adjacent tile
                if( route.empty() ) {
                    add_msg( m_info, _( "%s can't reach the source tile.  Try to sort out loot without a cart." ),
                             p.disp_name() );
                    continue;
                }
                // shorten the route to adjacent tile, if necessary
                if( !adjacent ) {
                    route.pop_back();
                }
                // set the destination and restart activity after player arrives there
                // we don't need to check for safe mode,
                // activity will be restarted only if
                // player arrives on destination tile
                stage = DO;
                p.set_destination( route, act );
                p.activity.set_to_null();
                return;
            }
            stage = DO;
            break;
        }
    }
    if( stage == DO ) {
        const tripoint &src = act.placement;
        const tripoint &src_loc = here.getlocal( src );
        bool is_adjacent_or_closer = square_dist( p.pos(), src_loc ) <= 1;
        // before we move any item, check if player is at or
        // adjacent to the loot source tile
        if( !is_adjacent_or_closer ) {
            stage = THINK;
            return;
        }
        // the boolean in this pair being true indicates the item is from a vehicle storage space
        auto items = std::vector<std::pair<item *, bool>>();
        vehicle *src_veh, *dest_veh;
        int src_part, dest_part;
        //Check source for cargo part
        //map_stack and vehicle_stack are different types but inherit from item_stack
        // TODO: use one for loop
        if( const cata::optional<vpart_reference> vp = here.veh_at( src_loc ).part_with_feature( "CARGO",
                false ) ) {
            src_veh = &vp->vehicle();
            src_part = vp->part_index();
            for( auto &it : src_veh->get_items( src_part ) ) {
                if( !it.is_owned_by( p, true ) ) {
                    continue;
                }
                it.set_owner( p );
                items.push_back( std::make_pair( &it, true ) );
            }
        } else {
            src_veh = nullptr;
            src_part = -1;
        }
        for( auto &it : here.i_at( src_loc ) ) {
            if( !it.is_owned_by( p, true ) ) {
                continue;
            }
            it.set_owner( p );
            items.push_back( std::make_pair( &it, false ) );
        }
        //Skip items that have already been processed
        for( auto it = items.begin() + num_processed; it < items.end(); ++it ) {
            ++num_processed;
            item &thisitem = *it->first;
            // skip unpickable liquid
            if( thisitem.made_of( LIQUID ) ) {
                continue;
            }
            // skip favorite items in ignore favorite zones
            if( thisitem.is_favorite && mgr.has( zone_type_LOOT_IGNORE_FAVORITES, src ) ) {
                continue;
            }
            // Only if it's from a vehicle do we use the vehicle source location information.
            vehicle *this_veh = it->second ? src_veh : nullptr;
            const int this_part = it->second ? src_part : -1;
            const zone_type_id id = mgr.get_near_zone_type_for_item( thisitem, abspos,
                                    ACTIVITY_SEARCH_DISTANCE );
            // checks whether the item is already on correct loot zone or not
            // if it is, we can skip such item, if not we move the item to correct pile
            // think empty bag on food pile, after you ate the content
            if( mgr.has( id, src ) ) {
                continue;
            }
            const std::unordered_set<tripoint> &dest_set = mgr.get_near( id, abspos, ACTIVITY_SEARCH_DISTANCE,
                    &thisitem );
            for( const tripoint &dest : dest_set ) {
                const tripoint &dest_loc = here.getlocal( dest );
                //Check destination for cargo part
                if( const cata::optional<vpart_reference> vp = here.veh_at( dest_loc ).part_with_feature( "CARGO",
                        false ) ) {
                    dest_veh = &vp->vehicle();
                    dest_part = vp->part_index();
                } else {
                    dest_veh = nullptr;
                    dest_part = -1;
                }
                // skip tiles with inaccessible furniture, like filled charcoal kiln
                if( !here.can_put_items_ter_furn( dest_loc ) ||
                    static_cast<int>( here.i_at( dest_loc ).size() ) >= MAX_ITEM_IN_SQUARE ) {
                    continue;
                }
                units::volume free_space;
                // if there's a vehicle with space do not check the tile beneath
                if( dest_veh ) {
                    free_space = dest_veh->free_volume( dest_part );
                } else {
                    free_space = here.free_volume( dest_loc );
                }
                // check free space at destination
                if( free_space >= thisitem.volume() ) {
                    move_item( p, thisitem, thisitem.count(), src_loc, dest_loc, this_veh, this_part );
                    // moved item away from source so decrement
                    if( num_processed > 0 ) {
                        --num_processed;
                    }
                    break;
                }
            }
            if( p.moves <= 0 ) {
                return;
            }
        }
        //this location is sorted
        stage = THINK;
        return;
    }
    // If we got here without restarting the activity, it means we're done
    add_msg( m_info, _( "%s sorted out every item possible." ), p.disp_name( false, true ) );
    if( p.is_npc() ) {
        npc *guy = dynamic_cast<npc *>( &p );
        guy->revert_after_activity();
    }
    p.activity.set_to_null();
}
References _, act, ACT_MOVE_LOOT, Character::activity, ACTIVITY_SEARCH_DISTANCE, add_msg(), Character::assign_activity(), map::can_put_items_ter_furn(), Character::cancel_activity(), map::check_vehicle_zones(), item::count(), Character::disp_name(), item_stack::empty(), fd_fire, map::free_volume(), g, map::get_field(), zone_manager::get_manager(), get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), map::i_at(), map::inbounds(), item::is_favorite, player::is_npc(), item::is_owned_by(), LIQUID, m_info, item::made_of(), MAX_ITEM_IN_SQUARE, move_item(), Creature::moves, optional_vpart_position::part_with_feature(), map::passable(), Character::pos(), npc::revert_after_activity(), map::route(), route_adjacent(), Character::set_destination(), Creature::set_moves(), item::set_owner(), player_activity::set_to_null(), item_stack::size(), square_dist(), map::veh_at(), vehicle::vehicle(), item::volume(), zone_type_LOOT_IGNORE, zone_type_LOOT_IGNORE_FAVORITES, and zone_type_LOOT_UNSORTED.
Referenced by activity_handlers::move_loot_do_turn().
activity_on_turn_wear()
void activity_on_turn_wear (player_activity & act, player & p)
Definition at line 698 of file activity_item_handling.cpp.
{
    // ACT_WEAR has item_location targets, and int quantities
    while( p.moves > 0 && !act.targets.empty() ) {
        item_location target = std::move( act.targets.back() );
        int quantity = act.values.back();
        act.targets.pop_back();
        act.values.pop_back();
        if( !target ) {
            debugmsg( "Lost target item of ACT_WEAR" );
            continue;
        }
        // Make copies so the original remains untouched if wearing fails
        item newit = *target;
        item leftovers = newit;
        // Handle charges, quantity == 0 means move all
        if( quantity != 0 && newit.count_by_charges() ) {
            leftovers.charges = newit.charges - quantity;
            if( leftovers.charges > 0 ) {
                newit.charges = quantity;
            }
        } else {
            leftovers.charges = 0;
        }
        if( p.wear_item( newit ) ) {
            // If we wore up a whole stack, remove the original item
            // Otherwise, replace the item with the leftovers
            if( leftovers.charges > 0 ) {
                *target = std::move( leftovers );
            } else {
                target.remove_item();
            }
        }
    }
    // If there are no items left we are done
    if( act.targets.empty() ) {
        p.cancel_activity();
    }
}
References act, Character::cancel_activity(), item::charges, item::count_by_charges(), debugmsg, avatar_action::move(), Creature::moves, item_location::remove_item(), and Character::wear_item().
Referenced by activity_handlers::wear_do_turn().
butcher_time_to_cut()
int butcher_time_to_cut (const inventory & inv, const item & corpse_item, butcher_type action)
Definition at line 764 of file activity_handlers.cpp.
{
    const mtype &corpse = *corpse_item.get_mtype();
    const int initial_factor = inv.max_quality( action == DISSECT ? qual_CUT_FINE : qual_BUTCHER );
    // Multiplier for dissection, since it uses different "quality units"
    const int factor = action == DISSECT ? ( initial_factor * 15 ) : initial_factor;
    int time_to_cut = size_factor_in_time_to_cut( corpse.size );
    // At factor 0, base 100 time_to_cut remains 100. At factor 50, it's 50 , at factor 75 it's 25
    time_to_cut *= std::max( 25, 100 - factor );
    if( time_to_cut < 3000 ) {
        time_to_cut = 3000;
    }
    switch( action ) {
        case BUTCHER:
            break;
        case BUTCHER_FULL:
            if( !corpse_item.has_flag( flag_FIELD_DRESS ) || corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) {
                time_to_cut *= 6;
            } else {
                time_to_cut *= 4;
            }
            break;
        case F_DRESS:
        case SKIN:
            time_to_cut *= 2;
            break;
        case QUARTER:
            time_to_cut = std::max( 1000, time_to_cut / 4 );
            break;
        case DISMEMBER:
            time_to_cut = std::max( 400, time_to_cut / 10 );
            break;
        case DISSECT:
            time_to_cut *= 7;
            break;
    }
    if( corpse_item.has_flag( flag_QUARTERED ) ) {
        time_to_cut /= 4;
    }
    time_to_cut = time_to_cut * ( 10 - g->u.get_crafting_helpers( 3 ).size() ) / 10;
    return time_to_cut;
}
References action, BUTCHER, BUTCHER_FULL, corpse, DISMEMBER, DISSECT, F_DRESS, flag_FIELD_DRESS(), flag_FIELD_DRESS_FAILED(), flag_QUARTERED(), g, item::get_mtype(), item::has_flag(), visitable< T >::max_quality(), qual_BUTCHER, qual_CUT_FINE, QUARTER, size_factor_in_time_to_cut(), and SKIN.
Referenced by butcher_submenu(), and consider_butchery().
consider_butchery()
butchery_setup consider_butchery (const item & corpse_item, player & u, butcher_type action)
Definition at line 532 of file activity_handlers.cpp.
{
    map &here = get_map();
    butchery_setup setup;
    setup.can_do = butchery_possibility::yes;
    setup.type = action;
    const auto wont_do = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.problems.emplace_back( msg );
        setup.can_do = butchery_possibility::never;
    };
    const auto not_this_one = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.problems.emplace_back( msg );
        if( setup.can_do != butchery_possibility::never ) {
            setup.can_do = butchery_possibility::not_this;
        }
    };
    const auto info = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.info.emplace_back( msg );
    };
    const auto need_confirm = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.problems.emplace_back( msg );
        if( setup.can_do == butchery_possibility::yes ) {
            setup.can_do = butchery_possibility::need_confirmation;
        }
    };
    const inventory &inv = u.crafting_inventory();
    const int factor = inv.max_quality( action == DISSECT ? qual_CUT_FINE : qual_BUTCHER );
    const mtype &corpse = *corpse_item.get_mtype();
    if( action != DISSECT && factor == INT_MIN ) {
        wont_do( _( "None of your cutting tools are suitable for butchering." ),
                 butcherable_rating::no_tool );
    }
    if( action == DISSECT ) {
        switch( factor ) {
            case INT_MIN:
                wont_do( _( "None of your tools are sharp and precise enough to do that." ),
                         butcherable_rating::no_tool );
                break;
            case 1:
                info( _( "You could use a better tool, but this will do." ), butcherable_rating::info_tools );
                break;
            case 2:
                info( _( "This tool is great, but you still would like a scalpel." ),
                      butcherable_rating::info_tools );
                break;
            case 3:
                info( _( "You dissect the corpse with a trusty scalpel." ), butcherable_rating::info_tools );
                break;
            case 5:
                info( _( "You dissect the corpse with a sophisticated system of surgical grade scalpels." ),
                      butcherable_rating::info_tools );
                break;
        }
    }
    bool has_tree_nearby = false;
    for( const tripoint &pt : here.points_in_radius( u.pos(), PICKUP_RANGE ) ) {
        if( here.has_flag( flag_TREE, pt ) ) {
            has_tree_nearby = true;
            break;
        }
    }
    bool b_rack_present = false;
    for( const tripoint &pt : here.points_in_radius( u.pos(), PICKUP_RANGE ) ) {
        if( here.has_flag_furn( flag_BUTCHER_EQ, pt ) ) {
            b_rack_present = true;
            break;
        }
    }
    if( !b_rack_present ) {
        b_rack_present = inv.has_item_with( []( const item & it ) {
            return it.has_flag( "BUTCHER_RACK" );
        } );
    }
    // workshop butchery (full) prequisites
    if( action == BUTCHER_FULL ) {
        const bool has_rope = inv.has_amount( itype_rope_30, 1 ) ||
                              inv.has_amount( itype_rope_makeshift_30, 1 ) ||
                              inv.has_amount( itype_hd_tow_cable, 1 ) ||
                              inv.has_amount( itype_vine_30, 1 ) ||
                              inv.has_amount( itype_grapnel, 1 );
        const bool big_corpse = corpse.size >= MS_MEDIUM;
        if( big_corpse ) {
            if( has_rope && !has_tree_nearby && !b_rack_present ) {
                not_this_one(
                    _( "You need to suspend this corpse to butcher it.  While you have a rope to lift the corpse, there is no tree nearby to hang it from." ),
                    butcherable_rating::no_tree_rope_rack );
            }
            if( !has_rope && !b_rack_present ) {
                not_this_one(
                    _( "To perform a full butchery on a corpse this big, you need either a butchering rack, a nearby hanging meathook, or both a long rope in your inventory and a nearby tree to hang the corpse from." ),
                    butcherable_rating::no_tree_rope_rack );
            }
            if( !( here.has_nearby_table( u.pos(), PICKUP_RANGE ) || inv.has_item_with( []( const item & it ) {
            return it.has_flag( "FLAT_SURFACE" );
            } ) ) ) {
                not_this_one(
                    _( "To perform a full butchery on a corpse this big, you need a table nearby or something else with a flat surface.  A leather tarp spread out on the ground could suffice." ),
                    butcherable_rating::no_table );
            }
        }
    }
    if( action == DISSECT && ( corpse_item.has_flag( flag_QUARTERED ) ||
                               corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
        not_this_one( _( "It would be futile to search for implants inside this badly damaged corpse." ),
                      butcherable_rating::too_damaged );
    }
    if( action == F_DRESS && ( corpse_item.has_flag( flag_FIELD_DRESS ) ||
                               corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
        not_this_one( _( "This corpse is already field dressed." ),
                      butcherable_rating::already_dressed );
    }
    if( action == SKIN && corpse_item.has_flag( flag_SKINNED ) ) {
        not_this_one( _( "This corpse is already skinned." ), butcherable_rating::already_skinned );
    }
    if( action == QUARTER ) {
        if( corpse.size == MS_TINY ) {
            not_this_one( _( "This corpse is too small to quarter without damaging." ),
                          butcherable_rating::too_small );
        }
        if( corpse_item.has_flag( flag_QUARTERED ) ) {
            not_this_one( _( "This is already quartered." ), butcherable_rating::already_quartered );
        }
        if( !( corpse_item.has_flag( flag_FIELD_DRESS ) ||
               corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) &&
            corpse_item.get_mtype()->harvest->has_entry_type( "offal" ) ) {
            not_this_one( _( "You need to perform field dressing before quartering." ),
                          butcherable_rating::needs_dressing );
        }
    }
    // applies to all butchery actions
    const bool is_human = corpse.id == mtype_id::NULL_ID() || ( corpse.in_species( HUMAN ) &&
                          !corpse.in_species( ZOMBIE ) );
    if( is_human && !( u.has_trait_flag( trait_flag_CANNIBAL ) ||
                       u.has_trait_flag( trait_flag_PSYCHOPATH ) ||
                       u.has_trait_flag( trait_flag_SAPIOVORE ) ) ) {
        need_confirm( _( "Would you dare desecrate the mortal remains of a fellow human being?" ),
                      butcherable_rating::warn_cannibalism );
    }
    setup.move_cost = butcher_time_to_cut( inv, corpse_item, action );
    return setup;
}
References _, action, already_dressed, already_quartered, already_skinned, BUTCHER_FULL, butcher_time_to_cut(), butchery_setup::can_do, corpse, Character::crafting_inventory(), DISSECT, F_DRESS, flag_BUTCHER_EQ(), flag_FIELD_DRESS(), flag_FIELD_DRESS_FAILED(), flag_QUARTERED(), flag_SKINNED(), flag_TREE(), get_map(), item::get_mtype(), mtype::harvest, visitable< T >::has_amount(), harvest_list::has_entry_type(), item::has_flag(), map::has_flag(), map::has_flag_furn(), visitable< T >::has_item_with(), map::has_nearby_table(), Character::has_trait_flag(), HUMAN, butchery_setup::info, info_tools, itype_grapnel, itype_hd_tow_cable, itype_rope_30, itype_rope_makeshift_30, itype_vine_30, visitable< T >::max_quality(), butchery_setup::move_cost, MS_MEDIUM, MS_TINY, need_confirmation, needs_dressing, never, no_table, no_tool, no_tree_rope_rack, not_this, string_id< mtype >::NULL_ID(), PICKUP_RANGE, map::points_in_radius(), Character::pos(), butchery_setup::problems, qual_BUTCHER, qual_CUT_FINE, QUARTER, SKIN, too_damaged, too_small, trait_flag_CANNIBAL(), trait_flag_PSYCHOPATH(), trait_flag_SAPIOVORE(), butchery_setup::type, warn_cannibalism, yes, and ZOMBIE.
Referenced by activity_handlers::butcher_finish(), and butcher_submenu().
drop_on_map()
void drop_on_map (Character & c, item_drop_reason reason, const std::list< item > & items, const tripoint & where)
Definition at line 306 of file activity_item_handling.cpp.
{
    if( items.empty() ) {
        return;
    }
    map &here = get_map();
    const std::string ter_name = here.name( where );
    const bool can_move_there = here.passable( where );
    if( same_type( items ) ) {
        const item &it = items.front();
        const int dropcount = items.size() * it.count();
        const std::string it_name = it.tname( dropcount );
        switch( reason ) {
            case item_drop_reason::deliberate:
                if( can_move_there ) {
                    c.add_msg_player_or_npc(
                        vgettext( "You drop your %1$s on the %2$s.",
                                  "You drop your %1$s on the %2$s.", dropcount ),
                        vgettext( "<npcname> drops their %1$s on the %2$s.",
                                  "<npcname> drops their %1$s on the %2$s.", dropcount ),
                        it_name, ter_name
                    );
                } else {
                    c.add_msg_player_or_npc(
                        vgettext( "You put your %1$s in the %2$s.",
                                  "You put your %1$s in the %2$s.", dropcount ),
                        vgettext( "<npcname> puts their %1$s in the %2$s.",
                                  "<npcname> puts their %1$s in the %2$s.", dropcount ),
                        it_name, ter_name
                    );
                }
                break;
            case item_drop_reason::too_large:
                c.add_msg_if_player(
                    vgettext( "There's no room in your inventory for the %s, so you drop it.",
                              "There's no room in your inventory for the %s, so you drop them.", dropcount ),
                    it_name
                );
                break;
            case item_drop_reason::too_heavy:
                c.add_msg_if_player(
                    vgettext( "The %s is too heavy to carry, so you drop it.",
                              "The %s is too heavy to carry, so you drop them.", dropcount ),
                    it_name
                );
                break;
            case item_drop_reason::tumbling:
                c.add_msg_if_player(
                    m_bad,
                    vgettext( "Your %1$s tumbles to the %2$s.",
                              "Your %1$s tumble to the %2$s.", dropcount ),
                    it_name, ter_name
                );
                break;
        }
    } else {
        switch( reason ) {
            case item_drop_reason::deliberate:
                if( can_move_there ) {
                    c.add_msg_player_or_npc(
                        _( "You drop several items on the %s." ),
                        _( "<npcname> drops several items on the %s." ),
                        ter_name
                    );
                } else {
                    c.add_msg_player_or_npc(
                        _( "You put several items in the %s." ),
                        _( "<npcname> puts several items in the %s." ),
                        ter_name
                    );
                }
                break;
            case item_drop_reason::too_large:
            case item_drop_reason::too_heavy:
            case item_drop_reason::tumbling:
                c.add_msg_if_player( m_bad, _( "Some items tumble to the %s." ), ter_name );
                break;
        }
    }
    for( auto &it : items ) {
        here.add_item_or_charges( where, it );
        pass_to_ownership_handling( it, c );
    }
}
References _, map::add_item_or_charges(), c, item::count(), deliberate, get_map(), m_bad, map::name(), pass_to_ownership_handling(), map::passable(), same_type(), item::tname(), too_heavy, too_large, tumbling, and vgettext().
Referenced by butchery_drops_harvest(), move_items_activity_actor::do_turn(), extract_or_wreck_cbms(), and put_into_vehicle_or_drop().
find_auto_consume()
bool find_auto_consume (player & p, bool food)
Definition at line 3136 of file activity_item_handling.cpp.
{
    // return false if there is no point searching again while the activity is still happening.
    if( p.is_npc() ) {
        return false;
    }
    if( p.has_effect( effect_nausea ) ) {
        return true;
    }
    static const std::string flag_MELTS( "MELTS" );
    static const std::string flag_EDIBLE_FROZEN( "EDIBLE_FROZEN" );
    const tripoint pos = p.pos();
    map &here = get_map();
    zone_manager &mgr = zone_manager::get_manager();
    zone_type_id consume_type_zone( "" );
    if( food ) {
        consume_type_zone = zone_type_id( "AUTO_EAT" );
    } else {
        consume_type_zone = zone_type_id( "AUTO_DRINK" );
    }
    if( here.check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    const std::unordered_set<tripoint> &dest_set = mgr.get_near( consume_type_zone, here.getabs( pos ),
            ACTIVITY_SEARCH_DISTANCE );
    if( dest_set.empty() ) {
        return false;
    }
    for( const tripoint loc : dest_set ) {
        if( loc.z != p.pos().z ) {
            continue;
        }
        const optional_vpart_position vp = here.veh_at( g->m.getlocal( loc ) );
        std::vector<item *> items_here;
        if( vp ) {
            vehicle &veh = vp->vehicle();
            int index = veh.part_with_feature( vp->part_index(), "CARGO", false );
            if( index >= 0 ) {
                vehicle_stack vehitems = veh.get_items( index );
                for( item &it : vehitems ) {
                    items_here.push_back( &it );
                }
            }
        } else {
            map_stack mapitems = here.i_at( here.getlocal( loc ) );
            for( item &it : mapitems ) {
                items_here.push_back( &it );
            }
        }
        for( item *it : items_here ) {
            item &comest = p.get_consumable_from( *it );
            if( comest.is_null() || comest.is_craft() || !comest.is_food() ||
                p.fun_for( comest ).first < -5 ) {
                // not good eatings.
                continue;
            }
            if( !p.can_consume( *it ) ) {
                continue;
            }
            if( food && p.compute_effective_nutrients( comest ).kcal < 50 ) {
                // not filling enough
                continue;
            }
            if( !p.will_eat( comest, false ).success() ) {
                // wont like it, cannibal meat etc
                continue;
            }
            if( !it->is_owned_by( p, true ) ) {
                // it aint ours.
                continue;
            }
            if( !food && comest.get_comestible()->quench < 15 ) {
                // not quenching enough
                continue;
            }
            if( comest.has_flag( flag_UNSAFE_CONSUME ) ) {
                // Unsafe to drink or eat
                continue;
            }
            if( !food && it->is_watertight_container() && it->contents_made_of( SOLID ) ) {
                // its frozen
                continue;
            }
            p.mod_moves( -pickup::cost_to_move_item( p, *it ) * std::max( rl_dist( p.pos(),
                         here.getlocal( loc ) ), 1 ) );
            item_location item_loc;
            if( vp ) {
                item_loc = item_location( vehicle_cursor( vp->vehicle(), vp->part_index() ), &comest );
            } else {
                item_loc = item_location( map_cursor( here.getlocal( loc ) ), &comest );
            }
            avatar_action::eat( g->u, item_loc );
            // eat() may have removed the item, so check its still there.
            if( item_loc.get_item() && item_loc->is_container() ) {
                item_loc->on_contents_changed();
            }
            return true;
        }
    }
    return false;
}
References ACTIVITY_SEARCH_DISTANCE, zone_manager::cache_vzones(), Character::can_consume(), map::check_vehicle_zones(), Character::compute_effective_nutrients(), item::contents_made_of(), pickup::cost_to_move_item(), avatar_action::eat(), effect_nausea, flag_UNSAFE_CONSUME(), Character::fun_for(), g, item::get_comestible(), Character::get_consumable_from(), item_location::get_item(), vehicle::get_items(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), map::getabs(), map::getlocal(), Creature::has_effect(), item::has_flag(), map::i_at(), item::is_container(), item::is_craft(), item::is_food(), player::is_npc(), item::is_null(), item::is_owned_by(), item::is_watertight_container(), nutrients::kcal, Creature::mod_moves(), item::on_contents_changed(), vehicle::part_with_feature(), Character::pos(), rl_dist(), SOLID, map::veh_at(), Character::will_eat(), and tripoint::z.
Referenced by player_activity::do_turn().
generic_multi_activity_handler()
bool generic_multi_activity_handler (player_activity & act, player & p, bool check_only = false)
Definition at line 2950 of file activity_item_handling.cpp.
{
    map &here = get_map();
    const tripoint abspos = here.getabs( p.pos() );
    // NOLINTNEXTLINE(performance-unnecessary-copy-initialization)
    activity_id activity_to_restore = act.id();
    // Nuke the current activity, leaving the backlog alone
    if( !check_only ) {
        p.activity = player_activity();
    }
    // now we setup the target spots based on which activity is occurring
    // the set of target work spots - potentially after we have fetched required tools.
    std::unordered_set<tripoint> src_set = generic_multi_activity_locations( p, activity_to_restore );
    // now we have our final set of points
    std::vector<tripoint> src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
    // now loop through the work-spot tiles and judge whether its worth traveling to it yet
    // or if we need to fetch something first.
    for( const tripoint &src : src_sorted ) {
        const tripoint &src_loc = here.getlocal( src );
        if( !here.inbounds( src_loc ) && !check_only ) {
            if( !here.inbounds( p.pos() ) ) {
                // p is implicitly an NPC that has been moved off the map, so reset the activity
                // and unload them
                p.assign_activity( activity_to_restore );
                p.set_moves( 0 );
                g->reload_npcs();
                return false;
            }
            const std::vector<tripoint> route = route_adjacent( p, src_loc );
            if( route.empty() ) {
                // can't get there, can't do anything, skip it
                continue;
            }
            p.set_moves( 0 );
            p.set_destination( route, player_activity( activity_to_restore ) );
            return false;
        }
        activity_reason_info act_info = can_do_activity_there( activity_to_restore, p,
                                        src_loc, ACTIVITY_SEARCH_DISTANCE );
        // see activity_handlers.h enum for requirement_check_result
        const requirement_check_result req_res = generic_multi_activity_check_requirement( p,
                activity_to_restore, act_info, src, src_loc, src_set, check_only );
        if( req_res == SKIP_LOCATION ) {
            continue;
        } else if( req_res == RETURN_EARLY ) {
            return true;
        }
        if( square_dist( p.pos(), src_loc ) > 1 ) {
            std::vector<tripoint> route = route_adjacent( p, src_loc );
            // check if we found path to source / adjacent tile
            if( route.empty() ) {
                check_npc_revert( p );
                continue;
            }
            if( !check_only ) {
                if( p.moves <= 0 ) {
                    // Restart activity and break from cycle.
                    p.assign_activity( activity_to_restore );
                    return true;
                }
                // set the destination and restart activity after player arrives there
                // we don't need to check for safe mode,
                // activity will be restarted only if
                // player arrives on destination tile
                p.set_destination( route, player_activity( activity_to_restore ) );
                return true;
            }
        }
        // we checked if the work spot was in darkness earlier
        // but there is a niche case where the player is in darkness but the work spot is not
        // this can create infinite loops
        // and we can't check player.pos() for darkness before they've traveled to where they are going to be.
        // but now we are here, we check
        if( activity_to_restore != ACT_TIDY_UP &&
            activity_to_restore != ACT_MOVE_LOOT &&
            activity_to_restore != ACT_FETCH_REQUIRED &&
            !character_funcs::can_see_fine_details( p ) ) {
            p.add_msg_if_player( m_info, _( "It is too dark to work here." ) );
            return false;
        }
        if( !check_only ) {
            if( !generic_multi_activity_do( p, activity_to_restore, act_info, src, src_loc ) ) {
                // if the activity was succesful
                // then a new activity was assigned
                // and the backlog was given the multi-act
                return false;
            }
        } else {
            return true;
        }
    }
    if( !check_only ) {
        if( p.moves <= 0 ) {
            // Restart activity and break from cycle.
            p.assign_activity( activity_to_restore );
            p.activity_vehicle_part_index = -1;
            return false;
        }
        // if we got here, we need to revert otherwise NPC will be stuck in AI Limbo and have a head explosion.
        if( p.backlog.empty() || src_set.empty() ) {
            check_npc_revert( p );
            // tidy up leftover moved parts and tools left lying near the work spots.
            if( player_activity( activity_to_restore ).is_multi_type() ) {
                p.assign_activity( ACT_TIDY_UP );
            }
        }
        p.activity_vehicle_part_index = -1;
    }
    // scanned every location, tried every path.
    return false;
}
References _, act, ACT_FETCH_REQUIRED, ACT_MOVE_LOOT, ACT_TIDY_UP, Character::activity, ACTIVITY_SEARCH_DISTANCE, Character::activity_vehicle_part_index, player::add_msg_if_player(), Character::assign_activity(), Character::backlog, can_do_activity_there(), character_funcs::can_see_fine_details(), check_npc_revert(), g, generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_locations(), get_map(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), string_id< T >::id(), map::inbounds(), m_info, Creature::moves, Character::pos(), RETURN_EARLY, route_adjacent(), Character::set_destination(), Creature::set_moves(), SKIP_LOCATION, and square_dist().
Referenced by activity_handlers::chop_trees_do_turn(), npc::do_player_activity(), activity_handlers::fetch_do_turn(), npc::find_job_to_perform(), activity_handlers::multiple_butcher_do_turn(), activity_handlers::multiple_chop_planks_do_turn(), activity_handlers::multiple_construction_do_turn(), activity_handlers::multiple_farm_do_turn(), activity_handlers::multiple_fish_do_turn(), activity_handlers::multiple_mine_do_turn(), activity_handlers::tidy_up_do_turn(), activity_handlers::vehicle_deconstruction_do_turn(), and activity_handlers::vehicle_repair_do_turn().
get_sorted_tiles_by_distance()
std::vector< tripoint > get_sorted_tiles_by_distance (const tripoint & abspos, const std::unordered_set< tripoint > & tiles)
Definition at line 4371 of file activity_handlers.cpp.
{
    const auto cmp = [abspos]( tripoint a, tripoint b ) {
        const int da = rl_dist( abspos, a );
        const int db = rl_dist( abspos, b );
        return da < db;
    };
    std::vector<tripoint> sorted( tiles.begin(), tiles.end() );
    std::sort( sorted.begin(), sorted.end(), cmp );
    return sorted;
}
References a, b, and rl_dist().
Referenced by activity_on_turn_move_loot(), talk_function::basecamp_mission(), find_refuel_spot_zone(), generic_multi_activity_handler(), perform_zone_activity_turn(), basecamp::place_results(), route_adjacent(), tidy_activity(), and basecamp::validate_sort_points().
put_into_vehicle_or_drop() [1/2]
void put_into_vehicle_or_drop (Character & c, item_drop_reason reason, const std::list< item > & items)
Definition at line 394 of file activity_item_handling.cpp.
{
    return put_into_vehicle_or_drop( c, reason, items, c.pos() );
}
References c, and put_into_vehicle_or_drop().
Referenced by player::add_or_drop_with_msg(), Character::apply_damage(), crafting::complete_disassemble(), veh_interact::complete_vehicle(), player::consume(), damage_item(), Character::dispose_item(), drop_activity_actor::do_turn(), move_items_activity_actor::do_turn(), Character::drop_invalid_inventory(), wash_activity_actor::finish(), move_item(), put_into_vehicle_or_drop(), vehicle::reload_seeds(), and tidy_activity().
put_into_vehicle_or_drop() [2/2]
void put_into_vehicle_or_drop (Character & c, item_drop_reason reason, const std::list< item > & items, const tripoint & where, bool force_ground = false)
Definition at line 399 of file activity_item_handling.cpp.
{
    map &here = get_map();
    const cata::optional<vpart_reference> vp = here.veh_at( where ).part_with_feature( "CARGO", false );
    if( vp && !force_ground ) {
        put_into_vehicle( c, reason, items, vp->vehicle(), vp->part_index() );
        return;
    }
    drop_on_map( c, reason, items, where );
}
References c, drop_on_map(), get_map(), optional_vpart_position::part_with_feature(), put_into_vehicle(), and map::veh_at().
route_adjacent()
std::vector< tripoint > route_adjacent (const player & p, const tripoint & dest)
Definition at line 1024 of file activity_item_handling.cpp.
{
    auto passable_tiles = std::unordered_set<tripoint>();
    map &here = get_map();
    for( const tripoint &tp : here.points_in_radius( dest, 1 ) ) {
        if( tp != p.pos() && here.passable( tp ) && !here.obstructed_by_vehicle_rotation( dest, tp ) ) {
            passable_tiles.emplace( tp );
        }
    }
    const auto &sorted = get_sorted_tiles_by_distance( p.pos(), passable_tiles );
    const auto &avoid = p.get_path_avoid();
    for( const tripoint &tp : sorted ) {
        auto route = here.route( p.pos(), tp, p.get_pathfinding_settings(), avoid );
        if( !route.empty() ) {
            return route;
        }
    }
    return std::vector<tripoint>();
}
References get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), map::obstructed_by_vehicle_rotation(), map::passable(), map::points_in_radius(), Character::pos(), and map::route().
Referenced by activity_on_turn_move_loot(), activity_handlers::find_mount_do_turn(), generic_multi_activity_handler(), and generic_multi_activity_locations().
try_fuel_fire()
void try_fuel_fire (player_activity & act, player & p, bool starting_fire = false)
Definition at line 3241 of file activity_item_handling.cpp.
{
    const tripoint pos = p.pos();
    std::vector<tripoint> adjacent = closest_points_first( pos, PICKUP_RANGE );
    adjacent.erase( adjacent.begin() );
    cata::optional<tripoint> best_fire = starting_fire ? act.placement : find_best_fire( adjacent,
                                         pos );
    map &here = get_map();
    if( !best_fire || !here.accessible_items( *best_fire ) ) {
        return;
    }
    cata::optional<tripoint> refuel_spot = find_refuel_spot_zone( pos );
    if( !refuel_spot ) {
        refuel_spot = find_refuel_spot_trap( adjacent, pos );
        if( !refuel_spot ) {
            return;
        }
    }
    // Special case: fire containers allow burning logs, so use them as fuel if fire is contained
    bool contained = here.has_flag_furn( TFLAG_FIRE_CONTAINER, *best_fire );
    fire_data fd( 1, contained );
    time_duration fire_age = here.get_field_age( *best_fire, fd_fire );
    // Maybe TODO: - refueling in the rain could use more fuel
    // First, simulate expected burn per turn, to see if we need more fuel
    map_stack fuel_on_fire = here.i_at( *best_fire );
    for( item &it : fuel_on_fire ) {
        it.simulate_burn( fd );
        // Unconstrained fires grow below -50_minutes age
        if( !contained && fire_age < -40_minutes && fd.fuel_produced > 1.0f && !it.made_of( LIQUID ) ) {
            // Too much - we don't want a firestorm!
            // Move item back to refueling pile
            // Note: move_item() handles messages (they're the generic "you drop x")
            move_item( p, it, 0, *best_fire, *refuel_spot, nullptr, -1 );
            return;
        }
    }
    // Enough to sustain the fire
    // TODO: It's not enough in the rain
    if( !starting_fire && ( fd.fuel_produced >= 1.0f || fire_age < 10_minutes ) ) {
        return;
    }
    // We need to move fuel from stash to fire
    map_stack potential_fuel = here.i_at( *refuel_spot );
    for( item &it : potential_fuel ) {
        if( it.made_of( LIQUID ) ) {
            continue;
        }
        float last_fuel = fd.fuel_produced;
        it.simulate_burn( fd );
        if( fd.fuel_produced > last_fuel ) {
            int quantity = std::max( 1, std::min( it.charges, it.charges_per_volume( 250_ml ) ) );
            // Note: move_item() handles messages (they're the generic "you drop x")
            move_item( p, it, quantity, *refuel_spot, *best_fire, nullptr, -1 );
            return;
        }
    }
}
References map::accessible_items(), act, item::charges, item::charges_per_volume(), closest_points_first(), fd_fire, find_best_fire(), find_refuel_spot_trap(), find_refuel_spot_zone(), fire_data::fuel_produced, map::get_field_age(), get_map(), map::has_flag_furn(), map::i_at(), LIQUID, item::made_of(), move_item(), PICKUP_RANGE, Character::pos(), item::simulate_burn(), and TFLAG_FIRE_CONTAINER.
Referenced by player_activity::do_turn(), and activity_handlers::start_fire_do_turn().