Cataclysm BN: src/activity_handlers.cpp File Reference
activity_handlers.cpp File Reference
#include "activity_handlers.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstddef>
#include <iterator>
#include <memory>
#include <ostream>
#include <queue>
#include <set>
#include <stdexcept>
#include <string>
#include <utility>
#include "action.h"
#include "advanced_inv.h"
#include "armor_layers.h"
#include "avatar.h"
#include "avatar_action.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "construction.h"
#include "construction_partial.h"
#include "coordinate_conversions.h"
#include "craft_command.h"
#include "crafting.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "distribution_grid.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "fault.h"
#include "field_type.h"
#include "fstream_utils.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "harvest.h"
#include "iexamine.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_group.h"
#include "item_location.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "martialarts.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "omdata.h"
#include "optional.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "pldata.h"
#include "point.h"
#include "ranged.h"
#include "recipe.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "text_snippets.h"
#include "timed_event.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_interact.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
namespace activity_handlers
namespace activity_handlers::repair_activity_hack
namespace activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}
Enumerations
enum class butcherable_rating : int {
butcherable = 0 , no_tool , no_tree_rope_rack , no_table ,
no_saw , too_damaged , already_dressed , already_skinned ,
already_quartered , too_small , needs_dressing , warn_cannibalism ,
info_tools
}
enum repeat_type : int {
REPEAT_INIT = 0 , REPEAT_ONCE , REPEAT_FOREVER , REPEAT_FULL ,
REPEAT_EVENT , REPEAT_CANCEL
}
enum class activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::hack_type_t : int { activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::vehicle_weldrig = 0 , activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::furniture = 1 }
Functions
static const std::string trait_flag_CANNIBAL ("CANNIBAL")
static const std::string trait_flag_PSYCHOPATH ("PSYCHOPATH")
static const std::string trait_flag_SAPIOVORE ("SAPIOVORE")
static const std::string flag_AUTODOC ("AUTODOC")
static const std::string flag_AUTODOC_COUCH ("AUTODOC_COUCH")
static const std::string flag_BUTCHER_EQ ("BUTCHER_EQ")
static const std::string flag_FIELD_DRESS ("FIELD_DRESS")
static const std::string flag_FIELD_DRESS_FAILED ("FIELD_DRESS_FAILED")
static const std::string flag_FISH_GOOD ("FISH_GOOD")
static const std::string flag_FISH_POOR ("FISH_POOR")
static const std::string flag_FORAGE_HALLU ("FORAGE_HALLU")
static const std::string flag_FORAGE_POISON ("FORAGE_POISON")
static const std::string flag_GIBBED ("GIBBED")
static const std::string flag_HIDDEN_HALLU ("HIDDEN_HALLU")
static const std::string flag_HIDDEN_ITEM ("HIDDEN_ITEM")
static const std::string flag_HIDDEN_POISON ("HIDDEN_POISON")
static const std::string flag_MESSY ("MESSY")
static const std::string flag_PLANTABLE ("PLANTABLE")
static const std::string flag_PULPED ("PULPED")
static const std::string flag_QUARTERED ("QUARTERED")
static const std::string flag_RELOAD_ONE ("RELOAD_ONE")
static const std::string flag_REQUIRES_TINDER ("REQUIRES_TINDER")
static const std::string flag_SAFECRACK ("SAFECRACK")
static const std::string flag_SKINNED ("SKINNED")
static const std::string flag_SPEEDLOADER ("SPEEDLOADER")
static const std::string flag_SUPPORTS_ROOF ("SUPPORTS_ROOF")
static const std::string flag_TREE ("TREE")
static const std::string flag_USE_UPS ("USE_UPS")
static bool check_butcher_cbm (const int roll)
static void extract_or_wreck_cbms (const std::list< item > &cbms, int roll, player &p)
butchery_setup consider_butchery (const item &corpse_item, player &u, butcher_type action)
static void set_up_butchery_activity (player_activity &act, player &u, const butchery_setup &setup)
static int size_factor_in_time_to_cut (m_size size)
int butcher_time_to_cut (const Character &who, const inventory &inv, const item &corpse_item, const butcher_type action)
static int corpse_damage_effect (int weight, const std::string &entry_type, int damage_level)
static void butchery_drops_harvest (item *corpse_item, const mtype &mt, player &p, const std::function< int()> &roll_butchery, butcher_type action, const std::function< double()> &roll_drops)
static void butchery_quarter (item *corpse_item, const player &p)
static bool magic_train (player_activity *act, player *p)
static repeat_type repeat_menu (const std::string &title, repeat_type last_selection)
cata::optional< hack_type_t > activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_hack_type (const player_activity &activity)
tripoint activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_position (const player_activity &activity)
item activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool (hack_type_t hack_type, const player_activity &activity)
void activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source (hack_type_t hack_type, const tripoint &position, item &tool, const int original_charges)
void activity_handlers::repair_activity_hack::patch_activity_for_vehicle_welder (player_activity &activity, const tripoint &veh_part_position, const vehicle &veh, int interact_part_idx)
void activity_handlers::repair_activity_hack::patch_activity_for_furniture (player_activity &activity, const tripoint &furniture_position, const itype_id &itt)
static void rod_fish (player *p, const std::vector< monster * > &fishables)
std::vector< tripoint > get_sorted_tiles_by_distance (const tripoint &abspos, const std::unordered_set< tripoint > &tiles)
template<typename fn >
static void cleanup_tiles (std::unordered_set< tripoint > &tiles, fn &cleanup)
static void perform_zone_activity_turn (player *p, const zone_type_id &ztype, const std::function< bool(const tripoint &)> &tile_filter, const std::function< void(player &p, const tripoint &)> &tile_action, const std::string &finished_msg)
static void blood_magic (player *p, int cost)
Variables
static const activity_id ACT_ADV_INVENTORY ("ACT_ADV_INVENTORY")
static const activity_id ACT_ARMOR_LAYERS ("ACT_ARMOR_LAYERS")
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_BURROW ("ACT_BURROW")
static const activity_id ACT_BUTCHER ("ACT_BUTCHER")
static const activity_id ACT_BUTCHER_FULL ("ACT_BUTCHER_FULL")
static const activity_id ACT_CHOP_LOGS ("ACT_CHOP_LOGS")
static const activity_id ACT_CHOP_PLANKS ("ACT_CHOP_PLANKS")
static const activity_id ACT_CHOP_TREE ("ACT_CHOP_TREE")
static const activity_id ACT_CHURN ("ACT_CHURN")
static const activity_id ACT_CLEAR_RUBBLE ("ACT_CLEAR_RUBBLE")
static const activity_id ACT_CONSUME_DRINK_MENU ("ACT_CONSUME_DRINK_MENU")
static const activity_id ACT_CONSUME_FOOD_MENU ("ACT_CONSUME_FOOD_MENU")
static const activity_id ACT_CONSUME_MEDS_MENU ("ACT_CONSUME_MEDS_MENU")
static const activity_id ACT_CRACKING ("ACT_CRACKING")
static const activity_id ACT_CRAFT ("ACT_CRAFT")
static const activity_id ACT_DISMEMBER ("ACT_DISMEMBER")
static const activity_id ACT_DISSECT ("ACT_DISSECT")
static const activity_id ACT_EAT_MENU ("ACT_EAT_MENU")
static const activity_id ACT_FERTILIZE_PLOT ("ACT_FERTILIZE_PLOT")
static const activity_id ACT_FETCH_REQUIRED ("ACT_FETCH_REQUIRED")
static const activity_id ACT_FIELD_DRESS ("ACT_FIELD_DRESS")
static const activity_id ACT_FILL_LIQUID ("ACT_FILL_LIQUID")
static const activity_id ACT_MILK ("ACT_MILK")
static const activity_id ACT_FILL_PIT ("ACT_FILL_PIT")
static const activity_id ACT_FIND_MOUNT ("ACT_FIND_MOUNT")
static const activity_id ACT_FIRSTAID ("ACT_FIRSTAID")
static const activity_id ACT_FISH ("ACT_FISH")
static const activity_id ACT_FORAGE ("ACT_FORAGE")
static const activity_id ACT_GAME ("ACT_GAME")
static const activity_id ACT_GENERIC_GAME ("ACT_GENERIC_GAME")
static const activity_id ACT_GUNMOD_ADD ("ACT_GUNMOD_ADD")
static const activity_id ACT_HACKSAW ("ACT_HACKSAW")
static const activity_id ACT_HAIRCUT ("ACT_HAIRCUT")
static const activity_id ACT_HAND_CRANK ("ACT_HAND_CRANK")
static const activity_id ACT_HOTWIRE_CAR ("ACT_HOTWIRE_CAR")
static const activity_id ACT_JACKHAMMER ("ACT_JACKHAMMER")
static const activity_id ACT_LOCKPICK ("ACT_LOCKPICK")
static const activity_id ACT_LONGSALVAGE ("ACT_LONGSALVAGE")
static const activity_id ACT_MAKE_ZLAVE ("ACT_MAKE_ZLAVE")
static const activity_id ACT_MEDITATE ("ACT_MEDITATE")
static const activity_id ACT_MEND_ITEM ("ACT_MEND_ITEM")
static const activity_id ACT_MIND_SPLICER ("ACT_MIND_SPLICER")
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const activity_id ACT_MULTIPLE_BUTCHER ("ACT_MULTIPLE_BUTCHER")
static const activity_id ACT_MULTIPLE_CHOP_PLANKS ("ACT_MULTIPLE_CHOP_PLANKS")
static const activity_id ACT_MULTIPLE_CHOP_TREES ("ACT_MULTIPLE_CHOP_TREES")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const activity_id ACT_MULTIPLE_MINE ("ACT_MULTIPLE_MINE")
static const activity_id ACT_MULTIPLE_FARM ("ACT_MULTIPLE_FARM")
static const activity_id ACT_MULTIPLE_FISH ("ACT_MULTIPLE_FISH")
static const activity_id ACT_OPERATION ("ACT_OPERATION")
static const activity_id ACT_OXYTORCH ("ACT_OXYTORCH")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_PLANT_SEED ("ACT_PLANT_SEED")
static const activity_id ACT_PLAY_WITH_PET ("ACT_PLAY_WITH_PET")
static const activity_id ACT_PRY_NAILS ("ACT_PRY_NAILS")
static const activity_id ACT_PULP ("ACT_PULP")
static const activity_id ACT_QUARTER ("ACT_QUARTER")
static const activity_id ACT_READ ("ACT_READ")
static const activity_id ACT_RELOAD ("ACT_RELOAD")
static const activity_id ACT_REPAIR_ITEM ("ACT_REPAIR_ITEM")
static const activity_id ACT_ROBOT_CONTROL ("ACT_ROBOT_CONTROL")
static const activity_id ACT_SHAVE ("ACT_SHAVE")
static const activity_id ACT_SKIN ("ACT_SKIN")
static const activity_id ACT_SOCIALIZE ("ACT_SOCIALIZE")
static const activity_id ACT_SPELLCASTING ("ACT_SPELLCASTING")
static const activity_id ACT_START_ENGINES ("ACT_START_ENGINES")
static const activity_id ACT_START_FIRE ("ACT_START_FIRE")
static const activity_id ACT_STUDY_SPELL ("ACT_STUDY_SPELL")
static const activity_id ACT_TIDY_UP ("ACT_TIDY_UP")
static const activity_id ACT_TOOLMOD_ADD ("ACT_TOOLMOD_ADD")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_TRAVELLING ("ACT_TRAVELLING")
static const activity_id ACT_TREE_COMMUNION ("ACT_TREE_COMMUNION")
static const activity_id ACT_TRY_SLEEP ("ACT_TRY_SLEEP")
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const activity_id ACT_VEHICLE_DECONSTRUCTION ("ACT_VEHICLE_DECONSTRUCTION")
static const activity_id ACT_VEHICLE_REPAIR ("ACT_VEHICLE_REPAIR")
static const activity_id ACT_VIBE ("ACT_VIBE")
static const activity_id ACT_WAIT ("ACT_WAIT")
static const activity_id ACT_WAIT_NPC ("ACT_WAIT_NPC")
static const activity_id ACT_WAIT_STAMINA ("ACT_WAIT_STAMINA")
static const activity_id ACT_WAIT_WEATHER ("ACT_WAIT_WEATHER")
static const activity_id ACT_WEAR ("ACT_WEAR")
static const efftype_id effect_ai_waiting ("ai_waiting")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_sheared ("sheared")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_under_op ("under_operation")
static const itype_id itype_2x4 ("2x4")
static const itype_id itype_animal ("animal")
static const itype_id itype_battery ("battery")
static const itype_id itype_burnt_out_bionic ("burnt_out_bionic")
static const itype_id itype_grapnel ("grapnel")
static const itype_id itype_hd_tow_cable ("hd_tow_cable")
static const itype_id itype_log ("log")
static const itype_id itype_mind_scan_robofac ("mind_scan_robofac")
static const itype_id itype_muscle ("muscle")
static const itype_id itype_nail ("nail")
static const itype_id itype_pipe ("pipe")
static const itype_id itype_rope_30 ("rope_30")
static const itype_id itype_rope_makeshift_30 ("rope_makeshift_30")
static const itype_id itype_scrap ("scrap")
static const itype_id itype_sheet_metal ("sheet_metal")
static const itype_id itype_spike ("spike")
static const itype_id itype_splinter ("splinter")
static const itype_id itype_stick_long ("stick_long")
static const itype_id itype_steel_chunk ("steel_chunk")
static const itype_id itype_steel_plate ("steel_plate")
static const itype_id itype_vine_30 ("vine_30")
static const itype_id itype_wire ("wire")
static const itype_id itype_welder ("welder")
static const itype_id itype_wool_staple ("wool_staple")
static const zone_type_id zone_type_FARM_PLOT ("FARM_PLOT")
static const skill_id skill_computer ("computer")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_mechanics ("mechanics")
static const skill_id skill_survival ("survival")
static const quality_id qual_BUTCHER ("BUTCHER")
static const quality_id qual_CUT_FINE ("CUT_FINE")
static const quality_id qual_LOCKPICK ("LOCKPICK")
static const species_id HUMAN ("HUMAN")
static const species_id ZOMBIE ("ZOMBIE")
static const bionic_id bio_ears ("bio_ears")
static const bionic_id bio_painkiller ("bio_painkiller")
static const itype_id itype_UPS ("UPS")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_STOCKY_TROGLO ("STOCKY_TROGLO")
Enumeration Type Documentation
butcherable_rating
enum class butcherable_rating : int strong
Enumerator
butcherable
no_tool
no_tree_rope_rack
no_table
no_saw
too_damaged
already_dressed
already_skinned
already_quartered
too_small
needs_dressing
warn_cannibalism
info_tools
Definition at line 517 of file activity_handlers.cpp.
                              : int {
    butcherable = 0,
    no_tool,
    no_tree_rope_rack,
    no_table,
    no_saw,
    too_damaged,
    already_dressed,
    already_skinned,
    already_quartered,
    too_small,
    needs_dressing,
    warn_cannibalism,
    info_tools
};
repeat_type
enum repeat_type : int
Enumerator
REPEAT_INIT
REPEAT_ONCE
REPEAT_FOREVER
REPEAT_FULL
REPEAT_EVENT
REPEAT_CANCEL
Definition at line 2590 of file activity_handlers.cpp.
                 : int {
    // REPEAT_INIT should be zero. In some scenarios (veh welder), activity value default to zero.
    REPEAT_INIT = 0,    // Haven't found repeat value yet.
    REPEAT_ONCE,        // Repeat just once
    REPEAT_FOREVER,     // Repeat for as long as possible
    REPEAT_FULL,        // Repeat until damage==0
    REPEAT_EVENT,       // Repeat until something interesting happens
    REPEAT_CANCEL,      // Stop repeating
};
Function Documentation
blood_magic()
static void blood_magic (player * p, int cost) static
Definition at line 4663 of file activity_handlers.cpp.
{
    std::vector<uilist_entry> uile;
    std::vector<bodypart_id> parts;
    int i = 0;
    for( const bodypart_id &bp : p->get_all_body_parts( true ) ) {
        const int hp_cur = p->get_part_hp_cur( bp );
        uilist_entry entry( i, hp_cur > cost, i + 49, body_part_hp_bar_ui_text( bp ) );
        const std::pair<std::string, nc_color> &hp = get_hp_bar( hp_cur, p->get_part_hp_max( bp ) );
        entry.ctxt = colorize( hp.first, hp.second );
        uile.emplace_back( entry );
        parts.push_back( bp );
        i++;
    }
    int action = -1;
    while( action < 0 ) {
        action = uilist( _( "Choose part\nto draw blood from." ), uile );
    }
    p->mod_part_hp_cur( parts[action], - cost );
    p->mod_pain( std::max( 1, cost / 3 ) );
}
References _, action, body_part_hp_bar_ui_text(), colorize(), uilist_entry::ctxt, Creature::get_all_body_parts(), get_hp_bar(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), hp, Character::mod_pain(), and Creature::mod_part_hp_cur().
Referenced by activity_handlers::spellcasting_finish().
butcher_time_to_cut()
int butcher_time_to_cut (const Character & who, const inventory & inv, const item & corpse_item, const butcher_type action)
Definition at line 765 of file activity_handlers.cpp.
{
    const mtype &corpse = *corpse_item.get_mtype();
    const int initial_factor = inv.max_quality( action == DISSECT ? qual_CUT_FINE : qual_BUTCHER );
    // Multiplier for dissection, since it uses different "quality units"
    const int factor = action == DISSECT ? ( initial_factor * 15 ) : initial_factor;
    int time_to_cut = size_factor_in_time_to_cut( corpse.size );
    // At factor 0, base 100 time_to_cut remains 100. At factor 50, it's 50 , at factor 75 it's 25
    time_to_cut *= std::max( 25, 100 - factor );
    if( time_to_cut < 3000 ) {
        time_to_cut = 3000;
    }
    switch( action ) {
        case BUTCHER:
            break;
        case BUTCHER_FULL:
            if( !corpse_item.has_flag( flag_FIELD_DRESS ) || corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) {
                time_to_cut *= 6;
            } else {
                time_to_cut *= 4;
            }
            break;
        case F_DRESS:
        case SKIN:
            time_to_cut *= 2;
            break;
        case QUARTER:
            time_to_cut = std::max( 1000, time_to_cut / 4 );
            break;
        case DISMEMBER:
            time_to_cut = std::max( 400, time_to_cut / 10 );
            break;
        case DISSECT:
            time_to_cut *= 7;
            break;
    }
    if( corpse_item.has_flag( flag_QUARTERED ) ) {
        time_to_cut /= 4;
    }
    time_to_cut = time_to_cut * ( 10 - character_funcs::get_crafting_helpers( who, 3 ).size() ) / 10;
    return time_to_cut;
}
References action, BUTCHER, BUTCHER_FULL, corpse, DISMEMBER, DISSECT, F_DRESS, flag_FIELD_DRESS(), flag_FIELD_DRESS_FAILED(), flag_QUARTERED(), character_funcs::get_crafting_helpers(), item::get_mtype(), item::has_flag(), visitable< T >::max_quality(), qual_BUTCHER, qual_CUT_FINE, QUARTER, size_factor_in_time_to_cut(), and SKIN.
Referenced by butcher_submenu(), and consider_butchery().
butchery_drops_harvest()
static void butchery_drops_harvest (item * corpse_item, const mtype & mt, player & p, const std::function< int()> & roll_butchery, butcher_type action, const std::function< double()> & roll_drops) static
Definition at line 870 of file activity_handlers.cpp.
{
    p.add_msg_if_player( m_neutral, mt.harvest->message() );
    int monster_weight = to_gram( mt.weight );
    monster_weight += std::round( monster_weight * rng_float( -0.1, 0.1 ) );
    if( corpse_item->has_flag( flag_QUARTERED ) ) {
        monster_weight *= 0.95;
    }
    if( corpse_item->has_flag( flag_GIBBED ) ) {
        monster_weight = std::round( 0.85 * monster_weight );
        if( action != F_DRESS ) {
            p.add_msg_if_player( m_bad,
                                 _( "You salvage what you can from the corpse, but it is badly damaged." ) );
        }
    }
    if( corpse_item->has_flag( flag_SKINNED ) ) {
        monster_weight = std::round( 0.85 * monster_weight );
    }
    int practice = 4 + roll_butchery();
    if( mt.harvest.is_null() ) {
        debugmsg( "ERROR: %s has no harvest entry.", mt.id.c_str() );
        return;
    }
    map &here = get_map();
    for( const harvest_entry &entry : *mt.harvest ) {
        const int butchery = roll_butchery();
        const float min_num = entry.base_num.first + butchery * entry.scale_num.first;
        const float max_num = entry.base_num.second + butchery * entry.scale_num.second;
        int roll = 0;
        // mass_ratio will override the use of base_num, scale_num, and max
        if( entry.mass_ratio != 0.00f ) {
            roll = static_cast<int>( std::round( entry.mass_ratio * monster_weight ) );
            roll = corpse_damage_effect( roll, entry.type, corpse_item->damage_level( 4 ) );
        } else if( entry.type != "bionic" && entry.type != "bionic_group" ) {
            roll = std::min<int>( entry.max, std::round( rng_float( min_num, max_num ) ) );
            // will not give less than min_num defined in the JSON
            roll = std::max<int>( corpse_damage_effect( roll, entry.type, corpse_item->damage_level( 4 ) ),
                                  entry.base_num.first );
        }
        const itype *drop = nullptr;
        if( entry.type != "bionic_group" ) {
            drop = &*itype_id( entry.drop );
        }
        // BIONIC handling - no code for DISSECT to let the bionic drop fall through
        if( entry.type == "bionic" || entry.type == "bionic_group" ) {
            if( action == F_DRESS ) {
                if( drop != nullptr && !drop->bionic ) {
                    if( one_in( 3 ) ) {
                        p.add_msg_if_player( m_bad,
                                             _( "You notice some strange organs, perhaps harvestable via careful dissection." ) );
                    }
                    continue;
                }
                p.add_msg_if_player( m_bad,
                                     _( "You notice there are bionics implanted in this corpse, that careful dissection might preserve." ) );
                continue;
            }
            if( action == BUTCHER || action == BUTCHER_FULL || action == DISMEMBER ) {
                if( drop != nullptr && !drop->bionic ) {
                    if( one_in( 3 ) ) {
                        p.add_msg_if_player( m_bad,
                                             _( "Your butchering tool destroys a strange organ.  Perhaps a more surgical approach would allow harvesting it." ) );
                    }
                    continue;
                }
                switch( rng( 1, 3 ) ) {
                    case 1:
                        p.add_msg_if_player( m_bad,
                                             _( "Your butchering tool encounters something implanted in this corpse, but your rough cuts destroy it." ) );
                        break;
                    case 2:
                        p.add_msg_if_player( m_bad,
                                             _( "You find traces of implants in the body, but you care only for the flesh." ) );
                        break;
                    case 3:
                        p.add_msg_if_player( m_bad,
                                             _( "You found some bionics in the body, but harvesting them would require more surgical approach." ) );
                        break;
                }
                continue;
            }
        }
        // Check if monster was gibbed, and handle accordingly
        if( corpse_item->has_flag( flag_GIBBED ) && ( entry.type == "flesh" || entry.type == "bone" ) ) {
            roll /= 2;
        }
        if( corpse_item->has_flag( flag_SKINNED ) && entry.type == "skin" ) {
            roll = 0;
        }
        // QUICK BUTCHERY
        if( action == BUTCHER ) {
            if( entry.type == "flesh" ) {
                roll = roll / 4;
            } else if( entry.type == "bone" ) {
                roll /= 2;
            } else if( corpse_item->get_mtype()->size >= MS_MEDIUM && ( entry.type == "skin" ) ) {
                roll /= 2;
            } else if( entry.type == "offal" ) {
                roll /= 5;
            } else {
                continue;
            }
        }
        // RIP AND TEAR
        if( action == DISMEMBER ) {
            if( entry.type == "flesh" ) {
                roll /= 6;
            } else {
                continue;
            }
        }
        // field dressing ignores everything outside below list
        if( action == F_DRESS ) {
            if( entry.type == "bone" ) {
                roll = rng( 0, roll / 2 );
            }
            if( entry.type == "flesh" ) {
                continue;
            }
            if( entry.type == "skin" ) {
                continue;
            }
        }
        // you only get the skin from skinning
        if( action == SKIN ) {
            if( entry.type != "skin" ) {
                continue;
            }
            if( corpse_item->has_flag( flag_FIELD_DRESS_FAILED ) ) {
                roll = rng( 0, roll );
            }
        }
        // field dressing removed innards and bones from meatless limbs
        if( ( action == BUTCHER_FULL || action == BUTCHER ) && corpse_item->has_flag( flag_FIELD_DRESS ) ) {
            if( entry.type == "offal" ) {
                continue;
            }
            if( entry.type == "bone" ) {
                roll = ( roll / 2 ) + rng( roll / 2, roll );
            }
        }
        // unskillfull field dressing may damage the skin, meat, and other parts
        if( ( action == BUTCHER_FULL || action == BUTCHER ) &&
            corpse_item->has_flag( flag_FIELD_DRESS_FAILED ) ) {
            if( entry.type == "offal" ) {
                continue;
            }
            if( entry.type == "bone" ) {
                roll = ( roll / 2 ) + rng( roll / 2, roll );
            }
            if( entry.type == "flesh" || entry.type == "skin" ) {
                roll = rng( 0, roll );
            }
        }
        // quartering ruins skin
        if( corpse_item->has_flag( flag_QUARTERED ) ) {
            if( entry.type == "skin" ) {
                //not continue to show fail effect
                roll = 0;
            } else {
                roll /= 4;
            }
        }
        if( entry.type != "bionic" && entry.type != "bionic_group" ) {
            // divide total dropped weight by drop's weight to get amount
            if( entry.mass_ratio != 0.00f ) {
                // apply skill before converting to items, but only if mass_ratio is defined
                roll *= roll_drops();
                roll = std::ceil( static_cast<double>( roll ) /
                                  to_gram( drop->weight ) );
            }
            if( roll <= 0 ) {
                p.add_msg_if_player( m_bad, _( "You fail to harvest: %s" ), drop->nname( 1 ) );
                continue;
            }
            if( drop->phase == LIQUID ) {
                item obj( drop, calendar::turn, roll );
                if( obj.goes_bad() ) {
                    obj.set_rot( corpse_item->get_rot() );
                }
                for( const std::string &flg : entry.flags ) {
                    obj.set_flag( flg );
                }
                for( const fault_id &flt : entry.faults ) {
                    obj.faults.emplace( flt );
                }
                // TODO: smarter NPC liquid handling
                if( p.is_npc() ) {
                    drop_on_map( p, item_drop_reason::deliberate, { obj }, p.pos() );
                } else {
                    liquid_handler::handle_all_liquid( obj, 1 );
                }
            } else if( drop->count_by_charges() ) {
                item obj( drop, calendar::turn, roll );
                if( obj.goes_bad() ) {
                    obj.set_rot( corpse_item->get_rot() );
                }
                for( const std::string &flg : entry.flags ) {
                    obj.set_flag( flg );
                }
                for( const fault_id &flt : entry.faults ) {
                    obj.faults.emplace( flt );
                }
                if( !p.backlog.empty() && p.backlog.front().id() == ACT_MULTIPLE_BUTCHER ) {
                    obj.set_var( "activity_var", p.name );
                }
                here.add_item_or_charges( p.pos(), obj );
            } else {
                item obj( drop, calendar::turn );
                obj.set_mtype( &mt );
                if( obj.goes_bad() ) {
                    obj.set_rot( corpse_item->get_rot() );
                }
                for( const std::string &flg : entry.flags ) {
                    obj.set_flag( flg );
                }
                for( const fault_id &flt : entry.faults ) {
                    obj.faults.emplace( flt );
                }
                if( !p.backlog.empty() && p.backlog.front().id() == ACT_MULTIPLE_BUTCHER ) {
                    obj.set_var( "activity_var", p.name );
                }
                for( int i = 0; i != roll; ++i ) {
                    here.add_item_or_charges( p.pos(), obj );
                }
            }
            p.add_msg_if_player( m_good, _( "You harvest: %s" ), drop->nname( roll ) );
        }
        practice++;
    }
    // 20% of the original corpse weight is not an item, but liquid gore
    if( action != DISSECT ) {
        p.practice( skill_survival, std::max( 0, practice ), std::max( mt.size - MS_MEDIUM, 0 ) + 4 );
    }
}
References _, ACT_MULTIPLE_BUTCHER, action, map::add_item_or_charges(), player::add_msg_if_player(), Character::backlog, harvest_entry::base_num, itype::bionic, BUTCHER, BUTCHER_FULL, string_id< T >::c_str(), corpse_damage_effect(), itype::count_by_charges(), item::damage_level(), debugmsg, deliberate, DISMEMBER, DISSECT, harvest_entry::drop, drop_on_map(), F_DRESS, harvest_entry::faults, flag_FIELD_DRESS(), flag_FIELD_DRESS_FAILED(), flag_GIBBED(), flag_QUARTERED(), flag_SKINNED(), harvest_entry::flags, get_map(), item::get_mtype(), item::get_rot(), liquid_handler::handle_all_liquid(), mtype::harvest, item::has_flag(), mtype::id, player::is_npc(), string_id< T >::is_null(), LIQUID, m_bad, m_good, m_neutral, harvest_entry::mass_ratio, harvest_entry::max, harvest_list::message(), MS_MEDIUM, Character::name, itype::nname(), int_id< T >::obj(), one_in(), itype::phase, Character::pos(), Character::practice(), rng(), rng_float(), harvest_entry::scale_num, mtype::size, skill_survival, SKIN, units::to_gram(), calendar::turn, harvest_entry::type, itype::weight, and mtype::weight.
Referenced by activity_handlers::butcher_finish().
butchery_quarter()
static void butchery_quarter (item * corpse_item, const player & p) static
Definition at line 1119 of file activity_handlers.cpp.
{
    corpse_item->set_flag( flag_QUARTERED );
    p.add_msg_if_player( m_good,
                         _( "You roughly slice the corpse of %s into four parts and set them aside." ),
                         corpse_item->get_mtype()->nname() );
    map &here = get_map();
    // 4 quarters (one exists, add 3, flag does the rest)
    for( int i = 1; i <= 3; i++ ) {
        here.add_item_or_charges( p.pos(), *corpse_item, true );
    }
}
References _, map::add_item_or_charges(), player::add_msg_if_player(), flag_QUARTERED(), get_map(), item::get_mtype(), m_good, mtype::nname(), Character::pos(), and item::set_flag().
Referenced by activity_handlers::butcher_finish().
check_butcher_cbm()
static bool check_butcher_cbm (const int roll) static
Definition at line 465 of file activity_handlers.cpp.
{
    // Failure rates for dissection rolls
    // 90% at roll 0, 72% at roll 1, 60% at roll 2, 51% @ 3, 45% @ 4, 40% @ 5, ... , 25% @ 10
    // Roll is roughly a rng(0, -3 + 1st_aid + fine_cut_quality + 1/2 electronics + small_dex_bonus)
    // Roll is reduced by corpse damage level, but to no less than 0
    add_msg( m_debug, _( "Roll = %i" ), roll );
    add_msg( m_debug, _( "Failure chance = %f%%" ), ( 9.0f / ( 10.0f + roll * 2.5f ) ) * 100.0f );
    const bool failed = x_in_y( 9, ( 10 + roll * 2.5 ) );
    return !failed;
}
References _, add_msg(), failed, m_debug, and x_in_y().
Referenced by extract_or_wreck_cbms().
cleanup_tiles()
template<typename fn > static void cleanup_tiles (std::unordered_set< tripoint > & tiles, fn & cleanup) static
Definition at line 4419 of file activity_handlers.cpp.
{
    auto it = tiles.begin();
    map &here = get_map();
    while( it != tiles.end() ) {
        auto current = it++;
        const tripoint &tile_loc = here.getlocal( *current );
        if( cleanup( tile_loc ) ) {
            tiles.erase( current );
        }
    }
}
References get_map(), and map::getlocal().
Referenced by perform_zone_activity_turn().
consider_butchery()
butchery_setup consider_butchery (const item & corpse_item, player & u, butcher_type action)
Definition at line 533 of file activity_handlers.cpp.
{
    map &here = get_map();
    butchery_setup setup;
    setup.can_do = butchery_possibility::yes;
    setup.type = action;
    const auto wont_do = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.problems.emplace_back( msg );
        setup.can_do = butchery_possibility::never;
    };
    const auto not_this_one = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.problems.emplace_back( msg );
        if( setup.can_do != butchery_possibility::never ) {
            setup.can_do = butchery_possibility::not_this;
        }
    };
    const auto info = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.info.emplace_back( msg );
    };
    const auto need_confirm = [&setup]( const std::string & msg, butcherable_rating ) {
        setup.problems.emplace_back( msg );
        if( setup.can_do == butchery_possibility::yes ) {
            setup.can_do = butchery_possibility::need_confirmation;
        }
    };
    const inventory &inv = u.crafting_inventory();
    const int factor = inv.max_quality( action == DISSECT ? qual_CUT_FINE : qual_BUTCHER );
    const mtype &corpse = *corpse_item.get_mtype();
    if( action != DISSECT && factor == INT_MIN ) {
        wont_do( _( "None of your cutting tools are suitable for butchering." ),
                 butcherable_rating::no_tool );
    }
    if( action == DISSECT ) {
        switch( factor ) {
            case INT_MIN:
                wont_do( _( "None of your tools are sharp and precise enough to do that." ),
                         butcherable_rating::no_tool );
                break;
            case 1:
                info( _( "You could use a better tool, but this will do." ), butcherable_rating::info_tools );
                break;
            case 2:
                info( _( "This tool is great, but you still would like a scalpel." ),
                      butcherable_rating::info_tools );
                break;
            case 3:
                info( _( "You dissect the corpse with a trusty scalpel." ), butcherable_rating::info_tools );
                break;
            case 5:
                info( _( "You dissect the corpse with a sophisticated system of surgical grade scalpels." ),
                      butcherable_rating::info_tools );
                break;
        }
    }
    bool has_tree_nearby = false;
    for( const tripoint &pt : here.points_in_radius( u.pos(), PICKUP_RANGE ) ) {
        if( here.has_flag( flag_TREE, pt ) ) {
            has_tree_nearby = true;
            break;
        }
    }
    bool b_rack_present = false;
    for( const tripoint &pt : here.points_in_radius( u.pos(), PICKUP_RANGE ) ) {
        if( here.has_flag_furn( flag_BUTCHER_EQ, pt ) ) {
            b_rack_present = true;
            break;
        }
    }
    if( !b_rack_present ) {
        b_rack_present = inv.has_item_with( []( const item & it ) {
            return it.has_flag( "BUTCHER_RACK" );
        } );
    }
    // workshop butchery (full) prequisites
    if( action == BUTCHER_FULL ) {
        const bool has_rope = inv.has_amount( itype_rope_30, 1 ) ||
                              inv.has_amount( itype_rope_makeshift_30, 1 ) ||
                              inv.has_amount( itype_hd_tow_cable, 1 ) ||
                              inv.has_amount( itype_vine_30, 1 ) ||
                              inv.has_amount( itype_grapnel, 1 );
        const bool big_corpse = corpse.size >= MS_MEDIUM;
        if( big_corpse ) {
            if( has_rope && !has_tree_nearby && !b_rack_present ) {
                not_this_one(
                    _( "You need to suspend this corpse to butcher it.  While you have a rope to lift the corpse, there is no tree nearby to hang it from." ),
                    butcherable_rating::no_tree_rope_rack );
            }
            if( !has_rope && !b_rack_present ) {
                not_this_one(
                    _( "To perform a full butchery on a corpse this big, you need either a butchering rack, a nearby hanging meathook, or both a long rope in your inventory and a nearby tree to hang the corpse from." ),
                    butcherable_rating::no_tree_rope_rack );
            }
            if( !( here.has_nearby_table( u.pos(), PICKUP_RANGE ) || inv.has_item_with( []( const item & it ) {
            return it.has_flag( "FLAT_SURFACE" );
            } ) ) ) {
                not_this_one(
                    _( "To perform a full butchery on a corpse this big, you need a table nearby or something else with a flat surface.  A leather tarp spread out on the ground could suffice." ),
                    butcherable_rating::no_table );
            }
        }
    }
    if( action == DISSECT && ( corpse_item.has_flag( flag_QUARTERED ) ||
                               corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
        not_this_one( _( "It would be futile to search for implants inside this badly damaged corpse." ),
                      butcherable_rating::too_damaged );
    }
    if( action == F_DRESS && ( corpse_item.has_flag( flag_FIELD_DRESS ) ||
                               corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
        not_this_one( _( "This corpse is already field dressed." ),
                      butcherable_rating::already_dressed );
    }
    if( action == SKIN && corpse_item.has_flag( flag_SKINNED ) ) {
        not_this_one( _( "This corpse is already skinned." ), butcherable_rating::already_skinned );
    }
    if( action == QUARTER ) {
        if( corpse.size == MS_TINY ) {
            not_this_one( _( "This corpse is too small to quarter without damaging." ),
                          butcherable_rating::too_small );
        }
        if( corpse_item.has_flag( flag_QUARTERED ) ) {
            not_this_one( _( "This is already quartered." ), butcherable_rating::already_quartered );
        }
        if( !( corpse_item.has_flag( flag_FIELD_DRESS ) ||
               corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) &&
            corpse_item.get_mtype()->harvest->has_entry_type( "offal" ) ) {
            not_this_one( _( "You need to perform field dressing before quartering." ),
                          butcherable_rating::needs_dressing );
        }
    }
    // applies to all butchery actions
    const bool is_human = corpse.id == mtype_id::NULL_ID() || ( corpse.in_species( HUMAN ) &&
                          !corpse.in_species( ZOMBIE ) );
    if( is_human && !( u.has_trait_flag( trait_flag_CANNIBAL ) ||
                       u.has_trait_flag( trait_flag_PSYCHOPATH ) ||
                       u.has_trait_flag( trait_flag_SAPIOVORE ) ) ) {
        need_confirm( _( "Would you dare desecrate the mortal remains of a fellow human being?" ),
                      butcherable_rating::warn_cannibalism );
    }
    setup.move_cost = butcher_time_to_cut( u, inv, corpse_item, action );
    return setup;
}
References _, action, already_dressed, already_quartered, already_skinned, BUTCHER_FULL, butcher_time_to_cut(), butchery_setup::can_do, corpse, Character::crafting_inventory(), DISSECT, F_DRESS, flag_BUTCHER_EQ(), flag_FIELD_DRESS(), flag_FIELD_DRESS_FAILED(), flag_QUARTERED(), flag_SKINNED(), flag_TREE(), get_map(), item::get_mtype(), mtype::harvest, visitable< T >::has_amount(), harvest_list::has_entry_type(), item::has_flag(), map::has_flag(), map::has_flag_furn(), visitable< T >::has_item_with(), map::has_nearby_table(), Character::has_trait_flag(), HUMAN, butchery_setup::info, info_tools, itype_grapnel, itype_hd_tow_cable, itype_rope_30, itype_rope_makeshift_30, itype_vine_30, visitable< T >::max_quality(), butchery_setup::move_cost, MS_MEDIUM, MS_TINY, need_confirmation, needs_dressing, never, no_table, no_tool, no_tree_rope_rack, not_this, string_id< mtype >::NULL_ID(), PICKUP_RANGE, map::points_in_radius(), Character::pos(), butchery_setup::problems, qual_BUTCHER, qual_CUT_FINE, QUARTER, SKIN, too_damaged, too_small, trait_flag_CANNIBAL(), trait_flag_PSYCHOPATH(), trait_flag_SAPIOVORE(), butchery_setup::type, warn_cannibalism, yes, and ZOMBIE.
Referenced by activity_handlers::butcher_finish(), and butcher_submenu().
corpse_damage_effect()
static int corpse_damage_effect (int weight, const std::string & entry_type, int damage_level) static
Definition at line 813 of file activity_handlers.cpp.
{
    const float slight_damage = 0.9;
    const float damage = 0.75;
    const float high_damage = 0.5;
    const int destroyed = 0;
    switch( damage_level ) {
        case 2:
            // "damaged"
            if( entry_type == "offal" ) {
                return std::round( weight * damage );
            }
            if( entry_type == "skin" ) {
                return std::round( weight * damage );
            }
            if( entry_type == "flesh" ) {
                return std::round( weight * slight_damage );
            }
            break;
        case 3:
            // "mangled"
            if( entry_type == "offal" ) {
                return destroyed;
            }
            if( entry_type == "skin" ) {
                return std::round( weight * high_damage );
            }
            if( entry_type == "bone" ) {
                return std::round( weight * slight_damage );
            }
            if( entry_type == "flesh" ) {
                return std::round( weight * damage );
            }
            break;
        case 4:
            // "pulped"
            if( entry_type == "offal" ) {
                return destroyed;
            }
            if( entry_type == "skin" ) {
                return destroyed;
            }
            if( entry_type == "bone" ) {
                return std::round( weight * damage );
            }
            if( entry_type == "flesh" ) {
                return std::round( weight * high_damage );
            }
            break;
        default:
            // "bruised" modifier is almost impossible to avoid; also includes no modifier (zero damage)
            break;
    }
    return weight;
}
References destroyed.
Referenced by butchery_drops_harvest().
extract_or_wreck_cbms()
static void extract_or_wreck_cbms (const std::list< item > & cbms, int roll, player & p) static
Definition at line 477 of file activity_handlers.cpp.
{
    if( roll < 0 ) {
        return;
    }
    for( item it : cbms ) {
        // For some stupid reason, zombie pheromones are dropped using bionic type
        // This complicates things
        if( it.is_bionic() ) {
            if( check_butcher_cbm( roll ) || it.typeId() == itype_burnt_out_bionic ) {
                add_msg( m_good, _( "You discover a %s!" ), it.tname() );
            } else {
                // We convert instead of recreating so that it keeps flags and faults
                it.convert( itype_burnt_out_bionic );
                add_msg( m_bad, _( "Your imprecise surgery damaged a bionic, producing a %s." ), it.tname() );
            }
        } else {
            if( !check_butcher_cbm( roll ) ) {
                add_msg( m_bad, _( "Your imprecise surgery destroyed some organs." ) );
                continue;
            } else {
                add_msg( m_good, _( "You discover a %s!" ), it.tname() );
            }
        }
        if( it.type->phase == LIQUID ) {
            // TODO: smarter NPC liquid handling
            if( p.is_npc() ) {
                drop_on_map( p, item_drop_reason::deliberate, { it }, p.pos() );
            } else {
                liquid_handler::handle_all_liquid( it, 1 );
            }
        } else {
            get_map().add_item( p.pos(), it );
        }
    }
}
References _, map::add_item(), add_msg(), check_butcher_cbm(), deliberate, drop_on_map(), get_map(), liquid_handler::handle_all_liquid(), player::is_npc(), itype_burnt_out_bionic, LIQUID, m_bad, m_good, and Character::pos().
Referenced by activity_handlers::butcher_finish().
flag_AUTODOC()
static const std::string flag_AUTODOC ("AUTODOC") static
Referenced by activity_handlers::operation_do_turn(), and activity_handlers::operation_finish().
flag_AUTODOC_COUCH()
static const std::string flag_AUTODOC_COUCH ("AUTODOC_COUCH") static
Referenced by activity_handlers::operation_do_turn().
flag_BUTCHER_EQ()
static const std::string flag_BUTCHER_EQ ("BUTCHER_EQ") static
Referenced by consider_butchery().
flag_FIELD_DRESS()
static const std::string flag_FIELD_DRESS ("FIELD_DRESS") static
Referenced by activity_handlers::butcher_finish(), butcher_time_to_cut(), butchery_drops_harvest(), and consider_butchery().
flag_FIELD_DRESS_FAILED()
static const std::string flag_FIELD_DRESS_FAILED ("FIELD_DRESS_FAILED") static
Referenced by butcher_time_to_cut(), butchery_drops_harvest(), and consider_butchery().
flag_FISH_GOOD()
static const std::string flag_FISH_GOOD ("FISH_GOOD") static
Referenced by activity_handlers::fish_do_turn().
flag_FISH_POOR()
static const std::string flag_FISH_POOR ("FISH_POOR") static
Referenced by activity_handlers::fish_do_turn().
flag_FORAGE_HALLU()
static const std::string flag_FORAGE_HALLU ("FORAGE_HALLU") static
Referenced by activity_handlers::forage_finish().
flag_FORAGE_POISON()
static const std::string flag_FORAGE_POISON ("FORAGE_POISON") static
Referenced by activity_handlers::forage_finish().
flag_GIBBED()
static const std::string flag_GIBBED ("GIBBED") static
Referenced by butchery_drops_harvest().
flag_HIDDEN_HALLU()
static const std::string flag_HIDDEN_HALLU ("HIDDEN_HALLU") static
Referenced by activity_handlers::forage_finish().
flag_HIDDEN_ITEM()
static const std::string flag_HIDDEN_ITEM ("HIDDEN_ITEM") static
Referenced by activity_handlers::plant_seed_finish().
flag_HIDDEN_POISON()
static const std::string flag_HIDDEN_POISON ("HIDDEN_POISON") static
Referenced by activity_handlers::forage_finish().
flag_MESSY()
static const std::string flag_MESSY ("MESSY") static
Referenced by activity_handlers::pulp_do_turn().
flag_PLANTABLE()
static const std::string flag_PLANTABLE ("PLANTABLE") static
Referenced by activity_handlers::plant_seed_finish().
flag_PULPED()
static const std::string flag_PULPED ("PULPED") static
Referenced by activity_handlers::pulp_do_turn().
flag_QUARTERED()
static const std::string flag_QUARTERED ("QUARTERED") static
Referenced by butcher_time_to_cut(), butchery_drops_harvest(), butchery_quarter(), and consider_butchery().
flag_RELOAD_ONE()
static const std::string flag_RELOAD_ONE ("RELOAD_ONE") static
Referenced by activity_handlers::reload_finish().
flag_REQUIRES_TINDER()
static const std::string flag_REQUIRES_TINDER ("REQUIRES_TINDER") static
Referenced by activity_handlers::start_fire_do_turn().
flag_SAFECRACK()
static const std::string flag_SAFECRACK ("SAFECRACK") static
Referenced by activity_handlers::cracking_do_turn().
flag_SKINNED()
static const std::string flag_SKINNED ("SKINNED") static
Referenced by activity_handlers::butcher_finish(), butchery_drops_harvest(), and consider_butchery().
flag_SPEEDLOADER()
static const std::string flag_SPEEDLOADER ("SPEEDLOADER") static
Referenced by activity_handlers::reload_finish().
flag_SUPPORTS_ROOF()
static const std::string flag_SUPPORTS_ROOF ("SUPPORTS_ROOF") static
Referenced by activity_handlers::burrow_finish(), and activity_handlers::pickaxe_finish().
flag_TREE()
static const std::string flag_TREE ("TREE") static
Referenced by consider_butchery().
flag_USE_UPS()
static const std::string flag_USE_UPS ("USE_UPS") static
Referenced by activity_handlers::game_do_turn().
get_sorted_tiles_by_distance()
std::vector< tripoint > get_sorted_tiles_by_distance (const tripoint & abspos, const std::unordered_set< tripoint > & tiles)
Definition at line 4402 of file activity_handlers.cpp.
{
    const auto cmp = [abspos]( tripoint a, tripoint b ) {
        const int da = rl_dist( abspos, a );
        const int db = rl_dist( abspos, b );
        return da < db;
    };
    std::vector<tripoint> sorted( tiles.begin(), tiles.end() );
    std::sort( sorted.begin(), sorted.end(), cmp );
    return sorted;
}
References a, b, and rl_dist().
Referenced by activity_on_turn_move_loot(), talk_function::basecamp_mission(), find_refuel_spot_zone(), generic_multi_activity_handler(), perform_zone_activity_turn(), basecamp::place_results(), route_adjacent(), tidy_activity(), and basecamp::validate_sort_points().
magic_train()
static bool magic_train (player_activity * act, player * p) static
Definition at line 2209 of file activity_handlers.cpp.
{
    if( !p ) {
        return false;
    }
    const spell_id &sp_id = spell_id( act->name );
    if( sp_id.is_valid() ) {
        const bool knows = g->u.magic->knows_spell( sp_id );
        if( knows ) {
            spell &studying = p->magic->get_spell( sp_id );
            const int expert_multiplier = act->values.empty() ? 0 : act->values[0];
            const int xp = roll_remainder( studying.exp_modifier( *p ) * expert_multiplier );
            studying.gain_exp( xp );
            p->add_msg_if_player( m_good, _( "You learn a little about the spell: %s" ),
                                  sp_id->name );
        } else {
            p->magic->learn_spell( act->name, *p );
            // you can decline to learn this spell , as it may lock you out of other magic.
            if( p->magic->knows_spell( sp_id ) ) {
                add_msg( m_good, _( "You learn %s." ), sp_id->name.translated() );
            } else {
                act->set_to_null();
            }
        }
        return true;
    }
    return false;
}
References _, act, add_msg(), player::add_msg_if_player(), spell::exp_modifier(), g, spell::gain_exp(), string_id< T >::is_valid(), m_good, Character::magic, spell_type::name, roll_remainder(), and translation::translated().
Referenced by activity_handlers::train_finish().
perform_zone_activity_turn()
static void perform_zone_activity_turn (player * p, const zone_type_id & ztype, const std::function< bool(const tripoint &)> & tile_filter, const std::function< void(player &p, const tripoint &)> & tile_action, const std::string & finished_msg) static
Definition at line 4434 of file activity_handlers.cpp.
{
    const zone_manager &mgr = zone_manager::get_manager();
    map &here = get_map();
    const tripoint abspos = here.getabs( p->pos() );
    std::unordered_set<tripoint> unsorted_tiles = mgr.get_near( ztype, abspos );
    cleanup_tiles( unsorted_tiles, tile_filter );
    // sort remaining tiles by distance
    const std::vector<tripoint> &tiles = get_sorted_tiles_by_distance( abspos, unsorted_tiles );
    for( const tripoint &tile : tiles ) {
        const tripoint &tile_loc = here.getlocal( tile );
        std::vector<tripoint> route = here.route( p->pos(), tile_loc, p->get_pathfinding_settings(),
                                      p->get_path_avoid() );
        if( route.size() > 1 ) {
            route.pop_back();
            p->set_destination( route, p->activity );
            p->activity.set_to_null();
            return;
        } else {
            // we are at destination already
            /* Perform action */
            tile_action( *p, tile_loc );
            if( p->moves <= 0 ) {
                return;
            }
        }
    }
    add_msg( m_info, finished_msg );
    p->activity.set_to_null();
}
References Character::activity, add_msg(), cleanup_tiles(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), m_info, Creature::moves, Character::pos(), map::route(), Character::set_destination(), and player_activity::set_to_null().
Referenced by activity_handlers::fertilize_plot_do_turn().
repeat_menu()
static repeat_type repeat_menu (const std::string & title, repeat_type last_selection) static
Definition at line 2600 of file activity_handlers.cpp.
{
    uilist rmenu;
    rmenu.text = title;
    rmenu.addentry( REPEAT_ONCE, true, '1', _( "Repeat once" ) );
    rmenu.addentry( REPEAT_FOREVER, true, '2', _( "Repeat until reinforced" ) );
    rmenu.addentry( REPEAT_FULL, true, '3', _( "Repeat until fully repaired, but don't reinforce" ) );
    rmenu.addentry( REPEAT_EVENT, true, '4', _( "Repeat until success/failure/level up" ) );
    rmenu.addentry( REPEAT_INIT, true, '5', _( "Back to item selection" ) );
    rmenu.selected = last_selection - REPEAT_ONCE;
    rmenu.query();
    if( rmenu.ret >= REPEAT_INIT && rmenu.ret <= REPEAT_EVENT ) {
        return static_cast<repeat_type>( rmenu.ret );
    }
    return REPEAT_CANCEL;
}
References _, uilist::addentry(), uilist::query(), REPEAT_CANCEL, REPEAT_EVENT, REPEAT_FOREVER, REPEAT_FULL, REPEAT_INIT, REPEAT_ONCE, uilist::ret, uilist::selected, uilist::text, and PATH_INFO::title().
Referenced by activity_handlers::repair_item_finish().
rod_fish()
static void rod_fish (player * p, const std::vector< monster * > & fishables) static
Definition at line 3237 of file activity_handlers.cpp.
{
    map &here = get_map();
    //if the vector is empty (no fish around) the player is still given a small chance to get a (let us say it was hidden) fish
    if( fishables.empty() ) {
        const std::vector<mtype_id> fish_group = MonsterGroupManager::GetMonstersFromGroup(
                    mongroup_id( "GROUP_FISH" ) );
        const mtype_id fish_mon = random_entry_ref( fish_group );
        here.add_item_or_charges( p->pos(), item::make_corpse( fish_mon, calendar::turn + rng( 0_turns,
                                  3_hours ) ) );
        p->add_msg_if_player( m_good, _( "You caught a %s." ), fish_mon.obj().nname() );
    } else {
        monster *chosen_fish = random_entry( fishables );
        chosen_fish->fish_population -= 1;
        if( chosen_fish->fish_population <= 0 ) {
            g->catch_a_monster( chosen_fish, p->pos(), p, 50_hours );
        } else {
            here.add_item_or_charges( p->pos(), item::make_corpse( chosen_fish->type->id,
                                      calendar::turn + rng( 0_turns,
                                              3_hours ) ) );
            p->add_msg_if_player( m_good, _( "You caught a %s." ), chosen_fish->type->nname() );
        }
    }
    for( item &elem : here.i_at( p->pos() ) ) {
        if( elem.is_corpse() && !elem.has_var( "activity_var" ) ) {
            elem.set_var( "activity_var", p->name );
        }
    }
}
References _, map::add_item_or_charges(), player::add_msg_if_player(), monster::fish_population, g, get_map(), MonsterGroupManager::GetMonstersFromGroup(), map::i_at(), mtype::id, m_good, item::make_corpse(), Character::name, mtype::nname(), string_id< T >::obj(), Character::pos(), random_entry(), random_entry_ref(), rng(), calendar::turn, and monster::type.
Referenced by activity_handlers::fish_do_turn().
set_up_butchery_activity()
static void set_up_butchery_activity (player_activity & act, player & u, const butchery_setup & setup) static
Definition at line 688 of file activity_handlers.cpp.
{
    const auto print_reasons = [&u, &setup]() {
        for( const std::string &prob : setup.problems ) {
            u.add_msg_if_player( m_bad, prob );
        }
        if( setup.problems.empty() ) {
            for( const std::string &info : setup.info ) {
                u.add_msg_if_player( m_info, info );
            }
        }
    };
    if( setup.can_do == butchery_possibility::never ) {
        act.set_to_null();
        print_reasons();
        return;
    }
    if( setup.can_do == butchery_possibility::not_this ) {
        act.targets.pop_back();
        print_reasons();
        return;
    }
    if( setup.can_do == butchery_possibility::need_confirmation ) {
        if( u.is_player() ) {
            if( query_yn( _( "Would you dare desecrate the mortal remains of a fellow human being?" ) ) ) {
                switch( rng( 1, 3 ) ) {
                    case 1:
                        u.add_msg_if_player( m_bad, _( "You clench your teeth at the prospect of this gruesome job." ) );
                        break;
                    case 2:
                        u.add_msg_if_player( m_bad, _( "This will haunt you in your dreams." ) );
                        break;
                    case 3:
                        u.add_msg_if_player( m_bad,
                                             _( "You try to look away, but this gruesome image will stay on your mind for some time." ) );
                        break;
                }
                g->u.add_morale( MORALE_BUTCHER, -50, 0, 2_days, 3_hours );
            } else {
                u.add_msg_if_player( m_good, _( "It needs a coffin, not a knife." ) );
                act.targets.pop_back();
                return;
            }
        } else {
            u.add_morale( MORALE_BUTCHER, -50, 0, 2_days, 3_hours );
        }
    }
    print_reasons();
    act.moves_left = setup.move_cost;
    // We have a valid target, so preform the full finish function
    // instead of just selecting the next valid target
    act.index = false;
}
References _, act, Character::add_morale(), player::add_msg_if_player(), butchery_setup::can_do, g, butchery_setup::info, player::is_player(), m_bad, m_good, m_info, MORALE_BUTCHER, butchery_setup::move_cost, need_confirmation, never, not_this, butchery_setup::problems, query_yn(), and rng().
Referenced by activity_handlers::butcher_finish().
size_factor_in_time_to_cut()
static int size_factor_in_time_to_cut (m_size size) static
Definition at line 744 of file activity_handlers.cpp.
{
    switch( size ) {
        // Time (roughly) in turns to cut up the corpse
        case MS_TINY:
            return 150;
        case MS_SMALL:
            return 300;
        case MS_MEDIUM:
            return 450;
        case MS_LARGE:
            return 600;
        case MS_HUGE:
            return 1800;
        default:
            debugmsg( "Invalid m_size value for butchering corpse: %d", static_cast<int>( size ) );
            break;
    }
    return 0;
}
References debugmsg, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, and om_direction::size.
Referenced by activity_handlers::butcher_finish(), and butcher_time_to_cut().
trait_flag_CANNIBAL()
static const std::string trait_flag_CANNIBAL ("CANNIBAL") static
Referenced by consider_butchery().
trait_flag_PSYCHOPATH()
static const std::string trait_flag_PSYCHOPATH ("PSYCHOPATH") static
Referenced by consider_butchery().
trait_flag_SAPIOVORE()
static const std::string trait_flag_SAPIOVORE ("SAPIOVORE") static
Referenced by consider_butchery().
Variable Documentation
ACT_ADV_INVENTORY
const activity_id ACT_ADV_INVENTORY("ACT_ADV_INVENTORY") ("ACT_ADV_INVENTORY") static
ACT_ARMOR_LAYERS
const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS") ("ACT_ARMOR_LAYERS") static
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
ACT_BURROW
const activity_id ACT_BURROW("ACT_BURROW") ("ACT_BURROW") static
ACT_BUTCHER
const activity_id ACT_BUTCHER("ACT_BUTCHER") ("ACT_BUTCHER") static
Referenced by activity_handlers::butcher_finish().
ACT_BUTCHER_FULL
const activity_id ACT_BUTCHER_FULL("ACT_BUTCHER_FULL") ("ACT_BUTCHER_FULL") static
Referenced by activity_handlers::butcher_finish().
ACT_CHOP_LOGS
const activity_id ACT_CHOP_LOGS("ACT_CHOP_LOGS") ("ACT_CHOP_LOGS") static
ACT_CHOP_PLANKS
const activity_id ACT_CHOP_PLANKS("ACT_CHOP_PLANKS") ("ACT_CHOP_PLANKS") static
ACT_CHOP_TREE
const activity_id ACT_CHOP_TREE("ACT_CHOP_TREE") ("ACT_CHOP_TREE") static
ACT_CHURN
const activity_id ACT_CHURN("ACT_CHURN") ("ACT_CHURN") static
ACT_CLEAR_RUBBLE
const activity_id ACT_CLEAR_RUBBLE("ACT_CLEAR_RUBBLE") ("ACT_CLEAR_RUBBLE") static
ACT_CONSUME_DRINK_MENU
const activity_id ACT_CONSUME_DRINK_MENU("ACT_CONSUME_DRINK_MENU") ("ACT_CONSUME_DRINK_MENU") static
ACT_CONSUME_FOOD_MENU
const activity_id ACT_CONSUME_FOOD_MENU("ACT_CONSUME_FOOD_MENU") ("ACT_CONSUME_FOOD_MENU") static
ACT_CONSUME_MEDS_MENU
const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU") ("ACT_CONSUME_MEDS_MENU") static
ACT_CRACKING
const activity_id ACT_CRACKING("ACT_CRACKING") ("ACT_CRACKING") static
ACT_CRAFT
const activity_id ACT_CRAFT("ACT_CRAFT") ("ACT_CRAFT") static
ACT_DISMEMBER
const activity_id ACT_DISMEMBER("ACT_DISMEMBER") ("ACT_DISMEMBER") static
Referenced by activity_handlers::butcher_finish().
ACT_DISSECT
const activity_id ACT_DISSECT("ACT_DISSECT") ("ACT_DISSECT") static
Referenced by activity_handlers::butcher_finish().
ACT_EAT_MENU
const activity_id ACT_EAT_MENU("ACT_EAT_MENU") ("ACT_EAT_MENU") static
ACT_FERTILIZE_PLOT
const activity_id ACT_FERTILIZE_PLOT("ACT_FERTILIZE_PLOT") ("ACT_FERTILIZE_PLOT") static
ACT_FETCH_REQUIRED
const activity_id ACT_FETCH_REQUIRED("ACT_FETCH_REQUIRED") ("ACT_FETCH_REQUIRED") static
ACT_FIELD_DRESS
const activity_id ACT_FIELD_DRESS("ACT_FIELD_DRESS") ("ACT_FIELD_DRESS") static
Referenced by activity_handlers::butcher_finish().
ACT_FILL_LIQUID
const activity_id ACT_FILL_LIQUID("ACT_FILL_LIQUID") ("ACT_FILL_LIQUID") static
ACT_FILL_PIT
const activity_id ACT_FILL_PIT("ACT_FILL_PIT") ("ACT_FILL_PIT") static
ACT_FIND_MOUNT
const activity_id ACT_FIND_MOUNT("ACT_FIND_MOUNT") ("ACT_FIND_MOUNT") static
Referenced by activity_handlers::find_mount_do_turn().
ACT_FIRSTAID
const activity_id ACT_FIRSTAID("ACT_FIRSTAID") ("ACT_FIRSTAID") static
ACT_FISH
const activity_id ACT_FISH("ACT_FISH") ("ACT_FISH") static
ACT_FORAGE
const activity_id ACT_FORAGE("ACT_FORAGE") ("ACT_FORAGE") static
ACT_GAME
const activity_id ACT_GAME("ACT_GAME") ("ACT_GAME") static
ACT_GENERIC_GAME
const activity_id ACT_GENERIC_GAME("ACT_GENERIC_GAME") ("ACT_GENERIC_GAME") static
ACT_GUNMOD_ADD
const activity_id ACT_GUNMOD_ADD("ACT_GUNMOD_ADD") ("ACT_GUNMOD_ADD") static
ACT_HACKSAW
const activity_id ACT_HACKSAW("ACT_HACKSAW") ("ACT_HACKSAW") static
ACT_HAIRCUT
const activity_id ACT_HAIRCUT("ACT_HAIRCUT") ("ACT_HAIRCUT") static
ACT_HAND_CRANK
const activity_id ACT_HAND_CRANK("ACT_HAND_CRANK") ("ACT_HAND_CRANK") static
ACT_HOTWIRE_CAR
const activity_id ACT_HOTWIRE_CAR("ACT_HOTWIRE_CAR") ("ACT_HOTWIRE_CAR") static
ACT_JACKHAMMER
const activity_id ACT_JACKHAMMER("ACT_JACKHAMMER") ("ACT_JACKHAMMER") static
ACT_LOCKPICK
const activity_id ACT_LOCKPICK("ACT_LOCKPICK") ("ACT_LOCKPICK") static
ACT_LONGSALVAGE
const activity_id ACT_LONGSALVAGE("ACT_LONGSALVAGE") ("ACT_LONGSALVAGE") static
ACT_MAKE_ZLAVE
const activity_id ACT_MAKE_ZLAVE("ACT_MAKE_ZLAVE") ("ACT_MAKE_ZLAVE") static
ACT_MEDITATE
const activity_id ACT_MEDITATE("ACT_MEDITATE") ("ACT_MEDITATE") static
ACT_MEND_ITEM
const activity_id ACT_MEND_ITEM("ACT_MEND_ITEM") ("ACT_MEND_ITEM") static
ACT_MILK
const activity_id ACT_MILK("ACT_MILK") ("ACT_MILK") static
ACT_MIND_SPLICER
const activity_id ACT_MIND_SPLICER("ACT_MIND_SPLICER") ("ACT_MIND_SPLICER") static
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
ACT_MULTIPLE_BUTCHER
const activity_id ACT_MULTIPLE_BUTCHER("ACT_MULTIPLE_BUTCHER") ("ACT_MULTIPLE_BUTCHER") static
Referenced by butchery_drops_harvest().
ACT_MULTIPLE_CHOP_PLANKS
const activity_id ACT_MULTIPLE_CHOP_PLANKS("ACT_MULTIPLE_CHOP_PLANKS") ("ACT_MULTIPLE_CHOP_PLANKS") static
ACT_MULTIPLE_CHOP_TREES
const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES") ("ACT_MULTIPLE_CHOP_TREES") static
Referenced by activity_handlers::chop_tree_finish().
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
ACT_MULTIPLE_FARM
const activity_id ACT_MULTIPLE_FARM("ACT_MULTIPLE_FARM") ("ACT_MULTIPLE_FARM") static
ACT_MULTIPLE_FISH
const activity_id ACT_MULTIPLE_FISH("ACT_MULTIPLE_FISH") ("ACT_MULTIPLE_FISH") static
Referenced by activity_handlers::fish_finish().
ACT_MULTIPLE_MINE
const activity_id ACT_MULTIPLE_MINE("ACT_MULTIPLE_MINE") ("ACT_MULTIPLE_MINE") static
ACT_OPERATION
const activity_id ACT_OPERATION("ACT_OPERATION") ("ACT_OPERATION") static
ACT_OXYTORCH
const activity_id ACT_OXYTORCH("ACT_OXYTORCH") ("ACT_OXYTORCH") static
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
ACT_PLANT_SEED
const activity_id ACT_PLANT_SEED("ACT_PLANT_SEED") ("ACT_PLANT_SEED") static
ACT_PLAY_WITH_PET
const activity_id ACT_PLAY_WITH_PET("ACT_PLAY_WITH_PET") ("ACT_PLAY_WITH_PET") static
ACT_PRY_NAILS
const activity_id ACT_PRY_NAILS("ACT_PRY_NAILS") ("ACT_PRY_NAILS") static
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
ACT_QUARTER
const activity_id ACT_QUARTER("ACT_QUARTER") ("ACT_QUARTER") static
Referenced by activity_handlers::butcher_finish().
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
ACT_RELOAD
const activity_id ACT_RELOAD("ACT_RELOAD") ("ACT_RELOAD") static
ACT_REPAIR_ITEM
const activity_id ACT_REPAIR_ITEM("ACT_REPAIR_ITEM") ("ACT_REPAIR_ITEM") static
Referenced by activity_handlers::repair_activity_hack::patch_activity_for_furniture(), and activity_handlers::repair_activity_hack::patch_activity_for_vehicle_welder().
ACT_ROBOT_CONTROL
const activity_id ACT_ROBOT_CONTROL("ACT_ROBOT_CONTROL") ("ACT_ROBOT_CONTROL") static
ACT_SHAVE
const activity_id ACT_SHAVE("ACT_SHAVE") ("ACT_SHAVE") static
ACT_SKIN
const activity_id ACT_SKIN("ACT_SKIN") ("ACT_SKIN") static
Referenced by activity_handlers::butcher_finish().
ACT_SOCIALIZE
const activity_id ACT_SOCIALIZE("ACT_SOCIALIZE") ("ACT_SOCIALIZE") static
ACT_SPELLCASTING
const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING") ("ACT_SPELLCASTING") static
ACT_START_ENGINES
const activity_id ACT_START_ENGINES("ACT_START_ENGINES") ("ACT_START_ENGINES") static
ACT_START_FIRE
const activity_id ACT_START_FIRE("ACT_START_FIRE") ("ACT_START_FIRE") static
ACT_STUDY_SPELL
const activity_id ACT_STUDY_SPELL("ACT_STUDY_SPELL") ("ACT_STUDY_SPELL") static
ACT_TIDY_UP
const activity_id ACT_TIDY_UP("ACT_TIDY_UP") ("ACT_TIDY_UP") static
Referenced by activity_handlers::fish_finish().
ACT_TOOLMOD_ADD
const activity_id ACT_TOOLMOD_ADD("ACT_TOOLMOD_ADD") ("ACT_TOOLMOD_ADD") static
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
ACT_TRAVELLING
const activity_id ACT_TRAVELLING("ACT_TRAVELLING") ("ACT_TRAVELLING") static
Referenced by activity_handlers::travel_do_turn().
ACT_TREE_COMMUNION
const activity_id ACT_TREE_COMMUNION("ACT_TREE_COMMUNION") ("ACT_TREE_COMMUNION") static
ACT_TRY_SLEEP
const activity_id ACT_TRY_SLEEP("ACT_TRY_SLEEP") ("ACT_TRY_SLEEP") static
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
ACT_VEHICLE_DECONSTRUCTION
const activity_id ACT_VEHICLE_DECONSTRUCTION("ACT_VEHICLE_DECONSTRUCTION") ("ACT_VEHICLE_DECONSTRUCTION") static
ACT_VEHICLE_REPAIR
const activity_id ACT_VEHICLE_REPAIR("ACT_VEHICLE_REPAIR") ("ACT_VEHICLE_REPAIR") static
ACT_VIBE
const activity_id ACT_VIBE("ACT_VIBE") ("ACT_VIBE") static
ACT_WAIT
const activity_id ACT_WAIT("ACT_WAIT") ("ACT_WAIT") static
ACT_WAIT_NPC
const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC") ("ACT_WAIT_NPC") static
ACT_WAIT_STAMINA
const activity_id ACT_WAIT_STAMINA("ACT_WAIT_STAMINA") ("ACT_WAIT_STAMINA") static
ACT_WAIT_WEATHER
const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER") ("ACT_WAIT_WEATHER") static
ACT_WEAR
const activity_id ACT_WEAR("ACT_WEAR") ("ACT_WEAR") static
bio_ears
const bionic_id bio_ears("bio_ears") ("bio_ears") static
Referenced by activity_handlers::cracking_do_turn().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by activity_handlers::operation_do_turn().
effect_ai_waiting
const efftype_id effect_ai_waiting("ai_waiting") ("ai_waiting") static
Referenced by activity_handlers::find_mount_do_turn().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by activity_handlers::operation_do_turn().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by activity_handlers::operation_do_turn().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by activity_handlers::operation_do_turn().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by activity_handlers::robot_control_finish().
effect_sheared
const efftype_id effect_sheared("sheared") ("sheared") static
Referenced by activity_handlers::shear_finish().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by activity_handlers::operation_do_turn(), activity_handlers::try_sleep_do_turn(), and activity_handlers::try_sleep_finish().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by activity_handlers::milk_finish(), and activity_handlers::shear_finish().
effect_under_op
const efftype_id effect_under_op("under_operation") ("under_operation") static
Referenced by activity_handlers::operation_do_turn(), and activity_handlers::operation_finish().
HUMAN
const species_id HUMAN("HUMAN") ("HUMAN") static
Referenced by consider_butchery().
itype_2x4
const itype_id itype_2x4("2x4") ("2x4") static
Referenced by activity_handlers::chop_planks_finish(), and activity_handlers::pry_nails_finish().
itype_animal
const itype_id itype_animal("animal") ("animal") static
Referenced by activity_handlers::start_engines_finish().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), and activity_handlers::hand_crank_do_turn().
itype_burnt_out_bionic
const itype_id itype_burnt_out_bionic("burnt_out_bionic") ("burnt_out_bionic") static
Referenced by extract_or_wreck_cbms().
itype_grapnel
const itype_id itype_grapnel("grapnel") ("grapnel") static
Referenced by consider_butchery().
itype_hd_tow_cable
const itype_id itype_hd_tow_cable("hd_tow_cable") ("hd_tow_cable") static
Referenced by consider_butchery().
itype_log
const itype_id itype_log("log") ("log") static
Referenced by activity_handlers::chop_logs_finish().
itype_mind_scan_robofac
const itype_id itype_mind_scan_robofac("mind_scan_robofac") ("mind_scan_robofac") static
Referenced by activity_handlers::mind_splicer_finish().
itype_muscle
const itype_id itype_muscle("muscle") ("muscle") static
Referenced by activity_handlers::start_engines_finish().
itype_nail
const itype_id itype_nail("nail") ("nail") static
Referenced by activity_handlers::pry_nails_finish().
itype_pipe
const itype_id itype_pipe("pipe") ("pipe") static
Referenced by activity_handlers::hacksaw_finish(), and activity_handlers::oxytorch_finish().
itype_rope_30
const itype_id itype_rope_30("rope_30") ("rope_30") static
Referenced by consider_butchery().
itype_rope_makeshift_30
const itype_id itype_rope_makeshift_30("rope_makeshift_30") ("rope_makeshift_30") static
Referenced by consider_butchery().
itype_scrap
const itype_id itype_scrap("scrap") ("scrap") static
Referenced by activity_handlers::hacksaw_finish(), and activity_handlers::oxytorch_finish().
itype_sheet_metal
const itype_id itype_sheet_metal("sheet_metal") ("sheet_metal") static
Referenced by activity_handlers::oxytorch_finish().
itype_spike
const itype_id itype_spike("spike") ("spike") static
Referenced by activity_handlers::hacksaw_finish(), and activity_handlers::oxytorch_finish().
itype_splinter
const itype_id itype_splinter("splinter") ("splinter") static
Referenced by activity_handlers::chop_logs_finish(), and activity_handlers::chop_planks_finish().
itype_steel_chunk
const itype_id itype_steel_chunk("steel_chunk") ("steel_chunk") static
Referenced by activity_handlers::hacksaw_finish(), and activity_handlers::oxytorch_finish().
itype_steel_plate
const itype_id itype_steel_plate("steel_plate") ("steel_plate") static
Referenced by activity_handlers::oxytorch_finish().
itype_stick_long
const itype_id itype_stick_long("stick_long") ("stick_long") static
Referenced by activity_handlers::chop_logs_finish().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by activity_handlers::game_do_turn().
itype_vine_30
const itype_id itype_vine_30("vine_30") ("vine_30") static
Referenced by consider_butchery().
itype_welder
const itype_id itype_welder("welder") ("welder") static
Referenced by activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool().
itype_wire
const itype_id itype_wire("wire") ("wire") static
Referenced by activity_handlers::hacksaw_finish(), and activity_handlers::oxytorch_finish().
itype_wool_staple
const itype_id itype_wool_staple("wool_staple") ("wool_staple") static
Referenced by activity_handlers::shear_finish().
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static
Referenced by activity_handlers::butcher_finish(), butcher_time_to_cut(), and consider_butchery().
qual_CUT_FINE
const quality_id qual_CUT_FINE("CUT_FINE") ("CUT_FINE") static
Referenced by activity_handlers::butcher_finish(), butcher_time_to_cut(), and consider_butchery().
qual_LOCKPICK
const quality_id qual_LOCKPICK("LOCKPICK") ("LOCKPICK") static
Referenced by activity_handlers::lockpicking_finish().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by activity_handlers::robot_control_finish().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by activity_handlers::butcher_finish().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by activity_handlers::pry_nails_finish().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by activity_handlers::butcher_finish(), and activity_handlers::make_zlave_finish().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by activity_handlers::lockpicking_finish().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by activity_handlers::butcher_finish(), butchery_drops_harvest(), activity_handlers::fish_do_turn(), activity_handlers::forage_finish(), activity_handlers::make_zlave_finish(), activity_handlers::pulp_do_turn(), and activity_handlers::start_fire_finish().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by activity_handlers::build_do_turn().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by activity_handlers::operation_do_turn().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by activity_handlers::tree_communion_do_turn().
trait_STOCKY_TROGLO
const trait_id trait_STOCKY_TROGLO("STOCKY_TROGLO") ("STOCKY_TROGLO") static
Referenced by activity_handlers::pickaxe_finish().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by consider_butchery().
zone_type_FARM_PLOT
const zone_type_id zone_type_FARM_PLOT("FARM_PLOT") ("FARM_PLOT") static
Referenced by activity_handlers::fertilize_plot_do_turn().