Cataclysm BN: src/activity_actor.cpp File Reference
activity_actor.cpp File Reference
#include "activity_actor.h"
#include "activity_actor_definitions.h"
#include <algorithm>
#include <cmath>
#include <list>
#include <string>
#include <utility>
#include "avatar_action.h"
#include "activity_handlers.h"
#include "advanced_inv.h"
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "crafting.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "game.h"
#include "gates.h"
#include "iexamine.h"
#include "int_id.h"
#include "item.h"
#include "item_group.h"
#include "item_location.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "npc.h"
#include "output.h"
#include "options.h"
#include "pickup.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "ranged.h"
#include "recipe_dictionary.h"
#include "rng.h"
#include "sounds.h"
#include "timed_event.h"
#include "translations.h"
#include "uistate.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
namespace activity_actors
Enumerations
enum hack_result { HACK_UNABLE , HACK_FAIL , HACK_NOTHING , HACK_SUCCESS }
enum hack_type { HACK_SAFE , HACK_DOOR , HACK_GAS , HACK_NULL }
Functions
static const std::string flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT")
static const std::string has_thievery_witness ("has_thievery_witness")
static int hack_level (const Character &who)
static hack_result hack_attempt (Character &who, const bool using_bionic)
static hack_type get_hack_type (tripoint examp)
void serialize (const cata::clone_ptr< activity_actor > &actor, JsonOut &jsout)
void deserialize (cata::clone_ptr< activity_actor > &actor, JsonIn &jsin)
Variables
static const itype_id itype_bone_human ("bone_human")
static const itype_id itype_electrohack ("electrohack")
static const skill_id skill_computer ("computer")
static const mtype_id mon_zombie ("mon_zombie")
static const mtype_id mon_zombie_fat ("mon_zombie_fat")
static const mtype_id mon_zombie_rot ("mon_zombie_rot")
static const mtype_id mon_skeleton ("mon_skeleton")
static const mtype_id mon_zombie_crawler ("mon_zombie_crawler")
const std::unordered_map< activity_id, std::unique_ptr< activity_actor > JsonIn activity_actors::deserialize_functions
Enumeration Type Documentation
hack_result
enum hack_result
Enumerator
HACK_UNABLE
HACK_FAIL
HACK_NOTHING
HACK_SUCCESS
Definition at line 742 of file activity_actor.cpp.
                 {
    HACK_UNABLE,
    HACK_FAIL,
    HACK_NOTHING,
    HACK_SUCCESS
};
hack_type
enum hack_type
Enumerator
HACK_SAFE
HACK_DOOR
HACK_GAS
HACK_NULL
Definition at line 749 of file activity_actor.cpp.
               {
    HACK_SAFE,
    HACK_DOOR,
    HACK_GAS,
    HACK_NULL
};
Function Documentation
deserialize()
void deserialize (cata::clone_ptr< activity_actor > & actor, JsonIn & jsin)
Definition at line 1301 of file activity_actor.cpp.
{
    if( jsin.test_null() ) {
        actor = nullptr;
    } else {
        JsonObject data = jsin.get_object();
        if( data.has_member( "actor_data" ) ) {
            activity_id actor_type;
            data.read( "actor_type", actor_type );
            auto deserializer = activity_actors::deserialize_functions.find( actor_type );
            if( deserializer != activity_actors::deserialize_functions.end() ) {
                actor = deserializer->second( *data.get_raw( "actor_data" ) );
            } else {
                debugmsg( "Failed to find activity actor deserializer for type \"%s\"", actor_type.c_str() );
                actor = nullptr;
            }
        } else {
            debugmsg( "Failed to load activity actor" );
            actor = nullptr;
        }
    }
}
References string_id< T >::c_str(), debugmsg, activity_actors::deserialize_functions, JsonIn::get_object(), JsonObject::get_raw(), JsonObject::has_member(), JsonObject::read(), and JsonIn::test_null().
Referenced by edit_json(), activity_handlers::fill_liquid_do_turn(), and auto_pickup::player_settings::load().
flag_RELOAD_AND_SHOOT()
static const std::string flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT") static
Referenced by aim_activity_actor::do_turn(), and aim_activity_actor::unload_RAS_weapon().
get_hack_type()
static hack_type get_hack_type (tripoint examp) static
Definition at line 803 of file activity_actor.cpp.
{
    hack_type type = HACK_NULL;
    const map &here = get_map();
    const furn_t &xfurn_t = here.furn( examp ).obj();
    const ter_t &xter_t = here.ter( examp ).obj();
    if( xter_t.examine == &iexamine::pay_gas || xfurn_t.examine == &iexamine::pay_gas ) {
        type = HACK_GAS;
    } else if( xter_t.examine == &iexamine::cardreader || xfurn_t.examine == &iexamine::cardreader ) {
        type = HACK_DOOR;
    } else if( xter_t.examine == &iexamine::gunsafe_el || xfurn_t.examine == &iexamine::gunsafe_el ) {
        type = HACK_SAFE;
    }
    return type;
}
References iexamine::cardreader(), map_data_common_t::examine, map::furn(), get_map(), iexamine::gunsafe_el(), HACK_DOOR, HACK_GAS, HACK_NULL, HACK_SAFE, int_id< T >::obj(), iexamine::pay_gas(), map::ter(), and type.
Referenced by hacking_activity_actor::finish(), and activity_handlers::repair_item_finish().
hack_attempt()
static hack_result hack_attempt (Character & who, const bool using_bionic) static
Definition at line 765 of file activity_actor.cpp.
{
    // TODO: Remove this once player -> Character migration is complete
    {
        player *p = dynamic_cast<player *>( &who );
        p->practice( skill_computer, 20 );
    }
    // only skilled supergenius never cause short circuits, but the odds are low for people
    // with moderate skills
    const int hack_stddev = 5;
    int success = std::ceil( normal_roll( hack_level( who ), hack_stddev ) );
    if( success < 0 ) {
        who.add_msg_if_player( _( "You cause a short circuit!" ) );
        if( using_bionic ) {
            who.mod_power_level( -25_kJ );
        } else {
            who.use_charges( itype_electrohack, 25 );
        }
        if( success <= -5 ) {
            if( !using_bionic ) {
                who.add_msg_if_player( m_bad, _( "Your electrohack is ruined!" ) );
                who.use_amount( itype_electrohack, 1 );
            } else {
                who.add_msg_if_player( m_bad, _( "Your power is drained!" ) );
                who.mod_power_level( units::from_kilojoule( -rng( 25,
                                     units::to_kilojoule( who.get_power_level() ) ) ) );
            }
        }
        return HACK_FAIL;
    } else if( success < 6 ) {
        return HACK_NOTHING;
    } else {
        return HACK_SUCCESS;
    }
}
References _, Creature::add_msg_if_player(), units::from_kilojoule(), Character::get_power_level(), HACK_FAIL, hack_level(), HACK_NOTHING, HACK_SUCCESS, itype_electrohack, m_bad, Character::mod_power_level(), normal_roll(), player::practice(), rng(), skill_computer, behavior::success, units::to_kilojoule(), Character::use_amount(), and Character::use_charges().
Referenced by hacking_activity_actor::finish().
hack_level()
static int hack_level (const Character & who) static
Computer increases success chance of hacking card readers Intelligence increases success chance of hacking card readers
Definition at line 756 of file activity_actor.cpp.
{
    ///\EFFECT_COMPUTER increases success chance of hacking card readers
    // odds go up with int>8, down with int<8
    // 4 int stat is worth 1 computer skill here
    ///\EFFECT_INT increases success chance of hacking card readers
    return who.get_skill_level( skill_computer ) + who.int_cur / 2 - 8;
}
References Character::get_skill_level(), Character::int_cur, and skill_computer.
Referenced by hack_attempt().
has_thievery_witness()
static const std::string has_thievery_witness ("has_thievery_witness") static
Referenced by pickup_activity_actor::do_turn().
serialize()
void serialize (const cata::clone_ptr< activity_actor > & actor, JsonOut & jsout)
Definition at line 1287 of file activity_actor.cpp.
{
    if( !actor ) {
        jsout.write_null();
    } else {
        jsout.start_object();
        jsout.member( "actor_type", actor->get_type() );
        jsout.member( "actor_data", *actor );
        jsout.end_object();
    }
}
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and JsonOut::write_null().
Referenced by edit_json(), activity_handlers::fill_liquid_do_turn(), auto_pickup::player_settings::save(), and serialize_liquid_source().
Variable Documentation
itype_bone_human
const itype_id itype_bone_human("bone_human") ("bone_human") static
Referenced by dig_activity_actor::finish().
itype_electrohack
const itype_id itype_electrohack("electrohack") ("electrohack") static
Referenced by hack_attempt().
mon_skeleton
const mtype_id mon_skeleton("mon_skeleton") ("mon_skeleton") static
Referenced by dig_activity_actor::finish().
mon_zombie
const mtype_id mon_zombie("mon_zombie") ("mon_zombie") static
Referenced by dig_activity_actor::finish().
mon_zombie_crawler
const mtype_id mon_zombie_crawler("mon_zombie_crawler") ("mon_zombie_crawler") static
Referenced by dig_activity_actor::finish().
mon_zombie_fat
const mtype_id mon_zombie_fat("mon_zombie_fat") ("mon_zombie_fat") static
Referenced by dig_activity_actor::finish().
mon_zombie_rot
const mtype_id mon_zombie_rot("mon_zombie_rot") ("mon_zombie_rot") static
Referenced by dig_activity_actor::finish().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by hack_attempt(), and hack_level().