Cataclysm BN: src/active_tile_data.cpp File Reference
active_tile_data.cpp File Reference
#include "active_tile_data.h"
#include "active_tile_data_def.h"
#include "coordinate_conversions.h"
#include "debug.h"
#include "distribution_grid.h"
#include "item.h"
#include "itype.h"
#include "json.h"
#include "map.h"
#include "mapbuffer.h"
#include "rng.h"
#include "vehicle.h"
#include "vpart_range.h"
#include "weather.h"
#include "submap.h"
Classes
class null_tile_data
Namespaces
namespace active_tiles
Functions
static const std::string flag_RECHARGE ("RECHARGE")
static const std::string flag_USE_UPS ("USE_UPS")
template<typename T >
T * active_tiles::furn_at (const tripoint_abs_ms &p)
template active_tile_data * active_tiles::furn_at< active_tile_data > (const tripoint_abs_ms &)
template vehicle_connector_tile * active_tiles::furn_at< vehicle_connector_tile > (const tripoint_abs_ms &)
template battery_tile * active_tiles::furn_at< battery_tile > (const tripoint_abs_ms &)
template steady_consumer_tile * active_tiles::furn_at< steady_consumer_tile > (const tripoint_abs_ms &)
template charge_watcher_tile * active_tiles::furn_at< charge_watcher_tile > (const tripoint_abs_ms &)
int ticks_between (const time_point &from, const time_point &to, const time_duration &tick_length)
static std::map< std::string, std::unique_ptr< active_tile_data > > build_type_map ()
Variables
static const itype_id itype_battery ("battery")
Function Documentation
build_type_map()
static std::map< std::string, std::unique_ptr< active_tile_data > > build_type_map () static
Definition at line 380 of file active_tile_data.cpp.
{
    std::map<std::string, std::unique_ptr<active_tile_data>> type_map;
    const auto add_type = [&type_map]( active_tile_data * arg ) {
        type_map[arg->get_type()].reset( arg );
    };
    add_type( new battery_tile() );
    add_type( new charge_watcher_tile() );
    add_type( new charger_tile() );
    add_type( new solar_tile() );
    add_type( new steady_consumer_tile() );
    add_type( new vehicle_connector_tile() );
    return type_map;
}
References arg().
Referenced by active_tile_data::create().
flag_RECHARGE()
static const std::string flag_RECHARGE ("RECHARGE") static
Referenced by charger_tile::update_internal().
flag_USE_UPS()
static const std::string flag_USE_UPS ("USE_UPS") static
Referenced by charger_tile::update_internal().
ticks_between()
int ticks_between (const time_point & from, const time_point & to, const time_duration & tick_length) inline
Definition at line 106 of file active_tile_data.cpp.
{
    return ( to_turn<int>( to ) / to_turns<int>( tick_length ) ) - ( to_turn<int>
            ( from ) / to_turns<int>( tick_length ) );
}
Referenced by steady_consumer_tile::update_internal().
Variable Documentation
itype_battery
const itype_id itype_battery("battery") ("battery") static