Cataclysm BN: src/action.cpp File Reference
action.cpp File Reference
#include "action.h"
#include <algorithm>
#include <climits>
#include <istream>
#include <iterator>
#include <memory>
#include <utility>
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "crafting.h"
#include "creature.h"
#include "cursesdef.h"
#include "debug.h"
#include "game.h"
#include "iexamine.h"
#include "input.h"
#include "item.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "popup.h"
#include "ret_val.h"
#include "string_utils.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "vehicle.h"
#include "vpart_position.h"
Macros
#define REGISTER_ACTION(name)
#define REGISTER_CATEGORY(name)
Functions
static const std::string flag_CONSOLE ("CONSOLE")
static const std::string flag_FLOTATION ("FLOTATION")
static const std::string flag_GOES_DOWN ("GOES_DOWN")
static const std::string flag_GOES_UP ("GOES_UP")
static const std::string flag_REACH_ATTACK ("REACH_ATTACK")
static const std::string flag_SWIMMABLE ("SWIMMABLE")
std::vector< char > keys_bound_to (action_id act, const bool restrict_to_printable)
Get list of keys bound to an action ID.
action_id action_from_key (char ch)
Lookup the action ID assigned to a given key.
std::string action_ident (action_id act)
Lookup a unique string identifier for a given action ID.
bool can_action_change_worldstate (const action_id act)
Lookup whether an action can affect the state of the game world.
action_id look_up_action (const std::string &ident)
Lookup an action ID by its unique string identifier.
std::string press_x (action_id act)
std::string press_x (action_id act, const std::string &key_bound, const std::string &key_unbound)
std::string press_x (action_id act, const std::string &key_bound_pre, const std::string &key_bound_suf, const std::string &key_unbound)
cata::optional< std::string > press_x_if_bound (action_id act)
action_id get_movement_action_from_delta (const tripoint &d, const iso_rotate rot)
Translate coordinate delta into movement action.
point get_delta_from_movement_action (const action_id act, const iso_rotate rot)
int hotkey_for_action (action_id action, const bool restrict_to_printable)
Get the key for an action, used in the action menu to give each action the hotkey it is bound to.
bool can_butcher_at (const tripoint &p)
Test whether it is possible to perform butcher action.
bool can_move_vertical_at (const tripoint &p, int movez)
Test whether vertical movement is possible.
bool can_examine_at (const tripoint &p)
Test whether examine is possible.
static bool can_pickup_at (const tripoint &p)
bool can_interact_at (action_id action, const tripoint &p)
Test whether it is possible to perform a given action.
action_id handle_action_menu ()
Show the action menu.
action_id handle_main_menu ()
Show in-game main menu.
cata::optional< tripoint > choose_direction (const std::string &message, const bool allow_vertical)
Request player input of a direction, possibly including vertical component.
cata::optional< tripoint > choose_adjacent (const std::string &message, const bool allow_vertical)
Request player input of adjacent tile, possibly including vertical tiles.
cata::optional< tripoint > choose_adjacent_highlight (const std::string &message, const std::string &failure_message, const action_id action, bool allow_vertical)
Request player input of adjacent tile with highlighting, possibly on different z-level.
cata::optional< tripoint > choose_adjacent_highlight (const std::string &message, const std::string &failure_message, const std::function< bool(const tripoint &)> &allowed, const bool allow_vertical)
Request player input of adjacent tile with highlighting, possibly on different z-level.
Variables
static const quality_id qual_BUTCHER ("BUTCHER")
static const quality_id qual_CUT_FINE ("CUT_FINE")
Macro Definition Documentation
REGISTER_ACTION
#define REGISTER_ACTION (name)
Value:
        entries.emplace_back( name, true, hotkey_for_action(name), \
        ctxt.get_action_name( action_ident( name ) ) );
REGISTER_CATEGORY
#define REGISTER_CATEGORY (name)
Value:
    categories_by_int[last_category] = name; \
    catgname = name; \
    catgname += "…"; \
    entries.emplace_back( last_category, true, -1, catgname ); \
    last_category++;
Function Documentation
action_from_key()
action_id action_from_key (char ch)
Lookup the action ID assigned to a given key.
Looks up a key by character and returns the action_id currently mapped to that key. If no key is currently mapped then ACTION_NULL is returned instead
Parameters
ch The character corresponding to the key to look up
Returns
The action id of the specified key
Definition at line 60 of file action.cpp.
{
    input_context ctxt = get_default_mode_input_context();
    const input_event event( ch, CATA_INPUT_KEYBOARD );
    const std::string &action = ctxt.input_to_action( event );
    return look_up_action( action );
}
References action, CATA_INPUT_KEYBOARD, get_default_mode_input_context(), input_context::input_to_action(), and look_up_action().
action_ident()
std::string action_ident (action_id act)
Lookup a unique string identifier for a given action ID.
Translates an action_id into a unique string identifier. This is the value recorded in the keymap configuration file.
Note
The values we use here are more or less human-readable, but are not always suitable for display directly to the user.
Parameters
act The action ID to lookup an identifier for
Returns
The string identifier for the specified action ID.
Definition at line 68 of file action.cpp.
{
    switch( act ) {
        case ACTION_PAUSE:
            return "pause";
        case ACTION_TIMEOUT:
            return "TIMEOUT";
        case ACTION_MOVE_FORTH:
            return "UP";
        case ACTION_MOVE_FORTH_RIGHT:
            return "RIGHTUP";
        case ACTION_MOVE_RIGHT:
            return "RIGHT";
        case ACTION_MOVE_BACK_RIGHT:
            return "RIGHTDOWN";
        case ACTION_MOVE_BACK:
            return "DOWN";
        case ACTION_MOVE_BACK_LEFT:
            return "LEFTDOWN";
        case ACTION_MOVE_LEFT:
            return "LEFT";
        case ACTION_MOVE_FORTH_LEFT:
            return "LEFTUP";
        case ACTION_MOVE_DOWN:
            return "LEVEL_DOWN";
        case ACTION_MOVE_UP:
            return "LEVEL_UP";
        case ACTION_TOGGLE_MAP_MEMORY:
            return "toggle_map_memory";
        case ACTION_CENTER:
            return "center";
        case ACTION_SHIFT_N:
            return "shift_n";
        case ACTION_SHIFT_NE:
            return "shift_ne";
        case ACTION_SHIFT_E:
            return "shift_e";
        case ACTION_SHIFT_SE:
            return "shift_se";
        case ACTION_SHIFT_S:
            return "shift_s";
        case ACTION_SHIFT_SW:
            return "shift_sw";
        case ACTION_SHIFT_W:
            return "shift_w";
        case ACTION_SHIFT_NW:
            return "shift_nw";
        case ACTION_CYCLE_MOVE:
            return "cycle_move";
        case ACTION_RESET_MOVE:
            return "reset_move";
        case ACTION_TOGGLE_RUN:
            return "toggle_run";
        case ACTION_TOGGLE_CROUCH:
            return "toggle_crouch";
        case ACTION_OPEN_MOVEMENT:
            return "open_movement";
        case ACTION_OPEN:
            return "open";
        case ACTION_CLOSE:
            return "close";
        case ACTION_SMASH:
            return "smash";
        case ACTION_EXAMINE:
            return "examine";
        case ACTION_ADVANCEDINV:
            return "advinv";
        case ACTION_PICKUP:
            return "pickup";
        case ACTION_PICKUP_FEET:
            return "pickup_feet";
        case ACTION_GRAB:
            return "grab";
        case ACTION_HAUL:
            return "haul";
        case ACTION_BUTCHER:
            return "butcher";
        case ACTION_CHAT:
            return "chat";
        case ACTION_LOOK:
            return "look";
        case ACTION_PEEK:
            return "peek";
        case ACTION_LIST_ITEMS:
            return "listitems";
        case ACTION_ZONES:
            return "zones";
        case ACTION_LOOT:
            return "loot";
        case ACTION_INVENTORY:
            return "inventory";
        case ACTION_COMPARE:
            return "compare";
        case ACTION_ORGANIZE:
            return "organize";
        case ACTION_USE:
            return "apply";
        case ACTION_USE_WIELDED:
            return "apply_wielded";
        case ACTION_WEAR:
            return "wear";
        case ACTION_TAKE_OFF:
            return "take_off";
        case ACTION_EAT:
            return "eat";
        case ACTION_OPEN_CONSUME:
            return "open_consume";
        case ACTION_READ:
            return "read";
        case ACTION_WIELD:
            return "wield";
        case ACTION_PICK_STYLE:
            return "pick_style";
        case ACTION_RELOAD_ITEM:
            return "reload_item";
        case ACTION_RELOAD_WEAPON:
            return "reload_weapon";
        case ACTION_RELOAD_WIELDED:
            return "reload_wielded";
        case ACTION_UNLOAD:
            return "unload";
        case ACTION_MEND:
            return "mend";
        case ACTION_THROW:
            return "throw";
        case ACTION_FIRE:
            return "fire";
        case ACTION_FIRE_BURST:
            return "fire_burst";
        case ACTION_CAST_SPELL:
            return "cast_spell";
        case ACTION_SELECT_FIRE_MODE:
            return "select_fire_mode";
        case ACTION_SELECT_DEFAULT_AMMO:
            return "select_default_ammo";
        case ACTION_DROP:
            return "drop";
        case ACTION_DIR_DROP:
            return "drop_adj";
        case ACTION_BIONICS:
            return "bionics";
        case ACTION_MUTATIONS:
            return "mutations";
        case ACTION_SORT_ARMOR:
            return "sort_armor";
        case ACTION_WAIT:
            return "wait";
        case ACTION_CRAFT:
            return "craft";
        case ACTION_RECRAFT:
            return "recraft";
        case ACTION_LONGCRAFT:
            return "long_craft";
        case ACTION_CONSTRUCT:
            return "construct";
        case ACTION_DISASSEMBLE:
            return "disassemble";
        case ACTION_SLEEP:
            return "sleep";
        case ACTION_CONTROL_VEHICLE:
            return "control_vehicle";
        case ACTION_TOGGLE_AUTO_TRAVEL_MODE:
            return "auto_travel_mode";
        case ACTION_TOGGLE_SAFEMODE:
            return "safemode";
        case ACTION_TOGGLE_AUTOSAFE:
            return "autosafe";
        case ACTION_TOGGLE_THIEF_MODE:
            return "toggle_thief_mode";
        case ACTION_IGNORE_ENEMY:
            return "ignore_enemy";
        case ACTION_WHITELIST_ENEMY:
            return "whitelist_enemy";
        case ACTION_SAVE:
            return "save";
        case ACTION_QUICKSAVE:
            return "quicksave";
        case ACTION_QUICKLOAD:
            return "quickload";
        case ACTION_SUICIDE:
            return "SUICIDE";
        case ACTION_PL_INFO:
            return "player_data";
        case ACTION_MAP:
            return "map";
        case ACTION_SKY:
            return "sky";
        case ACTION_MISSIONS:
            return "missions";
        case ACTION_FACTIONS:
            return "factions";
        case ACTION_SCORES:
            return "scores";
        case ACTION_MORALE:
            return "morale";
        case ACTION_MESSAGES:
            return "messages";
        case ACTION_HELP:
            return "help";
        case ACTION_DEBUG:
            return "debug";
        case ACTION_DISPLAY_SCENT:
            return "debug_scent";
        case ACTION_DISPLAY_SCENT_TYPE:
            return "debug_scent_type";
        case ACTION_DISPLAY_TEMPERATURE:
            return "debug_temp";
        case ACTION_DISPLAY_VEHICLE_AI:
            return "debug_vehicle_ai";
        case ACTION_DISPLAY_VISIBILITY:
            return "debug_visibility";
        case ACTION_DISPLAY_TRANSPARENCY:
            return "debug_transparency";
        case ACTION_DISPLAY_LIGHTING:
            return "debug_lighting";
        case ACTION_DISPLAY_RADIATION:
            return "debug_radiation";
        case ACTION_DISPLAY_SUBMAP_GRID:
            return "debug_submap_grid";
        case ACTION_TOGGLE_HOUR_TIMER:
            return "debug_hour_timer";
        case ACTION_TOGGLE_DEBUG_MODE:
            return "debug_mode";
        case ACTION_ZOOM_OUT:
            return "zoom_out";
        case ACTION_ZOOM_IN:
            return "zoom_in";
        case ACTION_TOGGLE_FULLSCREEN:
            return "toggle_fullscreen";
        case ACTION_TOGGLE_PIXEL_MINIMAP:
            return "toggle_pixel_minimap";
        case ACTION_TOGGLE_PANEL_ADM:
            return "toggle_panel_adm";
        case ACTION_PANEL_MGMT:
            return "panel_mgmt";
        case ACTION_RELOAD_TILESET:
            return "reload_tileset";
        case ACTION_TOGGLE_AUTO_FEATURES:
            return "toggle_auto_features";
        case ACTION_TOGGLE_AUTO_PULP_BUTCHER:
            return "toggle_auto_pulp_butcher";
        case ACTION_TOGGLE_AUTO_MINING:
            return "toggle_auto_mining";
        case ACTION_TOGGLE_AUTO_FORAGING:
            return "toggle_auto_foraging";
        case ACTION_TOGGLE_AUTO_PICKUP:
            return "toggle_auto_pickup";
        case ACTION_ACTIONMENU:
            return "action_menu";
        case ACTION_ITEMACTION:
            return "item_action_menu";
        case ACTION_SELECT:
            return "SELECT";
        case ACTION_SEC_SELECT:
            return "SEC_SELECT";
        case ACTION_AUTOATTACK:
            return "autoattack";
        case ACTION_MAIN_MENU:
            return "main_menu";
        case ACTION_DIARY:
            return "diary";
        case ACTION_KEYBINDINGS:
            return "HELP_KEYBINDINGS";
        case ACTION_OPTIONS:
            return "open_options";
        case ACTION_AUTOPICKUP:
            return "open_autopickup";
        case ACTION_AUTONOTES:
            return "open_autonotes";
        case ACTION_SAFEMODE:
            return "open_safemode";
        case ACTION_COLOR:
            return "open_color";
        case ACTION_WORLD_MODS:
            return "open_world_mods";
        case ACTION_DISTRACTION_MANAGER:
            return "open_distraction_manager";
        case ACTION_NULL:
            return "null";
        default:
            return "unknown";
    }
}
References act, ACTION_ACTIONMENU, ACTION_ADVANCEDINV, ACTION_AUTOATTACK, ACTION_AUTONOTES, ACTION_AUTOPICKUP, ACTION_BIONICS, ACTION_BUTCHER, ACTION_CAST_SPELL, ACTION_CENTER, ACTION_CHAT, ACTION_CLOSE, ACTION_COLOR, ACTION_COMPARE, ACTION_CONSTRUCT, ACTION_CONTROL_VEHICLE, ACTION_CRAFT, ACTION_CYCLE_MOVE, ACTION_DEBUG, ACTION_DIARY, ACTION_DIR_DROP, ACTION_DISASSEMBLE, ACTION_DISPLAY_LIGHTING, ACTION_DISPLAY_RADIATION, ACTION_DISPLAY_SCENT, ACTION_DISPLAY_SCENT_TYPE, ACTION_DISPLAY_SUBMAP_GRID, ACTION_DISPLAY_TEMPERATURE, ACTION_DISPLAY_TRANSPARENCY, ACTION_DISPLAY_VEHICLE_AI, ACTION_DISPLAY_VISIBILITY, ACTION_DISTRACTION_MANAGER, ACTION_DROP, ACTION_EAT, ACTION_EXAMINE, ACTION_FACTIONS, ACTION_FIRE, ACTION_FIRE_BURST, ACTION_GRAB, ACTION_HAUL, ACTION_HELP, ACTION_IGNORE_ENEMY, ACTION_INVENTORY, ACTION_ITEMACTION, ACTION_KEYBINDINGS, ACTION_LIST_ITEMS, ACTION_LONGCRAFT, ACTION_LOOK, ACTION_LOOT, ACTION_MAIN_MENU, ACTION_MAP, ACTION_MEND, ACTION_MESSAGES, ACTION_MISSIONS, ACTION_MORALE, ACTION_MOVE_BACK, ACTION_MOVE_BACK_LEFT, ACTION_MOVE_BACK_RIGHT, ACTION_MOVE_DOWN, ACTION_MOVE_FORTH, ACTION_MOVE_FORTH_LEFT, ACTION_MOVE_FORTH_RIGHT, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_MUTATIONS, ACTION_NULL, ACTION_OPEN, ACTION_OPEN_CONSUME, ACTION_OPEN_MOVEMENT, ACTION_OPTIONS, ACTION_ORGANIZE, ACTION_PANEL_MGMT, ACTION_PAUSE, ACTION_PEEK, ACTION_PICK_STYLE, ACTION_PICKUP, ACTION_PICKUP_FEET, ACTION_PL_INFO, ACTION_QUICKLOAD, ACTION_QUICKSAVE, ACTION_READ, ACTION_RECRAFT, ACTION_RELOAD_ITEM, ACTION_RELOAD_TILESET, ACTION_RELOAD_WEAPON, ACTION_RELOAD_WIELDED, ACTION_RESET_MOVE, ACTION_SAFEMODE, ACTION_SAVE, ACTION_SCORES, ACTION_SEC_SELECT, ACTION_SELECT, ACTION_SELECT_DEFAULT_AMMO, ACTION_SELECT_FIRE_MODE, ACTION_SHIFT_E, ACTION_SHIFT_N, ACTION_SHIFT_NE, ACTION_SHIFT_NW, ACTION_SHIFT_S, ACTION_SHIFT_SE, ACTION_SHIFT_SW, ACTION_SHIFT_W, ACTION_SKY, ACTION_SLEEP, ACTION_SMASH, ACTION_SORT_ARMOR, ACTION_SUICIDE, ACTION_TAKE_OFF, ACTION_THROW, ACTION_TIMEOUT, ACTION_TOGGLE_AUTO_FEATURES, ACTION_TOGGLE_AUTO_FORAGING, ACTION_TOGGLE_AUTO_MINING, ACTION_TOGGLE_AUTO_PICKUP, ACTION_TOGGLE_AUTO_PULP_BUTCHER, ACTION_TOGGLE_AUTO_TRAVEL_MODE, ACTION_TOGGLE_AUTOSAFE, ACTION_TOGGLE_CROUCH, ACTION_TOGGLE_DEBUG_MODE, ACTION_TOGGLE_FULLSCREEN, ACTION_TOGGLE_HOUR_TIMER, ACTION_TOGGLE_MAP_MEMORY, ACTION_TOGGLE_PANEL_ADM, ACTION_TOGGLE_PIXEL_MINIMAP, ACTION_TOGGLE_RUN, ACTION_TOGGLE_SAFEMODE, ACTION_TOGGLE_THIEF_MODE, ACTION_UNLOAD, ACTION_USE, ACTION_USE_WIELDED, ACTION_WAIT, ACTION_WEAR, ACTION_WHITELIST_ENEMY, ACTION_WIELD, ACTION_WORLD_MODS, ACTION_ZONES, ACTION_ZOOM_IN, and ACTION_ZOOM_OUT.
Referenced by help::get_dir_grid(), game::get_player_input(), game::handle_action(), handle_main_menu(), input_manager::init(), keys_bound_to(), look_up_action(), press_x(), and press_x_if_bound().
can_action_change_worldstate()
bool can_action_change_worldstate (action_id act)
Lookup whether an action can affect the state of the game world.
Looks an action ID up and determines if that action can change world state in any case. This is a static determination from a hard-coded list.
This function can be used to count the number of user actions that actually affected the game state separate from other actions that only result in view and menu navigation. The only current example of this is game::user_action_counter.
Parameters
act action ID to lookup in table
Returns
true if action has potential to alter world state, otherwise returns false.
Definition at line 352 of file action.cpp.
{
    switch( act ) {
        // Shift view
        case ACTION_TOGGLE_MAP_MEMORY:
        case ACTION_CENTER:
        case ACTION_SHIFT_N:
        case ACTION_SHIFT_NE:
        case ACTION_SHIFT_E:
        case ACTION_SHIFT_SE:
        case ACTION_SHIFT_S:
        case ACTION_SHIFT_SW:
        case ACTION_SHIFT_W:
        case ACTION_SHIFT_NW:
        // Environment Interaction
        case ACTION_LOOK:
        case ACTION_LIST_ITEMS:
        case ACTION_ZONES:
        // Long-term / special actions
        case ACTION_SAVE:
        case ACTION_QUICKSAVE:
        case ACTION_QUICKLOAD:
        case ACTION_SUICIDE:
        // Info Screens
        case ACTION_PL_INFO:
        case ACTION_MAP:
        case ACTION_SKY:
        case ACTION_MISSIONS:
        case ACTION_SCORES:
        case ACTION_FACTIONS:
        case ACTION_MORALE:
        case ACTION_MESSAGES:
        case ACTION_HELP:
        case ACTION_MAIN_MENU:
        case ACTION_KEYBINDINGS:
        case ACTION_OPTIONS:
        case ACTION_AUTOPICKUP:
        case ACTION_AUTONOTES:
        case ACTION_SAFEMODE:
        case ACTION_COLOR:
        case ACTION_WORLD_MODS:
        case ACTION_DISTRACTION_MANAGER:
        // Debug Functions
        case ACTION_TOGGLE_FULLSCREEN:
        case ACTION_DEBUG:
        case ACTION_DISPLAY_SCENT:
        case ACTION_DISPLAY_SCENT_TYPE:
        case ACTION_DISPLAY_TEMPERATURE:
        case ACTION_DISPLAY_VEHICLE_AI:
        case ACTION_DISPLAY_VISIBILITY:
        case ACTION_DISPLAY_LIGHTING:
        case ACTION_DISPLAY_RADIATION:
        case ACTION_DISPLAY_TRANSPARENCY:
        case ACTION_DISPLAY_SUBMAP_GRID:
        case ACTION_ZOOM_OUT:
        case ACTION_ZOOM_IN:
        case ACTION_TOGGLE_PIXEL_MINIMAP:
        case ACTION_TOGGLE_PANEL_ADM:
        case ACTION_PANEL_MGMT:
        case ACTION_RELOAD_TILESET:
        case ACTION_TIMEOUT:
        case ACTION_TOGGLE_AUTO_FEATURES:
        case ACTION_TOGGLE_AUTO_PULP_BUTCHER:
        case ACTION_TOGGLE_AUTO_MINING:
        case ACTION_TOGGLE_AUTO_FORAGING:
            return false;
        default:
            return true;
    }
}
References act, ACTION_AUTONOTES, ACTION_AUTOPICKUP, ACTION_CENTER, ACTION_COLOR, ACTION_DEBUG, ACTION_DISPLAY_LIGHTING, ACTION_DISPLAY_RADIATION, ACTION_DISPLAY_SCENT, ACTION_DISPLAY_SCENT_TYPE, ACTION_DISPLAY_SUBMAP_GRID, ACTION_DISPLAY_TEMPERATURE, ACTION_DISPLAY_TRANSPARENCY, ACTION_DISPLAY_VEHICLE_AI, ACTION_DISPLAY_VISIBILITY, ACTION_DISTRACTION_MANAGER, ACTION_FACTIONS, ACTION_HELP, ACTION_KEYBINDINGS, ACTION_LIST_ITEMS, ACTION_LOOK, ACTION_MAIN_MENU, ACTION_MAP, ACTION_MESSAGES, ACTION_MISSIONS, ACTION_MORALE, ACTION_OPTIONS, ACTION_PANEL_MGMT, ACTION_PL_INFO, ACTION_QUICKLOAD, ACTION_QUICKSAVE, ACTION_RELOAD_TILESET, ACTION_SAFEMODE, ACTION_SAVE, ACTION_SCORES, ACTION_SHIFT_E, ACTION_SHIFT_N, ACTION_SHIFT_NE, ACTION_SHIFT_NW, ACTION_SHIFT_S, ACTION_SHIFT_SE, ACTION_SHIFT_SW, ACTION_SHIFT_W, ACTION_SKY, ACTION_SUICIDE, ACTION_TIMEOUT, ACTION_TOGGLE_AUTO_FEATURES, ACTION_TOGGLE_AUTO_FORAGING, ACTION_TOGGLE_AUTO_MINING, ACTION_TOGGLE_AUTO_PULP_BUTCHER, ACTION_TOGGLE_FULLSCREEN, ACTION_TOGGLE_MAP_MEMORY, ACTION_TOGGLE_PANEL_ADM, ACTION_TOGGLE_PIXEL_MINIMAP, ACTION_WORLD_MODS, ACTION_ZONES, ACTION_ZOOM_IN, and ACTION_ZOOM_OUT.
Referenced by game::handle_action().
can_butcher_at()
bool can_butcher_at (const tripoint & p)
Test whether it is possible to perform butcher action.
Checks whether the butcher action makes sense at a given point. Checks for both corpses and items that can be disassembled.
This is part of a new API that will allow for a more robust user interface. See the note in can_interact_at()
Parameters
p Point to perform the test at
Returns
true if there is a corpse or item that can be disassembled at a point, otherwise false
Definition at line 547 of file action.cpp.
{
    avatar &you = get_avatar();
    // TODO: unify this with game::butcher
    const int factor = you.max_quality( qual_BUTCHER );
    const int factorD = you.max_quality( qual_CUT_FINE );
    map_stack items = get_map().i_at( p );
    bool has_item = false;
    bool has_corpse = false;
    const inventory &crafting_inv = you.crafting_inventory();
    for( item &items_it : items ) {
        if( items_it.is_corpse() ) {
            if( factor != INT_MIN  || factorD != INT_MIN ) {
                has_corpse = true;
            }
        } else if( crafting::can_disassemble( you, items_it, crafting_inv ).success() ) {
            has_item = true;
        }
    }
    return has_corpse || has_item;
}
References crafting::can_disassemble(), Character::crafting_inventory(), get_avatar(), get_map(), visitable< inventory >::has_item(), map::i_at(), inventory::items, visitable< T >::max_quality(), qual_BUTCHER, qual_CUT_FINE, and behavior::success.
Referenced by can_interact_at().
can_examine_at()
bool can_examine_at (const tripoint & p)
Test whether examine is possible.
Checks whether the examine action makes sense at a given point.
This is part of a new API that will allow for a more robust user interface. See the note in can_interact_at()
Parameters
p Point to perform the test at
Returns
true if the examine action is possible at this point, otherwise false
Definition at line 589 of file action.cpp.
{
    map &here = get_map();
    Character &u = get_player_character();
    if( here.veh_at( p ) ) {
        return true;
    }
    if( here.has_flag( flag_CONSOLE, p ) ) {
        return true;
    }
    if( here.has_items( p ) ) {
        return true;
    }
    const furn_t &xfurn_t = here.furn( p ).obj();
    const ter_t &xter_t = here.ter( p ).obj();
    if( here.has_furn( p ) && xfurn_t.examine != &iexamine::none ) {
        return true;
    } else if( xter_t.examine != &iexamine::none ) {
        return true;
    }
    Creature *c = g->critter_at( p );
    if( c != nullptr && p != u.pos() ) {
        return true;
    }
    return here.can_see_trap_at( p, u );
}
References c, map::can_see_trap_at(), map_data_common_t::examine, flag_CONSOLE(), map::furn(), g, get_map(), get_player_character(), map::has_flag(), map::has_furn(), map::has_items(), iexamine::none(), int_id< T >::obj(), Character::pos(), map::ter(), and map::veh_at().
Referenced by can_interact_at().
can_interact_at()
bool can_interact_at (action_id action, const tripoint & p)
Test whether it is possible to perform a given action.
Checks whether we can interact with something using the specified action and the given tile.
Note
: This is part of a new API that will allow for a more robust user interface. Possible features include: Extending the "select a nearby tile" widget to highlight tiles that can be interacted with, "suggest" context-sensitive actions to the user that are currently relevant.
Parameters
action The action ID to perform the test for
p Point to perform test at
Returns
true if movement is possible in the indicated direction
Definition at line 631 of file action.cpp.
{
    map &here = get_map();
    switch( action ) {
        case ACTION_OPEN:
            return here.open_door( p, !here.is_outside( g->u.pos() ), true );
        case ACTION_CLOSE: {
            const optional_vpart_position vp = here.veh_at( p );
            return ( vp &&
                     vp->vehicle().next_part_to_close( vp->part_index(),
                             veh_pointer_or_null( here.veh_at( g->u.pos() ) ) != &vp->vehicle() ) >= 0 ) ||
                   here.close_door( p, !here.is_outside( g->u.pos() ), true );
        }
        case ACTION_BUTCHER:
            return can_butcher_at( p );
        case ACTION_MOVE_UP:
            return can_move_vertical_at( p, 1 );
        case ACTION_MOVE_DOWN:
            return can_move_vertical_at( p, -1 );
        case ACTION_EXAMINE:
            return can_examine_at( p );
        case ACTION_PICKUP:
        case ACTION_PICKUP_FEET:
            return can_pickup_at( p );
        default:
            return false;
    }
}
References action, ACTION_BUTCHER, ACTION_CLOSE, ACTION_EXAMINE, ACTION_MOVE_DOWN, ACTION_MOVE_UP, ACTION_OPEN, ACTION_PICKUP, ACTION_PICKUP_FEET, can_butcher_at(), can_examine_at(), can_move_vertical_at(), can_pickup_at(), map::close_door(), g, get_map(), map::is_outside(), map::open_door(), map::veh_at(), and veh_pointer_or_null().
Referenced by choose_adjacent_highlight(), and handle_action_menu().
can_move_vertical_at()
bool can_move_vertical_at (const tripoint & p, int movez)
Test whether vertical movement is possible.
Checks whether it is possible to perform up or down movement actions at this location, defined as whether it is possible to swim up/down at this location, or if there is an up or down staircase at this location.
This is part of a new API that will allow for a more robust user interface. See the note in can_interact_at()
Parameters
p Point to perform test at
movez Direction to move. -1 for down, all other values for up
Returns
true if movement is possible in the indicated direction, otherwise false
Definition at line 570 of file action.cpp.
{
    map &here = get_map();
    // TODO: unify this with game::move_vertical
    if( here.has_flag( flag_SWIMMABLE, p ) && here.has_flag( TFLAG_DEEP_WATER, p ) ) {
        if( movez == -1 ) {
            return !g->u.is_underwater() && !g->u.worn_with_flag( flag_FLOTATION );
        } else {
            return g->u.swim_speed() < 500 || g->u.is_wearing( itype_id( "swim_fins" ) );
        }
    }
    if( movez == -1 ) {
        return here.has_flag( flag_GOES_DOWN, p );
    } else {
        return here.has_flag( flag_GOES_UP, p );
    }
}
References flag_FLOTATION(), flag_GOES_DOWN(), flag_GOES_UP(), flag_SWIMMABLE(), g, get_map(), map::has_flag(), and TFLAG_DEEP_WATER.
Referenced by can_interact_at().
can_pickup_at()
static bool can_pickup_at (const tripoint & p) static
Definition at line 619 of file action.cpp.
{
    bool veh_has_items = false;
    map &here = get_map();
    const optional_vpart_position vp = here.veh_at( p );
    if( vp ) {
        const int cargo_part = vp->vehicle().part_with_feature( vp->part_index(), "CARGO", false );
        veh_has_items = cargo_part >= 0 && !vp->vehicle().get_items( cargo_part ).empty();
    }
    return here.has_items( p ) || veh_has_items;
}
References get_map(), map::has_items(), optional_vpart_position::part_with_feature(), and map::veh_at().
Referenced by can_interact_at().
choose_adjacent()
cata::optional< tripoint > choose_adjacent (const std::string & message, bool allow_vertical = false)
Request player input of adjacent tile, possibly including vertical tiles.
Asks the player to input desired direction of an adjacent tile, for example when executing an examine or directional item drop. This version of the function supports selection of tiles above and below the player if an appropriate flag is set.
Parameters
[in] message Message used in assembling the prompt to the player
[in] allow_vertical Allows player to select tiles above/below them if true
Definition at line 1026 of file action.cpp.
{
    const cata::optional<tripoint> dir = choose_direction( message, allow_vertical );
    if( !dir ) {
        return cata::nullopt;
    }
    if( get_map().obstructed_by_vehicle_rotation( g->u.pos(), *dir + g->u.pos() ) ) {
        add_msg( _( "You can't reach through that vehicle's wall." ) );
        return cata::nullopt;
    }
    return *dir + g->u.pos();
}
References _, add_msg(), choose_direction(), g, get_map(), mapgen_defer::message, and cata::nullopt.
Referenced by Character::activate_bionic(), iuse::burrow(), iuse::cable_attach(), iuse::capture_monster_act(), choose_adjacent_highlight(), game::control_vehicle(), iuse::directional_hologram(), Character::dismount(), game::drop_in_direction(), iuse::extinguisher(), iuse::fish_trap(), liquid_handler::get_liquid_target(), grab(), iuse::jackhammer(), iuse::ladder(), iuse::makemound(), petfood(), iuse::pickaxe(), place_construction(), firestarter_actor::prep_firestarter_use(), smash(), iuse::spray_can(), iuse::tazer(), iuse::tow_attach(), place_monster_iuse::use(), place_npc_iuse::use(), deploy_furn_actor::use(), inscribe_actor::use(), and place_trap_actor::use().
choose_adjacent_highlight() [1/2]
cata::optional< tripoint > choose_adjacent_highlight (const std::string & message, const std::string & failure_message, action_id action, bool allow_vertical = false)
Request player input of adjacent tile with highlighting, possibly on different z-level.
Asks the player to input desired direction of an adjacent tile, for example when executing an examine or directional item drop. This version of the function allows the player to select a tile above or below.
This function is identical to choose_adjacent except that squares are highlighted for the player to indicate valid squares for a given action_id
Parameters
[in] message Message used in assembling the prompt to the player
[in] failure_message Message used if there is no vaild adjacent tile
[in] action An action ID to drive the highlighting output
[in] allow_vertical Allows direction vector to have vertical component if true
Definition at line 1042 of file action.cpp.
{
    const std::function<bool( const tripoint & )> f = [&action]( const tripoint & p ) {
        return can_interact_at( action, p );
    };
    return choose_adjacent_highlight( message, failure_message, f, allow_vertical );
}
References action, can_interact_at(), choose_adjacent_highlight(), and mapgen_defer::message.
Referenced by iuse::boltcutters(), iuse::capture_monster_act(), choose_adjacent_highlight(), iuse::chop_logs(), iuse::chop_tree(), iuse::clear_rubble(), close(), iuse::crowbar(), iuse::dig(), iuse::dig_channel(), game::examine(), iuse::fill_pit(), iuse::geiger(), iuse::hacksaw(), iuse::hammer(), iuse::mop(), open(), iuse::oxytorch(), game::pickup(), iuse::siphon(), pick_lock_actor::use(), and vehicle::use_harness().
choose_adjacent_highlight() [2/2]
cata::optional< tripoint > choose_adjacent_highlight (const std::string & message, const std::string & failure_message, const std::function< bool(const tripoint &)> & allowed, bool allow_vertical = false)
Request player input of adjacent tile with highlighting, possibly on different z-level.
Asks the player to input desired direction of an adjacent tile, for example when executing an examine or directional item drop. This version of the function allows the player to select a tile above or below.
This function is identical to choose_adjacent except that squares are highlighted for the player to indicate valid squares, based on the result of the provided should_highlight function.
Parameters
[in] message Message used in assembling the prompt to the player
[in] failure_message Message used if there is no vaild adjacent tile
[in] allowed A function that will be called to determine if a given location is allowed for selection
[in] allow_vertical Allows direction vector to have vertical component if true
Definition at line 1051 of file action.cpp.
{
    std::vector<tripoint> valid;
    map &here = get_map();
    if( allowed ) {
        for( const tripoint &pos : here.points_in_radius( g->u.pos(), 1 ) ) {
            if( !here.obstructed_by_vehicle_rotation( g->u.pos(), pos ) && allowed( pos ) ) {
                valid.emplace_back( pos );
            }
        }
    }
    const bool auto_select = get_option<bool>( "AUTOSELECT_SINGLE_VALID_TARGET" );
    if( valid.empty() && auto_select ) {
        add_msg( failure_message );
        return cata::nullopt;
    } else if( valid.size() == 1 && auto_select ) {
        return valid.back();
    }
    shared_ptr_fast<game::draw_callback_t> hilite_cb;
    if( !valid.empty() ) {
        hilite_cb = make_shared_fast<game::draw_callback_t>( [&]() {
            for( const tripoint &pos : valid ) {
                here.drawsq( g->w_terrain, pos, drawsq_params().highlight( true ) );
            }
        } );
        g->add_draw_callback( hilite_cb );
    }
    return choose_adjacent( message, allow_vertical );
}
References add_msg(), choose_adjacent(), map::drawsq(), g, get_map(), mapgen_defer::message, cata::nullopt, map::obstructed_by_vehicle_rotation(), and map::points_in_radius().
choose_direction()
cata::optional< tripoint > choose_direction (const std::string & message, bool allow_vertical = false)
Request player input of a direction, possibly including vertical component.
Asks the player to input a desired direction. This differs from choose_adjacent in that the selected direction is returned as an offset to the player's current position rather than coordinate of a tile. This version of the function allows selection of the tile above and below the player if the appropriate flag is set.
Parameters
[in] message Message used in assembling the prompt to the player
[in] allow_vertical Allows direction vector to have vertical component if true
Definition at line 984 of file action.cpp.
{
    input_context ctxt( "DEFAULTMODE" );
    ctxt.set_iso( true );
    ctxt.register_directions();
    ctxt.register_action( "pause" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    if( allow_vertical ) {
        ctxt.register_action( "LEVEL_UP" );
        ctxt.register_action( "LEVEL_DOWN" );
    }
    static_popup popup;
    //~ %s: "Close where?" "Pry where?" etc.
    popup.message( _( "%s (Direction button)" ), message ).on_top( true );
    std::string action;
    do {
        ui_manager::redraw();
        action = ctxt.handle_input();
        if( const cata::optional<tripoint> vec = ctxt.get_direction( action ) ) {
            // Make player's sprite face left/right if interacting with something to the left or right
            if( vec->x > 0 ) {
                g->u.facing = FD_RIGHT;
            } else if( vec->x < 0 ) {
                g->u.facing = FD_LEFT;
            }
            return vec;
        } else if( action == "pause" ) {
            return tripoint_zero;
        } else if( action == "LEVEL_UP" ) {
            return tripoint_above;
        } else if( action == "LEVEL_DOWN" ) {
            return tripoint_below;
        }
    } while( action != "QUIT" );
    add_msg( _( "Never mind." ) );
    return cata::nullopt;
}
References _, action, add_msg(), FD_LEFT, FD_RIGHT, g, input_context::get_direction(), input_context::handle_input(), mapgen_defer::message, cata::nullopt, popup(), ui_manager::redraw(), input_context::register_action(), input_context::register_directions(), input_context::set_iso(), tripoint_above, tripoint_below, and tripoint_zero.
Referenced by choose_adjacent(), activity_handlers::chop_tree_finish(), game::peek(), smash(), debug_menu::teleport_overmap(), and deploy_tent_actor::use().
flag_CONSOLE()
static const std::string flag_CONSOLE ("CONSOLE") static
Referenced by can_examine_at().
flag_FLOTATION()
static const std::string flag_FLOTATION ("FLOTATION") static
Referenced by can_move_vertical_at().
flag_GOES_DOWN()
static const std::string flag_GOES_DOWN ("GOES_DOWN") static
Referenced by can_move_vertical_at().
flag_GOES_UP()
static const std::string flag_GOES_UP ("GOES_UP") static
Referenced by can_move_vertical_at().
flag_REACH_ATTACK()
static const std::string flag_REACH_ATTACK ("REACH_ATTACK") static
Referenced by handle_action_menu().
flag_SWIMMABLE()
static const std::string flag_SWIMMABLE ("SWIMMABLE") static
Referenced by can_move_vertical_at().
get_delta_from_movement_action()
point get_delta_from_movement_action (const action_id act, const iso_rotate rot)
Definition at line 512 of file action.cpp.
{
    const bool iso_mode = rot == iso_rotate::yes && use_tiles && tile_iso;
    switch( act ) {
        case ACTION_MOVE_FORTH:
            return iso_mode ? point_north_east : point_north;
        case ACTION_MOVE_FORTH_RIGHT:
            return iso_mode ? point_east : point_north_east;
        case ACTION_MOVE_RIGHT:
            return iso_mode ? point_south_east : point_east;
        case ACTION_MOVE_BACK_RIGHT:
            return iso_mode ? point_south : point_south_east;
        case ACTION_MOVE_BACK:
            return iso_mode ? point_south_west : point_south;
        case ACTION_MOVE_BACK_LEFT:
            return iso_mode ? point_west : point_south_west;
        case ACTION_MOVE_LEFT:
            return iso_mode ? point_north_west : point_west;
        case ACTION_MOVE_FORTH_LEFT:
            return iso_mode ? point_north : point_north_west;
        default:
            return point_zero;
    }
}
References act, ACTION_MOVE_BACK, ACTION_MOVE_BACK_LEFT, ACTION_MOVE_BACK_RIGHT, ACTION_MOVE_FORTH, ACTION_MOVE_FORTH_LEFT, ACTION_MOVE_FORTH_RIGHT, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, point_zero, tile_iso, use_tiles, and yes.
Referenced by game::handle_action(), and defense_game::pre_action().
get_movement_action_from_delta()
action_id get_movement_action_from_delta (const tripoint & d, iso_rotate rot)
Translate coordinate delta into movement action.
For a given coordinate delta, this function returns the associated user movement action that would generated that delta. See action_id for the list of available movement commands that may be generated. This function takes iso mode into account.
The only valid values for the coordinates of d are -1, 0 and 1
Note
: This function does not sanitize its inputs, which can result in some strange behavior:
If d.z is valid and non-zero, then d.x and d.y are ignored.
If d.z is invalid, it is treated as if it were zero.
If d.z is 0 or invalid, then any invalid d.x or d.y results in ACTION_MOVE_FORTH_LEFT
If d.z is 0 or invalid, then a d.x == d.y == 0 results in ACTION_MOVE_FORTH_LEFT
Parameters
[in] d coordinate delta, each coordinate should be -1, 0, or 1
Returns
ID of corresponding move action (usually... see note above)
Definition at line 484 of file action.cpp.
{
    if( d.z == -1 ) {
        return ACTION_MOVE_DOWN;
    } else if( d.z == 1 ) {
        return ACTION_MOVE_UP;
    }
    const bool iso_mode = rot == iso_rotate::yes && use_tiles && tile_iso;
    if( d.xy() == point_north ) {
        return iso_mode ? ACTION_MOVE_FORTH_LEFT : ACTION_MOVE_FORTH;
    } else if( d.xy() == point_north_east ) {
        return iso_mode ? ACTION_MOVE_FORTH : ACTION_MOVE_FORTH_RIGHT;
    } else if( d.xy() == point_east ) {
        return iso_mode ? ACTION_MOVE_FORTH_RIGHT : ACTION_MOVE_RIGHT;
    } else if( d.xy() == point_south_east ) {
        return iso_mode ? ACTION_MOVE_RIGHT : ACTION_MOVE_BACK_RIGHT;
    } else if( d.xy() == point_south ) {
        return iso_mode ? ACTION_MOVE_BACK_RIGHT : ACTION_MOVE_BACK;
    } else if( d.xy() == point_south_west ) {
        return iso_mode ? ACTION_MOVE_BACK : ACTION_MOVE_BACK_LEFT;
    } else if( d.xy() == point_west ) {
        return iso_mode ? ACTION_MOVE_BACK_LEFT : ACTION_MOVE_LEFT;
    } else {
        return iso_mode ? ACTION_MOVE_LEFT : ACTION_MOVE_FORTH_LEFT;
    }
}
References ACTION_MOVE_BACK, ACTION_MOVE_BACK_LEFT, ACTION_MOVE_BACK_RIGHT, ACTION_MOVE_DOWN, ACTION_MOVE_FORTH, ACTION_MOVE_FORTH_LEFT, ACTION_MOVE_FORTH_RIGHT, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, point_east, point_north, point_north_east, point_south, point_south_east, point_south_west, point_west, tile_iso, use_tiles, tripoint::xy(), yes, and tripoint::z.
Referenced by Character::get_next_auto_move_direction().
handle_action_menu()
action_id handle_action_menu ()
Show the action menu.
Prompts the user with the action menu, and returns any action requested by user input at that menu.
Returns
action_id ID of action requested by user at menu.
Definition at line 660 of file action.cpp.
{
    const input_context ctxt = get_default_mode_input_context();
    std::string catgname;
#define REGISTER_ACTION(name) entries.emplace_back(name, true, hotkey_for_action(name), \
        ctxt.get_action_name( action_ident( name ) ) );
#define REGISTER_CATEGORY(name)  categories_by_int[last_category] = name; \
    catgname = name; \
    catgname += "…"; \
    entries.emplace_back( last_category, true, -1, catgname ); \
    last_category++;
    // Calculate weightings for the various actions to give the player suggestions
    // Weight >= 200: Special action only available right now
    std::map<action_id, int> action_weightings;
    // Check if we're in a potential combat situation, if so, sort a few actions to the top.
    if( !g->u.get_hostile_creatures( 60 ).empty() ) {
        // Only prioritize movement options if we're not driving.
        if( !g->u.controlling_vehicle ) {
            action_weightings[ACTION_CYCLE_MOVE] = 400;
        }
        // Only prioritize fire weapon options if we're wielding a ranged weapon.
        if( g->u.weapon.is_gun() || g->u.weapon.has_flag( flag_REACH_ATTACK ) ) {
            action_weightings[ACTION_FIRE] = 350;
        }
    }
    // If we're already running, make it simple to toggle running to off.
    if( g->u.movement_mode_is( CMM_RUN ) ) {
        action_weightings[ACTION_TOGGLE_RUN] = 300;
    }
    // If we're already crouching, make it simple to toggle crouching to off.
    if( g->u.movement_mode_is( CMM_CROUCH ) ) {
        action_weightings[ACTION_TOGGLE_CROUCH] = 300;
    }
    map &here = get_map();
    // Check if we're on a vehicle, if so, vehicle controls should be top.
    if( here.veh_at( g->u.pos() ) ) {
        // Make it 300 to prioritize it before examining the vehicle.
        action_weightings[ACTION_CONTROL_VEHICLE] = 300;
    }
    // Check if we can perform one of our actions on nearby terrain. If so,
    // display that action at the top of the list.
    for( const tripoint &pos : here.points_in_radius( g->u.pos(), 1 ) ) {
        if( pos != g->u.pos() ) {
            // Check for actions that work on nearby tiles, skipping tiles blocked by vehicles
            if( here.obstructed_by_vehicle_rotation( g->u.pos(), pos ) ) {
                continue;
            }
            if( can_interact_at( ACTION_OPEN, pos ) ) {
                action_weightings[ACTION_OPEN] = 200;
            }
            if( can_interact_at( ACTION_CLOSE, pos ) ) {
                action_weightings[ACTION_CLOSE] = 200;
            }
            if( can_interact_at( ACTION_EXAMINE, pos ) ) {
                action_weightings[ACTION_EXAMINE] = 200;
            }
        } else {
            // Check for actions that work on own tile only
            if( can_interact_at( ACTION_BUTCHER, pos ) ) {
                action_weightings[ACTION_BUTCHER] = 200;
            }
            if( can_interact_at( ACTION_MOVE_UP, pos ) ) {
                action_weightings[ACTION_MOVE_UP] = 200;
            }
            if( can_interact_at( ACTION_MOVE_DOWN, pos ) ) {
                action_weightings[ACTION_MOVE_DOWN] = 200;
            }
        }
    }
    // sort the map by its weightings
    std::vector<std::pair<action_id, int> > sorted_pairs;
    std::copy( action_weightings.begin(), action_weightings.end(),
               std::back_inserter<std::vector<std::pair<action_id, int> > >( sorted_pairs ) );
    std::reverse( sorted_pairs.begin(), sorted_pairs.end() );
    // Default category is called "back"
    std::string category = "back";
    while( true ) {
        std::vector<uilist_entry> entries;
        uilist_entry *entry;
        std::map<int, std::string> categories_by_int;
        int last_category = NUM_ACTIONS + 1;
        if( category == "back" ) {
            std::vector<std::pair<action_id, int> >::iterator it;
            for( it = sorted_pairs.begin(); it != sorted_pairs.end(); ++it ) {
                if( it->second >= 200 ) {
                    REGISTER_ACTION( it->first );
                }
            }
            REGISTER_CATEGORY( _( "Look" ) );
            REGISTER_CATEGORY( _( "Interact" ) );
            REGISTER_CATEGORY( _( "Inventory" ) );
            REGISTER_CATEGORY( _( "Combat" ) );
            REGISTER_CATEGORY( _( "Craft" ) );
            REGISTER_CATEGORY( _( "Info" ) );
            REGISTER_CATEGORY( _( "Misc" ) );
            if( hotkey_for_action( ACTION_QUICKSAVE ) > -1 ) {
                REGISTER_ACTION( ACTION_QUICKSAVE );
            }
            REGISTER_ACTION( ACTION_SAVE );
            if( hotkey_for_action( ACTION_QUICKLOAD ) > -1 ) {
                REGISTER_ACTION( ACTION_QUICKLOAD );
            }
            if( hotkey_for_action( ACTION_SUICIDE ) > -1 ) {
                REGISTER_ACTION( ACTION_SUICIDE );
            }
            REGISTER_ACTION( ACTION_HELP );
            if( ( entry = &entries.back() ) ) {
                // help _is_a menu.
                entry->txt += "…";
            }
            if( hotkey_for_action( ACTION_DEBUG ) > -1 ) {
                // register with global key
                REGISTER_CATEGORY( _( "Debug" ) );
                if( ( entry = &entries.back() ) ) {
                    entry->hotkey = hotkey_for_action( ACTION_DEBUG );
                }
            }
        } else if( category == _( "Look" ) ) {
            REGISTER_ACTION( ACTION_LOOK );
            REGISTER_ACTION( ACTION_PEEK );
            REGISTER_ACTION( ACTION_LIST_ITEMS );
            REGISTER_ACTION( ACTION_ZONES );
            REGISTER_ACTION( ACTION_MAP );
            REGISTER_ACTION( ACTION_SKY );
        } else if( category == _( "Inventory" ) ) {
            REGISTER_ACTION( ACTION_INVENTORY );
            REGISTER_ACTION( ACTION_ADVANCEDINV );
            REGISTER_ACTION( ACTION_SORT_ARMOR );
            REGISTER_ACTION( ACTION_DIR_DROP );
            // Everything below here can be accessed through
            // the inventory screen, so it's sorted to the
            // end of the list.
            REGISTER_ACTION( ACTION_DROP );
            REGISTER_ACTION( ACTION_COMPARE );
            REGISTER_ACTION( ACTION_ORGANIZE );
            REGISTER_ACTION( ACTION_USE );
            REGISTER_ACTION( ACTION_WEAR );
            REGISTER_ACTION( ACTION_TAKE_OFF );
            REGISTER_ACTION( ACTION_EAT );
            REGISTER_ACTION( ACTION_OPEN_CONSUME );
            REGISTER_ACTION( ACTION_READ );
            REGISTER_ACTION( ACTION_WIELD );
            REGISTER_ACTION( ACTION_UNLOAD );
        } else if( category == _( "Debug" ) ) {
            REGISTER_ACTION( ACTION_DEBUG );
            if( ( entry = &entries.back() ) ) {
                // debug _is_a menu.
                entry->txt += "…";
            }
#if !defined(TILES)
            REGISTER_ACTION( ACTION_TOGGLE_FULLSCREEN );
#endif
#if defined(TILES)
            REGISTER_ACTION( ACTION_TOGGLE_PIXEL_MINIMAP );
            REGISTER_ACTION( ACTION_RELOAD_TILESET );
#endif // TILES
            REGISTER_ACTION( ACTION_TOGGLE_PANEL_ADM );
            REGISTER_ACTION( ACTION_DISPLAY_SCENT );
            REGISTER_ACTION( ACTION_DISPLAY_SCENT_TYPE );
            REGISTER_ACTION( ACTION_DISPLAY_TEMPERATURE );
            REGISTER_ACTION( ACTION_DISPLAY_VEHICLE_AI );
            REGISTER_ACTION( ACTION_DISPLAY_VISIBILITY );
            REGISTER_ACTION( ACTION_DISPLAY_LIGHTING );
            REGISTER_ACTION( ACTION_DISPLAY_TRANSPARENCY );
            REGISTER_ACTION( ACTION_DISPLAY_RADIATION );
            REGISTER_ACTION( ACTION_DISPLAY_SUBMAP_GRID );
            REGISTER_ACTION( ACTION_TOGGLE_DEBUG_MODE );
        } else if( category == _( "Interact" ) ) {
            REGISTER_ACTION( ACTION_EXAMINE );
            REGISTER_ACTION( ACTION_SMASH );
            REGISTER_ACTION( ACTION_MOVE_DOWN );
            REGISTER_ACTION( ACTION_MOVE_UP );
            REGISTER_ACTION( ACTION_OPEN );
            REGISTER_ACTION( ACTION_CLOSE );
            REGISTER_ACTION( ACTION_CHAT );
            REGISTER_ACTION( ACTION_PICKUP );
            REGISTER_ACTION( ACTION_PICKUP_FEET );
            REGISTER_ACTION( ACTION_GRAB );
            REGISTER_ACTION( ACTION_HAUL );
            REGISTER_ACTION( ACTION_BUTCHER );
            REGISTER_ACTION( ACTION_LOOT );
        } else if( category == _( "Combat" ) ) {
            REGISTER_ACTION( ACTION_CYCLE_MOVE );
            REGISTER_ACTION( ACTION_RESET_MOVE );
            REGISTER_ACTION( ACTION_TOGGLE_RUN );
            REGISTER_ACTION( ACTION_TOGGLE_CROUCH );
            REGISTER_ACTION( ACTION_OPEN_MOVEMENT );
            REGISTER_ACTION( ACTION_FIRE );
            REGISTER_ACTION( ACTION_RELOAD_ITEM );
            REGISTER_ACTION( ACTION_RELOAD_WEAPON );
            REGISTER_ACTION( ACTION_RELOAD_WIELDED );
            REGISTER_ACTION( ACTION_CAST_SPELL );
            REGISTER_ACTION( ACTION_SELECT_FIRE_MODE );
            REGISTER_ACTION( ACTION_SELECT_DEFAULT_AMMO );
            REGISTER_ACTION( ACTION_THROW );
            REGISTER_ACTION( ACTION_FIRE_BURST );
            REGISTER_ACTION( ACTION_PICK_STYLE );
            REGISTER_ACTION( ACTION_TOGGLE_AUTO_TRAVEL_MODE );
            REGISTER_ACTION( ACTION_TOGGLE_SAFEMODE );
            REGISTER_ACTION( ACTION_TOGGLE_AUTOSAFE );
            REGISTER_ACTION( ACTION_IGNORE_ENEMY );
            REGISTER_ACTION( ACTION_TOGGLE_AUTO_FEATURES );
            REGISTER_ACTION( ACTION_TOGGLE_AUTO_PULP_BUTCHER );
            REGISTER_ACTION( ACTION_TOGGLE_AUTO_MINING );
            REGISTER_ACTION( ACTION_TOGGLE_AUTO_FORAGING );
        } else if( category == _( "Craft" ) ) {
            REGISTER_ACTION( ACTION_CRAFT );
            REGISTER_ACTION( ACTION_RECRAFT );
            REGISTER_ACTION( ACTION_LONGCRAFT );
            REGISTER_ACTION( ACTION_CONSTRUCT );
            REGISTER_ACTION( ACTION_DISASSEMBLE );
        } else if( category == _( "Info" ) ) {
            REGISTER_ACTION( ACTION_PL_INFO );
            REGISTER_ACTION( ACTION_MISSIONS );
            REGISTER_ACTION( ACTION_SCORES );
            REGISTER_ACTION( ACTION_FACTIONS );
            REGISTER_ACTION( ACTION_MORALE );
            REGISTER_ACTION( ACTION_MESSAGES );
            REGISTER_ACTION( ACTION_DIARY );
        } else if( category == _( "Misc" ) ) {
            REGISTER_ACTION( ACTION_WAIT );
            REGISTER_ACTION( ACTION_SLEEP );
            REGISTER_ACTION( ACTION_BIONICS );
            REGISTER_ACTION( ACTION_MUTATIONS );
            REGISTER_ACTION( ACTION_CONTROL_VEHICLE );
            REGISTER_ACTION( ACTION_ITEMACTION );
            REGISTER_ACTION( ACTION_TOGGLE_THIEF_MODE );
#if defined(TILES)
            if( use_tiles ) {
                REGISTER_ACTION( ACTION_ZOOM_OUT );
                REGISTER_ACTION( ACTION_ZOOM_IN );
            }
#endif
        }
        if( category != "back" ) {
            std::string msg = _( "Back" );
            msg += "…";
            entries.emplace_back( 2 * NUM_ACTIONS, true,
                                  hotkey_for_action( ACTION_ACTIONMENU ), msg );
        }
        std::string title = _( "Actions" );
        if( category != "back" ) {
            catgname = category;
            capitalize_letter( catgname, 0 );
            title += ": " + catgname;
        }
        uilist smenu;
        smenu.settext( title );
        smenu.entries = entries;
        smenu.query();
        const int selection = smenu.ret;
        if( selection < 0 || selection == NUM_ACTIONS ) {
            return ACTION_NULL;
        } else if( selection == 2 * NUM_ACTIONS ) {
            if( category != "back" ) {
                category = "back";
            } else {
                return ACTION_NULL;
            }
        } else if( selection > NUM_ACTIONS ) {
            category = categories_by_int[selection];
        } else {
            return static_cast<action_id>( selection );
        }
    }
#undef REGISTER_ACTION
#undef REGISTER_CATEGORY
}
References _, ACTION_ACTIONMENU, ACTION_ADVANCEDINV, ACTION_BIONICS, ACTION_BUTCHER, ACTION_CAST_SPELL, ACTION_CHAT, ACTION_CLOSE, ACTION_COMPARE, ACTION_CONSTRUCT, ACTION_CONTROL_VEHICLE, ACTION_CRAFT, ACTION_CYCLE_MOVE, ACTION_DEBUG, ACTION_DIARY, ACTION_DIR_DROP, ACTION_DISASSEMBLE, ACTION_DISPLAY_LIGHTING, ACTION_DISPLAY_RADIATION, ACTION_DISPLAY_SCENT, ACTION_DISPLAY_SCENT_TYPE, ACTION_DISPLAY_SUBMAP_GRID, ACTION_DISPLAY_TEMPERATURE, ACTION_DISPLAY_TRANSPARENCY, ACTION_DISPLAY_VEHICLE_AI, ACTION_DISPLAY_VISIBILITY, ACTION_DROP, ACTION_EAT, ACTION_EXAMINE, ACTION_FACTIONS, ACTION_FIRE, ACTION_FIRE_BURST, ACTION_GRAB, ACTION_HAUL, ACTION_HELP, ACTION_IGNORE_ENEMY, ACTION_INVENTORY, ACTION_ITEMACTION, ACTION_LIST_ITEMS, ACTION_LONGCRAFT, ACTION_LOOK, ACTION_LOOT, ACTION_MAP, ACTION_MESSAGES, ACTION_MISSIONS, ACTION_MORALE, ACTION_MOVE_DOWN, ACTION_MOVE_UP, ACTION_MUTATIONS, ACTION_NULL, ACTION_OPEN, ACTION_OPEN_CONSUME, ACTION_OPEN_MOVEMENT, ACTION_ORGANIZE, ACTION_PEEK, ACTION_PICK_STYLE, ACTION_PICKUP, ACTION_PICKUP_FEET, ACTION_PL_INFO, ACTION_QUICKLOAD, ACTION_QUICKSAVE, ACTION_READ, ACTION_RECRAFT, ACTION_RELOAD_ITEM, ACTION_RELOAD_TILESET, ACTION_RELOAD_WEAPON, ACTION_RELOAD_WIELDED, ACTION_RESET_MOVE, ACTION_SAVE, ACTION_SCORES, ACTION_SELECT_DEFAULT_AMMO, ACTION_SELECT_FIRE_MODE, ACTION_SKY, ACTION_SLEEP, ACTION_SMASH, ACTION_SORT_ARMOR, ACTION_SUICIDE, ACTION_TAKE_OFF, ACTION_THROW, ACTION_TOGGLE_AUTO_FEATURES, ACTION_TOGGLE_AUTO_FORAGING, ACTION_TOGGLE_AUTO_MINING, ACTION_TOGGLE_AUTO_PULP_BUTCHER, ACTION_TOGGLE_AUTO_TRAVEL_MODE, ACTION_TOGGLE_AUTOSAFE, ACTION_TOGGLE_CROUCH, ACTION_TOGGLE_DEBUG_MODE, ACTION_TOGGLE_FULLSCREEN, ACTION_TOGGLE_PANEL_ADM, ACTION_TOGGLE_PIXEL_MINIMAP, ACTION_TOGGLE_RUN, ACTION_TOGGLE_SAFEMODE, ACTION_TOGGLE_THIEF_MODE, ACTION_UNLOAD, ACTION_USE, ACTION_WAIT, ACTION_WEAR, ACTION_WIELD, ACTION_ZONES, ACTION_ZOOM_IN, ACTION_ZOOM_OUT, can_interact_at(), capitalize_letter(), CMM_CROUCH, CMM_RUN, uilist::entries, flag_REACH_ATTACK(), g, get_default_mode_input_context(), get_map(), uilist_entry::hotkey, hotkey_for_action(), NUM_ACTIONS, map::obstructed_by_vehicle_rotation(), map::points_in_radius(), uilist::query(), REGISTER_ACTION, REGISTER_CATEGORY, uilist::ret, uilist::settext(), PATH_INFO::title(), uilist_entry::txt, use_tiles, and map::veh_at().
Referenced by game::handle_action().
handle_main_menu()
action_id handle_main_menu ()
Show in-game main menu.
Prompts the user with the main game menu, and returns any action requested by user input at that menu.
Returns
action_id ID of action requested by user at menu.
Definition at line 947 of file action.cpp.
{
    const input_context ctxt = get_default_mode_input_context();
    std::vector<uilist_entry> entries;
    const auto REGISTER_ACTION = [&]( action_id name ) {
        entries.emplace_back( name, true, hotkey_for_action( name ),
                              ctxt.get_action_name( action_ident( name ) ) );
    };
    REGISTER_ACTION( ACTION_HELP );
    REGISTER_ACTION( ACTION_KEYBINDINGS );
    REGISTER_ACTION( ACTION_OPTIONS );
    REGISTER_ACTION( ACTION_AUTOPICKUP );
    REGISTER_ACTION( ACTION_AUTONOTES );
    REGISTER_ACTION( ACTION_SAFEMODE );
    REGISTER_ACTION( ACTION_DISTRACTION_MANAGER );
    REGISTER_ACTION( ACTION_COLOR );
    REGISTER_ACTION( ACTION_WORLD_MODS );
    REGISTER_ACTION( ACTION_ACTIONMENU );
    REGISTER_ACTION( ACTION_QUICKSAVE );
    REGISTER_ACTION( ACTION_SAVE );
    REGISTER_ACTION( ACTION_DEBUG );
    uilist smenu;
    smenu.settext( _( "MAIN MENU" ) );
    smenu.entries = entries;
    smenu.query();
    int selection = smenu.ret;
    if( selection < 0 || selection >= NUM_ACTIONS ) {
        return ACTION_NULL;
    } else {
        return static_cast<action_id>( selection );
    }
}
References _, ACTION_ACTIONMENU, ACTION_AUTONOTES, ACTION_AUTOPICKUP, ACTION_COLOR, ACTION_DEBUG, ACTION_DISTRACTION_MANAGER, ACTION_HELP, action_ident(), ACTION_KEYBINDINGS, ACTION_NULL, ACTION_OPTIONS, ACTION_QUICKSAVE, ACTION_SAFEMODE, ACTION_SAVE, ACTION_WORLD_MODS, uilist::entries, input_context::get_action_name(), get_default_mode_input_context(), hotkey_for_action(), om_direction::name(), NUM_ACTIONS, uilist::query(), REGISTER_ACTION, uilist::ret, and uilist::settext().
Referenced by game::handle_action().
hotkey_for_action()
int hotkey_for_action (action_id action, bool restrict_to_printable = true)
Get the key for an action, used in the action menu to give each action the hotkey it is bound to.
Parameters
action Action ID to lookup in keymap.
restrict_to_printable If true the function returns the bound key only if it is printable. If false, any key (whether they it is printable or not) is returned.
Returns
the key code for the hotkey or -1 if no key is associated with the given action.
Note
We ignore bindings to '?' because that will already do something else in this menu (open the menu keybindings).
Definition at line 537 of file action.cpp.
{
    auto is_valid_key = []( char key ) {
        return key != '?';
    };
    std::vector<char> keys = keys_bound_to( action, restrict_to_printable );
    auto valid = std::find_if( keys.begin(), keys.end(), is_valid_key );
    return valid == keys.end() ? -1 : *valid;
}
References action, and keys_bound_to().
Referenced by debug_menu::debug(), get_initial_hotkey(), handle_action_menu(), and handle_main_menu().
keys_bound_to()
std::vector< char > keys_bound_to (action_id act, bool restrict_to_printable = true)
Get list of keys bound to an action ID.
Returns a vector of all keys currently bound to the given action. If not keys are bound to the given action then the returned vector is simply left empty.
Parameters
act Action ID to lookup in keymap
restrict_to_printable If true the function returns the bound keys only if they are printable. If false, all keys (whether they are printable or not) are returned.
Returns
all keys (as characters) currently bound to a give action ID
Definition at line 54 of file action.cpp.
{
    input_context ctxt = get_default_mode_input_context();
    return ctxt.keys_bound_to( action_ident( act ), restrict_to_printable );
}
References act, action_ident(), get_default_mode_input_context(), and input_context::keys_bound_to().
Referenced by help::get_dir_grid(), and hotkey_for_action().
look_up_action()
action_id look_up_action (const std::string & ident)
Lookup an action ID by its unique string identifier.
Translates a unique string identifier into an action_id. This identifier is generally the value used in a keymap configuration file. If no corresponding action_id is found for this identifier then ACTION_NULL is returned instead.
Parameters
ident Unique string identifier corresponding to an action_id
Returns
Corresponding action_id for the supplied string identifier
Definition at line 423 of file action.cpp.
{
    // Temporarily for the interface with the input manager!
    if( ident == "move_nw" ) {
        return ACTION_MOVE_FORTH_LEFT;
    } else if( ident == "move_sw" ) {
        return ACTION_MOVE_BACK_LEFT;
    } else if( ident == "move_ne" ) {
        return ACTION_MOVE_FORTH_RIGHT;
    } else if( ident == "move_se" ) {
        return ACTION_MOVE_BACK_RIGHT;
    } else if( ident == "move_n" ) {
        return ACTION_MOVE_FORTH;
    } else if( ident == "move_s" ) {
        return ACTION_MOVE_BACK;
    } else if( ident == "move_w" ) {
        return ACTION_MOVE_LEFT;
    } else if( ident == "move_e" ) {
        return ACTION_MOVE_RIGHT;
    } else if( ident == "move_down" ) {
        return ACTION_MOVE_DOWN;
    } else if( ident == "move_up" ) {
        return ACTION_MOVE_UP;
    }
    // ^^ Temporarily for the interface with the input manager!
    for( int i = 0; i < NUM_ACTIONS; i++ ) {
        if( action_ident( static_cast<action_id>( i ) ) == ident ) {
            return static_cast<action_id>( i );
        }
    }
    return ACTION_NULL;
}
References action_ident(), ACTION_MOVE_BACK, ACTION_MOVE_BACK_LEFT, ACTION_MOVE_BACK_RIGHT, ACTION_MOVE_DOWN, ACTION_MOVE_FORTH, ACTION_MOVE_FORTH_LEFT, ACTION_MOVE_FORTH_RIGHT, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NULL, and NUM_ACTIONS.
Referenced by action_from_key(), input_context::display_menu(), and game::handle_action().
press_x() [1/3]
std::string press_x (action_id act)
Definition at line 457 of file action.cpp.
{
    input_context ctxt = get_default_mode_input_context();
    return ctxt.press_x( action_ident( act ), _( "Press " ), "", _( "Try" ) );
}
References _, act, action_ident(), get_default_mode_input_context(), and input_context::press_x().
Referenced by game::check_safe_mode_allowed(), draw_hint(), game::handle_action(), character_martial_arts::learn_style(), avatar_funcs::mend_item(), avatar_action::move(), game::place_player(), press_x_if_bound(), avatar::read(), avatar_action::swim(), and Character::update_needs().
press_x() [2/3]
std::string press_x (action_id act, const std::string & key_bound, const std::string & key_unbound)
Definition at line 462 of file action.cpp.
{
    input_context ctxt = get_default_mode_input_context();
    return ctxt.press_x( action_ident( act ), key_bound, "", key_unbound );
}
References act, action_ident(), get_default_mode_input_context(), and input_context::press_x().
press_x() [3/3]
std::string press_x (action_id act, const std::string & key_bound_pre, const std::string & key_bound_suf, const std::string & key_unbound)
Definition at line 467 of file action.cpp.
{
    input_context ctxt = get_default_mode_input_context();
    return ctxt.press_x( action_ident( act ), key_bound_pre, key_bound_suf, key_unbound );
}
References act, action_ident(), get_default_mode_input_context(), and input_context::press_x().
press_x_if_bound()
cata::optional< std::string > press_x_if_bound (action_id act)
Definition at line 474 of file action.cpp.
{
    input_context ctxt = get_default_mode_input_context();
    std::string description = action_ident( act );
    if( ctxt.keys_bound_to( description ).empty() ) {
        return cata::nullopt;
    }
    return press_x( act );
}
References act, action_ident(), get_default_mode_input_context(), input_context::keys_bound_to(), cata::nullopt, and press_x().
Referenced by game::handle_action().
Variable Documentation
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static
Referenced by can_butcher_at().
qual_CUT_FINE
const quality_id qual_CUT_FINE("CUT_FINE") ("CUT_FINE") static
Referenced by can_butcher_at().