Cataclysm BN: src/animation.h File Reference
animation.h File Reference
#include <list>
#include <map>
#include <vector>
#include "color.h"
#include "point.h"
Classes
struct explosion_tile
struct point_with_value
Namespaces
namespace explosion_handler
Macros
#define CATA_SRC_ANIMATION_H
Typedefs
using one_bucket = std::vector< point_with_value >
using bucketed_points = std::list< one_bucket >
Enumerations
enum explosion_neighbors {
N_NO_NEIGHBORS = 0 , N_NORTH = 1 , N_SOUTH = 2 , N_NS = 3 ,
N_WEST = 4 , N_NW = 5 , N_SW = 6 , N_NSW = 7 ,
N_EAST = 8 , N_NE = 9 , N_SE = 10 , N_NSE = 11 ,
N_WE = 12 , N_NWE = 13 , N_SWE = 14 , N_NSWE = 15
}
Functions
void explosion_handler::draw_explosion (const tripoint &p, int radius, const nc_color &col, const std::string &exp_name)
void explosion_handler::draw_custom_explosion (const tripoint &p, const std::map< tripoint, nc_color > &area, const std::string &exp_name)
bucketed_points bucket_by_distance (const tripoint &origin, const std::map< tripoint, double > &to_bucket)
bucketed_points optimal_bucketing (const bucketed_points &buckets, size_t max_buckets)
bool minimap_requires_animation ()
bool terrain_requires_animation ()
Macro Definition Documentation
CATA_SRC_ANIMATION_H
#define CATA_SRC_ANIMATION_H
Definition at line 3 of file animation.h.
Typedef Documentation
bucketed_points
using bucketed_points = std::list<one_bucket>
Definition at line 50 of file animation.h.
one_bucket
using one_bucket = std::vector<point_with_value>
Definition at line 49 of file animation.h.
Enumeration Type Documentation
explosion_neighbors
enum explosion_neighbors
Enumerator
N_NO_NEIGHBORS
N_NORTH
N_SOUTH
N_NS
N_WEST
N_NW
N_SW
N_NSW
N_EAST
N_NE
N_SE
N_NSE
N_WE
N_NWE
N_SWE
N_NSWE
Definition at line 12 of file animation.h.
{
    N_NO_NEIGHBORS = 0,
    N_NORTH = 1,
    N_SOUTH = 2,
    N_NS = 3,
    N_WEST = 4,
    N_NW = 5,
    N_SW = 6,
    N_NSW = 7,
    N_EAST = 8,
    N_NE = 9,
    N_SE = 10,
    N_NSE = 11,
    N_WE = 12,
    N_NWE = 13,
    N_SWE = 14,
    N_NSWE = 15
};
Function Documentation
bucket_by_distance()
bucketed_points bucket_by_distance (const tripoint & origin, const std::map< tripoint, double > & to_bucket)
Definition at line 983 of file animation.cpp.
{
    std::map<int, one_bucket> by_distance;
    for( const std::pair<const tripoint, double> &pv : to_bucket ) {
        int dist = trig_dist_squared( origin, pv.first );
        by_distance[dist].emplace_back( pv.first, pv.second );
    }
    bucketed_points buckets;
    for( const std::pair<const int, one_bucket> &bc : by_distance ) {
        buckets.emplace_back( bc.second );
    }
    return buckets;
}
References trig_dist_squared().
Referenced by ranged::draw_cone_aoe().
minimap_requires_animation()
bool minimap_requires_animation ()
Definition at line 1135 of file animation.cpp.
{
#if defined(TILES)
    return tilecontext->minimap_requires_animation();
#else
    return false;
#endif // TILES
}
Referenced by game::get_player_input().
optimal_bucketing()
bucketed_points optimal_bucketing (const bucketed_points & buckets, size_t max_buckets)
Definition at line 998 of file animation.cpp.
{
    if( buckets.size() <= max_buckets ) {
        return buckets;
    }
    assert( max_buckets > 1 );
    std::vector<size_t> sizes = {};
    for( const one_bucket &bc : buckets ) {
        sizes.emplace_back( bc.size() );
    }
    bucketed_points optimal = buckets;
    // TODO: Good algorithm here, this one is a greedy finder of smallest adjacent size sums
    for( size_t i = 0; i < buckets.size() - max_buckets; i++ ) {
        auto smallest = sizes.begin();
        size_t smallest_sum = *smallest + *( smallest + 1 );
        for( auto iter = sizes.begin() + 1; ( iter + 1 ) != sizes.end(); iter++ ) {
            size_t sum = *iter + *( iter + 1 );
            if( sum < smallest_sum ) {
                smallest = iter;
                smallest_sum = sum;
            }
        }
        size_t distance = std::distance( sizes.begin(), smallest );
        sizes[distance] += sizes[distance + 1];
        sizes.erase( smallest + 1 );
        auto left_bucket = std::next( optimal.begin(), distance );
        auto right_bucket = std::next( left_bucket );
        left_bucket->insert( left_bucket->end(), right_bucket->begin(), right_bucket->end() );
        optimal.erase( right_bucket );
    }
    return optimal;
}
Referenced by ranged::draw_cone_aoe().
terrain_requires_animation()
bool terrain_requires_animation ()
Definition at line 1144 of file animation.cpp.
{
#if defined(TILES)
    return tilecontext->terrain_requires_animation();
#else
    return false;
#endif // TILES
}
Referenced by game::get_player_input().