Cataclysm BN: src/animation.cpp File Reference
animation.cpp File Reference
#include "animation.h"
#include "avatar.h"
#include "character.h"
#include "creature.h"
#include "cursesdef.h"
#include "explosion.h"
#include "game.h"
#include "game_constants.h"
#include "map.h"
#include "monster.h"
#include "mtype.h"
#include "options.h"
#include "output.h"
#include "player.h"
#include "point.h"
#include "popup.h"
#include "posix_time.h"
#include "ranged.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "weather.h"
#include <algorithm>
#include <list>
#include <map>
#include <string>
#include <utility>
#include <vector>
Classes
class anonymous_namespace{animation.cpp}::basic_animation
class anonymous_namespace{animation.cpp}::explosion_animation
class anonymous_namespace{animation.cpp}::bullet_animation
class anonymous_namespace{animation.cpp}::wave_animation
Namespaces
namespace anonymous_namespace{animation.cpp}
namespace ranged
Functions
bool anonymous_namespace{animation.cpp}::is_point_visible (const tripoint &p, int margin=0)
bool anonymous_namespace{animation.cpp}::is_radius_visible (const tripoint &center, int radius)
bool anonymous_namespace{animation.cpp}::is_layer_visible (const std::map< tripoint, explosion_tile > &layer)
tripoint anonymous_namespace{animation.cpp}::relative_view_pos (const player &u, const tripoint &p) noexcept
tripoint anonymous_namespace{animation.cpp}::relative_view_pos (const game &g, const tripoint &p) noexcept
void anonymous_namespace{animation.cpp}::draw_explosion_curses (game &g, const tripoint &center, const int r, const nc_color &col)
constexpr explosion_neighbors anonymous_namespace{animation.cpp}::operator| (explosion_neighbors lhs, explosion_neighbors rhs)
constexpr explosion_neighbors anonymous_namespace{animation.cpp}::operator^ (explosion_neighbors lhs, explosion_neighbors rhs)
void anonymous_namespace{animation.cpp}::draw_custom_explosion_curses (game &g, const std::list< std::map< tripoint, explosion_tile > > &layers)
void anonymous_namespace{animation.cpp}::draw_bullet_curses (map &m, const tripoint &t, const char bullet, const tripoint *const p)
void anonymous_namespace{animation.cpp}::hit_animation (const player &u, const tripoint &center, nc_color cColor, const std::string &cTile)
void anonymous_namespace{animation.cpp}::draw_hit_mon_curses (const tripoint &center, const monster &m, const player &u, const bool dead)
void anonymous_namespace{animation.cpp}::draw_hit_player_curses (const game &g, const Character &p, const int dam)
void anonymous_namespace{animation.cpp}::draw_line_curses (game &g, const tripoint &center, const std::vector< tripoint > &ret, bool noreveal)
void anonymous_namespace{animation.cpp}::draw_line_curses (game &g, const std::vector< tripoint > &points)
void anonymous_namespace{animation.cpp}::draw_weather_curses (const catacurses::window &win, const weather_printable &w)
void anonymous_namespace{animation.cpp}::draw_sct_curses (const game &g)
void anonymous_namespace{animation.cpp}::draw_zones_curses (const catacurses::window &w, const tripoint &start, const tripoint &end, const tripoint &offset)
bucketed_points bucket_by_distance (const tripoint &origin, const std::map< tripoint, double > &to_bucket)
bucketed_points optimal_bucketing (const bucketed_points &buckets, size_t max_buckets)
static void draw_cone_aoe_curses (const tripoint &, const bucketed_points &waves)
void ranged::draw_cone_aoe (const tripoint &origin, const std::map< tripoint, double > &aoe)
bool minimap_requires_animation ()
bool terrain_requires_animation ()
Function Documentation
bucket_by_distance()
bucketed_points bucket_by_distance (const tripoint & origin, const std::map< tripoint, double > & to_bucket)
Definition at line 983 of file animation.cpp.
{
    std::map<int, one_bucket> by_distance;
    for( const std::pair<const tripoint, double> &pv : to_bucket ) {
        int dist = trig_dist_squared( origin, pv.first );
        by_distance[dist].emplace_back( pv.first, pv.second );
    }
    bucketed_points buckets;
    for( const std::pair<const int, one_bucket> &bc : by_distance ) {
        buckets.emplace_back( bc.second );
    }
    return buckets;
}
References trig_dist_squared().
Referenced by ranged::draw_cone_aoe().
draw_cone_aoe_curses()
static void draw_cone_aoe_curses (const tripoint & , const bucketed_points & waves) static
Definition at line 1035 of file animation.cpp.
{
    // Calculate screen offset relative to player + view offset position
    const avatar &u = get_avatar();
    const tripoint center = u.pos() + u.view_offset;
    const tripoint topleft( center.x - catacurses::getmaxx( g->w_terrain ) / 2,
                            center.y - catacurses::getmaxy( g->w_terrain ) / 2, 0 );
    auto it = waves.begin();
    shared_ptr_fast<game::draw_callback_t> wave_cb =
    make_shared_fast<game::draw_callback_t>( [&]() {
        // All the buckets up until now
        for( auto inner_it = waves.begin(); inner_it != std::next( it ); inner_it++ ) {
            for( const point_with_value &pr : *inner_it ) {
                // update tripoint in relation to top left corner of curses window
                // mvwputch already filters out of bounds coordinates
                const tripoint p = pr.pt - topleft;
                int intensity = ( pr.val >= 1.0 ) + ( pr.val >= 0.5 ) + ( inner_it == it );
                nc_color col;
                switch( intensity ) {
                    case 3:
                        col = c_red;
                        break;
                    case 2:
                        col = c_yellow;
                        break;
                    case 1:
                        col = c_white;
                        break;
                    default:
                        col = c_dark_gray;
                        break;
                }
                // TODO: Prettier
                mvwputch( g->w_terrain, p.xy(), col, '*' );
            }
        }
    } );
    g->add_draw_callback( wave_cb );
    wave_animation anim;
    for( it = waves.begin(); it != waves.end(); it++ ) {
        anim.progress();
    }
}
References center, g, get_avatar(), catacurses::getmaxx(), catacurses::getmaxy(), Character::pos(), and player::view_offset.
Referenced by ranged::draw_cone_aoe().
minimap_requires_animation()
bool minimap_requires_animation ()
Definition at line 1135 of file animation.cpp.
{
#if defined(TILES)
    return tilecontext->minimap_requires_animation();
#else
    return false;
#endif // TILES
}
Referenced by game::get_player_input().
optimal_bucketing()
bucketed_points optimal_bucketing (const bucketed_points & buckets, size_t max_buckets)
Definition at line 998 of file animation.cpp.
{
    if( buckets.size() <= max_buckets ) {
        return buckets;
    }
    assert( max_buckets > 1 );
    std::vector<size_t> sizes = {};
    for( const one_bucket &bc : buckets ) {
        sizes.emplace_back( bc.size() );
    }
    bucketed_points optimal = buckets;
    // TODO: Good algorithm here, this one is a greedy finder of smallest adjacent size sums
    for( size_t i = 0; i < buckets.size() - max_buckets; i++ ) {
        auto smallest = sizes.begin();
        size_t smallest_sum = *smallest + *( smallest + 1 );
        for( auto iter = sizes.begin() + 1; ( iter + 1 ) != sizes.end(); iter++ ) {
            size_t sum = *iter + *( iter + 1 );
            if( sum < smallest_sum ) {
                smallest = iter;
                smallest_sum = sum;
            }
        }
        size_t distance = std::distance( sizes.begin(), smallest );
        sizes[distance] += sizes[distance + 1];
        sizes.erase( smallest + 1 );
        auto left_bucket = std::next( optimal.begin(), distance );
        auto right_bucket = std::next( left_bucket );
        left_bucket->insert( left_bucket->end(), right_bucket->begin(), right_bucket->end() );
        optimal.erase( right_bucket );
    }
    return optimal;
}
Referenced by ranged::draw_cone_aoe().
terrain_requires_animation()
bool terrain_requires_animation ()
Definition at line 1144 of file animation.cpp.
{
#if defined(TILES)
    return tilecontext->terrain_requires_animation();
#else
    return false;
#endif // TILES
}
Referenced by game::get_player_input().