Cataclysm BN: src/armor_layers.h File Reference
armor_layers.h File Reference
Macros
#define CATA_SRC_ARMOR_LAYERS_H
Functions
void show_armor_layers_ui (Character &who)
Macro Definition Documentation
CATA_SRC_ARMOR_LAYERS_H
#define CATA_SRC_ARMOR_LAYERS_H
Definition at line 3 of file armor_layers.h.
Function Documentation
show_armor_layers_ui()
void show_armor_layers_ui (Character & who)
Definition at line 439 of file armor_layers.cpp.
{
    /* Define required height of the right pane:
    * + 3 - horizontal lines;
    * + 1 - caption line;
    * + 2 - innermost/outermost string lines;
    * + num_bp - sub-categories (torso, head, eyes, etc.);
    * + 1 - gap;
    * number of lines required for displaying all items is calculated dynamically,
    * because some items can have multiple entries (i.e. cover a few parts of body).
    */
    int req_right_h = 3 + 1 + 2 + num_bp + 1;
    for( const body_part cover : all_body_parts ) {
        for( const item &elem : who.worn ) {
            if( elem.covers( cover ) ) {
                req_right_h++;
            }
        }
    }
    /* Define required height of the mid pane:
    * + 3 - horizontal lines;
    * + 1 - caption line;
    * + 8 - general properties
    * + 13 - ASSUMPTION: max possible number of flags @ item
    * + num_bp+1 - warmth & enc block
    */
    const int req_mid_h = 3 + 1 + 8 + 13 + num_bp + 1;
    int win_h = 0;
    int win_w = 0;
    point win;
    int cont_h   = 0;
    int left_w   = 0;
    int right_w  = 0;
    int middle_w = 0;
    int tabindex = num_bp;
    const int tabcount = num_bp + 1;
    int leftListIndex  = 0;
    int leftListOffset = 0;
    int selected       = -1;
    int rightListOffset = 0;
    int leftListLines = 0;
    int rightListLines = 0;
    std::vector<std::list<item>::iterator> tmp_worn;
    std::array<std::string, 13> armor_cat = {{
            _( "Torso" ), _( "Head" ), _( "Eyes" ), _( "Mouth" ), _( "L. Arm" ), _( "R. Arm" ),
            _( "L. Hand" ), _( "R. Hand" ), _( "L. Leg" ), _( "R. Leg" ), _( "L. Foot" ),
            _( "R. Foot" ), _( "All" )
        }
    };
    // Layout window
    catacurses::window w_sort_armor;
    // Subwindows (between lines)
    catacurses::window w_sort_cat;
    catacurses::window w_sort_left;
    catacurses::window w_sort_middle;
    catacurses::window w_sort_right;
    catacurses::window w_encumb;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        win_h = std::min( TERMY, std::max( { FULL_SCREEN_HEIGHT, req_right_h, req_mid_h } ) );
        win_w = FULL_SCREEN_WIDTH + ( TERMX - FULL_SCREEN_WIDTH ) * 3 / 4;
        win.x = TERMX / 2 - win_w / 2;
        win.y = TERMY / 2 - win_h / 2;
        cont_h = win_h - 4;
        left_w = ( win_w - 4 ) / 3;
        right_w = left_w;
        middle_w = ( win_w - 4 ) - left_w - right_w;
        leftListLines = rightListLines = cont_h - 2;
        w_sort_armor = catacurses::newwin( win_h, win_w, win );
        w_sort_cat = catacurses::newwin( 1, win_w - 4, win + point( 2, 1 ) );
        w_sort_left = catacurses::newwin( cont_h, left_w, win + point( 1, 3 ) );
        w_sort_middle = catacurses::newwin( cont_h - num_bp - 1, middle_w,
                                            win + point( 2 + left_w, 3 ) );
        w_sort_right = catacurses::newwin( cont_h, right_w,
                                           win + point( 3 + left_w + middle_w, 3 ) );
        w_encumb = catacurses::newwin( num_bp + 1, middle_w,
                                       win + point( 2 + left_w, -1 + 3 + cont_h - num_bp ) );
        ui.position_from_window( w_sort_armor );
    } );
    ui.mark_resize();
    input_context ctxt( "SORT_ARMOR" );
    ctxt.register_cardinal();
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "PREV_TAB" );
    ctxt.register_action( "NEXT_TAB" );
    ctxt.register_action( "MOVE_ARMOR" );
    ctxt.register_action( "CHANGE_SIDE" );
    ctxt.register_action( "ASSIGN_INVLETS" );
    ctxt.register_action( "SORT_ARMOR" );
    ctxt.register_action( "EQUIP_ARMOR" );
    ctxt.register_action( "EQUIP_ARMOR_HERE" );
    ctxt.register_action( "REMOVE_ARMOR" );
    ctxt.register_action( "USAGE_HELP" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    auto do_return_entry = []() {
        avatar &you = get_avatar();
        you.assign_activity( ACT_ARMOR_LAYERS, 0 );
        you.activity.auto_resume = true;
        you.activity.moves_left = INT_MAX;
    };
    int leftListSize = 0;
    int rightListSize = 0;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        draw_grid( w_sort_armor, left_w, middle_w );
        werase( w_sort_cat );
        werase( w_sort_left );
        werase( w_sort_middle );
        werase( w_sort_right );
        werase( w_encumb );
        // top bar
        wprintz( w_sort_cat, c_white, _( "Sort Armor" ) );
        wprintz( w_sort_cat, c_yellow, "  << %s >>", armor_cat[tabindex] );
        right_print( w_sort_cat, 0, 0, c_white, string_format(
                         _( "Press [<color_yellow>%s</color>] for help.  "
                            "Press [<color_yellow>%s</color>] to change keybindings." ),
                         ctxt.get_desc( "USAGE_HELP" ),
                         ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
        if( leftListLines > leftListSize ) {
            leftListOffset = 0;
        } else if( leftListOffset + leftListLines > leftListSize ) {
            leftListOffset = leftListSize - leftListLines;
        }
        if( leftListOffset > leftListIndex ) {
            leftListOffset = leftListIndex;
        } else if( leftListOffset + leftListLines <= leftListIndex ) {
            leftListOffset = leftListIndex + 1 - leftListLines;
        }
        // Left header
        mvwprintz( w_sort_left, point_zero, c_light_gray, _( "(Innermost)" ) );
        right_print( w_sort_left, 0, 0, c_light_gray, string_format( _( "Storage (%s)" ),
                     volume_units_abbr() ) );
        // Left list
        const int max_drawindex = std::min( leftListSize - leftListOffset, leftListLines );
        for( int drawindex = 0; drawindex < max_drawindex; drawindex++ ) {
            int itemindex = leftListOffset + drawindex;
            if( itemindex == leftListIndex ) {
                mvwprintz( w_sort_left, point( 0, drawindex + 1 ), c_yellow, ">>" );
            }
            std::string worn_armor_name = tmp_worn[itemindex]->tname();
            item_penalties const penalties =
                get_item_penalties( tmp_worn[itemindex], who, tabindex );
            const int offset_x = ( itemindex == selected ) ? 3 : 2;
            trim_and_print( w_sort_left, point( offset_x, drawindex + 1 ), left_w - offset_x - 3,
                            penalties.color_for_stacking_badness(), worn_armor_name );
            right_print( w_sort_left, drawindex + 1, 0, c_light_gray,
                         format_volume( tmp_worn[itemindex]->get_storage() ) );
        }
        // Left footer
        mvwprintz( w_sort_left, point( 0, cont_h - 1 ), c_light_gray, _( "(Outermost)" ) );
        if( leftListOffset + leftListLines < leftListSize ) {
            // TODO: replace it by right_print()
            mvwprintz( w_sort_left, point( left_w - utf8_width( _( "<more>" ) ), cont_h - 1 ),
                       c_light_blue, _( "<more>" ) );
        }
        if( leftListSize == 0 ) {
            // TODO: replace it by right_print()
            mvwprintz( w_sort_left, point( left_w - utf8_width( _( "<empty>" ) ), cont_h - 1 ),
                       c_light_blue, _( "<empty>" ) );
        }
        // Items stats
        if( leftListSize > 0 ) {
            draw_mid_pane( w_sort_middle, tmp_worn[leftListIndex], who, tabindex );
        } else {
            // NOLINTNEXTLINE(cata-use-named-point-constants)
            fold_and_print( w_sort_middle, point( 1, 0 ), middle_w - 1, c_white,
                            _( "Nothing to see here!" ) );
        }
        mvwprintz( w_encumb, point_east, c_white, _( "Encumbrance and Warmth" ) );
        character_display::print_encumbrance( w_encumb, who, -1,
                                              ( leftListSize > 0 ) ? &*tmp_worn[leftListIndex] : nullptr );
        // Right header
        mvwprintz( w_sort_right, point_zero, c_light_gray, _( "(Innermost)" ) );
        right_print( w_sort_right, 0, 0, c_light_gray, _( "Encumbrance" ) );
        const auto &combine_bp = [&]( const int cover ) -> bool {
            return cover > 3 && cover % 2 == 0 &&
            items_cover_bp( who, cover ) == items_cover_bp( who, cover + 1 );
        };
        // Right list
        rightListSize = 0;
        for( int cover = 0; cover < num_bp; cover++ ) {
            rightListSize += items_cover_bp( who, cover ).size() + 1;
            if( combine_bp( cover ) ) {
                cover++;
            }
        }
        if( rightListLines > rightListSize ) {
            rightListOffset = 0;
        } else if( rightListOffset + rightListLines > rightListSize ) {
            rightListOffset = rightListSize - rightListLines;
        }
        for( int cover = 0, pos = 1, curr = 0; cover < num_bp; cover++ ) {
            bool combined = false;
            if( combine_bp( cover ) ) {
                combined = true;
            }
            if( curr >= rightListOffset && pos <= rightListLines ) {
                mvwprintz( w_sort_right, point( 1, pos ), ( cover == tabindex ? c_yellow : c_white ),
                           "%s:", body_part_name_as_heading( all_body_parts[cover], combined ? 2 : 1 ) );
                pos++;
            }
            curr++;
            for( layering_item_info &elem : items_cover_bp( who, cover ) ) {
                if( curr >= rightListOffset && pos <= rightListLines ) {
                    nc_color color = elem.penalties.color_for_stacking_badness();
                    trim_and_print( w_sort_right, point( 2, pos ), right_w - 5, color,
                                    elem.name );
                    char plus = elem.penalties.badness() > 0 ? '+' : ' ';
                    mvwprintz( w_sort_right, point( right_w - 4, pos ), c_light_gray, "%3d%c",
                               elem.encumber, plus );
                    pos++;
                }
                curr++;
            }
            if( combined ) {
                cover++;
            }
        }
        // Right footer
        mvwprintz( w_sort_right, point( 0, cont_h - 1 ), c_light_gray, _( "(Outermost)" ) );
        if( rightListOffset + rightListLines < rightListSize ) {
            // TODO: replace it by right_print()
            mvwprintz( w_sort_right, point( right_w - utf8_width( _( "<more>" ) ), cont_h - 1 ), c_light_blue,
                       _( "<more>" ) );
        }
        // F5
        wnoutrefresh( w_sort_cat );
        wnoutrefresh( w_sort_left );
        wnoutrefresh( w_sort_middle );
        wnoutrefresh( w_sort_right );
        wnoutrefresh( w_encumb );
    } );
    avatar &you = get_avatar();
    bool exit = false;
    while( !exit ) {
        if( who.is_avatar() ) {
            // Totally hoisted this from advanced_inv
            if( you.moves < 0 ) {
                do_return_entry();
                return;
            }
        } else {
            // Player is sorting NPC's armor here
            if( rl_dist( you.pos(), who.pos() ) > 1 ) {
                you.add_msg_if_npc( m_bad, _( "%s is too far to sort armor." ), who.name );
                return;
            }
            if( you.attitude_to( you ) != Creature::A_FRIENDLY ) {
                you.add_msg_if_npc( m_bad, _( "%s is not friendly!" ), who.name );
                return;
            }
        }
        // Create ptr list of items to display
        tmp_worn.clear();
        if( tabindex == num_bp ) {
            // All
            for( auto it = who.worn.begin(); it != who.worn.end(); ++it ) {
                tmp_worn.push_back( it );
            }
        } else {
            // bp_*
            body_part bp = static_cast<body_part>( tabindex );
            for( auto it = who.worn.begin(); it != who.worn.end(); ++it ) {
                if( it->covers( bp ) ) {
                    tmp_worn.push_back( it );
                }
            }
        }
        leftListSize = tmp_worn.size();
        // Ensure leftListIndex is in bounds
        int new_index_upper_bound = std::max( 0, leftListSize - 1 );
        leftListIndex = std::min( leftListIndex, new_index_upper_bound );
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( who.is_npc() && action == "ASSIGN_INVLETS" ) {
            // It doesn't make sense to assign invlets to NPC items
            continue;
        }
        // Helper function for moving items in the list
        auto shift_selected_item = [&]() {
            if( selected >= 0 ) {
                std::list<item>::iterator to = tmp_worn[leftListIndex];
                if( leftListIndex > selected ) {
                    ++to;
                }
                who.worn.splice( to, who.worn, tmp_worn[selected] );
                selected = leftListIndex;
                who.reset_encumbrance();
            }
        };
        if( action == "UP" && leftListSize > 0 ) {
            if( leftListIndex > 0 ) {
                leftListIndex--;
                if( leftListIndex < leftListOffset ) {
                    leftListOffset = leftListIndex;
                }
            } else {
                leftListIndex = leftListSize - 1;
                if( leftListLines >= leftListSize ) {
                    leftListOffset = 0;
                } else {
                    leftListOffset = leftListSize - leftListLines;
                }
            }
            shift_selected_item();
        } else if( action == "DOWN" && leftListSize > 0 ) {
            if( leftListIndex + 1 < leftListSize ) {
                leftListIndex++;
                if( leftListIndex >= leftListOffset + leftListLines ) {
                    leftListOffset = leftListIndex + 1 - leftListLines;
                }
            } else {
                leftListIndex = 0;
                leftListOffset = 0;
            }
            shift_selected_item();
        } else if( action == "LEFT" ) {
            tabindex--;
            if( tabindex < 0 ) {
                tabindex = tabcount - 1;
            }
            leftListIndex = leftListOffset = 0;
            selected = -1;
        } else if( action == "RIGHT" ) {
            tabindex = ( tabindex + 1 ) % tabcount;
            leftListIndex = leftListOffset = 0;
            selected = -1;
        } else if( action == "NEXT_TAB" ) {
            if( rightListOffset + rightListLines < rightListSize ) {
                rightListOffset++;
            }
        } else if( action == "PREV_TAB" ) {
            if( rightListOffset > 0 ) {
                rightListOffset--;
            }
        } else if( action == "MOVE_ARMOR" ) {
            if( selected >= 0 ) {
                selected = -1;
            } else {
                selected = leftListIndex;
            }
        } else if( action == "CHANGE_SIDE" ) {
            if( leftListIndex < leftListSize && tmp_worn[leftListIndex]->is_sided() ) {
                if( you.query_yn( _( "Swap side for %s?" ),
                                  colorize( tmp_worn[leftListIndex]->tname(),
                                            tmp_worn[leftListIndex]->color_in_inventory() ) ) ) {
                    who.change_side( *tmp_worn[leftListIndex] );
                }
            }
        } else if( action == "SORT_ARMOR" ) {
            // Copy to a vector because stable_sort requires random-access
            // iterators
            std::vector<item> worn_copy( who.worn.begin(), who.worn.end() );
            std::stable_sort( worn_copy.begin(), worn_copy.end(),
            []( const item & l, const item & r ) {
                return l.get_layer() < r.get_layer();
            }
                            );
            std::copy( worn_copy.begin(), worn_copy.end(), who.worn.begin() );
            who.reset_encumbrance();
        } else if( action == "EQUIP_ARMOR" ) {
            // filter inventory for all items that are armor/clothing
            item_location loc = game_menus::inv::wear( *who.as_player() );
            // only equip if something valid selected!
            if( loc ) {
                // wear the item
                cata::optional<std::list<item>::iterator> new_equip_it =
                    who.as_player()->wear_possessed( *loc.obtain( who ) );
                if( new_equip_it ) {
                    body_part bp = static_cast<body_part>( tabindex );
                    if( tabindex == num_bp || ( **new_equip_it ).covers( bp ) ) {
                        // Set ourselves up to be pointing at the new item
                        // TODO: This doesn't work yet because we don't save our
                        // state through other activities, but that's a thing
                        // that would be nice to do.
                        leftListIndex =
                            std::count_if( who.worn.begin(), *new_equip_it,
                        [&]( const item & i ) {
                            return tabindex == num_bp || i.covers( bp );
                        } );
                    }
                } else if( who.is_npc() ) {
                    // TODO: Pass the reason here
                    popup( _( "Can't put this on!" ) );
                }
            }
        } else if( action == "EQUIP_ARMOR_HERE" ) {
            // filter inventory for all items that are armor/clothing
            item_location loc = game_menus::inv::wear( *who.as_player() );
            // only equip if something valid selected!
            if( loc ) {
                // wear the item
                if( cata::optional<std::list<item>::iterator> new_equip_it =
                        who.as_player()->wear_possessed( *loc.obtain( who ) ) ) {
                    // save iterator to cursor's position
                    std::list<item>::iterator cursor_it = tmp_worn[leftListIndex];
                    // reorder `worn` vector to place new item at cursor
                    who.worn.splice( cursor_it, who.worn, *new_equip_it );
                } else if( who.is_npc() ) {
                    // TODO: Pass the reason here
                    popup( _( "Can't put this on!" ) );
                }
            }
        } else if( action == "REMOVE_ARMOR" ) {
            // query (for now)
            if( leftListIndex < leftListSize ) {
                if( you.query_yn( _( "Remove selected armor?" ) ) ) {
                    do_return_entry();
                    // remove the item, asking to drop it if necessary
                    who.as_player()->takeoff( *tmp_worn[leftListIndex] );
                    if( !you.has_activity( ACT_ARMOR_LAYERS ) ) {
                        // An activity has been created to take off the item;
                        // we must surrender control until it is done.
                        return;
                    }
                    you.cancel_activity();
                    selected = -1;
                }
            }
        } else if( action == "ASSIGN_INVLETS" ) {
            assert( who.is_avatar() );
            // prompt first before doing this (yes, yes, more popups...)
            if( query_yn( _( "Reassign invlets for armor?" ) ) ) {
                // Start with last armor (the most unimportant one?)
                auto iiter = inv_chars.rbegin();
                auto witer = who.worn.rbegin();
                while( witer != who.worn.rend() && iiter != inv_chars.rend() ) {
                    const char invlet = *iiter;
                    item &w = *witer;
                    if( invlet == w.invlet ) {
                        ++witer;
                    } else if( who.invlet_to_item( invlet ) != nullptr ) {
                        ++iiter;
                    } else {
                        who.inv.reassign_item( w, invlet );
                        ++witer;
                        ++iiter;
                    }
                }
            }
        } else if( action == "USAGE_HELP" ) {
            popup_getkey(
                _( "Use the [<color_yellow>arrow- or keypad keys</color>] to navigate the left list.\n"
                   "[<color_yellow>%s</color>] to select highlighted armor for reordering.\n"
                   "[<color_yellow>%s</color>] / [<color_yellow>%s</color>] to scroll the right list.\n"
                   "[<color_yellow>%s</color>] to assign special inventory letters to clothing.\n"
                   "[<color_yellow>%s</color>] to change the side on which item is worn.\n"
                   "[<color_yellow>%s</color>] to sort armor into natural layer order.\n"
                   "[<color_yellow>%s</color>] to equip a new item.\n"
                   "[<color_yellow>%s</color>] to equip a new item at the currently selected position.\n"
                   "[<color_yellow>%s</color>] to remove selected armor from oneself.\n"
                   "\n"
                   "\n"
                   "Encumbrance explanation:\n"
                   "\n"
                   "<color_light_gray>The first number is the summed encumbrance from all clothing "
                   "on that bodypart.  The second number is an additional encumbrance penalty "
                   "caused by wearing either multiple items on one of the bodypart's layers or "
                   "wearing items the wrong way (e.g. a shirt over a backpack).  "
                   "The sum of these values is the effective encumbrance value "
                   "your character has for that bodypart.</color>" ),
                ctxt.get_desc( "MOVE_ARMOR" ),
                ctxt.get_desc( "PREV_TAB" ),
                ctxt.get_desc( "NEXT_TAB" ),
                ctxt.get_desc( "ASSIGN_INVLETS" ),
                ctxt.get_desc( "CHANGE_SIDE" ),
                ctxt.get_desc( "SORT_ARMOR" ),
                ctxt.get_desc( "EQUIP_ARMOR" ),
                ctxt.get_desc( "EQUIP_ARMOR_HERE" ),
                ctxt.get_desc( "REMOVE_ARMOR" )
            );
        } else if( action == "QUIT" ) {
            exit = true;
        }
    }
}
References _, Creature::A_FRIENDLY, ACT_ARMOR_LAYERS, action, Character::activity, Creature::add_msg_if_npc(), all_body_parts, Creature::as_player(), Character::assign_activity(), Character::attitude_to(), player_activity::auto_resume, body_part_name_as_heading(), c_light_blue, c_light_gray, c_white, c_yellow, Character::cancel_activity(), Character::change_side(), color(), colorize(), item::covers(), draw_grid(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), fold_and_print(), format_volume(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_avatar(), input_context::get_desc(), anonymous_namespace{armor_layers.cpp}::get_item_penalties(), input_context::handle_input(), Character::has_activity(), Character::inv, inv_chars, item::invlet, Character::invlet_to_item(), Creature::is_avatar(), Creature::is_npc(), items_cover_bp(), m_bad, Creature::moves, player_activity::moves_left, mvwprintz(), Character::name, catacurses::newwin(), num_bp, item_location::obtain(), sign::plus, point_east, point_zero, popup(), popup_getkey(), Character::pos(), character_display::print_encumbrance(), player::query_yn(), query_yn(), inventory::reassign_item(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), Character::reset_encumbrance(), right_print(), rl_dist(), string_format(), Character::takeoff(), TERMX, TERMY, trim_and_print(), utf8_width(), volume_units_abbr(), game_menus::inv::wear(), Character::wear_possessed(), catacurses::werase(), catacurses::wnoutrefresh(), Character::worn, wprintz(), point::x, and point::y.
Referenced by activity_handlers::armor_layers_do_turn(), game::handle_action(), and game::npc_menu().