Cataclysm BN: src/armor_layers.cpp File Reference
armor_layers.cpp File Reference
#include "player.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <iterator>
#include <memory>
#include <string>
#include <vector>
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_display.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "game_inventory.h"
#include "input.h"
#include "inventory.h"
#include "item.h"
#include "line.h"
#include "output.h"
#include "player_activity.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui_manager.h"
#include "units_utility.h"
Classes
struct anonymous_namespace{armor_layers.cpp}::item_penalties
struct layering_item_info
Namespaces
namespace anonymous_namespace{armor_layers.cpp}
Functions
static const std::string flag_AURA ("AURA")
static const std::string flag_BELTED ("BELTED")
static const std::string flag_FANCY ("FANCY")
static const std::string flag_FIT ("FIT")
static const std::string flag_FLOTATION ("FLOTATION")
static const std::string flag_HOOD ("HOOD")
static const std::string flag_OUTER ("OUTER")
static const std::string flag_OVERSIZE ("OVERSIZE")
static const std::string flag_PERSONAL ("PERSONAL")
static const std::string flag_POCKETS ("POCKETS")
static const std::string flag_SEMITANGIBLE ("SEMITANGIBLE")
static const std::string flag_COMPACT ("COMPACT")
static const std::string flag_SKINTIGHT ("SKINTIGHT")
static const std::string flag_SUPER_FANCY ("SUPER_FANCY")
static const std::string flag_SWIM_GOGGLES ("SWIM_GOGGLES")
static const std::string flag_WAIST ("WAIST")
static const std::string flag_WATER_FRIENDLY ("WATER_FRIENDLY")
static const std::string flag_WATERPROOF ("WATERPROOF")
std::string anonymous_namespace{armor_layers.cpp}::clothing_layer (const item &worn_item)
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_properties (const item &worn_item, int width, const Character &)
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_protection (const item &worn_item, int width)
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_flags_description (const item &worn_item)
item_penalties anonymous_namespace{armor_layers.cpp}::get_item_penalties (std::list< item >::const_iterator worn_item_it, const Character &c, int tabindex)
std::string anonymous_namespace{armor_layers.cpp}::body_part_names (const std::vector< body_part > &parts)
void anonymous_namespace{armor_layers.cpp}::draw_mid_pane (const catacurses::window &w_sort_middle, std::list< item >::const_iterator const worn_item_it, const Character &c, int tabindex)
static std::vector< layering_item_info > items_cover_bp (const Character &c, int bp)
static void draw_grid (const catacurses::window &w, int left_pane_w, int mid_pane_w)
Variables
static const activity_id ACT_ARMOR_LAYERS ("ACT_ARMOR_LAYERS")
Function Documentation
draw_grid()
static void draw_grid (const catacurses::window & w, int left_pane_w, int mid_pane_w) static
Definition at line 418 of file armor_layers.cpp.
{
    const int win_w = getmaxx( w );
    const int win_h = getmaxy( w );
    draw_border( w );
    mvwhline( w, point( 1, 2 ), 0, win_w - 2 );
    mvwvline( w, point( left_pane_w + 1, 3 ), 0, win_h - 4 );
    mvwvline( w, point( left_pane_w + mid_pane_w + 2, 3 ), 0, win_h - 4 );
    // intersections
    mvwputch( w, point( 0, 2 ), BORDER_COLOR, LINE_XXXO );
    mvwputch( w, point( win_w - 1, 2 ), BORDER_COLOR, LINE_XOXX );
    mvwputch( w, point( left_pane_w + 1, 2 ), BORDER_COLOR, LINE_OXXX );
    mvwputch( w, point( left_pane_w + 1, win_h - 1 ), BORDER_COLOR, LINE_XXOX );
    mvwputch( w, point( left_pane_w + mid_pane_w + 2, 2 ), BORDER_COLOR, LINE_OXXX );
    mvwputch( w, point( left_pane_w + mid_pane_w + 2, win_h - 1 ), BORDER_COLOR, LINE_XXOX );
    wnoutrefresh( w );
}
References BORDER_COLOR, draw_border(), catacurses::getmaxx(), catacurses::getmaxy(), LINE_OXXX, LINE_XOXX, LINE_XXOX, LINE_XXXO, catacurses::mvwhline(), mvwputch(), catacurses::mvwvline(), and catacurses::wnoutrefresh().
Referenced by player::sort_armor().
flag_AURA()
static const std::string flag_AURA ("AURA") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer().
flag_BELTED()
static const std::string flag_BELTED ("BELTED") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer().
flag_COMPACT()
static const std::string flag_COMPACT ("COMPACT") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_FANCY()
static const std::string flag_FANCY ("FANCY") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_FIT()
static const std::string flag_FIT ("FIT") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_FLOTATION()
static const std::string flag_FLOTATION ("FLOTATION") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_HOOD()
static const std::string flag_HOOD ("HOOD") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_OUTER()
static const std::string flag_OUTER ("OUTER") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer().
flag_OVERSIZE()
static const std::string flag_OVERSIZE ("OVERSIZE") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_PERSONAL()
static const std::string flag_PERSONAL ("PERSONAL") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer().
flag_POCKETS()
static const std::string flag_POCKETS ("POCKETS") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_SEMITANGIBLE()
static const std::string flag_SEMITANGIBLE ("SEMITANGIBLE") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_SKINTIGHT()
static const std::string flag_SKINTIGHT ("SKINTIGHT") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer().
flag_SUPER_FANCY()
static const std::string flag_SUPER_FANCY ("SUPER_FANCY") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_SWIM_GOGGLES()
static const std::string flag_SWIM_GOGGLES ("SWIM_GOGGLES") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_WAIST()
static const std::string flag_WAIST ("WAIST") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer().
flag_WATER_FRIENDLY()
static const std::string flag_WATER_FRIENDLY ("WATER_FRIENDLY") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_WATERPROOF()
static const std::string flag_WATERPROOF ("WATERPROOF") static
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
items_cover_bp()
static std::vector< layering_item_info > items_cover_bp (const Character & c, int bp) static
Definition at line 404 of file armor_layers.cpp.
{
    std::vector<layering_item_info> s;
    for( auto elem_it = c.worn.begin(); elem_it != c.worn.end(); ++elem_it ) {
        if( elem_it->covers( static_cast<body_part>( bp ) ) ) {
            s.push_back( { get_item_penalties( elem_it, c, bp ),
                           elem_it->get_encumber( c ),
                           elem_it->tname()
                         } );
        }
    }
    return s;
}
References c, and anonymous_namespace{armor_layers.cpp}::get_item_penalties().
Referenced by player::sort_armor().
Variable Documentation
ACT_ARMOR_LAYERS
const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS") ("ACT_ARMOR_LAYERS") static
Referenced by player::sort_armor().