Cataclysm BN: src/artifact.cpp File Reference
artifact.cpp File Reference
#include "artifact.h"
#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <iosfwd>
#include <map>
#include <memory>
#include <set>
#include <vector>
#include "assign.h"
#include "bodypart.h"
#include "cata_utility.h"
#include "color.h"
#include "damage.h"
#include "debug.h"
#include "fstream_utils.h"
#include "item_factory.h"
#include "iuse.h"
#include "json.h"
#include "optional.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
Classes
struct artifact_shape_datum
struct artifact_property_datum
struct artifact_dream_datum
struct artifact_tool_form_datum
struct artifact_weapon_datum
struct artifact_armor_form_datum
Namespaces
namespace io
Macros
#define PAIR(x) case x: return #x;
Enumerations
enum artifact_natural_shape {
ARTSHAPE_SPHERE , ARTSHAPE_ROD , ARTSHAPE_TEARDROP , ARTSHAPE_LAMP ,
ARTSHAPE_SNAKE , ARTSHAPE_DISC , ARTSHAPE_BEADS , ARTSHAPE_NAPKIN ,
ARTSHAPE_URCHIN , ARTSHAPE_JELLY , ARTSHAPE_SPIRAL , ARTSHAPE_PIN ,
ARTSHAPE_TUBE , ARTSHAPE_PYRAMID , ARTSHAPE_CRYSTAL , ARTSHAPE_KNOT ,
ARTSHAPE_CRESCENT , ARTSHAPE_MAX
}
enum artifact_weapon_type {
ARTWEAP_BULK , ARTWEAP_CLUB , ARTWEAP_SPEAR , ARTWEAP_SWORD ,
ARTWEAP_KNIFE , NUM_ARTWEAPS
}
enum artifact_tool_form {
ARTTOOLFORM_HARP , ARTTOOLFORM_STAFF , ARTTOOLFORM_SWORD , ARTTOOLFORM_KNIFE ,
ARTTOOLFORM_CUBE , NUM_ARTTOOLFORMS
}
enum artifact_armor_mod {
ARMORMOD_NULL , ARMORMOD_LIGHT , ARMORMOD_BULKY , ARMORMOD_POCKETED ,
ARMORMOD_FURRED , ARMORMOD_PADDED , ARMORMOD_PLATED , NUM_ARMORMODS
}
enum artifact_armor_form {
ARTARMFORM_ROBE , ARTARMFORM_COAT , ARTARMFORM_MASK , ARTARMFORM_HELM ,
ARTARMFORM_GLOVES , ARTARMFORM_BOOTS , ARTARMFORM_RING , NUM_ARTARMFORMS
}
Functions
template<typename V , typename B >
units::quantity< V, B > rng (const units::quantity< V, B > &min, const units::quantity< V, B > &max)
std::vector< art_effect_passive > fill_good_passive ()
std::vector< art_effect_passive > fill_bad_passive ()
std::vector< art_effect_active > fill_good_active ()
std::vector< art_effect_active > fill_bad_active ()
std::string artifact_name (const std::string &type)
itype_id new_artifact ()
itype_id new_natural_artifact (artifact_natural_property prop)
void load_artifacts (const std::string &path)
bool save_artifacts (const std::string &path)
template<typename E >
void serialize_enum_vector_as_int (JsonOut &json, const std::string &member, const std::vector< E > &vec)
template<>
std::string io::enum_to_string< art_effect_passive > (art_effect_passive data)
template<>
std::string io::enum_to_string< art_effect_active > (art_effect_active data)
template<>
std::string io::enum_to_string< art_charge > (art_charge data)
template<>
std::string io::enum_to_string< art_charge_req > (art_charge_req data)
Variables
static const std::array< int, NUM_AEPS > passive_effect_cost
static const std::array< int, NUM_AEAS > active_effect_cost
static const std::array< artifact_shape_datum, ARTSHAPE_MAX > artifact_shape_data
static const std::array< artifact_property_datum, ARTPROP_MAX > artifact_property_data
static const std::array< artifact_tool_form_datum, NUM_ARTTOOLFORMS > artifact_tool_form_data
static const std::array< artifact_weapon_datum, NUM_ARTWEAPS > artifact_weapon_data
static const std::array< artifact_armor_form_datum, NUM_ARTARMFORMS > artifact_armor_form_data
static const std::array< artifact_armor_form_datum, NUM_ARMORMODS > artifact_armor_mod_data
static const std::array< std::string, 20 > artifact_adj
static const std::array< std::string, 20 > artifact_noun
static const std::array< artifact_dream_datum, NUM_ACRS > artifact_dream_data
Macro Definition Documentation
PAIR
#define PAIR (x) case x: return #x;
Definition at line 1418 of file artifact.cpp.
Enumeration Type Documentation
artifact_armor_form
enum artifact_armor_form
Enumerator
ARTARMFORM_ROBE
ARTARMFORM_COAT
ARTARMFORM_MASK
ARTARMFORM_HELM
ARTARMFORM_GLOVES
ARTARMFORM_BOOTS
ARTARMFORM_RING
NUM_ARTARMFORMS
Definition at line 259 of file artifact.cpp.
{
    ARTARMFORM_ROBE,
    ARTARMFORM_COAT,
    ARTARMFORM_MASK,
    ARTARMFORM_HELM,
    ARTARMFORM_GLOVES,
    ARTARMFORM_BOOTS,
    ARTARMFORM_RING,
    NUM_ARTARMFORMS
};
artifact_armor_mod
enum artifact_armor_mod
Enumerator
ARMORMOD_NULL
ARMORMOD_LIGHT
ARMORMOD_BULKY
ARMORMOD_POCKETED
ARMORMOD_FURRED
ARMORMOD_PADDED
ARMORMOD_PLATED
NUM_ARMORMODS
Definition at line 226 of file artifact.cpp.
{
    ARMORMOD_NULL,
    ARMORMOD_LIGHT,
    ARMORMOD_BULKY,
    ARMORMOD_POCKETED,
    ARMORMOD_FURRED,
    ARMORMOD_PADDED,
    ARMORMOD_PLATED,
    NUM_ARMORMODS
};
artifact_natural_shape
enum artifact_natural_shape
Enumerator
ARTSHAPE_SPHERE
ARTSHAPE_ROD
ARTSHAPE_TEARDROP
ARTSHAPE_LAMP
ARTSHAPE_SNAKE
ARTSHAPE_DISC
ARTSHAPE_BEADS
ARTSHAPE_NAPKIN
ARTSHAPE_URCHIN
ARTSHAPE_JELLY
ARTSHAPE_SPIRAL
ARTSHAPE_PIN
ARTSHAPE_TUBE
ARTSHAPE_PYRAMID
ARTSHAPE_CRYSTAL
ARTSHAPE_KNOT
ARTSHAPE_CRESCENT
ARTSHAPE_MAX
Definition at line 130 of file artifact.cpp.
{
    ARTSHAPE_SPHERE,
    ARTSHAPE_ROD,
    ARTSHAPE_TEARDROP,
    ARTSHAPE_LAMP,
    ARTSHAPE_SNAKE,
    ARTSHAPE_DISC,
    ARTSHAPE_BEADS,
    ARTSHAPE_NAPKIN,
    ARTSHAPE_URCHIN,
    ARTSHAPE_JELLY,
    ARTSHAPE_SPIRAL,
    ARTSHAPE_PIN,
    ARTSHAPE_TUBE,
    ARTSHAPE_PYRAMID,
    ARTSHAPE_CRYSTAL,
    ARTSHAPE_KNOT,
    ARTSHAPE_CRESCENT,
    ARTSHAPE_MAX
};
artifact_tool_form
enum artifact_tool_form
Enumerator
ARTTOOLFORM_HARP
ARTTOOLFORM_STAFF
ARTTOOLFORM_SWORD
ARTTOOLFORM_KNIFE
ARTTOOLFORM_CUBE
NUM_ARTTOOLFORMS
Definition at line 201 of file artifact.cpp.
{
    ARTTOOLFORM_HARP,
    ARTTOOLFORM_STAFF,
    ARTTOOLFORM_SWORD,
    ARTTOOLFORM_KNIFE,
    ARTTOOLFORM_CUBE,
    NUM_ARTTOOLFORMS
};
artifact_weapon_type
enum artifact_weapon_type
Enumerator
ARTWEAP_BULK
ARTWEAP_CLUB
ARTWEAP_SPEAR
ARTWEAP_SWORD
ARTWEAP_KNIFE
NUM_ARTWEAPS
Definition at line 180 of file artifact.cpp.
{
    ARTWEAP_BULK,  // A bulky item that works okay for bashing
    ARTWEAP_CLUB,  // An item designed to bash
    ARTWEAP_SPEAR, // A stab-only weapon
    ARTWEAP_SWORD, // A long slasher
    ARTWEAP_KNIFE, // Short, slash and stab
    NUM_ARTWEAPS
};
Function Documentation
artifact_name()
std::string artifact_name (const std::string & type)
Definition at line 1087 of file artifact.cpp.
{
    const std::string noun = _( random_entry_ref( artifact_noun ) );
    const std::string adj = _( random_entry_ref( artifact_adj ) );
    std::string ret = string_format( noun, adj );
    ret = string_format( pgettext( "artifact name (type, noun)", "%1$s of %2$s" ), type, ret );
    return ret;
}
References _, artifact_adj, artifact_noun, pgettext(), random_entry_ref(), cata::hash64_detail::ret, string_format(), and type.
Referenced by it_artifact_tool::create_name(), and it_artifact_armor::create_name().
fill_bad_active()
std::vector< art_effect_active > fill_bad_active ()
Definition at line 1078 of file artifact.cpp.
{
    std::vector<art_effect_active> ret;
    for( int i = AEA_SPLIT + 1; i < NUM_AEAS; i++ ) {
        ret.push_back( static_cast<art_effect_active>( i ) );
    }
    return ret;
}
References AEA_SPLIT, NUM_AEAS, and cata::hash64_detail::ret.
Referenced by new_artifact().
fill_bad_passive()
std::vector< art_effect_passive > fill_bad_passive ()
Definition at line 1060 of file artifact.cpp.
{
    std::vector<art_effect_passive> ret;
    for( int i = AEP_SPLIT + 1; i < NUM_AEPS; i++ ) {
        ret.push_back( static_cast<art_effect_passive>( i ) );
    }
    return ret;
}
References AEP_SPLIT, NUM_AEPS, and cata::hash64_detail::ret.
Referenced by new_artifact().
fill_good_active()
std::vector< art_effect_active > fill_good_active ()
Definition at line 1069 of file artifact.cpp.
{
    std::vector<art_effect_active> ret;
    for( int i = AEA_NULL + 1; i < AEA_SPLIT; i++ ) {
        ret.push_back( static_cast<art_effect_active>( i ) );
    }
    return ret;
}
References AEA_NULL, AEA_SPLIT, and cata::hash64_detail::ret.
Referenced by new_artifact().
fill_good_passive()
std::vector< art_effect_passive > fill_good_passive ()
Definition at line 1051 of file artifact.cpp.
{
    std::vector<art_effect_passive> ret;
    for( int i = AEP_NULL + 1; i < AEP_SPLIT; i++ ) {
        ret.push_back( static_cast<art_effect_passive>( i ) );
    }
    return ret;
}
References AEP_NULL, AEP_SPLIT, and cata::hash64_detail::ret.
Referenced by new_artifact().
load_artifacts()
void load_artifacts (const std::string & path)
Definition at line 1098 of file artifact.cpp.
{
    read_from_file_optional_json( path, []( JsonIn & artifact_json ) {
        artifact_json.start_array();
        while( !artifact_json.end_array() ) {
            JsonObject jo = artifact_json.get_object();
            std::string type = jo.get_string( "type" );
            if( type == "artifact_tool" ) {
                item_controller->add_item_type( static_cast<const itype &>( it_artifact_tool( jo ) ) );
            } else if( type == "artifact_armor" ) {
                item_controller->add_item_type( static_cast<const itype &>( it_artifact_armor( jo ) ) );
            } else {
                jo.throw_error( "unrecognized artifact type.", "type" );
            }
        }
    } );
}
References JsonIn::end_array(), read_from_file_optional_json(), JsonIn::start_array(), and type.
new_artifact()
itype_id new_artifact ()
Definition at line 677 of file artifact.cpp.
{
    if( one_in( 2 ) ) {
        // Generate a "tool" artifact
        it_artifact_tool def;
        const artifact_tool_form_datum &info = random_entry_ref( artifact_tool_form_data );
        def.create_name( _( info.name ) );
        def.color = info.color;
        def.sym = std::string( 1, info.sym );
        def.materials.push_back( info.material );
        def.volume = rng( info.volume_min, info.volume_max );
        def.weight = rng( info.weight_min, info.weight_max );
        // Set up the basic weapon type
        const artifact_weapon_datum &weapon = artifact_weapon_data[info.base_weapon];
        def.melee[DT_BASH] = rng( weapon.bash_min, weapon.bash_max );
        def.melee[DT_CUT] = rng( weapon.cut_min, weapon.cut_max );
        def.melee[DT_STAB] = rng( weapon.stab_min, weapon.stab_max );
        def.m_to_hit = rng( weapon.to_hit_min, weapon.to_hit_max );
        if( !weapon.tag.empty() ) {
            def.item_tags.insert( weapon.tag );
        }
        // Add an extra weapon perhaps?
        if( one_in( 2 ) ) {
            const artifact_weapon_type select = random_entry_ref( info.extra_weapons );
            if( select != NUM_ARTWEAPS ) {
                const artifact_weapon_datum &weapon = artifact_weapon_data[select];
                def.volume += weapon.volume;
                def.weight += weapon.weight;
                def.melee[DT_BASH] += rng( weapon.bash_min, weapon.bash_max );
                def.melee[DT_CUT] += rng( weapon.cut_min, weapon.cut_max );
                def.melee[DT_STAB] += rng( weapon.stab_min, weapon.stab_max );
                def.m_to_hit += rng( weapon.to_hit_min, weapon.to_hit_max );
                if( !weapon.tag.empty() ) {
                    def.item_tags.insert( weapon.tag );
                }
                def.create_name( std::string( _( weapon.adjective ) ) + " " + _( info.name ) );
            }
        }
        def.description = no_translation(
                              string_format(
                                  _( "This is the %s.\nIt is the only one of its kind.\nIt may have unknown powers; try activating them." ),
                                  def.nname( 1 ) ) );
        // Finally, pick some powers
        art_effect_passive passive_tmp = AEP_NULL;
        art_effect_active active_tmp = AEA_NULL;
        int num_good = 0;
        int num_bad = 0;
        int value = 0;
        std::vector<art_effect_passive> good_effects = fill_good_passive();
        std::vector<art_effect_passive> bad_effects = fill_bad_passive();
        // Wielded effects first
        while( !good_effects.empty() && !bad_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( num_good < 1 || num_bad < 1 || one_in( num_good + 1 ) ||
                 one_in( num_bad + 1 ) || value > 1 ) ) {
            if( value < 1 && one_in( 2 ) ) {
                // Good
                passive_tmp = random_entry_removed( good_effects );
                num_good++;
            } else if( !bad_effects.empty() ) {
                // Bad effect
                passive_tmp = random_entry_removed( bad_effects );
                num_bad++;
            }
            value += passive_effect_cost[passive_tmp];
            def.artifact->effects_wielded.push_back( passive_tmp );
        }
        // Next, carried effects; more likely to be just bad
        num_good = 0;
        num_bad = 0;
        value = 0;
        good_effects = fill_good_passive();
        bad_effects = fill_bad_passive();
        while( one_in( 2 ) && !good_effects.empty() && !bad_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( num_bad < 1 || one_in( num_bad + 1 ) || value > 1 ) ) {
            if( value < 1 && one_in( 3 ) ) {
                // Good
                passive_tmp = random_entry_removed( good_effects );
                num_good++;
            } else {
                // Bad effect
                passive_tmp = random_entry_removed( bad_effects );
                num_bad++;
            }
            value += passive_effect_cost[passive_tmp];
            def.artifact->effects_carried.push_back( passive_tmp );
        }
        // Finally, activated effects; not necessarily good or bad
        num_good = 0;
        num_bad = 0;
        value = 0;
        std::vector<art_effect_active> good_a_effects = fill_good_active();
        std::vector<art_effect_active> bad_a_effects = fill_bad_active();
        while( !good_a_effects.empty() && !bad_a_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( value > 3 || ( num_bad > 0 && num_good == 0 ) ||
                 !one_in( 3 - num_good ) || !one_in( 3 - num_bad ) ) ) {
            if( !one_in( 3 ) && value <= 1 ) {
                // Good effect
                active_tmp = random_entry_removed( good_a_effects );
                num_good++;
                value += active_effect_cost[active_tmp];
            } else {
                // Bad effect
                active_tmp = random_entry_removed( bad_a_effects );
                num_bad++;
                value += active_effect_cost[active_tmp];
            }
            def.artifact->effects_activated.push_back( active_tmp );
            def.tool->max_charges += rng( 1, 3 );
        }
        def.tool->def_charges = def.tool->max_charges;
        // If we have charges, pick a recharge mechanism
        if( def.tool->max_charges > 0 ) {
            def.artifact->charge_type = static_cast<art_charge>( rng( ARTC_NULL + 1, NUM_ARTCS - 1 ) );
        }
        // 1 in 8 chance that it can't recharge!
        if( one_in( 8 ) && num_bad + num_good >= 4 ) {
            def.artifact->charge_type = ARTC_NULL;
        }
        // Maybe pick an extra recharge requirement
        if( one_in( std::max( 1, 6 - num_good ) ) && def.artifact->charge_type != ARTC_NULL ) {
            def.artifact->charge_req = static_cast<art_charge_req>( rng( ACR_NULL + 1, NUM_ACRS - 1 ) );
        }
        // Assign dream data (stored individually so they can be overridden in json)
        def.artifact->dream_msg_unmet  = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].msg_unmet;
        def.artifact->dream_msg_met    = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].msg_met;
        def.artifact->dream_freq_unmet = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].freq_unmet;
        def.artifact->dream_freq_met   = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].freq_met;
        // Stronger artifacts have a higher chance of picking their dream
        def.artifact->dream_freq_unmet *= ( 1 + 0.1 * ( num_bad + num_good ) );
        def.artifact->dream_freq_met   *= ( 1 + 0.1 * ( num_bad + num_good ) );
        item_controller->add_item_type( static_cast<itype &>( def ) );
        return def.get_id();
    } else {
        // Generate an armor artifact
        it_artifact_armor def;
        const artifact_armor_form_datum &info = random_entry_ref( artifact_armor_form_data );
        def.create_name( _( info.name ) );
        // Armor is always [
        def.sym = "[";
        def.color = info.color;
        def.materials.push_back( info.material );
        def.volume = info.volume;
        def.weight = info.weight;
        def.melee[DT_BASH] = info.melee_bash;
        def.melee[DT_CUT] = info.melee_cut;
        def.m_to_hit = info.melee_hit;
        def.armor->covers = info.covers;
        def.armor->encumber = info.encumb;
        def.armor->max_encumber = info.max_encumb;
        def.armor->coverage = info.coverage;
        def.armor->thickness = info.thickness;
        def.armor->env_resist = info.env_resist;
        def.armor->warmth = info.warmth;
        def.armor->storage = info.storage;
        std::string description = string_format( info.plural ?
                                  _( "This is the %s.\nThey are the only ones of their kind." ) :
                                  _( "This is the %s.\nIt is the only one of its kind." ), def.nname( 1 ) );
        // Modify the armor further
        if( !one_in( 4 ) ) {
            const artifact_armor_mod mod = random_entry_ref( info.available_mods );
            if( mod != ARMORMOD_NULL ) {
                const artifact_armor_form_datum &modinfo = artifact_armor_mod_data[mod];
                if( modinfo.volume >= 0_ml || def.volume > -modinfo.volume ) {
                    def.volume += modinfo.volume;
                } else {
                    def.volume = 250_ml;
                }
                if( modinfo.weight >= 0_gram || def.weight.value() > std::abs( modinfo.weight.value() ) ) {
                    def.weight += modinfo.weight;
                } else {
                    def.weight = 1_gram;
                }
                def.armor->encumber += modinfo.encumb;
                if( modinfo.coverage > 0 || def.armor->coverage > std::abs( modinfo.coverage ) ) {
                    def.armor->coverage += modinfo.coverage;
                } else {
                    def.armor->coverage = 0;
                }
                if( modinfo.thickness > 0 || def.armor->thickness > std::abs( modinfo.thickness ) ) {
                    def.armor->thickness += modinfo.thickness;
                } else {
                    def.armor->thickness = 0;
                }
                if( modinfo.env_resist > 0 || def.armor->env_resist > std::abs( modinfo.env_resist ) ) {
                    def.armor->env_resist += modinfo.env_resist;
                } else {
                    def.armor->env_resist = 0;
                }
                def.armor->warmth += modinfo.warmth;
                if( modinfo.storage > 0_ml || def.armor->storage > -modinfo.storage ) {
                    def.armor->storage += modinfo.storage;
                } else {
                    def.armor->storage = 0_ml;
                }
                description += string_format( info.plural ?
                                              _( "\nThey are %s" ) :
                                              _( "\nIt is %s" ),
                                              _( modinfo.name ) );
            }
        }
        def.description = no_translation( description );
        // Finally, pick some effects
        int num_good = 0;
        int num_bad = 0;
        int value = 0;
        art_effect_passive passive_tmp = AEP_NULL;
        std::vector<art_effect_passive> good_effects = fill_good_passive();
        std::vector<art_effect_passive> bad_effects = fill_bad_passive();
        while( !good_effects.empty() && !bad_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( num_good < 1 || one_in( num_good * 2 ) || value > 1 ||
                 !one_in( 3 - num_bad ) ) ) {
            if( value < 1 && one_in( 2 ) ) {
                // Good effect
                passive_tmp = random_entry_removed( good_effects );
                num_good++;
            } else {
                // Bad effect
                passive_tmp = random_entry_removed( bad_effects );
                num_bad++;
            }
            value += passive_effect_cost[passive_tmp];
            def.artifact->effects_worn.push_back( passive_tmp );
        }
        item_controller->add_item_type( static_cast<itype &>( def ) );
        return def.get_id();
    }
}
References _, ACR_NULL, active_effect_cost, artifact_weapon_datum::adjective, AEA_NULL, AEP_NULL, itype::armor, ARMORMOD_NULL, ARTC_NULL, itype::artifact, artifact_armor_form_data, artifact_armor_mod_data, artifact_dream_data, artifact_tool_form_data, artifact_weapon_data, artifact_armor_form_datum::available_mods, artifact_tool_form_datum::base_weapon, artifact_weapon_datum::bash_max, artifact_weapon_datum::bash_min, artifact_tool_form_datum::color, artifact_armor_form_datum::color, itype::color, artifact_armor_form_datum::coverage, artifact_armor_form_datum::covers, it_artifact_tool::create_name(), it_artifact_armor::create_name(), artifact_weapon_datum::cut_max, artifact_weapon_datum::cut_min, itype::description, DT_BASH, DT_CUT, DT_STAB, artifact_armor_form_datum::encumb, artifact_armor_form_datum::env_resist, artifact_tool_form_datum::extra_weapons, fill_bad_active(), fill_bad_passive(), fill_good_active(), fill_good_passive(), itype::get_id(), item_controller, itype::item_tags, itype::m_to_hit, artifact_tool_form_datum::material, artifact_armor_form_datum::material, itype::materials, artifact_armor_form_datum::max_encumb, itype::melee, artifact_armor_form_datum::melee_bash, artifact_armor_form_datum::melee_cut, artifact_armor_form_datum::melee_hit, artifact_tool_form_datum::name, artifact_armor_form_datum::name, itype::nname(), no_translation(), NUM_ACRS, NUM_ARTCS, NUM_ARTWEAPS, one_in(), passive_effect_cost, artifact_armor_form_datum::plural, random_entry_ref(), random_entry_removed(), rng(), artifact_weapon_datum::stab_max, artifact_weapon_datum::stab_min, artifact_armor_form_datum::storage, string_format(), artifact_tool_form_datum::sym, itype::sym, artifact_weapon_datum::tag, artifact_armor_form_datum::thickness, artifact_weapon_datum::to_hit_max, artifact_weapon_datum::to_hit_min, itype::tool, units::quantity< V, U >::value(), artifact_weapon_datum::volume, artifact_armor_form_datum::volume, itype::volume, artifact_tool_form_datum::volume_max, artifact_tool_form_datum::volume_min, artifact_armor_form_datum::warmth, artifact_weapon_datum::weight, artifact_armor_form_datum::weight, itype::weight, artifact_tool_form_datum::weight_max, and artifact_tool_form_datum::weight_min.
Referenced by map::spawn_artifact().
new_natural_artifact()
itype_id new_natural_artifact (artifact_natural_property prop)
Definition at line 931 of file artifact.cpp.
{
    // Natural artifacts are always tools.
    it_artifact_tool def;
    // Pick a form
    const artifact_shape_datum &shape_data = random_entry_ref( artifact_shape_data );
    // Pick a property
    const artifact_natural_property property = ( prop > ARTPROP_NULL ? prop :
            static_cast<artifact_natural_property>( rng( ARTPROP_NULL + 1,
                    ARTPROP_MAX - 1 ) ) );
    const artifact_property_datum &property_data = artifact_property_data[property];
    def.sym = ":";
    def.color = c_yellow;
    def.materials.push_back( material_id( "stone" ) );
    def.volume = rng( shape_data.volume_min, shape_data.volume_max );
    def.weight = rng( shape_data.weight_min, shape_data.weight_max );
    def.melee[DT_BASH] = 0;
    def.melee[DT_CUT] = 0;
    def.m_to_hit = 0;
    def.create_name( _( property_data.name ), _( shape_data.name ) );
    def.description = no_translation(
                          string_format( pgettext( "artifact description", "This %1$s %2$s." ),
                                         _( shape_data.desc ), _( property_data.desc ) ) );
    // Three possibilities: good passive + bad passive, good active + bad active,
    // and bad passive + good active
    bool good_passive = false, bad_passive = false,
         good_active  = false, bad_active  = false;
    switch( rng( 1, 3 ) ) {
        case 1:
            good_passive = true;
            bad_passive  = true;
            break;
        case 2:
            good_active = true;
            bad_active  = true;
            break;
        case 3:
            bad_passive = true;
            good_active = true;
            break;
    }
    // This is slowly incremented, allowing for better arts
    int value_to_reach = 0;
    int value = 0;
    art_effect_passive aep_good = AEP_NULL, aep_bad = AEP_NULL;
    art_effect_active  aea_good = AEA_NULL, aea_bad = AEA_NULL;
    do {
        if( good_passive ) {
            aep_good = random_entry_ref( property_data.passive_good );
            if( aep_good == AEP_NULL || one_in( 4 ) ) {
                aep_good = static_cast<art_effect_passive>( rng( AEP_NULL + 1, AEP_SPLIT - 1 ) );
            }
        }
        if( bad_passive ) {
            aep_bad = random_entry_ref( property_data.passive_bad );
            if( aep_bad == AEP_NULL || one_in( 4 ) ) {
                aep_bad = static_cast<art_effect_passive>( rng( AEP_SPLIT + 1, NUM_AEAS - 1 ) );
            }
        }
        if( good_active ) {
            aea_good = random_entry_ref( property_data.active_good );
            if( aea_good == AEA_NULL || one_in( 4 ) ) {
                aea_good = static_cast<art_effect_active>( rng( AEA_NULL + 1, AEA_SPLIT - 1 ) );
            }
        }
        if( bad_active ) {
            aea_bad = random_entry_ref( property_data.active_bad );
            if( aea_bad == AEA_NULL || one_in( 4 ) ) {
                aea_bad = static_cast<art_effect_active>( rng( AEA_SPLIT + 1, NUM_AEAS - 1 ) );
            }
        }
        value = passive_effect_cost[aep_good] + passive_effect_cost[aep_bad] +
                active_effect_cost[aea_good] +  active_effect_cost[aea_bad];
        // Yes, it is intentional that this is 1 the first check
        value_to_reach++;
    } while( value > value_to_reach );
    if( aep_good != AEP_NULL ) {
        def.artifact->effects_carried.push_back( aep_good );
    }
    if( aep_bad != AEP_NULL ) {
        def.artifact->effects_carried.push_back( aep_bad );
    }
    if( aea_good != AEA_NULL ) {
        def.artifact->effects_activated.push_back( aea_good );
    }
    if( aea_bad != AEA_NULL ) {
        def.artifact->effects_activated.push_back( aea_bad );
    }
    // Natural artifacts ALWAYS can recharge
    // (When "implanting" them in a mundane item, this ability may be lost
    if( !def.artifact->effects_activated.empty() ) {
        def.tool->def_charges = def.tool->max_charges = rng( 1, 4 );
        def.artifact->charge_type = static_cast<art_charge>( rng( ARTC_NULL + 1, NUM_ARTCS - 1 ) );
        //Maybe pick an extra recharge requirement
        if( one_in( 6 ) ) {
            def.artifact->charge_req = static_cast<art_charge_req>( rng( ACR_NULL + 1, NUM_ACRS - 1 ) );
        }
    }
    // Assign dream data (stored individually so they can be overridden in json)
    def.artifact->dream_msg_unmet  = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].msg_unmet;
    def.artifact->dream_msg_met    = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].msg_met;
    def.artifact->dream_freq_unmet = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].freq_unmet;
    def.artifact->dream_freq_met   = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].freq_met;
    item_controller->add_item_type( static_cast<itype &>( def ) );
    return def.get_id();
}
References _, ACR_NULL, artifact_property_datum::active_bad, active_effect_cost, artifact_property_datum::active_good, AEA_NULL, AEA_SPLIT, AEP_NULL, AEP_SPLIT, ARTC_NULL, itype::artifact, artifact_dream_data, artifact_property_data, artifact_shape_data, ARTPROP_MAX, ARTPROP_NULL, c_yellow, itype::color, it_artifact_tool::create_name(), artifact_shape_datum::desc, artifact_property_datum::desc, itype::description, DT_BASH, DT_CUT, itype::get_id(), item_controller, itype::m_to_hit, itype::materials, itype::melee, artifact_shape_datum::name, artifact_property_datum::name, no_translation(), NUM_ACRS, NUM_AEAS, NUM_ARTCS, one_in(), artifact_property_datum::passive_bad, passive_effect_cost, artifact_property_datum::passive_good, pgettext(), random_entry_ref(), rng(), string_format(), itype::sym, itype::tool, itype::volume, artifact_shape_datum::volume_max, artifact_shape_datum::volume_min, itype::weight, artifact_shape_datum::weight_max, and artifact_shape_datum::weight_min.
Referenced by map::spawn_natural_artifact().
rng()
template<typename V , typename B > units::quantity< V, B > rng (const units::quantity< V, B > & min, const units::quantity< V, B > & max) inline
Definition at line 32 of file artifact.cpp.
{
    return units::quantity<V, B>( rng( min.value(), max.value() ), B{} );
}
References rng(), and units::quantity< V, U >::value().
Referenced by mattack::absorb_meat(), weather_effect::acid(), mattack::acid_accurate(), mattack::acid_barf(), mdefense::acidsplash(), computer_session::action_extract_rad_source(), computer_session::action_irradiator(), computer_session::action_radio_archive(), Character::activate_bionic(), Character::activate_mutation(), timed_event::actualize(), Character::add_addiction(), game::add_artifact_dreams(), item::add_rain_to_container(), addict_effect(), vehicle::alarm(), iuse::anticonvulsant(), iuse::antiparasitic(), spell::aoe(), jmapgen_gaspump::apply(), jmapgen_loot::apply(), apply_ammo_effects(), Character::armor_absorb(), iuse::artifact(), npc::assess_danger(), mission::assign(), vehicle::autopilot_patrol(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), iuse::blech(), blobify(), mdeath::blobsplit(), Character::blossoms(), trapfunc::board(), mattack::boomer(), mdeath::boomer_glow(), mattack::boomer_glow(), vehicle::break_off(), overmap::build_anthill(), overmap::build_city_street(), overmap::build_lab(), overmap::build_mine(), overmap::build_tunnel(), VehicleSpawnFunction::builtin_parkinglot(), VehicleSpawnFunction::builtin_pileup(), map::burn_body_part(), MapExtras::burned_ground_parser(), activity_handlers::burrow_finish(), activity_handlers::butcher_finish(), butchery_drops_harvest(), player::calc_focus_change(), item::calc_rot(), trapfunc::caltrops(), trapfunc::caltrops_glass(), iuse::camera(), can_fire_turret(), avatar_action::can_fire_weapon(), iuse::can_goo(), player::can_sleep(), talk_function::caravan_return(), talk_function::carpenter_return(), spell::cast_all_effects(), game::catch_a_monster(), iuse::chainsaw_off(), activity_handlers::chop_logs_finish(), activity_handlers::chop_planks_finish(), activity_handlers::chop_tree_finish(), cluster_sounds(), iuse::contacts(), avatar::create(), mission_type::create(), Single_item_creator::create(), Item_group::create(), Trait_group_collection::create(), Trait_group_distribution::create(), map::create_anomaly(), spell::create_field(), map::create_hot_air(), Item_group::create_single(), trapfunc::crossbow(), map::crush(), iuse::cs_lajatang_off(), salvage_actor::cut_up(), spell::damage(), vehicle::damage_all(), mattack::dance(), mattack::darkman(), iuse::datura(), Character::deal_damage(), Creature::deal_damage_handle_type(), monster::deal_damage_handle_type(), monster::deal_projectile_attack(), debug_menu::debug(), map::decay_cosmetic_fields(), trap::detect_trap(), item::detonate(), player::disarm(), map::disarm_trap(), map::displace_water(), explosion_handler::do_blast(), explosion_handler::do_blast_new(), Character::do_damage_for_bionic_failure(), vehicle::do_engine_damage(), do_purify(), avatar::do_read(), mattack::dodge_check(), construct::done_trunk_plank(), map::draw_connections(), map::draw_lab(), map::draw_maptile(), map::draw_mine(), map::draw_office_tower(), draw_rough_circle(), map::draw_slimepit(), map::draw_temple(), map::draw_triffid(), map::drop_furniture(), drop_or_embed_projectile(), spell::duration(), dialogue::dynamic_line(), player::eat(), eff_fun_bleed(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_onfire(), eff_fun_rat(), iexamine::egg_sack_generic(), iuse::ehandcuffs(), iuse::einktabletpc(), explosion_handler::emp_blast(), character_funcs::estimate_effect_dur(), mattack::evolve_kill_strike(), Character::expose_to_disease(), iuse::extinguisher(), computer_session::failure_amigara(), computer_session::failure_damage(), computer_session::failure_manhacks(), computer_session::failure_pump_leak(), farm_action(), mattack::fear_paralyze(), talk_function::field_harvest(), game::find_or_make_stairs(), find_potential_computer_point(), mission_start::find_safety(), dig_activity_actor::finish(), fire(), iuse::firecracker_pack_act(), activity_handlers::fish_do_turn(), iuse::fish_trap(), mattack::flesh_golem(), game::fling_creature(), activity_handlers::forage_finish(), talk_function::forage_return(), Character::forced_dismount(), mattack::formblob(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), iexamine::gaspump(), map::generate(), mapgen_basic_container::generate(), lightson_game::generate_change_coords(), overmap::generate_sub(), generate_weather_anim_frame(), jmapgen_int::get(), Name::get(), field_effect::get_duration(), monster::get_horde_attraction(), effect::get_mod(), get_music_description(), get_random_index(), weather_generator::get_weather(), MonsterGroupManager::GetRandomMonsterFromGroup(), MonsterGroupManager::GetResultFromGroup(), give_aid_to(), talk_function::give_equipment(), trapfunc::glass(), trapfunc::glow(), mattack::grab(), iuse::granade_act(), iuse::grenade_inc_act(), mattack::grow_vine(), mattack::growplants(), activity_handlers::gunmod_add_finish(), hack_attempt(), computer_session::hack_attempt(), activity_handlers::hacksaw_finish(), hackveh(), handbrake(), ranged::handle_gun_damage(), start_location::handle_heli_crash(), npc::handle_sound(), vehicle::handle_trap(), player::hardcoded_effects(), hardcoded_mutation_attack(), harvest_common(), iexamine::harvest_plant(), monster::hasten_upgrade(), monster::hear_sound(), Character::hearing_ability(), Character::hitall(), activity_handlers::hotwire_finish(), trapfunc::hum(), basecamp::hunting_results(), monster::impact(), player::impact(), mattack::impale(), iuse::inhaler(), init_memory_card_with_random_stuff(), vehicle::init_state(), Character::install_bionics(), Character::irradiate(), is_summon_friendly(), item::item(), mission_start::kill_horde_master(), vehicle::leak_fuel(), mattack::leech_spawner(), monster::load(), activity_handlers::lockpicking_finish(), mattack::longswipe(), mattack::lunge(), iuse::magic_8_ball(), monster::make_friendly(), map::make_rubble(), activity_handlers::make_zlave_finish(), mapgen_ants_curved(), mapgen_ants_four_way(), mapgen_ants_generic(), mapgen_ants_straight(), mapgen_ants_tee(), mapgen_cavern(), mapgen_crater(), mapgen_field(), mapgen_forest_trail_curved(), mapgen_forest_trail_four_way(), mapgen_forest_trail_straight(), mapgen_forest_trail_tee(), mapgen_hellmouth(), mapgen_hive(), mapgen_lake_shore(), mapgen_rift(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), mapgen_road(), mapgen_rock_partial(), mapgen_sewer_four_way(), mapgen_tutorial(), marloss_common(), Character::melee_attack(), melee_message(), Character::melee_special_effects(), melee_train(), iuse::meth(), Item_modifier::modify(), monster::monster(), map::monster_in_field(), talk_function::morale_chat(), talk_function::morale_chat_activity(), avatar_action::move(), Character::move_effects(), monster::move_effects(), overmap::move_hordes(), monster::move_to(), npc::move_to(), npc::mug_player(), iuse::multicooker(), multicooker_hallu(), spell_effect::mutate(), Character::mutate_towards(), MapExtras::mx_casings(), MapExtras::mx_collegekids(), MapExtras::mx_corpses(), MapExtras::mx_crater(), MapExtras::mx_drugdeal(), MapExtras::mx_grave(), MapExtras::mx_helicopter(), MapExtras::mx_house_spider(), MapExtras::mx_house_wasp(), MapExtras::mx_looters(), MapExtras::mx_marloss_pilgrimage(), MapExtras::mx_mayhem(), MapExtras::mx_military(), MapExtras::mx_minefield(), MapExtras::mx_pond(), MapExtras::mx_portal(), MapExtras::mx_portal_in(), MapExtras::mx_roadblock(), MapExtras::mx_roadworks(), MapExtras::mx_science(), MapExtras::mx_spider(), MapExtras::mx_supplydrop(), iuse::mycus(), new_artifact(), lightson_game::new_level(), minesweeper_game::new_level(), new_natural_artifact(), monster::next_upgrade_time(), vehicle::noise_and_smoke(), monster::nursebot_operate(), Character::old_mutate(), om_cutdown_trees(), om_harvest_furn(), Character::on_damage_of_type(), player::on_dodge(), monster::on_hit(), player::on_hit(), vehicle::operate_planter(), vehicle::operate_reaper(), vehicle::operate_scoop(), activity_handlers::oxytorch_finish(), iuse::pack_cbm(), parse_tags(), vehicle::part_collision(), iexamine::pedestal_wyrm(), timed_event::per_turn(), Character::perform_special_attacks(), Character::perform_technique(), game::perhaps_add_random_npc(), petfood(), iuse::pheromone(), mattack::photograph(), groundcover_extra::pick(), pick_plant(), activity_handlers::pickaxe_finish(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), overmap::place_cities(), Character::place_corpse(), mission_start::place_deposit_box(), map::place_items(), overmap::place_mongroups(), game::place_player(), start_location::place_player(), mission_start::place_priest_diary(), overmap::place_radios(), overmap::place_river(), overmap::place_rivers(), vehicle::place_spawn_items(), map::place_spawns(), overmap::place_special(), overmap::place_special_attempt(), overmap::place_swamps(), game::place_vehicle_nearby(), map::place_vending(), monster::plan(), monexamine::play_with(), activity_handlers::play_with_pet_finish(), map::player_in_field(), vehicle::pldrive(), avatar_action::plthrow(), iuse::portal(), player::practice(), iexamine::practice_survival_while_foraging(), mdeath::preg_roach(), computer_session::print_gibberish_line(), game::process_artifact(), Character::process_bionic(), item::process_corpse(), map::process_fields_in_submap(), item::process_litcig(), monster::process_one_effect(), sounds::process_sound_markers(), monster::process_turn(), player::process_turn(), projectile_attack(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), iuse::purify_iv(), monster::push_to(), radio_tower::radio_tower(), mission_start::ranch_nurse_1(), rand_char(), om_direction::random(), random_neighbor(), random_point(), random_string(), avatar::randomize(), npc::randomize(), mattack::ratking(), Character::react_to_felt_pain(), SkillLevel::readBook(), basecamp::recruit_return(), iexamine::recycle_compactor(), activity_handlers::reload_finish(), vehicle::remove_part(), monster::reset_special_rng(), explosion_handler::explosion_funcs::resonance_cascade(), reveal_destination(), mattack::riotbot(), rng(), distribution::rng_roll(), activity_handlers::robot_control_finish(), robot_finds_kitten::robot_finds_kitten(), rod_fish(), talk_trial::roll(), Character::roll_bash_damage(), Character::roll_cut_damage(), map::rotten_item_spawn(), iuse::rpgdie(), game::save_cyborg(), scatter_chunks(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), mattack::science(), science_room(), basecamp::search_results(), mattack::searchlight(), vehicle::selfdrive(), set_description(), npc::set_omt_destination(), set_up_butchery_activity(), trapfunc::shadow(), map::shake_vehicle(), mattack::shockstorm(), map::shoot(), npc::shop_restock(), trapfunc::shotgun(), mattack::shriek_stun(), iexamine::shrub_wildveggies(), overmap::signal_hordes(), item::simulate_burn(), sinkhole_safety_roll(), mattack::slimespring(), smash(), vehicle::smash_security_system(), trapfunc::snake(), Character::sound_hallu(), npc::spawn_at_sm(), map::spawn_monsters_submap_group(), spell_effect::spawn_summoned_monster(), defense_game::spawn_wave_monster(), defense_game::special_wave_message(), vehicle::spew_field(), mattack::spit_sap(), mdeath::splatter(), map::spread_gas(), monster::stability_roll(), game::start_calendar(), snake_game::start_game(), basecamp::start_garage_chop(), starting_inv(), str_to_illiterate_str(), mattack::stretch_attack(), mattack::stretch_bite(), Character::suffer_from_asthma(), Character::suffer_from_bad_bionics(), Character::suffer_from_chemimbalance(), Character::suffer_from_other_mutations(), Character::suffer_from_radiation(), Character::suffer_from_schizophrenia(), Character::suffer_from_stimulants(), Character::suffer_while_awake(), Character::suffer_while_underwater(), Character::suffer_without_sleep(), survive_random_encounter(), mattack::taze(), iuse::tazer(), teleport::teleport(), mattack::tentacle(), test_crossing_threshold(), player::throw_item(), iuse::throwable_extinguisher_act(), mattack::thrown_by_judo(), vehicle::thrust(), iexamine::toilet(), vehicle::transform_terrain(), iexamine::tree_hickory(), mattack::triffid_heartbeat(), explosion_iuse::trigger_explosion(), iuse::trimmer_off(), trapfunc::tripwire(), try_reject_mutagen(), try_remove_downed(), try_remove_grab(), monster::try_reproduce(), om_direction::turn_random(), Character::uninstall_bionic(), player::update_body_wetness(), Character::update_needs(), game::update_stair_monsters(), iuse_transform::use(), consume_drug_iuse::use(), place_monster_iuse::use(), enzlave_actor::use(), fireweapon_off_actor::use(), mutagen_actor::use(), mutagen_iv_actor::use(), sew_advanced_actor::use(), game::vertical_move(), Character::vomit(), mongroup::wander(), map::water_from(), weed_msg(), weather_effect::wet_player(), and mdefense::zapback().
save_artifacts()
bool save_artifacts (const std::string & path)
Definition at line 1277 of file artifact.cpp.
{
    return write_to_file( path, [&]( std::ostream & fout ) {
        JsonOut json( fout, true );
        json.start_array();
        // We only want runtime types, otherwise static artifacts are loaded twice (on init and then on game load)
        for( const itype *e : item_controller->get_runtime_types() ) {
            if( !e->artifact ) {
                continue;
            }
            if( e->tool ) {
                json.write( it_artifact_tool( *e ) );
            } else if( e->armor ) {
                json.write( it_artifact_armor( *e ) );
            }
        }
        json.end_array();
    }, _( "artifact file" ) );
}
References _, JsonOut::end_array(), item_controller, JsonOut::start_array(), JsonOut::write(), and write_to_file().
Referenced by game::save_artifacts().
serialize_enum_vector_as_int()
template<typename E > void serialize_enum_vector_as_int (JsonOut & json, const std::string & member, const std::vector< E > & vec)
Definition at line 1300 of file artifact.cpp.
{
    json.member( member );
    json.start_array();
    for( auto &e : vec ) {
        json.write( static_cast<int>( e ) );
    }
    json.end_array();
}
References JsonOut::end_array(), JsonOut::member(), mapgen_defer::member, JsonOut::start_array(), and JsonOut::write().
Referenced by it_artifact_tool::serialize(), and it_artifact_armor::serialize().
Variable Documentation
active_effect_cost
const std::array<int, NUM_AEAS> active_effect_cost static
Definition at line 90 of file artifact.cpp.
Referenced by new_artifact(), and new_natural_artifact().
artifact_adj
const std::array<std::string, 20> artifact_adj static
Initial value:
= { {
        translate_marker( "Forbidden" ), translate_marker( "Unknowable" ), translate_marker( "Forgotten" ), translate_marker( "Hideous" ), translate_marker( "Eldritch" ),
        translate_marker( "Gelatinous" ), translate_marker( "Ancient" ), translate_marker( "Cursed" ), translate_marker( "Bloody" ), translate_marker( "Undying" ),
        translate_marker( "Shadowy" ), translate_marker( "Silent" ), translate_marker( "Cyclopean" ), translate_marker( "Fungal" ), translate_marker( "Unspeakable" ),
        translate_marker( "Antediluvian" ), translate_marker( "Frigid" ), translate_marker( "Shattered" ), translate_marker( "Sleeping" ), translate_marker( "Repellent" )
    }
}
Definition at line 578 of file artifact.cpp.
Referenced by artifact_name().
artifact_armor_form_data
const std::array<artifact_armor_form_datum, NUM_ARTARMFORMS> artifact_armor_form_data static
Definition at line 457 of file artifact.cpp.
Referenced by new_artifact().
artifact_armor_mod_data
const std::array<artifact_armor_form_datum, NUM_ARMORMODS> artifact_armor_mod_data static
Definition at line 533 of file artifact.cpp.
Referenced by new_artifact().
artifact_dream_data
const std::array<artifact_dream_datum, NUM_ACRS> artifact_dream_data static
Initial value:
= { {
        {   {translate_marker( "The %s is somehow vaguely dissatisfied even though it doesn't want anything.  Seeing this is a bug!" )},
            {translate_marker( "The %s is satisfied, as it should be because it has no standards.  Seeing this is a bug!" )},
            100,  0
        }, { {translate_marker( "Your %s feels needy, like it wants to be held." )},
            {translate_marker( "You snuggle your %s closer." )},
            50,  35
        }, { {translate_marker( "Your %s feels needy, like it wants to be touched." )},
            {translate_marker( "You press your %s against your skin." )},
            50,  35
        }, { {translate_marker( "The %s is confused to find you dreaming while awake.  Seeing this is a bug!" )},
            {translate_marker( "Your %s sleeps soundly." )},
            100, 33
        }, { {translate_marker( "Your %s longs for the glow." )},
            {translate_marker( "Your %s basks in the glow." )},
            25,  75
        }, { {translate_marker( "You dream of angels' tears falling on your %s." )},
            {translate_marker( "You dream of playing in the rain with your %s." )},
            50,  60
        }, { {translate_marker( "You dream that your %s is being buried alive." )},
            {translate_marker( "You dream of your %s dancing in a blue void." )},
            50,  50
        }
    }
}
Definition at line 594 of file artifact.cpp.
Referenced by it_artifact_tool::deserialize(), it_artifact_tool::it_artifact_tool(), new_artifact(), and new_natural_artifact().
artifact_noun
const std::array<std::string, 20> artifact_noun static
Initial value:
= { {
        translate_marker( "%s Technique" ), translate_marker( "%s Dreams" ), translate_marker( "%s Beasts" ), translate_marker( "%s Evil" ), translate_marker( "%s Miasma" ),
        translate_marker( "the %s Abyss" ), translate_marker( "the %s City" ), translate_marker( "%s Shadows" ), translate_marker( "%s Shade" ), translate_marker( "%s Illusion" ),
        translate_marker( "%s Justice" ), translate_marker( "the %s Necropolis" ), translate_marker( "%s Ichor" ), translate_marker( "the %s Monolith" ), translate_marker( "%s Aeons" ),
        translate_marker( "%s Graves" ), translate_marker( "%s Horrors" ), translate_marker( "%s Suffering" ), translate_marker( "%s Death" ), translate_marker( "%s Horror" )
    }
}
Definition at line 585 of file artifact.cpp.
Referenced by artifact_name().
artifact_property_data
const std::array<artifact_property_datum, ARTPROP_MAX> artifact_property_data static
Definition at line 290 of file artifact.cpp.
Referenced by new_natural_artifact().
artifact_shape_data
const std::array<artifact_shape_datum, ARTSHAPE_MAX> artifact_shape_data static
Initial value:
= { {
        {translate_marker( "sphere" ), translate_marker( "smooth sphere" ), 500_ml, 1_liter, 1_gram, 1150_gram},
        {translate_marker( "rod" ), translate_marker( "tapered rod" ), 250_ml, 1750_ml, 1_gram, 800_gram},
        {translate_marker( "teardrop" ), translate_marker( "teardrop-shaped stone" ), 500_ml, 1500_ml, 1_gram, 950_gram},
        {translate_marker( "lamp" ), translate_marker( "hollow, transparent cube" ), 1_liter, 225_ml, 1_gram, 350_gram},
        {translate_marker( "snake" ), translate_marker( "winding, flexible rod" ), 0_ml, 2_liter, 1_gram, 950_gram},
        {translate_marker( "disc" ), translate_marker( "smooth disc" ), 1_liter, 1500_ml, 200_gram, 400_gram},
        {translate_marker( "beads" ), translate_marker( "string of beads" ), 750_ml, 1750_ml, 1_gram, 700_gram},
        {translate_marker( "napkin" ), translate_marker( "very thin sheet" ), 0_ml, 750_ml, 1_gram, 350_gram},
        {translate_marker( "urchin" ), translate_marker( "spiked sphere" ), 750_ml, 1250_ml, 200_gram, 700_gram},
        {translate_marker( "jelly" ), translate_marker( "malleable blob" ), 500_ml, 2_liter, 200_gram, 450_gram},
        {translate_marker( "spiral" ), translate_marker( "spiraling rod" ), 1250_ml, 1500_ml, 200_gram, 350_gram},
        {translate_marker( "pin" ), translate_marker( "pointed rod" ), 250_ml, 1250_ml, 100_gram, 1050_gram},
        {translate_marker( "tube" ), translate_marker( "hollow tube" ), 500_ml, 1250_ml, 350_gram, 700_gram},
        {translate_marker( "pyramid" ), translate_marker( "regular tetrahedron" ), 750_ml, 1750_ml, 200_gram, 450_gram},
        {translate_marker( "crystal" ), translate_marker( "translucent crystal" ), 250_ml, 1500_ml, 200_gram, 800_gram},
        {translate_marker( "knot" ), translate_marker( "twisted, knotted cord" ), 500_ml, 1500_ml, 100_gram, 800_gram},
        {translate_marker( "crescent" ), translate_marker( "crescent-shaped stone" ), 500_ml, 1500_ml, 200_gram, 700_gram}
    }
}
Definition at line 270 of file artifact.cpp.
Referenced by new_natural_artifact().
artifact_tool_form_data
const std::array<artifact_tool_form_datum, NUM_ARTTOOLFORMS> artifact_tool_form_data static
Initial value:
= { {
        {
            translate_marker( "Harp" ), ';', def_c_yellow, material_id( "wood" ), 5_liter, 7500_ml, 1150_gram, 2100_gram, ARTWEAP_BULK,
            {{ARTWEAP_SPEAR, ARTWEAP_SWORD, ARTWEAP_KNIFE}}
        },
        {
            translate_marker( "Staff" ), '/', def_c_brown, material_id( "wood" ), 1500_ml, 3_liter, 450_gram, 1150_gram, ARTWEAP_CLUB,
            {{ARTWEAP_BULK, ARTWEAP_SPEAR, ARTWEAP_KNIFE}}
        },
        {
            translate_marker( "Sword" ), '/', def_c_light_blue, material_id( "steel" ), 2_liter, 3500_ml, 900_gram, 3259_gram, ARTWEAP_SWORD,
            {{ARTWEAP_BULK, NUM_ARTWEAPS, NUM_ARTWEAPS}}
        },
        {
            translate_marker( "Dagger" ), ';', def_c_light_blue, material_id( "steel" ), 250_ml, 1_liter, 100_gram, 700_gram, ARTWEAP_KNIFE,
            {{NUM_ARTWEAPS, NUM_ARTWEAPS, NUM_ARTWEAPS}}
        },
        {
            translate_marker( "Cube" ), '*', def_c_white, material_id( "steel" ), 250_ml, 750_ml, 100_gram, 2300_gram, ARTWEAP_BULK,
            {{ARTWEAP_SPEAR, NUM_ARTWEAPS, NUM_ARTWEAPS}}
        }
    }
}
Definition at line 421 of file artifact.cpp.
Referenced by new_artifact().
artifact_weapon_data
const std::array<artifact_weapon_datum, NUM_ARTWEAPS> artifact_weapon_data static
Initial value:
= { {
        { translate_marker( "Heavy" ),   0_ml,   1400_gram, 10, 20,  0,  0,  0,  0, -2, 0, "" },
        { translate_marker( "Knobbed" ), 250_ml,  250_gram, 14, 30,  0,  0,  0,  0, -1, 1, "" },
        { translate_marker( "Spiked" ),  250_ml,  100_gram,  0,  0,  0,  0, 20, 40, -1, 1, "" },
        { translate_marker( "Edged" ),   500_ml,  450_gram,  0,  0, 20, 50,  0,  0, -1, 2, "SHEATH_SWORD" },
        { translate_marker( "Bladed" ),  250_ml, 2250_gram,  0,  0,  0,  0, 12, 30, -1, 1, "SHEATH_KNIFE" }
    }
}
Definition at line 448 of file artifact.cpp.
Referenced by new_artifact().
passive_effect_cost
const std::array<int, NUM_AEPS> passive_effect_cost static
Definition at line 43 of file artifact.cpp.
Referenced by new_artifact(), and new_natural_artifact().