Cataclysm BN: src/artifact.h File Reference
artifact.h File Reference
#include <string>
#include "enums.h"
#include "itype.h"
#include "relic.h"
Classes
struct enum_traits< art_effect_active >
struct enum_traits< art_charge >
struct enum_traits< art_charge_req >
class it_artifact_tool
class it_artifact_armor
Macros
#define CATA_SRC_ARTIFACT_H
Enumerations
enum art_effect_active : int {
AEA_NULL = 0 , AEA_STORM , AEA_FIREBALL , AEA_ADRENALINE ,
AEA_MAP , AEA_BLOOD , AEA_FATIGUE , AEA_ACIDBALL ,
AEA_PULSE , AEA_HEAL , AEA_CONFUSED , AEA_ENTRANCE ,
AEA_BUGS , AEA_TELEPORT , AEA_LIGHT , AEA_GROWTH ,
AEA_HURTALL , AEA_FUN , AEA_SPLIT , AEA_RADIATION ,
AEA_PAIN , AEA_MUTATE , AEA_PARALYZE , AEA_FIRESTORM ,
AEA_ATTENTION , AEA_TELEGLOW , AEA_NOISE , AEA_SCREAM ,
AEA_DIM , AEA_FLASH , AEA_VOMIT , AEA_SHADOWS ,
AEA_STAMINA_EMPTY , NUM_AEAS
}
enum art_charge : int {
ARTC_NULL , ARTC_TIME , ARTC_SOLAR , ARTC_PAIN ,
ARTC_HP , ARTC_FATIGUE , ARTC_PORTAL , NUM_ARTCS
}
enum art_charge_req : int {
ACR_NULL = 0 , ACR_EQUIP , ACR_SKIN , ACR_SLEEP ,
ACR_RAD , ACR_WET , ACR_SKY , NUM_ACRS
}
Functions
itype_id new_artifact ()
itype_id new_natural_artifact (artifact_natural_property prop)
void load_artifacts (const std::string &path)
bool save_artifacts (const std::string &path)
bool check_art_charge_req (item &it)
Macro Definition Documentation
CATA_SRC_ARTIFACT_H
#define CATA_SRC_ARTIFACT_H
Definition at line 3 of file artifact.h.
Enumeration Type Documentation
art_charge
enum art_charge : int
Enumerator
ARTC_NULL
ARTC_TIME
ARTC_SOLAR
ARTC_PAIN
ARTC_HP
ARTC_FATIGUE
ARTC_PORTAL
NUM_ARTCS
Definition at line 62 of file artifact.h.
                : int {
    ARTC_NULL,    // Never recharges!
    ARTC_TIME,    // Very slowly recharges with time
    ARTC_SOLAR,   // Recharges in sunlight
    ARTC_PAIN,    // Creates pain to recharge
    ARTC_HP,      // Drains HP to recharge
    ARTC_FATIGUE, // Creates fatigue to recharge
    ARTC_PORTAL,  // Consumes portals
    NUM_ARTCS
};
art_charge_req
enum art_charge_req : int
Enumerator
ACR_NULL
ACR_EQUIP
ACR_SKIN
ACR_SLEEP
ACR_RAD
ACR_WET
ACR_SKY
NUM_ACRS
Definition at line 78 of file artifact.h.
                    : int {
    ACR_NULL = 0, //No extra requirement
    ACR_EQUIP,    //Must be worn/wielded as appropriate
    ACR_SKIN,     //As ACR_EQUIP, plus must be only 50+-coverage thing on a bodypart (or no gloves if wielded)
    ACR_SLEEP,    //Only while sleeping
    ACR_RAD,      //Must be irradiated/in irradiated tile
    ACR_WET,      //Must be wet or in rain
    ACR_SKY,      //Must be on a Z-level above the surface
    NUM_ACRS
};
art_effect_active
enum art_effect_active : int
Enumerator
AEA_NULL
AEA_STORM
AEA_FIREBALL
AEA_ADRENALINE
AEA_MAP
AEA_BLOOD
AEA_FATIGUE
AEA_ACIDBALL
AEA_PULSE
AEA_HEAL
AEA_CONFUSED
AEA_ENTRANCE
AEA_BUGS
AEA_TELEPORT
AEA_LIGHT
AEA_GROWTH
AEA_HURTALL
AEA_FUN
AEA_SPLIT
AEA_RADIATION
AEA_PAIN
AEA_MUTATE
AEA_PARALYZE
AEA_FIRESTORM
AEA_ATTENTION
AEA_TELEGLOW
AEA_NOISE
AEA_SCREAM
AEA_DIM
AEA_FLASH
AEA_VOMIT
AEA_SHADOWS
AEA_STAMINA_EMPTY
NUM_AEAS
Definition at line 16 of file artifact.h.
                       : int {
    AEA_NULL = 0,
    AEA_STORM, // Emits shock fields
    AEA_FIREBALL, // Targeted
    AEA_ADRENALINE, // Adrenaline rush
    AEA_MAP, // Maps the area around you
    AEA_BLOOD, // Shoots blood all over
    AEA_FATIGUE, // Creates interdimensional fatigue
    AEA_ACIDBALL, // Targeted acid
    AEA_PULSE, // Destroys adjacent terrain
    AEA_HEAL, // Heals minor damage
    AEA_CONFUSED, // Confuses all monsters in view
    AEA_ENTRANCE, // Chance to make nearby monsters friendly
    AEA_BUGS, // Chance to summon friendly insects
    AEA_TELEPORT, // Teleports you
    AEA_LIGHT, // Temporary light source
    AEA_GROWTH, // Grow plants, a la triffid queen
    AEA_HURTALL, // Hurts all monsters!
    AEA_FUN, // Temporary morale bonus
    AEA_SPLIT, // Split between good and bad
    AEA_RADIATION, // Spew radioactive gas
    AEA_PAIN, // Increases player pain
    AEA_MUTATE, // Chance of mutation
    AEA_PARALYZE, // You lose several turns
    AEA_FIRESTORM, // Spreads minor fire all around you
    AEA_ATTENTION, // Attention from sub-prime denizens
    AEA_TELEGLOW, // Teleglow disease
    AEA_NOISE, // Loud noise
    AEA_SCREAM, // Noise & morale penalty
    AEA_DIM, // Darkens the sky slowly
    AEA_FLASH, // Flashbang
    AEA_VOMIT, // User vomits
    AEA_SHADOWS, // Summon shadow creatures
    AEA_STAMINA_EMPTY, // Empties most of the player's stamina gauge
    NUM_AEAS
};
Function Documentation
check_art_charge_req()
bool check_art_charge_req (item & it)
Definition at line 11598 of file game.cpp.
{
    player &p = g->u;
    bool reqsmet = true;
    const bool worn = p.is_worn( it );
    const bool wielded = ( &it == &p.weapon );
    const bool heldweapon = ( wielded && !it.is_armor() ); //don't charge wielded clothes
    map &here = get_map();
    switch( it.type->artifact->charge_req ) {
        case( ACR_NULL ):
        case( NUM_ACRS ):
            break;
        case( ACR_EQUIP ):
            //Generated artifacts won't both be wearable and have charges, but nice for mods
            reqsmet = ( worn || heldweapon );
            break;
        case( ACR_SKIN ):
            //As ACR_EQUIP, but also requires nothing worn on bodypart wielding or wearing item
            if( !worn && !heldweapon ) {
                reqsmet = false;
                break;
            }
            for( const body_part bp : all_body_parts ) {
                if( it.covers( bp ) || ( heldweapon && ( bp == bp_hand_r || bp == bp_hand_l ) ) ) {
                    reqsmet = true;
                    for( auto &i : p.worn ) {
                        if( i.covers( bp ) && ( &it != &i ) && i.get_coverage() > 50 ) {
                            reqsmet = false;
                            break; //This one's no good, check the next body part
                        }
                    }
                    if( reqsmet ) {
                        break;    //Only need skin contact on one bodypart
                    }
                }
            }
            break;
        case( ACR_SLEEP ):
            reqsmet = p.has_effect( effect_sleep );
            break;
        case( ACR_RAD ):
            reqsmet = ( ( here.get_radiation( p.pos() ) > 0 ) || ( p.get_rad() > 0 ) );
            break;
        case( ACR_WET ):
            reqsmet = std::any_of( p.body_wetness.begin(), p.body_wetness.end(),
            []( const int w ) {
                return w != 0;
            } );
            if( !reqsmet && sum_conditions( calendar::turn - 1_turns, calendar::turn, p.pos() ).rain_amount > 0
                && !( p.in_vehicle && here.veh_at( p.pos() )->is_inside() ) ) {
                reqsmet = true;
            }
            break;
        case( ACR_SKY ):
            reqsmet = ( p.posz() > 0 );
            break;
    }
    return reqsmet;
}
References ACR_EQUIP, ACR_NULL, ACR_RAD, ACR_SKIN, ACR_SKY, ACR_SLEEP, ACR_WET, all_body_parts, itype::artifact, Character::body_wetness, bp_hand_l, bp_hand_r, item::covers(), effect_sleep, g, game::get_map, Character::get_rad(), map::get_radiation(), Creature::has_effect(), Character::in_vehicle, item::is_armor(), Character::is_worn(), NUM_ACRS, Character::pos(), Character::posz(), weather_sum::rain_amount, sum_conditions(), calendar::turn, item::type, map::veh_at(), Character::weapon, and Character::worn.
Referenced by game::add_artifact_dreams(), and game::process_artifact().
load_artifacts()
void load_artifacts (const std::string & path)
Definition at line 1098 of file artifact.cpp.
{
    read_from_file_optional_json( path, []( JsonIn & artifact_json ) {
        artifact_json.start_array();
        while( !artifact_json.end_array() ) {
            JsonObject jo = artifact_json.get_object();
            std::string type = jo.get_string( "type" );
            if( type == "artifact_tool" ) {
                item_controller->add_item_type( static_cast<const itype &>( it_artifact_tool( jo ) ) );
            } else if( type == "artifact_armor" ) {
                item_controller->add_item_type( static_cast<const itype &>( it_artifact_armor( jo ) ) );
            } else {
                jo.throw_error( "unrecognized artifact type.", "type" );
            }
        }
    } );
}
References JsonIn::end_array(), read_from_file_optional_json(), JsonIn::start_array(), and type.
new_artifact()
itype_id new_artifact ()
Definition at line 677 of file artifact.cpp.
{
    if( one_in( 2 ) ) {
        // Generate a "tool" artifact
        it_artifact_tool def;
        const artifact_tool_form_datum &info = random_entry_ref( artifact_tool_form_data );
        def.create_name( _( info.name ) );
        def.color = info.color;
        def.sym = std::string( 1, info.sym );
        def.materials.push_back( info.material );
        def.volume = rng( info.volume_min, info.volume_max );
        def.weight = rng( info.weight_min, info.weight_max );
        // Set up the basic weapon type
        const artifact_weapon_datum &weapon = artifact_weapon_data[info.base_weapon];
        def.melee[DT_BASH] = rng( weapon.bash_min, weapon.bash_max );
        def.melee[DT_CUT] = rng( weapon.cut_min, weapon.cut_max );
        def.melee[DT_STAB] = rng( weapon.stab_min, weapon.stab_max );
        def.m_to_hit = rng( weapon.to_hit_min, weapon.to_hit_max );
        if( !weapon.tag.empty() ) {
            def.item_tags.insert( weapon.tag );
        }
        // Add an extra weapon perhaps?
        if( one_in( 2 ) ) {
            const artifact_weapon_type select = random_entry_ref( info.extra_weapons );
            if( select != NUM_ARTWEAPS ) {
                const artifact_weapon_datum &weapon = artifact_weapon_data[select];
                def.volume += weapon.volume;
                def.weight += weapon.weight;
                def.melee[DT_BASH] += rng( weapon.bash_min, weapon.bash_max );
                def.melee[DT_CUT] += rng( weapon.cut_min, weapon.cut_max );
                def.melee[DT_STAB] += rng( weapon.stab_min, weapon.stab_max );
                def.m_to_hit += rng( weapon.to_hit_min, weapon.to_hit_max );
                if( !weapon.tag.empty() ) {
                    def.item_tags.insert( weapon.tag );
                }
                def.create_name( std::string( _( weapon.adjective ) ) + " " + _( info.name ) );
            }
        }
        def.description = no_translation(
                              string_format(
                                  _( "This is the %s.\nIt is the only one of its kind.\nIt may have unknown powers; try activating them." ),
                                  def.nname( 1 ) ) );
        // Finally, pick some powers
        art_effect_passive passive_tmp = AEP_NULL;
        art_effect_active active_tmp = AEA_NULL;
        int num_good = 0;
        int num_bad = 0;
        int value = 0;
        std::vector<art_effect_passive> good_effects = fill_good_passive();
        std::vector<art_effect_passive> bad_effects = fill_bad_passive();
        // Wielded effects first
        while( !good_effects.empty() && !bad_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( num_good < 1 || num_bad < 1 || one_in( num_good + 1 ) ||
                 one_in( num_bad + 1 ) || value > 1 ) ) {
            if( value < 1 && one_in( 2 ) ) {
                // Good
                passive_tmp = random_entry_removed( good_effects );
                num_good++;
            } else if( !bad_effects.empty() ) {
                // Bad effect
                passive_tmp = random_entry_removed( bad_effects );
                num_bad++;
            }
            value += passive_effect_cost[passive_tmp];
            def.artifact->effects_wielded.push_back( passive_tmp );
        }
        // Next, carried effects; more likely to be just bad
        num_good = 0;
        num_bad = 0;
        value = 0;
        good_effects = fill_good_passive();
        bad_effects = fill_bad_passive();
        while( one_in( 2 ) && !good_effects.empty() && !bad_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( num_bad < 1 || one_in( num_bad + 1 ) || value > 1 ) ) {
            if( value < 1 && one_in( 3 ) ) {
                // Good
                passive_tmp = random_entry_removed( good_effects );
                num_good++;
            } else {
                // Bad effect
                passive_tmp = random_entry_removed( bad_effects );
                num_bad++;
            }
            value += passive_effect_cost[passive_tmp];
            def.artifact->effects_carried.push_back( passive_tmp );
        }
        // Finally, activated effects; not necessarily good or bad
        num_good = 0;
        num_bad = 0;
        value = 0;
        std::vector<art_effect_active> good_a_effects = fill_good_active();
        std::vector<art_effect_active> bad_a_effects = fill_bad_active();
        while( !good_a_effects.empty() && !bad_a_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( value > 3 || ( num_bad > 0 && num_good == 0 ) ||
                 !one_in( 3 - num_good ) || !one_in( 3 - num_bad ) ) ) {
            if( !one_in( 3 ) && value <= 1 ) {
                // Good effect
                active_tmp = random_entry_removed( good_a_effects );
                num_good++;
                value += active_effect_cost[active_tmp];
            } else {
                // Bad effect
                active_tmp = random_entry_removed( bad_a_effects );
                num_bad++;
                value += active_effect_cost[active_tmp];
            }
            def.artifact->effects_activated.push_back( active_tmp );
            def.tool->max_charges += rng( 1, 3 );
        }
        def.tool->def_charges = def.tool->max_charges;
        // If we have charges, pick a recharge mechanism
        if( def.tool->max_charges > 0 ) {
            def.artifact->charge_type = static_cast<art_charge>( rng( ARTC_NULL + 1, NUM_ARTCS - 1 ) );
        }
        // 1 in 8 chance that it can't recharge!
        if( one_in( 8 ) && num_bad + num_good >= 4 ) {
            def.artifact->charge_type = ARTC_NULL;
        }
        // Maybe pick an extra recharge requirement
        if( one_in( std::max( 1, 6 - num_good ) ) && def.artifact->charge_type != ARTC_NULL ) {
            def.artifact->charge_req = static_cast<art_charge_req>( rng( ACR_NULL + 1, NUM_ACRS - 1 ) );
        }
        // Assign dream data (stored individually so they can be overridden in json)
        def.artifact->dream_msg_unmet  = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].msg_unmet;
        def.artifact->dream_msg_met    = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].msg_met;
        def.artifact->dream_freq_unmet = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].freq_unmet;
        def.artifact->dream_freq_met   = artifact_dream_data[static_cast<int>
                                         ( def.artifact->charge_req )].freq_met;
        // Stronger artifacts have a higher chance of picking their dream
        def.artifact->dream_freq_unmet *= ( 1 + 0.1 * ( num_bad + num_good ) );
        def.artifact->dream_freq_met   *= ( 1 + 0.1 * ( num_bad + num_good ) );
        item_controller->add_item_type( static_cast<itype &>( def ) );
        return def.get_id();
    } else {
        // Generate an armor artifact
        it_artifact_armor def;
        const artifact_armor_form_datum &info = random_entry_ref( artifact_armor_form_data );
        def.create_name( _( info.name ) );
        // Armor is always [
        def.sym = "[";
        def.color = info.color;
        def.materials.push_back( info.material );
        def.volume = info.volume;
        def.weight = info.weight;
        def.melee[DT_BASH] = info.melee_bash;
        def.melee[DT_CUT] = info.melee_cut;
        def.m_to_hit = info.melee_hit;
        def.armor->covers = info.covers;
        def.armor->encumber = info.encumb;
        def.armor->max_encumber = info.max_encumb;
        def.armor->coverage = info.coverage;
        def.armor->thickness = info.thickness;
        def.armor->env_resist = info.env_resist;
        def.armor->warmth = info.warmth;
        def.armor->storage = info.storage;
        std::string description = string_format( info.plural ?
                                  _( "This is the %s.\nThey are the only ones of their kind." ) :
                                  _( "This is the %s.\nIt is the only one of its kind." ), def.nname( 1 ) );
        // Modify the armor further
        if( !one_in( 4 ) ) {
            const artifact_armor_mod mod = random_entry_ref( info.available_mods );
            if( mod != ARMORMOD_NULL ) {
                const artifact_armor_form_datum &modinfo = artifact_armor_mod_data[mod];
                if( modinfo.volume >= 0_ml || def.volume > -modinfo.volume ) {
                    def.volume += modinfo.volume;
                } else {
                    def.volume = 250_ml;
                }
                if( modinfo.weight >= 0_gram || def.weight.value() > std::abs( modinfo.weight.value() ) ) {
                    def.weight += modinfo.weight;
                } else {
                    def.weight = 1_gram;
                }
                def.armor->encumber += modinfo.encumb;
                if( modinfo.coverage > 0 || def.armor->coverage > std::abs( modinfo.coverage ) ) {
                    def.armor->coverage += modinfo.coverage;
                } else {
                    def.armor->coverage = 0;
                }
                if( modinfo.thickness > 0 || def.armor->thickness > std::abs( modinfo.thickness ) ) {
                    def.armor->thickness += modinfo.thickness;
                } else {
                    def.armor->thickness = 0;
                }
                if( modinfo.env_resist > 0 || def.armor->env_resist > std::abs( modinfo.env_resist ) ) {
                    def.armor->env_resist += modinfo.env_resist;
                } else {
                    def.armor->env_resist = 0;
                }
                def.armor->warmth += modinfo.warmth;
                if( modinfo.storage > 0_ml || def.armor->storage > -modinfo.storage ) {
                    def.armor->storage += modinfo.storage;
                } else {
                    def.armor->storage = 0_ml;
                }
                description += string_format( info.plural ?
                                              _( "\nThey are %s" ) :
                                              _( "\nIt is %s" ),
                                              _( modinfo.name ) );
            }
        }
        def.description = no_translation( description );
        // Finally, pick some effects
        int num_good = 0;
        int num_bad = 0;
        int value = 0;
        art_effect_passive passive_tmp = AEP_NULL;
        std::vector<art_effect_passive> good_effects = fill_good_passive();
        std::vector<art_effect_passive> bad_effects = fill_bad_passive();
        while( !good_effects.empty() && !bad_effects.empty() &&
               num_good < 3 && num_bad < 3 &&
               ( num_good < 1 || one_in( num_good * 2 ) || value > 1 ||
                 !one_in( 3 - num_bad ) ) ) {
            if( value < 1 && one_in( 2 ) ) {
                // Good effect
                passive_tmp = random_entry_removed( good_effects );
                num_good++;
            } else {
                // Bad effect
                passive_tmp = random_entry_removed( bad_effects );
                num_bad++;
            }
            value += passive_effect_cost[passive_tmp];
            def.artifact->effects_worn.push_back( passive_tmp );
        }
        item_controller->add_item_type( static_cast<itype &>( def ) );
        return def.get_id();
    }
}
References _, ACR_NULL, active_effect_cost, artifact_weapon_datum::adjective, AEA_NULL, AEP_NULL, itype::armor, ARMORMOD_NULL, ARTC_NULL, itype::artifact, artifact_armor_form_data, artifact_armor_mod_data, artifact_dream_data, artifact_tool_form_data, artifact_weapon_data, artifact_armor_form_datum::available_mods, artifact_tool_form_datum::base_weapon, artifact_weapon_datum::bash_max, artifact_weapon_datum::bash_min, artifact_tool_form_datum::color, artifact_armor_form_datum::color, itype::color, artifact_armor_form_datum::coverage, artifact_armor_form_datum::covers, it_artifact_tool::create_name(), it_artifact_armor::create_name(), artifact_weapon_datum::cut_max, artifact_weapon_datum::cut_min, itype::description, DT_BASH, DT_CUT, DT_STAB, artifact_armor_form_datum::encumb, artifact_armor_form_datum::env_resist, artifact_tool_form_datum::extra_weapons, fill_bad_active(), fill_bad_passive(), fill_good_active(), fill_good_passive(), itype::get_id(), item_controller, itype::item_tags, itype::m_to_hit, artifact_tool_form_datum::material, artifact_armor_form_datum::material, itype::materials, artifact_armor_form_datum::max_encumb, itype::melee, artifact_armor_form_datum::melee_bash, artifact_armor_form_datum::melee_cut, artifact_armor_form_datum::melee_hit, artifact_tool_form_datum::name, artifact_armor_form_datum::name, itype::nname(), no_translation(), NUM_ACRS, NUM_ARTCS, NUM_ARTWEAPS, one_in(), passive_effect_cost, artifact_armor_form_datum::plural, random_entry_ref(), random_entry_removed(), rng(), artifact_weapon_datum::stab_max, artifact_weapon_datum::stab_min, artifact_armor_form_datum::storage, string_format(), artifact_tool_form_datum::sym, itype::sym, artifact_weapon_datum::tag, artifact_armor_form_datum::thickness, artifact_weapon_datum::to_hit_max, artifact_weapon_datum::to_hit_min, itype::tool, units::quantity< V, U >::value(), artifact_weapon_datum::volume, artifact_armor_form_datum::volume, itype::volume, artifact_tool_form_datum::volume_max, artifact_tool_form_datum::volume_min, artifact_armor_form_datum::warmth, artifact_weapon_datum::weight, artifact_armor_form_datum::weight, itype::weight, artifact_tool_form_datum::weight_max, and artifact_tool_form_datum::weight_min.
Referenced by map::spawn_artifact().
new_natural_artifact()
itype_id new_natural_artifact (artifact_natural_property prop)
Definition at line 931 of file artifact.cpp.
{
    // Natural artifacts are always tools.
    it_artifact_tool def;
    // Pick a form
    const artifact_shape_datum &shape_data = random_entry_ref( artifact_shape_data );
    // Pick a property
    const artifact_natural_property property = ( prop > ARTPROP_NULL ? prop :
            static_cast<artifact_natural_property>( rng( ARTPROP_NULL + 1,
                    ARTPROP_MAX - 1 ) ) );
    const artifact_property_datum &property_data = artifact_property_data[property];
    def.sym = ":";
    def.color = c_yellow;
    def.materials.push_back( material_id( "stone" ) );
    def.volume = rng( shape_data.volume_min, shape_data.volume_max );
    def.weight = rng( shape_data.weight_min, shape_data.weight_max );
    def.melee[DT_BASH] = 0;
    def.melee[DT_CUT] = 0;
    def.m_to_hit = 0;
    def.create_name( _( property_data.name ), _( shape_data.name ) );
    def.description = no_translation(
                          string_format( pgettext( "artifact description", "This %1$s %2$s." ),
                                         _( shape_data.desc ), _( property_data.desc ) ) );
    // Three possibilities: good passive + bad passive, good active + bad active,
    // and bad passive + good active
    bool good_passive = false, bad_passive = false,
         good_active  = false, bad_active  = false;
    switch( rng( 1, 3 ) ) {
        case 1:
            good_passive = true;
            bad_passive  = true;
            break;
        case 2:
            good_active = true;
            bad_active  = true;
            break;
        case 3:
            bad_passive = true;
            good_active = true;
            break;
    }
    // This is slowly incremented, allowing for better arts
    int value_to_reach = 0;
    int value = 0;
    art_effect_passive aep_good = AEP_NULL, aep_bad = AEP_NULL;
    art_effect_active  aea_good = AEA_NULL, aea_bad = AEA_NULL;
    do {
        if( good_passive ) {
            aep_good = random_entry_ref( property_data.passive_good );
            if( aep_good == AEP_NULL || one_in( 4 ) ) {
                aep_good = static_cast<art_effect_passive>( rng( AEP_NULL + 1, AEP_SPLIT - 1 ) );
            }
        }
        if( bad_passive ) {
            aep_bad = random_entry_ref( property_data.passive_bad );
            if( aep_bad == AEP_NULL || one_in( 4 ) ) {
                aep_bad = static_cast<art_effect_passive>( rng( AEP_SPLIT + 1, NUM_AEAS - 1 ) );
            }
        }
        if( good_active ) {
            aea_good = random_entry_ref( property_data.active_good );
            if( aea_good == AEA_NULL || one_in( 4 ) ) {
                aea_good = static_cast<art_effect_active>( rng( AEA_NULL + 1, AEA_SPLIT - 1 ) );
            }
        }
        if( bad_active ) {
            aea_bad = random_entry_ref( property_data.active_bad );
            if( aea_bad == AEA_NULL || one_in( 4 ) ) {
                aea_bad = static_cast<art_effect_active>( rng( AEA_SPLIT + 1, NUM_AEAS - 1 ) );
            }
        }
        value = passive_effect_cost[aep_good] + passive_effect_cost[aep_bad] +
                active_effect_cost[aea_good] +  active_effect_cost[aea_bad];
        // Yes, it is intentional that this is 1 the first check
        value_to_reach++;
    } while( value > value_to_reach );
    if( aep_good != AEP_NULL ) {
        def.artifact->effects_carried.push_back( aep_good );
    }
    if( aep_bad != AEP_NULL ) {
        def.artifact->effects_carried.push_back( aep_bad );
    }
    if( aea_good != AEA_NULL ) {
        def.artifact->effects_activated.push_back( aea_good );
    }
    if( aea_bad != AEA_NULL ) {
        def.artifact->effects_activated.push_back( aea_bad );
    }
    // Natural artifacts ALWAYS can recharge
    // (When "implanting" them in a mundane item, this ability may be lost
    if( !def.artifact->effects_activated.empty() ) {
        def.tool->def_charges = def.tool->max_charges = rng( 1, 4 );
        def.artifact->charge_type = static_cast<art_charge>( rng( ARTC_NULL + 1, NUM_ARTCS - 1 ) );
        //Maybe pick an extra recharge requirement
        if( one_in( 6 ) ) {
            def.artifact->charge_req = static_cast<art_charge_req>( rng( ACR_NULL + 1, NUM_ACRS - 1 ) );
        }
    }
    // Assign dream data (stored individually so they can be overridden in json)
    def.artifact->dream_msg_unmet  = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].msg_unmet;
    def.artifact->dream_msg_met    = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].msg_met;
    def.artifact->dream_freq_unmet = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].freq_unmet;
    def.artifact->dream_freq_met   = artifact_dream_data[static_cast<int>
                                     ( def.artifact->charge_req )].freq_met;
    item_controller->add_item_type( static_cast<itype &>( def ) );
    return def.get_id();
}
References _, ACR_NULL, artifact_property_datum::active_bad, active_effect_cost, artifact_property_datum::active_good, AEA_NULL, AEA_SPLIT, AEP_NULL, AEP_SPLIT, ARTC_NULL, itype::artifact, artifact_dream_data, artifact_property_data, artifact_shape_data, ARTPROP_MAX, ARTPROP_NULL, c_yellow, itype::color, it_artifact_tool::create_name(), artifact_shape_datum::desc, artifact_property_datum::desc, itype::description, DT_BASH, DT_CUT, itype::get_id(), item_controller, itype::m_to_hit, itype::materials, itype::melee, artifact_shape_datum::name, artifact_property_datum::name, no_translation(), NUM_ACRS, NUM_AEAS, NUM_ARTCS, one_in(), artifact_property_datum::passive_bad, passive_effect_cost, artifact_property_datum::passive_good, pgettext(), random_entry_ref(), rng(), string_format(), itype::sym, itype::tool, itype::volume, artifact_shape_datum::volume_max, artifact_shape_datum::volume_min, itype::weight, artifact_shape_datum::weight_max, and artifact_shape_datum::weight_min.
Referenced by map::spawn_natural_artifact().
save_artifacts()
bool save_artifacts (const std::string & path)
Definition at line 1277 of file artifact.cpp.
{
    return write_to_file( path, [&]( std::ostream & fout ) {
        JsonOut json( fout, true );
        json.start_array();
        // We only want runtime types, otherwise static artifacts are loaded twice (on init and then on game load)
        for( const itype *e : item_controller->get_runtime_types() ) {
            if( !e->artifact ) {
                continue;
            }
            if( e->tool ) {
                json.write( it_artifact_tool( *e ) );
            } else if( e->armor ) {
                json.write( it_artifact_armor( *e ) );
            }
        }
        json.end_array();
    }, _( "artifact file" ) );
}
References _, JsonOut::end_array(), item_controller, JsonOut::start_array(), JsonOut::write(), and write_to_file().
Referenced by game::save_artifacts().