Cataclysm BN: src/assign.h File Reference
assign.h File Reference
#include <algorithm>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include "calendar.h"
#include "color.h"
#include "damage.h"
#include "debug.h"
#include "json.h"
#include "units.h"
#include "units_serde.h"
Classes
class detail::is_optional_helper< T >
class detail::is_optional_helper< cata::optional< T > >
class is_optional< T >
Namespaces
namespace cata
namespace detail
Macros
#define CATA_SRC_ASSIGN_H
Functions
bool is_strict_enabled (const std::string &src)
Check whether strict checks are enabled for given mod.
void report_strict_violation (const JsonObject &jo, const std::string &message, const std::string &name)
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, int >::type = 0>
bool assign (const JsonObject &jo, const std::string &name, T &val, bool strict=false, T lo=std::numeric_limits< T >::lowest(), T hi=std::numeric_limits< T >::max())
bool assign (const JsonObject &jo, const std::string &name, bool &val, bool strict=false)
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, int >::type = 0>
bool assign (const JsonObject &jo, const std::string &name, std::pair< T, T > &val, bool strict=false, T lo=std::numeric_limits< T >::lowest(), T hi=std::numeric_limits< T >::max())
template<typename T , typename std::enable_if< std::is_class< T >::value &&!is_optional< T >::value, int >::type = 0>
bool assign (const JsonObject &jo, const std::string &name, T &val, bool strict=false)
template<typename T >
std::enable_if< std::is_constructible< T, std::string >::value, bool >::type assign (const JsonObject &jo, const std::string &name, std::set< T > &val, bool=false)
template<typename T >
bool assign_map_from_array (const JsonObject &jo, const std::string &name, T &val, bool=false)
Load map from JSON array of [key, value] pairs.
bool assign (const JsonObject &jo, const std::string &name, units::volume &val, bool strict=false, const units::volume lo=units::volume_min, const units::volume hi=units::volume_max)
bool assign (const JsonObject &jo, const std::string &name, units::mass &val, bool strict=false, const units::mass lo=units::mass_min, const units::mass hi=units::mass_max)
bool assign (const JsonObject &jo, const std::string &name, units::money &val, bool strict=false, const units::money lo=units::money_min, const units::money hi=units::money_max)
bool assign (const JsonObject &jo, const std::string &name, units::energy &val, bool strict=false, const units::energy lo=units::energy_min, const units::energy hi=units::energy_max)
template<typename lvt , typename ut , typename s , typename std::enable_if_t< units::quantity_details< ut >::common_zero_point::value > * = nullptr>
units::quantity< lvt, ut > mult_unit (const JsonObject &, const std::string &, const units::quantity< lvt, ut > &val, const s scalar)
template<typename T , typename F >
bool assign_unit_common (const JsonObject &jo, const std::string &name, T &val, F parse, bool strict, const T lo, const T hi)
bool assign (const JsonObject &jo, const std::string &name, units::probability &val, bool strict=false, const units::probability lo=units::probability_min, const units::probability hi=units::probability_max)
bool assign (const JsonObject &jo, const std::string &name, units::temperature &val, bool strict=false, const units::temperature lo=units::temperature_min, const units::temperature hi=units::temperature_max)
bool assign (const JsonObject &jo, const std::string &name, nc_color &val, const bool strict=false)
template<typename T >
std::enable_if< std::is_same< typenamestd::decay< T >::type, time_duration >::value, bool >::type read_with_factor (const JsonObject &jo, const std::string &name, T &val, const T &factor)
template<typename T >
std::enable_if< std::is_same< typenamestd::decay< T >::type, time_duration >::value, bool >::type assign (const JsonObject &jo, const std::string &name, T &val, bool strict, const T &factor)
template<typename T >
bool assign (const JsonObject &jo, const std::string &name, cata::optional< T > &val, const bool strict=false)
void assign_dmg_relative (damage_instance &out, const damage_instance &val, damage_instance relative, bool &strict)
void assign_dmg_proportional (const JsonObject &jo, const std::string &name, damage_instance &out, const damage_instance &val, damage_instance proportional, bool &strict)
void check_assigned_dmg (const JsonObject &err, const std::string &name, const damage_instance &out, const damage_instance &lo_inst, const damage_instance &hi_inst)
bool assign (const JsonObject &jo, const std::string &name, damage_instance &val, bool strict=false, const damage_instance &lo=damage_instance(DT_NULL, 0.0f, 0.0f, 0.0f, 0.0f), const damage_instance &hi=damage_instance(DT_NULL, float_max, float_max, float_max, float_max))
Variables
constexpr float float_max = std::numeric_limits<float>::max()
Macro Definition Documentation
CATA_SRC_ASSIGN_H
#define CATA_SRC_ASSIGN_H
Definition at line 3 of file assign.h.
Function Documentation
assign() [1/15]
bool assign (const JsonObject & jo, const std::string & name, bool & val, bool strict = false)
Definition at line 16 of file assign.cpp.
{
    bool out;
    if( !jo.read( name, out ) ) {
        return false;
    }
    if( strict && out == val ) {
        report_strict_violation( jo, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References om_direction::name(), JsonObject::read(), and report_strict_violation().
Referenced by it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), ranged_bash_info::deserialize(), map_bash_info::deserialize(), furn_workbench_info::deserialize(), plant_data::deserialize(), Character::load(), activity_type::load(), vehicle_prototype::load(), weather_generator::load(), saw_barrel_actor::load(), saw_stock_actor::load(), weigh_self_actor::load(), ascii_art::load(), disease_type::load(), scent_type::load(), construction::load(), generic_factory< T >::load(), harvest_entry::load(), map_data_common_t::load(), mattack_actor::load(), mission_type::load(), mtype::load(), overmap_land_use_code::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), trap::load(), vpart_info::load(), ter_t::load(), furn_t::load(), mut_transform::load(), material_type::load(), place_trap_actor::data::load(), unpack_actor::load(), change_scent_iuse::load(), salvage_actor::load(), inscribe_actor::load(), cauterize_actor::load(), enzlave_actor::load(), holster_actor::load(), place_trap_actor::load(), emit_actor::load(), deploy_tent_actor::load(), bionic_data::load(), vpart_info::load_engine(), load_mat_burn_data(), mod_management::load_modfile(), vpart_info::load_rotor(), vpart_info::load_wheel(), vpart_info::load_workbench(), and MonsterGroupManager::LoadMonsterGroup().
assign() [2/15]
template<typename T > bool assign (const JsonObject & jo, const std::string & name, cata::optional< T > & val, const bool strict = false) inline
Definition at line 441 of file assign.h.
{
    if( !jo.has_member( name ) ) {
        return false;
    }
    if( jo.has_null( name ) ) {
        val.reset();
        return true;
    }
    if( !val ) {
        val.emplace();
    }
    return assign( jo, name, *val, strict );
}
References assign(), cata::optional< T >::emplace(), JsonObject::has_member(), JsonObject::has_null(), om_direction::name(), and cata::optional< T >::reset().
assign() [3/15]
bool assign (const JsonObject & jo, const std::string & name, damage_instance & val, bool strict = false, const damage_instance & lo = damage_instance(DT_NULL, 0.0f, 0.0f, 0.0f, 0.0f), const damage_instance & hi = damage_instance(DT_NULL, float_max, float_max, float_max, float_max))
Definition at line 434 of file assign.cpp.
{
    // What we'll eventually be returning for the damage instance
    damage_instance out;
    if( jo.has_array( name ) ) {
        out = load_damage_instance_inherit( jo.get_array( name ), val );
    } else if( jo.has_object( name ) ) {
        out = load_damage_instance_inherit( jo.get_object( name ), val );
    } else {
        // Legacy: remove after 0.F
        float amount = 0.0f;
        float arpen = 0.0f;
        float dmg_mult = 1.0f;
        bool with_legacy = false;
        // There will always be either a prop_damage or damage (name)
        if( jo.has_member( name ) ) {
            with_legacy = true;
            amount = jo.get_float( name );
        } else if( jo.has_member( "prop_damage" ) ) {
            dmg_mult = jo.get_float( "prop_damage" );
            with_legacy = true;
        }
        // And there may or may not be armor penetration
        if( jo.has_member( "pierce" ) ) {
            with_legacy = true;
            arpen = jo.get_float( "pierce" );
        }
        if( with_legacy ) {
            out.add_damage( DT_STAB, amount, arpen, 1.0f, dmg_mult );
        }
    }
    // Object via which to report errors which differs for proportional/relative
    // values
    const JsonObject &err = jo;
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Currently, we load only either relative or proportional when loading
    // damage There's no good reason for this, but it's simple for now
    if( relative.has_object( name ) ) {
        assign_dmg_relative(
            out, val, load_damage_instance( relative.get_object( name ) ), strict );
    } else if( relative.has_array( name ) ) {
        assign_dmg_relative(
            out, val, load_damage_instance( relative.get_array( name ) ), strict );
    } else if( proportional.has_object( name ) ) {
        assign_dmg_proportional(
            proportional, name, out, val,
            load_damage_instance( proportional.get_object( name ) ), strict );
    } else if( proportional.has_array( name ) ) {
        assign_dmg_proportional(
            proportional, name, out, val,
            load_damage_instance( proportional.get_array( name ) ), strict );
    } else if( relative.has_member( name ) || relative.has_member( "pierce" )
               || relative.has_member( "prop_damage" ) ) {
        // Legacy: Remove after 0.F
        // It is valid for relative to adjust any of pierce, prop_damage, or
        // damage So check for what it's modifying, and modify that
        float amt = 0.0f;
        float arpen = 0.0f;
        float dmg_mult = 1.0f;
        if( relative.has_member( name ) ) {
            amt = relative.get_float( name );
        }
        if( relative.has_member( "pierce" ) ) {
            arpen = relative.get_float( "pierce" );
        }
        if( relative.has_member( "prop_damage" ) ) {
            dmg_mult = relative.get_float( "prop_damage" );
        }
        assign_dmg_relative(
            out, val, damage_instance( DT_STAB, amt, arpen, 1.0f, dmg_mult ),
            strict );
    } else if( proportional.has_member( name )
               || proportional.has_member( "pierce" )
               || proportional.has_member( "prop_damage" ) ) {
        // Legacy: Remove after 0.F
        // It is valid for proportional to adjust any of pierce, prop_damage, or
        // damage So check if it's modifying any of the things before going on
        // to modify it
        float amt = 0.0f;
        float arpen = 0.0f;
        float dmg_mult = 1.0f;
        if( proportional.has_member( name ) ) {
            amt = proportional.get_float( name );
        }
        if( proportional.has_member( "pierce" ) ) {
            arpen = proportional.get_float( "pierce" );
        }
        if( proportional.has_member( "prop_damage" ) ) {
            dmg_mult = proportional.get_float( "prop_damage" );
        }
        assign_dmg_proportional(
            proportional, name, out, val,
            damage_instance( DT_STAB, amt, arpen, 1.0f, dmg_mult ), strict );
    } else if( !jo.has_member( name ) && !jo.has_member( "prop_damage" ) ) {
        // Straight copy-from, not modified by proportional or relative
        out = val;
        strict = false;
    }
    check_assigned_dmg( err, name, out, lo, hi );
    if( strict && out == val ) {
        report_strict_violation( err,
                                 "cannot assign explicit damage value the same "
                                 "as default or inherited value",
                                 name );
    }
    if( out.damage_units.empty() ) {
        out = damage_instance( DT_BULLET, 0.0f );
    }
    // Now that we've verified everything in out is all good, set val to it
    val = out;
    return true;
}
References damage_instance::add_damage(), JsonObject::allow_omitted_members(), assign_dmg_proportional(), assign_dmg_relative(), check_assigned_dmg(), damage_instance::damage_units, DT_BULLET, DT_STAB, JsonObject::get_array(), JsonObject::get_float(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), cata::hash64_detail::lo, load_damage_instance(), load_damage_instance_inherit(), om_direction::name(), and report_strict_violation().
assign() [4/15]
bool assign (const JsonObject & jo, const std::string & name, nc_color & val, const bool strict = false)
Definition at line 412 of file assign.cpp.
{
    if( !jo.has_member( name ) ) {
        return false;
    }
    const nc_color out = color_from_string( jo.get_string( name ) );
    if( out == c_unset ) {
        jo.throw_error( "invalid color name", name );
    }
    if( strict && out == val ) {
        report_strict_violation( jo,
                                 "cannot assign explicit value the same as "
                                 "default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References c_unset, color_from_string(), JsonObject::get_string(), JsonObject::has_member(), om_direction::name(), report_strict_violation(), and JsonObject::throw_error().
assign() [5/15]
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, int >::type = 0> bool assign (const JsonObject & jo, const std::string & name, std::pair< T, T > & val, bool strict = false, T lo = std::numeric_limits<T>::lowest(), T hi = std::numeric_limits<T>::max())
Definition at line 102 of file assign.h.
{
    std::pair<T, T> out;
    if( jo.has_array( name ) ) {
        auto arr = jo.get_array( name );
        arr.read( 0, out.first );
        arr.read( 1, out.second );
    } else if( jo.read( name, out.first ) ) {
        out.second = out.first;
    } else {
        return false;
    }
    if( out.first > out.second ) {
        std::swap( out.first, out.second );
    }
    if( out.first < lo || out.second > hi ) {
        jo.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( jo, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::get_array(), JsonObject::has_array(), cata::hash64_detail::lo, om_direction::name(), JsonObject::read(), JsonArray::read(), report_strict_violation(), cata::swap(), and JsonObject::throw_error().
assign() [6/15]
template<typename T > std::enable_if< std::is_constructible< T, std::string >::value, bool >::type assign (const JsonObject & jo, const std::string & name, std::set< T > & val, bool = false)
Definition at line 159 of file assign.h.
{
    JsonObject add = jo.get_object( "extend" );
    add.allow_omitted_members();
    JsonObject del = jo.get_object( "delete" );
    del.allow_omitted_members();
    if( jo.has_string( name ) || jo.has_array( name ) ) {
        val = jo.get_tags<T>( name );
        if( add.has_member( name ) || del.has_member( name ) ) {
            // ill-formed to (re)define a value and then extend/delete within same definition
            jo.throw_error( "multiple assignment of value", name );
        }
        return true;
    }
    bool res = false;
    if( add.has_string( name ) || add.has_array( name ) ) {
        auto tags = add.get_tags<T>( name );
        val.insert( tags.begin(), tags.end() );
        res = true;
    }
    if( del.has_string( name ) || del.has_array( name ) ) {
        for( const auto &e : del.get_tags<T>( name ) ) {
            val.erase( e );
        }
        res = true;
    }
    return res;
}
References om_direction::add(), JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::get_tags(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), om_direction::name(), and JsonObject::throw_error().
assign() [7/15]
template<typename T > std::enable_if< std::is_same< typenamestd::decay< T >::type, time_duration >::value, bool >::type assign (const JsonObject & jo, const std::string & name, T & val, bool strict, const T & factor) inline
Definition at line 397 of file assign.h.
{
    T out{};
    double scalar;
    // Object via which to report errors which differs for proportional/relative values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as rules
    // such as +10% are well-formed independent of whether they affect base value
    if( read_with_factor( relative, name, out, factor ) ) {
        err = relative;
        strict = false;
        out = out + val;
    } else if( proportional.read( name, scalar ) ) {
        err = proportional;
        if( scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1", name );
        }
        strict = false;
        out = val * scalar;
    } else if( !read_with_factor( jo, name, out, factor ) ) {
        return false;
    }
    if( strict && out == val ) {
        report_strict_violation( err, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), JsonObject::get_object(), om_direction::name(), JsonObject::read(), read_with_factor(), report_strict_violation(), and JsonObject::throw_error().
assign() [8/15]
template<typename T , typename std::enable_if< std::is_class< T >::value &&!is_optional< T >::value, int >::type = 0> bool assign (const JsonObject & jo, const std::string & name, T & val, bool strict = false)
Definition at line 141 of file assign.h.
{
    T out;
    if( !jo.read( name, out ) ) {
        return false;
    }
    if( strict && out == val ) {
        report_strict_violation( jo, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References om_direction::name(), JsonObject::read(), and report_strict_violation().
assign() [9/15]
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, int >::type = 0> bool assign (const JsonObject & jo, const std::string & name, T & val, bool strict = false, T lo = std::numeric_limits<T>::lowest(), T hi = std::numeric_limits<T>::max())
Definition at line 50 of file assign.h.
{
    T out;
    double scalar;
    // Object via which to report errors which differs for proportional/relative values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as rules
    // such as +10% are well-formed independent of whether they affect base value
    if( relative.read( name, out ) ) {
        err = relative;
        strict = false;
        out += val;
    } else if( proportional.read( name, scalar ) ) {
        err = proportional;
        if( scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1", name );
        }
        strict = false;
        out = val * scalar;
    } else if( !jo.read( name, out ) ) {
        return false;
    }
    if( out < lo || out > hi ) {
        err.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( err, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), JsonObject::get_object(), om_direction::name(), JsonObject::read(), report_strict_violation(), and JsonObject::throw_error().
Referenced by assign().
assign() [10/15]
bool assign (const JsonObject & jo, const std::string & name, units::energy & val, bool strict = false, const units::energy lo = units::energy_min, const units::energy hi = units::energy_max)
Definition at line 261 of file assign.cpp.
{
    const auto parse = [&name]( const JsonObject & obj, units::energy & out ) {
        if( obj.has_int( name ) ) {
            const std::int64_t tmp = obj.get_int( name );
            if( tmp > units::to_kilojoule( units::energy_max ) ) {
                out = units::energy_max;
            } else {
                out = units::from_kilojoule( tmp );
            }
            return true;
        }
        if( obj.has_string( name ) ) {
            out = read_from_json_string<units::energy>( *obj.get_raw( name ),
                    units::energy_units );
            return true;
        }
        return false;
    };
    units::energy out;
    // Object via which to report errors which differs for proportional/relative
    // values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as
    // rules such as +10% are well-formed independent of whether they affect
    // base value
    if( relative.has_member( name ) ) {
        units::energy tmp;
        err = relative;
        if( !parse( err, tmp ) ) {
            err.throw_error( "invalid relative value specified", name );
        }
        strict = false;
        out = val + tmp;
    } else if( proportional.has_member( name ) ) {
        double scalar;
        err = proportional;
        if( !err.read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1",
                             name );
        }
        strict = false;
        out = val * scalar;
    } else if( !parse( jo, out ) ) {
        return false;
    }
    if( out < lo || out > hi ) {
        err.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( err,
                                 "cannot assign explicit value the same as "
                                 "default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), units::energy_max, units::energy_units, units::from_kilojoule(), JsonObject::get_object(), JsonObject::has_member(), om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), JsonObject::throw_error(), and units::to_kilojoule().
assign() [11/15]
bool assign (const JsonObject & jo, const std::string & name, units::mass & val, bool strict = false, const units::mass lo = units::mass_min, const units::mass hi = units::mass_max)
Definition at line 115 of file assign.cpp.
{
    const auto parse = [&name]( const JsonObject & obj, units::mass & out ) {
        if( obj.has_int( name ) ) {
            out = units::from_gram<std::int64_t>( obj.get_int( name ) );
            return true;
        }
        if( obj.has_string( name ) ) {
            out = read_from_json_string<units::mass>( *obj.get_raw( name ),
                    units::mass_units );
            return true;
        }
        return false;
    };
    units::mass out;
    // Object via which to report errors which differs for proportional/relative
    // values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as
    // rules such as +10% are well-formed independent of whether they affect
    // base value
    if( relative.has_member( name ) ) {
        units::mass tmp;
        err = relative;
        if( !parse( err, tmp ) ) {
            err.throw_error( "invalid relative value specified", name );
        }
        strict = false;
        out = val + tmp;
    } else if( proportional.has_member( name ) ) {
        double scalar;
        err = proportional;
        if( !err.read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1",
                             name );
        }
        strict = false;
        out = val * scalar;
    } else if( !parse( jo, out ) ) {
        return false;
    }
    if( out < lo || out > hi ) {
        err.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( err,
                                 "cannot assign explicit value the same as "
                                 "default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), units::mass_units, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), and JsonObject::throw_error().
assign() [12/15]
bool assign (const JsonObject & jo, const std::string & name, units::money & val, bool strict = false, const units::money lo = units::money_min, const units::money hi = units::money_max)
Definition at line 188 of file assign.cpp.
{
    const auto parse = [&name]( const JsonObject & obj, units::money & out ) {
        if( obj.has_int( name ) ) {
            out = units::from_cent( obj.get_int( name ) );
            return true;
        }
        if( obj.has_string( name ) ) {
            out = read_from_json_string<units::money>( *obj.get_raw( name ),
                    units::money_units );
            return true;
        }
        return false;
    };
    units::money out;
    // Object via which to report errors which differs for proportional/relative
    // values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as
    // rules such as +10% are well-formed independent of whether they affect
    // base value
    if( relative.has_member( name ) ) {
        units::money tmp;
        err = relative;
        if( !parse( err, tmp ) ) {
            err.throw_error( "invalid relative value specified", name );
        }
        strict = false;
        out = val + tmp;
    } else if( proportional.has_member( name ) ) {
        double scalar;
        err = proportional;
        if( !err.read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1",
                             name );
        }
        strict = false;
        out = val * scalar;
    } else if( !parse( jo, out ) ) {
        return false;
    }
    if( out < lo || out > hi ) {
        err.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( err,
                                 "cannot assign explicit value the same as "
                                 "default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), units::from_cent(), JsonObject::get_object(), JsonObject::has_member(), units::money_units, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), and JsonObject::throw_error().
assign() [13/15]
bool assign (const JsonObject & jo, const std::string & name, units::probability & val, bool strict = false, const units::probability lo = units::probability_min, const units::probability hi = units::probability_max)
Definition at line 339 of file assign.cpp.
{
    const auto parse = [&name]( const JsonObject & obj, units::probability & out ) {
        if( obj.has_string( name ) ) {
            long double tmp;
            std::string suffix;
            std::istringstream str( obj.get_string( name ) );
            str.imbue( std::locale::classic() );
            str >> tmp >> suffix;
            if( str.peek() != std::istringstream::traits_type::eof() ) {
                obj.throw_error( "syntax error when specifying volume", name );
            }
            if( suffix == "pm" ) {
                out = units::from_one_in_million(
                          static_cast<units::probability::value_type>( tmp ) );
            } else if( suffix == "%" ) {
                out = units::from_percent( tmp );
            } else {
                obj.throw_error( "unrecognized volumetric unit", name );
            }
            return true;
        }
        return false;
    };
    return assign_unit_common( jo, name, val, parse, strict, lo, hi );
}
References assign_unit_common(), units::from_one_in_million(), units::from_percent(), cata::hash64_detail::lo, om_direction::name(), and int_id< T >::obj().
assign() [14/15]
bool assign (const JsonObject & jo, const std::string & name, units::temperature & val, bool strict = false, const units::temperature lo = units::temperature_min, const units::temperature hi = units::temperature_max)
Definition at line 373 of file assign.cpp.
{
    const auto parse = [&name]( const JsonObject & obj, units::temperature & out ) {
        if( obj.has_string( name ) ) {
            long double value;
            std::string suffix;
            std::istringstream str( obj.get_string( name ) );
            str.imbue( std::locale::classic() );
            str >> value >> suffix;
            if( str.peek() != std::istringstream::traits_type::eof() ) {
                obj.throw_error( "syntax error when specifying temperature", name );
            }
            const auto &unit_suffixes = units::temperature_units;
            auto iter = std::find_if(
                            unit_suffixes.begin(), unit_suffixes.end(),
                            [&suffix]( const std::pair<std::string, units::temperature> &
            suffix_value ) {
                return suffix_value.first == suffix;
            } );
            if( iter != unit_suffixes.end() ) {
                out = mult_unit( obj, name, iter->second, value );
            } else {
                obj.throw_error( "unrecognized temperature unit", name );
            }
            return true;
        }
        return false;
    };
    return assign_unit_common( jo, name, val, parse, strict, lo, hi );
}
References assign_unit_common(), cata::hash64_detail::lo, mult_unit(), om_direction::name(), int_id< T >::obj(), and units::temperature_units.
assign() [15/15]
bool assign (const JsonObject & jo, const std::string & name, units::volume & val, bool strict = false, const units::volume lo = units::volume_min, const units::volume hi = units::volume_max)
Definition at line 34 of file assign.cpp.
{
    const auto parse = [&name]( const JsonObject & obj, units::volume & out ) {
        if( obj.has_int( name ) ) {
            out = obj.get_int( name ) * units::legacy_volume_factor;
            return true;
        }
        if( obj.has_string( name ) ) {
            units::volume::value_type tmp;
            std::string suffix;
            std::istringstream str( obj.get_string( name ) );
            str.imbue( std::locale::classic() );
            str >> tmp >> suffix;
            if( str.peek() != std::istringstream::traits_type::eof() ) {
                obj.throw_error( "syntax error when specifying volume", name );
            }
            if( suffix == "ml" ) {
                out = units::from_milliliter( tmp );
            } else if( suffix == "L" ) {
                out = units::from_milliliter( tmp * 1000 );
            } else {
                obj.throw_error( "unrecognized volumetric unit", name );
            }
            return true;
        }
        return false;
    };
    units::volume out;
    // Object via which to report errors which differs for proportional/relative values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as rules
    // such as +10% are well-formed independent of whether they affect base value
    if( relative.has_member( name ) ) {
        units::volume tmp;
        err = relative;
        if( !parse( err, tmp ) ) {
            err.throw_error( "invalid relative value specified", name );
        }
        strict = false;
        out = val + tmp;
    } else if( proportional.has_member( name ) ) {
        double scalar;
        err = proportional;
        if( !err.read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1", name );
        }
        strict = false;
        out = val * scalar;
    } else if( !parse( jo, out ) ) {
        return false;
    }
    if( out < lo || out > hi ) {
        err.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( err, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), units::from_milliliter(), JsonObject::get_object(), JsonObject::has_member(), units::legacy_volume_factor, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), and JsonObject::throw_error().
assign_dmg_proportional()
void assign_dmg_proportional (const JsonObject & jo, const std::string & name, damage_instance & out, const damage_instance & val, damage_instance proportional, bool & strict)
Definition at line 627 of file assign.cpp.
{
    for( const damage_unit &val_dmg : val.damage_units ) {
        for( damage_unit &scalar : proportional.damage_units ) {
            if( scalar.type != val_dmg.type ) {
                continue;
            }
            // Do not require strict parsing for relative and proportional
            // values as rules such as +10% are well-formed independent of
            // whether they affect base value
            strict = false;
            // Can't have negative percent, and 100% is pointless
            // If it's 0, it wasn't loaded
            if( scalar.amount == 1 || scalar.amount < 0 ) {
                jo.throw_error(
                    "Proportional damage multiplier must be a positive number "
                    "other than 1",
                    name );
            }
            // If it's 0, it wasn't loaded
            if( scalar.res_pen < 0 || scalar.res_pen == 1 ) {
                jo.throw_error(
                    "Proportional armor penetration multiplier must be a "
                    "positive number other than 1",
                    name );
            }
            // It wasn't loaded, so set it 100%
            if( scalar.res_pen == 0 ) {
                scalar.res_pen = 1.0f;
            }
            // Ditto
            if( scalar.amount == 0 ) {
                scalar.amount = 1.0f;
            }
            // If it's 1, it wasn't loaded (or was loaded as 1)
            if( scalar.res_mult <= 0 ) {
                jo.throw_error(
                    "Proportional armor penetration multiplier must be a "
                    "positive number",
                    name );
            }
            // If it's 1, it wasn't loaded (or was loaded as 1)
            if( scalar.damage_multiplier <= 0 ) {
                jo.throw_error(
                    "Proportional damage multiplier must be a positive number",
                    name );
            }
            damage_unit out_dmg( scalar.type, 0.0f );
            out_dmg.amount = val_dmg.amount * scalar.amount;
            out_dmg.res_pen = val_dmg.res_pen * scalar.res_pen;
            out_dmg.res_mult = val_dmg.res_mult * scalar.res_mult;
            out_dmg.damage_multiplier =
                val_dmg.damage_multiplier * scalar.damage_multiplier;
            out.add( out_dmg );
        }
    }
}
References damage_instance::add(), damage_unit::amount, damage_unit::damage_multiplier, damage_instance::damage_units, om_direction::name(), damage_unit::res_mult, damage_unit::res_pen, JsonObject::throw_error(), and damage_unit::type.
Referenced by assign().
assign_dmg_relative()
void assign_dmg_relative (damage_instance & out, const damage_instance & val, damage_instance relative, bool & strict)
Definition at line 701 of file assign.cpp.
{
    for( const damage_unit &val_dmg : val.damage_units ) {
        for( damage_unit &tmp : relative.damage_units ) {
            if( tmp.type != val_dmg.type ) {
                continue;
            }
            // Do not require strict parsing for relative and proportional
            // values as rules such as +10% are well-formed independent of
            // whether they affect base value
            strict = false;
            // res_mult is set to 1 if it's not specified. Set it to zero so we
            // don't accidentally add to it
            if( tmp.res_mult == 1.0f ) {
                tmp.res_mult = 0;
            }
            // Same for damage_multiplier
            if( tmp.damage_multiplier == 1.0f ) {
                tmp.damage_multiplier = 0;
            }
            damage_unit out_dmg( tmp.type, 0.0f );
            out_dmg.amount = tmp.amount + val_dmg.amount;
            out_dmg.res_pen = tmp.res_pen + val_dmg.res_pen;
            out_dmg.res_mult = tmp.res_mult + val_dmg.res_mult;
            out_dmg.damage_multiplier =
                tmp.damage_multiplier + val_dmg.damage_multiplier;
            out.add( out_dmg );
        }
    }
}
References damage_instance::add(), damage_unit::amount, damage_unit::damage_multiplier, damage_instance::damage_units, damage_unit::res_mult, damage_unit::res_pen, and damage_unit::type.
Referenced by assign().
assign_map_from_array()
template<typename T > bool assign_map_from_array (const JsonObject & jo, const std::string & name, T & val, bool = false)
Load map from JSON array of [key, value] pairs.
Supports extend by pair and delete by key.
Definition at line 200 of file assign.h.
{
    using K = typename T::key_type;
    using V = typename T::mapped_type;
    JsonObject add = jo.get_object( "extend" );
    add.allow_omitted_members();
    JsonObject del = jo.get_object( "delete" );
    del.allow_omitted_members();
    if( jo.has_array( name ) ) {
        val.clear();
        std::vector<std::pair<K, V>> tmp;
        jo.get_raw( name )->read( tmp, true );
        for( const auto &it : tmp ) {
            val.insert( std::move( it ) );
        }
        if( add.has_member( name ) || del.has_member( name ) ) {
            // ill-formed to (re)define a value and then extend/delete within same definition
            jo.throw_error( "multiple assignment of value", name );
        }
        return true;
    }
    bool res = false;
    if( add.has_array( name ) ) {
        std::vector<std::pair<K, V>> tmp;
        add.get_raw( name )->read( tmp, true );
        for( const auto &it : tmp ) {
            val[std::move( it.first )] = std::move( it.second );
        }
        res = true;
    }
    if( del.has_array( name ) ) {
        std::vector<K> tmp;
        del.get_raw( name )->read( tmp, true );
        for( const auto &it : tmp ) {
            val.erase( it );
        }
        res = true;
    }
    return res;
}
References om_direction::add(), JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::get_raw(), JsonObject::has_array(), JsonObject::has_member(), avatar_action::move(), om_direction::name(), JsonIn::read(), and JsonObject::throw_error().
Referenced by construction::load(), and bionic_data::load().
assign_unit_common()
template<typename T , typename F > bool assign_unit_common (const JsonObject & jo, const std::string & name, T & val, F parse, bool strict, const T lo, const T hi) inline
Definition at line 300 of file assign.h.
{
    T out;
    // Object via which to report errors which differs for proportional/relative values
    JsonObject err = jo;
    err.allow_omitted_members();
    JsonObject relative = jo.get_object( "relative" );
    relative.allow_omitted_members();
    JsonObject proportional = jo.get_object( "proportional" );
    proportional.allow_omitted_members();
    // Do not require strict parsing for relative and proportional values as rules
    // such as +10% are well-formed independent of whether they affect base value
    if( relative.has_member( name ) ) {
        T tmp;
        err = relative;
        if( !parse( err, tmp ) ) {
            err.throw_error( "invalid relative value specified", name );
        }
        strict = false;
        out = val + tmp;
    } else if( proportional.has_member( name ) ) {
        double scalar;
        err = proportional;
        if( !err.read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
            err.throw_error( "multiplier must be a positive number other than 1", name );
        }
        strict = false;
        out = mult_unit( err, name, val, scalar );
    } else if( !parse( jo, out ) ) {
        return false;
    }
    if( out < lo || out > hi ) {
        err.throw_error( "value outside supported range", name );
    }
    if( strict && out == val ) {
        report_strict_violation( err, "cannot assign explicit value the same as default or inherited value",
                                 name );
    }
    val = out;
    return true;
}
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), mult_unit(), om_direction::name(), JsonObject::read(), report_strict_violation(), and JsonObject::throw_error().
Referenced by assign().
check_assigned_dmg()
void check_assigned_dmg (const JsonObject & err, const std::string & name, const damage_instance & out, const damage_instance & lo_inst, const damage_instance & hi_inst)
Definition at line 569 of file assign.cpp.
{
    for( const damage_unit &out_dmg : out.damage_units ) {
        auto lo_iter = std::find_if(
                           lo_inst.damage_units.begin(), lo_inst.damage_units.end(),
        [&out_dmg]( const damage_unit & du ) {
            return du.type == out_dmg.type || du.type == DT_NULL;
        } );
        auto hi_iter = std::find_if(
                           hi_inst.damage_units.begin(), hi_inst.damage_units.end(),
        [&out_dmg]( const damage_unit & du ) {
            return du.type == out_dmg.type || du.type == DT_NULL;
        } );
        if( lo_iter == lo_inst.damage_units.end() ) {
            err.throw_error(
                "Min damage type used in assign does not match damage type "
                "assigned",
                name );
        }
        if( hi_iter == hi_inst.damage_units.end() ) {
            err.throw_error(
                "Max damage type used in assign does not match damage type "
                "assigned",
                name );
        }
        const damage_unit &hi_dmg = *hi_iter;
        const damage_unit &lo_dmg = *lo_iter;
        if( out_dmg.amount < lo_dmg.amount || out_dmg.amount > hi_dmg.amount ) {
            err.throw_error( "value for damage outside supported range", name );
        }
        if( out_dmg.res_pen < lo_dmg.res_pen
            || out_dmg.res_pen > hi_dmg.res_pen ) {
            err.throw_error(
                "value for armor penetration outside supported range", name );
        }
        if( out_dmg.res_mult < lo_dmg.res_mult
            || out_dmg.res_mult > hi_dmg.res_mult ) {
            err.throw_error(
                "value for armor penetration multiplier outside supported "
                "range",
                name );
        }
        if( out_dmg.damage_multiplier < lo_dmg.damage_multiplier
            || out_dmg.damage_multiplier > hi_dmg.damage_multiplier ) {
            err.throw_error(
                "value for damage multiplier outside supported range", name );
        }
    }
}
References damage_unit::amount, damage_unit::damage_multiplier, damage_instance::damage_units, om_direction::name(), damage_unit::res_mult, damage_unit::res_pen, and JsonObject::throw_error().
Referenced by assign().
is_strict_enabled()
bool is_strict_enabled (const std::string & src)
Check whether strict checks are enabled for given mod.
Definition at line 368 of file mod_manager.cpp.
{
    return src == mod_management::get_default_core_content_pack().str();
}
References mod_management::get_default_core_content_pack(), and string_id< T >::str().
Referenced by anonymous_namespace{mapdata.cpp}::is_json_check_strict(), generic_factory< T >::load(), harvest_entry::load(), mattack_actor::load(), mission_type::load(), mtype::load(), overmap_land_use_code::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), rotatable_symbols::load(), bionic_data::load(), Item_factory::load(), Item_factory::load_ammo(), Item_factory::load_basic_info(), and Item_factory::load_comestible().
mult_unit()
template<typename lvt , typename ut , typename s , typename std::enable_if_t< units::quantity_details< ut >::common_zero_point::value > * = nullptr> units::quantity< lvt, ut > mult_unit (const JsonObject & err, const std::string & name, const units::quantity< lvt, ut > & val, const s scalar) inline
Definition at line 284 of file assign.h.
{
    return val * scalar;
}
Referenced by assign(), and assign_unit_common().
read_with_factor()
template<typename T > std::enable_if< std::is_same< typenamestd::decay< T >::type, time_duration >::value, bool >::type read_with_factor (const JsonObject & jo, const std::string & name, T & val, const T & factor) inline
Definition at line 375 of file assign.h.
{
    int tmp;
    if( jo.read( name, tmp, false ) ) {
        // JSON contained a raw number -> apply factor
        val = tmp * factor;
        return true;
    } else if( jo.has_string( name ) ) {
        // JSON contained a time duration string -> no factor
        val = read_from_json_string<time_duration>( *jo.get_raw( name ), time_duration::units );
        return true;
    }
    return false;
}
References JsonObject::get_raw(), JsonObject::has_string(), om_direction::name(), JsonObject::read(), and time_duration::units.
Referenced by assign().
report_strict_violation()
void report_strict_violation (const JsonObject & jo, const std::string & message, const std::string & name)
Definition at line 3 of file assign.cpp.
{
    try {
        // Let the json class do the formatting, it includes the context of the JSON data.
        jo.throw_error( message, name );
    } catch( const JsonError &err ) {
        // And catch the exception so the loading continues like normal.
        debugmsg( "(json-error)\n%s", err.what() );
    }
}
References debugmsg, mapgen_defer::message, om_direction::name(), and JsonObject::throw_error().
Referenced by assign(), and assign_unit_common().
Variable Documentation
float_max
constexpr float float_max = std::numeric_limits<float>::max() constexpr
Definition at line 457 of file assign.h.