Cataclysm BN: src/auto_pickup.cpp File Reference
auto_pickup.cpp File Reference
#include "auto_pickup.h"
#include <algorithm>
#include <cstddef>
#include <functional>
#include <memory>
#include <utility>
#include "avatar.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "game.h"
#include "input.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "json.h"
#include "material.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
Functions
static bool check_special_rule (const std::vector< material_id > &materials, const std::string &rule)
auto_pickup::player_settings & get_auto_pickup ()
Function Documentation
check_special_rule()
bool check_special_rule (const std::vector< material_id > & materials, const std::string & rule) static
Definition at line 571 of file auto_pickup.cpp.
{
    char type = ' ';
    std::vector<std::string> filter;
    if( rule[1] == ':' ) {
        type = rule[0];
        filter = string_split( rule.substr( 2 ), ',' );
    }
    if( filter.empty() || materials.empty() ) {
        return false;
    }
    if( type == 'm' ) {
        return std::any_of( materials.begin(), materials.end(), [&filter]( const material_id & mat ) {
            return std::any_of( filter.begin(), filter.end(), [&mat]( const std::string & search ) {
                return lcmatch( mat->name(), search );
            } );
        } );
    } else if( type == 'M' ) {
        return std::all_of( materials.begin(), materials.end(), [&filter]( const material_id & mat ) {
            return std::any_of( filter.begin(), filter.end(), [&mat]( const std::string & search ) {
                return lcmatch( mat->name(), search );
            } );
        } );
    }
    return false;
}
References string_split(), and type.
Referenced by auto_pickup::rule_list::create_rule(), auto_pickup::rule_list::refresh_map_items(), and auto_pickup::rule::test_pattern().
get_auto_pickup()
auto_pickup::player_settings & get_auto_pickup ()
Definition at line 38 of file auto_pickup.cpp.
{
    static auto_pickup::player_settings single_instance;
    return single_instance;
}
Referenced by advanced_inventory::display(), game::handle_action(), game::load(), game::load_static_data(), main_menu::opening_screen(), examine_item_menu::run(), game::save(), select_autopickup_items(), and game::start_game().