Cataclysm BN: src/auto_note.cpp File Reference
auto_note.cpp File Reference
#include "auto_note.h"
#include <iostream>
#include <memory>
#include "cata_utility.h"
#include "color.h"
#include "cursesdef.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "game.h"
#include "generic_factory.h"
#include "input.h"
#include "json.h"
#include "map_extras.h"
#include "options.h"
#include "output.h"
#include "point.h"
#include "translations.h"
#include "ui_manager.h"
Namespaces
namespace auto_notes
Functions
auto_notes::auto_note_settings & get_auto_notes_settings ()
Function Documentation
get_auto_notes_settings()
auto_notes::auto_note_settings & get_auto_notes_settings ()
Definition at line 386 of file auto_note.cpp.
{
    static auto_notes::auto_note_settings staticSettings;
    return staticSettings;
}
Referenced by MapExtras::apply_function(), auto_notes::auto_note_manager_gui::auto_note_manager_gui(), game::handle_action(), game::load(), game::save(), auto_notes::auto_note_manager_gui::show(), and game::start_game().