Cataclysm BN: src/avatar.cpp File Reference
avatar.cpp File Reference
#include "avatar.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cstdlib>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <unordered_map>
#include <utility>
#include "action.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "character_stat.h"
#include "clzones.h"
#include "color.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "game.h"
#include "game_constants.h"
#include "help.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "kill_tracker.h"
#include "magic_teleporter_list.h"
#include "map.h"
#include "map_memory.h"
#include "martialarts.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "morale.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "pathfinding.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "ranged.h"
#include "recipe.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
Functions
static const std::string flag_FIX_FARSIGHT ("FIX_FARSIGHT")
static void skim_book_msg (const item &book, avatar &u)
avatar & get_avatar ()
Variables
static const activity_id ACT_READ ("ACT_READ")
static const bionic_id bio_eye_optic ("bio_eye_optic")
static const bionic_id bio_memory ("bio_memory")
static const bionic_id bio_watch ("bio_watch")
static const efftype_id effect_alarm_clock ("alarm_clock")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_slept_through_alarm ("slept_through_alarm")
static const itype_id itype_guidebook ("guidebook")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_HYPEROPIC ("HYPEROPIC")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_PROF_DICEMASTER ("PROF_DICEMASTER")
static const std::array< int, 20 > xp_cutoffs
Function Documentation
flag_FIX_FARSIGHT()
static const std::string flag_FIX_FARSIGHT ("FIX_FARSIGHT") static
Referenced by avatar::get_book_reader().
get_avatar()
avatar & get_avatar ()
Definition at line 102 of file avatar.cpp.
{
    return g->u;
}
References avatar::player_map_memory, and Character::pos().
Referenced by mdefense::acidsplash(), computer_session::action_emerg_ref_center(), advanced_inventory_pane::add_items_from_area(), aim_activity_actor::aim_activity_actor(), item::basic_info(), can_butcher_at(), veh_interact::cant_do(), debug_menu::character_edit_menu(), basecamp_action_components::choose_components(), item::color_in_inventory(), item::component_info(), overmap_ui::display(), item::display_name(), pickup::do_pickup(), aim_activity_actor::do_turn(), construct::done_vehicle(), overmap_ui::draw_ascii(), draw_can_craft_indicator(), draw_cone_aoe_curses(), draw_env_compact(), draw_lighting_classic(), draw_loc_labels(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), map_data_common_t::extended_description(), generate_weather_anim_frame(), sfx::get_heard_volume(), get_heat_radiation(), kill_tracker::get_kills_text(), item::gun_info(), vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), avatar_action::move(), kill_tracker::notify(), peek_related_recipe(), debug_menu::pick_character(), pick_one_up(), pldrive(), teleporter_callback::refresh(), avatar_action::reload(), avatar_action::reload_item(), avatar_action::reload_weapon(), avatar_action::reload_wielded(), DefaultRemovePartHandler::removed(), aim_activity_actor::restore_view(), examine_item_menu::run(), select_crafting_recipe(), map::shoot(), speed_description(), spell_panel(), iexamine::translocator(), aim_activity_actor::unload_RAS_weapon(), inscribe_actor::use(), weather_effect::wet_player(), avatar_action::wield(), and mdefense::zapback().
skim_book_msg()
static void skim_book_msg (const item & book, avatar & u) static
Definition at line 666 of file avatar.cpp.
{
    if( !book.type->book ) {
        return;
    }
    const auto &reading = book.type->book;
    const skill_id &skill = reading->skill;
    if( skill && u.get_skill_level_object( skill ).can_train() ) {
        add_msg( m_info, _( "Can bring your %s skill to %d." ),
                 skill.obj().name(), reading->level );
        if( reading->req != 0 ) {
            add_msg( m_info, _( "Requires %s level %d to understand." ),
                     skill.obj().name(), reading->req );
        }
    }
    if( reading->intel != 0 ) {
        add_msg( m_info, _( "Requires intelligence of %d to easily read." ), reading->intel );
    }
    //It feels wrong to use a pointer to *this, but I can't find any other player pointers in this method.
    if( character_funcs::get_book_fun_for( u, book ) != 0 ) {
        add_msg( m_info, _( "Reading this book affects your morale by %d" ),
                 character_funcs::get_book_fun_for( u, book ) );
    }
    if( book.type->use_methods.count( "MA_MANUAL" ) ) {
        const matype_id style_to_learn = martial_art_learned_from( *book.type );
        add_msg( m_info, _( "You can learn %s style from it." ), style_to_learn->name );
        add_msg( m_info, _( "This fighting style is %s to learn." ),
                 martialart_difficulty( style_to_learn ) );
        add_msg( m_info, _( "It would be easier to master if you'd have skill expertise in %s." ),
                 style_to_learn->primary_skill->name() );
        add_msg( m_info, _( "A training session with this book takes %s" ),
                 to_string( time_duration::from_minutes( reading->time ) ) );
    } else {
        add_msg( m_info, vgettext( "A chapter of this book takes %d minute to read.",
                                   "A chapter of this book takes %d minutes to read.", reading->time ),
                 reading->time );
    }
    std::vector<std::string> recipe_list;
    for( const auto &elem : reading->recipes ) {
        // If the player knows it, they recognize it even if it's not clearly stated.
        if( elem.is_hidden() && !u.knows_recipe( elem.recipe ) ) {
            continue;
        }
        recipe_list.push_back( elem.name );
    }
    if( !recipe_list.empty() ) {
        std::string recipe_line =
            string_format( vgettext( "This book contains %1$zu crafting recipe: %2$s",
                                     "This book contains %1$zu crafting recipes: %2$s",
                                     recipe_list.size() ),
                           recipe_list.size(),
                           enumerate_as_string( recipe_list ) );
        add_msg( m_info, recipe_line );
    }
    if( recipe_list.size() != reading->recipes.size() ) {
        add_msg( m_info, _( "It might help you figuring out some more recipes." ) );
    }
    add_msg( _( "You note that you have a copy of %s in your possession." ), book.type_name() );
}
References _, add_msg(), itype::book, SkillLevel::can_train(), enumerate_as_string(), time_duration::from_minutes(), character_funcs::get_book_fun_for(), Character::get_skill_level_object(), Character::knows_recipe(), m_info, martial_art_learned_from(), martialart_difficulty(), martialart::name, Skill::name(), string_id< T >::obj(), martialart::primary_skill, string_format(), to_string(), item::type, item::type_name(), itype::use_methods, and vgettext().
Referenced by avatar::do_read(), and avatar::read().
Variable Documentation
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
Referenced by avatar::read().
bio_eye_optic
const bionic_id bio_eye_optic("bio_eye_optic") ("bio_eye_optic") static
Referenced by avatar::get_book_reader().
bio_memory
const bionic_id bio_memory("bio_memory") ("bio_memory") static
Referenced by avatar::do_read().
bio_watch
const bionic_id bio_watch("bio_watch") ("bio_watch") static
Referenced by avatar::wake_up().
effect_alarm_clock
const efftype_id effect_alarm_clock("alarm_clock") ("alarm_clock") static
Referenced by avatar::wake_up().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by avatar::get_book_reader().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by avatar::wake_up().
effect_slept_through_alarm
const efftype_id effect_slept_through_alarm("slept_through_alarm") ("slept_through_alarm") static
Referenced by avatar::wake_up().
itype_guidebook
const itype_id itype_guidebook("guidebook") ("guidebook") static
Referenced by avatar::read().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by avatar::disp_morale().
trait_HYPEROPIC
const trait_id trait_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by avatar::get_book_reader().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by avatar::get_book_reader().
trait_PROF_DICEMASTER
const trait_id trait_PROF_DICEMASTER("PROF_DICEMASTER") ("PROF_DICEMASTER") static
Referenced by avatar::read(), and avatar::time_to_read().
xp_cutoffs
const std::array<int, 20> xp_cutoffs static
Initial value:
= { {
        300, 900, 2700, 6500, 14000,
        23000, 34000, 48000, 64000, 85000,
        100000, 120000, 140000, 165000, 195000,
        225000, 265000, 305000, 355000, 405000
    }
}
Definition at line 1022 of file avatar.cpp.
Referenced by avatar::free_upgrade_points(), and avatar::kill_xp_for_next_point().