Cataclysm BN: src/avatar_functions.cpp File Reference
avatar_functions.cpp File Reference
#include "avatar_functions.h"
#include "avatar.h"
#include "character_functions.h"
#include "field_type.h"
#include "map.h"
#include "mapdata.h"
#include "trap.h"
#include "vpart_position.h"
#include "vehicle.h"
#include "veh_type.h"
Namespaces
namespace avatar_funcs
Functions
void avatar_funcs::try_to_sleep (avatar &you, const time_duration &dur=30_minutes)
Handles sleep attempts by the player, starts ACT_TRY_SLEEP activity.
Variables
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_THRESH_SPIDER ("THRESH_SPIDER")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
static const trait_id trait_WEB_SPINNER ("WEB_SPINNER")
static const trait_id trait_WEB_WALKER ("WEB_WALKER")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
static const bionic_id bio_soporific ("bio_soporific")
Variable Documentation
bio_soporific
const bionic_id bio_soporific("bio_soporific") ("bio_soporific") static
Referenced by avatar_funcs::try_to_sleep().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by avatar_funcs::try_to_sleep().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by avatar_funcs::try_to_sleep().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by avatar_funcs::try_to_sleep().
trait_THRESH_SPIDER
const trait_id trait_THRESH_SPIDER("THRESH_SPIDER") ("THRESH_SPIDER") static
Referenced by avatar_funcs::try_to_sleep().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by avatar_funcs::try_to_sleep().
trait_WEB_SPINNER
const trait_id trait_WEB_SPINNER("WEB_SPINNER") ("WEB_SPINNER") static
Referenced by avatar_funcs::try_to_sleep().
trait_WEB_WALKER
const trait_id trait_WEB_WALKER("WEB_WALKER") ("WEB_WALKER") static
Referenced by avatar_funcs::try_to_sleep().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by avatar_funcs::try_to_sleep().