Cataclysm BN: src/bionics.cpp File Reference
bionics.cpp File Reference
#include "bionics.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <forward_list>
#include <iterator>
#include <list>
#include <memory>
#include <type_traits>
#include "action.h"
#include "assign.h"
#include "avatar.h"
#include "avatar_action.h"
#include "ballistics.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_martial_arts.h"
#include "character_stat.h"
#include "colony.h"
#include "color.h"
#include "consistency_report.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "effect.h"
#include "enum_conversions.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field_type.h"
#include "game.h"
#include "generic_factory.h"
#include "handle_liquid.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "json.h"
#include "line.h"
#include "magic.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "memorial_logger.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mutation.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "pldata.h"
#include "point.h"
#include "projectile.h"
#include "requirements.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "teleport.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
Namespaces
namespace anonymous_namespace{bionics.cpp}
Functions
static const std::string flag_ALLOWS_NATURAL_ATTACKS ("ALLOWS_NATURAL_ATTACKS")
static const std::string flag_AURA ("AURA")
static const std::string flag_CABLE_SPOOL ("CABLE_SPOOL")
static const std::string flag_NO_UNWIELD ("NO_UNWIELD")
static const std::string flag_PERPETUAL ("PERPETUAL")
static const std::string flag_PERSONAL ("PERSONAL")
static const std::string flag_SAFE_FUEL_OFF ("SAFE_FUEL_OFF")
static const std::string flag_SEALED ("SEALED")
static const std::string flag_SEMITANGIBLE ("SEMITANGIBLE")
std::vector< bodypart_id > get_occupied_bodyparts (const bionic_id &bid)
List of bodyparts occupied by a bionic.
static void force_comedown (effect &eff)
static bool attempt_recharge (Character &p, bionic &bio, units::energy &amount, int factor=1, int rate=1)
int bionic_manip_cos (float adjusted_skill, int bionic_difficulty)
std::string list_occupied_bps (const bionic_id &bio_id, const std::string &intro, const bool each_bp_on_new_line)
std::vector< bionic_id > bionics_cancelling_trait (const std::vector< bionic_id > &bios, const trait_id &tid)
Variables
static const activity_id ACT_OPERATION ("ACT_OPERATION")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_assisted ("assisted")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_bloodworms ("bloodworms")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_cocaine_high ("cocaine_high")
static const efftype_id effect_datura ("datura")
static const efftype_id effect_dermatik ("dermatik")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_heating_bionic ("heating_bionic")
static const efftype_id effect_iodine ("iodine")
static const efftype_id effect_meth ("meth")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_operating ("operating")
static const efftype_id effect_pblue ("pblue")
static const efftype_id effect_pkill_l ("pkill_l")
static const efftype_id effect_pkill1 ("pkill1")
static const efftype_id effect_pkill2 ("pkill2")
static const efftype_id effect_pkill3 ("pkill3")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_badpoison ("badpoison")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_stung ("stung")
static const efftype_id effect_teleglow ("teleglow")
static const efftype_id effect_took_flumed ("took_flumed")
static const efftype_id effect_took_prozac ("took_prozac")
static const efftype_id effect_took_prozac_bad ("took_prozac_bad")
static const efftype_id effect_took_xanax ("took_xanax")
static const efftype_id effect_under_op ("under_operation")
static const efftype_id effect_visuals ("visuals")
static const efftype_id effect_weed_high ("weed_high")
static const efftype_id effect_infected ("infected")
static const itype_id fuel_type_battery ("battery")
static const itype_id fuel_type_metabolism ("metabolism")
static const itype_id fuel_type_muscle ("muscle")
static const itype_id fuel_type_sun_light ("sunlight")
static const itype_id fuel_type_wind ("wind")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_anesthetic ("anesthetic")
static const itype_id itype_burnt_out_bionic ("burnt_out_bionic")
static const itype_id itype_radiocontrol ("radiocontrol")
static const itype_id itype_remotevehcontrol ("remotevehcontrol")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_UPS_off ("UPS_off")
static const itype_id itype_water_clean ("water_clean")
static const fault_id fault_bionic_nonsterile ("fault_bionic_nonsterile")
static const skill_id skill_computer ("computer")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_mechanics ("mechanics")
static const bionic_id bio_adrenaline ("bio_adrenaline")
static const bionic_id bio_advreactor ("bio_advreactor")
static const bionic_id bio_ads ("bio_ads")
static const bionic_id bio_blood_anal ("bio_blood_anal")
static const bionic_id bio_blood_filter ("bio_blood_filter")
static const bionic_id bio_cqb ("bio_cqb")
static const bionic_id bio_earplugs ("bio_earplugs")
static const bionic_id bio_ears ("bio_ears")
static const bionic_id bio_emp ("bio_emp")
static const bionic_id bio_evap ("bio_evap")
static const bionic_id bio_eye_optic ("bio_eye_optic")
static const bionic_id bio_flashbang ("bio_flashbang")
static const bionic_id bio_geiger ("bio_geiger")
static const bionic_id bio_gills ("bio_gills")
static const bionic_id bio_hydraulics ("bio_hydraulics")
static const bionic_id bio_jointservo ("bio_jointservo")
static const bionic_id bio_lighter ("bio_lighter")
static const bionic_id bio_lockpick ("bio_lockpick")
static const bionic_id bio_magnet ("bio_magnet")
static const bionic_id bio_meteorologist ("bio_meteorologist")
static const bionic_id bio_nanobots ("bio_nanobots")
static const bionic_id bio_painkiller ("bio_painkiller")
static const bionic_id bio_plutdump ("bio_plutdump")
static const bionic_id bio_power_storage ("bio_power_storage")
static const bionic_id bio_power_storage_mkII ("bio_power_storage_mkII")
static const bionic_id bio_probability_travel ("bio_probability_travel")
static const bionic_id bio_radscrubber ("bio_radscrubber")
static const bionic_id bio_reactor ("bio_reactor")
static const bionic_id bio_remote ("bio_remote")
static const bionic_id bio_resonator ("bio_resonator")
static const bionic_id bio_shockwave ("bio_shockwave")
static const bionic_id bio_teleport ("bio_teleport")
static const bionic_id bio_time_freeze ("bio_time_freeze")
static const bionic_id bio_tools ("bio_tools")
static const bionic_id bio_torsionratchet ("bio_torsionratchet")
static const bionic_id bio_water_extractor ("bio_water_extractor")
static const bionic_id bionic_TOOLS_EXTEND ("bio_tools_extend")
static const bionic_id afs_bio_dopamine_stimulators ("afs_bio_dopamine_stimulators")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_DEBUG_BIONICS ("DEBUG_BIONICS")
static const trait_id trait_MASOCHIST ("MASOCHIST")
static const trait_id trait_MASOCHIST_MED ("MASOCHIST_MED")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PROF_AUTODOC ("PROF_AUTODOC")
static const trait_id trait_PROF_MED ("PROF_MED")
static const trait_id trait_THRESH_MEDICAL ("THRESH_MEDICAL")
static const flag_str_id flag_BIONIC_GUN ("BIONIC_GUN")
static const flag_str_id flag_BIONIC_WEAPON ("BIONIC_WEAPON")
static const flag_str_id flag_BIONIC_TOGGLED ("BIONIC_TOGGLED")
constexpr int BIONIC_NOITEM_DIFFICULTY = 12
generic_factory< bionic_data > anonymous_namespace{bionics.cpp}::bionic_factory ("bionic")
std::vector< bionic_id > anonymous_namespace{bionics.cpp}::faulty_bionics
Function Documentation
attempt_recharge()
static bool attempt_recharge (Character & p, bionic & bio, units::energy & amount, int factor = 1, int rate = 1) static
Parameters
p the player
bio the bionic that is meant to be recharged.
amount the amount of power that is to be spent recharging the bionic.
factor multiplies the power cost per turn.
rate divides the number of turns we may charge (rate of 2 discharges in half the time).
Returns
indicates whether we successfully charged the bionic.
Definition at line 1506 of file bionics.cpp.
{
    const bionic_data &info = bio.info();
    units::energy power_cost = info.power_over_time * factor;
    bool recharged = false;
    if( power_cost > 0_kJ ) {
        if( p.get_power_level() >= power_cost ) {
            // Set the recharging cost and charge the bionic.
            amount = power_cost;
            // This is our first turn of charging, so subtract a turn from the recharge delay.
            bio.charge_timer = info.charge_time - rate;
            recharged = true;
        }
    }
    return recharged;
}
References bionic_data::charge_time, bionic::charge_timer, Character::get_power_level(), bionic::info(), and bionic_data::power_over_time.
Referenced by Character::process_bionic().
bionic_manip_cos()
int bionic_manip_cos (float adjusted_skill, int bionic_difficulty)
Definition at line 1886 of file bionics.cpp.
{
    if( g->u.has_trait( trait_DEBUG_BIONICS ) ) {
        return 100;
    }
    int chance_of_success = 0;
    // we will base chance_of_success on a ratio of skill and difficulty
    // when skill=difficulty, this gives us 1.  skill < difficulty gives a fraction.
    float skill_difficulty_parameter = static_cast<float>( adjusted_skill /
                                       ( 4.0 * bionic_difficulty ) );
    // when skill == difficulty, chance_of_success is 50%. Chance of success drops quickly below that
    // to reserve bionics for characters with the appropriate skill.  For more difficult bionics, the
    // curve flattens out just above 80%
    chance_of_success = static_cast<int>( ( 100 * skill_difficulty_parameter ) /
                                          ( skill_difficulty_parameter + std::sqrt( 1 / skill_difficulty_parameter ) ) );
    return chance_of_success;
}
References g, and trait_DEBUG_BIONICS.
Referenced by best_installer(), Character::can_install_bionics(), Character::can_uninstall_bionic(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), bionic_uninstall_preset::get_failure_chance(), Character::install_bionics(), game::save_cyborg(), and Character::uninstall_bionic().
bionics_cancelling_trait()
std::vector< bionic_id > bionics_cancelling_trait (const std::vector< bionic_id > & bios, const trait_id & tid)
Definition at line 2815 of file bionics.cpp.
{
    // Vector of bionics to return
    std::vector<bionic_id> bionics_cancelling;
    // Search through the vector of of bionics, and see if the trait is cancelled by one of them
    for( const bionic_id &bid : bios ) {
        for( const trait_id &trait : bid->canceled_mutations ) {
            if( trait == tid ) {
                bionics_cancelling.emplace_back( bid );
            }
        }
    }
    return bionics_cancelling;
}
Referenced by set_traits().
flag_ALLOWS_NATURAL_ATTACKS()
static const std::string flag_ALLOWS_NATURAL_ATTACKS ("ALLOWS_NATURAL_ATTACKS") static
Referenced by Character::get_effective_efficiency().
flag_AURA()
static const std::string flag_AURA ("AURA") static
Referenced by Character::get_effective_efficiency().
flag_CABLE_SPOOL()
static const std::string flag_CABLE_SPOOL ("CABLE_SPOOL") static
Referenced by Character::activate_bionic(), Character::consume_remote_fuel(), and Character::find_remote_fuel().
flag_NO_UNWIELD()
static const std::string flag_NO_UNWIELD ("NO_UNWIELD") static
Referenced by Character::activate_bionic(), and npc::check_or_use_weapon_cbm().
flag_PERPETUAL()
static const std::string flag_PERPETUAL ("PERPETUAL") static
Referenced by Character::burn_fuel(), Character::passive_power_gen(), and Character::process_bionic().
flag_PERSONAL()
static const std::string flag_PERSONAL ("PERSONAL") static
Referenced by Character::get_effective_efficiency().
flag_SAFE_FUEL_OFF()
static const std::string flag_SAFE_FUEL_OFF ("SAFE_FUEL_OFF") static
Referenced by Character::burn_fuel(), and bionic::toggle_safe_fuel_mod().
flag_SEALED()
static const std::string flag_SEALED ("SEALED") static
Referenced by Character::activate_bionic().
flag_SEMITANGIBLE()
static const std::string flag_SEMITANGIBLE ("SEMITANGIBLE") static
Referenced by Character::get_effective_efficiency().
force_comedown()
static void force_comedown (effect & eff) static
Definition at line 442 of file bionics.cpp.
{
    if( eff.is_null() || eff.get_effect_type() == nullptr || eff.get_duration() <= 1_turns ) {
        return;
    }
    eff.set_duration( std::min( eff.get_duration(), eff.get_int_dur_factor() ) );
}
References effect::get_duration(), effect::get_effect_type(), effect::get_int_dur_factor(), effect::is_null(), and effect::set_duration().
Referenced by Character::activate_bionic().
get_occupied_bodyparts()
std::vector< bodypart_id > get_occupied_bodyparts (const bionic_id & bid)
List of bodyparts occupied by a bionic.
Definition at line 231 of file bionics.cpp.
{
    std::vector<bodypart_id> parts;
    for( const std::pair<const bodypart_str_id, int> &element : bid->occupied_bodyparts ) {
        if( element.second > 0 ) {
            parts.push_back( element.first.id() );
        }
    }
    return parts;
}
References bionic_data::occupied_bodyparts.
Referenced by bionic_install_preset::get_denial(), and activity_handlers::operation_do_turn().
list_occupied_bps()
std::string list_occupied_bps (const bionic_id & bio_id, const std::string & intro, const bool each_bp_on_new_line)
Definition at line 2468 of file bionics.cpp.
{
    if( bio_id->occupied_bodyparts.empty() ) {
        return "";
    }
    std::string desc = intro;
    for( const std::pair<const bodypart_str_id, int> &elem : bio_id->occupied_bodyparts ) {
        desc += ( each_bp_on_new_line ? "\n" : " " );
        //~ <Bodypart name> (<number of occupied slots> slots);
        desc += string_format( _( "%s (%i slots);" ),
                               body_part_name_as_heading( elem.first->token, 1 ),
                               elem.second );
    }
    return desc;
}
References _, body_part_name_as_heading(), bionic_data::occupied_bodyparts, and string_format().
Referenced by item::bionic_info(), and draw_description().
Variable Documentation
ACT_OPERATION
const activity_id ACT_OPERATION("ACT_OPERATION") ("ACT_OPERATION") static
Referenced by Character::install_bionics(), and Character::uninstall_bionic().
afs_bio_dopamine_stimulators
const bionic_id afs_bio_dopamine_stimulators("afs_bio_dopamine_stimulators") ("afs_bio_dopamine_stimulators") static
Referenced by Character::process_bionic().
bio_adrenaline
const bionic_id bio_adrenaline("bio_adrenaline") ("bio_adrenaline") static
Referenced by Character::activate_bionic().
bio_ads
const bionic_id bio_ads("bio_ads") ("bio_ads") static
Referenced by Character::deactivate_bionic(), and Character::process_bionic().
bio_advreactor
const bionic_id bio_advreactor("bio_advreactor") ("bio_advreactor") static
Referenced by Character::can_uninstall_bionic().
bio_blood_anal
const bionic_id bio_blood_anal("bio_blood_anal") ("bio_blood_anal") static
Referenced by Character::activate_bionic().
bio_blood_filter
const bionic_id bio_blood_filter("bio_blood_filter") ("bio_blood_filter") static
Referenced by Character::activate_bionic().
bio_cqb
const bionic_id bio_cqb("bio_cqb") ("bio_cqb") static
Referenced by Character::activate_bionic(), and Character::deactivate_bionic().
bio_earplugs
const bionic_id bio_earplugs("bio_earplugs") ("bio_earplugs") static
Referenced by Character::activate_bionic().
bio_ears
const bionic_id bio_ears("bio_ears") ("bio_ears") static
Referenced by Character::activate_bionic(), and Character::add_bionic().
bio_emp
const bionic_id bio_emp("bio_emp") ("bio_emp") static
Referenced by Character::activate_bionic().
bio_evap
const bionic_id bio_evap("bio_evap") ("bio_evap") static
Referenced by Character::activate_bionic(), and Character::process_bionic().
bio_eye_optic
const bionic_id bio_eye_optic("bio_eye_optic") ("bio_eye_optic") static
Referenced by Character::can_uninstall_bionic().
bio_flashbang
const bionic_id bio_flashbang("bio_flashbang") ("bio_flashbang") static
Referenced by Character::activate_bionic().
bio_geiger
const bionic_id bio_geiger("bio_geiger") ("bio_geiger") static
Referenced by Character::activate_bionic().
bio_gills
const bionic_id bio_gills("bio_gills") ("bio_gills") static
Referenced by Character::process_bionic().
bio_hydraulics
const bionic_id bio_hydraulics("bio_hydraulics") ("bio_hydraulics") static
Referenced by Character::activate_bionic(), and Character::process_bionic().
bio_jointservo
const bionic_id bio_jointservo("bio_jointservo") ("bio_jointservo") static
Referenced by Character::activate_bionic().
bio_lighter
const bionic_id bio_lighter("bio_lighter") ("bio_lighter") static
Referenced by Character::activate_bionic().
bio_lockpick
const bionic_id bio_lockpick("bio_lockpick") ("bio_lockpick") static
Referenced by Character::activate_bionic().
bio_magnet
const bionic_id bio_magnet("bio_magnet") ("bio_magnet") static
Referenced by Character::activate_bionic().
bio_meteorologist
const bionic_id bio_meteorologist("bio_meteorologist") ("bio_meteorologist") static
Referenced by Character::activate_bionic().
bio_nanobots
const bionic_id bio_nanobots("bio_nanobots") ("bio_nanobots") static
Referenced by Character::process_bionic().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by Character::has_enough_anesth(), and Character::process_bionic().
bio_plutdump
const bionic_id bio_plutdump("bio_plutdump") ("bio_plutdump") static
Referenced by Character::activate_bionic().
bio_power_storage
const bionic_id bio_power_storage("bio_power_storage") ("bio_power_storage") static
Referenced by Character::add_bionic(), and Character::amount_of_storage_bionics().
bio_power_storage_mkII
const bionic_id bio_power_storage_mkII("bio_power_storage_mkII") ("bio_power_storage_mkII") static
Referenced by Character::add_bionic(), and Character::amount_of_storage_bionics().
bio_probability_travel
const bionic_id bio_probability_travel("bio_probability_travel") ("bio_probability_travel") static
Referenced by Character::activate_bionic().
bio_radscrubber
const bionic_id bio_radscrubber("bio_radscrubber") ("bio_radscrubber") static
Referenced by Character::activate_bionic().
bio_reactor
const bionic_id bio_reactor("bio_reactor") ("bio_reactor") static
Referenced by Character::can_uninstall_bionic().
bio_remote
const bionic_id bio_remote("bio_remote") ("bio_remote") static
Referenced by Character::activate_bionic(), Character::deactivate_bionic(), and Character::process_bionic().
bio_resonator
const bionic_id bio_resonator("bio_resonator") ("bio_resonator") static
Referenced by Character::activate_bionic().
bio_shockwave
const bionic_id bio_shockwave("bio_shockwave") ("bio_shockwave") static
Referenced by Character::activate_bionic().
bio_teleport
const bionic_id bio_teleport("bio_teleport") ("bio_teleport") static
Referenced by Character::activate_bionic().
bio_time_freeze
const bionic_id bio_time_freeze("bio_time_freeze") ("bio_time_freeze") static
Referenced by Character::activate_bionic().
bio_tools
const bionic_id bio_tools("bio_tools") ("bio_tools") static
Referenced by Character::activate_bionic(), Character::add_bionic(), and Character::deactivate_bionic().
bio_torsionratchet
const bionic_id bio_torsionratchet("bio_torsionratchet") ("bio_torsionratchet") static
Referenced by Character::activate_bionic().
bio_water_extractor
const bionic_id bio_water_extractor("bio_water_extractor") ("bio_water_extractor") static
Referenced by Character::activate_bionic().
BIONIC_NOITEM_DIFFICULTY
constexpr int BIONIC_NOITEM_DIFFICULTY = 12 constexpr
Definition at line 209 of file bionics.cpp.
Referenced by Character::can_uninstall_bionic(), and Character::uninstall_bionic().
bionic_TOOLS_EXTEND
const bionic_id bionic_TOOLS_EXTEND("bio_tools_extend") ("bio_tools_extend") static
Referenced by Character::deactivate_bionic().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by Character::activate_bionic().
effect_assisted
const efftype_id effect_assisted("assisted") ("assisted") static
Referenced by Character::bionics_adjusted_skill().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by Character::process_bionic().
effect_badpoison
const efftype_id effect_badpoison("badpoison") ("badpoison") static
Referenced by Character::activate_bionic().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::process_bionic().
effect_bloodworms
const efftype_id effect_bloodworms("bloodworms") ("bloodworms") static
Referenced by Character::activate_bionic().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by Character::activate_bionic().
effect_cocaine_high
const efftype_id effect_cocaine_high("cocaine_high") ("cocaine_high") static
Referenced by Character::activate_bionic().
effect_datura
const efftype_id effect_datura("datura") ("datura") static
Referenced by Character::activate_bionic().
effect_dermatik
const efftype_id effect_dermatik("dermatik") ("dermatik") static
Referenced by Character::activate_bionic().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by Character::activate_bionic().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by Character::activate_bionic().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by Character::activate_bionic().
effect_heating_bionic
const efftype_id effect_heating_bionic("heating_bionic") ("heating_bionic") static
Referenced by Character::heat_emission().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by Character::do_damage_for_bionic_failure().
effect_iodine
const efftype_id effect_iodine("iodine") ("iodine") static
Referenced by Character::activate_bionic().
effect_meth
const efftype_id effect_meth("meth") ("meth") static
Referenced by Character::activate_bionic().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::introduce_into_anesthesia(), and Character::uninstall_bionic().
effect_operating
const efftype_id effect_operating("operating") ("operating") static
Referenced by Character::uninstall_bionic().
effect_pblue
const efftype_id effect_pblue("pblue") ("pblue") static
Referenced by Character::activate_bionic().
effect_pkill1
const efftype_id effect_pkill1("pkill1") ("pkill1") static
Referenced by Character::activate_bionic().
effect_pkill2
const efftype_id effect_pkill2("pkill2") ("pkill2") static
Referenced by Character::activate_bionic().
effect_pkill3
const efftype_id effect_pkill3("pkill3") ("pkill3") static
Referenced by Character::activate_bionic().
effect_pkill_l
const efftype_id effect_pkill_l("pkill_l") ("pkill_l") static
Referenced by Character::activate_bionic().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by Character::activate_bionic().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Character::uninstall_bionic().
effect_stung
const efftype_id effect_stung("stung") ("stung") static
Referenced by Character::activate_bionic().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by Character::activate_bionic().
effect_took_flumed
const efftype_id effect_took_flumed("took_flumed") ("took_flumed") static
Referenced by Character::activate_bionic().
effect_took_prozac
const efftype_id effect_took_prozac("took_prozac") ("took_prozac") static
Referenced by Character::activate_bionic().
effect_took_prozac_bad
const efftype_id effect_took_prozac_bad("took_prozac_bad") ("took_prozac_bad") static
Referenced by Character::activate_bionic().
effect_took_xanax
const efftype_id effect_took_xanax("took_xanax") ("took_xanax") static
Referenced by Character::activate_bionic().
effect_under_op
const efftype_id effect_under_op("under_operation") ("under_operation") static
Referenced by Character::do_damage_for_bionic_failure(), Character::install_bionics(), and Character::uninstall_bionic().
effect_visuals
const efftype_id effect_visuals("visuals") ("visuals") static
Referenced by Character::activate_bionic().
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by Character::activate_bionic().
fault_bionic_nonsterile
const fault_id fault_bionic_nonsterile("fault_bionic_nonsterile") ("fault_bionic_nonsterile") static
Referenced by Character::perform_uninstall(), and Character::uninstall_bionic().
flag_BIONIC_GUN
const flag_str_id flag_BIONIC_GUN("BIONIC_GUN") ("BIONIC_GUN") static
Referenced by Character::activate_bionic(), bionic_data::check(), and npc::check_or_use_weapon_cbm().
flag_BIONIC_TOGGLED
const flag_str_id flag_BIONIC_TOGGLED("BIONIC_TOGGLED") ("BIONIC_TOGGLED") static
Referenced by Character::activate_bionic(), Character::deactivate_bionic(), and bionic_data::load().
flag_BIONIC_WEAPON
const flag_str_id flag_BIONIC_WEAPON("BIONIC_WEAPON") ("BIONIC_WEAPON") static
Referenced by Character::activate_bionic(), bionic_data::check(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), and Character::uninstall_bionic().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by Character::find_remote_fuel().
fuel_type_metabolism
const itype_id fuel_type_metabolism("metabolism") ("metabolism") static
Referenced by Character::burn_fuel().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by Character::burn_fuel(), and Character::passive_power_gen().
fuel_type_sun_light
const itype_id fuel_type_sun_light("sunlight") ("sunlight") static
Referenced by Character::burn_fuel(), Character::find_remote_fuel(), Character::passive_power_gen(), and Character::reset_remote_fuel().
fuel_type_wind
const itype_id fuel_type_wind("wind") ("wind") static
Referenced by Character::burn_fuel(), and Character::passive_power_gen().
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
Referenced by Character::consume_remote_fuel(), and Character::find_remote_fuel().
itype_anesthetic
const itype_id itype_anesthetic("anesthetic") ("anesthetic") static
Referenced by Character::uninstall_bionic().
itype_burnt_out_bionic
const itype_id itype_burnt_out_bionic("burnt_out_bionic") ("burnt_out_bionic") static
Referenced by Character::perform_uninstall(), and Character::uninstall_bionic().
itype_radiocontrol
const itype_id itype_radiocontrol("radiocontrol") ("radiocontrol") static
Referenced by Character::deactivate_bionic().
itype_remotevehcontrol
const itype_id itype_remotevehcontrol("remotevehcontrol") ("remotevehcontrol") static
Referenced by Character::deactivate_bionic().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by npc::check_or_use_weapon_cbm().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by Character::consume_remote_fuel(), and Character::find_remote_fuel().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by Character::activate_bionic().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by Character::can_install_bionics(), Character::can_uninstall_bionic(), Character::install_bionics(), and Character::uninstall_bionic().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by Character::can_install_bionics(), Character::can_uninstall_bionic(), Character::install_bionics(), and Character::uninstall_bionic().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by Character::can_install_bionics(), Character::can_uninstall_bionic(), Character::install_bionics(), and Character::uninstall_bionic().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by Character::can_install_bionics(), Character::can_uninstall_bionic(), Character::install_bionics(), and Character::uninstall_bionic().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by Character::introduce_into_anesthesia().
trait_DEBUG_BIONICS
const trait_id trait_DEBUG_BIONICS("DEBUG_BIONICS") ("DEBUG_BIONICS") static
Referenced by bionic_manip_cos(), Character::has_enough_anesth(), Character::install_bionics(), Character::introduce_into_anesthesia(), and Character::uninstall_bionic().
trait_MASOCHIST
const trait_id trait_MASOCHIST("MASOCHIST") ("MASOCHIST") static
Referenced by Character::introduce_into_anesthesia().
trait_MASOCHIST_MED
const trait_id trait_MASOCHIST_MED("MASOCHIST_MED") ("MASOCHIST_MED") static
Referenced by Character::introduce_into_anesthesia().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by Character::has_enough_anesth().
trait_PROF_AUTODOC
const trait_id trait_PROF_AUTODOC("PROF_AUTODOC") ("PROF_AUTODOC") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
trait_PROF_MED
const trait_id trait_PROF_MED("PROF_MED") ("PROF_MED") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
trait_THRESH_MEDICAL
const trait_id trait_THRESH_MEDICAL("THRESH_MEDICAL") ("THRESH_MEDICAL") static
Referenced by Character::introduce_into_anesthesia().