Cataclysm BN: src/bodypart.h File Reference
bodypart.h File Reference
#include <array>
#include <bitset>
#include <cstddef>
#include <initializer_list>
#include <string>
#include "int_id.h"
#include "string_id.h"
#include "translations.h"
Classes
struct enum_traits< body_part >
struct enum_traits< side >
struct body_part_type
class bodypart
class body_part_set
Macros
#define CATA_SRC_BODYPART_H
Typedefs
using bodypart_str_id = string_id< body_part_type >
using bodypart_id = int_id< body_part_type >
Enumerations
enum body_part : int {
bp_torso = 0 , bp_head , bp_eyes , bp_mouth ,
bp_arm_l , bp_arm_r , bp_hand_l , bp_hand_r ,
bp_leg_l , bp_leg_r , bp_foot_l , bp_foot_r ,
num_bp
}
enum class side : int { BOTH , LEFT , RIGHT , num_sides }
Functions
template<typename T >
bool operator< (body_part a, T b)
const bodypart_str_id & convert_bp (body_part bp)
Returns the new id for old token.
side opposite_side (side s)
Returns the opposite side.
std::string body_part_name (body_part bp, int number=1)
Returns the matching name of the body_part token.
std::string body_part_name (const bodypart_id &bp, int number=1)
std::string body_part_name_accusative (body_part bp, int number=1)
Returns the matching accusative name of the body_part token, i.e.
std::string body_part_name_accusative (const bodypart_id &bp, int number=1)
std::string body_part_name_as_heading (body_part bp, int number)
Returns the name of the body parts in a context where the name is used as a heading or title e.g.
std::string body_part_name_as_heading (const bodypart_id &bp, int number)
std::string body_part_hp_bar_ui_text (const bodypart_id &bp)
Returns the body part text to be displayed in the HP bar.
std::string encumb_text (body_part bp)
Returns the matching encumbrance text for a given body_part token.
body_part random_body_part (bool main_parts_only=false)
Returns a random body_part token.
body_part mutate_to_main_part (body_part bp)
Returns the matching main body_part that corresponds to the input; i.e.
body_part opposite_body_part (body_part bp)
Returns the opposite body part (limb on the other side)
body_part get_body_part_token (const std::string &id)
Returns the matching body_part token from the corresponding body_part string.
Variables
const bodypart_str_id body_part_head
const bodypart_str_id body_part_eyes
const bodypart_str_id body_part_mouth
const bodypart_str_id body_part_torso
const bodypart_str_id body_part_arm_l
const bodypart_str_id body_part_arm_r
const bodypart_str_id body_part_hand_l
const bodypart_str_id body_part_hand_r
const bodypart_str_id body_part_leg_l
const bodypart_str_id body_part_foot_l
const bodypart_str_id body_part_leg_r
const bodypart_str_id body_part_foot_r
constexpr std::array< body_part, 12 > all_body_parts
Contains all valid body_part values in the order they are defined in.
const std::array< size_t, 12 > bp_aiOther = {{0, 1, 2, 3, 5, 4, 7, 6, 9, 8, 11, 10}}
Macro Definition Documentation
CATA_SRC_BODYPART_H
#define CATA_SRC_BODYPART_H
Definition at line 3 of file bodypart.h.
Typedef Documentation
bodypart_id
using bodypart_id = int_id<body_part_type>
Definition at line 23 of file bodypart.h.
bodypart_str_id
using bodypart_str_id = string_id<body_part_type>
Definition at line 22 of file bodypart.h.
Enumeration Type Documentation
body_part
enum body_part : int
Enumerator
bp_torso
bp_head
bp_eyes
bp_mouth
bp_arm_l
bp_arm_r
bp_hand_l
bp_hand_r
bp_leg_l
bp_leg_r
bp_foot_l
bp_foot_r
num_bp
Definition at line 39 of file bodypart.h.
               : int {
    bp_torso = 0,
    bp_head,
    bp_eyes,
    bp_mouth,
    bp_arm_l,
    bp_arm_r,
    bp_hand_l,
    bp_hand_r,
    bp_leg_l,
    bp_leg_r,
    bp_foot_l,
    bp_foot_r,
    num_bp
};
side
enum class side : int strong
Enumerator
BOTH
LEFT
RIGHT
num_sides
Definition at line 66 of file bodypart.h.
                : int {
    BOTH,
    LEFT,
    RIGHT,
    num_sides
};
Function Documentation
body_part_hp_bar_ui_text()
std::string body_part_hp_bar_ui_text (const bodypart_id & bp)
Returns the body part text to be displayed in the HP bar.
Definition at line 353 of file bodypart.cpp.
{
    return _( bp->hp_bar_ui_text );
}
References _.
Referenced by blood_magic(), draw_health_classic(), draw_limb2(), draw_limb_narrow(), and draw_limb_wide().
body_part_name() [1/2]
std::string body_part_name (body_part bp, int number = 1)
Returns the matching name of the body_part token.
Definition at line 317 of file bodypart.cpp.
{
    return body_part_name( convert_bp( bp ), number );
}
References body_part_name(), and convert_bp().
Referenced by iexamine::autodoc(), Character::block_hit(), body_part_name(), npc::complain(), trapfunc::crossbow(), Character::deal_damage(), effect::disp_desc(), effect::disp_name(), mattack::flesh_golem(), Character::hardcoded_effects(), mattack::longswipe(), mattack::lunge(), Character::mend(), memorial_logger::notify(), Character::reduce_healing_effect(), Character::regen(), trapfunc::shotgun(), Character::suffer_from_sunburn(), Character::suffer_water_damage(), mattack::tentacle(), Character::update_bodytemp(), and Character::wear_item().
body_part_name() [2/2]
std::string body_part_name (const bodypart_id & bp, int number = 1)
Definition at line 322 of file bodypart.cpp.
{
    // See comments in `body_part_type::load` about why these two strings are
    // not a single translation object with plural enabled.
    return number > 1 ? bp->name_multiple.translated() : bp->name.translated();
}
body_part_name_accusative() [1/2]
std::string body_part_name_accusative (body_part bp, int number = 1)
Returns the matching accusative name of the body_part token, i.e.
"Shrapnel hits your X". These are identical to body_part_name above in English, but not in some other languages.
Definition at line 329 of file bodypart.cpp.
{
    return body_part_name_accusative( convert_bp( bp ), number );
}
References body_part_name_accusative(), and convert_bp().
Referenced by mattack::acid_barf(), character_funcs::add_pain_msg(), mattack::bio_op_impale(), mattack::bio_op_takedown(), body_part_name_accusative(), anonymous_namespace{armor_layers.cpp}::body_part_names(), melee_actor::call(), mattack::dermatik(), explosion_handler::do_blast(), explosion_handler::do_blast_new(), Character::do_damage_for_bionic_failure(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::growplants(), Character::hardcoded_effects(), mattack::longswipe(), mattack::lunge(), monster::melee_attack(), melee_actor::on_damage(), activity_handlers::operation_do_turn(), trapfunc::pit_glass(), trapfunc::pit_spikes(), game::place_player(), map::player_in_field(), ranged::print_dmg_msg(), Character::process_one_effect(), trapfunc::snare_heavy(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::tentacle(), and mattack::vine().
body_part_name_accusative() [2/2]
std::string body_part_name_accusative (const bodypart_id & bp, int number = 1)
Definition at line 334 of file bodypart.cpp.
{
    // See comments in `body_part_type::load` about why these two strings are
    // not a single translation object with plural enabled.
    return number > 1 ? bp->accusative_multiple.translated() : bp->accusative.translated();
}
body_part_name_as_heading() [1/2]
std::string body_part_name_as_heading (body_part bp, int number)
Returns the name of the body parts in a context where the name is used as a heading or title e.g.
"Left Arm".
Definition at line 341 of file bodypart.cpp.
{
    return body_part_name_as_heading( convert_bp( bp ), number );
}
References body_part_name_as_heading(), and convert_bp().
Referenced by item::bionic_info(), body_part_name_as_heading(), Character::can_install_bionics(), Character::extended_description(), list_occupied_bps(), character_display::print_encumbrance(), show_armor_layers_ui(), and show_bionics_ui().
body_part_name_as_heading() [2/2]
std::string body_part_name_as_heading (const bodypart_id & bp, int number)
Definition at line 346 of file bodypart.cpp.
{
    // See comments in `body_part_type::load` about why these two strings are
    // not a single translation object with plural enabled.
    return number > 1 ? bp->name_as_heading_multiple.translated() : bp->name_as_heading.translated();
}
convert_bp()
const bodypart_str_id & convert_bp (body_part bp)
Returns the new id for old token.
Definition at line 185 of file bodypart.cpp.
{
    static const std::vector<bodypart_str_id> body_parts = {
        bodypart_str_id( "torso" ),
        bodypart_str_id( "head" ),
        bodypart_str_id( "eyes" ),
        bodypart_str_id( "mouth" ),
        bodypart_str_id( "arm_l" ),
        bodypart_str_id( "arm_r" ),
        bodypart_str_id( "hand_l" ),
        bodypart_str_id( "hand_r" ),
        bodypart_str_id( "leg_l" ),
        bodypart_str_id( "leg_r" ),
        bodypart_str_id( "foot_l" ),
        bodypart_str_id( "foot_r" ),
        bodypart_str_id::NULL_ID()
    };
    if( bp > num_bp || bp < bp_torso ) {
        debugmsg( "Invalid body part token %d", bp );
        return body_parts[ num_bp ];
    }
    return body_parts[static_cast<size_t>( bp )];
}
References bp_torso, debugmsg, string_id< body_part_type >::NULL_ID(), and num_bp.
Referenced by mattack::acid_barf(), Creature::add_effect(), Creature::add_env_effect(), iexamine::autodoc(), body_part_name(), body_part_name_accusative(), body_part_name_as_heading(), spell::bp_is_affected(), map::burn_body_part(), melee_actor::call(), Character::can_swap(), Character::can_wear(), body_part_type::check_consistency(), item::covers(), Creature::deal_melee_hit(), draw_limb_health(), heal_actor::finish_using(), mattack::fungus_fortify(), effect::get_bp(), get_bp(), Creature::get_effect(), mattack::growplants(), Character::hardcoded_effects(), Creature::has_effect(), Creature::has_effect_with_flag(), Character::hitall(), Character::impact(), character_funcs::is_bp_immune_to(), Character::is_immune_field(), Creature::load(), item::on_wear(), player_morale::on_worn_item_washed(), pick_part_to_heal(), map::player_in_field(), Character::process_one_effect(), Character::regen(), Creature::remove_effect(), player_morale::set_worn(), Character::update_bodytemp(), heal_actor::use_healing_item(), npc::wear_if_wanted(), and weather_effect::wet_player().
encumb_text()
std::string encumb_text (body_part bp)
Returns the matching encumbrance text for a given body_part token.
Definition at line 358 of file bodypart.cpp.
{
    const std::string &txt = get_bp( bp ).encumb_text;
    return !txt.empty() ? _( txt ) : txt;
}
References _, body_part_type::encumb_text, and get_bp().
Referenced by Character::wear_item().
get_body_part_token()
body_part get_body_part_token (const std::string & id)
Returns the matching body_part token from the corresponding body_part string.
Definition at line 180 of file bodypart.cpp.
{
    return legacy_id_to_enum( id );
}
References legacy_id_to_enum().
Referenced by assign_coverage_from_json(), game::dump_stats(), disease_type::load(), field_type::load(), mutation_branch::load(), load_effect_data(), melee_actor::load_internal(), load_mon_effect_data(), and load_mutation_attack().
mutate_to_main_part()
body_part mutate_to_main_part (body_part bp)
Returns the matching main body_part that corresponds to the input; i.e.
returns bp_arm_l from bp_hand_l.
Definition at line 370 of file bodypart.cpp.
{
    return get_bp( bp ).main_part->token;
}
References get_bp(), body_part_type::main_part, and body_part_type::token.
operator<()
template<typename T > bool operator< (body_part a, T b) inline
Definition at line 56 of file bodypart.h.
{
    return static_cast<int>( a ) < static_cast<int>( b );
}
References a, and b.
Referenced by read_inventory_preset::sort_compare().
opposite_body_part()
body_part opposite_body_part (body_part bp)
Returns the opposite body part (limb on the other side)
Definition at line 375 of file bodypart.cpp.
{
    return get_bp( bp ).opposite_part->token;
}
References get_bp(), body_part_type::opposite_part, and body_part_type::token.
opposite_side()
side opposite_side (side s)
Returns the opposite side.
Definition at line 30 of file bodypart.cpp.
{
    switch( s ) {
        case side::BOTH:
            return side::BOTH;
        case side::LEFT:
            return side::RIGHT;
        case side::RIGHT:
            return side::LEFT;
        case side::num_sides:
            debugmsg( "invalid side %d", static_cast<int>( s ) );
            break;
    }
    return s;
}
References BOTH, debugmsg, LEFT, num_sides, and RIGHT.
Referenced by npc::adjust_worn(), and item::swap_side().
random_body_part()
body_part random_body_part (bool main_parts_only = false)
Returns a random body_part token.
main_parts_only will limit it to arms, legs, torso, and head.
Definition at line 364 of file bodypart.cpp.
{
    const auto &part = human_anatomy->random_body_part();
    return main_parts_only ? part->main_part->token : part->token;
}
References human_anatomy, and anatomy::random_body_part().
Referenced by mdeath::boomer_glow(), mattack::boomer_glow(), game::start_game(), Character::suffer_from_bad_bionics(), and Character::suffer_from_schizophrenia().
Variable Documentation
all_body_parts
constexpr std::array<body_part, 12> all_body_parts constexpr
Initial value:
= {{
        bp_torso, bp_head, bp_eyes, bp_mouth,
        bp_arm_l, bp_arm_r, bp_hand_l, bp_hand_r,
        bp_leg_l, bp_leg_r, bp_foot_l, bp_foot_r
    }
}
Contains all valid body_part values in the order they are defined in.
Use this to iterate over them.
Definition at line 82 of file bodypart.h.
Referenced by add_effect_to_target(), Character::apply_wetness_morale(), Character::bodypart_exposure(), bp_affected(), check_art_charge_req(), body_part_type::check_consistency(), character_funcs::do_pause(), Character::drench(), Character::drench_mut_calc(), anonymous_namespace{armor_layers.cpp}::get_item_penalties(), Character::hardcoded_effects(), ranged::hit_with_aoe(), Character::item_encumb(), layer_item(), list_and_combine_bps(), mutation_branch::load(), behavior::character_oracle_t::needs_warmth_badly(), item::on_wear(), show_armor_layers_ui(), Character::suffer_from_other_mutations(), character_funcs::update_body_wetness(), and Character::wear_item().
body_part_arm_l
const bodypart_str_id body_part_arm_l extern
body_part_arm_r
const bodypart_str_id body_part_arm_r extern
body_part_eyes
const bodypart_str_id body_part_eyes extern
body_part_foot_l
const bodypart_str_id body_part_foot_l extern
body_part_foot_r
const bodypart_str_id body_part_foot_r extern
body_part_hand_l
const bodypart_str_id body_part_hand_l extern
body_part_hand_r
const bodypart_str_id body_part_hand_r extern
body_part_head
const bodypart_str_id body_part_head extern
body_part_leg_l
const bodypart_str_id body_part_leg_l extern
body_part_leg_r
const bodypart_str_id body_part_leg_r extern
body_part_mouth
const bodypart_str_id body_part_mouth extern
body_part_torso
const bodypart_str_id body_part_torso extern
bp_aiOther
const std::array<size_t, 12> bp_aiOther = {{0, 1, 2, 3, 5, 4, 7, 6, 9, 8, 11, 10}}
Definition at line 273 of file bodypart.h.
Referenced by anonymous_namespace{armor_layers.cpp}::body_part_names(), get_encumbrance(), and other_part().