Cataclysm BN: src/bonuses.cpp File Reference
bonuses.cpp File Reference
#include "bonuses.h"
#include <algorithm>
#include <string>
#include <utility>
#include "character.h"
#include "damage.h"
#include "json.h"
#include "string_formatter.h"
#include "translations.h"
Functions
static bool needs_damage_type (affected_stat as)
static scaling_stat scaling_stat_from_string (const std::string &s)
static affected_stat affected_stat_from_string (const std::string &s)
static std::string string_from_affected_stat (const affected_stat &s)
static std::string string_from_scaling_stat (const scaling_stat &s)
Variables
static const std::map< std::string, affected_stat > affected_stat_map
static const std::map< std::string, scaling_stat > scaling_stat_map
static const std::map< affected_stat, std::string > affected_stat_map_translation
static const std::map< scaling_stat, std::string > scaling_stat_map_translation
Function Documentation
affected_stat_from_string()
static affected_stat affected_stat_from_string (const std::string & s) static
Definition at line 51 of file bonuses.cpp.
{
    const auto &iter = affected_stat_map.find( s );
    if( iter != affected_stat_map.end() ) {
        return iter->second;
    }
    return affected_stat::NONE;
}
References affected_stat_map, and NONE.
Referenced by bonus_container::load().
needs_damage_type()
static bool needs_damage_type (affected_stat as) static
Definition at line 13 of file bonuses.cpp.
{
    return as == affected_stat::DAMAGE ||
           as == affected_stat::ARMOR ||
           as == affected_stat::ARMOR_PENETRATION;
}
References ARMOR, ARMOR_PENETRATION, and DAMAGE.
Referenced by affected_type::affected_type(), bonus_container::get_description(), and bonus_container::load().
scaling_stat_from_string()
static scaling_stat scaling_stat_from_string (const std::string & s) static
Definition at line 41 of file bonuses.cpp.
{
    const auto &iter = scaling_stat_map.find( s );
    if( iter == scaling_stat_map.end() ) {
        return STAT_NULL;
    }
    return iter->second;
}
References scaling_stat_map, and STAT_NULL.
Referenced by effect_scaling::effect_scaling().
string_from_affected_stat()
static std::string string_from_affected_stat (const affected_stat & s) static
Definition at line 74 of file bonuses.cpp.
{
    const auto &iter = affected_stat_map_translation.find( s );
    return iter != affected_stat_map_translation.end() ? _( iter->second ) : "";
}
References _, and affected_stat_map_translation.
Referenced by bonus_container::get_description().
string_from_scaling_stat()
static std::string string_from_scaling_stat (const scaling_stat & s) static
Definition at line 88 of file bonuses.cpp.
{
    const auto &iter = scaling_stat_map_translation.find( s );
    return iter != scaling_stat_map_translation.end() ? _( iter->second ) : "";
}
References _, and scaling_stat_map_translation.
Referenced by bonus_container::get_description().
Variable Documentation
affected_stat_map
const std::map<std::string, affected_stat> affected_stat_map static
Initial value:
= {{
        std::make_pair( "hit", affected_stat::HIT ),
        std::make_pair( "dodge", affected_stat::DODGE ),
        std::make_pair( "block", affected_stat::BLOCK ),
        std::make_pair( "speed", affected_stat::SPEED ),
        std::make_pair( "movecost", affected_stat::MOVE_COST ),
        std::make_pair( "damage", affected_stat::DAMAGE ),
        std::make_pair( "armor", affected_stat::ARMOR ),
        std::make_pair( "arpen", affected_stat::ARMOR_PENETRATION ),
        std::make_pair( "target_armor_multiplier", affected_stat::TARGET_ARMOR_MULTIPLIER )
    }
}
Definition at line 20 of file bonuses.cpp.
Referenced by affected_stat_from_string().
affected_stat_map_translation
const std::map<affected_stat, std::string> affected_stat_map_translation static
Initial value:
= {{
        std::make_pair( affected_stat::HIT, translate_marker( "Accuracy" ) ),
        std::make_pair( affected_stat::DODGE, translate_marker( "Dodge" ) ),
        std::make_pair( affected_stat::BLOCK, translate_marker( "Block" ) ),
        std::make_pair( affected_stat::SPEED, translate_marker( "Speed" ) ),
        std::make_pair( affected_stat::MOVE_COST, translate_marker( "Move cost" ) ),
        std::make_pair( affected_stat::DAMAGE, translate_marker( "damage" ) ),
        std::make_pair( affected_stat::ARMOR, translate_marker( "Armor" ) ),
        std::make_pair( affected_stat::ARMOR_PENETRATION, translate_marker( "Armor penetration" ) ),
        std::make_pair( affected_stat::TARGET_ARMOR_MULTIPLIER, translate_marker( "Target armor multiplier" ) ),
    }
}
Definition at line 61 of file bonuses.cpp.
Referenced by string_from_affected_stat().
scaling_stat_map
const std::map<std::string, scaling_stat> scaling_stat_map static
Initial value:
= {{
        std::make_pair( "str", STAT_STR ),
        std::make_pair( "dex", STAT_DEX ),
        std::make_pair( "int", STAT_INT ),
        std::make_pair( "per", STAT_PER ),
    }
}
Definition at line 33 of file bonuses.cpp.
Referenced by scaling_stat_from_string().
scaling_stat_map_translation
const std::map<scaling_stat, std::string> scaling_stat_map_translation static
Initial value:
= {{
        std::make_pair( STAT_STR, translate_marker( "strength" ) ),
        std::make_pair( STAT_DEX, translate_marker( "dexterity" ) ),
        std::make_pair( STAT_INT, translate_marker( "intelligence" ) ),
        std::make_pair( STAT_PER, translate_marker( "perception" ) ),
    }
}
Definition at line 80 of file bonuses.cpp.
Referenced by string_from_scaling_stat().