Cataclysm BN: src/catacharset.h File Reference
catacharset.h File Reference
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>
Classes
class utf8_wrapper
UTF8-Wrapper over std::string.
Macros
#define CATA_SRC_CATACHARSET_H
#define ANY_LENGTH 5
#define NULL_UNICODE 0x0000
#define PERCENT_SIGN_UNICODE 0x0025
#define UNKNOWN_UNICODE 0xFFFD
Functions
uint32_t UTF8_getch (const char **src, int *srclen)
uint32_t UTF8_getch (const std::string &str)
int cursorx_to_position (const char *line, int cursorx, int *prevpos=nullptr, int maxlen=-1)
int utf8_width (const char *s, bool ignore_tags=false)
int utf8_width (const std::string &str, bool ignore_tags=false)
int utf8_width (const utf8_wrapper &str, bool ignore_tags=false)
std::string left_justify (const std::string &str, int width, bool ignore_tags=false)
std::string right_justify (const std::string &str, int width, bool ignore_tags=false)
std::string utf8_justify (const std::string &str, int width, bool ignore_tags=false)
int center_text_pos (const char *text, int start_pos, int end_pos)
Center text inside whole line.
int center_text_pos (const std::string &text, int start_pos, int end_pos)
int center_text_pos (const utf8_wrapper &text, int start_pos, int end_pos)
std::string utf32_to_utf8 (uint32_t ch)
std::string utf8_truncate (const std::string &s, size_t length)
std::string base64_encode (const std::string &str)
std::string base64_decode (const std::string &str)
std::wstring utf8_to_wstr (const std::string &str)
std::string wstr_to_utf8 (const std::wstring &wstr)
std::string utf32_to_utf8 (const std::u32string &str)
std::u32string utf8_to_utf32 (const std::string &str)
std::vector< std::string > utf8_display_split (const std::string &)
Macro Definition Documentation
ANY_LENGTH
#define ANY_LENGTH 5
Definition at line 10 of file catacharset.h.
CATA_SRC_CATACHARSET_H
#define CATA_SRC_CATACHARSET_H
Definition at line 3 of file catacharset.h.
NULL_UNICODE
#define NULL_UNICODE 0x0000
Definition at line 11 of file catacharset.h.
PERCENT_SIGN_UNICODE
#define PERCENT_SIGN_UNICODE 0x0025
Definition at line 12 of file catacharset.h.
UNKNOWN_UNICODE
#define UNKNOWN_UNICODE 0xFFFD
Definition at line 13 of file catacharset.h.
Function Documentation
base64_decode()
std::string base64_decode (const std::string & str)
Definition at line 310 of file catacharset.cpp.
{
    // do not decode if it is not base64
    if( str.empty() || str[0] != '#' ) {
        return str;
    }
    build_base64_decoding_table();
    std::string instr = str.substr( 1 );
    int input_length = instr.length();
    if( input_length % 4 != 0 ) {
        return str;
    }
    int output_length = input_length / 4 * 3;
    const char *data = instr.c_str();
    if( data[input_length - 1] == '=' ) {
        output_length--;
    }
    if( data[input_length - 2] == '=' ) {
        output_length--;
    }
    std::string decoded_data( output_length, '\0' );
    for( int i = 0, j = 0; i < input_length; ) {
        unsigned sextet_a = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                            ( data[i++] )];
        unsigned sextet_b = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                            ( data[i++] )];
        unsigned sextet_c = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                            ( data[i++] )];
        unsigned sextet_d = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                            ( data[i++] )];
        unsigned triple = ( sextet_a << 3 * 6 )
                          + ( sextet_b << 2 * 6 )
                          + ( sextet_c << 1 * 6 )
                          + ( sextet_d << 0 * 6 );
        if( j < output_length ) {
            decoded_data[j++] = ( triple >> 2 * 8 ) & 0xFF;
        }
        if( j < output_length ) {
            decoded_data[j++] = ( triple >> 1 * 8 ) & 0xFF;
        }
        if( j < output_length ) {
            decoded_data[j++] = ( triple >> 0 * 8 ) & 0xFF;
        }
    }
    return decoded_data;
}
References base64_decoding_table, and build_base64_decoding_table().
Referenced by save_t::from_base_path().
base64_encode()
std::string base64_encode (const std::string & str)
Definition at line 276 of file catacharset.cpp.
{
    //assume it is already encoded
    if( !str.empty() && str[0] == '#' ) {
        return str;
    }
    int input_length = str.length();
    int output_length = 4 * ( ( input_length + 2 ) / 3 );
    std::string encoded_data( output_length, '\0' );
    const unsigned char *data = reinterpret_cast<const unsigned char *>( str.c_str() );
    for( int i = 0, j = 0; i < input_length; ) {
        unsigned octet_a = i < input_length ? data[i++] : 0;
        unsigned octet_b = i < input_length ? data[i++] : 0;
        unsigned octet_c = i < input_length ? data[i++] : 0;
        unsigned triple = ( octet_a << 0x10 ) + ( octet_b << 0x08 ) + octet_c;
        encoded_data[j++] = base64_encoding_table[( triple >> 3 * 6 ) & 0x3F];
        encoded_data[j++] = base64_encoding_table[( triple >> 2 * 6 ) & 0x3F];
        encoded_data[j++] = base64_encoding_table[( triple >> 1 * 6 ) & 0x3F];
        encoded_data[j++] = base64_encoding_table[( triple >> 0 * 6 ) & 0x3F];
    }
    for( int i = 0; i < mod_table[input_length % 3]; i++ ) {
        encoded_data[output_length - 1 - i] = '=';
    }
    return "#" + encoded_data;
}
References base64_encoding_table, and mod_table.
Referenced by save_t::base_path(), game::get_player_base_save_path(), diary::load(), game::move_save_to_graveyard(), and diary::store().
center_text_pos() [1/3]
int center_text_pos (const char * text, int start_pos, int end_pos)
Center text inside whole line.
Parameters
text to be centered.
start_pos printable position on line.
end_pos printable position on line.
Returns
First char position of centered text or start_pos if text is too big.
Definition at line 460 of file catacharset.cpp.
{
    int full_screen = end_pos - start_pos + 1;
    int str_len = utf8_width( text );
    int position = ( full_screen - str_len ) / 2;
    if( position <= 0 ) {
        return start_pos;
    }
    return start_pos + position;
}
References utf8_width().
Referenced by center_text_pos(), and decorate_panel().
center_text_pos() [2/3]
int center_text_pos (const std::string & text, int start_pos, int end_pos)
Definition at line 473 of file catacharset.cpp.
{
    return center_text_pos( text.c_str(), start_pos, end_pos );
}
References center_text_pos().
center_text_pos() [3/3]
int center_text_pos (const utf8_wrapper & text, int start_pos, int end_pos)
Definition at line 478 of file catacharset.cpp.
{
    int full_screen = end_pos - start_pos + 1;
    int str_len = text.display_width();
    int position = ( full_screen - str_len ) / 2;
    if( position <= 0 ) {
        return start_pos;
    }
    return start_pos + position;
}
References utf8_wrapper::display_width().
cursorx_to_position()
int cursorx_to_position (const char * line, int cursorx, int * prevpos = nullptr, int maxlen = -1)
Definition at line 204 of file catacharset.cpp.
{
    int dummy;
    int i = 0;
    int c = 0;
    int *p = prevpos ? prevpos : &dummy;
    *p = 0;
    while( c < cursorx ) {
        const char *utf8str = line + i;
        int len = ANY_LENGTH;
        if( utf8str[0] == 0 ) {
            break;
        }
        uint32_t ch = UTF8_getch( &utf8str, &len );
        int cw = mk_wcwidth( ch );
        len = ANY_LENGTH - len;
        if( len <= 0 ) {
            len = 1;
        }
        if( maxlen >= 0 && maxlen < ( i + len ) ) {
            break;
        }
        i += len;
        if( cw <= 0 ) {
            cw = 0;
        }
        c += cw;
        if( c <= cursorx ) {
            *p = i;
        }
    }
    return i;
}
References ANY_LENGTH, c, line(), mk_wcwidth(), and UTF8_getch().
Referenced by trim_by_length(), and utf8_truncate().
left_justify()
std::string left_justify (const std::string & str, int width, bool ignore_tags = false)
Definition at line 170 of file catacharset.cpp.
{
    int str_width = utf8_width( str, ignore_tags );
    if( str_width >= width ) {
        return str;
    } else {
        return str + std::string( width - str_width, ' ' );
    }
}
References utf8_width().
Referenced by talk_function::companion_choose(), draw_limb_narrow(), draw_limb_wide(), draw_speed_tab(), draw_spellbook_info(), Character::extended_description(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), avatar::read(), render_wind(), and utf8_justify().
right_justify()
std::string right_justify (const std::string & str, int width, bool ignore_tags = false)
Definition at line 180 of file catacharset.cpp.
{
    int str_width = utf8_width( str, ignore_tags );
    if( str_width >= width ) {
        return str;
    } else {
        return std::string( width - str_width, ' ' ) + str;
    }
}
References utf8_width().
Referenced by veh_interact::calc_overview(), camp_car_description(), camp_trip_description(), debug_menu::character_edit_menu(), basecamp::recruit_return(), and utf8_justify().
utf32_to_utf8() [1/2]
std::string utf32_to_utf8 (const std::u32string & str)
Definition at line 417 of file catacharset.cpp.
{
    std::string ret;
    ret.reserve( str.length() );
    for( auto it = str.begin(); it < str.end(); ++it ) {
        ret += utf32_to_utf8( *it );
    }
    return ret;
}
References cata::hash64_detail::ret, and utf32_to_utf8().
utf32_to_utf8() [2/2]
std::string utf32_to_utf8 (uint32_t ch)
Definition at line 99 of file catacharset.cpp.
{
    char out[5];
    char *buf = out;
    static const unsigned char utf8FirstByte[7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC };
    int utf8Bytes;
    if( ch < 0x80 ) {
        utf8Bytes = 1;
    } else if( ch < 0x800 ) {
        utf8Bytes = 2;
    } else if( ch < 0x10000 ) {
        utf8Bytes = 3;
    } else if( ch <= 0x10FFFF ) {
        utf8Bytes = 4;
    } else {
        utf8Bytes = 3;
        ch = UNKNOWN_UNICODE;
    }
    buf += utf8Bytes;
    switch( utf8Bytes ) {
        case 4:
            *--buf = ( ch | 0x80 ) & 0xBF;
            ch >>= 6;
        /* fallthrough */
        case 3:
            *--buf = ( ch | 0x80 ) & 0xBF;
            ch >>= 6;
        /* fallthrough */
        case 2:
            *--buf = ( ch | 0x80 ) & 0xBF;
            ch >>= 6;
        /* fallthrough */
        case 1:
            *--buf = ch | utf8FirstByte[utf8Bytes];
    }
    out[utf8Bytes] = '\0';
    return out;
}
References UNKNOWN_UNICODE.
Referenced by translation::deserialize(), input_context::get_desc(), map_extra::get_symbol(), overmap_land_use_code::get_symbol(), oter_type_t::get_symbol(), weather_printable::get_symbol(), weather_animation_t::get_symbol(), weather_type::get_symbol(), oter_t::get_symbol(), field_type::get_symbol(), string_editor_window::print_editor(), string_editor_window::query_string(), and utf32_to_utf8().
utf8_display_split()
std::vector< std::string > utf8_display_split (const std::string & s)
Definition at line 440 of file catacharset.cpp.
{
    std::vector<std::string> result;
    std::string current_glyph;
    const char *pos = s.c_str();
    int len = s.length();
    while( len > 0 ) {
        const char *old_pos = pos;
        const uint32_t ch = UTF8_getch( &pos, &len );
        const int width = mk_wcwidth( ch );
        if( width > 0 && !current_glyph.empty() ) {
            result.push_back( current_glyph );
            current_glyph.clear();
        }
        current_glyph += std::string( old_pos, pos );
    }
    result.push_back( current_glyph );
    return result;
}
References mk_wcwidth(), and UTF8_getch().
Referenced by mapgen_function_json_base::setup_common().
UTF8_getch() [1/2]
uint32_t UTF8_getch (const char ** src, int * srclen)
Definition at line 18 of file catacharset.cpp.
{
    const unsigned char *p = *reinterpret_cast<const unsigned char **>( src );
    int left = 0;
    bool overlong = false;
    bool underflow = false;
    uint32_t ch = UNKNOWN_UNICODE;
    if( *srclen == 0 ) {
        return UNKNOWN_UNICODE;
    }
    if( p[0] >= 0xFC ) {
        if( ( p[0] & 0xFE ) == 0xFC ) {
            if( p[0] == 0xFC && ( p[1] & 0xFC ) == 0x80 ) {
                overlong = true;
            }
            ch = static_cast<uint32_t>( p[0] & 0x01 );
            left = 5;
        }
    } else if( p[0] >= 0xF8 ) {
        if( ( p[0] & 0xFC ) == 0xF8 ) {
            if( p[0] == 0xF8 && ( p[1] & 0xF8 ) == 0x80 ) {
                overlong = true;
            }
            ch = static_cast<uint32_t>( p[0] & 0x03 );
            left = 4;
        }
    } else if( p[0] >= 0xF0 ) {
        if( ( p[0] & 0xF8 ) == 0xF0 ) {
            if( p[0] == 0xF0 && ( p[1] & 0xF0 ) == 0x80 ) {
                overlong = true;
            }
            ch = static_cast<uint32_t>( p[0] & 0x07 );
            left = 3;
        }
    } else if( p[0] >= 0xE0 ) {
        if( ( p[0] & 0xF0 ) == 0xE0 ) {
            if( p[0] == 0xE0 && ( p[1] & 0xE0 ) == 0x80 ) {
                overlong = true;
            }
            ch = static_cast<uint32_t>( p[0] & 0x0F );
            left = 2;
        }
    } else if( p[0] >= 0xC0 ) {
        if( ( p[0] & 0xE0 ) == 0xC0 ) {
            if( ( p[0] & 0xDE ) == 0xC0 ) {
                overlong = true;
            }
            ch = static_cast<uint32_t>( p[0] & 0x1F );
            left = 1;
        }
    } else {
        if( ( p[0] & 0x80 ) == 0x00 ) {
            ch = static_cast<uint32_t>( p[0] );
        }
    }
    ++*src;
    --*srclen;
    while( left > 0 && *srclen > 0 ) {
        ++p;
        if( ( p[0] & 0xC0 ) != 0x80 ) {
            ch = UNKNOWN_UNICODE;
            break;
        }
        ch <<= 6;
        ch |= ( p[0] & 0x3F );
        ++*src;
        --*srclen;
        --left;
    }
    if( left > 0 ) {
        underflow = true;
    }
    if( overlong || underflow ||
        ( ch >= 0xD800 && ch <= 0xDFFF ) ||
        ( ch == 0xFFFE || ch == 0xFFFF ) || ch > 0x10FFFF ) {
        ch = UNKNOWN_UNICODE;
    }
    return ch;
}
References UNKNOWN_UNICODE.
Referenced by utf8_wrapper::at(), utf8_wrapper::byte_start(), utf8_wrapper::byte_start_display(), game::cleanup_at_end(), folded_text::codepoint_coordinates(), cursorx_to_position(), folded_text::folded_text(), input_manager::get_input_event(), utf8_wrapper::init_utf8_wrapper(), rotatable_symbols::load(), string_editor_window::print_editor(), string_editor_window::query_string(), unicode_codepoint_from_symbol_reader(), utf8_display_split(), UTF8_getch(), utf8_to_utf32(), utf8_width(), utf8_width_notags(), and word_rewrap().
UTF8_getch() [2/2]
uint32_t UTF8_getch (const std::string & str) inline
Definition at line 19 of file catacharset.h.
{
    const char *utf8str = str.c_str();
    int len = str.length();
    return UTF8_getch( &utf8str, &len );
}
References utf8_wrapper::str(), and UTF8_getch().
utf8_justify()
std::string utf8_justify (const std::string & str, int width, bool ignore_tags = false)
Definition at line 190 of file catacharset.cpp.
{
    if( width < 0 ) {
        return left_justify( str, -width, ignore_tags );
    } else {
        return right_justify( str, width, ignore_tags );
    }
}
References left_justify(), and right_justify().
Referenced by print_mana().
utf8_to_utf32()
std::u32string utf8_to_utf32 (const std::string & str)
Definition at line 427 of file catacharset.cpp.
{
    int len = str.length();
    const char *dat = str.data();
    std::u32string ret;
    ret.reserve( len );
    while( len > 0 ) {
        ret.push_back( UTF8_getch( &dat, &len ) );
    }
    ret.shrink_to_fit();
    return ret;
}
References cata::hash64_detail::ret, and UTF8_getch().
Referenced by translation::deserialize().
utf8_to_wstr()
std::wstring utf8_to_wstr (const std::string & str)
Definition at line 383 of file catacharset.cpp.
{
#if defined(_WIN32)
    int sz = MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, nullptr, 0 ) + 1;
    std::wstring wstr( sz, '\0' );
    MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, &wstr[0], sz );
    strip_trailing_nulls( wstr );
    return wstr;
#else
    std::size_t sz = std::mbstowcs( nullptr, str.c_str(), 0 ) + 1;
    std::wstring wstr( sz, '\0' );
    std::mbstowcs( &wstr[0], str.c_str(), sz );
    strip_trailing_nulls( wstr );
    return wstr;
#endif
}
References strip_trailing_nulls().
Referenced by game::check_safe_mode_allowed(), anonymous_namespace{filesystem.cpp}::is_directory_stat(), lcmatch(), obscure_message(), cata_ofstream::open(), cata_ifstream::open(), localized_comparator::operator()(), remove_directory(), to_lower_case(), and to_upper_case().
utf8_truncate()
std::string utf8_truncate (const std::string & s, size_t length)
Definition at line 238 of file catacharset.cpp.
{
    if( length == 0 || s.empty() ) {
        return s;
    }
    int last_pos = cursorx_to_position( s.c_str(), length, nullptr, -1 );
    return s.substr( 0, last_pos );
}
References cursorx_to_position().
Referenced by draw_env_compact(), draw_loc_labels(), draw_location_classic(), character_display::print_encumbrance(), advanced_inventory::refresh_minimap(), set_traits(), options_manager::show(), item::tname(), trunc_ellipse(), and iexamine::vending().
utf8_width() [1/3]
int utf8_width (const char * s, bool ignore_tags = false)
Definition at line 142 of file catacharset.cpp.
{
    if( ignore_tags ) {
        return utf8_width( remove_color_tags( s ) );
    }
    int len = strlen( s );
    const char *ptr = s;
    int w = 0;
    while( len > 0 ) {
        uint32_t ch = UTF8_getch( &ptr, &len );
        if( ch == UNKNOWN_UNICODE ) {
            continue;
        }
        w += mk_wcwidth( ch );
    }
    return w;
}
References mk_wcwidth(), ptr(), remove_color_tags(), UNKNOWN_UNICODE, UTF8_getch(), and utf8_width().
Referenced by Character::body_window(), camp_car_description(), center_print(), center_text_pos(), Item_factory::check_definitions(), teleporter_list::choose_teleport_location(), game::cleanup_at_end(), string_input_popup::create_window(), player_morale::display(), veh_interact::display_esc(), veh_interact::display_list(), veh_interact::display_mode(), veh_interact::display_name(), veh_interact::display_stats(), Character::dispose_item(), inventory_column::draw(), char_creation::draw_age(), overmap_ui::draw_ascii(), overmap_ui::draw_camp_labels(), talk_function::draw_camp_tabs(), draw_char_narrow(), draw_char_wide(), overmap_ui::draw_city_labels(), draw_connectors(), draw_env_compact(), inventory_selector::draw_footer(), draw_health_classic(), char_creation::draw_height(), target_ui::draw_help_notice(), draw_hint(), draw_limb2(), draw_limb_health(), help::draw_menu(), draw_needs_compact(), game::draw_panels(), draw_points(), draw_recipe_subtabs(), draw_spellbook_info(), draw_stats_tab(), draw_stealth(), draw_subtab(), draw_tab(), draw_tabs(), draw_time(), inventory_column::expand_to_fit(), Character::extended_description(), query_popup::fold_query(), get_colored_bar(), inventory_column::get_entry_cell_width(), inventory_selector::get_footer_min_width(), inventory_selector::get_header_min_width(), get_labeled_bar(), game::get_player_input(), known_magic::get_spellname_max_width(), scrollingcombattext::cSCT::getPosX(), scrollingcombattext::cSCT::getPosY(), query_popup::init(), Messages::dialog::init(), insert_table(), left_justify(), game::list_items(), ascii_art::load(), map_key::map_key(), game::mon_info(), name_and_value(), obscure_message(), main_menu::opening_screen(), target_ui::panel_cursor_info(), pickup::pick_up(), character_display::print_encumbrance(), snake_game::print_header(), advanced_inventory::print_items(), main_menu::print_menu(), vehicle::print_part_list(), print_ranged_chance(), query_for_template_name(), string_input_popup::query_string(), avatar::read(), advanced_inventory::redraw_pane(), wish_monster_callback::refresh(), wish_item_callback::refresh(), game::reset_item_list_state(), right_justify(), right_print(), overmap_ui::search(), select_crafting_recipe(), set_description(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), options_manager::cOpt::setNext(), uilist::setup(), shortcut_print(), show_armor_layers_ui(), show_bionics_ui(), worldfactory::show_modselection_window(), worldfactory::show_worldgen_tab_confirm(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), item::tname(), trim_by_length(), trunc_ellipse(), overmap_ui::update_note_preview(), trading_window::update_win(), and utf8_width().
utf8_width() [2/3]
int utf8_width (const std::string & str, bool ignore_tags = false)
Definition at line 160 of file catacharset.cpp.
{
    return utf8_width( str.c_str(), ignore_tags );
}
References utf8_width().
utf8_width() [3/3]
int utf8_width (const utf8_wrapper & str, bool ignore_tags = false)
Definition at line 165 of file catacharset.cpp.
{
    return utf8_width( str.c_str(), ignore_tags );
}
References utf8_wrapper::c_str(), and utf8_width().
wstr_to_utf8()
std::string wstr_to_utf8 (const std::wstring & wstr)
Definition at line 400 of file catacharset.cpp.
{
#if defined(_WIN32)
    int sz = WideCharToMultiByte( CP_UTF8, 0, wstr.c_str(), -1, nullptr, 0, nullptr, nullptr );
    std::string str( sz, '\0' );
    WideCharToMultiByte( CP_UTF8, 0, wstr.c_str(), -1, &str[0], sz, nullptr, nullptr );
    strip_trailing_nulls( str );
    return str;
#else
    std::size_t sz = std::wcstombs( nullptr, wstr.c_str(), 0 ) + 1;
    std::string str( sz, '\0' );
    std::wcstombs( &str[0], wstr.c_str(), sz );
    strip_trailing_nulls( str );
    return str;
#endif
}
References strip_trailing_nulls().
Referenced by game::check_safe_mode_allowed(), obscure_message(), localized_comparator::operator()(), to_lower_case(), and to_upper_case().