Cataclysm BN: src/cata_utility.cpp File Reference
cata_utility.cpp File Reference
#include "cata_utility.h"
#include "fstream_utils.h"
#include <cctype>
#include <cmath>
#include <cstdio>
#include <exception>
#include <fstream>
#include <iterator>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include "debug.h"
#include "filesystem.h"
#include "json.h"
#include "options.h"
#include "output.h"
#include "rng.h"
#include "translations.h"
#include "units.h"
Functions
static double pow10 (unsigned int n)
double round_up (double val, unsigned int dp)
Round a value up at a given decimal place.
int modulo (int v, int m)
bool isBetween (int test, int down, int up)
Determine whether a value is between two given boundaries.
double logarithmic (double t)
Basic logistic function.
double logarithmic_range (int min, int max, int pos)
Normalized logistic function.
double normal_cdf (double x, double mean, double stddev)
Cumulative distribution function of a certain normal distribution.
int bound_mod_to_vals (int val, int mod, int max, int min)
Clamp the value of a modifier in order to bound the resulting value.
double clamp_to_width (double value, int width, int &scale)
Clamp (number and space wise) value to with, taking into account the specified preferred scale, returning the adjusted (shortened) scale that best fit the width, optionally returning a flag that indicate if the value was truncated to fit the width.
double clamp_to_width (double value, int width, int &scale, bool *out_truncated)
float multi_lerp (const std::vector< std::pair< float, float > > &points, float x)
From points, finds p1 and p2 such that p1.first < x < p2.first Then linearly interpolates between p1.second and p2.second and returns the result.
static std::ios_base::openmode cata_ios_mode_to_std (std::ios_base::openmode dir, cata_ios_mode m)
void write_to_file (const std::string &path, const std::function< void(std::ostream &)> &writer)
bool write_to_file (const std::string &path, const std::function< void(std::ostream &)> &writer, const char *const fail_message)
Open a file for writing, calls the writer on that stream.
std::istream & safe_getline (std::istream &ins, std::string &str)
bool read_from_file (const std::string &path, const std::function< void(std::istream &)> &reader)
Try to open and read from given file using the given callback.
bool read_from_file_json (const std::string &path, const std::function< void(JsonIn &)> &reader)
bool read_from_file (const std::string &path, JsonDeserializer &reader)
bool read_from_file_optional (const std::string &path, const std::function< void(std::istream &)> &reader)
bool read_from_file_optional_json (const std::string &path, const std::function< void(JsonIn &)> &reader)
bool read_from_file_optional (const std::string &path, JsonDeserializer &reader)
std::string obscure_message (const std::string &str, std::function< char()> f)
Apply fuzzy effect to a string like: Hello, world! --> H##lo, wurl#!
std::string serialize_wrapper (const std::function< void(JsonOut &)> &callback)
@group JSON (de)serialization wrappers.
void deserialize_wrapper (const std::function< void(JsonIn &)> &callback, const std::string &data)
Function Documentation
bound_mod_to_vals()
int bound_mod_to_vals (int val, int mod, int max, int min)
Clamp the value of a modifier in order to bound the resulting value.
Ensures that a modifier value will not cause a base value to exceed given bounds when applied. If necessary, the given modifier value is increased or reduced to meet this constraint.
Giving a value of zero for min or max indicates that there is no minimum or maximum boundary, respectively.
Parameters
val The base value that the modifier will be applied to
mod The desired modifier to be added to the base value
max The desired maximum value of the base value after modification, or zero.
min The desired minimum value of the base value after modification, or zero.
Returns
Value of mod, possibly altered to respect the min and max boundaries
Definition at line 111 of file cata_utility.cpp.
{
    if( val + mod > max && max != 0 ) {
        mod = std::max( max - val, 0 );
    }
    if( val + mod < min && min != 0 ) {
        mod = std::min( min - val, 0 );
    }
    return mod;
}
Referenced by Character::process_one_effect().
cata_ios_mode_to_std()
static std::ios_base::openmode cata_ios_mode_to_std (std::ios_base::openmode dir, cata_ios_mode m) static
Definition at line 177 of file cata_utility.cpp.
{
    std::ios_base::openmode ret = dir;
    if( static_cast<int>( m ) & static_cast<int>( cata_ios_mode::binary ) ) {
        ret |= std::ios_base::binary;
    }
    if( static_cast<int>( m ) & static_cast<int>( cata_ios_mode::app ) ) {
        ret |= std::ios_base::app;
    }
    return ret;
}
References app, binary, and cata::hash64_detail::ret.
Referenced by cata_ofstream::open(), and cata_ifstream::open().
clamp_to_width() [1/2]
double clamp_to_width (double value, int width, int & scale)
Clamp (number and space wise) value to with, taking into account the specified preferred scale, returning the adjusted (shortened) scale that best fit the width, optionally returning a flag that indicate if the value was truncated to fit the width.
Definition at line 122 of file cata_utility.cpp.
{
    return clamp_to_width( value, width, scale, nullptr );
}
References clamp_to_width().
Referenced by clamp_to_width(), and format_volume().
clamp_to_width() [2/2]
double clamp_to_width (double value, int width, int & scale, bool * out_truncated)
Definition at line 127 of file cata_utility.cpp.
{
    if( out_truncated != nullptr ) {
        *out_truncated = false;
    }
    if( value >= std::pow( 10.0, width ) ) {
        // above the maximum number we can fit in the width without decimal
        // show the biggest number we can without decimal
        // flag as truncated
        value = std::pow( 10.0, width ) - 1.0;
        scale = 0;
        if( out_truncated != nullptr ) {
            *out_truncated = true;
        }
    } else if( scale > 0 ) {
        for( int s = 1; s <= scale; s++ ) {
            // 1 decimal separator + "s"
            int scale_width = 1 + s;
            if( width > scale_width && value >= std::pow( 10.0, width - scale_width ) ) {
                // above the maximum number we can fit in the width with "s" decimals
                // show this number with one less decimal than "s"
                scale = s - 1;
                break;
            }
        }
    }
    return value;
}
deserialize_wrapper()
void deserialize_wrapper (const std::function< void(JsonIn &)> & callback, const std::string & data)
Definition at line 667 of file cata_utility.cpp.
{
    std::istringstream buffer( data );
    JsonIn jsin( buffer );
    callback( jsin );
}
Referenced by deserialize(), and rcdrive().
isBetween()
bool isBetween (int test, int down, int up)
Determine whether a value is between two given boundaries.
Parameters
test Value to be tested.
down Lower boundary for value.
up Upper boundary for value.
Returns
True if test value is greater than lower boundary and less than upper boundary, otherwise returns false.
Definition at line 59 of file cata_utility.cpp.
{
    return test > down && test < up;
}
logarithmic()
double logarithmic (double t)
Basic logistic function.
Calculates the value at a single point on a standard logistic curve.
Parameters
t Point on logistic curve to retrieve value for
Returns
Value of the logistic curve at the given point
Definition at line 68 of file cata_utility.cpp.
{
    return 1 / ( 1 + std::exp( -t ) );
}
Referenced by logarithmic_range().
logarithmic_range()
double logarithmic_range (int min, int max, int pos)
Normalized logistic function.
Generates a logistic curve on the domain [-6,6], then normalizes such that the value ranges from 1 to 0. A single point is then calculated on this curve.
Parameters
min t-value that should yield an output of 1 on the scaled curve.
max t-value that should yield an output of 0 on the scaled curve.
pos t-value to calculate the output for.
Returns
The value of the scaled logistic curve at point pos.
Definition at line 73 of file cata_utility.cpp.
{
    const double LOGI_CUTOFF = 4;
    const double LOGI_MIN = logarithmic( -LOGI_CUTOFF );
    const double LOGI_MAX = logarithmic( +LOGI_CUTOFF );
    const double LOGI_RANGE = LOGI_MAX - LOGI_MIN;
    if( min >= max ) {
        debugmsg( "Invalid interval (%d, %d).", min, max );
        return 0.0;
    }
    // Anything beyond (min,max) gets clamped.
    if( pos <= min ) {
        return 1.0;
    } else if( pos >= max ) {
        return 0.0;
    }
    // Normalize the pos to [0,1]
    double range = max - min;
    double unit_pos = ( pos - min ) / range;
    // Scale and flip it to [+LOGI_CUTOFF,-LOGI_CUTOFF]
    double scaled_pos = LOGI_CUTOFF - 2 * LOGI_CUTOFF * unit_pos;
    // Get the raw logistic value.
    double raw_logistic = logarithmic( scaled_pos );
    // Scale the output to [0,1]
    return ( raw_logistic - LOGI_MIN ) / LOGI_RANGE;
}
References debugmsg, and logarithmic().
Referenced by ranged::aim_per_move(), Character::block_hit(), player_morale::morale_point::get_net_bonus(), weather_generator::get_water_temperature(), and Character::update_bodytemp().
modulo()
int modulo (int v, int m)
Definition at line 50 of file cata_utility.cpp.
{
    // C++11: negative v and positive m result in negative v%m (or 0),
    // but this is supposed to be mathematical modulo: 0 <= v%m < m,
    const int r = v % m;
    // Adding m in that (and only that) case.
    return r >= 0 ? r : r + ( m * ( 1 - r / m ) );
}
Referenced by is_sm_tile_outside(), is_sm_tile_over_water(), set_skills(), and distraction_manager::distraction_manager_gui::show().
multi_lerp()
float multi_lerp (const std::vector< std::pair< float, float > > & points, float x)
From points, finds p1 and p2 such that p1.first < x < p2.first Then linearly interpolates between p1.second and p2.second and returns the result.
points should be sorted by first elements of the pairs. If x is outside range, returns second value of the first (if x < points[0].first) or last point.
Definition at line 156 of file cata_utility.cpp.
{
    size_t i = 0;
    while( i < points.size() && points[i].first <= x ) {
        i++;
    }
    if( i == 0 ) {
        return points.front().second;
    } else if( i >= points.size() ) {
        return points.back().second;
    }
    // How far are we along the way from last threshold to current one
    const float t = ( x - points[i - 1].first ) /
                    ( points[i].first - points[i - 1].first );
    // Linear interpolation of values at relevant thresholds
    return ( t * points[i].second ) + ( ( 1 - t ) * points[i - 1].second );
}
References second.
Referenced by character_effects::get_kcal_speed_penalty(), character_effects::get_thirst_speed_penalty(), npc_ai::gun_value(), and Character::reset_stats().
normal_cdf()
double normal_cdf (double x, double mean, double stddev)
Cumulative distribution function of a certain normal distribution.
Parameters
x point at which the CDF of the distribution is measured
mean mean of the normal distribution
stddev standard deviation of the normal distribution
Returns
The probability that a random point from the distribution will be lesser than
Parameters
x
Definition at line 106 of file cata_utility.cpp.
{
    return 0.5 * ( 1.0 + std::erf( ( x - mean ) / ( stddev * M_SQRT2 ) ) );
}
References M_SQRT2.
Referenced by ranged::hit_chance().
obscure_message()
std::string obscure_message (const std::string & str, std::function< char()> f)
Apply fuzzy effect to a string like: Hello, world! --> H##lo, wurl#!
Parameters
str the original string to be processed
f the function that guides how to mess the message f() will be called for each character (lingual, not byte): [-] f() == -1 : nothing will be done [-] f() == 0 : the said character will be replace by a random character [-] f() == ch : the said character will be replace by ch
Returns
The processed string
Definition at line 620 of file cata_utility.cpp.
{
    //~ translators: place some random 1-width characters here in your language if possible, or leave it as is
    std::string gibberish_narrow = _( "abcdefghijklmnopqrstuvwxyz" );
    std::string gibberish_wide =
        //~ translators: place some random 2-width characters here in your language if possible, or leave it as is
        _( "" );
    std::wstring w_gibberish_narrow = utf8_to_wstr( gibberish_narrow );
    std::wstring w_gibberish_wide = utf8_to_wstr( gibberish_wide );
    std::wstring w_str = utf8_to_wstr( str );
    // a trailing NULL terminator is necessary for utf8_width function
    char transformation[2] = { 0 };
    for( size_t i = 0; i < w_str.size(); ++i ) {
        transformation[0] = f();
        std::string this_char = wstr_to_utf8( std::wstring( 1, w_str[i] ) );
        if( transformation[0] == -1 ) {
            continue;
        } else if( transformation[0] == 0 ) {
            if( utf8_width( this_char ) == 1 ) {
                w_str[i] = random_entry( w_gibberish_narrow );
            } else {
                w_str[i] = random_entry( w_gibberish_wide );
            }
        } else {
            // Only support the case e.g. replace current character to symbols like # or ?
            if( utf8_width( transformation ) != 1 ) {
                debugmsg( "target character isn't narrow" );
            }
            // A 2-width wide character in the original string should be replace by two narrow characters
            w_str.replace( i, 1, utf8_to_wstr( std::string( utf8_width( this_char ), transformation[0] ) ) );
        }
    }
    std::string result = wstr_to_utf8( w_str );
    if( utf8_width( str ) != utf8_width( result ) ) {
        debugmsg( "utf8_width differ between original string and obscured string" );
    }
    return result;
}
References _, debugmsg, random_entry(), utf8_to_wstr(), utf8_width(), and wstr_to_utf8().
Referenced by iuse::radio_on().
pow10()
static double pow10 (unsigned int n) static
Definition at line 28 of file cata_utility.cpp.
{
    double ret = 1;
    double tmp = 10;
    while( n ) {
        if( n & 1 ) {
            ret *= tmp;
        }
        tmp *= tmp;
        n >>= 1;
    }
    return ret;
}
References cata::hash64_detail::ret.
Referenced by round_up().
read_from_file() [1/2]
bool read_from_file (const std::string & path, const std::function< void(std::istream &)> & reader)
Try to open and read from given file using the given callback.
The file is opened for reading (binary mode), given to the callback (which does the actual reading) and closed. Any exceptions from the callbacks are caught and reported as debugmsg. If the stream is in a fail state (other than EOF) after the callback returns, it is handled as error as well.
The callback can either be a generic std::istream, a JsonIn stream (which has been initialized from the std::istream) or a JsonDeserializer object (in case of the later, it's JsonDeserializer::deserialize method will be invoked).
The functions with the "_optional" prefix do not show a debug message when the file does not exist. They simply ignore the call and return false immediately (without calling the callback). They can be used for loading legacy files.
Returns
true is the file was read without any errors, false upon any error.
Definition at line 519 of file cata_utility.cpp.
{
    try {
        cata_ifstream fin = std::move( cata_ifstream().mode( cata_ios_mode::binary ).open( path ) );
        if( !fin.is_open() ) {
            throw std::runtime_error( "opening file failed" );
        }
        reader( *fin );
        if( fin.bad() ) {
            throw std::runtime_error( "reading file failed" );
        }
        return true;
    } catch( const std::exception &err ) {
        debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.c_str(), err.what() );
        return false;
    }
}
References _, cata_ifstream::bad(), binary, debugmsg, cata_ifstream::is_open(), avatar_action::move(), and open().
Referenced by build_resource_list(), diary::load(), game::load(), read_from_file_json(), read_from_file_optional(), and sokoban_game::start_game().
read_from_file() [2/2]
bool read_from_file (const std::string & path, JsonDeserializer & reader)
Definition at line 546 of file cata_utility.cpp.
{
    return read_from_file_json( path, [&reader]( JsonIn & jsin ) {
        reader.deserialize( jsin );
    } );
}
References JsonDeserializer::deserialize(), and read_from_file_json().
read_from_file_json()
bool read_from_file_json (const std::string & path, const std::function< void(JsonIn &)> & reader)
Definition at line 538 of file cata_utility.cpp.
{
    return read_from_file( path, [&]( std::istream & fin ) {
        JsonIn jsin( fin, path );
        reader( jsin );
    } );
}
References read_from_file().
Referenced by get_random_tip_of_the_day(), Name::load_from_file(), avatar::load_template(), and read_from_file().
read_from_file_optional() [1/2]
bool read_from_file_optional (const std::string & path, const std::function< void(std::istream &)> & reader)
Definition at line 553 of file cata_utility.cpp.
{
    // Note: slight race condition here, but we'll ignore it. Worst case: the file
    // exists and got removed before reading it -> reading fails with a message
    // Or file does not exists, than everything works fine because it's optional anyway.
    return file_exist( path ) && read_from_file( path, reader );
}
References file_exist(), and read_from_file().
Referenced by get_input_string_from_file(), main_menu::init_strings(), game::load(), main_menu::load_file(), game::load_master(), zone_manager::load_zones(), overmap::open(), and read_from_file_optional_json().
read_from_file_optional() [2/2]
bool read_from_file_optional (const std::string & path, JsonDeserializer & reader)
Definition at line 571 of file cata_utility.cpp.
{
    return read_from_file_optional_json( path, [&reader]( JsonIn & jsin ) {
        reader.deserialize( jsin );
    } );
}
References JsonDeserializer::deserialize(), and read_from_file_optional_json().
read_from_file_optional_json()
bool read_from_file_optional_json (const std::string & path, const std::function< void(JsonIn &)> & reader)
Definition at line 562 of file cata_utility.cpp.
{
    return read_from_file_optional( path, [&]( std::istream & fin ) {
        JsonIn jsin( fin, path );
        reader( jsin );
    } );
}
References read_from_file_optional().
Referenced by auto_notes::auto_note_settings::load(), help::load(), options_manager::load(), panel_manager::load(), auto_pickup::player_settings::load(), map_memory::load(), load_artifacts(), color_manager::load_custom(), mod_management::load_mod_info(), mod_management::load_mod_list(), mod_manager::load_mods_list(), WORLD::load_options(), mod_manager::load_replacement_mods(), map_memory::load_submap(), read_from_file_optional(), and mapbuffer::unserialize_submaps().
round_up()
double round_up (double val, unsigned int dp)
Round a value up at a given decimal place.
Parameters
val Value to be rounded.
dp Decimal place to round the value at.
Returns
Rounded value.
Definition at line 42 of file cata_utility.cpp.
{
    // Some implementations of std::pow does not return the accurate result even
    // for small powers of 10, so we use a specialized routine to calculate them.
    const double denominator = pow10( dp );
    return std::ceil( denominator * val ) / denominator;
}
References pow10().
Referenced by item::animal_armor_info(), item::armor_info(), item::basic_info(), veh_interact::calc_overview(), carry_volume_string(), carry_weight_string(), comestible_inventory_preset::comestible_inventory_preset(), item::contents_info(), format_volume(), inventory_selector::get_weight_and_volume_stats(), pickup::pick_up(), Character::pour_into(), and vehicle::print_part_list().
safe_getline()
std::istream & safe_getline (std::istream & ins, std::string & str)
Definition at line 492 of file cata_utility.cpp.
{
    str.clear();
    std::istream::sentry se( ins, true );
    std::streambuf *sb = ins.rdbuf();
    while( true ) {
        int c = sb->sbumpc();
        switch( c ) {
            case '\n':
                return ins;
            case '\r':
                if( sb->sgetc() == '\n' ) {
                    sb->sbumpc();
                }
                return ins;
            case EOF:
                if( str.empty() ) {
                    ins.setstate( std::ios::eofbit );
                }
                return ins;
            default:
                str += static_cast<char>( c );
        }
    }
}
References c.
Referenced by sokoban_game::parse_level().
serialize_wrapper()
std::string serialize_wrapper (const std::function< void(JsonOut &)> & callback)
@group JSON (de)serialization wrappers.
The functions here provide a way to (de)serialize objects without actually including "json.h". The *_wrapper function create the JSON stream instances and therefor require "json.h", but the caller doesn't. Callers should just forward the stream reference to the actual (de)serialization function.
The inline function do this by calling T::(de)serialize (which is assumed to exist with the proper signature).
Exceptions
std::exception Deserialization functions may throw upon malformed JSON or unexpected/invalid content.
Definition at line 659 of file cata_utility.cpp.
{
    std::ostringstream buffer;
    JsonOut jsout( buffer );
    callback( jsout );
    return buffer.str();
}
Referenced by iuse::radiocontrol(), rcdrive(), map_memory::save(), and serialize().
write_to_file() [1/2]
void write_to_file (const std::string & path, const std::function< void(std::ostream &)> & writer)
Definition at line 453 of file cata_utility.cpp.
{
    // Any of the below may throw. ofstream_wrapper will clean up the temporary path on its own.
    ofstream_wrapper fout( path, cata_ios_mode::binary );
    writer( fout.stream() );
    fout.close();
}
References binary, ofstream_wrapper::close(), and ofstream_wrapper::stream().
Referenced by can_write_to_dir(), copy_file(), edit_json(), auto_notes::auto_note_settings::save(), distraction_manager::distraction_manager_gui::save(), game::save(), input_manager::save(), options_manager::save(), panel_manager::save(), overmap::save(), auto_pickup::player_settings::save(), safemode::save(), WORLD::save(), map_memory::save(), save_artifacts(), color_manager::save_custom(), game::save_factions_missions_npcs(), worldfactory::save_last_world_info(), mod_management::save_mod_list(), mod_manager::save_mods_list(), game::save_player_data(), mapbuffer::save_quad(), avatar::save_template(), zone_manager::save_zones(), diary::store(), weather_generator::test_weather(), game::write_memorial_file(), and write_to_file().
write_to_file() [2/2]
bool write_to_file (const std::string & path, const std::function< void(std::ostream &)> & writer, const char * fail_message)
Open a file for writing, calls the writer on that stream.
If the writer throws, or if the file could not be opened or if any I/O error happens, the function shows a popup containing the fail_message, the error text and the path.
Returns
Whether saving succeeded (no error was caught).
Exceptions
The void function throws when writing failes or when the writer throws. The other function catches all exceptions and returns false.
Definition at line 461 of file cata_utility.cpp.
{
    try {
        write_to_file( path, writer );
        return true;
    } catch( const std::exception &err ) {
        if( fail_message ) {
            popup( _( "Failed to write %1$s to \"%2$s\": %3$s" ), fail_message, path.c_str(), err.what() );
        }
        return false;
    }
}
References _, popup(), and write_to_file().