Cataclysm BN: src/character_effects.cpp File Reference
character_effects.cpp File Reference
#include "character_effects.h"
#include "bionics.h"
#include "calendar.h"
#include "character_martial_arts.h"
#include "character.h"
#include "creature.h"
#include "handle_liquid.h"
#include "itype.h"
#include "make_static.h"
#include "map_iterator.h"
#include "player.h"
#include "rng.h"
#include "skill.h"
#include "submap.h"
#include "trap.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather_gen.h"
#include "weather.h"
Namespaces
namespace character_effects
Functions
stat_mod character_effects::get_pain_penalty (const Character &ch)
Returns the effect of pain on stats.
int character_effects::get_kcal_speed_penalty (float kcal_percent)
Returns the penalty to speed from starvation.
int character_effects::get_thirst_speed_penalty (int thirst)
Returns the penalty to speed from thirst.
int character_effects::calc_morale_fatigue_cap (int fatigue)
Calculates character's morale cap due to fatigue.
double character_effects::vomit_mod (const Character &ch)
Returns the modifier value used for vomiting effects.
int character_effects::talk_skill (const Character &ch)
Returns a value used when attempting to convince NPC's of something.
int character_effects::intimidation (const Character &ch)
Returns a value used when attempting to intimidate NPC's.
int character_effects::calc_focus_equilibrium (const Character &who)
Uses morale, pain and fatigue to return the player's focus target goto value.
int character_effects::calc_focus_change (const Character &who)
Calculates actual focus gain/loss value from focus equilibrium.
Variables
static const activity_id ACT_READ ("ACT_READ")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_INT_SLIME ("INT_SLIME")
static const trait_id trait_NAUSEA ("NAUSEA")
static const trait_id trait_STRONGSTOMACH ("STRONGSTOMACH")
static const trait_id trait_VOMITOUS ("VOMITOUS")
static const trait_id trait_WEAKSTOMACH ("WEAKSTOMACH")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_weed_high ("weed_high")
Variable Documentation
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
Referenced by character_effects::calc_focus_equilibrium().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by character_effects::intimidation().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by character_effects::vomit_mod().
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by character_effects::vomit_mod().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by character_effects::calc_focus_equilibrium(), and character_effects::get_pain_penalty().
trait_INT_SLIME
const trait_id trait_INT_SLIME("INT_SLIME") ("INT_SLIME") static
Referenced by character_effects::get_pain_penalty().
trait_NAUSEA
const trait_id trait_NAUSEA("NAUSEA") ("NAUSEA") static
Referenced by character_effects::vomit_mod().
trait_STRONGSTOMACH
const trait_id trait_STRONGSTOMACH("STRONGSTOMACH") ("STRONGSTOMACH") static
Referenced by character_effects::vomit_mod().
trait_VOMITOUS
const trait_id trait_VOMITOUS("VOMITOUS") ("VOMITOUS") static
Referenced by character_effects::vomit_mod().
trait_WEAKSTOMACH
const trait_id trait_WEAKSTOMACH("WEAKSTOMACH") ("WEAKSTOMACH") static
Referenced by character_effects::vomit_mod().