Cataclysm BN: src/character_functions.cpp File Reference
character_functions.cpp File Reference
#include "character_functions.h"
#include "bionics.h"
#include "calendar.h"
#include "character_martial_arts.h"
#include "character.h"
#include "creature.h"
#include "handle_liquid.h"
#include "itype.h"
#include "make_static.h"
#include "map_iterator.h"
#include "player.h"
#include "rng.h"
#include "submap.h"
#include "trap.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather_gen.h"
#include "weather.h"
Namespaces
namespace character_funcs
Functions
static const std::string flag_FUNGUS ("FUNGUS")
static const std::string flag_SWIMMABLE ("SWIMMABLE")
time_duration character_funcs::estimate_effect_dur (int skill_lvl, const efftype_id &effect, const time_duration &error_magnitude, int threshold, const Creature &target)
Estimate effect duration based on relevant skill.
void character_funcs::siphon (Character &ch, vehicle &veh, const itype_id &desired_liquid)
Siphons fuel (if available) from the specified vehicle into container or similar via game::handle_liquid.
bool character_funcs::is_fun_to_read (const Character &ch, const item &book)
Returns whether character considers it fun to read the book.
int character_funcs::get_book_fun_for (const Character &ch, const item &book)
Returns enjoyability value of a book for given character.
comfort_response_t character_funcs::base_comfort_value (const Character &who, const tripoint &p)
Rate point's ability to serve as a bed.
int character_funcs::rate_sleep_spot (const Character &who, const tripoint &p)
Rate point's ability to serve as a bed.
bool character_funcs::roll_can_sleep (Character &who)
Checked each turn during "lying_down", returns true if the avatar falls asleep.
bool character_funcs::can_interface_armor (const Character &who)
Check whether character has an active bionic capable of interfacing with power armor.
std::string character_funcs::fmt_wielded_weapon (const Character &who)
Get the formatted name of the currently wielded item (if any) with current gun mode (if gun)
void character_funcs::add_pain_msg (const Character &who, int val, body_part bp)
Add message describing how character feels pain.
float character_funcs::fine_detail_vision_mod (const Character &who)
Calculates multiplier for the time taken to perform tasks that require detail vision (reading, crafting, etc.).
float character_funcs::fine_detail_vision_mod (const Character &who, const tripoint &p)
bool character_funcs::can_see_fine_details (const Character &who)
Checks whether character vision at given pos is good enough to see fine details.
bool character_funcs::can_see_fine_details (const Character &who, const tripoint &p)
Variables
static const trait_id trait_CANNIBAL ("CANNIBAL")
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_EASYSLEEPER ("EASYSLEEPER")
static const trait_id trait_EASYSLEEPER2 ("EASYSLEEPER2")
static const trait_id trait_INSOMNIA ("INSOMNIA")
static const trait_id trait_LOVES_BOOKS ("LOVES_BOOKS")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PER_SLIME_OK ("PER_SLIME_OK")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_SAPIOVORE ("SAPIOVORE")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_THRESH_SPIDER ("THRESH_SPIDER")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
static const trait_id trait_WEB_SPINNER ("WEB_SPINNER")
static const trait_id trait_WEB_WALKER ("WEB_WALKER")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_darkness ("darkness")
static const efftype_id effect_meth ("meth")
static const bionic_id bio_soporific ("bio_soporific")
static const itype_id itype_cookbook_human ("cookbook_human")
Function Documentation
flag_FUNGUS()
static const std::string flag_FUNGUS ("FUNGUS") static
Referenced by character_funcs::base_comfort_value().
flag_SWIMMABLE()
static const std::string flag_SWIMMABLE ("SWIMMABLE") static
Referenced by character_funcs::base_comfort_value().
Variable Documentation
bio_soporific
const bionic_id bio_soporific("bio_soporific") ("bio_soporific") static
Referenced by character_funcs::rate_sleep_spot(), and character_funcs::roll_can_sleep().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by character_funcs::fine_detail_vision_mod().
effect_darkness
const efftype_id effect_darkness("darkness") ("darkness") static
Referenced by character_funcs::fine_detail_vision_mod().
effect_meth
const efftype_id effect_meth("meth") ("meth") static
Referenced by character_funcs::roll_can_sleep().
itype_cookbook_human
const itype_id itype_cookbook_human("cookbook_human") ("cookbook_human") static
Referenced by character_funcs::get_book_fun_for(), and character_funcs::is_fun_to_read().
trait_CANNIBAL
const trait_id trait_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by character_funcs::get_book_fun_for(), and character_funcs::is_fun_to_read().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by character_funcs::base_comfort_value().
trait_EASYSLEEPER
const trait_id trait_EASYSLEEPER("EASYSLEEPER") ("EASYSLEEPER") static
Referenced by character_funcs::rate_sleep_spot().
trait_EASYSLEEPER2
const trait_id trait_EASYSLEEPER2("EASYSLEEPER2") ("EASYSLEEPER2") static
Referenced by character_funcs::rate_sleep_spot().
trait_INSOMNIA
const trait_id trait_INSOMNIA("INSOMNIA") ("INSOMNIA") static
Referenced by character_funcs::rate_sleep_spot().
trait_LOVES_BOOKS
const trait_id trait_LOVES_BOOKS("LOVES_BOOKS") ("LOVES_BOOKS") static
Referenced by character_funcs::get_book_fun_for().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by character_funcs::base_comfort_value().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by character_funcs::add_pain_msg().
trait_PER_SLIME_OK
const trait_id trait_PER_SLIME_OK("PER_SLIME_OK") ("PER_SLIME_OK") static
Referenced by character_funcs::fine_detail_vision_mod().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by character_funcs::get_book_fun_for(), and character_funcs::is_fun_to_read().
trait_SAPIOVORE
const trait_id trait_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by character_funcs::get_book_fun_for(), and character_funcs::is_fun_to_read().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by character_funcs::base_comfort_value().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by character_funcs::get_book_fun_for(), and character_funcs::is_fun_to_read().
trait_THRESH_SPIDER
const trait_id trait_THRESH_SPIDER("THRESH_SPIDER") ("THRESH_SPIDER") static
Referenced by character_funcs::base_comfort_value().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by character_funcs::base_comfort_value(), and character_funcs::rate_sleep_spot().
trait_WEB_SPINNER
const trait_id trait_WEB_SPINNER("WEB_SPINNER") ("WEB_SPINNER") static
Referenced by character_funcs::base_comfort_value().
trait_WEB_WALKER
const trait_id trait_WEB_WALKER("WEB_WALKER") ("WEB_WALKER") static
Referenced by character_funcs::base_comfort_value().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by character_funcs::base_comfort_value().