Cataclysm BN: src/character_turn.cpp File Reference
character_turn.cpp File Reference
#include "character_turn.h"
#include "bionics.h"
#include "calendar.h"
#include "character_effects.h"
#include "character_functions.h"
#include "character_stat.h"
#include "character_martial_arts.h"
#include "character.h"
#include "creature.h"
#include "game.h"
#include "handle_liquid.h"
#include "itype.h"
#include "magic_enchantment.h"
#include "mutation.h"
#include "overmapbuffer.h"
#include "make_static.h"
#include "map_iterator.h"
#include "morale.h"
#include "player.h"
#include "rng.h"
#include "submap.h"
#include "trap.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather_gen.h"
#include "weather.h"
Namespaces
namespace character_funcs
Functions
void character_funcs::update_body_wetness (Character &who, const w_point &weather)
Maintains body wetness and handles the rate at which the player dries.
void character_funcs::do_pause (Character &who)
Do pause action ('.
void character_funcs::search_surroundings (Character &who)
Search surrounding squares for traps (and maybe other things in the future).
void character_funcs::update_mental_focus (Character &who)
Uses calc_focus_change to update the player's current focus.
Variables
static const trait_id trait_ACIDBLOOD ("ACIDBLOOD")
static const trait_id trait_ARACHNID_ARMS_OK ("ARACHNID_ARMS_OK")
static const trait_id trait_ARACHNID_ARMS ("ARACHNID_ARMS")
static const trait_id trait_CHITIN_FUR ("CHITIN_FUR")
static const trait_id trait_CHITIN_FUR2 ("CHITIN_FUR2")
static const trait_id trait_CHITIN_FUR3 ("CHITIN_FUR3")
static const trait_id trait_CHITIN2 ("CHITIN2")
static const trait_id trait_CHITIN3 ("CHITIN3")
static const trait_id trait_COLDBLOOD4 ("COLDBLOOD4")
static const trait_id trait_COMPOUND_EYES ("COMPOUND_EYES")
static const trait_id trait_DEBUG_BIONIC_POWER ("DEBUG_BIONIC_POWER")
static const trait_id trait_EATHEALTH ("EATHEALTH")
static const trait_id trait_FAT ("FAT")
static const trait_id trait_FELINE_FUR ("FELINE_FUR")
static const trait_id trait_FUR ("FUR")
static const trait_id trait_INSECT_ARMS_OK ("INSECT_ARMS_OK")
static const trait_id trait_INSECT_ARMS ("INSECT_ARMS")
static const trait_id trait_LIGHTFUR ("LIGHTFUR")
static const trait_id trait_LUPINE_FUR ("LUPINE_FUR")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_NOMAD ("NOMAD")
static const trait_id trait_NOMAD2 ("NOMAD2")
static const trait_id trait_NOMAD3 ("NOMAD3")
static const trait_id trait_PARAIMMUNE ("PARAIMMUNE")
static const trait_id trait_SLIMY ("SLIMY")
static const trait_id trait_STIMBOOST ("STIMBOOST")
static const trait_id trait_SUNLIGHT_DEPENDENT ("SUNLIGHT_DEPENDENT")
static const trait_id trait_THICK_SCALES ("THICK_SCALES")
static const trait_id trait_URSINE_FUR ("URSINE_FUR")
static const trait_id trait_WEBBED ("WEBBED")
static const trait_id trait_WHISKERS_RAT ("WHISKERS_RAT")
static const trait_id trait_WHISKERS ("WHISKERS")
static const efftype_id effect_bloodworms ("bloodworms")
static const efftype_id effect_brainworms ("brainworms")
static const efftype_id effect_darkness ("darkness")
static const efftype_id effect_depressants ("depressants")
static const efftype_id effect_dermatik ("dermatik")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_happy ("happy")
static const efftype_id effect_irradiated ("irradiated")
static const efftype_id effect_masked_scent ("masked_scent")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_paincysts ("paincysts")
static const efftype_id effect_pkill ("pkill")
static const efftype_id effect_sad ("sad")
static const efftype_id effect_sleep_deprived ("sleep_deprived")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_stim_overdose ("stim_overdose")
static const efftype_id effect_stim ("stim")
static const efftype_id effect_tapeworm ("tapeworm")
static const efftype_id effect_thirsty ("thirsty")
static const skill_id skill_swimming ("swimming")
static const bionic_id bio_ground_sonar ("bio_ground_sonar")
static const bionic_id bio_hydraulics ("bio_hydraulics")
static const bionic_id bio_speed ("bio_speed")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_UPS_off ("UPS_off")
static const itype_id itype_UPS ("UPS")
Variable Documentation
bio_ground_sonar
const bionic_id bio_ground_sonar("bio_ground_sonar") ("bio_ground_sonar") static
Referenced by character_funcs::search_surroundings().
bio_hydraulics
const bionic_id bio_hydraulics("bio_hydraulics") ("bio_hydraulics") static
Referenced by Character::reset_stats().
bio_speed
const bionic_id bio_speed("bio_speed") ("bio_speed") static
Referenced by Character::recalc_speed_bonus().
effect_bloodworms
const efftype_id effect_bloodworms("bloodworms") ("bloodworms") static
Referenced by Character::process_effects_internal().
effect_brainworms
const efftype_id effect_brainworms("brainworms") ("brainworms") static
Referenced by Character::process_effects_internal().
effect_darkness
const efftype_id effect_darkness("darkness") ("darkness") static
Referenced by Character::process_effects_internal().
effect_depressants
const efftype_id effect_depressants("depressants") ("depressants") static
Referenced by Character::reset_stats().
effect_dermatik
const efftype_id effect_dermatik("dermatik") ("dermatik") static
Referenced by Character::process_effects_internal().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by character_funcs::do_pause().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by Character::process_effects_internal().
effect_happy
const efftype_id effect_happy("happy") ("happy") static
Referenced by Character::reset_stats().
effect_irradiated
const efftype_id effect_irradiated("irradiated") ("irradiated") static
Referenced by Character::reset_stats().
effect_masked_scent
const efftype_id effect_masked_scent("masked_scent") ("masked_scent") static
Referenced by Character::process_turn().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::process_turn().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by character_funcs::do_pause().
effect_paincysts
const efftype_id effect_paincysts("paincysts") ("paincysts") static
Referenced by Character::process_effects_internal().
effect_pkill
const efftype_id effect_pkill("pkill") ("pkill") static
Referenced by Character::reset_stats().
effect_sad
const efftype_id effect_sad("sad") ("sad") static
Referenced by Character::reset_stats().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Character::process_turn().
effect_sleep_deprived
const efftype_id effect_sleep_deprived("sleep_deprived") ("sleep_deprived") static
Referenced by Character::reset_stats().
effect_stim
const efftype_id effect_stim("stim") ("stim") static
Referenced by Character::reset_stats().
effect_stim_overdose
const efftype_id effect_stim_overdose("stim_overdose") ("stim_overdose") static
Referenced by Character::reset_stats().
effect_tapeworm
const efftype_id effect_tapeworm("tapeworm") ("tapeworm") static
Referenced by Character::process_effects_internal().
effect_thirsty
const efftype_id effect_thirsty("thirsty") ("thirsty") static
Referenced by Character::reset_stats().
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
Referenced by Character::process_items().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by Character::process_items().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by Character::process_items().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by character_funcs::do_pause().
trait_ACIDBLOOD
const trait_id trait_ACIDBLOOD("ACIDBLOOD") ("ACIDBLOOD") static
Referenced by Character::process_effects_internal().
trait_ARACHNID_ARMS
const trait_id trait_ARACHNID_ARMS("ARACHNID_ARMS") ("ARACHNID_ARMS") static
Referenced by Character::reset_stats().
trait_ARACHNID_ARMS_OK
const trait_id trait_ARACHNID_ARMS_OK("ARACHNID_ARMS_OK") ("ARACHNID_ARMS_OK") static
Referenced by Character::reset_stats().
trait_CHITIN2
const trait_id trait_CHITIN2("CHITIN2") ("CHITIN2") static
Referenced by Character::reset_stats().
trait_CHITIN3
const trait_id trait_CHITIN3("CHITIN3") ("CHITIN3") static
Referenced by Character::reset_stats().
trait_CHITIN_FUR
const trait_id trait_CHITIN_FUR("CHITIN_FUR") ("CHITIN_FUR") static
Referenced by character_funcs::update_body_wetness().
trait_CHITIN_FUR2
const trait_id trait_CHITIN_FUR2("CHITIN_FUR2") ("CHITIN_FUR2") static
Referenced by character_funcs::update_body_wetness().
trait_CHITIN_FUR3
const trait_id trait_CHITIN_FUR3("CHITIN_FUR3") ("CHITIN_FUR3") static
Referenced by Character::reset_stats(), and character_funcs::update_body_wetness().
trait_COLDBLOOD4
const trait_id trait_COLDBLOOD4("COLDBLOOD4") ("COLDBLOOD4") static
Referenced by Character::recalc_speed_bonus().
trait_COMPOUND_EYES
const trait_id trait_COMPOUND_EYES("COMPOUND_EYES") ("COMPOUND_EYES") static
Referenced by Character::reset_stats().
trait_DEBUG_BIONIC_POWER
const trait_id trait_DEBUG_BIONIC_POWER("DEBUG_BIONIC_POWER") ("DEBUG_BIONIC_POWER") static
Referenced by Character::process_turn().
trait_EATHEALTH
const trait_id trait_EATHEALTH("EATHEALTH") ("EATHEALTH") static
Referenced by Character::process_effects_internal().
trait_FAT
const trait_id trait_FAT("FAT") ("FAT") static
Referenced by Character::process_one_effect().
trait_FELINE_FUR
const trait_id trait_FELINE_FUR("FELINE_FUR") ("FELINE_FUR") static
Referenced by character_funcs::update_body_wetness().
trait_FUR
const trait_id trait_FUR("FUR") ("FUR") static
Referenced by character_funcs::update_body_wetness().
trait_INSECT_ARMS
const trait_id trait_INSECT_ARMS("INSECT_ARMS") ("INSECT_ARMS") static
Referenced by Character::reset_stats().
trait_INSECT_ARMS_OK
const trait_id trait_INSECT_ARMS_OK("INSECT_ARMS_OK") ("INSECT_ARMS_OK") static
Referenced by Character::reset_stats().
trait_LIGHTFUR
const trait_id trait_LIGHTFUR("LIGHTFUR") ("LIGHTFUR") static
Referenced by character_funcs::update_body_wetness().
trait_LUPINE_FUR
const trait_id trait_LUPINE_FUR("LUPINE_FUR") ("LUPINE_FUR") static
Referenced by character_funcs::update_body_wetness().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by Character::process_effects_internal().
trait_NOMAD
const trait_id trait_NOMAD("NOMAD") ("NOMAD") static
Referenced by Character::process_turn().
trait_NOMAD2
const trait_id trait_NOMAD2("NOMAD2") ("NOMAD2") static
Referenced by Character::process_turn().
trait_NOMAD3
const trait_id trait_NOMAD3("NOMAD3") ("NOMAD3") static
Referenced by Character::process_turn().
trait_PARAIMMUNE
const trait_id trait_PARAIMMUNE("PARAIMMUNE") ("PARAIMMUNE") static
Referenced by Character::process_effects_internal().
trait_SLIMY
const trait_id trait_SLIMY("SLIMY") ("SLIMY") static
Referenced by character_funcs::update_body_wetness().
trait_STIMBOOST
const trait_id trait_STIMBOOST("STIMBOOST") ("STIMBOOST") static
Referenced by Character::reset_stats().
trait_SUNLIGHT_DEPENDENT
const trait_id trait_SUNLIGHT_DEPENDENT("SUNLIGHT_DEPENDENT") ("SUNLIGHT_DEPENDENT") static
Referenced by Character::recalc_speed_bonus().
trait_THICK_SCALES
const trait_id trait_THICK_SCALES("THICK_SCALES") ("THICK_SCALES") static
Referenced by Character::reset_stats().
trait_URSINE_FUR
const trait_id trait_URSINE_FUR("URSINE_FUR") ("URSINE_FUR") static
Referenced by character_funcs::update_body_wetness().
trait_WEBBED
const trait_id trait_WEBBED("WEBBED") ("WEBBED") static
Referenced by Character::reset_stats().
trait_WHISKERS
const trait_id trait_WHISKERS("WHISKERS") ("WHISKERS") static
Referenced by Character::reset_stats().
trait_WHISKERS_RAT
const trait_id trait_WHISKERS_RAT("WHISKERS_RAT") ("WHISKERS_RAT") static
Referenced by Character::reset_stats().