Cataclysm BN: src/character.cpp File Reference
character.cpp File Reference
#include "character.h"
#include "character_encumbrance.h"
#include <algorithm>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <numeric>
#include <ostream>
#include <type_traits>
#include "action.h"
#include "activity_handlers.h"
#include "activity_actor_definitions.h"
#include "anatomy.h"
#include "avatar.h"
#include "bionics.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "character_stat.h"
#include "clzones.h"
#include "colony.h"
#include "construction.h"
#include "consumption.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "debug.h"
#include "disease.h"
#include "effect.h"
#include "event.h"
#include "event_bus.h"
#include "field.h"
#include "field_type.h"
#include "fire.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "item_contents.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "lightmap.h"
#include "line.h"
#include "make_static.h"
#include "magic_enchantment.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "material.h"
#include "math_defines.h"
#include "memorial_logger.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "morale.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overlay_ordering.h"
#include "overmapbuffer.h"
#include "pathfinding.h"
#include "player.h"
#include "profession.h"
#include "recipe_dictionary.h"
#include "ret_val.h"
#include "rng.h"
#include "scent_map.h"
#include "skill.h"
#include "skill_boost.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_utils.h"
#include "submap.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "ui_manager.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_interact.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weather_gen.h"
Namespaces
namespace io
namespace vision
namespace warmth
Functions
static const std::string flag_ACTIVE_CLOAKING ("ACTIVE_CLOAKING")
static const std::string flag_ALLOWS_NATURAL_ATTACKS ("ALLOWS_NATURAL_ATTACKS")
static const std::string flag_AURA ("AURA")
static const std::string flag_BELTED ("BELTED")
static const std::string flag_BLIND ("BLIND")
static const std::string flag_DEAF ("DEAF")
static const std::string flag_EFFECT_INVISIBLE ("EFFECT_INVISIBLE")
static const std::string flag_EFFECT_NIGHT_VISION ("EFFECT_NIGHT_VISION")
static const std::string flag_FIX_NEARSIGHT ("FIX_NEARSIGHT")
static const std::string flag_FUNGUS ("FUNGUS")
static const std::string flag_GNV_EFFECT ("GNV_EFFECT")
static const std::string flag_HELMET_COMPAT ("HELMET_COMPAT")
static const std::string flag_IR_EFFECT ("IR_EFFECT")
static const std::string flag_ONLY_ONE ("ONLY_ONE")
static const std::string flag_OUTER ("OUTER")
static const std::string flag_OVERSIZE ("OVERSIZE")
static const std::string flag_PARTIAL_DEAF ("PARTIAL_DEAF")
static const std::string flag_PERPETUAL ("PERPETUAL")
static const std::string flag_PERSONAL ("PERSONAL")
static const std::string flag_PLOWABLE ("PLOWABLE")
static const std::string flag_POWERARMOR_EXO ("POWERARMOR_EXO")
static const std::string flag_POWERARMOR_EXTERNAL ("POWERARMOR_EXTERNAL")
static const std::string flag_POWERARMOR_MOD ("POWERARMOR_MOD")
static const std::string flag_POWERARMOR_COMPATIBLE ("POWERARMOR_COMPATIBLE")
static const std::string flag_RESTRICT_HANDS ("RESTRICT_HANDS")
static const std::string flag_SEMITANGIBLE ("SEMITANGIBLE")
static const std::string flag_SKINTIGHT ("SKINTIGHT")
static const std::string flag_SPEEDLOADER ("SPEEDLOADER")
static const std::string flag_SPLINT ("SPLINT")
static const std::string flag_STR_DRAW ("STR_DRAW")
static const std::string flag_STURDY ("STURDY")
static const std::string flag_SWIM_GOGGLES ("SWIM_GOGGLES")
static const std::string flag_UNDERSIZE ("UNDERSIZE")
static const std::string flag_USE_UPS ("USE_UPS")
template<>
std::string io::enum_to_string< character_movemode > (character_movemode data)
Character & get_player_character ()
static void try_remove_downed (Character &c)
static void try_remove_bear_trap (Character &c)
static void try_remove_lightsnare (Character &c)
static void try_remove_heavysnare (Character &c)
static void try_remove_crushed (Character &c)
static bool try_remove_grab (Character &c)
static void try_remove_webs (Character &c)
float vision::threshold_for_nv_range (float range)
Returns the light level that darkness will have at this range from player.
float vision::nv_range_from_per (int per)
float vision::nv_range_from_eye_encumbrance (int enc)
template<typename T , typename Output >
void find_ammo_helper (T &src, const item &obj, bool empty, Output out, bool nested)
static void layer_item (char_encumbrance_data &vals, const item &it, std::array< layer_level, num_bp > &highest_layer_so_far, const Character &c)
static int wind_resistance_from_item_list (const std::vector< const item * > &items)
std::map< bodypart_id, int > warmth::wind_resistance_from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
Returns wind resistance provided by armor, etc.
static void apply_mut_encumbrance (char_encumbrance_data &vals, const trait_id &mut, const body_part_set &oversize)
static int get_speedydex_bonus (const int dex)
template<>
std::string io::enum_to_string< character_stat > (character_stat data)
int ticks_between (const time_point &from, const time_point &to, const time_duration &tick_length)
template<float mutation_branch::* member>
float calc_mutation_value (const std::vector< const mutation_branch * > &mutations)
template<float mutation_branch::* member>
float calc_mutation_value_additive (const std::vector< const mutation_branch * > &mutations)
template<float mutation_branch::* member>
float calc_mutation_value_multiplicative (const std::vector< const mutation_branch * > &mutations)
std::string get_stat_name (character_stat Stat)
Get translated name of a stat.
static void destroyed_armor_msg (Character &who, const std::string &pre_damage_name)
static void item_armor_enchantment_adjust (const Character &guy, damage_unit &du, const item &armor)
static void armor_enchantment_adjust (const Character &guy, damage_unit &du)
template<typename Acc = int const&(int const &, int const &)>
static std::map< bodypart_id, int > warmth::acc_clothing_warmth (const std::map< bodypart_id, std::vector< const item * > > &clothing_map, Acc accumulation_function)
std::map< bodypart_id, int > warmth::from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
std::map< bodypart_id, int > warmth::bonus_from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
std::map< bodypart_id, int > warmth::from_effects (const Character &c)
bool has_psy_protection (const Character &c, int partial_chance)
Returns true if the player has a psyshield artifact, or sometimes if wearing tinfoil.
Variables
static const activity_id ACT_MOVE_ITEMS ("ACT_MOVE_ITEMS")
static const activity_id ACT_TRAVELLING ("ACT_TRAVELLING")
static const activity_id ACT_TREE_COMMUNION ("ACT_TREE_COMMUNION")
static const activity_id ACT_TRY_SLEEP ("ACT_TRY_SLEEP")
static const activity_id ACT_WAIT_STAMINA ("ACT_WAIT_STAMINA")
static const bionic_id bio_eye_optic ("bio_eye_optic")
static const bionic_id bio_watch ("bio_watch")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_ai_waiting ("ai_waiting")
static const efftype_id effect_alarm_clock ("alarm_clock")
static const efftype_id effect_bandaged ("bandaged")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_blisters ("blisters")
static const efftype_id effect_bloated ("bloated")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_cold ("cold")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_corroding ("corroding")
static const efftype_id effect_cough_suppress ("cough_suppress")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_darkness ("darkness")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_earphones ("earphones")
static const efftype_id effect_foodpoison ("foodpoison")
static const efftype_id effect_frostbite ("frostbite")
static const efftype_id effect_frostbite_recovery ("frostbite_recovery")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_glowing ("glowing")
static const efftype_id effect_glowy_led ("glowy_led")
static const efftype_id effect_got_checked ("got_checked")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_grabbing ("grabbing")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_heating_bionic ("heating_bionic")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_hot ("hot")
static const efftype_id effect_hot_speed ("hot_speed")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_jetinjector ("jetinjector")
static const efftype_id effect_lack_sleep ("lack_sleep")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_melatonin_supplements ("melatonin")
static const efftype_id effect_meth ("meth")
static const efftype_id effect_masked_scent ("masked_scent")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_pkill1 ("pkill1")
static const efftype_id effect_pkill2 ("pkill2")
static const efftype_id effect_pkill3 ("pkill3")
static const efftype_id effect_recently_coughed ("recently_coughed")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_saddled ("monster_saddled")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_slept_through_alarm ("slept_through_alarm")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_took_prozac ("took_prozac")
static const efftype_id effect_took_xanax ("took_xanax")
static const efftype_id effect_webbed ("webbed")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_apparatus ("apparatus")
static const itype_id itype_beartrap ("beartrap")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const itype_id itype_fire ("fire")
static const itype_id itype_rm13_armor_on ("rm13_armor_on")
static const itype_id itype_rope_6 ("rope_6")
static const itype_id itype_snare_trigger ("snare_trigger")
static const itype_id itype_string_36 ("string_36")
static const itype_id itype_toolset ("toolset")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_UPS_off ("UPS_off")
static const itype_id itype_power_storage ("bio_power_storage")
static const itype_id itype_power_storage_mkII ("bio_power_storage_mkII")
static const itype_id itype_bio_armor ("bio_armor")
static const fault_id fault_bionic_nonsterile ("fault_bionic_nonsterile")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_throw ("throw")
static const species_id HUMAN ("HUMAN")
static const species_id ROBOT ("ROBOT")
static const trait_id trait_ACIDBLOOD ("ACIDBLOOD")
static const trait_id trait_ACIDPROOF ("ACIDPROOF")
static const trait_id trait_ADRENALINE ("ADRENALINE")
static const trait_id trait_ANTENNAE ("ANTENNAE")
static const trait_id trait_ANTLERS ("ANTLERS")
static const trait_id trait_BADBACK ("BADBACK")
static const trait_id trait_DEBUG_NODMG ("DEBUG_NODMG")
static const trait_id trait_SQUEAMISH ("SQUEAMISH")
static const trait_id trait_WOOLALLERGY ("WOOLALLERGY")
static const bionic_id bio_ads ("bio_ads")
static const bionic_id bio_blindfold ("bio_blindfold")
static const bionic_id bio_climate ("bio_climate")
static const bionic_id bio_cloak ("bio_cloak")
static const bionic_id bio_earplugs ("bio_earplugs")
static const bionic_id bio_ears ("bio_ears")
static const bionic_id bio_faraday ("bio_faraday")
static const bionic_id bio_flashlight ("bio_flashlight")
static const bionic_id bio_gills ("bio_gills")
static const bionic_id bio_ground_sonar ("bio_ground_sonar")
static const bionic_id bio_heatsink ("bio_heatsink")
static const bionic_id bio_infrared ("bio_infrared")
static const bionic_id bio_jointservo ("bio_jointservo")
static const bionic_id bio_laser ("bio_laser")
static const bionic_id bio_leukocyte ("bio_leukocyte")
static const bionic_id bio_lighter ("bio_lighter")
static const bionic_id bio_membrane ("bio_membrane")
static const bionic_id bio_memory ("bio_memory")
static const bionic_id bio_night_vision ("bio_night_vision")
static const bionic_id bio_railgun ("bio_railgun")
static const bionic_id bio_recycler ("bio_recycler")
static const bionic_id bio_shock_absorber ("bio_shock_absorber")
static const bionic_id bio_storage ("bio_storage")
static const bionic_id bio_synaptic_regen ("bio_synaptic_regen")
static const bionic_id bio_tattoo_led ("bio_tattoo_led")
static const bionic_id bio_tools ("bio_tools")
static const bionic_id bio_ups ("bio_ups")
static const bionic_id afs_bio_linguistic_coprocessor ("afs_bio_linguistic_coprocessor")
static const trait_id trait_BARK ("BARK")
static const trait_id trait_BIRD_EYE ("BIRD_EYE")
static const trait_id trait_CEPH_EYES ("CEPH_EYES")
static const trait_id trait_DEAF ("DEAF")
static const trait_id trait_DEBUG_CLOAK ("DEBUG_CLOAK")
static const trait_id trait_DEBUG_LS ("DEBUG_LS")
static const trait_id trait_DEBUG_NIGHTVISION ("DEBUG_NIGHTVISION")
static const trait_id trait_DEBUG_NOTEMP ("DEBUG_NOTEMP")
static const trait_id trait_DEBUG_STORAGE ("DEBUG_STORAGE")
static const trait_id trait_DISORGANIZED ("DISORGANIZED")
static const trait_id trait_DOWN ("DOWN")
static const trait_id trait_ELECTRORECEPTORS ("ELECTRORECEPTORS")
static const trait_id trait_FASTLEARNER ("FASTLEARNER")
static const trait_id trait_GILLS_CEPH ("GILLS_CEPH")
static const trait_id trait_GILLS ("GILLS")
static const trait_id trait_HEAVYSLEEPER ("HEAVYSLEEPER")
static const trait_id trait_HEAVYSLEEPER2 ("HEAVYSLEEPER2")
static const trait_id trait_HIBERNATE ("HIBERNATE")
static const trait_id trait_HOARDER ("HOARDER")
static const trait_id trait_HOLLOW_BONES ("HOLLOW_BONES")
static const trait_id trait_HORNS_POINTED ("HORNS_POINTED")
static const trait_id trait_INFRARED ("INFRARED")
static const trait_id trait_LEG_TENT_BRACE ("LEG_TENT_BRACE")
static const trait_id trait_LIGHT_BONES ("LIGHT_BONES")
static const trait_id trait_LIZ_IR ("LIZ_IR")
static const trait_id trait_M_DEPENDENT ("M_DEPENDENT")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_M_SKIN2 ("M_SKIN2")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_MEMBRANE ("MEMBRANE")
static const trait_id trait_MOREPAIN ("MORE_PAIN")
static const trait_id trait_MOREPAIN2 ("MORE_PAIN2")
static const trait_id trait_MOREPAIN3 ("MORE_PAIN3")
static const trait_id trait_MYOPIC ("MYOPIC")
static const trait_id trait_NO_THIRST ("NO_THIRST")
static const trait_id trait_NOMAD ("NOMAD")
static const trait_id trait_NOMAD2 ("NOMAD2")
static const trait_id trait_NOMAD3 ("NOMAD3")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PACKMULE ("PACKMULE")
static const trait_id trait_PADDED_FEET ("PADDED_FEET")
static const trait_id trait_PAINRESIST_TROGLO ("PAINRESIST_TROGLO")
static const trait_id trait_PAINRESIST ("PAINRESIST")
static const trait_id trait_PAWS_LARGE ("PAWS_LARGE")
static const trait_id trait_PAWS ("PAWS")
static const trait_id trait_PER_SLIME_OK ("PER_SLIME_OK")
static const trait_id trait_PER_SLIME ("PER_SLIME")
static const trait_id trait_PROF_FOODP ("PROF_FOODP")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_RADIOGENIC ("RADIOGENIC")
static const trait_id trait_ROOTS2 ("ROOTS2")
static const trait_id trait_ROOTS3 ("ROOTS3")
static const trait_id trait_SEESLEEP ("SEESLEEP")
static const trait_id trait_SELFAWARE ("SELFAWARE")
static const trait_id trait_SHELL ("SHELL")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHOUT2 ("SHOUT2")
static const trait_id trait_SHOUT3 ("SHOUT3")
static const trait_id trait_SLIMESPAWNER ("SLIMESPAWNER")
static const trait_id trait_SLIMY ("SLIMY")
static const trait_id trait_SLOWLEARNER ("SLOWLEARNER")
static const trait_id trait_STRONGSTOMACH ("STRONGSTOMACH")
static const trait_id trait_THRESH_CEPHALOPOD ("THRESH_CEPHALOPOD")
static const trait_id trait_THRESH_INSECT ("THRESH_INSECT")
static const trait_id trait_THRESH_PLANT ("THRESH_PLANT")
static const trait_id trait_THRESH_SPIDER ("THRESH_SPIDER")
static const trait_id trait_TRANSPIRATION ("TRANSPIRATION")
static const trait_id trait_URSINE_EYE ("URSINE_EYE")
static const trait_id trait_VISCOUS ("VISCOUS")
static const trait_id trait_WEBBED ("WEBBED")
static const flag_str_id flag_COLLAR ("COLLAR")
static const flag_str_id flag_HOOD ("HOOD")
static const flag_str_id flag_POCKETS ("POCKETS")
static const flag_str_id flag_CLIMATE_CONTROL ("CLIMATE_CONTROL")
static const flag_str_id flag_BIONIC_ARMOR_INTERFACE ("BIONIC_ARMOR_INTERFACE")
static const mtype_id mon_player_blob ("mon_player_blob")
static const mtype_id mon_shadow_snake ("mon_shadow_snake")
static const std::map< std::string, std::function< float(std::vector< const mutation_branch * >)> > mutation_value_map
Function Documentation
apply_mut_encumbrance()
static void apply_mut_encumbrance (char_encumbrance_data & vals, const trait_id & mut, const body_part_set & oversize) static
Definition at line 3863 of file character.cpp.
{
    for( const std::pair<const body_part, int> &enc : mut->encumbrance_always ) {
        vals.elems[enc.first].encumbrance += enc.second;
    }
    for( const std::pair<const body_part, int> &enc : mut->encumbrance_covered ) {
        if( !oversize.test( enc.first ) ) {
            vals.elems[enc.first].encumbrance += enc.second;
        }
    }
}
References char_encumbrance_data::elems, mutation_branch::encumbrance_always, mutation_branch::encumbrance_covered, and body_part_set::test().
Referenced by Character::mut_cbm_encumb().
armor_enchantment_adjust()
static void armor_enchantment_adjust (const Character & guy, damage_unit & du) static
Definition at line 7854 of file character.cpp.
{
    switch( du.type ) {
        case DT_ACID:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_ACID );
            break;
        case DT_BASH:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_BASH );
            break;
        case DT_BIOLOGICAL:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_BIO );
            break;
        case DT_COLD:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_COLD );
            break;
        case DT_CUT:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_CUT );
            break;
        case DT_ELECTRIC:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_ELEC );
            break;
        case DT_HEAT:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_HEAT );
            break;
        case DT_STAB:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_STAB );
            break;
        case DT_BULLET:
            du.amount += guy.bonus_from_enchantments( du.amount, enchant_vals::mod::ARMOR_BULLET );
            break;
        default:
            return;
    }
    du.amount = std::max( 0.0f, du.amount );
}
References damage_unit::amount, enchant_vals::ARMOR_ACID, enchant_vals::ARMOR_BASH, enchant_vals::ARMOR_BIO, enchant_vals::ARMOR_BULLET, enchant_vals::ARMOR_COLD, enchant_vals::ARMOR_CUT, enchant_vals::ARMOR_ELEC, enchant_vals::ARMOR_HEAT, enchant_vals::ARMOR_STAB, Character::bonus_from_enchantments(), DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_STAB, and damage_unit::type.
Referenced by Character::absorb_hit().
calc_mutation_value()
template<float mutation_branch::* member> float calc_mutation_value (const std::vector< const mutation_branch * > & mutations)
Definition at line 6443 of file character.cpp.
{
    float lowest = 0.0f;
    float highest = 0.0f;
    for( const mutation_branch *mut : mutations ) {
        float val = mut->*member;
        lowest = std::min( lowest, val );
        highest = std::max( highest, val );
    }
    return std::min( 0.0f, lowest ) + std::max( 0.0f, highest );
}
References mapgen_defer::member.
calc_mutation_value_additive()
template<float mutation_branch::* member> float calc_mutation_value_additive (const std::vector< const mutation_branch * > & mutations)
Definition at line 6457 of file character.cpp.
{
    float ret = 0.0f;
    for( const mutation_branch *mut : mutations ) {
        ret += mut->*member;
    }
    return ret;
}
References mapgen_defer::member, and cata::hash64_detail::ret.
calc_mutation_value_multiplicative()
template<float mutation_branch::* member> float calc_mutation_value_multiplicative (const std::vector< const mutation_branch * > & mutations)
Definition at line 6467 of file character.cpp.
{
    float ret = 1.0f;
    for( const mutation_branch *mut : mutations ) {
        ret *= mut->*member;
    }
    return ret;
}
References mapgen_defer::member, and cata::hash64_detail::ret.
destroyed_armor_msg()
static void destroyed_armor_msg (Character & who, const std::string & pre_damage_name) static
Definition at line 7800 of file character.cpp.
{
    if( who.is_avatar() ) {
        g->memorial().add(
            //~ %s is armor name
            pgettext( "memorial_male", "Worn %s was completely destroyed." ),
            pgettext( "memorial_female", "Worn %s was completely destroyed." ),
            pre_damage_name );
    }
    who.add_msg_player_or_npc( m_bad, _( "Your %s is completely destroyed!" ),
                               _( "<npcname>'s %s is completely destroyed!" ),
                               pre_damage_name );
}
References _, Creature::add_msg_player_or_npc(), g, Creature::is_avatar(), m_bad, and pgettext().
Referenced by Character::absorb_hit().
find_ammo_helper()
template<typename T , typename Output > void find_ammo_helper (T & src, const item & obj, bool empty, Output out, bool nested)
Definition at line 2504 of file character.cpp.
{
    if( obj.is_watertight_container() ) {
        if( !obj.is_container_empty() ) {
            auto contents_id = obj.contents.front().typeId();
            // Look for containers with the same type of liquid as that already in our container
            src.visit_items( [&src, &nested, &out, &contents_id, &obj]( item * node ) {
                if( node == &obj ) {
                    // This stops containers and magazines counting *themselves* as ammo sources.
                    return VisitResponse::SKIP;
                }
                if( node->is_container() && !node->is_container_empty() &&
                    node->contents.front().typeId() == contents_id ) {
                    out = item_location( src, node );
                }
                return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
            } );
        } else {
            // Look for containers with any liquid
            src.visit_items( [&src, &nested, &out]( item * node ) {
                if( node->is_container() && node->contents_made_of( LIQUID ) ) {
                    out = item_location( src, node );
                }
                return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
            } );
        }
    }
    if( obj.magazine_integral() ) {
        // find suitable ammo excluding that already loaded in magazines
        const std::set<ammotype> &ammo = obj.ammo_types();
        const auto mags = obj.magazine_compatible();
        src.visit_items( [&src, &nested, &out, &mags, ammo]( item * node ) {
            if( node->is_gun() || node->is_tool() ) {
                // guns/tools never contain usable ammo so most efficient to skip them now
                return VisitResponse::SKIP;
            }
            if( !node->made_of( SOLID ) ) {
                // some liquids are ammo but we can't reload with them unless within a container or frozen
                return VisitResponse::SKIP;
            }
            if( node->is_ammo_container() && !node->contents.empty() &&
                !node->contents_made_of( SOLID ) ) {
                for( const ammotype &at : ammo ) {
                    if( node->contents.front().ammo_type() == at ) {
                        out = item_location( src, node );
                    }
                }
                return VisitResponse::SKIP;
            }
            for( const ammotype &at : ammo ) {
                if( node->ammo_type() == at ) {
                    out = item_location( src, node );
                }
            }
            if( node->is_magazine() && node->has_flag( flag_SPEEDLOADER ) ) {
                if( mags.count( node->typeId() ) && node->ammo_remaining() ) {
                    out = item_location( src, node );
                }
            }
            return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
        } );
    } else {
        // find compatible magazines excluding those already loaded in tools/guns
        const auto mags = obj.magazine_compatible();
        src.visit_items( [&src, &nested, &out, mags, empty]( item * node ) {
            if( node->is_gun() || node->is_tool() ) {
                return VisitResponse::SKIP;
            }
            if( node->is_magazine() ) {
                if( mags.count( node->typeId() ) && ( node->ammo_remaining() || empty ) ) {
                    out = item_location( src, node );
                }
                return VisitResponse::SKIP;
            }
            return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
        } );
    }
}
References item::ammo_type(), item::contents, item::contents_made_of(), item_contents::empty(), flag_SPEEDLOADER(), item_contents::front(), item::has_flag(), item::is_ammo_container(), item::is_container(), item::is_container_empty(), item::is_gun(), item::is_magazine(), item::is_tool(), LIQUID, item::made_of(), NEXT, int_id< T >::obj(), SKIP, SOLID, and item::typeId().
Referenced by Character::find_ammo().
flag_ACTIVE_CLOAKING()
static const std::string flag_ACTIVE_CLOAKING ("ACTIVE_CLOAKING") static
Referenced by Character::is_wearing_active_optcloak().
flag_ALLOWS_NATURAL_ATTACKS()
static const std::string flag_ALLOWS_NATURAL_ATTACKS ("ALLOWS_NATURAL_ATTACKS") static
Referenced by Character::active_light().
flag_AURA()
static const std::string flag_AURA ("AURA") static
Referenced by Character::active_light(), Character::can_wear(), Character::is_wearing_helmet(), and Character::is_wearing_shoes().
flag_BELTED()
static const std::string flag_BELTED ("BELTED") static
Referenced by Character::can_wear(), and Character::is_wearing_shoes().
flag_BLIND()
static const std::string flag_BLIND ("BLIND") static
Referenced by Character::is_blind().
flag_DEAF()
static const std::string flag_DEAF ("DEAF") static
Referenced by Character::is_deaf(), and Character::is_immune_effect().
flag_EFFECT_INVISIBLE()
static const std::string flag_EFFECT_INVISIBLE ("EFFECT_INVISIBLE") static
Referenced by Character::is_invisible().
flag_EFFECT_NIGHT_VISION()
static const std::string flag_EFFECT_NIGHT_VISION ("EFFECT_NIGHT_VISION") static
Referenced by Character::has_nv().
flag_FIX_NEARSIGHT()
static const std::string flag_FIX_NEARSIGHT ("FIX_NEARSIGHT") static
Referenced by Character::recalc_sight_limits().
flag_FUNGUS()
static const std::string flag_FUNGUS ("FUNGUS") static
Referenced by Character::in_climate_control(), and Character::is_deaf().
flag_GNV_EFFECT()
static const std::string flag_GNV_EFFECT ("GNV_EFFECT") static
Referenced by Character::has_nv().
flag_HELMET_COMPAT()
static const std::string flag_HELMET_COMPAT ("HELMET_COMPAT") static
Referenced by Character::can_wear(), Character::head_cloth_encumbrance(), and Character::is_wearing_helmet().
flag_IR_EFFECT()
static const std::string flag_IR_EFFECT ("IR_EFFECT") static
Referenced by Character::recalc_sight_limits().
flag_ONLY_ONE()
static const std::string flag_ONLY_ONE ("ONLY_ONE") static
Referenced by Character::can_wear().
flag_OUTER()
static const std::string flag_OUTER ("OUTER") static
Referenced by Character::can_wear().
flag_OVERSIZE()
static const std::string flag_OVERSIZE ("OVERSIZE") static
Referenced by Character::can_wear(), Character::is_wearing_helmet(), and Character::mut_cbm_encumb().
flag_PARTIAL_DEAF()
static const std::string flag_PARTIAL_DEAF ("PARTIAL_DEAF") static
Referenced by Character::is_immune_effect().
flag_PERPETUAL()
static const std::string flag_PERPETUAL ("PERPETUAL") static
Referenced by Character::get_fuel_available().
flag_PERSONAL()
static const std::string flag_PERSONAL ("PERSONAL") static
Referenced by Character::active_light(), Character::can_wear(), Character::is_wearing_helmet(), and Character::is_wearing_shoes().
flag_PLOWABLE()
static const std::string flag_PLOWABLE ("PLOWABLE") static
Referenced by Character::rooted(), and Character::rooted_message().
flag_POWERARMOR_COMPATIBLE()
static const std::string flag_POWERARMOR_COMPATIBLE ("POWERARMOR_COMPATIBLE") static
Referenced by Character::can_wear().
flag_POWERARMOR_EXO()
static const std::string flag_POWERARMOR_EXO ("POWERARMOR_EXO") static
Referenced by Character::can_wear(), Character::is_wearing_active_power_armor(), and Character::is_wearing_power_armor().
flag_POWERARMOR_EXTERNAL()
static const std::string flag_POWERARMOR_EXTERNAL ("POWERARMOR_EXTERNAL") static
Referenced by Character::can_wear().
flag_POWERARMOR_MOD()
static const std::string flag_POWERARMOR_MOD ("POWERARMOR_MOD") static
Referenced by Character::can_swap(), and Character::can_wear().
flag_RESTRICT_HANDS()
static const std::string flag_RESTRICT_HANDS ("RESTRICT_HANDS") static
Referenced by Character::can_wear().
flag_SEMITANGIBLE()
static const std::string flag_SEMITANGIBLE ("SEMITANGIBLE") static
Referenced by Character::active_light(), Character::can_wear(), Character::head_cloth_encumbrance(), Character::is_wearing_helmet(), and Character::is_wearing_shoes().
flag_SKINTIGHT()
static const std::string flag_SKINTIGHT ("SKINTIGHT") static
Referenced by Character::can_wear(), Character::head_cloth_encumbrance(), Character::is_wearing_helmet(), and Character::is_wearing_shoes().
flag_SPEEDLOADER()
static const std::string flag_SPEEDLOADER ("SPEEDLOADER") static
Referenced by find_ammo_helper().
flag_SPLINT()
static const std::string flag_SPLINT ("SPLINT") static
Referenced by Character::body_window(), and Character::can_wear().
flag_STR_DRAW()
static const std::string flag_STR_DRAW ("STR_DRAW") static
Referenced by Character::meets_stat_requirements().
flag_STURDY()
static const std::string flag_STURDY ("STURDY") static
Referenced by Character::armor_absorb().
flag_SWIM_GOGGLES()
static const std::string flag_SWIM_GOGGLES ("SWIM_GOGGLES") static
Referenced by Character::recalc_sight_limits().
flag_UNDERSIZE()
static const std::string flag_UNDERSIZE ("UNDERSIZE") static
Referenced by Character::wear_item().
flag_USE_UPS()
static const std::string flag_USE_UPS ("USE_UPS") static
Referenced by Character::consume_charges(), Character::has_enough_charges(), and Character::use_charges().
get_player_character()
Character & get_player_character ()
Definition at line 382 of file character.cpp.
{
    return g->u;
}
Referenced by vehicle::act_on_map(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), Character::activate_bionic(), map::add_field(), monexamine::add_leash(), npc::address_needs(), npc::address_player(), map::apparent_light_helper(), Character::apply_damage(), npc::assess_danger(), item::book_info(), map::build_map_cache(), map::build_seen_cache(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), can_examine_at(), talk_function::caravan_dist(), npc::check_or_use_weapon_cbm(), ui::omap::choose_point(), npc::complain(), npc::complain_about(), construction_color(), npc::consume_food_from_camp(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), debug_menu::debug_menu_uilist(), debug_vision(), repair_item_actor::default_action(), ui::omap::display(), ui::omap::display_editor(), ui::omap::display_hordes(), ui::omap::display_scents(), ui::omap::display_visible_weather(), ui::omap::display_weather(), explosion_handler::do_blast_new(), npc::do_reload(), overmap_ui::draw_ascii(), npc::drop_items(), dialogue::dynamic_line(), explosion_handler::emp_blast(), npc::execute_action(), basecamp::faction_display(), npc::faction_display(), computer_session::failure_manhacks(), computer_session::failure_secubots(), mattack::fear_paralyze(), talk_function::field_build_1(), talk_function::field_build_2(), talk_function::field_harvest(), overmapbuffer::find_all_radio_stations(), npc::find_corpse_to_pulp(), npc::find_item(), overmapbuffer::find_radio_station(), mission_start::find_safety(), heal_actor::finish_using(), npc::form_opinion(), mattack::fungus_sprout(), map::generate_lightmap(), sfx::get_heard_angle(), get_mission_om_origin(), overmapbuffer::get_npcs_near_player(), overmap_ui::get_overmap_neighbors(), overmap_ui::get_overmap_path_to(), aim_activity_actor::get_weapon(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::goto_location(), ranged::gunmode_checks_weapon(), handbrake(), item::handle_pickup_ownership(), npc::handle_sound(), vehicle::handle_trap(), npc::heal_player(), npc::heal_self(), ranged::hit_with_aoe(), heal_actor::info(), defense_game::init_map(), is_player_outside(), ma_style_callback::key(), list_available_constructions(), npc::method_of_attack(), monexamine::mfriend_menu(), map_funcs::migo_nerve_cage_removal(), npc::move(), npc::move_away_from(), overmapbuffer::move_hordes(), map::move_vehicle(), npc::mug_player(), npc_throw(), player_morale::on_worn_item_washed(), vehicle::open_or_close(), vehicle::part_collision(), monexamine::pet_menu(), npc::pick_up_item(), pl_sees(), avatar_action::plthrow(), npc::pretend_heal(), overmapbuffer::process_mongroups(), mission_util::random_house_in_closest_city(), npc::reach_omt_destination(), item::ready_to_revive(), npc::regen_ai_cache(), monexamine::remove_battery(), monexamine::remove_leash(), reveal_destination(), mission_start::reveal_lab_train_depot(), mission_util::reveal_om_ter(), mission_start::reveal_refugee_center(), player_morale::set_worn(), map::shake_vehicle(), explosion_handler::shrapnel(), spell_effect_area(), vehicle::start_engine(), vehicle::thrust(), character_funcs::try_uncanny_dodge(), distribution_grid_tracker::update(), editmap::update_view_with_help(), vehicle::use_controls(), and npc::use_painkiller().
get_speedydex_bonus()
static int get_speedydex_bonus (const int dex) static
Definition at line 3972 of file character.cpp.
{
    static const std::string speedydex_min_dex( "SPEEDYDEX_MIN_DEX" );
    static const std::string speedydex_dex_speed( "SPEEDYDEX_DEX_SPEED" );
    // this is the number to be multiplied by the increment
    const int modified_dex = std::max( dex - get_option<int>( speedydex_min_dex ), 0 );
    return modified_dex * get_option<int>( speedydex_dex_speed );
}
Referenced by Character::get_speed().
get_stat_name()
std::string get_stat_name (character_stat Stat)
Get translated name of a stat.
Definition at line 7621 of file character.cpp.
{
    switch( Stat ) {
        // *INDENT-OFF*
    case character_stat::STRENGTH:     return pgettext( "strength stat", "STR" );
    case character_stat::DEXTERITY:    return pgettext( "dexterity stat", "DEX" );
    case character_stat::INTELLIGENCE: return pgettext( "intelligence stat", "INT" );
    case character_stat::PERCEPTION:   return pgettext( "perception stat", "PER" );
        // *INDENT-ON*
        default:
            return pgettext( "fake stat there's an error", "ERR" );
            break;
    }
    return pgettext( "fake stat there's an error", "ERR" );
}
References DEXTERITY, INTELLIGENCE, PERCEPTION, pgettext(), and STRENGTH.
Referenced by item::bionic_info().
has_psy_protection()
bool has_psy_protection (const Character & c, int partial_chance)
Returns true if the player has a psyshield artifact, or sometimes if wearing tinfoil.
Definition at line 10349 of file character.cpp.
{
    return c.has_artifact_with( AEP_PSYSHIELD ) ||
           ( c.worn_with_flag( "PSYSHIELD_PARTIAL" ) && one_in( partial_chance ) );
}
References AEP_PSYSHIELD, c, and one_in().
Referenced by mattack::fear_paralyze(), and Character::hardcoded_effects().
item_armor_enchantment_adjust()
static void item_armor_enchantment_adjust (const Character & guy, damage_unit & du, const item & armor) static
Definition at line 7814 of file character.cpp.
{
    switch( du.type ) {
        case DT_ACID:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_ACID );
            break;
        case DT_BASH:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_BASH );
            break;
        case DT_BIOLOGICAL:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_BIO );
            break;
        case DT_COLD:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_COLD );
            break;
        case DT_CUT:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_CUT );
            break;
        case DT_ELECTRIC:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_ELEC );
            break;
        case DT_HEAT:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_HEAT );
            break;
        case DT_STAB:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_STAB );
            break;
        case DT_BULLET:
            du.amount += armor.bonus_from_enchantments( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_BULLET );
            break;
        default:
            return;
    }
    du.amount = std::max( 0.0f, du.amount );
}
References damage_unit::amount, item::bonus_from_enchantments(), DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_STAB, enchant_vals::ITEM_ARMOR_ACID, enchant_vals::ITEM_ARMOR_BASH, enchant_vals::ITEM_ARMOR_BIO, enchant_vals::ITEM_ARMOR_BULLET, enchant_vals::ITEM_ARMOR_COLD, enchant_vals::ITEM_ARMOR_CUT, enchant_vals::ITEM_ARMOR_ELEC, enchant_vals::ITEM_ARMOR_HEAT, enchant_vals::ITEM_ARMOR_STAB, and damage_unit::type.
Referenced by Character::absorb_hit().
layer_item()
static void layer_item (char_encumbrance_data & vals, const item & it, std::array< layer_level, num_bp > & highest_layer_so_far, const Character & c) static
Definition at line 3598 of file character.cpp.
{
    const auto item_layer = it.get_layer();
    int encumber_val = it.get_encumber( c );
    // For the purposes of layering penalty, set a min of 2 and a max of 10 per item.
    int layering_encumbrance = std::min( 10, std::max( 2, encumber_val ) );
    /*
     * Setting layering_encumbrance to 0 at this point makes the item cease to exist
     * for the purposes of the layer penalty system. (normally an item has a minimum
     * layering_encumbrance of 2 )
     */
    if( it.has_flag( "SEMITANGIBLE" ) ) {
        encumber_val = 0;
        layering_encumbrance = 0;
    }
    if( it.has_flag( "COMPACT" ) ) {
        layering_encumbrance = 0;
    }
    body_part_set covered_parts = it.get_covered_body_parts();
    for( const body_part bp : all_body_parts ) {
        if( !covered_parts.test( bp ) ) {
            continue;
        }
        highest_layer_so_far[bp] =
            std::max( highest_layer_so_far[bp], item_layer );
        // Apply layering penalty to this layer, as well as any layer worn
        // within it that would normally be worn outside of it.
        for( layer_level penalty_layer = item_layer;
             penalty_layer <= highest_layer_so_far[bp]; ++penalty_layer ) {
            vals.elems[bp].layer( penalty_layer, layering_encumbrance );
        }
        vals.elems[bp].armor_encumbrance += encumber_val;
    }
}
References all_body_parts, c, char_encumbrance_data::elems, item::get_covered_body_parts(), item::get_encumber(), item::get_layer(), item::has_flag(), and body_part_set::test().
Referenced by Character::item_encumb().
ticks_between()
int ticks_between (const time_point & from, const time_point & to, const time_duration & tick_length) inline
Definition at line 4515 of file character.cpp.
{
    return ( to_turn<int>( to ) / to_turns<int>( tick_length ) ) - ( to_turn<int>
            ( from ) / to_turns<int>( tick_length ) );
}
Referenced by Character::update_body(), and Character::update_stomach().
try_remove_bear_trap()
static void try_remove_bear_trap (Character & c) static
Strength increases chance to escape bear trap
Definition at line 1259 of file character.cpp.
{
    map &here = get_map();
    /* Real bear traps can't be removed without the proper tools or immense strength; eventually this should
       allow normal players two options: removal of the limb or removal of the trap from the ground
       (at which point the player could later remove it from the leg with the right tools).
       As such we are currently making it a bit easier for players and NPC's to get out of bear traps.
    */
    /** @EFFECT_STR increases chance to escape bear trap */
    // If is riding, then despite the character having the effect, it is the mounted creature that escapes.
    if( c.is_player() && c.is_mounted() ) {
        auto mon = c.mounted_creature.get();
        if( mon->type->melee_dice * mon->type->melee_sides >= 18 ) {
            if( x_in_y( mon->type->melee_dice * mon->type->melee_sides, 200 ) ) {
                mon->remove_effect( effect_beartrap );
                c.remove_effect( effect_beartrap );
                here.spawn_item( c.pos(), itype_beartrap );
                add_msg( _( "The %s escapes the bear trap!" ), mon->get_name() );
            } else {
                c.add_msg_if_player( m_bad,
                                     _( "Your %s tries to free itself from the bear trap, but can't get loose!" ), mon->get_name() );
            }
        }
    } else {
        if( x_in_y( c.get_str(), 100 ) ) {
            c.remove_effect( effect_beartrap );
            c.add_msg_player_or_npc( m_good, _( "You free yourself from the bear trap!" ),
                                     _( "<npcname> frees themselves from the bear trap!" ) );
            here.spawn_item( c.pos(), itype_beartrap );
        } else {
            c.add_msg_if_player( m_bad,
                                 _( "You try to free yourself from the bear trap, but can't get loose!" ) );
        }
    }
}
References _, add_msg(), c, effect_beartrap, get_map(), itype_beartrap, m_bad, m_good, map::spawn_item(), and x_in_y().
Referenced by Character::move_effects(), and Character::wait_effects().
try_remove_crushed()
static void try_remove_crushed (Character & c) static
Strength increases chance to escape crushing rubble Dexterity increases chance to escape crushing rubble, slightly
Definition at line 1355 of file character.cpp.
{
    /** @EFFECT_STR increases chance to escape crushing rubble */
    /** @EFFECT_DEX increases chance to escape crushing rubble, slightly */
    if( x_in_y( c.get_str() + c.get_dex() / 4.0, 100 ) ) {
        c.remove_effect( effect_crushed );
        c.add_msg_player_or_npc( m_good, _( "You free yourself from the rubble!" ),
                                 _( "<npcname> frees themselves from the rubble!" ) );
    } else {
        c.add_msg_if_player( m_bad, _( "You try to free yourself from the rubble, but can't get loose!" ) );
    }
}
References _, c, effect_crushed, m_bad, m_good, and x_in_y().
Referenced by Character::move_effects().
try_remove_downed()
static void try_remove_downed (Character & c) static
Dexterity increases chance to stand up when knocked down Strength increases chance to stand up when knocked down, slightly
Definition at line 1244 of file character.cpp.
{
    /** @EFFECT_DEX increases chance to stand up when knocked down */
    /** @EFFECT_STR increases chance to stand up when knocked down, slightly */
    if( rng( 0, 40 ) > c.get_dex() + c.get_str() / 2 ) {
        c.add_msg_if_player( _( "You struggle to stand." ) );
    } else {
        c.add_msg_player_or_npc( m_good, _( "You stand up." ),
                                 _( "<npcname> stands up." ) );
        c.remove_effect( effect_downed );
    }
}
References _, c, effect_downed, m_good, and rng().
Referenced by Character::move_effects(), and Character::wait_effects().
try_remove_grab()
static bool try_remove_grab (Character & c) static
Strength increases chance to escape grab
Definition at line 1369 of file character.cpp.
{
    int zed_number = 0;
    map &here = get_map();
    if( c.is_mounted() ) {
        auto mon = c.mounted_creature.get();
        if( mon->has_effect( effect_grabbed ) ) {
            if( ( dice( mon->type->melee_dice + mon->type->melee_sides,
                        3 ) < c.get_effect_int( effect_grabbed ) ) ||
                !one_in( 4 ) ) {
                add_msg( m_bad, _( "Your %s tries to break free, but fails!" ), mon->get_name() );
                return false;
            } else {
                add_msg( m_good, _( "Your %s breaks free from the grab!" ), mon->get_name() );
                c.remove_effect( effect_grabbed );
                mon->remove_effect( effect_grabbed );
            }
        } else {
            if( one_in( 4 ) ) {
                add_msg( m_bad, _( "You are pulled from your %s!" ), mon->get_name() );
                c.remove_effect( effect_grabbed );
                c.forced_dismount();
            }
        }
    } else {
        for( auto&& dest : here.points_in_radius( c.pos(), 1, 0 ) ) { // *NOPAD*
            const monster *const mon = g->critter_at<monster>( dest );
            if( mon && mon->has_effect( effect_grabbing ) ) {
                zed_number += mon->get_grab_strength();
            }
        }
        if( zed_number == 0 ) {
            c.add_msg_player_or_npc( m_good, _( "You find yourself no longer grabbed." ),
                                     _( "<npcname> finds themselves no longer grabbed." ) );
            c.remove_effect( effect_grabbed );
            /** @EFFECT_STR increases chance to escape grab */
        } else if( rng( 0, c.get_str() ) < rng( c.get_effect_int( effect_grabbed, bp_torso ), 8 ) ) {
            c.add_msg_player_or_npc( m_bad, _( "You try break out of the grab, but fail!" ),
                                     _( "<npcname> tries to break out of the grab, but fails!" ) );
            return false;
        } else {
            c.add_msg_player_or_npc( m_good, _( "You break out of the grab!" ),
                                     _( "<npcname> breaks out of the grab!" ) );
            c.remove_effect( effect_grabbed );
            for( auto&& dest : here.points_in_radius( c.pos(), 1, 0 ) ) { // *NOPAD*
                monster *mon = g->critter_at<monster>( dest );
                if( mon && mon->has_effect( effect_grabbing ) ) {
                    mon->remove_effect( effect_grabbing );
                }
            }
        }
    }
    return true;
}
References _, add_msg(), bp_torso, c, dice(), effect_grabbed, effect_grabbing, g, monster::get_grab_strength(), get_map(), Creature::has_effect(), m_bad, m_good, one_in(), map::points_in_radius(), Creature::remove_effect(), and rng().
Referenced by Character::move_effects(), and Character::wait_effects().
try_remove_heavysnare()
static void try_remove_heavysnare (Character & c) static
Strength increases chance to escape heavy snare, slightly Dexterity increases chance to escape light snare
Definition at line 1324 of file character.cpp.
{
    map &here = get_map();
    if( c.is_mounted() ) {
        auto mon = c.mounted_creature.get();
        if( mon->type->melee_dice * mon->type->melee_sides >= 7 ) {
            if( x_in_y( mon->type->melee_dice * mon->type->melee_sides, 32 ) ) {
                mon->remove_effect( effect_heavysnare );
                c.remove_effect( effect_heavysnare );
                here.spawn_item( c.pos(), itype_rope_6 );
                here.spawn_item( c.pos(), itype_snare_trigger );
                add_msg( _( "The %s escapes the heavy snare!" ), mon->get_name() );
            }
        }
    } else {
        /** @EFFECT_STR increases chance to escape heavy snare, slightly */
        /** @EFFECT_DEX increases chance to escape light snare */
        if( x_in_y( c.get_str(), 32 ) || x_in_y( c.get_dex(), 16 ) ) {
            c.remove_effect( effect_heavysnare );
            c.add_msg_player_or_npc( m_good, _( "You free yourself from the heavy snare!" ),
                                     _( "<npcname> frees themselves from the heavy snare!" ) );
            here.spawn_item( c.pos(), itype_rope_6 );
            here.spawn_item( c.pos(), itype_snare_trigger );
        } else {
            c.add_msg_if_player( m_bad,
                                 _( "You try to free yourself from the heavy snare, but can't get loose!" ) );
        }
    }
}
References _, add_msg(), c, effect_heavysnare, get_map(), itype_rope_6, itype_snare_trigger, m_bad, m_good, map::spawn_item(), and x_in_y().
Referenced by Character::move_effects(), and Character::wait_effects().
try_remove_lightsnare()
static void try_remove_lightsnare (Character & c) static
Strength increases chance to escape light snare Dexterity increases chance to escape light snare
Definition at line 1295 of file character.cpp.
{
    map &here = get_map();
    if( c.is_mounted() ) {
        auto mon = c.mounted_creature.get();
        if( x_in_y( mon->type->melee_dice * mon->type->melee_sides, 12 ) ) {
            mon->remove_effect( effect_lightsnare );
            c.remove_effect( effect_lightsnare );
            here.spawn_item( c.pos(), itype_string_36 );
            here.spawn_item( c.pos(), itype_snare_trigger );
            add_msg( _( "The %s escapes the light snare!" ), mon->get_name() );
        }
    } else {
        /** @EFFECT_STR increases chance to escape light snare */
        /** @EFFECT_DEX increases chance to escape light snare */
        if( x_in_y( c.get_str(), 12 ) || x_in_y( c.get_dex(), 8 ) ) {
            c.remove_effect( effect_lightsnare );
            c.add_msg_player_or_npc( m_good, _( "You free yourself from the light snare!" ),
                                     _( "<npcname> frees themselves from the light snare!" ) );
            here.spawn_item( c.pos(), itype_string_36 );
            here.spawn_item( c.pos(), itype_snare_trigger );
        } else {
            c.add_msg_if_player( m_bad,
                                 _( "You try to free yourself from the light snare, but can't get loose!" ) );
        }
    }
}
References _, add_msg(), c, effect_lightsnare, get_map(), itype_snare_trigger, itype_string_36, m_bad, m_good, map::spawn_item(), and x_in_y().
Referenced by Character::move_effects(), and Character::wait_effects().
try_remove_webs()
static void try_remove_webs (Character & c) static
Strength increases chance to escape webs
Definition at line 1425 of file character.cpp.
{
    if( c.is_mounted() ) {
        auto mon = c.mounted_creature.get();
        if( x_in_y( mon->type->melee_dice * mon->type->melee_sides,
                    6 * c.get_effect_int( effect_webbed ) ) ) {
            add_msg( _( "The %s breaks free of the webs!" ), mon->get_name() );
            mon->remove_effect( effect_webbed );
            c.remove_effect( effect_webbed );
        }
        /** @EFFECT_STR increases chance to escape webs */
    } else if( x_in_y( c.get_str(), 6 * c.get_effect_int( effect_webbed ) ) ) {
        c.add_msg_player_or_npc( m_good, _( "You free yourself from the webs!" ),
                                 _( "<npcname> frees themselves from the webs!" ) );
        c.remove_effect( effect_webbed );
    } else {
        c.add_msg_if_player( _( "You try to free yourself from the webs, but can't get loose!" ) );
    }
}
References _, add_msg(), c, effect_webbed, m_good, and x_in_y().
Referenced by Character::move_effects(), and Character::wait_effects().
wind_resistance_from_item_list()
static int wind_resistance_from_item_list (const std::vector< const item * > & items) static
Definition at line 3724 of file character.cpp.
{
    int total_exposed = 100;
    for( const item *it : items ) {
        const item &i = *it;
        int penalty = 100 - i.wind_resist();
        int coverage = std::max( 0, i.get_coverage() - penalty );
        total_exposed = total_exposed * ( 100 - coverage ) / 100;
    }
    return 100 - total_exposed;
}
References item::get_coverage(), and item::wind_resist().
Referenced by warmth::wind_resistance_from_clothing().
Variable Documentation
ACT_MOVE_ITEMS
const activity_id ACT_MOVE_ITEMS("ACT_MOVE_ITEMS") ("ACT_MOVE_ITEMS") static
Referenced by Character::cancel_activity(), and Character::stop_hauling().
ACT_TRAVELLING
const activity_id ACT_TRAVELLING("ACT_TRAVELLING") ("ACT_TRAVELLING") static
Referenced by Character::has_distant_destination().
ACT_TREE_COMMUNION
const activity_id ACT_TREE_COMMUNION("ACT_TREE_COMMUNION") ("ACT_TREE_COMMUNION") static
Referenced by Character::calc_needs_rates().
ACT_TRY_SLEEP
const activity_id ACT_TRY_SLEEP("ACT_TRY_SLEEP") ("ACT_TRY_SLEEP") static
Referenced by Character::cancel_activity(), Character::fall_asleep(), Character::in_sleep_state(), and Character::update_needs().
ACT_WAIT_STAMINA
const activity_id ACT_WAIT_STAMINA("ACT_WAIT_STAMINA") ("ACT_WAIT_STAMINA") static
Referenced by Character::cancel_activity().
afs_bio_linguistic_coprocessor
const bionic_id afs_bio_linguistic_coprocessor("afs_bio_linguistic_coprocessor") ("afs_bio_linguistic_coprocessor") static
Referenced by Character::read_speed().
bio_ads
const bionic_id bio_ads("bio_ads") ("bio_ads") static
Referenced by Character::absorb_hit().
bio_blindfold
const bionic_id bio_blindfold("bio_blindfold") ("bio_blindfold") static
Referenced by Character::is_blind().
bio_climate
const bionic_id bio_climate("bio_climate") ("bio_climate") static
Referenced by Character::in_climate_control().
bio_cloak
const bionic_id bio_cloak("bio_cloak") ("bio_cloak") static
Referenced by Character::basic_symbol_color().
bio_earplugs
const bionic_id bio_earplugs("bio_earplugs") ("bio_earplugs") static
Referenced by Character::hearing_ability(), and Character::is_deaf().
bio_ears
const bionic_id bio_ears("bio_ears") ("bio_ears") static
Referenced by Character::hearing_ability(), Character::is_deaf(), and Character::is_immune_effect().
bio_eye_optic
const bionic_id bio_eye_optic("bio_eye_optic") ("bio_eye_optic") static
Referenced by Character::overmap_sight_range(), and Character::sight_impaired().
bio_faraday
const bionic_id bio_faraday("bio_faraday") ("bio_faraday") static
Referenced by Character::is_immune_damage().
bio_flashlight
const bionic_id bio_flashlight("bio_flashlight") ("bio_flashlight") static
Referenced by Character::active_light().
bio_gills
const bionic_id bio_gills("bio_gills") ("bio_gills") static
Referenced by Character::update_stamina().
bio_ground_sonar
const bionic_id bio_ground_sonar("bio_ground_sonar") ("bio_ground_sonar") static
Referenced by Character::sees_with_specials().
bio_heatsink
const bionic_id bio_heatsink("bio_heatsink") ("bio_heatsink") static
Referenced by Character::is_immune_field(), and Character::update_bodytemp().
bio_infrared
const bionic_id bio_infrared("bio_infrared") ("bio_infrared") static
Referenced by Character::recalc_sight_limits().
bio_jointservo
const bionic_id bio_jointservo("bio_jointservo") ("bio_jointservo") static
Referenced by Character::run_cost().
bio_laser
const bionic_id bio_laser("bio_laser") ("bio_laser") static
Referenced by Character::has_fire(), and Character::use_fire().
bio_leukocyte
const bionic_id bio_leukocyte("bio_leukocyte") ("bio_leukocyte") static
Referenced by Character::update_health().
bio_lighter
const bionic_id bio_lighter("bio_lighter") ("bio_lighter") static
Referenced by Character::has_fire(), and Character::use_fire().
bio_membrane
const bionic_id bio_membrane("bio_membrane") ("bio_membrane") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
bio_memory
const bionic_id bio_memory("bio_memory") ("bio_memory") static
Referenced by Character::adjust_for_focus(), and Character::do_skill_rust().
bio_night_vision
const bionic_id bio_night_vision("bio_night_vision") ("bio_night_vision") static
Referenced by Character::has_nv().
bio_railgun
const bionic_id bio_railgun("bio_railgun") ("bio_railgun") static
Referenced by Character::throw_range().
bio_recycler
const bionic_id bio_recycler("bio_recycler") ("bio_recycler") static
Referenced by Character::calc_needs_rates().
bio_shock_absorber
const bionic_id bio_shock_absorber("bio_shock_absorber") ("bio_shock_absorber") static
Referenced by Character::mut_cbm_encumb().
bio_storage
const bionic_id bio_storage("bio_storage") ("bio_storage") static
Referenced by Character::volume_capacity_reduced_by().
bio_synaptic_regen
const bionic_id bio_synaptic_regen("bio_synaptic_regen") ("bio_synaptic_regen") static
Referenced by Character::update_needs().
bio_tattoo_led
const bionic_id bio_tattoo_led("bio_tattoo_led") ("bio_tattoo_led") static
Referenced by Character::active_light().
bio_tools
const bionic_id bio_tools("bio_tools") ("bio_tools") static
Referenced by Character::has_fire(), and Character::use_fire().
bio_ups
const bionic_id bio_ups("bio_ups") ("bio_ups") static
Referenced by Character::use_charges().
bio_watch
const bionic_id bio_watch("bio_watch") ("bio_watch") static
Referenced by Character::has_alarm_clock(), and Character::has_watch().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by Character::check_needs_extremes(), Character::get_perceived_pain(), Character::on_effect_int_change(), and Character::on_hurt().
effect_ai_waiting
const efftype_id effect_ai_waiting("ai_waiting") ("ai_waiting") static
Referenced by Character::dismount(), and Character::forced_dismount().
effect_alarm_clock
const efftype_id effect_alarm_clock("alarm_clock") ("alarm_clock") static
Referenced by Character::wake_up().
effect_bandaged
const efftype_id effect_bandaged("bandaged") ("bandaged") static
Referenced by Character::apply_damage(), Character::body_window(), Character::healing_rate_medicine(), Character::reduce_healing_effect(), and Character::regen().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by Character::die(), Character::move_effects(), try_remove_bear_trap(), and Character::wait_effects().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by Character::body_window(), Character::deal_damage(), and Character::limb_color().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::body_window(), Character::is_immune_effect(), and Character::limb_color().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by Character::deal_damage(), and Character::is_blind().
effect_blisters
const efftype_id effect_blisters("blisters") ("blisters") static
Referenced by Character::update_bodytemp().
effect_bloated
const efftype_id effect_bloated("bloated") ("bloated") static
Referenced by Character::vomit().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by Character::basic_symbol_color(), Character::recalc_sight_limits(), and Character::sight_impaired().
effect_cold
const efftype_id effect_cold("cold") ("cold") static
Referenced by Character::update_bodytemp().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
effect_corroding
const efftype_id effect_corroding("corroding") ("corroding") static
Referenced by Character::is_immune_effect().
effect_cough_suppress
const efftype_id effect_cough_suppress("cough_suppress") ("cough_suppress") static
Referenced by Character::cough().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by Character::move_effects(), and try_remove_crushed().
effect_darkness
const efftype_id effect_darkness("darkness") ("darkness") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by Character::hearing_ability(), Character::is_deaf(), and Character::is_immune_effect().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by Character::apply_damage(), Character::body_window(), Character::healing_rate_medicine(), Character::reduce_healing_effect(), and Character::regen().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by Character::is_immune_effect(), Character::is_on_ground(), Character::move_effects(), Character::symbol_color(), try_remove_downed(), and Character::wait_effects().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by Character::check_needs_extremes(), and Character::vomit().
effect_earphones
const efftype_id effect_earphones("earphones") ("earphones") static
Referenced by Character::hearing_ability().
effect_foodpoison
const efftype_id effect_foodpoison("foodpoison") ("foodpoison") static
Referenced by Character::vomit().
effect_frostbite
const efftype_id effect_frostbite("frostbite") ("frostbite") static
Referenced by Character::update_bodytemp().
effect_frostbite_recovery
const efftype_id effect_frostbite_recovery("frostbite_recovery") ("frostbite_recovery") static
Referenced by Character::update_bodytemp().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by Character::vomit().
effect_glowing
const efftype_id effect_glowing("glowing") ("glowing") static
Referenced by Character::active_light().
effect_glowy_led
const efftype_id effect_glowy_led("glowy_led") ("glowy_led") static
Referenced by Character::active_light().
effect_got_checked
const efftype_id effect_got_checked("got_checked") ("got_checked") static
Referenced by Character::get_pain_description().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by Character::deal_damage(), Character::item_handling_cost(), Character::move_effects(), Character::symbol_color(), try_remove_grab(), and Character::wait_effects().
effect_grabbing
const efftype_id effect_grabbing("grabbing") ("grabbing") static
Referenced by Character::deal_damage(), and try_remove_grab().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by Character::mount_creature().
effect_heating_bionic
const efftype_id effect_heating_bionic("heating_bionic") ("heating_bionic") static
Referenced by warmth::from_effects(), and Character::warmth().
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
Referenced by Character::die(), Character::move_effects(), try_remove_heavysnare(), and Character::wait_effects().
effect_hot
const efftype_id effect_hot("hot") ("hot") static
Referenced by Character::update_bodytemp().
effect_hot_speed
const efftype_id effect_hot_speed("hot_speed") ("hot_speed") static
Referenced by Character::update_bodytemp().
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
Referenced by Character::move_effects(), and Character::recalc_sight_limits().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by Character::body_window(), Character::deal_damage(), and Character::limb_color().
effect_jetinjector
const efftype_id effect_jetinjector("jetinjector") ("jetinjector") static
Referenced by Character::check_needs_extremes().
effect_lack_sleep
const efftype_id effect_lack_sleep("lack_sleep") ("lack_sleep") static
Referenced by Character::check_needs_extremes().
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
Referenced by Character::die(), Character::move_effects(), try_remove_lightsnare(), and Character::wait_effects().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by Character::update_needs(), and Character::wake_up().
effect_masked_scent
const efftype_id effect_masked_scent("masked_scent") ("masked_scent") static
Referenced by Character::restore_scent().
effect_melatonin_supplements
const efftype_id effect_melatonin_supplements("melatonin") ("melatonin") static
Referenced by Character::update_needs().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by Character::apply_damage(), Character::body_window(), and draw_limb_health().
effect_meth
const efftype_id effect_meth("meth") ("meth") static
Referenced by Character::check_needs_extremes().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::mod_pain(), Character::on_hurt(), Character::react_to_felt_pain(), Character::recalc_sight_limits(), and Character::update_needs().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by Character::is_immune_effect(), and Character::vomit().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by Character::absorb_hit(), Character::basic_symbol_color(), and Character::is_immune_effect().
effect_pkill1
const efftype_id effect_pkill1("pkill1") ("pkill1") static
Referenced by Character::vomit().
effect_pkill2
const efftype_id effect_pkill2("pkill2") ("pkill2") static
Referenced by Character::vomit().
effect_pkill3
const efftype_id effect_pkill3("pkill3") ("pkill3") static
Referenced by Character::vomit().
effect_recently_coughed
const efftype_id effect_recently_coughed("recently_coughed") ("recently_coughed") static
Referenced by Character::cough(), and Character::update_needs().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by Character::dismount(), Character::forced_dismount(), and Character::mount_creature().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by Character::dismount(), Character::forced_dismount(), Character::is_mounted(), and Character::mount_creature().
effect_saddled
const efftype_id effect_saddled("monster_saddled") ("monster_saddled") static
Referenced by Character::check_mount_is_spooked().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Character::calc_needs_rates(), Character::fall_asleep(), Character::is_hibernating(), Character::on_hurt(), Character::react_to_felt_pain(), Character::rest_quality(), Character::update_needs(), and Character::wake_up().
effect_slept_through_alarm
const efftype_id effect_slept_through_alarm("slept_through_alarm") ("slept_through_alarm") static
Referenced by Character::wake_up().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by Character::basic_symbol_color().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by Character::mount_creature().
effect_took_prozac
const efftype_id effect_took_prozac("took_prozac") ("took_prozac") static
Referenced by Character::apply_persistent_morale().
effect_took_xanax
const efftype_id effect_took_xanax("took_xanax") ("took_xanax") static
Referenced by Character::apply_persistent_morale().
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
Referenced by Character::move_effects(), try_remove_webs(), and Character::wait_effects().
fault_bionic_nonsterile
const fault_id fault_bionic_nonsterile("fault_bionic_nonsterile") ("fault_bionic_nonsterile") static
Referenced by Character::place_corpse().
flag_BIONIC_ARMOR_INTERFACE
const flag_str_id flag_BIONIC_ARMOR_INTERFACE("BIONIC_ARMOR_INTERFACE") ("BIONIC_ARMOR_INTERFACE") static
Referenced by Character::has_charges(), and Character::use_charges().
flag_CLIMATE_CONTROL
const flag_str_id flag_CLIMATE_CONTROL("CLIMATE_CONTROL") ("CLIMATE_CONTROL") static
Referenced by Character::in_climate_control().
flag_COLLAR
const flag_str_id flag_COLLAR("COLLAR") ("COLLAR") static
Referenced by Character::update_bodytemp().
flag_HOOD
const flag_str_id flag_HOOD("HOOD") ("HOOD") static
Referenced by Character::update_bodytemp().
flag_POCKETS
const flag_str_id flag_POCKETS("POCKETS") ("POCKETS") static
Referenced by Character::update_bodytemp().
HUMAN
const species_id HUMAN("HUMAN") ("HUMAN") static
Referenced by Character::in_species().
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
Referenced by Character::use_charges().
itype_apparatus
const itype_id itype_apparatus("apparatus") ("apparatus") static
Referenced by Character::has_charges().
itype_beartrap
const itype_id itype_beartrap("beartrap") ("beartrap") static
Referenced by Character::die(), and try_remove_bear_trap().
itype_bio_armor
const itype_id itype_bio_armor("bio_armor") ("bio_armor") static
Referenced by Character::consume_charges(), Character::has_charges(), Character::has_enough_charges(), and Character::use_charges().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by Character::item_handling_cost().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by Character::has_charges(), and Character::use_charges().
itype_power_storage
const itype_id itype_power_storage("bio_power_storage") ("bio_power_storage") static
Referenced by Character::place_corpse().
itype_power_storage_mkII
const itype_id itype_power_storage_mkII("bio_power_storage_mkII") ("bio_power_storage_mkII") static
Referenced by Character::place_corpse().
itype_rm13_armor_on
const itype_id itype_rm13_armor_on("rm13_armor_on") ("rm13_armor_on") static
Referenced by Character::is_immune_effect(), Character::is_immune_field(), Character::recalc_sight_limits(), and Character::update_bodytemp().
itype_rope_6
const itype_id itype_rope_6("rope_6") ("rope_6") static
Referenced by Character::die(), and try_remove_heavysnare().
itype_snare_trigger
const itype_id itype_snare_trigger("snare_trigger") ("snare_trigger") static
Referenced by Character::die(), try_remove_heavysnare(), and try_remove_lightsnare().
itype_string_36
const itype_id itype_string_36("string_36") ("string_36") static
Referenced by Character::die(), and try_remove_lightsnare().
itype_toolset
const itype_id itype_toolset("toolset") ("toolset") static
Referenced by Character::use_charges().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by Character::ammo_count_for(), Character::consume_charges(), Character::has_charges(), Character::has_enough_charges(), and Character::use_charges().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by Character::use_charges().
mon_player_blob
const mtype_id mon_player_blob("mon_player_blob") ("mon_player_blob") static
Referenced by Character::deal_damage().
mon_shadow_snake
const mtype_id mon_shadow_snake("mon_shadow_snake") ("mon_shadow_snake") static
Referenced by Character::deal_damage().
mutation_value_map
const std::map<std::string, std::function <float(std::vector<const mutation_branch *>)> > mutation_value_map static
Definition at line 6477 of file character.cpp.
Referenced by Character::mutation_value().
ROBOT
const species_id ROBOT("ROBOT") ("ROBOT") static
Referenced by Character::sees_with_specials().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by Character::avoid_trap(), and Character::get_dodge_base().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by Character::swim_speed().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by Character::throw_range().
trait_ACIDBLOOD
const trait_id trait_ACIDBLOOD("ACIDBLOOD") ("ACIDBLOOD") static
Referenced by Character::bloodType(), and Character::deal_damage().
trait_ACIDPROOF
const trait_id trait_ACIDPROOF("ACIDPROOF") ("ACIDPROOF") static
Referenced by Character::is_immune_damage().
trait_ADRENALINE
const trait_id trait_ADRENALINE("ADRENALINE") ("ADRENALINE") static
Referenced by Character::on_hurt().
trait_ANTENNAE
const trait_id trait_ANTENNAE("ANTENNAE") ("ANTENNAE") static
Referenced by Character::can_wear(), and Character::sees().
trait_ANTLERS
const trait_id trait_ANTLERS("ANTLERS") ("ANTLERS") static
Referenced by Character::can_wear().
trait_BADBACK
const trait_id trait_BADBACK("BADBACK") ("BADBACK") static
Referenced by Character::burn_move_stamina().
trait_BARK
const trait_id trait_BARK("BARK") ("BARK") static
Referenced by Character::update_bodytemp().
trait_BIRD_EYE
const trait_id trait_BIRD_EYE("BIRD_EYE") ("BIRD_EYE") static
Referenced by Character::recalc_sight_limits().
trait_CEPH_EYES
const trait_id trait_CEPH_EYES("CEPH_EYES") ("CEPH_EYES") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
trait_DEAF
const trait_id trait_DEAF("DEAF") ("DEAF") static
Referenced by Character::is_deaf().
trait_DEBUG_CLOAK
const trait_id trait_DEBUG_CLOAK("DEBUG_CLOAK") ("DEBUG_CLOAK") static
Referenced by Character::basic_symbol_color(), and Character::is_invisible().
trait_DEBUG_LS
const trait_id trait_DEBUG_LS("DEBUG_LS") ("DEBUG_LS") static
Referenced by Character::update_needs(), and Character::update_stomach().
trait_DEBUG_NIGHTVISION
const trait_id trait_DEBUG_NIGHTVISION("DEBUG_NIGHTVISION") ("DEBUG_NIGHTVISION") static
Referenced by Character::recalc_sight_limits().
trait_DEBUG_NODMG
const trait_id trait_DEBUG_NODMG("DEBUG_NODMG") ("DEBUG_NODMG") static
Referenced by Character::apply_damage(), Character::deal_damage(), Character::hurtall(), and Character::is_immune_field().
trait_DEBUG_NOTEMP
const trait_id trait_DEBUG_NOTEMP("DEBUG_NOTEMP") ("DEBUG_NOTEMP") static
Referenced by Character::update_bodytemp().
trait_DEBUG_STORAGE
const trait_id trait_DEBUG_STORAGE("DEBUG_STORAGE") ("DEBUG_STORAGE") static
Referenced by Character::can_pick_weight(), Character::volume_capacity_reduced_by(), and Character::weight_capacity().
trait_DISORGANIZED
const trait_id trait_DISORGANIZED("DISORGANIZED") ("DISORGANIZED") static
Referenced by Character::volume_capacity_reduced_by().
trait_DOWN
const trait_id trait_DOWN("DOWN") ("DOWN") static
Referenced by Character::floor_warmth().
trait_ELECTRORECEPTORS
const trait_id trait_ELECTRORECEPTORS("ELECTRORECEPTORS") ("ELECTRORECEPTORS") static
Referenced by Character::sees_with_specials().
trait_FASTLEARNER
const trait_id trait_FASTLEARNER("FASTLEARNER") ("FASTLEARNER") static
Referenced by Character::adjust_for_focus().
trait_GILLS
const trait_id trait_GILLS("GILLS") ("GILLS") static
Referenced by Character::shout().
trait_GILLS_CEPH
const trait_id trait_GILLS_CEPH("GILLS_CEPH") ("GILLS_CEPH") static
Referenced by Character::shout().
trait_HEAVYSLEEPER
const trait_id trait_HEAVYSLEEPER("HEAVYSLEEPER") ("HEAVYSLEEPER") static
Referenced by Character::react_to_felt_pain().
trait_HEAVYSLEEPER2
const trait_id trait_HEAVYSLEEPER2("HEAVYSLEEPER2") ("HEAVYSLEEPER2") static
Referenced by Character::react_to_felt_pain().
trait_HIBERNATE
const trait_id trait_HIBERNATE("HIBERNATE") ("HIBERNATE") static
Referenced by Character::fall_asleep(), and Character::is_hibernating().
trait_HOARDER
const trait_id trait_HOARDER("HOARDER") ("HOARDER") static
Referenced by Character::apply_persistent_morale().
trait_HOLLOW_BONES
const trait_id trait_HOLLOW_BONES("HOLLOW_BONES") ("HOLLOW_BONES") static
Referenced by Character::absorb_hit().
trait_HORNS_POINTED
const trait_id trait_HORNS_POINTED("HORNS_POINTED") ("HORNS_POINTED") static
Referenced by Character::can_wear().
trait_INFRARED
const trait_id trait_INFRARED("INFRARED") ("INFRARED") static
Referenced by Character::recalc_sight_limits().
trait_LEG_TENT_BRACE
const trait_id trait_LEG_TENT_BRACE("LEG_TENT_BRACE") ("LEG_TENT_BRACE") static
Referenced by Character::is_immune_effect().
trait_LIGHT_BONES
const trait_id trait_LIGHT_BONES("LIGHT_BONES") ("LIGHT_BONES") static
Referenced by Character::absorb_hit().
trait_LIZ_IR
const trait_id trait_LIZ_IR("LIZ_IR") ("LIZ_IR") static
Referenced by Character::recalc_sight_limits().
trait_M_DEPENDENT
const trait_id trait_M_DEPENDENT("M_DEPENDENT") ("M_DEPENDENT") static
Referenced by Character::update_stomach().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by Character::run_cost().
trait_M_SKIN2
const trait_id trait_M_SKIN2("M_SKIN2") ("M_SKIN2") static
Referenced by Character::is_immune_damage(), and Character::update_bodytemp().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by Character::in_climate_control(), Character::is_deaf(), Character::is_immune_damage(), and Character::update_bodytemp().
trait_MEMBRANE
const trait_id trait_MEMBRANE("MEMBRANE") ("MEMBRANE") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
trait_MOREPAIN
const trait_id trait_MOREPAIN("MORE_PAIN") ("MORE_PAIN") static
Referenced by Character::mod_pain().
trait_MOREPAIN2
const trait_id trait_MOREPAIN2("MORE_PAIN2") ("MORE_PAIN2") static
Referenced by Character::mod_pain().
trait_MOREPAIN3
const trait_id trait_MOREPAIN3("MORE_PAIN3") ("MORE_PAIN3") static
Referenced by Character::mod_pain().
trait_MYOPIC
const trait_id trait_MYOPIC("MYOPIC") ("MYOPIC") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
trait_NO_THIRST
const trait_id trait_NO_THIRST("NO_THIRST") ("NO_THIRST") static
Referenced by Character::update_stomach().
trait_NOMAD
const trait_id trait_NOMAD("NOMAD") ("NOMAD") static
Referenced by Character::apply_persistent_morale().
trait_NOMAD2
const trait_id trait_NOMAD2("NOMAD2") ("NOMAD2") static
Referenced by Character::apply_persistent_morale().
trait_NOMAD3
const trait_id trait_NOMAD3("NOMAD3") ("NOMAD3") static
Referenced by Character::apply_persistent_morale().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by Character::check_needs_extremes(), Character::mod_pain(), and Character::update_needs().
trait_PACKMULE
const trait_id trait_PACKMULE("PACKMULE") ("PACKMULE") static
Referenced by Character::volume_capacity_reduced_by().
trait_PADDED_FEET
const trait_id trait_PADDED_FEET("PADDED_FEET") ("PADDED_FEET") static
Referenced by Character::run_cost().
trait_PAINRESIST
const trait_id trait_PAINRESIST("PAINRESIST") ("PAINRESIST") static
Referenced by Character::mod_pain().
trait_PAINRESIST_TROGLO
const trait_id trait_PAINRESIST_TROGLO("PAINRESIST_TROGLO") ("PAINRESIST_TROGLO") static
Referenced by Character::mod_pain().
trait_PAWS
const trait_id trait_PAWS("PAWS") ("PAWS") static
Referenced by Character::swim_speed().
trait_PAWS_LARGE
const trait_id trait_PAWS_LARGE("PAWS_LARGE") ("PAWS_LARGE") static
Referenced by Character::swim_speed().
trait_PER_SLIME
const trait_id trait_PER_SLIME("PER_SLIME") ("PER_SLIME") static
Referenced by Character::hearing_ability(), Character::recalc_sight_limits(), and Character::sight_impaired().
trait_PER_SLIME_OK
const trait_id trait_PER_SLIME_OK("PER_SLIME_OK") ("PER_SLIME_OK") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
trait_PROF_FOODP
const trait_id trait_PROF_FOODP("PROF_FOODP") ("PROF_FOODP") static
Referenced by Character::apply_persistent_morale(), Character::get_shout_volume(), and Character::shout().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by Character::update_bodytemp().
trait_RADIOGENIC
const trait_id trait_RADIOGENIC("RADIOGENIC") ("RADIOGENIC") static
Referenced by Character::update_body().
trait_ROOTS2
const trait_id trait_ROOTS2("ROOTS2") ("ROOTS2") static
Referenced by Character::calc_needs_rates(), Character::rooted(), and Character::rooted_message().
trait_ROOTS3
const trait_id trait_ROOTS3("ROOTS3") ("ROOTS3") static
Referenced by Character::calc_needs_rates(), Character::rooted(), Character::rooted_message(), and Character::run_cost().
trait_SEESLEEP
const trait_id trait_SEESLEEP("SEESLEEP") ("SEESLEEP") static
Referenced by Character::get_env_resist(), Character::recalc_sight_limits(), and Character::sight_impaired().
trait_SELFAWARE
const trait_id trait_SELFAWARE("SELFAWARE") ("SELFAWARE") static
Referenced by Character::get_hunger_description(), Character::get_pain_description(), and Character::print_health().
trait_SHELL
const trait_id trait_SHELL("SHELL") ("SHELL") static
Referenced by Character::volume_capacity_reduced_by().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by Character::get_working_arm_count(), Character::recalc_sight_limits(), Character::update_bodytemp(), and Character::volume_capacity_reduced_by().
trait_SHOUT2
const trait_id trait_SHOUT2("SHOUT2") ("SHOUT2") static
Referenced by Character::get_shout_volume(), and Character::shout().
trait_SHOUT3
const trait_id trait_SHOUT3("SHOUT3") ("SHOUT3") static
Referenced by Character::get_shout_volume(), and Character::shout().
trait_SLIMESPAWNER
const trait_id trait_SLIMESPAWNER("SLIMESPAWNER") ("SLIMESPAWNER") static
Referenced by Character::deal_damage().
trait_SLIMY
const trait_id trait_SLIMY("SLIMY") ("SLIMY") static
Referenced by Character::is_immune_effect().
trait_SLOWLEARNER
const trait_id trait_SLOWLEARNER("SLOWLEARNER") ("SLOWLEARNER") static
Referenced by Character::adjust_for_focus().
trait_SQUEAMISH
const trait_id trait_SQUEAMISH("SQUEAMISH") ("SQUEAMISH") static
Referenced by Character::can_wear().
trait_STRONGSTOMACH
const trait_id trait_STRONGSTOMACH("STRONGSTOMACH") ("STRONGSTOMACH") static
Referenced by Character::is_immune_effect().
trait_THRESH_CEPHALOPOD
const trait_id trait_THRESH_CEPHALOPOD("THRESH_CEPHALOPOD") ("THRESH_CEPHALOPOD") static
Referenced by Character::bloodType().
trait_THRESH_INSECT
const trait_id trait_THRESH_INSECT("THRESH_INSECT") ("THRESH_INSECT") static
Referenced by Character::bloodType().
trait_THRESH_PLANT
const trait_id trait_THRESH_PLANT("THRESH_PLANT") ("THRESH_PLANT") static
Referenced by Character::bloodType().
trait_THRESH_SPIDER
const trait_id trait_THRESH_SPIDER("THRESH_SPIDER") ("THRESH_SPIDER") static
Referenced by Character::bloodType().
trait_TRANSPIRATION
const trait_id trait_TRANSPIRATION("TRANSPIRATION") ("TRANSPIRATION") static
Referenced by Character::calc_needs_rates().
trait_URSINE_EYE
const trait_id trait_URSINE_EYE("URSINE_EYE") ("URSINE_EYE") static
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
trait_VISCOUS
const trait_id trait_VISCOUS("VISCOUS") ("VISCOUS") static
Referenced by Character::is_immune_effect().
trait_WEBBED
const trait_id trait_WEBBED("WEBBED") ("WEBBED") static
Referenced by Character::swim_speed().
trait_WOOLALLERGY
const trait_id trait_WOOLALLERGY("WOOLALLERGY") ("WOOLALLERGY") static
Referenced by Character::can_wear().