Cataclysm BN: src/character_display.cpp File Reference
character_display.cpp File Reference
#include "character_display.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdlib>
#include <memory>
#include <unordered_map>
#include "addiction.h"
#include "avatar.h"
#include "bionics.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_effects.h"
#include "character_encumbrance.h"
#include "debug.h"
#include "effect.h"
#include "game.h"
#include "input.h"
#include "mutation.h"
#include "options.h"
#include "output.h"
#include "pldata.h"
#include "profession.h"
#include "ranged.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "weather.h"
Classes
struct HeaderSkill
Namespaces
namespace anonymous_namespace{character_display.cpp}
Enumerations
enum class anonymous_namespace{character_display.cpp}::player_display_tab {
anonymous_namespace{character_display.cpp}::stats , anonymous_namespace{character_display.cpp}::encumbrance , anonymous_namespace{character_display.cpp}::skills , anonymous_namespace{character_display.cpp}::traits ,
anonymous_namespace{character_display.cpp}::bionics , anonymous_namespace{character_display.cpp}::effects , anonymous_namespace{character_display.cpp}::num_tabs
}
Functions
static const std::string header_spaces (26, ' ')
static int temperature_print_rescaling (int temp)
static body_part other_part (body_part bp)
static bool should_combine_bps (const Character &ch, body_part l, body_part r, const item *selected_clothing)
static std::vector< std::pair< body_part, bool > > list_and_combine_bps (const Character &ch, const item *selected_clothing)
static std::string swim_cost_text (int moves)
static std::string run_cost_text (int moves)
static std::string reload_cost_text (int moves)
static std::string melee_cost_text (int moves)
static std::string melee_stamina_cost_text (int cost)
static std::string mouth_stamina_cost_text (int cost)
static std::string ranged_cost_text (double disp)
static std::string dodge_skill_text (double mod)
static int get_encumbrance (const Character &p, body_part bp, bool combine)
static std::string get_encumbrance_description (const Character &p, body_part bp, bool combine)
static bool is_cqb_skill (const skill_id &id)
static player_display_tab next_tab (const player_display_tab tab)
static player_display_tab prev_tab (const player_display_tab tab)
static void draw_stats_tab (const catacurses::window &w_stats, const Character &you, const unsigned int line, const player_display_tab curtab)
static void draw_stats_info (const catacurses::window &w_info, const Character &you, const unsigned int line)
static void draw_encumbrance_tab (const catacurses::window &w_encumb, const Character &you, const unsigned int line, const player_display_tab curtab)
static void draw_encumbrance_info (const catacurses::window &w_info, const Character &you, const unsigned int line)
static void draw_traits_tab (const catacurses::window &w_traits, const unsigned int line, const player_display_tab curtab, const std::vector< trait_id > &traitslist, const size_t trait_win_size_y)
static void draw_traits_info (const catacurses::window &w_info, const unsigned int line, const std::vector< trait_id > &traitslist)
static void draw_bionics_tab (const catacurses::window &w_bionics, const Character &you, const unsigned int line, const player_display_tab curtab, const std::vector< bionic > &bionicslist, const size_t bionics_win_size_y)
static void draw_bionics_info (const catacurses::window &w_info, const unsigned int line, const std::vector< bionic > &bionicslist)
static void draw_effects_tab (const catacurses::window &w_effects, const unsigned int line, const player_display_tab curtab, const std::vector< std::pair< std::string, std::string > > &effect_name_and_text, const size_t effect_win_size_y)
static void draw_effects_info (const catacurses::window &w_info, const unsigned int line, const std::vector< std::pair< std::string, std::string > > &effect_name_and_text)
static void draw_skills_tab (const catacurses::window &w_skills, Character &you, unsigned int line, const player_display_tab curtab, std::vector< HeaderSkill > &skillslist, const size_t skill_win_size_y)
static void draw_skills_info (const catacurses::window &w_info, unsigned int line, const std::vector< HeaderSkill > &skillslist)
static void draw_speed_tab (const catacurses::window &w_speed, const Character &you, const std::map< std::string, int > &speed_effects)
static void draw_info_window (const catacurses::window &w_info, const Character &you, const unsigned int line, const player_display_tab curtab, const std::vector< trait_id > &traitslist, const std::vector< bionic > &bionicslist, const std::vector< std::pair< std::string, std::string > > &effect_name_and_text, const std::vector< HeaderSkill > &skillslist)
static void draw_tip (const catacurses::window &w_tip, const Character &you, const std::string &race, const input_context &ctxt)
static bool handle_player_display_action (Character &you, unsigned int &line, player_display_tab &curtab, input_context &ctxt, const ui_adaptor &ui_tip, const ui_adaptor &ui_info, const ui_adaptor &ui_stats, const ui_adaptor &ui_encumb, const ui_adaptor &ui_traits, const ui_adaptor &ui_bionics, const ui_adaptor &ui_effects, const ui_adaptor &ui_skills, const std::vector< trait_id > &traitslist, const std::vector< bionic > &bionicslist, const std::vector< std::pair< std::string, std::string > > &effect_name_and_text, const std::vector< HeaderSkill > &skillslist)
Variables
static const skill_id skill_swimming ("swimming")
static const std::string title_STATS = translate_marker("STATS")
static const std::string title_ENCUMB = translate_marker("ENCUMBRANCE AND WARMTH")
static const std::string title_EFFECTS = translate_marker("EFFECTS")
static const std::string title_SPEED = translate_marker("SPEED")
static const std::string title_SKILLS = translate_marker("SKILLS")
static const std::string title_BIONICS = translate_marker("BIONICS")
static const std::string title_TRAITS = translate_marker("TRAITS")
Function Documentation
dodge_skill_text()
static std::string dodge_skill_text (double mod) static
Definition at line 195 of file character_display.cpp.
{
    return string_format( _( "Dodge skill: <color_white>%+.1f</color>\n" ), mod );
}
References _, and string_format().
Referenced by get_encumbrance_description().
draw_bionics_info()
static void draw_bionics_info (const catacurses::window & w_info, const unsigned int line, const std::vector< bionic > & bionicslist) static
Definition at line 568 of file character_display.cpp.
{
    werase( w_info );
    if( line < bionicslist.size() ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_light_gray, "%s",
                        bionicslist[line].info().description );
    }
    wnoutrefresh( w_info );
}
References c_light_gray, fold_and_print(), FULL_SCREEN_WIDTH, line(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_bionics_tab()
static void draw_bionics_tab (const catacurses::window & w_bionics, const Character & you, const unsigned int line, const player_display_tab curtab, const std::vector< bionic > & bionicslist, const size_t bionics_win_size_y) static
Definition at line 530 of file character_display.cpp.
{
    werase( w_bionics );
    const bool is_current_tab = curtab == player_display_tab::bionics;
    const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
    center_print( w_bionics, 0, title_col, _( title_BIONICS ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    trim_and_print( w_bionics, point( 1, 1 ), getmaxx( w_bionics ) - 1, c_white,
                    string_format( _( "Bionic Power: <color_light_blue>%1$d</color>"
                                      " / <color_light_blue>%2$d</color>" ),
                                   units::to_kilojoule( you.get_power_level() ), units::to_kilojoule( you.get_max_power_level() ) ) );
    const size_t useful_y = bionics_win_size_y - 2;
    const size_t half_y = useful_y / 2;
    size_t min = 0;
    size_t max = 0;
    if( !is_current_tab || line <= half_y ) { // near the top
        min = 0;
        max = std::min( bionicslist.size(), useful_y );
    } else if( line >= bionicslist.size() - half_y ) { // near the bottom
        min = ( bionicslist.size() <= useful_y ? 0 : bionicslist.size() - useful_y );
        max = bionicslist.size();
    } else { // scrolling
        min = line - half_y;
        max = std::min( bionicslist.size(), line + useful_y - half_y );
    }
    for( size_t i = min; i < max; i++ ) {
        trim_and_print( w_bionics, point( 1, static_cast<int>( 2 + i - min ) ), getmaxx( w_bionics ) - 1,
                        is_current_tab && i == line ? hilite( c_white ) : c_white, "%s", bionicslist[i].info().name );
    }
    wnoutrefresh( w_bionics );
}
References _, c_light_gray, c_white, center_print(), Character::get_max_power_level(), Character::get_power_level(), catacurses::getmaxx(), h_light_gray, hilite(), line(), om_direction::name(), string_format(), title_BIONICS, units::to_kilojoule(), trim_and_print(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_effects_info()
static void draw_effects_info (const catacurses::window & w_info, const unsigned int line, const std::vector< std::pair< std::string, std::string > > & effect_name_and_text) static
Definition at line 621 of file character_display.cpp.
{
    werase( w_info );
    const size_t actual_size = effect_name_and_text.size();
    if( line < actual_size ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                        effect_name_and_text[line].second );
    }
    wnoutrefresh( w_info );
}
References c_light_gray, fold_and_print(), FULL_SCREEN_WIDTH, line(), second, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_effects_tab()
static void draw_effects_tab (const catacurses::window & w_effects, const unsigned int line, const player_display_tab curtab, const std::vector< std::pair< std::string, std::string > > & effect_name_and_text, const size_t effect_win_size_y) static
Definition at line 580 of file character_display.cpp.
{
    werase( w_effects );
    const bool is_current_tab = curtab == player_display_tab::effects;
    const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
    center_print( w_effects, 0, title_col, _( title_EFFECTS ) );
    const size_t half_y = ( effect_win_size_y - 1 ) / 2;
    size_t min = 0;
    size_t max = 0;
    const size_t actual_size = effect_name_and_text.size();
    if( !is_current_tab || line <= half_y ) {
        min = 0;
        max = effect_win_size_y - 1;
        if( actual_size < max ) {
            max = actual_size;
        }
    } else if( line >= actual_size - half_y ) {
        min = ( actual_size < effect_win_size_y - 1 ? 0 : actual_size - effect_win_size_y + 1 );
        max = actual_size;
    } else {
        min = line - half_y;
        max = line - half_y + effect_win_size_y - 1;
        if( actual_size < max ) {
            max = actual_size;
        }
    }
    for( size_t i = min; i < max; i++ ) {
        trim_and_print( w_effects, point( 0, static_cast<int>( 1 + i - min ) ), getmaxx( w_effects ) - 1,
                        is_current_tab && i == line ? h_light_gray : c_light_gray, effect_name_and_text[i].first );
    }
    wnoutrefresh( w_effects );
}
References _, c_light_gray, center_print(), catacurses::getmaxx(), h_light_gray, line(), title_EFFECTS, trim_and_print(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_encumbrance_info()
static void draw_encumbrance_info (const catacurses::window & w_info, const Character & you, const unsigned int line) static
Definition at line 460 of file character_display.cpp.
{
    const std::vector<std::pair<body_part, bool>> bps = list_and_combine_bps( you, nullptr );
    werase( w_info );
    body_part bp = num_bp;
    bool combined_here = false;
    if( line < bps.size() ) {
        bp = bps[line].first;
        combined_here = bps[line].second;
    }
    const std::string s = get_encumbrance_description( you, bp, combined_here );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_light_gray, s );
    wnoutrefresh( w_info );
}
References c_light_gray, fold_and_print(), FULL_SCREEN_WIDTH, get_encumbrance_description(), line(), list_and_combine_bps(), num_bp, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_encumbrance_tab()
static void draw_encumbrance_tab (const catacurses::window & w_encumb, const Character & you, const unsigned int line, const player_display_tab curtab) static
Definition at line 445 of file character_display.cpp.
{
    werase( w_encumb );
    const bool is_current_tab = curtab == player_display_tab::encumbrance;
    const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
    center_print( w_encumb, 0, title_col, _( title_ENCUMB ) );
    if( is_current_tab ) {
        character_display::print_encumbrance( w_encumb, you, line );
    } else {
        character_display::print_encumbrance( w_encumb, you );
    }
    wnoutrefresh( w_encumb );
}
References _, c_light_gray, center_print(), h_light_gray, line(), character_display::print_encumbrance(), title_ENCUMB, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_info_window()
static void draw_info_window (const catacurses::window & w_info, const Character & you, const unsigned int line, const player_display_tab curtab, const std::vector< trait_id > & traitslist, const std::vector< bionic > & bionicslist, const std::vector< std::pair< std::string, std::string > > & effect_name_and_text, const std::vector< HeaderSkill > & skillslist) static
Definition at line 862 of file character_display.cpp.
{
    switch( curtab ) {
        case player_display_tab::stats:
            draw_stats_info( w_info, you, line );
            break;
        case player_display_tab::encumbrance:
            draw_encumbrance_info( w_info, you, line );
            break;
        case player_display_tab::skills:
            draw_skills_info( w_info, line, skillslist );
            break;
        case player_display_tab::traits:
            draw_traits_info( w_info, line, traitslist );
            break;
        case player_display_tab::bionics:
            draw_bionics_info( w_info, line, bionicslist );
            break;
        case player_display_tab::effects:
            draw_effects_info( w_info, line, effect_name_and_text );
            break;
        case player_display_tab::num_tabs:
            abort();
    }
}
References abort, draw_bionics_info(), draw_effects_info(), draw_encumbrance_info(), draw_skills_info(), draw_stats_info(), draw_traits_info(), and line().
Referenced by character_display::disp_info().
draw_skills_info()
static void draw_skills_info (const catacurses::window & w_info, unsigned int line, const std::vector< HeaderSkill > & skillslist) static
Definition at line 738 of file character_display.cpp.
{
    werase( w_info );
    if( line < 1 ) {
        line = 1;
    }
    const Skill *selectedSkill = nullptr;
    if( line < skillslist.size() && !skillslist[line].is_header ) {
        selectedSkill = skillslist[line].skill;
    }
    werase( w_info );
    if( selectedSkill ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                        selectedSkill->description() );
    }
    wnoutrefresh( w_info );
}
References c_light_gray, Skill::description(), fold_and_print(), FULL_SCREEN_WIDTH, line(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_skills_tab()
static void draw_skills_tab (const catacurses::window & w_skills, Character & you, unsigned int line, const player_display_tab curtab, std::vector< HeaderSkill > & skillslist, const size_t skill_win_size_y) static
Definition at line 641 of file character_display.cpp.
{
    const int col_width = 25;
    if( line == 0 ) { //can't point to a header;
        line = 1;
    }
    werase( w_skills );
    const bool is_current_tab = curtab == player_display_tab::skills;
    nc_color cstatus = is_current_tab ? h_light_gray : c_light_gray;
    center_print( w_skills, 0, cstatus, _( title_SKILLS ) );
    size_t min = 0;
    size_t max = 0;
    const size_t half_y = ( skill_win_size_y - 1 ) / 2;
    if( !is_current_tab || line <= half_y ) {
        min = 0;
    } else if( line >= skillslist.size() - half_y ) {
        min = ( skillslist.size() < skill_win_size_y - 1 ? 0 : skillslist.size() -
                skill_win_size_y + 1 );
    } else {
        min = line - half_y;
    }
    max = std::min( min + skill_win_size_y - 1, skillslist.size() );
    int y_pos = 1;
    for( size_t i = min; i < max; i++, y_pos++ ) {
        const Skill *aSkill = skillslist[i].skill;
        const SkillLevel &level = you.get_skill_level_object( aSkill->ident() );
        if( skillslist[i].is_header ) {
            const SkillDisplayType t = SkillDisplayType::get_skill_type( aSkill->display_category() );
            std::string type_name = t.display_string();
            mvwprintz( w_skills, point( 0, y_pos ), c_light_gray, header_spaces );
            center_print( w_skills, y_pos, c_yellow, type_name );
        } else {
            const bool can_train = level.can_train();
            const bool training = level.isTraining();
            const bool rusting = level.isRusting();
            int exercise = level.exercise();
            int level_num = level.level();
            bool locked = false;
            if( you.has_active_bionic( bionic_id( "bio_cqb" ) ) && is_cqb_skill( aSkill->ident() ) ) {
                level_num = 5;
                exercise = 0;
                locked = true;
            }
            if( is_current_tab && i == line ) {
                if( locked ) {
                    cstatus = h_yellow;
                } else if( !can_train ) {
                    cstatus = rusting ? h_light_red : h_white;
                } else if( exercise >= 100 ) {
                    cstatus = training ? h_pink : h_magenta;
                } else if( rusting ) {
                    cstatus = training ? h_light_red : h_red;
                } else {
                    cstatus = training ? h_light_blue : h_blue;
                }
                mvwprintz( w_skills, point( 1, y_pos ), cstatus, std::string( col_width, ' ' ) );
            } else {
                if( locked ) {
                    cstatus = c_yellow;
                } else if( rusting ) {
                    cstatus = training ? c_light_red : c_red;
                } else if( !can_train ) {
                    cstatus = c_white;
                } else {
                    cstatus = training ? c_light_blue : c_blue;
                }
                mvwprintz( w_skills, point( 1, y_pos ), c_light_gray, std::string( col_width, ' ' ) );
            }
            mvwprintz( w_skills, point( 1, y_pos ), cstatus, "%s:", aSkill->name() );
            if( aSkill->ident() == skill_id( "dodge" ) ) {
                mvwprintz( w_skills, point( 14, y_pos ), cstatus, "%4.1f/%-2d(%2d%%)",
                           you.get_dodge(), level_num, exercise < 0 ? 0 : exercise );
            } else {
                mvwprintz( w_skills, point( 19, y_pos ), cstatus, "%-2d(%2d%%)",
                           level_num,
                           ( exercise < 0 ? 0 : exercise ) );
            }
        }
    }
    if( is_current_tab && skillslist.size() > skill_win_size_y - 1 ) {
        draw_scrollbar( w_skills, line - 1, skill_win_size_y - 1, skillslist.size() - 1,
                        // NOLINTNEXTLINE(cata-use-named-point-constants)
                        point( 0, 1 ) );
    }
    wnoutrefresh( w_skills );
}
References _, c_blue, c_light_blue, c_light_gray, c_light_red, c_red, c_white, c_yellow, SkillLevel::can_train(), center_print(), Skill::display_category(), SkillDisplayType::display_string(), draw_scrollbar(), SkillLevel::exercise(), Character::get_dodge(), Character::get_skill_level_object(), SkillDisplayType::get_skill_type(), h_blue, h_light_blue, h_light_gray, h_light_red, h_magenta, h_pink, h_red, h_white, h_yellow, Character::has_active_bionic(), header_spaces(), Skill::ident(), is_cqb_skill(), SkillLevel::isRusting(), SkillLevel::isTraining(), SkillLevel::level(), line(), mvwprintz(), Skill::name(), title_SKILLS, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_speed_tab()
static void draw_speed_tab (const catacurses::window & w_speed, const Character & you, const std::map< std::string, int > & speed_effects) static
Definition at line 760 of file character_display.cpp.
{
    werase( w_speed );
    // Finally, draw speed.
    center_print( w_speed, 0, c_light_gray, _( title_SPEED ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w_speed, point( 1, 1 ), c_light_gray, _( "Base Move Cost:" ) );
    mvwprintz( w_speed, point( 1, 2 ), c_light_gray, _( "Current Speed:" ) );
    int newmoves = you.get_speed();
    int pen = 0;
    unsigned int line = 3;
    if( you.weight_carried() > you.weight_capacity() ) {
        pen = 25 * ( you.weight_carried() - you.weight_capacity() ) / ( you.weight_capacity() );
        mvwprintz( w_speed, point( 1, line ), c_red,
                   pgettext( "speed penalty", "Overburdened        -%2d%%" ), pen );
        line++;
    }
    pen = character_effects::get_pain_penalty( you ).speed;
    if( pen >= 1 ) {
        mvwprintz( w_speed, point( 1, line ), c_red,
                   pgettext( "speed penalty", "Pain                -%2d%%" ), pen );
        line++;
    }
    if( you.get_thirst() > thirst_levels::very_thirsty ) {
        pen = std::abs( character_effects::get_thirst_speed_penalty( you.get_thirst() ) );
        mvwprintz( w_speed, point( 1, line ), c_red,
                   pgettext( "speed penalty", "Thirst              -%2d%%" ), pen );
        line++;
    }
    if( character_effects::get_kcal_speed_penalty( you.get_kcal_percent() ) < 0 ) {
        pen = std::abs( character_effects::get_kcal_speed_penalty( you.get_kcal_percent() ) );
        //~ %s: Starving/Underfed (already left-justified), %2d: speed penalty
        mvwprintz( w_speed, point( 1, line ), c_red, pgettext( "speed penalty", "%s-%2d%%" ),
                   left_justify( _( "Starving" ), 20 ), pen );
        line++;
    }
    if( you.has_trait( trait_id( "SUNLIGHT_DEPENDENT" ) ) && !g->is_in_sunlight( you.pos() ) ) {
        pen = ( g->light_level( you.posz() ) >= 12 ? 5 : 10 );
        mvwprintz( w_speed, point( 1, line ), c_red,
                   pgettext( "speed penalty", "Out of Sunlight     -%2d%%" ), pen );
        line++;
    }
    const float temperature_speed_modifier = you.mutation_value( "temperature_speed_modifier" );
    if( temperature_speed_modifier != 0 ) {
        nc_color pen_color;
        std::string pen_sign;
        const auto player_local_temp = get_weather().get_temperature( you.pos() );
        if( you.has_trait( trait_id( "COLDBLOOD4" ) ) && player_local_temp > 65 ) {
            pen_color = c_green;
            pen_sign = "+";
        } else if( player_local_temp < 65 ) {
            pen_color = c_red;
            pen_sign = "-";
        }
        if( !pen_sign.empty() ) {
            pen = ( player_local_temp - 65 ) * temperature_speed_modifier;
            mvwprintz( w_speed, point( 1, line ), pen_color,
                       //~ %s: sign of bonus/penalty, %2d: speed bonus/penalty
                       pgettext( "speed modifier", "Cold-Blooded        %s%2d%%" ), pen_sign, std::abs( pen ) );
            line++;
        }
    }
    int quick_bonus = static_cast<int>( newmoves - ( newmoves / 1.1 ) );
    int bio_speed_bonus = quick_bonus;
    if( you.has_trait( trait_id( "QUICK" ) ) && you.has_bionic( bionic_id( "bio_speed" ) ) ) {
        bio_speed_bonus = static_cast<int>( newmoves / 1.1 - ( newmoves / 1.1 / 1.1 ) );
        std::swap( quick_bonus, bio_speed_bonus );
    }
    if( you.has_trait( trait_id( "QUICK" ) ) ) {
        mvwprintz( w_speed, point( 1, line ), c_green,
                   pgettext( "speed bonus", "Quick               +%2d%%" ), quick_bonus );
        line++;
    }
    if( you.has_bionic( bionic_id( "bio_speed" ) ) ) {
        mvwprintz( w_speed, point( 1, line ), c_green,
                   pgettext( "speed bonus", "Bionic Speed        +%2d%%" ), bio_speed_bonus );
        line++;
    }
    for( const std::pair<const std::string, int> &speed_effect : speed_effects ) {
        nc_color col = ( speed_effect.second > 0 ? c_green : c_red );
        mvwprintz( w_speed, point( 1, line ), col, "%s", speed_effect.first );
        mvwprintz( w_speed, point( 21, line ), col, ( speed_effect.second > 0 ? "+" : "-" ) );
        mvwprintz( w_speed, point( std::abs( speed_effect.second ) >= 10 ? 22 : 23, line ), col, "%d%%",
                   std::abs( speed_effect.second ) );
        line++;
    }
    int runcost = you.run_cost( 100 );
    nc_color col = ( runcost <= 100 ? c_green : c_red );
    mvwprintz( w_speed, point( 21 + ( runcost >= 100 ? 0 : ( runcost < 10 ? 2 : 1 ) ), 1 ), col,
               "%d", runcost );
    col = ( newmoves >= 100 ? c_green : c_red );
    mvwprintz( w_speed, point( 21 + ( newmoves >= 100 ? 0 : ( newmoves < 10 ? 2 : 1 ) ), 2 ), col,
               "%d", newmoves );
    wnoutrefresh( w_speed );
}
References _, c_green, c_light_gray, c_red, center_print(), g, Character::get_kcal_percent(), character_effects::get_kcal_speed_penalty(), character_effects::get_pain_penalty(), Character::get_speed(), weather_manager::get_temperature(), Character::get_thirst(), character_effects::get_thirst_speed_penalty(), get_weather(), Character::has_bionic(), Character::has_trait(), left_justify(), line(), Character::mutation_value(), mvwprintz(), pgettext(), Character::pos(), Character::posz(), Character::run_cost(), stat_mod::speed, cata::swap(), title_SPEED, very_thirsty, Character::weight_capacity(), Character::weight_carried(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_stats_info()
static void draw_stats_info (const catacurses::window & w_info, const Character & you, const unsigned int line) static
Definition at line 370 of file character_display.cpp.
{
    werase( w_info );
    nc_color col_temp = c_light_gray;
    if( line == 0 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                        _( "Strength affects your melee damage, the amount of weight you can carry, your total HP, "
                           "your resistance to many diseases, and the effectiveness of actions which require brute force." ) );
        print_colored_text( w_info, point( 1, 3 ), col_temp, c_light_gray,
                            string_format( _( "Base HP: <color_white>%d</color>" ),
                                           you.get_part_hp_max( bodypart_id( "torso" ) ) ) );
        print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                            string_format( _( "Carry weight (%s): <color_white>%.1f</color>" ), weight_units(),
                                           convert_weight( you.weight_capacity() ) ) );
        print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                            string_format( _( "Melee damage: <color_white>%.1f</color>" ), you.bonus_damage( false ) ) );
    } else if( line == 1 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                        _( "Dexterity affects your chance to hit in melee combat, helps you steady your "
                           "gun for ranged combat, and enhances many actions that require finesse." ) );
        print_colored_text( w_info, point( 1, 3 ), col_temp, c_light_gray,
                            string_format( _( "Melee to-hit bonus: <color_white>%+.1lf</color>" ), you.get_melee_hit_base() ) );
        print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                            string_format( _( "Ranged penalty: <color_white>%+d</color>" ),
                                           -std::abs( you.ranged_dex_mod() ) ) );
        print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                            string_format( _( "Throwing penalty per target's dodge: <color_white>%+d</color>" ),
                                           ranged::throw_dispersion_per_dodge( you, false ) ) );
    } else if( line == 2 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                        _( "Intelligence is less important in most situations, but it is vital for more complex tasks like "
                           "electronics crafting.  It also affects how much skill you can pick up from reading a book." ) );
        if( you.rust_rate() ) {
            print_colored_text( w_info, point( 1, 3 ), col_temp, c_light_gray,
                                string_format( _( "Skill rust: <color_white>%d%%</color>" ), you.rust_rate() ) );
        }
        print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                            string_format( _( "Read times: <color_white>%d%%</color>" ), you.read_speed( false ) ) );
        print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                            string_format( _( "Crafting bonus: <color_white>+%d%%</color>" ), you.get_int() ) );
    } else if( line == 3 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                        _( "Perception is the most important stat for ranged combat.  It's also used for "
                           "detecting traps and other things of interest." ) );
        print_colored_text( w_info, point( 1, 3 ), col_temp, c_light_gray,
                            string_format( _( "Base night vision range: <color_white>%.1f</color>" ),
                                           vision::nv_range_from_per( you.get_per() ) ) );
        print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                            string_format( _( "Trap detection level: <color_white>%d</color>" ), you.get_per() ) );
        if( you.ranged_per_mod() > 0 ) {
            print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                                string_format( _( "Aiming penalty: <color_white>%+d</color>" ), -you.ranged_per_mod() ) );
        }
    } else if( line == 4 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        const int lines = fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                                          _( "Your height.  Simply how tall you are." ) );
        fold_and_print( w_info, point( 1, 1 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                        you.height_string() );
    } else if( line == 5 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        const int lines = fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                                          _( "This is how old you are." ) );
        fold_and_print( w_info, point( 1, 1 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                        you.age_string() );
    }
    wnoutrefresh( w_info );
}
References _, Character::age_string(), Character::bonus_damage(), c_light_gray, c_magenta, convert_weight(), fold_and_print(), FULL_SCREEN_WIDTH, Character::get_int(), Character::get_melee_hit_base(), Creature::get_part_hp_max(), Character::get_per(), Character::height_string(), line(), vision::nv_range_from_per(), print_colored_text(), Character::ranged_dex_mod(), Character::ranged_per_mod(), Character::read_speed(), Character::rust_rate(), string_format(), ranged::throw_dispersion_per_dodge(), Character::weight_capacity(), weight_units(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_stats_tab()
static void draw_stats_tab (const catacurses::window & w_stats, const Character & you, const unsigned int line, const player_display_tab curtab) static
Definition at line 318 of file character_display.cpp.
{
    werase( w_stats );
    const nc_color title_col = curtab == player_display_tab::stats ? h_light_gray : c_light_gray;
    center_print( w_stats, 0, title_col, _( title_STATS ) );
    const auto line_color = [curtab, line]( const unsigned int line_to_draw ) {
        if( curtab == player_display_tab::stats && line == line_to_draw ) {
            return h_light_gray;
        } else {
            return c_light_gray;
        }
    };
    // Stats
    const auto display_stat = [&w_stats]( const char *name, int cur, int max, int line_n,
    const nc_color col ) {
        nc_color cstatus;
        if( cur <= 0 ) {
            cstatus = c_dark_gray;
        } else if( cur < max / 2 ) {
            cstatus = c_red;
        } else if( cur < max ) {
            cstatus = c_light_red;
        } else if( cur == max ) {
            cstatus = c_white;
        } else if( cur < max * 1.5 ) {
            cstatus = c_light_green;
        } else {
            cstatus = c_green;
        }
        mvwprintz( w_stats, point( 1, line_n ), col, name );
        mvwprintz( w_stats, point( 18, line_n ), cstatus, "%2d", cur );
        mvwprintz( w_stats, point( 21, line_n ), c_light_gray, "(%2d)", max );
    };
    display_stat( _( "Strength:" ), you.get_str(), you.get_str_base(), 1, line_color( 0 ) );
    display_stat( _( "Dexterity:" ), you.get_dex(), you.get_dex_base(), 2, line_color( 1 ) );
    display_stat( _( "Intelligence:" ), you.get_int(), you.get_int_base(), 3, line_color( 2 ) );
    display_stat( _( "Perception:" ), you.get_per(), you.get_per_base(), 4, line_color( 3 ) );
    mvwprintz( w_stats, point( 1, 5 ), line_color( 4 ), _( "Height:" ) );
    mvwprintz( w_stats, point( 25 - utf8_width( you.height_string() ), 5 ), line_color( 4 ),
               you.height_string() );
    mvwprintz( w_stats, point( 1, 6 ), line_color( 5 ), _( "Age:" ) );
    mvwprintz( w_stats, point( 25 - utf8_width( you.age_string() ), 6 ), line_color( 5 ),
               you.age_string() );
    wnoutrefresh( w_stats );
}
References _, Character::age_string(), c_dark_gray, c_green, c_light_gray, c_light_green, c_light_red, c_red, c_white, center_print(), display_stat(), Character::get_dex(), Character::get_dex_base(), Character::get_int(), Character::get_int_base(), Character::get_per(), Character::get_per_base(), Character::get_str(), Character::get_str_base(), h_light_gray, Character::height_string(), line(), mvwprintz(), om_direction::name(), title_STATS, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_tip()
static void draw_tip (const catacurses::window & w_tip, const Character & you, const std::string & race, const input_context & ctxt) static
Definition at line 893 of file character_display.cpp.
{
    werase( w_tip );
    // Print name and header
    if( you.custom_profession.empty() ) {
        if( you.crossed_threshold() ) {
            //~ player info window: 1s - name, 2s - gender, 3s - Prof or Mutation name
            mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s | %3$s" ), you.name,
                       you.male ? _( "Male" ) : _( "Female" ), race );
        } else if( !you.prof.is_valid() || you.prof == profession::generic() ) {
            // Regular person. Nothing interesting.
            //~ player info window: 1s - name, 2s - gender '|' - field separator.
            mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s" ), you.name,
                       you.male ? _( "Male" ) : _( "Female" ) );
        } else {
            mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s | %3$s" ), you.name,
                       you.male ? _( "Male" ) : _( "Female" ), you.prof->gender_appropriate_name( you.male ) );
        }
    } else {
        mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s | %3$s" ), you.name,
                   you.male ? _( "Male" ) : _( "Female" ), you.custom_profession );
    }
    right_print( w_tip, 0, 1, c_white, string_format(
                     _( "[<color_yellow>%s</color>]" ),
                     ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
    wnoutrefresh( w_tip );
}
References _, c_white, Character::crossed_threshold(), Character::custom_profession, profession::gender_appropriate_name(), profession::generic(), input_context::get_desc(), string_id< T >::is_valid(), Character::male, mvwprintz(), Character::name, point_zero, Character::prof, right_print(), string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
draw_traits_info()
static void draw_traits_info (const catacurses::window & w_info, const unsigned int line, const std::vector< trait_id > & traitslist) static
Definition at line 517 of file character_display.cpp.
{
    werase( w_info );
    if( line < traitslist.size() ) {
        const auto &mdata = traitslist[line].obj();
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_light_gray, string_format(
                            "%s: %s", colorize( mdata.name(), mdata.get_display_color() ), traitslist[line]->desc() ) );
    }
    wnoutrefresh( w_info );
}
References c_light_gray, colorize(), fold_and_print(), FULL_SCREEN_WIDTH, line(), string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_traits_tab()
static void draw_traits_tab (const catacurses::window & w_traits, const unsigned int line, const player_display_tab curtab, const std::vector< trait_id > & traitslist, const size_t trait_win_size_y) static
Definition at line 478 of file character_display.cpp.
{
    werase( w_traits );
    const bool is_current_tab = curtab == player_display_tab::traits;
    const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
    center_print( w_traits, 0, title_col, _( title_TRAITS ) );
    size_t min = 0;
    size_t max = 0;
    if( !is_current_tab || line <= ( trait_win_size_y - 2 ) / 2 ) {
        min = 0;
        max = trait_win_size_y - 1;
        if( traitslist.size() < max ) {
            max = traitslist.size();
        }
    } else if( line >= traitslist.size() - trait_win_size_y / 2 ) {
        min = ( traitslist.size() < trait_win_size_y - 1 ? 0 : traitslist.size() - trait_win_size_y + 1 );
        max = traitslist.size();
    } else {
        min = line - ( trait_win_size_y - 2 ) / 2;
        max = line + ( trait_win_size_y + 1 ) / 2;
        if( traitslist.size() < max ) {
            max = traitslist.size();
        }
    }
    for( size_t i = min; i < max; i++ ) {
        const auto &mdata = traitslist[i].obj();
        const auto color = mdata.get_display_color();
        trim_and_print( w_traits, point( 1, static_cast<int>( 1 + i - min ) ), getmaxx( w_traits ) - 1,
                        is_current_tab && i == line ? hilite( color ) : color, mdata.name() );
    }
    wnoutrefresh( w_traits );
}
References _, c_light_gray, center_print(), color(), catacurses::getmaxx(), h_light_gray, hilite(), line(), title_TRAITS, trim_and_print(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by character_display::disp_info().
get_encumbrance()
static int get_encumbrance (const Character & p, body_part bp, bool combine) static
Definition at line 200 of file character_display.cpp.
{
    // Body parts that can't combine with anything shouldn't print double values on combine
    // This shouldn't happen, but handle this, just in case
    const bool combines_with_other = static_cast<int>( bp_aiOther[bp] ) != bp;
    return p.encumb( bp ) * ( ( combine && combines_with_other ) ? 2 : 1 );
}
References bp_aiOther, and Character::encumb().
Referenced by get_encumbrance_description().
get_encumbrance_description()
static std::string get_encumbrance_description (const Character & p, body_part bp, bool combine) static
Definition at line 208 of file character_display.cpp.
{
    std::string s;
    const int eff_encumbrance = get_encumbrance( p, bp, combine );
    switch( bp ) {
        case bp_torso: {
            const int melee_roll_pen = std::max( -eff_encumbrance, -80 );
            s += string_format( _( "Melee attack rolls: <color_white>%+d%%</color>\n" ), melee_roll_pen );
            s += dodge_skill_text( -( eff_encumbrance / 10.0 ) );
            s += swim_cost_text( ( eff_encumbrance / 10.0 ) * ( 80 - p.get_skill_level(
                                     skill_swimming ) * 3 ) );
            s += melee_cost_text( eff_encumbrance );
            break;
        }
        case bp_head:
            s += _( "<color_magenta>Head encumbrance has no effect; it simply limits how much you can put on.</color>" );
            break;
        case bp_eyes:
            s += string_format(
                     _( "Perception when checking traps or firing ranged weapons: <color_white>%+d</color>\n"
                        "Dispersion when throwing items: <color_white>%+d</color>\n"
                        "Night vision range: <color_white>%+.1f</color>" ),
                     -( eff_encumbrance / 10 ),
                     eff_encumbrance * 10,
                     vision::nv_range_from_eye_encumbrance( eff_encumbrance ) );
            break;
        case bp_mouth:
            s += _( "<color_magenta>Covering your mouth will make it more difficult to breathe and catch your breath.</color>\n" );
            s += mouth_stamina_cost_text( -( eff_encumbrance / 5 ) );
            break;
        case bp_arm_l:
        case bp_arm_r:
            s += _( "<color_magenta>Arm encumbrance affects stamina cost of melee attacks and accuracy with ranged weapons.</color>\n" );
            s += melee_stamina_cost_text( eff_encumbrance * 2 );
            s += ranged_cost_text( eff_encumbrance / 5.0 );
            break;
        case bp_hand_l:
        case bp_hand_r:
            s += _( "<color_magenta>Reduces the speed at which you can handle or manipulate items.</color>\n\n" );
            s += reload_cost_text( ( eff_encumbrance / 10 ) * 15 );
            s += string_format( _( "Dexterity when throwing items: <color_white>%+.1f</color>\n" ),
                                -( eff_encumbrance / 10.0f ) );
            s += melee_cost_text( eff_encumbrance / 2 );
            s += string_format( _( "Reduced gun aim speed: <color_white>%.1f</color>" ),
                                ranged::aim_speed_encumbrance_modifier( p ) );
            break;
        case bp_leg_l:
        case bp_leg_r:
            s += run_cost_text( static_cast<int>( eff_encumbrance * 0.15 ) );
            s += swim_cost_text( ( eff_encumbrance / 10 ) * ( 50 - p.get_skill_level(
                                     skill_swimming ) * 2 ) / 2 );
            s += dodge_skill_text( -eff_encumbrance / 10.0 / 4.0 );
            break;
        case bp_foot_l:
        case bp_foot_r:
            s += run_cost_text( static_cast<int>( eff_encumbrance * 0.25 ) );
            break;
        case num_bp:
            break;
    }
    return s;
}
References _, ranged::aim_speed_encumbrance_modifier(), bp_arm_l, bp_arm_r, bp_eyes, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_mouth, bp_torso, dodge_skill_text(), get_encumbrance(), Character::get_skill_level(), melee_cost_text(), melee_stamina_cost_text(), mouth_stamina_cost_text(), num_bp, vision::nv_range_from_eye_encumbrance(), ranged_cost_text(), reload_cost_text(), run_cost_text(), skill_swimming, string_format(), and swim_cost_text().
Referenced by draw_encumbrance_info().
handle_player_display_action()
static bool handle_player_display_action (Character & you, unsigned int & line, player_display_tab & curtab, input_context & ctxt, const ui_adaptor & ui_tip, const ui_adaptor & ui_info, const ui_adaptor & ui_stats, const ui_adaptor & ui_encumb, const ui_adaptor & ui_traits, const ui_adaptor & ui_bionics, const ui_adaptor & ui_effects, const ui_adaptor & ui_skills, const std::vector< trait_id > & traitslist, const std::vector< bionic > & bionicslist, const std::vector< std::pair< std::string, std::string > > & effect_name_and_text, const std::vector< HeaderSkill > & skillslist) static
Definition at line 925 of file character_display.cpp.
{
    const auto invalidate_tab = [&]( const player_display_tab tab ) {
        switch( tab ) {
            case player_display_tab::stats:
                ui_stats.invalidate_ui();
                break;
            case player_display_tab::encumbrance:
                ui_encumb.invalidate_ui();
                break;
            case player_display_tab::traits:
                ui_traits.invalidate_ui();
                break;
            case player_display_tab::bionics:
                ui_bionics.invalidate_ui();
                break;
            case player_display_tab::effects:
                ui_effects.invalidate_ui();
                break;
            case player_display_tab::skills:
                ui_skills.invalidate_ui();
                break;
            case player_display_tab::num_tabs:
                abort();
        }
    };
    unsigned int line_beg = 0;
    unsigned int line_end = 0;
    switch( curtab ) {
        case player_display_tab::stats:
            line_end = 6;
            break;
        case player_display_tab::encumbrance: {
            const std::vector<std::pair<body_part, bool>> bps = list_and_combine_bps( you, nullptr );
            line_end = bps.size();
            break;
        }
        case player_display_tab::traits:
            line_end = traitslist.size();
            break;
        case player_display_tab::bionics:
            line_end = bionicslist.size();
            break;
        case player_display_tab::effects:
            line_end = effect_name_and_text.size();
            break;
        case player_display_tab::skills:
            line_beg = 1; // skip first header
            line_end = skillslist.size();
            break;
        case player_display_tab::num_tabs:
            abort();
    }
    if( line_beg >= line_end || line < line_beg ) {
        line = line_beg;
    } else if( line > line_end - 1 ) {
        line = line_end - 1;
    }
    bool done = false;
    std::string action = ctxt.handle_input();
    if( action == "UP" ) {
        if( line > line_beg ) {
            --line;
        } else {
            line = line_end - 1;
        }
        if( curtab == player_display_tab::skills && skillslist[line].is_header ) {
            --line;
        }
        invalidate_tab( curtab );
        ui_info.invalidate_ui();
    } else if( action == "DOWN" ) {
        if( line + 1 < line_end ) {
            ++line;
        } else {
            line = line_beg;
        }
        if( curtab == player_display_tab::skills && skillslist[line].is_header ) {
            ++line;
        }
        invalidate_tab( curtab );
        ui_info.invalidate_ui();
    } else if( action == "NEXT_TAB" || action == "PREV_TAB" ) {
        line = 0;
        invalidate_tab( curtab );
        curtab = action == "NEXT_TAB" ? next_tab( curtab ) : prev_tab( curtab );
        invalidate_tab( curtab );
        ui_info.invalidate_ui();
    } else if( action == "QUIT" ) {
        done = true;
    } else if( action == "CONFIRM" ) {
        switch( curtab ) {
            default:
                break;
            case player_display_tab::stats:
                if( line < 4 && get_option<bool>( "STATS_THROUGH_KILLS" ) && you.is_avatar() ) {
                    character_display::upgrade_stat_prompt( *you.as_avatar(), static_cast<character_stat>( line ) );
                }
                invalidate_tab( curtab );
                break;
            case player_display_tab::skills: {
                const Skill *selectedSkill = nullptr;
                if( line < skillslist.size() && !skillslist[line].is_header ) {
                    selectedSkill = skillslist[line].skill;
                }
                if( selectedSkill ) {
                    you.get_skill_level_object( selectedSkill->ident() ).toggleTraining();
                }
                invalidate_tab( curtab );
                break;
            }
        }
    } else if( action == "CHANGE_PROFESSION_NAME" ) {
        string_input_popup popup;
        popup.title( _( "Profession Name: " ) )
        .width( 25 )
        .text( "" )
        .max_length( 25 )
        .query();
        you.custom_profession = popup.text();
        ui_tip.invalidate_ui();
    }
    return done;
}
References _, abort, action, Creature::as_avatar(), Character::custom_profession, detail::digits::done, Character::get_skill_level_object(), input_context::handle_input(), Skill::ident(), ui_adaptor::invalidate_ui(), Creature::is_avatar(), line(), list_and_combine_bps(), next_tab(), popup(), prev_tab(), SkillLevel::toggleTraining(), and character_display::upgrade_stat_prompt().
Referenced by character_display::disp_info().
header_spaces()
static const std::string header_spaces (26 , ' ') static
Referenced by draw_skills_tab().
is_cqb_skill()
static bool is_cqb_skill (const skill_id & id) static
Definition at line 274 of file character_display.cpp.
{
    // TODO: this skill list here is used in other places as well. Useless redundancy and
    // dependency. Maybe change it into a flag of the skill that indicates it's a skill used
    // by the bionic?
    static const std::array<skill_id, 5> cqb_skills = { {
            skill_id( "melee" ), skill_id( "unarmed" ), skill_id( "cutting" ),
            skill_id( "bashing" ), skill_id( "stabbing" ),
        }
    };
    return std::find( cqb_skills.begin(), cqb_skills.end(), id ) != cqb_skills.end();
}
References detail::find().
Referenced by draw_skills_tab().
list_and_combine_bps()
static std::vector< std::pair< body_part, bool > > list_and_combine_bps (const Character & ch, const item * selected_clothing) static
Definition at line 74 of file character_display.cpp.
{
    // bool represents whether the part has been combined with its other half
    std::vector<std::pair<body_part, bool>> bps;
    for( auto bp : all_body_parts ) {
        // assuming that a body part has at most one other half
        if( other_part( other_part( bp ) ) != bp ) {
            debugmsg( "Bodypart %d has more than one other half!", bp );
        }
        if( should_combine_bps( ch, bp, other_part( bp ), selected_clothing ) ) {
            if( bp < other_part( bp ) ) {
                // only add the earlier one
                bps.emplace_back( bp, true );
            }
        } else {
            bps.emplace_back( bp, false );
        }
    }
    return bps;
}
References all_body_parts, debugmsg, other_part(), and should_combine_bps().
Referenced by draw_encumbrance_info(), handle_player_display_action(), and character_display::print_encumbrance().
melee_cost_text()
static std::string melee_cost_text (int moves) static
Definition at line 177 of file character_display.cpp.
{
    return string_format(
               _( "Melee and thrown attack movement point cost: <color_white>%+d</color>\n" ), moves );
}
References _, and string_format().
Referenced by get_encumbrance_description().
melee_stamina_cost_text()
static std::string melee_stamina_cost_text (int cost) static
Definition at line 182 of file character_display.cpp.
{
    return string_format( _( "Melee stamina cost: <color_white>%+d</color>\n" ), cost );
}
References _, and string_format().
Referenced by get_encumbrance_description().
mouth_stamina_cost_text()
static std::string mouth_stamina_cost_text (int cost) static
Definition at line 186 of file character_display.cpp.
{
    return string_format( _( "Stamina Regeneration: <color_white>%+d</color>\n" ), cost );
}
References _, and string_format().
Referenced by get_encumbrance_description().
next_tab()
static player_display_tab next_tab (const player_display_tab tab) static
Definition at line 300 of file character_display.cpp.
{
    if( static_cast<int>( tab ) + 1 < static_cast<int>( player_display_tab::num_tabs ) ) {
        return static_cast<player_display_tab>( static_cast<int>( tab ) + 1 );
    } else {
        return static_cast<player_display_tab>( 0 );
    }
}
Referenced by handle_player_display_action().
other_part()
static body_part other_part (body_part bp) static
Definition at line 56 of file character_display.cpp.
{
    return static_cast<body_part>( bp_aiOther[bp] );
}
References bp_aiOther.
Referenced by vehicle::can_mount(), list_and_combine_bps(), and should_combine_bps().
prev_tab()
static player_display_tab prev_tab (const player_display_tab tab) static
Definition at line 309 of file character_display.cpp.
{
    if( static_cast<int>( tab ) > 0 ) {
        return static_cast<player_display_tab>( static_cast<int>( tab ) - 1 );
    } else {
        return static_cast<player_display_tab>( static_cast<int>( player_display_tab::num_tabs ) - 1 );
    }
}
Referenced by handle_player_display_action().
ranged_cost_text()
static std::string ranged_cost_text (double disp) static
Definition at line 190 of file character_display.cpp.
{
    return string_format( _( "Dispersion when using ranged attacks: <color_white>%+.1f</color>\n" ),
                          disp );
}
References _, and string_format().
Referenced by get_encumbrance_description().
reload_cost_text()
static std::string reload_cost_text (int moves) static
Definition at line 172 of file character_display.cpp.
{
    return string_format( _( "Reloading movement point cost: <color_white>%+d</color>\n" ), moves );
}
References _, and string_format().
Referenced by get_encumbrance_description().
run_cost_text()
static std::string run_cost_text (int moves) static
Definition at line 167 of file character_display.cpp.
{
    return string_format( _( "Movement point cost: <color_white>%+d</color>\n" ), moves );
}
References _, and string_format().
Referenced by get_encumbrance_description().
should_combine_bps()
static bool should_combine_bps (const Character & ch, body_part l, body_part r, const item * selected_clothing) static
Definition at line 61 of file character_display.cpp.
{
    const char_encumbrance_data enc_data = ch.get_encumbrance();
    return l != r && // are different parts
           l == other_part( r ) && r == other_part( l ) && // are complementary parts
           // same encumberance & temperature
           enc_data.elems[l] == enc_data.elems[r] &&
           temperature_print_rescaling( ch.temp_conv[l] ) == temperature_print_rescaling( ch.temp_conv[r] ) &&
           // selected_clothing covers both or neither parts
           ( !selected_clothing || ( selected_clothing->covers( l ) == selected_clothing->covers( r ) ) );
}
References item::covers(), char_encumbrance_data::elems, Character::get_encumbrance(), other_part(), Character::temp_conv, and temperature_print_rescaling().
Referenced by list_and_combine_bps().
swim_cost_text()
static std::string swim_cost_text (int moves) static
Definition at line 162 of file character_display.cpp.
{
    return string_format( _( "Swimming movement point cost: <color_white>%+d</color>\n" ), moves );
}
References _, and string_format().
Referenced by get_encumbrance_description().
temperature_print_rescaling()
static int temperature_print_rescaling (int temp) static
Definition at line 51 of file character_display.cpp.
{
    return ( temp / 100.0 ) * 2 - 100;
}
Referenced by character_display::print_encumbrance(), and should_combine_bps().
Variable Documentation
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by get_encumbrance_description().
title_BIONICS
const std::string title_BIONICS = translate_marker("BIONICS") static
Definition at line 44 of file character_display.cpp.
Referenced by draw_bionics_tab().
title_EFFECTS
const std::string title_EFFECTS = translate_marker("EFFECTS") static
Definition at line 41 of file character_display.cpp.
Referenced by draw_effects_tab().
title_ENCUMB
const std::string title_ENCUMB = translate_marker("ENCUMBRANCE AND WARMTH") static
Definition at line 40 of file character_display.cpp.
Referenced by draw_encumbrance_tab().
title_SKILLS
const std::string title_SKILLS = translate_marker("SKILLS") static
Definition at line 43 of file character_display.cpp.
Referenced by draw_skills_tab().
title_SPEED
const std::string title_SPEED = translate_marker("SPEED") static
Definition at line 42 of file character_display.cpp.
Referenced by draw_speed_tab().
title_STATS
const std::string title_STATS = translate_marker("STATS") static
Definition at line 39 of file character_display.cpp.
Referenced by draw_stats_tab().
title_TRAITS
const std::string title_TRAITS = translate_marker("TRAITS") static
Definition at line 45 of file character_display.cpp.
Referenced by draw_traits_tab().