Cataclysm BN: enum_flags_reader< E > Class Template Reference
enum_flags_reader< E > Class Template Reference
Uses io::string_to_enum to convert the string from JSON to a C++ enum.
#include <generic_readers.h>
Public Member Functions
enum_flags_reader (const std::string &flag_type)
E get_next (JsonIn &jin) const
Public Member Functions inherited from generic_typed_reader< enum_flags_reader< E > >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Private Attributes
const std::string flag_type
Detailed Description
template<typename E>
class enum_flags_reader< E >
Uses io::string_to_enum to convert the string from JSON to a C++ enum.
Definition at line 423 of file generic_readers.h.
Constructor & Destructor Documentation
enum_flags_reader()
template<typename E > enum_flags_reader< E >::enum_flags_reader (const std::string & flag_type) inline
Definition at line 429 of file generic_readers.h.
                                                        : flag_type( flag_type ) {
        }
Member Function Documentation
get_next()
template<typename E > E enum_flags_reader< E >::get_next (JsonIn & jin) const inline
Definition at line 432 of file generic_readers.h.
{
            const auto position = jin.tell();
            const std::string flag = jin.get_string();
            try {
                return io::string_to_enum<E>( flag );
            } catch( const io::InvalidEnumString & ) {
                jin.seek( position );
                jin.error( string_format( "invalid %s: \"%s\"", flag_type, flag ) );
                throw; // ^^ throws already
            }
        }
References JsonIn::error(), enum_flags_reader< E >::flag_type, JsonIn::get_string(), JsonIn::seek(), string_format(), and JsonIn::tell().
Member Data Documentation
flag_type
template<typename E > const std::string enum_flags_reader< E >::flag_type private
Definition at line 426 of file generic_readers.h.
Referenced by enum_flags_reader< E >::get_next().
The documentation for this class was generated from the following file:
src/generic_readers.h