Cataclysm BN: emit_actor Class Reference
emit_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
emit_actor (const std::string &type="emit_actor")
~emit_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
Public Attributes
std::set< emit_id > emits
bool scale_qty = false
If true multiplies the emits by number of charges on the item.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1118 of file iuse_actor.h.
Constructor & Destructor Documentation
emit_actor()
emit_actor::emit_actor (const std::string & type = "emit_actor") inline
Definition at line 1125 of file iuse_actor.h.
: iuse_actor(type) {}
~emit_actor()
emit_actor::~emit_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > emit_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4239 of file iuse_actor.cpp.
{
    return std::make_unique<emit_actor>( *this );
}
finalize()
void emit_actor::finalize (const itype_id &) override virtual
Finalizes the actor.
Must be called after all items are loaded.
Reimplemented from iuse_actor.
Definition at line 4244 of file iuse_actor.cpp.
{
    /*
    // TODO: This must be called after all finalization
    for( const auto& e : emits ) {
        if( !e.is_valid() ) {
            debugmsg( "Item %s has unknown emit source %s", my_item_type.c_str(), e.c_str() );
        }
    }
    */
    if( scale_qty && !item::count_by_charges( my_item_type ) ) {
        debugmsg( "Item %s has emit_actor with scale_qty, but is not counted by charges",
                  my_item_type.c_str() );
        scale_qty = false;
    }
}
References string_id< T >::c_str(), item::count_by_charges(), and debugmsg.
load()
void emit_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 4222 of file iuse_actor.cpp.
{
    assign( obj, "emits", emits );
    assign( obj, "scale_qty", scale_qty );
}
References assign().
use()
int emit_actor::use (player & , item & it, bool , const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 4228 of file iuse_actor.cpp.
{
    map &here = get_map();
    const float scaling = scale_qty ? it.charges : 1;
    for( const auto &e : emits ) {
        here.emit_field( pos, e, scaling );
    }
    return 1;
}
References item::charges, map::emit_field(), get_map(), and Character::pos().
Member Data Documentation
emits
std::set<emit_id> emit_actor::emits
Definition at line 1121 of file iuse_actor.h.
scale_qty
bool emit_actor::scale_qty = false
If true multiplies the emits by number of charges on the item.
Definition at line 1123 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp