Cataclysm BN: unfold_vehicle_iuse Class Reference
unfold_vehicle_iuse Class Reference
This iuse creates a new vehicle on the map.
#include <iuse_actor.h>
Public Member Functions
unfold_vehicle_iuse (const std::string &type="unfold_vehicle")
~unfold_vehicle_iuse () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
vproto_id vehicle_id
Id of the vehicle prototype (.
std::string unfold_msg
Message shown after successfully unfolding the item.
int moves = 0
Creature::moves it takes to unfold.
std::map< itype_id, int > tools_needed
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This iuse creates a new vehicle on the map.
Definition at line 213 of file iuse_actor.h.
Constructor & Destructor Documentation
unfold_vehicle_iuse()
unfold_vehicle_iuse::unfold_vehicle_iuse (const std::string & type = "unfold_vehicle") inline
Definition at line 225 of file iuse_actor.h.
: iuse_actor(type) {}
~unfold_vehicle_iuse()
unfold_vehicle_iuse::~unfold_vehicle_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > unfold_vehicle_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 620 of file iuse_actor.cpp.
{
    return std::make_unique<unfold_vehicle_iuse>( *this );
}
load()
void unfold_vehicle_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 625 of file iuse_actor.cpp.
{
    vehicle_id = vproto_id( obj.get_string( "vehicle_name" ) );
    obj.read( "unfold_msg", unfold_msg );
    obj.read( "moves", moves );
    obj.read( "tools_needed", tools_needed );
}
References JsonObject::get_string(), moves, JsonObject::read(), tools_needed, unfold_msg, and vehicle_id.
use()
int unfold_vehicle_iuse::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 633 of file iuse_actor.cpp.
{
    if( p.is_underwater() ) {
        p.add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    for( const auto &tool : tools_needed ) {
        // Amount == -1 means need one, but don't consume it.
        if( !p.has_amount( tool.first, 1 ) ) {
            p.add_msg_if_player( _( "You need %s to do it!" ),
                                 item::nname( tool.first ) );
            return 0;
        }
    }
    vehicle *veh = get_map().add_vehicle( vehicle_id, p.pos(), 0_degrees, 0, 0, false );
    if( veh == nullptr ) {
        p.add_msg_if_player( m_info, _( "There's no room to unfold the %s." ), it.tname() );
        return 0;
    }
    veh->set_owner( p );
    // Mark the vehicle as foldable.
    veh->tags.insert( "convertible" );
    // Store the id of the item the vehicle is made of.
    veh->tags.insert( std::string( "convertible:" ) + it.typeId().str() );
    if( !unfold_msg.empty() ) {
        p.add_msg_if_player( _( unfold_msg ), it.tname() );
    }
    p.moves -= moves;
    // Restore HP of parts if we stashed them previously.
    if( it.has_var( "folding_bicycle_parts" ) ) {
        // Brand new, no HP stored
        return 1;
    }
    std::istringstream veh_data;
    const auto data = it.get_var( "folding_bicycle_parts" );
    veh_data.str( data );
    if( !data.empty() && data[0] >= '0' && data[0] <= '9' ) {
        // starts with a digit -> old format
        for( const vpart_reference &vpr : veh->get_all_parts() ) {
            int tmp;
            veh_data >> tmp;
            veh->set_hp( vpr.part(), tmp );
        }
    } else {
        try {
            JsonIn json( veh_data );
            // Load parts into a temporary vector to not override
            // cached values (like precalc, passenger_id, ...)
            std::vector<vehicle_part> parts;
            json.read( parts );
            for( size_t i = 0; i < parts.size() && i < static_cast<size_t>( veh->part_count() ); i++ ) {
                const vehicle_part &src = parts[i];
                vehicle_part &dst = veh->part( i );
                // and now only copy values, that are
                // expected to be consistent.
                veh->set_hp( dst, src.hp() );
                dst.blood = src.blood;
                // door state/amount of fuel/direction of headlight
                dst.ammo_set( src.ammo_current(), src.ammo_remaining() );
                dst.flags = src.flags;
            }
        } catch( const JsonError &e ) {
            debugmsg( "Error restoring vehicle: %s", e.c_str() );
        }
    }
    return 1;
}
References _, player::add_msg_if_player(), map::add_vehicle(), vehicle_part::ammo_current(), vehicle_part::ammo_remaining(), vehicle_part::ammo_set(), vehicle_part::blood, JsonError::c_str(), debugmsg, vehicle_part::flags, vehicle::get_all_parts(), get_map(), item::get_var(), visitable< T >::has_amount(), item::has_var(), vehicle_part::hp(), Character::is_mounted(), Creature::is_underwater(), m_info, Creature::moves, moves, item::nname(), vehicle::part(), vehicle::part_count(), Character::pos(), JsonIn::read(), vehicle::set_hp(), vehicle::set_owner(), string_id< T >::str(), vehicle::tags, item::tname(), tool, tools_needed, item::typeId(), unfold_msg, and vehicle_id.
Member Data Documentation
moves
int unfold_vehicle_iuse::moves = 0
Creature::moves it takes to unfold.
Definition at line 222 of file iuse_actor.h.
Referenced by load(), and use().
tools_needed
std::map<itype_id, int> unfold_vehicle_iuse::tools_needed
Definition at line 223 of file iuse_actor.h.
Referenced by load(), and use().
unfold_msg
std::string unfold_vehicle_iuse::unfold_msg
Message shown after successfully unfolding the item.
Definition at line 220 of file iuse_actor.h.
Referenced by load(), and use().
vehicle_id
vproto_id unfold_vehicle_iuse::vehicle_id
Id of the vehicle prototype (.
See also
map::add_vehicle what it expects) that will be created when unfolding the item.
Definition at line 218 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp