Cataclysm BN: bionic_install_surgeon_preset Class Reference
bionic_install_surgeon_preset Class Reference
Public Member Functions
bionic_install_surgeon_preset (player &pl, player &patient)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Protected Attributes
player & p
player & pa
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Private Member Functions
std::string get_operation_duration (const item_location &loc)
std::string get_failure_chance (const item_location &loc)
std::string get_money_amount (const item_location &loc)
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Detailed Description
Definition at line 1886 of file game_inventory.cpp.
Constructor & Destructor Documentation
bionic_install_surgeon_preset()
bionic_install_surgeon_preset::bionic_install_surgeon_preset (player & pl, player & patient) inline
Definition at line 1889 of file game_inventory.cpp.
                                                                     :
            p( pl ), pa( patient ) {
            append_cell( [this]( const item_location & loc ) {
                return get_failure_chance( loc );
            }, _( "FAILURE CHANCE" ) );
            append_cell( [this]( const item_location & loc ) {
                return get_operation_duration( loc );
            }, _( "OPERATION DURATION" ) );
            append_cell( [this]( const item_location & loc ) {
                return get_money_amount( loc );
            }, _( "PRICE" ) );
        }
References _, inventory_selector_preset::append_cell(), get_failure_chance(), get_money_amount(), and get_operation_duration().
Member Function Documentation
get_denial()
std::string bionic_install_surgeon_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 1908 of file game_inventory.cpp.
{
            const item *it = loc.get_item();
            const itype *itemtype = it->type;
            const bionic_id &bid = itemtype->bionic->id;
            if( it->has_fault( fault_bionic_nonsterile ) ) {
                return _( "CBM is not sterile." );
            } else if( pa.has_bionic( bid ) ) {
                return _( "CBM is already installed." );
            } else if( bid->upgraded_bionic &&
                       !pa.has_bionic( bid->upgraded_bionic ) &&
                       it->is_upgrade() ) {
                return _( "No base version installed." );
            } else if( std::any_of( bid->available_upgrades.begin(),
                                    bid->available_upgrades.end(),
                                    std::bind( &player::has_bionic, &pa,
                                               std::placeholders::_1 ) ) ) {
                return _( "Superior version installed." );
            } else if( pa.is_npc() && !bid->has_flag( flag_BIONIC_NPC_USABLE ) ) {
                return _( "CBM is not compatible with patient." );
            }
            return std::string();
        }
References _, bionic_data::available_upgrades, itype::bionic, fault_bionic_nonsterile, flag_BIONIC_NPC_USABLE, item_location::get_item(), Character::has_bionic(), item::has_fault(), bionic_data::has_flag(), player::is_npc(), item::is_upgrade(), pa, item::type, and bionic_data::upgraded_bionic.
get_failure_chance()
std::string bionic_install_surgeon_preset::get_failure_chance (const item_location & loc) inline private
Definition at line 1946 of file game_inventory.cpp.
{
            const int difficulty = loc.get_item()->type->bionic->difficulty;
            int chance_of_failure = 100;
            player &installer = p;
            // Override player's skills with surgeon skill
            const int adjusted_skill = installer.bionics_adjusted_skill( skill_firstaid,
                                       skill_computer,
                                       skill_electronics,
                                       20 );
            if( g->u.has_trait( trait_DEBUG_BIONICS ) ) {
                chance_of_failure = 0;
            } else {
                chance_of_failure = 100 - bionic_manip_cos( adjusted_skill, difficulty );
            }
            return string_format( _( "%i%%" ), chance_of_failure );
        }
References _, itype::bionic, bionic_manip_cos(), Character::bionics_adjusted_skill(), g, item_location::get_item(), p, skill_computer, skill_electronics, skill_firstaid, string_format(), trait_DEBUG_BIONICS, and item::type.
Referenced by bionic_install_surgeon_preset().
get_money_amount()
std::string bionic_install_surgeon_preset::get_money_amount (const item_location & loc) inline private
Definition at line 1967 of file game_inventory.cpp.
{
            return format_money( loc.get_item()->price( true ) * 2 );
        }
References format_money(), item_location::get_item(), and item::price().
Referenced by bionic_install_surgeon_preset().
get_operation_duration()
std::string bionic_install_surgeon_preset::get_operation_duration (const item_location & loc) inline private
Definition at line 1939 of file game_inventory.cpp.
{
            const int difficulty = loc.get_item()->type->bionic->difficulty;
            // 20 minutes per bionic difficulty.
            return to_string( time_duration::from_minutes( difficulty * 20 ) );
        }
References itype::bionic, time_duration::from_minutes(), item_location::get_item(), to_string(), and item::type.
Referenced by bionic_install_surgeon_preset().
is_shown()
bool bionic_install_surgeon_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 1904 of file game_inventory.cpp.
{
            return loc->is_bionic();
        }
References item::is_bionic().
Member Data Documentation
p
player& bionic_install_surgeon_preset::p protected
Definition at line 1934 of file game_inventory.cpp.
Referenced by get_failure_chance().
pa
player& bionic_install_surgeon_preset::pa protected
Definition at line 1935 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp