Cataclysm BN: JsonError Class Reference
JsonError Class Reference
#include <json.h>
Public Member Functions
JsonError (const std::string &msg)
const char * c_str () const noexcept
Detailed Description
Definition at line 51 of file json.h.
Constructor & Destructor Documentation
JsonError()
JsonError::JsonError (const std::string & msg)
Definition at line 2125 of file json.cpp.
    : std::runtime_error( msg )
{
}
Member Function Documentation
c_str()
const char * JsonError::c_str () const inline noexcept
Definition at line 55 of file json.h.
{
            return what();
        }
Referenced by iuse::camera(), einkpc_download_memory_card(), vehicle::fold_up(), inventory::json_load_invcache(), vehicle::restore(), game::serialize_master(), show_photo_selection(), debug_menu::anonymous_namespace{wisheffect.cpp}::try_read_time_string(), game::unserialize(), game::unserialize_master(), and unfold_vehicle_iuse::use().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp