Cataclysm BN: body_part_set Class Reference
body_part_set Class Reference
#include <bodypart.h>
Public Member Functions
body_part_set ()=default
body_part_set (std::initializer_list< body_part > bps)
body_part_set & operator|= (const body_part_set &rhs)
body_part_set & operator&= (const body_part_set &rhs)
body_part_set operator| (const body_part_set &rhs) const
body_part_set operator& (const body_part_set &rhs) const
body_part_set operator~ () const
bool test (const body_part &bp) const
void set (const body_part &bp)
void reset (const body_part &bp)
bool any () const
bool none () const
size_t count () const
template<typename Stream >
void serialize (Stream &s) const
template<typename Stream >
void deserialize (Stream &s)
Static Public Member Functions
static body_part_set all ()
Private Member Functions
body_part_set (const std::bitset< num_bp > &other)
Private Attributes
std::bitset< num_bp > parts
Detailed Description
Definition at line 198 of file bodypart.h.
Constructor & Destructor Documentation
body_part_set() [1/3]
body_part_set::body_part_set (const std::bitset< num_bp > & other) inline explicit private
Definition at line 203 of file bodypart.h.
: parts(other) { }
body_part_set() [2/3]
body_part_set::body_part_set () default
Referenced by operator&(), operator|(), and operator~().
body_part_set() [3/3]
body_part_set::body_part_set (std::initializer_list< body_part > bps) inline
Definition at line 207 of file bodypart.h.
{
            for( const auto &bp : bps ) {
                set( bp );
            }
        }
References set().
Member Function Documentation
all()
static body_part_set body_part_set::all () inline static
Definition at line 233 of file bodypart.h.
{
            return ~body_part_set();
        }
Referenced by Character::exclusive_flag_coverage().
any()
bool body_part_set::any () const inline
Definition at line 246 of file bodypart.h.
{
            return parts.any();
        }
References parts.
Referenced by item::armor_info(), player_morale::on_worn_item_washed(), and player_morale::set_worn().
count()
size_t body_part_set::count () const inline
Definition at line 252 of file bodypart.h.
{
            return parts.count();
        }
References parts.
Referenced by Character::armor_absorb().
deserialize()
template<typename Stream > void body_part_set::deserialize (Stream & s) inline
Definition at line 261 of file bodypart.h.
{
            s.read( parts );
        }
References parts.
none()
bool body_part_set::none () const inline
Definition at line 249 of file bodypart.h.
{
            return parts.none();
        }
References parts.
Referenced by Character::covered_with_flag().
operator&()
body_part_set body_part_set::operator& (const body_part_set & rhs) const inline
Definition at line 225 of file bodypart.h.
{
            return body_part_set( parts & rhs.parts );
        }
References body_part_set(), and parts.
operator&=()
body_part_set & body_part_set::operator&= (const body_part_set & rhs) inline
Definition at line 217 of file bodypart.h.
{
            parts &= rhs.parts;
            return *this;
        }
References parts.
operator|()
body_part_set body_part_set::operator| (const body_part_set & rhs) const inline
Definition at line 222 of file bodypart.h.
{
            return body_part_set( parts | rhs.parts );
        }
References body_part_set(), and parts.
operator|=()
body_part_set & body_part_set::operator|= (const body_part_set & rhs) inline
Definition at line 213 of file bodypart.h.
{
            parts |= rhs.parts;
            return *this;
        }
References parts.
operator~()
body_part_set body_part_set::operator~ () const inline
Definition at line 229 of file bodypart.h.
{
            return body_part_set( ~parts );
        }
References body_part_set(), and parts.
reset()
void body_part_set::reset (const body_part & bp) inline
Definition at line 243 of file bodypart.h.
{
            parts.reset( bp );
        }
References parts.
Referenced by item::get_covered_body_parts().
serialize()
template<typename Stream > void body_part_set::serialize (Stream & s) const inline
Definition at line 257 of file bodypart.h.
{
            s.write( parts );
        }
References parts.
set()
void body_part_set::set (const body_part & bp) inline
Definition at line 240 of file bodypart.h.
{
            parts.set( bp );
        }
References parts.
Referenced by assign_coverage_from_json(), body_part_set(), and item::get_covered_body_parts().
test()
bool body_part_set::test (const body_part & bp) const inline
Definition at line 237 of file bodypart.h.
{
            return parts.test( bp );
        }
References parts.
Referenced by npc::adjust_worn(), apply_mut_encumbrance(), Character::bodypart_exposure(), Character::can_swap(), Character::can_wear(), item::covers(), Character::drench(), layer_item(), Character::mutation_attacks(), item::on_wear(), player_morale::on_worn_item_washed(), player_morale::set_worn(), Character::update_bodytemp(), and weather_effect::wet_player().
Member Data Documentation
parts
std::bitset<num_bp> body_part_set::parts private
Definition at line 201 of file bodypart.h.
Referenced by any(), count(), deserialize(), none(), operator&(), operator&=(), operator|(), operator|=(), operator~(), reset(), serialize(), set(), and test().
The documentation for this class was generated from the following file:
src/bodypart.h