Cataclysm BN: jmapgen_nested Class Reference
jmapgen_nested Class Reference
Calls another mapgen call inside the current one.
Classes
class neighborhood_check
Public Member Functions
jmapgen_nested (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, point p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
weighted_int_list< std::string > entries
weighted_int_list< std::string > else_entries
neighborhood_check neighbors
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Calls another mapgen call inside the current one.
Note: can't use regular overmap ids.
Parameters
entries list of pairs [nested mapgen id, weight].
Definition at line 1794 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_nested()
jmapgen_nested::jmapgen_nested (const JsonObject & jsi) inline
Definition at line 1854 of file mapgen.cpp.
                                                : neighbors( jsi.get_object( "neighbors" ) ) {
            load_weighted_entries( jsi, "chunks", entries );
            load_weighted_entries( jsi, "else_chunks", else_entries );
        }
References else_entries, entries, mapgen_defer::jsi, and load_weighted_entries().
Member Function Documentation
apply()
void jmapgen_nested::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1858 of file mapgen.cpp.
{
            const std::string *res = neighbors.test( dat ) ? entries.pick() : else_entries.pick();
            if( res == nullptr || res->empty() || *res == "null" ) {
                // This will be common when neighbors.test(...) is false, since else_entires is often empty.
                return;
            }
            const auto iter = nested_mapgen.find( *res );
            if( iter == nested_mapgen.end() ) {
                debugmsg( "Unknown nested mapgen function id %s", res->c_str() );
                return;
            }
            // A second roll? Let's allow it for now
            const auto &ptr = iter->second.pick();
            if( ptr == nullptr ) {
                return;
            }
            ( *ptr )->nest( dat, point( x.get(), y.get() ) );
        }
References debugmsg, else_entries, entries, jmapgen_int::get(), neighbors, nested_mapgen, ptr(), and jmapgen_nested::neighborhood_check::test().
has_vehicle_collision()
bool jmapgen_nested::has_vehicle_collision (mapgendata & dat, point p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1879 of file mapgen.cpp.
{
            const weighted_int_list<std::string> &selected_entries = neighbors.test(
                        dat ) ? entries : else_entries;
            if( selected_entries.empty() ) {
                return false;
            }
            for( auto &entry : selected_entries ) {
                if( entry.obj == "null" ) {
                    continue;
                }
                const auto iter = nested_mapgen.find( entry.obj );
                if( iter == nested_mapgen.end() ) {
                    return false;
                }
                for( const auto &nest : iter->second ) {
                    if( nest.obj->has_vehicle_collision( dat, p ) ) {
                        return true;
                    }
                }
            }
            return false;
        }
References else_entries, weighted_list< W, T >::empty(), entries, neighbors, nested_mapgen, and jmapgen_nested::neighborhood_check::test().
Member Data Documentation
else_entries
weighted_int_list<std::string> jmapgen_nested::else_entries
Definition at line 1852 of file mapgen.cpp.
Referenced by apply(), has_vehicle_collision(), and jmapgen_nested().
entries
weighted_int_list<std::string> jmapgen_nested::entries
Definition at line 1851 of file mapgen.cpp.
Referenced by apply(), has_vehicle_collision(), and jmapgen_nested().
neighbors
neighborhood_check jmapgen_nested::neighbors
Definition at line 1853 of file mapgen.cpp.
Referenced by apply(), and has_vehicle_collision().
The documentation for this class was generated from the following file:
src/mapgen.cpp