Cataclysm BN: jmapgen_monster_group Class Reference
jmapgen_monster_group Class Reference
Place spawn points for a monster group (actual monster spawning is done later).
Public Member Functions
jmapgen_monster_group (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
mongroup_id id
float density
jmapgen_int chance
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place spawn points for a monster group (actual monster spawning is done later).
"monster": id of the monster group. "chance": see density: see map::place_spawns
Definition at line 1207 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_monster_group()
jmapgen_monster_group::jmapgen_monster_group (const JsonObject & jsi) inline
Definition at line 1213 of file mapgen.cpp.
                                                       :
            id( jsi.get_string( "monster" ) )
            , density( jsi.get_float( "density", -1.0f ) )
            , chance( jsi, "chance", 1, 1 ) {
            if( !id.is_valid() ) {
                set_mapgen_defer( jsi, "monster", "no such monster group" );
            }
        }
References mapgen_defer::jsi, and set_mapgen_defer().
Member Function Documentation
apply()
void jmapgen_monster_group::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1221 of file mapgen.cpp.
{
            dat.m.place_spawns( id, chance.get(), point( x.val, y.val ), point( x.valmax, y.valmax ),
                                density == -1.0f ? dat.monster_density() : density );
        }
References chance, density, jmapgen_int::get(), mapgendata::m, mapgendata::monster_density(), map::place_spawns(), jmapgen_int::val, and jmapgen_int::valmax.
Member Data Documentation
chance
jmapgen_int jmapgen_monster_group::chance
Definition at line 1212 of file mapgen.cpp.
Referenced by apply().
density
float jmapgen_monster_group::density
Definition at line 1211 of file mapgen.cpp.
Referenced by apply().
id
mongroup_id jmapgen_monster_group::id
Definition at line 1210 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp