Cataclysm BN: detail::local_translation_cache< const char * > Class Reference
detail::local_translation_cache< const char * > Class Reference
#include <translations.h>
Public Member Functions
const char * operator() (const char *arg)
Private Attributes
std::string cached_arg
int cached_lang_version = INVALID_LANGUAGE_VERSION
bool same_as_arg
const char * cached_translation
Detailed Description
Definition at line 80 of file translations.h.
Member Function Documentation
operator()()
const char * detail::local_translation_cache< const char * >::operator() (const char * arg) inline
Definition at line 88 of file translations.h.
{
            if( cached_lang_version != get_current_language_version() || cached_arg != arg ) {
                cached_lang_version = get_current_language_version();
                cached_translation = _translate_internal( arg );
                same_as_arg = cached_translation == arg;
                cached_arg = arg;
            }
            // mimic gettext() behavior: return `arg` if no translation is found
            // `same_as_arg` is needed to ensure that the current `arg` is returned (not a cached one)
            return same_as_arg ? arg : cached_translation;
        }
References detail::_translate_internal(), arg(), and detail::get_current_language_version().
Member Data Documentation
cached_arg
std::string detail::local_translation_cache< const char * >::cached_arg private
Definition at line 83 of file translations.h.
cached_lang_version
int detail::local_translation_cache< const char * >::cached_lang_version = INVALID_LANGUAGE_VERSION private
Definition at line 84 of file translations.h.
cached_translation
const char* detail::local_translation_cache< const char * >::cached_translation private
Definition at line 86 of file translations.h.
same_as_arg
bool detail::local_translation_cache< const char * >::same_as_arg private
Definition at line 85 of file translations.h.
The documentation for this class was generated from the following file:
src/translations.h