Cataclysm BN: bonus_container Class Reference
bonus_container Class Reference
#include <bonuses.h>
Public Member Functions
bonus_container ()
void load (const JsonObject &jo)
float get_flat (const Character &u, affected_stat stat, damage_type dt) const
float get_flat (const Character &u, affected_stat stat) const
float get_mult (const Character &u, affected_stat stat, damage_type dt) const
float get_mult (const Character &u, affected_stat stat) const
std::string get_description () const
Private Types
using bonus_map = std::map< affected_type, std::vector< effect_scaling > >
Private Member Functions
void load (const JsonArray &jarr, bool mult)
Private Attributes
bonus_map bonuses_flat
All kinds of bonuses by types to damage, hit etc.
bonus_map bonuses_mult
Detailed Description
Definition at line 69 of file bonuses.h.
Member Typedef Documentation
bonus_map
using bonus_container::bonus_map = std::map<affected_type, std::vector<effect_scaling> > private
Definition at line 86 of file bonuses.h.
Constructor & Destructor Documentation
bonus_container()
bonus_container::bonus_container () default
Member Function Documentation
get_description()
std::string bonus_container::get_description () const
Definition at line 202 of file bonuses.cpp.
{
    std::string dump;
    for( const auto &boni : bonuses_mult ) {
        std::string type = string_from_affected_stat( boni.first.get_stat() );
        if( needs_damage_type( boni.first.get_stat() ) ) {
            //~ %1$s: damage type, %2$s: damage-related bonus name
            type = string_format( pgettext( "type of damage", "%1$s %2$s" ),
                                  name_by_dt( boni.first.get_damage_type() ), type );
        }
        for( const auto &sf : boni.second ) {
            if( sf.stat ) {
                //~ %1$s: bonus name, %2$d: bonus percentage, %3$s: stat name
                dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$d%%</stat> of %3$s" ),
                                       type, static_cast<int>( sf.scale * 100 ), string_from_scaling_stat( sf.stat ) );
            } else {
                //~ %1$s: bonus name, %2$d: bonus percentage
                dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$d%%</stat>" ),
                                       type, static_cast<int>( sf.scale * 100 ) );
            }
            dump += "\n";
        }
    }
    for( const auto &boni : bonuses_flat ) {
        std::string type = string_from_affected_stat( boni.first.get_stat() );
        if( needs_damage_type( boni.first.get_stat() ) ) {
            //~ %1$s: damage type, %2$s: damage-related bonus name
            type = string_format( pgettext( "type of damage", "%1$s %2$s" ),
                                  name_by_dt( boni.first.get_damage_type() ), type );
        }
        for( const auto &sf : boni.second ) {
            if( sf.stat ) {
                //~ %1$s: bonus name, %2$+d: bonus percentage, %3$s: stat name
                dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$+d%%</stat> of %3$s" ),
                                       type, static_cast<int>( sf.scale * 100 ), string_from_scaling_stat( sf.stat ) );
            } else {
                //~ %1$s: bonus name, %2$+d: bonus value
                dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$+d</stat>" ),
                                       type, static_cast<int>( sf.scale ) );
            }
            dump += "\n";
        }
    }
    return dump;
}
References bonuses_flat, bonuses_mult, name_by_dt(), needs_damage_type(), pgettext(), string_format(), string_from_affected_stat(), string_from_scaling_stat(), and type.
Referenced by ma_technique::get_description(), and ma_buff::get_description().
get_flat() [1/2]
float bonus_container::get_flat (const Character & u, affected_stat stat) const
Definition at line 176 of file bonuses.cpp.
{
    return get_flat( u, stat, DT_NULL );
}
References DT_NULL, and get_flat().
get_flat() [2/2]
float bonus_container::get_flat (const Character & u, affected_stat stat, damage_type dt) const
Definition at line 161 of file bonuses.cpp.
{
    const affected_type type( stat, dt );
    const auto &iter = bonuses_flat.find( type );
    if( iter == bonuses_flat.end() ) {
        return 0.0f;
    }
    float ret = 0.0f;
    for( const auto &es : iter->second ) {
        ret += es.get( u );
    }
    return ret;
}
References bonuses_flat, cata::hash64_detail::ret, and type.
Referenced by ma_buff::armor_bonus(), ma_technique::armor_penetration(), ma_buff::arpen_bonus(), ma_buff::block_bonus(), ma_buff::damage_bonus(), ma_technique::damage_bonus(), ma_buff::dodge_bonus(), get_flat(), ma_buff::hit_bonus(), ma_technique::move_cost_penalty(), and ma_buff::speed_bonus().
get_mult() [1/2]
float bonus_container::get_mult (const Character & u, affected_stat stat) const
Definition at line 197 of file bonuses.cpp.
{
    return get_mult( u, stat, DT_NULL );
}
References DT_NULL, and get_mult().
get_mult() [2/2]
float bonus_container::get_mult (const Character & u, affected_stat stat, damage_type dt) const
Definition at line 181 of file bonuses.cpp.
{
    const affected_type type( stat, dt );
    const auto &iter = bonuses_mult.find( type );
    if( iter == bonuses_mult.end() ) {
        return 1.0f;
    }
    float ret = 1.0f;
    for( const auto &es : iter->second ) {
        ret *= es.get( u );
    }
    // Currently all relevant effects require non-negative values
    return std::max( 0.0f, ret );
}
References bonuses_mult, cata::hash64_detail::ret, and type.
Referenced by ma_buff::damage_mult(), ma_technique::damage_multiplier(), get_mult(), and ma_technique::move_cost_multiplier().
load() [1/2]
void bonus_container::load (const JsonArray & jarr, bool mult) private
Definition at line 113 of file bonuses.cpp.
{
    for( const JsonObject &qualifiers : jarr ) {
        const affected_stat as = affected_stat_from_string( qualifiers.get_string( "stat" ) );
        if( as == affected_stat::NONE ) {
            qualifiers.throw_error( "Invalid affected stat", "stat" );
        }
        damage_type dt = DT_NULL;
        if( needs_damage_type( as ) ) {
            dt = dt_by_name( qualifiers.get_string( "type" ) );
            if( dt == DT_NULL ) {
                qualifiers.throw_error( "Invalid damage type", "type" );
            }
        }
        const affected_type at( as, dt );
        auto &selected = mult ? bonuses_mult : bonuses_flat;
        selected[at].emplace_back( qualifiers );
    }
}
References affected_stat_from_string(), bonuses_flat, bonuses_mult, dt_by_name(), DT_NULL, needs_damage_type(), and NONE.
load() [2/2]
void bonus_container::load (const JsonObject & jo)
Definition at line 107 of file bonuses.cpp.
{
    load( jo.get_array( "flat_bonuses" ), false );
    load( jo.get_array( "mult_bonuses" ), true );
}
References JsonObject::get_array(), and load().
Referenced by load(), ma_technique::load(), and ma_buff::load().
Member Data Documentation
bonuses_flat
bonus_map bonus_container::bonuses_flat private
All kinds of bonuses by types to damage, hit etc.
Definition at line 88 of file bonuses.h.
Referenced by get_description(), get_flat(), and load().
bonuses_mult
bonus_map bonus_container::bonuses_mult private
Definition at line 89 of file bonuses.h.
Referenced by get_description(), get_mult(), and load().
The documentation for this class was generated from the following files:
src/bonuses.h
src/bonuses.cpp