Cataclysm BN: addiction Class Reference
addiction Class Reference
#include <pldata.h>
Public Member Functions
addiction ()=default
addiction (add_type const t, const int i=1)
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Public Attributes
add_type type = add_type::NONE
int intensity = 0
time_duration sated = 1_hours
Detailed Description
Definition at line 47 of file pldata.h.
Constructor & Destructor Documentation
addiction() [1/2]
addiction::addiction () default
addiction() [2/2]
addiction::addiction (add_type const t, const int i = 1) inline
Definition at line 55 of file pldata.h.
: type {t}, intensity {i} { }
Member Function Documentation
deserialize()
void addiction::deserialize (JsonIn & jsin)
Definition at line 3410 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    type = static_cast<add_type>( jo.get_int( "type_enum" ) );
    intensity = jo.get_int( "intensity" );
    jo.read( "sated", sated );
}
References JsonObject::allow_omitted_members(), JsonObject::get_int(), JsonIn::get_object(), JsonObject::read(), and type.
serialize()
void addiction::serialize (JsonOut & json) const
Definition at line 3401 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "type_enum", type );
    json.member( "intensity", intensity );
    json.member( "sated", sated );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and type.
Member Data Documentation
intensity
int addiction::intensity = 0
Definition at line 51 of file pldata.h.
sated
time_duration addiction::sated = 1_hours
Definition at line 52 of file pldata.h.
type
add_type addiction::type = add_type::NONE
Definition at line 50 of file pldata.h.
Referenced by addiction_name(), addiction_text(), and addiction_reader::erase_next().
The documentation for this class was generated from the following files:
src/pldata.h
src/savegame_json.cpp