Cataclysm BN: sokoban_game Class Reference
sokoban_game Class Reference
#include <iuse_software_sokoban.h>
Classes
class cUndo
Public Member Functions
int start_game ()
sokoban_game ()
Private Member Functions
void parse_level (std::istream &fin)
bool check_win ()
int get_wall_connection (const point &)
void draw_level (const catacurses::window &w_sokoban)
void print_score (const catacurses::window &w_sokoban, int iScore, int iMoves)
Private Attributes
int iCurrentLevel = 0
int iNumLevel = 0
int iTotalMoves = 0
std::map< int, std::map< int, std::string > > mLevel
std::map< int, std::map< std::string, size_t > > mLevelInfo
std::vector< std::map< int, std::map< int, std::string > > > vLevel
std::vector< cUndo > vUndo
std::vector< std::vector< std::pair< int, int > > > vLevelDone
std::map< int, bool > mAlreadyWon
Detailed Description
Definition at line 19 of file iuse_software_sokoban.h.
Constructor & Destructor Documentation
sokoban_game()
sokoban_game::sokoban_game () default
Member Function Documentation
check_win()
bool sokoban_game::check_win () private
Definition at line 203 of file iuse_software_sokoban.cpp.
{
    for( auto &elem : vLevelDone[iCurrentLevel] ) {
        if( mLevel[elem.first][elem.second] != "*" ) {
            return false;
        }
    }
    return true;
}
References iCurrentLevel, mLevel, and vLevelDone.
Referenced by start_game().
draw_level()
void sokoban_game::draw_level (const catacurses::window & w_sokoban) private
Definition at line 164 of file iuse_software_sokoban.cpp.
{
    const point iOffset( ( FULL_SCREEN_WIDTH - 2 - mLevelInfo[iCurrentLevel]["MaxLevelX"] ) / 2,
                         ( FULL_SCREEN_HEIGHT - 2 - mLevelInfo[iCurrentLevel]["MaxLevelY"] ) / 2 );
    for( auto &elem : mLevel ) {
        for( std::map<int, std::string>::iterator iterX = elem.second.begin();
             iterX != elem.second.end(); ++iterX ) {
            std::string sTile = iterX->second;
            if( sTile == "#" ) {
                mvwputch( w_sokoban, iOffset + point( iterX->first, elem.first ),
                          c_white, get_wall_connection( point( iterX->first, elem.first ) ) );
            } else {
                nc_color cCol = c_white;
                if( sTile == "." || sTile == "*" ||  sTile == "+" ) {
                    cCol = red_background( c_white );
                }
                if( sTile == "." ) {
                    sTile = " ";
                }
                if( sTile == "*" ) {
                    sTile = "$";
                }
                if( sTile == "+" ) {
                    sTile = "@";
                }
                mvwprintz( w_sokoban, iOffset + point( iterX->first, elem.first ), cCol, sTile );
            }
        }
    }
}
References c_white, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_wall_connection(), iCurrentLevel, mLevel, mLevelInfo, mvwprintz(), mvwputch(), and red_background().
Referenced by start_game().
get_wall_connection()
int sokoban_game::get_wall_connection (const point & i) private
Definition at line 104 of file iuse_software_sokoban.cpp.
{
    bool bTop = false;
    bool bRight = false;
    bool bBottom = false;
    bool bLeft = false;
    if( mLevel[i.y - 1][i.x] == "#" ) {
        bTop = true;
    }
    if( mLevel[i.y][i.x + 1] == "#" ) {
        bRight = true;
    }
    if( mLevel[i.y + 1][i.x] == "#" ) {
        bBottom = true;
    }
    if( mLevel[i.y][i.x - 1] == "#" ) {
        bLeft = true;
    }
    if( !bRight && !bLeft ) {
        return LINE_XOXO; //
    } else if( !bTop && !bBottom ) {
        return LINE_OXOX;
    } else if( bTop && bRight && !bBottom && !bLeft ) {
        return LINE_XXOO;
    } else if( !bTop && bRight && bBottom && !bLeft ) {
        return LINE_OXXO;
    } else if( !bTop && !bRight && bBottom && bLeft ) {
        return LINE_OOXX;
    } else if( bTop && !bRight && !bBottom && bLeft ) {
        return LINE_XOOX;
    } else if( bTop && bRight && bBottom && !bLeft ) {
        return LINE_XXXO;
    } else if( bTop && bRight && !bBottom && bLeft ) {
        return LINE_XXOX;
    } else if( bTop && !bRight && bBottom && bLeft ) {
        return LINE_XOXX;
    } else if( !bTop && bRight && bBottom && bLeft ) {
        return LINE_OXXX;
    } else if( bTop && bRight && bBottom && bLeft ) {
        return LINE_XXXX;
    }
    return '#';
}
References LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_OXXX, LINE_XOOX, LINE_XOXO, LINE_XOXX, LINE_XXOO, LINE_XXOX, LINE_XXXO, LINE_XXXX, mLevel, point::x, and point::y.
Referenced by draw_level().
parse_level()
void sokoban_game::parse_level (std::istream & fin) private
Definition at line 36 of file iuse_software_sokoban.cpp.
{
    /*
    # Wall
    $ Package
    space Floor
    . Goal
    * Package on Goal
    @ Sokoban
    + Sokoban on Goal
    */
    iCurrentLevel = 0;
    iNumLevel = 0;
    vLevel.clear();
    vUndo.clear();
    vLevelDone.clear();
    std::string sLine;
    while( !fin.eof() ) {
        safe_getline( fin, sLine );
        if( sLine.substr( 0, 3 ) == "; #" ) {
            iNumLevel++;
            continue;
        } else if( sLine[0] == ';' ) {
            continue;
        }
        if( sLine.empty() ) {
            //Find level start
            vLevel.resize( iNumLevel + 1 );
            vLevelDone.resize( iNumLevel + 1 );
            mLevelInfo[iNumLevel]["MaxLevelY"] = 0;
            mLevelInfo[iNumLevel]["MaxLevelX"] = 0;
            mLevelInfo[iNumLevel]["PlayerY"] = 0;
            mLevelInfo[iNumLevel]["PlayerX"] = 0;
            continue;
        }
        if( mLevelInfo[iNumLevel]["MaxLevelX"] < sLine.length() ) {
            mLevelInfo[iNumLevel]["MaxLevelX"] = sLine.length();
        }
        for( size_t i = 0; i < sLine.length(); i++ ) {
            if( sLine[i] == '@' ) {
                if( mLevelInfo[iNumLevel]["PlayerY"] == 0 && mLevelInfo[iNumLevel]["PlayerX"] == 0 ) {
                    mLevelInfo[iNumLevel]["PlayerY"] = mLevelInfo[iNumLevel]["MaxLevelY"];
                    mLevelInfo[iNumLevel]["PlayerX"] = i;
                } else {
                    // TODO: describe why it's invalid
                    throw std::runtime_error( "invalid content of sokoban file" );
                }
            }
            if( sLine[i] == '.' || sLine[i] == '*' || sLine[i] == '+' ) {
                vLevelDone[iNumLevel].push_back( std::make_pair( static_cast<int>
                                                 ( mLevelInfo[iNumLevel]["MaxLevelY"] ), static_cast<int>( i ) ) );
            }
            vLevel[iNumLevel][mLevelInfo[iNumLevel]["MaxLevelY"]][i] = sLine[i];
        }
        mLevelInfo[iNumLevel]["MaxLevelY"]++;
    }
}
References iCurrentLevel, iNumLevel, mLevelInfo, safe_getline(), vLevel, vLevelDone, and vUndo.
Referenced by start_game().
print_score()
void sokoban_game::print_score (const catacurses::window & w_sokoban, int iScore, int iMoves) private
Definition at line 23 of file iuse_software_sokoban.cpp.
{
    mvwprintz( w_sokoban, point( 3, 1 ), c_white, _( "Level: %d/%d" ), iCurrentLevel + 1, iNumLevel );
    wprintw( w_sokoban, "    " );
    mvwprintz( w_sokoban, point( 3, 2 ), c_white, _( "Score: %d" ), iScore );
    mvwprintz( w_sokoban, point( 3, 3 ), c_white, _( "Moves: %d" ), iMoves );
    wprintw( w_sokoban, "    " );
    mvwprintz( w_sokoban, point( 3, 4 ), c_white, _( "Total moves: %d" ), iTotalMoves );
}
References _, c_white, iCurrentLevel, iNumLevel, iTotalMoves, mvwprintz(), and catacurses::wprintw().
Referenced by start_game().
start_game()
int sokoban_game::start_game ()
Definition at line 213 of file iuse_software_sokoban.cpp.
{
    int iScore = 0;
    int iMoves = 0;
    iTotalMoves = 0;
    point dir;
    using namespace std::placeholders;
    read_from_file( PATH_INFO::sokoban(), std::bind( &sokoban_game::parse_level, this, _1 ) );
    catacurses::window w_sokoban;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ) {
        const point iOffset( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                             TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 );
        w_sokoban = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                        iOffset );
        ui.position_from_window( w_sokoban );
    } );
    ui.mark_resize();
    input_context ctxt( "SOKOBAN" );
    ctxt.register_cardinal();
    ctxt.register_action( "NEXT" );
    ctxt.register_action( "PREV" );
    ctxt.register_action( "RESET" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "UNDO" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_sokoban );
        draw_border( w_sokoban, BORDER_COLOR, _( "Sokoban" ), hilite( c_white ) );
        std::vector<std::string> shortcuts;
        shortcuts.push_back( _( "<+> next" ) ); // '+': next
        shortcuts.push_back( _( "<-> prev" ) ); // '-': prev
        shortcuts.push_back( _( "<r>eset" ) ); // 'r': reset
        shortcuts.push_back( _( "<q>uit" ) );  // 'q': quit
        shortcuts.push_back( _( "<u>ndo move" ) ); // 'u': undo move
        int indent = 10;
        for( auto &shortcut : shortcuts ) {
            indent = std::max( indent, utf8_width( shortcut ) + 1 );
        }
        indent = std::min( indent, 30 );
        for( size_t i = 0; i < shortcuts.size(); i++ ) {
            shortcut_print( w_sokoban, point( FULL_SCREEN_WIDTH - indent, i + 1 ),
                            c_white, c_light_green, shortcuts[i] );
        }
        print_score( w_sokoban, iScore, iMoves );
        draw_level( w_sokoban );
        wnoutrefresh( w_sokoban );
    } );
    point pl;
    bool bNewLevel = true;
    bool bMoved = false;
    do {
        if( bNewLevel ) {
            bNewLevel = false;
            iMoves = 0;
            vUndo.clear();
            pl.y = mLevelInfo[iCurrentLevel]["PlayerY"];
            pl.x = mLevelInfo[iCurrentLevel]["PlayerX"];
            mLevel = vLevel[iCurrentLevel];
        }
        std::string action;
        if( check_win() ) {
            //we won yay
            if( !mAlreadyWon[iCurrentLevel] ) {
                iScore += 500;
                mAlreadyWon[iCurrentLevel] = true;
            }
            action = "NEXT";
        } else {
            ui_manager::redraw();
            //Check input
            action = ctxt.handle_input();
        }
        bMoved = false;
        if( const cata::optional<tripoint> vec = ctxt.get_direction( action ) ) {
            dir = vec->xy();
            bMoved = true;
        } else if( action == "QUIT" ) {
            return iScore;
        } else if( action == "UNDO" ) {
            point pl_new;
            bool bUndoSkip = false;
            //undo move
            if( !vUndo.empty() ) {
                //reset last player pos
                mLevel[pl.y][pl.x] = mLevel[pl.y][pl.x] == "+" ? "." : " ";
                pl_new = vUndo[vUndo.size() - 1].old;
                mLevel[pl_new.y][pl_new.x] = vUndo[vUndo.size() - 1].sTileOld;
                vUndo.pop_back();
                bUndoSkip = true;
            }
            if( bUndoSkip && !vUndo.empty() ) {
                dir = vUndo[vUndo.size() - 1].old;
                if( vUndo[vUndo.size() - 1].sTileOld == "$" ||
                    vUndo[vUndo.size() - 1].sTileOld == "*" ) {
                    mLevel[pl.y][pl.x] = mLevel[pl.y][pl.x] == "." ? "*" : "$";
                    point np = pl + dir;
                    mLevel[np.y][np.x] = mLevel[np.y][np.x] == "*" ?
                                         "." : " ";
                    vUndo.pop_back();
                }
            }
            if( bUndoSkip ) {
                pl = pl_new;
            }
        } else if( action == "RESET" ) {
            //reset level
            bNewLevel = true;
        } else if( action == "NEXT" ) {
            //next level
            iCurrentLevel++;
            if( iCurrentLevel >= iNumLevel ) {
                iCurrentLevel = 0;
            }
            bNewLevel = true;
        } else if( action == "PREV" ) {
            //previous level
            iCurrentLevel--;
            if( iCurrentLevel < 0 ) {
                iCurrentLevel = iNumLevel - 1;
            }
            bNewLevel = true;
        }
        if( bMoved ) {
            //check if we can move the player
            std::string sMoveTo = mLevel[pl.y + dir.y][pl.x + dir.x];
            bool bMovePlayer = false;
            if( sMoveTo != "#" ) {
                if( sMoveTo == "$" || sMoveTo == "*" ) {
                    //Check if we can move the package
                    point p_pack = pl + dir * 2;
                    std::string sMovePackTo = mLevel[p_pack.y][p_pack.x];
                    if( sMovePackTo == "." || sMovePackTo == " " ) {
                        //move both
                        bMovePlayer = true;
                        mLevel[p_pack.y][p_pack.x] = sMovePackTo == "." ? "*" : "$";
                        vUndo.push_back( cUndo( dir, sMoveTo ) );
                        iMoves--;
                    }
                } else {
                    bMovePlayer = true;
                }
                if( bMovePlayer ) {
                    //move player
                    vUndo.push_back( cUndo( pl, mLevel[pl.y][pl.x] ) );
                    mLevel[pl.y][pl.x] = mLevel[pl.y][pl.x] == "+" ? "." : " ";
                    mLevel[pl.y + dir.y][pl.x + dir.x] = sMoveTo == "." || sMoveTo == "*" ? "+" : "@";
                    pl += dir;
                    iMoves++;
                    iTotalMoves++;
                }
            }
        }
    } while( true );
    return iScore;
}
References _, action, BORDER_COLOR, c_light_green, c_white, check_win(), draw_border(), draw_level(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::get_direction(), input_context::handle_input(), hilite(), iCurrentLevel, iNumLevel, iTotalMoves, mAlreadyWon, mLevel, mLevelInfo, catacurses::newwin(), parse_level(), print_score(), read_from_file(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), shortcut_print(), PATH_INFO::sokoban(), TERMX, TERMY, utf8_width(), vLevel, vUndo, catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by play_videogame().
Member Data Documentation
iCurrentLevel
int sokoban_game::iCurrentLevel = 0 private
Definition at line 38 of file iuse_software_sokoban.h.
Referenced by check_win(), draw_level(), parse_level(), print_score(), and start_game().
iNumLevel
int sokoban_game::iNumLevel = 0 private
Definition at line 39 of file iuse_software_sokoban.h.
Referenced by parse_level(), print_score(), and start_game().
iTotalMoves
int sokoban_game::iTotalMoves = 0 private
Definition at line 40 of file iuse_software_sokoban.h.
Referenced by print_score(), and start_game().
mAlreadyWon
std::map<int, bool> sokoban_game::mAlreadyWon private
Definition at line 46 of file iuse_software_sokoban.h.
Referenced by start_game().
mLevel
std::map<int, std::map<int, std::string> > sokoban_game::mLevel private
Definition at line 41 of file iuse_software_sokoban.h.
Referenced by check_win(), draw_level(), get_wall_connection(), and start_game().
mLevelInfo
std::map<int, std::map<std::string, size_t> > sokoban_game::mLevelInfo private
Definition at line 42 of file iuse_software_sokoban.h.
Referenced by draw_level(), parse_level(), and start_game().
vLevel
std::vector<std::map<int, std::map<int, std::string> > > sokoban_game::vLevel private
Definition at line 43 of file iuse_software_sokoban.h.
Referenced by parse_level(), and start_game().
vLevelDone
std::vector<std::vector<std::pair<int, int> > > sokoban_game::vLevelDone private
Definition at line 45 of file iuse_software_sokoban.h.
Referenced by check_win(), and parse_level().
vUndo
std::vector<cUndo> sokoban_game::vUndo private
Definition at line 44 of file iuse_software_sokoban.h.
Referenced by parse_level(), and start_game().
The documentation for this class was generated from the following files:
src/iuse_software_sokoban.h
src/iuse_software_sokoban.cpp