Cataclysm BN: game::debug_hour_timer Class Reference
game::debug_hour_timer Class Reference
Public Types
using IRLTimeMs = std::chrono::time_point< std::chrono::system_clock, std::chrono::milliseconds >
Public Member Functions
void toggle ()
void print_time ()
Private Attributes
bool enabled = false
cata::optional< IRLTimeMs > start_time = cata::nullopt
Detailed Description
Definition at line 929 of file game.h.
Member Typedef Documentation
IRLTimeMs
using game::debug_hour_timer::IRLTimeMs = std::chrono::time_point<std::chrono::system_clock, std::chrono::milliseconds>
Definition at line 932 of file game.h.
Member Function Documentation
print_time()
void game::debug_hour_timer::print_time ()
Definition at line 11165 of file game.cpp.
{
    if( enabled ) {
        if( calendar::once_every( time_duration::from_hours( 1 ) ) ) {
            const IRLTimeMs now = std::chrono::time_point_cast<std::chrono::milliseconds>(
                                      std::chrono::system_clock::now() );
            if( start_time ) {
                add_msg( "in-game hour took: %d ms", ( now - *start_time ).count() );
            } else {
                add_msg( "starting debug timer" );
            }
            start_time = now;
        }
    }
}
References add_msg(), detail::count(), enabled, time_duration::from_hours(), and calendar::once_every().
Referenced by game::do_turn().
toggle()
void game::debug_hour_timer::toggle ()
Definition at line 11158 of file game.cpp.
{
    enabled = !enabled;
    start_time = cata::nullopt;
    add_msg( string_format( "debug timer %s", enabled ? "enabled" : "disabled" ) );
}
References add_msg(), enabled, cata::nullopt, and string_format().
Referenced by game::toggle_debug_hour_timer().
Member Data Documentation
enabled
bool game::debug_hour_timer::enabled = false private
Definition at line 936 of file game.h.
start_time
cata::optional<IRLTimeMs> game::debug_hour_timer::start_time = cata::nullopt private
Definition at line 937 of file game.h.
The documentation for this class was generated from the following files:
src/game.h
src/game.cpp