Cataclysm BN: wish_item_callback Class Reference
wish_item_callback Class Reference
Public Member Functions
wish_item_callback (const std::vector< const itype * > &ids)
void select (uilist *menu) override
After a new item is selected, call this once.
bool key (const input_context &, const input_event &event, int, uilist *) override
void refresh (uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual ~uilist_callback ()=default
Public Attributes
bool incontainer
bool has_flag
bool spawn_everything
std::string msg
std::string flag
const std::vector< const itype * > & standard_itype_ids
Detailed Description
Definition at line 575 of file wish.cpp.
Constructor & Destructor Documentation
wish_item_callback()
wish_item_callback::wish_item_callback (const std::vector< const itype * > & ids) inline
Definition at line 584 of file wish.cpp.
                                                                  :
            incontainer( false ), has_flag( false ), spawn_everything( false ), standard_itype_ids( ids ) {
        }
Member Function Documentation
key()
bool wish_item_callback::key (const input_context & , const input_event & event, int , uilist *) inline override virtual
Reimplemented from uilist_callback.
Definition at line 595 of file wish.cpp.
{
            if( event.get_first_input() == 'f' ) {
                incontainer = !incontainer;
                return true;
            }
            if( event.get_first_input() == 'F' ) {
                flag = string_input_popup()
                       .title( _( "Add which flag?  Use UPPERCASE letters without quotes" ) )
                       .query_string();
                if( !flag.empty() ) {
                    has_flag = true;
                }
                return true;
            }
            if( event.get_first_input() == 'E' ) {
                spawn_everything = !spawn_everything;
                return true;
            }
            return false;
        }
References _, flag, input_event::get_first_input(), has_flag, incontainer, string_input_popup::query_string(), spawn_everything, and string_input_popup::title().
refresh()
void wish_item_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 617 of file wish.cpp.
{
            const int starty = 3;
            const int startx = menu->w_width - menu->pad_right;
            const std::string padding( menu->pad_right, ' ' );
            for( int y = 2; y < menu->w_height - 1; y++ ) {
                mvwprintw( menu->window, point( startx - 1, y ), padding );
            }
            mvwhline( menu->window, point( startx, 1 ), ' ', menu->pad_right - 1 );
            const int entnum = menu->selected;
            if( entnum >= 0 && static_cast<size_t>( entnum ) < standard_itype_ids.size() ) {
                item tmp( standard_itype_ids[entnum], calendar::turn );
                const std::string header = string_format( "#%d: %s%s%s", entnum,
                                           standard_itype_ids[entnum]->get_id().c_str(),
                                           incontainer ? _( " (contained)" ) : "",
                                           has_flag ? _( " (flagged)" ) : "" );
                mvwprintz( menu->window, point( startx + ( menu->pad_right - 1 - utf8_width( header ) ) / 2, 1 ),
                           c_cyan, header );
                std::vector<iteminfo> info = tmp.info();
                std::string info_string = format_item_info( info, {} );
                fold_and_print( menu->window, point( startx, starty ), menu->pad_right - 1, c_light_gray,
                                info_string );
            }
            if( spawn_everything ) {
                mvwprintz( menu->window, point( startx, menu->w_height - 4 ), c_green,
                           _( "Select any item to spawn everything (ignores filters)." ) );
            }
            mvwprintz( menu->window, point( startx, menu->w_height - 3 ), c_green, msg );
            msg.erase();
            input_context ctxt( menu->input_category );
            mvwprintw( menu->window, point( startx, menu->w_height - 2 ),
                       _( "[%s] find, [f] container, [F] flag, [E] everything, [%s] quit" ),
                       ctxt.get_desc( "FILTER" ), ctxt.get_desc( "QUIT" ) );
            wnoutrefresh( menu->window );
        }
References _, c_cyan, c_green, c_light_gray, fold_and_print(), format_item_info(), input_context::get_desc(), std::this_thread::get_id(), has_flag, incontainer, item::info(), uilist::input_category, msg, catacurses::mvwhline(), catacurses::mvwprintw(), mvwprintz(), uilist::pad_right, uilist::selected, spawn_everything, standard_itype_ids, string_format(), calendar::turn, utf8_width(), uilist::w_height, uilist::w_width, uilist::window, and catacurses::wnoutrefresh().
select()
void wish_item_callback::select (uilist *) inline override virtual
After a new item is selected, call this once.
Reimplemented from uilist_callback.
Definition at line 588 of file wish.cpp.
{
            if( menu->selected < 0 ) {
                return;
            }
            incontainer = standard_itype_ids[menu->selected]->phase == phase_id::LIQUID;
        }
References incontainer, LIQUID, uilist::selected, and standard_itype_ids.
Member Data Documentation
flag
std::string wish_item_callback::flag
Definition at line 582 of file wish.cpp.
Referenced by key(), and debug_menu::wishitem().
has_flag
bool wish_item_callback::has_flag
Definition at line 579 of file wish.cpp.
Referenced by key(), refresh(), and debug_menu::wishitem().
incontainer
bool wish_item_callback::incontainer
Definition at line 578 of file wish.cpp.
Referenced by key(), refresh(), select(), and debug_menu::wishitem().
msg
std::string wish_item_callback::msg
Definition at line 581 of file wish.cpp.
Referenced by refresh(), and debug_menu::wishitem().
spawn_everything
bool wish_item_callback::spawn_everything
Definition at line 580 of file wish.cpp.
Referenced by key(), refresh(), and debug_menu::wishitem().
standard_itype_ids
const std::vector<const itype *>& wish_item_callback::standard_itype_ids
Definition at line 583 of file wish.cpp.
Referenced by refresh(), and select().
The documentation for this class was generated from the following file:
src/wish.cpp