Cataclysm BN: options_manager::PageItem Class Reference
options_manager::PageItem Class Reference
Single page item (entry).
Public Member Functions
PageItem ()
PageItem (ItemType type, const std::string &data, const std::string &group)
std::string fmt_tooltip (const Group &group, const options_container &cont) const
Public Attributes
ItemType type
std::string data
std::string group
Empty if not assigned to any group.
Detailed Description
Single page item (entry).
Definition at line 294 of file options.h.
Constructor & Destructor Documentation
PageItem() [1/2]
options_manager::PageItem::PageItem () inline
Definition at line 302 of file options.h.
: type(ItemType::BlankLine) { }
PageItem() [2/2]
options_manager::PageItem::PageItem (ItemType type, const std::string & data, const std::string & group) inline
Definition at line 303 of file options.h.
                    : type( type ), data( data ), group( group ) { }
Member Function Documentation
fmt_tooltip()
std::string options_manager::PageItem::fmt_tooltip (const Group & group, const options_container & cont) const
Definition at line 2702 of file options.cpp.
{
    switch( type ) {
        case ItemType::BlankLine:
            return "";
        case ItemType::GroupHeader: {
            return group.tooltip_.translated();
        }
        case ItemType::Option: {
            const std::string &opt_name = data;
            const cOpt &opt = cont.find( opt_name )->second;
            std::string ret = string_format( "%s #%s",
                                             opt.getTooltip(),
                                             opt.getDefaultText() );
#if defined(TILES) || defined(_WIN32)
            if( opt_name == "TERMINAL_X" ) {
                int new_window_width = 0;
                new_window_width = projected_window_width();
                ret += " -- ";
                ret += string_format(
                           vgettext( "The window will be %d pixel wide with the selected value.",
                                     "The window will be %d pixels wide with the selected value.",
                                     new_window_width ), new_window_width );
            } else if( opt_name == "TERMINAL_Y" ) {
                int new_window_height = 0;
                new_window_height = projected_window_height();
                ret += " -- ";
                ret += string_format(
                           vgettext( "The window will be %d pixel tall with the selected value.",
                                     "The window will be %d pixels tall with the selected value.",
                                     new_window_height ), new_window_height );
            }
#endif
            return ret;
        }
        default:
            abort();
    }
}
References abort, options_manager::BlankLine, options_manager::cOpt::getDefaultText(), options_manager::cOpt::getTooltip(), options_manager::GroupHeader, options_manager::Option, cata::hash64_detail::ret, string_format(), type, and vgettext().
Referenced by options_manager::show().
Member Data Documentation
data
std::string options_manager::PageItem::data
Definition at line 298 of file options.h.
Referenced by options_manager::addOptionToPage(), options_manager::serialize(), and options_manager::show().
group
std::string options_manager::PageItem::group
Empty if not assigned to any group.
Definition at line 300 of file options.h.
Referenced by options_manager::show().
type
ItemType options_manager::PageItem::type
Definition at line 297 of file options.h.
Referenced by options_manager::addOptionToPage(), options_manager::serialize(), and options_manager::show().
The documentation for this class was generated from the following files:
src/options.h
src/options.cpp