Cataclysm BN: ups_based_armor_actor Class Reference
ups_based_armor_actor Class Reference
Items that can be worn and can be activated to consume energy from UPS.
#include <iuse_actor.h>
Public Member Functions
ups_based_armor_actor (const std::string &type="ups_based_armor")
~ups_based_armor_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string activate_msg
Shown when activated.
std::string deactive_msg
Shown when deactivated.
std::string out_of_power_msg
Shown when it runs out of power.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Items that can be worn and can be activated to consume energy from UPS.
Note that the energy consumption is done in player::process_active_items, it is not done by this class!
Definition at line 394 of file iuse_actor.h.
Constructor & Destructor Documentation
ups_based_armor_actor()
ups_based_armor_actor::ups_based_armor_actor (const std::string & type = "ups_based_armor") inline
Definition at line 404 of file iuse_actor.h.
: iuse_actor(type) {}
~ups_based_armor_actor()
ups_based_armor_actor::~ups_based_armor_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > ups_based_armor_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 984 of file iuse_actor.cpp.
{
    return std::make_unique<ups_based_armor_actor>( *this );
}
load()
void ups_based_armor_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1029 of file iuse_actor.cpp.
{
    obj.read( "activate_msg", activate_msg );
    obj.read( "deactive_msg", deactive_msg );
    obj.read( "out_of_power_msg", out_of_power_msg );
}
References activate_msg, deactive_msg, out_of_power_msg, and JsonObject::read().
use()
int ups_based_armor_actor::use (player & p, item & it, bool t, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 1044 of file iuse_actor.cpp.
{
    if( t ) {
        // Normal, continuous usage, do nothing. The item is *not* charge-based.
        return 0;
    }
    if( p.get_item_position( &it ) >= -1 ) {
        p.add_msg_if_player( m_info, _( "You should wear the %s before activating it." ),
                             it.tname() );
        return 0;
    }
    if( !it.active && !has_powersource( it, p ) ) {
        p.add_msg_if_player( m_info,
                             _( "You need some source of power for your %s (a simple UPS will do)." ), it.tname() );
        if( it.is_power_armor() ) {
            p.add_msg_if_player( m_info,
                                 _( "There is also a certain bionic that helps with this kind of armor." ) );
        }
        return 0;
    }
    it.active = !it.active;
    p.reset_encumbrance();
    if( it.active ) {
        if( activate_msg.empty() ) {
            p.add_msg_if_player( m_info, _( "You activate your %s." ), it.tname() );
        } else {
            p.add_msg_if_player( m_info, _( activate_msg ), it.tname() );
        }
    } else {
        if( deactive_msg.empty() ) {
            p.add_msg_if_player( m_info, _( "You deactivate your %s." ), it.tname() );
        } else {
            p.add_msg_if_player( m_info, _( deactive_msg ), it.tname() );
        }
    }
    return 0;
}
References _, activate_msg, item::active, player::add_msg_if_player(), deactive_msg, Character::get_item_position(), has_powersource(), item::is_power_armor(), m_info, Character::reset_encumbrance(), and item::tname().
Member Data Documentation
activate_msg
std::string ups_based_armor_actor::activate_msg
Shown when activated.
Definition at line 398 of file iuse_actor.h.
Referenced by load(), and use().
deactive_msg
std::string ups_based_armor_actor::deactive_msg
Shown when deactivated.
Definition at line 400 of file iuse_actor.h.
Referenced by load(), and use().
out_of_power_msg
std::string ups_based_armor_actor::out_of_power_msg
Shown when it runs out of power.
Definition at line 402 of file iuse_actor.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp