Cataclysm BN: weather_generator Class Reference
weather_generator Class Reference
#include <weather_gen.h>
Public Member Functions
weather_generator ()
const weather_type_id & get_bad_weather () const
const weather_type_id & get_default_weather () const
int forecast_priority (const weather_type_id &w) const
w_point get_weather (const tripoint &, const time_point &, unsigned seed) const
TODO: Remove the regular tripoint overload, replace with *_abs_ms one.
w_point get_weather (const tripoint_abs_ms &location, const time_point &t, const calendar_config &calendar_config, unsigned seed) const
const weather_type_id & get_weather_conditions (const tripoint &, const time_point &, unsigned seed) const
const weather_type_id & get_weather_conditions (const w_point &) const
int get_wind_direction (season_type) const
int convert_winddir (int) const
void test_weather (unsigned) const
units::temperature get_weather_temperature (const tripoint_abs_ms &, const time_point &, const calendar_config &calendar_config, unsigned) const
units::temperature get_water_temperature (const tripoint_abs_ms &, const time_point &, const calendar_config &calendar_config, unsigned) const
Static Public Member Functions
static weather_generator load (const JsonObject &jo)
Public Attributes
double base_humidity = 0
double base_pressure = 0
double base_acid = 0
double base_wind = 0
int base_wind_distrib_peaks = 0
std::array< season_modifier, 4 > season_stats
int base_wind_season_variation = 0
units::temperature temperature_daily_amplitude = 5_c
units::temperature temperature_noise_amplitude = 8_c
std::vector< weather_type_id > weather_types
Static Public Attributes
static int current_winddir = 1000
Detailed Description
Definition at line 30 of file weather_gen.h.
Constructor & Destructor Documentation
weather_generator()
weather_generator::weather_generator () default
Member Function Documentation
convert_winddir()
int weather_generator::convert_winddir (int inputdir) const
Definition at line 280 of file weather_gen.cpp.
{
    // Convert from discrete distribution output to angle
    float finputdir = inputdir * 22.5;
    return static_cast<int>( finputdir );
}
Referenced by get_weather().
forecast_priority()
int weather_generator::forecast_priority (const weather_type_id & w) const
Definition at line 196 of file weather_gen.cpp.
{
    auto it = std::find( weather_types.begin(), weather_types.end(), w );
    if( it == weather_types.end() ) {
        return -1;
    }
    return std::distance( weather_types.begin(), it );
}
References detail::find().
get_bad_weather()
const weather_type_id & weather_generator::get_bad_weather () const
Definition at line 185 of file weather_gen.cpp.
{
    const weather_type_id *bad_weather = &get_default_weather();
    for( const weather_type_id &wt : weather_types ) {
        if( wt->precip == precip_class::heavy ) {
            bad_weather = &wt;
        }
    }
    return *bad_weather;
}
References get_default_weather(), and heavy.
Referenced by Character::suffer_from_artifacts().
get_default_weather()
const weather_type_id & weather_generator::get_default_weather () const
Definition at line 180 of file weather_gen.cpp.
{
    return weather_types[0];
}
Referenced by get_bad_weather().
get_water_temperature()
units::temperature weather_generator::get_water_temperature (const tripoint_abs_ms & location, const time_point & time, const calendar_config & calendar_config, unsigned seed) const
Definition at line 287 of file weather_gen.cpp.
{
    // Instead of using a realistic model, we'll just smooth out air temperature
    // Smooth out both in time and intensity
    // And add caps - it must stay liquid water
    constexpr std::array<std::pair<time_duration, double>, 7> measurement_weights = {{
            { 7_days, 0.1 },
            { 7_days + 12_hours, 0.1 },
            { 3_days, 0.2 },
            { 3_days + 12_hours, 0.2 },
            { 1_days, 0.2 },
            { 0_days + 12_hours, 0.2 },
            { 0_days, 0.1 }
        }
    };
    const units::temperature weighted_avg = std::accumulate( measurement_weights.begin(),
                                            measurement_weights.end(),
                                            0_c,
                                            [this, location, time, seed, calendar_config]( units::temperature acc,
    const std::pair<time_duration, double> &pr ) {
        units::temperature weather_temperature =
            get_weather_temperature( location, time - pr.first, calendar_config, seed );
        return acc + multiply_any_unit( weather_temperature, pr.second );
    } );
    // Rescale the range:
    // For avg air temp<-10C, water is 0C
    // For avg air temp> 30C, water is 30C
    // logarithmic_range smoothing for the in-between
    constexpr int lower_limit = units::to_millidegree_celsius( -10_c );
    constexpr int upper_limit = units::to_millidegree_celsius( 30_c );
    const int weighted_average_celsius = units::to_millidegree_celsius( weighted_avg );
    const double t = logarithmic_range( lower_limit,
                                        upper_limit,
                                        weighted_average_celsius );
    return multiply_any_unit( 0_c, 1 - t ) + multiply_any_unit( 30_c, t );
}
References logarithmic_range(), units::multiply_any_unit(), iuse::seed(), and units::to_millidegree_celsius().
Referenced by weather_manager::update_weather().
get_weather() [1/2]
w_point weather_generator::get_weather (const tripoint & location, const time_point & t, unsigned seed) const
TODO: Remove the regular tripoint overload, replace with *_abs_ms one.
Definition at line 117 of file weather_gen.cpp.
{
    return get_weather( tripoint_abs_ms( location ), t, calendar::config, seed );
}
References calendar::config, get_weather(), and iuse::seed().
Referenced by weather_manager::get_temperature(), get_weather(), get_weather_conditions(), test_weather(), and weather_manager::update_weather().
get_weather() [2/2]
w_point weather_generator::get_weather (const tripoint_abs_ms & location, const time_point & t, const calendar_config & calendar_config, unsigned seed) const
Definition at line 123 of file weather_gen.cpp.
{
    const weather_gen_common common = get_common_data( location.xy(), t, calendar_config, seed );
    const double x( common.x );
    const double y( common.y );
    const double z( common.z );
    const unsigned modSEED = common.modSEED;
    // +1 in midwinter, -1 in midsummer
    const double cgyf = common.cosine_of_gregorian_year_fraction;
    const season_type season = common.season;
    // Noise factors
    const units::temperature T( weather_temperature_from_common_data( *this, common, t ) );
    double A( raw_noise_4d( x, y, z, modSEED ) * 8.0 );
    double W( raw_noise_4d( x / 2.5, y / 2.5, z / 200, modSEED ) * 10.0 );
    // Humidity variation
    double mod_h = season_stats[static_cast<size_t>( season )].humidity_mod;
    // Relative humidity, a percentage.
    double H = std::min( 100., std::max( 0.,
                                         base_humidity + mod_h + 100 * (
                                                 .15 * -cgyf +
                                                 raw_noise_4d( x, y, z, modSEED + 101 ) *
                                                 .2 * ( cgyf + 2 ) ) ) );
    // Pressure
    double P =
        base_pressure +
        raw_noise_4d( x, y, z, modSEED + 211 ) *
        10 * ( cgyf + 2 );
    // Wind power
    W = std::max( 0, static_cast<int>( base_wind * rng( 1, 2 ) / std::pow( ( P + W ) / 1014.78, rng( 9,
                                       base_wind_distrib_peaks ) ) +
                                       -cgyf / base_wind_season_variation * rng( 1, 2 ) ) );
    // Initial static variable
    if( current_winddir == 1000 ) {
        current_winddir = get_wind_direction( season );
        current_winddir = convert_winddir( current_winddir );
    } else {
        // When wind strength is low, wind direction is more variable
        bool changedir = one_in( W * 2160 );
        if( changedir ) {
            current_winddir = get_wind_direction( season );
            current_winddir = convert_winddir( current_winddir );
        }
    }
    std::string wind_desc = get_wind_desc( W );
    // Acid rains
    const double acid_content = base_acid * A;
    bool acid = acid_content >= 1.0;
    return w_point{ T, H, P, W, wind_desc, current_winddir, acid };
}
References mattack::acid(), base_acid, base_humidity, base_pressure, base_wind, base_wind_distrib_peaks, base_wind_season_variation, game_menus::inv::common(), convert_winddir(), current_winddir, get_common_data(), get_wind_desc(), get_wind_direction(), one_in(), raw_noise_4d(), rng(), season, season_stats, iuse::seed(), weather_temperature_from_common_data(), and coords::coord_point< Point, Origin, Scale >::xy().
get_weather_conditions() [1/2]
const weather_type_id & weather_generator::get_weather_conditions (const tripoint & location, const time_point & t, unsigned seed) const
Definition at line 205 of file weather_gen.cpp.
{
    w_point w( get_weather( location, t, seed ) );
    return get_weather_conditions( w );
}
References get_weather(), get_weather_conditions(), and iuse::seed().
Referenced by get_weather_conditions(), test_weather(), and weather_manager::update_weather().
get_weather_conditions() [2/2]
const weather_type_id & weather_generator::get_weather_conditions (const w_point & w) const
Definition at line 212 of file weather_gen.cpp.
{
    w_point wp2 = w;
    const weather_type_id *current_conditions = &weather_type_id::NULL_ID();
    for( const weather_type_id &type : weather_types ) {
        const weather_requirements &requires = type->requirements;
        weather_requirements rq2 = requires;
        bool test_pressure =
            requires.pressure_max > w.pressure &&
            requires.pressure_min < w.pressure;
        bool test_humidity =
            requires.humidity_max > w.humidity &&
            requires.humidity_min < w.humidity;
        if( ( requires.humidity_and_pressure && !( test_pressure && test_humidity ) ) ||
            ( !requires.humidity_and_pressure && !( test_pressure || test_humidity ) ) ) {
            continue;
        }
        bool test_temperature =
            requires.temperature_max > units::to_fahrenheit( w.temperature ) &&
            requires.temperature_min < units::to_fahrenheit( w.temperature );
        bool test_windspeed =
            requires.windpower_max > w.windpower &&
            requires.windpower_min < w.windpower;
        bool test_acidic = !requires.acidic || w.acidic;
        if( !( test_temperature && test_windspeed && test_acidic ) ) {
            continue;
        }
        if( !requires.required_weathers.empty() ) {
            if( std::find( requires.required_weathers.begin(), requires.required_weathers.end(),
                           *current_conditions ) == requires.required_weathers.end() ) {
                continue;
            }
        }
        if( requires.time != weather_time_requirement_type::both ) {
            bool day = is_day( calendar::turn );
            if( ( requires.time == weather_time_requirement_type::day && !day ) ||
                ( requires.time == weather_time_requirement_type::night && day ) ) {
                continue;
            }
        }
        current_conditions = &type;
    }
    return current_conditions->obj().id;
}
References w_point::acidic, both, day, detail::find(), w_point::humidity, weather_type::id, is_day(), night, string_id< weather_type >::NULL_ID(), w_point::pressure, weather_requirements::pressure_max, w_point::temperature, units::to_fahrenheit(), calendar::turn, type, and w_point::windpower.
get_weather_temperature()
units::temperature weather_generator::get_weather_temperature (const tripoint_abs_ms & location, const time_point & t, const calendar_config & calendar_config, unsigned seed) const
Definition at line 110 of file weather_gen.cpp.
{
    return weather_temperature_from_common_data( *this, get_common_data( location.xy(), t,
            calendar_config, seed ), t );
}
References get_common_data(), iuse::seed(), weather_temperature_from_common_data(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by item::process_rot().
get_wind_direction()
int weather_generator::get_wind_direction (season_type season) const
Definition at line 259 of file weather_gen.cpp.
{
    cata_default_random_engine &wind_dir_gen = rng_get_engine();
    // Assign chance to angle direction
    if( season == SPRING ) {
        std::discrete_distribution<int> distribution {3, 3, 5, 8, 11, 10, 5, 2, 5, 6, 6, 5, 8, 10, 8, 6};
        return distribution( wind_dir_gen );
    } else if( season == SUMMER ) {
        std::discrete_distribution<int> distribution {3, 4, 4, 8, 8, 9, 8, 3, 7, 8, 10, 7, 7, 7, 5, 3};
        return distribution( wind_dir_gen );
    } else if( season == AUTUMN ) {
        std::discrete_distribution<int> distribution {4, 6, 6, 7, 6, 5, 4, 3, 5, 6, 8, 8, 10, 10, 8, 5};
        return distribution( wind_dir_gen );
    } else if( season == WINTER ) {
        std::discrete_distribution<int> distribution {5, 3, 2, 3, 2, 2, 2, 2, 4, 6, 10, 8, 12, 19, 13, 9};
        return distribution( wind_dir_gen );
    } else {
        return 0;
    }
}
References AUTUMN, rng_get_engine(), season, SPRING, SUMMER, and WINTER.
Referenced by get_weather().
load()
weather_generator weather_generator::load (const JsonObject & jo) static
Definition at line 378 of file weather_gen.cpp.
{
    static const std::array<std::pair<std::string, int>, NUM_SEASONS> legacy_temp_id_values = {{
            {"spring_temp_manual_mod", 0},
            {"summer_temp_manual_mod", 10},
            {"autumn_temp_manual_mod", 0},
            {"winter_temp_manual_mod", -15},
        }
    };
    static const std::array<std::string, NUM_SEASONS> season_temp_ids = {
        "spring_temp", "summer_temp", "autumn_temp", "winter_temp"
    };
    static const std::array<std::string, NUM_SEASONS> season_humidity_ids = {
        "spring_humidity_manual_mod",
        "summer_humidity_manual_mod",
        "autumn_humidity_manual_mod",
        "winter_humidity_manual_mod"
    };
    weather_generator ret;
    float base_temp = jo.get_float( "base_temperature", 0.0 );
    // Handling legacy temperature settings
    // Don't handle legacy settings in strict mode, let it error
    if( !json_report_strict ) {
        for( size_t i = 0; i < season_temp_ids.size(); i++ ) {
            ret.season_stats[i].average_temperature = units::from_celsius(
                        base_temp +
                        jo.get_int( legacy_temp_id_values[i].first, 0 ) +
                        legacy_temp_id_values[i].second
                    );
        }
    }
    // Reading temperature settings
    for( size_t i = 0; i < season_temp_ids.size(); i++ ) {
        maybe_temperature_reader( jo, season_temp_ids[i],
                                  ret.season_stats[i].average_temperature, false );
        assign( jo, season_humidity_ids[i], ret.season_stats[i].humidity_mod );
    }
    // Reading other weather settings.
    ret.base_humidity = jo.get_float( "base_humidity", 50.0 );
    ret.base_pressure = jo.get_float( "base_pressure", 0.0 );
    ret.base_acid = jo.get_float( "base_acid", 0.0 );
    ret.base_wind = jo.get_float( "base_wind", 0.0 );
    ret.base_wind_distrib_peaks = jo.get_int( "base_wind_distrib_peaks", 0 );
    ret.base_wind_season_variation = jo.get_int( "base_wind_season_variation", 0 );
    assign( jo, "temperature_daily_amplitude", ret.temperature_daily_amplitude );
    assign( jo, "temperature_noise_amplitude", ret.temperature_noise_amplitude );
    jo.get_member( "weather_types" ); // Throw if does not exist
    jo.read( "weather_types", ret.weather_types );
    if( ret.weather_types.empty() ) {
        jo.throw_error( "expected at least 1 weather type", "weather_types" );
    }
    return ret;
}
References assign(), units::from_celsius(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_member(), json_report_strict, maybe_temperature_reader(), NUM_SEASONS, JsonObject::read(), cata::hash64_detail::ret, and JsonObject::throw_error().
Referenced by load_region_settings().
test_weather()
void weather_generator::test_weather (unsigned seed = 1000) const
Definition at line 328 of file weather_gen.cpp.
{
    // Outputs a Cata year's worth of weather data to a CSV file.
    // Usage:
    // weather_generator WEATHERGEN; // Instantiate the class.
    // WEATHERGEN.test_weather(); // Runs this test.
    write_to_file( "weather.output", [&]( std::ostream & testfile ) {
        testfile <<
                 "|;year;season;day;hour;minute;temperature(F);humidity(%);pressure(mB);weatherdesc;windspeed(mph);winddirection"
                 << std::endl;
        const time_point begin = calendar::turn;
        const time_point end = begin + 2 * calendar::year_length();
        for( time_point i = begin; i < end; i += 20_minutes ) {
            w_point w = get_weather( tripoint_zero, i, seed );
            const weather_type_id &conditions = get_weather_conditions( w );
            int year = to_turns<int>( i - calendar::turn_zero ) / to_turns<int>
                       ( calendar::year_length() ) + 1;
            const int hour = hour_of_day<int>( i );
            const int minute = minute_of_hour<int>( i );
            int day;
            if( calendar::eternal_season() ) {
                day = to_days<int>( time_past_new_year( i ) );
            } else {
                day = day_of_season<int>( i );
            }
            testfile << "|;" << year << ";" << season_of_year( i ) << ";" << day << ";" << hour << ";" << minute
                     << ";" << w.temperature << ";" << w.humidity << ";" << w.pressure << ";" << conditions->name << ";"
                     << w.windpower << ";" << w.winddirection << std::endl;
        }
    }, "weather test file" );
}
References day, calendar::eternal_season(), get_weather(), get_weather_conditions(), hour, w_point::humidity, minute, weather_type::name, w_point::pressure, season_of_year(), iuse::seed(), w_point::temperature, time_past_new_year(), tripoint_zero, calendar::turn, calendar::turn_zero, w_point::winddirection, w_point::windpower, write_to_file(), year, and calendar::year_length().
Referenced by debug_menu::debug().
Member Data Documentation
base_acid
double weather_generator::base_acid = 0
Definition at line 37 of file weather_gen.h.
Referenced by get_weather().
base_humidity
double weather_generator::base_humidity = 0
Definition at line 34 of file weather_gen.h.
Referenced by get_weather().
base_pressure
double weather_generator::base_pressure = 0
Definition at line 36 of file weather_gen.h.
Referenced by get_weather().
base_wind
double weather_generator::base_wind = 0
Definition at line 39 of file weather_gen.h.
Referenced by get_weather().
base_wind_distrib_peaks
int weather_generator::base_wind_distrib_peaks = 0
Definition at line 41 of file weather_gen.h.
Referenced by get_weather().
base_wind_season_variation
int weather_generator::base_wind_season_variation = 0
Definition at line 44 of file weather_gen.h.
Referenced by get_weather().
current_winddir
int weather_generator::current_winddir = 1000 static
Definition at line 52 of file weather_gen.h.
Referenced by get_weather().
season_stats
std::array<season_modifier, 4> weather_generator::season_stats
Definition at line 42 of file weather_gen.h.
Referenced by get_weather(), and season_temp().
temperature_daily_amplitude
units::temperature weather_generator::temperature_daily_amplitude = 5_c
Definition at line 47 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
temperature_noise_amplitude
units::temperature weather_generator::temperature_noise_amplitude = 8_c
Definition at line 49 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
weather_types
std::vector<weather_type_id> weather_generator::weather_types
Definition at line 53 of file weather_gen.h.
The documentation for this class was generated from the following files:
src/weather_gen.h
src/weather_gen.cpp