Cataclysm BN: inventory_column Class Reference
inventory_column Class Reference
#include <inventory_ui.h>
Classes
struct cell_t
struct entry_cell_cache_t
Public Member Functions
inventory_column (const inventory_selector_preset &preset=default_preset)
virtual ~inventory_column ()=default
bool empty () const
virtual bool activatable () const
Can this column be activated?
bool visible () const
Is this column visible?
virtual bool allows_selecting () const
Does this column allow selecting? "Cosmetic" columns (list of selected items) can explicitly prohibit selecting.
size_t page_index () const
size_t pages_count () const
bool has_available_choices () const
bool is_selected (const inventory_entry &entry) const
bool is_selected_by_category (const inventory_entry &entry) const
Does this entry belong to the selected category? When navigation_mode::ITEM is used it's equivalent to is_selected().
const inventory_entry & get_selected () const
std::vector< inventory_entry * > get_all_selected () const
std::vector< inventory_entry * > get_entries (const std::function< bool(const inventory_entry &entry)> &filter_func) const
inventory_entry * find_by_invlet (int invlet) const
void draw (const catacurses::window &win, point pos) const
void add_entry (const inventory_entry &entry)
void move_entries_to (inventory_column &dest)
void clear ()
void set_stack_favorite (const item_location &location, bool favorite)
bool select (const item_location &loc)
Selects the specified location.
void select (size_t new_index, scroll_direction dir)
Change the selection.
size_t get_selected_index ()
void set_multiselect (bool multiselect)
void set_visibility (bool visibility)
void set_width (size_t new_width, const std::vector< inventory_column * > &all_columns)
void set_height (size_t new_height)
size_t get_width () const
size_t get_height () const
void expand_to_fit (const inventory_entry &entry)
Expands the column to fit the new entry.
virtual void reset_width (const std::vector< inventory_column * > &all_columns)
Resets width to original (unchanged).
int reassign_custom_invlets (const player &p, int min_invlet, int max_invlet)
Returns next custom inventory letter.
virtual void prepare_paging (const std::string &filter="")
Reorder entries, repopulate titles, adjust to the new height.
virtual void on_input (const inventory_input &input)
Event handlers.
virtual void on_change (const inventory_entry &)
The entry has been changed.
virtual void on_activate ()
The column has been activated.
virtual void on_deactivate ()
The column has been deactivated.
virtual void on_mode_change (navigation_mode mode)
Selection mode has been changed.
void set_filter (const std::string &filter)
Protected Member Functions
void move_selection (scroll_direction dir)
Move the selection.
void move_selection_page (scroll_direction dir)
size_t next_selectable_index (size_t index, scroll_direction dir) const
size_t page_of (size_t index) const
size_t page_of (const inventory_entry &entry) const
size_t get_entry_indent (const inventory_entry &entry) const
Indentation of the entry.
size_t get_entry_cell_width (size_t index, size_t cell_index) const
Overall cell width.
size_t get_entry_cell_width (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_width () const
Sum of the cell widths.
entry_cell_cache_t make_entry_cell_cache (const inventory_entry &entry) const
const entry_cell_cache_t & get_entry_cell_cache (size_t index) const
Protected Attributes
const inventory_selector_preset & preset
std::vector< inventory_entry > entries
std::vector< inventory_entry > entries_unfiltered
navigation_mode mode = navigation_mode::ITEM
bool active = false
bool multiselect = false
bool paging_is_valid = false
bool visibility = true
size_t selected_index = 0
size_t page_offset = 0
size_t entries_per_page = std::numeric_limits<size_t>::max()
size_t height = std::numeric_limits<size_t>::max()
size_t reserved_width = 0
Private Member Functions
size_t visible_cells () const
Private Attributes
std::vector< cell_t > cells
std::vector< entry_cell_cache_t > entries_cell_cache
Detailed Description
Definition at line 219 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_column()
inventory_column::inventory_column (const inventory_selector_preset & preset = default_preset) inline
Definition at line 222 of file inventory_ui.h.
                                                                                     : preset( preset ) {
            cells.resize( preset.get_cells_count() );
        }
References cells, inventory_selector_preset::get_cells_count(), and preset.
~inventory_column()
virtual inventory_column::~inventory_column () virtual default
Member Function Documentation
activatable()
bool inventory_column::activatable () const virtual
Can this column be activated?
Returns
Whether the column contains selectable entries. Note: independent from 'allows_selecting'
Reimplemented in selection_column.
Definition at line 202 of file inventory_ui.cpp.
{
    return std::any_of( entries.begin(), entries.end(), []( const inventory_entry & e ) {
        return e.is_selectable();
    } );
}
References entries.
Referenced by selection_column::activatable().
add_entry()
void inventory_column::add_entry (const inventory_entry & entry)
Definition at line 707 of file inventory_ui.cpp.
{
    if( std::find( entries.begin(), entries.end(), entry ) != entries.end() ) {
        debugmsg( "Tried to add a duplicate entry." );
        return;
    }
    const auto iter = std::find_if( entries.rbegin(), entries.rend(),
    [ &entry ]( const inventory_entry & cur ) {
        const item_category *cur_cat = cur.get_category_ptr();
        const item_category *new_cat = entry.get_category_ptr();
        return cur_cat == new_cat || ( cur_cat != nullptr && new_cat != nullptr
                                       && ( *cur_cat == *new_cat || *cur_cat < *new_cat ) );
    } );
    entries.insert( iter.base(), entry );
    entries_cell_cache.clear();
    expand_to_fit( entry );
    paging_is_valid = false;
}
References debugmsg, and detail::find().
Referenced by inventory_selector::add_entry(), move_entries_to(), and selection_column::on_change().
allows_selecting()
virtual bool inventory_column::allows_selecting () const inline virtual
Does this column allow selecting? "Cosmetic" columns (list of selected items) can explicitly prohibit selecting.
Note: independent from 'activatable'
Reimplemented in selection_column.
Definition at line 246 of file inventory_ui.h.
{
            return true;
        }
clear()
void inventory_column::clear ()
Definition at line 813 of file inventory_ui.cpp.
{
    entries.clear();
    entries_cell_cache.clear();
    paging_is_valid = false;
}
Referenced by inventory_selector::clear_items().
draw()
void inventory_column::draw (const catacurses::window & win, point pos) const
Definition at line 859 of file inventory_ui.cpp.
{
    if( !visible() ) {
        return;
    }
    const auto available_cell_width = [ this ]( size_t index, size_t cell_index ) {
        const size_t displayed_width = cells[cell_index].current_width;
        const size_t real_width = get_entry_cell_width( index, cell_index );
        return displayed_width > real_width ? displayed_width - real_width : 0;
    };
    // Do the actual drawing
    for( size_t index = page_offset, line = 0; index < entries.size() &&
         line < entries_per_page; ++index, ++line ) {
        const auto &entry = entries[index];
        const auto &entry_cell_cache = get_entry_cell_cache( index );
        if( !entry ) {
            continue;
        }
        int x1 = pos.x + get_entry_indent( entry );
        int x2 = pos.x + std::max( static_cast<int>( reserved_width - get_cells_width() ), 0 );
        int yy = pos.y + line;
        const bool selected = active && is_selected( entry );
        if( selected && visible_cells() > 1 ) {
            for( int hx = x1, hx_max = pos.x + get_width(); hx < hx_max; ++hx ) {
                mvwputch( win, point( hx, yy ), h_white, ' ' );
            }
        }
        const std::string &denial = entry_cell_cache.denial;
        if( !denial.empty() ) {
            const size_t max_denial_width = std::max( static_cast<int>( get_width() - ( min_denial_gap +
                                            get_entry_cell_width( index, 0 ) ) ), 0 );
            const size_t denial_width = std::min( max_denial_width, static_cast<size_t>( utf8_width( denial,
                                                  true ) ) );
            trim_and_print( win, point( pos.x + get_width() - denial_width, yy ), denial_width, c_red, denial );
        }
        const size_t count = denial.empty() ? cells.size() : 1;
        for( size_t cell_index = 0; cell_index < count; ++cell_index ) {
            if( !cells[cell_index].visible() ) {
                continue; // Don't show empty cells
            }
            if( line != 0 && cell_index != 0 && entry.is_category() ) {
                break; // Don't show duplicated titles
            }
            x2 += cells[cell_index].current_width;
            size_t text_width = utf8_width( entry_cell_cache.text[cell_index], true );
            size_t text_gap = cell_index > 0 ? std::max( cells[cell_index].gap(), min_cell_gap ) : 0;
            size_t available_width = x2 - x1 - text_gap;
            if( text_width > available_width ) {
                // See if we can steal some of the needed width from an adjacent cell
                if( cell_index == 0 && count >= 2 ) {
                    available_width += available_cell_width( index, 1 );
                } else if( cell_index > 0 ) {
                    available_width += available_cell_width( index, cell_index - 1 );
                }
                text_width = std::min( text_width, available_width );
            }
            if( text_width > 0 ) {
                const int text_x = cell_index == 0 ? x1 : x2 -
                                   text_width; // Align either to the left or to the right
                const std::string &text = entry_cell_cache.text[cell_index];
                if( entry.is_item() && ( selected || !entry.is_selectable() ) ) {
                    trim_and_print( win, point( text_x, yy ), text_width, selected ? h_white : c_dark_gray,
                                    remove_color_tags( text ) );
                } else {
                    trim_and_print( win, point( text_x, yy ), text_width, entry_cell_cache.color, text );
                }
            }
            x1 = x2;
        }
        if( entry.is_item() ) {
            int xx = pos.x;
            if( entry.get_invlet() != '\0' ) {
                mvwputch( win, point( pos.x, yy ), entry.get_invlet_color(), entry.get_invlet() );
            }
            xx += 2;
            if( get_option<bool>( "ITEM_SYMBOLS" ) ) {
                const nc_color color = entry.any_item()->color();
                mvwputch( win, point( xx, yy ), color, entry.any_item()->symbol() );
                xx += 2;
            }
            if( allows_selecting() && activatable() && multiselect ) {
                if( entry.chosen_count == 0 ) {
                    mvwputch( win, point( xx, yy ), c_dark_gray, '-' );
                } else if( entry.chosen_count >= entry.get_available_count() ) {
                    mvwputch( win, point( xx, yy ), c_light_green, '+' );
                } else {
                    mvwputch( win, point( xx, yy ), c_light_green, '#' );
                }
            }
        }
    }
    if( pages_count() > 1 ) {
        mvwprintw( win, pos + point( 0, height - 1 ), _( "Page %d/%d" ), page_index() + 1, pages_count() );
    }
}
References _, active, c_dark_gray, c_light_green, c_red, inventory_selector_preset::cells, color(), detail::count(), h_white, line(), min_cell_gap, min_denial_gap, catacurses::mvwprintw(), mvwputch(), remove_color_tags(), trim_and_print(), utf8_width(), point::x, and point::y.
Referenced by inventory_selector::draw_columns().
empty()
bool inventory_column::empty () const inline
Definition at line 228 of file inventory_ui.h.
{
            return entries.empty();
        }
References entries.
Referenced by inventory_selector::rearrange_columns(), and visible().
expand_to_fit()
void inventory_column::expand_to_fit (const inventory_entry & entry)
Expands the column to fit the new entry.
Definition at line 531 of file inventory_ui.cpp.
{
    if( !entry ) {
        return;
    }
    // Don't use cell cache here since the entry may not yet be placed into the vector of entries.
    const std::string denial = preset.get_denial( entry );
    for( size_t i = 0, num = denial.empty() ? cells.size() : 1; i < num; ++i ) {
        auto &cell = cells[i];
        cell.real_width = std::max( cell.real_width, get_entry_cell_width( entry, i ) );
        // Don't reveal the cell for headers and stubs
        if( cell.visible() || ( entry.is_item() && !preset.is_stub_cell( entry, i ) ) ) {
            const size_t cell_gap = i > 0 ? normal_cell_gap : 0;
            cell.current_width = std::max( cell.current_width, cell_gap + cell.real_width );
        }
    }
    if( !denial.empty() ) {
        reserved_width = std::max( get_entry_cell_width( entry, 0 ) + min_denial_gap + utf8_width( denial,
                                   true ),
                                   reserved_width );
    }
}
References inventory_selector_preset::cells, inventory_entry::is_item(), min_denial_gap, normal_cell_gap, num, and utf8_width().
Referenced by selection_column::on_change(), selection_column::prepare_paging(), and selection_column::reset_width().
find_by_invlet()
inventory_entry * inventory_column::find_by_invlet (int invlet) const
Definition at line 209 of file inventory_ui.cpp.
{
    for( const auto &elem : entries ) {
        if( elem.is_item() && elem.get_invlet() == invlet ) {
            return const_cast<inventory_entry *>( &elem );
        }
    }
    return nullptr;
}
References entries.
get_all_selected()
std::vector< inventory_entry * > inventory_column::get_all_selected () const
Definition at line 617 of file inventory_ui.cpp.
{
    const auto filter_to_selected = [&]( const inventory_entry & entry ) {
        return is_selected( entry );
    };
    return get_entries( filter_to_selected );
}
get_cells_width()
size_t inventory_column::get_cells_width () const protected
Sum of the cell widths.
Definition at line 431 of file inventory_ui.cpp.
{
    return std::accumulate( cells.begin(), cells.end(), static_cast<size_t>( 0 ), []( size_t lhs,
    const cell_t &cell ) {
        return lhs + cell.current_width;
    } );
}
References inventory_selector_preset::cells.
Referenced by get_width().
get_entries()
std::vector< inventory_entry * > inventory_column::get_entries (const std::function< bool(const inventory_entry &entry)> & filter_func) const
Definition at line 625 of file inventory_ui.cpp.
{
    std::vector<inventory_entry *> res;
    if( allows_selecting() ) {
        for( const auto &elem : entries ) {
            if( filter_func( elem ) ) {
                res.push_back( const_cast<inventory_entry *>( &elem ) );
            }
        }
    }
    return res;
}
get_entry_cell_cache()
const inventory_column::entry_cell_cache_t & inventory_column::get_entry_cell_cache (size_t index) const protected
Definition at line 464 of file inventory_ui.cpp.
{
    assert( index < entries.size() );
    if( entries_cell_cache.size() < entries.size() ) {
        entries_cell_cache.resize( entries.size() );
    }
    if( !entries_cell_cache[index].assigned ) {
        entries_cell_cache[index] = make_entry_cell_cache( entries[index] );
    }
    return entries_cell_cache[index];
}
get_entry_cell_width() [1/2]
size_t inventory_column::get_entry_cell_width (const inventory_entry & entry, size_t cell_index) const protected
Definition at line 419 of file inventory_ui.cpp.
{
    size_t res = utf8_width( preset.get_cell_text( entry, cell_index ), true );
    if( cell_index == 0 ) {
        res += get_entry_indent( entry );
    }
    return res;
}
References utf8_width().
get_entry_cell_width() [2/2]
size_t inventory_column::get_entry_cell_width (size_t index, size_t cell_index) const protected
Overall cell width.
If corresponding cell is not empty (its width is greater than zero), then a value returned by inventory_column::get_entry_indent() is added to the result.
Definition at line 408 of file inventory_ui.cpp.
{
    size_t res = utf8_width( get_entry_cell_cache( index ).text[cell_index], true );
    if( cell_index == 0 ) {
        res += get_entry_indent( entries[index] );
    }
    return res;
}
References utf8_width().
get_entry_indent()
size_t inventory_column::get_entry_indent (const inventory_entry & entry) const protected
Indentation of the entry.
Parameters
entry The entry to check
Returns
Either left indent when it's zero, or a gap between cells.
Definition at line 831 of file inventory_ui.cpp.
{
    if( !entry.is_item() ) {
        return 0;
    }
    size_t res = 2;
    if( get_option<bool>( "ITEM_SYMBOLS" ) ) {
        res += 2;
    }
    if( allows_selecting() && activatable() && multiselect ) {
        res += 2;
    }
    return res;
}
References inventory_entry::is_item().
get_height()
size_t inventory_column::get_height () const
Definition at line 224 of file inventory_ui.cpp.
{
    return std::min( entries.size(), height );
}
References entries, and height.
get_selected()
const inventory_entry & inventory_column::get_selected () const
Definition at line 607 of file inventory_ui.cpp.
{
    if( selected_index >= entries.size() || !entries[selected_index].is_item() ) {
        // clang complains if we use the default constructor here
        static const inventory_entry dummy( nullptr );
        return dummy;
    }
    return entries[selected_index];
}
Referenced by inventory_pick_selector::execute(), and inventory_selector::get_selected().
get_selected_index()
size_t inventory_column::get_selected_index () inline
Definition at line 291 of file inventory_ui.h.
{
            return selected_index;
        }
References selected_index.
Referenced by inventory_selector::get_selection_position().
get_width()
size_t inventory_column::get_width () const
Definition at line 219 of file inventory_ui.cpp.
{
    return std::max( get_cells_width(), reserved_width );
}
References get_cells_width(), and reserved_width.
has_available_choices()
bool inventory_column::has_available_choices () const
Definition at line 582 of file inventory_ui.cpp.
{
    if( !allows_selecting() || !activatable() ) {
        return false;
    }
    for( size_t i = 0; i < entries.size(); ++i ) {
        if( entries[i].is_item() && get_entry_cell_cache( i ).denial.empty() ) {
            return true;
        }
    }
    return false;
}
is_selected()
bool inventory_column::is_selected (const inventory_entry & entry) const
Definition at line 595 of file inventory_ui.cpp.
{
    return entry == get_selected() || ( multiselect && is_selected_by_category( entry ) );
}
is_selected_by_category()
bool inventory_column::is_selected_by_category (const inventory_entry & entry) const
Does this entry belong to the selected category? When navigation_mode::ITEM is used it's equivalent to is_selected().
Definition at line 600 of file inventory_ui.cpp.
{
    return entry.is_item() && mode == navigation_mode::CATEGORY
           && entry.get_category_ptr() == get_selected().get_category_ptr()
           && page_of( entry ) == page_index();
}
References CATEGORY, inventory_entry::get_category_ptr(), and inventory_entry::is_item().
make_entry_cell_cache()
inventory_column::entry_cell_cache_t inventory_column::make_entry_cell_cache (const inventory_entry & entry) const protected
Definition at line 447 of file inventory_ui.cpp.
{
    entry_cell_cache_t result;
    result.assigned = true;
    result.color = preset.get_color( entry );
    result.denial = preset.get_denial( entry );
    result.text.resize( preset.get_cells_count() );
    for( size_t i = 0, n = preset.get_cells_count(); i < n; ++i ) {
        result.text[i] = preset.get_cell_text( entry, i );
    }
    return result;
}
move_entries_to()
void inventory_column::move_entries_to (inventory_column & dest)
Definition at line 727 of file inventory_ui.cpp.
{
    for( const auto &elem : entries ) {
        if( elem.is_item() &&
            // this column already has this entry, no need to try to add it again
            std::find( dest.entries.begin(), dest.entries.end(), elem ) == dest.entries.end() ) {
            dest.add_entry( elem );
        }
    }
    dest.prepare_paging();
    clear();
}
References add_entry(), catacurses::clear(), entries, detail::find(), and prepare_paging().
Referenced by inventory_selector::rearrange_columns().
move_selection()
void inventory_column::move_selection (scroll_direction dir) protected
Move the selection.
Definition at line 378 of file inventory_ui.cpp.
{
    size_t index = selected_index;
    do {
        index = next_selectable_index( index, dir );
    } while( index != selected_index && is_selected_by_category( entries[index] ) );
    select( index, dir );
}
move_selection_page()
void inventory_column::move_selection_page (scroll_direction dir) protected
Definition at line 389 of file inventory_ui.cpp.
{
    size_t index = selected_index;
    do {
        const size_t next_index = next_selectable_index( index, dir );
        const bool flipped = next_index == selected_index ||
                             ( next_index > selected_index ) != ( static_cast<int>( dir ) > 0 );
        if( flipped && page_of( next_index ) == page_index() ) {
            break; // If flipped and still on the same page - no need to flip
        }
        index = next_index;
    } while( page_of( next_selectable_index( index, dir ) ) == page_index() );
    select( index, dir );
}
next_selectable_index()
size_t inventory_column::next_selectable_index (size_t index, scroll_direction dir) const protected
Definition at line 355 of file inventory_ui.cpp.
{
    if( entries.empty() ) {
        return index;
    }
    // limit index to the space of the size of entries
    index = index % entries.size();
    size_t new_index = index;
    do {
        // 'new_index' incremented by 'dir' using division remainder (number of entries) to loop over the entries.
        // Negative step '-k' (backwards) is equivalent to '-k + N' (forward), where:
        //     N = entries.size()  - number of elements,
        //     k = |step|          - absolute step (k <= N).
        new_index = ( new_index + static_cast<int>( dir ) + entries.size() ) % entries.size();
    } while( new_index != index && !entries[new_index].is_selectable() );
    if( !entries[new_index].is_selectable() ) {
        return static_cast<size_t>( -1 );
    }
    return new_index;
}
on_activate()
virtual void inventory_column::on_activate () inline virtual
The column has been activated.
Definition at line 322 of file inventory_ui.h.
{
            active = true;
        }
References active.
Referenced by inventory_selector::append_column(), and inventory_selector::set_active_column().
on_change()
virtual void inventory_column::on_change (const inventory_entry &) inline virtual
The entry has been changed.
Reimplemented in selection_column.
Definition at line 320 of file inventory_ui.h.
{}
on_deactivate()
virtual void inventory_column::on_deactivate () inline virtual
The column has been deactivated.
Definition at line 326 of file inventory_ui.h.
{
            active = false;
        }
References active.
Referenced by inventory_selector::set_active_column().
on_input()
void inventory_column::on_input (const inventory_input & input) virtual
Event handlers.
Definition at line 683 of file inventory_ui.cpp.
{
    if( empty() || !active ) {
        return; // ignore
    }
    if( input.action == "DOWN" ) {
        move_selection( scroll_direction::FORWARD );
    } else if( input.action == "UP" ) {
        move_selection( scroll_direction::BACKWARD );
    } else if( input.action == "PAGE_DOWN" ) {
        move_selection_page( scroll_direction::FORWARD );
    } else if( input.action == "PAGE_UP" ) {
        move_selection_page( scroll_direction::BACKWARD );
    } else if( input.action == "HOME" ) {
        select( 0, scroll_direction::FORWARD );
    } else if( input.action == "END" ) {
        select( entries.size() - 1, scroll_direction::BACKWARD );
    } else if( input.action == "TOGGLE_FAVORITE" ) {
        const item_location &loc = get_selected().any_item();
        set_stack_favorite( loc, !loc->is_favorite );
    }
}
References inventory_input::action, active, BACKWARD, FORWARD, and item::is_favorite.
on_mode_change()
virtual void inventory_column::on_mode_change (navigation_mode mode) inline virtual
Selection mode has been changed.
Reimplemented in selection_column.
Definition at line 330 of file inventory_ui.h.
{
            this->mode = mode;
        }
References mode.
Referenced by inventory_selector::append_column().
page_index()
size_t inventory_column::page_index () const inline
Definition at line 250 of file inventory_ui.h.
{
            return page_of( page_offset );
        }
References page_of(), and page_offset.
page_of() [1/2]
size_t inventory_column::page_of (const inventory_entry & entry) const protected
Definition at line 577 of file inventory_ui.cpp.
{
    return page_of( std::distance( entries.begin(), std::find( entries.begin(), entries.end(),
                                   entry ) ) );
}
References detail::find().
page_of() [2/2]
size_t inventory_column::page_of (size_t index) const protected
Definition at line 570 of file inventory_ui.cpp.
{
    assert( entries_per_page ); // To appease static analysis
    // NOLINTNEXTLINE(clang-analyzer-core.DivideZero)
    return index / entries_per_page;
}
Referenced by page_index(), and pages_count().
pages_count()
size_t inventory_column::pages_count () const inline
Definition at line 254 of file inventory_ui.h.
{
            return page_of( entries.size() + entries_per_page - 1 );
        }
References entries, entries_per_page, and page_of().
Referenced by selection_column::activatable().
prepare_paging()
void inventory_column::prepare_paging (const std::string & filter = "") virtual
Reorder entries, repopulate titles, adjust to the new height.
Reimplemented in selection_column.
Definition at line 740 of file inventory_ui.cpp.
{
    if( paging_is_valid ) {
        return;
    }
    const auto filter_fn = filter_from_string<inventory_entry>(
    filter, [this]( const std::string & filter ) {
        return preset.get_filter( filter );
    } );
    // FIXME: toggled status of multiselect menu resets when filtering the menu
    // First, remove all non-items
    const auto new_end = std::remove_if( entries.begin(),
    entries.end(), [&filter_fn]( const inventory_entry & entry ) {
        return !entry.is_item() || !filter_fn( entry );
    } );
    entries.erase( new_end, entries.end() );
    // Then sort them with respect to categories
    auto from = entries.begin();
    while( from != entries.end() ) {
        auto to = std::next( from );
        while( to != entries.end() && from->get_category_ptr() == to->get_category_ptr() ) {
            to->update_cache();
            std::advance( to, 1 );
        }
        if( ordered_categories.count( from->get_category_ptr()->get_id().c_str() ) == 0 ) {
            std::sort( from, to, [ this ]( const inventory_entry & lhs, const inventory_entry & rhs ) {
                if( lhs.is_selectable() != rhs.is_selectable() ) {
                    return lhs.is_selectable(); // Disabled items always go last
                }
                return preset.sort_compare( lhs, rhs );
            } );
        }
        from = to;
    }
    // Recover categories
    const item_category *current_category = nullptr;
    for( auto iter = entries.begin(); iter != entries.end(); ++iter ) {
        if( iter->get_category_ptr() == current_category ) {
            continue;
        }
        current_category = iter->get_category_ptr();
        iter = entries.insert( iter, inventory_entry( current_category ) );
        expand_to_fit( *iter );
    }
    // Determine the new height.
    entries_per_page = height;
    if( entries.size() > entries_per_page ) {
        entries_per_page -= 1;  // Make room for the page number.
        for( size_t i = entries_per_page - 1; i < entries.size(); i += entries_per_page ) {
            auto iter = std::next( entries.begin(), i );
            if( iter->is_category() ) {
                // The last item on the page must not be a category.
                entries.insert( iter, inventory_entry() );
            } else {
                // The first item on the next page must be a category.
                iter = std::next( iter );
                if( iter != entries.end() && iter->is_item() ) {
                    entries.insert( iter, inventory_entry( iter->get_category_ptr() ) );
                }
            }
        }
    }
    entries_cell_cache.clear();
    paging_is_valid = true;
    if( entries_unfiltered.empty() ) {
        entries_unfiltered = entries;
    }
    // Select the uppermost possible entry
    select( selected_index, selected_index ? scroll_direction::BACKWARD : scroll_direction::FORWARD );
}
References BACKWARD, FORWARD, inventory_entry::is_selectable(), and ordered_categories.
Referenced by move_entries_to(), and selection_column::prepare_paging().
reassign_custom_invlets()
int inventory_column::reassign_custom_invlets (const player & p, int min_invlet, int max_invlet)
Returns next custom inventory letter.
Definition at line 847 of file inventory_ui.cpp.
{
    int cur_invlet = min_invlet;
    for( auto &elem : entries ) {
        // Only items on map/in vehicles: those that the player does not possess.
        if( elem.is_selectable() && !p.has_item( *elem.any_item() ) ) {
            elem.custom_invlet = cur_invlet <= max_invlet ? cur_invlet++ : '\0';
        }
    }
    return cur_invlet;
}
References visitable< T >::has_item().
reset_width()
void inventory_column::reset_width (const std::vector< inventory_column * > & all_columns) virtual
Resets width to original (unchanged).
Reimplemented in selection_column.
Definition at line 559 of file inventory_ui.cpp.
{
    for( auto &elem : cells ) {
        elem = cell_t();
    }
    reserved_width = 0;
    for( auto &elem : entries ) {
        expand_to_fit( elem );
    }
}
References inventory_selector_preset::cells.
Referenced by selection_column::reset_width().
select() [1/2]
bool inventory_column::select (const item_location & loc)
Selects the specified location.
Definition at line 820 of file inventory_ui.cpp.
{
    for( size_t index = 0; index < entries.size(); ++index ) {
        if( entries[index].is_selectable() && entries[index].any_item() == loc ) {
            select( index, scroll_direction::FORWARD );
            return true;
        }
    }
    return false;
}
References FORWARD.
Referenced by selection_column::prepare_paging(), and inventory_selector::select_position().
select() [2/2]
void inventory_column::select (size_t new_index, scroll_direction dir)
Change the selection.
Parameters
new_index Index of the entry to select.
dir If the entry is not selectable, move in the specified direction
Definition at line 342 of file inventory_ui.cpp.
{
    if( new_index < entries.size() ) {
        if( !entries[new_index].is_selectable() ) {
            new_index = next_selectable_index( new_index, dir );
        }
        selected_index = new_index;
        page_offset = ( new_index == static_cast<size_t>( -1 ) ) ?
                      0 : selected_index - selected_index % entries_per_page;
    }
}
set_filter()
void inventory_column::set_filter (const std::string & filter)
Definition at line 439 of file inventory_ui.cpp.
{
    entries = entries_unfiltered;
    entries_cell_cache.clear();
    paging_is_valid = false;
    prepare_paging( filter );
}
set_height()
void inventory_column::set_height (size_t new_height)
Definition at line 518 of file inventory_ui.cpp.
{
    if( height != new_height ) {
        if( new_height <= 1 ) {
            debugmsg( "Unable to assign height <= 1 (was %zd).", new_height );
            return;
        }
        height = new_height;
        entries_per_page = new_height;
        paging_is_valid = false;
    }
}
References debugmsg.
set_multiselect()
void inventory_column::set_multiselect (bool multiselect) inline
Definition at line 295 of file inventory_ui.h.
{
            this->multiselect = multiselect;
        }
References multiselect.
set_stack_favorite()
void inventory_column::set_stack_favorite (const item_location & location, bool favorite)
Definition at line 641 of file inventory_ui.cpp.
{
    const item *selected_item = location.get_item();
    std::list<item *> to_favorite;
    if( location.where() == item_location::type::character ) {
        int position = g->u.get_item_position( selected_item );
        if( position < 0 ) {
            g->u.i_at( position ).set_favorite( !selected_item->is_favorite ); // worn/wielded
        } else {
            g->u.inv.set_stack_favorite( position, !selected_item->is_favorite ); // in inventory
        }
    } else if( location.where() == item_location::type::map ) {
        auto items = g->m.i_at( location.position() );
        for( auto &item : items ) {
            if( item.stacks_with( *selected_item ) ) {
                to_favorite.push_back( &item );
            }
        }
        for( auto &item : to_favorite ) {
            item->set_favorite( favorite );
        }
    } else if( location.where() == item_location::type::vehicle ) {
        const cata::optional<vpart_reference> vp = g->m.veh_at(
                    location.position() ).part_with_feature( "CARGO", true );
        assert( vp );
        auto items = vp->vehicle().get_items( vp->part_index() );
        for( auto &item : items ) {
            if( item.stacks_with( *selected_item ) ) {
                to_favorite.push_back( &item );
            }
        }
        for( auto *item : to_favorite ) {
            item->set_favorite( favorite );
        }
    }
}
References item_location::character, g, item_location::get_item(), item::is_favorite, item_location::map, item_location::position(), item::set_favorite(), item::stacks_with(), item_location::vehicle, and item_location::where().
set_visibility()
void inventory_column::set_visibility (bool visibility) inline
Definition at line 299 of file inventory_ui.h.
{
            this->visibility = visibility;
        }
References visibility.
set_width()
void inventory_column::set_width (size_t new_width, const std::vector< inventory_column * > & all_columns)
Definition at line 480 of file inventory_ui.cpp.
{
    reset_width( all_columns );
    int width_gap = get_width() - new_width;
    // Now adjust the width if we must
    while( width_gap != 0 ) {
        const int step = width_gap > 0 ? -1 : 1;
        // Should return true when lhs < rhs
        const auto cmp_for_expansion = []( const cell_t &lhs, const cell_t &rhs ) {
            return lhs.visible() && lhs.gap() < rhs.gap();
        };
        // Should return true when lhs < rhs
        const auto cmp_for_shrinking = []( const cell_t &lhs, const cell_t &rhs ) {
            if( !lhs.visible() ) {
                return false;
            }
            if( rhs.gap() <= min_cell_gap ) {
                return lhs.current_width < rhs.current_width;
            } else {
                return lhs.gap() < rhs.gap();
            }
        };
        const auto &cell = step > 0
                           ? std::min_element( cells.begin(), cells.end(), cmp_for_expansion )
                           : std::max_element( cells.begin(), cells.end(), cmp_for_shrinking );
        if( cell == cells.end() || !cell->visible() ) {
            break; // This is highly unlikely to happen, but just in case
        }
        cell->current_width += step;
        width_gap += step;
    }
    reserved_width = new_width;
}
References inventory_selector_preset::cells, inventory_column::cell_t::current_width, inventory_column::cell_t::gap(), min_cell_gap, and inventory_column::cell_t::visible().
visible()
bool inventory_column::visible () const inline
Is this column visible?
Definition at line 238 of file inventory_ui.h.
{
            return !empty() && visibility && preset.get_cells_count() > 0;
        }
References empty(), inventory_selector_preset::get_cells_count(), preset, and visibility.
visible_cells()
size_t inventory_column::visible_cells () const private
Returns
Number of visible cells
Definition at line 976 of file inventory_ui.cpp.
{
    return std::count_if( cells.begin(), cells.end(), []( const cell_t &elem ) {
        return elem.visible();
    } );
}
References inventory_selector_preset::cells.
Member Data Documentation
active
bool inventory_column::active = false protected
Definition at line 378 of file inventory_ui.h.
Referenced by on_activate(), and on_deactivate().
cells
std::vector<cell_t> inventory_column::cells private
Definition at line 403 of file inventory_ui.h.
Referenced by inventory_column().
entries
std::vector<inventory_entry> inventory_column::entries protected
Definition at line 375 of file inventory_ui.h.
Referenced by activatable(), empty(), find_by_invlet(), get_height(), move_entries_to(), selection_column::on_change(), pages_count(), and selection_column::prepare_paging().
entries_cell_cache
std::vector<entry_cell_cache_t> inventory_column::entries_cell_cache mutable private
Definition at line 404 of file inventory_ui.h.
entries_per_page
size_t inventory_column::entries_per_page = std::numeric_limits<size_t>::max() protected
Definition at line 385 of file inventory_ui.h.
Referenced by pages_count().
entries_unfiltered
std::vector<inventory_entry> inventory_column::entries_unfiltered protected
Definition at line 376 of file inventory_ui.h.
height
size_t inventory_column::height = std::numeric_limits<size_t>::max() protected
Definition at line 386 of file inventory_ui.h.
Referenced by get_height().
mode
navigation_mode inventory_column::mode = navigation_mode::ITEM protected
Definition at line 377 of file inventory_ui.h.
Referenced by on_mode_change().
multiselect
bool inventory_column::multiselect = false protected
Definition at line 379 of file inventory_ui.h.
Referenced by set_multiselect().
page_offset
size_t inventory_column::page_offset = 0 protected
Definition at line 384 of file inventory_ui.h.
Referenced by page_index().
paging_is_valid
bool inventory_column::paging_is_valid = false protected
Definition at line 380 of file inventory_ui.h.
Referenced by selection_column::on_change().
preset
const inventory_selector_preset& inventory_column::preset protected
Definition at line 373 of file inventory_ui.h.
Referenced by inventory_column(), and visible().
reserved_width
size_t inventory_column::reserved_width = 0 protected
Definition at line 387 of file inventory_ui.h.
Referenced by get_width().
selected_index
size_t inventory_column::selected_index = 0 protected
Definition at line 383 of file inventory_ui.h.
Referenced by get_selected_index().
visibility
bool inventory_column::visibility = true protected
Definition at line 381 of file inventory_ui.h.
Referenced by set_visibility(), and visible().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp