Cataclysm BN: deploy_furn_actor Class Reference
deploy_furn_actor Class Reference
Implements deployable furniture from items.
#include <iuse_actor.h>
Public Member Functions
deploy_furn_actor ()
~deploy_furn_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
string_id< furn_t > furn_type
furniture type id the item should create
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Implements deployable furniture from items.
Definition at line 473 of file iuse_actor.h.
Constructor & Destructor Documentation
deploy_furn_actor()
deploy_furn_actor::deploy_furn_actor () inline
Definition at line 481 of file iuse_actor.h.
: iuse_actor("deploy_furn") {}
~deploy_furn_actor()
deploy_furn_actor::~deploy_furn_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > deploy_furn_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1204 of file iuse_actor.cpp.
{
    return std::make_unique<deploy_furn_actor>( *this );
}
info()
void deploy_furn_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 1209 of file iuse_actor.cpp.
{
    std::vector<std::string> can_function_as;
    const furn_t &the_furn = furn_type.obj();
    const std::string furn_name = the_furn.name();
    if( the_furn.workbench ) {
        can_function_as.emplace_back( _( "a <info>crafting station</info>" ) );
    }
    if( the_furn.has_flag( "BUTCHER_EQ" ) ) {
        can_function_as.emplace_back(
            _( "a place to hang <info>corpses for butchering</info>" ) );
    }
    if( the_furn.has_flag( "FLAT_SURF" ) ) {
        can_function_as.emplace_back(
            _( "a flat surface to <info>butcher</info> onto or <info>eat meals</info> from" ) );
    }
    if( the_furn.has_flag( "CAN_SIT" ) ) {
        can_function_as.emplace_back( _( "a place to <info>sit</info>" ) );
    }
    if( the_furn.has_flag( "HIDE_PLACE" ) ) {
        can_function_as.emplace_back( _( "a place to <info>hide</info>" ) );
    }
    if( the_furn.has_flag( "FIRE_CONTAINER" ) ) {
        can_function_as.emplace_back( _( "a safe place to <info>contain a fire</info>" ) );
    }
    if( the_furn.crafting_pseudo_item == itype_char_smoker ) {
        can_function_as.emplace_back( _( "a place to <info>smoke or dry food</info> for preservation" ) );
    }
    if( can_function_as.empty() ) {
        dump.emplace_back( "DESCRIPTION",
                           string_format( _( "Can be <info>activated</info> to deploy as furniture (<stat>%s</stat>)." ),
                                          furn_name ) );
    } else {
        std::string furn_usages = enumerate_as_string( can_function_as, enumeration_conjunction::or_ );
        dump.emplace_back( "DESCRIPTION",
                           string_format(
                               _( "Can be <info>activated</info> to deploy as furniture (<stat>%s</stat>), which can then be used as %s." ),
                               furn_name, furn_usages ) );
    }
}
References _, furn_t::crafting_pseudo_item, enumerate_as_string(), furn_type, map_data_common_t::has_flag(), itype_char_smoker, map_data_common_t::name(), string_id< T >::obj(), or_, string_format(), and furn_t::workbench.
load()
void deploy_furn_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1252 of file iuse_actor.cpp.
{
    furn_type = furn_str_id( obj.get_string( "furn_type" ) );
}
References furn_type, and JsonObject::get_string().
use()
int deploy_furn_actor::use (player & p, item & it, bool , const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 1257 of file iuse_actor.cpp.
{
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    tripoint pnt = pos;
    if( pos == p.pos() ) {
        if( const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Deploy where?" ) ) ) {
            pnt = *pnt_;
        } else {
            return 0;
        }
    }
    if( pnt == p.pos() ) {
        p.add_msg_if_player( m_info,
                             _( "You attempt to become one with the furniture.  It doesn't work." ) );
        return 0;
    }
    map &here = get_map();
    optional_vpart_position veh_there = here.veh_at( pnt );
    if( veh_there.has_value() ) {
        // TODO: check for protrusion+short furniture, wheels+tiny furniture, NOCOLLIDE flag, etc.
        // and/or integrate furniture deployment with construction (which already seems to perform these checks sometimes?)
        p.add_msg_if_player( m_info, _( "The space under %s is too cramped to deploy a %s in." ),
                             veh_there.value().vehicle().disp_name(), it.tname() );
        return 0;
    }
    // For example: dirt = 2, long grass = 3
    if( here.move_cost( pnt ) != 2 && here.move_cost( pnt ) != 3 ) {
        p.add_msg_if_player( m_info, _( "You can't deploy a %s there." ), it.tname() );
        return 0;
    }
    if( here.has_furn( pnt ) ) {
        p.add_msg_if_player( m_info, _( "There is already furniture at that location." ) );
        return 0;
    }
    here.furn_set( pnt, furn_type );
    p.mod_moves( to_turns<int>( 2_seconds ) );
    return 1;
}
References _, player::add_msg_if_player(), choose_adjacent(), vehicle::disp_name(), map::furn_set(), furn_type, get_map(), map::has_furn(), cata::optional< T >::has_value(), Character::is_mounted(), m_info, Creature::mod_moves(), map::move_cost(), Character::pos(), item::tname(), cata::optional< T >::value(), map::veh_at(), and vpart_position::vehicle().
Member Data Documentation
furn_type
string_id<furn_t> deploy_furn_actor::furn_type
furniture type id the item should create
Definition at line 479 of file iuse_actor.h.
Referenced by info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp