Cataclysm BN: grid_furn_transform_queue Class Reference
grid_furn_transform_queue Class Reference
Represents queued active tile / furniture transformations.
#include <distribution_grid.h>
Public Member Functions
void add (const tripoint_abs_ms &p, const furn_str_id &id, const std::string &msg)
void apply (mapbuffer &mb, distribution_grid_tracker &grid_tracker, Character &u, map &m)
void clear ()
bool operator== (const grid_furn_transform_queue &l) const
std::string to_string () const
Private Attributes
std::vector< transform_queue_entry > queue
Detailed Description
Represents queued active tile / furniture transformations.
Some active tiles can turn into other active tiles, or even inactive tiles, as a result of an update. If such transformation is applied immediately, it could trigger recalculation of the grid that's being updated, which would require additional code to handle.
As a simpler alternative, we queue active tile transformations and apply them only after all grids have been updated. The transformations are applied according to FIFO method, so if some tile has multiple competing transforms queued, the last one will win out.
Definition at line 88 of file distribution_grid.h.
Member Function Documentation
add()
void grid_furn_transform_queue::add (const tripoint_abs_ms & p, const furn_str_id & id, const std::string & msg) inline
Definition at line 94 of file distribution_grid.h.
{
            queue.emplace_back( transform_queue_entry{ p, id, msg } );
        }
References base_camps::id, and queue.
Referenced by charge_watcher_tile::update_internal(), and steady_consumer_tile::update_internal().
apply()
void grid_furn_transform_queue::apply (mapbuffer & mb, distribution_grid_tracker & grid_tracker, Character & u, map & m)
Definition at line 293 of file distribution_grid.cpp.
{
    for( const auto &qt : queue ) {
        tripoint_abs_sm p_abs_sm;
        point_sm_ms p_within_sm;
        std::tie( p_abs_sm, p_within_sm ) = project_remain<coords::sm>( qt.p );
        submap *sm = mb.lookup_submap( p_abs_sm );
        if( sm == nullptr ) {
            return;
        }
        const furn_t &old_t = sm->get_furn( p_within_sm.raw() ).obj();
        const furn_t &new_t = qt.id.obj();
        sm->set_furn( p_within_sm.raw(), qt.id );
        if( !qt.msg.empty() ) {
            const tripoint pos_local = m.getlocal( qt.p.raw() );
            if( u.sees( pos_local ) ) {
                add_msg( "%s", _( qt.msg ) );
            }
        }
        // TODO: this is copy-pasted from map.cpp
        if( old_t.active ) {
            sm->active_furniture.erase( p_within_sm );
            // TODO: Only for g->m? Observer pattern?
            grid_tracker.on_changed( qt.p );
        }
        if( new_t.active ) {
            active_tile_data *atd = new_t.active->clone();
            atd->set_last_updated( calendar::turn );
            sm->active_furniture[p_within_sm].reset( atd );
            grid_tracker.on_changed( qt.p );
        }
    }
}
References _, furn_t::active, add_msg(), map::getlocal(), furn_t::id, mapbuffer::lookup_submap(), string_id< T >::obj(), distribution_grid_tracker::on_changed(), queue, coords::coord_point< Point, Origin, Scale >::raw(), Character::sees(), active_tile_data::set_last_updated(), coords::sm, and calendar::turn.
Referenced by distribution_grid_tracker::update().
clear()
void grid_furn_transform_queue::clear () inline
Definition at line 100 of file distribution_grid.h.
                     {
            queue.clear();
        }
References queue.
Referenced by distribution_grid_tracker::update().
operator==()
bool grid_furn_transform_queue::operator== (const grid_furn_transform_queue & l) const inline
Definition at line 104 of file distribution_grid.h.
{
            return queue == l.queue;
        }
References queue.
to_string()
std::string grid_furn_transform_queue::to_string () const
Definition at line 333 of file distribution_grid.cpp.
{
    std::string ret;
    size_t i = 0;
    for( const transform_queue_entry &q : queue ) {
        ret += string_format( "% 2d: %s %s \"%s\"\n", i, q.p.to_string(), q.id, q.msg );
        i++;
    }
    return ret;
}
References queue, cata::hash64_detail::ret, and string_format().
Member Data Documentation
queue
std::vector<transform_queue_entry> grid_furn_transform_queue::queue private
Definition at line 91 of file distribution_grid.h.
Referenced by add(), apply(), clear(), operator==(), and to_string().
The documentation for this class was generated from the following files:
src/distribution_grid.h
src/distribution_grid.cpp