Cataclysm BN: cone_factory Class Reference
cone_factory Class Reference
#include <shape_impl.h>
Public Member Functions
cone_factory ()=default
cone_factory (const cone_factory &)=default
cone_factory (units::angle half_angle, double length)
std::shared_ptr< shape > create (const rl_vec3d &start, const rl_vec3d &end) const override
const std::string & get_type () const override
void serialize (JsonOut &jsout) const override
void deserialize (JsonIn &jsin) override
double get_range () const override
std::string get_description () const override
Public Member Functions inherited from shape_factory_impl
virtual ~shape_factory_impl ()=default
Private Attributes
units::angle half_angle
TODO: Angles deserve a proper unit type.
double length
Detailed Description
Definition at line 266 of file shape_impl.h.
Constructor & Destructor Documentation
cone_factory() [1/3]
cone_factory::cone_factory () default
cone_factory() [2/3]
cone_factory::cone_factory (const cone_factory &) default
cone_factory() [3/3]
cone_factory::cone_factory (units::angle half_angle, double length) inline
Definition at line 275 of file shape_impl.h.
            : half_angle( half_angle )
            , length( length )
        {}
Member Function Documentation
create()
std::shared_ptr< shape > cone_factory::create (const rl_vec3d & start, const rl_vec3d & end) const inline override virtual
Implements shape_factory_impl.
Definition at line 280 of file shape_impl.h.
{
            std::shared_ptr<cone> c = std::make_shared<cone>( half_angle, length );
            // Very thin cones may lack points close to origin after discretization, so let's hack it
            std::shared_ptr<cylinder> cyl = std::make_shared<cylinder>( length - 1.0, 0.5 );
            // Offset to prevent it reaching backwards when rotated
            std::shared_ptr<shape_impl> offset_cyl = std::make_shared<offset_shape>( cyl,
                    rl_vec3d( 0.0, -0.5, 0.0 ) );
            auto mindist = std::make_shared<shape_min>( c, offset_cyl );
            auto mindist_minus_origin = std::make_shared<shape_exclude_circle>( mindist, 0.5 );
            rl_vec3d diff = end - start;
            // Plus 90 deg because @ref cone extends in -y direction
            units::angle rotation_angle = units::atan2( diff.y, diff.x ) + 90_degrees;
            std::shared_ptr<rotate_z_shape> r = std::make_shared<rotate_z_shape>(
                                                    mindist_minus_origin, rotation_angle );
            std::shared_ptr<offset_shape> o = std::make_shared<offset_shape>( r,
                                              rl_vec3d( start.x, start.y, start.z ) );
            return std::make_shared<shape>( o, start.as_point() );
        }
References rl_vec3d::as_point(), units::atan2(), c, half_angle, length, rl_vec3d::x, rl_vec3d::y, and rl_vec3d::z.
deserialize()
void cone_factory::deserialize (JsonIn & jsin) inline override virtual
Reimplemented from shape_factory_impl.
Definition at line 308 of file shape_impl.h.
{
            JsonObject jo = jsin.get_object();
            half_angle = units::from_degrees( jo.get_int( "half_angle" ) );
            jo.read( "length", length );
        }
References units::from_degrees(), JsonObject::get_int(), JsonIn::get_object(), half_angle, length, and JsonObject::read().
get_description()
std::string cone_factory::get_description () const inline override virtual
Implements shape_factory_impl.
Definition at line 318 of file shape_impl.h.
{
            return string_format( _( "Cone of length <info>%d</info>, apex angle <info>%d</info>" ),
                                  static_cast<int>( length ),
                                  static_cast<int>( std::round( units::to_degrees( half_angle * 2 ) ) ) );
        }
References _, half_angle, length, string_format(), and units::to_degrees().
get_range()
double cone_factory::get_range () const inline override virtual
Implements shape_factory_impl.
Definition at line 314 of file shape_impl.h.
{
            return length;
        }
References length.
get_type()
const std::string & cone_factory::get_type () const inline override virtual
Implements shape_factory_impl.
Definition at line 299 of file shape_impl.h.
{
            return STATIC( "cone" );
        }
References STATIC.
serialize()
void cone_factory::serialize (JsonOut & jsout) const inline override virtual
Reimplemented from shape_factory_impl.
Definition at line 303 of file shape_impl.h.
{
            jsout.start_object();
            jsout.member( "half_angle", static_cast<int>( std::round( units::to_degrees( half_angle ) ) ) );
            jsout.member( "length", length );
        }
References half_angle, length, JsonOut::member(), JsonOut::start_object(), and units::to_degrees().
Member Data Documentation
half_angle
units::angle cone_factory::half_angle private
TODO: Angles deserve a proper unit type.
Definition at line 270 of file shape_impl.h.
Referenced by create(), deserialize(), get_description(), and serialize().
length
double cone_factory::length private
Definition at line 271 of file shape_impl.h.
Referenced by create(), deserialize(), get_description(), get_range(), and serialize().
The documentation for this class was generated from the following file:
src/shape_impl.h