Cataclysm BN: explosion_handler::explosion_queue Class Reference
explosion_handler::explosion_queue Class Reference
#include <explosion_queue.h>
Public Member Functions
void add (queued_explosion &&exp)
void execute ()
void clear ()
Private Attributes
std::deque< queued_explosion > elems
Detailed Description
Definition at line 52 of file explosion_queue.h.
Member Function Documentation
add()
void explosion_handler::explosion_queue::add (queued_explosion && exp) inline
Definition at line 58 of file explosion_queue.h.
{
            elems.push_back( std::move( exp ) );
        }
References elems, and avatar_action::move().
Referenced by explosion_handler::explosion(), explosion_handler::flashbang(), explosion_handler::resonance_cascade(), and explosion_handler::shockwave().
clear()
void explosion_handler::explosion_queue::clear () inline
Definition at line 64 of file explosion_queue.h.
{
            elems.clear();
        }
References elems.
Referenced by game::setup().
execute()
void explosion_handler::explosion_queue::execute ()
Definition at line 1267 of file explosion.cpp.
{
    while( !elems.empty() ) {
        queued_explosion exp = std::move( elems.front() );
        elems.pop_front();
        switch( exp.type ) {
            case ExplosionType::Regular:
                explosion_funcs::regular( exp );
                break;
            case ExplosionType::Flashbang:
                explosion_funcs::flashbang( exp );
                break;
            case ExplosionType::ResonanceCascade:
                explosion_funcs::resonance_cascade( exp );
                break;
            case ExplosionType::Shockwave:
                explosion_funcs::shockwave( exp );
                break;
            default:
                debugmsg( "Explosion type not implemented." );
                break;
        }
    }
}
References debugmsg, explosion_handler::flashbang(), avatar_action::move(), explosion_handler::explosion_funcs::regular(), explosion_handler::resonance_cascade(), and explosion_handler::shockwave().
Referenced by game::do_turn(), mdeath::explode(), and mdeath::focused_beam().
Member Data Documentation
elems
std::deque<queued_explosion> explosion_handler::explosion_queue::elems private
Definition at line 55 of file explosion_queue.h.
Referenced by add(), and clear().
The documentation for this class was generated from the following files:
src/explosion_queue.h
src/explosion.cpp