Cataclysm BN: JsonValue Class Reference
JsonValue Class Reference
#include <json.h>
Public Member Functions
JsonValue (JsonIn &jsin, int pos)
operator std::string () const
operator int () const
operator bool () const
operator double () const
operator JsonObject () const
operator JsonArray () const
template<typename T >
bool read (T &t, bool throw_on_error=false) const
bool test_string () const
bool test_int () const
bool test_bool () const
bool test_float () const
bool test_object () const
bool test_array () const
void throw_error (const std::string &err) const
void show_warning (std::string err) const
std::string get_string () const
int get_int () const
bool get_bool () const
double get_float () const
JsonObject get_object () const
JsonArray get_array () const
Private Member Functions
JsonIn & seek () const
Private Attributes
JsonIn & jsin_
int pos_
Detailed Description
Definition at line 1126 of file json.h.
Constructor & Destructor Documentation
JsonValue()
JsonValue::JsonValue (JsonIn & jsin, int pos) inline
Definition at line 1135 of file json.h.
: jsin_(jsin), pos_(pos) { }
Member Function Documentation
get_array()
JsonArray JsonValue::get_array () const inline
Definition at line 1199 of file json.h.
{
            return seek().get_array();
        }
References JsonIn::get_array(), and seek().
Referenced by json_item_substitution::load(), clothing_mod::load(), tool_comp::load(), item_comp::load(), item_group::load_item_group(), requirement_data::load_obj_list(), load_place_mapings(), load_place_mapings_alternatively(), load_place_mapings_string(), and trait_group::load_trait_group().
get_bool()
bool JsonValue::get_bool () const inline
Definition at line 1190 of file json.h.
{
            return seek().get_bool();
        }
References JsonIn::get_bool(), and seek().
Referenced by JsonObject::get_bool().
get_float()
double JsonValue::get_float () const inline
Definition at line 1193 of file json.h.
{
            return seek().get_float();
        }
References JsonIn::get_float(), and seek().
Referenced by JsonObject::get_float().
get_int()
int JsonValue::get_int () const inline
Definition at line 1187 of file json.h.
{
            return seek().get_int();
        }
References JsonIn::get_int(), and seek().
Referenced by JsonObject::get_int().
get_object()
JsonObject JsonValue::get_object () const inline
Definition at line 1196 of file json.h.
{
            return seek().get_object();
        }
References JsonIn::get_object(), and seek().
Referenced by json_item_substitution::substitution::info::info(), quality_requirement::load(), item_group::load_item_group(), load_place_mapings(), load_place_mapings_string(), and trait_group::load_trait_group().
get_string()
std::string JsonValue::get_string () const inline
Definition at line 1184 of file json.h.
{
            return seek().get_string();
        }
References JsonIn::get_string(), and seek().
Referenced by JsonObject::get_string(), item_group::load_item_group(), load_place_mapings_string(), and trait_group::load_trait_group().
operator bool()
JsonValue::operator bool () const inline
Definition at line 1143 of file json.h.
{
            return seek().get_bool();
        }
References JsonIn::get_bool(), and seek().
operator double()
JsonValue::operator double () const inline
Definition at line 1146 of file json.h.
{
            return seek().get_float();
        }
References JsonIn::get_float(), and seek().
operator int()
JsonValue::operator int () const inline
Definition at line 1140 of file json.h.
{
            return seek().get_int();
        }
References JsonIn::get_int(), and seek().
operator JsonArray()
JsonValue::operator JsonArray () const inline
Definition at line 1152 of file json.h.
{
            return seek().get_array();
        }
References JsonIn::get_array(), and seek().
operator JsonObject()
JsonValue::operator JsonObject () const inline
Definition at line 1149 of file json.h.
{
            return seek().get_object();
        }
References JsonIn::get_object(), and seek().
operator std::string()
JsonValue::operator std::string () const inline
Definition at line 1137 of file json.h.
{
            return seek().get_string();
        }
References JsonIn::get_string(), and seek().
read()
template<typename T > bool JsonValue::read (T & t, bool throw_on_error = false) const inline
Definition at line 1156 of file json.h.
{
            return seek().read( t, throw_on_error );
        }
References JsonIn::read(), and seek().
Referenced by json_item_substitution::substitution::info::info(), and tool_comp::load().
seek()
JsonIn & JsonValue::seek () const private
Definition at line 2141 of file json.cpp.
{
    jsin_.seek( pos_ );
    return jsin_;
}
References jsin_, pos_, and JsonIn::seek().
Referenced by get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), operator bool(), operator double(), operator int(), operator JsonArray(), operator JsonObject(), operator std::string(), read(), test_array(), test_bool(), test_float(), test_int(), test_object(), test_string(), and throw_error().
show_warning()
void JsonValue::show_warning (std::string err) const
Definition at line 295 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    try {
        throw_error( err );
    } catch( const std::exception &e ) {
        debugmsg( "%s", e.what() );
    }
#else
    ( void )err;
#endif // CATA_IN_TOOL
}
References debugmsg, and throw_error().
test_array()
bool JsonValue::test_array () const inline
Definition at line 1175 of file json.h.
{
            return seek().test_array();
        }
References seek(), and JsonIn::test_array().
Referenced by item_group::load_item_group(), load_place_mapings_alternatively(), and trait_group::load_trait_group().
test_bool()
bool JsonValue::test_bool () const inline
Definition at line 1166 of file json.h.
{
            return seek().test_bool();
        }
References seek(), and JsonIn::test_bool().
test_float()
bool JsonValue::test_float () const inline
Definition at line 1169 of file json.h.
{
            return seek().test_float();
        }
References seek(), and JsonIn::test_float().
test_int()
bool JsonValue::test_int () const inline
Definition at line 1163 of file json.h.
{
            return seek().test_int();
        }
References seek(), and JsonIn::test_int().
test_object()
bool JsonValue::test_object () const inline
Definition at line 1172 of file json.h.
{
            return seek().test_object();
        }
References seek(), and JsonIn::test_object().
Referenced by item_group::load_item_group(), load_place_mapings(), load_place_mapings_string(), and trait_group::load_trait_group().
test_string()
bool JsonValue::test_string () const inline
Definition at line 1160 of file json.h.
{
            return seek().test_string();
        }
References seek(), and JsonIn::test_string().
Referenced by json_item_substitution::substitution::info::info(), tool_comp::load(), item_group::load_item_group(), load_place_mapings_string(), and trait_group::load_trait_group().
throw_error()
void JsonValue::throw_error (const std::string & err) const inline
Definition at line 1179 of file json.h.
{
            seek().error( err );
        }
References JsonIn::error(), and seek().
Referenced by tool_comp::load(), item_comp::load(), item_group::load_item_group(), load_place_mapings_string(), trait_group::load_trait_group(), and show_warning().
Member Data Documentation
jsin_
JsonIn& JsonValue::jsin_ private
Definition at line 1129 of file json.h.
Referenced by seek().
pos_
int JsonValue::pos_ private
Definition at line 1130 of file json.h.
Referenced by seek().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp