Cataclysm BN: bionic_install_preset Class Reference
bionic_install_preset Class Reference
Public Member Functions
bionic_install_preset (player &pl, player &patient)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Protected Attributes
player & p
player & pa
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Private Member Functions
std::string get_operation_duration (const item_location &loc)
std::string get_failure_chance (const item_location &loc)
std::string get_anesth_amount (const item_location &loc)
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Detailed Description
Definition at line 1782 of file game_inventory.cpp.
Constructor & Destructor Documentation
bionic_install_preset()
bionic_install_preset::bionic_install_preset (player & pl, player & patient) inline
Definition at line 1785 of file game_inventory.cpp.
                                                             :
            p( pl ), pa( patient ) {
            append_cell( [ this ]( const item_location & loc ) {
                return get_failure_chance( loc );
            }, _( "COMPLICATION CHANCE" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_operation_duration( loc );
            }, _( "OPERATION DURATION" ) );
            append_cell( [this]( const item_location & loc ) {
                return get_anesth_amount( loc );
            }, _( "ANESTHETIC REQUIRED" ) );
        }
References _, inventory_selector_preset::append_cell(), get_anesth_amount(), get_failure_chance(), and get_operation_duration().
Member Function Documentation
get_anesth_amount()
std::string bionic_install_preset::get_anesth_amount (const item_location & loc) inline private
Definition at line 1877 of file game_inventory.cpp.
{
            const int weight = 7;
            const int duration = loc.get_item()->type->bionic->difficulty * 2;
            return string_format( _( "%i mL" ), anesthetic_requirement( duration * weight ) );
        }
References _, anonymous_namespace{game_inventory.cpp}::anesthetic_requirement(), itype::bionic, item_location::get_item(), string_format(), and item::type.
Referenced by bionic_install_preset().
get_denial()
std::string bionic_install_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 1804 of file game_inventory.cpp.
{
            const item *it = loc.get_item();
            const itype *itemtype = it->type;
            const bionic_id &bid = itemtype->bionic->id;
            if( it->has_fault( fault_bionic_nonsterile ) ) {
                // NOLINTNEXTLINE(cata-text-style): single space after the period for symmetry
                return _( "/!\\ CBM is not sterile. /!\\ Please use autoclave or other methods to sterilize." );
            } else if( pa.has_bionic( bid ) ) {
                return _( "CBM already installed" );
            } else if( !pa.can_install_cbm_on_bp( get_occupied_bodyparts( bid ) ) ) {
                return _( "CBM not compatible with patient's body." );
            } else if( bid->upgraded_bionic &&
                       !pa.has_bionic( bid->upgraded_bionic ) &&
                       it->is_upgrade() ) {
                return _( "No base version installed" );
            } else if( std::any_of( bid->available_upgrades.begin(),
                                    bid->available_upgrades.end(),
                                    std::bind( &player::has_bionic, &pa,
                                               std::placeholders::_1 ) ) ) {
                return _( "Superior version installed" );
            } else if( pa.is_npc() && !bid->has_flag( flag_BIONIC_NPC_USABLE ) ) {
                return _( "CBM not compatible with patient" );
            } else if( units::energy_max - pa.get_max_power_level() < bid->capacity ) {
                return _( "Max power capacity already reached" );
            } else if( !p.has_enough_anesth( itemtype, pa ) ) {
                const int weight = 7;
                const int duration = loc.get_item()->type->bionic->difficulty * 2;
                return string_format( _( "%i mL" ), anesthetic_requirement( duration * weight ) );
            }
            return std::string();
        }
References _, anonymous_namespace{game_inventory.cpp}::anesthetic_requirement(), bionic_data::available_upgrades, itype::bionic, Character::can_install_cbm_on_bp(), bionic_data::capacity, units::energy_max, fault_bionic_nonsterile, flag_BIONIC_NPC_USABLE, item_location::get_item(), Character::get_max_power_level(), get_occupied_bodyparts(), Character::has_bionic(), Character::has_enough_anesth(), item::has_fault(), bionic_data::has_flag(), player::is_npc(), item::is_upgrade(), p, pa, string_format(), item::type, and bionic_data::upgraded_bionic.
get_failure_chance()
std::string bionic_install_preset::get_failure_chance (const item_location & loc) inline private
Definition at line 1851 of file game_inventory.cpp.
{
            const int difficulty = loc.get_item()->type->bionic->difficulty;
            int chance_of_failure = 100;
            player &installer = p;
            std::vector<const item *> install_programs = p.crafting_inventory().items_with( [loc](
                        const item & it ) -> bool { return it.typeId() == loc.get_item()->type->bionic->installation_data; } );
            const bool has_install_program = !install_programs.empty();
            const int adjusted_skill = installer.bionics_adjusted_skill( skill_firstaid,
                                       skill_computer,
                                       skill_electronics,
                                       -1 );
            if( g->u.has_trait( trait_DEBUG_BIONICS ) ) {
                chance_of_failure = 0;
            } else {
                chance_of_failure = has_install_program ? 1 : 100 - bionic_manip_cos( adjusted_skill, difficulty );
            }
            return string_format( has_install_program ? _( "<color_white>*</color> %i%%" ) : _( "%i%%" ),
                                  chance_of_failure );
        }
References _, itype::bionic, bionic_manip_cos(), Character::bionics_adjusted_skill(), Character::crafting_inventory(), g, item_location::get_item(), visitable< T >::items_with(), p, skill_computer, skill_electronics, skill_firstaid, string_format(), trait_DEBUG_BIONICS, item::type, and item::typeId().
Referenced by bionic_install_preset().
get_operation_duration()
std::string bionic_install_preset::get_operation_duration (const item_location & loc) inline private
Definition at line 1844 of file game_inventory.cpp.
{
            const int difficulty = loc.get_item()->type->bionic->difficulty;
            // 20 minutes per bionic difficulty.
            return to_string( time_duration::from_minutes( difficulty * 20 ) );
        }
References itype::bionic, time_duration::from_minutes(), item_location::get_item(), to_string(), and item::type.
Referenced by bionic_install_preset().
is_shown()
bool bionic_install_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 1800 of file game_inventory.cpp.
{
            return loc->is_bionic();
        }
References item::is_bionic().
Member Data Documentation
p
player& bionic_install_preset::p protected
Definition at line 1839 of file game_inventory.cpp.
Referenced by get_denial(), and get_failure_chance().
pa
player& bionic_install_preset::pa protected
Definition at line 1840 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp