Cataclysm BN: mon_attack_effect_reader Class Reference
mon_attack_effect_reader Class Reference
Public Member Functions
mon_effect_data get_next (JsonIn &jin) const
template<typename C >
void erase_next (JsonIn &jin, C &container) const
Public Member Functions inherited from generic_typed_reader< mon_attack_effect_reader >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Detailed Description
Definition at line 667 of file monstergenerator.cpp.
Member Function Documentation
erase_next()
template<typename C > void mon_attack_effect_reader::erase_next (JsonIn & jin, C & container) const inline
Definition at line 675 of file monstergenerator.cpp.
{
            const efftype_id id = efftype_id( jin.get_string() );
            reader_detail::handler<C>().erase_if( container, [&id]( const mon_effect_data & e ) {
                return e.id == id;
            } );
        }
References efftype_id, JsonIn::get_string(), base_camps::id, and mon_effect_data::id.
get_next()
mon_effect_data mon_attack_effect_reader::get_next (JsonIn & jin) const inline
Definition at line 670 of file monstergenerator.cpp.
{
            JsonObject e = jin.get_object();
            return load_mon_effect_data( e );
        }
References JsonIn::get_object(), and load_mon_effect_data().
The documentation for this class was generated from the following file:
src/monstergenerator.cpp