Cataclysm BN: ter_furn_transform Class Reference
ter_furn_transform Class Reference
#include <magic_ter_furn_transform.h>
Public Member Functions
void add_all_messages (const Creature &critter, const tripoint &location) const
void add_all_messages (const map &m, const Creature &critter, const tripoint &location) const
void transform (const tripoint &location) const
void transform (map &m, const tripoint &location) const
void load (const JsonObject &jo, const std::string &)
bool is_valid () const
Static Public Member Functions
static void load_transform (const JsonObject &jo, const std::string &src)
static const std::vector< ter_furn_transform > & get_all ()
static void reset_all ()
Public Attributes
ter_furn_transform_id id
bool was_loaded = false
Private Member Functions
cata::optional< ter_str_id > next_ter (const ter_str_id &ter) const
cata::optional< ter_str_id > next_ter (const std::string &flag) const
cata::optional< furn_str_id > next_furn (const furn_str_id &furn) const
cata::optional< furn_str_id > next_furn (const std::string &flag) const
template<class T , class K >
cata::optional< ter_furn_data< T > > find_transform (const std::map< K, ter_furn_data< T > > &list, const K &key) const
template<class T , class K >
cata::optional< T > next (const std::map< K, ter_furn_data< T > > &list, const K &key) const
template<class T , class K >
bool add_message (const std::map< K, ter_furn_data< T > > &list, const K &key, const Creature &critter, const tripoint &location) const
Private Attributes
std::string fail_message
std::map< ter_str_id, ter_furn_data< ter_str_id > > ter_transform
std::map< std::string, ter_furn_data< ter_str_id > > ter_flag_transform
std::map< furn_str_id, ter_furn_data< furn_str_id > > furn_transform
std::map< std::string, ter_furn_data< furn_str_id > > furn_flag_transform
Detailed Description
Definition at line 38 of file magic_ter_furn_transform.h.
Member Function Documentation
add_all_messages() [1/2]
void ter_furn_transform::add_all_messages (const Creature & critter, const tripoint & location) const
Definition at line 179 of file magic_ter_fur_transform.cpp.
{
    add_all_messages( get_map(), critter, location );
}
References add_all_messages(), and get_map().
Referenced by add_all_messages().
add_all_messages() [2/2]
void ter_furn_transform::add_all_messages (const map & m, const Creature & critter, const tripoint & location) const
Definition at line 184 of file magic_ter_fur_transform.cpp.
{
    const ter_id ter_at_loc = m.ter( location );
    if( !add_message( ter_transform, ter_at_loc->id, critter, location ) ) {
        for( const std::pair<const std::string, ter_furn_data<ter_str_id>> &data : ter_flag_transform ) {
            if( data.second.has_msg() && ter_at_loc->has_flag( data.first ) ) {
                data.second.add_msg( critter );
                break;
            }
        }
    }
    const furn_id furn_at_loc = m.furn( location );
    if( !add_message( furn_transform, furn_at_loc->id, critter, location ) ) {
        for( const std::pair<const std::string, ter_furn_data<furn_str_id>> &data : furn_flag_transform ) {
            if( data.second.has_msg() && furn_at_loc->has_flag( data.first ) ) {
                data.second.add_msg( critter );
                break;
            }
        }
    }
}
References add_message(), map::furn(), furn_flag_transform, furn_transform, map_data_common_t::has_flag(), ter_t::id, furn_t::id, map::ter(), ter_flag_transform, and ter_transform.
add_message()
template<class T , class K > bool ter_furn_transform::add_message (const std::map< K, ter_furn_data< T > > & list, const K & key, const Creature & critter, const tripoint & location) const private
Definition at line 166 of file magic_ter_fur_transform.cpp.
{
    const cata::optional<ter_furn_data<T>> result = find_transform( list, key );
    if( result && !result->has_msg() ) {
        if( critter.sees( location ) ) {
            result->add_msg( critter );
        }
        return true;
    }
    return false;
}
References find_transform(), and Creature::sees().
Referenced by add_all_messages().
find_transform()
template<class T , class K > cata::optional< ter_furn_data< T > > ter_furn_transform::find_transform (const std::map< K, ter_furn_data< T > > & list, const K & key) const private
Definition at line 124 of file magic_ter_fur_transform.cpp.
{
    const auto result_iter = list.find( key );
    if( result_iter == list.cend() ) {
        return cata::nullopt;
    }
    return result_iter->second;
}
References cata::nullopt.
Referenced by add_message(), and next().
get_all()
const std::vector< ter_furn_transform > & ter_furn_transform::get_all () static
Definition at line 54 of file magic_ter_fur_transform.cpp.
{
    return ter_furn_transform_factory.get_all();
}
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
is_valid()
bool ter_furn_transform::is_valid () const
Definition at line 49 of file magic_ter_fur_transform.cpp.
{
    return ter_furn_transform_factory.is_valid( this->id );
}
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
load()
void ter_furn_transform::load (const JsonObject & jo, const std::string &)
Definition at line 85 of file magic_ter_fur_transform.cpp.
{
    std::string input;
    mandatory( jo, was_loaded, "id", input );
    id = ter_furn_transform_id( input );
    optional( jo, was_loaded, "fail_message", fail_message, "" );
    if( jo.has_member( "terrain" ) ) {
        for( JsonObject ter_obj : jo.get_array( "terrain" ) ) {
            ter_furn_data<ter_str_id> cur_results = ter_furn_data<ter_str_id>();
            cur_results.load( ter_obj );
            for( const std::string valid_terrain : ter_obj.get_array( "valid_terrain" ) ) {
                ter_transform.emplace( ter_str_id( valid_terrain ), cur_results );
            }
            for( const std::string valid_terrain : ter_obj.get_array( "valid_flags" ) ) {
                ter_flag_transform.emplace( valid_terrain, cur_results );
            }
        }
    }
    if( jo.has_member( "furniture" ) ) {
        for( JsonObject furn_obj : jo.get_array( "furniture" ) ) {
            ter_furn_data<furn_str_id> cur_results = ter_furn_data<furn_str_id>();
            cur_results.load( furn_obj );
            for( const std::string valid_furn : furn_obj.get_array( "valid_furniture" ) ) {
                furn_transform.emplace( furn_str_id( valid_furn ), cur_results );
            }
            for( const std::string valid_terrain : furn_obj.get_array( "valid_flags" ) ) {
                furn_flag_transform.emplace( valid_terrain, cur_results );
            }
        }
    }
}
References fail_message, furn_flag_transform, furn_transform, JsonObject::get_array(), JsonObject::has_member(), ter_furn_data< T >::load(), mandatory(), optional(), ter_flag_transform, ter_transform, and was_loaded.
load_transform()
void ter_furn_transform::load_transform (const JsonObject & jo, const std::string & src) static
Definition at line 39 of file magic_ter_fur_transform.cpp.
{
    ter_furn_transform_factory.load( jo, src );
}
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
Referenced by DynamicDataLoader::initialize().
next()
template<class T , class K > cata::optional< T > ter_furn_transform::next (const std::map< K, ter_furn_data< T > > & list, const K & key) const private
Definition at line 135 of file magic_ter_fur_transform.cpp.
{
    const cata::optional<ter_furn_data<T>> result = find_transform( list, key );
    if( result ) {
        return result->pick();
    }
    return cata::nullopt;
}
References find_transform(), and cata::nullopt.
Referenced by next_furn(), and next_ter().
next_furn() [1/2]
cata::optional< furn_str_id > ter_furn_transform::next_furn (const furn_str_id & furn) const private
Definition at line 155 of file magic_ter_fur_transform.cpp.
{
    return next( furn_transform, furn );
}
References furn_transform, and next().
Referenced by transform().
next_furn() [2/2]
cata::optional< furn_str_id > ter_furn_transform::next_furn (const std::string & flag) const private
Definition at line 160 of file magic_ter_fur_transform.cpp.
{
    return next( furn_flag_transform, flag );
}
References furn_flag_transform, and next().
next_ter() [1/2]
cata::optional< ter_str_id > ter_furn_transform::next_ter (const std::string & flag) const private
Definition at line 150 of file magic_ter_fur_transform.cpp.
{
    return next( ter_flag_transform, flag );
}
References next(), and ter_flag_transform.
next_ter() [2/2]
cata::optional< ter_str_id > ter_furn_transform::next_ter (const ter_str_id & ter) const private
Definition at line 145 of file magic_ter_fur_transform.cpp.
{
    return next( ter_transform, ter );
}
References next(), and ter_transform.
Referenced by transform().
reset_all()
void ter_furn_transform::reset_all () static
Definition at line 44 of file magic_ter_fur_transform.cpp.
{
    ter_furn_transform_factory.reset();
}
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
Referenced by DynamicDataLoader::unload_data().
transform() [1/2]
void ter_furn_transform::transform (const tripoint & location) const
Definition at line 208 of file magic_ter_fur_transform.cpp.
{
    transform( get_map(), location );
}
References get_map(), and transform().
Referenced by transform().
transform() [2/2]
void ter_furn_transform::transform (map & m, const tripoint & location) const
Definition at line 213 of file magic_ter_fur_transform.cpp.
{
    const ter_id ter_at_loc = m.ter( location );
    cata::optional<ter_str_id> ter_potential = next_ter( ter_at_loc->id );
    const furn_id furn_at_loc = m.furn( location );
    cata::optional<furn_str_id> furn_potential = next_furn( furn_at_loc->id );
    if( !ter_potential ) {
        for( const std::pair<const std::string, ter_furn_data<ter_str_id>> &flag_result :
             ter_flag_transform )             {
            if( ter_at_loc->has_flag( flag_result.first ) ) {
                ter_potential = next_ter( flag_result.first );
                if( ter_potential ) {
                    break;
                }
            }
        }
    }
    if( !furn_potential ) {
        for( const std::pair<const std::string, ter_furn_data<furn_str_id>> &flag_result :
             furn_flag_transform ) {
            if( furn_at_loc->has_flag( flag_result.first ) ) {
                furn_potential = next_furn( flag_result.first );
                if( furn_potential ) {
                    break;
                }
            }
        }
    }
    if( ter_potential ) {
        m.ter_set( location, *ter_potential );
    }
    if( furn_potential ) {
        m.furn_set( location, *furn_potential );
    }
}
References map::furn(), furn_flag_transform, map::furn_set(), map_data_common_t::has_flag(), ter_t::id, furn_t::id, next_furn(), next_ter(), map::ter(), ter_flag_transform, and map::ter_set().
Member Data Documentation
fail_message
std::string ter_furn_transform::fail_message private
Definition at line 43 of file magic_ter_furn_transform.h.
Referenced by load().
furn_flag_transform
std::map<std::string, ter_furn_data<furn_str_id> > ter_furn_transform::furn_flag_transform private
Definition at line 49 of file magic_ter_furn_transform.h.
Referenced by add_all_messages(), load(), next_furn(), and transform().
furn_transform
std::map<furn_str_id, ter_furn_data<furn_str_id> > ter_furn_transform::furn_transform private
Definition at line 48 of file magic_ter_furn_transform.h.
Referenced by add_all_messages(), load(), and next_furn().
id
ter_furn_transform_id ter_furn_transform::id
Definition at line 70 of file magic_ter_furn_transform.h.
ter_flag_transform
std::map<std::string, ter_furn_data<ter_str_id> > ter_furn_transform::ter_flag_transform private
Definition at line 46 of file magic_ter_furn_transform.h.
Referenced by add_all_messages(), load(), next_ter(), and transform().
ter_transform
std::map<ter_str_id, ter_furn_data<ter_str_id> > ter_furn_transform::ter_transform private
Definition at line 45 of file magic_ter_furn_transform.h.
Referenced by add_all_messages(), load(), and next_ter().
was_loaded
bool ter_furn_transform::was_loaded = false
Definition at line 71 of file magic_ter_furn_transform.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/magic_ter_furn_transform.h
src/magic_ter_fur_transform.cpp