Cataclysm BN: consistency_report Class Reference
consistency_report Class Reference
Helper class for aggregating warnings reported during consistency check of some object with id.
#include <consistency_report.h>
Public Member Functions
consistency_report ()=default
~consistency_report ()=default
void warn (const char *msg)
void warn (const std::string &msg)
template<typename ... Args>
void warn (const std::string &format, Args &&... args)
template<typename ... Args>
void warn (const char *format, Args &&... args)
bool is_empty () const
std::string format (const std::string &data_type, const std::string &id) const
Format the report for debugmsg.
Private Attributes
std::vector< std::string > warns
Detailed Description
Helper class for aggregating warnings reported during consistency check of some object with id.
Definition at line 14 of file consistency_report.h.
Constructor & Destructor Documentation
consistency_report()
consistency_report::consistency_report () default
~consistency_report()
consistency_report::~consistency_report () default
Member Function Documentation
format()
std::string consistency_report::format (const std::string & data_type, const std::string & id) const inline
Format the report for debugmsg.
Definition at line 46 of file consistency_report.h.
{
            std::string ret = string_format( "Warnings for %s \"%s\":", data_type, id );
            for( const std::string &s : warns ) {
                ret += '\n';
                ret += s;
            }
            return ret;
        }
References cata::hash64_detail::ret, string_format(), and warns.
Referenced by bionic_data::check(), construction::check(), construction_sequence::check(), and warn().
is_empty()
bool consistency_report::is_empty () const inline
Definition at line 41 of file consistency_report.h.
{
            return warns.empty();
        }
References warns.
Referenced by bionic_data::check(), construction::check(), and construction_sequence::check().
warn() [1/4]
template<typename ... Args> void consistency_report::warn (const char * format, Args &&... args) inline
Definition at line 37 of file consistency_report.h.
{
            warns.push_back( string_format( format, std::forward<Args>( args )... ) );
        }
References format(), string_format(), and warns.
warn() [2/4]
void consistency_report::warn (const char * msg) inline
Definition at line 23 of file consistency_report.h.
{
            warns.push_back( msg );
        }
References warns.
Referenced by bionic_data::check(), construction::check(), and construction_sequence::check().
warn() [3/4]
template<typename ... Args> void consistency_report::warn (const std::string & format, Args &&... args) inline
Definition at line 32 of file consistency_report.h.
{
            warns.push_back( string_format( format, std::forward<Args>( args )... ) );
        }
References format(), string_format(), and warns.
warn() [4/4]
void consistency_report::warn (const std::string & msg) inline
Definition at line 27 of file consistency_report.h.
{
            warns.push_back( msg );
        }
References warns.
Member Data Documentation
warns
std::vector<std::string> consistency_report::warns private
Definition at line 17 of file consistency_report.h.
Referenced by format(), is_empty(), and warn().
The documentation for this class was generated from the following file:
src/consistency_report.h