Cataclysm BN: leap_actor Class Reference
leap_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
leap_actor ()=default
~leap_actor () override=default
void load_internal (const JsonObject &obj, const std::string &src) override
bool call (monster &) const override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
float max_range
float min_range
bool allow_no_target
int move_cost
float min_consider_range
float max_consider_range
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 25 of file mattack_actors.h.
Constructor & Destructor Documentation
leap_actor()
leap_actor::leap_actor () default
~leap_actor()
leap_actor::~leap_actor () override default
Member Function Documentation
call()
bool leap_actor::call (monster & z) const override virtual
Implements mattack_actor.
Definition at line 74 of file mattack_actors.cpp.
{
    if( !z.can_act() || !z.move_effects( false ) ) {
        return false;
    }
    std::vector<tripoint> options;
    tripoint target = z.move_target();
    float best_float = trigdist ? trig_dist( z.pos(), target ) : square_dist( z.pos(), target );
    if( best_float < min_consider_range || best_float > max_consider_range ) {
        return false;
    }
    // We wanted the float for range check
    // int here will make the jumps more random
    int best = std::numeric_limits<int>::max();
    if( !allow_no_target && z.attack_target() == nullptr ) {
        return false;
    }
    map &here = get_map();
    std::multimap<int, tripoint> candidates;
    for( const tripoint &candidate : here.points_in_radius( z.pos(), max_range ) ) {
        if( candidate == z.pos() ) {
            continue;
        }
        float leap_dist = trigdist ? trig_dist( z.pos(), candidate ) :
                          square_dist( z.pos(), candidate );
        if( leap_dist > max_range || leap_dist < min_range ) {
            continue;
        }
        int candidate_dist = rl_dist( candidate, target );
        if( candidate_dist >= best_float ) {
            continue;
        }
        candidates.emplace( candidate_dist, candidate );
    }
    for( const auto &candidate : candidates ) {
        const int &cur_dist = candidate.first;
        const tripoint &dest = candidate.second;
        if( cur_dist > best ) {
            break;
        }
        if( !z.sees( dest ) ) {
            continue;
        }
        if( !g->is_empty( dest ) ) {
            continue;
        }
        bool blocked_path = false;
        // check if monster has a clear path to the proposed point
        std::vector<tripoint> line = here.find_clear_path( z.pos(), dest );
        tripoint prev_point = z.pos();
        for( auto &i : line ) {
            if( here.impassable( i ) || here.obstructed_by_vehicle_rotation( prev_point, i ) ) {
                blocked_path = true;
                break;
            }
            prev_point = i;
        }
        // don't leap into water if you could drown (#38038)
        if( z.is_aquatic_danger( dest ) ) {
            blocked_path = true;
        }
        if( blocked_path ) {
            continue;
        }
        options.push_back( dest );
        best = cur_dist;
    }
    if( options.empty() ) {
        return false;    // Nowhere to leap!
    }
    z.moves -= move_cost;
    const tripoint chosen = random_entry( options );
    bool seen = g->u.sees( z ); // We can see them jump...
    z.setpos( chosen );
    seen |= g->u.sees( z ); // ... or we can see them land
    if( seen ) {
        add_msg( _( "The %s leaps!" ), z.name() );
    }
    return true;
}
References _, add_msg(), allow_no_target, monster::attack_target(), monster::can_act(), map::find_clear_path(), g, get_map(), map::impassable(), monster::is_aquatic_danger(), line(), max_consider_range, max_range, min_range, move_cost, monster::move_effects(), monster::move_target(), Creature::moves, monster::name(), map::obstructed_by_vehicle_rotation(), PATH_INFO::options(), map::points_in_radius(), monster::pos(), random_entry(), rl_dist(), Creature::sees(), monster::setpos(), square_dist(), trig_dist(), and trigdist.
clone()
std::unique_ptr< mattack_actor > leap_actor::clone () const override virtual
Implements mattack_actor.
Definition at line 69 of file mattack_actors.cpp.
{
    return std::make_unique<leap_actor>( *this );
}
load_internal()
void leap_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Implements mattack_actor.
Definition at line 57 of file mattack_actors.cpp.
{
    // Mandatory:
    max_range = obj.get_float( "max_range" );
    // Optional:
    min_range = obj.get_float( "min_range", 1.0f );
    allow_no_target = obj.get_bool( "allow_no_target", false );
    move_cost = obj.get_int( "move_cost", 150 );
    min_consider_range = obj.get_float( "min_consider_range", 0.0f );
    max_consider_range = obj.get_float( "max_consider_range", 200.0f );
}
References allow_no_target, JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), max_consider_range, max_range, min_consider_range, min_range, and move_cost.
Member Data Documentation
allow_no_target
bool leap_actor::allow_no_target
Definition at line 32 of file mattack_actors.h.
Referenced by call(), and load_internal().
max_consider_range
float leap_actor::max_consider_range
Definition at line 37 of file mattack_actors.h.
Referenced by call(), and load_internal().
max_range
float leap_actor::max_range
Definition at line 28 of file mattack_actors.h.
Referenced by call(), and load_internal().
min_consider_range
float leap_actor::min_consider_range
Definition at line 35 of file mattack_actors.h.
Referenced by load_internal().
min_range
float leap_actor::min_range
Definition at line 30 of file mattack_actors.h.
Referenced by call(), and load_internal().
move_cost
int leap_actor::move_cost
Definition at line 33 of file mattack_actors.h.
Referenced by call(), and load_internal().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp