Cataclysm BN: event_bus Class Reference
event_bus Class Reference
#include <event_bus.h>
Public Member Functions
event_bus ()=default
event_bus (const event_bus &)=delete
event_bus & operator= (const event_bus &)=delete
~event_bus ()
void subscribe (event_subscriber *)
void unsubscribe (event_subscriber *)
void send (const cata::event &) const
template<event_type Type, typename... Args>
void send (Args &&... args) const
Private Attributes
std::vector< event_subscriber * > subscribers
Detailed Description
Definition at line 27 of file event_bus.h.
Constructor & Destructor Documentation
event_bus() [1/2]
event_bus::event_bus () default
event_bus() [2/2]
event_bus::event_bus (const event_bus &) delete
~event_bus()
event_bus::~event_bus ()
Definition at line 32 of file event_bus.cpp.
{
    while( !subscribers.empty() ) {
        unsubscribe( subscribers.front() );
    }
}
References subscribers, and unsubscribe().
Member Function Documentation
operator=()
event_bus & event_bus::operator= (const event_bus &) delete
send() [1/2]
template<event_type Type, typename... Args> void event_bus::send (Args &&... args) const inline
Definition at line 39 of file event_bus.h.
{
            send( cata::event::make<Type>( std::forward<Args>( args )... ) );
        }
References send().
send() [2/2]
void event_bus::send (const cata::event & e) const
Definition at line 58 of file event_bus.cpp.
{
    for( event_subscriber *s : subscribers ) {
        s->notify( e );
    }
}
References subscribers.
Referenced by Character::apply_damage(), game::cleanup_at_end(), iexamine::pedestal_wyrm(), send(), and trap::trigger().
subscribe()
void event_bus::subscribe (event_subscriber * s)
Definition at line 39 of file event_bus.cpp.
{
    if( get_option<bool>( "ENABLE_EVENTS" ) ) {
        subscribers.push_back( s );
        s->on_subscribe( this );
    }
}
References event_subscriber::on_subscribe(), and subscribers.
Referenced by game::game().
unsubscribe()
void event_bus::unsubscribe (event_subscriber * s)
Definition at line 47 of file event_bus.cpp.
{
    auto it = std::find( subscribers.begin(), subscribers.end(), s );
    if( it == subscribers.end() ) {
        debugmsg( "Trying to remove subscriber that isn't there" );
    } else {
        ( *it )->on_unsubscribe( this );
        subscribers.erase( it );
    }
}
References debugmsg, detail::find(), and subscribers.
Referenced by ~event_bus(), and event_subscriber::~event_subscriber().
Member Data Documentation
subscribers
std::vector<event_subscriber *> event_bus::subscribers private
Definition at line 43 of file event_bus.h.
Referenced by send(), subscribe(), unsubscribe(), and ~event_bus().
The documentation for this class was generated from the following files:
src/event_bus.h
src/event_bus.cpp