Cataclysm BN: detail::dynamic_arg_list Class Reference
detail::dynamic_arg_list Class Reference
#include <fmtlib_core.h>
Classes
struct node
struct typed_node
Public Member Functions
template<typename T , typename Arg >
const T & push (const Arg &arg)
Private Attributes
std::unique_ptr< node<> > head_
Detailed Description
Definition at line 1653 of file fmtlib_core.h.
Member Function Documentation
push()
template<typename T , typename Arg > const T & detail::dynamic_arg_list::push (const Arg & arg) inline
Definition at line 1677 of file fmtlib_core.h.
{
            auto new_node = std::unique_ptr<typed_node<T>>( new typed_node<T>( arg ) );
            auto &value = new_node->value;
            new_node->next = std::move( head_ );
            head_ = std::move( new_node );
            return value;
        }
References arg(), head_, avatar_action::move(), and detail::value< Context >::value().
Referenced by dynamic_format_arg_store< Context >::push_back().
Member Data Documentation
head_
std::unique_ptr<node<> > detail::dynamic_arg_list::head_ private
Definition at line 1674 of file fmtlib_core.h.
Referenced by push().
The documentation for this class was generated from the following file:
src/fmtlib_core.h