Cataclysm BN: nc_color Class Reference
nc_color Class Reference
#include <color.h>
Public Member Functions
nc_color ()
int to_color_pair_index () const
operator int () const
nc_color bold () const
bool is_bold () const
nc_color blink () const
bool is_blink () const
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Static Public Member Functions
static nc_color from_color_pair_index (int index)
Private Member Functions
nc_color (const int a)
Private Attributes
int attribute_value
Detailed Description
Definition at line 348 of file color.h.
Constructor & Destructor Documentation
nc_color() [1/2]
nc_color::nc_color (const int a) inline private
Definition at line 354 of file color.h.
: attribute_value(a) { }
nc_color() [2/2]
nc_color::nc_color () inline
Definition at line 357 of file color.h.
: attribute_value(0) { }
Referenced by blink(), bold(), and from_color_pair_index().
Member Function Documentation
blink()
nc_color nc_color::blink () const
Definition at line 402 of file ncurses_def.cpp.
{
    return nc_color( attribute_value | A_BLINK );
}
References attribute_value, and nc_color().
bold()
nc_color nc_color::bold () const
Definition at line 392 of file ncurses_def.cpp.
{
    return nc_color( attribute_value | A_BOLD );
}
References attribute_value, and nc_color().
deserialize()
void nc_color::deserialize (JsonIn & jsin)
Definition at line 30 of file color.cpp.
{
    if( jsin.test_int() ) {
        attribute_value = jsin.get_int();
    } else if( jsin.test_string() ) {
        const nc_color out = color_from_string( jsin.get_string() );
        if( out == c_unset ) {
            jsin.error( "invalid color name" );
        }
        attribute_value = out.attribute_value;
    } else {
        jsin.error( "expected color string or legacy int identifier" );
    }
}
References attribute_value, c_unset, color_from_string(), JsonIn::error(), JsonIn::get_int(), JsonIn::get_string(), JsonIn::test_int(), and JsonIn::test_string().
from_color_pair_index()
nc_color nc_color::from_color_pair_index (int index) static
Definition at line 382 of file ncurses_def.cpp.
{
    return nc_color( COLOR_PAIR( index ) );
}
References nc_color().
Referenced by color_manager::load_default().
is_blink()
bool nc_color::is_blink () const
Definition at line 407 of file ncurses_def.cpp.
{
    return attribute_value & A_BLINK;
}
References attribute_value.
is_bold()
bool nc_color::is_bold () const
Definition at line 397 of file ncurses_def.cpp.
{
    return attribute_value & A_BOLD;
}
References attribute_value.
operator int()
nc_color::operator int () const inline
Definition at line 365 of file color.h.
{
            return attribute_value;
        }
References attribute_value.
serialize()
void nc_color::serialize (JsonOut & jsout) const
Definition at line 25 of file color.cpp.
{
    jsout.write( attribute_value );
}
References attribute_value, and JsonOut::write().
to_color_pair_index()
int nc_color::to_color_pair_index () const
Definition at line 387 of file ncurses_def.cpp.
{
    return PAIR_NUMBER( attribute_value );
}
References attribute_value.
Member Data Documentation
attribute_value
int nc_color::attribute_value private
Definition at line 352 of file color.h.
Referenced by blink(), bold(), deserialize(), is_blink(), is_bold(), operator int(), serialize(), and to_color_pair_index().
The documentation for this class was generated from the following files:
src/color.h
src/color.cpp
src/ncurses_def.cpp