Cataclysm BN: cata_libintl::trans_catalogue Class Reference
cata_libintl::trans_catalogue Class Reference
Translation catalogue.
#include <cata_libintl.h>
Classes
struct catalogue_plurals_info
struct string_descr
Public Member Functions
u32 get_num_strings () const
Number of entries in the catalogue.
const char * get_nth_translation (u32 n) const
Get singular translated string of given entry.
const char * get_nth_pl_translation (u32 n, size_t num) const
Get correct plural translated string of given entry for given number.
const char * get_nth_orig_string (u32 n) const
Get original msgid (with msgctxt) of given entry.
bool check_nth_translation_has_plf (u32 n) const
Check whether translated string contains plural forms.
Static Public Member Functions
static trans_catalogue load_from_file (const std::string &file_path)
Load translation catalogue from given MO file.
static trans_catalogue load_from_memory (std::string mo_file)
Load translation catalogue from given MO file in memory.
Private Types
using meta_headers = std::vector< std::string >
Private Member Functions
trans_catalogue (std::string buffer)
void set_buffer (std::string buffer)
u32 buf_size () const
u8 get_u8 (u32 offs) const
u8 get_u8_unsafe (u32 offs) const
u32 get_u32 (u32 offs) const
u32 get_u32_unsafe (u32 offs) const
string_descr get_string_descr (u32 offs) const
string_descr get_string_descr_unsafe (u32 offs) const
const char * offs_to_cstr (u32 offs) const
void process_file_header ()
void check_string_terminators ()
void check_string_plurals ()
std::string get_metadata () const
Static Private Member Functions
static void check_encoding (const meta_headers &headers)
static catalogue_plurals_info parse_plf_header (const meta_headers &headers)
Private Attributes
bool is_little_endian = true
std::string buffer
catalogue_plurals_info plurals
u32 number_of_strings = 0
u32 offs_orig_table = 0
u32 offs_trans_table = 0
Detailed Description
Translation catalogue.
Corresponds to single MO file.
Definition at line 81 of file cata_libintl.h.
Member Typedef Documentation
meta_headers
using cata_libintl::trans_catalogue::meta_headers = std::vector<std::string> private
Definition at line 93 of file cata_libintl.h.
Constructor & Destructor Documentation
trans_catalogue()
cata_libintl::trans_catalogue::trans_catalogue (std::string buffer) explicit private
Definition at line 662 of file cata_libintl.cpp.
{
    set_buffer( std::move( buffer ) );
    process_file_header();
    check_string_terminators();
    meta_headers headers = string_split( get_metadata(), '\n' );
    check_encoding( headers );
    this->plurals = parse_plf_header( headers );
    check_string_plurals();
}
References buffer, check_encoding(), check_string_plurals(), check_string_terminators(), get_metadata(), avatar_action::move(), parse_plf_header(), plurals, process_file_header(), set_buffer(), and string_split().
Referenced by load_from_memory().
Member Function Documentation
buf_size()
u32 cata_libintl::trans_catalogue::buf_size () const inline private
Definition at line 111 of file cata_libintl.h.
{
            return static_cast<u32>( buffer.size() );
        }
References buffer.
Referenced by check_string_terminators(), get_u32(), and get_u8().
check_encoding()
void cata_libintl::trans_catalogue::check_encoding (const meta_headers & headers) static private
Definition at line 537 of file cata_libintl.cpp.
{
    // HACK: The checks here are rather crude and don't account for
    //       possible extra spaces or wrong capitalization.
    //       However, we don't expect people to manually configure
    //       these headers (there're tons of software for that),
    //       and the strings here match output of our own scripts and
    //       Poedit/xgettext/Transifex, so leaving as is should be fine.
    {
        bool found = false;
        for( const std::string &entry : headers ) {
            if( !string_starts_with( entry, "Content-Type:" ) ) {
                continue;
            }
            found = true;
            static const std::string expected = "Content-Type: text/plain; charset=UTF-8";
            if( entry != expected ) {
                std::string e =
                    string_format( "unrecognized value in Content-Type header (wrong charset?). Expected \"%s\"",
                                   expected );
                throw std::runtime_error( e );
            }
            break;
        }
        if( !found ) {
            throw std::runtime_error( "failed to find Content-Type header" );
        }
    }
    {
        bool found = false;
        for( const std::string &entry : headers ) {
            if( !string_starts_with( entry, "Content-Transfer-Encoding:" ) ) {
                continue;
            }
            found = true;
            static const std::string expected = "Content-Transfer-Encoding: 8bit";
            if( entry != expected ) {
                std::string e =
                    string_format( "unrecognized value in Content-Transfer-Encoding header.  Expected \"%s\"",
                                   expected );
                throw std::runtime_error( e );
            }
            break;
        }
        if( !found ) {
            throw std::runtime_error( "failed to find Content-Transfer-Encoding header" );
        }
    }
}
References string_format(), and string_starts_with().
Referenced by trans_catalogue().
check_nth_translation_has_plf()
bool cata_libintl::trans_catalogue::check_nth_translation_has_plf (u32 n) const
Check whether translated string contains plural forms.
Definition at line 676 of file cata_libintl.cpp.
{
    u32 descr_offs = offs_trans_table + n * MO_STRING_DESCR_SIZE;
    string_descr r = get_string_descr_unsafe( descr_offs );
    for( u32 offs = r.offset; offs < r.offset + r.length; offs++ ) {
        if( get_u8_unsafe( offs ) == PLF_SEPARATOR ) {
            return true;
        }
    }
    return false;
}
References get_string_descr_unsafe(), get_u8_unsafe(), cata_libintl::trans_catalogue::string_descr::length, cata_libintl::MO_STRING_DESCR_SIZE, offs_trans_table, cata_libintl::trans_catalogue::string_descr::offset, and cata_libintl::PLF_SEPARATOR.
Referenced by cata_libintl::trans_library::build_string_table().
check_string_plurals()
void cata_libintl::trans_catalogue::check_string_plurals () private
Definition at line 497 of file cata_libintl.cpp.
{
    // Skip metadata (the 0th entry)
    for( u32 i = 1; i < number_of_strings; i++ ) {
        string_descr info = get_string_descr_unsafe( offs_orig_table + i * MO_STRING_DESCR_SIZE );
        // Check for null byte - msgid/msgid_plural separator
        bool has_plurals = false;
        for( u32 j = info.offset; j < info.offset + info.length; j++ ) {
            if( get_u8_unsafe( j ) == 0 ) {
                has_plurals = true;
                break;
            }
        }
        if( !has_plurals ) {
            continue;
        }
        // Count null bytes - each plural form is a null-terminated string (including last one)
        u32 offs_tr = offs_trans_table + i * MO_STRING_DESCR_SIZE;
        string_descr info_tr = get_string_descr_unsafe( offs_tr );
        size_t plural_forms = 0;
        for( u32 j = info_tr.offset; j <= info_tr.offset + info_tr.length; j++ ) {
            if( get_u8_unsafe( j ) == PLF_SEPARATOR ) {
                plural_forms += 1;
            }
        }
        // Number of plural forms should match the number specified in metadata
        if( plural_forms != this->plurals.num ) {
            std::string e = string_format(
                                "string_descr at offs %#x: expected %d plural forms, got %d",
                                offs_tr, this->plurals.num, plural_forms
                            );
            throw std::runtime_error( e );
        }
    }
}
References get_string_descr_unsafe(), get_u8_unsafe(), cata_libintl::trans_catalogue::string_descr::length, cata_libintl::MO_STRING_DESCR_SIZE, cata_libintl::trans_catalogue::catalogue_plurals_info::num, number_of_strings, offs_orig_table, offs_trans_table, cata_libintl::trans_catalogue::string_descr::offset, cata_libintl::PLF_SEPARATOR, plurals, and string_format().
Referenced by trans_catalogue().
check_string_terminators()
void cata_libintl::trans_catalogue::check_string_terminators () private
Definition at line 468 of file cata_libintl.cpp.
{
    const auto check_string = [this]( u32 offs ) {
        // Check that string with its null terminator (not included in string length)
        // does not extend beyond file boundaries.
        string_descr s = get_string_descr( offs );
        if( s.offset + s.length + 1 > buf_size() ) {
            std::string e = string_format(
                                "string_descr at offs %#x: extends beyond EOF (len:%#x offs:%#x fsize:%#x)",
                                offs, s.length, s.offset, buf_size()
                            );
            throw std::runtime_error( e );
        }
        // Also check for existence of the null byte.
        u8 terminator = get_u8( s.offset + s.length );
        if( terminator != 0 ) {
            std::string e = string_format(
                                "string_descr at offs %#x: missing null terminator",
                                offs
                            );
            throw std::runtime_error( e );
        }
    };
    for( u32 i = 0; i < number_of_strings; i++ ) {
        check_string( offs_orig_table + i * MO_STRING_DESCR_SIZE );
        check_string( offs_trans_table + i * MO_STRING_DESCR_SIZE );
    }
}
References buf_size(), get_string_descr(), get_u8(), cata_libintl::trans_catalogue::string_descr::length, cata_libintl::MO_STRING_DESCR_SIZE, number_of_strings, offs_orig_table, offs_trans_table, cata_libintl::trans_catalogue::string_descr::offset, and string_format().
Referenced by trans_catalogue().
get_metadata()
std::string cata_libintl::trans_catalogue::get_metadata () const private
Definition at line 417 of file cata_libintl.cpp.
{
    // We're looking for a string with empty msgid and absent msgctxt and msgid_pl.
    // Since the strings are sorted in lexicographical order, this will be the first string.
    constexpr u32 METADATA_STRING_LEN = 0;
    string_descr k = get_string_descr_unsafe( offs_orig_table );
    if( k.length != METADATA_STRING_LEN ) {
        std::string e = string_format(
                            "invalid metadata entry (expected length %#x, got %#x)",
                            METADATA_STRING_LEN, k.length
                        );
        throw std::runtime_error( e );
    }
    string_descr v = get_string_descr_unsafe( offs_trans_table );
    return std::string( offs_to_cstr( v.offset ) );
}
References get_string_descr_unsafe(), cata_libintl::trans_catalogue::string_descr::length, offs_orig_table, offs_to_cstr(), offs_trans_table, cata_libintl::trans_catalogue::string_descr::offset, and string_format().
Referenced by trans_catalogue().
get_nth_orig_string()
const char * cata_libintl::trans_catalogue::get_nth_orig_string (u32 n) const
Get original msgid (with msgctxt) of given entry.
Definition at line 690 of file cata_libintl.cpp.
{
    u32 descr_offs = offs_orig_table + n * MO_STRING_DESCR_SIZE;
    string_descr r = get_string_descr_unsafe( descr_offs );
    return offs_to_cstr( r.offset );
}
References get_string_descr_unsafe(), cata_libintl::MO_STRING_DESCR_SIZE, offs_orig_table, offs_to_cstr(), and cata_libintl::trans_catalogue::string_descr::offset.
Referenced by cata_libintl::trans_library::build_string_table().
get_nth_pl_translation()
const char * cata_libintl::trans_catalogue::get_nth_pl_translation (u32 n, size_t num) const
Get correct plural translated string of given entry for given number.
Definition at line 706 of file cata_libintl.cpp.
{
    u32 descr_offs = offs_trans_table + n * MO_STRING_DESCR_SIZE;
    string_descr r = get_string_descr_unsafe( descr_offs );
    size_t plf = plurals.expr->eval( num );
    if( plf == 0 || plf >= plurals.num ) {
        return offs_to_cstr( r.offset );
    }
    size_t curr_plf = 0;
    for( u32 offs = r.offset; offs < r.offset + r.length; offs++ ) {
        if( get_u8_unsafe( offs ) == PLF_SEPARATOR ) {
            curr_plf += 1;
            if( plf == curr_plf ) {
                return offs_to_cstr( offs + 1 );
            }
        }
    }
    return nullptr;
}
References cata_libintl::trans_catalogue::catalogue_plurals_info::expr, get_string_descr_unsafe(), get_u8_unsafe(), cata_libintl::trans_catalogue::string_descr::length, cata_libintl::MO_STRING_DESCR_SIZE, cata_libintl::trans_catalogue::catalogue_plurals_info::num, num, offs_to_cstr(), offs_trans_table, cata_libintl::trans_catalogue::string_descr::offset, cata_libintl::PLF_SEPARATOR, and plurals.
get_nth_translation()
const char * cata_libintl::trans_catalogue::get_nth_translation (u32 n) const
Get singular translated string of given entry.
Definition at line 698 of file cata_libintl.cpp.
{
    u32 descr_offs = offs_trans_table + n * MO_STRING_DESCR_SIZE;
    string_descr r = get_string_descr_unsafe( descr_offs );
    return offs_to_cstr( r.offset );
}
References get_string_descr_unsafe(), cata_libintl::MO_STRING_DESCR_SIZE, offs_to_cstr(), offs_trans_table, and cata_libintl::trans_catalogue::string_descr::offset.
get_num_strings()
u32 cata_libintl::trans_catalogue::get_num_strings () const inline
Number of entries in the catalogue.
Definition at line 162 of file cata_libintl.h.
{
            return number_of_strings;
        }
References number_of_strings.
Referenced by cata_libintl::trans_library::build_string_table().
get_string_descr()
trans_catalogue::string_descr cata_libintl::trans_catalogue::get_string_descr (u32 offs) const private
Definition at line 401 of file cata_libintl.cpp.
{
    string_descr ret;
    ret.length = get_u32( offs );
    ret.offset = get_u32( offs + 4 );
    return ret;
}
References get_u32(), and cata::hash64_detail::ret.
Referenced by check_string_terminators().
get_string_descr_unsafe()
trans_catalogue::string_descr cata_libintl::trans_catalogue::get_string_descr_unsafe (u32 offs) const private
Definition at line 409 of file cata_libintl.cpp.
{
    string_descr ret;
    ret.length = get_u32_unsafe( offs );
    ret.offset = get_u32_unsafe( offs + 4 );
    return ret;
}
References get_u32_unsafe(), and cata::hash64_detail::ret.
Referenced by check_nth_translation_has_plf(), check_string_plurals(), get_metadata(), get_nth_orig_string(), get_nth_pl_translation(), and get_nth_translation().
get_u32()
u32 cata_libintl::trans_catalogue::get_u32 (u32 offs) const private
Definition at line 392 of file cata_libintl.cpp.
{
    if( offs + 4 > buf_size() ) {
        std::string e = string_format( "tried get_u32() at offs %#x with file size %#x", offs, buf_size() );
        throw std::runtime_error( e );
    }
    return get_u32_unsafe( offs );
}
References buf_size(), get_u32_unsafe(), and string_format().
Referenced by get_string_descr(), and process_file_header().
get_u32_unsafe()
u32 cata_libintl::trans_catalogue::get_u32_unsafe (u32 offs) const inline private
Definition at line 121 of file cata_libintl.h.
{
            if( is_little_endian ) {
                return get_u8_unsafe( offs ) |
                       get_u8_unsafe( offs + 1 ) << 8 |
                       get_u8_unsafe( offs + 2 ) << 16 |
                       get_u8_unsafe( offs + 3 ) << 24;
            } else {
                return get_u8_unsafe( offs + 3 ) |
                       get_u8_unsafe( offs + 2 ) << 8 |
                       get_u8_unsafe( offs + 1 ) << 16 |
                       get_u8_unsafe( offs ) << 24;
            }
        }
References get_u8_unsafe(), and is_little_endian.
Referenced by get_string_descr_unsafe(), and get_u32().
get_u8()
u8 cata_libintl::trans_catalogue::get_u8 (u32 offs) const private
Definition at line 383 of file cata_libintl.cpp.
{
    if( offs + 1 > buf_size() ) {
        std::string e = string_format( "tried get_u8() at offs %#x with file size %#x", offs, buf_size() );
        throw std::runtime_error( e );
    }
    return get_u8_unsafe( offs );
}
References buf_size(), get_u8_unsafe(), and string_format().
Referenced by check_string_terminators().
get_u8_unsafe()
u8 cata_libintl::trans_catalogue::get_u8_unsafe (u32 offs) const inline private
Definition at line 116 of file cata_libintl.h.
{
            return static_cast<u8>( buffer[offs] );
        }
References buffer.
Referenced by check_nth_translation_has_plf(), check_string_plurals(), get_nth_pl_translation(), get_u32_unsafe(), and get_u8().
load_from_file()
trans_catalogue cata_libintl::trans_catalogue::load_from_file (const std::string & file_path) static
Load translation catalogue from given MO file.
Exceptions
std::runtime_error on failure.
Definition at line 364 of file cata_libintl.cpp.
{
    std::stringstream buffer;
    cata_ifstream file = std::move( cata_ifstream().mode( cata_ios_mode::binary ).open( file_path ) );
    if( !file.is_open() ) {
        throw std::runtime_error( "failed to open file" );
    }
    buffer << file->rdbuf();
    if( file.fail() ) {
        throw std::runtime_error( "failed to read file" );
    }
    return load_from_memory( buffer.str() );
}
References binary, buffer, file, load_from_memory(), avatar_action::move(), and open().
load_from_memory()
trans_catalogue cata_libintl::trans_catalogue::load_from_memory (std::string mo_file) static
Load translation catalogue from given MO file in memory.
Exceptions
std::runtime_error on failure.
Definition at line 378 of file cata_libintl.cpp.
{
    return trans_catalogue( std::move( mo_file ) );
}
References avatar_action::move(), and trans_catalogue().
Referenced by load_from_file().
offs_to_cstr()
const char * cata_libintl::trans_catalogue::offs_to_cstr (u32 offs) const inline private
Definition at line 138 of file cata_libintl.h.
{
            return &buffer[offs];
        }
References buffer.
Referenced by get_metadata(), get_nth_orig_string(), get_nth_pl_translation(), and get_nth_translation().
parse_plf_header()
trans_catalogue::catalogue_plurals_info cata_libintl::trans_catalogue::parse_plf_header (const meta_headers & headers) static private
Definition at line 587 of file cata_libintl.cpp.
{
    constexpr size_t MAX_PLURAL_FORMS = 8;
    // HACK: Same as with encoding headers, we expect this header to be
    //       automatically generated. This "parser" here succeeds with
    //       MO files compiled from PO created with Transifex/Poedit/msginit,
    //       and that'll probably extend to majority of other software.
    catalogue_plurals_info ret;
    // Parse Plural-Forms header.
    std::string plf_raw;
    {
        bool found = false;
        for( const std::string &entry : headers ) {
            if( !string_starts_with( entry, "Plural-Forms:" ) ) {
                continue;
            }
            found = true;
            plf_raw = entry.substr( 13 ); // length of "Plural-Forms:" string
            break;
        }
        if( !found ) {
            // Default to Germanic rules (English, German, Dutch, ...)
            ret.num = 2;
            ret.expr = parse_plural_rules( "n!=1" );
            return ret;
        }
    }
    std::vector<std::string> parts = string_split( plf_raw, ';' );
    if( parts.size() != 3 ) {
        throw std::runtime_error( "expected Plural-Forms header to have 2 ';' characters" );
    }
    // Parse & validate nplurals
    {
        std::string plf_n_raw = parts[0];
        if( !string_starts_with( plf_n_raw, " nplurals=" ) ) {
            throw std::runtime_error( "failed to parse Plural-Forms header" );
        }
        plf_n_raw = plf_n_raw.substr( 10 ); // 10 is length of " nplurals=" string
        try {
            ret.num = std::stoul( plf_n_raw );
        } catch( const std::runtime_error &err ) {
            std::string e = string_format( "failed to parse Plural-Forms nplurals number '%s': %s", plf_n_raw,
                                           err.what() );
            throw std::runtime_error( e );
        }
        if( ret.num == 0 || ret.num > MAX_PLURAL_FORMS ) {
            std::string e = string_format( "expected at most 1-%d plural forms, got %d", MAX_PLURAL_FORMS,
                                           ret.num );
            throw std::runtime_error( e );
        }
    }
    // Parse & validate plural formula
    {
        std::string plf_rules_raw = parts[1];
        if( !string_starts_with( plf_rules_raw, " plural=" ) ) {
            throw std::runtime_error( "failed to parse Plural-Forms header" );
        }
        plf_rules_raw = plf_rules_raw.substr( 8 ); // 8 is length of " plural=" string
        try {
            ret.expr = parse_plural_rules( plf_rules_raw );
        } catch( const std::runtime_error &err ) {
            std::string e = string_format( "failed to parse plural forms formula: %s", err.what() );
            throw std::runtime_error( e );
        }
    }
    return ret;
}
References cata_libintl::parse_plural_rules(), cata::hash64_detail::ret, string_format(), string_split(), and string_starts_with().
Referenced by trans_catalogue().
process_file_header()
void cata_libintl::trans_catalogue::process_file_header () private
Definition at line 437 of file cata_libintl.cpp.
{
    constexpr u32 MO_MAGIC_NUMBER_LE = 0x950412de;
    constexpr u32 MO_MAGIC_NUMBER_BE = 0xde120495;
    constexpr u32 MO_SUPPORTED_REVISION = 0;
    constexpr u32 OFFS_MAGIC_NUMBER = 0;
    constexpr u32 OFFS_REVISION = 4;
    constexpr u32 OFFS_NUM_STRINGS = 8;
    constexpr u32 OFFS_ORIG_TABLE_BEGIN = 12;
    constexpr u32 OFFS_TRANS_TABLE_BEGIN = 16;
    u32 magic = this->buffer.size() > 4 ? get_u32( OFFS_MAGIC_NUMBER ) : 0;
    if( magic != MO_MAGIC_NUMBER_LE && magic != MO_MAGIC_NUMBER_BE ) {
        throw std::runtime_error( "not a MO file" );
    }
    this->is_little_endian = magic == MO_MAGIC_NUMBER_LE;
    if( get_u32( OFFS_REVISION ) != MO_SUPPORTED_REVISION ) {
        std::string e = string_format(
                            "expected revision %d, got %d",
                            MO_SUPPORTED_REVISION,
                            get_u32( OFFS_REVISION )
                        );
        throw std::runtime_error( e );
    }
    number_of_strings = get_u32( OFFS_NUM_STRINGS );
    offs_orig_table = get_u32( OFFS_ORIG_TABLE_BEGIN );
    offs_trans_table = get_u32( OFFS_TRANS_TABLE_BEGIN );
}
References buffer, get_u32(), is_little_endian, number_of_strings, offs_orig_table, offs_trans_table, and string_format().
Referenced by trans_catalogue().
set_buffer()
void cata_libintl::trans_catalogue::set_buffer (std::string buffer) inline private
Definition at line 108 of file cata_libintl.h.
{
            this->buffer = std::move( buffer );
        }
References buffer, and avatar_action::move().
Referenced by trans_catalogue().
Member Data Documentation
buffer
std::string cata_libintl::trans_catalogue::buffer private
Definition at line 98 of file cata_libintl.h.
Referenced by buf_size(), get_u8_unsafe(), load_from_file(), offs_to_cstr(), process_file_header(), set_buffer(), and trans_catalogue().
is_little_endian
bool cata_libintl::trans_catalogue::is_little_endian = true private
Definition at line 97 of file cata_libintl.h.
Referenced by get_u32_unsafe(), and process_file_header().
number_of_strings
u32 cata_libintl::trans_catalogue::number_of_strings = 0 private
Definition at line 100 of file cata_libintl.h.
Referenced by check_string_plurals(), check_string_terminators(), get_num_strings(), and process_file_header().
offs_orig_table
u32 cata_libintl::trans_catalogue::offs_orig_table = 0 private
Definition at line 101 of file cata_libintl.h.
Referenced by check_string_plurals(), check_string_terminators(), get_metadata(), get_nth_orig_string(), and process_file_header().
offs_trans_table
u32 cata_libintl::trans_catalogue::offs_trans_table = 0 private
Definition at line 102 of file cata_libintl.h.
Referenced by check_nth_translation_has_plf(), check_string_plurals(), check_string_terminators(), get_metadata(), get_nth_pl_translation(), get_nth_translation(), and process_file_header().
plurals
catalogue_plurals_info cata_libintl::trans_catalogue::plurals private
Definition at line 99 of file cata_libintl.h.
Referenced by check_string_plurals(), get_nth_pl_translation(), and trans_catalogue().
The documentation for this class was generated from the following files:
src/cata_libintl.h
src/cata_libintl.cpp