Cataclysm BN: ma_weapon_damage_reader Class Reference
ma_weapon_damage_reader Class Reference
Public Member Functions
std::pair< damage_type, int > get_next (JsonIn &jin) const
template<typename C >
void erase_next (JsonIn &jin, C &container) const
Public Member Functions inherited from generic_typed_reader< ma_weapon_damage_reader >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Public Attributes
std::map< std::string, damage_type > dt_map = get_dt_map()
Detailed Description
Definition at line 136 of file martialarts.cpp.
Member Function Documentation
erase_next()
template<typename C > void ma_weapon_damage_reader::erase_next (JsonIn & jin, C & container) const inline
Definition at line 152 of file martialarts.cpp.
{
            JsonObject jo = jin.get_object();
            std::string type = jo.get_string( "type" );
            const auto iter = get_dt_map().find( type );
            if( iter == get_dt_map().end() ) {
                jo.throw_error( "Invalid damage type" );
            }
            damage_type id = iter->second;
            reader_detail::handler<C>().erase_if( container, [&id]( const std::pair<damage_type, int> &e ) {
                return e.first == id;
            } );
        }
References get_dt_map(), JsonIn::get_object(), JsonObject::get_string(), base_camps::id, JsonObject::throw_error(), and type.
get_next()
std::pair< damage_type, int > ma_weapon_damage_reader::get_next (JsonIn & jin) const inline
Definition at line 141 of file martialarts.cpp.
{
            JsonObject jo = jin.get_object();
            std::string type = jo.get_string( "type" );
            const auto iter = get_dt_map().find( type );
            if( iter == get_dt_map().end() ) {
                jo.throw_error( "Invalid damage type" );
            }
            const damage_type dt = iter->second;
            return std::pair<damage_type, int>( dt, jo.get_int( "min" ) );
        }
References get_dt_map(), JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), JsonObject::throw_error(), and type.
Member Data Documentation
dt_map
std::map<std::string, damage_type> ma_weapon_damage_reader::dt_map = get_dt_map()
Definition at line 139 of file martialarts.cpp.
The documentation for this class was generated from the following file:
src/martialarts.cpp