Cataclysm BN: snake_game Class Reference
snake_game Class Reference
#include <iuse_software_snake.h>
Public Member Functions
snake_game ()
void print_score (const catacurses::window &w_snake, int iScore)
void print_header (const catacurses::window &w_snake, bool show_shortcut=true)
void snake_over (const catacurses::window &w_snake, int iScore)
int start_game ()
Detailed Description
Definition at line 10 of file iuse_software_snake.h.
Constructor & Destructor Documentation
snake_game()
snake_game::snake_game () default
Member Function Documentation
print_header()
void snake_game::print_header (const catacurses::window & w_snake, bool show_shortcut = true)
Definition at line 29 of file iuse_software_snake.cpp.
{
    draw_border( w_snake, BORDER_COLOR, _( "S N A K E" ), c_white );
    if( show_shortcut ) {
        std::string shortcut = _( "<q>uit" );
        shortcut_print( w_snake, point( FULL_SCREEN_WIDTH - utf8_width( shortcut ) - 2, 0 ),
                        c_white, c_light_green, shortcut );
    }
}
References _, BORDER_COLOR, c_light_green, c_white, draw_border(), FULL_SCREEN_WIDTH, shortcut_print(), and utf8_width().
Referenced by snake_over(), and start_game().
print_score()
void snake_game::print_score (const catacurses::window & w_snake, int iScore)
Definition at line 24 of file iuse_software_snake.cpp.
{
    mvwprintz( w_snake, point( 5, 0 ), c_white, string_format( _( "Score: %d" ), iScore ) );
}
References _, c_white, mvwprintz(), and string_format().
Referenced by start_game().
snake_over()
void snake_game::snake_over (const catacurses::window & w_snake, int iScore)
Definition at line 39 of file iuse_software_snake.cpp.
{
    werase( w_snake );
    print_header( w_snake, false );
    // Body of dead snake
    size_t body_length = 3;
    for( size_t i = 1; i <= body_length; i++ ) {
        for( size_t j = 0; j <= 1; j++ ) {
            mvwprintz( w_snake, point( 4 + j * 65, i ), c_green, "|   |" );
        }
    }
    // Head of dead snake
    mvwprintz( w_snake, point( 3, body_length + 1 ), c_green, "(     )" );
    mvwprintz( w_snake, point( 4, body_length + 1 ), c_dark_gray, "x   x" );
    mvwprintz( w_snake, point( 3, body_length + 2 ), c_green, " \\___/ " );
    mvwputch( w_snake, point( 6, body_length + 3 ), c_red, '|' );
    mvwputch( w_snake, point( 6, body_length + 4 ), c_red, '^' );
    // Tail of dead snake
    mvwprintz( w_snake, point( 70, body_length + 1 ), c_green, "\\ /" );
    mvwputch( w_snake, point( 71, body_length + 2 ), c_green, 'v' );
    std::vector<std::string> game_over_text;
    game_over_text.push_back( R"(  ________    _____      _____   ___________)" );
    game_over_text.push_back( R"( /  _____/   /  _  \    /     \  \_   _____/)" );
    game_over_text.push_back( R"(/   \  ___  /  /_\  \  /  \ /  \  |    __)_ )" );
    game_over_text.push_back( R"(\    \_\  \/    |    \/    Y    \ |        \)" );
    game_over_text.push_back( R"( \______  /\____|__  /\____|__  //_______  /)" );
    game_over_text.push_back( R"(        \/         \/         \/         \/ )" );
    game_over_text.push_back( R"( ________ ____   _________________________  )" );
    game_over_text.push_back( R"( \_____  \\   \ /   /\_   _____/\______   \ )" );
    game_over_text.push_back( R"(  /   |   \\   Y   /  |    __)_  |       _/ )" );
    game_over_text.push_back( R"( /    |    \\     /   |        \ |    |   \ )" );
    game_over_text.push_back( R"( \_______  / \___/   /_______  / |____|_  / )" );
    game_over_text.push_back( R"(         \/                  \/         \/  )" );
    for( size_t i = 0; i < game_over_text.size(); i++ ) {
        mvwprintz( w_snake, point( 17, i + 3 ), c_light_red, game_over_text[i] );
    }
    center_print( w_snake, 17, c_yellow, string_format( _( "TOTAL SCORE: %d" ), iScore ) );
    // TODO: print actual bound keys
    center_print( w_snake, 21, c_white, _( "Press 'q' or ESC to exit." ) );
    wnoutrefresh( w_snake );
}
References _, c_dark_gray, c_green, c_light_red, c_red, c_white, c_yellow, center_print(), mvwprintz(), mvwputch(), print_header(), string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by start_game().
start_game()
int snake_game::start_game ()
Definition at line 87 of file iuse_software_snake.cpp.
{
    std::vector<std::pair<int, int> > vSnakeBody;
    std::map<int, std::map<int, bool> > mSnakeBody;
    catacurses::window w_snake;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const point iOffset( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                             TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 );
        w_snake = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                      iOffset );
        ui.position_from_window( w_snake );
    } );
    ui.mark_resize();
    //Snake start position
    vSnakeBody.push_back( std::make_pair( FULL_SCREEN_HEIGHT / 2, FULL_SCREEN_WIDTH / 2 ) );
    mSnakeBody[FULL_SCREEN_HEIGHT / 2][FULL_SCREEN_WIDTH / 2] = true;
    //Snake start direction
    int iDirY = 0;
    int iDirX = 1;
    //Snake start length
    size_t iSnakeBody = 10;
    //GameSpeed aka inputdelay/timeout
    int iGameSpeed = 100;
    //Score
    int iScore = 0;
    int iFruitPosY = 0;
    int iFruitPosX = 0;
    input_context ctxt( "SNAKE" );
    ctxt.register_cardinal();
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_snake );
        print_header( w_snake );
        for( auto it = vSnakeBody.begin(); it != vSnakeBody.end(); ++it ) {
            const nc_color col = it + 1 == vSnakeBody.end() ? c_white : c_light_gray;
            mvwputch( w_snake, point( it->second, it->first ), col, '#' );
        }
        if( iFruitPosX != 0 && iFruitPosY != 0 ) {
            mvwputch( w_snake, point( iFruitPosX, iFruitPosY ), c_light_red, '*' );
        }
        print_score( w_snake, iScore );
        wnoutrefresh( w_snake );
    } );
    do {
        //Check if we hit a border
        if( vSnakeBody[vSnakeBody.size() - 1].first + iDirY == 0 ) {
            vSnakeBody.push_back( std::make_pair( vSnakeBody[vSnakeBody.size() - 1].first +
                                                  iDirY + FULL_SCREEN_HEIGHT - 2,
                                                  vSnakeBody[vSnakeBody.size() - 1].second + iDirX ) );
        } else if( vSnakeBody[vSnakeBody.size() - 1].first + iDirY == FULL_SCREEN_HEIGHT - 1 ) {
            vSnakeBody.push_back( std::make_pair( vSnakeBody[vSnakeBody.size() - 1].first +
                                                  iDirY - FULL_SCREEN_HEIGHT + 2,
                                                  vSnakeBody[vSnakeBody.size() - 1].second + iDirX ) );
        } else if( vSnakeBody[vSnakeBody.size() - 1].second + iDirX == 0 ) {
            vSnakeBody.push_back( std::make_pair( vSnakeBody[vSnakeBody.size() - 1].first + iDirY,
                                                  vSnakeBody[vSnakeBody.size() - 1].second +
                                                  iDirX + FULL_SCREEN_WIDTH - 2 ) );
        } else if( vSnakeBody[vSnakeBody.size() - 1].second + iDirX == FULL_SCREEN_WIDTH - 1 ) {
            vSnakeBody.push_back( std::make_pair( vSnakeBody[vSnakeBody.size() - 1].first + iDirY,
                                                  vSnakeBody[vSnakeBody.size() - 1].second +
                                                  iDirX - FULL_SCREEN_WIDTH + 2 ) );
        } else {
            vSnakeBody.push_back( std::make_pair( vSnakeBody[vSnakeBody.size() - 1].first + iDirY,
                                                  vSnakeBody[vSnakeBody.size() - 1].second + iDirX ) );
        }
        //Check if we hit ourselves
        if( mSnakeBody[vSnakeBody[vSnakeBody.size() - 1].first]
            [vSnakeBody[vSnakeBody.size() - 1].second] ) {
            //We are dead :(
            break;
        } else {
            //Add new position to map
            mSnakeBody[vSnakeBody[vSnakeBody.size() - 1].first]
            [vSnakeBody[vSnakeBody.size() - 1].second] = true;
        }
        //Have we eaten the forbidden fruit?
        if( vSnakeBody[vSnakeBody.size() - 1].first == iFruitPosY &&
            vSnakeBody[vSnakeBody.size() - 1].second == iFruitPosX ) {
            iScore += 500;
            iSnakeBody += 10;
            iGameSpeed -= 3;
            iFruitPosY = 0;
            iFruitPosX = 0;
        }
        //Check if we are longer than our max size
        if( vSnakeBody.size() > iSnakeBody ) {
            mSnakeBody[vSnakeBody[0].first][vSnakeBody[0].second] = false;
            vSnakeBody.erase( vSnakeBody.begin(), vSnakeBody.begin() + 1 );
        }
        //On full length add a fruit
        if( iFruitPosX == 0 && iFruitPosY == 0 ) {
            do {
                iFruitPosY = rng( 1, FULL_SCREEN_HEIGHT - 2 );
                iFruitPosX = rng( 1, FULL_SCREEN_WIDTH - 2 );
            } while( mSnakeBody[iFruitPosY][iFruitPosX] );
        }
        ui_manager::redraw();
        const std::string action = ctxt.handle_input( iGameSpeed );
        if( action == "UP" ) {
            if( iDirY != 1 ) {
                iDirY = -1;
                iDirX = 0;
            }
        } else if( action == "DOWN" ) {
            if( iDirY != -1 ) {
                iDirY = 1;
                iDirX = 0;
            }
        } else if( action == "LEFT" ) {
            if( iDirX != 1 ) {
                iDirY = 0;
                iDirX = -1;
            }
        } else if( action == "RIGHT" ) {
            if( iDirX != -1 ) {
                iDirY = 0;
                iDirX = 1;
            }
        } else if( action == "QUIT" ) {
            return iScore;
        }
    } while( true );
    ui.on_redraw( [&]( const ui_adaptor & ) {
        snake_over( w_snake, iScore );
    } );
    do {
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "QUIT" ) {
            break;
        }
    } while( true );
    return iScore;
}
References action, c_light_gray, c_light_red, c_white, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::handle_input(), mvwputch(), catacurses::newwin(), print_header(), print_score(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), rng(), snake_over(), TERMX, TERMY, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by play_videogame().
The documentation for this class was generated from the following files:
src/iuse_software_snake.h
src/iuse_software_snake.cpp