Cataclysm BN: ma_buff Class Reference
ma_buff Class Reference
#include <martialarts.h>
Public Member Functions
ma_buff ()
void apply_buff (Character &u) const
bool is_valid_character (const Character &u) const
void apply_character (Character &u) const
int hit_bonus (const Character &u) const
int dodge_bonus (const Character &u) const
int speed_bonus (const Character &u) const
int block_bonus (const Character &u) const
int arpen_bonus (const Character &u, damage_type dt) const
int armor_bonus (const Character &guy, damage_type dt) const
float damage_bonus (const Character &u, damage_type dt) const
float damage_mult (const Character &u, damage_type dt) const
bool is_throw_immune () const
bool is_quiet () const
bool is_stealthy () const
efftype_id get_effect_id () const
std::string get_description (bool passive=false) const
void load (const JsonObject &jo, const std::string &src)
Static Public Member Functions
static const ma_buff * from_effect (const effect &eff)
Public Attributes
mabuff_id id
bool was_loaded = false
std::string name
std::string description
ma_requirements reqs
time_duration buff_duration = 0_turns
int max_stacks = 0
int dodges_bonus = 0
int blocks_bonus = 0
bonus_container bonuses
All kinds of bonuses by types to damage, hit, armor etc.
bool quiet = false
bool throw_immune = false
bool strictly_melee = false
bool stealthy = false
Detailed Description
Definition at line 131 of file martialarts.h.
Constructor & Destructor Documentation
ma_buff()
ma_buff::ma_buff ()
Definition at line 607 of file martialarts.cpp.
    : buff_duration( 1_turns )
{
    max_stacks = 1; // total number of stacks this buff can have
    dodges_bonus = 0; // extra dodges, like karate
    blocks_bonus = 0; // extra blocks, like karate
    throw_immune = false;
}
References blocks_bonus, dodges_bonus, max_stacks, and throw_immune.
Member Function Documentation
apply_buff()
void ma_buff::apply_buff (Character & u) const
Definition at line 634 of file martialarts.cpp.
{
    u.add_effect( get_effect_id(), time_duration::from_turns( buff_duration ) );
}
References Creature::add_effect(), buff_duration, time_duration::from_turns(), and get_effect_id().
Referenced by simultaneous_add().
apply_character()
void ma_buff::apply_character (Character & u) const
Definition at line 644 of file martialarts.cpp.
{
    u.mod_num_dodges_bonus( dodges_bonus );
    u.set_num_blocks_bonus( u.get_num_blocks_bonus() + blocks_bonus );
}
References blocks_bonus, dodges_bonus, Creature::get_num_blocks_bonus(), Creature::mod_num_dodges_bonus(), and Creature::set_num_blocks_bonus().
armor_bonus()
int ma_buff::armor_bonus (const Character & guy, damage_type dt) const
Definition at line 670 of file martialarts.cpp.
{
    return bonuses.get_flat( guy, affected_stat::ARMOR, dt );
}
References ARMOR, bonuses, and bonus_container::get_flat().
arpen_bonus()
int ma_buff::arpen_bonus (const Character & u, damage_type dt) const
Definition at line 662 of file martialarts.cpp.
{
    return bonuses.get_flat( u, affected_stat::ARMOR_PENETRATION, dt );
}
References ARMOR_PENETRATION, bonuses, and bonus_container::get_flat().
block_bonus()
int ma_buff::block_bonus (const Character & u) const
Definition at line 658 of file martialarts.cpp.
{
    return bonuses.get_flat( u, affected_stat::BLOCK );
}
References BLOCK, bonuses, and bonus_container::get_flat().
damage_bonus()
float ma_buff::damage_bonus (const Character & u, damage_type dt) const
Definition at line 674 of file martialarts.cpp.
{
    return bonuses.get_flat( u, affected_stat::DAMAGE, dt );
}
References bonuses, DAMAGE, and bonus_container::get_flat().
damage_mult()
float ma_buff::damage_mult (const Character & u, damage_type dt) const
Definition at line 678 of file martialarts.cpp.
{
    return bonuses.get_mult( u, affected_stat::DAMAGE, dt );
}
References bonuses, DAMAGE, and bonus_container::get_mult().
dodge_bonus()
int ma_buff::dodge_bonus (const Character & u) const
Definition at line 654 of file martialarts.cpp.
{
    return bonuses.get_flat( u, affected_stat::DODGE );
}
References bonuses, DODGE, and bonus_container::get_flat().
from_effect()
const ma_buff * ma_buff::from_effect (const effect & eff) static
Definition at line 624 of file martialarts.cpp.
{
    const std::string &id = eff.get_effect_type()->id.str();
    // Same as in get_effect_id!
    if( id.compare( 0, 7, "mabuff:" ) != 0 ) {
        return nullptr;
    }
    return &mabuff_id( id.substr( 7 ) ).obj();
}
References game_menus::inv::compare(), effect::get_effect_type(), effect_type::id, string_id< T >::obj(), and string_id< T >::str().
Referenced by accumulate_ma_buff_effects(), Character::hardcoded_effects(), and search_ma_buff_effect().
get_description()
std::string ma_buff::get_description (bool passive = false) const
Definition at line 695 of file martialarts.cpp.
{
    std::string dump;
    dump += string_format( _( "<bold>Buff technique:</bold> %s" ), _( name ) ) + "\n";
    std::string temp = bonuses.get_description();
    if( !temp.empty() ) {
        dump += string_format( _( "<bold>%s:</bold> " ),
                               vgettext( "Bonus", "Bonus/stack", max_stacks ) ) + "\n" + temp;
    }
    dump += reqs.get_description( true );
    if( max_stacks > 1 ) {
        dump += string_format( _( "* Will <info>stack</info> up to <stat>%d</stat> times" ),
                               max_stacks ) + "\n";
    }
    const int turns = to_turns<int>( buff_duration );
    if( !passive && turns ) {
        dump += string_format( _( "* Will <info>last</info> for <stat>%d %s</stat>" ),
                               turns, vgettext( "turn", "turns", turns ) ) + "\n";
    }
    if( dodges_bonus > 0 ) {
        dump += string_format( _( "* Will give a <good>+%s</good> bonus to <info>dodge</info>%s" ),
                               dodges_bonus, vgettext( " for the stack", " per stack", max_stacks ) ) + "\n";
    } else if( dodges_bonus < 0 ) {
        dump += string_format( _( "* Will give a <bad>%s</bad> penalty to <info>dodge</info>%s" ),
                               dodges_bonus, vgettext( " for the stack", " per stack", max_stacks ) ) + "\n";
    }
    if( blocks_bonus > 0 ) {
        dump += string_format( _( "* Will give a <good>+%s</good> bonus to <info>block</info>%s" ),
                               blocks_bonus, vgettext( " for the stack", " per stack", max_stacks ) ) + "\n";
    } else if( blocks_bonus < 0 ) {
        dump += string_format( _( "* Will give a <bad>%s</bad> penalty to <info>block</info>%s" ),
                               blocks_bonus, vgettext( " for the stack", " per stack", max_stacks ) ) + "\n";
    }
    if( quiet ) {
        dump += _( "* Attacks will be completely <info>silent</info>" ) + std::string( "\n" );
    }
    if( stealthy ) {
        dump += _( "* Movement will make <info>less noise</info>" ) + std::string( "\n" );
    }
    return dump;
}
References _, blocks_bonus, bonuses, buff_duration, dodges_bonus, bonus_container::get_description(), ma_requirements::get_description(), max_stacks, name, passive, quiet, reqs, stealthy, string_format(), and vgettext().
get_effect_id()
efftype_id ma_buff::get_effect_id () const
Definition at line 619 of file martialarts.cpp.
{
    return efftype_id( std::string( "mabuff:" ) + id.str() );
}
References efftype_id.
Referenced by apply_buff(), and ma_buff_effect_type::ma_buff_effect_type().
hit_bonus()
int ma_buff::hit_bonus (const Character & u) const
Definition at line 650 of file martialarts.cpp.
{
    return bonuses.get_flat( u, affected_stat::HIT );
}
References bonuses, bonus_container::get_flat(), and HIT.
is_quiet()
bool ma_buff::is_quiet () const
Definition at line 686 of file martialarts.cpp.
{
    return quiet;
}
References quiet.
is_stealthy()
bool ma_buff::is_stealthy () const
Definition at line 690 of file martialarts.cpp.
{
    return stealthy;
}
References stealthy.
is_throw_immune()
bool ma_buff::is_throw_immune () const
Definition at line 682 of file martialarts.cpp.
{
    return throw_immune;
}
References throw_immune.
is_valid_character()
bool ma_buff::is_valid_character (const Character & u) const
Definition at line 639 of file martialarts.cpp.
{
    return reqs.is_valid_character( u );
}
References ma_requirements::is_valid_character(), and reqs.
Referenced by simultaneous_add().
load()
void ma_buff::load (const JsonObject & jo, const std::string & src)
Definition at line 207 of file martialarts.cpp.
{
    mandatory( jo, was_loaded, "name", name );
    mandatory( jo, was_loaded, "description", description );
    optional( jo, was_loaded, "buff_duration", buff_duration, 2_turns );
    optional( jo, was_loaded, "max_stacks", max_stacks, 1 );
    optional( jo, was_loaded, "bonus_dodges", dodges_bonus, 0 );
    optional( jo, was_loaded, "bonus_blocks", blocks_bonus, 0 );
    optional( jo, was_loaded, "quiet", quiet, false );
    optional( jo, was_loaded, "throw_immune", throw_immune, false );
    optional( jo, was_loaded, "stealthy", stealthy, false );
    reqs.load( jo, src );
    bonuses.load( jo );
}
References blocks_bonus, bonuses, buff_duration, description, dodges_bonus, bonus_container::load(), ma_requirements::load(), mandatory(), max_stacks, name, optional(), quiet, reqs, stealthy, throw_immune, and was_loaded.
speed_bonus()
int ma_buff::speed_bonus (const Character & u) const
Definition at line 666 of file martialarts.cpp.
{
    return bonuses.get_flat( u, affected_stat::SPEED );
}
References bonuses, bonus_container::get_flat(), and SPEED.
Member Data Documentation
blocks_bonus
int ma_buff::blocks_bonus = 0
Definition at line 187 of file martialarts.h.
Referenced by apply_character(), get_description(), load(), and ma_buff().
bonuses
bonus_container ma_buff::bonuses
All kinds of bonuses by types to damage, hit, armor etc.
Definition at line 190 of file martialarts.h.
Referenced by armor_bonus(), arpen_bonus(), block_bonus(), damage_bonus(), damage_mult(), dodge_bonus(), get_description(), hit_bonus(), load(), and speed_bonus().
buff_duration
time_duration ma_buff::buff_duration = 0_turns
Definition at line 183 of file martialarts.h.
Referenced by apply_buff(), get_description(), load(), and ma_buff_effect_type::ma_buff_effect_type().
description
std::string ma_buff::description
Definition at line 176 of file martialarts.h.
Referenced by load(), and ma_buff_effect_type::ma_buff_effect_type().
dodges_bonus
int ma_buff::dodges_bonus = 0
Definition at line 186 of file martialarts.h.
Referenced by apply_character(), get_description(), load(), and ma_buff().
id
mabuff_id ma_buff::id
Definition at line 173 of file martialarts.h.
max_stacks
int ma_buff::max_stacks = 0
Definition at line 184 of file martialarts.h.
Referenced by get_description(), load(), ma_buff(), and ma_buff_effect_type::ma_buff_effect_type().
name
std::string ma_buff::name
Definition at line 175 of file martialarts.h.
Referenced by get_description(), load(), and ma_buff_effect_type::ma_buff_effect_type().
quiet
bool ma_buff::quiet = false
Definition at line 192 of file martialarts.h.
Referenced by get_description(), is_quiet(), and load().
reqs
ma_requirements ma_buff::reqs
Definition at line 179 of file martialarts.h.
Referenced by get_description(), is_valid_character(), and load().
stealthy
bool ma_buff::stealthy = false
Definition at line 195 of file martialarts.h.
Referenced by get_description(), is_stealthy(), and load().
strictly_melee
bool ma_buff::strictly_melee = false
Definition at line 194 of file martialarts.h.
throw_immune
bool ma_buff::throw_immune = false
Definition at line 193 of file martialarts.h.
Referenced by is_throw_immune(), load(), and ma_buff().
was_loaded
bool ma_buff::was_loaded = false
Definition at line 174 of file martialarts.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/martialarts.h
src/martialarts.cpp