Cataclysm BN: behavior::character_oracle_t Class Reference
behavior::character_oracle_t Class Reference
#include <character_oracle.h>
Public Member Functions
character_oracle_t (const Character *subject)
status_t needs_warmth_badly () const
Predicates used by AI to determine goals.
status_t needs_water_badly () const
status_t needs_food_badly () const
status_t can_wear_warmer_clothes () const
status_t can_make_fire () const
status_t can_take_shelter () const
status_t has_water () const
status_t has_food () const
Private Attributes
const Character * subject
Detailed Description
Definition at line 13 of file character_oracle.h.
Constructor & Destructor Documentation
character_oracle_t()
behavior::character_oracle_t::character_oracle_t (const Character * subject) inline
Definition at line 16 of file character_oracle.h.
{
            this->subject = subject;
        }
References subject.
Member Function Documentation
can_make_fire()
status_t behavior::character_oracle_t::can_make_fire () const
Definition at line 70 of file character_oracle.cpp.
{
    // Check inventory for firemaking tools and fuel
    bool tool = false;
    bool fuel = false;
    for( const auto &i : subject->inv.const_slice() ) {
        const item &candidate = i->front();
        if( candidate.has_flag( flag_FIRESTARTER ) ) {
            tool = true;
            if( fuel ) {
                return running;
            }
        } else if( candidate.flammable() ) {
            fuel = true;
            if( tool ) {
                return running;
            }
        }
    }
    return success;
}
References inventory::const_slice(), flag_FIRESTARTER(), item::flammable(), item::has_flag(), Character::inv, behavior::running, subject, behavior::success, and tool.
can_take_shelter()
status_t behavior::character_oracle_t::can_take_shelter () const
Definition at line 92 of file character_oracle.cpp.
{
    // See if we know about some shelter
    // Don't know how yet.
    return failure;
}
References behavior::failure.
can_wear_warmer_clothes()
status_t behavior::character_oracle_t::can_wear_warmer_clothes () const
Definition at line 56 of file character_oracle.cpp.
{
    const player *p = dynamic_cast<const player *>( subject );
    // Check inventory for wearable warmer clothes, greedily.
    // Don't consider swapping clothes yet, just evaluate adding clothes.
    for( const auto &i : subject->inv.const_slice() ) {
        const item &candidate = i->front();
        if( candidate.get_warmth() > 0 || p->can_wear( candidate ).success() ) {
            return running;
        }
    }
    return failure;
}
References Character::can_wear(), inventory::const_slice(), behavior::failure, item::get_warmth(), Character::inv, behavior::running, and subject.
has_food()
status_t behavior::character_oracle_t::has_food () const
Definition at line 108 of file character_oracle.cpp.
{
    // Check if we know about food somewhere
    bool found_food = subject->inv.has_item_with( []( const item & cand ) {
        return cand.is_food() && cand.get_comestible()->has_calories();
    } );
    return found_food ? running : failure;
}
References behavior::failure, item::get_comestible(), visitable< T >::has_item_with(), Character::inv, item::is_food(), behavior::running, and subject.
has_water()
status_t behavior::character_oracle_t::has_water () const
Definition at line 99 of file character_oracle.cpp.
{
    // Check if we know about water somewhere
    bool found_water = subject->inv.has_item_with( []( const item & cand ) {
        return cand.is_food() && cand.get_comestible()->quench > 0;
    } );
    return found_water ? running : failure;
}
References behavior::failure, item::get_comestible(), visitable< T >::has_item_with(), Character::inv, item::is_food(), behavior::running, and subject.
needs_food_badly()
status_t behavior::character_oracle_t::needs_food_badly () const
Definition at line 47 of file character_oracle.cpp.
{
    // Check hunger threshold.
    if( subject->get_kcal_percent() < 0.5f ) {
        return running;
    }
    return success;
}
References Character::get_kcal_percent(), behavior::running, subject, and behavior::success.
needs_warmth_badly()
status_t behavior::character_oracle_t::needs_warmth_badly () const
Predicates used by AI to determine goals.
Definition at line 26 of file character_oracle.cpp.
{
    const player *p = dynamic_cast<const player *>( subject );
    // Use player::temp_conv to predict whether the Character is "in trouble".
    for( const body_part bp : all_body_parts ) {
        if( p->temp_conv[ bp ] <= BODYTEMP_VERY_COLD ) {
            return running;
        }
    }
    return success;
}
References all_body_parts, BODYTEMP_VERY_COLD, behavior::running, subject, behavior::success, and Character::temp_conv.
needs_water_badly()
status_t behavior::character_oracle_t::needs_water_badly () const
Definition at line 38 of file character_oracle.cpp.
{
    // Check thirst threshold.
    if( subject->get_thirst() > thirst_levels::parched ) {
        return running;
    }
    return success;
}
References Character::get_thirst(), parched, behavior::running, subject, and behavior::success.
Member Data Documentation
subject
const Character* behavior::character_oracle_t::subject private
Definition at line 31 of file character_oracle.h.
Referenced by can_make_fire(), can_wear_warmer_clothes(), character_oracle_t(), has_food(), has_water(), needs_food_badly(), needs_warmth_badly(), and needs_water_badly().
The documentation for this class was generated from the following files:
src/character_oracle.h
src/character_oracle.cpp