Cataclysm BN: rect_range< RectType >::iterator Class Reference
rect_range< RectType >::iterator Class Reference
#include <rect_range.h>
Public Member Functions
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
RectType operator* () const
iterator operator+ (const int offset) const
int operator- (const iterator &rhs) const
iterator & operator++ ()
Private Member Functions
iterator (const rect_range *const r, const int i)
Private Attributes
const rect_range * range
int index
Friends
class rect_range
Detailed Description
template<typename RectType>
class rect_range< RectType >::iterator
Definition at line 22 of file rect_range.h.
Constructor & Destructor Documentation
iterator()
template<typename RectType > rect_range< RectType >::iterator::iterator (const rect_range *const r, const int i) inline private
Definition at line 29 of file rect_range.h.
                                                                   : range( r ), index( i ) {
                }
Referenced by rect_range< RectType >::iterator::operator+().
Member Function Documentation
operator!=()
template<typename RectType > bool rect_range< RectType >::iterator::operator!= (const iterator & rhs) const inline
Definition at line 36 of file rect_range.h.
{
                    return !operator==( rhs );
                }
References rect_range< RectType >::iterator::operator==().
operator*()
template<typename RectType > RectType rect_range< RectType >::iterator::operator* () const inline
Definition at line 39 of file rect_range.h.
{
                    return { ( index % range->count.x ) *range->width, ( index / range->count.x ) *range->height, range->width, range->height };
                }
References rect_range< RectType >::count, rect_range< RectType >::height, rect_range< RectType >::iterator::index, rect_range< RectType >::iterator::range, rect_range< RectType >::width, and point::x.
operator+()
template<typename RectType > iterator rect_range< RectType >::iterator::operator+ (const int offset) const inline
Definition at line 43 of file rect_range.h.
{
                    return iterator( range, index + offset );
                }
References rect_range< RectType >::iterator::index, rect_range< RectType >::iterator::iterator(), and rect_range< RectType >::iterator::range.
operator++()
template<typename RectType > iterator & rect_range< RectType >::iterator::operator++ () inline
Definition at line 49 of file rect_range.h.
{
                    ++index;
                    return *this;
                }
References rect_range< RectType >::iterator::index.
operator-()
template<typename RectType > int rect_range< RectType >::iterator::operator- (const iterator & rhs) const inline
Definition at line 46 of file rect_range.h.
{
                    return index - rhs.index;
                }
References rect_range< RectType >::iterator::index.
operator==()
template<typename RectType > bool rect_range< RectType >::iterator::operator== (const iterator & rhs) const inline
Definition at line 33 of file rect_range.h.
{
                    return range == rhs.range && index == rhs.index;
                }
References rect_range< RectType >::iterator::index, and rect_range< RectType >::iterator::range.
Referenced by rect_range< RectType >::iterator::operator!=().
Friends And Related Function Documentation
rect_range
template<typename RectType > friend class rect_range friend
Definition at line 25 of file rect_range.h.
Member Data Documentation
index
template<typename RectType > int rect_range< RectType >::iterator::index private
Definition at line 27 of file rect_range.h.
Referenced by rect_range< RectType >::iterator::operator*(), rect_range< RectType >::iterator::operator+(), rect_range< RectType >::iterator::operator++(), rect_range< RectType >::iterator::operator-(), and rect_range< RectType >::iterator::operator==().
range
template<typename RectType > const rect_range* rect_range< RectType >::iterator::range private
Definition at line 26 of file rect_range.h.
Referenced by rect_range< RectType >::iterator::operator*(), rect_range< RectType >::iterator::operator+(), and rect_range< RectType >::iterator::operator==().
The documentation for this class was generated from the following file:
src/rect_range.h