Cataclysm BN: editmap::game_draw_callback_t_container Class Reference
editmap::game_draw_callback_t_container Class Reference
Public Member Functions
game_draw_callback_t_container (editmap *em)
shared_ptr_fast< game::draw_callback_t > create_or_get ()
Private Attributes
editmap * em
weak_ptr_fast< game::draw_callback_t > cbw
Detailed Description
Definition at line 289 of file editmap.cpp.
Constructor & Destructor Documentation
game_draw_callback_t_container()
editmap::game_draw_callback_t_container::game_draw_callback_t_container (editmap * em) inline
Definition at line 292 of file editmap.cpp.
: em(em) {}
Member Function Documentation
create_or_get()
shared_ptr_fast< game::draw_callback_t > editmap::game_draw_callback_t_container::create_or_get ()
Definition at line 299 of file editmap.cpp.
{
    shared_ptr_fast<game::draw_callback_t> cb = cbw.lock();
    if( !cb ) {
        cbw = cb = make_shared_fast<game::draw_callback_t>(
        [this]() {
            em->draw_main_ui_overlay();
        } );
        g->add_draw_callback( cb );
    }
    return cb;
}
References cbw, editmap::draw_main_ui_overlay(), em, and g.
Referenced by editmap::edit(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), editmap::mapgen_preview(), editmap::mapgen_retarget(), and editmap::select_shape().
Member Data Documentation
cbw
weak_ptr_fast<game::draw_callback_t> editmap::game_draw_callback_t_container::cbw private
Definition at line 296 of file editmap.cpp.
Referenced by create_or_get().
em
editmap* editmap::game_draw_callback_t_container::em private
Definition at line 295 of file editmap.cpp.
Referenced by create_or_get().
The documentation for this class was generated from the following file:
src/editmap.cpp