Cataclysm BN: Trait_creation_data Class Reference
Trait_creation_data Class Reference abstract
Base interface for trait generation.
#include <trait_group.h>
Public Types
using RecursionList = std::vector< trait_group::Trait_group_tag >
Public Member Functions
Trait_creation_data (int _probability)
virtual ~Trait_creation_data ()=default
Trait_creation_data (const Trait_creation_data &)=delete
Trait_creation_data & operator= (const Trait_creation_data &)=delete
virtual trait_group::Trait_list create (RecursionList &rec) const =0
Create a list of traits.
trait_group::Trait_list create () const
virtual void check_consistency () const =0
Check the trait templates for consistency (valid trait types, etc).
virtual bool remove_trait (const trait_id &tid)=0
Remove the given trait from this and all linked groups.
virtual bool has_trait (const trait_id &tid) const =0
Check if this group or any linked groups contain the given trait.
Public Attributes
int probability
Detailed Description
Base interface for trait generation.
Used to generate a list of traits.
Definition at line 69 of file trait_group.h.
Member Typedef Documentation
RecursionList
using Trait_creation_data::RecursionList = std::vector<trait_group::Trait_group_tag>
Definition at line 72 of file trait_group.h.
Constructor & Destructor Documentation
Trait_creation_data() [1/2]
Trait_creation_data::Trait_creation_data (int _probability) inline
Definition at line 74 of file trait_group.h.
: probability(_probability) {}
~Trait_creation_data()
virtual Trait_creation_data::~Trait_creation_data () virtual default
Trait_creation_data() [2/2]
Trait_creation_data::Trait_creation_data (const Trait_creation_data &) delete
Member Function Documentation
check_consistency()
virtual void Trait_creation_data::check_consistency () const pure virtual
Check the trait templates for consistency (valid trait types, etc).
Implemented in Single_trait_creator, Trait_group_creator, and Trait_group.
create() [1/2]
Trait_list Trait_creation_data::create () const
Definition at line 120 of file trait_group.cpp.
{
    RecursionList rec;
    auto result = create( rec );
    return result;
}
References create().
Referenced by create(), Trait_group_collection::create(), and Trait_group_distribution::create().
create() [2/2]
virtual trait_group::Trait_list Trait_creation_data::create (RecursionList & rec) const pure virtual
Create a list of traits.
The resulting list might be empty.
Parameters
[out] rec Recursion list, output goes here
Implemented in Single_trait_creator, Trait_group_creator, Trait_group_collection, and Trait_group_distribution.
has_trait()
virtual bool Trait_creation_data::has_trait (const trait_id & tid) const pure virtual
Check if this group or any linked groups contain the given trait.
Implemented in Single_trait_creator, Trait_group_creator, and Trait_group.
operator=()
Trait_creation_data & Trait_creation_data::operator= (const Trait_creation_data &) delete
remove_trait()
virtual bool Trait_creation_data::remove_trait (const trait_id & tid) pure virtual
Remove the given trait from this and all linked groups.
Used for blacklisting.
Implemented in Single_trait_creator, Trait_group_creator, and Trait_group.
Member Data Documentation
probability
int Trait_creation_data::probability
Definition at line 103 of file trait_group.h.
Referenced by Trait_group::add_group_entry(), Trait_group::add_trait_entry(), Trait_group_collection::create(), Trait_group_distribution::create(), and Trait_group_collection::Trait_group_collection().
The documentation for this class was generated from the following files:
src/trait_group.h
src/trait_group.cpp