Cataclysm BN: Skill Class Reference
Skill Class Reference
#include <skill.h>
Public Member Functions
Skill ()
Skill (const skill_id &ident, const translation &name, const translation &description, const std::set< std::string > &tags, skill_displayType_id display_type)
const skill_id & ident () const
std::string name () const
std::string description () const
int get_companion_skill_practice (const std::string &companion_skill) const
skill_displayType_id display_category () const
time_info_t time_to_attack () const
int companion_combat_rank_factor () const
int companion_survival_rank_factor () const
int companion_industry_rank_factor () const
bool operator== (const Skill &b) const
bool operator!= (const Skill &b) const
bool is_combat_skill () const
bool is_contextual_skill () const
Static Public Member Functions
static void load_skill (const JsonObject &jsobj)
static skill_id from_legacy_int (int legacy_id)
static skill_id random_skill ()
static void reset ()
static std::vector< const Skill * > get_skills_sorted_by (std::function< bool(const Skill &, const Skill &)> pred)
Static Public Attributes
static std::vector< Skill > skills
Private Attributes
skill_id _ident
translation _name
translation _description
std::set< std::string > _tags
time_info_t _time_to_attack
skill_displayType_id _display_type
std::unordered_map< std::string, int > _companion_skill_practice
int _companion_combat_rank_factor = 0
int _companion_survival_rank_factor = 0
int _companion_industry_rank_factor = 0
Static Private Attributes
static std::map< skill_id, Skill > contextual_skills
Friends
class string_id< Skill >
Detailed Description
Definition at line 32 of file skill.h.
Constructor & Destructor Documentation
Skill() [1/2]
Skill::Skill ()
Definition at line 54 of file skill.cpp.
             : Skill( skill_id::NULL_ID(), to_translation( "nothing" ),
                            to_translation( "The zen-most skill there is." ),
                            std::set<std::string> {}, skill_displayType_id::NULL_ID() )
{
}
References string.
Skill() [2/2]
Skill::Skill (const skill_id & ident, const translation & name, const translation & description, const std::set< std::string > & tags, skill_displayType_id display_type)
Definition at line 60 of file skill.cpp.
    : _ident( ident ), _name( name ), _description( description ), _tags( tags ),
      _display_type( display_type )
{
}
Member Function Documentation
companion_combat_rank_factor()
int Skill::companion_combat_rank_factor () const inline
Definition at line 84 of file skill.h.
{
            return _companion_combat_rank_factor;
        }
References _companion_combat_rank_factor.
companion_industry_rank_factor()
int Skill::companion_industry_rank_factor () const inline
Definition at line 90 of file skill.h.
{
            return _companion_industry_rank_factor;
        }
References _companion_industry_rank_factor.
companion_survival_rank_factor()
int Skill::companion_survival_rank_factor () const inline
Definition at line 87 of file skill.h.
{
            return _companion_survival_rank_factor;
        }
References _companion_survival_rank_factor.
description()
std::string Skill::description () const inline
Definition at line 71 of file skill.h.
{
            return _description.translated();
        }
References _description, and translation::translated().
Referenced by draw_skills_info(), set_skills(), and diary::skill_changes().
display_category()
skill_displayType_id Skill::display_category () const inline
Definition at line 78 of file skill.h.
{
            return _display_type;
        }
References _display_type.
Referenced by draw_skills_tab().
from_legacy_int()
skill_id Skill::from_legacy_int (int legacy_id) static
Definition at line 186 of file skill.cpp.
{
    static const std::array<skill_id, 28> legacy_skills = { {
            skill_id::NULL_ID(), skill_id( "dodge" ), skill_id( "melee" ), skill_id( "unarmed" ),
            skill_id( "bashing" ), skill_id( "cutting" ), skill_id( "stabbing" ), skill_id( "throw" ),
            skill_id( "gun" ), skill_id( "pistol" ), skill_id( "shotgun" ), skill_id( "smg" ),
            skill_id( "rifle" ), skill_id( "archery" ), skill_id( "launcher" ), skill_id( "mechanics" ),
            skill_id( "electronics" ), skill_id( "cooking" ), skill_id( "tailor" ), skill_id::NULL_ID(),
            skill_id( "firstaid" ), skill_id( "speech" ), skill_id( "barter" ), skill_id( "computer" ),
            skill_id( "survival" ), skill_id( "traps" ), skill_id( "swimming" ), skill_id( "driving" ),
        }
    };
    if( static_cast<size_t>( legacy_id ) < legacy_skills.size() ) {
        return legacy_skills[legacy_id];
    }
    debugmsg( "legacy skill id %d is invalid", legacy_id );
    return skills.front().ident(); // return a non-null id because callers might not expect a null-id
}
References debugmsg, string_id< Skill >::NULL_ID(), skill_id, and skills.
Referenced by npc_favor::deserialize().
get_companion_skill_practice()
int Skill::get_companion_skill_practice (const std::string & companion_skill) const inline
Definition at line 74 of file skill.h.
{
            return _companion_skill_practice.find( companion_skill ) == _companion_skill_practice.end() ? 0 :
                   _companion_skill_practice.at( companion_skill );
        }
References _companion_skill_practice.
get_skills_sorted_by()
std::vector< const Skill * > Skill::get_skills_sorted_by (std::function< bool(const Skill &, const Skill &)> pred) static
Definition at line 67 of file skill.cpp.
{
    std::vector<const Skill *> result;
    result.reserve( skills.size() );
    std::transform( begin( skills ), end( skills ), back_inserter( result ), []( const Skill & s ) {
        return &s;
    } );
    std::sort( begin( result ), end( result ), [&]( const Skill * lhs, const Skill * rhs ) {
        return pred( *lhs, *rhs );
    } );
    return result;
}
References skills, and iexamine::transform().
Referenced by character_display::disp_info(), npc::faction_display(), basecamp::recruit_return(), set_description(), set_skills(), and debug_menu::wishskill().
ident()
const skill_id & Skill::ident () const inline
Definition at line 65 of file skill.h.
{
            return _ident;
        }
References _ident.
Referenced by draw_skills_tab(), game::dump_stats(), handle_player_display_action(), load_skill(), set_skills(), and debug_menu::wishskill().
is_combat_skill()
bool Skill::is_combat_skill () const
Definition at line 211 of file skill.cpp.
{
    static const std::string combat_skill( "combat_skill" );
    return _tags.count( combat_skill ) > 0;
}
References _tags.
Referenced by Item_factory::check_definitions(), Character::do_skill_rust(), and player::practice().
is_contextual_skill()
bool Skill::is_contextual_skill () const
Definition at line 217 of file skill.cpp.
{
    static const std::string contextual_skill( "contextual_skill" );
    return _tags.count( contextual_skill ) > 0;
}
References _tags.
Referenced by SkillLevelMap::get_skill_level_object(), and load_skill().
load_skill()
void Skill::load_skill (const JsonObject & jsobj) static
Definition at line 90 of file skill.cpp.
{
    // TEMPORARY until 0.G: Remove "ident" support
    skill_id ident = skill_id( jsobj.has_string( "ident" ) ? jsobj.get_string( "ident" ) :
                               jsobj.get_string( "id" ) );
    skills.erase( std::remove_if( begin( skills ), end( skills ), [&]( const Skill & s ) {
        return s._ident == ident;
    } ), end( skills ) );
    translation name;
    jsobj.read( "name", name );
    translation desc;
    jsobj.read( "description", desc );
    std::unordered_map<std::string, int> companion_skill_practice;
    for( JsonObject jo_csp : jsobj.get_array( "companion_skill_practice" ) ) {
        companion_skill_practice.emplace( jo_csp.get_string( "skill" ), jo_csp.get_int( "weight" ) );
    }
    time_info_t time_to_attack;
    if( jsobj.has_object( "time_to_attack" ) ) {
        JsonObject jso_tta = jsobj.get_object( "time_to_attack" );
        jso_tta.read( "min_time", time_to_attack.min_time );
        jso_tta.read( "base_time", time_to_attack.base_time );
        jso_tta.read( "time_reduction_per_level", time_to_attack.time_reduction_per_level );
    }
    skill_displayType_id display_type = skill_displayType_id( jsobj.get_string( "display_category" ) );
    Skill sk( ident, name, desc, jsobj.get_tags( "tags" ), display_type );
    sk._time_to_attack = time_to_attack;
    sk._companion_combat_rank_factor = jsobj.get_int( "companion_combat_rank_factor", 0 );
    sk._companion_survival_rank_factor = jsobj.get_int( "companion_survival_rank_factor", 0 );
    sk._companion_industry_rank_factor = jsobj.get_int( "companion_industry_rank_factor", 0 );
    sk._companion_skill_practice = companion_skill_practice;
    if( sk.is_contextual_skill() ) {
        contextual_skills[sk.ident()] = sk;
    } else {
        skills.push_back( sk );
    }
}
References _companion_combat_rank_factor, _companion_industry_rank_factor, _companion_skill_practice, _companion_survival_rank_factor, _ident, _time_to_attack, time_info_t::base_time, contextual_skills, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_object(), JsonObject::has_string(), ident(), is_contextual_skill(), time_info_t::min_time, name(), JsonObject::read(), skill_id, skills, time_info_t::time_reduction_per_level, and time_to_attack().
Referenced by DynamicDataLoader::initialize().
name()
std::string Skill::name () const inline
Definition at line 68 of file skill.h.
{
            return _name.translated();
        }
References _name, and translation::translated().
Referenced by basic_item_filter(), item::book_info(), enzlave_actor::can_use(), talk_function::companion_choose(), basecamp::craft_description(), avatar::do_read(), Character::do_skill_rust(), draw_skills_tab(), Character::enumerate_unmet_requirements(), npc::finish_read(), dialogue::gen_responses(), avatar::get_book_reader(), player_activity::get_progress_message(), item::gun_info(), player::handle_skill_warning(), load_skill(), memorial_logger::notify(), player::practice(), avatar::read(), activity_handlers::repair_item_finish(), set_skills(), diary::skill_changes(), skim_book_msg(), read_inventory_preset::sort_compare(), Character::suffer_from_schizophrenia(), activity_handlers::train_finish(), veh_interact::update_part_requirements(), and debug_menu::wishskill().
operator!=()
bool Skill::operator!= (const Skill & b) const inline
Definition at line 98 of file skill.h.
{
            return !( *this == b );
        }
References b.
operator==()
bool Skill::operator== (const Skill & b) const inline
Definition at line 94 of file skill.h.
{
            return this->_ident == b._ident;
        }
References b.
random_skill()
skill_id Skill::random_skill () static
Definition at line 205 of file skill.cpp.
{
    return random_entry_ref( skills ).ident();
}
References random_entry_ref(), and skills.
Referenced by avatar::randomize(), and Character::suffer_from_schizophrenia().
reset()
void Skill::reset () static
Definition at line 84 of file skill.cpp.
{
    skills.clear();
    contextual_skills.clear();
}
References contextual_skills, and skills.
Referenced by DynamicDataLoader::unload_data().
time_to_attack()
time_info_t Skill::time_to_attack () const inline
Definition at line 81 of file skill.h.
{
            return _time_to_attack;
        }
References _time_to_attack.
Referenced by load_skill(), and time_to_attack().
Friends And Related Function Documentation
string_id< Skill >
friend class string_id< Skill > friend
Definition at line 29 of file skill.h.
Member Data Documentation
_companion_combat_rank_factor
int Skill::_companion_combat_rank_factor = 0 private
Definition at line 45 of file skill.h.
Referenced by companion_combat_rank_factor(), and load_skill().
_companion_industry_rank_factor
int Skill::_companion_industry_rank_factor = 0 private
Definition at line 47 of file skill.h.
Referenced by companion_industry_rank_factor(), and load_skill().
_companion_skill_practice
std::unordered_map<std::string, int> Skill::_companion_skill_practice private
Definition at line 42 of file skill.h.
Referenced by get_companion_skill_practice(), and load_skill().
_companion_survival_rank_factor
int Skill::_companion_survival_rank_factor = 0 private
Definition at line 46 of file skill.h.
Referenced by companion_survival_rank_factor(), and load_skill().
_description
translation Skill::_description private
Definition at line 38 of file skill.h.
Referenced by description().
_display_type
skill_displayType_id Skill::_display_type private
Definition at line 41 of file skill.h.
Referenced by display_category().
_ident
skill_id Skill::_ident private
Definition at line 35 of file skill.h.
Referenced by ident(), and load_skill().
_name
translation Skill::_name private
Definition at line 37 of file skill.h.
Referenced by name().
_tags
std::set<std::string> Skill::_tags private
Definition at line 39 of file skill.h.
Referenced by is_combat_skill(), and is_contextual_skill().
_time_to_attack
time_info_t Skill::_time_to_attack private
Definition at line 40 of file skill.h.
Referenced by load_skill(), and time_to_attack().
contextual_skills
std::map< skill_id, Skill > Skill::contextual_skills static private
Definition at line 44 of file skill.h.
Referenced by load_skill(), and reset().
skills
std::vector< Skill > Skill::skills static
Definition at line 49 of file skill.h.
Referenced by apply_all_to_unassigned(), companion_combat_rank(), companion_industry_rank(), talk_function::companion_skill_trainer(), companion_survival_rank(), game::dump_stats(), from_legacy_int(), get_skills_sorted_by(), load_skill(), diary::new_page(), random_skill(), npc::randomize(), reset(), and standard_npc::standard_npc().
The documentation for this class was generated from the following files:
src/skill.h
src/skill.cpp