Cataclysm BN: shape_factory Class Reference
shape_factory Class Reference
A class that produces shapes from two points: origin and destination.
#include <shape.h>
Public Member Functions
shape_factory ()
shape_factory (const shape_factory &)
~shape_factory ()
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
std::shared_ptr< shape > create (const tripoint &start, const tripoint &end) const
std::shared_ptr< shape > create (const rl_vec3d &start, const rl_vec3d &end) const
double get_range () const
std::string get_description () const
shape_factory & operator= (const shape_factory &other)
Private Attributes
std::shared_ptr< shape_factory_impl > impl
Detailed Description
A class that produces shapes from two points: origin and destination.
Definition at line 44 of file shape.h.
Constructor & Destructor Documentation
shape_factory() [1/2]
shape_factory::shape_factory () default
shape_factory() [2/2]
shape_factory::shape_factory (const shape_factory &) default
~shape_factory()
shape_factory::~shape_factory () default
Member Function Documentation
create() [1/2]
std::shared_ptr< shape > shape_factory::create (const rl_vec3d & start, const rl_vec3d & end) const
Definition at line 84 of file shape.cpp.
{
    if( impl == nullptr ) {
        return std::make_shared<shape>( std::make_shared<empty_shape>(), tripoint_zero );
    }
    return impl->create( start, end );
}
References impl, and tripoint_zero.
create() [2/2]
std::shared_ptr< shape > shape_factory::create (const tripoint & start, const tripoint & end) const
Definition at line 79 of file shape.cpp.
{
    return create( rl_vec3d( start ), rl_vec3d( end ) );
}
References create().
Referenced by create().
deserialize()
void shape_factory::deserialize (JsonIn & jsin)
Definition at line 65 of file shape.cpp.
{
    jsin.start_array();
    std::string type_string = jsin.get_string();
    if( type_string == "cone" ) {
        impl = std::make_shared<cone_factory>();
        impl->deserialize( jsin );
    } else {
        debugmsg( "Invalid type" );
        impl.reset();
    }
    jsin.end_array();
}
References debugmsg, JsonIn::end_array(), JsonIn::get_string(), impl, and JsonIn::start_array().
get_description()
std::string shape_factory::get_description () const
Definition at line 99 of file shape.cpp.
{
    if( impl == nullptr ) {
        return "BUGGED SHAPE DESCRIPTION";
    }
    return impl->get_description();
}
References impl.
get_range()
double shape_factory::get_range () const
Definition at line 92 of file shape.cpp.
{
    if( impl == nullptr ) {
        return 0.0;
    }
    return impl->get_range();
}
References impl.
Referenced by target_handler::mode_shaped().
operator=()
shape_factory & shape_factory::operator= (const shape_factory & other) default
serialize()
void shape_factory::serialize (JsonOut & jsout) const
Definition at line 50 of file shape.cpp.
{
    // TODO: poly_serialized should handle this with some rewriting
    jsout.start_array();
    if( impl != nullptr ) {
        jsout.write( impl->get_type() );
        jsout.start_object();
        impl->serialize( jsout );
        jsout.end_object();
    } else {
        jsout.write_null();
    }
    jsout.end_array();
}
References JsonOut::end_array(), JsonOut::end_object(), impl, JsonOut::start_array(), JsonOut::start_object(), JsonOut::write(), and JsonOut::write_null().
Member Data Documentation
impl
std::shared_ptr<shape_factory_impl> shape_factory::impl private
Definition at line 61 of file shape.h.
Referenced by create(), deserialize(), get_description(), get_range(), and serialize().
The documentation for this class was generated from the following files:
src/shape.h
src/shape.cpp