Cataclysm BN: detail::bigint Class Reference
detail::bigint Class Reference
#include <fmtlib_format-inl.h>
Public Member Functions
bigint ()
bigint (uint64_t n)
~bigint ()
bigint (const bigint &)=delete
void operator= (const bigint &)=delete
void assign (const bigint &other)
void assign (uint64_t n)
int num_bigits () const
FMT_NOINLINE bigint & operator<<= (int shift)
template<typename Int >
bigint & operator*= (Int value)
void assign_pow10 (int exp)
void square ()
void align (const bigint &other)
int divmod_assign (const bigint &divisor)
Private Types
enum { bigits_capacity = 32 }
using bigit = uint32_t
using double_bigit = uint64_t
Private Member Functions
bigit operator[] (int index) const
bigit & operator[] (int index)
void subtract_bigits (int index, bigit other, bigit &borrow)
void remove_leading_zeros ()
void subtract_aligned (const bigint &other)
void multiply (uint32_t value)
void multiply (uint64_t value)
Private Attributes
basic_memory_buffer< bigit, bigits_capacity > bigits_
int exp_
Static Private Attributes
static FMT_CONSTEXPR_DECL const int bigit_bits = bits<bigit>::value
Friends
struct formatter< bigint >
int compare (const bigint &lhs, const bigint &rhs)
int add_compare (const bigint &lhs1, const bigint &lhs2, const bigint &rhs)
Detailed Description
Definition at line 1314 of file fmtlib_format-inl.h.
Member Typedef Documentation
bigit
using detail::bigint::bigit = uint32_t private
Definition at line 1319 of file fmtlib_format-inl.h.
double_bigit
using detail::bigint::double_bigit = uint64_t private
Definition at line 1320 of file fmtlib_format-inl.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
bigits_capacity
Definition at line 1321 of file fmtlib_format-inl.h.
{ bigits_capacity = 32 };
Constructor & Destructor Documentation
bigint() [1/3]
detail::bigint::bigint () inline
Definition at line 1396 of file fmtlib_format-inl.h.
: exp_(0) {}
bigint() [2/3]
detail::bigint::bigint (uint64_t n) inline explicit
Definition at line 1397 of file fmtlib_format-inl.h.
{
            assign( n );
        }
References assign().
~bigint()
detail::bigint::~bigint () inline
Definition at line 1400 of file fmtlib_format-inl.h.
                  {
            assert( bigits_.capacity() <= bigits_capacity );
        }
References bigits_, and bigits_capacity.
bigint() [3/3]
detail::bigint::bigint (const bigint &) delete
Member Function Documentation
align()
void detail::bigint::align (const bigint & other) inline
Definition at line 1568 of file fmtlib_format-inl.h.
{
            int exp_difference = exp_ - other.exp_;
            if( exp_difference <= 0 ) {
                return;
            }
            int num_bigits = static_cast<int>( bigits_.size() );
            bigits_.resize( to_unsigned( num_bigits + exp_difference ) );
            for( int i = num_bigits - 1, j = i + exp_difference; i >= 0; --i, --j ) {
                bigits_[j] = bigits_[i];
            }
            std::uninitialized_fill_n( bigits_.data(), exp_difference, 0 );
            exp_ -= exp_difference;
        }
References bigits_, exp_, num_bigits(), other, and detail::to_unsigned().
Referenced by divmod_assign().
assign() [1/2]
void detail::bigint::assign (const bigint & other) inline
Definition at line 1407 of file fmtlib_format-inl.h.
{
            auto size = other.bigits_.size();
            bigits_.resize( size );
            auto data = other.bigits_.data();
            std::copy( data, data + size, make_checked( bigits_.data(), size ) );
            exp_ = other.exp_;
        }
References bigits_, exp_, detail::make_checked(), other, and om_direction::size.
Referenced by assign_pow10(), bigint(), and detail::fallback_format().
assign() [2/2]
void detail::bigint::assign (uint64_t n) inline
Definition at line 1415 of file fmtlib_format-inl.h.
{
            size_t num_bigits = 0;
            do {
                bigits_[num_bigits++] = n & ~bigit( 0 );
                n >>= bigit_bits;
            } while( n != 0 );
            bigits_.resize( num_bigits );
            exp_ = 0;
        }
References bigit_bits, bigits_, exp_, and num_bigits().
assign_pow10()
void detail::bigint::assign_pow10 (int exp) inline
Definition at line 1510 of file fmtlib_format-inl.h.
{
            assert( exp >= 0 );
            if( exp == 0 ) {
                return assign( 1 );
            }
            // Find the top bit.
            int bitmask = 1;
            while( exp >= bitmask ) {
                bitmask <<= 1;
            }
            bitmask >>= 1;
            // pow(10, exp) = pow(5, exp) * pow(2, exp). First compute pow(5, exp) by
            // repeated squaring and multiplication.
            assign( 5 );
            bitmask >>= 1;
            while( bitmask != 0 ) {
                square();
                if( ( exp & bitmask ) != 0 ) {
                    *this *= 5;
                }
                bitmask >>= 1;
            }
            *this <<= exp;  // Multiply by pow(2, exp) by shifting.
        }
References assign(), detail::exp, and square().
Referenced by detail::fallback_format().
divmod_assign()
int detail::bigint::divmod_assign (const bigint & divisor) inline
Definition at line 1584 of file fmtlib_format-inl.h.
{
            FMT_ASSERT( this != &divisor, "" );
            if( compare( *this, divisor ) < 0 ) {
                return 0;
            }
            FMT_ASSERT( divisor.bigits_[divisor.bigits_.size() - 1u] != 0, "" );
            align( divisor );
            int quotient = 0;
            do {
                subtract_aligned( divisor );
                ++quotient;
            } while( compare( *this, divisor ) >= 0 );
            return quotient;
        }
References align(), bigits_, compare, FMT_ASSERT, and subtract_aligned().
Referenced by detail::fallback_format().
multiply() [1/2]
void detail::bigint::multiply (uint32_t value) inline private
Definition at line 1365 of file fmtlib_format-inl.h.
{
            const double_bigit wide_value = value;
            bigit carry = 0;
            for( size_t i = 0, n = bigits_.size(); i < n; ++i ) {
                double_bigit result = bigits_[i] * wide_value + carry;
                bigits_[i] = static_cast<bigit>( result );
                carry = static_cast<bigit>( result >> bigit_bits );
            }
            if( carry != 0 ) {
                bigits_.push_back( carry );
            }
        }
References bigit_bits, and bigits_.
Referenced by operator*=().
multiply() [2/2]
void detail::bigint::multiply (uint64_t value) inline private
Definition at line 1378 of file fmtlib_format-inl.h.
{
            const bigit mask = ~bigit( 0 );
            const double_bigit lower = value & mask;
            const double_bigit upper = value >> bigit_bits;
            double_bigit carry = 0;
            for( size_t i = 0, n = bigits_.size(); i < n; ++i ) {
                double_bigit result = bigits_[i] * lower + ( carry & mask );
                carry =
                    bigits_[i] * upper + ( result >> bigit_bits ) + ( carry >> bigit_bits );
                bigits_[i] = static_cast<bigit>( result );
            }
            while( carry != 0 ) {
                bigits_.push_back( carry & mask );
                carry >>= bigit_bits;
            }
        }
References bigit_bits, and bigits_.
num_bigits()
int detail::bigint::num_bigits () const inline
Definition at line 1425 of file fmtlib_format-inl.h.
{
            return static_cast<int>( bigits_.size() ) + exp_;
        }
References bigits_, and exp_.
Referenced by align(), assign(), remove_leading_zeros(), and square().
operator*=()
template<typename Int > bigint & detail::bigint::operator*= (Int value) inline
Definition at line 1448 of file fmtlib_format-inl.h.
{
            FMT_ASSERT( value > 0, "" );
            multiply( uint32_or_64_or_128_t<Int>( value ) );
            return *this;
        }
References FMT_ASSERT, and multiply().
operator<<=()
FMT_NOINLINE bigint & detail::bigint::operator<<= (int shift) inline
Definition at line 1429 of file fmtlib_format-inl.h.
{
            assert( shift >= 0 );
            exp_ += shift / bigit_bits;
            shift %= bigit_bits;
            if( shift == 0 ) {
                return *this;
            }
            bigit carry = 0;
            for( size_t i = 0, n = bigits_.size(); i < n; ++i ) {
                bigit c = bigits_[i] >> ( bigit_bits - shift );
                bigits_[i] = ( bigits_[i] << shift ) + carry;
                carry = c;
            }
            if( carry != 0 ) {
                bigits_.push_back( carry );
            }
            return *this;
        }
References bigit_bits, bigits_, c, and exp_.
operator=()
void detail::bigint::operator= (const bigint &) delete
operator[]() [1/2]
bigit & detail::bigint::operator[] (int index) inline private
Definition at line 1328 of file fmtlib_format-inl.h.
{
            return bigits_[to_unsigned( index )];
        }
References bigits_, detail::index, and detail::to_unsigned().
operator[]() [2/2]
bigit detail::bigint::operator[] (int index) const inline private
Definition at line 1325 of file fmtlib_format-inl.h.
{
            return bigits_[to_unsigned( index )];
        }
References bigits_, detail::index, and detail::to_unsigned().
remove_leading_zeros()
void detail::bigint::remove_leading_zeros () inline private
Definition at line 1342 of file fmtlib_format-inl.h.
{
            int num_bigits = static_cast<int>( bigits_.size() ) - 1;
            while( num_bigits > 0 && ( *this )[num_bigits] == 0 ) {
                --num_bigits;
            }
            bigits_.resize( to_unsigned( num_bigits + 1 ) );
        }
References bigits_, num_bigits(), and detail::to_unsigned().
Referenced by square(), and subtract_aligned().
square()
void detail::bigint::square () inline
Definition at line 1535 of file fmtlib_format-inl.h.
                      {
            basic_memory_buffer<bigit, bigits_capacity> n( std::move( bigits_ ) );
            int num_bigits = static_cast<int>( bigits_.size() );
            int num_result_bigits = 2 * num_bigits;
            bigits_.resize( to_unsigned( num_result_bigits ) );
            using accumulator_t = conditional_t<FMT_USE_INT128, uint128_t, accumulator>;
            auto sum = accumulator_t();
            for( int bigit_index = 0; bigit_index < num_bigits; ++bigit_index ) {
                // Compute bigit at position bigit_index of the result by adding
                // cross-product terms n[i] * n[j] such that i + j == bigit_index.
                for( int i = 0, j = bigit_index; j >= 0; ++i, --j ) {
                    // Most terms are multiplied twice which can be optimized in the future.
                    sum += static_cast<double_bigit>( n[i] ) * n[j];
                }
                ( *this )[bigit_index] = static_cast<bigit>( sum );
                sum >>= bits<bigit>::value;  // Compute the carry.
            }
            // Do the same for the top half.
            for( int bigit_index = num_bigits; bigit_index < num_result_bigits;
                 ++bigit_index ) {
                for( int j = num_bigits - 1, i = bigit_index - j; i < num_bigits; ) {
                    sum += static_cast<double_bigit>( n[i++] ) * n[j--];
                }
                ( *this )[bigit_index] = static_cast<bigit>( sum );
                sum >>= bits<bigit>::value;
            }
            --num_result_bigits;
            remove_leading_zeros();
            exp_ *= 2;
        }
References bigits_, exp_, avatar_action::move(), num_bigits(), remove_leading_zeros(), and detail::to_unsigned().
Referenced by assign_pow10().
subtract_aligned()
void detail::bigint::subtract_aligned (const bigint & other) inline private
Definition at line 1351 of file fmtlib_format-inl.h.
{
            FMT_ASSERT( other.exp_ >= exp_, "unaligned bigints" );
            FMT_ASSERT( compare( *this, other ) >= 0, "" );
            bigit borrow = 0;
            int i = other.exp_ - exp_;
            for( size_t j = 0, n = other.bigits_.size(); j != n; ++i, ++j ) {
                subtract_bigits( i, other.bigits_[j], borrow );
            }
            while( borrow > 0 ) {
                subtract_bigits( i, 0, borrow );
            }
            remove_leading_zeros();
        }
References compare, exp_, FMT_ASSERT, other, remove_leading_zeros(), and subtract_bigits().
Referenced by divmod_assign().
subtract_bigits()
void detail::bigint::subtract_bigits (int index, bigit other, bigit & borrow) inline private
Definition at line 1336 of file fmtlib_format-inl.h.
{
            auto result = static_cast<double_bigit>( ( *this )[index] ) - other - borrow;
            ( *this )[index] = static_cast<bigit>( result );
            borrow = static_cast<bigit>( result >>( bigit_bits * 2 - 1 ) );
        }
References bigit_bits, detail::index, and other.
Referenced by subtract_aligned().
Friends And Related Function Documentation
add_compare
int add_compare (const bigint & lhs1, const bigint & lhs2, const bigint & rhs) friend
Definition at line 1478 of file fmtlib_format-inl.h.
{
            int max_lhs_bigits = ( std::max )( lhs1.num_bigits(), lhs2.num_bigits() );
            int num_rhs_bigits = rhs.num_bigits();
            if( max_lhs_bigits + 1 < num_rhs_bigits ) {
                return -1;
            }
            if( max_lhs_bigits > num_rhs_bigits ) {
                return 1;
            }
            auto get_bigit = []( const bigint & n, int i ) -> bigit {
                return i >= n.exp_ && i < n.num_bigits() ? n[i - n.exp_] : 0;
            };
            double_bigit borrow = 0;
            int min_exp = ( std::min )( ( std::min )( lhs1.exp_, lhs2.exp_ ), rhs.exp_ );
            for( int i = num_rhs_bigits - 1; i >= min_exp; --i ) {
                double_bigit sum =
                    static_cast<double_bigit>( get_bigit( lhs1, i ) ) + get_bigit( lhs2, i );
                bigit rhs_bigit = get_bigit( rhs, i );
                if( sum > rhs_bigit + borrow ) {
                    return 1;
                }
                borrow = rhs_bigit + borrow - sum;
                if( borrow > 1 ) {
                    return -1;
                }
                borrow <<= bigit_bits;
            }
            return borrow != 0 ? -1 : 0;
        }
compare
int compare (const bigint & lhs, const bigint & rhs) friend
Definition at line 1454 of file fmtlib_format-inl.h.
{
            int num_lhs_bigits = lhs.num_bigits(), num_rhs_bigits = rhs.num_bigits();
            if( num_lhs_bigits != num_rhs_bigits ) {
                return num_lhs_bigits > num_rhs_bigits ? 1 : -1;
            }
            int i = static_cast<int>( lhs.bigits_.size() ) - 1;
            int j = static_cast<int>( rhs.bigits_.size() ) - 1;
            int end = i - j;
            if( end < 0 ) {
                end = 0;
            }
            for( ; i >= end; --i, --j ) {
                bigit lhs_bigit = lhs[i], rhs_bigit = rhs[j];
                if( lhs_bigit != rhs_bigit ) {
                    return lhs_bigit > rhs_bigit ? 1 : -1;
                }
            }
            if( i != j ) {
                return i > j ? 1 : -1;
            }
            return 0;
        }
Referenced by divmod_assign(), and subtract_aligned().
formatter< bigint >
friend struct formatter< bigint > friend
Definition at line 1332 of file fmtlib_format-inl.h.
Member Data Documentation
bigit_bits
FMT_CONSTEXPR_DECL const int detail::bigint::bigit_bits = bits<bigit>::value static private
Definition at line 1332 of file fmtlib_format-inl.h.
Referenced by assign(), formatter< detail::bigint >::format(), multiply(), operator<<=(), and subtract_bigits().
bigits_
basic_memory_buffer<bigit, bigits_capacity> detail::bigint::bigits_ private
Definition at line 1322 of file fmtlib_format-inl.h.
Referenced by align(), assign(), divmod_assign(), formatter< detail::bigint >::format(), multiply(), num_bigits(), operator<<=(), operator[](), remove_leading_zeros(), square(), and ~bigint().
exp_
int detail::bigint::exp_ private
Definition at line 1323 of file fmtlib_format-inl.h.
Referenced by align(), assign(), formatter< detail::bigint >::format(), num_bigits(), operator<<=(), square(), and subtract_aligned().
The documentation for this class was generated from the following file:
src/fmtlib_format-inl.h