Cataclysm BN: saw_stock_actor Class Reference
saw_stock_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
saw_stock_actor (const std::string &type="saw_stock")
void load (const JsonObject &jo) override
int use (player &p, item &it, bool t, const tripoint &pnt) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
ret_val< bool > can_use_on (const player &p, const item &it, const item &target) const
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1145 of file iuse_actor.h.
Constructor & Destructor Documentation
saw_stock_actor()
saw_stock_actor::saw_stock_actor (const std::string & type = "saw_stock") inline
Definition at line 1148 of file iuse_actor.h.
: iuse_actor(type) {}
Member Function Documentation
can_use_on()
ret_val< bool > saw_stock_actor::can_use_on (const player & p, const item & it, const item & target) const
Definition at line 4345 of file iuse_actor.cpp.
{
    if( !target.is_gun() ) {
        return ret_val<bool>::make_failure( _( "It's not a gun." ) );
    }
    if( target.gunmod_find( itype_stock_small ) ) {
        return ret_val<bool>::make_failure( _( "The stock is already sawn-off." ) );
    }
    // Exclude pistols and the like that have had a stock mount bubba'd onto them.
    const auto gunmods = target.gunmods();
    const bool external_stock = std::any_of( gunmods.begin(), gunmods.end(),
    []( const item * mod ) {
        return mod->type->gunmod->location == gunmod_location( "stock mount" );
    } );
    if( external_stock ) {
        return ret_val<bool>::make_failure( _( "You can't saw anything off this." ) );
    }
    // Don't allow trying to stack stock mods.
    const bool modified_stock = std::any_of( gunmods.begin(), gunmods.end(),
    []( const item * mod ) {
        return mod->type->gunmod->location == gunmod_location( "stock" );
    } );
    if( modified_stock ) {
        return ret_val<bool>::make_failure( _( "Can't cut off modified stocks." ) );
    }
    // Also bail out if there's no unmodified stock to touch at all.
    if( target.get_free_mod_locations( gunmod_location( "stock" ) ) == 0 ||
        target.type->gun->skill_used == skill_id( "pistol" ) ) {
        return ret_val<bool>::make_failure(
                   _( "This doesn't have a stock." ) );
    }
    // Stock ideally should be made out of wood.
    if( !target.made_of( material_id( "wood" ) ) ) {
        return ret_val<bool>::make_failure(
                   _( "Can't cut off non-wooden stocks." ) );
    }
    return ret_val<bool>::make_success();
}
References _, item::get_free_mod_locations(), itype::gun, item::gunmod_find(), item::gunmods(), item::is_gun(), itype_stock_small, item::made_of(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and item::type.
Referenced by saw_stock_inventory_preset::get_denial().
clone()
std::unique_ptr< iuse_actor > saw_stock_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4392 of file iuse_actor.cpp.
{
    return std::make_unique<saw_stock_actor>( *this );
}
load()
void saw_stock_actor::load (const JsonObject & jo) override virtual
Implements iuse_actor.
Definition at line 4320 of file iuse_actor.cpp.
{
    assign( jo, "cost", cost );
}
References assign(), and iuse_actor::cost.
use()
int saw_stock_actor::use (player & p, item & it, bool t, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4325 of file iuse_actor.cpp.
{
    if( t ) {
        return 0;
    }
    auto loc = game_menus::inv::saw_stock( p, it );
    if( !loc ) {
        p.add_msg_if_player( _( "Never mind." ) );
        return 0;
    }
    item &obj = *loc.obtain( p );
    p.add_msg_if_player( _( "You saw down the stock of your %s." ), obj.tname() );
    obj.put_in( item( "stock_small", calendar::turn ) );
    return 0;
}
References _, player::add_msg_if_player(), item::put_in(), game_menus::inv::saw_stock(), item::tname(), and calendar::turn.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp