Cataclysm BN: jmapgen_trap Class Reference
jmapgen_trap Class Reference
Place a trap.
Public Member Functions
jmapgen_trap (const JsonObject &jsi)
jmapgen_trap (const std::string &tid)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, const point &p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
trap_id id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a trap.
"trap": id of the trap.
Definition at line 1420 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_trap() [1/2]
jmapgen_trap::jmapgen_trap (const JsonObject & jsi) inline
Definition at line 1424 of file mapgen.cpp.
                                              :
            id( 0 ) {
            const trap_str_id sid( jsi.get_string( "trap" ) );
            if( !sid.is_valid() ) {
                set_mapgen_defer( jsi, "trap", "no such trap" );
            }
            id = sid.id();
        }
References JsonObject::get_string(), string_id< T >::id(), string_id< T >::is_valid(), mapgen_defer::jsi, and set_mapgen_defer().
jmapgen_trap() [2/2]
jmapgen_trap::jmapgen_trap (const std::string & tid) inline
Definition at line 1433 of file mapgen.cpp.
                                             :
            id( 0 ) {
            const trap_str_id sid( tid );
            if( !sid.is_valid() ) {
                throw std::runtime_error( "unknown trap type" );
            }
            id = sid.id();
        }
References string_id< T >::id(), and string_id< T >::is_valid().
Member Function Documentation
apply()
void jmapgen_trap::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1441 of file mapgen.cpp.
{
            const tripoint actual_loc = tripoint( x.get(), y.get(), dat.m.get_abs_sub().z );
            dat.m.trap_set( actual_loc, id );
        }
References jmapgen_int::get(), map::get_abs_sub(), mapgendata::m, map::trap_set(), and tripoint::z.
has_vehicle_collision()
bool jmapgen_trap::has_vehicle_collision (mapgendata & dat, const point & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1445 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
id
trap_id jmapgen_trap::id
Definition at line 1423 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp