Cataclysm BN: towing_data Class Reference
towing_data Class Reference
#include <vehicle.h>
Public Member Functions
towing_data (vehicle *towed_veh=nullptr, vehicle *tower_veh=nullptr)
vehicle * get_towed_by () const
bool set_towing (vehicle *tower_veh, vehicle *towed_veh)
vehicle * get_towed () const
void clear_towing ()
Public Attributes
towing_point_side tow_direction
tripoint other_towing_point
Private Attributes
vehicle * towing
vehicle * towed_by
Detailed Description
Definition at line 146 of file vehicle.h.
Constructor & Destructor Documentation
towing_data()
towing_data::towing_data (vehicle * towed_veh = nullptr, vehicle * tower_veh = nullptr) inline
Definition at line 152 of file vehicle.h.
                                                                                  :
            towing( towed_veh ), towed_by( tower_veh ) {}
Member Function Documentation
clear_towing()
void towing_data::clear_towing () inline
Definition at line 161 of file vehicle.h.
{
            towing = nullptr;
            towed_by = nullptr;
        }
References towed_by, and towing.
Referenced by veh_interact::complete_vehicle(), vehicle::invalidate_towing(), vehicle::shed_loose_parts(), and vehicle::split_vehicles().
get_towed()
vehicle * towing_data::get_towed () const inline
Definition at line 158 of file vehicle.h.
{
            return towing;
        }
References towing.
Referenced by veh_interact::complete_vehicle(), vehicle::do_towing_move(), vehicle::ground_acceleration(), vehicle::invalidate_towing(), vehicle::is_towed(), vehicle::is_towing(), map::move_vehicle(), vehicle::no_towing_slack(), vehicle::shed_loose_parts(), vehicle::slowdown(), vehicle::split_vehicles(), vehicle::thrust(), vehicle::tow_cable_too_far(), and vehicle::water_acceleration().
get_towed_by()
vehicle * towing_data::get_towed_by () const inline
Definition at line 154 of file vehicle.h.
{
            return towed_by;
        }
References towed_by.
Referenced by veh_interact::complete_vehicle(), vehicle::invalidate_towing(), vehicle::is_towed(), vehicle::is_towing(), vehicle::no_towing_slack(), vehicle::shed_loose_parts(), vehicle::split_vehicles(), and vehicle::tow_cable_too_far().
set_towing()
bool towing_data::set_towing (vehicle * tower_veh, vehicle * towed_veh)
Definition at line 6117 of file vehicle.cpp.
{
    if( !towed_veh || !tower_veh ) {
        return false;
    }
    towed_veh->tow_data.towed_by = tower_veh;
    tower_veh->tow_data.towing = towed_veh;
    tower_veh->set_tow_directions();
    towed_veh->set_tow_directions();
    return true;
}
References vehicle::set_tow_directions(), vehicle::tow_data, towed_by, and towing.
Referenced by vehicle::split_vehicles(), iuse::tow_attach(), and game::validate_linked_vehicles().
Member Data Documentation
other_towing_point
tripoint towing_data::other_towing_point
Definition at line 167 of file vehicle.h.
Referenced by game::validate_linked_vehicles().
tow_direction
towing_point_side towing_data::tow_direction
Definition at line 165 of file vehicle.h.
Referenced by vehicle::do_towing_move(), and vehicle::set_tow_directions().
towed_by
vehicle* towing_data::towed_by private
Definition at line 150 of file vehicle.h.
Referenced by clear_towing(), get_towed_by(), and set_towing().
towing
vehicle* towing_data::towing private
Definition at line 149 of file vehicle.h.
Referenced by clear_towing(), get_towed(), and set_towing().
The documentation for this class was generated from the following files:
src/vehicle.h
src/vehicle.cpp