Cataclysm BN: wash_activity_actor Class Reference
wash_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
wash_activity_actor ()=default
wash_activity_actor (const iuse_locations &targets, int moves_total)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Attributes
iuse_locations targets
int moves_total = 0
Detailed Description
Definition at line 504 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
wash_activity_actor() [1/2]
wash_activity_actor::wash_activity_actor () default
wash_activity_actor() [2/2]
wash_activity_actor::wash_activity_actor (const iuse_locations & targets, int moves_total) inline
Definition at line 512 of file activity_actor_definitions.h.
                                                                              :
            targets( targets ), moves_total( moves_total ) {};
Member Function Documentation
clone()
std::unique_ptr< activity_actor > wash_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 523 of file activity_actor_definitions.h.
{
            return std::make_unique<wash_activity_actor>( *this );
        }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > wash_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 1253 of file activity_actor.cpp.
{
    wash_activity_actor actor;
    JsonObject data = jsin.get_object();
    data.read( "targets", actor.targets );
    data.read( "moves_total", actor.moves_total );
    return actor.clone();
}
References clone(), JsonIn::get_object(), moves_total, JsonObject::read(), and targets.
do_turn()
void wash_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 520 of file activity_actor_definitions.h.
{};
finish()
void wash_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 743 of file activity_item_handling.cpp.
{
    // Check again that we have enough water and soap incase the amount in our inventory changed somehow
    // Consume the water and soap
    units::volume total_volume = 0_ml;
    for( const auto &it : targets ) {
        total_volume += it.loc->volume() * it.count / it.loc->count();
    }
    washing_requirements required = washing_requirements_for_volume( total_volume );
    const auto is_liquid_crafting_component = []( const item & it ) {
        return is_crafting_component( it ) && ( !it.count_by_charges() || it.made_of( LIQUID ) ||
                                                it.contents_made_of( LIQUID ) );
    };
    const inventory &crafting_inv = who.crafting_inventory();
    if( !crafting_inv.has_charges( itype_water, required.water, is_liquid_crafting_component ) &&
        !crafting_inv.has_charges( itype_water_clean, required.water, is_liquid_crafting_component ) ) {
        who.add_msg_if_player( _( "You need %1$i charges of water or clean water to wash these items." ),
                               required.water );
        act.set_to_null();
        return;
    } else if( !crafting_inv.has_charges( itype_soap, required.cleanser ) &&
               !crafting_inv.has_charges( itype_detergent, required.cleanser ) ) {
        who.add_msg_if_player( _( "You need %1$i charges of cleansing agent to wash these items." ),
                               required.cleanser );
        act.set_to_null();
        return;
    }
    for( auto &i : targets ) {
        item &it = *i.loc;
        if( i.count >= it.count() ) {
            if( i.count > it.count() ) {
                debugmsg( "Invalid item count to wash: tried %d, max %d", i.count, it.count() );
            }
            it.item_tags.erase( "FILTHY" );
        } else {
            item it2 = it;
            it.charges -= i.count;
            it2.charges = i.count;
            it2.item_tags.erase( "FILTHY" );
            std::list<item> tmp;
            tmp.push_back( it2 );
            put_into_vehicle_or_drop( who, item_drop_reason::deliberate, tmp );
        }
        who.on_worn_item_washed( it );
    }
    std::vector<item_comp> comps;
    comps.push_back( item_comp( itype_water, required.water ) );
    comps.push_back( item_comp( itype_water_clean, required.water ) );
    who.as_player()->consume_items( comps, 1, is_liquid_crafting_component );
    std::vector<item_comp> comps1;
    comps1.push_back( item_comp( itype_soap, required.cleanser ) );
    comps1.push_back( item_comp( itype_detergent, required.cleanser ) );
    who.as_player()->consume_items( comps1 );
    who.add_msg_if_player( m_good, _( "You washed your items." ) );
    // Make sure newly washed components show up as available if player attempts to craft immediately
    who.invalidate_crafting_inventory();
    act.set_to_null();
}
References _, act, Creature::add_msg_if_player(), Creature::as_player(), item::charges, washing_requirements::cleanser, player::consume_items(), item::count(), Character::crafting_inventory(), debugmsg, deliberate, cata::flat_set< T, Compare, Data >::erase(), inventory::has_charges(), Character::invalidate_crafting_inventory(), is_crafting_component(), item::item_tags, itype_detergent, itype_soap, itype_water, itype_water_clean, LIQUID, m_good, Character::on_worn_item_washed(), put_into_vehicle_or_drop(), targets, washing_requirements_for_volume(), and washing_requirements::water.
get_type()
activity_id wash_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 515 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_WASH" );
        }
serialize()
void wash_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1243 of file activity_actor.cpp.
{
    jsout.start_object();
    jsout.member( "targets", targets );
    jsout.member( "moves_total", moves_total );
    jsout.end_object();
}
References JsonOut::end_object(), JsonOut::member(), moves_total, JsonOut::start_object(), and targets.
start()
void wash_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1128 of file activity_actor.cpp.
{
    act.moves_total = moves_total;
    act.moves_left = moves_total;
}
References act, and moves_total.
Member Data Documentation
moves_total
int wash_activity_actor::moves_total = 0 private
Definition at line 508 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
targets
iuse_locations wash_activity_actor::targets private
Definition at line 507 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp
src/activity_item_handling.cpp