Cataclysm BN: JsonArray Class Reference
JsonArray Class Reference
#include <json.h>
Classes
class const_iterator
Public Member Functions
JsonArray (JsonIn &jsin)
JsonArray (const JsonArray &ja)
JsonArray ()
~JsonArray ()
JsonArray & operator= (const JsonArray &)
void finish ()
bool has_more () const
size_t size () const
bool empty ()
std::string str ()
void throw_error (std::string err)
void throw_error (std::string err, int idx)
void show_warning (std::string err)
void show_warning (std::string err, int idx)
bool next_bool ()
int next_int ()
double next_float ()
std::string next_string ()
JsonArray next_array ()
JsonObject next_object ()
void skip_value ()
bool get_bool (size_t index) const
int get_int (size_t index) const
double get_float (size_t index) const
std::string get_string (size_t index) const
JsonArray get_array (size_t index) const
JsonObject get_object (size_t index) const
template<typename T = std::string>
std::set< T > get_tags (size_t index) const
const_iterator begin () const
const_iterator end () const
bool test_null () const
bool test_bool () const
bool test_number () const
bool test_int () const
bool test_float () const
bool test_string () const
bool test_bitset () const
bool test_array () const
bool test_object () const
bool has_null (size_t index) const
bool has_bool (size_t index) const
bool has_number (size_t index) const
bool has_int (size_t index) const
bool has_float (size_t index) const
bool has_string (size_t index) const
bool has_array (size_t index) const
bool has_object (size_t index) const
template<typename T >
bool read_next (T &t)
template<typename T >
bool read (size_t i, T &t, bool throw_on_error=false) const
Private Member Functions
void verify_index (size_t i) const
Private Attributes
std::vector< size_t > positions
int start
size_t index
int end_
bool final_separator
JsonIn * jsin
Detailed Description
Definition at line 1026 of file json.h.
Constructor & Destructor Documentation
JsonArray() [1/3]
JsonArray::JsonArray (JsonIn & jsin)
Definition at line 506 of file json.cpp.
{
    jsin = &j;
    start = jsin->tell();
    index = 0;
    // cache the position of each element
    jsin->start_array();
    while( !jsin->end_array() ) {
        positions.push_back( jsin->tell() );
        jsin->skip_value();
    }
    end_ = jsin->tell();
    final_separator = jsin->get_ate_separator();
}
References end_, JsonIn::end_array(), final_separator, JsonIn::get_ate_separator(), index, jsin, positions, JsonIn::skip_value(), start, JsonIn::start_array(), and JsonIn::tell().
JsonArray() [2/3]
JsonArray::JsonArray (const JsonArray & ja)
Definition at line 521 of file json.cpp.
{
    jsin = ja.jsin;
    start = ja.start;
    index = 0;
    positions = ja.positions;
    end_ = ja.end_;
    final_separator = ja.final_separator;
}
References end_, final_separator, index, jsin, positions, and start.
JsonArray() [3/3]
JsonArray::JsonArray () inline
Definition at line 1040 of file json.h.
: start(0), index(0), end_(0), final_separator(false), jsin(nullptr) {}
~JsonArray()
JsonArray::~JsonArray () inline
Definition at line 1041 of file json.h.
                     {
            finish();
        }
References finish().
Member Function Documentation
begin()
JsonArray::const_iterator JsonArray::begin () const inline
Definition at line 1230 of file json.h.
{
    return const_iterator( *this, 0 );
}
empty()
bool JsonArray::empty ()
Definition at line 559 of file json.cpp.
{
    return positions.empty();
}
References positions.
Referenced by Item_factory::load(), and Item_factory::load_basic_info().
end()
JsonArray::const_iterator JsonArray::end () const inline
Definition at line 1235 of file json.h.
{
    return const_iterator( *this, size() );
}
References size().
finish()
void JsonArray::finish ()
Definition at line 543 of file json.cpp.
{
    if( jsin && jsin->good() ) {
        jsin->seek( end_ );
        jsin->set_ate_separator( final_separator );
    }
}
References end_, final_separator, JsonIn::good(), jsin, JsonIn::seek(), and JsonIn::set_ate_separator().
Referenced by ~JsonArray().
get_array()
JsonArray JsonArray::get_array (size_t index) const
Definition at line 665 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->get_array();
}
References JsonIn::get_array(), jsin, positions, JsonIn::seek(), and verify_index().
Referenced by get_random_tip_of_the_day(), jmapgen_monster::jmapgen_monster(), mutation_branch::load(), Item_factory::load_basic_info(), Item_factory::load_item_group(), load_mapgen(), load_place_mapings_alternatively(), mutation_branch::load_trait_group(), load_transform_results(), load_weighted_entries(), and MonsterGroupManager::LoadMonsterGroup().
get_bool()
bool JsonArray::get_bool (size_t index) const
Definition at line 637 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->get_bool();
}
References JsonIn::get_bool(), jsin, positions, JsonIn::seek(), and verify_index().
get_float()
double JsonArray::get_float (size_t index) const
Definition at line 651 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->get_float();
}
References JsonIn::get_float(), jsin, positions, JsonIn::seek(), and verify_index().
Referenced by extract_effect().
get_int()
int JsonArray::get_int (size_t index) const
Definition at line 644 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->get_int();
}
References JsonIn::get_int(), jsin, positions, JsonIn::seek(), and verify_index().
Referenced by mtype::add_special_attack(), mission::deserialize(), jmapgen_int::jmapgen_int(), jmapgen_monster::jmapgen_monster(), mtype::load(), tool_comp::load(), item_comp::load(), color_loader< ColorType >::load_colors(), load_distribution(), Item_factory::load_item_group(), mutation_branch::load_trait_group(), load_transform_results(), load_weighted_entries(), and mapgen_function_json_nested::setup_internal().
get_object()
JsonObject JsonArray::get_object (size_t index) const
Definition at line 672 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->get_object();
}
References JsonIn::get_object(), jsin, positions, JsonIn::seek(), and verify_index().
get_string()
std::string JsonArray::get_string (size_t index) const
Definition at line 658 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->get_string();
}
References JsonIn::get_string(), jsin, positions, JsonIn::seek(), and verify_index().
Referenced by mtype::add_special_attack(), vehicle_part::deserialize(), item_reader::get_next(), jmapgen_monster::jmapgen_monster(), ma_technique::load(), mtype::load(), tool_comp::load(), item_comp::load(), Item_factory::load_basic_info(), Item_factory::load_item_group(), mutation_branch::load_trait_group(), load_transform_results(), load_weighted_entries(), and mapgen_function_json_base::setup_common().
get_tags()
template<typename T > std::set< T > JsonArray::get_tags (size_t index) const
Definition at line 1309 of file json.h.
{
    std::set<T> res;
    verify_index( index );
    jsin->seek( positions[ index ] );
    // allow single string as tag
    if( jsin->test_string() ) {
        res.insert( T( jsin->get_string() ) );
        return res;
    }
    for( const std::string line : jsin->get_array() ) {
        res.insert( T( line ) );
    }
    return res;
}
References JsonIn::get_array(), JsonIn::get_string(), index, jsin, line(), positions, JsonIn::seek(), JsonIn::test_string(), and verify_index().
has_array()
bool JsonArray::has_array (size_t index) const
Definition at line 774 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->test_array();
}
References jsin, positions, JsonIn::seek(), JsonIn::test_array(), and verify_index().
has_bool()
bool JsonArray::has_bool (size_t index) const
Definition at line 753 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->test_bool();
}
References jsin, positions, JsonIn::seek(), JsonIn::test_bool(), and verify_index().
has_float()
bool JsonArray::has_float (size_t index) const inline
Definition at line 1105 of file json.h.
{
            return has_number( index );
        }
References has_number(), and index.
has_int()
bool JsonArray::has_int (size_t index) const inline
Definition at line 1102 of file json.h.
{
            return has_number( index );
        }
References has_number(), and index.
has_more()
bool JsonArray::has_more () const
Definition at line 551 of file json.cpp.
{
    return index < positions.size();
}
References index, and positions.
Referenced by Character::load(), monster::load(), disease_type::load(), mtype::load(), Item_factory::load_basic_info(), load_distribution(), io::detail::has_archive_tag< T, typename enable_if_type< typename T::archive_type_tag >::type >::read(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), and test_string().
has_null()
bool JsonArray::has_null (size_t index) const
Definition at line 746 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->test_null();
}
References jsin, positions, JsonIn::seek(), JsonIn::test_null(), and verify_index().
has_number()
bool JsonArray::has_number (size_t index) const
Definition at line 760 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->test_number();
}
References jsin, positions, JsonIn::seek(), JsonIn::test_number(), and verify_index().
Referenced by has_float(), and has_int().
has_object()
bool JsonArray::has_object (size_t index) const
Definition at line 781 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->test_object();
}
References jsin, positions, JsonIn::seek(), JsonIn::test_object(), and verify_index().
has_string()
bool JsonArray::has_string (size_t index) const
Definition at line 767 of file json.cpp.
{
    verify_index( i );
    jsin->seek( positions[i] );
    return jsin->test_string();
}
References jsin, positions, JsonIn::seek(), JsonIn::test_string(), and verify_index().
Referenced by mtype::load().
next_array()
JsonArray JsonArray::next_array ()
Definition at line 615 of file json.cpp.
{
    verify_index( index );
    jsin->seek( positions[index++] );
    return jsin->get_array();
}
References JsonIn::get_array(), index, jsin, positions, JsonIn::seek(), and verify_index().
next_bool()
bool JsonArray::next_bool ()
Definition at line 587 of file json.cpp.
{
    verify_index( index );
    jsin->seek( positions[index++] );
    return jsin->get_bool();
}
References JsonIn::get_bool(), index, jsin, positions, JsonIn::seek(), and verify_index().
next_float()
double JsonArray::next_float ()
Definition at line 601 of file json.cpp.
{
    verify_index( index );
    jsin->seek( positions[index++] );
    return jsin->get_float();
}
References JsonIn::get_float(), index, jsin, positions, JsonIn::seek(), and verify_index().
next_int()
int JsonArray::next_int ()
Definition at line 594 of file json.cpp.
{
    verify_index( index );
    jsin->seek( positions[index++] );
    return jsin->get_int();
}
References JsonIn::get_int(), index, jsin, positions, JsonIn::seek(), and verify_index().
Referenced by load_place_mapings_alternatively(), and MonsterGroupManager::LoadMonsterGroup().
next_object()
JsonObject JsonArray::next_object ()
Definition at line 622 of file json.cpp.
{
    verify_index( index );
    jsin->seek( positions[index++] );
    return jsin->get_object();
}
References JsonIn::get_object(), index, jsin, positions, JsonIn::seek(), and verify_index().
Referenced by mtype::load(), load_distribution(), and load_place_mapings_alternatively().
next_string()
std::string JsonArray::next_string ()
Definition at line 608 of file json.cpp.
{
    verify_index( index );
    jsin->seek( positions[index++] );
    return jsin->get_string();
}
References JsonIn::get_string(), index, jsin, positions, JsonIn::seek(), and verify_index().
Referenced by json_talk_topic::load(), disease_type::load(), Item_factory::load_basic_info(), and load_place_mapings_alternatively().
operator=()
JsonArray & JsonArray::operator= (const JsonArray & ja)
Definition at line 531 of file json.cpp.
{
    jsin = ja.jsin;
    start = ja.start;
    index = 0;
    positions = ja.positions;
    end_ = ja.end_;
    final_separator = ja.final_separator;
    return *this;
}
References end_, final_separator, index, jsin, positions, and start.
read()
template<typename T > bool JsonArray::read (size_t i, T & t, bool throw_on_error = false) const inline
Definition at line 1119 of file json.h.
{
            verify_index( i );
            jsin->seek( positions[i] );
            return jsin->read( t, throw_on_error );
        }
References jsin, positions, JsonIn::read(), JsonIn::seek(), and verify_index().
Referenced by assign(), tool_comp::load(), and item_comp::load().
read_next()
template<typename T > bool JsonArray::read_next (T & t) inline
Definition at line 1113 of file json.h.
{
            verify_index( index );
            jsin->seek( positions[index++] );
            return jsin->read( t );
        }
References index, jsin, positions, JsonIn::read(), JsonIn::seek(), and verify_index().
Referenced by Character::load(), monster::load(), load_min_max(), and io::detail::has_archive_tag< T, E >::read().
show_warning() [1/2]
void JsonArray::show_warning (std::string err)
Definition at line 268 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    try {
        throw_error( err );
    } catch( const std::exception &e ) {
        debugmsg( "%s", e.what() );
    }
#else
    ( void )err;
#endif // CATA_IN_TOOL
}
References debugmsg, and throw_error().
show_warning() [2/2]
void JsonArray::show_warning (std::string err, int idx)
Definition at line 281 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    try {
        throw_error( err, idx );
    } catch( const std::exception &e ) {
        debugmsg( "%s", e.what() );
    }
#else
    ( void )err;
    ( void )idx;
#endif // CATA_IN_TOOL
}
References debugmsg, and throw_error().
size()
size_t JsonArray::size () const
Definition at line 555 of file json.cpp.
{
    return positions.size();
}
References positions.
Referenced by mission::deserialize(), vehicle_part::deserialize(), end(), extract_effect(), get_random_tip_of_the_day(), jmapgen_int::jmapgen_int(), tool_comp::load(), item_comp::load(), load_mapgen(), load_place_mapings_alternatively(), load_region_overlay(), and mapgen_function_json_base::setup_common().
skip_value()
void JsonArray::skip_value ()
Definition at line 629 of file json.cpp.
{
    verify_index( index );
    ++index;
}
References index, and verify_index().
str()
std::string JsonArray::str ()
Definition at line 564 of file json.cpp.
{
    if( jsin ) {
        return jsin->substr( start, end_ - start );
    } else {
        return "[]";
    }
}
References end_, jsin, start, and JsonIn::substr().
test_array()
bool JsonArray::test_array () const
Definition at line 726 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_array();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_array().
Referenced by load_mapgen().
test_bitset()
bool JsonArray::test_bitset () const
Definition at line 717 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_bitset();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_bitset().
test_bool()
bool JsonArray::test_bool () const
Definition at line 690 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_bool();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_bool().
test_float()
bool JsonArray::test_float () const inline
Definition at line 1090 of file json.h.
{
            return test_number();
        }
References test_number().
test_int()
bool JsonArray::test_int () const inline
Definition at line 1087 of file json.h.
{
            return test_number();
        }
References test_number().
Referenced by load_place_mapings_alternatively().
test_null()
bool JsonArray::test_null () const
Definition at line 681 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_null();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_null().
test_number()
bool JsonArray::test_number () const
Definition at line 699 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_number();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_number().
Referenced by test_float(), and test_int().
test_object()
bool JsonArray::test_object () const
Definition at line 735 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_object();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_object().
Referenced by load_place_mapings_alternatively().
test_string()
bool JsonArray::test_string () const
Definition at line 708 of file json.cpp.
{
    if( !has_more() ) {
        return false;
    }
    jsin->seek( positions[index] );
    return jsin->test_string();
}
References has_more(), index, jsin, positions, JsonIn::seek(), and JsonIn::test_string().
Referenced by load_place_mapings_alternatively().
throw_error() [1/2]
void JsonArray::throw_error (std::string err)
Definition at line 214 of file json.cpp.
{
    if( !jsin ) {
        throw JsonError( err );
    }
    jsin->error( err );
}
References JsonIn::error(), and jsin.
Referenced by mtype::add_special_attack(), mtype::load(), load_place_mapings_alternatively(), mapgen_function_json_base::setup_common(), and show_warning().
throw_error() [2/2]
void JsonArray::throw_error (std::string err, int idx)
Definition at line 222 of file json.cpp.
{
    if( !jsin ) {
        throw JsonError( err );
    }
    if( idx >= 0 && size_t( idx ) < positions.size() ) {
        jsin->seek( positions[idx] );
    }
    jsin->error( err );
}
References JsonIn::error(), jsin, positions, and JsonIn::seek().
verify_index()
void JsonArray::verify_index (size_t i) const private
Definition at line 573 of file json.cpp.
{
    if( !jsin ) {
        throw JsonError( "tried to access empty array." );
    } else if( i >= positions.size() ) {
        jsin->seek( start );
        std::stringstream err;
        err << "bad index value: " << i;
        jsin->error( err.str() );
    }
}
References JsonIn::error(), jsin, positions, JsonIn::seek(), and start.
Referenced by get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), JsonArray::const_iterator::operator*(), read(), read_next(), and skip_value().
Member Data Documentation
end_
int JsonArray::end_ private
Definition at line 1032 of file json.h.
Referenced by finish(), JsonArray(), operator=(), and str().
final_separator
bool JsonArray::final_separator private
Definition at line 1033 of file json.h.
Referenced by finish(), JsonArray(), and operator=().
index
size_t JsonArray::index private
Definition at line 1031 of file json.h.
Referenced by get_tags(), has_float(), has_int(), has_more(), JsonArray(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), operator=(), read_next(), skip_value(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), and test_string().
jsin
JsonIn* JsonArray::jsin private
Definition at line 1034 of file json.h.
Referenced by finish(), get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), JsonArray(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), JsonArray::const_iterator::operator*(), operator=(), read(), read_next(), str(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), throw_error(), and verify_index().
positions
std::vector<size_t> JsonArray::positions private
Definition at line 1029 of file json.h.
Referenced by empty(), get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), get_tags(), has_array(), has_bool(), has_more(), has_null(), has_number(), has_object(), has_string(), JsonArray(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), JsonArray::const_iterator::operator*(), operator=(), read(), read_next(), size(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), throw_error(), and verify_index().
start
int JsonArray::start private
Definition at line 1030 of file json.h.
Referenced by JsonArray(), operator=(), str(), and verify_index().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp