Cataclysm BN: auto_pickup::rule Class Reference
auto_pickup::rule Class Reference
A single entry in the list of auto pickup entries rule_list.
#include <auto_pickup.h>
Public Member Functions
rule ()=default
rule (const std::string &r, const bool a, const bool e)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
void test_pattern () const
Public Attributes
std::string sRule
bool bActive = false
bool bExclude = false
Detailed Description
A single entry in the list of auto pickup entries rule_list.
The data contained can be edited by the player and determines what to pick/ignore.
Definition at line 41 of file auto_pickup.h.
Constructor & Destructor Documentation
rule() [1/2]
auto_pickup::rule::rule () default
rule() [2/2]
auto_pickup::rule::rule (const std::string & r, const bool a, const bool e) inline
Definition at line 50 of file auto_pickup.h.
                                                               : sRule( r ), bActive( a ), bExclude( e ) {
        }
Member Function Documentation
deserialize()
void rule::deserialize (JsonIn & jsin)
Definition at line 777 of file auto_pickup.cpp.
{
    JsonObject jo = jsin.get_object();
    sRule = jo.get_string( "rule" );
    bActive = jo.get_bool( "active" );
    bExclude = jo.get_bool( "exclude" );
}
References bActive, bExclude, JsonObject::get_bool(), JsonIn::get_object(), JsonObject::get_string(), and sRule.
Referenced by auto_pickup::rule_list::deserialize().
serialize()
void rule::serialize (JsonOut & jsout) const
Definition at line 759 of file auto_pickup.cpp.
{
    jsout.start_object();
    jsout.member( "rule", sRule );
    jsout.member( "active", bActive );
    jsout.member( "exclude", bExclude );
    jsout.end_object();
}
References bActive, bExclude, JsonOut::end_object(), JsonOut::member(), sRule, and JsonOut::start_object().
Referenced by auto_pickup::rule_list::serialize().
test_pattern()
void rule::test_pattern () const
Definition at line 413 of file auto_pickup.cpp.
{
    std::vector<std::string> vMatchingItems;
    if( sRule.empty() ) {
        return;
    }
    //Loop through all itemfactory items
    //APU now ignores prefixes, bottled items and suffix combinations still not generated
    for( const itype *e : item_controller->all() ) {
        const std::string sItemName = e->nname( 1 );
        if( !check_special_rule( e->materials, sRule ) && !wildcard_match( sItemName, sRule ) ) {
            continue;
        }
        vMatchingItems.push_back( sItemName );
    }
    int iStartPos = 0;
    int iContentHeight = 0;
    int iContentWidth = 0;
    catacurses::window w_test_rule_border;
    catacurses::window w_test_rule_content;
    ui_adaptor ui;
    const auto init_windows = [&]( ui_adaptor & ui ) {
        const point iOffset( 15 + ( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 ),
                             5 + ( TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 :
                                   0 ) );
        iContentHeight = FULL_SCREEN_HEIGHT - 8;
        iContentWidth = FULL_SCREEN_WIDTH - 30;
        w_test_rule_border = catacurses::newwin( iContentHeight + 2, iContentWidth,
                             iOffset );
        w_test_rule_content = catacurses::newwin( iContentHeight,
                              iContentWidth - 2,
                              iOffset + point_south_east );
        ui.position_from_window( w_test_rule_border );
    };
    init_windows( ui );
    ui.on_screen_resize( init_windows );
    int nmatch = vMatchingItems.size();
    const std::string buf = string_format( vgettext( "%1$d item matches: %2$s",
                                           "%1$d items match: %2$s",
                                           nmatch ), nmatch, sRule );
    int iLine = 0;
    input_context ctxt( "AUTO_PICKUP_TEST" );
    ctxt.register_updown();
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ui.on_redraw( [&]( const ui_adaptor & ) {
        draw_border( w_test_rule_border, BORDER_COLOR, buf, hilite( c_white ) );
        center_print( w_test_rule_border, iContentHeight + 1, red_background( c_white ),
                      _( "Won't display content or suffix matches" ) );
        wnoutrefresh( w_test_rule_border );
        // Clear the lines
        for( int i = 0; i < iContentHeight; i++ ) {
            for( int j = 0; j < 79; j++ ) {
                mvwputch( w_test_rule_content, point( j, i ), c_black, ' ' );
            }
        }
        calcStartPos( iStartPos, iLine, iContentHeight, vMatchingItems.size() );
        // display auto pickup
        for( int i = iStartPos; i < static_cast<int>( vMatchingItems.size() ); i++ ) {
            if( i >= iStartPos &&
                i < iStartPos + ( iContentHeight > static_cast<int>( vMatchingItems.size() ) ?
                                  static_cast<int>( vMatchingItems.size() ) : iContentHeight ) ) {
                nc_color cLineColor = c_white;
                mvwprintz( w_test_rule_content, point( 0, i - iStartPos ), cLineColor, "%d", i + 1 );
                mvwprintz( w_test_rule_content, point( 4, i - iStartPos ), cLineColor, "" );
                if( iLine == i ) {
                    wprintz( w_test_rule_content, c_yellow, ">> " );
                } else {
                    wprintz( w_test_rule_content, c_yellow, "   " );
                }
                wprintz( w_test_rule_content, iLine == i ? hilite( cLineColor ) : cLineColor, vMatchingItems[i] );
            }
        }
        wnoutrefresh( w_test_rule_content );
    } );
    while( true ) {
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "DOWN" ) {
            iLine++;
            if( iLine >= static_cast<int>( vMatchingItems.size() ) ) {
                iLine = 0;
            }
        } else if( action == "UP" ) {
            iLine--;
            if( iLine < 0 ) {
                iLine = vMatchingItems.size() - 1;
            }
        } else if( action == "QUIT" ) {
            break;
        }
    }
}
References _, action, BORDER_COLOR, c_black, c_white, c_yellow, calcStartPos(), center_print(), check_special_rule(), draw_border(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::handle_input(), hilite(), item_controller, mvwprintz(), mvwputch(), catacurses::newwin(), point_south_east, red_background(), ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), sRule, string_format(), TERMX, TERMY, vgettext(), wildcard_match(), catacurses::wnoutrefresh(), and wprintz().
Member Data Documentation
bActive
bool auto_pickup::rule::bActive = false
Definition at line 45 of file auto_pickup.h.
Referenced by auto_pickup::rule_list::create_rule(), deserialize(), auto_pickup::rule_list::refresh_map_items(), and serialize().
bExclude
bool auto_pickup::rule::bExclude = false
Definition at line 46 of file auto_pickup.h.
Referenced by auto_pickup::rule_list::create_rule(), deserialize(), auto_pickup::rule_list::refresh_map_items(), and serialize().
sRule
std::string auto_pickup::rule::sRule
Definition at line 44 of file auto_pickup.h.
Referenced by auto_pickup::rule_list::create_rule(), deserialize(), auto_pickup::rule_list::refresh_map_items(), serialize(), and test_pattern().
The documentation for this class was generated from the following files:
src/auto_pickup.h
src/auto_pickup.cpp