Cataclysm BN: VehicleSpawn Class Reference
VehicleSpawn Class Reference
This class handles a weighted list of different spawn functions, allowing a single vehicle_spawn to have multiple possibilities.
#include <vehicle_group.h>
Public Member Functions
VehicleSpawn ()=default
void add (const double &weight, const shared_ptr_fast< VehicleFunction > &func)
void apply (map &m, const std::string &terrain_name) const
This will invoke the vehicle spawn on the map.
Static Public Member Functions
static void apply (const vspawn_id &id, map &m, const std::string &terrain_name)
A static helper function.
static void load (const JsonObject &jo)
static void reset ()
Private Types
using FunctionMap = std::unordered_map< std::string, vehicle_gen_pointer >
Private Attributes
weighted_float_list< shared_ptr_fast< VehicleFunction > > types
Static Private Attributes
static FunctionMap builtin_functions
Detailed Description
This class handles a weighted list of different spawn functions, allowing a single vehicle_spawn to have multiple possibilities.
Definition at line 156 of file vehicle_group.h.
Member Typedef Documentation
FunctionMap
using VehicleSpawn::FunctionMap = std::unordered_map<std::string, vehicle_gen_pointer> private
Definition at line 186 of file vehicle_group.h.
Constructor & Destructor Documentation
VehicleSpawn()
VehicleSpawn::VehicleSpawn () default
Member Function Documentation
add()
void VehicleSpawn::add (const double & weight, const shared_ptr_fast< VehicleFunction > & func) inline
Definition at line 161 of file vehicle_group.h.
{
            types.add( func, weight );
        }
References types.
Referenced by load().
apply() [1/2]
void VehicleSpawn::apply (const vspawn_id & id, map & m, const std::string & terrain_name) static
A static helper function.
This will invoke the supplied vehicle spawn on the map.
Parameters
id The spawnid to apply
m The map on which to add the vehicle.
terrain_name The name of the terrain being spawned on.
Definition at line 210 of file vehicle_group.cpp.
{
    id.obj().apply( m, terrain_name );
}
apply() [2/2]
void VehicleSpawn::apply (map & m, const std::string & terrain_name) const
This will invoke the vehicle spawn on the map.
Parameters
m The map on which to add the vehicle.
terrain_name The name of the terrain being spawned on.
Definition at line 200 of file vehicle_group.cpp.
{
    const shared_ptr_fast<VehicleFunction> *func = types.pick();
    if( func == nullptr ) {
        debugmsg( "unable to find valid function for vehicle spawn" );
    } else {
        ( *func )->apply( m, terrain_name );
    }
}
References debugmsg, and types.
Referenced by mapgen_highway(), mapgen_parking_lot(), and mapgen_subway().
load()
void VehicleSpawn::load (const JsonObject & jo) static
Definition at line 175 of file vehicle_group.cpp.
{
    VehicleSpawn &spawn = vspawns[vspawn_id( jo.get_string( "id" ) )];
    for( JsonObject type : jo.get_array( "spawn_types" ) ) {
        if( type.has_object( "vehicle_json" ) ) {
            JsonObject vjo = type.get_object( "vehicle_json" );
            spawn.add( type.get_float( "weight" ), make_shared_fast<VehicleFunction_json>( vjo ) );
        } else if( type.has_string( "vehicle_function" ) ) {
            if( builtin_functions.count( type.get_string( "vehicle_function" ) ) == 0 ) {
                type.throw_error( "load_vehicle_spawn: unable to find builtin function", "vehicle_function" );
            }
            spawn.add( type.get_float( "weight" ), make_shared_fast<VehicleFunction_builtin>
                       ( builtin_functions[type.get_string( "vehicle_function" )] ) );
        } else {
            type.throw_error( "load_vehicle_spawn: missing required vehicle_json (object) or vehicle_function (string)." );
        }
    }
}
References add(), builtin_functions, JsonObject::get_array(), JsonObject::get_string(), type, and vspawns.
Referenced by DynamicDataLoader::initialize().
reset()
void VehicleSpawn::reset () static
Definition at line 195 of file vehicle_group.cpp.
{
    vspawns.clear();
}
References vspawns.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
builtin_functions
VehicleSpawn::FunctionMap VehicleSpawn::builtin_functions static private
Initial value:
= {
    { "no_vehicles", VehicleSpawnFunction::builtin_no_vehicles },
    { "jack-knifed_semi", VehicleSpawnFunction::builtin_jackknifed_semi },
    { "vehicle_pileup", VehicleSpawnFunction::builtin_citypileup },
    { "policecar_pileup", VehicleSpawnFunction::builtin_policepileup },
    { "parkinglot", VehicleSpawnFunction::builtin_parkinglot }
}
Definition at line 187 of file vehicle_group.h.
Referenced by load().
types
weighted_float_list<shared_ptr_fast<VehicleFunction> > VehicleSpawn::types private
Definition at line 184 of file vehicle_group.h.
Referenced by add(), and apply().
The documentation for this class was generated from the following files:
src/vehicle_group.h
src/vehicle_group.cpp