Cataclysm BN: spell_events Class Reference
spell_events Class Reference
#include <magic.h>
Public Member Functions
void notify (const cata::event &) override
Public Member Functions inherited from event_subscriber
event_subscriber ()=default
event_subscriber (const event_subscriber &)=delete
event_subscriber & operator= (const event_subscriber &)=delete
virtual ~event_subscriber ()
Detailed Description
Definition at line 125 of file magic.h.
Member Function Documentation
notify()
void spell_events::notify (const cata::event & e) override virtual
Implements event_subscriber.
Definition at line 2100 of file magic.cpp.
{
    switch( e.type() ) {
        case event_type::player_levels_spell: {
            spell_id sid = e.get<spell_id>( "spell" );
            int slvl = e.get<int>( "new_level" );
            spell_type spell_cast = spell_factory.obj( sid );
            for( std::map<std::string, int>::iterator it = spell_cast.learn_spells.begin();
                 it != spell_cast.learn_spells.end(); ++it ) {
                std::string learn_spell_id = it->first;
                int learn_at_level = it->second;
                if( learn_at_level == slvl ) {
                    g->u.magic->learn_spell( learn_spell_id, g->u );
                    spell_type spell_learned = spell_factory.obj( spell_id( learn_spell_id ) );
                    add_msg(
                        _( "Your experience and knowledge in creating and manipulating magical energies to cast %s have opened your eyes to new possibilities, you can now cast %s." ),
                        spell_cast.name,
                        spell_learned.name );
                }
            }
            break;
        }
        default:
            break;
    }
}
References _, add_msg(), g, cata::event::get(), spell_type::name, player_levels_spell, anonymous_namespace{magic.cpp}::spell_factory, spell_id, and cata::event::type().
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp