Cataclysm BN: Creature Class Reference
Creature Class Reference abstract
#include <creature.h>
Public Types
enum Attitude : int { A_HOSTILE , A_NEUTRAL , A_FRIENDLY , A_ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Public Member Functions
virtual ~Creature ()
virtual std::string get_name () const =0
virtual std::string disp_name (bool possessive=false, bool capitalize_first=false) const =0
virtual std::string skin_name () const =0
virtual std::vector< std::string > get_grammatical_genders () const
virtual bool is_player () const
virtual bool is_avatar () const
virtual bool is_npc () const
virtual bool is_monster () const
virtual monster * as_monster ()
virtual const monster * as_monster () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual Character * as_character ()
virtual const Character * as_character () const
virtual player * as_player ()
virtual const player * as_player () const
virtual avatar * as_avatar ()
virtual const avatar * as_avatar () const
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
virtual void process_turn ()
Processes effects and bonuses and allocates move points based on speed.
virtual void reset_bonuses ()
Resets the value of all bonus fields to 0.
virtual void reset_stats ()=0
Resets stats, and applies effects in an idempotent manner.
virtual void reset ()
Handles stat and bonus reset.
virtual void bleed () const
Adds an appropriate blood splatter.
virtual void die (Creature *killer)=0
Empty function.
virtual float hit_roll () const =0
Should always be overwritten by the appropriate player/NPC/monster version.
virtual float dodge_roll ()=0
virtual float stability_roll () const =0
virtual Attitude attitude_to (const Creature &other) const =0
Attitude (of this creature) towards another creature.
virtual bool avoid_trap (const tripoint &pos, const trap &tr) const =0
Called when a creature triggers a trap, returns true if they don't set it off.
virtual bool sees (const Creature &critter) const
The functions check whether this creature can see the target.
virtual bool sees (const tripoint &t, bool is_avatar=false, int range_mod=0) const
virtual int sight_range (int light_level) const =0
How far the creature sees under the given light.
virtual float power_rating () const =0
Returns an approximation of the creature's strength.
virtual float speed_rating () const =0
Returns an approximate number of tiles this creature can travel per turn.
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
virtual bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &dam)=0
virtual void absorb_hit (const bodypart_id &bp, damage_instance &dam)=0
void knock_back_from (const tripoint &p)
virtual void knock_back_to (const tripoint &to)=0
Knocks the creature to a specified tile.
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, const damage_instance &dam, dealt_damage_instance &dealt_dam)
virtual void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack)
Attempts to harm a creature with a projectile.
virtual dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &dam)
Deals the damage via an attack.
virtual void deal_damage_handle_type (const damage_unit &du, bodypart_id bp, int &damage, int &pain)
virtual void apply_damage (Creature *source, bodypart_id bp, int amount, bool bypass_med=false)=0
virtual void on_dodge (Creature *source, int difficulty)
This creature just dodged an attack - possibly special/ranged attack - from source.
virtual void on_hit (Creature *source, bodypart_id bp_hit, dealt_projectile_attack const *proj=nullptr)=0
This creature just got hit by an attack - possibly special/ranged attack - from source.
virtual bool digging () const
virtual bool is_on_ground () const =0
virtual bool is_underwater () const
virtual void set_underwater (bool x)
virtual bool is_warm () const
virtual bool in_species (const species_id &) const
virtual bool has_weapon () const =0
virtual bool is_hallucination () const =0
virtual bool is_dead_state () const =0
virtual bool is_elec_immune () const =0
virtual bool is_immune_effect (const efftype_id &type) const =0
virtual bool is_immune_damage (damage_type type) const =0
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
virtual bool is_immune_field (const field_type_id &) const
Returns true if we are immune to the field type with the given fid.
virtual float fall_damage_mod () const =0
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
virtual int impact (int force, const tripoint &pos)=0
Deals falling/collision damage with terrain/creature at pos.
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
virtual int posx () const =0
virtual int posy () const =0
virtual int posz () const =0
virtual const tripoint & pos () const =0
virtual void setpos (const tripoint &pos)=0
virtual bool move_effects (bool attacking)=0
Processes move stopping effects.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
virtual void add_effect (const efftype_id &eff_id, const time_duration &dur, const bodypart_str_id &bp, int intensity=0, bool force=false, bool deferred=false)
Adds or modifies an effect.
void add_effect (const efftype_id &eff_id, const time_duration &dur, body_part bp=num_bp, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp=num_bp, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp, bool REMOVED, int intensity=1, bool force=false)=delete
bool remove_effect (const efftype_id &eff_id, body_part bp=num_bp)
Removes a listed effect.
virtual bool remove_effect (const efftype_id &eff_id, const bodypart_str_id &bp)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id, const bodypart_str_id &bp) const
bool has_effect_with_flag (const std::string &flag, body_part bp=num_bp) const
Check if creature has any effect with the given flag.
const effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp)
std::vector< const effect * > get_all_effects_of_type (const efftype_id &eff_id) const
Returns pointers to all effects matching given type.
time_duration get_effect_dur (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
virtual units::mass get_weight () const =0
void process_effects ()
Processes through all the effects on the Creature.
virtual void process_effects_internal ()=0
Processes effects according to class (monster, player)
virtual bool has_trait (const trait_id &flag) const
Returns true if the player has the entered trait, returns false for non-humans.
virtual void mod_pain (int npain)
virtual void mod_pain_noresist (int npain)
virtual void set_pain (int npain)
virtual int get_pain () const
virtual int get_perceived_pain () const
virtual std::pair< std::string, nc_color > get_pain_description () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual bool in_sleep_state () const
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_env_resist (bodypart_id bp) const
virtual int get_armor_bash (bodypart_id bp) const
virtual int get_armor_cut (bodypart_id bp) const
virtual int get_armor_bullet (bodypart_id bp) const
virtual int get_armor_bash_base (bodypart_id bp) const
virtual int get_armor_cut_base (bodypart_id bp) const
virtual int get_armor_bullet_base (bodypart_id bp) const
virtual int get_armor_bash_bonus () const
virtual int get_armor_cut_bonus () const
virtual int get_armor_bullet_bonus () const
virtual int get_armor_type (damage_type dt, bodypart_id bp) const =0
virtual float get_dodge () const
virtual float get_melee () const =0
Returns melee skill level, to be used to throttle dodge practice.
virtual float get_hit () const
virtual int get_speed () const
virtual m_size get_size () const =0
virtual int get_hp (const bodypart_id &bp) const
virtual int get_hp () const
virtual int get_hp_max (const bodypart_id &bp) const
virtual int get_hp_max () const
virtual int hp_percentage () const =0
Returns overall % of HP remaining.
virtual bool made_of (const material_id &m) const =0
virtual bool made_of_any (const std::set< material_id > &ms) const =0
virtual field_type_id bloodType () const =0
virtual field_type_id gibType () const =0
virtual bool has_flag (const m_flag) const
virtual bool uncanny_dodge ()
Handles the uncanny dodge bionic and effects, returns true if the creature successfully dodges.
anatomy_id get_anatomy () const
void set_anatomy (anatomy_id anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (bool only_main=false) const
Returns body parts this creature have.
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bodypart * get_part (const bodypart_id &id)
bodypart get_part (const bodypart_id &id) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
void set_part_hp_cur (const bodypart_id &id, int set)
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void mod_part_hp_cur (const bodypart_id &id, int mod)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual float get_dodge_base () const =0
virtual float get_hit_base () const =0
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual bool has_grab_break_tec () const =0
virtual void mod_stat (const std::string &stat, float modifier)
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_bash_bonus (int nbasharm)
virtual void set_armor_cut_bonus (int ncutarm)
virtual void set_armor_bullet_bonus (int nbulletarm)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
virtual units::mass weight_capacity () const
virtual const pathfinding_settings & get_pathfinding_settings () const =0
Returns settings for pathfinding.
virtual std::set< tripoint > get_path_avoid () const =0
Returns a set of points we do not want to path through.
void draw (const catacurses::window &w, point origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
virtual int print_info (const catacurses::window &w, int vStart, int vLines, int column) const =0
Write information about this creature.
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
virtual void add_msg_if_player (const std::string &) const
virtual void add_msg_if_player (const game_message_params &, const std::string &) const
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_player_or_npc (const std::string &, const std::string &) const
virtual void add_msg_player_or_npc (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
virtual void add_msg_player_or_say (const std::string &, const std::string &) const
virtual void add_msg_player_or_say (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
virtual std::string extended_description () const =0
virtual nc_color symbol_color () const =0
virtual nc_color basic_symbol_color () const =0
virtual const std::string & symbol () const =0
virtual bool is_symbol_highlighted () const
effects_map get_all_effects () const
body_part select_body_part (Creature *source, int hit_roll) const
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
Static Public Member Functions
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
static void reset_hit_range ()
Public Attributes
FacingDirection facing = FD_RIGHT
return the direction the creature is facing, for sdl horizontal flip
int moves = 0
Static Public Attributes
static const std::map< std::string, m_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit = default_dispersion_for_ecogh
Protected Member Functions
void set_killer (Creature *killer)
virtual void process_one_effect (effect &e, bool is_new)=0
Processes one effect on the Creature.
Creature ()
Creature (const Creature &)=default
Creature (Creature &&)=default
Creature & operator= (const Creature &)=default
Creature & operator= (Creature &&)=default
virtual void on_stat_change (const std::string &, int)
virtual void on_effect_int_change (const efftype_id &, int, const bodypart_str_id &)
virtual void on_damage_of_type (int, damage_type, const bodypart_id &)
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Protected Attributes
Creature * killer = nullptr
pimpl< effects_map > effects
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
int armor_bash_bonus = 0
int armor_cut_bonus = 0
int armor_bullet_bonus = 0
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0
int block_bonus = 0
float hit_bonus = 0.0
bool fake = false
Private Attributes
anatomy_id creature_anatomy = anatomy_id("default_anatomy")
anatomy is the plan of the creature's body
std::map< bodypart_str_id, bodypart > body
this is the actual body of the creature
int pain = 0
bool underwater = false
Detailed Description
Definition at line 77 of file creature.h.
Member Enumeration Documentation
Attitude
enum Creature::Attitude : int
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
neutral - anything between. friendly - avoid harming it, maybe even help. any - any of the above, used in safemode_ui
Enumerator
A_HOSTILE
A_NEUTRAL
A_FRIENDLY
A_ANY
Definition at line 166 of file creature.h.
                      : int {
            A_HOSTILE,
            A_NEUTRAL,
            A_FRIENDLY,
            A_ANY
        };
Constructor & Destructor Documentation
~Creature()
Creature::~Creature () virtual default
Creature() [1/3]
Creature::Creature () protected
Definition at line 100 of file creature.cpp.
{
    moves = 0;
    pain = 0;
    killer = nullptr;
    speed_base = 100;
    underwater = false;
    Creature::reset_bonuses();
    fake = false;
}
References fake, killer, moves, pain, reset_bonuses(), speed_base, and underwater.
Creature() [2/3]
Creature::Creature (const Creature &) protected default
Creature() [3/3]
Creature::Creature (Creature &&) protected default
Member Function Documentation
absorb_hit()
virtual void Creature::absorb_hit (const bodypart_id & bp, damage_instance & dam) pure virtual
Implemented in Character, and monster.
Referenced by deal_damage().
add_effect() [1/3]
void Creature::add_effect (const effect & eff, bool force = false, bool deferred = false)
Definition at line 986 of file creature.cpp.
{
    add_effect( eff.get_id(), eff.get_duration(), eff.get_bp(), eff.get_intensity(),
                force, deferred );
}
References add_effect(), deferred, effect::get_bp(), effect::get_duration(), effect::get_id(), and effect::get_intensity().
Referenced by Character::absorb_hit(), Character::activate_bionic(), enchantment::activate_passive(), add_effect(), monster::add_effect(), add_effect_to_target(), add_env_effect(), addict_effect(), npc::address_player(), iuse::adrenaline_injector(), alcohol(), iuse::antiasthmatic(), iuse::antibiotic(), iuse::anticonvulsant(), ma_buff::apply_buff(), map::apply_character_light(), iuse::artifact(), npc::assess_danger(), iexamine::autodoc(), mattack::bio_op_impale(), mattack::bio_op_takedown(), iuse::blech(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), cauterize_actor::cauterize_effect(), Character::check_needs_extremes(), Character::consume_effects(), iuse::contacts(), Character::cough(), map::creature_in_field(), map::crush(), iuse::datura(), Character::deal_damage(), deal_damage_handle_type(), talk_function::deny_equipment(), talk_function::deny_follow(), talk_function::deny_lead(), talk_function::deny_personal_info(), talk_function::deny_train(), mattack::dermatik(), Character::do_damage_for_bionic_failure(), character_funcs::do_pause(), Character::eat(), iuse::ecig(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_mutating(), eff_fun_spores(), eff_fun_toxin_buildup(), npc::execute_action(), Character::expose_to_disease(), Character::fall_asleep(), heal_actor::finish_using(), mattack::flame(), mattack::flesh_golem(), iexamine::flower_marloss(), iexamine::flower_poppy(), iuse::flumed(), iuse::flusleep(), mattack::formblob(), mattack::fungus_bristle(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::give_equipment(), mattack::grab(), mattack::grab_drag(), start_location::handle_heli_crash(), Character::hardcoded_effects(), Character::heat_emission(), Character::impact(), mattack::impale(), iuse::inhaler(), Character::install_bionics(), Character::introduce_into_anesthesia(), iuse::jet_injector(), Character::knock_back_to(), game::knockback(), mattack::longswipe(), mattack::lunge(), iuse::melatonin_tablet(), Character::melee_attack(), monster::melee_attack(), Character::mend(), iuse::meth(), Character::modify_stimulation(), game::mon_info_update(), Character::mount_creature(), npc::move_to(), mattack::nurse_assist(), mattack::nurse_check_up(), melee_actor::on_damage(), bite_actor::on_damage(), Character::on_hit(), Character::on_hurt(), npc::on_load(), activity_handlers::operation_do_turn(), mattack::para_sting(), vehicle::part_collision(), Character::perform_technique(), teleporter_list::place_avatar_overmap(), game::place_player(), iuse::play_music(), map::player_in_field(), iuse::poison(), turret_data::prepare_fire(), game::process_artifact(), item::process_litcig(), sounds::process_sound_markers(), projectile_attack(), iuse::prozac(), mattack::ranged_pull(), npc::reboot(), Character::reset_stats(), talk_effect_fun_t::set_add_effect(), npc::set_attitude(), mattack::shriek_stun(), sleep(), game::start_game(), talk_function::start_training(), iuse::stimpack(), mattack::stretch_bite(), iuse::strong_antibiotic(), Character::suffer(), Character::suffer_from_artifacts(), Character::suffer_from_asthma(), Character::suffer_from_bad_bionics(), Character::suffer_from_other_mutations(), Character::suffer_from_schizophrenia(), Character::suffer_from_stimulants(), Character::suffer_while_awake(), Character::suffer_without_sleep(), mattack::tankgun(), teleport::teleport(), test_crossing_threshold(), iuse::thorazine(), gun_actor::try_target(), Character::uninstall_bionic(), Character::update_bodytemp(), game::update_stair_monsters(), Character::update_vitamins(), consume_drug_iuse::use(), change_scent_iuse::use(), musical_instrument_actor::use(), mutagen_actor::use(), game::validate_mounted_npcs(), Character::vomit(), wait(), iuse::weak_antibiotic(), iuse::weed_cake(), and iuse::xanax().
add_effect() [2/3]
void Creature::add_effect (const efftype_id & eff_id, const time_duration & dur, body_part bp = num_bp, int intensity = 0, bool force = false, bool deferred = false)
Definition at line 993 of file creature.cpp.
{
    add_effect( eff_id, dur, convert_bp( bp ), intensity, force, deferred );
}
References add_effect(), convert_bp(), and deferred.
add_effect() [3/3]
void Creature::add_effect (const efftype_id & eff_id, const time_duration & dur, const bodypart_str_id & bp, int intensity = 0, bool force = false, bool deferred = false) virtual
Adds or modifies an effect.
If intensity is given it will set the effect intensity to the given value, or as close as max_intensity values permit.
Reimplemented in monster.
Definition at line 999 of file creature.cpp.
{
    // Check our innate immunity
    if( !force && is_immune_effect( eff_id ) ) {
        return;
    }
    if( eff_id == efftype_id( "knockdown" ) && ( has_effect( effect_ridden ) ||
            has_effect( effect_riding ) ) ) {
        monster *mons = dynamic_cast<monster *>( this );
        if( mons && mons->mounted_player ) {
            mons->mounted_player->forced_dismount();
        }
    }
    if( !eff_id.is_valid() ) {
        debugmsg( "Invalid effect, ID: %s", eff_id.c_str() );
        return;
    }
    const effect_type &type = eff_id.obj();
    bodypart_str_id bp = base_bp;
    // Mutate to a main (HP'd) body_part if necessary.
    if( type.get_main_parts() ) {
        bp = bp->main_part;
    }
    bool found = false;
    // Check if we already have it
    auto matching_map = effects->find( eff_id );
    if( matching_map != effects->end() ) {
        auto &bodyparts = matching_map->second;
        auto found_effect = bodyparts.find( bp );
        if( found_effect != bodyparts.end() && !found_effect->second.is_removed() ) {
            found = true;
            effect &e = found_effect->second;
            const int prev_int = e.get_intensity();
            // If we do, mod the duration, factoring in the mod value
            e.mod_duration( time_duration::from_turns( static_cast<int>(
                                to_turns<int64_t>( dur ) * e.get_dur_add_perc() / 100 ) ) );
            // Limit to max duration
            if( e.get_max_duration() > 0_turns && e.get_duration() > e.get_max_duration() ) {
                e.set_duration( e.get_max_duration() );
            }
            // int_dur_factor overrides all other intensity settings
            // ...but it's handled in set_duration, so explicitly do nothing here
            if( e.get_int_dur_factor() > 0_turns ) {
                // Set intensity if value is given
            } else if( intensity > 0 ) {
                e.set_intensity( intensity );
                // Else intensity uses the type'd step size if it already exists
            } else if( e.get_int_add_val() != 0 ) {
                e.mod_intensity( e.get_int_add_val() );
            }
            // Bound intensity by [1, max intensity]
            if( e.get_intensity() < 1 ) {
                add_msg( m_debug, "Bad intensity, ID: %s", e.get_id().c_str() );
                e.set_intensity( 1 );
            } else if( e.get_intensity() > e.get_max_intensity() ) {
                e.set_intensity( e.get_max_intensity() );
            }
            if( e.get_intensity() != prev_int ) {
                on_effect_int_change( e.get_id(), e.get_intensity(), e.get_bp() );
            }
        }
    }
    if( !found ) {
        // If we don't already have it then add a new one
        // Then check if the effect is blocked by another
        for( const auto &elem : *effects ) {
            for( auto &_effect_it : elem.second ) {
                if( !_effect_it.second.is_removed() )
                    for( const auto &blocked_effect : _effect_it.second.get_blocks_effects() ) {
                        if( blocked_effect == eff_id ) {
                            // The effect is blocked by another, return
                            return;
                        }
                    }
            }
        }
        // Now we can make the new effect for application
        effect e( &type, dur, bp, intensity, calendar::turn );
        // Bound to max duration
        if( e.get_max_duration() > 0_turns && e.get_duration() > e.get_max_duration() ) {
            e.set_duration( e.get_max_duration() );
        }
        // Force intensity if it is duration based
        if( e.get_int_dur_factor() != 0_turns ) {
            // + 1 here so that the lowest is intensity 1, not 0
            e.set_intensity( e.get_duration() / e.get_int_dur_factor() + 1 );
        }
        // Bound new effect intensity by [1, max intensity]
        if( e.get_intensity() < 1 ) {
            add_msg( m_debug, "Bad intensity, ID: %s", e.get_id().c_str() );
            e.set_intensity( 1 );
        } else if( e.get_intensity() > e.get_max_intensity() ) {
            e.set_intensity( e.get_max_intensity() );
        }
        ( *effects )[eff_id][bp] = e;
        if( Character *ch = as_character() ) {
            g->events().send<event_type::character_gains_effect>( ch->getID(), eff_id );
            if( is_player() && !type.get_apply_message().empty() ) {
                add_msg( type.gain_game_message_type(), _( type.get_apply_message() ) );
            }
        }
        on_effect_int_change( e.get_id(), e.get_intensity(), e.get_bp() );
        // Perform any effect addition effects.
        // only when not deferred
        if( !deferred ) {
            process_one_effect( e, true );
        }
    }
}
References _, add_msg(), as_character(), string_id< T >::c_str(), character_gains_effect, debugmsg, deferred, effect_ridden, effect_riding, effects, efftype_id, Character::forced_dismount(), time_duration::from_turns(), g, effect::get_bp(), effect::get_dur_add_perc(), effect::get_duration(), effect::get_id(), effect::get_int_add_val(), effect::get_int_dur_factor(), effect::get_intensity(), effect::get_max_duration(), effect::get_max_intensity(), has_effect(), is_immune_effect(), is_player(), string_id< T >::is_valid(), m_debug, body_part_type::main_part, effect::mod_duration(), effect::mod_intensity(), monster::mounted_player, string_id< T >::obj(), on_effect_int_change(), process_one_effect(), effect::set_duration(), effect::set_intensity(), calendar::turn, and type.
add_env_effect() [1/2]
bool Creature::add_env_effect (const efftype_id & eff_id, body_part vector, int strength, const time_duration & dur, body_part bp, bool REMOVED, int intensity = 1, bool force = false) delete
add_env_effect() [2/2]
bool Creature::add_env_effect (const efftype_id & eff_id, body_part vector, int strength, const time_duration & dur, body_part bp = num_bp, int intensity = 1, bool force = false)
Gives chance to save via environmental resist, returns false if resistance was successful.
Definition at line 1118 of file creature.cpp.
{
    if( !force && is_immune_effect( eff_id ) ) {
        return false;
    }
    if( dice( strength, 3 ) > dice( get_env_resist( convert_bp( vector ).id() ), 3 ) ) {
        // Only add the effect if we fail the resist roll
        // Don't check immunity (force == true), because we did check above
        add_effect( eff_id, dur, bp, intensity, true );
        return true;
    } else {
        return false;
    }
}
References add_effect(), convert_bp(), dice(), get_env_resist(), and is_immune_effect().
Referenced by mattack::acid_barf(), mattack::boomer(), mattack::boomer_glow(), map::burn_body_part(), map::creature_in_field(), fungal_effects::fungalize(), trapfunc::goo(), and map::player_in_field().
add_msg_if_npc() [1/10]
template<typename ... Args> void Creature::add_msg_if_npc (const char *const msg, Args &&... args) const inline
Definition at line 645 of file creature.h.
{
            return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_npc(), and string_format().
add_msg_if_npc() [2/10]
virtual void Creature::add_msg_if_npc (const game_message_params & , const std::string &) const inline virtual
Reimplemented in monster, monster, and npc.
Definition at line 640 of file creature.h.
                                                                {}
add_msg_if_npc() [3/10]
void Creature::add_msg_if_npc (const game_message_params & params, const translation & msg) const
Definition at line 1932 of file creature.cpp.
{
    return add_msg_if_npc( params, msg.translated() );
}
References add_msg_if_npc(), and translation::translated().
add_msg_if_npc() [4/10]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const char *const msg, Args &&... args) const inline
Definition at line 657 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_npc() [5/10]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const std::string & msg, Args &&... args) const inline
Definition at line 665 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_npc() [6/10]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const translation & msg, Args &&... args) const inline
Definition at line 673 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_npc() [7/10]
virtual void Creature::add_msg_if_npc (const std::string &) const inline virtual
Reimplemented in monster, monster, and npc.
Definition at line 639 of file creature.h.
{}
Referenced by add_msg_if_npc(), Character::deactivate_bionic(), Character::melee_special_effects(), Character::perform_technique(), explosion_handler::explosion_funcs::regular(), show_armor_layers_ui(), and Character::wear_item().
add_msg_if_npc() [8/10]
template<typename ... Args> void Creature::add_msg_if_npc (const std::string & msg, Args &&... args) const inline
Definition at line 649 of file creature.h.
{
            return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_npc(), and string_format().
add_msg_if_npc() [9/10]
void Creature::add_msg_if_npc (const translation & msg) const
Definition at line 1927 of file creature.cpp.
{
    return add_msg_if_npc( msg.translated() );
}
References add_msg_if_npc(), and translation::translated().
add_msg_if_npc() [10/10]
template<typename ... Args> void Creature::add_msg_if_npc (const translation & msg, Args &&... args) const inline
Definition at line 653 of file creature.h.
{
            return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_npc(), and string_format().
add_msg_if_player() [1/10]
template<typename ... Args> void Creature::add_msg_if_player (const char *const msg, Args &&... args) const inline
Definition at line 603 of file creature.h.
{
            return add_msg_if_player( string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_player(), and string_format().
add_msg_if_player() [2/10]
virtual void Creature::add_msg_if_player (const game_message_params & , const std::string &) const inline virtual
Reimplemented in npc, npc, and player.
Definition at line 598 of file creature.h.
                                                                   {}
add_msg_if_player() [3/10]
void Creature::add_msg_if_player (const game_message_params & params, const translation & msg) const
Definition at line 1922 of file creature.cpp.
{
    return add_msg_if_player( params, msg.translated() );
}
References add_msg_if_player(), and translation::translated().
add_msg_if_player() [4/10]
template<typename ... Args> void Creature::add_msg_if_player (const game_message_params & params, const char *const msg, Args &&... args) const inline
Definition at line 615 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_player( params, string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_player(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player() [5/10]
template<typename ... Args> void Creature::add_msg_if_player (const game_message_params & params, const std::string & msg, Args &&... args) const inline
Definition at line 623 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_player( params, string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_player(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player() [6/10]
template<typename ... Args> void Creature::add_msg_if_player (const game_message_params & params, const translation & msg, Args &&... args) const inline
Definition at line 631 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_player( params, string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_player(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player() [7/10]
virtual void Creature::add_msg_if_player (const std::string &) const inline virtual
Reimplemented in npc, npc, and player.
Definition at line 597 of file creature.h.
{}
Referenced by Character::absorb_hit(), mdefense::acidsplash(), Character::activate_bionic(), Character::activate_mutation(), Character::add_bionic(), ter_furn_data< T >::add_msg(), add_msg_if_player(), character_funcs::add_pain_msg(), addict_effect(), Character::apply_damage(), Character::armor_absorb(), Character::assign_activity(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::burn_move_stamina(), Character::calc_needs_rates(), vehicle::can_close(), can_use_mutation_warn(), autodrive_activity_actor::canceled(), spell::cast_all_effects(), Character::change_side(), Character::check_mount_will_move(), Character::check_needs_extremes(), doors::close_door(), Character::consume(), Character::consume_effects(), Character::consume_item(), Character::consume_med(), crafting_speed_multiplier(), item::deactivate(), Character::deactivate_bionic(), Character::deal_damage(), mattack::dermatik(), vehicle::do_autodrive(), Character::do_skill_rust(), stash_activity_actor::do_turn(), pickup_activity_actor::do_turn(), Character::drench(), Character::drop_invalid_inventory(), Character::eat(), Character::fall_asleep(), autodrive_activity_actor::finish(), dig_activity_actor::finish(), dig_channel_activity_actor::finish(), hacking_activity_actor::finish(), wash_activity_actor::finish(), ranged::fire_gun(), mattack::flesh_golem(), mattack::fungus_bristle(), hack_attempt(), Character::handle_melee_wear(), Character::hardcoded_effects(), Character::has_enough_charges(), Character::impact(), Character::introduce_into_anesthesia(), Character::irradiate(), known_magic::learn_spell(), marloss_add(), character_martial_arts::martialart_use_message(), Character::melee_attack(), monster::melee_attack(), Character::melee_special_effects(), Character::mend(), Character::modify_morale(), Character::modify_stimulation(), Character::mount_creature(), Character::move_effects(), Character::mutate(), Character::mutate_towards(), Character::on_damage_of_type(), mattack::para_sting(), Character::perform_technique(), vehicle::pldrive(), Character::pour_into(), ranged::print_dmg_msg(), Character::print_health(), Character::process_bionic(), Character::process_effects_internal(), Character::process_one_effect(), relic_funcs::process_recharge_entry(), Character::process_turn(), character_funcs::rate_sleep_spot(), Character::reach_attack(), Character::reduce_healing_effect(), Character::regen(), Character::restore_scent(), character_funcs::roll_can_sleep(), mattack::science(), character_funcs::search_surroundings(), character_funcs::select_ammo(), Character::shout(), detail::show_mutations_ui_internal(), character_funcs::siphon(), spell_effect::spawn_summoned_vehicle(), sting_shoot(), Character::suffer_from_asthma(), Character::suffer_from_bad_bionics(), Character::suffer_from_chemimbalance(), Character::suffer_from_other_mutations(), Character::suffer_from_radiation(), Character::suffer_from_schizophrenia(), Character::suffer_from_stimulants(), Character::suffer_from_sunburn(), Character::suffer_mutation_power(), Character::suffer_while_underwater(), Character::suffer_without_sleep(), mattack::tankgun(), test_crossing_threshold(), mattack::thrown_by_judo(), try_reject_mutagen(), disassemble_activity_actor::try_start_single(), gun_actor::try_target(), character_funcs::try_wield_contents(), Character::update_needs(), Character::wear_item(), and Character::will_eat().
add_msg_if_player() [8/10]
template<typename ... Args> void Creature::add_msg_if_player (const std::string & msg, Args &&... args) const inline
Definition at line 607 of file creature.h.
{
            return add_msg_if_player( string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_player(), and string_format().
add_msg_if_player() [9/10]
void Creature::add_msg_if_player (const translation & msg) const
Definition at line 1917 of file creature.cpp.
{
    return add_msg_if_player( msg.translated() );
}
References add_msg_if_player(), and translation::translated().
add_msg_if_player() [10/10]
template<typename ... Args> void Creature::add_msg_if_player (const translation & msg, Args &&... args) const inline
Definition at line 611 of file creature.h.
{
            return add_msg_if_player( string_format( msg, std::forward<Args>( args )... ) );
        }
References add_msg_if_player(), and string_format().
add_msg_player_or_npc() [1/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const inline
Definition at line 692 of file creature.h.
{
            return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_npc(), and string_format().
add_msg_player_or_npc() [2/10]
virtual void Creature::add_msg_player_or_npc (const game_message_params & , const std::string & , const std::string &) const inline virtual
Reimplemented in monster, monster, npc, npc, and player.
Definition at line 683 of file creature.h.
                                                                       {}
add_msg_player_or_npc() [3/10]
void Creature::add_msg_player_or_npc (const game_message_params & params, const translation & pc, const translation & npc) const
Definition at line 1942 of file creature.cpp.
{
    return add_msg_player_or_npc( params, pc.translated(), npc.translated() );
}
References add_msg_player_or_npc(), and translation::translated().
add_msg_player_or_npc() [4/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const char *const player_msg, const char *const npc_msg, Args &&... args) const inline
Definition at line 710 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_npc() [5/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const std::string & player_msg, const std::string & npc_msg, Args &&... args) const inline
Definition at line 719 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_npc() [6/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const translation & player_msg, const translation & npc_msg, Args &&... args) const inline
Definition at line 728 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_npc() [7/10]
virtual void Creature::add_msg_player_or_npc (const std::string & , const std::string &) const inline virtual
Reimplemented in monster, monster, npc, npc, and player.
Definition at line 681 of file creature.h.
                                                                       {}
Referenced by mattack::acid_barf(), add_msg_player_or_npc(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::block_hit(), mattack::boomer(), mattack::boomer_glow(), Character::burn_fuel(), melee_actor::call(), Character::can_use(), enchantment::cast_enchantment_spell(), Character::change_side(), Character::check_needs_extremes(), map::creature_in_field(), Character::deal_damage(), destroyed_armor_msg(), trapfunc::dissector(), Character::do_damage_for_bionic_failure(), character_funcs::do_pause(), Character::drop(), map::drop_furniture(), Character::eat(), mattack::evolve_kill_strike(), Character::feed_furnace_with(), Character::feed_reactor_with(), mattack::flesh_golem(), Character::forced_dismount(), Character::fuel_bionic_with(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::grab_drag(), mattack::growplants(), ranged::handle_gun_damage(), Character::handle_melee_wear(), Character::hardcoded_effects(), Character::impact(), mattack::impale(), Character::introduce_into_anesthesia(), Character::knock_back_to(), mattack::longswipe(), mattack::lunge(), Character::melee_attack(), Character::melee_special_effects(), Character::modify_morale(), Character::move_effects(), Character::mutate_towards(), Character::mutation_effect(), melee_actor::on_damage(), Character::perform_technique(), Character::perform_uninstall(), player_hit_message(), Character::process_bionic(), mattack::pull_metal_weapon(), mattack::ranged_pull(), Character::remove_mutation(), mattack::science(), mattack::smash(), mattack::stretch_attack(), mattack::stretch_bite(), Character::suffer_from_asthma(), Character::suffer_from_bad_bionics(), Character::suffer_from_schizophrenia(), Character::suffer_water_damage(), Character::suffer_while_awake(), Character::suffer_without_sleep(), Character::takeoff(), mattack::taze(), mattack::tentacle(), try_reject_mutagen(), mattack::vine(), Character::vomit(), Character::wear_item(), and Character::wear_possessed().
add_msg_player_or_npc() [8/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const std::string & player_msg, const std::string & npc_msg, Args &&... args) const inline
Definition at line 698 of file creature.h.
{
            return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_npc(), and string_format().
add_msg_player_or_npc() [9/10]
void Creature::add_msg_player_or_npc (const translation & pc, const translation & npc) const
Definition at line 1937 of file creature.cpp.
{
    return add_msg_player_or_npc( pc.translated(), npc.translated() );
}
References add_msg_player_or_npc(), and translation::translated().
add_msg_player_or_npc() [10/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const translation & player_msg, const translation & npc_msg, Args &&... args) const inline
Definition at line 704 of file creature.h.
{
            return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_npc(), and string_format().
add_msg_player_or_say() [1/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const inline
Definition at line 748 of file creature.h.
{
            return add_msg_player_or_say( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_speech, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_say(), and string_format().
add_msg_player_or_say() [2/10]
virtual void Creature::add_msg_player_or_say (const game_message_params & , const std::string & , const std::string &) const inline virtual
Reimplemented in npc, npc, and player.
Definition at line 739 of file creature.h.
                                                                       {}
add_msg_player_or_say() [3/10]
void Creature::add_msg_player_or_say (const game_message_params & params, const translation & pc, const translation & npc) const
Definition at line 1953 of file creature.cpp.
{
    return add_msg_player_or_say( params, pc.translated(), npc.translated() );
}
References add_msg_player_or_say(), and translation::translated().
add_msg_player_or_say() [4/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const game_message_params & params, const char *const player_msg, const char *const npc_speech, Args &&... args) const inline
Definition at line 766 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_say( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_speech, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_say(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_say() [5/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const game_message_params & params, const std::string & player_msg, const std::string & npc_speech, Args &&... args) const inline
Definition at line 775 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_say( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_speech, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_say(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_say() [6/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const game_message_params & params, const translation & player_msg, const translation & npc_speech, Args &&... args) const inline
Definition at line 784 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_say( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_speech, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_say(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_say() [7/10]
virtual void Creature::add_msg_player_or_say (const std::string & , const std::string &) const inline virtual
Reimplemented in npc, npc, and player.
Definition at line 737 of file creature.h.
                                                                       {}
Referenced by add_msg_player_or_say().
add_msg_player_or_say() [8/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const std::string & player_msg, const std::string & npc_speech, Args &&... args) const inline
Definition at line 754 of file creature.h.
{
            return add_msg_player_or_say( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_speech, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_say(), and string_format().
add_msg_player_or_say() [9/10]
void Creature::add_msg_player_or_say (const translation & pc, const translation & npc) const
Definition at line 1948 of file creature.cpp.
{
    return add_msg_player_or_say( pc.translated(), npc.translated() );
}
References add_msg_player_or_say(), and translation::translated().
add_msg_player_or_say() [10/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const translation & player_msg, const translation & npc_speech, Args &&... args) const inline
Definition at line 760 of file creature.h.
{
            return add_msg_player_or_say( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_speech, std::forward<Args>( args )... ) );
        }
References add_msg_player_or_say(), and string_format().
apply_damage()
virtual void Creature::apply_damage (Creature * source, bodypart_id bp, int amount, bool bypass_med = false) pure virtual
Implemented in monster, and Character.
Referenced by deal_damage(), explosion_handler::do_blast(), vehicle::part_collision(), and teleport::teleport().
as_avatar() [1/2]
virtual avatar * Creature::as_avatar () inline virtual
Reimplemented in avatar.
Definition at line 128 of file creature.h.
{
            return nullptr;
        }
Referenced by Character::activate_bionic(), iexamine::autoclave_empty(), iuse::cable_attach(), iuse::camera(), doors::close_door(), Character::consume_item(), iuse::disassemble(), throw_activity_actor::do_turn(), iuse::einktabletpc(), disassemble_activity_actor::finish(), read_inventory_preset::get_denial(), gunmod_inventory_preset::get_odds(), iuse::gunmod_attach(), handle_player_display_action(), iuse::lumber(), spell_effect::map_area(), iuse::mind_splicer(), iuse::pack_cbm(), iuse::radio_mod(), iuse::radiocar(), read_inventory_preset::read_inventory_preset(), activity_handlers::spellcasting_finish(), iuse::toolmod_attach(), spell_effect::translocate(), holster_actor::use(), sew_advanced_actor::use(), and detach_gunmods_actor::use().
as_avatar() [2/2]
virtual const avatar * Creature::as_avatar () const inline virtual
Reimplemented in avatar.
Definition at line 131 of file creature.h.
{
            return nullptr;
        }
as_character() [1/2]
virtual Character * Creature::as_character () inline virtual
Reimplemented in Character.
Definition at line 116 of file creature.h.
{
            return nullptr;
        }
Referenced by add_effect(), Character::melee_attack(), remove_effect(), sees(), and spell_effect::spawn_summoned_vehicle().
as_character() [2/2]
virtual const Character * Creature::as_character () const inline virtual
Reimplemented in Character.
Definition at line 119 of file creature.h.
{
            return nullptr;
        }
as_monster() [1/2]
virtual monster * Creature::as_monster () inline virtual
Reimplemented in monster.
Definition at line 104 of file creature.h.
{
            return nullptr;
        }
as_monster() [2/2]
virtual const monster * Creature::as_monster () const inline virtual
Reimplemented in monster.
Definition at line 107 of file creature.h.
{
            return nullptr;
        }
as_npc() [1/2]
virtual npc * Creature::as_npc () inline virtual
Reimplemented in npc.
Definition at line 110 of file creature.h.
{
            return nullptr;
        }
Referenced by complete_construction(), read_inventory_preset::read_inventory_preset(), and Character::update_needs().
as_npc() [2/2]
virtual const npc * Creature::as_npc () const inline virtual
Reimplemented in npc.
Definition at line 113 of file creature.h.
{
            return nullptr;
        }
as_player() [1/2]
virtual player * Creature::as_player () inline virtual
Reimplemented in player.
Definition at line 122 of file creature.h.
{
            return nullptr;
        }
Referenced by Character::apply_damage(), complete_construction(), crafting::complete_disassemble(), Character::consume(), Character::consume_med(), map::creature_in_field(), Character::dispose_item(), character_funcs::do_pause(), veh_interact::do_remove(), veh_interact::do_repair(), Character::drop(), drop_or_handle(), Character::eat(), wash_activity_actor::finish(), ranged::fire_gun(), Character::hardcoded_effects(), Character::invoke_item(), character_funcs::list_ammo(), melee_train(), npc_ai::melee_value(), game_menus::inv::multiwash(), obtain_activity_items(), Character::on_dodge(), item::on_takeoff(), item::on_wear(), spell_effect::pain_split(), Character::perform_special_attacks(), vehicle::pldrive(), Character::process_items(), Character::process_turn(), show_armor_layers_ui(), teleport::teleport(), ranged::throw_item(), character_funcs::try_wield_contents(), Character::update_body(), veh_interact::update_part_requirements(), and Character::wear_possessed().
as_player() [2/2]
virtual const player * Creature::as_player () const inline virtual
Reimplemented in player.
Definition at line 125 of file creature.h.
{
            return nullptr;
        }
attitude_raw_string()
std::string Creature::attitude_raw_string (Attitude att) static
Simplified attitude string for unlocalized needs.
Definition at line 1852 of file creature.cpp.
{
    switch( att ) {
        case Creature::A_HOSTILE:
            return "hostile";
        case Creature::A_NEUTRAL:
            return "neutral";
        case Creature::A_FRIENDLY:
            return "friendly";
        default:
            return "other";
    }
}
References A_FRIENDLY, A_HOSTILE, and A_NEUTRAL.
attitude_to()
virtual Attitude Creature::attitude_to (const Creature & other) const pure virtual
Attitude (of this creature) towards another creature.
This might not be symmetric.
Implemented in Character, monster, and npc.
Referenced by Character::get_hostile_creatures(), target_ui::list_friendlies_in_lof(), melee_actor::on_damage(), monster::plan(), and mattack::taze().
auto_find_hostile_target()
Creature * Creature::auto_find_hostile_target (int range, int & boo_hoo, int area = 0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
This is for creatures that are friendly towards the player and therefor choose a target that is hostile to the player.
Parameters
range The maximal range to look for monsters, anything outside of that range is ignored.
boo_hoo The number of targets that have been skipped because the player is in the way.
area The area of effect of the projectile aimed.
Definition at line 336 of file creature.cpp.
{
    Creature *target = nullptr;
    player &u = g->u; // Could easily protect something that isn't the player
    constexpr int hostile_adj = 2; // Priority bonus for hostile targets
    const int iff_dist = ( range + area ) * 3 / 2 + 6; // iff check triggers at this distance
    // iff safety margin (degrees). less accuracy, more paranoia
    units::angle iff_hangle = units::from_degrees( 15 + area );
    float best_target_rating = -1.0f; // bigger is better
    units::angle u_angle = {};         // player angle relative to turret
    boo_hoo = 0;         // how many targets were passed due to IFF. Tragically.
    bool self_area_iff = false; // Need to check if the target is near the vehicle we're a part of
    bool area_iff = false;      // Need to check distance from target to player
    bool angle_iff = true;      // Need to check if player is in a cone between us and target
    int pldist = rl_dist( pos(), g->u.pos() );
    map &here = get_map();
    vehicle *in_veh = is_fake() ? veh_pointer_or_null( here.veh_at( pos() ) ) : nullptr;
    if( pldist < iff_dist && sees( g->u ) ) {
        area_iff = area > 0;
        angle_iff = true;
        // Player inside vehicle won't be hit by shots from the roof,
        // so we can fire "through" them just fine.
        const optional_vpart_position vp = here.veh_at( u.pos() );
        if( in_veh && veh_pointer_or_null( vp ) == in_veh && vp->is_inside() ) {
            angle_iff = false; // No angle IFF, but possibly area IFF
        } else if( pldist < 3 ) {
            // granularity increases with proximity
            iff_hangle = ( pldist == 2 ? 30_degrees : 60_degrees );
        }
        u_angle = coord_to_angle( pos(), u.pos() );
    }
    if( area > 0 && in_veh != nullptr ) {
        self_area_iff = true;
    }
    std::vector<Creature *> targets = g->get_creatures_if( [&]( const Creature & critter ) {
        if( critter.is_monster() ) {
            // friendly to the player, not a target for us
            return static_cast<const monster *>( &critter )->friendly == 0;
        }
        if( critter.is_npc() ) {
            // friendly to the player, not a target for us
            return static_cast<const npc *>( &critter )->get_attitude() == NPCATT_KILL;
        }
        // TODO: what about g->u?
        return false;
    } );
    for( auto &m : targets ) {
        if( !sees( *m ) ) {
            // can't see nor sense it
            if( is_fake() && in_veh ) {
                // If turret in the vehicle then
                // Hack: trying yo avoid turret LOS blocking by frames bug by trying to see target from vehicle boundary
                // Or turret wallhack for turret's car
                // TODO: to visibility checking another way, probably using 3D FOV
                std::vector<tripoint> path_to_target = line_to( pos(), m->pos() );
                path_to_target.insert( path_to_target.begin(), pos() );
                // Getting point on vehicle boundaries and on line between target and turret
                bool continueFlag = true;
                do {
                    const optional_vpart_position vp = here.veh_at( path_to_target.back() );
                    vehicle *const veh = vp ? &vp->vehicle() : nullptr;
                    if( in_veh == veh ) {
                        continueFlag = false;
                    } else {
                        path_to_target.pop_back();
                    }
                } while( continueFlag );
                tripoint oldPos = pos();
                setpos( path_to_target.back() ); //Temporary moving targeting npc on vehicle boundary postion
                bool seesFromVehBound = sees( *m ); // And look from there
                setpos( oldPos );
                if( !seesFromVehBound ) {
                    continue;
                }
            } else {
                continue;
            }
        }
        int dist = rl_dist( pos(), m->pos() ) + 1; // rl_dist can be 0
        if( dist > range + 1 || dist < area ) {
            // Too near or too far
            continue;
        }
        // Prioritize big, armed and hostile stuff
        float mon_rating = m->power_rating();
        float target_rating = mon_rating / dist;
        if( mon_rating + hostile_adj <= 0 ) {
            // We wouldn't attack it even if it was hostile
            continue;
        }
        if( in_veh != nullptr && veh_pointer_or_null( here.veh_at( m->pos() ) ) == in_veh ) {
            // No shooting stuff on vehicle we're a part of
            continue;
        }
        if( area_iff && rl_dist( u.pos(), m->pos() ) <= area ) {
            // Player in AoE
            boo_hoo++;
            continue;
        }
        // Hostility check can be expensive, but we need to inform the player of boo_hoo
        // only when the target is actually "hostile enough"
        bool maybe_boo = false;
        if( angle_iff ) {
            units::angle tangle = coord_to_angle( pos(), m->pos() );
            units::angle diff = units::fabs( u_angle - tangle );
            // Player is in the angle and not too far behind the target
            if( ( diff + iff_hangle > 360_degrees || diff < iff_hangle ) &&
                ( dist * 3 / 2 + 6 > pldist ) ) {
                maybe_boo = true;
            }
        }
        if( !maybe_boo && ( ( mon_rating + hostile_adj ) / dist <= best_target_rating ) ) {
            // "Would we skip the target even if it was hostile?"
            // Helps avoid (possibly expensive) attitude calculation
            continue;
        }
        if( m->attitude_to( u ) == A_HOSTILE ) {
            target_rating = ( mon_rating + hostile_adj ) / dist;
            if( maybe_boo ) {
                boo_hoo++;
                continue;
            }
        }
        if( target_rating <= best_target_rating || target_rating <= 0 ) {
            continue; // Handle this late so that boo_hoo++ can happen
        }
        // Expensive check for proximity to vehicle
        if( self_area_iff && overlaps_vehicle( in_veh->get_points(), m->pos(), area ) ) {
            continue;
        }
        target = m;
        best_target_rating = target_rating;
    }
    return target;
}
References A_HOSTILE, coord_to_angle(), units::fabs(), units::from_degrees(), g, get_map(), vehicle::get_points(), is_fake(), is_monster(), is_npc(), line_to(), overlaps_vehicle(), pos(), Character::pos(), rl_dist(), sees(), setpos(), map::veh_at(), and veh_pointer_or_null().
Referenced by vehicle::automatic_fire_turret(), gun_actor::call(), mattack::chickenbot(), mattack::flamethrower(), and mattack::multi_robot().
avoid_trap()
virtual bool Creature::avoid_trap (const tripoint & pos, const trap & tr) const pure virtual
Called when a creature triggers a trap, returns true if they don't set it off.
Parameters
tr is the trap that was triggered.
pos is the location of the trap (not necessarily of the creature) in the main map.
Implemented in Character, and monster.
basic_symbol_color()
virtual nc_color Creature::basic_symbol_color () const pure virtual
Implemented in Character, monster, and npc.
Referenced by draw().
bleed()
void Creature::bleed () const virtual
Adds an appropriate blood splatter.
Definition at line 127 of file creature.cpp.
{
    const field_type_id &blood_type = bloodType();
    if( blood_type ) {
        get_map().add_splatter( blood_type, pos() );
    }
}
References map::add_splatter(), bloodType(), get_map(), and pos().
Referenced by Character::body_window(), eff_fun_bleed(), Character::limb_color(), mdeath::normal(), vehicle::part_collision(), and pick_part_to_heal().
block_hit()
virtual bool Creature::block_hit (Creature * source, bodypart_id & bp_hit, damage_instance & dam) pure virtual
Implemented in monster, and Character.
Referenced by deal_melee_hit().
bloodType()
virtual field_type_id Creature::bloodType () const pure virtual
Implemented in Character, and monster.
Referenced by bleed(), and projectile_attack().
check_dead_state()
void Creature::check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
You can either call this function after hitting this creature, or let the game call it during game::cleanup_dead. As die has many side effects (messages, on-death-triggers, ...), you should be careful when calling this and expect that at least a "The monster dies!" message might have been printed. If you want to print any message relating to the attack (e.g. how much damage has been dealt, how the attack was performed, what has been blocked...), do it before calling this function.
Definition at line 1845 of file creature.cpp.
{
    if( is_dead_state() ) {
        die( nullptr );
    }
}
References die(), and is_dead_state().
Referenced by mattack::bio_op_impale(), mattack::bio_op_takedown(), map::crush(), mattack::dermatik(), trapfunc::dissector(), explosion_handler::do_blast(), explosion_handler::emp_blast(), game::fling_creature(), game::forced_door_closing(), trapfunc::goo(), mattack::impale(), monster::knock_back_to(), game::knockback(), mattack::longswipe(), mattack::lunge(), Character::melee_attack(), monster::melee_attack(), map::monster_in_field(), Character::on_hit(), monster::on_hit(), map::player_in_field(), smash(), mattack::stretch_attack(), mattack::taze(), teleport::teleport(), mattack::tentacle(), mattack::thrown_by_judo(), mattack::vine(), and mdefense::zapback().
clear_effects()
void Creature::clear_effects ()
Remove all effects.
Definition at line 1134 of file creature.cpp.
{
    for( auto &elem : *effects ) {
        for( auto &_effect_it : elem.second ) {
            remove_effect( elem.first, _effect_it.first );
        }
    }
}
References effects, and remove_effect().
Referenced by iuse::granade_act().
deal_damage()
dealt_damage_instance Creature::deal_damage (Creature * source, bodypart_id bp, const damage_instance & dam) virtual
Deals the damage via an attack.
Allows armor mitigation etc.
Most sources of external damage should use deal_damage Mutates the damage_instance& object passed in to reflect the post-mitigation object. Does nothing if this creature is already dead. Does not call check_dead_state.
Parameters
source The attacking creature, can be null.
bp The attacked body part
dam The damage dealt
Reimplemented in Character.
Definition at line 880 of file creature.cpp.
{
    if( is_dead_state() ) {
        return dealt_damage_instance();
    }
    int total_damage = 0;
    int total_pain = 0;
    damage_instance d = dam; // copy, since we will mutate in absorb_hit
    dealt_damage_instance dealt_dams;
    absorb_hit( bp, d );
    // Add up all the damage units dealt
    for( const auto &it : d.damage_units ) {
        int cur_damage = 0;
        deal_damage_handle_type( it, bp, cur_damage, total_pain );
        if( cur_damage > 0 ) {
            dealt_dams.dealt_dams[ it.type ] += cur_damage;
            total_damage += cur_damage;
        }
    }
    mod_pain( total_pain );
    apply_damage( source, bp, total_damage );
    return dealt_dams;
}
References absorb_hit(), apply_damage(), damage_instance::damage_units, deal_damage_handle_type(), dealt_damage_instance::dealt_dams, is_dead_state(), and mod_pain().
Referenced by mattack::acid_barf(), mdefense::acidsplash(), mattack::bio_op_impale(), mattack::bio_op_takedown(), trapfunc::board(), melee_actor::call(), trapfunc::crossbow(), Character::deal_damage(), deal_melee_hit(), trapfunc::drain(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), trapfunc::glow(), mattack::growplants(), ranged::hit_with_aoe(), mattack::impale(), trapfunc::lava(), mattack::longswipe(), mattack::lunge(), map::monster_in_field(), Character::on_hit(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), trapfunc::shotgun(), trapfunc::snare_heavy(), trapfunc::snare_light(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::taze(), iuse::tazer(), mattack::tentacle(), trapfunc::tripwire(), mattack::vine(), and mdefense::zapback().
deal_damage_handle_type()
void Creature::deal_damage_handle_type (const damage_unit & du, bodypart_id bp, int & damage, int & pain) virtual
Reimplemented in monster.
Definition at line 908 of file creature.cpp.
{
    // Handles ACIDPROOF, electric immunity etc.
    if( is_immune_damage( du.type ) ) {
        return;
    }
    // Apply damage multiplier from skill, critical hits or grazes after all other modifications.
    const int adjusted_damage = du.amount * du.damage_multiplier;
    if( adjusted_damage <= 0 ) {
        return;
    }
    float div = 4.0f;
    switch( du.type ) {
        case DT_BASH:
            // Bashing damage is less painful
            div = 5.0f;
            break;
        case DT_HEAT:
            // heat damage sets us on fire sometimes
            if( rng( 0, 100 ) < adjusted_damage ) {
                add_effect( effect_onfire, rng( 1_turns, 3_turns ), bp->token );
            }
            break;
        case DT_ELECTRIC:
            // Electrical damage adds a major speed/dex debuff
            add_effect( effect_zapped, 1_turns * std::max( adjusted_damage, 2 ) );
            break;
        case DT_ACID:
            // Acid damage and acid burns are more painful
            div = 3.0f;
            break;
        default:
            break;
    }
    on_damage_of_type( adjusted_damage, du.type, bp );
    damage += adjusted_damage;
    pain += roll_remainder( adjusted_damage / div );
}
References add_effect(), damage_unit::amount, damage_unit::damage_multiplier, DT_ACID, DT_BASH, DT_ELECTRIC, DT_HEAT, effect_onfire, effect_zapped, is_immune_damage(), on_damage_of_type(), pain, rng(), roll_remainder(), and damage_unit::type.
Referenced by deal_damage(), and monster::deal_damage_handle_type().
deal_melee_attack()
int Creature::deal_melee_attack (Creature * source, int hitroll) virtual
Definition at line 503 of file creature.cpp.
{
    int hit_spread = hitroll - dodge_roll() - size_melee_penalty();
    if( has_flag( MF_IMMOBILE ) ) {
        // Under normal circumstances, even a clumsy person would
        // not miss a turret.  It should, however, be possible to
        // miss a smaller target, especially when wielding a
        // clumsy weapon or when severely encumbered.
        hit_spread += 40;
    }
    // If attacker missed call targets on_dodge event
    if( hit_spread <= 0 && source != nullptr && !source->is_hallucination() ) {
        on_dodge( source, source->get_melee() );
    }
    return hit_spread;
}
References dodge_roll(), get_melee(), has_flag(), is_hallucination(), MF_IMMOBILE, on_dodge(), and size_melee_penalty().
Referenced by melee_actor::call(), Character::melee_attack(), monster::melee_attack(), Character::perform_special_attacks(), and avatar_funcs::try_disarm_npc().
deal_melee_hit()
void Creature::deal_melee_hit (Creature * source, int hit_spread, bool critical_hit, const damage_instance & dam, dealt_damage_instance & dealt_dam) virtual
Definition at line 522 of file creature.cpp.
{
    if( source == nullptr || source->is_hallucination() ) {
        dealt_dam.bp_hit = anatomy_id( "human_anatomy" )->random_body_part()->token;
        return;
    }
    // If carrying a rider, there is a chance the hits may hit rider instead.
    // melee attack will start off as targeted at mount
    if( has_effect( effect_ridden ) ) {
        monster *mons = dynamic_cast<monster *>( this );
        if( mons && mons->mounted_player ) {
            if( !mons->has_flag( MF_MECH_DEFENSIVE ) &&
                one_in( std::max( 2, mons->get_size() - mons->mounted_player->get_size() ) ) ) {
                mons->mounted_player->deal_melee_hit( source, hit_spread, critical_hit, dam, dealt_dam );
                return;
            }
        }
    }
    damage_instance d = dam; // copy, since we will mutate in block_hit
    bodypart_id bp_hit = convert_bp( select_body_part( source, hit_spread ) ).id();
    const body_part bp_token = bp_hit->token;
    block_hit( source, bp_hit, d );
    on_hit( source, bp_hit ); // trigger on-gethit events
    dealt_dam = deal_damage( source, bp_hit, d );
    dealt_dam.bp_hit = bp_token;
}
References block_hit(), dealt_damage_instance::bp_hit, convert_bp(), deal_damage(), deal_melee_hit(), effect_ridden, Character::get_size(), monster::get_size(), has_effect(), monster::has_flag(), string_id< T >::id(), is_hallucination(), MF_MECH_DEFENSIVE, monster::mounted_player, on_hit(), one_in(), anatomy::random_body_part(), and select_body_part().
Referenced by deal_melee_hit(), Character::melee_attack(), monster::melee_attack(), and Character::perform_special_attacks().
deal_projectile_attack()
void Creature::deal_projectile_attack (Creature * source, dealt_projectile_attack & attack) virtual
Attempts to harm a creature with a projectile.
Parameters
source Pointer to the creature who shot the projectile.
attack A structure describing the attack and its results.
print_messages enables message printing by default.
Reimplemented in monster.
Definition at line 658 of file creature.cpp.
{
    const bool magic = attack.proj.has_effect( ammo_effect_magic );
    const bool targetted_crit_allowed = !attack.proj.has_effect( ammo_effect_NO_CRIT );
    const double missed_by = attack.missed_by;
    if( missed_by >= 1.0 && !magic ) {
        // Total miss
        return;
    }
    // If carrying a rider, there is a chance the hits may hit rider instead.
    if( has_effect( effect_ridden ) ) {
        monster *mons = dynamic_cast<monster *>( this );
        if( mons && mons->mounted_player ) {
            if( !mons->has_flag( MF_MECH_DEFENSIVE ) &&
                one_in( std::max( 2, mons->get_size() - mons->mounted_player->get_size() ) ) ) {
                mons->mounted_player->deal_projectile_attack( source, attack );
                return;
            }
        }
    }
    const projectile &proj = attack.proj;
    dealt_damage_instance &dealt_dam = attack.dealt_dam;
    const bool u_see_this = g->u.sees( *this );
    const int avoid_roll = dodge_roll();
    // Do dice(10, speed) instead of dice(speed, 10) because speed could potentially be > 10000
    const int diff_roll = dice( 10, proj.speed );
    // Partial dodge, capped at [0.0, 1.0], added to missed_by
    const double dodge_rescaled = avoid_roll / static_cast<double>( diff_roll );
    const double goodhit = missed_by + std::max( 0.0, std::min( 1.0, dodge_rescaled ) );
    if( goodhit >= 1.0 && !magic ) {
        attack.missed_by = 1.0; // Arbitrary value
        // "Avoid" rather than "dodge", because it includes removing self from the line of fire
        //  rather than just Matrix-style bullet dodging
        if( source != nullptr && g->u.sees( *source ) ) {
            add_msg_player_or_npc(
                m_warning,
                _( "You avoid %s projectile!" ),
                _( "<npcname> avoids %s projectile." ),
                source->disp_name( true ) );
        } else {
            add_msg_player_or_npc(
                m_warning,
                _( "You avoid an incoming projectile!" ),
                _( "<npcname> avoids an incoming projectile." ) );
        }
        return;
    }
    // Bounce applies whether it does damage or not.
    if( proj.has_effect( ammo_effect_BOUNCE ) ) {
        add_effect( effect_bounced, 1_turns );
    }
    bodypart_id bp_hit;
    double hit_value = missed_by + rng_float( -0.5, 0.5 );
    if( targetted_crit_allowed || magic ) { //default logic for selecting bodypart
        if( goodhit < accuracy_critical && hit_value <= 0.2 ) {
            bp_hit = bodypart_str_id( "head" );
        } else if( hit_value <= 0.4 || magic ) {
            bp_hit = bodypart_str_id( "torso" );
        } else if( one_in( 4 ) ) {
            if( one_in( 2 ) ) {
                bp_hit = bodypart_str_id( "leg_l" );
            } else {
                bp_hit = bodypart_str_id( "leg_r" );
            }
        } else {
            if( one_in( 2 ) ) {
                bp_hit = bodypart_str_id( "arm_l" );
            } else {
                bp_hit = bodypart_str_id( "arm_r" );
            }
        }
    } else { // no crit logic for selecting bodypart
        if( hit_value <= 0.4 && !one_in( 4 ) ) {
            bp_hit = one_in( 3 ) ? bodypart_str_id( "head" ) : bodypart_str_id( "torso" );
        } else if( one_in( 4 ) ) {
            if( one_in( 2 ) ) {
                bp_hit = bodypart_str_id( "leg_l" );
            } else {
                bp_hit = bodypart_str_id( "leg_r" );
            }
        } else {
            if( one_in( 2 ) ) {
                bp_hit = bodypart_str_id( "arm_l" );
            } else {
                bp_hit = bodypart_str_id( "arm_r" );
            }
        }
    }
    double damage_mult = 1.0;
    ranged::hit_tier ht = ranged::hit_tier::normal;
    if( magic ) {
        damage_mult *= rng_float( 0.9, 1.1 );
    } else if( targetted_crit_allowed && goodhit < accuracy_critical ) {
        ht = ranged::hit_tier::critical;
        damage_mult *= 1.5;
    } else if( goodhit < accuracy_standard ) {
        damage_mult *= rng_float( 0.9, 1.1 );
    } else if( goodhit < accuracy_grazing ) {
        ht = ranged::hit_tier::grazing;
        damage_mult *= 0.5;
    }
    attack.missed_by = goodhit;
    // copy it, since we're mutating
    damage_instance impact = proj.impact;
    if( damage_mult > 0.0f && proj.has_effect( ammo_effect_NO_DAMAGE_SCALING ) ) {
        damage_mult = 1.0f;
    }
    impact.mult_damage( damage_mult );
    if( proj.has_effect( ammo_effect_NOGIB ) ) {
        float dmg_ratio = static_cast<float>( impact.total_damage() ) / get_hp_max( bp_hit );
        if( dmg_ratio > 1.25f ) {
            impact.mult_damage( 1.0f / dmg_ratio );
        }
    }
    dealt_dam = deal_damage( source, bp_hit, impact );
    dealt_dam.bp_hit = bp_hit->token;
    // Apply ammo effects to target.
    if( proj.has_effect( ammo_effect_TANGLE ) ) {
        monster *z = dynamic_cast<monster *>( this );
        player *n = dynamic_cast<player *>( this );
        // if its a tameable animal, its a good way to catch them if they are running away, like them ranchers do!
        // we assume immediate success, then certain monster types immediately break free in monster.cpp move_effects()
        if( z ) {
            const item &drop_item = proj.get_drop();
            if( !drop_item.is_null() ) {
                z->add_effect( effect_tied, 1_turns, num_bp );
                z->tied_item = cata::make_value<item>( drop_item );
            } else {
                add_msg( m_debug, "projectile with TANGLE effect, but no drop item specified" );
            }
        } else if( n && !is_immune_effect( effect_downed ) ) {
            // no tied up effect for people yet, just down them and stun them, its close enough to the desired effect.
            // we can assume a person knows how to untangle their legs eventually and not panic like an animal.
            add_effect( effect_downed, 1_turns );
            // stunned to simulate staggering around and stumbling trying to get the entangled thing off of them.
            add_effect( effect_stunned, rng( 3_turns, 8_turns ) );
        }
    }
    if( proj.has_effect( ammo_effect_INCENDIARY ) ) {
        if( made_of( material_id( "veggy" ) ) || made_of_any( cmat_flammable ) ) {
            add_effect( effect_onfire, rng( 2_turns, 6_turns ), bp_hit->token );
        } else if( made_of_any( cmat_flesh ) && one_in( 4 ) ) {
            add_effect( effect_onfire, rng( 1_turns, 4_turns ), bp_hit->token );
        }
    } else if( proj.has_effect( ammo_effect_IGNITE ) ) {
        if( made_of( material_id( "veggy" ) ) || made_of_any( cmat_flammable ) ) {
            add_effect( effect_onfire, 6_turns, bp_hit->token );
        } else if( made_of_any( cmat_flesh ) ) {
            add_effect( effect_onfire, 10_turns, bp_hit->token );
        }
    }
    if( bp_hit == bodypart_str_id( "head" ) && proj.has_effect( ammo_effect_BLINDS_EYES ) ) {
        // TODO: Change this to require bp_eyes
        add_env_effect( effect_blind, bp_eyes, 5, rng( 3_turns, 10_turns ) );
    }
    if( proj.has_effect( ammo_effect_APPLY_SAP ) ) {
        add_effect( effect_sap, 1_turns * dealt_dam.total_damage() );
    }
    if( proj.has_effect( ammo_effect_PARALYZEPOISON ) && dealt_dam.total_damage() > 0 ) {
        add_msg_if_player( m_bad, _( "You feel poison coursing through your body!" ) );
        add_effect( effect_paralyzepoison, 5_minutes );
    }
    int stun_strength = 0;
    if( proj.has_effect( ammo_effect_BEANBAG ) ) {
        stun_strength = 4;
    }
    if( proj.has_effect( ammo_effect_LARGE_BEANBAG ) ) {
        stun_strength = 16;
    }
    if( stun_strength > 0 ) {
        switch( get_size() ) {
            case MS_TINY:
                stun_strength *= 4;
                break;
            case MS_SMALL:
                stun_strength *= 2;
                break;
            case MS_MEDIUM:
            default:
                break;
            case MS_LARGE:
                stun_strength /= 2;
                break;
            case MS_HUGE:
                stun_strength /= 4;
                break;
        }
        add_effect( effect_stunned, 1_turns * rng( stun_strength / 2, stun_strength ) );
    }
    if( u_see_this ) {
        if( damage_mult == 0 ) {
            if( source != nullptr ) {
                add_msg( source->is_player() ? _( "You miss!" ) : _( "The shot misses!" ) );
            }
        } else {
            ranged::print_dmg_msg( *this, source, dealt_dam, ht );
        }
    }
    check_dead_state();
    attack.hit_critter = this;
    attack.missed_by = goodhit;
}
References ammo_effect_magic, ammo_effect_NO_CRIT, deal_projectile_attack(), dealt_projectile_attack::dealt_dam, dice(), dodge_roll(), effect_ridden, g, Character::get_size(), monster::get_size(), projectile::has_effect(), has_effect(), monster::has_flag(), MF_MECH_DEFENSIVE, dealt_projectile_attack::missed_by, monster::mounted_player, one_in(), dealt_projectile_attack::proj, and projectile::speed.
Referenced by damage_targets(), deal_projectile_attack(), monster::deal_projectile_attack(), and projectile_attack().
describe_infrared()
void Creature::describe_infrared (std::vector< std::string > & buf) const
Describe this creature as seen by the avatar via infrared vision.
Definition at line 1982 of file creature.cpp.
{
    std::string size_str;
    switch( get_size() ) {
        case m_size::MS_TINY:
            size_str = pgettext( "infrared size", "tiny" );
            break;
        case m_size::MS_SMALL:
            size_str = pgettext( "infrared size", "small" );
            break;
        case m_size::MS_MEDIUM:
            size_str = pgettext( "infrared size", "medium" );
            break;
        case m_size::MS_LARGE:
            size_str = pgettext( "infrared size", "large" );
            break;
        case m_size::MS_HUGE:
            size_str = pgettext( "infrared size", "huge" );
            break;
        default:
            debugmsg( "Creature has invalid size class." );
            size_str = "invalid";
            break;
    }
    buf.push_back( _( "You see a figure radiating heat." ) );
    buf.push_back( string_format( _( "It is %s in size." ), size_str ) );
}
References _, debugmsg, get_size(), MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, pgettext(), and string_format().
Referenced by target_ui::panel_target_info().
describe_specials()
void Creature::describe_specials (std::vector< std::string > & buf) const
Describe this creature as detected by the avatar's special senses.
Definition at line 2010 of file creature.cpp.
{
    buf.push_back( _( "You sense a creature here." ) );
}
References _.
Referenced by target_ui::panel_target_info().
die()
virtual void Creature::die (Creature * killer) pure virtual
Empty function.
Should always be overwritten by the appropriate player/NPC/monster version.
Implemented in monster, npc, and Character.
Referenced by check_dead_state(), debug_menu::debug(), knock_back_from(), talk_function::loot_building(), and monster::push_to().
digging()
bool Creature::digging () const virtual
Reimplemented in monster.
Definition at line 180 of file creature.cpp.
{
    return false;
}
Referenced by sees(), and Character::sees_with_specials().
disp_name()
virtual std::string Creature::disp_name (bool possessive = false, bool capitalize_first = false) const pure virtual
Implemented in Character, and monster.
Referenced by mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), game::butcher(), melee_actor::call(), vehicle::can_close(), enchantment::cast_enchantment_spell(), doors::close_door(), damage_targets(), Character::deal_damage(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), Character::hardcoded_effects(), Character::impact(), trapfunc::ledge(), mattack::lunge(), Character::melee_attack(), monster::melee_attack(), Character::melee_special_effects(), npc::move(), Character::mutation_attacks(), Character::on_hit(), Character::on_hurt(), vehicle::part_collision(), player_hit_message(), ranged::print_dmg_msg(), mattack::ranged_pull(), explosion_handler::explosion_funcs::regular(), replace_with_npc_name(), mattack::science(), mattack::shockstorm(), mattack::smash(), iuse::tazer(), teleport::teleport(), and mdefense::zapback().
dodge_roll()
virtual float Creature::dodge_roll () pure virtual
Implemented in Character, and monster.
Referenced by deal_melee_attack(), deal_projectile_attack(), and Character::melee_attack().
draw() [1/2]
void Creature::draw (const catacurses::window & w, const tripoint & origin, bool inverted) const
Definition at line 1812 of file creature.cpp.
{
    if( is_draw_tiles_mode() ) {
        return;
    }
    point draw( -origin.xy() + point( getmaxx( w ) / 2 + posx(), getmaxy( w ) / 2 + posy() ) );
    if( inverted ) {
        mvwputch_inv( w, draw, basic_symbol_color(), symbol() );
    } else if( is_symbol_highlighted() ) {
        mvwputch_hi( w, draw, basic_symbol_color(), symbol() );
    } else {
        mvwputch( w, draw, symbol_color(), symbol() );
    }
}
References basic_symbol_color(), draw(), catacurses::getmaxx(), catacurses::getmaxy(), is_draw_tiles_mode(), is_symbol_highlighted(), mvwputch(), mvwputch_hi(), mvwputch_inv(), posx(), posy(), symbol(), and symbol_color().
draw() [2/2]
void Creature::draw (const catacurses::window & w, point origin, bool inverted) const
Definition at line 1807 of file creature.cpp.
{
    draw( w, tripoint( origin, posz() ), inverted );
}
References draw(), and posz().
Referenced by draw(), draw_critter_internal(), editmap::draw_main_ui_overlay(), and editmap::uber_draw_ter().
extended_description()
virtual std::string Creature::extended_description () const pure virtual
Implemented in Character, monster, and npc.
Referenced by game::extended_description().
fall_damage_mod()
virtual float Creature::fall_damage_mod () const pure virtual
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
Implemented in Character, and monster.
get_all_body_parts()
std::vector< bodypart_id > Creature::get_all_body_parts (bool only_main = false) const
Returns body parts this creature have.
Parameters
only_main If true, only displays parts that can have hit points
Definition at line 1633 of file creature.cpp.
{
    std::vector<bodypart_id> all_bps;
    for( const std::pair<const bodypart_str_id, bodypart> &elem : body ) {
        if( only_main && elem.first->main_part != elem.first ) {
            continue;
        }
        all_bps.push_back( elem.first );
    }
    return  all_bps;
}
References body.
Referenced by npc::adjust_worn(), blood_magic(), Character::bodypart_exposure(), Character::can_wear(), relic_funcs::check_recharge_reqs(), Character::do_damage_for_bionic_failure(), Character::enforce_minimum_healing(), Character::extended_description(), Character::get_all_armor_type(), give_aid_to(), start_location::handle_heli_crash(), Character::healall(), Character::hurtall(), Character::mend(), map::player_in_field(), Character::process_bionic(), show_bionics_ui(), Character::update_bodytemp(), Character::warmth(), npc::wear_if_wanted(), and weather_effect::wet_player().
get_all_effects()
effects_map Creature::get_all_effects () const
Definition at line 2015 of file creature.cpp.
{
    effects_map effects_without_removed;
    for( auto &outer : *effects ) {
        for( auto &inner : outer.second ) {
            if( !inner.second.is_removed() ) {
                effects_without_removed[outer.first][inner.first] = inner.second;
            }
        }
    }
    return effects_without_removed;
}
References effects.
Referenced by character_display::disp_info().
get_all_effects_of_type()
std::vector< const effect * > Creature::get_all_effects_of_type (const efftype_id & eff_id) const
Returns pointers to all effects matching given type.
Definition at line 1236 of file creature.cpp.
{
    std::vector<const effect *> ret;
    auto got_outer = effects->find( eff_id );
    if( got_outer != effects->end() ) {
        for( const auto &pr : got_outer->second ) {
            ret.push_back( &pr.second );
        }
    }
    return ret;
}
References effects, and cata::hash64_detail::ret.
get_anatomy()
anatomy_id Creature::get_anatomy () const
Definition at line 1523 of file creature.cpp.
{
    return creature_anatomy;
}
References creature_anatomy.
Referenced by get_random_body_part(), and set_body().
get_armor_bash()
int Creature::get_armor_bash (bodypart_id bp) const virtual
Reimplemented in Character, and monster.
Definition at line 1472 of file creature.cpp.
{
    return armor_bash_bonus;
}
References armor_bash_bonus.
Referenced by explosion_handler::do_blast(), and vehicle::part_collision().
get_armor_bash_base()
int Creature::get_armor_bash_base (bodypart_id bp) const virtual
Reimplemented in Character.
Definition at line 1484 of file creature.cpp.
{
    return armor_bash_bonus;
}
References armor_bash_bonus.
get_armor_bash_bonus()
int Creature::get_armor_bash_bonus () const virtual
Definition at line 1496 of file creature.cpp.
{
    return armor_bash_bonus;
}
References armor_bash_bonus.
get_armor_bullet()
int Creature::get_armor_bullet (bodypart_id bp) const virtual
Reimplemented in Character, and monster.
Definition at line 1480 of file creature.cpp.
{
    return armor_bullet_bonus;
}
References armor_bullet_bonus.
get_armor_bullet_base()
int Creature::get_armor_bullet_base (bodypart_id bp) const virtual
Reimplemented in Character.
Definition at line 1492 of file creature.cpp.
{
    return armor_bullet_bonus;
}
References armor_bullet_bonus.
get_armor_bullet_bonus()
int Creature::get_armor_bullet_bonus () const virtual
Definition at line 1504 of file creature.cpp.
{
    return armor_bullet_bonus;
}
References armor_bullet_bonus.
get_armor_cut()
int Creature::get_armor_cut (bodypart_id bp) const virtual
Reimplemented in Character, and monster.
Definition at line 1476 of file creature.cpp.
{
    return armor_cut_bonus;
}
References armor_cut_bonus.
Referenced by vehicle::part_collision().
get_armor_cut_base()
int Creature::get_armor_cut_base (bodypart_id bp) const virtual
Reimplemented in Character.
Definition at line 1488 of file creature.cpp.
{
    return armor_cut_bonus;
}
References armor_cut_bonus.
get_armor_cut_bonus()
int Creature::get_armor_cut_bonus () const virtual
Definition at line 1500 of file creature.cpp.
{
    return armor_cut_bonus;
}
References armor_cut_bonus.
get_armor_type()
virtual int Creature::get_armor_type (damage_type dt, bodypart_id bp) const pure virtual
Implemented in Character, and monster.
get_attitude_ui_data()
const std::pair< translation, nc_color > & Creature::get_attitude_ui_data (Attitude att) static
Creature Attitude as String and color.
Definition at line 1866 of file creature.cpp.
{
    using pair_t = std::pair<translation, nc_color>;
    static const std::array<pair_t, 5> strings {
        {
            pair_t {to_translation( "Hostile" ), c_red},
            pair_t {to_translation( "Neutral" ), h_white},
            pair_t {to_translation( "Friendly" ), c_green},
            pair_t {to_translation( "Any" ), c_yellow},
            pair_t {to_translation( "BUG: Behavior unnamed.  (Creature::get_attitude_ui_data)" ), h_red}
        }
    };
    if( static_cast<int>( att ) < 0 || static_cast<int>( att ) >= static_cast<int>( strings.size() ) ) {
        return strings.back();
    }
    return strings[att];
}
References c_green, c_red, c_yellow, h_red, h_white, and to_translation().
Referenced by game::list_monsters(), and safemode::show().
get_block_bonus()
int Creature::get_block_bonus () const virtual
Definition at line 1692 of file creature.cpp.
{
    return block_bonus; //base is 0
}
References block_bonus.
get_body()
const std::map< bodypart_str_id, bodypart > & Creature::get_body () const
Definition at line 1533 of file creature.cpp.
{
    return body;
}
References body.
Referenced by npc::adjust_worn(), Character::calc_all_parts_hp(), spell::can_cast(), npc::form_opinion(), get_hp(), get_hp_max(), Character::get_lowest_hp(), known_magic::has_enough_energy(), ranged::hit_with_aoe(), Character::hp_percentage(), spell_effect::pain_split(), Character::process_bionic(), Character::suffer(), Character::suffer_water_damage(), and heal_actor::use_healing_item().
get_dodge()
float Creature::get_dodge () const virtual
Reimplemented in Character, and monster.
Definition at line 1514 of file creature.cpp.
{
    return get_dodge_base() + get_dodge_bonus();
}
References get_dodge_base(), and get_dodge_bonus().
Referenced by mattack::boomer(), mattack::boomer_glow(), mattack::dodge_check(), Character::get_dodge(), monster::get_dodge(), iuse::tazer(), and ranged::throwing_dispersion().
get_dodge_base()
virtual float Creature::get_dodge_base () const pure virtual
Implemented in Character, and monster.
Referenced by get_dodge().
get_dodge_bonus()
float Creature::get_dodge_bonus () const virtual
Definition at line 1688 of file creature.cpp.
{
    return dodge_bonus;
}
References dodge_bonus.
Referenced by get_dodge().
get_effect() [1/2]
effect & Creature::get_effect (const efftype_id & eff_id, body_part bp = num_bp)
Definition at line 1220 of file creature.cpp.
{
    return const_cast<effect &>( const_cast<const Creature *>( this )->get_effect( eff_id, bp ) );
}
References get_effect().
get_effect() [2/2]
const effect & Creature::get_effect (const efftype_id & eff_id, body_part bp = num_bp) const
Return the effect that matches the given arguments exactly.
Definition at line 1225 of file creature.cpp.
{
    auto got_outer = effects->find( eff_id );
    if( got_outer != effects->end() ) {
        auto got_inner = got_outer->second.find( convert_bp( bp ) );
        if( got_inner != got_outer->second.end() && !got_inner->second.is_removed() ) {
            return got_inner->second;
        }
    }
    return effect::null_effect;
}
References convert_bp(), effects, and effect::null_effect.
Referenced by Character::activate_bionic(), monexamine::add_leash(), Character::apply_damage(), iexamine::autodoc(), Character::body_window(), bp_affected(), Character::calc_needs_rates(), npc::complain(), character_funcs::do_pause(), draw_limb_health(), heal_actor::finish_using(), get_effect(), get_effect_dur(), get_effect_int(), Character::healing_rate_medicine(), mattack::kamikaze(), monster::melee_attack(), Character::mend(), Character::mutate(), melee_actor::on_damage(), Character::process_bionic(), monster::process_effects_internal(), Character::process_one_effect(), monster::process_one_effect(), sounds::process_sound_markers(), Character::reduce_healing_effect(), remove_effect(), Character::reset_stats(), talk_effect_fun_t::set_add_effect(), monexamine::start_leading(), monexamine::tie_pet(), monexamine::untie_pet(), Character::update_needs(), Character::update_vitamins(), consume_drug_iuse::use(), change_scent_iuse::use(), Character::vomit(), avatar::wake_up(), and mattack::zombie_fuse().
get_effect_dur()
time_duration Creature::get_effect_dur (const efftype_id & eff_id, body_part bp = num_bp) const
Returns the duration of the matching effect.
Returns 0 if effect doesn't exist.
Definition at line 1247 of file creature.cpp.
{
    const effect &eff = get_effect( eff_id, bp );
    if( !eff.is_null() ) {
        return eff.get_duration();
    }
    return 0_turns;
}
References effect::get_duration(), get_effect(), and effect::is_null().
Referenced by iuse::adrenaline_injector(), mattack::check_money_left(), Character::check_needs_extremes(), iuse::ecig(), character_funcs::estimate_effect_dur(), heal_actor::finish_using(), Character::hardcoded_effects(), Character::hearing_ability(), Character::introduce_into_anesthesia(), iuse::jet_injector(), monster::nursebot_operate(), activity_handlers::operation_do_turn(), monexamine::pay_bot(), iuse::prozac(), Character::roll_bash_damage(), iuse::smoking(), heal_actor::use_healing_item(), and weed_msg().
get_effect_int()
int Creature::get_effect_int (const efftype_id & eff_id, body_part bp = num_bp) const
Returns the intensity of the matching effect.
Returns 0 if effect doesn't exist.
Definition at line 1256 of file creature.cpp.
{
    const effect &eff = get_effect( eff_id, bp );
    if( !eff.is_null() ) {
        return eff.get_intensity();
    }
    return 0;
}
References get_effect(), effect::get_intensity(), and effect::is_null().
Referenced by npc::address_player(), Character::bionics_adjusted_skill(), Character::body_window(), Character::check_needs_extremes(), Character::deal_damage(), eff_fun_mutating(), fungal_effects::fungalize(), Character::get_perceived_pain(), mattack::grab(), mattack::grab_drag(), Character::is_deaf(), game::mon_info_update(), monster::move_effects(), Character::process_turn(), mattack::ranged_pull(), mattack::resurrect(), game::save_cyborg(), Character::update_bodytemp(), musical_instrument_actor::use(), mutagen_actor::use(), Character::vomit(), character_effects::vomit_mod(), and Character::warmth().
get_env_resist()
int Creature::get_env_resist (bodypart_id bp) const virtual
Reimplemented in Character.
Definition at line 1468 of file creature.cpp.
{
    return 0;
}
Referenced by add_env_effect().
get_grammatical_genders()
std::vector< std::string > Creature::get_grammatical_genders () const virtual
Reimplemented in Character.
Definition at line 115 of file creature.cpp.
{
    // Returning empty list means we use the language-specified default
    return {};
}
get_hit()
float Creature::get_hit () const virtual
Definition at line 1518 of file creature.cpp.
{
    return get_hit_base() + get_hit_bonus();
}
References get_hit_base(), and get_hit_bonus().
Referenced by mattack::dodge_check(), monster::hit_roll(), and monster::melee_attack().
get_hit_base()
virtual float Creature::get_hit_base () const pure virtual
Implemented in Character, and monster.
Referenced by get_hit().
get_hit_bonus()
float Creature::get_hit_bonus () const virtual
Definition at line 1696 of file creature.cpp.
{
    return hit_bonus; //base is 0
}
References hit_bonus.
Referenced by get_hit().
get_hp() [1/2]
int Creature::get_hp () const virtual
Reimplemented in monster.
Definition at line 1658 of file creature.cpp.
{
    return get_hp( bodypart_id( "num_bp" ) );
}
References get_hp().
Referenced by Character::do_damage_for_bionic_failure(), and get_hp().
get_hp() [2/2]
int Creature::get_hp (const bodypart_id & bp) const virtual
Reimplemented in monster.
Definition at line 1646 of file creature.cpp.
{
    if( bp != bodypart_id( "num_bp" ) ) {
        return get_part_hp_cur( bp );
    }
    int hp_total = 0;
    for( const std::pair<const bodypart_str_id, bodypart> &elem : get_body() ) {
        hp_total += elem.second.get_hp_cur();
    }
    return hp_total;
}
References get_body(), and get_part_hp_cur().
Referenced by player_hit_message(), and ranged::print_dmg_msg().
get_hp_max() [1/2]
int Creature::get_hp_max () const virtual
Reimplemented in monster.
Definition at line 1675 of file creature.cpp.
{
    return get_hp_max( bodypart_id( "num_bp" ) );
}
References get_hp_max().
Referenced by npc::character_danger(), Character::deal_damage(), and get_hp_max().
get_hp_max() [2/2]
int Creature::get_hp_max (const bodypart_id & bp) const virtual
Reimplemented in monster.
Definition at line 1663 of file creature.cpp.
{
    if( bp != bodypart_id( "num_bp" ) ) {
        return get_part_hp_max( bp );
    }
    int hp_total = 0;
    for( const std::pair<const bodypart_str_id, bodypart> &elem : get_body() ) {
        hp_total += elem.second.get_hp_max();
    }
    return hp_total;
}
References get_body(), and get_part_hp_max().
Referenced by spell::energy_cost_string(), start_location::handle_heli_crash(), player_hit_message(), and ranged::print_dmg_msg().
get_killer()
Creature * Creature::get_killer () const virtual
Definition at line 1432 of file creature.cpp.
{
    return killer;
}
References killer.
Referenced by monster::die(), and mdeath::jabberwock().
get_melee()
virtual float Creature::get_melee () const pure virtual
Returns melee skill level, to be used to throttle dodge practice.
Implemented in Character, and monster.
Referenced by deal_melee_attack().
get_moves()
int Creature::get_moves () const
Definition at line 1410 of file creature.cpp.
{
    return moves;
}
References moves.
Referenced by activity_handlers::build_do_turn(), activity_handlers::craft_do_turn(), and pickup::do_pickup().
get_name()
virtual std::string Creature::get_name () const pure virtual
Implemented in Character, and monster.
Referenced by vehicle::can_close(), doors::close_door(), get_part(), game::process_voluntary_act_interrupt(), and projectile_attack().
get_num_blocks()
int Creature::get_num_blocks () const virtual
Definition at line 1446 of file creature.cpp.
{
    return num_blocks + num_blocks_bonus;
}
References num_blocks, and num_blocks_bonus.
Referenced by Character::process_turn().
get_num_blocks_bonus()
int Creature::get_num_blocks_bonus () const virtual
Definition at line 1454 of file creature.cpp.
{
    return num_blocks_bonus;
}
References num_blocks_bonus.
Referenced by ma_buff::apply_character(), and Character::hardcoded_effects().
get_num_dodges()
int Creature::get_num_dodges () const virtual
Definition at line 1450 of file creature.cpp.
{
    return num_dodges + num_dodges_bonus;
}
References num_dodges, and num_dodges_bonus.
Referenced by Character::process_turn().
get_num_dodges_base()
int Creature::get_num_dodges_base () const virtual
Definition at line 1462 of file creature.cpp.
{
    return num_dodges;
}
References num_dodges.
Referenced by enchantment::activate_passive().
get_num_dodges_bonus()
int Creature::get_num_dodges_bonus () const virtual
Definition at line 1458 of file creature.cpp.
{
    return num_dodges_bonus;
}
References num_dodges_bonus.
get_pain()
int Creature::get_pain () const virtual
Definition at line 1372 of file creature.cpp.
{
    return pain;
}
References pain.
Referenced by addict_effect(), Character::burn_move_stamina(), debug_menu::character_edit_menu(), Character::check_and_recover_morale(), get_perceived_pain(), Character::get_perceived_pain(), npc::has_painkiller(), Character::process_bionic(), Character::process_one_effect(), sounds::process_sound_markers(), npc::process_turn(), Character::regen(), Character::suffer_from_other_mutations(), and npc::use_painkiller().
get_pain_description()
std::pair< std::string, nc_color > Creature::get_pain_description () const virtual
Reimplemented in Character.
Definition at line 1382 of file creature.cpp.
{
    float scale = get_perceived_pain() / 10.f;
    std::string pain_string;
    nc_color pain_color = c_yellow;
    if( scale > 7 ) {
        pain_string = _( "Severe pain" );
    } else if( scale > 6 ) {
        pain_string = _( "Intense pain" );
    } else if( scale > 5 ) {
        pain_string = _( "Unmanageable pain" );
    } else if( scale > 4 ) {
        pain_string = _( "Distressing pain" );
    } else if( scale > 3 ) {
        pain_string = _( "Distracting pain" );
    } else if( scale > 2 ) {
        pain_string = _( "Moderate pain" );
    } else if( scale > 1 ) {
        pain_string = _( "Mild pain" );
    } else if( scale > 0 ) {
        pain_string = _( "Minimal pain" );
    } else {
        pain_string = _( "No pain" );
        pain_color = c_white;
    }
    return std::make_pair( pain_string, pain_color );
}
References _, c_white, c_yellow, and get_perceived_pain().
Referenced by Character::get_pain_description().
get_part() [1/2]
bodypart * Creature::get_part (const bodypart_id & id)
Definition at line 1546 of file creature.cpp.
{
    auto found = body.find( id.id() );
    if( found == body.end() ) {
        debugmsg( "Could not find bodypart %s in %s's body", id.id().c_str(), get_name() );
        return nullptr;
    }
    return &found->second;
}
References body, debugmsg, and get_name().
Referenced by Character::calc_all_parts_hp(), get_part_healed_total(), get_part_hp_cur(), get_part_hp_max(), mod_part_healed_total(), mod_part_hp_cur(), mod_part_hp_max(), Character::regen(), set_part_healed_total(), set_part_hp_cur(), and set_part_hp_max().
get_part() [2/2]
bodypart Creature::get_part (const bodypart_id & id) const
Definition at line 1556 of file creature.cpp.
{
    auto found = body.find( id.id() );
    if( found == body.end() ) {
        debugmsg( "Could not find bodypart %s in %s's body", id.id().c_str(), get_name() );
        return bodypart();
    }
    return found->second;
}
References body, debugmsg, and get_name().
get_part_healed_total()
int Creature::get_part_healed_total (const bodypart_id & id) const
Definition at line 1576 of file creature.cpp.
{
    return get_part( id ).get_healed_total();
}
References bodypart::get_healed_total(), and get_part().
Referenced by Character::enforce_minimum_healing().
get_part_hp_cur()
int Creature::get_part_hp_cur (const bodypart_id & id) const
Definition at line 1566 of file creature.cpp.
{
    return get_part( id ).get_hp_cur();
}
References bodypart::get_hp_cur(), and get_part().
Referenced by Character::apply_damage(), iexamine::autodoc(), Character::block_hit(), Character::blood_loss(), blood_magic(), Character::body_window(), debug_menu::character_edit_menu(), debug_menu::debug(), draw_limb_health(), Character::extended_description(), heal_actor::finish_using(), get_hp(), Character::heal(), Character::hp_percentage(), Character::hurtall(), Character::is_dead_state(), Character::is_limb_broken(), Character::is_limb_disabled(), Character::on_damage_of_type(), Character::on_hurt(), pick_part_to_heal(), Character::run_cost(), and memorial_logger::write().
get_part_hp_max()
int Creature::get_part_hp_max (const bodypart_id & id) const
Definition at line 1571 of file creature.cpp.
{
    return get_part( id ).get_hp_max();
}
References bodypart::get_hp_max(), and get_part().
Referenced by iexamine::autodoc(), Character::blood_loss(), blood_magic(), Character::body_window(), draw_limb_health(), draw_stats_info(), Character::extended_description(), heal_actor::finish_using(), get_hp_max(), Character::heal(), Character::hp_percentage(), Character::is_limb_disabled(), pick_part_to_heal(), Character::run_cost(), set_stats(), and memorial_logger::write().
get_path_avoid()
virtual std::set< tripoint > Creature::get_path_avoid () const pure virtual
Returns a set of points we do not want to path through.
Implemented in Character, monster, and npc.
get_pathfinding_settings()
virtual const pathfinding_settings & Creature::get_pathfinding_settings () const pure virtual
Returns settings for pathfinding.
Implemented in Character, monster, and npc.
get_perceived_pain()
int Creature::get_perceived_pain () const virtual
Reimplemented in Character.
Definition at line 1377 of file creature.cpp.
{
    return get_pain();
}
References get_pain().
Referenced by get_pain_description().
get_random_body_part()
bodypart_id Creature::get_random_body_part (bool main = false) const
Definition at line 1626 of file creature.cpp.
{
    // TODO: Refuse broken limbs, adjust for mutations
    const bodypart_id &part = get_anatomy()->random_body_part();
    return main ? part->main_part.id() : part;
}
References get_anatomy(), int_id< T >::id(), main(), and anatomy::random_body_part().
Referenced by mattack::acid_barf(), mattack::bio_op_impale(), mattack::dermatik(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::longswipe(), mattack::lunge(), game::place_player(), map::player_in_field(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::tentacle(), and mattack::vine().
get_size()
virtual m_size Creature::get_size () const pure virtual
Implemented in Character, and monster.
Referenced by describe_infrared(), ranged_target_size(), Character::reach_attack(), select_body_part(), size_melee_penalty(), and weight_capacity().
get_speed()
int Creature::get_speed () const virtual
Reimplemented in Character.
Definition at line 1510 of file creature.cpp.
{
    return get_speed_base() + get_speed_bonus();
}
References get_speed_base(), and get_speed_bonus().
Referenced by mdeath::blobsplit(), iuse::can_goo(), monster::extended_description(), Character::get_speed(), trapfunc::goo(), mattack::kamikaze(), vehicle::part_vpower_w(), process_turn(), monster::speed_rating(), vehicle::thrust(), and monster::turns_to_reach().
get_speed_base()
int Creature::get_speed_base () const virtual
Definition at line 1680 of file creature.cpp.
{
    return speed_base;
}
References speed_base.
Referenced by blobify(), iuse::can_goo(), iuse::extinguisher(), mattack::formblob(), get_speed(), trapfunc::glow(), trapfunc::goo(), iuse::granade_act(), monster::init_from_item(), monster::on_load(), poly_keep_speed(), monster::process_effects_internal(), Character::recalc_speed_bonus(), and mattack::resurrect().
get_speed_bonus()
int Creature::get_speed_bonus () const virtual
Definition at line 1684 of file creature.cpp.
{
    return speed_bonus;
}
References speed_bonus.
Referenced by get_speed(), monster::process_effects_internal(), and Character::recalc_speed_bonus().
get_value()
std::string Creature::get_value (const std::string & key) const
Definition at line 1347 of file creature.cpp.
{
    auto it = values.find( key );
    return ( it == values.end() ) ? "" : it->second;
}
References values.
Referenced by Character::activate_bionic(), Character::apply_skill_boost(), Character::burn_fuel(), Character::deactivate_bionic(), avatar::do_read(), pickup_activity_actor::do_turn(), draw_bionics_titlebar(), Character::drench(), Character::fuel_bionic_with(), Character::get_fuel_available(), Character::get_fuel_capacity(), vehicle::get_next_shifted_index(), Character::get_total_fuel_capacity(), game::handle_action(), pick_one_up(), Character::process_bionic(), query_consume_ownership(), iuse::radiocontrol(), rcdrive(), avatar::read(), game::remoteveh(), Character::restore_scent(), talk_effect_fun_t::set_adjust_var(), conditional_t< T >::set_compare_var(), conditional_t< T >::set_has_var(), Character::setID(), npc::talk_to_u(), activity_handlers::try_sleep_query(), and Character::update_fuel_storage().
get_weight()
virtual units::mass Creature::get_weight () const pure virtual
Implemented in Character, and monster.
Referenced by vehicle::part_collision().
gibType()
virtual field_type_id Creature::gibType () const pure virtual
Implemented in Character, and monster.
has_effect() [1/2]
bool Creature::has_effect (const efftype_id & eff_id, body_part bp = num_bp) const
Check if creature has the matching effect.
bp = num_bp means to check if the Creature has any effect of the matching type, targeted or untargeted.
Definition at line 1185 of file creature.cpp.
{
    return has_effect( eff_id, convert_bp( bp ) );
}
References convert_bp(), and has_effect().
Referenced by vehicle::activate_animal_follow(), Character::activate_bionic(), Character::active_light(), add_effect(), monexamine::add_leash(), addict_effect(), npc::address_needs(), iuse::adrenaline_injector(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antifungal(), iuse::antiparasitic(), temperature_effect::apply(), map::apply_character_light(), Character::apply_damage(), Character::apply_persistent_morale(), npc::assess_danger(), monexamine::attach_or_remove_saddle(), monster::attitude(), iexamine::autodoc(), Character::basic_symbol_color(), best_installer(), Character::block_hit(), trapfunc::board(), Character::body_window(), mattack::boomer_glow(), trapfunc::caltrops(), monster::can_act(), can_fire_turret(), avatar_action::can_fire_weapon(), monster::can_hear(), Character::can_mount(), npc::can_read(), cauterize_actor::can_use(), cauterize_actor::cauterize_effect(), check_art_charge_req(), mattack::check_money_left(), Character::check_needs_extremes(), relic_funcs::check_recharge_reqs(), game::check_safe_mode_allowed(), monster::color_with_effects(), npc::complain(), Character::consume_effects(), iuse::contacts(), Character::cough(), player::crafting_success_roll(), vehicle::damage_direct(), monexamine::deactivate_pet(), Character::deal_damage(), deal_melee_hit(), deal_projectile_attack(), trap::detect_trap(), monster::die(), Character::die(), game::disable_robot(), trapfunc::dissector(), Character::do_damage_for_bionic_failure(), character_funcs::do_pause(), game::do_turn(), stash_activity_actor::do_turn(), draw_limb_health(), Character::drench(), Character::eat(), eff_fun_hot(), iuse::einktabletpc(), explosion_handler::emp_blast(), game::examine(), npc::execute_action(), iuse::eyedrops(), find_auto_consume(), monster::find_dragged_foe(), activity_handlers::find_mount_do_turn(), find_targets_to_ungrab(), character_funcs::fine_detail_vision_mod(), heal_actor::finish_using(), fire(), ranged::fire_gun(), npc::form_opinion(), mattack::frag(), iuse::fungicide(), avatar::get_book_reader(), Character::get_dodge(), monster::get_dodge(), Character::get_miss_reason(), Character::get_pain_description(), monster::get_worn_armor_val(), give_aid_to(), trapfunc::glow(), trapfunc::goo(), mattack::grab(), mattack::grab_drag(), game::grabbed_veh_move(), game::handle_action(), Character::hardcoded_effects(), has_effect(), vehicle::has_harnessed_animal(), npc::heal_self(), Character::hearing_ability(), Character::hit_roll(), monster::hit_roll(), ranged::hit_with_aoe(), in_sleep_state(), character_effects::intimidation(), Character::introduce_into_anesthesia(), Character::irradiate(), Character::is_blind(), Character::is_hibernating(), Character::is_mounted(), Character::is_on_ground(), npc::is_stationary(), Character::item_handling_cost(), iuse::jet_injector(), mattack::kamikaze(), game::knockback(), trapfunc::lava(), Character::limb_color(), Character::load(), make_mon_corpse(), iuse::melatonin_tablet(), monster::melee_attack(), Character::mend(), iuse::meth(), monexamine::milk_source(), Character::mod_pain(), game::mon_info_update(), game::monmove(), Character::mount_creature(), monster::move(), npc::move(), avatar_action::move(), Character::move_effects(), monster::move_effects(), npc::move_pause(), monster::move_to(), npc::move_to(), iuse::multicooker(), monster::name_with_armor(), npc::npc_dismount(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), bite_actor::on_damage(), monster::on_damage_of_type(), Character::on_hit(), Character::on_hurt(), npc::on_load(), activity_handlers::operation_do_turn(), iuse::oxygen_bottle(), mattack::parrot(), vehicle::part_vpower_w(), Character::perform_technique(), monexamine::pet_menu(), photo_def_for_camera_point(), pick_part_to_heal(), Character::pick_technique(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), game::place_player(), monster::plan(), avatar_action::plthrow(), monster::print_info(), game::print_items_info(), Character::process_bionic(), Character::process_effects_internal(), monster::process_effects_internal(), item::process_litcig(), Character::process_one_effect(), sounds::process_sound_markers(), process_turn(), Character::process_turn(), monster::process_turn(), game::process_voluntary_act_interrupt(), iuse::prozac(), monster::push_to(), mattack::ranged_pull(), Character::react_to_felt_pain(), Character::recalc_sight_limits(), Character::regen(), npc::regen_ai_cache(), remove_effect(), monexamine::remove_leash(), Character::reset_stats(), resists_effect(), Character::rest_quality(), mattack::resurrect(), mattack::rifle(), iuse::robotcontrol(), Character::roll_bash_damage(), character_funcs::roll_can_sleep(), iexamine::safe(), sees(), vehicle::selfdrive(), npc::set_attitude(), conditional_t< T >::set_has_effect(), monster::setpos(), monexamine::shear_animal(), mattack::shriek_alert(), mattack::shriek_stun(), Character::sight_impaired(), trapfunc::sinkhole(), mdeath::splatter(), monster::stability_roll(), monexamine::start_leading(), vehicle::steering_effectiveness(), monexamine::stop_leading(), mattack::stretch_bite(), iuse::strong_antibiotic(), Character::suffer_from_asthma(), Character::suffer_from_bad_bionics(), Character::suffer_from_chemimbalance(), Character::suffer_from_other_mutations(), Character::suffer_from_schizophrenia(), Character::suffer_from_stimulants(), Character::suffer_from_sunburn(), Character::suffer_in_sunlight(), Character::suffer_while_awake(), Character::suffer_without_sleep(), monexamine::swap(), avatar_action::swim(), Character::symbol_color(), npc::talk_to_u(), mattack::tankgun(), iuse::thorazine(), ranged::throw_item(), vehicle::thrust(), monexamine::tie_pet(), npc::took_painkiller(), iuse::towel_common(), trapfunc::tripwire(), try_remove_grab(), activity_handlers::try_sleep_do_turn(), activity_handlers::try_sleep_finish(), gun_actor::try_target(), Character::uninstall_bionic(), monexamine::untie_pet(), Character::update_bodytemp(), Character::update_needs(), Character::update_vitamins(), cauterize_actor::use(), musical_instrument_actor::use(), game::use_computer(), vehicle::use_harness(), heal_actor::use_healing_item(), Character::vomit(), character_effects::vomit_mod(), wait(), Character::wait_effects(), avatar::wake_up(), Character::wake_up(), iuse::weak_antibiotic(), npc::wear_if_wanted(), Character::will_eat(), and mattack::zombie_fuse().
has_effect() [2/2]
bool Creature::has_effect (const efftype_id & eff_id, const bodypart_str_id & bp) const
Definition at line 1189 of file creature.cpp.
{
    // num_bp means anything targeted or not
    if( !bp ) {
        auto got = effects->find( eff_id );
        return got != effects->end() && !got->second.begin()->second.is_removed();
    } else {
        auto got_outer = effects->find( eff_id );
        if( got_outer != effects->end() ) {
            auto got_inner = got_outer->second.find( bp );
            if( got_inner != got_outer->second.end() && !got_inner->second.is_removed() ) {
                return true;
            }
        }
        return false;
    }
}
References effects.
has_effect_with_flag()
bool Creature::has_effect_with_flag (const std::string & flag, body_part bp = num_bp) const
Check if creature has any effect with the given flag.
Definition at line 1207 of file creature.cpp.
{
    const auto &tmp = convert_bp( bp ).id();
    for( const auto &elem : *effects ) {
        for( const auto &_it : elem.second ) {
            if( tmp == _it.first && !_it.second.is_removed() && _it.second.has_flag( flag ) ) {
                return true;
            }
        }
    }
    return false;
}
References convert_bp(), effects, and string_id< T >::id().
Referenced by Character::fall_damage_mod(), Character::has_nv(), Character::is_immune_damage(), Character::is_invisible(), game::phasing_move(), Character::recalc_sight_limits(), and teleport::teleport().
has_flag()
virtual bool Creature::has_flag (const m_flag) const inline virtual
Reimplemented in monster.
Definition at line 486 of file creature.h.
{
            return false;
        }
Referenced by iuse::cable_attach(), Character::deal_damage(), deal_melee_attack(), Character::process_bionic(), ranged_target_size(), Character::rooted(), Character::rooted_message(), sees(), Character::sees_with_specials(), and mattack::smash().
has_grab_break_tec()
virtual bool Creature::has_grab_break_tec () const pure virtual
Implemented in Character, and monster.
has_trait()
bool Creature::has_trait (const trait_id & flag) const virtual
Returns true if the player has the entered trait, returns false for non-humans.
Reimplemented in Character.
Definition at line 1331 of file creature.cpp.
{
    return false;
}
Referenced by bite_actor::on_damage(), and resists_effect().
has_weapon()
virtual bool Creature::has_weapon () const pure virtual
Implemented in Character, and monster.
Referenced by Character::on_hit(), and Character::pick_technique().
hit_roll()
virtual float Creature::hit_roll () const pure virtual
Should always be overwritten by the appropriate player/NPC/monster version.
Implemented in Character, and monster.
Referenced by select_body_part().
hp_percentage()
virtual int Creature::hp_percentage () const pure virtual
Returns overall % of HP remaining.
Implemented in Character, and monster.
Referenced by monster::plan().
impact()
virtual int Creature::impact (int force, const tripoint & pos) pure virtual
Deals falling/collision damage with terrain/creature at pos.
Implemented in Character, and monster.
in_sleep_state()
bool Creature::in_sleep_state () const virtual
Reimplemented in Character.
Definition at line 1423 of file creature.cpp.
{
    return has_effect( effect_sleep ) || has_effect( effect_lying_down ) ||
           has_effect( effect_npc_suspend );
}
References effect_lying_down, effect_npc_suspend, effect_sleep, and has_effect().
Referenced by Character::in_sleep_state(), and monster::melee_attack().
in_species()
bool Creature::in_species (const species_id &) const virtual
Reimplemented in Character, and monster.
Definition at line 971 of file creature.cpp.
{
    return false;
}
Referenced by Character::pick_technique(), and Character::sees_with_specials().
is_avatar()
virtual bool Creature::is_avatar () const inline virtual
Reimplemented in avatar.
Definition at line 95 of file creature.h.
{
            return false;
        }
Referenced by map::board_vehicle(), melee_actor::call(), doors::close_door(), complete_construction(), Character::consume_item(), debug_menu::debug(), destroyed_armor_msg(), iuse::disassemble(), Character::dismount(), map::displace_vehicle(), aim_activity_actor::do_turn(), throw_activity_actor::do_turn(), drop_or_handle(), Character::fall_asleep(), spell_effect::flashbang(), character_funcs::get_crafting_helpers(), handle_player_display_action(), Character::hardcoded_effects(), activity_handlers::jackhammer_finish(), iuse::ma_manual(), marloss_common(), Character::mount_creature(), npc::move_to(), iuse::note_bionics(), activity_handlers::pickaxe_finish(), sees(), player::select_requirements(), show_armor_layers_ui(), show_mutations_ui(), character_funcs::show_skill_capped_notice(), character_funcs::siphon(), read_inventory_preset::sort_compare(), disassemble_activity_actor::start(), teleport::teleport(), activity_handlers::train_finish(), teleporter_list::translocate(), try_reject_mutagen(), and character_funcs::try_uncanny_dodge().
is_dangerous_field()
bool Creature::is_dangerous_field (const field_entry & entry) const
Returns true if the given field entry is dangerous to us.
Definition at line 197 of file creature.cpp.
{
    // If it's dangerous and we're not immune return true, else return false
    return entry.is_dangerous() && !is_immune_field( entry.get_field_type() );
}
References field_entry::get_field_type(), field_entry::is_dangerous(), and is_immune_field().
Referenced by npc::could_move_onto(), npc::find_corpse_to_pulp(), game::get_dangerous_tile(), npc::good_escape_direction(), and is_dangerous_fields().
is_dangerous_fields()
bool Creature::is_dangerous_fields (const field & fld) const
Returns true if there is a field in the field set that is dangerous to us.
Definition at line 185 of file creature.cpp.
{
    // Else check each field to see if it's dangerous to us
    for( auto &dfield : fld ) {
        if( is_dangerous_field( dfield.second ) ) {
            return true;
        }
    }
    // No fields were found to be dangerous, so the field set isn't dangerous
    return false;
}
References is_dangerous_field().
Referenced by character_funcs::do_pause(), npc::sees_dangerous_field(), and monster::will_move_to().
is_dead_state()
virtual bool Creature::is_dead_state () const pure virtual
Implemented in Character, and monster.
Referenced by check_dead_state(), deal_damage(), mattack::evolve_kill_strike(), Character::melee_attack(), vehicle::part_collision(), Character::perform_special_attacks(), and process_turn().
is_elec_immune()
virtual bool Creature::is_elec_immune () const pure virtual
Implemented in Character, and monster.
Referenced by mattack::thrown_by_judo(), and mdefense::zapback().
is_fake()
bool Creature::is_fake () const virtual
Returns true for non-real Creatures used temporarily; i.e.
fake NPC's used for turret fire.
Definition at line 976 of file creature.cpp.
{
    return fake;
}
References fake.
Referenced by auto_find_hostile_target(), npc::die(), item::on_pickup(), npc::set_attitude(), npc::set_fac(), set_killer(), npc::setpos(), and npc::travel_overmap().
is_hallucination()
virtual bool Creature::is_hallucination () const pure virtual
Implemented in avatar, monster, and npc.
Referenced by Character::block_hit(), Character::deal_damage(), deal_melee_attack(), deal_melee_hit(), knock_back_from(), Character::melee_special_effects(), mission::on_creature_death(), vehicle::part_collision(), monster::push_to(), and sees().
is_immune_damage()
virtual bool Creature::is_immune_damage (damage_type type) const pure virtual
Implemented in Character, and monster.
Referenced by deal_damage_handle_type().
is_immune_effect()
virtual bool Creature::is_immune_effect (const efftype_id & type) const pure virtual
Implemented in Character, and monster.
Referenced by add_effect(), add_env_effect(), mattack::bio_op_takedown(), map::creature_in_field(), and mattack::shriek_stun().
is_immune_field()
virtual bool Creature::is_immune_field (const field_type_id &) const inline virtual
Returns true if we are immune to the field type with the given fid.
Does not handle intensity, so this function should only be called through is_dangerous_field().
Reimplemented in Character, and monster.
Definition at line 327 of file creature.h.
{
            return false;
        }
Referenced by map::creature_in_field(), is_dangerous_field(), Character::is_immune_field(), and monster::is_immune_field().
is_monster()
virtual bool Creature::is_monster () const inline virtual
Reimplemented in monster.
Definition at line 101 of file creature.h.
{
            return false;
        }
Referenced by auto_find_hostile_target(), vehicle::can_close(), doors::close_door(), map::creature_in_field(), npc::evaluate_enemy(), trapfunc::ledge(), Character::melee_attack(), ranged::print_dmg_msg(), game::swap_critters(), gun_actor::try_target(), and game::non_dead_range< T >::iterator::valid().
is_npc()
virtual bool Creature::is_npc () const inline virtual
Reimplemented in npc, and player.
Definition at line 98 of file creature.h.
{
            return false;
        }
Referenced by Character::apply_damage(), Character::assign_activity(), auto_find_hostile_target(), Character::calc_needs_rates(), Character::can_takeoff(), Character::check_outbounds_activity(), complete_construction(), Character::consume(), Character::consume_effects(), Character::consume_item(), Character::cough(), character_funcs::do_pause(), migration_cancel_activity_actor::do_turn(), npc::enough_time_to_reload(), npc::evaluate_enemy(), mattack::formblob(), mattack::gene_sting(), Character::hardcoded_effects(), Character::has_fire(), Character::healing_rate(), Character::knock_back_to(), target_ui::list_friendlies_in_lof(), monster::melee_attack(), melee_message(), Character::mod_stamina(), monster::move(), npc::mug_player(), Character::on_hurt(), player_hit_message(), Character::process_turn(), item::reach_range(), explosion_handler::explosion_funcs::regular(), character_funcs::select_ammo(), crafting::select_tool_component(), show_armor_layers_ui(), Character::suffer_from_asthma(), Character::suffer_from_schizophrenia(), Character::takeoff(), gun_actor::try_target(), Character::update_body(), Character::update_needs(), Character::update_stomach(), Character::update_vitamins(), and game::non_dead_range< T >::iterator::valid().
is_on_ground()
virtual bool Creature::is_on_ground () const pure virtual
Implemented in Character, and monster.
is_player()
virtual bool Creature::is_player () const inline virtual
Reimplemented in npc, and player.
Definition at line 92 of file creature.h.
{
            return false;
        }
Referenced by add_effect(), Character::armor_absorb(), Character::bionics_install_failure(), vehicle::can_close(), Character::can_wear(), Character::check_needs_extremes(), doors::close_door(), Character::deal_damage(), Character::disp_name(), Character::eat(), npc::enough_time_to_reload(), npc::evaluate_enemy(), Character::extended_description(), mattack::formblob(), mattack::gene_sting(), mattack::grab_drag(), Character::hardcoded_effects(), Character::impact(), npc::is_ally(), npc::is_friendly(), npc::is_obeying(), Character::melee_attack(), monster::melee_attack(), Character::melee_special_effects(), npc::method_of_attack(), monster::move(), Character::mutation_attacks(), npc::on_attacked(), melee_actor::on_damage(), Character::on_hit(), Character::perform_technique(), player_hit_message(), Character::practice(), ranged::print_dmg_msg(), Character::print_health(), process_effects(), projectile_attack(), mattack::ranged_pull(), Character::react_to_felt_pain(), explosion_handler::explosion_funcs::regular(), remove_effect(), sees(), Character::sees(), Character::sees_with_infrared(), Character::shout(), game::swap_critters(), gun_actor::try_target(), and Character::update_needs().
is_symbol_highlighted()
bool Creature::is_symbol_highlighted () const virtual
Reimplemented in monster.
Definition at line 1828 of file creature.cpp.
{
    return false;
}
Referenced by draw().
is_underwater()
bool Creature::is_underwater () const virtual
Reimplemented in monster.
Definition at line 170 of file creature.cpp.
{
    return underwater;
}
References underwater.
Referenced by iuse::antifungal(), iuse::antiparasitic(), iuse::arrow_flammable(), cata_event_dispatch::avatar_moves(), Character::basic_symbol_color(), iuse::burrow(), Character::can_eat(), firestarter_actor::can_use(), cauterize_actor::can_use(), fireweapon_off_actor::can_use(), musical_instrument_actor::can_use(), repair_item_actor::can_use_tool(), iuse::chainsaw_off(), iuse::combatsaw_off(), Character::consume_item(), iuse::contacts(), iuse::cs_lajatang_off(), iuse::dive_tank(), character_funcs::do_pause(), game::do_turn(), iuse::dog_whistle(), iuse::e_combatsaw_off(), iuse::ecs_lajatang_off(), iuse::einktabletpc(), iuse::elec_chainsaw_off(), iuse::eyedrops(), iuse::firecracker(), iuse::firecracker_pack(), iuse::fish_trap(), iuse::fungicide(), Character::get_shout_volume(), ranged::get_weapon_dispersion(), iuse::gun_repair(), iuse::hand_crank(), ranged::handle_gun_damage(), monster::is_underwater(), iuse::jackhammer(), mine_activity(), avatar_action::move(), iuse::multicooker(), iuse::pack_item(), iuse::pheromone(), iuse::pickaxe(), map::player_in_field(), iuse::portable_game(), Character::recalc_sight_limits(), sees(), Character::set_underwater(), Character::shout(), Character::sight_impaired(), Character::suffer(), Character::suffer_from_asthma(), avatar_action::swim(), Character::swim_speed(), toolweapon_on(), avatar_funcs::try_to_sleep(), iuse::unfold_generic(), iuse::unpack_item(), iuse_transform::use(), unfold_vehicle_iuse::use(), fireweapon_off_actor::use(), fireweapon_on_actor::use(), musical_instrument_actor::use(), heal_actor::use(), place_trap_actor::use(), sew_advanced_actor::use(), game::vertical_move(), and iuse::vibe().
is_warm()
bool Creature::is_warm () const virtual
Reimplemented in Character, and monster.
Definition at line 966 of file creature.cpp.
{
    return true;
}
Referenced by Character::melee_special_effects(), and Character::sees_with_infrared().
knock_back_from()
void Creature::knock_back_from (const tripoint & p)
Definition at line 1891 of file creature.cpp.
{
    if( p == pos() ) {
        return; // No effect
    }
    if( is_hallucination() ) {
        die( nullptr );
        return;
    }
    tripoint to = pos();
    if( p.x < posx() ) {
        to.x++;
    }
    if( p.x > posx() ) {
        to.x--;
    }
    if( p.y < posy() ) {
        to.y++;
    }
    if( p.y > posy() ) {
        to.y--;
    }
    knock_back_to( to );
}
References die(), is_hallucination(), knock_back_to(), pos(), posx(), posy(), tripoint::x, and tripoint::y.
Referenced by Character::perform_technique().
knock_back_to()
virtual void Creature::knock_back_to (const tripoint & to) pure virtual
Knocks the creature to a specified tile.
Implemented in Character, and monster.
Referenced by knock_back_from().
load()
void Creature::load (const JsonObject & jsin) protected
Definition at line 3053 of file savegame_json.cpp.
{
    jsin.allow_omitted_members();
    jsin.read( "moves", moves );
    jsin.read( "pain", pain );
    killer = nullptr; // see Creature::load
    if( jsin.has_object( "effects" ) ) {
        // Because JSON requires string keys we need to convert back to our bp keys
        std::unordered_map<std::string, std::unordered_map<std::string, effect>> tmp_map;
        jsin.read( "effects", tmp_map );
        int key_num = 0;
        for( auto maps : tmp_map ) {
            const efftype_id id( maps.first );
            if( !id.is_valid() ) {
                debugmsg( "Invalid effect: %s", id.c_str() );
                continue;
            }
            for( auto i : maps.second ) {
                if( !( std::istringstream( i.first ) >> key_num ) ) {
                    key_num = 0;
                }
                const bodypart_str_id &bp = convert_bp( static_cast<body_part>( key_num ) );
                effect &e = i.second;
                ( *effects )[id][bp] = e;
                on_effect_int_change( id, e.get_intensity(), bp );
            }
        }
    }
    jsin.read( "values", values );
    jsin.read( "blocks_left", num_blocks );
    jsin.read( "dodges_left", num_dodges );
    jsin.read( "num_blocks_bonus", num_blocks_bonus );
    jsin.read( "num_dodges_bonus", num_dodges_bonus );
    jsin.read( "armor_bash_bonus", armor_bash_bonus );
    jsin.read( "armor_cut_bonus", armor_cut_bonus );
    jsin.read( "armor_bullet_bonus", armor_bullet_bonus );
    jsin.read( "speed", speed_base );
    jsin.read( "speed_bonus", speed_bonus );
    jsin.read( "dodge_bonus", dodge_bonus );
    jsin.read( "block_bonus", block_bonus );
    jsin.read( "hit_bonus", hit_bonus );
    jsin.read( "underwater", underwater );
    jsin.read( "body", body );
    fake = false; // see Creature::load
    on_stat_change( "pain", pain );
}
References JsonObject::allow_omitted_members(), convert_bp(), debugmsg, effect::get_intensity(), JsonObject::has_object(), base_camps::id, pain, and JsonObject::read().
Referenced by Character::load(), and monster::load().
load_hit_range()
void Creature::load_hit_range (const JsonObject & jo) static
Definition at line 1970 of file creature.cpp.
{
    if( jo.has_array( "even_good" ) ) {
        jo.read( "even_good", dispersion_for_even_chance_of_good_hit );
    }
}
References dispersion_for_even_chance_of_good_hit, JsonObject::has_array(), and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
made_of()
virtual bool Creature::made_of (const material_id & m) const pure virtual
Implemented in Character, and monster.
made_of_any()
virtual bool Creature::made_of_any (const std::set< material_id > & ms) const pure virtual
Implemented in Character, and monster.
Referenced by mattack::evolve_kill_strike().
mod_block_bonus()
void Creature::mod_block_bonus (int nblock) virtual
Definition at line 1771 of file creature.cpp.
{
    block_bonus += nblock;
}
References block_bonus.
Referenced by mod_stat().
mod_dodge_bonus()
void Creature::mod_dodge_bonus (float ndodge) virtual
Definition at line 1767 of file creature.cpp.
{
    dodge_bonus += ndodge;
}
References dodge_bonus.
Referenced by mod_stat(), monster::process_one_effect(), and Character::reset_stats().
mod_hit_bonus()
void Creature::mod_hit_bonus (float nhit) virtual
Definition at line 1775 of file creature.cpp.
{
    hit_bonus += nhit;
}
References hit_bonus.
Referenced by mod_stat().
mod_moves()
void Creature::mod_moves (int nmoves)
Definition at line 1414 of file creature.cpp.
{
    moves += nmoves;
}
References moves.
Referenced by Character::activate_bionic(), Character::activate_mutation(), iexamine::autodoc(), melee_actor::call(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), Character::change_side(), doors::close_door(), Character::consume_med(), iuse::crowbar(), iexamine::cvdmachine(), Character::deactivate_mutation(), iuse::directional_hologram(), Character::dismount(), do_aim(), move_items_activity_actor::do_turn(), throw_activity_actor::do_turn(), Character::feed_furnace_with(), Character::feed_reactor_with(), iexamine::fertilize_plant(), find_auto_consume(), iexamine::fireplace(), Character::fuel_bionic_with(), iuse::geiger(), game::handle_action(), harvest_common(), mattack::longswipe(), monexamine::mech_hack(), Character::melee_attack(), monster::melee_attack(), iexamine::migo_nerve_cluster(), mill_activate(), mill_load_food(), mod_stat(), Character::mount_creature(), move_item(), npc::move_to(), iuse::mp3(), iuse::mp3_on(), npc::npc_dismount(), game::npc_menu(), item_location::impl::item_on_person::obtain(), item_location::impl::item_in_container::obtain(), pickup::obtain_and_tokenize_items(), npc::on_load(), iexamine::pit(), iexamine::pit_covered(), iexamine::quern_examine(), Character::reach_attack(), avatar::read(), bandolier_actor::reload(), monster::shove_vehicle(), iexamine::sign(), smash(), smoker_activate(), smoker_load_food(), iexamine::smoker_options(), activity_handlers::start_fire_do_turn(), Character::takeoff(), ranged::throw_item(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), avatar_funcs::try_disarm_npc(), avatar_funcs::try_steal_from_npc(), avatar_funcs::unload_item(), change_scent_iuse::use(), place_npc_iuse::use(), deploy_furn_actor::use(), firestarter_actor::use(), place_trap_actor::use(), avatar_action::use_item(), and game::vertical_move().
mod_num_dodges_bonus()
void Creature::mod_num_dodges_bonus (int ndodges) virtual
Definition at line 1724 of file creature.cpp.
{
    num_dodges_bonus += ndodges;
}
References num_dodges_bonus.
Referenced by enchantment::activate_passive(), and ma_buff::apply_character().
mod_pain()
void Creature::mod_pain (int npain) virtual
Reimplemented in Character.
Definition at line 1353 of file creature.cpp.
{
    mod_pain_noresist( npain );
}
References mod_pain_noresist().
Referenced by deal_damage(), Character::mod_pain(), and mod_stat().
mod_pain_noresist()
void Creature::mod_pain_noresist (int npain) virtual
Definition at line 1358 of file creature.cpp.
{
    set_pain( pain + npain );
}
References pain, and set_pain().
Referenced by iuse::artifact(), mod_pain(), game::process_artifact(), relic_funcs::process_recharge_entry(), spell_effect::recover_energy(), and test_crossing_threshold().
mod_part_healed_total()
void Creature::mod_part_healed_total (const bodypart_id & id, int mod)
Definition at line 1606 of file creature.cpp.
{
    get_part( id )->mod_healed_total( mod );
}
References get_part(), and bodypart::mod_healed_total().
Referenced by Character::healall().
mod_part_hp_cur()
void Creature::mod_part_hp_cur (const bodypart_id & id, int mod)
Definition at line 1596 of file creature.cpp.
{
    get_part( id )->mod_hp_cur( mod );
}
References get_part(), and bodypart::mod_hp_cur().
Referenced by Character::apply_damage(), blood_magic(), Character::heal(), and Character::hurtall().
mod_part_hp_max()
void Creature::mod_part_hp_max (const bodypart_id & id, int mod)
Definition at line 1601 of file creature.cpp.
{
    get_part( id )->mod_hp_max( mod );
}
References get_part(), and bodypart::mod_hp_max().
mod_speed_bonus()
void Creature::mod_speed_bonus (int nspeed) virtual
Definition at line 1763 of file creature.cpp.
{
    speed_bonus += nspeed;
}
References speed_bonus.
Referenced by mod_stat(), monster::process_one_effect(), and Character::recalc_speed_bonus().
mod_stat()
void Creature::mod_stat (const std::string & stat, float modifier) virtual
Reimplemented in Character.
Definition at line 1701 of file creature.cpp.
{
    if( stat == "speed" ) {
        mod_speed_bonus( modifier );
    } else if( stat == "dodge" ) {
        mod_dodge_bonus( modifier );
    } else if( stat == "block" ) {
        mod_block_bonus( modifier );
    } else if( stat == "hit" ) {
        mod_hit_bonus( modifier );
    } else if( stat == "pain" ) {
        mod_pain( modifier );
    } else if( stat == "moves" ) {
        mod_moves( modifier );
    } else {
        add_msg( "Tried to modify a nonexistent stat %s.", stat.c_str() );
    }
}
References add_msg(), mod_block_bonus(), mod_dodge_bonus(), mod_hit_bonus(), mod_moves(), mod_pain(), and mod_speed_bonus().
Referenced by Character::mod_stat().
move_effects()
virtual bool Creature::move_effects (bool attacking) pure virtual
Processes move stopping effects.
Returns false if movement is stopped.
Implemented in Character, and monster.
on_damage_of_type()
virtual void Creature::on_damage_of_type (int , damage_type , const bodypart_id &) inline protected virtual
Reimplemented in Character, and monster.
Definition at line 844 of file creature.h.
{}
Referenced by deal_damage_handle_type(), and monster::on_damage_of_type().
on_dodge()
void Creature::on_dodge (Creature * source, int difficulty) virtual
This creature just dodged an attack - possibly special/ranged attack - from source.
Players should train dodge, monsters may use some special defenses.
Reimplemented in Character.
Definition at line 957 of file creature.cpp.
{
}
Referenced by mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), deal_melee_attack(), mattack::dermatik(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::impale(), mattack::longswipe(), mattack::lunge(), mattack::ranged_pull(), mattack::smash(), mattack::stretch_attack(), mattack::stretch_bite(), and mattack::tentacle().
on_effect_int_change()
virtual void Creature::on_effect_int_change (const efftype_id & , int , const bodypart_str_id &) inline protected virtual
Reimplemented in Character.
Definition at line 843 of file creature.h.
{}
Referenced by add_effect(), process_effects(), and remove_effect().
on_hit()
virtual void Creature::on_hit (Creature * source, bodypart_id bp_hit, dealt_projectile_attack const * proj = nullptr) pure virtual
This creature just got hit by an attack - possibly special/ranged attack - from source.
Parameters
source Source creature, can be nullptr
proj Source projectile, can be nullptr Players should train dodge, possibly counter-attack somehow.
Implemented in Character, and monster.
Referenced by mattack::acid_barf(), mattack::bio_op_impale(), mattack::bio_op_takedown(), melee_actor::call(), deal_melee_hit(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::impale(), mattack::longswipe(), mattack::lunge(), mattack::stretch_attack(), mattack::stretch_bite(), and mattack::tentacle().
on_stat_change()
virtual void Creature::on_stat_change (const std::string & , int) inline protected virtual
Reimplemented in Character.
Definition at line 842 of file creature.h.
{}
Referenced by set_pain().
operator=() [1/2]
Creature & Creature::operator= (const Creature &) protected default
operator=() [2/2]
Creature & Creature::operator= (Creature &&) protected default
pos()
virtual const tripoint & Creature::pos () const pure virtual
Implemented in Character, and monster.
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), mdefense::acidsplash(), npc::alt_attack(), spell_effect::area_pull(), spell_effect::area_push(), auto_find_hostile_target(), vehicle::automatic_fire_turret(), npc::avoid_friendly_fire(), spell_effect::bash(), bleed(), mattack::boomer(), mattack::boomer_glow(), calculate_spell_effect_area(), mon_spellcasting_actor::call(), gun_actor::call(), spell::cast_all_effects(), enchantment::cast_enchantment_spell(), trapfunc::cast_spell(), spell_effect::charm_monster(), mattack::chickenbot(), mattack::copbot(), map::could_see_items(), map::creature_in_field(), damage_targets(), Character::deal_damage(), debug_menu::debug(), map::displace_vehicle(), draw_critter_internal(), npc::enough_time_to_reload(), mattack::evolve_kill_strike(), npc::execute_action(), mattack::flame(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::frag(), mattack::fungus_fortify(), Character::get_hostile_creatures(), Character::get_visible_creatures(), mattack::grab_drag(), mattack::howl(), is_adjacent(), spell::is_target_in_range(), spell::is_valid_target(), Character::is_visible_in_range(), knock_back_from(), game::list_monsters(), mattack::longswipe(), mattack::lunge(), Character::melee_attack(), monster::melee_attack(), npc::method_of_attack(), spell_effect::mod_moves(), spell_effect::morale(), npc::move_to(), mattack::multi_robot(), spell_effect::mutate(), Character::on_dodge(), spell_effect::pain_split(), vehicle::part_collision(), Character::perform_technique(), monster::plan(), ranged::print_dmg_msg(), projectile_attack(), spell_effect::projectile_attack(), mattack::pull_metal_weapon(), mattack::ranged_pull(), mattack::rattle(), target_ui::recalc_aim_turning_penalty(), spell_effect::recover_energy(), mdefense::return_fire(), mattack::rifle(), mattack::riotbot(), mattack::science(), sees(), Character::sees(), map::sees_some_items(), Character::sees_with_infrared(), map::shake_vehicle(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::smash(), mattack::smash_specific(), spell_effect::spawn_ethereal_item(), mattack::spit_sap(), sting_get_target(), sting_shoot(), mattack::stretch_attack(), mattack::stretch_bite(), game::swap_critters(), swap_pos(), mattack::tankgun(), ranged::targetable_creatures(), teleport::teleport(), mattack::tentacle(), ranged::throwing_dispersion(), spell_effect::timed_event(), mattack::tindalos_teleport(), spell_effect::transform_blast(), Character::valid_aoe_technique(), spell_effect::vomit(), within_target_range(), npc::wont_hit_friend(), and mdefense::zapback().
posx()
virtual int Creature::posx () const pure virtual
Implemented in Character, and monster.
Referenced by Character::deal_damage(), map::displace_vehicle(), draw(), draw_critter_internal(), knock_back_from(), player_hit_message(), mattack::ranged_pull(), mattack::riotbot(), sees(), map::shake_vehicle(), mattack::shockstorm(), and Character::valid_aoe_technique().
posy()
virtual int Creature::posy () const pure virtual
Implemented in Character, and monster.
Referenced by Character::deal_damage(), map::displace_vehicle(), draw(), draw_critter_internal(), knock_back_from(), player_hit_message(), mattack::ranged_pull(), mattack::riotbot(), sees(), map::shake_vehicle(), mattack::shockstorm(), and Character::valid_aoe_technique().
posz()
virtual int Creature::posz () const pure virtual
Implemented in Character, and monster.
Referenced by map::displace_vehicle(), draw(), draw_critter_internal(), is_adjacent(), mattack::riotbot(), sees(), map::shake_vehicle(), mattack::shockstorm(), and mattack::shriek_stun().
power_rating()
virtual float Creature::power_rating () const pure virtual
Returns an approximation of the creature's strength.
Implemented in Character, and monster.
Referenced by mattack::chickenbot(), and mattack::multi_robot().
print_info()
virtual int Creature::print_info (const catacurses::window & w, int vStart, int vLines, int column) const pure virtual
Write information about this creature.
Parameters
w the window to print the text into.
vStart vertical start to print, that means the first line to print.
vLines number of lines to print at most (printing less is fine).
column horizontal start to print (column), horizontal end is one character before the right border of the window (to keep the border).
Returns
The line just behind the last printed line, that means multiple calls to this can be stacked, the return value is acceptable as vStart for the next call without creating empty lines or overwriting lines.
Implemented in npc, Character, and monster.
Referenced by game::list_monsters(), target_ui::panel_target_info(), and editmap::update_view_with_help().
process_effects()
void Creature::process_effects ()
Processes through all the effects on the Creature.
This is the only function that is allowed to remove effects.
Definition at line 1265 of file creature.cpp.
{
    process_effects_internal();
    // id's and body_part's of all effects to be removed. If we ever get player or
    // monster specific removals these will need to be moved down to that level and then
    // passed in to this function.
    std::vector<std::pair<efftype_id, bodypart_str_id>> to_remove;
    // Decay/removal of effects
    for( auto &elem : *effects ) {
        for( auto &_it : elem.second ) {
            if( _it.second.is_removed() ) {
                to_remove.emplace_back( elem.first, _it.first );
                continue;
            }
            // Add any effects that others remove to the removal list
            for( const efftype_id &removed_effect : _it.second.get_removes_effects() ) {
                to_remove.emplace_back( removed_effect, bodypart_str_id::NULL_ID() );
            }
            effect &e = _it.second;
            const int prev_int = e.get_intensity();
            // Run decay effects, marking effects for removal as necessary.
            if( e.decay( calendar::turn, is_player() ) ) {
                to_remove.emplace_back( elem.first, _it.first );
            }
            if( e.get_intensity() != prev_int && e.get_duration() > 0_turns ) {
                on_effect_int_change( e.get_id(), e.get_intensity(), e.get_bp() );
            }
        }
    }
    // Run the on-remove effects
    for( const std::pair<efftype_id, bodypart_str_id> &r : to_remove ) {
        remove_effect( r.first, r.second );
    }
    // Actually remove effects. This should be the last thing done in process_effects().
    for( const std::pair<efftype_id, bodypart_str_id> &r : to_remove ) {
        if( !r.second ) {
            effects->erase( r.first );
        } else {
            ( *effects )[r.first].erase( r.second );
            // If there are no more effects of a given type remove the type map
            if( ( *effects )[r.first].empty() ) {
                effects->erase( r.first );
            }
        }
    }
}
References effect::decay(), effects, effect::get_bp(), effect::get_duration(), effect::get_id(), effect::get_intensity(), is_player(), string_id< body_part_type >::NULL_ID(), on_effect_int_change(), process_effects_internal(), remove_effect(), and calendar::turn.
Referenced by npc::on_load(), and process_turn().
process_effects_internal()
virtual void Creature::process_effects_internal () pure virtual
Processes effects according to class (monster, player)
Implemented in Character, and monster.
Referenced by process_effects().
process_one_effect()
virtual void Creature::process_one_effect (effect & e, bool is_new) protected pure virtual
Processes one effect on the Creature.
Implemented in Character, and monster.
Referenced by add_effect().
process_turn()
void Creature::process_turn () virtual
Processes effects and bonuses and allocates move points based on speed.
Reimplemented in Character, monster, and npc.
Definition at line 152 of file creature.cpp.
{
    if( is_dead_state() ) {
        return;
    }
    reset_bonuses();
    process_effects();
    // Call this in case any effects have changed our stats
    reset_stats();
    // add an appropriate number of moves
    if( !has_effect( effect_ridden ) ) {
        moves += get_speed();
    }
}
References effect_ridden, get_speed(), has_effect(), is_dead_state(), moves, process_effects(), reset_bonuses(), and reset_stats().
Referenced by Character::process_turn(), and monster::process_turn().
ranged_target_size()
double Creature::ranged_target_size () const
Size of the target this creature presents to ranged weapons.
0.0 means unhittable, 1.0 means all projectiles going through this creature's tile will hit it.
Definition at line 547 of file ranged.cpp.
{
    if( has_flag( MF_HARDTOSHOOT ) ) {
        switch( get_size() ) {
            case MS_TINY:
            case MS_SMALL:
                return occupied_tile_fraction( MS_TINY );
            case MS_MEDIUM:
                return occupied_tile_fraction( MS_SMALL );
            case MS_LARGE:
                return occupied_tile_fraction( MS_MEDIUM );
            case MS_HUGE:
                return occupied_tile_fraction( MS_LARGE );
            default:
                break;
        }
    }
    return occupied_tile_fraction( get_size() );
}
References get_size(), has_flag(), MF_HARDTOSHOOT, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, and occupied_tile_fraction().
Referenced by npc::confident_throw_range(), draw_throw_aim(), target_ui::panel_fire_mode_aim(), and projectile_attack().
remove_effect() [1/2]
bool Creature::remove_effect (const efftype_id & eff_id, body_part bp = num_bp)
Removes a listed effect.
bp = num_bp means to remove all effects of a given type, targeted or untargeted. Returns true if anything was removed.
Definition at line 1142 of file creature.cpp.
{
    return remove_effect( eff_id, convert_bp( bp ) );
}
References convert_bp(), and remove_effect().
Referenced by Character::activate_bionic(), iuse::anticonvulsant(), iuse::antifungal(), iuse::antiparasitic(), monexamine::attach_or_remove_saddle(), iexamine::autodoc(), mattack::check_money_left(), clear_effects(), iuse::contacts(), vehicle::damage_direct(), monster::die(), npc::die(), game::disable_robot(), Character::dismount(), Character::drench(), iuse::eyedrops(), monster::find_dragged_foe(), activity_handlers::find_mount_do_turn(), heal_actor::finish_using(), Character::forced_dismount(), iuse::fungicide(), give_aid_to(), game::handle_action(), Character::hardcoded_effects(), iuse::inhaler(), Character::mend(), activity_handlers::milk_finish(), Character::mount_creature(), monster::move(), Character::move_effects(), monster::move_effects(), monster::move_to(), npc::move_to(), Character::mutate(), npc::npc_dismount(), mattack::nurse_check_up(), monster::nursebot_operate(), monster::on_damage_of_type(), npc::on_load(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), iuse::oxygen_bottle(), game::place_player(), game::place_player_overmap(), monster::plan(), turret_data::post_fire(), Character::process_bionic(), process_effects(), Character::process_effects_internal(), Character::regen(), monexamine::remove_armor(), monexamine::remove_bag_from(), remove_effect(), monexamine::remove_harness(), monexamine::remove_leash(), Character::reset_stats(), Character::restore_scent(), mattack::resurrect(), talk_effect_fun_t::set_remove_effect(), activity_handlers::shear_finish(), monexamine::stop_leading(), monexamine::swap(), avatar_action::swim(), teleport::teleport(), iuse::thorazine(), iuse::towel_common(), try_remove_grab(), monexamine::untie_pet(), Character::update_bodytemp(), Character::update_vitamins(), vehicle::use_harness(), Character::vomit(), wait(), avatar::wake_up(), Character::wake_up(), and talk_function::wake_up().
remove_effect() [2/2]
bool Creature::remove_effect (const efftype_id & eff_id, const bodypart_str_id & bp) virtual
Definition at line 1146 of file creature.cpp.
{
    if( !has_effect( eff_id, bp ) ) {
        //Effect doesn't exist, so do nothing
        return false;
    }
    const effect_type &type = eff_id.obj();
    Character *ch = as_character();
    if( ch != nullptr ) {
        if( is_player() ) {
            if( !type.get_remove_message().empty() ) {
                add_msg( type.lose_game_message_type(), _( type.get_remove_message() ) );
            }
        }
        g->events().send<event_type::character_loses_effect>( ch->getID(), eff_id );
    }
    // num_bp means remove all of a given effect id
    if( !bp ) {
        for( auto &it : ( *effects )[eff_id] ) {
            auto &e = it.second;
            if( !e.is_removed() ) {
                on_effect_int_change( e.get_id(), 0, e.get_bp() );
                e.set_removed();
            }
        }
    } else {
        effect &e = get_effect( eff_id, bp->token );
        on_effect_int_change( e.get_id(), 0, e.get_bp() );
        e.set_removed();
    }
    // Sleep is a special case, since it affects max sight range and other effects
    // Must be below the set_removed above or we'll get an infinite loop
    if( ch != nullptr && eff_id == effect_sleep ) {
        ch->wake_up();
    }
    return true;
}
References _, add_msg(), as_character(), character_loses_effect, effect_sleep, effects, g, effect::get_bp(), get_effect(), effect::get_id(), Character::getID(), has_effect(), is_player(), string_id< T >::obj(), on_effect_int_change(), effect::set_removed(), body_part_type::token, type, and Character::wake_up().
remove_value()
void Creature::remove_value (const std::string & key)
Definition at line 1342 of file creature.cpp.
{
    values.erase( key );
}
References values.
Referenced by Character::apply_skill_boost(), Character::burn_fuel(), Character::cancel_activity(), iuse::radiocontrol(), rcdrive(), Character::reset_remote_fuel(), Character::restore_scent(), talk_effect_fun_t::set_remove_var(), game::setremoteveh(), activity_handlers::try_sleep_do_turn(), and Character::update_fuel_storage().
replace_with_npc_name()
std::string Creature::replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
Its purpose is to avoid repeated code and improve source readability / maintainability.
Definition at line 1886 of file creature.cpp.
{
    return replace_all( std::move( input ), "<npcname>", disp_name() );
}
References disp_name(), avatar_action::move(), and replace_all().
Referenced by monster::add_msg_if_npc(), npc::add_msg_if_npc(), monster::add_msg_player_or_npc(), npc::add_msg_player_or_npc(), and popup_player_or_npc().
reset()
void Creature::reset () virtual
Handles stat and bonus reset.
Reimplemented in Character.
Definition at line 121 of file creature.cpp.
{
    reset_bonuses();
    reset_stats();
}
References reset_bonuses(), and reset_stats().
Referenced by Character::reset().
reset_bonuses()
void Creature::reset_bonuses () virtual
Resets the value of all bonus fields to 0.
Reimplemented in Character, and monster.
Definition at line 135 of file creature.cpp.
{
    num_blocks = 1;
    num_dodges = 1;
    num_blocks_bonus = 0;
    num_dodges_bonus = 0;
    armor_bash_bonus = 0;
    armor_cut_bonus = 0;
    armor_bullet_bonus = 0;
    speed_bonus = 0;
    dodge_bonus = 0;
    block_bonus = 0;
    hit_bonus = 0;
}
References armor_bash_bonus, armor_bullet_bonus, armor_cut_bonus, block_bonus, dodge_bonus, hit_bonus, num_blocks, num_blocks_bonus, num_dodges, num_dodges_bonus, and speed_bonus.
Referenced by Creature(), process_turn(), reset(), Character::reset_bonuses(), and monster::reset_bonuses().
reset_hit_range()
void Creature::reset_hit_range () static
Definition at line 1977 of file creature.cpp.
{
    dispersion_for_even_chance_of_good_hit = default_dispersion_for_ecogh;
}
References default_dispersion_for_ecogh, and dispersion_for_even_chance_of_good_hit.
Referenced by DynamicDataLoader::unload_data().
reset_stats()
virtual void Creature::reset_stats () pure virtual
Resets stats, and applies effects in an idempotent manner.
Implemented in Character, and monster.
Referenced by process_turn(), and reset().
resists_effect()
bool Creature::resists_effect (const effect & e) const
Returns true if the creature resists an effect.
Definition at line 1316 of file creature.cpp.
{
    for( auto &i : e.get_resist_effects() ) {
        if( has_effect( i ) ) {
            return true;
        }
    }
    for( auto &i : e.get_resist_traits() ) {
        if( has_trait( i ) ) {
            return true;
        }
    }
    return false;
}
References effect::get_resist_effects(), effect::get_resist_traits(), has_effect(), and has_trait().
Referenced by character_display::disp_info(), eff_fun_fungus(), Character::process_one_effect(), monster::process_one_effect(), Character::recalc_speed_bonus(), and Character::reset_stats().
sees() [1/2]
bool Creature::sees (const Creature & critter) const virtual
The functions check whether this creature can see the target.
The target may either be another creature (critter), or a specific point on the map.
The function that take another creature as input should check visibility of that creature (e.g. not digging, or otherwise invisible). They must than check whether the location of the other monster is visible.
Reimplemented in Character.
Definition at line 203 of file creature.cpp.
{
    // Creatures always see themselves (simplifies drawing).
    if( &critter == this ) {
        return true;
    }
    if( critter.is_hallucination() ) {
        // hallucinations are imaginations of the player character, npcs or monsters don't hallucinate.
        // Invisible hallucinations would be pretty useless (nobody would see them at all), therefor
        // the player will see them always.
        return is_player();
    }
    if( !fov_3d && !debug_mode && posz() != critter.posz() ) {
        return false;
    }
    // This check is ridiculously expensive so defer it to after everything else.
    auto visible = []( const Character * ch ) {
        return ch == nullptr || !ch->is_invisible();
    };
    map &here = get_map();
    const Character *ch = critter.as_character();
    const int wanted_range = rl_dist( pos(), critter.pos() );
    // Can always see adjacent monsters on the same level, unless they're through a vehicle wall.
    // We also bypass lighting for vertically adjacent monsters, but still check for floors.
    if( wanted_range <= 1 && ( posz() == critter.posz() || here.sees( pos(), critter.pos(), 1 ) ) ) {
        if( here.obscured_by_vehicle_rotation( pos(), critter.pos() ) ) {
            return false;
        }
        return visible( ch );
    } else if( ( wanted_range > 1 && critter.digging() ) ||
               ( critter.has_flag( MF_NIGHT_INVISIBILITY ) && here.light_at( critter.pos() ) <= lit_level::LOW ) ||
               ( critter.is_underwater() && !is_underwater() && here.is_divable( critter.pos() ) ) ||
               ( here.has_flag_ter_or_furn( TFLAG_HIDE_PLACE, critter.pos() ) &&
                 !( std::abs( posx() - critter.posx() ) <= 1 && std::abs( posy() - critter.posy() ) <= 1 &&
                    std::abs( posz() - critter.posz() ) <= 1 ) ) ) {
        return false;
    }
    if( ch != nullptr ) {
        if( ch->movement_mode_is( CMM_CROUCH ) ) {
            const int coverage = here.obstacle_coverage( pos(), critter.pos() );
            if( coverage < 30 ) {
                return sees( critter.pos(), critter.is_avatar() ) && visible( ch );
            }
            float size_modifier = 1.0;
            switch( ch->get_size() ) {
                case MS_TINY:
                    size_modifier = 2.0;
                    break;
                case MS_SMALL:
                    size_modifier = 1.4;
                    break;
                case MS_MEDIUM:
                    break;
                case MS_LARGE:
                    size_modifier = 0.6;
                    break;
                case MS_HUGE:
                    size_modifier = 0.15;
                    break;
                default:
                    break;
            }
            const int vision_modifier = 30 - 0.5 * coverage * size_modifier;
            if( vision_modifier > 1 ) {
                return sees( critter.pos(), critter.is_avatar(), vision_modifier ) && visible( ch );
            }
            return false;
        }
    }
    return sees( critter.pos(), critter.is_avatar() ) && visible( ch );
}
References as_character(), CMM_CROUCH, debug_mode, digging(), fov_3d, get_map(), Character::get_size(), has_flag(), map::has_flag_ter_or_furn(), is_avatar(), map::is_divable(), is_hallucination(), is_player(), is_underwater(), map::light_at(), LOW, MF_NIGHT_INVISIBILITY, Character::movement_mode_is(), MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, map::obscured_by_vehicle_rotation(), map::obstacle_coverage(), pos(), posx(), posy(), posz(), rl_dist(), sees(), map::sees(), and TFLAG_HIDE_PLACE.
Referenced by mattack::acid(), ter_furn_transform::add_message(), monster::attack_target(), auto_find_hostile_target(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), leap_actor::call(), gun_actor::call(), vehicle::autodrive_controller::check_drivable(), mattack::copbot(), mattack::darkman(), mattack::dermatik(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::fungus_bristle(), mattack::howl(), mattack::longswipe(), mattack::lunge(), game::mon_info_update(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::plan(), monster::print_info(), mattack::pull_metal_weapon(), mattack::ranged_pull(), monster::rate_target(), mattack::rattle(), mdefense::return_fire(), mattack::science(), mattack::searchlight(), sees(), Character::sees(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::slimespring(), mattack::spit_sap(), mattack::stare(), sting_get_target(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::tentacle(), mattack::thrown_by_judo(), mattack::tindalos_teleport(), monster::will_reach(), within_target_range(), and within_visual_range().
sees() [2/2]
bool Creature::sees (const tripoint & t, bool is_avatar = false, int range_mod = 0) const virtual
Reimplemented in Character.
Definition at line 279 of file creature.cpp.
{
    if( !fov_3d && posz() != t.z ) {
        return false;
    }
    map &here = get_map();
    const int range_cur = sight_range( here.ambient_light_at( t ) );
    const int range_day = sight_range( default_daylight_level() );
    const int range_night = sight_range( 0 );
    const int range_max = std::max( range_day, range_night );
    const int range_min = std::min( range_cur, range_max );
    const int wanted_range = rl_dist( pos(), t );
    if( wanted_range <= range_min ||
        ( wanted_range <= range_max &&
          here.ambient_light_at( t ) > g->natural_light_level( t.z ) ) ) {
        int range = 0;
        if( here.ambient_light_at( t ) > g->natural_light_level( t.z ) ) {
            range = MAX_VIEW_DISTANCE;
        } else {
            range = range_min;
        }
        if( has_effect( effect_no_sight ) ) {
            range = 1;
        }
        if( range_mod > 0 ) {
            range = std::min( range, range_mod );
        }
        if( is_avatar ) {
            // Special case monster -> player visibility, forcing it to be symmetric with player vision.
            const float player_visibility_factor = g->u.visibility() / 100.0f;
            int adj_range = std::floor( range * player_visibility_factor );
            return adj_range >= wanted_range &&
                   here.get_cache_ref( pos().z ).seen_cache[pos().x][pos().y] > LIGHT_TRANSPARENCY_SOLID;
        } else {
            return here.sees( pos(), t, range );
        }
    } else {
        return false;
    }
}
References map::ambient_light_at(), default_daylight_level(), effect_no_sight, fov_3d, g, map::get_cache_ref(), get_map(), has_effect(), is_avatar(), LIGHT_TRANSPARENCY_SOLID, MAX_VIEW_DISTANCE, pos(), posz(), rl_dist(), level_cache::seen_cache, map::sees(), sight_range(), tripoint::x, tripoint::y, and tripoint::z.
select_body_part()
body_part Creature::select_body_part (Creature * source, int hit_roll) const
Definition at line 1833 of file creature.cpp.
{
    int szdif = source->get_size() - get_size();
    add_msg( m_debug, "hit roll = %d", hit_roll );
    add_msg( m_debug, "source size = %d", source->get_size() );
    add_msg( m_debug, "target size = %d", get_size() );
    add_msg( m_debug, "difference = %d", szdif );
    return human_anatomy->select_body_part( szdif, hit_roll )->token;
}
References add_msg(), get_size(), hit_roll(), human_anatomy, m_debug, and anatomy::select_body_part().
Referenced by melee_actor::call(), and deal_melee_hit().
set_all_parts_hp_cur()
void Creature::set_all_parts_hp_cur (int set)
Definition at line 1611 of file creature.cpp.
{
    for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
        elem.second.set_hp_cur( set );
    }
}
References body.
Referenced by debug_menu::character_edit_menu(), iexamine::dimensional_portal(), and spell_effect::pain_split().
set_all_parts_hp_to_max()
void Creature::set_all_parts_hp_to_max ()
Definition at line 1618 of file creature.cpp.
{
    for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
        elem.second.set_hp_to_max();
    }
}
References body.
Referenced by Character::environmental_revert_effect(), and tutorial_game::init().
set_anatomy()
void Creature::set_anatomy (anatomy_id anat)
Definition at line 1528 of file creature.cpp.
{
    creature_anatomy = anat;
}
References creature_anatomy.
Referenced by Character::load(), and monster::monster().
set_armor_bash_bonus()
void Creature::set_armor_bash_bonus (int nbasharm) virtual
Definition at line 1729 of file creature.cpp.
{
    armor_bash_bonus = nbasharm;
}
References armor_bash_bonus.
set_armor_bullet_bonus()
void Creature::set_armor_bullet_bonus (int nbulletarm) virtual
Definition at line 1737 of file creature.cpp.
{
    armor_bullet_bonus = nbulletarm;
}
References armor_bullet_bonus.
set_armor_cut_bonus()
void Creature::set_armor_cut_bonus (int ncutarm) virtual
Definition at line 1733 of file creature.cpp.
{
    armor_cut_bonus = ncutarm;
}
References armor_cut_bonus.
set_block_bonus()
void Creature::set_block_bonus (int nblock) virtual
Definition at line 1755 of file creature.cpp.
{
    block_bonus = nblock;
}
References block_bonus.
set_body()
void Creature::set_body ()
Definition at line 1538 of file creature.cpp.
{
    body.clear();
    for( const bodypart_id &bp : get_anatomy()->get_bodyparts() ) {
        body.emplace( bp.id(), bodypart( bp.id() ) );
    }
}
References body, and get_anatomy().
Referenced by avatar::create(), Character::load(), monster::monster(), character_funcs::normalize(), avatar::randomize(), npc::randomize(), and standard_npc::standard_npc().
set_dodge_bonus()
void Creature::set_dodge_bonus (float ndodge) virtual
Definition at line 1750 of file creature.cpp.
{
    dodge_bonus = ndodge;
}
References dodge_bonus.
set_fake()
void Creature::set_fake (bool fake_value) virtual
Sets a Creature's fake boolean.
Definition at line 981 of file creature.cpp.
{
    fake = fake_value;
}
References fake.
Referenced by vehicle::get_targeting_npc(), make_fake_npc(), gun_actor::shoot(), basecamp::start_clearcut(), and basecamp::start_cut_logs().
set_hit_bonus()
void Creature::set_hit_bonus (float nhit) virtual
Definition at line 1759 of file creature.cpp.
{
    hit_bonus = nhit;
}
References hit_bonus.
set_killer()
void Creature::set_killer (Creature * killer) protected
Definition at line 1437 of file creature.cpp.
{
    // Only the first killer will be stored, calling set_killer again with a different
    // killer would mean it's called on a dead creature and therefore ignored.
    if( killer != nullptr && !killer->is_fake() && this->killer == nullptr ) {
        this->killer = killer;
    }
}
References is_fake(), and killer.
Referenced by monster::apply_damage(), Character::apply_damage(), monster::die(), and Character::die().
set_moves()
void Creature::set_moves (int nmoves)
Definition at line 1418 of file creature.cpp.
{
    moves = nmoves;
}
References moves.
Referenced by activity_on_turn_move_loot(), activity_handlers::build_do_turn(), complete_construction(), activity_handlers::craft_do_turn(), do_aim(), npc::do_player_activity(), fetch_activity(), generic_multi_activity_handler(), Character::hardcoded_effects(), and npc::move().
set_num_blocks_bonus()
void Creature::set_num_blocks_bonus (int nblocks) virtual
Definition at line 1720 of file creature.cpp.
{
    num_blocks_bonus = nblocks;
}
References num_blocks_bonus.
Referenced by ma_buff::apply_character(), and Character::hardcoded_effects().
set_pain()
void Creature::set_pain (int npain) virtual
Reimplemented in Character.
Definition at line 1363 of file creature.cpp.
{
    npain = std::max( npain, 0 );
    if( pain != npain ) {
        pain = npain;
        on_stat_change( "pain", pain );
    }
}
References on_stat_change(), and pain.
Referenced by mod_pain_noresist(), and Character::set_pain().
set_part_healed_total()
void Creature::set_part_healed_total (const bodypart_id & id, int set)
Definition at line 1591 of file creature.cpp.
{
    get_part( id )->set_healed_total( set );
}
References get_part(), and bodypart::set_healed_total().
Referenced by Character::enforce_minimum_healing().
set_part_hp_cur()
void Creature::set_part_hp_cur (const bodypart_id & id, int set)
Definition at line 1581 of file creature.cpp.
{
    get_part( id )->set_hp_cur( set );
}
References get_part(), and bodypart::set_hp_cur().
Referenced by debug_menu::character_edit_menu(), Character::check_needs_extremes(), Character::hardcoded_effects(), Character::load(), and Character::mend().
set_part_hp_max()
void Creature::set_part_hp_max (const bodypart_id & id, int set)
Definition at line 1586 of file creature.cpp.
{
    get_part( id )->set_hp_max( set );
}
References get_part(), and bodypart::set_hp_max().
Referenced by Character::load().
set_speed_base()
void Creature::set_speed_base (int nspeed) virtual
Definition at line 1742 of file creature.cpp.
{
    speed_base = nspeed;
}
References speed_base.
Referenced by blobify(), iuse::can_goo(), iuse::extinguisher(), mattack::formblob(), trapfunc::glow(), trapfunc::goo(), iuse::granade_act(), monster::init_from_item(), monster::monster(), monster::on_load(), monster::poly(), poly_keep_speed(), and mattack::resurrect().
set_speed_bonus()
void Creature::set_speed_bonus (int nspeed) virtual
Definition at line 1746 of file creature.cpp.
{
    speed_bonus = nspeed;
}
References speed_bonus.
Referenced by monster::process_effects_internal(), and Character::recalc_speed_bonus().
set_underwater()
void Creature::set_underwater (bool x) virtual
Reimplemented in Character.
Definition at line 175 of file creature.cpp.
{
    underwater = x;
}
References underwater.
Referenced by monster::move_to(), and Character::set_underwater().
set_value()
void Creature::set_value (const std::string & key, const std::string & value)
Definition at line 1337 of file creature.cpp.
{
    values[ key ] = value;
}
References values.
Referenced by Character::burn_fuel(), can_do_activity_there(), Character::deactivate_bionic(), pickup_activity_actor::do_turn(), Character::find_remote_fuel(), Character::fuel_bionic_with(), game::handle_action(), json_dynamic_line_effect::json_dynamic_line_effect(), player::player(), pickup::query_thief(), iuse::radiocontrol(), rcdrive(), talk_effect_fun_t::set_add_var(), talk_effect_fun_t::set_adjust_var(), game::setremoteveh(), activity_handlers::try_sleep_query(), Character::update_fuel_storage(), and change_scent_iuse::use().
setpos()
virtual void Creature::setpos (const tripoint & pos) pure virtual
Implemented in Character, monster, and npc.
Referenced by auto_find_hostile_target(), map::displace_vehicle(), trapfunc::ledge(), vehicle::part_collision(), Character::perform_technique(), mattack::ranged_pull(), game::swap_critters(), swap_pos(), and teleport::teleport().
sight_range()
virtual int Creature::sight_range (int light_level) const pure virtual
How far the creature sees under the given light.
Places outside this range can
Parameters
light_level See game::light_level.
Implemented in Character, and monster.
Referenced by sees().
size_melee_penalty()
int Creature::size_melee_penalty () const
Definition at line 482 of file creature.cpp.
{
    switch( get_size() ) {
        case MS_TINY:
            return 30;
        case MS_SMALL:
            return 15;
        case MS_MEDIUM:
            return 0;
        case MS_LARGE:
            return -10;
        case MS_HUGE:
            return -20;
        default:
            break;
    }
    debugmsg( "Invalid target size %d", get_size() );
    return 0;
}
References debugmsg, get_size(), MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, and MS_TINY.
Referenced by deal_melee_attack(), and item::effective_dps().
skin_name()
virtual std::string Creature::skin_name () const pure virtual
Implemented in Character, and monster.
Referenced by monster::melee_attack(), and ranged::print_dmg_msg().
speed_rating()
virtual float Creature::speed_rating () const pure virtual
Returns an approximate number of tiles this creature can travel per turn.
Implemented in Character, monster, and npc.
Referenced by npc::enough_time_to_reload().
stability_roll()
virtual float Creature::stability_roll () const pure virtual
Implemented in Character, and monster.
Referenced by mattack::grab_drag().
store()
void Creature::store (JsonOut & jsout) const protected
These two functions are responsible for storing and loading the members of this class to/from json data.
All classes that inherit from this class should implement their own version of these functions. They are not virtual on purpose, as it's not needed. Every implementation of those functions should a) call the same function with the same parameters of the super class and b) store/load their own members, but not members of any sub or super class.
The functions are (on purpose) not part of the json serialize/deserialize system (defined in json.h). The Creature class is incomplete, there won't be any instance of that class alone, but there will be instances of sub classes (e.g. player, monster). Those (complete) classes implement the deserialize/serialize interface of json. That way only one json object per npc/player/monster instance is created (inside of the serialize function). E.g. player::serialize() looks like this: json.start_object();store(json);json.end_object() player::store than stores the members of the player class, and it calls Character::store, which stores the members of the Character class and calls Creature::store, which stores the members of the Creature class. All data goes into the single json object created in player::serialize.
Definition at line 3006 of file savegame_json.cpp.
{
    jsout.member( "moves", moves );
    jsout.member( "pain", pain );
    // killer is not stored, it's temporary anyway, any creature that has a non-null
    // killer is dead (as per definition) and should not be stored.
    // Because JSON requires string keys we need to convert our int keys
    std::unordered_map<std::string, std::unordered_map<std::string, effect>> tmp_map;
    for( auto maps : *effects ) {
        for( const auto &i : maps.second ) {
            if( i.second.is_removed() ) {
                continue;
            }
            std::ostringstream convert;
            convert << i.first->token;
            tmp_map[maps.first.str()][convert.str()] = i.second;
        }
    }
    jsout.member( "effects", tmp_map );
    jsout.member( "values", values );
    jsout.member( "blocks_left", num_blocks );
    jsout.member( "dodges_left", num_dodges );
    jsout.member( "num_blocks_bonus", num_blocks_bonus );
    jsout.member( "num_dodges_bonus", num_dodges_bonus );
    jsout.member( "armor_bash_bonus", armor_bash_bonus );
    jsout.member( "armor_cut_bonus", armor_cut_bonus );
    jsout.member( "armor_bullet_bonus", armor_bullet_bonus );
    jsout.member( "speed", speed_base );
    jsout.member( "speed_bonus", speed_bonus );
    jsout.member( "dodge_bonus", dodge_bonus );
    jsout.member( "block_bonus", block_bonus );
    jsout.member( "hit_bonus", hit_bonus );
    jsout.member( "underwater", underwater );
    jsout.member( "body", body );
    // fake is not stored, it's temporary anyway, only used to fire with a gun.
}
References item::convert(), JsonOut::member(), and pain.
Referenced by Character::store(), and monster::store().
symbol()
virtual const std::string & Creature::symbol () const pure virtual
Implemented in Character, and monster.
Referenced by draw().
symbol_color()
virtual nc_color Creature::symbol_color () const pure virtual
Implemented in Character, and monster.
Referenced by draw().
uncanny_dodge()
virtual bool Creature::uncanny_dodge () inline virtual
Handles the uncanny dodge bionic and effects, returns true if the creature successfully dodges.
Reimplemented in Character.
Definition at line 490 of file creature.h.
{
            return false;
        }
Referenced by mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), mattack::dermatik(), mattack::evolve_kill_strike(), mattack::flame(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::growplants(), mattack::impale(), mattack::longswipe(), mattack::lunge(), mattack::ranged_pull(), mattack::smash(), sting_shoot(), mattack::stretch_bite(), mattack::taze(), mattack::tentacle(), and mattack::vine().
weight_capacity()
units::mass Creature::weight_capacity () const virtual
Reimplemented in Character, and monster.
Definition at line 1780 of file creature.cpp.
{
    units::mass base_carry = 13_kilogram;
    switch( get_size() ) {
        case MS_TINY:
            base_carry /= 4;
            break;
        case MS_SMALL:
            base_carry /= 2;
            break;
        case MS_MEDIUM:
        default:
            break;
        case MS_LARGE:
            base_carry *= 2;
            break;
        case MS_HUGE:
            base_carry *= 4;
            break;
    }
    return base_carry;
}
References get_size(), MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, and MS_TINY.
Referenced by Character::weight_capacity().
Member Data Documentation
armor_bash_bonus
int Creature::armor_bash_bonus = 0 protected
Definition at line 824 of file creature.h.
Referenced by get_armor_bash(), Character::get_armor_bash(), monster::get_armor_bash(), get_armor_bash_base(), get_armor_bash_bonus(), reset_bonuses(), and set_armor_bash_bonus().
armor_bullet_bonus
int Creature::armor_bullet_bonus = 0 protected
Definition at line 826 of file creature.h.
Referenced by get_armor_bullet(), Character::get_armor_bullet(), monster::get_armor_bullet(), get_armor_bullet_base(), get_armor_bullet_bonus(), reset_bonuses(), and set_armor_bullet_bonus().
armor_cut_bonus
int Creature::armor_cut_bonus = 0 protected
Definition at line 825 of file creature.h.
Referenced by get_armor_cut(), Character::get_armor_cut(), monster::get_armor_cut(), get_armor_cut_base(), get_armor_cut_bonus(), monster::get_armor_type(), reset_bonuses(), and set_armor_cut_bonus().
block_bonus
int Creature::block_bonus = 0 protected
Definition at line 831 of file creature.h.
Referenced by Character::block_hit(), get_block_bonus(), mod_block_bonus(), reset_bonuses(), and set_block_bonus().
body
std::map<bodypart_str_id, bodypart> Creature::body private
this is the actual body of the creature
Definition at line 498 of file creature.h.
Referenced by get_all_body_parts(), get_body(), get_part(), Character::place_corpse(), set_all_parts_hp_cur(), set_all_parts_hp_to_max(), set_body(), and enzlave_actor::use().
cmat_flameres
const std::set< material_id > Creature::cmat_flameres static
Initial value:
{
    material_id( "stone" ), material_id( "kevlar" ), material_id( "steel" )
}
Definition at line 482 of file creature.h.
Referenced by map::monster_in_field().
cmat_flammable
const std::set< material_id > Creature::cmat_flammable static
Initial value:
{
    material_id( "paper" ), material_id( "powder" ), material_id( "wood" ),
    material_id( "cotton" ), material_id( "wool" )
}
Definition at line 481 of file creature.h.
Referenced by trapfunc::lava(), and map::monster_in_field().
cmat_flesh
const std::set< material_id > Creature::cmat_flesh static
Initial value:
{
    material_id( "flesh" ), material_id( "iflesh" )
}
Definition at line 479 of file creature.h.
Referenced by mattack::evolve_kill_strike(), trapfunc::lava(), and map::monster_in_field().
cmat_fleshnveg
const std::set< material_id > Creature::cmat_fleshnveg static
Initial value:
{
    material_id( "flesh" ),  material_id( "iflesh" ), material_id( "veggy" )
}
Definition at line 480 of file creature.h.
Referenced by map::monster_in_field().
creature_anatomy
anatomy_id Creature::creature_anatomy = anatomy_id("default_anatomy") private
anatomy is the plan of the creature's body
Definition at line 496 of file creature.h.
Referenced by get_anatomy(), and set_anatomy().
dispersion_for_even_chance_of_good_hit
std::vector< int > Creature::dispersion_for_even_chance_of_good_hit = default_dispersion_for_ecogh static
Definition at line 852 of file creature.h.
Referenced by load_hit_range(), range_with_even_chance_of_good_hit(), and reset_hit_range().
dodge_bonus
float Creature::dodge_bonus = 0.0 protected
Definition at line 830 of file creature.h.
Referenced by get_dodge_bonus(), mod_dodge_bonus(), reset_bonuses(), and set_dodge_bonus().
effects
pimpl<effects_map> Creature::effects protected
Definition at line 812 of file creature.h.
Referenced by add_effect(), monster::can_act(), Character::check_and_recover_morale(), clear_effects(), Character::conduct_blood_analysis(), get_all_effects(), get_all_effects_of_type(), get_effect(), monster::get_effect_status(), Character::get_overlay_ids(), has_effect(), has_effect_with_flag(), Character::has_mabuff(), Character::is_quiet(), Character::is_stealthy(), Character::is_throw_immune(), Character::load(), change_scent_iuse::load(), Character::mabuff_armor_bonus(), Character::mabuff_arpen_bonus(), Character::mabuff_attack_cost_mult(), Character::mabuff_attack_cost_penalty(), Character::mabuff_block_bonus(), Character::mabuff_damage_bonus(), Character::mabuff_damage_mult(), Character::mabuff_dodge_bonus(), Character::mabuff_speed_bonus(), Character::mabuff_tohit_bonus(), npc::on_load(), monster::print_info(), process_effects(), Character::process_effects_internal(), monster::process_effects_internal(), Character::recalc_speed_bonus(), remove_effect(), Character::reset_stats(), and change_scent_iuse::use().
facing
FacingDirection Creature::facing = FD_RIGHT
return the direction the creature is facing, for sdl horizontal flip
Definition at line 135 of file creature.h.
Referenced by Character::mount_creature(), monster::move(), avatar_action::move(), npc::move_to(), target_ui::set_cursor_pos(), and npc::vehicle_danger().
fake
bool Creature::fake = false protected
Definition at line 834 of file creature.h.
Referenced by Creature(), is_fake(), and set_fake().
hit_bonus
float Creature::hit_bonus = 0.0 protected
Definition at line 832 of file creature.h.
Referenced by get_hit_bonus(), mod_hit_bonus(), reset_bonuses(), and set_hit_bonus().
killer
Creature* Creature::killer = nullptr protected
Definition at line 804 of file creature.h.
Referenced by Character::apply_damage(), Creature(), npc::die(), get_killer(), and set_killer().
moves
int Creature::moves = 0
Definition at line 574 of file creature.h.
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), target_ui::action_aim(), target_ui::action_aim_and_shoot(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), relic::activate(), npc::activate_item(), activity_on_turn_move_loot(), activity_on_turn_wear(), monexamine::add_armor(), addict_effect(), iuse::adrenaline_injector(), npc::aim(), mattack::antqueen(), iuse::arrow_flammable(), iuse::artifact(), Character::assign_activity(), monexamine::attach_bag_to(), iexamine::autodoc(), iexamine::bars(), monster::bash_at(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), trapfunc::board(), iuse::boltcutters(), mattack::boomer(), mattack::boomer_glow(), mattack::breathe(), Character::burn_move_stamina(), iuse::cable_attach(), leap_actor::call(), trapfunc::caltrops(), trapfunc::caltrops_glass(), iuse::camera(), monster::can_act(), can_fire_turret(), avatar_action::can_fire_weapon(), iuse::capture_monster_act(), cauterize_actor::cauterize_effect(), iexamine::chainfence(), game::chat(), npc::consume_cbm_items(), npc::consume_food(), iuse::contacts(), Character::cough(), Character::crafting_inventory(), Creature(), iexamine::curtains(), salvage_actor::cut_up(), mattack::darkman(), monexamine::deactivate_pet(), debug_menu::debug(), mattack::dermatik(), game::disable_robot(), Character::dispose_item(), npc::dispose_item(), vehicle::do_autodrive(), character_funcs::do_pause(), npc::do_player_activity(), npc::do_pulp(), npc::do_reload(), game::do_turn(), player_activity::do_turn(), autodrive_activity_actor::do_turn(), move_items_activity_actor::do_turn(), mattack::doot(), drink_nectar(), monexamine::dump_items(), Character::eat(), avatar_action::eat_here(), eff_fun_fungus(), iuse::einktabletpc(), mattack::evolve_kill_strike(), game::exam_vehicle(), npc::execute_action(), iuse::extinguisher(), iuse::eyedrops(), fire(), ranged::fire_gun(), mattack::flame(), mattack::flesh_golem(), mattack::flesh_tendril(), iexamine::flower_marloss(), iexamine::flower_poppy(), mattack::formblob(), mattack::frag(), iexamine::fswitch(), mattack::fungus(), iexamine::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_inject(), iexamine::fvat_empty(), iexamine::fvat_full(), mattack::gene_sting(), generic_multi_activity_handler(), get_moves(), give_item_to(), trapfunc::glass(), mattack::grab(), game::grabbed_furn_move(), game::grabbed_veh_move(), grenade_helper(), mattack::grow_vine(), iuse::gun_repair(), computer_session::hack_attempt(), hackveh(), handbrake(), game::handle_action(), iuse::handle_ground_graffiti(), Character::hardcoded_effects(), iexamine::harvest_plant(), mattack::howl(), mattack::impale(), vehicle::interact_with(), game::is_game_over(), iexamine::keg(), monexamine::kill_zslave(), iuse::ladder(), iexamine::ledge(), place_trap_actor::data::load(), change_scent_iuse::load(), aim_activity_actor::load_RAS_weapon(), mattack::longswipe(), mattack::lunge(), spell_effect::mod_moves(), mod_moves(), monster::monster(), map::monster_in_field(), iuse::mop(), monster::move(), avatar_action::move(), npc::move_pause(), monster::move_to(), npc::move_to(), game::moving_vehicle_dismount(), npc::mug_player(), iuse::multicooker(), multicooker_hallu(), npc::npc(), item_location::impl::item_on_map::obtain(), item_location::impl::item_on_vehicle::obtain(), pickup::obtain_and_tokenize_items(), item::on_wield(), open(), iuse::oxygen_bottle(), iuse::pack_item(), mattack::para_sting(), mattack::parrot(), parse_vp_reqs(), iexamine::pay_gas(), game::peek(), Character::perform_technique(), perform_zone_activity_turn(), petfood(), game::phasing_move(), iuse::pheromone(), mattack::photograph(), pick_one_up(), npc::pick_up_item(), player::player(), map::player_in_field(), vehicle::pldrive(), avatar_action::plthrow(), monster::poly(), iexamine::portable_structure(), npc::pretend_fire(), npc::pretend_heal(), game::process_activity(), item::process_litcig(), process_turn(), Character::process_turn(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), monexamine::push(), monster::push_to(), iuse::radiocar(), iuse::radiocontrol(), avatar_action::ramp_move(), npc::randomize(), mattack::ranged_pull(), mattack::rattle(), rcdrive(), activity_handlers::read_do_turn(), avatar_action::reload(), iexamine::reload_furniture(), monexamine::remove_armor(), monexamine::remove_bag_from(), activity_handlers::repair_item_do_turn(), item::reset_cable(), mattack::resurrect(), mattack::rifle(), mattack::riotbot(), iuse::robotcontrol(), iexamine::safe(), mattack::science(), set_moves(), mattack::shockstorm(), gun_actor::shoot(), show_armor_layers_ui(), show_bionics_ui(), mattack::shriek(), mattack::shriek_alert(), sleep(), smash(), mattack::smash(), mattack::spit_sap(), mattack::stare(), activity_handlers::start_fire_do_turn(), game::start_game(), character_funcs::store_in_container(), npc::stow_item(), mattack::stretch_attack(), mattack::stretch_bite(), Character::suffer_from_asthma(), Character::suffer_from_bad_bionics(), Character::suffer_from_chemimbalance(), Character::suffer_without_sleep(), monexamine::swap(), avatar_action::swim(), npc::talk_to_u(), mattack::tankgun(), mattack::taze(), iuse::tazer(), iuse::teleport(), mattack::tentacle(), mattack::tindalos_teleport(), toolweapon_off(), iuse::tow_attach(), iuse::towel_common(), iexamine::tree_hickory(), mattack::triffid_heartbeat(), trapfunc::tripwire(), try_consume(), gun_actor::try_target(), character_funcs::try_wield_contents(), iuse::unfold_generic(), avatar_funcs::unload_item(), aim_activity_actor::unload_RAS_weapon(), iuse::unpack_item(), game::update_stair_monsters(), mattack::upgrade(), iuse_transform::use(), unfold_vehicle_iuse::use(), consume_drug_iuse::use(), place_monster_iuse::use(), change_scent_iuse::use(), firestarter_actor::use(), enzlave_actor::use(), fireweapon_off_actor::use(), manualnoise_actor::use(), heal_actor::use(), sew_advanced_actor::use(), npc::use_painkiller(), iexamine::vending(), game::vertical_move(), mattack::vine(), Character::vomit(), iuse::vortex(), game::walk_move(), iuse::water_purifier(), Character::wear_item(), iuse::weed_cake(), npc::wield(), avatar::wield(), and mattack::zombie_fuse().
num_blocks
int Creature::num_blocks = 0 protected
Definition at line 819 of file creature.h.
Referenced by get_num_blocks(), and reset_bonuses().
num_blocks_bonus
int Creature::num_blocks_bonus = 0 protected
Definition at line 821 of file creature.h.
Referenced by get_num_blocks(), get_num_blocks_bonus(), reset_bonuses(), and set_num_blocks_bonus().
num_dodges
int Creature::num_dodges = 0 protected
Definition at line 820 of file creature.h.
Referenced by get_num_dodges(), get_num_dodges_base(), and reset_bonuses().
num_dodges_bonus
int Creature::num_dodges_bonus = 0 protected
Definition at line 822 of file creature.h.
Referenced by get_num_dodges(), get_num_dodges_bonus(), mod_num_dodges_bonus(), and reset_bonuses().
pain
int Creature::pain = 0 private
Definition at line 892 of file creature.h.
Referenced by Creature(), deal_damage_handle_type(), monster::deal_damage_handle_type(), get_pain(), Character::get_pain_description(), mod_pain_noresist(), Character::process_bionic(), and set_pain().
size_map
const std::map< std::string, m_size > Creature::size_map static
Initial value:
= {
    {"TINY", MS_TINY}, {"SMALL", MS_SMALL}, {"MEDIUM", MS_MEDIUM},
    {"LARGE", MS_LARGE}, {"HUGE", MS_HUGE}
}
Definition at line 82 of file creature.h.
Referenced by iuse::capture_monster_act().
speed_base
int Creature::speed_base = 0 protected
Definition at line 827 of file creature.h.
Referenced by Creature(), get_speed_base(), monster::init_from_item(), and set_speed_base().
speed_bonus
int Creature::speed_bonus = 0 protected
Definition at line 829 of file creature.h.
Referenced by get_speed_bonus(), mod_speed_bonus(), reset_bonuses(), and set_speed_bonus().
underwater
bool Creature::underwater = false private
Definition at line 893 of file creature.h.
Referenced by Creature(), is_underwater(), and set_underwater().
values
std::unordered_map<std::string, std::string> Creature::values protected
Definition at line 814 of file creature.h.
Referenced by get_value(), remove_value(), and set_value().
The documentation for this class was generated from the following files:
src/creature.h
src/creature.cpp
src/ranged.cpp
src/savegame_json.cpp