Cataclysm BN: string_input_popup Class Reference
string_input_popup Class Reference
Shows a window querying the user for input.
#include <string_input_popup.h>
Public Member Functions
string_input_popup ()
~string_input_popup ()
string_input_popup & title (const std::string &value)
The title: short string before the actual input field.
string_input_popup & description (const std::string &value)
Additional help text, shown below the input box.
string_input_popup & identifier (const std::string &value)
An identifier to be used to store / get the input history.
string_input_popup & width (int value)
Width (in console cells) of the input field itself.
string_input_popup & max_length (int value)
Maximal amount of Unicode characters that can be given by the user.
string_input_popup & only_digits (bool value)
If true, any non-digit input cancels the input.
string_input_popup & hist_use_uilist (bool value)
Make any difference only if @identifier is used.
string_input_popup & ignore_custom_actions (const bool value)
If true and the custom input context returns an input action, the action is not handled at all and left to be handled by the caller.
string_input_popup & window (const catacurses::window &w, const point &start, int endx)
Set the window area where to display the input text.
bool canceled () const
Whether the input box was canceled via the ESCAPE key (or similar) If the input was finished via the ENTER key (or similar), this will return false.
bool confirmed () const
Returns true if query was finished via the ENTER key.
bool handled () const
Returns false if the last input was unhandled.
string_input_popup & text (const std::string &value)
Set / get the text that can be modified by the user.
const std::string & text () const
string_input_popup & context (input_context &ctxt)
Set / get the input context that is used to gather user input.
input_context & context () const
string_input_popup & title_color (const nc_color &color)
Set / get the foreground color of the title.
string_input_popup & desc_color (const nc_color &color)
Set / get the foreground color of the description.
string_input_popup & string_color (const nc_color &color)
Set / get the foreground color of the input string.
string_input_popup & cursor_color (const nc_color &color)
Set / get the foreground color of the caret.
string_input_popup & underscore_color (const nc_color &color)
Set / get the foreground color of the dashed line.
void query (bool loop=true, bool draw_only=false)
Draws the input box, waits for input (if loop is true).
int query_int (bool loop=true, bool draw_only=false)
int64_t query_int64_t (bool loop=true, bool draw_only=false)
const std::string & query_string (bool loop=true, bool draw_only=false)
void edit (std::string &value)
Edit values in place.
void edit (long &value)
void edit (int &value)
Public Attributes
std::map< long, std::function< bool()> > callbacks
Private Member Functions
void create_window ()
void create_context ()
void show_history (utf8_wrapper &ret)
void add_to_history (const std::string &value) const
void update_input_history (utf8_wrapper &ret, bool up)
void draw (const utf8_wrapper &ret, const utf8_wrapper &edit, int shift) const
Private Attributes
std::string _title
std::string _text
std::string _description
std::string _identifier
std::string _session_str_entered
nc_color _title_color = c_light_red
nc_color _desc_color = c_green
nc_color _string_color = c_magenta
nc_color _cursor_color = h_light_gray
nc_color _underscore_color = c_light_gray
int _width = 0
int _max_length = -1
bool _only_digits = false
bool _hist_use_uilist = true
bool _ignore_custom_actions = true
int _startx = 0
int _starty = 0
int _endx = 0
int _position = -1
int _hist_str_ind = 0
const size_t _hist_max_size = 100
int w_width = 0
int w_height = 0
std::vector< std::string > descformatted
std::vector< std::string > title_split
int titlesize = 0
bool custom_window = false
catacurses::window w
std::unique_ptr< input_context > ctxt_ptr
input_context * ctxt = nullptr
bool _canceled = false
bool _confirmed = false
bool _handled = false
Detailed Description
Shows a window querying the user for input.
Returns the input that was entered. If the user cancels the input (e.g. by pressing Escape), an empty string is returned. An empty string may also be returned when the user does not enter any text and confirms the input (by pressing ENTER).
Examples:
input = string_input_popup().title("Enter something").query();
// shows the input field in window w at coordinates (10,20) up to (30,20).
input = string_input_popup().window(w, 10, 20, 30).query();
Parameters
title The displayed title, describing what to enter. color_tags can be used.
width Width of the input area where the user input appears.
input The initially display input. The user can change this.
desc An optional text (e.h. help or formatting information) which is displayed above the input. Color tags can be used.
identifier If not empty, this is used to store and retrieve previously entered text. All calls with the same identifier share this history, the history is also stored when saving the game (see uistate).
max_length The maximal length of the text the user can input. More input is simply ignored and the returned string is never longer than this.
only_digits Whether to only allow digits in the string.
Definition at line 47 of file string_input_popup.h.
Constructor & Destructor Documentation
string_input_popup()
string_input_popup::string_input_popup () default
~string_input_popup()
string_input_popup::~string_input_popup () default
Member Function Documentation
add_to_history()
void string_input_popup::add_to_history (const std::string & value) const private
Definition at line 151 of file string_input_popup.cpp.
{
    if( !_identifier.empty() && !value.empty() ) {
        std::vector<std::string> &hist = uistate.gethistory( _identifier );
        if( hist.empty() || hist[hist.size() - 1] != value ) {
            hist.push_back( value );
        }
    }
}
References _identifier, uistatedata::gethistory(), and uistate.
Referenced by query_string().
canceled()
bool string_input_popup::canceled () const inline
Whether the input box was canceled via the ESCAPE key (or similar) If the input was finished via the ENTER key (or similar), this will return false.
Definition at line 257 of file string_input_popup.h.
{
            return _canceled;
        }
References _canceled.
Referenced by overmap_ui::create_note(), edit(), trading_window::get_var_trade(), prompt_disassemble_in_seq(), query_for_template_name(), and basecamp::start_crafting().
confirmed()
bool string_input_popup::confirmed () const inline
Returns true if query was finished via the ENTER key.
Definition at line 263 of file string_input_popup.h.
{
            return _confirmed;
        }
References _confirmed.
Referenced by overmap_ui::create_note().
context() [1/2]
input_context & string_input_popup::context () const inline
Definition at line 198 of file string_input_popup.h.
{
            return *ctxt;
        }
References ctxt.
context() [2/2]
string_input_popup & string_input_popup::context (input_context & ctxt)
Set / get the input context that is used to gather user input.
The class will create its own context if none is set here.
Definition at line 500 of file string_input_popup.cpp.
{
    ctxt_ptr.reset();
    this->ctxt = &ctxt;
    return *this;
}
References ctxt, and ctxt_ptr.
Referenced by input_context::display_menu().
create_context()
void string_input_popup::create_context () private
Definition at line 87 of file string_input_popup.cpp.
{
    ctxt_ptr = std::make_unique<input_context>( "STRING_INPUT" );
    ctxt = ctxt_ptr.get();
    ctxt->register_action( "ANY_INPUT" );
}
References ctxt, ctxt_ptr, and input_context::register_action().
Referenced by query_string().
create_window()
void string_input_popup::create_window () private
Definition at line 31 of file string_input_popup.cpp.
{
    titlesize = utf8_width( remove_color_tags( _title ) ); // Occupied horizontal space
    if( _max_length <= 0 ) {
        _max_length = _width;
    }
    // 2 for border (top and bottom) and 1 for the input text line.
    w_height = 2 + 1;
    // |"w_width = width + titlesize (this text) + 5": _____  |
    w_width = FULL_SCREEN_WIDTH;
    if( _width <= 0 ) {
        _width = std::max( 5, FULL_SCREEN_WIDTH - titlesize - 5 ); // Default if unspecified
    } else {
        _width = std::min( FULL_SCREEN_WIDTH - 20, _width );
        w_width = _width + titlesize + 5;
    }
    title_split = { _title };
    if( w_width > FULL_SCREEN_WIDTH ) {
        // Out of horizontal space- wrap the title
        titlesize = FULL_SCREEN_WIDTH - _width - 5;
        w_width = FULL_SCREEN_WIDTH;
        for( int wraplen = w_width - 2; wraplen >= titlesize; wraplen-- ) {
            title_split = foldstring( _title, wraplen );
            if( utf8_width( title_split.back() ) <= titlesize ) {
                break;
            }
        }
        w_height += static_cast<int>( title_split.size() ) - 1;
    }
    descformatted.clear();
    if( !_description.empty() ) {
        const int twidth = std::min( utf8_width( remove_color_tags( _description ) ), w_width - 4 );
        descformatted = foldstring( _description, twidth );
        w_height += descformatted.size();
    }
    // length of title + border (left) + space
    _startx = titlesize + 2;
    if( _max_length <= 0 ) {
        _max_length = 1024;
    }
    _endx = w_width - 3;
    const int w_y = ( TERMY - w_height ) / 2;
    const int w_x = std::max( ( TERMX - w_width ) / 2, 0 );
    w = catacurses::newwin( w_height, w_width, point( w_x, w_y ) );
    _starty = w_height - 2; // The ____ looks better at the bottom right when the title folds
    custom_window = false;
}
References _description, _endx, _max_length, _startx, _starty, _title, _width, custom_window, descformatted, foldstring(), FULL_SCREEN_WIDTH, catacurses::newwin(), remove_color_tags(), TERMX, TERMY, title_split, titlesize, utf8_width(), w, w_height, and w_width.
Referenced by query_string().
cursor_color()
string_input_popup & string_input_popup::cursor_color (const nc_color & color) inline
Set / get the foreground color of the caret.
Optional, default value is h_light_gray.
Definition at line 229 of file string_input_popup.h.
{
            _cursor_color = color;
            return *this;
        }
References _cursor_color, and color().
desc_color()
string_input_popup & string_input_popup::desc_color (const nc_color & color) inline
Set / get the foreground color of the description.
Optional, default value is c_green.
Definition at line 213 of file string_input_popup.h.
{
            _desc_color = color;
            return *this;
        }
References _desc_color, and color().
Referenced by overmap_ui::create_note(), and select_crafting_recipe().
description()
string_input_popup & string_input_popup::description (const std::string & value) inline
Additional help text, shown below the input box.
It's optional, default is an empty text.
Definition at line 124 of file string_input_popup.h.
{
            _description = value;
            return *this;
        }
References _description.
Referenced by overmap_ui::create_note(), veh_interact::do_install(), trading_window::get_var_trade(), game::list_items(), minesweeper_game::new_level(), prompt_disassemble_in_seq(), query_for_template_name(), overmap_ui::search(), select_crafting_recipe(), set_profession(), set_scenario(), options_manager::cOpt::setNext(), and safemode::show().
draw()
void string_input_popup::draw (const utf8_wrapper & ret, const utf8_wrapper & edit, int shift) const private
Definition at line 205 of file string_input_popup.cpp.
{
    if( !custom_window ) {
        draw_border( w );
        for( size_t i = 0; i < descformatted.size(); ++i ) {
            trim_and_print( w, point( 1, 1 + i ), w_width - 2, _desc_color, descformatted[i] );
        }
        int pos_y = descformatted.size() + 1;
        for( int i = 0; i < static_cast<int>( title_split.size() ) - 1; i++ ) {
            mvwprintz( w, point( i + 1, pos_y++ ), _title_color, title_split[i] );
        }
        right_print( w, pos_y, w_width - titlesize - 1, _title_color, title_split.back() );
    }
    const int scrmax = _endx - _startx;
    // remove the scrolled out of view part from the input string
    const utf8_wrapper ds( ret.substr_display( shift, scrmax ) );
    int start_x_edit = _startx;
    // Clear the line
    mvwprintw( w, point( _startx, _starty ), std::string( std::max( 0, scrmax ), ' ' ) );
    // Print the whole input string in default color
    mvwprintz( w, point( _startx, _starty ), _string_color, "%s", ds.c_str() );
    size_t sx = ds.display_width();
    // Print the cursor in its own color
    if( _position >= 0 && static_cast<size_t>( _position ) < ret.length() ) {
        utf8_wrapper cursor = ret.substr( _position, 1 );
        size_t a = _position;
        while( a > 0 && cursor.display_width() == 0 ) {
            // A combination code point, move back to the earliest
            // non-combination code point
            a--;
            cursor = ret.substr( a, _position - a + 1 );
        }
        const size_t left_over = ret.substr( 0, a ).display_width() - shift;
        mvwprintz( w, point( _startx + left_over, _starty ), _cursor_color, "%s", cursor.c_str() );
        start_x_edit += left_over;
    } else if( _position == _max_length && _max_length > 0 ) {
        mvwprintz( w, point( _startx + sx, _starty ), _cursor_color, " " );
        start_x_edit += sx;
        sx++; // don't override trailing ' '
    } else {
        mvwprintz( w, point( _startx + sx, _starty ), _cursor_color, "_" );
        start_x_edit += sx;
        sx++; // don't override trailing '_'
    }
    if( static_cast<int>( sx ) < scrmax ) {
        // could be scrolled out of view when the cursor is at the start of the input
        size_t l = scrmax - sx;
        if( _max_length > 0 ) {
            if( static_cast<int>( ret.length() ) >= _max_length ) {
                l = 0; // no more input possible!
            } else if( _position == static_cast<int>( ret.length() ) ) {
                // one '_' is already printed, formatted as cursor
                l = std::min<size_t>( l, _max_length - ret.length() - 1 );
            } else {
                l = std::min<size_t>( l, _max_length - ret.length() );
            }
        }
        if( l > 0 ) {
            mvwprintz( w, point( _startx + sx, _starty ), _underscore_color, std::string( l, '_' ) );
        }
    }
    if( !edit.empty() ) {
        mvwprintz( w, point( start_x_edit, _starty ), _cursor_color, "%s", edit.c_str() );
    }
    wnoutrefresh( w );
}
References _cursor_color, _desc_color, _endx, _max_length, _position, _startx, _starty, _string_color, _title_color, _underscore_color, a, utf8_wrapper::c_str(), custom_window, descformatted, utf8_wrapper::display_width(), draw_border(), edit(), catacurses::mvwprintw(), mvwprintz(), cata::hash64_detail::ret, right_print(), sx, title_split, titlesize, trim_and_print(), w, w_width, and catacurses::wnoutrefresh().
Referenced by query_string().
edit() [1/3]
void string_input_popup::edit (int & value)
Definition at line 528 of file string_input_popup.cpp.
{
    only_digits( true );
    text( std::to_string( value ) );
    query();
    if( !canceled() ) {
        value = std::atoi( text().c_str() );
    }
}
References canceled(), only_digits(), query(), text(), and to_string().
edit() [2/3]
void string_input_popup::edit (long & value)
Definition at line 518 of file string_input_popup.cpp.
{
    only_digits( true );
    text( std::to_string( value ) );
    query();
    if( !canceled() ) {
        value = std::atol( text().c_str() );
    }
}
References canceled(), only_digits(), query(), text(), and to_string().
edit() [3/3]
void string_input_popup::edit (std::string & value)
Edit values in place.
This combines: calls to text to set the current value, query to get user input and setting the value back into the parameter object (when the popup was not canceled). Canceling the popup keeps the value unmodified.
Definition at line 507 of file string_input_popup.cpp.
{
    only_digits( false );
    text( value );
    query();
    if( !canceled() ) {
        value = text();
    }
}
References canceled(), only_digits(), query(), and text().
Referenced by veh_interact::do_install(), draw(), trading_window::get_var_trade(), game::list_items(), minesweeper_game::new_level(), prompt_disassemble_in_seq(), loot_options::query_loot(), query_string(), select_crafting_recipe(), set_profession(), set_scenario(), options_manager::cOpt::setNext(), and basecamp::start_crafting().
handled()
bool string_input_popup::handled () const inline
Returns false if the last input was unhandled.
Useful to avoid handling input already handled by the popup itself.
Definition at line 270 of file string_input_popup.h.
{
            return _handled;
        }
References _handled.
hist_use_uilist()
string_input_popup & string_input_popup::hist_use_uilist (bool value) inline
Make any difference only if @identifier is used.
If true, create UiList window with query history, otherwise use arrow keys at string input to move through history. Default is true.
Definition at line 167 of file string_input_popup.h.
{
            _hist_use_uilist = value;
            return *this;
        }
References _hist_use_uilist.
Referenced by select_crafting_recipe().
identifier()
string_input_popup & string_input_popup::identifier (const std::string & value) inline
An identifier to be used to store / get the input history.
If empty (the default), no history will be available, otherwise the history associated with the identifier will be available. If the input is not canceled, the new input is added to the history.
Definition at line 136 of file string_input_popup.h.
{
            _identifier = value;
            return *this;
        }
References _identifier.
Referenced by overmap_ui::create_note(), game::list_items(), loot_options::query_loot(), select_crafting_recipe(), iexamine::sign(), and wait().
ignore_custom_actions()
string_input_popup & string_input_popup::ignore_custom_actions (const bool value) inline
If true and the custom input context returns an input action, the action is not handled at all and left to be handled by the caller.
Otherwise the action is always handled as an input event to the popup. The caller can use handled to check whether the last input is handled.
Definition at line 177 of file string_input_popup.h.
{
            _ignore_custom_actions = value;
            return *this;
        }
References _ignore_custom_actions.
max_length()
string_input_popup & string_input_popup::max_length (int value) inline
Maximal amount of Unicode characters that can be given by the user.
The default is something like 1000.
Definition at line 151 of file string_input_popup.h.
{
            _max_length = value;
            return *this;
        }
References _max_length.
Referenced by game::cleanup_at_end(), input_context::display_menu(), veh_interact::do_install(), game::list_items(), pickup::pick_up(), loot_options::query_loot(), options_manager::cOpt::setNext(), and safemode::show().
only_digits()
string_input_popup & string_input_popup::only_digits (bool value) inline
If true, any non-digit input cancels the input.
Default is false.
Definition at line 158 of file string_input_popup.h.
{
            _only_digits = value;
            return *this;
        }
References _only_digits.
Referenced by debug_menu::debug(), edit(), basecamp::job_assignment_ui(), overmap_ui::map_notes_callback::key(), mill_load_food(), iexamine::pay_gas(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), advanced_inventory::query_charges(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), iexamine::reload_furniture(), vehicle::reload_seeds(), options_manager::show(), safemode::show(), and smoker_load_food().
query()
void string_input_popup::query (bool loop = true, bool draw_only = false)
Draws the input box, waits for input (if loop is true).
Returns
text()
Definition at line 276 of file string_input_popup.cpp.
{
    query_string( loop, draw_only );
}
References query_string().
Referenced by edit().
query_int()
int string_input_popup::query_int (bool loop = true, bool draw_only = false)
Definition at line 281 of file string_input_popup.cpp.
{
    return std::atoi( query_string( loop, draw_only ).c_str() );
}
References query_string().
Referenced by debug_menu::debug(), basecamp::job_assignment_ui(), overmap_ui::map_notes_callback::key(), mill_load_food(), iexamine::pay_gas(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), advanced_inventory::query_charges(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), iexamine::reload_furniture(), vehicle::reload_seeds(), smoker_load_food(), and wait().
query_int64_t()
int64_t string_input_popup::query_int64_t (bool loop = true, bool draw_only = false)
Definition at line 286 of file string_input_popup.cpp.
{
    return std::atoll( query_string( loop, draw_only ).c_str() );
}
References query_string().
query_string()
const std::string & string_input_popup::query_string (bool loop = true, bool draw_only = false)
Definition at line 291 of file string_input_popup.cpp.
{
    if( !custom_window && !w ) {
        create_window();
        _position = -1;
    }
    if( !ctxt ) {
        create_context();
    }
    cata::optional<ime_sentry> sentry;
    if( !draw_only && loop ) {
        sentry.emplace();
    }
    utf8_wrapper ret( _text );
    utf8_wrapper edit( ctxt->get_edittext() );
    if( _position == -1 ) {
        _position = ret.length();
    }
    const int scrmax = _endx - _startx;
    // in output (console) cells, not characters of the string!
    int shift = 0;
    std::unique_ptr<ui_adaptor> ui;
    if( !draw_only && !custom_window ) {
        ui = std::make_unique<ui_adaptor>();
        ui->position_from_window( w );
        ui->on_screen_resize( [this]( ui_adaptor & ui ) {
            create_window();
            ui.position_from_window( w );
        } );
        ui->on_redraw( [&]( const ui_adaptor & ) {
            draw( ret, edit, shift );
        } );
    }
    int ch = 0;
    _canceled = false;
    _confirmed = false;
    do {
        if( _position < 0 ) {
            _position = 0;
        }
        const size_t left_shift = ret.substr( 0, _position ).display_width();
        if( static_cast<int>( left_shift ) < shift ) {
            shift = 0;
        } else if( _position < static_cast<int>( ret.length() ) &&
                   static_cast<int>( left_shift ) + 1 >= shift + scrmax ) {
            // if the cursor is inside the input string, keep one cell right of
            // the cursor visible, because the cursor might be on a multi-cell
            // character.
            shift = left_shift - scrmax + 2;
        } else if( _position == static_cast<int>( ret.length() ) &&
                   static_cast<int>( left_shift ) >= shift + scrmax ) {
            // cursor is behind the end of the input string, keep the
            // trailing '_' visible (always a single cell character)
            shift = left_shift - scrmax + 1;
        } else if( shift < 0 ) {
            shift = 0;
        }
        const size_t xleft_shift = ret.substr_display( 0, shift ).display_width();
        if( static_cast<int>( xleft_shift ) != shift ) {
            // This prevents a multi-cell character from been split, which is not possible
            // instead scroll a cell further to make that character disappear completely
            shift++;
        }
        if( ui ) {
            ui_manager::redraw();
        } else {
            draw( ret, edit, shift );
        }
        if( draw_only ) {
            return _text;
        }
        const std::string action = ctxt->handle_input();
        const input_event ev = ctxt->get_raw_input();
        ch = ev.type == CATA_INPUT_KEYBOARD ? ev.get_first_input() : 0;
        _handled = true;
        if( callbacks[ch] ) {
            if( callbacks[ch]() ) {
                continue;
            }
        }
        if( _ignore_custom_actions && action != "ANY_INPUT" ) {
            _handled = false;
            continue;
        }
        if( ch == KEY_ESCAPE ) {
#if defined(__ANDROID__)
            if( get_option<bool>( "ANDROID_AUTO_KEYBOARD" ) ) {
                SDL_StopTextInput();
            }
#endif
            _text.clear();
            _position = -1;
            _canceled = true;
            return _text;
        } else if( ch == '\n' ) {
            add_to_history( ret.str() );
            _confirmed = true;
            _text = ret.str();
            if( !_hist_use_uilist ) {
                _hist_str_ind = 0;
                _session_str_entered.erase( 0 );
            }
            return _text;
        } else if( ch == KEY_UP ) {
            if( !_identifier.empty() ) {
                if( _hist_use_uilist ) {
                    show_history( ret );
                } else {
                    update_input_history( ret, true );
                }
            } else {
                _handled = false;
            }
        } else if( ch == KEY_DOWN ) {
            if( !_identifier.empty() ) {
                if( !_hist_use_uilist ) {
                    update_input_history( ret, false );
                }
            } else {
                _handled = false;
            }
        } else if( ch == KEY_DOWN || ch == KEY_NPAGE || ch == KEY_PPAGE || ch == KEY_BTAB || ch == 9 ) {
            _handled = false;
        } else if( ch == KEY_RIGHT ) {
            if( _position + 1 <= static_cast<int>( ret.size() ) ) {
                _position++;
            }
        } else if( ch == KEY_LEFT ) {
            if( _position > 0 ) {
                _position--;
            }
        } else if( ch == 0x15 ) {                      // ctrl-u: delete all the things
            _position = 0;
            ret.erase( 0 );
            // Move the cursor back and re-draw it
        } else if( ch == KEY_BACKSPACE ) {
            // but silently drop input if we're at 0, instead of adding '^'
            if( _position > 0 && _position <= static_cast<int>( ret.size() ) ) {
                // TODO: it is safe now since you only input ASCII chars
                _position--;
                ret.erase( _position, 1 );
            }
        } else if( ch == KEY_HOME ) {
            _position = 0;
        } else if( ch == KEY_END ) {
            _position = ret.size();
        } else if( ch == KEY_DC ) {
            if( _position < static_cast<int>( ret.size() ) ) {
                ret.erase( _position, 1 );
            }
        } else if( ch == KEY_F( 2 ) ) {
            std::string tmp = get_input_string_from_file();
            int tmplen = utf8_width( tmp );
            if( tmplen > 0 && ( tmplen + utf8_width( ret ) <= _max_length || _max_length == 0 ) ) {
                ret.append( tmp );
            }
        } else if( !ev.text.empty() && _only_digits && !( isdigit( ev.text[0] ) || ev.text[0] == '-' ) ) {
            // ignore non-digit (and '-' is a digit as well)
        } else if( _max_length > 0 && static_cast<int>( ret.length() ) >= _max_length ) {
            // no further input possible, ignore key
        } else if( !ev.text.empty() ) {
            const utf8_wrapper t( ev.text );
            ret.insert( _position, t );
            _position += t.length();
            edit.erase( 0 );
            ctxt->set_edittext( edit.c_str() );
        } else if( ev.edit_refresh ) {
            const utf8_wrapper t( ev.edit );
            edit.erase( 0 );
            edit.insert( 0, t );
            ctxt->set_edittext( edit.c_str() );
        } else if( ev.edit.empty() ) {
            edit.erase( 0 );
            ctxt->set_edittext( edit.c_str() );
        } else {
            _handled = false;
        }
    } while( loop );
    _text = ret.str();
    return _text;
}
References _canceled, _confirmed, _endx, _handled, _hist_str_ind, _hist_use_uilist, _identifier, _ignore_custom_actions, _max_length, _only_digits, _position, _session_str_entered, _startx, _text, action, add_to_history(), callbacks, CATA_INPUT_KEYBOARD, create_context(), create_window(), ctxt, custom_window, draw(), input_event::edit, edit(), input_event::edit_refresh, cata::optional< T >::emplace(), input_context::get_edittext(), input_event::get_first_input(), get_input_string_from_file(), input_context::get_raw_input(), input_context::handle_input(), KEY_BACKSPACE, KEY_BTAB, KEY_DC, KEY_DOWN, KEY_END, KEY_ESCAPE, KEY_F(), KEY_HOME, KEY_LEFT, KEY_NPAGE, KEY_PPAGE, KEY_RIGHT, KEY_UP, utf8_wrapper::length(), ui_manager::redraw(), cata::hash64_detail::ret, input_context::set_edittext(), show_history(), input_event::text, input_event::type, update_input_history(), utf8_width(), and w.
Referenced by game::cleanup_at_end(), overmap_ui::create_note(), debug_menu::debug(), input_context::display_menu(), veh_interact::do_relabel(), veh_interact::do_rename(), construct::done_vehicle(), wish_item_callback::key(), game::list_items(), pickup::pick_up(), query(), query_for_template_name(), query_int(), query_int64_t(), monexamine::rename_pet(), overmap_ui::search(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), iexamine::sign(), and debug_menu::teleport_overmap().
show_history()
void string_input_popup::show_history (utf8_wrapper & ret) private
Definition at line 94 of file string_input_popup.cpp.
{
    if( _identifier.empty() ) {
        return;
    }
    std::vector<std::string> &hist = uistate.gethistory( _identifier );
    uilist hmenu;
    hmenu.title = _( "d: delete history" );
    hmenu.allow_anykey = true;
    for( size_t h = 0; h < hist.size(); h++ ) {
        hmenu.addentry( h, true, -2, hist[h] );
    }
    if( !ret.empty() && ( hmenu.entries.empty() ||
                          hmenu.entries[hist.size() - 1].txt != ret.str() ) ) {
        hmenu.addentry( hist.size(), true, -2, ret.str() );
    }
    if( !hmenu.entries.empty() ) {
        hmenu.selected = hmenu.entries.size() - 1;
        hmenu.w_height_setup = [&]() -> int {
            // number of lines that make up the menu window: 2*border+entries
            int height = 2 + hmenu.entries.size();
            if( getbegy( w ) < height )
            {
                height = std::max( getbegy( w ), 4 );
            }
            return height;
        };
        hmenu.w_x_setup = [&]( int ) -> int {
            return getbegx( w );
        };
        hmenu.w_y_setup = [&]( const int height ) -> int {
            return std::max( getbegy( w ) - height, 0 );
        };
        bool finished = false;
        do {
            hmenu.query();
            if( hmenu.ret >= 0 && hmenu.entries[hmenu.ret].txt != ret.str() ) {
                ret = hmenu.entries[hmenu.ret].txt;
                if( static_cast<size_t>( hmenu.ret ) < hist.size() ) {
                    hist.erase( hist.begin() + hmenu.ret );
                    hist.push_back( ret.str() );
                }
                _position = ret.size();
                finished = true;
            } else if( hmenu.ret == UILIST_UNBOUND && hmenu.keypress == 'd' ) {
                hist.clear();
                finished = true;
            } else if( hmenu.ret != UILIST_UNBOUND ) {
                finished = true;
            }
        } while( !finished );
    }
}
References _, _identifier, _position, uilist::addentry(), uilist::allow_anykey, uilist::entries, finished, catacurses::getbegx(), catacurses::getbegy(), uistatedata::gethistory(), uilist::keypress, uilist::query(), cata::hash64_detail::ret, uilist::ret, uilist::selected, uilist::title, UILIST_UNBOUND, uistate, w, uilist::w_height_setup, uilist::w_x_setup, and uilist::w_y_setup.
Referenced by query_string().
string_color()
string_input_popup & string_input_popup::string_color (const nc_color & color) inline
Set / get the foreground color of the input string.
Optional, default value is c_magenta.
Definition at line 221 of file string_input_popup.h.
{
            _string_color = color;
            return *this;
        }
References _string_color, and color().
Referenced by overmap_ui::create_note().
text() [1/2]
const std::string & string_input_popup::text () const inline
Definition at line 116 of file string_input_popup.h.
{
            return _text;
        }
References _text.
Referenced by edit().
text() [2/2]
string_input_popup & string_input_popup::text (const std::string & value)
Set / get the text that can be modified by the user.
Note that canceling the query makes this an empty string. It's optional default is an empty string.
Definition at line 538 of file string_input_popup.cpp.
{
    _text = value;
    const auto u8size = utf8_wrapper( _text ).size();
    if( _position < 0 || static_cast<size_t>( _position ) > u8size ) {
        _position = u8size;
    }
    return *this;
}
References _position, _text, and utf8_wrapper::size().
Referenced by overmap_ui::create_note(), debug_menu::debug(), input_context::display_menu(), veh_interact::do_relabel(), overmap_ui::map_notes_callback::key(), game::list_items(), mill_load_food(), iexamine::pay_gas(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), query_for_template_name(), iexamine::reload_furniture(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), and smoker_load_food().
title()
string_input_popup & string_input_popup::title (const std::string & value) inline
The title: short string before the actual input field.
It's optional, default is an empty string.
Definition at line 105 of file string_input_popup.h.
{
            _title = value;
            return *this;
        }
References _title.
Referenced by overmap_ui::create_note(), debug_menu::debug(), veh_interact::do_install(), veh_interact::do_relabel(), veh_interact::do_rename(), construct::done_vehicle(), trading_window::get_var_trade(), basecamp::job_assignment_ui(), wish_item_callback::key(), overmap_ui::map_notes_callback::key(), game::list_items(), mill_load_food(), minesweeper_game::new_level(), iexamine::pay_gas(), pickup::pick_up(), prompt_disassemble_in_seq(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), advanced_inventory::query_charges(), query_for_template_name(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), loot_options::query_loot(), iexamine::reload_furniture(), vehicle::reload_seeds(), monexamine::rename_pet(), overmap_ui::search(), select_crafting_recipe(), set_profession(), set_scenario(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), iexamine::sign(), smoker_load_food(), basecamp::start_crafting(), debug_menu::teleport_overmap(), and wait().
title_color()
string_input_popup & string_input_popup::title_color (const nc_color & color) inline
Set / get the foreground color of the title.
Optional, default value is c_light_red.
Definition at line 205 of file string_input_popup.h.
{
            _title_color = color;
            return *this;
        }
References _title_color, and color().
Referenced by overmap_ui::create_note().
underscore_color()
string_input_popup & string_input_popup::underscore_color (const nc_color & color) inline
Set / get the foreground color of the dashed line.
Optional, default value is c_light_gray.
Definition at line 237 of file string_input_popup.h.
{
            _underscore_color = color;
            return *this;
        }
References _underscore_color, and color().
update_input_history()
void string_input_popup::update_input_history (utf8_wrapper & ret, bool up) private
Definition at line 161 of file string_input_popup.cpp.
{
    if( _identifier.empty() ) {
        return;
    }
    std::vector<std::string> &hist = uistate.gethistory( _identifier );
    if( hist.empty() ) {
        return;
    }
    if( hist.size() >= _hist_max_size ) {
        hist.erase( hist.begin(), hist.begin() + ( hist.size() - _hist_max_size ) );
    }
    if( up ) {
        if( _hist_str_ind >= static_cast<int>( hist.size() ) ) {
            return;
        } else if( _hist_str_ind == 0 ) {
            _session_str_entered = ret.str();
            //avoid showing the same result twice (after reopen filter window without reset)
            if( hist.size() > 1 && _session_str_entered == hist.back() ) {
                _hist_str_ind += 1;
            }
        }
    } else {
        if( _hist_str_ind == 1 ) {
            ret = _session_str_entered;
            _position = ret.length();
            //show initial string entered and 'return'
            _hist_str_ind = 0;
            return;
        } else if( _hist_str_ind == 0 ) {
            return;
        }
    }
    _hist_str_ind += up ? 1 : -1;
    ret = hist[hist.size() - _hist_str_ind];
    _position = ret.length();
}
References _hist_max_size, _hist_str_ind, _identifier, _position, _session_str_entered, uistatedata::gethistory(), cata::hash64_detail::ret, and uistate.
Referenced by query_string().
width()
string_input_popup & string_input_popup::width (int value) inline
Width (in console cells) of the input field itself.
Definition at line 143 of file string_input_popup.h.
{
            _width = value;
            return *this;
        }
References _width.
Referenced by overmap_ui::create_note(), debug_menu::debug(), veh_interact::do_install(), veh_interact::do_relabel(), veh_interact::do_rename(), construct::done_vehicle(), basecamp::job_assignment_ui(), overmap_ui::map_notes_callback::key(), game::list_items(), mill_load_food(), minesweeper_game::new_level(), iexamine::pay_gas(), pickup::pick_up(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), advanced_inventory::query_charges(), query_for_template_name(), loot_options::query_loot(), iexamine::reload_furniture(), vehicle::reload_seeds(), monexamine::rename_pet(), select_crafting_recipe(), set_profession(), set_scenario(), options_manager::cOpt::setNext(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), smoker_load_food(), and debug_menu::teleport_overmap().
window()
string_input_popup & string_input_popup::window (const catacurses::window & w, const point & start, int endx)
Set the window area where to display the input text.
If this is set, the class will not create a separate window and only the editable text will be printed at the given part of the given window. Integer parameters define the area (one line) where the editable text is printed.
This method only has effect before the default window is initialized. After that calls to this method are just ignored.
Definition at line 485 of file string_input_popup.cpp.
{
    if( !custom_window && this->w ) {
        // default window already created
        return *this;
    }
    this->w = w;
    _startx = start.x;
    _starty = start.y;
    _endx = endx;
    custom_window = true;
    return *this;
}
References _endx, _startx, _starty, custom_window, w, point::x, and point::y.
Referenced by game::cleanup_at_end(), and input_context::display_menu().
Member Data Documentation
_canceled
bool string_input_popup::_canceled = false private
Definition at line 86 of file string_input_popup.h.
Referenced by canceled(), and query_string().
_confirmed
bool string_input_popup::_confirmed = false private
Definition at line 87 of file string_input_popup.h.
Referenced by confirmed(), and query_string().
_cursor_color
nc_color string_input_popup::_cursor_color = h_light_gray private
Definition at line 58 of file string_input_popup.h.
Referenced by cursor_color(), and draw().
_desc_color
nc_color string_input_popup::_desc_color = c_green private
Definition at line 56 of file string_input_popup.h.
Referenced by desc_color(), and draw().
_description
std::string string_input_popup::_description private
Definition at line 52 of file string_input_popup.h.
Referenced by create_window(), and description().
_endx
int string_input_popup::_endx = 0 private
Definition at line 67 of file string_input_popup.h.
Referenced by create_window(), draw(), query_string(), and window().
_handled
bool string_input_popup::_handled = false private
Definition at line 88 of file string_input_popup.h.
Referenced by handled(), and query_string().
_hist_max_size
const size_t string_input_popup::_hist_max_size = 100 private
Definition at line 71 of file string_input_popup.h.
Referenced by update_input_history().
_hist_str_ind
int string_input_popup::_hist_str_ind = 0 private
Definition at line 69 of file string_input_popup.h.
Referenced by query_string(), and update_input_history().
_hist_use_uilist
bool string_input_popup::_hist_use_uilist = true private
Definition at line 63 of file string_input_popup.h.
Referenced by hist_use_uilist(), and query_string().
_identifier
std::string string_input_popup::_identifier private
Definition at line 53 of file string_input_popup.h.
Referenced by add_to_history(), identifier(), query_string(), show_history(), and update_input_history().
_ignore_custom_actions
bool string_input_popup::_ignore_custom_actions = true private
Definition at line 64 of file string_input_popup.h.
Referenced by ignore_custom_actions(), and query_string().
_max_length
int string_input_popup::_max_length = -1 private
Definition at line 61 of file string_input_popup.h.
Referenced by create_window(), draw(), max_length(), and query_string().
_only_digits
bool string_input_popup::_only_digits = false private
Definition at line 62 of file string_input_popup.h.
Referenced by only_digits(), and query_string().
_position
int string_input_popup::_position = -1 private
Definition at line 68 of file string_input_popup.h.
Referenced by draw(), query_string(), show_history(), text(), and update_input_history().
_session_str_entered
std::string string_input_popup::_session_str_entered private
Definition at line 54 of file string_input_popup.h.
Referenced by query_string(), and update_input_history().
_startx
int string_input_popup::_startx = 0 private
Definition at line 65 of file string_input_popup.h.
Referenced by create_window(), draw(), query_string(), and window().
_starty
int string_input_popup::_starty = 0 private
Definition at line 66 of file string_input_popup.h.
Referenced by create_window(), draw(), and window().
_string_color
nc_color string_input_popup::_string_color = c_magenta private
Definition at line 57 of file string_input_popup.h.
Referenced by draw(), and string_color().
_text
std::string string_input_popup::_text private
Definition at line 51 of file string_input_popup.h.
Referenced by query_string(), and text().
_title
std::string string_input_popup::_title private
Definition at line 50 of file string_input_popup.h.
Referenced by create_window(), and title().
_title_color
nc_color string_input_popup::_title_color = c_light_red private
Definition at line 55 of file string_input_popup.h.
Referenced by draw(), and title_color().
_underscore_color
nc_color string_input_popup::_underscore_color = c_light_gray private
Definition at line 59 of file string_input_popup.h.
Referenced by draw(), and underscore_color().
_width
int string_input_popup::_width = 0 private
Definition at line 60 of file string_input_popup.h.
Referenced by create_window(), and width().
callbacks
std::map<long, std::function<bool()> > string_input_popup::callbacks
Definition at line 287 of file string_input_popup.h.
Referenced by query_for_template_name(), and query_string().
ctxt
input_context* string_input_popup::ctxt = nullptr private
Definition at line 84 of file string_input_popup.h.
Referenced by context(), create_context(), and query_string().
ctxt_ptr
std::unique_ptr<input_context> string_input_popup::ctxt_ptr private
Definition at line 83 of file string_input_popup.h.
Referenced by context(), and create_context().
custom_window
bool string_input_popup::custom_window = false private
Definition at line 80 of file string_input_popup.h.
Referenced by create_window(), draw(), query_string(), and window().
descformatted
std::vector<std::string> string_input_popup::descformatted private
Definition at line 76 of file string_input_popup.h.
Referenced by create_window(), and draw().
title_split
std::vector<std::string> string_input_popup::title_split private
Definition at line 77 of file string_input_popup.h.
Referenced by create_window(), and draw().
titlesize
int string_input_popup::titlesize = 0 private
Definition at line 78 of file string_input_popup.h.
Referenced by create_window(), and draw().
w
catacurses::window string_input_popup::w private
Definition at line 81 of file string_input_popup.h.
Referenced by create_window(), draw(), query_string(), show_history(), and window().
w_height
int string_input_popup::w_height = 0 private
Definition at line 75 of file string_input_popup.h.
Referenced by create_window().
w_width
int string_input_popup::w_width = 0 private
Definition at line 74 of file string_input_popup.h.
Referenced by create_window(), and draw().
The documentation for this class was generated from the following files:
src/string_input_popup.h
src/string_input_popup.cpp