Cataclysm BN: typed_flag_reader< T > Class Template Reference
typed_flag_reader< T > Class Template Reference
Uses a map (unordered or standard) to convert strings from JSON to some other type (the mapped type of the map: C::mapped_type).
#include <generic_readers.h>
Public Member Functions
typed_flag_reader (const map_t &flag_map, const std::string &flag_type)
T get_next (JsonIn &jin) const
Public Member Functions inherited from generic_typed_reader< typed_flag_reader< T > >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Private Types
using map_t = std::map< std::string, T >
Private Attributes
const map_t & flag_map
const std::string flag_type
Detailed Description
template<typename T>
class typed_flag_reader< T >
Uses a map (unordered or standard) to convert strings from JSON to some other type (the mapped type of the map: C::mapped_type).
It works for all mapped types, not just enums.
One can use this if the member is std::set<some_enum> or some_enum and a map std::map<std::string, some_enum> with all the value enumeration values exists.
The class can be conveniently instantiated for a given map mapping using the helper function make_flag_reader (see below). The flag type (flag_type) is used when the input contains invalid flags (a string that is not contained in the map). It should sound something like "my-enum-type".
Definition at line 385 of file generic_readers.h.
Member Typedef Documentation
map_t
template<typename T > using typed_flag_reader< T >::map_t = std::map<std::string, T> private
Definition at line 388 of file generic_readers.h.
Constructor & Destructor Documentation
typed_flag_reader()
template<typename T > typed_flag_reader< T >::typed_flag_reader (const map_t & flag_map, const std::string & flag_type) inline
Definition at line 395 of file generic_readers.h.
            : flag_map( flag_map )
            , flag_type( flag_type ) {
        }
Member Function Documentation
get_next()
template<typename T > T typed_flag_reader< T >::get_next (JsonIn & jin) const inline
Definition at line 400 of file generic_readers.h.
{
            const std::string flag = jin.get_string();
            const auto iter = flag_map.find( flag );
            if( iter == flag_map.cend() ) {
                jin.seek( jin.tell() );
                jin.error( string_format( "invalid %s: \"%s\"", flag_type, flag ) );
            }
            return iter->second;
        }
References JsonIn::error(), typed_flag_reader< T >::flag_map, typed_flag_reader< T >::flag_type, JsonIn::get_string(), JsonIn::seek(), string_format(), and JsonIn::tell().
Member Data Documentation
flag_map
template<typename T > const map_t& typed_flag_reader< T >::flag_map private
Definition at line 391 of file generic_readers.h.
Referenced by typed_flag_reader< T >::get_next().
flag_type
template<typename T > const std::string typed_flag_reader< T >::flag_type private
Definition at line 392 of file generic_readers.h.
Referenced by typed_flag_reader< T >::get_next().
The documentation for this class was generated from the following file:
src/generic_readers.h