Cataclysm BN: fireweapon_on_actor Class Reference
fireweapon_on_actor Class Reference
Active burning melee weapon.
#include <iuse_actor.h>
Public Member Functions
fireweapon_on_actor (const std::string &type="fireweapon_on")
~fireweapon_on_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string noise_message
std::string voluntary_extinguish_message
std::string charges_extinguish_message
std::string water_extinguish_message
std::string auto_extinguish_message
int noise = 0
int noise_chance = 1
int auto_extinguish_chance = 0
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Active burning melee weapon.
Definition at line 709 of file iuse_actor.h.
Constructor & Destructor Documentation
fireweapon_on_actor()
fireweapon_on_actor::fireweapon_on_actor (const std::string & type = "fireweapon_on") inline
Definition at line 721 of file iuse_actor.h.
: iuse_actor(type) {}
~fireweapon_on_actor()
fireweapon_on_actor::~fireweapon_on_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > fireweapon_on_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2235 of file iuse_actor.cpp.
{
    return std::make_unique<fireweapon_on_actor>( *this );
}
load()
void fireweapon_on_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2221 of file iuse_actor.cpp.
{
    noise_message                   = obj.get_string( "noise_message", "hsss" );
    voluntary_extinguish_message    = obj.get_string( "voluntary_extinguish_message" );
    charges_extinguish_message      = obj.get_string( "charges_extinguish_message" );
    water_extinguish_message        = obj.get_string( "water_extinguish_message" );
    noise                           = obj.get_int( "noise", 0 );
    noise_chance                    = obj.get_int( "noise_chance", 1 );
    auto_extinguish_chance          = obj.get_int( "auto_extinguish_chance", 0 );
    if( auto_extinguish_chance > 0 ) {
        auto_extinguish_message         = obj.get_string( "auto_extinguish_message" );
    }
}
References auto_extinguish_chance, auto_extinguish_message, charges_extinguish_message, JsonObject::get_int(), JsonObject::get_string(), noise, noise_chance, noise_message, voluntary_extinguish_message, and water_extinguish_message.
use()
int fireweapon_on_actor::use (player & p, item & it, bool t, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2240 of file iuse_actor.cpp.
{
    bool extinguish = true;
    if( it.charges == 0 ) {
        p.add_msg_if_player( m_bad, _( charges_extinguish_message ) );
    } else if( p.is_underwater() ) {
        p.add_msg_if_player( m_bad, _( water_extinguish_message ) );
    } else if( auto_extinguish_chance > 0 && one_in( auto_extinguish_chance ) ) {
        p.add_msg_if_player( m_bad, _( auto_extinguish_message ) );
    } else if( !t ) {
        p.add_msg_if_player( _( voluntary_extinguish_message ) );
    } else {
        extinguish = false;
    }
    if( extinguish ) {
        it.deactivate( &p, false );
    } else if( one_in( noise_chance ) ) {
        if( noise > 0 ) {
            sounds::sound( p.pos(), noise, sounds::sound_t::combat, _( noise_message ) );
        } else {
            p.add_msg_if_player( _( noise_message ) );
        }
    }
    return it.type->charges_to_use();
}
References _, player::add_msg_if_player(), auto_extinguish_chance, auto_extinguish_message, item::charges, charges_extinguish_message, itype::charges_to_use(), sounds::combat, item::deactivate(), Creature::is_underwater(), m_bad, noise, noise_chance, noise_message, one_in(), Character::pos(), sounds::sound(), item::type, voluntary_extinguish_message, and water_extinguish_message.
Member Data Documentation
auto_extinguish_chance
int fireweapon_on_actor::auto_extinguish_chance = 0
Definition at line 719 of file iuse_actor.h.
Referenced by load(), and use().
auto_extinguish_message
std::string fireweapon_on_actor::auto_extinguish_message
Definition at line 716 of file iuse_actor.h.
Referenced by load(), and use().
charges_extinguish_message
std::string fireweapon_on_actor::charges_extinguish_message
Definition at line 714 of file iuse_actor.h.
Referenced by load(), and use().
noise
int fireweapon_on_actor::noise = 0
Definition at line 717 of file iuse_actor.h.
Referenced by load(), and use().
noise_chance
int fireweapon_on_actor::noise_chance = 1
Definition at line 718 of file iuse_actor.h.
Referenced by load(), and use().
noise_message
std::string fireweapon_on_actor::noise_message
Definition at line 712 of file iuse_actor.h.
Referenced by load(), and use().
voluntary_extinguish_message
std::string fireweapon_on_actor::voluntary_extinguish_message
Definition at line 713 of file iuse_actor.h.
Referenced by load(), and use().
water_extinguish_message
std::string fireweapon_on_actor::water_extinguish_message
Definition at line 715 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp