Cataclysm BN: it_artifact_tool Class Reference
it_artifact_tool Class Reference
#include <artifact.h>
Public Member Functions
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
it_artifact_tool ()
it_artifact_tool (const JsonObject &jo)
it_artifact_tool (const itype &base)
void create_name (const std::string &type)
void create_name (const std::string &property_name, const std::string &shape_name)
Public Member Functions inherited from itype
itype ()
virtual ~itype ()
int damage_min () const
int damage_max () const
std::string get_item_type_string () const
std::string nname (unsigned int quantity) const
const itype_id & get_id () const
bool count_by_charges () const
int charges_default () const
int charges_to_use () const
int charge_factor () const
int maximum_charges () const
bool can_have_charges () const
int charges_per_volume (const units::volume &vol) const
Number of (charges of) this type of item that fit into the given volume.
bool has_use () const
bool has_flag (const std::string &flag) const
bool has_flag (const flag_str_id &flag) const
const FlagsSetType & get_flags () const
bool can_use (const std::string &iuse_name) const
const use_function * get_use (const std::string &iuse_name) const
int invoke (player &p, item &it, const tripoint &pos) const
int invoke (player &p, item &it, const tripoint &pos, const std::string &iuse_name) const
void tick (player &p, item &it, const tripoint &pos) const
Additional Inherited Members
Public Types inherited from itype
using FlagsSetType = std::set< std::string >
Public Attributes inherited from itype
std::vector< std::pair< itype_id, mod_id > > src
cata::value_ptr< islot_container > container
Slots for various item type properties.
cata::value_ptr< islot_tool > tool
cata::value_ptr< islot_comestible > comestible
cata::value_ptr< islot_brewable > brewable
cata::value_ptr< islot_armor > armor
cata::value_ptr< islot_pet_armor > pet_armor
cata::value_ptr< islot_book > book
cata::value_ptr< islot_mod > mod
cata::value_ptr< islot_engine > engine
cata::value_ptr< islot_wheel > wheel
cata::value_ptr< islot_fuel > fuel
cata::value_ptr< islot_gun > gun
cata::value_ptr< islot_gunmod > gunmod
cata::value_ptr< islot_magazine > magazine
cata::value_ptr< islot_battery > battery
cata::value_ptr< islot_bionic > bionic
cata::value_ptr< islot_ammo > ammo
cata::value_ptr< islot_seed > seed
cata::value_ptr< islot_artifact > artifact
cata::value_ptr< relic > relic_data
cata::value_ptr< islot_milling > milling_data
bool was_loaded = false
itype_id looks_like
itype_id repairs_like
std::string snippet_category
translation description
ascii_art_id picture_id
cata::optional< itype_id > default_container
std::map< quality_id, int > qualities
std::map< std::string, std::string > properties
std::vector< conditional_name > conditional_names
std::vector< material_id > materials
std::map< std::string, use_function > use_methods
Actions an instance can perform (if any) indexed by action type.
use_function drop_action
Action to take BEFORE the item is placed on map.
std::set< emit_id > emits
Fields to emit when item is in active state.
std::set< matec_id > techniques
std::map< skill_id, int > min_skills
int min_str = 0
int min_dex = 0
int min_int = 0
int min_per = 0
phase_id phase = SOLID
explosion_data explosion
bool explode_in_fire = false
bool countdown_destroy = false
Is item destroyed after the countdown action is run?
int countdown_interval = 0
Default countdown interval (if any) for item.
use_function countdown_action
Action to take when countdown expires.
bool rigid = true
std::array< int, NUM_DT > melee
Damage output in melee for zero or more damage types.
damage_instance thrown_damage
Base damage output when thrown.
int m_to_hit = 0
unsigned light_emission = 0
item_category_id category_force
If set via JSON forces item category to this (preventing automatic assignment)
std::string sym
nc_color color = c_white
std::set< itype_id > repair
Damage scale compared to the old float damage value.
std::vector< recipe_id > recipes
What recipes can make this item.
std::set< fault_id > faults
What faults (if any) can occur.
std::map< ammotype, std::set< itype_id > > magazines
Magazine types (if any) for each ammo type that can be used to reload this item.
std::map< ammotype, itype_id > magazine_default
Default magazine for each ammo type that can be used to reload this item.
units::volume magazine_well = 0_ml
Volume above which the magazine starts to protrude from the item and add extra volume.
layer_level layer = layer_level::MAX_CLOTHING_LAYER
float solar_efficiency = 0
Efficiency of solar energy conversion for solarpacks.
FlagsSetType item_tags
units::mass weight = 0_gram
Weight of item (or each stack member)
units::mass integral_weight = -1_gram
Weight difference with the part it replaces for mods.
units::volume volume = 0_ml
Space occupied by items of this type CAUTION: value given is for a default-sized stack.
units::volume integral_volume = -1_ml
Space consumed when integrated as part of another item (defaults to volume) CAUTION: value given is for a default-sized stack.
int stack_size = 0
Number of items per above volume for count_by_charges items.
units::money price = 0_cent
Value before cataclysm.
units::money price_post = -1_cent
Value after cataclysm, dependent upon practical usages.
Static Public Attributes inherited from itype
static constexpr int damage_scale = 1000
Protected Attributes inherited from itype
itype_id id = itype_id::NULL_ID()
translation name = no_translation("none")
unique string identifier for this type
Detailed Description
Definition at line 96 of file artifact.h.
Constructor & Destructor Documentation
it_artifact_tool() [1/3]
it_artifact_tool::it_artifact_tool ()
Definition at line 621 of file artifact.cpp.
{
    tool = cata::make_value<islot_tool>();
    artifact = cata::make_value<islot_artifact>();
    id = item_controller->create_artifact_id();
    price = 0_cent;
    tool->charges_per_use = 1;
    artifact->charge_type = ARTC_NULL;
    artifact->charge_req = ACR_NULL;
    artifact->dream_msg_unmet  = artifact_dream_data[static_cast<int>( ACR_NULL )].msg_unmet;
    artifact->dream_msg_met    = artifact_dream_data[static_cast<int>( ACR_NULL )].msg_met;
    artifact->dream_freq_unmet = artifact_dream_data[static_cast<int>( ACR_NULL )].freq_unmet;
    artifact->dream_freq_met   = artifact_dream_data[static_cast<int>( ACR_NULL )].freq_met;
    use_methods.emplace( "ARTIFACT", use_function( "ARTIFACT", &iuse::artifact ) );
}
References ACR_NULL, ARTC_NULL, itype::artifact, iuse::artifact(), artifact_dream_data, item_controller, itype::price, itype::tool, and itype::use_methods.
it_artifact_tool() [2/3]
it_artifact_tool::it_artifact_tool (const JsonObject & jo)
Definition at line 637 of file artifact.cpp.
{
    tool = cata::make_value<islot_tool>();
    artifact = cata::make_value<islot_artifact>();
    use_methods.emplace( "ARTIFACT", use_function( "ARTIFACT", &iuse::artifact ) );
    deserialize( jo );
}
References itype::artifact, iuse::artifact(), deserialize(), itype::tool, and itype::use_methods.
it_artifact_tool() [3/3]
it_artifact_tool::it_artifact_tool (const itype & base) inline
Definition at line 104 of file artifact.h.
: itype(base) {}
Member Function Documentation
create_name() [1/2]
void it_artifact_tool::create_name (const std::string & property_name, const std::string & shape_name)
Definition at line 665 of file artifact.cpp.
{
    name = no_translation( string_format( pgettext( "artifact name (property, shape)", "%1$s %2$s" ),
                                          property_name, shape_name ) );
}
References itype::name, no_translation(), pgettext(), and string_format().
create_name() [2/2]
void it_artifact_tool::create_name (const std::string & type)
Definition at line 660 of file artifact.cpp.
{
    name = no_translation( artifact_name( type ) );
}
References artifact_name(), itype::name, no_translation(), and type.
Referenced by new_artifact(), and new_natural_artifact().
deserialize()
void it_artifact_tool::deserialize (const JsonObject & jo)
Definition at line 1116 of file artifact.cpp.
{
    jo.read( "id", id, true );
    name = no_translation( jo.get_string( "name" ) );
    description = no_translation( jo.get_string( "description" ) );
    if( jo.has_int( "sym" ) ) {
        sym = std::string( 1, jo.get_int( "sym" ) );
    } else {
        sym = jo.get_string( "sym" );
    }
    jo.read( "color", color );
    assign( jo, "price", price, false, 0_cent );
    // LEGACY: Since it seems artifacts get serialized out to disk, and they're
    // dynamic, we need to allow for them to be read from disk for, oh, I guess
    // quite some time. Loading and saving once will write things out as a JSON
    // array.
    if( jo.has_string( "m1" ) ) {
        materials.push_back( material_id( jo.get_string( "m1" ) ) );
    }
    if( jo.has_string( "m2" ) ) {
        materials.push_back( material_id( jo.get_string( "m2" ) ) );
    }
    // Assumption, perhaps dangerous, that we won't wind up with m1 and m2 and
    // a materials array in our serialized objects at the same time.
    if( jo.has_array( "materials" ) ) {
        for( const std::string id : jo.get_array( "materials" ) ) {
            materials.push_back( material_id( id ) );
        }
    }
    volume = jo.get_int( "volume" ) * units::legacy_volume_factor;
    weight = units::from_gram<std::int64_t>( jo.get_int( "weight" ) );
    melee[DT_BASH] = jo.get_int( "melee_dam" );
    melee[DT_CUT] = jo.get_int( "melee_cut" );
    m_to_hit = jo.get_int( "m_to_hit" );
    item_tags = jo.get_tags( "item_flags" );
    jo.read( "techniques", techniques );
    tool->max_charges = jo.get_int( "max_charges" );
    tool->def_charges = jo.get_int( "def_charges" );
    tool->charges_per_use = jo.get_int( "charges_per_use" );
    tool->turns_per_charge = jo.get_int( "turns_per_charge" );
    // Artifacts in older saves store ammo as string.
    if( jo.has_array( "ammo" ) ) {
        for( const std::string id : jo.get_array( "ammo" ) ) {
            tool->ammo_id.insert( ammotype( id ) );
        }
    } else if( jo.has_string( "ammo" ) ) {
        tool->ammo_id.insert( ammotype( jo.get_string( "ammo" ) ) );
    } else {
        jo.throw_error( "\"ammo\" node is neither array, not string" );
    }
    tool->revert_to.emplace( jo.get_string( "revert_to", "null" ) );
    if( tool->revert_to->is_null() ) {
        tool->revert_to.reset();
    }
    artifact->charge_type = static_cast<art_charge>( jo.get_int( "charge_type" ) );
    // Artifacts in older saves do not have charge_req
    if( jo.has_int( "charge_req" ) ) {
        artifact->charge_req  = static_cast<art_charge_req>( jo.get_int( "charge_req" ) );
    } else {
        artifact->charge_req = ACR_NULL;
    }
    for( const int entry : jo.get_array( "effects_wielded" ) ) {
        artifact->effects_wielded.push_back( static_cast<art_effect_passive>( entry ) );
    }
    for( const int entry : jo.get_array( "effects_activated" ) ) {
        artifact->effects_activated.push_back( static_cast<art_effect_active>( entry ) );
    }
    for( const int entry : jo.get_array( "effects_carried" ) ) {
        artifact->effects_carried.push_back( static_cast<art_effect_passive>( entry ) );
    }
    //Generate any missing dream data (due to e.g. old save)
    if( !jo.has_array( "dream_unmet" ) ) {
        artifact->dream_msg_unmet = artifact_dream_data[static_cast<int>( artifact->charge_req )].msg_unmet;
    } else {
        for( const std::string line : jo.get_array( "dream_unmet" ) ) {
            artifact->dream_msg_unmet.push_back( line );
        }
    }
    if( !jo.has_array( "dream_met" ) ) {
        artifact->dream_msg_met   = artifact_dream_data[static_cast<int>( artifact->charge_req )].msg_met;
    } else {
        for( const std::string line : jo.get_array( "dream_met" ) ) {
            artifact->dream_msg_met.push_back( line );
        }
    }
    if( jo.has_int( "dream_freq_unmet" ) ) {
        artifact->dream_freq_unmet = jo.get_int( "dream_freq_unmet" );
    } else {
        artifact->dream_freq_unmet = artifact_dream_data[static_cast<int>
                                     ( artifact->charge_req )].freq_unmet;
    }
    if( jo.has_int( "dream_freq_met" ) ) {
        artifact->dream_freq_met   = jo.get_int( "dream_freq_met" );
    } else {
        artifact->dream_freq_met   = artifact_dream_data[static_cast<int>( artifact->charge_req )].freq_met;
    }
}
References ACR_NULL, itype::artifact, artifact_dream_data, assign(), itype::color, itype::description, DT_BASH, DT_CUT, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_string(), itype::item_tags, units::legacy_volume_factor, line(), itype::m_to_hit, itype::name, no_translation(), itype::price, JsonObject::read(), itype::sym, itype::techniques, JsonObject::throw_error(), itype::tool, itype::volume, and itype::weight.
Referenced by it_artifact_tool().
serialize()
void it_artifact_tool::serialize (JsonOut & json) const
Definition at line 1311 of file artifact.cpp.
{
    json.start_object();
    json.member( "type", "artifact_tool" );
    // generic data
    json.member( "id", id );
    // Artifact names and descriptions are always constructed using `no_translation`,
    // so `translated()` here only retrieves the underlying string
    json.member( "name", name.translated() );
    json.member( "description", description.translated() );
    json.member( "sym", sym );
    json.member( "color", color );
    json.member( "price", units::to_cent( price ) );
    json.member( "materials" );
    json.start_array();
    for( const material_id &mat : materials ) {
        json.write( mat );
    }
    json.end_array();
    json.member( "volume", volume / units::legacy_volume_factor );
    json.member( "weight", to_gram( weight ) );
    json.member( "melee_dam", melee[DT_BASH] );
    json.member( "melee_cut", melee[DT_CUT] );
    json.member( "m_to_hit", m_to_hit );
    json.member( "item_flags", item_tags );
    json.member( "techniques", techniques );
    // tool data
    json.member( "ammo", tool->ammo_id );
    json.member( "max_charges", tool->max_charges );
    json.member( "def_charges", tool->def_charges );
    json.member( "charges_per_use", tool->charges_per_use );
    json.member( "turns_per_charge", tool->turns_per_charge );
    if( tool->revert_to ) {
        json.member( "revert_to", *tool->revert_to );
    }
    // artifact data
    json.member( "charge_type", artifact->charge_type );
    json.member( "charge_req",  artifact->charge_req );
    serialize_enum_vector_as_int( json, "effects_wielded", artifact->effects_wielded );
    serialize_enum_vector_as_int( json, "effects_activated", artifact->effects_activated );
    serialize_enum_vector_as_int( json, "effects_carried", artifact->effects_carried );
    json.member( "dream_unmet",        artifact->dream_msg_unmet );
    json.member( "dream_met",          artifact->dream_msg_met );
    json.member( "dream_freq_unmet",   artifact->dream_freq_unmet );
    json.member( "dream_freq_met",     artifact->dream_freq_met );
    json.end_object();
}
References itype::artifact, itype::color, itype::description, DT_BASH, DT_CUT, JsonOut::end_array(), JsonOut::end_object(), itype::item_tags, units::legacy_volume_factor, itype::m_to_hit, JsonOut::member(), itype::name, itype::price, serialize_enum_vector_as_int(), JsonOut::start_array(), JsonOut::start_object(), itype::sym, itype::techniques, units::to_cent(), units::to_gram(), itype::tool, translation::translated(), itype::volume, itype::weight, and JsonOut::write().
The documentation for this class was generated from the following files:
src/artifact.h
src/artifact.cpp