Cataclysm BN: mutagen_iv_actor Class Reference
mutagen_iv_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
mutagen_iv_actor ()
~mutagen_iv_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string mutation_category
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1184 of file iuse_actor.h.
Constructor & Destructor Documentation
mutagen_iv_actor()
mutagen_iv_actor::mutagen_iv_actor () inline
Definition at line 1189 of file iuse_actor.h.
: iuse_actor("mutagen_iv") {}
~mutagen_iv_actor()
mutagen_iv_actor::~mutagen_iv_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > mutagen_iv_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4504 of file iuse_actor.cpp.
{
    return std::make_unique<mutagen_iv_actor>( *this );
}
load()
void mutagen_iv_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 4509 of file iuse_actor.cpp.
{
    mutation_category = obj.get_string( "mutation_category", "ANY" );
}
References JsonObject::get_string().
use()
int mutagen_iv_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Strength increases volume of painful shouting when using IV mutagen Intelligence reduces sleep duration when using IV mutagen
Implements iuse_actor.
Definition at line 4514 of file iuse_actor.cpp.
{
    mutagen_attempt checks =
        mutagen_common_checks( p, it, false, mutagen_technique::injected_mutagen );
    if( !checks.allowed ) {
        return checks.charges_used;
    }
    const mutation_category_trait &m_category = mutation_category_trait::get_category(
                mutation_category );
    if( p.has_trait( trait_MUT_JUNKIE ) ) {
        p.add_msg_if_player( m_category.junkie_message() );
    } else {
        p.add_msg_if_player( m_category.iv_message() );
    }
    // try to cross the threshold to be able to get post-threshold mutations this iv.
    test_crossing_threshold( p, m_category );
    // TODO: Remove the "is_player" part, implement NPC screams
    if( p.is_player() && !( p.has_trait( trait_NOPAIN ) ) && m_category.iv_sound ) {
        p.mod_pain( m_category.iv_pain );
        /** @EFFECT_STR increases volume of painful shouting when using IV mutagen */
        sounds::sound( p.pos(), m_category.iv_noise + p.str_cur, sounds::sound_t::alert,
                       m_category.iv_sound_message(), true, m_category.iv_sound_id(), m_category.iv_sound_variant() );
    }
    int mut_count = m_category.iv_min_mutations;
    for( int i = 0; i < m_category.iv_additional_mutations; ++i ) {
        if( !one_in( m_category.iv_additional_mutations_chance ) ) {
            ++mut_count;
        }
    }
    for( int i = 0; i < mut_count; i++ ) {
        p.mutate_category( m_category.id );
        p.mod_pain( m_category.iv_pain  * rng( 1, 5 ) );
    }
    p.mod_stored_kcal( -10 * m_category.iv_hunger * mut_count );
    p.mod_thirst( m_category.iv_thirst * mut_count );
    p.mod_fatigue( m_category.iv_fatigue * mut_count );
    if( m_category.id == "CHIMERA" ) {
        p.add_morale( MORALE_MUTAGEN_CHIMERA, m_category.iv_morale, m_category.iv_morale_max );
    } else if( m_category.id == "ELFA" ) {
        p.add_morale( MORALE_MUTAGEN_ELF, m_category.iv_morale, m_category.iv_morale_max );
    } else if( m_category.iv_morale > 0 ) {
        p.add_morale( MORALE_MUTAGEN_MUTATION, m_category.iv_morale, m_category.iv_morale_max );
    }
    if( m_category.iv_sleep && !one_in( 3 ) ) {
        p.add_msg_if_player( m_bad, m_category.iv_sleep_message() );
        /** @EFFECT_INT reduces sleep duration when using IV mutagen */
        p.fall_asleep( time_duration::from_turns( m_category.iv_sleep_dur - p.int_cur * 5 ) );
    }
    // try crossing again after getting new in-category mutations.
    test_crossing_threshold( p, m_category );
    return it.type->charges_to_use();
}
References Character::add_morale(), player::add_msg_if_player(), sounds::alert, mutagen_attempt::allowed, itype::charges_to_use(), mutagen_attempt::charges_used, Character::fall_asleep(), time_duration::from_turns(), mutation_category_trait::get_category(), Character::has_trait(), mutation_category_trait::id, injected_mutagen, Character::int_cur, player::is_player(), mutation_category_trait::iv_additional_mutations, mutation_category_trait::iv_additional_mutations_chance, mutation_category_trait::iv_fatigue, mutation_category_trait::iv_hunger, mutation_category_trait::iv_message(), mutation_category_trait::iv_min_mutations, mutation_category_trait::iv_morale, mutation_category_trait::iv_morale_max, mutation_category_trait::iv_noise, mutation_category_trait::iv_pain, mutation_category_trait::iv_sleep, mutation_category_trait::iv_sleep_dur, mutation_category_trait::iv_sleep_message(), mutation_category_trait::iv_sound, mutation_category_trait::iv_sound_id(), mutation_category_trait::iv_sound_message(), mutation_category_trait::iv_sound_variant(), mutation_category_trait::iv_thirst, mutation_category_trait::junkie_message(), m_bad, Character::mod_fatigue(), Character::mod_pain(), Character::mod_stored_kcal(), Character::mod_thirst(), MORALE_MUTAGEN_CHIMERA, MORALE_MUTAGEN_ELF, MORALE_MUTAGEN_MUTATION, mutagen_common_checks(), Character::mutate_category(), one_in(), Character::pos(), rng(), sounds::sound(), Character::str_cur, test_crossing_threshold(), trait_MUT_JUNKIE, trait_NOPAIN, and item::type.
Member Data Documentation
mutation_category
std::string mutagen_iv_actor::mutation_category
Definition at line 1187 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp