Cataclysm BN: Creature_tracker Class Reference
Creature_tracker Class Reference
#include <creature_tracker.h>
Classes
class weak_ptr_comparator
Public Member Functions
Creature_tracker ()
~Creature_tracker ()
shared_ptr_fast< monster > find (const tripoint &pos) const
Returns the monster at the given location.
int temporary_id (const monster &critter) const
Returns a temporary id of the given monster (which must exist in the tracker).
shared_ptr_fast< monster > from_temporary_id (int id)
bool add (shared_ptr_fast< monster > critter)
Adds the given monster to the tracker.
size_t size () const
bool update_pos (const monster &critter, const tripoint &new_pos)
Updates the position of the given monster to the given point.
void remove (const monster &critter)
Removes the given monster from the Creature tracker, adjusting other entries as needed.
void clear ()
void rebuild_cache ()
void swap_positions (monster &first, monster &second)
Swaps the positions of two monsters.
bool kill_marked_for_death ()
Kills 0 hp monsters.
void remove_dead ()
Removes dead monsters from.
const std::vector< shared_ptr_fast< monster > > & get_monsters_list () const
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
const decltype(monster_faction_map_) & factions () const
Private Member Functions
void add_to_faction_map (shared_ptr_fast< monster > critter)
void remove_from_location_map (const monster &critter)
Remove the monsters entry in monsters_by_location.
Private Attributes
std::unordered_map< mfaction_id, std::set< weak_ptr_fast< monster >, weak_ptr_comparator > > monster_faction_map_
std::vector< shared_ptr_fast< monster > > removed_
Creatures that get removed via remove are stored here until the end of the turn.
std::vector< shared_ptr_fast< monster > > monsters_list
std::unordered_map< tripoint, shared_ptr_fast< monster > > monsters_by_location
Detailed Description
Definition at line 19 of file creature_tracker.h.
Constructor & Destructor Documentation
Creature_tracker()
Creature_tracker::Creature_tracker () default
~Creature_tracker()
Creature_tracker::~Creature_tracker () default
Member Function Documentation
add()
bool Creature_tracker::add (shared_ptr_fast< monster > critter)
Adds the given monster to the tracker.
critter must not be null. If the operation succeeded, the monster pointer is now managed by this tracker.
Returns
Whether the operation was successful. It may fail if there is already another monster at the location of the new monster.
Definition at line 56 of file creature_tracker.cpp.
{
    assert( critter_ptr );
    monster &critter = *critter_ptr;
    if( critter.type->id.is_null() ) { // Don't want to spawn null monsters o.O
        return false;
    }
    if( critter.type->has_flag( MF_VERMIN ) ) {
        // Don't spawn vermin, they aren't implemented yet
        return false;
    }
    if( const shared_ptr_fast<monster> existing_mon_ptr = find( critter.pos() ) ) {
        // We can spawn stuff on hallucinations, but we need to kill them first
        if( existing_mon_ptr->is_hallucination() ) {
            existing_mon_ptr->die( nullptr );
            // But don't remove - that would change the monster order and could segfault
        } else if( critter.is_hallucination() ) {
            return false;
        } else {
            debugmsg( "there's already a monster at %d,%d,%d", critter.pos().x, critter.pos().y,
                      critter.pos().z );
            return false;
        }
    }
    if( MonsterGroupManager::monster_is_blacklisted( critter.type->id ) ) {
        return false;
    }
    monsters_list.emplace_back( critter_ptr );
    monsters_by_location[critter.pos()] = critter_ptr;
    add_to_faction_map( critter_ptr );
    return true;
}
References add_to_faction_map(), debugmsg, monster::die(), find(), mtype::has_flag(), mtype::id, monster::is_hallucination(), string_id< T >::is_null(), MF_VERMIN, MonsterGroupManager::monster_is_blacklisted(), monsters_by_location, monsters_list, monster::pos(), monster::type, tripoint::x, tripoint::y, and tripoint::z.
Referenced by deserialize().
add_to_faction_map()
void Creature_tracker::add_to_faction_map (shared_ptr_fast< monster > critter) private
Definition at line 94 of file creature_tracker.cpp.
{
    assert( critter_ptr );
    monster &critter = *critter_ptr;
    // Only 1 faction per mon at the moment.
    if( critter.friendly == 0 ) {
        monster_faction_map_[ critter.faction ].insert( critter_ptr );
    } else {
        static const mfaction_str_id playerfaction( "player" );
        monster_faction_map_[ playerfaction ].insert( critter_ptr );
    }
}
References monster::faction, monster::friendly, and monster_faction_map_.
Referenced by add(), and rebuild_cache().
clear()
void Creature_tracker::clear ()
Definition at line 199 of file creature_tracker.cpp.
{
    monsters_list.clear();
    monsters_by_location.clear();
    monster_faction_map_.clear();
    removed_.clear();
}
References monster_faction_map_, monsters_by_location, monsters_list, and removed_.
deserialize()
void Creature_tracker::deserialize (JsonIn & jsin)
Definition at line 1310 of file savegame.cpp.
{
    monsters_list.clear();
    monsters_by_location.clear();
    jsin.start_array();
    while( !jsin.end_array() ) {
        // TODO: would be nice if monster had a constructor using JsonIn or similar, so this could be one statement.
        shared_ptr_fast<monster> mptr = make_shared_fast<monster>();
        jsin.read( *mptr );
        add( mptr );
    }
}
References add(), JsonIn::end_array(), monsters_by_location, monsters_list, JsonIn::read(), and JsonIn::start_array().
factions()
const decltype(monster_faction_map_) & Creature_tracker::factions () const inline
Definition at line 90 of file creature_tracker.h.
{
            return monster_faction_map_;
        }
References monster_faction_map_.
find()
shared_ptr_fast< monster > Creature_tracker::find (const tripoint & pos) const
Returns the monster at the given location.
If there is no monster, it returns a nullptr. Dead monsters are ignored and not returned.
Definition at line 23 of file creature_tracker.cpp.
{
    const auto iter = monsters_by_location.find( pos );
    if( iter != monsters_by_location.end() ) {
        const shared_ptr_fast<monster> &mon_ptr = iter->second;
        if( !mon_ptr->is_dead() ) {
            return mon_ptr;
        }
    }
    return nullptr;
}
References monsters_by_location.
Referenced by add(), and update_pos().
from_temporary_id()
shared_ptr_fast< monster > Creature_tracker::from_temporary_id (int id)
Definition at line 47 of file creature_tracker.cpp.
{
    if( static_cast<size_t>( id ) < monsters_list.size() ) {
        return monsters_list[id];
    } else {
        return nullptr;
    }
}
References base_camps::id, and monsters_list.
get_monsters_list()
const std::vector< shared_ptr_fast< monster > > & Creature_tracker::get_monsters_list () const inline
Definition at line 83 of file creature_tracker.h.
{
            return monsters_list;
        }
References monsters_list.
kill_marked_for_death()
bool Creature_tracker::kill_marked_for_death ()
Kills 0 hp monsters.
Returns if it killed any.
Definition at line 254 of file creature_tracker.cpp.
{
    // Important: `Creature::die` must not be called after creature objects (NPCs, monsters) have
    // been removed, the dying creature could still have a pointer (the killer) to another creature.
    bool monster_is_dead = false;
    // Copy the list so we can iterate the copy safely *and* add new monsters from within monster::die
    // This happens for example with blob monsters (they split into two smaller monsters).
    const auto copy = monsters_list;
    for( const shared_ptr_fast<monster> &mon_ptr : copy ) {
        assert( mon_ptr );
        monster &critter = *mon_ptr;
        if( !critter.is_dead() ) {
            continue;
        }
        dbg( DL::Info ) << string_format( "cleanup_dead: critter %s hp:%d %s",
                                          critter.pos().to_string(), critter.get_hp(), critter.name() );
        critter.die( nullptr );
        monster_is_dead = true;
    }
    return monster_is_dead;
}
References dbg, monster::die(), monster::get_hp(), Info, monster::is_dead(), monsters_list, monster::name(), monster::pos(), string_format(), and tripoint::to_string().
rebuild_cache()
void Creature_tracker::rebuild_cache ()
Definition at line 207 of file creature_tracker.cpp.
{
    monsters_by_location.clear();
    monster_faction_map_.clear();
    for( const shared_ptr_fast<monster> &mon_ptr : monsters_list ) {
        monsters_by_location[mon_ptr->pos()] = mon_ptr;
        add_to_faction_map( mon_ptr );
    }
}
References add_to_faction_map(), monster_faction_map_, monsters_by_location, and monsters_list.
Referenced by update_pos().
remove()
void Creature_tracker::remove (const monster & critter)
Removes the given monster from the Creature tracker, adjusting other entries as needed.
Definition at line 174 of file creature_tracker.cpp.
{
    const auto iter = std::find_if( monsters_list.begin(), monsters_list.end(),
    [&]( const shared_ptr_fast<monster> &ptr ) {
        return ptr.get() == &critter;
    } );
    if( iter == monsters_list.end() ) {
        debugmsg( "Tried to remove invalid monster %s", critter.name() );
        return;
    }
    for( auto &pair : monster_faction_map_ ) {
        const auto fac_iter = pair.second.find( *iter );
        if( fac_iter != pair.second.end() ) {
            // Need to do this manually because the shared pointer containing critter is kept valid
            // within removed_ and so the weak pointer in monster_faction_map_ is also valid.
            pair.second.erase( fac_iter );
            break;
        }
    }
    remove_from_location_map( critter );
    removed_.push_back( *iter );
    monsters_list.erase( iter );
}
References debugmsg, monster_faction_map_, monsters_list, monster::name(), ptr(), remove_from_location_map(), and removed_.
remove_dead()
void Creature_tracker::remove_dead ()
Removes dead monsters from.
Their pointers are invalidated.
Definition at line 278 of file creature_tracker.cpp.
{
    // Can't use game::all_monsters() as it would not contain *dead* monsters.
    for( auto iter = monsters_list.begin(); iter != monsters_list.end(); ) {
        const monster &critter = **iter;
        if( critter.is_dead() ) {
            remove_from_location_map( critter );
            iter = monsters_list.erase( iter );
        } else {
            ++iter;
        }
    }
    removed_.clear();
}
References monster::is_dead(), monsters_list, remove_from_location_map(), and removed_.
remove_from_location_map()
void Creature_tracker::remove_from_location_map (const monster & critter) private
Remove the monsters entry in monsters_by_location.
Definition at line 155 of file creature_tracker.cpp.
{
    const auto pos_iter = monsters_by_location.find( critter.pos() );
    if( pos_iter != monsters_by_location.end() && pos_iter->second.get() == &critter ) {
        monsters_by_location.erase( pos_iter );
        return;
    }
    // When it's not in the map at its current location, it might still be there under,
    // another location, so look for it.
    const auto iter = std::find_if( monsters_by_location.begin(), monsters_by_location.end(),
    [&]( const decltype( monsters_by_location )::value_type & v ) {
        return v.second.get() == &critter;
    } );
    if( iter != monsters_by_location.end() ) {
        monsters_by_location.erase( iter );
    }
}
References monsters_by_location, and monster::pos().
Referenced by remove(), remove_dead(), and update_pos().
serialize()
void Creature_tracker::serialize (JsonOut & jsout) const
Definition at line 1323 of file savegame.cpp.
{
    jsout.start_array();
    for( const auto &monster_ptr : monsters_list ) {
        jsout.write( *monster_ptr );
    }
    jsout.end_array();
}
References JsonOut::end_array(), monsters_list, JsonOut::start_array(), and JsonOut::write().
size()
size_t Creature_tracker::size () const
Definition at line 108 of file creature_tracker.cpp.
{
    return monsters_list.size();
}
References monsters_list.
swap_positions()
void Creature_tracker::swap_positions (monster & first, monster & second)
Swaps the positions of two monsters.
Definition at line 217 of file creature_tracker.cpp.
{
    if( first.pos() == second.pos() ) {
        return;
    }
    // Either of them may be invalid!
    const auto first_iter = monsters_by_location.find( first.pos() );
    const auto second_iter = monsters_by_location.find( second.pos() );
    // implied: first_iter != second_iter
    shared_ptr_fast<monster> first_ptr;
    if( first_iter != monsters_by_location.end() ) {
        first_ptr = first_iter->second;
        monsters_by_location.erase( first_iter );
    }
    shared_ptr_fast<monster> second_ptr;
    if( second_iter != monsters_by_location.end() ) {
        second_ptr = second_iter->second;
        monsters_by_location.erase( second_iter );
    }
    // implied: (first_ptr != second_ptr) or (first_ptr == nullptr && second_ptr == nullptr)
    tripoint temp = second.pos();
    second.spawn( first.pos() );
    first.spawn( temp );
    // If the pointers have been taken out of the list, put them back in.
    if( first_ptr ) {
        monsters_by_location[first.pos()] = first_ptr;
    }
    if( second_ptr ) {
        monsters_by_location[second.pos()] = second_ptr;
    }
}
References monsters_by_location, monster::pos(), second, and monster::spawn().
temporary_id()
int Creature_tracker::temporary_id (const monster & critter) const
Returns a temporary id of the given monster (which must exist in the tracker).
The id is valid until monsters are added or removed from the tracker. The id remains valid through serializing and deserializing. Use from_temporary_id to get the monster pointer back. (The later may return a nullptr if the given id is not valid.)
Definition at line 35 of file creature_tracker.cpp.
{
    const auto iter = std::find_if( monsters_list.begin(), monsters_list.end(),
    [&]( const shared_ptr_fast<monster> &ptr ) {
        return ptr.get() == &critter;
    } );
    if( iter == monsters_list.end() ) {
        return -1;
    }
    return iter - monsters_list.begin();
}
References monsters_list, and ptr().
update_pos()
bool Creature_tracker::update_pos (const monster & critter, const tripoint & new_pos)
Updates the position of the given monster to the given point.
Returns whether the operation was successful.
Definition at line 113 of file creature_tracker.cpp.
{
    if( critter.is_dead() ) {
        // find ignores dead critters anyway, changing their position in the
        // monsters_by_location map is useless.
        remove_from_location_map( critter );
        return true;
    }
    if( const shared_ptr_fast<monster> new_critter_ptr = find( new_pos ) ) {
        auto &othermon = *new_critter_ptr;
        if( othermon.is_hallucination() ) {
            othermon.die( nullptr );
        } else {
            debugmsg( "update_zombie_pos: wanted to move %s to %d,%d,%d, but new location already has %s",
                      critter.disp_name(),
                      new_pos.x, new_pos.y, new_pos.z, othermon.disp_name() );
            return false;
        }
    }
    const auto iter = std::find_if( monsters_list.begin(), monsters_list.end(),
    [&]( const shared_ptr_fast<monster> &ptr ) {
        return ptr.get() == &critter;
    } );
    if( iter != monsters_list.end() ) {
        monsters_by_location.erase( critter.pos() );
        monsters_by_location[new_pos] = *iter;
        return true;
    } else {
        const tripoint &old_pos = critter.pos();
        // We're changing the x/y/z coordinates of a zombie that hasn't been added
        // to the game yet. `add` will update monsters_by_location for us.
        debugmsg( "update_zombie_pos: no %s at %d,%d,%d (moving to %d,%d,%d)",
                  critter.disp_name(),
                  old_pos.x, old_pos.y, old_pos.z, new_pos.x, new_pos.y, new_pos.z );
        // Rebuild cache in case the monster actually IS in the game, just bugged
        rebuild_cache();
        return false;
    }
}
References debugmsg, monster::disp_name(), find(), monster::is_dead(), monsters_by_location, monsters_list, monster::pos(), ptr(), rebuild_cache(), remove_from_location_map(), tripoint::x, tripoint::y, and tripoint::z.
Member Data Documentation
monster_faction_map_
std::unordered_map<mfaction_id, std::set<weak_ptr_fast<monster>, weak_ptr_comparator> > Creature_tracker::monster_faction_map_ private
Definition at line 35 of file creature_tracker.h.
Referenced by add_to_faction_map(), clear(), factions(), rebuild_cache(), and remove().
monsters_by_location
std::unordered_map<tripoint, shared_ptr_fast<monster> > Creature_tracker::monsters_by_location private
Definition at line 96 of file creature_tracker.h.
Referenced by add(), clear(), deserialize(), find(), rebuild_cache(), remove_from_location_map(), swap_positions(), and update_pos().
monsters_list
std::vector<shared_ptr_fast<monster> > Creature_tracker::monsters_list private
Definition at line 95 of file creature_tracker.h.
Referenced by add(), clear(), deserialize(), from_temporary_id(), get_monsters_list(), kill_marked_for_death(), rebuild_cache(), remove(), remove_dead(), serialize(), size(), temporary_id(), and update_pos().
removed_
std::vector<shared_ptr_fast<monster> > Creature_tracker::removed_ private
Creatures that get removed via remove are stored here until the end of the turn.
This keeps the objects valid and they can still be accessed instead of causing UB.
Definition at line 41 of file creature_tracker.h.
Referenced by clear(), remove(), and remove_dead().
The documentation for this class was generated from the following files:
src/creature_tracker.h
src/creature_tracker.cpp
src/savegame.cpp