Cataclysm BN: ofstream_wrapper Class Reference
ofstream_wrapper Class Reference
Wrapper around std::ofstream that handles error checking and throws on errors.
#include <fstream_utils.h>
Public Member Functions
ofstream_wrapper (const std::string &path, cata_ios_mode mode)
~ofstream_wrapper ()
std::ostream & stream ()
operator std::ostream & ()
void close ()
Private Member Functions
void open (cata_ios_mode mode)
Private Attributes
cata_ofstream file_stream
std::string path
std::string temp_path
Detailed Description
Wrapper around std::ofstream that handles error checking and throws on errors.
Use like a normal ofstream: the stream is opened in the constructor and closed via close. Both functions check for success and throw std::exception upon any error (e.g. when opening failed or when the stream is in an error state when being closed). Use stream (or the implicit conversion) to access the output stream and to write to it.
Note
: The stream is closed in the destructor, but no exception is throw from it. To ensure all errors get reported correctly, you should always call close explicitly.
: This uses exclusive I/O.
Definition at line 165 of file fstream_utils.h.
Constructor & Destructor Documentation
ofstream_wrapper()
ofstream_wrapper::ofstream_wrapper (const std::string & path, cata_ios_mode mode)
Definition at line 476 of file cata_utility.cpp.
    : path( path )
{
    open( mode );
}
References open().
~ofstream_wrapper()
ofstream_wrapper::~ofstream_wrapper ()
Definition at line 483 of file cata_utility.cpp.
{
    try {
        close();
    } catch( ... ) {
        // ignored in destructor
    }
}
References close().
Member Function Documentation
close()
void ofstream_wrapper::close ()
Definition at line 599 of file cata_utility.cpp.
{
    if( !file_stream.is_open() ) {
        return;
    }
    file_stream.flush();
    bool failed = file_stream.fail();
    file_stream.close();
    if( failed ) {
        // Remove the incomplete or otherwise faulty file (if possible).
        // Failures from it are ignored as we can't really do anything about them.
        remove_file( temp_path );
        throw std::runtime_error( "writing to file failed" );
    }
    if( !rename_file( temp_path, path ) ) {
        // Leave the temp path, so the user can move it if possible.
        throw std::runtime_error( "moving temporary file \"" + temp_path + "\" failed" );
    }
}
References cata_ofstream::close(), cata_ofstream::fail(), failed, file_stream, cata_ofstream::flush(), cata_ofstream::is_open(), path, remove_file(), rename_file(), and temp_path.
Referenced by write_to_file(), and ~ofstream_wrapper().
open()
void ofstream_wrapper::open (cata_ios_mode mode) private
Definition at line 578 of file cata_utility.cpp.
{
    if( dir_exist( path ) ) {
        throw std::runtime_error( "target path is a directory" );
    }
    // Create a *unique* temporary path. No other running program should
    // use this path. If the file exists, it must be of a *former* program
    // instance and can savely be deleted.
    temp_path = path + "." + get_pid_string() + ".temp";
    if( file_exist( temp_path ) ) {
        remove_file( temp_path );
    }
    file_stream = std::move( cata_ofstream().mode( mode ).open( temp_path ) );
    if( !file_stream.is_open() ) {
        throw std::runtime_error( "opening file failed" );
    }
}
References dir_exist(), file_exist(), file_stream, get_pid_string(), cata_ofstream::is_open(), avatar_action::move(), open(), path, remove_file(), and temp_path.
Referenced by ofstream_wrapper(), and open().
operator std::ostream &()
ofstream_wrapper::operator std::ostream & () inline
Definition at line 181 of file fstream_utils.h.
{
            return *file_stream;
        }
References file_stream.
stream()
std::ostream & ofstream_wrapper::stream () inline
Definition at line 178 of file fstream_utils.h.
{
            return *file_stream;
        }
References file_stream.
Referenced by write_to_file().
Member Data Documentation
file_stream
cata_ofstream ofstream_wrapper::file_stream private
Definition at line 168 of file fstream_utils.h.
Referenced by close(), open(), operator std::ostream &(), and stream().
path
std::string ofstream_wrapper::path private
Definition at line 169 of file fstream_utils.h.
Referenced by close(), and open().
temp_path
std::string ofstream_wrapper::temp_path private
Definition at line 170 of file fstream_utils.h.
Referenced by close(), and open().
The documentation for this class was generated from the following files:
src/fstream_utils.h
src/cata_utility.cpp