Cataclysm BN: vehicle_part_iterator< range_type > Class Template Reference
vehicle_part_iterator< range_type > Class Template Reference
Exposes (multiple) parts of one vehicle as vpart_reference.
#include <vpart_range.h>
Public Member Functions
vehicle_part_iterator (const range_type &r, size_t i)
vehicle_part_iterator (const vehicle_part_iterator &)=default
vehicle_part_iterator & operator= (const vehicle_part_iterator &)=default
const vpart_reference & operator* () const
const vpart_reference * operator-> () const
vehicle_part_iterator & operator++ ()
bool operator== (const vehicle_part_iterator &rhs) const
bool operator!= (const vehicle_part_iterator &rhs) const
Private Member Functions
const range_type & range () const
void skip_to_next_valid (size_t i)
Private Attributes
std::reference_wrapper< const range_type > range_
cata::optional< vpart_reference > vp_
Detailed Description
template<typename range_type>
class vehicle_part_iterator< range_type >
Exposes (multiple) parts of one vehicle as vpart_reference.
Uses an arbitrary range_type to supply
the vehicle reference,
information which parts should be iterated over (and which should be skipped).
Definition at line 25 of file vpart_range.h.
Constructor & Destructor Documentation
vehicle_part_iterator() [1/2]
template<typename range_type > vehicle_part_iterator< range_type >::vehicle_part_iterator (const range_type & r, size_t i) inline
Definition at line 47 of file vpart_range.h.
                                                               : range_( r ) {
            assert( i <= range().part_count() );
            skip_to_next_valid( i );
        }
References vehicle_part_iterator< range_type >::range(), and vehicle_part_iterator< range_type >::skip_to_next_valid().
vehicle_part_iterator() [2/2]
template<typename range_type > vehicle_part_iterator< range_type >::vehicle_part_iterator (const vehicle_part_iterator< range_type > &) default
Member Function Documentation
operator!=()
template<typename range_type > bool vehicle_part_iterator< range_type >::operator!= (const vehicle_part_iterator< range_type > & rhs) const inline
Definition at line 78 of file vpart_range.h.
{
            return !operator==( rhs );
        }
References vehicle_part_iterator< range_type >::operator==().
operator*()
template<typename range_type > const vpart_reference & vehicle_part_iterator< range_type >::operator* () const inline
Definition at line 54 of file vpart_range.h.
{
            assert( vp_ );
            return *vp_;
        }
References vehicle_part_iterator< range_type >::vp_.
operator++()
template<typename range_type > vehicle_part_iterator & vehicle_part_iterator< range_type >::operator++ () inline
Definition at line 63 of file vpart_range.h.
{
            assert( vp_ );
            skip_to_next_valid( vp_->part_index() + 1 );
            return *this;
        }
References vehicle_part_iterator< range_type >::skip_to_next_valid().
operator->()
template<typename range_type > const vpart_reference * vehicle_part_iterator< range_type >::operator-> () const inline
Definition at line 58 of file vpart_range.h.
{
            assert( vp_ );
            return &*vp_;
        }
References vehicle_part_iterator< range_type >::vp_.
operator=()
template<typename range_type > vehicle_part_iterator & vehicle_part_iterator< range_type >::operator= (const vehicle_part_iterator< range_type > &) default
operator==()
template<typename range_type > bool vehicle_part_iterator< range_type >::operator== (const vehicle_part_iterator< range_type > & rhs) const inline
Definition at line 69 of file vpart_range.h.
{
            if( vp_.has_value() != rhs.vp_.has_value() ) {
                return false;
            }
            if( !vp_.has_value() ) {
                return true;
            }
            return &vp_->vehicle() == &rhs.vp_->vehicle() && vp_->part_index() == rhs.vp_->part_index();
        }
References cata::optional< T >::has_value(), and vehicle_part_iterator< range_type >::vp_.
Referenced by vehicle_part_iterator< range_type >::operator!=().
range()
template<typename range_type > const range_type & vehicle_part_iterator< range_type >::range () const inline private
Definition at line 31 of file vpart_range.h.
{
            return range_.get();
        }
Referenced by vehicle_part_iterator< range_type >::skip_to_next_valid(), and vehicle_part_iterator< range_type >::vehicle_part_iterator().
skip_to_next_valid()
template<typename range_type > void vehicle_part_iterator< range_type >::skip_to_next_valid (size_t i) inline private
Definition at line 34 of file vpart_range.h.
{
            while( i < range().part_count() &&
                   !range().matches( i ) ) {
                ++i;
            }
            if( i < range().part_count() ) {
                vp_.emplace( range().vehicle(), i );
            } else {
                vp_.reset();
            }
        }
References cata::optional< T >::emplace(), vehicle_part_iterator< range_type >::range(), cata::optional< T >::reset(), and vehicle.
Referenced by vehicle_part_iterator< range_type >::operator++(), and vehicle_part_iterator< range_type >::vehicle_part_iterator().
Member Data Documentation
range_
template<typename range_type > std::reference_wrapper<const range_type> vehicle_part_iterator< range_type >::range_ private
Definition at line 28 of file vpart_range.h.
vp_
template<typename range_type > cata::optional<vpart_reference> vehicle_part_iterator< range_type >::vp_ private
Definition at line 29 of file vpart_range.h.
Referenced by vehicle_part_iterator< range_type >::operator*(), vehicle_part_iterator< range_type >::operator->(), and vehicle_part_iterator< range_type >::operator==().
The documentation for this class was generated from the following file:
src/vpart_range.h