Cataclysm BN: start_location Class Reference
start_location Class Reference
#include <start_location.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check () const
std::string name () const
int targets_count () const
std::pair< std::string, ot_match_type > random_target () const
const std::set< std::string > & flags () const
tripoint_abs_omt find_player_initial_location () const
Find a suitable start location on the overmap.
void prepare_map (const tripoint_abs_omt &omtstart) const
Initialize the map at players start location using prepare_map.
void place_player (player &u) const
Place the player somewhere in the reality bubble (g->m).
void burn (const tripoint_abs_omt &omtstart, size_t count, int rad) const
Burn random terrain / furniture with FLAMMABLE or FLAMMABLE_ASH tag.
void add_map_extra (const tripoint_abs_omt &omtstart, const std::string &map_extra) const
Adds a map extra, see map_extras.h and map_extras.cpp.
void handle_heli_crash (player &u) const
void surround_with_monsters (const tripoint_abs_omt &omtstart, const mongroup_id &type, float expected_points) const
Adds surround start monsters.
Public Attributes
start_location_id id
bool was_loaded = false
Private Member Functions
void prepare_map (tinymap &m) const
Private Attributes
translation _name
std::vector< std::pair< std::string, ot_match_type > > _omt_types
std::set< std::string > _flags
Detailed Description
Definition at line 21 of file start_location.h.
Member Function Documentation
add_map_extra()
void start_location::add_map_extra (const tripoint_abs_omt & omtstart, const std::string & map_extra) const
Adds a map extra, see map_extras.h and map_extras.cpp.
Look at the namespace MapExtras and class map_extras.
Definition at line 392 of file start_location.cpp.
{
    const tripoint_abs_sm player_location = project_to<coords::sm>( omtstart );
    tinymap m;
    m.load( player_location, false );
    // TODO: fix point types
    MapExtras::apply_function( map_extra, m, player_location.raw() );
    m.save();
}
References MapExtras::apply_function(), map::load(), coords::coord_point< Point, Origin, Scale >::raw(), and map::save().
Referenced by game::start_game().
burn()
void start_location::burn (const tripoint_abs_omt & omtstart, size_t count, int rad) const
Burn random terrain / furniture with FLAMMABLE or FLAMMABLE_ASH tag.
Doors and windows are excluded.
Parameters
omtstart Global overmap terrain coordinates where the player is to be spawned.
rad safe radius area to prevent player spawn next to burning wall.
count number of fire on the map.
Definition at line 366 of file start_location.cpp.
{
    const tripoint_abs_sm player_location = project_to<coords::sm>( omtstart );
    tinymap m;
    m.load( player_location, false );
    m.build_outside_cache( m.get_abs_sub().z );
    const point u( g->u.posx() % HALF_MAPSIZE_X, g->u.posy() % HALF_MAPSIZE_Y );
    std::vector<tripoint> valid;
    for( const tripoint &p : m.points_on_zlevel() ) {
        if( !( m.has_flag_ter( "DOOR", p ) ||
               m.has_flag_ter( "OPENCLOSE_INSIDE", p ) ||
               m.is_outside( p ) ||
               ( p.x >= u.x - rad && p.x <= u.x + rad && p.y >= u.y - rad && p.y <= u.y + rad ) ) ) {
            if( m.has_flag( "FLAMMABLE", p ) || m.has_flag( "FLAMMABLE_ASH", p ) ) {
                valid.push_back( p );
            }
        }
    }
    std::shuffle( valid.begin(), valid.end(), rng_get_engine() );
    for( size_t i = 0; i < std::min( count, valid.size() ); i++ ) {
        m.add_field( valid[i], fd_fire, 3 );
    }
    m.save();
}
References map::add_field(), map::build_outside_cache(), detail::count(), fd_fire, g, map::get_abs_sub(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, map::has_flag(), map::has_flag_ter(), map::is_outside(), map::load(), map::points_on_zlevel(), rng_get_engine(), map::save(), point::x, tripoint::x, point::y, tripoint::y, and tripoint::z.
Referenced by game::start_game().
check()
void start_location::check () const
Definition at line 101 of file start_location.cpp.
{
}
finalize()
void start_location::finalize ()
Definition at line 105 of file start_location.cpp.
{
}
find_player_initial_location()
tripoint_abs_omt start_location::find_player_initial_location () const
Find a suitable start location on the overmap.
Returns
Global, absolute overmap terrain coordinates where the player should spawn. It may return overmap::invalid_tripoint if no suitable starting location could be found in the world.
Definition at line 208 of file start_location.cpp.
{
    // Spiral out from the world origin scanning for a compatible starting location,
    // creating overmaps as necessary.
    const int radius = 3;
    std::vector<point_abs_om> overmaps = closest_points_first( point_abs_om(), radius );
    // Skip overmap (0,0), that's endgame
    overmaps.erase( overmaps.begin() );
    // Shuffle 8 first ones so that we don't always start at (1,0)
    std::shuffle( overmaps.begin(), overmaps.begin() + 7, rng_get_engine() );
    for( const point_abs_om &omp : overmaps ) {
        overmap &omap = overmap_buffer.get( omp );
        const tripoint_om_omt omtstart = omap.find_random_omt( random_target() );
        if( omtstart.raw() != tripoint_min ) {
            return project_combine( omp, omtstart );
        }
    }
    // Should never happen, if it does we messed up.
    popup( _( "Unable to generate a valid starting location %s [%s] in a radius of %d overmaps, please report this failure." ),
           name(), id.str(), radius );
    return overmap::invalid_tripoint;
}
References _, closest_points_first(), overmap::find_random_omt(), overmapbuffer::get(), overmap::invalid_tripoint, name(), overmap_buffer, popup(), coords::project_combine(), random_target(), coords::coord_point< Point, Origin, Scale >::raw(), rng_get_engine(), and tripoint_min.
Referenced by game::start_game().
flags()
const std::set< std::string > & start_location::flags () const
Definition at line 78 of file start_location.cpp.
{
    return _flags;
}
References _flags.
Referenced by place_player(), and prepare_map().
handle_heli_crash()
void start_location::handle_heli_crash (player & u) const
Definition at line 405 of file start_location.cpp.
{
    for( const bodypart_id &bp : u.get_all_body_parts( true ) ) {
        if( bp == bodypart_id( "head" ) || bp == bodypart_id( "torso" ) ) {
            continue;// Skip head + torso for balance reasons.
        }
        const int roll = static_cast<int>( rng( 1, 8 ) );
        switch( roll ) {
            // Damage + Bleed
            case 1:
            case 2:
                u.add_effect( effect_bleed, 6_minutes, bp->token );
            /* fallthrough */
            case 3:
            case 4:
            // Just damage
            case 5: {
                const int maxHp = u.get_hp_max( bp );
                // Body part health will range from 33% to 66% with occasional bleed
                const int dmg = static_cast<int>( rng( maxHp / 3, maxHp * 2 / 3 ) );
                u.apply_damage( nullptr, bp, dmg );
                break;
            }
            // No damage
            default:
                break;
        }
    }
}
References Creature::add_effect(), Character::apply_damage(), effect_bleed, Creature::get_all_body_parts(), Creature::get_hp_max(), and rng().
Referenced by game::start_game().
load()
void start_location::load (const JsonObject & jo, const std::string & src)
Definition at line 83 of file start_location.cpp.
{
    mandatory( jo, was_loaded, "name", _name );
    std::string ter;
    ot_match_type ter_match_type = ot_match_type::type;
    for( const JsonValue entry : jo.get_array( "terrain" ) ) {
        if( entry.test_string() ) {
            ter = entry.get_string();
        } else {
            JsonObject jot = entry.get_object();
            ter = jot.get_string( "om_terrain" );
            ter_match_type = jot.get_enum_value<ot_match_type>( "om_terrain_match_type", ter_match_type );
        }
        _omt_types.emplace_back( ter, ter_match_type );
    }
    optional( jo, was_loaded, "flags", _flags, auto_flags_reader<> {} );
}
References _flags, _name, _omt_types, JsonObject::get_array(), JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), mandatory(), optional(), type, and was_loaded.
name()
std::string start_location::name () const
Definition at line 63 of file start_location.cpp.
{
    return _name.translated();
}
References _name, and translation::translated().
Referenced by find_player_initial_location(), and set_description().
place_player()
void start_location::place_player (player & u) const
Place the player somewhere in the reality bubble (g->m).
Strength allows player to start behind less-bashable furniture and terrain
Definition at line 302 of file start_location.cpp.
{
    // Need the "real" map with it's inside/outside cache and the like.
    map &m = g->m;
    // Start us off somewhere in the center of the map
    u.setx( HALF_MAPSIZE_X );
    u.sety( HALF_MAPSIZE_Y );
    u.setz( g->get_levz() );
    m.invalidate_map_cache( m.get_abs_sub().z );
    m.build_map_cache( m.get_abs_sub().z );
    const bool must_be_inside = flags().count( "ALLOW_OUTSIDE" ) == 0;
    ///\EFFECT_STR allows player to start behind less-bashable furniture and terrain
    // TODO: Allow using items here
    const int bash = u.get_str();
    // Remember biggest found location
    // Sometimes it may be impossible to automatically found an ideal location
    // but the player may be more creative than this algorithm and do away with just "good"
    int best_rate = 0;
    // In which attempt did this area get checked?
    // We can overwrite earlier attempts, but not start in them
    int checked[MAPSIZE_X][MAPSIZE_Y];
    std::fill_n( &checked[0][0], MAPSIZE_X * MAPSIZE_Y, 0 );
    bool found_good_spot = false;
    // Try some random points at start
    int tries = 0;
    const auto check_spot = [&]( const tripoint & pt ) {
        tries++;
        const int rate = rate_location( m, pt, must_be_inside, bash, tries, checked );
        if( best_rate < rate ) {
            best_rate = rate;
            u.setpos( pt );
            if( rate == INT_MAX ) {
                found_good_spot = true;
            }
        }
    };
    while( !found_good_spot && tries < 100 ) {
        tripoint rand_point( HALF_MAPSIZE_X + rng( 0, SEEX * 2 - 1 ),
                             HALF_MAPSIZE_Y + rng( 0, SEEY * 2 - 1 ),
                             u.posz() );
        check_spot( rand_point );
    }
    // If we haven't got a good location by now, screw it and brute force it
    // This only happens in exotic locations (deep of a science lab), but it does happen
    if( !found_good_spot ) {
        tripoint tmp = u.pos();
        int &x = tmp.x;
        int &y = tmp.y;
        for( x = 0; x < MAPSIZE_X; x++ ) {
            for( y = 0; y < MAPSIZE_Y; y++ ) {
                check_spot( tmp );
            }
        }
    }
    if( !found_good_spot ) {
        debugmsg( "Could not find a good starting place for character" );
    }
}
References spell_effect::bash(), map::build_map_cache(), debugmsg, flags(), g, map::get_abs_sub(), Character::get_str(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, map::invalidate_map_cache(), MAPSIZE_X, MAPSIZE_Y, Character::pos(), Character::posz(), rate_location(), rng(), SEEX, SEEY, Character::setpos(), Character::setx(), Character::sety(), Character::setz(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by game::start_game().
prepare_map() [1/2]
void start_location::prepare_map (const tripoint_abs_omt & omtstart) const
Initialize the map at players start location using prepare_map.
Parameters
omtstart Global overmap terrain coordinates where the player is to be spawned.
Definition at line 231 of file start_location.cpp.
{
    // Now prepare the initial map (change terrain etc.)
    const tripoint_abs_sm player_location = project_to<coords::sm>( omtstart );
    tinymap player_start;
    // TODO: fix point types
    player_start.load( player_location.raw(), false );
    prepare_map( player_start );
    player_start.save();
}
References map::load(), prepare_map(), coords::coord_point< Point, Origin, Scale >::raw(), and map::save().
Referenced by prepare_map(), and game::start_game().
prepare_map() [2/2]
void start_location::prepare_map (tinymap & m) const private
Definition at line 197 of file start_location.cpp.
{
    const int z = m.get_abs_sub().z;
    if( flags().count( "BOARDED" ) > 0 ) {
        m.build_outside_cache( z );
        board_up( m, m.points_on_zlevel( z ) );
    } else {
        m.translate( t_window_domestic, t_curtains );
    }
}
References board_up(), map::build_outside_cache(), detail::count(), flags(), map::get_abs_sub(), map::points_on_zlevel(), t_curtains, t_window_domestic, map::translate(), and tripoint::z.
random_target()
std::pair< std::string, ot_match_type > start_location::random_target () const
Definition at line 73 of file start_location.cpp.
{
    return random_entry( _omt_types );
}
References _omt_types, and random_entry().
Referenced by find_player_initial_location().
surround_with_monsters()
void start_location::surround_with_monsters (const tripoint_abs_omt & omtstart, const mongroup_id & type, float expected_points) const
Adds surround start monsters.
Parameters
expected_points Expected value of "monster points" (map tiles times density from map::place_spawns).
Definition at line 447 of file start_location.cpp.
{
    for( const tripoint_abs_omt &p : points_in_radius( omtstart, 1 ) ) {
        if( p != omtstart ) {
            add_monsters( p, type, roll_remainder( expected_points / 8.0f ) );
        }
    }
}
References add_monsters(), points_in_radius(), roll_remainder(), and type.
Referenced by game::start_game().
targets_count()
int start_location::targets_count () const
Definition at line 68 of file start_location.cpp.
{
    return _omt_types.size();
}
References _omt_types.
Referenced by set_description().
Member Data Documentation
_flags
std::set<std::string> start_location::_flags private
Definition at line 75 of file start_location.h.
Referenced by flags(), and load().
_name
translation start_location::_name private
Definition at line 73 of file start_location.h.
Referenced by load(), and name().
_omt_types
std::vector<std::pair<std::string, ot_match_type> > start_location::_omt_types private
Definition at line 74 of file start_location.h.
Referenced by load(), random_target(), and targets_count().
id
start_location_id start_location::id
Definition at line 24 of file start_location.h.
was_loaded
bool start_location::was_loaded = false
Definition at line 25 of file start_location.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/start_location.h
src/start_location.cpp