Cataclysm BN: player_morale Class Reference
player_morale Class Reference
#include <morale.h>
Classes
struct body_part_data
class morale_point
class morale_subtype
struct mutation_data
Public Member Functions
player_morale ()
player_morale (player_morale &&)=default
player_morale (const player_morale &)=default
player_morale & operator= (player_morale &&)=default
player_morale & operator= (const player_morale &)=default
void add (morale_type type, int bonus, int max_bonus=0, const time_duration &duration=6_minutes, const time_duration &decay_start=3_minutes, bool capped=false)
Adds morale to existing or creates one.
void add (morale_type type, int bonus, int max_bonus, const time_duration &duration, const time_duration &decay_start, bool capped, const itype &item_type)
void add (morale_type type, int bonus, int max_bonus, const time_duration &duration, const time_duration &decay_start, bool capped, const efftype_id &effect_type)
void set_permanent (const morale_type &type, int bonus)
Sets the new level for the permanent morale, or creates one.
bool has (const morale_type &type) const
Returns true if any morale point with specified morale exists.
int get (const morale_type &type) const
Returns bonus from specified morale.
void remove (const morale_type &type)
Removes specified morale.
void clear ()
Clears up all morale points.
int get_level () const
Returns overall morale level.
void decay (const time_duration &ticks=1_turns)
Ticks down morale counters and removes them.
void display (int focus_eq, int pain_penalty, int fatigue_cap)
Displays morale screen.
bool consistent_with (const player_morale &morale) const
Returns false whether morale is inconsistent with the argument.
void calculate_percentage ()
calculates the percentage contribution for each morale point
int get_total_positive_value () const
int get_total_negative_value () const
void on_mutation_gain (const trait_id &mid)
void on_mutation_loss (const trait_id &mid)
void on_stat_change (const std::string &stat, int value)
void on_item_wear (const item &it)
void on_item_takeoff (const item &it)
void on_worn_item_transform (const item &old_it, const item &new_it)
void on_worn_item_washed (const item &it)
void on_effect_int_change (const efftype_id &eid, int intensity, const bodypart_str_id &bp=bodypart_str_id::NULL_ID())
void store (JsonOut &jsout) const
void load (const JsonObject &jsin)
Private Types
using mutation_handler = std::function< void(player_morale &)>
Private Member Functions
void add (morale_type type, const morale_subtype &subtype, int bonus, int max_bonus, const time_duration &duration, const time_duration &decay_start, bool capped)
int has (const morale_type &type, const morale_subtype &subtype) const
void remove (const morale_type &type, const morale_subtype &subtype)
void set_permanent_typed (const morale_type &type, int bonus, const morale_subtype &subtype)
morale_mult get_temper_mult () const
void set_prozac (bool new_took_prozac)
void set_prozac_bad (bool new_took_prozac_bad)
void set_stylish (bool new_stylish)
void set_worn (const item &it, bool worn)
void set_mutation (const trait_id &mid, bool active)
bool has_mutation (const trait_id &mid)
void remove_if (const std::function< bool(const morale_point &)> &func)
void remove_expired ()
void invalidate ()
void update_stylish_bonus ()
void update_squeamish_penalty ()
void update_masochist_bonus ()
void update_bodytemp_penalty (const time_duration &ticks)
void update_constrained_penalty ()
Private Attributes
std::vector< morale_point > points
std::map< bodypart_id, body_part_data > body_parts
body_part_data no_body_part
std::map< trait_id, mutation_data > mutations
std::map< itype_id, int > super_fancy_items
int level
bool level_is_valid
bool took_prozac
bool took_prozac_bad
bool stylish
int perceived_pain
Detailed Description
Definition at line 36 of file morale.h.
Member Typedef Documentation
mutation_handler
using player_morale::mutation_handler = std::function<void (player_morale &)> private
Definition at line 255 of file morale.h.
Constructor & Destructor Documentation
player_morale() [1/3]
player_morale::player_morale ()
Definition at line 264 of file morale.cpp.
                             :
    level( 0 ),
    level_is_valid( false ),
    took_prozac( false ),
    took_prozac_bad( false ),
    stylish( false ),
    perceived_pain( 0 )
{
    using namespace std::placeholders;
    // Cannot use 'this' because the object is copyable
    const auto set_optimist       = std::bind( &player_morale::set_permanent, _1, MORALE_PERM_OPTIMIST,
                                    _2 );
    const auto set_badtemper      = std::bind( &player_morale::set_permanent, _1, MORALE_PERM_BADTEMPER,
                                    _2 );
    const auto set_stylish        = std::bind( &player_morale::set_stylish, _1, _2 );
    const auto update_constrained = std::bind( &player_morale::update_constrained_penalty, _1 );
    const auto update_masochist   = std::bind( &player_morale::update_masochist_bonus, _1 );
    mutations[trait_OPTIMISTIC]    = mutation_data(
                                         std::bind( set_optimist, _1, 9 ),
                                         std::bind( set_optimist, _1, 0 ) );
    mutations[trait_BADTEMPER]     = mutation_data(
                                         std::bind( set_badtemper, _1, -9 ),
                                         std::bind( set_badtemper, _1, 0 ) );
    mutations[trait_STYLISH]       = mutation_data(
                                         std::bind( set_stylish, _1, true ),
                                         std::bind( set_stylish, _1, false ) );
    mutations[trait_FLOWERS]       = mutation_data( update_constrained );
    mutations[trait_ROOTS1]         = mutation_data( update_constrained );
    mutations[trait_ROOTS2]        = mutation_data( update_constrained );
    mutations[trait_ROOTS3]        = mutation_data( update_constrained );
    mutations[trait_LEAVES2]       = mutation_data( update_constrained );
    mutations[trait_LEAVES3]       = mutation_data( update_constrained );
    mutations[trait_MASOCHIST]     = mutation_data( update_masochist );
    mutations[trait_MASOCHIST_MED] = mutation_data( update_masochist );
    mutations[trait_CENOBITE]      = mutation_data( update_masochist );
}
References MORALE_PERM_BADTEMPER, MORALE_PERM_OPTIMIST, mutations, set_permanent(), set_stylish(), trait_BADTEMPER, trait_CENOBITE, trait_FLOWERS, trait_LEAVES2, trait_LEAVES3, trait_MASOCHIST, trait_MASOCHIST_MED, trait_OPTIMISTIC, trait_ROOTS1, trait_ROOTS2, trait_ROOTS3, trait_STYLISH, update_constrained_penalty(), and update_masochist_bonus().
player_morale() [2/3]
player_morale::player_morale (player_morale &&) default
player_morale() [3/3]
player_morale::player_morale (const player_morale &) default
Member Function Documentation
add() [1/4]
void player_morale::add (morale_type type, const morale_subtype & subtype, int bonus, int max_bonus, const time_duration & duration, const time_duration & decay_start, bool capped) private
Definition at line 302 of file morale.cpp.
{
    if( ( duration == 0_turns ) && !type->is_permanent() ) {
        std::string full_desc = subtype.has_description()
                                ? type.obj().describe( subtype.describe() )
                                : type.obj().describe();
        debugmsg( "Tried to set a non-permanent morale \"%s\" as permanent.", full_desc );
        return;
    }
    for( morale_point &m : points ) {
        if( m.matches( type, subtype ) ) {
            const int prev_bonus = m.get_net_bonus();
            m.add( bonus, max_bonus, duration, decay_start, capped );
            if( m.is_expired() ) {
                remove_expired();
            } else if( m.get_net_bonus() != prev_bonus ) {
                invalidate();
            }
            return;
        }
    }
    morale_point new_morale( type, subtype, bonus, max_bonus, duration, decay_start, capped );
    if( !new_morale.is_expired() ) {
        points.push_back( new_morale );
        invalidate();
    }
}
References debugmsg, player_morale::morale_subtype::describe(), player_morale::morale_subtype::has_description(), invalidate(), player_morale::morale_point::is_expired(), points, remove_expired(), and type.
add() [2/4]
void player_morale::add (morale_type type, int bonus, int max_bonus, const time_duration & duration, const time_duration & decay_start, bool capped, const efftype_id & effect_type)
Definition at line 354 of file morale.cpp.
{
    morale_subtype subtype( effect_type );
    add( type, subtype, bonus, max_bonus, duration, decay_start, capped );
}
References add(), and type.
add() [3/4]
void player_morale::add (morale_type type, int bonus, int max_bonus, const time_duration & duration, const time_duration & decay_start, bool capped, const itype & item_type)
Definition at line 346 of file morale.cpp.
{
    morale_subtype subtype( item_type );
    add( type, subtype, bonus, max_bonus, duration, decay_start, capped );
}
References add(), and type.
add() [4/4]
void player_morale::add (morale_type type, int bonus, int max_bonus = 0, const time_duration & duration = 6_minutes, const time_duration & decay_start = 3_minutes, bool capped = false)
Adds morale to existing or creates one.
Definition at line 338 of file morale.cpp.
{
    morale_subtype subtype;
    add( type, subtype, bonus, max_bonus, duration, decay_start, capped );
}
References add(), and type.
Referenced by add(), set_permanent_typed(), and update_bodytemp_penalty().
calculate_percentage()
void player_morale::calculate_percentage ()
calculates the percentage contribution for each morale point
Definition at line 436 of file morale.cpp.
{
    const morale_mult mult = get_temper_mult();
    int sum_of_positive_squares = 0;
    int sum_of_negative_squares = 0;
    for( const morale_point &m : points ) {
        const int bonus = m.get_net_bonus( mult );
        if( bonus > 0 ) {
            sum_of_positive_squares += bonus * bonus;
        } else {
            sum_of_negative_squares += bonus * bonus;
        }
    }
    for( morale_point &m : points ) {
        const int bonus = m.get_net_bonus( mult );
        if( bonus > 0 ) {
            m.set_percent_contribution( bonus * bonus * 100.0 / sum_of_positive_squares );
        } else {
            m.set_percent_contribution( bonus * bonus * 100.0 / sum_of_negative_squares );
        }
    }
}
References get_temper_mult(), and points.
Referenced by display().
clear()
void player_morale::clear ()
Clears up all morale points.
Definition at line 882 of file morale.cpp.
{
    points.clear();
    no_body_part = body_part_data();
    body_parts.clear();
    for( auto &m : mutations ) {
        m.second.clear();
    }
    took_prozac = false;
    took_prozac_bad = false;
    stylish = false;
    super_fancy_items.clear();
    invalidate();
}
References body_parts, invalidate(), mutations, no_body_part, points, stylish, super_fancy_items, took_prozac, and took_prozac_bad.
consistent_with()
bool player_morale::consistent_with (const player_morale & morale) const
Returns false whether morale is inconsistent with the argument.
Only permanent morale is checked
Definition at line 841 of file morale.cpp.
{
    const auto test_points = []( const player_morale & lhs, const player_morale & rhs ) {
        for( const auto &lhp : lhs.points ) {
            if( !lhp.is_permanent() ) {
                continue;
            }
            const auto iter = std::find_if( rhs.points.begin(), rhs.points.end(),
            [ &lhp ]( const morale_point & rhp ) {
                return lhp.matches( rhp );
            } );
            if( iter == rhs.points.end() || lhp.get_net_bonus() != iter->get_net_bonus() ) {
                debugmsg( "Morale \"%s\" is inconsistent: lhs %d != rhs %s",
                          lhp.get_name(), lhp.get_net_bonus(),
                          ( iter == rhs.points.end() ? "N/A" : std::to_string( iter->get_net_bonus() ).c_str() ) );
                return false;
            }
        }
        return true;
    };
    if( took_prozac != morale.took_prozac ) {
        debugmsg( "player_morale::took_prozac is inconsistent." );
        return false;
    } else if( took_prozac_bad != morale.took_prozac_bad ) {
        debugmsg( "player_morale::took_prozac (bad) is inconsistent." );
        return false;
    } else if( stylish != morale.stylish ) {
        debugmsg( "player_morale::stylish is inconsistent." );
        return false;
    } else if( perceived_pain != morale.perceived_pain ) {
        debugmsg( "player_morale::perceived_pain is inconsistent." );
        return false;
    }
    return test_points( *this, morale ) && test_points( morale, *this );
}
References debugmsg, spell_effect::morale(), perceived_pain, points, stylish, to_string(), took_prozac, and took_prozac_bad.
decay()
void player_morale::decay (const time_duration & ticks = 1_turns)
Ticks down morale counters and removes them.
Definition at line 521 of file morale.cpp.
{
    const auto do_decay = [ &ticks ]( morale_point & m ) {
        m.decay( ticks );
    };
    std::for_each( points.begin(), points.end(), do_decay );
    remove_expired();
    update_bodytemp_penalty( ticks );
    invalidate();
}
References invalidate(), points, remove_expired(), and update_bodytemp_penalty().
display()
void player_morale::display (int focus_eq, int pain_penalty, int fatigue_cap)
Displays morale screen.
Definition at line 533 of file morale.cpp.
{
    /*calculates the percent contributions of the morale points,
     * must be done before anything else in this method
     */
    calculate_percentage();
    constexpr int left_padding = 2; // including border
    constexpr int right_padding = 2; // including border
    constexpr int middle_padding_min = 2;
    constexpr int middle_padding_max = 12;
    class morale_line
    {
        public:
            enum class number_format {
                normal,
                signed_or_dash,
                percent,
            };
            enum class line_color {
                normal,
                green_gray_red,
                red_gray_green,
            };
            struct separation_line {};
        private:
            bool sep_line = false;
            std::string left;
            std::string right;
            nc_color color;
        public:
            morale_line() = default;
            morale_line( const separation_line ) : sep_line( true ) {}
            morale_line( const std::string &text, const nc_color &color )
                : left( text ), color( color ) {}
            morale_line( const std::string &left, const std::string &right,
                         const nc_color &color )
                : left( left ), right( right ), color( color ) {}
            morale_line( const std::string &text, const int num,
                         const number_format num_fmt, const line_color col )
                : left( text ) {
                switch( num_fmt ) {
                    case number_format::normal:
                        right = string_format( "%d", num );
                        break;
                    case number_format::signed_or_dash:
                        if( num == 0 ) {
                            right = "-";
                        } else {
                            right = string_format( "%+d", num );
                        }
                        break;
                    case number_format::percent:
                        right = string_format( "%d%%", num );
                        break;
                }
                switch( col ) {
                    case line_color::normal:
                        color = c_white;
                        break;
                    case line_color::green_gray_red:
                    case line_color::red_gray_green:
                        if( num == 0 ) {
                            color = c_dark_gray;
                        } else if( ( num > 0 ) ^ ( col == line_color::red_gray_green ) ) {
                            color = c_green;
                        } else {
                            color = c_light_red;
                        }
                        break;
                }
            }
            int max_width() const {
                if( sep_line ) {
                    return 0;
                } else if( right.empty() ) {
                    return left_padding + utf8_width( left ) + right_padding;
                } else {
                    return left_padding + utf8_width( left ) + middle_padding_max
                           + utf8_width( right ) + right_padding;
                }
            }
            void draw( catacurses::window &w, const int posy ) const {
                int width = getmaxx( w );
                if( sep_line ) {
                    mvwhline( w, point( 0, posy ), LINE_XXXO, 1 );
                    mvwhline( w, point( 1, posy ), 0, width - 2 );
                    mvwhline( w, point( width - 1, posy ), LINE_XOXX, 1 );
                } else {
                    int text_width = width - left_padding - right_padding;
                    if( !right.empty() ) {
                        right_print( w, posy, right_padding, color, right );
                        text_width -= middle_padding_min + utf8_width( right );
                    }
                    trim_and_print( w, point( left_padding, posy ), text_width, color, left );
                }
            }
    };
    // Separate and sort positive and negative morale
    const morale_mult mult = get_temper_mult();
    std::vector<morale_point> positive_morale;
    std::vector<morale_point> negative_morale;
    for( const morale_point &mp : points ) {
        const int bonus = mp.get_net_bonus( mult );
        if( bonus > 0 ) {
            positive_morale.emplace_back( mp );
        } else if( bonus < 0 ) {
            negative_morale.emplace_back( mp );
        }
    }
    const auto sort_morale = []( const morale_point & lhs, const morale_point & rhs ) -> bool {
        const int lhs_percent = lhs.get_percent_contribution();
        const int rhs_percent = rhs.get_percent_contribution();
        return localized_compare( std::make_pair( -lhs_percent, lhs.get_name() ),
                                  std::make_pair( -rhs_percent, rhs.get_name() ) );
    };
    std::sort( positive_morale.begin(), positive_morale.end(), sort_morale );
    std::sort( negative_morale.begin(), negative_morale.end(), sort_morale );
    // Initialize lines
    const std::vector<morale_line> top_lines {
        {},
        { _( "Morale" ), c_white },
        { morale_line::separation_line {} },
        positive_morale.empty() &&negative_morale.empty() ?
        morale_line( _( "Nothing affects your morale" ), c_dark_gray ) :
        morale_line( _( "Source" ), _( "Value" ), c_light_gray ),
    };
    struct middle_morale_line {
        bool is_caption;
        morale_line ml;
        middle_morale_line( const bool is_caption, const morale_line &ml )
            : is_caption( is_caption ), ml( ml ) {}
    };
    std::vector<middle_morale_line> middle_lines;
    if( !positive_morale.empty() || !negative_morale.empty() ) {
        middle_lines.emplace_back( true, morale_line(
                                       _( "Total positive morale" ), get_total_positive_value(),
                                       morale_line::number_format::signed_or_dash,
                                       morale_line::line_color::green_gray_red
                                   ) );
        for( const morale_point &mp : positive_morale ) {
            middle_lines.emplace_back( false, morale_line(
                                           mp.get_name(), mp.get_percent_contribution(),
                                           morale_line::number_format::percent,
                                           morale_line::line_color::green_gray_red
                                       ) );
        }
        middle_lines.emplace_back( false, morale_line() );
        middle_lines.emplace_back( true, morale_line(
                                       _( "Total negative morale" ), -get_total_negative_value(),
                                       morale_line::number_format::signed_or_dash,
                                       morale_line::line_color::green_gray_red
                                   ) );
        for( const morale_point &mp : negative_morale ) {
            middle_lines.emplace_back( false, morale_line(
                                           mp.get_name(), mp.get_percent_contribution(),
                                           morale_line::number_format::percent,
                                           morale_line::line_color::red_gray_green
                                       ) );
        }
    }
    std::vector<morale_line> bottom_lines;
    bottom_lines.emplace_back( morale_line::separation_line {} );
    bottom_lines.emplace_back(
        _( "Total morale:" ), get_level(),
        morale_line::number_format::signed_or_dash,
        morale_line::line_color::green_gray_red
    );
    if( pain_penalty != 0 ) {
        bottom_lines.emplace_back(
            _( "Pain level:" ), -pain_penalty,
            morale_line::number_format::signed_or_dash,
            morale_line::line_color::green_gray_red
        );
    }
    if( fatigue_cap ) {
        bottom_lines.emplace_back(
            _( "Fatigue Morale Cap:" ), fatigue_cap,
            morale_line::number_format::normal,
            morale_line::line_color::red_gray_green
        );
    }
    bottom_lines.emplace_back(
        _( "Focus trends towards:" ), focus_eq,
        morale_line::number_format::normal,
        morale_line::line_color::normal
    );
    bottom_lines.emplace_back();
    const auto calc_max_width = []( const int width, const morale_line & ml ) -> int {
        return std::max( width, ml.max_width() );
    };
    const int max_window_width = std::max( {
        std::accumulate( top_lines.begin(), top_lines.end(), 0, calc_max_width ),
        std::accumulate( middle_lines.begin(), middle_lines.end(), 0,
        []( const int width, const middle_morale_line & ml ) -> int {
            return std::max( width, ml.ml.max_width() );
        } ),
        std::accumulate( bottom_lines.begin(), bottom_lines.end(), 0, calc_max_width )
    } );
    const int static_lines_height = top_lines.size() + bottom_lines.size();
    int win_w = 0;
    int win_h = 0;
    const int rows_total = middle_lines.size();
    int rows_visible = 0;
    int offset = 0;
    catacurses::window w;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        win_w = std::min( max_window_width, FULL_SCREEN_WIDTH );
        win_h = FULL_SCREEN_HEIGHT;
        const point win( ( TERMX - win_w ) / 2, ( TERMY - win_h ) / 2 );
        rows_visible = std::max( win_h - static_lines_height, 0 );
        if( rows_total < rows_visible ) {
            offset = 0;
        } else if( offset + rows_visible > rows_total ) {
            offset = rows_total - rows_visible;
        }
        w = catacurses::newwin( win_h, win_w, win );
        ui.position_from_window( w );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w );
        draw_border( w );
        int line = 0;
        for( const morale_line &ml : top_lines ) {
            ml.draw( w, line );
            ++line;
        }
        line = win_h - static_cast<int>( bottom_lines.size() );
        for( const morale_line &ml : bottom_lines ) {
            ml.draw( w, line );
            ++line;
        }
        bool caption_drawn = false;
        for( int mid_line = 0; offset + mid_line >= 0; --mid_line ) {
            if( offset + mid_line < rows_total ) {
                const middle_morale_line &ml = middle_lines[offset + mid_line];
                if( ml.is_caption ) {
                    ml.ml.draw( w, top_lines.size() );
                    caption_drawn = true;
                    break;
                }
            }
        }
        for( int mid_line = caption_drawn ? 1 : 0;
             mid_line < rows_visible && offset + mid_line < rows_total;
             ++mid_line ) {
            if( offset + mid_line >= 0 ) {
                const middle_morale_line &ml = middle_lines[offset + mid_line];
                ml.ml.draw( w, static_cast<int>( top_lines.size() ) + mid_line );
            }
        }
        draw_scrollbar( w, offset, rows_visible, rows_total,
                        point( 0, top_lines.size() ), c_white, true );
        wnoutrefresh( w );
    } );
    input_context ctxt( "MORALE" );
    ctxt.register_action( "UP" );
    ctxt.register_action( "DOWN" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    std::string action;
    do {
        ui_manager::redraw();
        action = ctxt.handle_input();
        if( action == "DOWN" && offset < std::max( 0, rows_total - rows_visible ) ) {
            offset++;
        } else if( action == "UP" && offset > 0 ) {
            offset--;
        }
    } while( action != "CONFIRM" && action != "QUIT" );
}
References _, action, c_dark_gray, c_green, c_light_gray, c_light_red, c_white, calculate_percentage(), color(), overmap_ui::draw(), draw_border(), draw_scrollbar(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_level(), player_morale::morale_point::get_name(), player_morale::morale_point::get_percent_contribution(), get_temper_mult(), get_total_negative_value(), get_total_positive_value(), catacurses::getmaxx(), input_context::handle_input(), left, line(), LINE_XOXX, LINE_XXXO, localized_compare, catacurses::mvwhline(), catacurses::newwin(), normal, num, points, ui_manager::redraw(), input_context::register_action(), right, right_print(), string_format(), TERMX, TERMY, trim_and_print(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
get()
int player_morale::get (const morale_type & type) const
Returns bonus from specified morale.
Definition at line 382 of file morale.cpp.
{
    // TODO: This should be well defined for multiple bonuses of the same type!
    auto iter = std::find_if( points.begin(), points.end(), [&type]( const morale_point & m ) {
        return m.type_matches( type );
    } );
    return iter != points.end() ? iter->get_net_bonus() : 0;
}
References points, and type.
get_level()
int player_morale::get_level () const
Returns overall morale level.
Definition at line 489 of file morale.cpp.
{
    if( !level_is_valid ) {
        const morale_mult mult = get_temper_mult();
        int sum_of_positive_squares = 0;
        int sum_of_negative_squares = 0;
        for( auto &m : points ) {
            const int bonus = m.get_net_bonus( mult );
            if( bonus > 0 ) {
                sum_of_positive_squares += bonus * bonus;
            } else {
                sum_of_negative_squares += bonus * bonus;
            }
        }
        level = std::sqrt( sum_of_positive_squares ) - std::sqrt( sum_of_negative_squares );
        if( took_prozac ) {
            level *= morale_mults::prozac;
            if( took_prozac_bad ) {
                level *= morale_mults::prozac_bad;
            }
        }
        level_is_valid = true;
    }
    return level;
}
References get_temper_mult(), level, level_is_valid, points, morale_mults::prozac, morale_mults::prozac_bad, took_prozac, and took_prozac_bad.
Referenced by display().
get_temper_mult()
morale_mult player_morale::get_temper_mult () const private
Definition at line 422 of file morale.cpp.
{
    morale_mult mult;
    if( has( MORALE_PERM_OPTIMIST ) ) {
        mult *= morale_mults::optimist;
    }
    if( has( MORALE_PERM_BADTEMPER ) ) {
        mult *= morale_mults::badtemper;
    }
    return mult;
}
References morale_mults::badtemper, has(), MORALE_PERM_BADTEMPER, MORALE_PERM_OPTIMIST, and morale_mults::optimist.
Referenced by calculate_percentage(), display(), get_level(), get_total_negative_value(), and get_total_positive_value().
get_total_negative_value()
int player_morale::get_total_negative_value () const
Definition at line 462 of file morale.cpp.
{
    const morale_mult mult = get_temper_mult();
    int sum = 0;
    for( const morale_point &m : points ) {
        const int bonus = m.get_net_bonus( mult );
        if( bonus < 0 ) {
            sum += bonus * bonus;
        }
    }
    return std::sqrt( sum );
}
References get_temper_mult(), and points.
Referenced by display().
get_total_positive_value()
int player_morale::get_total_positive_value () const
Definition at line 475 of file morale.cpp.
{
    const morale_mult mult = get_temper_mult();
    int sum = 0;
    for( const morale_point &m : points ) {
        const int bonus = m.get_net_bonus( mult );
        if( bonus > 0 ) {
            sum += bonus * bonus;
        }
    }
    return std::sqrt( sum );
}
References get_temper_mult(), and points.
Referenced by display().
has() [1/2]
bool player_morale::has (const morale_type & type) const
Returns true if any morale point with specified morale exists.
Definition at line 375 of file morale.cpp.
{
    return std::any_of( points.begin(), points.end(), [&type]( const morale_point & m ) {
        return m.type_matches( type );
    } );
}
References points, and type.
Referenced by get_temper_mult().
has() [2/2]
int player_morale::has (const morale_type & type, const morale_subtype & subtype) const private
has_mutation()
bool player_morale::has_mutation (const trait_id & mid) private
Definition at line 903 of file morale.cpp.
{
    const auto &mutation = mutations.find( mid );
    return ( mutation != mutations.end() && mutation->second.get_active() );
}
References mutations.
Referenced by update_constrained_penalty(), and update_masochist_bonus().
invalidate()
void player_morale::invalidate () private
Definition at line 898 of file morale.cpp.
{
    level_is_valid = false;
}
References level_is_valid.
Referenced by add(), clear(), decay(), remove_if(), set_prozac(), and set_prozac_bad().
load()
void player_morale::load (const JsonObject & jsin)
Definition at line 3184 of file savegame_json.cpp.
{
    jsin.allow_omitted_members();
    jsin.read( "morale", points );
}
References JsonObject::allow_omitted_members(), and JsonObject::read().
on_effect_int_change()
void player_morale::on_effect_int_change (const efftype_id & eid, int intensity, const bodypart_str_id & bp = bodypart_str_id::NULL_ID())
Definition at line 974 of file morale.cpp.
{
    if( eid == effect_took_prozac && !bp_id ) {
        set_prozac( intensity != 0 );
    } else if( eid == effect_took_prozac_bad && !bp_id ) {
        set_prozac_bad( intensity != 0 );
    } else if( eid == effect_cold && bp_id ) {
        body_parts[bp_id].cold = intensity;
    } else if( eid == effect_hot && bp_id ) {
        body_parts[bp_id].hot = intensity;
    }
    const morale_type &mt = eid->get_morale_type();
    if( mt ) {
        morale_subtype subtype( eid );
        if( intensity > 0 ) {
            effect ugly_hack( &*eid, 1_turns, bp_id, intensity, calendar::turn_zero );
            int value = ugly_hack.get_amount( "MORALE" );
            set_permanent_typed( mt, value, subtype );
        } else {
            remove( mt, subtype );
        }
    }
}
References body_parts, effect_cold, effect_hot, effect_took_prozac, effect_took_prozac_bad, effect::get_amount(), effect_type::get_morale_type(), remove(), set_permanent_typed(), set_prozac(), set_prozac_bad(), and calendar::turn_zero.
Referenced by Character::check_and_recover_morale().
on_item_takeoff()
void player_morale::on_item_takeoff (const item & it)
Definition at line 940 of file morale.cpp.
{
    set_worn( it, false );
}
References set_worn().
on_item_wear()
void player_morale::on_item_wear (const item & it)
Definition at line 935 of file morale.cpp.
{
    set_worn( it, true );
}
References set_worn().
Referenced by Character::check_and_recover_morale().
on_mutation_gain()
void player_morale::on_mutation_gain (const trait_id & mid)
Definition at line 917 of file morale.cpp.
{
    set_mutation( mid, true );
}
References set_mutation().
Referenced by Character::check_and_recover_morale().
on_mutation_loss()
void player_morale::on_mutation_loss (const trait_id & mid)
Definition at line 922 of file morale.cpp.
{
    set_mutation( mid, false );
}
References set_mutation().
on_stat_change()
void player_morale::on_stat_change (const std::string & stat, int value)
Definition at line 927 of file morale.cpp.
{
    if( stat == "perceived_pain" ) {
        perceived_pain = value;
        update_masochist_bonus();
    }
}
References perceived_pain, and update_masochist_bonus().
Referenced by Character::check_and_recover_morale().
on_worn_item_transform()
void player_morale::on_worn_item_transform (const item & old_it, const item & new_it)
Definition at line 945 of file morale.cpp.
{
    set_worn( old_it, false );
    set_worn( new_it, true );
}
References set_worn().
on_worn_item_washed()
void player_morale::on_worn_item_washed (const item & it)
Definition at line 951 of file morale.cpp.
{
    const auto update_body_part = [&]( body_part_data & bp_data ) {
        bp_data.filthy -= 1;
    };
    const body_part_set covered( it.get_covered_body_parts() );
    if( covered.any() ) {
        for( const bodypart_id &bp_id : get_player_character().get_all_body_parts() ) {
            auto bp = bp_id->token;
            if( covered.test( bp ) ) {
                const bodypart_id bp_id = convert_bp( bp ).id();
                update_body_part( body_parts[bp_id] );
            }
        }
    } else {
        update_body_part( no_body_part );
    }
    update_squeamish_penalty();
}
References body_part_set::any(), body_parts, convert_bp(), item::get_covered_body_parts(), get_player_character(), string_id< T >::id(), no_body_part, body_part_set::test(), and update_squeamish_penalty().
operator=() [1/2]
player_morale & player_morale::operator= (const player_morale &) default
operator=() [2/2]
player_morale & player_morale::operator= (player_morale &&) default
remove() [1/2]
void player_morale::remove (const morale_type & type)
Removes specified morale.
Definition at line 401 of file morale.cpp.
{
    remove_if( [ type ]( const morale_point & m ) -> bool {
        return m.type_matches( type );
    } );
}
References remove_if(), type, and player_morale::morale_point::type_matches().
Referenced by on_effect_int_change(), and set_permanent_typed().
remove() [2/2]
void player_morale::remove (const morale_type & type, const morale_subtype & subtype) private
Definition at line 408 of file morale.cpp.
{
    remove_if( [ &type, &subtype ]( const morale_point & m ) -> bool {
        return m.matches( type, subtype );
    } );
}
References player_morale::morale_point::matches(), remove_if(), and type.
remove_expired()
void player_morale::remove_expired () private
Definition at line 415 of file morale.cpp.
{
    remove_if( []( const morale_point & m ) -> bool {
        return m.is_expired();
    } );
}
References player_morale::morale_point::is_expired(), and remove_if().
Referenced by add(), and decay().
remove_if()
void player_morale::remove_if (const std::function< bool(const morale_point &)> & func) private
Definition at line 391 of file morale.cpp.
{
    const auto new_end = std::remove_if( points.begin(), points.end(), func );
    if( new_end != points.end() ) {
        points.erase( new_end, points.end() );
        invalidate();
    }
}
References invalidate(), and points.
Referenced by remove(), and remove_expired().
set_mutation()
void player_morale::set_mutation (const trait_id & mid, bool active) private
Definition at line 909 of file morale.cpp.
{
    const auto &mutation = mutations.find( mid );
    if( mutation != mutations.end() ) {
        mutation->second.set_active( *this, active );
    }
}
References active, and mutations.
Referenced by on_mutation_gain(), and on_mutation_loss().
set_permanent()
void player_morale::set_permanent (const morale_type & type, int bonus)
Sets the new level for the permanent morale, or creates one.
Definition at line 362 of file morale.cpp.
{
    set_permanent_typed( type, bonus, morale_subtype() );
}
References set_permanent_typed(), and type.
Referenced by player_morale(), update_constrained_penalty(), update_masochist_bonus(), update_squeamish_penalty(), and update_stylish_bonus().
set_permanent_typed()
void player_morale::set_permanent_typed (const morale_type & type, int bonus, const morale_subtype & subtype) private
Definition at line 367 of file morale.cpp.
{
    // Hack: should replace instead of remove+readd
    remove( type, subtype );
    add( type, subtype, bonus, 0, 0_turns, 0_turns, false );
}
References add(), remove(), and type.
Referenced by on_effect_int_change(), and set_permanent().
set_prozac()
void player_morale::set_prozac (bool new_took_prozac) private
Definition at line 1055 of file morale.cpp.
{
    if( took_prozac != new_took_prozac ) {
        took_prozac = new_took_prozac;
        update_masochist_bonus();
        invalidate();
    }
}
References invalidate(), took_prozac, and update_masochist_bonus().
Referenced by on_effect_int_change().
set_prozac_bad()
void player_morale::set_prozac_bad (bool new_took_prozac_bad) private
Definition at line 1064 of file morale.cpp.
{
    if( took_prozac_bad != new_took_prozac_bad ) {
        took_prozac_bad = new_took_prozac_bad;
        invalidate();
    }
}
References invalidate(), and took_prozac_bad.
Referenced by on_effect_int_change().
set_stylish()
void player_morale::set_stylish (bool new_stylish) private
Definition at line 1072 of file morale.cpp.
{
    if( stylish != new_stylish ) {
        stylish = new_stylish;
        update_stylish_bonus();
    }
}
References stylish, and update_stylish_bonus().
Referenced by player_morale().
set_worn()
void player_morale::set_worn (const item & it, bool worn) private
Definition at line 1000 of file morale.cpp.
{
    const bool fancy = it.has_flag( "FANCY" );
    const bool super_fancy = it.has_flag( "SUPER_FANCY" );
    const bool filthy_gear = it.has_flag( "FILTHY" );
    const int sign = ( worn ) ? 1 : -1;
    const auto update_body_part = [&]( body_part_data & bp_data ) {
        if( fancy || super_fancy ) {
            bp_data.fancy += sign;
        }
        if( filthy_gear ) {
            bp_data.filthy += sign;
        }
        bp_data.covered += sign;
    };
    const body_part_set covered( it.get_covered_body_parts() );
    if( covered.any() ) {
        for( const bodypart_id &bp_id : get_player_character().get_all_body_parts() ) {
            auto bp = bp_id->token;
            if( covered.test( bp ) ) {
                const bodypart_id bp_id = convert_bp( bp ).id();
                update_body_part( body_parts[bp_id] );
            }
        }
    } else {
        update_body_part( no_body_part );
    }
    if( super_fancy ) {
        const auto id = it.typeId();
        const auto iter = super_fancy_items.find( id );
        if( iter != super_fancy_items.end() ) {
            iter->second += sign;
            if( iter->second == 0 ) {
                super_fancy_items.erase( iter );
            }
        } else if( worn ) {
            super_fancy_items[id] = 1;
        } else {
            debugmsg( "Tried to take off \"%s\" which isn't worn.", id.c_str() );
        }
    }
    if( fancy || super_fancy ) {
        update_stylish_bonus();
    }
    if( filthy_gear ) {
        update_squeamish_penalty();
    }
    update_constrained_penalty();
}
References body_part_set::any(), body_parts, convert_bp(), debugmsg, item::get_covered_body_parts(), get_player_character(), item::has_flag(), base_camps::id, string_id< T >::id(), no_body_part, sign(), super_fancy_items, body_part_set::test(), item::typeId(), update_constrained_penalty(), update_squeamish_penalty(), and update_stylish_bonus().
Referenced by on_item_takeoff(), on_item_wear(), and on_worn_item_transform().
store()
void player_morale::store (JsonOut & jsout) const
Definition at line 3179 of file savegame_json.cpp.
{
    jsout.member( "morale", points );
}
References JsonOut::member().
update_bodytemp_penalty()
void player_morale::update_bodytemp_penalty (const time_duration & ticks) private
Definition at line 1118 of file morale.cpp.
{
    float max_cold_penalty = 0;
    float max_hot_penalty = 0;
    for( const std::pair<const bodypart_id, body_part_data> &bpt : body_parts ) {
        const bodypart_id bp = bpt.first;
        max_cold_penalty += body_parts[bp].cold * bp->cold_morale_mod;
        max_hot_penalty += body_parts[bp].hot * bp->hot_morale_mod;
    }
    if( max_cold_penalty != 0 ) {
        add( MORALE_COLD, -2 * to_turns<int>( ticks ), -std::abs( max_cold_penalty ), 1_minutes, 30_seconds,
             true );
    }
    if( max_hot_penalty != 0 ) {
        add( MORALE_HOT, -2 * to_turns<int>( ticks ), -std::abs( max_hot_penalty ), 1_minutes, 30_seconds,
             true );
    }
}
References add(), body_parts, MORALE_COLD, and MORALE_HOT.
Referenced by decay().
update_constrained_penalty()
void player_morale::update_constrained_penalty () private
Definition at line 1137 of file morale.cpp.
{
    const auto bp_pen = [ this ]( bodypart_id bp, int pen ) -> int {
        return ( body_parts[bp].covered > 0 ) ? pen : 0;
    };
    int pen = 0;
    if( has_mutation( trait_FLOWERS ) ) {
        pen += bp_pen( bodypart_id( "head" ), 10 );
    }
    if( has_mutation( trait_ROOTS1 ) || has_mutation( trait_ROOTS2 ) ||
        has_mutation( trait_ROOTS3 ) ) {
        pen += bp_pen( bodypart_id( "foot_l" ), 5 );
        pen += bp_pen( bodypart_id( "foot_r" ), 5 );
    }
    if( has_mutation( trait_LEAVES2 ) || has_mutation( trait_LEAVES3 ) ) {
        pen += bp_pen( bodypart_id( "arm_l" ), 5 );
        pen += bp_pen( bodypart_id( "arm_r" ), 5 );
    }
    set_permanent( MORALE_PERM_CONSTRAINED, -std::min( pen, 10 ) );
}
References body_parts, has_mutation(), MORALE_PERM_CONSTRAINED, set_permanent(), trait_FLOWERS, trait_LEAVES2, trait_LEAVES3, trait_ROOTS1, trait_ROOTS2, and trait_ROOTS3.
Referenced by player_morale(), and set_worn().
update_masochist_bonus()
void player_morale::update_masochist_bonus () private
Definition at line 1097 of file morale.cpp.
{
    const bool amateur_masochist = has_mutation( trait_MASOCHIST );
    const bool advanced_masochist = has_mutation( trait_MASOCHIST_MED ) ||
                                    has_mutation( trait_CENOBITE );
    const bool any_masochist = amateur_masochist || advanced_masochist;
    int bonus = 0;
    if( any_masochist ) {
        bonus = perceived_pain / 2.5;
        if( amateur_masochist ) {
            bonus = std::min( bonus, 25 );
        }
        if( took_prozac ) {
            bonus = bonus / 3;
        }
    }
    set_permanent( MORALE_PERM_MASOCHIST, bonus );
}
References has_mutation(), MORALE_PERM_MASOCHIST, perceived_pain, set_permanent(), took_prozac, trait_CENOBITE, trait_MASOCHIST, and trait_MASOCHIST_MED.
Referenced by on_stat_change(), player_morale(), and set_prozac().
update_squeamish_penalty()
void player_morale::update_squeamish_penalty () private
Definition at line 1159 of file morale.cpp.
{
    if( !get_option<bool>( "FILTHY_MORALE" ) ) {
        set_permanent( MORALE_PERM_FILTHY, 0 );
        return;
    }
    int penalty = 0;
    for( const std::pair<const bodypart_id, body_part_data> &bpt : body_parts ) {
        if( bpt.second.filthy > 0 ) {
            penalty += bpt.first->squeamish_penalty;
        }
    }
    penalty += 2 * std::min( static_cast<int>( no_body_part.filthy ), 3 );
    set_permanent( MORALE_PERM_FILTHY, -penalty );
}
References body_parts, player_morale::body_part_data::filthy, MORALE_PERM_FILTHY, no_body_part, and set_permanent().
Referenced by on_worn_item_washed(), and set_worn().
update_stylish_bonus()
void player_morale::update_stylish_bonus () private
Definition at line 1080 of file morale.cpp.
{
    int bonus = 0;
    if( stylish ) {
        float tmp_bonus = 0;
        for( const std::pair<const bodypart_id, body_part_data> &bpt : body_parts ) {
            if( bpt.second.fancy > 0 ) {
                tmp_bonus += bpt.first->stylish_bonus;
            }
        }
        bonus = std::min( static_cast<int>( 2 * super_fancy_items.size() ) +
                          2 * std::min( static_cast<int>( no_body_part.fancy ), 3 ) + static_cast<int>( tmp_bonus ), 20 );
    }
    set_permanent( MORALE_PERM_FANCY, bonus );
}
References body_parts, player_morale::body_part_data::fancy, MORALE_PERM_FANCY, no_body_part, set_permanent(), stylish, and super_fancy_items.
Referenced by set_stylish(), and set_worn().
Member Data Documentation
body_parts
std::map<bodypart_id, body_part_data> player_morale::body_parts private
Definition at line 252 of file morale.h.
Referenced by clear(), on_effect_int_change(), on_worn_item_washed(), set_worn(), update_bodytemp_penalty(), update_constrained_penalty(), update_squeamish_penalty(), and update_stylish_bonus().
level
int player_morale::level mutable private
Definition at line 280 of file morale.h.
Referenced by get_level().
level_is_valid
bool player_morale::level_is_valid mutable private
Definition at line 281 of file morale.h.
Referenced by get_level(), and invalidate().
mutations
std::map<trait_id, mutation_data> player_morale::mutations private
Definition at line 275 of file morale.h.
Referenced by clear(), has_mutation(), player_morale(), and set_mutation().
no_body_part
body_part_data player_morale::no_body_part private
Definition at line 253 of file morale.h.
Referenced by clear(), on_worn_item_washed(), set_worn(), update_squeamish_penalty(), and update_stylish_bonus().
perceived_pain
int player_morale::perceived_pain private
Definition at line 286 of file morale.h.
Referenced by consistent_with(), on_stat_change(), and update_masochist_bonus().
points
std::vector<morale_point> player_morale::points private
Definition at line 236 of file morale.h.
Referenced by add(), calculate_percentage(), clear(), consistent_with(), decay(), display(), get(), get_level(), get_total_negative_value(), get_total_positive_value(), has(), and remove_if().
stylish
bool player_morale::stylish private
Definition at line 285 of file morale.h.
Referenced by clear(), consistent_with(), set_stylish(), and update_stylish_bonus().
super_fancy_items
std::map<itype_id, int> player_morale::super_fancy_items private
Definition at line 277 of file morale.h.
Referenced by clear(), set_worn(), and update_stylish_bonus().
took_prozac
bool player_morale::took_prozac private
Definition at line 283 of file morale.h.
Referenced by clear(), consistent_with(), get_level(), set_prozac(), and update_masochist_bonus().
took_prozac_bad
bool player_morale::took_prozac_bad private
Definition at line 284 of file morale.h.
Referenced by clear(), consistent_with(), get_level(), and set_prozac_bad().
The documentation for this class was generated from the following files:
src/morale.h
src/morale.cpp
src/savegame_json.cpp