Cataclysm BN: inventory_compare_selector Class Reference
inventory_compare_selector Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_compare_selector (player &p)
std::pair< const item *, const item * > execute ()
Public Member Functions inherited from inventory_multiselector
inventory_multiselector (player &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title="")
Public Member Functions inherited from inventory_selector
inventory_selector (player &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
void add_character_items (Character &character)
These functions add items from map / vehicles.
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
bool select (const item_location &loc)
Select a location.
const inventory_entry & get_selected ()
void select_position (std::pair< size_t, size_t > position)
std::pair< size_t, size_t > get_selection_position ()
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void set_active_column (size_t index)
std::string action_bound_to_key (char key) const
std::vector< char > all_bound_keys () const
Returns all keys in the current context which are bound to an action.
Protected Member Functions
void toggle_entry (inventory_entry *entry)
Protected Member Functions inherited from inventory_multiselector
void rearrange_columns (size_t client_width) override
Tackles screen overflow.
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
void add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr)
void add_item (inventory_column &target_column, item_location &&location, const item_category *custom_category=nullptr)
void add_items (inventory_column &target_column, const std::function< item_location(item *)> &locator, const std::vector< std::list< item * > > &stacks, const item_category *custom_category=nullptr)
inventory_input get_input ()
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
void set_filter ()
virtual stats get_raw_stats () const
Get stats to display in top right.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Protected Attributes
std::vector< const item * > compared
Protected Attributes inherited from inventory_selector
player & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
Additional Inherited Members
Public Types inherited from inventory_selector
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 2 >
Public Attributes inherited from inventory_selector
bool keep_open = false
Static Protected Member Functions inherited from inventory_selector
static stats get_weight_and_volume_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity)
Detailed Description
Definition at line 676 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_compare_selector()
inventory_compare_selector::inventory_compare_selector (player & p)
Definition at line 1958 of file inventory_ui.cpp.
                                                                  :
    inventory_multiselector( p, default_preset, _( "ITEMS TO COMPARE" ) ) {}
Member Function Documentation
execute()
std::pair< const item *, const item * > inventory_compare_selector::execute ()
Definition at line 1961 of file inventory_ui.cpp.
{
    shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
    while( true ) {
        ui_manager::redraw();
        const inventory_input input = get_input();
        inventory_entry *just_selected = nullptr;
        if( input.entry != nullptr ) {
            select( input.entry->any_item() );
            toggle_entry( input.entry );
            just_selected = input.entry;
        } else if( input.action == "RIGHT" ) {
            const auto selection( get_active_column().get_all_selected() );
            for( auto &elem : selection ) {
                if( elem->chosen_count == 0 || selection.size() == 1 ) {
                    toggle_entry( elem );
                    just_selected = elem;
                    if( compared.size() == 2 ) {
                        break;
                    }
                }
            }
        } else if( input.action == "CONFIRM" ) {
            popup_getkey( _( "You need two items for comparison.  Use %s to select them." ),
                          ctxt.get_desc( "RIGHT" ) );
        } else if( input.action == "QUIT" ) {
            return std::make_pair( nullptr, nullptr );
        } else if( input.action == "INVENTORY_FILTER" ) {
            set_filter();
        } else if( input.action == "TOGGLE_FAVORITE" ) {
            // TODO: implement favoriting in multi selection menus while maintaining selection
        } else {
            on_input( input );
        }
        if( compared.size() == 2 ) {
            const auto res = std::make_pair( compared[0], compared[1] );
            // Clear second selected entry to prevent comparison reopening too
            // soon
            if( just_selected ) {
                toggle_entry( just_selected );
            }
            return res;
        }
    }
}
References _, inventory_input::action, inventory_entry::any_item(), compared, inventory_selector::create_or_get_ui_adaptor(), inventory_selector::ctxt, inventory_input::entry, inventory_selector::get_active_column(), input_context::get_desc(), inventory_selector::get_input(), inventory_selector::on_input(), popup_getkey(), ui_manager::redraw(), inventory_selector::select(), inventory_selector::set_filter(), and toggle_entry().
Referenced by game_menus::inv::compare().
toggle_entry()
void inventory_compare_selector::toggle_entry (inventory_entry * entry) protected
Definition at line 2012 of file inventory_ui.cpp.
{
    const item *it = &*entry->any_item();
    const auto iter = std::find( compared.begin(), compared.end(), it );
    entry->chosen_count = iter == compared.end() ? 1 : 0;
    if( entry->chosen_count != 0 ) {
        compared.push_back( it );
    } else {
        compared.erase( iter );
    }
    on_change( *entry );
}
References inventory_entry::any_item(), inventory_entry::chosen_count, compared, detail::find(), and inventory_selector::on_change().
Referenced by execute().
Member Data Documentation
compared
std::vector<const item *> inventory_compare_selector::compared protected
Definition at line 683 of file inventory_ui.h.
Referenced by execute(), and toggle_entry().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp