Cataclysm BN: jmapgen_field Class Reference
jmapgen_field Class Reference
Places fields on the map.
Public Member Functions
jmapgen_field (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
field_type_id ftype
int intensity
time_duration age
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Places fields on the map.
"field": field type ident. "intensity": initial field intensity. "age": initial field age.
Definition at line 836 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_field()
jmapgen_field::jmapgen_field (const JsonObject & jsi) inline
Definition at line 842 of file mapgen.cpp.
                                               :
            ftype( field_type_id( jsi.get_string( "field" ) ) )
            , intensity( jsi.get_int( "intensity", 1 ) )
            , age( time_duration::from_turns( jsi.get_int( "age", 0 ) ) ) {
            if( !ftype.id() ) {
                set_mapgen_defer( jsi, "field", "invalid field type" );
            }
        }
References ftype, int_id< T >::id(), mapgen_defer::jsi, and set_mapgen_defer().
Member Function Documentation
apply()
void jmapgen_field::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 850 of file mapgen.cpp.
{
            dat.m.add_field( tripoint( x.get(), y.get(), dat.m.get_abs_sub().z ), ftype, intensity, age );
        }
References map::add_field(), age, ftype, jmapgen_int::get(), map::get_abs_sub(), intensity, mapgendata::m, and tripoint::z.
Member Data Documentation
age
time_duration jmapgen_field::age
Definition at line 841 of file mapgen.cpp.
Referenced by apply().
ftype
field_type_id jmapgen_field::ftype
Definition at line 839 of file mapgen.cpp.
Referenced by apply(), and jmapgen_field().
intensity
int jmapgen_field::intensity
Definition at line 840 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp