Cataclysm BN: DynamicDataLoader Class Reference
DynamicDataLoader Class Reference
This class is used to load (and unload) the dynamic (and moddable) data from json files.
#include <init.h>
Classes
struct cached_streams
Public Types
using type_string = std::string
using t_type_function_map = std::map< type_string, std::function< void(const JsonObject &, const std::string &, const std::string &, const std::string &)> >
using str_vec = std::vector< std::string >
using deferred_json = std::list< std::pair< json_source_location, std::string > >
JSON data dependent upon as-yet unparsed definitions first: JSON source location, second: source identifier.
Public Member Functions
void load_data_from_path (const std::string &path, const std::string &src, loading_ui &ui)
Load all data from json files located in the path (recursive).
void unload_data ()
Deletes and unloads all the data previously loaded with load_data_from_path.
void finalize_loaded_data (loading_ui &ui)
Called to finalize the loaded data.
void load_deferred (deferred_json &data)
Loads and then removes entries from.
bool is_data_finalized () const
Returns whether the data is finalized and ready to be utilized.
shared_ptr_fast< std::istream > get_cached_stream (const std::string &path)
Get a possibly cached stream for deferred data loading.
Static Public Member Functions
static DynamicDataLoader & get_instance ()
Returns the single instance of this class.
Private Member Functions
void add (const std::string &type, std::function< void(const JsonObject &)> f)
void add (const std::string &type, std::function< void(const JsonObject &, const std::string &)> f)
void add (const std::string &type, std::function< void(const JsonObject &, const std::string &, const std::string &, const std::string &)> f)
void load_all_from_json (JsonIn &jsin, const std::string &src, loading_ui &ui, const std::string &base_path, const std::string &full_path)
Load all the types from that json data.
void load_object (const JsonObject &jo, const std::string &src, const std::string &base_path=std::string(), const std::string &full_path=std::string())
Load a single object from a json object.
DynamicDataLoader ()
~DynamicDataLoader ()
void initialize ()
Initializes type_function_map.
void check_consistency (loading_ui &ui)
Check the consistency of all the loaded data.
Private Attributes
bool finalized = false
std::unique_ptr< cached_streams > stream_cache
t_type_function_map type_function_map
Maps the type string (coming from json) to the functor that loads that kind of object from json.
Detailed Description
This class is used to load (and unload) the dynamic (and moddable) data from json files.
There exists only one instance of this class, which can be accessed with get_instance
Usage is basically this:
Let user decide which world to play in.
Call unload_data (to unload data from a previously loaded world, if any)
Call load_data_from_path(...) repeatedly with different paths for all the mods of the current world.
Call finalize_loaded_data when all mods have been loaded.
Play.
The object initializes itself upon first usage. It also unloads everything when the program ends.
Porting stuff to json works like this:
create a function void load_my_object(JsonObject &jo);
Add an entry to type_function_map (inside of initialize) that calls the new function.
Inside that function load the data from the json object. You must also provide a reset function and add a call to that function in unload_data
Optional: create a finalize function and call it from finalize_loaded_data
Optional: create a function to check the consistency of the loaded data and call this function from check_consistency
Than create json files.
Definition at line 56 of file init.h.
Member Typedef Documentation
deferred_json
using DynamicDataLoader::deferred_json = std::list<std::pair<json_source_location, std::string> >
JSON data dependent upon as-yet unparsed definitions first: JSON source location, second: source identifier.
Definition at line 68 of file init.h.
str_vec
using DynamicDataLoader::str_vec = std::vector<std::string>
Definition at line 62 of file init.h.
t_type_function_map
using DynamicDataLoader::t_type_function_map = std::map<type_string, std::function<void(const JsonObject &, const std::string &, const std::string &, const std::string &)> >
Definition at line 60 of file init.h.
type_string
using DynamicDataLoader::type_string = std::string
Definition at line 59 of file init.h.
Constructor & Destructor Documentation
DynamicDataLoader()
DynamicDataLoader::DynamicDataLoader () private
Definition at line 112 of file init.cpp.
{
    initialize();
}
References initialize().
~DynamicDataLoader()
DynamicDataLoader::~DynamicDataLoader () private default
Member Function Documentation
add() [1/3]
void DynamicDataLoader::add (const std::string & type, std::function< void(const JsonObject &)> f) private
Definition at line 232 of file init.cpp.
{
    const auto pair = type_function_map.emplace( type, [f]( const JsonObject & obj, const std::string &,
    const std::string &, const std::string & ) {
        f( obj );
    } );
    if( !pair.second ) {
        debugmsg( "tried to insert a second handler for type %s into the DynamicDataLoader", type.c_str() );
    }
}
References debugmsg, type, and type_function_map.
Referenced by initialize().
add() [2/3]
void DynamicDataLoader::add (const std::string & type, std::function< void(const JsonObject &, const std::string &)> f) private
Definition at line 219 of file init.cpp.
{
    const auto pair = type_function_map.emplace( type, [f]( const JsonObject & obj,
                      const std::string & src,
    const std::string &, const std::string & ) {
        f( obj, src );
    } );
    if( !pair.second ) {
        debugmsg( "tried to insert a second handler for type %s into the DynamicDataLoader", type.c_str() );
    }
}
References debugmsg, type, and type_function_map.
add() [3/3]
void DynamicDataLoader::add (const std::string & type, std::function< void(const JsonObject &, const std::string &, const std::string &, const std::string &)> f) private
Definition at line 209 of file init.cpp.
{
    const auto pair = type_function_map.emplace( type, f );
    if( !pair.second ) {
        debugmsg( "tried to insert a second handler for type %s into the DynamicDataLoader", type.c_str() );
    }
}
References debugmsg, type, and type_function_map.
check_consistency()
void DynamicDataLoader::check_consistency (loading_ui & ui) private
Check the consistency of all the loaded data.
May print a debugmsg if something seems wrong.
Parameters
ui Finalization status display.
Definition at line 723 of file init.cpp.
{
    ui.new_context( _( "Verifying" ) );
    using named_entry = std::pair<std::string, std::function<void()>>;
    const std::vector<named_entry> entries = {{
            { _( "Flags" ), &json_flag::check_consistency },
            {
                _( "Crafting requirements" ), []()
                {
                    requirement_data::check_consistency();
                }
            },
            { _( "Vitamins" ), &vitamin::check_consistency },
            { _( "Weather types" ), &weather_types::check_consistency },
            { _( "Field types" ), &field_types::check_consistency },
            { _( "Ammo effects" ), &ammo_effects::check_consistency },
            { _( "Emissions" ), &emit::check_consistency },
            { _( "Activities" ), &activity_type::check_consistency },
            {
                _( "Items" ), []()
                {
                    item_controller->check_definitions();
                }
            },
            { _( "Materials" ), &materials::check },
            { _( "Engine faults" ), &fault::check_consistency },
            { _( "Vehicle parts" ), &vpart_info::check },
            { _( "Mapgen definitions" ), &check_mapgen_definitions },
            { _( "Mapgen palettes" ), &mapgen_palette::check_definitions },
            {
                _( "Monster types" ), []()
                {
                    MonsterGenerator::generator().check_monster_definitions();
                }
            },
            { _( "Monster groups" ), &MonsterGroupManager::check_group_definitions },
            { _( "Furniture and terrain" ), &check_furniture_and_terrain },
            { _( "Constructions" ), &constructions::check_consistency },
            { _( "Construction sequences" ), &constructions::check_consistency },
            { _( "Professions" ), &profession::check_definitions },
            { _( "Scenarios" ), &scenario::check_definitions },
            { _( "Martial arts" ), &check_martialarts },
            { _( "Mutations" ), &mutation_branch::check_consistency },
            { _( "Mutation Categories" ), &mutation_category_trait::check_consistency },
            { _( "Overmap land use codes" ), &overmap_land_use_codes::check_consistency },
            { _( "Overmap connections" ), &overmap_connections::check_consistency },
            { _( "Overmap terrain" ), &overmap_terrains::check_consistency },
            { _( "Overmap locations" ), &overmap_locations::check_consistency },
            { _( "Overmap specials" ), &overmap_specials::check_consistency },
            { _( "Map extras" ), &MapExtras::check_consistency },
            { _( "Start locations" ), &start_locations::check_consistency },
            { _( "Ammunition types" ), &ammunition_type::check_consistency },
            { _( "Traps" ), &trap::check_consistency },
            { _( "Bionics" ), &bionic_data::check_consistency },
            { _( "Gates" ), &gates::check },
            { _( "NPC classes" ), &npc_class::check_consistency },
            { _( "Behaviors" ), &behavior::check_consistency },
            { _( "Mission types" ), &mission_type::check_consistency },
            {
                _( "Item actions" ), []()
                {
                    item_action_generator::generator().check_consistency();
                }
            },
            { _( "Harvest lists" ), &harvest_list::check_consistency },
            { _( "NPC templates" ), &npc_template::check_consistency },
            { _( "Body parts" ), &body_part_type::check_consistency },
            { _( "Anatomies" ), &anatomy::check_consistency },
            { _( "Spells" ), &spell_type::check_consistency },
            { _( "Enchantments" ), &enchantment::check_consistency },
            { _( "Transformations" ), &event_transformation::check_consistency },
            { _( "Statistics" ), &event_statistic::check_consistency },
            { _( "Scent types" ), &scent_type::check_scent_consistency },
            { _( "Scores" ), &score::check_consistency },
            { _( "Achievements" ), &achievement::check_consistency },
            { _( "Disease types" ), &disease_type::check_disease_consistency },
            { _( "Factions" ), &faction_template::check_consistency },
            { _( "Effects" ), &effect_type::check_consistency },
        }
    };
    for( const named_entry &e : entries ) {
        ui.add_entry( e.first );
    }
    ui.show();
    for( const named_entry &e : entries ) {
        e.second();
        ui.proceed();
    }
}
References _, gates::check(), materials::check(), vpart_info::check(), achievement::check_consistency(), activity_type::check_consistency(), ammunition_type::check_consistency(), ammo_effects::check_consistency(), anatomy::check_consistency(), behavior::check_consistency(), bionic_data::check_consistency(), body_part_type::check_consistency(), constructions::check_consistency(), effect_type::check_consistency(), emit::check_consistency(), event_transformation::check_consistency(), event_statistic::check_consistency(), score::check_consistency(), faction_template::check_consistency(), fault::check_consistency(), field_types::check_consistency(), json_flag::check_consistency(), harvest_list::check_consistency(), spell_type::check_consistency(), enchantment::check_consistency(), MapExtras::check_consistency(), mission_type::check_consistency(), mutation_branch::check_consistency(), mutation_category_trait::check_consistency(), npc_template::check_consistency(), npc_class::check_consistency(), overmap_terrains::check_consistency(), overmap_land_use_codes::check_consistency(), overmap_connections::check_consistency(), overmap_locations::check_consistency(), overmap_specials::check_consistency(), requirement_data::check_consistency(), start_locations::check_consistency(), trap::check_consistency(), vitamin::check_consistency(), weather_types::check_consistency(), item_action_generator::check_consistency(), mapgen_palette::check_definitions(), profession::check_definitions(), scenario::check_definitions(), disease_type::check_disease_consistency(), check_furniture_and_terrain(), MonsterGroupManager::check_group_definitions(), check_mapgen_definitions(), check_martialarts(), MonsterGenerator::check_monster_definitions(), scent_type::check_scent_consistency(), item_action_generator::generator(), MonsterGenerator::generator(), and item_controller.
Referenced by finalize_loaded_data().
finalize_loaded_data()
void DynamicDataLoader::finalize_loaded_data (loading_ui & ui)
Called to finalize the loaded data.
This should be called after all the mods have been loaded. It must be called once after loading all data. It also checks the consistency of the loaded data with check_consistency
Parameters
ui Finalization status display.
Exceptions
std::exception if the loaded data is not valid. The game should not proceed in that case.
Definition at line 635 of file init.cpp.
{
    assert( !finalized && "Can't finalize the data twice." );
    assert( !stream_cache && "Expected stream cache to be null before finalization" );
    on_out_of_scope reset_stream_cache( [this]() {
        stream_cache.reset();
    } );
    stream_cache = std::make_unique<cached_streams>();
    ui.new_context( _( "Finalizing" ) );
    using named_entry = std::pair<std::string, std::function<void()>>;
    const std::vector<named_entry> entries = {{
            { _( "Flags" ), &json_flag::finalize_all },
            { _( "Body parts" ), &body_part_type::finalize_all },
            { _( "Bionics" ), &bionic_data::finalize_all },
            { _( "Weather types" ), &weather_types::finalize_all },
            { _( "Field types" ), &field_types::finalize_all },
            { _( "Ammo effects" ), &ammo_effects::finalize_all },
            { _( "Emissions" ), &emit::finalize },
            {
                _( "Items" ), []()
                {
                    item_controller->finalize();
                }
            },
            {
                _( "Crafting requirements" ), []()
                {
                    requirement_data::finalize();
                }
            },
            { _( "Vehicle parts" ), &vpart_info::finalize },
            { _( "Traps" ), &trap::finalize },
            { _( "Terrain" ), &set_ter_ids },
            { _( "Furniture" ), &finalize_furn },
            { _( "Overmap land use codes" ), &overmap_land_use_codes::finalize },
            { _( "Overmap terrain" ), &overmap_terrains::finalize },
            { _( "Overmap connections" ), &overmap_connections::finalize },
            { _( "Overmap specials" ), &overmap_specials::finalize },
            { _( "Overmap locations" ), &overmap_locations::finalize },
            { _( "Start locations" ), &start_locations::finalize_all },
            { _( "Zone manager" ), &zone_manager::reset_manager },
            { _( "Vehicle prototypes" ), &vehicle_prototype::finalize },
            { _( "Mapgen weights" ), &calculate_mapgen_weights },
            {
                _( "Monster types" ), []()
                {
                    MonsterGenerator::generator().finalize_mtypes();
                }
            },
            { _( "Monster groups" ), &MonsterGroupManager::FinalizeMonsterGroups },
            { _( "Monster factions" ), &monfactions::finalize },
            { _( "Factions" ), &npc_factions::finalize },
            { _( "Constructions" ), &constructions::finalize },
            { _( "Construction sequences" ), &construction_sequences::finalize },
            { _( "Crafting recipes" ), &recipe_dictionary::finalize },
            { _( "Recipe groups" ), &recipe_group::check },
            { _( "Martial arts" ), &finialize_martial_arts },
            { _( "NPC classes" ), &npc_class::finalize_all },
            { _( "Missions" ), &mission_type::finalize },
            { _( "Behaviors" ), &behavior::finalize },
            { _( "Harvest lists" ), &harvest_list::finalize_all },
            { _( "Anatomies" ), &anatomy::finalize_all },
            { _( "Mutations" ), &mutation_branch::finalize },
            { _( "Achievements" ), &achievement::finalize },
            { _( "Localization" ), &l10n_data::load_mod_catalogues },
#if defined(TILES)
            { _( "Tileset" ), &load_tileset },
#endif
        }
    };
    for( const named_entry &e : entries ) {
        ui.add_entry( e.first );
    }
    ui.show();
    for( const named_entry &e : entries ) {
        e.second();
        ui.proceed();
    }
    check_consistency( ui );
    finalized = true;
}
References _, calculate_mapgen_weights(), recipe_group::check(), check_consistency(), achievement::finalize(), behavior::finalize(), constructions::finalize(), construction_sequences::finalize(), emit::finalize(), npc_factions::finalize(), mission_type::finalize(), monfactions::finalize(), mutation_branch::finalize(), overmap_terrains::finalize(), overmap_land_use_codes::finalize(), overmap_connections::finalize(), overmap_locations::finalize(), overmap_specials::finalize(), recipe_dictionary::finalize(), requirement_data::finalize(), trap::finalize(), vpart_info::finalize(), vehicle_prototype::finalize(), ammo_effects::finalize_all(), anatomy::finalize_all(), bionic_data::finalize_all(), body_part_type::finalize_all(), field_types::finalize_all(), json_flag::finalize_all(), harvest_list::finalize_all(), npc_class::finalize_all(), start_locations::finalize_all(), weather_types::finalize_all(), finalize_furn(), MonsterGenerator::finalize_mtypes(), finalized, MonsterGroupManager::FinalizeMonsterGroups(), finialize_martial_arts(), MonsterGenerator::generator(), item_controller, l10n_data::load_mod_catalogues(), zone_manager::reset_manager(), set_ter_ids(), and stream_cache.
Referenced by load_and_finalize_packs().
get_cached_stream()
shared_ptr_fast< std::istream > DynamicDataLoader::get_cached_stream (const std::string & path)
Get a possibly cached stream for deferred data loading.
If the cached stream is still in use by outside code, this returns a new stream to avoid conflict of stream cursor. The stream cursor is not reset if a cached stream is returned.
Definition at line 141 of file init.cpp.
{
    assert( !finalized && "Cannot open data file after finalization." );
    assert( stream_cache && "Stream cache is only available during finalization" );
    shared_ptr_fast<std::istringstream> cached = stream_cache->cache.get( path, nullptr );
    // Create a new stream if the file is not opened yet, or if some code is still
    // using the previous stream (in such case, `cached` and `stream_cache` have
    // two references to the stream, hence the test for > 2).
    if( !cached ) {
        cached = make_shared_fast<std::istringstream>( read_entire_file( path ) );
    } else if( cached.use_count() > 2 ) {
        cached = make_shared_fast<std::istringstream>( cached->str() );
    }
    stream_cache->cache.insert( 8, path, cached );
    return cached;
}
References finalized, read_entire_file(), and stream_cache.
Referenced by load_deferred(), mapgen_function_json_base::setup_common(), and throw_error_at_json_loc().
get_instance()
DynamicDataLoader & DynamicDataLoader::get_instance () static
Returns the single instance of this class.
Definition at line 119 of file init.cpp.
{
    static DynamicDataLoader theDynamicDataLoader;
    return theDynamicDataLoader;
}
Referenced by clear_loaded_data(), generic_factory< T >::finalize(), Item_factory::finalize(), mission_type::finalize(), recipe_dictionary::finalize(), vpart_info::finalize(), init::is_data_loaded(), load_and_finalize_packs(), init::load_soundpack_files(), game::load_static_data(), mapgen_function_json_base::setup_common(), and throw_error_at_json_loc().
initialize()
void DynamicDataLoader::initialize () private
Initializes type_function_map.
Definition at line 243 of file init.cpp.
{
    // all of the applicable types that can be loaded, along with their loading functions
    // Add to this as needed with new StaticFunctionAccessors or new ClassFunctionAccessors for new applicable types
    // Static Function Access
    add( "WORLD_OPTION", &load_world_option );
    add( "EXTERNAL_OPTION", &load_external_option );
    add( "json_flag", &json_flag::load_all );
    add( "fault", &fault::load_fault );
    add( "field_type", &field_types::load );
    add( "weather_type", &weather_types::load );
    add( "ammo_effect", &ammo_effects::load );
    add( "emit", &emit::load_emit );
    add( "activity_type", &activity_type::load );
    add( "vitamin", &vitamin::load_vitamin );
    add( "material", &materials::load );
    add( "bionic", &bionic_data::load_bionic );
    add( "profession", &profession::load_profession );
    add( "profession_item_substitutions", &profession::load_item_substitutions );
    add( "skill", &Skill::load_skill );
    add( "skill_display_type", &SkillDisplayType::load );
    add( "dream", &dreams::load );
    add( "mutation_category", &mutation_category_trait::load );
    add( "mutation_type", &load_mutation_type );
    add( "mutation", &mutation_branch::load_trait );
    add( "furniture", &load_furniture );
    add( "terrain", &load_terrain );
    add( "monstergroup", &MonsterGroupManager::LoadMonsterGroup );
    add( "MONSTER_BLACKLIST", &MonsterGroupManager::LoadMonsterBlacklist );
    add( "MONSTER_WHITELIST", &MonsterGroupManager::LoadMonsterWhitelist );
    add( "speech", &load_speech );
    add( "ammunition_type", &ammunition_type::load_ammunition_type );
    add( "start_location", &start_locations::load );
    add( "scenario", &scenario::load_scenario );
    add( "SCENARIO_BLACKLIST", &scen_blacklist::load_scen_blacklist );
    add( "skill_boost", &skill_boost::load_boost );
    add( "enchantment", &enchantment::load_enchantment );
    add( "hit_range", &Creature::load_hit_range );
    add( "scent_type", &scent_type::load_scent_type );
    add( "disease_type", &disease_type::load_disease_type );
    add( "ascii_art", &ascii_art::load_ascii_art );
    // json/colors.json would be listed here, but it's loaded before the others (see init_colors())
    // Non Static Function Access
    add( "snippet", []( const JsonObject & jo ) {
        SNIPPET.load_snippet( jo );
    } );
    add( "item_group", []( const JsonObject & jo ) {
        item_controller->load_item_group( jo );
    } );
    add( "trait_group", []( const JsonObject & jo ) {
        mutation_branch::load_trait_group( jo );
    } );
    add( "item_action", []( const JsonObject & jo ) {
        item_action_generator::generator().load_item_action( jo );
    } );
    add( "vehicle_part",  &vpart_info::load );
    add( "vehicle",  &vehicle_prototype::load );
    add( "vehicle_group",  &VehicleGroup::load );
    add( "vehicle_placement",  &VehiclePlacement::load );
    add( "vehicle_spawn",  &VehicleSpawn::load );
    add( "requirement", []( const JsonObject & jo ) {
        requirement_data::load_requirement( jo );
    } );
    add( "trap", &trap::load_trap );
    add( "AMMO", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_ammo( jo, src );
    } );
    add( "GUN", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_gun( jo, src );
    } );
    add( "ARMOR", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_armor( jo, src );
    } );
    add( "PET_ARMOR", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_pet_armor( jo, src );
    } );
    add( "TOOL", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_tool( jo, src );
    } );
    add( "TOOLMOD", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_toolmod( jo, src );
    } );
    add( "TOOL_ARMOR", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_tool_armor( jo, src );
    } );
    add( "BOOK", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_book( jo, src );
    } );
    add( "COMESTIBLE", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_comestible( jo, src );
    } );
    add( "CONTAINER", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_container( jo, src );
    } );
    add( "ENGINE", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_engine( jo, src );
    } );
    add( "WHEEL", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_wheel( jo, src );
    } );
    add( "FUEL", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_fuel( jo, src );
    } );
    add( "GUNMOD", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_gunmod( jo, src );
    } );
    add( "MAGAZINE", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_magazine( jo, src );
    } );
    add( "BATTERY", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_battery( jo, src );
    } );
    add( "GENERIC", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_generic( jo, src );
    } );
    add( "BIONIC_ITEM", []( const JsonObject & jo, const std::string & src ) {
        item_controller->load_bionic( jo, src );
    } );
    add( "ITEM_CATEGORY", &item_category::load_item_cat );
    add( "MIGRATION", []( const JsonObject & jo ) {
        item_controller->load_migration( jo );
    } );
    add( "charge_removal_blacklist", charge_removal_blacklist::load );
    add( "to_cbc_migration", to_cbc_migration::load );
    add( "MONSTER", []( const JsonObject & jo, const std::string & src ) {
        MonsterGenerator::generator().load_monster( jo, src );
    } );
    add( "SPECIES", []( const JsonObject & jo, const std::string & src ) {
        MonsterGenerator::generator().load_species( jo, src );
    } );
    add( "LOOT_ZONE", &zone_type::load_zones );
    add( "monster_adjustment", &load_monster_adjustment );
    add( "recipe_category", &load_recipe_category );
    add( "recipe",  &recipe_dictionary::load_recipe );
    add( "uncraft", &recipe_dictionary::load_uncraft );
    add( "recipe_group",  &recipe_group::load );
    add( "tool_quality", &quality::load_static );
    add( "technique", &load_technique );
    add( "weapon_category", &weapon_category::load_weapon_categories );
    add( "martial_art", &load_martial_art );
    add( "effect_type", &load_effect_type );
    add( "obsolete_terrain", &overmap::load_obsolete_terrains );
    add( "overmap_terrain", &overmap_terrains::load );
    add( "construction_category", &construction_categories::load );
    add( "construction_group", &construction_groups::load );
    add( "construction_sequence", &construction_sequences::load );
    add( "construction", &constructions::load );
    add( "mapgen", &load_mapgen );
    add( "overmap_land_use_code", &overmap_land_use_codes::load );
    add( "overmap_connection", &overmap_connections::load );
    add( "overmap_location", &overmap_locations::load );
    add( "overmap_special", &overmap_specials::load );
    add( "city_building", &city_buildings::load );
    add( "map_extra", &MapExtras::load );
    add( "region_settings", &load_region_settings );
    add( "region_overlay", &load_region_overlay );
    add( "ITEM_BLACKLIST", []( const JsonObject & jo ) {
        item_controller->load_item_blacklist( jo );
    } );
    add( "TRAIT_BLACKLIST", []( const JsonObject & jo ) {
        mutation_branch::load_trait_blacklist( jo );
    } );
    // loaded earlier.
    add( "colordef", &load_ignored_type );
    // mod information, ignored, handled by the mod manager
    add( "MOD_INFO", &load_ignored_type );
    add( "faction", &faction_template::load );
    add( "npc", &npc_template::load );
    add( "npc_class", &npc_class::load_npc_class );
    add( "talk_topic", &load_talk_topic );
    add( "behavior", &behavior::load_behavior );
    add( "MONSTER_FACTION", &monfactions::load_monster_faction );
    add( "sound_effect", &sfx::load_sound_effects );
    add( "sound_effect_preload", &sfx::load_sound_effect_preload );
    add( "playlist", &sfx::load_playlist );
    add( "gate", &gates::load );
    add( "overlay_order", &load_overlay_ordering );
    add( "mission_definition", []( const JsonObject & jo, const std::string & src ) {
        mission_type::load_mission_type( jo, src );
    } );
    add( "harvest", []( const JsonObject & jo, const std::string & src ) {
        harvest_list::load( jo, src );
    } );
    add( "monster_attack", []( const JsonObject & jo, const std::string & src ) {
        MonsterGenerator::generator().load_monster_attack( jo, src );
    } );
    add( "palette", mapgen_palette::load );
    add( "rotatable_symbol", &rotatable_symbols::load );
    add( "body_part", &body_part_type::load_bp );
    add( "anatomy", &anatomy::load_anatomy );
    add( "morale_type", &morale_type_data::load_type );
    add( "SPELL", &spell_type::load_spell );
    add( "clothing_mod", &clothing_mods::load );
    add( "ter_furn_transform", &ter_furn_transform::load_transform );
    add( "event_transformation", &event_transformation::load_transformation );
    add( "event_statistic", &event_statistic::load_statistic );
    add( "score", &score::load_score );
    add( "achievement", &achievement::load_achievement );
#if defined(TILES)
    add( "mod_tileset", &load_mod_tileset );
#else
    // No TILES - no tilesets
    add( "mod_tileset", &load_ignored_type );
#endif
}
References add(), item_action_generator::generator(), MonsterGenerator::generator(), item_controller, activity_type::load(), dreams::load(), charge_removal_blacklist::load(), to_cbc_migration::load(), vehicle_prototype::load(), VehicleGroup::load(), VehiclePlacement::load(), VehicleSpawn::load(), ammo_effects::load(), clothing_mods::load(), constructions::load(), construction_categories::load(), construction_groups::load(), construction_sequences::load(), field_types::load(), gates::load(), MapExtras::load(), mapgen_palette::load(), materials::load(), overmap_terrains::load(), overmap_land_use_codes::load(), overmap_connections::load(), overmap_locations::load(), overmap_specials::load(), city_buildings::load(), recipe_group::load(), rotatable_symbols::load(), start_locations::load(), vpart_info::load(), weather_types::load(), harvest_list::load(), faction_template::load(), mutation_category_trait::load(), npc_template::load(), SkillDisplayType::load(), achievement::load_achievement(), json_flag::load_all(), ammunition_type::load_ammunition_type(), anatomy::load_anatomy(), ascii_art::load_ascii_art(), behavior::load_behavior(), bionic_data::load_bionic(), skill_boost::load_boost(), body_part_type::load_bp(), disease_type::load_disease_type(), load_effect_type(), emit::load_emit(), enchantment::load_enchantment(), load_external_option(), fault::load_fault(), load_furniture(), Creature::load_hit_range(), load_ignored_type(), item_action_generator::load_item_action(), item_category::load_item_cat(), profession::load_item_substitutions(), load_mapgen(), load_martial_art(), mission_type::load_mission_type(), load_mod_tileset(), MonsterGenerator::load_monster(), load_monster_adjustment(), MonsterGenerator::load_monster_attack(), monfactions::load_monster_faction(), load_mutation_type(), npc_class::load_npc_class(), overmap::load_obsolete_terrains(), load_overlay_ordering(), sfx::load_playlist(), profession::load_profession(), recipe_dictionary::load_recipe(), load_recipe_category(), load_region_overlay(), load_region_settings(), requirement_data::load_requirement(), scen_blacklist::load_scen_blacklist(), scenario::load_scenario(), scent_type::load_scent_type(), score::load_score(), Skill::load_skill(), snippet_library::load_snippet(), sfx::load_sound_effect_preload(), sfx::load_sound_effects(), MonsterGenerator::load_species(), load_speech(), spell_type::load_spell(), quality::load_static(), event_statistic::load_statistic(), load_talk_topic(), load_technique(), load_terrain(), mutation_branch::load_trait(), mutation_branch::load_trait_blacklist(), mutation_branch::load_trait_group(), ter_furn_transform::load_transform(), event_transformation::load_transformation(), trap::load_trap(), morale_type_data::load_type(), recipe_dictionary::load_uncraft(), vitamin::load_vitamin(), weapon_category::load_weapon_categories(), load_world_option(), zone_type::load_zones(), MonsterGroupManager::LoadMonsterBlacklist(), MonsterGroupManager::LoadMonsterGroup(), MonsterGroupManager::LoadMonsterWhitelist(), and SNIPPET.
Referenced by DynamicDataLoader().
is_data_finalized()
bool DynamicDataLoader::is_data_finalized () const inline
Returns whether the data is finalized and ready to be utilized.
Definition at line 164 of file init.h.
{
            return finalized;
        }
References finalized.
Referenced by init::is_data_loaded().
load_all_from_json()
void DynamicDataLoader::load_all_from_json (JsonIn & jsin, const std::string & src, loading_ui & ui, const std::string & base_path, const std::string & full_path) private
Load all the types from that json data.
Parameters
jsin Might contain single object, or an array of objects. Each object must have a "type", that is part of the type_function_map
src String identifier for mod this data comes from
ui Finalization status display.
Exceptions
std::exception on all kind of errors.
Definition at line 508 of file init.cpp.
{
    // TEMPORARY until 0.G: Remove single object support for consistency
    if( jsin.test_object() ) {
        // find type and dispatch single object
        JsonObject jo = jsin.get_object();
        load_object( jo, src, base_path, full_path );
        jo.finish();
        // if there's anything else in the file, it's an error.
        jsin.eat_whitespace();
        if( jsin.good() ) {
            jsin.error( string_format( "expected single-object file but found '%c'", jsin.peek() ) );
        }
    } else if( jsin.test_array() ) {
        jsin.start_array();
        // find type and dispatch each object until array close
        while( !jsin.end_array() ) {
            JsonObject jo = jsin.get_object();
            load_object( jo, src, base_path, full_path );
            jo.finish();
        }
    } else {
        // not an object or an array?
        jsin.error( "expected object or array" );
    }
    inp_mngr.pump_events();
}
References PATH_INFO::base_path(), JsonIn::eat_whitespace(), JsonIn::end_array(), JsonIn::error(), JsonObject::finish(), JsonIn::get_object(), JsonIn::good(), inp_mngr, load_object(), JsonIn::peek(), input_manager::pump_events(), JsonIn::start_array(), string_format(), JsonIn::test_array(), and JsonIn::test_object().
Referenced by load_data_from_path().
load_data_from_path()
void DynamicDataLoader::load_data_from_path (const std::string & path, const std::string & src, loading_ui & ui)
Load all data from json files located in the path (recursive).
Parameters
path Either a folder (recursively load all files with the extension .json), or a file (load only that file, don't check extension).
src String identifier for mod this data comes from
ui Finalization status display.
Exceptions
std::exception on all kind of errors.
Definition at line 466 of file init.cpp.
{
    assert( !finalized && "Can't load additional data after finalization.  Must be unloaded first." );
    // We assume that each folder is consistent in itself,
    // and all the previously loaded folders.
    // E.g. the core might provide a vpart "frame-x"
    // the first loaded mode might provide a vehicle that uses that frame
    // But not the other way round.
    // get a list of all files in the directory
    str_vec files = get_files_from_path( ".json", path, true, true );
    if( files.empty() ) {
        std::ifstream tmp( path.c_str(), std::ios::in );
        if( tmp ) {
            // path is actually a file, don't checking the extension,
            // assume we want to load this file anyway
            files.push_back( path );
        }
    }
    // iterate over each file
    for( auto &files_i : files ) {
        const std::string &file = files_i;
        // open the file as a stream
        cata_ifstream infile = std::move( cata_ifstream().mode( cata_ios_mode::binary ).open( file ) );
        // and stuff it into ram
        std::istringstream iss(
            std::string(
                ( std::istreambuf_iterator<char>( *infile ) ),
                std::istreambuf_iterator<char>()
            )
        );
        try {
            // parse it
            JsonIn jsin( iss, file );
            load_all_from_json( jsin, src, ui, path, file );
        } catch( const JsonError &err ) {
            throw std::runtime_error( err.what() );
        }
    }
}
References binary, file, finalized, get_files_from_path(), load_all_from_json(), avatar_action::move(), and open().
Referenced by load_and_finalize_packs(), and init::load_soundpack_files().
load_deferred()
void DynamicDataLoader::load_deferred (deferred_json & data)
Loads and then removes entries from.
Parameters
data
Definition at line 158 of file init.cpp.
{
    while( !data.empty() ) {
        const size_t n = data.size();
        auto it = data.begin();
        for( size_t idx = 0; idx != n; ++idx ) {
            if( !it->first.path ) {
                debugmsg( "JSON source location has null path, data may load incorrectly" );
            } else {
                try {
                    shared_ptr_fast<std::istream> stream = get_cached_stream( *it->first.path );
                    JsonIn jsin( *stream, it->first );
                    JsonObject jo = jsin.get_object();
                    load_object( jo, it->second );
                } catch( const JsonError &err ) {
                    debugmsg( "(json-error)\n%s", err.what() );
                }
            }
            ++it;
            inp_mngr.pump_events();
        }
        data.erase( data.begin(), it );
        if( data.size() == n ) {
            for( const auto &elem : data ) {
                if( !elem.first.path ) {
                    debugmsg( "JSON source location has null path when reporting circular dependency" );
                } else {
                    try {
                        shared_ptr_fast<std::istream> stream = get_cached_stream( *it->first.path );
                        JsonIn jsin( *stream, elem.first );
                        jsin.error( "JSON contains circular dependency, this object is discarded" );
                    } catch( const JsonError &err ) {
                        debugmsg( "(json-error)\n%s", err.what() );
                    }
                }
                inp_mngr.pump_events();
            }
            data.clear();
            return; // made no progress on this cycle so abort
        }
    }
}
References debugmsg, JsonIn::error(), get_cached_stream(), JsonIn::get_object(), inp_mngr, load_object(), and input_manager::pump_events().
Referenced by generic_factory< T >::finalize(), Item_factory::finalize(), mission_type::finalize(), recipe_dictionary::finalize(), and vpart_info::finalize().
load_object()
void DynamicDataLoader::load_object (const JsonObject & jo, const std::string & src, const std::string & base_path = std::string(), const std::string & full_path = std::string()) private
Load a single object from a json object.
Parameters
jo The json object to load the C++-object from.
src String identifier for mod this data comes from
Exceptions
std::exception on all kind of errors.
Definition at line 125 of file init.cpp.
{
    const std::string type = jo.get_string( "type" );
    const t_type_function_map::iterator it = type_function_map.find( type );
    if( it == type_function_map.end() ) {
        jo.throw_error( "unrecognized JSON object", "type" );
    }
    it->second( jo, src, base_path, full_path );
}
References PATH_INFO::base_path(), JsonObject::get_string(), JsonObject::throw_error(), type, and type_function_map.
Referenced by load_all_from_json(), and load_deferred().
unload_data()
void DynamicDataLoader::unload_data ()
Deletes and unloads all the data previously loaded with load_data_from_path.
Definition at line 537 of file init.cpp.
{
    finalized = false;
    achievement::reset();
    activity_type::reset();
    ammo_effects::reset();
    ammunition_type::reset();
    anatomy::reset();
    ascii_art::reset();
    behavior::reset();
    bionic_data::reset();
    body_part_type::reset();
    charge_removal_blacklist::reset();
    clear_techniques_and_martial_arts();
    clothing_mods::reset();
    construction_categories::reset();
    construction_groups::reset();
    construction_sequences::reset();
    constructions::reset();
    Creature::reset_hit_range();
    disease_type::reset();
    dreams::clear();
    emit::reset();
    enchantment::reset();
    event_statistic::reset();
    event_transformation::reset();
    faction_template::reset();
    fault::reset();
    field_types::reset();
    gates::reset();
    harvest_list::reset();
    item_action_generator::generator().reset();
    item_controller->reset();
    json_flag::reset();
    MapExtras::reset();
    mapgen_palette::reset();
    materials::reset();
    mission_type::reset();
    monfactions::reset();
    MonsterGenerator::generator().reset();
    MonsterGroupManager::ClearMonsterGroups();
    morale_type_data::reset();
    mutation_branch::reset_all();
    mutation_category_trait::reset();
    mutations_category.clear();
    npc_class::reset_npc_classes();
    npc_template::reset();
    overmap_connections::reset();
    overmap_land_use_codes::reset();
    overmap_locations::reset();
    overmap_specials::reset();
    overmap_terrains::reset();
    overmap::reset_obsolete_terrains();
    profession::reset();
    quality::reset();
    recipe_dictionary::reset();
    recipe_group::reset();
    requirement_data::reset();
    reset_effect_types();
    reset_furn_ter();
    reset_mapgens();
    reset_monster_adjustment();
    reset_mutation_types();
    reset_overlay_ordering();
    reset_recipe_categories();
    reset_region_settings();
    reset_scenarios_blacklist();
    reset_speech();
    rotatable_symbols::reset();
    scenario::reset();
    scent_type::reset();
    score::reset();
    skill_boost::reset();
    Skill::reset();
    SkillDisplayType::reset();
    SNIPPET.clear_snippets();
    spell_type::reset_all();
    start_locations::reset();
    ter_furn_transform::reset_all();
    to_cbc_migration::reset();
    trap::reset();
    unload_talk_topics();
    vehicle_prototype::reset();
    VehicleGroup::reset();
    VehiclePlacement::reset();
    VehicleSpawn::reset();
    vitamin::reset();
    vpart_info::reset();
    weapon_category::reset();
    weather_types::reset();
    zone_type::reset_zones();
    l10n_data::unload_mod_catalogues();
#if defined(TILES)
    reset_mod_tileset();
#endif
}
References dreams::clear(), snippet_library::clear_snippets(), clear_techniques_and_martial_arts(), MonsterGroupManager::ClearMonsterGroups(), finalized, item_action_generator::generator(), MonsterGenerator::generator(), item_controller, mutations_category, achievement::reset(), activity_type::reset(), ammunition_type::reset(), ammo_effects::reset(), anatomy::reset(), ascii_art::reset(), behavior::reset(), bionic_data::reset(), body_part_type::reset(), clothing_mods::reset(), constructions::reset(), construction_categories::reset(), construction_groups::reset(), construction_sequences::reset(), disease_type::reset(), emit::reset(), event_transformation::reset(), event_statistic::reset(), score::reset(), faction_template::reset(), fault::reset(), field_types::reset(), json_flag::reset(), gates::reset(), harvest_list::reset(), item_action_generator::reset(), enchantment::reset(), MapExtras::reset(), mapgen_palette::reset(), weapon_category::reset(), materials::reset(), mission_type::reset(), monfactions::reset(), MonsterGenerator::reset(), morale_type_data::reset(), mutation_category_trait::reset(), npc_template::reset(), overmap_terrains::reset(), overmap_land_use_codes::reset(), overmap_connections::reset(), overmap_locations::reset(), overmap_specials::reset(), profession::reset(), recipe_dictionary::reset(), recipe_group::reset(), quality::reset(), requirement_data::reset(), rotatable_symbols::reset(), charge_removal_blacklist::reset(), to_cbc_migration::reset(), scenario::reset(), scent_type::reset(), Skill::reset(), SkillDisplayType::reset(), skill_boost::reset(), start_locations::reset(), trap::reset(), vpart_info::reset(), vehicle_prototype::reset(), VehicleGroup::reset(), VehiclePlacement::reset(), VehicleSpawn::reset(), vitamin::reset(), weather_types::reset(), spell_type::reset_all(), ter_furn_transform::reset_all(), mutation_branch::reset_all(), reset_effect_types(), reset_furn_ter(), Creature::reset_hit_range(), reset_mapgens(), reset_mod_tileset(), reset_monster_adjustment(), reset_mutation_types(), npc_class::reset_npc_classes(), overmap::reset_obsolete_terrains(), reset_overlay_ordering(), reset_recipe_categories(), reset_region_settings(), reset_scenarios_blacklist(), reset_speech(), zone_type::reset_zones(), SNIPPET, l10n_data::unload_mod_catalogues(), and unload_talk_topics().
Referenced by clear_loaded_data().
Member Data Documentation
finalized
bool DynamicDataLoader::finalized = false private
Definition at line 71 of file init.h.
Referenced by finalize_loaded_data(), get_cached_stream(), is_data_finalized(), load_data_from_path(), and unload_data().
stream_cache
std::unique_ptr<cached_streams> DynamicDataLoader::stream_cache private
Definition at line 74 of file init.h.
Referenced by finalize_loaded_data(), and get_cached_stream().
type_function_map
t_type_function_map DynamicDataLoader::type_function_map private
Maps the type string (coming from json) to the functor that loads that kind of object from json.
Definition at line 80 of file init.h.
Referenced by add(), and load_object().
The documentation for this class was generated from the following files:
src/init.h
src/init.cpp