Cataclysm BN: cauterize_actor Class Reference
cauterize_actor Class Reference
Cauterizes a wounded/masochistic survivor.
#include <iuse_actor.h>
Public Member Functions
cauterize_actor (const std::string &type="cauterize")
~cauterize_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Static Public Member Functions
static bool cauterize_effect (player &p, item &it, bool force)
Public Attributes
bool flame = true
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Cauterizes a wounded/masochistic survivor.
Definition at line 649 of file iuse_actor.h.
Constructor & Destructor Documentation
cauterize_actor()
cauterize_actor::cauterize_actor (const std::string & type = "cauterize") inline
Definition at line 657 of file iuse_actor.h.
: iuse_actor(type) {}
~cauterize_actor()
cauterize_actor::~cauterize_actor () override default
Member Function Documentation
can_use()
ret_val< bool > cauterize_actor::can_use (const Character & p, const item & it, bool , const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 1972 of file iuse_actor.cpp.
{
    if( !p.has_effect( effect_bite ) &&
        !p.has_effect( effect_bleed ) &&
        !p.has_trait( trait_MASOCHIST ) &&
        !p.has_trait( trait_MASOCHIST_MED ) &&
        !p.has_trait( trait_CENOBITE ) ) {
        return ret_val<bool>::make_failure(
                   _( "You are not bleeding or bitten, there is no need to cauterize yourself." ) );
    }
    if( p.is_mounted() ) {
        return ret_val<bool>::make_failure( _( "You cannot cauterize while mounted." ) );
    }
    if( flame ) {
        if( !p.has_charges( itype_fire, 4 ) ) {
            return ret_val<bool>::make_failure(
                       _( "You need a source of flame (4 charges worth) before you can cauterize yourself." ) );
        }
    } else {
        if( !it.units_sufficient( p ) ) {
            return ret_val<bool>::make_failure( _( "You need at least %d charges to cauterize wounds." ),
                                                it.ammo_required() );
        }
    }
    if( p.is_underwater() ) {
        return ret_val<bool>::make_failure( _( "You can't do that while underwater." ) );
    }
    return ret_val<bool>::make_success();
}
References _, item::ammo_required(), effect_bite, effect_bleed, flame, Character::has_charges(), Creature::has_effect(), Character::has_trait(), Character::is_mounted(), Creature::is_underwater(), itype_fire, ret_val< T >::make_failure(), ret_val< T >::make_success(), trait_CENOBITE, trait_MASOCHIST, trait_MASOCHIST_MED, and item::units_sufficient().
cauterize_effect()
bool cauterize_actor::cauterize_effect (player & p, item & it, bool force) static
Definition at line 1911 of file iuse_actor.cpp.
{
    // TODO: Make this less hacky
    static const heal_actor dummy = prepare_dummy();
    hp_part hpart = dummy.use_healing_item( p, p, it, force );
    if( hpart != num_hp_parts ) {
        p.add_msg_if_player( m_neutral, _( "You cauterize yourself." ) );
        if( !( p.has_trait( trait_NOPAIN ) ) ) {
            p.mod_pain( 15 );
            p.add_msg_if_player( m_bad, _( "It hurts like hell!" ) );
        } else {
            p.add_msg_if_player( m_neutral, _( "It itches a little." ) );
        }
        const body_part bp = player::hp_to_bp( hpart );
        if( p.has_effect( effect_bite, bp ) ) {
            p.add_effect( effect_bite, 260_minutes, bp );
        }
        p.moves = 0;
        return true;
    }
    return false;
}
References _, Creature::add_effect(), player::add_msg_if_player(), effect_bite, Creature::has_effect(), Character::has_trait(), Character::hp_to_bp(), m_bad, m_neutral, Character::mod_pain(), Creature::moves, num_hp_parts, prepare_dummy(), trait_NOPAIN, and heal_actor::use_healing_item().
Referenced by use().
clone()
std::unique_ptr< iuse_actor > cauterize_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1894 of file iuse_actor.cpp.
{
    return std::make_unique<cauterize_actor>( *this );
}
Referenced by Item_factory::finalize_pre().
load()
void cauterize_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1888 of file iuse_actor.cpp.
{
    assign( obj, "cost", cost );
    assign( obj, "flame", flame );
}
References assign(), iuse_actor::cost, and flame.
use()
int cauterize_actor::use (player & p, item & it, bool t, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 1936 of file iuse_actor.cpp.
{
    if( t ) {
        return 0;
    }
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    bool has_disease = p.has_effect( effect_bite ) || p.has_effect( effect_bleed );
    bool did_cauterize = false;
    if( has_disease ) {
        did_cauterize = cauterize_effect( p, it, false );
    } else {
        const bool can_have_fun = p.has_trait( trait_MASOCHIST ) || p.has_trait( trait_MASOCHIST_MED ) ||
                                  p.has_trait( trait_CENOBITE );
        if( can_have_fun && query_yn( _( "Cauterize yourself for fun?" ) ) ) {
            did_cauterize = cauterize_effect( p, it, true );
        }
    }
    if( !did_cauterize ) {
        return 0;
    }
    if( flame ) {
        p.use_charges( itype_fire, 4 );
        return 0;
    } else {
        return cost >= 0 ? cost : it.ammo_required();
    }
}
References _, player::add_msg_if_player(), item::ammo_required(), cauterize_effect(), iuse_actor::cost, effect_bite, effect_bleed, flame, Creature::has_effect(), Character::has_trait(), Character::is_mounted(), itype_fire, m_info, query_yn(), trait_CENOBITE, trait_MASOCHIST, trait_MASOCHIST_MED, and Character::use_charges().
Member Data Documentation
flame
bool cauterize_actor::flame = true
Definition at line 653 of file iuse_actor.h.
Referenced by can_use(), Item_factory::finalize_pre(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp