Cataclysm BN: field_entry Class Reference
field_entry Class Reference
An active or passive effect existing on a tile.
#include <field.h>
Public Member Functions
field_entry ()
field_entry (const field_type_id &t, const int i, const time_duration &a)
nc_color color () const
std::string symbol () const
int move_cost () const
int extra_radiation_min () const
int extra_radiation_max () const
int radiation_hurt_damage_min () const
int radiation_hurt_damage_max () const
std::string radiation_hurt_message () const
int intensity_upgrade_chance () const
time_duration intensity_upgrade_duration () const
int monster_spawn_chance () const
int monster_spawn_count () const
int monster_spawn_radius () const
mongroup_id monster_spawn_group () const
float light_emitted () const
float local_light_override () const
float translucency () const
bool is_transparent () const
int convection_temperature_mod () const
field_type_id get_field_type () const
field_type_id set_field_type (const field_type_id &new_type)
int get_max_field_intensity () const
int get_field_intensity () const
int set_field_intensity (int new_intensity)
time_duration get_field_age () const
time_duration set_field_age (const time_duration &new_age)
Sets age to the given value.
time_duration mod_field_age (const time_duration &mod_age)
Adds given value to age.
bool is_dangerous () const
std::string name () const
bool is_field_alive ()
bool gas_can_spread ()
time_duration get_underwater_age_speedup () const
int get_gas_absorption_factor () const
bool decays_on_actualize () const
std::vector< field_effect > field_effects () const
Private Attributes
field_type_id type
int intensity
time_duration age
bool is_alive
Detailed Description
An active or passive effect existing on a tile.
Each effect can vary in intensity and age (usually used as a time to live).
Definition at line 19 of file field.h.
Constructor & Destructor Documentation
field_entry() [1/2]
field_entry::field_entry () inline
Definition at line 22 of file field.h.
: type(fd_null), intensity(1), age(0_turns), is_alive(false) { }
field_entry() [2/2]
field_entry::field_entry (const field_type_id & t, const int i, const time_duration & a) inline
Definition at line 23 of file field.h.
                                                                                   : type( t ),
            intensity( i ), age( a ), is_alive( true ) { }
Member Function Documentation
color()
nc_color field_entry::color () const
Definition at line 94 of file field.cpp.
{
    return type.obj().get_color( intensity - 1 );
}
References field_type::get_color(), intensity, int_id< T >::obj(), and type.
Referenced by colorized_field_description_at(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), game::print_fields_info(), and editmap::update_view_with_help().
convection_temperature_mod()
int field_entry::convection_temperature_mod () const
Definition at line 89 of file field.cpp.
{
    return type.obj().get_convection_temperature_mod( intensity - 1 );
}
References field_type::get_convection_temperature_mod(), intensity, int_id< T >::obj(), and type.
decays_on_actualize()
bool field_entry::decays_on_actualize () const inline
Definition at line 105 of file field.h.
{
            return type.obj().accelerated_decay;
        }
References field_type::accelerated_decay, int_id< T >::obj(), and type.
Referenced by map::drop_fields().
extra_radiation_max()
int field_entry::extra_radiation_max () const
Definition at line 19 of file field.cpp.
{
    return type.obj().get_extra_radiation_max( intensity - 1 );
}
References field_type::get_extra_radiation_max(), intensity, int_id< T >::obj(), and type.
Referenced by map::player_in_field(), and map::process_fields_in_submap().
extra_radiation_min()
int field_entry::extra_radiation_min () const
Definition at line 14 of file field.cpp.
{
    return type.obj().get_extra_radiation_min( intensity - 1 );
}
References field_type::get_extra_radiation_min(), intensity, int_id< T >::obj(), and type.
Referenced by map::player_in_field(), and map::process_fields_in_submap().
field_effects()
std::vector< field_effect > field_entry::field_effects () const
Definition at line 294 of file field.cpp.
{
    return type->get_intensity_level( intensity - 1 ).field_effects;
}
References field_intensity_level::field_effects, field_type::get_intensity_level(), intensity, and type.
Referenced by map::creature_in_field().
gas_can_spread()
bool field_entry::gas_can_spread () inline
Definition at line 93 of file field.h.
{
            return is_field_alive() && type.obj().phase == GAS && type.obj().percent_spread > 0;
        }
References GAS, is_field_alive(), int_id< T >::obj(), field_type::percent_spread, field_type::phase, and type.
Referenced by map::process_fields_in_submap().
get_field_age()
time_duration field_entry::get_field_age () const
Returns
age.
Definition at line 133 of file field.cpp.
{
    return age;
}
References age.
Referenced by map::decay_fields_and_scent(), map::drop_fields(), map::gas_spread_to(), map::get_field_age(), mod_field_age(), map::process_fields_in_submap(), map::spread_gas(), submap::store(), and editmap::update_view_with_help().
get_field_intensity()
int field_entry::get_field_intensity () const
Definition at line 121 of file field.cpp.
{
    return intensity;
}
References intensity.
Referenced by map::burn_body_part(), map::drop_fields(), editmap::edit_fld(), map::gas_can_spread_to(), map::gas_spread_to(), maptile_field_intensity(), map::monster_in_field(), map::player_in_field(), map::process_fields_in_submap(), relic_funcs::process_recharge_entry(), map::set_field_intensity(), map::shoot(), map::spread_gas(), submap::store(), editmap::update_fmenu_entry(), map::update_pathfinding_cache(), and editmap::update_view_with_help().
get_field_type()
field_type_id field_entry::get_field_type () const
Definition at line 105 of file field.cpp.
{
    return type;
}
References type.
Referenced by map::creature_in_field(), map::decay_fields_and_scent(), map::drop_fields(), map::gas_can_spread_to(), map::gas_spread_to(), Creature::is_dangerous_field(), map::monster_in_field(), map::player_in_field(), map::process_fields_in_submap(), map::spread_gas(), submap::store(), map::update_pathfinding_cache(), and editmap::update_view_with_help().
get_gas_absorption_factor()
int field_entry::get_gas_absorption_factor () const inline
Definition at line 101 of file field.h.
{
            return type.obj().gas_absorption_factor;
        }
References field_type::gas_absorption_factor, int_id< T >::obj(), and type.
Referenced by iuse::gasmask().
get_max_field_intensity()
int field_entry::get_max_field_intensity () const
Definition at line 116 of file field.cpp.
{
    return type.obj().get_max_intensity();
}
References field_type::get_max_intensity(), int_id< T >::obj(), and type.
Referenced by set_field_intensity().
get_underwater_age_speedup()
time_duration field_entry::get_underwater_age_speedup () const inline
Definition at line 97 of file field.h.
{
            return type.obj().underwater_age_speedup;
        }
References int_id< T >::obj(), type, and field_type::underwater_age_speedup.
Referenced by map::process_fields_in_submap().
intensity_upgrade_chance()
int field_entry::intensity_upgrade_chance () const
Definition at line 39 of file field.cpp.
{
    return type.obj().get_intensity_upgrade_chance( intensity - 1 );
}
References field_type::get_intensity_upgrade_chance(), intensity, int_id< T >::obj(), and type.
Referenced by map::process_fields_in_submap().
intensity_upgrade_duration()
time_duration field_entry::intensity_upgrade_duration () const
Definition at line 44 of file field.cpp.
{
    return type.obj().get_intensity_upgrade_duration( intensity - 1 );
}
References field_type::get_intensity_upgrade_duration(), intensity, int_id< T >::obj(), and type.
Referenced by map::process_fields_in_submap().
is_dangerous()
bool field_entry::is_dangerous () const inline
Definition at line 78 of file field.h.
{
            return type.obj().is_dangerous();
        }
References field_type::is_dangerous(), int_id< T >::obj(), and type.
Referenced by advanced_inv_area::init(), Creature::is_dangerous_field(), and character_funcs::pick_safe_adjacent_tile().
is_field_alive()
bool field_entry::is_field_alive () inline
Definition at line 89 of file field.h.
{
            return is_alive;
        }
References is_alive.
Referenced by map::creature_in_field(), gas_can_spread(), map::monster_in_field(), map::player_in_field(), and map::process_fields_in_submap().
is_transparent()
bool field_entry::is_transparent () const
Definition at line 84 of file field.cpp.
{
    return type.obj().get_transparent( intensity - 1 );
}
References field_type::get_transparent(), intensity, int_id< T >::obj(), and type.
Referenced by map::build_transparency_cache().
light_emitted()
float field_entry::light_emitted () const
Definition at line 69 of file field.cpp.
{
    return type.obj().get_light_emitted( intensity - 1 );
}
References field_type::get_light_emitted(), intensity, int_id< T >::obj(), and type.
Referenced by map::generate_lightmap().
local_light_override()
float field_entry::local_light_override () const
Definition at line 74 of file field.cpp.
{
    return type.obj().get_local_light_override( intensity - 1 );
}
References field_type::get_local_light_override(), intensity, int_id< T >::obj(), and type.
Referenced by map::generate_lightmap().
mod_field_age()
time_duration field_entry::mod_field_age (const time_duration & mod_age) inline
Adds given value to age.
Returns
New value of age.
Definition at line 73 of file field.h.
{
            return set_field_age( get_field_age() + mod_age );
        }
References get_field_age(), and set_field_age().
Referenced by map::process_fields_in_submap().
monster_spawn_chance()
int field_entry::monster_spawn_chance () const
Definition at line 49 of file field.cpp.
{
    return type.obj().get_monster_spawn_chance( intensity - 1 );
}
References field_type::get_monster_spawn_chance(), intensity, int_id< T >::obj(), and type.
Referenced by map::process_fields_in_submap().
monster_spawn_count()
int field_entry::monster_spawn_count () const
Definition at line 54 of file field.cpp.
{
    return type.obj().get_monster_spawn_count( intensity - 1 );
}
References field_type::get_monster_spawn_count(), intensity, int_id< T >::obj(), and type.
Referenced by map::process_fields_in_submap().
monster_spawn_group()
mongroup_id field_entry::monster_spawn_group () const
Definition at line 64 of file field.cpp.
{
    return type.obj().get_monster_spawn_group( intensity - 1 );
}
References field_type::get_monster_spawn_group(), intensity, int_id< T >::obj(), and type.
Referenced by map::process_fields_in_submap().
monster_spawn_radius()
int field_entry::monster_spawn_radius () const
Definition at line 59 of file field.cpp.
{
    return type.obj().get_monster_spawn_radius( intensity - 1 );
}
References field_type::get_monster_spawn_radius(), intensity, int_id< T >::obj(), and type.
Referenced by map::process_fields_in_submap().
move_cost()
int field_entry::move_cost () const
Definition at line 9 of file field.cpp.
{
    return type.obj().get_move_cost( intensity - 1 );
}
References field_type::get_move_cost(), intensity, int_id< T >::obj(), and type.
name()
std::string field_entry::name () const inline
Definition at line 84 of file field.h.
{
            return type.obj().get_name( intensity - 1 );
        }
References field_type::get_name(), intensity, int_id< T >::obj(), and type.
Referenced by colorized_field_description_at(), map::player_in_field(), game::print_fields_info(), and editmap::update_view_with_help().
radiation_hurt_damage_max()
int field_entry::radiation_hurt_damage_max () const
Definition at line 29 of file field.cpp.
{
    return type.obj().get_radiation_hurt_damage_max( intensity - 1 );
}
References field_type::get_radiation_hurt_damage_max(), intensity, int_id< T >::obj(), and type.
Referenced by map::player_in_field().
radiation_hurt_damage_min()
int field_entry::radiation_hurt_damage_min () const
Definition at line 24 of file field.cpp.
{
    return type.obj().get_radiation_hurt_damage_min( intensity - 1 );
}
References field_type::get_radiation_hurt_damage_min(), intensity, int_id< T >::obj(), and type.
Referenced by map::player_in_field().
radiation_hurt_message()
std::string field_entry::radiation_hurt_message () const
Definition at line 34 of file field.cpp.
{
    return type.obj().get_radiation_hurt_message( intensity - 1 );
}
References field_type::get_radiation_hurt_message(), intensity, int_id< T >::obj(), and type.
Referenced by map::player_in_field().
set_field_age()
time_duration field_entry::set_field_age (const time_duration & new_age)
Sets age to the given value.
Returns
New value of age.
Definition at line 138 of file field.cpp.
{
    return age = new_age;
}
References age.
Referenced by map::decay_fields_and_scent(), map::gas_spread_to(), mod_field_age(), map::process_fields_in_submap(), and map::spread_gas().
set_field_intensity()
int field_entry::set_field_intensity (int new_intensity)
Definition at line 126 of file field.cpp.
{
    is_alive = new_intensity > 0;
    return intensity = std::max( std::min( new_intensity, get_max_field_intensity() ), 1 );
}
References get_max_field_intensity(), intensity, and is_alive.
Referenced by map::gas_spread_to(), map::monster_in_field(), map::player_in_field(), map::process_fields_in_submap(), and map::set_field_intensity().
set_field_type()
field_type_id field_entry::set_field_type (const field_type_id & new_type)
Definition at line 110 of file field.cpp.
{
    type = new_type;
    return type;
}
References type.
symbol()
std::string field_entry::symbol () const
Definition at line 99 of file field.cpp.
{
    return type.obj().get_symbol( intensity - 1 );
}
References field_type::get_symbol(), intensity, int_id< T >::obj(), and type.
Referenced by editmap_hilight::draw(), and editmap::draw_main_ui_overlay().
translucency()
float field_entry::translucency () const
Definition at line 79 of file field.cpp.
{
    return type.obj().get_translucency( intensity - 1 );
}
References field_type::get_translucency(), intensity, int_id< T >::obj(), and type.
Referenced by map::build_transparency_cache().
Member Data Documentation
age
time_duration field_entry::age private
Definition at line 117 of file field.h.
Referenced by get_field_age(), and set_field_age().
intensity
int field_entry::intensity private
Definition at line 115 of file field.h.
Referenced by color(), convection_temperature_mod(), extra_radiation_max(), extra_radiation_min(), field_effects(), get_field_intensity(), intensity_upgrade_chance(), intensity_upgrade_duration(), is_transparent(), light_emitted(), local_light_override(), monster_spawn_chance(), monster_spawn_count(), monster_spawn_group(), monster_spawn_radius(), move_cost(), name(), radiation_hurt_damage_max(), radiation_hurt_damage_min(), radiation_hurt_message(), set_field_intensity(), symbol(), and translucency().
is_alive
bool field_entry::is_alive private
Definition at line 119 of file field.h.
Referenced by is_field_alive(), and set_field_intensity().
type
field_type_id field_entry::type private
Definition at line 113 of file field.h.
Referenced by color(), convection_temperature_mod(), decays_on_actualize(), extra_radiation_max(), extra_radiation_min(), field_effects(), gas_can_spread(), get_field_type(), get_gas_absorption_factor(), get_max_field_intensity(), get_underwater_age_speedup(), intensity_upgrade_chance(), intensity_upgrade_duration(), is_dangerous(), is_transparent(), light_emitted(), local_light_override(), monster_spawn_chance(), monster_spawn_count(), monster_spawn_group(), monster_spawn_radius(), move_cost(), name(), radiation_hurt_damage_max(), radiation_hurt_damage_min(), radiation_hurt_message(), set_field_type(), symbol(), and translucency().
The documentation for this class was generated from the following files:
src/field.h
src/field.cpp