Cataclysm BN: dynamic_format_arg_store< Context > Class Template Reference
dynamic_format_arg_store< Context > Class Template Reference
\rst A dynamic version of fmt::format_arg_store.
#include <fmtlib_core.h>
Classes
struct need_copy
Public Member Functions
template<typename T >
void push_back (const T &arg)
\rst Adds an argument into the dynamic store for later passing to a formatting function.
template<typename T >
void push_back (std::reference_wrapper< T > arg)
template<typename T >
void push_back (const detail::named_arg< char_type, T > &arg)
Adds named argument into the dynamic store for later passing to a formatting function.
void clear ()
Erase all elements from the store.
void reserve (size_t new_cap, size_t new_cap_named)
\rst Reserves space to store at least new_cap arguments including new_cap_named* named arguments.
Private Types
using char_type = typename Context::char_type
template<typename T >
using stored_type = conditional_t< detail::is_string< T >::value, std::basic_string< char_type >, T >
Private Member Functions
unsigned long long get_types () const
const basic_format_arg< Context > * data () const
template<typename T >
void emplace_arg (const T &arg)
template<typename T >
void emplace_arg (const detail::named_arg< char_type, T > &arg)
Private Attributes
std::vector< basic_format_arg< Context > > data_
std::vector< detail::named_arg_info< char_type > > named_info_
detail::dynamic_arg_list dynamic_args_
Friends
class basic_format_args< Context >
Detailed Description
template<typename Context>
class dynamic_format_arg_store< Context >
\rst A dynamic version of fmt::format_arg_store.
It's equipped with a storage to potentially temporary objects which lifetimes could be shorter than the format arguments object.
It can be implicitly converted into ~fmtbasic_format_args for passing into type-erased formatting functions such as ~fmtvformat. \endrst
Definition at line 1877 of file fmtlib_core.h.
Member Typedef Documentation
char_type
template<typename Context > using dynamic_format_arg_store< Context >::char_type = typename Context::char_type private
Definition at line 1884 of file fmtlib_core.h.
stored_type
template<typename Context > template<typename T > using dynamic_format_arg_store< Context >::stored_type = conditional_t<detail::is_string<T>::value, std::basic_string<char_type>, T> private
Definition at line 1901 of file fmtlib_core.h.
Member Function Documentation
clear()
template<typename Context > void dynamic_format_arg_store< Context >::clear () inline
Erase all elements from the store.
Definition at line 2020 of file fmtlib_core.h.
                     {
            data_.clear();
            named_info_.clear();
            dynamic_args_ = detail::dynamic_arg_list();
        }
data()
template<typename Context > const basic_format_arg< Context > * dynamic_format_arg_store< Context >::data () const inline private
Definition at line 1921 of file fmtlib_core.h.
{
            return named_info_.empty() ? data_.data() : data_.data() + 1;
        }
emplace_arg() [1/2]
template<typename Context > template<typename T > void dynamic_format_arg_store< Context >::emplace_arg (const detail::named_arg< char_type, T > & arg) inline private
Definition at line 1930 of file fmtlib_core.h.
{
            if( named_info_.empty() ) {
                constexpr const detail::named_arg_info<char_type> *zero_ptr{nullptr};
                data_.insert( data_.begin(), {zero_ptr, 0} );
            }
            data_.emplace_back( detail::make_arg<Context>( detail::unwrap( arg.value ) ) );
            auto pop_one = []( std::vector<basic_format_arg<Context>> *data ) {
                data->pop_back();
            };
            std::unique_ptr<std::vector<basic_format_arg<Context>>, decltype( pop_one )>
                    guard{&data_, pop_one};
            named_info_.push_back( {arg.name, static_cast<int>( data_.size() - 2u )} );
            data_[0].value_.named_args = {named_info_.data(), named_info_.size()};
            guard.release();
        }
References arg(), and detail::unwrap().
emplace_arg() [2/2]
template<typename Context > template<typename T > void dynamic_format_arg_store< Context >::emplace_arg (const T & arg) inline private
Definition at line 1925 of file fmtlib_core.h.
{
            data_.emplace_back( detail::make_arg<Context>( arg ) );
        }
References arg().
get_types()
template<typename Context > unsigned long long dynamic_format_arg_store< Context >::get_types () const inline private
Definition at line 1914 of file fmtlib_core.h.
{
            return detail::is_unpacked_bit | data_.size() |
                   ( named_info_.empty()
                     ? 0ULL
                     : static_cast<unsigned long long>( detail::has_named_args_bit ) );
        }
References detail::has_named_args_bit, and detail::is_unpacked_bit.
push_back() [1/3]
template<typename Context > template<typename T > void dynamic_format_arg_store< Context >::push_back (const detail::named_arg< char_type, T > & arg) inline
Adds named argument into the dynamic store for later passing to a formatting function.
std::reference_wrapper is supported to avoid copying of the argument.
Definition at line 2008 of file fmtlib_core.h.
{
            const char_type *arg_name =
                dynamic_args_.push<std::basic_string<char_type>>( arg.name ).c_str();
            if( detail::const_check( need_copy<T>::value ) ) {
                emplace_arg(
                    fmt::arg( arg_name, dynamic_args_.push<stored_type<T>>( arg.value ) ) );
            } else {
                emplace_arg( fmt::arg( arg_name, arg.value ) );
            }
        }
References arg(), detail::const_check(), and detail::dynamic_arg_list::push().
push_back() [2/3]
template<typename Context > template<typename T > void dynamic_format_arg_store< Context >::push_back (const T & arg) inline
\rst Adds an argument into the dynamic store for later passing to a formatting function.
Note that custom types and string types (but not string views) are copied into the store dynamically allocating memory if necessary.
Example**::
fmt::dynamic_format_arg_store<fmt::format_context> store; store.push_back(42); store.push_back("abc"); store.push_back(1.5f); std::string result = fmt::vformat("{} and {} and {}", store); \endrst
Definition at line 1964 of file fmtlib_core.h.
{
            if( detail::const_check( need_copy<T>::value ) ) {
                emplace_arg( dynamic_args_.push<stored_type<T>>( arg ) );
            } else {
                emplace_arg( detail::unwrap( arg ) );
            }
        }
References arg(), detail::const_check(), detail::dynamic_arg_list::push(), and detail::unwrap().
push_back() [3/3]
template<typename Context > template<typename T > void dynamic_format_arg_store< Context >::push_back (std::reference_wrapper< T > arg) inline
      \rst
      Adds a reference to the argument into the dynamic store for later passing to
      a formatting function. Supports named arguments wrapped in
      ``std::reference_wrapper`` via ``std::ref()``/``std::cref()``.
        Example**::
        fmt::dynamic_format_arg_store<fmt::format_context> store;
        char str[] = "1234567890";
        store.push_back(std::cref(str));
        int a1_val{42};
        auto a1 = fmt::arg("a1_", a1_val);
        store.push_back(std::cref(a1));
Changing str affects the output but only for string and custom types. str[0] = 'X';
std::string result = fmt::vformat("{} and {a1_}"); assert(result == "X234567890 and 42"); \endrst
Definition at line 1994 of file fmtlib_core.h.
{
            static_assert(
                detail::is_named_arg<typename std::remove_cv<T>::type>::value ||
                need_copy<T>::value,
                "objects of built-in types and string views are always copied" );
            emplace_arg( arg.get() );
        }
References arg().
reserve()
template<typename Context > void dynamic_format_arg_store< Context >::reserve (size_t new_cap, size_t new_cap_named) inline
\rst Reserves space to store at least new_cap arguments including new_cap_named* named arguments.
\endrst
Definition at line 2032 of file fmtlib_core.h.
{
            FMT_ASSERT( new_cap >= new_cap_named,
                        "Set of arguments includes set of named arguments" );
            data_.reserve( new_cap );
            named_info_.reserve( new_cap_named );
        }
References FMT_ASSERT.
Friends And Related Function Documentation
basic_format_args< Context >
template<typename Context > friend class basic_format_args< Context > friend
Definition at line 1910 of file fmtlib_core.h.
Member Data Documentation
data_
template<typename Context > std::vector<basic_format_arg<Context> > dynamic_format_arg_store< Context >::data_ private
Definition at line 1905 of file fmtlib_core.h.
dynamic_args_
template<typename Context > detail::dynamic_arg_list dynamic_format_arg_store< Context >::dynamic_args_ private
Definition at line 1910 of file fmtlib_core.h.
named_info_
template<typename Context > std::vector<detail::named_arg_info<char_type> > dynamic_format_arg_store< Context >::named_info_ private
Definition at line 1906 of file fmtlib_core.h.
The documentation for this class was generated from the following file:
src/fmtlib_core.h