Cataclysm BN: detail::specs_checker< Handler > Class Template Reference
detail::specs_checker< Handler > Class Template Reference
#include <fmtlib_format.h>
Public Member Functions
FMT_CONSTEXPR specs_checker (const Handler &handler, detail::type arg_type)
FMT_CONSTEXPR specs_checker (const specs_checker &other)
FMT_CONSTEXPR void on_align (align_t align)
FMT_CONSTEXPR void on_plus ()
FMT_CONSTEXPR void on_minus ()
FMT_CONSTEXPR void on_space ()
FMT_CONSTEXPR void on_hash ()
FMT_CONSTEXPR void on_zero ()
FMT_CONSTEXPR void end_precision ()
Private Member Functions
FMT_CONSTEXPR Handler & error_handler ()
Private Attributes
numeric_specs_checker< Handler > checker_
Detailed Description
template<typename Handler>
class detail::specs_checker< Handler >
Definition at line 2867 of file fmtlib_format.h.
Constructor & Destructor Documentation
specs_checker() [1/2]
template<typename Handler > FMT_CONSTEXPR detail::specs_checker< Handler >::specs_checker (const Handler & handler, detail::type arg_type) inline
Definition at line 2878 of file fmtlib_format.h.
            : Handler( handler ), checker_( error_handler(), arg_type ) {}
specs_checker() [2/2]
template<typename Handler > FMT_CONSTEXPR detail::specs_checker< Handler >::specs_checker (const specs_checker< Handler > & other) inline
Definition at line 2881 of file fmtlib_format.h.
            : Handler( other ), checker_( error_handler(), other.arg_type_ ) {}
Member Function Documentation
end_precision()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::end_precision () inline
Definition at line 2916 of file fmtlib_format.h.
{
            checker_.check_precision();
        }
References detail::numeric_specs_checker< ErrorHandler >::check_precision().
Referenced by dynamic_formatter< Char >::format().
error_handler()
template<typename Handler > FMT_CONSTEXPR Handler & detail::specs_checker< Handler >::error_handler () inline private
Definition at line 2873 of file fmtlib_format.h.
{
            return *this;
        }
on_align()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::on_align (align_t align) inline
Definition at line 2884 of file fmtlib_format.h.
{
            if( align == align::numeric ) {
                checker_.require_numeric_argument();
            }
            Handler::on_align( align );
        }
References align::numeric, and detail::numeric_specs_checker< ErrorHandler >::require_numeric_argument().
Referenced by dynamic_formatter< Char >::format().
on_hash()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::on_hash () inline
Definition at line 2906 of file fmtlib_format.h.
{
            checker_.require_numeric_argument();
            Handler::on_hash();
        }
References detail::numeric_specs_checker< ErrorHandler >::require_numeric_argument().
Referenced by dynamic_formatter< Char >::format().
on_minus()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::on_minus () inline
Definition at line 2896 of file fmtlib_format.h.
{
            checker_.check_sign();
            Handler::on_minus();
        }
References detail::numeric_specs_checker< ErrorHandler >::check_sign().
Referenced by dynamic_formatter< Char >::format().
on_plus()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::on_plus () inline
Definition at line 2891 of file fmtlib_format.h.
{
            checker_.check_sign();
            Handler::on_plus();
        }
References detail::numeric_specs_checker< ErrorHandler >::check_sign().
Referenced by dynamic_formatter< Char >::format().
on_space()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::on_space () inline
Definition at line 2901 of file fmtlib_format.h.
{
            checker_.check_sign();
            Handler::on_space();
        }
References detail::numeric_specs_checker< ErrorHandler >::check_sign().
Referenced by dynamic_formatter< Char >::format().
on_zero()
template<typename Handler > FMT_CONSTEXPR void detail::specs_checker< Handler >::on_zero () inline
Definition at line 2911 of file fmtlib_format.h.
{
            checker_.require_numeric_argument();
            Handler::on_zero();
        }
References detail::numeric_specs_checker< ErrorHandler >::require_numeric_argument().
Member Data Documentation
checker_
template<typename Handler > numeric_specs_checker<Handler> detail::specs_checker< Handler >::checker_ private
Definition at line 2870 of file fmtlib_format.h.
The documentation for this class was generated from the following file:
src/fmtlib_format.h