Cataclysm BN: detail::counting_buffer< T > Class Template Reference
detail::counting_buffer< T > Class Template Reference final
#include <fmtlib_core.h>
Public Member Functions
counting_buffer ()
size_t count ()
Public Member Functions inherited from detail::buffer< char >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
char * begin () FMT_NOEXCEPT
const char * begin () const FMT_NOEXCEPT
char * end () FMT_NOEXCEPT
const char * end () const FMT_NOEXCEPT
size_t size () const FMT_NOEXCEPT
Returns the size of this buffer.
size_t capacity () const FMT_NOEXCEPT
Returns the capacity of this buffer.
char * data () FMT_NOEXCEPT
Returns a pointer to the buffer data.
const char * data () const FMT_NOEXCEPT
Returns a pointer to the buffer data.
void clear ()
Clears this buffer.
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const char &value)
void append (const U *begin, const U *end)
Appends data to the end of the buffer.
char & operator[] (I index)
const char & operator[] (I index) const
Protected Member Functions
void grow (size_t) final FMT_OVERRIDE
Increases the buffer capacity to hold at least capacity elements.
Protected Member Functions inherited from detail::buffer< char >
buffer (size_t sz) FMT_NOEXCEPT
buffer (char *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
~buffer ()=default
void set (char *buf_data, size_t buf_capacity) FMT_NOEXCEPT
Sets the buffer data and capacity.
Private Types
enum { buffer_size = 256 }
Private Attributes
T data_ [buffer_size]
size_t count_ = 0
Additional Inherited Members
Public Types inherited from detail::buffer< char >
using value_type = char
using const_reference = const char &
Detailed Description
template<typename T = char>
class detail::counting_buffer< T >
Definition at line 918 of file fmtlib_core.h.
Member Enumeration Documentation
anonymous enum
template<typename T = char> anonymous enum private
Enumerator
buffer_size
Definition at line 921 of file fmtlib_core.h.
{ buffer_size = 256 };
Constructor & Destructor Documentation
counting_buffer()
template<typename T = char> detail::counting_buffer< T >::counting_buffer () inline
Definition at line 936 of file fmtlib_core.h.
: buffer<T>(data_, 0, buffer_size) {}
Member Function Documentation
count()
template<typename T = char> size_t detail::counting_buffer< T >::count () inline
Definition at line 938 of file fmtlib_core.h.
                       {
            return count_ + this->size();
        }
References detail::counting_buffer< T >::count_, and detail::buffer< char >::size().
Referenced by formatted_size().
grow()
template<typename T = char> void detail::counting_buffer< T >::grow (size_t capacity) inline final protected virtual
Increases the buffer capacity to hold at least capacity elements.
Implements detail::buffer< char >.
Definition at line 927 of file fmtlib_core.h.
{
            if( this->size() != buffer_size ) {
                return;
            }
            count_ += this->size();
            this->clear();
        }
References detail::counting_buffer< T >::buffer_size, detail::buffer< char >::clear(), and detail::buffer< char >::size().
Member Data Documentation
count_
template<typename T = char> size_t detail::counting_buffer< T >::count_ = 0 private
Definition at line 923 of file fmtlib_core.h.
Referenced by detail::counting_buffer< T >::count().
data_
template<typename T = char> T detail::counting_buffer< T >::data_[buffer_size] private
Definition at line 922 of file fmtlib_core.h.
The documentation for this class was generated from the following file:
src/fmtlib_core.h