Cataclysm BN: spell Class Reference
spell Class Reference
#include <magic.h>
Public Member Functions
spell ()=default
spell (spell_id sp, int xp=0)
void set_message (const translation &msg)
int exp_to_next_level () const
std::string exp_progress () const
int xp () const
void gain_exp (int nxp)
void set_exp (int nxp)
int casting_exp (const Character &guy) const
float exp_modifier (const Character &guy) const
void gain_level ()
void gain_levels (int gains)
void set_level (int nlevel)
bool is_max_level () const
int get_max_level () const
int field_intensity () const
int damage () const
dealt_damage_instance get_dealt_damage_instance () const
damage_instance get_damage_instance () const
int aoe () const
int range () const
int energy_cost (const Character &guy) const
int duration () const
time_duration duration_turns () const
float spell_fail (const Character &guy) const
std::string colorized_fail_percent (const Character &guy) const
int casting_time (const Character &guy) const
bool can_cast (const Character &guy) const
bool can_learn (const Character &guy) const
bool is_valid () const
bool bp_is_affected (body_part bp) const
bool has_flag (const spell_flag &flag) const
bool is_spell_class (const trait_id &mid) const
bool in_aoe (const tripoint &source, const tripoint &target) const
spell_id id () const
trait_id spell_class () const
skill_id skill () const
std::string effect () const
std::string effect_data () const
vproto_id summon_vehicle_id () const
std::string name () const
std::string description () const
std::string message () const
std::string energy_string () const
std::string energy_cost_string (const Character &guy) const
std::string energy_cur_string (const Character &guy) const
std::string enumerate_targets () const
std::string list_targeted_monster_names () const
std::string damage_string () const
std::string aoe_string () const
std::string duration_string () const
energy_type energy_source () const
nc_color damage_type_color () const
std::string damage_type_string () const
int get_level () const
int get_difficulty () const
void create_field (const tripoint &at) const
void make_sound (const tripoint &target) const
void make_sound (const tripoint &target, int loudness) const
int heal (const tripoint &target) const
void cast_spell_effect (Creature &source, const tripoint &target) const
void cast_all_effects (Creature &source, const tripoint &target) const
bool is_target_in_range (const Creature &caster, const tripoint &p) const
bool is_valid_target (const Creature &caster, const tripoint &p) const
bool is_valid_target (valid_target t) const
bool is_valid_effect_target (valid_target t) const
bool target_by_monster_id (const tripoint &p) const
cata::optional< tripoint > random_valid_target (const Creature &caster, const tripoint &caster_pos) const
Private Member Functions
damage_type dmg_type () const
int min_leveled_damage () const
int min_leveled_aoe () const
int min_leveled_duration () const
Private Attributes
spell_id type
int experience = 0
translation alt_message
Friends
class spell_events
Detailed Description
Definition at line 285 of file magic.h.
Constructor & Destructor Documentation
spell() [1/2]
spell::spell () default
spell() [2/2]
spell::spell (spell_id sp, int xp = 0)
Definition at line 446 of file magic.cpp.
                                  :
    type( sp ),
    experience( xp )
{}
Member Function Documentation
aoe()
int spell::aoe () const
Definition at line 518 of file magic.cpp.
{
    const int leveled_aoe = min_leveled_aoe();
    if( has_flag( spell_flag::RANDOM_AOE ) ) {
        return rng( std::min( leveled_aoe, type->max_aoe ), std::max( leveled_aoe, type->max_aoe ) );
    } else {
        if( type->max_aoe >= type->min_aoe ) {
            return std::min( leveled_aoe, type->max_aoe );
        } else {
            return std::max( leveled_aoe, type->max_aoe );
        }
    }
}
References has_flag(), spell_type::max_aoe, spell_type::min_aoe, min_leveled_aoe(), RANDOM_AOE, rng(), and type.
Referenced by aoe_string(), spell_effect::area_pull(), spell_effect::area_push(), spell_effect::bash(), calculate_spell_effect_area(), spell_effect::charm_monster(), spellcasting_callback::draw_spell_info(), spell_effect::explosion(), in_aoe(), spell_effect::map_area(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), target_ui::panel_spell_info(), target_ui::set_cursor_pos(), spell_effect::teleport_random(), spell_effect::transform_blast(), and spell_effect::vomit().
aoe_string()
std::string spell::aoe_string () const
Definition at line 542 of file magic.cpp.
{
    if( has_flag( spell_flag::RANDOM_AOE ) ) {
        return string_format( "%d-%d", min_leveled_aoe(), type->max_aoe );
    } else {
        return string_format( "%d", aoe() );
    }
}
References aoe(), has_flag(), spell_type::max_aoe, min_leveled_aoe(), RANDOM_AOE, string_format(), and type.
Referenced by spellcasting_callback::draw_spell_info(), and target_ui::panel_spell_info().
bp_is_affected()
bool spell::bp_is_affected (body_part bp) const
Definition at line 892 of file magic.cpp.
{
    return type->affected_bps.count( convert_bp( bp ) );
}
References spell_type::affected_bps, convert_bp(), and type.
Referenced by add_effect_to_target().
can_cast()
bool spell::can_cast (const Character & guy) const
Definition at line 671 of file magic.cpp.
{
    switch( type->energy_source ) {
        case mana_energy:
            return guy.magic->available_mana() >= energy_cost( guy );
        case stamina_energy:
            return guy.get_stamina() >= energy_cost( guy );
        case hp_energy: {
            for( const std::pair<const bodypart_str_id, bodypart> &elem : guy.get_body() ) {
                if( energy_cost( guy ) < elem.second.get_hp_cur() ) {
                    return true;
                }
            }
            return false;
        }
        case bionic_energy:
            return guy.get_power_level() >= units::from_kilojoule( energy_cost( guy ) );
        case fatigue_energy:
            return guy.get_fatigue() < fatigue_levels::exhausted;
        case none_energy:
        default:
            return true;
    }
}
References bionic_energy, energy_cost(), spell_type::energy_source, exhausted, fatigue_energy, units::from_kilojoule(), Creature::get_body(), Character::get_fatigue(), Character::get_power_level(), Character::get_stamina(), hp_energy, Character::magic, mana_energy, none_energy, stamina_energy, and type.
Referenced by cast_spell(), spellcasting_callback::draw_spell_info(), and target_ui::run().
can_learn()
bool spell::can_learn (const Character & guy) const
Definition at line 623 of file magic.cpp.
{
    if( type->spell_class == trait_NONE ) {
        return true;
    }
    return guy.has_trait( type->spell_class );
}
References Character::has_trait(), spell_type::spell_class, trait_NONE, and type.
cast_all_effects()
void spell::cast_all_effects (Creature & source, const tripoint & target) const
Definition at line 1181 of file magic.cpp.
{
    if( has_flag( spell_flag::WONDER ) ) {
        const auto iter = type->additional_spells.begin();
        for( int num_spells = std::abs( damage() ); num_spells > 0; num_spells-- ) {
            if( type->additional_spells.empty() ) {
                debugmsg( "ERROR: %s has WONDER flag but no spells to choose from!", type->id.c_str() );
                return;
            }
            const int rand_spell = rng( 0, type->additional_spells.size() - 1 );
            spell sp = ( iter + rand_spell )->get_spell( get_level() );
            const bool _self = ( iter + rand_spell )->self;
            // This spell flag makes it so the message of the spell that's cast using this spell will be sent.
            // if a message is added to the casting spell, it will be sent as well.
            source.add_msg_if_player( sp.message() );
            if( sp.has_flag( RANDOM_TARGET ) ) {
                if( const cata::optional<tripoint> new_target = sp.random_valid_target( source,
                        _self ? source.pos() : target ) ) {
                    sp.cast_all_effects( source, *new_target );
                }
            } else {
                if( _self ) {
                    sp.cast_all_effects( source, source.pos() );
                } else {
                    sp.cast_all_effects( source, target );
                }
            }
        }
    } else {
        // first call the effect of the main spell
        cast_spell_effect( source, target );
        for( const fake_spell &extra_spell : type->additional_spells ) {
            spell sp = extra_spell.get_spell( get_level() );
            if( sp.has_flag( RANDOM_TARGET ) ) {
                if( const cata::optional<tripoint> new_target = sp.random_valid_target( source,
                        extra_spell.self ? source.pos() : target ) ) {
                    sp.cast_all_effects( source, *new_target );
                }
            } else {
                if( extra_spell.self ) {
                    sp.cast_all_effects( source, source.pos() );
                } else {
                    sp.cast_all_effects( source, target );
                }
            }
        }
    }
}
References Creature::add_msg_if_player(), spell_type::additional_spells, string_id< T >::c_str(), cast_all_effects(), cast_spell_effect(), damage(), debugmsg, get_level(), fake_spell::get_spell(), has_flag(), spell_type::id, message(), Creature::pos(), RANDOM_TARGET, random_valid_target(), rng(), fake_spell::self, type, and WONDER.
Referenced by enchantment::activate_passive(), mon_spellcasting_actor::call(), cast_all_effects(), enchantment::cast_enchantment_spell(), trapfunc::cast_spell(), and activity_handlers::spellcasting_finish().
cast_spell_effect()
void spell::cast_spell_effect (Creature & source, const tripoint & target) const
Definition at line 1176 of file magic.cpp.
{
    type->effect( *this, source, target );
}
References spell_type::effect, and type.
Referenced by cast_all_effects().
casting_exp()
int spell::casting_exp (const Character & guy) const
Definition at line 1082 of file magic.cpp.
{
    // the amount of xp you would get with no modifiers
    const int base_casting_xp = 75;
    return std::round( guy.adjust_for_focus( base_casting_xp * exp_modifier( guy ) ) );
}
References Character::adjust_for_focus(), and exp_modifier().
Referenced by activity_handlers::spellcasting_finish().
casting_time()
int spell::casting_time (const Character & guy) const
Definition at line 701 of file magic.cpp.
{
    // casting time in moves
    int casting_time = 0;
    if( type->base_casting_time < type->final_casting_time ) {
        casting_time = std::min( type->final_casting_time,
                                 static_cast<int>( std::round( type->base_casting_time + type->casting_time_increment *
                                         get_level() ) ) );
    } else if( type->base_casting_time > type->final_casting_time ) {
        casting_time = std::max( type->final_casting_time,
                                 static_cast<int>( std::round( type->base_casting_time + type->casting_time_increment *
                                         get_level() ) ) );
    } else {
        casting_time = type->base_casting_time;
    }
    if( !has_flag( spell_flag::NO_LEGS ) ) {
        // the first 20 points of encumbrance combined is ignored
        const int legs_encumb = std::max( 0, guy.encumb( bp_leg_l ) + guy.encumb( bp_leg_r ) - 20 );
        casting_time += legs_encumb * 3;
    }
    if( has_flag( spell_flag::SOMATIC ) ) {
        // the first 20 points of encumbrance combined is ignored
        const int arms_encumb = std::max( 0, guy.encumb( bp_arm_l ) + guy.encumb( bp_arm_r ) - 20 );
        casting_time += arms_encumb * 2;
    }
    return casting_time;
}
References spell_type::base_casting_time, bp_arm_l, bp_arm_r, bp_leg_l, bp_leg_r, casting_time(), spell_type::casting_time_increment, Character::encumb(), spell_type::final_casting_time, get_level(), has_flag(), NO_LEGS, SOMATIC, and type.
Referenced by cast_spell(), casting_time(), spellcasting_callback::draw_spell_info(), mon_spellcasting_actor::load_internal(), and cast_spell_actor::use().
colorized_fail_percent()
std::string spell::colorized_fail_percent (const Character & guy) const
Definition at line 782 of file magic.cpp.
{
    const float fail_fl = spell_fail( guy ) * 100.0f;
    std::string fail_str;
    fail_fl == 100.0f ? fail_str = _( "Too Difficult!" ) : fail_str = string_format( "%.1f %% %s",
                                   fail_fl, _( "Failure Chance" ) );
    nc_color color;
    if( fail_fl > 90.0f ) {
        color = c_magenta;
    } else if( fail_fl > 75.0f ) {
        color = c_red;
    } else if( fail_fl > 60.0f ) {
        color = c_light_red;
    } else if( fail_fl > 35.0f ) {
        color = c_yellow;
    } else if( fail_fl > 15.0f ) {
        color = c_green;
    } else {
        color = c_light_green;
    }
    return colorize( fail_str, color );
}
References _, c_green, c_light_green, c_light_red, c_magenta, c_red, c_yellow, color(), colorize(), spell_fail(), and string_format().
Referenced by spellcasting_callback::draw_spell_info(), and target_ui::panel_spell_info().
create_field()
void spell::create_field (const tripoint & at) const
Definition at line 897 of file magic.cpp.
{
    if( !type->field ) {
        return;
    }
    const int intensity = field_intensity() + rng( -type->field_intensity_variance * field_intensity(),
                          type->field_intensity_variance * field_intensity() );
    if( intensity <= 0 ) {
        return;
    }
    if( one_in( type->field_chance ) ) {
        map &here = get_map();
        field_entry *field = here.get_field( at, *type->field );
        if( field ) {
            field->set_field_intensity( field->get_field_intensity() + intensity );
        } else {
            here.add_field( at, *type->field, intensity, -duration_turns() );
        }
    }
}
References map::add_field(), duration_turns(), spell_type::field, spell_type::field_chance, field_intensity(), spell_type::field_intensity_variance, map::get_field(), get_map(), one_in(), rng(), and type.
Referenced by damage_targets().
damage()
int spell::damage () const
Definition at line 483 of file magic.cpp.
{
    const int leveled_damage = min_leveled_damage();
    if( has_flag( spell_flag::RANDOM_DAMAGE ) ) {
        return rng( std::min( leveled_damage, type->max_damage ), std::max( leveled_damage,
                    type->max_damage ) );
    } else {
        if( type->min_damage >= 0 || type->max_damage >= type->min_damage ) {
            return std::min( leveled_damage, type->max_damage );
        } else { // if it's negative, min and max work differently
            return std::max( leveled_damage, type->max_damage );
        }
    }
}
References has_flag(), spell_type::max_damage, spell_type::min_damage, min_leveled_damage(), RANDOM_DAMAGE, rng(), and type.
Referenced by spell_effect::bash(), cast_all_effects(), spell_effect::charm_monster(), damage_string(), damage_targets(), spellcasting_callback::draw_spell_info(), spell_effect::explosion(), get_damage_instance(), get_dealt_damage_instance(), heal(), make_sound(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), spell_effect::noise(), spell_effect::recover_energy(), target_ui::run(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), and spell_effect::transform_blast().
damage_string()
std::string spell::damage_string () const
Definition at line 499 of file magic.cpp.
{
    if( has_flag( spell_flag::RANDOM_DAMAGE ) ) {
        return string_format( "%d-%d", min_leveled_damage(), type->max_damage );
    } else {
        const int dmg = damage();
        if( dmg >= 0 ) {
            return string_format( "%d", dmg );
        } else {
            return string_format( "+%d", std::abs( dmg ) );
        }
    }
}
References damage(), has_flag(), spell_type::max_damage, min_leveled_damage(), RANDOM_DAMAGE, string_format(), and type.
Referenced by spellcasting_callback::draw_spell_info(), and target_ui::panel_spell_info().
damage_type_color()
nc_color spell::damage_type_color () const
Definition at line 995 of file magic.cpp.
{
    switch( dmg_type() ) {
        case DT_HEAT:
            return c_red;
        case DT_ACID:
            return c_light_green;
        case DT_BASH:
            return c_magenta;
        case DT_BIOLOGICAL:
            return c_green;
        case DT_COLD:
            return c_white;
        case DT_CUT:
            return c_light_gray;
        case DT_ELECTRIC:
            return c_light_blue;
        case DT_BULLET:
        /* fallthrough */
        case DT_STAB:
            return c_light_red;
        case DT_TRUE:
            return c_dark_gray;
        default:
            return c_black;
    }
}
References c_black, c_dark_gray, c_green, c_light_blue, c_light_gray, c_light_green, c_light_red, c_magenta, c_red, c_white, dmg_type(), DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_STAB, and DT_TRUE.
Referenced by spellcasting_callback::draw_spell_info(), and spell_effect_area().
damage_type_string()
std::string spell::damage_type_string () const
Definition at line 1023 of file magic.cpp.
{
    return name_by_dt( dmg_type() );
}
References dmg_type(), and name_by_dt().
Referenced by spellcasting_callback::draw_spell_info().
description()
std::string spell::description () const
Definition at line 990 of file magic.cpp.
{
    return type->description.translated();
}
References spell_type::description, translation::translated(), and type.
Referenced by spellcasting_callback::draw_spell_info(), target_ui::panel_spell_info(), and diary::spell_changes().
dmg_type()
damage_type spell::dmg_type () const private
Definition at line 1133 of file magic.cpp.
{
    return type->dmg_type;
}
References spell_type::dmg_type, and type.
Referenced by damage_type_color(), damage_type_string(), get_damage_instance(), and get_dealt_damage_instance().
duration()
int spell::duration () const
Definition at line 566 of file magic.cpp.
{
    const int leveled_duration = min_leveled_duration();
    if( has_flag( spell_flag::RANDOM_DURATION ) ) {
        return rng( std::min( leveled_duration, type->max_duration ), std::max( leveled_duration,
                    type->max_duration ) );
    } else {
        if( type->max_duration >= type->min_duration ) {
            return std::min( leveled_duration, type->max_duration );
        } else {
            return std::max( leveled_duration, type->max_duration );
        }
    }
}
References has_flag(), spell_type::max_duration, spell_type::min_duration, min_leveled_duration(), RANDOM_DURATION, rng(), and type.
Referenced by add_effect_to_target(), spell_effect::charm_monster(), spellcasting_callback::draw_spell_info(), duration_string(), and duration_turns().
duration_string()
std::string spell::duration_string () const
Definition at line 582 of file magic.cpp.
{
    if( has_flag( spell_flag::RANDOM_DURATION ) ) {
        return string_format( "%s - %s", moves_to_string( min_leveled_duration() ),
                              moves_to_string( type->max_duration ) );
    } else {
        return moves_to_string( duration() );
    }
}
References duration(), has_flag(), spell_type::max_duration, min_leveled_duration(), moves_to_string(), RANDOM_DURATION, string_format(), and type.
Referenced by spellcasting_callback::draw_spell_info().
duration_turns()
time_duration spell::duration_turns () const
Definition at line 592 of file magic.cpp.
{
    return 1_turns * duration() / 100;
}
References duration().
Referenced by create_field(), spell_effect::morale(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), spell_effect::spawn_summoned_vehicle(), and spell_effect::timed_event().
effect()
std::string spell::effect () const
Definition at line 935 of file magic.cpp.
{
    return type->effect_name;
}
References spell_type::effect_name, and type.
Referenced by calculate_spell_effect_area(), mon_spellcasting_actor::call(), spellcasting_callback::draw_spell_info(), enumerate_spell_data(), target_ui::panel_spell_info(), and target_ui::set_cursor_pos().
effect_data()
std::string spell::effect_data () const
Definition at line 1152 of file magic.cpp.
{
    return type->effect_str;
}
References spell_type::effect_str, and type.
Referenced by add_effect_to_target(), damage_targets(), spellcasting_callback::draw_spell_info(), spell_effect::morale(), spell_effect::mutate(), spell_effect::recover_energy(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), spell_effect::timed_event(), and spell_effect::transform_blast().
energy_cost()
int spell::energy_cost (const Character & guy) const
Definition at line 631 of file magic.cpp.
{
    int cost;
    if( type->base_energy_cost < type->final_energy_cost ) {
        cost = std::min( type->final_energy_cost,
                         static_cast<int>( std::round( type->base_energy_cost + type->energy_increment * get_level() ) ) );
    } else if( type->base_energy_cost > type->final_energy_cost ) {
        cost = std::max( type->final_energy_cost,
                         static_cast<int>( std::round( type->base_energy_cost + type->energy_increment * get_level() ) ) );
    } else {
        cost = type->base_energy_cost;
    }
    if( !has_flag( spell_flag::NO_HANDS ) ) {
        // the first 10 points of combined encumbrance is ignored, but quickly adds up
        const int hands_encumb = std::max( 0, guy.encumb( bp_hand_l ) + guy.encumb( bp_hand_r ) - 10 );
        switch( type->energy_source ) {
            default:
                cost += 10 * hands_encumb;
                break;
            case hp_energy:
                cost += hands_encumb;
                break;
            case stamina_energy:
                cost += 100 * hands_encumb;
                break;
        }
    }
    return cost;
}
References spell_type::base_energy_cost, bp_hand_l, bp_hand_r, Character::encumb(), spell_type::energy_increment, spell_type::energy_source, spell_type::final_energy_cost, get_level(), has_flag(), hp_energy, NO_HANDS, stamina_energy, and type.
Referenced by can_cast(), energy_cost_string(), known_magic::has_enough_energy(), and activity_handlers::spellcasting_finish().
energy_cost_string()
std::string spell::energy_cost_string (const Character & guy) const
Definition at line 838 of file magic.cpp.
{
    if( energy_source() == none_energy ) {
        return _( "none" );
    }
    if( energy_source() == bionic_energy || energy_source() == mana_energy ) {
        return colorize( std::to_string( energy_cost( guy ) ), c_light_blue );
    }
    if( energy_source() == hp_energy ) {
        auto pair = get_hp_bar( energy_cost( guy ), guy.get_hp_max() / num_hp_parts );
        return colorize( pair.first, pair.second );
    }
    if( energy_source() == stamina_energy ) {
        auto pair = get_hp_bar( energy_cost( guy ), guy.get_stamina_max() );
        return colorize( pair.first, pair.second );
    }
    if( energy_source() == fatigue_energy ) {
        return colorize( std::to_string( energy_cost( guy ) ), c_cyan );
    }
    debugmsg( "ERROR: Spell %s has invalid energy source.", id().c_str() );
    return _( "error: energy_type" );
}
References _, bionic_energy, c_cyan, c_light_blue, colorize(), debugmsg, energy_cost(), energy_source(), fatigue_energy, get_hp_bar(), Creature::get_hp_max(), Character::get_stamina_max(), hp_energy, mana_energy, none_energy, num_hp_parts, stamina_energy, and to_string().
Referenced by spellcasting_callback::draw_spell_info(), and target_ui::panel_spell_info().
energy_cur_string()
std::string spell::energy_cur_string (const Character & guy) const
Definition at line 861 of file magic.cpp.
{
    if( energy_source() == none_energy ) {
        return _( "infinite" );
    }
    if( energy_source() == bionic_energy ) {
        return colorize( std::to_string( units::to_kilojoule( guy.get_power_level() ) ), c_light_blue );
    }
    if( energy_source() == mana_energy ) {
        return colorize( std::to_string( guy.magic->available_mana() ), c_light_blue );
    }
    if( energy_source() == stamina_energy ) {
        auto pair = get_hp_bar( guy.get_stamina(), guy.get_stamina_max() );
        return colorize( pair.first, pair.second );
    }
    if( energy_source() == hp_energy ) {
        return "";
    }
    if( energy_source() == fatigue_energy ) {
        const std::pair<std::string, nc_color> pair = guy.get_fatigue_description();
        return colorize( pair.first, pair.second );
    }
    debugmsg( "ERROR: Spell %s has invalid energy source.", id().c_str() );
    return _( "error: energy_type" );
}
References _, bionic_energy, c_light_blue, colorize(), debugmsg, energy_source(), fatigue_energy, Character::get_fatigue_description(), get_hp_bar(), Character::get_power_level(), Character::get_stamina(), Character::get_stamina_max(), hp_energy, Character::magic, mana_energy, none_energy, stamina_energy, units::to_kilojoule(), and to_string().
Referenced by spellcasting_callback::draw_spell_info(), and target_ui::panel_spell_info().
energy_source()
energy_type spell::energy_source () const
Definition at line 940 of file magic.cpp.
{
    return type->energy_source;
}
References spell_type::energy_source, and type.
Referenced by cast_spell(), spellcasting_callback::draw_spell_info(), energy_cost_string(), energy_cur_string(), known_magic::has_enough_energy(), target_ui::panel_spell_info(), and activity_handlers::spellcasting_finish().
energy_string()
std::string spell::energy_string () const
Definition at line 820 of file magic.cpp.
{
    switch( type->energy_source ) {
        case hp_energy:
            return _( "health" );
        case mana_energy:
            return _( "mana" );
        case stamina_energy:
            return _( "stamina" );
        case bionic_energy:
            return _( "bionic power" );
        case fatigue_energy:
            return _( "fatigue" );
        default:
            return "";
    }
}
References _, bionic_energy, spell_type::energy_source, fatigue_energy, hp_energy, mana_energy, stamina_energy, and type.
Referenced by cast_spell(), spellcasting_callback::draw_spell_info(), target_ui::panel_spell_info(), and target_ui::run().
enumerate_targets()
std::string spell::enumerate_targets () const
Definition at line 1090 of file magic.cpp.
{
    std::vector<std::string> all_valid_targets;
    int last_target = static_cast<int>( valid_target::_LAST );
    for( int i = 0; i < last_target; ++i ) {
        valid_target t = static_cast<valid_target>( i );
        if( is_valid_target( t ) && t != target_none ) {
            all_valid_targets.emplace_back( io::enum_to_string( t ) );
        }
    }
    if( all_valid_targets.size() == 1 ) {
        return all_valid_targets[0];
    }
    std::string ret;
    // TODO: if only we had a function to enumerate strings and concatenate them...
    for( auto iter = all_valid_targets.begin(); iter != all_valid_targets.end(); iter++ ) {
        if( iter + 1 == all_valid_targets.end() ) {
            ret = string_format( _( "%s and %s" ), ret, *iter );
        } else if( iter == all_valid_targets.begin() ) {
            ret = *iter;
        } else {
            ret = string_format( _( "%s, %s" ), ret, *iter );
        }
    }
    return ret;
}
References _, _LAST, io::enum_to_string(), is_valid_target(), cata::hash64_detail::ret, string_format(), and target_none.
Referenced by spellcasting_callback::draw_spell_info().
exp_modifier()
float spell::exp_modifier (const Character & guy) const
Definition at line 1073 of file magic.cpp.
{
    const float int_modifier = ( guy.get_int() - 8.0f ) / 8.0f;
    const float difficulty_modifier = get_difficulty() / 20.0f;
    const float spellcraft_modifier = guy.get_skill_level( skill() ) / 10.0f;
    return ( int_modifier + difficulty_modifier + spellcraft_modifier ) / 5.0f + 1.0f;
}
References get_difficulty(), Character::get_int(), Character::get_skill_level(), and skill().
Referenced by casting_exp(), magic_train(), and activity_handlers::study_spell_do_turn().
exp_progress()
std::string spell::exp_progress () const
Definition at line 1062 of file magic.cpp.
{
    const int level = get_level();
    const int this_level_xp = exp_for_level( level );
    const int next_level_xp = exp_for_level( level + 1 );
    const int denominator = next_level_xp - this_level_xp;
    const float progress = static_cast<float>( xp() - this_level_xp ) / std::max( 1.0f,
                           static_cast<float>( denominator ) );
    return string_format( "%i%%", clamp( static_cast<int>( std::round( progress * 100 ) ), 0, 99 ) );
}
References clamp(), exp_for_level(), get_level(), string_format(), and xp().
exp_to_next_level()
int spell::exp_to_next_level () const
Definition at line 1057 of file magic.cpp.
{
    return exp_for_level( get_level() + 1 ) - xp();
}
References exp_for_level(), get_level(), and xp().
Referenced by spellcasting_callback::draw_spell_info(), and gain_level().
field_intensity()
int spell::field_intensity () const
Definition at line 471 of file magic.cpp.
{
    return std::min( type->max_field_intensity,
                     static_cast<int>( type->min_field_intensity + std::round( get_level() *
                                       type->field_intensity_increment ) ) );
}
References spell_type::field_intensity_increment, get_level(), spell_type::max_field_intensity, spell_type::min_field_intensity, and type.
Referenced by create_field().
gain_exp()
void spell::gain_exp (int nxp)
Definition at line 810 of file magic.cpp.
{
    experience += nxp;
}
References experience.
Referenced by gain_level(), magic_train(), activity_handlers::spellcasting_finish(), and activity_handlers::study_spell_do_turn().
gain_level()
void spell::gain_level ()
Definition at line 597 of file magic.cpp.
{
    gain_exp( exp_to_next_level() );
}
References exp_to_next_level(), and gain_exp().
Referenced by gain_levels(), fake_spell::get_spell(), learn_spells(), known_magic::on_mutation_gain(), npc::randomize(), and activity_handlers::spellcasting_finish().
gain_levels()
void spell::gain_levels (int gains)
Definition at line 602 of file magic.cpp.
{
    if( gains < 1 ) {
        return;
    }
    for( int gained = 0; gained < gains && !is_max_level(); gained++ ) {
        gain_level();
    }
}
References gain_level(), and is_max_level().
Referenced by set_level().
get_damage_instance()
damage_instance spell::get_damage_instance () const
Definition at line 1138 of file magic.cpp.
{
    damage_instance dmg;
    dmg.add_damage( dmg_type(), damage() );
    return dmg;
}
References damage_instance::add_damage(), damage(), and dmg_type().
Referenced by damage_targets().
get_dealt_damage_instance()
dealt_damage_instance spell::get_dealt_damage_instance () const
Definition at line 1145 of file magic.cpp.
{
    dealt_damage_instance dmg;
    dmg.set_damage( dmg_type(), damage() );
    return dmg;
}
References damage(), dmg_type(), and dealt_damage_instance::set_damage().
get_difficulty()
int spell::get_difficulty () const
Definition at line 696 of file magic.cpp.
{
    return type->difficulty;
}
References spell_type::difficulty, and type.
Referenced by spellcasting_callback::draw_spell_info(), exp_modifier(), dialogue::gen_responses(), spell_fail(), talk_function::start_training(), and activity_handlers::study_spell_finish().
get_level()
int spell::get_level () const
Definition at line 1034 of file magic.cpp.
{
    // you aren't at the next level unless you have the requisite xp, so floor
    return std::max( static_cast<int>( std::floor( std::log( experience + a ) / b + c ) ), 0 );
}
References a, b, c, and experience.
Referenced by Character::add_bionic(), cast_all_effects(), casting_time(), spellcasting_callback::draw_spell_info(), energy_cost(), exp_progress(), exp_to_next_level(), field_intensity(), dialogue::gen_responses(), fake_spell::get_spell(), is_max_level(), learn_spells(), min_leveled_aoe(), min_leveled_damage(), min_leveled_duration(), diary::new_page(), target_ui::panel_spell_info(), npc::randomize(), range(), spell_fail(), activity_handlers::spellcasting_finish(), talk_function::start_training(), activity_handlers::study_spell_do_turn(), and learn_spell_actor::use().
get_max_level()
int spell::get_max_level () const
Definition at line 1040 of file magic.cpp.
{
    return type->max_level;
}
References spell_type::max_level, and type.
Referenced by spellcasting_callback::draw_spell_info(), and fake_spell::get_spell().
has_flag()
bool spell::has_flag (const spell_flag & flag) const
Definition at line 661 of file magic.cpp.
{
    return type->spell_tags[flag];
}
References spell_type::spell_tags, and type.
Referenced by add_summoned_mon(), aoe(), aoe_string(), spell_effect::bash(), cast_all_effects(), cast_spell(), casting_time(), casting_time_encumbered(), spell_effect::cone_attack(), damage(), damage_string(), duration(), duration_string(), energy_cost(), energy_cost_encumbered(), enumerate_spell_data(), in_aoe(), is_summon_friendly(), spell_effect::line_attack(), make_sound(), spell_effect::mutate(), spell_effect::recover_energy(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_vehicle(), spell_fail(), activity_handlers::spellcasting_finish(), spell_effect::target_attack(), and spell_effect::teleport_random().
heal()
int spell::heal (const tripoint & target) const
Definition at line 1162 of file magic.cpp.
{
    monster *const mon = g->critter_at<monster>( target );
    if( mon ) {
        return mon->heal( -damage() );
    }
    Character *const p = g->critter_at<Character>( target );
    if( p ) {
        p->healall( -damage() );
        return -damage();
    }
    return -1;
}
References damage(), g, monster::heal(), and Character::healall().
Referenced by damage_targets().
id()
spell_id spell::id () const
Definition at line 456 of file magic.cpp.
{
    return type;
}
References type.
Referenced by cast_spell(), spell_effect::flashbang(), spell_effect::morale(), diary::new_page(), spell_effect_area(), activity_handlers::spellcasting_finish(), talk_function::start_training(), and cast_spell_actor::use().
in_aoe()
bool spell::in_aoe (const tripoint & source, const tripoint & target) const
Definition at line 533 of file magic.cpp.
{
    if( has_flag( spell_flag::RANDOM_AOE ) ) {
        return rl_dist( source, target ) <= type->max_aoe;
    } else {
        return rl_dist( source, target ) <= aoe();
    }
}
References aoe(), has_flag(), spell_type::max_aoe, RANDOM_AOE, rl_dist(), and type.
Referenced by target_ui::panel_spell_info().
is_max_level()
bool spell::is_max_level () const
Definition at line 618 of file magic.cpp.
{
    return get_level() >= type->max_level;
}
References get_level(), spell_type::max_level, and type.
Referenced by spellcasting_callback::draw_spell_info(), gain_levels(), dialogue::gen_responses(), learn_spells(), npc::randomize(), spell_effect::spawn_ethereal_item(), activity_handlers::spellcasting_finish(), and learn_spell_actor::use().
is_spell_class()
bool spell::is_spell_class (const trait_id & mid) const
Definition at line 666 of file magic.cpp.
{
    return mid == type->spell_class;
}
References spell_type::spell_class, and type.
is_target_in_range()
bool spell::is_target_in_range (const Creature & caster, const tripoint & p) const
Definition at line 945 of file magic.cpp.
{
    return rl_dist( caster.pos(), p ) <= range();
}
References Creature::pos(), range(), and rl_dist().
Referenced by enchantment::cast_enchantment_spell().
is_valid()
bool spell::is_valid () const
Definition at line 887 of file magic.cpp.
{
    return type.is_valid();
}
References string_id< T >::is_valid(), and type.
Referenced by known_magic::learn_spell().
is_valid_effect_target()
bool spell::is_valid_effect_target (valid_target t) const
Definition at line 971 of file magic.cpp.
{
    return type->effect_targets[t];
}
References spell_type::effect_targets, and type.
Referenced by spell_move().
is_valid_target() [1/2]
bool spell::is_valid_target (const Creature & caster, const tripoint & p) const
Definition at line 955 of file magic.cpp.
{
    bool valid = false;
    if( Creature *const cr = g->critter_at<Creature>( p ) ) {
        Creature::Attitude cr_att = cr->attitude_to( caster );
        valid = valid || ( cr_att != Creature::A_FRIENDLY && is_valid_target( target_hostile ) );
        valid = valid || ( cr_att == Creature::A_FRIENDLY && is_valid_target( target_ally ) &&
                           p != caster.pos() );
        valid = valid || ( is_valid_target( target_self ) && p == caster.pos() );
        valid = valid && target_by_monster_id( p );
    } else {
        valid = is_valid_target( target_ground );
    }
    return valid;
}
References Creature::A_FRIENDLY, g, is_valid_target(), Creature::pos(), target_ally, target_by_monster_id(), target_ground, target_hostile, and target_self.
Referenced by spell_effect::bash(), calculate_spell_effect_area(), enchantment::cast_enchantment_spell(), spell_effect::charm_monster(), damage_targets(), spellcasting_callback::draw_spell_info(), enumerate_targets(), spell_effect::flashbang(), is_valid_target(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), random_valid_target(), activity_handlers::spellcasting_finish(), target_ui::update_status(), and spell_effect::vomit().
is_valid_target() [2/2]
bool spell::is_valid_target (valid_target t) const
Definition at line 950 of file magic.cpp.
{
    return type->valid_targets[t];
}
References type, and spell_type::valid_targets.
list_targeted_monster_names()
std::string spell::list_targeted_monster_names () const
Definition at line 1117 of file magic.cpp.
{
    if( type->targeted_monster_ids.empty() ) {
        return "";
    }
    std::vector<std::string> all_valid_monster_names;
    for( const mtype_id &mon_id : type->targeted_monster_ids ) {
        all_valid_monster_names.emplace_back( mon_id->nname() );
    }
    //remove repeat names
    all_valid_monster_names.erase( std::unique( all_valid_monster_names.begin(),
                                   all_valid_monster_names.end() ), all_valid_monster_names.end() );
    std::string ret = enumerate_as_string( all_valid_monster_names );
    return ret;
}
References enumerate_as_string(), mtype::nname(), cata::hash64_detail::ret, spell_type::targeted_monster_ids, and type.
Referenced by spellcasting_callback::draw_spell_info().
make_sound() [1/2]
void spell::make_sound (const tripoint & target) const
Definition at line 918 of file magic.cpp.
{
    if( !has_flag( spell_flag::SILENT ) ) {
        int loudness = std::abs( damage() ) / 3;
        if( has_flag( spell_flag::LOUD ) ) {
            loudness += 1 + damage() / 3;
        }
        make_sound( target, loudness );
    }
}
References damage(), has_flag(), LOUD, make_sound(), and SILENT.
Referenced by spell_effect::area_pull(), spell_effect::area_push(), trapfunc::cast_spell(), spell_effect::charm_monster(), damage_targets(), make_sound(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), spell_effect::noise(), spell_effect::pain_split(), spell_effect::recover_energy(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), spell_effect::timed_event(), and spell_effect::vomit().
make_sound() [2/2]
void spell::make_sound (const tripoint & target, int loudness) const
Definition at line 929 of file magic.cpp.
{
    sounds::sound( target, loudness, type->sound_type, type->sound_description.translated(),
                   type->sound_ambient, type->sound_id, type->sound_variant );
}
References sounds::sound(), spell_type::sound_ambient, spell_type::sound_description, spell_type::sound_id, spell_type::sound_type, spell_type::sound_variant, translation::translated(), and type.
message()
std::string spell::message () const
Definition at line 734 of file magic.cpp.
{
    if( !alt_message.empty() ) {
        return alt_message.translated();
    }
    return type->message.translated();
}
References alt_message, translation::empty(), spell_type::message, translation::translated(), and type.
Referenced by mon_spellcasting_actor::call(), cast_all_effects(), and activity_handlers::spellcasting_finish().
min_leveled_aoe()
int spell::min_leveled_aoe () const private
Definition at line 513 of file magic.cpp.
{
    return type->min_aoe + std::round( get_level() * type->aoe_increment );
}
References spell_type::aoe_increment, get_level(), spell_type::min_aoe, and type.
Referenced by aoe(), and aoe_string().
min_leveled_damage()
int spell::min_leveled_damage () const private
Definition at line 478 of file magic.cpp.
{
    return type->min_damage + std::round( get_level() * type->damage_increment );
}
References spell_type::damage_increment, get_level(), spell_type::min_damage, and type.
Referenced by damage(), and damage_string().
min_leveled_duration()
int spell::min_leveled_duration () const private
Definition at line 561 of file magic.cpp.
{
    return type->min_duration + std::round( get_level() * type->duration_increment );
}
References spell_type::duration_increment, get_level(), spell_type::min_duration, and type.
Referenced by duration(), and duration_string().
name()
std::string spell::name () const
Definition at line 729 of file magic.cpp.
{
    return type->name.translated();
}
References spell_type::name, translation::translated(), and type.
Referenced by mon_spellcasting_actor::call(), dialogue::gen_responses(), spell_effect::none(), target_ui::panel_spell_info(), spell_effect::recover_energy(), diary::spell_changes(), and activity_handlers::spellcasting_finish().
random_valid_target()
cata::optional< tripoint > spell::random_valid_target (const Creature & caster, const tripoint & caster_pos) const
Definition at line 1232 of file magic.cpp.
{
    std::set<tripoint> valid_area;
    for( const tripoint &target : spell_effect::spell_effect_blast( *this, caster_pos, caster_pos,
            range(), false ) ) {
        if( is_valid_target( caster, target ) ) {
            valid_area.emplace( target );
        }
    }
    if( valid_area.empty() ) {
        return cata::nullopt;
    }
    return random_entry( valid_area );
}
References is_valid_target(), cata::nullopt, random_entry(), range(), and spell_effect::spell_effect_blast().
Referenced by cast_all_effects(), and activity_handlers::spellcasting_finish().
range()
int spell::range () const
Definition at line 551 of file magic.cpp.
{
    const int leveled_range = type->min_range + std::round( get_level() * type->range_increment );
    if( type->max_range >= type->min_range ) {
        return std::min( leveled_range, type->max_range );
    } else {
        return std::max( leveled_range, type->max_range );
    }
}
References get_level(), spell_type::max_range, spell_type::min_range, spell_type::range_increment, and type.
Referenced by mon_spellcasting_actor::call(), spellcasting_callback::draw_spell_info(), enumerate_spell_data(), is_target_in_range(), target_handler::mode_spell(), random_valid_target(), spell_effect::spell_effect_cone(), activity_handlers::spellcasting_finish(), and spell_effect::teleport_random().
set_exp()
void spell::set_exp (int nxp)
Definition at line 815 of file magic.cpp.
{
    experience = nxp;
}
References experience.
set_level()
void spell::set_level (int nlevel)
Definition at line 612 of file magic.cpp.
{
    experience = 0;
    gain_levels( nlevel );
}
References experience, and gain_levels().
Referenced by Character::add_bionic().
set_message()
void spell::set_message (const translation & msg)
Definition at line 451 of file magic.cpp.
{
    alt_message = msg;
}
References alt_message.
Referenced by mon_spellcasting_actor::load_internal().
skill()
skill_id spell::skill () const
Definition at line 466 of file magic.cpp.
{
    return type->skill;
}
References spell_type::skill, and type.
Referenced by exp_modifier(), spell_fail(), and activity_handlers::study_spell_finish().
spell_class()
trait_id spell::spell_class () const
Definition at line 461 of file magic.cpp.
{
    return type->spell_class;
}
References spell_type::spell_class, and type.
Referenced by spellcasting_callback::draw_spell_info().
spell_fail()
float spell::spell_fail (const Character & guy) const
Definition at line 742 of file magic.cpp.
{
    if( has_flag( spell_flag::NO_FAIL ) ) {
        return 0.0f;
    }
    // formula is based on the following:
    // exponential curve
    // effective skill of 0 or less is 100% failure
    // effective skill of 8 (8 int, 0 spellcraft, 0 spell level, spell difficulty 0) is ~50% failure
    // effective skill of 30 is 0% failure
    const float effective_skill = 2 * ( get_level() - get_difficulty() ) + guy.get_int() +
                                  guy.get_skill_level( skill() );
    // add an if statement in here because sufficiently large numbers will definitely overflow because of exponents
    if( effective_skill > 30.0f ) {
        return 0.0f;
    } else if( effective_skill < 0.0f ) {
        return 1.0f;
    }
    float fail_chance = std::pow( ( effective_skill - 30.0f ) / 30.0f, 2 );
    if( has_flag( spell_flag::SOMATIC ) && !guy.has_trait_flag( "SUBTLE_SPELL" ) ) {
        // the first 20 points of encumbrance combined is ignored
        const int arms_encumb = std::max( 0, guy.encumb( bp_arm_l ) + guy.encumb( bp_arm_r ) - 20 );
        // each encumbrance point beyond the "gray" color counts as half an additional fail %
        fail_chance += arms_encumb / 200.0f;
    }
    if( has_flag( spell_flag::VERBAL ) && !guy.has_trait_flag( "SILENT_SPELL" ) ) {
        // a little bit of mouth encumbrance is allowed, but not much
        const int mouth_encumb = std::max( 0, guy.encumb( bp_mouth ) - 5 );
        fail_chance += mouth_encumb / 100.0f;
    }
    // concentration spells work better than you'd expect with a higher focus pool
    if( has_flag( spell_flag::CONCENTRATE ) ) {
        if( guy.focus_pool <= 0 ) {
            return 0.0f;
        }
        fail_chance /= guy.focus_pool / 100.0f;
    }
    return clamp( fail_chance, 0.0f, 1.0f );
}
References bp_arm_l, bp_arm_r, bp_mouth, clamp(), CONCENTRATE, Character::encumb(), Character::focus_pool, get_difficulty(), Character::get_int(), get_level(), Character::get_skill_level(), has_flag(), Character::has_trait_flag(), NO_FAIL, skill(), SOMATIC, and VERBAL.
Referenced by colorized_fail_percent(), and activity_handlers::spellcasting_finish().
summon_vehicle_id()
vproto_id spell::summon_vehicle_id () const
Definition at line 1157 of file magic.cpp.
{
    return vproto_id( type->effect_str );
}
References spell_type::effect_str, and type.
Referenced by spell_effect::spawn_summoned_vehicle().
target_by_monster_id()
bool spell::target_by_monster_id (const tripoint & p) const
Definition at line 976 of file magic.cpp.
{
    if( type->targeted_monster_ids.empty() ) {
        return true;
    }
    bool valid = false;
    if( monster *const target = g->critter_at<monster>( p ) ) {
        if( type->targeted_monster_ids.find( target->type->id ) != type->targeted_monster_ids.end() ) {
            valid = true;
        }
    }
    return valid;
}
References g, spell_type::targeted_monster_ids, and type.
Referenced by is_valid_target().
xp()
int spell::xp () const
Definition at line 805 of file magic.cpp.
{
    return experience;
}
References experience.
Referenced by spellcasting_callback::draw_spell_info(), exp_progress(), exp_to_next_level(), and activity_handlers::spellcasting_finish().
Friends And Related Function Documentation
spell_events
friend class spell_events friend
Definition at line 288 of file magic.h.
Member Data Documentation
alt_message
translation spell::alt_message private
Definition at line 298 of file magic.h.
Referenced by message(), and set_message().
experience
int spell::experience = 0 private
Definition at line 293 of file magic.h.
Referenced by gain_exp(), get_level(), set_exp(), set_level(), and xp().
type
spell_id spell::type private
Definition at line 290 of file magic.h.
Referenced by aoe(), aoe_string(), bp_is_affected(), can_cast(), can_learn(), cast_all_effects(), cast_spell_effect(), casting_time(), create_field(), damage(), damage_string(), description(), dmg_type(), duration(), duration_string(), effect(), effect_data(), energy_cost(), energy_source(), energy_string(), field_intensity(), get_difficulty(), get_max_level(), has_flag(), id(), in_aoe(), is_max_level(), is_spell_class(), is_valid(), is_valid_effect_target(), is_valid_target(), list_targeted_monster_names(), make_sound(), message(), min_leveled_aoe(), min_leveled_damage(), min_leveled_duration(), name(), range(), skill(), spell_class(), summon_vehicle_id(), and target_by_monster_id().
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp