Cataclysm BN: utf8_wrapper Class Reference
utf8_wrapper Class Reference
UTF8-Wrapper over std::string.
#include <catacharset.h>
Public Member Functions
utf8_wrapper ()
utf8_wrapper (const std::string &d)
utf8_wrapper (const char *d)
void insert (size_t start, const utf8_wrapper &other)
utf8_wrapper substr (size_t start, size_t length) const
utf8_wrapper substr (size_t start) const
void erase (size_t start, size_t length)
void erase (size_t start)
void append (const utf8_wrapper &other)
utf8_wrapper & replace_all (const utf8_wrapper &search, const utf8_wrapper &replace)
utf8_wrapper substr_display (size_t start, size_t length) const
Returns a substring based on the display width, not the number of code points (as the other substr function does).
utf8_wrapper substr_display (size_t start) const
utf8_wrapper & operator= (const std::string &d)
const std::string & str () const
uint32_t at (size_t start) const
size_t size () const
size_t length () const
bool empty () const
size_t display_width () const
const char * c_str () const
std::string shorten (size_t maxlength) const
Return a substring at most maxlength width (display width).
Protected Member Functions
size_t byte_start (size_t bstart, size_t start) const
size_t byte_start_display (size_t bstart, size_t start) const
utf8_wrapper substr_byte (size_t bytestart, size_t length, bool use_display_width) const
void init_utf8_wrapper ()
Protected Attributes
std::string _data
size_t _length
size_t _display_width
Detailed Description
UTF8-Wrapper over std::string.
It looks and feels like a std::string, but uses code points counts as index, not bytes. A multi-byte Unicode character might be represented as 3 bytes in UTF8, this class will see these 3 bytes as 1 character. It will never separate them. It will however split between code points which might be problematic when containing combination characters. In this case use the *_display functions. They operate on the display width. Code points with a zero width are considered to belong to the previous code point and are not split from that. Having a string with like [letter0][letter1][combination-mark][letter2] (assuming each letter has a width of 1) will return a display_width of 3. substr_display(1, 2) returns [letter1][combination-mark][letter2], substr_display(1, 1) returns [letter1][combination-mark] substr_display(2, 1) returns [letter2]
Note: functions use code points, not bytes, for counting/indexing! Functions with the _display suffix use display width for counting/indexing! Protected functions might behave different
For function documentation see std::string, the functions here mimic the behavior of the equally named std::string function.
Definition at line 85 of file catacharset.h.
Constructor & Destructor Documentation
utf8_wrapper() [1/3]
utf8_wrapper::utf8_wrapper () inline
Definition at line 88 of file catacharset.h.
: _length(0), _display_width(0) { }
Referenced by operator=(), and substr_byte().
utf8_wrapper() [2/3]
utf8_wrapper::utf8_wrapper (const std::string & d)
Definition at line 508 of file catacharset.cpp.
                                               : _data( d ), _length( 0 ), _display_width( 0 )
{
    init_utf8_wrapper();
}
References init_utf8_wrapper().
utf8_wrapper() [3/3]
utf8_wrapper::utf8_wrapper (const char * d)
Definition at line 513 of file catacharset.cpp.
                                          : _length( 0 ), _display_width( 0 )
{
    _data = std::string( d );
    init_utf8_wrapper();
}
References _data, and init_utf8_wrapper().
Member Function Documentation
append()
void utf8_wrapper::append (const utf8_wrapper & other)
Definition at line 622 of file catacharset.cpp.
{
    _data.append( other._data );
    _length += other._length;
    _display_width += other._display_width;
}
References _data, _display_width, _length, and other.
Referenced by worldfactory::show_worldgen_tab_confirm().
at()
uint32_t utf8_wrapper::at (size_t start) const
Definition at line 599 of file catacharset.cpp.
{
    const size_t bstart = byte_start( 0, start );
    const char *utf8str = _data.c_str() + bstart;
    int len = _data.length() - bstart;
    while( len > 0 ) {
        const uint32_t ch = UTF8_getch( &utf8str, &len );
        if( ch != UNKNOWN_UNICODE ) {
            return ch;
        }
    }
    return 0;
}
References _data, byte_start(), UNKNOWN_UNICODE, and UTF8_getch().
Referenced by string_editor_window::cursor_updown(), string_editor_window::query_string(), and worldfactory::show_worldgen_tab_confirm().
byte_start()
size_t utf8_wrapper::byte_start (size_t bstart, size_t start) const protected
Definition at line 519 of file catacharset.cpp.
{
    if( bstart >= _data.length() ) {
        return _data.length();
    }
    const char *utf8str = _data.c_str() + bstart;
    int len = _data.length() - bstart;
    while( len > 0 && start > 0 ) {
        const uint32_t ch = UTF8_getch( &utf8str, &len );
        if( ch == UNKNOWN_UNICODE ) {
            continue;
        }
        start--;
    }
    return utf8str - _data.c_str();
}
References _data, UNKNOWN_UNICODE, and UTF8_getch().
Referenced by at(), erase(), insert(), substr(), and substr_byte().
byte_start_display()
size_t utf8_wrapper::byte_start_display (size_t bstart, size_t start) const protected
Definition at line 536 of file catacharset.cpp.
{
    if( bstart >= _data.length() ) {
        return _data.length();
    }
    if( start == 0 ) {
        return 0;
    }
    const char *utf8str = _data.c_str() + bstart;
    int len = _data.length() - bstart;
    while( len > 0 ) {
        const char *prevstart = utf8str;
        const uint32_t ch = UTF8_getch( &utf8str, &len );
        if( ch == UNKNOWN_UNICODE ) {
            continue;
        }
        const int width = mk_wcwidth( ch );
        if( static_cast<int>( start ) >= width ) {
            // If width is 0, include the code point (might be combination character)
            // Same when width is actually smaller than start
            start -= width;
        } else {
            // If width is 2 and start is 1, stop before the multi-cell code point
            // Same when width is 1 and start is 0.
            return prevstart - _data.c_str();
        }
    }
    return _data.length();
}
References _data, mk_wcwidth(), UNKNOWN_UNICODE, and UTF8_getch().
Referenced by substr_byte(), and substr_display().
c_str()
const char * utf8_wrapper::c_str () const inline
Definition at line 148 of file catacharset.h.
{
            return _data.c_str();
        }
References _data.
Referenced by string_input_popup::draw(), and utf8_width().
display_width()
size_t utf8_wrapper::display_width () const inline
Definition at line 145 of file catacharset.h.
{
            return _display_width;
        }
References _display_width.
Referenced by center_text_pos(), string_input_popup::draw(), and shorten().
empty()
bool utf8_wrapper::empty () const inline
Definition at line 140 of file catacharset.h.
{
            return size() == 0;
        }
References size().
Referenced by string_editor_window::cursor_updown(), string_editor_window::query_string(), and worldfactory::show_worldgen_tab_confirm().
erase() [1/2]
void utf8_wrapper::erase (size_t start) inline
Definition at line 98 of file catacharset.h.
{
            erase( start, _length - start );
        }
References _length, and erase().
erase() [2/2]
void utf8_wrapper::erase (size_t start, size_t length)
Definition at line 613 of file catacharset.cpp.
{
    const size_t bstart = byte_start( 0, start );
    const utf8_wrapper removed( substr_byte( bstart, length, false ) );
    _data.erase( bstart, removed._data.length() );
    _length -= removed._length;
    _display_width -= removed._display_width;
}
References _data, _display_width, _length, byte_start(), length(), and substr_byte().
Referenced by erase(), string_editor_window::query_string(), replace_all(), and worldfactory::show_worldgen_tab_confirm().
init_utf8_wrapper()
void utf8_wrapper::init_utf8_wrapper () protected
Definition at line 494 of file catacharset.cpp.
{
    const char *utf8str = _data.c_str();
    int len = _data.length();
    while( len > 0 ) {
        const uint32_t ch = UTF8_getch( &utf8str, &len );
        if( ch == UNKNOWN_UNICODE ) {
            continue;
        }
        _length++;
        _display_width += mk_wcwidth( ch );
    }
}
References _data, _display_width, _length, mk_wcwidth(), UNKNOWN_UNICODE, and UTF8_getch().
Referenced by utf8_wrapper().
insert()
void utf8_wrapper::insert (size_t start, const utf8_wrapper & other)
Definition at line 566 of file catacharset.cpp.
{
    const size_t bstart = byte_start( 0, start );
    _data.insert( bstart, other._data );
    _length += other._length;
    _display_width += other._display_width;
}
References _data, _display_width, _length, byte_start(), and other.
Referenced by string_editor_window::query_string(), and replace_all().
length()
size_t utf8_wrapper::length () const inline
Definition at line 137 of file catacharset.h.
{
            return size();
        }
References size().
Referenced by erase(), string_editor_window::query_string(), string_input_popup::query_string(), worldfactory::show_worldgen_tab_confirm(), substr(), substr_byte(), and substr_display().
operator=()
utf8_wrapper & utf8_wrapper::operator= (const std::string & d) inline
Definition at line 122 of file catacharset.h.
{
            *this = utf8_wrapper( d );
            return *this;
        }
References utf8_wrapper().
replace_all()
utf8_wrapper & utf8_wrapper::replace_all (const utf8_wrapper & search, const utf8_wrapper & replace)
Definition at line 629 of file catacharset.cpp.
{
    for( std::string::size_type i = _data.find( search._data ); i != std::string::npos;
         i = _data.find( search._data, i ) ) {
        erase( i, search.length() );
        insert( i, replace );
        i += replace._data.length();
    }
    return *this;
}
References _data, erase(), insert(), and overmap_ui::search().
shorten()
std::string utf8_wrapper::shorten (size_t maxlength) const
Return a substring at most maxlength width (display width).
If the string had to shortened, an ellipsis (...) is added. The string with the ellipsis will be exactly maxlength displayed characters.
Definition at line 641 of file catacharset.cpp.
{
    if( display_width() <= maxlength ) {
        return str();
    }
    // 2026 is the utf8 for
    return substr_display( 0, maxlength - 1 ).str() + "\u2026";
}
References display_width(), str(), and substr_display().
size()
size_t utf8_wrapper::size () const inline
Definition at line 134 of file catacharset.h.
{
            return _length;
        }
References _length.
Referenced by string_editor_window::cursor_leftright(), string_editor_window::cursor_updown(), empty(), length(), string_editor_window::query_string(), and string_input_popup::text().
str()
const std::string & utf8_wrapper::str () const inline
Definition at line 126 of file catacharset.h.
{
            return _data;
        }
References _data.
Referenced by string_editor_window::print_editor(), string_editor_window::query_string(), shorten(), worldfactory::show_worldgen_tab_confirm(), and UTF8_getch().
substr() [1/2]
utf8_wrapper utf8_wrapper::substr (size_t start) const inline
Definition at line 94 of file catacharset.h.
{
            return substr( start, _length - start );
        }
References _length, and substr().
substr() [2/2]
utf8_wrapper utf8_wrapper::substr (size_t start, size_t length) const
Definition at line 574 of file catacharset.cpp.
{
    return substr_byte( byte_start( 0, start ), length, false );
}
References byte_start(), length(), and substr_byte().
Referenced by string_editor_window::cursor_updown(), string_editor_window::print_editor(), and substr().
substr_byte()
utf8_wrapper utf8_wrapper::substr_byte (size_t bytestart, size_t length, bool use_display_width) const protected
Definition at line 584 of file catacharset.cpp.
{
    if( length == 0 || bytestart >= _data.length() ) {
        return utf8_wrapper();
    }
    size_t bend;
    if( use_display_width ) {
        bend = byte_start_display( bytestart, length );
    } else {
        bend = byte_start( bytestart, length );
    }
    return utf8_wrapper( _data.substr( bytestart, bend - bytestart ) );
}
References _data, byte_start(), byte_start_display(), length(), and utf8_wrapper().
Referenced by erase(), substr(), and substr_display().
substr_display() [1/2]
utf8_wrapper utf8_wrapper::substr_display (size_t start) const inline
Definition at line 118 of file catacharset.h.
{
            return substr_display( start, _length - start );
        }
References _length, and substr_display().
substr_display() [2/2]
utf8_wrapper utf8_wrapper::substr_display (size_t start, size_t length) const
Returns a substring based on the display width, not the number of code points (as the other substr function does).
Parameters
start Start the returned substring with the character that is at that position when this string would be have been printed (rounded down). E.g. a string "aa" (where a is a normal character, and ` is a combination code point) would be displayed as two cells: "aa". substr_display(0,2) would return the whole string, substr_display(0,1) would return the first two code points, substr_display(1,1) would return the last two code points.
length Display length of the returned string, the returned string can have a shorter display length (especially if the last character is a multi-cell character and including it would exceed the length parameter).
Definition at line 579 of file catacharset.cpp.
{
    return substr_byte( byte_start_display( 0, start ), length, true );
}
References byte_start_display(), length(), and substr_byte().
Referenced by string_editor_window::cursor_updown(), shorten(), and substr_display().
Member Data Documentation
_data
std::string utf8_wrapper::_data protected
Definition at line 159 of file catacharset.h.
Referenced by append(), at(), byte_start(), byte_start_display(), c_str(), erase(), init_utf8_wrapper(), insert(), replace_all(), str(), substr_byte(), and utf8_wrapper().
_display_width
size_t utf8_wrapper::_display_width protected
Definition at line 161 of file catacharset.h.
Referenced by append(), display_width(), erase(), init_utf8_wrapper(), and insert().
_length
size_t utf8_wrapper::_length protected
Definition at line 160 of file catacharset.h.
Referenced by append(), erase(), init_utf8_wrapper(), insert(), size(), substr(), and substr_display().
The documentation for this class was generated from the following files:
src/catacharset.h
src/catacharset.cpp