Cataclysm BN: score Class Reference
score Class Reference
#include <event_statistics.h>
Public Member Functions
score ()=default
std::string description (stats_tracker &) const
cata_variant value (stats_tracker &) const
void load (const JsonObject &, const std::string &)
void check () const
Static Public Member Functions
static void load_score (const JsonObject &, const std::string &)
static void check_consistency ()
static const std::vector< score > & get_all ()
static void reset ()
Public Attributes
string_id< score > id
bool was_loaded = false
Private Attributes
translation description_
string_id< event_statistic > stat_
Detailed Description
Definition at line 92 of file event_statistics.h.
Constructor & Destructor Documentation
score()
score::score () default
Member Function Documentation
check()
void score::check () const
Definition at line 1055 of file event_statistics.cpp.
{
    if( !stat_.is_valid() ) {
        debugmsg( "score %s refers to invalid statistic %s", id.str(), stat_.str() );
    }
}
References debugmsg, and stat_.
check_consistency()
void score::check_consistency () static
Definition at line 128 of file event_statistics.cpp.
{
    score_factory.check();
}
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
std::string score::description (stats_tracker & stats) const
Definition at line 1026 of file event_statistics.cpp.
{
    cata_variant val = value( stats );
    std::string value_string = value( stats ).get_string();
    std::string desc;
    if( val.type() == cata_variant_type::int_ ) {
        desc = stat_->description().translated( val.get<int>() );
    } else {
        desc = stat_->description().translated();
    }
    if( description_.empty() ) {
        //~ Default format for scores.  %1$s is statistic description; %2$s is value.
        return string_format( _( "%2$s %1$s" ), desc, value_string );
    } else {
        return string_format( desc, value_string );
    }
}
References _, description_, translation::empty(), cata_variant::get(), cata_variant::get_string(), int_, stat_, string_format(), cata_variant::type(), and value().
get_all()
const std::vector< score > & score::get_all () static
Definition at line 133 of file event_statistics.cpp.
{
    return score_factory.get_all();
}
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by stats_tracker::notify(), and stats_tracker::valid_scores().
load()
void score::load (const JsonObject & jo, const std::string &)
Definition at line 1049 of file event_statistics.cpp.
{
    optional( jo, was_loaded, "description", description_ );
    mandatory( jo, was_loaded, "statistic", stat_ );
}
References description_, mandatory(), optional(), stat_, and was_loaded.
load_score()
void score::load_score (const JsonObject & jo, const std::string & src) static
Definition at line 123 of file event_statistics.cpp.
{
    score_factory.load( jo, src );
}
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void score::reset () static
Definition at line 138 of file event_statistics.cpp.
{
    score_factory.reset();
}
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by DynamicDataLoader::unload_data().
value()
cata_variant score::value (stats_tracker & stats) const
Definition at line 1044 of file event_statistics.cpp.
{
    return stats.value_of( stat_ );
}
References stat_.
Referenced by description().
Member Data Documentation
description_
translation score::description_ private
Definition at line 110 of file event_statistics.h.
Referenced by description(), and load().
id
string_id<score> score::id
Definition at line 107 of file event_statistics.h.
stat_
string_id<event_statistic> score::stat_ private
Definition at line 111 of file event_statistics.h.
Referenced by check(), description(), load(), and value().
was_loaded
bool score::was_loaded = false
Definition at line 108 of file event_statistics.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/event_statistics.h
src/event_statistics.cpp