Cataclysm BN: debug_menu::effect_edit_callback Class Reference
debug_menu::effect_edit_callback Class Reference
Public Member Functions
effect_edit_callback (Creature &c, const std::vector< entry_data > &meta, const std::function< void()> &on_creature_changed)
bool key (const input_context &ctx, const input_event &key, int entnum, uilist *parent_menu) override
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual void refresh (uilist *)
virtual ~uilist_callback ()=default
Static Public Member Functions
static std::map< std::string, effect_edit_fun > get_handled_actions ()
Private Types
using effect_edit_fun = void(effect_edit_callback::*)(const input_context &, const input_event &, int, uilist &)
Private Member Functions
void add_effect_submenu (const input_context &, const input_event &, int, uilist &menu)
void clear_effects (const input_context &, const input_event &, int, uilist &)
void remove (const input_context &, const input_event &, int entnum, uilist &)
void change_body_part (const input_context &, const input_event &, int entnum, uilist &parent_menu)
void change_intensity (const input_context &, const input_event &, int entnum, uilist &)
void change_duration (const input_context &, const input_event &, int entnum, uilist &)
void toggle_force (const input_context &, const input_event &, int, uilist &)
Private Attributes
Creature & c
const std::vector< efftype_id > all_effects = find_all_effect_types()
const std::vector< entry_data > meta
std::function< void()> on_creature_changed
Static Private Attributes
static const std::map< std::string, effect_edit_fun > handled_actions
Detailed Description
Definition at line 256 of file wisheffect.cpp.
Member Typedef Documentation
effect_edit_fun
using debug_menu::effect_edit_callback::effect_edit_fun = void (effect_edit_callback::*)(const input_context &, const input_event &, int, uilist &) private
Definition at line 259 of file wisheffect.cpp.
Constructor & Destructor Documentation
effect_edit_callback()
debug_menu::effect_edit_callback::effect_edit_callback (Creature & c, const std::vector< entry_data > & meta, const std::function< void()> & on_creature_changed) inline
Definition at line 275 of file wisheffect.cpp.
            : c( c )
            , meta( meta )
            , on_creature_changed( on_creature_changed )
        {}
Member Function Documentation
add_effect_submenu()
void debug_menu::effect_edit_callback::add_effect_submenu (const input_context & , const input_event & , int , uilist & menu) inline private
Definition at line 303 of file wisheffect.cpp.
{
            wisheffect_state &last_val = uistate.debug_menu.effect;
            uilist submenu;
            submenu.w_x_setup = 0;
            submenu.w_width_setup = []() -> int {
                return TERMX;
            };
            submenu.pad_right_setup = []() -> int {
                return TERMX - 40;
            };
            effect_select_callback callback( c );
            register_callback( submenu, callback );
            submenu.input_category = menu.input_category;
            int i = 0;
            for( const efftype_id &eff : all_effects ) {
                submenu.addentry( i++, true, -1, eff.str() );
            }
            submenu.set_selected( last_val.last_type_selected_index );
            submenu.query();
            if( submenu.ret >= 0 && submenu.ret < static_cast<int>( all_effects.size() ) ) {
                const efftype_id eff_type = all_effects[static_cast<size_t>( submenu.ret )];
                last_val.last_type_selected_index = submenu.ret;
                time_duration duration = last_val.duration <= 0_seconds ? eff_type->get_max_duration() :
                                         last_val.duration;
                c.add_effect( eff_type, duration, last_val.bodypart, last_val.intensity, last_val.force );
                on_creature_changed();
            }
        }
References uilist::addentry(), wisheffect_state::bodypart, c, uistatedata::debug_menu, wisheffect_state::duration, debug_menu_state::effect, wisheffect_state::force, effect_type::get_max_duration(), uilist::input_category, wisheffect_state::intensity, wisheffect_state::last_type_selected_index, uilist::pad_right_setup, uilist::query(), debug_menu::anonymous_namespace{wisheffect.cpp}::register_callback(), uilist::ret, uilist::set_selected(), TERMX, uistate, uilist::w_width_setup, and uilist::w_x_setup.
change_body_part()
void debug_menu::effect_edit_callback::change_body_part (const input_context & , const input_event & , int entnum, uilist & parent_menu) inline private
Definition at line 355 of file wisheffect.cpp.
{
            cata::optional<bodypart_str_id> bp = query_body_part( c );
            if( bp ) {
                on_creature_changed();
                const bodypart_str_id bp_from = meta[entnum].body_part;
                std::vector<effect> to_move;
                foreach_effect( c, meta[entnum], [&]( const effect & eff ) {
                    to_move.push_back( eff );
                } );
                for( const effect &eff : to_move ) {
                    c.remove_effect( eff.get_id(), bp_from );
                    c.add_effect( eff.get_id(), eff.get_duration(), *bp, eff.get_intensity(), true );
                }
                auto iter_to = std::find_if( meta.begin(), meta.end(), [bp]( const entry_data & ed ) {
                    return ed.body_part == *bp;
                } );
                size_t bp_index = std::distance( iter_to, meta.begin() ) % meta.size();
                parent_menu.set_selected( bp_index );
            }
        }
References c, debug_menu::anonymous_namespace{wisheffect.cpp}::foreach_effect(), effect::get_duration(), effect::get_id(), effect::get_intensity(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_body_part(), and uilist::set_selected().
change_duration()
void debug_menu::effect_edit_callback::change_duration (const input_context & , const input_event & , int entnum, uilist &) inline private
Definition at line 389 of file wisheffect.cpp.
{
            cata::optional<time_duration> dur = query_duration();
            if( dur ) {
                on_creature_changed();
                foreach_effect( c, meta[entnum], [&]( const effect & eff ) {
                    effect &e = c.get_effect( eff.get_id(), eff.get_bp()->token );
                    if( !e.is_null() ) {
                        e.set_duration( *dur );
                    }
                } );
            }
        }
References c, debug_menu::anonymous_namespace{wisheffect.cpp}::foreach_effect(), effect::get_bp(), effect::get_id(), effect::is_null(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration(), and body_part_type::token.
change_intensity()
void debug_menu::effect_edit_callback::change_intensity (const input_context & , const input_event & , int entnum, uilist &) inline private
Definition at line 376 of file wisheffect.cpp.
{
            cata::optional<int> new_intensity = query_intensity();
            if( new_intensity ) {
                on_creature_changed();
                foreach_effect( c, meta[entnum], [&]( const effect & eff ) {
                    effect &e = c.get_effect( eff.get_id(), eff.get_bp()->token );
                    if( !e.is_null() ) {
                        e.set_intensity( *new_intensity );
                    }
                } );
            }
        }
References c, debug_menu::anonymous_namespace{wisheffect.cpp}::foreach_effect(), effect::get_bp(), effect::get_id(), effect::is_null(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), and body_part_type::token.
clear_effects()
void debug_menu::effect_edit_callback::clear_effects (const input_context & , const input_event & , int , uilist &) inline private
Definition at line 334 of file wisheffect.cpp.
{
            on_creature_changed();
            c.clear_effects();
            if( !c.get_all_effects().empty() ) {
                debugmsg( "Couldn't clear effects" );
            }
        }
References c, and debugmsg.
get_handled_actions()
static std::map< std::string, effect_edit_fun > debug_menu::effect_edit_callback::get_handled_actions () inline static
Definition at line 283 of file wisheffect.cpp.
{
            return handled_actions;
        }
key()
bool debug_menu::effect_edit_callback::key (const input_context & ctx, const input_event & key, int entnum, uilist * parent_menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 288 of file wisheffect.cpp.
{
            const std::string &action = ctx.input_to_action( key );
            auto iter = handled_actions.find( action );
            if( iter != handled_actions.end() ) {
                // This ugly thing is a call to method using a pointer-to-member-method
                ( ( *this ).*( iter->second ) )( ctx, key, entnum, *parent_menu );
                return true;
            }
            return false;
        }
References action, and input_context::input_to_action().
remove()
void debug_menu::effect_edit_callback::remove (const input_context & , const input_event & , int entnum, uilist &) inline private
Definition at line 342 of file wisheffect.cpp.
{
            on_creature_changed();
            foreach_effect( c, meta[entnum], [&]( const effect & eff ) {
                bool removed = c.remove_effect( eff.get_id(), eff.get_bp()->token );
                if( !removed ) {
                    debugmsg( "Couldn't remove %s from %s",
                              eff.get_id().str(),
                              eff.get_bp().str() );
                }
            } );
        }
References c, debug_menu::anonymous_namespace{wisheffect.cpp}::foreach_effect(), effect::get_bp(), effect::get_id(), and body_part_type::token.
toggle_force()
void debug_menu::effect_edit_callback::toggle_force (const input_context & , const input_event & , int , uilist &) inline private
Definition at line 402 of file wisheffect.cpp.
{
            toggle_effect_force();
        }
References debug_menu::anonymous_namespace{wisheffect.cpp}::toggle_effect_force().
Member Data Documentation
all_effects
const std::vector<efftype_id> debug_menu::effect_edit_callback::all_effects = find_all_effect_types() private
Definition at line 269 of file wisheffect.cpp.
c
Creature& debug_menu::effect_edit_callback::c private
Definition at line 266 of file wisheffect.cpp.
handled_actions
const std::map< std::string, effect_edit_callback::effect_edit_fun > debug_menu::effect_edit_callback::handled_actions static private
Initial value:
= {{
        { "ADD_NEW_EFFECT", &effect_edit_callback::add_effect_submenu },
        { "CLEAR_EFFECTS", &effect_edit_callback::clear_effects },
        { "REMOVE", &effect_edit_callback::remove },
        { "CHANGE_BODY_PART", &effect_edit_callback::change_body_part },
        { "CHANGE_INTENSITY", &effect_edit_callback::change_intensity },
        { "CHANGE_DURATION", &effect_edit_callback::change_duration },
        { "TOGGLE_FORCE", &effect_edit_callback::toggle_force },
    }
}
Definition at line 264 of file wisheffect.cpp.
meta
const std::vector<entry_data> debug_menu::effect_edit_callback::meta private
Definition at line 271 of file wisheffect.cpp.
on_creature_changed
std::function<void()> debug_menu::effect_edit_callback::on_creature_changed private
Definition at line 272 of file wisheffect.cpp.
The documentation for this class was generated from the following file:
src/wisheffect.cpp