Cataclysm BN: mapgen_function_json Class Reference
mapgen_function_json Class Reference
#include <mapgen.h>
Public Member Functions
void setup () override
void check (const std::string &oter_name) const override
void generate (mapgendata &) override
mapgen_function_json (const json_source_location &jsrcloc, int w, const point &grid_offset, const point &grid_total)
~mapgen_function_json () override=default
Public Member Functions inherited from mapgen_function_json_base
bool check_inbounds (const jmapgen_int &x, const jmapgen_int &y, const JsonObject &jso) const
size_t calc_index (const point &p) const
bool has_vehicle_collision (mapgendata &dat, const point &offset) const
Public Member Functions inherited from mapgen_function
virtual ~mapgen_function ()=default
Public Attributes
ter_id fill_ter
oter_id predecessor_mapgen
Public Attributes inherited from mapgen_function
int weight
Protected Member Functions
bool setup_internal (const JsonObject &jo) override
Protected Member Functions inherited from mapgen_function_json_base
mapgen_function_json_base (const json_source_location &jsrcloc)
virtual ~mapgen_function_json_base ()
void setup_common ()
bool setup_common (const JsonObject &jo)
void setup_setmap (const JsonArray &parray)
virtual void setup_setmap_internal ()
void check_common (const std::string &oter_name) const
void formatted_set_incredibly_simple (map &m, const point &offset) const
Protected Member Functions inherited from mapgen_function
mapgen_function (const int w)
Private Attributes
jmapgen_int rotation
Additional Inherited Members
Protected Attributes inherited from mapgen_function_json_base
bool do_format
bool is_ready
point mapgensize
point m_offset
std::vector< ter_furn_id > format
point total_size
std::vector< jmapgen_setmap > setmap_points
jmapgen_objects objects
Detailed Description
Definition at line 348 of file mapgen.h.
Constructor & Destructor Documentation
mapgen_function_json()
mapgen_function_json::mapgen_function_json (const json_source_location & jsrcloc, int w, const point & grid_offset, const point & grid_total)
Definition at line 610 of file mapgen.cpp.
    : mapgen_function( w )
    , mapgen_function_json_base( jsrcloc )
    , fill_ter( t_null )
    , rotation( 0 )
{
    m_offset.x = grid_offset.x * mapgensize.x;
    m_offset.y = grid_offset.y * mapgensize.y;
    total_size.x = grid_total.x * mapgensize.x;
    total_size.y = grid_total.y * mapgensize.y;
    objects = jmapgen_objects( m_offset, mapgensize, total_size );
}
References mapgen_function_json_base::m_offset, mapgen_function_json_base::mapgensize, mapgen_function_json_base::objects, mapgen_function_json_base::total_size, point::x, and point::y.
~mapgen_function_json()
mapgen_function_json::~mapgen_function_json () override default
Member Function Documentation
check()
void mapgen_function_json::check (const std::string & oter_name) const override virtual
Reimplemented from mapgen_function.
Definition at line 2556 of file mapgen.cpp.
{
    check_common( oter_name );
}
References mapgen_function_json_base::check_common().
generate()
void mapgen_function_json::generate (mapgendata & md) override virtual
Implements mapgen_function.
Definition at line 2802 of file mapgen.cpp.
{
    map *const m = &md.m;
    if( fill_ter != t_null ) {
        m->draw_fill_background( fill_ter );
    }
    if( predecessor_mapgen != oter_str_id::NULL_ID() ) {
        mapgendata predecessor_mapgen_dat( md, predecessor_mapgen );
        run_mapgen_func( predecessor_mapgen.id().str(), predecessor_mapgen_dat );
        // Now we have to do some rotation shenanigans. We need to ensure that
        // our predecessor is not rotated out of alignment as part of rotating this location,
        // and there are actually two sources of rotation--the mapgen can rotate explicitly, and
        // the entire overmap terrain may be rotatable. To ensure we end up in the right rotation,
        // we basically have to initially reverse the rotation that we WILL do in the future so that
        // when we apply that rotation, our predecessor is back in its original state while this
        // location is rotated as desired.
        m->rotate( ( -rotation.get() + 4 ) % 4 );
        if( md.terrain_type()->is_rotatable() ) {
            m->rotate( ( -static_cast<int>( md.terrain_type()->get_dir() ) + 4 ) % 4 );
        }
    }
    if( do_format ) {
        formatted_set_incredibly_simple( *m, point_zero );
    }
    for( auto &elem : setmap_points ) {
        elem.apply( md, point_zero );
    }
    objects.apply( md, point_zero );
    resolve_regional_terrain_and_furniture( md );
    m->rotate( rotation.get() );
    if( md.terrain_type()->is_rotatable() ) {
        mapgen_rotate( m, md.terrain_type(), false );
    }
}
References jmapgen_objects::apply(), mapgen_function_json_base::do_format, map::draw_fill_background(), fill_ter, mapgen_function_json_base::formatted_set_incredibly_simple(), jmapgen_int::get(), oter_t::get_dir(), int_id< T >::id(), oter_t::is_rotatable(), mapgendata::m, mapgen_rotate(), string_id< oter_t >::NULL_ID(), mapgen_function_json_base::objects, point_zero, predecessor_mapgen, resolve_regional_terrain_and_furniture(), map::rotate(), rotation, run_mapgen_func(), mapgen_function_json_base::setmap_points, string_id< T >::str(), t_null, and mapgendata::terrain_type().
setup()
void mapgen_function_json::setup () override virtual
Reimplemented from mapgen_function.
Definition at line 2369 of file mapgen.cpp.
{
    setup_common();
}
References mapgen_function_json_base::setup_common().
setup_internal()
bool mapgen_function_json::setup_internal (const JsonObject & jo) override protected virtual
Implements mapgen_function_json_base.
Definition at line 2321 of file mapgen.cpp.
{
    // Just to make sure no one does anything stupid
    if( jo.has_member( "mapgensize" ) ) {
        jo.throw_error( "\"mapgensize\" only allowed for nested mapgen" );
    }
    // something akin to mapgen fill_background.
    if( jo.has_string( "fill_ter" ) ) {
        fill_ter = ter_str_id( jo.get_string( "fill_ter" ) ).id();
    }
    if( jo.has_member( "rotation" ) ) {
        rotation = jmapgen_int( jo, "rotation" );
    }
    if( jo.has_member( "predecessor_mapgen" ) ) {
        predecessor_mapgen = oter_str_id( jo.get_string( "predecessor_mapgen" ) ).id();
    } else {
        predecessor_mapgen = oter_str_id::NULL_ID();
    }
    return fill_ter != t_null || predecessor_mapgen != oter_str_id::NULL_ID();
}
References fill_ter, JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_string(), string_id< T >::id(), string_id< oter_t >::NULL_ID(), predecessor_mapgen, rotation, t_null, and JsonObject::throw_error().
Member Data Documentation
fill_ter
ter_id mapgen_function_json::fill_ter
Definition at line 358 of file mapgen.h.
Referenced by generate(), and setup_internal().
predecessor_mapgen
oter_id mapgen_function_json::predecessor_mapgen
Definition at line 359 of file mapgen.h.
Referenced by generate(), and setup_internal().
rotation
jmapgen_int mapgen_function_json::rotation private
Definition at line 365 of file mapgen.h.
Referenced by generate(), and setup_internal().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp