Cataclysm BN: catacurses::window Class Reference
catacurses::window Class Reference
A wrapper over a pointer to a curses window.
#include <cursesdef.h>
Public Member Functions
window ()=default
window (std::shared_ptr< void > ptr)
template<typename T = void>
T * get () const
operator bool () const
bool operator== (const window &rhs) const
std::weak_ptr< void > weak_ptr () const
Private Attributes
std::shared_ptr< void > native_window
Detailed Description
A wrapper over a pointer to a curses window.
All curses functions here receive/return and operate on such a window. The objects have shared ownership of the contained pointer (behaves like a shared pointer).
Use newwin to get a new instance. Use the default constructor to get an invalid window pointer (test for this via operator bool()). Use the operator= to reset the pointer.
Definition at line 54 of file cursesdef.h.
Constructor & Destructor Documentation
window() [1/2]
catacurses::window::window () default
window() [2/2]
catacurses::window::window (std::shared_ptr< void > ptr) inline
Definition at line 61 of file cursesdef.h.
                                          : native_window( std::move( ptr ) ) {
        }
Member Function Documentation
get()
template<typename T = void> T * catacurses::window::get () const inline
Definition at line 64 of file cursesdef.h.
{
            return static_cast<T *>( native_window.get() );
        }
References native_window.
Referenced by catacurses::getbegx(), catacurses::getbegy(), catacurses::getcurx(), catacurses::getcury(), catacurses::getmaxx(), catacurses::getmaxy(), catacurses::init_interface(), worldfactory::make_new_world(), catacurses::mvwaddch(), catacurses::mvwhline(), catacurses::mvwprintw(), catacurses::mvwvline(), catacurses::resizeterm(), catacurses::waddch(), catacurses::wattroff(), catacurses::wattron(), catacurses::wborder(), catacurses::wclear(), catacurses::werase(), catacurses::wmove(), catacurses::wnoutrefresh(), catacurses::wprintw(), catacurses::wredrawln(), and catacurses::wrefresh().
operator bool()
catacurses::window::operator bool () const inline explicit
Definition at line 67 of file cursesdef.h.
{
            return native_window.operator bool();
        }
References native_window.
operator==()
bool catacurses::window::operator== (const window & rhs) const inline
Definition at line 70 of file cursesdef.h.
{
            return native_window.get() == rhs.native_window.get();
        }
References native_window.
weak_ptr()
std::weak_ptr< void > catacurses::window::weak_ptr () const inline
Definition at line 73 of file cursesdef.h.
{
            return native_window;
        }
References native_window.
Member Data Documentation
native_window
std::shared_ptr<void> catacurses::window::native_window private
Definition at line 57 of file cursesdef.h.
Referenced by get(), operator bool(), operator==(), and weak_ptr().
The documentation for this class was generated from the following file:
src/cursesdef.h