Cataclysm BN: jmapgen_furniture Class Reference
jmapgen_furniture Class Reference
Place a furniture.
Public Member Functions
jmapgen_furniture (const JsonObject &jsi)
jmapgen_furniture (const std::string &fid)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, const point &p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
furn_id id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a furniture.
"furn": id of the furniture.
Definition at line 1470 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_furniture() [1/2]
jmapgen_furniture::jmapgen_furniture (const JsonObject & jsi) inline
Definition at line 1474 of file mapgen.cpp.
: jmapgen_furniture(jsi.get_string("furn")) {}
jmapgen_furniture() [2/2]
jmapgen_furniture::jmapgen_furniture (const std::string & fid) inline
Definition at line 1475 of file mapgen.cpp.
: id(furn_id(fid)) {}
Member Function Documentation
apply()
void jmapgen_furniture::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1476 of file mapgen.cpp.
{
            dat.m.furn_set( point( x.get(), y.get() ), id );
        }
References map::furn_set(), jmapgen_int::get(), and mapgendata::m.
has_vehicle_collision()
bool jmapgen_furniture::has_vehicle_collision (mapgendata & dat, const point & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1479 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
id
furn_id jmapgen_furniture::id
Definition at line 1473 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp