Cataclysm BN: JsonIn Class Reference
JsonIn Class Reference
#include <json.h>
Public Member Functions
JsonIn (std::istream &s)
JsonIn (std::istream &s, const std::string &path)
JsonIn (std::istream &s, const json_source_location &loc)
JsonIn (const JsonIn &)=delete
JsonIn & operator= (const JsonIn &)=delete
shared_ptr_fast< std::string > get_path () const
bool get_ate_separator ()
void set_ate_separator (bool s)
int tell ()
void seek (int pos)
char peek ()
bool good ()
void eat_whitespace ()
void uneat_whitespace ()
void skip_member ()
void skip_string ()
void skip_value ()
void skip_object ()
void skip_array ()
void skip_true ()
void skip_false ()
void skip_null ()
void skip_number ()
std::string get_string ()
int get_int ()
unsigned int get_uint ()
int64_t get_int64 ()
uint64_t get_uint64 ()
bool get_bool ()
double get_float ()
std::string get_member_name ()
JsonObject get_object ()
JsonArray get_array ()
template<typename E , typename = typename std::enable_if<std::is_enum<E>::value>::type>
E get_enum_value ()
void start_array ()
bool end_array ()
void start_object ()
bool end_object ()
bool test_null ()
bool test_bool ()
bool test_number ()
bool test_int ()
bool test_float ()
bool test_string ()
bool test_bitset ()
bool test_array ()
bool test_object ()
bool read (bool &b, bool throw_on_error=false)
bool read (char &c, bool throw_on_error=false)
bool read (signed char &c, bool throw_on_error=false)
bool read (unsigned char &c, bool throw_on_error=false)
bool read (short unsigned int &s, bool throw_on_error=false)
bool read (short int &s, bool throw_on_error=false)
bool read (int &i, bool throw_on_error=false)
bool read (int64_t &i, bool throw_on_error=false)
bool read (uint64_t &i, bool throw_on_error=false)
bool read (unsigned int &u, bool throw_on_error=false)
bool read (float &f, bool throw_on_error=false)
bool read (double &d, bool throw_on_error=false)
bool read (std::string &s, bool throw_on_error=false)
template<size_t N>
bool read (std::bitset< N > &b, bool throw_on_error=false)
bool read (JsonDeserializer &j, bool throw_on_error=false)
template<typename T >
auto read (T &thing, bool throw_on_error=false) -> decltype(thing.str(), true)
template<typename T >
auto read (T &v, bool throw_on_error=false) -> decltype(deserialize(v, *this), true)
Overload that calls a global function deserialize(T&,JsonIn&), if available.
template<typename T >
auto read (T &v, bool throw_on_error=false) -> decltype(v.deserialize(*this), true)
Overload that calls a member function T::deserialize(JsonIn&), if available.
template<typename T , std::enable_if_t< std::is_enum< T >::value, int > = 0>
bool read (T &val, bool throw_on_error=false)
template<typename T , typename U >
bool read (std::pair< T, U > &p, bool throw_on_error=false)
Overload for std::pair.
template<typename T , typename std::enable_if< !std::is_same< void, typename T::value_type >::value >::type * = nullptr>
auto read (T &v, bool throw_on_error=false) -> decltype(v.front(), true)
template<typename T , size_t N>
bool read (std::array< T, N > &v, bool throw_on_error=false)
template<typename T , typename std::enable_if< std::is_same< typename T::key_type, typename T::value_type >::value >::type * = nullptr>
bool read (T &v, bool throw_on_error=false)
template<typename T , typename U , typename V >
bool read (cata::colony< T, U, V > &v, bool throw_on_error=false)
template<typename T , typename std::enable_if< !std::is_same< typename T::key_type, typename T::value_type >::value >::type * = nullptr>
bool read (T &m, bool throw_on_error=true)
std::string line_number (int offset_modifier=0)
void error (const std::string &message, int offset=0)
void string_error (const std::string &message, int offset)
bool error_or_false (bool throw_, const std::string &message, int offset=0)
void rewind (int max_lines=-1, int max_chars=-1)
std::string substr (size_t pos, size_t len=std::string::npos)
Private Member Functions
void skip_separator ()
void skip_pair_separator ()
void end_value ()
number_sci_notation get_any_number ()
number_sci_notation get_any_int ()
Private Attributes
std::istream * stream
shared_ptr_fast< std::string > path
bool ate_separator = false
Detailed Description
Definition at line 176 of file json.h.
Constructor & Destructor Documentation
JsonIn() [1/4]
JsonIn::JsonIn (std::istream & s) inline
Definition at line 188 of file json.h.
: stream(&s) {}
JsonIn() [2/4]
JsonIn::JsonIn (std::istream & s, const std::string & path) inline
Definition at line 189 of file json.h.
            : stream( &s ), path( make_shared_fast<std::string>( path ) ) {}
JsonIn() [3/4]
JsonIn::JsonIn (std::istream & s, const json_source_location & loc) inline
Definition at line 191 of file json.h.
            : stream( &s ), path( loc.path ) {
            seek( loc.offset );
        }
References json_source_location::offset, and seek().
JsonIn() [4/4]
JsonIn::JsonIn (const JsonIn &) delete
Member Function Documentation
eat_whitespace()
void JsonIn::eat_whitespace ()
Definition at line 748 of file json.cpp.
{
    while( is_whitespace( peek() ) ) {
        stream->get();
    }
}
References is_whitespace(), peek(), and stream.
Referenced by end_array(), end_object(), get_any_number(), get_bool(), get_string(), DynamicDataLoader::load_all_from_json(), skip_false(), skip_null(), skip_number(), skip_pair_separator(), skip_separator(), skip_string(), skip_true(), skip_value(), start_array(), start_object(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), and test_string().
end_array()
bool JsonIn::end_array ()
Definition at line 1389 of file json.cpp.
{
    eat_whitespace();
    if( peek() == ']' ) {
        if( ate_separator ) {
            uneat_whitespace();
            error( "comma not allowed at end of array" );
        }
        stream->get();
        end_value();
        return true;
    } else {
        // not the end yet, so just return false?
        return false;
    }
}
References ate_separator, eat_whitespace(), end_value(), error(), peek(), stream, and uneat_whitespace().
Referenced by cata_variant::deserialize(), auto_pickup::rule_list::deserialize(), color_manager::deserialize(), Creature_tracker::deserialize(), faction_manager::deserialize(), help::deserialize(), iuse_location::deserialize(), mm_submap::deserialize(), mm_region::deserialize(), mapbuffer::deserialize(), options_manager::deserialize(), panel_manager::deserialize(), pickup::act_item::deserialize(), point::deserialize(), tripoint::deserialize(), safemode::deserialize(), shape_factory::deserialize(), deserialize(), mongroup::deserialize_legacy(), generic_typed_reader< Derived >::erase_values_from(), generic_typed_reader< Derived >::insert_values_from(), inventory::json_load_items(), JsonArray::JsonArray(), input_manager::load(), Name::load(), submap::load(), DynamicDataLoader::load_all_from_json(), load_artifacts(), color_loader< ColorType >::load_colorfile(), map_memory::load_legacy(), overmap::load_legacy_monstergroups(), overmap::load_monster_groups(), load_optional_enum_array(), WORLD::load_options(), mod_manager::load_replacement_mods(), avatar::load_template(), read(), skip_array(), overmap::unserialize(), mission::unserialize_all(), unserialize_array_from_compacted_sequence(), and overmap::unserialize_view().
end_object()
bool JsonIn::end_object ()
Definition at line 1422 of file json.cpp.
{
    eat_whitespace();
    if( peek() == '}' ) {
        if( ate_separator ) {
            uneat_whitespace();
            error( "comma not allowed at end of object" );
        }
        stream->get();
        end_value();
        return true;
    } else {
        // not the end yet, so just return false?
        return false;
    }
}
References ate_separator, eat_whitespace(), end_value(), error(), peek(), stream, and uneat_whitespace().
Referenced by faction_manager::deserialize(), mapbuffer::deserialize(), mongroup::deserialize_legacy(), JsonObject::JsonObject(), read(), skip_object(), overmap::unserialize(), game::unserialize_master(), and overmap::unserialize_view().
end_value()
void JsonIn::end_value () private
Definition at line 765 of file json.cpp.
{
    ate_separator = false;
    skip_separator();
}
References ate_separator, and skip_separator().
Referenced by end_array(), end_object(), get_any_number(), get_bool(), get_string(), skip_false(), skip_null(), skip_number(), skip_string(), and skip_true().
error()
void JsonIn::error (const std::string & message, int offset = 0)
Definition at line 1678 of file json.cpp.
{
    std::ostringstream err;
    err << "Json error: " << line_number( offset ) << ": " << message;
    // if we can't get more info from the stream don't try
    if( !stream->good() ) {
        throw JsonError( err.str() );
    }
    // also print surrounding few lines of context, if not too large
    err << "\n\n";
    stream->seekg( offset, std::istream::cur );
    size_t pos = tell();
    rewind( 3, 240 );
    size_t startpos = tell();
    std::string buffer( pos - startpos, '\0' );
    stream->read( &buffer[0], pos - startpos );
    auto it = buffer.begin();
    for( ; it < buffer.end() && ( *it == '\r' || *it == '\n' ); ++it ) {
        // skip starting newlines
    }
    for( ; it < buffer.end(); ++it ) {
        if( *it == '\r' ) {
            err << '\n';
            if( it + 1 < buffer.end() && *( it + 1 ) == '\n' ) {
                ++it;
            }
        } else {
            err << *it;
        }
    }
    if( !is_whitespace( peek() ) ) {
        err << peek();
    }
    // display a pointer to the position
    rewind( 1, 240 );
    startpos = tell();
    err << '\n';
    if( pos > startpos ) {
        err << std::string( pos - startpos, ' ' );
    }
    err << "^\n";
    seek( pos );
    // if that wasn't the end of the line, continue underneath pointer
    char ch = stream->get();
    if( ch == '\r' ) {
        if( peek() == '\n' ) {
            stream->get();
        }
    } else if( ch == '\n' ) {
        // pass
    } else if( peek() != '\r' && peek() != '\n' && !stream->eof() ) {
        for( size_t i = 0; i < pos - startpos + 1; ++i ) {
            err << ' ';
        }
    }
    // print the next couple lines as well
    int line_count = 0;
    for( int i = 0; line_count < 3 && stream->good() && i < 240; ++i ) {
        stream->get( ch );
        if( !stream->good() ) {
            break;
        }
        if( ch == '\r' ) {
            ch = '\n';
            ++line_count;
            if( stream->peek() == '\n' ) {
                stream->get( ch );
            }
        } else if( ch == '\n' ) {
            ++line_count;
        }
        err << ch;
    }
    std::string msg = err.str();
    if( !msg.empty() && msg.back() != '\n' ) {
        msg.push_back( '\n' );
    }
    throw JsonError( msg );
}
References is_whitespace(), line_number(), mapgen_defer::message, peek(), rewind(), seek(), stream, and tell().
Referenced by cata_variant::deserialize(), damage_instance::deserialize(), nc_color::deserialize(), end_array(), end_object(), error_or_false(), get_any_int(), get_any_number(), get_bool(), get_enum_value(), get_int(), get_int64(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), JsonObject::get_source_location(), get_string(), get_uint(), get_uint64(), JsonObject::JsonObject(), DynamicDataLoader::load_all_from_json(), DynamicDataLoader::load_deferred(), read(), read_from_json_string(), mapgen_function_json_base::setup_common(), skip_false(), skip_null(), skip_pair_separator(), skip_separator(), skip_string(), skip_true(), skip_value(), start_array(), start_object(), string_error(), JsonValue::throw_error(), JsonArray::throw_error(), JsonObject::throw_error(), JsonArray::verify_index(), and JsonObject::verify_position().
error_or_false()
bool JsonIn::error_or_false (bool throw_, const std::string & message, int offset = 0)
Definition at line 1774 of file json.cpp.
{
    if( throw_ ) {
        error( message, offset );
    }
    return false;
}
References error(), and mapgen_defer::message.
Referenced by read().
get_any_int()
number_sci_notation JsonIn::get_any_int () private
Definition at line 1170 of file json.cpp.
{
    number_sci_notation n = get_any_number();
    if( n.exp < 0 ) {
        error( "Integers cannot have a decimal point or negative order of magnitude." );
    }
    // Manually apply scientific notation, since std::pow converts to double under the hood.
    for( int64_t i = 0; i < n.exp; i++ ) {
        if( n.number > std::numeric_limits<uint64_t>::max() / 10ULL ) {
            error( "Specified order of magnitude too large -- encountered overflow applying it." );
        }
        n.number *= 10ULL;
    }
    n.exp = 0;
    return n;
}
References error(), number_sci_notation::exp, get_any_number(), and number_sci_notation::number.
Referenced by get_int(), get_int64(), get_uint(), and get_uint64().
get_any_number()
number_sci_notation JsonIn::get_any_number () private
Definition at line 1270 of file json.cpp.
{
    // this could maybe be prettier?
    char ch;
    number_sci_notation ret;
    int mod_e = 0;
    eat_whitespace();
    stream->get( ch );
    if( ( ret.negative = ch == '-' ) ) {
        stream->get( ch );
    } else if( ch != '.' && ( ch < '0' || ch > '9' ) ) {
        // not a valid float
        std::stringstream err;
        err << "expecting number but found '" << ch << "'";
        error( err.str(), -1 );
    }
    if( ch == '0' ) {
        // allow a single leading zero in front of a '.' or 'e'/'E'
        stream->get( ch );
        if( ch >= '0' && ch <= '9' ) {
            error( "leading zeros not allowed", -1 );
        }
    }
    while( ch >= '0' && ch <= '9' ) {
        ret.number *= 10;
        ret.number += ( ch - '0' );
        stream->get( ch );
    }
    if( ch == '.' ) {
        stream->get( ch );
        while( ch >= '0' && ch <= '9' ) {
            ret.number *= 10;
            ret.number += ( ch - '0' );
            mod_e -= 1;
            stream->get( ch );
        }
    }
    if( ch == 'e' || ch == 'E' ) {
        stream->get( ch );
        bool neg;
        if( ( neg = ch == '-' ) ) {
            stream->get( ch );
        } else if( ch == '+' ) {
            stream->get( ch );
        }
        while( ch >= '0' && ch <= '9' ) {
            ret.exp *= 10;
            ret.exp += ( ch - '0' );
            stream->get( ch );
        }
        if( neg ) {
            ret.exp *= -1;
        }
    }
    // unget the final non-number character (probably a separator)
    stream->unget();
    end_value();
    ret.exp += mod_e;
    return ret;
}
References eat_whitespace(), end_value(), error(), cata::hash64_detail::ret, and stream.
Referenced by get_any_int(), and get_float().
get_array()
JsonArray JsonIn::get_array ()
Definition at line 1368 of file json.cpp.
{
    return JsonArray( *this );
}
Referenced by damage_instance::deserialize(), JsonValue::get_array(), JsonArray::get_array(), item_reader::get_next(), JsonObject::get_tags(), JsonArray::get_tags(), inventory::json_load_invcache(), load_languages(), mod_manager::load_mods_list(), JsonArray::next_array(), and JsonValue::operator JsonArray().
get_ate_separator()
bool JsonIn::get_ate_separator () inline
Definition at line 202 of file json.h.
{
            return ate_separator;
        }
References ate_separator.
Referenced by JsonArray::JsonArray(), and JsonObject::JsonObject().
get_bool()
bool JsonIn::get_bool ()
Definition at line 1331 of file json.cpp.
{
    char ch;
    char text[5];
    std::stringstream err;
    eat_whitespace();
    stream->get( ch );
    if( ch == 't' ) {
        stream->get( text, 4 );
        if( strcmp( text, "rue" ) == 0 ) {
            end_value();
            return true;
        } else {
            err << R"(not a boolean.  expected "true", but got ")";
            err << ch << text << "\"";
            error( err.str(), -4 );
        }
    } else if( ch == 'f' ) {
        stream->get( text, 5 );
        if( strcmp( text, "alse" ) == 0 ) {
            end_value();
            return false;
        } else {
            err << R"(not a boolean.  expected "false", but got ")";
            err << ch << text << "\"";
            error( err.str(), -5 );
        }
    }
    err << "not a boolean value!  expected 't' or 'f' but got '" << ch << "'";
    error( err.str(), -1 );
    throw JsonError( "warnings are silly" );
}
References eat_whitespace(), end_value(), error(), and stream.
Referenced by mongroup::deserialize_legacy(), JsonValue::get_bool(), JsonObject::get_bool(), JsonArray::get_bool(), submap::load(), JsonArray::next_bool(), JsonValue::operator bool(), and read().
get_enum_value()
template<typename E , typename = typename std::enable_if<std::is_enum<E>::value>::type> E JsonIn::get_enum_value () inline
Definition at line 243 of file json.h.
{
            const auto old_offset = tell();
            try {
                return io::string_to_enum<E>( get_string() );
            } catch( const io::InvalidEnumString & ) {
                seek( old_offset ); // so the error message points to the correct place.
                error( "invalid enumeration value" );
            }
        }
References error(), get_string(), seek(), and tell().
Referenced by JsonObject::get_enum_value(), and load_optional_enum_array().
get_float()
double JsonIn::get_float ()
Definition at line 1264 of file json.cpp.
{
    number_sci_notation n = get_any_number();
    return n.number * std::pow( 10.0f, n.exp ) * ( n.negative ? -1.f : 1.f );
}
References number_sci_notation::exp, get_any_number(), number_sci_notation::negative, and number_sci_notation::number.
Referenced by JsonValue::get_float(), JsonObject::get_float(), JsonArray::get_float(), JsonArray::next_float(), JsonValue::operator double(), and read().
get_int()
int JsonIn::get_int ()
Definition at line 1187 of file json.cpp.
{
    static_assert( sizeof( int ) <= sizeof( int64_t ),
                   "JsonIn::get_int() assumed sizeof( int ) <= sizeof( int64_t )" );
    number_sci_notation n = get_any_int();
    if( !n.negative && n.number > static_cast<uint64_t>( std::numeric_limits<int>::max() ) ) {
        error( "Found a number greater than " + std::to_string( std::numeric_limits<int>::max() ) +
               " which is unsupported in this context." );
    } else if( n.negative && n.number > neg_INT_MIN() ) {
        error( "Found a number less than " + std::to_string( std::numeric_limits<int>::min() ) +
               " which is unsupported in this context." );
    }
    if( n.negative ) {
        static_assert( neg_INT_MIN() <= static_cast<uint64_t>( std::numeric_limits<int>::max() )
                       || neg_INT_MIN() - static_cast<uint64_t>( std::numeric_limits<int>::max() )
                       <= static_cast<uint64_t>( std::numeric_limits<int>::max() ),
                       "JsonIn::get_int() assumed -INT_MIN - INT_MAX <= INT_MAX" );
        if( n.number > static_cast<uint64_t>( std::numeric_limits<int>::max() ) ) {
            const uint64_t x = n.number - static_cast<uint64_t>( std::numeric_limits<int>::max() );
            return -std::numeric_limits<int>::max() - static_cast<int>( x );
        } else {
            return -static_cast<int>( n.number );
        }
    } else {
        return static_cast<int>( n.number );
    }
}
References error(), get_any_int(), neg_INT_MIN(), number_sci_notation::negative, number_sci_notation::number, and to_string().
Referenced by character_id::deserialize(), time_duration::deserialize(), time_point::deserialize(), nc_color::deserialize(), mm_submap::deserialize(), mapbuffer::deserialize(), point::deserialize(), tripoint::deserialize(), mongroup::deserialize_legacy(), JsonValue::get_int(), JsonObject::get_int(), JsonArray::get_int(), submap::load(), map_memory::load_legacy(), JsonArray::next_int(), JsonValue::operator int(), read(), and game::unserialize_master().
get_int64()
int64_t JsonIn::get_int64 ()
Definition at line 1229 of file json.cpp.
{
    number_sci_notation n = get_any_int();
    if( !n.negative && n.number > static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) ) {
        error( "Signed integers greater than " +
               std::to_string( std::numeric_limits<int64_t>::max() ) + " not supported." );
    } else if( n.negative && n.number > neg_INT64_MIN() ) {
        error( "Integers less than "
               + std::to_string( std::numeric_limits<int64_t>::min() ) + " not supported." );
    }
    if( n.negative ) {
        static_assert( neg_INT64_MIN() <= static_cast<uint64_t>( std::numeric_limits<int64_t>::max() )
                       || neg_INT64_MIN() - static_cast<uint64_t>( std::numeric_limits<int64_t>::max() )
                       <= static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ),
                       "JsonIn::get_int64() assumed -INT64_MIN - INT64_MAX <= INT64_MAX" );
        if( n.number > static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) ) {
            const uint64_t x = n.number - static_cast<uint64_t>( std::numeric_limits<int64_t>::max() );
            return -std::numeric_limits<int64_t>::max() - static_cast<int64_t>( x );
        } else {
            return -static_cast<int64_t>( n.number );
        }
    } else {
        return static_cast<int64_t>( n.number );
    }
}
References error(), get_any_int(), neg_INT64_MIN(), number_sci_notation::negative, number_sci_notation::number, and to_string().
get_member_name()
std::string JsonIn::get_member_name ()
Definition at line 955 of file json.cpp.
{
    std::string s = get_string();
    skip_pair_separator();
    return s;
}
References get_string(), and skip_pair_separator().
Referenced by faction_manager::deserialize(), mapbuffer::deserialize(), mongroup::deserialize_legacy(), JsonObject::JsonObject(), read(), overmap::unserialize(), game::unserialize_master(), and overmap::unserialize_view().
get_object()
JsonObject JsonIn::get_object ()
Definition at line 1364 of file json.cpp.
{
    return JsonObject( *this );
}
Referenced by deserialize(), achievement::time_bound::deserialize(), achievement_state::deserialize(), achievements_tracker::deserialize(), damage_instance::deserialize(), kill_tracker::deserialize(), event_multiset::deserialize(), stats_tracker::deserialize(), mongroup::deserialize(), achievement_requirement::deserialize(), computer_option::deserialize(), computer_failure::deserialize(), computer::deserialize(), pickup::pick_drop_selection::deserialize(), item_location::deserialize(), active_tiles::furn_transform::deserialize(), aim_activity_actor::deserialize(), dig_activity_actor::deserialize(), dig_channel_activity_actor::deserialize(), disassemble_activity_actor::deserialize(), drop_activity_actor::deserialize(), hacking_activity_actor::deserialize(), move_items_activity_actor::deserialize(), open_gate_activity_actor::deserialize(), pickup_activity_actor::deserialize(), stash_activity_actor::deserialize(), throw_activity_actor::deserialize(), wash_activity_actor::deserialize(), auto_pickup::rule::deserialize(), basecamp::deserialize(), bionic::deserialize(), bodypart::deserialize(), Character::trait_data::deserialize(), character_martial_arts::deserialize(), zone_data::deserialize(), color_manager::deserialize(), consumption_event::deserialize(), comp_selection< CompType >::deserialize(), item_drop_token::deserialize(), drop_token_provider::deserialize(), effect::deserialize(), value_constraint::deserialize(), new_field::deserialize(), faction::deserialize(), help::deserialize(), item::deserialize(), item::craft_data::deserialize(), zone_priority_data::deserialize(), item_contents::deserialize(), islot_ammo::deserialize(), fake_spell::deserialize(), known_magic::deserialize(), teleporter_list::deserialize(), ranged_bash_info::deserialize(), map_bash_info::deserialize(), furn_workbench_info::deserialize(), plant_data::deserialize(), mission::deserialize(), monster::deserialize(), player_morale::morale_subtype::deserialize(), player_morale::morale_point::deserialize(), job_data::deserialize(), npc_personality::deserialize(), npc_opinion::deserialize(), npc_follower_rules::deserialize(), npc_chatbin::deserialize(), npc_favor::deserialize(), options_manager::deserialize(), overmap_connection::subtype::deserialize(), panel_manager::deserialize(), player_activity::deserialize(), addiction::deserialize(), projectile::deserialize(), relic::deserialize(), requirement_data::deserialize(), safemode::deserialize(), SkillLevel::deserialize(), translation::deserialize(), vehicle_part::deserialize(), label::deserialize(), vehicle::deserialize(), avatar::deserialize(), extended_photo_def::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), npc::deserialize(), cone_factory::deserialize(), stomach_contents::deserialize(), ma_weapon_damage_reader::erase_next(), ma_skill_reader::get_next(), ma_weapon_damage_reader::get_next(), ma_buff_reader::get_next(), mon_attack_effect_reader::get_next(), skilllevel_reader::get_next(), addiction_reader::get_next(), JsonValue::get_object(), JsonObject::get_object(), JsonArray::get_object(), input_manager::load(), Name::load(), DynamicDataLoader::load_all_from_json(), color_loader< ColorType >::load_colorfile(), DynamicDataLoader::load_deferred(), worldfactory::load_last_world_info(), WORLD::load_options(), avatar::load_template(), font_loader::load_throws(), JsonArray::next_object(), JsonValue::operator JsonObject(), mapgen_function_json_base::setup_common(), game::unserialize(), and game::unserialize_master().
get_path()
shared_ptr_fast< std::string > JsonIn::get_path () const inline
Definition at line 198 of file json.h.
{
            return path;
        }
References path.
Referenced by JsonObject::get_source_location().
get_string()
std::string JsonIn::get_string ()
Definition at line 1096 of file json.cpp.
{
    eat_whitespace();
    std::string s;
    char ch;
    std::string err;
    bool success = false;
    do {
        // the first character had better be a '"'
        stream->get( ch );
        if( !stream->good() ) {
            err = "read operation failed";
            break;
        }
        if( ch != '"' ) {
            err = "expected string but got '" + std::string( 1, ch ) + "'";
            break;
        }
        // add chars to the string, one at a time
        do {
            ch = stream->peek();
            if( !stream->good() ) {
                err = "read operation failed";
                break;
            }
            if( ch == '"' ) {
                stream->ignore();
                success = true;
                break;
            }
            if( !get_escaped_or_unicode( *stream, s, err ) ) {
                break;
            }
        } while( stream->good() );
    } while( false );
    if( success ) {
        end_value();
        return s;
    }
    if( stream->eof() ) {
        error( "couldn't find end of string, reached EOF." );
    } else if( stream->fail() ) {
        error( "stream failure while reading string." );
    } else {
        error( err, -1 );
    }
}
References eat_whitespace(), end_value(), error(), get_escaped_or_unicode(), stream, and behavior::success.
Referenced by computer::deserialize(), nc_color::deserialize(), mm_submap::deserialize(), shape_factory::deserialize(), translation::deserialize(), deserialize(), mongroup::deserialize_legacy(), ma_skill_reader::erase_next(), mon_attack_effect_reader::erase_next(), skilllevel_reader::erase_next(), addiction_reader::erase_next(), item_reader::erase_next(), get_enum_value(), get_member_name(), auto_flags_reader< FlagType >::get_next(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), string_id_reader< T >::get_next(), ma_buff_reader::get_next(), item_reader::get_next(), JsonValue::get_string(), JsonObject::get_string(), JsonArray::get_string(), JsonObject::get_tags(), JsonArray::get_tags(), submap::load(), map_memory::load_legacy(), JsonArray::next_string(), JsonValue::operator std::string(), read(), read_from_json_string(), and overmap::unserialize().
get_uint()
unsigned int JsonIn::get_uint ()
Definition at line 1215 of file json.cpp.
{
    number_sci_notation n = get_any_int();
    if( n.number > std::numeric_limits<unsigned int>::max() ) {
        error( "Found a number greater than " +
               std::to_string( std::numeric_limits<unsigned int>::max() ) +
               " which is unsupported in this context." );
    }
    if( n.negative ) {
        error( "Unsigned integers cannot have a negative sign." );
    }
    return static_cast<unsigned int>( n.number );
}
References error(), get_any_int(), number_sci_notation::negative, number_sci_notation::number, and to_string().
Referenced by read().
get_uint64()
uint64_t JsonIn::get_uint64 ()
Definition at line 1255 of file json.cpp.
{
    number_sci_notation n = get_any_int();
    if( n.negative ) {
        error( "Unsigned integers cannot have a negative sign." );
    }
    return n.number;
}
References error(), get_any_int(), number_sci_notation::negative, and number_sci_notation::number.
good()
bool JsonIn::good ()
Definition at line 736 of file json.cpp.
{
    return stream->good();
}
References stream.
Referenced by JsonObject::finish(), JsonArray::finish(), and DynamicDataLoader::load_all_from_json().
line_number()
std::string JsonIn::line_number (int offset_modifier = 0)
Definition at line 1640 of file json.cpp.
{
    const std::string &name = path ? *path : "<unknown source file>";
    if( stream && stream->eof() ) {
        return name + ":EOF";
    } else if( !stream || stream->fail() ) {
        return name + ":???";
    } // else stream is fine
    int pos = tell();
    int line = 1;
    int offset = 1;
    char ch;
    seek( 0 );
    for( int i = 0; i < pos + offset_modifier; ++i ) {
        stream->get( ch );
        if( !stream->good() ) {
            break;
        }
        if( ch == '\r' ) {
            offset = 1;
            ++line;
            if( peek() == '\n' ) {
                stream->get();
                ++i;
            }
        } else if( ch == '\n' ) {
            offset = 1;
            ++line;
        } else {
            ++offset;
        }
    }
    seek( pos );
    std::stringstream ret;
    ret << name << ":" << line << ":" << offset;
    return ret.str();
}
References line(), om_direction::name(), path, peek(), cata::hash64_detail::ret, seek(), stream, and tell().
Referenced by error(), and JsonObject::line_number().
operator=()
JsonIn & JsonIn::operator= (const JsonIn &) delete
peek()
char JsonIn::peek ()
Definition at line 732 of file json.cpp.
{
    return static_cast<char>( stream->peek() );
}
References stream.
Referenced by eat_whitespace(), end_array(), end_object(), error(), line_number(), DynamicDataLoader::load_all_from_json(), rewind(), skip_separator(), skip_value(), start_array(), start_object(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), and uneat_whitespace().
read() [1/25]
bool JsonIn::read (bool & b, bool throw_on_error = false)
Definition at line 1485 of file json.cpp.
{
    if( !test_bool() ) {
        return error_or_false( throw_on_error, "Expected bool" );
    }
    b = get_bool();
    return true;
}
References b, error_or_false(), get_bool(), and test_bool().
Referenced by assign_map_from_array(), deserialize(), cata_variant::deserialize(), zone_manager::deserialize(), consumption_history_t::deserialize(), Creature_tracker::deserialize(), faction_manager::deserialize(), iuse_location::deserialize(), pickup::act_item::deserialize(), item_read_extended_photos(), submap::load(), JsonObject::read(), JsonArray::read(), JsonValue::read(), read(), JsonArray::read_next(), vehicle::restore(), overmap::unserialize(), unserialize_array_from_compacted_sequence(), game::unserialize_master(), overmap::unserialize_view(), and unfold_vehicle_iuse::use().
read() [2/25]
template<typename T , typename U , typename V > bool JsonIn::read (cata::colony< T, U, V > & v, bool throw_on_error = false) inline
Definition at line 473 of file json.h.
{
            if( !test_array() ) {
                return error_or_false( throw_on_error, "Expected json array" );
            }
            try {
                start_array();
                v.clear();
                while( !end_array() ) {
                    T element;
                    if( read( element, throw_on_error ) ) {
                        v.insert( std::move( element ) );
                    } else {
                        skip_value();
                    }
                }
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
            return true;
        }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::clear(), end_array(), error_or_false(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), avatar_action::move(), read(), skip_value(), start_array(), and test_array().
read() [3/25]
bool JsonIn::read (char & c, bool throw_on_error = false)
Definition at line 1494 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    c = get_int();
    return true;
}
References c, error_or_false(), get_int(), and test_number().
read() [4/25]
bool JsonIn::read (double & d, bool throw_on_error = false)
Definition at line 1588 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    d = get_float();
    return true;
}
References error_or_false(), get_float(), and test_number().
read() [5/25]
bool JsonIn::read (float & f, bool throw_on_error = false)
Definition at line 1579 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    f = get_float();
    return true;
}
References error_or_false(), get_float(), and test_number().
read() [6/25]
bool JsonIn::read (int & i, bool throw_on_error = false)
Definition at line 1543 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    i = get_int();
    return true;
}
References error_or_false(), get_int(), and test_number().
read() [7/25]
bool JsonIn::read (int64_t & i, bool throw_on_error = false)
read() [8/25]
bool JsonIn::read (JsonDeserializer & j, bool throw_on_error = false)
Definition at line 1621 of file json.cpp.
{
    // can't know what type of json object it will deserialize from,
    // so just try to deserialize, catching any error.
    // TODO: non-verbose flag for JsonIn errors so try/catch is faster here
    try {
        j.deserialize( *this );
        return true;
    } catch( const JsonError & ) {
        if( throw_on_error ) {
            throw;
        }
        return false;
    }
}
References JsonDeserializer::deserialize().
read() [9/25]
bool JsonIn::read (short int & s, bool throw_on_error = false)
Definition at line 1533 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    // TODO: test for overflow
    s = get_int();
    return true;
}
References error_or_false(), get_int(), and test_number().
read() [10/25]
bool JsonIn::read (short unsigned int & s, bool throw_on_error = false)
Definition at line 1523 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    // TODO: test for overflow
    s = get_int();
    return true;
}
References error_or_false(), get_int(), and test_number().
read() [11/25]
bool JsonIn::read (signed char & c, bool throw_on_error = false)
Definition at line 1503 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    // TODO: test for overflow
    c = get_int();
    return true;
}
References c, error_or_false(), get_int(), and test_number().
read() [12/25]
template<typename T , size_t N> bool JsonIn::read (std::array< T, N > & v, bool throw_on_error = false) inline
Definition at line 410 of file json.h.
{
            if( !test_array() ) {
                return error_or_false( throw_on_error, "Expected json array" );
            }
            try {
                start_array();
                for( size_t i = 0; i < N; ++i ) {
                    if( end_array() ) {
                        if( throw_on_error ) {
                            error( "Json array is too short" );
                        }
                        return false; // json array is too small
                    }
                    if( !read( v[i], throw_on_error ) ) {
                        return false; // invalid entry
                    }
                }
                bool result = end_array();
                if( !result && throw_on_error ) {
                    error( "Array had too many elements" );
                }
                return result;
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
        }
References end_array(), error(), error_or_false(), read(), start_array(), and test_array().
read() [13/25]
template<size_t N> bool JsonIn::read (std::bitset< N > & b, bool throw_on_error = false)
Definition at line 1607 of file json.cpp.
{
    if( !test_bitset() ) {
        return error_or_false( throw_on_error, "Expected bitset" );
    }
    std::string tmp_string = get_string();
    if( tmp_string.length() > N ) {
        // If the loaded string contains more bits than expected, skip the most significant bits
        tmp_string.erase( 0, tmp_string.length() - N );
    }
    b = std::bitset<N> ( tmp_string );
    return true;
}
References b, error_or_false(), get_string(), and test_bitset().
read() [14/25]
template<typename T , typename U > bool JsonIn::read (std::pair< T, U > & p, bool throw_on_error = false) inline
Overload for std::pair.
Definition at line 356 of file json.h.
{
            if( !test_array() ) {
                return error_or_false( throw_on_error, "Expected json array encoding pair" );
            }
            try {
                start_array();
                bool result = !end_array() &&
                              read( p.first, throw_on_error ) &&
                              !end_array() &&
                              read( p.second, throw_on_error ) &&
                              end_array();
                if( !result && throw_on_error ) {
                    error( "Array had wrong number of elements for pair" );
                }
                return result;
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
        }
References end_array(), error(), error_or_false(), read(), start_array(), and test_array().
read() [15/25]
bool JsonIn::read (std::string & s, bool throw_on_error = false)
Definition at line 1597 of file json.cpp.
{
    if( !test_string() ) {
        return error_or_false( throw_on_error, "Expected string" );
    }
    s = get_string();
    return true;
}
References error_or_false(), get_string(), and test_string().
read() [16/25]
template<typename T , typename std::enable_if< !std::is_same< typename T::key_type, typename T::value_type >::value >::type * = nullptr> bool JsonIn::read (T & m, bool throw_on_error = true) inline
Definition at line 503 of file json.h.
{
            if( !test_object() ) {
                return error_or_false( throw_on_error, "Expected json object" );
            }
            try {
                start_object();
                m.clear();
                while( !end_object() ) {
                    using key_type = typename T::key_type;
                    key_type key = key_from_json_string<key_type>()( get_member_name() );
                    typename T::mapped_type element;
                    if( read( element, throw_on_error ) ) {
                        m[std::move( key )] = std::move( element );
                    } else {
                        skip_value();
                    }
                }
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
            return true;
        }
References end_object(), error_or_false(), get_member_name(), avatar_action::move(), read(), skip_value(), start_object(), and test_object().
read() [17/25]
template<typename T > auto JsonIn::read (T & thing, bool throw_on_error = false) -> decltype(thing.str(), true) inline
Definition at line 295 of file json.h.
{
            std::string tmp;
            if( !read( tmp, throw_on_error ) ) {
                return false;
            }
            thing = T( tmp );
            return true;
        }
References read(), and mdeath::thing().
read() [18/25]
template<typename T , typename std::enable_if< std::is_same< typename T::key_type, typename T::value_type >::value >::type * = nullptr> bool JsonIn::read (T & v, bool throw_on_error = false) inline
Definition at line 445 of file json.h.
{
            if( !test_array() ) {
                return error_or_false( throw_on_error, "Expected json array" );
            }
            try {
                start_array();
                v.clear();
                while( !end_array() ) {
                    typename T::value_type element;
                    if( read( element, throw_on_error ) ) {
                        v.insert( std::move( element ) );
                    } else {
                        skip_value();
                    }
                }
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
            return true;
        }
References end_array(), error_or_false(), avatar_action::move(), read(), skip_value(), start_array(), and test_array().
read() [19/25]
template<typename T > auto JsonIn::read (T & v, bool throw_on_error = false) -> decltype(deserialize(v, *this), true) inline
Overload that calls a global function deserialize(T&,JsonIn&), if available.
Definition at line 306 of file json.h.
{
            try {
                deserialize( v, *this );
                return true;
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
        }
References deserialize().
read() [20/25]
template<typename T > auto JsonIn::read (T & v, bool throw_on_error = false) -> decltype(v.deserialize(*this), true) inline
Overload that calls a member function T::deserialize(JsonIn&), if available.
Definition at line 321 of file json.h.
{
            try {
                v.deserialize( *this );
                return true;
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
        }
read() [21/25]
template<typename T , typename std::enable_if< !std::is_same< void, typename T::value_type >::value >::type * = nullptr> auto JsonIn::read (T & v, bool throw_on_error = false) -> decltype(v.front(), true) inline
Definition at line 383 of file json.h.
{
            if( !test_array() ) {
                return error_or_false( throw_on_error, "Expected json array" );
            }
            try {
                start_array();
                v.clear();
                while( !end_array() ) {
                    typename T::value_type element;
                    if( read( element, throw_on_error ) ) {
                        v.push_back( std::move( element ) );
                    } else {
                        skip_value();
                    }
                }
            } catch( const JsonError & ) {
                if( throw_on_error ) {
                    throw;
                }
                return false;
            }
            return true;
        }
References end_array(), error_or_false(), avatar_action::move(), read(), skip_value(), start_array(), and test_array().
read() [22/25]
template<typename T , std::enable_if_t< std::is_enum< T >::value, int > = 0> bool JsonIn::read (T & val, bool throw_on_error = false) inline
Definition at line 334 of file json.h.
{
            int i;
            if( read( i, false ) ) {
                val = static_cast<T>( i );
                return true;
            }
            std::string s;
            int s_pos = tell();
            if( read( s, throw_on_error ) ) {
                try {
                    val = io::string_to_enum<T>( s );
                } catch( const io::InvalidEnumString &err ) {
                    int curr_pos = tell();
                    return error_or_false( throw_on_error, err.what(), s_pos - curr_pos );
                }
                return true;
            }
            return false;
        }
References error_or_false(), read(), and tell().
read() [23/25]
bool JsonIn::read (uint64_t & i, bool throw_on_error = false)
read() [24/25]
bool JsonIn::read (unsigned char & c, bool throw_on_error = false)
Definition at line 1513 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    // TODO: test for overflow
    c = get_int();
    return true;
}
References c, error_or_false(), get_int(), and test_number().
read() [25/25]
bool JsonIn::read (unsigned int & u, bool throw_on_error = false)
Definition at line 1570 of file json.cpp.
{
    if( !test_number() ) {
        return error_or_false( throw_on_error, "Expected number" );
    }
    u = get_uint();
    return true;
}
References error_or_false(), get_uint(), and test_number().
rewind()
void JsonIn::rewind (int max_lines = -1, int max_chars = -1)
Definition at line 1782 of file json.cpp.
{
    if( max_lines < 0 && max_chars < 0 ) {
        // just rewind to the beginning i guess
        seek( 0 );
        return;
    }
    if( tell() == 0 ) {
        return;
    }
    int lines_found = 0;
    stream->seekg( -1, std::istream::cur );
    for( int i = 0; i < max_chars; ++i ) {
        size_t tellpos = tell();
        if( peek() == '\n' ) {
            ++lines_found;
            if( tellpos > 0 ) {
                stream->seekg( -1, std::istream::cur );
                if( peek() != '\r' ) {
                    stream->seekg( 1, std::istream::cur );
                } else {
                    --tellpos;
                }
            }
        } else if( peek() == '\r' ) {
            ++lines_found;
        }
        if( lines_found == max_lines ) {
            // don't include the last \n or \r
            if( peek() == '\n' ) {
                stream->seekg( 1, std::istream::cur );
            } else if( peek() == '\r' ) {
                stream->seekg( 1, std::istream::cur );
                if( peek() == '\n' ) {
                    stream->seekg( 1, std::istream::cur );
                }
            }
            break;
        } else if( tellpos == 0 ) {
            break;
        }
        stream->seekg( -1, std::istream::cur );
    }
}
References peek(), seek(), stream, and tell().
Referenced by error().
seek()
void JsonIn::seek (int pos)
Definition at line 741 of file json.cpp.
{
    stream->clear();
    stream->seekg( pos );
    ate_separator = false;
}
References ate_separator, and stream.
Referenced by translation::deserialize(), error(), JsonObject::finish(), JsonArray::finish(), JsonObject::get_array(), JsonArray::get_array(), JsonObject::get_bool(), JsonArray::get_bool(), get_enum_value(), JsonObject::get_enum_value(), JsonObject::get_float(), JsonArray::get_float(), JsonObject::get_int(), JsonArray::get_int(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), JsonObject::get_object(), JsonArray::get_object(), JsonObject::get_raw(), JsonObject::get_source_location(), JsonObject::get_string(), JsonArray::get_string(), JsonObject::get_tags(), JsonArray::get_tags(), JsonObject::has_array(), JsonArray::has_array(), JsonObject::has_bool(), JsonArray::has_bool(), JsonObject::has_null(), JsonArray::has_null(), JsonObject::has_number(), JsonArray::has_number(), JsonObject::has_object(), JsonArray::has_object(), JsonObject::has_string(), JsonArray::has_string(), JsonIn(), JsonObject::line_number(), line_number(), JsonArray::next_array(), JsonArray::next_bool(), JsonArray::next_float(), JsonArray::next_int(), JsonArray::next_object(), JsonArray::next_string(), JsonObject::read(), JsonArray::read(), read_from_json_string(), JsonArray::read_next(), rewind(), JsonValue::seek(), JsonArray::test_array(), JsonArray::test_bitset(), JsonArray::test_bool(), JsonArray::test_null(), JsonArray::test_number(), JsonArray::test_object(), JsonArray::test_string(), JsonObject::throw_error(), JsonArray::throw_error(), JsonArray::verify_index(), and JsonObject::verify_position().
set_ate_separator()
void JsonIn::set_ate_separator (bool s) inline
Definition at line 205 of file json.h.
{
            ate_separator = s;
        }
References ate_separator.
Referenced by JsonObject::finish(), and JsonArray::finish().
skip_array()
void JsonIn::skip_array ()
Definition at line 891 of file json.cpp.
{
    start_array();
    while( !end_array() ) {
        skip_value();
    }
    // end_value called by end_array
}
References end_array(), skip_value(), and start_array().
Referenced by skip_value().
skip_false()
void JsonIn::skip_false ()
Definition at line 913 of file json.cpp.
{
    char text[6];
    eat_whitespace();
    stream->get( text, 6 );
    if( strcmp( text, "false" ) != 0 ) {
        std::stringstream err;
        err << R"(expected "false", but found ")" << text << "\"";
        error( err.str(), -5 );
    }
    end_value();
}
References eat_whitespace(), end_value(), error(), and stream.
Referenced by skip_value().
skip_member()
void JsonIn::skip_member ()
Definition at line 771 of file json.cpp.
{
    skip_string();
    skip_pair_separator();
    skip_value();
}
References skip_pair_separator(), skip_string(), and skip_value().
Referenced by skip_object().
skip_null()
void JsonIn::skip_null ()
Definition at line 926 of file json.cpp.
{
    char text[5];
    eat_whitespace();
    stream->get( text, 5 );
    if( strcmp( text, "null" ) != 0 ) {
        std::stringstream err;
        err << R"(expected "null", but found ")" << text << "\"";
        error( err.str(), -4 );
    }
    end_value();
}
References eat_whitespace(), end_value(), error(), and stream.
Referenced by mm_region::deserialize(), and skip_value().
skip_number()
void JsonIn::skip_number ()
Definition at line 939 of file json.cpp.
{
    char ch;
    eat_whitespace();
    // skip all of (+-0123456789.eE)
    while( stream->good() ) {
        stream->get( ch );
        if( ch != '+' && ch != '-' && ( ch < '0' || ch > '9' ) &&
            ch != 'e' && ch != 'E' && ch != '.' ) {
            stream->unget();
            break;
        }
    }
    end_value();
}
References eat_whitespace(), end_value(), and stream.
Referenced by skip_value().
skip_object()
void JsonIn::skip_object ()
Definition at line 882 of file json.cpp.
{
    start_object();
    while( !end_object() ) {
        skip_member();
    }
    // end_value called by end_object
}
References end_object(), skip_member(), and start_object().
Referenced by skip_value().
skip_pair_separator()
void JsonIn::skip_pair_separator () private
Definition at line 811 of file json.cpp.
{
    char ch;
    eat_whitespace();
    stream->get( ch );
    if( ch != ':' ) {
        std::stringstream err;
        err << "expected pair separator ':', not '" << ch << "'";
        error( err.str(), -1 );
    } else if( ate_separator ) {
        error( "duplicate pair separator ':' not allowed", -1 );
    }
    ate_separator = true;
}
References ate_separator, eat_whitespace(), error(), and stream.
Referenced by get_member_name(), and skip_member().
skip_separator()
void JsonIn::skip_separator () private
Definition at line 778 of file json.cpp.
{
    eat_whitespace();
    signed char ch = peek();
    if( ch == ',' ) {
        if( ate_separator ) {
            error( "duplicate comma" );
        }
        stream->get();
        ate_separator = true;
    } else if( ch == ']' || ch == '}' || ch == ':' ) {
        // okay
        if( ate_separator ) {
            std::stringstream err;
            err << "comma should not be found before '" << ch << "'";
            uneat_whitespace();
            error( err.str() );
        }
        ate_separator = false;
    } else if( ch == EOF ) {
        // that's okay too... probably
        if( ate_separator ) {
            uneat_whitespace();
            error( "comma at end of file not allowed" );
        }
        ate_separator = false;
    } else {
        // not okay >:(
        uneat_whitespace();
        error( "missing comma", 1 );
    }
}
References ate_separator, eat_whitespace(), error(), peek(), stream, and uneat_whitespace().
Referenced by end_value().
skip_string()
void JsonIn::skip_string ()
Definition at line 826 of file json.cpp.
{
    char ch;
    eat_whitespace();
    stream->get( ch );
    if( ch != '"' ) {
        std::stringstream err;
        err << "expecting string but found '" << ch << "'";
        error( err.str(), -1 );
    }
    while( stream->good() ) {
        stream->get( ch );
        if( ch == '\\' ) {
            stream->get( ch );
            continue;
        } else if( ch == '"' ) {
            break;
        } else if( ch == '\r' || ch == '\n' ) {
            error( "string not closed before end of line", -1 );
        }
    }
    end_value();
}
References eat_whitespace(), end_value(), error(), and stream.
Referenced by skip_member(), and skip_value().
skip_true()
void JsonIn::skip_true ()
Definition at line 900 of file json.cpp.
{
    char text[5];
    eat_whitespace();
    stream->get( text, 5 );
    if( strcmp( text, "true" ) != 0 ) {
        std::stringstream err;
        err << R"(expected "true", but found ")" << text << "\"";
        error( err.str(), -4 );
    }
    end_value();
}
References eat_whitespace(), end_value(), error(), and stream.
Referenced by skip_value().
skip_value()
void JsonIn::skip_value ()
Definition at line 850 of file json.cpp.
{
    eat_whitespace();
    char ch = peek();
    // it's either a string '"'
    if( ch == '"' ) {
        skip_string();
        // or an object '{'
    } else if( ch == '{' ) {
        skip_object();
        // or an array '['
    } else if( ch == '[' ) {
        skip_array();
        // or a number (-0123456789)
    } else if( ch == '-' || ( ch >= '0' && ch <= '9' ) ) {
        skip_number();
        // or "true", "false" or "null"
    } else if( ch == 't' ) {
        skip_true();
    } else if( ch == 'f' ) {
        skip_false();
    } else if( ch == 'n' ) {
        skip_null();
        // or an error.
    } else {
        std::stringstream err;
        err << "expected JSON value but got '" << ch << "'";
        error( err.str() );
    }
    // skip_* end value automatically
}
References eat_whitespace(), error(), peek(), skip_array(), skip_false(), skip_null(), skip_number(), skip_object(), skip_string(), and skip_true().
Referenced by JsonArray::JsonArray(), JsonObject::JsonObject(), submap::load(), read(), skip_array(), skip_member(), and game::unserialize_master().
start_array()
void JsonIn::start_array ()
Definition at line 1373 of file json.cpp.
{
    eat_whitespace();
    if( peek() == '[' ) {
        stream->get();
        ate_separator = false;
        return;
    } else {
        // expecting an array, so this is an error
        std::stringstream err;
        err << "tried to start array, but found '";
        err << peek() << "', not '['";
        error( err.str() );
    }
}
References ate_separator, eat_whitespace(), error(), peek(), and stream.
Referenced by cata_variant::deserialize(), auto_pickup::rule_list::deserialize(), color_manager::deserialize(), Creature_tracker::deserialize(), faction_manager::deserialize(), help::deserialize(), iuse_location::deserialize(), mm_submap::deserialize(), mm_region::deserialize(), mapbuffer::deserialize(), options_manager::deserialize(), panel_manager::deserialize(), pickup::act_item::deserialize(), point::deserialize(), tripoint::deserialize(), safemode::deserialize(), shape_factory::deserialize(), deserialize(), mongroup::deserialize_legacy(), generic_typed_reader< Derived >::erase_values_from(), generic_typed_reader< Derived >::insert_values_from(), inventory::json_load_items(), JsonArray::JsonArray(), input_manager::load(), Name::load(), submap::load(), DynamicDataLoader::load_all_from_json(), load_artifacts(), color_loader< ColorType >::load_colorfile(), map_memory::load_legacy(), overmap::load_legacy_monstergroups(), overmap::load_monster_groups(), load_optional_enum_array(), WORLD::load_options(), mod_manager::load_replacement_mods(), read(), skip_array(), overmap::unserialize(), mission::unserialize_all(), unserialize_array_from_compacted_sequence(), and overmap::unserialize_view().
start_object()
void JsonIn::start_object ()
Definition at line 1406 of file json.cpp.
{
    eat_whitespace();
    if( peek() == '{' ) {
        stream->get();
        ate_separator = false; // not that we want to
        return;
    } else {
        // expecting an object, so fail loudly
        std::stringstream err;
        err << "tried to start object, but found '";
        err << peek() << "', not '{'";
        error( err.str() );
    }
}
References ate_separator, eat_whitespace(), error(), peek(), and stream.
Referenced by faction_manager::deserialize(), mapbuffer::deserialize(), mongroup::deserialize_legacy(), JsonObject::JsonObject(), read(), skip_object(), overmap::unserialize(), game::unserialize_master(), and overmap::unserialize_view().
string_error()
void JsonIn::string_error (const std::string & message, int offset)
Definition at line 1758 of file json.cpp.
{
    if( test_string() ) {
        // skip quote mark
        stream->ignore();
        std::string s;
        std::string err;
        for( int i = 0; i < offset; ++i ) {
            if( !get_escaped_or_unicode( *stream, s, err ) ) {
                break;
            }
        }
    }
    error( message, -1 );
}
References error(), get_escaped_or_unicode(), mapgen_defer::message, stream, and test_string().
Referenced by translation::deserialize().
substr()
std::string JsonIn::substr (size_t pos, size_t len = std::string::npos)
Definition at line 1827 of file json.cpp.
{
    std::string ret;
    if( len == std::string::npos ) {
        stream->seekg( 0, std::istream::end );
        size_t end = tell();
        len = end - pos;
    }
    ret.resize( len );
    stream->seekg( pos );
    stream->read( &ret[0], len );
    return ret;
}
References cata::hash64_detail::ret, stream, and tell().
Referenced by JsonArray::str(), and JsonObject::str().
tell()
int JsonIn::tell ()
Definition at line 728 of file json.cpp.
{
    return stream->tellg();
}
References stream.
Referenced by translation::deserialize(), error(), get_enum_value(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), JsonArray::JsonArray(), JsonObject::JsonObject(), line_number(), read(), read_from_json_string(), rewind(), substr(), and uneat_whitespace().
test_array()
bool JsonIn::test_array ()
Definition at line 1471 of file json.cpp.
{
    eat_whitespace();
    return peek() == '[';
}
References eat_whitespace(), and peek().
Referenced by damage_instance::deserialize(), faction_manager::deserialize(), generic_typed_reader< Derived >::erase_values_from(), JsonObject::has_array(), JsonArray::has_array(), generic_typed_reader< Derived >::insert_values_from(), submap::load(), DynamicDataLoader::load_all_from_json(), mod_management::load_mod_info(), avatar::load_template(), read(), JsonArray::test_array(), and JsonValue::test_array().
test_bitset()
bool JsonIn::test_bitset ()
Definition at line 1465 of file json.cpp.
{
    eat_whitespace();
    return peek() == '"';
}
References eat_whitespace(), and peek().
Referenced by read(), and JsonArray::test_bitset().
test_bool()
bool JsonIn::test_bool ()
Definition at line 1445 of file json.cpp.
{
    eat_whitespace();
    const char ch = peek();
    return ch == 't' || ch == 'f';
}
References eat_whitespace(), and peek().
Referenced by JsonObject::has_bool(), JsonArray::has_bool(), read(), JsonArray::test_bool(), and JsonValue::test_bool().
test_float()
bool JsonIn::test_float () inline
Definition at line 266 of file json.h.
{
            return test_number();
        }
References test_number().
Referenced by JsonValue::test_float().
test_int()
bool JsonIn::test_int () inline
Definition at line 263 of file json.h.
{
            return test_number();
        }
References test_number().
Referenced by nc_color::deserialize(), mm_submap::deserialize(), submap::load(), and JsonValue::test_int().
test_null()
bool JsonIn::test_null ()
Definition at line 1439 of file json.cpp.
{
    eat_whitespace();
    return peek() == 'n';
}
References eat_whitespace(), and peek().
Referenced by deserialize(), hacking_activity_actor::deserialize(), mm_region::deserialize(), JsonObject::has_null(), JsonArray::has_null(), and JsonArray::test_null().
test_number()
bool JsonIn::test_number ()
Definition at line 1452 of file json.cpp.
{
    eat_whitespace();
    const char ch = peek();
    return ch == '-' || ch == '+' || ch == '.' || ( ch >= '0' && ch <= '9' );
}
References eat_whitespace(), and peek().
Referenced by JsonObject::has_number(), JsonArray::has_number(), read(), test_float(), test_int(), and JsonArray::test_number().
test_object()
bool JsonIn::test_object ()
Definition at line 1477 of file json.cpp.
{
    eat_whitespace();
    return peek() == '{';
}
References eat_whitespace(), and peek().
Referenced by damage_instance::deserialize(), faction_manager::deserialize(), job_data::deserialize(), JsonObject::has_object(), JsonArray::has_object(), DynamicDataLoader::load_all_from_json(), mod_management::load_mod_info(), read(), JsonArray::test_object(), and JsonValue::test_object().
test_string()
bool JsonIn::test_string ()
Definition at line 1459 of file json.cpp.
{
    eat_whitespace();
    return peek() == '"';
}
References eat_whitespace(), and peek().
Referenced by computer::deserialize(), time_duration::deserialize(), nc_color::deserialize(), translation::deserialize(), ma_buff_reader::get_next(), item_reader::get_next(), JsonObject::get_tags(), JsonArray::get_tags(), JsonObject::has_string(), JsonArray::has_string(), submap::load(), read(), string_error(), JsonArray::test_string(), and JsonValue::test_string().
uneat_whitespace()
void JsonIn::uneat_whitespace ()
Definition at line 755 of file json.cpp.
{
    while( tell() > 0 ) {
        stream->seekg( -1, std::istream::cur );
        if( !is_whitespace( peek() ) ) {
            break;
        }
    }
}
References is_whitespace(), peek(), stream, and tell().
Referenced by end_array(), end_object(), and skip_separator().
Member Data Documentation
ate_separator
bool JsonIn::ate_separator = false private
Definition at line 181 of file json.h.
Referenced by end_array(), end_object(), end_value(), get_ate_separator(), seek(), set_ate_separator(), skip_pair_separator(), skip_separator(), start_array(), and start_object().
path
shared_ptr_fast<std::string> JsonIn::path private
Definition at line 180 of file json.h.
Referenced by get_path(), and line_number().
stream
std::istream* JsonIn::stream private
Definition at line 179 of file json.h.
Referenced by eat_whitespace(), end_array(), end_object(), error(), get_any_number(), get_bool(), get_string(), good(), line_number(), peek(), rewind(), seek(), skip_false(), skip_null(), skip_number(), skip_pair_separator(), skip_separator(), skip_string(), skip_true(), start_array(), start_object(), string_error(), substr(), tell(), and uneat_whitespace().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp