Cataclysm BN: anatomy Class Reference
anatomy Class Reference
A structure that contains body parts.
#include <anatomy.h>
Public Member Functions
anatomy ()=default
anatomy (const anatomy &)=default
anatomy & operator= (const anatomy &)=default
bodypart_id random_body_part () const
Returns a random body_part token.
bodypart_id select_body_part (int size_diff, int hit_roll) const
Returns a random body part dependent on attacker's relative size and hit roll.
std::vector< bodypart_id > get_bodyparts () const
void add_body_part (const bodypart_str_id &new_bp)
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check () const
Static Public Member Functions
static void load_anatomy (const JsonObject &jo, const std::string &src)
static void reset ()
static void finalize_all ()
static void check_consistency ()
Public Attributes
anatomy_id id
bool was_loaded = false
Private Member Functions
bodypart_str_id get_part_with_cumulative_hit_size (float size) const
Private Attributes
std::vector< bodypart_str_id > unloaded_bps
std::vector< bodypart_id > cached_bps
float size_sum = 0.0f
Sum of chances to hit a body part randomly, without aiming.
Detailed Description
A structure that contains body parts.
Keeps caches for weighted selections.
Definition at line 20 of file anatomy.h.
Constructor & Destructor Documentation
anatomy() [1/2]
anatomy::anatomy () default
anatomy() [2/2]
anatomy::anatomy (const anatomy &) default
Member Function Documentation
add_body_part()
void anatomy::add_body_part (const bodypart_str_id & new_bp)
Definition at line 114 of file anatomy.cpp.
{
    cached_bps.emplace_back( new_bp.id() );
    const body_part_type &bp_struct = new_bp.obj();
    size_sum += bp_struct.hit_size;
}
References cached_bps, body_part_type::hit_size, string_id< T >::id(), string_id< T >::obj(), and size_sum.
Referenced by finalize().
check()
void anatomy::check () const
Definition at line 91 of file anatomy.cpp.
{
    if( !get_part_with_cumulative_hit_size( size_sum ).is_valid() ) {
        debugmsg( "Invalid size_sum calculation for anatomy %s", id.c_str() );
    }
    for( size_t i = 0; i < 3; i++ ) {
        const float size_all = std::accumulate( cached_bps.begin(), cached_bps.end(), 0.0f, [i]( float acc,
        const bodypart_id & bp ) {
            return acc + bp->hit_size_relative[i];
        } );
        if( size_all <= 0.0f ) {
            debugmsg( "Anatomy %s has no part hittable when size difference is %d", id.c_str(),
                      static_cast<int>( i ) - 1 );
        }
    }
}
References cached_bps, debugmsg, get_part_with_cumulative_hit_size(), and size_sum.
check_consistency()
void anatomy::check_consistency () static
Definition at line 83 of file anatomy.cpp.
{
    anatomy_factory.check();
    if( !human_anatomy.is_valid() ) {
        debugmsg( "Could not load human anatomy, expect crash" );
    }
}
References anonymous_namespace{anatomy.cpp}::anatomy_factory, debugmsg, human_anatomy, and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
finalize()
void anatomy::finalize ()
Definition at line 67 of file anatomy.cpp.
{
    size_sum = 0.0f;
    cached_bps.clear();
    for( const bodypart_str_id &id : unloaded_bps ) {
        if( id.is_valid() ) {
            add_body_part( id );
        } else {
            debugmsg( "Anatomy %s has invalid body part %s", id.c_str(), id.c_str() );
        }
    }
    unloaded_bps.clear();
}
References add_body_part(), cached_bps, debugmsg, size_sum, and unloaded_bps.
Referenced by finalize_all().
finalize_all()
void anatomy::finalize_all () static
Definition at line 58 of file anatomy.cpp.
{
    // For some weird reason, generic_factory::finalize doesn't call finalize
    anatomy_factory.finalize();
    for( const anatomy &an : anatomy_factory.get_all() ) {
        const_cast<anatomy &>( an ).finalize();
    }
}
References anonymous_namespace{anatomy.cpp}::anatomy_factory, and finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_bodyparts()
std::vector< bodypart_id > anatomy::get_bodyparts () const
Definition at line 109 of file anatomy.cpp.
{
    return cached_bps;
}
References cached_bps.
get_part_with_cumulative_hit_size()
bodypart_str_id anatomy::get_part_with_cumulative_hit_size (float size) const private
Definition at line 122 of file anatomy.cpp.
{
    for( const bodypart_id &part : cached_bps ) {
        size -= part->hit_size;
        if( size <= 0.0f ) {
            return part.id();
        }
    }
    return bodypart_str_id::NULL_ID();
}
References cached_bps, string_id< body_part_type >::NULL_ID(), and om_direction::size.
Referenced by check(), and random_body_part().
load()
void anatomy::load (const JsonObject & jo, const std::string & src)
Definition at line 47 of file anatomy.cpp.
{
    mandatory( jo, was_loaded, "id", id );
    mandatory( jo, was_loaded, "parts", unloaded_bps );
}
References mandatory(), unloaded_bps, and was_loaded.
load_anatomy()
void anatomy::load_anatomy (const JsonObject & jo, const std::string & src) static
Definition at line 42 of file anatomy.cpp.
{
    anatomy_factory.load( jo, src );
}
References anonymous_namespace{anatomy.cpp}::anatomy_factory.
Referenced by DynamicDataLoader::initialize().
operator=()
anatomy & anatomy::operator= (const anatomy &) default
random_body_part()
bodypart_id anatomy::random_body_part () const
Returns a random body_part token.
main_parts_only will limit it to arms, legs, torso, and head.
Definition at line 134 of file anatomy.cpp.
{
    return get_part_with_cumulative_hit_size( rng_float( 0.0f, size_sum ) ).id();
}
References get_part_with_cumulative_hit_size(), string_id< T >::id(), rng_float(), and size_sum.
Referenced by Creature::deal_melee_hit(), Creature::get_random_body_part(), and random_body_part().
reset()
void anatomy::reset () static
Definition at line 53 of file anatomy.cpp.
{
    anatomy_factory.reset();
}
References anonymous_namespace{anatomy.cpp}::anatomy_factory.
Referenced by DynamicDataLoader::unload_data().
select_body_part()
bodypart_id anatomy::select_body_part (int size_diff, int hit_roll) const
Returns a random body part dependent on attacker's relative size and hit roll.
Definition at line 139 of file anatomy.cpp.
{
    const size_t size_diff_index = static_cast<size_t>( 1 + clamp( size_diff, -1, 1 ) );
    weighted_float_list<bodypart_id> hit_weights;
    for( const bodypart_id &bp : cached_bps ) {
        float weight = bp->hit_size_relative[size_diff_index];
        if( weight <= 0.0f ) {
            continue;
        }
        if( hit_roll != 0 ) {
            weight *= std::pow( hit_roll, bp->hit_difficulty );
        }
        hit_weights.add( bp, weight );
    }
    // Debug for seeing weights.
    for( const weighted_object<double, bodypart_id> &pr : hit_weights ) {
        add_msg( m_debug, "%s = %.3f", pr.obj.obj().name, pr.weight );
    }
    const bodypart_id *ret = hit_weights.pick();
    if( ret == nullptr ) {
        debugmsg( "Attempted to select body part from empty anatomy %s", id.c_str() );
        return bodypart_str_id::NULL_ID().id();
    }
    add_msg( m_debug, "selected part: %s", ret->id().obj().name );
    return *ret;
}
References weighted_list< W, T >::add(), add_msg(), cached_bps, clamp(), debugmsg, string_id< T >::id(), m_debug, string_id< body_part_type >::NULL_ID(), weighted_list< W, T >::pick(), and cata::hash64_detail::ret.
Referenced by Creature::select_body_part().
Member Data Documentation
cached_bps
std::vector<bodypart_id> anatomy::cached_bps private
Definition at line 24 of file anatomy.h.
Referenced by add_body_part(), check(), finalize(), get_bodyparts(), get_part_with_cumulative_hit_size(), and select_body_part().
id
anatomy_id anatomy::id
Definition at line 32 of file anatomy.h.
size_sum
float anatomy::size_sum = 0.0f private
Sum of chances to hit a body part randomly, without aiming.
Definition at line 26 of file anatomy.h.
Referenced by add_body_part(), check(), finalize(), and random_body_part().
unloaded_bps
std::vector<bodypart_str_id> anatomy::unloaded_bps private
Definition at line 23 of file anatomy.h.
Referenced by finalize(), and load().
was_loaded
bool anatomy::was_loaded = false
Definition at line 33 of file anatomy.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/anatomy.h
src/anatomy.cpp