Cataclysm BN: loot_options Class Reference
loot_options Class Reference
#include <clzones.h>
Public Member Functions
std::string get_mark () const override
bool has_options () const override
bool query_at_creation () override
bool query () override
std::string get_zone_name_suggestion () const override
std::vector< std::pair< std::string, std::string > > get_descriptions () const override
void serialize (JsonOut &json) const override
void deserialize (const JsonObject &jo_zone) override
Public Member Functions inherited from zone_options
virtual ~zone_options ()=default
Public Member Functions inherited from mark_option
virtual ~mark_option ()=default
Private Types
enum query_loot_result { canceled , successful , changed }
Private Member Functions
query_loot_result query_loot ()
Private Attributes
std::string mark
Additional Inherited Members
Static Public Member Functions inherited from zone_options
static shared_ptr_fast< zone_options > create (const zone_type_id &type)
static bool is_valid (const zone_type_id &type, const zone_options &options)
Detailed Description
Definition at line 196 of file clzones.h.
Member Enumeration Documentation
query_loot_result
enum loot_options::query_loot_result private
Enumerator
canceled
successful
changed
Definition at line 202 of file clzones.h.
{
            canceled,
            successful,
            changed,
        };
Member Function Documentation
deserialize()
void loot_options::deserialize (const JsonObject & jo_zone) override virtual
Reimplemented from zone_options.
Definition at line 372 of file clzones.cpp.
{
    jo_zone.read( "mark", mark );
}
References mark, and JsonObject::read().
get_descriptions()
std::vector< std::pair< std::string, std::string > > loot_options::get_descriptions () const override virtual
Reimplemented from zone_options.
Definition at line 358 of file clzones.cpp.
{
    std::vector<std::pair<std::string, std::string>> options;
    options.emplace_back( std::make_pair( _( "Loot: Custom: " ),
                                          !mark.empty() ? mark : _( "No filter" ) ) );
    return options;
}
References _, mark, and PATH_INFO::options().
get_mark()
std::string loot_options::get_mark () const inline override virtual
Implements mark_option.
Definition at line 211 of file clzones.h.
{
            return mark;
        }
References mark.
get_zone_name_suggestion()
std::string loot_options::get_zone_name_suggestion () const override virtual
Reimplemented from zone_options.
Definition at line 350 of file clzones.cpp.
{
    if( !mark.empty() ) {
        return string_format( _( "Loot: Custom: %s" ), mark );
    }
    return _( "Loot: Custom: No Filter" );
}
References _, mark, and string_format().
has_options()
bool loot_options::has_options () const inline override virtual
Reimplemented from zone_options.
Definition at line 215 of file clzones.h.
{
            return true;
        }
query()
bool loot_options::query () override virtual
Reimplemented from zone_options.
Definition at line 345 of file clzones.cpp.
{
    return query_loot() == changed;
}
References changed, and query_loot().
query_at_creation()
bool loot_options::query_at_creation () override virtual
Reimplemented from zone_options.
Definition at line 340 of file clzones.cpp.
{
    return query_loot() != canceled;
}
References canceled, and query_loot().
query_loot()
loot_options::query_loot_result loot_options::query_loot () private
Definition at line 264 of file clzones.cpp.
{
    int w_height = TERMY / 2;
    const int w_width = TERMX / 2;
    const int w_y0 = ( TERMY > w_height ) ? ( TERMY - w_height ) / 4 : 0;
    const int w_x0 = ( TERMX > w_width ) ? ( TERMX - w_width ) / 2 : 0;
    catacurses::window w_con = catacurses::newwin( w_height, w_width, point( w_x0, w_y0 ) );
    draw_item_filter_rules( w_con, 1, w_height - 1, item_filter_type::FILTER );
    string_input_popup()
    .title( _( "Filter:" ) )
    .width( 55 )
    .identifier( "item_filter" )
    .max_length( 256 )
    .edit( mark );
    return changed;
}
References _, changed, draw_item_filter_rules(), string_input_popup::edit(), FILTER, string_input_popup::identifier(), mark, string_input_popup::max_length(), catacurses::newwin(), TERMX, TERMY, string_input_popup::title(), and string_input_popup::width().
Referenced by query(), and query_at_creation().
serialize()
void loot_options::serialize (JsonOut & json) const override virtual
Reimplemented from zone_options.
Definition at line 367 of file clzones.cpp.
{
    json.member( "mark", mark );
}
References mark, and JsonOut::member().
Member Data Documentation
mark
std::string loot_options::mark private
Definition at line 200 of file clzones.h.
Referenced by deserialize(), get_descriptions(), get_mark(), get_zone_name_suggestion(), query_loot(), and serialize().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp