Cataclysm BN: iteminfo_query Class Reference
iteminfo_query Class Reference
#include <iteminfo_query.h>
Public Member Functions
iteminfo_query (const iteminfo_query_base &values)
iteminfo_query (const std::string &bits)
iteminfo_query (const std::vector< iteminfo_parts > &set_bits)
bool test (const iteminfo_parts &value) const
Static Public Attributes
static const iteminfo_query all
static const iteminfo_query no_text
static const iteminfo_query any_flags
static const iteminfo_query no_conditions
Private Attributes
iteminfo_query_base parts
Detailed Description
Definition at line 226 of file iteminfo_query.h.
Constructor & Destructor Documentation
iteminfo_query() [1/3]
iteminfo_query::iteminfo_query (const iteminfo_query_base & values)
Definition at line 17 of file iteminfo_query.cpp.
    : parts( values )
{
}
iteminfo_query() [2/3]
iteminfo_query::iteminfo_query (const std::string & bits)
Definition at line 6 of file iteminfo_query.cpp.
                                                      : parts( bits )
{
}
iteminfo_query() [3/3]
iteminfo_query::iteminfo_query (const std::vector< iteminfo_parts > & set_bits)
Definition at line 10 of file iteminfo_query.cpp.
{
    for( auto &bit : set_bits ) {
        parts.set( static_cast<size_t>( bit ) );
    }
}
References parts.
Member Function Documentation
test()
bool iteminfo_query::test (const iteminfo_parts & value) const
Definition at line 22 of file iteminfo_query.cpp.
{
    return parts.test( static_cast<size_t>( value ) );
}
References parts.
Referenced by item::ammo_info(), item::animal_armor_info(), item::armor_fit_info(), item::armor_info(), item::armor_protection_info(), item::basic_info(), item::bionic_info(), item::book_info(), item::combat_info(), item::component_info(), item::container_info(), item::contents_info(), item::disassembly_info(), item::final_info(), item::food_info(), item::gun_info(), item::gunmod_info(), item::info(), item::magazine_info(), item::med_info(), item::qualities_info(), item::repair_info(), and item::tool_info().
Member Data Documentation
all
const iteminfo_query iteminfo_query::all static
Initial value:
= iteminfo_query(
            std::string( static_cast<size_t>( iteminfo_parts::NUM_VALUES ), '1' ) )
Definition at line 237 of file iteminfo_query.h.
Referenced by item::info(), and item::info_string().
any_flags
const iteminfo_query iteminfo_query::any_flags static
Initial value:
= iteminfo_query(
std::vector<iteminfo_parts> {
    iteminfo_parts::DESCRIPTION_FLAGS,
    iteminfo_parts::DESCRIPTION_FLAGS_HELMETCOMPAT,
    iteminfo_parts::DESCRIPTION_FLAGS_FITS,
    iteminfo_parts::DESCRIPTION_FLAGS_VARSIZE,
    iteminfo_parts::DESCRIPTION_FLAGS_SIDED,
    iteminfo_parts::DESCRIPTION_FLAGS_POWERARMOR,
    iteminfo_parts::DESCRIPTION_FLAGS_POWERARMOR_RADIATIONHINT,
    iteminfo_parts::DESCRIPTION_IRRADIATION
})
Definition at line 239 of file iteminfo_query.h.
no_conditions
const iteminfo_query iteminfo_query::no_conditions static
Initial value:
= iteminfo_query(iteminfo_query::all.parts &
        ~( iteminfo_query(
std::vector<iteminfo_parts> {
    iteminfo_parts::FOOD_ROT_STORAGE
})).parts)
Definition at line 240 of file iteminfo_query.h.
Referenced by item::info().
no_text
const iteminfo_query iteminfo_query::no_text static
Definition at line 238 of file iteminfo_query.h.
Referenced by draw_caravan_items().
parts
iteminfo_query_base iteminfo_query::parts private
Definition at line 229 of file iteminfo_query.h.
Referenced by iteminfo_query(), and test().
The documentation for this class was generated from the following files:
src/iteminfo_query.h
src/iteminfo_query.cpp