Cataclysm BN: map_memory Class Reference
map_memory Class Reference
Manages map tiles memorized by the avatar.
#include <map_memory.h>
Classes
struct coord_pair
Helper class for converting global ms coord into global sm coord + ms coord within the submap.
Public Member Functions
map_memory ()
void load (const tripoint &pos)
Load memorized submaps around given global map square pos.
void load_legacy (JsonIn &jsin)
Load legacy memory file.
bool save (const tripoint &pos)
Save memorized submaps to disk, drop ones far from given global map square pos.
bool prepare_region (const tripoint &p1, const tripoint &p2)
Prepares map memory for optimized rendering and/or memorization of given region.
void memorize_tile (const tripoint &pos, const std::string &ter, int subtile, int rotation)
Memorizes given tile, overwriting old value.
const memorized_terrain_tile & get_tile (const tripoint &pos)
Returns memorized tile.
bool has_memory_for_autodrive (const tripoint &pos)
For autodrive use only.
void memorize_symbol (const tripoint &pos, int symbol)
Memorizes given symbol, overwriting old value.
int get_symbol (const tripoint &pos)
Returns memorized symbol.
void clear_memorized_tile (const tripoint &pos)
Clears memorized tile and symbol.
Private Member Functions
shared_ptr_fast< mm_submap > fetch_submap (const tripoint &sm_pos)
Find, load or allocate a submap.
shared_ptr_fast< mm_submap > find_submap (const tripoint &sm_pos)
Find submap amongst the loaded submaps.
shared_ptr_fast< mm_submap > load_submap (const tripoint &sm_pos)
Load submap from disk.
shared_ptr_fast< mm_submap > allocate_submap (const tripoint &sm_pos)
Allocate empty submap.
mm_submap & get_submap (const tripoint &sm_pos)
Find, load or allocate a submap.
void clear_cache ()
Private Attributes
std::map< tripoint, shared_ptr_fast< mm_submap > > submaps
std::vector< shared_ptr_fast< mm_submap > > cached
tripoint cache_pos
point cache_size
Detailed Description
Manages map tiles memorized by the avatar.
Note that there are 2 separate memories in here:
memorized graphic tiles (for TILES with a tileset)
memorized symbols (for CURSES or TILES in ascii mode) TODO: combine tiles and curses. Also, split map memory into layers (terrain/furn/vpart/...)?
Definition at line 109 of file map_memory.h.
Constructor & Destructor Documentation
map_memory()
map_memory::map_memory ()
Definition at line 68 of file map_memory.cpp.
{
    clear_cache();
}
References clear_cache().
Member Function Documentation
allocate_submap()
shared_ptr_fast< mm_submap > map_memory::allocate_submap (const tripoint & sm_pos) private
Allocate empty submap.
Returns
the submap.
Definition at line 180 of file map_memory.cpp.
{
    // Since all save/load operations are done on regions of submaps,
    // we need to allocate the whole region at once.
    shared_ptr_fast<mm_submap> ret;
    tripoint reg = reg_coord_pair( sm_pos ).reg;
    dbg( DL::Info ) << "Allocated mm_region " << reg << " [" << mmr_to_sm_copy( reg ) << "]";
    for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
        for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
            tripoint pos = mmr_to_sm_copy( reg ) + tripoint( x, y, 0 );
            shared_ptr_fast<mm_submap> sm = make_shared_fast<mm_submap>();
            if( pos == sm_pos ) {
                ret = sm;
            }
            submaps.insert( std::make_pair( pos, sm ) );
        }
    }
    return ret;
}
References dbg, Info, MM_REG_SIZE, mmr_to_sm_copy(), reg_coord_pair::reg, cata::hash64_detail::ret, coords::sm, and submaps.
Referenced by fetch_submap().
clear_cache()
void map_memory::clear_cache () private
Definition at line 406 of file map_memory.cpp.
{
    cached.clear();
    cache_pos = tripoint_min;
    cache_size = point_zero;
}
References cache_pos, cache_size, cached, point_zero, and tripoint_min.
Referenced by load(), map_memory(), and save().
clear_memorized_tile()
void map_memory::clear_memorized_tile (const tripoint & pos)
Clears memorized tile and symbol.
Parameters
pos tile position, in global ms coords.
Definition at line 117 of file map_memory.cpp.
{
    coord_pair p( pos );
    mm_submap &sm = get_submap( p.sm );
    sm.set_symbol( p.loc, mm_submap::default_symbol );
    sm.set_tile( p.loc, mm_submap::default_tile );
}
References mm_submap::default_symbol, mm_submap::default_tile, get_submap(), map_memory::coord_pair::loc, coords::sm, and map_memory::coord_pair::sm.
fetch_submap()
shared_ptr_fast< mm_submap > map_memory::fetch_submap (const tripoint & sm_pos) private
Find, load or allocate a submap.
May be slow.
Returns
the submap.
Definition at line 167 of file map_memory.cpp.
{
    shared_ptr_fast<mm_submap> sm = find_submap( sm_pos );
    if( sm ) {
        return sm;
    }
    sm = load_submap( sm_pos );
    if( sm ) {
        return sm;
    }
    return allocate_submap( sm_pos );
}
References allocate_submap(), find_submap(), load_submap(), and coords::sm.
Referenced by get_submap(), has_memory_for_autodrive(), load(), and prepare_region().
find_submap()
shared_ptr_fast< mm_submap > map_memory::find_submap (const tripoint & sm_pos) private
Find submap amongst the loaded submaps.
Returns
nullptr if failed.
Definition at line 203 of file map_memory.cpp.
{
    auto sm = submaps.find( sm_pos );
    if( sm == submaps.end() ) {
        return nullptr;
    } else {
        return sm->second;
    }
}
References coords::sm, and submaps.
Referenced by fetch_submap().
get_submap()
mm_submap & map_memory::get_submap (const tripoint & sm_pos) private
Find, load or allocate a submap.
Uses cache made by prepare_region to speed up the lookup.
Returns
the submap.
Definition at line 284 of file map_memory.cpp.
{
    // First, try fetching from cache.
    // If it's not in cache (or cache is absent), go the long way.
    if( cache_pos != tripoint_min ) {
        int zoffset = get_map().has_zlevels()
                      ? ( sm_pos.z + OVERMAP_DEPTH ) * cache_size.y * cache_size.x
                      : 0;
        const point idx = ( sm_pos - cache_pos ).xy();
        if( idx.x > 0 && idx.y > 0 && idx.x < cache_size.x && idx.y < cache_size.y ) {
            return *cached[idx.y * cache_size.x + idx.x + zoffset];
        }
    }
    return *fetch_submap( sm_pos );
}
References cache_pos, cache_size, cached, fetch_submap(), get_map(), map::has_zlevels(), OVERMAP_DEPTH, tripoint_min, point::x, point::y, and tripoint::z.
Referenced by clear_memorized_tile(), get_symbol(), get_tile(), memorize_symbol(), and memorize_tile().
get_symbol()
int map_memory::get_symbol (const tripoint & pos)
Returns memorized symbol.
Parameters
pos tile position, in global ms coords.
Definition at line 103 of file map_memory.cpp.
{
    coord_pair p( pos );
    const mm_submap &sm = get_submap( p.sm );
    return sm.symbol( p.loc );
}
References get_submap(), map_memory::coord_pair::loc, coords::sm, and map_memory::coord_pair::sm.
get_tile()
const memorized_terrain_tile & map_memory::get_tile (const tripoint & pos)
Returns memorized tile.
Parameters
pos tile position, in global ms coords.
Definition at line 73 of file map_memory.cpp.
{
    coord_pair p( pos );
    const mm_submap &sm = get_submap( p.sm );
    return sm.tile( p.loc );
}
References get_submap(), map_memory::coord_pair::loc, coords::sm, and map_memory::coord_pair::sm.
has_memory_for_autodrive()
bool map_memory::has_memory_for_autodrive (const tripoint & pos)
For autodrive use only.
Checks whether tile at given pos was memorized.
Parameters
pos tile position, in global ms coords.
Definition at line 80 of file map_memory.cpp.
{
    // HACK: Map memory is not supposed to be used by ingame mechanics.
    //       It's just a graphical overlay, it memorizes tileset tiles and text symbols.
    //       Problem is, many cars' headlights won't cover every ground tile in front of them at night,
    //       and these dark tiles would be considered as possible obstacles.
    //       To work around it, we check for whether map memory has any data associated with the tile
    //       and then assume it's up to date, which works in 99% cases.
    //       Oh, and we don't want to use get_tile() and get_symbol() to avoid looking up the mm_submap twice.
    coord_pair p( pos );
    shared_ptr_fast<mm_submap> sm = fetch_submap( p.sm );
    return sm->tile( p.loc ) != mm_submap::default_tile ||
           sm->symbol( p.loc ) != mm_submap::default_symbol;
}
References mm_submap::default_symbol, mm_submap::default_tile, fetch_submap(), map_memory::coord_pair::loc, coords::sm, and map_memory::coord_pair::sm.
load()
void map_memory::load (const tripoint & pos)
Load memorized submaps around given global map square pos.
Definition at line 300 of file map_memory.cpp.
{
    const std::string dirname = find_mm_dir();
    clear_cache();
    if( !dir_exist( dirname ) ) {
        // Old saves have [plname].mm file and no [plname].mm1 folder
        const std::string legacy_file = find_legacy_mm_file();
        if( file_exist( legacy_file ) ) {
            try {
                read_from_file_optional_json( legacy_file, [&]( JsonIn & jsin ) {
                    this->load_legacy( jsin );
                } );
            } catch( const std::exception &err ) {
                debugmsg( "Failed to load legacy memory map file: %s", err.what() );
            }
        }
        return;
    }
    coord_pair p( pos );
    tripoint start = p.sm - tripoint( MM_SIZE / 2, MM_SIZE / 2, 0 );
    dbg( DL::Info ) << "[LOAD] Loading memory map around " << p.sm << ". Loading submaps within "
                    << start << "->" << start + tripoint( MM_SIZE, MM_SIZE, 0 );
    for( int dy = 0; dy < MM_SIZE; dy++ ) {
        for( int dx = 0; dx < MM_SIZE; dx++ ) {
            fetch_submap( start + tripoint( dx, dy, 0 ) );
        }
    }
    dbg( DL::Info ) << "[LOAD] Done.";
}
References clear_cache(), dbg, debugmsg, dir_exist(), fetch_submap(), file_exist(), find_legacy_mm_file(), find_mm_dir(), Info, load_legacy(), MM_SIZE, read_from_file_optional_json(), and map_memory::coord_pair::sm.
load_legacy()
void map_memory::load_legacy (JsonIn & jsin)
Load legacy memory file.
TODO: remove after 0.F (or whatever BN will have instead).
Definition at line 3318 of file savegame_json.cpp.
{
    struct mig_elem {
        int symbol;
        memorized_terrain_tile tile;
    };
    std::map<tripoint, mig_elem> elems;
    jsin.start_array();
    jsin.start_array();
    while( !jsin.end_array() ) {
        jsin.start_array();
        tripoint p;
        p.x = jsin.get_int();
        p.y = jsin.get_int();
        p.z = jsin.get_int();
        mig_elem &elem = elems[p];
        elem.tile.tile = jsin.get_string();
        elem.tile.subtile = jsin.get_int();
        elem.tile.rotation = jsin.get_int();
        jsin.end_array();
    }
    jsin.start_array();
    while( !jsin.end_array() ) {
        jsin.start_array();
        tripoint p;
        p.x = jsin.get_int();
        p.y = jsin.get_int();
        p.z = jsin.get_int();
        elems[p].symbol = jsin.get_int();
        jsin.end_array();
    }
    jsin.end_array();
    for( const std::pair<const tripoint, mig_elem> &elem : elems ) {
        coord_pair cp( elem.first );
        shared_ptr_fast<mm_submap> sm = find_submap( cp.sm );
        if( !sm ) {
            sm = allocate_submap( cp.sm );
        }
        if( elem.second.tile != mm_submap::default_tile ) {
            sm->set_tile( cp.loc, elem.second.tile );
        }
        if( elem.second.symbol != mm_submap::default_symbol ) {
            sm->set_symbol( cp.loc, elem.second.symbol );
        }
    }
}
References mm_submap::default_symbol, mm_submap::default_tile, JsonIn::end_array(), JsonIn::get_int(), JsonIn::get_string(), map_memory::coord_pair::loc, coords::sm, map_memory::coord_pair::sm, JsonIn::start_array(), Character::symbol(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by load().
load_submap()
shared_ptr_fast< mm_submap > map_memory::load_submap (const tripoint & sm_pos) private
Load submap from disk.
Returns
nullptr if failed.
Definition at line 232 of file map_memory.cpp.
{
    if( test_mode ) {
        return nullptr;
    }
    const std::string dirname = find_mm_dir();
    reg_coord_pair p( sm_pos );
    const std::string path = find_region_path( dirname, p.reg );
    if( !dir_exist( dirname ) ) {
        // Old saves don't have [plname].mm1 folder
        return nullptr;
    }
    mm_region mmr;
    const auto loader = [&]( JsonIn & jsin ) {
        mmr.deserialize( jsin );
    };
    try {
        if( !read_from_file_optional_json( path, loader ) ) {
            // Region not found
            return nullptr;
        }
    } catch( const std::exception &err ) {
        debugmsg( "Failed to load memory map region (%d,%d,%d): %s",
                  p.reg.x, p.reg.y, p.reg.z, err.what() );
        return nullptr;
    }
    dbg( DL::Info ) << "Loaded mm_region " << p.reg << " [" << mmr_to_sm_copy( p.reg ) << "]";
    shared_ptr_fast<mm_submap> ret;
    for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
        for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
            tripoint pos = mmr_to_sm_copy( p.reg ) + tripoint( x, y, 0 );
            shared_ptr_fast<mm_submap> &sm = mmr.submaps[x][y];
            if( pos == sm_pos ) {
                ret = sm;
            }
            temp_remove_open_air( mmr.submaps[x][y] );
            submaps.insert( std::make_pair( pos, sm ) );
        }
    }
    return ret;
}
References dbg, debugmsg, mm_region::deserialize(), dir_exist(), find_mm_dir(), find_region_path(), Info, MM_REG_SIZE, mmr_to_sm_copy(), read_from_file_optional_json(), reg_coord_pair::reg, cata::hash64_detail::ret, coords::sm, mm_region::submaps, submaps, temp_remove_open_air(), test_mode, tripoint::x, tripoint::y, and tripoint::z.
Referenced by fetch_submap().
memorize_symbol()
void map_memory::memorize_symbol (const tripoint & pos, int symbol)
Memorizes given symbol, overwriting old value.
Parameters
pos tile position, in global ms coords.
Definition at line 110 of file map_memory.cpp.
{
    coord_pair p( pos );
    mm_submap &sm = get_submap( p.sm );
    sm.set_symbol( p.loc, symbol );
}
References get_submap(), map_memory::coord_pair::loc, coords::sm, map_memory::coord_pair::sm, and symbol().
memorize_tile()
void map_memory::memorize_tile (const tripoint & pos, const std::string & ter, int subtile, int rotation)
Memorizes given tile, overwriting old value.
Parameters
pos tile position, in global ms coords.
Definition at line 95 of file map_memory.cpp.
{
    coord_pair p( pos );
    mm_submap &sm = get_submap( p.sm );
    sm.set_tile( p.loc, memorized_terrain_tile{ ter, subtile, rotation } );
}
References get_submap(), map_memory::coord_pair::loc, coords::sm, and map_memory::coord_pair::sm.
prepare_region()
bool map_memory::prepare_region (const tripoint & p1, const tripoint & p2)
Prepares map memory for optimized rendering and/or memorization of given region.
Parameters
p1 top-left corner of the region, in global ms coords
p2 bottom-right corner of the region, in global ms coords Both coords are inclusive and should be on the same Z level.
Returns
whether the region was re-cached
Definition at line 125 of file map_memory.cpp.
{
    assert( p1.z == p2.z );
    assert( p1.x <= p2.x && p1.y <= p2.y );
    tripoint sm_p1 = coord_pair( p1 ).sm - point_south_east;
    tripoint sm_p2 = coord_pair( p2 ).sm + point_south_east;
    tripoint sm_pos = sm_p1;
    point sm_size = sm_p2.xy() - sm_p1.xy();
    bool z_levels = get_map().has_zlevels();
    if( sm_pos.z == cache_pos.z || z_levels ) {
        inclusive_rectangle<point> rect( cache_pos.xy(), cache_pos.xy() + cache_size );
        if( rect.contains( sm_p1.xy() ) && rect.contains( sm_p2.xy() ) ) {
            return false;
        }
    }
    dbg( DL::Info ) << "Preparing memory map for area: pos: " << sm_pos << " size: " << sm_size;
    int minz = z_levels ? -OVERMAP_DEPTH : p1.z;
    int maxz = z_levels ? OVERMAP_HEIGHT : p1.z;
    cache_pos = sm_pos;
    cache_size = sm_size;
    cached.clear();
    cached.reserve( cache_size.x * cache_size.y * ( maxz - minz + 1 ) );
    for( int z = minz; z <= maxz; z++ ) {
        for( int dy = 0; dy < cache_size.y; dy++ ) {
            for( int dx = 0; dx < cache_size.x; dx++ ) {
                cached.push_back( fetch_submap( tripoint( cache_pos.xy(), z ) + point( dx, dy ) ) );
            }
        }
    }
    return true;
}
References cache_pos, cache_size, cached, inclusive_rectangle< Point, >::contains(), dbg, fetch_submap(), get_map(), map::has_zlevels(), Info, OVERMAP_DEPTH, OVERMAP_HEIGHT, point_south_east, map_memory::coord_pair::sm, point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, and tripoint::z.
save()
bool map_memory::save (const tripoint & pos)
Save memorized submaps to disk, drop ones far from given global map square pos.
Definition at line 333 of file map_memory.cpp.
{
    tripoint sm_center = coord_pair( pos ).sm;
    const std::string dirname = find_mm_dir();
    assure_dir_exist( dirname );
    clear_cache();
    dbg( DL::Info ) << "N submaps before save: " << submaps.size();
    // Since mm_submaps are always allocated in regions,
    // we are certain that each region will be filled.
    std::map<tripoint, mm_region> regions;
    for( auto &it : submaps ) {
        const reg_coord_pair p( it.first );
        regions[p.reg].submaps[p.sm_loc.x][p.sm_loc.y] = it.second;
    }
    submaps.clear();
    constexpr point MM_HSIZE_P = point( MM_SIZE / 2, MM_SIZE / 2 );
    half_open_rectangle<point> rect_keep( sm_center.xy() - MM_HSIZE_P, sm_center.xy() + MM_HSIZE_P );
    dbg( DL::Info ) << "[SAVE] Saving memory map around " << sm_center << ". Keeping submaps within "
                    << rect_keep.p_min << "->" << rect_keep.p_max;
    bool result = true;
    for( auto &it : regions ) {
        const tripoint &regp = it.first;
        mm_region &reg = it.second;
        if( !reg.is_empty() ) {
            const std::string path = find_region_path( dirname, regp );
            const std::string descr = string_format(
                                          _( "memory map region for (%d,%d,%d)" ),
                                          regp.x, regp.y, regp.z
                                      );
            const auto writer = [&]( std::ostream & fout ) -> void {
                fout << serialize_wrapper( [&]( JsonOut & jsout )
                {
                    reg.serialize( jsout );
                } );
            };
            const bool res = write_to_file( path, writer, descr.c_str() );
            result = result & res;
        }
        tripoint regp_sm = mmr_to_sm_copy( regp );
        half_open_rectangle<point> rect_reg(
            regp_sm.xy(),
            regp_sm.xy() + point( MM_REG_SIZE, MM_REG_SIZE )
        );
        if( rect_reg.overlaps( rect_keep ) ) {
            dbg( DL::Info ) << "Keeping mm_region " << regp << " [" << regp_sm << "]";
            // Put submaps back
            for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
                for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
                    tripoint p = regp_sm + tripoint( x, y, 0 );
                    shared_ptr_fast<mm_submap> &sm = reg.submaps[x][y];
                    submaps.insert( std::make_pair( p, sm ) );
                }
            }
        } else {
            dbg( DL::Info ) << "Dropping mm_region " << regp << " [" << regp_sm << "]";
        }
    }
    dbg( DL::Info ) << "[SAVE] Done.";
    dbg( DL::Info ) << "N submaps after save: " << submaps.size();
    return result;
}
References _, assure_dir_exist(), clear_cache(), dbg, find_mm_dir(), find_region_path(), Info, mm_region::is_empty(), MM_REG_SIZE, MM_SIZE, mmr_to_sm_copy(), half_open_rectangle< Point, >::overlaps(), half_open_rectangle< Point, >::p_max, half_open_rectangle< Point, >::p_min, reg_coord_pair::reg, mm_region::serialize(), serialize_wrapper(), coords::sm, map_memory::coord_pair::sm, reg_coord_pair::sm_loc, string_format(), mm_region::submaps, submaps, write_to_file(), point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, and tripoint::z.
Member Data Documentation
cache_pos
tripoint map_memory::cache_pos private
Definition at line 185 of file map_memory.h.
Referenced by clear_cache(), get_submap(), and prepare_region().
cache_size
point map_memory::cache_size private
Definition at line 186 of file map_memory.h.
Referenced by clear_cache(), get_submap(), and prepare_region().
cached
std::vector<shared_ptr_fast<mm_submap> > map_memory::cached private
Definition at line 184 of file map_memory.h.
Referenced by clear_cache(), get_submap(), and prepare_region().
submaps
std::map<tripoint, shared_ptr_fast<mm_submap> > map_memory::submaps private
Definition at line 182 of file map_memory.h.
Referenced by allocate_submap(), find_submap(), load_submap(), and save().
The documentation for this class was generated from the following files:
src/map_memory.h
src/map_memory.cpp
src/savegame_json.cpp