Cataclysm BN: deploy_tent_actor Class Reference
deploy_tent_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
deploy_tent_actor ()
~deploy_tent_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
bool check_intact (const tripoint &center) const
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
string_id< furn_t > wall
string_id< furn_t > floor
cata::optional< string_id< furn_t > > floor_center
string_id< furn_t > door_opened
string_id< furn_t > door_closed
int radius = 1
cata::optional< itype_id > broken_type
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1197 of file iuse_actor.h.
Constructor & Destructor Documentation
deploy_tent_actor()
deploy_tent_actor::deploy_tent_actor () inline
Definition at line 1208 of file iuse_actor.h.
: iuse_actor("deploy_tent") {}
~deploy_tent_actor()
deploy_tent_actor::~deploy_tent_actor () override default
Member Function Documentation
check_intact()
bool deploy_tent_actor::check_intact (const tripoint & center) const
Definition at line 4644 of file iuse_actor.cpp.
{
    map &here = get_map();
    for( const tripoint &dest : here.points_in_radius( center, radius ) ) {
        const furn_id fid = here.furn( dest );
        if( dest == center && floor_center ) {
            if( fid != *floor_center ) {
                return false;
            }
        } else if( square_dist( dest, center ) < radius ) {
            // So we are inside the tent
            if( fid != floor ) {
                return false;
            }
        } else {
            // We are on the border of the tent
            if( fid != wall && fid != door_opened && fid != door_closed ) {
                return false;
            }
        }
    }
    return true;
}
References center, map::furn(), get_map(), map::points_in_radius(), and square_dist().
Referenced by iexamine::portable_structure().
clone()
std::unique_ptr< iuse_actor > deploy_tent_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4572 of file iuse_actor.cpp.
{
    return std::make_unique<deploy_tent_actor>( *this );
}
load()
void deploy_tent_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 4577 of file iuse_actor.cpp.
{
    assign( obj, "radius", radius );
    assign( obj, "wall", wall );
    assign( obj, "floor", floor );
    assign( obj, "floor_center", floor_center );
    assign( obj, "door_opened", door_opened );
    assign( obj, "door_closed", door_closed );
    assign( obj, "broken_type", broken_type );
}
References assign().
use()
int deploy_tent_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 4588 of file iuse_actor.cpp.
{
    int diam = 2 * radius + 1;
    if( p.is_mounted() ) {
        p.add_msg_if_player( _( "You cannot do that while mounted." ) );
        return 0;
    }
    const cata::optional<tripoint> dir = choose_direction( string_format(
            _( "Put up the %s where (%dx%d clear area)?" ), it.tname(), diam, diam ) );
    if( !dir ) {
        return 0;
    }
    const tripoint direction = *dir;
    map &here = get_map();
    // We place the center of the structure (radius + 1)
    // spaces away from the player.
    // First check there's enough room.
    const tripoint center = p.pos() + tripoint( ( radius + 1 ) * direction.x,
                            ( radius + 1 ) * direction.y, 0 );
    for( const tripoint &dest : here.points_in_radius( center, radius ) ) {
        if( const auto vp = here.veh_at( dest ) ) {
            add_msg( m_info, _( "The %s is in the way." ), vp->vehicle().name );
            return 0;
        }
        if( const Creature *const c = g->critter_at( dest ) ) {
            add_msg( m_info, _( "The %s is in the way." ), c->disp_name() );
            return 0;
        }
        if( here.impassable( dest ) || !here.has_flag( "FLAT", dest ) ) {
            add_msg( m_info, _( "The %s in that direction isn't suitable for placing the %s." ),
                     here.name( dest ), it.tname() );
            return 0;
        }
        if( here.has_furn( dest ) ) {
            add_msg( m_info, _( "There is already furniture (%s) there." ), here.furnname( dest ) );
            return 0;
        }
    }
    // Make a square of floor surrounded by wall.
    for( const tripoint &dest : here.points_in_radius( center, radius ) ) {
        here.furn_set( dest, wall );
    }
    for( const tripoint &dest : here.points_in_radius( center, radius - 1 ) ) {
        here.furn_set( dest, floor );
    }
    // Place the center floor and the door.
    if( floor_center ) {
        here.furn_set( center, *floor_center );
    }
    here.furn_set( p.pos() + direction, door_closed );
    add_msg( m_info, _( "You set up the %s on the ground." ), it.tname() );
    add_msg( m_info, _( "Examine the center square to pack it up again." ) );
    return 1;
}
References _, add_msg(), player::add_msg_if_player(), c, center, choose_direction(), map::furn_set(), map::furnname(), g, get_map(), map::has_flag(), map::has_furn(), map::impassable(), Character::is_mounted(), m_info, map::name(), map::points_in_radius(), Character::pos(), string_format(), item::tname(), and map::veh_at().
Member Data Documentation
broken_type
cata::optional<itype_id> deploy_tent_actor::broken_type
Definition at line 1206 of file iuse_actor.h.
Referenced by iexamine::portable_structure().
door_closed
string_id<furn_t> deploy_tent_actor::door_closed
Definition at line 1204 of file iuse_actor.h.
door_opened
string_id<furn_t> deploy_tent_actor::door_opened
Definition at line 1203 of file iuse_actor.h.
floor
string_id<furn_t> deploy_tent_actor::floor
Definition at line 1201 of file iuse_actor.h.
floor_center
cata::optional<string_id<furn_t> > deploy_tent_actor::floor_center
Definition at line 1202 of file iuse_actor.h.
radius
int deploy_tent_actor::radius = 1
Definition at line 1205 of file iuse_actor.h.
Referenced by iexamine::portable_structure().
wall
string_id<furn_t> deploy_tent_actor::wall
Definition at line 1200 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp