Cataclysm BN: manualnoise_actor Class Reference
manualnoise_actor Class Reference
Makes noise of a given volume.
#include <iuse_actor.h>
Public Member Functions
manualnoise_actor (const std::string &type="manualnoise")
~manualnoise_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string no_charges_message
std::string use_message
std::string noise_message
std::string noise_id
std::string noise_variant
int noise = 0
int moves = 0
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Makes noise of a given volume.
Definition at line 732 of file iuse_actor.h.
Constructor & Destructor Documentation
manualnoise_actor()
manualnoise_actor::manualnoise_actor (const std::string & type = "manualnoise") inline
Definition at line 743 of file iuse_actor.h.
: iuse_actor(type) {}
~manualnoise_actor()
manualnoise_actor::~manualnoise_actor () override default
Member Function Documentation
can_use()
ret_val< bool > manualnoise_actor::can_use (const Character & , const item & it, bool , const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 2297 of file iuse_actor.cpp.
{
    if( it.charges < it.type->charges_to_use() ) {
        return ret_val<bool>::make_failure( _( "This tool doesn't have enough charges." ) );
    }
    return ret_val<bool>::make_success();
}
References _, item::charges, itype::charges_to_use(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and item::type.
clone()
std::unique_ptr< iuse_actor > manualnoise_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2272 of file iuse_actor.cpp.
{
    return std::make_unique<manualnoise_actor>( *this );
}
load()
void manualnoise_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2261 of file iuse_actor.cpp.
{
    no_charges_message  = obj.get_string( "no_charges_message" );
    use_message         = obj.get_string( "use_message" );
    noise_message       = obj.get_string( "noise_message", "hsss" );
    noise_id            = obj.get_string( "noise_id", "misc" );
    noise_variant       = obj.get_string( "noise_variant", "default" );
    noise               = obj.get_int( "noise", 0 );
    moves               = obj.get_int( "moves", 0 );
}
References JsonObject::get_int(), JsonObject::get_string(), moves, no_charges_message, noise, noise_id, noise_message, noise_variant, and use_message.
use()
int manualnoise_actor::use (player & p, item & it, bool t, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2277 of file iuse_actor.cpp.
{
    if( t ) {
        return 0;
    }
    if( it.type->charges_to_use() != 0 && it.charges < it.type->charges_to_use() ) {
        p.add_msg_if_player( _( no_charges_message ) );
        return 0;
    }
    {
        p.moves -= moves;
        if( noise > 0 ) {
            sounds::sound( p.pos(), noise, sounds::sound_t::activity,
                           noise_message.empty() ? _( "Hsss" ) : _( noise_message ), true, noise_id, noise_variant );
        }
        p.add_msg_if_player( _( use_message ) );
    }
    return it.type->charges_to_use();
}
References _, sounds::activity, player::add_msg_if_player(), item::charges, itype::charges_to_use(), Creature::moves, moves, no_charges_message, noise, noise_id, noise_message, noise_variant, Character::pos(), sounds::sound(), item::type, and use_message.
Member Data Documentation
moves
int manualnoise_actor::moves = 0
Definition at line 741 of file iuse_actor.h.
Referenced by load(), and use().
no_charges_message
std::string manualnoise_actor::no_charges_message
Definition at line 735 of file iuse_actor.h.
Referenced by load(), and use().
noise
int manualnoise_actor::noise = 0
Definition at line 740 of file iuse_actor.h.
Referenced by load(), and use().
noise_id
std::string manualnoise_actor::noise_id
Definition at line 738 of file iuse_actor.h.
Referenced by load(), and use().
noise_message
std::string manualnoise_actor::noise_message
Definition at line 737 of file iuse_actor.h.
Referenced by load(), and use().
noise_variant
std::string manualnoise_actor::noise_variant
Definition at line 739 of file iuse_actor.h.
Referenced by load(), and use().
use_message
std::string manualnoise_actor::use_message
Definition at line 736 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp