Cataclysm BN: achievement Class Reference
achievement Class Reference
#include <achievement.h>
Classes
class time_bound
Public Member Functions
achievement ()=default
void load (const JsonObject &, const std::string &)
void check () const
const translation & name () const
const translation & description () const
const std::vector< string_id< achievement > > & hidden_by () const
const cata::optional< time_bound > & time_constraint () const
const std::vector< achievement_requirement > & requirements () const
Static Public Member Functions
static void load_achievement (const JsonObject &, const std::string &)
static void finalize ()
static void check_consistency ()
static const std::vector< achievement > & get_all ()
static void reset ()
Public Attributes
string_id< achievement > id
bool was_loaded = false
Private Attributes
translation name_
translation description_
std::vector< string_id< achievement > > hidden_by_
cata::optional< time_bound > time_constraint_
std::vector< achievement_requirement > requirements_
Detailed Description
Definition at line 56 of file achievement.h.
Constructor & Destructor Documentation
achievement()
achievement::achievement () default
Member Function Documentation
check()
void achievement::check () const
Definition at line 335 of file achievement.cpp.
{
    for( const string_id<achievement> &a : hidden_by_ ) {
        if( !a.is_valid() ) {
            debugmsg( "Achievement %s specifies hidden_by achievement %s, but the latter does not "
                      "exist.", id.str(), a.str() );
        }
    }
    if( time_constraint_ ) {
        time_constraint_->check( id );
    }
    for( const achievement_requirement &req : requirements_ ) {
        req.check( id );
    }
}
References a, debugmsg, hidden_by_, requirements_, and time_constraint_.
check_consistency()
void achievement::check_consistency () static
Definition at line 311 of file achievement.cpp.
{
    achievement_factory.check();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
const translation & achievement::description () const inline
Definition at line 76 of file achievement.h.
{
            return description_;
        }
References description_.
Referenced by achievement_tracker::ui_text(), achievement_state::ui_text(), and achievements_tracker::ui_text_for().
finalize()
void achievement::finalize () static
Definition at line 302 of file achievement.cpp.
{
    for( achievement &a : const_cast<std::vector<achievement>&>( achievement::get_all() ) ) {
        for( achievement_requirement &req : a.requirements_ ) {
            req.finalize();
        }
    }
}
References a, achievement_requirement::finalize(), and get_all().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< achievement > & achievement::get_all () static
Definition at line 316 of file achievement.cpp.
{
    return achievement_factory.get_all();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by finalize(), achievements_tracker::notify(), and achievements_tracker::valid_achievements().
hidden_by()
const std::vector< string_id< achievement > > & achievement::hidden_by () const inline
Definition at line 80 of file achievement.h.
{
            return hidden_by_;
        }
References hidden_by_.
Referenced by achievements_tracker::is_hidden().
load()
void achievement::load (const JsonObject & jo, const std::string &)
Definition at line 326 of file achievement.cpp.
{
    mandatory( jo, was_loaded, "name", name_ );
    optional( jo, was_loaded, "description", description_ );
    optional( jo, was_loaded, "hidden_by", hidden_by_ );
    optional( jo, was_loaded, "time_constraint", time_constraint_ );
    mandatory( jo, was_loaded, "requirements", requirements_ );
}
References description_, hidden_by_, mandatory(), name_, optional(), requirements_, time_constraint_, and was_loaded.
load_achievement()
void achievement::load_achievement (const JsonObject & jo, const std::string & src) static
Definition at line 297 of file achievement.cpp.
{
    achievement_factory.load( jo, src );
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::initialize().
name()
const translation & achievement::name () const inline
Definition at line 72 of file achievement.h.
{
            return name_;
        }
References name_.
Referenced by achievement_tracker::ui_text(), and achievement_state::ui_text().
requirements()
const std::vector< achievement_requirement > & achievement::requirements () const inline
Definition at line 109 of file achievement.h.
{
            return requirements_;
        }
References requirements_.
Referenced by achievement_state::ui_text().
reset()
void achievement::reset () static
Definition at line 321 of file achievement.cpp.
{
    achievement_factory.reset();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::unload_data().
time_constraint()
const cata::optional< time_bound > & achievement::time_constraint () const inline
Definition at line 105 of file achievement.h.
{
            return time_constraint_;
        }
References time_constraint_.
Referenced by achievement_tracker::set_requirement(), achievement_tracker::time_is_expired(), achievement_tracker::ui_text(), and achievement_state::ui_text().
Member Data Documentation
description_
translation achievement::description_ private
Definition at line 114 of file achievement.h.
Referenced by description(), and load().
hidden_by_
std::vector<string_id<achievement> > achievement::hidden_by_ private
Definition at line 115 of file achievement.h.
Referenced by check(), hidden_by(), and load().
id
string_id<achievement> achievement::id
Definition at line 69 of file achievement.h.
Referenced by achievements_tracker::is_hidden(), and achievements_tracker::ui_text_for().
name_
translation achievement::name_ private
Definition at line 113 of file achievement.h.
Referenced by load(), and name().
requirements_
std::vector<achievement_requirement> achievement::requirements_ private
Definition at line 117 of file achievement.h.
Referenced by check(), load(), and requirements().
time_constraint_
cata::optional<time_bound> achievement::time_constraint_ private
Definition at line 116 of file achievement.h.
Referenced by check(), load(), and time_constraint().
was_loaded
bool achievement::was_loaded = false
Definition at line 70 of file achievement.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp