Cataclysm BN: enum_bitset< E > Class Template Reference
enum_bitset< E > Class Template Reference
#include <enum_bitset.h>
Public Member Functions
enum_bitset ()=default
enum_bitset (const enum_bitset &)=default
enum_bitset & operator= (const enum_bitset &)=default
bool operator== (const enum_bitset &rhs) const noexcept
bool operator!= (const enum_bitset &rhs) const noexcept
enum_bitset & operator&= (const enum_bitset &rhs) noexcept
enum_bitset & operator|= (const enum_bitset &rhs) noexcept
bool operator[] (E e) const
enum_bitset & operator[] (E e)
enum_bitset & set (E e, bool val=true)
enum_bitset & set_all ()
enum_bitset & clear (E e)
enum_bitset & clear_all ()
bool test (E e) const
bool test_all () const
bool test_any () const
size_t count () const
Static Public Member Functions
static constexpr size_t size () noexcept
Static Private Member Functions
static constexpr size_t get_pos (E e) noexcept
Private Attributes
std::bitset< enum_bitset< E >::size()> bits
Detailed Description
template<typename E>
class enum_bitset< E >
Definition at line 11 of file enum_bitset.h.
Constructor & Destructor Documentation
enum_bitset() [1/2]
template<typename E > enum_bitset< E >::enum_bitset () default
enum_bitset() [2/2]
template<typename E > enum_bitset< E >::enum_bitset (const enum_bitset< E > &) default
Member Function Documentation
clear()
template<typename E > enum_bitset & enum_bitset< E >::clear (E e) inline
Definition at line 60 of file enum_bitset.h.
{
            bits.reset( get_pos( e ) );
            return *this;
        }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
Referenced by reader_detail::handler< enum_bitset< E > >::erase().
clear_all()
template<typename E > enum_bitset & enum_bitset< E >::clear_all () inline
Definition at line 65 of file enum_bitset.h.
{
            bits.reset();
            return *this;
        }
References enum_bitset< E >::bits.
Referenced by reader_detail::handler< enum_bitset< E > >::clear().
count()
template<typename E > size_t enum_bitset< E >::count () const inline
Definition at line 82 of file enum_bitset.h.
{
            return bits.count();
        }
References enum_bitset< E >::bits.
get_pos()
template<typename E > static constexpr size_t enum_bitset< E >::get_pos (E e) inline static constexpr private noexcept
Definition at line 91 of file enum_bitset.h.
{
            return static_cast<size_t>( static_cast<typename std::underlying_type<E>::type>( e ) );
        }
References type.
Referenced by enum_bitset< E >::clear(), enum_bitset< E >::operator[](), enum_bitset< E >::set(), enum_bitset< E >::size(), and enum_bitset< E >::test().
operator!=()
template<typename E > bool enum_bitset< E >::operator!= (const enum_bitset< E > & rhs) const inline noexcept
Definition at line 28 of file enum_bitset.h.
{
            return !( *this == rhs );
        }
operator&=()
template<typename E > enum_bitset & enum_bitset< E >::operator&= (const enum_bitset< E > & rhs) inline noexcept
Definition at line 32 of file enum_bitset.h.
{
            bits &= rhs.bits;
            return *this;
        }
References enum_bitset< E >::bits.
operator=()
template<typename E > enum_bitset & enum_bitset< E >::operator= (const enum_bitset< E > &) default
operator==()
template<typename E > bool enum_bitset< E >::operator== (const enum_bitset< E > & rhs) const inline noexcept
Definition at line 24 of file enum_bitset.h.
{
            return bits == rhs.bits;
        }
References enum_bitset< E >::bits.
operator[]() [1/2]
template<typename E > enum_bitset & enum_bitset< E >::operator[] (E e) inline
Definition at line 46 of file enum_bitset.h.
{
            return bits[ get_pos( e ) ];
        }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
operator[]() [2/2]
template<typename E > bool enum_bitset< E >::operator[] (E e) const inline
Definition at line 42 of file enum_bitset.h.
{
            return bits[ get_pos( e ) ];
        }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
operator|=()
template<typename E > enum_bitset & enum_bitset< E >::operator|= (const enum_bitset< E > & rhs) inline noexcept
Definition at line 37 of file enum_bitset.h.
{
            bits |= rhs.bits;
            return *this;
        }
References enum_bitset< E >::bits.
set()
template<typename E > enum_bitset & enum_bitset< E >::set (E e, bool val = true) inline
Definition at line 50 of file enum_bitset.h.
{
            bits.set( get_pos( e ), val );
            return *this;
        }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
Referenced by options_manager::cache_to_globals(), and reader_detail::handler< enum_bitset< E > >::insert().
set_all()
template<typename E > enum_bitset & enum_bitset< E >::set_all () inline
Definition at line 55 of file enum_bitset.h.
{
            bits.set();
            return *this;
        }
References enum_bitset< E >::bits.
size()
template<typename E > static constexpr size_t enum_bitset< E >::size () inline static constexpr noexcept
Definition at line 86 of file enum_bitset.h.
{
            return get_pos( enum_traits<E>::last );
        }
References enum_bitset< E >::get_pos().
test()
template<typename E > bool enum_bitset< E >::test (E e) const inline
Definition at line 70 of file enum_bitset.h.
{
            return bits.test( get_pos( e ) );
        }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
Referenced by fmt_mask().
test_all()
template<typename E > bool enum_bitset< E >::test_all () const inline
Definition at line 74 of file enum_bitset.h.
{
            return bits.all();
        }
References enum_bitset< E >::bits.
Referenced by fmt_mask().
test_any()
template<typename E > bool enum_bitset< E >::test_any () const inline
Definition at line 78 of file enum_bitset.h.
{
            return bits.any();
        }
References enum_bitset< E >::bits.
Referenced by fmt_mask().
Member Data Documentation
bits
template<typename E > std::bitset<enum_bitset<E>::size()> enum_bitset< E >::bits private
Definition at line 95 of file enum_bitset.h.
Referenced by enum_bitset< E >::clear(), enum_bitset< E >::clear_all(), enum_bitset< E >::count(), enum_bitset< E >::operator&=(), enum_bitset< E >::operator==(), enum_bitset< E >::operator[](), enum_bitset< E >::operator|=(), enum_bitset< E >::set(), enum_bitset< E >::set_all(), enum_bitset< E >::test(), enum_bitset< E >::test_all(), and enum_bitset< E >::test_any().
The documentation for this class was generated from the following files:
src/debug.h
src/enum_bitset.h