Cataclysm BN: mapgen_palette Class Reference
mapgen_palette Class Reference
#include <mapgen.h>
Public Types
using placing_map = std::unordered_map< map_key, std::vector< shared_ptr_fast< const jmapgen_piece > > >
The mapping from character (key) to a list of things that should be placed.
Public Member Functions
template<typename PieceType >
void load_place_mapings (const JsonObject &jo, const std::string &member_name, placing_map &format_placings)
Load (append to format_placings) the places that should be put there.
void check ()
Static Public Member Functions
static mapgen_palette load_temp (const JsonObject &jo, const std::string &src)
Loads a palette object and returns it.
static void load (const JsonObject &jo, const std::string &src)
Load a palette object and adds it to the global set of palettes.
static void reset ()
Unload all palettes.
static const mapgen_palette & get (const palette_id &id)
Returns a palette with given id.
static void check_definitions ()
Public Attributes
palette_id id
std::unordered_map< map_key, ter_id > format_terrain
std::unordered_map< map_key, furn_id > format_furniture
placing_map format_placings
Private Member Functions
void add (const palette_id &rh)
Adds a palette to this one.
void add (const mapgen_palette &rh)
Static Private Member Functions
static mapgen_palette load_internal (const JsonObject &jo, const std::string &src, bool require_id, bool allow_recur)
Detailed Description
Definition at line 210 of file mapgen.h.
Member Typedef Documentation
placing_map
using mapgen_palette::placing_map = std::unordered_map<map_key, std::vector< shared_ptr_fast<const jmapgen_piece> >>
The mapping from character (key) to a list of things that should be placed.
This is similar to objects, but it uses key to get the actual position where to place things out of the json "bitmap" (which is used to paint the terrain/furniture).
Definition at line 219 of file mapgen.h.
Member Function Documentation
add() [1/2]
void mapgen_palette::add (const mapgen_palette & rh) private
Definition at line 2225 of file mapgen.cpp.
{
    for( auto &placing : rh.format_placings ) {
        format_placings[ placing.first ] = placing.second;
    }
    for( auto &placing : rh.format_terrain ) {
        format_terrain[ placing.first ] = placing.second;
    }
    for( auto &placing : rh.format_furniture ) {
        format_furniture[ placing.first ] = placing.second;
    }
}
References format_furniture, format_placings, and format_terrain.
add() [2/2]
void mapgen_palette::add (const palette_id & rh) private
Adds a palette to this one.
New values take preference over the old ones.
Definition at line 2220 of file mapgen.cpp.
{
    add( get( rh ) );
}
References add(), and get().
Referenced by add(), and load_internal().
check()
void mapgen_palette::check ()
Definition at line 2165 of file mapgen.cpp.
{
    std::string context = "palette " + id;
    for( const std::pair<const map_key, furn_id> &p : format_furniture ) {
        if( check_furn( p.second, context ) ) {
            return;
        }
    }
    for( const auto &p : format_placings ) {
        for( const shared_ptr_fast<const jmapgen_piece> &j : p.second ) {
            j->check( context );
        }
    }
}
References check_furn(), format_furniture, format_placings, and id.
check_definitions()
void mapgen_palette::check_definitions () static
Definition at line 2213 of file mapgen.cpp.
{
    for( auto &p : palettes ) {
        p.second.check();
    }
}
References palettes.
Referenced by DynamicDataLoader::check_consistency().
get()
const mapgen_palette & mapgen_palette::get (const palette_id & id) static
Returns a palette with given id.
If not found, debugmsg and returns a dummy.
Definition at line 2201 of file mapgen.cpp.
{
    const auto iter = palettes.find( id );
    if( iter != palettes.end() ) {
        return iter->second;
    }
    debugmsg( "Requested palette with unknown id %s", id.c_str() );
    static mapgen_palette dummy;
    return dummy;
}
References debugmsg, and palettes.
Referenced by add().
load()
void mapgen_palette::load (const JsonObject & jo, const std::string & src) static
Load a palette object and adds it to the global set of palettes.
If "palette" field is specified, those palettes will be loaded recursively.
Definition at line 2186 of file mapgen.cpp.
{
    mapgen_palette ret = load_internal( jo, src, true, false );
    if( ret.id.empty() ) {
        jo.throw_error( "Named palette needs an id" );
    }
    palettes[ ret.id ] = ret;
}
References load_internal(), palettes, cata::hash64_detail::ret, and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
load_internal()
mapgen_palette mapgen_palette::load_internal (const JsonObject & jo, const std::string & src, bool require_id, bool allow_recur) static private
Definition at line 2238 of file mapgen.cpp.
{
    mapgen_palette new_pal;
    auto &format_placings = new_pal.format_placings;
    auto &format_terrain = new_pal.format_terrain;
    auto &format_furniture = new_pal.format_furniture;
    if( require_id ) {
        new_pal.id = jo.get_string( "id" );
    }
    if( jo.has_array( "palettes" ) ) {
        if( allow_recur ) {
            auto pals = jo.get_string_array( "palettes" );
            for( auto &p : pals ) {
                new_pal.add( p );
            }
        } else {
            jo.throw_error( "Recursive palettes are not implemented yet" );
        }
    }
    // mandatory: every character in rows must have matching entry, unless fill_ter is set
    // "terrain": { "a": "t_grass", "b": "t_lava" }
    if( jo.has_member( "terrain" ) ) {
        for( const JsonMember member : jo.get_object( "terrain" ) ) {
            const map_key key( member );
            if( member.test_string() ) {
                format_terrain[key] = ter_id( member.get_string() );
            } else {
                auto &vect = format_placings[ key ];
                ::load_place_mapings<jmapgen_terrain>( member, vect );
                if( !vect.empty() ) {
                    // Dummy entry to signal that this terrain is actually defined, because
                    // the code below checks that each square on the map has a valid terrain
                    // defined somehow.
                    format_terrain[key] = t_null;
                }
            }
        }
    }
    if( jo.has_object( "furniture" ) ) {
        for( const JsonMember member : jo.get_object( "furniture" ) ) {
            const map_key key( member );
            if( member.test_string() ) {
                format_furniture[key] = furn_id( member.get_string() );
            } else {
                auto &vect = format_placings[ key ];
                ::load_place_mapings<jmapgen_furniture>( member, vect );
            }
        }
    }
    new_pal.load_place_mapings<jmapgen_field>( jo, "fields", format_placings );
    new_pal.load_place_mapings<jmapgen_npc>( jo, "npcs", format_placings );
    new_pal.load_place_mapings<jmapgen_sign>( jo, "signs", format_placings );
    new_pal.load_place_mapings<jmapgen_vending_machine>( jo, "vendingmachines", format_placings );
    new_pal.load_place_mapings<jmapgen_toilet>( jo, "toilets", format_placings );
    new_pal.load_place_mapings<jmapgen_gaspump>( jo, "gaspumps", format_placings );
    new_pal.load_place_mapings<jmapgen_item_group>( jo, "items", format_placings );
    new_pal.load_place_mapings<jmapgen_monster_group>( jo, "monsters", format_placings );
    new_pal.load_place_mapings<jmapgen_vehicle>( jo, "vehicles", format_placings );
    // json member name is not optimal, it should be plural like all the others above, but that conflicts
    // with the items entry with refers to item groups.
    new_pal.load_place_mapings<jmapgen_spawn_item>( jo, "item", format_placings );
    new_pal.load_place_mapings<jmapgen_trap>( jo, "traps", format_placings );
    new_pal.load_place_mapings<jmapgen_monster>( jo, "monster", format_placings );
    new_pal.load_place_mapings<jmapgen_furniture>( jo, "furniture", format_placings );
    new_pal.load_place_mapings<jmapgen_terrain>( jo, "terrain", format_placings );
    new_pal.load_place_mapings<jmapgen_make_rubble>( jo, "rubble", format_placings );
    new_pal.load_place_mapings<jmapgen_computer>( jo, "computers", format_placings );
    new_pal.load_place_mapings<jmapgen_sealed_item>( jo, "sealed_item", format_placings );
    new_pal.load_place_mapings<jmapgen_nested>( jo, "nested", format_placings );
    new_pal.load_place_mapings<jmapgen_liquid_item>( jo, "liquids", format_placings );
    new_pal.load_place_mapings<jmapgen_graffiti>( jo, "graffiti", format_placings );
    new_pal.load_place_mapings<jmapgen_translate>( jo, "translate", format_placings );
    new_pal.load_place_mapings<jmapgen_zone>( jo, "zones", format_placings );
    new_pal.load_place_mapings<jmapgen_ter_furn_transform>( jo, "ter_furn_transforms",
            format_placings );
    new_pal.load_place_mapings<jmapgen_faction>( jo, "faction_owner_character", format_placings );
    return new_pal;
}
References add(), format_furniture, format_placings, format_terrain, JsonObject::get_object(), JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), id, load_place_mapings(), load_place_mapings< jmapgen_furniture >(), load_place_mapings< jmapgen_terrain >(), mapgen_defer::member, t_null, ter_id, and JsonObject::throw_error().
Referenced by load(), and load_temp().
load_place_mapings()
template<typename PieceType > void mapgen_palette::load_place_mapings (const JsonObject & jo, const std::string & member_name, placing_map & format_placings)
Load (append to format_placings) the places that should be put there.
member_name is the name of an optional object / array in the json object jsi.
Definition at line 2118 of file mapgen.cpp.
{
    if( jo.has_object( "mapping" ) ) {
        for( const JsonMember member : jo.get_object( "mapping" ) ) {
            const map_key key( member );
            JsonObject sub = member.get_object();
            sub.allow_omitted_members();
            if( !sub.has_member( member_name ) ) {
                continue;
            }
            auto &vect = format_placings[ key ];
            ::load_place_mapings<PieceType>( sub.get_member( member_name ), vect );
        }
    }
    if( !jo.has_object( member_name ) ) {
        return;
    }
    /* This is kind of a hack. Loading furniture/terrain from `jo` is already done in
     * mapgen_palette::load_temp, continuing here would load it again and cause trouble.
     */
    if( member_name == "terrain" || member_name == "furniture" ) {
        return;
    }
    for( const JsonMember member : jo.get_object( member_name ) ) {
        const map_key key( member );
        auto &vect = format_placings[ key ];
        ::load_place_mapings<PieceType>( member, vect );
    }
}
References JsonObject::allow_omitted_members(), format_placings, JsonObject::get_member(), JsonObject::get_object(), JsonObject::has_member(), JsonObject::has_object(), and mapgen_defer::member.
Referenced by load_internal().
load_temp()
mapgen_palette mapgen_palette::load_temp (const JsonObject & jo, const std::string & src) static
Loads a palette object and returns it.
Doesn't save it anywhere.
Definition at line 2181 of file mapgen.cpp.
{
    return load_internal( jo, src, false, true );
}
References load_internal().
Referenced by mapgen_function_json_base::setup_common().
reset()
void mapgen_palette::reset () static
Unload all palettes.
Definition at line 2196 of file mapgen.cpp.
{
    palettes.clear();
}
References palettes.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
format_furniture
std::unordered_map<map_key, furn_id> mapgen_palette::format_furniture
Definition at line 223 of file mapgen.h.
Referenced by add(), check(), load_internal(), and mapgen_function_json_base::setup_common().
format_placings
placing_map mapgen_palette::format_placings
Definition at line 224 of file mapgen.h.
Referenced by add(), check(), load_internal(), load_place_mapings(), and mapgen_function_json_base::setup_common().
format_terrain
std::unordered_map<map_key, ter_id> mapgen_palette::format_terrain
Definition at line 222 of file mapgen.h.
Referenced by add(), load_internal(), and mapgen_function_json_base::setup_common().
id
palette_id mapgen_palette::id
Definition at line 213 of file mapgen.h.
Referenced by check(), and load_internal().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp