Cataclysm BN: int_id< T > Class Template Reference
int_id< T > Class Template Reference
Just like the string_id, this is a wrapper for int based identifiers.
#include <int_id.h>
Public Types
using This = int_id< T >
Public Member Functions
int_id (const int id)
Explicit constructor to make it stand out in the code, so one can easily search for all places that use it.
template<typename S , typename std::enable_if_t< !std::is_same< S, T >::value, int > = 0>
int_id (const int_id< S > &id)=delete
Prevent accidental construction from other int ids.
int_id ()
Default constructor constructs a 0-id.
int_id (const string_id< T > &id)
Construct an id from the matching string based id.
template<typename S , class = typename std::enable_if< std::is_convertible<S, std::string >::value>::type>
int_id (S &&id)
Forwarding constructor, forwards any parameter to the string_id constructor to create the int id.
bool operator< (const This &rhs) const
Comparison, only useful when the id is used in std::map or std::set as key.
bool operator== (const This &rhs) const
The usual comparator, compares the integer id as usual.
bool operator!= (const This &rhs) const
The usual comparator, compares the integer id as usual.
int to_i () const
Returns the identifier as plain int.
operator int () const
Conversion to int as with the to_i function.
operator bool () const
const string_id< T > & id () const
const T & obj () const
const T & operator* () const
const T * operator-> () const
bool is_valid () const
Returns whether this id is valid, that means whether it refers to an existing object.
const oter_type_t & obj () const
Private Attributes
int _id
Related Functions
(Note that these are not member functions.)
template<>
bool is_valid () const
template<>
const ammo_effect & obj () const
template<>
const string_id< ammo_effect > & id () const
template<>
int_id (const string_id< ammo_effect > &id)
template<>
bool is_valid () const
template<>
const body_part_type & obj () const
template<>
const bodypart_str_id & id () const
template<>
int_id (const string_id< body_part_type > &id)
template<>
bool is_valid () const
template<>
const field_type & obj () const
template<>
const string_id< field_type > & id () const
template<>
int_id (const string_id< field_type > &id)
template<>
bool is_valid () const
template<>
const json_flag & obj () const
template<>
const flag_str_id & id () const
template<>
int_id (const flag_str_id &id)
template<>
bool is_valid () const
template<>
const ter_t & obj () const
template<>
const string_id< ter_t > & id () const
template<>
int_id (const string_id< ter_t > &id)
template<>
bool is_valid () const
template<>
const furn_t & obj () const
template<>
int_id (const string_id< furn_t > &id)
template<>
const monfaction & obj () const
template<>
const string_id< monfaction > & id () const
template<>
int_id (const string_id< monfaction > &id)
template<>
const string_id< oter_type_t > & id () const
template<>
int_id (const string_id< oter_type_t > &id)
template<>
int_id (const string_id< oter_t > &id)
template<>
bool is_valid () const
template<>
const oter_t & obj () const
template<>
const string_id< oter_t > & id () const
template<>
const trap & obj () const
template<>
const string_id< trap > & id () const
template<>
bool is_valid () const
Detailed Description
template<typename T>
class int_id< T >
Just like the string_id, this is a wrapper for int based identifiers.
The template parameter T specifies what kind of object it identifies (e.g. a trap type, monster type, ...)
Definition at line 19 of file int_id.h.
Member Typedef Documentation
This
template<typename T > using int_id< T >::This = int_id<T>
Definition at line 22 of file int_id.h.
Constructor & Destructor Documentation
int_id() [1/5]
template<typename T > int_id< T >::int_id (const int id) inline explicit
Explicit constructor to make it stand out in the code, so one can easily search for all places that use it.
Definition at line 28 of file int_id.h.
            : _id( id ) {
        }
int_id() [2/5]
template<typename T > template<typename S , typename std::enable_if_t< !std::is_same< S, T >::value, int > = 0> int_id< T >::int_id (const int_id< S > & id) delete
Prevent accidental construction from other int ids.
int_id() [3/5]
template<typename T > int_id< T >::int_id () inline
Default constructor constructs a 0-id.
No id value is special to this class, 0 as id is just as normal as any other integer value.
Definition at line 42 of file int_id.h.
            : _id( 0 ) {
        }
int_id() [4/5]
template<typename T > int_id< T >::int_id (const string_id< T > & id)
Construct an id from the matching string based id.
This may show a debug message if the string id is invalid.
int_id() [5/5]
template<typename T > template<typename S , class = typename std::enable_if< std::is_convertible<S, std::string >::value>::type> int_id< T >::int_id (S && id) inline explicit
Forwarding constructor, forwards any parameter to the string_id constructor to create the int id.
This allows plain C-strings, and std::strings to be used.
Definition at line 58 of file int_id.h.
: int_id(string_id<T>(std::forward<S>(id))) {}
Member Function Documentation
id()
template<typename T > const string_id< ammo_effect > & id () const
Definition at line 33 of file ammo_effect.cpp.
{
    return all_ammo_effects.convert( *this );
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::autoclave_full(), iexamine::autodoc(), cata_event_dispatch::avatar_moves(), Character::bionic_armor_bonus(), overmap::build_connection(), overmap::build_lab(), ter_t::check(), map::close_door(), companion_travel_time_calc(), overmap_specials::create_building_from(), debug_menu::debug(), basecamp::define_camp(), iuse::dig(), iuse::dig_channel(), draw_limb_health(), map::draw_map(), elevate_bridges(), Character::extended_description(), mapgen_function_json::generate(), generate_uniform(), Character::get_armor_bash_base(), Character::get_armor_bullet_base(), Character::get_armor_cut_base(), Character::get_env_resist(), get_heat_radiation(), Creature::get_random_body_part(), map::get_roof(), Character::get_used_bionics_slots(), good_fishing_spot(), map::grow_plant(), is_ot_match(), jmapgen_field::jmapgen_field(), iexamine::kiln_empty(), iexamine::kiln_full(), generic_factory< T >::load(), mapgen_parking_lot(), editmap::mapgen_preview(), mapgen_road(), mill_activate(), iexamine::mill_finalize(), talk_function::om_building_region(), om_companion_path(), om_target_tile(), Character::on_damage_of_type(), open(), map::open_door(), operator==(), oter_get_rotation_dir(), oter_no_dir(), map::place_items(), map::place_spawns(), iexamine::portable_structure(), map::process_fields_in_submap(), talk_function::recover_camp(), blueprint_options::serialize(), overmap::serialize(), conditional_t< T >::set_at_om_location(), smoker_activate(), smoker_finalize(), talk_function::start_camp(), basecamp::start_cut_logs(), basecamp::start_fortifications(), submap::store(), basecamp::survey_return(), jmapgen_nested::neighborhood_check::test(), gates::toggle_gate(), explosion_iuse::trigger_explosion(), editmap::update_view_with_help(), heal_actor::use_healing_item(), and game::walk_move().
is_valid()
template<typename T > bool is_valid () const
Returns whether this id is valid, that means whether it refers to an existing object.
Definition at line 19 of file ammo_effect.cpp.
{
    return all_ammo_effects.is_valid( *this );
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by ammo_effect::check(), jmapgen_sealed_item::check(), and colorized_feature_description_at().
obj() [1/2]
template<typename T > const ammo_effect & obj () const
Definition at line 26 of file ammo_effect.cpp.
{
    return all_ammo_effects.obj( *this );
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by map::actualize(), field::add_field(), apply_base_faction(), Character::base_comfort_value(), map::bash_furn_success(), map::bash_rating(), map::bash_resistance(), map::bash_strength(), map::bash_ter_furn(), map::bash_ter_success(), board_up(), activity_handlers::build_do_turn(), map::build_floor_cache(), MapExtras::burned_ground_parser(), can_examine_at(), map::can_move_furniture(), jmapgen_sealed_item::check(), construct::check_deconstruct(), map::close_door(), field_entry::color(), complete_construction(), field_entry::convection_temperature_mod(), iexamine::curtains(), MapExtras::dead_vegetation_parser(), field_entry::decays_on_actualize(), iexamine::deployed_furniture(), map::determine_wall_corner(), field::displayed_description_affix(), game::do_turn(), construct::done_deconstruct(), editmap_hilight::draw(), overmap_ui::draw_ascii(), editmap::draw_main_ui_overlay(), map::draw_maptile(), overmap_ui::draw_om_sidebar(), map::drop_furniture(), editmap::edit_fld(), map::examine(), game::examine(), game::extended_description(), field_entry::extra_radiation_max(), field_entry::extra_radiation_min(), activity_handlers::fill_liquid_do_turn(), activity_handlers::fill_pit_finish(), monfactions::finalize(), dig_activity_actor::finish(), dig_channel_activity_actor::finish(), iexamine::fireplace(), Character::floor_bedding_warmth(), game::forced_door_closing(), inventory::form_from_map(), furn_is_supported(), map::furn_set(), map::furnname(), field_entry::gas_can_spread(), generic_multi_activity_locations(), get_alt_ter(), get_convection_temperature(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), maptile::get_furn_t(), map::get_furn_transforms_into(), field_entry::get_gas_absorption_factor(), get_hack_type(), get_keg_capacity(), map::get_known_connections(), field_entry::get_max_field_intensity(), map::get_roof(), submap::get_signage(), maptile::get_ter_t(), map::get_ter_transforms_into(), maptile::get_trap_t(), field_entry::get_underwater_age_speedup(), grab(), game::grabbed_furn_move(), map::grow_plant(), map::has_flag_furn(), map::has_flag_ter(), map::has_flag_ter_or_furn(), submap::has_signage(), int_id< T >::id(), field_entry::intensity_upgrade_chance(), field_entry::intensity_upgrade_duration(), map::is_bashable(), map::is_bashable_furn(), map::is_bashable_ter(), field_entry::is_dangerous(), Character::is_immune_field(), monster::is_immune_field(), field_entry::is_transparent(), iexamine::ledge(), field_entry::light_emitted(), explosion_iuse::load(), field_entry::local_light_override(), talk_function::loot_building(), mapgen_lake_shore(), fungal_effects::marlossify(), map_stack::max_volume(), field_entry::monster_spawn_chance(), field_entry::monster_spawn_count(), field_entry::monster_spawn_group(), field_entry::monster_spawn_radius(), field_entry::move_cost(), map::move_cost(), map::move_cost_ter_furn(), field_entry::name(), vehicle::noise_and_smoke(), int_id< T >::obj(), om_cutdown_trees(), om_harvest_furn(), om_harvest_ter(), map::open_door(), int_id< T >::operator*(), int_id< T >::operator->(), map::place_items(), game::place_player(), overmap_ui::place_ter_or_special(), game::print_trap_info(), map::process_fields_in_submap(), activity_handlers::pulp_do_turn(), map::rad_scorch(), field_entry::radiation_hurt_damage_max(), field_entry::radiation_hurt_damage_min(), field_entry::radiation_hurt_message(), iexamine::reload_furniture(), map::remove_field(), field::remove_field(), map::remove_trap(), map::restock_fruits(), set_item_map_or_vehicle(), smash(), fungal_effects::spread_fungus_one_tile(), map::supports_above(), field_entry::symbol(), map::ter_set(), map::tername(), map::tr_at(), map::translate(), map::translate_radius(), field_entry::translucency(), iexamine::trap(), map::trap_set(), activity_handlers::tree_communion_do_turn(), player::try_to_sleep(), editmap::update_fmenu_entry(), map::update_suspension_cache(), editmap::update_view_with_help(), iexamine::use_furn_fake_item(), map::vehicle_wheel_traction(), game::walk_move(), map::water_from(), and workbench_crafting_speed_multiplier().
obj() [2/2]
const oter_t & obj () const
Definition at line 269 of file overmap.cpp.
{
    return terrain_types.obj( *this );
}
References anonymous_namespace{overmap.cpp}::terrain_types.
operator bool()
template<typename T > int_id< T >::operator bool () const inline explicit
Definition at line 94 of file int_id.h.
{
            return _id != 0;
        }
References int_id< T >::_id.
operator int()
template<typename T > int_id< T >::operator int () const inline explicit
Conversion to int as with the to_i function.
Definition at line 90 of file int_id.h.
{
            return _id;
        }
References int_id< T >::_id.
operator!=()
template<typename T > bool int_id< T >::operator!= (const This & rhs) const inline
The usual comparator, compares the integer id as usual.
Definition at line 75 of file int_id.h.
{
            return _id != rhs._id;
        }
References int_id< T >::_id.
operator*()
template<typename T > const T & int_id< T >::operator* () const inline
Definition at line 103 of file int_id.h.
{
            return obj();
        }
References int_id< T >::obj().
operator->()
template<typename T > const T * int_id< T >::operator-> () const inline
Definition at line 107 of file int_id.h.
{
            return &obj();
        }
References int_id< T >::obj().
operator<()
template<typename T > bool int_id< T >::operator< (const This & rhs) const inline
Comparison, only useful when the id is used in std::map or std::set as key.
Definition at line 63 of file int_id.h.
{
            return _id < rhs._id;
        }
References int_id< T >::_id.
operator==()
template<typename T > bool int_id< T >::operator== (const This & rhs) const inline
The usual comparator, compares the integer id as usual.
Definition at line 69 of file int_id.h.
{
            return _id == rhs._id;
        }
References int_id< T >::_id.
to_i()
template<typename T > int int_id< T >::to_i () const inline
Returns the identifier as plain int.
Use with care, the plain int does not have any information as what type of object it refers to (the T template parameter of the class).
Definition at line 84 of file int_id.h.
{
            return _id;
        }
References int_id< T >::_id.
Referenced by map::actualize(), editmap_hilight::draw(), generic_factory< T >::insert(), monfactions::load_monster_faction(), generic_factory< T >::obj(), map::remove_trap(), editmap::setup_fmenu(), mapgen_function_json_base::setup_setmap(), map::ter_set(), editmap::update_fmenu_entry(), and editmap::update_view_with_help().
Friends And Related Function Documentation
id() [1/9]
const bodypart_str_id & id () const related
Definition at line 33 of file ammo_effect.cpp.
{
    return all_ammo_effects.convert( *this );
}
Referenced by apply_ammo_effects(), are_requirements_nearby(), belongs_to_connection(), do_purify(), find_tent_itype(), get_all_mutation_prereqs(), iexamine::get_harvest_items(), monfactions::get_or_add_faction(), list_filter_high_priority(), list_filter_low_priority(), load_inline_topic(), load_overlay_ordering_into_array(), load_talk_topic(), mapgen_lake_shore(), iuse::purify_iv(), and sounds::sound().
id() [2/9]
const string_id< field_type > & id () const related
Definition at line 164 of file bodypart.cpp.
{
    return body_part_factory.convert( *this );
}
References anonymous_namespace{bodypart.cpp}::body_part_factory.
id() [3/9]
const flag_str_id & id () const related
Definition at line 98 of file field_type.cpp.
{
    return all_field_types.convert( *this );
}
References anonymous_namespace{field_type.cpp}::all_field_types.
id() [4/9]
const string_id< ter_t > & id () const related
Definition at line 33 of file flag.cpp.
{
    return json_flags_all.convert( *this );
}
References anonymous_namespace{flag.cpp}::json_flags_all.
id() [5/9]
const string_id< monfaction > & id () const related
Definition at line 67 of file mapdata.cpp.
{
    return terrain_data.convert( *this );
}
References anonymous_namespace{mapdata.cpp}::terrain_data.
id() [6/9]
const string_id< oter_type_t > & id () const related
Definition at line 38 of file monfaction.cpp.
{
    return obj().id;
}
References int_id< T >::obj().
id() [7/9]
const string_id< oter_t > & id () const related
Definition at line 252 of file overmap.cpp.
{
    return terrain_types.convert( *this );
}
References anonymous_namespace{overmap.cpp}::terrain_types.
id() [8/9]
const string_id< trap > & id () const related
Definition at line 322 of file overmap.cpp.
{
    return terrains.convert( *this );
}
References anonymous_namespace{overmap.cpp}::terrains.
id() [9/9]
const string_id< trap > & id () const related
Definition at line 56 of file trap.cpp.
{
    return trap_factory.convert( *this );
}
References anonymous_namespace{trap.cpp}::trap_factory.
int_id() [1/9]
int_id (const flag_str_id & id) related
Definition at line 61 of file flag.cpp.
                                       : _id( id.id() )
{
}
int_id() [2/9]
int_id (const string_id< ammo_effect > & id) related
Definition at line 61 of file ammo_effect.cpp.
                                                              : _id( id.id() )
{
}
int_id() [3/9]
int_id (const string_id< body_part_type > & id) related
Definition at line 178 of file bodypart.cpp.
: _id(id.id()) {}
int_id() [4/9]
int_id (const string_id< field_type > & id) related
Definition at line 126 of file field_type.cpp.
                                                            : _id( id.id() )
{
}
int_id() [5/9]
int_id (const string_id< furn_t > & id) related
Definition at line 143 of file mapdata.cpp.
                                                    : _id( id.id() )
{
}
int_id() [6/9]
int_id (const string_id< monfaction > & id) related
Definition at line 71 of file monfaction.cpp.
    : _id( id.id() )
{
}
int_id() [7/9]
int_id (const string_id< oter_t > & id) related
Definition at line 304 of file overmap.cpp.
: _id(id.id()) {}
int_id() [8/9]
int_id (const string_id< oter_type_t > & id) related
Definition at line 266 of file overmap.cpp.
: _id(id.id()) {}
int_id() [9/9]
int_id (const string_id< ter_t > & id) related
Definition at line 81 of file mapdata.cpp.
                                                  : _id( id.id() )
{
}
is_valid() [1/8]
bool is_valid () const related
Definition at line 19 of file ammo_effect.cpp.
{
    return all_ammo_effects.is_valid( *this );
}
Referenced by apply_ammo_effects(), talk_function::bionic_remove(), and base_camps::max_upgrade_by_type().
is_valid() [2/8]
bool is_valid () const related
Definition at line 143 of file bodypart.cpp.
{
    return body_part_factory.is_valid( *this );
}
References anonymous_namespace{bodypart.cpp}::body_part_factory.
is_valid() [3/8]
bool is_valid () const related
Definition at line 84 of file field_type.cpp.
{
    return all_field_types.is_valid( *this );
}
References anonymous_namespace{field_type.cpp}::all_field_types.
is_valid() [4/8]
bool is_valid () const related
Definition at line 19 of file flag.cpp.
{
    return json_flags_all.is_valid( *this );
}
References anonymous_namespace{flag.cpp}::json_flags_all.
is_valid() [5/8]
bool is_valid () const related
Definition at line 53 of file mapdata.cpp.
{
    return terrain_data.is_valid( *this );
}
References anonymous_namespace{mapdata.cpp}::terrain_data.
is_valid() [6/8]
bool is_valid () const related
Definition at line 101 of file mapdata.cpp.
{
    return furniture_data.is_valid( *this );
}
References anonymous_namespace{mapdata.cpp}::furniture_data.
is_valid() [7/8]
bool is_valid () const related
Definition at line 308 of file overmap.cpp.
{
    return terrains.is_valid( *this );
}
References anonymous_namespace{overmap.cpp}::terrains.
is_valid() [8/8]
bool is_valid () const related
Definition at line 83 of file trap.cpp.
{
    return trap_factory.is_valid( *this );
}
References anonymous_namespace{trap.cpp}::trap_factory.
obj() [1/9]
const body_part_type & obj () const related
Definition at line 26 of file ammo_effect.cpp.
{
    return all_ammo_effects.obj( *this );
}
Referenced by assign(), butchery_drops_harvest(), calc_category(), crafting::can_disassemble(), activity_handlers::chop_logs_finish(), Messages::deserialize(), deserialize(), draw_ai_goal(), find_ammo_helper(), find_index(), load_distribution(), load_languages(), load_min_max(), visitable< T >::parents(), parse_vp_reqs(), pass_to_ownership_handling(), prompt_disassemble_in_seq(), visitable< T >::remove_item(), retrieve_index(), serialize(), and iuse::water_purifier().
obj() [2/9]
const field_type & obj () const related
Definition at line 157 of file bodypart.cpp.
{
    return body_part_factory.obj( *this );
}
References anonymous_namespace{bodypart.cpp}::body_part_factory.
obj() [3/9]
const json_flag & obj () const related
Definition at line 91 of file field_type.cpp.
{
    return all_field_types.obj( *this );
}
References anonymous_namespace{field_type.cpp}::all_field_types.
obj() [4/9]
const ter_t & obj () const related
Definition at line 26 of file flag.cpp.
{
    return json_flags_all.obj( *this );
}
References anonymous_namespace{flag.cpp}::json_flags_all.
obj() [5/9]
const furn_t & obj () const related
Definition at line 60 of file mapdata.cpp.
{
    return terrain_data.obj( *this );
}
References anonymous_namespace{mapdata.cpp}::terrain_data.
obj() [6/9]
const monfaction & obj () const related
Definition at line 108 of file mapdata.cpp.
{
    return furniture_data.obj( *this );
}
References anonymous_namespace{mapdata.cpp}::furniture_data.
obj() [7/9]
const monfaction & obj () const related
Definition at line 26 of file monfaction.cpp.
{
    if( static_cast<size_t>( _id ) >= faction_list.size() ) {
        debugmsg( "invalid monfaction id %d", _id );
        return mfaction_id( 0 ).obj();
    }
    return faction_list[_id];
}
References int_id< T >::_id, debugmsg, faction_list, and int_id< T >::obj().
obj() [8/9]
const trap & obj () const related
Definition at line 315 of file overmap.cpp.
{
    return terrains.obj( *this );
}
References anonymous_namespace{overmap.cpp}::terrains.
obj() [9/9]
const trap & obj () const related
Definition at line 49 of file trap.cpp.
{
    return trap_factory.obj( *this );
}
References anonymous_namespace{trap.cpp}::trap_factory.
Member Data Documentation
_id
template<typename T > int int_id< T >::_id private
Definition at line 117 of file int_id.h.
Referenced by int_id< T >::obj(), int_id< T >::operator bool(), int_id< T >::operator int(), int_id< T >::operator!=(), int_id< T >::operator<(), int_id< T >::operator==(), and int_id< T >::to_i().
The documentation for this class was generated from the following files:
src/int_id.h
src/ammo_effect.cpp
src/bodypart.cpp
src/field_type.cpp
src/flag.cpp
src/mapdata.cpp
src/monfaction.cpp
src/overmap.cpp
src/trap.cpp