Cataclysm BN: set_transform_iuse Class Reference
set_transform_iuse Class Reference
This is a iuse_transform that changes a set of items with a specific flag.
#include <iuse_actor.h>
Public Member Functions
set_transform_iuse (const std::string &type="set_transform")
~set_transform_iuse () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_transform
iuse_transform (const std::string &type="transform")
~iuse_transform () override=default
ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const override
std::string get_name () const override
Returns the translated name of the action.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
Public Attributes
bool turn_off
Whether the object turns things off or on.
std::string flag
Flag string so we know what the heck we're transforming.
int set_charges = 0
minimum charges (if any) required for transformation
translation set_charges_msg
displayed if item is in player possession with s replaced by item name
Public Attributes inherited from iuse_transform
translation msg_transform
displayed if player sees transformation with s replaced by item name
itype_id target
type of the resulting item
itype_id container
if set transform item to container and place new item (of type target) inside
int ammo_qty = -1
if zero or positive set remaining ammo of target to this (after transformation)
std::vector< int > random_ammo_qty
if this has values, set remaining ammo of target to one of them chosen at random (after transformation)
int countdown = 0
if positive set transformed item active and start countdown
itype_id ammo_type
if both this and ammo_qty are specified then set target to this specific ammo
bool active = false
used to set the active property of the transformed target
bool need_worn = false
does the item requires to be worn to be activable
bool need_wielding = false
does the item requires to be wielded to be activable
int moves = 0
subtracted from Creature::moves when transformation is successful
int need_fire = 0
minimum number of fire charges required (if any) for transformation
translation need_fire_msg
displayed if item is in player possession with s replaced by item name
int need_charges = 0
minimum charges (if any) required for transformation
translation need_charges_msg
displayed if item is in player possession with s replaced by item name
std::map< quality_id, int > qualities_needed
Tool qualities needed, e.g.
translation menu_text
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This is a iuse_transform that changes a set of items with a specific flag.
The player has to activate the item manually, it will then transform it and everything with the designated flag
Definition at line 317 of file iuse_actor.h.
Constructor & Destructor Documentation
set_transform_iuse()
set_transform_iuse::set_transform_iuse (const std::string & type = "set_transform") inline
Definition at line 336 of file iuse_actor.h.
: iuse_transform(type) {}
~set_transform_iuse()
set_transform_iuse::~set_transform_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > set_transform_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Reimplemented from iuse_transform.
Definition at line 894 of file iuse_actor.cpp.
{
    return std::make_unique<set_transform_iuse>( *this );
}
load()
void set_transform_iuse::load (const JsonObject & obj) override virtual
Reimplemented from iuse_transform.
Definition at line 899 of file iuse_actor.cpp.
{
    iuse_transform::load( obj );
    obj.read( "turn_off", turn_off );
    obj.read( "flag", flag );
    if( !obj.read( "set_charges_msg", set_charges_msg ) ) {
        set_charges_msg = to_translation( "The %s is empty!" );
    }
    if( !obj.read( "set_charges", set_charges ) ) {
        set_charges = 0;
    }
    set_charges = std::max( set_charges, 0 );
}
References flag, iuse_transform::load(), JsonObject::read(), set_charges, set_charges_msg, to_translation(), and turn_off.
use()
int set_transform_iuse::use (player & p, item & it, bool t, const tripoint & pos) const override virtual
Reimplemented from iuse_transform.
Definition at line 914 of file iuse_actor.cpp.
{
    if( t ) {
        return 0; // invoked from active item processing, do nothing.
    }
    const bool possess = p.has_item( it ) ||
                         ( it.has_flag( "ALLOWS_REMOTE_USE" ) && square_dist( p.pos(), pos ) == 1 );
    if( set_charges ) {
        if( it.is_power_armor() && character_funcs::can_interface_armor( p ) ) {
            if( !p.has_power() ) {
                if( possess ) {
                    p.add_msg_if_player( m_info, set_charges_msg, it.tname() );
                }
                return 0;
            }
        } else if( it.units_remaining( p ) < set_charges ) {
            if( possess ) {
                p.add_msg_if_player( m_info, set_charges_msg, it.tname() );
            }
            return 0;
        }
    }
    iuse_transform::use( p, it, t, pos );
    for( auto &elem : p.worn ) {
        if( elem.has_flag( flag ) && elem.active == turn_off ) {
            if( elem.type->can_use( "set_transformed" ) ) {
                const set_transformed_iuse *actor = dynamic_cast<const set_transformed_iuse *>
                                                    ( elem.get_use( "set_transformed" )->get_actor_ptr() );
                if( actor == nullptr ) {
                    debugmsg( "iuse_actor type descriptor and actual type mismatch" );
                } else {
                    actor->bypass( p, elem, t, pos );
                }
            } else {
                debugmsg( "Expected set_transformed function" );
            }
        }
    }
    return 0;
}
References player::add_msg_if_player(), set_transformed_iuse::bypass(), character_funcs::can_interface_armor(), debugmsg, flag, item::has_flag(), visitable< T >::has_item(), Character::has_power(), item::is_power_armor(), m_info, Character::pos(), set_charges, set_charges_msg, square_dist(), item::tname(), turn_off, item::units_remaining(), iuse_transform::use(), and Character::worn.
Member Data Documentation
flag
std::string set_transform_iuse::flag
Flag string so we know what the heck we're transforming.
Definition at line 328 of file iuse_actor.h.
Referenced by load(), item::process_tool(), and use().
set_charges
int set_transform_iuse::set_charges = 0
minimum charges (if any) required for transformation
Definition at line 331 of file iuse_actor.h.
Referenced by load(), and use().
set_charges_msg
translation set_transform_iuse::set_charges_msg
displayed if item is in player possession with s replaced by item name
Definition at line 334 of file iuse_actor.h.
Referenced by load(), and use().
turn_off
bool set_transform_iuse::turn_off
Whether the object turns things off or on.
Definition at line 323 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp