Cataclysm BN: detail::arg_formatter_base< OutputIt, Char, ErrorHandler > Class Template Reference
detail::arg_formatter_base< OutputIt, Char, ErrorHandler > Class Template Reference
#include <fmtlib_format.h>
Classes
struct char_spec_handler
struct cstring_spec_handler
Public Types
using iterator = OutputIt
using char_type = Char
using format_specs = basic_format_specs< Char >
Public Member Functions
arg_formatter_base (OutputIt out, format_specs *s, locale_ref loc)
iterator operator() (monostate)
template<typename T , FMT_ENABLE_IF(is_integral< T >::value) >
FMT_INLINE iterator operator() (T value)
iterator operator() (Char value)
iterator operator() (bool value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
iterator operator() (T value)
iterator operator() (const Char *value)
iterator operator() (basic_string_view< Char > value)
iterator operator() (const void *value)
Protected Member Functions
iterator out ()
format_specs * specs ()
void write (bool value)
void write (const Char *value)
Private Types
using reserve_iterator = remove_reference_t< decltype(detail::reserve(std::declval< iterator & >(), 0))>
Private Member Functions
auto reserve (size_t n) -> decltype(detail::reserve(out_, n))
template<typename T >
void write_int (T value, const format_specs &spec)
void write (char value)
template<typename Ch , FMT_ENABLE_IF(std::is_same< Ch, Char >::value) >
void write (Ch value)
void write (string_view value)
void write (wstring_view value)
template<typename Ch >
void write (const Ch *s, size_t size, const format_specs &specs)
template<typename Ch >
void write (basic_string_view< Ch > s, const format_specs &specs={})
void write_pointer (const void *p)
Private Attributes
iterator out_
locale_ref locale_
format_specs * specs_
Detailed Description
template<typename OutputIt, typename Char, typename ErrorHandler = error_handler>
class detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
Definition at line 2437 of file fmtlib_format.h.
Member Typedef Documentation
char_type
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> using detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::char_type = Char
Definition at line 2441 of file fmtlib_format.h.
format_specs
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> using detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::format_specs = basic_format_specs<Char>
Definition at line 2442 of file fmtlib_format.h.
iterator
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> using detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::iterator = OutputIt
Definition at line 2440 of file fmtlib_format.h.
reserve_iterator
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> using detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::reserve_iterator = remove_reference_t<decltype(detail::reserve(std::declval<iterator &>(), 0))> private
Definition at line 2455 of file fmtlib_format.h.
Constructor & Destructor Documentation
arg_formatter_base()
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::arg_formatter_base (OutputIt out, format_specs * s, locale_ref loc) inline
Definition at line 2566 of file fmtlib_format.h.
            : out_( out ), locale_( loc ), specs_( s ) {}
Member Function Documentation
operator()() [1/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (basic_string_view< Char > value) inline
Definition at line 2617 of file fmtlib_format.h.
{
            if( specs_ ) {
                check_string_type_spec( specs_->type, error_handler() );
                write( value, *specs_ );
            } else {
                write( value );
            }
            return out_;
        }
References detail::check_string_type_spec(), basic_format_specs< Char >::type, and detail::write().
operator()() [2/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (bool value) inline
Definition at line 2590 of file fmtlib_format.h.
{
            if( specs_ && specs_->type ) {
                return ( *this )( value ? 1 : 0 );
            }
            write( value != 0 );
            return out_;
        }
References basic_format_specs< Char >::type, and detail::write().
operator()() [3/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (Char value) inline
Definition at line 2584 of file fmtlib_format.h.
{
            handle_char_specs( specs_,
                               char_spec_handler( *this, static_cast<Char>( value ) ) );
            return out_;
        }
References detail::handle_char_specs().
operator()() [4/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (const Char * value) inline
Definition at line 2609 of file fmtlib_format.h.
{
            if( !specs_ ) {
                return write( value ), out_;
            }
            handle_cstring_type_spec( specs_->type, cstring_spec_handler( *this, value ) );
            return out_;
        }
References detail::handle_cstring_type_spec(), basic_format_specs< Char >::type, and detail::write().
operator()() [5/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (const void * value) inline
Definition at line 2627 of file fmtlib_format.h.
{
            if( specs_ ) {
                check_pointer_type_spec( specs_->type, error_handler() );
            }
            write_pointer( value );
            return out_;
        }
References detail::check_pointer_type_spec(), and basic_format_specs< Char >::type.
operator()() [6/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (monostate) inline
Definition at line 2569 of file fmtlib_format.h.
{
            FMT_ASSERT( false, "invalid argument type" );
            return out_;
        }
References FMT_ASSERT.
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
operator()() [7/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> template<typename T , FMT_ENABLE_IF(is_integral< T >::value) > FMT_INLINE iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (T value) inline
Definition at line 2575 of file fmtlib_format.h.
{
            if( specs_ ) {
                write_int( value, *specs_ );
            } else {
                out_ = detail::write<Char>( out_, value );
            }
            return out_;
        }
References detail::write_int().
operator()() [8/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator() (T value) inline
Definition at line 2599 of file fmtlib_format.h.
{
            auto specs = specs_ ? *specs_ : format_specs();
            if( const_check( is_supported_floating_point( value ) ) ) {
                out_ = detail::write( out_, value, specs, locale_ );
            } else {
                FMT_ASSERT( false, "unsupported float argument type" );
            }
            return out_;
        }
References detail::const_check(), FMT_ASSERT, detail::is_supported_floating_point(), and detail::write().
out()
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out () inline protected
Definition at line 2540 of file fmtlib_format.h.
                       {
            return out_;
        }
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
reserve()
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> auto detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::reserve (size_t n) -> decltype(detail::reserve(out_, n)) inline private
Definition at line 2451 of file fmtlib_format.h.
{
            return detail::reserve( out_, n );
        }
References detail::reserve().
specs()
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> format_specs * detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs () inline protected
Definition at line 2543 of file fmtlib_format.h.
{
            return specs_;
        }
Referenced by printf_arg_formatter< OutputIt, Char >::operator()(), and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
write() [1/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> template<typename Ch > void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (basic_string_view< Ch > s, const format_specs & specs = {}) inline private
Definition at line 2496 of file fmtlib_format.h.
                                                                         {} ) {
            out_ = detail::write( out_, s, specs );
        }
write() [2/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (bool value) inline protected
Definition at line 2547 of file fmtlib_format.h.
{
            if( specs_ ) {
                write( string_view( value ? "true" : "false" ), *specs_ );
            } else {
                out_ = detail::write<Char>( out_, value );
            }
        }
References detail::write().
write() [3/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> template<typename Ch , FMT_ENABLE_IF(std::is_same< Ch, Char >::value) > void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (Ch value) inline private
Definition at line 2471 of file fmtlib_format.h.
{
            out_ = detail::write<Char>( out_, value );
        }
write() [4/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (char value) inline private
Definition at line 2465 of file fmtlib_format.h.
{
            auto &&it = reserve( 1 );
            *it++ = value;
        }
References detail::reserve().
Referenced by printf_arg_formatter< OutputIt, Char >::operator()(), and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
write() [5/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> template<typename Ch > void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (const Ch * s, size_t size, const format_specs & specs) inline private
Definition at line 2486 of file fmtlib_format.h.
{
            auto width = specs.width != 0
                         ? count_code_points( basic_string_view<Ch>( s, size ) )
                         : 0;
            out_ = write_padded( out_, specs, size, width, [ = ]( reserve_iterator it ) {
                return copy_str<Char>( s, s + size, it );
            } );
        }
References detail::count_code_points(), om_direction::size, basic_format_specs< Char >::width, and detail::write_padded().
write() [6/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (const Char * value) inline protected
Definition at line 2555 of file fmtlib_format.h.
{
            if( !value ) {
                FMT_THROW( format_error( "string pointer is null" ) );
            } else {
                auto length = std::char_traits<char_type>::length( value );
                basic_string_view<char_type> sv( value, length );
                specs_ ? write( sv, *specs_ ) : write( sv );
            }
        }
References FMT_THROW, and detail::write().
write() [7/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (string_view value) inline private
Definition at line 2475 of file fmtlib_format.h.
{
            auto &&it = reserve( value.size() );
            it = copy_str<Char>( value.begin(), value.end(), it );
        }
References detail::reserve().
write() [8/8]
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write (wstring_view value) inline private
Definition at line 2479 of file fmtlib_format.h.
{
            static_assert( std::is_same<Char, wchar_t>::value, "" );
            auto &&it = reserve( value.size() );
            it = std::copy( value.begin(), value.end(), it );
        }
References detail::reserve().
write_int()
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> template<typename T > void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write_int (T value, const format_specs & spec) inline private
Definition at line 2458 of file fmtlib_format.h.
{
            using uint_type = uint32_or_64_or_128_t<T>;
            int_writer<iterator, Char, uint_type> w( out_, locale_, value, spec );
            handle_int_type_spec( spec.type, w );
            out_ = w.out;
        }
References detail::handle_int_type_spec(), detail::int_writer< OutputIt, Char, UInt >::out, basic_format_specs< Char >::type, and detail::uint_type.
write_pointer()
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> void detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write_pointer (const void * p) inline private
Definition at line 2500 of file fmtlib_format.h.
{
            out_ = write_ptr<char_type>( out_, to_uintptr( p ), specs_ );
        }
References detail::to_uintptr().
Member Data Documentation
locale_
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> locale_ref detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::locale_ private
Definition at line 2446 of file fmtlib_format.h.
out_
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> iterator detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out_ private
Definition at line 2445 of file fmtlib_format.h.
specs_
template<typename OutputIt , typename Char , typename ErrorHandler = error_handler> format_specs* detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs_ private
Definition at line 2447 of file fmtlib_format.h.
The documentation for this class was generated from the following file:
src/fmtlib_format.h