Cataclysm BN: solar_tile Class Reference
solar_tile Class Reference
#include <active_tile_data_def.h>
Public Member Functions
void update_internal (time_point to, const tripoint_abs_ms &p, distribution_grid &grid) override
active_tile_data * clone () const override
const std::string & get_type () const override
void store (JsonOut &jsout) const override
void load (JsonObject &jo) override
Public Member Functions inherited from active_tile_data
void update (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)
time_point get_last_updated ()
void set_last_updated (time_point t)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
virtual ~active_tile_data ()
Public Attributes
int power
Additional Inherited Members
Static Public Member Functions inherited from active_tile_data
static active_tile_data * create (const std::string &id)
Detailed Description
Definition at line 64 of file active_tile_data_def.h.
Member Function Documentation
clone()
active_tile_data * solar_tile::clone () const override virtual
Implements active_tile_data.
Definition at line 138 of file active_tile_data.cpp.
{
    return new solar_tile( *this );
}
get_type()
const std::string & solar_tile::get_type () const override virtual
Implements active_tile_data.
Definition at line 143 of file active_tile_data.cpp.
{
    static const std::string type( "solar" );
    return type;
}
References type.
load()
void solar_tile::load (JsonObject & jo) override virtual
Implements active_tile_data.
Definition at line 154 of file active_tile_data.cpp.
{
    // Can't use generic_factory because we don't have unique ids
    jo.read( "power", power );
    // TODO: Remove all of this, it's a hack around a mistake
    int dummy;
    jo.read( "stored_energy", dummy, false );
    jo.read( "max_energy", dummy, false );
}
References power, and JsonObject::read().
store()
void solar_tile::store (JsonOut & jsout) const override virtual
Implements active_tile_data.
Definition at line 149 of file active_tile_data.cpp.
{
    jsout.member( "power", power );
}
References JsonOut::member(), and power.
update_internal()
void solar_tile::update_internal (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) override virtual
Parameters
to the time to update to
p absolute map coordinates (map::getabs) of the tile being updated
grid distribution grid being updated, containing the tile being updated
Implements active_tile_data.
Definition at line 113 of file active_tile_data.cpp.
{
    constexpr time_point zero = time_point::from_turn( 0 );
    constexpr time_duration tick_length = 10_minutes;
    constexpr int tick_turns = to_turns<int>( tick_length );
    time_duration till_then = get_last_updated() - zero;
    time_duration till_now = to - zero;
    // This is just for rounding to nearest tick
    time_duration ticks_then = till_then / tick_turns;
    time_duration ticks_now = till_now / tick_turns;
    // This is to cut down on sum_conditions
    if( ticks_then == ticks_now ) {
        return;
    }
    time_duration rounded_then = ticks_then * tick_turns;
    time_duration rounded_now = ticks_now * tick_turns;
    // TODO: Use something that doesn't calc a ton of worthless crap
    float sunlight = sum_conditions( zero + rounded_then, zero + rounded_now,
                                     p.raw() ).sunlight / default_daylight_level();
    // int64 because we can have years in here
    std::int64_t produced = power * static_cast<std::int64_t>( sunlight ) / 1000;
    grid.mod_resource( static_cast<int>( std::min( static_cast<std::int64_t>( INT_MAX ), produced ) ) );
}
References default_daylight_level(), time_point::from_turn(), active_tile_data::get_last_updated(), distribution_grid::mod_resource(), power, coords::coord_point< Point, Origin, Scale >::raw(), sum_conditions(), sunlight(), and weather_sum::sunlight.
Member Data Documentation
power
int solar_tile::power
Definition at line 68 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
The documentation for this class was generated from the following files:
src/active_tile_data_def.h
src/active_tile_data.cpp