Cataclysm BN: behavior::node_t Class Reference
behavior::node_t Class Reference
#include <behavior.h>
Public Member Functions
node_t ()
behavior_return tick (const oracle_t *subject) const
std::string goal () const
void set_strategy (const strategy_t *new_strategy)
void set_predicate (std::function< status_t(const oracle_t *)> new_predicate)
void set_goal (const std::string &new_goal)
void add_child (const node_t *new_child)
void load (const JsonObject &jo, const std::string &src)
void check () const
Public Attributes
string_id< node_t > id
bool was_loaded = false
Private Attributes
std::vector< const node_t * > children
const strategy_t * strategy
std::function< status_t(const oracle_t *)> predicate
std::string _goal
Detailed Description
Definition at line 55 of file behavior.h.
Constructor & Destructor Documentation
node_t()
node_t::node_t ()
Definition at line 97 of file behavior.cpp.
{
    predicate = &return_running;
}
References predicate, and behavior::return_running().
Member Function Documentation
add_child()
void node_t::add_child (const node_t * new_child)
Definition at line 29 of file behavior.cpp.
{
    children.push_back( new_child );
}
References children.
Referenced by mtype::add_goal().
check()
void node_t::check () const
Definition at line 136 of file behavior.cpp.
{
    // Invariants
    if( children.empty() ) {
        if( _goal.empty() ) {
            debugmsg( "Behavior %s must have either children or a goal.",
                      id.str() );
        }
    } else {
        if( strategy == nullptr ) {
            debugmsg( "Behavior %s has children but no strategy.", id.str() );
        }
        if( !_goal.empty() ) {
            debugmsg( "Behavior %s has both children and a goal.", id.str() );
        }
    }
}
References _goal, children, debugmsg, and strategy.
goal()
std::string node_t::goal () const
Definition at line 50 of file behavior.cpp.
{
    return _goal;
}
References _goal.
Referenced by behavior::tree::goal().
load()
void node_t::load (const JsonObject & jo, const std::string & src)
Definition at line 102 of file behavior.cpp.
{
    // We don't initialize the node unless it has no children (opportunistic optimization).
    // Instead we initialize a parallel struct that holds the labels until finalization.
    if( jo.has_array( "children" ) ) {
        temp_node_data.emplace_back();
        node_data &new_data = temp_node_data.back();
        new_data.id = id;
        optional( jo, was_loaded, "children", new_data.children );
    }
    if( jo.has_string( "strategy" ) ) {
        std::unordered_map<std::string, const strategy_t *>::iterator new_strategy =
            behavior::strategy_map.find( jo.get_string( "strategy" ) );
        if( new_strategy != strategy_map.end() ) {
            strategy = new_strategy->second;
        } else {
            debugmsg( "While loading %s, failed to find strategy %s.",
                      id.str(), jo.get_string( "strategy" ) );
            jo.throw_error( "Invalid strategy in behavior." );
        }
    }
    if( jo.has_string( "predicate" ) ) {
        auto new_predicate = predicate_map.find( jo.get_string( "predicate" ) );
        if( new_predicate != predicate_map.end() ) {
            predicate = new_predicate->second;
        } else {
            debugmsg( "While loading %s, failed to find predicate %s.",
                      id.str(), jo.get_string( "predicate" ) );
            jo.throw_error( "Invalid strategy in behavior." );
        }
    }
    optional( jo, was_loaded, "goal", _goal );
}
References _goal, node_data::children, debugmsg, JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), node_data::id, id, optional(), predicate, behavior::predicate_map, strategy, behavior::strategy_map, anonymous_namespace{behavior.cpp}::temp_node_data, JsonObject::throw_error(), and was_loaded.
set_goal()
void node_t::set_goal (const std::string & new_goal)
Definition at line 25 of file behavior.cpp.
{
    _goal = new_goal;
}
References _goal.
set_predicate()
void node_t::set_predicate (std::function< status_t(const oracle_t *)> new_predicate)
Definition at line 21 of file behavior.cpp.
{
    predicate = new_predicate;
}
References predicate.
set_strategy()
void node_t::set_strategy (const strategy_t * new_strategy)
Definition at line 17 of file behavior.cpp.
{
    strategy = new_strategy;
}
References strategy.
Referenced by mtype::set_strategy().
tick()
behavior_return node_t::tick (const oracle_t * subject) const
Definition at line 34 of file behavior.cpp.
{
    assert( predicate );
    if( children.empty() ) {
        return { predicate( subject ), this };
    } else {
        assert( strategy != nullptr );
        status_t result = predicate( subject );
        if( result == running ) {
            return strategy->evaluate( subject, children );
        } else {
            return { result, nullptr };
        }
    }
}
References children, behavior::strategy_t::evaluate(), predicate, behavior::running, and strategy.
Referenced by behavior::tree::tick().
Member Data Documentation
_goal
std::string behavior::node_t::_goal private
Definition at line 79 of file behavior.h.
Referenced by check(), goal(), load(), and set_goal().
children
std::vector<const node_t *> behavior::node_t::children private
Definition at line 75 of file behavior.h.
Referenced by add_child(), check(), and tick().
id
string_id<node_t> behavior::node_t::id
Definition at line 72 of file behavior.h.
Referenced by load().
predicate
std::function<status_t(const oracle_t *)> behavior::node_t::predicate private
Definition at line 77 of file behavior.h.
Referenced by load(), node_t(), set_predicate(), and tick().
strategy
const strategy_t* behavior::node_t::strategy private
Definition at line 76 of file behavior.h.
Referenced by check(), load(), set_strategy(), and tick().
was_loaded
bool behavior::node_t::was_loaded = false
Definition at line 73 of file behavior.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/behavior.h
src/behavior.cpp