Cataclysm BN: faction Class Reference
faction Class Reference
#include <faction.h>
Public Member Functions
faction ()=default
faction (const faction_template &templ)
void deserialize (JsonIn &jsin)
void serialize (JsonOut &json) const
void faction_display (const catacurses::window &fac_w, int width) const
std::string describe () const
std::vector< std::string > epilogue () const
std::string food_supply_text ()
nc_color food_supply_color ()
bool has_relationship (const faction_id &guy_id, npc_factions::relationship flag) const
void add_to_membership (const character_id &guy_id, const std::string &guy_name, bool known)
void remove_member (const character_id &guy_id)
Public Member Functions inherited from faction_template
faction_template (const faction_template &)=default
faction_template & operator= (const faction_template &)=default
Public Attributes
std::vector< int > opinion_of
bool validated = false
std::map< character_id, std::pair< std::string, bool > > members
Public Attributes inherited from faction_template
std::string name
int likes_u
int respects_u
bool known_by_u
faction_id id
std::string desc
int size
int power
int food_supply
int wealth
bool lone_wolf_faction
itype_id currency
std::map< std::string, std::bitset< npc_factions::rel_types > > relations
std::string mon_faction
std::set< std::tuple< int, int, snippet_id > > epilogue_data
Additional Inherited Members
Static Public Member Functions inherited from faction_template
static void load (const JsonObject &jsobj)
static void check_consistency ()
static void reset ()
Protected Member Functions inherited from faction_template
faction_template ()
void load_relations (const JsonObject &jsobj)
Detailed Description
Definition at line 95 of file faction.h.
Constructor & Destructor Documentation
faction() [1/2]
faction::faction () default
faction() [2/2]
faction::faction (const faction_template & templ)
Definition at line 54 of file faction.cpp.
{
    id = templ.id;
    // first init *all* members, than copy those from the template
    static_cast<faction_template &>( *this ) = templ;
}
References faction_template::id.
Member Function Documentation
add_to_membership()
void faction::add_to_membership (const character_id & guy_id, const std::string & guy_name, bool known)
Definition at line 139 of file faction.cpp.
{
    members[guy_id] = std::make_pair( guy_name, known );
}
References members.
Referenced by npc::set_fac(), and npc::set_known_to_u().
describe()
std::string faction::describe () const
Definition at line 122 of file faction.cpp.
{
    std::string ret = _( desc );
    return ret;
}
References _, faction_template::desc, and cata::hash64_detail::ret.
deserialize()
void faction::deserialize (JsonIn & jsin)
Definition at line 2953 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "id", id );
    jo.read( "name", name );
    jo.read( "likes_u", likes_u );
    jo.read( "respects_u", respects_u );
    jo.read( "known_by_u", known_by_u );
    jo.read( "size", size );
    jo.read( "power", power );
    if( !jo.read( "food_supply", food_supply ) ) {
        food_supply = 100;
    }
    if( !jo.read( "wealth", wealth ) ) {
        wealth = 100;
    }
    if( jo.has_array( "opinion_of" ) ) {
        opinion_of = jo.get_int_array( "opinion_of" );
    }
    load_relations( jo );
}
References JsonObject::allow_omitted_members(), JsonObject::get_int_array(), JsonIn::get_object(), JsonObject::has_array(), om_direction::name(), JsonObject::read(), and om_direction::size.
epilogue()
std::vector< std::string > faction::epilogue () const
Definition at line 128 of file faction.cpp.
{
    std::vector<std::string> ret;
    for( const std::tuple<int, int, snippet_id> &epilogue_entry : epilogue_data ) {
        if( power >= std::get<0>( epilogue_entry ) && power < std::get<1>( epilogue_entry ) ) {
            ret.emplace_back( std::get<2>( epilogue_entry )->translated() );
        }
    }
    return ret;
}
References faction_template::epilogue_data, faction_template::power, and cata::hash64_detail::ret.
faction_display()
void faction::faction_display (const catacurses::window & fac_w, int width) const
Definition at line 486 of file faction.cpp.
{
    int y = 2;
    mvwprintz( fac_w, point( width, ++y ), c_light_gray, _( "Attitude to you:           %s" ),
               fac_ranking_text( likes_u ) );
    fold_and_print( fac_w, point( width, ++y ), getmaxx( fac_w ) - width - 2, c_light_gray, _( desc ) );
}
References _, c_light_gray, faction_template::desc, fac_ranking_text(), fold_and_print(), catacurses::getmaxx(), faction_template::likes_u, and mvwprintz().
Referenced by faction_manager::display().
food_supply_color()
nc_color faction::food_supply_color ()
Definition at line 311 of file faction.cpp.
{
    int val = food_supply / ( size * 288 );
    if( val >= 30 ) {
        return c_green;
    } else if( val >= 14 ) {
        return c_light_green;
    } else if( val >= 6 ) {
        return c_yellow;
    } else if( val >= 3 ) {
        return c_light_red;
    } else {
        return c_red;
    }
}
References c_green, c_light_green, c_light_red, c_red, c_yellow, faction_template::food_supply, and faction_template::size.
Referenced by basecamp::faction_display().
food_supply_text()
std::string faction::food_supply_text ()
Definition at line 292 of file faction.cpp.
{
    //Convert to how many days you can support the population
    int val = food_supply / ( size * 288 );
    if( val >= 30 ) {
        return pgettext( "Faction food", "Overflowing" );
    }
    if( val >= 14 ) {
        return pgettext( "Faction food", "Well-Stocked" );
    }
    if( val >= 6 ) {
        return pgettext( "Faction food", "Scrapping By" );
    }
    if( val >= 3 ) {
        return pgettext( "Faction food", "Malnourished" );
    }
    return pgettext( "Faction food", "Starving" );
}
References faction_template::food_supply, pgettext(), and faction_template::size.
Referenced by basecamp::faction_display().
has_relationship()
bool faction::has_relationship (const faction_id & guy_id, npc_factions::relationship flag) const
Definition at line 327 of file faction.cpp.
{
    for( const auto &rel_data : relations ) {
        if( rel_data.first == guy_id.c_str() ) {
            return rel_data.second.test( flag );
        }
    }
    return false;
}
References string_id< T >::c_str(), and faction_template::relations.
Referenced by npc::has_faction_relationship().
remove_member()
void faction::remove_member (const character_id & guy_id)
Definition at line 145 of file faction.cpp.
{
    for( auto it = members.cbegin(), next_it = it; it != members.cend(); it = next_it ) {
        ++next_it;
        if( guy_id == it->first ) {
            members.erase( it );
            break;
        }
    }
    if( members.empty() ) {
        for( const faction_template &elem : npc_factions::all_templates ) {
            // This is a templated base faction - don't delete it, just leave it as zero members for now.
            // Only want to delete dynamically created factions.
            if( elem.id == id ) {
                return;
            }
        }
        g->faction_manager_ptr->remove_faction( id );
    }
}
References npc_factions::all_templates, g, and members.
Referenced by npc::die(), and npc::set_fac().
serialize()
void faction::serialize (JsonOut & json) const
Definition at line 2977 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "id", id );
    json.member( "name", name );
    json.member( "likes_u", likes_u );
    json.member( "respects_u", respects_u );
    json.member( "known_by_u", known_by_u );
    json.member( "size", size );
    json.member( "power", power );
    json.member( "food_supply", food_supply );
    json.member( "wealth", wealth );
    json.member( "opinion_of", opinion_of );
    json.member( "relations" );
    json.start_object();
    for( const auto &rel_data : relations ) {
        json.member( rel_data.first );
        json.start_object();
        for( const auto &rel_flag : npc_factions::relation_strs ) {
            json.member( rel_flag.first, rel_data.second.test( rel_flag.second ) );
        }
        json.end_object();
    }
    json.end_object();
    json.end_object();
}
References JsonOut::end_object(), JsonOut::member(), om_direction::name(), npc_factions::relation_strs, om_direction::size, and JsonOut::start_object().
Member Data Documentation
members
std::map<character_id, std::pair<std::string, bool> > faction::members
Definition at line 116 of file faction.h.
Referenced by add_to_membership(), npc::die(), and remove_member().
opinion_of
std::vector<int> faction::opinion_of
Definition at line 114 of file faction.h.
validated
bool faction::validated = false
Definition at line 115 of file faction.h.
The documentation for this class was generated from the following files:
src/faction.h
src/faction.cpp
src/savegame_json.cpp