Cataclysm BN: character_id Class Reference
character_id Class Reference
#include <character_id.h>
Public Member Functions
character_id ()
character_id (int i)
bool is_valid () const
int get_value () const
character_id & operator++ ()
void serialize (JsonOut &) const
void deserialize (JsonIn &)
Private Attributes
int value
Friends
bool operator== (character_id l, character_id r)
bool operator!= (character_id l, character_id r)
bool operator< (character_id l, character_id r)
std::ostream & operator<< (std::ostream &o, character_id id)
Detailed Description
Definition at line 11 of file character_id.h.
Constructor & Destructor Documentation
character_id() [1/2]
character_id::character_id () inline
Definition at line 14 of file character_id.h.
: value(-1) {}
character_id() [2/2]
character_id::character_id (int i) inline explicit
Definition at line 16 of file character_id.h.
                                       : value( i ) {
        }
Member Function Documentation
deserialize()
void character_id::deserialize (JsonIn & jsin)
Definition at line 327 of file savegame_json.cpp.
{
    value = jsin.get_int();
}
References JsonIn::get_int(), and value.
Referenced by game::unserialize_master().
get_value()
int character_id::get_value () const inline
Definition at line 23 of file character_id.h.
{
            return value;
        }
References value.
Referenced by item::already_used_by_player(), mission::assign(), mission_end::deposit_box(), avatar::do_read(), item_location::impl::item_on_person::ensure_who_unpacked(), item::get_remaining_chapters(), mission_start::kill_horde_master(), item::mark_as_used_by_player(), item::mark_chapter_as_read(), iuse::note_bionics(), mission_start::place_deposit_box(), mission_start::place_dog(), mission_start::place_npc_software(), avatar::read(), Character::setID(), npc::start_read(), talk_function::start_training(), cata_variant_detail::convert< cata_variant_type::character_id >::to_string(), and mission::wrap_up().
is_valid()
bool character_id::is_valid () const inline
Definition at line 19 of file character_id.h.
{
            return value > 0;
        }
References value.
Referenced by mission::assign(), vehicle_part::crew(), monster::find_dragged_foe(), mission::is_assigned(), mission::is_complete(), player::load(), game::load(), item::on_pickup(), mission::process(), mission::set_player_id_legacy_0c(), and Character::setID().
operator++()
character_id & character_id::operator++ () inline
Definition at line 27 of file character_id.h.
{
            ++value;
            return *this;
        }
References value.
serialize()
void character_id::serialize (JsonOut & jsout) const
Definition at line 322 of file savegame_json.cpp.
{
    jsout.write( value );
}
References value, and JsonOut::write().
Friends And Related Function Documentation
operator!=
bool operator!= (character_id l, character_id r) friend
Definition at line 39 of file character_id.h.
{
            return l.get_value() != r.get_value();
        }
operator<
bool operator< (character_id l, character_id r) friend
Definition at line 43 of file character_id.h.
{
            return l.get_value() < r.get_value();
        }
operator<<
std::ostream & operator<< (std::ostream & o, character_id id) friend
Definition at line 47 of file character_id.h.
{
            return o << id.get_value();
        }
operator==
bool operator== (character_id l, character_id r) friend
Definition at line 35 of file character_id.h.
{
            return l.get_value() == r.get_value();
        }
Member Data Documentation
value
int character_id::value private
Definition at line 51 of file character_id.h.
Referenced by deserialize(), get_value(), is_valid(), operator++(), and serialize().
The documentation for this class was generated from the following files:
src/character_id.h
src/savegame_json.cpp