Cataclysm BN: detail::arg_formatter< OutputIt, Char > Class Template Reference
detail::arg_formatter< OutputIt, Char > Class Template Reference
The default argument formatter.
#include <fmtlib_format.h>
Public Types
using iterator = typename base::iterator
using format_specs = typename base::format_specs
Public Types inherited from detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
using iterator = OutputIt
using char_type = Char
using format_specs = basic_format_specs< Char >
Public Member Functions
arg_formatter (context_type &ctx, basic_format_parse_context< char_type > *parse_ctx=nullptr, format_specs *specs=nullptr, const Char *ptr=nullptr)
\rst Constructs an argument formatter object.
iterator operator() (typename basic_format_arg< context_type >::handle handle)
Formats an argument of a user-defined type.
Public Member Functions inherited from detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
arg_formatter_base (OutputIt out, format_specs *s, locale_ref loc)
iterator operator() (monostate)
template<typename T , FMT_ENABLE_IF(is_integral< T >::value) >
FMT_INLINE iterator operator() (T value)
iterator operator() (Char value)
iterator operator() (bool value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
iterator operator() (T value)
iterator operator() (const Char *value)
iterator operator() (basic_string_view< Char > value)
iterator operator() (const void *value)
Private Types
using char_type = Char
using base = arg_formatter_base< OutputIt, Char >
using context_type = basic_format_context< OutputIt, Char >
Private Attributes
context_type & ctx_
basic_format_parse_context< char_type > * parse_ctx_
const Char * ptr_
Additional Inherited Members
Protected Member Functions inherited from detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
iterator out ()
format_specs * specs ()
void write (bool value)
void write (const Char *value)
Detailed Description
template<typename OutputIt, typename Char>
class detail::arg_formatter< OutputIt, Char >
The default argument formatter.
Definition at line 2638 of file fmtlib_format.h.
Member Typedef Documentation
base
template<typename OutputIt , typename Char > using detail::arg_formatter< OutputIt, Char >::base = arg_formatter_base<OutputIt, Char> private
Definition at line 2642 of file fmtlib_format.h.
char_type
template<typename OutputIt , typename Char > using detail::arg_formatter< OutputIt, Char >::char_type = Char private
Definition at line 2641 of file fmtlib_format.h.
context_type
template<typename OutputIt , typename Char > using detail::arg_formatter< OutputIt, Char >::context_type = basic_format_context<OutputIt, Char> private
Definition at line 2643 of file fmtlib_format.h.
format_specs
template<typename OutputIt , typename Char > using detail::arg_formatter< OutputIt, Char >::format_specs = typename base::format_specs
Definition at line 2651 of file fmtlib_format.h.
iterator
template<typename OutputIt , typename Char > using detail::arg_formatter< OutputIt, Char >::iterator = typename base::iterator
Definition at line 2650 of file fmtlib_format.h.
Constructor & Destructor Documentation
arg_formatter()
template<typename OutputIt , typename Char > detail::arg_formatter< OutputIt, Char >::arg_formatter (context_type & ctx, basic_format_parse_context< char_type > * parse_ctx = nullptr, format_specs * specs = nullptr, const Char * ptr = nullptr) inline explicit
\rst Constructs an argument formatter object.
ctx* is a reference to the formatting context, specs* contains format specifier information for standard argument types. \endrst
Definition at line 2660 of file fmtlib_format.h.
            : base( ctx.out(), specs, ctx.locale() ),
              ctx_( ctx ),
              parse_ctx_( parse_ctx ),
              ptr_( ptr ) {}
Member Function Documentation
operator()()
template<typename OutputIt , typename Char > iterator detail::arg_formatter< OutputIt, Char >::operator() (typename basic_format_arg< context_type >::handle handle) inline
Formats an argument of a user-defined type.
Definition at line 2672 of file fmtlib_format.h.
{
            if( ptr_ ) {
                advance_to( *parse_ctx_, ptr_ );
            }
            handle.format( *parse_ctx_, ctx_ );
            return ctx_.out();
        }
References advance_to(), basic_format_arg< Context >::handle::format(), and basic_format_context< OutputIt, Char >::out().
Member Data Documentation
ctx_
template<typename OutputIt , typename Char > context_type& detail::arg_formatter< OutputIt, Char >::ctx_ private
Definition at line 2645 of file fmtlib_format.h.
parse_ctx_
template<typename OutputIt , typename Char > basic_format_parse_context<char_type>* detail::arg_formatter< OutputIt, Char >::parse_ctx_ private
Definition at line 2646 of file fmtlib_format.h.
ptr_
template<typename OutputIt , typename Char > const Char* detail::arg_formatter< OutputIt, Char >::ptr_ private
Definition at line 2647 of file fmtlib_format.h.
The documentation for this class was generated from the following file:
src/fmtlib_format.h