Cataclysm BN: optional_vpart_position Class Reference
optional_vpart_position Class Reference
Simple wrapper to forward functions that may return a cata::optional to vpart_position.
#include <vpart_position.h>
Public Member Functions
optional_vpart_position (cata::optional< vpart_position > p)
cata::optional< std::string > get_label () const
cata::optional< vpart_reference > part_with_feature (const std::string &f, bool unbroken) const
cata::optional< vpart_reference > part_with_feature (vpart_bitflags f, bool unbroken) const
cata::optional< vpart_reference > obstacle_at_part () const
cata::optional< vpart_reference > part_displayed () const
Public Member Functions inherited from cata::optional< vpart_position >
constexpr optional () noexcept
constexpr optional (const nullopt_t) noexcept
optional (const optional &other)
optional (optional &&other)
optional (in_place_t, Args &&... args)
optional (in_place_t, std::initializer_list< U > ilist, Args &&... args)
optional (U &&t)
optional (U &&t)
~optional ()
constexpr const vpart_position * operator-> () const
vpart_position * operator-> ()
constexpr const vpart_position & operator* () const
vpart_position & operator* ()
constexpr operator bool () const noexcept
constexpr bool has_value () const noexcept
vpart_position & value ()
const vpart_position & value () const
vpart_position value_or (O &&other) const
vpart_position & emplace (Args &&... args)
vpart_position & emplace (std::initializer_list< U > ilist, Args &&... args)
void reset () noexcept
optional & operator= (nullopt_t) noexcept
optional & operator= (const optional &other)
optional & operator= (optional &&other)
optional & operator= (U &&value)
optional & operator= (const optional< U > &other)
optional & operator= (optional< U > &&other)
void swap (optional &other)
Additional Inherited Members
Public Attributes inherited from cata::optional< vpart_position >
volatile char dont_use
char dummy
StoredType data
Detailed Description
Simple wrapper to forward functions that may return a cata::optional to vpart_position.
They generally return an empty optional, or forward to the same function in vpart_position.
Definition at line 103 of file vpart_position.h.
Constructor & Destructor Documentation
optional_vpart_position()
optional_vpart_position::optional_vpart_position (cata::optional< vpart_position > p) inline
Definition at line 106 of file vpart_position.h.
                                                                  : cata::optional<vpart_position>
            ( std::move( p ) ) { }
Member Function Documentation
get_label()
cata::optional< std::string > optional_vpart_position::get_label () const inline
Definition at line 109 of file vpart_position.h.
{
            return has_value() ? value().get_label() : cata::nullopt;
        }
References vpart_position::get_label(), cata::optional< vpart_position >::has_value(), cata::nullopt, and cata::optional< vpart_position >::value().
Referenced by game::place_player().
obstacle_at_part()
cata::optional< vpart_reference > optional_vpart_position::obstacle_at_part () const
Definition at line 2494 of file vehicle.cpp.
{
    return has_value() ? value().obstacle_at_part() : cata::nullopt;
}
References cata::optional< vpart_position >::has_value(), cata::nullopt, vpart_position::obstacle_at_part(), and cata::optional< vpart_position >::value().
Referenced by game::fling_creature().
part_displayed()
cata::optional< vpart_reference > optional_vpart_position::part_displayed () const
Definition at line 2499 of file vehicle.cpp.
{
    return has_value() ? value().part_displayed() : cata::nullopt;
}
References cata::optional< vpart_position >::has_value(), cata::nullopt, vpart_position::part_displayed(), and cata::optional< vpart_position >::value().
Referenced by enumerate_objects_around_point(), and game::walk_move().
part_with_feature() [1/2]
cata::optional< vpart_reference > optional_vpart_position::part_with_feature (const std::string & f, bool unbroken) const
Definition at line 2482 of file vehicle.cpp.
{
    return has_value() ? value().part_with_feature( f, unbroken ) : cata::nullopt;
}
References cata::optional< vpart_position >::has_value(), cata::nullopt, vpart_position::part_with_feature(), and cata::optional< vpart_position >::value().
Referenced by activity_on_turn_move_loot(), zone_manager::add(), are_requirements_nearby(), character_funcs::base_comfort_value(), map::board_vehicle(), can_pickup_at(), map::can_put_items(), map::deregister_vehicle_zone(), editmap::draw_main_ui_overlay(), emit_radio_signal(), fetch_activity(), npc::find_item(), fire(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), inventory::form_from_map(), item::get_cable_target(), game::get_dangerous_tile(), player::get_eligible_containers_for_crafting(), ranged::gunmode_checks_weapon(), map::has_flag_vpart(), advanced_inv_area::init(), game::load(), avatar_action::move(), npc::move_to(), pickup::pick_up(), npc::pick_up_item(), game::place_player(), put_into_vehicle_or_drop(), zone_manager::revert_vzones(), set_item_map_or_vehicle(), game::swap_critters(), avatar_action::swim(), rot::temperature_flag_for_location(), tidy_activity(), avatar_funcs::try_to_sleep(), map::unboard_vehicle(), Character::update_bodytemp(), map::use_charges(), avatar_action::wield(), and workbench_crafting_speed_multiplier().
part_with_feature() [2/2]
cata::optional< vpart_reference > optional_vpart_position::part_with_feature (vpart_bitflags f, bool unbroken) const
Definition at line 2488 of file vehicle.cpp.
{
    return has_value() ? value().part_with_feature( f, unbroken ) : cata::nullopt;
}
References cata::optional< vpart_position >::has_value(), cata::nullopt, vpart_position::part_with_feature(), and cata::optional< vpart_position >::value().
The documentation for this class was generated from the following files:
src/vpart_position.h
src/vehicle.cpp