Cataclysm BN: json_dynamic_line_effect Class Reference
json_dynamic_line_effect Class Reference
#include <dialogue.h>
Public Member Functions
json_dynamic_line_effect (const JsonObject &jo, const std::string &id)
bool test_condition (const dialogue &d) const
void apply (dialogue &d) const
Private Attributes
std::function< bool(const dialogue &)> condition
talk_effect_t effect
Detailed Description
Definition at line 390 of file dialogue.h.
Constructor & Destructor Documentation
json_dynamic_line_effect()
json_dynamic_line_effect::json_dynamic_line_effect (const JsonObject & jo, const std::string & id)
Definition at line 3084 of file npctalk.cpp.
{
    std::function<bool( const dialogue & )> tmp_condition;
    read_condition<dialogue>( jo, "condition", tmp_condition, true );
    talk_effect_t tmp_effect = talk_effect_t( jo );
    // if the topic has a sentinel, it means implicitly add a check for the sentinel value
    // and do not run the effects if it is set.  if it is not set, run the effects and
    // set the sentinel
    if( jo.has_string( "sentinel" ) ) {
        const std::string sentinel = jo.get_string( "sentinel" );
        const std::string varname = "npctalk_var_sentinel_" + id + "_" + sentinel;
        condition = [varname, tmp_condition]( const dialogue & d ) {
            return d.alpha->get_value( varname ) != "yes" && tmp_condition( d );
        };
        std::function<void( const dialogue &d )> function = [varname]( const dialogue & d ) {
            d.alpha->set_value( varname, "yes" );
        };
        tmp_effect.effects.emplace_back( function );
    } else {
        condition = tmp_condition;
    }
    effect = tmp_effect;
}
References dialogue::alpha, condition, talk_effect_t::effects, JsonObject::get_string(), JsonObject::has_string(), read_condition< dialogue >(), and Creature::set_value().
Member Function Documentation
apply()
void json_dynamic_line_effect::apply (dialogue & d) const
Definition at line 3113 of file npctalk.cpp.
{
    effect.apply( d );
}
test_condition()
bool json_dynamic_line_effect::test_condition (const dialogue & d) const
Definition at line 3108 of file npctalk.cpp.
{
    return condition( d );
}
References condition.
Member Data Documentation
condition
std::function<bool(const dialogue &)> json_dynamic_line_effect::condition private
Definition at line 393 of file dialogue.h.
Referenced by json_dynamic_line_effect(), and test_condition().
effect
talk_effect_t json_dynamic_line_effect::effect private
Definition at line 394 of file dialogue.h.
The documentation for this class was generated from the following files:
src/dialogue.h
src/npctalk.cpp