Cataclysm BN: mon_spellcasting_actor Class Reference
mon_spellcasting_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
mon_spellcasting_actor ()=default
~mon_spellcasting_actor () override=default
void load_internal (const JsonObject &obj, const std::string &src) override
bool call (monster &) const override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
bool self
spell spell_data
int move_cost
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 47 of file mattack_actors.h.
Constructor & Destructor Documentation
mon_spellcasting_actor()
mon_spellcasting_actor::mon_spellcasting_actor () default
~mon_spellcasting_actor()
mon_spellcasting_actor::~mon_spellcasting_actor () override default
Member Function Documentation
call()
bool mon_spellcasting_actor::call (monster & mon) const override virtual
Implements mattack_actor.
Definition at line 185 of file mattack_actors.cpp.
{
    if( !mon.can_act() ) {
        return false;
    }
    if( !mon.attack_target() ) {
        // this is an attack. there is no reason to attack if there isn't a real target.
        return false;
    }
    const tripoint target = self ? mon.pos() : mon.attack_target()->pos();
    std::string fx = spell_data.effect();
    // is the spell an attack that needs to hit the target?
    // examples of spells that don't: summons, teleport self
    const bool targeted_attack = fx == "target_attack" || fx == "projectile_attack" ||
                                 fx == "cone_attack" || fx == "line_attack";
    if( targeted_attack && rl_dist( mon.pos(), target ) > spell_data.range() ) {
        return false;
    }
    std::string target_name;
    if( const Creature *target_monster = g->critter_at( target ) ) {
        target_name = target_monster->disp_name();
    }
    if( g->u.sees( target ) ) {
        add_msg( spell_data.message(), mon.disp_name(), spell_data.name(), target_name );
    }
    spell_data.cast_all_effects( mon, target );
    return true;
}
References add_msg(), monster::attack_target(), monster::can_act(), spell::cast_all_effects(), monster::disp_name(), spell::effect(), g, spell::message(), spell::name(), Creature::pos(), monster::pos(), spell::range(), rl_dist(), and spell_data.
clone()
std::unique_ptr< mattack_actor > mon_spellcasting_actor::clone () const override virtual
Implements mattack_actor.
Definition at line 164 of file mattack_actors.cpp.
{
    return std::make_unique<mon_spellcasting_actor>( *this );
}
load_internal()
void mon_spellcasting_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Implements mattack_actor.
Definition at line 169 of file mattack_actors.cpp.
{
    std::string sp_id;
    fake_spell intermediate;
    mandatory( obj, was_loaded, "spell_data", intermediate );
    self = intermediate.self;
    translation monster_message;
    optional( obj, was_loaded, "monster_message", monster_message,
              //~ "<Monster Display name> cast <Spell Name> on <Target name>!"
              to_translation( "%1$s casts %2$s at %3$s!" ) );
    spell_data = intermediate.get_spell();
    spell_data.set_message( monster_message );
    avatar fake_player;
    move_cost = spell_data.casting_time( fake_player );
}
References spell::casting_time(), fake_spell::get_spell(), mandatory(), move_cost, optional(), fake_spell::self, spell::set_message(), spell_data, to_translation(), and mattack_actor::was_loaded.
Member Data Documentation
move_cost
int mon_spellcasting_actor::move_cost
Definition at line 53 of file mattack_actors.h.
Referenced by load_internal().
self
bool mon_spellcasting_actor::self
Definition at line 51 of file mattack_actors.h.
spell_data
spell mon_spellcasting_actor::spell_data
Definition at line 52 of file mattack_actors.h.
Referenced by call(), and load_internal().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp