Cataclysm BN: mapbuffer Class Reference
mapbuffer Class Reference
Store, buffer, save and load the entire world map.
#include <mapbuffer.h>
Public Member Functions
mapbuffer ()
~mapbuffer ()
void save (bool delete_after_save=false)
Store all submaps in this instance into savefiles.
void reset ()
Delete all buffered submaps.
bool add_submap (const tripoint &p, std::unique_ptr< submap > &sm)
Add a new submap to the buffer.
bool add_submap (const tripoint &p, submap *sm)
submap * lookup_submap (const tripoint &p)
Get a submap stored in this buffer.
submap * lookup_submap (const tripoint_abs_sm &p)
submap_map_t::iterator begin ()
submap_map_t::iterator end ()
bool is_submap_loaded (const tripoint &p) const
Private Types
using submap_map_t = std::map< tripoint, submap * >
Private Member Functions
void remove_submap (tripoint addr)
submap * unserialize_submaps (const tripoint &p)
void deserialize (JsonIn &jsin)
void save_quad (const std::string &dirname, const std::string &filename, const tripoint &om_addr, std::list< tripoint > &submaps_to_delete, bool delete_after_save)
Private Attributes
submap_map_t submaps
Detailed Description
Store, buffer, save and load the entire world map.
Definition at line 19 of file mapbuffer.h.
Member Typedef Documentation
submap_map_t
using mapbuffer::submap_map_t = std::map<tripoint, submap *> private
Definition at line 62 of file mapbuffer.h.
Constructor & Destructor Documentation
mapbuffer()
mapbuffer::mapbuffer () default
~mapbuffer()
mapbuffer::~mapbuffer ()
Definition at line 44 of file mapbuffer.cpp.
{
    reset();
}
References reset().
Member Function Documentation
add_submap() [1/2]
bool mapbuffer::add_submap (const tripoint & p, std::unique_ptr< submap > & sm)
Add a new submap to the buffer.
Parameters
x,y,z The absolute world position in submap coordinates. Same as the ones in lookup_submap.
sm The submap. If the submap has been added, the unique_ptr is released (set to NULL).
Returns
true if the submap has been stored here. False if there is already a submap with the specified coordinates. The submap is not stored than and the caller must take of the submap object on their own (and properly delete it).
Definition at line 68 of file mapbuffer.cpp.
{
    const bool result = add_submap( p, sm.get() );
    if( result ) {
        sm.release();
    }
    return result;
}
References add_submap(), and coords::sm.
Referenced by add_submap(), deserialize(), generate_uniform(), and map::saven().
add_submap() [2/2]
bool mapbuffer::add_submap (const tripoint & p, submap * sm)
Definition at line 57 of file mapbuffer.cpp.
{
    if( submaps.count( p ) != 0 ) {
        return false;
    }
    submaps[p] = sm;
    return true;
}
References coords::sm, and submaps.
begin()
submap_map_t::iterator mapbuffer::begin () inline
Definition at line 65 of file mapbuffer.h.
{
            return submaps.begin();
        }
References submaps.
deserialize()
void mapbuffer::deserialize (JsonIn & jsin) private
Definition at line 280 of file mapbuffer.cpp.
{
    jsin.start_array();
    while( !jsin.end_array() ) {
        std::unique_ptr<submap> sm = std::make_unique<submap>();
        tripoint submap_coordinates;
        jsin.start_object();
        int version = 0;
        while( !jsin.end_object() ) {
            std::string submap_member_name = jsin.get_member_name();
            if( submap_member_name == "version" ) {
                version = jsin.get_int();
            } else if( submap_member_name == "coordinates" ) {
                jsin.start_array();
                tripoint loc{ jsin.get_int(), jsin.get_int(), jsin.get_int() };
                jsin.end_array();
                submap_coordinates = loc;
            } else {
                sm->load( jsin, submap_member_name, version );
            }
        }
        if( !add_submap( submap_coordinates, sm ) ) {
            debugmsg( "submap %d,%d,%d was already loaded", submap_coordinates.x, submap_coordinates.y,
                      submap_coordinates.z );
        }
    }
}
References add_submap(), debugmsg, JsonIn::end_array(), JsonIn::end_object(), JsonIn::get_int(), JsonIn::get_member_name(), coords::sm, JsonIn::start_array(), JsonIn::start_object(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by unserialize_submaps().
end()
submap_map_t::iterator mapbuffer::end () inline
Definition at line 68 of file mapbuffer.h.
{
            return submaps.end();
        }
References submaps.
is_submap_loaded()
bool mapbuffer::is_submap_loaded (const tripoint & p) const inline
Definition at line 72 of file mapbuffer.h.
{
            return submaps.count( p ) > 0;
        }
References submaps.
lookup_submap() [1/2]
submap * mapbuffer::lookup_submap (const tripoint & p)
Get a submap stored in this buffer.
Parameters
x,y,z The absolute world position in submap coordinates. Same as the ones in add_submap.
Returns
NULL if the submap is not in the mapbuffer and could not be loaded. The mapbuffer takes care of the returned submap object, don't delete it on your own.
Definition at line 88 of file mapbuffer.cpp.
{
    const auto iter = submaps.find( p );
    if( iter == submaps.end() ) {
        try {
            return unserialize_submaps( p );
        } catch( const std::exception &err ) {
            debugmsg( "Failed to load submap %s: %s", p.to_string(), err.what() );
        }
        return nullptr;
    }
    return iter->second;
}
References debugmsg, submaps, tripoint::to_string(), and unserialize_submaps().
Referenced by grid_furn_transform_queue::apply(), distribution_grid::distribution_grid(), overmap_ui::draw_ascii(), vehicle::find_vehicle(), active_tiles::furn_at(), overmap::is_omt_generated(), is_sm_tile_outside(), is_sm_tile_over_water(), map::loadn(), lookup_submap(), distribution_grid::update(), and charger_tile::update_internal().
lookup_submap() [2/2]
submap * mapbuffer::lookup_submap (const tripoint_abs_sm & p) inline
Definition at line 57 of file mapbuffer.h.
{
            return lookup_submap( p.raw() );
        }
References lookup_submap(), and coords::coord_point< Point, Origin, Scale >::raw().
remove_submap()
void mapbuffer::remove_submap (tripoint addr) private
Definition at line 77 of file mapbuffer.cpp.
{
    auto m_target = submaps.find( addr );
    if( m_target == submaps.end() ) {
        debugmsg( "Tried to remove non-existing submap %s", addr.to_string() );
        return;
    }
    delete m_target->second;
    submaps.erase( m_target );
}
References debugmsg, submaps, and tripoint::to_string().
Referenced by save().
reset()
void mapbuffer::reset ()
Delete all buffered submaps.
Definition at line 49 of file mapbuffer.cpp.
{
    for( auto &elem : submaps ) {
        delete elem.second;
    }
    submaps.clear();
}
References submaps.
Referenced by init::check_mods_for_errors(), game::cleanup_at_end(), main_menu::new_character_tab(), game::quickload(), game::start_game(), main_menu::world_tab(), and ~mapbuffer().
save()
void mapbuffer::save (bool delete_after_save = false)
Store all submaps in this instance into savefiles.
Parameters
delete_after_save If true, the saved submaps are removed from the mapbuffer (and deleted).
Definition at line 103 of file mapbuffer.cpp.
{
    assure_dir_exist( g->get_world_base_save_path() + "/maps" );
    int num_saved_submaps = 0;
    int num_total_submaps = submaps.size();
    map &here = get_map();
    const tripoint map_origin = sm_to_omt_copy( here.get_abs_sub() );
    const bool map_has_zlevels = g != nullptr && here.has_zlevels();
    static_popup popup;
    // A set of already-saved submaps, in global overmap coordinates.
    std::set<tripoint> saved_submaps;
    std::list<tripoint> submaps_to_delete;
    static constexpr std::chrono::milliseconds update_interval( 500 );
    auto last_update = std::chrono::steady_clock::now();
    for( auto &elem : submaps ) {
        auto now = std::chrono::steady_clock::now();
        if( last_update + update_interval < now ) {
            popup.message( _( "Please wait as the map saves [%d/%d]" ),
                           num_saved_submaps, num_total_submaps );
            ui_manager::redraw();
            refresh_display();
            inp_mngr.pump_events();
            last_update = now;
        }
        // Whatever the coordinates of the current submap are,
        // we're saving a 2x2 quad of submaps at a time.
        // Submaps are generated in quads, so we know if we have one member of a quad,
        // we have the rest of it, if that assumption is broken we have REAL problems.
        const tripoint om_addr = sm_to_omt_copy( elem.first );
        if( saved_submaps.count( om_addr ) != 0 ) {
            // Already handled this one.
            continue;
        }
        saved_submaps.insert( om_addr );
        // A segment is a chunk of 32x32 submap quads.
        // We're breaking them into subdirectories so there aren't too many files per directory.
        // Might want to make a set for this one too so it's only checked once per save().
        const std::string dirname = find_dirname( om_addr );
        const std::string quad_path = find_quad_path( dirname, om_addr );
        // delete_on_save deletes everything, otherwise delete submaps
        // outside the current map.
        const bool zlev_del = !map_has_zlevels && om_addr.z != g->get_levz();
        save_quad( dirname, quad_path, om_addr, submaps_to_delete,
                   delete_after_save || zlev_del ||
                   om_addr.x < map_origin.x || om_addr.y < map_origin.y ||
                   om_addr.x > map_origin.x + HALF_MAPSIZE ||
                   om_addr.y > map_origin.y + HALF_MAPSIZE );
        num_saved_submaps += 4;
    }
    for( auto &elem : submaps_to_delete ) {
        remove_submap( elem );
    }
    get_distribution_grid_tracker().on_saved();
}
References _, assure_dir_exist(), find_dirname(), find_quad_path(), g, map::get_abs_sub(), get_distribution_grid_tracker(), get_map(), HALF_MAPSIZE, map::has_zlevels(), inp_mngr, distribution_grid_tracker::on_saved(), popup(), input_manager::pump_events(), ui_manager::redraw(), refresh_display(), remove_submap(), save_quad(), sm_to_omt_copy(), submaps, tripoint::x, tripoint::y, and tripoint::z.
Referenced by game::save_maps().
save_quad()
void mapbuffer::save_quad (const std::string & dirname, const std::string & filename, const tripoint & om_addr, std::list< tripoint > & submaps_to_delete, bool delete_after_save) private
Definition at line 166 of file mapbuffer.cpp.
{
    std::vector<point> offsets;
    std::vector<tripoint> submap_addrs;
    offsets.push_back( point_zero );
    offsets.push_back( point_south );
    offsets.push_back( point_east );
    offsets.push_back( point_south_east );
    bool all_uniform = true;
    for( auto &offsets_offset : offsets ) {
        tripoint submap_addr = omt_to_sm_copy( om_addr );
        submap_addr.x += offsets_offset.x;
        submap_addr.y += offsets_offset.y;
        submap_addrs.push_back( submap_addr );
        submap *sm = submaps[submap_addr];
        if( sm != nullptr && !sm->is_uniform ) {
            all_uniform = false;
        }
    }
    if( all_uniform ) {
        // Nothing to save - this quad will be regenerated faster than it would be re-read
        if( delete_after_save ) {
            for( auto &submap_addr : submap_addrs ) {
                if( submaps.count( submap_addr ) > 0 && submaps[submap_addr] != nullptr ) {
                    submaps_to_delete.push_back( submap_addr );
                }
            }
        }
        return;
    }
    if( disable_mapgen ) {
        return;
    }
    // Don't create the directory if it would be empty
    assure_dir_exist( dirname );
    write_to_file( filename, [&]( std::ostream & fout ) {
        JsonOut jsout( fout );
        jsout.start_array();
        for( auto &submap_addr : submap_addrs ) {
            if( submaps.count( submap_addr ) == 0 ) {
                continue;
            }
            submap *sm = submaps[submap_addr];
            if( sm == nullptr ) {
                continue;
            }
            jsout.start_object();
            jsout.member( "version", savegame_version );
            jsout.member( "coordinates" );
            jsout.start_array();
            jsout.write( submap_addr.x );
            jsout.write( submap_addr.y );
            jsout.write( submap_addr.z );
            jsout.end_array();
            sm->store( jsout );
            jsout.end_object();
            if( delete_after_save ) {
                submaps_to_delete.push_back( submap_addr );
            }
        }
        jsout.end_array();
    } );
}
References assure_dir_exist(), disable_mapgen, JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), offsets, omt_to_sm_copy(), point_east, point_south, point_south_east, point_zero, savegame_version, coords::sm, JsonOut::start_array(), JsonOut::start_object(), submaps, JsonOut::write(), write_to_file(), tripoint::x, and tripoint::y.
Referenced by save().
unserialize_submaps()
submap * mapbuffer::unserialize_submaps (const tripoint & p) private
Definition at line 248 of file mapbuffer.cpp.
{
    // Map the tripoint to the submap quad that stores it.
    const tripoint om_addr = sm_to_omt_copy( p );
    const std::string dirname = find_dirname( om_addr );
    std::string quad_path = find_quad_path( dirname, om_addr );
    if( !file_exist( quad_path ) ) {
        // Fix for old saves where the path was generated using std::stringstream, which
        // did format the number using the current locale. That formatting may insert
        // thousands separators, so the resulting path is "map/1,234.7.8.map" instead
        // of "map/1234.7.8.map".
        std::ostringstream buffer;
        buffer << dirname << "/" << om_addr.x << "." << om_addr.y << "." << om_addr.z << ".map";
        if( file_exist( buffer.str() ) ) {
            quad_path = buffer.str();
        }
    }
    using namespace std::placeholders;
    if( !read_from_file_optional_json( quad_path, std::bind( &mapbuffer::deserialize, this, _1 ) ) ) {
        // If it doesn't exist, trigger generating it.
        return nullptr;
    }
    if( submaps.count( p ) == 0 ) {
        debugmsg( "file %s did not contain the expected submap %d,%d,%d",
                  quad_path, p.x, p.y, p.z );
        return nullptr;
    }
    return submaps[ p ];
}
References debugmsg, deserialize(), file_exist(), find_dirname(), find_quad_path(), read_from_file_optional_json(), sm_to_omt_copy(), submaps, tripoint::x, tripoint::y, and tripoint::z.
Referenced by lookup_submap().
Member Data Documentation
submaps
submap_map_t mapbuffer::submaps private
Definition at line 85 of file mapbuffer.h.
Referenced by add_submap(), begin(), end(), is_submap_loaded(), lookup_submap(), remove_submap(), reset(), save(), save_quad(), and unserialize_submaps().
The documentation for this class was generated from the following files:
src/mapbuffer.h
src/mapbuffer.cpp