Cataclysm BN: bandolier_actor Class Reference
bandolier_actor Class Reference
Store ammo and later reload using it.
#include <iuse_actor.h>
Public Member Functions
bool is_valid_ammo_type (const itype &) const
Can this type of ammo ever be stored.
bool can_store (const item &bandolier, const item &obj) const
Check if obj could be stored in the bandolier.
bool reload (player &p, item &obj) const
Store ammo in the bandolier.
bandolier_actor (const std::string &type="bandolier")
~bandolier_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
units::volume max_stored_volume () const
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int capacity = 1
Total number of rounds that can be stored.
std::set< ammotype > ammo
What types of ammo can be stored?
int draw_cost = INVENTORY_HANDLING_PENALTY
Base cost of accessing/storing an item.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Store ammo and later reload using it.
Definition at line 884 of file iuse_actor.h.
Constructor & Destructor Documentation
bandolier_actor()
bandolier_actor::bandolier_actor (const std::string & type = "bandolier") inline
Definition at line 905 of file iuse_actor.h.
: iuse_actor(type) {}
~bandolier_actor()
bandolier_actor::~bandolier_actor () override default
Member Function Documentation
can_store()
bool bandolier_actor::can_store (const item & bandolier, const item & obj) const
Check if obj could be stored in the bandolier.
Definition at line 2861 of file iuse_actor.cpp.
{
    if( !bandolier.contents.empty() && ( bandolier.contents.front().typeId() != obj.typeId() ||
                                         bandolier.contents.front().charges >= capacity ) ) {
        return false;
    }
    return is_valid_ammo_type( *obj.type );
}
References capacity, item::charges, item::contents, item_contents::empty(), item_contents::front(), is_valid_ammo_type(), item::type, and item::typeId().
Referenced by reload().
clone()
std::unique_ptr< iuse_actor > bandolier_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2821 of file iuse_actor.cpp.
{
    return std::make_unique<bandolier_actor>( *this );
}
info()
void bandolier_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 2837 of file iuse_actor.cpp.
{
    if( !ammo.empty() ) {
        auto str = enumerate_as_string( ammo.begin(), ammo.end(),
        [&]( const ammotype & a ) {
            return string_format( "<stat>%s</stat>", a->name() );
        }, enumeration_conjunction::or_ );
        dump.emplace_back( "TOOL", string_format(
                               vgettext( "Can be activated to store a single round of ",
                                         "Can be activated to store up to <stat>%i</stat> rounds of ", capacity ),
                               capacity ),
                           str );
    }
}
References a, ammo, capacity, enumerate_as_string(), or_, string_format(), and vgettext().
is_valid_ammo_type()
bool bandolier_actor::is_valid_ammo_type (const itype & t) const
Can this type of ammo ever be stored.
Definition at line 2853 of file iuse_actor.cpp.
{
    if( !t.ammo ) {
        return false;
    }
    return ammo.count( t.ammo->type );
}
References itype::ammo, and ammo.
Referenced by can_store(), and max_stored_volume().
load()
void bandolier_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2826 of file iuse_actor.cpp.
{
    capacity = obj.get_int( "capacity", capacity );
    ammo.clear();
    for( auto &e : obj.get_tags( "ammo" ) ) {
        ammo.insert( ammotype( e ) );
    }
    draw_cost = obj.get_int( "draw_cost", draw_cost );
}
References ammo, capacity, draw_cost, JsonObject::get_int(), and JsonObject::get_tags().
max_stored_volume()
units::volume bandolier_actor::max_stored_volume () const
Definition at line 2965 of file iuse_actor.cpp.
{
    // This is relevant only for bandoliers with the non-rigid flag
    // Find all valid ammo
    auto ammo_types = item_controller->find( [&]( const itype & t ) {
        return is_valid_ammo_type( t );
    } );
    // Figure out which has the greatest volume and calculate on that basis
    units::volume max_ammo_volume{};
    for( const auto *ammo_type : ammo_types ) {
        max_ammo_volume = std::max( max_ammo_volume, ammo_type->volume / ammo_type->stack_size );
    }
    return max_ammo_volume * capacity;
}
References capacity, is_valid_ammo_type(), and item_controller.
reload()
bool bandolier_actor::reload (player & p, item & obj) const
Store ammo in the bandolier.
Definition at line 2871 of file iuse_actor.cpp.
{
    if( !obj.is_bandolier() ) {
        debugmsg( "Invalid item passed to bandolier_actor" );
        return false;
    }
    // find all nearby compatible ammo (matching type currently contained if appropriate)
    auto found = p.nearby( [&]( const item * e, const item * parent ) {
        return parent != &obj && can_store( obj, *e );
    } );
    if( found.empty() ) {
        p.add_msg_if_player( m_bad, _( "No matching ammo for the %1$s" ), obj.type_name() );
        return false;
    }
    // convert these into reload options and display the selection prompt
    std::vector<item_reload_option> opts;
    std::transform( std::make_move_iterator( found.begin() ), std::make_move_iterator( found.end() ),
    std::back_inserter( opts ), [&]( item_location && e ) {
        return item_reload_option( &p, &obj, &obj, e );
    } );
    item_reload_option sel = character_funcs::select_ammo( p, obj, std::move( opts ) );
    if( !sel ) {
        return false; // canceled menu
    }
    p.mod_moves( -sel.moves() );
    // add or stack the ammo dependent upon existing contents
    if( obj.contents.empty() ) {
        item put = sel.ammo->split( sel.qty() );
        if( !put.is_null() ) {
            obj.put_in( put );
        } else {
            obj.put_in( *sel.ammo );
            sel.ammo.remove_item();
        }
    } else {
        obj.contents.front().charges += sel.qty();
        if( sel.ammo->charges > sel.qty() ) {
            sel.ammo->charges -= sel.qty();
        } else {
            sel.ammo.remove_item();
        }
    }
    p.add_msg_if_player( _( "You store the %1$s in your %2$s" ),
                         obj.contents.front().tname( sel.qty() ),
                         obj.type_name() );
    return true;
}
References _, player::add_msg_if_player(), item_reload_option::ammo, can_store(), item::charges, item::contents, debugmsg, item_contents::empty(), item_contents::front(), item::is_bandolier(), item::is_null(), m_bad, Creature::mod_moves(), avatar_action::move(), item_reload_option::moves(), Character::nearby(), item::put_in(), item_reload_option::qty(), item_location::remove_item(), character_funcs::select_ammo(), item::split(), item::tname(), iexamine::transform(), and item::type_name().
Referenced by use().
use()
int bandolier_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2927 of file iuse_actor.cpp.
{
    if( p.is_wielding( it ) ) {
        p.add_msg_if_player( _( "You need to unwield your %s before using it." ),
                             it.type_name() );
        return 0;
    }
    uilist menu;
    menu.text = _( "Store ammo" );
    std::vector<std::function<void()>> actions;
    menu.addentry( -1, it.contents.empty() || it.contents.front().charges < capacity,
                   'r', _( "Store ammo in %s" ), it.type_name() );
    actions.emplace_back( [&] { reload( p, it ); } );
    menu.addentry( -1, !it.contents.empty(), 'u', _( "Unload %s" ), it.type_name() );
    actions.emplace_back( [&] {
        if( p.i_add_or_drop( it.contents.front() ) )
        {
            it.remove_item( it.contents.front() );
        } else
        {
            p.add_msg_if_player( _( "Never mind." ) );
        }
    } );
    menu.query();
    if( menu.ret >= 0 ) {
        actions[ menu.ret ]();
    }
    return 0;
}
References _, player::add_msg_if_player(), uilist::addentry(), capacity, item::charges, item::contents, item_contents::empty(), item_contents::front(), Character::i_add_or_drop(), Character::is_wielding(), uilist::query(), reload(), visitable< T >::remove_item(), uilist::ret, uilist::text, and item::type_name().
Member Data Documentation
ammo
std::set<ammotype> bandolier_actor::ammo
What types of ammo can be stored?
Definition at line 891 of file iuse_actor.h.
Referenced by info(), is_valid_ammo_type(), and load().
capacity
int bandolier_actor::capacity = 1
Total number of rounds that can be stored.
Definition at line 888 of file iuse_actor.h.
Referenced by can_store(), info(), load(), max_stored_volume(), and use().
draw_cost
int bandolier_actor::draw_cost = INVENTORY_HANDLING_PENALTY
Base cost of accessing/storing an item.
Scales down to half of that with skills.
Definition at line 894 of file iuse_actor.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp