Cataclysm BN: disassemble_activity_actor Class Reference
disassemble_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
disassemble_activity_actor ()=default
disassemble_activity_actor (std::vector< iuse_location > &&targets, tripoint_abs_ms pos, bool recursive)
~disassemble_activity_actor ()=default
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
act_progress_message get_progress_message (const player_activity &, const Character &) const override
bool try_start_single (player_activity &act, Character &who)
int calc_num_targets () const
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Attributes
std::vector< iuse_location > targets
tripoint_abs_ms pos
bool recursive = false
int initial_num_targets = 0
Detailed Description
Definition at line 230 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
disassemble_activity_actor() [1/2]
disassemble_activity_actor::disassemble_activity_actor () default
disassemble_activity_actor() [2/2]
disassemble_activity_actor::disassemble_activity_actor (std::vector< iuse_location > && targets, tripoint_abs_ms pos, bool recursive) inline
Definition at line 240 of file activity_actor_definitions.h.
          : targets( std::move( targets ) ), pos( pos ), recursive( recursive ) {}
~disassemble_activity_actor()
disassemble_activity_actor::~disassemble_activity_actor () default
Member Function Documentation
calc_num_targets()
int disassemble_activity_actor::calc_num_targets () const
Definition at line 597 of file activity_actor.cpp.
{
    return static_cast<int>( targets.size() );
}
References targets.
Referenced by get_progress_message(), and start().
clone()
std::unique_ptr< activity_actor > disassemble_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 255 of file activity_actor_definitions.h.
{
            return std::make_unique<disassemble_activity_actor>( *this );
        }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > disassemble_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 649 of file activity_actor.cpp.
{
    disassemble_activity_actor actor;
    JsonObject data = jsin.get_object();
    data.read( "targets", actor.targets );
    data.read( "pos", actor.pos );
    data.read( "recursive", actor.recursive );
    data.read( "initial_num_targets", actor.initial_num_targets );
    return actor.clone();
}
References clone(), JsonIn::get_object(), initial_num_targets, pos, JsonObject::read(), recursive, and targets.
do_turn()
void disassemble_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 252 of file activity_actor_definitions.h.
{};
finish()
void disassemble_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 613 of file activity_actor.cpp.
{
    const iuse_location &target = targets.front();
    if( !target.loc ) {
        debugmsg( "Lost target of ACT_DISASSEMBLY" );
    } else {
        crafting::complete_disassemble( who, target, get_map().getlocal( pos.raw() ) );
    }
    targets.erase( targets.begin() );
    if( try_start_single( act, who ) ) {
        return;
    }
    // Make a copy to avoid use-after-free
    bool recurse = this->recursive;
    act.set_to_null();
    if( recurse ) {
        crafting::disassemble_all( *who.as_avatar(), recurse );
    }
}
References act, Creature::as_avatar(), crafting::complete_disassemble(), debugmsg, crafting::disassemble_all(), get_map(), iuse_location::loc, pos, coords::coord_point< Point, Origin, Scale >::raw(), recursive, player_activity::set_to_null(), targets, and try_start_single().
get_progress_message()
act_progress_message disassemble_activity_actor::get_progress_message (const player_activity & act, const Character &) const override virtual
Reimplemented from activity_actor.
Definition at line 663 of file activity_actor.cpp.
{
    std::string msg;
    const int percentage = ( ( act.moves_total - act.moves_left ) * 100 ) / act.moves_total;
    msg = string_format( "%d%%", percentage );
    if( initial_num_targets != 1 ) {
        constexpr int width = 20; // An arbitrary value
        std::string item_name_trimmed = trim_by_length( targets.front().loc->display_name(), width );
        msg += string_format(
                   _( "\n%d out of %d, working on %-20s" ),
                   initial_num_targets - calc_num_targets() + 1,
                   initial_num_targets,
                   item_name_trimmed
               );
    }
    return act_progress_message::make_extra_info( std::move( msg ) );
}
References _, act, calc_num_targets(), initial_num_targets, act_progress_message::make_extra_info(), avatar_action::move(), string_format(), targets, and trim_by_length().
get_type()
activity_id disassemble_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 247 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_DISASSEMBLE" );
        }
serialize()
void disassemble_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 637 of file activity_actor.cpp.
{
    jsout.start_object();
    jsout.member( "targets", targets );
    jsout.member( "pos", pos );
    jsout.member( "recursive", recursive );
    jsout.member( "initial_num_targets", initial_num_targets );
    jsout.end_object();
}
References JsonOut::end_object(), initial_num_targets, JsonOut::member(), pos, recursive, JsonOut::start_object(), and targets.
start()
void disassemble_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 602 of file activity_actor.cpp.
{
    if( !who.is_avatar() ) {
        debugmsg( "ACT_DISASSEMBLE is not implemented for NPCs" );
        act.set_to_null();
    } else if( !try_start_single( act, who ) ) {
        act.set_to_null();
    }
    initial_num_targets = calc_num_targets();
}
References act, calc_num_targets(), debugmsg, initial_num_targets, Creature::is_avatar(), and try_start_single().
try_start_single()
bool disassemble_activity_actor::try_start_single (player_activity & act, Character & who)
Definition at line 569 of file activity_actor.cpp.
{
    if( targets.empty() ) {
        return false;
    }
    const iuse_location &target = targets.front();
    if( !target.loc ) {
        debugmsg( "Lost target of ACT_DISASSEMBLE" );
        targets.clear();
        return false;
    }
    const item &itm = *target.loc;
    const recipe &dis = recipe_dictionary::get_uncraft( itm.typeId() );
    // Have to check here again in case we ran out of tools
    const ret_val<bool> can_do = crafting::can_disassemble( who, itm, who.crafting_inventory() );
    if( !can_do.success() ) {
        who.add_msg_if_player( m_info, "%s", can_do.c_str() );
        return false;
    }
    int moves_needed = dis.time * target.count;
    act.moves_total = moves_needed;
    act.moves_left = moves_needed;
    return true;
}
References act, Creature::add_msg_if_player(), ret_val< T >::c_str(), crafting::can_disassemble(), iuse_location::count, Character::crafting_inventory(), debugmsg, recipe_dictionary::get_uncraft(), iuse_location::loc, m_info, ret_val< T >::success(), targets, recipe::time, and item::typeId().
Referenced by finish(), and start().
Member Data Documentation
initial_num_targets
int disassemble_activity_actor::initial_num_targets = 0 private
Definition at line 236 of file activity_actor_definitions.h.
Referenced by deserialize(), get_progress_message(), serialize(), and start().
pos
tripoint_abs_ms disassemble_activity_actor::pos private
Definition at line 234 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
recursive
bool disassemble_activity_actor::recursive = false private
Definition at line 235 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
targets
std::vector<iuse_location> disassemble_activity_actor::targets private
Definition at line 233 of file activity_actor_definitions.h.
Referenced by calc_num_targets(), deserialize(), finish(), get_progress_message(), serialize(), and try_start_single().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp