Cataclysm BN: place_trap_actor Class Reference
place_trap_actor Class Reference
#include <iuse_actor.h>
Classes
struct data
Public Member Functions
bool is_allowed (player &p, const tripoint &pos, const std::string &name) const
place_trap_actor (const std::string &type="place_trap")
~place_trap_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
bool allow_underwater = false
Whether one can place the trap when underwater.
bool allow_under_player = false
Whether one can place the trap directly under the character itself.
bool needs_solid_neighbor = false
Whether the trap needs solid neighbor squares (e.g.
ter_str_id needs_neighbor_terrain
Contains a terrain id of the terrain that must exist in a neighbor square to allow placing this trap.
data unburied_data
Data that applies to unburied traps and to traps that *can * not be buried.
std::string bury_question
Contains the question asked when the player can bury the trap.
data buried_data
Data that applies to buried traps.
trap_str_id outer_layer_trap
The trap that makes up the outer layer of a multi-tile trap.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1072 of file iuse_actor.h.
Constructor & Destructor Documentation
place_trap_actor()
place_trap_actor::place_trap_actor (const std::string & type = "place_trap")
Definition at line 4048 of file iuse_actor.cpp.
                                                          :
    iuse_actor( type ), needs_neighbor_terrain( ter_str_id::NULL_ID() ),
    outer_layer_trap( trap_str_id::NULL_ID() ) {}
~place_trap_actor()
place_trap_actor::~place_trap_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > place_trap_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4077 of file iuse_actor.cpp.
{
    return std::make_unique<place_trap_actor>( *this );
}
is_allowed()
bool place_trap_actor::is_allowed (player & p, const tripoint & pos, const std::string & name) const
Definition at line 4101 of file iuse_actor.cpp.
{
    if( !allow_under_player && pos == p.pos() ) {
        p.add_msg_if_player( m_info, _( "Yeah.  Place the %s at your feet.  Real damn smart move." ),
                             name );
        return false;
    }
    map &here = get_map();
    if( here.move_cost( pos ) != 2 ) {
        p.add_msg_if_player( m_info, _( "You can't place a %s there." ), name );
        return false;
    }
    if( needs_solid_neighbor ) {
        if( !is_solid_neighbor( pos, point_east ) && !is_solid_neighbor( pos, point_south ) &&
            !is_solid_neighbor( pos, point_south_east ) && !is_solid_neighbor( pos, point_north_east ) ) {
            p.add_msg_if_player( m_info, _( "You must place the %s between two solid tiles." ), name );
            return false;
        }
    }
    if( needs_neighbor_terrain && !has_neighbor( pos, needs_neighbor_terrain ) ) {
        p.add_msg_if_player( m_info, _( "The %s needs a %s adjacent to it." ), name,
                             needs_neighbor_terrain.obj().name() );
        return false;
    }
    const trap &existing_trap = here.tr_at( pos );
    if( !existing_trap.is_null() ) {
        if( existing_trap.can_see( pos, p ) ) {
            p.add_msg_if_player( m_info, _( "You can't place a %s there.  It contains a trap already." ),
                                 name );
        } else {
            p.add_msg_if_player( m_bad, _( "You trigger a %s!" ), existing_trap.name() );
            existing_trap.trigger( pos, &p );
        }
        return false;
    }
    return true;
}
References _, player::add_msg_if_player(), allow_under_player, trap::can_see(), get_map(), has_neighbor(), trap::is_null(), is_solid_neighbor(), m_bad, m_info, map::move_cost(), map_data_common_t::name(), trap::name(), om_direction::name(), needs_neighbor_terrain, needs_solid_neighbor, string_id< T >::obj(), point_east, point_north_east, point_south, point_south_east, Character::pos(), map::tr_at(), and trap::trigger().
Referenced by use().
load()
void place_trap_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 4062 of file iuse_actor.cpp.
{
    assign( obj, "allow_underwater", allow_underwater );
    assign( obj, "allow_under_player", allow_under_player );
    assign( obj, "needs_solid_neighbor", needs_solid_neighbor );
    assign( obj, "needs_neighbor_terrain", needs_neighbor_terrain );
    assign( obj, "bury_question", bury_question );
    if( !bury_question.empty() ) {
        JsonObject buried_json = obj.get_object( "bury" );
        buried_data.load( buried_json );
    }
    unburied_data.load( obj );
    assign( obj, "outer_layer_trap", outer_layer_trap );
}
References allow_under_player, allow_underwater, assign(), buried_data, bury_question, JsonObject::get_object(), place_trap_actor::data::load(), needs_neighbor_terrain, needs_solid_neighbor, outer_layer_trap, and unburied_data.
use()
int place_trap_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 4149 of file iuse_actor.cpp.
{
    const bool could_bury = !bury_question.empty();
    if( !allow_underwater && p.is_underwater() ) {
        p.add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You can't do that while mounted." ) );
        return 0;
    }
    const cata::optional<tripoint> pos_ = choose_adjacent( string_format( _( "Place %s where?" ),
                                          it.tname() ) );
    if( !pos_ ) {
        return 0;
    }
    tripoint pos = *pos_;
    if( !is_allowed( p, pos, it.tname() ) ) {
        return 0;
    }
    map &here = get_map();
    int distance_to_trap_center = unburied_data.trap.obj().get_trap_radius() +
                                  outer_layer_trap.obj().get_trap_radius() + 1;
    if( unburied_data.trap.obj().get_trap_radius() > 0 ) {
        // Math correction for multi-tile traps
        pos.x = ( pos.x - p.posx() ) * distance_to_trap_center + p.posx();
        pos.y = ( pos.y - p.posy() ) * distance_to_trap_center + p.posy();
        for( const tripoint &t : here.points_in_radius( pos, outer_layer_trap.obj().get_trap_radius(),
                0 ) ) {
            if( !is_allowed( p, t, it.tname() ) ) {
                p.add_msg_if_player( m_info,
                                     _( "That trap needs a space in %d tiles radius to be clear, centered %d tiles from you." ),
                                     outer_layer_trap.obj().get_trap_radius(), distance_to_trap_center );
                return 0;
            }
        }
    }
    const bool has_shovel = p.has_quality( quality_id( "DIG" ), 3 );
    const bool is_diggable = here.has_flag( "DIGGABLE", pos );
    bool bury = false;
    if( could_bury && has_shovel && is_diggable ) {
        bury = query_yn( _( bury_question ) );
    }
    const auto &data = bury ? buried_data : unburied_data;
    p.add_msg_if_player( m_info, _( data.done_message ), distance_to_trap_center );
    p.practice( skill_id( "traps" ), data.practice );
    p.mod_moves( -data.moves );
    place_and_add_as_known( p, pos, data.trap );
    for( const tripoint &t : here.points_in_radius( pos, data.trap.obj().get_trap_radius(), 0 ) ) {
        if( t != pos ) {
            place_and_add_as_known( p, t, outer_layer_trap );
        }
    }
    return 1;
}
References _, player::add_msg_if_player(), allow_underwater, buried_data, bury_question, choose_adjacent(), place_trap_actor::data::done_message, get_map(), trap::get_trap_radius(), map::has_flag(), visitable< T >::has_quality(), is_allowed(), Character::is_mounted(), Creature::is_underwater(), m_info, Creature::mod_moves(), place_trap_actor::data::moves, string_id< T >::obj(), outer_layer_trap, place_and_add_as_known(), map::points_in_radius(), Character::pos(), Character::posx(), Character::posy(), place_trap_actor::data::practice, player::practice(), query_yn(), skill_id, string_format(), item::tname(), place_trap_actor::data::trap, unburied_data, tripoint::x, and tripoint::y.
Member Data Documentation
allow_under_player
bool place_trap_actor::allow_under_player = false
Whether one can place the trap directly under the character itself.
Definition at line 1089 of file iuse_actor.h.
Referenced by is_allowed(), and load().
allow_underwater
bool place_trap_actor::allow_underwater = false
Whether one can place the trap when underwater.
Definition at line 1087 of file iuse_actor.h.
Referenced by load(), and use().
buried_data
data place_trap_actor::buried_data
Data that applies to buried traps.
Definition at line 1104 of file iuse_actor.h.
Referenced by load(), and use().
bury_question
std::string place_trap_actor::bury_question
Contains the question asked when the player can bury the trap.
Something like "Bury the trap?"
Definition at line 1102 of file iuse_actor.h.
Referenced by load(), and use().
needs_neighbor_terrain
ter_str_id place_trap_actor::needs_neighbor_terrain
Contains a terrain id of the terrain that must exist in a neighbor square to allow placing this trap.
If empty, it is ignored. This is for example for snare traps.
Definition at line 1096 of file iuse_actor.h.
Referenced by is_allowed(), and load().
needs_solid_neighbor
bool place_trap_actor::needs_solid_neighbor = false
Whether the trap needs solid neighbor squares (e.g.
for trap wire).
Definition at line 1091 of file iuse_actor.h.
Referenced by is_allowed(), and load().
outer_layer_trap
trap_str_id place_trap_actor::outer_layer_trap
The trap that makes up the outer layer of a multi-tile trap.
This is not supported for buried traps!
Definition at line 1108 of file iuse_actor.h.
Referenced by load(), and use().
unburied_data
data place_trap_actor::unburied_data
Data that applies to unburied traps and to traps that *can * not be buried.
Definition at line 1098 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp