Cataclysm BN: jmapgen_zone Class Reference
jmapgen_zone Class Reference
Place a zone.
Public Member Functions
jmapgen_zone (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
zone_type_id zone_type
faction_id faction
std::string name = ""
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a zone.
Definition at line 1736 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_zone()
jmapgen_zone::jmapgen_zone (const JsonObject & jsi) inline
Definition at line 1742 of file mapgen.cpp.
{
            if( jsi.has_string( "faction" ) && jsi.has_string( "type" ) ) {
                std::string fac_id = jsi.get_string( "faction" );
                faction = faction_id( fac_id );
                std::string zone_id = jsi.get_string( "type" );
                zone_type = zone_type_id( zone_id );
                if( jsi.has_string( "name" ) ) {
                    name = jsi.get_string( "name" );
                }
            }
        }
References JsonObject::get_string(), JsonObject::has_string(), mapgen_defer::jsi, and name.
Member Function Documentation
apply()
void jmapgen_zone::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1753 of file mapgen.cpp.
{
            zone_manager &mgr = zone_manager::get_manager();
            const tripoint start = dat.m.getabs( tripoint( x.val, y.val, 0 ) );
            const tripoint end = dat.m.getabs( tripoint( x.valmax, y.valmax, 0 ) );
            mgr.add( name, zone_type, faction, false, true, start, end );
        }
References zone_manager::add(), zone_manager::get_manager(), map::getabs(), mapgendata::m, name, jmapgen_int::val, and jmapgen_int::valmax.
Member Data Documentation
faction
faction_id jmapgen_zone::faction
Definition at line 1740 of file mapgen.cpp.
name
std::string jmapgen_zone::name = ""
Definition at line 1741 of file mapgen.cpp.
Referenced by apply(), and jmapgen_zone().
zone_type
zone_type_id jmapgen_zone::zone_type
Definition at line 1739 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp