Cataclysm BN: input_context Class Reference
input_context Class Reference
Represents a context in which a set of actions can be performed.
#include <input.h>
Public Types
using input_event_filter = std::function< bool(const input_event &)>
Public Member Functions
input_context ()
input_context (const std::string &category)
void register_action (const std::string &action_descriptor)
Register an action with this input context.
void register_action (const std::string &action_descriptor, const translation &name)
Same as other register_action function but allows a context specific action name.
std::string get_available_single_char_hotkeys (std::string requested_keys="abcdefghijkpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-=:;'\",./<>?!@#$%^&*()_+[]\\{}|`~")
Get the set of available single character keyboard keys that do not conflict with any registered hotkeys.
std::string get_desc (const std::string &action_descriptor, unsigned int max_limit=0, const input_event_filter &evt_filter=allow_all_keys) const
Get a description text for the key/other input method associated with the given action.
std::string get_desc (const std::string &action_descriptor, const std::string &text, const input_event_filter &evt_filter=allow_all_keys) const
Get a description based on text.
std::string describe_key_and_name (const std::string &action_descriptor, const input_event_filter &evt_filter=allow_all_keys) const
Equivalent to get_desc(act, get_action_name(act), filter)
const std::string & handle_input ()
Handles input and returns the next action in the queue.
const std::string & handle_input (int timeout)
cata::optional< tripoint > get_direction (const std::string &action) const
Convert a direction action (UP, DOWN etc) to a delta vector.
cata::optional< tripoint > get_coordinates (const catacurses::window &capture_win_)
Get the coordinates associated with the last mouse click (if any).
void register_directions ()
void register_updown ()
void register_leftright ()
void register_cardinal ()
action_id display_menu (bool permit_execute_action=false)
Displays the possible actions in the current context and their keybindings.
input_event get_raw_input ()
Temporary method to retrieve the raw input received, so that input_contexts can be used in screens where not all possible actions have been defined in keybindings.json yet.
std::string get_action_name (const std::string &action_id) const
Get the human-readable name for an action.
std::string press_x (const std::string &action_id) const
std::string press_x (const std::string &action_id, const std::string &key_bound, const std::string &key_unbound) const
std::string press_x (const std::string &action_id, const std::string &key_bound_pre, const std::string &key_bound_suf, const std::string &key_unbound) const
std::vector< char > keys_bound_to (const std::string &action_descriptor, bool restrict_to_printable=true) const
Keys (and only keys, other input types are not included) that trigger the given action.
std::string key_bound_to (const std::string &action_descriptor, size_t index=0, bool restrict_to_printable=true) const
void set_edittext (const std::string &s)
Get/Set edittext to display IME unspecified string.
std::string get_edittext ()
void set_iso (bool mode=true)
void set_timeout (int val)
Sets input polling timeout as appropriate for the current interface system.
void reset_timeout ()
const std::string & input_to_action (const input_event &inp) const
std::vector< std::string > get_registered_actions_copy () const
Static Public Attributes
static const input_event_filter disallow_lower_case
static const input_event_filter allow_all_keys
Private Member Functions
bool action_uses_input (const std::string &action_id, const input_event &event) const
Returns whether action uses the specified input.
std::string get_conflicts (const input_event &event) const
Return a user presentable list of actions that conflict with the proposed keybinding.
void clear_conflicting_keybindings (const input_event &event)
Clear an input_event from all conflicting keybindings that are registered by this input_context.
std::vector< std::string > filter_strings_by_phrase (const std::vector< std::string > &strings, const std::string &phrase) const
Filter a vector of strings by a phrase, returning only strings that contain the phrase.
Private Attributes
std::vector< std::string > registered_actions
std::string edittext
bool registered_any_input
std::string category
point coordinate
bool coordinate_input_received
bool handling_coordinate_input
input_event next_action
bool iso_mode = false
int timeout = -1
std::map< std::string, translation > action_name_overrides
When registering for actions within an input_context, callers can specify a custom action name that will override the action's normal name.
Detailed Description
Represents a context in which a set of actions can be performed.
This class is responsible for registering possible actions (traditionally keypresses), handling input, and yielding the correct action string descriptors for given input.
This turns this class into an abstraction method between actual input(keyboard, gamepad etc.) and game.
Definition at line 385 of file input.h.
Member Typedef Documentation
input_event_filter
using input_context::input_event_filter = std::function<bool(const input_event &)>
Definition at line 543 of file input.h.
Constructor & Destructor Documentation
input_context() [1/2]
input_context::input_context () inline
Definition at line 393 of file input.h.
                        : registered_any_input( false ), category( "default" ),
            coordinate_input_received( false ), handling_coordinate_input( false ) {
#if defined(__ANDROID__)
            input_context_stack.push_back( this );
            allow_text_entry = false;
#endif
        }
input_context() [2/2]
input_context::input_context (const std::string & category) inline
Definition at line 402 of file input.h.
                                                   : registered_any_input( false ),
            category( category ), coordinate_input_received( false ), handling_coordinate_input( false ) {
#if defined(__ANDROID__)
            input_context_stack.push_back( this );
            allow_text_entry = false;
#endif
        }
Member Function Documentation
action_uses_input()
bool input_context::action_uses_input (const std::string & action_id, const input_event & event) const private
Returns whether action uses the specified input.
Definition at line 589 of file input.cpp.
{
    const auto &events = inp_mngr.get_action_attributes( action_id, category ).input_events;
    return std::find( events.begin(), events.end(), event ) != events.end();
}
References category, detail::find(), input_manager::get_action_attributes(), inp_mngr, and action_attributes::input_events.
Referenced by display_menu().
clear_conflicting_keybindings()
void input_context::clear_conflicting_keybindings (const input_event & event) private
Clear an input_event from all conflicting keybindings that are registered by this input_context.
Parameters
event The input event to be cleared from conflicting keybindings.
Definition at line 604 of file input.cpp.
{
    // The default context is always included to cover cases where the same
    // keybinding exists for the same action in both the global and local
    // contexts.
    input_manager::t_actions &default_actions = inp_mngr.action_contexts[default_context_id];
    input_manager::t_actions &category_actions = inp_mngr.action_contexts[category];
    for( std::vector<std::string>::const_iterator registered_action = registered_actions.begin();
         registered_action != registered_actions.end();
         ++registered_action ) {
        input_manager::t_actions::iterator default_action = default_actions.find( *registered_action );
        input_manager::t_actions::iterator category_action = category_actions.find( *registered_action );
        if( default_action != default_actions.end() ) {
            std::vector<input_event> &events = default_action->second.input_events;
            events.erase( std::remove( events.begin(), events.end(), event ), events.end() );
        }
        if( category_action != category_actions.end() ) {
            std::vector<input_event> &events = category_action->second.input_events;
            events.erase( std::remove( events.begin(), events.end(), event ), events.end() );
        }
    }
}
References input_manager::action_contexts, category, default_context_id(), inp_mngr, and registered_actions.
Referenced by display_menu().
describe_key_and_name()
std::string input_context::describe_key_and_name (const std::string & action_descriptor, const input_event_filter & evt_filter = allow_all_keys) const
Equivalent to get_desc(act, get_action_name(act), filter)
Definition at line 848 of file input.cpp.
{
    return get_desc( action_descriptor, get_action_name( action_descriptor ), evt_filter );
}
References get_action_name(), and get_desc().
Referenced by editmap::edit(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_mapgen(), editmap::mapgen_preview(), editmap::mapgen_retarget(), computer_session::query_ynq(), and editmap::select_shape().
display_menu()
action_id input_context::display_menu (bool permit_execute_action = false)
Displays the possible actions in the current context and their keybindings.
Parameters
permit_execute_action If true the function allows the user to specify an action to execute
Returns
action_id of any action the user specified to execute, or ACTION_NULL if none
Definition at line 999 of file input.cpp.
{
    action_id action_to_execute = ACTION_NULL;
    // Shamelessly stolen from help.cpp
    input_context ctxt( "HELP_KEYBINDINGS" );
    ctxt.register_action( "UP", to_translation( "Scroll up" ) );
    ctxt.register_action( "DOWN", to_translation( "Scroll down" ) );
    ctxt.register_action( "PAGE_DOWN" );
    ctxt.register_action( "PAGE_UP" );
    ctxt.register_action( "REMOVE" );
    ctxt.register_action( "ADD_LOCAL" );
    ctxt.register_action( "ADD_GLOBAL" );
    ctxt.register_action( "EXECUTE" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "ANY_INPUT" );
    if( category != "HELP_KEYBINDINGS" ) {
        // avoiding inception!
        ctxt.register_action( "HELP_KEYBINDINGS" );
    }
    std::string hotkeys = ctxt.get_available_single_char_hotkeys( display_help_hotkeys );
    ui_adaptor ui;
    int width = 0;
    int height = 0;
    catacurses::window w_help;
    size_t display_height = 0;
    size_t legwidth = 0;
    string_input_popup spopup;
    const auto recalc_size = [&]( ui_adaptor & ui ) {
        int maxwidth = std::max( FULL_SCREEN_WIDTH, TERMX );
        width = min( 80, maxwidth );
        int maxheight = std::max( FULL_SCREEN_HEIGHT, TERMY );
        height = min( maxheight, static_cast<int>( hotkeys.size() ) + LEGEND_HEIGHT + BORDER_SPACE );
        w_help = catacurses::newwin( height - 2, width - 2,
                                     point( maxwidth / 2 - width / 2, maxheight / 2 - height / 2 ) );
        // height of the area usable for display of keybindings, excludes headers & borders
        display_height = height - LEGEND_HEIGHT - BORDER_SPACE; // -2 for the border
        // width of the legend
        legwidth = width - 4 - BORDER_SPACE;
        spopup.window( w_help, point( 4, 8 ), legwidth )
        .max_length( legwidth )
        .context( ctxt );
        ui.position_from_window( w_help );
    };
    recalc_size( ui );
    ui.on_screen_resize( recalc_size );
    // has the user changed something?
    bool changed = false;
    // keybindings before the user changed anything.
    input_manager::t_action_contexts old_action_contexts( inp_mngr.action_contexts );
    // current status: adding/removing/executing/showing keybindings
    enum { s_remove, s_add, s_add_global, s_execute, s_show } status = s_show;
    // copy of registered_actions, but without the ANY_INPUT and COORDINATE, which should not be shown
    std::vector<std::string> org_registered_actions( registered_actions );
    org_registered_actions.erase( std::remove_if( org_registered_actions.begin(),
                                  org_registered_actions.end(),
    []( const std::string & a ) {
        return a == ANY_INPUT || a == COORDINATE;
    } ), org_registered_actions.end() );
    // colors of the keybindings
    static const nc_color global_key = c_light_gray;
    static const nc_color local_key = c_light_green;
    static const nc_color unbound_key = c_light_red;
    // (vertical) scroll offset
    size_t scroll_offset = 0;
    // keybindings help
    std::string legend;
    legend += colorize( _( "Unbound keys" ), unbound_key ) + "\n";
    legend += colorize( _( "Keybinding active only on this screen" ), local_key ) + "\n";
    legend += colorize( _( "Keybinding active globally" ), global_key ) + "\n";
    legend += _( "Press - to remove keybinding\nPress + to add local keybinding\nPress = to add global keybinding\n" );
    if( permit_execute_action ) {
        legend += _( "Press . to execute action\n" );
    }
    std::vector<std::string> filtered_registered_actions = org_registered_actions;
    std::string filter_phrase;
    std::string action;
    int raw_input_char = 0;
    const auto redraw = [&]( const ui_adaptor & ) {
        werase( w_help );
        draw_border( w_help, BORDER_COLOR, _( "Keybindings" ), c_light_red );
        draw_scrollbar( w_help, scroll_offset, display_height,
                        filtered_registered_actions.size(), point( 0, 10 ), c_white, true );
        fold_and_print( w_help, point( 2, 1 ), legwidth, c_white, legend );
        for( size_t i = 0; i + scroll_offset < filtered_registered_actions.size() &&
             i < display_height; i++ ) {
            const std::string &action_id = filtered_registered_actions[i + scroll_offset];
            bool overwrite_default;
            const action_attributes &attributes = inp_mngr.get_action_attributes( action_id, category,
                                                  &overwrite_default );
            char invlet;
            if( i < hotkeys.size() ) {
                invlet = hotkeys[i];
            } else {
                invlet = ' ';
            }
            if( status == s_add_global && overwrite_default ) {
                // We're trying to add a global, but this action has a local
                // defined, so gray out the invlet.
                mvwprintz( w_help, point( 2, i + 10 ), c_dark_gray, "%c ", invlet );
            } else if( status == s_add || status == s_add_global ) {
                mvwprintz( w_help, point( 2, i + 10 ), c_light_blue, "%c ", invlet );
            } else if( status == s_remove ) {
                mvwprintz( w_help, point( 2, i + 10 ), c_light_blue, "%c ", invlet );
            } else if( status == s_execute ) {
                mvwprintz( w_help, point( 2, i + 10 ), c_white, "%c ", invlet );
            } else {
                mvwprintz( w_help, point( 2, i + 10 ), c_blue, "  " );
            }
            nc_color col;
            if( attributes.input_events.empty() ) {
                col = unbound_key;
            } else if( overwrite_default ) {
                col = local_key;
            } else {
                col = global_key;
            }
            mvwprintz( w_help, point( 4, i + 10 ), col, "%s:", get_action_name( action_id ) );
            mvwprintz( w_help, point( 52, i + 10 ), col, "%s", get_desc( action_id ) );
        }
        // spopup.query_string() will call wnoutrefresh( w_help )
        spopup.text( filter_phrase );
        spopup.query_string( false, true );
    };
    ui.on_redraw( redraw );
    // do not switch IME mode now, but restore previous mode on return
    ime_sentry sentry( ime_sentry::keep );
    while( true ) {
        ui_manager::redraw();
        if( status == s_show ) {
            filter_phrase = spopup.query_string( false );
            action = ctxt.input_to_action( ctxt.get_raw_input() );
        } else {
            action = ctxt.handle_input();
        }
        raw_input_char = ctxt.get_raw_input().get_first_input();
        filtered_registered_actions = filter_strings_by_phrase( org_registered_actions, filter_phrase );
        if( scroll_offset > filtered_registered_actions.size() ) {
            scroll_offset = 0;
        }
        if( filtered_registered_actions.empty() && action != "QUIT" ) {
            continue;
        }
        // In addition to the modifiable hotkeys, we also check for hardcoded
        // keys, e.g. '+', '-', '=', '.' in order to prevent the user from
        // entering an unrecoverable state.
        if( action == "ADD_LOCAL" || raw_input_char == '+' ) {
            status = s_add;
        } else if( action == "ADD_GLOBAL" || raw_input_char == '=' ) {
            status = s_add_global;
        } else if( action == "REMOVE" || raw_input_char == '-' ) {
            status = s_remove;
        } else if( ( action == "EXECUTE" || raw_input_char == '.' ) && permit_execute_action ) {
            status = s_execute;
        } else if( action == "ANY_INPUT" ) {
            const size_t hotkey_index = hotkeys.find_first_of( raw_input_char );
            if( hotkey_index == std::string::npos ) {
                continue;
            }
            const size_t action_index = hotkey_index + scroll_offset;
            if( action_index >= filtered_registered_actions.size() ) {
                continue;
            }
            const std::string &action_id = filtered_registered_actions[action_index];
            // Check if this entry is local or global.
            bool is_local = false;
            const action_attributes &actions = inp_mngr.get_action_attributes( action_id, category, &is_local );
            bool is_empty = actions.input_events.empty();
            const std::string name = get_action_name( action_id );
            // We don't want to completely delete a global context entry.
            // Only attempt removal for a local context, or when there's
            // bindings for the default context.
            if( status == s_remove && ( is_local || !is_empty ) ) {
                if( !get_option<bool>( "QUERY_KEYBIND_REMOVAL" ) || query_yn( is_local &&
                        is_empty ? _( "Reset to global bindings for %s?" ) : _( "Clear keys for %s?" ), name ) ) {
                    // If it's global, reset the global actions.
                    std::string category_to_access = category;
                    if( !is_local ) {
                        category_to_access = default_context_id;
                    }
                    inp_mngr.remove_input_for_action( action_id, category_to_access );
                    changed = true;
                }
            } else if( status == s_add_global && is_local ) {
                // Disallow adding global actions to an action that already has a local defined.
                popup( _( "There are already local keybindings defined for this action, please remove them first." ) );
            } else if( status == s_add || status == s_add_global ) {
                const input_event new_event = query_popup()
                                              .message( _( "New key for %s" ), name )
                                              .allow_anykey( true )
                                              .query()
                                              .evt;
                if( action_uses_input( action_id, new_event ) ) {
                    popup_getkey( _( "This key is already used for %s." ), name );
                    status = s_show;
                    continue;
                }
                const std::string conflicts = get_conflicts( new_event );
                const bool has_conflicts = !conflicts.empty();
                bool resolve_conflicts = false;
                if( has_conflicts ) {
                    resolve_conflicts = query_yn(
                                            _( "This key conflicts with %s. Remove this key from the conflicting command(s), and continue?" ),
                                            conflicts.c_str() );
                }
                if( !has_conflicts || resolve_conflicts ) {
                    if( resolve_conflicts ) {
                        clear_conflicting_keybindings( new_event );
                    }
                    // We might be adding a local or global action.
                    std::string category_to_access = category;
                    if( status == s_add_global ) {
                        category_to_access = default_context_id;
                    }
                    inp_mngr.add_input_for_action( action_id, category_to_access, new_event );
                    changed = true;
                }
            } else if( status == s_execute && permit_execute_action ) {
                action_to_execute = look_up_action( action_id );
                break;
            }
            status = s_show;
        } else if( action == "DOWN" ) {
            if( filtered_registered_actions.size() > display_height &&
                scroll_offset < filtered_registered_actions.size() - display_height ) {
                scroll_offset++;
            }
        } else if( action == "UP" ) {
            if( scroll_offset > 0 ) {
                scroll_offset--;
            }
        } else if( action == "PAGE_DOWN" ) {
            if( scroll_offset + display_height < filtered_registered_actions.size() ) {
                scroll_offset += std::min( display_height, filtered_registered_actions.size() -
                                           display_height - scroll_offset );
            } else if( filtered_registered_actions.size() > display_height ) {
                scroll_offset = 0;
            }
        } else if( action == "PAGE_UP" ) {
            if( scroll_offset >= display_height ) {
                scroll_offset -= display_height;
            } else if( scroll_offset > 0 ) {
                scroll_offset = 0;
            } else if( filtered_registered_actions.size() > display_height ) {
                scroll_offset = filtered_registered_actions.size() - display_height;
            }
        } else if( action == "QUIT" ) {
            if( status != s_show ) {
                status = s_show;
            } else {
                break;
            }
        } else if( action == "HELP_KEYBINDINGS" ) {
            // update available hotkeys in case they've changed
            hotkeys = ctxt.get_available_single_char_hotkeys( display_help_hotkeys );
        }
    }
    if( changed && query_yn( _( "Save changes?" ) ) ) {
        try {
            inp_mngr.save();
            get_help().load();
        } catch( std::exception &err ) {
            popup( _( "saving keybindings failed: %s" ), err.what() );
        }
    } else if( changed ) {
        inp_mngr.action_contexts.swap( old_action_contexts );
    }
    return action_to_execute;
}
References _, a, action, input_manager::action_contexts, ACTION_NULL, action_uses_input(), input_manager::add_input_for_action(), query_popup::allow_anykey(), BORDER_COLOR, BORDER_SPACE, c_blue, c_dark_gray, c_light_blue, c_light_gray, c_light_green, c_light_red, c_white, category, clear_conflicting_keybindings(), colorize(), string_input_popup::context(), default_context_id(), display_help_hotkeys, draw_border(), draw_scrollbar(), query_popup::result::evt, filter_strings_by_phrase(), fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_manager::get_action_attributes(), get_action_name(), get_available_single_char_hotkeys(), get_conflicts(), get_desc(), input_event::get_first_input(), get_help(), get_raw_input(), handle_input(), inp_mngr, action_attributes::input_events, input_to_action(), ime_sentry::keep, LEGEND_HEIGHT, help::load(), look_up_action(), string_input_popup::max_length(), query_popup::message(), mvwprintz(), om_direction::name(), catacurses::newwin(), popup(), popup_getkey(), query_popup::query(), string_input_popup::query_string(), query_yn(), ui_manager::redraw(), register_action(), registered_actions, input_manager::remove_input_for_action(), input_manager::save(), TERMX, TERMY, string_input_popup::text(), to_translation(), catacurses::werase(), and string_input_popup::window().
Referenced by game::handle_action(), handle_input(), and main_menu::opening_screen().
filter_strings_by_phrase()
std::vector< std::string > input_context::filter_strings_by_phrase (const std::vector< std::string > & strings, const std::string & phrase) const private
Filter a vector of strings by a phrase, returning only strings that contain the phrase.
Parameters
strings The vector of strings to filter
phrase The phrase to search within each of the given strings
Returns
A vector of the filtered strings
Definition at line 1434 of file input.cpp.
{
    std::vector<std::string> filtered_strings;
    for( auto &str : strings ) {
        if( lcmatch( remove_color_tags( get_action_name( str ) ), phrase ) ) {
            filtered_strings.push_back( str );
        }
    }
    return filtered_strings;
}
References get_action_name(), lcmatch(), and remove_color_tags().
Referenced by display_menu().
get_action_name()
std::string input_context::get_action_name (const std::string & action_id) const
Get the human-readable name for an action.
Definition at line 1361 of file input.cpp.
{
    // 1) Check action name overrides specific to this input_context
    const auto action_name_override =
        action_name_overrides.find( action_id );
    if( action_name_override != action_name_overrides.end() ) {
        return action_name_override->second.translated();
    }
    // 2) Check if the hotkey has a name
    const action_attributes &attributes = inp_mngr.get_action_attributes( action_id, category );
    if( !attributes.name.empty() ) {
        return attributes.name.translated();
    }
    // 3) If the hotkey has no name, the user has created a local hotkey in
    // this context that is masking the global hotkey. Fallback to the global
    // hotkey's name.
    const action_attributes &default_attributes = inp_mngr.get_action_attributes( action_id,
            default_context_id );
    if( !default_attributes.name.empty() ) {
        return default_attributes.name.translated();
    }
    // 4) Unable to find suitable name. Keybindings configuration likely borked
    return action_id;
}
References action_name_overrides, category, default_context_id(), translation::empty(), input_manager::get_action_attributes(), inp_mngr, action_attributes::name, and translation::translated().
Referenced by describe_key_and_name(), display_menu(), overmap_ui::draw_om_sidebar(), filter_strings_by_phrase(), query_popup::fold_query(), handle_main_menu(), game::look_around(), and examine_item_menu::run().
get_available_single_char_hotkeys()
std::string input_context::get_available_single_char_hotkeys (std::string requested_keys = "abcdefghijkpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-=:;'\",./<>?!@#$%^&*()_+[]\\{}|`~")
Get the set of available single character keyboard keys that do not conflict with any registered hotkeys.
The result will only include characters from the requested_keys parameter that have no conflicts i.e. the set difference requested_keys - conflicts.
Parameters
requested_keys The set of single character hotkeys to potentially use. Defaults to all printable ascii.
Returns
Returns the set of non-conflicting, single character keyboard keys suitable for use as hotkeys.
Definition at line 721 of file input.cpp.
{
    for( std::vector<std::string>::const_iterator registered_action = registered_actions.begin();
         registered_action != registered_actions.end();
         ++registered_action ) {
        const std::vector<input_event> &events = inp_mngr.get_input_for_action( *registered_action,
                category );
        for( const auto &events_event : events ) {
            // Only consider keyboard events without modifiers
            if( events_event.type == CATA_INPUT_KEYBOARD && events_event.modifiers.empty() ) {
                requested_keys.erase( std::remove_if( requested_keys.begin(), requested_keys.end(),
                                                      ContainsPredicate<std::vector<int>, char>(
                                                              events_event.sequence ) ),
                                      requested_keys.end() );
            }
        }
    }
    return requested_keys;
}
References CATA_INPUT_KEYBOARD, category, input_manager::get_input_for_action(), inp_mngr, and registered_actions.
Referenced by display_menu(), pickup::pick_up(), and uilist::query().
get_conflicts()
std::string input_context::get_conflicts (const input_event & event) const private
Return a user presentable list of actions that conflict with the proposed keybinding.
Returns an empty string if nothing conflicts.
Definition at line 596 of file input.cpp.
{
    return enumerate_as_string( registered_actions.begin(), registered_actions.end(),
    [ this, &event ]( const std::string & action ) {
        return action_uses_input( action, event ) ? get_action_name( action ) : std::string();
    } );
}
References action, enumerate_as_string(), and registered_actions.
Referenced by display_menu().
get_coordinates()
cata::optional< tripoint > input_context::get_coordinates (const catacurses::window & capture_win_)
Get the coordinates associated with the last mouse click (if any).
TODO: This right now is more or less specific to the map window, and returns the absolute map coordinate. Eventually this should be made more flexible.
Definition at line 1338 of file input.cpp.
{
    if( !coordinate_input_received ) {
        return cata::nullopt;
    }
    const point view_size( getmaxx( capture_win ), getmaxy( capture_win ) );
    const point win_min( getbegx( capture_win ),
                         getbegy( capture_win ) );
    const half_open_rectangle<point> win_bounds( win_min, win_min + view_size );
    if( !win_bounds.contains( coordinate ) ) {
        return cata::nullopt;
    }
    point view_offset;
    if( capture_win == g->w_terrain ) {
        view_offset = g->ter_view_p.xy();
    }
    const point p = view_offset - ( view_size / 2 - coordinate );
    return tripoint( p, g->get_levz() );
}
References half_open_rectangle< Point, >::contains(), coordinate, coordinate_input_received, g, catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), and cata::nullopt.
Referenced by overmap_ui::display(), game::handle_action(), target_ui::handle_cursor_movement(), game::handle_mouseview(), and game::look_around().
get_desc() [1/2]
std::string input_context::get_desc (const std::string & action_descriptor, const std::string & text, const input_event_filter & evt_filter = allow_all_keys) const
Get a description based on text.
If a bound key for action_descriptor satisfying evt_filter is contained in text, surround the key with brackets and change the case if necessary (e.g. "(Y)es"). Otherwise prefix text with description of the first bound key satisfying evt_filter, surrounded in square brackets (e.g "[RETURN] Yes").
Parameters
action_descriptor The action descriptor for which to return a description of the bound keys.
text The base text for action description
evt_filter Only keys satisfying this function will be considered
Definition at line 808 of file input.cpp.
{
    if( action_descriptor == "ANY_INPUT" ) {
        // \u00A0 is the non-breaking space
        //~ keybinding description for anykey
        return string_format( pgettext( "keybinding", "[any]\u00A0%s" ), text );
    }
    const auto &events = inp_mngr.get_input_for_action( action_descriptor, category );
    bool na = true;
    for( const auto &evt : events ) {
        if( evt_filter( evt ) &&
            // Only display gamepad buttons if a gamepad is available.
            ( gamepad_available() || evt.type != CATA_INPUT_GAMEPAD ) ) {
            na = false;
            if( evt.type == CATA_INPUT_KEYBOARD && evt.sequence.size() == 1 ) {
                const int ch = evt.get_first_input();
                const std::string key = utf32_to_utf8( ch );
                const auto pos = ci_find_substr( text, key );
                if( ch > ' ' && ch <= '~' && pos >= 0 ) {
                    return text.substr( 0, pos ) + "(" + key + ")" + text.substr( pos + key.size() );
                }
            }
        }
    }
    if( na ) {
        //~ keybinding description for unbound or disabled keys
        return string_format( pgettext( "keybinding", "[n/a]\u00A0%s" ), text );
    } else {
        //~ keybinding description for bound keys
        return string_format( pgettext( "keybinding", "[%s]\u00A0%s" ),
                              get_desc( action_descriptor, 1, evt_filter ), text );
    }
}
References CATA_INPUT_GAMEPAD, CATA_INPUT_KEYBOARD, category, ci_find_substr(), gamepad_available(), get_desc(), input_manager::get_input_for_action(), inp_mngr, pgettext(), string_format(), and utf32_to_utf8().
get_desc() [2/2]
std::string input_context::get_desc (const std::string & action_descriptor, unsigned int max_limit = 0, const input_event_filter & evt_filter = allow_all_keys) const
Get a description text for the key/other input method associated with the given action.
If there are multiple bound keys, no more than max_limit will be described in the result. In addition, only keys satisfying evt_filter will be described.
Parameters
action_descriptor The action descriptor for which to return a description of the bound keys.
max_limit No more than max_limit bound keys will be described in the returned description. A value of 0 indicates no limit.
evt_filter Only keys satisfying this function will be described.
Definition at line 756 of file input.cpp.
{
    if( action_descriptor == "ANY_INPUT" ) {
        return "(*)"; // * for wildcard
    }
    bool is_local = false;
    const std::vector<input_event> &events = inp_mngr.get_input_for_action( action_descriptor,
            category, &is_local );
    if( events.empty() ) {
        return is_local ? _( "Unbound locally!" ) : _( "Unbound globally!" );
    }
    std::vector<input_event> inputs_to_show;
    for( auto &events_i : events ) {
        const input_event &event = events_i;
        if( evt_filter( event ) &&
            // Only display gamepad buttons if a gamepad is available.
            ( gamepad_available() || event.type != CATA_INPUT_GAMEPAD ) ) {
            inputs_to_show.push_back( event );
        }
        if( max_limit > 0 && inputs_to_show.size() == max_limit ) {
            break;
        }
    }
    if( inputs_to_show.empty() ) {
        return pgettext( "keybinding", "Disabled" );
    }
    std::string rval;
    for( size_t i = 0; i < inputs_to_show.size(); ++i ) {
        for( size_t j = 0; j < inputs_to_show[i].sequence.size(); ++j ) {
            rval += inp_mngr.get_keyname( inputs_to_show[i].sequence[j], inputs_to_show[i].type );
        }
        // We're generating a list separated by "," and "or"
        if( i + 2 == inputs_to_show.size() ) {
            rval += _( " or " );
        } else if( i + 1 < inputs_to_show.size() ) {
            rval += ", ";
        }
    }
    return rval;
}
References _, CATA_INPUT_GAMEPAD, category, gamepad_available(), input_manager::get_input_for_action(), input_manager::get_keyname(), inp_mngr, pgettext(), and type.
Referenced by defense_game::caravan(), choose_ma_style(), describe_key_and_name(), display_menu(), draw_bionics_titlebar(), target_ui::draw_controls_list(), inventory_selector::draw_footer(), target_ui::draw_help_notice(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), draw_sorting_indicator(), draw_tip(), editmap::edit(), editmap::edit_fld(), inventory_compare_selector::execute(), inventory_iuse_selector::execute(), inventory_drop_selector::execute(), game::extended_description(), query_popup::fold_query(), get_desc(), game::get_player_input(), basecamp::job_assignment_ui(), game::look_around(), editmap::mapgen_preview(), character_martial_arts::pick_style(), pickup::pick_up(), overmap_ui::place_ter_or_special(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), debug_menu::effect_select_callback::refresh(), overmap_ui::search(), set_description(), set_profession(), set_stats(), robot_finds_kitten::show(), panel_manager::show_adm(), show_armor_layers_ui(), show_bionics_ui(), diary::show_diary_ui(), worldfactory::show_modselection_window(), show_mutations_titlebar(), worldfactory::show_worldgen_tab_confirm(), trading_window::update_win(), debug_menu::wishitem(), debug_menu::wishmonster(), and basecamp::worker_assignment_ui().
get_direction()
cata::optional< tripoint > input_context::get_direction (const std::string & action) const
Convert a direction action (UP, DOWN etc) to a delta vector.
Returns
If the action is a movement action (UP, DOWN, ...), the delta vector associated with it. Otherwise returns an empty value. The returned vector will always have a z component of 0.
Definition at line 961 of file input.cpp.
{
    static const auto noop = static_cast<tripoint( * )( tripoint )>( []( tripoint p ) {
        return p;
    } );
    static const auto rotate = static_cast<tripoint( * )( tripoint )>( []( tripoint p ) {
        rotate_direction_cw( p.x, p.y );
        return p;
    } );
    const auto transform = iso_mode && tile_iso && use_tiles ? rotate : noop;
    if( action == "UP" ) {
        return transform( tripoint_north );
    } else if( action == "DOWN" ) {
        return transform( tripoint_south );
    } else if( action == "LEFT" ) {
        return transform( tripoint_west );
    } else if( action == "RIGHT" ) {
        return transform( tripoint_east );
    } else if( action == "LEFTUP" ) {
        return transform( tripoint_north_west );
    } else if( action == "RIGHTUP" ) {
        return transform( tripoint_north_east );
    } else if( action == "LEFTDOWN" ) {
        return transform( tripoint_south_west );
    } else if( action == "RIGHTDOWN" ) {
        return transform( tripoint_south_east );
    } else {
        return cata::nullopt;
    }
}
References action, iso_mode, cata::nullopt, rotate(), rotate_direction_cw(), tile_iso, iexamine::transform(), tripoint_east, tripoint_north, tripoint_north_east, tripoint_north_west, tripoint_south, tripoint_south_east, tripoint_south_west, tripoint_west, and use_tiles.
Referenced by choose_direction(), overmap_ui::display(), veh_interact::do_main_loop(), editmap::eget_direction(), target_ui::handle_cursor_movement(), game::look_around(), editmap::mapgen_retarget(), overmap_ui::place_ter_or_special(), lightson_game::start_game(), minesweeper_game::start_game(), and sokoban_game::start_game().
get_edittext()
std::string input_context::get_edittext ()
Definition at line 1453 of file input.cpp.
{
    return edittext;
}
References edittext.
Referenced by string_input_popup::query_string().
get_raw_input()
input_event input_context::get_raw_input ()
Temporary method to retrieve the raw input received, so that input_contexts can be used in screens where not all possible actions have been defined in keybindings.json yet.
Definition at line 1299 of file input.cpp.
{
    return next_action;
}
References next_action.
Referenced by help::display_help(), display_menu(), draw_item_info(), inventory_selector::get_input(), game::handle_action(), uilist::inputfilter(), game::mouse_edge_scrolling(), main_menu::new_character_tab(), main_menu::opening_screen(), veh_interact::overview(), trading_window::perform_trade(), robot_finds_kitten::process_input(), uilist::query(), query_popup::query_once(), string_input_popup::query_string(), computer_session::query_ynq(), show_bionics_ui(), trading_window::show_item_data(), detail::show_mutations_ui_internal(), worldfactory::show_worldgen_tab_confirm(), and main_menu::world_tab().
get_registered_actions_copy()
std::vector< std::string > input_context::get_registered_actions_copy () const inline
Definition at line 742 of file input.h.
{
            return registered_actions;
        }
References registered_actions.
Referenced by inventory_selector::action_bound_to_key(), and inventory_selector::all_bound_keys().
handle_input() [1/2]
const std::string & input_context::handle_input ()
Handles input and returns the next action in the queue.
This internally calls getch() or whatever other input method is available(e.g. gamepad).
If the action is mouse input, returns "MOUSE".
Returns
One of the input actions formerly registered with register_action(), or "ERROR" if an error happened.
Definition at line 854 of file input.cpp.
{
    return handle_input( timeout );
}
References handle_input(), and timeout.
Referenced by defense_game::caravan(), choose_direction(), game_menus::inv::compare(), Character::conduct_blood_analysis(), game::disp_NPCs(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), help::display_help(), display_menu(), veh_interact::do_install(), veh_interact::do_main_loop(), veh_interact::do_remove(), veh_interact::do_repair(), draw_item_info(), editmap::edit(), game::extended_description(), inventory_selector::get_input(), handle_input(), game::handle_key_blocking_activity(), game::handle_mouseview(), handle_player_display_action(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_missions(), game::list_monsters(), main_menu::load_character_tab(), game::look_around(), editmap::mapgen_retarget(), main_menu::new_character_tab(), main_menu::opening_screen(), veh_interact::overview(), trading_window::perform_trade(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), robot_finds_kitten::process_input(), uilist::query(), query_popup::query_once(), string_input_popup::query_string(), computer_session::query_ynq(), target_ui::run(), examine_item_menu::run(), scrollable_text(), overmap_ui::search(), select_crafting_recipe(), editmap::select_shape(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), defense_game::setup(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), show_armor_layers_ui(), show_bionics_ui(), diary::show_diary_ui(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), detail::show_mutations_ui_internal(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), basecamp::worker_assignment_ui(), main_menu::world_tab(), and game::zones_manager().
handle_input() [2/2]
const std::string & input_context::handle_input (int timeout)
Definition at line 859 of file input.cpp.
{
    const auto old_timeout = inp_mngr.get_timeout();
    if( timeout >= 0 ) {
        inp_mngr.set_timeout( timeout );
    }
    next_action.type = CATA_INPUT_ERROR;
    const std::string *result = &CATA_ERROR;
    while( true ) {
        next_action = inp_mngr.get_input_event();
        if( next_action.type == CATA_INPUT_TIMEOUT ) {
            result = &TIMEOUT;
            break;
        }
        const std::string &action = input_to_action( next_action );
        // Special help action
        if( action == "HELP_KEYBINDINGS" ) {
            inp_mngr.reset_timeout();
            display_menu();
            inp_mngr.set_timeout( timeout );
            result = &HELP_KEYBINDINGS;
            break;
        }
        if( next_action.type == CATA_INPUT_MOUSE ) {
            if( !handling_coordinate_input && action == CATA_ERROR ) {
                continue; // Ignore this mouse input.
            }
            coordinate_input_received = true;
            coordinate = next_action.mouse_pos;
        } else {
            coordinate_input_received = false;
        }
        if( action != CATA_ERROR ) {
            result = &action;
            break;
        }
        // If we registered to receive any input, return ANY_INPUT
        // to signify that an unregistered key was pressed.
        if( registered_any_input ) {
            result = &ANY_INPUT;
            break;
        }
        // If it's an invalid key, just keep looping until the user
        // enters something proper.
    }
    inp_mngr.set_timeout( old_timeout );
    return *result;
}
References action, ANY_INPUT, CATA_ERROR, CATA_INPUT_ERROR, CATA_INPUT_MOUSE, CATA_INPUT_TIMEOUT, coordinate, coordinate_input_received, display_menu(), input_manager::get_input_event(), input_manager::get_timeout(), handling_coordinate_input, HELP_KEYBINDINGS, inp_mngr, input_to_action(), input_event::mouse_pos, next_action, registered_any_input, input_manager::reset_timeout(), input_manager::set_timeout(), TIMEOUT, timeout, and input_event::type.
input_to_action()
const std::string & input_context::input_to_action (const input_event & inp) const
Definition at line 634 of file input.cpp.
{
    for( auto &elem : registered_actions ) {
        const std::string &action = elem;
        const std::vector<input_event> &check_inp = inp_mngr.get_input_for_action( action, category );
        // Does this action have our queried input event in its keybindings?
        for( auto &check_inp_i : check_inp ) {
            if( check_inp_i == inp ) {
                return action;
            }
        }
    }
    return CATA_ERROR;
}
References action, CATA_ERROR, category, input_manager::get_input_for_action(), inp_mngr, and registered_actions.
Referenced by action_from_key(), display_menu(), handle_input(), uilist::inputfilter(), debug_menu::effect_select_callback::key(), debug_menu::effect_edit_callback::key(), ma_style_callback::key(), actmenu_cb::key(), and overmap_ui::map_notes_callback::key().
key_bound_to()
std::string input_context::key_bound_to (const std::string & action_descriptor, size_t index = 0, bool restrict_to_printable = true) const
Definition at line 714 of file input.cpp.
{
    const auto bound_keys = keys_bound_to( action_descriptor, restrict_to_printable );
    return bound_keys.size() > index ? std::string( 1, bound_keys[index] ) : "";
}
References keys_bound_to().
Referenced by examine_item_menu::run(), and overmap_ui::show_notes_manager().
keys_bound_to()
std::vector< char > input_context::keys_bound_to (const std::string & action_descriptor, bool restrict_to_printable = true) const
Keys (and only keys, other input types are not included) that trigger the given action.
Parameters
action_descriptor The action descriptor for which to get the bound keys.
restrict_to_printable If true the function returns the bound keys only if they are printable. If false, all keys (whether they are printable or not) are returned.
Returns
All keys bound to the given action descriptor.
Definition at line 695 of file input.cpp.
{
    std::vector<char> result;
    const std::vector<input_event> &events = inp_mngr.get_input_for_action( action_descriptor,
            category );
    for( const auto &events_event : events ) {
        // Ignore multi-key input and non-keyboard input
        // TODO: fix for Unicode.
        if( events_event.type == CATA_INPUT_KEYBOARD && events_event.sequence.size() == 1 ) {
            if( !restrict_to_printable || ( events_event.sequence.front() < 0xFF &&
                                            isprint( events_event.sequence.front() ) ) ) {
                result.push_back( static_cast<char>( events_event.sequence.front() ) );
            }
        }
    }
    return result;
}
References CATA_INPUT_KEYBOARD, category, input_manager::get_input_for_action(), and inp_mngr.
Referenced by inventory_selector::action_bound_to_key(), inventory_selector::all_bound_keys(), target_ui::draw_controls_list(), key_bound_to(), key_bound_to(), keybind(), keys_bound_to(), press_x_if_bound(), and print_ranged_chance().
press_x() [1/3]
std::string input_context::press_x (const std::string & action_id) const
Definition at line 1390 of file input.cpp.
{
    return press_x( action_id, _( "Press " ), "", _( "Try" ) );
}
References _, and press_x().
Referenced by game::list_monsters(), press_x(), press_x(), and select_crafting_recipe().
press_x() [2/3]
std::string input_context::press_x (const std::string & action_id, const std::string & key_bound, const std::string & key_unbound) const
Definition at line 1395 of file input.cpp.
{
    return press_x( action_id, key_bound, "", key_unbound );
}
References press_x().
press_x() [3/3]
std::string input_context::press_x (const std::string & action_id, const std::string & key_bound_pre, const std::string & key_bound_suf, const std::string & key_unbound) const
Definition at line 1402 of file input.cpp.
{
    if( action_id == "ANY_INPUT" ) {
        return _( "any key" );
    }
    if( action_id == "COORDINATE" ) {
        return _( "mouse movement" );
    }
    const input_manager::t_input_event_list &events = inp_mngr.get_input_for_action( action_id,
            category );
    if( events.empty() ) {
        return key_unbound;
    }
    std::string keyed = key_bound_pre;
    for( size_t j = 0; j < events.size(); j++ ) {
        for( size_t k = 0; k < events[j].sequence.size(); ++k ) {
            keyed += inp_mngr.get_keyname( events[j].sequence[k], events[j].type );
        }
        if( j + 1 < events.size() ) {
            keyed += _( " or " );
        }
    }
    keyed += key_bound_suf;
    return keyed;
}
References _, category, input_manager::get_input_for_action(), input_manager::get_keyname(), inp_mngr, and type.
register_action() [1/2]
void input_context::register_action (const std::string & action_descriptor)
Register an action with this input context.
Only registered actions will be returned by handle_input(), it's thus possible to have multiple actions associated with the same keypress, as long as they don't ever occur in the same input context.
If action_descriptor is the special "ANY_INPUT", instead of ignoring unregistered keys, those keys will all be linked to this "ANY_INPUT" action.
If action_descriptor is the special "COORDINATE", coordinate input will be processed and the specified coordinates can be retrieved using get_coordinates(). Currently the only form of coordinate input is mouse input(you can directly click coordinates on the screen).
Parameters
action_descriptor String of action id.
Definition at line 676 of file input.cpp.
{
    register_action( action_descriptor, translation() );
}
References register_action().
Referenced by defense_game::caravan(), choose_direction(), choose_ma_style(), game_menus::inv::compare(), Character::conduct_blood_analysis(), construction_menu(), string_input_popup::create_context(), character_display::disp_info(), game::disp_NPCs(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), help::display_help(), display_menu(), draw_item_info(), editmap::edit(), game::extended_description(), get_default_mode_input_context(), game::get_player_input(), target_ui::init_window_and_input(), uilist::inputfilter(), inventory_multiselector::inventory_multiselector(), inventory_selector::inventory_selector(), game::item_action_menu(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_missions(), game::list_monsters(), game::look_around(), editmap::mapgen_retarget(), main_menu::opening_screen(), trading_window::perform_trade(), character_martial_arts::pick_style(), pickup::pick_up(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), robot_finds_kitten::process_input(), uilist::query(), query_popup::query_once(), computer_session::query_ynq(), advanced_inventory::redraw_sidebar(), register_action(), advanced_inventory::register_ctxt(), register_directions(), register_leftright(), register_updown(), examine_item_menu::run(), scrollable_text(), overmap_ui::search(), select_crafting_recipe(), editmap::select_shape(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), defense_game::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), show_armor_layers_ui(), show_bionics_ui(), diary::show_diary_ui(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), detail::show_mutations_ui_internal(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), veh_interact::veh_interact(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
register_action() [2/2]
void input_context::register_action (const std::string & action_descriptor, const translation & name)
Same as other register_action function but allows a context specific action name.
The given name is displayed instead of the name taken from the input_manager.
Parameters
action_descriptor String of action id.
name Name of the action, displayed to the user. If empty use the name reported by the input_manager.
Definition at line 681 of file input.cpp.
{
    if( action_descriptor == "ANY_INPUT" ) {
        registered_any_input = true;
    } else if( action_descriptor == "COORDINATE" ) {
        handling_coordinate_input = true;
    }
    registered_actions.push_back( action_descriptor );
    if( !name.empty() ) {
        action_name_overrides[action_descriptor] = name;
    }
}
References action_name_overrides, handling_coordinate_input, om_direction::name(), registered_actions, and registered_any_input.
register_cardinal()
void input_context::register_cardinal ()
Definition at line 936 of file input.cpp.
{
    register_updown();
    register_leftright();
}
References register_leftright(), and register_updown().
Referenced by defense_game::caravan(), faction_manager::display(), help::display_help(), game::list_missions(), main_menu::opening_screen(), robot_finds_kitten::process_input(), register_directions(), examine_item_menu::run(), select_crafting_recipe(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), show_armor_layers_ui(), diary::show_diary_ui(), color_manager::show_gui(), show_scores_ui(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), and game::zones_manager().
register_directions()
void input_context::register_directions ()
Definition at line 915 of file input.cpp.
{
    register_cardinal();
    register_action( "LEFTUP" );
    register_action( "LEFTDOWN" );
    register_action( "RIGHTUP" );
    register_action( "RIGHTDOWN" );
}
References register_action(), and register_cardinal().
Referenced by choose_direction(), overmap_ui::display(), editmap::edit(), target_ui::init_window_and_input(), game::look_around(), editmap::mapgen_retarget(), overmap_ui::place_ter_or_special(), editmap::select_shape(), lightson_game::start_game(), and veh_interact::veh_interact().
register_leftright()
void input_context::register_leftright ()
Definition at line 930 of file input.cpp.
{
    register_action( "LEFT" );
    register_action( "RIGHT" );
}
References register_action().
Referenced by register_cardinal().
register_updown()
void input_context::register_updown ()
Definition at line 924 of file input.cpp.
{
    register_action( "UP" );
    register_action( "DOWN" );
}
References register_action().
Referenced by character_display::disp_info(), faction_manager::display(), uilist::inputfilter(), basecamp::job_assignment_ui(), worldfactory::pick_world(), uilist::query(), register_cardinal(), worldfactory::show_active_world_mods(), show_bionics_ui(), worldfactory::show_modselection_window(), detail::show_mutations_ui_internal(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), and basecamp::worker_assignment_ui().
reset_timeout()
void input_context::reset_timeout ()
Definition at line 1463 of file input.cpp.
{
    timeout = -1;
}
References timeout.
Referenced by game::get_player_input(), game::look_around(), and game::zones_manager().
set_edittext()
void input_context::set_edittext (const std::string & s)
Get/Set edittext to display IME unspecified string.
Definition at line 1448 of file input.cpp.
{
    edittext = s;
}
References edittext.
Referenced by string_input_popup::query_string().
set_iso()
void input_context::set_iso (bool mode = true)
Definition at line 1429 of file input.cpp.
{
    iso_mode = mode;
}
References iso_mode.
Referenced by choose_direction(), editmap::edit(), editmap::eget_direction(), get_default_mode_input_context(), game::get_player_input(), target_ui::init_window_and_input(), game::look_around(), editmap::mapgen_retarget(), and editmap::select_shape().
set_timeout()
void input_context::set_timeout (int val)
Sets input polling timeout as appropriate for the current interface system.
Use this method to set timeouts when using input_context, rather than calling the old timeout() method or using input_manager::(re)set_timeout, as using this method will cause CATA_INPUT_TIMEOUT events to be generated correctly, and will reset timeout correctly when a new input context is entered.
Definition at line 1458 of file input.cpp.
{
    timeout = val;
}
References timeout.
Referenced by game::get_player_input(), game::look_around(), and game::zones_manager().
Member Data Documentation
action_name_overrides
std::map<std::string, translation> input_context::action_name_overrides private
When registering for actions within an input_context, callers can specify a custom action name that will override the action's normal name.
This map stores those overrides. The key is the action ID and the value is the user-visible name.
Definition at line 713 of file input.h.
Referenced by get_action_name(), and register_action().
allow_all_keys
const input_context::input_event_filter input_context::allow_all_keys static
Initial value:
=
[](const input_event &) -> bool {
    return true;
}
Definition at line 545 of file input.h.
Referenced by game::cancel_activity_or_ignore_query(), diary::edit_page_ui(), pickup::query_thief(), query_yn(), computer_session::query_ynq(), and diary::show_diary_ui().
category
std::string input_context::category private
Definition at line 699 of file input.h.
Referenced by action_uses_input(), clear_conflicting_keybindings(), display_menu(), get_action_name(), get_available_single_char_hotkeys(), get_desc(), input_to_action(), keys_bound_to(), and press_x().
coordinate
point input_context::coordinate private
Definition at line 700 of file input.h.
Referenced by get_coordinates(), and handle_input().
coordinate_input_received
bool input_context::coordinate_input_received private
Definition at line 701 of file input.h.
Referenced by get_coordinates(), and handle_input().
disallow_lower_case
const input_context::input_event_filter input_context::disallow_lower_case static
Initial value:
=
[](const input_event &evt) -> bool {
    return evt.type != CATA_INPUT_KEYBOARD ||
    evt.get_first_input() < 'a' || evt.get_first_input() > 'z';
}
Definition at line 544 of file input.h.
Referenced by game::cancel_activity_or_ignore_query(), diary::edit_page_ui(), pickup::query_thief(), query_yn(), and computer_session::query_ynq().
edittext
std::string input_context::edittext private
Definition at line 694 of file input.h.
Referenced by get_edittext(), and set_edittext().
handling_coordinate_input
bool input_context::handling_coordinate_input private
Definition at line 702 of file input.h.
Referenced by handle_input(), and register_action().
iso_mode
bool input_context::iso_mode = false private
Definition at line 704 of file input.h.
Referenced by get_direction(), and set_iso().
next_action
input_event input_context::next_action private
Definition at line 703 of file input.h.
Referenced by get_raw_input(), and handle_input().
registered_actions
std::vector<std::string> input_context::registered_actions private
Definition at line 693 of file input.h.
Referenced by clear_conflicting_keybindings(), display_menu(), get_available_single_char_hotkeys(), get_conflicts(), get_registered_actions_copy(), input_to_action(), and register_action().
registered_any_input
bool input_context::registered_any_input private
Definition at line 698 of file input.h.
Referenced by handle_input(), and register_action().
timeout
int input_context::timeout = -1 private
Definition at line 705 of file input.h.
Referenced by handle_input(), reset_timeout(), and set_timeout().
The documentation for this class was generated from the following files:
src/input.h
src/input.cpp