Cataclysm BN: detail::numeric_specs_checker< ErrorHandler > Class Template Reference
detail::numeric_specs_checker< ErrorHandler > Class Template Reference
#include <fmtlib_format.h>
Public Member Functions
FMT_CONSTEXPR numeric_specs_checker (ErrorHandler &eh, detail::type arg_type)
FMT_CONSTEXPR void require_numeric_argument ()
FMT_CONSTEXPR void check_sign ()
FMT_CONSTEXPR void check_precision ()
Private Attributes
ErrorHandler & error_handler_
detail::type arg_type_
Detailed Description
template<typename ErrorHandler>
class detail::numeric_specs_checker< ErrorHandler >
Definition at line 2834 of file fmtlib_format.h.
Constructor & Destructor Documentation
numeric_specs_checker()
template<typename ErrorHandler > FMT_CONSTEXPR detail::numeric_specs_checker< ErrorHandler >::numeric_specs_checker (ErrorHandler & eh, detail::type arg_type) inline
Definition at line 2837 of file fmtlib_format.h.
            : error_handler_( eh ), arg_type_( arg_type ) {}
Member Function Documentation
check_precision()
template<typename ErrorHandler > FMT_CONSTEXPR void detail::numeric_specs_checker< ErrorHandler >::check_precision () inline
Definition at line 2854 of file fmtlib_format.h.
{
            if( is_integral_type( arg_type_ ) || arg_type_ == type::pointer_type ) {
                error_handler_.on_error( "precision not allowed for this argument type" );
            }
        }
References detail::is_integral_type().
Referenced by detail::specs_checker< Handler >::end_precision().
check_sign()
template<typename ErrorHandler > FMT_CONSTEXPR void detail::numeric_specs_checker< ErrorHandler >::check_sign () inline
Definition at line 2846 of file fmtlib_format.h.
{
            require_numeric_argument();
            if( is_integral_type( arg_type_ ) && arg_type_ != type::int_type &&
                arg_type_ != type::long_long_type && arg_type_ != type::char_type ) {
                error_handler_.on_error( "format specifier requires signed argument" );
            }
        }
References detail::is_integral_type().
Referenced by detail::specs_checker< Handler >::on_minus(), detail::specs_checker< Handler >::on_plus(), and detail::specs_checker< Handler >::on_space().
require_numeric_argument()
template<typename ErrorHandler > FMT_CONSTEXPR void detail::numeric_specs_checker< ErrorHandler >::require_numeric_argument () inline
Definition at line 2840 of file fmtlib_format.h.
{
            if( !is_arithmetic_type( arg_type_ ) ) {
                error_handler_.on_error( "format specifier requires numeric argument" );
            }
        }
References detail::is_arithmetic_type().
Referenced by detail::specs_checker< Handler >::on_align(), detail::specs_checker< Handler >::on_hash(), and detail::specs_checker< Handler >::on_zero().
Member Data Documentation
arg_type_
template<typename ErrorHandler > detail::type detail::numeric_specs_checker< ErrorHandler >::arg_type_ private
Definition at line 2862 of file fmtlib_format.h.
error_handler_
template<typename ErrorHandler > ErrorHandler& detail::numeric_specs_checker< ErrorHandler >::error_handler_ private
Definition at line 2861 of file fmtlib_format.h.
The documentation for this class was generated from the following file:
src/fmtlib_format.h