Cataclysm BN: cone Class Reference
cone Class Reference
Cone centered along y axis.
#include <shape_impl.h>
Public Member Functions
cone (units::angle half_angle, double h)
double signed_distance (const rl_vec3d &p) const override
inclusive_cuboid< rl_vec3d > bounding_box () const override
Public Member Functions inherited from shape_impl
virtual ~shape_impl ()=default
Private Attributes
double h
double sin_angle
double cos_angle
Detailed Description
Cone centered along y axis.
Tip is at zero, base at (0, -h, 0). A 90 degree half angle will cause zero division.
Definition at line 42 of file shape_impl.h.
Constructor & Destructor Documentation
cone()
cone::cone (units::angle half_angle, double h) inline
Definition at line 50 of file shape_impl.h.
            : h( h )
            , sin_angle( sin( half_angle ) )
            , cos_angle( cos( half_angle ) )
        {}
Member Function Documentation
bounding_box()
inclusive_cuboid< rl_vec3d > cone::bounding_box () const inline override virtual
Implements shape_impl.
Definition at line 68 of file shape_impl.h.
{
            return inclusive_cuboid<rl_vec3d>( rl_vec3d( -sin_angle * h, -h, 0 ),
                                               rl_vec3d( sin_angle * h, 0, 0 ) );
        }
References h, and sin_angle.
signed_distance()
double cone::signed_distance (const rl_vec3d & p) const inline override virtual
Implements shape_impl.
Definition at line 56 of file shape_impl.h.
{
            // Based on https://www.iquilezles.org/www/articles/distfunctions/distfunctions.htm
            rl_vec2d q( h * sin_angle / cos_angle, -h );
            rl_vec2d w( std::sqrt( p.x * p.x + p.z * p.z ), p.y );
            rl_vec2d a = w - q * clamp( w.dot_product( q ) / q.dot_product( q ), 0.0f, 1.0f );
            rl_vec2d b = w - rl_vec2d( q.x * clamp( w.x / q.x, 0.0f, 1.0f ), q.y );
            float k = q.y >= 0.0f ? 1.0f : -1.0f;
            float d = std::min( a.dot_product( a ), b.dot_product( b ) );
            float s = std::max( k * ( w.x * q.y - w.y * q.x ), k * ( w.y - q.y ) );
            return std::sqrt( d ) * sign( s );
        }
References a, b, clamp(), cos_angle, rl_vec2d::dot_product(), h, sign(), sin_angle, rl_vec2d::x, rl_vec3d::x, rl_vec2d::y, rl_vec3d::y, and rl_vec3d::z.
Member Data Documentation
cos_angle
double cone::cos_angle private
Definition at line 47 of file shape_impl.h.
Referenced by signed_distance().
h
double cone::h private
Definition at line 45 of file shape_impl.h.
Referenced by bounding_box(), and signed_distance().
sin_angle
double cone::sin_angle private
Definition at line 46 of file shape_impl.h.
Referenced by bounding_box(), and signed_distance().
The documentation for this class was generated from the following file:
src/shape_impl.h