Cataclysm BN: player_morale::morale_point Class Reference
player_morale::morale_point Class Reference
Public Member Functions
morale_point (const morale_type &type=MORALE_NULL, morale_subtype subtype=morale_subtype(), int bonus=0, int max_bonus=0, time_duration duration=6_minutes, time_duration decay_start=3_minutes, bool capped=false)
void deserialize (JsonIn &jsin)
void serialize (JsonOut &json) const
std::string get_name () const
int get_net_bonus () const
int get_net_bonus (const morale_mult &mult) const
bool is_expired () const
bool is_permanent () const
bool type_matches (const morale_type &_type) const
bool matches (const morale_type &_type) const
bool matches (const morale_type &_type, const morale_subtype &_subtype) const
bool matches (const morale_point &mp) const
void add (int new_bonus, int new_max_bonus, time_duration new_duration, time_duration new_decay_start, bool new_cap)
void decay (const time_duration &ticks=1_turns)
void set_percent_contribution (double contribution)
double get_percent_contribution () const
Private Member Functions
time_duration pick_time (const time_duration &current_time, const time_duration &new_time, bool same_sign) const
Returns either new_time or remaining time (which one is greater).
int normalize_bonus (int bonus, int max_bonus, bool capped) const
Returns normalized bonus if either max_bonus != 0 or capped == true.
Private Attributes
morale_type type
morale_subtype subtype
int bonus = 0
time_duration duration = 0_turns
time_duration decay_start = 0_turns
time_duration age = 0_turns
double percent_contribution = 0
this point's percent contribution to the total positive or total negative morale effect
Detailed Description
Definition at line 144 of file morale.h.
Constructor & Destructor Documentation
morale_point()
player_morale::morale_point::morale_point (const morale_type & type = MORALE_NULL, morale_subtype subtype = morale_subtype(), int bonus = 0, int max_bonus = 0, time_duration duration = 6_minutes, time_duration decay_start = 3_minutes, bool capped = false) inline
Definition at line 147 of file morale.h.
                                          :
                    type( type ),
                    subtype( subtype ),
                    bonus( normalize_bonus( bonus, max_bonus, capped ) ),
                    duration( std::max( duration, 0_turns ) ),
                    decay_start( std::max( decay_start, 0_turns ) ),
                    age( 0_turns ) {}
Member Function Documentation
add()
void player_morale::morale_point::add (int new_bonus, int new_max_bonus, time_duration new_duration, time_duration new_decay_start, bool new_cap)
Definition at line 177 of file morale.cpp.
{
    new_duration = std::max( 0_turns, new_duration );
    new_decay_start = std::max( 0_turns, new_decay_start );
    const bool same_sign = ( bonus > 0 ) == ( new_max_bonus > 0 );
    if( new_cap || new_duration == 0_turns ) {
        duration = new_duration;
        decay_start = new_decay_start;
    } else {
        duration = pick_time( duration, new_duration, same_sign );
        decay_start = pick_time( decay_start, new_decay_start, same_sign );
    }
    int sqrt_of_sum_of_squares;
    if( new_cap || !same_sign ) {
        // If the morale bonus is capped apply the full bonus
        // This is because some morale types build up slowly to a cap over time (e.g. MORALE_WET)
        // If the new bonus is opposing apply the full bonus
        sqrt_of_sum_of_squares = get_net_bonus() + new_bonus;
    } else {
        // Otherwise use the sqrt of sum of squares to nerf stacking
        sqrt_of_sum_of_squares = std::pow( get_net_bonus(), 2 ) + std::pow( new_bonus, 2 );
        sqrt_of_sum_of_squares = std::sqrt( sqrt_of_sum_of_squares );
        sqrt_of_sum_of_squares *= sgn( bonus );
    }
    bonus = normalize_bonus( sqrt_of_sum_of_squares, new_max_bonus, new_cap );
    age = 0_turns; // Brand new. The assignment should stay below get_net_bonus() and pick_time().
}
References sgn().
decay()
void player_morale::morale_point::decay (const time_duration & ticks = 1_turns)
Definition at line 226 of file morale.cpp.
{
    if( ticks < 0_turns ) {
        debugmsg( "The function called with negative ticks %d.", to_turns<int>( ticks ) );
        return;
    }
    age += ticks;
}
References debugmsg.
deserialize()
void player_morale::morale_point::deserialize (JsonIn & jsin)
Definition at line 3151 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "type", type );
    if( !jo.read( "subtype", subtype ) && jo.has_string( "item_type" ) ) {
        subtype = morale_subtype( *itype_id( jo.get_string( "item_type" ) ) );
    }
    jo.read( "bonus", bonus );
    jo.read( "duration", duration );
    jo.read( "decay_start", decay_start );
    jo.read( "age", age );
}
References item::age(), JsonObject::allow_omitted_members(), JsonIn::get_object(), JsonObject::get_string(), JsonObject::has_string(), itype_id, JsonObject::read(), and item::type.
get_name()
std::string player_morale::morale_point::get_name () const
Definition at line 129 of file morale.cpp.
{
    if( subtype.has_description() ) {
        return type.obj().describe( subtype.describe() );
    } else {
        return type.obj().describe();
    }
}
References player_morale::morale_subtype::describe(), morale_type_data::describe(), player_morale::morale_subtype::has_description(), string_id< T >::obj(), subtype, and type.
Referenced by player_morale::display().
get_net_bonus() [1/2]
int player_morale::morale_point::get_net_bonus () const
Definition at line 138 of file morale.cpp.
{
    return bonus * ( ( !is_permanent() && age > decay_start ) ?
                     logarithmic_range( to_turns<int>( decay_start ), to_turns<int>( duration ),
                                        to_turns<int>( age ) ) : 1 );
}
References logarithmic_range().
get_net_bonus() [2/2]
int player_morale::morale_point::get_net_bonus (const morale_mult & mult) const
Definition at line 145 of file morale.cpp.
{
    return get_net_bonus() * mult;
}
get_percent_contribution()
double player_morale::morale_point::get_percent_contribution () const
Definition at line 222 of file morale.cpp.
{
    return percent_contribution;
}
Referenced by player_morale::display().
is_expired()
bool player_morale::morale_point::is_expired () const
Definition at line 150 of file morale.cpp.
{
    // Zero morale bonuses will be shown occasionally anyway
    return ( !is_permanent() && age >= duration ) || bonus == 0;
}
Referenced by player_morale::add(), and player_morale::remove_expired().
is_permanent()
bool player_morale::morale_point::is_permanent () const
Definition at line 156 of file morale.cpp.
{
    return ( duration == 0_turns );
}
matches() [1/3]
bool player_morale::morale_point::matches (const morale_point & mp) const
Definition at line 172 of file morale.cpp.
{
    return type == mp.type && subtype.matches( mp.subtype );
}
References subtype, type, and type.
matches() [2/3]
bool player_morale::morale_point::matches (const morale_type & _type) const
Referenced by player_morale::remove().
matches() [3/3]
bool player_morale::morale_point::matches (const morale_type & _type, const morale_subtype & _subtype) const
Definition at line 166 of file morale.cpp.
{
    return _type == type && subtype.matches( _subtype );
}
References type.
normalize_bonus()
int player_morale::morale_point::normalize_bonus (int bonus, int max_bonus, bool capped) const private
Returns normalized bonus if either max_bonus != 0 or capped == true.
Definition at line 236 of file morale.cpp.
{
    return ( ( std::abs( bonus ) > std::abs( max_bonus ) && ( max_bonus != 0 ||
               capped ) ) ? max_bonus : bonus );
}
pick_time()
time_duration player_morale::morale_point::pick_time (const time_duration & current_time, const time_duration & new_time, bool same_sign) const private
Returns either new_time or remaining time (which one is greater).
Only returns new time if same_sign is true
Definition at line 210 of file morale.cpp.
{
    const time_duration remaining_time = current_time - age;
    return ( remaining_time <= new_time && same_sign ) ? new_time : remaining_time;
}
serialize()
void player_morale::morale_point::serialize (JsonOut & json) const
Definition at line 3165 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "type", type );
    json.member( "subtype", subtype );
    json.member( "bonus", bonus );
    json.member( "duration", duration );
    json.member( "decay_start", decay_start );
    json.member( "age", age );
    json.end_object();
}
References item::age(), JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and item::type.
set_percent_contribution()
void player_morale::morale_point::set_percent_contribution (double contribution)
Definition at line 217 of file morale.cpp.
{
    percent_contribution = contribution;
}
type_matches()
bool player_morale::morale_point::type_matches (const morale_type & _type) const
Definition at line 161 of file morale.cpp.
{
    return _type == type;
}
References type.
Referenced by player_morale::remove().
Member Data Documentation
age
time_duration player_morale::morale_point::age = 0_turns private
Definition at line 191 of file morale.h.
bonus
int player_morale::morale_point::bonus = 0 private
Definition at line 188 of file morale.h.
decay_start
time_duration player_morale::morale_point::decay_start = 0_turns private
Definition at line 190 of file morale.h.
duration
time_duration player_morale::morale_point::duration = 0_turns private
Definition at line 189 of file morale.h.
percent_contribution
double player_morale::morale_point::percent_contribution = 0 private
this point's percent contribution to the total positive or total negative morale effect
Definition at line 195 of file morale.h.
subtype
morale_subtype player_morale::morale_point::subtype private
Definition at line 186 of file morale.h.
Referenced by get_name(), and matches().
type
morale_type player_morale::morale_point::type private
Definition at line 185 of file morale.h.
Referenced by get_name(), and matches().
The documentation for this class was generated from the following files:
src/morale.h
src/morale.cpp
src/savegame_json.cpp