Cataclysm BN: coords::coord_point< Point, Origin, Scale > Class Template Reference
coords::coord_point< Point, Origin, Scale > Class Template Reference
A generic coordinate-type-safe point.
#include <coordinates.h>
Public Member Functions
constexpr coord_point ()=default
constexpr coord_point (const Point &p)
template<typename T >
constexpr coord_point (T x, T y)
template<typename T >
constexpr coord_point (T x, T y, T z)
template<typename T >
constexpr coord_point (const coord_point< point, Origin, Scale > &xy, T z)
constexpr Point & raw ()
constexpr const Point & raw () const
constexpr auto & x ()
constexpr auto x () const
constexpr auto & y ()
constexpr auto y () const
constexpr auto xy () const
constexpr auto & z ()
constexpr auto z () const
std::string to_string () const
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
coord_point & operator+= (const coord_point< Point, origin::relative, Scale > &r)
coord_point & operator-= (const coord_point< Point, origin::relative, Scale > &r)
coord_point & operator+= (const point &r)
coord_point & operator-= (const point &r)
coord_point & operator+= (const tripoint &r)
coord_point & operator-= (const tripoint &r)
Static Public Attributes
static constexpr int dimension = Point::dimension
Private Attributes
Point raw_
Friends
coord_point operator+ (const coord_point &l, const point &r)
coord_point operator+ (const coord_point &l, const tripoint &r)
coord_point operator- (const coord_point &l, const point &r)
coord_point operator- (const coord_point &l, const tripoint &r)
Detailed Description
template<typename Point, origin Origin, scale Scale>
class coords::coord_point< Point, Origin, Scale >
A generic coordinate-type-safe point.
Generally you wouldn't use this class directly, but via the typedefs below (point_abs_ms, etc.).
Point should be the underlying representation type (either point or tripoint).
Origin and Scale define the coordinate system for the point.
For more details see doc/POINTS_COORDINATES.md.
Definition at line 93 of file coordinates.h.
Constructor & Destructor Documentation
coord_point() [1/5]
template<typename Point , origin Origin, scale Scale> constexpr coords::coord_point< Point, Origin, Scale >::coord_point () constexpr default
coord_point() [2/5]
template<typename Point , origin Origin, scale Scale> constexpr coords::coord_point< Point, Origin, Scale >::coord_point (const Point & p) inline explicit constexpr
Definition at line 99 of file coordinates.h.
                                                         :
            raw_( p )
        {}
coord_point() [3/5]
template<typename Point , origin Origin, scale Scale> template<typename T > constexpr coords::coord_point< Point, Origin, Scale >::coord_point (T x, T y) inline constexpr
Definition at line 103 of file coordinates.h.
: raw_(x, y) {}
coord_point() [4/5]
template<typename Point , origin Origin, scale Scale> template<typename T > constexpr coords::coord_point< Point, Origin, Scale >::coord_point (T x, T y, T z) inline constexpr
Definition at line 105 of file coordinates.h.
: raw_(x, y, z) {}
coord_point() [5/5]
template<typename Point , origin Origin, scale Scale> template<typename T > constexpr coords::coord_point< Point, Origin, Scale >::coord_point (const coord_point< point, Origin, Scale > & xy, T z) inline constexpr
Definition at line 107 of file coordinates.h.
                                                                                  :
            raw_( xy.raw(), z )
        {}
Member Function Documentation
deserialize()
template<typename Point , origin Origin, scale Scale> void coords::coord_point< Point, Origin, Scale >::deserialize (JsonIn & jsin) inline
Definition at line 147 of file coordinates.h.
{
            raw().deserialize( jsin );
        }
Referenced by mongroup::deserialize_legacy(), overmap::load_monster_groups(), and overmap::unserialize().
operator+=() [1/3]
template<typename Point , origin Origin, scale Scale> coord_point & coords::coord_point< Point, Origin, Scale >::operator+= (const coord_point< Point, origin::relative, Scale > & r) inline
Definition at line 151 of file coordinates.h.
{
            raw_ += r.raw();
            return *this;
        }
References coords::coord_point< Point, Origin, Scale >::raw().
operator+=() [2/3]
template<typename Point , origin Origin, scale Scale> coord_point & coords::coord_point< Point, Origin, Scale >::operator+= (const point & r) inline
Definition at line 161 of file coordinates.h.
{
            raw_ += r;
            return *this;
        }
operator+=() [3/3]
template<typename Point , origin Origin, scale Scale> coord_point & coords::coord_point< Point, Origin, Scale >::operator+= (const tripoint & r) inline
Definition at line 171 of file coordinates.h.
{
            raw_ += r;
            return *this;
        }
operator-=() [1/3]
template<typename Point , origin Origin, scale Scale> coord_point & coords::coord_point< Point, Origin, Scale >::operator-= (const coord_point< Point, origin::relative, Scale > & r) inline
Definition at line 156 of file coordinates.h.
{
            raw_ -= r.raw();
            return *this;
        }
References coords::coord_point< Point, Origin, Scale >::raw().
operator-=() [2/3]
template<typename Point , origin Origin, scale Scale> coord_point & coords::coord_point< Point, Origin, Scale >::operator-= (const point & r) inline
Definition at line 166 of file coordinates.h.
{
            raw_ -= r;
            return *this;
        }
operator-=() [3/3]
template<typename Point , origin Origin, scale Scale> coord_point & coords::coord_point< Point, Origin, Scale >::operator-= (const tripoint & r) inline
Definition at line 176 of file coordinates.h.
{
            raw_ -= r;
            return *this;
        }
raw() [1/2]
template<typename Point , origin Origin, scale Scale> constexpr Point & coords::coord_point< Point, Origin, Scale >::raw () inline constexpr
Definition at line 111 of file coordinates.h.
{
            return raw_;
        }
Referenced by start_location::add_map_extra(), grid_furn_transform_queue::apply(), iuse::cable_attach(), vehicle::autodrive_controller::check_drivable(), closest_points_first(), vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_goal_zone(), vehicle::autodrive_controller::compute_path(), debug_menu::debug(), direction_from(), item::display_name(), vehicle::do_towing_move(), overmap_ui::draw_ascii(), vehicle::drive_to_local_target(), start_location::find_player_initial_location(), find_valid_teleporters_omt(), vehicle::find_vehicle(), disassemble_activity_actor::finish(), overmapbuffer::fix_npcs(), vehicle::get_angle_from_targ(), vehicle::get_debug_overlay_data(), om_noise::om_noise_layer::global_omt_pos(), vehicle::interact_vehicle_locked(), overmap::is_omt_generated(), line_to(), map::load(), map::loadn(), mapbuffer::lookup_submap(), manhattan_dist(), midpoint(), octile_dist(), coords::operator!=(), coords::project_to_impl< ScaleUp, 0, ResultScale >::operator()(), coords::project_to_impl< 0, ScaleDown, ResultScale >::operator()(), std::hash< coords::coord_point< Point, Origin, Scale > >::operator()(), coords::operator*(), coords::operator+(), coords::coord_point< Point, Origin, Scale >::operator+=(), coords::operator-(), coords::coord_point< Point, Origin, Scale >::operator-=(), coords::operator<(), coords::operator<<(), coords::operator==(), Character::overmap_los(), teleporter_list::place_avatar_overmap(), start_location::prepare_map(), coords::project_combine(), coords::project_remain(), rl_dist(), overmap::signal_hordes(), debug_menu::spawn_nested_mapgen(), square_dist(), activity_handlers::travel_do_turn(), trig_dist(), charger_tile::update_internal(), solar_tile::update_internal(), game::update_overmap_seen(), and reveal_map_actor::use().
raw() [2/2]
template<typename Point , origin Origin, scale Scale> constexpr const Point & coords::coord_point< Point, Origin, Scale >::raw () const inline constexpr
Definition at line 114 of file coordinates.h.
{
            return raw_;
        }
serialize()
template<typename Point , origin Origin, scale Scale> void coords::coord_point< Point, Origin, Scale >::serialize (JsonOut & jsout) const inline
Definition at line 144 of file coordinates.h.
{
            raw().serialize( jsout );
        }
to_string()
template<typename Point , origin Origin, scale Scale> std::string coords::coord_point< Point, Origin, Scale >::to_string () const inline
Definition at line 140 of file coordinates.h.
{
            return raw_.to_string();
        }
Referenced by overmap::build_lab(), debug_menu::character_edit_menu(), debug_menu::mission_debug::describe(), game::disp_NPCs(), elevate_bridges(), basecamp::faction_display(), npc::faction_display(), overmapbuffer::fix_npcs(), overmap::generate_sub(), distribution_grid::get_resource(), npc::go_to_omt_destination(), game::list_missions(), distribution_grid::mod_resource(), overmap::overmap(), game::overmap_npc_move(), overmap::populate(), npc::set_omt_destination(), debug_menu::teleport_long(), debug_menu::teleport_overmap(), distribution_grid::update(), and iexamine::use_furn_fake_item().
x() [1/2]
template<typename Point , origin Origin, scale Scale> constexpr auto & coords::coord_point< Point, Origin, Scale >::x () inline constexpr
Definition at line 118 of file coordinates.h.
{
            return raw_.x;
        }
Referenced by overmap::build_mine(), overmap_ui::draw_ascii(), overmap_ui::draw_city_labels(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), overmap::explored(), overmapbuffer::find_camp(), overmapbuffer::fix_npcs(), overmap_ui::fmt_omt_coords(), get_common_data(), overmapbuffer::get_overmaps_near(), npc::go_to_omt_destination(), overmap::good_river(), overmap::is_explored(), overmap::move_hordes(), om_noise::om_noise_layer_forest::noise_at(), om_noise::om_noise_layer_floodplain::noise_at(), om_noise::om_noise_layer_lake::noise_at(), talk_function::om_simple_dir(), Character::overmap_los(), mission_util::parse_mission_om_target(), overmap::place_forest_trails(), overmap::place_river(), overmap::place_special_attempt(), overmapbuffer::player_filename(), overmap::populate_connections_out_from_neighbors(), overmap_ui::search(), overmap::seen(), mongroup::set_target(), basecamp::start_fortifications(), overmap::ter(), overmap::ter_set(), overmapbuffer::terrain_filename(), overmap::unserialize(), overmap::unserialize_view(), game::update_overmap_seen(), and mongroup::wander().
x() [2/2]
template<typename Point , origin Origin, scale Scale> constexpr auto coords::coord_point< Point, Origin, Scale >::x () const inline constexpr
Definition at line 121 of file coordinates.h.
{
            return raw_.x;
        }
xy()
template<typename Point , origin Origin, scale Scale> constexpr auto coords::coord_point< Point, Origin, Scale >::xy () const inline constexpr
Definition at line 130 of file coordinates.h.
{
            return coord_point<point, Origin, Scale>( raw_.xy() );
        }
Referenced by talk_function::abandon_camp(), overmapbuffer::add_camp(), overmap::add_extra(), overmap::add_note(), overmapbuffer::add_vehicle(), talk_function::assign_camp(), overmap::build_connection(), overmap::build_lab(), overmap::build_tunnel(), talk_function::companion_choose(), npc::consume_food_from_camp(), iuse::directional_antenna(), faction_manager::display(), overmap_ui::display(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), overmap::extra(), pf::find_overmap_path(), overmap::find_terrain(), overmapbuffer::fix_mongroups(), overmapbuffer::fix_npcs(), overmap::generate_over(), overmap::generate_sub(), get_basecamp(), overmapbuffer::get_existing_om_global(), overmapbuffer::get_extras(), overmapbuffer::get_npcs_near(), overmapbuffer::get_npcs_near_omt(), overmapbuffer::get_npcs_near_player(), overmapbuffer::get_om_global(), overmapbuffer::get_overmaps_near(), overmapbuffer::get_vehicle(), weather_generator::get_weather(), weather_generator::get_weather_temperature(), npc::go_to_omt_destination(), overmapbuffer::groups_at(), overmap::has_extra(), overmap::has_note(), overmap::has_note_with_danger_radius(), overmapbuffer::has_vehicle(), overmapbuffer::insert_npc(), overmap::is_marked_dangerous(), editmap::mapgen_preview(), overmap::mark_note_dangerous(), overmap::move_hordes(), overmapbuffer::move_vehicle(), talk_function::name_mission_tabs(), overmap::note(), om_companion_path(), om_set_hide_site(), talk_function::om_simple_dir(), om_target_tile(), distribution_grid_tracker::on_changed(), npc_dist_to_player::operator()(), Character::overmap_los(), overmap::place_building(), overmap::place_cities(), overmap::place_forest_trails(), overmap::place_forests(), overmap::place_lakes(), overmap::place_radios(), overmap::place_rivers(), overmap::place_special(), overmap::place_swamps(), overmap_ui::place_ter_or_special(), map::point_within_camp(), player::process_turn(), coords::project_remain(), overmapbuffer::remove_camp(), overmap_ui::search(), conditional_t< T >::set_at_om_location(), vehicle::set_submap_moved(), overmap::signal_hordes(), overmapbuffer::spawn_monster(), basecamp::start_clearcut(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), basecamp::survey_return(), mission_util::target_closest_lab_entrance(), game::update_overmap_seen(), and mongroup::wander().
y() [1/2]
template<typename Point , origin Origin, scale Scale> constexpr auto & coords::coord_point< Point, Origin, Scale >::y () inline constexpr
Definition at line 124 of file coordinates.h.
{
            return raw_.y;
        }
Referenced by overmap::build_mine(), overmap_ui::draw_ascii(), overmap_ui::draw_city_labels(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), overmap::explored(), overmapbuffer::find_camp(), overmapbuffer::fix_npcs(), overmap_ui::fmt_omt_coords(), get_common_data(), overmapbuffer::get_overmaps_near(), npc::go_to_omt_destination(), overmap::good_river(), overmap::is_explored(), overmap::move_hordes(), om_noise::om_noise_layer_forest::noise_at(), om_noise::om_noise_layer_floodplain::noise_at(), om_noise::om_noise_layer_lake::noise_at(), talk_function::om_simple_dir(), Character::overmap_los(), mission_util::parse_mission_om_target(), overmap::place_forest_trails(), overmap::place_river(), overmap::place_special_attempt(), overmapbuffer::player_filename(), overmap::populate_connections_out_from_neighbors(), overmap_ui::search(), overmap::seen(), mongroup::set_target(), basecamp::start_fortifications(), overmap::ter(), overmap::ter_set(), overmapbuffer::terrain_filename(), overmap::unserialize(), overmap::unserialize_view(), game::update_overmap_seen(), and mongroup::wander().
y() [2/2]
template<typename Point , origin Origin, scale Scale> constexpr auto coords::coord_point< Point, Origin, Scale >::y () const inline constexpr
Definition at line 127 of file coordinates.h.
{
            return raw_.y;
        }
z() [1/2]
template<typename Point , origin Origin, scale Scale> constexpr auto & coords::coord_point< Point, Origin, Scale >::z () inline constexpr
Definition at line 133 of file coordinates.h.
{
            return raw_.z;
        }
Referenced by overmap::add_extra(), overmap::add_note(), overmap::build_lab(), ui::omap::choose_point(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), overmap_ui::display(), ui::omap::display_visible_weather(), ui::omap::display_weather(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), overmap::explored(), overmap::extra(), farm_action(), pf::find_overmap_path(), overmapbuffer::fix_mongroups(), overmapbuffer::get_description_at(), overmapbuffer::get_existing_om_global(), get_mission_om_origin(), overmapbuffer::get_npcs_near(), overmapbuffer::get_npcs_near_omt(), overmapbuffer::get_npcs_near_player(), overmapbuffer::get_om_global(), weather_manager::get_temperature(), overmapbuffer::get_vehicle(), overmapbuffer::groups_at(), overmap::has_extra(), overmap::has_note(), overmap::has_note_with_danger_radius(), overmapbuffer::has_vehicle(), overmap::is_explored(), overmap::is_marked_dangerous(), mission_start::kill_horde_master(), editmap::mapgen_veh_destroy(), overmap::mark_note_dangerous(), overmap::note(), om_cutdown_trees(), om_harvest_itm(), om_harvest_ter(), mission_util::parse_mission_om_target(), mission_start::place_deposit_box(), mission_start::place_dog(), mission_start::place_priest_diary(), mission_start::place_zombie_mom(), overmap::populate_connections_out_from_neighbors(), coords::project_remain(), mission_start::reveal_lab_train_depot(), mission_util::reveal_om_ter(), talk_function::scavenging_raid_return(), overmap_ui::search(), overmap::seen(), npc::set_omt_destination(), overmap_ui::show_notes_manager(), overmapbuffer::spawn_monster(), basecamp::survey_return(), mission_util::target_closest_lab_entrance(), overmap::ter(), overmap::ter_set(), and game::update_overmap_seen().
z() [2/2]
template<typename Point , origin Origin, scale Scale> constexpr auto coords::coord_point< Point, Origin, Scale >::z () const inline constexpr
Definition at line 136 of file coordinates.h.
{
            return raw_.z;
        }
Friends And Related Function Documentation
operator+ [1/2]
template<typename Point , origin Origin, scale Scale> coord_point operator+ (const coord_point< Point, Origin, Scale > & l, const point & r) friend
Definition at line 181 of file coordinates.h.
{
            return coord_point( l.raw() + r );
        }
operator+ [2/2]
template<typename Point , origin Origin, scale Scale> coord_point operator+ (const coord_point< Point, Origin, Scale > & l, const tripoint & r) friend
Definition at line 185 of file coordinates.h.
{
            return coord_point( l.raw() + r );
        }
operator- [1/2]
template<typename Point , origin Origin, scale Scale> coord_point operator- (const coord_point< Point, Origin, Scale > & l, const point & r) friend
Definition at line 189 of file coordinates.h.
{
            return coord_point( l.raw() - r );
        }
operator- [2/2]
template<typename Point , origin Origin, scale Scale> coord_point operator- (const coord_point< Point, Origin, Scale > & l, const tripoint & r) friend
Definition at line 193 of file coordinates.h.
{
            return coord_point( l.raw() - r );
        }
Member Data Documentation
dimension
template<typename Point , origin Origin, scale Scale> constexpr int coords::coord_point< Point, Origin, Scale >::dimension = Point::dimension static constexpr
Definition at line 96 of file coordinates.h.
raw_
template<typename Point , origin Origin, scale Scale> Point coords::coord_point< Point, Origin, Scale >::raw_ private
Definition at line 197 of file coordinates.h.
The documentation for this class was generated from the following file:
src/coordinates.h