Cataclysm BN: basic_format_args< Context > Class Template Reference
basic_format_args< Context > Class Template Reference
\rst A view of a collection of formatting arguments.
#include <fmtlib_core.h>
Public Types
using size_type = int
using format_arg = basic_format_arg< Context >
Public Member Functions
basic_format_args ()
template<typename... Args>
FMT_INLINE basic_format_args (const format_arg_store< Context, Args... > &store)
\rst Constructs a basic_format_args object from ~fmtformat_arg_store.
FMT_INLINE basic_format_args (const dynamic_format_arg_store< Context > &store)
\rst Constructs a basic_format_args object from ~fmtdynamic_format_arg_store.
basic_format_args (const format_arg *args, int count)
\rst Constructs a basic_format_args object from a dynamic set of arguments.
format_arg get (int id) const
Returns the argument with the specified id.
template<typename Char >
format_arg get (basic_string_view< Char > name) const
template<typename Char >
int get_id (basic_string_view< Char > name) const
int max_size () const
Private Member Functions
bool is_packed () const
bool has_named_args () const
detail::type type (int index) const
basic_format_args (unsigned long long desc, const detail::value< Context > *values)
basic_format_args (unsigned long long desc, const format_arg *args)
Private Attributes
unsigned long long desc_
union {
const detail::value< Context > * values_
const format_arg * args_
};
Detailed Description
template<typename Context>
class basic_format_args< Context >
\rst A view of a collection of formatting arguments.
To avoid lifetime issues it should only be used as a parameter type in type-erased functions such as vformat::
void vlog(string_view format_str, format_args args); // OK format_args args = make_format_args(42); // Error: dangling reference \endrst
Definition at line 2050 of file fmtlib_core.h.
Member Typedef Documentation
format_arg
template<typename Context > using basic_format_args< Context >::format_arg = basic_format_arg<Context>
Definition at line 2054 of file fmtlib_core.h.
size_type
template<typename Context > using basic_format_args< Context >::size_type = int
Definition at line 2053 of file fmtlib_core.h.
Constructor & Destructor Documentation
basic_format_args() [1/6]
template<typename Context > basic_format_args< Context >::basic_format_args (unsigned long long desc, const detail::value< Context > * values) inline private
Definition at line 2085 of file fmtlib_core.h.
            : desc_( desc ), values_( values ) {}
basic_format_args() [2/6]
template<typename Context > basic_format_args< Context >::basic_format_args (unsigned long long desc, const format_arg * args) inline private
Definition at line 2088 of file fmtlib_core.h.
            : desc_( desc ), args_( args ) {}
basic_format_args() [3/6]
template<typename Context > basic_format_args< Context >::basic_format_args () inline
Definition at line 2092 of file fmtlib_core.h.
: desc_(0) {}
basic_format_args() [4/6]
template<typename Context > template<typename... Args> FMT_INLINE basic_format_args< Context >::basic_format_args (const format_arg_store< Context, Args... > & store) inline
\rst Constructs a basic_format_args object from ~fmtformat_arg_store.
\endrst
Definition at line 2100 of file fmtlib_core.h.
            : basic_format_args( store.desc, store.data_.args() ) {}
basic_format_args() [5/6]
template<typename Context > FMT_INLINE basic_format_args< Context >::basic_format_args (const dynamic_format_arg_store< Context > & store) inline
\rst Constructs a basic_format_args object from ~fmtdynamic_format_arg_store.
\endrst
Definition at line 2109 of file fmtlib_core.h.
            : basic_format_args( store.get_types(), store.data() ) {}
basic_format_args() [6/6]
template<typename Context > basic_format_args< Context >::basic_format_args (const format_arg * args, int count) inline
\rst Constructs a basic_format_args object from a dynamic set of arguments.
\endrst
Definition at line 2117 of file fmtlib_core.h.
            : basic_format_args( detail::is_unpacked_bit | detail::to_unsigned( count ),
                                 args ) {}
Member Function Documentation
get() [1/2]
template<typename Context > template<typename Char > format_arg basic_format_args< Context >::get (basic_string_view< Char > name) const inline
Definition at line 2141 of file fmtlib_core.h.
{
            int id = get_id( name );
            return id >= 0 ? get( id ) : format_arg();
        }
References basic_format_args< Context >::get(), basic_format_args< Context >::get_id(), and om_direction::name().
get() [2/2]
template<typename Context > format_arg basic_format_args< Context >::get (int id) const inline
Returns the argument with the specified id.
Definition at line 2122 of file fmtlib_core.h.
{
            format_arg arg;
            if( !is_packed() ) {
                if( id < max_size() ) {
                    arg = args_[id];
                }
                return arg;
            }
            if( id >= detail::max_packed_args ) {
                return arg;
            }
            arg.type_ = type( id );
            if( arg.type_ == detail::type::none_type ) {
                return arg;
            }
            arg.value_ = values_[id];
            return arg;
        }
References arg(), basic_format_args< Context >::args_, base_camps::id, basic_format_args< Context >::is_packed(), detail::max_packed_args, basic_format_args< Context >::max_size(), detail::none_type, basic_format_args< Context >::type(), and basic_format_args< Context >::values_.
Referenced by basic_format_args< Context >::get(), and detail::vformat().
get_id()
template<typename Context > template<typename Char > int basic_format_args< Context >::get_id (basic_string_view< Char > name) const inline
Definition at line 2146 of file fmtlib_core.h.
{
            if( !has_named_args() ) {
                return -1;
            }
            const auto &named_args =
                ( is_packed() ? values_[-1] : args_[-1].value_ ).named_args;
            for( size_t i = 0; i < named_args.size; ++i ) {
                if( named_args.data[i].name == name ) {
                    return named_args.data[i].id;
                }
            }
            return -1;
        }
References basic_format_args< Context >::args_, basic_format_args< Context >::has_named_args(), basic_format_args< Context >::is_packed(), om_direction::name(), basic_format_arg< Context >::value_, and basic_format_args< Context >::values_.
Referenced by basic_format_args< Context >::get().
has_named_args()
template<typename Context > bool basic_format_args< Context >::has_named_args () const inline private
Definition at line 2075 of file fmtlib_core.h.
{
            return ( desc_ & detail::has_named_args_bit ) != 0;
        }
References basic_format_args< Context >::desc_, and detail::has_named_args_bit.
Referenced by basic_format_args< Context >::get_id().
is_packed()
template<typename Context > bool basic_format_args< Context >::is_packed () const inline private
Definition at line 2072 of file fmtlib_core.h.
{
            return ( desc_ & detail::is_unpacked_bit ) == 0;
        }
References basic_format_args< Context >::desc_, and detail::is_unpacked_bit.
Referenced by basic_format_args< Context >::get(), basic_format_args< Context >::get_id(), and basic_format_args< Context >::max_size().
max_size()
template<typename Context > int basic_format_args< Context >::max_size () const inline
Definition at line 2160 of file fmtlib_core.h.
{
            unsigned long long max_packed = detail::max_packed_args;
            return static_cast<int>( is_packed() ? max_packed
                                     : desc_ & ~detail::is_unpacked_bit );
        }
References basic_format_args< Context >::desc_, basic_format_args< Context >::is_packed(), detail::is_unpacked_bit, and detail::max_packed_args.
Referenced by basic_format_args< Context >::get().
type()
template<typename Context > detail::type basic_format_args< Context >::type (int index) const inline private
Definition at line 2079 of file fmtlib_core.h.
{
            int shift = index * detail::packed_arg_bits;
            unsigned int mask = ( 1 << detail::packed_arg_bits ) - 1;
            return static_cast<detail::type>( ( desc_ >> shift ) & mask );
        }
References basic_format_args< Context >::desc_, and detail::packed_arg_bits.
Referenced by basic_format_args< Context >::get().
Member Data Documentation
union { ... } basic_format_args< Context >::@11
args_
template<typename Context > const format_arg* basic_format_args< Context >::args_
Definition at line 2069 of file fmtlib_core.h.
Referenced by basic_format_args< Context >::get(), and basic_format_args< Context >::get_id().
desc_
template<typename Context > unsigned long long basic_format_args< Context >::desc_ private
Definition at line 2061 of file fmtlib_core.h.
Referenced by basic_format_args< Context >::has_named_args(), basic_format_args< Context >::is_packed(), basic_format_args< Context >::max_size(), and basic_format_args< Context >::type().
values_
template<typename Context > const detail::value<Context>* basic_format_args< Context >::values_
Definition at line 2068 of file fmtlib_core.h.
Referenced by basic_format_args< Context >::get(), and basic_format_args< Context >::get_id().
The documentation for this class was generated from the following file:
src/fmtlib_core.h