Cataclysm BN: change_scent_iuse Class Reference
change_scent_iuse Class Reference
This iuse contains the logic to change one's scent.
#include <iuse_actor.h>
Public Member Functions
change_scent_iuse ()
~change_scent_iuse () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
scenttype_id scenttypeid
The scent type id of the new scent.
int moves = 100
How many move points this action takes.
int charges_to_use = 1
How many charge are consumed on use.
int scent_mod = 0
Scent value modifier.
time_duration duration
How long does the scent stays.
bool waterproof = false
Is the scent mask waterproof.
std::vector< effect_data > effects
Side effect of using the item.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This iuse contains the logic to change one's scent.
Definition at line 408 of file iuse_actor.h.
Constructor & Destructor Documentation
change_scent_iuse()
change_scent_iuse::change_scent_iuse () inline
Definition at line 426 of file iuse_actor.h.
: iuse_actor("change_scent") { }
~change_scent_iuse()
change_scent_iuse::~change_scent_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > change_scent_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 5075 of file iuse_actor.cpp.
{
    return std::make_unique<change_scent_iuse>( *this );
}
load()
void change_scent_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 5036 of file iuse_actor.cpp.
{
    scenttypeid = scenttype_id( obj.get_string( "scent_typeid" ) );
    if( !scenttypeid.is_valid() ) {
        obj.throw_error( "Invalid scent type id.", "scent_typeid" );
    }
    if( obj.has_array( "effects" ) ) {
        for( JsonObject e : obj.get_array( "effects" ) ) {
            effects.push_back( load_effect_data( e ) );
        }
    }
    assign( obj, "moves", moves );
    assign( obj, "charges_to_use", charges_to_use );
    assign( obj, "scent_mod", scent_mod );
    assign( obj, "duration", duration );
    assign( obj, "waterproof", waterproof );
}
References assign(), Creature::effects, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), load_effect_data(), Creature::moves, and JsonObject::throw_error().
use()
int change_scent_iuse::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 5054 of file iuse_actor.cpp.
{
    p.set_value( "prev_scent", p.get_type_of_scent().c_str() );
    if( waterproof ) {
        p.set_value( "waterproof_scent", "true" );
    }
    p.add_effect( efftype_id( "masked_scent" ), duration, num_bp, scent_mod );
    p.set_type_of_scent( scenttypeid );
    p.mod_moves( -moves );
    add_msg( m_info, _( "You use the %s to mask your scent" ), it.tname() );
    // Apply the various effects.
    for( const auto &eff : effects ) {
        p.add_effect( eff.id, eff.duration, eff.bp );
        if( eff.permanent ) {
            p.get_effect( eff.id, eff.bp ).set_permanent();
        }
    }
    return charges_to_use;
}
References _, Creature::add_effect(), add_msg(), string_id< T >::c_str(), Creature::effects, efftype_id, Creature::get_effect(), Character::get_type_of_scent(), m_info, Creature::mod_moves(), Creature::moves, num_bp, effect::set_permanent(), Character::set_type_of_scent(), Creature::set_value(), and item::tname().
Member Data Documentation
charges_to_use
int change_scent_iuse::charges_to_use = 1
How many charge are consumed on use.
Definition at line 416 of file iuse_actor.h.
duration
time_duration change_scent_iuse::duration
How long does the scent stays.
Definition at line 420 of file iuse_actor.h.
effects
std::vector<effect_data> change_scent_iuse::effects
Side effect of using the item.
Definition at line 424 of file iuse_actor.h.
moves
int change_scent_iuse::moves = 100
How many move points this action takes.
Definition at line 414 of file iuse_actor.h.
scent_mod
int change_scent_iuse::scent_mod = 0
Scent value modifier.
Definition at line 418 of file iuse_actor.h.
scenttypeid
scenttype_id change_scent_iuse::scenttypeid
The scent type id of the new scent.
Definition at line 412 of file iuse_actor.h.
waterproof
bool change_scent_iuse::waterproof = false
Is the scent mask waterproof.
Definition at line 422 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp