Cataclysm BN: Item_spawn_data Class Reference
Item_spawn_data Class Reference abstract
Base interface for item spawn.
#include <item_group.h>
Public Types
using ItemList = std::vector< item >
using RecursionList = std::vector< std::string >
Public Member Functions
Item_spawn_data (int _probability)
virtual ~Item_spawn_data ()=default
virtual ItemList create (const time_point &birthday, RecursionList &rec) const =0
Create a list of items.
ItemList create (const time_point &birthday) const
virtual item create_single (const time_point &birthday, RecursionList &rec) const =0
The same as create, but create a single item only.
item create_single (const time_point &birthday) const
virtual void check_consistency (const std::string &context) const =0
Check item / spawn settings for consistency.
virtual bool remove_item (const itype_id &itemid)=0
For item blacklisted, remove the given item from this and all linked groups.
virtual bool replace_item (const itype_id &itemid, const itype_id &replacementid)=0
virtual bool has_item (const itype_id &itemid) const =0
virtual std::set< const itype * > every_item () const =0
Public Attributes
int probability
probability, used by the parent object.
Detailed Description
Base interface for item spawn.
Used to generate a list of items.
Definition at line 104 of file item_group.h.
Member Typedef Documentation
ItemList
using Item_spawn_data::ItemList = std::vector<item>
Definition at line 107 of file item_group.h.
RecursionList
using Item_spawn_data::RecursionList = std::vector<std::string>
Definition at line 108 of file item_group.h.
Constructor & Destructor Documentation
Item_spawn_data()
Item_spawn_data::Item_spawn_data (int _probability) inline
Definition at line 110 of file item_group.h.
: probability(_probability) { }
~Item_spawn_data()
virtual Item_spawn_data::~Item_spawn_data () virtual default
Member Function Documentation
check_consistency()
virtual void Item_spawn_data::check_consistency (const std::string & context) const pure virtual
Check item / spawn settings for consistency.
Includes checking for valid item types and valid settings.
Implemented in Single_item_creator, and Item_group.
create() [1/2]
Item_spawn_data::ItemList Item_spawn_data::create (const time_point & birthday) const
Definition at line 31 of file item_group.cpp.
{
    RecursionList rec;
    return create( birthday, rec );
}
References create().
create() [2/2]
virtual ItemList Item_spawn_data::create (const time_point & birthday, RecursionList & rec) const pure virtual
Create a list of items.
The create list might be empty. No item of it will be the null item.
Parameters
[in] birthday All items have that value as birthday.
[out] rec Recursion list, output goes here
Implemented in Single_item_creator, and Item_group.
Referenced by jmapgen_loot::apply(), create(), and Single_item_creator::create().
create_single() [1/2]
item Item_spawn_data::create_single (const time_point & birthday) const
Definition at line 37 of file item_group.cpp.
{
    RecursionList rec;
    return create_single( birthday, rec );
}
References create_single().
create_single() [2/2]
virtual item Item_spawn_data::create_single (const time_point & birthday, RecursionList & rec) const pure virtual
The same as create, but create a single item only.
The returned item might be a null item!
Implemented in Single_item_creator, and Item_group.
Referenced by create_single(), and Single_item_creator::create_single().
every_item()
virtual std::set< const itype * > Item_spawn_data::every_item () const pure virtual
Implemented in Single_item_creator, and Item_group.
Referenced by Single_item_creator::every_item().
has_item()
virtual bool Item_spawn_data::has_item (const itype_id & itemid) const pure virtual
Implemented in Single_item_creator, and Item_group.
Referenced by Item_factory::add_item_to_group().
remove_item()
virtual bool Item_spawn_data::remove_item (const itype_id & itemid) pure virtual
For item blacklisted, remove the given item from this and all linked groups.
Implemented in Single_item_creator, and Item_group.
Referenced by Item_factory::add_item_to_group(), and Single_item_creator::remove_item().
replace_item()
virtual bool Item_spawn_data::replace_item (const itype_id & itemid, const itype_id & replacementid) pure virtual
Implemented in Single_item_creator, and Item_group.
Referenced by Single_item_creator::replace_item().
Member Data Documentation
probability
int Item_spawn_data::probability
probability, used by the parent object.
Definition at line 142 of file item_group.h.
Referenced by Item_group::add_group_entry(), Item_group::add_item_entry(), Item_group::create(), Item_group::create_single(), and Item_group::Item_group().
The documentation for this class was generated from the following files:
src/item_group.h
src/item_group.cpp