Cataclysm BN: read_inventory_preset Class Reference
read_inventory_preset Class Reference final
Public Member Functions
read_inventory_preset (const player &p)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
nc_color get_color (const inventory_entry &entry) const override
Color that will be used to display the entry string.
bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const override
Splits books into groups: Unknown, CanTrainSkill, CanNotTrainSkillAnymore, ForFun.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Private Member Functions
const islot_book & get_book (const item_location &loc) const
bool is_known (const item_location &loc) const
int get_known_recipes (const islot_book &book) const
Private Attributes
const player & p
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Detailed Description
Definition at line 975 of file game_inventory.cpp.
Constructor & Destructor Documentation
read_inventory_preset()
read_inventory_preset::read_inventory_preset (const player & p) inline
Definition at line 978 of file game_inventory.cpp.
                                                 : p( p ) {
            const std::string unknown = _( "<color_dark_gray>?</color>" );
            append_cell( [ this, &p ]( const item_location & loc ) -> std::string {
                if( loc->type->can_use( "MA_MANUAL" ) ) {
                    return _( "martial arts" );
                }
                const islot_book &book = get_book( loc );
                if( !book.skill ) {
                    return std::string();
                }
                const SkillLevel &skill = p.get_skill_level_object( book.skill );
                if( !skill.can_train() ) {
                    return std::string();
                }
                if( skill.level() < book.req ) {
                    //~ %1$s: book skill name, %3$d: book required skill level, %3$d: book skill level, %4$d: player skill level
                    return string_format( pgettext( "skill", "%1$s from %2$d to %3$d (%4$d)" ), book.skill->name(),
                                          book.req, book.level,
                                          skill.level() );
                }
                //~ %1$s: book skill name, %2$d: book skill level, %3$d: player skill level
                return string_format( pgettext( "skill", "%1$s to %2$d (%3$d)" ), book.skill->name(), book.level,
                                      skill.level() );
            }, _( "TRAINS (CURRENT)" ), unknown );
            append_cell( [ this ]( const item_location & loc ) -> std::string {
                const islot_book &book = get_book( loc );
                const int unlearned = book.recipes.size() - get_known_recipes( book );
                return unlearned > 0 ? std::to_string( unlearned ) : std::string();
            }, _( "RECIPES" ), unknown );
            append_cell( [ &p ]( const item_location & loc ) -> std::string {
                return good_bad_none( character_funcs::get_book_fun_for( p, *loc ) );
            }, _( "FUN" ), unknown );
            append_cell( [ this, &p, unknown ]( const item_location & loc ) -> std::string {
                std::vector<std::string> dummy;
                // This is terrible and needs to be removed asap when this entire file is refactored
                // to use the new avatar class
                const player *reader = nullptr;
                if( const avatar *av = p.as_avatar() ) {
                    reader = av->get_book_reader( *loc, dummy );
                } else if( const npc *n = p.as_npc() ) {
                    reader = n;
                }
                if( reader == nullptr ) {
                    return unknown;
                }
                int time_to_read = 0;
                // HACK: Need to refactor this
                // after moving reading methods from `npc` and `avatar`.
                if( const npc *npc_reader = reader->as_npc() ) {
                    time_to_read = npc_reader->time_to_read( *loc, *reader );
                } else if( const avatar *av = reader->as_avatar() ) {
                    time_to_read = av->time_to_read( *loc, *reader );
                } else {
                    debugmsg( "Reader is not NPC or avatar" );
                    time_to_read = 1;
                }
                // Actual reading time (in turns). Can be penalized.
                const int actual_turns = time_to_read / to_moves<int>( 1_turns );
                const std::string duration = to_string_approx( time_duration::from_turns( actual_turns ), false );
                // Theoretical reading time (in turns) based on the reader speed. Free of penalties.
                const int normal_turns = get_book( loc ).time * reader->read_speed() / to_moves<int>( 1_turns );
                if( actual_turns > normal_turns ) { // Longer - complicated stuff.
                    return string_format( "<color_light_red>%s</color>", duration );
                }
                return duration; // Normal speed.
            }, _( "CHAPTER IN" ), unknown );
        }
References _, inventory_selector_preset::append_cell(), Creature::as_avatar(), Creature::as_npc(), itype::can_use(), time_duration::from_turns(), get_book(), character_funcs::get_book_fun_for(), get_known_recipes(), Character::get_skill_level_object(), anonymous_namespace{game_inventory.cpp}::good_bad_none(), p, pgettext(), Character::read_speed(), islot_book::recipes, string_format(), islot_book::time, to_string(), to_string_approx(), item::type, and unknown.
Member Function Documentation
get_book()
const islot_book & read_inventory_preset::get_book (const item_location & loc) const inline private
Definition at line 1195 of file game_inventory.cpp.
{
            return *loc->type->book;
        }
References itype::book, and item::type.
Referenced by read_inventory_preset(), and sort_compare().
get_color()
nc_color read_inventory_preset::get_color (const inventory_entry & entry) const inline override virtual
Color that will be used to display the entry string.
Reimplemented from inventory_selector_preset.
Definition at line 1077 of file game_inventory.cpp.
{
            if( !entry.is_item() ) {
                return inventory_selector_preset::get_color( entry );
            }
            return entry.any_item()->color_in_inventory( p );
        }
References inventory_entry::any_item(), item::color_in_inventory(), inventory_selector_preset::get_color(), inventory_entry::is_item(), and p.
get_denial()
std::string read_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 1061 of file game_inventory.cpp.
{
            // This is terrible and needs to be removed asap when this entire file is refactored
            // to use the new avatar class
            const avatar *u = p.as_avatar();
            if( !u ) {
                return std::string();
            }
            std::vector<std::string> denials;
            if( u->get_book_reader( *loc, denials ) == nullptr && !denials.empty() &&
                !loc->type->can_use( "learn_spell" ) && u->has_identified( loc->typeId() ) ) {
                return std::move( denials.front() );
            }
            return std::string();
        }
References Creature::as_avatar(), itype::can_use(), avatar::get_book_reader(), avatar::has_identified(), avatar_action::move(), p, item::type, and item::typeId().
get_known_recipes()
int read_inventory_preset::get_known_recipes (const islot_book & book) const inline private
Definition at line 1208 of file game_inventory.cpp.
{
            int res = 0;
            for( const auto &elem : book.recipes ) {
                if( p.knows_recipe( elem.recipe ) ) {
                    ++res; // If the player knows it, they recognize it even if it's not clearly stated.
                }
            }
            return res;
        }
References Character::knows_recipe(), p, and islot_book::recipes.
Referenced by read_inventory_preset().
is_known()
bool read_inventory_preset::is_known (const item_location & loc) const inline private
Definition at line 1199 of file game_inventory.cpp.
{
            // This is terrible and needs to be removed asap when this entire file is refactored
            // to use the new avatar class
            if( const avatar *u = dynamic_cast<const avatar *>( &p ) ) {
                return u->has_identified( loc->typeId() );
            }
            return false;
        }
References player::has_identified(), p, and item::typeId().
Referenced by sort_compare().
is_shown()
bool read_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 1057 of file game_inventory.cpp.
{
            return loc->is_book();
        }
References item::is_book().
sort_compare()
bool read_inventory_preset::sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const inline override virtual
Splits books into groups: Unknown, CanTrainSkill, CanNotTrainSkillAnymore, ForFun.
Unknown sorted by default algorithm.
CanTrainSkill grouped by skill and sorted by time to read because player probably wants to level up certain skill faster.
CanNotTrainSkillAnymore grouped by skill.
ForFun sorted to make most fun books first.
Reimplemented from inventory_selector_preset.
Definition at line 1091 of file game_inventory.cpp.
{
            const bool base_sort = inventory_selector_preset::sort_compare( lhs, rhs );
            // Player doesn't really interested if NPC knows about book.
            if( p.is_avatar() ) {
                const bool known_a = is_known( lhs.any_item() );
                const bool known_b = is_known( rhs.any_item() );
                // If we don't know book, it should be first.
                // Since we don't know it's contents,
                // we don't apply our skill based sortings here.
                if( !known_a || !known_b ) {
                    return ( !known_a && !known_b ) ? base_sort : !known_a;
                }
            }
            struct localized_string {
                std::string s;
                bool operator==( const localized_string &other ) const {
                    return s == other.s;
                }
                bool operator<( const localized_string &other ) const {
                    return localized_compare( s, other.s );
                }
            };
            // Used to unify martial arts and skills.
            struct book_info {
                    bool can_teach = false;
                    bool can_still_learn = false;
                    bool is_learnable_already = true;
                    int time_to_levelup = 0;
                    int fun = 0;
                    book_info( const islot_book &book, const player &p ):
                        time_to_levelup( book.time ),
                        fun( book.fun ),
                        book( book ) {
                        if( book.martial_art ) {
                            can_teach = true;
                            can_still_learn = !p.martial_arts_data->has_martialart( book.martial_art );
                        }
                        if( book.skill ) {
                            const int skill_level = p.get_skill_level( book.skill );
                            can_teach = true;
                            can_still_learn = skill_level < book.level;
                            is_learnable_already = skill_level >= book.req;
                        }
                    }
                    localized_string get_localized_skill()const {
                        assert( can_teach );
                        if( book.martial_art ) {
                            return { _( "martial arts" ) };
                        }
                        return { book.skill->name() };
                    }
                private:
                    const islot_book &book;
            };
            const islot_book &book_a = get_book( lhs.any_item() );
            const islot_book &book_b = get_book( rhs.any_item() );
            const book_info info_a( book_a, p );
            const book_info info_b( book_b, p );
            if( !info_a.can_teach && !info_b.can_teach ) {
                return ( info_a.fun == info_b.fun ) ? base_sort : info_a.fun > info_b.fun;
            } else if( info_a.can_teach != info_b.can_teach ) {
                return info_a.can_teach;
            }
            if( info_a.can_still_learn != info_b.can_still_learn ) {
                return info_a.can_still_learn;
            }
            const bool can_still_learn = info_a.can_still_learn;
            const localized_string skill_a = info_a.get_localized_skill();
            const localized_string skill_b = info_b.get_localized_skill();
            if( can_still_learn ) {
                const auto a = std::make_tuple(
                                   skill_a,
                                   info_a.is_learnable_already ? 0 : 1,
                                   info_a.time_to_levelup
                               );
                const auto b = std::make_tuple(
                                   skill_b,
                                   info_b.is_learnable_already ? 0 : 1,
                                   info_b.time_to_levelup
                               );
                return ( a == b ) ? base_sort : ( a < b );
            }
            if( skill_a == skill_b ) {
                return base_sort;
            }
            return skill_a < skill_b;
        }
References _, a, inventory_entry::any_item(), b, islot_book::fun, get_book(), Character::get_skill_level(), Creature::is_avatar(), is_known(), islot_book::level, localized_compare, islot_book::martial_art, Character::martial_arts_data, Skill::name(), operator<(), coords::operator==(), other, p, islot_book::req, islot_book::skill, inventory_selector_preset::sort_compare(), and islot_book::time.
Member Data Documentation
p
const player& read_inventory_preset::p private
Definition at line 1218 of file game_inventory.cpp.
Referenced by get_color(), get_denial(), get_known_recipes(), is_known(), read_inventory_preset(), and sort_compare().
The documentation for this class was generated from the following file:
src/game_inventory.cpp