Cataclysm BN: ime_sentry Class Reference
ime_sentry Class Reference
used before text input to change IME mode and auto-restore IME mode when leaving the scope
#include <ime.h>
Public Types
enum mode { enable = 0 , disable = 1 , keep = 2 }
Public Member Functions
ime_sentry (mode m=enable)
~ime_sentry ()
Private Attributes
bool previously_enabled
Detailed Description
used before text input to change IME mode and auto-restore IME mode when leaving the scope
Definition at line 14 of file ime.h.
Member Enumeration Documentation
mode
enum ime_sentry::mode
Enumerator
enable
disable
keep
Definition at line 17 of file ime.h.
                  {
            enable = 0,
            disable = 1,
            keep = 2,
        };
Constructor & Destructor Documentation
ime_sentry()
ime_sentry::ime_sentry (ime_sentry::mode m = enable)
Definition at line 137 of file ime.cpp.
                                         : previously_enabled( ime_enabled() )
{
    switch( m ) {
        case enable:
            enable_ime();
            break;
        case disable:
            disable_ime();
            break;
        case keep:
            // do nothing
            break;
    }
}
References disable, disable_ime(), enable, enable_ime(), and keep.
~ime_sentry()
ime_sentry::~ime_sentry ()
Definition at line 152 of file ime.cpp.
{
    if( previously_enabled ) {
        enable_ime();
    } else {
        disable_ime();
    }
}
References disable_ime(), enable_ime(), and previously_enabled.
Member Data Documentation
previously_enabled
bool ime_sentry::previously_enabled private
Definition at line 26 of file ime.h.
Referenced by ~ime_sentry().
The documentation for this class was generated from the following files:
src/ime.h
src/ime.cpp