Cataclysm BN: comestible_filtered_inventory_preset Class Reference
comestible_filtered_inventory_preset Class Reference
Public Member Functions
comestible_filtered_inventory_preset (const player &p, bool(*predicate)(const item &it))
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
Public Member Functions inherited from comestible_inventory_preset
comestible_inventory_preset (const player &p)
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const override
Whether the first item is considered to go before the second.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Private Attributes
bool(* predicate)(const item &it)
Additional Inherited Members
Protected Member Functions inherited from comestible_inventory_preset
int get_order (const item_location &loc, const time_duration &time) const
const item & get_consumable_item (const item_location &loc) const
const islot_comestible & get_edible_comestible (const item_location &loc) const
const islot_comestible & get_edible_comestible (const item &it) const
time_duration get_time_left (const item_location &loc) const
std::string get_time_left_rounded (const item_location &loc) const
std::string get_freshness (const item_location &loc)
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Detailed Description
Definition at line 770 of file game_inventory.cpp.
Constructor & Destructor Documentation
comestible_filtered_inventory_preset()
comestible_filtered_inventory_preset::comestible_filtered_inventory_preset (const player & p, bool(*)(const item &it) predicate) inline
Definition at line 773 of file game_inventory.cpp.
                                                                                                      :
            comestible_inventory_preset( p ), predicate( predicate ) {}
Member Function Documentation
is_shown()
bool comestible_filtered_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from comestible_inventory_preset.
Definition at line 776 of file game_inventory.cpp.
{
            return comestible_inventory_preset::is_shown( loc ) &&
                   predicate( get_consumable_item( loc ) );
        }
References comestible_inventory_preset::get_consumable_item(), comestible_inventory_preset::is_shown(), and predicate.
Member Data Documentation
predicate
bool(* comestible_filtered_inventory_preset::predicate) (const item &it) private
Definition at line 782 of file game_inventory.cpp.
Referenced by is_shown().
The documentation for this class was generated from the following file:
src/game_inventory.cpp