Cataclysm BN: SkillLevel Class Reference
SkillLevel Class Reference
#include <skill.h>
Public Member Functions
SkillLevel ()=default
bool isTraining () const
bool toggleTraining ()
int level () const
int level (int plevel)
int highestLevel () const
int exercise (bool raw=false) const
int exercised_level () const
void train (int amount, bool skip_scaling=false)
bool isRusting () const
bool rust (bool charged_bio_mem, int character_rate)
void practice ()
bool can_train () const
void readBook (int minimumGain, int maximumGain, int maximumLevel=-1)
bool operator== (const SkillLevel &b) const
bool operator< (const SkillLevel &b) const
bool operator> (const SkillLevel &b) const
bool operator== (const int &b) const
bool operator< (const int &b) const
bool operator> (const int &b) const
bool operator!= (const SkillLevel &b) const
bool operator<= (const SkillLevel &b) const
bool operator>= (const SkillLevel &b) const
bool operator!= (const int &b) const
bool operator<= (const int &b) const
bool operator>= (const int &b) const
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Private Attributes
int _level = 0
int _exercise = 0
time_point _lastPracticed = calendar::turn
bool _isTraining = true
int _highestLevel = 0
Detailed Description
Definition at line 106 of file skill.h.
Constructor & Destructor Documentation
SkillLevel()
SkillLevel::SkillLevel () default
Member Function Documentation
can_train()
bool SkillLevel::can_train () const
Definition at line 311 of file skill.cpp.
{
    return get_option<float>( "SKILL_TRAINING_SPEED" ) > 0.0;
}
Referenced by item::book_info(), player::calc_focus_equilibrium(), item::color_in_inventory(), avatar::do_read(), draw_skills_tab(), npc::finish_read(), player_activity::get_progress_message(), player::practice(), and skim_book_msg().
deserialize()
void SkillLevel::deserialize (JsonIn & jsin)
Definition at line 302 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    data.read( "level", _level );
    data.read( "exercise", _exercise );
    data.read( "istraining", _isTraining );
    if( !data.read( "lastpracticed", _lastPracticed ) ) {
        _lastPracticed = calendar::start_of_cataclysm + time_duration::from_hours(
                             get_option<int>( "INITIAL_TIME" ) );
    }
    data.read( "highestlevel", _highestLevel );
    if( _highestLevel < _level ) {
        _highestLevel = _level;
    }
}
References _exercise, _highestLevel, _isTraining, _lastPracticed, _level, JsonObject::allow_omitted_members(), time_duration::from_hours(), JsonIn::get_object(), JsonObject::read(), and calendar::start_of_cataclysm.
exercise()
int SkillLevel::exercise (bool raw = false) const inline
Definition at line 140 of file skill.h.
{
            return raw ? _exercise : _exercise / ( ( _level + 1 ) * ( _level + 1 ) );
        }
References _exercise, and _level.
Referenced by avatar::do_read(), draw_skills_tab(), exercised_level(), dialogue::gen_responses(), player_activity::get_progress_message(), serialize(), and memorial_logger::write().
exercised_level()
int SkillLevel::exercised_level () const inline
Definition at line 144 of file skill.h.
{
            return level() * level() * 100 + exercise();
        }
References exercise(), and level().
highestLevel()
int SkillLevel::highestLevel () const inline
Definition at line 136 of file skill.h.
{
            return _highestLevel;
        }
References _highestLevel.
Referenced by serialize().
isRusting()
bool SkillLevel::isRusting () const
Definition at line 263 of file skill.cpp.
{
    return get_option<std::string>( "SKILL_RUST" ) != "off" && ( _level > 0 ) &&
           calendar::turn - _lastPracticed > rustRate( _level );
}
References _lastPracticed, _level, anonymous_namespace{skill.cpp}::rustRate(), and calendar::turn.
Referenced by draw_skills_tab().
isTraining()
bool SkillLevel::isTraining () const inline
Definition at line 117 of file skill.h.
{
            return _isTraining;
        }
References _isTraining.
Referenced by draw_skills_tab(), player::practice(), and serialize().
level() [1/2]
int SkillLevel::level () const inline
Definition at line 125 of file skill.h.
{
            return _level;
        }
References _level.
Referenced by item::book_info(), player::calc_focus_equilibrium(), avatar::do_read(), Character::do_skill_rust(), draw_skills_tab(), exercised_level(), npc::finish_read(), dialogue::gen_responses(), player_activity::get_progress_message(), SkillLevelMap::get_skill_level(), player::handle_skill_warning(), SkillLevelMap::mod_skill_level(), player::practice(), serialize(), Character::set_skill_level(), and memorial_logger::write().
level() [2/2]
int SkillLevel::level (int plevel) inline
Definition at line 128 of file skill.h.
{
            _level = plevel;
            if( _level > _highestLevel ) {
                _highestLevel = _level;
            }
            return plevel;
        }
References _highestLevel, and _level.
operator!=() [1/2]
bool SkillLevel::operator!= (const int & b) const inline
Definition at line 186 of file skill.h.
{
            return !( *this == b );
        }
References b.
operator!=() [2/2]
bool SkillLevel::operator!= (const SkillLevel & b) const inline
Definition at line 176 of file skill.h.
{
            return !( *this == b );
        }
References b.
operator<() [1/2]
bool SkillLevel::operator< (const int & b) const inline
Definition at line 169 of file skill.h.
{
            return this->_level < b;
        }
References b.
operator<() [2/2]
bool SkillLevel::operator< (const SkillLevel & b) const inline
Definition at line 159 of file skill.h.
{
            return this->_level < b._level || ( this->_level == b._level && this->_exercise < b._exercise );
        }
References b.
operator<=() [1/2]
bool SkillLevel::operator<= (const int & b) const inline
Definition at line 189 of file skill.h.
{
            return !( *this > b );
        }
References b.
operator<=() [2/2]
bool SkillLevel::operator<= (const SkillLevel & b) const inline
Definition at line 179 of file skill.h.
{
            return !( *this > b );
        }
References b.
operator==() [1/2]
bool SkillLevel::operator== (const int & b) const inline
Definition at line 166 of file skill.h.
{
            return this->_level == b;
        }
References b.
operator==() [2/2]
bool SkillLevel::operator== (const SkillLevel & b) const inline
Definition at line 156 of file skill.h.
{
            return this->_level == b._level && this->_exercise == b._exercise;
        }
References b.
operator>() [1/2]
bool SkillLevel::operator> (const int & b) const inline
Definition at line 172 of file skill.h.
{
            return this->_level > b;
        }
References b.
operator>() [2/2]
bool SkillLevel::operator> (const SkillLevel & b) const inline
Definition at line 162 of file skill.h.
{
            return this->_level > b._level || ( this->_level == b._level && this->_exercise > b._exercise );
        }
References b.
operator>=() [1/2]
bool SkillLevel::operator>= (const int & b) const inline
Definition at line 192 of file skill.h.
{
            return !( *this < b );
        }
References b.
operator>=() [2/2]
bool SkillLevel::operator>= (const SkillLevel & b) const inline
Definition at line 182 of file skill.h.
{
            return !( *this < b );
        }
References b.
practice()
void SkillLevel::practice ()
Definition at line 297 of file skill.cpp.
{
    _lastPracticed = calendar::turn;
}
References _lastPracticed, and calendar::turn.
Referenced by player::practice(), readBook(), and debug_menu::wishskill().
readBook()
void SkillLevel::readBook (int minimumGain, int maximumGain, int maximumLevel = -1)
Definition at line 302 of file skill.cpp.
{
    if( _level < maximumLevel || maximumLevel < 0 ) {
        train( ( _level + 1 ) * rng( minimumGain, maximumGain ) );
    }
    practice();
}
References _level, practice(), rng(), and train().
Referenced by avatar::do_read(), and npc::finish_read().
rust()
bool SkillLevel::rust (bool charged_bio_mem, int character_rate)
Definition at line 269 of file skill.cpp.
{
    const time_duration delta = calendar::turn - _lastPracticed;
    const float char_rate = character_rate / 100.0;
    const time_duration skill_rate = rustRate( _level );
    if( to_turns<int>( skill_rate ) * char_rate <= 0 || delta <= 0_turns ||
        delta % ( skill_rate * char_rate ) != 0_turns ) {
        return false;
    }
    if( charged_bio_mem ) {
        return one_in( 5 );
    }
    _exercise -= _level;
    const std::string &rust_type = get_option<std::string>( "SKILL_RUST" );
    if( _exercise < 0 ) {
        if( rust_type == "vanilla" || rust_type == "int" ) {
            _exercise = ( 100 * _level * _level ) - 1;
            --_level;
        } else {
            _exercise = 0;
        }
    }
    return false;
}
References _exercise, _lastPracticed, _level, one_in(), anonymous_namespace{skill.cpp}::rustRate(), and calendar::turn.
Referenced by Character::do_skill_rust().
serialize()
void SkillLevel::serialize (JsonOut & json) const
Definition at line 291 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "level", level() );
    json.member( "exercise", exercise( true ) );
    json.member( "istraining", isTraining() );
    json.member( "lastpracticed", _lastPracticed );
    json.member( "highestlevel", highestLevel() );
    json.end_object();
}
References _lastPracticed, JsonOut::end_object(), exercise(), highestLevel(), isTraining(), level(), JsonOut::member(), and JsonOut::start_object().
toggleTraining()
bool SkillLevel::toggleTraining () inline
Definition at line 120 of file skill.h.
{
            _isTraining = !_isTraining;
            return _isTraining;
        }
References _isTraining.
Referenced by handle_player_display_action().
train()
void SkillLevel::train (int amount, bool skip_scaling = false)
Definition at line 223 of file skill.cpp.
{
    // Working off rust to regain levels goes twice as fast as reaching levels in the first place
    if( _level < _highestLevel ) {
        amount *= 2;
    }
    if( skip_scaling ) {
        _exercise += amount;
    } else {
        const double scaling = get_option<float>( "SKILL_TRAINING_SPEED" );
        if( scaling > 0.0 ) {
            _exercise += roll_remainder( amount * scaling );
        }
    }
    if( _exercise >= 100 * ( _level + 1 ) * ( _level + 1 ) ) {
        _exercise = 0;
        ++_level;
        if( _level > _highestLevel ) {
            _highestLevel = _level;
        }
    }
}
References _exercise, _highestLevel, _level, and roll_remainder().
Referenced by dialogue::gen_responses(), player::practice(), readBook(), and activity_handlers::train_finish().
Member Data Documentation
_exercise
int SkillLevel::_exercise = 0 private
Definition at line 109 of file skill.h.
Referenced by deserialize(), exercise(), rust(), and train().
_highestLevel
int SkillLevel::_highestLevel = 0 private
Definition at line 112 of file skill.h.
Referenced by deserialize(), highestLevel(), level(), and train().
_isTraining
bool SkillLevel::_isTraining = true private
Definition at line 111 of file skill.h.
Referenced by deserialize(), isTraining(), and toggleTraining().
_lastPracticed
time_point SkillLevel::_lastPracticed = calendar::turn private
Definition at line 110 of file skill.h.
Referenced by deserialize(), isRusting(), practice(), rust(), and serialize().
_level
int SkillLevel::_level = 0 private
Definition at line 108 of file skill.h.
Referenced by deserialize(), exercise(), isRusting(), level(), readBook(), rust(), and train().
The documentation for this class was generated from the following files:
src/skill.h
src/savegame_json.cpp
src/skill.cpp