Cataclysm BN: distribution_grid_tracker Class Reference
distribution_grid_tracker Class Reference
Contains and manages all the active distribution grids.
#include <distribution_grid.h>
Public Member Functions
distribution_grid_tracker ()
distribution_grid_tracker (mapbuffer &buffer)
distribution_grid_tracker (distribution_grid_tracker &&)=default
distribution_grid & grid_at (const tripoint_abs_ms &p)
Gets grid at given global map square coordinate.
const distribution_grid & grid_at (const tripoint_abs_ms &p) const
std::uintptr_t debug_grid_id (const tripoint_abs_omt &omp) const
Identify grid at given overmap tile (for debug purposes).
void update (time_point to)
grid_furn_transform_queue & get_transform_queue ()
void load (half_open_rectangle< point_abs_sm > area)
Loads grids in an area given by submap coords.
void load (const map &m)
Loads grids in the same area as a given map.
void on_changed (const tripoint_abs_ms &p)
Updates grid at given global map square coordinate.
void on_saved ()
void on_options_changed ()
Private Member Functions
distribution_grid & make_distribution_grid_at (const tripoint_abs_sm &sm_pos)
Private Attributes
std::map< tripoint_abs_sm, shared_ptr_fast< distribution_grid > > parent_distribution_grids
Mapping of sm position to grid it belongs to.
half_open_rectangle< point_abs_sm > bounds
In submap coords, to mirror map.
mapbuffer & mb
grid_furn_transform_queue transform_queue
std::unordered_set< shared_ptr_fast< distribution_grid > > grids_requiring_updates
Most grids are empty or idle, this contains the rest.
Detailed Description
Contains and manages all the active distribution grids.
Definition at line 114 of file distribution_grid.h.
Constructor & Destructor Documentation
distribution_grid_tracker() [1/3]
distribution_grid_tracker::distribution_grid_tracker ()
Definition at line 173 of file distribution_grid.cpp.
    : distribution_grid_tracker( MAPBUFFER )
{}
distribution_grid_tracker() [2/3]
distribution_grid_tracker::distribution_grid_tracker (mapbuffer & buffer)
Definition at line 177 of file distribution_grid.cpp.
    : mb( buffer )
{
}
distribution_grid_tracker() [3/3]
distribution_grid_tracker::distribution_grid_tracker (distribution_grid_tracker &&) default
Member Function Documentation
debug_grid_id()
std::uintptr_t distribution_grid_tracker::debug_grid_id (const tripoint_abs_omt & omp) const
Identify grid at given overmap tile (for debug purposes).
Returns
0 if there's no grid.
Definition at line 281 of file distribution_grid.cpp.
{
    tripoint_abs_sm sm_pos = project_to<coords::sm>( omp );
    auto iter = parent_distribution_grids.find( sm_pos );
    if( iter != parent_distribution_grids.end() ) {
        distribution_grid *ret = iter->second.get();
        return reinterpret_cast<std::uintptr_t>( ret );
    } else {
        return 0;
    }
}
References parent_distribution_grids, and cata::hash64_detail::ret.
Referenced by overmap_ui::grids_draw_data::get_active().
get_transform_queue()
grid_furn_transform_queue & distribution_grid_tracker::get_transform_queue () inline
Definition at line 161 of file distribution_grid.h.
{
            return transform_queue;
        }
References transform_queue.
Referenced by charge_watcher_tile::update_internal(), and steady_consumer_tile::update_internal().
grid_at() [1/2]
distribution_grid & distribution_grid_tracker::grid_at (const tripoint_abs_ms & p)
Gets grid at given global map square coordinate.
map::getabs
Definition at line 263 of file distribution_grid.cpp.
{
    tripoint_abs_sm sm_pos = project_to<coords::sm>( p );
    auto iter = parent_distribution_grids.find( sm_pos );
    if( iter != parent_distribution_grids.end() ) {
        return *iter->second;
    }
    // This is ugly for the const case
    return make_distribution_grid_at( sm_pos );
}
References make_distribution_grid_at(), and parent_distribution_grids.
Referenced by iexamine::check_power(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source(), inventory::form_from_map(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), grid_at(), iuse::report_grid_charge(), use_charges_from_furn(), and iexamine::use_furn_fake_item().
grid_at() [2/2]
const distribution_grid & distribution_grid_tracker::grid_at (const tripoint_abs_ms & p) const
Definition at line 275 of file distribution_grid.cpp.
{
    return const_cast<const distribution_grid &>(
               const_cast<distribution_grid_tracker *>( this )->grid_at( p ) );
}
References grid_at().
load() [1/2]
void distribution_grid_tracker::load (const map & m)
Loads grids in the same area as a given map.
Definition at line 359 of file distribution_grid.cpp.
{
    point_abs_sm p_min( m.get_abs_sub().xy() );
    point_abs_sm p_max( p_min + point( m.getmapsize(), m.getmapsize() ) );
    load( half_open_rectangle<point_abs_sm>( p_min, p_max ) );
}
References map::get_abs_sub(), map::getmapsize(), load(), and tripoint::xy().
load() [2/2]
void distribution_grid_tracker::load (half_open_rectangle< point_abs_sm > area)
Loads grids in an area given by submap coords.
Definition at line 353 of file distribution_grid.cpp.
{
    bounds = area;
    on_saved();
}
References bounds, and on_saved().
Referenced by load().
make_distribution_grid_at()
distribution_grid & distribution_grid_tracker::make_distribution_grid_at (const tripoint_abs_sm & sm_pos) private
Parameters
omt_pos Absolute submap position of one of the tiles of the grid.
Definition at line 182 of file distribution_grid.cpp.
{
    if( !get_option<bool>( "ELECTRIC_GRID" ) ) {
        return empty_grid;
    }
    const std::set<tripoint_abs_omt> overmap_positions = overmap_buffer.electric_grid_at(
                project_to<coords::omt>( sm_pos ) );
    assert( !overmap_positions.empty() );
    std::vector<tripoint_abs_sm> submap_positions;
    for( const tripoint_abs_omt &omp : overmap_positions ) {
        tripoint_abs_sm tp = project_to<coords::sm>( omp );
        submap_positions.emplace_back( tp + point_zero );
        submap_positions.emplace_back( tp + point_east );
        submap_positions.emplace_back( tp + point_south );
        submap_positions.emplace_back( tp + point_south_east );
    }
    shared_ptr_fast<distribution_grid> dist_grid = make_shared_fast<distribution_grid>
            ( submap_positions, mb );
    for( const tripoint_abs_sm &smp : submap_positions ) {
        shared_ptr_fast<distribution_grid> &old_grid = parent_distribution_grids[smp];
        if( old_grid != dist_grid ) {
            grids_requiring_updates.erase( old_grid );
            old_grid = dist_grid;
        }
    }
    if( !dist_grid->empty() ) {
        grids_requiring_updates.emplace( dist_grid );
    }
    // This ugly expression + lint suppresion are needed to convince clang-tidy
    // that we are, in fact, NOT leaking memory.
    return *parent_distribution_grids[submap_positions.front()];
    // NOLINTNEXTLINE(clang-analyzer-cplusplus.NewDeleteLeaks)
}
References overmapbuffer::electric_grid_at(), empty_grid, grids_requiring_updates, mb, overmap_buffer, parent_distribution_grids, point_east, point_south, point_south_east, and point_zero.
Referenced by grid_at(), on_changed(), and on_saved().
on_changed()
void distribution_grid_tracker::on_changed (const tripoint_abs_ms & p)
Updates grid at given global map square coordinate.
Definition at line 247 of file distribution_grid.cpp.
{
    tripoint_abs_sm sm_pos = project_to<coords::sm>( p );
    // TODO: If not in bounds, just drop the grid, rebuild lazily
    if( parent_distribution_grids.count( sm_pos ) > 0 ||
        bounds.contains( sm_pos.xy() ) ) {
        // TODO: Don't rebuild, update
        make_distribution_grid_at( sm_pos );
    }
}
References bounds, make_distribution_grid_at(), parent_distribution_grids, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by grid_furn_transform_queue::apply(), and map::furn_set().
on_options_changed()
void distribution_grid_tracker::on_options_changed ()
Definition at line 258 of file distribution_grid.cpp.
{
    on_saved();
}
References on_saved().
on_saved()
void distribution_grid_tracker::on_saved ()
Definition at line 222 of file distribution_grid.cpp.
{
    if( !get_option<bool>( "ELECTRIC_GRID" ) ||
        world_generator->active_world == nullptr ) {
        return;
    }
    tripoint_abs_sm min_bounds( bounds.p_min, -OVERMAP_DEPTH );
    tripoint_abs_sm max_bounds( bounds.p_max, OVERMAP_HEIGHT );
    tripoint_range<tripoint_abs_sm> bounds_range( min_bounds, max_bounds );
    // Remove all grids that are no longer in the bounds
    for( auto iter = parent_distribution_grids.begin(); iter != parent_distribution_grids.end(); ) {
        if( !bounds_range.is_point_inside( iter->first ) ) {
            grids_requiring_updates.erase( iter->second );
            iter = parent_distribution_grids.erase( iter );
        } else {
            ++iter;
        }
    }
    for( const tripoint_abs_sm &sm_pos : bounds_range ) {
        if( parent_distribution_grids.find( sm_pos ) == parent_distribution_grids.end() ) {
            make_distribution_grid_at( sm_pos );
        }
    }
}
References bounds, grids_requiring_updates, tripoint_range< Tripoint >::is_point_inside(), make_distribution_grid_at(), OVERMAP_DEPTH, OVERMAP_HEIGHT, parent_distribution_grids, and world_generator.
Referenced by load(), on_options_changed(), and mapbuffer::save().
update()
void distribution_grid_tracker::update (time_point to)
Definition at line 344 of file distribution_grid.cpp.
{
    for( const shared_ptr_fast<distribution_grid> &grid : grids_requiring_updates ) {
        grid->update( to );
    }
    transform_queue.apply( mb, *this, get_player_character(), get_map() );
    transform_queue.clear();
}
References grid_furn_transform_queue::apply(), grid_furn_transform_queue::clear(), get_map(), get_player_character(), grids_requiring_updates, mb, and transform_queue.
Member Data Documentation
bounds
half_open_rectangle<point_abs_sm> distribution_grid_tracker::bounds private
In submap coords, to mirror map.
Definition at line 130 of file distribution_grid.h.
Referenced by load(), on_changed(), and on_saved().
grids_requiring_updates
std::unordered_set<shared_ptr_fast<distribution_grid> > distribution_grid_tracker::grids_requiring_updates private
Most grids are empty or idle, this contains the rest.
Definition at line 139 of file distribution_grid.h.
Referenced by make_distribution_grid_at(), on_saved(), and update().
mb
mapbuffer& distribution_grid_tracker::mb private
Definition at line 132 of file distribution_grid.h.
Referenced by make_distribution_grid_at(), and update().
parent_distribution_grids
std::map<tripoint_abs_sm, shared_ptr_fast<distribution_grid> > distribution_grid_tracker::parent_distribution_grids private
Mapping of sm position to grid it belongs to.
Definition at line 120 of file distribution_grid.h.
Referenced by debug_grid_id(), grid_at(), make_distribution_grid_at(), on_changed(), and on_saved().
transform_queue
grid_furn_transform_queue distribution_grid_tracker::transform_queue private
Definition at line 134 of file distribution_grid.h.
Referenced by get_transform_queue(), and update().
The documentation for this class was generated from the following files:
src/distribution_grid.h
src/distribution_grid.cpp