Cataclysm BN: basic_memory_buffer< T, SIZE, Allocator > Class Template Reference
basic_memory_buffer< T, SIZE, Allocator > Class Template Reference final
\rst A dynamically growing memory buffer for trivially copyable/constructible types with the first SIZE elements stored in the object itself.
#include <fmtlib_format.h>
Public Types
using value_type = T
using const_reference = const T &
Public Types inherited from detail::buffer< T >
using value_type = T
using const_reference = const T &
Public Member Functions
basic_memory_buffer (const Allocator &alloc=Allocator())
~basic_memory_buffer ()
basic_memory_buffer (basic_memory_buffer &&other) FMT_NOEXCEPT
\rst Constructs a :class:fmt::basic_memory_buffer object moving the content of the other object to it.
basic_memory_buffer & operator= (basic_memory_buffer &&other) FMT_NOEXCEPT
\rst Moves the content of the other basic_memory_buffer object to this one.
Allocator get_allocator () const
void resize (size_t count)
Resizes the buffer to contain count elements.
void reserve (size_t new_capacity)
Increases the buffer capacity to new_capacity.
template<typename ContiguousRange >
void append (const ContiguousRange &range)
Public Member Functions inherited from detail::buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
T * begin () FMT_NOEXCEPT
T * end () FMT_NOEXCEPT
const T * begin () const FMT_NOEXCEPT
const T * end () const FMT_NOEXCEPT
size_t size () const FMT_NOEXCEPT
Returns the size of this buffer.
size_t capacity () const FMT_NOEXCEPT
Returns the capacity of this buffer.
T * data () FMT_NOEXCEPT
Returns a pointer to the buffer data.
const T * data () const FMT_NOEXCEPT
Returns a pointer to the buffer data.
void clear ()
Clears this buffer.
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename I >
T & operator[] (I index)
template<typename I >
const T & operator[] (I index) const
Protected Member Functions
void grow (size_t size) final FMT_OVERRIDE
Increases the buffer capacity to hold at least capacity elements.
Protected Member Functions inherited from detail::buffer< T >
buffer (size_t sz) FMT_NOEXCEPT
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
~buffer ()=default
void set (T *buf_data, size_t buf_capacity) FMT_NOEXCEPT
Sets the buffer data and capacity.
Private Member Functions
void deallocate ()
void move (basic_memory_buffer &other)
Private Attributes
T store_ [SIZE]
Allocator alloc_
Detailed Description
template<typename T, size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>>
class basic_memory_buffer< T, SIZE, Allocator >
\rst A dynamically growing memory buffer for trivially copyable/constructible types with the first SIZE elements stored in the object itself.
You can use one of the following type aliases for common character types:
+-------------—+---------------------------—+ | Type | Definition | +================+==============================+ | memory_buffer | basic_memory_buffer<char> | +-------------—+---------------------------—+ | wmemory_buffer | basic_memory_buffer<wchar_t> | +-------------—+---------------------------—+
Example**::
fmt::memory_buffer out; format_to(out, "The answer is {}.", 42);
This will append the following output to the out object:
.. code-block:: none
The answer is 42.
The output can be converted to an std::string with to_string(out). \endrst
Definition at line 740 of file fmtlib_format.h.
Member Typedef Documentation
const_reference
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> using basic_memory_buffer< T, SIZE, Allocator >::const_reference = const T&
Definition at line 762 of file fmtlib_format.h.
value_type
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> using basic_memory_buffer< T, SIZE, Allocator >::value_type = T
Definition at line 761 of file fmtlib_format.h.
Constructor & Destructor Documentation
basic_memory_buffer() [1/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer (const Allocator & alloc = Allocator()) inline explicit
Definition at line 764 of file fmtlib_format.h.
            : alloc_( alloc ) {
            this->set( store_, SIZE );
        }
References detail::buffer< T >::set().
~basic_memory_buffer()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> basic_memory_buffer< T, SIZE, Allocator >::~basic_memory_buffer () inline
Definition at line 768 of file fmtlib_format.h.
{
            deallocate();
        }
References basic_memory_buffer< T, SIZE, Allocator >::deallocate().
basic_memory_buffer() [2/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer (basic_memory_buffer< T, SIZE, Allocator > && other) inline
\rst Constructs a :class:fmt::basic_memory_buffer object moving the content of the other object to it.
\endrst
Definition at line 798 of file fmtlib_format.h.
{ move(other); }
References basic_memory_buffer< T, SIZE, Allocator >::move(), and other.
Member Function Documentation
append()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> template<typename ContiguousRange > void basic_memory_buffer< T, SIZE, Allocator >::append (const ContiguousRange & range) inline
Definition at line 833 of file fmtlib_format.h.
{
            append( range.data(), range.data() + range.size() );
        }
References basic_memory_buffer< T, SIZE, Allocator >::append().
Referenced by basic_memory_buffer< T, SIZE, Allocator >::append().
deallocate()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void basic_memory_buffer< T, SIZE, Allocator >::deallocate () inline private
Definition at line 749 of file fmtlib_format.h.
{
            T *data = this->data();
            if( data != store_ ) {
                alloc_.deallocate( data, this->capacity() );
            }
        }
References basic_memory_buffer< T, SIZE, Allocator >::alloc_, detail::buffer< T >::capacity(), detail::buffer< T >::data(), and basic_memory_buffer< T, SIZE, Allocator >::store_.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::operator=(), and basic_memory_buffer< T, SIZE, Allocator >::~basic_memory_buffer().
get_allocator()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> Allocator basic_memory_buffer< T, SIZE, Allocator >::get_allocator () const inline
Definition at line 813 of file fmtlib_format.h.
{
            return alloc_;
        }
References basic_memory_buffer< T, SIZE, Allocator >::alloc_.
grow()
template<typename T , size_t SIZE, typename Allocator > void basic_memory_buffer< T, SIZE, Allocator >::grow (size_t capacity) final protected virtual
Increases the buffer capacity to hold at least capacity elements.
Implements detail::buffer< T >.
Definition at line 839 of file fmtlib_format.h.
{
#ifdef FMT_FUZZ
    if( size > 5000 ) {
        throw std::runtime_error( "fuzz mode - won't grow that much" );
    }
#endif
    size_t old_capacity = this->capacity();
    size_t new_capacity = old_capacity + old_capacity / 2;
    if( size > new_capacity ) {
        new_capacity = size;
    }
    T *old_data = this->data();
    T *new_data =
        std::allocator_traits<Allocator>::allocate( alloc_, new_capacity );
    // The following code doesn't throw, so the raw pointer above doesn't leak.
    std::uninitialized_copy( old_data, old_data + this->size(),
                             detail::make_checked( new_data, new_capacity ) );
    this->set( new_data, new_capacity );
    // deallocate must not throw according to the standard, but even if it does,
    // the buffer already uses the new storage and will deallocate it in
    // destructor.
    if( old_data != store_ ) {
        alloc_.deallocate( old_data, old_capacity );
    }
}
References detail::make_checked(), and om_direction::size.
move()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void basic_memory_buffer< T, SIZE, Allocator >::move (basic_memory_buffer< T, SIZE, Allocator > & other) inline private
Definition at line 774 of file fmtlib_format.h.
{
            alloc_ = std::move( other.alloc_ );
            T *data = other.data();
            size_t size = other.size(), capacity = other.capacity();
            if( data == other.store_ ) {
                this->set( store_, capacity );
                std::uninitialized_copy( other.store_, other.store_ + size,
                                         detail::make_checked( store_, capacity ) );
            } else {
                this->set( data, capacity );
                // Set pointer to the inline array so that delete is not called
                // when deallocating.
                other.set( other.store_, 0 );
            }
            this->resize( size );
        }
References basic_memory_buffer< T, SIZE, Allocator >::alloc_, detail::buffer< T >::capacity(), detail::buffer< T >::data(), detail::make_checked(), avatar_action::move(), other, basic_memory_buffer< T, SIZE, Allocator >::resize(), detail::buffer< T >::set(), detail::buffer< T >::size(), and basic_memory_buffer< T, SIZE, Allocator >::store_.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), and basic_memory_buffer< T, SIZE, Allocator >::operator=().
operator=()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> basic_memory_buffer & basic_memory_buffer< T, SIZE, Allocator >::operator= (basic_memory_buffer< T, SIZE, Allocator > && other) inline
\rst Moves the content of the other basic_memory_buffer object to this one.
\endrst
Definition at line 805 of file fmtlib_format.h.
{
            FMT_ASSERT( this != &other, "" );
            deallocate();
            move( other );
            return *this;
        }
References basic_memory_buffer< T, SIZE, Allocator >::deallocate(), FMT_ASSERT, basic_memory_buffer< T, SIZE, Allocator >::move(), and other.
reserve()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void basic_memory_buffer< T, SIZE, Allocator >::reserve (size_t new_capacity) inline
Increases the buffer capacity to new_capacity.
Definition at line 826 of file fmtlib_format.h.
{
            this->try_reserve( new_capacity );
        }
References detail::buffer< T >::try_reserve().
resize()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void basic_memory_buffer< T, SIZE, Allocator >::resize (size_t count) inline
Resizes the buffer to contain count elements.
If T is a POD type new elements may not be initialized.
Definition at line 821 of file fmtlib_format.h.
{
            this->try_resize( count );
        }
References detail::buffer< T >::try_resize().
Referenced by format_system_error(), and basic_memory_buffer< T, SIZE, Allocator >::move().
Member Data Documentation
alloc_
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> Allocator basic_memory_buffer< T, SIZE, Allocator >::alloc_ private
Definition at line 746 of file fmtlib_format.h.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::deallocate(), basic_memory_buffer< T, SIZE, Allocator >::get_allocator(), and basic_memory_buffer< T, SIZE, Allocator >::move().
store_
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> T basic_memory_buffer< T, SIZE, Allocator >::store_[SIZE] private
Definition at line 743 of file fmtlib_format.h.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::deallocate(), and basic_memory_buffer< T, SIZE, Allocator >::move().
The documentation for this class was generated from the following file:
src/fmtlib_format.h