Cataclysm BN: cata::poly_serialized< T > Class Template Reference
cata::poly_serialized< T > Class Template Reference
Copyable unique_ptr that writes and reads objects of derived types.
#include <poly_serialized.h>
Public Member Functions
poly_serialized ()=default
poly_serialized (poly_serialized &&)=default
poly_serialized (T *value)
poly_serialized (const poly_serialized< T > &other)
poly_serialized & operator= (poly_serialized< T > other)
template<typename Stream = JsonOut>
void serialize (Stream &jsout) const
template<typename Stream = JsonIn>
void deserialize (Stream &jsin)
Detailed Description
template<class T>
class cata::poly_serialized< T >
Copyable unique_ptr that writes and reads objects of derived types.
Base type must implement get_type and static create.
Definition at line 18 of file poly_serialized.h.
Constructor & Destructor Documentation
poly_serialized() [1/4]
template<class T > cata::poly_serialized< T >::poly_serialized () default
poly_serialized() [2/4]
template<class T > cata::poly_serialized< T >::poly_serialized (poly_serialized< T > &&) default
poly_serialized() [3/4]
template<class T > cata::poly_serialized< T >::poly_serialized (T * value) inline
Definition at line 23 of file poly_serialized.h.
: std::unique_ptr<T>(value) {}
poly_serialized() [4/4]
template<class T > cata::poly_serialized< T >::poly_serialized (const poly_serialized< T > & other) inline
Definition at line 24 of file poly_serialized.h.
                                                           :
            std::unique_ptr<T>( other ? other.get()->clone() : nullptr ) {}
References other.
Member Function Documentation
deserialize()
template<class T > template<typename Stream = JsonIn> void cata::poly_serialized< T >::deserialize (Stream & jsin) inline
Definition at line 46 of file poly_serialized.h.
{
            jsin.start_array();
            if( jsin.test_null() ) {
                this->reset();
            } else {
                std::decay_t < decltype( this->get()->get_type() ) > read_type;
                jsin.read( read_type );
                this->reset( T::create( read_type ) );
                this->get()->deserialize( jsin );
            }
            jsin.end_array();
        }
References charge_removal_blacklist::get(), and ammo_effects::reset().
operator=()
template<class T > poly_serialized & cata::poly_serialized< T >::operator= (poly_serialized< T > other) inline
Definition at line 26 of file poly_serialized.h.
{
            std::unique_ptr<T>::operator=( std::move( other ) );
            return *this;
        }
References avatar_action::move(), and other.
serialize()
template<class T > template<typename Stream = JsonOut> void cata::poly_serialized< T >::serialize (Stream & jsout) const inline
Definition at line 32 of file poly_serialized.h.
{
            jsout.start_array();
            if( this->get() ) {
                jsout.write( this->get()->get_type() );
                jsout.start_object();
                this->get()->serialize( jsout );
                jsout.end_object();
            } else {
                jsout.write_null();
            }
            jsout.end_array();
        }
References charge_removal_blacklist::get().
The documentation for this class was generated from the following files:
src/map.h
src/poly_serialized.h