Cataclysm BN: system_error Class Reference
system_error Class Reference
An error returned by an operating system or a language runtime, for example a file opening error.
#include <fmtlib_format.h>
Public Member Functions
template<typename... Args>
system_error (int error_code, string_view message, const Args &... args)
system_error (const system_error &)=default
system_error & operator= (const system_error &)=default
system_error (system_error &&)=default
system_error & operator= (system_error &&)=default
~system_error () FMT_NOEXCEPT FMT_OVERRIDE
int error_code () const
Protected Member Functions
system_error ()
Protected Attributes
int error_code_
Private Member Functions
void init (int err_code, string_view format_str, format_args args)
Detailed Description
An error returned by an operating system or a language runtime, for example a file opening error.
Definition at line 3738 of file fmtlib_format.h.
Constructor & Destructor Documentation
system_error() [1/4]
system_error::system_error () inline protected
Definition at line 3746 of file fmtlib_format.h.
: std::runtime_error(""), error_code_(0) {}
system_error() [2/4]
template<typename... Args> system_error::system_error (int error_code, string_view message, const Args &... args) inline
     \rst
     Constructs a :class:`fmt::system_error` object with a description
     formatted with `fmt::format_system_error`. *message* and additional
     arguments passed into the constructor are formatted similarly to
     `fmt::format`.
       Example**::
This throws a system_error with the description cannot open file 'madeup': No such file or directory or similar (system message may vary). const char *filename = "madeup"; std::FILE *file = std::fopen(filename, "r"); if (!file) throw fmt::system_error(errno, "cannot open file '{}'", filename); \endrst
Definition at line 3768 of file fmtlib_format.h.
            : std::runtime_error( "" ) {
            init( error_code, message, make_format_args( args... ) );
        }
References make_format_args(), and mapgen_defer::message.
system_error() [3/4]
system_error::system_error (const system_error &) default
system_error() [4/4]
system_error::system_error (system_error &&) default
~system_error()
FMT_API FMT_FUNC system_error::~system_error () default
Member Function Documentation
error_code()
int system_error::error_code () const inline
Definition at line 3778 of file fmtlib_format.h.
{
            return error_code_;
        }
init()
FMT_FUNC void system_error::init (int err_code, string_view format_str, format_args args) private
Definition at line 253 of file fmtlib_format-inl.h.
{
    error_code_ = err_code;
    memory_buffer buffer;
    format_system_error( buffer, err_code, vformat( format_str, args ) );
    std::runtime_error &base = *this;
    base = std::runtime_error( to_string( buffer ) );
}
References format_system_error(), to_string(), and vformat().
operator=() [1/2]
system_error & system_error::operator= (const system_error &) default
operator=() [2/2]
system_error & system_error::operator= (system_error &&) default
Member Data Documentation
error_code_
int system_error::error_code_ protected
Definition at line 3744 of file fmtlib_format.h.
The documentation for this class was generated from the following files:
src/fmtlib_format.h
src/fmtlib_format-inl.h