Cataclysm BN: stomach_contents Class Reference
stomach_contents Class Reference
#include <stomach.h>
Public Member Functions
stomach_contents ()
void ingest (const food_summary &ingested)
Directly adds food to stomach contents.
food_summary digest (const needs_rates &metabolic_rates, int five_mins)
Processes food and outputs nutrients that are finished processing Metabolic rates are required because they determine the rate of absorption of nutrients into the body.
void empty ()
int get_calories () const
void mod_calories (int calories)
time_duration time_since_ate () const
void ate ()
void serialize (JsonOut &json) const
void deserialize (JsonIn &json)
Private Member Functions
stomach_digest_rates get_digest_rates (const needs_rates &metabolic_rates)
Private Attributes
nutrients nutr
time_point last_ate
Detailed Description
Definition at line 66 of file stomach.h.
Constructor & Destructor Documentation
stomach_contents()
stomach_contents::stomach_contents ()
Definition at line 103 of file stomach.cpp.
{
    empty();
    last_ate = calendar::before_time_starts;
}
References calendar::before_time_starts, empty(), and last_ate.
Member Function Documentation
ate()
void stomach_contents::ate ()
Definition at line 184 of file stomach.cpp.
{
    last_ate = calendar::turn;
}
References last_ate, and calendar::turn.
Referenced by ingest(), and Character::suffer_in_sunlight().
deserialize()
void stomach_contents::deserialize (JsonIn & json)
Definition at line 118 of file stomach.cpp.
{
    JsonObject jo = json.get_object();
    jo.read( "vitamins", nutr.vitamins );
    jo.read( "calories", nutr.kcal );
    jo.read( "last_ate", last_ate );
}
References JsonIn::get_object(), nutrients::kcal, last_ate, nutr, JsonObject::read(), and nutrients::vitamins.
digest()
food_summary stomach_contents::digest (const needs_rates & metabolic_rates, int five_mins)
Processes food and outputs nutrients that are finished processing Metabolic rates are required because they determine the rate of absorption of nutrients into the body.
Parameters
metabolic_rates The metabolic rates of the owner of this stomach
five_mins Five-minute intervals passed since this method was last called
Definition at line 132 of file stomach.cpp.
{
    food_summary digested{};
    stomach_digest_rates rates = get_digest_rates( metabolic_rates );
    // Digest kCal -- use min_kcal by default, but no more than what's in stomach,
    // and no less than percentage_kcal of what's in stomach.
    int kcal_fraction = std::lround( nutr.kcal * rates.percent_kcal );
    digested.nutr.kcal = clamp( five_mins * rates.min_kcal, five_mins * kcal_fraction, nutr.kcal );
    // Digest vitamins just like we did kCal, but we need to do one at a time.
    for( const std::pair<const vitamin_id, int> &vit : nutr.vitamins ) {
        int vit_fraction = std::lround( vit.second * rates.percent_vitamin );
        digested.nutr.vitamins[vit.first] =
            five_mins * clamp( rates.min_vitamin, vit_fraction, vit.second );
    }
    nutr -= digested.nutr;
    return digested;
}
References clamp(), get_digest_rates(), nutrients::kcal, stomach_digest_rates::min_kcal, stomach_digest_rates::min_vitamin, nutr, stomach_digest_rates::percent_kcal, stomach_digest_rates::percent_vitamin, and nutrients::vitamins.
Referenced by Character::update_stomach().
empty()
void stomach_contents::empty ()
Definition at line 153 of file stomach.cpp.
{
    nutr = nutrients{};
}
References nutr.
Referenced by stomach_contents(), and Character::vomit().
get_calories()
int stomach_contents::get_calories () const
Definition at line 179 of file stomach.cpp.
{
    return nutr.kcal;
}
References nutrients::kcal, and nutr.
Referenced by npc::address_needs(), Character::consume_effects(), npc::consume_food_from_camp(), eff_fun_hallu(), Character::get_hunger_description(), Character::suffer_from_radiation(), avatar::vomit(), Character::vomit(), player::vomit_mod(), and Character::will_eat().
get_digest_rates()
stomach_digest_rates stomach_contents::get_digest_rates (const needs_rates & metabolic_rates) private
Definition at line 158 of file stomach.cpp.
{
    stomach_digest_rates rates;
    rates.min_vitamin = 1;
    rates.percent_vitamin = 1.0f / 6.0f;
    rates.min_kcal = 100;
    rates.percent_kcal = 0.5f;
    rates.min_vitamin = std::round( 100.0 / 24.0 * metabolic_rates.hunger );
    rates.percent_vitamin = 0.05f * metabolic_rates.hunger;
    return rates;
}
References needs_rates::hunger, stomach_digest_rates::min_kcal, stomach_digest_rates::min_vitamin, stomach_digest_rates::percent_kcal, and stomach_digest_rates::percent_vitamin.
Referenced by digest().
ingest()
void stomach_contents::ingest (const food_summary & ingested)
Directly adds food to stomach contents.
Will still add contents if past maximum volume. Also updates last_ate to current turn.
Parameters
ingested The food to be ingested
Definition at line 126 of file stomach.cpp.
{
    nutr += ingested.nutr;
    ate();
}
References ate(), food_summary::nutr, and nutr.
Referenced by Character::consume_effects().
mod_calories()
void stomach_contents::mod_calories (int calories)
Definition at line 170 of file stomach.cpp.
{
    if( -cal >= nutr.kcal ) {
        nutr.kcal = 0;
        return;
    }
    nutr.kcal += cal;
}
References nutrients::kcal, and nutr.
serialize()
void stomach_contents::serialize (JsonOut & json) const
Definition at line 109 of file stomach.cpp.
{
    json.start_object();
    json.member( "vitamins", nutr.vitamins );
    json.member( "calories", nutr.kcal );
    json.member( "last_ate", last_ate );
    json.end_object();
}
References JsonOut::end_object(), nutrients::kcal, last_ate, JsonOut::member(), nutr, JsonOut::start_object(), and nutrients::vitamins.
time_since_ate()
time_duration stomach_contents::time_since_ate () const
Definition at line 189 of file stomach.cpp.
{
    return calendar::turn - last_ate;
}
References last_ate, and calendar::turn.
Member Data Documentation
last_ate
time_point stomach_contents::last_ate private
Definition at line 109 of file stomach.h.
Referenced by ate(), deserialize(), serialize(), stomach_contents(), and time_since_ate().
nutr
nutrients stomach_contents::nutr private
Definition at line 107 of file stomach.h.
Referenced by deserialize(), digest(), empty(), get_calories(), ingest(), mod_calories(), and serialize().
The documentation for this class was generated from the following files:
src/stomach.h
src/stomach.cpp