Cataclysm BN: monfaction Class Reference
monfaction Class Reference
#include <monfaction.h>
Public Member Functions
mf_attitude attitude (const mfaction_id &other) const
Public Attributes
mfaction_id loadid
mfaction_id base_faction
mfaction_str_id id
mfaction_att_map attitude_map
Detailed Description
Definition at line 28 of file monfaction.h.
Member Function Documentation
attitude()
mf_attitude monfaction::attitude (const mfaction_id & other) const
Definition at line 106 of file monfaction.cpp.
{
    const auto &found = attitude_map.find( other );
    if( found != attitude_map.end() ) {
        return found->second;
    }
    const auto base = other.obj().base_faction;
    if( other != base ) {
        return attitude( base );
    }
    // Shouldn't happen
    debugmsg( "Invalid faction relations (no relation found): %s -> %s",
              id.c_str(), other.obj().id.c_str() );
    return MFA_FRIENDLY;
}
References attitude(), attitude_map, debugmsg, MFA_FRIENDLY, and other.
Referenced by attitude(), and mattack::parrot_at_danger().
Member Data Documentation
attitude_map
mfaction_att_map monfaction::attitude_map
Definition at line 35 of file monfaction.h.
Referenced by apply_base_faction(), and attitude().
base_faction
mfaction_id monfaction::base_faction
Definition at line 32 of file monfaction.h.
Referenced by monfactions::get_or_add_faction().
id
mfaction_str_id monfaction::id
Definition at line 33 of file monfaction.h.
Referenced by monfactions::finalize(), and monfactions::get_or_add_faction().
loadid
mfaction_id monfaction::loadid
Definition at line 31 of file monfaction.h.
Referenced by monfactions::get_or_add_faction().
The documentation for this class was generated from the following files:
src/monfaction.h
src/monfaction.cpp