Cataclysm BN: fireweapon_off_actor Class Reference
fireweapon_off_actor Class Reference
Try to turn on a burning melee weapon Not iuse_transform, because they don't have that much in common.
#include <iuse_actor.h>
Public Member Functions
fireweapon_off_actor ()
~fireweapon_off_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
itype_id target_id
std::string success_message
std::string lacks_fuel_message
std::string failure_message
int noise = 0
int moves = 0
int success_chance = INT_MIN
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Try to turn on a burning melee weapon Not iuse_transform, because they don't have that much in common.
Definition at line 685 of file iuse_actor.h.
Constructor & Destructor Documentation
fireweapon_off_actor()
fireweapon_off_actor::fireweapon_off_actor () inline
Definition at line 697 of file iuse_actor.h.
: iuse_actor("fireweapon_off") {}
~fireweapon_off_actor()
fireweapon_off_actor::~fireweapon_off_actor () override default
Member Function Documentation
can_use()
ret_val< bool > fireweapon_off_actor::can_use (const Character & p, const item & it, bool , const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 2208 of file iuse_actor.cpp.
{
    if( it.charges < it.type->charges_to_use() ) {
        return ret_val<bool>::make_failure( _( "This tool doesn't have enough charges." ) );
    }
    if( p.is_underwater() ) {
        return ret_val<bool>::make_failure( _( "You can't do that while underwater." ) );
    }
    return ret_val<bool>::make_success();
}
References _, item::charges, itype::charges_to_use(), Creature::is_underwater(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and item::type.
clone()
std::unique_ptr< iuse_actor > fireweapon_off_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2175 of file iuse_actor.cpp.
{
    return std::make_unique<fireweapon_off_actor>( *this );
}
load()
void fireweapon_off_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2164 of file iuse_actor.cpp.
{
    obj.read( "target_id", target_id, true );
    success_message     = obj.get_string( "success_message", "hsss" );
    lacks_fuel_message  = obj.get_string( "lacks_fuel_message" );
    failure_message     = obj.get_string( "failure_message", "hsss" );
    noise               = obj.get_int( "noise", 0 );
    moves               = obj.get_int( "moves", 0 );
    success_chance      = obj.get_int( "success_chance", INT_MIN );
}
References failure_message, JsonObject::get_int(), JsonObject::get_string(), lacks_fuel_message, moves, noise, JsonObject::read(), success_chance, success_message, and target_id.
use()
int fireweapon_off_actor::use (player & p, item & it, bool t, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2180 of file iuse_actor.cpp.
{
    if( t ) {
        return 0;
    }
    if( it.charges <= 0 ) {
        p.add_msg_if_player( _( lacks_fuel_message ) );
        return 0;
    }
    p.moves -= moves;
    if( rng( 0, 10 ) - it.damage_level( 4 ) > success_chance && !p.is_underwater() ) {
        if( noise > 0 ) {
            sounds::sound( p.pos(), noise, sounds::sound_t::combat, _( success_message ) );
        } else {
            p.add_msg_if_player( _( success_message ) );
        }
        it.convert( target_id );
        it.active = true;
    } else if( !failure_message.empty() ) {
        p.add_msg_if_player( m_bad, _( failure_message ) );
    }
    return it.type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::charges, itype::charges_to_use(), sounds::combat, item::convert(), item::damage_level(), failure_message, Creature::is_underwater(), lacks_fuel_message, m_bad, Creature::moves, moves, noise, Character::pos(), rng(), sounds::sound(), success_chance, success_message, target_id, and item::type.
Member Data Documentation
failure_message
std::string fireweapon_off_actor::failure_message
Definition at line 691 of file iuse_actor.h.
Referenced by load(), and use().
lacks_fuel_message
std::string fireweapon_off_actor::lacks_fuel_message
Definition at line 690 of file iuse_actor.h.
Referenced by load(), and use().
moves
int fireweapon_off_actor::moves = 0
Definition at line 693 of file iuse_actor.h.
Referenced by load(), and use().
noise
int fireweapon_off_actor::noise = 0
Definition at line 692 of file iuse_actor.h.
Referenced by load(), and use().
success_chance
int fireweapon_off_actor::success_chance = INT_MIN
Definition at line 695 of file iuse_actor.h.
Referenced by load(), and use().
success_message
std::string fireweapon_off_actor::success_message
Definition at line 689 of file iuse_actor.h.
Referenced by load(), and use().
target_id
itype_id fireweapon_off_actor::target_id
Definition at line 688 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp