Cataclysm BN: cata::optional< T > Class Template Reference
cata::optional< T > Class Template Reference
#include <optional.h>
Public Member Functions
constexpr optional () noexcept
constexpr optional (const nullopt_t) noexcept
optional (const optional &other)
optional (optional &&other)
template<typename... Args>
optional (in_place_t, Args &&... args)
template<typename U , typename... Args>
optional (in_place_t, std::initializer_list< U > ilist, Args &&... args)
template<typename U = T, typename std::enable_if< !std::is_same< optional< T >, typename std::decay< U >::type >::value &&std::is_constructible< T, U && >::value &&std::is_convertible< U &&, T >::value, bool >::type = true>
optional (U &&t)
template<typename U = T, typename std::enable_if< !std::is_same< optional< T >, std::decay< U > >::value &&std::is_constructible< T, U && >::value &&!std::is_convertible< U &&, T >::value, bool >::type = false>
optional (U &&t)
~optional ()
constexpr const T * operator-> () const
T * operator-> ()
constexpr const T & operator* () const
T & operator* ()
constexpr operator bool () const noexcept
constexpr bool has_value () const noexcept
T & value ()
const T & value () const
template<typename O >
T value_or (O &&other) const
template<class... Args>
T & emplace (Args &&... args)
template<class U , class... Args>
T & emplace (std::initializer_list< U > ilist, Args &&... args)
void reset () noexcept
optional & operator= (nullopt_t) noexcept
optional & operator= (const optional &other)
optional & operator= (optional &&other)
template<class U = T, typename std::enable_if< !std::is_same< optional< T >, typename std::decay< U >::type >::value &&std::is_constructible< T, U && >::value &&std::is_convertible< U &&, T >::value, bool >::type = true>
optional & operator= (U &&value)
template<class U >
optional & operator= (const optional< U > &other)
template<class U >
optional & operator= (optional< U > &&other)
void swap (optional &other)
Private Types
using StoredType = typename std::remove_const< T >::type
Private Member Functions
T & get ()
const T & get () const
template<typename... Args>
void construct (Args &&... args)
void destruct ()
Private Attributes
union {
volatile char dont_use
char dummy
StoredType data
};
bool full
Detailed Description
template<typename T>
class cata::optional< T >
Definition at line 30 of file optional.h.
Member Typedef Documentation
StoredType
template<typename T > using cata::optional< T >::StoredType = typename std::remove_const<T>::type private
Definition at line 33 of file optional.h.
Constructor & Destructor Documentation
optional() [1/8]
template<typename T > constexpr cata::optional< T >::optional () inline constexpr noexcept
Definition at line 63 of file optional.h.
: dummy(), full(false) { }
optional() [2/8]
template<typename T > constexpr cata::optional< T >::optional (const nullopt_t) inline constexpr noexcept
Definition at line 64 of file optional.h.
: dummy(), full(false) { }
optional() [3/8]
template<typename T > cata::optional< T >::optional (const optional< T > & other) inline
Definition at line 66 of file optional.h.
                                          : full( false ) {
            if( other.full ) {
                construct( other.get() );
            }
        }
References cata::optional< T >::construct(), and other.
optional() [4/8]
template<typename T > cata::optional< T >::optional (optional< T > && other) inline
Definition at line 71 of file optional.h.
                                     : full( false ) {
            if( other.full ) {
                construct( std::move( other.get() ) );
            }
        }
References cata::optional< T >::construct(), avatar_action::move(), and other.
optional() [5/8]
template<typename T > template<typename... Args> cata::optional< T >::optional (in_place_t , Args &&... args) inline explicit
Definition at line 77 of file optional.h.
                                                         : data( std::forward<Args>( args )... ),
            full( true ) { }
optional() [6/8]
template<typename T > template<typename U , typename... Args> cata::optional< T >::optional (in_place_t , std::initializer_list< U > ilist, Args &&... args) inline explicit
Definition at line 81 of file optional.h.
                                             : data( ilist,
                                       std::forward<Args>( args )... ), full( true ) { }
optional() [7/8]
template<typename T > template<typename U = T, typename std::enable_if< !std::is_same< optional< T >, typename std::decay< U >::type >::value &&std::is_constructible< T, U && >::value &&std::is_convertible< U &&, T >::value, bool >::type = true> cata::optional< T >::optional (U && t) inline
Definition at line 91 of file optional.h.
            : optional( in_place, std::forward<U>( t ) ) { }
optional() [8/8]
template<typename T > template<typename U = T, typename std::enable_if< !std::is_same< optional< T >, std::decay< U > >::value &&std::is_constructible< T, U && >::value &&!std::is_convertible< U &&, T >::value, bool >::type = false> cata::optional< T >::optional (U && t) inline explicit
Definition at line 100 of file optional.h.
            : optional( in_place, std::forward<U>( t ) ) { }
~optional()
template<typename T > cata::optional< T >::~optional () inline
Definition at line 103 of file optional.h.
                    {
            reset();
        }
References cata::optional< T >::reset().
Member Function Documentation
construct()
template<typename T > template<typename... Args> void cata::optional< T >::construct (Args &&... args) inline private
Definition at line 53 of file optional.h.
{
            assert( !full );
            new( &data )StoredType( std::forward<Args>( args )... );
            full = true;
        }
References cata::optional< T >::data, and cata::optional< T >::full.
Referenced by cata::optional< T >::emplace(), cata::optional< T >::operator=(), cata::optional< T >::optional(), and cata::optional< T >::swap().
destruct()
template<typename T > void cata::optional< T >::destruct () inline private
Definition at line 58 of file optional.h.
{
            data.~StoredType();
        }
References cata::optional< T >::data.
Referenced by cata::optional< T >::reset(), and cata::optional< T >::swap().
emplace() [1/2]
template<typename T > template<class... Args> T & cata::optional< T >::emplace (Args &&... args) inline
Definition at line 146 of file optional.h.
{
            reset();
            construct( std::forward<Args>( args )... );
            return get();
        }
References cata::optional< T >::construct(), cata::optional< T >::get(), and cata::optional< T >::reset().
Referenced by assign(), map::bash_furn_success(), game::find_or_make_stairs(), iexamine::getNearFilledGasTank(), vehicle::init_state(), string_input_popup::query_string(), and vehicle_part_iterator< range_type >::skip_to_next_valid().
emplace() [2/2]
template<typename T > template<class U , class... Args> T & cata::optional< T >::emplace (std::initializer_list< U > ilist, Args &&... args) inline
Definition at line 152 of file optional.h.
{
            reset();
            construct( ilist, std::forward<Args>( args )... );
            return get();
        }
References cata::optional< T >::construct(), cata::optional< T >::get(), and cata::optional< T >::reset().
get() [1/2]
template<typename T > T & cata::optional< T >::get () inline private
Definition at line 43 of file optional.h.
                 {
            assert( full );
            return data;
        }
References cata::optional< T >::data, and cata::optional< T >::full.
Referenced by cata::optional< T >::emplace(), cata::optional< T >::operator*(), cata::optional< T >::operator->(), cata::optional< T >::operator=(), cata::optional< T >::swap(), cata::optional< T >::value(), and cata::optional< T >::value_or().
get() [2/2]
template<typename T > const T & cata::optional< T >::get () const inline private
Definition at line 47 of file optional.h.
{
            assert( full );
            return data;
        }
References cata::optional< T >::data, and cata::optional< T >::full.
has_value()
template<typename T > constexpr bool cata::optional< T >::has_value () const inline constexpr noexcept
Definition at line 123 of file optional.h.
{
            return full;
        }
References cata::optional< T >::full.
Referenced by computer_session::action_research(), item::basic_info(), vehicle::check_heli_ascend(), throw_activity_actor::do_turn(), overmap_ui::draw_ascii(), enumerate_objects_around_point(), game::find_or_make_stairs(), overmap_ui::get_overmap_path_to(), mapgen_function_json_base::has_vehicle_collision(), jmapgen_alternativly< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), cata::operator==(), vehicle_part_iterator< range_type >::operator==(), detail::show_mutations_ui_internal(), map::supports_above(), ranged::throw_item(), deploy_furn_actor::use(), and ui_adaptor::~ui_adaptor().
operator bool()
template<typename T > constexpr cata::optional< T >::operator bool () const inline explicit constexpr noexcept
Definition at line 120 of file optional.h.
{
            return full;
        }
References cata::optional< T >::full.
operator*() [1/2]
template<typename T > T & cata::optional< T >::operator* () inline
Definition at line 116 of file optional.h.
                       {
            return get();
        }
References cata::optional< T >::get().
operator*() [2/2]
template<typename T > constexpr const T & cata::optional< T >::operator* () const inline constexpr
Definition at line 113 of file optional.h.
{
            return get();
        }
References cata::optional< T >::get().
operator->() [1/2]
template<typename T > T * cata::optional< T >::operator-> () inline
Definition at line 110 of file optional.h.
{
            return &get();
        }
References cata::optional< T >::get().
operator->() [2/2]
template<typename T > constexpr const T * cata::optional< T >::operator-> () const inline constexpr
Definition at line 107 of file optional.h.
{
            return &get();
        }
References cata::optional< T >::get().
operator=() [1/6]
template<typename T > optional & cata::optional< T >::operator= (const optional< T > & other) inline
Definition at line 169 of file optional.h.
{
            if( full && other.full ) {
                get() = other.get();
            } else if( full ) {
                reset();
            } else if( other.full ) {
                construct( other.get() );
            }
            return *this;
        }
References cata::optional< T >::construct(), cata::optional< T >::full, cata::optional< T >::get(), other, and cata::optional< T >::reset().
operator=() [2/6]
template<typename T > template<class U > optional & cata::optional< T >::operator= (const optional< U > & other) inline
Definition at line 203 of file optional.h.
{
            if( full && other.full ) {
                get() = other.get();
            } else if( full ) {
                reset();
            } else if( other.full ) {
                construct( other.get() );
            }
            return *this;
        }
References cata::optional< T >::construct(), cata::optional< T >::full, cata::optional< T >::get(), other, and cata::optional< T >::reset().
operator=() [3/6]
template<typename T > optional & cata::optional< T >::operator= (nullopt_t) inline noexcept
Definition at line 165 of file optional.h.
{
            reset();
            return *this;
        }
References cata::optional< T >::reset().
operator=() [4/6]
template<typename T > optional & cata::optional< T >::operator= (optional< T > && other) inline
Definition at line 179 of file optional.h.
{
            if( full && other.full ) {
                get() = std::move( other.get() );
            } else if( full ) {
                reset();
            } else if( other.full ) {
                construct( std::move( other.get() ) );
            }
            return *this;
        }
References cata::optional< T >::construct(), cata::optional< T >::full, cata::optional< T >::get(), avatar_action::move(), other, and cata::optional< T >::reset().
operator=() [5/6]
template<typename T > template<class U > optional & cata::optional< T >::operator= (optional< U > && other) inline
Definition at line 214 of file optional.h.
{
            if( full && other.full ) {
                get() = std::move( other.get() );
            } else if( full ) {
                reset();
            } else if( other.full ) {
                construct( std::move( other.get() ) );
            }
            return *this;
        }
References cata::optional< T >::construct(), cata::optional< T >::full, cata::optional< T >::get(), avatar_action::move(), other, and cata::optional< T >::reset().
operator=() [6/6]
template<typename T > template<class U = T, typename std::enable_if< !std::is_same< optional< T >, typename std::decay< U >::type >::value &&std::is_constructible< T, U && >::value &&std::is_convertible< U &&, T >::value, bool >::type = true> optional & cata::optional< T >::operator= (U && value) inline
Definition at line 194 of file optional.h.
{
            if( full ) {
                get() = std::forward<U>( value );
            } else {
                construct( std::forward<U>( value ) );
            }
            return *this;
        }
References cata::optional< T >::construct(), cata::optional< T >::full, cata::optional< T >::get(), and cata::optional< T >::value().
reset()
template<typename T > void cata::optional< T >::reset () inline noexcept
Definition at line 158 of file optional.h.
{
            if( full ) {
                full = false;
                destruct();
            }
        }
References cata::optional< T >::destruct(), and cata::optional< T >::full.
Referenced by assign(), correct_if_magic(), cata::optional< T >::emplace(), find_base_construction(), game::handle_mouseview(), cata::optional< T >::operator=(), vehicle_part_iterator< range_type >::skip_to_next_valid(), smash(), and cata::optional< T >::~optional().
swap()
template<typename T > void cata::optional< T >::swap (optional< T > & other) inline
Definition at line 225 of file optional.h.
{
            using std::swap;
            if( full && other.full ) {
                swap( get(), other.get() );
            } else if( other.full() ) {
                construct( std::move( other.get() ) );
                other.destruct();
            } else if( full ) {
                other.construct( std::move( get() ) );
                destruct();
            }
        }
References cata::optional< T >::construct(), cata::optional< T >::destruct(), cata::optional< T >::full, cata::optional< T >::get(), avatar_action::move(), other, cata::swap(), and cata::optional< T >::swap().
Referenced by cata::optional< T >::swap().
value() [1/2]
template<typename T > T & cata::optional< T >::value () inline
Definition at line 127 of file optional.h.
                   {
            if( !full ) {
                throw bad_optional_access();
            }
            return get();
        }
References cata::optional< T >::full, and cata::optional< T >::get().
Referenced by computer_session::action_research(), item::basic_info(), mutation_branch::check_consistency(), game::control_vehicle(), create_trail_callback(), create_zone_callback(), Character::expose_to_disease(), game::find_or_make_stairs(), Character::get_effective_efficiency(), item::io(), game::list_items(), cata::optional< T >::operator=(), activity_handlers::repair_item_finish(), select_crafting_recipe(), detail::show_mutations_ui_internal(), iuse::spray_can(), ui_adaptor::ui_adaptor(), Character::update_type_of_scent(), place_npc_iuse::use(), deploy_furn_actor::use(), inscribe_actor::use(), and ui_adaptor::~ui_adaptor().
value() [2/2]
template<typename T > const T & cata::optional< T >::value () const inline
Definition at line 133 of file optional.h.
{
            if( !full ) {
                throw bad_optional_access();
            }
            return get();
        }
References cata::optional< T >::full, and cata::optional< T >::get().
value_or()
template<typename T > template<typename O > T cata::optional< T >::value_or (O && other) const inline
Definition at line 141 of file optional.h.
{
            return full ? get() : static_cast<T>( other );
        }
References cata::optional< T >::full, cata::optional< T >::get(), and other.
Referenced by advanced_inv_area::init().
Member Data Documentation
union { ... } cata::optional< T >::@21
data
template<typename T > StoredType cata::optional< T >::data
Definition at line 39 of file optional.h.
Referenced by cata::optional< T >::construct(), cata::optional< T >::destruct(), and cata::optional< T >::get().
dont_use
template<typename T > volatile char cata::optional< T >::dont_use
Definition at line 37 of file optional.h.
dummy
template<typename T > char cata::optional< T >::dummy
Definition at line 38 of file optional.h.
full
template<typename T > bool cata::optional< T >::full private
Definition at line 41 of file optional.h.
Referenced by cata::optional< T >::construct(), cata::optional< T >::get(), cata::optional< T >::has_value(), cata::optional< T >::operator bool(), cata::optional< T >::operator=(), cata::optional< T >::reset(), cata::optional< T >::swap(), cata::optional< T >::value(), and cata::optional< T >::value_or().
The documentation for this class was generated from the following files:
src/action.h
src/optional.h