Cataclysm BN: jmapgen_npc Class Reference
jmapgen_npc Class Reference
Place an NPC.
Public Member Functions
jmapgen_npc (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
string_id< npc_template > npc_class
bool target
std::vector< std::string > traits
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place an NPC.
"class": the npc class, see map::place_npc
Definition at line 875 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_npc()
jmapgen_npc::jmapgen_npc (const JsonObject & jsi) inline
Definition at line 881 of file mapgen.cpp.
                                             :
            npc_class( jsi.get_string( "class" ) )
            , target( jsi.get_bool( "target", false ) ) {
            if( !npc_class.is_valid() ) {
                set_mapgen_defer( jsi, "class", "unknown npc class" );
            }
            if( jsi.has_string( "add_trait" ) ) {
                std::string new_trait = jsi.get_string( "add_trait" );
                traits.emplace_back( new_trait );
            } else if( jsi.has_array( "add_trait" ) ) {
                for( const std::string new_trait : jsi.get_array( "add_trait" ) ) {
                    traits.emplace_back( new_trait );
                }
            }
        }
References JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), mapgen_defer::jsi, set_mapgen_defer(), and traits.
Member Function Documentation
apply()
void jmapgen_npc::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 896 of file mapgen.cpp.
{
            character_id npc_id = dat.m.place_npc( point( x.get(), y.get() ), npc_class );
            if( dat.mission() && target ) {
                dat.mission()->set_target_npc_id( npc_id );
            }
            npc *p = g->find_npc( npc_id );
            if( p != nullptr ) {
                for( const std::string &new_trait : traits ) {
                    p->set_mutation( trait_id( new_trait ) );
                }
            }
        }
References g, jmapgen_int::get(), mapgendata::m, mapgendata::mission(), map::place_npc(), Character::set_mutation(), mission::set_target_npc_id(), target, trait_id, and traits.
Member Data Documentation
npc_class
string_id<npc_template> jmapgen_npc::npc_class
Definition at line 878 of file mapgen.cpp.
target
bool jmapgen_npc::target
Definition at line 879 of file mapgen.cpp.
Referenced by apply().
traits
std::vector<std::string> jmapgen_npc::traits
Definition at line 880 of file mapgen.cpp.
Referenced by apply(), and jmapgen_npc().
The documentation for this class was generated from the following file:
src/mapgen.cpp