Cataclysm BN: throbber_popup Class Reference
throbber_popup Class Reference
Popup optimized to work as a throbber (indicate some calculation running in background).
#include <popup.h>
Public Member Functions
throbber_popup (const std::string &msg)
Create a popup on the UI stack.
void refresh ()
Refresh the popup.
Private Attributes
std::shared_ptr< ui_adaptor > ui
std::string msg
std::chrono::steady_clock::time_point last_update
Additional Inherited Members
Private Member Functions inherited from query_popup
query_popup ()
Default construction.
query_popup & context (const std::string &cat)
Specify the input context.
template<typename ... Args>
query_popup & message (const std::string &fmt, Args &&... args)
Specify the query message.
template<typename ... Args>
query_popup & message (const char *const fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const nc_color &bar_color, const std::string &fmt, Args &&... args)
Like query_popup::message, but with waiting symbol prepended to the text.
template<typename ... Args>
query_popup & wait_message (const nc_color &bar_color, const char *const fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const std::string &fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const char *const fmt, Args &&... args)
query_popup & option (const std::string &opt)
Specify an action as an option.
query_popup & option (const std::string &opt, const std::function< bool(const input_event &)> &filter)
Specify an action as an option, and a filter of allowed input events for this action.
query_popup & allow_anykey (bool allow)
Specify whether non-option actions can be returned.
query_popup & allow_cancel (bool allow)
Specify whether an implicit cancel option is allowed.
query_popup & on_top (bool top)
Whether to show the popup on the top of the screen.
query_popup & full_screen (bool full)
Whether to show the popup in FULL_SCREEN_HEIGHT and FULL_SCREEN_WIDTH.
query_popup & cursor (size_t pos)
Specify starting cursor position.
query_popup & default_color (const nc_color &d_color)
Specify the default message color.
void show () const
Draw the UI.
result query_once ()
Query once and return the result.
result query ()
Query until a valid action or an error happens and return the result.
std::shared_ptr< ui_adaptor > create_or_get_adaptor (bool disable_below=false)
Create or get a ui_adaptor on the UI stack to handle redrawing and resizing of the popup.
Detailed Description
Popup optimized to work as a throbber (indicate some calculation running in background).
Create an instance of this class to put the popup on the UI stack.
Call refresh() to redraw the popup, refresh the game window and poll events. To minimize the cost of repeated UI redraws and window refreshes, actual redraw/refresh/poll rate is kept at maximum 2 times per second, and all UIs under the popup are disabled (are not redrawn or resized).
The popup stays on the UI stack until its lifetime ends.
Example:
{
    throbber_popup popup( _( "Please wait…" ) );
    while( loading ) {
        popup.refresh(); // may be safely called 1000s of times per second
        load_part();
    }
    // The popup is removed from UI stack when it goes out of scope.
    // Note that the removal is not visible until the next time `ui_manager::redraw` is called.
}
Definition at line 312 of file popup.h.
Constructor & Destructor Documentation
throbber_popup()
throbber_popup::throbber_popup (const std::string & msg)
Create a popup on the UI stack.
The popup is removed from UI stack when it goes out of scope.
Parameters
msg message to display. A spinning animation is appended automatically on the left side of the message.
Definition at line 401 of file popup.cpp.
                                                     : msg( msg )
{
    on_top( true );
    ui = create_or_get_adaptor( true );
}
References query_popup::create_or_get_adaptor(), and query_popup::on_top().
Member Function Documentation
refresh()
void throbber_popup::refresh ()
Refresh the popup.
Ideally, should be called at least 2 times per second to keep the refresh rate consistent.
Definition at line 407 of file popup.cpp.
{
    static constexpr std::chrono::milliseconds update_interval( 500 );
    auto now = std::chrono::steady_clock::now();
    if( last_update + update_interval < now ) {
        wait_message( "%s", msg ); // re-assign the message to advance the animation
        ui_manager::redraw();
        refresh_display();
        last_update = now;
#if defined(TILES)
        SDL_PumpEvents();
#endif // TILES
    }
}
References last_update, msg, ui_manager::redraw(), refresh_display(), and query_popup::wait_message().
Member Data Documentation
last_update
std::chrono::steady_clock::time_point throbber_popup::last_update private
Definition at line 332 of file popup.h.
Referenced by refresh().
msg
std::string throbber_popup::msg private
Definition at line 331 of file popup.h.
Referenced by refresh().
ui
std::shared_ptr<ui_adaptor> throbber_popup::ui private
Definition at line 330 of file popup.h.
The documentation for this class was generated from the following files:
src/popup.h
src/popup.cpp