Cataclysm BN: item_location::impl::item_on_person Class Reference
item_location::impl::item_on_person Class Reference
Public Member Functions
item_on_person (Character &who, item *which)
item_on_person (character_id who_id, int idx)
void serialize (JsonOut &js) const override
item * unpack (int idx) const override
type where () const override
tripoint position () const override
std::string describe (const Character *ch) const override
item_location obtain (Character &ch, int qty) override
int obtain_cost (const Character &ch, int qty) const override
void remove_item () override
bool valid () const override
void make_dirty () override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual item_location parent_item () const
item * target () const
Private Member Functions
bool ensure_who_unpacked () const
Private Attributes
character_id who_id
Character * who
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 246 of file item_location.cpp.
Constructor & Destructor Documentation
item_on_person() [1/2]
item_location::impl::item_on_person::item_on_person (Character & who, item * which) inline
Definition at line 265 of file item_location.cpp.
                                                      : impl( which ) {
            who_id = who.getID();
            this->who = &who;
        }
References Character::getID(), who, and who_id.
item_on_person() [2/2]
item_location::impl::item_on_person::item_on_person (character_id who_id, int idx) inline
Definition at line 270 of file item_location.cpp.
: impl(idx), who_id(who_id), who(nullptr) {}
Member Function Documentation
describe()
std::string item_location::impl::item_on_person::describe (const Character * ch) const inline override virtual
Implements item_location::impl.
Definition at line 305 of file item_location.cpp.
{
            if( !target() || !ensure_who_unpacked() ) {
                return std::string();
            }
            if( ch == who ) {
                auto parents = who->parents( *target() );
                if( !parents.empty() && who->is_worn( *parents.back() ) ) {
                    return parents.back()->type_name();
                } else if( who->is_worn( *target() ) ) {
                    return _( "worn" );
                } else {
                    return _( "inventory" );
                }
            } else {
                return who->name;
            }
        }
References _, ensure_who_unpacked(), Character::is_worn(), Character::name, visitable< T >::parents(), item_location::impl::target(), and who.
ensure_who_unpacked()
bool item_location::impl::item_on_person::ensure_who_unpacked () const inline private
Definition at line 252 of file item_location.cpp.
{
            if( !who ) {
                who = g->critter_by_id<Character>( who_id );
                if( !who ) {
                    // If we failed to find it throw a debug message cause we're probably going to crash soon
                    debugmsg( "Failed to find item_location owner with character_id %d", who_id.get_value() );
                    return false;
                }
            }
            return true;
        }
References debugmsg, g, character_id::get_value(), who, and who_id.
Referenced by describe(), make_dirty(), obtain_cost(), position(), remove_item(), serialize(), unpack(), and valid().
make_dirty()
void item_location::impl::item_on_person::make_dirty () inline override virtual
Implements item_location::impl.
Definition at line 409 of file item_location.cpp.
{
            if( ensure_who_unpacked() ) {
                idx = find_index( *who, what.get() );
            }
            needs_unpacking = true;
        }
References ensure_who_unpacked(), find_index(), item_location::impl::idx, item_location::impl::needs_unpacking, item_location::impl::what, and who.
obtain()
item_location item_location::impl::item_on_person::obtain (Character & ch, int qty) inline override virtual
Implements item_location::impl.
Definition at line 327 of file item_location.cpp.
{
            ch.mod_moves( -obtain_cost( ch, qty ) );
            if( &ch.i_at( ch.get_item_position( target() ) ) == target() ) {
                // item already in target characters inventory at base of stack
                return item_location( ch, target() );
            }
            item obj = target()->split( qty );
            if( !obj.is_null() ) {
                return item_location( ch, &ch.i_add( obj, should_stack ) );
            } else {
                item *inv = &ch.i_add( *target(), should_stack );
                remove_item();  // This also takes off the item from whoever wears it.
                return item_location( ch, inv );
            }
        }
References Character::get_item_position(), Character::i_add(), Character::i_at(), item::is_null(), item_location::item_location(), Creature::mod_moves(), obtain_cost(), remove_item(), item_location::impl::should_stack, item::split(), and item_location::impl::target().
obtain_cost()
int item_location::impl::item_on_person::obtain_cost (const Character & ch, int qty) const inline override virtual
Implements item_location::impl.
Definition at line 345 of file item_location.cpp.
{
            if( !target() || !ensure_who_unpacked() ) {
                return 0;
            }
            int mv = 0;
            item obj = *target();
            obj = obj.split( qty );
            if( obj.is_null() ) {
                obj = *target();
            }
            if( who->is_armed() && &who->weapon == target() ) {
                // no penalties because we already have this item in our hands
                mv += dynamic_cast<player *>( who )->item_handling_cost( obj, false, 0 );
            } else {
                auto parents = who->parents( *target() );
                if( !parents.empty() && who->is_worn( *parents.back() ) ) {
                    // if outermost parent item is worn status effects (e.g. GRABBED) are not applied
                    // holsters may also adjust the volume cost factor
                    if( parents.back()->can_holster( obj, true ) ) {
                        auto ptr = dynamic_cast<const holster_actor *>
                                   ( parents.back()->type->get_use( "holster" )->get_actor_ptr() );
                        mv += dynamic_cast<player *>( who )->item_handling_cost( obj, false, ptr->draw_cost );
                    } else if( parents.back()->is_bandolier() ) {
                        auto ptr = dynamic_cast<const bandolier_actor *>
                                   ( parents.back()->type->get_use( "bandolier" )->get_actor_ptr() );
                        mv += dynamic_cast<player *>( who )->item_handling_cost( obj, false, ptr->draw_cost );
                    } else {
                        mv += dynamic_cast<player *>( who )->item_handling_cost( obj, false,
                                INVENTORY_HANDLING_PENALTY / 2 );
                    }
                } else {
                    // it is more expensive to obtain items from the inventory
                    // TODO: calculate cost for searching in inventory proportional to item volume
                    mv += dynamic_cast<player *>( who )->item_handling_cost( obj, true, INVENTORY_HANDLING_PENALTY );
                }
            }
            if( &ch != who ) {
                // TODO: implement movement cost for transferring item between characters
            }
            return mv;
        }
References ensure_who_unpacked(), INVENTORY_HANDLING_PENALTY, Character::is_armed(), item::is_null(), Character::is_worn(), visitable< T >::parents(), item_location::ptr, item::split(), item_location::impl::target(), Character::weapon, and who.
Referenced by obtain().
position()
tripoint item_location::impl::item_on_person::position () const inline override virtual
Implements item_location::impl.
Definition at line 298 of file item_location.cpp.
{
            if( !ensure_who_unpacked() ) {
                return tripoint_zero;
            }
            return who->pos();
        }
References ensure_who_unpacked(), Character::pos(), tripoint_zero, and who.
remove_item()
void item_location::impl::item_on_person::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 396 of file item_location.cpp.
{
            if( !ensure_who_unpacked() ) {
                return;
            }
            who->remove_item( *what );
        }
References ensure_who_unpacked(), visitable< T >::remove_item(), item_location::impl::what, and who.
Referenced by obtain().
serialize()
void item_location::impl::item_on_person::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 272 of file item_location.cpp.
{
            if( !ensure_who_unpacked() ) {
                // Write an invalid item_location to avoid invalid json
                js.start_object();
                js.member( "type", "null" );
                js.end_object();
                return;
            }
            js.start_object();
            js.member( "type", "character" );
            js.member( "character", who_id );
            js.member( "idx", find_index( *who, target() ) );
            js.end_object();
        }
References JsonOut::end_object(), ensure_who_unpacked(), find_index(), JsonOut::member(), JsonOut::start_object(), item_location::impl::target(), who, and who_id.
unpack()
item * item_location::impl::item_on_person::unpack (int idx) const inline override virtual
Implements item_location::impl.
Definition at line 287 of file item_location.cpp.
{
            if( !ensure_who_unpacked() ) {
                return nullptr;
            }
            return retrieve_index( *who, idx );
        }
References ensure_who_unpacked(), item_location::impl::idx, retrieve_index(), and who.
valid()
bool item_location::impl::item_on_person::valid () const inline override virtual
Reimplemented from item_location::impl.
Definition at line 403 of file item_location.cpp.
{
            ensure_who_unpacked();
            ensure_unpacked();
            return !!what && !!who;
        }
References item_location::impl::ensure_unpacked(), ensure_who_unpacked(), item_location::impl::what, and who.
where()
type item_location::impl::item_on_person::where () const inline override virtual
Implements item_location::impl.
Definition at line 294 of file item_location.cpp.
{
            return type::character;
        }
References item_location::character.
Member Data Documentation
who
Character* item_location::impl::item_on_person::who mutable private
Definition at line 250 of file item_location.cpp.
Referenced by describe(), ensure_who_unpacked(), item_on_person(), make_dirty(), obtain_cost(), position(), remove_item(), serialize(), unpack(), and valid().
who_id
character_id item_location::impl::item_on_person::who_id private
Definition at line 249 of file item_location.cpp.
Referenced by ensure_who_unpacked(), item_on_person(), and serialize().
The documentation for this class was generated from the following file:
src/item_location.cpp