Cataclysm BN: pimpl< T > Class Template Reference
pimpl< T > Class Template Reference
This is a wrapper for implementing the pointer-to-implementation technique, see for example http://en.cppreference.com/w/cpp/language/pimpl.
#include <pimpl.h>
Public Member Functions
pimpl ()
template<typename P , typename ... Args, typename = typename std::enable_if < !is_pimpl<P>::value >::type>
pimpl (P &&head, Args &&... args)
pimpl (const pimpl< T > &rhs)
pimpl (pimpl< T > &&rhs)
pimpl< T > & operator= (const pimpl< T > &rhs)
pimpl< T > & operator= (pimpl< T > &&rhs)
bool operator== (const pimpl< T > &rhs) const
template<typename JsonStream >
void deserialize (JsonStream &stream)
Forwards the stream to T::deserialize.
template<typename JsonStream >
void serialize (JsonStream &stream) const
Forwards the stream to T::serialize.
Detailed Description
template<typename T>
class pimpl< T >
This is a wrapper for implementing the pointer-to-implementation technique, see for example http://en.cppreference.com/w/cpp/language/pimpl.
It's a container for one element of type T, which is always present (one can not create a pimpl instance without a contained T instance).
The contained T can be access like a pointer via operator-> and operator.
The constructor forwards all its arguments to the constructor of T.
Definition at line 34 of file pimpl.h.
Constructor & Destructor Documentation
pimpl() [1/4]
template<typename T > pimpl< T >::pimpl () inline explicit
Definition at line 41 of file pimpl.h.
: std::unique_ptr<T>(new T()) { }
pimpl() [2/4]
template<typename T > template<typename P , typename ... Args, typename = typename std::enable_if < !is_pimpl<P>::value >::type> pimpl< T >::pimpl (P && head, Args &&... args) inline explicit
Definition at line 44 of file pimpl.h.
                                   : std::unique_ptr<T>( new T( std::forward<P>( head ), std::forward<Args>( args )... ) ) { }
pimpl() [3/4]
template<typename T > pimpl< T >::pimpl (const pimpl< T > & rhs) inline explicit
Definition at line 47 of file pimpl.h.
: std::unique_ptr<T>(new T(*rhs)) { }
pimpl() [4/4]
template<typename T > pimpl< T >::pimpl (pimpl< T > && rhs) inline explicit
Definition at line 48 of file pimpl.h.
: std::unique_ptr<T>(new T(std::move(*rhs))) { }
Member Function Documentation
deserialize()
template<typename T > template<typename JsonStream > void pimpl< T >::deserialize (JsonStream & stream) inline
Forwards the stream to T::deserialize.
Definition at line 68 of file pimpl.h.
{
            operator*().deserialize( stream );
        }
References time_duration::deserialize(), and operator*().
operator=() [1/2]
template<typename T > pimpl< T > & pimpl< T >::operator= (const pimpl< T > & rhs) inline
Definition at line 50 of file pimpl.h.
{
            operator*() = *rhs;
            return *this;
        }
References operator*().
operator=() [2/2]
template<typename T > pimpl< T > & pimpl< T >::operator= (pimpl< T > && rhs) inline
Definition at line 54 of file pimpl.h.
{
            operator*() = std::move( *rhs );
            return *this;
        }
References avatar_action::move(), and operator*().
operator==()
template<typename T > bool pimpl< T >::operator== (const pimpl< T > & rhs) const inline
Definition at line 59 of file pimpl.h.
{
            return operator*() == *rhs;
        }
References operator*().
serialize()
template<typename T > template<typename JsonStream > void pimpl< T >::serialize (JsonStream & stream) const inline
Forwards the stream to T::serialize.
Definition at line 73 of file pimpl.h.
{
            operator*().serialize( stream );
        }
References operator*(), and time_duration::serialize().
The documentation for this class was generated from the following file:
src/pimpl.h