Cataclysm BN: bionic_sterilize_preset Class Reference
bionic_sterilize_preset Class Reference
Public Member Functions
bionic_sterilize_preset (player &pl)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Protected Attributes
player & p
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Detailed Description
Definition at line 2093 of file game_inventory.cpp.
Constructor & Destructor Documentation
bionic_sterilize_preset()
bionic_sterilize_preset::bionic_sterilize_preset (player & pl) inline
Definition at line 2096 of file game_inventory.cpp.
                                              :
            p( pl ) {
        }
Member Function Documentation
get_denial()
std::string bionic_sterilize_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 2104 of file game_inventory.cpp.
{
            if( loc.get_item()->has_flag( flag_FILTHY ) ) {
                return  _( "CBM is filthy.  Wash it first." );
            }
            return std::string();
        }
References _, flag_FILTHY(), item_location::get_item(), and item::has_flag().
is_shown()
bool bionic_sterilize_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 2100 of file game_inventory.cpp.
{
            return loc->has_fault( fault_bionic_nonsterile ) && loc->is_bionic();
        }
References fault_bionic_nonsterile, item::has_fault(), and item::is_bionic().
Member Data Documentation
p
player& bionic_sterilize_preset::p protected
Definition at line 2113 of file game_inventory.cpp.
The documentation for this class was generated from the following file:
src/game_inventory.cpp