Cataclysm BN: armor_inventory_preset Class Reference
armor_inventory_preset Class Reference
Public Member Functions
armor_inventory_preset (player &pl, const std::string &color_in)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool is_shown (const item_location &) const
Does this entry satisfy the basic preset conditions?
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Protected Attributes
player & p
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Private Member Functions
std::string get_number_string (int number) const
Private Attributes
const std::string color
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Detailed Description
Definition at line 285 of file game_inventory.cpp.
Constructor & Destructor Documentation
armor_inventory_preset()
armor_inventory_preset::armor_inventory_preset (player & pl, const std::string & color_in) inline
Definition at line 288 of file game_inventory.cpp.
                                                                        :
            p( pl ), color( color_in ) {
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->get_encumber( p ) );
            }, _( "ENCUMBRANCE" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return loc->get_storage() > 0_ml ? string_format( "<%s>%s</color>", color,
                        format_volume( loc->get_storage() ) ) : std::string();
            }, _( "STORAGE" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return string_format( "<%s>%d%%</color>", color, loc->get_coverage() );
            }, _( "COVERAGE" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->get_warmth() );
            }, _( "WARMTH" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->bash_resist() );
            }, _( "BASH" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->cut_resist() );
            }, _( "CUT" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->bullet_resist() );
            }, _( "BULLET" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->acid_resist() );
            }, _( "ACID" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->fire_resist() );
            }, _( "FIRE" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_number_string( loc->get_env_resist() );
            }, _( "ENV" ) );
        }
References _, item::acid_resist(), inventory_selector_preset::append_cell(), item::bash_resist(), item::bullet_resist(), color, item::cut_resist(), item::fire_resist(), format_volume(), item::get_coverage(), item::get_encumber(), item::get_env_resist(), get_number_string(), item::get_storage(), item::get_warmth(), p, and string_format().
Member Function Documentation
get_number_string()
std::string armor_inventory_preset::get_number_string (int number) const inline private
Definition at line 335 of file game_inventory.cpp.
{
            return number ? string_format( "<%s>%d</color>", color, number ) : std::string();
        }
References color, and string_format().
Referenced by armor_inventory_preset().
Member Data Documentation
color
const std::string armor_inventory_preset::color private
Definition at line 339 of file game_inventory.cpp.
Referenced by armor_inventory_preset(), and get_number_string().
p
player& armor_inventory_preset::p protected
Definition at line 333 of file game_inventory.cpp.
Referenced by armor_inventory_preset(), wear_inventory_preset::get_denial(), take_off_inventory_preset::get_denial(), wear_inventory_preset::is_shown(), and take_off_inventory_preset::is_shown().
The documentation for this class was generated from the following file:
src/game_inventory.cpp