Cataclysm BN: explosion_iuse Class Reference
explosion_iuse Class Reference
This is a iuse_actor for active items that explode when their charges reaches 0.
#include <iuse_actor.h>
Public Member Functions
explosion_iuse (const std::string &type="explosion")
~explosion_iuse () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
void trigger_explosion (const tripoint &p, Creature *source) const
Produces all the explosions from this actor.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
explosion_data explosion
int draw_explosion_radius = -1
nc_color draw_explosion_color = c_white
bool do_flashbang = false
Call game::flashbang?
bool flashbang_player_immune = false
int fields_radius = -1
Create fields of this type around the center of the explosion.
field_type_id fields_type
int fields_min_intensity = 1
int fields_max_intensity = 0
int emp_blast_radius = -1
Calls game::emp_blast if >= 0.
int scrambler_blast_radius = -1
Calls game::scrambler_blast if >= 0.
int sound_volume = -1
Volume of sound each turn, -1 means no sound at all.
std::string sound_msg
std::string no_deactivate_msg
Message shown when the player tries to deactivate the item, which is not allowed.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This is a iuse_actor for active items that explode when their charges reaches 0.
It can be called each turn, it can make a sound each turn.
Definition at line 168 of file iuse_actor.h.
Constructor & Destructor Documentation
explosion_iuse()
explosion_iuse::explosion_iuse (const std::string & type = "explosion") inline
Definition at line 198 of file iuse_actor.h.
: iuse_actor(type) {}
~explosion_iuse()
explosion_iuse::~explosion_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > explosion_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 488 of file iuse_actor.cpp.
{
    return std::make_unique<explosion_iuse>( *this );
}
info()
void explosion_iuse::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 603 of file iuse_actor.cpp.
{
    if( explosion.damage > 0 ) {
        dump.emplace_back( "TOOL", _( "Blast damage at epicenter: " ),
                           explosion.damage );
        dump.emplace_back( "TOOL", _( "Blast radius: " ), static_cast<int>( explosion.radius ) );
    }
    const auto &sd = explosion.fragment;
    if( sd ) {
        dump.emplace_back( "TOOL", _( "Shrapnel damage: " ),
                           static_cast<int>( sd->impact.total_damage() ) );
        dump.emplace_back( "TOOL", _( "Shrapnel range: " ), sd->range );
    }
    // TODO: List other effects, like EMP and clouds
}
References _, explosion_data::damage, explosion, explosion_data::fragment, and explosion_data::radius.
load()
void explosion_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 518 of file iuse_actor.cpp.
{
    if( obj.has_object( "explosion" ) ) {
        auto expl = obj.get_object( "explosion" );
        explosion = load_explosion_data( expl );
    }
    obj.read( "draw_explosion_radius", draw_explosion_radius );
    if( obj.has_member( "draw_explosion_color" ) ) {
        draw_explosion_color = color_from_string( obj.get_string( "draw_explosion_color" ) );
    }
    obj.read( "do_flashbang", do_flashbang );
    obj.read( "flashbang_player_immune", flashbang_player_immune );
    obj.read( "fields_radius", fields_radius );
    if( obj.has_member( "fields_type" ) || fields_radius > 0 ) {
        fields_type = field_type_id( obj.get_string( "fields_type" ) );
    }
    obj.read( "fields_min_intensity", fields_min_intensity );
    obj.read( "fields_max_intensity", fields_max_intensity );
    if( fields_max_intensity == 0 ) {
        fields_max_intensity = fields_type.obj().get_max_intensity();
    }
    obj.read( "emp_blast_radius", emp_blast_radius );
    obj.read( "scrambler_blast_radius", scrambler_blast_radius );
    obj.read( "sound_volume", sound_volume );
    obj.read( "sound_msg", sound_msg );
    obj.read( "no_deactivate_msg", no_deactivate_msg );
}
References color_from_string(), do_flashbang, draw_explosion_color, draw_explosion_radius, emp_blast_radius, explosion, fields_max_intensity, fields_min_intensity, fields_radius, fields_type, flashbang_player_immune, field_type::get_max_intensity(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), load_explosion_data(), no_deactivate_msg, int_id< T >::obj(), JsonObject::read(), scrambler_blast_radius, sound_msg, and sound_volume.
trigger_explosion()
void explosion_iuse::trigger_explosion (const tripoint & p, Creature * source) const
Produces all the explosions from this actor.
Definition at line 571 of file iuse_actor.cpp.
{
    if( explosion ) {
        explosion_handler::explosion( pos, explosion, source );
    }
    if( draw_explosion_radius >= 0 ) {
        explosion_handler::draw_explosion( pos, draw_explosion_radius, draw_explosion_color, "explosion" );
    }
    if( do_flashbang ) {
        explosion_handler::flashbang( pos, flashbang_player_immune, "explosion" );
    }
    map &here = get_map();
    if( fields_radius >= 0 && fields_type.id() ) {
        std::vector<tripoint> gas_sources = points_for_gas_cloud( pos, fields_radius );
        for( auto &gas_source : gas_sources ) {
            const int field_intensity = rng( fields_min_intensity, fields_max_intensity );
            here.add_field( gas_source, fields_type, field_intensity, 1_turns );
        }
    }
    if( scrambler_blast_radius >= 0 ) {
        for( const tripoint &dest : here.points_in_radius( pos, scrambler_blast_radius ) ) {
            explosion_handler::scrambler_blast( dest );
        }
    }
    if( emp_blast_radius >= 0 ) {
        for( const tripoint &dest : here.points_in_radius( pos, emp_blast_radius ) ) {
            explosion_handler::emp_blast( dest );
        }
    }
}
References map::add_field(), do_flashbang, explosion_handler::draw_explosion(), draw_explosion_color, draw_explosion_radius, explosion_handler::emp_blast(), emp_blast_radius, explosion_handler::explosion(), explosion, fields_max_intensity, fields_min_intensity, fields_radius, fields_type, explosion_handler::flashbang(), flashbang_player_immune, get_map(), int_id< T >::id(), points_for_gas_cloud(), map::points_in_radius(), Character::pos(), rng(), explosion_handler::scrambler_blast(), and scrambler_blast_radius.
Referenced by use().
use()
int explosion_iuse::use (player & p, item & it, bool t, const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 547 of file iuse_actor.cpp.
{
    if( t ) {
        if( sound_volume >= 0 ) {
            sounds::sound( pos, sound_volume, sounds::sound_t::alarm,
                           sound_msg.empty() ? _( "Tick." ) : _( sound_msg ), true, "misc", "bomb_ticking" );
        }
        return 0;
    }
    if( it.charges > 0 ) {
        if( p.has_item( it ) ) {
            if( no_deactivate_msg.empty() ) {
                p.add_msg_if_player( m_warning,
                                     _( "You've already set the %s's timer you might want to get away from it." ), it.tname() );
            } else {
                p.add_msg_if_player( m_info, _( no_deactivate_msg ), it.tname() );
            }
        }
        return 0;
    }
    trigger_explosion( pos, it.activated_by.get() );
    return 1;
}
References _, item::activated_by, player::add_msg_if_player(), sounds::alarm, item::charges, visitable< T >::has_item(), m_info, m_warning, no_deactivate_msg, Character::pos(), sounds::sound(), sound_msg, sound_volume, item::tname(), and trigger_explosion().
Member Data Documentation
do_flashbang
bool explosion_iuse::do_flashbang = false
Call game::flashbang?
Definition at line 180 of file iuse_actor.h.
Referenced by mattack::kamikaze(), load(), and trigger_explosion().
draw_explosion_color
nc_color explosion_iuse::draw_explosion_color = c_white
Definition at line 178 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
draw_explosion_radius
int explosion_iuse::draw_explosion_radius = -1
Definition at line 177 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
emp_blast_radius
int explosion_iuse::emp_blast_radius = -1
Calls game::emp_blast if >= 0.
Definition at line 188 of file iuse_actor.h.
Referenced by mattack::kamikaze(), load(), and trigger_explosion().
explosion
explosion_data explosion_iuse::explosion
Definition at line 173 of file iuse_actor.h.
Referenced by npc::find_dangerous_explosives(), info(), mattack::kamikaze(), load(), and trigger_explosion().
fields_max_intensity
int explosion_iuse::fields_max_intensity = 0
Definition at line 186 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
fields_min_intensity
int explosion_iuse::fields_min_intensity = 1
Definition at line 185 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
fields_radius
int explosion_iuse::fields_radius = -1
Create fields of this type around the center of the explosion.
Definition at line 183 of file iuse_actor.h.
Referenced by mattack::kamikaze(), load(), and trigger_explosion().
fields_type
field_type_id explosion_iuse::fields_type
Definition at line 184 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
flashbang_player_immune
bool explosion_iuse::flashbang_player_immune = false
Definition at line 181 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
no_deactivate_msg
std::string explosion_iuse::no_deactivate_msg
Message shown when the player tries to deactivate the item, which is not allowed.
Definition at line 196 of file iuse_actor.h.
Referenced by load(), and use().
scrambler_blast_radius
int explosion_iuse::scrambler_blast_radius = -1
Calls game::scrambler_blast if >= 0.
Definition at line 190 of file iuse_actor.h.
Referenced by load(), and trigger_explosion().
sound_msg
std::string explosion_iuse::sound_msg
Definition at line 193 of file iuse_actor.h.
Referenced by load(), and use().
sound_volume
int explosion_iuse::sound_volume = -1
Volume of sound each turn, -1 means no sound at all.
Definition at line 192 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp