Cataclysm BN: steady_consumer_tile Class Reference
steady_consumer_tile Class Reference
#include <active_tile_data_def.h>
Public Member Functions
void update_internal (time_point to, const tripoint_abs_ms &p, distribution_grid &grid) override
active_tile_data * clone () const override
const std::string & get_type () const override
void store (JsonOut &jsout) const override
void load (JsonObject &jo) override
Public Member Functions inherited from active_tile_data
void update (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)
time_point get_last_updated ()
void set_last_updated (time_point t)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
virtual ~active_tile_data ()
Public Attributes
int power
time_duration consume_every = 1_seconds
active_tiles::furn_transform transform
Additional Inherited Members
Static Public Member Functions inherited from active_tile_data
static active_tile_data * create (const std::string &id)
Detailed Description
Definition at line 77 of file active_tile_data_def.h.
Member Function Documentation
clone()
active_tile_data * steady_consumer_tile::clone () const override virtual
Implements active_tile_data.
Definition at line 329 of file active_tile_data.cpp.
{
    return new steady_consumer_tile( *this );
}
get_type()
const std::string & steady_consumer_tile::get_type () const override virtual
Implements active_tile_data.
Definition at line 334 of file active_tile_data.cpp.
{
    static const std::string type( "steady_consumer" );
    return type;
}
References type.
load()
void steady_consumer_tile::load (JsonObject & jo) override virtual
Implements active_tile_data.
Definition at line 347 of file active_tile_data.cpp.
{
    jo.read( "power", power );
    jo.read( "consume_every", consume_every );
    jo.read( "transform", transform );
}
References consume_every, power, JsonObject::read(), and transform.
store()
void steady_consumer_tile::store (JsonOut & jsout) const override virtual
Implements active_tile_data.
Definition at line 340 of file active_tile_data.cpp.
{
    jsout.member( "power", power );
    jsout.member( "consume_every", consume_every );
    jsout.member( "transform", transform );
}
References consume_every, JsonOut::member(), power, and transform.
update_internal()
void steady_consumer_tile::update_internal (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) override virtual
Parameters
to the time to update to
p absolute map coordinates (map::getabs) of the tile being updated
grid distribution grid being updated, containing the tile being updated
Implements active_tile_data.
Definition at line 307 of file active_tile_data.cpp.
{
    int ticks = ticks_between( get_last_updated(), to, consume_every );
    if( ticks == 0 ) {
        return;
    }
    std::int64_t power = this->power * ticks;
    int missing = grid.mod_resource( -power );
    if( missing == 0 ) {
        return;
    }
    if( transform.id.is_null() ) {
        return;
    }
    get_distribution_grid_tracker().get_transform_queue().add( p, transform.id, transform.msg );
}
References grid_furn_transform_queue::add(), consume_every, get_distribution_grid_tracker(), active_tile_data::get_last_updated(), distribution_grid_tracker::get_transform_queue(), active_tiles::furn_transform::id, string_id< T >::is_null(), distribution_grid::mod_resource(), active_tiles::furn_transform::msg, power, ticks_between(), and transform.
Member Data Documentation
consume_every
time_duration steady_consumer_tile::consume_every = 1_seconds
Definition at line 82 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
power
int steady_consumer_tile::power
Definition at line 81 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
transform
active_tiles::furn_transform steady_consumer_tile::transform
Definition at line 83 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
The documentation for this class was generated from the following files:
src/active_tile_data_def.h
src/active_tile_data.cpp