Cataclysm BN: Item_factory Class Reference
Item_factory Class Reference
Central item type management class.
#include <item_factory.h>
Public Member Functions
Item_factory ()
~Item_factory ()
void reset ()
Reset the item factory.
void check_definitions () const
Check consistency of itype and item group definitions, for example valid material, valid tool, etc.
Item groups
Item groups are used to spawn random items (in random amounts).
You usually only need the item_group::items_from function to create items from a group.
void load_item_group (const JsonObject &jsobj)
Callback for the init system (DynamicDataLoader), loads an item group definitions.
void load_item_group (const JsonObject &jsobj, const item_group_id &group_id, const std::string &subtype)
Load a item group from json.
void load_item_group (const JsonArray &entries, const item_group_id &group_id, bool is_collection, int ammo_chance, int magazine_chance)
Like above, but the above loads data from several members of the object, this function assume the given array is the "entries" member of the item group.
Item_spawn_data * get_group (const item_group_id &item_group_id)
Get the item group object.
std::vector< item_group_id > get_all_group_names ()
Returns the idents of all item groups that are known.
bool add_item_to_group (const item_group_id &group_id, const itype_id &item_id, int chance)
Sets the chance of the specified item in the group.
Private Attributes
friend itype_id
Item type loading
These function load different instances of itype objects from json.
The loaded item types are stored and can be accessed through find_template.
Parameters
jo The json object to load data from.
Exceptions
JsonError if the json object contains invalid data.
using GroupMap = std::map< item_group_id, std::unique_ptr< Item_spawn_data > >
bool frozen = false
Set at finalization and prevents alterations to the static item templates.
std::map< itype_id, itype > m_abstracts
std::unordered_map< itype_id, itype > m_templates
std::map< itype_id, std::unique_ptr< itype > > m_runtimes
GroupMap m_template_groups
std::unordered_map< itype_id, ammotype > migrated_ammo
std::unordered_map< itype_id, itype_id > migrated_magazines
std::map< item_action_id, use_function > iuse_function_list
std::map< itype_id, migration > migrations
std::map< itype_id, std::set< itype_id > > tool_subtypes
Contains the tool subtype mappings for crafting (i.e.
std::set< itype_id > repair_tools
std::set< itype_id > gun_tools
std::set< std::string > repair_actions
void load_ammo (const JsonObject &jo, const std::string &src)
void load_gun (const JsonObject &jo, const std::string &src)
void load_armor (const JsonObject &jo, const std::string &src)
void load_pet_armor (const JsonObject &jo, const std::string &src)
void load_tool (const JsonObject &jo, const std::string &src)
void load_toolmod (const JsonObject &jo, const std::string &src)
void load_tool_armor (const JsonObject &jo, const std::string &src)
void load_book (const JsonObject &jo, const std::string &src)
void load_comestible (const JsonObject &jo, const std::string &src)
void load_container (const JsonObject &jo, const std::string &src)
void load_engine (const JsonObject &jo, const std::string &src)
void load_wheel (const JsonObject &jo, const std::string &src)
void load_fuel (const JsonObject &jo, const std::string &src)
void load_gunmod (const JsonObject &jo, const std::string &src)
void load_magazine (const JsonObject &jo, const std::string &src)
void load_battery (const JsonObject &jo, const std::string &src)
void load_generic (const JsonObject &jo, const std::string &src)
void load_bionic (const JsonObject &jo, const std::string &src)
void finalize ()
called after all JSON has been read and performs any necessary cleanup tasks
void load_migration (const JsonObject &jo)
Migrations transform items loaded from legacy saves.
itype_id migrate_id (const itype_id &id)
Applies any migration of the item id.
void migrate_item (const itype_id &id, item &obj)
Applies any migrations to an instance of an item.
void add_item_type (const itype &def)
Add a passed in itype to the collection of item types.
bool has_iuse (const item_action_id &type) const
Check if an iuse is known to the Item_factory.
void load_item_blacklist (const JsonObject &json)
std::vector< const itype * > all () const
Get all item templates (both static and runtime)
std::vector< const itype * > get_runtime_types () const
Get item types created at runtime.
std::vector< const itype * > find (const std::function< bool(const itype &)> &func)
Find all item templates (both static and runtime) matching UnaryPredicate function.
itype_id create_artifact_id () const
Create a new (and currently unused) item type id.
std::list< itype_id > subtype_replacement (const itype_id &) const
bool has_template (const itype_id &id) const
Check if an item type is known to the Item_factory.
const itype * find_template (const itype_id &id) const
Returns the itype with the given id.
bool check_ammo_type (std::string &msg, const ammotype &ammo) const
Checks that ammo is listed in ammunition_type::name().
bool load_definition (const JsonObject &jo, const std::string &src, itype &def)
Called before creating a new template and handles inheritance via copy-from May defer instantiation of the template if depends on other objects not as-yet loaded.
template<typename SlotType >
void load_slot (cata::value_ptr< SlotType > &slotptr, const JsonObject &jo, const std::string &src)
Load the data of the slot struct.
template<typename SlotType >
void load_slot_optional (cata::value_ptr< SlotType > &slotptr, const JsonObject &jo, const std::string &member, const std::string &src)
Load item the item slot if present in json.
void load (islot_tool &slot, const JsonObject &jo, const std::string &src)
void load (islot_container &slot, const JsonObject &jo, const std::string &src)
void load (islot_comestible &slot, const JsonObject &jo, const std::string &src)
void load (islot_brewable &slot, const JsonObject &jo, const std::string &src)
void load (islot_armor &slot, const JsonObject &jo, const std::string &src)
void load (islot_pet_armor &slot, const JsonObject &jo, const std::string &src)
void load (islot_book &slot, const JsonObject &jo, const std::string &src)
void load (islot_mod &slot, const JsonObject &jo, const std::string &src)
void load (islot_engine &slot, const JsonObject &jo, const std::string &src)
void load (islot_wheel &slot, const JsonObject &jo, const std::string &src)
void load (islot_fuel &slot, const JsonObject &jo, const std::string &src)
void load (islot_gun &slot, const JsonObject &jo, const std::string &src)
void load (islot_gunmod &slot, const JsonObject &jo, const std::string &src)
void load (islot_magazine &slot, const JsonObject &jo, const std::string &src)
void load (islot_battery &slot, const JsonObject &jo, const std::string &src)
void load (islot_bionic &slot, const JsonObject &jo, const std::string &src)
void load (islot_seed &slot, const JsonObject &jo, const std::string &src)
void load (islot_artifact &slot, const JsonObject &jo, const std::string &src)
void load (relic &slot, const JsonObject &jo, const std::string &src)
void load (islot_milling &slot, const JsonObject &jo, const std::string &src)
void emplace_usage (std::map< std::string, use_function > &container, const std::string &iuse_id)
void set_use_methods_from_json (const JsonObject &jo, const std::string &member, std::map< std::string, use_function > &use_methods)
use_function usage_from_string (const std::string &type) const
std::pair< std::string, use_function > usage_from_object (const JsonObject &obj)
bool load_sub_ref (std::unique_ptr< Item_spawn_data > &ptr, const JsonObject &obj, const std::string &name, const Item_group &parent)
Helper function for Item_group loading.
bool load_string (std::vector< std::string > &vec, const JsonObject &obj, const std::string &name)
void add_entry (Item_group &ig, const JsonObject &obj)
void load_basic_info (const JsonObject &jo, itype &def, const std::string &src)
void set_qualities_from_json (const JsonObject &jo, const std::string &member, itype &def)
void extend_qualities_from_json (const JsonObject &jo, const std::string &member, itype &def)
void delete_qualities_from_json (const JsonObject &jo, const std::string &member, itype &def)
void set_properties_from_json (const JsonObject &jo, const std::string &member, itype &def)
void clear ()
void init ()
void finalize_item_blacklist ()
void finalize_pre (itype &obj)
Applies part of finalization that don't depend on other items.
void register_cached_uses (const itype &obj)
Registers the item as having repair actions (if it has any).
void finalize_post (itype &obj)
Applies part of finalization that depends on other items.
void add_iuse (const std::string &type, use_function_pointer f)
void add_iuse (const std::string &type, use_function_pointer f, const std::string &info)
void add_actor (std::unique_ptr< iuse_actor >)
static void npc_implied_flags (itype &item_template)
static void set_allergy_flags (itype &item_template)
Detailed Description
Central item type management class.
It contains a map of all item types, accessible via find_template. Those item types are loaded from json via the load_* functions.
It also contains all item groups that are used to spawn items.
You usually use the single global instance item_controller.
Definition at line 60 of file item_factory.h.
Member Typedef Documentation
GroupMap
using Item_factory::GroupMap = std::map<item_group_id, std::unique_ptr<Item_spawn_data> > private
Definition at line 250 of file item_factory.h.
Constructor & Destructor Documentation
Item_factory()
Item_factory::Item_factory ()
Definition at line 772 of file item_factory.cpp.
{
    init();
}
References init().
~Item_factory()
Item_factory::~Item_factory () default
Member Function Documentation
add_actor()
void Item_factory::add_actor (std::unique_ptr< iuse_actor > ptr) private
Definition at line 828 of file item_factory.cpp.
{
    std::string type = ptr->type;
    iuse_function_list[ type ] = use_function( std::move( ptr ) );
}
References iuse_function_list, avatar_action::move(), ptr(), and type.
Referenced by init(), and usage_from_object().
add_entry()
void Item_factory::add_entry (Item_group & ig, const JsonObject & obj) private
Definition at line 2909 of file item_factory.cpp.
{
    std::unique_ptr<Item_group> gptr;
    int probability = obj.get_int( "prob", 100 );
    JsonArray jarr;
    if( obj.has_member( "collection" ) ) {
        gptr = std::make_unique<Item_group>( Item_group::G_COLLECTION, probability, ig.with_ammo,
                                             ig.with_magazine );
        jarr = obj.get_array( "collection" );
    } else if( obj.has_member( "distribution" ) ) {
        gptr = std::make_unique<Item_group>( Item_group::G_DISTRIBUTION, probability, ig.with_ammo,
                                             ig.with_magazine );
        jarr = obj.get_array( "distribution" );
    }
    if( gptr ) {
        for( const JsonObject job2 : jarr ) {
            add_entry( *gptr, job2 );
        }
        ig.add_entry( std::move( gptr ) );
        return;
    }
    std::unique_ptr<Single_item_creator> sptr;
    if( obj.has_member( "item" ) ) {
        sptr = std::make_unique<Single_item_creator>(
                   obj.get_string( "item" ), Single_item_creator::S_ITEM, probability );
    } else if( obj.has_member( "group" ) ) {
        sptr = std::make_unique<Single_item_creator>(
                   obj.get_string( "group" ), Single_item_creator::S_ITEM_GROUP, probability );
    }
    if( !sptr ) {
        return;
    }
    Item_modifier modifier;
    bool use_modifier = false;
    use_modifier |= load_min_max( modifier.damage, obj, "damage" );
    use_modifier |= load_min_max( modifier.dirt, obj, "dirt" );
    modifier.damage.first *= itype::damage_scale;
    modifier.damage.second *= itype::damage_scale;
    use_modifier |= load_min_max( modifier.charges, obj, "charges" );
    use_modifier |= load_min_max( modifier.count, obj, "count" );
    use_modifier |= load_sub_ref( modifier.ammo, obj, "ammo", ig );
    use_modifier |= load_sub_ref( modifier.container, obj, "container", ig );
    use_modifier |= load_sub_ref( modifier.contents, obj, "contents", ig );
    use_modifier |= load_string( modifier.custom_flags, obj, "custom-flags" );
    if( use_modifier ) {
        sptr->modifier.emplace( std::move( modifier ) );
    }
    ig.add_entry( std::move( sptr ) );
}
References add_entry(), Item_group::add_entry(), Item_modifier::ammo, Item_modifier::charges, Item_modifier::container, Item_modifier::contents, Item_modifier::count, Item_modifier::custom_flags, Item_modifier::damage, itype::damage_scale, Item_modifier::dirt, Item_group::G_COLLECTION, Item_group::G_DISTRIBUTION, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_member(), load_min_max(), load_string(), load_sub_ref(), avatar_action::move(), Single_item_creator::S_ITEM, Single_item_creator::S_ITEM_GROUP, Item_group::with_ammo, and Item_group::with_magazine.
Referenced by add_entry(), and load_item_group().
add_item_to_group()
bool Item_factory::add_item_to_group (const item_group_id & group_id, const itype_id & item_id, int chance)
Sets the chance of the specified item in the group.
Parameters
group_id Group to add item to
item_id Id of item to add to group
chance The relative weight of the item. A value of 0 removes the item from the group.
Returns
false if the group doesn't exist.
Definition at line 3196 of file item_factory.cpp.
{
    if( m_template_groups.find( group_id ) == m_template_groups.end() ) {
        return false;
    }
    Item_spawn_data &group_to_access = *m_template_groups[group_id];
    if( group_to_access.has_item( item_id ) ) {
        group_to_access.remove_item( item_id );
    }
    Item_group *ig = dynamic_cast<Item_group *>( &group_to_access );
    if( chance != 0 && ig != nullptr ) {
        // Only re-add if chance != 0
        ig->add_item_entry( item_id, chance );
    }
    return true;
}
References Item_group::add_item_entry(), Item_spawn_data::has_item(), m_template_groups, and Item_spawn_data::remove_item().
add_item_type()
void Item_factory::add_item_type (const itype & def)
Add a passed in itype to the collection of item types.
If the item type overrides an existing type, the existing type is deleted first.
Parameters
def The new item type, must not be null.
Definition at line 834 of file item_factory.cpp.
{
    if( m_runtimes.count( def.id ) > 0 ) {
        // Do NOT allow overwriting it, it's undefined behavior
        debugmsg( "Tried to add runtime type %s, but it exists already", def.id.c_str() );
        return;
    }
    auto &new_item_ptr = m_runtimes[ def.id ];
    new_item_ptr = std::make_unique<itype>( def );
    if( frozen ) {
        finalize_pre( *new_item_ptr );
        finalize_post( *new_item_ptr );
    }
}
References string_id< T >::c_str(), debugmsg, finalize_post(), finalize_pre(), frozen, itype::id, and m_runtimes.
add_iuse() [1/2]
void Item_factory::add_iuse (const std::string & type, use_function_pointer f) private
Definition at line 816 of file item_factory.cpp.
{
    iuse_function_list[ type ] = use_function( type, f );
}
References iuse_function_list, and type.
Referenced by init().
add_iuse() [2/2]
void Item_factory::add_iuse (const std::string & type, use_function_pointer f, const std::string & info) private
Definition at line 821 of file item_factory.cpp.
{
    iuse_function_list[ type ] =
        use_function( std::make_unique<iuse_function_wrapper_with_info>( type, f, info ) );
}
References iuse_function_list, and type.
all()
std::vector< const itype * > Item_factory::all () const
Get all item templates (both static and runtime)
Definition at line 3258 of file item_factory.cpp.
{
    assert( frozen );
    std::vector<const itype *> res;
    res.reserve( m_templates.size() + m_runtimes.size() );
    for( const auto &e : m_templates ) {
        res.push_back( &e.second );
    }
    for( const auto &e : m_runtimes ) {
        res.push_back( e.second.get() );
    }
    return res;
}
References frozen, m_runtimes, and m_templates.
check_ammo_type()
bool Item_factory::check_ammo_type (std::string & msg, const ammotype & ammo) const private
Checks that ammo is listed in ammunition_type::name().
At least one instance of this ammo type should be defined. If any of checks fails, prints a message to the msg stream.
Parameters
msg Stream in which all error messages are printed.
ammo Ammo type to check.
Definition at line 1093 of file item_factory.cpp.
{
    if( ammo.is_null() ) {
        return false;
    }
    if( !ammo.is_valid() ) {
        msg += string_format( "ammo type %s is not known\n", ammo.c_str() );
        return false;
    }
    if( std::none_of( m_templates.begin(),
    m_templates.end(), [&ammo]( const decltype( m_templates )::value_type & e ) {
    return e.second.ammo && e.second.ammo->type == ammo;
})) {
        msg += string_format( "there is no actual ammo of type %s defined\n", ammo.c_str() );
        return false;
    }
    return true;
}
References string_id< T >::c_str(), string_id< T >::is_null(), string_id< T >::is_valid(), m_templates, and string_format().
Referenced by check_definitions().
check_definitions()
void Item_factory::check_definitions () const
Check consistency of itype and item group definitions, for example valid material, valid tool, etc.
This should be called once after all json data has been loaded.
Definition at line 1114 of file item_factory.cpp.
{
    for( const auto &elem : m_templates ) {
        std::string msg;
        const itype *type = &elem.second;
        if( !type->category_force.is_valid() ) {
            msg += "undefined category " + type->category_force.str() + "\n";
        }
        if( type->weight < 0_gram ) {
            msg += "negative weight\n";
        }
        if( type->volume < 0_ml ) {
            msg += "negative volume\n";
        }
        if( type->count_by_charges() || type->phase == LIQUID ) {
            if( type->stack_size <= 0 ) {
                msg += string_format( "invalid stack_size %d on type using charges\n", type->stack_size );
            }
        }
        if( type->price < 0_cent ) {
            msg += "negative price\n";
        }
        if( type->damage_min() > 0 || type->damage_max() < 0 || type->damage_min() > type->damage_max() ) {
            msg += "invalid damage range\n";
        }
        if( type->description.empty() ) {
            msg += "empty description\n";
        }
        for( const material_id &mat_id : type->materials ) {
            if( mat_id.str() == "null" || !mat_id.is_valid() ) {
                msg += string_format( "invalid material %s\n", mat_id.c_str() );
            }
        }
        if( type->sym.empty() ) {
            msg += "symbol not defined\n";
        } else if( utf8_width( type->sym ) != 1 ) {
            msg += "symbol must be exactly one console cell width\n";
        }
        for( const auto &_a : type->techniques ) {
            if( !_a.is_valid() ) {
                msg += string_format( "unknown technique %s\n", _a.c_str() );
            }
        }
        if( !type->snippet_category.empty() ) {
            if( !SNIPPET.has_category( type->snippet_category ) ) {
                msg += string_format( "item %s: snippet category %s without any snippets\n", type->id.c_str(),
                                      type->snippet_category.c_str() );
            }
        }
        for( auto &q : type->qualities ) {
            if( !q.first.is_valid() ) {
                msg += string_format( "item %s has unknown quality %s\n", type->id.c_str(), q.first.c_str() );
            }
        }
        if( type->default_container && !has_template( *type->default_container ) ) {
            if( !type->default_container->is_null() ) {
                msg += string_format( "invalid container property %s\n", type->default_container->c_str() );
            }
        }
        for( const auto &e : type->emits ) {
            if( !e.is_valid() ) {
                msg += string_format( "item %s has unknown emit source %s\n", type->id.c_str(), e.c_str() );
            }
        }
        for( const auto &f : type->faults ) {
            if( !f.is_valid() ) {
                msg += string_format( "invalid item fault %s\n", f.c_str() );
            }
        }
        if( type->has_flag( "FIRESTARTER" ) &&
            !type->can_have_charges() &&
            !type->get_use( "firestarter" ) ) {
            msg += string_format( "has 'FIRESTARTER' flag, but neither can have charges nor defines 'firestarter' use func" );
        }
        if( type->comestible ) {
            if( !type->comestible->tool.is_null() ) {
                auto req_tool = find_template( type->comestible->tool );
                if( !req_tool->tool ) {
                    msg += string_format( "invalid tool property %s\n", type->comestible->tool.c_str() );
                }
            }
        }
        if( type->brewable ) {
            if( type->brewable->time < 1_turns ) {
                msg += "brewable time is less than 1 turn\n";
            }
            if( type->brewable->results.empty() ) {
                msg += "empty product list\n";
            }
            for( auto &b : type->brewable->results ) {
                if( !has_template( b ) ) {
                    msg += string_format( "invalid result id %s\n", b.c_str() );
                }
            }
        }
        if( type->seed ) {
            if( type->seed->grow < 1_turns ) {
                msg += "seed growing time is less than 1 turn\n";
            }
            if( !has_template( type->seed->fruit_id ) ) {
                msg += string_format( "invalid fruit id %s\n", type->seed->fruit_id.c_str() );
            }
            for( auto &b : type->seed->byproducts ) {
                if( !has_template( b ) ) {
                    msg += string_format( "invalid byproduct id %s\n", b.c_str() );
                }
            }
        }
        if( type->book ) {
            if( type->book->skill && !type->book->skill.is_valid() ) {
                msg += "uses invalid book skill.\n";
            }
            if( type->book->martial_art && !type->book->martial_art.is_valid() ) {
                msg += string_format( "trains invalid martial art '%s'.\n", type->book->martial_art.str() );
            }
            if( type->can_use( "MA_MANUAL" ) && !type->book->martial_art ) {
                msg += "has use_action MA_MANUAL but does not specify a martial art\n";
            }
        }
        if( type->can_use( "MA_MANUAL" ) && !type->book ) {
            msg += "has use_action MA_MANUAL but is not a book\n";
        }
        if( type->milling_data ) {
            if( !has_template( type->milling_data->into_ ) ) {
                msg += "type to mill into is invalid: " + type->milling_data->into_.str() + "\n";
            }
            if( !type->milling_data->into_->count_by_charges() ) {
                msg += "type to mill into must be counted by charges: " + type->milling_data->into_.str() + "\n";
            }
        }
        if( type->ammo ) {
            if( !type->ammo->type && type->ammo->type != ammotype( "NULL" ) ) {
                msg += "must define at least one ammo type\n";
            }
            check_ammo_type( msg, type->ammo->type );
            if( type->ammo->casing && ( !has_template( *type->ammo->casing ) ||
                                        type->ammo->casing->is_null() ) ) {
                msg += string_format( "invalid casing property %s\n", type->ammo->casing->c_str() );
            }
            if( !type->ammo->drop.is_null() && !has_template( type->ammo->drop ) ) {
                msg += string_format( "invalid drop item %s\n", type->ammo->drop.c_str() );
            }
            if( type->ammo->range != 0 && type->ammo->shape ) {
                msg += string_format( "shape is set, but range is %d != 0", type->ammo->range );
            }
        }
        if( type->battery ) {
            if( type->battery->max_capacity < 0_J ) {
                msg += "battery cannot have negative maximum charge\n";
            }
        }
        if( type->gun ) {
            for( const ammotype &at : type->gun->ammo ) {
                check_ammo_type( msg, at );
            }
            if( type->gun->ammo.empty() ) {
                // if gun doesn't use ammo forbid both integral or detachable magazines
                if( static_cast<bool>( type->gun->clip ) || !type->magazines.empty() ) {
                    msg += "cannot specify clip_size or magazine without ammo type\n";
                }
                if( type->has_flag( "RELOAD_AND_SHOOT" ) ) {
                    msg += "RELOAD_AND_SHOOT requires an ammo type to be specified\n";
                }
            } else {
                if( type->has_flag( "RELOAD_AND_SHOOT" ) && !type->magazines.empty() ) {
                    msg += "RELOAD_AND_SHOOT cannot be used with magazines\n";
                }
                for( const ammotype &at : type->gun->ammo ) {
                    if( !type->gun->clip && !type->magazines.empty() && !type->magazine_default.count( at ) ) {
                        msg += string_format( "specified magazine but none provided for ammo type %s\n", at.str() );
                    }
                }
            }
            if( type->gun->barrel_length < 0_ml ) {
                msg += "gun barrel length cannot be negative\n";
            }
            if( !type->gun->skill_used ) {
                msg += "uses no skill\n";
            } else if( !type->gun->skill_used.is_valid() ) {
                msg += string_format( "uses an invalid skill %s\n", type->gun->skill_used.str() );
            }
            for( auto &gm : type->gun->default_mods ) {
                if( !has_template( gm ) ) {
                    msg += "invalid default mod.\n";
                }
            }
            for( auto &gm : type->gun->built_in_mods ) {
                if( !has_template( gm ) ) {
                    msg += "invalid built-in mod.\n";
                }
            }
        }
        if( type->gunmod ) {
            if( type->gunmod->location.str().empty() ) {
                msg += "gunmod does not specify location\n";
            }
            if( ( type->gunmod->sight_dispersion < 0 ) != ( type->gunmod->aim_speed < 0 ) ) {
                msg += "gunmod must have both sight_dispersion and aim_speed set or neither of them set\n";
            }
            for( const gun_type_type &t : type->gunmod->usable ) {
                // TODO: Make gun_type_type not require horrid checks like this one
                const skill_id gun_skill = skill_id( t.name_ );
                bool is_skill = ( gun_skill.is_valid() && gun_skill->is_combat_skill() )
                                || t.name_ == "bow"
                                || t.name_ == "crossbow";
                itype_id item_type( t.name_ );
                bool is_item = item_type.is_valid();
                if( !is_skill && !is_item ) {
                    msg += string_format( "gunmod is usable for invalid item/gun type %s\n", t.name_ );
                    continue;
                }
                if( json_report_strict && t.name_ == "bow" ) {
                    msg += string_format( "'bow' location is deprecated, use 'archery' instead" );
                }
                // We need to check is_skill because something can be both an item and a skill
                if( !is_skill && is_item ) {
                    const itype *target = &*item_type;
                    if( target->gun->valid_mod_locations.count( type->gunmod->location ) == 0 ) {
                        msg += string_format( "gunmod is usable for gun %s which doesn't have a slot of type %s\n",
                                              t.name_, type->gunmod->location.str() );
                    }
                    if( type->mod != nullptr && !type->mod->ammo_modifier.empty() ) {
                        auto acceptable_ammo = type->mod->ammo_modifier;
                        for( const auto &pr : type->mod->magazine_adaptor ) {
                            acceptable_ammo.insert( pr.first );
                        }
                        auto acceptable_magazines = !type->mod->magazine_adaptor.empty()
                                                    ? type->mod->magazine_adaptor
                                                    : target->magazines;
                        for( const ammotype &ammo : acceptable_ammo ) {
                            if( acceptable_magazines.find( ammo ) == acceptable_magazines.end() ) {
                                msg += string_format( "gunmod can be applied to %s, which has no magazines for ammo %s\n",
                                                      t.name_, ammo.str() );
                            }
                        }
                    }
                }
            }
        }
        if( type->mod ) {
            for( const ammotype &at : type->mod->ammo_modifier ) {
                check_ammo_type( msg, at );
            }
            for( const auto &e : type->mod->acceptable_ammo ) {
                check_ammo_type( msg, e );
            }
            for( const auto &e : type->mod->magazine_adaptor ) {
                check_ammo_type( msg, e.first );
                if( e.second.empty() ) {
                    msg += string_format( "no magazines specified for ammo type %s\n", e.first.str() );
                }
                for( const itype_id &opt : e.second ) {
                    const itype *mag = find_template( opt );
                    if( !mag->magazine || !mag->magazine->type.count( e.first ) ) {
                        msg += string_format( "invalid magazine %s in magazine adapter\n", opt.str() );
                    }
                }
            }
        }
        if( type->magazine ) {
            for( const ammotype &at : type->magazine->type ) {
                check_ammo_type( msg, at );
            }
            if( type->magazine->type.empty() ) {
                msg += "magazine did not specify ammo type\n";
            }
            if( type->magazine->capacity < 0 ) {
                msg += string_format( "invalid capacity %i\n", type->magazine->capacity );
            }
            if( type->magazine->count < 0 || type->magazine->count > type->magazine->capacity ) {
                msg += string_format( "invalid count %i\n", type->magazine->count );
            }
            const itype *da = find_template( type->magazine->default_ammo );
            if( !( da->ammo && type->magazine->type.count( da->ammo->type ) ) ) {
                msg += string_format( "invalid default_ammo %s\n", type->magazine->default_ammo.str() );
            }
            if( type->magazine->reliability < 0 || type->magazine->reliability > 100 ) {
                msg += string_format( "invalid reliability %i\n", type->magazine->reliability );
            }
            if( type->magazine->reload_time < 0 ) {
                msg += string_format( "invalid reload_time %i\n", type->magazine->reload_time );
            }
            if( type->magazine->linkage && ( !has_template( *type->magazine->linkage ) ||
                                             type->magazine->linkage->is_null() ) ) {
                msg += string_format( "invalid linkage property %s\n", type->magazine->linkage->c_str() );
            }
        }
        for( const std::pair<const string_id<ammunition_type>, std::set<itype_id>> &ammo_variety :
             type->magazines ) {
            if( ammo_variety.second.empty() ) {
                msg += string_format( "no magazine specified for %s\n", ammo_variety.first.str() );
            }
            for( const itype_id &magazine : ammo_variety.second ) {
                const itype *mag_ptr = find_template( magazine );
                if( mag_ptr == nullptr ) {
                    msg += string_format( "magazine \"%s\" specified for \"%s\" does not exist\n",
                                          magazine.str(), ammo_variety.first.str() );
                } else if( !mag_ptr->magazine ) {
                    msg += string_format(
                               "magazine \"%s\" specified for \"%s\" is not a magazine\n", magazine.str(),
                               ammo_variety.first.str() );
                } else if( !mag_ptr->magazine->type.count( ammo_variety.first ) ) {
                    msg += string_format( "magazine \"%s\" does not take compatible ammo\n", magazine );
                } else if( mag_ptr->has_flag( "SPEEDLOADER" ) &&
                           mag_ptr->magazine->capacity != type->gun->clip ) {
                    msg += string_format(
                               "speedloader %s capacity (%d) does not match gun capacity (%d).\n",
                               magazine.str(), mag_ptr->magazine->capacity, type->gun->clip );
                }
            }
        }
        if( type->tool ) {
            for( const ammotype &at : type->tool->ammo_id ) {
                check_ammo_type( msg, at );
            }
            if( type->tool->revert_to && ( !has_template( *type->tool->revert_to ) ||
                                           type->tool->revert_to->is_null() ) ) {
                msg += string_format( "invalid revert_to property %s\n", type->tool->revert_to->c_str() );
            }
            if( !type->tool->revert_msg.empty() && !type->tool->revert_to ) {
                msg += "cannot specify revert_msg without revert_to\n";
            }
            if( !type->tool->subtype.is_empty() && !has_template( type->tool->subtype ) ) {
                msg += string_format( "invalid tool subtype %s\n", type->tool->subtype.str() );
            }
        }
        if( type->bionic ) {
            if( !type->bionic->id.is_valid() ) {
                msg += string_format( "there is no bionic with id %s\n", type->bionic->id.c_str() );
            }
        }
        if( type->container ) {
            if( type->container->seals && !type->container->unseals_into.is_null() ) {
                msg += string_format( "resealable container unseals_into %s\n",
                                      type->container->unseals_into.c_str() );
            }
            if( type->container->contains <= 0_ml ) {
                msg += string_format( "\"contains\" (%d) must be >0\n", type->container->contains.value() );
            }
            if( !has_template( type->container->unseals_into ) ) {
                msg += string_format( "unseals_into invalid id %s\n", type->container->unseals_into.c_str() );
            }
        }
        if( type->relic_data ) {
            type->relic_data->check();
        }
        for( const auto &elem : type->use_methods ) {
            const iuse_actor *actor = elem.second.get_actor_ptr();
            assert( actor );
            if( !actor->is_valid() ) {
                msg += string_format( "item action \"%s\" was not described.\n", actor->type.c_str() );
            }
            if( actor->type == "CABLE_ATTACH" && !vpart_id( type->id.str() ).is_valid() ) {
                msg += string_format( "no valid vehicle part for CABLE_ATTACH action\n" );
            }
        }
        if( type->fuel && !type->count_by_charges() ) {
            msg += "fuel value set, but item isn't count_by_charges.\n";
        }
        if( msg.empty() ) {
            continue;
        }
        debugmsg( "warnings for type %s:\n%s", type->id.c_str(), msg );
    }
    for( const auto &e : migrations ) {
        if( !m_templates.count( e.second.replace ) ) {
            debugmsg( "Invalid migration target: %s", e.second.replace.c_str() );
        }
        for( const auto &c : e.second.contents ) {
            if( !m_templates.count( c ) ) {
                debugmsg( "Invalid migration contents: %s", c.c_str() );
            }
        }
    }
    for( const auto &elem : m_template_groups ) {
        elem.second->check_consistency( elem.first.str() );
    }
}
References itype::ammo, b, c, string_id< T >::c_str(), check_ammo_type(), debugmsg, find_template(), itype::gun, snippet_library::has_category(), itype::has_flag(), has_template(), Skill::is_combat_skill(), iuse_actor::is_valid(), string_id< T >::is_valid(), json_report_strict, LIQUID, m_template_groups, m_templates, itype::magazine, itype::magazines, migrations, gun_type_type::name_, skill_id, SNIPPET, string_id< T >::str(), string_format(), type, iuse_actor::type, and utf8_width().
clear()
void Item_factory::clear () private
Definition at line 2761 of file item_factory.cpp.
{
    iuse_function_list.clear();
    deferred.clear();
    m_abstracts.clear();
    m_runtimes.clear();
    m_template_groups.clear();
    m_templates.clear();
    gun_tools.clear();
    repair_actions.clear();
    repair_tools.clear();
    tool_subtypes.clear();
    item_blacklist.clear();
    migrated_ammo.clear();
    migrated_magazines.clear();
    migrations.clear();
    frozen = false;
}
References deferred, frozen, gun_tools, item_blacklist, iuse_function_list, m_abstracts, m_runtimes, m_template_groups, m_templates, migrated_ammo, migrated_magazines, migrations, repair_actions, repair_tools, and tool_subtypes.
Referenced by reset().
create_artifact_id()
itype_id Item_factory::create_artifact_id () const
Create a new (and currently unused) item type id.
Definition at line 3309 of file item_factory.cpp.
{
    itype_id id;
    int i = m_runtimes.size();
    do {
        id = itype_id( string_format( "artifact_%d", i ) );
        ++i;
    } while( has_template( id ) );
    return id;
}
References has_template(), base_camps::id, itype_id, m_runtimes, and string_format().
delete_qualities_from_json()
void Item_factory::delete_qualities_from_json (const JsonObject & jo, const std::string & member, itype & def) private
Definition at line 2728 of file item_factory.cpp.
{
    for( JsonArray curr : jo.get_array( member ) ) {
        const auto iter = def.qualities.find( quality_id( curr.get_string( 0 ) ) );
        if( iter != def.qualities.end() && iter->second == curr.get_int( 1 ) ) {
            def.qualities.erase( iter );
        }
    }
}
References JsonObject::get_array(), mapgen_defer::member, and itype::qualities.
Referenced by load_basic_info().
emplace_usage()
void Item_factory::emplace_usage (std::map< std::string, use_function > & container, const std::string & iuse_id) private
Definition at line 3082 of file item_factory.cpp.
{
    use_function fun = usage_from_string( iuse_id );
    if( fun ) {
        container.emplace( iuse_id, fun );
    }
}
References usage_from_string().
Referenced by finalize_pre(), and set_use_methods_from_json().
extend_qualities_from_json()
void Item_factory::extend_qualities_from_json (const JsonObject & jo, const std::string & member, itype & def) private
Definition at line 2720 of file item_factory.cpp.
{
    for( JsonArray curr : jo.get_array( member ) ) {
        def.qualities[quality_id( curr.get_string( 0 ) )] = curr.get_int( 1 );
    }
}
References JsonObject::get_array(), mapgen_defer::member, and itype::qualities.
Referenced by load_basic_info().
finalize()
void Item_factory::finalize ()
called after all JSON has been read and performs any necessary cleanup tasks
Definition at line 631 of file item_factory.cpp.
{
    DynamicDataLoader::get_instance().load_deferred( deferred );
    finalize_item_blacklist();
    // we can no longer add or adjust static item templates
    frozen = true;
    for( auto &e : m_templates ) {
        finalize_pre( e.second );
        register_cached_uses( e.second );
    }
    for( auto &e : m_templates ) {
        finalize_post( e.second );
    }
    // We may actually have some runtimes here - ones loaded from saved game
    // TODO: support for runtimes that repair
    for( auto &e : m_runtimes ) {
        finalize_pre( *e.second );
        finalize_post( *e.second );
    }
    // for each item register all (non-obsolete) potential recipes
    for( const std::pair<const recipe_id, recipe> &p : recipe_dict ) {
        const recipe &rec = p.second;
        if( rec.obsolete || rec.will_be_blacklisted() ) {
            continue;
        }
        const itype_id &result = rec.result();
        auto it = m_templates.find( result );
        if( it != m_templates.end() ) {
            it->second.recipes.push_back( p.first );
        }
    }
}
References deferred, finalize_item_blacklist(), finalize_post(), finalize_pre(), frozen, DynamicDataLoader::get_instance(), DynamicDataLoader::load_deferred(), m_runtimes, m_templates, recipe::obsolete, recipe_dict, register_cached_uses(), recipe::result(), and recipe::will_be_blacklisted().
finalize_item_blacklist()
void Item_factory::finalize_item_blacklist () private
Definition at line 670 of file item_factory.cpp.
{
    for( const itype_id &blackout : item_blacklist ) {
        std::unordered_map<itype_id, itype>::iterator candidate = m_templates.find( blackout );
        if( candidate == m_templates.end() ) {
            debugmsg( "item on blacklist %s does not exist", blackout.c_str() );
            continue;
        }
        for( std::pair<const item_group_id, std::unique_ptr<Item_spawn_data>> &g : m_template_groups ) {
            g.second->remove_item( candidate->first );
        }
        // remove any blacklisted items from requirements
        for( const std::pair<const requirement_id, requirement_data> &r : requirement_data::all() ) {
            const_cast<requirement_data &>( r.second ).blacklist_item( candidate->first );
        }
        // remove any recipes used to craft the blacklisted item
        recipe_dictionary::delete_if( [&candidate]( const recipe & r ) {
            return r.result() == candidate->first;
        } );
    }
    for( vproto_id &vid : vehicle_prototype::get_all() ) {
        vehicle_prototype &prototype = const_cast<vehicle_prototype &>( vid.obj() );
        for( vehicle_item_spawn &vis : prototype.item_spawns ) {
            auto &vec = vis.item_ids;
            const auto iter = std::remove_if( vec.begin(), vec.end(), item_is_blacklisted );
            vec.erase( iter, vec.end() );
        }
    }
    for( const std::pair<const itype_id, migration> &migrate : migrations ) {
        if( m_templates.find( migrate.second.replace ) == m_templates.end() ) {
            debugmsg( "Replacement item for migration %s does not exist", migrate.first.c_str() );
            continue;
        }
        for( std::pair<const item_group_id, std::unique_ptr<Item_spawn_data>> &g : m_template_groups ) {
            g.second->replace_item( migrate.first, migrate.second.replace );
        }
        // replace migrated items in requirements
        for( const std::pair<const requirement_id, requirement_data> &r : requirement_data::all() ) {
            const_cast<requirement_data &>( r.second ).replace_item( migrate.first,
                    migrate.second.replace );
        }
        // remove any recipes used to craft the migrated item
        // if there's a valid recipe, it will be for the replacement
        recipe_dictionary::delete_if( [&migrate]( const recipe & r ) {
            return !r.obsolete && r.result() == migrate.first;
        } );
        // If the default ammo of an ammo_type gets migrated, we migrate all guns using that ammo
        // type to the ammo type of whatever that default ammo was migrated to.
        // To do that we need to store a map of ammo to the migration replacement thereof.
        auto maybe_ammo = m_templates.find( migrate.first );
        // If the itype_id is valid and the itype has ammo data
        if( maybe_ammo != m_templates.end() && maybe_ammo->second.ammo ) {
            auto replacement = m_templates.find( migrate.second.replace );
            if( replacement->second.ammo ) {
                migrated_ammo.emplace( std::make_pair( migrate.first, replacement->second.ammo->type ) );
            } else {
                debugmsg( "Replacement item %s for migrated ammo %s is not ammo.",
                          migrate.second.replace.str(), migrate.first.str() );
            }
        }
        // migrate magazines as well
        auto maybe_mag = m_templates.find( migrate.first );
        if( maybe_mag != m_templates.end() && maybe_mag->second.magazine ) {
            auto replacement = m_templates.find( migrate.second.replace );
            if( replacement->second.magazine ) {
                migrated_magazines.emplace( std::make_pair( migrate.first, migrate.second.replace ) );
            } else {
                debugmsg( "Replacement item %s for migrated magazine %s is not a magazine.",
                          migrate.second.replace.str(), migrate.first.str() );
            }
        }
    }
    for( vproto_id &vid : vehicle_prototype::get_all() ) {
        vehicle_prototype &prototype = const_cast<vehicle_prototype &>( vid.obj() );
        for( vehicle_item_spawn &vis : prototype.item_spawns ) {
            for( itype_id &type_to_spawn : vis.item_ids ) {
                std::map<itype_id, migration>::iterator replacement =
                    migrations.find( type_to_spawn );
                if( replacement != migrations.end() ) {
                    type_to_spawn = replacement->second.replace;
                }
            }
        }
    }
}
References requirement_data::all(), debugmsg, recipe_dictionary::delete_if(), g, vehicle_prototype::get_all(), item_blacklist, vehicle_item_spawn::item_ids, item_is_blacklisted(), vehicle_prototype::item_spawns, m_template_groups, m_templates, to_cbc_migration::migrate(), migrated_ammo, migrated_magazines, migrations, recipe::obsolete, replacement, and recipe::result().
Referenced by finalize().
finalize_post()
void Item_factory::finalize_post (itype & obj) private
Applies part of finalization that depends on other items.
Definition at line 581 of file item_factory.cpp.
{
    // erase all invalid flags (not defined in flags.json), display warning about invalid flags
    erase_if( obj.item_tags, [&]( const std::string & f ) {
        if( !json_flag::get( f ).id.is_valid() ) {
            debugmsg( "itype '%s' uses undefined flag '%s'. Please add corresponding 'json_flag' entry to json.",
                      obj.id.c_str(), f );
            return true;
        } else {
            return false;
        }
    } );
    // handle complex firearms as a special case
    if( obj.gun && !obj.has_flag( "PRIMITIVE_RANGED_WEAPON" ) ) {
        std::copy( gun_tools.begin(), gun_tools.end(), std::inserter( obj.repair, obj.repair.begin() ) );
        return;
    }
    // for each item iterate through potential repair tools
    for( const auto &tool : repair_tools ) {
        // check if item can be repaired with any of the actions?
        for( const auto &act : repair_actions ) {
            const use_function *func = m_templates[tool].get_use( act );
            if( func == nullptr ) {
                continue;
            }
            // tool has a possible repair action, check if the materials are compatible
            const auto &opts = dynamic_cast<const repair_item_actor *>( func->get_actor_ptr() )->materials;
            if( std::any_of( obj.materials.begin(), obj.materials.end(), [&opts]( const material_id & m ) {
            return opts.count( m ) > 0;
            } ) ) {
                obj.repair.insert( tool );
            }
        }
    }
    if( obj.comestible ) {
        for( const std::pair<diseasetype_id, int> elem : obj.comestible->contamination ) {
            const diseasetype_id dtype = elem.first;
            if( !dtype.is_valid() ) {
                debugmsg( "contamination in %s contains invalid diseasetype_id %s.",
                          obj.id.str(), dtype.str() );
            }
        }
    }
}
References erase_if(), and itype::item_tags.
Referenced by add_item_type(), and finalize().
finalize_pre()
void Item_factory::finalize_pre (itype & obj) private
Applies part of finalization that don't depend on other items.
Definition at line 164 of file item_factory.cpp.
{
    // TODO: separate repairing from reinforcing/enhancement
    if( obj.damage_max() == obj.damage_min() ) {
        obj.item_tags.insert( "NO_REPAIR" );
    }
    if( obj.has_flag( "STAB" ) || obj.has_flag( "SPEAR" ) ) {
        std::swap( obj.melee[DT_CUT], obj.melee[DT_STAB] );
    }
    // add usage methods (with default values) based upon qualities
    // if a method was already set the specific values remain unchanged
    for( const auto &q : obj.qualities ) {
        for( const auto &u : q.first.obj().usages ) {
            if( q.second >= u.first ) {
                emplace_usage( obj.use_methods, u.second );
            }
        }
    }
    if( obj.mod ) {
        std::string func = obj.gunmod ? "GUNMOD_ATTACH" : "TOOLMOD_ATTACH";
        emplace_usage( obj.use_methods, func );
    } else if( obj.gun ) {
        const std::string func = "detach_gunmods";
        emplace_usage( obj.use_methods, func );
    }
    if( get_option<bool>( "NO_FAULTS" ) ) {
        obj.faults.clear();
    }
    // If no category was forced via JSON automatically calculate one now
    if( !obj.category_force.is_valid() || obj.category_force.is_empty() ) {
        obj.category_force = calc_category( obj );
    }
    // use pre-cataclysm price as default if post-cataclysm price unspecified
    if( obj.price_post < 0_cent ) {
        obj.price_post = obj.price;
    }
    // use base volume if integral volume unspecified
    if( obj.integral_volume < 0_ml ) {
        obj.integral_volume = obj.volume;
    }
    // use base weight if integral weight unspecified
    if( obj.integral_weight < 0_gram ) {
        obj.integral_weight = obj.weight;
    }
    // for ammo and comestibles stack size defaults to count of initial charges
    // Set max stack size to 200 to prevent integer overflow
    if( obj.count_by_charges() ) {
        if( obj.stack_size == 0 ) {
            obj.stack_size = obj.charges_default();
        } else if( obj.stack_size > 200 ) {
            debugmsg( obj.id.str() + " stack size is too large, reducing to 200" );
            obj.stack_size = 200;
        }
    }
    // Items always should have some volume.
    // TODO: handle possible exception software?
    // TODO: make items with 0 volume an error during loading?
    if( obj.volume <= 0_ml ) {
        obj.volume = units::from_milliliter( 1 );
    }
    // set light_emission based on LIGHT_[X] flag
    for( const auto &f : obj.item_tags ) {
        int ll;
        if( sscanf( f.c_str(), "LIGHT_%i", &ll ) == 1 && ll > 0 ) {
            obj.light_emission = ll;
        }
    }
    // remove LIGHT_[X] flags
    erase_if( obj.item_tags, []( const std::string & f ) {
        return f.find( "LIGHT_" ) == 0;
    } );
    // Set max volume for containers to prevent integer overflow
    if( obj.container && obj.container->contains > 10000_liter ) {
        debugmsg( obj.id.str() + " storage volume is too large, reducing to 10000 liters" );
        obj.container->contains = 10000_liter;
    }
    if( obj.ammo ) {
        // for ammo not specifying loudness (or an explicit zero) derive value from other properties
        if( obj.ammo->loudness < 0 ) {
            obj.ammo->loudness = obj.ammo->range * 2;
            for( const damage_unit &du : obj.ammo->damage ) {
                obj.ammo->loudness += ( du.amount + du.res_pen ) * 2;
            }
        }
        const auto &mats = obj.materials;
        if( std::find( mats.begin(), mats.end(), material_id( "hydrocarbons" ) ) == mats.end() &&
            std::find( mats.begin(), mats.end(), material_id( "oil" ) ) == mats.end() ) {
            const auto &ammo_effects = obj.ammo->ammo_effects;
            obj.ammo->cookoff = ammo_effects.count( ammo_effect_INCENDIARY ) > 0 ||
                                ammo_effects.count( ammo_effect_COOKOFF ) > 0;
            static const std::set<ammo_effect_str_id> special_cookoff_tags = {{
                    ammo_effect_EXPLOSIVE, ammo_effect_EXPLOSIVE_BIG, ammo_effect_EXPLOSIVE_HUGE, ammo_effect_EXPLOSIVE_SMALL, ammo_effect_FLASHBANG, ammo_effect_FRAG, ammo_effect_NAPALM, ammo_effect_NAPALM_BIG, ammo_effect_SMOKE, ammo_effect_SMOKE_BIG, ammo_effect_TOXICGAS,
                }
            };
            obj.ammo->special_cookoff = std::any_of( ammo_effects.begin(), ammo_effects.end(),
            []( const ammo_effect_str_id & ae_id ) {
                return special_cookoff_tags.count( ae_id ) > 0;
            } );
        } else {
            obj.ammo->cookoff = false;
            obj.ammo->special_cookoff = false;
        }
        for( auto iter = obj.ammo->ammo_effects.begin(); iter != obj.ammo->ammo_effects.end(); ) {
            const ammo_effect_str_id &ae_id = *iter;
            if( ae_id.is_valid() ) {
                iter++;
            } else {
                int dummy = 0;
                if( sscanf( ae_id.c_str(), "RECOVER_%i", &dummy ) == 1 ) {
                    obj.ammo->dont_recover_one_in *= dummy;
                } else {
                    debugmsg( "%s has unknown ammo_effect %s, removing", obj.id, ae_id );
                }
                iter = obj.ammo->ammo_effects.erase( iter );
            }
        }
    }
    const auto check_ammo_effects = []( const itype_id & id, std::set<ammo_effect_str_id> &effects ) {
        for( auto iter = effects.begin(); iter != effects.end(); ) {
            const ammo_effect_str_id &ae_id = *iter;
            if( ae_id.is_valid() ) {
                iter++;
            } else {
                debugmsg( "%s has unknown ammo_effect %s, removing", id, ae_id );
                iter = effects.erase( iter );
            }
        }
    };
    if( obj.gun ) {
        check_ammo_effects( obj.id, obj.gun->ammo_effects );
    }
    if( obj.gunmod ) {
        check_ammo_effects( obj.id, obj.gunmod->ammo_effects );
    }
    // Helper for ammo migration in following sections
    auto migrate_ammo_set = [&]( std::set<ammotype> &ammoset ) {
        for( auto ammo_type_it = ammoset.begin(); ammo_type_it != ammoset.end(); ) {
            auto maybe_migrated = migrated_ammo.find( ammo_type_it->obj().default_ammotype() );
            if( maybe_migrated != migrated_ammo.end() ) {
                ammo_type_it = ammoset.erase( ammo_type_it );
                ammoset.insert( ammoset.begin(), maybe_migrated->second );
            } else {
                ++ammo_type_it;
            }
        }
    };
    if( obj.magazine ) {
        // ensure default_ammo is set
        if( obj.magazine->default_ammo.is_null() ) {
            obj.magazine->default_ammo = ammotype( *obj.magazine->type.begin() )->default_ammotype();
        }
        // If the magazine has ammo types for which the default ammo has been migrated, we need to
        // replace those ammo types with that of the migrated ammo
        migrate_ammo_set( obj.magazine->type );
        // ensure default_ammo is migrated if need be
        auto maybe_migrated = migrated_ammo.find( obj.magazine->default_ammo );
        if( maybe_migrated != migrated_ammo.end() ) {
            obj.magazine->default_ammo = maybe_migrated->second.obj().default_ammotype();
        }
    }
    // Migrate compataible magazines
    for( auto kv : obj.magazines ) {
        for( auto mag_it = kv.second.begin(); mag_it != kv.second.end(); ) {
            auto maybe_migrated = migrated_magazines.find( *mag_it );
            if( maybe_migrated != migrated_magazines.end() ) {
                mag_it = kv.second.erase( mag_it );
                kv.second.insert( kv.second.begin(), maybe_migrated->second );
            } else {
                ++mag_it;
            }
        }
    }
    // Migrate default magazines
    for( auto kv : obj.magazine_default ) {
        auto maybe_migrated = migrated_magazines.find( kv.second );
        if( maybe_migrated != migrated_magazines.end() ) {
            kv.second = maybe_migrated->second;
        }
    }
    if( obj.mod ) {
        // Migrate acceptable ammo and ammo modifiers
        migrate_ammo_set( obj.mod->acceptable_ammo );
        migrate_ammo_set( obj.mod->ammo_modifier );
        for( auto kv = obj.mod->magazine_adaptor.begin(); kv != obj.mod->magazine_adaptor.end(); ) {
            auto maybe_migrated = migrated_ammo.find( kv->first.obj().default_ammotype() );
            if( maybe_migrated != migrated_ammo.end() ) {
                for( const itype_id &compatible_mag : kv->second ) {
                    obj.mod->magazine_adaptor[maybe_migrated->second].insert( compatible_mag );
                }
                kv = obj.mod->magazine_adaptor.erase( kv );
            } else {
                ++kv;
            }
        }
    }
    if( obj.gunmod && !obj.has_flag( flag_MELEE_GUNMOD ) ) {
        for( const std::pair<const gun_mode_id, gun_modifier_data> &pr : obj.gunmod->mode_modifier ) {
            if( pr.first == gun_mode_REACH ) {
                obj.item_tags.insert( flag_MELEE_GUNMOD.str() );
                break;
            }
        }
    }
    if( obj.gun ) {
        // If the gun has ammo types for which the default ammo has been migrated, we need to
        // replace those ammo types with that of the migrated ammo
        for( auto ammo_type_it = obj.gun->ammo.begin(); ammo_type_it != obj.gun->ammo.end(); ) {
            auto maybe_migrated = migrated_ammo.find( ammo_type_it->obj().default_ammotype() );
            if( maybe_migrated != migrated_ammo.end() ) {
                const ammotype old_ammo = *ammo_type_it;
                // Remove the old ammotype add the migrated version
                ammo_type_it = obj.gun->ammo.erase( ammo_type_it );
                const ammotype &new_ammo = maybe_migrated->second;
                obj.gun->ammo.insert( obj.gun->ammo.begin(), new_ammo );
                // Migrate the compatible magazines
                auto old_mag_it = obj.magazines.find( old_ammo );
                if( old_mag_it != obj.magazines.end() ) {
                    for( const itype_id &old_mag : old_mag_it->second ) {
                        obj.magazines[new_ammo].insert( old_mag );
                    }
                    obj.magazines.erase( old_ammo );
                }
                // And the default magazines for each magazine type
                auto old_default_mag_it = obj.magazine_default.find( old_ammo );
                if( old_default_mag_it != obj.magazine_default.end() ) {
                    const itype_id &old_default_mag = old_default_mag_it->second;
                    obj.magazine_default[new_ammo] = old_default_mag;
                    obj.magazine_default.erase( old_ammo );
                }
            } else {
                ++ammo_type_it;
            }
        }
        // TODO: add explicit action field to gun definitions
        const auto defmode_name = [&]() {
            if( obj.gun->clip == 1 ) {
                return translate_marker( "manual" ); // break-type actions
            } else if( obj.gun->skill_used == skill_id( "pistol" ) && obj.has_flag( "RELOAD_ONE" ) ) {
                return translate_marker( "revolver" );
            } else {
                return translate_marker( "semi" );
            }
        };
        // if the gun doesn't have a DEFAULT mode then add one now
        obj.gun->modes.emplace( gun_mode_id( "DEFAULT" ),
                                gun_modifier_data( defmode_name(), 1, std::set<std::string>() ) );
        // If a "gun" has a reach attack, give it an additional melee mode.
        if( obj.has_flag( "REACH_ATTACK" ) ) {
            obj.gun->modes.emplace( gun_mode_id( "MELEE" ),
                                    gun_modifier_data( translate_marker( "melee" ), 1,
            { "MELEE" } ) );
        }
        if( obj.gun->burst > 1 ) {
            // handle legacy JSON format
            obj.gun->modes.emplace( gun_mode_id( "AUTO" ),
                                    gun_modifier_data( translate_marker( "auto" ), obj.gun->burst,
                                            std::set<std::string>() ) );
        }
        if( obj.gun->handling < 0 ) {
            bool burst_only = std::all_of( obj.gun->modes.begin(), obj.gun->modes.end(),
            []( const std::pair<gun_mode_id, gun_modifier_data> &pr ) {
                return pr.second.qty() > 1 || pr.second.flags().count( "MELEE" ) > 0;
            } );
            // TODO: specify in JSON via classes
            if( obj.gun->skill_used == skill_id( "shotgun" ) ) {
                obj.gun->handling = 30;
            } else if( obj.gun->skill_used == skill_id( "rifle" ) ||
                       obj.gun->skill_used == skill_id( "smg" ) ) {
                obj.gun->handling = burst_only ? 40 : 20;
            } else {
                obj.gun->handling = burst_only ? 25 : 15;
            }
        }
        obj.gun->reload_noise = _( obj.gun->reload_noise );
    }
    set_allergy_flags( obj );
    hflesh_to_flesh( obj );
    npc_implied_flags( obj );
    if( obj.comestible ) {
        std::map<vitamin_id, int> &vitamins = obj.comestible->default_nutrition.vitamins;
        if( get_option<bool>( "NO_VITAMINS" ) ) {
            for( auto &vit : vitamins ) {
                if( vit.first->type() == vitamin_type::VITAMIN ) {
                    vit.second = 0;
                }
            }
        } else if( vitamins.empty() && obj.comestible->healthy >= 0 ) {
            // Default vitamins of healthy comestibles to their edible base materials if none explicitly specified.
            auto healthy = std::max( obj.comestible->healthy, 1 ) * 10;
            auto mat = obj.materials;
            // TODO: migrate inedible comestibles to appropriate alternative types.
            mat.erase( std::remove_if( mat.begin(), mat.end(), []( const string_id<material_type> &m ) {
                return !m.obj().edible();
            } ), mat.end() );
            // For comestibles composed of multiple edible materials we calculate the average.
            for( const auto &v : vitamin::all() ) {
                if( !vitamins.count( v.first ) ) {
                    for( const auto &m : mat ) {
                        double amount = m->vitamin( v.first ) * healthy / mat.size();
                        vitamins[v.first] += std::ceil( amount );
                    }
                }
            }
        }
    }
    if( obj.tool ) {
        if( !obj.tool->subtype.is_empty() && has_template( obj.tool->subtype ) ) {
            tool_subtypes[ obj.tool->subtype ].insert( obj.id );
        }
    }
    // Legacy food heating stuff
    {
        // Needs to be split into 2 functions + flag
        if( obj.use_methods.count( "HOTPLATE" ) != 0 ) {
            obj.use_methods.erase( "HOTPLATE" );
            obj.use_methods["TOGGLE_HEATS_FOOD"] =
                use_function( "TOGGLE_HEATS_FOOD", &iuse::toggle_heats_food );
            cauterize_actor cauterize;
            cauterize.flame = false;
            obj.use_methods["cauterize"] = cauterize.clone();
            obj.item_tags.emplace( "HEATS_FOOD_USING_CHARGES" );
        }
        if( obj.use_methods.count( "HEAT_FOOD" ) != 0 ) {
            obj.use_methods.erase( "HEAT_FOOD" );
            obj.item_tags.emplace( "HEATS_FOOD_USING_FIRE" );
        }
        if( obj.use_methods.count( "HEATPACK" ) != 0 ) {
            obj.use_methods.erase( "HEATPACK" );
            obj.use_methods["TOGGLE_HEATS_FOOD"] =
                use_function( "TOGGLE_HEATS_FOOD", &iuse::toggle_heats_food );
            obj.item_tags.emplace( "HEATS_FOOD_IS_CONSUMED" );
        }
    }
    for( auto &e : obj.use_methods ) {
        e.second.get_actor_ptr()->finalize( obj.id );
    }
    if( obj.drop_action.get_actor_ptr() != nullptr ) {
        obj.drop_action.get_actor_ptr()->finalize( obj.id );
    }
    if( obj.has_flag( "PERSONAL" ) ) {
        obj.layer = PERSONAL_LAYER;
    } else if( obj.has_flag( "SKINTIGHT" ) ) {
        obj.layer = UNDERWEAR_LAYER;
    } else if( obj.has_flag( "WAIST" ) ) {
        obj.layer = WAIST_LAYER;
    } else if( obj.has_flag( "OUTER" ) ) {
        obj.layer = OUTER_LAYER;
    } else if( obj.has_flag( "BELTED" ) ) {
        obj.layer = BELTED_LAYER;
    } else if( obj.has_flag( "AURA" ) ) {
        obj.layer = AURA_LAYER;
    } else {
        obj.layer = REGULAR_LAYER;
    }
    if( obj.can_use( "MA_MANUAL" ) && obj.book && obj.book->martial_art.is_null() &&
        string_starts_with( obj.get_id().str(), "manual_" ) ) {
        // HACK: Legacy martial arts books rely on a hack whereby the name of the
        // martial art is derived from the item id
        obj.book->martial_art = matype_id( "style_" + obj.get_id().str().substr( 7 ) );
    }
}
References _, vitamin::all(), itype::ammo, ammo_effect_COOKOFF, ammo_effect_EXPLOSIVE, ammo_effect_EXPLOSIVE_BIG, ammo_effect_EXPLOSIVE_HUGE, ammo_effect_EXPLOSIVE_SMALL, ammo_effect_FLASHBANG, ammo_effect_FRAG, ammo_effect_INCENDIARY, ammo_effect_NAPALM, ammo_effect_NAPALM_BIG, ammo_effect_SMOKE, ammo_effect_SMOKE_BIG, ammo_effect_TOXICGAS, damage_unit::amount, AURA_LAYER, BELTED_LAYER, itype::book, string_id< T >::c_str(), calc_category(), itype::can_use(), itype::category_force, itype::charges_default(), cauterize_actor::clone(), itype::comestible, itype::container, itype::count_by_charges(), itype::damage_max(), itype::damage_min(), debugmsg, ammunition_type::default_ammotype(), itype::drop_action, DT_CUT, DT_STAB, emplace_usage(), erase_if(), itype::faults, iuse_actor::finalize(), detail::find(), flag_MELEE_GUNMOD, cauterize_actor::flame, units::from_milliliter(), use_function::get_actor_ptr(), itype::get_id(), itype::gun, gun_mode_REACH, itype::gunmod, itype::has_flag(), has_template(), hflesh_to_flesh(), base_camps::id, itype::id, itype::integral_volume, itype::integral_weight, string_id< T >::is_empty(), string_id< T >::is_valid(), itype::item_tags, itype::layer, itype::light_emission, itype::magazine, itype::magazine_default, itype::magazines, itype::materials, matype_id, itype::melee, migrated_ammo, migrated_magazines, itype::mod, npc_implied_flags(), OUTER_LAYER, PERSONAL_LAYER, itype::price, itype::price_post, itype::qualities, REGULAR_LAYER, damage_unit::res_pen, set_allergy_flags(), itype::stack_size, string_id< T >::str(), string_starts_with(), cata::swap(), iuse::toggle_heats_food(), itype::tool, tool_subtypes, translate_marker, UNDERWEAR_LAYER, itype::use_methods, material_type::vitamin(), VITAMIN, itype::volume, WAIST_LAYER, and itype::weight.
Referenced by add_item_type(), and finalize().
find()
std::vector< const itype * > Item_factory::find (const std::function< bool(const itype &)> & func)
Find all item templates (both static and runtime) matching UnaryPredicate function.
Find all templates matching the UnaryPredicate function.
Definition at line 3287 of file item_factory.cpp.
{
    assert( frozen );
    std::vector<const itype *> res;
    for( const auto &e : m_templates ) {
        const itype *i = &e.second;
        if( func( *i ) ) {
            res.push_back( i );
        }
    }
    for( const auto &e : m_runtimes ) {
        const itype *i = e.second.get();
        if( func( *i ) ) {
            res.push_back( i );
        }
    }
    return res;
}
References frozen, m_runtimes, and m_templates.
find_template()
const itype * Item_factory::find_template (const itype_id & id) const private
Returns the itype with the given id.
This function never returns null, if the item type is unknown, a new item type is generated, stored and returned.
Parameters
id Item type id (itype::id).
Definition at line 1522 of file item_factory.cpp.
{
    assert( frozen );
    auto found = m_templates.find( id );
    if( found != m_templates.end() ) {
        return &found->second;
    }
    auto rt = m_runtimes.find( id );
    if( rt != m_runtimes.end() ) {
        return rt->second.get();
    }
    //If we didn't find the item maybe it is a building instead!
    const recipe_id &making_id = recipe_id( id.c_str() );
    if( oter_str_id( id.c_str() ).is_valid() ||
        ( making_id.is_valid() && making_id.obj().is_blueprint() ) ) {
        itype *def = new itype();
        def->id = id;
        def->name = no_translation( string_format( "DEBUG: %s", id.c_str() ) );
        def->description = making_id.obj().description;
        m_runtimes[ id ].reset( def );
        return def;
    }
    debugmsg( "Missing item definition: %s", id.c_str() );
    itype *def = new itype();
    def->id = id;
    def->name = no_translation( string_format( "undefined-%s", id.c_str() ) );
    def->description = no_translation( string_format( "Missing item definition for %s.", id.c_str() ) );
    m_runtimes[ id ].reset( def );
    return def;
}
References debugmsg, itype::description, recipe::description, frozen, base_camps::id, itype::id, recipe::is_blueprint(), string_id< T >::is_valid(), m_runtimes, m_templates, itype::name, no_translation(), string_id< T >::obj(), and string_format().
Referenced by check_definitions().
get_all_group_names()
std::vector< item_group_id > Item_factory::get_all_group_names ()
Returns the idents of all item groups that are known.
Definition at line 3187 of file item_factory.cpp.
{
    std::vector<item_group_id> rval;
    for( GroupMap::value_type &group_pair : m_template_groups ) {
        rval.push_back( item_group_id( group_pair.first ) );
    }
    return rval;
}
References m_template_groups.
get_group()
Item_spawn_data * Item_factory::get_group (const item_group_id & item_group_id)
Get the item group object.
Returns null if the item group does not exists.
Definition at line 1559 of file item_factory.cpp.
{
    GroupMap::iterator group_iter = m_template_groups.find( item_group_id );
    if( group_iter != m_template_groups.end() ) {
        return group_iter->second.get();
    }
    return nullptr;
}
References m_template_groups.
get_runtime_types()
std::vector< const itype * > Item_factory::get_runtime_types () const
Get item types created at runtime.
Definition at line 3275 of file item_factory.cpp.
{
    std::vector<const itype *> res;
    res.reserve( m_runtimes.size() );
    for( const auto &e : m_runtimes ) {
        res.push_back( e.second.get() );
    }
    return res;
}
References m_runtimes.
has_iuse()
bool Item_factory::has_iuse (const item_action_id & type) const inline
Check if an iuse is known to the Item_factory.
Parameters
type Iuse type id.
Definition at line 218 of file item_factory.h.
{
            return iuse_function_list.find( type ) != iuse_function_list.end();
        }
References iuse_function_list, and type.
Referenced by usage_from_object().
has_template()
bool Item_factory::has_template (const itype_id & id) const private
Check if an item type is known to the Item_factory.
Parameters
id Item type id (itype::id).
Definition at line 3253 of file item_factory.cpp.
{
    return m_templates.count( id ) || m_runtimes.count( id );
}
References m_runtimes, and m_templates.
Referenced by check_definitions(), create_artifact_id(), and finalize_pre().
init()
void Item_factory::init () private
Definition at line 850 of file item_factory.cpp.
{
    add_iuse( "ACIDBOMB_ACT", &iuse::acidbomb_act );
    add_iuse( "ADRENALINE_INJECTOR", &iuse::adrenaline_injector );
    add_iuse( "ALCOHOL", &iuse::alcohol_medium );
    add_iuse( "ALCOHOL_STRONG", &iuse::alcohol_strong );
    add_iuse( "ALCOHOL_WEAK", &iuse::alcohol_weak );
    add_iuse( "ANTIASTHMATIC", &iuse::antiasthmatic );
    add_iuse( "ANTIBIOTIC", &iuse::antibiotic );
    add_iuse( "ANTICONVULSANT", &iuse::anticonvulsant );
    add_iuse( "ANTIFUNGAL", &iuse::antifungal );
    add_iuse( "ANTIPARASITIC", &iuse::antiparasitic );
    add_iuse( "ARROW_FLAMABLE", &iuse::arrow_flammable );
    add_iuse( "ARTIFACT", &iuse::artifact );
    add_iuse( "AUTOCLAVE", &iuse::autoclave );
    add_iuse( "BELL", &iuse::bell );
    add_iuse( "BLECH", &iuse::blech );
    add_iuse( "BLECH_BECAUSE_UNCLEAN", &iuse::blech_because_unclean );
    add_iuse( "BOLTCUTTERS", &iuse::boltcutters );
    add_iuse( "C4", &iuse::c4 );
    add_iuse( "TOW_ATTACH", &iuse::tow_attach );
    add_iuse( "CABLE_ATTACH", &iuse::cable_attach );
    add_iuse( "CAMERA", &iuse::camera );
    add_iuse( "CAN_GOO", &iuse::can_goo );
    add_iuse( "COIN_FLIP", &iuse::coin_flip );
    add_iuse( "DIRECTIONAL_HOLOGRAM", &iuse::directional_hologram );
    add_iuse( "CAPTURE_MONSTER_ACT", &iuse::capture_monster_act );
    add_iuse( "CAPTURE_MONSTER_VEH", &iuse::capture_monster_veh );
    add_iuse( "CARVER_OFF", &iuse::carver_off );
    add_iuse( "CARVER_ON", &iuse::carver_on );
    add_iuse( "CATFOOD", &iuse::catfood );
    add_iuse( "CATTLEFODDER", &iuse::feedcattle );
    add_iuse( "CHAINSAW_OFF", &iuse::chainsaw_off );
    add_iuse( "CHAINSAW_ON", &iuse::chainsaw_on );
    add_iuse( "CHEW", &iuse::chew );
    add_iuse( "RPGDIE", &iuse::rpgdie );
    add_iuse( "BIRDFOOD", &iuse::feedbird );
    add_iuse( "BURROW", &iuse::burrow );
    add_iuse( "CHOP_TREE", &iuse::chop_tree );
    add_iuse( "CHOP_LOGS", &iuse::chop_logs );
    add_iuse( "CIRCSAW_ON", &iuse::circsaw_on );
    add_iuse( "CLEAR_RUBBLE", &iuse::clear_rubble );
    add_iuse( "COMBATSAW_OFF", &iuse::combatsaw_off );
    add_iuse( "COMBATSAW_ON", &iuse::combatsaw_on );
    add_iuse( "E_COMBATSAW_OFF", &iuse::e_combatsaw_off );
    add_iuse( "E_COMBATSAW_ON", &iuse::e_combatsaw_on );
    add_iuse( "CONTACTS", &iuse::contacts );
    add_iuse( "CROWBAR", &iuse::crowbar );
    add_iuse( "CS_LAJATANG_OFF", &iuse::cs_lajatang_off );
    add_iuse( "CS_LAJATANG_ON", &iuse::cs_lajatang_on );
    add_iuse( "ECS_LAJATANG_OFF", &iuse::ecs_lajatang_off );
    add_iuse( "ECS_LAJATANG_ON", &iuse::ecs_lajatang_on );
    add_iuse( "DATURA", &iuse::datura );
    add_iuse( "DIG", &iuse::dig );
    add_iuse( "DIVE_TANK", &iuse::dive_tank );
    add_iuse( "DIRECTIONAL_ANTENNA", &iuse::directional_antenna );
    add_iuse( "DISASSEMBLE", &iuse::disassemble );
    add_iuse( "CRAFT", &iuse::craft );
    add_iuse( "DOGFOOD", &iuse::dogfood );
    add_iuse( "DOG_WHISTLE", &iuse::dog_whistle );
    add_iuse( "DOLLCHAT", &iuse::talking_doll );
    add_iuse( "ECIG", &iuse::ecig );
    add_iuse( "EHANDCUFFS", &iuse::ehandcuffs );
    add_iuse( "EINKTABLETPC", &iuse::einktabletpc );
    add_iuse( "ELEC_CHAINSAW_OFF", &iuse::elec_chainsaw_off );
    add_iuse( "ELEC_CHAINSAW_ON", &iuse::elec_chainsaw_on );
    add_iuse( "EXTINGUISHER", &iuse::extinguisher );
    add_iuse( "EYEDROPS", &iuse::eyedrops );
    add_iuse( "FILL_PIT", &iuse::fill_pit );
    add_iuse( "FIRECRACKER", &iuse::firecracker );
    add_iuse( "FIRECRACKER_ACT", &iuse::firecracker_act );
    add_iuse( "FIRECRACKER_PACK", &iuse::firecracker_pack );
    add_iuse( "FIRECRACKER_PACK_ACT", &iuse::firecracker_pack_act );
    add_iuse( "FISH_ROD", &iuse::fishing_rod );
    add_iuse( "FISH_TRAP", &iuse::fish_trap );
    // Obsolete
    add_iuse( "FLUMED", &iuse::flumed );
    add_iuse( "FLUSLEEP", &iuse::flusleep );
    add_iuse( "FOODPERSON", &iuse::foodperson );
    add_iuse( "FUNGICIDE", &iuse::fungicide );
    add_iuse( "GASMASK", &iuse::gasmask,
              translate_marker( "Can be activated to <good>increase environmental "
                                "protection</good>.  Will consume charges when active, "
                                "but <info>only when environmental hazards are "
                                "present</info>."
                              ) );
    add_iuse( "GEIGER", &iuse::geiger );
    add_iuse( "GRANADE", &iuse::granade );
    add_iuse( "GRANADE_ACT", &iuse::granade_act );
    add_iuse( "GRENADE_INC_ACT", &iuse::grenade_inc_act );
    add_iuse( "GUN_REPAIR", &iuse::gun_repair );
    add_iuse( "GUNMOD_ATTACH", &iuse::gunmod_attach );
    add_iuse( "TOOLMOD_ATTACH", &iuse::toolmod_attach );
    add_iuse( "HACKSAW", &iuse::hacksaw );
    add_iuse( "HAIRKIT", &iuse::hairkit );
    add_iuse( "HAMMER", &iuse::hammer );
    add_iuse( "HONEYCOMB", &iuse::honeycomb );
    add_iuse( "INHALER", &iuse::inhaler );
    add_iuse( "JACKHAMMER", &iuse::jackhammer );
    add_iuse( "JET_INJECTOR", &iuse::jet_injector );
    add_iuse( "LADDER", &iuse::ladder );
    add_iuse( "LUMBER", &iuse::lumber );
    add_iuse( "MAGIC_8_BALL", &iuse::magic_8_ball );
    add_iuse( "PLAY_GAME", &iuse::play_game );
    add_iuse( "MAKEMOUND", &iuse::makemound );
    add_iuse( "DIG_CHANNEL", &iuse::dig_channel );
    add_iuse( "MARLOSS", &iuse::marloss );
    add_iuse( "MARLOSS_GEL", &iuse::marloss_gel );
    add_iuse( "MARLOSS_SEED", &iuse::marloss_seed );
    add_iuse( "MA_MANUAL", &iuse::ma_manual );
    add_iuse( "MEDITATE", &iuse::meditate );
    add_iuse( "METH", &iuse::meth );
    add_iuse( "MININUKE", &iuse::mininuke );
    add_iuse( "MOLOTOV_LIT", &iuse::molotov_lit );
    add_iuse( "MOP", &iuse::mop );
    add_iuse( "MP3", &iuse::mp3 );
    add_iuse( "MP3_ON", &iuse::mp3_on );
    add_iuse( "MULTICOOKER", &iuse::multicooker );
    add_iuse( "MYCUS", &iuse::mycus );
    add_iuse( "NOISE_EMITTER_OFF", &iuse::noise_emitter_off );
    add_iuse( "NOISE_EMITTER_ON", &iuse::noise_emitter_on );
    add_iuse( "NOTE_BIONICS", &iuse::note_bionics );
    add_iuse( "OXYGEN_BOTTLE", &iuse::oxygen_bottle );
    add_iuse( "OXYTORCH", &iuse::oxytorch );
    add_iuse( "PACK_CBM", &iuse::pack_cbm );
    add_iuse( "PACK_ITEM", &iuse::pack_item );
    add_iuse( "PHEROMONE", &iuse::pheromone );
    add_iuse( "PICKAXE", &iuse::pickaxe );
    add_iuse( "PLANTBLECH", &iuse::plantblech );
    add_iuse( "POISON", &iuse::poison );
    add_iuse( "PORTABLE_GAME", &iuse::portable_game );
    add_iuse( "PORTAL", &iuse::portal );
    add_iuse( "PROZAC", &iuse::prozac );
    add_iuse( "PURIFIER", &iuse::purifier );
    add_iuse( "PURIFY_IV", &iuse::purify_iv );
    add_iuse( "PURIFY_SMART", &iuse::purify_smart );
    add_iuse( "RADGLOVE", &iuse::radglove );
    add_iuse( "RADIOCAR", &iuse::radiocar );
    add_iuse( "RADIOCARON", &iuse::radiocaron );
    add_iuse( "RADIOCONTROL", &iuse::radiocontrol );
    add_iuse( "RADIO_MOD", &iuse::radio_mod );
    add_iuse( "RADIO_OFF", &iuse::radio_off );
    add_iuse( "RADIO_ON", &iuse::radio_on );
    add_iuse( "REMOTEVEH", &iuse::remoteveh );
    add_iuse( "REMOVE_ALL_MODS", &iuse::remove_all_mods );
    add_iuse( "REPORT_GRID_CHARGE", &iuse::report_grid_charge );
    add_iuse( "REPORT_GRID_CONNECTIONS", &iuse::report_grid_connections );
    add_iuse( "RM13ARMOR_OFF", &iuse::rm13armor_off );
    add_iuse( "RM13ARMOR_ON", &iuse::rm13armor_on );
    add_iuse( "ROBOTCONTROL", &iuse::robotcontrol );
    add_iuse( "SEED", &iuse::seed );
    add_iuse( "SEWAGE", &iuse::sewage );
    add_iuse( "SHAVEKIT", &iuse::shavekit );
    add_iuse( "SHOCKTONFA_OFF", &iuse::shocktonfa_off );
    add_iuse( "SHOCKTONFA_ON", &iuse::shocktonfa_on );
    add_iuse( "SIPHON", &iuse::siphon );
    add_iuse( "SLEEP", &iuse::sleep );
    add_iuse( "SMOKING", &iuse::smoking );
    add_iuse( "SOLARPACK", &iuse::solarpack );
    add_iuse( "SOLARPACK_OFF", &iuse::solarpack_off );
    add_iuse( "SPRAY_CAN", &iuse::spray_can );
    add_iuse( "STIMPACK", &iuse::stimpack );
    add_iuse( "STRONG_ANTIBIOTIC", &iuse::strong_antibiotic );
    add_iuse( "TAZER", &iuse::tazer );
    add_iuse( "TAZER2", &iuse::tazer2 );
    add_iuse( "TELEPORT", &iuse::teleport );
    add_iuse( "THORAZINE", &iuse::thorazine );
    add_iuse( "THROWABLE_EXTINGUISHER_ACT", &iuse::throwable_extinguisher_act );
    add_iuse( "TOWEL", &iuse::towel );
    add_iuse( "TOGGLE_HEATS_FOOD", &iuse::toggle_heats_food );
    add_iuse( "TRIMMER_OFF", &iuse::trimmer_off );
    add_iuse( "TRIMMER_ON", &iuse::trimmer_on );
    add_iuse( "UNFOLD_GENERIC", &iuse::unfold_generic );
    add_iuse( "UNPACK_ITEM", &iuse::unpack_item );
    add_iuse( "VACCINE", &iuse::vaccine );
    add_iuse( "CALL_OF_TINDALOS", &iuse::call_of_tindalos );
    add_iuse( "BLOOD_DRAW", &iuse::blood_draw );
    add_iuse( "MIND_SPLICER", &iuse::mind_splicer );
    add_iuse( "VIBE", &iuse::vibe );
    add_iuse( "HAND_CRANK", &iuse::hand_crank );
    add_iuse( "VORTEX", &iuse::vortex );
    add_iuse( "WASH_SOFT_ITEMS", &iuse::wash_soft_items );
    add_iuse( "WASH_HARD_ITEMS", &iuse::wash_hard_items );
    add_iuse( "WASH_ALL_ITEMS", &iuse::wash_all_items );
    add_iuse( "WATER_PURIFIER", &iuse::water_purifier );
    add_iuse( "WEAK_ANTIBIOTIC", &iuse::weak_antibiotic );
    add_iuse( "WEATHER_TOOL", &iuse::weather_tool );
    add_iuse( "WEED_CAKE", &iuse::weed_cake );
    add_iuse( "XANAX", &iuse::xanax );
    // Obsolete - just dummies, won't be called
    add_iuse( "HOTPLATE", &iuse::toggle_heats_food );
    add_iuse( "HEAT_FOOD", &iuse::toggle_heats_food );
    add_iuse( "HEATPACK", &iuse::toggle_heats_food );
    add_actor( std::make_unique<ammobelt_actor>() );
    add_actor( std::make_unique<bandolier_actor>() );
    add_actor( std::make_unique<cauterize_actor>() );
    add_actor( std::make_unique<consume_drug_iuse>() );
    add_actor( std::make_unique<delayed_transform_iuse>() );
    add_actor( std::make_unique<set_transform_iuse>() );
    add_actor( std::make_unique<set_transformed_iuse>() );
    add_actor( std::make_unique<enzlave_actor>() );
    add_actor( std::make_unique<explosion_iuse>() );
    add_actor( std::make_unique<firestarter_actor>() );
    add_actor( std::make_unique<fireweapon_off_actor>() );
    add_actor( std::make_unique<fireweapon_on_actor>() );
    add_actor( std::make_unique<heal_actor>() );
    add_actor( std::make_unique<holster_actor>() );
    add_actor( std::make_unique<inscribe_actor>() );
    add_actor( std::make_unique<iuse_transform>() );
    add_actor( std::make_unique<unpack_actor>() );
    add_actor( std::make_unique<countdown_actor>() );
    add_actor( std::make_unique<manualnoise_actor>() );
    add_actor( std::make_unique<musical_instrument_actor>() );
    add_actor( std::make_unique<pick_lock_actor>() );
    add_actor( std::make_unique<deploy_furn_actor>() );
    add_actor( std::make_unique<place_monster_iuse>() );
    add_actor( std::make_unique<change_scent_iuse>() );
    add_actor( std::make_unique<place_npc_iuse>() );
    add_actor( std::make_unique<reveal_map_actor>() );
    add_actor( std::make_unique<salvage_actor>() );
    add_actor( std::make_unique<unfold_vehicle_iuse>() );
    add_actor( std::make_unique<place_trap_actor>() );
    add_actor( std::make_unique<emit_actor>() );
    add_actor( std::make_unique<saw_barrel_actor>() );
    add_actor( std::make_unique<install_bionic_actor>() );
    add_actor( std::make_unique<detach_gunmods_actor>() );
    add_actor( std::make_unique<mutagen_actor>() );
    add_actor( std::make_unique<mutagen_iv_actor>() );
    add_actor( std::make_unique<deploy_tent_actor>() );
    add_actor( std::make_unique<learn_spell_actor>() );
    add_actor( std::make_unique<cast_spell_actor>() );
    add_actor( std::make_unique<weigh_self_actor>() );
    add_actor( std::make_unique<sew_advanced_actor>() );
    // An empty dummy group, it will not spawn anything. However, it makes that item group
    // id valid, so it can be used all over the place without need to explicitly check for it.
    m_template_groups[item_group_id( "EMPTY_GROUP" )] = std::make_unique<Item_group>
            ( Item_group::G_COLLECTION, 100, 0,
              0 );
}
References iuse::acidbomb_act(), add_actor(), add_iuse(), iuse::adrenaline_injector(), iuse::alcohol_medium(), iuse::alcohol_strong(), iuse::alcohol_weak(), iuse::antiasthmatic(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antifungal(), iuse::antiparasitic(), iuse::arrow_flammable(), iuse::artifact(), iuse::autoclave(), iuse::bell(), iuse::blech(), iuse::blech_because_unclean(), iuse::blood_draw(), iuse::boltcutters(), iuse::burrow(), iuse::c4(), iuse::cable_attach(), iuse::call_of_tindalos(), iuse::camera(), iuse::can_goo(), iuse::capture_monster_act(), iuse::capture_monster_veh(), iuse::carver_off(), iuse::carver_on(), iuse::catfood(), iuse::chainsaw_off(), iuse::chainsaw_on(), iuse::chew(), iuse::chop_logs(), iuse::chop_tree(), iuse::circsaw_on(), iuse::clear_rubble(), iuse::coin_flip(), iuse::combatsaw_off(), iuse::combatsaw_on(), iuse::contacts(), iuse::craft(), iuse::crowbar(), iuse::cs_lajatang_off(), iuse::cs_lajatang_on(), iuse::datura(), iuse::dig(), iuse::dig_channel(), iuse::directional_antenna(), iuse::directional_hologram(), iuse::disassemble(), iuse::dive_tank(), iuse::dog_whistle(), iuse::dogfood(), iuse::e_combatsaw_off(), iuse::e_combatsaw_on(), iuse::ecig(), iuse::ecs_lajatang_off(), iuse::ecs_lajatang_on(), iuse::ehandcuffs(), iuse::einktabletpc(), iuse::elec_chainsaw_off(), iuse::elec_chainsaw_on(), iuse::extinguisher(), iuse::eyedrops(), iuse::feedbird(), iuse::feedcattle(), iuse::fill_pit(), iuse::firecracker(), iuse::firecracker_act(), iuse::firecracker_pack(), iuse::firecracker_pack_act(), iuse::fish_trap(), iuse::fishing_rod(), iuse::flumed(), iuse::flusleep(), iuse::foodperson(), iuse::fungicide(), Item_group::G_COLLECTION, iuse::gasmask(), iuse::geiger(), iuse::granade(), iuse::granade_act(), iuse::grenade_inc_act(), iuse::gun_repair(), iuse::gunmod_attach(), iuse::hacksaw(), iuse::hairkit(), iuse::hammer(), iuse::hand_crank(), iuse::honeycomb(), iuse::inhaler(), iuse::jackhammer(), iuse::jet_injector(), iuse::ladder(), iuse::lumber(), m_template_groups, iuse::ma_manual(), iuse::magic_8_ball(), iuse::makemound(), iuse::marloss(), iuse::marloss_gel(), iuse::marloss_seed(), iuse::meditate(), iuse::meth(), iuse::mind_splicer(), iuse::mininuke(), iuse::molotov_lit(), iuse::mop(), iuse::mp3(), iuse::mp3_on(), iuse::multicooker(), iuse::mycus(), iuse::noise_emitter_off(), iuse::noise_emitter_on(), iuse::note_bionics(), iuse::oxygen_bottle(), iuse::oxytorch(), iuse::pack_cbm(), iuse::pack_item(), iuse::pheromone(), iuse::pickaxe(), iuse::plantblech(), iuse::play_game(), iuse::poison(), iuse::portable_game(), iuse::portal(), iuse::prozac(), iuse::purifier(), iuse::purify_iv(), iuse::purify_smart(), iuse::radglove(), iuse::radio_mod(), iuse::radio_off(), iuse::radio_on(), iuse::radiocar(), iuse::radiocaron(), iuse::radiocontrol(), iuse::remoteveh(), iuse::remove_all_mods(), iuse::report_grid_charge(), iuse::report_grid_connections(), iuse::rm13armor_off(), iuse::rm13armor_on(), iuse::robotcontrol(), iuse::rpgdie(), iuse::seed(), iuse::sewage(), iuse::shavekit(), iuse::shocktonfa_off(), iuse::shocktonfa_on(), iuse::siphon(), iuse::sleep(), iuse::smoking(), iuse::solarpack(), iuse::solarpack_off(), iuse::spray_can(), iuse::stimpack(), iuse::strong_antibiotic(), iuse::talking_doll(), iuse::tazer(), iuse::tazer2(), iuse::teleport(), iuse::thorazine(), iuse::throwable_extinguisher_act(), iuse::toggle_heats_food(), iuse::toolmod_attach(), iuse::tow_attach(), iuse::towel(), translate_marker, iuse::trimmer_off(), iuse::trimmer_on(), iuse::unfold_generic(), iuse::unpack_item(), iuse::vaccine(), iuse::vibe(), iuse::vortex(), iuse::wash_all_items(), iuse::wash_hard_items(), iuse::wash_soft_items(), iuse::water_purifier(), iuse::weak_antibiotic(), iuse::weather_tool(), iuse::weed_cake(), and iuse::xanax().
Referenced by Item_factory(), and reset().
load() [1/20]
void Item_factory::load (islot_armor & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1849 of file item_factory.cpp.
{
    bool strict = src == "dda";
    assign( jo, "encumbrance", slot.encumber, strict, 0 );
    assign( jo, "max_encumbrance", slot.max_encumber, strict, slot.encumber );
    assign( jo, "coverage", slot.coverage, strict, 0, 100 );
    assign( jo, "material_thickness", slot.thickness, strict, 0 );
    assign( jo, "environmental_protection", slot.env_resist, strict, 0 );
    assign( jo, "environmental_protection_with_filter", slot.env_resist_w_filter, strict, 0 );
    assign( jo, "warmth", slot.warmth, strict, 0 );
    assign( jo, "storage", slot.storage, strict, 0_ml );
    assign( jo, "weight_capacity_modifier", slot.weight_capacity_modifier );
    assign( jo, "weight_capacity_bonus", slot.weight_capacity_bonus, strict, 0_gram );
    assign( jo, "valid_mods", slot.valid_mods, strict );
    assign_coverage_from_json( jo, "covers", slot.covers, slot.sided );
}
References assign(), assign_coverage_from_json(), islot_armor::coverage, islot_armor::covers, islot_armor::encumber, islot_armor::env_resist, islot_armor::env_resist_w_filter, islot_armor::max_encumber, islot_armor::sided, islot_armor::storage, islot_armor::thickness, islot_armor::valid_mods, islot_armor::warmth, islot_armor::weight_capacity_bonus, and islot_armor::weight_capacity_modifier.
load() [2/20]
void Item_factory::load (islot_artifact & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1646 of file item_factory.cpp.
{
    slot.charge_type = jo.get_enum_value( "charge_type", ARTC_NULL );
    slot.charge_req  = jo.get_enum_value( "charge_req",  ACR_NULL );
    // No dreams unless specified for artifacts embedded in items.
    // If specifying dreams, message should be set too,
    // since the array with the defaults isn't accessible from here.
    slot.dream_freq_unmet = jo.get_int( "dream_freq_unmet", 0 );
    slot.dream_freq_met   = jo.get_int( "dream_freq_met",   0 );
    // TODO: Make sure it doesn't cause problems if this is empty
    slot.dream_msg_unmet  = jo.get_string_array( "dream_unmet" );
    slot.dream_msg_met    = jo.get_string_array( "dream_met" );
    load_optional_enum_array( slot.effects_wielded, jo, "effects_wielded" );
    load_optional_enum_array( slot.effects_activated, jo, "effects_activated" );
    load_optional_enum_array( slot.effects_carried, jo, "effects_carried" );
    load_optional_enum_array( slot.effects_worn, jo, "effects_worn" );
}
References ACR_NULL, ARTC_NULL, islot_artifact::charge_req, islot_artifact::charge_type, islot_artifact::dream_freq_met, islot_artifact::dream_freq_unmet, islot_artifact::dream_msg_met, islot_artifact::dream_msg_unmet, islot_artifact::effects_activated, islot_artifact::effects_carried, islot_artifact::effects_wielded, islot_artifact::effects_worn, JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_string_array(), and load_optional_enum_array().
load() [3/20]
void Item_factory::load (islot_battery & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2263 of file item_factory.cpp.
{
    slot.max_capacity = read_from_json_string<units::energy>( *jo.get_raw( "max_capacity" ),
                        units::energy_units );
}
References units::energy_units, JsonObject::get_raw(), and islot_battery::max_capacity.
load() [4/20]
void Item_factory::load (islot_bionic & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2278 of file item_factory.cpp.
{
    bool strict = src == "dda";
    if( jo.has_member( "bionic_id" ) ) {
        assign( jo, "bionic_id", slot.id, strict );
    } else {
        assign( jo, "id", slot.id, strict );
    }
    assign( jo, "difficulty", slot.difficulty, strict, 0 );
    assign( jo, "is_upgrade", slot.is_upgrade );
    assign( jo, "installation_data", slot.installation_data );
}
References assign(), islot_bionic::difficulty, JsonObject::has_member(), islot_bionic::id, islot_bionic::installation_data, and islot_bionic::is_upgrade.
load() [5/20]
void Item_factory::load (islot_book & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1984 of file item_factory.cpp.
{
    bool strict = src == "dda";
    assign( jo, "max_level", slot.level, strict, 0, MAX_SKILL );
    assign( jo, "required_level", slot.req, strict, 0, MAX_SKILL );
    assign( jo, "fun", slot.fun, strict );
    assign( jo, "intelligence", slot.intel, strict, 0 );
    if( jo.has_int( "time" ) ) {
        slot.time = jo.get_int( "time" );
    } else if( jo.has_string( "time" ) ) {
        slot.time = to_minutes<int>( read_from_json_string<time_duration>( *jo.get_raw( "time" ),
                                     time_duration::units ) );
    }
    assign( jo, "skill", slot.skill, strict );
    assign( jo, "martial_art", slot.martial_art, strict );
    assign( jo, "chapters", slot.chapters, strict, 0 );
}
References assign(), islot_book::chapters, islot_book::fun, JsonObject::get_int(), JsonObject::get_raw(), JsonObject::has_int(), JsonObject::has_string(), islot_book::intel, islot_book::level, islot_book::martial_art, MAX_SKILL, islot_book::req, islot_book::skill, islot_book::time, and time_duration::units.
load() [6/20]
void Item_factory::load (islot_brewable & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2134 of file item_factory.cpp.
{
    assign( jo, "time", slot.time, false, 1_turns );
    jo.read( "results", slot.results, true );
}
References assign(), JsonObject::read(), islot_brewable::results, and islot_brewable::time.
load() [7/20]
void Item_factory::load (islot_comestible & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2012 of file item_factory.cpp.
{
    bool strict = src == "dda";
    JsonObject relative = jo.get_object( "relative" );
    JsonObject proportional = jo.get_object( "proportional" );
    relative.allow_omitted_members();
    proportional.allow_omitted_members();
    assign( jo, "comestible_type", slot.comesttype, strict );
    assign( jo, "tool", slot.tool, strict );
    assign( jo, "charges", slot.def_charges, strict, 1 );
    assign( jo, "quench", slot.quench, strict );
    assign( jo, "fun", slot.fun, strict );
    assign( jo, "stim", slot.stim, strict );
    assign( jo, "fatigue_mod", slot.fatigue_mod, strict );
    assign( jo, "healthy", slot.healthy, strict );
    assign( jo, "parasites", slot.parasites, strict, 0 );
    assign( jo, "radiation", slot.radiation, strict );
    assign( jo, "freezing_point", slot.freeze_point, strict );
    assign( jo, "spoils_in", slot.spoils, strict, 1_hours );
    assign( jo, "cooks_like", slot.cooks_like, strict );
    assign( jo, "smoking_result", slot.smoking_result, strict );
    for( const JsonObject &jsobj : jo.get_array( "contamination" ) ) {
        slot.contamination.emplace( diseasetype_id( jsobj.get_string( "disease" ) ),
                                    jsobj.get_int( "probability" ) );
    }
    if( jo.has_member( "primary_material" ) ) {
        std::string mat = jo.get_string( "primary_material" );
        slot.specific_heat_solid = material_id( mat )->specific_heat_solid();
        slot.specific_heat_liquid = material_id( mat )->specific_heat_liquid();
        slot.latent_heat = material_id( mat )->latent_heat();
    } else if( jo.has_member( "material" ) ) {
        float specific_heat_solid = 0;
        float specific_heat_liquid = 0;
        float latent_heat = 0;
        for( const std::string &m : jo.get_tags( "material" ) ) {
            specific_heat_solid += material_id( m )->specific_heat_solid();
            specific_heat_liquid += material_id( m )->specific_heat_liquid();
            latent_heat += material_id( m )->latent_heat();
        }
        // Average based on number of materials.
        slot.specific_heat_liquid = specific_heat_liquid / jo.get_tags( "material" ).size();
        slot.specific_heat_solid = specific_heat_solid / jo.get_tags( "material" ).size();
        slot.latent_heat = latent_heat / jo.get_tags( "material" ).size();
    }
    bool is_not_boring = false;
    if( jo.has_member( "primary_material" ) ) {
        std::string mat = jo.get_string( "primary_material" );
        is_not_boring = is_not_boring || mat == "junk";
    }
    if( jo.has_member( "material" ) ) {
        for( const std::string &m : jo.get_tags( "material" ) ) {
            is_not_boring = is_not_boring || m == "junk";
        }
    }
    // Junk food never gets old by default, but this can still be overridden.
    if( is_not_boring ) {
        slot.monotony_penalty = 0;
    }
    assign( jo, "monotony_penalty", slot.monotony_penalty, strict );
    if( jo.has_string( "addiction_type" ) ) {
        slot.add = addiction_type( jo.get_string( "addiction_type" ) );
    }
    assign( jo, "addiction_potential", slot.addict, strict );
    bool got_calories = false;
    if( jo.has_member( "calories" ) ) {
        slot.default_nutrition.kcal = jo.get_int( "calories" );
        got_calories = true;
    } else if( relative.has_member( "calories" ) ) {
        slot.default_nutrition.kcal += relative.get_int( "calories" );
        got_calories = true;
    } else if( proportional.has_member( "calories" ) ) {
        slot.default_nutrition.kcal *= proportional.get_float( "calories" );
        got_calories = true;
    } else if( jo.has_member( "nutrition" ) ) {
        slot.default_nutrition.kcal = jo.get_int( "nutrition" ) * islot_comestible::kcal_per_nutr;
    }
    if( jo.has_member( "nutrition" ) && got_calories ) {
        jo.throw_error( "cannot specify both nutrition and calories", "nutrition" );
    }
    // any specification of vitamins suppresses use of material defaults @see Item_factory::finalize
    if( jo.has_array( "vitamins" ) ) {
        for( JsonArray pair : jo.get_array( "vitamins" ) ) {
            vitamin_id vit( pair.get_string( 0 ) );
            slot.default_nutrition.vitamins[ vit ] = pair.get_int( 1 );
        }
    } else {
        if( relative.has_int( "vitamins" ) ) {
            // allows easy specification of 'fortified' comestibles
            for( auto &v : vitamin::all() ) {
                slot.default_nutrition.vitamins[ v.first ] += relative.get_int( "vitamins" );
            }
        } else if( relative.has_array( "vitamins" ) ) {
            for( JsonArray pair : relative.get_array( "vitamins" ) ) {
                vitamin_id vit( pair.get_string( 0 ) );
                slot.default_nutrition.vitamins[ vit ] += pair.get_int( 1 );
            }
        }
    }
    if( jo.has_string( "rot_spawn" ) ) {
        slot.rot_spawn = mongroup_id( jo.get_string( "rot_spawn" ) );
    }
    assign( jo, "rot_spawn_chance", slot.rot_spawn_chance, strict, 0 );
}
References islot_comestible::add, islot_comestible::addict, addiction_type(), vitamin::all(), JsonObject::allow_omitted_members(), assign(), islot_comestible::comesttype, islot_comestible::contamination, islot_comestible::cooks_like, islot_comestible::def_charges, islot_comestible::default_nutrition, islot_comestible::fatigue_mod, islot_comestible::freeze_point, islot_comestible::fun, JsonObject::get_array(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), islot_comestible::healthy, nutrients::kcal, islot_comestible::kcal_per_nutr, islot_comestible::latent_heat, material_type::latent_heat(), islot_comestible::monotony_penalty, islot_comestible::parasites, islot_comestible::quench, islot_comestible::radiation, islot_comestible::rot_spawn, islot_comestible::rot_spawn_chance, islot_comestible::smoking_result, islot_comestible::specific_heat_liquid, material_type::specific_heat_liquid(), islot_comestible::specific_heat_solid, material_type::specific_heat_solid(), islot_comestible::spoils, islot_comestible::stim, JsonObject::throw_error(), islot_comestible::tool, and nutrients::vitamins.
load() [8/20]
void Item_factory::load (islot_container & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2169 of file item_factory.cpp.
{
    assign( jo, "contains", slot.contains );
    assign( jo, "seals", slot.seals );
    assign( jo, "watertight", slot.watertight );
    assign( jo, "preserves", slot.preserves );
    assign( jo, "unseals_into", slot.unseals_into );
}
References assign(), islot_container::contains, islot_container::preserves, islot_container::seals, islot_container::unseals_into, and islot_container::watertight.
load() [9/20]
void Item_factory::load (islot_engine & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1715 of file item_factory.cpp.
{
    assign( jo, "displacement", slot.displacement );
}
References assign(), and islot_engine::displacement.
load() [10/20]
void Item_factory::load (islot_fuel & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1744 of file item_factory.cpp.
{
    bool strict = src == "dda";
    assign( jo, "energy", slot.energy, strict, 0.001f );
    if( jo.has_member( "pump_terrain" ) ) {
        slot.pump_terrain = jo.get_string( "pump_terrain" );
    }
    if( jo.has_member( "explosion_data" ) ) {
        slot.has_explode_data = true;
        JsonObject jo_ed = jo.get_object( "explosion_data" );
        slot.explosion_data.explosion_chance_hot = jo_ed.get_int( "chance_hot" );
        slot.explosion_data.explosion_chance_cold = jo_ed.get_int( "chance_cold" );
        slot.explosion_data.explosion_factor = jo_ed.get_float( "factor" );
        slot.explosion_data.fiery_explosion = jo_ed.get_bool( "fiery" );
        slot.explosion_data.fuel_size_factor = jo_ed.get_float( "size_factor" );
    }
}
References assign(), islot_fuel::energy, fuel_explosion::explosion_chance_cold, fuel_explosion::explosion_chance_hot, islot_fuel::explosion_data, fuel_explosion::explosion_factor, fuel_explosion::fiery_explosion, fuel_explosion::fuel_size_factor, JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), islot_fuel::has_explode_data, JsonObject::has_member(), and islot_fuel::pump_terrain.
load() [11/20]
void Item_factory::load (islot_gun & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1772 of file item_factory.cpp.
{
    bool strict = src == "dda";
    if( jo.has_member( "burst" ) && jo.has_member( "modes" ) ) {
        jo.throw_error( "cannot specify both burst and modes", "burst" );
    }
    assign( jo, "skill", slot.skill_used, strict );
    if( jo.has_array( "ammo" ) ) {
        slot.ammo.clear();
        for( const std::string id : jo.get_array( "ammo" ) ) {
            slot.ammo.insert( ammotype( id ) );
        }
    } else if( jo.has_string( "ammo" ) ) {
        slot.ammo.clear();
        slot.ammo.insert( ammotype( jo.get_string( "ammo" ) ) );
    }
    assign( jo, "range", slot.range, strict );
    // Damage instance assign reader handles pierce
    assign( jo, "ranged_damage", slot.damage, strict, damage_instance( DT_NULL, -20, -20, -20, -20 ) );
    assign( jo, "dispersion", slot.dispersion, strict );
    assign( jo, "sight_dispersion", slot.sight_dispersion, strict, 0, static_cast<int>( MAX_RECOIL ) );
    assign( jo, "recoil", slot.recoil, strict, 0 );
    assign( jo, "handling", slot.handling, strict );
    assign( jo, "durability", slot.durability, strict, 0, 10 );
    assign( jo, "burst", slot.burst, strict, 1 );
    assign( jo, "loudness", slot.loudness, strict );
    assign( jo, "clip_size", slot.clip, strict, 0 );
    assign( jo, "reload", slot.reload_time, strict, 0 );
    assign( jo, "reload_noise", slot.reload_noise, strict );
    assign( jo, "reload_noise_volume", slot.reload_noise_volume, strict, 0 );
    assign( jo, "barrel_length", slot.barrel_length, strict, 0_ml );
    assign( jo, "built_in_mods", slot.built_in_mods, strict );
    assign( jo, "default_mods", slot.default_mods, strict );
    assign( jo, "ups_charges", slot.ups_charges, strict, 0 );
    assign( jo, "blackpowder_tolerance", slot.blackpowder_tolerance, strict, 0 );
    assign( jo, "min_cycle_recoil", slot.min_cycle_recoil, strict, 0 );
    assign( jo, "ammo_effects", slot.ammo_effects, strict );
    if( jo.has_array( "valid_mod_locations" ) ) {
        slot.valid_mod_locations.clear();
        for( JsonArray curr : jo.get_array( "valid_mod_locations" ) ) {
            slot.valid_mod_locations.emplace( curr.get_string( 0 ), curr.get_int( 1 ) );
        }
    }
    assign( jo, "modes", slot.modes );
}
References islot_gun::ammo, islot_gun::ammo_effects, assign(), islot_gun::barrel_length, islot_gun::blackpowder_tolerance, islot_gun::built_in_mods, islot_gun::burst, islot_gun::clip, common_ranged_data::damage, islot_gun::default_mods, common_ranged_data::dispersion, DT_NULL, islot_gun::durability, JsonObject::get_array(), JsonObject::get_string(), islot_gun::handling, JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), islot_gun::loudness, MAX_RECOIL, islot_gun::min_cycle_recoil, islot_gun::modes, common_ranged_data::range, islot_gun::recoil, islot_gun::reload_noise, islot_gun::reload_noise_volume, islot_gun::reload_time, islot_gun::sight_dispersion, islot_gun::skill_used, JsonObject::throw_error(), islot_gun::ups_charges, and islot_gun::valid_mod_locations.
load() [12/20]
void Item_factory::load (islot_gunmod & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2178 of file item_factory.cpp.
{
    bool strict = src == "dda";
    assign( jo, "damage_modifier", slot.damage, strict, damage_instance( DT_NULL, -20, -20, -20,
            -20 ) );
    assign( jo, "loudness_modifier", slot.loudness );
    assign( jo, "location", slot.location );
    assign( jo, "dispersion_modifier", slot.dispersion );
    assign( jo, "sight_dispersion", slot.sight_dispersion );
    assign( jo, "aim_speed", slot.aim_speed, strict, -1 );
    assign( jo, "handling_modifier", slot.handling, strict );
    assign( jo, "range_modifier", slot.range );
    assign( jo, "consume_chance", slot.consume_chance );
    assign( jo, "consume_divisor", slot.consume_divisor );
    assign( jo, "ammo_effects", slot.ammo_effects, strict );
    assign( jo, "ups_charges_multiplier", slot.ups_charges_multiplier );
    assign( jo, "ups_charges_modifier", slot.ups_charges_modifier );
    assign( jo, "weight_multiplier", slot.weight_multiplier );
    if( jo.has_int( "install_time" ) ) {
        slot.install_time = jo.get_int( "install_time" );
    } else if( jo.has_string( "install_time" ) ) {
        slot.install_time = to_moves<int>( read_from_json_string<time_duration>
                                           ( *jo.get_raw( "install_time" ),
                                             time_duration::units ) );
    }
    if( jo.has_member( "mod_targets" ) ) {
        slot.usable.clear();
        for( const auto &t : jo.get_tags( "mod_targets" ) ) {
            slot.usable.insert( gun_type_type( t ) );
        }
    }
    assign( jo, "mode_modifier", slot.mode_modifier );
    assign( jo, "reload_modifier", slot.reload_modifier );
    assign( jo, "min_str_required_mod", slot.min_str_required_mod );
    if( jo.has_array( "add_mod" ) ) {
        slot.add_mod.clear();
        for( JsonArray curr : jo.get_array( "add_mod" ) ) {
            slot.add_mod.emplace( curr.get_string( 0 ), curr.get_int( 1 ) );
        }
    }
    assign( jo, "blacklist_mod", slot.blacklist_mod );
}
References islot_gunmod::add_mod, islot_gunmod::aim_speed, islot_gunmod::ammo_effects, assign(), islot_gunmod::blacklist_mod, islot_gunmod::consume_chance, islot_gunmod::consume_divisor, common_ranged_data::damage, common_ranged_data::dispersion, DT_NULL, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_raw(), JsonObject::get_tags(), islot_gunmod::handling, JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_string(), islot_gunmod::install_time, islot_gunmod::location, islot_gunmod::loudness, islot_gunmod::min_str_required_mod, islot_gunmod::mode_modifier, common_ranged_data::range, islot_gunmod::reload_modifier, islot_gunmod::sight_dispersion, time_duration::units, islot_gunmod::ups_charges_modifier, islot_gunmod::ups_charges_multiplier, islot_gunmod::usable, and islot_gunmod::weight_multiplier.
load() [13/20]
void Item_factory::load (islot_magazine & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2234 of file item_factory.cpp.
{
    bool strict = src == "dda";
    if( jo.has_array( "ammo_type" ) ) {
        slot.type.clear();
        for( const std::string &id : jo.get_array( "ammo_type" ) ) {
            slot.type.insert( ammotype( id ) );
        }
    } else if( jo.has_string( "ammo_type" ) ) {
        slot.type.clear();
        slot.type.insert( ammotype( jo.get_string( "ammo_type" ) ) );
    }
    assign( jo, "capacity", slot.capacity, strict, 0 );
    assign( jo, "count", slot.count, strict, 0 );
    assign( jo, "default_ammo", slot.default_ammo, strict );
    assign( jo, "reliability", slot.reliability, strict, 0, 10 );
    assign( jo, "reload_time", slot.reload_time, strict, 0 );
    assign( jo, "linkage", slot.linkage, strict );
}
References assign(), islot_magazine::capacity, islot_magazine::count, islot_magazine::default_ammo, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), islot_magazine::linkage, islot_magazine::reliability, islot_magazine::reload_time, and islot_magazine::type.
load() [14/20]
void Item_factory::load (islot_milling & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1664 of file item_factory.cpp.
{
    assign( jo, "into", slot.into_ );
    assign( jo, "conversion_rate", slot.conversion_rate_ );
}
References assign(), islot_milling::conversion_rate_, and islot_milling::into_.
load() [15/20]
void Item_factory::load (islot_mod & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1932 of file item_factory.cpp.
{
    bool strict = src == "dda";
    if( jo.has_array( "ammo_modifier" ) ) {
        for( const std::string id : jo.get_array( "ammo_modifier" ) ) {
            slot.ammo_modifier.insert( ammotype( id ) );
        }
    } else if( jo.has_string( "ammo_modifier" ) ) {
        slot.ammo_modifier.insert( ammotype( jo.get_string( "ammo_modifier" ) ) );
    }
    assign( jo, "capacity_multiplier", slot.capacity_multiplier, strict );
    if( jo.has_member( "acceptable_ammo" ) ) {
        slot.acceptable_ammo.clear();
        for( auto &e : jo.get_tags( "acceptable_ammo" ) ) {
            slot.acceptable_ammo.insert( ammotype( e ) );
        }
    }
    JsonArray mags = jo.get_array( "magazine_adaptor" );
    if( !mags.empty() ) {
        slot.magazine_adaptor.clear();
    }
    for( JsonArray arr : mags ) {
        ammotype ammo( arr.get_string( 0 ) ); // an ammo type (e.g. 9mm)
        // compatible magazines for this ammo type
        for( const std::string line : arr.get_array( 1 ) ) {
            slot.magazine_adaptor[ ammo ].insert( itype_id( line ) );
        }
    }
}
References islot_mod::acceptable_ammo, islot_mod::ammo_modifier, assign(), islot_mod::capacity_multiplier, JsonArray::empty(), JsonObject::get_array(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), itype_id, line(), and islot_mod::magazine_adaptor.
load() [16/20]
void Item_factory::load (islot_pet_armor & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1868 of file item_factory.cpp.
{
    bool strict = src == "dda";
    assign( jo, "material_thickness", slot.thickness, strict, 0 );
    assign( jo, "max_pet_vol", slot.max_vol, strict, 0_ml );
    assign( jo, "min_pet_vol", slot.min_vol, strict, 0_ml );
    assign( jo, "pet_bodytype", slot.bodytype, strict );
    assign( jo, "environmental_protection", slot.env_resist, strict, 0 );
    assign( jo, "environmental_protection_with_filter", slot.env_resist_w_filter, strict, 0 );
    assign( jo, "storage", slot.storage, strict, 0_ml );
}
References assign(), islot_pet_armor::bodytype, islot_pet_armor::env_resist, islot_pet_armor::env_resist_w_filter, islot_pet_armor::max_vol, islot_pet_armor::min_vol, islot_pet_armor::storage, and islot_pet_armor::thickness.
load() [17/20]
void Item_factory::load (islot_seed & slot, const JsonObject & jo, const std::string & src) private
Definition at line 2159 of file item_factory.cpp.
{
    assign( jo, "grow", slot.grow, false, 1_days );
    assign( jo, "fruit_div", slot.fruit_div, false, 1 );
    assign( jo, "plant_name", slot.plant_name );
    assign( jo, "fruit", slot.fruit_id );
    assign( jo, "seeds", slot.spawn_seeds );
    assign( jo, "byproducts", slot.byproducts );
}
References assign(), islot_seed::byproducts, islot_seed::fruit_div, islot_seed::fruit_id, islot_seed::grow, islot_seed::plant_name, and islot_seed::spawn_seeds.
load() [18/20]
void Item_factory::load (islot_tool & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1881 of file item_factory.cpp.
{
    bool strict = src == "dda";
    if( jo.has_array( "ammo" ) ) {
        for( const std::string id : jo.get_array( "ammo" ) ) {
            slot.ammo_id.insert( ammotype( id ) );
        }
    } else if( jo.has_string( "ammo" ) ) {
        slot.ammo_id.insert( ammotype( jo.get_string( "ammo" ) ) );
    }
    assign( jo, "max_charges", slot.max_charges, strict, 0 );
    assign( jo, "initial_charges", slot.def_charges, strict, 0 );
    assign( jo, "charges_per_use", slot.charges_per_use, strict, 0 );
    assign( jo, "charge_factor", slot.charge_factor, strict, 1 );
    assign( jo, "turns_per_charge", slot.turns_per_charge, strict, 0 );
    assign( jo, "power_draw", slot.power_draw, strict, 0 );
    assign( jo, "revert_to", slot.revert_to, strict );
    assign( jo, "revert_msg", slot.revert_msg, strict );
    assign( jo, "sub", slot.subtype, strict );
    if( jo.has_array( "rand_charges" ) ) {
        if( jo.has_member( "initial_charges" ) ) {
            jo.throw_error( "You can have a fixed initial amount of charges, or randomized.  Not both.",
                            "rand_charges" );
        }
        for( const int charge : jo.get_array( "rand_charges" ) ) {
            slot.rand_charges.push_back( charge );
        }
        if( slot.rand_charges.size() == 1 ) {
            // see item::item(...) for the use of this array
            jo.throw_error( "a rand_charges array with only one entry will be ignored, it needs at least 2 entries!",
                            "rand_charges" );
        }
    }
}
References islot_tool::ammo_id, assign(), islot_tool::charge_factor, islot_tool::charges_per_use, islot_tool::def_charges, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), islot_tool::max_charges, islot_tool::power_draw, islot_tool::rand_charges, islot_tool::revert_msg, islot_tool::revert_to, islot_tool::subtype, JsonObject::throw_error(), and islot_tool::turns_per_charge.
Referenced by load_slot().
load() [19/20]
void Item_factory::load (islot_wheel & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1729 of file item_factory.cpp.
{
    assign( jo, "diameter", slot.diameter );
    assign( jo, "width", slot.width );
}
References assign(), islot_wheel::diameter, and islot_wheel::width.
load() [20/20]
void Item_factory::load (relic & slot, const JsonObject & jo, const std::string & src) private
Definition at line 1927 of file item_factory.cpp.
{
    slot.load( jo );
}
References relic::load().
load_ammo()
void Item_factory::load_ammo (const JsonObject & jo, const std::string & src)
Definition at line 1695 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        assign( jo, "stack_size", def.stack_size, src == "dda", 1 );
        if( def.was_loaded ) {
            if( def.ammo ) {
                def.ammo->was_loaded = true;
            } else {
                def.ammo = cata::make_value<islot_ammo>();
                def.ammo->was_loaded = true;
            }
        } else {
            def.ammo = cata::make_value<islot_ammo>();
        }
        def.ammo->load( jo );
        load_basic_info( jo, def, src );
    }
}
References itype::ammo, assign(), load_basic_info(), load_definition(), itype::stack_size, and itype::was_loaded.
load_armor()
void Item_factory::load_armor (const JsonObject & jo, const std::string & src)
Definition at line 1831 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.armor, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::armor, load_basic_info(), load_definition(), and load_slot().
load_basic_info()
void Item_factory::load_basic_info (const JsonObject & jo, itype & def, const std::string & src) private
Definition at line 2398 of file item_factory.cpp.
{
    bool strict = src == "dda";
    assign( jo, "category", def.category_force, strict );
    assign( jo, "weight", def.weight, strict, 0_gram );
    assign( jo, "integral_weight", def.integral_weight, strict, 0_gram );
    assign( jo, "volume", def.volume );
    assign( jo, "price", def.price, false, 0_cent );
    assign( jo, "price_postapoc", def.price_post, false, 0_cent );
    assign( jo, "stackable", def.stackable_, strict );
    assign( jo, "integral_volume", def.integral_volume );
    assign( jo, "bashing", def.melee[DT_BASH], strict, 0 );
    assign( jo, "cutting", def.melee[DT_CUT], strict, 0 );
    assign( jo, "to_hit", def.m_to_hit, strict );
    assign( jo, "container", def.default_container );
    assign( jo, "rigid", def.rigid );
    assign( jo, "min_strength", def.min_str );
    assign( jo, "min_dexterity", def.min_dex );
    assign( jo, "min_intelligence", def.min_int );
    assign( jo, "min_perception", def.min_per );
    assign( jo, "emits", def.emits );
    assign( jo, "magazine_well", def.magazine_well );
    assign( jo, "explode_in_fire", def.explode_in_fire );
    assign( jo, "insulation", def.insulation_factor );
    assign( jo, "solar_efficiency", def.solar_efficiency );
    assign( jo, "ascii_picture", def.picture_id );
    if( jo.has_member( "thrown_damage" ) ) {
        def.thrown_damage = load_damage_instance( jo.get_array( "thrown_damage" ) );
    } else {
        // TODO: Move to finalization
        def.thrown_damage.clear();
        def.thrown_damage.add_damage( DT_BASH, def.melee[DT_BASH] + def.weight / 1.0_kilogram );
    }
    if( jo.has_member( "repairs_like" ) ) {
        jo.read( "repairs_like", def.repairs_like );
    }
    if( jo.has_member( "damage_states" ) ) {
        auto arr = jo.get_array( "damage_states" );
        def.damage_min_ = arr.get_int( 0 ) * itype::damage_scale;
        def.damage_max_ = arr.get_int( 1 ) * itype::damage_scale;
    }
    // NOTE: please also change `needs_plural` in `lang/extract_json_string.py`
    // when changing this list
    static const std::set<std::string> needs_plural = {
        "AMMO",
        "ARMOR",
        "BATTERY",
        "BIONIC_ITEM",
        "BOOK",
        "COMESTIBLE",
        "CONTAINER",
        "ENGINE",
        "GENERIC",
        "GUN",
        "GUNMOD",
        "MAGAZINE",
        "PET_ARMOR",
        "TOOL",
        "TOOLMOD",
        "TOOL_ARMOR",
        "WHEEL",
    };
    if( needs_plural.find( jo.get_string( "type" ) ) != needs_plural.end() ) {
        def.name = translation( translation::plural_tag() );
    } else {
        def.name = translation();
    }
    if( !jo.read( "name", def.name ) ) {
        jo.throw_error( "name unspecified for item type" );
    }
    if( jo.has_member( "description" ) ) {
        jo.read( "description", def.description );
    }
    if( jo.has_string( "symbol" ) ) {
        def.sym = jo.get_string( "symbol" );
    }
    if( jo.has_string( "color" ) ) {
        def.color = color_from_string( jo.get_string( "color" ) );
    }
    if( jo.has_member( "material" ) ) {
        def.materials.clear();
        for( auto &m : jo.get_tags( "material" ) ) {
            def.materials.emplace_back( m );
        }
    }
    if( jo.has_string( "phase" ) ) {
        def.phase = jo.get_enum_value<phase_id>( "phase" );
    }
    if( jo.has_array( "magazines" ) ) {
        def.magazine_default.clear();
        def.magazines.clear();
        for( JsonArray arr : jo.get_array( "magazines" ) ) {
            ammotype ammo( arr.get_string( 0 ) ); // an ammo type (e.g. 9mm)
            JsonArray compat = arr.get_array( 1 ); // compatible magazines for this ammo type
            // the first magazine for this ammo type is the default
            def.magazine_default[ ammo ] = itype_id( compat.get_string( 0 ) );
            while( compat.has_more() ) {
                def.magazines[ ammo ].insert( itype_id( compat.next_string() ) );
            }
        }
    }
    JsonArray jarr = jo.get_array( "min_skills" );
    if( !jarr.empty() ) {
        def.min_skills.clear();
    }
    for( JsonArray cur : jarr ) {
        const auto sk = skill_id( cur.get_string( 0 ) );
        if( !sk.is_valid() ) {
            jo.throw_error( string_format( "invalid skill: %s", sk.c_str() ), "min_skills" );
        }
        def.min_skills[ sk ] = cur.get_int( 1 );
    }
    if( jo.has_member( "explosion" ) ) {
        JsonObject je = jo.get_object( "explosion" );
        def.explosion = load_explosion_data( je );
    }
    assign( jo, "flags", def.item_tags );
    assign( jo, "faults", def.faults );
    if( jo.has_member( "qualities" ) ) {
        def.qualities.clear();
        set_qualities_from_json( jo, "qualities", def );
    } else {
        if( jo.has_object( "extend" ) ) {
            JsonObject tmp = jo.get_object( "extend" );
            tmp.allow_omitted_members();
            extend_qualities_from_json( tmp, "qualities", def );
        }
        if( jo.has_object( "delete" ) ) {
            JsonObject tmp = jo.get_object( "delete" );
            tmp.allow_omitted_members();
            delete_qualities_from_json( tmp, "qualities", def );
        }
    }
    if( jo.has_member( "properties" ) ) {
        set_properties_from_json( jo, "properties", def );
    }
    for( auto &s : jo.get_tags( "techniques" ) ) {
        def.techniques.insert( matec_id( s ) );
    }
    set_use_methods_from_json( jo, "use_action", def.use_methods );
    assign( jo, "countdown_interval", def.countdown_interval );
    assign( jo, "countdown_destroy", def.countdown_destroy );
    if( jo.has_string( "countdown_action" ) ) {
        def.countdown_action = usage_from_string( jo.get_string( "countdown_action" ) );
    } else if( jo.has_object( "countdown_action" ) ) {
        auto tmp = jo.get_object( "countdown_action" );
        use_function fun = usage_from_object( tmp ).second;
        if( fun ) {
            def.countdown_action = fun;
        }
    }
    if( jo.has_string( "drop_action" ) ) {
        def.drop_action = usage_from_string( jo.get_string( "drop_action" ) );
    } else if( jo.has_object( "drop_action" ) ) {
        auto tmp = jo.get_object( "drop_action" );
        use_function fun = usage_from_object( tmp ).second;
        if( fun ) {
            def.drop_action = fun;
        }
    }
    jo.read( "looks_like", def.looks_like );
    if( jo.has_member( "conditional_names" ) ) {
        def.conditional_names.clear();
        for( const JsonObject curr : jo.get_array( "conditional_names" ) ) {
            conditional_name cname;
            cname.type = curr.get_enum_value<condition_type>( "type" );
            cname.condition = curr.get_string( "condition" );
            cname.name = translation( translation::plural_tag() );
            if( !curr.read( "name", cname.name ) ) {
                curr.throw_error( "name unspecified for conditional name" );
            }
            def.conditional_names.push_back( cname );
        }
    }
    load_slot_optional( def.container, jo, "container_data", src );
    load_slot_optional( def.armor, jo, "armor_data", src );
    load_slot_optional( def.pet_armor, jo, "pet_armor_data", src );
    load_slot_optional( def.book, jo, "book_data", src );
    load_slot_optional( def.gun, jo, "gun_data", src );
    load_slot_optional( def.bionic, jo, "bionic_data", src );
    assign( jo, "ammo_data", def.ammo, src == "dda" );
    load_slot_optional( def.seed, jo, "seed_data", src );
    load_slot_optional( def.artifact, jo, "artifact_data", src );
    load_slot_optional( def.brewable, jo, "brewable", src );
    load_slot_optional( def.fuel, jo, "fuel", src );
    load_slot_optional( def.relic_data, jo, "relic_data", src );
    load_slot_optional( def.milling_data, jo, "milling", src );
    // optional gunmod slot may also specify mod data
    if( jo.has_member( "gunmod_data" ) ) {
        // use the same JsonObject for the two load_slot calls to avoid
        // warnings about unvisited Json members
        JsonObject jo_gunmod = jo.get_object( "gunmod_data" );
        load_slot( def.gunmod, jo_gunmod, src );
        load_slot( def.mod, jo_gunmod, src );
    }
    if( jo.has_string( "abstract" ) ) {
        jo.read( "abstract", def.id, true );
    } else {
        jo.read( "id", def.id, true );
    }
    if( !def.src.empty() && def.src.back().first != def.id ) {
        def.src.clear();
    }
    def.src.emplace_back( def.id, mod_id( src ) );
    // snippet_category should be loaded after def.id is determined
    if( jo.has_array( "snippet_category" ) ) {
        // auto-create a category that is unlikely to already be used and put the
        // snippets in it.
        def.snippet_category = "auto:" + def.id.str();
        SNIPPET.add_snippets_from_json( def.snippet_category, jo.get_array( "snippet_category" ) );
    } else {
        def.snippet_category = jo.get_string( "snippet_category", "" );
    }
    if( jo.has_string( "abstract" ) ) {
        m_abstracts[ def.id ] = def;
    } else {
        m_templates[ def.id ] = def;
    }
}
References damage_instance::add_damage(), snippet_library::add_snippets_from_json(), JsonObject::allow_omitted_members(), itype::ammo, itype::armor, itype::artifact, assign(), itype::bionic, itype::book, itype::brewable, itype::category_force, damage_instance::clear(), itype::color, color_from_string(), conditional_name::condition, itype::conditional_names, itype::container, itype::countdown_action, itype::countdown_destroy, itype::countdown_interval, itype::damage_max_, itype::damage_min_, itype::damage_scale, itype::default_container, delete_qualities_from_json(), itype::description, itype::drop_action, DT_BASH, DT_CUT, itype::emits, JsonArray::empty(), itype::explode_in_fire, itype::explosion, extend_qualities_from_json(), itype::faults, itype::fuel, JsonObject::get_array(), JsonArray::get_array(), JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), JsonArray::get_string(), JsonObject::get_tags(), itype::gun, itype::gunmod, JsonObject::has_array(), JsonObject::has_member(), JsonArray::has_more(), JsonObject::has_object(), JsonObject::has_string(), itype::id, itype::insulation_factor, itype::integral_volume, itype::integral_weight, itype::item_tags, itype_id, load_damage_instance(), load_explosion_data(), load_slot(), load_slot_optional(), itype::looks_like, m_abstracts, m_templates, itype::m_to_hit, itype::magazine_default, itype::magazine_well, itype::magazines, itype::materials, itype::melee, itype::milling_data, itype::min_dex, itype::min_int, itype::min_per, itype::min_skills, itype::min_str, itype::mod, conditional_name::name, itype::name, JsonArray::next_string(), itype::pet_armor, itype::phase, itype::picture_id, itype::price, itype::price_post, itype::qualities, JsonObject::read(), itype::relic_data, itype::repairs_like, itype::rigid, itype::seed, set_properties_from_json(), set_qualities_from_json(), set_use_methods_from_json(), skill_id, SNIPPET, itype::snippet_category, itype::solar_efficiency, itype::src, itype::stackable_, string_id< T >::str(), string_format(), itype::sym, itype::techniques, JsonObject::throw_error(), itype::thrown_damage, conditional_name::type, usage_from_object(), usage_from_string(), itype::use_methods, itype::volume, and itype::weight.
Referenced by load_ammo(), load_armor(), load_battery(), load_bionic(), load_book(), load_comestible(), load_container(), load_engine(), load_fuel(), load_generic(), load_gun(), load_gunmod(), load_magazine(), load_pet_armor(), load_tool(), load_tool_armor(), load_toolmod(), and load_wheel().
load_battery()
void Item_factory::load_battery (const JsonObject & jo, const std::string & src)
Definition at line 2269 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.battery, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::battery, load_basic_info(), load_definition(), and load_slot().
load_bionic()
void Item_factory::load_bionic (const JsonObject & jo, const std::string & src)
Definition at line 2294 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.bionic, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::bionic, load_basic_info(), load_definition(), and load_slot().
load_book()
void Item_factory::load_book (const JsonObject & jo, const std::string & src)
Definition at line 2003 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.book, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::book, load_basic_info(), load_definition(), and load_slot().
load_comestible()
void Item_factory::load_comestible (const JsonObject & jo, const std::string & src)
Definition at line 2140 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        assign( jo, "stack_size", def.stack_size, src == "dda", 1 );
        load_slot( def.comestible, jo, src );
        load_basic_info( jo, def, src );
    }
}
References assign(), itype::comestible, load_basic_info(), load_definition(), load_slot(), and itype::stack_size.
load_container()
void Item_factory::load_container (const JsonObject & jo, const std::string & src)
Definition at line 2150 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.container, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::container, load_basic_info(), load_definition(), and load_slot().
load_definition()
bool Item_factory::load_definition (const JsonObject & jo, const std::string & src, itype & def) private
Called before creating a new template and handles inheritance via copy-from May defer instantiation of the template if depends on other objects not as-yet loaded.
Definition at line 1611 of file item_factory.cpp.
{
    assert( !frozen );
    if( !jo.has_string( "copy-from" ) ) {
        // if this is a new definition ensure we start with a clean itype
        def = itype();
        return true;
    }
    itype_id copy_from;
    jo.read( "copy-from", copy_from, true );
    auto base = m_templates.find( copy_from );
    if( base != m_templates.end() ) {
        def = base->second;
        def.looks_like = copy_from;
        def.was_loaded = true;
        return true;
    }
    auto abstract = m_abstracts.find( copy_from );
    if( abstract != m_abstracts.end() ) {
        def = abstract->second;
        if( def.looks_like.is_empty() ) {
            def.looks_like = copy_from;
        }
        def.was_loaded = true;
        return true;
    }
    deferred.emplace_back( jo.get_source_location(), src );
    jo.allow_omitted_members();
    return false;
}
References JsonObject::allow_omitted_members(), deferred, frozen, JsonObject::get_source_location(), JsonObject::has_string(), string_id< T >::is_empty(), itype::looks_like, m_abstracts, m_templates, JsonObject::read(), and itype::was_loaded.
Referenced by load_ammo(), load_armor(), load_battery(), load_bionic(), load_book(), load_comestible(), load_container(), load_engine(), load_fuel(), load_generic(), load_gun(), load_gunmod(), load_magazine(), load_pet_armor(), load_tool(), load_tool_armor(), load_toolmod(), and load_wheel().
load_engine()
void Item_factory::load_engine (const JsonObject & jo, const std::string & src)
Definition at line 1720 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.engine, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::engine, load_basic_info(), load_definition(), and load_slot().
load_fuel()
void Item_factory::load_fuel (const JsonObject & jo, const std::string & src)
Definition at line 1763 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.fuel, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::fuel, load_basic_info(), load_definition(), and load_slot().
load_generic()
void Item_factory::load_generic (const JsonObject & jo, const std::string & src)
Definition at line 2303 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_basic_info( jo, def, src );
    }
}
References load_basic_info(), and load_definition().
load_gun()
void Item_factory::load_gun (const JsonObject & jo, const std::string & src)
Definition at line 1822 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.gun, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::gun, load_basic_info(), load_definition(), and load_slot().
load_gunmod()
void Item_factory::load_gunmod (const JsonObject & jo, const std::string & src)
Definition at line 2224 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.gunmod, jo, src );
        load_slot( def.mod, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::gunmod, load_basic_info(), load_definition(), load_slot(), and itype::mod.
load_item_blacklist()
void Item_factory::load_item_blacklist (const JsonObject & json)
Definition at line 765 of file item_factory.cpp.
{
    json.read( "items", item_blacklist, true );
}
References item_blacklist, and JsonObject::read().
load_item_group() [1/3]
void Item_factory::load_item_group (const JsonArray & entries, const item_group_id & group_id, bool is_collection, int ammo_chance, int magazine_chance)
Like above, but the above loads data from several members of the object, this function assume the given array is the "entries" member of the item group.
For each element in the array, Item_factory::add_entry is called.
Assuming the input array looks like [ x, y, z ], this function loads it like the above would load this object:
{
     "subtype": "depends on is_collection parameter",
     "id": "identifier",
     "entries": [ x, y, z ]
}
Note that each entry in the array has to be a JSON object. The other function above can also load data from arrays of strings, where the strings are item or group ids.
Definition at line 2969 of file item_factory.cpp.
{
    const auto type = is_collection ? Item_group::G_COLLECTION : Item_group::G_DISTRIBUTION;
    std::unique_ptr<Item_spawn_data> &isd = m_template_groups[group_id];
    Item_group *const ig = make_group_or_throw( group_id, isd, type, ammo_chance, magazine_chance );
    for( const JsonObject subobj : entries ) {
        add_entry( *ig, subobj );
    }
}
References add_entry(), Item_group::G_COLLECTION, Item_group::G_DISTRIBUTION, m_template_groups, make_group_or_throw(), and type.
load_item_group() [2/3]
void Item_factory::load_item_group (const JsonObject & jsobj)
Callback for the init system (DynamicDataLoader), loads an item group definitions.
Parameters
jsobj The json object to load from.
Exceptions
JsonError if the json object contains invalid data.
Definition at line 2962 of file item_factory.cpp.
{
    const item_group_id group_id = item_group_id( jsobj.get_string( "id" ) );
    const std::string subtype = jsobj.get_string( "subtype", "old" );
    load_item_group( jsobj, group_id, subtype );
}
References JsonObject::get_string(), and load_item_group().
Referenced by load_item_group().
load_item_group() [3/3]
void Item_factory::load_item_group (const JsonObject & jsobj, const item_group_id & group_id, const std::string & subtype)
Load a item group from json.
It differs from the other load_item_group function as it uses the ident and subtype given as parameter and does not look up those things in the json data (the json object here does not need to have them). This is intended for inline definitions of item groups, e.g. in monster death drops: the item group there is embedded into the monster type definition.
Parameters
jsobj The json object to load from.
group_id The ident of the item that is to be loaded.
subtype The type of the item group, either "collection", "distribution" or "old" ("old" is a distribution, too).
Exceptions
JsonError if the json object contains invalid data.
Definition at line 2981 of file item_factory.cpp.
{
    std::unique_ptr<Item_spawn_data> &isd = m_template_groups[group_id];
    Item_group::Type type = Item_group::G_COLLECTION;
    if( subtype == "old" || subtype == "distribution" ) {
        type = Item_group::G_DISTRIBUTION;
    } else if( subtype != "collection" ) {
        jsobj.throw_error( "unknown item group type", "subtype" );
    }
    Item_group *ig = make_group_or_throw( group_id, isd, type, jsobj.get_int( "ammo", 0 ),
                                          jsobj.get_int( "magazine", 0 ) );
    if( subtype == "old" ) {
        for( const JsonValue entry : jsobj.get_array( "items" ) ) {
            if( entry.test_object() ) {
                JsonObject subobj = entry.get_object();
                add_entry( *ig, subobj );
            } else {
                JsonArray pair = entry.get_array();
                ig->add_item_entry( itype_id( pair.get_string( 0 ) ), pair.get_int( 1 ) );
            }
        }
        return;
    }
    if( jsobj.has_member( "entries" ) ) {
        for( const JsonObject subobj : jsobj.get_array( "entries" ) ) {
            add_entry( *ig, subobj );
        }
    }
    if( jsobj.has_member( "items" ) ) {
        for( const JsonValue entry : jsobj.get_array( "items" ) ) {
            if( entry.test_string() ) {
                ig->add_item_entry( itype_id( entry.get_string() ), 100 );
            } else if( entry.test_array() ) {
                JsonArray subitem = entry.get_array();
                ig->add_item_entry( itype_id( subitem.get_string( 0 ) ), subitem.get_int( 1 ) );
            } else {
                JsonObject subobj = entry.get_object();
                add_entry( *ig, subobj );
            }
        }
    }
    if( jsobj.has_member( "groups" ) ) {
        for( const JsonValue entry : jsobj.get_array( "groups" ) ) {
            if( entry.test_string() ) {
                ig->add_group_entry( item_group_id( entry.get_string() ), 100 );
            } else if( entry.test_array() ) {
                JsonArray subitem = entry.get_array();
                ig->add_group_entry( item_group_id( subitem.get_string( 0 ) ), subitem.get_int( 1 ) );
            } else {
                JsonObject subobj = entry.get_object();
                add_entry( *ig, subobj );
            }
        }
    }
}
References add_entry(), Item_group::add_group_entry(), Item_group::add_item_entry(), Item_group::G_COLLECTION, Item_group::G_DISTRIBUTION, JsonObject::get_array(), JsonArray::get_array(), JsonObject::get_int(), JsonArray::get_int(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_member(), itype_id, m_template_groups, make_group_or_throw(), JsonObject::throw_error(), and type.
load_magazine()
void Item_factory::load_magazine (const JsonObject & jo, const std::string & src)
Definition at line 2254 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.magazine, jo, src );
        load_basic_info( jo, def, src );
    }
}
References load_basic_info(), load_definition(), load_slot(), and itype::magazine.
load_migration()
void Item_factory::load_migration (const JsonObject & jo)
Migrations transform items loaded from legacy saves.
Definition at line 2652 of file item_factory.cpp.
{
    migration m;
    assign( jo, "replace", m.replace );
    assign( jo, "flags", m.flags );
    assign( jo, "charges", m.charges );
    assign( jo, "contents", m.contents );
    if( jo.has_string( "id" ) ) {
        jo.read( "id", m.id, true );
        migrations[ m.id ] = m;
    } else if( jo.has_array( "id" ) ) {
        std::vector<itype_id> ids;
        jo.read( "id", ids, true );
        for( const itype_id id : ids ) {
            m.id = id;
            migrations[ m.id ] = m;
        }
    } else {
        jo.throw_error( "`id` of `MIGRATION` is neither string nor array" );
    }
}
References assign(), migration::charges, migration::contents, migration::flags, JsonObject::has_array(), JsonObject::has_string(), base_camps::id, migration::id, migrations, JsonObject::read(), migration::replace, and JsonObject::throw_error().
load_pet_armor()
void Item_factory::load_pet_armor (const JsonObject & jo, const std::string & src)
Definition at line 1840 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.pet_armor, jo, src );
        load_basic_info( jo, def, src );
    }
}
References load_basic_info(), load_definition(), load_slot(), and itype::pet_armor.
load_slot()
template<typename SlotType > void Item_factory::load_slot (cata::value_ptr< SlotType > & slotptr, const JsonObject & jo, const std::string & src) private
Load the data of the slot struct.
It creates the slot object (of type SlotType) and and calls load to do the actual (type specific) loading.
Definition at line 1573 of file item_factory.cpp.
{
    if( !slotptr ) {
        slotptr = cata::make_value<SlotType>();
    }
    load( *slotptr, jo, src );
}
References load().
Referenced by load_armor(), load_basic_info(), load_battery(), load_bionic(), load_book(), load_comestible(), load_container(), load_engine(), load_fuel(), load_gun(), load_gunmod(), load_magazine(), load_pet_armor(), load_slot_optional(), load_tool(), load_tool_armor(), load_toolmod(), and load_wheel().
load_slot_optional()
template<typename SlotType > void Item_factory::load_slot_optional (cata::value_ptr< SlotType > & slotptr, const JsonObject & jo, const std::string & member, const std::string & src) private
Load item the item slot if present in json.
Checks whether the json object has a member of the given name and if so, loads the item slot from that object. If the member does not exists, nothing is done.
Definition at line 1583 of file item_factory.cpp.
{
    if( !jo.has_member( member ) ) {
        return;
    }
    JsonObject slotjo = jo.get_object( member );
    load_slot( slotptr, slotjo, src );
}
References JsonObject::get_object(), JsonObject::has_member(), load_slot(), and mapgen_defer::member.
Referenced by load_basic_info().
load_string()
bool Item_factory::load_string (std::vector< std::string > & vec, const JsonObject & obj, const std::string & name) private
Definition at line 2890 of file item_factory.cpp.
{
    bool result = false;
    std::string temp;
    if( obj.has_array( name ) ) {
        for( const std::string line : obj.get_array( name ) ) {
            result |= true;
            vec.push_back( line );
        }
    } else if( obj.has_member( name ) ) {
        result |= obj.read( name, temp );
        vec.push_back( temp );
    }
    return result;
}
References JsonObject::get_array(), JsonObject::has_array(), JsonObject::has_member(), line(), om_direction::name(), and JsonObject::read().
Referenced by add_entry().
load_sub_ref()
bool Item_factory::load_sub_ref (std::unique_ptr< Item_spawn_data > & ptr, const JsonObject & obj, const std::string & name, const Item_group & parent) private
Helper function for Item_group loading.
If obj contains an array or string titled name + "-item" or name + "-group", this resets ptr and adds the item(s) or group(s) to it.
Parameters
ptr Data we operate on, results are stored here
obj Json object being searched
name Name of item or group we are searching for
parent The item group that obj is in. Used so that the result's magazine and ammo probabilities can be inherited.
Returns
Whether anything was loaded.
Definition at line 2829 of file item_factory.cpp.
{
    const std::string iname( name + "-item" );
    const std::string gname( name + "-group" );
    std::vector< std::pair<const std::string, bool> >
    entries; // pair.second is true for groups, false for items
    const int prob = 100;
    auto get_array = [&obj, &name, &entries]( const std::string & arr_name, const bool isgroup ) {
        if( !obj.has_array( arr_name ) ) {
            return;
        } else if( name != "contents" ) {
            obj.throw_error( string_format( "You can't use an array for '%s'", arr_name ) );
        }
        for( const std::string line : obj.get_array( arr_name ) ) {
            entries.emplace_back( line, isgroup );
        }
    };
    get_array( iname, false );
    get_array( gname, true );
    if( obj.has_member( name ) ) {
        obj.throw_error( string_format( "This has been a TODO: since 2014.  Use '%s' and/or '%s' instead.",
                                        iname, gname ) );
        // TODO: !
        return false;
    }
    if( obj.has_string( iname ) ) {
        entries.push_back( std::make_pair( obj.get_string( iname ), false ) );
    }
    if( obj.has_string( gname ) ) {
        entries.push_back( std::make_pair( obj.get_string( gname ), true ) );
    }
    if( entries.size() > 1 && name != "contents" ) {
        obj.throw_error( string_format( "You can only use one of '%s' and '%s'", iname, gname ) );
        return false;
    } else if( entries.size() == 1 ) {
        const auto type = entries.front().second ? Single_item_creator::Type::S_ITEM_GROUP :
                          Single_item_creator::Type::S_ITEM;
        Single_item_creator *result = new Single_item_creator( entries.front().first, type, prob );
        result->inherit_ammo_mag_chances( parent.with_ammo, parent.with_magazine );
        ptr.reset( result );
        return true;
    } else if( entries.empty() ) {
        return false;
    }
    Item_group *result = new Item_group( Item_group::Type::G_COLLECTION, prob, parent.with_ammo,
                                         parent.with_magazine );
    ptr.reset( result );
    for( const auto &elem : entries ) {
        if( elem.second ) {
            result->add_group_entry( item_group_id( elem.first ), prob );
        } else {
            result->add_item_entry( itype_id( elem.first ), prob );
        }
    }
    return true;
}
References JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), itype_id, line(), om_direction::name(), ptr(), string_format(), JsonObject::throw_error(), type, Item_group::with_ammo, and Item_group::with_magazine.
Referenced by add_entry().
load_tool()
void Item_factory::load_tool (const JsonObject & jo, const std::string & src)
Definition at line 1918 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.tool, jo, src );
        load_basic_info( jo, def, src );
    }
}
References load_basic_info(), load_definition(), load_slot(), and itype::tool.
load_tool_armor()
void Item_factory::load_tool_armor (const JsonObject & jo, const std::string & src)
Definition at line 1974 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.tool, jo, src );
        load_slot( def.armor, jo, src );
        load_basic_info( jo, def, src );
    }
}
References itype::armor, load_basic_info(), load_definition(), load_slot(), and itype::tool.
load_toolmod()
void Item_factory::load_toolmod (const JsonObject & jo, const std::string & src)
Definition at line 1965 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.mod, jo, src );
        load_basic_info( jo, def, src );
    }
}
References load_basic_info(), load_definition(), load_slot(), and itype::mod.
load_wheel()
void Item_factory::load_wheel (const JsonObject & jo, const std::string & src)
Definition at line 1735 of file item_factory.cpp.
{
    itype def;
    if( load_definition( jo, src, def ) ) {
        load_slot( def.wheel, jo, src );
        load_basic_info( jo, def, src );
    }
}
References load_basic_info(), load_definition(), load_slot(), and itype::wheel.
migrate_id()
itype_id Item_factory::migrate_id (const itype_id & id)
Applies any migration of the item id.
Definition at line 2675 of file item_factory.cpp.
{
    auto iter = migrations.find( id );
    return iter != migrations.end() ? iter->second.replace : id;
}
References base_camps::id, and migrations.
migrate_item()
void Item_factory::migrate_item (const itype_id & id, item & obj)
Applies any migrations to an instance of an item.
Parameters
id the original id (before any replacement)
obj The instance
See also
Item_factory::migrate_id
Definition at line 2681 of file item_factory.cpp.
{
    auto iter = migrations.find( id );
    if( iter != migrations.end() ) {
        for( const std::string &f : iter->second.flags ) {
            obj.set_flag( f );
        }
        if( iter->second.charges > 0 ) {
            obj.charges = iter->second.charges;
        }
        obj.contents.migrate_item( obj, iter->second.contents );
        // check contents of migrated containers do not exceed capacity
        if( obj.is_container() && !obj.contents.empty() ) {
            item &child = obj.contents.back();
            const int capacity = child.charges_per_volume( obj.get_container_capacity() );
            child.charges = std::min( child.charges, capacity );
        }
    }
}
References item_contents::back(), item::charges, item::charges_per_volume(), item::contents, item_contents::empty(), item::get_container_capacity(), item::is_container(), item_contents::migrate_item(), migrations, and item::set_flag().
npc_implied_flags()
void Item_factory::npc_implied_flags (itype & item_template) static private
Definition at line 2369 of file item_factory.cpp.
{
    if( item_template.use_methods.count( "explosion" ) ) {
        item_template.item_tags.insert( "DANGEROUS" );
    }
    if( item_template.has_flag( "DANGEROUS" ) ) {
        item_template.item_tags.insert( "NPC_THROW_NOW" );
    }
    if( item_template.has_flag( "BOMB" ) ) {
        item_template.item_tags.insert( "NPC_ACTIVATE" );
    }
    if( item_template.has_flag( "NPC_THROW_NOW" ) ) {
        item_template.item_tags.insert( "NPC_THROWN" );
    }
    if( item_template.has_flag( "NPC_ACTIVATE" ) ||
        item_template.has_flag( "NPC_THROWN" ) ) {
        item_template.item_tags.insert( "NPC_ALT_ATTACK" );
    }
    if( item_template.has_flag( "DANGEROUS" ) ||
        item_template.has_flag( "PSEUDO" ) ) {
        item_template.item_tags.insert( "TRADER_AVOID" );
    }
}
References itype::has_flag(), itype::item_tags, and itype::use_methods.
Referenced by finalize_pre().
register_cached_uses()
void Item_factory::register_cached_uses (const itype & obj) private
Registers the item as having repair actions (if it has any).
Definition at line 566 of file item_factory.cpp.
{
    for( auto &e : obj.use_methods ) {
        // can this item function as a repair tool?
        if( repair_actions.count( e.first ) ) {
            repair_tools.insert( obj.id );
        }
        // can this item be used to repair complex firearms?
        if( e.first == "GUN_REPAIR" ) {
            gun_tools.insert( obj.id );
        }
    }
}
References gun_tools, itype::id, repair_actions, repair_tools, and itype::use_methods.
Referenced by finalize().
reset()
void Item_factory::reset ()
Reset the item factory.
All item type definitions and item groups are erased.
Definition at line 2755 of file item_factory.cpp.
{
    clear();
    init();
}
References clear(), and init().
set_allergy_flags()
void Item_factory::set_allergy_flags (itype & item_template) static private
Definition at line 2313 of file item_factory.cpp.
{
    using material_allergy_pair = std::pair<material_id, std::string>;
    static const std::vector<material_allergy_pair> all_pairs = {{
            // First allergens:
            // An item is an allergen even if it has trace amounts of allergenic material
            std::make_pair( material_id( "hflesh" ), "CANNIBALISM" ),
            std::make_pair( material_id( "hflesh" ), "ALLERGEN_MEAT" ),
            std::make_pair( material_id( "iflesh" ), "ALLERGEN_MEAT" ),
            std::make_pair( material_id( "flesh" ), "ALLERGEN_MEAT" ),
            std::make_pair( material_id( "wheat" ), "ALLERGEN_WHEAT" ),
            std::make_pair( material_id( "fruit" ), "ALLERGEN_FRUIT" ),
            std::make_pair( material_id( "veggy" ), "ALLERGEN_VEGGY" ),
            std::make_pair( material_id( "bean" ), "ALLERGEN_VEGGY" ),
            std::make_pair( material_id( "tomato" ), "ALLERGEN_VEGGY" ),
            std::make_pair( material_id( "garlic" ), "ALLERGEN_VEGGY" ),
            std::make_pair( material_id( "nut" ), "ALLERGEN_NUT" ),
            std::make_pair( material_id( "mushroom" ), "ALLERGEN_VEGGY" ),
            std::make_pair( material_id( "milk" ), "ALLERGEN_MILK" ),
            std::make_pair( material_id( "egg" ), "ALLERGEN_EGG" ),
            std::make_pair( material_id( "junk" ), "ALLERGEN_JUNK" ),
            // Not food, but we can keep it here
            std::make_pair( material_id( "wool" ), "ALLERGEN_WOOL" ),
            // Now "made of". Those flags should not be passed
            std::make_pair( material_id( "flesh" ), "CARNIVORE_OK" ),
            std::make_pair( material_id( "hflesh" ), "CARNIVORE_OK" ),
            std::make_pair( material_id( "iflesh" ), "CARNIVORE_OK" ),
            std::make_pair( material_id( "milk" ), "CARNIVORE_OK" ),
            std::make_pair( material_id( "egg" ), "CARNIVORE_OK" ),
            std::make_pair( material_id( "honey" ), "URSINE_HONEY" ),
        }
    };
    const auto &mats = item_template.materials;
    for( const auto &pr : all_pairs ) {
        if( std::find( mats.begin(), mats.end(), std::get<0>( pr ) ) != mats.end() ) {
            item_template.item_tags.insert( std::get<1>( pr ) );
        }
    }
}
References detail::find(), itype::item_tags, and itype::materials.
Referenced by finalize_pre().
set_properties_from_json()
void Item_factory::set_properties_from_json (const JsonObject & jo, const std::string & member, itype & def) private
Definition at line 2739 of file item_factory.cpp.
{
    if( jo.has_array( member ) ) {
        for( JsonArray curr : jo.get_array( member ) ) {
            const auto prop = std::pair<std::string, std::string>( curr.get_string( 0 ), curr.get_string( 1 ) );
            if( def.properties.count( prop.first ) > 0 ) {
                curr.throw_error( "Duplicated property", 0 );
            }
            def.properties.insert( prop );
        }
    } else {
        jo.throw_error( "Properties list is not an array", member );
    }
}
References JsonObject::get_array(), JsonObject::has_array(), mapgen_defer::member, itype::properties, and JsonObject::throw_error().
Referenced by load_basic_info().
set_qualities_from_json()
void Item_factory::set_qualities_from_json (const JsonObject & jo, const std::string & member, itype & def) private
Definition at line 2703 of file item_factory.cpp.
{
    if( jo.has_array( member ) ) {
        for( JsonArray curr : jo.get_array( member ) ) {
            const auto quali = std::pair<quality_id, int>( quality_id( curr.get_string( 0 ) ),
                               curr.get_int( 1 ) );
            if( def.qualities.count( quali.first ) > 0 ) {
                curr.throw_error( "Duplicated quality", 0 );
            }
            def.qualities.insert( quali );
        }
    } else {
        jo.throw_error( "Qualities list is not an array", member );
    }
}
References JsonObject::get_array(), JsonObject::has_array(), mapgen_defer::member, itype::qualities, and JsonObject::throw_error().
Referenced by load_basic_info().
set_use_methods_from_json()
void Item_factory::set_use_methods_from_json (const JsonObject & jo, const std::string & member, std::map< std::string, use_function > & use_methods) private
Definition at line 3041 of file item_factory.cpp.
{
    if( !jo.has_member( member ) ) {
        return;
    }
    use_methods.clear();
    if( jo.has_array( member ) ) {
        for( const JsonValue entry : jo.get_array( member ) ) {
            if( entry.test_string() ) {
                std::string type = entry.get_string();
                emplace_usage( use_methods, type );
            } else if( entry.test_object() ) {
                auto obj = entry.get_object();
                std::pair<std::string, use_function> fun = usage_from_object( obj );
                if( fun.second ) {
                    use_methods.insert( fun );
                }
            } else {
                entry.throw_error( "array element is neither string nor object." );
            }
        }
    } else {
        if( jo.has_string( member ) ) {
            std::string type = jo.get_string( member );
            emplace_usage( use_methods, type );
        } else if( jo.has_object( member ) ) {
            auto obj = jo.get_object( member );
            std::pair<std::string, use_function> fun = usage_from_object( obj );
            if( fun.second ) {
                use_methods.insert( fun );
            }
        } else {
            jo.throw_error( "member 'use_action' is neither string nor object." );
        }
    }
}
References emplace_usage(), JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), mapgen_defer::member, JsonObject::throw_error(), type, and usage_from_object().
Referenced by load_basic_info().
subtype_replacement()
std::list< itype_id > Item_factory::subtype_replacement (const itype_id & base) const
Definition at line 3320 of file item_factory.cpp.
{
    std::list<itype_id> ret;
    ret.push_back( base );
    const auto replacements = tool_subtypes.find( base );
    if( replacements != tool_subtypes.end() ) {
        ret.insert( ret.end(), replacements->second.begin(), replacements->second.end() );
    }
    return ret;
}
References cata::hash64_detail::ret, and tool_subtypes.
usage_from_object()
std::pair< std::string, use_function > Item_factory::usage_from_object (const JsonObject & obj) private
Definition at line 3091 of file item_factory.cpp.
{
    auto type = obj.get_string( "type" );
    if( type == "repair_item" ) {
        type = obj.get_string( "item_action_type" );
        if( !has_iuse( type ) ) {
            add_actor( std::make_unique<repair_item_actor>( type ) );
            repair_actions.insert( type );
        }
    }
    use_function method = usage_from_string( type );
    if( !method.get_actor_ptr() ) {
        return std::make_pair( type, use_function() );
    }
    method.get_actor_ptr()->load( obj );
    return std::make_pair( type, method );
}
References add_actor(), use_function::get_actor_ptr(), JsonObject::get_string(), has_iuse(), iuse_actor::load(), repair_actions, type, and usage_from_string().
Referenced by load_basic_info(), and set_use_methods_from_json().
usage_from_string()
use_function Item_factory::usage_from_string (const std::string & type) const private
Definition at line 3113 of file item_factory.cpp.
{
    auto func = iuse_function_list.find( type );
    if( func != iuse_function_list.end() ) {
        return func->second;
    }
    // Otherwise, return a hardcoded function we know exists (hopefully)
    debugmsg( "Received unrecognized iuse function %s, using iuse::none instead", type.c_str() );
    return use_function();
}
References debugmsg, iuse_function_list, and type.
Referenced by emplace_usage(), load_basic_info(), and usage_from_object().
Member Data Documentation
frozen
bool Item_factory::frozen = false private
Set at finalization and prevents alterations to the static item templates.
Definition at line 242 of file item_factory.h.
Referenced by add_item_type(), all(), clear(), finalize(), find(), find_template(), and load_definition().
gun_tools
std::set<itype_id> Item_factory::gun_tools private
Definition at line 377 of file item_factory.h.
Referenced by clear(), and register_cached_uses().
itype_id
friend Item_factory::itype_id private
Definition at line 62 of file item_factory.h.
Referenced by create_artifact_id(), load(), load_basic_info(), load_item_group(), and load_sub_ref().
iuse_function_list
std::map<item_action_id, use_function> Item_factory::iuse_function_list private
Definition at line 358 of file item_factory.h.
Referenced by add_actor(), add_iuse(), clear(), has_iuse(), and usage_from_string().
m_abstracts
std::map<itype_id, itype> Item_factory::m_abstracts private
Definition at line 244 of file item_factory.h.
Referenced by clear(), load_basic_info(), and load_definition().
m_runtimes
std::map<itype_id, std::unique_ptr<itype> > Item_factory::m_runtimes mutable private
Definition at line 248 of file item_factory.h.
Referenced by add_item_type(), all(), clear(), create_artifact_id(), finalize(), find(), find_template(), get_runtime_types(), and has_template().
m_template_groups
GroupMap Item_factory::m_template_groups private
Definition at line 251 of file item_factory.h.
Referenced by add_item_to_group(), check_definitions(), clear(), finalize_item_blacklist(), get_all_group_names(), get_group(), init(), and load_item_group().
m_templates
std::unordered_map<itype_id, itype> Item_factory::m_templates private
Definition at line 246 of file item_factory.h.
Referenced by all(), check_ammo_type(), check_definitions(), clear(), finalize(), finalize_item_blacklist(), find(), find_template(), has_template(), load_basic_info(), and load_definition().
migrated_ammo
std::unordered_map<itype_id, ammotype> Item_factory::migrated_ammo private
Definition at line 253 of file item_factory.h.
Referenced by clear(), finalize_item_blacklist(), and finalize_pre().
migrated_magazines
std::unordered_map<itype_id, itype_id> Item_factory::migrated_magazines private
Definition at line 254 of file item_factory.h.
Referenced by clear(), finalize_item_blacklist(), and finalize_pre().
migrations
std::map<itype_id, migration> Item_factory::migrations private
Definition at line 365 of file item_factory.h.
Referenced by check_definitions(), clear(), finalize_item_blacklist(), load_migration(), migrate_id(), and migrate_item().
repair_actions
std::set<std::string> Item_factory::repair_actions private
Definition at line 379 of file item_factory.h.
Referenced by clear(), register_cached_uses(), and usage_from_object().
repair_tools
std::set<itype_id> Item_factory::repair_tools private
Definition at line 374 of file item_factory.h.
Referenced by clear(), and register_cached_uses().
tool_subtypes
std::map<itype_id, std::set<itype_id> > Item_factory::tool_subtypes private
Contains the tool subtype mappings for crafting (i.e.
mess kit is a hotplate etc.). This is should be obsoleted when requirement_data allows AND/OR nesting.
Definition at line 371 of file item_factory.h.
Referenced by clear(), finalize_pre(), and subtype_replacement().
The documentation for this class was generated from the following files:
src/item_factory.h
src/item_factory.cpp