Cataclysm BN: om_noise::om_noise_layer_forest Class Reference
om_noise::om_noise_layer_forest Class Reference
#include <overmap_noise.h>
Public Member Functions
om_noise_layer_forest (const point_abs_omt &global_base_point, unsigned seed)
float noise_at (const point_om_omt &local_omt_pos) const override
Noise value at the provided overmap terrain location.
Public Member Functions inherited from om_noise::om_noise_layer
virtual ~om_noise_layer ()=default
Additional Inherited Members
Protected Member Functions inherited from om_noise::om_noise_layer
om_noise_layer (const point_abs_omt &global_base_point, const unsigned seed)
Providing the global base point of the overmap and a common seed across overmaps will ensure that the noise is continuous across overmap boundaries.
point_abs_omt global_omt_pos (const point_om_omt &local_omt_pos) const
float get_seed () const
Detailed Description
Definition at line 51 of file overmap_noise.h.
Constructor & Destructor Documentation
om_noise_layer_forest()
om_noise::om_noise_layer_forest::om_noise_layer_forest (const point_abs_omt & global_base_point, unsigned seed) inline
Definition at line 54 of file overmap_noise.h.
            : om_noise_layer( global_base_point, seed ) {
        }
Member Function Documentation
noise_at()
float om_noise::om_noise_layer_forest::noise_at (const point_om_omt & omt_local) const override virtual
Noise value at the provided overmap terrain location.
Parameters
omt_local point location in overmap terrain local coordinates.
Implements om_noise::om_noise_layer.
Definition at line 10 of file overmap_noise.cpp.
{
    const point_abs_omt p = global_omt_pos( local_omt_pos );
    float r = scaled_octave_noise_3d( 8, 0.5, 0.03, 0, 1, p.x(), p.y(), get_seed() );
    r = std::pow( r, 2.0f );
    float d = scaled_octave_noise_3d( 12, 0.5, 0.07, 0, 1, p.x(), p.y(), get_seed() );
    d = std::pow( d, 3.0f );
    return std::max( 0.0f, r - d * 0.5f );
}
References om_noise::om_noise_layer::get_seed(), om_noise::om_noise_layer::global_omt_pos(), scaled_octave_noise_3d(), coords::coord_point< Point, Origin, Scale >::x(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by overmap::place_forests().
The documentation for this class was generated from the following files:
src/overmap_noise.h
src/overmap_noise.cpp