Cataclysm BN: JsonObject::const_iterator Class Reference
JsonObject::const_iterator Class Reference
#include <json.h>
Public Member Functions
const_iterator (const JsonObject &object, const decltype(iter_) &iter)
const_iterator & operator++ ()
JsonMember operator* () const
Private Attributes
const JsonObject & object_
decltype(JsonObject::positions) ::const_iterator iter_
Friends
bool operator== (const const_iterator &lhs, const const_iterator &rhs)
bool operator!= (const const_iterator &lhs, const const_iterator &rhs)
Detailed Description
Definition at line 1271 of file json.h.
Constructor & Destructor Documentation
const_iterator()
JsonObject::const_iterator::const_iterator (const JsonObject & object, const decltype(iter_) & iter) inline
Definition at line 1278 of file json.h.
                                                                                  : object_( object ),
            iter_( iter ) { }
Member Function Documentation
operator*()
JsonMember JsonObject::const_iterator::operator* () const inline
Definition at line 1285 of file json.h.
{
            object_.mark_visited( iter_->first );
            return JsonMember( iter_->first, JsonValue( *object_.jsin, iter_->second ) );
        }
References iter_, JsonObject::jsin, JsonObject::mark_visited(), and object_.
operator++()
const_iterator & JsonObject::const_iterator::operator++ () inline
Definition at line 1281 of file json.h.
{
            iter_++;
            return *this;
        }
References iter_.
Friends And Related Function Documentation
operator!=
bool operator!= (const const_iterator & lhs, const const_iterator & rhs) friend
Definition at line 1293 of file json.h.
{
            return !operator==( lhs, rhs );
        }
operator==
bool operator== (const const_iterator & lhs, const const_iterator & rhs) friend
Definition at line 1290 of file json.h.
{
            return lhs.iter_ == rhs.iter_;
        }
Member Data Documentation
iter_
decltype(JsonObject::positions) ::const_iterator JsonObject::const_iterator::iter_ private
Definition at line 1275 of file json.h.
Referenced by operator*(), and operator++().
object_
const JsonObject& JsonObject::const_iterator::object_ private
Definition at line 1274 of file json.h.
Referenced by operator*().
The documentation for this class was generated from the following file:
src/json.h