Cataclysm BN: dependency_node Class Reference
dependency_node Class Reference
#include <dependency_tree.h>
Public Member Functions
dependency_node ()
dependency_node (mod_id _key)
void add_parent (dependency_node *parent)
void add_child (dependency_node *child)
void add_conflict (const dependency_node *conflict)
bool is_available () const
bool has_errors () const
std::map< node_error_type, std::vector< std::string > > errors ()
std::string s_errors ()
std::vector< mod_id > get_dependencies_as_strings () const
std::vector< dependency_node * > get_dependencies_as_nodes () const
std::vector< mod_id > get_dependents_as_strings () const
std::vector< dependency_node * > get_dependents_as_nodes () const
void inherit_errors ()
Public Attributes
std::vector< dependency_node * > parents
std::vector< dependency_node * > children
std::vector< const dependency_node * > conflicts
std::map< node_error_type, std::vector< std::string > > all_errors
mod_id key
bool availability
int index
int lowlink
bool on_stack
Detailed Description
Definition at line 19 of file dependency_tree.h.
Constructor & Destructor Documentation
dependency_node() [1/2]
dependency_node::dependency_node ()
Definition at line 20 of file dependency_tree.cpp.
                                : index( -1 ), lowlink( -1 ), on_stack( false )
{
    availability = true;
}
References availability.
dependency_node() [2/2]
dependency_node::dependency_node (mod_id _key)
Definition at line 25 of file dependency_tree.cpp.
                                             : index( -1 ), lowlink( -1 ), on_stack( false )
{
    key = _key;
    availability = true;
}
References availability, and key.
Member Function Documentation
add_child()
void dependency_node::add_child (dependency_node * child)
Definition at line 36 of file dependency_tree.cpp.
{
    children.push_back( child );
}
References children.
Referenced by dependency_tree::build_connections().
add_conflict()
void dependency_node::add_conflict (const dependency_node * conflict)
Definition at line 41 of file dependency_tree.cpp.
{
    auto it = std::find( conflicts.begin(), conflicts.end(), conflict );
    if( it == conflicts.end() ) {
        conflicts.push_back( conflict );
    }
}
References conflicts, and detail::find().
Referenced by dependency_tree::build_connections().
add_parent()
void dependency_node::add_parent (dependency_node * parent)
Definition at line 31 of file dependency_tree.cpp.
{
    parents.push_back( parent );
}
References parents.
Referenced by dependency_tree::build_connections().
errors()
std::map< node_error_type, std::vector< std::string > > dependency_node::errors ()
Definition at line 54 of file dependency_tree.cpp.
{
    return all_errors;
}
References all_errors.
get_dependencies_as_nodes()
std::vector< dependency_node * > dependency_node::get_dependencies_as_nodes () const
Definition at line 142 of file dependency_tree.cpp.
{
    std::vector<dependency_node *> dependencies;
    std::vector<dependency_node *> ret;
    std::set<mod_id> found;
    std::stack<dependency_node *> nodes_to_check;
    for( auto &elem : parents ) {
        nodes_to_check.push( elem );
    }
    found.insert( key );
    while( !nodes_to_check.empty() ) {
        dependency_node *check = nodes_to_check.top();
        nodes_to_check.pop();
        // make sure that the one we are checking is not THIS one
        if( found.find( check->key ) != found.end() ) {
            continue; // just keep going, we aren't really caring about availability right now
        }
        // add check to dependencies
        dependencies.push_back( check );
        // add parents to check list
        if( !check->parents.empty() ) {
            for( auto &elem : check->parents ) {
                nodes_to_check.push( elem );
            }
        }
        found.insert( check->key );
    }
    // sort from the back!
    for( std::vector<dependency_node *>::reverse_iterator it =
             dependencies.rbegin();
         it != dependencies.rend(); ++it ) {
        if( std::find( ret.begin(), ret.end(), *it ) == ret.end() ) {
            ret.push_back( *it );
        }
    }
    return ret;
}
References detail::check(), detail::find(), key, parents, and cata::hash64_detail::ret.
Referenced by get_dependencies_as_strings().
get_dependencies_as_strings()
std::vector< mod_id > dependency_node::get_dependencies_as_strings () const
Definition at line 126 of file dependency_tree.cpp.
{
    std::vector<mod_id> ret;
    std::vector<dependency_node *> as_nodes = get_dependencies_as_nodes();
    ret.reserve( as_nodes.size() );
    for( auto &as_node : as_nodes ) {
        ret.push_back( ( as_node )->key );
    }
    // returns dependencies in a guaranteed valid order
    return ret;
}
References get_dependencies_as_nodes(), key, and cata::hash64_detail::ret.
get_dependents_as_nodes()
std::vector< dependency_node * > dependency_node::get_dependents_as_nodes () const
Definition at line 203 of file dependency_tree.cpp.
{
    std::vector<dependency_node *> dependents;
    std::vector<dependency_node *> ret;
    std::set<mod_id> found;
    std::stack<dependency_node *> nodes_to_check;
    for( auto &elem : children ) {
        nodes_to_check.push( elem );
    }
    found.insert( key );
    while( !nodes_to_check.empty() ) {
        dependency_node *check = nodes_to_check.top();
        nodes_to_check.pop();
        if( found.find( check->key ) != found.end() ) {
            // skip it because we recursed for some reason
            continue;
        }
        dependents.push_back( check );
        if( !check->children.empty() ) {
            for( auto &elem : check->children ) {
                nodes_to_check.push( elem );
            }
        }
        found.insert( check->key );
    }
    // sort from front, keeping only one copy of the node
    for( auto &dependent : dependents ) {
        if( std::find( ret.begin(), ret.end(), dependent ) == ret.end() ) {
            ret.push_back( dependent );
        }
    }
    return ret;
}
References detail::check(), children, detail::find(), key, and cata::hash64_detail::ret.
Referenced by get_dependents_as_strings().
get_dependents_as_strings()
std::vector< mod_id > dependency_node::get_dependents_as_strings () const
Definition at line 187 of file dependency_tree.cpp.
{
    std::vector<mod_id> ret;
    std::vector<dependency_node *> as_nodes = get_dependents_as_nodes();
    ret.reserve( as_nodes.size() );
    for( auto &as_node : as_nodes ) {
        ret.push_back( ( as_node )->key );
    }
    // returns dependencies in a guaranteed valid order
    return ret;
}
References get_dependents_as_nodes(), key, and cata::hash64_detail::ret.
has_errors()
bool dependency_node::has_errors () const
Definition at line 72 of file dependency_tree.cpp.
{
    bool ret = false;
    for( const auto &elem : all_errors ) {
        if( !elem.second.empty() ) {
            ret = true;
            break;
        }
    }
    return ret;
}
References all_errors, and cata::hash64_detail::ret.
Referenced by mod_ui::try_add().
inherit_errors()
void dependency_node::inherit_errors ()
Definition at line 84 of file dependency_tree.cpp.
{
    std::stack<dependency_node * > nodes_to_check;
    std::set<mod_id> nodes_visited;
    for( auto &elem : parents ) {
        nodes_to_check.push( elem );
    }
    nodes_visited.insert( key );
    while( !nodes_to_check.empty() ) {
        dependency_node *check = nodes_to_check.top();
        nodes_to_check.pop();
        // add check errors
        if( !check->errors().empty() ) {
            std::map<node_error_type, std::vector<std::string > > cerrors = check->errors();
            for( auto &cerror : cerrors ) {
                std::vector<std::string> node_errors = cerror.second;
                node_error_type error_type = cerror.first;
                std::vector<std::string> cur_errors = all_errors[error_type];
                for( auto &node_error : node_errors ) {
                    if( std::find( cur_errors.begin(), cur_errors.end(), node_error ) ==
                        cur_errors.end() ) {
                        all_errors[cerror.first].push_back( node_error );
                    }
                }
            }
        }
        if( nodes_visited.find( check->key ) != nodes_visited.end() ) {
            continue;
        }
        // add check parents, if exist, to stack
        if( !check->parents.empty() ) {
            for( auto &elem : check->parents ) {
                nodes_to_check.push( elem );
            }
        }
        nodes_visited.insert( check->key );
    }
}
References all_errors, detail::check(), detail::find(), key, and parents.
is_available()
bool dependency_node::is_available () const
Definition at line 49 of file dependency_tree.cpp.
{
    return all_errors.empty();
}
References all_errors.
s_errors()
std::string dependency_node::s_errors ()
Definition at line 59 of file dependency_tree.cpp.
{
    std::string ret;
    for( auto &elem : all_errors ) {
        if( !ret.empty() ) {
            ret += "\n";
        }
        ret += _( error_keyvals[static_cast<size_t>( elem.first )] );
        ret += enumerate_as_string( elem.second, enumeration_conjunction::none );
    }
    return ret;
}
References _, all_errors, enumerate_as_string(), error_keyvals, none, and cata::hash64_detail::ret.
Referenced by init::check_mods_for_errors(), and mod_ui::try_add().
Member Data Documentation
all_errors
std::map<node_error_type, std::vector<std::string> > dependency_node::all_errors
Definition at line 25 of file dependency_tree.h.
Referenced by dependency_tree::build_connections(), dependency_tree::check_for_conflicting_dependencies(), errors(), has_errors(), inherit_errors(), is_available(), and s_errors().
availability
bool dependency_node::availability
Definition at line 27 of file dependency_tree.h.
Referenced by dependency_node().
children
std::vector<dependency_node *> dependency_node::children
Definition at line 23 of file dependency_tree.h.
Referenced by add_child(), and get_dependents_as_nodes().
conflicts
std::vector<const dependency_node *> dependency_node::conflicts
Definition at line 24 of file dependency_tree.h.
Referenced by add_conflict(), and dependency_tree::check_for_conflicting_dependencies().
index
int dependency_node::index
Definition at line 30 of file dependency_tree.h.
Referenced by dependency_tree::strong_connect().
key
mod_id dependency_node::key
Definition at line 26 of file dependency_tree.h.
Referenced by dependency_tree::check_for_conflicting_dependencies(), dependency_node(), get_dependencies_as_nodes(), get_dependencies_as_strings(), get_dependents_as_nodes(), get_dependents_as_strings(), inherit_errors(), and dependency_tree::strong_connect().
lowlink
int dependency_node::lowlink
Definition at line 31 of file dependency_tree.h.
Referenced by dependency_tree::strong_connect().
on_stack
bool dependency_node::on_stack
Definition at line 32 of file dependency_tree.h.
Referenced by dependency_tree::strong_connect().
parents
std::vector<dependency_node *> dependency_node::parents
Definition at line 22 of file dependency_tree.h.
Referenced by add_parent(), get_dependencies_as_nodes(), inherit_errors(), and dependency_tree::strong_connect().
The documentation for this class was generated from the following files:
src/dependency_tree.h
src/dependency_tree.cpp