Cataclysm BN: zone_manager Class Reference
zone_manager Class Reference
#include <clzones.h>
Public Types
using ref_zone_data = std::reference_wrapper< zone_data >
using ref_const_zone_data = std::reference_wrapper< const zone_data >
Public Member Functions
void add (const std::string &name, const zone_type_id &type, const faction_id &faction, bool invert, bool enabled, const tripoint &start, const tripoint &end, shared_ptr_fast< zone_options > options=nullptr)
const zone_data * get_zone_at (const tripoint &where, const zone_type_id &type) const
void create_vehicle_loot_zone (class vehicle &vehicle, const point &mount_point, zone_data &new_zone)
bool remove (zone_data &zone)
unsigned int size () const
const std::map< zone_type_id, zone_type > & get_types () const
std::string get_name_from_type (const zone_type_id &type) const
bool has_type (const zone_type_id &type) const
bool has_defined (const zone_type_id &type, const faction_id &fac=your_fac) const
void cache_data ()
void cache_vzones ()
bool has (const zone_type_id &type, const tripoint &where, const faction_id &fac=your_fac) const
bool has_near (const zone_type_id &type, const tripoint &where, int range=MAX_DISTANCE, const faction_id &fac=your_fac) const
bool has_loot_dest_near (const tripoint &where) const
bool custom_loot_has (const tripoint &where, const item *it) const
std::unordered_set< tripoint > get_near (const zone_type_id &type, const tripoint &where, int range=MAX_DISTANCE, const item *it=nullptr, const faction_id &fac=your_fac) const
cata::optional< tripoint > get_nearest (const zone_type_id &type, const tripoint &where, int range=MAX_DISTANCE, const faction_id &fac=your_fac) const
zone_type_id get_near_zone_type_for_item (const item &it, const tripoint &where, int range=MAX_DISTANCE) const
std::vector< zone_data > get_zones (const zone_type_id &type, const tripoint &where, const faction_id &fac=your_fac) const
const zone_data * get_zone_at (const tripoint &where) const
const zone_data * get_bottom_zone (const tripoint &where, const faction_id &fac=your_fac) const
cata::optional< std::string > query_name (const std::string &default_name="") const
cata::optional< zone_type_id > query_type () const
void swap (zone_data &a, zone_data &b)
void rotate_zones (map &target_map, int turns)
std::unordered_set< tripoint > get_point_set_loot (const tripoint &where, int radius, const faction_id &fac=your_fac) const
std::unordered_set< tripoint > get_point_set_loot (const tripoint &where, int radius, bool npc_search, const faction_id &fac=your_fac) const
std::vector< ref_zone_data > get_zones (const faction_id &fac=your_fac)
std::vector< ref_const_zone_data > get_zones (const faction_id &fac=your_fac) const
bool save_zones ()
void load_zones ()
void zone_edited (zone_data &zone)
void revert_vzones ()
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Static Public Member Functions
static zone_manager & get_manager ()
static void reset_manager ()
Private Member Functions
std::unordered_set< tripoint > get_point_set (const zone_type_id &type, const faction_id &fac=your_fac) const
std::unordered_set< tripoint > get_vzone_set (const zone_type_id &type, const faction_id &fac=your_fac) const
zone_manager ()
~zone_manager ()=default
zone_manager (zone_manager &&)=default
zone_manager (const zone_manager &)=default
zone_manager & operator= (zone_manager &&)=default
zone_manager & operator= (const zone_manager &)=default
Private Attributes
std::vector< zone_data > zones
std::vector< zone_data * > added_vzones
std::vector< std::pair< zone_data, zone_data * > > changed_vzones
std::vector< zone_data > removed_vzones
std::map< zone_type_id, zone_type > types
std::unordered_map< std::string, std::unordered_set< tripoint > > area_cache
std::unordered_map< std::string, std::unordered_set< tripoint > > vzone_cache
std::unordered_map< tripoint, int > num_processed
Static Private Attributes
static const int MAX_DISTANCE = 10
Detailed Description
Definition at line 339 of file clzones.h.
Member Typedef Documentation
ref_const_zone_data
using zone_manager::ref_const_zone_data = std::reference_wrapper<const zone_data>
Definition at line 343 of file clzones.h.
ref_zone_data
using zone_manager::ref_zone_data = std::reference_wrapper<zone_data>
Definition at line 342 of file clzones.h.
Constructor & Destructor Documentation
zone_manager() [1/3]
zone_manager::zone_manager () private
Definition at line 61 of file clzones.cpp.
{
    types.emplace( zone_NO_AUTO_PICKUP,
                   zone_type( translate_marker( "No Auto Pickup" ),
                              translate_marker( "You won't auto-pickup items inside the zone." ) ) );
    types.emplace( zone_NO_NPC_PICKUP,
                   zone_type( translate_marker( "No NPC Pickup" ),
                              translate_marker( "Friendly NPCs don't pickup items inside the zone." ) ) );
    types.emplace( zone_type_id( "NPC_RETREAT" ),
                   zone_type( translate_marker( "NPC Retreat" ),
                              translate_marker( "When fleeing, friendly NPCs will attempt to retreat toward this zone if it is within 60 tiles." ) ) );
    types.emplace( zone_type_id( "NPC_NO_INVESTIGATE" ),
                   zone_type( translate_marker( "NPC Ignore Sounds" ),
                              translate_marker( "Friendly NPCs won't investigate unseen sounds coming from this zone." ) ) );
    types.emplace( zone_type_id( "NPC_INVESTIGATE_ONLY" ),
                   zone_type( translate_marker( "NPC Investigation Area" ),
                              translate_marker( "Friendly NPCs will investigate unseen sounds only if they come from inside this area." ) ) );
    for( const zone_type &zone : zone_type::get_all() ) {
        types.emplace( zone.id, zone );
    }
    types.emplace( zone_type_id( "SOURCE_FIREWOOD" ),
                   zone_type( translate_marker( "Source: Firewood" ),
                              translate_marker( "Source for firewood or other flammable materials in this zone may be used to automatically refuel fires.  "
                                      "This will be done to maintain light during long-running tasks such as crafting, reading or waiting." ) ) );
    types.emplace( zone_CONSTRUCTION_BLUEPRINT,
                   zone_type( translate_marker( "Construction: Blueprint" ),
                              translate_marker( "Designate a blueprint zone for construction." ) ) );
    types.emplace( zone_FARM_PLOT,
                   zone_type( translate_marker( "Farm: Plot" ),
                              translate_marker( "Designate a farm plot for tilling and planting." ) ) );
    types.emplace( zone_type_id( "CHOP_TREES" ),
                   zone_type( translate_marker( "Chop Trees" ),
                              translate_marker( "Designate an area to chop down trees." ) ) );
    types.emplace( zone_type_id( "FISHING_SPOT" ),
                   zone_type( translate_marker( "Fishing Spot" ),
                              translate_marker( "Designate an area to fish from." ) ) );
    types.emplace( zone_type_id( "MINING" ),
                   zone_type( translate_marker( "Mine Terrain" ),
                              translate_marker( "Designate an area to mine." ) ) );
    types.emplace( zone_type_id( "VEHICLE_DECONSTRUCT" ),
                   zone_type( translate_marker( "Vehicle Deconstruct Zone" ),
                              translate_marker( "Any vehicles in this area are marked for deconstruction." ) ) );
    types.emplace( zone_type_id( "VEHICLE_REPAIR" ),
                   zone_type( translate_marker( "Vehicle Repair Zone" ),
                              translate_marker( "Any vehicles in this area are marked for repair work." ) ) );
    types.emplace( zone_type_id( "VEHICLE_PATROL" ),
                   zone_type( translate_marker( "Vehicle Patrol Zone" ),
                              translate_marker( "Vehicles with an autopilot will patrol in this zone." ) ) );
    types.emplace( zone_type_id( "CAMP_STORAGE" ),
                   zone_type( translate_marker( "Basecamp: Storage" ),
                              translate_marker( "Items in this zone will be added to a basecamp's inventory for use by it's workers." ) ) );
    types.emplace( zone_CAMP_FOOD,
                   zone_type( translate_marker( "Basecamp: Food" ),
                              translate_marker( "Items in this zone will be added to a basecamp's food supply in the Distribute Food mission." ) ) );
    types.emplace( zone_type_id( "AUTO_EAT" ),
                   zone_type( translate_marker( "Auto Eat" ),
                              translate_marker( "Items in this zone will be automatically eaten during a long activity if you get hungry." ) ) );
    types.emplace( zone_type_id( "AUTO_DRINK" ),
                   zone_type( translate_marker( "Auto Drink" ),
                              translate_marker( "Items in this zone will be automatically consumed during a long activity if you get thirsty." ) ) );
}
References zone_type::get_all(), translate_marker, types, zone_CAMP_FOOD, zone_CONSTRUCTION_BLUEPRINT, zone_FARM_PLOT, zone_NO_AUTO_PICKUP, and zone_NO_NPC_PICKUP.
Referenced by reset_manager().
~zone_manager()
zone_manager::~zone_manager () private default
zone_manager() [2/3]
zone_manager::zone_manager (zone_manager &&) private default
zone_manager() [3/3]
zone_manager::zone_manager (const zone_manager &) private default
Member Function Documentation
add()
void zone_manager::add (const std::string & name, const zone_type_id & type, const faction_id & faction, bool invert, bool enabled, const tripoint & start, const tripoint & end, shared_ptr_fast< zone_options > options = nullptr)
Definition at line 974 of file clzones.cpp.
{
    zone_data new_zone = zone_data( name, type, fac, invert, enabled, start, end, options );
    //the start is a vehicle tile with cargo space
    map &here = get_map();
    if( const cata::optional<vpart_reference> vp = here.veh_at( here.getlocal(
                start ) ).part_with_feature( "CARGO", false ) ) {
        // TODO:Allow for loot zones on vehicles to be larger than 1x1
        if( start == end && query_yn( _( "Bind this zone to the cargo part here?" ) ) ) {
            // TODO: refactor zone options for proper validation code
            if( type == zone_FARM_PLOT || type == zone_CONSTRUCTION_BLUEPRINT ) {
                popup( _( "You cannot add that type of zone to a vehicle." ), PF_NONE );
                return;
            }
            create_vehicle_loot_zone( vp->vehicle(), vp->mount(), new_zone );
            return;
        }
    }
    //Create a regular zone
    zones.push_back( new_zone );
    cache_data();
}
References _, cache_data(), create_vehicle_loot_zone(), enabled, get_map(), map::getlocal(), om_direction::name(), PATH_INFO::options(), optional_vpart_position::part_with_feature(), PF_NONE, popup(), query_yn(), type, map::veh_at(), zone_CONSTRUCTION_BLUEPRINT, zone_FARM_PLOT, and zones.
Referenced by jmapgen_zone::apply().
cache_data()
void zone_manager::cache_data ()
Definition at line 604 of file clzones.cpp.
{
    area_cache.clear();
    for( auto &elem : zones ) {
        if( !elem.get_enabled() ) {
            continue;
        }
        const std::string &type_hash = elem.get_type_hash();
        auto &cache = area_cache[type_hash];
        // Draw marked area
        for( const tripoint &p : tripoint_range<tripoint>( elem.get_start_point(),
                elem.get_end_point() ) ) {
            cache.insert( p );
        }
    }
}
References area_cache, and zones.
Referenced by add(), load_zones(), zone_data::set_position(), and zone_data::set_type().
cache_vzones()
void zone_manager::cache_vzones ()
Definition at line 624 of file clzones.cpp.
{
    vzone_cache.clear();
    auto vzones = get_map().get_vehicle_zones( g->get_levz() );
    for( auto elem : vzones ) {
        if( !elem->get_enabled() ) {
            continue;
        }
        const std::string &type_hash = elem->get_type_hash();
        auto &cache = vzone_cache[type_hash];
        // TODO: looks very similar to the above cache_data - maybe merge it?
        // Draw marked area
        for( const tripoint &p : tripoint_range<tripoint>( elem->get_start_point(),
                elem->get_end_point() ) ) {
            cache.insert( p );
        }
    }
}
References g, get_map(), map::get_vehicle_zones(), and vzone_cache.
Referenced by create_vehicle_loot_zone(), basecamp::distribute_food(), find_auto_consume(), map::get_vehicle_zones(), load_zones(), remove(), and revert_vzones().
create_vehicle_loot_zone()
void zone_manager::create_vehicle_loot_zone (class vehicle & vehicle, const point & mount_point, zone_data & new_zone)
Definition at line 962 of file clzones.cpp.
{
    //create a vehicle loot zone
    new_zone.set_is_vehicle( true );
    auto nz = vehicle.loot_zones.emplace( mount_point, new_zone );
    get_map().register_vehicle_zone( &vehicle, g->get_levz() );
    vehicle.zones_dirty = false;
    added_vzones.push_back( &nz->second );
    cache_vzones();
}
References added_vzones, cache_vzones(), g, get_map(), vehicle::loot_zones, map::register_vehicle_zone(), zone_data::set_is_vehicle(), and vehicle::zones_dirty.
Referenced by add(), vehicle::merge_rackable_vehicle(), and vehicle::split_vehicles().
custom_loot_has()
bool zone_manager::custom_loot_has (const tripoint & where, const item * it) const
Definition at line 759 of file clzones.cpp.
{
    auto zone = get_zone_at( where, zone_LOOT_CUSTOM );
    if( !zone || !it ) {
        return false;
    }
    const loot_options &options = dynamic_cast<const loot_options &>( zone->get_options() );
    std::string filter_string = options.get_mark();
    auto z = item_filter_from_string( filter_string );
    return z( *it );
}
References get_zone_at(), item_filter_from_string(), PATH_INFO::options(), and zone_LOOT_CUSTOM.
Referenced by get_near().
deserialize()
void zone_manager::deserialize (JsonIn & jsin)
Definition at line 1136 of file clzones.cpp.
{
    jsin.read( zones );
    for( auto it = zones.begin(); it != zones.end(); ++it ) {
        const zone_type_id zone_type = it->get_type();
        if( !has_type( zone_type ) ) {
            zones.erase( it );
            debugmsg( "Invalid zone type: %s", zone_type.c_str() );
        }
    }
}
References debugmsg, has_type(), JsonIn::read(), and zones.
Referenced by load_zones().
get_bottom_zone()
const zone_data * zone_manager::get_bottom_zone (const tripoint & where, const faction_id & fac = your_fac) const
Definition at line 930 of file clzones.cpp.
{
    for( auto it = zones.rbegin(); it != zones.rend(); ++it ) {
        const auto &zone = *it;
        if( zone.get_faction() != fac ) {
            continue;
        }
        if( zone.has_inside( where ) ) {
            return &zone;
        }
    }
    auto vzones = get_map().get_vehicle_zones( g->get_levz() );
    for( auto it = vzones.rbegin(); it != vzones.rend(); ++it ) {
        const auto zone = *it;
        if( zone->get_faction() != fac ) {
            continue;
        }
        if( zone->has_inside( where ) ) {
            return zone;
        }
    }
    return nullptr;
}
References g, get_map(), map::get_vehicle_zones(), and zones.
get_manager()
zone_manager & zone_manager::get_manager () static
Definition at line 126 of file clzones.cpp.
{
    static zone_manager manager;
    return manager;
}
Referenced by activity_on_turn_move_loot(), jmapgen_zone::apply(), are_requirements_nearby(), vehicle::autopilot_patrol(), vehicle::autopilot_patrol_check(), talk_function::basecamp_mission(), can_do_activity_there(), game::check_near_zone(), game::check_zone(), basecamp::distribute_food(), overmap_ui::draw_ascii(), find_auto_consume(), find_refuel_spot_zone(), basecamp::form_crafting_inventory(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_locations(), map::get_vehicle_zones(), npc::good_escape_direction(), npc::handle_sound(), has_loot_dest_near(), game::load(), loot(), vehicle::merge_rackable_vehicle(), perform_zone_activity_turn(), basecamp::place_results(), plot_options::query_seed(), query_type(), requirements_map(), reset_manager(), map::rotate(), zone_data::set_enabled(), zone_data::set_name(), zone_data::set_position(), zone_data::set_type(), vehicle::split_vehicles(), tidy_activity(), basecamp::validate_sort_points(), and game::zones_manager().
get_name_from_type()
std::string zone_manager::get_name_from_type (const zone_type_id & type) const
Definition at line 583 of file clzones.cpp.
{
    const auto &iter = types.find( type );
    if( iter != types.end() ) {
        return iter->second.name();
    }
    return "Unknown Type";
}
References type, and types.
get_near()
std::unordered_set< tripoint > zone_manager::get_near (const zone_type_id & type, const tripoint & where, int range = MAX_DISTANCE, const item * it = nullptr, const faction_id & fac = your_fac) const
Definition at line 772 of file clzones.cpp.
{
    const auto &point_set = get_point_set( type, fac );
    auto near_point_set = std::unordered_set<tripoint>();
    for( auto &point : point_set ) {
        if( point.z == where.z ) {
            if( square_dist( point, where ) <= range ) {
                if( it && has( zone_LOOT_CUSTOM, point ) ) {
                    if( custom_loot_has( point, it ) ) {
                        near_point_set.insert( point );
                    }
                } else {
                    near_point_set.insert( point );
                }
            }
        }
    }
    const auto &vzone_set = get_vzone_set( type, fac );
    for( auto &point : vzone_set ) {
        if( point.z == where.z ) {
            if( square_dist( point, where ) <= range ) {
                if( it && has( zone_LOOT_CUSTOM, point ) ) {
                    if( custom_loot_has( point, it ) ) {
                        near_point_set.insert( point );
                    }
                } else {
                    near_point_set.insert( point );
                }
            }
        }
    }
    return near_point_set;
}
References custom_loot_has(), get_point_set(), get_vzone_set(), has(), square_dist(), type, tripoint::z, and zone_LOOT_CUSTOM.
Referenced by add_basecamp_storage_to_loot_zone_list(), vehicle::autopilot_patrol(), basecamp::distribute_food(), find_auto_consume(), find_refuel_spot_zone(), generic_multi_activity_locations(), get_near_zone_type_for_item(), and perform_zone_activity_turn().
get_near_zone_type_for_item()
zone_type_id zone_manager::get_near_zone_type_for_item (const item & it, const tripoint & where, int range = MAX_DISTANCE) const
Definition at line 848 of file clzones.cpp.
{
    const item_category &cat = it.get_category();
    if( has_near( zone_LOOT_CUSTOM, where, range ) ) {
        if( !get_near( zone_LOOT_CUSTOM, where, range, &it ).empty() ) {
            return zone_LOOT_CUSTOM;
        }
    }
    if( it.has_flag( flag_FIREWOOD ) ) {
        if( has_near( zone_LOOT_WOOD, where, range ) ) {
            return zone_LOOT_WOOD;
        }
    }
    if( it.is_corpse() ) {
        if( has_near( zone_LOOT_CORPSE, where, range ) ) {
            return zone_LOOT_CORPSE;
        }
    }
    cata::optional<zone_type_id> zone_check_first = cat.priority_zone( it );
    if( zone_check_first && has_near( *zone_check_first, where, range ) ) {
        return *zone_check_first;
    }
    if( cat.zone() ) {
        return *cat.zone();
    }
    if( cat.get_id() == itcat_food ) {
        const bool preserves = it.is_food_container() && it.type->container->preserves;
        // skip food without comestible, like MREs
        if( const item *it_food = it.get_food() ) {
            if( it_food->get_comestible()->comesttype == "DRINK" ) {
                if( !preserves && it_food->goes_bad() && has_near( zone_LOOT_PDRINK, where, range ) ) {
                    return zone_LOOT_PDRINK;
                } else if( has_near( zone_LOOT_DRINK, where, range ) ) {
                    return zone_LOOT_DRINK;
                }
            }
            if( !preserves && it_food->goes_bad() && has_near( zone_LOOT_PFOOD, where, range ) ) {
                return zone_LOOT_PFOOD;
            }
        }
        return zone_LOOT_FOOD;
    }
    return zone_type_id();
}
References itype::container, flag_FIREWOOD(), item::get_category(), item::get_food(), item_category::get_id(), get_near(), item::has_flag(), has_near(), item::is_corpse(), item::is_food_container(), itcat_food, item_category::priority_zone(), item::type, item_category::zone(), zone_LOOT_CORPSE, zone_LOOT_CUSTOM, zone_LOOT_DRINK, zone_LOOT_FOOD, zone_LOOT_PDRINK, zone_LOOT_PFOOD, and zone_LOOT_WOOD.
get_nearest()
cata::optional< tripoint > zone_manager::get_nearest (const zone_type_id & type, const tripoint & where, int range = MAX_DISTANCE, const faction_id & fac = your_fac) const
Definition at line 810 of file clzones.cpp.
{
    if( range < 0 ) {
        return cata::nullopt;
    }
    tripoint nearest_pos = tripoint( INT_MIN, INT_MIN, INT_MIN );
    int nearest_dist = range + 1;
    const std::unordered_set<tripoint> &point_set = get_point_set( type, fac );
    for( const tripoint &p : point_set ) {
        int cur_dist = square_dist( p, where );
        if( cur_dist < nearest_dist ) {
            nearest_dist = cur_dist;
            nearest_pos = p;
            if( nearest_dist == 0 ) {
                return nearest_pos;
            }
        }
    }
    const std::unordered_set<tripoint> &vzone_set = get_vzone_set( type, fac );
    for( const tripoint &p : vzone_set ) {
        int cur_dist = square_dist( p, where );
        if( cur_dist < nearest_dist ) {
            nearest_dist = cur_dist;
            nearest_pos = p;
            if( nearest_dist == 0 ) {
                return nearest_pos;
            }
        }
    }
    if( nearest_dist > range ) {
        return cata::nullopt;
    }
    return nearest_pos;
}
References get_point_set(), get_vzone_set(), cata::nullopt, square_dist(), and type.
Referenced by npc::good_escape_direction().
get_point_set()
std::unordered_set< tripoint > zone_manager::get_point_set (const zone_type_id & type, const faction_id & fac = your_fac) const private
Definition at line 646 of file clzones.cpp.
{
    const auto &type_iter = area_cache.find( zone_data::make_type_hash( type, fac ) );
    if( type_iter == area_cache.end() ) {
        return std::unordered_set<tripoint>();
    }
    return type_iter->second;
}
References area_cache, zone_data::make_type_hash(), and type.
Referenced by get_near(), get_nearest(), has(), and has_near().
get_point_set_loot() [1/2]
std::unordered_set< tripoint > zone_manager::get_point_set_loot (const tripoint & where, int radius, bool npc_search, const faction_id & fac = your_fac) const
Definition at line 663 of file clzones.cpp.
{
    std::unordered_set<tripoint> res;
    map &here = get_map();
    for( const tripoint elem : here.points_in_radius( here.getlocal( where ), radius ) ) {
        const zone_data *zone = get_zone_at( here.getabs( elem ) );
        // if not a LOOT zone
        if( ( !zone ) || ( zone->get_type().str().substr( 0, 4 ) != "LOOT" ) ) {
            continue;
        }
        if( npc_search && ( has( zone_NO_NPC_PICKUP, elem ) ) ) {
            continue;
        }
        res.insert( elem );
    }
    return res;
}
References get_map(), zone_data::get_type(), get_zone_at(), map::getabs(), map::getlocal(), has(), map::points_in_radius(), string_id< T >::str(), and zone_NO_NPC_PICKUP.
get_point_set_loot() [2/2]
std::unordered_set< tripoint > zone_manager::get_point_set_loot (const tripoint & where, int radius, const faction_id & fac = your_fac) const
Definition at line 657 of file clzones.cpp.
{
    return get_point_set_loot( where, radius, false, fac );
}
References get_point_set_loot().
Referenced by generic_multi_activity_check_requirement(), get_point_set_loot(), and requirements_map().
get_types()
const std::map< zone_type_id, zone_type > & zone_manager::get_types () const inline
Definition at line 391 of file clzones.h.
{
            return types;
        }
References types.
Referenced by has_loot_dest_near(), and query_type().
get_vzone_set()
std::unordered_set< tripoint > zone_manager::get_vzone_set (const zone_type_id & type, const faction_id & fac = your_fac) const private
Definition at line 682 of file clzones.cpp.
{
    //Only regenerate the vehicle zone cache if any vehicles have moved
    const auto &type_iter = vzone_cache.find( zone_data::make_type_hash( type, fac ) );
    if( type_iter == vzone_cache.end() ) {
        return std::unordered_set<tripoint>();
    }
    return type_iter->second;
}
References zone_data::make_type_hash(), type, and vzone_cache.
Referenced by get_near(), get_nearest(), has(), and has_near().
get_zone_at() [1/2]
const zone_data * zone_manager::get_zone_at (const tripoint & where) const
Definition at line 918 of file clzones.cpp.
{
    for( auto it = zones.rbegin(); it != zones.rend(); ++it ) {
        const auto &zone = *it;
        if( zone.has_inside( where ) ) {
            return &zone;
        }
    }
    return nullptr;
}
References zones.
get_zone_at() [2/2]
const zone_data * zone_manager::get_zone_at (const tripoint & where, const zone_type_id & type) const
Definition at line 743 of file clzones.cpp.
{
    for( const zone_data &zone : zones ) {
        if( zone.has_inside( where ) && zone.get_type() == type ) {
            return &zone;
        }
    }
    auto vzones = get_map().get_vehicle_zones( g->get_levz() );
    for( const zone_data *zone : vzones ) {
        if( zone->has_inside( where ) && zone->get_type() == type ) {
            return zone;
        }
    }
    return nullptr;
}
References g, get_map(), map::get_vehicle_zones(), type, and zones.
Referenced by custom_loot_has(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), get_point_set_loot(), and get_zone_for_act().
get_zones() [1/3]
std::vector< zone_manager::ref_zone_data > zone_manager::get_zones (const faction_id & fac = your_fac)
Definition at line 1088 of file clzones.cpp.
{
    auto zones = std::vector<ref_zone_data>();
    for( auto &zone : this->zones ) {
        if( zone.get_faction() == fac ) {
            zones.emplace_back( zone );
        }
    }
    auto vzones = get_map().get_vehicle_zones( g->get_levz() );
    for( auto zone : vzones ) {
        if( zone->get_faction() == fac ) {
            zones.emplace_back( *zone );
        }
    }
    return zones;
}
References g, get_map(), map::get_vehicle_zones(), and zones.
get_zones() [2/3]
std::vector< zone_manager::ref_const_zone_data > zone_manager::get_zones (const faction_id & fac = your_fac) const
Definition at line 1109 of file clzones.cpp.
{
    auto zones = std::vector<ref_const_zone_data>();
    for( auto &zone : this->zones ) {
        if( zone.get_faction() == fac ) {
            zones.emplace_back( zone );
        }
    }
    auto vzones = get_map().get_vehicle_zones( g->get_levz() );
    for( auto zone : vzones ) {
        if( zone->get_faction() == fac ) {
            zones.emplace_back( *zone );
        }
    }
    return zones;
}
References g, get_map(), map::get_vehicle_zones(), and zones.
get_zones() [3/3]
std::vector< zone_data > zone_manager::get_zones (const zone_type_id & type, const tripoint & where, const faction_id & fac = your_fac) const
Definition at line 902 of file clzones.cpp.
{
    auto zones = std::vector<zone_data>();
    for( const auto &zone : this->zones ) {
        if( zone.get_type() == type && zone.get_faction() == fac ) {
            if( zone.has_inside( where ) ) {
                zones.emplace_back( zone );
            }
        }
    }
    return zones;
}
References type, and zones.
Referenced by can_do_activity_there(), and generic_multi_activity_do().
has()
bool zone_manager::has (const zone_type_id & type, const tripoint & where, const faction_id & fac = your_fac) const
Definition at line 694 of file clzones.cpp.
{
    const auto &point_set = get_point_set( type, fac );
    const auto &vzone_set = get_vzone_set( type, fac );
    return point_set.find( where ) != point_set.end() || vzone_set.find( where ) != vzone_set.end();
}
References get_point_set(), get_vzone_set(), and type.
Referenced by are_requirements_nearby(), game::check_zone(), get_near(), get_point_set_loot(), and npc::handle_sound().
has_defined()
bool zone_manager::has_defined (const zone_type_id & type, const faction_id & fac = your_fac) const
Definition at line 598 of file clzones.cpp.
{
    const auto &type_iter = area_cache.find( zone_data::make_type_hash( type, fac ) );
    return type_iter != area_cache.end();
}
References area_cache, zone_data::make_type_hash(), and type.
has_loot_dest_near()
bool zone_manager::has_loot_dest_near (const tripoint & where) const
Definition at line 726 of file clzones.cpp.
{
    for( const auto &ztype : get_manager().get_types() ) {
        const zone_type_id &type = ztype.first;
        if( type == zone_CAMP_FOOD || type == zone_FARM_PLOT ||
            type == zone_LOOT_UNSORTED || type == zone_LOOT_IGNORE ||
            type == zone_CONSTRUCTION_BLUEPRINT ||
            type == zone_NO_AUTO_PICKUP || type == zone_NO_NPC_PICKUP ) {
            continue;
        }
        if( has_near( type, where ) ) {
            return true;
        }
    }
    return false;
}
References get_manager(), get_types(), has_near(), type, zone_CAMP_FOOD, zone_CONSTRUCTION_BLUEPRINT, zone_FARM_PLOT, zone_LOOT_IGNORE, zone_LOOT_UNSORTED, zone_NO_AUTO_PICKUP, and zone_NO_NPC_PICKUP.
has_near()
bool zone_manager::has_near (const zone_type_id & type, const tripoint & where, int range = MAX_DISTANCE, const faction_id & fac = your_fac) const
Definition at line 702 of file clzones.cpp.
{
    const auto &point_set = get_point_set( type, fac );
    for( auto &point : point_set ) {
        if( point.z == where.z ) {
            if( square_dist( point, where ) <= range ) {
                return true;
            }
        }
    }
    const auto &vzone_set = get_vzone_set( type, fac );
    for( auto &point : vzone_set ) {
        if( point.z == where.z ) {
            if( square_dist( point, where ) <= range ) {
                return true;
            }
        }
    }
    return false;
}
References get_point_set(), get_vzone_set(), square_dist(), type, and tripoint::z.
Referenced by add_basecamp_storage_to_loot_zone_list(), vehicle::autopilot_patrol_check(), can_do_activity_there(), game::check_near_zone(), get_near_zone_type_for_item(), and has_loot_dest_near().
has_type()
bool zone_manager::has_type (const zone_type_id & type) const
Definition at line 593 of file clzones.cpp.
{
    return types.count( type ) > 0;
}
References type, and types.
Referenced by deserialize().
load_zones()
void zone_manager::load_zones ()
Definition at line 1216 of file clzones.cpp.
{
    std::string savefile = g->get_player_base_save_path() + ".zones.json";
    read_from_file_optional( savefile, [&]( std::istream & fin ) {
        JsonIn jsin( fin );
        deserialize( jsin );
    } );
    revert_vzones();
    added_vzones.clear();
    changed_vzones.clear();
    removed_vzones.clear();
    cache_data();
    cache_vzones();
}
References added_vzones, cache_data(), cache_vzones(), changed_vzones, deserialize(), g, read_from_file_optional(), removed_vzones, and revert_vzones().
Referenced by game::load().
operator=() [1/2]
zone_manager & zone_manager::operator= (const zone_manager &) private default
operator=() [2/2]
zone_manager & zone_manager::operator= (zone_manager &&) private default
query_name()
cata::optional< std::string > zone_manager::query_name (const std::string & default_name = "") const
Definition at line 472 of file clzones.cpp.
{
    string_input_popup popup;
    popup
    .title( _( "Zone name:" ) )
    .width( 55 )
    .text( default_name )
    .query();
    if( popup.canceled() ) {
        return {};
    } else {
        return popup.text();
    }
}
References _, and popup().
Referenced by zone_data::set_name().
query_type()
cata::optional< zone_type_id > zone_manager::query_type () const
Definition at line 487 of file clzones.cpp.
{
    const auto &types = get_manager().get_types();
    std::vector<std::pair<zone_type_id, zone_type>> types_vec;
    std::copy( types.begin(), types.end(),
               std::back_inserter<std::vector<std::pair<zone_type_id, zone_type>>>( types_vec ) );
    std::sort( types_vec.begin(), types_vec.end(),
    []( const std::pair<zone_type_id, zone_type> &lhs, const std::pair<zone_type_id, zone_type> &rhs ) {
        return localized_compare( lhs.second.name(), rhs.second.name() );
    } );
    uilist as_m;
    as_m.desc_enabled = true;
    as_m.text = _( "Select zone type:" );
    size_t i = 0;
    for( const auto &pair : types_vec ) {
        const auto &type = pair.second;
        as_m.addentry_desc( i++, true, MENU_AUTOASSIGN, type.name(), type.desc() );
    }
    as_m.query();
    if( as_m.ret < 0 ) {
        return {};
    }
    size_t index = as_m.ret;
    auto iter = types_vec.begin();
    std::advance( iter, index );
    return iter->first;
}
References _, uilist::addentry_desc(), uilist::desc_enabled, get_manager(), get_types(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::text, type, and types.
Referenced by zone_data::set_type().
remove()
bool zone_manager::remove (zone_data & zone)
Definition at line 1001 of file clzones.cpp.
{
    for( auto it = zones.begin(); it != zones.end(); ++it ) {
        if( &zone == &*it ) {
            zones.erase( it );
            return true;
        }
    }
    zone_data old_zone = zone_data( zone );
    //If the zone was previously edited this session
    //Move original data out of changed
    for( auto it = changed_vzones.begin(); it != changed_vzones.end(); ++it ) {
        if( it->second == &zone ) {
            old_zone = zone_data( it->first );
            changed_vzones.erase( it );
            break;
        }
    }
    bool added = false;
    //If the zone was added this session
    //remove from added, and don't add to removed
    for( auto it = added_vzones.begin(); it != added_vzones.end(); ++it ) {
        if( *it == &zone ) {
            added = true;
            added_vzones.erase( it );
            break;
        }
    }
    if( !added ) {
        removed_vzones.push_back( old_zone );
    }
    if( !get_map().deregister_vehicle_zone( zone ) ) {
        debugmsg( "Tried to remove a zone from an unloaded vehicle" );
        return false;
    }
    cache_vzones();
    return true;
}
References added_vzones, cache_vzones(), changed_vzones, debugmsg, get_map(), removed_vzones, and zones.
Referenced by revert_vzones().
reset_manager()
void zone_manager::reset_manager () static
Definition at line 132 of file clzones.cpp.
{
    get_manager() = zone_manager();
}
References get_manager(), and zone_manager().
Referenced by DynamicDataLoader::finalize_loaded_data().
revert_vzones()
void zone_manager::revert_vzones ()
Definition at line 1247 of file clzones.cpp.
{
    map &here = get_map();
    for( auto zone : removed_vzones ) {
        //Code is copied from add() to avoid yn query
        if( const cata::optional<vpart_reference> vp = here.veh_at( here.getlocal(
                    zone.get_start_point() ) ).part_with_feature( "CARGO", false ) ) {
            zone.set_is_vehicle( true );
            vp->vehicle().loot_zones.emplace( vp->mount(), zone );
            vp->vehicle().zones_dirty = false;
            here.register_vehicle_zone( &vp->vehicle(), g->get_levz() );
            cache_vzones();
        }
    }
    for( const auto &zpair : changed_vzones ) {
        *( zpair.second ) = zpair.first;
    }
    for( auto zone : added_vzones ) {
        remove( *zone );
    }
}
References added_vzones, cache_vzones(), changed_vzones, g, get_map(), map::getlocal(), optional_vpart_position::part_with_feature(), map::register_vehicle_zone(), remove(), removed_vzones, and map::veh_at().
Referenced by load_zones().
rotate_zones()
void zone_manager::rotate_zones (map & target_map, int turns)
Definition at line 1052 of file clzones.cpp.
{
    if( turns == 0 ) {
        return;
    }
    const tripoint a_start = target_map.getabs( tripoint_zero );
    const tripoint a_end = target_map.getabs( tripoint( 23, 23, 0 ) );
    const point dim( 24, 24 );
    for( zone_data &zone : zones ) {
        const tripoint z_start = zone.get_start_point();
        const tripoint z_end = zone.get_end_point();
        if( ( a_start.x <= z_start.x && a_start.y <= z_start.y ) &&
            ( a_end.x > z_start.x && a_end.y >= z_start.y ) &&
            ( a_start.x <= z_end.x && a_start.y <= z_end.y ) &&
            ( a_end.x >= z_end.x && a_end.y >= z_end.y ) &&
            ( a_start.z == z_start.z )
          ) {
            tripoint z_l_start3 = target_map.getlocal( z_start );
            tripoint z_l_end3 = target_map.getlocal( z_end );
            // don't rotate centered squares
            if( z_l_start3.x == z_l_start3.y && z_l_end3.x == z_l_end3.y && z_l_start3.x + z_l_end3.x == 23 ) {
                continue;
            }
            point z_l_start = z_l_start3.xy().rotate( turns, dim );
            point z_l_end = z_l_end3.xy().rotate( turns, dim );
            point new_z_start = target_map.getabs( z_l_start );
            point new_z_end = target_map.getabs( z_l_end );
            tripoint first = tripoint( std::min( new_z_start.x, new_z_end.x ),
                                       std::min( new_z_start.y, new_z_end.y ), a_start.z );
            tripoint second = tripoint( std::max( new_z_start.x, new_z_end.x ),
                                        std::max( new_z_start.y, new_z_end.y ), a_end.z );
            zone.set_position( std::make_pair( first, second ), false );
        }
    }
}
References map::getabs(), map::getlocal(), point::rotate(), second, tripoint_zero, point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, tripoint::z, and zones.
Referenced by map::rotate().
save_zones()
bool zone_manager::save_zones ()
Definition at line 1203 of file clzones.cpp.
{
    std::string savefile = g->get_player_base_save_path() + ".zones.json";
    added_vzones.clear();
    changed_vzones.clear();
    removed_vzones.clear();
    return write_to_file( savefile, [&]( std::ostream & fout ) {
        JsonOut jsout( fout );
        serialize( jsout );
    }, _( "zones date" ) );
}
References _, added_vzones, changed_vzones, g, removed_vzones, serialize(), and write_to_file().
serialize()
void zone_manager::serialize (JsonOut & json) const
Definition at line 1131 of file clzones.cpp.
{
    json.write( zones );
}
References JsonOut::write(), and zones.
Referenced by save_zones().
size()
unsigned int zone_manager::size () const inline
Definition at line 388 of file clzones.h.
{
            return zones.size();
        }
References zones.
swap()
void zone_manager::swap (zone_data & a, zone_data & b)
Definition at line 1041 of file clzones.cpp.
{
    if( a.get_is_vehicle() || b.get_is_vehicle() ) {
        //Current swap mechanic will change which vehicle the zone is on
        // TODO: track and update vehicle zone priorities?
        popup( _( "You cannot change the order of vehicle loot zones." ), PF_NONE );
        return;
    }
    std::swap( a, b );
}
References _, a, b, PF_NONE, popup(), and cata::swap().
zone_edited()
void zone_manager::zone_edited (zone_data & zone)
Definition at line 1233 of file clzones.cpp.
{
    if( zone.get_is_vehicle() ) {
        //Check if this zone has already been stored
        for( auto &changed_vzone : changed_vzones ) {
            if( &zone == changed_vzone.second ) {
                return;
            }
        }
        //Add it to the list of changed zones
        changed_vzones.push_back( std::make_pair( zone_data( zone ), &zone ) );
    }
}
References changed_vzones, and zone_data::get_is_vehicle().
Referenced by zone_data::set_enabled(), zone_data::set_name(), and zone_data::set_type().
Member Data Documentation
added_vzones
std::vector<zone_data *> zone_manager::added_vzones private
Definition at line 350 of file clzones.h.
Referenced by create_vehicle_loot_zone(), load_zones(), remove(), revert_vzones(), and save_zones().
area_cache
std::unordered_map<std::string, std::unordered_set<tripoint> > zone_manager::area_cache private
Definition at line 357 of file clzones.h.
Referenced by cache_data(), get_point_set(), and has_defined().
changed_vzones
std::vector<std::pair<zone_data, zone_data *> > zone_manager::changed_vzones private
Definition at line 352 of file clzones.h.
Referenced by load_zones(), remove(), revert_vzones(), save_zones(), and zone_edited().
MAX_DISTANCE
const int zone_manager::MAX_DISTANCE = 10 static private
Definition at line 346 of file clzones.h.
num_processed
std::unordered_map<tripoint, int> zone_manager::num_processed private
Definition at line 365 of file clzones.h.
removed_vzones
std::vector<zone_data> zone_manager::removed_vzones private
Definition at line 354 of file clzones.h.
Referenced by load_zones(), remove(), revert_vzones(), and save_zones().
types
std::map<zone_type_id, zone_type> zone_manager::types private
Definition at line 356 of file clzones.h.
Referenced by get_name_from_type(), get_types(), has_type(), query_type(), and zone_manager().
vzone_cache
std::unordered_map<std::string, std::unordered_set<tripoint> > zone_manager::vzone_cache private
Definition at line 358 of file clzones.h.
Referenced by cache_vzones(), and get_vzone_set().
zones
std::vector<zone_data> zone_manager::zones private
Definition at line 347 of file clzones.h.
Referenced by add(), cache_data(), deserialize(), get_bottom_zone(), get_zone_at(), get_zones(), remove(), rotate_zones(), serialize(), and size().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp