Cataclysm BN: pickup_inventory_preset Class Reference
pickup_inventory_preset Class Reference
Public Member Functions
pickup_inventory_preset (const player &p)
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool is_shown (const item_location &) const
Does this entry satisfy the basic preset conditions?
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Private Attributes
const player & p
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Detailed Description
Definition at line 426 of file game_inventory.cpp.
Constructor & Destructor Documentation
pickup_inventory_preset()
pickup_inventory_preset::pickup_inventory_preset (const player & p) inline
Definition at line 429 of file game_inventory.cpp.
: p(p) {}
Member Function Documentation
get_denial()
std::string pickup_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Reimplemented in disassemble_inventory_preset, and activatable_inventory_preset.
Definition at line 431 of file game_inventory.cpp.
{
            if( !p.has_item( *loc ) ) {
                if( loc->made_of( LIQUID ) ) {
                    return _( "Can't pick up spilt liquids" );
                } else if( !p.can_pick_volume( *loc ) && p.is_armed() ) {
                    return _( "Too big to pick up" );
                } else if( !p.can_pick_weight( *loc, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
                    return _( "Too heavy to pick up" );
                }
            }
            return std::string();
        }
References _, Character::can_pick_volume(), Character::can_pick_weight(), visitable< T >::has_item(), Character::is_armed(), LIQUID, item::made_of(), and p.
Referenced by disassemble_inventory_preset::get_denial(), and activatable_inventory_preset::get_denial().
Member Data Documentation
p
const player& pickup_inventory_preset::p private
Definition at line 446 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp