Cataclysm BN: format_int Class Reference
format_int Class Reference
Fast integer formatter.
#include <fmtlib_format.h>
Public Member Functions
format_int (int value)
format_int (long value)
format_int (long long value)
format_int (unsigned value)
format_int (unsigned long value)
format_int (unsigned long long value)
size_t size () const
Returns the number of characters written to the output buffer.
const char * data () const
Returns a pointer to the output buffer content.
const char * c_str () const
Returns a pointer to the output buffer content with terminating null character appended.
std::string str () const
\rst Returns the content of the output buffer as an std::string.
Private Types
enum { buffer_size = std::numeric_limits<unsigned long long>::digits10 + 3 }
Private Member Functions
template<typename UInt >
char * format_unsigned (UInt value)
template<typename Int >
char * format_signed (Int value)
Private Attributes
char buffer_ [buffer_size]
char * str_
Detailed Description
Fast integer formatter.
Definition at line 3809 of file fmtlib_format.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
buffer_size
Definition at line 3814 of file fmtlib_format.h.
{ buffer_size = std::numeric_limits<unsigned long long>::digits10 + 3 };
Constructor & Destructor Documentation
format_int() [1/6]
format_int::format_int (int value) inline explicit
Definition at line 3837 of file fmtlib_format.h.
: str_(format_signed(value)) {}
format_int() [2/6]
format_int::format_int (long value) inline explicit
Definition at line 3839 of file fmtlib_format.h.
: str_(format_signed(value)) {}
format_int() [3/6]
format_int::format_int (long long value) inline explicit
Definition at line 3840 of file fmtlib_format.h.
: str_(format_signed(value)) {}
format_int() [4/6]
format_int::format_int (unsigned value) inline explicit
Definition at line 3841 of file fmtlib_format.h.
: str_(format_unsigned(value)) {}
format_int() [5/6]
format_int::format_int (unsigned long value) inline explicit
Definition at line 3843 of file fmtlib_format.h.
: str_(format_unsigned(value)) {}
format_int() [6/6]
format_int::format_int (unsigned long long value) inline explicit
Definition at line 3844 of file fmtlib_format.h.
            : str_( format_unsigned( value ) ) {}
Member Function Documentation
c_str()
const char * format_int::c_str () const inline
Returns a pointer to the output buffer content with terminating null character appended.
Definition at line 3864 of file fmtlib_format.h.
{
            buffer_[buffer_size - 1] = '\0';
            return str_;
        }
References buffer_, buffer_size, and str_.
data()
const char * format_int::data () const inline
Returns a pointer to the output buffer content.
No terminating null character is appended.
Definition at line 3856 of file fmtlib_format.h.
{
            return str_;
        }
References str_.
format_signed()
template<typename Int > char * format_int::format_signed (Int value) inline private
Definition at line 3823 of file fmtlib_format.h.
{
            auto abs_value = static_cast<detail::uint32_or_64_or_128_t<Int>>( value );
            bool negative = value < 0;
            if( negative ) {
                abs_value = 0 - abs_value;
            }
            auto begin = format_unsigned( abs_value );
            if( negative ) {
                *--begin = '-';
            }
            return begin;
        }
References format_unsigned().
format_unsigned()
template<typename UInt > char * format_int::format_unsigned (UInt value) inline private
Definition at line 3818 of file fmtlib_format.h.
{
            auto n = static_cast<detail::uint32_or_64_or_128_t<UInt>>( value );
            return detail::format_decimal( buffer_, n, buffer_size - 1 ).begin;
        }
References buffer_, buffer_size, and detail::format_decimal().
Referenced by format_signed().
size()
size_t format_int::size () const inline
Returns the number of characters written to the output buffer.
Definition at line 3848 of file fmtlib_format.h.
{
            return detail::to_unsigned( buffer_ - str_ + buffer_size - 1 );
        }
References buffer_, buffer_size, str_, and detail::to_unsigned().
Referenced by str().
str()
std::string format_int::str () const inline
\rst Returns the content of the output buffer as an std::string.
\endrst
Definition at line 3874 of file fmtlib_format.h.
{
            return std::string( str_, size() );
        }
References size(), and str_.
Member Data Documentation
buffer_
char format_int::buffer_[buffer_size] mutable private
Definition at line 3815 of file fmtlib_format.h.
Referenced by c_str(), format_unsigned(), and size().
str_
char* format_int::str_ private
Definition at line 3816 of file fmtlib_format.h.
Referenced by c_str(), data(), size(), and str().
The documentation for this class was generated from the following file:
src/fmtlib_format.h