Cataclysm BN: timed_event_manager Class Reference
timed_event_manager Class Reference
#include <timed_event.h>
Public Member Functions
void add (timed_event_type type, const time_point &when, int faction_id=-1)
Add an entry to the event queue.
void add (timed_event_type type, const time_point &when, int faction_id, const tripoint &where)
Add an entry to the event queue.
bool queued (timed_event_type type) const
timed_event * get (timed_event_type type)
void process ()
Process all queued events, potentially altering the game state and modifying the event queue.
Private Attributes
std::list< timed_event > events
Detailed Description
Definition at line 44 of file timed_event.h.
Member Function Documentation
add() [1/2]
void timed_event_manager::add (timed_event_type type, const time_point & when, int faction_id, const tripoint & where)
Add an entry to the event queue.
Parameters are basically passed through to timed_event::timed_event.
Definition at line 324 of file timed_event.cpp.
{
    events.emplace_back( type, when, faction_id, where );
}
References events, and type.
add() [2/2]
void timed_event_manager::add (timed_event_type type, const time_point & when, int faction_id = -1)
Add an entry to the event queue.
Parameters are basically passed through to timed_event::timed_event.
Definition at line 318 of file timed_event.cpp.
{
    add( type, when, faction_id, g->u.global_sm_location() );
}
References add(), g, and type.
Referenced by add().
get()
timed_event * timed_event_manager::get (timed_event_type type)
Returns
One of the queued events of the given type, or nullptr if no event of that type is queued.
Definition at line 336 of file timed_event.cpp.
{
    for( auto &e : events ) {
        if( e.type == type ) {
            return &e;
        }
    }
    return nullptr;
}
References events, and type.
Referenced by game::natural_light_level(), and queued().
process()
void timed_event_manager::process ()
Process all queued events, potentially altering the game state and modifying the event queue.
Definition at line 305 of file timed_event.cpp.
{
    for( auto it = events.begin(); it != events.end(); ) {
        it->per_turn();
        if( it->when <= calendar::turn ) {
            it->actualize();
            it = events.erase( it );
        } else {
            it++;
        }
    }
}
References events, and calendar::turn.
Referenced by game::do_turn().
queued()
bool timed_event_manager::queued (timed_event_type type) const
Returns
Whether at least one element of the given type is queued.
Definition at line 331 of file timed_event.cpp.
{
    return const_cast<timed_event_manager &>( *this ).get( type ) != nullptr;
}
References get(), and type.
Referenced by game::natural_light_level().
Member Data Documentation
events
std::list<timed_event> timed_event_manager::events private
Definition at line 47 of file timed_event.h.
Referenced by add(), get(), and process().
The documentation for this class was generated from the following files:
src/timed_event.h
src/timed_event.cpp