Cataclysm BN: repair_item_actor Class Reference
repair_item_actor Class Reference
Repair an item.
#include <iuse_actor.h>
Public Types
enum attempt_hint : int {
AS_SUCCESS = 0 , AS_RETRY , AS_FAILURE , AS_DESTROYED ,
AS_CANT , AS_CANT_USE_TOOL , AS_CANT_YET
}
enum repair_type : int {
RT_NOTHING = 0 , RT_REPAIR , RT_REFIT , RT_DOWNSIZING ,
RT_UPSIZING , RT_REINFORCE , RT_PRACTICE , NUM_REPAIR_TYPES
}
Public Member Functions
attempt_hint repair (player &pl, item &tool, item_location &fix) const
Attempts to repair target item with selected tool.
bool can_repair_target (player &pl, const item &fix, bool print_msg) const
Checks if repairs on target item are possible.
bool can_use_tool (const player &p, const item &tool, bool print_msg) const
Checks if we are allowed to use the tool.
bool handle_components (player &pl, const item &fix, bool print_msg, bool just_check) const
Returns if components are available.
std::pair< float, float > repair_chance (const player &pl, const item &fix, repair_type action_type) const
Returns the chance to repair and to damage an item.
repair_type default_action (const item &fix, int current_skill_level) const
What are we most likely trying to do with this item?
int repair_recipe_difficulty (const player &pl, const item &fix, bool training=false) const
Calculates the difficulty to repair an item based on recipes to craft it and player's knowledge of them.
repair_item_actor (const std::string &type="repair_item")
~repair_item_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual void finalize (const itype_id &)
Finalizes the actor.
Static Public Member Functions
static std::string action_description (repair_type)
Describes members of repair_type enum.
Public Attributes
std::set< material_id > materials
Materials we are allowed to repair.
skill_id used_skill
Skill used.
int trains_skill_to = 0
Maximum skill level that can be gained by using this actor.
float cost_scaling = 1.0f
Volume of materials required (and used up) as percentage of repaired item's volume.
int tool_quality = 0
Extra value added to skill roll.
int move_cost = 0
Move cost for every attempt.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Repair an item.
Definition at line 933 of file iuse_actor.h.
Member Enumeration Documentation
attempt_hint
enum repair_item_actor::attempt_hint : int
Enumerator
AS_SUCCESS
AS_RETRY
AS_FAILURE
AS_DESTROYED
AS_CANT
AS_CANT_USE_TOOL
AS_CANT_YET
Definition at line 952 of file iuse_actor.h.
                          : int {
            AS_SUCCESS = 0,     // Success, but can retry
            AS_RETRY,           // Failed, but can retry
            AS_FAILURE,         // Failed hard, don't retry
            AS_DESTROYED,       // Failed and destroyed item
            AS_CANT,            // Couldn't attempt
            AS_CANT_USE_TOOL,   // Cannot use tool
            AS_CANT_YET         // Skill too low
        };
repair_type
enum repair_item_actor::repair_type : int
Enumerator
RT_NOTHING
RT_REPAIR
RT_REFIT
RT_DOWNSIZING
RT_UPSIZING
RT_REINFORCE
RT_PRACTICE
NUM_REPAIR_TYPES
Definition at line 962 of file iuse_actor.h.
                         : int {
            RT_NOTHING = 0,
            RT_REPAIR,          // Just repairing damage
            RT_REFIT,           // Refitting
            RT_DOWNSIZING,      // When small, reduce clothing to small size
            RT_UPSIZING,        // When normal, increase clothing to normal size
            RT_REINFORCE,       // Getting damage below 0
            RT_PRACTICE,        // Wanted to reinforce, but can't
            NUM_REPAIR_TYPES
        };
Constructor & Destructor Documentation
repair_item_actor()
repair_item_actor::repair_item_actor (const std::string & type = "repair_item") inline
Definition at line 997 of file iuse_actor.h.
: iuse_actor(type) {}
~repair_item_actor()
repair_item_actor::~repair_item_actor () override default
Member Function Documentation
action_description()
std::string repair_item_actor::action_description (repair_item_actor::repair_type rt) static
Describes members of repair_type enum.
Definition at line 3577 of file iuse_actor.cpp.
{
    static const std::array<std::string, NUM_REPAIR_TYPES> arr = {{
            translate_marker( "Nothing" ),
            translate_marker( "Repairing" ),
            translate_marker( "Refitting" ),
            translate_marker( "Downsizing" ),
            translate_marker( "Upsizing" ),
            translate_marker( "Reinforcing" ),
            translate_marker( "Practicing" )
        }
    };
    return _( arr[rt] );
}
References _, and translate_marker.
Referenced by activity_handlers::repair_item_finish().
can_repair_target()
bool repair_item_actor::can_repair_target (player & pl, const item & fix, bool print_msg) const
Checks if repairs on target item are possible.
Excludes checks on tool. Doesn't just estimate - should not return true if repairs are not possible or false if they are.
Definition at line 3265 of file iuse_actor.cpp.
{
    // In some rare cases (indices getting scrambled after inventory overflow)
    //  our `fix` can be a different item.
    if( fix.is_null() ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "You do not have that item!" ) );
        }
        return false;
    }
    if( fix.is_firearm() ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "That requires gunsmithing tools." ) );
        }
        return false;
    }
    if( fix.count_by_charges() || fix.has_flag( "NO_REPAIR" ) ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "You cannot repair this type of item." ) );
        }
        return false;
    }
    if( any_of( materials.begin(), materials.end(), [&fix]( const material_id & mat ) {
    return mat.obj()
               .repaired_with() == fix.typeId();
    } ) ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "This can be used to repair other items, not itself." ) );
        }
        return false;
    }
    if( !handle_components( pl, fix, print_msg, true ) ) {
        return false;
    }
    const bool can_be_refitted = fix.has_flag( "VARSIZE" );
    if( can_be_refitted && !fix.has_flag( "FIT" ) ) {
        return true;
    }
    const bool resizing_matters = fix.get_encumber( pl ) != 0;
    const bool small = pl.get_size() == MS_TINY;
    const bool can_resize = small != fix.has_flag( "UNDERSIZE" );
    if( can_be_refitted && resizing_matters && can_resize ) {
        return true;
    }
    if( fix.damage() > 0 ) {
        return true;
    }
    if( fix.damage() <= fix.min_damage() ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "Your %s is already enhanced to its maximum potential." ),
                                  fix.tname() );
        }
        return false;
    }
    if( fix.has_flag( "PRIMITIVE_RANGED_WEAPON" ) || !fix.reinforceable() ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "You cannot improve your %s any more this way." ),
                                  fix.tname() );
        }
        return false;
    }
    return true;
}
References _, player::add_msg_if_player(), item::count_by_charges(), item::damage(), item::get_encumber(), Character::get_size(), handle_components(), item::has_flag(), item::is_firearm(), item::is_null(), m_info, item::min_damage(), MS_TINY, item::reinforceable(), and item::tname().
Referenced by repair(), and activity_handlers::repair_item_finish().
can_use_tool()
bool repair_item_actor::can_use_tool (const player & p, const item & tool, bool print_msg) const
Checks if we are allowed to use the tool.
Definition at line 3039 of file iuse_actor.cpp.
{
    if( p.is_underwater() ) {
        if( print_msg ) {
            p.add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        }
        return false;
    }
    if( p.is_mounted() ) {
        if( print_msg ) {
            p.add_msg_player_or_npc( m_bad, _( "You can't do that while mounted." ),
                                     _( "<npcname> can't do that while mounted." ) );
        }
        return false;
    }
    if( !character_funcs::can_see_fine_details( p ) ) {
        if( print_msg ) {
            p.add_msg_if_player( m_info, _( "You can't see to do that!" ) );
        }
        return false;
    }
    if( !tool.units_sufficient( p ) ) {
        if( print_msg ) {
            p.add_msg_if_player( m_info, _( "Your tool does not have enough charges to do that." ) );
        }
        return false;
    }
    return true;
}
References _, player::add_msg_if_player(), player::add_msg_player_or_npc(), character_funcs::can_see_fine_details(), Character::is_mounted(), Creature::is_underwater(), m_bad, m_info, and tool.
Referenced by repair(), activity_handlers::repair_item_finish(), and use().
clone()
std::unique_ptr< iuse_actor > repair_item_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 3112 of file iuse_actor.cpp.
{
    return std::make_unique<repair_item_actor>( *this );
}
default_action()
repair_item_actor::repair_type repair_item_actor::default_action (const item & fix, int current_skill_level) const
What are we most likely trying to do with this item?
Definition at line 3385 of file iuse_actor.cpp.
{
    if( fix.damage() > 0 ) {
        return RT_REPAIR;
    }
    const bool can_be_refitted = fix.has_flag( flag_VARSIZE );
    const bool doesnt_fit = !fix.has_flag( flag_FIT );
    if( doesnt_fit && can_be_refitted ) {
        return RT_REFIT;
    }
    Character &player_character = get_player_character();
    const bool smol = player_character.get_size() == MS_TINY;
    const bool is_undersized = fix.has_flag( flag_UNDERSIZE );
    const bool is_oversized = fix.has_flag( flag_OVERSIZE );
    const bool resizing_matters = fix.get_encumber( player_character ) != 0;
    const bool too_big_while_smol = smol && !is_undersized && !is_oversized;
    if( too_big_while_smol && can_be_refitted && resizing_matters ) {
        return RT_DOWNSIZING;
    }
    const bool too_small_while_big = !smol && is_undersized && !is_oversized;
    if( too_small_while_big && can_be_refitted && resizing_matters ) {
        return RT_UPSIZING;
    }
    if( fix.damage() > fix.min_damage() ) {
        return RT_REINFORCE;
    }
    if( current_skill_level <= trains_skill_to ) {
        return RT_PRACTICE;
    }
    return RT_NOTHING;
}
References item::damage(), flag_FIT(), flag_OVERSIZE(), flag_UNDERSIZE(), flag_VARSIZE(), item::get_encumber(), get_player_character(), Character::get_size(), item::has_flag(), item::min_damage(), MS_TINY, RT_DOWNSIZING, RT_NOTHING, RT_PRACTICE, RT_REFIT, RT_REINFORCE, RT_REPAIR, RT_UPSIZING, and trains_skill_to.
Referenced by repair(), and activity_handlers::repair_item_finish().
get_name()
std::string repair_item_actor::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 3593 of file iuse_actor.cpp.
{
    const std::string mats = enumerate_as_string( materials.begin(), materials.end(),
    []( const material_id & mid ) {
        return _( mid->name() );
    } );
    return string_format( _( "Repair %s" ), mats );
}
References _, enumerate_as_string(), and string_format().
handle_components()
bool repair_item_actor::handle_components (player & pl, const item & fix, bool print_msg, bool just_check) const
Returns if components are available.
Consumes them if just_check is false.
Definition at line 3117 of file iuse_actor.cpp.
{
    // Entries valid for repaired items
    std::set<material_id> valid_entries;
    for( const auto &mat : materials ) {
        if( fix.made_of( mat ) ) {
            valid_entries.insert( mat );
        }
    }
    if( valid_entries.empty() ) {
        if( print_msg ) {
            pl.add_msg_if_player( m_info, _( "Your %s is not made of any of:" ),
                                  fix.tname() );
            for( const auto &mat_name : materials ) {
                const auto &mat = mat_name.obj();
                pl.add_msg_if_player( m_info, _( "%s (repaired using %s)" ), mat.name(),
                                      item::nname( mat.repaired_with(), 2 ) );
            }
        }
        return false;
    }
    const inventory &crafting_inv = pl.crafting_inventory();
    // Repairing or modifying items requires at least 1 repair item,
    //  otherwise number is related to size of item
    // Round up if checking, but roll if actually consuming
    // TODO: should 250_ml be part of the cost_scaling?
    const int items_needed = std::max<int>( 1, just_check ?
                                            std::ceil( fix.volume() / 250_ml * cost_scaling ) :
                                            roll_remainder( fix.volume() / 250_ml * cost_scaling ) );
    std::function<bool( const item & )> filter;
    if( fix.is_filthy() ) {
        filter = []( const item & component ) {
            return component.allow_crafting_component();
        };
    } else {
        filter = is_crafting_component;
    }
    // Go through all discovered repair items and see if we have any of them available
    std::vector<item_comp> comps;
    for( const auto &entry : valid_entries ) {
        const itype_id &component_id = entry.obj().repaired_with();
        // Certain (different!) materials are repaired with the same components (steel, iron, hard steel use scrap metal).
        // This checks avoids adding the same component twice, which is annoying to the user.
        if( std::find_if( comps.begin(), comps.end(), [&]( const item_comp & ic ) {
        return ic.type == component_id;
    } ) != comps.end() ) {
            continue;
        }
        if( item::count_by_charges( component_id ) ) {
            if( crafting_inv.has_charges( component_id, items_needed ) ) {
                comps.emplace_back( component_id, items_needed );
            }
        } else if( crafting_inv.has_amount( component_id, items_needed, false, filter ) ) {
            comps.emplace_back( component_id, items_needed );
        }
    }
    if( comps.empty() ) {
        if( print_msg ) {
            for( const auto &entry : valid_entries ) {
                const auto &mat_comp = entry.obj().repaired_with();
                pl.add_msg_if_player( m_info,
                                      _( "You don't have enough %s to do that.  Have: %d, need: %d" ),
                                      item::nname( mat_comp, 2 ),
                                      mat_comp->count_by_charges() ?
                                      crafting_inv.amount_of( mat_comp, false ) :
                                      crafting_inv.charges_of( mat_comp, items_needed ),
                                      items_needed );
            }
        }
        return false;
    }
    if( !just_check ) {
        if( comps.empty() ) {
            // This shouldn't happen - the check in can_repair_target should prevent it
            // But report it, just in case
            debugmsg( "Attempted repair with no components" );
        }
        pl.consume_items( comps, 1, filter );
    }
    return true;
}
References _, player::add_msg_if_player(), visitable< T >::amount_of(), visitable< T >::charges_of(), component, player::consume_items(), cost_scaling, item::count_by_charges(), Character::crafting_inventory(), debugmsg, visitable< T >::has_amount(), inventory::has_charges(), is_crafting_component(), item::is_filthy(), m_info, item::made_of(), item::nname(), string_id< T >::obj(), roll_remainder(), item::tname(), and item::volume().
Referenced by can_repair_target(), and repair().
load()
void repair_item_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 3017 of file iuse_actor.cpp.
{
    // Mandatory:
    for( const std::string line : obj.get_array( "materials" ) ) {
        materials.emplace( line );
    }
    // TODO: Make skill non-mandatory while still erroring on invalid skill
    const std::string skill_string = obj.get_string( "skill" );
    used_skill = skill_id( skill_string );
    if( !used_skill.is_valid() ) {
        obj.throw_error( "Invalid skill", "skill" );
    }
    cost_scaling = obj.get_float( "cost_scaling" );
    // Optional
    tool_quality = obj.get_int( "tool_quality", 0 );
    move_cost    = obj.get_int( "move_cost", 500 );
    trains_skill_to = obj.get_int( "trains_skill_to", 5 ) - 1;
}
References cost_scaling, JsonObject::get_array(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string(), string_id< T >::is_valid(), line(), move_cost, skill_id, JsonObject::throw_error(), tool_quality, trains_skill_to, and used_skill.
repair()
repair_item_actor::attempt_hint repair_item_actor::repair (player & pl, item & tool, item_location & fix) const
Attempts to repair target item with selected tool.
Definition at line 3450 of file iuse_actor.cpp.
{
    if( !can_use_tool( pl, tool, true ) ) {
        return AS_CANT_USE_TOOL;
    }
    if( !can_repair_target( pl, *fix, true ) ) {
        return AS_CANT;
    }
    const int current_skill_level = pl.get_skill_level( used_skill );
    const auto action = default_action( *fix, current_skill_level );
    const auto chance = repair_chance( pl, *fix, action );
    int practice_amount = repair_recipe_difficulty( pl, *fix, true ) / 2 + 1;
    float roll_value = rng_float( 0.0, 1.0 );
    enum roll_result {
        SUCCESS,
        FAILURE,
        NEUTRAL
    } roll;
    if( roll_value > 1.0f - chance.second ) {
        roll = FAILURE;
    } else if( roll_value < chance.first ) {
        roll = SUCCESS;
    } else {
        roll = NEUTRAL;
    }
    if( action == RT_NOTHING ) {
        pl.add_msg_if_player( m_bad, _( "You won't learn anything more by doing that." ) );
        return AS_CANT;
    }
    // If not for this if, it would spam a lot
    if( current_skill_level > trains_skill_to ) {
        practice_amount = 0;
    }
    pl.practice( used_skill, practice_amount, trains_skill_to );
    if( roll == FAILURE ) {
        return damage_item( pl, fix ) ? AS_DESTROYED : AS_FAILURE;
    }
    if( action == RT_PRACTICE ) {
        return AS_RETRY;
    }
    if( action == RT_REPAIR ) {
        if( roll == SUCCESS ) {
            const std::string startdurability = fix->durability_indicator( true );
            const auto damage = fix->damage();
            handle_components( pl, *fix, false, false );
            fix->set_damage( std::max( damage - itype::damage_scale, 0 ) );
            const std::string resultdurability = fix->durability_indicator( true );
            if( damage > itype::damage_scale ) {
                pl.add_msg_if_player( m_good, _( "You repair your %s!  ( %s-> %s)" ), fix->tname( 1, false ),
                                      startdurability, resultdurability );
            } else {
                pl.add_msg_if_player( m_good, _( "You repair your %s completely!  ( %s-> %s)" ), fix->tname( 1,
                                      false ), startdurability, resultdurability );
            }
            return AS_SUCCESS;
        }
        return AS_RETRY;
    }
    if( action == RT_REFIT ) {
        if( roll == SUCCESS ) {
            if( !fix->has_flag( "FIT" ) ) {
                pl.add_msg_if_player( m_good, _( "You take your %s in, improving the fit." ),
                                      fix->tname() );
                fix->set_flag( "FIT" );
            }
            handle_components( pl, *fix, false, false );
            return AS_SUCCESS;
        }
        return AS_RETRY;
    }
    if( action == RT_DOWNSIZING ) {
        //We don't need to check for smallness or undersize because DOWNSIZING already guarantees that
        if( roll == SUCCESS ) {
            pl.add_msg_if_player( m_good, _( "You resize the %s to accommodate your tiny build." ),
                                  fix->tname().c_str() );
            fix->set_flag( "UNDERSIZE" );
            handle_components( pl, *fix, false, false );
            return AS_SUCCESS;
        }
        return AS_RETRY;
    }
    if( action == RT_UPSIZING ) {
        //We don't need to check for smallness or undersize because UPSIZING already guarantees that
        if( roll == SUCCESS ) {
            pl.add_msg_if_player( m_good, _( "You adjust the %s back to its normal size." ),
                                  fix->tname().c_str() );
            fix->unset_flag( "UNDERSIZE" );
            handle_components( pl, *fix, false, false );
            return AS_SUCCESS;
        }
        return AS_RETRY;
    }
    if( action == RT_REINFORCE ) {
        if( fix->has_flag( "PRIMITIVE_RANGED_WEAPON" ) || !fix->reinforceable() ) {
            pl.add_msg_if_player( m_info, _( "You cannot improve your %s any more this way." ),
                                  fix->tname() );
            return AS_CANT;
        }
        if( roll == SUCCESS ) {
            pl.add_msg_if_player( m_good, _( "You make your %s extra sturdy." ), fix->tname() );
            fix->mod_damage( -itype::damage_scale );
            handle_components( pl, *fix, false, false );
            return AS_SUCCESS;
        }
        return AS_RETRY;
    }
    pl.add_msg_if_player( m_info, _( "Your %s is already enhanced." ), fix->tname() );
    return AS_CANT;
}
References _, action, player::add_msg_if_player(), AS_CANT, AS_CANT_USE_TOOL, AS_DESTROYED, AS_FAILURE, AS_RETRY, AS_SUCCESS, can_repair_target(), can_use_tool(), item::damage(), damage_item(), itype::damage_scale, default_action(), item::durability_indicator(), Character::get_skill_level(), handle_components(), item::has_flag(), m_bad, m_good, m_info, item::mod_damage(), Character::practice(), item::reinforceable(), repair_chance(), repair_recipe_difficulty(), rng_float(), RT_DOWNSIZING, RT_NOTHING, RT_PRACTICE, RT_REFIT, RT_REINFORCE, RT_REPAIR, RT_UPSIZING, item::set_damage(), item::set_flag(), item::tname(), tool, trains_skill_to, item::unset_flag(), and used_skill.
Referenced by activity_handlers::repair_item_finish().
repair_chance()
std::pair< float, float > repair_item_actor::repair_chance (const player & pl, const item & fix, repair_item_actor::repair_type action_type) const
Returns the chance to repair and to damage an item.
Tailor randomly improves clothing repair efforts Mechanics randomly improves metal repair efforts Dexterity reduces the chances of damaging an item when repairing
Definition at line 3338 of file iuse_actor.cpp.
{
    /** @EFFECT_TAILOR randomly improves clothing repair efforts */
    /** @EFFECT_MECHANICS randomly improves metal repair efforts */
    const int skill = pl.get_skill_level( used_skill );
    const int recipe_difficulty = repair_recipe_difficulty( pl, fix );
    int action_difficulty = 0;
    switch( action_type ) {
        case RT_REPAIR:
            action_difficulty = fix.damage_level( 4 );
            break;
        case RT_REFIT:
            // Let's make refitting as hard as recovering an almost-wrecked item
            action_difficulty = fix.max_damage() / itype::damage_scale;
            break;
        case RT_REINFORCE:
            // Reinforcing is at least as hard as refitting
            action_difficulty = std::max( fix.max_damage() / itype::damage_scale, recipe_difficulty );
            break;
        case RT_PRACTICE:
            // Skill gain scales with recipe difficulty, so practice difficulty should too
            action_difficulty = recipe_difficulty;
        default:
            ;
    }
    const int difficulty = recipe_difficulty + action_difficulty;
    // Sample numbers:
    // Item   | Damage | Skill | Dex | Success | Failure
    // Hoodie |    2   |   3   |  10 |   6%    |   0%
    // Hazmat |    1   |   10  |  10 |   8%    |   0%
    // Hazmat |    1   |   5   |  20 |   0%    |   2%
    // t-shirt|    4   |   1   |  5  |   2%    |   3%
    // Duster |    2   |   5   |  5  |   10%   |   0%
    // Duster |    2   |   2   |  10 |   4%    |   1%
    // Duster | Refit  |   2   |  10 |   0%    |   N/A
    float success_chance = ( 10 + 2 * skill - 2 * difficulty + tool_quality / 5.0f ) / 100.0f;
    /** @EFFECT_DEX reduces the chances of damaging an item when repairing */
    float damage_chance = ( difficulty - skill - ( tool_quality + pl.dex_cur ) / 5.0f ) / 100.0f;
    damage_chance = std::max( 0.0f, std::min( 1.0f, damage_chance ) );
    success_chance = std::max( 0.0f, std::min( 1.0f - damage_chance, success_chance ) );
    return std::make_pair( success_chance, damage_chance );
}
References item::damage_level(), itype::damage_scale, Character::dex_cur, Character::get_skill_level(), item::max_damage(), repair_recipe_difficulty(), RT_PRACTICE, RT_REFIT, RT_REINFORCE, RT_REPAIR, tool_quality, and used_skill.
Referenced by repair(), and activity_handlers::repair_item_finish().
repair_recipe_difficulty()
int repair_item_actor::repair_recipe_difficulty (const player & pl, const item & fix, bool training = false) const
Calculates the difficulty to repair an item based on recipes to craft it and player's knowledge of them.
If training is true, player's lacking knowledge and skills are not used to increase difficulty.
Definition at line 3247 of file iuse_actor.cpp.
{
    int diff = find_repair_difficulty( pl, fix.typeId(), training );
    // If we don't find a recipe, see if there's a repairs_like that has a recipe
    if( diff == -1 && !fix.type->repairs_like.is_empty() ) {
        diff = find_repair_difficulty( pl, fix.type->repairs_like, training );
    }
    // If we still don't find a recipe, difficulty is 10
    if( diff == -1 ) {
        diff = 10;
    }
    return diff;
}
References find_repair_difficulty(), string_id< T >::is_empty(), itype::repairs_like, item::type, and item::typeId().
Referenced by repair(), and repair_chance().
use()
int repair_item_actor::use (player & p, item & it, bool , const tripoint & position) const override virtual
Implements iuse_actor.
Definition at line 3097 of file iuse_actor.cpp.
{
    if( !can_use_tool( p, it, true ) ) {
        return 0;
    }
    p.assign_activity( ACT_REPAIR_ITEM, 0, p.get_item_position( &it ), INT_MIN );
    // We also need to store the repair actor subtype in the activity
    p.activity.str_values.push_back( type );
    // storing of item_location to support repairs by tools on the ground
    p.activity.targets.emplace_back( get_item_location( p, it, position ) );
    // All repairs are done in the activity, including charge cost and target item selection
    return 0;
}
References ACT_REPAIR_ITEM, Character::activity, Character::assign_activity(), can_use_tool(), get_item_location(), Character::get_item_position(), Character::position, player_activity::str_values, player_activity::targets, and iuse_actor::type.
Member Data Documentation
cost_scaling
float repair_item_actor::cost_scaling = 1.0f
Volume of materials required (and used up) as percentage of repaired item's volume.
Set to 0 to always use just 1 component.
Definition at line 946 of file iuse_actor.h.
Referenced by handle_components(), and load().
materials
std::set<material_id> repair_item_actor::materials
Materials we are allowed to repair.
Definition at line 937 of file iuse_actor.h.
Referenced by repair_inventory_preset::is_shown().
move_cost
int repair_item_actor::move_cost = 0
Move cost for every attempt.
Definition at line 950 of file iuse_actor.h.
Referenced by load(), and activity_handlers::repair_item_finish().
tool_quality
int repair_item_actor::tool_quality = 0
Extra value added to skill roll.
Definition at line 948 of file iuse_actor.h.
Referenced by load(), and repair_chance().
trains_skill_to
int repair_item_actor::trains_skill_to = 0
Maximum skill level that can be gained by using this actor.
Definition at line 941 of file iuse_actor.h.
Referenced by default_action(), load(), and repair().
used_skill
skill_id repair_item_actor::used_skill
Skill used.
Definition at line 939 of file iuse_actor.h.
Referenced by load(), repair(), repair_chance(), and activity_handlers::repair_item_finish().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp