Cataclysm BN: tileset Class Reference
tileset Class Reference
#include <cata_tiles.h>
Classes
struct season_tile_value
Public Member Functions
int get_tile_width () const
int get_tile_height () const
float get_tile_pixelscale () const
const std::string & get_tileset_id () const
const texture * get_tile (const size_t index) const
const texture * get_night_tile (const size_t index) const
const texture * get_shadow_tile (const size_t index) const
const texture * get_overexposed_tile (const size_t index) const
const texture * get_memory_tile (const size_t index) const
const texture * get_z_overlay (const size_t index) const
tile_type & create_tile_type (const std::string &id, tile_type &&new_tile_type)
const tile_type * find_tile_type (const std::string &id) const
cata::optional< tile_lookup_res > find_tile_type_by_season (const std::string &id, season_type season) const
Looks up tile by id + season suffix AND just raw id Example: if id == "t_tree_apple" and season == SPRING will first look up "t_tree_apple_season_spring" if not found, will look up "t_tree_apple" if still nothing is found, will return cata::nullopt.
Static Private Member Functions
static const texture * get_if_available (const size_t index, const decltype(shadow_tile_values) &tiles)
Private Attributes
std::string tileset_id
int tile_width
int tile_height
float tile_pixelscale
std::vector< texture > tile_values
std::vector< texture > shadow_tile_values
std::vector< texture > night_tile_values
std::vector< texture > overexposed_tile_values
std::vector< texture > memory_tile_values
std::vector< texture > z_overlay_values
std::unordered_map< std::string, tile_type > tile_ids
std::unordered_map< std::string, season_tile_value > tile_ids_by_season [season_type::NUM_SEASONS]
Friends
class tileset_loader
Detailed Description
Definition at line 111 of file cata_tiles.h.
Member Function Documentation
create_tile_type()
tile_type & tileset::create_tile_type (const std::string & id, tile_type && new_tile_type)
find_tile_type()
const tile_type * tileset::find_tile_type (const std::string & id) const
find_tile_type_by_season()
cata::optional< tile_lookup_res > tileset::find_tile_type_by_season (const std::string & id, season_type season) const
Looks up tile by id + season suffix AND just raw id Example: if id == "t_tree_apple" and season == SPRING will first look up "t_tree_apple_season_spring" if not found, will look up "t_tree_apple" if still nothing is found, will return cata::nullopt.
Parameters
id : "raw" tile id (without season suffix)
season : season suffix encoded as season_type enum
Returns
cata::nullopt if no tile is found, cata::optional with found id (e.g. "t_tree_apple_season_spring" or "t_tree_apple) and found tile.
Note: this method is guaranteed to return pointers to the keys and values stored inside the tileset::tile_ids collection. I.e. result of this method call is invalidated when the corresponding tileset is invalidated.
get_if_available()
static const texture * tileset::get_if_available (const size_t index, const decltype(shadow_tile_values) & tiles) inline static private
Definition at line 139 of file cata_tiles.h.
{
            return index < tiles.size() ? & tiles[index] : nullptr;
        }
Referenced by get_memory_tile(), get_night_tile(), get_overexposed_tile(), get_shadow_tile(), get_tile(), and get_z_overlay().
get_memory_tile()
const texture * tileset::get_memory_tile (const size_t index) const inline
Definition at line 172 of file cata_tiles.h.
{
            return get_if_available( index, memory_tile_values );
        }
References get_if_available(), and memory_tile_values.
get_night_tile()
const texture * tileset::get_night_tile (const size_t index) const inline
Definition at line 163 of file cata_tiles.h.
{
            return get_if_available( index, night_tile_values );
        }
References get_if_available(), and night_tile_values.
get_overexposed_tile()
const texture * tileset::get_overexposed_tile (const size_t index) const inline
Definition at line 169 of file cata_tiles.h.
{
            return get_if_available( index, overexposed_tile_values );
        }
References get_if_available(), and overexposed_tile_values.
get_shadow_tile()
const texture * tileset::get_shadow_tile (const size_t index) const inline
Definition at line 166 of file cata_tiles.h.
{
            return get_if_available( index, shadow_tile_values );
        }
References get_if_available(), and shadow_tile_values.
get_tile()
const texture * tileset::get_tile (const size_t index) const inline
Definition at line 160 of file cata_tiles.h.
{
            return get_if_available( index, tile_values );
        }
References get_if_available(), and tile_values.
get_tile_height()
int tileset::get_tile_height () const inline
Definition at line 150 of file cata_tiles.h.
{
            return tile_height;
        }
References tile_height.
get_tile_pixelscale()
float tileset::get_tile_pixelscale () const inline
Definition at line 153 of file cata_tiles.h.
{
            return tile_pixelscale;
        }
References tile_pixelscale.
get_tile_width()
int tileset::get_tile_width () const inline
Definition at line 147 of file cata_tiles.h.
{
            return tile_width;
        }
References tile_width.
get_tileset_id()
const std::string & tileset::get_tileset_id () const inline
Definition at line 156 of file cata_tiles.h.
{
            return tileset_id;
        }
References tileset_id.
get_z_overlay()
const texture * tileset::get_z_overlay (const size_t index) const inline
Definition at line 175 of file cata_tiles.h.
{
            return get_if_available( index, z_overlay_values );
        }
References get_if_available(), and z_overlay_values.
Friends And Related Function Documentation
tileset_loader
friend class tileset_loader friend
Definition at line 144 of file cata_tiles.h.
Member Data Documentation
memory_tile_values
std::vector<texture> tileset::memory_tile_values private
Definition at line 131 of file cata_tiles.h.
Referenced by get_memory_tile().
night_tile_values
std::vector<texture> tileset::night_tile_values private
Definition at line 129 of file cata_tiles.h.
Referenced by get_night_tile().
overexposed_tile_values
std::vector<texture> tileset::overexposed_tile_values private
Definition at line 130 of file cata_tiles.h.
Referenced by get_overexposed_tile().
shadow_tile_values
std::vector<texture> tileset::shadow_tile_values private
Definition at line 128 of file cata_tiles.h.
Referenced by get_shadow_tile().
tile_height
int tileset::tile_height private
Definition at line 122 of file cata_tiles.h.
Referenced by get_tile_height().
tile_ids
std::unordered_map<std::string, tile_type> tileset::tile_ids private
Definition at line 134 of file cata_tiles.h.
tile_ids_by_season
std::unordered_map<std::string, season_tile_value> tileset::tile_ids_by_season[season_type::NUM_SEASONS] private
Definition at line 137 of file cata_tiles.h.
tile_pixelscale
float tileset::tile_pixelscale private
Definition at line 125 of file cata_tiles.h.
Referenced by get_tile_pixelscale().
tile_values
std::vector<texture> tileset::tile_values private
Definition at line 127 of file cata_tiles.h.
Referenced by get_tile().
tile_width
int tileset::tile_width private
Definition at line 121 of file cata_tiles.h.
Referenced by get_tile_width().
tileset_id
std::string tileset::tileset_id private
Definition at line 119 of file cata_tiles.h.
Referenced by get_tileset_id().
z_overlay_values
std::vector<texture> tileset::z_overlay_values private
Definition at line 132 of file cata_tiles.h.
Referenced by get_z_overlay().
The documentation for this class was generated from the following file:
src/cata_tiles.h