Cataclysm BN: holster_actor Class Reference
holster_actor Class Reference
Holster a weapon.
#include <iuse_actor.h>
Public Member Functions
bool can_holster (const item &obj) const
Check if obj could be stored in the holster.
bool store (player &p, item &holster, item &obj) const
Store an object in the holster.
holster_actor (const std::string &type="holster")
~holster_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
units::volume max_stored_volume () const
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string holster_prompt
Prompt to use when selecting an item.
std::string holster_msg
Message to show when holstering an item.
units::volume max_volume
Maximum volume of each item that can be holstered.
units::volume min_volume
Minimum volume of each item that can be holstered or 1/3 max_volume if unspecified.
units::mass max_weight = units::mass(-1, units::mass::unit_type{})
Maximum weight of each item.
int multi = 1
Total number of items that holster can contain.
int draw_cost = INVENTORY_HANDLING_PENALTY
Base cost of accessing/storing an item.
std::vector< skill_id > skills
Guns using any of these skills can be holstered.
std::vector< std::string > flags
Items with any of these flags set can be holstered.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Holster a weapon.
Definition at line 842 of file iuse_actor.h.
Constructor & Destructor Documentation
holster_actor()
holster_actor::holster_actor (const std::string & type = "holster") inline
Definition at line 870 of file iuse_actor.h.
: iuse_actor(type) {}
~holster_actor()
holster_actor::~holster_actor () override default
Member Function Documentation
can_holster()
bool holster_actor::can_holster (const item & obj) const
Check if obj could be stored in the holster.
Definition at line 2648 of file iuse_actor.cpp.
{
    if( obj.volume() > max_volume || obj.volume() < min_volume ) {
        return false;
    }
    if( max_weight > 0_gram && obj.weight() > max_weight ) {
        return false;
    }
    if( obj.active ) {
        return false;
    }
    return std::any_of( flags.begin(), flags.end(), [&]( const std::string & f ) {
        return obj.has_flag( f );
    } ) ||
    std::find( skills.begin(), skills.end(), obj.gun_skill() ) != skills.end();
}
References item::active, detail::find(), flags, item::gun_skill(), max_volume, max_weight, min_volume, skills, item::volume(), and item::weight().
Referenced by holster_inventory_preset::is_shown().
clone()
std::unique_ptr< iuse_actor > holster_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2621 of file iuse_actor.cpp.
{
    return std::make_unique<holster_actor>( *this );
}
info()
void holster_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 2780 of file iuse_actor.cpp.
{
    std::string message = vgettext( "Can be activated to store a suitable item.",
                                    "Can be activated to store suitable items.", multi );
    dump.emplace_back( "DESCRIPTION", message );
    dump.emplace_back( "TOOL", _( "Num items: " ), "<num>", iteminfo::no_flags, multi );
    dump.emplace_back( "TOOL", _( "Item volume: Min: " ),
                       string_format( "<num> %s", volume_units_abbr() ),
                       iteminfo::is_decimal | iteminfo::no_newline | iteminfo::lower_is_better,
                       convert_volume( min_volume.value() ) );
    dump.emplace_back( "TOOL", _( "  Max: " ),
                       string_format( "<num> %s", volume_units_abbr() ),
                       iteminfo::is_decimal,
                       convert_volume( max_volume.value() ) );
    if( max_weight > 0_gram ) {
        dump.emplace_back( "TOOL", _( "Max item weight: " ),
                           string_format( _( "<num> %s" ), weight_units() ),
                           iteminfo::is_decimal,
                           convert_weight( max_weight ) );
    }
}
References _, convert_volume(), convert_weight(), iteminfo::is_decimal, iteminfo::lower_is_better, max_volume, max_weight, mapgen_defer::message, min_volume, multi, iteminfo::no_flags, iteminfo::no_newline, string_format(), units::quantity< V, U >::value(), vgettext(), volume_units_abbr(), and weight_units().
load()
void holster_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2626 of file iuse_actor.cpp.
{
    holster_prompt = obj.get_string( "holster_prompt", "" );
    holster_msg = obj.get_string( "holster_msg", "" );
    assign( obj, "max_volume", max_volume );
    if( !assign( obj, "min_volume", min_volume ) ) {
        min_volume = max_volume / 3;
    }
    assign( obj, "max_weight", max_weight );
    multi      = obj.get_int( "multi",      multi );
    draw_cost  = obj.get_int( "draw_cost",  draw_cost );
    auto tmp = obj.get_string_array( "skills" );
    std::transform( tmp.begin(), tmp.end(), std::back_inserter( skills ),
    []( const std::string & elem ) {
        return skill_id( elem );
    } );
    flags = obj.get_string_array( "flags" );
}
References assign(), draw_cost, flags, JsonObject::get_int(), JsonObject::get_string(), JsonObject::get_string_array(), holster_msg, holster_prompt, max_volume, max_weight, min_volume, multi, skills, and iexamine::transform().
max_stored_volume()
units::volume holster_actor::max_stored_volume () const
Definition at line 2803 of file iuse_actor.cpp.
{
    return max_volume * multi;
}
References max_volume, and multi.
store()
bool holster_actor::store (player & p, item & holster, item & obj) const
Store an object in the holster.
Definition at line 2665 of file iuse_actor.cpp.
{
    if( obj.is_null() || holster.is_null() ) {
        debugmsg( "Null item was passed to holster_actor" );
        return false;
    }
    // if selected item is unsuitable inform the player why not
    if( obj.volume() > max_volume ) {
        p.add_msg_if_player( m_info, _( "Your %1$s is too big to fit in your %2$s" ),
                             obj.tname(), holster.tname() );
        return false;
    }
    if( obj.volume() < min_volume ) {
        p.add_msg_if_player( m_info, _( "Your %1$s is too small to fit in your %2$s" ),
                             obj.tname(), holster.tname() );
        return false;
    }
    if( max_weight > 0_gram && obj.weight() > max_weight ) {
        p.add_msg_if_player( m_info, _( "Your %1$s is too heavy to fit in your %2$s" ),
                             obj.tname(), holster.tname() );
        return false;
    }
    if( obj.active ) {
        p.add_msg_if_player( m_info, _( "You don't think putting your %1$s in your %2$s is a good idea" ),
                             obj.tname(), holster.tname() );
        return false;
    }
    if( std::none_of( flags.begin(), flags.end(), [&]( const std::string & f ) {
    return obj.has_flag( f );
    } ) &&
    std::find( skills.begin(), skills.end(), obj.gun_skill() ) == skills.end() ) {
        p.add_msg_if_player( m_info, _( "You can't put your %1$s in your %2$s" ),
                             obj.tname(), holster.tname() );
        return false;
    }
    p.add_msg_if_player( holster_msg.empty() ? _( "You holster your %s" ) : _( holster_msg ),
                         obj.tname(), holster.tname() );
    // holsters ignore penalty effects (e.g. GRABBED) when determining number of moves to consume
    p.store( holster, obj, false, draw_cost );
    return true;
}
References _, item::active, player::add_msg_if_player(), debugmsg, draw_cost, detail::find(), flags, item::gun_skill(), game_menus::inv::holster(), holster_msg, item::is_null(), m_info, max_volume, max_weight, min_volume, skills, player::store(), item::tname(), item::volume(), and item::weight().
Referenced by use().
use()
int holster_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2714 of file iuse_actor.cpp.
{
    if( p.is_wielding( it ) ) {
        p.add_msg_if_player( _( "You need to unwield your %s before using it." ), it.tname() );
        return 0;
    }
    int pos = 0;
    std::vector<std::string> opts;
    if( static_cast<int>( it.contents.num_item_stacks() ) < multi ) {
        std::string prompt = holster_prompt.empty() ? _( "Holster item" ) : _( holster_prompt );
        opts.push_back( prompt );
        pos = -1;
    }
    std::list<item *> top_contents{ it.contents.all_items_top() };
    std::transform( top_contents.begin(), top_contents.end(), std::back_inserter( opts ),
    []( const item * elem ) {
        return string_format( _( "Draw %s" ), elem->display_name() );
    } );
    item *internal_item = nullptr;
    if( opts.size() > 1 ) {
        int ret = uilist( string_format( _( "Use %s" ), it.tname() ), opts );
        if( ret < 0 ) {
            pos = -2;
        } else {
            pos += ret;
            if( opts.size() != it.contents.num_item_stacks() ) {
                ret--;
            }
            auto iter = std::next( top_contents.begin(), ret );
            internal_item = *iter;
        }
    } else {
        internal_item = &it.contents.front();
    }
    if( pos < -1 ) {
        p.add_msg_if_player( _( "Never mind." ) );
        return 0;
    }
    if( pos >= 0 ) {
        // worn holsters ignore penalty effects (e.g. GRABBED) when determining number of moves to consume
        if( p.is_worn( it ) ) {
            p.wield_contents( it, internal_item, false, draw_cost );
        } else {
            p.wield_contents( it, internal_item );
        }
    } else {
        item_location loc = game_menus::inv::holster( p, it );
        if( !loc ) {
            p.add_msg_if_player( _( "Never mind." ) );
            return 0;
        }
        store( p, it, *loc.obtain( p ) );
    }
    return 0;
}
References _, player::add_msg_if_player(), item_contents::all_items_top(), item::contents, draw_cost, item_contents::front(), game_menus::inv::holster(), holster_prompt, Character::is_wielding(), Character::is_worn(), multi, item_contents::num_item_stacks(), item_location::obtain(), Character::pos(), pickup::prompt, cata::hash64_detail::ret, store(), string_format(), item::tname(), iexamine::transform(), and player::wield_contents().
Member Data Documentation
draw_cost
int holster_actor::draw_cost = INVENTORY_HANDLING_PENALTY
Base cost of accessing/storing an item.
Scales down to half of that with skills.
Definition at line 858 of file iuse_actor.h.
Referenced by load(), store(), and use().
flags
std::vector<std::string> holster_actor::flags
Items with any of these flags set can be holstered.
Definition at line 862 of file iuse_actor.h.
Referenced by can_holster(), load(), and store().
holster_msg
std::string holster_actor::holster_msg
Message to show when holstering an item.
Definition at line 848 of file iuse_actor.h.
Referenced by load(), and store().
holster_prompt
std::string holster_actor::holster_prompt
Prompt to use when selecting an item.
Definition at line 846 of file iuse_actor.h.
Referenced by load(), and use().
max_volume
units::volume holster_actor::max_volume
Maximum volume of each item that can be holstered.
Definition at line 850 of file iuse_actor.h.
Referenced by can_holster(), info(), load(), max_stored_volume(), and store().
max_weight
units::mass holster_actor::max_weight = units::mass(-1, units::mass::unit_type{})
Maximum weight of each item.
If unspecified no weight limit is imposed
Definition at line 854 of file iuse_actor.h.
Referenced by can_holster(), info(), load(), and store().
min_volume
units::volume holster_actor::min_volume
Minimum volume of each item that can be holstered or 1/3 max_volume if unspecified.
Definition at line 852 of file iuse_actor.h.
Referenced by can_holster(), info(), load(), and store().
multi
int holster_actor::multi = 1
Total number of items that holster can contain.
Definition at line 856 of file iuse_actor.h.
Referenced by info(), load(), max_stored_volume(), and use().
skills
std::vector<skill_id> holster_actor::skills
Guns using any of these skills can be holstered.
Definition at line 860 of file iuse_actor.h.
Referenced by can_holster(), load(), and store().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp