Cataclysm BN: drop_token_provider Class Reference
drop_token_provider Class Reference
#include <drop_token.h>
Public Member Functions
drop_token_provider ()=default
item_drop_token make_next (time_point turn)
void clear ()
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Private Attributes
time_point last_turn = calendar::before_time_starts
int last_drop = 0
Detailed Description
Definition at line 51 of file drop_token.h.
Constructor & Destructor Documentation
drop_token_provider()
drop_token_provider::drop_token_provider () default
Member Function Documentation
clear()
void drop_token_provider::clear ()
Definition at line 37 of file drop_token.cpp.
{
    last_turn = calendar::before_time_starts;
    last_drop = 0;
}
References calendar::before_time_starts, last_drop, and last_turn.
deserialize()
void drop_token_provider::deserialize (JsonIn & jsin)
Definition at line 53 of file drop_token.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.read( "last_turn", last_turn );
    jo.read( "last_drop", last_drop );
}
References JsonIn::get_object(), last_drop, last_turn, and JsonObject::read().
make_next()
item_drop_token drop_token_provider::make_next (time_point turn)
Definition at line 25 of file drop_token.cpp.
{
    if( turn != last_turn ) {
        last_turn = turn;
        last_drop = 0;
    }
    last_drop++;
    return item_drop_token{ turn, last_drop, last_drop };
}
References last_drop, last_turn, and calendar::turn.
Referenced by pickup::obtain_and_tokenize_items().
serialize()
void drop_token_provider::serialize (JsonOut & jsout) const
Definition at line 43 of file drop_token.cpp.
{
    jsout.start_object();
    jsout.member( "last_turn", last_turn );
    jsout.member( "last_drop", last_drop );
    jsout.end_object();
}
References JsonOut::end_object(), last_drop, last_turn, JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
last_drop
int drop_token_provider::last_drop = 0 private
Definition at line 55 of file drop_token.h.
Referenced by clear(), deserialize(), make_next(), and serialize().
last_turn
time_point drop_token_provider::last_turn = calendar::before_time_starts private
Definition at line 54 of file drop_token.h.
Referenced by clear(), deserialize(), make_next(), and serialize().
The documentation for this class was generated from the following files:
src/drop_token.h
src/drop_token.cpp