Cataclysm BN: cata::value_ptr< T > Class Template Reference
cata::value_ptr< T > Class Template Reference
This class is essentially a copyable unique pointer.
#include <value_ptr.h>
Public Member Functions
value_ptr ()=default
value_ptr (value_ptr &&)=default
value_ptr (T *value)
value_ptr (const value_ptr< T > &other)
value_ptr & operator= (value_ptr< T > other)
template<typename Stream = JsonOut>
void serialize (Stream &jsout) const
template<typename Stream = JsonIn>
void deserialize (Stream &jsin)
Detailed Description
template<class T>
class cata::value_ptr< T >
This class is essentially a copyable unique pointer.
Its purpose is to allow for sparse storage of data without wasting memory in classes such as itype.
Definition at line 18 of file value_ptr.h.
Constructor & Destructor Documentation
value_ptr() [1/4]
template<class T > cata::value_ptr< T >::value_ptr () default
value_ptr() [2/4]
template<class T > cata::value_ptr< T >::value_ptr (value_ptr< T > &&) default
value_ptr() [3/4]
template<class T > cata::value_ptr< T >::value_ptr (T * value) inline
Definition at line 23 of file value_ptr.h.
: std::unique_ptr<T>(value) {}
value_ptr() [4/4]
template<class T > cata::value_ptr< T >::value_ptr (const value_ptr< T > & other) inline
Definition at line 24 of file value_ptr.h.
                                               :
            std::unique_ptr<T>( other ? new T( *other ) : nullptr ) {}
References other.
Member Function Documentation
deserialize()
template<class T > template<typename Stream = JsonIn> void cata::value_ptr< T >::deserialize (Stream & jsin) inline
Definition at line 40 of file value_ptr.h.
{
            if( jsin.test_null() ) {
                this->reset();
            } else {
                this->reset( new T() );
                this->get()->deserialize( jsin );
            }
        }
References charge_removal_blacklist::get(), and ammo_effects::reset().
operator=()
template<class T > value_ptr & cata::value_ptr< T >::operator= (value_ptr< T > other) inline
Definition at line 26 of file value_ptr.h.
{
            std::unique_ptr<T>::operator=( std::move( other ) );
            return *this;
        }
References avatar_action::move(), and other.
serialize()
template<class T > template<typename Stream = JsonOut> void cata::value_ptr< T >::serialize (Stream & jsout) const inline
Definition at line 32 of file value_ptr.h.
{
            if( this->get() ) {
                this->get()->serialize( jsout );
            } else {
                jsout.write_null();
            }
        }
References charge_removal_blacklist::get().
The documentation for this class was generated from the following files:
src/item_factory.h
src/value_ptr.h