Cataclysm BN: detail::buffer< T > Class Template Reference
detail::buffer< T > Class Template Reference abstract
\rst A contiguous memory buffer with an optional growing ability.
#include <fmtlib_core.h>
Public Types
using value_type = T
using const_reference = const T &
Public Member Functions
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
T * begin () FMT_NOEXCEPT
T * end () FMT_NOEXCEPT
const T * begin () const FMT_NOEXCEPT
const T * end () const FMT_NOEXCEPT
size_t size () const FMT_NOEXCEPT
Returns the size of this buffer.
size_t capacity () const FMT_NOEXCEPT
Returns the capacity of this buffer.
T * data () FMT_NOEXCEPT
Returns a pointer to the buffer data.
const T * data () const FMT_NOEXCEPT
Returns a pointer to the buffer data.
void clear ()
Clears this buffer.
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename I >
T & operator[] (I index)
template<typename I >
const T & operator[] (I index) const
Protected Member Functions
buffer (size_t sz) FMT_NOEXCEPT
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
~buffer ()=default
void set (T *buf_data, size_t buf_capacity) FMT_NOEXCEPT
Sets the buffer data and capacity.
virtual void grow (size_t capacity)=0
Increases the buffer capacity to hold at least capacity elements.
Private Attributes
T * ptr_
size_t size_
size_t capacity_
Detailed Description
template<typename T>
class detail::buffer< T >
\rst A contiguous memory buffer with an optional growing ability.
It is an internal class and shouldn't be used directly, only via ~fmtbasic_memory_buffer. \endrst
Definition at line 709 of file fmtlib_core.h.
Member Typedef Documentation
const_reference
template<typename T > using detail::buffer< T >::const_reference = const T&
Definition at line 741 of file fmtlib_core.h.
value_type
template<typename T > using detail::buffer< T >::value_type = T
Definition at line 740 of file fmtlib_core.h.
Constructor & Destructor Documentation
buffer() [1/3]
template<typename T > detail::buffer< T >::buffer (size_t sz) inline protected
Definition at line 719 of file fmtlib_core.h.
                                     :
        size_( sz ), capacity_( sz ) {}
buffer() [2/3]
template<typename T > detail::buffer< T >::buffer (T * p = nullptr, size_t sz = 0, size_t cap = 0) inline protected
Definition at line 722 of file fmtlib_core.h.
    :
        ptr_( p ),
              size_( sz ),
        capacity_( cap ) {}
~buffer()
template<typename T > detail::buffer< T >::~buffer () protected default
buffer() [3/3]
template<typename T > detail::buffer< T >::buffer (const buffer< T > &) delete
Member Function Documentation
append()
template<typename T > template<typename U > void detail::buffer< T >::append (const U * begin, const U * end)
Appends data to the end of the buffer.
Definition at line 682 of file fmtlib_format.h.
{
    do {
        auto count = to_unsigned( end - begin );
        try_reserve( size_ + count );
        auto free_cap = capacity_ - size_;
        if( free_cap < count ) {
            count = free_cap;
        }
        std::uninitialized_copy_n( begin, count, make_checked( ptr_ + size_, count ) );
        size_ += count;
        begin += count;
    } while( begin != end );
}
References detail::count(), detail::make_checked(), and detail::to_unsigned().
begin() [1/2]
template<typename T > const T * detail::buffer< T >::begin () const inline
Definition at line 749 of file fmtlib_core.h.
{
            return ptr_;
        }
References detail::buffer< T >::ptr_.
begin() [2/2]
template<typename T > T * detail::buffer< T >::begin () inline
Definition at line 746 of file fmtlib_core.h.
{ return ptr_; }
References detail::buffer< T >::ptr_.
Referenced by detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format().
capacity()
template<typename T > size_t detail::buffer< T >::capacity () const inline
Returns the capacity of this buffer.
Definition at line 762 of file fmtlib_core.h.
{
            return capacity_;
        }
References detail::buffer< T >::capacity_.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::deallocate(), detail::iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >::grow(), basic_memory_buffer< T, SIZE, Allocator >::move(), detail::snprintf_float(), and detail::to_pointer().
clear()
template<typename T > void detail::buffer< T >::clear () inline
Clears this buffer.
Definition at line 775 of file fmtlib_core.h.
                     {
            size_ = 0;
        }
References detail::buffer< T >::size_.
data() [1/2]
template<typename T > const T * detail::buffer< T >::data () const inline
Returns a pointer to the buffer data.
Definition at line 770 of file fmtlib_core.h.
{
            return ptr_;
        }
References detail::buffer< T >::ptr_.
data() [2/2]
template<typename T > T * detail::buffer< T >::data () inline
Returns a pointer to the buffer data.
Definition at line 767 of file fmtlib_core.h.
{ return ptr_; }
References detail::buffer< T >::ptr_.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::deallocate(), detail::fallback_format(), detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format(), detail::format_float(), basic_memory_buffer< T, SIZE, Allocator >::move(), detail::int_writer< OutputIt, Char, UInt >::on_num(), detail::report_error(), detail::snprintf_float(), detail::to_pointer(), to_string(), vfprintf(), vprint(), and detail::write_buffer().
end() [1/2]
template<typename T > const T * detail::buffer< T >::end () const inline
Definition at line 752 of file fmtlib_core.h.
{
            return ptr_ + size_;
        }
References detail::buffer< T >::ptr_, and detail::buffer< T >::size_.
end() [2/2]
template<typename T > T * detail::buffer< T >::end () inline
Definition at line 747 of file fmtlib_core.h.
{ return ptr_ + size_; }
References detail::buffer< T >::ptr_, and detail::buffer< T >::size_.
Referenced by detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format().
grow()
template<typename T > virtual void detail::buffer< T >::grow (size_t capacity) protected pure virtual
Increases the buffer capacity to hold at least capacity elements.
Implemented in detail::iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >, basic_memory_buffer< T, SIZE, Allocator >, basic_memory_buffer< wchar_t >, detail::iterator_buffer< OutputIt, T, Traits >, detail::iterator_buffer< T *, T >, and detail::counting_buffer< T >.
Referenced by detail::buffer< T >::try_reserve().
operator=()
template<typename T > void detail::buffer< T >::operator= (const buffer< T > &) delete
operator[]() [1/2]
template<typename T > template<typename I > T & detail::buffer< T >::operator[] (I index) inline
Definition at line 804 of file fmtlib_core.h.
{
            return ptr_[index];
        }
References detail::index, and detail::buffer< T >::ptr_.
operator[]() [2/2]
template<typename T > template<typename I > const T & detail::buffer< T >::operator[] (I index) const inline
Definition at line 807 of file fmtlib_core.h.
{
            return ptr_[index];
        }
References detail::index, and detail::buffer< T >::ptr_.
push_back()
template<typename T > void detail::buffer< T >::push_back (const T & value) inline
Definition at line 796 of file fmtlib_core.h.
{
            try_reserve( size_ + 1 );
            ptr_[size_++] = value;
        }
References detail::buffer< T >::ptr_, detail::buffer< T >::size_, and detail::buffer< T >::try_reserve().
Referenced by detail::format_float(), detail::utf8_to_utf16::utf8_to_utf16(), and vprint().
set()
template<typename T > void detail::buffer< T >::set (T * buf_data, size_t buf_capacity) inline protected
Sets the buffer data and capacity.
Definition at line 731 of file fmtlib_core.h.
{
            ptr_ = buf_data;
            capacity_ = buf_capacity;
        }
References detail::buffer< T >::capacity_, and detail::buffer< T >::ptr_.
Referenced by basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), detail::iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >::grow(), and basic_memory_buffer< T, SIZE, Allocator >::move().
size()
template<typename T > size_t detail::buffer< T >::size () const inline
Returns the size of this buffer.
Definition at line 757 of file fmtlib_core.h.
{
            return size_;
        }
References detail::buffer< T >::size_.
Referenced by detail::iterator_buffer< OutputIt, T, Traits >::count(), detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format(), detail::format_float(), format_system_error(), detail::format_value(), detail::iterator_buffer< OutputIt, T, Traits >::grow(), basic_memory_buffer< T, SIZE, Allocator >::move(), detail::report_error(), detail::reserve(), detail::utf8_to_utf16::size(), detail::snprintf_float(), detail::to_pointer(), to_string(), vfprintf(), vprint(), and detail::write_buffer().
try_reserve()
template<typename T > void detail::buffer< T >::try_reserve (size_t new_capacity) inline
Definition at line 790 of file fmtlib_core.h.
{
            if( new_capacity > capacity_ ) {
                grow( new_capacity );
            }
        }
References detail::buffer< T >::capacity_, and detail::buffer< T >::grow().
Referenced by detail::buffer< T >::push_back(), detail::reserve(), basic_memory_buffer< T, SIZE, Allocator >::reserve(), detail::snprintf_float(), and detail::buffer< T >::try_resize().
try_resize()
template<typename T > void detail::buffer< T >::try_resize (size_t count) inline
Definition at line 781 of file fmtlib_core.h.
{
            try_reserve( count );
            size_ = count <= capacity_ ? count : capacity_;
        }
References detail::buffer< T >::capacity_, detail::count(), detail::buffer< T >::size_, and detail::buffer< T >::try_reserve().
Referenced by detail::fallback_format(), detail::format_float(), detail::format_value(), basic_memory_buffer< T, SIZE, Allocator >::resize(), detail::snprintf_float(), and detail::to_pointer().
Member Data Documentation
capacity_
template<typename T > size_t detail::buffer< T >::capacity_ private
Definition at line 714 of file fmtlib_core.h.
Referenced by detail::buffer< T >::capacity(), detail::buffer< T >::set(), detail::buffer< T >::try_reserve(), and detail::buffer< T >::try_resize().
ptr_
template<typename T > T* detail::buffer< T >::ptr_ private
Definition at line 712 of file fmtlib_core.h.
Referenced by detail::buffer< T >::begin(), detail::buffer< T >::data(), detail::buffer< T >::end(), detail::buffer< T >::operator[](), detail::buffer< T >::push_back(), and detail::buffer< T >::set().
size_
template<typename T > size_t detail::buffer< T >::size_ private
Definition at line 713 of file fmtlib_core.h.
Referenced by detail::buffer< T >::clear(), detail::buffer< T >::end(), detail::buffer< T >::push_back(), detail::buffer< T >::size(), and detail::buffer< T >::try_resize().
The documentation for this class was generated from the following files:
src/fmtlib_core.h
src/fmtlib_format.cpp
src/fmtlib_format.h