Cataclysm BN: ter_furn_data< T > Class Template Reference
ter_furn_data< T > Class Template Reference
#include <magic_ter_furn_transform.h>
Public Member Functions
ter_furn_data ()=default
ter_furn_data (const weighted_int_list< T > &list, const std::string &message, const bool message_good)
bool has_msg () const
void add_msg (const Creature &critter) const
cata::optional< T > pick () const
void load (const JsonObject &jo)
Private Attributes
weighted_int_list< T > list
std::string message
bool message_good
Detailed Description
template<class T>
class ter_furn_data< T >
Definition at line 20 of file magic_ter_furn_transform.h.
Constructor & Destructor Documentation
ter_furn_data() [1/2]
template<class T > ter_furn_data< T >::ter_furn_data () default
ter_furn_data() [2/2]
template<class T > ter_furn_data< T >::ter_furn_data (const weighted_int_list< T > & list, const std::string & message, const bool message_good) inline
Definition at line 28 of file magic_ter_furn_transform.h.
                                                 :
            list( list ), message( message ), message_good( message_good ) {}
Member Function Documentation
add_msg()
template<class T > void ter_furn_data< T >::add_msg (const Creature & critter) const
Definition at line 269 of file magic_ter_fur_transform.cpp.
{
    critter.add_msg_if_player( message_good ? m_good : m_bad, message );
}
References Creature::add_msg_if_player(), m_bad, m_good, and mapgen_defer::message.
has_msg()
template<class T > bool ter_furn_data< T >::has_msg
Definition at line 263 of file magic_ter_fur_transform.cpp.
{
    return !message.empty();
}
References mapgen_defer::message.
load()
template<class T > void ter_furn_data< T >::load (const JsonObject & jo)
Definition at line 78 of file magic_ter_fur_transform.cpp.
{
    load_transform_results( jo, "result", list );
    message = jo.get_string( "message", "" );
    message_good = jo.get_bool( "message_good", true );
}
References JsonObject::get_bool(), JsonObject::get_string(), load_transform_results(), and mapgen_defer::message.
Referenced by ter_furn_transform::load().
pick()
template<class T > cata::optional< T > ter_furn_data< T >::pick
Definition at line 253 of file magic_ter_fur_transform.cpp.
{
    const T *picked = list.pick();
    if( picked == nullptr ) {
        return cata::nullopt;
    }
    return *picked;
}
References cata::nullopt.
Member Data Documentation
list
template<class T > weighted_int_list<T> ter_furn_data< T >::list private
Definition at line 23 of file magic_ter_furn_transform.h.
message
template<class T > std::string ter_furn_data< T >::message private
Definition at line 24 of file magic_ter_furn_transform.h.
message_good
template<class T > bool ter_furn_data< T >::message_good private
Definition at line 25 of file magic_ter_furn_transform.h.
The documentation for this class was generated from the following files:
src/magic_ter_furn_transform.h
src/magic_ter_fur_transform.cpp