Cataclysm BN: weapon_category Class Reference
weapon_category Class Reference
#include <martialarts.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
const weapon_category_id & getId () const
const translation & name () const
Static Public Member Functions
static void load_weapon_categories (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< weapon_category > & get_all ()
Private Attributes
weapon_category_id id
bool was_loaded = false
translation name_
Friends
class generic_factory< weapon_category >
Detailed Description
Definition at line 25 of file martialarts.h.
Member Function Documentation
get_all()
const std::vector< weapon_category > & weapon_category::get_all () static
Definition at line 85 of file martialarts.cpp.
{
    return weapon_category_factory.get_all();
}
References anonymous_namespace{martialarts.cpp}::weapon_category_factory.
getId()
const weapon_category_id & weapon_category::getId () const inline
Definition at line 35 of file martialarts.h.
{
            return id;
        }
References id.
load()
void weapon_category::load (const JsonObject & jo, const std::string & src)
Definition at line 80 of file martialarts.cpp.
{
    mandatory( jo, was_loaded, "name", name_ );
}
References mandatory(), name_, and was_loaded.
load_weapon_categories()
void weapon_category::load_weapon_categories (const JsonObject & jo, const std::string & src) static
Definition at line 70 of file martialarts.cpp.
{
    weapon_category_factory.load( jo, src );
}
References anonymous_namespace{martialarts.cpp}::weapon_category_factory.
Referenced by DynamicDataLoader::initialize().
name()
const translation & weapon_category::name () const inline
Definition at line 39 of file martialarts.h.
{
            return name_;
        }
Referenced by cat_order::operator()().
reset()
void weapon_category::reset () static
Definition at line 75 of file martialarts.cpp.
{
    weapon_category_factory.reset();
}
References anonymous_namespace{martialarts.cpp}::weapon_category_factory.
Referenced by DynamicDataLoader::unload_data().
Friends And Related Function Documentation
generic_factory< weapon_category >
friend class generic_factory< weapon_category > friend
Definition at line 39 of file martialarts.h.
Member Data Documentation
id
weapon_category_id weapon_category::id private
Definition at line 46 of file martialarts.h.
Referenced by getId().
name_
translation weapon_category::name_ private
Definition at line 49 of file martialarts.h.
Referenced by load().
was_loaded
bool weapon_category::was_loaded = false private
Definition at line 47 of file martialarts.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/martialarts.h
src/martialarts.cpp