Cataclysm BN: overmapbuffer Class Reference
overmapbuffer Class Reference
#include <overmapbuffer.h>
Public Types
using t_point_with_note = std::pair< point_abs_omt, std::string >
using t_notes_vector = std::vector< t_point_with_note >
using t_point_with_extra = std::pair< point_abs_omt, string_id< map_extra > >
using t_extras_vector = std::vector< t_point_with_extra >
Public Member Functions
overmapbuffer ()
overmap & get (const point_abs_om &)
Uses overmap coordinates, that means x and y are directly compared with the position of the overmap.
void save ()
void clear ()
void create_custom_overmap (const point_abs_om &, overmap_special_batch &specials)
const oter_id & ter (const tripoint_abs_omt &p)
Returns the overmap terrain at the given OMT coordinates.
const oter_id & ter_existing (const tripoint_abs_omt &p)
Returns the overmap terrain at the given OMT coordinates.
void ter_set (const tripoint_abs_omt &p, const oter_id &id)
bool has_note (const tripoint_abs_omt &p)
Uses global overmap terrain coordinates.
cata::optional< int > has_note_with_danger_radius (const tripoint_abs_omt &p)
Check whether the tile has a note that's marked as dangerous.
bool is_marked_dangerous (const tripoint_abs_omt &p)
const std::string & note (const tripoint_abs_omt &p)
void add_note (const tripoint_abs_omt &, const std::string &message)
void delete_note (const tripoint_abs_omt &p)
void mark_note_dangerous (const tripoint_abs_omt &p, int radius, bool is_dangerous)
bool has_extra (const tripoint_abs_omt &p)
const string_id< map_extra > & extra (const tripoint_abs_omt &p)
void add_extra (const tripoint_abs_omt &p, const string_id< map_extra > &id)
void delete_extra (const tripoint_abs_omt &p)
bool is_explored (const tripoint_abs_omt &p)
void toggle_explored (const tripoint_abs_omt &p)
bool seen (const tripoint_abs_omt &p)
void set_seen (const tripoint_abs_omt &p, bool seen=true)
bool has_vehicle (const tripoint_abs_omt &p)
bool has_horde (const tripoint_abs_omt &p)
int get_horde_size (const tripoint_abs_omt &p)
std::vector< om_vehicle > get_vehicle (const tripoint_abs_omt &p)
const regional_settings & get_settings (const tripoint_abs_omt &p)
std::array< std::array< scent_trace, 3 >, 3 > scents_near (const tripoint_abs_omt &origin)
Accessors for horde introspection into overmaps.
scent_trace scent_at (const tripoint_abs_omt &pos)
Method to retrieve the scent at a given location.
void set_scent (const tripoint_abs_omt &loc, int strength)
Method to set a scent trace.
bool is_safe (const tripoint_abs_omt &p)
Check for any dangerous monster groups at the global overmap terrain coordinates.
void move_vehicle (vehicle *veh, const point_abs_ms &old_msp)
Move the tracking mark of the given vehicle.
void add_vehicle (vehicle *veh)
Add the vehicle to be tracked in the overmap.
void remove_camp (const basecamp &camp)
Remove basecamp.
void remove_vehicle (const vehicle *veh)
Remove the vehicle from being tracked in the overmap.
void add_camp (const basecamp &camp)
Add Basecamp to overmapbuffer.
cata::optional< basecamp * > find_camp (const point_abs_omt &p)
std::vector< shared_ptr_fast< npc > > get_npcs_near (const tripoint_abs_sm &p, int radius)
Get all npcs in a area with given radius around given central point.
std::vector< shared_ptr_fast< npc > > get_companion_mission_npcs (int range=100)
Get all (currently loaded!) npcs that have a companion mission set.
std::vector< shared_ptr_fast< npc > > get_npcs_near_omt (const tripoint_abs_omt &p, int radius)
Uses overmap terrain coordinates, this also means radius is in overmap terrain.
std::vector< shared_ptr_fast< npc > > get_npcs_near_player (int radius)
Same as get_npcs_near(int,int,int,int) but uses player position as center.
shared_ptr_fast< npc > find_npc (character_id id)
Find the npc with the given ID.
std::vector< shared_ptr_fast< npc > > get_overmap_npcs ()
Get all NPCs active on the overmap.
shared_ptr_fast< npc > remove_npc (const character_id &id)
Find npc by id and if found, erase it from the npc list and return it (or return nullptr if not found).
void insert_npc (const shared_ptr_fast< npc > &who)
Adds the npc to an overmap (based on the npcs current location) and stores it there.
std::vector< tripoint_abs_omt > find_all (const tripoint_abs_omt &origin, const omt_find_params &params)
Find all places with the specific overmap terrain type.
std::vector< tripoint_abs_omt > find_all (const tripoint_abs_omt &origin, const std::string &type, int dist, bool must_be_seen, ot_match_type match_type=ot_match_type::type, bool existing_overmaps_only=false, const cata::optional< overmap_special_id > &om_special=cata::nullopt)
tripoint_abs_omt find_random (const tripoint_abs_omt &origin, const omt_find_params &params)
Returns a random point of specific terrain type among those found in certain search radius.
tripoint_abs_omt find_random (const tripoint_abs_omt &origin, const std::string &type, int dist, bool must_be_seen, ot_match_type match_type=ot_match_type::type, bool existing_overmaps_only=false, const cata::optional< overmap_special_id > &om_special=cata::nullopt)
bool reveal (const point_abs_omt &center, int radius, int z)
Mark a square area around center on Z-level z as seen.
bool reveal (const tripoint_abs_omt &center, int radius)
bool reveal (const tripoint_abs_omt &center, int radius, const std::function< bool(const oter_id &)> &filter)
std::vector< tripoint_abs_omt > get_travel_path (const tripoint_abs_omt &src, const tripoint_abs_omt &dest, overmap_path_params params)
bool reveal_route (const tripoint_abs_omt &source, const tripoint_abs_omt &dest, const omt_route_params &params)
tripoint_abs_omt find_closest (const tripoint_abs_omt &origin, const omt_find_params &params)
Returns the closest point of terrain type.
tripoint_abs_omt find_closest (const tripoint_abs_omt &origin, const std::string &type, int radius, bool must_be_seen, ot_match_type match_type=ot_match_type::type, bool existing_overmaps_only=false, const cata::optional< overmap_special_id > &om_special=cata::nullopt)
overmap_with_local_coords get_existing_om_global (const point_abs_omt &p)
overmap_with_local_coords get_existing_om_global (const tripoint_abs_omt &p)
overmap_with_local_coords get_om_global (const point_abs_omt &p)
overmap_with_local_coords get_om_global (const tripoint_abs_omt &p)
bool has (const point_abs_om &p)
Pass global overmap coordinates (same as get).
overmap * get_existing (const point_abs_om &p)
Get an existing overmap, does not create a new one and may return NULL if the requested overmap does not exist.
bool is_omt_generated (const tripoint_abs_omt &loc)
Returns whether or not the location has been generated (e.g.
t_notes_vector get_all_notes (int z)
t_notes_vector find_notes (int z, const std::string &pattern)
t_extras_vector get_all_extras (int z)
t_extras_vector find_extras (int z, const std::string &pattern)
void signal_hordes (const tripoint_abs_sm &center, int sig_power)
Signal nearby hordes to move to given location.
void process_mongroups ()
Process nearby monstergroups (dying mostly).
void move_hordes ()
Let hordes move a step.
std::vector< mongroup * > monsters_at (const tripoint_abs_omt &p)
std::vector< mongroup * > groups_at (const tripoint_abs_sm &p)
Monster groups at p - absolute submap coordinates.
void spawn_monster (const tripoint_abs_sm &p)
Spawn monsters from the overmap onto the main map (game::m).
void despawn_monster (const monster &critter)
Despawn the monster back onto the overmap.
radio_tower_reference find_radio_station (int frequency)
Find radio station with given frequency, search an unspecified area around the current player location.
std::vector< radio_tower_reference > find_all_radio_stations ()
Find all radio stations that can be received around the current player location.
std::vector< camp_reference > get_camps_near (const tripoint_abs_sm &location, int radius)
std::vector< city_reference > get_cities_near (const tripoint_abs_sm &location, int radius)
Find all cities within the specified radius.
city_reference closest_city (const tripoint_abs_sm &center)
Find the closest city.
city_reference closest_known_city (const tripoint_abs_sm &center)
std::string get_description_at (const tripoint_abs_sm &where)
bool place_special (const overmap_special &special, const tripoint_abs_omt &p, om_direction::type dir, bool must_be_unexplored, bool force)
Place the specified overmap special directly on the map using the provided location and rotation.
bool place_special (const overmap_special_id &special_id, const tripoint_abs_omt &center, int radius)
Place the specified overmap special using the overmap's placement algorithm.
bool check_ot (const std::string &otype, ot_match_type match_type, const tripoint_abs_omt &p)
See overmap::check_ot, this uses global overmap terrain coordinates.
bool check_overmap_special_type (const overmap_special_id &id, const tripoint_abs_omt &loc)
bool check_ot_existing (const std::string &otype, ot_match_type match_type, const tripoint_abs_omt &loc)
These versions of the check_* methods will only check existing overmaps, and return false if the overmap doesn't exist.
bool check_overmap_special_type_existing (const overmap_special_id &id, const tripoint_abs_omt &loc)
std::set< tripoint_abs_omt > electric_grid_at (const tripoint_abs_omt &p)
Gets the electric grid to which a point belongs by walking along the connected tiles.
std::vector< tripoint_rel_omt > electric_grid_connectivity_at (const tripoint_abs_omt &p)
Retrieve electric grid connections from given point.
Static Public Member Functions
static std::string terrain_filename (const point_abs_om &)
static std::string player_filename (const point_abs_om &)
Private Member Functions
bool is_findable_location (const tripoint_abs_omt &location, const omt_find_params &params)
Common function used by the find_closest/all/random to determine if the location is findable based on the specified criteria.
t_notes_vector get_notes (int z, const std::string *pattern)
Get a list of notes in the (loaded) overmaps.
t_extras_vector get_extras (int z, const std::string *pattern)
Get a list of map extras in the (loaded) overmaps.
void fix_mongroups (overmap &new_overmap)
Go thorough the monster groups of the overmap and move out-of-bounds groups to the correct overmap (if it exists), also removes empty groups.
void fix_npcs (overmap &new_overmap)
Moves out-of-bounds NPCs to the overmaps they should be in.
std::vector< overmap * > get_overmaps_near (const point_abs_sm &p, int radius)
Retrieve overmaps that overlap the bounding box defined by the location and radius.
std::vector< overmap * > get_overmaps_near (const tripoint_abs_sm &location, int radius)
Private Attributes
std::unordered_map< point_abs_om, std::unique_ptr< overmap > > overmaps
std::set< point_abs_om > known_non_existing
Set of overmap coordinates of overmaps that are known to not exist on disk.
overmap * last_requested_overmap
Detailed Description
Definition at line 164 of file overmapbuffer.h.
Member Typedef Documentation
t_extras_vector
using overmapbuffer::t_extras_vector = std::vector<t_point_with_extra>
Definition at line 425 of file overmapbuffer.h.
t_notes_vector
using overmapbuffer::t_notes_vector = std::vector<t_point_with_note>
Definition at line 417 of file overmapbuffer.h.
t_point_with_extra
using overmapbuffer::t_point_with_extra = std::pair<point_abs_omt, string_id<map_extra> >
Definition at line 424 of file overmapbuffer.h.
t_point_with_note
using overmapbuffer::t_point_with_note = std::pair<point_abs_omt, std::string>
Definition at line 416 of file overmapbuffer.h.
Constructor & Destructor Documentation
overmapbuffer()
overmapbuffer::overmapbuffer ()
Definition at line 49 of file overmapbuffer.cpp.
    : last_requested_overmap( nullptr )
{
}
Member Function Documentation
add_camp()
void overmapbuffer::add_camp (const basecamp & camp)
Add Basecamp to overmapbuffer.
Definition at line 629 of file overmapbuffer.cpp.
{
    const point_abs_omt omt = camp.camp_omt_pos().xy();
    const overmap_with_local_coords om_loc = get_om_global( omt );
    om_loc.om->camps.push_back( camp );
}
References basecamp::camp_omt_pos(), overmap::camps, get_om_global(), overmap_with_local_coords::om, coords::omt, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by map::add_camp(), and game::validate_camps().
add_extra()
void overmapbuffer::add_extra (const tripoint_abs_omt & p, const string_id< map_extra > & id)
Definition at line 245 of file overmapbuffer.cpp.
{
    overmap_with_local_coords om_loc = get_om_global( p );
    om_loc.om->add_extra( om_loc.local, id );
}
References overmap::add_extra(), get_om_global(), overmap_with_local_coords::local, and overmap_with_local_coords::om.
Referenced by MapExtras::apply_function().
add_note()
void overmapbuffer::add_note (const tripoint_abs_omt & p, const std::string & message)
Definition at line 223 of file overmapbuffer.cpp.
{
    overmap_with_local_coords om_loc = get_om_global( p );
    om_loc.om->add_note( om_loc.local, message );
}
References overmap::add_note(), get_om_global(), overmap_with_local_coords::local, mapgen_defer::message, and overmap_with_local_coords::om.
Referenced by MapExtras::apply_function(), basecamp::combat_mission_return(), overmap_ui::create_note(), om_line_mark(), om_range_mark(), and game::vertical_notes().
add_vehicle()
void overmapbuffer::add_vehicle (vehicle * veh)
Add the vehicle to be tracked in the overmap.
Definition at line 610 of file overmapbuffer.cpp.
{
    const tripoint_abs_omt omt = veh->global_omt_location();
    const overmap_with_local_coords om_loc = get_existing_om_global( omt );
    if( !om_loc.om ) {
        debugmsg( "Can't find overmap for vehicle at %s", omt.to_string() );
        return;
    }
    int id = om_loc.om->vehicles.size() + 1;
    // this *should* be unique but just in case
    while( om_loc.om->vehicles.count( id ) > 0 ) {
        id++;
    }
    om_vehicle &tracked_veh = om_loc.om->vehicles[id];
    tracked_veh.p = om_loc.local.xy();
    tracked_veh.name = veh->name;
    veh->om_id = id;
}
References debugmsg, get_existing_om_global(), vehicle::global_omt_location(), base_camps::id, overmap_with_local_coords::local, om_vehicle::name, vehicle::name, overmap_with_local_coords::om, vehicle::om_id, coords::omt, om_vehicle::p, overmap::vehicles, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by veh_interact::do_rename(), move_vehicle(), game::place_vehicle_nearby(), and vehicle::toggle_tracking().
check_ot()
bool overmapbuffer::check_ot (const std::string & otype, ot_match_type match_type, const tripoint_abs_omt & p)
See overmap::check_ot, this uses global overmap terrain coordinates.
This function may create a new overmap if needed.
Definition at line 922 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( p );
    return om_loc.om->check_ot( type, match_type, om_loc.local );
}
References overmap::check_ot(), get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, and type.
Referenced by is_findable_location(), and random_house_in_city().
check_ot_existing()
bool overmapbuffer::check_ot_existing (const std::string & otype, ot_match_type match_type, const tripoint_abs_omt & loc)
These versions of the check_* methods will only check existing overmaps, and return false if the overmap doesn't exist.
They do not create new overmaps.
Definition at line 902 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_existing_om_global( loc );
    if( !om_loc ) {
        return false;
    }
    return om_loc.om->check_ot( type, match_type, om_loc.local );
}
References overmap::check_ot(), get_existing_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, and type.
Referenced by is_findable_location().
check_overmap_special_type()
bool overmapbuffer::check_overmap_special_type (const overmap_special_id & id, const tripoint_abs_omt & loc)
Definition at line 929 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( loc );
    return om_loc.om->check_overmap_special_type( id, om_loc.local );
}
References overmap::check_overmap_special_type(), get_om_global(), overmap_with_local_coords::local, and overmap_with_local_coords::om.
Referenced by is_findable_location().
check_overmap_special_type_existing()
bool overmapbuffer::check_overmap_special_type_existing (const overmap_special_id & id, const tripoint_abs_omt & loc)
Definition at line 912 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_existing_om_global( loc );
    if( !om_loc ) {
        return false;
    }
    return om_loc.om->check_overmap_special_type( id, om_loc.local );
}
References overmap::check_overmap_special_type(), get_existing_om_global(), overmap_with_local_coords::local, and overmap_with_local_coords::om.
Referenced by is_findable_location().
clear()
void overmapbuffer::clear ()
Definition at line 210 of file overmapbuffer.cpp.
{
    overmaps.clear();
    known_non_existing.clear();
    last_requested_overmap = nullptr;
}
References known_non_existing, last_requested_overmap, and overmaps.
Referenced by init::check_mods_for_errors(), game::cleanup_at_end(), main_menu::new_character_tab(), game::quickload(), game::start_game(), and main_menu::world_tab().
closest_city()
city_reference overmapbuffer::closest_city (const tripoint_abs_sm & center)
Find the closest city.
If no city is close, returns an object with city set to nullptr.
Parameters
center The center of the search, the distance for determining the closest city is calculated as distance to this point. In global submap coordinates!
Definition at line 1374 of file overmapbuffer.cpp.
{
    const auto cities = get_cities_near( center, omt_to_sm_copy( OMAPX ) );
    if( !cities.empty() ) {
        return cities.front();
    }
    return city_reference::invalid;
}
References center, get_cities_near(), city_reference::invalid, OMAPX, and omt_to_sm_copy().
Referenced by jmapgen_sign::apply(), jmapgen_graffiti::apply(), item::display_name(), get_description_at(), mission_place::near_town(), mission_util::random_house_in_closest_city(), and weather_forecast().
closest_known_city()
city_reference overmapbuffer::closest_known_city (const tripoint_abs_sm & center)
Definition at line 1385 of file overmapbuffer.cpp.
{
    const auto cities = get_cities_near( center, omt_to_sm_copy( OMAPX ) );
    const auto it = std::find_if( cities.begin(), cities.end(),
    [this]( const city_reference & elem ) {
        const tripoint_abs_omt p = project_to<coords::omt>( elem.abs_sm_pos );
        return seen( p );
    } );
    if( it != cities.end() ) {
        return *it;
    }
    return city_reference::invalid;
}
References center, get_cities_near(), city_reference::invalid, OMAPX, and omt_to_sm_copy().
Referenced by get_description_at().
create_custom_overmap()
void overmapbuffer::create_custom_overmap (const point_abs_om & p, overmap_special_batch & specials)
Definition at line 105 of file overmapbuffer.cpp.
{
    if( last_requested_overmap != nullptr ) {
        auto om_iter = overmaps.find( p );
        if( om_iter != overmaps.end() && om_iter->second.get() == last_requested_overmap ) {
            last_requested_overmap = nullptr;
        }
    }
    overmap &new_om = *( overmaps[ p ] = std::make_unique<overmap>( p ) );
    new_om.populate( specials );
}
References last_requested_overmap, overmaps, overmap::populate(), and anonymous_namespace{overmap.cpp}::specials.
Referenced by overmap::place_specials().
delete_extra()
void overmapbuffer::delete_extra (const tripoint_abs_omt & p)
Definition at line 251 of file overmapbuffer.cpp.
{
    if( has_extra( p ) ) {
        overmap_with_local_coords om_loc = get_om_global( p );
        om_loc.om->delete_extra( om_loc.local );
    }
}
References overmap::delete_extra(), get_om_global(), has_extra(), overmap_with_local_coords::local, and overmap_with_local_coords::om.
delete_note()
void overmapbuffer::delete_note (const tripoint_abs_omt & p)
Definition at line 229 of file overmapbuffer.cpp.
{
    if( has_note( p ) ) {
        overmap_with_local_coords om_loc = get_om_global( p );
        om_loc.om->delete_note( om_loc.local );
    }
}
References overmap::delete_note(), get_om_global(), has_note(), overmap_with_local_coords::local, and overmap_with_local_coords::om.
Referenced by overmap_ui::create_note(), overmap_ui::display(), overmap_ui::map_notes_callback::key(), om_line_mark(), and om_range_mark().
despawn_monster()
void overmapbuffer::despawn_monster (const monster & critter)
Despawn the monster back onto the overmap.
The monsters position (monster::pos()) is interpreted as relative to the main map.
Definition at line 1491 of file overmapbuffer.cpp.
{
    // Get absolute coordinates of the monster in map squares, translate to submap position
    // TODO: fix point types
    tripoint_abs_sm abs_sm( ms_to_sm_copy( get_map().getabs( critter.pos() ) ) );
    // Get the overmap coordinates and get the overmap, sm is now local to that overmap
    point_abs_om omp;
    tripoint_om_sm sm;
    std::tie( omp, sm ) = project_remain<coords::om>( abs_sm );
    overmap &om = get( omp );
    // Store the monster using coordinates local to the overmap.
    om.monster_map->insert( std::make_pair( sm, critter ) );
}
References get(), get_map(), ms_to_sm_copy(), coords::om, monster::pos(), and coords::sm.
Referenced by game::despawn_monster().
electric_grid_at()
std::set< tripoint_abs_omt > overmapbuffer::electric_grid_at (const tripoint_abs_omt & p)
Gets the electric grid to which a point belongs by walking along the connected tiles.
Will always return a non-empty set.
Parameters
p Overmap coordinates of the point in the grid
Definition at line 1683 of file overmapbuffer.cpp.
{
    std::set<tripoint_abs_omt> result;
    std::queue<tripoint_abs_omt> open;
    open.emplace( p );
    while( !open.empty() ) {
        // It's weired that the game takes a lot of time to copy a tripoint_abs_omt, so use reference here.
        const tripoint_abs_omt &elem = open.front();
        result.emplace( elem );
        overmap_with_local_coords omc = get_om_global( elem );
        const auto &connections_bitset = omc.om->electric_grid_connections[omc.local];
        for( size_t i = 0; i < six_cardinal_directions.size(); i++ ) {
            if( connections_bitset.test( i ) ) {
                tripoint_abs_omt other = elem + six_cardinal_directions[i];
                if( result.count( other ) == 0 ) {
                    open.emplace( other );
                }
            }
        }
        open.pop();
    }
    return result;
}
References overmap::electric_grid_connections, get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, open(), other, and six_cardinal_directions.
Referenced by overmap_ui::grids_draw_data::get_inactive(), and distribution_grid_tracker::make_distribution_grid_at().
electric_grid_connectivity_at()
std::vector< tripoint_rel_omt > overmapbuffer::electric_grid_connectivity_at (const tripoint_abs_omt & p)
Retrieve electric grid connections from given point.
Returned vector may be empty.
Definition at line 1710 of file overmapbuffer.cpp.
{
    std::vector<tripoint_rel_omt> ret;
    ret.reserve( six_cardinal_directions.size() );
    overmap_with_local_coords omc = get_om_global( p );
    const auto &connections_bitset = omc.om->electric_grid_connections[omc.local];
    for( size_t i = 0; i < six_cardinal_directions.size(); i++ ) {
        if( connections_bitset.test( i ) ) {
            ret.emplace_back( six_cardinal_directions[i] );
        }
    }
    return ret;
}
References overmap::electric_grid_connections, get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, cata::hash64_detail::ret, and six_cardinal_directions.
Referenced by iuse::report_grid_connections().
extra()
const string_id< map_extra > & overmapbuffer::extra (const tripoint_abs_omt & p)
Definition at line 381 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->extra( om_loc.local );
    }
    static const string_id<map_extra> id;
    return id;
}
References get_existing_om_global(), and base_camps::id.
Referenced by get_extras().
find_all() [1/2]
std::vector< tripoint_abs_omt > overmapbuffer::find_all (const tripoint_abs_omt & origin, const omt_find_params & params)
Find all places with the specific overmap terrain type.
The function only searches on the z-level indicated by origin. This function may create a new overmap if needed.
Parameters
origin Location of search see omt_find_params for definitions of the terms
Definition at line 1074 of file overmapbuffer.cpp.
{
    std::vector<tripoint_abs_omt> result;
    // dist == 0 means search a whole overmap diameter.
    const int min_dist = params.min_distance;
    const int max_dist = params.search_range ? params.search_range : OMAPX;
    size_t num_overmaps = overmaps.size();
    size_t counter = 0;
    for( const tripoint_abs_omt &loc : closest_points_first( origin, min_dist, max_dist ) ) {
        if( is_findable_location( loc, params ) ) {
            result.push_back( loc );
        }
        counter += 1;
        if( params.popup && ( num_overmaps != overmaps.size() || counter == 512 ) ) {
            params.popup->refresh();
            num_overmaps = overmaps.size();
            counter = 0;
        }
    }
    return result;
}
References closest_points_first(), is_findable_location(), omt_find_params::min_distance, OMAPX, overmaps, omt_find_params::popup, and omt_find_params::search_range.
Referenced by talk_function::buy_100_logs(), talk_function::buy_10_logs(), find_all(), find_random(), game::place_vehicle_nearby(), reveal_map_actor::reveal_targets(), and mission_util::target_om_ter_random().
find_all() [2/2]
std::vector< tripoint_abs_omt > overmapbuffer::find_all (const tripoint_abs_omt & origin, const std::string & type, int dist, bool must_be_seen, ot_match_type match_type = ot_match_type::type, bool existing_overmaps_only = false, const cata::optional< overmap_special_id > & om_special = cata::nullopt)
Definition at line 1101 of file overmapbuffer.cpp.
{
    const omt_find_params params = assign_params( type, dist, must_be_seen, match_type,
                                   existing_overmaps_only, om_special );
    return find_all( origin, params );
}
References assign_params(), find_all(), and type.
find_all_radio_stations()
std::vector< radio_tower_reference > overmapbuffer::find_all_radio_stations ()
Find all radio stations that can be received around the current player location.
All entries in the returned vector are valid (have a valid tower pointer).
Definition at line 1295 of file overmapbuffer.cpp.
{
    std::vector<radio_tower_reference> result;
    // TODO: fix point types
    const tripoint_abs_sm center( get_player_character().global_sm_location() );
    // perceived signal strength is distance (in submaps) - signal strength, so towers
    // further than RADIO_MAX_STRENGTH submaps away can never be received at all.
    const int radius = RADIO_MAX_STRENGTH;
    for( auto &om : get_overmaps_near( center, radius ) ) {
        for( auto &tower : om->radios ) {
            const auto rref = create_radio_tower_reference( *om, tower, center );
            if( rref.signal_strength > 0 ) {
                result.push_back( rref );
            }
        }
    }
    return result;
}
References center, create_radio_tower_reference(), get_overmaps_near(), get_player_character(), coords::om, and RADIO_MAX_STRENGTH.
Referenced by iuse::radio_on().
find_camp()
cata::optional< basecamp * > overmapbuffer::find_camp (const point_abs_omt & p)
Definition at line 1137 of file overmapbuffer.cpp.
{
    for( auto &it : overmaps ) {
        const point_abs_omt p2( p );
        for( int x2 = p2.x() - 3; x2 < p2.x() + 3; x2++ ) {
            for( int y2 = p2.y() - 3; y2 < p2.y() + 3; y2++ ) {
                if( cata::optional<basecamp *> camp = it.second->find_camp( point_abs_omt( x2, y2 ) ) ) {
                    return camp;
                }
            }
        }
    }
    return cata::nullopt;
}
References cata::nullopt, overmaps, coords::coord_point< Point, Origin, Scale >::x(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by talk_function::abandon_camp(), talk_function::assign_camp(), iexamine::bulletin_board(), talk_function::companion_choose(), npc::consume_food_from_camp(), npc::die(), faction_manager::display(), npc::faction_display(), get_basecamp(), talk_function::goto_location(), talk_function::name_mission_tabs(), map::point_within_camp(), conditional_t< T >::set_at_om_location(), talk_function::stop_guard(), npc::within_boundaries_of_camp(), and npc::worker_downtime().
find_closest() [1/2]
tripoint_abs_omt overmapbuffer::find_closest (const tripoint_abs_omt & origin, const omt_find_params & params)
Returns the closest point of terrain type.
Parameters
origin Location of search see omt_find_params for definitions of the terms
Definition at line 1010 of file overmapbuffer.cpp.
{
    // Check the origin before searching adjacent tiles!
    if( params.min_distance == 0 && is_findable_location( origin, params ) ) {
        return origin;
    }
    // By default search overmaps within a radius of 4,
    // i.e. C = current overmap, X = overmaps searched:
    // XXXXXXXXX
    // XXXXXXXXX
    // XXXXXXXXX
    // XXXXXXXXX
    // XXXXCXXXX
    // XXXXXXXXX
    // XXXXXXXXX
    // XXXXXXXXX
    // XXXXXXXXX
    //
    // See overmap::place_specials for how we attempt to insure specials are placed within this
    // range.  The actual number is 5 because 1 covers the current overmap,
    // and each additional one expends the search to the next concentric circle of overmaps.
    const int min_dist = params.min_distance;
    const int max_dist = params.search_range ? params.search_range : OMAPX * 5;
    std::vector<tripoint_abs_omt> result;
    cata::optional<int> found_dist;
    size_t num_overmaps = overmaps.size();
    size_t counter = 0;
    for( const point_abs_omt &loc_xy : closest_points_first( origin.xy(), min_dist, max_dist ) ) {
        const int dist_xy = square_dist( origin.xy(), loc_xy );
        if( found_dist && *found_dist < dist_xy ) {
            break;
        }
        for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT; z++ ) {
            const tripoint_abs_omt loc( loc_xy, z );
            const int dist = square_dist( origin, loc );
            if( found_dist && *found_dist < dist ) {
                continue;
            }
            if( is_findable_location( loc, params ) ) {
                found_dist = dist;
                result.push_back( loc );
            }
            counter += 1;
            if( params.popup && ( num_overmaps != overmaps.size() || counter == 512 ) ) {
                params.popup->refresh();
                num_overmaps = overmaps.size();
                counter = 0;
            }
        }
    }
    return random_entry( result, overmap::invalid_tripoint );
}
References closest_points_first(), overmap::invalid_tripoint, is_findable_location(), omt_find_params::min_distance, OMAPX, OVERMAP_DEPTH, OVERMAP_HEIGHT, overmaps, omt_find_params::popup, random_entry(), omt_find_params::search_range, and square_dist().
Referenced by talk_function::caravan_dist(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), talk_function::field_build_1(), talk_function::field_build_2(), talk_function::field_harvest(), talk_function::field_plant(), find_closest(), find_or_create_om_terrain(), mission_start::kill_horde_master(), mission_start::place_deposit_box(), mission_start::place_npc_software(), mission_start::reveal_lab_train_depot(), mission_util::reveal_om_ter(), mission_start::reveal_refugee_center(), mission_util::reveal_road(), talk_function::scavenging_raid_return(), npc::set_omt_destination(), and mission_util::target_closest_lab_entrance().
find_closest() [2/2]
tripoint_abs_omt overmapbuffer::find_closest (const tripoint_abs_omt & origin, const std::string & type, int radius, bool must_be_seen, ot_match_type match_type = ot_match_type::type, bool existing_overmaps_only = false, const cata::optional< overmap_special_id > & om_special = cata::nullopt)
Definition at line 1000 of file overmapbuffer.cpp.
{
    const omt_find_params params = assign_params( type, radius, must_be_seen, match_type,
                                   existing_overmaps_only, om_special );
    return find_closest( origin, params );
}
References assign_params(), find_closest(), and type.
find_extras()
t_extras_vector overmapbuffer::find_extras (int z, const std::string & pattern) inline
Definition at line 429 of file overmapbuffer.h.
{
            return get_extras( z, &pattern ); // filter with pattern
        }
References get_extras().
find_notes()
t_notes_vector overmapbuffer::find_notes (int z, const std::string & pattern) inline
Definition at line 421 of file overmapbuffer.h.
{
            return get_notes( z, &pattern ); // filter with pattern
        }
References get_notes().
find_npc()
shared_ptr_fast< npc > overmapbuffer::find_npc (character_id id)
Find the npc with the given ID.
Returns NULL if the npc could not be found. Searches all loaded overmaps.
Definition at line 1127 of file overmapbuffer.cpp.
{
    for( auto &it : overmaps ) {
        if( auto p = it.second->find_npc( id ) ) {
            return p;
        }
    }
    return nullptr;
}
References overmaps.
Referenced by basecamp::add_assignee(), basecamp::combat_mission_return(), talk_function::companion_choose(), game::disp_NPC_epilogues(), faction_manager::display(), overmap_ui::draw_ascii(), npc::find_item(), game::find_npc(), player::load(), talk_function::npc_die(), basecamp::remove_assignee(), game::reset_npc_dispositions(), basecamp::validate_assignees(), and basecamp::worker_assignment_ui().
find_radio_station()
radio_tower_reference overmapbuffer::find_radio_station (int frequency)
Find radio station with given frequency, search an unspecified area around the current player location.
If no matching tower has been found, it returns an object with the tower pointer set to null.
Definition at line 1280 of file overmapbuffer.cpp.
{
    // TODO: fix point types
    const tripoint_abs_sm center( get_player_character().global_sm_location() );
    for( auto &om : get_overmaps_near( center, RADIO_MAX_STRENGTH ) ) {
        for( auto &tower : om->radios ) {
            const auto rref = create_radio_tower_reference( *om, tower, center );
            if( rref.signal_strength > 0 && tower.frequency == frequency ) {
                return rref;
            }
        }
    }
    return radio_tower_reference{ nullptr, point_abs_sm(), 0 };
}
References center, create_radio_tower_reference(), get_overmaps_near(), get_player_character(), coords::om, and RADIO_MAX_STRENGTH.
Referenced by iuse::directional_antenna(), and iuse::radio_on().
find_random() [1/2]
tripoint_abs_omt overmapbuffer::find_random (const tripoint_abs_omt & origin, const omt_find_params & params)
Returns a random point of specific terrain type among those found in certain search radius.
This function may create new overmaps if needed.
Parameters
origin Location of search see omt_find_params for definitions of the terms
Definition at line 1111 of file overmapbuffer.cpp.
{
    return random_entry( find_all( origin, params ), overmap::invalid_tripoint );
}
References find_all(), overmap::invalid_tripoint, and random_entry().
Referenced by find_or_create_om_terrain(), find_random(), and reveal_destination().
find_random() [2/2]
tripoint_abs_omt overmapbuffer::find_random (const tripoint_abs_omt & origin, const std::string & type, int dist, bool must_be_seen, ot_match_type match_type = ot_match_type::type, bool existing_overmaps_only = false, const cata::optional< overmap_special_id > & om_special = cata::nullopt)
Definition at line 1117 of file overmapbuffer.cpp.
{
    const omt_find_params params = assign_params( type, dist, must_be_seen, match_type,
                                   existing_overmaps_only, om_special );
    return find_random( origin, params );
}
References assign_params(), find_random(), and type.
fix_mongroups()
void overmapbuffer::fix_mongroups (overmap & new_overmap) private
Go thorough the monster groups of the overmap and move out-of-bounds groups to the correct overmap (if it exists), also removes empty groups.
Definition at line 117 of file overmapbuffer.cpp.
{
    for( auto it = new_overmap.zg.begin(); it != new_overmap.zg.end(); ) {
        auto &mg = it->second;
        // spawn related code simply sets population to 0 when they have been
        // transformed into spawn points on a submap, the group can then be removed
        if( mg.empty() ) {
            new_overmap.zg.erase( it++ );
            continue;
        }
        // Inside the bounds of the overmap?
        if( mg.pos.x() >= 0 && mg.pos.y() >= 0 && mg.pos.x() < OMAPX * 2 &&
            mg.pos.y() < OMAPY * 2 ) {
            ++it;
            continue;
        }
        point_abs_sm smabs = project_combine( new_overmap.pos(), mg.pos.xy() );
        point_abs_om omp;
        point_om_sm sm_rem;
        std::tie( omp, sm_rem ) = project_remain<coords::om>( smabs );
        if( !has( omp ) ) {
            // Don't generate new overmaps, as this can be called from the
            // overmap-generating code.
            ++it;
            continue;
        }
        overmap &om = get( omp );
        mg.pos = tripoint_om_sm( sm_rem, mg.pos.z() );
        om.add_mon_group( mg );
        new_overmap.zg.erase( it++ );
    }
}
References get(), has(), coords::om, OMAPX, OMAPY, overmap::pos(), coords::project_combine(), coords::coord_point< Point, Origin, Scale >::xy(), coords::coord_point< Point, Origin, Scale >::z(), and overmap::zg.
Referenced by get().
fix_npcs()
void overmapbuffer::fix_npcs (overmap & new_overmap) private
Moves out-of-bounds NPCs to the overmaps they should be in.
Definition at line 150 of file overmapbuffer.cpp.
{
    // First step: move all npcs that are located outside of the given overmap
    // into a separate container. After that loop, new_overmap.npcs is no
    // accessed anymore!
    decltype( overmap::npcs ) to_relocate;
    for( auto it = new_overmap.npcs.begin(); it != new_overmap.npcs.end(); ) {
        npc &np = **it;
        const tripoint_abs_omt npc_omt_pos = np.global_omt_location();
        const point_abs_om npc_om_pos = project_to<coords::om>( npc_omt_pos.xy() );
        const point_abs_om loc = new_overmap.pos();
        if( npc_om_pos == loc ) {
            // Nothing to do
            ++it;
            continue;
        }
        to_relocate.push_back( *it );
        it = new_overmap.npcs.erase( it );
    }
    // Second step: put them back where they belong. This step involves loading
    // new overmaps (via `get`), which does in turn call this function for the
    // newly loaded overmaps. This in turn may move NPCs from the second overmap
    // back into the first overmap. This messes up the iteration of it. The
    // iteration is therefore done in a separate step above (which does *not*
    // involve loading new overmaps).
    for( auto &ptr : to_relocate ) {
        npc &np = *ptr;
        const tripoint_abs_omt npc_omt_pos = np.global_omt_location();
        const point_abs_om npc_om_pos = project_to<coords::om>( npc_omt_pos.xy() );
        const point_abs_om loc = new_overmap.pos();
        if( !has( npc_om_pos ) ) {
            // This can't really happen without save editing
            // We have no sane option here, just place the NPC on the edge
            debugmsg( "NPC %s is out of bounds, on non-generated overmap %s",
                      np.name, loc.to_string() );
            point_abs_sm npc_sm = project_to<coords::sm>( npc_om_pos );
            point_abs_sm min = project_to<coords::sm>( loc );
            point_abs_sm max =
                project_to<coords::sm>( loc + point_south_east ) - point_south_east;
            npc_sm.x() = clamp( npc_sm.x(), min.x(), max.x() );
            npc_sm.y() = clamp( npc_sm.y(), min.y(), max.y() );
            // TODO: fix point types
            np.spawn_at_sm( tripoint_abs_sm( npc_sm, np.posz() ).raw() );
            new_overmap.npcs.push_back( ptr );
            continue;
        }
        // Simplest case: just move the pointer
        get( npc_om_pos ).insert_npc( ptr );
    }
}
References clamp(), debugmsg, get(), Character::global_omt_location(), has(), overmap::insert_npc(), Character::name, overmap::npcs, point_south_east, overmap::pos(), Character::posz(), ptr(), coords::coord_point< Point, Origin, Scale >::raw(), npc::spawn_at_sm(), coords::coord_point< Point, Origin, Scale >::to_string(), coords::coord_point< Point, Origin, Scale >::x(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by get().
get()
overmap & overmapbuffer::get (const point_abs_om & p)
Uses overmap coordinates, that means x and y are directly compared with the position of the overmap.
Definition at line 82 of file overmapbuffer.cpp.
{
    if( last_requested_overmap != nullptr && last_requested_overmap->pos() == p ) {
        return *last_requested_overmap;
    }
    const auto it = overmaps.find( p );
    if( it != overmaps.end() ) {
        return *( last_requested_overmap = it->second.get() );
    }
    // That constructor loads an existing overmap or creates a new one.
    overmap &new_om = *( overmaps[ p ] = std::make_unique<overmap>( p ) );
    new_om.populate();
    // Note: fix_mongroups might load other overmaps, so overmaps.back() is not
    // necessarily the overmap at (x,y)
    fix_mongroups( new_om );
    fix_npcs( new_om );
    last_requested_overmap = &new_om;
    return new_om;
}
References fix_mongroups(), fix_npcs(), last_requested_overmap, overmaps, overmap::populate(), and overmap::pos().
Referenced by despawn_monster(), start_location::find_player_initial_location(), fix_mongroups(), fix_npcs(), game::get_cur_om(), get_existing(), get_om_global(), groups_at(), tutorial_game::init(), defense_game::init_map(), insert_npc(), npc::setpos(), spawn_monster(), and npc::travel_overmap().
get_all_extras()
t_extras_vector overmapbuffer::get_all_extras (int z) inline
Definition at line 426 of file overmapbuffer.h.
{
            return get_extras( z, nullptr ); // NULL => don't filter extras
        }
References get_extras().
get_all_notes()
t_notes_vector overmapbuffer::get_all_notes (int z) inline
Definition at line 418 of file overmapbuffer.h.
{
            return get_notes( z, nullptr ); // NULL => don't filter notes
        }
References get_notes().
Referenced by overmap_ui::show_notes_manager().
get_camps_near()
std::vector< camp_reference > overmapbuffer::get_camps_near (const tripoint_abs_sm & location, int radius)
Definition at line 1314 of file overmapbuffer.cpp.
{
    std::vector<camp_reference> result;
    for( const auto om : get_overmaps_near( location, radius ) ) {
        result.reserve( result.size() + om->camps.size() );
        std::transform( om->camps.begin(), om->camps.end(), std::back_inserter( result ),
        [&]( basecamp & element ) {
            const tripoint_abs_omt camp_pt = element.camp_omt_pos();
            const tripoint_abs_sm camp_sm = project_to<coords::sm>( camp_pt );
            const auto distance = rl_dist( camp_sm, location );
            return camp_reference{ &element, camp_sm, distance };
        } );
    }
    std::sort( result.begin(), result.end(), []( const camp_reference & lhs,
    const camp_reference & rhs ) {
        return lhs.get_distance_from_bounds() < rhs.get_distance_from_bounds();
    } );
    return result;
}
References get_overmaps_near(), coords::om, and iexamine::transform().
Referenced by overmap_ui::draw_camp_labels().
get_cities_near()
std::vector< city_reference > overmapbuffer::get_cities_near (const tripoint_abs_sm & location, int radius)
Find all cities within the specified radius.
Result is sorted by proximity to location in ascending order.
Definition at line 1348 of file overmapbuffer.cpp.
{
    std::vector<city_reference> result;
    for( const auto om : get_overmaps_near( location, radius ) ) {
        result.reserve( result.size() + om->cities.size() );
        std::transform( om->cities.begin(), om->cities.end(), std::back_inserter( result ),
        [&]( city & element ) {
            const auto rel_pos_city = project_to<coords::sm>( element.pos );
            const auto abs_pos_city =
                tripoint_abs_sm( project_combine( om->pos(), rel_pos_city ), 0 );
            const auto distance = rl_dist( abs_pos_city, location );
            return city_reference{ &element, abs_pos_city, distance };
        } );
    }
    std::sort( result.begin(), result.end(), []( const city_reference & lhs,
    const city_reference & rhs ) {
        return lhs.get_distance_from_bounds() < rhs.get_distance_from_bounds();
    } );
    return result;
}
References get_overmaps_near(), coords::om, and iexamine::transform().
Referenced by closest_city(), closest_known_city(), and overmap_ui::draw_city_labels().
get_companion_mission_npcs()
std::vector< shared_ptr_fast< npc > > overmapbuffer::get_companion_mission_npcs (int range = 100)
Get all (currently loaded!) npcs that have a companion mission set.
Definition at line 1220 of file overmapbuffer.cpp.
{
    std::vector<shared_ptr_fast<npc>> available;
    // TODO: this is an arbitrary radius, replace with something sane.
    for( const auto &guy : get_npcs_near_player( range ) ) {
        if( guy->has_companion_mission() ) {
            available.push_back( guy );
        }
    }
    return available;
}
References available, and get_npcs_near_player().
Referenced by basecamp::abandon_camp(), talk_function::companion_choose_return(), talk_function::companion_list(), and basecamp::reset_camp_workers().
get_description_at()
std::string overmapbuffer::get_description_at (const tripoint_abs_sm & where)
Definition at line 1401 of file overmapbuffer.cpp.
{
    const auto oter = ter( project_to<coords::omt>( where ) );
    const nc_color ter_color = oter->get_color();
    const std::string ter_name = colorize( oter->get_name(), ter_color );
    if( where.z() != 0 ) {
        return ter_name;
    }
    const auto closest_cref = closest_known_city( where );
    if( !closest_cref ) {
        return ter_name;
    }
    const auto &closest_city = *closest_cref.city;
    const std::string closest_city_name = colorize( closest_city.name, c_yellow );
    const direction dir = direction_from( closest_cref.abs_sm_pos, where );
    const std::string dir_name = colorize( direction_name( dir ), c_light_gray );
    const int sm_size = omt_to_sm_copy( closest_cref.city->size );
    const int sm_dist = closest_cref.distance;
    //~ First parameter is a terrain name, second parameter is a direction, and third parameter is a city name.
    std::string format_string = pgettext( "terrain description", "%1$s %2$s from %3$s" );
    if( sm_dist <= 3 * sm_size / 4 ) {
        if( sm_size >= 16 ) {
            // The city is big enough to be split in districts.
            if( sm_dist <= sm_size / 4 ) {
                //~ First parameter is a terrain name, second parameter is a direction, and third parameter is a city name.
                format_string = pgettext( "terrain description", "%1$s in central %3$s" );
            } else {
                //~ First parameter is a terrain name, second parameter is a direction, and third parameter is a city name.
                format_string = pgettext( "terrain description", "%1$s in %2$s %3$s" );
            }
        } else {
            //~ First parameter is a terrain name, second parameter is a direction, and third parameter is a city name.
            format_string = pgettext( "terrain description", "%1$s in %3$s" );
        }
    } else if( sm_dist <= sm_size ) {
        if( sm_size >= 8 ) {
            // The city is big enough to have outskirts.
            //~ First parameter is a terrain name, second parameter is a direction, and third parameter is a city name.
            format_string = pgettext( "terrain description", "%1$s on the %2$s outskirts of %3$s" );
        } else {
            //~ First parameter is a terrain name, second parameter is a direction, and third parameter is a city name.
            format_string = pgettext( "terrain description", "%1$s in %3$s" );
        }
    }
    return string_format( format_string, ter_name, dir_name, closest_city_name );
}
References c_light_gray, c_yellow, city_reference::city, closest_city(), closest_known_city(), colorize(), direction_from(), direction_name(), omt_to_sm_copy(), pgettext(), string_format(), ter(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by overmap_ui::draw_om_sidebar(), overmap_ui::show_notes_manager(), and memorial_logger::write().
get_existing()
overmap * overmapbuffer::get_existing (const point_abs_om & p)
Get an existing overmap, does not create a new one and may return NULL if the requested overmap does not exist.
(x,y) are global overmap coordinates (same as get).
Definition at line 259 of file overmapbuffer.cpp.
{
    if( last_requested_overmap && last_requested_overmap->pos() == p ) {
        return last_requested_overmap;
    }
    const auto it = overmaps.find( p );
    if( it != overmaps.end() ) {
        return last_requested_overmap = it->second.get();
    }
    if( known_non_existing.count( p ) > 0 ) {
        // This overmap does not exist on disk (this has already been
        // checked in a previous call of this function).
        return nullptr;
    }
    if( file_exist( terrain_filename( p ) ) ) {
        // File exists, load it normally (the get function
        // indirectly call overmap::open to do so).
        return &get( p );
    }
    // File does not exist (or not readable which is essentially
    // the same for our usage). A second call of this function with
    // the same coordinates will not check the file system, and
    // return early.
    // If the overmap had been created in the mean time, the previous
    // loop would have found and returned it.
    known_non_existing.insert( p );
    return nullptr;
}
References file_exist(), get(), known_non_existing, last_requested_overmap, overmaps, overmap::pos(), and terrain_filename().
Referenced by get_existing_om_global(), get_overmaps_near(), has(), and overmap::open().
get_existing_om_global() [1/2]
overmap_with_local_coords overmapbuffer::get_existing_om_global (const point_abs_omt & p)
Definition at line 310 of file overmapbuffer.cpp.
{
    return get_existing_om_global( tripoint_abs_omt( p, 0 ) );
}
References get_existing_om_global().
Referenced by add_vehicle(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), check_ot_existing(), check_overmap_special_type_existing(), extra(), get_existing_om_global(), get_vehicle(), has_extra(), has_note(), has_note_with_danger_radius(), has_vehicle(), is_explored(), is_marked_dangerous(), is_omt_generated(), note(), remove_vehicle(), scent_at(), overmap_ui::search(), seen(), mission_util::target_om_ter_random(), and ter_existing().
get_existing_om_global() [2/2]
overmap_with_local_coords overmapbuffer::get_existing_om_global (const tripoint_abs_omt & p)
Definition at line 316 of file overmapbuffer.cpp.
{
    point_abs_om om_pos;
    point_om_omt local;
    std::tie( om_pos, local ) = project_remain<coords::om>( p.xy() );
    overmap *om = get_existing( om_pos );
    if( om == nullptr ) {
        return overmap_with_local_coords{ nullptr, tripoint_om_omt() };
    }
    return overmap_with_local_coords{ om, tripoint_om_omt( local, p.z() ) };
}
References get_existing(), coords::om, coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
get_extras()
overmapbuffer::t_extras_vector overmapbuffer::get_extras (int z, const std::string * pattern) private
Get a list of map extras in the (loaded) overmaps.
Parameters
z only this specific z-level is search for map extras.
pattern only map extras that contain this pattern are returned. If the pattern is NULL, every map extra matches.
Definition at line 1524 of file overmapbuffer.cpp.
{
    overmapbuffer::t_extras_vector result;
    for( auto &it : overmaps ) {
        const overmap &om = *it.second;
        for( int i = 0; i < OMAPX; i++ ) {
            for( int j = 0; j < OMAPY; j++ ) {
                tripoint_om_omt p( i, j, z );
                const string_id<map_extra> &extra = om.extra( p );
                if( extra.is_null() ) {
                    continue;
                }
                const std::string &extra_text = extra.c_str();
                if( pattern != nullptr && lcmatch( extra_text, *pattern ) ) {
                    // pattern not found in note text
                    continue;
                }
                result.push_back( t_point_with_extra(
                                      project_combine( om.pos(), p.xy() ),
                                      om.extra( p )
                                  ) );
            }
        }
    }
    return result;
}
References extra(), lcmatch(), coords::om, OMAPX, OMAPY, overmaps, coords::project_combine(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by find_extras(), and get_all_extras().
get_horde_size()
int overmapbuffer::get_horde_size (const tripoint_abs_omt & p)
Definition at line 415 of file overmapbuffer.cpp.
{
    int horde_size = 0;
    for( const auto &m : overmap_buffer.monsters_at( p ) ) {
        if( m->horde ) {
            if( !m->monsters.empty() ) {
                horde_size += m->monsters.size();
            } else {
                // We don't know how large this will actually be, because
                // population "1" can still result in a zombie pack.
                // So we double the population as an estimate to make
                // hordes more likely to be visible on the overmap.
                horde_size += m->population * 2;
            }
        }
    }
    return horde_size;
}
References monsters_at(), and overmap_buffer.
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), and overmap_ui::draw_overmap_chunk().
get_notes()
overmapbuffer::t_notes_vector overmapbuffer::get_notes (int z, const std::string * pattern) private
Get a list of notes in the (loaded) overmaps.
Parameters
z only this specific z-level is search for notes.
pattern only notes that contain this pattern are returned. If the pattern is NULL, every note matches.
Definition at line 1505 of file overmapbuffer.cpp.
{
    t_notes_vector result;
    for( auto &it : overmaps ) {
        const overmap &om = *it.second;
        const auto &all_om_notes = om.all_notes( z );
        for( const om_note &note : all_om_notes ) {
            if( pattern != nullptr && lcmatch( note.text, *pattern ) ) {
                continue;
            }
            result.push_back( t_point_with_note(
                                  project_combine( it.first, note.p ),
                                  note.text
                              ) );
        }
    }
    return result;
}
References lcmatch(), note(), coords::om, overmaps, and coords::project_combine().
Referenced by find_notes(), and get_all_notes().
get_npcs_near()
std::vector< shared_ptr_fast< npc > > overmapbuffer::get_npcs_near (const tripoint_abs_sm & p, int radius)
Get all npcs in a area with given radius around given central point.
Only npcs on the given z-level are considered. Uses square_dist for distance calculation.
Parameters
p Central point in submap coordinates.
radius Maximal distance of npc from (x,y). If the npc is at most this far away from (x,y) it will be returned. A radius of 0 returns only those npcs that are on the specific submap.
Definition at line 1233 of file overmapbuffer.cpp.
{
    std::vector<shared_ptr_fast<npc>> result;
    for( auto &it : get_overmaps_near( p.xy(), radius ) ) {
        auto temp = it->get_npcs( [&]( const npc & guy ) {
            // Global position of NPC, in submap coordinates
            // TODO: fix point types
            const tripoint_abs_sm pos( guy.global_sm_location() );
            if( p.z() != INT_MIN && pos.z() != p.z() ) {
                return false;
            }
            return square_dist( p.xy(), pos.xy() ) <= radius;
        } );
        result.insert( result.end(), temp.begin(), temp.end() );
    }
    return result;
}
References get_overmaps_near(), Character::global_sm_location(), square_dist(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by get_npcs_near_player(), and map::rotate().
get_npcs_near_omt()
std::vector< shared_ptr_fast< npc > > overmapbuffer::get_npcs_near_omt (const tripoint_abs_omt & p, int radius)
Uses overmap terrain coordinates, this also means radius is in overmap terrain.
A radius of 0 returns all npcs that are on that specific overmap terrain tile.
Definition at line 1253 of file overmapbuffer.cpp.
{
    std::vector<shared_ptr_fast<npc>> result;
    for( auto &it : get_overmaps_near( project_to<coords::sm>( p.xy() ), radius ) ) {
        auto temp = it->get_npcs( [&]( const npc & guy ) {
            // Global position of NPC, in submap coordinates
            tripoint_abs_omt pos = guy.global_omt_location();
            if( p.z() != INT_MIN && pos.z() != p.z() ) {
                return false;
            }
            return square_dist( p.xy(), pos.xy() ) <= radius;
        } );
        result.insert( result.end(), temp.begin(), temp.end() );
    }
    return result;
}
References get_overmaps_near(), Character::global_omt_location(), square_dist(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
get_npcs_near_player()
std::vector< shared_ptr_fast< npc > > overmapbuffer::get_npcs_near_player (int radius)
Same as get_npcs_near(int,int,int,int) but uses player position as center.
Definition at line 1171 of file overmapbuffer.cpp.
{
    tripoint_abs_omt plpos_omt = get_player_character().global_omt_location();
    // get_npcs_near needs submap coordinates
    tripoint_abs_sm plpos = project_to<coords::sm>( plpos_omt );
    // INT_MIN is a (a bit ugly) way to inform get_npcs_near not to filter by z-level
    const int zpos = get_map().has_zlevels() ? INT_MIN : plpos.z();
    return get_npcs_near( tripoint_abs_sm( plpos.xy(), zpos ), radius );
}
References get_map(), get_npcs_near(), get_player_character(), Character::global_omt_location(), map::has_zlevels(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by game::create_starting_npcs(), game::disp_NPCs(), overmap_ui::draw_ascii(), get_companion_mission_npcs(), mission::is_complete(), game::load_npcs(), game::overmap_npc_move(), game::perhaps_add_random_npc(), Character::suffer_from_schizophrenia(), and game::validate_npc_followers().
get_om_global() [1/2]
overmap_with_local_coords overmapbuffer::get_om_global (const point_abs_omt & p)
Definition at line 294 of file overmapbuffer.cpp.
{
    return get_om_global( tripoint_abs_omt( p, 0 ) );
}
References get_om_global().
Referenced by add_camp(), add_extra(), add_note(), check_ot(), check_overmap_special_type(), delete_extra(), delete_note(), electric_grid_at(), electric_grid_connectivity_at(), get_om_global(), get_settings(), mark_note_dangerous(), move_vehicle(), place_special(), remove_camp(), overmap::set_electric_grid_connections(), set_scent(), set_seen(), ter(), ter_set(), and toggle_explored().
get_om_global() [2/2]
overmap_with_local_coords overmapbuffer::get_om_global (const tripoint_abs_omt & p)
Definition at line 300 of file overmapbuffer.cpp.
{
    point_abs_om om_pos;
    point_om_omt local;
    std::tie( om_pos, local ) = project_remain<coords::om>( p.xy() );
    overmap *om = &get( om_pos );
    return { om, tripoint_om_omt( local, p.z() ) };
}
References get(), coords::om, coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
get_overmap_npcs()
std::vector< shared_ptr_fast< npc > > overmapbuffer::get_overmap_npcs ()
Get all NPCs active on the overmap.
Definition at line 1336 of file overmapbuffer.cpp.
{
    std::vector<shared_ptr_fast<npc>> result;
    for( auto &om : overmaps ) {
        const overmap &overmap = *om.second;
        for( auto &guy : overmap.npcs ) {
            result.push_back( guy );
        }
    }
    return result;
}
References overmap::npcs, coords::om, and overmaps.
get_overmaps_near() [1/2]
std::vector< overmap * > overmapbuffer::get_overmaps_near (const point_abs_sm & p, int radius) private
Retrieve overmaps that overlap the bounding box defined by the location and radius.
The location is in absolute submap coordinates, the radius is in the same system. The overmaps are returned sorted by distance from the provided location (closest first).
Definition at line 1215 of file overmapbuffer.cpp.
{
    return get_overmaps_near( tripoint_abs_sm( p, 0 ), radius );
}
References get_overmaps_near().
Referenced by find_all_radio_stations(), find_radio_station(), get_camps_near(), get_cities_near(), get_npcs_near(), get_npcs_near_omt(), get_overmaps_near(), move_hordes(), place_special(), process_mongroups(), and signal_hordes().
get_overmaps_near() [2/2]
std::vector< overmap * > overmapbuffer::get_overmaps_near (const tripoint_abs_sm & location, int radius) private
Definition at line 1181 of file overmapbuffer.cpp.
{
    // Grab the corners of a square around the target location at distance radius.
    // Convert to overmap coordinates and iterate from the minimum to the maximum.
    const point_abs_om start =
        project_to<coords::om>( location.xy() + point( -radius, -radius ) );
    const point_abs_om end =
        project_to<coords::om>( location.xy() + point( radius, radius ) );
    const point_rel_om offset = end - start;
    std::vector<overmap *> result;
    result.reserve( ( offset.x() + 1 ) * ( offset.y() + 1 ) );
    for( int x = start.x(); x <= end.x(); ++x ) {
        for( int y = start.y(); y <= end.y(); ++y ) {
            if( overmap *existing_om = get_existing( point_abs_om( x, y ) ) ) {
                result.emplace_back( existing_om );
            }
        }
    }
    // Sort the resulting overmaps so that the closest ones are first.
    const tripoint_abs_om center = project_to<coords::om>( location );
    std::sort( result.begin(), result.end(), [&center]( const overmap * lhs,
    const overmap * rhs ) {
        const tripoint_abs_om lhs_pos( lhs->pos(), 0 );
        const tripoint_abs_om rhs_pos( rhs->pos(), 0 );
        return trig_dist( center, lhs_pos ) < trig_dist( center, rhs_pos );
    } );
    return result;
}
References center, get_existing(), coords::coord_point< Point, Origin, Scale >::x(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::y().
get_settings()
const regional_settings & overmapbuffer::get_settings (const tripoint_abs_omt & p)
Definition at line 217 of file overmapbuffer.cpp.
{
    overmap *om = get_om_global( p ).om;
    return om->get_settings();
}
References get_om_global(), coords::om, and overmap_with_local_coords::om.
Referenced by overmap_ui::get_weather_at_point().
get_travel_path()
std::vector< tripoint_abs_omt > overmapbuffer::get_travel_path (const tripoint_abs_omt & src, const tripoint_abs_omt & dest, overmap_path_params params)
Definition at line 824 of file overmapbuffer.cpp.
{
    if( src == overmap::invalid_tripoint || dest == overmap::invalid_tripoint ) {
        return {};
    }
    const pf::omt_scoring_fn estimate = [&]( tripoint_abs_omt pos ) {
        const int cur_cost = pos == src ? 0 : get_terrain_cost( pos, params );
        if( cur_cost < 0 ) {
            return pf::omt_score::rejected;
        }
        return pf::omt_score( cur_cost, is_ramp( pos ) );
    };
    constexpr int radius = 4 * OMAPX; // radius of search in OMTs = 4 overmaps
    const pf::simple_path<tripoint_abs_omt> path = pf::find_overmap_path( src, dest, radius, estimate );
    return path.points;
}
References pf::find_overmap_path(), get_terrain_cost(), overmap::invalid_tripoint, is_ramp(), OMAPX, pf::simple_path< Point >::points, and pf::omt_score::rejected.
Referenced by overmap_ui::get_overmap_path_to(), talk_function::goto_location(), game::overmap_npc_move(), and npc::set_omt_destination().
get_vehicle()
std::vector< om_vehicle > overmapbuffer::get_vehicle (const tripoint_abs_omt & p)
Definition at line 455 of file overmapbuffer.cpp.
{
    std::vector<om_vehicle> result;
    if( p.z() != 0 ) {
        return result;
    }
    const overmap_with_local_coords om_loc = get_existing_om_global( p );
    if( !om_loc ) {
        return result;
    }
    for( const auto &ov : om_loc.om->vehicles ) {
        if( ov.second.p == om_loc.local.xy() ) {
            result.push_back( ov.second );
        }
    }
    return result;
}
References get_existing_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, overmap::vehicles, coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by overmap_ui::draw_ascii().
groups_at()
std::vector< mongroup * > overmapbuffer::groups_at (const tripoint_abs_sm & p)
Monster groups at p - absolute submap coordinates.
Groups with no population are not included.
Definition at line 520 of file overmapbuffer.cpp.
{
    std::vector<mongroup *> result;
    point_om_sm sm_within_om;
    point_abs_om omp;
    std::tie( omp, sm_within_om ) = project_remain<coords::om>( p.xy() );
    if( !has( omp ) ) {
        return result;
    }
    overmap &om = get( omp );
    auto groups_range = om.zg.equal_range( tripoint_om_sm( sm_within_om, p.z() ) );
    for( auto it = groups_range.first; it != groups_range.second; ++it ) {
        mongroup &mg = it->second;
        if( mg.empty() ) {
            continue;
        }
        result.push_back( &mg );
    }
    return result;
}
References mongroup::empty(), get(), has(), coords::om, coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by monster::die(), monsters_at(), and map::spawn_monsters_submap().
has()
bool overmapbuffer::has (const point_abs_om & p)
Pass global overmap coordinates (same as get).
Returns
true if the buffer has a overmap with the given coordinates.
Definition at line 288 of file overmapbuffer.cpp.
{
    return get_existing( p ) != nullptr;
}
References get_existing().
Referenced by fix_mongroups(), fix_npcs(), groups_at(), and overmap::place_specials().
has_extra()
bool overmapbuffer::has_extra (const tripoint_abs_omt & p)
Definition at line 373 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->has_extra( om_loc.local );
    }
    return false;
}
References get_existing_om_global().
Referenced by delete_extra().
has_horde()
bool overmapbuffer::has_horde (const tripoint_abs_omt & p)
Definition at line 404 of file overmapbuffer.cpp.
{
    for( const auto &m : overmap_buffer.monsters_at( p ) ) {
        if( m->horde ) {
            return true;
        }
    }
    return false;
}
References monsters_at(), and overmap_buffer.
has_note()
bool overmapbuffer::has_note (const tripoint_abs_omt & p)
Uses global overmap terrain coordinates.
Definition at line 340 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->has_note( om_loc.local );
    }
    return false;
}
References get_existing_om_global().
Referenced by delete_note(), overmap_ui::display(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), overmap_ui::map_notes_callback::key(), mark_note_dangerous(), om_line_mark(), om_range_mark(), and game::vertical_notes().
has_note_with_danger_radius()
cata::optional< int > overmapbuffer::has_note_with_danger_radius (const tripoint_abs_omt & p)
Check whether the tile has a note that's marked as dangerous.
If such note exists, returns danger radius (may be 0).
Definition at line 348 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->has_note_with_danger_radius( om_loc.local );
    }
    return cata::nullopt;
}
References get_existing_om_global(), and cata::nullopt.
Referenced by overmap_ui::show_notes_manager().
has_vehicle()
bool overmapbuffer::has_vehicle (const tripoint_abs_omt & p)
Definition at line 435 of file overmapbuffer.cpp.
{
    if( p.z() ) {
        return false;
    }
    const overmap_with_local_coords om_loc = get_existing_om_global( p );
    if( !om_loc ) {
        return false;
    }
    for( const auto &v : om_loc.om->vehicles ) {
        if( v.second.p == om_loc.local.xy() ) {
            return true;
        }
    }
    return false;
}
References get_existing_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, overmap::vehicles, coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), and overmap_ui::draw_overmap_chunk().
insert_npc()
void overmapbuffer::insert_npc (const shared_ptr_fast< npc > & who)
Adds the npc to an overmap (based on the npcs current location) and stores it there.
The overmap takes ownership of the pointer.
Definition at line 1152 of file overmapbuffer.cpp.
{
    assert( who );
    const tripoint_abs_omt npc_omt_pos = who->global_omt_location();
    const point_abs_om npc_om_pos = project_to<coords::om>( npc_omt_pos.xy() );
    get( npc_om_pos ).insert_npc( who );
}
References get(), overmap::insert_npc(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by game::create_starting_npcs(), debug_menu::debug(), game::perhaps_add_random_npc(), map::place_npc(), basecamp::recruit_return(), map::rotate(), game::save_cyborg(), and game::spawn_hallucination().
is_explored()
bool overmapbuffer::is_explored (const tripoint_abs_omt & p)
Definition at line 390 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->is_explored( om_loc.local );
    }
    return false;
}
References get_existing_om_global().
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), and overmap_ui::draw_overmap_chunk().
is_findable_location()
bool overmapbuffer::is_findable_location (const tripoint_abs_omt & location, const omt_find_params & params) private
Common function used by the find_closest/all/random to determine if the location is findable based on the specified criteria.
Parameters
location Location of search see omt_find_params for definitions of the terms
Definition at line 955 of file overmapbuffer.cpp.
{
    bool type_matches = false;
    if( params.existing_only ) {
        for( const std::pair<std::string, ot_match_type> &elem : params.types ) {
            type_matches = check_ot_existing( elem.first, elem.second, location );
            if( type_matches ) {
                break;
            }
        }
    } else {
        for( const std::pair<std::string, ot_match_type> &elem : params.types ) {
            type_matches = check_ot( elem.first, elem.second, location );
            if( type_matches ) {
                break;
            }
        }
    }
    if( !type_matches ) {
        return false;
    }
    if( params.must_see && !seen( location ) ) {
        return false;
    }
    if( params.cant_see && seen( location ) ) {
        return false;
    }
    if( params.om_special ) {
        bool meets_om_special = false;
        if( params.existing_only ) {
            meets_om_special = check_overmap_special_type_existing( *params.om_special, location );
        } else {
            meets_om_special = check_overmap_special_type( *params.om_special, location );
        }
        if( !meets_om_special ) {
            return false;
        }
    }
    return true;
}
References omt_find_params::cant_see, check_ot(), check_ot_existing(), check_overmap_special_type(), check_overmap_special_type_existing(), omt_find_params::existing_only, omt_find_params::must_see, omt_find_params::om_special, seen(), and omt_find_params::types.
Referenced by find_all(), and find_closest().
is_marked_dangerous()
bool overmapbuffer::is_marked_dangerous (const tripoint_abs_omt & p)
Definition at line 356 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->is_marked_dangerous( om_loc.local );
    }
    return false;
}
References get_existing_om_global().
Referenced by overmap_ui::draw_ascii(), get_terrain_cost(), overmap_ui::map_notes_callback::key(), and overmap_ui::show_notes_manager().
is_omt_generated()
bool overmapbuffer::is_omt_generated (const tripoint_abs_omt & loc)
Returns whether or not the location has been generated (e.g.
mapgen has run).
Parameters
loc is in world-global omt coordinates.
Returns
True if the location has been generated.
Definition at line 329 of file overmapbuffer.cpp.
{
    if( overmap_with_local_coords om_loc = get_existing_om_global( loc ) ) {
        return om_loc.om->is_omt_generated( om_loc.local );
    }
    // If the overmap doesn't exist, then for sure the local mapgen
    // hasn't happened.
    return false;
}
References get_existing_om_global().
is_safe()
bool overmapbuffer::is_safe (const tripoint_abs_omt & p)
Check for any dangerous monster groups at the global overmap terrain coordinates.
If there are any, it's not safe.
Definition at line 1551 of file overmapbuffer.cpp.
{
    for( auto &mongrp : monsters_at( p ) ) {
        if( !mongrp->is_safe() ) {
            return false;
        }
    }
    return true;
}
References monsters_at().
Referenced by mission_start::find_safety(), and conditional_t< T >::set_at_safe_space().
mark_note_dangerous()
void overmapbuffer::mark_note_dangerous (const tripoint_abs_omt & p, int radius, bool is_dangerous)
Definition at line 237 of file overmapbuffer.cpp.
{
    if( has_note( p ) ) {
        overmap_with_local_coords om_loc = get_om_global( p );
        om_loc.om->mark_note_dangerous( om_loc.local, radius, is_dangerous );
    }
}
References get_om_global(), has_note(), overmap_with_local_coords::local, overmap::mark_note_dangerous(), and overmap_with_local_coords::om.
Referenced by overmap_ui::map_notes_callback::key().
monsters_at()
std::vector< mongroup * > overmapbuffer::monsters_at (const tripoint_abs_omt & p)
Definition at line 507 of file overmapbuffer.cpp.
{
    // (x,y) are overmap terrain coordinates, they spawn 2x2 submaps,
    // but monster groups are defined with submap coordinates.
    tripoint_abs_sm p_sm = project_to<coords::sm>( p );
    std::vector<mongroup *> result;
    for( const point &offset : std::array<point, 4> { { { point_zero }, { point_south }, { point_east }, { point_south_east } } } ) {
        std::vector<mongroup *> tmp = groups_at( p_sm + offset );
        result.insert( result.end(), tmp.begin(), tmp.end() );
    }
    return result;
}
References groups_at(), point_east, point_south, point_south_east, and point_zero.
Referenced by overmap_ui::draw_ascii(), overmap_ui::draw_om_sidebar(), get_horde_size(), has_horde(), and is_safe().
move_hordes()
void overmapbuffer::move_hordes ()
Let hordes move a step.
Note that this may move monster groups inside the reality bubble, therefore you should probably call map::spawn_monsters to spawn them.
Definition at line 496 of file overmapbuffer.cpp.
{
    // arbitrary radius to include nearby overmaps (aside from the current one)
    const auto radius = MAPSIZE * 2;
    // TODO: fix point types
    const tripoint_abs_sm center( get_player_character().global_sm_location() );
    for( auto &om : get_overmaps_near( center, radius ) ) {
        om->move_hordes();
    }
}
References center, get_overmaps_near(), get_player_character(), MAPSIZE, and coords::om.
Referenced by game::do_turn().
move_vehicle()
void overmapbuffer::move_vehicle (vehicle * veh, const point_abs_ms & old_msp)
Move the tracking mark of the given vehicle.
Parameters
veh The vehicle whose tracking device is active and that has been moved.
old_msp The previous position (before the movement) of the vehicle. In map square coordinates (see vehicle::real_global_pos), it's used to remove the vehicle from the old overmap if the new position is on another overmap.
Definition at line 571 of file overmapbuffer.cpp.
{
    const point_abs_ms new_msp = veh->global_square_location().xy();
    const point_abs_omt old_omt = project_to<coords::omt>( old_msp );
    const point_abs_omt new_omt = project_to<coords::omt>( new_msp );
    const overmap_with_local_coords old_om_loc = get_om_global( old_omt );
    const overmap_with_local_coords new_om_loc = get_om_global( new_omt );
    if( old_om_loc.om == new_om_loc.om ) {
        new_om_loc.om->vehicles[veh->om_id].p = new_om_loc.local.xy();
    } else {
        old_om_loc.om->vehicles.erase( veh->om_id );
        add_vehicle( veh );
    }
}
References add_vehicle(), get_om_global(), vehicle::global_square_location(), overmap_with_local_coords::local, overmap_with_local_coords::om, vehicle::om_id, overmap::vehicles, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by vehicle::set_submap_moved().
note()
const std::string & overmapbuffer::note (const tripoint_abs_omt & p)
Definition at line 364 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->note( om_loc.local );
    }
    static const std::string empty_string;
    return empty_string;
}
References get_existing_om_global().
Referenced by overmap_ui::create_note(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), get_notes(), overmap_ui::map_notes_callback::map_notes_callback(), om_line_mark(), and om_range_mark().
place_special() [1/2]
bool overmapbuffer::place_special (const overmap_special & special, const tripoint_abs_omt & p, om_direction::type dir, bool must_be_unexplored, bool force)
Place the specified overmap special directly on the map using the provided location and rotation.
Intended to be used when you have a special in hand, the desired location and rotation are known and the special should be directly placed rather than using the overmap's placement algorithm.
Parameters
special The overmap special to place.
p The location to place the overmap special. Absolute overmap terrain coordinates.
dir The direction to rotate the overmap special before placement.
must_be_unexplored If true, will require that all of the terrains where the special would be placed are unexplored.
force If true, placement will bypass the checks for valid placement.
Returns
True if the special was placed, else false.
Definition at line 1561 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( p );
    bool placed = false;
    // Only place this special if we can actually place it per its criteria, or we're forcing
    // the placement, which is mostly a debug behavior, since a forced placement may not function
    // correctly (e.g. won't check correct underlying terrain).
    if( om_loc.om->can_place_special(
            special, om_loc.local, dir, must_be_unexplored ) || force ) {
        // Get the closest city that is within the overmap because
        // all of the overmap generation functions only function within
        // the single overmap. If future generation is hoisted up to the
        // buffer to spawn overmaps, then this can also be changed accordingly.
        const city c = om_loc.om->get_nearest_city( om_loc.local );
        om_loc.om->place_special( special, om_loc.local, dir, c,
                                  must_be_unexplored, force );
        placed = true;
    }
    return placed;
}
References c, overmap::can_place_special(), overmap::get_nearest_city(), get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, and overmap::place_special().
Referenced by find_or_create_om_terrain(), and overmap_ui::place_ter_or_special().
place_special() [2/2]
bool overmapbuffer::place_special (const overmap_special_id & special_id, const tripoint_abs_omt & center, int radius)
Place the specified overmap special using the overmap's placement algorithm.
Intended to be used when you have a special that you want placed but it should be placed similarly to as if it were created during overmap generation.
Parameters
special_id The id of overmap special to place.
center Used in conjunction with radius to search the specified and adjacent overmaps for a valid placement location. Absolute overmap terrain coordinates.
radius Used in conjunction with center. Absolute overmap terrain units.
Returns
True if the special was placed, else false.
Definition at line 1586 of file overmapbuffer.cpp.
{
    // First find the requested special. If it doesn't exist, we're done here.
    bool found = false;
    overmap_special special;
    for( const auto &elem : overmap_specials::get_all() ) {
        if( elem.id == special_id ) {
            special = elem;
            found = true;
            break;
        }
    }
    if( !found ) {
        return false;
    }
    // Force our special to occur just once when we're spawning it here.
    special.occurrences.min = 1;
    special.occurrences.max = 1;
    // Figure out the longest side of the special for purposes of determining our sector size
    // when attempting placements.
    const auto calculate_longest_side = [&special]() {
        auto min_max_x = std::minmax_element( special.terrains.begin(),
                                              special.terrains.end(), []( const overmap_special_terrain & lhs,
        const overmap_special_terrain & rhs ) {
            return lhs.p.x < rhs.p.x;
        } );
        auto min_max_y = std::minmax_element( special.terrains.begin(),
                                              special.terrains.end(), []( const overmap_special_terrain & lhs,
        const overmap_special_terrain & rhs ) {
            return lhs.p.y < rhs.p.y;
        } );
        const int special_longest_side = std::max( min_max_x.second->p.x - min_max_x.first->p.x,
                                         min_max_y.second->p.y - min_max_y.first->p.y ) + 1;
        // If our longest side is greater than the OMSPEC_FREQ, just use that instead.
        return std::min( special_longest_side, OMSPEC_FREQ );
    };
    const int longest_side = calculate_longest_side();
    // Predefine our sectors to search in.
    om_special_sectors sectors = get_sectors( longest_side );
    // Get all of the overmaps within the defined radius of the center.
    for( const auto &om : get_overmaps_near(
             project_to<coords::sm>( center ), omt_to_sm_copy( radius ) ) ) {
        // Build an overmap_special_batch for the special on this overmap.
        std::vector<const overmap_special *> specials;
        specials.push_back( &special );
        overmap_special_batch batch( om->pos(), specials );
        // Filter the sectors to those which are in in range of our center point, so
        // that we don't end up creating specials in areas that are outside of our radius,
        // since the whole point is to create a special that is within the parameters.
        std::vector<point_om_omt> sector_points_in_range;
        std::copy_if( sectors.sectors.begin(), sectors.sectors.end(),
        std::back_inserter( sector_points_in_range ), [&]( point_om_omt & p ) {
            const point_abs_omt global_sector_point = project_combine( om->pos(), p );
            // We'll include this sector if it's within our radius. We reduce the radius by
            // the length of the longest side of our special so that we don't end up in a
            // scenario where one overmap terrain of the special is within the radius but the
            // rest of it is outside the radius (due to size, rotation, etc), which would
            // then result in us placing the special but then not finding it later if we
            // search using the same radius value we used in placing it.
            return square_dist( global_sector_point, center.xy() ) <= radius - longest_side;
        } );
        om_special_sectors sectors_in_range {sector_points_in_range, sectors.sector_width};
        // Attempt to place the specials using our batch and sectors. We
        // require they be placed in unexplored terrain right now.
        om->place_specials_pass( batch, sectors_in_range, true, true );
        // The place special pass will erase specials that have reached their
        // maximum number of instances so first check if its been erased.
        if( batch.empty() ) {
            return true;
        }
        // Hasn't been erased, so lets check placement counts.
        for( const auto &special_placement : batch ) {
            if( special_placement.instances_placed > 0 ) {
                // It was placed, lets get outta here.
                return true;
            }
        }
    }
    // If we got this far, we've failed to make the placement.
    return false;
}
References center, overmap_special_batch::empty(), overmap_specials::get_all(), get_overmaps_near(), get_sectors(), overmap_special::occurrences, coords::om, OMSPEC_FREQ, omt_to_sm_copy(), om_special_sectors::sector_width, om_special_sectors::sectors, anonymous_namespace{overmap.cpp}::specials, and overmap_special::terrains.
player_filename()
std::string overmapbuffer::player_filename (const point_abs_om & p) static
Definition at line 77 of file overmapbuffer.cpp.
{
    return string_format( "%s.seen.%d.%d", g->get_player_base_save_path(), p.x(), p.y() );
}
References g, string_format(), coords::coord_point< Point, Origin, Scale >::x(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by overmap::open(), and overmap::save().
process_mongroups()
void overmapbuffer::process_mongroups ()
Process nearby monstergroups (dying mostly).
Definition at line 485 of file overmapbuffer.cpp.
{
    // arbitrary radius to include nearby overmaps (aside from the current one)
    const auto radius = MAPSIZE * 2;
    // TODO: fix point types
    const tripoint_abs_sm center( get_player_character().global_sm_location() );
    for( auto &om : get_overmaps_near( center, radius ) ) {
        om->process_mongroups();
    }
}
References center, get_overmaps_near(), get_player_character(), MAPSIZE, and coords::om.
Referenced by game::do_turn().
remove_camp()
void overmapbuffer::remove_camp (const basecamp & camp)
Remove basecamp.
Definition at line 586 of file overmapbuffer.cpp.
{
    const point_abs_omt omt = camp.camp_omt_pos().xy();
    const overmap_with_local_coords om_loc = get_om_global( omt );
    std::vector<basecamp> &camps = om_loc.om->camps;
    for( auto it = camps.begin(); it != camps.end(); ++it ) {
        if( it->camp_omt_pos().xy() == omt ) {
            camps.erase( it );
            return;
        }
    }
}
References basecamp::camp_omt_pos(), overmap::camps, get_om_global(), overmap_with_local_coords::om, coords::omt, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by basecamp::abandon_camp().
remove_npc()
shared_ptr_fast< npc > overmapbuffer::remove_npc (const character_id & id)
Find npc by id and if found, erase it from the npc list and return it (or return nullptr if not found).
Definition at line 1160 of file overmapbuffer.cpp.
{
    for( auto &it : overmaps ) {
        if( const auto p = it.second->erase_npc( id ) ) {
            return p;
        }
    }
    debugmsg( "overmapbuffer::remove_npc: NPC (%d) not found.", id.get_value() );
    return nullptr;
}
References debugmsg, and overmaps.
Referenced by talk_function::caravan_return(), talk_function::carpenter_return(), game::cleanup_dead(), basecamp::combat_mission_return(), talk_function::forage_return(), map::rotate(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), and survive_random_encounter().
remove_vehicle()
void overmapbuffer::remove_vehicle (const vehicle * veh)
Remove the vehicle from being tracked in the overmap.
Definition at line 599 of file overmapbuffer.cpp.
{
    const tripoint_abs_omt omt = veh->global_omt_location();
    const overmap_with_local_coords om_loc = get_existing_om_global( omt );
    if( !om_loc.om ) {
        debugmsg( "Can't find overmap for vehicle at %s", omt.to_string() );
        return;
    }
    om_loc.om->vehicles.erase( veh->om_id );
}
References debugmsg, get_existing_om_global(), vehicle::global_omt_location(), overmap_with_local_coords::om, vehicle::om_id, coords::omt, and overmap::vehicles.
Referenced by map::detach_vehicle(), veh_interact::do_rename(), map::loadn(), and vehicle::toggle_tracking().
reveal() [1/3]
bool overmapbuffer::reveal (const point_abs_omt & center, int radius, int z)
Mark a square area around center on Z-level z as seen.
Parameters
center is in absolute overmap terrain coordinates.
radius The half size of the square to make visible. A value of 0 makes only center visible, radius 1 makes a square 3x3 visible.
z Z level to make area on
Returns
true if something has actually been revealed.
Definition at line 672 of file overmapbuffer.cpp.
{
    return reveal( tripoint_abs_omt( center, z ), radius );
}
References center, and reveal().
Referenced by computer_session::action_maps(), iuse::artifact(), mission_util::assign_mission_target(), basecamp::combat_mission_return(), mission_util::get_om_terrain_pos(), mission_start::kill_horde_master(), spell_effect::map_area(), om_set_hide_site(), mission_start::place_deposit_box(), mission_start::place_dog(), mission_start::place_npc_software(), mission_start::place_priest_diary(), mission_start::place_zombie_mom(), reveal(), reveal_destination(), mission_util::reveal_om_ter(), reveal_route(), reveal_map_actor::reveal_targets(), talk_function::scavenging_raid_return(), game::start_game(), mission_util::target_closest_lab_entrance(), mission_util::target_om_ter_random(), and activity_handlers::tree_communion_do_turn().
reveal() [2/3]
bool overmapbuffer::reveal (const tripoint_abs_omt & center, int radius)
Definition at line 677 of file overmapbuffer.cpp.
{
    return reveal( center, radius, []( const oter_id & ) {
        return true;
    } );
}
References center, and reveal().
reveal() [3/3]
bool overmapbuffer::reveal (const tripoint_abs_omt & center, int radius, const std::function< bool(const oter_id &)> & filter)
Definition at line 684 of file overmapbuffer.cpp.
{
    int radius_squared = radius * radius;
    bool result = false;
    for( int i = -radius; i <= radius; i++ ) {
        for( int j = -radius; j <= radius; j++ ) {
            const tripoint_abs_omt p = center + point( i, j );
            if( seen( p ) ) {
                continue;
            }
            if( trigdist && i * i + j * j > radius_squared ) {
                continue;
            }
            if( !filter( ter( p ) ) ) {
                continue;
            }
            result = true;
            set_seen( p, true );
        }
    }
    return result;
}
References center, seen(), set_seen(), ter(), and trigdist.
reveal_route()
bool overmapbuffer::reveal_route (const tripoint_abs_omt & source, const tripoint_abs_omt & dest, const omt_route_params & params)
Definition at line 844 of file overmapbuffer.cpp.
{
    // Maximal radius of search (in overmaps)
    static const int RADIUS = 4;
    // half-size of the area to search in
    static const point_rel_omt O( RADIUS * OMAPX, RADIUS * OMAPY );
    if( source == overmap::invalid_tripoint || dest == overmap::invalid_tripoint ) {
        return false;
    }
    // Local source - center of the local area
    const point_rel_omt start( O );
    // To convert local coordinates to global ones
    const tripoint_abs_omt base = source - start;
    // Local destination - relative to base
    const point_rel_omt finish = ( dest - base ).xy();
    const auto get_ter_at = [&]( const point_rel_omt & p ) {
        return ter( base + p );
    };
    const oter_id oter = get_ter_at( start );
    const auto connection = overmap_connections::guess_for( oter );
    if( !connection ) {
        return false;
    }
    const pf::two_node_scoring_fn<point_rel_omt> estimate =
    [&]( pf::directed_node<point_rel_omt> cur, cata::optional<pf::directed_node<point_rel_omt>> ) {
        int cost = 0;
        const oter_id oter = get_ter_at( cur.pos );
        if( !connection->has( oter ) ) {
            if( params.road_only ) {
                return pf::node_score::rejected;
            }
            if( is_river( oter ) ) {
                return pf::node_score::rejected; // Can't walk on water
            }
            // Allow going slightly off-road to overcome small obstacles (e.g. craters),
            // but heavily penalize that to make roads preferable
            cost = 250;
        }
        return pf::node_score( cost, manhattan_dist( finish, cur.pos ) );
    };
    // TODO: use overmapbuffer::get_travel_path() with appropriate params instead
    // TODO: tick params.popup
    const auto path = pf::greedy_path( start, finish, O * 2, estimate );
    for( const auto &node : path.nodes ) {
        reveal( base + node.pos, params.radius );
    }
    return !path.nodes.empty();
}
References pf::greedy_path(), overmap_connections::guess_for(), overmap::invalid_tripoint, is_river(), manhattan_dist(), OMAPX, OMAPY, pf::directed_node< Point >::pos, omt_route_params::radius, pf::node_score::rejected, reveal(), omt_route_params::road_only, and ter().
Referenced by mission_start::reveal_refugee_center(), and mission_util::reveal_road().
save()
void overmapbuffer::save ()
Definition at line 202 of file overmapbuffer.cpp.
{
    for( auto &omp : overmaps ) {
        // Note: this may throw io errors from std::ofstream
        omp.second->save();
    }
}
References overmaps.
Referenced by game::save_maps().
scent_at()
scent_trace overmapbuffer::scent_at (const tripoint_abs_omt & pos)
Method to retrieve the scent at a given location.
Definition at line 556 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->scent_at( p );
    }
    return scent_trace();
}
References get_existing_om_global().
Referenced by overmap_ui::get_scent_glyph(), Character::process_turn(), and scents_near().
scents_near()
std::array< std::array< scent_trace, 3 >, 3 > overmapbuffer::scents_near (const tripoint_abs_omt & origin)
Accessors for horde introspection into overmaps.
Probably also useful for NPC overmap-scale navigation. Returns the 3x3 array of scent values surrounding the origin point.
Parameters
origin is in world-global omt coordinates.
Definition at line 541 of file overmapbuffer.cpp.
{
    std::array<std::array<scent_trace, 3>, 3> found_traces;
    for( int x = -1; x <= 1 ; ++x ) {
        for( int y = -1; y <= 1; ++y ) {
            tripoint_abs_omt iter = origin + point( x, y );
            found_traces[x + 1][y + 1] = scent_at( iter );
        }
    }
    return found_traces;
}
References scent_at().
seen()
bool overmapbuffer::seen (const tripoint_abs_omt & p)
Definition at line 636 of file overmapbuffer.cpp.
{
    if( const overmap_with_local_coords om_loc = get_existing_om_global( p ) ) {
        return om_loc.om->seen( om_loc.local );
    }
    return false;
}
References get_existing_om_global().
Referenced by overmap_ui::draw_ascii(), overmap_ui::draw_camp_labels(), overmap_ui::draw_city_labels(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), overmap_ui::get_overmap_neighbors(), overmap_ui::get_overmap_path_to(), get_terrain_cost(), is_findable_location(), om_target_tile(), reveal(), set_seen(), and game::vertical_notes().
set_scent()
void overmapbuffer::set_scent (const tripoint_abs_omt & loc, int strength)
Method to set a scent trace.
Parameters
loc is in world-global omt coordinates.
strength sets the intensity of the scent trace, used for determining if a monster can detect the scent.
Definition at line 564 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( loc );
    scent_trace new_scent( calendar::turn, strength );
    om_loc.om->set_scent( loc, new_scent );
}
References get_om_global(), overmap_with_local_coords::om, overmap::set_scent(), and calendar::turn.
Referenced by game::do_turn().
set_seen()
void overmapbuffer::set_seen (const tripoint_abs_omt & p, bool seen = true)
Definition at line 644 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( p );
    om_loc.om->seen( om_loc.local ) = seen;
}
References get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, seen(), and overmap::seen().
Referenced by computer_session::action_map_sewer(), computer_session::action_map_subway(), overmap_ui::place_ter_or_special(), reveal(), game::update_overmap_seen(), map::update_visibility_cache(), and game::vertical_notes().
signal_hordes()
void overmapbuffer::signal_hordes (const tripoint_abs_sm & center, int sig_power)
Signal nearby hordes to move to given location.
Parameters
center The origin of the signal, hordes (that recognize the signal) want to go to there. In global submap coordinates.
sig_power The signal strength, higher values means it visible farther away.
Definition at line 473 of file overmapbuffer.cpp.
{
    const auto radius = sig_power;
    for( auto &om : get_overmaps_near( center, radius ) ) {
        const point_abs_sm abs_pos_om = project_to<coords::sm>( om->pos() );
        const tripoint_rel_sm rel_pos = center - abs_pos_om;
        // overmap::signal_hordes expects a coordinate relative to the overmap, this is easier
        // for processing as the monster group stores is location as relative coordinates, too.
        om->signal_hordes( rel_pos, sig_power );
    }
}
References center, get_overmaps_near(), and coords::om.
Referenced by sounds::process_sounds().
spawn_monster()
void overmapbuffer::spawn_monster (const tripoint_abs_sm & p)
Spawn monsters from the overmap onto the main map (game::m).
p is an absolute submap coordinate.
Definition at line 1455 of file overmapbuffer.cpp.
{
    // Create a copy, so we can reuse x and y later
    point_abs_sm abs_sm = p.xy();
    point_om_sm sm;
    point_abs_om omp;
    std::tie( omp, sm ) = project_remain<coords::om>( abs_sm );
    overmap &om = get( omp );
    const tripoint_om_sm current_submap_loc( sm, p.z() );
    auto monster_bucket = om.monster_map->equal_range( current_submap_loc );
    std::for_each( monster_bucket.first, monster_bucket.second,
    [&]( std::pair<const tripoint_om_sm, monster> &monster_entry ) {
        monster &this_monster = monster_entry.second;
        // The absolute position in map squares, (x,y) is already global, but it's a
        // submap coordinate, so translate it and add the exact monster position on
        // the submap. modulo because the zombies position might be negative, as it
        // is stored *after* it has gone out of bounds during shifting. When reloading
        // we only need the part that tells where on the submap to put it.
        point ms( modulo( this_monster.posx(), SEEX ), modulo( this_monster.posy(), SEEY ) );
        assert( ms.x >= 0 && ms.x < SEEX );
        assert( ms.y >= 0 && ms.y < SEEX );
        // TODO: fix point types
        ms += project_to<coords::ms>( p.xy() ).raw();
        const map &here = get_map();
        // The monster position must be local to the main map when added to the game
        const tripoint local = tripoint( here.getlocal( ms ), p.z() );
        assert( here.inbounds( local ) );
        monster *const placed = g->place_critter_at( make_shared_fast<monster>( this_monster ),
                                local );
        if( placed ) {
            placed->on_load();
        }
    } );
    om.monster_map->erase( current_submap_loc );
}
References get(), coords::om, coords::sm, coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by map::spawn_monsters_submap().
ter()
const oter_id & overmapbuffer::ter (const tripoint_abs_omt & p)
Returns the overmap terrain at the given OMT coordinates.
Creates a new overmap if necessary.
Definition at line 650 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( p );
    return om_loc.om->ter( om_loc.local );
}
References get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, and overmap::ter().
Referenced by computer_session::action_map_sewer(), computer_session::action_map_subway(), Character::activate_bionic(), Character::activate_mutation(), memorial_logger::add(), Character::burn_fuel(), debug_menu::character_edit_menu(), basecamp::combat_mission_return(), companion_travel_time_calc(), debug_menu::debug(), basecamp::define_camp(), overmap_ui::draw_ascii(), draw_env_compact(), draw_loc_labels(), draw_location_classic(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), map::generate(), get_description_at(), overmap_ui::get_overmap_neighbors(), good_fishing_spot(), map::grow_plant(), mission::is_complete(), map::loadn(), editmap::mapgen_preview(), MapExtras::mx_bandits_block(), MapExtras::mx_minefield(), MapExtras::mx_roadblock(), MapExtras::mx_roadworks(), talk_function::om_building_region(), om_companion_path(), om_target_tile(), Character::overmap_los(), Character::passive_power_gen(), game::perhaps_add_random_npc(), photo_def_for_camera_point(), map::place_items(), mission_start::place_npc_software(), map::place_spawns(), game::pre_print_all_tile_info(), talk_function::recover_camp(), render_wind(), reveal(), reveal_route(), reveal_target(), conditional_t< T >::set_at_om_location(), map::spread_gas(), talk_function::start_camp(), basecamp::start_cut_logs(), basecamp::start_fortifications(), sum_conditions(), basecamp::survey_return(), vehicle::total_wind_epower_w(), activity_handlers::tree_communion_do_turn(), Character::update_bodytemp(), game::update_overmap_seen(), game::vertical_notes(), and iuse::weather_tool().
ter_existing()
const oter_id & overmapbuffer::ter_existing (const tripoint_abs_omt & p)
Returns the overmap terrain at the given OMT coordinates.
Returns ot_null if the point is not in any existing overmap.
Definition at line 656 of file overmapbuffer.cpp.
{
    static const oter_id ot_null;
    const overmap_with_local_coords om_loc = get_existing_om_global( p );
    if( !om_loc.om ) {
        return ot_null;
    }
    return om_loc.om->ter( om_loc.local );
}
References get_existing_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, ot_null, and overmap::ter().
Referenced by overmap_ui::get_overmap_path_to(), get_terrain_cost(), and is_ramp().
ter_set()
void overmapbuffer::ter_set (const tripoint_abs_omt & p, const oter_id & id)
Definition at line 666 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( p );
    return om_loc.om->ter_set( om_loc.local, id );
}
References get_om_global(), overmap_with_local_coords::local, overmap_with_local_coords::om, and overmap::ter_set().
Referenced by basecamp::define_camp(), find_or_create_om_terrain(), talk_function::loot_building(), editmap::mapgen_preview(), om_set_hide_site(), overmap_ui::place_ter_or_special(), basecamp::start_clearcut(), basecamp::start_cut_logs(), and basecamp::survey_return().
terrain_filename()
std::string overmapbuffer::terrain_filename (const point_abs_om & p) static
Definition at line 72 of file overmapbuffer.cpp.
{
    return string_format( "%s/o.%d.%d", g->get_world_base_save_path(), p.x(), p.y() );
}
References g, string_format(), coords::coord_point< Point, Origin, Scale >::x(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by get_existing(), overmap::open(), and overmap::save().
toggle_explored()
void overmapbuffer::toggle_explored (const tripoint_abs_omt & p)
Definition at line 398 of file overmapbuffer.cpp.
{
    const overmap_with_local_coords om_loc = get_om_global( p );
    om_loc.om->explored( om_loc.local ) = !om_loc.om->explored( om_loc.local );
}
References overmap::explored(), get_om_global(), overmap_with_local_coords::local, and overmap_with_local_coords::om.
Referenced by overmap_ui::display().
Member Data Documentation
known_non_existing
std::set<point_abs_om> overmapbuffer::known_non_existing mutable private
Set of overmap coordinates of overmaps that are known to not exist on disk.
See get_existing for usage.
Definition at line 537 of file overmapbuffer.h.
Referenced by clear(), and get_existing().
last_requested_overmap
overmap* overmapbuffer::last_requested_overmap mutable private
Definition at line 539 of file overmapbuffer.h.
Referenced by clear(), create_custom_overmap(), get(), and get_existing().
overmaps
std::unordered_map< point_abs_om, std::unique_ptr< overmap > > overmapbuffer::overmaps private
Definition at line 532 of file overmapbuffer.h.
Referenced by clear(), create_custom_overmap(), find_all(), find_camp(), find_closest(), find_npc(), get(), get_existing(), get_extras(), get_notes(), get_overmap_npcs(), remove_npc(), and save().
The documentation for this class was generated from the following files:
src/overmapbuffer.h
src/overmapbuffer.cpp