Cataclysm BN: query_popup Class Reference
query_popup Class Reference
UI class for displaying messages or querying player input with popups.
#include <popup.h>
Classes
struct button
struct query_option
struct result
Query result returned by query_once and query.
Public Member Functions
query_popup ()
Default construction.
query_popup & context (const std::string &cat)
Specify the input context.
template<typename ... Args>
query_popup & message (const std::string &fmt, Args &&... args)
Specify the query message.
template<typename ... Args>
query_popup & message (const char *const fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const nc_color &bar_color, const std::string &fmt, Args &&... args)
Like query_popup::message, but with waiting symbol prepended to the text.
template<typename ... Args>
query_popup & wait_message (const nc_color &bar_color, const char *const fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const std::string &fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const char *const fmt, Args &&... args)
query_popup & option (const std::string &opt)
Specify an action as an option.
query_popup & option (const std::string &opt, const std::function< bool(const input_event &)> &filter)
Specify an action as an option, and a filter of allowed input events for this action.
query_popup & allow_anykey (bool allow)
Specify whether non-option actions can be returned.
query_popup & allow_cancel (bool allow)
Specify whether an implicit cancel option is allowed.
query_popup & on_top (bool top)
Whether to show the popup on the top of the screen.
query_popup & full_screen (bool full)
Whether to show the popup in FULL_SCREEN_HEIGHT and FULL_SCREEN_WIDTH.
query_popup & cursor (size_t pos)
Specify starting cursor position.
query_popup & default_color (const nc_color &d_color)
Specify the default message color.
void show () const
Draw the UI.
result query_once ()
Query once and return the result.
result query ()
Query until a valid action or an error happens and return the result.
Protected Member Functions
std::shared_ptr< ui_adaptor > create_or_get_adaptor (bool disable_below=false)
Create or get a ui_adaptor on the UI stack to handle redrawing and resizing of the popup.
Private Member Functions
void invalidate_ui () const
void init () const
Static Private Member Functions
static std::vector< std::vector< std::string > > fold_query (const std::string &category, const std::vector< query_option > &options, int max_width, int horz_padding)
template<typename ... Args>
static void assert_format (const std::string &, Args &&...)
static std::string wait_text (const std::string &text, const nc_color &bar_color)
static std::string wait_text (const std::string &text)
Private Attributes
std::string category
std::string text
std::vector< query_option > options
size_t cur
nc_color default_text_color
bool anykey
bool cancel
bool ontop
bool fullscr
std::weak_ptr< ui_adaptor > adaptor
catacurses::window win
std::vector< std::string > folded_msg
std::vector< button > buttons
Detailed Description
UI class for displaying messages or querying player input with popups.
Example:
std::string action = query_popup() .context("YESNOCANCEL") // input context to use .message("%s", _("Do you want to save before jumping into the lava?")) .option("YES") // yes, save before jumping .option("NO") // no, don't save before jumping .option("QUIT") // NOOO, I didn't mean to jump into lava! .cursor(2) // default to the third option QUIT .query() // do the query, and get the input action and event .action // retrieve the input action
Please refer to documentation of individual functions for detailed explanation.
Definition at line 38 of file popup.h.
Constructor & Destructor Documentation
query_popup()
query_popup::query_popup ()
Default construction.
Note that context and options are not set in default construction, and calling query_once or query right after default construction will return { false, "ERROR", {} }.
Definition at line 15 of file popup.cpp.
    : cur( 0 ), default_text_color( c_white ), anykey( false ), cancel( false ), ontop( false ),
      fullscr( false )
{
}
Member Function Documentation
allow_anykey()
query_popup & query_popup::allow_anykey (bool allow)
Specify whether non-option actions can be returned.
Mouse movement is always ignored regardless of this setting.
Definition at line 45 of file popup.cpp.
{
    // Change does not affect cache, do not invalidate the window
    anykey = allow;
    return *this;
}
References anykey.
Referenced by input_context::display_menu(), popup(), and player::power_mutations_ui().
allow_cancel()
query_popup & query_popup::allow_cancel (bool allow)
Specify whether an implicit cancel option is allowed.
This call does not list the cancel option in the UI. Use option("QUIT") instead to explicitly list cancel in the UI.
Definition at line 52 of file popup.cpp.
{
    // Change does not affect cache, do not invalidate the window
    cancel = allow;
    return *this;
}
References cancel.
Referenced by popup(), player::power_mutations_ui(), and pickup::query_thief().
assert_format()
template<typename ... Args> static void query_popup::assert_format (const std::string & , Args && ...) inline static private
Definition at line 243 of file popup.h.
{
            static_assert( sizeof...( Args ) > 0,
                           "Format string should take at least one argument.  "
                           "If your message is not a format string, "
                           "use `message( \"%s\", text )` instead." );
        }
Referenced by message(), and wait_message().
context()
query_popup & query_popup::context (const std::string & cat)
Specify the input context.
In addition to being used to handle input actions, the input context will also be used to generate option text, so it should always be specified as long as at least one option is specified with option(), even if query_once or query are not called afterwards.
Definition at line 21 of file popup.cpp.
{
    invalidate_ui();
    category = cat;
    return *this;
}
References category, and invalidate_ui().
Referenced by game::cancel_activity_or_ignore_query(), popup(), player::power_mutations_ui(), pickup::query_thief(), and query_yn().
create_or_get_adaptor()
std::shared_ptr< ui_adaptor > query_popup::create_or_get_adaptor (bool disable_below = false) protected
Create or get a ui_adaptor on the UI stack to handle redrawing and resizing of the popup.
Definition at line 242 of file popup.cpp.
{
    std::shared_ptr<ui_adaptor> ui = adaptor.lock();
    if( !ui ) {
        if( disable_below ) {
            ui = std::make_shared<ui_adaptor>( ui_adaptor::disable_uis_below{} );
        } else {
            ui = std::make_shared<ui_adaptor>();
        }
        adaptor = ui;
        ui->on_redraw( [this]( const ui_adaptor & ) {
            show();
        } );
        ui->on_screen_resize( [this]( ui_adaptor & ) {
            init();
        } );
        ui->mark_resize();
    }
    return ui;
}
References adaptor, init(), and show().
Referenced by query(), query_once(), static_popup::static_popup(), and throbber_popup::throbber_popup().
cursor()
query_popup & query_popup::cursor (size_t pos)
Specify starting cursor position.
Definition at line 73 of file popup.cpp.
{
    // Change does not affect cache, do not invalidate window
    cur = pos;
    return *this;
}
References cur.
Referenced by pickup::query_thief(), and query_yn().
default_color()
query_popup & query_popup::default_color (const nc_color & d_color)
Specify the default message color.
Definition at line 80 of file popup.cpp.
{
    default_text_color = d_color;
    return *this;
}
References default_text_color.
Referenced by query_yn().
fold_query()
std::vector< std::vector< std::string > > query_popup::fold_query (const std::string & category, const std::vector< query_option > & options, int max_width, int horz_padding) static private
Definition at line 86 of file popup.cpp.
{
    input_context ctxt( category );
    std::vector<std::vector<std::string>> folded_query;
    folded_query.emplace_back();
    int query_cnt = 0;
    int query_width = 0;
    for( const auto &opt : options ) {
        const auto &name = ctxt.get_action_name( opt.action );
        const auto &desc = ctxt.get_desc( opt.action, name, opt.filter );
        const int this_query_width = utf8_width( desc, true ) + horz_padding;
        ++query_cnt;
        query_width += this_query_width;
        if( query_width > max_width + horz_padding ) {
            if( query_cnt == 1 ) {
                // Each line has at least one query, so keep this query in the current line
                folded_query.back().emplace_back( desc );
                folded_query.emplace_back();
                query_cnt = 0;
                query_width = 0;
            } else {
                // Wrap this query to the next line
                folded_query.emplace_back();
                folded_query.back().emplace_back( desc );
                query_cnt = 1;
                query_width = this_query_width;
            }
        } else {
            folded_query.back().emplace_back( desc );
        }
    }
    if( folded_query.back().empty() ) {
        folded_query.pop_back();
    }
    return folded_query;
}
References category, input_context::get_action_name(), input_context::get_desc(), om_direction::name(), options, and utf8_width().
Referenced by init().
full_screen()
query_popup & query_popup::full_screen (bool full)
Whether to show the popup in FULL_SCREEN_HEIGHT and FULL_SCREEN_WIDTH.
Definition at line 66 of file popup.cpp.
{
    invalidate_ui();
    fullscr = full;
    return *this;
}
References fullscr, and invalidate_ui().
Referenced by popup().
init()
void query_popup::init () const private
Definition at line 145 of file popup.cpp.
{
    constexpr int horz_padding = 2;
    constexpr int vert_padding = 1;
    const int max_line_width = FULL_SCREEN_WIDTH - border_width * 2;
    // Fold message text
    folded_msg = foldstring( text, max_line_width );
    // Fold query buttons
    const auto &folded_query = fold_query( category, options, max_line_width, horz_padding );
    // Calculate size of message part
    int msg_width = 0;
    int msg_height = folded_msg.size();
    for( const auto &line : folded_msg ) {
        msg_width = std::max( msg_width, utf8_width( line, true ) );
    }
    // Calculate width with query buttons
    for( const auto &line : folded_query ) {
        if( !line.empty() ) {
            int button_width = 0;
            for( const auto &opt : line ) {
                button_width += utf8_width( opt, true );
            }
            msg_width = std::max( msg_width, button_width +
                                  horz_padding * static_cast<int>( line.size() - 1 ) );
        }
    }
    msg_width = std::min( msg_width, max_line_width );
    // Calculate height with query buttons & button positions
    buttons.clear();
    if( !folded_query.empty() ) {
        msg_height += vert_padding;
        for( const auto &line : folded_query ) {
            if( !line.empty() ) {
                int button_width = 0;
                for( const auto &opt : line ) {
                    button_width += utf8_width( opt, true );
                }
                // Right align.
                // TODO: multi-line buttons
                int button_x = std::max( 0, msg_width - button_width -
                                         horz_padding * static_cast<int>( line.size() - 1 ) );
                for( const auto &opt : line ) {
                    buttons.emplace_back( opt, point( button_x, msg_height ) );
                    button_x += utf8_width( opt, true ) + horz_padding;
                }
                msg_height += 1 + vert_padding;
            }
        }
        msg_height -= vert_padding;
    }
    // Calculate window size
    const int win_width = std::min( TERMX,
                                    fullscr ? FULL_SCREEN_WIDTH : msg_width + border_width * 2 );
    const int win_height = std::min( TERMY,
                                     fullscr ? FULL_SCREEN_HEIGHT : msg_height + border_width * 2 );
    const int win_x = ( TERMX - win_width ) / 2;
    const int win_y = ontop ? 0 : ( TERMY - win_height ) / 2;
    win = catacurses::newwin( win_height, win_width, point( win_x, win_y ) );
    std::shared_ptr<ui_adaptor> ui = adaptor.lock();
    if( ui ) {
        ui->position_from_window( win );
    }
}
References adaptor, border_width, buttons, category, fold_query(), folded_msg, foldstring(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, fullscr, line(), catacurses::newwin(), ontop, options, TERMX, TERMY, text, utf8_width(), and win.
Referenced by create_or_get_adaptor(), query_once(), and show().
invalidate_ui()
void query_popup::invalidate_ui () const private
Definition at line 130 of file popup.cpp.
{
    if( win ) {
        win = {};
        folded_msg.clear();
        buttons.clear();
    }
    std::shared_ptr<ui_adaptor> ui = adaptor.lock();
    if( ui ) {
        ui->mark_resize();
    }
}
References adaptor, buttons, folded_msg, and win.
Referenced by context(), full_screen(), message(), on_top(), option(), and wait_message().
message() [1/2]
template<typename ... Args> query_popup & query_popup::message (const char *const fmt, Args &&... args) inline
Definition at line 98 of file popup.h.
{
            assert_format( fmt, std::forward<Args>( args )... );
            invalidate_ui();
            text = string_format( fmt, std::forward<Args>( args )... );
            return *this;
        }
References assert_format(), invalidate_ui(), string_format(), and text.
message() [2/2]
template<typename ... Args> query_popup & query_popup::message (const std::string & fmt, Args &&... args) inline
Specify the query message.
Definition at line 91 of file popup.h.
{
            assert_format( fmt, std::forward<Args>( args )... );
            invalidate_ui();
            text = string_format( fmt, std::forward<Args>( args )... );
            return *this;
        }
References assert_format(), invalidate_ui(), string_format(), and text.
Referenced by game::cancel_activity_or_ignore_query(), input_context::display_menu(), popup(), player::power_mutations_ui(), pickup::query_thief(), query_yn(), and game::zones_manager().
on_top()
query_popup & query_popup::on_top (bool top)
Whether to show the popup on the top of the screen.
Definition at line 59 of file popup.cpp.
{
    invalidate_ui();
    ontop = top;
    return *this;
}
References invalidate_ui(), and ontop.
Referenced by popup(), throbber_popup::throbber_popup(), and game::zones_manager().
option() [1/2]
query_popup & query_popup::option (const std::string & opt)
Specify an action as an option.
The action must be present in the supplied context, either locally or globally. The same applies to other option methods.
Definition at line 28 of file popup.cpp.
{
    invalidate_ui();
    options.emplace_back( opt, []( const input_event & ) {
        return true;
    } );
    return *this;
}
References invalidate_ui(), and options.
Referenced by game::cancel_activity_or_ignore_query(), pickup::query_thief(), and query_yn().
option() [2/2]
query_popup & query_popup::option (const std::string & opt, const std::function< bool(const input_event &)> & filter)
Specify an action as an option, and a filter of allowed input events for this action.
This is for compatibility with the "FORCE_CAPITAL_YN" option. Note that even if the input event is filtered, it will still select the respective dialog option, without closing the dialog.
Definition at line 37 of file popup.cpp.
{
    invalidate_ui();
    options.emplace_back( opt, filter );
    return *this;
}
References invalidate_ui(), and options.
query()
query_popup::result query_popup::query ()
Query until a valid action or an error happens and return the result.
Definition at line 348 of file popup.cpp.
{
    ime_sentry sentry( ime_sentry::disable );
    std::shared_ptr<ui_adaptor> ui = create_or_get_adaptor();
    result res;
    do {
        res = query_once();
    } while( res.wait_input );
    return res;
}
References create_or_get_adaptor(), ime_sentry::disable, query_once(), and query_popup::result::wait_input.
Referenced by game::cancel_activity_or_ignore_query(), input_context::display_menu(), popup(), player::power_mutations_ui(), pickup::query_thief(), and query_yn().
query_once()
query_popup::result query_popup::query_once ()
Query once and return the result.
In order for this method to return valid results, the popup must either have at least one option, or have allow_cancel or allow_anykey set to true. Otherwise { false, "ERROR", {} } is returned. The same applies to query.
Definition at line 263 of file popup.cpp.
{
    if( !anykey && !cancel && options.empty() ) {
        return { false, "ERROR", {} };
    }
    if( test_mode ) {
        return { false, "ERROR", {} };
    }
    std::shared_ptr<ui_adaptor> ui = create_or_get_adaptor();
    ui_manager::redraw();
    input_context ctxt( category );
    if( cancel || !options.empty() ) {
        ctxt.register_action( "HELP_KEYBINDINGS" );
    }
    if( !options.empty() ) {
        ctxt.register_action( "LEFT" );
        ctxt.register_action( "RIGHT" );
        ctxt.register_action( "CONFIRM" );
        for( const auto &opt : options ) {
            ctxt.register_action( opt.action );
        }
    }
    if( anykey ) {
        ctxt.register_action( "ANY_INPUT" );
        // Mouse movement, button, and wheel
        ctxt.register_action( "COORDINATE" );
    }
    if( cancel ) {
        ctxt.register_action( "QUIT" );
    }
    result res;
    // Assign outside construction of `res` to ensure execution order
    res.wait_input = !anykey;
    do {
        res.action = ctxt.handle_input();
        res.evt = ctxt.get_raw_input();
    } while(
        // Always ignore mouse movement
        ( res.evt.type == CATA_INPUT_MOUSE && res.evt.get_first_input() == MOUSE_MOVE ) ||
        // Ignore window losing focus in SDL
        ( res.evt.type == CATA_INPUT_KEYBOARD && res.evt.sequence.empty() )
    );
    if( cancel && res.action == "QUIT" ) {
        res.wait_input = false;
    } else if( res.action == "LEFT" ) {
        if( cur > 0 ) {
            --cur;
        } else {
            cur = options.size() - 1;
        }
    } else if( res.action == "RIGHT" ) {
        if( cur + 1 < options.size() ) {
            ++cur;
        } else {
            cur = 0;
        }
    } else if( res.action == "CONFIRM" ) {
        if( cur < options.size() ) {
            res.wait_input = false;
            res.action = options[cur].action;
        }
    } else if( res.action == "HELP_KEYBINDINGS" ) {
        // Keybindings may have changed, regenerate the UI
        init();
    } else {
        for( size_t ind = 0; ind < options.size(); ++ind ) {
            if( res.action == options[ind].action ) {
                cur = ind;
                if( options[ind].filter( res.evt ) ) {
                    res.wait_input = false;
                    break;
                }
            }
        }
    }
    return res;
}
References query_popup::result::action, anykey, cancel, CATA_INPUT_KEYBOARD, CATA_INPUT_MOUSE, category, create_or_get_adaptor(), cur, query_popup::result::evt, input_event::get_first_input(), input_context::get_raw_input(), input_context::handle_input(), init(), MOUSE_MOVE, options, ui_manager::redraw(), input_context::register_action(), input_event::sequence, test_mode, input_event::type, and query_popup::result::wait_input.
Referenced by query().
show()
void query_popup::show () const
Draw the UI.
An input context should be provided using context() for this function to properly generate option text.
Definition at line 217 of file popup.cpp.
{
    if( !win ) {
        init();
    }
    werase( win );
    draw_border( win );
    for( size_t line = 0; line < folded_msg.size(); ++line ) {
        nc_color col = default_text_color;
        print_colored_text( win, point( border_width, border_width + line ), col, col,
                            folded_msg[line] );
    }
    for( size_t ind = 0; ind < buttons.size(); ++ind ) {
        nc_color col = ind == cur ? hilite( c_white ) : c_white;
        const auto &btn = buttons[ind];
        print_colored_text( win, btn.pos + point( border_width, border_width ),
                            col, col, btn.text );
    }
    wnoutrefresh( win );
}
References border_width, buttons, c_white, cur, default_text_color, draw_border(), folded_msg, hilite(), init(), line(), print_colored_text(), catacurses::werase(), win, and catacurses::wnoutrefresh().
Referenced by create_or_get_adaptor().
wait_message() [1/4]
template<typename ... Args> query_popup & query_popup::wait_message (const char *const fmt, Args &&... args) inline
Definition at line 129 of file popup.h.
{
            assert_format( fmt, std::forward<Args>( args )... );
            invalidate_ui();
            text = wait_text( string_format( fmt, std::forward<Args>( args )... ) );
            return *this;
        }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
wait_message() [2/4]
template<typename ... Args> query_popup & query_popup::wait_message (const nc_color & bar_color, const char *const fmt, Args &&... args) inline
Definition at line 115 of file popup.h.
{
            assert_format( fmt, std::forward<Args>( args )... );
            invalidate_ui();
            text = wait_text( string_format( fmt, std::forward<Args>( args )... ), bar_color );
            return *this;
        }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
wait_message() [3/4]
template<typename ... Args> query_popup & query_popup::wait_message (const nc_color & bar_color, const std::string & fmt, Args &&... args) inline
Like query_popup::message, but with waiting symbol prepended to the text.
Definition at line 108 of file popup.h.
{
            assert_format( fmt, std::forward<Args>( args )... );
            invalidate_ui();
            text = wait_text( string_format( fmt, std::forward<Args>( args )... ), bar_color );
            return *this;
        }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
Referenced by throbber_popup::refresh().
wait_message() [4/4]
template<typename ... Args> query_popup & query_popup::wait_message (const std::string & fmt, Args &&... args) inline
Definition at line 122 of file popup.h.
{
            assert_format( fmt, std::forward<Args>( args )... );
            invalidate_ui();
            text = wait_text( string_format( fmt, std::forward<Args>( args )... ) );
            return *this;
        }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
wait_text() [1/2]
std::string query_popup::wait_text (const std::string & text) static private
Definition at line 369 of file popup.cpp.
{
    return wait_text( text, c_light_green );
}
References c_light_green, text, and wait_text().
wait_text() [2/2]
std::string query_popup::wait_text (const std::string & text, const nc_color & bar_color) static private
Definition at line 361 of file popup.cpp.
{
    static const std::array<std::string, 4> phase_icons = {{ "|", "/", "-", "\\" }};
    static size_t phase = phase_icons.size() - 1;
    phase = ( phase + 1 ) % phase_icons.size();
    return string_format( " %s %s", colorize( phase_icons[phase], bar_color ), text );
}
References colorize(), string_format(), and text.
Referenced by wait_message(), and wait_text().
Member Data Documentation
adaptor
std::weak_ptr<ui_adaptor> query_popup::adaptor private
Definition at line 228 of file popup.h.
Referenced by create_or_get_adaptor(), init(), and invalidate_ui().
anykey
bool query_popup::anykey private
Definition at line 216 of file popup.h.
Referenced by allow_anykey(), and query_once().
buttons
std::vector<button> query_popup::buttons mutable private
Definition at line 233 of file popup.h.
Referenced by init(), invalidate_ui(), and show().
cancel
bool query_popup::cancel private
Definition at line 217 of file popup.h.
Referenced by allow_cancel(), and query_once().
category
std::string query_popup::category private
Definition at line 211 of file popup.h.
Referenced by context(), fold_query(), init(), and query_once().
cur
size_t query_popup::cur private
Definition at line 214 of file popup.h.
Referenced by cursor(), query_once(), and show().
default_text_color
nc_color query_popup::default_text_color private
Definition at line 215 of file popup.h.
Referenced by default_color(), and show().
folded_msg
std::vector<std::string> query_popup::folded_msg mutable private
Definition at line 232 of file popup.h.
Referenced by init(), invalidate_ui(), and show().
fullscr
bool query_popup::fullscr private
Definition at line 219 of file popup.h.
Referenced by full_screen(), and init().
ontop
bool query_popup::ontop private
Definition at line 218 of file popup.h.
Referenced by init(), and on_top().
options
std::vector<query_option> query_popup::options private
Definition at line 213 of file popup.h.
Referenced by fold_query(), init(), option(), and query_once().
text
std::string query_popup::text private
Definition at line 212 of file popup.h.
Referenced by init(), message(), wait_message(), and wait_text().
win
catacurses::window query_popup::win mutable private
Definition at line 231 of file popup.h.
Referenced by init(), invalidate_ui(), and show().
The documentation for this class was generated from the following files:
src/popup.h
src/popup.cpp