Cataclysm BN: addiction_reader Class Reference
addiction_reader Class Reference
Public Member Functions
addiction get_next (JsonIn &jin) const
template<typename C >
void erase_next (JsonIn &jin, C &container) const
Public Member Functions inherited from generic_typed_reader< addiction_reader >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Detailed Description
Definition at line 105 of file profession.cpp.
Member Function Documentation
erase_next()
template<typename C > void addiction_reader::erase_next (JsonIn & jin, C & container) const inline
Definition at line 113 of file profession.cpp.
{
            const add_type type = addiction_type( jin.get_string() );
            reader_detail::handler<C>().erase_if( container, [&type]( const addiction & e ) {
                return e.type == type;
            } );
        }
References addiction_type(), JsonIn::get_string(), type, and addiction::type.
get_next()
addiction addiction_reader::get_next (JsonIn & jin) const inline
Definition at line 108 of file profession.cpp.
{
            JsonObject jo = jin.get_object();
            return addiction( addiction_type( jo.get_string( "type" ) ), jo.get_int( "intensity" ) );
        }
References addiction_type(), JsonObject::get_int(), JsonIn::get_object(), and JsonObject::get_string().
The documentation for this class was generated from the following file:
src/profession.cpp