Cataclysm BN: font_loader Class Reference
font_loader Class Reference
#include <font_loader.h>
Public Member Functions
void load ()
Public Attributes
bool fontblending = false
std::vector< std::string > typeface
std::vector< std::string > map_typeface
std::vector< std::string > overmap_typeface
int fontwidth = 8
int fontheight = 16
int fontsize = 16
int map_fontwidth = 8
int map_fontheight = 16
int map_fontsize = 16
int overmap_fontwidth = 8
int overmap_fontheight = 16
int overmap_fontsize = 16
Private Member Functions
void load_throws (const std::string &path)
Detailed Description
Definition at line 25 of file font_loader.h.
Member Function Documentation
load()
void font_loader::load () inline
Definition at line 75 of file font_loader.h.
                    {
            const std::string user_fontconfig = PATH_INFO::user_fontconfig();
            const std::string fontconfig = PATH_INFO::fontconfig();
            bool try_user = true;
            if( !file_exist( user_fontconfig ) ) {
                if( !copy_file( fontconfig, user_fontconfig ) ) {
                    try_user = false;
                    DebugLog( DL::Error, DC::SDL ) << "failed to create user font config file "
                                                   << user_fontconfig;
                }
            }
            if( try_user ) {
                font_loader copy = *this;
                try {
                    load_throws( user_fontconfig );
                    return;
                } catch( const std::exception &e ) {
                    DebugLog( DL::Error, DC::SDL ) << e.what();
                }
                *this = copy;
            }
            try {
                load_throws( fontconfig );
            } catch( const std::exception &e ) {
                DebugLog( DL::Error, DC::SDL ) << e.what();
                abort();
            }
        }
References abort, copy_file(), DebugLog, Error, file_exist(), PATH_INFO::fontconfig(), load_throws(), SDL, and PATH_INFO::user_fontconfig().
load_throws()
void font_loader::load_throws (const std::string & path) inline private
Definition at line 43 of file font_loader.h.
{
            try {
                cata_ifstream stream = std::move( cata_ifstream().mode( cata_ios_mode::binary ).open( path ) );
                JsonIn json( *stream );
                JsonObject config = json.get_object();
                if( config.has_string( "typeface" ) ) {
                    typeface.emplace_back( config.get_string( "typeface" ) );
                } else {
                    config.read( "typeface", typeface );
                }
                if( config.has_string( "map_typeface" ) ) {
                    map_typeface.emplace_back( config.get_string( "map_typeface" ) );
                } else {
                    config.read( "map_typeface", map_typeface );
                }
                if( config.has_string( "overmap_typeface" ) ) {
                    overmap_typeface.emplace_back( config.get_string( "overmap_typeface" ) );
                } else {
                    config.read( "overmap_typeface", overmap_typeface );
                }
                ensure_unifont_loaded( typeface );
                ensure_unifont_loaded( map_typeface );
                ensure_unifont_loaded( overmap_typeface );
            } catch( const std::exception &err ) {
                throw std::runtime_error( std::string( "loading font settings from " ) + path + " failed: " +
                                          err.what() );
            }
        }
References binary, calendar::config, ensure_unifont_loaded(), JsonIn::get_object(), map_typeface, avatar_action::move(), open(), overmap_typeface, and typeface.
Referenced by load().
Member Data Documentation
fontblending
bool font_loader::fontblending = false
Definition at line 28 of file font_loader.h.
fontheight
int font_loader::fontheight = 16
Definition at line 33 of file font_loader.h.
fontsize
int font_loader::fontsize = 16
Definition at line 34 of file font_loader.h.
fontwidth
int font_loader::fontwidth = 8
Definition at line 32 of file font_loader.h.
map_fontheight
int font_loader::map_fontheight = 16
Definition at line 36 of file font_loader.h.
map_fontsize
int font_loader::map_fontsize = 16
Definition at line 37 of file font_loader.h.
map_fontwidth
int font_loader::map_fontwidth = 8
Definition at line 35 of file font_loader.h.
map_typeface
std::vector<std::string> font_loader::map_typeface
Definition at line 30 of file font_loader.h.
Referenced by load_throws().
overmap_fontheight
int font_loader::overmap_fontheight = 16
Definition at line 39 of file font_loader.h.
overmap_fontsize
int font_loader::overmap_fontsize = 16
Definition at line 40 of file font_loader.h.
overmap_fontwidth
int font_loader::overmap_fontwidth = 8
Definition at line 38 of file font_loader.h.
overmap_typeface
std::vector<std::string> font_loader::overmap_typeface
Definition at line 31 of file font_loader.h.
Referenced by load_throws().
typeface
std::vector<std::string> font_loader::typeface
Definition at line 29 of file font_loader.h.
Referenced by load_throws().
The documentation for this class was generated from the following file:
src/font_loader.h