Cataclysm BN: minesweeper_game Class Reference
minesweeper_game Class Reference
#include <iuse_software_minesweeper.h>
Public Member Functions
int start_game ()
minesweeper_game ()
Private Types
enum reveal { unknown , flag , seen }
Private Member Functions
bool check_win ()
void new_level ()
Private Attributes
point max
point min
point level
point offset
int iBombs = 0
std::map< int, std::map< int, int > > mLevel
std::map< int, std::map< int, reveal > > mLevelReveal
Static Private Attributes
static constexpr int bomb = -1
Detailed Description
Definition at line 14 of file iuse_software_minesweeper.h.
Member Enumeration Documentation
reveal
enum minesweeper_game::reveal private
Enumerator
unknown
flag
seen
Definition at line 28 of file iuse_software_minesweeper.h.
                    {
            unknown,
            flag,
            seen
        };
Constructor & Destructor Documentation
minesweeper_game()
minesweeper_game::minesweeper_game ()
Definition at line 23 of file iuse_software_minesweeper.cpp.
{
    min = point( 8, 8 );
    max = point_zero;
    offset = point_zero;
}
References max, min, offset, and point_zero.
Member Function Documentation
check_win()
bool minesweeper_game::check_win () private
Definition at line 119 of file iuse_software_minesweeper.cpp.
{
    for( int y = 0; y < level.y; y++ ) {
        for( int x = 0; x < level.x; x++ ) {
            if( ( mLevelReveal[y][x] == flag || mLevelReveal[y][x] == unknown ) &&
                mLevel[y][x] != bomb ) {
                return false;
            }
        }
    }
    return true;
}
References bomb, flag, level, mLevel, mLevelReveal, unknown, point::x, and point::y.
Referenced by start_game().
new_level()
void minesweeper_game::new_level () private
Definition at line 30 of file iuse_software_minesweeper.cpp.
{
    auto set_num = [&]( const std::string & sType, int &iVal, const int iMin, const int iMax ) {
        const std::string desc = string_format( _( "Min: %d Max: %d" ), iMin, iMax );
        do {
            if( iVal < iMin || iVal > iMax ) {
                iVal = iMin;
            }
            string_input_popup()
            .title( sType )
            .width( 5 )
            .description( desc )
            .edit( iVal );
        } while( iVal < iMin || iVal > iMax );
    };
    uilist difficulty;
    difficulty.allow_cancel = false;
    difficulty.text = _( "Game Difficulty" );
    difficulty.entries.emplace_back( 0, true, 'b', _( "Beginner" ) );
    difficulty.entries.emplace_back( 1, true, 'i', _( "Intermediate" ) );
    difficulty.entries.emplace_back( 2, true, 'e', _( "Expert" ) );
    difficulty.entries.emplace_back( 3, true, 'c', _( "Custom" ) );
    difficulty.query();
    switch( difficulty.ret ) {
        case 0:
            level = point( 8, 8 );
            iBombs = 10;
            break;
        case 1:
            level = point( 16, 16 );
            iBombs = 40;
            break;
        case 2:
            level = point( 30, 16 );
            iBombs = 99;
            break;
        case 3:
        default:
            point new_level = min;
            set_num( _( "Level width:" ), new_level.x, min.x, max.x );
            set_num( _( "Level height:" ), new_level.y, min.y, max.y );
            const int area = new_level.x * new_level.y;
            int new_ibombs = area * 0.1;
            set_num( _( "Number of bombs:" ), new_ibombs, new_ibombs, area * 0.6 );
            level = new_level;
            iBombs = new_ibombs;
            break;
    }
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    offset = ( max - level ) / 2 + point( 1, 1 );
    mLevel.clear();
    mLevelReveal.clear();
    int iRandX;
    int iRandY;
    for( int i = 0; i < iBombs; i++ ) {
        do {
            iRandX = rng( 0, level.x - 1 );
            iRandY = rng( 0, level.y - 1 );
        } while( mLevel[iRandY][iRandX] == bomb );
        mLevel[iRandY][iRandX] = bomb;
    }
    for( int y = 0; y < level.y; y++ ) {
        for( int x = 0; x < level.x; x++ ) {
            if( mLevel[y][x] == bomb ) {
                for( point p : closest_points_first( {x, y}, 1 ) ) {
                    if( p.x >= 0 && p.x < level.x && p.y >= 0 && p.y < level.y ) {
                        if( mLevel[p.y][p.x] != bomb ) {
                            mLevel[p.y][p.x]++;
                        }
                    }
                }
            }
        }
    }
}
References _, uilist::allow_cancel, bomb, closest_points_first(), string_input_popup::description(), string_input_popup::edit(), uilist::entries, iBombs, level, max, min, mLevel, mLevelReveal, new_level(), offset, uilist::query(), uilist::ret, rng(), string_format(), uilist::text, string_input_popup::title(), string_input_popup::width(), point::x, and point::y.
Referenced by new_level(), and start_game().
start_game()
int minesweeper_game::start_game ()
Definition at line 133 of file iuse_software_minesweeper.cpp.
{
    catacurses::window w_minesweeper_border;
    catacurses::window w_minesweeper;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const point iCenter( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                             TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 );
        w_minesweeper_border = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                               iCenter );
        w_minesweeper = catacurses::newwin( FULL_SCREEN_HEIGHT - 2, FULL_SCREEN_WIDTH - 2,
                                            iCenter + point_south_east );
        max = point( FULL_SCREEN_WIDTH - 4, FULL_SCREEN_HEIGHT - 4 );
        ui.position_from_window( w_minesweeper_border );
    } );
    ui.mark_resize();
    input_context ctxt( "MINESWEEPER" );
    ctxt.register_cardinal();
    ctxt.register_action( "NEW" );
    ctxt.register_action( "FLAG" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    static const std::array<nc_color, 9> aColors = {{
            c_white,
            c_light_gray,
            c_cyan,
            c_blue,
            c_light_blue,
            c_green,
            c_magenta,
            c_red,
            c_yellow
        }
    };
    int iScore = 5;
    point pl;
    bool started = false;
    bool boom = false;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_minesweeper_border );
        draw_border( w_minesweeper_border );
        std::vector<std::string> shortcuts;
        shortcuts.push_back( _( "<n>ew level" ) );
        shortcuts.push_back( _( "<f>lag" ) );
        shortcuts.push_back( _( "<q>uit" ) );
        int iWidth = 0;
        for( auto &shortcut : shortcuts ) {
            if( iWidth > 0 ) {
                iWidth += 1;
            }
            iWidth += utf8_width( shortcut );
        }
        int iPos = FULL_SCREEN_WIDTH - iWidth - 1;
        for( auto &shortcut : shortcuts ) {
            shortcut_print( w_minesweeper_border, point( iPos, 0 ), c_white, c_light_green, shortcut );
            iPos += utf8_width( shortcut ) + 1;
        }
        mvwputch( w_minesweeper_border, point( 2, 0 ), hilite( c_white ), _( "Minesweeper" ) );
        wnoutrefresh( w_minesweeper_border );
        if( !started ) {
            return;
        }
        werase( w_minesweeper );
        draw_custom_border( w_minesweeper, 1, 1, 1, 1, 1, 1, 1, 1, BORDER_COLOR,
                            // NOLINTNEXTLINE(cata-use-named-point-constants)
                            offset + point( -1, -1 ), level.y + 2, level.x + 2 );
        for( int y = 0; y < level.y; ++y ) {
            for( int x = 0; x < level.x; ++x ) {
                char ch = '?';
                nc_color col = c_red;
                const int num = mLevel[y][x];
                switch( mLevelReveal[y][x] ) {
                    case unknown:
                        if( boom && num == bomb ) {
                            ch = '*';
                            col = h_red;
                        } else {
                            ch = '#';
                            col = c_white;
                        }
                        break;
                    case flag:
                        ch = '!';
                        if( boom && num == bomb ) {
                            col = h_red;
                        } else {
                            col = c_yellow;
                        }
                        break;
                    case seen: {
                        if( num == bomb ) {
                            ch = '*';
                            col = boom ? h_red : c_red;
                        } else if( num == 0 ) {
                            ch = ' ';
                            col = aColors[num];
                        } else if( num >= 1 && num <= 8 ) {
                            ch = '0' + num;
                            col = aColors[num];
                        }
                        break;
                    }
                }
                if( !boom && pl == point( x, y ) ) {
                    col = hilite( col );
                }
                mvwputch( w_minesweeper, offset + point( x, y ), col, ch );
            }
        }
        wnoutrefresh( w_minesweeper );
    } );
    std::function<void ( point )> rec_reveal = [&]( point  pt ) {
        if( mLevelReveal[pt.y][pt.x] == unknown || mLevelReveal[pt.y][pt.x] == flag ) {
            mLevelReveal[pt.y][pt.x] = seen;
            if( mLevel[pt.y][pt.x] == 0 ) {
                for( point p : closest_points_first( pt, 1 ) ) {
                    if( p.x >= 0 && p.x < level.x && p.y >= 0 && p.y < level.y ) {
                        if( mLevelReveal[p.y][p.x] != seen ) {
                            rec_reveal( p );
                        }
                    }
                }
            }
        }
    };
    const auto &reveal_all = [&]() {
        for( int y = 0; y < level.y; ++y ) {
            for( int x = 0; x < level.x; ++x ) {
                if( mLevelReveal[y][x] == unknown || ( mLevelReveal[y][x] == flag && mLevel[y][x] != bomb ) ) {
                    mLevelReveal[y][x] = seen;
                }
            }
        }
    };
    std::string action = "NEW";
    do {
        if( action == "NEW" ) {
            new_level();
            pl = point_zero;
            started = true;
            boom = false;
        }
        if( check_win() ) {
            reveal_all();
            ui.invalidate_ui();
            popup_top( _( "Congratulations, you won!" ) );
            iScore = 30;
            action = "QUIT";
        } else {
            ui_manager::redraw();
            action = ctxt.handle_input();
        }
        if( const cata::optional<tripoint> vec = ctxt.get_direction( action ) ) {
            const point newp = pl + vec->xy();
            if( half_open_rectangle<point>( point_zero, level ).contains( newp ) ) {
                pl = newp;
            }
        } else if( action == "FLAG" ) {
            if( mLevelReveal[pl.y][pl.x] == unknown ) {
                mLevelReveal[pl.y][pl.x] = flag;
            } else if( mLevelReveal[pl.y][pl.x] == flag ) {
                mLevelReveal[pl.y][pl.x] = unknown;
            }
        } else if( action == "CONFIRM" ) {
            if( mLevelReveal[pl.y][pl.x] != seen ) {
                if( mLevel[pl.y][pl.x] == bomb ) {
                    boom = true;
                    reveal_all();
                    ui.invalidate_ui();
                    popup_top( _( "Boom, you're dead!  Better luck next time." ) );
                    action = "QUIT";
                } else if( mLevelReveal[pl.y][pl.x] == unknown ) {
                    rec_reveal( pl );
                }
            }
        }
    } while( action != "QUIT" );
    return iScore;
}
References _, action, bomb, BORDER_COLOR, c_blue, c_cyan, c_green, c_light_blue, c_light_gray, c_light_green, c_magenta, c_red, c_white, c_yellow, check_win(), closest_points_first(), contains, draw_border(), draw_custom_border(), flag, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::get_direction(), h_red, input_context::handle_input(), hilite(), level, max, mLevel, mLevelReveal, mvwputch(), new_level(), catacurses::newwin(), num, offset, point_south_east, point_zero, popup_top(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), seen, shortcut_print(), TERMX, TERMY, unknown, utf8_width(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by play_videogame().
Member Data Documentation
bomb
constexpr int minesweeper_game::bomb = -1 static constexpr private
Definition at line 26 of file iuse_software_minesweeper.h.
Referenced by check_win(), new_level(), and start_game().
iBombs
int minesweeper_game::iBombs = 0 private
Definition at line 23 of file iuse_software_minesweeper.h.
Referenced by new_level().
level
point minesweeper_game::level private
Definition at line 21 of file iuse_software_minesweeper.h.
Referenced by check_win(), new_level(), and start_game().
max
point minesweeper_game::max private
Definition at line 19 of file iuse_software_minesweeper.h.
Referenced by minesweeper_game(), new_level(), and start_game().
min
point minesweeper_game::min private
Definition at line 20 of file iuse_software_minesweeper.h.
Referenced by minesweeper_game(), and new_level().
mLevel
std::map<int, std::map<int, int> > minesweeper_game::mLevel private
Definition at line 25 of file iuse_software_minesweeper.h.
Referenced by check_win(), new_level(), and start_game().
mLevelReveal
std::map<int, std::map<int, reveal> > minesweeper_game::mLevelReveal private
Definition at line 34 of file iuse_software_minesweeper.h.
Referenced by check_win(), new_level(), and start_game().
offset
point minesweeper_game::offset private
Definition at line 22 of file iuse_software_minesweeper.h.
Referenced by minesweeper_game(), new_level(), and start_game().
The documentation for this class was generated from the following files:
src/iuse_software_minesweeper.h
src/iuse_software_minesweeper.cpp