Cataclysm BN: distribution_grid Class Reference
distribution_grid Class Reference
A cache that organizes producers, storage and consumers of some resource, like electricity.
#include <distribution_grid.h>
Public Member Functions
distribution_grid (const std::vector< tripoint_abs_sm > &global_submap_coords, mapbuffer &buffer)
bool empty () const
operator bool () const
void update (time_point to)
int mod_resource (int amt, bool recurse=true)
int get_resource (bool recurse=true) const
const std::vector< tripoint_abs_ms > & get_contents () const
Private Attributes
std::map< tripoint_abs_sm, std::vector< tile_location > > contents
Map of submap coords to points on this submap that contain an active tile.
std::vector< tripoint_abs_ms > flat_contents
std::vector< tripoint_abs_sm > submap_coords
cata::optional< int > cached_amount_here
mapbuffer & mb
Friends
class distribution_grid_tracker
Detailed Description
A cache that organizes producers, storage and consumers of some resource, like electricity.
WARNING: Shouldn't be stored, as out of date grids are not updated.
Definition at line 36 of file distribution_grid.h.
Constructor & Destructor Documentation
distribution_grid()
distribution_grid::distribution_grid (const std::vector< tripoint_abs_sm > & global_submap_coords, mapbuffer & buffer)
Definition at line 19 of file distribution_grid.cpp.
                                                          :
    submap_coords( global_submap_coords ),
    mb( buffer )
{
    for( const tripoint_abs_sm &sm_coord : submap_coords ) {
        submap *sm = mb.lookup_submap( sm_coord );
        if( sm == nullptr ) {
            // Debugmsg already printed in mapbuffer.cpp
            return;
        }
        for( auto &active : sm->active_furniture ) {
            const tripoint_abs_ms abs_pos = project_combine( sm_coord, active.first );
            contents[sm_coord].emplace_back( active.first, abs_pos );
            flat_contents.emplace_back( abs_pos );
        }
    }
}
References active, contents, flat_contents, mapbuffer::lookup_submap(), mb, coords::project_combine(), coords::sm, and submap_coords.
Member Function Documentation
empty()
bool distribution_grid::empty () const
Definition at line 39 of file distribution_grid.cpp.
{
    return contents.empty();
}
References contents.
get_contents()
const std::vector< tripoint_abs_ms > & distribution_grid::get_contents () const inline
Definition at line 60 of file distribution_grid.h.
{
            return flat_contents;
        }
References flat_contents.
get_resource()
int distribution_grid::get_resource (bool recurse = true) const
Definition at line 121 of file distribution_grid.cpp.
{
    if( !recurse ) {
        if( cached_amount_here ) {
            return *cached_amount_here;
        } else {
            cached_amount_here = 0;
        }
    }
    int res = 0;
    std::vector<vehicle *> connected_vehicles;
    for( const auto &c : contents ) {
        for( const tile_location &loc : c.second ) {
            battery_tile *battery = active_tiles::furn_at<battery_tile>( loc.absolute );
            if( battery != nullptr ) {
                res += battery->get_resource();
                if( !recurse && cached_amount_here ) {
                    cached_amount_here = *cached_amount_here + res;
                }
                continue;
            }
            if( !recurse ) {
                continue;
            }
            vehicle_connector_tile *connector = active_tiles::furn_at<vehicle_connector_tile>( loc.absolute );
            if( connector != nullptr ) {
                for( const tripoint_abs_ms &veh_abs : connector->connected_vehicles ) {
                    vehicle *veh = vehicle::find_vehicle( veh_abs );
                    if( veh == nullptr ) {
                        // TODO: Disconnect
                        debugmsg( "lost vehicle at %s", veh_abs.to_string() );
                        continue;
                    }
                    connected_vehicles.push_back( veh );
                }
            }
        }
    }
    // TODO: Giga ugly. We only charge the first vehicle to get it to use its recursive graph traversal because it's inaccessible from here due to being a template method
    if( !connected_vehicles.empty() ) {
        res = connected_vehicles.front()->fuel_left( itype_battery, true );
    }
    if( !recurse ) {
        cached_amount_here = res;
    }
    return res;
}
References tile_location::absolute, c, cached_amount_here, vehicle_connector_tile::connected_vehicles, contents, debugmsg, vehicle::find_vehicle(), active_tiles::furn_at< battery_tile >(), active_tiles::furn_at< vehicle_connector_tile >(), battery_tile::get_resource(), itype_battery, and coords::coord_point< Point, Origin, Scale >::to_string().
Referenced by iexamine::check_power(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), iuse::report_grid_charge(), charge_watcher_tile::update_internal(), and iexamine::use_furn_fake_item().
mod_resource()
int distribution_grid::mod_resource (int amt, bool recurse = true)
Definition at line 72 of file distribution_grid.cpp.
{
    std::vector<vehicle *> connected_vehicles;
    for( const auto &c : contents ) {
        for( const tile_location &loc : c.second ) {
            battery_tile *battery = active_tiles::furn_at<battery_tile>( loc.absolute );
            if( battery != nullptr ) {
                int amt_before_battery = amt;
                amt = battery->mod_resource( amt );
                if( cached_amount_here ) {
                    cached_amount_here = *cached_amount_here + amt_before_battery - amt;
                }
                if( amt == 0 ) {
                    return 0;
                }
                continue;
            }
            if( !recurse ) {
                continue;
            }
            vehicle_connector_tile *connector = active_tiles::furn_at<vehicle_connector_tile>( loc.absolute );
            if( connector != nullptr ) {
                for( const tripoint_abs_ms &veh_abs : connector->connected_vehicles ) {
                    vehicle *veh = vehicle::find_vehicle( veh_abs );
                    if( veh == nullptr ) {
                        // TODO: Disconnect
                        debugmsg( "lost vehicle at %s", veh_abs.to_string() );
                        continue;
                    }
                    connected_vehicles.push_back( veh );
                }
            }
        }
    }
    // TODO: Giga ugly. We only charge the first vehicle to get it to use its recursive graph traversal because it's inaccessible from here due to being a template method
    if( !connected_vehicles.empty() ) {
        if( amt > 0 ) {
            amt = connected_vehicles.front()->charge_battery( amt, true );
        } else {
            amt = -connected_vehicles.front()->discharge_battery( -amt, true );
        }
    }
    return amt;
}
References tile_location::absolute, c, cached_amount_here, vehicle_connector_tile::connected_vehicles, contents, debugmsg, vehicle::find_vehicle(), active_tiles::furn_at< battery_tile >(), active_tiles::furn_at< vehicle_connector_tile >(), battery_tile::mod_resource(), and coords::coord_point< Point, Origin, Scale >::to_string().
Referenced by activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source(), solar_tile::update_internal(), steady_consumer_tile::update_internal(), and iexamine::use_furn_fake_item().
operator bool()
distribution_grid::operator bool () const explicit
Definition at line 44 of file distribution_grid.cpp.
{
    return !empty() && !submap_coords.empty();
}
update()
void distribution_grid::update (time_point to)
Definition at line 49 of file distribution_grid.cpp.
{
    for( const auto &c : contents ) {
        submap *sm = mb.lookup_submap( c.first );
        if( sm == nullptr ) {
            return;
        }
        for( const tile_location &loc : c.second ) {
            auto &active = sm->active_furniture[loc.on_submap];
            if( !active ) {
                debugmsg( "No active furniture at %s", loc.absolute.to_string() );
                contents.clear();
                return;
            }
            active->update( to, loc.absolute, *this );
        }
    }
}
References tile_location::absolute, active, c, contents, debugmsg, mapbuffer::lookup_submap(), mb, tile_location::on_submap, coords::sm, and coords::coord_point< Point, Origin, Scale >::to_string().
Friends And Related Function Documentation
distribution_grid_tracker
friend class distribution_grid_tracker friend
Definition at line 39 of file distribution_grid.h.
Member Data Documentation
cached_amount_here
cata::optional<int> distribution_grid::cached_amount_here mutable private
Definition at line 49 of file distribution_grid.h.
Referenced by get_resource(), and mod_resource().
contents
std::map<tripoint_abs_sm, std::vector<tile_location> > distribution_grid::contents private
Map of submap coords to points on this submap that contain an active tile.
Definition at line 45 of file distribution_grid.h.
Referenced by distribution_grid(), empty(), get_resource(), mod_resource(), and update().
flat_contents
std::vector<tripoint_abs_ms> distribution_grid::flat_contents private
Definition at line 46 of file distribution_grid.h.
Referenced by distribution_grid(), and get_contents().
mb
mapbuffer& distribution_grid::mb private
Definition at line 51 of file distribution_grid.h.
Referenced by distribution_grid(), and update().
submap_coords
std::vector<tripoint_abs_sm> distribution_grid::submap_coords private
Definition at line 47 of file distribution_grid.h.
Referenced by distribution_grid().
The documentation for this class was generated from the following files:
src/distribution_grid.h
src/distribution_grid.cpp