Cataclysm BN: basic_format_context< OutputIt, Char > Class Template Reference
basic_format_context< OutputIt, Char > Class Template Reference
#include <fmtlib_core.h>
Public Types
using char_type = Char
The character type for the output.
using iterator = OutputIt
using format_arg = basic_format_arg< basic_format_context >
using parse_context_type = basic_format_parse_context< Char >
template<typename T >
using formatter_type = formatter< T, char_type >
Public Member Functions
basic_format_context (const basic_format_context &)=delete
void operator= (const basic_format_context &)=delete
basic_format_context (OutputIt out, basic_format_args< basic_format_context > ctx_args, detail::locale_ref loc=detail::locale_ref())
Constructs a basic_format_context object.
format_arg arg (int id) const
format_arg arg (basic_string_view< char_type > name)
int arg_id (basic_string_view< char_type > name)
const basic_format_args< basic_format_context > & args () const
detail::error_handler error_handler ()
void on_error (const char *message)
iterator out ()
void advance_to (iterator it)
detail::locale_ref locale ()
Private Attributes
OutputIt out_
basic_format_args< basic_format_context > args_
detail::locale_ref loc_
Detailed Description
template<typename OutputIt, typename Char>
class basic_format_context< OutputIt, Char >
Definition at line 1688 of file fmtlib_core.h.
Member Typedef Documentation
char_type
template<typename OutputIt , typename Char > using basic_format_context< OutputIt, Char >::char_type = Char
The character type for the output.
Definition at line 1692 of file fmtlib_core.h.
format_arg
template<typename OutputIt , typename Char > using basic_format_context< OutputIt, Char >::format_arg = basic_format_arg<basic_format_context>
Definition at line 1701 of file fmtlib_core.h.
formatter_type
template<typename OutputIt , typename Char > template<typename T > using basic_format_context< OutputIt, Char >::formatter_type = formatter<T, char_type>
Definition at line 1703 of file fmtlib_core.h.
iterator
template<typename OutputIt , typename Char > using basic_format_context< OutputIt, Char >::iterator = OutputIt
Definition at line 1700 of file fmtlib_core.h.
parse_context_type
template<typename OutputIt , typename Char > using basic_format_context< OutputIt, Char >::parse_context_type = basic_format_parse_context<Char>
Definition at line 1702 of file fmtlib_core.h.
Constructor & Destructor Documentation
basic_format_context() [1/2]
template<typename OutputIt , typename Char > basic_format_context< OutputIt, Char >::basic_format_context (const basic_format_context< OutputIt, Char > &) delete
basic_format_context() [2/2]
template<typename OutputIt , typename Char > basic_format_context< OutputIt, Char >::basic_format_context (OutputIt out, basic_format_args< basic_format_context< OutputIt, Char > > ctx_args, detail::locale_ref loc = detail::locale_ref()) inline
Constructs a basic_format_context object.
References to the arguments are stored in the object so make sure they have appropriate lifetimes.
Definition at line 1711 of file fmtlib_core.h.
            : out_( out ), args_( ctx_args ), loc_( loc ) {}
Member Function Documentation
advance_to()
template<typename OutputIt , typename Char > void basic_format_context< OutputIt, Char >::advance_to (iterator it) inline
Definition at line 1742 of file fmtlib_core.h.
{
            if( !detail::is_back_insert_iterator<iterator>() ) {
                out_ = it;
            }
        }
References basic_format_context< OutputIt, Char >::out_.
arg() [1/2]
template<typename OutputIt , typename Char > format_arg basic_format_context< OutputIt, Char >::arg (basic_string_view< char_type > name) inline
Definition at line 1719 of file fmtlib_core.h.
{
            return args_.get( name );
        }
References basic_format_context< OutputIt, Char >::args_, and om_direction::name().
arg() [2/2]
template<typename OutputIt , typename Char > format_arg basic_format_context< OutputIt, Char >::arg (int id) const inline
Definition at line 1716 of file fmtlib_core.h.
{
            return args_.get( id );
        }
References basic_format_context< OutputIt, Char >::args_.
arg_id()
template<typename OutputIt , typename Char > int basic_format_context< OutputIt, Char >::arg_id (basic_string_view< char_type > name) inline
Definition at line 1722 of file fmtlib_core.h.
{
            return args_.get_id( name );
        }
References basic_format_context< OutputIt, Char >::args_, and om_direction::name().
args()
template<typename OutputIt , typename Char > const basic_format_args< basic_format_context > & basic_format_context< OutputIt, Char >::args () const inline
Definition at line 1725 of file fmtlib_core.h.
{
            return args_;
        }
References basic_format_context< OutputIt, Char >::args_.
error_handler()
template<typename OutputIt , typename Char > detail::error_handler basic_format_context< OutputIt, Char >::error_handler () inline
Definition at line 1729 of file fmtlib_core.h.
{
            return {};
        }
Referenced by basic_format_context< OutputIt, Char >::on_error().
locale()
template<typename OutputIt , typename Char > detail::locale_ref basic_format_context< OutputIt, Char >::locale () inline
Definition at line 1748 of file fmtlib_core.h.
{
            return loc_;
        }
References basic_format_context< OutputIt, Char >::loc_.
on_error()
template<typename OutputIt , typename Char > void basic_format_context< OutputIt, Char >::on_error (const char * message) inline
Definition at line 1732 of file fmtlib_core.h.
{
            error_handler().on_error( message );
        }
References basic_format_context< OutputIt, Char >::error_handler(), mapgen_defer::message, and detail::error_handler::on_error().
operator=()
template<typename OutputIt , typename Char > void basic_format_context< OutputIt, Char >::operator= (const basic_format_context< OutputIt, Char > &) delete
out()
template<typename OutputIt , typename Char > iterator basic_format_context< OutputIt, Char >::out () inline
Definition at line 1737 of file fmtlib_core.h.
                       {
            return out_;
        }
References basic_format_context< OutputIt, Char >::out_.
Referenced by formatter< detail::bigint >::format(), and detail::arg_formatter< OutputIt, Char >::operator()().
Member Data Documentation
args_
template<typename OutputIt , typename Char > basic_format_args<basic_format_context> basic_format_context< OutputIt, Char >::args_ private
Definition at line 1696 of file fmtlib_core.h.
Referenced by basic_format_context< OutputIt, Char >::arg(), basic_format_context< OutputIt, Char >::arg_id(), and basic_format_context< OutputIt, Char >::args().
loc_
template<typename OutputIt , typename Char > detail::locale_ref basic_format_context< OutputIt, Char >::loc_ private
Definition at line 1697 of file fmtlib_core.h.
Referenced by basic_format_context< OutputIt, Char >::locale().
out_
template<typename OutputIt , typename Char > OutputIt basic_format_context< OutputIt, Char >::out_ private
Definition at line 1695 of file fmtlib_core.h.
Referenced by basic_format_context< OutputIt, Char >::advance_to(), and basic_format_context< OutputIt, Char >::out().
The documentation for this class was generated from the following file:
src/fmtlib_core.h