Cataclysm BN: active_tile_data Class Reference
active_tile_data Class Reference abstract
#include <active_tile_data.h>
Public Member Functions
void update (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)
time_point get_last_updated ()
void set_last_updated (time_point t)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
virtual ~active_tile_data ()
virtual active_tile_data * clone () const =0
virtual const std::string & get_type () const =0
virtual void store (JsonOut &jsout) const =0
virtual void load (JsonObject &jo)=0
Static Public Member Functions
static active_tile_data * create (const std::string &id)
Protected Member Functions
virtual void update_internal (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)=0
Private Attributes
time_point last_updated
Detailed Description
Definition at line 14 of file active_tile_data.h.
Constructor & Destructor Documentation
~active_tile_data()
active_tile_data::~active_tile_data () virtual default
Member Function Documentation
clone()
virtual active_tile_data * active_tile_data::clone () const pure virtual
Implemented in null_tile_data, battery_tile, charge_watcher_tile, charger_tile, solar_tile, steady_consumer_tile, and vehicle_connector_tile.
Referenced by create(), and game::grabbed_furn_move().
create()
active_tile_data * active_tile_data::create (const std::string & id) static
Definition at line 395 of file active_tile_data.cpp.
{
    static const auto type_map = build_type_map();
    const auto iter = type_map.find( id );
    if( iter == type_map.end() ) {
        debugmsg( "Invalid active_tile_data id %s", id.c_str() );
        return new null_tile_data();
    }
    active_tile_data *new_tile = iter->second->clone();
    new_tile->last_updated = calendar::start_of_cataclysm;
    return new_tile;
}
References build_type_map(), clone(), debugmsg, last_updated, and calendar::start_of_cataclysm.
deserialize()
void active_tile_data::deserialize (JsonIn & jsin)
Definition at line 79 of file active_tile_data.cpp.
{
    JsonObject jo( jsin );
    jo.read( "last_updated", last_updated );
    load( jo );
}
References last_updated, load(), and JsonObject::read().
get_last_updated()
time_point active_tile_data::get_last_updated () inline
Definition at line 37 of file active_tile_data.h.
{
            return last_updated;
        }
References last_updated.
Referenced by charger_tile::update_internal(), solar_tile::update_internal(), and steady_consumer_tile::update_internal().
get_type()
virtual const std::string & active_tile_data::get_type () const pure virtual
Implemented in null_tile_data, battery_tile, charge_watcher_tile, charger_tile, solar_tile, steady_consumer_tile, and vehicle_connector_tile.
load()
virtual void active_tile_data::load (JsonObject & jo) pure virtual
Implemented in null_tile_data, battery_tile, charge_watcher_tile, charger_tile, solar_tile, steady_consumer_tile, and vehicle_connector_tile.
Referenced by deserialize().
serialize()
void active_tile_data::serialize (JsonOut & jsout) const
Definition at line 73 of file active_tile_data.cpp.
{
    jsout.member( "last_updated", last_updated );
    store( jsout );
}
References last_updated, JsonOut::member(), and store().
set_last_updated()
void active_tile_data::set_last_updated (time_point t) inline
Definition at line 40 of file active_tile_data.h.
{
            last_updated = t;
        }
References last_updated.
Referenced by grid_furn_transform_queue::apply().
store()
virtual void active_tile_data::store (JsonOut & jsout) const pure virtual
Implemented in null_tile_data, battery_tile, charge_watcher_tile, charger_tile, solar_tile, steady_consumer_tile, and vehicle_connector_tile.
Referenced by serialize().
update()
void active_tile_data::update (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) inline
Definition at line 32 of file active_tile_data.h.
{
            update_internal( to, p, grid );
            last_updated = to;
        }
References last_updated, and update_internal().
update_internal()
virtual void active_tile_data::update_internal (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) protected pure virtual
Parameters
to the time to update to
p absolute map coordinates (map::getabs) of the tile being updated
grid distribution grid being updated, containing the tile being updated
Implemented in battery_tile, charge_watcher_tile, charger_tile, solar_tile, steady_consumer_tile, vehicle_connector_tile, and null_tile_data.
Referenced by update().
Member Data Documentation
last_updated
time_point active_tile_data::last_updated private
Definition at line 20 of file active_tile_data.h.
Referenced by create(), deserialize(), get_last_updated(), serialize(), set_last_updated(), and update().
The documentation for this class was generated from the following files:
src/active_tile_data.h
src/active_tile_data.cpp