Cataclysm BN: invlet_favorites Class Reference
invlet_favorites Class Reference
#include <inventory.h>
Public Member Functions
invlet_favorites ()=default
invlet_favorites (const std::unordered_map< itype_id, std::string > &)
void set (char invlet, const itype_id &)
void erase (char invlet)
bool contains (char invlet, const itype_id &) const
std::string invlets_for (const itype_id &) const
const std::unordered_map< itype_id, std::string > & get_invlets_by_id () const
Private Attributes
std::unordered_map< itype_id, std::string > invlets_by_id
std::array< itype_id, 256 > ids_by_invlet
Detailed Description
Definition at line 71 of file inventory.h.
Constructor & Destructor Documentation
invlet_favorites() [1/2]
invlet_favorites::invlet_favorites () default
invlet_favorites() [2/2]
invlet_favorites::invlet_favorites (const std::unordered_map< itype_id, std::string > & map)
Definition at line 68 of file inventory.cpp.
{
    for( const auto &p : map ) {
        if( p.second.empty() ) {
            // The map gradually accumulates empty lists; remove those here
            continue;
        }
        invlets_by_id.insert( p );
        for( char invlet : p.second ) {
            uint8_t invlet_u = invlet;
            if( !ids_by_invlet[invlet_u].is_empty() ) {
                debugmsg( "Duplicate invlet: %s and %s both mapped to %c",
                          ids_by_invlet[invlet_u].str(), p.first.str(), invlet );
            }
            ids_by_invlet[invlet_u] = p.first;
        }
    }
}
References debugmsg, ids_by_invlet, and invlets_by_id.
Member Function Documentation
contains()
bool invlet_favorites::contains (char invlet, const itype_id & id) const
Definition at line 111 of file inventory.cpp.
{
    uint8_t invlet_u = invlet;
    return ids_by_invlet[invlet_u] == id;
}
References base_camps::id, and ids_by_invlet.
Referenced by set(), and inventory::update_invlet().
erase()
void invlet_favorites::erase (char invlet)
Definition at line 98 of file inventory.cpp.
{
    uint8_t invlet_u = invlet;
    const itype_id &id = ids_by_invlet[invlet_u];
    if( id.is_empty() ) {
        return;
    }
    std::string &invlets = invlets_by_id[id];
    std::string::iterator it = std::find( invlets.begin(), invlets.end(), invlet );
    invlets.erase( it );
    ids_by_invlet[invlet_u] = itype_id();
}
References detail::find(), base_camps::id, ids_by_invlet, invlets_by_id, and itype_id.
Referenced by inventory::reassign_item(), and set().
get_invlets_by_id()
const std::unordered_map< itype_id, std::string > & invlet_favorites::get_invlets_by_id () const
Definition at line 127 of file inventory.cpp.
{
    return invlets_by_id;
}
References invlets_by_id.
Referenced by inventory::json_save_invcache().
invlets_for()
std::string invlet_favorites::invlets_for (const itype_id & id) const
Definition at line 117 of file inventory.cpp.
{
    auto map_iterator = invlets_by_id.find( id );
    if( map_iterator == invlets_by_id.end() ) {
        return {};
    }
    return map_iterator->second;
}
References invlets_by_id.
Referenced by inventory::find_usable_cached_invlet().
set()
void invlet_favorites::set (char invlet, const itype_id & id)
Definition at line 87 of file inventory.cpp.
{
    if( contains( invlet, id ) ) {
        return;
    }
    erase( invlet );
    uint8_t invlet_u = invlet;
    ids_by_invlet[invlet_u] = id;
    invlets_by_id[id].push_back( invlet );
}
References contains(), erase(), base_camps::id, ids_by_invlet, and invlets_by_id.
Referenced by inventory::update_cache_with_item().
Member Data Documentation
ids_by_invlet
std::array<itype_id, 256> invlet_favorites::ids_by_invlet private
Definition at line 86 of file inventory.h.
Referenced by contains(), erase(), invlet_favorites(), and set().
invlets_by_id
std::unordered_map<itype_id, std::string> invlet_favorites::invlets_by_id private
Definition at line 85 of file inventory.h.
Referenced by erase(), get_invlets_by_id(), invlet_favorites(), invlets_for(), and set().
The documentation for this class was generated from the following files:
src/inventory.h
src/inventory.cpp