Cataclysm BN: countdown_actor Class Reference
countdown_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
countdown_actor (const std::string &type="countdown")
~countdown_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
ret_val< bool > can_use (const Character &, const item &it, bool, const tripoint &) const override
std::string get_name () const override
Returns the translated name of the action.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string name
if specified overrides default action name
int interval = 0
turns before countdown action (defaults to itype::countdown_interval)
std::string message
message if player sees activation with s replaced by item name
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 140 of file iuse_actor.h.
Constructor & Destructor Documentation
countdown_actor()
countdown_actor::countdown_actor (const std::string & type = "countdown") inline
Definition at line 143 of file iuse_actor.h.
: iuse_actor(type) {}
~countdown_actor()
countdown_actor::~countdown_actor () override default
Member Function Documentation
can_use()
ret_val< bool > countdown_actor::can_use (const Character & , const item & it, bool , const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 461 of file iuse_actor.cpp.
{
    if( it.active ) {
        return ret_val<bool>::make_failure( _( "It's already been triggered." ) );
    }
    return ret_val<bool>::make_success();
}
References _, item::active, ret_val< T >::make_failure(), and ret_val< T >::make_success().
clone()
std::unique_ptr< iuse_actor > countdown_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 430 of file iuse_actor.cpp.
{
    return std::make_unique<countdown_actor>( *this );
}
get_name()
std::string countdown_actor::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 471 of file iuse_actor.cpp.
{
    if( !name.empty() ) {
        return name;
    }
    return iuse_actor::get_name();
}
References iuse_actor::get_name(), and name.
info()
void countdown_actor::info (const item & it, std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 479 of file iuse_actor.cpp.
{
    dump.emplace_back( "TOOL", _( "Countdown: " ),
                       interval > 0 ? interval : it.type->countdown_interval );
    const auto countdown_actor = it.type->countdown_action.get_actor_ptr();
    if( countdown_actor != nullptr ) {
        countdown_actor->info( it, dump );
    }
}
References _, itype::countdown_action, itype::countdown_interval, use_function::get_actor_ptr(), info(), and item::type.
Referenced by info().
load()
void countdown_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 435 of file iuse_actor.cpp.
{
    obj.read( "name", name );
    obj.read( "interval", interval );
    obj.read( "message", message );
}
References message, name, and JsonObject::read().
use()
int countdown_actor::use (player & p, item & it, bool t, const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 442 of file iuse_actor.cpp.
{
    if( t ) {
        return 0;
    }
    if( it.active ) {
        return 0;
    }
    if( p.sees( pos ) && !message.empty() ) {
        p.add_msg_if_player( m_neutral, _( message ), it.tname() );
    }
    it.item_counter = interval > 0 ? interval : it.type->countdown_interval;
    it.active = true;
    return 0;
}
References _, item::active, player::add_msg_if_player(), itype::countdown_interval, interval, item::item_counter, m_neutral, message, Character::pos(), Character::sees(), item::tname(), and item::type.
Member Data Documentation
interval
int countdown_actor::interval = 0
turns before countdown action (defaults to itype::countdown_interval)
Definition at line 149 of file iuse_actor.h.
Referenced by use().
message
std::string countdown_actor::message
message if player sees activation with s replaced by item name
Definition at line 152 of file iuse_actor.h.
Referenced by load(), and use().
name
std::string countdown_actor::name
if specified overrides default action name
Definition at line 146 of file iuse_actor.h.
Referenced by get_name(), and load().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp