Cataclysm BN: item_location::impl::item_on_vehicle Class Reference
item_location::impl::item_on_vehicle Class Reference
Public Member Functions
item_on_vehicle (const vehicle_cursor &cur, item *which)
item_on_vehicle (const vehicle_cursor &cur, int idx)
void serialize (JsonOut &js) const override
item * unpack (int idx) const override
type where () const override
tripoint position () const override
std::string describe (const Character *ch) const override
item_location obtain (Character &ch, int qty) override
int obtain_cost (const Character &ch, int qty) const override
void remove_item () override
void make_dirty () override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual item_location parent_item () const
item * target () const
virtual bool valid () const
Private Attributes
vehicle_cursor cur
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 417 of file item_location.cpp.
Constructor & Destructor Documentation
item_on_vehicle() [1/2]
item_location::impl::item_on_vehicle::item_on_vehicle (const vehicle_cursor & cur, item * which) inline
Definition at line 423 of file item_location.cpp.
: impl(which), cur(cur) {}
item_on_vehicle() [2/2]
item_location::impl::item_on_vehicle::item_on_vehicle (const vehicle_cursor & cur, int idx) inline
Definition at line 424 of file item_location.cpp.
: impl(idx), cur(cur) {}
Member Function Documentation
describe()
std::string item_location::impl::item_on_vehicle::describe (const Character * ch) const inline override virtual
Implements item_location::impl.
Definition at line 449 of file item_location.cpp.
{
            vpart_position part_pos( cur.veh, cur.part );
            std::string res;
            if( auto label = part_pos.get_label() ) {
                res = colorize( *label, c_light_blue ) + " ";
            }
            if( auto cargo_part = part_pos.part_with_feature( "CARGO", true ) ) {
                res += cargo_part->part().name();
            } else {
                debugmsg( "item in vehicle part without cargo storage" );
            }
            if( ch ) {
                res += " " + direction_suffix( ch->pos(), part_pos.pos() );
            }
            return res;
        }
References c_light_blue, colorize(), cur, debugmsg, direction_suffix(), vpart_position::get_label(), vehicle_cursor::part, vpart_position::part_with_feature(), vpart_position::pos(), Character::pos(), and vehicle_cursor::veh.
make_dirty()
void item_location::impl::item_on_vehicle::make_dirty () inline override virtual
Implements item_location::impl.
Definition at line 509 of file item_location.cpp.
{
            if( what.get() != &cur.veh.part( cur.part ).base ) {
                idx = find_index( cur, what.get() );
            }
            needs_unpacking = true;
        }
References vehicle_part::base, cur, find_index(), item_location::impl::idx, item_location::impl::needs_unpacking, vehicle::part(), vehicle_cursor::part, vehicle_cursor::veh, and item_location::impl::what.
obtain()
item_location item_location::impl::item_on_vehicle::obtain (Character & ch, int qty) inline override virtual
Implements item_location::impl.
Definition at line 466 of file item_location.cpp.
{
            ch.moves -= obtain_cost( ch, qty );
            item obj = target()->split( qty );
            if( !obj.is_null() ) {
                return item_location( ch, &ch.i_add( obj, should_stack ) );
            } else {
                item *inv = &ch.i_add( *target(), should_stack );
                remove_item();
                return item_location( ch, inv );
            }
        }
References Character::i_add(), item::is_null(), item_location::item_location(), Creature::moves, obtain_cost(), remove_item(), item_location::impl::should_stack, item::split(), and item_location::impl::target().
obtain_cost()
int item_location::impl::item_on_vehicle::obtain_cost (const Character & ch, int qty) const inline override virtual
Implements item_location::impl.
Definition at line 479 of file item_location.cpp.
{
            if( !target() ) {
                return 0;
            }
            item obj = *target();
            obj = obj.split( qty );
            if( obj.is_null() ) {
                obj = *target();
            }
            int mv = dynamic_cast<const player *>( &ch )->item_handling_cost( obj, true,
                     VEHICLE_HANDLING_PENALTY );
            mv += 100 * rl_dist( ch.pos(), cur.veh.global_part_pos3( cur.part ) );
            // TODO: handle unpacking costs
            return mv;
        }
References cur, vehicle::global_part_pos3(), item::is_null(), vehicle_cursor::part, Character::pos(), rl_dist(), item::split(), item_location::impl::target(), vehicle_cursor::veh, and VEHICLE_HANDLING_PENALTY.
Referenced by obtain().
position()
tripoint item_location::impl::item_on_vehicle::position () const inline override virtual
Implements item_location::impl.
Definition at line 445 of file item_location.cpp.
{
            return cur.veh.global_part_pos3( cur.part );
        }
References cur, vehicle::global_part_pos3(), vehicle_cursor::part, and vehicle_cursor::veh.
Referenced by serialize().
remove_item()
void item_location::impl::item_on_vehicle::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 499 of file item_location.cpp.
{
            item &base = cur.veh.part( cur.part ).base;
            if( &base == target() ) {
                cur.veh.remove_part( cur.part ); // vehicle_part::base
            } else {
                cur.remove_item( *target() ); // item within CARGO
            }
            cur.veh.invalidate_mass();
        }
References vehicle_part::base, cur, vehicle::invalidate_mass(), vehicle::part(), vehicle_cursor::part, visitable< T >::remove_item(), vehicle::remove_part(), item_location::impl::target(), and vehicle_cursor::veh.
Referenced by obtain().
serialize()
void item_location::impl::item_on_vehicle::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 426 of file item_location.cpp.
{
            js.start_object();
            js.member( "type", "vehicle" );
            js.member( "pos", position() );
            js.member( "part", cur.part );
            if( target() != &cur.veh.part( cur.part ).base ) {
                js.member( "idx", find_index( cur, target() ) );
            }
            js.end_object();
        }
References vehicle_part::base, cur, JsonOut::end_object(), find_index(), JsonOut::member(), vehicle::part(), vehicle_cursor::part, position(), JsonOut::start_object(), item_location::impl::target(), and vehicle_cursor::veh.
unpack()
item * item_location::impl::item_on_vehicle::unpack (int idx) const inline override virtual
Implements item_location::impl.
Definition at line 437 of file item_location.cpp.
{
            return idx >= 0 ? retrieve_index( cur, idx ) : &cur.veh.part( cur.part ).base;
        }
References vehicle_part::base, cur, item_location::impl::idx, vehicle::part(), vehicle_cursor::part, retrieve_index(), and vehicle_cursor::veh.
where()
type item_location::impl::item_on_vehicle::where () const inline override virtual
Implements item_location::impl.
Definition at line 441 of file item_location.cpp.
{
            return type::vehicle;
        }
References item_location::vehicle.
Member Data Documentation
cur
vehicle_cursor item_location::impl::item_on_vehicle::cur private
Definition at line 420 of file item_location.cpp.
Referenced by describe(), make_dirty(), obtain_cost(), position(), remove_item(), serialize(), and unpack().
The documentation for this class was generated from the following file:
src/item_location.cpp