Cataclysm BN: mapgendata Class Reference
mapgendata Class Reference
Contains various information regarding the individual mapgen instance (generating a specific part of the map), used by the various mapgen functions to do their thing.
#include <mapgendata.h>
Public Member Functions
mapgendata (oter_id t_north, oter_id t_east, oter_id t_south, oter_id t_west, oter_id northeast, oter_id southeast, oter_id southwest, oter_id northwest, oter_id up, oter_id down, int z, const regional_settings &rsettings, map &mp, const oter_id &terrain_type, float density, const time_point &when, ::mission *miss)
mapgendata (const tripoint_abs_omt &over, map &m, float density, const time_point &when, ::mission *miss)
mapgendata (const mapgendata &other, const oter_id &other_id)
Creates a copy of this mapgen data, but stores a different terrain_type.
const oter_id & terrain_type () const
float monster_density () const
const time_point & when () const
::mission * mission () const
int zlevel () const
void set_dir (int dir_in, int val)
void fill (int val)
int & dir (int dir_in)
const oter_id & north () const
const oter_id & east () const
const oter_id & south () const
const oter_id & west () const
const oter_id & neast () const
const oter_id & seast () const
const oter_id & swest () const
const oter_id & nwest () const
const oter_id & above () const
const oter_id & below () const
const oter_id & neighbor_at (om_direction::type dir) const
void fill_groundcover ()
void square_groundcover (const point &p1, const point &p2)
ter_id groundcover ()
bool is_groundcover (const ter_id &iid) const
Public Attributes
oter_id t_nesw [8]
int n_fac = 0
int e_fac = 0
int s_fac = 0
int w_fac = 0
int ne_fac = 0
int se_fac = 0
int sw_fac = 0
int nw_fac = 0
oter_id t_above
oter_id t_below
const regional_settings & region
map & m
weighted_int_list< ter_id > default_groundcover
Private Attributes
oter_id terrain_type_
float density_
time_point when_
::mission * mission_
int zlevel_
Detailed Description
Contains various information regarding the individual mapgen instance (generating a specific part of the map), used by the various mapgen functions to do their thing.
Contains for example:
the map to generate the map onto,
the overmap terrain of the area to generate and its surroundings,
regional settings to use.
An instance of this class is passed through most of the mapgen code. If any of these functions need more information, add them here.
Definition at line 35 of file mapgendata.h.
Constructor & Destructor Documentation
mapgendata() [1/3]
mapgendata::mapgendata (oter_id t_north, oter_id t_east, oter_id t_south, oter_id t_west, oter_id northeast, oter_id southeast, oter_id southwest, oter_id northwest, oter_id up, oter_id down, int z, const regional_settings & rsettings, map & mp, const oter_id & terrain_type, float density, const time_point & when, ::mission * miss)
Definition at line 12 of file mapgendata.cpp.
    : terrain_type_( terrain_type ), density_( density ), when_( when ), mission_( miss ), zlevel_( z )
    , t_nesw{ north, east, south, west, northeast, southeast, southwest, northwest }
    , t_above( up )
    , t_below( down )
    , region( rsettings )
    , m( mp )
    , default_groundcover( region.default_groundcover )
{
}
mapgendata() [2/3]
mapgendata::mapgendata (const tripoint_abs_omt & over, map & m, float density, const time_point & when, ::mission * miss)
Definition at line 27 of file mapgendata.cpp.
    : mapgendata( overmap_buffer.ter( over + tripoint_north ),
                  overmap_buffer.ter( over + tripoint_east ),
                  overmap_buffer.ter( over + tripoint_south ),
                  overmap_buffer.ter( over + tripoint_west ),
                  overmap_buffer.ter( over + tripoint_north_east ),
                  overmap_buffer.ter( over + tripoint_south_east ),
                  overmap_buffer.ter( over + tripoint_south_west ),
                  overmap_buffer.ter( over + tripoint_north_west ),
                  overmap_buffer.ter( over + tripoint_above ),
                  overmap_buffer.ter( over + tripoint_below ),
                  over.z(), overmap_buffer.get_settings( over ), m,
                  overmap_buffer.ter( over ), density, when, miss )
{
}
mapgendata() [3/3]
mapgendata::mapgendata (const mapgendata & other, const oter_id & other_id)
Creates a copy of this mapgen data, but stores a different terrain_type.
Useful when you want to create a base map (e.g. forest/field/river), that gets refined later:
void generate_foo(mapgendata &dat) {
    mapgendata base_dat( dat, oter_id( "forest" ) );
    generate( base_dat );
    ... // refine map some more.
}
Definition at line 44 of file mapgendata.cpp.
                                                                         : mapgendata( other )
{
    terrain_type_ = other_id;
}
References other, and terrain_type_.
Member Function Documentation
above()
const oter_id & mapgendata::above () const inline
Definition at line 131 of file mapgendata.h.
{
            return t_above;
        }
Referenced by map::draw_connections(), map::draw_lab(), map::draw_mine(), map::draw_slimepit(), map::draw_temple(), and jmapgen_nested::neighborhood_check::test().
below()
const oter_id & mapgendata::below () const inline
Definition at line 134 of file mapgendata.h.
{
            return t_below;
        }
dir()
int & mapgendata::dir (int dir_in)
Definition at line 94 of file mapgendata.cpp.
{
    switch( dir_in ) {
        case 0:
            return n_fac;
        case 1:
            return e_fac;
        case 2:
            return s_fac;
        case 3:
            return w_fac;
        case 4:
            return ne_fac;
        case 5:
            return se_fac;
        case 6:
            return sw_fac;
        case 7:
            return nw_fac;
        default:
            debugmsg( "Invalid direction for mapgendata::set_dir.  dir_in = %d", dir_in );
            //return something just so the compiler doesn't freak out. Not really correct, though.
            return n_fac;
    }
}
References debugmsg, e_fac, n_fac, ne_fac, nw_fac, s_fac, se_fac, sw_fac, and w_fac.
Referenced by mapgen_forest(), mapgen_hellmouth(), mapgen_rock_partial(), and neighbor_at().
east()
const oter_id & mapgendata::east () const inline
Definition at line 110 of file mapgendata.h.
{
            return t_nesw[1];
        }
Referenced by map::draw_connections(), map::draw_lab(), map::draw_mine(), map::draw_office_tower(), mapgen_ants_generic(), mapgen_cavern(), mapgen_lake_shore(), mapgen_rift(), and neighbor_at().
fill()
void mapgendata::fill (int val)
Definition at line 82 of file mapgendata.cpp.
{
    n_fac = val;
    e_fac = val;
    s_fac = val;
    w_fac = val;
    ne_fac = val;
    se_fac = val;
    sw_fac = val;
    nw_fac = val;
}
References e_fac, n_fac, ne_fac, nw_fac, s_fac, se_fac, sw_fac, and w_fac.
Referenced by mapgen_forest().
fill_groundcover()
void mapgendata::fill_groundcover ()
Definition at line 125 of file mapgendata.cpp.
{
    m.draw_fill_background( default_groundcover );
}
References default_groundcover, map::draw_fill_background(), and m.
Referenced by map::draw_office_tower(), mapgen_forest(), mapgen_lake_shore(), mapgen_railroad(), mapgen_road(), and mapgen_subway().
groundcover()
ter_id mapgendata::groundcover ()
Definition at line 141 of file mapgendata.cpp.
{
    const ter_id *tid = default_groundcover.pick();
    return tid != nullptr ? *tid : t_null;
}
References default_groundcover, and t_null.
Referenced by map::draw_anthill(), mapgen_crater(), mapgen_field(), mapgen_highway(), mapgen_hive(), and mapgen_parking_lot().
is_groundcover()
bool mapgendata::is_groundcover (const ter_id & iid) const
Definition at line 130 of file mapgendata.cpp.
{
    for( const auto &pr : default_groundcover ) {
        if( pr.obj == iid ) {
            return true;
        }
    }
    return false;
}
References default_groundcover.
mission()
::mission * mapgendata::mission () const inline
Definition at line 96 of file mapgendata.h.
{
            return mission_;
        }
Referenced by jmapgen_npc::apply(), jmapgen_monster::apply(), and jmapgen_computer::apply().
monster_density()
float mapgendata::monster_density () const inline
Definition at line 90 of file mapgendata.h.
{
            return density_;
        }
Referenced by jmapgen_monster_group::apply(), map::draw_office_tower(), and mapgen_road().
neast()
const oter_id & mapgendata::neast () const inline
Definition at line 119 of file mapgendata.h.
{
            return t_nesw[4];
        }
Referenced by mapgen_lake_shore().
neighbor_at()
const oter_id & mapgendata::neighbor_at (om_direction::type dir) const
Definition at line 147 of file mapgendata.cpp.
{
    // TODO: De-uglify, implement proper conversion somewhere
    switch( dir ) {
        case om_direction::type::north:
            return north();
        case om_direction::type::east:
            return east();
        case om_direction::type::south:
            return south();
        case om_direction::type::west:
            return west();
        default:
            break;
    }
    debugmsg( "Tried to get neighbor from invalid direction %d", dir );
    return north();
}
References debugmsg, dir(), east(), om_direction::east, north(), om_direction::north, south(), om_direction::south, west(), and om_direction::west.
Referenced by mapgen_forest(), and jmapgen_nested::neighborhood_check::test().
north()
const oter_id & mapgendata::north () const inline
Definition at line 107 of file mapgendata.h.
{
            return t_nesw[0];
        }
Referenced by map::draw_connections(), map::draw_lab(), map::draw_mine(), map::draw_office_tower(), mapgen_ants_generic(), mapgen_cavern(), mapgen_lake_shore(), mapgen_rift(), and neighbor_at().
nwest()
const oter_id & mapgendata::nwest () const inline
Definition at line 128 of file mapgendata.h.
{
            return t_nesw[7];
        }
Referenced by mapgen_lake_shore().
seast()
const oter_id & mapgendata::seast () const inline
Definition at line 122 of file mapgendata.h.
{
            return t_nesw[5];
        }
Referenced by mapgen_lake_shore().
set_dir()
void mapgendata::set_dir (int dir_in, int val)
Definition at line 49 of file mapgendata.cpp.
{
    switch( dir_in ) {
        case 0:
            n_fac = val;
            break;
        case 1:
            e_fac = val;
            break;
        case 2:
            s_fac = val;
            break;
        case 3:
            w_fac = val;
            break;
        case 4:
            ne_fac = val;
            break;
        case 5:
            se_fac = val;
            break;
        case 6:
            sw_fac = val;
            break;
        case 7:
            nw_fac = val;
            break;
        default:
            debugmsg( "Invalid direction for mapgendata::set_dir.  dir_in = %d", dir_in );
            break;
    }
}
References debugmsg, e_fac, n_fac, ne_fac, nw_fac, s_fac, se_fac, sw_fac, and w_fac.
Referenced by mapgen_cavern(), and mapgen_crater().
south()
const oter_id & mapgendata::south () const inline
Definition at line 113 of file mapgendata.h.
{
            return t_nesw[2];
        }
Referenced by map::draw_connections(), map::draw_lab(), map::draw_mine(), map::draw_office_tower(), mapgen_ants_generic(), mapgen_cavern(), mapgen_lake_shore(), mapgen_rift(), and neighbor_at().
square_groundcover()
void mapgendata::square_groundcover (const point & p1, const point & p2)
Definition at line 120 of file mapgendata.cpp.
{
    m.draw_square_ter( default_groundcover, p1, p2 );
}
References default_groundcover, map::draw_square_ter(), and m.
swest()
const oter_id & mapgendata::swest () const inline
Definition at line 125 of file mapgendata.h.
{
            return t_nesw[6];
        }
Referenced by mapgen_lake_shore().
terrain_type()
const oter_id & mapgendata::terrain_type () const inline
Definition at line 87 of file mapgendata.h.
{
            return terrain_type_;
        }
Referenced by map::draw_anthill(), map::draw_connections(), map::draw_lab(), map::draw_map(), map::draw_mine(), map::draw_office_tower(), map::draw_slimepit(), map::draw_temple(), map::draw_triffid(), mapgen_function_json::generate(), mapgen_ants_curved(), mapgen_ants_generic(), mapgen_ants_straight(), mapgen_ants_tee(), mapgen_forest(), mapgen_forest_trail_curved(), mapgen_forest_trail_straight(), mapgen_forest_trail_tee(), mapgen_highway(), mapgen_railroad(), mapgen_railroad_bridge(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), mapgen_road(), mapgen_sewer_curved(), mapgen_sewer_straight(), mapgen_sewer_tee(), mapgen_subway(), and update_mapgen_function_json::update_map().
west()
const oter_id & mapgendata::west () const inline
Definition at line 116 of file mapgendata.h.
{
            return t_nesw[3];
        }
Referenced by map::draw_connections(), map::draw_lab(), map::draw_mine(), map::draw_office_tower(), mapgen_ants_generic(), mapgen_cavern(), mapgen_lake_shore(), mapgen_rift(), and neighbor_at().
when()
const time_point & mapgendata::when () const inline
Definition at line 93 of file mapgendata.h.
{
            return when_;
        }
Referenced by mapgen_ants_food(), mapgen_ants_generic(), mapgen_ants_larvae(), mapgen_ants_queen(), mapgen_cavern(), mapgen_crater(), mapgen_field(), mapgen_forest(), mapgen_forest_trail_curved(), mapgen_forest_trail_four_way(), mapgen_forest_trail_straight(), mapgen_forest_trail_tee(), mapgen_highway(), mapgen_hive(), mapgen_parking_lot(), mapgen_road(), mapgen_sewer_curved(), mapgen_sewer_four_way(), mapgen_sewer_straight(), and mapgen_sewer_tee().
zlevel()
int mapgendata::zlevel () const inline
Definition at line 99 of file mapgendata.h.
{
            // TODO: should be able to determine this from the map itself
            return zlevel_;
        }
Referenced by map::draw_lab(), map::draw_slimepit(), map::draw_temple(), mapgen_function_json_base::has_vehicle_collision(), jmapgen_alternativly< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), and mapgen_tutorial().
Member Data Documentation
default_groundcover
weighted_int_list<ter_id> mapgendata::default_groundcover
Definition at line 63 of file mapgendata.h.
Referenced by fill_groundcover(), groundcover(), is_groundcover(), and square_groundcover().
density_
float mapgendata::density_ private
Definition at line 39 of file mapgendata.h.
e_fac
int mapgendata::e_fac = 0
Definition at line 48 of file mapgendata.h.
Referenced by dir(), map::draw_mine(), map::draw_slimepit(), fill(), mapgen_cavern(), mapgen_crater(), mapgen_forest(), mapgen_hellmouth(), mapgen_rift(), mapgen_rock_partial(), and set_dir().
m
map& mapgendata::m
Definition at line 61 of file mapgendata.h.
Referenced by jmapgen_translate::apply(), jmapgen_field::apply(), jmapgen_npc::apply(), jmapgen_faction::apply(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_vending_machine::apply(), jmapgen_toilet::apply(), jmapgen_gaspump::apply(), jmapgen_liquid_item::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_spawn_item::apply(), jmapgen_trap::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_make_rubble::apply(), jmapgen_computer::apply(), jmapgen_sealed_item::apply(), jmapgen_zone::apply(), jmapgen_setmap::apply(), fill_groundcover(), mapgen_function_json::generate(), jmapgen_setmap::has_vehicle_collision(), mapgen_function_json_base::has_vehicle_collision(), jmapgen_alternativly< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), mapgen_ants_curved(), mapgen_ants_food(), mapgen_ants_four_way(), mapgen_ants_generic(), mapgen_ants_larvae(), mapgen_ants_queen(), mapgen_ants_straight(), mapgen_ants_tee(), mapgen_cavern(), mapgen_crater(), mapgen_field(), mapgen_forest(), mapgen_forest_trail_curved(), mapgen_forest_trail_four_way(), mapgen_forest_trail_straight(), mapgen_forest_trail_tee(), mapgen_hellmouth(), mapgen_highway(), mapgen_hive(), mapgen_lake_shore(), mapgen_null(), mapgen_open_air(), mapgen_parking_lot(), mapgen_railroad(), mapgen_railroad_bridge(), mapgen_rift(), mapgen_river_center(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), mapgen_road(), mapgen_rock(), mapgen_rock_partial(), mapgen_sewer_curved(), mapgen_sewer_four_way(), mapgen_sewer_straight(), mapgen_sewer_tee(), mapgen_subway(), mapgen_test(), mapgen_tutorial(), mapgen_function_json_nested::nest(), resolve_regional_terrain_and_furniture(), square_groundcover(), and update_mapgen_function_json::update_map().
mission_
::mission* mapgendata::mission_ private
Definition at line 41 of file mapgendata.h.
n_fac
int mapgendata::n_fac = 0
Definition at line 47 of file mapgendata.h.
Referenced by dir(), map::draw_mine(), map::draw_slimepit(), fill(), mapgen_crater(), mapgen_forest(), mapgen_rift(), mapgen_rock_partial(), and set_dir().
ne_fac
int mapgendata::ne_fac = 0
Definition at line 51 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
nw_fac
int mapgendata::nw_fac = 0
Definition at line 54 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
region
const regional_settings& mapgendata::region
Definition at line 59 of file mapgendata.h.
Referenced by mapgen_field(), mapgen_forest(), mapgen_forest_trail_curved(), mapgen_forest_trail_four_way(), mapgen_forest_trail_straight(), mapgen_forest_trail_tee(), mapgen_lake_shore(), and resolve_regional_terrain_and_furniture().
s_fac
int mapgendata::s_fac = 0
Definition at line 49 of file mapgendata.h.
Referenced by dir(), map::draw_mine(), map::draw_slimepit(), fill(), mapgen_cavern(), mapgen_crater(), mapgen_forest(), mapgen_hellmouth(), mapgen_rift(), mapgen_rock_partial(), and set_dir().
se_fac
int mapgendata::se_fac = 0
Definition at line 52 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
sw_fac
int mapgendata::sw_fac = 0
Definition at line 53 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
t_above
oter_id mapgendata::t_above
Definition at line 56 of file mapgendata.h.
t_below
oter_id mapgendata::t_below
Definition at line 57 of file mapgendata.h.
t_nesw
oter_id mapgendata::t_nesw[8]
Definition at line 45 of file mapgendata.h.
Referenced by map::draw_connections(), mapgen_cavern(), mapgen_crater(), mapgen_forest(), mapgen_hellmouth(), mapgen_hive(), mapgen_lake_shore(), mapgen_parking_lot(), mapgen_railroad(), mapgen_road(), mapgen_rock_partial(), and mapgen_subway().
terrain_type_
oter_id mapgendata::terrain_type_ private
Definition at line 38 of file mapgendata.h.
Referenced by mapgendata().
w_fac
int mapgendata::w_fac = 0
Definition at line 50 of file mapgendata.h.
Referenced by dir(), map::draw_mine(), map::draw_slimepit(), fill(), mapgen_crater(), mapgen_forest(), mapgen_rift(), mapgen_rock_partial(), and set_dir().
when_
time_point mapgendata::when_ private
Definition at line 40 of file mapgendata.h.
zlevel_
int mapgendata::zlevel_ private
Definition at line 42 of file mapgendata.h.
The documentation for this class was generated from the following files:
src/mapgendata.h
src/mapgendata.cpp