Cataclysm BN: uilist_callback Class Reference
uilist_callback Class Reference
uilist::query() handles most input events first, and then passes the event to the callback if it can't handle it.
#include <ui.h>
Public Member Functions
virtual void select (uilist *)
After a new item is selected, call this once.
virtual bool key (const input_context &, const input_event &, int, uilist *)
virtual void refresh (uilist *)
virtual ~uilist_callback ()=default
Detailed Description
uilist::query() handles most input events first, and then passes the event to the callback if it can't handle it.
The callback returninig a boolean false signifies that the callback can't "handle the event completely". This is unchanged before or after the PR.
Definition at line 166 of file ui.h.
Constructor & Destructor Documentation
~uilist_callback()
virtual uilist_callback::~uilist_callback () virtual default
Member Function Documentation
key()
virtual bool uilist_callback::key (const input_context & , const input_event & , int , uilist *) inline virtual
Reimplemented in spellcasting_callback, wish_mutate_callback, wish_monster_callback, wish_item_callback, debug_menu::effect_select_callback, debug_menu::effect_edit_callback, ma_style_callback, actmenu_cb, and overmap_ui::map_notes_callback.
Definition at line 174 of file ui.h.
{
            return false;
        }
Referenced by query_destination_callback::draw_squares(), and uilist::query().
refresh()
virtual void uilist_callback::refresh (uilist *) inline virtual
Reimplemented in query_destination_callback, spellcasting_callback, spellbook_callback, teleporter_callback, wish_mutate_callback, wish_monster_callback, wish_item_callback, and debug_menu::effect_select_callback.
Definition at line 178 of file ui.h.
{}
Referenced by uilist::show().
select()
virtual void uilist_callback::select (uilist *) inline virtual
After a new item is selected, call this once.
Reimplemented in overmap_ui::map_notes_callback, pointmenu_cb, and wish_item_callback.
Definition at line 173 of file ui.h.
{}
Referenced by uilist::filterlist(), uilist::query(), and uilist::scrollby().
The documentation for this class was generated from the following file:
src/ui.h