Cataclysm BN: known_magic Class Reference
known_magic Class Reference
#include <magic.h>
Public Member Functions
known_magic ()
void learn_spell (const std::string &sp, Character &guy, bool force=false)
void learn_spell (const spell_id &sp, Character &guy, bool force=false)
void learn_spell (const spell_type *sp, Character &guy, bool force=false)
void forget_spell (const std::string &sp)
void forget_spell (const spell_id &sp)
int time_to_learn_spell (const Character &guy, const spell_id &sp) const
int time_to_learn_spell (const Character &guy, const std::string &str) const
bool can_learn_spell (const Character &guy, const spell_id &sp) const
bool knows_spell (const std::string &sp) const
bool knows_spell (const spell_id &sp) const
bool knows_spell () const
std::vector< spell_id > spells () const
spell & get_spell (const spell_id &sp)
int select_spell (const Character &guy)
std::vector< spell * > get_spells ()
int available_mana () const
int max_mana (const Character &guy) const
void mod_mana (const Character &guy, int add_mana)
void set_mana (int new_mana)
double mana_regen_rate (const Character &guy) const
Mana regeneration rate (units per turn).
void update_mana (const Character &guy, double turns)
bool has_enough_energy (const Character &guy, spell &sp) const
void on_mutation_gain (const trait_id &mid, Character &guy)
void on_mutation_loss (const trait_id &mid)
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
bool set_invlet (const spell_id &sp, int invlet, const std::set< int > &used_invlets)
void rem_invlet (const spell_id &sp)
Public Attributes
bool casting_ignore = false
Private Member Functions
int get_spellname_max_width ()
int get_invlet (const spell_id &sp, std::set< int > &used_invlets)
Private Attributes
std::map< spell_id, spell > spellbook
std::map< spell_id, int > invlets
int mana_base = 0
int mana = 0
Detailed Description
Definition at line 446 of file magic.h.
Constructor & Destructor Documentation
known_magic()
known_magic::known_magic ()
Definition at line 1250 of file magic.cpp.
{
    mana_base = 1000;
    mana = mana_base;
}
References mana, and mana_base.
Member Function Documentation
available_mana()
int known_magic::available_mana () const
Definition at line 1417 of file magic.cpp.
{
    return mana;
}
References mana.
Referenced by has_enough_energy().
can_learn_spell()
bool known_magic::can_learn_spell (const Character & guy, const spell_id & sp) const
Definition at line 1389 of file magic.cpp.
{
    const spell_type &sp_t = sp.obj();
    if( sp_t.spell_class == trait_NONE ) {
        return true;
    }
    return !guy.has_opposite_trait( sp_t.spell_class );
}
References Character::has_opposite_trait(), string_id< T >::obj(), spell_type::spell_class, and trait_NONE.
Referenced by learn_spell().
deserialize()
void known_magic::deserialize (JsonIn & jsin)
Definition at line 1276 of file magic.cpp.
{
    JsonObject data = jsin.get_object();
    data.read( "mana", mana );
    for( JsonObject jo : data.get_array( "spellbook" ) ) {
        std::string id = jo.get_string( "id" );
        spell_id sp = spell_id( id );
        int xp = jo.get_int( "xp" );
        if( !sp.is_valid() ) {
            debugmsg( "Skipping spell with invalid id: %s", sp.c_str() );
        } else if( knows_spell( sp ) ) {
            spellbook[sp].set_exp( xp );
        } else {
            spellbook.emplace( sp, spell( sp, xp ) );
        }
    }
    data.read( "invlets", invlets );
}
References string_id< T >::c_str(), debugmsg, JsonObject::get_array(), JsonIn::get_object(), invlets, string_id< T >::is_valid(), knows_spell(), mana, JsonObject::read(), spell_id, and spellbook.
forget_spell() [1/2]
void known_magic::forget_spell (const spell_id & sp)
Definition at line 1379 of file magic.cpp.
{
    if( !knows_spell( sp ) ) {
        debugmsg( "Can't forget a spell you don't know!" );
        return;
    }
    add_msg( m_bad, _( "All knowledge of %s leaves you." ), sp->name );
    spellbook.erase( sp );
}
References _, add_msg(), debugmsg, knows_spell(), m_bad, spell_type::name, and spellbook.
forget_spell() [2/2]
void known_magic::forget_spell (const std::string & sp)
Definition at line 1374 of file magic.cpp.
{
    forget_spell( spell_id( sp ) );
}
References forget_spell(), and spell_id.
Referenced by forget_spell(), and on_mutation_loss().
get_invlet()
int known_magic::get_invlet (const spell_id & sp, std::set< int > & used_invlets) private
Definition at line 1789 of file magic.cpp.
{
    auto found = invlets.find( sp );
    if( found != invlets.end() ) {
        return found->second;
    }
    for( const std::pair<const spell_id, int> &invlet_pair : invlets ) {
        used_invlets.emplace( invlet_pair.second );
    }
    for( int i = 'a'; i <= 'z'; i++ ) {
        if( used_invlets.count( i ) == 0 ) {
            used_invlets.emplace( i );
            return i;
        }
    }
    for( int i = 'A'; i <= 'Z'; i++ ) {
        if( used_invlets.count( i ) == 0 ) {
            used_invlets.emplace( i );
            return i;
        }
    }
    for( int i = '!'; i <= '-'; i++ ) {
        if( used_invlets.count( i ) == 0 ) {
            used_invlets.emplace( i );
            return i;
        }
    }
    return 0;
}
References invlets.
Referenced by select_spell().
get_spell()
spell & known_magic::get_spell (const spell_id & sp)
Definition at line 1398 of file magic.cpp.
{
    if( !knows_spell( sp ) ) {
        static spell bugged_spell;
        debugmsg( "ERROR: Tried to get unknown spell" );
        return bugged_spell;
    }
    return spellbook.at( sp );
}
References debugmsg, knows_spell(), and spellbook.
Referenced by on_mutation_gain().
get_spellname_max_width()
int known_magic::get_spellname_max_width () private
Definition at line 1511 of file magic.cpp.
{
    int width = 0;
    for( const spell *sp : get_spells() ) {
        width = std::max( width, utf8_width( sp->name() ) );
    }
    return width;
}
References get_spells(), and utf8_width().
Referenced by select_spell().
get_spells()
std::vector< spell * > known_magic::get_spells ()
Definition at line 1408 of file magic.cpp.
{
    std::vector<spell *> spells;
    for( auto &spell_pair : spellbook ) {
        spells.emplace_back( &spell_pair.second );
    }
    return spells;
}
References spellbook, and spells().
Referenced by get_spellname_max_width(), on_mutation_loss(), and select_spell().
has_enough_energy()
bool known_magic::has_enough_energy (const Character & guy, spell & sp) const
Definition at line 1473 of file magic.cpp.
{
    int cost = sp.energy_cost( guy );
    switch( sp.energy_source() ) {
        case mana_energy:
            return available_mana() >= cost;
        case bionic_energy:
            return guy.get_power_level() >= units::from_kilojoule( cost );
        case stamina_energy:
            return guy.get_stamina() >= cost;
        case hp_energy:
            for( const std::pair<const bodypart_str_id, bodypart> &elem : guy.get_body() ) {
                if( elem.second.get_hp_cur() > cost ) {
                    return true;
                }
            }
            return false;
        case fatigue_energy:
            return guy.get_fatigue() < fatigue_levels::exhausted;
        case none_energy:
            return true;
        default:
            return false;
    }
}
References available_mana(), bionic_energy, spell::energy_cost(), spell::energy_source(), exhausted, fatigue_energy, units::from_kilojoule(), Creature::get_body(), Character::get_fatigue(), Character::get_power_level(), Character::get_stamina(), hp_energy, mana_energy, none_energy, and stamina_energy.
knows_spell() [1/3]
bool known_magic::knows_spell () const
Definition at line 1306 of file magic.cpp.
{
    return !spellbook.empty();
}
References spellbook.
Referenced by deserialize(), forget_spell(), get_spell(), and knows_spell().
knows_spell() [2/3]
bool known_magic::knows_spell (const spell_id & sp) const
Definition at line 1301 of file magic.cpp.
{
    return spellbook.count( sp ) == 1;
}
References spellbook.
knows_spell() [3/3]
bool known_magic::knows_spell (const std::string & sp) const
Definition at line 1296 of file magic.cpp.
{
    return knows_spell( spell_id( sp ) );
}
References knows_spell(), and spell_id.
learn_spell() [1/3]
void known_magic::learn_spell (const spell_id & sp, Character & guy, bool force = false)
Definition at line 1316 of file magic.cpp.
{
    learn_spell( &sp.obj(), guy, force );
}
References learn_spell(), and string_id< T >::obj().
learn_spell() [2/3]
void known_magic::learn_spell (const spell_type * sp, Character & guy, bool force = false)
Definition at line 1321 of file magic.cpp.
{
    if( !sp->is_valid() ) {
        debugmsg( "Tried to learn invalid spell" );
        return;
    }
    if( guy.magic->knows_spell( sp->id ) ) {
        // you already know the spell
        return;
    }
    spell temp_spell( sp->id );
    if( !temp_spell.is_valid() ) {
        debugmsg( "Tried to learn invalid spell" );
        return;
    }
    if( !force && sp->spell_class != trait_NONE ) {
        if( can_learn_spell( guy, sp->id ) && !guy.has_trait( sp->spell_class ) ) {
            std::string trait_cancel;
            for( const trait_id &cancel : sp->spell_class->cancels ) {
                if( cancel == sp->spell_class->cancels.back() &&
                    sp->spell_class->cancels.back() != sp->spell_class->cancels.front() ) {
                    trait_cancel = string_format( _( "%s and %s" ), trait_cancel, cancel->name() );
                } else if( cancel == sp->spell_class->cancels.front() ) {
                    trait_cancel = cancel->name();
                    if( sp->spell_class->cancels.size() == 1 ) {
                        trait_cancel = string_format( "%s: %s", trait_cancel, cancel->desc() );
                    }
                } else {
                    trait_cancel = string_format( _( "%s, %s" ), trait_cancel, cancel->name() );
                }
                if( cancel == sp->spell_class->cancels.back() ) {
                    trait_cancel += ".";
                }
            }
            if( query_yn(
                    _( "Learning this spell will make you a\n\n%s: %s\n\nand lock you out of\n\n%s\n\nContinue?" ),
                    sp->spell_class->name(), sp->spell_class->desc(), trait_cancel ) ) {
                guy.set_mutation( sp->spell_class );
                guy.on_mutation_gain( sp->spell_class );
                guy.add_msg_if_player( sp->spell_class.obj().desc() );
            } else {
                return;
            }
        }
    }
    if( force || can_learn_spell( guy, sp->id ) ) {
        spellbook.emplace( sp->id, temp_spell );
        guy.add_msg_if_player( m_good, _( "You learned %s!" ), sp->name );
    } else {
        guy.add_msg_if_player( m_bad, _( "You can't learn this spell." ) );
    }
}
References _, Creature::add_msg_if_player(), can_learn_spell(), cancel, mutation_branch::cancels, debugmsg, mutation_branch::desc(), Character::has_trait(), spell_type::id, spell_type::is_valid(), spell::is_valid(), m_bad, m_good, Character::magic, spell_type::name, mutation_branch::name(), string_id< T >::obj(), Character::on_mutation_gain(), query_yn(), Character::set_mutation(), spell_type::spell_class, spellbook, string_format(), and trait_NONE.
learn_spell() [3/3]
void known_magic::learn_spell (const std::string & sp, Character & guy, bool force = false)
Definition at line 1311 of file magic.cpp.
{
    learn_spell( spell_id( sp ), guy, force );
}
References learn_spell(), and spell_id.
Referenced by learn_spell(), and on_mutation_gain().
mana_regen_rate()
double known_magic::mana_regen_rate (const Character & guy) const
Mana regeneration rate (units per turn).
Definition at line 1445 of file magic.cpp.
{
    // mana should replenish in 8 hours.
    double full_replenish = to_turns<double>( 8_hours );
    double capacity = max_mana( guy );
    double mut_mul = guy.mutation_value( "mana_regen_multiplier" );
    double natural_regen = std::max( 0.0, capacity * mut_mul / full_replenish );
    double ench_bonus = guy.bonus_from_enchantments( natural_regen, enchant_vals::mod::MANA_REGEN );
    return std::max( 0.0, natural_regen + ench_bonus );
}
References Character::bonus_from_enchantments(), enchant_vals::MANA_REGEN, max_mana(), and Character::mutation_value().
Referenced by update_mana().
max_mana()
int known_magic::max_mana (const Character & guy) const
Definition at line 1432 of file magic.cpp.
{
    float int_bonus = ( ( 0.2f + guy.get_int() * 0.1f ) - 1.0f ) * mana_base;
    float mut_mul = guy.mutation_value( "mana_multiplier" );
    float mut_add = guy.mutation_value( "mana_modifier" );
    int natural_cap = std::max( 0.0f, ( ( mana_base + int_bonus ) * mut_mul ) + mut_add );
    int bp_penalty = units::to_kilojoule( guy.get_power_level() );
    int ench_bonus = guy.bonus_from_enchantments( natural_cap, enchant_vals::mod::MANA_CAP, true );
    return std::max( 0, natural_cap - bp_penalty + ench_bonus );
}
References Character::bonus_from_enchantments(), Character::get_int(), Character::get_power_level(), mana_base, enchant_vals::MANA_CAP, Character::mutation_value(), and units::to_kilojoule().
Referenced by mana_regen_rate(), and mod_mana().
mod_mana()
void known_magic::mod_mana (const Character & guy, int add_mana)
Definition at line 1427 of file magic.cpp.
{
    set_mana( clamp( mana + add_mana, 0, max_mana( guy ) ) );
}
References clamp(), mana, max_mana(), and set_mana().
Referenced by update_mana().
on_mutation_gain()
void known_magic::on_mutation_gain (const trait_id & mid, Character & guy)
Definition at line 1855 of file magic.cpp.
{
    for( const std::pair<const spell_id, int> &sp : mid->spells_learned ) {
        learn_spell( sp.first, guy, true );
        spell &temp_sp = get_spell( sp.first );
        for( int level = 0; level < sp.second; level++ ) {
            temp_sp.gain_level();
        }
    }
}
References spell::gain_level(), get_spell(), learn_spell(), and mutation_branch::spells_learned.
on_mutation_loss()
void known_magic::on_mutation_loss (const trait_id & mid)
Definition at line 1866 of file magic.cpp.
{
    std::vector<spell_id> spells_to_forget;
    for( const spell *sp : get_spells() ) {
        if( sp->is_spell_class( mid ) ) {
            spells_to_forget.emplace_back( sp->id() );
        }
    }
    for( const spell_id &sp_id : spells_to_forget ) {
        forget_spell( sp_id );
    }
}
References forget_spell(), and get_spells().
rem_invlet()
void known_magic::rem_invlet (const spell_id & sp)
Definition at line 1784 of file magic.cpp.
{
    invlets.erase( sp );
}
References invlets.
select_spell()
int known_magic::select_spell (const Character & guy)
Definition at line 1819 of file magic.cpp.
{
    // max width of spell names
    const int max_spell_name_length = get_spellname_max_width();
    std::vector<spell *> known_spells = get_spells();
    uilist spell_menu;
    spell_menu.w_height_setup = [&]() -> int {
        return clamp( static_cast<int>( known_spells.size() ), 24, TERMY * 9 / 10 );
    };
    const auto calc_width = []() -> int {
        return std::max( 80, TERMX * 3 / 8 );
    };
    spell_menu.w_width_setup = calc_width;
    spell_menu.pad_right_setup = [&]() -> int {
        return calc_width() - max_spell_name_length - 5;
    };
    spell_menu.title = _( "Choose a Spell" );
    spell_menu.hilight_disabled = true;
    spellcasting_callback cb( known_spells, casting_ignore );
    spell_menu.callback = &cb;
    std::set<int> used_invlets{ cb.reserved_invlets };
    for( size_t i = 0; i < known_spells.size(); i++ ) {
        spell_menu.addentry( static_cast<int>( i ), known_spells[i]->can_cast( guy ),
                             get_invlet( known_spells[i]->id(), used_invlets ), known_spells[i]->name() );
    }
    spell_menu.query();
    casting_ignore = static_cast<spellcasting_callback *>( spell_menu.callback )->casting_ignore;
    return spell_menu.ret;
}
References _, uilist::addentry(), uilist::callback, casting_ignore, clamp(), get_invlet(), get_spellname_max_width(), get_spells(), uilist::hilight_disabled, om_direction::name(), uilist::pad_right_setup, uilist::query(), spellcasting_callback::reserved_invlets, uilist::ret, TERMX, TERMY, uilist::title, uilist::w_height_setup, and uilist::w_width_setup.
serialize()
void known_magic::serialize (JsonOut & json) const
Definition at line 1256 of file magic.cpp.
{
    json.start_object();
    json.member( "mana", mana );
    json.member( "spellbook" );
    json.start_array();
    for( auto pair : spellbook ) {
        json.start_object();
        json.member( "id", pair.second.id() );
        json.member( "xp", pair.second.xp() );
        json.end_object();
    }
    json.end_array();
    json.member( "invlets", invlets );
    json.end_object();
}
References JsonOut::end_array(), JsonOut::end_object(), invlets, mana, JsonOut::member(), spellbook, JsonOut::start_array(), and JsonOut::start_object().
set_invlet()
bool known_magic::set_invlet (const spell_id & sp, int invlet, const std::set< int > & used_invlets)
Definition at line 1775 of file magic.cpp.
{
    if( used_invlets.count( invlet ) > 0 ) {
        return false;
    }
    invlets[sp] = invlet;
    return true;
}
References invlets.
set_mana()
void known_magic::set_mana (int new_mana)
Definition at line 1422 of file magic.cpp.
{
    mana = new_mana;
}
References mana.
Referenced by mod_mana().
spells()
std::vector< spell_id > known_magic::spells () const
Definition at line 1463 of file magic.cpp.
{
    std::vector<spell_id> spell_ids;
    for( auto pair : spellbook ) {
        spell_ids.emplace_back( pair.first );
    }
    return spell_ids;
}
References spellbook.
Referenced by get_spells().
time_to_learn_spell() [1/2]
int known_magic::time_to_learn_spell (const Character & guy, const spell_id & sp) const
Definition at line 1504 of file magic.cpp.
{
    const int base_time = to_moves<int>( 30_minutes );
    return base_time * ( 1.0 + sp->difficulty / ( 1.0 + ( guy.get_int() - 8.0 ) / 8.0 ) +
                         ( guy.get_skill_level( sp->skill ) / 10.0 ) );
}
References spell_type::difficulty, Character::get_int(), Character::get_skill_level(), and spell_type::skill.
Referenced by time_to_learn_spell().
time_to_learn_spell() [2/2]
int known_magic::time_to_learn_spell (const Character & guy, const std::string & str) const
Definition at line 1499 of file magic.cpp.
{
    return time_to_learn_spell( guy, spell_id( str ) );
}
References spell_id, and time_to_learn_spell().
update_mana()
void known_magic::update_mana (const Character & guy, double turns)
Definition at line 1458 of file magic.cpp.
{
    mod_mana( guy, mana_regen_rate( guy ) * turns );
}
References mana_regen_rate(), and mod_mana().
Member Data Documentation
casting_ignore
bool known_magic::casting_ignore = false
Definition at line 459 of file magic.h.
Referenced by select_spell().
invlets
std::map<spell_id, int> known_magic::invlets private
Definition at line 452 of file magic.h.
Referenced by deserialize(), get_invlet(), rem_invlet(), serialize(), and set_invlet().
mana
int known_magic::mana = 0 private
Definition at line 456 of file magic.h.
Referenced by available_mana(), deserialize(), known_magic(), mod_mana(), serialize(), and set_mana().
mana_base
int known_magic::mana_base = 0 private
Definition at line 454 of file magic.h.
Referenced by known_magic(), and max_mana().
spellbook
std::map<spell_id, spell> known_magic::spellbook private
Definition at line 450 of file magic.h.
Referenced by deserialize(), forget_spell(), get_spell(), get_spells(), knows_spell(), learn_spell(), serialize(), and spells().
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp