Cataclysm BN: mission_data Class Reference
mission_data Class Reference
#include <mission_companion.h>
Public Member Functions
mission_data ()
void add (const std::string &id, const std::string &name_display, const cata::optional< point > &dir, const std::string &text, bool priority=false, bool possible=true)
Adds the id's to the correct vectors (i.e.
void add_return (const std::string &id, const std::string &name_display, const cata::optional< point > &dir, const std::string &text, bool possible=true)
void add_start (const std::string &id, const std::string &name_display, const cata::optional< point > &dir, const std::string &text, bool possible=true)
void add (const std::string &id, const std::string &name_display="", const std::string &text="")
Public Attributes
std::vector< std::vector< mission_entry > > entries
mission_entry cur_key
Detailed Description
Definition at line 37 of file mission_companion.h.
Constructor & Destructor Documentation
mission_data()
mission_data::mission_data ()
Definition at line 92 of file mission_companion.cpp.
{
    for( int tab_num = base_camps::TAB_MAIN; tab_num != base_camps::TAB_NW + 3; tab_num++ ) {
        std::vector<mission_entry> k;
        entries.push_back( k );
    }
}
References entries, base_camps::TAB_MAIN, and base_camps::TAB_NW.
Member Function Documentation
add() [1/2]
void mission_data::add (const std::string & id, const std::string & name_display, const cata::optional< point > & dir, const std::string & text, bool priority = false, bool possible = true)
Adds the id's to the correct vectors (i.e.
tabs) in the UI.
Parameters
id is the mission reference
name_display is string displayed
dir is the direction of the expansion from the central camp, i.e. "[N]"
priority turns the mission key yellow and pushes to front of main tab
possible grays the mission key when false and makes it impossible to select
Definition at line 2137 of file mission_companion.cpp.
{
    mission_entry miss;
    miss.id = id;
    if( name_display.empty() ) {
        miss.name_display = id;
    } else {
        miss.name_display = name_display;
    }
    miss.dir = dir;
    miss.text = text;
    miss.priority = priority;
    miss.possible = possible;
    if( priority ) {
        entries[0].push_back( miss );
    }
    if( !possible ) {
        entries[10].push_back( miss );
    }
    const point direction = dir ? *dir : base_camps::base_dir;
    const int tab_order = base_camps::all_directions.at( direction ).tab_order;
    entries[tab_order + 1].emplace_back( miss );
}
References base_camps::all_directions, base_camps::base_dir, mission_entry::dir, entries, base_camps::id, mission_entry::id, mission_entry::name_display, mission_entry::possible, mission_entry::priority, and mission_entry::text.
Referenced by add(), add_return(), add_start(), talk_function::commune_carpentry(), talk_function::commune_farmfield(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::commune_refuge_caravan(), basecamp::get_available_missions(), talk_function::scavenger_patrol(), and talk_function::scavenger_raid().
add() [2/2]
void mission_data::add (const std::string & id, const std::string & name_display = "", const std::string & text = "")
Definition at line 2122 of file mission_companion.cpp.
{
    add( id, name_display, cata::nullopt, text, false, true );
}
References add(), and cata::nullopt.
add_return()
void mission_data::add_return (const std::string & id, const std::string & name_display, const cata::optional< point > & dir, const std::string & text, bool possible = true)
Definition at line 2127 of file mission_companion.cpp.
{
    add( id, name_display, dir, text, true, possible );
}
References add().
Referenced by basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
add_start()
void mission_data::add_start (const std::string & id, const std::string & name_display, const cata::optional< point > & dir, const std::string & text, bool possible = true)
Definition at line 2132 of file mission_companion.cpp.
{
    add( id, name_display, dir, text, false, possible );
}
References add().
Referenced by basecamp::add_available_recipes(), basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
Member Data Documentation
cur_key
mission_entry mission_data::cur_key
Definition at line 41 of file mission_companion.h.
Referenced by talk_function::basecamp_mission(), iexamine::bulletin_board(), talk_function::companion_mission(), and talk_function::display_and_choose_opts().
entries
std::vector<std::vector<mission_entry> > mission_data::entries
Definition at line 40 of file mission_companion.h.
Referenced by add(), talk_function::display_and_choose_opts(), and mission_data().
The documentation for this class was generated from the following files:
src/mission_companion.h
src/mission_companion.cpp