Cataclysm BN: scenario Class Reference
scenario Class Reference
#include <scenario.h>
Public Member Functions
scenario ()
void check_definition () const
Check that item definitions are valid.
const string_id< scenario > & ident () const
std::string gender_appropriate_name (bool male) const
std::string description (bool male) const
start_location_id start_location () const
start_location_id random_start_location () const
std::string start_name () const
int start_location_count () const
int start_location_targets_count () const
vproto_id vehicle () const
const profession_id & weighted_random_profession () const
std::vector< profession_id > permitted_professions () const
bool traitquery (const trait_id &trait) const
std::set< trait_id > get_locked_traits () const
bool is_locked_trait (const trait_id &trait) const
bool is_forbidden_trait (const trait_id &trait) const
bool allowed_start (const start_location_id &loc) const
signed int point_cost () const
bool has_map_extra () const
const std::string & get_map_extra () const
std::string prof_count_str () const
Returns "All", "Limited", or "Almost all" (translated) This is used by newcharacter.cpp.
bool scen_is_blacklisted () const
bool has_flag (const std::string &flag) const
Such as a seasonal start, fiery start, surrounded start, etc.
bool can_pick (const scenario &current_scenario, int points) const
const std::vector< mission_type_id > & missions () const
Static Public Member Functions
static void load_scenario (const JsonObject &jo, const std::string &src)
static const scenario * generic ()
static const scenario * weighted_random ()
static const std::vector< scenario > & get_all ()
static void reset ()
static void check_definitions ()
calls check_definition for each scenario
Private Member Functions
void load (const JsonObject &jo, const std::string &src)
bool scenario_traits_conflict_with_profession_traits (const profession &p) const
Private Attributes
string_id< scenario > id
bool was_loaded = false
translation _name_male
translation _name_female
translation _description_male
translation _description_female
translation _start_name
bool blacklist = false
bool extra_professions = false
std::vector< profession_id > professions
std::vector< profession_id > cached_permitted_professions
permitted_professions populates this vector on the first call, which takes a bit of work.
std::set< trait_id > _allowed_traits
std::set< trait_id > _forced_traits
std::set< trait_id > _forbidden_traits
std::vector< start_location_id > _allowed_locs
int _point_cost = 0
std::set< std::string > flags
std::string _map_extra
std::vector< mission_type_id > _missions
vproto_id _starting_vehicle = vproto_id::NULL_ID()
Friends
class string_id< scenario >
class generic_factory< scenario >
Detailed Description
Definition at line 18 of file scenario.h.
Constructor & Destructor Documentation
scenario()
scenario::scenario ()
Definition at line 39 of file scenario.cpp.
    : id( "" ), _name_male( no_translation( "null" ) ),
      _name_female( no_translation( "null" ) ),
      _description_male( no_translation( "null" ) ),
      _description_female( no_translation( "null" ) )
{
}
Member Function Documentation
allowed_start()
bool scenario::allowed_start (const start_location_id & loc) const
Definition at line 444 of file scenario.cpp.
{
    auto &vec = _allowed_locs;
    return std::find( vec.begin(), vec.end(), loc ) != vec.end();
}
References _allowed_locs, and detail::find().
can_pick()
bool scenario::can_pick (const scenario & current_scenario, int points) const
Definition at line 450 of file scenario.cpp.
{
    return point_cost() - current_scenario.point_cost() <= points;
}
References point_cost().
check_definition()
void scenario::check_definition () const
Check that item definitions are valid.
Definition at line 151 of file scenario.cpp.
{
    for( auto &p : professions ) {
        if( !p.is_valid() ) {
            debugmsg( "profession %s for scenario %s does not exist", p.c_str(), id.c_str() );
        }
    }
    if( std::any_of( professions.begin(), professions.end(), [&]( const string_id<profession> &p ) {
    return std::count( professions.begin(), professions.end(), p ) > 1;
    } ) ) {
        debugmsg( "Duplicate entries in the professions array." );
    }
    for( auto &l : _allowed_locs ) {
        if( !l.is_valid() ) {
            debugmsg( "starting location %s for scenario %s does not exist", l.c_str(), id.c_str() );
        }
    }
    if( blacklist ) {
        if( professions.empty() ) {
            debugmsg( "Scenario %s: Use an empty whitelist to whitelist everything.", id.c_str() );
        } else {
            permitted_professions(); // Debug msg if every profession is blacklisted
        }
    }
    check_traits( _allowed_traits, id );
    check_traits( _forced_traits, id );
    check_traits( _forbidden_traits, id );
    MapExtras::get_function( _map_extra ); // triggers a debug message upon invalid input
    for( auto &m : _missions ) {
        if( !m.is_valid() ) {
            debugmsg( "starting mission %s for scenario %s does not exist", m.c_str(), id.c_str() );
        }
        if( std::find( m->origins.begin(), m->origins.end(), ORIGIN_GAME_START ) == m->origins.end() ) {
            debugmsg( "starting mission %s for scenario %s must include an origin of ORIGIN_GAME_START",
                      m.c_str(), id.c_str() );
        }
    }
    if( _starting_vehicle && !_starting_vehicle.is_valid() ) {
        debugmsg( "vehicle prototype %s for profession %s does not exist", _starting_vehicle.c_str(),
                  id.c_str() );
    }
}
References _allowed_locs, _allowed_traits, _forbidden_traits, _forced_traits, _map_extra, _missions, _starting_vehicle, blacklist, string_id< T >::c_str(), check_traits(), debugmsg, detail::find(), MapExtras::get_function(), string_id< T >::is_valid(), ORIGIN_GAME_START, permitted_professions(), and professions.
check_definitions()
void scenario::check_definitions () static
calls check_definition for each scenario
Definition at line 134 of file scenario.cpp.
{
    for( const auto &scen : all_scenarios.get_all() ) {
        scen.check_definition();
    }
    sc_blacklist.finalize();
}
References anonymous_namespace{scenario.cpp}::all_scenarios, scen_blacklist::finalize(), and sc_blacklist.
Referenced by DynamicDataLoader::check_consistency().
description()
std::string scenario::description (bool male) const
Definition at line 214 of file scenario.cpp.
{
    if( male ) {
        return _description_male.translated();
    } else {
        return _description_female.translated();
    }
}
References _description_female, _description_male, male, and translation::translated().
gender_appropriate_name()
std::string scenario::gender_appropriate_name (bool male) const
Definition at line 205 of file scenario.cpp.
{
    if( male ) {
        return _name_male.translated();
    } else {
        return _name_female.translated();
    }
}
References _name_female, _name_male, male, and translation::translated().
generic()
const scenario * scenario::generic () static
Definition at line 99 of file scenario.cpp.
{
    return &generic_scenario_id.obj();
}
References anonymous_namespace{scenario.cpp}::generic_scenario_id.
Referenced by avatar::create(), avatar::load(), and player::operator()().
get_all()
const std::vector< scenario > & scenario::get_all () static
Definition at line 124 of file scenario.cpp.
{
    return all_scenarios.get_all();
}
References anonymous_namespace{scenario.cpp}::all_scenarios.
Referenced by scen_blacklist::finalize(), avatar::randomize(), and set_scenario().
get_locked_traits()
std::set< trait_id > scenario::get_locked_traits () const
Definition at line 424 of file scenario.cpp.
{
    return _forced_traits;
}
References _forced_traits.
Referenced by scenario_traits_conflict_with_profession_traits().
get_map_extra()
const std::string & scenario::get_map_extra () const
Definition at line 458 of file scenario.cpp.
{
    return _map_extra;
}
References _map_extra.
Referenced by game::start_game().
has_flag()
bool scenario::has_flag (const std::string & flag) const
Such as a seasonal start, fiery start, surrounded start, etc.
Definition at line 439 of file scenario.cpp.
{
    return flags.count( flag ) != 0;
}
References flags.
Referenced by game::start_calendar(), and game::start_game().
has_map_extra()
bool scenario::has_map_extra () const
Definition at line 454 of file scenario.cpp.
{
    return _map_extra != "mx_null";
}
References _map_extra.
Referenced by game::start_game().
ident()
const string_id< scenario > & scenario::ident () const
Definition at line 200 of file scenario.cpp.
{
    return id;
}
References id.
Referenced by avatar::load().
is_forbidden_trait()
bool scenario::is_forbidden_trait (const trait_id & trait) const
Definition at line 434 of file scenario.cpp.
{
    return _forbidden_traits.count( trait ) != 0;
}
References _forbidden_traits.
Referenced by scenario_traits_conflict_with_profession_traits(), and traitquery().
is_locked_trait()
bool scenario::is_locked_trait (const trait_id & trait) const
Definition at line 429 of file scenario.cpp.
{
    return _forced_traits.count( trait ) != 0;
}
References _forced_traits.
Referenced by scenario_traits_conflict_with_profession_traits(), and traitquery().
load()
void scenario::load (const JsonObject & jo, const std::string & src) private
Definition at line 52 of file scenario.cpp.
{
    // TODO: pretty much the same as in profession::load, but different contexts for pgettext.
    // TODO: maybe combine somehow?
    if( !was_loaded || jo.has_string( "name" ) ) {
        // These may differ depending on the language settings!
        const std::string name = jo.get_string( "name" );
        _name_female = to_translation( "scenario_female", name );
        _name_male = to_translation( "scenario_male", name );
    }
    if( !was_loaded || jo.has_string( "description" ) ) {
        // These also may differ depending on the language settings!
        const std::string desc = jo.get_string( "description" );
        _description_male = to_translation( "scen_desc_male", desc );
        _description_female = to_translation( "scen_desc_female", desc );
    }
    if( !was_loaded || jo.has_string( "start_name" ) ) {
        // Specifying translation context here and above to avoid adding unnecessary json code for every scenario
        // NOLINTNEXTLINE(cata-json-translation-input)
        _start_name = to_translation( "start_name", jo.get_string( "start_name" ) );
    }
    mandatory( jo, was_loaded, "points", _point_cost );
    optional( jo, was_loaded, "blacklist_professions", blacklist );
    optional( jo, was_loaded, "add_professions", extra_professions );
    optional( jo, was_loaded, "professions", professions,
              auto_flags_reader<string_id<profession>> {} );
    optional( jo, was_loaded, "traits", _allowed_traits, auto_flags_reader<trait_id> {} );
    optional( jo, was_loaded, "forced_traits", _forced_traits, auto_flags_reader<trait_id> {} );
    optional( jo, was_loaded, "forbidden_traits", _forbidden_traits, auto_flags_reader<trait_id> {} );
    optional( jo, was_loaded, "allowed_locs", _allowed_locs, auto_flags_reader<start_location_id> {} );
    if( _allowed_locs.empty() ) {
        jo.throw_error( "at least one starting location (member \"allowed_locs\") must be defined" );
    }
    optional( jo, was_loaded, "flags", flags, auto_flags_reader<> {} );
    optional( jo, was_loaded, "map_extra", _map_extra, "mx_null" );
    optional( jo, was_loaded, "missions", _missions, auto_flags_reader<mission_type_id> {} );
    if( jo.has_string( "vehicle" ) ) {
        _starting_vehicle = vproto_id( jo.get_string( "vehicle" ) );
    }
}
References _allowed_locs, _allowed_traits, _description_female, _description_male, _forbidden_traits, _forced_traits, _map_extra, _missions, _name_female, _name_male, _point_cost, _start_name, _starting_vehicle, blacklist, extra_professions, flags, JsonObject::get_string(), JsonObject::has_string(), mandatory(), om_direction::name(), optional(), professions, JsonObject::throw_error(), to_translation(), and was_loaded.
load_scenario()
void scenario::load_scenario (const JsonObject & jo, const std::string & src) static
Definition at line 47 of file scenario.cpp.
{
    all_scenarios.load( jo, src );
}
References anonymous_namespace{scenario.cpp}::all_scenarios.
Referenced by DynamicDataLoader::initialize().
missions()
const std::vector< mission_type_id > & scenario::missions () const
Definition at line 462 of file scenario.cpp.
{
    return _missions;
}
References _missions.
Referenced by game::start_game().
permitted_professions()
std::vector< profession_id > scenario::permitted_professions () const
Definition at line 301 of file scenario.cpp.
{
    if( !cached_permitted_professions.empty() ) {
        return cached_permitted_professions;
    }
    const auto all = profession::get_all();
    std::vector<profession_id> &res = cached_permitted_professions;
    for( const profession &p : all ) {
        const bool present = std::find( professions.begin(), professions.end(),
                                        p.ident() ) != professions.end();
        bool conflicting_traits = scenario_traits_conflict_with_profession_traits( p );
        if( blacklist || professions.empty() ) {
            if( !present && !p.has_flag( "SCEN_ONLY" ) && !conflicting_traits ) {
                res.push_back( p.ident() );
            }
        } else if( present ) {
            if( !conflicting_traits ) {
                res.push_back( p.ident() );
            } else {
                debugmsg( "Scenario %s and profession %s have conflicting trait requirements",
                          id.c_str(), p.ident().c_str() );
            }
        } else if( extra_professions ) {
            if( !p.has_flag( "SCEN_ONLY" ) && !conflicting_traits ) {
                res.push_back( p.ident() );
            }
        }
    }
    if( res.empty() ) {
        debugmsg( "Scenario %s blacklists all professions.", id );
        res.push_back( profession::generic() );
    }
    return res;
}
References om_direction::all, blacklist, cached_permitted_professions, debugmsg, extra_professions, detail::find(), profession::generic(), profession::get_all(), professions, and scenario_traits_conflict_with_profession_traits().
Referenced by check_definition(), reset_scenario(), and weighted_random_profession().
point_cost()
signed int scenario::point_cost () const
Definition at line 223 of file scenario.cpp.
{
    return _point_cost;
}
References _point_cost.
Referenced by can_pick(), and weighted_random().
prof_count_str()
std::string scenario::prof_count_str () const
Returns "All", "Limited", or "Almost all" (translated) This is used by newcharacter.cpp.
Definition at line 385 of file scenario.cpp.
{
    if( professions.empty() ) {
        return _( "All" );
    }
    return blacklist ? _( "Almost all" ) : _( "Limited" );
}
References _, blacklist, and professions.
random_start_location()
start_location_id scenario::random_start_location () const
Definition at line 232 of file scenario.cpp.
{
    return random_entry( _allowed_locs );
}
References _allowed_locs, and random_entry().
Referenced by game::start_game().
reset()
void scenario::reset () static
Definition at line 129 of file scenario.cpp.
{
    all_scenarios.reset();
}
References anonymous_namespace{scenario.cpp}::all_scenarios.
Referenced by DynamicDataLoader::unload_data().
scen_is_blacklisted()
bool scenario::scen_is_blacklisted () const
Definition at line 237 of file scenario.cpp.
{
    return sc_blacklist.scenarios.count( id ) != 0;
}
References sc_blacklist, and scen_blacklist::scenarios.
scenario_traits_conflict_with_profession_traits()
bool scenario::scenario_traits_conflict_with_profession_traits (const profession & p) const private
Definition at line 340 of file scenario.cpp.
{
    for( auto &pt : p.get_forbidden_traits() ) {
        if( is_locked_trait( pt ) ) {
            return true;
        }
    }
    for( auto &pt : p.get_locked_traits() ) {
        if( is_forbidden_trait( pt ) ) {
            return true;
        }
    }
    //  check if:
    //  locked traits for scenario prevent taking locked traits for professions
    //  locked traits for professions prevent taking locked traits for scenario
    for( auto &st : get_locked_traits() ) {
        for( auto &pt : p.get_locked_traits() ) {
            if( are_conflicting_traits( st, pt ) || are_conflicting_traits( pt, st ) ) {
                return true;
            }
        }
    }
    return false;
}
References are_conflicting_traits(), profession::get_forbidden_traits(), profession::get_locked_traits(), get_locked_traits(), is_forbidden_trait(), and is_locked_trait().
Referenced by permitted_professions().
start_location()
start_location_id scenario::start_location () const
Definition at line 228 of file scenario.cpp.
{
    return _allowed_locs.front();
}
References _allowed_locs.
start_location_count()
int scenario::start_location_count () const
Definition at line 399 of file scenario.cpp.
{
    return _allowed_locs.size();
}
References _allowed_locs.
start_location_targets_count()
int scenario::start_location_targets_count () const
Definition at line 404 of file scenario.cpp.
{
    int cnt = 0;
    for( const auto &sloc : _allowed_locs ) {
        cnt += sloc.obj().targets_count();
    }
    return cnt;
}
References _allowed_locs.
start_name()
std::string scenario::start_name () const
Definition at line 393 of file scenario.cpp.
{
    return _start_name.translated();
}
References _start_name, and translation::translated().
traitquery()
bool scenario::traitquery (const trait_id & trait) const
Definition at line 418 of file scenario.cpp.
{
    return _allowed_traits.count( trait ) != 0 || is_locked_trait( trait ) ||
           ( !is_forbidden_trait( trait ) && trait->startingtrait );
}
References _allowed_traits, is_forbidden_trait(), is_locked_trait(), and mutation_branch::startingtrait.
vehicle()
vproto_id scenario::vehicle () const
Definition at line 413 of file scenario.cpp.
{
    return _starting_vehicle;
}
References _starting_vehicle.
weighted_random()
const scenario * scenario::weighted_random () static
Definition at line 107 of file scenario.cpp.
{
    if( one_in( 3 ) ) {
        return generic();
    }
    const auto &list = all_scenarios.get_all();
    while( true ) {
        const scenario &scen = random_entry_ref( list );
        if( x_in_y( 2, std::abs( scen.point_cost() ) + 2 ) ) {
            return &scen;
        }
        // else reroll in the while loop.
    }
}
References anonymous_namespace{scenario.cpp}::all_scenarios, one_in(), point_cost(), random_entry_ref(), and x_in_y().
weighted_random_profession()
const profession_id & scenario::weighted_random_profession () const
Definition at line 367 of file scenario.cpp.
{
    // Strategy: 1/3 of the time, return the generic profession (if it's permitted).
    // Otherwise, the weight of each permitted profession is 2 / ( |point cost| + 2 )
    const auto choices = permitted_professions();
    if( one_in( 3 ) && choices.front() == profession::generic()->ident() ) {
        return profession::generic();
    }
    while( true ) {
        const profession_id &candidate = random_entry_ref( choices );
        if( x_in_y( 2, 2 + std::abs( candidate->point_cost() ) ) ) {
            return candidate->ident();
        }
    }
    return profession::generic(); // Suppress warnings
}
References profession::generic(), profession::ident(), one_in(), permitted_professions(), profession::point_cost(), random_entry_ref(), and x_in_y().
Friends And Related Function Documentation
generic_factory< scenario >
friend class generic_factory< scenario > friend
Definition at line 127 of file scenario.h.
string_id< scenario >
friend class string_id< scenario > friend
Definition at line 127 of file scenario.h.
Member Data Documentation
_allowed_locs
std::vector<start_location_id> scenario::_allowed_locs private
Definition at line 44 of file scenario.h.
Referenced by allowed_start(), check_definition(), load(), random_start_location(), start_location(), start_location_count(), and start_location_targets_count().
_allowed_traits
std::set<trait_id> scenario::_allowed_traits private
Definition at line 41 of file scenario.h.
Referenced by check_definition(), load(), and traitquery().
_description_female
translation scenario::_description_female private
Definition at line 28 of file scenario.h.
Referenced by description(), and load().
_description_male
translation scenario::_description_male private
Definition at line 27 of file scenario.h.
Referenced by description(), and load().
_forbidden_traits
std::set<trait_id> scenario::_forbidden_traits private
Definition at line 43 of file scenario.h.
Referenced by check_definition(), is_forbidden_trait(), and load().
_forced_traits
std::set<trait_id> scenario::_forced_traits private
Definition at line 42 of file scenario.h.
Referenced by check_definition(), get_locked_traits(), is_locked_trait(), and load().
_map_extra
std::string scenario::_map_extra private
Definition at line 47 of file scenario.h.
Referenced by check_definition(), get_map_extra(), has_map_extra(), and load().
_missions
std::vector<mission_type_id> scenario::_missions private
Definition at line 48 of file scenario.h.
Referenced by check_definition(), load(), and missions().
_name_female
translation scenario::_name_female private
Definition at line 26 of file scenario.h.
Referenced by gender_appropriate_name(), and load().
_name_male
translation scenario::_name_male private
Definition at line 25 of file scenario.h.
Referenced by gender_appropriate_name(), and load().
_point_cost
int scenario::_point_cost = 0 private
Definition at line 45 of file scenario.h.
Referenced by load(), and point_cost().
_start_name
translation scenario::_start_name private
Definition at line 29 of file scenario.h.
Referenced by load(), and start_name().
_starting_vehicle
vproto_id scenario::_starting_vehicle = vproto_id::NULL_ID() private
Definition at line 50 of file scenario.h.
Referenced by check_definition(), load(), and vehicle().
blacklist
bool scenario::blacklist = false private
Definition at line 31 of file scenario.h.
Referenced by check_definition(), load(), permitted_professions(), and prof_count_str().
cached_permitted_professions
std::vector<profession_id> scenario::cached_permitted_professions mutable private
permitted_professions populates this vector on the first call, which takes a bit of work.
On subsequent calls, this vector is returned.
Definition at line 39 of file scenario.h.
Referenced by permitted_professions().
extra_professions
bool scenario::extra_professions = false private
Definition at line 32 of file scenario.h.
Referenced by load(), and permitted_professions().
flags
std::set<std::string> scenario::flags private
Definition at line 46 of file scenario.h.
Referenced by has_flag(), and load().
id
string_id<scenario> scenario::id private
Definition at line 23 of file scenario.h.
Referenced by ident().
professions
std::vector<profession_id> scenario::professions private
Definition at line 33 of file scenario.h.
Referenced by check_definition(), load(), permitted_professions(), and prof_count_str().
was_loaded
bool scenario::was_loaded = false private
Definition at line 24 of file scenario.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/scenario.h
src/scenario.cpp