Cataclysm BN: fungal_effects Class Reference
fungal_effects Class Reference
#include <fungal_effects.h>
Public Member Functions
fungal_effects (game &g, map &mp)
fungal_effects (const fungal_effects &)=delete
fungal_effects (fungal_effects &&)=delete
void marlossify (const tripoint &p)
void create_spores (const tripoint &p, Creature *origin=nullptr)
Makes spores at p.
void fungalize (const tripoint &p, Creature *origin=nullptr, double spore_chance=0.0)
void spread_fungus (const tripoint &p)
void spread_fungus_one_tile (const tripoint &p, int growth)
Private Attributes
game & gm
map & m
Detailed Description
Definition at line 10 of file fungal_effects.h.
Constructor & Destructor Documentation
fungal_effects() [1/3]
fungal_effects::fungal_effects (game & g, map & mp)
Definition at line 60 of file fungal_effects.cpp.
    : gm( g ), m( mp )
{
}
fungal_effects() [2/3]
fungal_effects::fungal_effects (const fungal_effects &) delete
fungal_effects() [3/3]
fungal_effects::fungal_effects (fungal_effects &&) delete
Member Function Documentation
create_spores()
void fungal_effects::create_spores (const tripoint & p, Creature * origin = nullptr)
Makes spores at p.
source is used for kill counting
Definition at line 115 of file fungal_effects.cpp.
{
    for( const tripoint &tmp : get_map().points_in_radius( p, 1 ) ) {
        fungalize( tmp, origin, 0.25 );
    }
}
References fungalize(), get_map(), and points_in_radius().
Referenced by map::bash_furn_success(), map::bash_ter_success(), and iexamine::fungus().
fungalize()
void fungal_effects::fungalize (const tripoint & p, Creature * origin = nullptr, double spore_chance = 0.0)
Dexterity increases chance of knocking fungal spores away with your TAIL_CATTLE \EFFECT_MELEE increases chance of knocking fungal sports away with your TAIL_CATTLE
Definition at line 65 of file fungal_effects.cpp.
{
    if( monster *const mon_ptr = g->critter_at<monster>( p ) ) {
        monster &critter = *mon_ptr;
        if( gm.u.sees( p ) &&
            !critter.type->in_species( FUNGUS ) ) {
            add_msg( _( "The %s is covered in tiny spores!" ), critter.name() );
        }
        if( !critter.make_fungus() ) {
            // Don't insta-kill non-fungables. Jabberwocks, for example
            critter.add_effect( effect_stunned, rng( 1_turns, 3_turns ) );
            critter.apply_damage( origin, bodypart_id( "torso" ), rng( 25, 50 ) );
        }
    } else if( gm.u.pos() == p && gm.u.get_effect_int( effect_fungus ) < 3 ) {
        // TODO: Make this accept NPCs when they understand fungals
        player &pl = gm.u;
        ///\EFFECT_DEX increases chance of knocking fungal spores away with your TAIL_CATTLE
        ///\EFFECT_MELEE increases chance of knocking fungal sports away with your TAIL_CATTLE
        if( pl.has_trait( trait_TAIL_CATTLE ) &&
            one_in( 20 - pl.dex_cur - pl.get_skill_level( skill_melee ) ) ) {
            pl.add_msg_if_player(
                _( "The spores land on you, but you quickly swat them off with your tail!" ) );
            return;
        }
        // Spores hit the player--is there any hope?
        bool hit = false;
        hit |= one_in( 4 ) && pl.add_env_effect( effect_spores, bp_head, 3, 9_minutes, bp_head );
        hit |= one_in( 2 ) && pl.add_env_effect( effect_spores, bp_torso, 3, 9_minutes, bp_torso );
        hit |= one_in( 4 ) && pl.add_env_effect( effect_spores, bp_arm_l, 3, 9_minutes, bp_arm_l );
        hit |= one_in( 4 ) && pl.add_env_effect( effect_spores, bp_arm_r, 3, 9_minutes, bp_arm_r );
        hit |= one_in( 4 ) && pl.add_env_effect( effect_spores, bp_leg_l, 3, 9_minutes, bp_leg_l );
        hit |= one_in( 4 ) && pl.add_env_effect( effect_spores, bp_leg_r, 3, 9_minutes, bp_leg_r );
        if( hit ) {
            add_msg( m_warning, _( "You're covered in tiny spores!" ) );
        }
    } else if( gm.num_creatures() < 250 && x_in_y( spore_chance, 1.0 ) ) { // Spawn a spore
        if( monster *const spore = gm.place_critter_at( mon_spore, p ) ) {
            monster *origin_mon = dynamic_cast<monster *>( origin );
            if( origin_mon != nullptr ) {
                spore->make_ally( *origin_mon );
            } else if( origin != nullptr && origin->is_player() &&
                       gm.u.has_trait( trait_THRESH_MYCUS ) ) {
                spore->friendly = 1000;
            }
        }
    } else {
        spread_fungus( p );
    }
}
References _, monster::add_effect(), Creature::add_env_effect(), add_msg(), player::add_msg_if_player(), monster::apply_damage(), bp_arm_l, bp_arm_r, bp_head, bp_leg_l, bp_leg_r, bp_torso, Character::dex_cur, effect_fungus, effect_spores, effect_stunned, FUNGUS, g, Creature::get_effect_int(), Character::get_skill_level(), gm, Character::has_trait(), mtype::in_species(), m_warning, monster::make_ally(), monster::make_fungus(), mon_spore, monster::name(), game::num_creatures(), one_in(), game::place_critter_at(), Character::pos(), rng(), Character::sees(), skill_melee, spread_fungus(), trait_TAIL_CATTLE, trait_THRESH_MYCUS, monster::type, game::u, and x_in_y().
Referenced by create_spores(), mdeath::fungus(), mattack::fungus(), mattack::plant(), Character::spores(), and Character::vomit().
marlossify()
void fungal_effects::marlossify (const tripoint & p)
Definition at line 122 of file fungal_effects.cpp.
{
    auto &terrain = m.ter( p ).obj();
    if( one_in( 25 ) && ( terrain.movecost != 0 && !m.has_furn( p ) )
        && !terrain.has_flag( TFLAG_DEEP_WATER ) ) {
        m.ter_set( p, t_marloss );
        return;
    }
    for( int i = 0; i < 25; i++ ) {
        bool is_fungi = m.has_flag_ter( flag_FUNGUS, p );
        spread_fungus( p );
        if( is_fungi ) {
            return;
        }
    }
}
References flag_FUNGUS(), map::has_flag_ter(), map::has_furn(), m, int_id< T >::obj(), one_in(), spread_fungus(), t_marloss, map::ter(), map::ter_set(), terrain, and TFLAG_DEEP_WATER.
Referenced by MapExtras::mx_portal_in(), iuse::mycus(), and spawn_spores().
spread_fungus()
void fungal_effects::spread_fungus (const tripoint & p)
Definition at line 242 of file fungal_effects.cpp.
{
    int growth = 1;
    map &here = get_map();
    for( const tripoint &tmp : here.points_in_radius( p, 1 ) ) {
        if( tmp == p ) {
            continue;
        }
        if( m.has_flag( flag_FUNGUS, tmp ) ) {
            growth += 1;
        }
    }
    if( !m.has_flag_ter( flag_FUNGUS, p ) ) {
        spread_fungus_one_tile( p, growth );
    } else {
        // Everything is already fungus
        if( growth == 9 ) {
            return;
        }
        for( const tripoint &dest : here.points_in_radius( p, 1 ) ) {
            // One spread on average
            if( !m.has_flag( flag_FUNGUS, dest ) && one_in( 9 - growth ) ) {
                //growth chance is 100 in X simplified
                spread_fungus_one_tile( dest, 10 );
            }
        }
    }
}
References flag_FUNGUS(), get_map(), map::has_flag(), map::has_flag_ter(), m, one_in(), map::points_in_radius(), and spread_fungus_one_tile().
Referenced by mattack::fungal_trail(), fungalize(), marlossify(), mattack::plant(), and map::process_fields_in_submap().
spread_fungus_one_tile()
void fungal_effects::spread_fungus_one_tile (const tripoint & p, int growth)
Definition at line 139 of file fungal_effects.cpp.
{
    bool converted = false;
    // Terrain conversion
    if( m.has_flag_ter( flag_DIGGABLE, p ) ) {
        if( x_in_y( growth * 10, 100 ) ) {
            m.ter_set( p, t_fungus );
            converted = true;
        }
    } else if( m.has_flag( flag_FLAT, p ) ) {
        if( m.has_flag( TFLAG_INDOORS, p ) ) {
            if( x_in_y( growth * 10, 500 ) ) {
                m.ter_set( p, t_fungus_floor_in );
                converted = true;
            }
        } else if( m.has_flag( TFLAG_SUPPORTS_ROOF, p ) ) {
            if( x_in_y( growth * 10, 1000 ) ) {
                m.ter_set( p, t_fungus_floor_sup );
                converted = true;
            }
        } else {
            if( x_in_y( growth * 10, 2500 ) ) {
                m.ter_set( p, t_fungus_floor_out );
                converted = true;
            }
        }
    } else if( m.has_flag( flag_SHRUB, p ) ) {
        if( x_in_y( growth * 10, 200 ) ) {
            m.ter_set( p, t_shrub_fungal );
            converted = true;
        } else if( x_in_y( growth, 1000 ) ) {
            m.ter_set( p, t_marloss );
            converted = true;
        }
    } else if( m.has_flag( flag_THIN_OBSTACLE, p ) ) {
        if( x_in_y( growth * 10, 150 ) ) {
            m.ter_set( p, t_fungus_mound );
            converted = true;
        }
    } else if( m.has_flag( flag_YOUNG, p ) ) {
        if( x_in_y( growth * 10, 500 ) ) {
            if( m.get_field_intensity( p, fd_fungal_haze ) != 0 ) {
                if( x_in_y( growth * 10, 800 ) ) { // young trees are vulnerable
                    m.ter_set( p, t_fungus );
                    if( gm.place_critter_at( mon_fungal_blossom, p ) && gm.u.sees( p ) ) {
                        add_msg( m_warning, _( "The young tree blooms forth into a fungal blossom!" ) );
                    }
                } else if( x_in_y( growth * 10, 400 ) ) {
                    m.ter_set( p, t_marloss_tree );
                }
            } else {
                m.ter_set( p, t_tree_fungal_young );
            }
            converted = true;
        }
    } else if( m.has_flag( flag_TREE, p ) ) {
        if( one_in( 10 ) ) {
            if( m.get_field_intensity( p, fd_fungal_haze ) != 0 ) {
                if( x_in_y( growth * 10, 100 ) ) {
                    m.ter_set( p, t_fungus );
                    if( gm.place_critter_at( mon_fungal_blossom, p ) && gm.u.sees( p ) ) {
                        add_msg( m_warning, _( "The tree blooms forth into a fungal blossom!" ) );
                    }
                } else if( x_in_y( growth * 10, 600 ) ) {
                    m.ter_set( p, t_marloss_tree );
                }
            } else {
                m.ter_set( p, t_tree_fungal );
            }
            converted = true;
        }
    } else if( m.has_flag( flag_WALL, p ) && m.has_flag( flag_FLAMMABLE, p ) ) {
        if( x_in_y( growth * 10, 5000 ) ) {
            m.ter_set( p, t_fungus_wall );
            converted = true;
        }
    }
    // Furniture conversion
    if( converted ) {
        if( m.has_flag( flag_FLOWER, p ) ) {
            m.furn_set( p, f_flower_fungal );
        } else if( m.has_flag( flag_ORGANIC, p ) ) {
            if( m.furn( p ).obj().movecost == -10 ) {
                m.furn_set( p, f_fungal_mass );
            } else {
                m.furn_set( p, f_fungal_clump );
            }
        } else if( m.has_flag( flag_PLANT, p ) ) {
            // Replace the (already existing) seed
            // Can't use item_stack::only_item() since there might be fertilizer
            map_stack items = m.i_at( p );
            const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
                return it.is_seed();
            } );
            if( seed == items.end() || !seed->is_seed() ) {
                dbg( DL::Warn ) << "No seed item in the PLANT terrain at position " << p;
            } else {
                *seed = item( "fungal_seeds", calendar::turn );
            }
        }
    }
}
References _, add_msg(), item_stack::begin(), dbg, item_stack::end(), f_flower_fungal, f_fungal_clump, f_fungal_mass, fd_fungal_haze, flag_DIGGABLE(), flag_FLAMMABLE(), flag_FLAT(), flag_FLOWER(), flag_ORGANIC(), flag_PLANT(), flag_SHRUB(), flag_THIN_OBSTACLE(), flag_TREE(), flag_WALL(), flag_YOUNG(), map::furn(), map::furn_set(), map::get_field_intensity(), gm, map::has_flag(), map::has_flag_ter(), map::i_at(), m, m_warning, mon_fungal_blossom, map_data_common_t::movecost, int_id< T >::obj(), one_in(), game::place_critter_at(), iuse::seed(), Character::sees(), t_fungus, t_fungus_floor_in, t_fungus_floor_out, t_fungus_floor_sup, t_fungus_mound, t_fungus_wall, t_marloss, t_marloss_tree, t_shrub_fungal, t_tree_fungal, t_tree_fungal_young, map::ter_set(), TFLAG_INDOORS, TFLAG_SUPPORTS_ROOF, calendar::turn, game::u, Warn, and x_in_y().
Referenced by spread_fungus().
Member Data Documentation
gm
game& fungal_effects::gm private
Definition at line 14 of file fungal_effects.h.
Referenced by fungalize(), and spread_fungus_one_tile().
m
map& fungal_effects::m private
Definition at line 15 of file fungal_effects.h.
Referenced by marlossify(), spread_fungus(), and spread_fungus_one_tile().
The documentation for this class was generated from the following files:
src/fungal_effects.h
src/fungal_effects.cpp