Cataclysm BN: vehicle_stack Class Reference
vehicle_stack Class Reference
#include <vehicle.h>
Public Member Functions
vehicle_stack (cata::colony< item > *newstack, point newloc, vehicle *neworigin, int part)
iterator erase (const_iterator it) override
void insert (const item &newitem) override
int count_limit () const override
Maximum number of items allowed here.
units::volume max_volume () const override
Maximum volume allowed here.
Public Member Functions inherited from item_stack
item_stack (cata::colony< item > *items)
virtual ~item_stack ()=default
size_t size () const
bool empty () const
virtual void clear ()
item & only_item ()
iterator get_iterator_from_pointer (item *it)
iterator get_iterator_from_index (size_t idx)
size_t get_index_from_iterator (const const_iterator &it)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
units::volume stored_volume () const
Total volume of the items here.
units::volume free_volume () const
int amount_can_fit (const item &it) const
Returns how many of the specified item (or how many charges if it's counted by charges) could be added without violating either the volume or itemcount limits.
item * stacks_with (const item &it)
Return the item (or nullptr) that stacks with the argument.
const item * stacks_with (const item &it) const
Private Attributes
point location
vehicle * myorigin
int part_num
Additional Inherited Members
Public Types inherited from item_stack
using iterator = cata::colony< item >::iterator
using const_iterator = cata::colony< item >::const_iterator
using reverse_iterator = cata::colony< item >::reverse_iterator
using const_reverse_iterator = cata::colony< item >::const_reverse_iterator
Protected Attributes inherited from item_stack
cata::colony< item > * items
Detailed Description
Definition at line 123 of file vehicle.h.
Constructor & Destructor Documentation
vehicle_stack()
vehicle_stack::vehicle_stack (cata::colony< item > * newstack, point newloc, vehicle * neworigin, int part) inline
Definition at line 130 of file vehicle.h.
                                                                                                :
            item_stack( newstack ), location( newloc ), myorigin( neworigin ), part_num( part ) {}
Member Function Documentation
count_limit()
int vehicle_stack::count_limit () const inline override virtual
Maximum number of items allowed here.
Implements item_stack.
Definition at line 134 of file vehicle.h.
{
            return MAX_ITEM_IN_VEHICLE_STORAGE;
        }
References MAX_ITEM_IN_VEHICLE_STORAGE.
erase()
vehicle_stack::iterator vehicle_stack::erase (vehicle_stack::const_iterator it) override virtual
Implements item_stack.
Definition at line 231 of file vehicle.cpp.
{
    return myorigin->remove_item( part_num, it );
}
References myorigin, part_num, and vehicle::remove_item().
Referenced by vehicle::fold_up(), map::mop_spills(), MapExtras::mx_helicopter(), vehicle::operate_planter(), game::start_game(), and basecamp::start_garage_chop().
insert()
void vehicle_stack::insert (const item & newitem) override virtual
Implements item_stack.
Definition at line 236 of file vehicle.cpp.
{
    myorigin->add_item( part_num, newitem );
}
References vehicle::add_item(), myorigin, and part_num.
Referenced by veh_interact::complete_vehicle().
max_volume()
units::volume vehicle_stack::max_volume () const override virtual
Maximum volume allowed here.
Implements item_stack.
Definition at line 241 of file vehicle.cpp.
{
    if( myorigin->part_flag( part_num, "CARGO" ) && !myorigin->part( part_num ).is_broken() ) {
        // Set max volume for vehicle cargo to prevent integer overflow
        return std::min( myorigin->part( part_num ).info().size, 10000_liter );
    }
    return 0_ml;
}
References vehicle_part::info(), vehicle_part::is_broken(), myorigin, vehicle::part(), vehicle::part_flag(), part_num, and vpart_info::size.
Referenced by vehicle::max_volume().
Member Data Documentation
location
point vehicle_stack::location private
Definition at line 126 of file vehicle.h.
myorigin
vehicle* vehicle_stack::myorigin private
Definition at line 127 of file vehicle.h.
Referenced by erase(), insert(), and max_volume().
part_num
int vehicle_stack::part_num private
Definition at line 128 of file vehicle.h.
Referenced by erase(), insert(), and max_volume().
The documentation for this class was generated from the following files:
src/vehicle.h
src/vehicle.cpp