Cataclysm BN: jmapgen_translate Class Reference
jmapgen_translate Class Reference
Translate terrain from one ter_id to another.
Public Member Functions
jmapgen_translate (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &, const jmapgen_int &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
ter_id from
ter_id to
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Translate terrain from one ter_id to another.
"from": id of the starting terrain. "to": id of the ending terrain not useful for normal mapgen, very useful for mapgen_update
Definition at line 1716 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_translate()
jmapgen_translate::jmapgen_translate (const JsonObject & jsi) inline
Definition at line 1721 of file mapgen.cpp.
{
            if( jsi.has_string( "from" ) && jsi.has_string( "to" ) ) {
                const std::string from_id = jsi.get_string( "from" );
                const std::string to_id = jsi.get_string( "to" );
                from = ter_id( from_id );
                to = ter_id( to_id );
            }
        }
References from, JsonObject::get_string(), JsonObject::has_string(), mapgen_defer::jsi, ter_id, and to.
Member Function Documentation
apply()
void jmapgen_translate::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1729 of file mapgen.cpp.
{
            dat.m.translate( from, to );
        }
References from, mapgendata::m, to, and map::translate().
Member Data Documentation
from
ter_id jmapgen_translate::from
Definition at line 1719 of file mapgen.cpp.
Referenced by apply(), and jmapgen_translate().
to
ter_id jmapgen_translate::to
Definition at line 1720 of file mapgen.cpp.
Referenced by apply(), and jmapgen_translate().
The documentation for this class was generated from the following file:
src/mapgen.cpp