Cataclysm BN: basic_format_parse_context< Char, ErrorHandler > Class Template Reference
basic_format_parse_context< Char, ErrorHandler > Class Template Reference
\rst Parsing context consisting of a format string range being parsed and an argument counter for automatic indexing.
#include <fmtlib_core.h>
Public Types
using char_type = Char
using iterator = typename basic_string_view< Char >::iterator
Public Member Functions
constexpr basic_format_parse_context (basic_string_view< Char > format_str, ErrorHandler eh={}, int next_arg_id=0)
constexpr iterator begin () const FMT_NOEXCEPT
Returns an iterator to the beginning of the format string range being parsed.
constexpr iterator end () const FMT_NOEXCEPT
Returns an iterator past the end of the format string range being parsed.
FMT_CONSTEXPR void advance_to (iterator it)
Advances the begin iterator to it.
FMT_CONSTEXPR int next_arg_id ()
Reports an error if using the manual argument indexing; otherwise returns the next argument index and switches to the automatic indexing.
FMT_CONSTEXPR void check_arg_id (int)
Reports an error if using the automatic argument indexing; otherwise switches to the manual indexing.
FMT_CONSTEXPR void check_arg_id (basic_string_view< Char >)
FMT_CONSTEXPR void on_error (const char *message)
constexpr ErrorHandler error_handler () const
Private Attributes
basic_string_view< Char > format_str_
int next_arg_id_
Additional Inherited Members
Private Member Functions inherited from detail::error_handler
constexpr error_handler ()=default
constexpr error_handler (const error_handler &)=default
FMT_NORETURN FMT_API void on_error (const char *message)
Detailed Description
template<typename Char, typename ErrorHandler = detail::error_handler>
class basic_format_parse_context< Char, ErrorHandler >
\rst Parsing context consisting of a format string range being parsed and an argument counter for automatic indexing.
You can use one of the following type aliases for common character types:
+--------------------—+----------------------------------—+ | Type | Definition | +=======================+=====================================+ | format_parse_context | basic_format_parse_context<char> | +--------------------—+----------------------------------—+ | wformat_parse_context | basic_format_parse_context<wchar_t> | +--------------------—+----------------------------------—+ \endrst
Definition at line 591 of file fmtlib_core.h.
Member Typedef Documentation
char_type
template<typename Char , typename ErrorHandler = detail::error_handler> using basic_format_parse_context< Char, ErrorHandler >::char_type = Char
Definition at line 598 of file fmtlib_core.h.
iterator
template<typename Char , typename ErrorHandler = detail::error_handler> using basic_format_parse_context< Char, ErrorHandler >::iterator = typename basic_string_view<Char>::iterator
Definition at line 599 of file fmtlib_core.h.
Constructor & Destructor Documentation
basic_format_parse_context()
template<typename Char , typename ErrorHandler = detail::error_handler> constexpr basic_format_parse_context< Char, ErrorHandler >::basic_format_parse_context (basic_string_view< Char > format_str, ErrorHandler eh = {}, int next_arg_id = 0) inline explicit constexpr
Definition at line 601 of file fmtlib_core.h.
                                                                  {},
            int next_arg_id = 0 )
            : ErrorHandler( eh ), format_str_( format_str ), next_arg_id_( next_arg_id ) {}
Member Function Documentation
advance_to()
template<typename Char , typename ErrorHandler = detail::error_handler> FMT_CONSTEXPR void basic_format_parse_context< Char, ErrorHandler >::advance_to (iterator it) inline
Advances the begin iterator to it.
Definition at line 622 of file fmtlib_core.h.
{
            format_str_.remove_prefix( detail::to_unsigned( it - begin() ) );
        }
References basic_format_parse_context< Char, ErrorHandler >::begin(), basic_format_parse_context< Char, ErrorHandler >::format_str_, and detail::to_unsigned().
Referenced by advance_to().
begin()
template<typename Char , typename ErrorHandler = detail::error_handler> constexpr iterator basic_format_parse_context< Char, ErrorHandler >::begin () const inline constexpr
Returns an iterator to the beginning of the format string range being parsed.
Definition at line 610 of file fmtlib_core.h.
{
            return format_str_.begin();
        }
References basic_format_parse_context< Char, ErrorHandler >::format_str_.
Referenced by advance_to(), basic_format_parse_context< Char, ErrorHandler >::advance_to(), detail::format_handler< OutputIt, Char, Context >::on_format_specs(), and formatter< detail::bigint >::parse().
check_arg_id() [1/2]
template<typename Char , typename ErrorHandler = detail::error_handler> FMT_CONSTEXPR void basic_format_parse_context< Char, ErrorHandler >::check_arg_id (basic_string_view< Char >) inline
Definition at line 652 of file fmtlib_core.h.
{}
check_arg_id() [2/2]
template<typename Char , typename ErrorHandler = detail::error_handler> FMT_CONSTEXPR void basic_format_parse_context< Char, ErrorHandler >::check_arg_id (int) inline
Reports an error if using the automatic argument indexing; otherwise switches to the manual indexing.
Definition at line 644 of file fmtlib_core.h.
{
            if( next_arg_id_ > 0 ) {
                on_error( "cannot switch from automatic to manual argument indexing" );
            } else {
                next_arg_id_ = -1;
            }
        }
References basic_format_parse_context< Char, ErrorHandler >::next_arg_id_, and basic_format_parse_context< Char, ErrorHandler >::on_error().
Referenced by detail::format_handler< OutputIt, Char, Context >::on_arg_id().
end()
template<typename Char , typename ErrorHandler = detail::error_handler> constexpr iterator basic_format_parse_context< Char, ErrorHandler >::end () const inline constexpr
Returns an iterator past the end of the format string range being parsed.
Definition at line 617 of file fmtlib_core.h.
{
            return format_str_.end();
        }
References basic_format_parse_context< Char, ErrorHandler >::format_str_.
error_handler()
template<typename Char , typename ErrorHandler = detail::error_handler> constexpr ErrorHandler basic_format_parse_context< Char, ErrorHandler >::error_handler () const inline constexpr
Definition at line 658 of file fmtlib_core.h.
{
            return *this;
        }
next_arg_id()
template<typename Char , typename ErrorHandler = detail::error_handler> FMT_CONSTEXPR int basic_format_parse_context< Char, ErrorHandler >::next_arg_id () inline
Reports an error if using the manual argument indexing; otherwise returns the next argument index and switches to the automatic indexing.
Definition at line 630 of file fmtlib_core.h.
{
            // Don't check if the argument id is valid to avoid overhead and because it
            // will be checked during formatting anyway.
            if( next_arg_id_ >= 0 ) {
                return next_arg_id_++;
            }
            on_error( "cannot switch from manual to automatic argument indexing" );
            return 0;
        }
References basic_format_parse_context< Char, ErrorHandler >::next_arg_id_, and basic_format_parse_context< Char, ErrorHandler >::on_error().
Referenced by detail::format_handler< OutputIt, Char, Context >::on_arg_id().
on_error()
template<typename Char , typename ErrorHandler = detail::error_handler> FMT_CONSTEXPR void basic_format_parse_context< Char, ErrorHandler >::on_error (const char * message) inline
Definition at line 654 of file fmtlib_core.h.
{
            ErrorHandler::on_error( message );
        }
References mapgen_defer::message.
Referenced by basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), basic_format_parse_context< Char, ErrorHandler >::next_arg_id(), and basic_printf_context< OutputIt, Char >::on_error().
Member Data Documentation
format_str_
template<typename Char , typename ErrorHandler = detail::error_handler> basic_string_view<Char> basic_format_parse_context< Char, ErrorHandler >::format_str_ private
Definition at line 594 of file fmtlib_core.h.
Referenced by basic_format_parse_context< Char, ErrorHandler >::advance_to(), basic_format_parse_context< Char, ErrorHandler >::begin(), and basic_format_parse_context< Char, ErrorHandler >::end().
next_arg_id_
template<typename Char , typename ErrorHandler = detail::error_handler> int basic_format_parse_context< Char, ErrorHandler >::next_arg_id_ private
Definition at line 595 of file fmtlib_core.h.
Referenced by basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), and basic_format_parse_context< Char, ErrorHandler >::next_arg_id().
The documentation for this class was generated from the following file:
src/fmtlib_core.h