Cataclysm BN: detail::specs_handler< ParseContext, Context > Class Template Reference
detail::specs_handler< ParseContext, Context > Class Template Reference
#include <fmtlib_format.h>
Public Types
using char_type = typename Context::char_type
Public Member Functions
FMT_CONSTEXPR specs_handler (basic_format_specs< char_type > &specs, ParseContext &parse_ctx, Context &ctx)
template<typename Id >
FMT_CONSTEXPR void on_dynamic_width (Id arg_id)
template<typename Id >
FMT_CONSTEXPR void on_dynamic_precision (Id arg_id)
void on_error (const char *message)
Public Member Functions inherited from detail::specs_setter< Context::char_type >
FMT_CONSTEXPR specs_setter (basic_format_specs< Context::char_type > &specs)
FMT_CONSTEXPR specs_setter (const specs_setter &other)
FMT_CONSTEXPR void on_align (align_t align)
FMT_CONSTEXPR void on_fill (basic_string_view< Context::char_type > fill)
FMT_CONSTEXPR void on_plus ()
FMT_CONSTEXPR void on_minus ()
FMT_CONSTEXPR void on_space ()
FMT_CONSTEXPR void on_hash ()
FMT_CONSTEXPR void on_zero ()
FMT_CONSTEXPR void on_width (int width)
FMT_CONSTEXPR void on_precision (int precision)
FMT_CONSTEXPR void end_precision ()
FMT_CONSTEXPR void on_type (Context::char_type type)
Private Types
using format_arg = typename Context::format_arg
Private Member Functions
FMT_CONSTEXPR format_arg get_arg (auto_id)
FMT_CONSTEXPR format_arg get_arg (int arg_id)
FMT_CONSTEXPR format_arg get_arg (basic_string_view< char_type > arg_id)
Private Attributes
ParseContext & parse_context_
Context & context_
Additional Inherited Members
Protected Attributes inherited from detail::specs_setter< Context::char_type >
basic_format_specs< Context::char_type > & specs_
Detailed Description
template<typename ParseContext, typename Context>
class detail::specs_handler< ParseContext, Context >
Definition at line 2946 of file fmtlib_format.h.
Member Typedef Documentation
char_type
template<typename ParseContext , typename Context > using detail::specs_handler< ParseContext, Context >::char_type = typename Context::char_type
Definition at line 2949 of file fmtlib_format.h.
format_arg
template<typename ParseContext , typename Context > using detail::specs_handler< ParseContext, Context >::format_arg = typename Context::format_arg private
Definition at line 2973 of file fmtlib_format.h.
Constructor & Destructor Documentation
specs_handler()
template<typename ParseContext , typename Context > FMT_CONSTEXPR detail::specs_handler< ParseContext, Context >::specs_handler (basic_format_specs< char_type > & specs, ParseContext & parse_ctx, Context & ctx) inline
Definition at line 2951 of file fmtlib_format.h.
            : specs_setter<char_type>( specs ),
              parse_context_( parse_ctx ),
              context_( ctx ) {}
Member Function Documentation
get_arg() [1/3]
template<typename ParseContext , typename Context > FMT_CONSTEXPR format_arg detail::specs_handler< ParseContext, Context >::get_arg (auto_id) inline private
Definition at line 2975 of file fmtlib_format.h.
{
            return detail::get_arg( context_, parse_context_.next_arg_id() );
        }
References detail::get_arg().
get_arg() [2/3]
template<typename ParseContext , typename Context > FMT_CONSTEXPR format_arg detail::specs_handler< ParseContext, Context >::get_arg (basic_string_view< char_type > arg_id) inline private
Definition at line 2984 of file fmtlib_format.h.
{
            parse_context_.check_arg_id( arg_id );
            return detail::get_arg( context_, arg_id );
        }
References detail::get_arg().
get_arg() [3/3]
template<typename ParseContext , typename Context > FMT_CONSTEXPR format_arg detail::specs_handler< ParseContext, Context >::get_arg (int arg_id) inline private
Definition at line 2979 of file fmtlib_format.h.
{
            parse_context_.check_arg_id( arg_id );
            return detail::get_arg( context_, arg_id );
        }
References detail::get_arg().
on_dynamic_precision()
template<typename ParseContext , typename Context > template<typename Id > FMT_CONSTEXPR void detail::specs_handler< ParseContext, Context >::on_dynamic_precision (Id arg_id) inline
Definition at line 2962 of file fmtlib_format.h.
{
            this->specs_.precision = get_dynamic_spec<precision_checker>(
                                         get_arg( arg_id ), context_.error_handler() );
        }
References detail::get_arg(), and basic_format_specs< Char >::precision.
on_dynamic_width()
template<typename ParseContext , typename Context > template<typename Id > FMT_CONSTEXPR void detail::specs_handler< ParseContext, Context >::on_dynamic_width (Id arg_id) inline
Definition at line 2957 of file fmtlib_format.h.
{
            this->specs_.width = get_dynamic_spec<width_checker>(
                                     get_arg( arg_id ), context_.error_handler() );
        }
References detail::get_arg(), and basic_format_specs< Char >::width.
on_error()
template<typename ParseContext , typename Context > void detail::specs_handler< ParseContext, Context >::on_error (const char * message) inline
Definition at line 2967 of file fmtlib_format.h.
{
            context_.on_error( message );
        }
References mapgen_defer::message.
Member Data Documentation
context_
template<typename ParseContext , typename Context > Context& detail::specs_handler< ParseContext, Context >::context_ private
Definition at line 2990 of file fmtlib_format.h.
parse_context_
template<typename ParseContext , typename Context > ParseContext& detail::specs_handler< ParseContext, Context >::parse_context_ private
Definition at line 2989 of file fmtlib_format.h.
The documentation for this class was generated from the following file:
src/fmtlib_format.h