Cataclysm BN: drop_activity_actor Class Reference
drop_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
drop_activity_actor ()=default
drop_activity_actor (Character &ch, const drop_locations &items, bool force_ground, const tripoint &relpos)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Attributes
std::list< pickup::act_item > items
bool force_ground = false
tripoint relpos
Detailed Description
Definition at line 270 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
drop_activity_actor() [1/2]
drop_activity_actor::drop_activity_actor () default
drop_activity_actor() [2/2]
drop_activity_actor::drop_activity_actor (Character & ch, const drop_locations & items, bool force_ground, const tripoint & relpos)
Definition at line 698 of file activity_actor.cpp.
    : force_ground( force_ground ), relpos( relpos )
{
    this->items = pickup::reorder_for_dropping( ch, items );
}
References items, and pickup::reorder_for_dropping().
Member Function Documentation
clone()
std::unique_ptr< activity_actor > drop_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 290 of file activity_actor_definitions.h.
{
            return std::make_unique<drop_activity_actor>( *this );
        }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > drop_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 723 of file activity_actor.cpp.
{
    drop_activity_actor actor;
    JsonObject data = jsin.get_object();
    data.read( "items", actor.items );
    data.read( "force_ground", actor.force_ground );
    data.read( "relpos", actor.relpos );
    return actor.clone();
}
References clone(), force_ground, JsonIn::get_object(), items, JsonObject::read(), and relpos.
do_turn()
void drop_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 685 of file activity_item_handling.cpp.
{
    const tripoint pos = who.pos() + relpos;
    put_into_vehicle_or_drop( who, item_drop_reason::deliberate,
                              obtain_activity_items( who, items ),
                              pos, force_ground );
    if( items.empty() ) {
        who.cancel_activity();
    }
}
References Character::cancel_activity(), deliberate, force_ground, items, obtain_activity_items(), Character::pos(), put_into_vehicle_or_drop(), and relpos.
finish()
void drop_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 288 of file activity_actor_definitions.h.
{};
get_type()
activity_id drop_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 282 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_DROP" );
        }
serialize()
void drop_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 712 of file activity_actor.cpp.
{
    jsout.start_object();
    jsout.member( "items", items );
    jsout.member( "force_ground", force_ground );
    jsout.member( "relpos", relpos );
    jsout.end_object();
}
References JsonOut::end_object(), force_ground, items, JsonOut::member(), relpos, and JsonOut::start_object().
start()
void drop_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 705 of file activity_actor.cpp.
{
    // Set moves_left to value other than zero to indicate ongoing activity
    act.moves_total = 1;
    act.moves_left = 1;
}
References act.
Member Data Documentation
force_ground
bool drop_activity_actor::force_ground = false private
Definition at line 274 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
items
std::list<pickup::act_item> drop_activity_actor::items private
Definition at line 273 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), drop_activity_actor(), and serialize().
relpos
tripoint drop_activity_actor::relpos private
Definition at line 275 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp
src/activity_item_handling.cpp