Cataclysm BN: mutagen_actor Class Reference
mutagen_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
mutagen_actor ()
~mutagen_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::string mutation_category
bool is_weak = false
bool is_strong = false
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1181 of file iuse_actor.h.
Constructor & Destructor Documentation
mutagen_actor()
mutagen_actor::mutagen_actor () inline
Definition at line 1188 of file iuse_actor.h.
: iuse_actor("mutagen") {}
~mutagen_actor()
mutagen_actor::~mutagen_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > mutagen_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4517 of file iuse_actor.cpp.
{
    return std::make_unique<mutagen_actor>( *this );
}
load()
void mutagen_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 4522 of file iuse_actor.cpp.
{
    mutation_category = obj.get_string( "mutation_category", "ANY" );
    is_weak = obj.get_bool( "is_weak", false );
    is_strong = obj.get_bool( "is_strong", false );
}
References JsonObject::get_bool(), and JsonObject::get_string().
use()
int mutagen_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 4529 of file iuse_actor.cpp.
{
    mutagen_attempt checks =
        mutagen_common_checks( p, it, false, mutagen_technique::consumed_mutagen );
    if( !checks.allowed ) {
        return checks.charges_used;
    }
    bool no_category = mutation_category == "ANY";
    bool balanced = get_option<bool>( "BALANCED_MUTATIONS" );
    int accumulated_mutagen = p.get_effect_int( effect_accumulated_mutagen );
    if( balanced && !is_strong && is_weak && accumulated_mutagen < 2 && no_category && !p.query_yn(
            _( "Looking at it just makes you tired.  It probably won't work.  Do you want to try anyway?" )
        ) ) {
        return 0;
    }
    if( is_weak && !one_in( 3 ) && !balanced ) {
        // Nothing! Mutagenic flesh often just fails to work.
        return it.type->charges_to_use();
    }
    if( balanced && no_category ) {
        for( int i = ( is_strong ? 1 : 0 ) + ( is_weak ? 0 : 1 ); i > 0; i-- ) {
            p.add_effect( effect_accumulated_mutagen, 2_days, num_bp );
        }
    }
    const mutation_category_trait &m_category = mutation_category_trait::get_category(
                mutation_category );
    if( p.has_trait( trait_MUT_JUNKIE ) ) {
        p.add_msg_if_player( m_good, _( "You quiver with anticipation…" ) );
        p.add_morale( MORALE_MUTAGEN, 5, 50 );
    }
    p.add_msg_if_player( m_category.mutagen_message() );
    if( one_in( 6 ) ) {
        p.add_msg_player_or_npc( m_bad,
                                 _( "You suddenly feel dizzy, and collapse to the ground." ),
                                 _( "<npcname> suddenly collapses to the ground!" ) );
        p.add_effect( effect_downed, 20_turns, num_bp, 0 );
    }
    int mut_count = 1 + ( is_strong ? one_in( 3 ) : 0 );
    for( int i = 0; i < mut_count; i++ ) {
        p.mutate_category( m_category.id );
        p.mod_pain( m_category.mutagen_pain * rng( 1, 5 ) );
    }
    // burn calories directly
    p.mod_stored_nutr( m_category.mutagen_hunger * mut_count );
    p.mod_thirst( m_category.mutagen_thirst * mut_count );
    p.mod_fatigue( m_category.mutagen_fatigue * mut_count );
    return it.type->charges_to_use();
}
References _, Creature::add_effect(), Character::add_morale(), player::add_msg_if_player(), player::add_msg_player_or_npc(), mutagen_attempt::allowed, itype::charges_to_use(), mutagen_attempt::charges_used, consumed_mutagen, effect_accumulated_mutagen, effect_downed, mutation_category_trait::get_category(), Creature::get_effect_int(), Character::has_trait(), mutation_category_trait::id, m_bad, m_good, Character::mod_fatigue(), Character::mod_pain(), Character::mod_stored_nutr(), Character::mod_thirst(), MORALE_MUTAGEN, mutagen_common_checks(), mutation_category_trait::mutagen_fatigue, mutation_category_trait::mutagen_hunger, mutation_category_trait::mutagen_message(), mutation_category_trait::mutagen_pain, mutation_category_trait::mutagen_thirst, Character::mutate_category(), num_bp, one_in(), player::query_yn(), rng(), trait_MUT_JUNKIE, and item::type.
Member Data Documentation
is_strong
bool mutagen_actor::is_strong = false
Definition at line 1186 of file iuse_actor.h.
is_weak
bool mutagen_actor::is_weak = false
Definition at line 1185 of file iuse_actor.h.
mutation_category
std::string mutagen_actor::mutation_category
Definition at line 1184 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp