Cataclysm BN: diary Class Reference
diary Class Reference
diary is connected to the player avatar.
#include <diary.h>
Public Member Functions
diary ()
virtual ~diary ()=default
void death_entry ()
bool store ()
void load ()
void serialize (std::ostream &fout)
void deserialize (std::istream &fin)
void deserialize (JsonIn &jsin)
void serialize (JsonOut &jsout)
Static Public Member Functions
static void show_diary_ui (diary *c_diary)
Private Member Functions
void edit_page_ui ()
void edit_page_ui (const std::function< catacurses::window()> &create_window)
int set_opened_page (int page_number)
void new_page ()
void set_page_text (std::string text)
void delete_page ()
std::vector< std::string > get_pages_list ()
std::vector< std::string > get_change_list ()
std::map< int, std::string > get_desc_map ()
diary_page * get_page_ptr (int offset=0)
std::string get_page_text ()
std::vector< std::string > get_head_text ()
void skill_changes ()
void kill_changes ()
void trait_changes ()
void bionic_changes ()
void stat_changes ()
void mission_changes ()
void spell_changes ()
void martial_art_changes ()
void max_power_level_changes ()
void export_to_md (bool last_export=false)
void add_to_change_list (std::string entry, std::string desc="")
Private Attributes
std::string owner
std::vector< std::unique_ptr< diary_page > > pages
int opened_page = 0
std::vector< std::string > change_list
std::map< int, std::string > desc_map
Detailed Description
diary is connected to the player avatar.
the player is able to add new pages, every page saves the current character progression and shows the improvements compared to the previous pages the player is also able to add a text in every page.
Definition at line 62 of file diary.h.
Constructor & Destructor Documentation
diary()
diary::diary ()
Definition at line 681 of file diary.cpp.
{
    owner = get_avatar().name;
}
References get_avatar(), Character::name, and owner.
~diary()
virtual diary::~diary () virtual default
Member Function Documentation
add_to_change_list()
void diary::add_to_change_list (std::string entry, std::string desc = "") private
Definition at line 67 of file diary.cpp.
{
    if( !desc.empty() ) {
        desc_map[change_list.size() + get_head_text().size()] = desc;
    }
    change_list.push_back( entry );
}
References change_list, desc_map, and get_head_text().
Referenced by bionic_changes(), kill_changes(), martial_art_changes(), max_power_level_changes(), mission_changes(), skill_changes(), spell_changes(), stat_changes(), and trait_changes().
bionic_changes()
void diary::bionic_changes () private
Definition at line 232 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        if( !curr_page->bionics.empty() ) {
            add_to_change_list( _( "Bionics:" ) );
            for( const bionic_id &elem : curr_page->bionics ) {
                const bionic_data &b = elem.obj();
                add_to_change_list( b.name.translated(), b.description.translated() );
            }
            add_to_change_list( " " );
        }
    } else {
        bool flag = true;
        if( !curr_page->bionics.empty() ) {
            for( const bionic_id &elem : curr_page->bionics ) {
                if( std::find( prev_page->bionics.begin(), prev_page->bionics.end(),
                               elem ) == prev_page->bionics.end() ) {
                    if( flag ) {
                        add_to_change_list( _( "New bionics:" ) );
                        flag = false;
                    }
                    const bionic_data &b = elem.obj();
                    add_to_change_list( b.name.translated(), b.description.translated() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
        flag = true;
        if( !prev_page->bionics.empty() ) {
            for( const bionic_id &elem : prev_page->bionics ) {
                if( std::find( curr_page->bionics.begin(), curr_page->bionics.end(),
                               elem ) == curr_page->bionics.end() ) {
                    if( flag ) {
                        add_to_change_list( _( "Lost bionics:" ) );
                        flag = false;
                    }
                    const bionic_data &b = elem.obj();
                    add_to_change_list( b.name.translated(), b.description.translated() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
    }
}
References _, add_to_change_list(), b, diary_page::bionics, detail::find(), get_page_ptr(), and string_id< T >::obj().
Referenced by get_change_list().
death_entry()
void diary::death_entry ()
Definition at line 672 of file diary.cpp.
{
    bool last_time = query_yn( _( "Open your diary for the last time?" ) );
    if( last_time ) {
        show_diary_ui( this );
    }
    export_to_md( true );
}
References _, export_to_md(), query_yn(), and show_diary_ui().
Referenced by game::death_screen().
delete_page()
void diary::delete_page () private
Definition at line 723 of file diary.cpp.
{
    if( opened_page < static_cast<int>( pages.size() ) ) {
        pages.erase( pages.begin() + opened_page );
        set_opened_page( opened_page - 1 );
    }
}
References opened_page, pages, and set_opened_page().
Referenced by show_diary_ui().
deserialize() [1/2]
void diary::deserialize (JsonIn & jsin)
Definition at line 827 of file diary.cpp.
{
    try {
        JsonObject data = jsin.get_object();
        data.read( "owner", owner );
        pages.clear();
        for( JsonObject elem : data.get_array( "pages" ) ) {
            std::unique_ptr<diary_page> page( new diary_page() );
            page->m_text = elem.get_string( "text" );
            elem.read( "turn", page->turn );
            elem.read( "active", page->mission_active );
            elem.read( "completed", page->mission_completed );
            elem.read( "failed", page->mission_failed );
            elem.read( "kills", page->kills );
            elem.read( "npc_kills", page->npc_kills );
            elem.read( "male", page->male );
            elem.read( "str", page->strength );
            elem.read( "dex", page->dexterity );
            elem.read( "int", page->intelligence );
            elem.read( "per", page->perception );
            elem.read( "traits", page->traits );
            elem.read( "bionics", page->bionics );
            elem.read( "spells", page->known_spells );
            elem.read( "skill_levels", page->skill_levels );
            elem.read( "martial_arts", page->known_martial_arts );
            elem.read( "max_power_level", page->max_power_level );
            diary::pages.push_back( std::move( page ) );
        }
    } catch( const JsonError &e ) {
    }
}
References JsonObject::get_array(), JsonIn::get_object(), avatar_action::move(), owner, pages, and JsonObject::read().
deserialize() [2/2]
void diary::deserialize (std::istream & fin)
Definition at line 821 of file diary.cpp.
{
    JsonIn jsin( fin );
    deserialize( jsin );
}
References deserialize().
Referenced by deserialize(), and load().
edit_page_ui() [1/2]
void diary::edit_page_ui () private
Referenced by show_diary_ui().
edit_page_ui() [2/2]
void diary::edit_page_ui (const std::function< catacurses::window()> & create_window) private
Definition at line 371 of file diary_ui.cpp.
{
    // modify the stored text, so the new text is displayed after exiting from
    // the editor window, and before confirming or canceling the y/n query.
    std::string &new_text = get_page_ptr()->m_text;
    const std::string old_text = new_text;
    string_editor_window ed( create_window, new_text );
    do {
        const std::pair<bool, std::string> result = ed.query_string();
        new_text = result.second;
        // confirmed or unchanged
        if( result.first || old_text == new_text ) {
            break;
        }
        const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
        const auto &allow_key = force_uc ? input_context::disallow_lower_case
                                : input_context::allow_all_keys;
        const std::string action = query_popup()
                                   .context( "YESNOQUIT" )
                                   .message( "%s", _( "Save entry?" ) )
                                   .option( "YES", allow_key )
                                   .option( "NO", allow_key )
                                   .allow_cancel( true )
                                   .default_color( c_light_red )
                                   .query()
                                   .action;
        if( action == "YES" ) {
            break;
        } else if( action == "NO" ) {
            new_text = old_text;
            break;
        }
    } while( true );
}
References _, action, query_popup::result::action, input_context::allow_all_keys, query_popup::allow_cancel(), c_light_red, query_popup::context(), query_popup::default_color(), input_context::disallow_lower_case, get_page_ptr(), diary_page::m_text, query_popup::message(), query_popup::option(), query_popup::query(), and string_editor_window::query_string().
export_to_md()
void diary::export_to_md (bool last_export = false) private
Definition at line 731 of file diary.cpp.
{
    std::ofstream myfile;
    std::string path = last_export ? PATH_INFO::memorialdir() : g->get_world_base_save_path();
    path += "/" + owner + "s_diary.md";
    myfile.open( path );
    for( int i = 0; i < static_cast<int>( pages.size() ); i++ ) {
        set_opened_page( i );
        const diary_page page = *get_page_ptr();
        std::vector<std::string> left_diary_text = this->get_head_text();
        std::vector<std::string> change_list = this->get_change_list();
        left_diary_text.insert( left_diary_text.end(), change_list.begin(), change_list.end() );
        // add "## " before each "Entry" line to visually differentiate each page
        left_diary_text[0] = "## " + left_diary_text[0];
        for( const std::string &str : left_diary_text ) {
            myfile << remove_color_tags( str ) + "\n";
        }
        const std::vector<std::string> folded_texts = foldstring( page.m_text, 50 );
        for( const std::string_view folded_text : folded_texts ) {
            myfile << folded_text << "\n";
        }
        myfile << "\n\n\n";
    }
    myfile.close();
}
References change_list, foldstring(), g, get_change_list(), get_head_text(), get_page_ptr(), PATH_INFO::memorialdir(), owner, pages, remove_color_tags(), and set_opened_page().
Referenced by death_entry(), and show_diary_ui().
get_change_list()
std::vector< std::string > diary::get_change_list () private
Definition at line 577 of file diary.cpp.
{
    if( !change_list.empty() ) {
        return change_list;
    }
    if( !pages.empty() ) {
        stat_changes();
        skill_changes();
        trait_changes();
        bionic_changes();
        max_power_level_changes();
        spell_changes();
        martial_art_changes();
        mission_changes();
        kill_changes();
    }
    return change_list;
}
References bionic_changes(), change_list, kill_changes(), martial_art_changes(), max_power_level_changes(), mission_changes(), pages, skill_changes(), spell_changes(), stat_changes(), and trait_changes().
Referenced by export_to_md(), get_desc_map(), and show_diary_ui().
get_desc_map()
std::map< int, std::string > diary::get_desc_map () private
Definition at line 596 of file diary.cpp.
{
    if( !desc_map.empty() ) {
        return desc_map;
    } else {
        get_change_list();
        return desc_map;
    }
}
References desc_map, and get_change_list().
Referenced by show_diary_ui().
get_head_text()
std::vector< std::string > diary::get_head_text () private
Definition at line 616 of file diary.cpp.
{
    if( !pages.empty() ) {
        const diary_page *prev_page_ptr = get_page_ptr( -1 );
        const time_point prev_turn = ( prev_page_ptr != nullptr ) ? prev_page_ptr->turn :
                                     calendar::turn_zero;
        const time_duration turn_diff = get_page_ptr()->turn - prev_turn;
        const int days = to_days<int>( turn_diff );
        const int hours = to_hours<int>( turn_diff ) % 24;
        const int minutes = to_minutes<int>( turn_diff ) % 60;
        const int seconds = to_seconds<int>( turn_diff ) % 60;
        std::string time_diff_text;
        if( opened_page != 0 ) {
            // will display the time since last entry (excluding days) as "hours:min:sec"
            std::string days_text;
            std::string time_text;
            if( days > 0 ) {
                days_text = string_format( vgettext( "%d day, ", "%d days, ", days ), days );
            }
            time_text += ( hours > 9 ) ? std::to_string( hours ) : "0" + std::to_string( hours );
            time_text += ":";
            time_text += ( minutes > 9 ) ? std::to_string( minutes ) : "0" + std::to_string( minutes );
            time_text += ":";
            time_text += ( seconds > 9 ) ? std::to_string( seconds ) : "0" + std::to_string( seconds );
            //~ %1$s is xx days, %2$d is the time left in universal format
            time_diff_text = string_format( _( "%1$s%2$s since last entry" ),
                                            days_text, time_text );
        }
        //~ Head text of a diary page
        //~ %1$d is the current page number, %2$d is the number of pages in total
        std::vector<std::string> head_text = { string_format( _( "Entry: %1$d/%2$d" ), opened_page + 1, pages.size() ) };
        std::string complete_time_text = to_string( get_page_ptr()->turn ); // get complete time
        std::string day_and_time_text = complete_time_text.substr( complete_time_text.find_last_of( ',' ) +
                                        2 );
        day_and_time_text[0] = std::toupper( day_and_time_text[0] );
        std::string year_and_season_text = complete_time_text.substr( 0,
                                           complete_time_text.find_last_of( ',' ) + 1 );
        head_text.insert( head_text.end(), year_and_season_text );
        head_text.insert( head_text.end(), day_and_time_text );
        head_text.insert( head_text.end(), time_diff_text );
        if( !time_diff_text.empty() ) {
            head_text.insert( head_text.end(), { "" } );
        }
        return head_text;
    }
    return { "" };
}
References _, get_page_ptr(), opened_page, pages, string_format(), to_string(), calendar::turn, diary_page::turn, calendar::turn_zero, and vgettext().
Referenced by add_to_change_list(), export_to_md(), and show_diary_ui().
get_page_ptr()
diary_page * diary::get_page_ptr (int offset = 0) private
Definition at line 58 of file diary.cpp.
{
    if( !pages.empty() && opened_page + offset >= 0 ) {
        return pages[opened_page + offset].get();
    }
    return nullptr;
}
References opened_page, and pages.
Referenced by bionic_changes(), edit_page_ui(), export_to_md(), get_head_text(), get_page_text(), kill_changes(), martial_art_changes(), max_power_level_changes(), mission_changes(), set_page_text(), skill_changes(), spell_changes(), stat_changes(), and trait_changes().
get_page_text()
std::string diary::get_page_text () private
Definition at line 607 of file diary.cpp.
{
    if( !pages.empty() ) {
        return get_page_ptr()->m_text;
    }
    return "";
}
References get_page_ptr(), diary_page::m_text, and pages.
Referenced by show_diary_ui().
get_pages_list()
std::vector< std::string > diary::get_pages_list () private
Definition at line 32 of file diary.cpp.
{
    std::vector<std::string> result;
    for( std::unique_ptr<diary_page> &n : pages ) {
        result.push_back( to_string( n->turn ) );
    }
    return result;
}
References pages, and to_string().
Referenced by show_diary_ui().
kill_changes()
void diary::kill_changes () private
Definition at line 289 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        if( !curr_page->kills.empty() ) {
            add_to_change_list( _( "Kills:" ) );
            for( const std::pair<const string_id<mtype>, int> &elem : curr_page->kills ) {
                const mtype &m = elem.first.obj();
                nc_color color = m.color;
                std::string symbol = m.sym;
                std::string nname = m.nname( elem.second );
                add_to_change_list( string_format( "%4d ", elem.second ) + colorize( symbol,
                                    color ) + " " + colorize( nname, c_light_gray ), m.get_description() );
            }
            add_to_change_list( " " );
        }
        if( !curr_page->npc_kills.empty() ) {
            add_to_change_list( _( "NPC killed:" ) );
            for( const std::string &npc_name : curr_page->npc_kills ) {
                add_to_change_list( string_format( "%4d ", 1 ) + colorize( "@ " + npc_name, c_magenta ) );
            }
            add_to_change_list( " " );
        }
    } else {
        if( !curr_page->kills.empty() ) {
            bool flag = true;
            for( const std::pair<const string_id<mtype>, int> &elem : curr_page->kills ) {
                const mtype &m = elem.first.obj();
                nc_color color = m.color;
                std::string symbol = m.sym;
                std::string nname = m.nname( elem.second );
                int kills = elem.second;
                if( prev_page->kills.count( elem.first ) > 0 ) {
                    const int prev_kills = prev_page->kills[elem.first];
                    if( kills > prev_kills ) {
                        if( flag ) {
                            add_to_change_list( _( "Kills:" ) );
                            flag = false;
                        }
                        kills = kills - prev_kills;
                        add_to_change_list( string_format( "%4d ", kills ) + colorize( symbol,
                                            color ) + " " + colorize( nname, c_light_gray ), m.get_description() );
                    }
                } else {
                    if( flag ) {
                        add_to_change_list( _( "Kills:" ) );
                        flag = false;
                    }
                    add_to_change_list( string_format( "%4d ", kills ) + colorize( symbol,
                                        color ) + " " + colorize( nname, c_light_gray ), m.get_description() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
        if( !curr_page->npc_kills.empty() ) {
            const std::vector<std::string> &prev_npc_kills = prev_page->npc_kills;
            bool flag = true;
            for( const std::string &npc_name : curr_page->npc_kills ) {
                if( ( std::find( prev_npc_kills.begin(), prev_npc_kills.end(),
                                 npc_name ) == prev_npc_kills.end() ) ) {
                    if( flag ) {
                        add_to_change_list( _( "NPC killed:" ) );
                        flag = false;
                    }
                    add_to_change_list( string_format( "%4d ", 1 ) + colorize( "@ " + npc_name, c_magenta ) );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
    }
}
References _, add_to_change_list(), c_light_gray, c_magenta, color(), mtype::color, colorize(), detail::find(), mtype::get_description(), get_page_ptr(), diary_page::kills, mtype::nname(), diary_page::npc_kills, string_format(), mtype::sym, and symbol().
Referenced by get_change_list().
load()
void diary::load ()
Definition at line 810 of file diary.cpp.
{
    std::string name = base64_encode( get_avatar().get_name() + "_diary" );
    std::string path = g->get_world_base_save_path() + "/" + name + ".json";
    if( file_exist( path ) ) {
        read_from_file( path, [&]( std::istream & fin ) {
            deserialize( fin );
        } );
    }
}
References base64_encode(), deserialize(), file_exist(), g, get_avatar(), om_direction::name(), and read_from_file().
Referenced by game::load().
martial_art_changes()
void diary::martial_art_changes () private
Definition at line 126 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        if( !curr_page->known_martial_arts.empty() ) {
            add_to_change_list( _( "Known martial arts:" ) );
            for( const matype_id &elem : curr_page->known_martial_arts ) {
                const auto &ma = elem.obj();
                add_to_change_list( ma.name.translated(), ma.description.translated() );
            }
            add_to_change_list( "" );
        }
    } else {
        if( prev_page->known_martial_arts.empty() && !curr_page->known_martial_arts.empty() ) {
            add_to_change_list( _( "New martial arts:" ) );
            for( const matype_id &elem : curr_page->known_martial_arts ) {
                const auto &ma = elem.obj();
                add_to_change_list( ma.name.translated(), ma.description.translated() );
            }
            add_to_change_list( "" );
        } else {
            bool flag = true;
            for( const matype_id &elem : curr_page->known_martial_arts ) {
                if( std::find( prev_page->known_martial_arts.begin(), prev_page->known_martial_arts.end(),
                               elem ) == prev_page->known_martial_arts.end() ) {
                    if( flag ) {
                        add_to_change_list( _( "New martial arts:" ) );
                        flag = false;
                    }
                    const auto &ma = elem.obj();
                    add_to_change_list( ma.name.translated(), ma.description.translated() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
    }
}
References _, add_to_change_list(), detail::find(), get_page_ptr(), diary_page::known_martial_arts, and string_id< T >::obj().
Referenced by get_change_list().
max_power_level_changes()
void diary::max_power_level_changes () private
Definition at line 552 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        add_to_change_list( "Max power:" );
        add_to_change_list( string_format( _( "<color_yellow>%ikJ</color>" ),
                                           units::to_kilojoule( curr_page->max_power_level ) ) );
        add_to_change_list( " " );
    } else {
        if( curr_page->max_power_level != prev_page->max_power_level ) {
            add_to_change_list( "Max power:" );
            add_to_change_list( string_format(
                                    _( "<color_yellow>%i</color> -> <color_yellow>%ikJ</color>" ),
                                    units::to_kilojoule( prev_page->max_power_level ),
                                    units::to_kilojoule( curr_page->max_power_level ) ) );
            add_to_change_list( " " );
        }
    }
}
References _, add_to_change_list(), get_page_ptr(), diary_page::max_power_level, string_format(), and units::to_kilojoule().
Referenced by get_change_list().
mission_changes()
void diary::mission_changes () private
Definition at line 172 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        auto add_missions = [&]( const std::string name, const std::vector<int> *missions ) {
            if( !missions->empty() ) {
                bool flag = true;
                for( const int uid : *missions ) {
                    mission *miss = mission::find( uid );
                    if( miss != nullptr ) {
                        if( flag ) {
                            add_to_change_list( name );
                            flag = false;
                        }
                        add_to_change_list( miss->name(), miss->get_description() );
                    }
                }
                if( !flag ) {
                    add_to_change_list( " " );
                }
            }
        };
        add_missions( _( "Active missions:" ), &curr_page->mission_active );
        add_missions( _( "Completed missions:" ), &curr_page->mission_completed );
        add_missions( _( "Failed missions:" ), &curr_page->mission_failed );
    } else {
        auto add_missions = [&]( const std::string name, const std::vector<int> *missions,
        const std::vector<int> *prev_missions ) {
            bool flag = true;
            for( const int uid : *missions ) {
                if( std::find( prev_missions->begin(), prev_missions->end(), uid ) == prev_missions->end() ) {
                    mission *miss = mission::find( uid );
                    if( miss != nullptr ) {
                        if( flag ) {
                            add_to_change_list( name );
                            flag = false;
                        }
                        add_to_change_list( miss->name(), miss->get_description() );
                    }
                }
                if( !flag ) {
                    add_to_change_list( " " );
                }
            }
        };
        add_missions( _( "New missions:" ), &curr_page->mission_active, &prev_page->mission_active );
        add_missions( _( "New completed missions:" ), &curr_page->mission_completed,
                      &prev_page->mission_completed );
        add_missions( _( "New failed missions:" ), &curr_page->mission_failed, &prev_page->mission_failed );
    }
}
References _, add_to_change_list(), mission::find(), detail::find(), mission::get_description(), get_page_ptr(), diary_page::mission_active, diary_page::mission_completed, diary_page::mission_failed, mission::name(), and om_direction::name().
Referenced by get_change_list().
new_page()
void diary::new_page () private
Definition at line 690 of file diary.cpp.
{
    std::unique_ptr<diary_page> page( new diary_page() );
    page->m_text = std::string();
    page->turn = calendar::turn;
    page->kills = g->get_kill_tracker().kills;
    page->npc_kills = g->get_kill_tracker().npc_kills;
    avatar *u = &get_avatar();
    page->mission_completed = mission::to_uid_vector( u->get_completed_missions() );
    page->mission_active = mission::to_uid_vector( u->get_active_missions() );
    page->mission_failed = mission::to_uid_vector( u->get_failed_missions() );
    page->male = u->male;
    page->strength = u->get_str_base();
    page->dexterity = u->get_dex_base();
    page->intelligence = u->get_int_base();
    page->perception = u->get_per_base();
    page->traits = u->get_mutations( false );
    const auto spells = u->magic->get_spells();
    for( const spell *spell : spells ) {
        const spell_id &id = spell->id();
        const int lvl = spell->get_level();
        page->known_spells[id] = lvl;
    }
    page->known_martial_arts = u->martial_arts_data->get_known_styles();
    page->bionics = u->get_bionics();
    for( Skill &elem : Skill::skills ) {
        int level = u->get_skill_level_object( elem.ident() ).level();
        page->skill_levels.insert( { elem.ident(), level } );
    }
    page->max_power_level = u->get_max_power_level();
    diary::pages.push_back( std::move( page ) );
}
References g, avatar::get_active_missions(), get_avatar(), Character::get_bionics(), avatar::get_completed_missions(), avatar::get_dex_base(), avatar::get_failed_missions(), avatar::get_int_base(), spell::get_level(), Character::get_max_power_level(), Character::get_mutations(), avatar::get_per_base(), Character::get_skill_level_object(), avatar::get_str_base(), base_camps::id, spell::id(), SkillLevel::level(), Character::magic, Character::male, Character::martial_arts_data, avatar_action::move(), pages, Skill::skills, mission::to_uid_vector(), and calendar::turn.
Referenced by show_diary_ui().
serialize() [1/2]
void diary::serialize (JsonOut & jsout)
Definition at line 778 of file diary.cpp.
{
    jsout.member( "owner", owner );
    jsout.member( "pages" );
    jsout.start_array();
    for( std::unique_ptr<diary_page> &n : pages ) {
        jsout.start_object();
        jsout.member( "text", n->m_text );
        jsout.member( "turn", n->turn );
        jsout.member( "completed", n->mission_completed );
        jsout.member( "active", n->mission_active );
        jsout.member( "failed", n->mission_failed );
        jsout.member( "kills", n->kills );
        jsout.member( "npc_kills", n->npc_kills );
        jsout.member( "male", n->male );
        jsout.member( "str", n->strength );
        jsout.member( "dex", n->dexterity );
        jsout.member( "int", n->intelligence );
        jsout.member( "per", n->perception );
        jsout.member( "traits", n->traits );
        jsout.member( "bionics", n->bionics );
        jsout.member( "spells", n->known_spells );
        jsout.member( "skill_levels", n->skill_levels );
        jsout.member( "martial_arts", n->known_martial_arts );
        jsout.member( "max_power_level", n->max_power_level );
        jsout.end_object();
    }
    jsout.end_array();
}
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), owner, pages, JsonOut::start_array(), and JsonOut::start_object().
serialize() [2/2]
void diary::serialize (std::ostream & fout)
Definition at line 770 of file diary.cpp.
{
    JsonOut jsout( fout, true );
    jsout.start_object();
    serialize( jsout );
    jsout.end_object();
}
References JsonOut::end_object(), serialize(), and JsonOut::start_object().
Referenced by serialize(), and store().
set_opened_page()
int diary::set_opened_page (int page_number) private
Definition at line 41 of file diary.cpp.
{
    if( page_number != opened_page ) {
        change_list.clear();
        desc_map.clear();
    }
    if( pages.empty() ) {
        opened_page = -1;
    } else if( page_number < 0 ) {
        opened_page = pages.size() - 1;
    } else {
        opened_page = page_number % pages.size();
    }
    return opened_page;
}
References change_list, desc_map, opened_page, and pages.
Referenced by delete_page(), export_to_md(), and show_diary_ui().
set_page_text()
void diary::set_page_text (std::string text) private
Definition at line 685 of file diary.cpp.
{
    get_page_ptr()->m_text = text;
}
References get_page_ptr(), and diary_page::m_text.
show_diary_ui()
void diary::show_diary_ui (diary * c_diary) static
Definition at line 164 of file diary_ui.cpp.
{
    catacurses::window w_diary;
    catacurses::window w_pages; // pages window, left of diary
    catacurses::window w_text; // right part of diary
    catacurses::window w_changes; // left part of diary
    catacurses::window w_border; // borders of diary
    catacurses::window w_desc; // keybindings window up
    catacurses::window w_info; // bottom window
    enum class window_mode : int { PAGE_WIN = 0, CHANGE_WIN, TEXT_WIN, NUM_WIN, FIRST_WIN = 0, LAST_WIN = NUM_WIN - 1 };
    window_mode currwin = window_mode::PAGE_WIN;
    std::map<window_mode, int> selected = { {window_mode::PAGE_WIN, 0}, {window_mode::CHANGE_WIN, 0}, {window_mode::TEXT_WIN, 0} };
    input_context ctxt( "DIARY" );
    ctxt.register_cardinal();
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "NEW_PAGE" );
    ctxt.register_action( "DELETE PAGE" );
    ctxt.register_action( "EXPORT_DIARY" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ui_adaptor ui_diary;
    ui_diary.on_screen_resize( [&]( ui_adaptor & ui ) {
        const std::pair<point, point> beg_and_max = diary_window_position();
        const point &beg = ( uis_padding() != 0 ) ? point( uis_padding() + MAX_DAIRY_UI_WIDTH / 4 - 3,
                           beg_and_max.first.y - 1 ) : beg_and_max.first + point( uis_padding() - 3, -1 );
        const point &max = point( TERMX - beg.x - 5,
                                  beg_and_max.second.y ) - point( uis_padding(), 0 );
        const int midx = max.x / 2;
        w_changes = catacurses::newwin( max.y - 3, midx - 1, beg + point_south );
        w_text = catacurses::newwin( max.y - 3, max.x - midx - 1, beg + point( 2 + midx, 3 ) );
        w_border = catacurses::newwin( max.y + 5, max.x + 9, beg + point( -4, -2 ) );
        ui.position_from_window( w_border );
    } );
    ui_diary.mark_resize();
    ui_diary.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_changes );
        werase( w_text );
        werase( w_border );
        draw_diary_border( &w_border );
        // first get head text, then add the change list to it
        std::vector<std::string> left_diary_text = c_diary->get_head_text();
        std::vector<std::string> change_list = c_diary->get_change_list();
        left_diary_text.insert( left_diary_text.end(), change_list.begin(), change_list.end() );
        print_list_scrollable( &w_changes, left_diary_text, &selected[window_mode::CHANGE_WIN],
                               currwin == window_mode::CHANGE_WIN, false, report_color_error::yes );
        print_list_scrollable( &w_text, c_diary->get_page_text(), &selected[window_mode::TEXT_WIN],
                               currwin == window_mode::TEXT_WIN, false, report_color_error::no );
        wnoutrefresh( w_border );
        wnoutrefresh( w_changes );
        wnoutrefresh( w_text );
    } );
    ui_adaptor ui_pages;
    ui_pages.on_screen_resize( [&]( ui_adaptor & ui ) {
        const std::pair<point, point> beg_and_max = diary_window_position();
        const point &beg = beg_and_max.first;
        const point &max = beg_and_max.second;
        w_pages = catacurses::newwin( max.y + 5,
                                      ( uis_padding() != 0 ) ? MAX_DAIRY_UI_WIDTH / 4 - 7 : beg.x - 7, point( uis_padding(),
                                              beg.y - 3 ) );
        ui.position_from_window( w_pages );
    } );
    ui_pages.mark_resize();
    ui_pages.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_pages );
        print_list_scrollable( &w_pages, c_diary->get_pages_list(), &selected[window_mode::PAGE_WIN],
                               currwin == window_mode::PAGE_WIN, true, report_color_error::yes );
        center_print( w_pages, 0, c_light_gray, string_format( _( "pages: %d" ),
                      c_diary->get_pages_list().size() ) );
        wnoutrefresh( w_pages );
    } );
    ui_adaptor ui_desc;
    ui_desc.on_screen_resize( [&]( ui_adaptor & ui ) {
        const std::pair<point, point> beg_and_max = diary_window_position();
        const point &beg = beg_and_max.first;
        w_desc = catacurses::newwin( 3, TERMX - uis_padding() * 2, point( uis_padding(), beg.y - 6 ) );
        ui.position_from_window( w_desc );
    } );
    ui_desc.mark_resize();
    ui_desc.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_desc );
        draw_border( w_desc );
        center_print( w_desc, 0, c_light_gray, string_format( _( "%s's Diary" ), c_diary->owner ) );
        std::string desc = string_format( _( "%s, %s, %s, %s" ),
                                          ctxt.get_desc( "NEW_PAGE", _( "New page" ), input_context::allow_all_keys ),
                                          ctxt.get_desc( "CONFIRM", _( "Edit text" ), input_context::allow_all_keys ),
                                          ctxt.get_desc( "DELETE PAGE", _( "Delete page" ), input_context::allow_all_keys ),
                                          ctxt.get_desc( "EXPORT_DIARY", _( "Export diary" ), input_context::allow_all_keys )
                                        );
        center_print( w_desc, 1, c_white, desc );
        wnoutrefresh( w_desc );
    } );
    ui_adaptor ui_info;
    ui_info.on_screen_resize( [&]( ui_adaptor & ui ) {
        const std::pair<point, point> beg_and_max = diary_window_position();
        const point &beg = beg_and_max.first;
        const point &max = beg_and_max.second;
        w_info = catacurses::newwin( ( TERMY - beg.y - max.y - 2 ) > 7 ? 7 : TERMY - beg.y - max.y - 2,
                                     TERMX - uis_padding() * 2, point( uis_padding(), beg.y + max.y + 2 ) );
        ui.position_from_window( w_info );
    } );
    ui_info.mark_resize();
    ui_info.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_info );
        draw_border( w_info );
        center_print( w_info, 0, c_light_gray, string_format( _( "Info" ) ) );
        if( currwin == window_mode::CHANGE_WIN || currwin == window_mode::TEXT_WIN ) {
            fold_and_print( w_info, point_south_east, getmaxx( w_info ) - 2, c_white, string_format( "%s",
                            c_diary->get_desc_map()[selected[window_mode::CHANGE_WIN]] ) );
        }
        wnoutrefresh( w_info );
    } );
    while( true ) {
        if( ( !c_diary->pages.empty() &&
              selected[window_mode::PAGE_WIN] >= static_cast<int>( c_diary->pages.size() ) ) ||
            ( c_diary->pages.empty() && selected[window_mode::PAGE_WIN] != 0 ) ) {
            selected[window_mode::PAGE_WIN] = 0;
        }
        selected[window_mode::PAGE_WIN] = c_diary->set_opened_page( selected[window_mode::PAGE_WIN] );
        ui_diary.invalidate_ui();
        ui_pages.invalidate_ui();
        ui_desc.invalidate_ui();
        ui_info.invalidate_ui();
        ui_manager::redraw_invalidated();
        const std::string action = ctxt.handle_input();
        if( action == "RIGHT" ) {
            currwin = static_cast<window_mode>( static_cast<int>( currwin ) + 1 );
            if( currwin >= window_mode::NUM_WIN ) {
                currwin = window_mode::FIRST_WIN;
            }
            selected[window_mode::TEXT_WIN] = 0;
        } else if( action == "LEFT" ) {
            currwin = static_cast<window_mode>( static_cast<int>( currwin ) - 1 );
            if( currwin < window_mode::FIRST_WIN ) {
                currwin = window_mode::LAST_WIN;
            }
            selected[window_mode::TEXT_WIN] = 0;
        } else if( action == "DOWN" ) {
            selected[currwin]++;
            if( selected[window_mode::PAGE_WIN] >= static_cast<int>( c_diary->pages.size() ) ) {
                selected[window_mode::PAGE_WIN] = 0;
            }
        } else if( action == "UP" ) {
            selected[currwin]--;
            if( selected[window_mode::PAGE_WIN] < 0 ) {
                selected[window_mode::PAGE_WIN] = c_diary->pages.empty() ? 0 : c_diary->pages.size() - 1;
            }
        } else if( action == "CONFIRM" ) {
            if( !c_diary->pages.empty() ) {
                c_diary->edit_page_ui( [&]() {
                    return w_text;
                } );
            }
        } else if( action == "NEW_PAGE" ) {
            c_diary->new_page();
            selected[window_mode::PAGE_WIN] = c_diary->pages.size() - 1;
        } else if( action == "DELETE PAGE" ) {
            if( !c_diary->pages.empty() ) {
                if( query_yn( _( "Delete this page from the diary?" ) ) ) {
                    c_diary->delete_page();
                    if( selected[window_mode::PAGE_WIN] >= static_cast<int>( c_diary->pages.size() ) ) {
                        selected[window_mode::PAGE_WIN] --;
                    }
                }
            }
        } else if( action == "EXPORT_DIARY" ) {
            if( query_yn( _( "Export the diary as .md?" ) ) ) {
                c_diary->export_to_md();
            }
        } else if( action == "QUIT" ) {
            break;
        }
    }
}
References _, action, input_context::allow_all_keys, c_light_gray, c_white, center_print(), change_list, delete_page(), diary_window_position(), draw_border(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), edit_page_ui(), export_to_md(), fold_and_print(), get_change_list(), input_context::get_desc(), get_desc_map(), get_head_text(), get_page_text(), get_pages_list(), catacurses::getmaxx(), input_context::handle_input(), ui_adaptor::invalidate_ui(), ui_adaptor::mark_resize(), anonymous_namespace{diary_ui.cpp}::MAX_DAIRY_UI_WIDTH, new_page(), catacurses::newwin(), no, ui_adaptor::on_redraw(), ui_adaptor::on_screen_resize(), owner, pages, point_south, point_south_east, anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), query_yn(), ui_manager::redraw_invalidated(), input_context::register_action(), input_context::register_cardinal(), set_opened_page(), string_format(), TERMX, TERMY, uis_padding(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, point::y, and yes.
Referenced by death_entry(), and game::handle_action().
skill_changes()
void diary::skill_changes () private
Definition at line 380 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        if( curr_page->skill_levels.empty() ) {
            return;
        } else {
            add_to_change_list( _( "Skills:" ) );
            for( const std::pair<const string_id<Skill>, int> &elem : curr_page->skill_levels ) {
                if( elem.second > 0 ) {
                    Skill s = elem.first.obj();
                    add_to_change_list( string_format( "<color_light_blue>%s: %d</color>", s.name(), elem.second ),
                                        s.description() );
                }
            }
            add_to_change_list( "" );
        }
    } else {
        bool flag = true;
        for( const std::pair<const string_id<Skill>, int> &elem : curr_page->skill_levels ) {
            if( prev_page->skill_levels.find( elem.first ) != prev_page->skill_levels.end() ) {
                if( prev_page->skill_levels[elem.first] != elem.second ) {
                    if( flag ) {
                        add_to_change_list( _( "Skills:" ) );
                        flag = false;
                    }
                    Skill s = elem.first.obj();
                    add_to_change_list( string_format( _( "<color_light_blue>%s: %d -> %d</color>" ), s.name(),
                                                       prev_page->skill_levels[elem.first], elem.second ), s.description() );
                }
            }
        }
        if( !flag ) {
            add_to_change_list( " " );
        }
    }
}
References _, add_to_change_list(), Skill::description(), get_page_ptr(), Skill::name(), diary_page::skill_levels, and string_format().
Referenced by get_change_list().
spell_changes()
void diary::spell_changes () private
Definition at line 77 of file diary.cpp.
{
    avatar *u = &get_avatar();
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        if( !curr_page->known_spells.empty() ) {
            add_to_change_list( _( "Known spells:" ) );
            for( const std::pair<const string_id<spell_type>, int> &elem : curr_page->known_spells ) {
                const spell s = u->magic->get_spell( elem.first );
                add_to_change_list( string_format( _( "%s: %d" ), s.name(), elem.second ), s.description() );
            }
            add_to_change_list( " " );
        }
    } else {
        if( !curr_page->known_spells.empty() ) {
            bool flag = true;
            for( const std::pair<const string_id<spell_type>, int> &elem : curr_page->known_spells ) {
                if( prev_page->known_spells.find( elem.first ) != prev_page->known_spells.end() ) {
                    const int prev_lvl = prev_page->known_spells[elem.first];
                    if( elem.second != prev_lvl ) {
                        if( flag ) {
                            add_to_change_list( _( "Improved/new spells: " ) );
                            flag = false;
                        }
                        const spell s = u->magic->get_spell( elem.first );
                        add_to_change_list( string_format( _( "%s: %d -> %d" ), s.name(), prev_lvl, elem.second ),
                                            s.description() );
                    }
                } else {
                    if( flag ) {
                        add_to_change_list( _( "Improved/new spells: " ) );
                        flag = false;
                    }
                    const spell s = u->magic->get_spell( elem.first );
                    add_to_change_list( string_format( _( "%s: %d" ), s.name(), elem.second ), s.description() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
    }
}
References _, add_to_change_list(), spell::description(), get_avatar(), get_page_ptr(), diary_page::known_spells, Character::magic, spell::name(), and string_format().
Referenced by get_change_list().
stat_changes()
void diary::stat_changes () private
Definition at line 494 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        add_to_change_list( _( "Stats:" ) );
        add_to_change_list( string_format( _( "Strength: %d" ), curr_page->strength ) );
        add_to_change_list( string_format( _( "Dexterity: %d" ), curr_page->dexterity ) );
        add_to_change_list( string_format( _( "Intelligence: %d" ), curr_page->intelligence ) );
        add_to_change_list( string_format( _( "Perception: %d" ), curr_page->perception ) );
        add_to_change_list( " " );
    } else {
        bool flag = true;
        if( curr_page->strength != prev_page->strength ) {
            if( flag ) {
                add_to_change_list( _( "Stats:" ) );
                flag = false;
            }
            add_to_change_list( string_format( _( "Strength: %d -> %d" ), prev_page->strength,
                                               curr_page->strength ) );
        }
        if( curr_page->dexterity != prev_page->dexterity ) {
            if( flag ) {
                add_to_change_list( _( "Stats:" ) );
                flag = false;
            }
            add_to_change_list( string_format( _( "Dexterity: %d -> %d" ), prev_page->dexterity,
                                               curr_page->dexterity ) );
        }
        if( curr_page->intelligence != prev_page->intelligence ) {
            if( flag ) {
                add_to_change_list( _( "Stats: " ) );
                flag = false;
            }
            add_to_change_list( string_format( _( "Intelligence: %d -> %d" ), prev_page->intelligence,
                                               curr_page->intelligence ) );
        }
        if( curr_page->perception != prev_page->perception ) {
            if( flag ) {
                add_to_change_list( _( "Stats:" ) );
                flag = false;
            }
            add_to_change_list( string_format( _( "Perception: %d -> %d" ), prev_page->perception,
                                               curr_page->perception ) );
        }
        if( !flag ) {
            add_to_change_list( " " );
        }
    }
}
References _, add_to_change_list(), diary_page::dexterity, get_page_ptr(), diary_page::intelligence, diary_page::perception, diary_page::strength, and string_format().
Referenced by get_change_list().
store()
bool diary::store ()
Definition at line 760 of file diary.cpp.
{
    std::string name = base64_encode( get_avatar().get_name() + "_diary" );
    std::string path = g->get_world_base_save_path() + "/" + name + ".json";
    const bool is_writen = write_to_file( path, [&]( std::ostream & fout ) {
        serialize( fout );
    }, _( "diary data" ) );
    return is_writen;
}
References _, base64_encode(), g, get_avatar(), om_direction::name(), serialize(), and write_to_file().
Referenced by game::save_player_data().
trait_changes()
void diary::trait_changes () private
Definition at line 428 of file diary.cpp.
{
    diary_page *curr_page = get_page_ptr();
    diary_page *prev_page = get_page_ptr( -1 );
    if( curr_page == nullptr ) {
        return;
    }
    if( prev_page == nullptr ) {
        if( !curr_page->traits.empty() ) {
            add_to_change_list( _( "Mutations:" ) );
            for( const trait_id &elem : curr_page->traits ) {
                const mutation_branch &trait = elem.obj();
                add_to_change_list( colorize( trait.name(), trait.get_display_color() ), trait.desc() );
            }
            add_to_change_list( "" );
        }
    } else {
        if( prev_page->traits.empty() && !curr_page->traits.empty() ) {
            add_to_change_list( _( "Mutations:" ) );
            for( const trait_id &elem : curr_page->traits ) {
                const mutation_branch &trait = elem.obj();
                add_to_change_list( colorize( trait.name(), trait.get_display_color() ), trait.desc() );
            }
            add_to_change_list( "" );
        } else {
            bool flag = true;
            for( const trait_id &elem : curr_page->traits ) {
                if( std::find( prev_page->traits.begin(), prev_page->traits.end(),
                               elem ) == prev_page->traits.end() ) {
                    if( flag ) {
                        add_to_change_list( _( "Gained mutations:" ) );
                        flag = false;
                    }
                    const mutation_branch &trait = elem.obj();
                    add_to_change_list( colorize( trait.name(), trait.get_display_color() ), trait.desc() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
            flag = true;
            for( const trait_id &elem : prev_page->traits ) {
                if( std::find( curr_page->traits.begin(), curr_page->traits.end(),
                               elem ) == curr_page->traits.end() ) {
                    if( flag ) {
                        add_to_change_list( _( "Lost mutations:" ) );
                        flag = false;
                    }
                    const mutation_branch &trait = elem.obj();
                    add_to_change_list( colorize( trait.name(), trait.get_display_color() ), trait.desc() );
                }
            }
            if( !flag ) {
                add_to_change_list( " " );
            }
        }
    }
}
References _, add_to_change_list(), colorize(), mutation_branch::desc(), detail::find(), mutation_branch::get_display_color(), get_page_ptr(), mutation_branch::name(), string_id< T >::obj(), and diary_page::traits.
Referenced by get_change_list().
Member Data Documentation
change_list
std::vector<std::string> diary::change_list private
Definition at line 73 of file diary.h.
Referenced by add_to_change_list(), export_to_md(), get_change_list(), set_opened_page(), and show_diary_ui().
desc_map
std::map<int, std::string> diary::desc_map private
Definition at line 75 of file diary.h.
Referenced by add_to_change_list(), get_desc_map(), and set_opened_page().
opened_page
int diary::opened_page = 0 private
Definition at line 71 of file diary.h.
Referenced by delete_page(), get_head_text(), get_page_ptr(), and set_opened_page().
owner
std::string diary::owner private
Definition at line 66 of file diary.h.
Referenced by deserialize(), diary(), export_to_md(), serialize(), and show_diary_ui().
pages
std::vector< std::unique_ptr<diary_page> > diary::pages private
Definition at line 68 of file diary.h.
Referenced by delete_page(), deserialize(), export_to_md(), get_change_list(), get_head_text(), get_page_ptr(), get_page_text(), get_pages_list(), new_page(), serialize(), set_opened_page(), and show_diary_ui().
The documentation for this class was generated from the following files:
src/diary.h
src/diary.cpp
src/diary_ui.cpp