Cataclysm BN: emit Class Reference
emit Class Reference
#include <emit.h>
Public Member Functions
emit ()
const emit_id & id () const
bool is_null () const
When null field is always fd_null.
bool is_valid () const
When valid field is never fd_null.
field_type_id field () const
Type of field to emit.
int intensity () const
Intensity of output fields, range [1..maximum_intensity].
int qty () const
Units of field to generate per turn subject to chance.
int chance () const
Chance to emit each turn, range [1..100].
Static Public Member Functions
static void load_emit (const JsonObject &jo)
Load emission data from JSON definition.
static const std::map< emit_id, emit > & all ()
Get all currently loaded emission data.
static void finalize ()
Check consistency of all loaded emission data.
static void check_consistency ()
Check consistency of all loaded emission data.
static void reset ()
Clear all loaded emission data (invalidating any pointers)
Private Attributes
emit_id id_
field_type_id field_ = fd_null
int intensity_ = 1
int qty_ = 1
int chance_ = 100
std::string field_name
used during JSON loading only
Detailed Description
Definition at line 13 of file emit.h.
Constructor & Destructor Documentation
emit()
emit::emit ()
Definition at line 37 of file emit.cpp.
: id_(emit_id::NULL_ID()) {}
Member Function Documentation
all()
const std::map< emit_id, emit > & emit::all () static
Get all currently loaded emission data.
Definition at line 58 of file emit.cpp.
{
    return emits_all;
}
References emits_all.
chance()
int emit::chance () const inline
Chance to emit each turn, range [1..100].
Definition at line 44 of file emit.h.
{
            return chance_;
        }
References chance_.
Referenced by map::emit_field().
check_consistency()
void emit::check_consistency () static
Check consistency of all loaded emission data.
Definition at line 69 of file emit.cpp.
{
    for( auto &e : emits_all ) {
        const int max_intensity = e.second.field_.obj().get_max_intensity();
        if( e.second.intensity_ > max_intensity || e.second.intensity_ < 1 ) {
            debugmsg( "emission intensity of %s out of range (%d of max %d)", e.second.id_.c_str(),
                      e.second.intensity_, max_intensity );
            e.second.intensity_ = max_intensity;
        }
        if( e.second.qty_ <= 0 ) {
            debugmsg( "emission qty of %s out of range", e.second.id_.c_str() );
        }
        if( e.second.chance_ > 100 || e.second.chance_ <= 0 ) {
            debugmsg( "emission chance of %s out of range (%d of min 1 max 100)", e.second.id_.c_str(),
                      e.second.chance_ );
            e.second.chance_ = std::max( std::min( e.second.chance_, 100 ), 1 );
        }
    }
}
References debugmsg, and emits_all.
Referenced by DynamicDataLoader::check_consistency().
field()
field_type_id emit::field () const inline
Type of field to emit.
See also
emit::is_valid
Definition at line 29 of file emit.h.
{
            return field_;
        }
References field_.
Referenced by map::emit_field().
finalize()
void emit::finalize () static
Check consistency of all loaded emission data.
Definition at line 63 of file emit.cpp.
{
    for( auto &e : emits_all ) {
        e.second.field_ = field_type_id( e.second.field_name );
    }
}
References emits_all.
Referenced by DynamicDataLoader::finalize_loaded_data().
id()
const emit_id & emit::id () const inline
Definition at line 18 of file emit.h.
{
            return id_;
        }
References id_.
intensity()
int emit::intensity () const inline
Intensity of output fields, range [1..maximum_intensity].
Definition at line 34 of file emit.h.
{
            return intensity_;
        }
References intensity_.
Referenced by map::emit_field().
is_null()
bool emit::is_null () const
When null field is always fd_null.
Definition at line 39 of file emit.cpp.
{
    return id_ == emit_id::NULL_ID();
}
References id_, and string_id< emit >::NULL_ID().
is_valid()
bool emit::is_valid () const
When valid field is never fd_null.
load_emit()
void emit::load_emit (const JsonObject & jo) static
Load emission data from JSON definition.
Definition at line 44 of file emit.cpp.
{
    emit et;
    et.id_ = emit_id( jo.get_string( "id" ) );
    et.field_name = jo.get_string( "field" );
    jo.read( "intensity", et.intensity_ );
    jo.read( "qty", et.qty_ );
    jo.read( "chance", et.chance_ );
    emits_all[ et.id_ ] = et;
}
References chance_, emits_all, field_name, JsonObject::get_string(), id_, intensity_, qty_, and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
qty()
int emit::qty () const inline
Units of field to generate per turn subject to chance.
Definition at line 39 of file emit.h.
{
            return qty_;
        }
References qty_.
Referenced by map::emit_field().
reset()
void emit::reset () static
Clear all loaded emission data (invalidating any pointers)
Definition at line 89 of file emit.cpp.
{
    emits_all.clear();
}
References emits_all.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
chance_
int emit::chance_ = 100 private
Definition at line 68 of file emit.h.
Referenced by chance(), and load_emit().
field_
field_type_id emit::field_ = fd_null private
Definition at line 65 of file emit.h.
Referenced by field().
field_name
std::string emit::field_name private
used during JSON loading only
Definition at line 71 of file emit.h.
Referenced by load_emit().
id_
emit_id emit::id_ private
Definition at line 64 of file emit.h.
Referenced by id(), is_null(), and load_emit().
intensity_
int emit::intensity_ = 1 private
Definition at line 66 of file emit.h.
Referenced by intensity(), and load_emit().
qty_
int emit::qty_ = 1 private
Definition at line 67 of file emit.h.
Referenced by load_emit(), and qty().
The documentation for this class was generated from the following files:
src/emit.h
src/emit.cpp