Cataclysm BN: Trait_group_collection Class Reference
Trait_group_collection Class Reference
A collection of traits to generate.
#include <trait_group.h>
Public Member Functions
Trait_group_collection (int probability)
~Trait_group_collection () override=default
trait_group::Trait_list create (RecursionList &rec) const override
Create a list of traits.
void add_entry (std::unique_ptr< Trait_creation_data > ptr) override
Once the relevant data has been read from JSON, this function is always called (either from mutation_branch::add_entry, add_trait_entry or add_group_entry).
Public Member Functions inherited from Trait_group
Trait_group (int probability)
~Trait_group () override=default
void add_trait_entry (const trait_id &tid, int probability)
void add_group_entry (const trait_group::Trait_group_tag &gid, int probability)
void check_consistency () const override
Check the trait templates for consistency (valid trait types, etc).
bool remove_trait (const trait_id &tid) override
Remove the given trait from this and all linked groups.
bool has_trait (const trait_id &tid) const override
Check if this group or any linked groups contain the given trait.
Public Member Functions inherited from Trait_creation_data
Trait_creation_data (int _probability)
virtual ~Trait_creation_data ()=default
Trait_creation_data (const Trait_creation_data &)=delete
Trait_creation_data & operator= (const Trait_creation_data &)=delete
trait_group::Trait_list create () const
Additional Inherited Members
Public Types inherited from Trait_group
using CreatorList = std::vector< std::unique_ptr< Trait_creation_data > >
Public Types inherited from Trait_creation_data
using RecursionList = std::vector< trait_group::Trait_group_tag >
Public Attributes inherited from Trait_creation_data
int probability
Protected Attributes inherited from Trait_group
CreatorList creators
int sum_prob
Detailed Description
A collection of traits to generate.
At creation time, each trait will be included (or not) based on its own probability roll.
Definition at line 178 of file trait_group.h.
Constructor & Destructor Documentation
Trait_group_collection()
Trait_group_collection::Trait_group_collection (int probability)
Definition at line 246 of file trait_group.cpp.
    : Trait_group( probability )
{
    if( probability <= 0 || probability > 100 ) {
        debugmsg( "Probability %d out of range", probability );
    }
}
References debugmsg, and Trait_creation_data::probability.
~Trait_group_collection()
Trait_group_collection::~Trait_group_collection () override default
Member Function Documentation
add_entry()
void Trait_group_collection::add_entry (std::unique_ptr< Trait_creation_data > ptr) override virtual
Once the relevant data has been read from JSON, this function is always called (either from mutation_branch::add_entry, add_trait_entry or add_group_entry).
Its purpose is to add a Single_trait_creator or Trait_group_creator to creators.
Implements Trait_group.
Definition at line 267 of file trait_group.cpp.
{
    assert( ptr.get() != nullptr );
    if( ptr->probability <= 0 ) {
        return;
    }
    ptr->probability = std::min( 100, ptr->probability );
    creators.push_back( std::move( ptr ) );
    ptr.release();
}
References Trait_group::creators, avatar_action::move(), and ptr().
create()
Trait_list Trait_group_collection::create (RecursionList & rec) const override virtual
Create a list of traits.
The resulting list might be empty.
Parameters
[out] rec Recursion list, output goes here
Implements Trait_creation_data.
Definition at line 254 of file trait_group.cpp.
{
    Trait_list result;
    for( const auto &creator : creators ) {
        if( rng( 0, 99 ) >= ( creator )->probability ) {
            continue;
        }
        Trait_list tmp = ( creator )->create( rec );
        result.insert( result.end(), tmp.begin(), tmp.end() );
    }
    return result;
}
References Trait_creation_data::create(), Trait_group::creators, Trait_creation_data::probability, and rng().
The documentation for this class was generated from the following files:
src/trait_group.h
src/trait_group.cpp