Cataclysm BN: trading_window Class Reference
trading_window Class Reference
#include <npctrade.h>
Public Member Functions
trading_window ()=default
void setup_trade (int cost, npc &np)
bool perform_trade (npc &np, const std::string &deal)
void update_npc_owed (npc &np)
Public Attributes
std::vector< item_pricing > theirs
std::vector< item_pricing > yours
int your_balance = 0
Private Member Functions
void setup_win (ui_adaptor &ui)
void update_win (npc &np, const std::string &deal)
void show_item_data (size_t offset, std::vector< item_pricing > &target_list)
int get_var_trade (const item &it, int total_count, int amount_hint)
bool npc_will_accept_trade (const npc &np) const
int calc_npc_owes_you (const npc &np) const
Private Attributes
catacurses::window w_head
catacurses::window w_them
catacurses::window w_you
size_t entries_per_page = 0
bool focus_them = true
size_t them_off = 0
size_t you_off = 0
inventory temp
units::volume volume_left
units::mass weight_left
Detailed Description
Definition at line 54 of file npctrade.h.
Constructor & Destructor Documentation
trading_window()
trading_window::trading_window () default
Member Function Documentation
calc_npc_owes_you()
int trading_window::calc_npc_owes_you (const npc & np) const private
Definition at line 669 of file npctrade.cpp.
{
    // Friends don't hold debts against friends.
    if( np.will_exchange_items_freely() ) {
        return 0;
    }
    // If they're going to owe you more than before, and it's more than they're willing
    // to owe, then cap the amount owed at the present level or their willingness to owe
    // (whichever is bigger).
    //
    // When could they owe you more than max_willing_to_owe? It could be from quest rewards,
    // when they were less angry, or from when you were better friends.
    if( your_balance > np.op_of_u.owed && your_balance > np.max_willing_to_owe() ) {
        return std::max( np.op_of_u.owed, np.max_willing_to_owe() );
    }
    // Fair's fair. NPC will remember this debt (or credit they've extended)
    return your_balance;
}
References npc::max_willing_to_owe(), npc::op_of_u, npc_opinion::owed, npc::will_exchange_items_freely(), and your_balance.
Referenced by perform_trade(), and update_npc_owed().
get_var_trade()
int trading_window::get_var_trade (const item & it, int total_count, int amount_hint) private
Definition at line 474 of file npctrade.cpp.
{
    string_input_popup popup_input;
    int how_many = total_count;
    const bool contained = it.is_container() && !it.contents.empty();
    const std::string title = contained ?
                              string_format( _( "Trade how many containers with %s [MAX: %d]: " ),
                                      it.get_contained().type_name( how_many ), total_count ) :
                              string_format( _( "Trade how many %s [MAX: %d]: " ), it.type_name( how_many ), total_count );
    if( amount_hint > 0 ) {
        popup_input.description( string_format(
                                     _( "Hint: You can buy up to %d with your current balance." ),
                                     std::min( amount_hint, total_count ) ) );
    } else if( amount_hint < 0 ) {
        popup_input.description( string_format(
                                     _( "Hint: You'll need to offer %d to even out the deal." ),
                                     -amount_hint ) );
    }
    popup_input.title( title ).edit( how_many );
    if( popup_input.canceled() || how_many <= 0 ) {
        return -1;
    }
    return std::min( total_count, how_many );
}
References _, string_input_popup::canceled(), item::contents, string_input_popup::description(), string_input_popup::edit(), item_contents::empty(), item::get_contained(), item::is_container(), string_format(), string_input_popup::title(), PATH_INFO::title(), and item::type_name().
Referenced by perform_trade().
npc_will_accept_trade()
bool trading_window::npc_will_accept_trade (const npc & np) const private
Definition at line 748 of file npctrade.cpp.
{
    return np.will_exchange_items_freely() || your_balance + np.max_credit_extended() > 0;
}
References npc::max_credit_extended(), npc::will_exchange_items_freely(), and your_balance.
Referenced by perform_trade(), and update_win().
perform_trade()
bool trading_window::perform_trade (npc & np, const std::string & deal)
Definition at line 500 of file npctrade.cpp.
{
    volume_left = np.volume_capacity() - np.volume_carried();
    weight_left = np.weight_capacity() - np.weight_carried();
    // Shopkeeps are happy to have large inventories.
    if( np.mission == NPC_MISSION_SHOPKEEP ) {
        volume_left = 5000_liter;
        weight_left = 5000_kilogram;
    }
    input_context ctxt( "NPC_TRADE" );
    ctxt.register_action( "SWITCH_LISTS" );
    ctxt.register_action( "PAGE_UP" );
    ctxt.register_action( "PAGE_DOWN" );
    ctxt.register_action( "EXAMINE" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ctxt.register_action( "ANY_INPUT" );
    ui_adaptor ui;
    ui.on_screen_resize( [this]( ui_adaptor & ui ) {
        setup_win( ui );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        update_win( np, deal );
    } );
    bool confirm = false;
    bool exit = false;
    while( !exit ) {
        ui_manager::redraw();
        std::vector<item_pricing> &target_list = focus_them ? theirs : yours;
        size_t &offset = focus_them ? them_off : you_off;
        const std::string action = ctxt.handle_input();
        if( action == "SWITCH_LISTS" ) {
            focus_them = !focus_them;
        } else if( action == "PAGE_UP" ) {
            if( offset > entries_per_page ) {
                offset -= entries_per_page;
            } else {
                offset = 0;
            }
        } else if( action == "PAGE_DOWN" ) {
            if( offset + entries_per_page < target_list.size() ) {
                offset += entries_per_page;
            }
        } else if( action == "EXAMINE" ) {
            show_item_data( offset, target_list );
        } else if( action == "CONFIRM" ) {
            if( !npc_will_accept_trade( np ) ) {
                if( np.max_credit_extended() == 0 ) {
                    popup( _( "You'll need to offer me more than that." ) );
                } else {
                    popup(
                        _( "Sorry, I'm only willing to extend you %s in credit." ),
                        format_money( np.max_credit_extended() )
                    );
                }
            } else if( volume_left < 0_ml || weight_left < 0_gram ) {
                // Make sure NPC doesn't go over allowed volume
                popup( _( "%s can't carry all that." ), np.name );
            } else if( calc_npc_owes_you( np ) < your_balance ) {
                // NPC is happy with the trade, but isn't willing to remember the whole debt.
                const bool trade_ok = query_yn(
                                          _( "I'm never going to be able to pay you back for all that.  The most I'm willing to owe you is %s.\n\nContinue with trade?" ),
                                          format_money( np.max_willing_to_owe() )
                                      );
                if( trade_ok ) {
                    exit = true;
                    confirm = true;
                }
            } else {
                if( query_yn( _( "Looks like a deal!  Accept this trade?" ) ) ) {
                    exit = true;
                    confirm = true;
                }
            }
        } else if( action == "QUIT" ) {
            exit = true;
            confirm = false;
        } else if( action == "ANY_INPUT" ) {
            const input_event evt = ctxt.get_raw_input();
            if( evt.type != CATA_INPUT_KEYBOARD || evt.sequence.empty() ) {
                continue;
            }
            size_t ch = evt.get_first_input();
            // Letters & such
            if( ch >= 'a' && ch <= 'z' ) {
                ch -= 'a';
            } else if( ch >= 'A' && ch <= 'Z' ) {
                ch = ch - 'A' + ( 'z' - 'a' ) + 1;
            } else {
                continue;
            }
            ch += offset;
            if( ch < target_list.size() ) {
                item_pricing &ip = target_list[ch];
                int change_amount = 1;
                int &owner_sells = focus_them ? ip.u_has : ip.npc_has;
                int &owner_sells_charge = focus_them ? ip.u_charges : ip.npc_charges;
                const auto calc_amount_hint = [&]() -> int {
                    if( ip.price > 0 )
                    {
                        if( focus_them && your_balance > 0 ) {
                            return your_balance / ip.price;
                        } else if( !focus_them && your_balance < 0 ) {
                            int amt = your_balance / ip.price;
                            int rem = ( your_balance % ip.price ) == 0 ? 0 : 1;
                            return amt - rem;
                        }
                    }
                    return 0;
                };
                if( ip.selected ) {
                    if( owner_sells_charge > 0 ) {
                        change_amount = owner_sells_charge;
                        owner_sells_charge = 0;
                    } else if( owner_sells > 0 ) {
                        change_amount = owner_sells;
                        owner_sells = 0;
                    }
                } else if( ip.charges > 0 ) {
                    int hint = calc_amount_hint();
                    change_amount = get_var_trade( *ip.loc.get_item(), ip.charges, hint );
                    if( change_amount < 1 ) {
                        continue;
                    }
                    owner_sells_charge = change_amount;
                } else {
                    if( ip.count > 1 ) {
                        int hint = calc_amount_hint();
                        change_amount = get_var_trade( *ip.loc.get_item(), ip.count, hint );
                        if( change_amount < 1 ) {
                            continue;
                        }
                    }
                    owner_sells = change_amount;
                }
                ip.selected = !ip.selected;
                if( ip.selected != focus_them ) {
                    change_amount *= -1;
                }
                int delta_price = ip.price * change_amount;
                if( !np.will_exchange_items_freely() ) {
                    your_balance -= delta_price;
                }
                if( ip.loc.where() == item_location::type::character ) {
                    volume_left += ip.vol * change_amount;
                    weight_left += ip.weight * change_amount;
                }
            }
        }
    }
    return confirm;
}
References _, action, calc_npc_owes_you(), CATA_INPUT_KEYBOARD, item_location::character, item_pricing::charges, item_pricing::count, entries_per_page, focus_them, format_money(), input_event::get_first_input(), item_location::get_item(), input_context::get_raw_input(), get_var_trade(), input_context::handle_input(), item_pricing::loc, npc::max_credit_extended(), npc::max_willing_to_owe(), npc::mission, Character::name, item_pricing::npc_charges, item_pricing::npc_has, NPC_MISSION_SHOPKEEP, npc_will_accept_trade(), popup(), item_pricing::price, query_yn(), ui_manager::redraw(), input_context::register_action(), item_pricing::selected, input_event::sequence, setup_win(), show_item_data(), theirs, them_off, input_event::type, item_pricing::u_charges, item_pricing::u_has, update_win(), item_pricing::vol, Character::volume_capacity(), Character::volume_carried(), volume_left, item_pricing::weight, Character::weight_capacity(), Character::weight_carried(), weight_left, item_location::where(), npc::will_exchange_items_freely(), you_off, your_balance, and yours.
Referenced by npc_trading::trade().
setup_trade()
void trading_window::setup_trade (int cost, npc & np)
Definition at line 250 of file npctrade.cpp.
{
    // Populate the list of what the NPC is willing to buy, and the prices they pay
    // Note that the NPC's barter skill is factored into these prices.
    // TODO: Recalc item values every time a new item is selected
    // Trading is not linear - starving NPC may pay $100 for 3 jerky, but not $100000 for 300 jerky
    theirs = npc_trading::init_buying( g->u, np, true );
    yours = npc_trading::init_buying( np, g->u, false );
    if( np.will_exchange_items_freely() ) {
        your_balance = 0;
    } else {
        your_balance = np.op_of_u.owed - cost;
    }
}
References g, npc_trading::init_buying(), npc::op_of_u, npc_opinion::owed, theirs, npc::will_exchange_items_freely(), your_balance, and yours.
Referenced by npc_trading::trade().
setup_win()
void trading_window::setup_win (ui_adaptor & ui) private
Definition at line 239 of file npctrade.cpp.
{
    const int win_they_w = TERMX / 2;
    entries_per_page = std::min( TERMY - 7, 2 + ( 'z' - 'a' ) + ( 'Z' - 'A' ) );
    w_head = catacurses::newwin( 4, TERMX, point_zero );
    w_them = catacurses::newwin( TERMY - 4, win_they_w, point( 0, 4 ) );
    w_you = catacurses::newwin( TERMY - 4, TERMX - win_they_w, point( win_they_w, 4 ) );
    ui.position( point_zero, point( TERMX, TERMY ) );
}
References entries_per_page, catacurses::newwin(), point_zero, TERMX, TERMY, w_head, w_them, and w_you.
Referenced by perform_trade().
show_item_data()
void trading_window::show_item_data (size_t offset, std::vector< item_pricing > & target_list) private
Definition at line 407 of file npctrade.cpp.
{
    catacurses::window w_tmp;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        w_tmp = catacurses::newwin( 3, 21,
                                    point( 30 + ( TERMX - FULL_SCREEN_WIDTH ) / 2,
                                           1 + ( TERMY - FULL_SCREEN_HEIGHT ) / 2 ) );
        ui.position_from_window( w_tmp );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_tmp );
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        mvwprintz( w_tmp, point( 1, 1 ), c_red, _( "Examine which item?" ) );
        draw_border( w_tmp );
        wnoutrefresh( w_tmp );
    } );
    input_context ctxt( "NPC_TRADE" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "ANY_INPUT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    bool exit = false;
    while( !exit ) {
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "QUIT" ) {
            exit = true;
        } else if( action == "ANY_INPUT" ) {
            const input_event evt = ctxt.get_raw_input();
            if( evt.type != CATA_INPUT_KEYBOARD || evt.sequence.empty() ) {
                continue;
            }
            size_t help = evt.get_first_input();
            if( help >= 'a' && help <= 'z' ) {
                help -= 'a';
            } else if( help >= 'A' && help <= 'Z' ) {
                help = help - 'A' + 26;
            } else {
                continue;
            }
            help += offset;
            if( help < target_list.size() ) {
                std::vector<iteminfo> info;
                const item &itm = *target_list[help].loc.get_item();
                itm.info( true, info );
                item_info_data data( itm.tname(),
                                     itm.type_name(),
                                     info, {} );
                data.handle_scrolling = true;
                data.any_input = false;
                draw_item_info( []() -> catacurses::window {
                    const int width = std::min( TERMX, FULL_SCREEN_WIDTH );
                    const int height = std::min( TERMY, FULL_SCREEN_HEIGHT );
                    return catacurses::newwin( height, width, point( ( TERMX - width ) / 2, ( TERMY - height ) / 2 ) );
                }, data );
                exit = true;
            }
        }
    }
}
References _, action, item_info_data::any_input, c_red, CATA_INPUT_KEYBOARD, draw_border(), draw_item_info(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_event::get_first_input(), input_context::get_raw_input(), input_context::handle_input(), item_info_data::handle_scrolling, PATH_INFO::help(), item::info(), mvwprintz(), catacurses::newwin(), ui_manager::redraw(), input_context::register_action(), input_event::sequence, TERMX, TERMY, item::tname(), input_event::type, item::type_name(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by perform_trade().
update_npc_owed()
void trading_window::update_npc_owed (npc & np)
Definition at line 690 of file npctrade.cpp.
{
    np.op_of_u.owed = calc_npc_owes_you( np );
}
References calc_npc_owes_you(), npc::op_of_u, and npc_opinion::owed.
Referenced by npc_trading::trade().
update_win()
void trading_window::update_win (npc & np, const std::string & deal) private
Definition at line 266 of file npctrade.cpp.
{
    // Draw borders, one of which is highlighted
    werase( w_them );
    werase( w_you );
    std::set<item *> without;
    std::vector<item *> added;
    for( item_pricing &pricing : yours ) {
        if( pricing.selected ) {
            added.push_back( pricing.loc.get_item() );
        }
    }
    for( item_pricing &pricing : theirs ) {
        if( pricing.selected ) {
            without.insert( pricing.loc.get_item() );
        }
    }
    bool npc_out_of_space = volume_left < 0_ml || weight_left < 0_gram;
    // Colors for hinting if the trade will be accepted or not.
    const nc_color trade_color       = npc_will_accept_trade( np ) ? c_green : c_red;
    const nc_color trade_color_light = npc_will_accept_trade( np ) ? c_light_green : c_light_red;
    input_context ctxt( "NPC_TRADE" );
    werase( w_head );
    fold_and_print( w_head, point_zero, getmaxx( w_head ), c_white,
                    _( "Trading with %s.\n"
                       "[<color_yellow>%s</color>] to switch lists, letters to pick items, "
                       "[<color_yellow>%s</color>] and [<color_yellow>%s</color>] to switch pages, "
                       "[<color_yellow>%s</color>] to finalize, [<color_yellow>%s</color>] to quit, "
                       "[<color_yellow>%s</color>] to get information on an item." ),
                    np.disp_name(),
                    ctxt.get_desc( "SWITCH_LISTS" ),
                    ctxt.get_desc( "PAGE_UP" ),
                    ctxt.get_desc( "PAGE_DOWN" ),
                    ctxt.get_desc( "CONFIRM" ),
                    ctxt.get_desc( "QUIT" ),
                    ctxt.get_desc( "EXAMINE" ) );
    // Set up line drawings
    for( int i = 0; i < TERMX; i++ ) {
        mvwputch( w_head, point( i, 3 ), c_white, LINE_OXOX );
    }
    // End of line drawings
    mvwprintz( w_head, point( 2, 3 ),  npc_out_of_space ?  c_red : c_green,
               _( "Volume: %s %s, Weight: %.1f %s" ),
               format_volume( volume_left ), volume_units_abbr(),
               convert_weight( weight_left ), weight_units() );
    std::string cost_str = _( "Exchange" );
    if( !np.will_exchange_items_freely() ) {
        cost_str = string_format( your_balance >= 0 ? _( "Credit %s" ) : _( "Debt %s" ),
                                  format_money( std::abs( your_balance ) ) );
    }
    mvwprintz( w_head, point( TERMX / 2 + ( TERMX / 2 - utf8_width( cost_str ) ) / 2, 3 ),
               trade_color, cost_str );
    if( !deal.empty() ) {
        mvwprintz( w_head, point( ( TERMX - utf8_width( deal ) ) / 2, 3 ),
                   trade_color_light, deal );
    }
    draw_border( w_them, ( focus_them ? c_yellow : BORDER_COLOR ) );
    draw_border( w_you, ( !focus_them ? c_yellow : BORDER_COLOR ) );
    mvwprintz( w_them, point( 2, 0 ), trade_color, np.name );
    mvwprintz( w_you,  point( 2, 0 ), trade_color, _( "You" ) );
    // Draw lists of items, starting from offset
    for( size_t whose = 0; whose <= 1; whose++ ) {
        const bool they = whose == 0;
        const std::vector<item_pricing> &list = they ? theirs : yours;
        const size_t &offset = they ? them_off : you_off;
        const player &person = they ? static_cast<player &>( np ) :
                               static_cast<player &>( g->u );
        catacurses::window &w_whose = they ? w_them : w_you;
        int win_w = getmaxx( w_whose );
        // Borders
        win_w -= 2;
        for( size_t i = offset; i < list.size() && i < entries_per_page + offset; i++ ) {
            const item_pricing &ip = list[i];
            const item *it = ip.loc.get_item();
            auto color = it == &person.weapon ? c_yellow : c_light_gray;
            const int &owner_sells = they ? ip.u_has : ip.npc_has;
            const int &owner_sells_charge = they ? ip.u_charges : ip.npc_charges;
            std::string itname = it->display_name();
            if( np.will_exchange_items_freely() && ip.loc.where() != item_location::type::character ) {
                itname = itname + " (" + ip.loc.describe( &g->u ) + ")";
                color = c_light_blue;
            }
            if( ip.charges > 0 && owner_sells_charge > 0 ) {
                itname += string_format( _( ": trading %d" ), owner_sells_charge );
            } else {
                if( ip.count > 1 ) {
                    itname += string_format( _( " (%d)" ), ip.count );
                }
                if( owner_sells ) {
                    itname += string_format( _( ": trading %d" ), owner_sells );
                }
            }
            if( ip.selected ) {
                color = c_white;
            }
            int keychar = i - offset + 'a';
            if( keychar > 'z' ) {
                keychar = keychar - 'z' - 1 + 'A';
            }
            trim_and_print( w_whose, point( 1, i - offset + 1 ), win_w, color, "%c %c %s",
                            static_cast<char>( keychar ), ip.selected ? '+' : '-', itname );
#if defined(__ANDROID__)
            ctxt.register_manual_key( keychar, itname );
#endif
            std::string price_str = format_money( ip.price );
            nc_color price_color = np.will_exchange_items_freely() ? c_dark_gray : ( ip.selected ? c_white :
                                   c_light_gray );
            mvwprintz( w_whose, point( win_w - utf8_width( price_str ), i - offset + 1 ),
                       price_color, price_str );
        }
        if( offset > 0 ) {
            mvwprintw( w_whose, point( 1, entries_per_page + 2 ), _( "< Back" ) );
        }
        if( offset + entries_per_page < list.size() ) {
            mvwprintw( w_whose, point( 9, entries_per_page + 2 ), _( "More >" ) );
        }
    }
    wnoutrefresh( w_head );
    wnoutrefresh( w_them );
    wnoutrefresh( w_you );
}
References _, BORDER_COLOR, c_dark_gray, c_green, c_light_blue, c_light_gray, c_light_green, c_light_red, c_red, c_white, c_yellow, item_location::character, item_pricing::charges, color(), convert_weight(), item_pricing::count, item_location::describe(), Character::disp_name(), item::display_name(), draw_border(), entries_per_page, focus_them, fold_and_print(), format_money(), format_volume(), g, input_context::get_desc(), item_location::get_item(), catacurses::getmaxx(), LINE_OXOX, item_pricing::loc, catacurses::mvwprintw(), mvwprintz(), mvwputch(), Character::name, item_pricing::npc_charges, item_pricing::npc_has, npc_will_accept_trade(), point_zero, item_pricing::price, item_pricing::selected, string_format(), TERMX, theirs, them_off, trim_and_print(), item_pricing::u_charges, item_pricing::u_has, utf8_width(), volume_left, volume_units_abbr(), w_head, w_them, w_you, Character::weapon, weight_left, weight_units(), catacurses::werase(), item_location::where(), npc::will_exchange_items_freely(), catacurses::wnoutrefresh(), you_off, your_balance, and yours.
Referenced by perform_trade().
Member Data Documentation
entries_per_page
size_t trading_window::entries_per_page = 0 private
Definition at line 74 of file npctrade.h.
Referenced by perform_trade(), setup_win(), and update_win().
focus_them
bool trading_window::focus_them = true private
Definition at line 75 of file npctrade.h.
Referenced by perform_trade(), and update_win().
temp
inventory trading_window::temp private
Definition at line 78 of file npctrade.h.
theirs
std::vector<item_pricing> trading_window::theirs
Definition at line 58 of file npctrade.h.
Referenced by perform_trade(), setup_trade(), npc_trading::trade(), and update_win().
them_off
size_t trading_window::them_off = 0 private
Definition at line 76 of file npctrade.h.
Referenced by perform_trade(), and update_win().
volume_left
units::volume trading_window::volume_left private
Definition at line 79 of file npctrade.h.
Referenced by perform_trade(), and update_win().
w_head
catacurses::window trading_window::w_head private
Definition at line 71 of file npctrade.h.
Referenced by setup_win(), and update_win().
w_them
catacurses::window trading_window::w_them private
Definition at line 72 of file npctrade.h.
Referenced by setup_win(), and update_win().
w_you
catacurses::window trading_window::w_you private
Definition at line 73 of file npctrade.h.
Referenced by setup_win(), and update_win().
weight_left
units::mass trading_window::weight_left private
Definition at line 80 of file npctrade.h.
Referenced by perform_trade(), and update_win().
you_off
size_t trading_window::you_off = 0 private
Definition at line 76 of file npctrade.h.
Referenced by perform_trade(), and update_win().
your_balance
int trading_window::your_balance = 0
Definition at line 60 of file npctrade.h.
Referenced by calc_npc_owes_you(), npc_will_accept_trade(), perform_trade(), setup_trade(), and update_win().
yours
std::vector<item_pricing> trading_window::yours
Definition at line 59 of file npctrade.h.
Referenced by perform_trade(), setup_trade(), npc_trading::trade(), and update_win().
The documentation for this class was generated from the following files:
src/npctrade.h
src/npctrade.cpp