Cataclysm BN: detail::local_translation_cache< std::string > Class Reference
detail::local_translation_cache< std::string > Class Reference
#include <translations.h>
Public Member Functions
const std::string & operator() (const std::string &arg)
Private Attributes
int cached_lang_version = INVALID_LANGUAGE_VERSION
std::string cached_arg
std::string cached_translation
Detailed Description
Definition at line 62 of file translations.h.
Member Function Documentation
operator()()
const std::string & detail::local_translation_cache< std::string >::operator() (const std::string & arg) inline
Definition at line 69 of file translations.h.
{
            if( cached_lang_version != get_current_language_version() || cached_arg != arg ) {
                cached_lang_version = get_current_language_version();
                cached_arg = arg;
                cached_translation = _translate_internal( arg );
            }
            return cached_translation;
        }
References detail::_translate_internal(), arg(), and detail::get_current_language_version().
Member Data Documentation
cached_arg
std::string detail::local_translation_cache< std::string >::cached_arg private
Definition at line 66 of file translations.h.
cached_lang_version
int detail::local_translation_cache< std::string >::cached_lang_version = INVALID_LANGUAGE_VERSION private
Definition at line 65 of file translations.h.
cached_translation
std::string detail::local_translation_cache< std::string >::cached_translation private
Definition at line 67 of file translations.h.
The documentation for this class was generated from the following file:
src/translations.h