Cataclysm BN: monster Class Reference
monster Class Reference
#include <monster.h>
Public Member Functions
monster ()
monster (const mtype_id &id)
monster (const mtype_id &id, const tripoint &pos)
monster (const monster &)
monster (monster &&)
~monster () override
monster & operator= (const monster &)
monster & operator= (monster &&)
bool is_monster () const override
monster * as_monster () override
const monster * as_monster () const override
void poly (const mtype_id &id)
bool can_upgrade () const
void hasten_upgrade ()
int get_upgrade_time () const
void allow_upgrade ()
void try_upgrade (bool pin_time)
void try_reproduce ()
void refill_udders ()
void spawn (const tripoint &p)
m_size get_size () const override
units::mass get_weight () const override
units::mass weight_capacity () const override
units::volume get_volume () const
int get_hp (const bodypart_id &) const override
int get_hp () const override
int get_hp_max (const bodypart_id &) const override
int get_hp_max () const override
int hp_percentage () const override
Returns overall % of HP remaining.
float get_mountable_weight_ratio () const
std::string get_name () const override
std::string name (unsigned int quantity=1) const
std::string name_with_armor () const
std::string disp_name (bool possessive=false, bool capitalize_first=false) const override
std::string skin_name () const override
void get_HP_Bar (nc_color &color, std::string &text) const
std::pair< std::string, nc_color > get_attitude () const
int print_info (const catacurses::window &w, int vStart, int vLines, int column) const override
Write information about this creature.
nc_color basic_symbol_color () const override
nc_color symbol_color () const override
const std::string & symbol () const override
bool is_symbol_highlighted () const override
nc_color color_with_effects () const
std::string extended_description () const override
bool has_flag (m_flag f) const override
bool can_see () const
bool can_hear () const
bool can_submerge () const
bool can_drown () const
bool can_climb () const
bool digging () const override
bool can_dig () const
bool digs () const
bool flies () const
bool climbs () const
bool swims () const
bool can_act () const
int sight_range (int light_level) const override
How far the creature sees under the given light.
bool made_of (const material_id &m) const override
bool made_of_any (const std::set< material_id > &ms) const override
bool made_of (phase_id p) const
bool avoid_trap (const tripoint &pos, const trap &tr) const override
Called when a creature triggers a trap, returns true if they don't set it off.
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
tripoint move_target ()
Creature * attack_target ()
void shift (const point &sm_shift)
void set_goal (const tripoint &p)
bool wander ()
bool can_move_to (const tripoint &p) const
Checks whether we can move to/through p.
bool can_reach_to (const tripoint &p) const
bool will_move_to (const tripoint &p) const
bool can_squeeze_to (const tripoint &p) const
bool will_reach (const point &p)
int turns_to_reach (const point &p)
void set_dest (const tripoint &p)
void unset_dest ()
void wander_to (const tripoint &p, int f)
Set p as wander destination.
float rate_target (Creature &c, float best, bool smart=false) const
void plan ()
void move ()
void footsteps (const tripoint &p)
void shove_vehicle (const tripoint &remote_destination, const tripoint &nearby_destination)
bool is_aquatic_danger (const tripoint &at_pos)
Returns true if the given square presents a possibility of drowning for the monster: it's deep water, it's liquid, the monster can drown, and there is no boardable vehicle part present.
bool die_if_drowning (const tripoint &at_pos, int chance=1)
tripoint scent_move ()
int calc_movecost (const tripoint &f, const tripoint &t) const
int calc_climb_cost (const tripoint &f, const tripoint &t) const
bool is_immune_field (const field_type_id &fid) const override
Returns true if we are immune to the field type with the given fid.
bool move_to (const tripoint &p, bool force=false, bool step_on_critter=false, float stagger_adjustment=1.0)
Attempt to move to p.
bool attack_at (const tripoint &p)
Attack any enemies at the given location.
bool bash_at (const tripoint &p)
Try to smash/bash/destroy your way through the terrain at p.
bool push_to (const tripoint &p, int boost, size_t depth)
Try to push away whatever occupies p, then step in.
int bash_skill ()
Returns innate monster bash skill, without calculating additional from helpers.
int bash_estimate ()
int group_bash_skill (const tripoint &target)
Returns ability of monster and any cooperative helpers to bash the designated target.
void stumble ()
Stumble in a random direction, but with some caveats.
void knock_back_to (const tripoint &to) override
Knocks the creature to a specified tile.
bool is_fleeing (player &u) const
monster_attitude attitude (const Character *u=nullptr) const
Attitude attitude_to (const Creature &other) const override
Attitude (of this creature) towards another creature.
void process_triggers ()
bool is_underwater () const override
bool is_on_ground () const override
bool is_warm () const override
bool in_species (const species_id &spec) const override
bool has_weapon () const override
bool is_dead_state () const override
bool is_elec_immune () const override
bool is_immune_effect (const efftype_id &) const override
bool is_immune_damage (damage_type) const override
void absorb_hit (const bodypart_id &bp, damage_instance &dam) override
bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &d) override
void melee_attack (Creature &target)
void melee_attack (Creature &target, float accuracy)
void melee_attack (Creature &p, bool)=delete
void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack) override
Attempts to harm a creature with a projectile.
void deal_damage_handle_type (const damage_unit &du, bodypart_id bp, int &damage, int &pain) override
void apply_damage (Creature *source, bodypart_id bp, int dam, bool bypass_med=false) override
void explode ()
void die_in_explosion (Creature *source)
int heal (int delta_hp, bool overheal=false)
Flat addition to the monsters hp.
void set_hp (int hp)
Directly set the current hp of the monster (not capped at the maximal hp).
void process_effects_internal () override
Processes monster-specific effects before calling Creature::process_effects().
bool movement_impaired ()
Returns true if the monster has its movement impaired.
bool move_effects (bool attacking) override
Processes effects which may prevent the monster from moving (bear traps, crushed, etc.).
void add_effect (const efftype_id &eff_id, const time_duration &dur, const bodypart_str_id &bp, int intensity=0, bool force=false, bool deferred=false) override
Performs any monster-specific modifications to the arguments before passing to Creature::add_effect().
void add_effect (const efftype_id &eff_id, const time_duration &dur, body_part bp=num_bp, int intensity=0, bool force=false, bool deferred=false)
std::string get_effect_status () const
Returns a std::string containing effects for descriptions.
float power_rating () const override
Returns an approximation of the creature's strength.
float speed_rating () const override
Returns an approximate number of tiles this creature can travel per turn.
int get_worn_armor_val (damage_type dt) const
int get_armor_cut (bodypart_id bp) const override
int get_armor_bash (bodypart_id bp) const override
int get_armor_bullet (bodypart_id bp) const override
int get_armor_type (damage_type dt, bodypart_id bp) const override
float get_hit_base () const override
float get_dodge_base () const override
float get_dodge () const override
float get_melee () const override
Returns melee skill level, to be used to throttle dodge practice.
float hit_roll () const override
Should always be overwritten by the appropriate player/NPC/monster version.
float dodge_roll () override
int get_grab_strength () const
monster_horde_attraction get_horde_attraction ()
void set_horde_attraction (monster_horde_attraction mha)
bool will_join_horde (int size)
float fall_damage_mod () const override
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
int impact (int force, const tripoint &pos) override
Deals falling/collision damage with terrain/creature at pos.
bool has_grab_break_tec () const override
float stability_roll () const override
void on_hit (Creature *source, bodypart_id bp_hit, dealt_projectile_attack const *proj=nullptr) override
This creature just got hit by an attack - possibly special/ranged attack - from source.
void on_damage_of_type (int amt, damage_type dt, const bodypart_id &bp) override
void reset_special (const std::string &special_name)
Resets a given special to its monster type cooldown value.
void reset_special_rng (const std::string &special_name)
Resets a given special to a value between 0 and its monster type cooldown value.
void set_special (const std::string &special_name, int time)
Sets a given special to the given value.
void disable_special (const std::string &special_name)
Sets the enabled flag for the given special to false.
int shortest_special_cooldown () const
Return the lowest cooldown for an enabled special.
void process_turn () override
Processes effects and bonuses and allocates move points based on speed.
void reset_bonuses () override
Resets the value of all bonus fields to 0, clears special effect flags.
void reset_stats () override
Resets stats, and applies effects in an idempotent manner.
void die (Creature *killer) override
Empty function.
void drop_items_on_death ()
bool make_fungus ()
Makes this monster into a fungus version Returns false if no such monster exists Returns true if monster is immune to spores, or if it has been fungalized.
void make_friendly ()
void make_ally (const monster &z)
Makes this monster an ally of the given monster.
void add_item (const item &it)
bool use_mech_power (int amt)
bool check_mech_powered () const
int mech_str_addition () const
void process_items ()
void hear_sound (const tripoint &source, int vol, int distance)
Makes monster react to heard sound.
bool is_hallucination () const override
field_type_id bloodType () const override
field_type_id gibType () const override
void add_msg_if_npc (const std::string &msg) const override
void add_msg_if_npc (const game_message_params &params, const std::string &msg) const override
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg) const override
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg) const override
units::mass get_carried_weight ()
units::volume get_carried_volume ()
void move_special_item_to_inv (cata::value_ptr< item > &it)
bool is_dead () const
void setpos (const tripoint &p) override
const tripoint & pos () const override
int posx () const override
int posy () const override
int posz () const override
item to_item () const
Convert this monster into an item (see mtype::revert_to_itype).
void init_from_item (const item &itm)
Initialize values like speed / hp from data of an item.
void on_unload ()
Do some cleanup and caching as monster is being unloaded from map.
void on_load ()
Retroactively update monster.
const pathfinding_settings & get_pathfinding_settings () const override
Returns settings for pathfinding.
std::set< tripoint > get_path_avoid () const override
Returns a set of points we do not want to path through.
void set_summon_time (const time_duration &length)
void decrement_summon_timer ()
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_player_or_npc (const std::string &, const std::string &) const
virtual void add_msg_player_or_npc (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
Public Member Functions inherited from Creature
virtual ~Creature ()
virtual std::vector< std::string > get_grammatical_genders () const
virtual bool is_player () const
virtual bool is_avatar () const
virtual bool is_npc () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual Character * as_character ()
virtual const Character * as_character () const
virtual player * as_player ()
virtual const player * as_player () const
virtual avatar * as_avatar ()
virtual const avatar * as_avatar () const
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
virtual void reset ()
Handles stat and bonus reset.
virtual void bleed () const
Adds an appropriate blood splatter.
virtual bool sees (const Creature &critter) const
The functions check whether this creature can see the target.
virtual bool sees (const tripoint &t, bool is_avatar=false, int range_mod=0) const
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
void knock_back_from (const tripoint &p)
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, const damage_instance &dam, dealt_damage_instance &dealt_dam)
virtual dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &dam)
Deals the damage via an attack.
virtual void on_dodge (Creature *source, int difficulty)
This creature just dodged an attack - possibly special/ranged attack - from source.
virtual void set_underwater (bool x)
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, body_part bp=num_bp, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp=num_bp, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp, bool REMOVED, int intensity=1, bool force=false)=delete
bool remove_effect (const efftype_id &eff_id, body_part bp=num_bp)
Removes a listed effect.
virtual bool remove_effect (const efftype_id &eff_id, const bodypart_str_id &bp)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id, const bodypart_str_id &bp) const
bool has_effect_with_flag (const std::string &flag, body_part bp=num_bp) const
Check if creature has any effect with the given flag.
const effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp)
std::vector< const effect * > get_all_effects_of_type (const efftype_id &eff_id) const
Returns pointers to all effects matching given type.
time_duration get_effect_dur (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
void process_effects ()
Processes through all the effects on the Creature.
virtual bool has_trait (const trait_id &flag) const
Returns true if the player has the entered trait, returns false for non-humans.
virtual void mod_pain (int npain)
virtual void mod_pain_noresist (int npain)
virtual void set_pain (int npain)
virtual int get_pain () const
virtual int get_perceived_pain () const
virtual std::pair< std::string, nc_color > get_pain_description () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual bool in_sleep_state () const
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_env_resist (bodypart_id bp) const
virtual int get_armor_bash_base (bodypart_id bp) const
virtual int get_armor_cut_base (bodypart_id bp) const
virtual int get_armor_bullet_base (bodypart_id bp) const
virtual int get_armor_bash_bonus () const
virtual int get_armor_cut_bonus () const
virtual int get_armor_bullet_bonus () const
virtual float get_hit () const
virtual int get_speed () const
virtual bool uncanny_dodge ()
Handles the uncanny dodge bionic and effects, returns true if the creature successfully dodges.
anatomy_id get_anatomy () const
void set_anatomy (anatomy_id anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (bool only_main=false) const
Returns body parts this creature have.
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bodypart * get_part (const bodypart_id &id)
bodypart get_part (const bodypart_id &id) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
void set_part_hp_cur (const bodypart_id &id, int set)
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void mod_part_hp_cur (const bodypart_id &id, int mod)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual void mod_stat (const std::string &stat, float modifier)
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_bash_bonus (int nbasharm)
virtual void set_armor_cut_bonus (int ncutarm)
virtual void set_armor_bullet_bonus (int nbulletarm)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
void draw (const catacurses::window &w, const point &origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
virtual void add_msg_if_player (const std::string &) const
virtual void add_msg_if_player (const game_message_params &, const std::string &) const
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
virtual void add_msg_player_or_say (const std::string &, const std::string &) const
virtual void add_msg_player_or_say (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
effects_map get_all_effects () const
body_part select_body_part (Creature *source, int hit_roll) const
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
Public Member Functions inherited from visitable< monster >
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
Traverses this object and any child items contained using a visitor pattern.
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
Lightweight version which provides only the current node.
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
item * find_parent (const item &it)
Determine the immediate parent container (if any) for an item.
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
Returns vector of parent containers (if any) starting with the innermost.
std::vector< const item * > parents (const item &it) const
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, std::function< void(int)> visitor=nullptr) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX)
Removes items contained by this instance which match the filter.
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Attributes
tripoint wander_pos
int wandf
std::vector< item > inv
std::vector< item > corpse_components
Character * mounted_player = nullptr
character_id mounted_player_id
character_id dragged_foe_id
cata::value_ptr< item > tied_item
cata::value_ptr< item > tack_item
cata::value_ptr< item > armor_item
cata::value_ptr< item > storage_item
cata::value_ptr< item > battery_item
int friendly
int anger = 0
int morale = 0
mfaction_id faction
int mission_id
const mtype * type
bool no_extra_death_drops
bool no_corpse_quiet = false
bool death_drops = true
bool made_footstep
std::string unique_name
bool hallucination
int fish_population = 1
short ignoring
cata::optional< time_point > lastseen_turn
int staircount
std::map< itype_id, int > ammo
time_point last_updated = calendar::turn_zero
Public Attributes inherited from Creature
FacingDirection facing = FD_RIGHT
return the direction the creature is facing, for sdl horizontal flip
int moves = 0
Protected Member Functions
void store (JsonOut &json) const
void load (const JsonObject &data)
void process_one_effect (effect &it, bool is_new) override
Processes monster-specific effects of an effect.
Protected Member Functions inherited from Creature
void set_killer (Creature *killer)
Creature ()
Creature (const Creature &)=default
Creature (Creature &&)=default
Creature & operator= (const Creature &)=default
Creature & operator= (Creature &&)=default
virtual void on_stat_change (const std::string &, int)
virtual void on_effect_int_change (const efftype_id &, int, const bodypart_str_id &)
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Private Member Functions
void process_trigger (mon_trigger trig, int amount)
void process_trigger (mon_trigger trig, const std::function< int()> &amount_func)
void normalize_ammo (int old_ammo)
Legacy loading logic for monsters that are packing ammo.
int next_upgrade_time ()
Normal upgrades.
player * find_dragged_foe ()
void nursebot_operate (player *dragged_foe)
Private Attributes
int hp
std::map< std::string, mon_special_attack > special_attacks
tripoint goal
tripoint position
bool dead
bool upgrades
int upgrade_time
bool reproduces
cata::optional< time_point > baby_timer
time_point udder_timer
monster_horde_attraction horde_attraction
std::vector< tripoint > path
Found path.
std::bitset< NUM_MEFF > effect_cache
cata::optional< time_duration > summon_time_limit = cata::nullopt
Friends
class editmap
Additional Inherited Members
Public Types inherited from Creature
enum Attitude : int { A_HOSTILE , A_NEUTRAL , A_FRIENDLY , A_ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Static Public Member Functions inherited from Creature
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
static void reset_hit_range ()
Static Public Attributes inherited from Creature
static const std::map< std::string, m_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit = default_dispersion_for_ecogh
Protected Attributes inherited from Creature
Creature * killer = nullptr
pimpl< effects_map > effects
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
int armor_bash_bonus = 0
int armor_cut_bonus = 0
int armor_bullet_bonus = 0
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0
int block_bonus = 0
float hit_bonus = 0.0
bool fake = false
Related Functions inherited from visitable< monster >
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
item * find_parent (const item &it)
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
std::vector< const item * > parents (const item &it) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
Detailed Description
Definition at line 84 of file monster.h.
Constructor & Destructor Documentation
monster() [1/5]
monster::monster ()
Definition at line 169 of file monster.cpp.
{
    position.x = 20;
    position.y = 10;
    position.z = -500; // Some arbitrary number that will cause debugmsgs
    unset_dest();
    wandf = 0;
    hp = 60;
    moves = 0;
    friendly = 0;
    anger = 0;
    morale = 2;
    faction = mfaction_id( 0 );
    mission_id = -1;
    no_extra_death_drops = false;
    dead = false;
    death_drops = true;
    made_footstep = false;
    hallucination = false;
    ignoring = 0;
    upgrades = false;
    upgrade_time = -1;
    last_updated = calendar::start_of_cataclysm;
    udder_timer = calendar::turn;
    horde_attraction = MHA_NULL;
    set_anatomy( anatomy_id( "default_anatomy" ) );
    set_body();
}
References anger, dead, death_drops, friendly, hallucination, horde_attraction, hp, ignoring, last_updated, made_footstep, MHA_NULL, mission_id, morale, Creature::moves, no_extra_death_drops, position, Creature::set_anatomy(), Creature::set_body(), calendar::start_of_cataclysm, calendar::turn, udder_timer, unset_dest(), upgrade_time, upgrades, wandf, tripoint::x, tripoint::y, and tripoint::z.
monster() [2/5]
monster::monster (const mtype_id & id)
Definition at line 198 of file monster.cpp.
                                     : monster()
{
    type = &id.obj();
    moves = type->speed;
    Creature::set_speed_base( type->speed );
    hp = type->hp;
    for( auto &sa : type->special_attacks ) {
        auto &entry = special_attacks[sa.first];
        entry.cooldown = rng( 0, sa.second->cooldown );
    }
    anger = type->agro;
    morale = type->morale;
    faction = type->default_faction;
    ammo = type->starting_ammo;
    upgrades = type->upgrades && ( type->half_life || type->age_grow );
    reproduces = type->reproduces && type->baby_timer && !monster::has_flag( MF_NO_BREED );
    if( monster::has_flag( MF_AQUATIC ) ) {
        fish_population = dice( 1, 20 );
    }
    if( monster::has_flag( MF_RIDEABLE_MECH ) ) {
        itype_id mech_bat = itype_id( type->mech_battery );
        int max_charge = mech_bat->magazine->capacity;
        item mech_bat_item = item( mech_bat, calendar::start_of_cataclysm );
        mech_bat_item.ammo_consume( rng( 0, max_charge ), tripoint_zero );
        battery_item = cata::make_value<item>( mech_bat_item );
    }
}
References mtype::age_grow, mtype::agro, ammo, item::ammo_consume(), anger, mtype::baby_timer, battery_item, mtype::default_faction, dice(), fish_population, mtype::half_life, has_flag(), hp, mtype::hp, itype_id, itype::magazine, mtype::mech_battery, MF_AQUATIC, MF_NO_BREED, MF_RIDEABLE_MECH, morale, mtype::morale, Creature::moves, reproduces, mtype::reproduces, rng(), Creature::set_speed_base(), special_attacks, mtype::special_attacks, mtype::speed, calendar::start_of_cataclysm, mtype::starting_ammo, tripoint_zero, type, upgrades, and mtype::upgrades.
monster() [3/5]
monster::monster (const mtype_id & id, const tripoint & pos)
Definition at line 226 of file monster.cpp.
                                                        : monster( id )
{
    position = p;
    unset_dest();
}
References position, and unset_dest().
monster() [4/5]
monster::monster (const monster &) default
monster() [5/5]
monster::monster (monster &&) default
~monster()
monster::~monster () override default
Member Function Documentation
absorb_hit()
void monster::absorb_hit (const bodypart_id & bp, damage_instance & dam) override virtual
Implements Creature.
Definition at line 1379 of file monster.cpp.
{
    for( auto &elem : dam.damage_units ) {
        add_msg( m_debug, "Dam Type: %s :: Ar Pen: %.1f :: Armor Mult: %.1f",
                 name_by_dt( elem.type ), elem.res_pen, elem.res_mult );
        elem.amount -= std::min( resistances( *this ).get_effective_resist( elem ) +
                                 get_worn_armor_val( elem.type ), elem.amount );
    }
}
References add_msg(), damage_instance::damage_units, resistances::get_effective_resist(), get_worn_armor_val(), m_debug, and name_by_dt().
Referenced by item::effective_dps().
add_effect() [1/2]
void monster::add_effect (const efftype_id & eff_id, const time_duration & dur, body_part bp = num_bp, int intensity = 0, bool force = false, bool deferred = false)
Definition at line 1839 of file monster.cpp.
{
    // Effects are not applied to specific monster body part
    Creature::add_effect( eff_id, dur, bodypart_str_id::NULL_ID(), intensity, force, deferred );
}
References Creature::add_effect(), deferred, and string_id< body_part_type >::NULL_ID().
add_effect() [2/2]
void monster::add_effect (const efftype_id & eff_id, const time_duration & dur, const bodypart_str_id & bp, int intensity = 0, bool force = false, bool deferred = false) override virtual
Performs any monster-specific modifications to the arguments before passing to Creature::add_effect().
Reimplemented from Creature.
Definition at line 1831 of file monster.cpp.
{
    // Effects are not applied to specific monster body part
    Creature::add_effect( eff_id, dur, bodypart_str_id::NULL_ID(), intensity, force, deferred );
}
References Creature::add_effect(), deferred, and string_id< body_part_type >::NULL_ID().
Referenced by monexamine::add_armor(), monexamine::add_leash(), monexamine::attach_bag_to(), monexamine::attach_or_remove_saddle(), blobify(), deal_projectile_attack(), mdeath::detonate(), iuse::directional_hologram(), game::disable_robot(), Character::dismount(), explosion_handler::emp_blast(), iuse::extinguisher(), feedpet(), activity_handlers::find_mount_do_turn(), mattack::frag(), fungal_effects::fungalize(), monexamine::give_items_to(), mattack::grab(), mattack::grab_drag(), impact(), mattack::kamikaze(), knock_back_to(), monexamine::mech_hack(), melee_attack(), monexamine::milk_source(), map::monster_in_field(), Character::mount_creature(), move_to(), mattack::nurse_check_up(), mattack::nurse_operate(), nursebot_operate(), bite_actor::on_damage(), monexamine::pay_bot(), process_turn(), push_to(), mattack::ranged_pull(), mattack::resurrect(), game::revive_corpse(), mattack::rifle(), talk_effect_fun_t::set_u_buy_monster(), monexamine::shear_animal(), activity_handlers::shear_finish(), mattack::shriek_alert(), monexamine::start_leading(), mattack::stretch_bite(), monexamine::swap(), mattack::tankgun(), mattack::thrown_by_judo(), monexamine::tie_pet(), gun_actor::try_target(), Character::uninstall_bionic(), monexamine::untie_pet(), place_monster_iuse::use(), vehicle::use_harness(), and mattack::zombie_fuse().
add_item()
void monster::add_item (const item & it)
Definition at line 2667 of file monster.cpp.
{
    inv.push_back( it );
}
References inv.
Referenced by die(), drop_or_embed_projectile(), move_special_item_to_inv(), mattack::pull_metal_weapon(), mattack::searchlight(), and stash_on_pet().
add_msg_if_npc() [1/12]
template<typename ... Args> void Creature::add_msg_if_npc (const char *const msg, Args &&... args) const inline
Definition at line 645 of file creature.h.
{
            return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
        }
add_msg_if_npc() [2/12]
virtual void Creature::add_msg_if_npc (const game_message_params & , const std::string &) const inline virtual
Reimplemented from Creature.
Definition at line 640 of file creature.h.
                                                                {}
add_msg_if_npc() [3/12]
void Creature::add_msg_if_npc (const game_message_params & params, const translation & msg) const
Definition at line 643 of file creature.cpp.
{
    return add_msg_if_npc( params, msg.translated() );
}
add_msg_if_npc() [4/12]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const char *const msg, Args &&... args) const inline
Definition at line 657 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
        }
add_msg_if_npc() [5/12]
void monster::add_msg_if_npc (const game_message_params & params, const std::string & msg) const override virtual
Reimplemented from Creature.
Definition at line 2727 of file monster.cpp.
{
    if( g->u.sees( *this ) ) {
        add_msg( params, replace_with_npc_name( msg ) );
    }
}
References add_msg(), g, and Creature::replace_with_npc_name().
add_msg_if_npc() [6/12]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const std::string & msg, Args &&... args) const inline
Definition at line 665 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
        }
add_msg_if_npc() [7/12]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const translation & msg, Args &&... args) const inline
Definition at line 673 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
        }
add_msg_if_npc() [8/12]
virtual void Creature::add_msg_if_npc (const std::string &) const inline virtual
Reimplemented from Creature.
Definition at line 639 of file creature.h.
{}
add_msg_if_npc() [9/12]
void monster::add_msg_if_npc (const std::string & msg) const override virtual
Reimplemented from Creature.
Definition at line 2712 of file monster.cpp.
{
    if( g->u.sees( *this ) ) {
        add_msg( replace_with_npc_name( msg ) );
    }
}
References add_msg(), g, and Creature::replace_with_npc_name().
add_msg_if_npc() [10/12]
template<typename ... Args> void Creature::add_msg_if_npc (const std::string & msg, Args &&... args) const inline
Definition at line 649 of file creature.h.
{
            return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
        }
add_msg_if_npc() [11/12]
void Creature::add_msg_if_npc (const translation & msg) const
Definition at line 642 of file creature.cpp.
{
    return add_msg_if_npc( msg.translated() );
}
add_msg_if_npc() [12/12]
template<typename ... Args> void Creature::add_msg_if_npc (const translation & msg, Args &&... args) const inline
Definition at line 653 of file creature.h.
{
            return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
        }
add_msg_player_or_npc() [1/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const inline
Definition at line 692 of file creature.h.
{
            return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
add_msg_player_or_npc() [2/12]
virtual void Creature::add_msg_player_or_npc (const game_message_params & , const std::string & , const std::string &) const inline virtual
Reimplemented from Creature.
Definition at line 683 of file creature.h.
                                                                       {}
add_msg_player_or_npc() [3/12]
void Creature::add_msg_player_or_npc (const game_message_params & params, const translation & pc, const translation & npc) const
Definition at line 688 of file creature.cpp.
{
    return add_msg_player_or_npc( params, pc.translated(), npc.translated() );
}
add_msg_player_or_npc() [4/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const char *const player_msg, const char *const npc_msg, Args &&... args) const inline
Definition at line 710 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
add_msg_player_or_npc() [5/12]
void monster::add_msg_player_or_npc (const game_message_params & params, const std::string & player_msg, const std::string & npc_msg) const override virtual
Reimplemented from Creature.
Definition at line 2734 of file monster.cpp.
{
    if( g->u.sees( *this ) ) {
        add_msg( params, replace_with_npc_name( npc_msg ) );
    }
}
References add_msg(), g, and Creature::replace_with_npc_name().
add_msg_player_or_npc() [6/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const std::string & player_msg, const std::string & npc_msg, Args &&... args) const inline
Definition at line 719 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
add_msg_player_or_npc() [7/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const translation & player_msg, const translation & npc_msg, Args &&... args) const inline
Definition at line 728 of file creature.h.
{
            if( params.type == m_debug && !debug_mode ) {
                return;
            }
            return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
add_msg_player_or_npc() [8/12]
virtual void Creature::add_msg_player_or_npc (const std::string & , const std::string &) const inline virtual
Reimplemented from Creature.
Definition at line 681 of file creature.h.
                                                                       {}
add_msg_player_or_npc() [9/12]
void monster::add_msg_player_or_npc (const std::string & player_msg, const std::string & npc_msg) const override virtual
Reimplemented from Creature.
Definition at line 2719 of file monster.cpp.
{
    if( g->u.sees( *this ) ) {
        add_msg( replace_with_npc_name( npc_msg ) );
    }
}
References add_msg(), g, and Creature::replace_with_npc_name().
add_msg_player_or_npc() [10/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (const std::string & player_msg, const std::string & npc_msg, Args &&... args) const inline
Definition at line 698 of file creature.h.
{
            return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
add_msg_player_or_npc() [11/12]
void Creature::add_msg_player_or_npc (const translation & pc, const translation & npc) const
Definition at line 686 of file creature.cpp.
{
    return add_msg_player_or_npc( pc.translated(), npc.translated() );
}
add_msg_player_or_npc() [12/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (const translation & player_msg, const translation & npc_msg, Args &&... args) const inline
Definition at line 704 of file creature.h.
{
            return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                          string_format( npc_msg, std::forward<Args>( args )... ) );
        }
allow_upgrade()
void monster::allow_upgrade ()
Definition at line 305 of file monster.cpp.
{
    upgrade_time = 0;
}
References upgrade_time.
Referenced by mattack::evolve_kill_strike().
apply_damage()
void monster::apply_damage (Creature * source, bodypart_id bp, int dam, bool bypass_med = false) override virtual
Implements Creature.
Definition at line 1660 of file monster.cpp.
{
    if( is_dead_state() ) {
        return;
    }
    hp -= dam;
    if( hp < 1 ) {
        set_killer( source );
    } else if( dam > 0 ) {
        process_trigger( mon_trigger::HURT, 1 + static_cast<int>( dam / 3 ) );
    }
}
References hp, HURT, is_dead_state(), process_trigger(), and Creature::set_killer().
Referenced by mattack::dermatik(), map::drop_furniture(), explosion_handler::emp_blast(), iuse::extinguisher(), game::fling_creature(), game::forced_door_closing(), fungal_effects::fungalize(), impact(), monexamine::kill_zslave(), knock_back_to(), map::monster_in_field(), move_to(), process_effects_internal(), process_one_effect(), map::shake_vehicle(), and mattack::thrown_by_judo().
as_monster() [1/2]
const monster * monster::as_monster () const inline override virtual
Reimplemented from Creature.
Definition at line 103 of file monster.h.
{
            return this;
        }
as_monster() [2/2]
monster * monster::as_monster () inline override virtual
Reimplemented from Creature.
Definition at line 100 of file monster.h.
{
            return this;
        }
Referenced by emit_radio_signal().
attack_at()
bool monster::attack_at (const tripoint & p)
Attack any enemies at the given location.
Attacks only if there is a creature at the given location towards we are hostile.
Returns
true if something was attacked, false otherwise
Definition at line 1483 of file monmove.cpp.
{
    if( has_flag( MF_PACIFIST ) ) {
        return false;
    }
    if( p.z != posz() ) {
        // TODO: Remove this
        return false;
    }
    if( p == g->u.pos() ) {
        melee_attack( g->u );
        return true;
    }
    if( const auto mon_ = g->critter_at<monster>( p, is_hallucination() ) ) {
        monster &mon = *mon_;
        // Don't attack yourself.
        if( &mon == this ) {
            return false;
        }
        // With no melee dice, we can't attack, but we had to process until here
        // because hallucinations require no melee dice to destroy.
        if( type->melee_dice <= 0 ) {
            return false;
        }
        auto attitude = attitude_to( mon );
        // MF_ATTACKMON == hulk behavior, whack everything in your way
        if( attitude == A_HOSTILE || has_flag( MF_ATTACKMON ) ) {
            melee_attack( mon );
            return true;
        }
        return false;
    }
    npc *const guy = g->critter_at<npc>( p );
    if( guy && type->melee_dice > 0 ) {
        // For now we're always attacking NPCs that are getting into our
        // way. This is consistent with how it worked previously, but
        // later on not hitting allied NPCs would be cool.
        guy->on_attacked( *this ); // allow NPC hallucination to be one shot by monsters
        melee_attack( *guy );
        return true;
    }
    // Nothing to attack.
    return false;
}
References Creature::A_HOSTILE, attitude(), attitude_to(), g, has_flag(), is_hallucination(), melee_attack(), mtype::melee_dice, MF_ATTACKMON, MF_PACIFIST, npc::on_attacked(), posz(), type, and tripoint::z.
Referenced by move().
attack_target()
Creature * monster::attack_target ()
Definition at line 1013 of file monster.cpp.
{
    if( wander() ) {
        return nullptr;
    }
    Creature *target = g->critter_at( move_target() );
    if( target == nullptr || target == this ||
        attitude_to( *target ) == Creature::A_FRIENDLY || !sees( *target ) ) {
        return nullptr;
    }
    return target;
}
References Creature::A_FRIENDLY, attitude_to(), g, move_target(), Creature::sees(), and wander().
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), leap_actor::call(), mon_spellcasting_actor::call(), gun_actor::call(), mattack::chickenbot(), mattack::copbot(), mattack::dermatik(), mattack::evolve_kill_strike(), melee_actor::find_target(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::fungus_bristle(), mattack::grab(), mattack::grab_drag(), mattack::howl(), mattack::impale(), mattack::kamikaze(), mattack::longswipe(), mattack::lunge(), mattack::multi_robot(), mattack::pull_metal_weapon(), mattack::ranged_pull(), mattack::riotbot(), mattack::science(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::smash(), mattack::spit_sap(), sting_get_target(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::suicide(), mattack::tazer(), mattack::tentacle(), mattack::thrown_by_judo(), and mattack::tindalos_teleport().
attitude()
monster_attitude monster::attitude (const Character * u = nullptr) const
Definition at line 1086 of file monster.cpp.
{
    if( friendly != 0 ) {
        if( has_effect( effect_docile ) ) {
            return MATT_FPASSIVE;
        }
        if( u == &g->u ) {
            return MATT_FRIEND;
        }
        // Zombies don't understand not attacking NPCs, but dogs and bots should.
        const npc *np = dynamic_cast< const npc * >( u );
        if( np != nullptr && np->get_attitude() != NPCATT_KILL && !type->in_species( ZOMBIE ) ) {
            return MATT_FRIEND;
        }
        if( np != nullptr && np->is_hallucination() ) {
            return MATT_IGNORE;
        }
    }
    if( effect_cache[FLEEING] ) {
        return MATT_FLEE;
    }
    if( has_effect( effect_pacified ) ) {
        return MATT_ZLAVE;
    }
    int effective_anger  = anger;
    int effective_morale = morale;
    if( u != nullptr ) {
        // Those are checked quite often, so avoiding string construction is a good idea
        static const string_id<monfaction> faction_bee( "bee" );
        if( faction == faction_bee ) {
            if( u->has_trait( trait_BEE ) ) {
                return MATT_FRIEND;
            } else if( u->has_trait( trait_FLOWERS ) ) {
                effective_anger -= 10;
            }
        }
        if( type->in_species( FUNGUS ) && ( u->has_trait( trait_THRESH_MYCUS ) ||
                                            u->has_trait( trait_MYCUS_FRIEND ) ) ) {
            return MATT_FRIEND;
        }
        if( effective_anger >= 10 &&
            ( ( type->in_species( MAMMAL ) && u->has_trait( trait_PHEROMONE_MAMMAL ) ) ||
              ( type->in_species( INSECT ) && u->has_trait( trait_PHEROMONE_INSECT ) ) ) ) {
            effective_anger -= 20;
        }
        if( u->has_trait( trait_TERRIFYING ) ) {
            effective_morale -= 10;
        }
        if( has_flag( MF_ANIMAL ) ) {
            if( u->has_trait( trait_ANIMALEMPATH ) ) {
                effective_anger -= 10;
                if( effective_anger < 10 ) {
                    effective_morale += 55;
                }
            } else if( u->has_trait( trait_ANIMALEMPATH2 ) ) {
                effective_anger -= 20;
                if( effective_anger < 20 ) {
                    effective_morale += 80;
                }
            } else if( u->has_trait( trait_ANIMALDISCORD ) ) {
                if( effective_anger >= 10 ) {
                    effective_anger += 10;
                }
                if( effective_anger < 10 ) {
                    effective_morale -= 5;
                }
            } else if( u->has_trait( trait_ANIMALDISCORD2 ) ) {
                if( effective_anger >= 20 ) {
                    effective_anger += 20;
                }
                if( effective_anger < 20 ) {
                    effective_morale -= 5;
                }
            }
        }
        for( const trait_id &mut : u->get_mutations() ) {
            for( const std::pair<const species_id, int> &elem : mut.obj().anger_relations ) {
                if( type->in_species( elem.first ) ) {
                    effective_anger += elem.second;
                }
            }
        }
        for( const trait_id &mut : u->get_mutations() ) {
            for( const species_id &spe : mut.obj().ignored_by ) {
                if( type->in_species( spe ) ) {
                    return MATT_IGNORE;
                }
            }
        }
    }
    if( effective_morale < 0 ) {
        if( effective_morale + effective_anger > 0 && get_hp() > get_hp_max() / 3 ) {
            return MATT_FOLLOW;
        }
        return MATT_FLEE;
    }
    if( effective_anger <= 0 ) {
        if( get_hp() <= 0.6 * get_hp_max() ) {
            return MATT_FLEE;
        } else {
            return MATT_IGNORE;
        }
    }
    if( effective_anger < 10 ) {
        return MATT_FOLLOW;
    }
    return MATT_ATTACK;
}
References anger, effect_cache, effect_docile, effect_pacified, FLEEING, friendly, FUNGUS, g, npc::get_attitude(), get_hp(), get_hp_max(), Character::get_mutations(), Creature::has_effect(), has_flag(), Character::has_trait(), mtype::in_species(), INSECT, npc::is_hallucination(), MAMMAL, MATT_ATTACK, MATT_FLEE, MATT_FOLLOW, MATT_FPASSIVE, MATT_FRIEND, MATT_IGNORE, MATT_ZLAVE, MF_ANIMAL, morale, NPCATT_KILL, string_id< T >::obj(), trait_ANIMALDISCORD, trait_ANIMALDISCORD2, trait_ANIMALEMPATH, trait_ANIMALEMPATH2, trait_BEE, trait_FLOWERS, trait_MYCUS_FRIEND, trait_PHEROMONE_INSECT, trait_PHEROMONE_MAMMAL, trait_TERRIFYING, trait_THRESH_MYCUS, type, and ZOMBIE.
Referenced by attack_at(), attitude_to(), npc::attitude_to(), get_attitude(), is_fleeing(), game::mon_info_update(), move(), move_to(), plan(), will_move_to(), and will_reach().
attitude_to()
Creature::Attitude monster::attitude_to (const Creature & other) const override virtual
Attitude (of this creature) towards another creature.
This might not be symmetric.
Implements Creature.
Definition at line 1040 of file monster.cpp.
{
    const monster *m = other.is_monster() ? static_cast< const monster *>( &other ) : nullptr;
    const player *p = other.as_player();
    if( m != nullptr ) {
        if( m == this ) {
            return A_FRIENDLY;
        }
        auto faction_att = faction.obj().attitude( m->faction );
        if( ( friendly != 0 && m->friendly != 0 ) ||
            ( friendly == 0 && m->friendly == 0 && faction_att == MFA_FRIENDLY ) ) {
            // Friendly (to player) monsters are friendly to each other
            // Unfriendly monsters go by faction attitude
            return A_FRIENDLY;
        } else if( ( friendly == 0 && m->friendly == 0 && faction_att == MFA_HATE ) ) {
            // Stuff that hates a specific faction will always attack that faction
            return A_HOSTILE;
        } else if( ( friendly == 0 && m->friendly == 0 && faction_att == MFA_NEUTRAL ) ||
                   morale < 0 || anger < 10 ) {
            // Stuff that won't attack is neutral to everything
            return A_NEUTRAL;
        } else {
            return A_HOSTILE;
        }
    } else if( p != nullptr ) {
        switch( attitude( const_cast<player *>( p ) ) ) {
            case MATT_FRIEND:
            case MATT_ZLAVE:
                return A_FRIENDLY;
            case MATT_FPASSIVE:
            case MATT_FLEE:
            case MATT_IGNORE:
            case MATT_FOLLOW:
                return A_NEUTRAL;
            case MATT_ATTACK:
                return A_HOSTILE;
            case MATT_NULL:
            case NUM_MONSTER_ATTITUDES:
                break;
        }
    }
    // Should not happen!, creature should be either player or monster
    return A_NEUTRAL;
}
References Creature::A_FRIENDLY, Creature::A_HOSTILE, Creature::A_NEUTRAL, anger, attitude(), faction, friendly, MATT_ATTACK, MATT_FLEE, MATT_FOLLOW, MATT_FPASSIVE, MATT_FRIEND, MATT_IGNORE, MATT_NULL, MATT_ZLAVE, MFA_FRIENDLY, MFA_HATE, MFA_NEUTRAL, morale, NUM_MONSTER_ATTITUDES, and other.
Referenced by attack_at(), attack_target(), bash_at(), mattack::chickenbot(), game::examine(), mattack::grenadier(), mattack::grenadier_elite(), mattack::growplants(), game::mon_info_update(), move(), mattack::multi_robot(), mattack::nurse_assist(), mattack::nurse_operate(), plan(), rate_target(), mattack::resurrect(), mattack::upgrade(), and mattack::vine().
avoid_trap()
bool monster::avoid_trap (const tripoint & pos, const trap & tr) const override virtual
Called when a creature triggers a trap, returns true if they don't set it off.
Parameters
tr is the trap that was triggered.
pos is the location of the trap (not necessarily of the creature) in the main map.
Implements Creature.
Definition at line 878 of file monster.cpp.
{
    // The trap position is not used, monsters are to stupid to remember traps. Actually, they do
    // not even see them.
    // Traps are on the ground, digging monsters go below, fliers and climbers go above.
    if( digging() || flies() ) {
        return true;
    }
    return dice( 3, type->sk_dodge + 1 ) >= dice( 3, tr.get_avoidance() );
}
References dice(), digging(), flies(), trap::get_avoidance(), mtype::sk_dodge, and type.
bash_at()
bool monster::bash_at (const tripoint & p)
Try to smash/bash/destroy your way through the terrain at p.
Returns
true if we destroyed something, false otherwise.
Definition at line 1382 of file monmove.cpp.
{
    if( p.z != posz() ) {
        // TODO: Remove this
        return false;
    }
    //Hallucinations can't bash stuff.
    if( is_hallucination() ) {
        return false;
    }
    // Don't bash if a friendly monster is standing there
    monster *target = g->critter_at<monster>( p );
    if( target != nullptr && attitude_to( *target ) == A_FRIENDLY ) {
        return false;
    }
    bool try_bash = !can_move_to( p ) || one_in( 3 );
    if( !try_bash ) {
        return false;
    }
    bool can_bash = g->m.is_bashable( p ) && bash_skill() > 0;
    if( !can_bash ) {
        return false;
    }
    bool flat_ground = g->m.has_flag( "ROAD", p ) || g->m.has_flag( "FLAT", p );
    if( flat_ground && !g->m.is_bashable_furn( p ) ) {
        bool can_bash_ter = g->m.is_bashable_ter( p );
        bool try_bash_ter = one_in( 50 );
        if( !( can_bash_ter && try_bash_ter ) ) {
            return false;
        }
    }
    int bashskill = group_bash_skill( p );
    g->m.bash( p, bashskill );
    moves -= 100;
    return true;
}
References Creature::A_FRIENDLY, attitude_to(), bash_skill(), can_move_to(), g, group_bash_skill(), is_hallucination(), Creature::moves, one_in(), posz(), and tripoint::z.
Referenced by move().
bash_estimate()
int monster::bash_estimate ()
Definition at line 1425 of file monmove.cpp.
{
    int estimate = bash_skill();
    if( has_flag( MF_GROUP_BASH ) ) {
        // Right now just give them a boost so they try to bash a lot of stuff.
        // TODO: base it on number of nearby friendlies.
        estimate *= 2;
    }
    return estimate;
}
References bash_skill(), has_flag(), and MF_GROUP_BASH.
Referenced by move(), and scent_move().
bash_skill()
int monster::bash_skill ()
Returns innate monster bash skill, without calculating additional from helpers.
Definition at line 1436 of file monmove.cpp.
{
    return type->bash_skill;
}
References mtype::bash_skill, and type.
Referenced by bash_at(), bash_estimate(), group_bash_skill(), move(), and scent_move().
basic_symbol_color()
nc_color monster::basic_symbol_color () const override virtual
Implements Creature.
Definition at line 846 of file monster.cpp.
{
    return type->color;
}
References mtype::color, and type.
Referenced by print_info().
block_hit()
bool monster::block_hit (Creature * source, bodypart_id & bp_hit, damage_instance & d) override virtual
Implements Creature.
Definition at line 1374 of file monster.cpp.
{
    return false;
}
bloodType()
field_type_id monster::bloodType () const override virtual
Implements Creature.
Definition at line 2677 of file monster.cpp.
{
    if( is_hallucination() ) {
        return fd_null;
    }
    return type->bloodType();
}
References mtype::bloodType(), fd_null, is_hallucination(), and type.
Referenced by mattack::dogthing(), scatter_chunks(), and mdeath::splatter().
calc_climb_cost()
int monster::calc_climb_cost (const tripoint & f, const tripoint & t) const
Definition at line 1336 of file monmove.cpp.
{
    if( flies() ) {
        return 100;
    }
    if( climbs() && !g->m.has_flag( TFLAG_NO_FLOOR, t ) ) {
        const int diff = g->m.climb_difficulty( f );
        if( diff <= 10 ) {
            return 150;
        }
    }
    return 0;
}
References climbs(), flies(), g, and TFLAG_NO_FLOOR.
Referenced by move_to().
calc_movecost()
int monster::calc_movecost (const tripoint & f, const tripoint & t) const
Definition at line 1283 of file monmove.cpp.
{
    int movecost = 0;
    const int source_cost = g->m.move_cost( f );
    const int dest_cost = g->m.move_cost( t );
    // Digging and flying monsters ignore terrain cost
    if( flies() || ( digging() && g->m.has_flag( "DIGGABLE", t ) ) ) {
        movecost = 100;
        // Swimming monsters move super fast in water
    } else if( swims() ) {
        if( g->m.has_flag( "SWIMMABLE", f ) ) {
            movecost += 25;
        } else {
            movecost += 50 * g->m.move_cost( f );
        }
        if( g->m.has_flag( "SWIMMABLE", t ) ) {
            movecost += 25;
        } else {
            movecost += 50 * g->m.move_cost( t );
        }
    } else if( can_submerge() ) {
        // No-breathe monsters have to walk underwater slowly
        if( g->m.has_flag( "SWIMMABLE", f ) ) {
            movecost += 250;
        } else {
            movecost += 50 * g->m.move_cost( f );
        }
        if( g->m.has_flag( "SWIMMABLE", t ) ) {
            movecost += 250;
        } else {
            movecost += 50 * g->m.move_cost( t );
        }
        movecost /= 2;
    } else if( climbs() ) {
        if( g->m.has_flag( "CLIMBABLE", f ) ) {
            movecost += 150;
        } else {
            movecost += 50 * g->m.move_cost( f );
        }
        if( g->m.has_flag( "CLIMBABLE", t ) ) {
            movecost += 150;
        } else {
            movecost += 50 * g->m.move_cost( t );
        }
        movecost /= 2;
    } else {
        movecost = ( ( 50 * source_cost ) + ( 50 * dest_cost ) ) / 2.0;
    }
    return movecost;
}
References can_submerge(), climbs(), digging(), flies(), g, and swims().
Referenced by move_to(), and turns_to_reach().
can_act()
bool monster::can_act () const
Definition at line 951 of file monster.cpp.
{
    return moves > 0 &&
           ( effects->empty() ||
             ( !has_effect( effect_stunned ) && !has_effect( effect_downed ) && !has_effect( effect_webbed ) ) );
}
References effect_downed, effect_stunned, effect_webbed, Creature::effects, Creature::has_effect(), and Creature::moves.
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), leap_actor::call(), mon_spellcasting_actor::call(), mattack::dermatik(), mattack::evolve_kill_strike(), melee_actor::find_target(), mattack::flesh_golem(), mattack::grab(), mattack::grab_drag(), grenade_helper(), mattack::impale(), mattack::lunge(), mattack::science(), mattack::shockstorm(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::smash(), mattack::spit_sap(), mattack::stretch_attack(), and mattack::stretch_bite().
can_climb()
bool monster::can_climb () const
Definition at line 916 of file monster.cpp.
{
    return climbs() || flies();
}
References climbs(), and flies().
Referenced by move(), and will_move_to().
can_dig()
bool monster::can_dig () const
Definition at line 926 of file monster.cpp.
{
    return has_flag( MF_CAN_DIG );
}
References has_flag(), and MF_CAN_DIG.
Referenced by digging(), extended_description(), and move_to().
can_drown()
bool monster::can_drown () const
Definition at line 910 of file monster.cpp.
{
    return !swims() && !has_flag( MF_AQUATIC ) &&
           !has_flag( MF_NO_BREATHE ) && !flies();
}
References flies(), has_flag(), MF_AQUATIC, MF_NO_BREATHE, and swims().
Referenced by is_aquatic_danger().
can_hear()
bool monster::can_hear () const
Definition at line 899 of file monster.cpp.
{
    return has_flag( MF_HEARS ) && !has_effect( effect_deaf );
}
References effect_deaf, Creature::has_effect(), has_flag(), and MF_HEARS.
Referenced by hear_sound(), and will_reach().
can_move_to()
bool monster::can_move_to (const tripoint & p) const
Checks whether we can move to/through p.
This does not account for bashing.
This is used in pathfinding and ONLY checks the terrain. It ignores players and monsters, which might only block this tile temporarily. will_move_to() checks for impassable terrain etc can_reach_to() checks for z-level difference. can_move_to() is a wrapper for both of them. can_squeeze_to() checks for vehicle holes.
Definition at line 258 of file monmove.cpp.
{
    return can_reach_to( p ) && will_move_to( p );
}
References can_reach_to(), and will_move_to().
Referenced by bash_at(), mattack::grab_drag(), move(), move_to(), push_to(), scent_move(), map::spawn_monsters_submap(), stumble(), and game::update_stair_monsters().
can_reach_to()
bool monster::can_reach_to (const tripoint & p) const
Definition at line 230 of file monmove.cpp.
{
    map &here = get_map();
    if( p.z > pos().z && z_is_valid( pos().z ) ) {
        if( here.has_flag( TFLAG_RAMP_UP, tripoint( p.xy(), p.z - 1 ) ) ) {
            return true;
        }
        if( !here.has_flag( TFLAG_GOES_UP, pos() ) && !here.has_flag( TFLAG_NO_FLOOR, p ) ) {
            // can't go through the roof
            return false;
        }
    } else if( p.z < pos().z && z_is_valid( pos().z ) ) {
        if( !here.has_flag( TFLAG_GOES_DOWN, pos() ) ) {
            // can't go through the floor
            // you would fall anyway if there was no floor, so no need to check for that here
            return false;
        }
    }
    return true;
}
References get_map(), map::has_flag(), pos(), TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_NO_FLOOR, TFLAG_RAMP_UP, tripoint::xy(), tripoint::z, and z_is_valid().
Referenced by can_move_to().
can_see()
bool monster::can_see () const
Definition at line 894 of file monster.cpp.
{
    return has_flag( MF_SEES ) && !effect_cache[VISION_IMPAIRED];
}
References effect_cache, has_flag(), MF_SEES, and VISION_IMPAIRED.
Referenced by sight_range(), and will_reach().
can_squeeze_to()
bool monster::can_squeeze_to (const tripoint & p) const
Definition at line 251 of file monmove.cpp.
{
    map &m = get_map();
    return !m.obstructed_by_vehicle_rotation( pos(), p );
}
References get_map(), map::obstructed_by_vehicle_rotation(), and pos().
Referenced by is_adjacent(), melee_attack(), move(), and move_to().
can_submerge()
bool monster::can_submerge () const
Definition at line 904 of file monster.cpp.
{
    return ( has_flag( MF_NO_BREATHE ) || swims() || has_flag( MF_AQUATIC ) ) &&
           !has_flag( MF_ELECTRONIC );
}
References has_flag(), MF_AQUATIC, MF_ELECTRONIC, MF_NO_BREATHE, and swims().
Referenced by calc_movecost(), is_underwater(), move_to(), and will_move_to().
can_upgrade()
bool monster::can_upgrade () const
Definition at line 280 of file monster.cpp.
{
    return upgrades && get_option<float>( "MONSTER_UPGRADE_FACTOR" ) > 0.0;
}
References upgrades.
Referenced by extended_description(), hasten_upgrade(), and try_upgrade().
check_mech_powered()
bool monster::check_mech_powered () const
Definition at line 2407 of file monster.cpp.
{
    if( is_hallucination() || !has_flag( MF_RIDEABLE_MECH ) || !battery_item ) {
        return false;
    }
    if( battery_item->ammo_remaining() <= 0 ) {
        return false;
    }
    const itype &type = *battery_item->type;
    if( battery_item->ammo_remaining() <= type.magazine->capacity / 10 && one_in( 10 ) ) {
        add_msg( m_bad, _( "Your %s emits a beeping noise as its batteries start to get low." ),
                 get_name() );
    }
    return true;
}
References _, add_msg(), battery_item, get_name(), has_flag(), is_hallucination(), m_bad, MF_RIDEABLE_MECH, one_in(), and type.
Referenced by avatar_action::plthrow().
climbs()
bool monster::climbs () const
Definition at line 941 of file monster.cpp.
{
    return has_flag( MF_CLIMBS );
}
References has_flag(), and MF_CLIMBS.
Referenced by calc_climb_cost(), calc_movecost(), can_climb(), extended_description(), and move_to().
color_with_effects()
nc_color monster::color_with_effects () const
Definition at line 861 of file monster.cpp.
{
    nc_color ret = type->color;
    if( has_effect( effect_beartrap ) || has_effect( effect_stunned ) || has_effect( effect_downed ) ||
        has_effect( effect_tied ) ||
        has_effect( effect_lightsnare ) || has_effect( effect_heavysnare ) ) {
        ret = hilite( ret );
    }
    if( has_effect( effect_pacified ) ) {
        ret = invert_color( ret );
    }
    if( has_effect( effect_onfire ) ) {
        ret = red_background( ret );
    }
    return ret;
}
References mtype::color, effect_beartrap, effect_downed, effect_heavysnare, effect_lightsnare, effect_onfire, effect_pacified, effect_stunned, effect_tied, Creature::has_effect(), hilite(), invert_color(), red_background(), cata::hash64_detail::ret, and type.
Referenced by symbol_color().
deal_damage_handle_type()
void monster::deal_damage_handle_type (const damage_unit & du, bodypart_id bp, int & damage, int & pain) override virtual
Reimplemented from Creature.
Definition at line 1596 of file monster.cpp.
{
    switch( du.type ) {
        case DT_ELECTRIC:
            if( has_flag( MF_ELECTRIC ) ) {
                return; // immunity
            }
            break;
        case DT_COLD:
            if( has_flag( MF_COLDPROOF ) ) {
                return; // immunity
            }
            break;
        case DT_BASH:
            if( has_flag( MF_PLASTIC ) ) {
                damage += du.amount / rng( 2, 4 ); // lessened effect
                pain += du.amount / 4;
                return;
            }
            break;
        case DT_NULL:
            debugmsg( "monster::deal_damage_handle_type: illegal damage type DT_NULL" );
            break;
        case DT_ACID:
            if( has_flag( MF_ACIDPROOF ) ) {
                // immunity
                return;
            }
        case DT_TRUE:
        // typeless damage, should always go through
        case DT_BIOLOGICAL:
        // internal damage, like from smoke or poison
        case DT_CUT:
        case DT_STAB:
        case DT_BULLET:
        case DT_HEAT:
        default:
            break;
    }
    Creature::deal_damage_handle_type( du,  bp, damage, pain );
}
References damage_unit::amount, Creature::deal_damage_handle_type(), debugmsg, DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_NULL, DT_STAB, DT_TRUE, has_flag(), MF_ACIDPROOF, MF_COLDPROOF, MF_ELECTRIC, MF_PLASTIC, Creature::pain, rng(), and damage_unit::type.
Referenced by item::effective_dps().
deal_projectile_attack()
void monster::deal_projectile_attack (Creature * source, dealt_projectile_attack & attack) override virtual
Attempts to harm a creature with a projectile.
Parameters
source Pointer to the creature who shot the projectile.
attack A structure describing the attack and its results.
print_messages enables message printing by default.
Reimplemented from Creature.
Definition at line 1568 of file monster.cpp.
{
    const auto &proj = attack.proj;
    double &missed_by = attack.missed_by; // We can change this here
    // Whip has a chance to scare wildlife even if it misses
    if( proj.has_effect( ammo_effect_WHIP ) && type->in_category( "WILDLIFE" ) && one_in( 3 ) ) {
        add_effect( effect_run, rng( 3_turns, 5_turns ) );
    }
    if( missed_by > 1.0 ) {
        // Total miss
        return;
    }
    // No head = immune to ranged crits
    if( missed_by < accuracy_critical && has_flag( MF_NOHEAD ) ) {
        missed_by = accuracy_critical;
    }
    Creature::deal_projectile_attack( source, attack );
    if( !is_hallucination() && attack.hit_critter == this ) {
        // Maybe TODO: Get difficulty from projectile speed/size/missed_by
        on_hit( source, bodypart_id( "torso" ), &attack );
    }
}
References accuracy_critical, add_effect(), ammo_effect_WHIP, Creature::deal_projectile_attack(), effect_run, has_flag(), dealt_projectile_attack::hit_critter, mtype::in_category(), is_hallucination(), MF_NOHEAD, dealt_projectile_attack::missed_by, on_hit(), one_in(), dealt_projectile_attack::proj, rng(), and type.
decrement_summon_timer()
void monster::decrement_summon_timer ()
Definition at line 2149 of file monster.cpp.
{
    if( !summon_time_limit ) {
        return;
    }
    if( *summon_time_limit <= 0_turns ) {
        die( nullptr );
    } else {
        *summon_time_limit -= 1_turns;
    }
}
References die(), and summon_time_limit.
Referenced by process_turn().
deserialize()
void monster::deserialize (JsonIn & jsin)
Definition at line 1768 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    load( data );
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and load().
Referenced by mongroup::deserialize_legacy(), and overmap::unserialize().
die()
void monster::die (Creature * killer) override virtual
Empty function.
Should always be overwritten by the appropriate player/NPC/monster version.
Implements Creature.
Definition at line 2267 of file monster.cpp.
{
    if( dead ) {
        // We are already dead, don't die again, note that monster::dead is
        // *only* set to true in this function!
        return;
    }
    // We were carrying a creature, deposit the rider
    if( has_effect( effect_ridden ) && mounted_player ) {
        mounted_player->forced_dismount();
    }
    g->set_critter_died();
    dead = true;
    set_killer( nkiller );
    if( !death_drops ) {
        return;
    }
    if( !no_extra_death_drops ) {
        drop_items_on_death();
    }
    // TODO: should actually be class Character
    player *ch = dynamic_cast<player *>( get_killer() );
    if( !is_hallucination() && ch != nullptr ) {
        if( ( has_flag( MF_GUILT ) && ch->is_player() ) || ( ch->has_trait( trait_PACIFIST ) &&
                has_flag( MF_HUMAN ) ) ) {
            // has guilt flag or player is pacifist && monster is humanoid
            mdeath::guilt( *this );
        }
        g->events().send<event_type::character_kills_monster>( ch->getID(), type->id );
        if( ch->is_player() && ch->has_trait( trait_KILLER ) ) {
            if( one_in( 4 ) ) {
                const translation snip = SNIPPET.random_from_category( "killer_on_kill" ).value_or( translation() );
                ch->add_msg_if_player( m_good, "%s", snip );
            }
            ch->add_morale( MORALE_KILLER_HAS_KILLED, 5, 10, 6_hours, 4_hours );
            ch->rem_morale( MORALE_KILLER_NEED_TO_KILL );
        }
    }
    // Drop items stored in optionals
    move_special_item_to_inv( tack_item );
    move_special_item_to_inv( armor_item );
    move_special_item_to_inv( storage_item );
    move_special_item_to_inv( tied_item );
    if( has_effect( effect_lightsnare ) ) {
        add_item( item( "string_36", calendar::start_of_cataclysm ) );
        add_item( item( "snare_trigger", calendar::start_of_cataclysm ) );
    }
    if( has_effect( effect_heavysnare ) ) {
        add_item( item( "rope_6", calendar::start_of_cataclysm ) );
        add_item( item( "snare_trigger", calendar::start_of_cataclysm ) );
    }
    if( has_effect( effect_beartrap ) ) {
        add_item( item( "beartrap", calendar::start_of_cataclysm ) );
    }
    if( has_effect( effect_grabbing ) ) {
        remove_effect( effect_grabbing );
        for( player *p : find_targets_to_ungrab( pos() ) ) {
            p->add_msg_player_or_npc( m_good, _( "The last enemy holding you collapses!" ),
                                      _( "The last enemy holding <npcname> collapses!" ) );
            p->remove_effect( effect_grabbed );
        }
    }
    if( !is_hallucination() ) {
        for( const auto &it : inv ) {
            g->m.add_item_or_charges( pos(), it );
        }
    }
    // If we're a queen, make nearby groups of our type start to die out
    if( !is_hallucination() && has_flag( MF_QUEEN ) ) {
        // The submap coordinates of this monster, monster groups coordinates are
        // submap coordinates.
        const tripoint abssub = ms_to_sm_copy( g->m.getabs( pos() ) );
        // Do it for overmap above/below too
        for( const tripoint &p : points_in_radius( abssub, HALF_MAPSIZE, 1 ) ) {
            // TODO: fix point types
            for( auto &mgp : overmap_buffer.groups_at( tripoint_abs_sm( p ) ) ) {
                if( MonsterGroupManager::IsMonsterInGroup( mgp->type, type->id ) ) {
                    mgp->dying = true;
                }
            }
        }
    }
    mission::on_creature_death( *this );
    // Also, perform our death function
    if( is_hallucination() || summon_time_limit ) {
        //Hallucinations always just disappear
        mdeath::disappear( *this );
        return;
    }
    //Not a hallucination, go process the death effects.
    for( const auto &deathfunction : type->dies ) {
        deathfunction( *this );
    }
    // If our species fears seeing one of our own die, process that
    int anger_adjust = 0;
    int morale_adjust = 0;
    if( type->has_anger_trigger( mon_trigger::FRIEND_DIED ) ) {
        anger_adjust += 15;
    }
    if( type->has_fear_trigger( mon_trigger::FRIEND_DIED ) ) {
        morale_adjust -= 15;
    }
    if( type->has_placate_trigger( mon_trigger::FRIEND_DIED ) ) {
        anger_adjust -= 15;
    }
    if( anger_adjust != 0 || morale_adjust != 0 ) {
        int light = g->light_level( posz() );
        for( monster &critter : g->all_monsters() ) {
            if( !critter.type->same_species( *type ) ) {
                continue;
            }
            if( g->m.sees( critter.pos(), pos(), light ) ) {
                critter.morale += morale_adjust;
                critter.anger += anger_adjust;
            }
        }
    }
}
References _, add_item(), Character::add_morale(), player::add_msg_if_player(), armor_item, character_kills_monster, dead, death_drops, mtype::dies, mdeath::disappear(), drop_items_on_death(), effect_beartrap, effect_grabbed, effect_grabbing, effect_heavysnare, effect_lightsnare, effect_ridden, find_targets_to_ungrab(), Character::forced_dismount(), FRIEND_DIED, g, Creature::get_killer(), Character::getID(), overmapbuffer::groups_at(), mdeath::guilt(), HALF_MAPSIZE, mtype::has_anger_trigger(), Creature::has_effect(), mtype::has_fear_trigger(), has_flag(), mtype::has_placate_trigger(), Character::has_trait(), mtype::id, inv, is_hallucination(), player::is_player(), MonsterGroupManager::IsMonsterInGroup(), light, m_good, MF_GUILT, MF_HUMAN, MF_QUEEN, MORALE_KILLER_HAS_KILLED, MORALE_KILLER_NEED_TO_KILL, mounted_player, move_special_item_to_inv(), ms_to_sm_copy(), no_extra_death_drops, mission::on_creature_death(), one_in(), overmap_buffer, points_in_radius(), pos(), posz(), snippet_library::random_from_category(), Character::rem_morale(), Creature::remove_effect(), Creature::set_killer(), SNIPPET, calendar::start_of_cataclysm, storage_item, summon_time_limit, tack_item, tied_item, trait_KILLER, trait_PACIFIST, and type.
Referenced by computer_session::action_terminate(), Creature_tracker::add(), game::catch_a_monster(), decrement_summon_timer(), die_if_drowning(), die_in_explosion(), iuse::fungicide(), mattack::kamikaze(), Creature_tracker::kill_marked_for_death(), monexamine::kill_zslave(), knock_back_to(), melee_attack(), move(), avatar_action::move(), petfood(), mattack::photograph(), push_to(), mattack::suicide(), and mattack::zombie_fuse().
die_if_drowning()
bool monster::die_if_drowning (const tripoint & at_pos, int chance = 1)
Definition at line 660 of file monmove.cpp.
{
    if( is_aquatic_danger( at_pos ) && one_in( chance ) ) {
        die( nullptr );
        if( g->u.sees( at_pos ) ) {
            add_msg( _( "The %s drowns!" ), name() );
        }
        return true;
    }
    return false;
}
References _, add_msg(), die(), g, is_aquatic_danger(), name(), and one_in().
Referenced by knock_back_to(), and move().
die_in_explosion()
void monster::die_in_explosion (Creature * source)
Definition at line 1674 of file monster.cpp.
{
    hp = -9999; // huge to trigger explosion and prevent corpse item
    die( source );
}
References die(), and hp.
Referenced by game::forced_door_closing(), and iuse::granade_act().
digging()
bool monster::digging () const override virtual
Reimplemented from Creature.
Definition at line 921 of file monster.cpp.
{
    return digs() || ( can_dig() && is_underwater() );
}
References can_dig(), digs(), and is_underwater().
Referenced by avoid_trap(), calc_movecost(), footsteps(), map::monster_in_field(), move_to(), projectile_attack(), sight_range(), and will_move_to().
digs()
bool monster::digs () const
Definition at line 931 of file monster.cpp.
{
    return has_flag( MF_DIGS );
}
References has_flag(), and MF_DIGS.
Referenced by digging(), map::monster_in_field(), move_to(), will_move_to(), and will_reach().
disable_special()
void monster::disable_special (const std::string & special_name)
Sets the enabled flag for the given special to false.
Definition at line 2096 of file monster.cpp.
{
    const auto iter = special_attacks.find( special_name );
    if( iter != special_attacks.end() ) {
        iter->second.enabled = false;
    } else {
        debugmsg( "%s has no special attack %s", disp_name().c_str(), special_name.c_str() );
    }
}
References debugmsg, disp_name(), and special_attacks.
Referenced by mattack::grenadier(), mattack::grenadier_elite(), and mattack::kamikaze().
disp_name()
std::string monster::disp_name (bool possessive = false, bool capitalize_first = false) const override virtual
Implements Creature.
Definition at line 537 of file monster.cpp.
{
    if( !possessive ) {
        return string_format( capitalize_first ? _( "The %s" ) : _( "the %s" ), name() );
    } else {
        return string_format( capitalize_first ? _( "The %s's" ) : _( "the %s's" ), name() );
    }
}
References _, name(), and string_format().
Referenced by mdefense::acidsplash(), blobify(), mon_spellcasting_actor::call(), disable_special(), drop_or_embed_projectile(), mdeath::jabberwock(), melee_attack(), on_damage_of_type(), plan(), push_to(), set_special(), map::shake_vehicle(), shove_vehicle(), Character::uninstall_bionic(), and Creature_tracker::update_pos().
dodge_roll()
float monster::dodge_roll () override virtual
Implements Creature.
Definition at line 2001 of file monster.cpp.
{
    return get_dodge() * 5;
}
References get_dodge().
Referenced by mattack::dermatik().
drop_items_on_death()
void monster::drop_items_on_death ()
Definition at line 2448 of file monster.cpp.
{
    if( is_hallucination() ) {
        return;
    }
    if( !type->death_drops ) {
        return;
    }
    std::vector<item> items = item_group::items_from( type->death_drops, calendar::start_of_cataclysm );
    // This block removes some items, according to item spawn scaling factor
    const float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
    if( spawn_rate < 1 ) {
        // Temporary vector, to remember which items will be dropped
        std::vector<item> remaining;
        for( const item &it : items ) {
            if( rng_float( 0, 1 ) < spawn_rate ) {
                remaining.push_back( it );
            }
        }
        // If there aren't any items left, there's nothing left to do
        if( remaining.empty() ) {
            return;
        }
        items = remaining;
    }
    const auto dropped = g->m.spawn_items( pos(), items );
    if( has_flag( MF_FILTHY ) && get_option<bool>( "FILTHY_CLOTHES" ) ) {
        for( const auto &it : dropped ) {
            if( ( it->is_armor() || it->is_pet_armor() ) && !it->is_gun() ) {
                // handle wearable guns as a special case
                it->set_flag( "FILTHY" );
            }
        }
    }
}
References mtype::death_drops, g, has_flag(), is_hallucination(), item_group::items_from(), MF_FILTHY, pos(), rng_float(), calendar::start_of_cataclysm, and type.
Referenced by die().
explode()
void monster::explode ()
Definition at line 2137 of file monster.cpp.
{
    // Handled in mondeath::normal
    // +1 to avoid overflow when evaluating -hp
    hp = INT_MIN + 1;
}
References hp.
extended_description()
std::string monster::extended_description () const override virtual
Implements Creature.
Definition at line 687 of file monster.cpp.
{
    std::string ss;
    const std::pair<std::string, nc_color> att = get_attitude();
    std::string att_colored = colorize( att.first, att.second );
    std::string difficulty_str;
    if( debug_mode ) {
        difficulty_str = _( "Difficulty " ) + std::to_string( type->difficulty );
    } else {
        if( type->difficulty < 3 ) {
            difficulty_str = _( "<color_light_gray>Minimal threat.</color>" );
        } else if( type->difficulty < 10 ) {
            difficulty_str = _( "<color_light_gray>Mildly dangerous.</color>" );
        } else if( type->difficulty < 20 ) {
            difficulty_str = _( "<color_light_red>Dangerous.</color>" );
        } else if( type->difficulty < 30 ) {
            difficulty_str = _( "<color_red>Very dangerous.</color>" );
        } else if( type->difficulty < 50 ) {
            difficulty_str = _( "<color_red>Extremely dangerous.</color>" );
        } else {
            difficulty_str = _( "<color_red>Fatally dangerous!</color>" );
        }
    }
    if( display_mod_source ) {
        ss += _( "Origin: " );
        ss += enumerate_as_string( type->src.begin(),
        type->src.end(), []( const std::pair<mtype_id, mod_id> &source ) {
            return string_format( "'%s'", source.second->name() );
        }, enumeration_conjunction::arrow );
    }
    ss += "\n--\n";
    ss += string_format( _( "This is a %s.  %s %s" ), name(), att_colored,
                         difficulty_str ) + "\n";
    if( !get_effect_status().empty() ) {
        ss += string_format( _( "<stat>It is %s.</stat>" ), get_effect_status() ) + "\n";
    }
    ss += "--\n";
    const std::pair<std::string, nc_color> hp_bar = hp_description( hp, type->hp );
    ss += colorize( hp_bar.first, hp_bar.second ) + "\n";
    const std::pair<std::string, nc_color> speed_desc = speed_description(
                speed_rating(),
                has_flag( MF_IMMOBILE ) );
    ss += colorize( speed_desc.first, speed_desc.second ) + "\n";
    ss += "--\n";
    ss += string_format( "<dark>%s</dark>", type->get_description() ) + "\n";
    ss += "--\n";
    ss += string_format( _( "It is %s in size." ),
                         size_names.at( get_size() ) ) + "\n";
    std::vector<std::string> types = type->species_descriptions();
    if( type->has_flag( MF_ANIMAL ) ) {
        types.emplace_back( _( "an animal" ) );
    }
    if( !types.empty() ) {
        ss += string_format( _( "It is %s." ),
                             enumerate_as_string( types ) ) + "\n";
    }
    using flag_description = std::pair<m_flag, std::string>;
    const auto describe_flags = [this, &ss](
                                    const std::string & format,
                                    const std::vector<flag_description> &flags_names,
    const std::string &if_empty = "" ) {
        std::string flag_descriptions = enumerate_as_string( flags_names.begin(),
        flags_names.end(), [this]( const flag_description & fd ) {
            return type->has_flag( fd.first ) ? fd.second : "";
        } );
        if( !flag_descriptions.empty() ) {
            ss += string_format( format, flag_descriptions ) + "\n";
        } else if( !if_empty.empty() ) {
            ss += if_empty + "\n";
        }
    };
    using property_description = std::pair<bool, std::string>;
    const auto describe_properties = [&ss](
                                         const std::string & format,
                                         const std::vector<property_description> &property_names,
    const std::string &if_empty = "" ) {
        std::string property_descriptions = enumerate_as_string( property_names.begin(),
        property_names.end(), []( const property_description & pd ) {
            return pd.first ? pd.second : "";
        } );
        if( !property_descriptions.empty() ) {
            ss += string_format( format, property_descriptions ) + "\n";
        } else if( !if_empty.empty() ) {
            ss += if_empty + "\n";
        }
    };
    describe_flags( _( "It has the following senses: %s." ), {
        {m_flag::MF_HEARS, pgettext( "Hearing as sense", "hearing" )},
        {m_flag::MF_SEES, pgettext( "Sight as sense", "sight" )},
        {m_flag::MF_SMELLS, pgettext( "Smell as sense", "smell" )},
    }, _( "It doesn't have senses." ) );
    describe_properties( _( "It can %s." ), {
        {swims(), pgettext( "Swim as an action", "swim" )},
        {flies(), pgettext( "Fly as an action", "fly" )},
        {can_dig(), pgettext( "Dig as an action", "dig" )},
        {climbs(), pgettext( "Climb as an action", "climb" )}
    } );
    describe_flags( _( "<bad>In fight it can %s.</bad>" ), {
        {m_flag::MF_GRABS, pgettext( "Grab as an action", "grab" )},
        {m_flag::MF_VENOM, pgettext( "Poison as an action", "poison" )},
        {m_flag::MF_PARALYZE, pgettext( "Paralyze as an action", "paralyze" )},
        {m_flag::MF_BLEED, _( "cause bleed" )}
    } );
    if( !type->has_flag( m_flag::MF_NOHEAD ) ) {
        ss += std::string( _( "It has a head." ) ) + "\n";
    }
    ss += "--\n";
    ss += std::string( _( "In melee, you can expect to:" ) ) + "\n";
    ss += string_format( _( "Deal average damage per second: <stat>%.1f</stat>" ),
                         g->u.weapon.effective_dps( g->u, *this ) );
    ss += "\n";
    if( debug_mode ) {
        ss += string_format( _( "Current Speed: %1$d" ), get_speed() ) + "\n";
        ss += string_format( _( "Anger: %1$d" ), anger ) + "\n";
        ss += string_format( _( "Friendly: %1$d" ), friendly ) + "\n";
        ss += string_format( _( "Morale: %1$d" ), morale ) + "\n";
        const time_duration current_time = calendar::turn - calendar::turn_zero;
        ss += string_format( _( "Current Time: Turn %1$d | Day: %2$d" ),
                             to_turns<int>( current_time ),
                             to_days<int>( current_time ) ) + "\n";
        ss += string_format( _( "Upgrade Time: %1$d (turns left: %2$d) %3$s" ),
                             upgrade_time,
                             to_turns<int>( time_duration::from_days( upgrade_time ) - current_time ),
                             can_upgrade() ? "" : _( "<color_red>(can't upgrade)</color>" ) ) + "\n";
        if( baby_timer.has_value() ) {
            ss += string_format( _( "Reproduction time: %1$d (turns left: %2$d) %3$s" ),
                                 to_turn<int>( baby_timer.value() ),
                                 to_turn<int>( baby_timer.value() - current_time ),
                                 reproduces ? "" : _( "<color_red>(cannot reproduce)</color>" ) ) + "\n";
        }
    }
    return replace_colors( ss );
}
References _, anger, arrow, baby_timer, can_dig(), can_upgrade(), climbs(), colorize(), debug_mode, mtype::difficulty, display_mod_source, enumerate_as_string(), flies(), format(), friendly, time_duration::from_days(), g, get_attitude(), mtype::get_description(), get_effect_status(), get_size(), Creature::get_speed(), has_flag(), mtype::has_flag(), hp, mtype::hp, hp_description(), MF_ANIMAL, MF_BLEED, MF_GRABS, MF_HEARS, MF_IMMOBILE, MF_NOHEAD, MF_PARALYZE, MF_SEES, MF_SMELLS, MF_VENOM, morale, name(), pgettext(), replace_colors(), reproduces, size_names, mtype::species_descriptions(), speed_description(), speed_rating(), mtype::src, string_format(), swims(), to_string(), calendar::turn, calendar::turn_zero, type, and upgrade_time.
fall_damage_mod()
float monster::fall_damage_mod () const override virtual
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
Implements Creature.
Definition at line 2011 of file monster.cpp.
{
    if( flies() ) {
        return 0.0f;
    }
    switch( type->size ) {
        case MS_TINY:
            return 0.2f;
        case MS_SMALL:
            return 0.6f;
        case MS_MEDIUM:
            return 1.0f;
        case MS_LARGE:
            return 1.4f;
        case MS_HUGE:
            return 2.0f;
        default:
            return 1.0f;
    }
    return 0.0f;
}
References flies(), MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, mtype::size, and type.
Referenced by impact().
find_dragged_foe()
player * monster::find_dragged_foe () private
Definition at line 1088 of file monmove.cpp.
{
    // Make sure they're actually dragging someone.
    if( !dragged_foe_id.is_valid() || !has_effect( effect_dragging ) ) {
        dragged_foe_id = character_id();
        return nullptr;
    }
    // Dragged critters may die or otherwise become invalid, which is why we look
    // them up each time. Luckily, monsters dragging critters is relatively rare,
    // so this check should happen infrequently.
    player *dragged_foe = g->critter_by_id<player>( dragged_foe_id );
    if( dragged_foe == nullptr ) {
        // Target no longer valid.
        dragged_foe_id = character_id();
        remove_effect( effect_dragging );
    }
    return dragged_foe;
}
References character_id, dragged_foe_id, effect_dragging, g, Creature::has_effect(), character_id::is_valid(), and Creature::remove_effect().
Referenced by move().
flies()
bool monster::flies () const
Definition at line 936 of file monster.cpp.
{
    return has_flag( MF_FLIES );
}
References has_flag(), and MF_FLIES.
Referenced by avoid_trap(), calc_climb_cost(), calc_movecost(), can_climb(), can_drown(), extended_description(), fall_damage_mod(), footsteps(), is_immune_field(), trapfunc::ledge(), map::monster_in_field(), move(), move_to(), and will_move_to().
footsteps()
void monster::footsteps (const tripoint & p)
Definition at line 1166 of file monmove.cpp.
{
    if( made_footstep ) {
        return;
    }
    made_footstep = true;
    int volume = 6; // same as player's footsteps
    if( flies() ) {
        volume = 0;    // Flying monsters don't have footsteps!
    }
    if( digging() ) {
        volume = 10;
    }
    switch( type->size ) {
        case MS_TINY:
            volume = 0; // No sound for the tinies
            break;
        case MS_SMALL:
            volume /= 3;
            break;
        case MS_MEDIUM:
            break;
        case MS_LARGE:
            volume *= 1.5;
            break;
        case MS_HUGE:
            volume *= 2;
            break;
        default:
            break;
    }
    if( has_flag( MF_LOUDMOVES ) ) {
        volume += 6;
    }
    if( volume == 0 ) {
        return;
    }
    int dist = rl_dist( p, g->u.pos() );
    sounds::add_footstep( p, volume, dist, this, type->get_footsteps() );
    return;
}
References sounds::add_footstep(), digging(), flies(), g, mtype::get_footsteps(), has_flag(), made_footstep, MF_LOUDMOVES, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, rl_dist(), mtype::size, and type.
Referenced by move_to().
get_armor_bash()
int monster::get_armor_bash (bodypart_id bp) const override virtual
Reimplemented from Creature.
Definition at line 1879 of file monster.cpp.
{
    ( void ) bp;
    return static_cast<int>( type->armor_bash ) + armor_bash_bonus + get_worn_armor_val( DT_BASH );
}
References mtype::armor_bash, Creature::armor_bash_bonus, DT_BASH, get_worn_armor_val(), and type.
Referenced by game::fling_creature(), get_armor_type(), and impact().
get_armor_bullet()
int monster::get_armor_bullet (bodypart_id bp) const override virtual
Reimplemented from Creature.
Definition at line 1885 of file monster.cpp.
{
    ( void ) bp;
    return static_cast<int>( type->armor_bullet ) + armor_bullet_bonus + get_worn_armor_val(
               DT_BULLET );
}
References mtype::armor_bullet, Creature::armor_bullet_bonus, DT_BULLET, get_worn_armor_val(), and type.
Referenced by get_armor_type().
get_armor_cut()
int monster::get_armor_cut (bodypart_id bp) const override virtual
Reimplemented from Creature.
Definition at line 1872 of file monster.cpp.
{
    ( void ) bp;
    // TODO: Add support for worn armor?
    return static_cast<int>( type->armor_cut ) + armor_cut_bonus + get_worn_armor_val( DT_CUT );
}
References mtype::armor_cut, Creature::armor_cut_bonus, DT_CUT, get_worn_armor_val(), and type.
Referenced by get_armor_type(), impact(), and move_to().
get_armor_type()
int monster::get_armor_type (damage_type dt, bodypart_id bp) const override virtual
Implements Creature.
Definition at line 1892 of file monster.cpp.
{
    int worn_armor = get_worn_armor_val( dt );
    switch( dt ) {
        case DT_TRUE:
        case DT_BIOLOGICAL:
            return 0;
        case DT_BASH:
            return get_armor_bash( bp );
        case DT_CUT:
            return get_armor_cut( bp );
        case DT_BULLET:
            return get_armor_bullet( bp );
        case DT_ACID:
            return worn_armor + static_cast<int>( type->armor_acid );
        case DT_STAB:
            return worn_armor + static_cast<int>( type->armor_stab ) + armor_cut_bonus * 0.8f;
        case DT_HEAT:
            return worn_armor + static_cast<int>( type->armor_fire );
        case DT_COLD:
        case DT_ELECTRIC:
            return worn_armor;
        case DT_NULL:
        case NUM_DT:
            // Let it error below
            break;
    }
    debugmsg( "Invalid damage type: %d", dt );
    return 0;
}
References mtype::armor_acid, Creature::armor_cut_bonus, mtype::armor_fire, mtype::armor_stab, debugmsg, DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_NULL, DT_STAB, DT_TRUE, get_armor_bash(), get_armor_bullet(), get_armor_cut(), get_worn_armor_val(), NUM_DT, and type.
Referenced by map::monster_in_field(), and process_one_effect().
get_attitude()
std::pair< std::string, nc_color > monster::get_attitude () const
Definition at line 556 of file monster.cpp.
{
    const auto att = attitude_names.at( attitude( &g->u ) );
    return {
        _( att.first ),
        all_colors.get( att.second )
    };
}
References _, all_colors, attitude(), attitude_names, and g.
Referenced by extended_description(), and print_info().
get_carried_volume()
units::volume monster::get_carried_volume ()
Definition at line 2760 of file monster.cpp.
{
    units::volume total_volume = 0_ml;
    for( const item &it : inv ) {
        total_volume += it.volume();
    }
    return total_volume;
}
References inv.
Referenced by monexamine::give_items_to(), and stash_on_pet().
get_carried_weight()
units::mass monster::get_carried_weight ()
Definition at line 2742 of file monster.cpp.
{
    units::mass total_weight = 0_gram;
    if( tack_item ) {
        total_weight += tack_item->weight();
    }
    if( storage_item ) {
        total_weight += storage_item->weight();
    }
    if( armor_item ) {
        total_weight += armor_item->weight();
    }
    for( const item &it : inv ) {
        total_weight += it.weight();
    }
    return total_weight;
}
References armor_item, inv, storage_item, and tack_item.
Referenced by monexamine::add_armor(), monexamine::give_items_to(), and stash_on_pet().
get_dodge()
float monster::get_dodge () const override virtual
Reimplemented from Creature.
Definition at line 1977 of file monster.cpp.
{
    if( has_effect( effect_downed ) ) {
        return 0.0f;
    }
    float ret = Creature::get_dodge();
    if( has_effect( effect_lightsnare ) || has_effect( effect_heavysnare ) ||
        has_effect( effect_beartrap ) || has_effect( effect_tied ) ) {
        ret /= 2;
    }
    if( has_effect( effect_bouldering ) ) {
        ret /= 4;
    }
    return ret;
}
References effect_beartrap, effect_bouldering, effect_downed, effect_heavysnare, effect_lightsnare, effect_tied, Creature::get_dodge(), Creature::has_effect(), and cata::hash64_detail::ret.
Referenced by dodge_roll(), item::effective_dps(), and trapfunc::tripwire().
get_dodge_base()
float monster::get_dodge_base () const override virtual
Implements Creature.
Definition at line 1930 of file monster.cpp.
{
    return type->sk_dodge;
}
References mtype::sk_dodge, and type.
get_effect_status()
std::string monster::get_effect_status () const
Returns a std::string containing effects for descriptions.
Definition at line 1847 of file monster.cpp.
{
    std::vector<std::string> effect_status;
    for( auto &elem : *effects ) {
        for( auto &_it : elem.second ) {
            if( !_it.second.is_removed() && elem.first->is_show_in_info() ) {
                effect_status.push_back( _it.second.disp_name() );
            }
        }
    }
    return enumerate_as_string( effect_status );
}
References Creature::effects, and enumerate_as_string().
Referenced by extended_description(), and print_info().
get_grab_strength()
int monster::get_grab_strength () const
Definition at line 2006 of file monster.cpp.
{
    return type->grab_strength;
}
References mtype::grab_strength, and type.
Referenced by mattack::grab(), Character::hardcoded_effects(), and try_remove_grab().
get_hit_base()
float monster::get_hit_base () const override virtual
Implements Creature.
Definition at line 1925 of file monster.cpp.
{
    return type->melee_skill;
}
References mtype::melee_skill, and type.
get_horde_attraction()
monster_horde_attraction monster::get_horde_attraction ()
Definition at line 2969 of file monster.cpp.
{
    if( horde_attraction == MHA_NULL ) {
        horde_attraction = static_cast<monster_horde_attraction>( rng( 1, 5 ) );
    }
    return horde_attraction;
}
References horde_attraction, MHA_NULL, and rng().
Referenced by will_join_horde().
get_hp() [1/2]
int monster::get_hp () const override virtual
Reimplemented from Creature.
Definition at line 2917 of file monster.cpp.
{
    return hp;
}
References hp.
Referenced by attitude(), and hp_percentage().
get_hp() [2/2]
int monster::get_hp (const bodypart_id &) const override virtual
Reimplemented from Creature.
Definition at line 2912 of file monster.cpp.
{
    return hp;
}
References hp.
Referenced by mattack::absorb_meat(), iuse::artifact(), mdeath::broken(), spell_effect::charm_monster(), mattack::chickenbot(), mattack::copbot(), mattack::dermatik(), mattack::formblob(), mattack::generator(), iuse::granade_act(), mdeath::guilt(), Creature_tracker::kill_marked_for_death(), mattack::multi_robot(), mdeath::normal(), iuse::pheromone(), game::revive_corpse(), mattack::riotbot(), mattack::searchlight(), mdeath::splatter(), and mattack::zombie_fuse().
get_HP_Bar()
void monster::get_HP_Bar (nc_color & color, std::string & text) const
Definition at line 551 of file monster.cpp.
{
    std::tie( text, color ) = ::get_hp_bar( hp, type->hp, true );
}
References color(), get_hp_bar(), hp, mtype::hp, and type.
get_hp_max() [1/2]
int monster::get_hp_max () const override virtual
Reimplemented from Creature.
Definition at line 2907 of file monster.cpp.
{
    return type->hp;
}
References mtype::hp, and type.
Referenced by attitude(), hp_percentage(), and on_damage_of_type().
get_hp_max() [2/2]
int monster::get_hp_max (const bodypart_id &) const override virtual
Reimplemented from Creature.
Definition at line 2902 of file monster.cpp.
{
    return type->hp;
}
References mtype::hp, and type.
Referenced by mattack::absorb_meat(), mdeath::broken(), mattack::chickenbot(), mattack::copbot(), mattack::dermatik(), mattack::formblob(), mattack::generator(), iuse::granade_act(), map_funcs::migo_nerve_cage_removal(), mattack::mon_leech_evolution(), mattack::multi_robot(), mdeath::normal(), mattack::riotbot(), mattack::searchlight(), mdeath::splatter(), and mattack::zombie_fuse().
get_melee()
float monster::get_melee () const override virtual
Returns melee skill level, to be used to throttle dodge practice.
Implements Creature.
Definition at line 1996 of file monster.cpp.
{
    return type->melee_skill;
}
References mtype::melee_skill, and type.
get_mountable_weight_ratio()
float monster::get_mountable_weight_ratio () const
Definition at line 2922 of file monster.cpp.
{
    return type->mountable_weight_ratio;
}
References mtype::mountable_weight_ratio, and type.
Referenced by Character::can_mount(), vehicle::part_vpower_w(), and monexamine::pet_menu().
get_name()
std::string monster::get_name () const override virtual
Implements Creature.
Definition at line 488 of file monster.cpp.
{
    return name( 1 );
}
References name().
Referenced by monexamine::add_armor(), monexamine::add_leash(), monexamine::attach_bag_to(), check_mech_powered(), mattack::check_money_left(), spellcasting_callback::draw_spell_info(), monexamine::dump_items(), game::examine(), feedpet(), liquid_handler::get_liquid_target(), monexamine::give_items_to(), game::grabbed_veh_move(), monexamine::insert_battery(), trapfunc::lava(), monexamine::mech_hack(), melee_attack(), monexamine::mfriend_menu(), activity_handlers::milk_finish(), monexamine::milk_source(), Character::mount_creature(), monexamine::pay_bot(), monexamine::pet_menu(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), monexamine::play_with(), avatar_action::plthrow(), monexamine::push(), refill_udders(), monexamine::remove_armor(), monexamine::remove_bag_from(), monexamine::remove_harness(), monexamine::remove_leash(), set_profession(), setpos(), monexamine::shear_animal(), trapfunc::sinkhole(), monexamine::start_leading(), monexamine::stop_leading(), monexamine::swap(), vehicle::thrust(), monexamine::tie_pet(), trapfunc::tripwire(), monexamine::untie_pet(), vehicle::use_harness(), and game::vertical_move().
get_path_avoid()
std::set< tripoint > monster::get_path_avoid () const override virtual
Returns a set of points we do not want to path through.
Implements Creature.
Definition at line 3044 of file monster.cpp.
{
    return std::set<tripoint>();
}
Referenced by move().
get_pathfinding_settings()
const pathfinding_settings & monster::get_pathfinding_settings () const override virtual
Returns settings for pathfinding.
Implements Creature.
Definition at line 3039 of file monster.cpp.
{
    return type->path_settings;
}
References mtype::path_settings, and type.
Referenced by move(), turns_to_reach(), and will_reach().
get_size()
m_size monster::get_size () const override virtual
Implements Creature.
Definition at line 2692 of file monster.cpp.
{
    return m_size( type->size );
}
References mtype::size, and type.
Referenced by blobify(), Character::can_mount(), iuse::capture_monster_act(), Creature::deal_melee_hit(), Creature::deal_projectile_attack(), drop_or_embed_projectile(), explosion_handler::emp_blast(), extended_description(), get_volume(), get_weight(), vehicle::part_vpower_w(), monexamine::pet_menu(), power_rating(), shove_vehicle(), Character::swim_speed(), game::walk_move(), will_move_to(), and mattack::zombie_fuse().
get_upgrade_time()
int monster::get_upgrade_time () const
Definition at line 299 of file monster.cpp.
{
    return upgrade_time;
}
References upgrade_time.
Referenced by make_mon_corpse(), and mdeath::splatter().
get_volume()
units::volume monster::get_volume () const
Definition at line 2707 of file monster.cpp.
{
    return units::operator*( type->volume, ( get_size() + 1 ) / ( type->size + 1 ) );
}
References get_size(), units::operator*(), mtype::size, type, and mtype::volume.
Referenced by mattack::absorb_meat(), and pet_armor_loc().
get_weight()
units::mass monster::get_weight () const override virtual
Implements Creature.
Definition at line 2697 of file monster.cpp.
{
    return units::operator*( type->weight, ( get_size() + 1 ) / ( type->size + 1 ) );
}
References get_size(), units::operator*(), mtype::size, type, and mtype::weight.
Referenced by Character::can_mount(), item::contain_monster(), monexamine::pet_menu(), map::shake_vehicle(), and mdeath::splatter().
get_worn_armor_val()
int monster::get_worn_armor_val (damage_type dt) const
Definition at line 1861 of file monster.cpp.
{
    if( !has_effect( effect_monster_armor ) ) {
        return 0;
    }
    if( armor_item ) {
        return armor_item->damage_resist( dt );
    }
    return 0;
}
References armor_item, effect_monster_armor, and Creature::has_effect().
Referenced by absorb_hit(), get_armor_bash(), get_armor_bullet(), get_armor_cut(), and get_armor_type().
gibType()
field_type_id monster::gibType () const override virtual
Implements Creature.
Definition at line 2684 of file monster.cpp.
{
    if( is_hallucination() ) {
        return fd_null;
    }
    return type->gibType();
}
References fd_null, mtype::gibType(), is_hallucination(), and type.
Referenced by scatter_chunks(), and mdeath::splatter().
group_bash_skill()
int monster::group_bash_skill (const tripoint & target)
Returns ability of monster and any cooperative helpers to bash the designated target.
Definition at line 1441 of file monmove.cpp.
{
    if( !has_flag( MF_GROUP_BASH ) ) {
        return bash_skill();
    }
    int bashskill = 0;
    // pileup = more bash skill, but only help bashing mob directly in front of target
    const int max_helper_depth = 5;
    const std::vector<tripoint> bzone = get_bashing_zone( target, pos(), max_helper_depth );
    for( const tripoint &candidate : bzone ) {
        // Drawing this line backwards excludes the target and includes the candidate.
        std::vector<tripoint> path_to_target = line_to( target, candidate, 0, 0 );
        bool connected = true;
        monster *mon = nullptr;
        for( const tripoint &in_path : path_to_target ) {
            // If any point in the line from zombie to target is not a cooperating zombie,
            // it can't contribute.
            mon = g->critter_at<monster>( in_path );
            if( !mon ) {
                connected = false;
                break;
            }
            monster &helpermon = *mon;
            if( !helpermon.has_flag( MF_GROUP_BASH ) || helpermon.is_hallucination() ) {
                connected = false;
                break;
            }
        }
        if( !connected || !mon ) {
            continue;
        }
        // If we made it here, the last monster checked was the candidate.
        monster &helpermon = *mon;
        // Contribution falls off rapidly with distance from target.
        bashskill += helpermon.bash_skill() / rl_dist( candidate, target );
    }
    return bashskill;
}
References bash_skill(), g, get_bashing_zone(), has_flag(), is_hallucination(), line_to(), MF_GROUP_BASH, pos(), and rl_dist().
Referenced by bash_at().
has_flag()
bool monster::has_flag (m_flag f) const override virtual
Reimplemented from Creature.
Definition at line 889 of file monster.cpp.
{
    return type->has_flag( f );
}
References mtype::has_flag(), and type.
Referenced by attack_at(), attitude(), bash_estimate(), can_dig(), can_drown(), can_hear(), Character::can_mount(), can_see(), can_submerge(), Character::can_wield(), check_mech_powered(), climbs(), monexamine::deactivate_pet(), deal_damage_handle_type(), Creature::deal_melee_hit(), Creature::deal_projectile_attack(), deal_projectile_attack(), die(), digs(), game::disable_robot(), Character::dismount(), drop_items_on_death(), explosion_handler::emp_blast(), game::examine(), extended_description(), iuse::extinguisher(), feedpet(), flies(), footsteps(), group_bash_skill(), hear_sound(), ranged::hit_with_aoe(), is_immune_damage(), is_immune_effect(), is_immune_field(), is_warm(), knock_back_to(), load(), melee_attack(), mattack::mon_leech_evolution(), monster(), map::monster_in_field(), Character::mount_creature(), move(), avatar_action::move(), move_to(), on_load(), monexamine::pet_menu(), plan(), avatar_action::plthrow(), power_rating(), print_info(), process_effects_internal(), process_turn(), push_to(), scent_move(), explosion_handler::scrambler_blast(), shove_vehicle(), sight_range(), smash(), mattack::smash_specific(), stumble(), swims(), place_monster_iuse::use(), vehicle::use_harness(), use_mech_power(), game::vertical_move(), will_move_to(), and will_reach().
has_grab_break_tec()
bool monster::has_grab_break_tec () const override virtual
Implements Creature.
Definition at line 1945 of file monster.cpp.
{
    return false;
}
has_weapon()
bool monster::has_weapon () const override virtual
Implements Creature.
Definition at line 1289 of file monster.cpp.
{
    return false; // monsters will never have weapons, silly
}
hasten_upgrade()
void monster::hasten_upgrade ()
Definition at line 286 of file monster.cpp.
{
    if( !can_upgrade() || upgrade_time < 1 ) {
        return;
    }
    const int scaled_half_life = type->half_life * get_option<float>( "MONSTER_UPGRADE_FACTOR" );
    upgrade_time -= rng( 1, scaled_half_life );
    if( upgrade_time < 0 ) {
        upgrade_time = 0;
    }
}
References can_upgrade(), mtype::half_life, rng(), type, and upgrade_time.
Referenced by mattack::upgrade().
heal()
int monster::heal (int delta_hp, bool overheal = false)
Flat addition to the monsters hp.
If overheal is true, this is not capped by max hp. Returns actually healed hp.
Definition at line 1640 of file monster.cpp.
{
    const int maxhp = type->hp;
    if( delta_hp <= 0 || ( hp >= maxhp && !overheal ) ) {
        return 0;
    }
    const int old_hp = hp;
    hp += delta_hp;
    if( hp > maxhp && !overheal ) {
        hp = maxhp;
    }
    return hp - old_hp;
}
References hp, mtype::hp, and type.
Referenced by mattack::absorb_meat(), mattack::formblob(), mattack::generator(), spell::heal(), on_load(), process_effects_internal(), and mattack::zombie_fuse().
hear_sound()
void monster::hear_sound (const tripoint & source, int vol, int distance)
Makes monster react to heard sound.
Parameters
source Location of the sound source
vol Volume at the center of the sound source
distance Distance to sound source (currently just rl_dist)
Definition at line 2927 of file monster.cpp.
{
    if( !can_hear() ) {
        return;
    }
    const bool goodhearing = has_flag( MF_GOODHEARING );
    const int volume = goodhearing ? 2 * vol - dist : vol - dist;
    // Error is based on volume, louder sound = less error
    if( volume <= 0 ) {
        return;
    }
    int max_error = 0;
    if( volume < 2 ) {
        max_error = 10;
    } else if( volume < 5 ) {
        max_error = 5;
    } else if( volume < 10 ) {
        max_error = 3;
    } else if( volume < 20 ) {
        max_error = 1;
    }
    int target_x = source.x + rng( -max_error, max_error );
    int target_y = source.y + rng( -max_error, max_error );
    // target_z will require some special check due to soil muffling sounds
    int wander_turns = volume * ( goodhearing ? 6 : 1 );
    process_trigger( mon_trigger::SOUND, volume );
    if( morale >= 0 && anger >= 10 ) {
        // TODO: Add a proper check for fleeing attitude
        // but cache it nicely, because this part is called a lot
        wander_to( tripoint( target_x, target_y, source.z ), wander_turns );
    } else if( morale < 0 ) {
        // Monsters afraid of sound should not go towards sound
        wander_to( tripoint( 2 * posx() - target_x, 2 * posy() - target_y, 2 * posz() - source.z ),
                   wander_turns );
    }
}
References anger, can_hear(), has_flag(), MF_GOODHEARING, morale, posx(), posy(), posz(), process_trigger(), rng(), SOUND, wander_to(), tripoint::x, tripoint::y, and tripoint::z.
hit_roll()
float monster::hit_roll () const override virtual
Should always be overwritten by the appropriate player/NPC/monster version.
Implements Creature.
Definition at line 1935 of file monster.cpp.
{
    float hit = get_hit();
    if( has_effect( effect_bouldering ) ) {
        hit /= 4;
    }
    return melee::melee_hit_range( hit );
}
References effect_bouldering, Creature::get_hit(), Creature::has_effect(), and melee::melee_hit_range().
hp_percentage()
int monster::hp_percentage () const override virtual
Returns overall % of HP remaining.
Implements Creature.
Definition at line 1207 of file monster.cpp.
{
    return get_hp( bodypart_id( "torso" ) ) * 100 / get_hp_max();
}
References get_hp(), and get_hp_max().
Referenced by iuse::capture_monster_act(), and poly().
impact()
int monster::impact (int force, const tripoint & pos) override virtual
Deals falling/collision damage with terrain/creature at pos.
Implements Creature.
Definition at line 2035 of file monster.cpp.
{
    if( force <= 0 ) {
        return force;
    }
    const float mod = fall_damage_mod();
    int total_dealt = 0;
    if( g->m.has_flag( TFLAG_SHARP, p ) ) {
        const int cut_damage = std::max( 0.0f, 10 * mod - get_armor_cut( bodypart_id( "torso" ) ) );
        apply_damage( nullptr, bodypart_id( "torso" ), cut_damage );
        total_dealt += 10 * mod;
    }
    const int bash_damage = std::max( 0.0f, force * mod - get_armor_bash( bodypart_id( "torso" ) ) );
    apply_damage( nullptr, bodypart_id( "torso" ), bash_damage );
    total_dealt += force * mod;
    add_effect( effect_downed, time_duration::from_turns( rng( 0, mod * 3 + 1 ) ) );
    return total_dealt;
}
References add_effect(), apply_damage(), effect_downed, fall_damage_mod(), time_duration::from_turns(), g, get_armor_bash(), get_armor_cut(), rng(), and TFLAG_SHARP.
in_species()
bool monster::in_species (const species_id & spec) const override virtual
Reimplemented from Creature.
Definition at line 1299 of file monster.cpp.
{
    return type->in_species( spec );
}
References mtype::in_species(), and type.
init_from_item()
void monster::init_from_item (const item & itm)
Initialize values like speed / hp from data of an item.
This applies to robotic monsters that are spawned by invoking an item (e.g. turret), and to reviving monsters that spawn from a corpse.
Definition at line 2782 of file monster.cpp.
{
    if( itm.typeId() == itype_corpse ) {
        set_speed_base( get_speed_base() * 0.8 );
        const int burnt_penalty = itm.burnt;
        hp = static_cast<int>( hp * 0.7 );
        if( itm.damage_level( 4 ) > 0 ) {
            set_speed_base( speed_base / ( itm.damage_level( 4 ) + 1 ) );
            hp /= itm.damage_level( 4 ) + 1;
        }
        hp -= burnt_penalty;
        // HP can be 0 or less, in this case revive_corpse will just deactivate the corpse
        if( hp > 0 && type->has_flag( MF_REVIVES_HEALTHY ) ) {
            hp = type->hp;
            set_speed_base( type->speed );
        }
        const std::string up_time = itm.get_var( "upgrade_time" );
        if( !up_time.empty() ) {
            upgrade_time = std::stoi( up_time );
        }
    } else {
        // must be a robot
        const int damfac = itm.max_damage() - std::max( 0, itm.damage() ) + 1;
        // One hp at least, everything else would be unfair (happens only to monster with *very* low hp),
        hp = std::max( 1, hp * damfac / ( itm.max_damage() + 1 ) );
    }
}
References item::burnt, item::damage(), item::damage_level(), Creature::get_speed_base(), item::get_var(), mtype::has_flag(), hp, mtype::hp, itype_corpse, item::max_damage(), MF_REVIVES_HEALTHY, Creature::set_speed_base(), mtype::speed, Creature::speed_base, type, item::typeId(), and upgrade_time.
Referenced by game::revive_corpse(), and place_monster_iuse::use().
is_aquatic_danger()
bool monster::is_aquatic_danger (const tripoint & at_pos)
Returns true if the given square presents a possibility of drowning for the monster: it's deep water, it's liquid, the monster can drown, and there is no boardable vehicle part present.
Definition at line 654 of file monmove.cpp.
{
    return g->m.has_flag_ter( TFLAG_DEEP_WATER, at_pos ) && g->m.has_flag( flag_LIQUID, at_pos ) &&
           can_drown() && !g->m.veh_at( at_pos ).part_with_feature( "BOARDABLE", false );
}
References can_drown(), flag_LIQUID(), g, and TFLAG_DEEP_WATER.
Referenced by leap_actor::call(), and die_if_drowning().
is_dead()
bool monster::is_dead () const
Definition at line 2777 of file monster.cpp.
{
    return dead || is_dead_state();
}
References dead, and is_dead_state().
Referenced by explosion_handler::emp_blast(), game::fling_creature(), game::forced_door_closing(), Creature_tracker::kill_marked_for_death(), move(), avatar_action::move(), move_to(), Creature_tracker::remove_dead(), iuse::robotcontrol_can_target(), stumble(), and Creature_tracker::update_pos().
is_dead_state()
bool monster::is_dead_state () const override virtual
Implements Creature.
Definition at line 1369 of file monster.cpp.
{
    return hp <= 0;
}
References hp.
Referenced by apply_damage(), drop_or_embed_projectile(), is_dead(), and mdefense::return_fire().
is_elec_immune()
bool monster::is_elec_immune () const override virtual
Implements Creature.
Definition at line 1304 of file monster.cpp.
{
    return is_immune_damage( DT_ELECTRIC );
}
References DT_ELECTRIC, and is_immune_damage().
is_fleeing()
bool monster::is_fleeing (player & u) const
Definition at line 1028 of file monster.cpp.
{
    if( effect_cache[FLEEING] ) {
        return true;
    }
    if( anger >= 100 || morale >= 100 ) {
        return false;
    }
    monster_attitude att = attitude( &u );
    return att == MATT_FLEE || ( att == MATT_FOLLOW && rl_dist( pos(), u.pos() ) <= 4 );
}
References anger, attitude(), effect_cache, FLEEING, MATT_FLEE, MATT_FOLLOW, morale, Character::pos(), pos(), and rl_dist().
Referenced by plan(), process_effects_internal(), and scent_move().
is_hallucination()
bool monster::is_hallucination () const override virtual
Implements Creature.
Definition at line 2672 of file monster.cpp.
{
    return hallucination;
}
References hallucination.
Referenced by Creature_tracker::add(), attack_at(), bash_at(), bloodType(), iuse::camera(), check_mech_powered(), deal_projectile_attack(), game::despawn_monster(), die(), drop_items_on_death(), gibType(), iuse::granade_act(), group_bash_skill(), knock_back_to(), make_fungus(), melee_attack(), move(), avatar_action::move(), move_to(), behavior::monster_oracle_t::not_hallucination(), on_hit(), petfood(), photo_def_for_camera_point(), process_turn(), push_to(), stumble(), and use_mech_power().
is_immune_damage()
bool monster::is_immune_damage (damage_type dt) const override virtual
Implements Creature.
Definition at line 1336 of file monster.cpp.
{
    switch( dt ) {
        case DT_NULL:
            return true;
        case DT_TRUE:
            return false;
        case DT_BIOLOGICAL:
            // NOTE: Unused
            return false;
        case DT_BASH:
            return false;
        case DT_CUT:
            return false;
        case DT_ACID:
            return has_flag( MF_ACIDPROOF );
        case DT_STAB:
            return false;
        case DT_HEAT:
            return has_flag( MF_FIREPROOF );
        case DT_COLD:
            return false;
        case DT_ELECTRIC:
            return type->sp_defense == &mdefense::zapback ||
                   has_flag( MF_ELECTRIC ) ||
                   has_flag( MF_ELECTRIC_FIELD );
        case DT_BULLET:
            return false;
        default:
            return true;
    }
}
References DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_NULL, DT_STAB, DT_TRUE, has_flag(), MF_ACIDPROOF, MF_ELECTRIC, MF_ELECTRIC_FIELD, MF_FIREPROOF, mtype::sp_defense, type, and mdefense::zapback().
Referenced by is_elec_immune(), and is_immune_effect().
is_immune_effect()
bool monster::is_immune_effect (const efftype_id & effect) const override virtual
Implements Creature.
Definition at line 1309 of file monster.cpp.
{
    if( effect == effect_onfire ) {
        return is_immune_damage( DT_HEAT ) ||
               made_of( LIQUID ) ||
               has_flag( MF_FIREY );
    }
    if( effect == effect_bleed ) {
        return !has_flag( MF_WARM ) ||
               !made_of( material_id( "flesh" ) );
    }
    if( effect == effect_paralyzepoison ||
        effect == effect_badpoison ||
        effect == effect_poison ) {
        return !has_flag( MF_WARM ) ||
               ( !made_of( material_id( "flesh" ) ) && !made_of( material_id( "iflesh" ) ) );
    }
    if( effect == effect_stunned ) {
        return has_flag( MF_STUN_IMMUNE );
    }
    return false;
}
References DT_HEAT, effect_badpoison, effect_bleed, effect_onfire, effect_paralyzepoison, effect_poison, effect_stunned, has_flag(), is_immune_damage(), LIQUID, made_of(), MF_FIREY, MF_STUN_IMMUNE, and MF_WARM.
is_immune_field()
bool monster::is_immune_field (const field_type_id &) const override virtual
Returns true if we are immune to the field type with the given fid.
Does not handle intensity, so this function should only be called through is_dangerous_field().
Reimplemented from Creature.
Definition at line 83 of file monmove.cpp.
{
    if( fid == fd_fungal_haze ) {
        return has_flag( MF_NO_BREATHE ) || type->in_species( FUNGUS );
    }
    if( fid == fd_fungicidal_gas ) {
        return !type->in_species( FUNGUS );
    }
    if( fid == fd_insecticidal_gas ) {
        return !type->in_species( INSECT ) && !type->in_species( SPIDER );
    }
    const field_type &ft = fid.obj();
    if( ft.has_fume ) {
        return has_flag( MF_NO_BREATHE );
    }
    if( ft.has_acid ) {
        return has_flag( MF_ACIDPROOF ) || flies();
    }
    if( ft.has_fire ) {
        return has_flag( MF_FIREPROOF );
    }
    if( ft.has_elec ) {
        return has_flag( MF_ELECTRIC );
    }
    if( ft.immune_mtypes.count( type->id ) > 0 ) {
        return true;
    }
    // No specific immunity was found, so fall upwards
    return Creature::is_immune_field( fid );
}
References fd_fungal_haze, fd_fungicidal_gas, fd_insecticidal_gas, flies(), FUNGUS, field_type::has_acid, field_type::has_elec, field_type::has_fire, has_flag(), field_type::has_fume, mtype::id, field_type::immune_mtypes, mtype::in_species(), INSECT, Creature::is_immune_field(), MF_ACIDPROOF, MF_ELECTRIC, MF_FIREPROOF, MF_NO_BREATHE, int_id< T >::obj(), SPIDER, and type.
is_monster()
bool monster::is_monster () const inline override virtual
Reimplemented from Creature.
Definition at line 97 of file monster.h.
{
            return true;
        }
is_on_ground()
bool monster::is_on_ground () const override virtual
Implements Creature.
Definition at line 1283 of file monster.cpp.
{
    // TODO: actually make this work
    return false;
}
is_symbol_highlighted()
bool monster::is_symbol_highlighted () const override virtual
Reimplemented from Creature.
Definition at line 856 of file monster.cpp.
{
    return friendly != 0;
}
References friendly.
is_underwater()
bool monster::is_underwater () const override virtual
Reimplemented from Creature.
Definition at line 1278 of file monster.cpp.
{
    return Creature::is_underwater() && can_submerge();
}
References can_submerge(), and Creature::is_underwater().
Referenced by digging(), and sight_range().
is_warm()
bool monster::is_warm () const override virtual
Reimplemented from Creature.
Definition at line 1294 of file monster.cpp.
{
    return has_flag( MF_WARM );
}
References has_flag(), and MF_WARM.
knock_back_to()
void monster::knock_back_to (const tripoint & to) override virtual
Knocks the creature to a specified tile.
Implements Creature.
Definition at line 1940 of file monmove.cpp.
{
    if( to == pos() ) {
        return; // No effect
    }
    if( is_hallucination() ) {
        die( nullptr );
        return;
    }
    bool u_see = g->u.sees( to );
    // First, see if we hit another monster
    if( monster *const z = g->critter_at<monster>( to ) ) {
        apply_damage( z, bodypart_id( "torso" ), z->type->size );
        add_effect( effect_stunned, 1_turns );
        if( type->size > 1 + z->type->size ) {
            z->knock_back_from( pos() ); // Chain reaction!
            z->apply_damage( this, bodypart_id( "torso" ), type->size );
            z->add_effect( effect_stunned, 1_turns );
        } else if( type->size > z->type->size ) {
            z->apply_damage( this, bodypart_id( "torso" ), type->size );
            z->add_effect( effect_stunned, 1_turns );
        }
        z->check_dead_state();
        if( u_see ) {
            add_msg( _( "The %1$s bounces off a %2$s!" ), name(), z->name() );
        }
        return;
    }
    if( npc *const p = g->critter_at<npc>( to ) ) {
        apply_damage( p, bodypart_id( "torso" ), 3 );
        add_effect( effect_stunned, 1_turns );
        p->deal_damage( this, bodypart_id( "torso" ), damage_instance( DT_BASH, type->size ) );
        if( u_see ) {
            add_msg( _( "The %1$s bounces off %2$s!" ), name(), p->name );
        }
        p->check_dead_state();
        return;
    }
    // If we're still in the function at this point, we're actually moving a tile!
    // die_if_drowning will kill the monster if necessary, but if the deep water
    // tile is on a vehicle, we should check for swimmers out of water
    if( !die_if_drowning( to ) && has_flag( MF_AQUATIC ) ) {
        die( nullptr );
        if( u_see ) {
            add_msg( _( "The %s flops around and dies!" ), name() );
        }
    }
    if( g->m.impassable( to ) ) {
        // It's some kind of wall.
        apply_damage( nullptr, bodypart_id( "torso" ), type->size );
        add_effect( effect_stunned, 2_turns );
        if( u_see ) {
            add_msg( _( "The %1$s bounces off a %2$s." ), name(),
                     g->m.obstacle_name( to ) );
        }
    } else { // It's no wall
        setpos( to );
    }
    check_dead_state();
}
References _, add_effect(), add_msg(), apply_damage(), Creature::check_dead_state(), die(), die_if_drowning(), DT_BASH, effect_stunned, g, has_flag(), is_hallucination(), MF_AQUATIC, name(), pos(), setpos(), mtype::size, and type.
load()
void monster::load (const JsonObject & data) protected
Definition at line 1775 of file savegame_json.cpp.
{
    Creature::load( data );
    std::string sidtmp;
    // load->str->int
    data.read( "typeid", sidtmp );
    type = &mtype_id( sidtmp ).obj();
    data.read( "unique_name", unique_name );
    data.read( "posx", position.x );
    data.read( "posy", position.y );
    if( !data.read( "posz", position.z ) ) {
        position.z = g->get_levz();
    }
    data.read( "wandf", wandf );
    data.read( "wandx", wander_pos.x );
    data.read( "wandy", wander_pos.y );
    if( data.read( "wandz", wander_pos.z ) ) {
        wander_pos.z = position.z;
    }
    if( data.has_object( "tied_item" ) ) {
        JsonIn *tied_item_json = data.get_raw( "tied_item" );
        item newitem;
        newitem.deserialize( *tied_item_json );
        tied_item = cata::make_value<item>( newitem );
    }
    if( data.has_object( "tack_item" ) ) {
        JsonIn *tack_item_json = data.get_raw( "tack_item" );
        item newitem;
        newitem.deserialize( *tack_item_json );
        tack_item = cata::make_value<item>( newitem );
    }
    if( data.has_object( "armor_item" ) ) {
        JsonIn *armor_item_json = data.get_raw( "armor_item" );
        item newitem;
        newitem.deserialize( *armor_item_json );
        armor_item = cata::make_value<item>( newitem );
    }
    if( data.has_object( "storage_item" ) ) {
        JsonIn *storage_item_json = data.get_raw( "storage_item" );
        item newitem;
        newitem.deserialize( *storage_item_json );
        storage_item = cata::make_value<item>( newitem );
    }
    if( data.has_object( "battery_item" ) ) {
        JsonIn *battery_item_json = data.get_raw( "battery_item" );
        item newitem;
        newitem.deserialize( *battery_item_json );
        battery_item = cata::make_value<item>( newitem );
    }
    data.read( "hp", hp );
    // sp_timeout indicates an old save, prior to the special_attacks refactor
    if( data.has_array( "sp_timeout" ) ) {
        JsonArray parray = data.get_array( "sp_timeout" );
        size_t index = 0;
        int ptimeout = 0;
        while( parray.has_more() && index < type->special_attacks_names.size() ) {
            if( parray.read_next( ptimeout ) ) {
                // assume timeouts saved in same order as current monsters.json listing
                const std::string &aname = type->special_attacks_names[index++];
                auto &entry = special_attacks[aname];
                if( ptimeout >= 0 ) {
                    entry.cooldown = ptimeout;
                } else { // -1 means disabled, unclear what <-1 values mean in old saves
                    entry.cooldown = type->special_attacks.at( aname )->cooldown;
                    entry.enabled = false;
                }
            }
        }
    }
    // special_attacks indicates a save after the special_attacks refactor
    if( data.has_object( "special_attacks" ) ) {
        for( const JsonMember member : data.get_object( "special_attacks" ) ) {
            JsonObject saobject = member.get_object();
            saobject.allow_omitted_members();
            auto &entry = special_attacks[member.name()];
            entry.cooldown = saobject.get_int( "cooldown" );
            entry.enabled = saobject.get_bool( "enabled" );
        }
    }
    // make sure the loaded monster has every special attack its type says it should have
    for( auto &sa : type->special_attacks ) {
        const std::string &aname = sa.first;
        if( special_attacks.find( aname ) == special_attacks.end() ) {
            auto &entry = special_attacks[aname];
            entry.cooldown = rng( 0, sa.second->cooldown );
        }
    }
    data.read( "friendly", friendly );
    data.read( "mission_id", mission_id );
    data.read( "no_extra_death_drops", no_extra_death_drops );
    data.read( "dead", dead );
    data.read( "anger", anger );
    data.read( "morale", morale );
    data.read( "hallucination", hallucination );
    data.read( "stairscount", staircount ); // really?
    data.read( "fish_population", fish_population );
    // Load legacy plans.
    std::vector<tripoint> plans;
    data.read( "plans", plans );
    if( !plans.empty() ) {
        goal = plans.back();
    }
    data.read( "summon_time_limit", summon_time_limit );
    // This is relative to the monster so it isn't invalidated by map shifting.
    tripoint destination;
    data.read( "destination", destination );
    goal = pos() + destination;
    upgrades = data.get_bool( "upgrades", type->upgrades );
    upgrade_time = data.get_int( "upgrade_time", -1 );
    reproduces = data.get_bool( "reproduces", type->reproduces );
    baby_timer.reset();
    data.read( "baby_timer", baby_timer );
    if( baby_timer && *baby_timer == calendar::before_time_starts ) {
        baby_timer.reset();
    }
    data.read( "udder_timer", udder_timer );
    horde_attraction = static_cast<monster_horde_attraction>( data.get_int( "horde_attraction", 0 ) );
    data.read( "inv", inv );
    data.read( "corpse_components", corpse_components );
    data.read( "dragged_foe_id", dragged_foe_id );
    if( data.has_int( "ammo" ) && !type->starting_ammo.empty() ) {
        // Legacy loading for ammo.
        normalize_ammo( data.get_int( "ammo" ) );
    } else {
        data.read( "ammo", ammo );
        // legacy loading for milkable creatures, fix mismatch.
        if( has_flag( MF_MILKABLE ) && !type->starting_ammo.empty() && !ammo.empty() &&
            type->starting_ammo.begin()->first != ammo.begin()->first ) {
            const itype_id old_type = ammo.begin()->first;
            const int old_value = ammo.begin()->second;
            ammo[type->starting_ammo.begin()->first] = old_value;
            ammo.erase( old_type );
        }
    }
    faction = mfaction_str_id( data.get_string( "faction", "" ) );
    if( !data.read( "last_updated", last_updated ) ) {
        last_updated = calendar::turn;
    }
    data.read( "mounted_player_id", mounted_player_id );
    data.read( "path", path );
}
References JsonObject::allow_omitted_members(), ammo, anger, armor_item, baby_timer, battery_item, calendar::before_time_starts, corpse_components, dead, item::deserialize(), dragged_foe_id, fish_population, friendly, g, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_raw(), JsonObject::get_string(), goal, hallucination, JsonObject::has_array(), has_flag(), JsonObject::has_int(), JsonArray::has_more(), JsonObject::has_object(), horde_attraction, hp, inv, last_updated, Creature::load(), mapgen_defer::member, MF_MILKABLE, mission_id, morale, mounted_player_id, mtype_id, no_extra_death_drops, normalize_ammo(), path, pos(), position, JsonObject::read(), JsonArray::read_next(), reproduces, mtype::reproduces, rng(), special_attacks, mtype::special_attacks, mtype::special_attacks_names, staircount, mtype::starting_ammo, storage_item, summon_time_limit, tack_item, tied_item, calendar::turn, type, udder_timer, unique_name, upgrade_time, upgrades, mtype::upgrades, wander_pos, wandf, tripoint::x, tripoint::y, and tripoint::z.
Referenced by deserialize().
made_of() [1/2]
bool monster::made_of (const material_id & m) const override virtual
Implements Creature.
Definition at line 978 of file monster.cpp.
{
    return type->made_of( m );
}
References mtype::made_of(), and type.
Referenced by iuse::extinguisher(), mattack::formblob(), is_immune_effect(), trapfunc::lava(), make_fungus(), Character::melee_attack(), map::monster_in_field(), name_with_armor(), on_load(), and process_one_effect().
made_of() [2/2]
bool monster::made_of (phase_id p) const
Definition at line 988 of file monster.cpp.
{
    return type->phase == p;
}
References mtype::phase, and type.
made_of_any()
bool monster::made_of_any (const std::set< material_id > & ms) const override virtual
Implements Creature.
Definition at line 983 of file monster.cpp.
{
    return type->made_of_any( ms );
}
References mtype::made_of_any(), coords::ms, and type.
Referenced by trapfunc::lava(), and map::monster_in_field().
make_ally()
void monster::make_ally (const monster & z)
Makes this monster an ally of the given monster.
Definition at line 2661 of file monster.cpp.
{
    friendly = z.friendly;
    faction = z.faction;
}
References faction, and friendly.
Referenced by blobify(), fungal_effects::fungalize(), and mattack::resurrect().
make_friendly()
void monster::make_friendly ()
Definition at line 2655 of file monster.cpp.
{
    unset_dest();
    friendly = rng( 5, 30 ) + rng( 0, 20 );
}
References friendly, rng(), and unset_dest().
Referenced by iuse::artifact(), explosion_handler::emp_blast(), and explosion_handler::scrambler_blast().
make_fungus()
bool monster::make_fungus ()
Makes this monster into a fungus version Returns false if no such monster exists Returns true if monster is immune to spores, or if it has been fungalized.
Definition at line 2623 of file monster.cpp.
{
    if( is_hallucination() ) {
        return true;
    }
    if( type->in_species( FUNGUS ) ) { // No friendly-fungalizing ;-)
        return true;
    }
    if( !made_of( material_id( "flesh" ) ) && !made_of( material_id( "hflesh" ) ) &&
        !made_of( material_id( "veggy" ) ) && !made_of( material_id( "iflesh" ) ) &&
        !made_of( material_id( "bone" ) ) ) {
        // No fungalizing robots or weird stuff (mi-gos are technically fungi, blobs are goo)
        return true;
    }
    if( type->has_flag( MF_NO_FUNG_DMG ) ) {
        return true; // Returns true when monster immune to fungal damage.
    }
    if( type->fungalize_into.is_empty() ) {
        return false;
    }
    const std::string old_name = name();
    poly( type->fungalize_into );
    if( g->u.sees( pos() ) ) {
        add_msg( m_info, _( "The spores transform %1$s into a %2$s!" ),
                 old_name, name() );
    }
    return true;
}
References _, add_msg(), mtype::fungalize_into, FUNGUS, g, mtype::has_flag(), mtype::in_species(), string_id< T >::is_empty(), is_hallucination(), m_info, made_of(), MF_NO_FUNG_DMG, name(), poly(), pos(), and type.
Referenced by fungal_effects::fungalize(), iuse::fungicide(), and map::monster_in_field().
mech_str_addition()
int monster::mech_str_addition () const
Definition at line 2402 of file monster.cpp.
{
    return type->mech_str_bonus;
}
References mtype::mech_str_bonus, and type.
Referenced by ranged::throw_item().
melee_attack() [1/3]
void monster::melee_attack (Creature & p, bool) delete
melee_attack() [2/3]
void monster::melee_attack (Creature & target)
Definition at line 1389 of file monster.cpp.
{
    melee_attack( target, get_hit() );
}
References Creature::get_hit(), and melee_attack().
Referenced by attack_at(), mattack::grab(), melee_attack(), and game::update_stair_monsters().
melee_attack() [3/3]
void monster::melee_attack (Creature & target, float accuracy)
Definition at line 1394 of file monster.cpp.
{
    mod_moves( -type->attack_cost );
    if( type->melee_dice == 0 ) {
        // We don't attack, so just return
        return;
    }
    if( this == &target ) {
        // This happens sometimes
        return;
    }
    if( !can_squeeze_to( target.pos() ) ) {
        return;
    }
    int hitspread = target.deal_melee_attack( this, melee::melee_hit_range( accuracy ) );
    if( target.is_player() ||
        ( target.is_npc() && g->u.attitude_to( target ) == A_FRIENDLY ) ) {
        // Make us a valid target for a few turns
        add_effect( effect_hit_by_player, 3_turns );
    }
    if( has_flag( MF_HIT_AND_RUN ) ) {
        add_effect( effect_run, 4_turns );
    }
    const bool u_see_me = g->u.sees( *this );
    damage_instance damage = !is_hallucination() ? type->melee_damage : damage_instance();
    if( !is_hallucination() && type->melee_dice > 0 ) {
        damage.add_damage( DT_BASH, dice( type->melee_dice, type->melee_sides ) );
    }
    dealt_damage_instance dealt_dam;
    if( hitspread >= 0 ) {
        target.deal_melee_hit( this, hitspread, false, damage, dealt_dam );
    }
    body_part bp_hit = dealt_dam.bp_hit;
    const int total_dealt = dealt_dam.total_damage();
    if( hitspread < 0 ) {
        // Miss
        if( u_see_me && !target.in_sleep_state() ) {
            if( target.is_player() ) {
                add_msg( _( "You dodge %s." ), disp_name() );
            } else if( target.is_npc() ) {
                add_msg( _( "%1$s dodges %2$s attack." ),
                         target.disp_name(), name() );
            } else {
                add_msg( _( "The %1$s misses %2$s!" ),
                         name(), target.disp_name() );
            }
        } else if( target.is_player() ) {
            add_msg( _( "You dodge an attack from an unseen source." ) );
        }
    } else if( is_hallucination() || total_dealt > 0 ) {
        // Hallucinations always produce messages but never actually deal damage
        if( u_see_me ) {
            if( target.is_player() ) {
                sfx::play_variant_sound( "melee_attack", "monster_melee_hit",
                                         sfx::get_heard_volume( target.pos() ) );
                sfx::do_player_death_hurt( dynamic_cast<player &>( target ), false );
                //~ 1$s is attacker name, 2$s is bodypart name in accusative.
                add_msg( m_bad, _( "The %1$s hits your %2$s." ), name(),
                         body_part_name_accusative( bp_hit ) );
            } else if( target.is_npc() ) {
                if( has_effect( effect_ridden ) && has_flag( MF_RIDEABLE_MECH ) && pos() == g->u.pos() ) {
                    //~ %1$s: name of your mount, %2$s: target NPC name, %3$d: damage value
                    add_msg( m_good, _( "Your %1$s hits %2$s for %3$d damage!" ), name(), target.disp_name(),
                             total_dealt );
                } else {
                    //~ %1$s: attacker name, %2$s: target NPC name, %3$s: bodypart name in accusative
                    add_msg( _( "The %1$s hits %2$s %3$s." ), name(),
                             target.disp_name( true ),
                             body_part_name_accusative( bp_hit ) );
                }
            } else {
                if( has_effect( effect_ridden ) && has_flag( MF_RIDEABLE_MECH ) && pos() == g->u.pos() ) {
                    //~ %1$s: name of your mount, %2$s: target creature name, %3$d: damage value
                    add_msg( m_good, _( "Your %1$s hits %2$s for %3$d damage!" ), get_name(), target.disp_name(),
                             total_dealt );
                } else {
                    //~ %1$s: attacker name, %2$s: target creature name
                    add_msg( _( "The %1$s hits %2$s!" ), name(), target.disp_name() );
                }
            }
        } else if( target.is_player() ) {
            //~ %s is bodypart name in accusative.
            add_msg( m_bad, _( "Something hits your %s." ),
                     body_part_name_accusative( bp_hit ) );
        }
    } else {
        // No damage dealt
        if( u_see_me ) {
            if( target.is_player() ) {
                //~ 1$s is attacker name, 2$s is bodypart name in accusative, 3$s is armor name
                add_msg( _( "The %1$s hits your %2$s, but your %3$s protects you." ), name(),
                         body_part_name_accusative( bp_hit ), target.skin_name() );
            } else if( target.is_npc() ) {
                //~ $1s is monster name, %2$s is that monster target name,
                //~ $3s is target bodypart name in accusative, $4s is the monster target name,
                //~ 5$s is target armor name.
                add_msg( _( "The %1$s hits %2$s %3$s but is stopped by %4$s %5$s." ), name(),
                         target.disp_name( true ),
                         body_part_name_accusative( bp_hit ),
                         target.disp_name( true ),
                         target.skin_name() );
            } else {
                //~ $1s is monster name, %2$s is that monster target name,
                //~ $3s is target armor name.
                add_msg( _( "The %1$s hits %2$s but is stopped by its %3$s." ),
                         name(),
                         target.disp_name(),
                         target.skin_name() );
            }
        } else if( target.is_player() ) {
            //~ 1$s is bodypart name in accusative, 2$s is armor name.
            add_msg( _( "Something hits your %1$s, but your %2$s protects you." ),
                     body_part_name_accusative( bp_hit ), target.skin_name() );
        }
    }
    target.check_dead_state();
    if( is_hallucination() ) {
        if( one_in( 7 ) ) {
            die( nullptr );
        }
        return;
    }
    if( total_dealt <= 0 ) {
        return;
    }
    // Add any on damage effects
    for( const auto &eff : type->atk_effs ) {
        if( x_in_y( eff.chance, 100 ) ) {
            const body_part affected_bp = eff.affect_hit_bp ? bp_hit : eff.bp;
            target.add_effect( eff.id, time_duration::from_turns( eff.duration ), affected_bp );
            if( eff.permanent ) {
                target.get_effect( eff.id, affected_bp ).set_permanent();
            }
        }
    }
    const int stab_cut = dealt_dam.type_damage( DT_CUT ) + dealt_dam.type_damage( DT_STAB );
    if( stab_cut > 0 && has_flag( MF_VENOM ) ) {
        target.add_msg_if_player( m_bad, _( "You're envenomed!" ) );
        target.add_effect( effect_poison, 3_minutes );
    }
    if( stab_cut > 0 && has_flag( MF_BADVENOM ) ) {
        target.add_msg_if_player( m_bad,
                                  _( "You feel venom flood your body, wracking you with pain" ) );
        target.add_effect( effect_badpoison, 4_minutes );
    }
    if( stab_cut > 0 && has_flag( MF_PARALYZE ) ) {
        target.add_msg_if_player( m_bad, _( "You feel venom enter your body!" ) );
        target.add_effect( effect_paralyzepoison, 10_minutes );
    }
    if( total_dealt > 6 && stab_cut > 0 && has_flag( MF_BLEED ) ) {
        // Maybe should only be if DT_CUT > 6... Balance question
        target.add_effect( effect_bleed, 6_minutes, bp_hit );
    }
}
References _, Creature::A_FRIENDLY, damage_instance::add_damage(), Creature::add_effect(), add_effect(), add_msg(), Creature::add_msg_if_player(), mtype::atk_effs, mtype::attack_cost, body_part_name_accusative(), dealt_damage_instance::bp_hit, can_squeeze_to(), Creature::check_dead_state(), Creature::deal_melee_attack(), Creature::deal_melee_hit(), dice(), die(), Creature::disp_name(), disp_name(), sfx::do_player_death_hurt(), DT_BASH, DT_CUT, DT_STAB, effect_badpoison, effect_bleed, effect_hit_by_player, effect_paralyzepoison, effect_poison, effect_ridden, effect_run, time_duration::from_turns(), g, Creature::get_effect(), sfx::get_heard_volume(), get_name(), Creature::has_effect(), has_flag(), Creature::in_sleep_state(), is_hallucination(), Creature::is_npc(), Creature::is_player(), m_bad, m_good, mtype::melee_damage, mtype::melee_dice, melee::melee_hit_range(), mtype::melee_sides, MF_BADVENOM, MF_BLEED, MF_HIT_AND_RUN, MF_PARALYZE, MF_RIDEABLE_MECH, MF_VENOM, Creature::mod_moves(), name(), one_in(), sfx::play_variant_sound(), Creature::pos(), pos(), effect::set_permanent(), Creature::skin_name(), dealt_damage_instance::total_damage(), type, dealt_damage_instance::type_damage(), and x_in_y().
move()
void monster::move ()
Definition at line 678 of file monmove.cpp.
{
    // We decrement wandf no matter what.  We'll save our wander_to plans until
    // after we finish out set_dest plans, UNLESS they time out first.
    if( wandf > 0 ) {
        wandf--;
    }
    //Hallucinations have a chance of disappearing each turn
    if( is_hallucination() && one_in( 25 ) ) {
        die( nullptr );
        return;
    }
    map &here = get_map();
    behavior::monster_oracle_t oracle( this );
    behavior::tree goals;
    goals.add( type->get_goals() );
    std::string action = goals.tick( &oracle );
    //The monster can consume objects it stands on. Check if there are any.
    //If there are. Consume them.
    // TODO: Stick this in a map and dispatch to it via the action string.
    if( action == "consume_items" ) {
        if( g->u.sees( *this ) ) {
            add_msg( _( "The %s flows around the objects on the floor and they are quickly dissolved!" ),
                     name() );
        }
        static const auto volume_per_hp = 250_ml;
        for( auto &elem : g->m.i_at( pos() ) ) {
            hp += elem.volume() / volume_per_hp; // Yeah this means it can get more HP than normal.
            if( has_flag( MF_ABSORBS_SPLITS ) ) {
                while( hp / 2 > type->hp ) {
                    monster *const spawn = g->place_critter_around( type->id, pos(), 1 );
                    if( !spawn ) {
                        break;
                    }
                    hp -= type->hp;
                    //this is a new copy of the monster. Ideally we should copy the stats/effects that affect the parent
                    spawn->make_ally( *this );
                    if( g->u.sees( *this ) ) {
                        add_msg( _( "The %s splits in two!" ), name() );
                    }
                }
            }
        }
        g->m.i_clear( pos() );
    }
    // record position before moving to put the player there if we're dragging
    tripoint drag_to = g->m.getabs( pos() );
    const bool pacified = has_effect( effect_pacified );
    // First, use the special attack, if we can!
    // The attack may change `monster::special_attacks` (e.g. by transforming
    // this into another monster type). Therefore we can not iterate over it
    // directly and instead iterate over the map from the monster type
    // (properties of monster types should never change).
    for( const auto &sp_type : type->special_attacks ) {
        const std::string &special_name = sp_type.first;
        const auto local_iter = special_attacks.find( special_name );
        if( local_iter == special_attacks.end() ) {
            continue;
        }
        mon_special_attack &local_attack_data = local_iter->second;
        if( !local_attack_data.enabled ) {
            continue;
        }
        // Cooldowns are decremented in monster::process_turn
        if( local_attack_data.cooldown == 0 && !pacified && !is_hallucination() ) {
            if( !sp_type.second->call( *this ) ) {
                continue;
            }
            // `special_attacks` might have changed at this point. Sadly `reset_special`
            // doesn't check the attack name, so we need to do it here.
            if( special_attacks.count( special_name ) == 0 ) {
                continue;
            }
            reset_special( special_name );
        }
    }
    // Check if they're dragging a foe and find their hapless victim
    player *dragged_foe = find_dragged_foe();
    // Give nursebots a chance to do surgery.
    nursebot_operate( dragged_foe );
    // The monster can sometimes hang in air due to last fall being blocked
    if( !flies() && g->m.has_flag( TFLAG_NO_FLOOR, pos() ) ) {
        g->m.creature_on_trap( *this, false );
        if( is_dead() ) {
            return;
        }
    }
    // if the monster is in a deep water tile, it has a chance to drown
    if( die_if_drowning( pos(), 10 ) ) {
        return;
    }
    if( moves < 0 ) {
        return;
    }
    // TODO: Move this to attack_at/move_to/etc. functions
    bool attacking = false;
    if( !move_effects( attacking ) ) {
        moves = 0;
        return;
    }
    if( has_flag( MF_IMMOBILE ) || has_flag( MF_RIDEABLE_MECH ) ) {
        moves = 0;
        return;
    }
    if( has_effect( effect_stunned ) ) {
        stumble();
        moves = 0;
        return;
    }
    if( friendly > 0 ) {
        --friendly;
    }
    if( has_effect( effect_ai_waiting ) ) {
        moves = 0;
        return;
    }
    // don't move if a passenger in a moving vehicle
    auto vp = g->m.veh_at( pos() );
    bool harness_part = static_cast<bool>( g->m.veh_at( pos() ).part_with_feature( "ANIMAL_CTRL",
                                           true ) );
    if( vp && vp->vehicle().is_moving() && vp->vehicle().get_pet( vp->part_index() ) ) {
        moves = 0;
        return;
        // Don't move if harnessed, even if vehicle is stationary
    } else if( vp && has_effect( effect_harnessed ) ) {
        moves = 0;
        return;
        // If harnessed monster finds itself moved from the harness point, the harness probably broke!
    } else if( !harness_part && has_effect( effect_harnessed ) ) {
        remove_effect( effect_harnessed );
    }
    // Set attitude to attitude to our current target
    monster_attitude current_attitude = attitude( nullptr );
    if( !wander() ) {
        if( goal == g->u.pos() ) {
            current_attitude = attitude( &g->u );
        } else {
            for( const npc &guy : g->all_npcs() ) {
                if( goal == guy.pos() ) {
                    current_attitude = attitude( &guy );
                }
            }
        }
    }
    if( current_attitude == MATT_IGNORE ||
        ( current_attitude == MATT_FOLLOW && rl_dist( pos(), goal ) <= MONSTER_FOLLOW_DIST ) ) {
        moves -= 100;
        stumble();
        return;
    }
    bool moved = false;
    tripoint destination;
    bool try_to_move = false;
    for( const tripoint &dest : g->m.points_in_radius( pos(), 1 ) ) {
        if( dest != pos() ) {
            if( can_move_to( dest ) && can_squeeze_to( dest ) &&
                g->critter_at( dest, true ) == nullptr ) {
                try_to_move = true;
                break;
            }
        }
    }
    // If true, don't try to greedily avoid locally bad paths
    bool pathed = false;
    if( try_to_move ) {
        if( !wander() ) {
            while( !path.empty() && path.front() == pos() ) {
                path.erase( path.begin() );
            }
            const auto &pf_settings = get_pathfinding_settings();
            if( pf_settings.max_dist >= rl_dist( pos(), goal ) &&
                ( path.empty() || rl_dist( pos(), path.front() ) >= 2 || path.back() != goal ) ) {
                // We need a new path
                path = g->m.route( pos(), goal, pf_settings, get_path_avoid() );
            }
            // Try to respect old paths, even if we can't pathfind at the moment
            if( !path.empty() && path.back() == goal ) {
                destination = path.front();
                moved = true;
                pathed = true;
            } else {
                // Straight line forward, probably because we can't pathfind (well enough)
                destination = goal;
                moved = true;
            }
        }
    }
    if( !moved && has_flag( MF_SMELLS ) ) {
        // No sight... or our plans are invalid (e.g. moving through a transparent, but
        //  solid, square of terrain).  Fall back to smell if we have it.
        unset_dest();
        tripoint tmp = scent_move();
        if( tmp.x != -1 ) {
            destination = tmp;
            moved = true;
        }
    }
    if( wandf > 0 && !moved && friendly == 0 ) { // No LOS, no scent, so as a fall-back follow sound
        unset_dest();
        if( wander_pos != pos() ) {
            destination = wander_pos;
            moved = true;
        }
    }
    if( !g->m.has_zlevels() ) {
        // Otherwise weird things happen
        destination.z = posz();
    }
    point new_d( destination.xy() - pos().xy() );
    // toggle facing direction for sdl flip
    if( !tile_iso ) {
        if( new_d.x < 0 ) {
            facing = FD_LEFT;
        } else if( new_d.x > 0 ) {
            facing = FD_RIGHT;
        }
    } else {
        if( new_d.y <= 0 && new_d.x <= 0 ) {
            facing = FD_LEFT;
        }
        if( new_d.x >= 0 && new_d.y >= 0 ) {
            facing = FD_RIGHT;
        }
    }
    tripoint next_step;
    const bool can_open_doors = has_flag( MF_CAN_OPEN_DOORS );
    const bool staggers = has_flag( MF_STUMBLES );
    if( moved ) {
        // Implement both avoiding obstacles and staggering.
        moved = false;
        float switch_chance = 0.0;
        const bool can_bash = bash_skill() > 0;
        // This is a float and using trig_dist() because that Does the Right Thing(tm)
        // in both circular and roguelike distance modes.
        const float distance_to_target = trig_dist( pos(), destination );
        for( tripoint &candidate : squares_closer_to( pos(), destination ) ) {
            bool via_ramp = false;
            if( here.has_flag( TFLAG_RAMP_UP, candidate ) ) {
                via_ramp = true;
                candidate.z += 1;
            } else if( here.has_flag( TFLAG_RAMP_DOWN, candidate ) ) {
                via_ramp = true;
                candidate.z -= 1;
            }
            tripoint candidate_abs = g->m.getabs( candidate );
            if( candidate.z != posz() ) {
                bool can_z_move = true;
                if( !here.valid_move( pos(), candidate, false, true, via_ramp ) ) {
                    // Can't phase through floor
                    can_z_move = false;
                }
                // If we're trying to go up but can't fly, check if we can climb. If we can't, then don't
                // This prevents non-climb/fly enemies running up walls
                if( candidate.z > posz() && !( via_ramp || flies() ) ) {
                    if( !can_climb() || !here.has_floor_or_support( candidate ) ) {
                        // Can't "jump" up a whole z-level
                        can_z_move = false;
                    }
                }
                // Last chance - we can still do the z-level stair teleport bullshit that isn't removed yet
                // TODO: Remove z-level stair bullshit teleport after aligning all stairs
                if( !can_z_move &&
                    posx() / ( SEEX * 2 ) == candidate.x / ( SEEX * 2 ) &&
                    posy() / ( SEEY * 2 ) == candidate.y / ( SEEY * 2 ) ) {
                    const tripoint &upper = candidate.z > posz() ? candidate : pos();
                    const tripoint &lower = candidate.z > posz() ? pos() : candidate;
                    if( g->m.has_flag( TFLAG_GOES_DOWN, upper ) && g->m.has_flag( TFLAG_GOES_UP, lower ) ) {
                        can_z_move = true;
                    }
                }
                if( !can_z_move ) {
                    continue;
                }
            }
            // A flag to allow non-stumbling critters to stumble when the most direct choice is bad.
            bool bad_choice = false;
            const Creature *target = g->critter_at( candidate, is_hallucination() );
            if( target != nullptr ) {
                const Creature::Attitude att = attitude_to( *target );
                if( att == A_HOSTILE ) {
                    // When attacking an adjacent enemy, we're direct.
                    moved = true;
                    next_step = candidate_abs;
                    break;
                } else if( att == A_FRIENDLY && ( target->is_player() || target->is_npc() ) ) {
                    continue; // Friendly firing the player or an NPC is illegal for gameplay reasons
                } else if( !has_flag( MF_ATTACKMON ) && !has_flag( MF_PUSH_MON ) ) {
                    // Bail out if there's a non-hostile monster in the way and we're not pushy.
                    continue;
                }
                // Friendly fire and pushing are always bad choices - they take a lot of time
                bad_choice = true;
            }
            map &here = g->m;
            // is there an openable door?
            if( can_open_doors &&
                here.open_door( candidate, !here.is_outside( pos() ), true ) ) {
                moved = true;
                next_step = candidate_abs;
                continue;
            }
            // Try to shove vehicle out of the way
            shove_vehicle( destination, candidate );
            // Bail out if we can't move there and we can't bash.
            if( !pathed && ( !can_move_to( candidate ) || !can_squeeze_to( candidate ) ) ) {
                if( !can_bash ) {
                    continue;
                }
                // Don't bash if we're just tracking a noise.
                if( wander() && destination == wander_pos ) {
                    continue;
                }
                const int estimate = here.bash_rating( bash_estimate(), candidate );
                if( estimate <= 0 ) {
                    continue;
                }
                if( estimate < 5 ) {
                    bad_choice = true;
                }
            }
            const float progress = distance_to_target - trig_dist( candidate, destination );
            // The x2 makes the first (and most direct) path twice as likely,
            // since the chance of switching is 1/1, 1/4, 1/6, 1/8
            switch_chance += progress * 2;
            // Randomly pick one of the viable squares to move to weighted by distance.
            if( progress > 0 && ( !moved || x_in_y( progress, switch_chance ) ) ) {
                moved = true;
                next_step = candidate_abs;
                // If we stumble, pick a random square, otherwise take the first one,
                // which is the most direct path.
                // Except if the direct path is bad, then check others
                // Or if the path is given by pathfinder
                if( !staggers && ( !bad_choice || pathed ) ) {
                    break;
                }
            }
        }
    }
    // Finished logic section.  By this point, we should have chosen a square to
    //  move to (moved = true).
    const tripoint local_next_step = g->m.getlocal( next_step );
    if( moved ) { // Actual effects of moving to the square we've chosen
        const bool did_something =
            ( !pacified && attack_at( local_next_step ) ) ||
            ( !pacified && can_open_doors && g->m.open_door( local_next_step, !g->m.is_outside( pos() ) ) ) ||
            ( !pacified && bash_at( local_next_step ) ) ||
            ( !pacified && push_to( local_next_step, 0, 0 ) ) ||
            move_to( local_next_step, false, false, get_stagger_adjust( pos(), destination, local_next_step ) );
        if( !did_something ) {
            moves -= 100; // If we don't do this, we'll get infinite loops.
        }
        if( has_effect( effect_dragging ) && dragged_foe != nullptr ) {
            if( !dragged_foe->has_effect( effect_grabbed ) ) {
                dragged_foe = nullptr;
                remove_effect( effect_dragging );
            } else if( g->m.getlocal( drag_to ) != pos() &&
                       g->critter_at( g->m.getlocal( drag_to ) ) == nullptr ) {
                dragged_foe->setpos( g->m.getlocal( drag_to ) );
            }
        }
    } else {
        moves -= 100;
        stumble();
        path.clear();
    }
    if( has_effect( effect_led_by_leash ) ) {
        if( rl_dist( pos(), g->u.pos() ) > 8 ) {
            // Either failed to keep up with the player or moved away
            remove_effect( effect_led_by_leash );
            add_msg( m_info, _( "You lose hold of a leash." ) );
        }
    }
}
References _, Creature::A_FRIENDLY, Creature::A_HOSTILE, action, behavior::tree::add(), add_msg(), attack_at(), attitude(), attitude_to(), bash_at(), bash_estimate(), map::bash_rating(), bash_skill(), can_climb(), can_move_to(), can_squeeze_to(), mon_special_attack::cooldown, die(), die_if_drowning(), effect_ai_waiting, effect_dragging, effect_grabbed, effect_harnessed, effect_led_by_leash, effect_pacified, effect_stunned, mon_special_attack::enabled, Creature::facing, FD_LEFT, FD_RIGHT, find_dragged_foe(), flies(), friendly, g, mtype::get_goals(), get_map(), get_path_avoid(), get_pathfinding_settings(), get_stagger_adjust(), goal, Creature::has_effect(), map::has_flag(), has_flag(), map::has_floor_or_support(), hp, mtype::hp, mtype::id, is_dead(), is_hallucination(), Creature::is_npc(), map::is_outside(), Creature::is_player(), m_info, MATT_FOLLOW, MATT_IGNORE, MF_ABSORBS_SPLITS, MF_ATTACKMON, MF_CAN_OPEN_DOORS, MF_IMMOBILE, MF_PUSH_MON, MF_RIDEABLE_MECH, MF_SMELLS, MF_STUMBLES, MONSTER_FOLLOW_DIST, move_effects(), move_to(), Creature::moves, name(), nursebot_operate(), one_in(), map::open_door(), path, pos(), posx(), posy(), posz(), push_to(), Creature::remove_effect(), reset_special(), rl_dist(), scent_move(), SEEX, SEEY, Character::setpos(), shove_vehicle(), spawn(), special_attacks, mtype::special_attacks, squares_closer_to(), stumble(), TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_NO_FLOOR, TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, behavior::tree::tick(), tile_iso, trig_dist(), type, unset_dest(), map::valid_move(), wander(), wander_pos, wandf, point::x, tripoint::x, x_in_y(), tripoint::xy(), point::y, and tripoint::z.
move_effects()
bool monster::move_effects (bool attacking) override virtual
Processes effects which may prevent the monster from moving (bear traps, crushed, etc.).
Returns false if movement is stopped.
Implements Creature.
Definition at line 1685 of file monster.cpp.
{
    // This function is relatively expensive, we want that cached
    // IMPORTANT: If adding any new effects here, make SURE to
    // add them to hardcoded_movement_impairing in effect.cpp
    if( !effect_cache[MOVEMENT_IMPAIRED] ) {
        return true;
    }
    bool u_see_me = g->u.sees( *this );
    if( has_effect( effect_tied ) ) {
        // friendly pet, will stay tied down and obey.
        if( friendly == -1 ) {
            return false;
        }
        // non-friendly monster will struggle to get free occasionally.
        // some monsters can't be tangled up with a net/bolas/lasso etc.
        bool immediate_break = type->in_species( FISH ) || type->in_species( MOLLUSK ) ||
                               type->in_species( ROBOT ) || type->bodytype == "snake" || type->bodytype == "blob";
        if( !immediate_break && rng( 0, 900 ) > type->melee_dice * type->melee_sides * 1.5 ) {
            if( u_see_me ) {
                add_msg( _( "The %s struggles to break free of its bonds." ), name() );
            }
        } else if( immediate_break ) {
            remove_effect( effect_tied );
            if( tied_item ) {
                if( u_see_me ) {
                    add_msg( _( "The %s easily slips out of its bonds." ), name() );
                }
                g->m.add_item_or_charges( pos(), *tied_item );
                tied_item.reset();
            }
        } else {
            if( tied_item ) {
                const bool broken = rng( type->melee_dice * type->melee_sides, std::min( 10000,
                                         type->melee_dice * type->melee_sides * 250 ) ) > 800;
                if( !broken ) {
                    g->m.add_item_or_charges( pos(), *tied_item );
                }
                tied_item.reset();
                if( u_see_me ) {
                    if( broken ) {
                        add_msg( _( "The %s snaps the bindings holding it down." ), name() );
                    } else {
                        add_msg( _( "The %s breaks free of the bindings holding it down." ), name() );
                    }
                }
            }
            remove_effect( effect_tied );
        }
        return false;
    }
    if( has_effect( effect_downed ) ) {
        if( rng( 0, 40 ) > type->melee_dice * type->melee_sides * 1.5 ) {
            if( u_see_me ) {
                add_msg( _( "The %s struggles to stand." ), name() );
            }
        } else {
            if( u_see_me ) {
                add_msg( _( "The %s climbs to its feet!" ), name() );
            }
            remove_effect( effect_downed );
        }
        return false;
    }
    if( has_effect( effect_webbed ) ) {
        if( x_in_y( type->melee_dice * type->melee_sides, 6 * get_effect_int( effect_webbed ) ) ) {
            if( u_see_me ) {
                add_msg( _( "The %s breaks free of the webs!" ), name() );
            }
            remove_effect( effect_webbed );
        }
        return false;
    }
    if( has_effect( effect_lightsnare ) ) {
        if( x_in_y( type->melee_dice * type->melee_sides, 12 ) ) {
            remove_effect( effect_lightsnare );
            g->m.spawn_item( pos(), "string_36" );
            g->m.spawn_item( pos(), "snare_trigger" );
            if( u_see_me ) {
                add_msg( _( "The %s escapes the light snare!" ), name() );
            }
        }
        return false;
    }
    if( has_effect( effect_heavysnare ) ) {
        if( type->melee_dice * type->melee_sides >= 7 ) {
            if( x_in_y( type->melee_dice * type->melee_sides, 32 ) ) {
                remove_effect( effect_heavysnare );
                g->m.spawn_item( pos(), "rope_6" );
                g->m.spawn_item( pos(), "snare_trigger" );
                if( u_see_me ) {
                    add_msg( _( "The %s escapes the heavy snare!" ), name() );
                }
            }
        }
        return false;
    }
    if( has_effect( effect_beartrap ) ) {
        if( type->melee_dice * type->melee_sides >= 18 ) {
            if( x_in_y( type->melee_dice * type->melee_sides, 200 ) ) {
                remove_effect( effect_beartrap );
                g->m.spawn_item( pos(), "beartrap" );
                if( u_see_me ) {
                    add_msg( _( "The %s escapes the bear trap!" ), name() );
                }
            }
        }
        return false;
    }
    if( has_effect( effect_crushed ) ) {
        if( x_in_y( type->melee_dice * type->melee_sides, 100 ) ) {
            remove_effect( effect_crushed );
            if( u_see_me ) {
                add_msg( _( "The %s frees itself from the rubble!" ), name() );
            }
        }
        return false;
    }
    // If we ever get more effects that force movement on success this will need to be reworked to
    // only trigger success effects if /all/ rolls succeed
    if( has_effect( effect_in_pit ) ) {
        if( rng( 0, 40 ) > type->melee_dice * type->melee_sides ) {
            return false;
        } else {
            if( u_see_me ) {
                add_msg( _( "The %s escapes the pit!" ), name() );
            }
            remove_effect( effect_in_pit );
        }
    }
    if( has_effect( effect_grabbed ) ) {
        if( dice( type->melee_dice + type->melee_sides, 3 ) < get_effect_int( effect_grabbed ) ||
            !one_in( 4 ) ) {
            return false;
        } else {
            if( u_see_me ) {
                add_msg( _( "The %s breaks free from the grab!" ), name() );
            }
            remove_effect( effect_grabbed );
        }
    }
    return true;
}
References _, add_msg(), mtype::bodytype, broken, dice(), effect_beartrap, effect_cache, effect_crushed, effect_downed, effect_grabbed, effect_heavysnare, effect_in_pit, effect_lightsnare, effect_tied, effect_webbed, FISH, friendly, g, Creature::get_effect_int(), Creature::has_effect(), mtype::in_species(), mtype::melee_dice, mtype::melee_sides, MOLLUSK, MOVEMENT_IMPAIRED, name(), one_in(), pos(), Creature::remove_effect(), rng(), ROBOT, tied_item, type, and x_in_y().
Referenced by leap_actor::call(), and move().
move_special_item_to_inv()
void monster::move_special_item_to_inv (cata::value_ptr< item > & it)
Definition at line 2769 of file monster.cpp.
{
    if( it ) {
        add_item( *it );
        it.reset();
    }
}
References add_item().
Referenced by die().
move_target()
tripoint monster::move_target ()
Definition at line 1008 of file monster.cpp.
{
    return goal;
}
References goal.
Referenced by attack_target(), leap_actor::call(), editmap::uber_draw_ter(), and mattack::vine().
move_to()
bool monster::move_to (const tripoint & p, bool force = false, bool step_on_critter = false, float stagger_adjustment = 1.0)
Attempt to move to p.
If there's something blocking the movement, such as infinite move costs at the target, an existing NPC or monster, this function simply aborts and does nothing.
Parameters
p Destination of movement
force If this is set to true, the movement will happen even if there's currently something, else than a creature, blocking the destination.
step_on_critter If this is set to true, the movement will happen even if there's currently a creature blocking the destination.
stagger_adjustment is a multiplier for move cost to compensate for staggering.
Returns
true if movement successful, false otherwise
Definition at line 1548 of file monmove.cpp.
{
    const bool on_ground = !digging() && !flies();
    const bool z_move = p.z != pos().z;
    const bool going_up = p.z > pos().z;
    tripoint destination = p;
    // This is stair teleportation hackery.
    // TODO: Remove this in favor of stair alignment
    if( going_up ) {
        if( g->m.has_flag( TFLAG_GOES_UP, pos() ) ) {
            destination = find_closest_stair( p, TFLAG_GOES_DOWN );
        }
    } else if( z_move ) {
        if( g->m.has_flag( TFLAG_GOES_DOWN, pos() ) ) {
            destination = find_closest_stair( p, TFLAG_GOES_UP );
        }
    }
    // Allows climbing monsters to move on terrain with movecost <= 0
    Creature *critter = g->critter_at( destination, is_hallucination() );
    if( g->m.has_flag( "CLIMBABLE", destination ) ) {
        if( g->m.impassable( destination ) && critter == nullptr ) {
            if( flies() ) {
                moves -= 100;
                force = true;
                if( g->u.sees( *this ) ) {
                    add_msg( _( "The %1$s flies over the %2$s." ), name(),
                             g->m.has_flag_furn( "CLIMBABLE", p ) ? g->m.furnname( p ) :
                             g->m.tername( p ) );
                }
            } else if( climbs() ) {
                moves -= 150;
                force = true;
                if( g->u.sees( *this ) ) {
                    add_msg( _( "The %1$s climbs over the %2$s." ), name(),
                             g->m.has_flag_furn( "CLIMBABLE", p ) ? g->m.furnname( p ) :
                             g->m.tername( p ) );
                }
            }
        }
    }
    if( critter != nullptr && !step_on_critter ) {
        return false;
    }
    if( !can_squeeze_to( destination ) ) {
        return false;
    }
    // Make sure that we can move there, unless force is true.
    if( !force && !can_move_to( destination ) ) {
        return false;
    }
    if( !force ) {
        // This adjustment is to make it so that monster movement speed relative to the player
        // is consistent even if the monster stumbles,
        // and the same regardless of the distance measurement mode.
        // Note: Keep this as float here or else it will cancel valid moves
        const float cost = stagger_adjustment *
                           static_cast<float>( climbs() &&
                                               g->m.has_flag( TFLAG_NO_FLOOR, p ) ? calc_climb_cost( pos(), destination ) : calc_movecost( pos(),
                                                       destination ) );
        if( cost > 0.0f ) {
            moves -= static_cast<int>( std::ceil( cost ) );
        } else {
            return false;
        }
    }
    //Check for moving into/out of water
    bool was_water = g->m.is_divable( pos() );
    bool will_be_water = on_ground && can_submerge() && g->m.is_divable( destination );
    // Attitude check is kinda slow, better gate it
    if( was_water != will_be_water && !flies() ) {
        if( attitude( &g->u ) != MATT_ATTACK ) {
            // Nothing, no need to spam
        } else if( was_water && !will_be_water && g->u.sees( p ) ) {
            // Use more dramatic messages for swimming monsters
            //~ Message when a monster emerges from water
            //~ %1$s: monster name, %2$s: leaps/emerges, %3$s: terrain name
            add_msg( m_warning, pgettext( "monster movement", "A %1$s %2$s from the %3$s!" ), name(),
                     swims() || has_flag( MF_AQUATIC ) ? _( "leaps" ) : _( "emerges" ),
                     g->m.tername( pos() ) );
        } else if( !was_water && will_be_water && g->u.sees( destination ) ) {
            //~ Message when a monster enters water
            //~ %1$s: monster name, %2$s: dives/sinks, %3$s: terrain name
            add_msg( m_warning, pgettext( "monster movement", "A %1$s %2$s into the %3$s!" ), name(),
                     swims() || has_flag( MF_AQUATIC ) ? _( "dives" ) : _( "sinks" ),
                     g->m.tername( destination ) );
        }
    }
    setpos( destination );
    footsteps( destination );
    set_underwater( will_be_water );
    if( is_hallucination() ) {
        //Hallucinations don't do any of the stuff after this point
        return true;
    }
    if( type->size != MS_TINY && on_ground ) {
        const int sharp_damage = rng( 1, 10 );
        const int rough_damage = rng( 1, 2 );
        if( g->m.has_flag( "SHARP", pos() ) && !one_in( 4 ) &&
            get_armor_cut( bodypart_id( "torso" ) ) < sharp_damage ) {
            apply_damage( nullptr, bodypart_id( "torso" ), sharp_damage );
        }
        if( g->m.has_flag( "ROUGH", pos() ) && one_in( 6 ) &&
            get_armor_cut( bodypart_id( "torso" ) ) < rough_damage ) {
            apply_damage( nullptr, bodypart_id( "torso" ), rough_damage );
        }
    }
    if( g->m.has_flag( "UNSTABLE", destination ) && on_ground ) {
        add_effect( effect_bouldering, 1_turns, num_bp );
    } else if( has_effect( effect_bouldering ) ) {
        remove_effect( effect_bouldering );
    }
    if( g->m.has_flag_ter_or_furn( TFLAG_NO_SIGHT, destination ) && on_ground ) {
        add_effect( effect_no_sight, 1_turns, num_bp );
    } else if( has_effect( effect_no_sight ) ) {
        remove_effect( effect_no_sight );
    }
    g->m.creature_on_trap( *this );
    if( is_dead() ) {
        return true;
    }
    if( !will_be_water && ( digs() || can_dig() ) ) {
        set_underwater( g->m.has_flag( "DIGGABLE", pos() ) );
    }
    // Diggers turn the dirt into dirtmound
    if( digging() && g->m.has_flag( "DIGGABLE", pos() ) ) {
        int factor = 0;
        switch( type->size ) {
            case MS_TINY:
                factor = 100;
                break;
            case MS_SMALL:
                factor = 30;
                break;
            case MS_MEDIUM:
                factor = 6;
                break;
            case MS_LARGE:
                factor = 3;
                break;
            case MS_HUGE:
                factor = 1;
                break;
            default:
                factor = 6;
                break;
        }
        // TODO: make this take terrain type into account so diggers traveling under sand will create mounds of sand etc.
        if( one_in( factor ) ) {
            g->m.ter_set( pos(), t_dirtmound );
        }
    }
    // Acid trail monsters leave... a trail of acid
    if( has_flag( MF_ACIDTRAIL ) ) {
        g->m.add_field( pos(), fd_acid, 3 );
    }
    // Not all acid trail monsters leave as much acid. Every time this monster takes a step, there is a 1/5 chance it will drop a puddle.
    if( has_flag( MF_SHORTACIDTRAIL ) ) {
        if( one_in( 5 ) ) {
            g->m.add_field( pos(), fd_acid, 3 );
        }
    }
    if( has_flag( MF_SLUDGETRAIL ) ) {
        for( const tripoint &sludge_p : g->m.points_in_radius( pos(), 1 ) ) {
            const int fstr = 3 - ( std::abs( sludge_p.x - posx() ) + std::abs( sludge_p.y - posy() ) );
            if( fstr >= 2 ) {
                g->m.add_field( sludge_p, fd_sludge, fstr );
            }
        }
    }
    if( has_flag( MF_DRIPS_NAPALM ) ) {
        if( one_in( 10 ) ) {
            // if it has more napalm, drop some and reduce ammo in tank
            if( ammo[itype_pressurized_tank] > 0 ) {
                g->m.add_item_or_charges( pos(), item( "napalm", calendar::turn, 50 ) );
                ammo[itype_pressurized_tank] -= 50;
            } else {
                // TODO: remove MF_DRIPS_NAPALM flag since no more napalm in tank
                // Not possible for now since flag check is done on type, not individual monster
            }
        }
    }
    if( has_flag( MF_DRIPS_GASOLINE ) ) {
        if( one_in( 5 ) ) {
            // TODO: use same idea that limits napalm dripping
            g->m.add_item_or_charges( pos(), item( "gasoline" ) );
        }
    }
    return true;
}
References _, add_effect(), add_msg(), ammo, apply_damage(), attitude(), calc_climb_cost(), calc_movecost(), can_dig(), can_move_to(), can_squeeze_to(), can_submerge(), climbs(), digging(), digs(), effect_bouldering, effect_no_sight, fd_acid, fd_sludge, find_closest_stair(), flies(), footsteps(), g, get_armor_cut(), Creature::has_effect(), has_flag(), is_dead(), is_hallucination(), itype_pressurized_tank, m_warning, MATT_ATTACK, MF_ACIDTRAIL, MF_AQUATIC, MF_DRIPS_GASOLINE, MF_DRIPS_NAPALM, MF_SHORTACIDTRAIL, MF_SLUDGETRAIL, Creature::moves, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, name(), num_bp, one_in(), pgettext(), pos(), posx(), posy(), Creature::remove_effect(), rng(), Creature::set_underwater(), setpos(), mtype::size, swims(), t_dirtmound, TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_NO_FLOOR, TFLAG_NO_SIGHT, calendar::turn, type, and tripoint::z.
Referenced by mattack::grab_drag(), move(), game::place_player(), monexamine::push(), push_to(), and stumble().
movement_impaired()
bool monster::movement_impaired ()
Returns true if the monster has its movement impaired.
Definition at line 1680 of file monster.cpp.
{
    return effect_cache[MOVEMENT_IMPAIRED];
}
References effect_cache, and MOVEMENT_IMPAIRED.
Referenced by push_to().
name()
std::string monster::name (unsigned int quantity = 1) const
Definition at line 493 of file monster.cpp.
{
    if( !type ) {
        debugmsg( "monster::name empty type!" );
        return std::string();
    }
    if( !unique_name.empty() ) {
        return string_format( "%s: %s", type->nname( quantity ), unique_name );
    }
    return type->nname( quantity );
}
References debugmsg, mtype::nname(), string_format(), type, and unique_name.
Referenced by mattack::absorb_meat(), mdeath::acid(), mattack::acid_barf(), mattack::antqueen(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::bionics_uninstall_failure(), mdeath::blobsplit(), mdeath::boomer(), mattack::boomer(), mdeath::boomer_glow(), mattack::boomer_glow(), mdeath::broken(), mdeath::broken_ammo(), leap_actor::call(), melee_actor::call(), gun_actor::call(), iuse::camera(), iuse::can_goo(), mattack::chickenbot(), mdeath::conflagration(), trapfunc::cot(), trapfunc::crossbow(), mattack::dance(), mdeath::darkman(), mattack::darkman(), mattack::dermatik(), mattack::dermatik_growth(), mdeath::detonate(), die_if_drowning(), game::disable_robot(), mdeath::disappear(), mdeath::disintegrate(), disp_name(), mattack::dogthing(), mattack::doot(), effects_description_for_creature(), iuse::einktabletpc(), explosion_handler::emp_blast(), mattack::evolve_kill_strike(), extended_description(), iuse::extinguisher(), mattack::fear_paralyze(), mdeath::fireball(), mattack::flamethrower(), mattack::flesh_golem(), mattack::flesh_tendril(), game::forced_door_closing(), mattack::frag(), mdeath::fungalburst(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_growth(), mattack::fungus_haze(), mattack::fungus_inject(), mdeath::gameover(), mdeath::gas(), get_name(), mattack::grab(), mattack::grab_drag(), grenade_helper(), mdeath::guilt(), mattack::impale(), mattack::jackson(), mattack::kamikaze(), Creature_tracker::kill_marked_for_death(), knock_back_to(), mattack::longswipe(), mattack::lunge(), make_fake_npc(), make_fungus(), melee_attack(), mdeath::melt(), game::mon_info_update(), mattack::mon_leech_evolution(), move(), avatar_action::move(), move_effects(), move_to(), mattack::multi_robot(), mdeath::normal(), mattack::nurse_assist(), mattack::nurse_operate(), nursebot_operate(), melee_actor::on_damage(), on_load(), photo_def_for_camera_point(), mattack::photograph(), game::place_player(), mattack::plant(), print_info(), process_effects_internal(), process_turn(), mattack::pull_metal_weapon(), push_to(), mattack::ranged_pull(), Creature_tracker::remove(), mattack::resurrect(), mattack::rifle(), mattack::science(), explosion_handler::scrambler_blast(), gun_actor::shoot(), trapfunc::shotgun(), mattack::shriek_alert(), mattack::smash(), mdeath::smokeburst(), mattack::stare(), sting_shoot(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::tankgun(), mattack::taze(), mattack::tentacle(), mattack::tindalos_teleport(), mattack::triffid_growth(), gun_actor::try_target(), Character::uninstall_bionic(), game::update_stair_monsters(), mattack::upgrade(), place_monster_iuse::use(), mattack::vine(), mdeath::worm(), mdefense::zapback(), and mattack::zombie_fuse().
name_with_armor()
std::string monster::name_with_armor () const
Definition at line 506 of file monster.cpp.
{
    std::string ret;
    if( type->in_species( INSECT ) ) {
        ret = _( "carapace" );
    } else if( made_of( material_id( "veggy" ) ) ) {
        ret = _( "thick bark" );
    } else if( made_of( material_id( "bone" ) ) ) {
        ret = _( "exoskeleton" );
    } else if( made_of( material_id( "flesh" ) ) || made_of( material_id( "hflesh" ) ) ||
               made_of( material_id( "iflesh" ) ) ) {
        ret = _( "thick hide" );
    } else if( made_of( material_id( "iron" ) ) || made_of( material_id( "steel" ) ) ) {
        ret = _( "armor plating" );
    } else if( made_of( LIQUID ) ) {
        ret = _( "dense jelly mass" );
    } else {
        ret = _( "armor" );
    }
    if( has_effect( effect_monster_armor ) && !inv.empty() ) {
        for( const item &armor : inv ) {
            if( armor.is_pet_armor( true ) ) {
                ret += string_format( _( "wearing %1$s" ), armor.tname( 1 ) );
                break;
            }
        }
    }
    return ret;
}
References _, effect_monster_armor, Creature::has_effect(), mtype::in_species(), INSECT, inv, LIQUID, made_of(), cata::hash64_detail::ret, string_format(), and type.
Referenced by skin_name().
next_upgrade_time()
int monster::next_upgrade_time () private
Normal upgrades.
Definition at line 312 of file monster.cpp.
{
    if( type->age_grow > 0 ) {
        return type->age_grow;
    }
    const int scaled_half_life = type->half_life * get_option<float>( "MONSTER_UPGRADE_FACTOR" );
    int day = 1; // 1 day of guaranteed evolve time
    for( int i = 0; i < UPGRADE_MAX_ITERS; i++ ) {
        if( one_in( 2 ) ) {
            day += rng( 0, scaled_half_life );
            return day;
        } else {
            day += scaled_half_life;
        }
    }
    // didn't manage to upgrade, shouldn't ever then
    upgrades = false;
    return -1;
}
References mtype::age_grow, day, mtype::half_life, one_in(), rng(), type, UPGRADE_MAX_ITERS, and upgrades.
Referenced by try_upgrade().
normalize_ammo()
void monster::normalize_ammo (int old_ammo) private
Legacy loading logic for monsters that are packing ammo.
Definition at line 2119 of file monster.cpp.
{
    int total_ammo = 0;
    // Sum up the ammo entries to get a ratio.
    for( const auto &ammo_entry : type->starting_ammo ) {
        total_ammo += ammo_entry.second;
    }
    if( total_ammo == 0 ) {
        // Should never happen, but protect us from a div/0 if it does.
        return;
    }
    // Previous code gave robots 100 rounds of ammo.
    // This reassigns whatever is left from that in the appropriate proportions.
    for( const auto &ammo_entry : type->starting_ammo ) {
        ammo[ammo_entry.first] = old_ammo * ammo_entry.second / ( 100 * total_ammo );
    }
}
References ammo, mtype::starting_ammo, and type.
Referenced by load().
nursebot_operate()
void monster::nursebot_operate (player * dragged_foe) private
Definition at line 1111 of file monmove.cpp.
{
    // No dragged foe, nothing to do.
    if( dragged_foe == nullptr ) {
        return;
    }
    // Nothing to do if they can't operate, or they don't think they're dragging.
    if( !( type->has_special_attack( "OPERATE" ) && has_effect( effect_dragging ) ) ) {
        return;
    }
    if( rl_dist( pos(), goal ) == 1 && !g->m.has_flag_furn_or_vpart( flag_AUTODOC_COUCH, goal ) &&
        !has_effect( effect_operating ) ) {
        if( dragged_foe->has_effect( effect_grabbed ) && !has_effect( effect_countdown ) &&
            ( g->critter_at( goal ) == nullptr || g->critter_at( goal ) == dragged_foe ) ) {
            add_msg( m_bad, _( "The %1$s slowly but firmly puts %2$s down onto the autodoc couch." ), name(),
                     dragged_foe->disp_name() );
            dragged_foe->setpos( goal );
            // There's still time to get away
            add_effect( effect_countdown, 2_turns );
            add_msg( m_bad, _( "The %s produces a syringe full of some translucent liquid." ), name() );
        } else if( g->critter_at( goal ) != nullptr && has_effect( effect_dragging ) ) {
            sounds::sound( pos(), 8, sounds::sound_t::electronic_speech,
                           string_format(
                               _( "a soft robotic voice say, \"Please step away from the autodoc, this patient needs immediate care.\"" ) ) );
            // TODO: Make it able to push NPC/player
            push_to( goal, 4, 0 );
        }
    }
    if( get_effect_dur( effect_countdown ) == 1_turns && !has_effect( effect_operating ) ) {
        if( dragged_foe->has_effect( effect_grabbed ) ) {
            const bionic_collection &collec = *dragged_foe->my_bionics;
            const int index = rng( 0, collec.size() - 1 );
            const bionic &target_cbm = collec[index];
            //8 intelligence*4 + 8 first aid*4 + 3 computer *3 + 4 electronic*1 = 77
            const float adjusted_skill = static_cast<float>( 77 ) - std::min( static_cast<float>( 40 ),
                                         static_cast<float>( 77 ) - static_cast<float>( 77 ) / static_cast<float>( 10.0 ) );
            g->u.uninstall_bionic( target_cbm, *this, *dragged_foe, adjusted_skill );
            dragged_foe->remove_effect( effect_grabbed );
            remove_effect( effect_dragging );
            dragged_foe_id = character_id();
        }
    }
}
References _, add_effect(), add_msg(), character_id, Character::disp_name(), dragged_foe_id, effect_countdown, effect_dragging, effect_grabbed, effect_operating, sounds::electronic_speech, flag_AUTODOC_COUCH(), g, Creature::get_effect_dur(), goal, Creature::has_effect(), mtype::has_special_attack(), m_bad, Character::my_bionics, name(), pos(), push_to(), Creature::remove_effect(), rl_dist(), rng(), Character::setpos(), sounds::sound(), string_format(), and type.
Referenced by move().
on_damage_of_type()
void monster::on_damage_of_type (int amt, damage_type dt, const bodypart_id & bp) override virtual
Reimplemented from Creature.
Definition at line 2886 of file monster.cpp.
{
    Creature::on_damage_of_type( amt, dt, bp );
    int full_hp = get_hp_max();
    if( has_effect( effect_grabbing ) && ( dt == DT_BASH || dt == DT_CUT || dt == DT_STAB ) &&
        x_in_y( amt * 10, full_hp ) ) {
        remove_effect( effect_grabbing );
        for( player *p : find_targets_to_ungrab( pos() ) ) {
            p->add_msg_player_or_npc( m_good, _( "The %s flinches, letting you go!" ),
                                      _( "The %s flinches, letting <npcname> go!" ),
                                      disp_name().c_str() );
            p->remove_effect( effect_grabbed );
        }
    }
}
References _, disp_name(), DT_BASH, DT_CUT, DT_STAB, effect_grabbed, effect_grabbing, find_targets_to_ungrab(), get_hp_max(), Creature::has_effect(), m_good, Creature::on_damage_of_type(), pos(), Creature::remove_effect(), and x_in_y().
on_hit()
void monster::on_hit (Creature * source, bodypart_id bp_hit, dealt_projectile_attack const * proj = nullptr) override virtual
This creature just got hit by an attack - possibly special/ranged attack - from source.
Parameters
source Source creature, can be nullptr
proj Source projectile, can be nullptr Players should train dodge, possibly counter-attack somehow.
Implements Creature.
Definition at line 2845 of file monster.cpp.
{
    if( is_hallucination() ) {
        return;
    }
    if( rng( 0, 100 ) <= static_cast<int>( type->def_chance ) ) {
        type->sp_defense( *this, source, proj );
    }
    // Adjust anger/morale of same-species monsters, if appropriate
    int anger_adjust = 0;
    int morale_adjust = 0;
    if( type->has_anger_trigger( mon_trigger::FRIEND_ATTACKED ) ) {
        anger_adjust += 15;
    }
    if( type->has_fear_trigger( mon_trigger::FRIEND_ATTACKED ) ) {
        morale_adjust -= 15;
    }
    if( type->has_placate_trigger( mon_trigger::FRIEND_ATTACKED ) ) {
        anger_adjust -= 15;
    }
    if( anger_adjust != 0 || morale_adjust != 0 ) {
        int light = g->light_level( posz() );
        for( monster &critter : g->all_monsters() ) {
            if( !critter.type->same_species( *type ) ) {
                continue;
            }
            if( g->m.sees( critter.pos(), pos(), light ) ) {
                critter.morale += morale_adjust;
                critter.anger += anger_adjust;
            }
        }
    }
    check_dead_state();
    // TODO: Faction relations
}
References Creature::check_dead_state(), mtype::def_chance, FRIEND_ATTACKED, g, mtype::has_anger_trigger(), mtype::has_fear_trigger(), mtype::has_placate_trigger(), is_hallucination(), light, pos(), posz(), rng(), mtype::sp_defense, and type.
Referenced by deal_projectile_attack().
on_load()
void monster::on_load ()
Retroactively update monster.
Call this after a preexisting monster has been placed on map. Don't call for monsters that have been freshly created, it may cause the monster to upgrade itself into another monster type.
Definition at line 3004 of file monster.cpp.
{
    try_upgrade( false );
    try_reproduce();
    if( has_flag( MF_MILKABLE ) ) {
        refill_udders();
    }
    const time_duration dt = calendar::turn - last_updated;
    last_updated = calendar::turn;
    if( dt <= 0_turns ) {
        return;
    }
    float regen = type->regenerates;
    if( regen <= 0 ) {
        if( has_flag( MF_REVIVES ) ) {
            regen = 1.0f / to_turns<int>( 1_hours );
        } else if( made_of( material_id( "flesh" ) ) || made_of( material_id( "veggy" ) ) ) {
            // Most living stuff here
            regen = 0.25f / to_turns<int>( 1_hours );
        }
    }
    const int heal_amount = roll_remainder( regen * to_turns<int>( dt ) );
    const int healed = heal( heal_amount );
    int healed_speed = 0;
    if( healed < heal_amount && get_speed_base() < type->speed ) {
        int old_speed = get_speed_base();
        set_speed_base( std::min( get_speed_base() + heal_amount - healed, type->speed ) );
        healed_speed = get_speed_base() - old_speed;
    }
    add_msg( m_debug, "on_load() by %s, %d turns, healed %d hp, %d speed",
             name(), to_turns<int>( dt ), healed, healed_speed );
}
References add_msg(), Creature::get_speed_base(), has_flag(), heal(), last_updated, m_debug, made_of(), MF_MILKABLE, MF_REVIVES, name(), refill_udders(), mtype::regenerates, roll_remainder(), Creature::set_speed_base(), mtype::speed, try_reproduce(), try_upgrade(), calendar::turn, and type.
Referenced by map::spawn_monsters_submap(), and map::spawn_monsters_submap_group().
on_unload()
void monster::on_unload ()
Do some cleanup and caching as monster is being unloaded from map.
Definition at line 2999 of file monster.cpp.
{
    last_updated = calendar::turn;
}
References last_updated, and calendar::turn.
Referenced by game::despawn_monster().
operator=() [1/2]
monster & monster::operator= (const monster &) default
operator=() [2/2]
monster & monster::operator= (monster &&) default
plan()
void monster::plan ()
Definition at line 316 of file monmove.cpp.
{
    const auto &factions = g->critter_tracker->factions();
    // Bots are more intelligent than most living stuff
    bool smart_planning = has_flag( MF_PRIORITIZE_TARGETS );
    Creature *target = nullptr;
    int max_sight_range = std::max( type->vision_day, type->vision_night );
    // 8.6f is rating for tank drone 60 tiles away, moose 16 or boomer 33
    float dist = !smart_planning ? max_sight_range : 8.6f;
    bool fleeing = false;
    bool docile = friendly != 0 && has_effect( effect_docile );
    bool waiting = has_effect( effect_ai_waiting );
    const bool angers_hostile_weak = type->has_anger_trigger( mon_trigger::HOSTILE_WEAK );
    const int angers_hostile_near = type->has_anger_trigger( mon_trigger::HOSTILE_CLOSE ) ? 5 : 0;
    const int angers_mating_season = type->has_anger_trigger( mon_trigger::MATING_SEASON ) ? 3 : 0;
    const int angers_cub_threatened = type->has_anger_trigger( mon_trigger::PLAYER_NEAR_BABY ) ? 8 : 0;
    const int fears_hostile_near = type->has_fear_trigger( mon_trigger::HOSTILE_CLOSE ) ? 5 : 0;
    bool group_morale = has_flag( MF_GROUP_MORALE ) && morale < type->morale;
    bool swarms = has_flag( MF_SWARMS );
    auto mood = attitude();
    // If we can see the player, move toward them or flee, simpleminded animals are too dumb to follow the player.
    if( friendly == 0 && sees( g->u ) && !waiting ) {
        dist = rate_target( g->u, dist, smart_planning );
        fleeing = fleeing || is_fleeing( g->u );
        target = &g->u;
        if( dist <= 5 ) {
            anger += angers_hostile_near;
            morale -= fears_hostile_near;
            if( angers_mating_season > 0 ) {
                bool mating_angry = false;
                season_type season = season_of_year( calendar::turn );
                for( auto &elem : type->baby_flags ) {
                    if( ( season == SUMMER && elem == "SUMMER" ) ||
                        ( season == WINTER && elem == "WINTER" ) ||
                        ( season == SPRING && elem == "SPRING" ) ||
                        ( season == AUTUMN && elem == "AUTUMN" ) ) {
                        mating_angry = true;
                        break;
                    }
                }
                if( mating_angry ) {
                    anger += angers_mating_season;
                }
            }
        }
        if( angers_cub_threatened > 0 ) {
            for( monster &tmp : g->all_monsters() ) {
                if( type->baby_monster == tmp.type->id ) {
                    // baby nearby; is the player too close?
                    dist = tmp.rate_target( g->u, dist, smart_planning );
                    if( dist <= 3 ) {
                        //proximity to baby; monster gets furious and less likely to flee
                        anger += angers_cub_threatened;
                        morale += angers_cub_threatened / 2;
                    }
                }
            }
        }
    } else if( friendly != 0 && !docile && !waiting ) {
        for( monster &tmp : g->all_monsters() ) {
            if( tmp.friendly == 0 ) {
                float rating = rate_target( tmp, dist, smart_planning );
                if( rating < dist ) {
                    target = &tmp;
                    dist = rating;
                }
            }
        }
    }
    if( waiting ) {
        set_dest( pos() );
        return;
    }
    if( docile ) {
        if( friendly != 0 && target != nullptr ) {
            set_dest( target->pos() );
        }
        return;
    }
    int valid_targets = ( target == nullptr ) ? 1 : 0;
    for( npc &who : g->all_npcs() ) {
        auto faction_att = faction.obj().attitude( who.get_monster_faction() );
        if( faction_att == MFA_NEUTRAL || faction_att == MFA_FRIENDLY ) {
            continue;
        }
        float rating = rate_target( who, dist, smart_planning );
        bool fleeing_from = is_fleeing( who );
        if( rating == dist && ( fleeing || attitude( &who ) == MATT_ATTACK ) ) {
            ++valid_targets;
            if( one_in( valid_targets ) ) {
                target = &who;
            }
        }
        // Switch targets if closer and hostile or scarier than current target
        if( ( rating < dist && fleeing ) ||
            ( faction_att == MFA_HATE ) ||
            ( rating < dist && attitude( &who ) == MATT_ATTACK ) ||
            ( !fleeing && fleeing_from ) ) {
            target = &who;
            dist = rating;
            valid_targets = 1;
        }
        fleeing = fleeing || fleeing_from;
        if( rating <= 5 ) {
            anger += angers_hostile_near;
            morale -= fears_hostile_near;
            if( angers_mating_season > 0 ) {
                bool mating_angry = false;
                season_type season = season_of_year( calendar::turn );
                for( auto &elem : type->baby_flags ) {
                    if( ( season == SUMMER && elem == "SUMMER" ) ||
                        ( season == WINTER && elem == "WINTER" ) ||
                        ( season == SPRING && elem == "SPRING" ) ||
                        ( season == AUTUMN && elem == "AUTUMN" ) ) {
                        mating_angry = true;
                        break;
                    }
                }
                if( mating_angry ) {
                    anger += angers_mating_season;
                }
            }
        }
    }
    fleeing = fleeing || ( mood == MATT_FLEE );
    if( friendly == 0 ) {
        for( const auto &fac : factions ) {
            auto faction_att = faction.obj().attitude( fac.first );
            if( faction_att == MFA_NEUTRAL || faction_att == MFA_FRIENDLY ) {
                continue;
            }
            for( const weak_ptr_fast<monster> &weak : fac.second ) {
                const shared_ptr_fast<monster> shared = weak.lock();
                if( !shared ) {
                    continue;
                }
                monster &mon = *shared;
                float rating = rate_target( mon, dist, smart_planning );
                if( rating == dist ) {
                    ++valid_targets;
                    if( one_in( valid_targets ) ) {
                        target = &mon;
                    }
                }
                if( rating < dist ) {
                    target = &mon;
                    dist = rating;
                    valid_targets = 1;
                }
                if( rating <= 5 ) {
                    anger += angers_hostile_near;
                    morale -= fears_hostile_near;
                }
            }
        }
    }
    // Friendly monsters here
    // Avoid for hordes of same-faction stuff or it could get expensive
    const auto actual_faction = friendly == 0 ? faction : mfaction_str_id( "player" );
    const auto &myfaction_iter = factions.find( actual_faction );
    if( myfaction_iter == factions.end() ) {
        DebugLog( DL::Error, DC::Game ) << disp_name() << " tried to find faction "
                                        << actual_faction.id().str()
                                        << " which wasn't loaded in game::monmove";
        swarms = false;
        group_morale = false;
    }
    swarms = swarms && target == nullptr; // Only swarm if we have no target
    if( group_morale || swarms ) {
        for( const weak_ptr_fast<monster> &weak : myfaction_iter->second ) {
            const shared_ptr_fast<monster> shared = weak.lock();
            if( !shared ) {
                continue;
            }
            monster &mon = *shared;
            float rating = rate_target( mon, dist, smart_planning );
            if( group_morale && rating <= 10 ) {
                morale += 10 - rating;
            }
            if( swarms ) {
                if( rating < 5 ) { // Too crowded here
                    wander_pos.x = posx() * rng( 1, 3 ) - mon.posx();
                    wander_pos.y = posy() * rng( 1, 3 ) - mon.posy();
                    wandf = 2;
                    target = nullptr;
                    // Swarm to the furthest ally you can see
                } else if( rating < FLT_MAX && rating > dist && wandf <= 0 ) {
                    target = &mon;
                    dist = rating;
                }
            }
        }
    }
    // Operating monster keep you safe while they operate, how nice....
    if( type->has_special_attack( "OPERATE" ) ) {
        int prev_friendlyness = friendly;
        if( has_effect( effect_operating ) ) {
            friendly = 100;
            for( auto critter : g->m.get_creatures_in_radius( pos(), 6 ) ) {
                monster *mon = dynamic_cast<monster *>( critter );
                if( mon != nullptr && mon->type->in_species( ZOMBIE ) ) {
                    anger = 100;
                } else {
                    anger = 0;
                }
            }
        } else {
            friendly = prev_friendlyness;
        }
    }
    if( has_effect( effect_dragging ) ) {
        if( type->has_special_attack( "OPERATE" ) ) {
            bool found_path_to_couch = false;
            tripoint tmp( pos() + point( 12, 12 ) );
            tripoint couch_loc;
            for( const auto &couch_pos : g->m.find_furnitures_or_vparts_with_flag_in_radius( pos(), 10,
                    flag_AUTODOC_COUCH ) ) {
                if( g->m.clear_path( pos(), couch_pos, 10, 0, 100 ) ) {
                    if( rl_dist( pos(), couch_pos ) < rl_dist( pos(), tmp ) ) {
                        tmp = couch_pos;
                        found_path_to_couch = true;
                        couch_loc = couch_pos;
                    }
                }
            }
            if( !found_path_to_couch ) {
                anger = 0;
                remove_effect( effect_dragging );
            } else {
                set_dest( couch_loc );
            }
        }
    } else if( target != nullptr ) {
        tripoint dest = target->pos();
        auto att_to_target = attitude_to( *target );
        if( att_to_target == Attitude::A_HOSTILE && !fleeing ) {
            set_dest( dest );
        } else if( fleeing ) {
            set_dest( tripoint( posx() * 2 - dest.x, posy() * 2 - dest.y, posz() ) );
        }
        if( angers_hostile_weak && att_to_target != Attitude::A_FRIENDLY ) {
            int hp_per = target->hp_percentage();
            if( hp_per <= 70 ) {
                anger += 10 - static_cast<int>( hp_per / 10 );
            }
        }
    } else if( friendly > 0 && one_in( 3 ) ) {
        // Grow restless with no targets
        friendly--;
        // if no target, and friendly pet sees the player
    } else if( friendly < 0 && sees( g->u ) ) {
        // eg dogs
        if( !has_flag( MF_PET_WONT_FOLLOW ) ) {
            // if too far from the player, go to him
            if( rl_dist( pos(), g->u.pos() ) > 2 ) {
                set_dest( g->u.pos() );
            } else {
                unset_dest();
            }
            // eg cows, horses
        } else {
            unset_dest();
        }
        // when the players is close to their pet, it calms them
        // it helps them reach an homeostatic state, for morale and anger
        const int distance_from_friend = rl_dist( pos(), get_avatar().pos() );
        if( distance_from_friend < 12 ) {
            if( one_in( distance_from_friend * 3 ) ) {
                if( morale != type->morale ) {
                    morale += ( morale < type->morale ) ? 1 : -1;
                }
                if( anger != type->agro ) {
                    anger += ( anger < type->agro ) ? 1 : -1;
                }
            }
        }
    }
    // being led by a leash override other movements decisions
    if( has_effect( effect_led_by_leash ) && friendly != 0 ) {
        // if we have an hostile target adjacent to the payer, and we're not fleeing, we can potentially attack it
        if( target != nullptr && rl_dist( g->u.pos(), target->pos() ) < 2 &&
            target->attitude_to( g->u ) == Attitude::A_HOSTILE && !fleeing ) {
            // if we're too far from the player, go back to it
            if( rl_dist( pos(), g->u.pos() ) > 5 ) {
                set_dest( g->u.pos() );
            }
        } else if( rl_dist( pos(), g->u.pos() ) > 1 ) {
            set_dest( g->u.pos() );
        } else {
            unset_dest();
        }
    }
}
References mtype::agro, anger, attitude(), Creature::attitude_to(), attitude_to(), AUTUMN, mtype::baby_flags, mtype::baby_monster, DebugLog, disp_name(), effect_ai_waiting, effect_docile, effect_dragging, effect_led_by_leash, effect_operating, Error, faction, flag_AUTODOC_COUCH(), friendly, g, Game, get_avatar(), mtype::has_anger_trigger(), Creature::has_effect(), mtype::has_fear_trigger(), has_flag(), mtype::has_special_attack(), HOSTILE_CLOSE, HOSTILE_WEAK, Creature::hp_percentage(), mtype::id, mtype::in_species(), is_fleeing(), MATING_SEASON, MATT_ATTACK, MATT_FLEE, MF_GROUP_MORALE, MF_PET_WONT_FOLLOW, MF_PRIORITIZE_TARGETS, MF_SWARMS, MFA_FRIENDLY, MFA_HATE, MFA_NEUTRAL, morale, mtype::morale, one_in(), PLAYER_NEAR_BABY, Creature::pos(), pos(), posx(), posy(), posz(), rate_target(), Creature::remove_effect(), rl_dist(), rng(), season, season_of_year(), Creature::sees(), set_dest(), SPRING, SUMMER, calendar::turn, type, unset_dest(), mtype::vision_day, mtype::vision_night, wander_pos, wandf, WINTER, tripoint::x, tripoint::y, and ZOMBIE.
poly()
void monster::poly (const mtype_id & id)
Definition at line 261 of file monster.cpp.
{
    double hp_percentage = static_cast<double>( hp ) / static_cast<double>( type->hp );
    type = &id.obj();
    moves = 0;
    Creature::set_speed_base( type->speed );
    anger = type->agro;
    morale = type->morale;
    hp = static_cast<int>( hp_percentage * type->hp );
    special_attacks.clear();
    for( auto &sa : type->special_attacks ) {
        auto &entry = special_attacks[sa.first];
        entry.cooldown = sa.second->cooldown;
    }
    faction = type->default_faction;
    upgrades = type->upgrades;
    reproduces = type->reproduces;
}
References mtype::agro, anger, mtype::default_faction, hp, mtype::hp, hp_percentage(), morale, mtype::morale, Creature::moves, reproduces, mtype::reproduces, Creature::set_speed_base(), special_attacks, mtype::special_attacks, mtype::speed, type, upgrades, and mtype::upgrades.
Referenced by mattack::antqueen(), blobify(), iuse::can_goo(), mattack::dermatik_growth(), mattack::dogthing(), mattack::fungus_growth(), trapfunc::goo(), mattack::leech_spawner(), make_fungus(), mattack::mon_leech_evolution(), poly_keep_speed(), mattack::triffid_growth(), and try_upgrade().
pos()
const tripoint & monster::pos () const override virtual
Implements Creature.
Definition at line 256 of file monster.cpp.
{
    return position;
}
References position.
Referenced by mattack::absorb_meat(), mdeath::acid(), mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), Creature_tracker::add(), mdeath::amigara(), mattack::antqueen(), mdeath::blobsplit(), mdeath::boomer(), mattack::boomer(), mdeath::boomer_glow(), mattack::boomer_glow(), mattack::breathe(), mdeath::broken(), mdeath::broken_ammo(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), mattack::callblobs(), Character::can_mount(), can_reach_to(), can_squeeze_to(), mattack::check_money_left(), mattack::chickenbot(), mdeath::conflagration(), mattack::copbot(), mattack::darkman(), monexamine::deactivate_pet(), overmapbuffer::despawn_monster(), mdeath::detonate(), die(), mattack::dogthing(), mattack::doot(), vehicle::drive_to_local_target(), drop_items_on_death(), mattack::eat_crop(), mattack::eat_food(), mdeath::explode(), activity_handlers::find_mount_do_turn(), find_target_vehicle(), mdeath::fireball(), mattack::flame(), mattack::flesh_golem(), mattack::flesh_tendril(), mdeath::focused_beam(), mattack::formblob(), mattack::frag(), mattack::fungal_trail(), mdeath::fungalburst(), mdeath::fungus(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), mdeath::gas(), mattack::generator(), monexamine::give_items_to(), mattack::grab_drag(), group_bash_skill(), mattack::grow_vine(), mattack::growplants(), mdeath::guilt(), game::handle_action(), mattack::howl(), is_adjacent(), is_fleeing(), behavior::monster_oracle_t::items_available(), mattack::jackson(), mattack::kamikaze(), Creature_tracker::kill_marked_for_death(), mdeath::kill_vines(), knock_back_to(), mattack::leech_spawner(), load(), mattack::longswipe(), mattack::lunge(), make_fake_npc(), make_fungus(), make_mon_corpse(), melee_attack(), monexamine::milk_source(), game::mon_info_update(), mattack::mon_leech_evolution(), map::monster_in_field(), Character::mount_creature(), move(), move_effects(), move_to(), mattack::multi_robot(), mdeath::normal(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), nursebot_operate(), melee_actor::on_damage(), on_damage_of_type(), on_hit(), mattack::parrot(), mattack::photograph(), game::place_player(), plan(), mattack::plant(), mdeath::preg_roach(), process_effects_internal(), process_item_valptr(), process_items(), process_triggers(), process_turn(), mattack::pull_metal_weapon(), push_to(), mattack::ranged_pull(), rate_target(), mdeath::ratking(), mattack::ratking(), mattack::rattle(), monexamine::remove_armor(), Creature_tracker::remove_from_location_map(), mattack::resurrect(), mdefense::return_fire(), mattack::rifle(), mattack::riotbot(), iuse::robotcontrol_can_target(), scatter_chunks(), scent_move(), mattack::science(), mattack::searchlight(), setpos(), monexamine::shear_animal(), mattack::shockstorm(), gun_actor::shoot(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::slimespring(), mattack::smash(), mdeath::smokeburst(), mattack::spit_sap(), mdeath::splatter(), stash_on_pet(), sting_get_target(), sting_shoot(), store(), mattack::stretch_attack(), mattack::stretch_bite(), stumble(), Creature_tracker::swap_positions(), mattack::tankgun(), mattack::tentacle(), mdeath::thing(), mattack::tindalos_teleport(), mattack::triffid_heartbeat(), try_reproduce(), gun_actor::try_target(), turns_to_reach(), editmap::uber_draw_ter(), unset_dest(), Creature_tracker::update_pos(), place_monster_iuse::use(), use_mech_power(), mattack::vine(), mdeath::vine_cut(), wander(), will_join_horde(), will_reach(), within_target_range(), within_visual_range(), mdeath::worm(), and mattack::zombie_fuse().
posx()
int monster::posx () const inline override virtual
Implements Creature.
Definition at line 494 of file monster.h.
{
            return position.x;
        }
References position, and tripoint::x.
Referenced by mdeath::focused_beam(), hear_sound(), move(), move_to(), plan(), monexamine::push(), mattack::searchlight(), stumble(), mattack::triffid_heartbeat(), game::update_stair_monsters(), and will_reach().
posy()
int monster::posy () const inline override virtual
Implements Creature.
Definition at line 497 of file monster.h.
{
            return position.y;
        }
References position, and tripoint::y.
Referenced by mdeath::focused_beam(), hear_sound(), move(), move_to(), plan(), monexamine::push(), mattack::searchlight(), stumble(), mattack::triffid_heartbeat(), game::update_stair_monsters(), and will_reach().
posz()
int monster::posz () const inline override virtual
Implements Creature.
Definition at line 500 of file monster.h.
{
            return position.z;
        }
References position, and tripoint::z.
Referenced by attack_at(), bash_at(), die(), mattack::flame(), mdeath::focused_beam(), hear_sound(), is_adjacent(), move(), on_hit(), plan(), monexamine::push(), mattack::ratking(), scent_move(), mattack::searchlight(), mattack::shriek_stun(), stumble(), mattack::triffid_heartbeat(), turns_to_reach(), and will_reach().
power_rating()
float monster::power_rating () const override virtual
Returns an approximation of the creature's strength.
Implements Creature.
Definition at line 2824 of file monster.cpp.
{
    float ret = get_size() - 1; // Zed gets 1, cat -1, hulk 3
    ret += has_flag( MF_ELECTRONIC ) ? 2 : 0; // Robots tend to have guns
    // Hostile stuff gets a big boost
    // Neutral moose will still get burned if it comes close
    return ret;
}
References get_size(), has_flag(), MF_ELECTRONIC, and cata::hash64_detail::ret.
print_info()
int monster::print_info (const catacurses::window & w, int vStart, int vLines, int column) const override virtual
Write information about this creature.
Parameters
w the window to print the text into.
vStart vertical start to print, that means the first line to print.
vLines number of lines to print at most (printing less is fine).
column horizontal start to print (column), horizontal end is one character before the right border of the window (to keep the border).
Returns
The line just behind the last printed line, that means multiple calls to this can be stacked, the return value is acceptable as vStart for the next call without creating empty lines or overwriting lines.
Implements Creature.
Definition at line 638 of file monster.cpp.
{
    const int vEnd = vStart + vLines;
    mvwprintz( w, point( column, vStart ), basic_symbol_color(), name() );
    wprintw( w, " " );
    const auto att = get_attitude();
    wprintz( w, att.second, att.first );
    if( debug_mode ) {
        wprintz( w, c_light_gray, _( " Difficulty " ) + std::to_string( type->difficulty ) );
    }
    if( display_mod_source ) {
        const std::string mod_src = enumerate_as_string( type->src.begin(),
        type->src.end(), []( const std::pair<mtype_id, mod_id> &source ) {
            return string_format( "'%s'", source.second->name() );
        }, enumeration_conjunction::arrow );
        vStart += fold_and_print( w, point( column, vStart + 1 ), getmaxx( w ) - 2, c_cyan,
                                  string_format( _( "Origin: %s" ), mod_src ) );
    }
    if( sees( g->u ) ) {
        mvwprintz( w, point( column, ++vStart ), c_yellow, _( "Aware of your presence!" ) );
    }
    const auto speed_desc = speed_description( speed_rating(), has_flag( MF_IMMOBILE ) );
    mvwprintz( w, point( column, ++vStart ), speed_desc.second, speed_desc.first );
    std::string effects = get_effect_status();
    if( !effects.empty() ) {
        trim_and_print( w, point( column, ++vStart ), getmaxx( w ) - 2, h_white, effects );
    }
    const auto hp_desc = hp_description( hp, type->hp );
    mvwprintz( w, point( column, ++vStart ), hp_desc.second, hp_desc.first );
    if( has_effect( effect_ridden ) && mounted_player ) {
        mvwprintz( w, point( column, ++vStart ), c_white, _( "Rider: %s" ), mounted_player->disp_name() );
    }
    std::vector<std::string> lines = foldstring( type->get_description(), getmaxx( w ) - 1 - column );
    int numlines = lines.size();
    for( int i = 0; i < numlines && vStart <= vEnd; i++ ) {
        mvwprintz( w, point( column, ++vStart ), c_white, lines[i] );
    }
    return vStart;
}
References _, arrow, basic_symbol_color(), c_cyan, c_light_gray, c_white, c_yellow, debug_mode, mtype::difficulty, Character::disp_name(), display_mod_source, effect_ridden, Creature::effects, enumerate_as_string(), fold_and_print(), foldstring(), g, get_attitude(), mtype::get_description(), get_effect_status(), catacurses::getmaxx(), h_white, Creature::has_effect(), has_flag(), hp, mtype::hp, hp_description(), MF_IMMOBILE, mounted_player, mvwprintz(), name(), Creature::sees(), speed_description(), speed_rating(), mtype::src, string_format(), to_string(), trim_and_print(), type, catacurses::wprintw(), and wprintz().
Referenced by wish_monster_callback::refresh().
process_effects_internal()
void monster::process_effects_internal () override virtual
Processes monster-specific effects before calling Creature::process_effects().
Implements Creature.
Definition at line 2534 of file monster.cpp.
{
    // Monster only effects
    for( auto &elem : *effects ) {
        for( auto &_effect_it : elem.second ) {
            if( !_effect_it.second.is_removed() ) {
                process_one_effect( _effect_it.second, false );
            }
        }
    }
    // Like with player/NPCs - keep the speed above 0
    const int min_speed_bonus = -0.75 * get_speed_base();
    if( get_speed_bonus() < min_speed_bonus ) {
        set_speed_bonus( min_speed_bonus );
    }
    //If this monster has the ability to heal in combat, do it now.
    int regeneration_amount = type->regenerates;
    float regen_multiplier = 0;
    //Apply effect-triggered regeneration modifiers
    for( const auto &regeneration_modifier : type->regeneration_modifiers ) {
        if( has_effect( regeneration_modifier.first ) ) {
            effect &e = get_effect( regeneration_modifier.first );
            regen_multiplier = 1.00 + regeneration_modifier.second.base_modifier +
                               ( e.get_intensity() - 1 ) * regeneration_modifier.second.scale_modifier;
            regeneration_amount = round( regeneration_amount * regen_multiplier );
        }
    }
    //Prevent negative regeneration
    if( regeneration_amount < 0 ) {
        regeneration_amount = 0;
    }
    const int healed_amount = heal( round( regeneration_amount ) );
    if( healed_amount > 0 && one_in( 2 ) && g->u.sees( *this ) ) {
        add_msg( m_debug, ( "Regen: %s" ), healed_amount );
        std::string healing_format_string;
        if( healed_amount >= 50 ) {
            healing_format_string = _( "The %s is visibly regenerating!" );
        } else if( healed_amount >= 10 ) {
            healing_format_string = _( "The %s seems a little healthier." );
        } else {
            healing_format_string = _( "The %s is healing slowly." );
        }
        add_msg( m_warning, healing_format_string, name() );
    }
    if( type->regenerates_in_dark ) {
        const float light = g->m.ambient_light_at( pos() );
        // Magic number 10000 was chosen so that a floodlight prevents regeneration in a range of 20 tiles
        if( heal( static_cast<int>( 50.0 *  std::exp( - light * light / 10000 ) )  > 0 && one_in( 2 ) &&
                  g->u.sees( *this ) ) ) {
            add_msg( m_warning, _( "The %s uses the darkness to regenerate." ), name() );
        }
    }
    // Monster will regen morale and aggression if it is on max HP
    // It regens more morale and aggression if is currently fleeing.
    if( type->regen_morale && hp >= type->hp ) {
        if( is_fleeing( g->u ) ) {
            morale = type->morale;
            anger = type->agro;
        }
        if( morale <= type->morale ) {
            morale += 1;
        }
        if( anger <= type->agro ) {
            anger += 1;
        }
        if( morale < 0 ) {
            morale += 5;
        }
        if( anger < 0 ) {
            anger += 5;
        }
    }
    // If this critter dies in sunlight, check & assess damage.
    if( has_flag( MF_SUNDEATH ) && g->is_in_sunlight( pos() ) ) {
        if( g->u.sees( *this ) ) {
            add_msg( m_good, _( "The %s burns horribly in the sunlight!" ), name() );
        }
        apply_damage( nullptr, bodypart_id( "torso" ), 100 );
        if( hp < 0 ) {
            hp = 0;
        }
    }
}
References _, add_msg(), mtype::agro, anger, apply_damage(), Creature::effects, g, Creature::get_effect(), effect::get_intensity(), Creature::get_speed_base(), Creature::get_speed_bonus(), Creature::has_effect(), has_flag(), heal(), hp, mtype::hp, is_fleeing(), light, m_debug, m_good, m_warning, MF_SUNDEATH, morale, mtype::morale, name(), one_in(), pos(), process_one_effect(), mtype::regen_morale, mtype::regenerates, mtype::regenerates_in_dark, mtype::regeneration_modifiers, Creature::set_speed_bonus(), and type.
process_items()
void monster::process_items ()
Definition at line 2430 of file monster.cpp.
{
    for( auto iter = inv.begin(); iter != inv.end(); ) {
        if( iter->needs_processing() &&
            iter->process( nullptr, pos(), false )
          ) {
            iter = inv.erase( iter );
            continue;
        }
        iter++;
    }
    process_item_valptr( storage_item, *this );
    process_item_valptr( armor_item, *this );
    process_item_valptr( tack_item, *this );
    process_item_valptr( tied_item, *this );
}
References armor_item, inv, pos(), process_item_valptr(), storage_item, tack_item, and tied_item.
process_one_effect()
void monster::process_one_effect (effect & it, bool is_new) override protected virtual
Processes monster-specific effects of an effect.
Implements Creature.
Definition at line 2488 of file monster.cpp.
{
    // Monsters don't get trait-based reduction, but they do get effect based reduction
    bool reduced = resists_effect( it );
    const auto get_effect = [&it, is_new]( const std::string & arg, bool reduced ) {
        if( is_new ) {
            return it.get_amount( arg, reduced );
        }
        return it.get_mod( arg, reduced );
    };
    mod_speed_bonus( get_effect( "SPEED", reduced ) );
    mod_dodge_bonus( get_effect( "DODGE", reduced ) );
    int val = get_effect( "HURT", reduced );
    if( val > 0 ) {
        if( is_new || it.activated( calendar::turn, "HURT", val, reduced, 1 ) ) {
            apply_damage( nullptr, bodypart_id( "torso" ), val );
        }
    }
    const efftype_id &id = it.get_id();
    // TODO: MATERIALS use fire resistance
    if( it.impairs_movement() ) {
        effect_cache[MOVEMENT_IMPAIRED] = true;
    } else if( id == effect_onfire ) {
        int dam = 0;
        if( made_of( material_id( "veggy" ) ) ) {
            dam = rng( 10, 20 );
        } else if( made_of( material_id( "flesh" ) ) || made_of( material_id( "iflesh" ) ) ) {
            dam = rng( 5, 10 );
        }
        dam -= get_armor_type( DT_HEAT, bodypart_id( "torso" ) );
        if( dam > 0 ) {
            apply_damage( nullptr, bodypart_id( "torso" ), dam );
        } else {
            it.set_duration( 0_turns );
        }
    } else if( id == effect_run ) {
        effect_cache[FLEEING] = true;
    } else if( id == effect_no_sight || id == effect_blind ) {
        effect_cache[VISION_IMPAIRED] = true;
    }
}
References effect::activated(), apply_damage(), arg(), DT_HEAT, effect_blind, effect_cache, effect_no_sight, effect_onfire, effect_run, FLEEING, effect::get_amount(), get_armor_type(), Creature::get_effect(), effect::get_id(), effect::get_mod(), effect::impairs_movement(), made_of(), Creature::mod_dodge_bonus(), Creature::mod_speed_bonus(), MOVEMENT_IMPAIRED, Creature::resists_effect(), rng(), effect::set_duration(), calendar::turn, and VISION_IMPAIRED.
Referenced by process_effects_internal().
process_trigger() [1/2]
void monster::process_trigger (mon_trigger trig, const std::function< int()> & amount_func) private
Definition at line 1265 of file monster.cpp.
{
    if( type->has_anger_trigger( trig ) ) {
        anger += amount_func();
    }
    if( type->has_fear_trigger( trig ) ) {
        morale -= amount_func();
    }
    if( type->has_placate_trigger( trig ) ) {
        anger -= amount_func();
    }
}
References anger, mtype::has_anger_trigger(), mtype::has_fear_trigger(), mtype::has_placate_trigger(), morale, and type.
process_trigger() [2/2]
void monster::process_trigger (mon_trigger trig, int amount) private
Definition at line 1252 of file monster.cpp.
{
    if( type->has_anger_trigger( trig ) ) {
        anger += amount;
    }
    if( type->has_fear_trigger( trig ) ) {
        morale -= amount;
    }
    if( type->has_placate_trigger( trig ) ) {
        anger -= amount;
    }
}
References anger, mtype::has_anger_trigger(), mtype::has_fear_trigger(), mtype::has_placate_trigger(), morale, and type.
Referenced by apply_damage(), hear_sound(), and process_triggers().
process_triggers()
void monster::process_triggers ()
Definition at line 1212 of file monster.cpp.
{
    process_trigger( mon_trigger::STALK, [this]() {
        return anger > 0 && one_in( 5 ) ? 1 : 0;
    } );
    process_trigger( mon_trigger::FIRE, [this]() {
        int ret = 0;
        for( const auto &p : g->m.points_in_radius( pos(), 3 ) ) {
            ret += 5 * g->m.get_field_intensity( p, fd_fire );
        }
        return ret;
    } );
    // Meat checking is disabled as for now.
    // It's hard to ever see it in action
    // and even harder to balance it without making it exploitable
    if( morale != type->morale && one_in( 10 ) ) {
        if( morale < type->morale ) {
            morale++;
        } else {
            morale--;
        }
    }
    if( anger != type->agro && one_in( 10 ) ) {
        if( anger < type->agro ) {
            anger++;
        } else {
            anger--;
        }
    }
    // Cap values at [-100, 100] to prevent perma-angry moose etc.
    morale = std::min( 100, std::max( -100, morale ) );
    anger  = std::min( 100, std::max( -100, anger ) );
}
References mtype::agro, anger, fd_fire, FIRE, g, morale, mtype::morale, one_in(), pos(), process_trigger(), cata::hash64_detail::ret, STALK, and type.
Referenced by game::place_player().
process_turn()
void monster::process_turn () override virtual
Processes effects and bonuses and allocates move points based on speed.
Reimplemented from Creature.
Definition at line 2161 of file monster.cpp.
{
    decrement_summon_timer();
    if( !is_hallucination() ) {
        for( const std::pair<const emit_id, time_duration> &e : type->emit_fields ) {
            if( !calendar::once_every( e.second ) ) {
                continue;
            }
            const emit_id emid = e.first;
            if( emid == emit_id( "emit_shock_cloud" ) ) {
                if( has_effect( effect_emp ) ) {
                    continue; // don't emit electricity while EMPed
                } else if( has_effect( effect_supercharged ) ) {
                    g->m.emit_field( pos(), emit_id( "emit_shock_cloud_big" ) );
                    continue;
                }
            }
            g->m.emit_field( pos(), emid );
        }
    }
    // Special attack cooldowns are updated here.
    // Loop through the monster's special attacks, same as monster::move.
    for( const auto &sp_type : type->special_attacks ) {
        const std::string &special_name = sp_type.first;
        const auto local_iter = special_attacks.find( special_name );
        if( local_iter == special_attacks.end() ) {
            continue;
        }
        mon_special_attack &local_attack_data = local_iter->second;
        if( !local_attack_data.enabled ) {
            continue;
        }
        if( local_attack_data.cooldown > 0 ) {
            local_attack_data.cooldown--;
        }
    }
    // Persist grabs as long as there's an adjacent target.
    if( has_effect( effect_grabbing ) ) {
        for( auto &dest : g->m.points_in_radius( pos(), 1, 0 ) ) {
            const player *const p = g->critter_at<player>( dest );
            if( p && p->has_effect( effect_grabbed ) ) {
                add_effect( effect_grabbing, 2_turns );
            }
        }
    }
    // We update electrical fields here since they act every turn.
    if( has_flag( MF_ELECTRIC_FIELD ) ) {
        if( has_effect( effect_emp ) ) {
            if( calendar::once_every( 10_turns ) ) {
                sounds::sound( pos(), 5, sounds::sound_t::combat, _( "hummmmm." ), false, "humming", "electric" );
            }
        } else {
            for( const tripoint &zap : g->m.points_in_radius( pos(), 1 ) ) {
                const bool player_sees = g->u.sees( zap );
                const auto items = g->m.i_at( zap );
                for( const auto &item : items ) {
                    if( item.made_of( LIQUID ) && item.flammable() ) { // start a fire!
                        g->m.add_field( zap, fd_fire, 2, 1_minutes );
                        sounds::sound( pos(), 30, sounds::sound_t::combat,  _( "fwoosh!" ), false, "fire", "ignition" );
                        break;
                    }
                }
                if( zap != pos() ) {
                    explosion_handler::emp_blast( zap ); // Fries electronics due to the intensity of the field
                }
                const auto t = g->m.ter( zap );
                if( t == ter_str_id( "t_gas_pump" ) || t == ter_str_id( "t_gas_pump_a" ) ) {
                    if( one_in( 4 ) ) {
                        explosion_handler::explosion( pos(), nullptr, 40, 0.8, true );
                        if( player_sees ) {
                            add_msg( m_warning, _( "The %s explodes in a fiery inferno!" ), g->m.tername( zap ) );
                        }
                    } else {
                        if( player_sees ) {
                            add_msg( m_warning, _( "Lightning from %1$s engulfs the %2$s!" ), name(),
                                     g->m.tername( zap ) );
                        }
                        g->m.add_field( zap, fd_fire, 1, 2_turns );
                    }
                }
            }
            if( get_weather().lightning_active && !has_effect( effect_supercharged ) &&
                g->m.is_outside( pos() ) ) {
                get_weather().lightning_active = false; // only one supercharge per strike
                sounds::sound( pos(), 300, sounds::sound_t::combat, _( "BOOOOOOOM!!!" ), false, "environment",
                               "thunder_near" );
                sounds::sound( pos(), 20, sounds::sound_t::combat, _( "vrrrRRRUUMMMMMMMM!" ), false, "explosion",
                               "default" );
                if( g->u.sees( pos() ) ) {
                    add_msg( m_bad, _( "Lightning strikes the %s!" ), name() );
                    add_msg( m_bad, _( "Your vision goes white!" ) );
                    g->u.add_effect( effect_blind, rng( 1_minutes, 2_minutes ) );
                }
                add_effect( effect_supercharged, 12_hours );
            } else if( has_effect( effect_supercharged ) && calendar::once_every( 5_turns ) ) {
                sounds::sound( pos(), 20, sounds::sound_t::combat, _( "VMMMMMMMMM!" ), false, "humming",
                               "electric" );
            }
        }
    }
    Creature::process_turn();
}
References _, add_effect(), add_msg(), sounds::combat, mon_special_attack::cooldown, decrement_summon_timer(), effect_blind, effect_emp, effect_grabbed, effect_grabbing, effect_supercharged, mtype::emit_fields, explosion_handler::emp_blast(), mon_special_attack::enabled, explosion_handler::explosion(), fd_fire, item::flammable(), g, get_weather(), Creature::has_effect(), has_flag(), is_hallucination(), weather_manager::lightning_active, LIQUID, m_bad, m_warning, item::made_of(), MF_ELECTRIC_FIELD, name(), calendar::once_every(), one_in(), pos(), Creature::process_turn(), rng(), sounds::sound(), special_attacks, mtype::special_attacks, and type.
push_to()
bool monster::push_to (const tripoint & p, int boost, size_t depth)
Try to push away whatever occupies p, then step in.
May recurse and try to make the creature at p push further.
Parameters
p Location of pushed object
boost A bonus on the roll to represent a horde pushing from behind
depth Number of recursions so far
Returns
True if we managed to push something and took its place, false otherwise.
Definition at line 1757 of file monmove.cpp.
{
    if( is_hallucination() ) {
        // Don't let hallucinations push, not even other hallucinations
        return false;
    }
    if( !has_flag( MF_PUSH_MON ) || depth > 2 || has_effect( effect_pushed ) ) {
        return false;
    }
    // TODO: Generalize this to Creature
    monster *const critter = g->critter_at<monster>( p );
    if( critter == nullptr || critter == this ||
        p == pos() || critter->movement_impaired() ) {
        return false;
    }
    if( !can_move_to( p ) ) {
        return false;
    }
    if( critter->is_hallucination() ) {
        // Kill the hallu, but return false so that the regular move_to is uses instead
        critter->die( nullptr );
        return false;
    }
    // Stability roll of the pushed critter
    const int defend = critter->stability_roll();
    // Stability roll of the pushing zed
    const int attack = stability_roll() + boost;
    if( defend > attack ) {
        return false;
    }
    const int movecost_from = 50 * g->m.move_cost( p );
    const int movecost_attacker = std::max( movecost_from, 200 - 10 * ( attack - defend ) );
    const tripoint dir = p - pos();
    // Mark self as pushed to simplify recursive pushing
    add_effect( effect_pushed, 1_turns );
    for( size_t i = 0; i < 6; i++ ) {
        const point d{ rng( -1, 1 ), rng( -1, 1 ) };
        if( d.x == 0 && d.y == 0 ) {
            continue;
        }
        // Pushing forward is easier than pushing aside
        const int direction_penalty = std::abs( d.x - dir.x ) + std::abs( d.y - dir.y );
        if( direction_penalty > 2 ) {
            continue;
        }
        tripoint dest( p + d );
        const int dest_movecost_from = 50 * g->m.move_cost( dest );
        // Pushing into cars/windows etc. is harder
        const int movecost_penalty = g->m.move_cost( dest ) - 2;
        if( movecost_penalty <= -2 || get_map().obstructed_by_vehicle_rotation( p, dest ) ) {
            // Can't push into unpassable terrain
            continue;
        }
        int roll = attack - ( defend + direction_penalty + movecost_penalty );
        if( roll < 0 ) {
            continue;
        }
        Creature *critter_recur = g->critter_at( dest );
        if( !( critter_recur == nullptr || critter_recur->is_hallucination() ) ) {
            // Try to push recursively
            monster *mon_recur = dynamic_cast< monster * >( critter_recur );
            if( mon_recur == nullptr ) {
                continue;
            }
            if( critter->push_to( dest, roll, depth + 1 ) ) {
                // The tile isn't necessarily free, need to check
                if( !g->critter_at( p ) ) {
                    move_to( p );
                }
                moves -= movecost_attacker;
                // Don't knock down a creature that successfully
                // pushed another creature, just reduce moves
                critter->moves -= dest_movecost_from;
                return true;
            } else {
                return false;
            }
        }
        critter_recur = g->critter_at( dest );
        if( critter_recur != nullptr ) {
            if( critter_recur->is_hallucination() ) {
                critter_recur->die( nullptr );
            }
        } else if( !critter->has_flag( MF_IMMOBILE ) ) {
            critter->setpos( dest );
            move_to( p );
            moves -= movecost_attacker;
            critter->add_effect( effect_downed, time_duration::from_turns( movecost_from / 100 + 1 ) );
        }
        return true;
    }
    // Try to trample over a much weaker zed (or one with worse rolls)
    // Don't allow trampling with boost
    if( boost > 0 || attack < 2 * defend ) {
        return false;
    }
    g->swap_critters( *critter, *this );
    critter->add_effect( effect_stunned, rng( 0_turns, 2_turns ) );
    // Only print the message when near player or it can get spammy
    if( rl_dist( g->u.pos(), pos() ) < 4 && g->u.sees( *critter ) ) {
        add_msg( m_warning, _( "The %1$s tramples %2$s" ),
                 name(), critter->disp_name() );
    }
    moves -= movecost_attacker;
    if( movecost_from > 100 ) {
        critter->add_effect( effect_downed, time_duration::from_turns( movecost_from / 100 + 1 ) );
    } else {
        critter->moves -= movecost_from;
    }
    return true;
}
References _, add_effect(), add_msg(), can_move_to(), die(), Creature::die(), disp_name(), effect_downed, effect_pushed, effect_stunned, time_duration::from_turns(), g, get_map(), Creature::has_effect(), has_flag(), Creature::is_hallucination(), is_hallucination(), m_warning, MF_IMMOBILE, MF_PUSH_MON, move_to(), movement_impaired(), Creature::moves, name(), pos(), push_to(), rl_dist(), rng(), setpos(), stability_roll(), tripoint::x, and tripoint::y.
Referenced by move(), mattack::nurse_operate(), nursebot_operate(), and push_to().
rate_target()
float monster::rate_target (Creature & c, float best, bool smart = false) const
Definition at line 282 of file monmove.cpp.
{
    const auto d = rl_dist_fast( pos(), c.pos() );
    if( d <= 0 ) {
        return FLT_MAX;
    }
    // Check a very common and cheap case first
    if( !smart && d >= best ) {
        return FLT_MAX;
    }
    if( !sees( c ) ) {
        return FLT_MAX;
    }
    if( !smart ) {
        return int( d );
    }
    float power = c.power_rating();
    monster *mon = dynamic_cast< monster * >( &c );
    // Their attitude to us and not ours to them, so that bobcats won't get gunned down
    if( mon != nullptr && mon->attitude_to( *this ) == Attitude::A_HOSTILE ) {
        power += 2;
    }
    if( power > 0 ) {
        return int( d ) / power;
    }
    return FLT_MAX;
}
References attitude_to(), c, pos(), rl_dist_fast(), and Creature::sees().
Referenced by plan().
refill_udders()
void monster::refill_udders ()
Definition at line 450 of file monster.cpp.
{
    if( type->starting_ammo.empty() ) {
        debugmsg( "monster %s has no starting ammo to refill udders", get_name() );
        return;
    }
    if( ammo.empty() ) {
        // legacy animals got empty ammo map, fill them up now if needed.
        ammo[type->starting_ammo.begin()->first] = type->starting_ammo.begin()->second;
    }
    auto current_milk = ammo.find( itype_milk_raw );
    if( current_milk == ammo.end() ) {
        current_milk = ammo.find( itype_milk );
        if( current_milk != ammo.end() ) {
            // take this opportunity to update milk udders to raw_milk
            ammo[itype_milk_raw] = current_milk->second;
            // Erase old key-value from map
            ammo.erase( current_milk );
        }
    }
    // if we got here, we got milk.
    if( current_milk->second == type->starting_ammo.begin()->second ) {
        // already full up
        return;
    }
    if( calendar::turn - udder_timer > 1_days ) {
        // no point granularizing this really, you milk once a day.
        ammo.begin()->second = type->starting_ammo.begin()->second;
        udder_timer = calendar::turn;
    }
}
References ammo, debugmsg, get_name(), itype_milk, itype_milk_raw, mtype::starting_ammo, calendar::turn, type, and udder_timer.
Referenced by on_load().
reset_bonuses()
void monster::reset_bonuses () override virtual
Resets the value of all bonus fields to 0, clears special effect flags.
Reimplemented from Creature.
Definition at line 2058 of file monster.cpp.
{
    effect_cache.reset();
    Creature::reset_bonuses();
}
References effect_cache, and Creature::reset_bonuses().
reset_special()
void monster::reset_special (const std::string & special_name)
Resets a given special to its monster type cooldown value.
Definition at line 2070 of file monster.cpp.
{
    const auto iter = type->special_attacks.find( special_name );
    if( iter != type->special_attacks.end() ) {
        set_special( special_name, iter->second->cooldown );
    }
}
References set_special(), mtype::special_attacks, and type.
Referenced by mattack::breathe(), and move().
reset_special_rng()
void monster::reset_special_rng (const std::string & special_name)
Resets a given special to a value between 0 and its monster type cooldown value.
Definition at line 2078 of file monster.cpp.
{
    const auto iter = type->special_attacks.find( special_name );
    if( iter != type->special_attacks.end() ) {
        set_special( special_name, rng( 0, iter->second->cooldown ) );
    }
}
References rng(), set_special(), mtype::special_attacks, and type.
reset_stats()
void monster::reset_stats () override virtual
Resets stats, and applies effects in an idempotent manner.
Implements Creature.
Definition at line 2065 of file monster.cpp.
{
    // Nothing here yet
}
scent_move()
tripoint monster::scent_move ()
Definition at line 1208 of file monmove.cpp.
{
    // TODO: Remove when scentmap is 3D
    if( std::abs( posz() - g->get_levz() ) > SCENT_MAP_Z_REACH ) {
        return { -1, -1, INT_MIN };
    }
    const std::set<scenttype_id> &tracked_scents = type->scents_tracked;
    const std::set<scenttype_id> &ignored_scents = type->scents_ignored;
    std::vector<tripoint> smoves;
    int bestsmell = 10; // Squares with smell 0 are not eligible targets.
    int smell_threshold = 200; // Squares at or above this level are ineligible.
    if( has_flag( MF_KEENNOSE ) ) {
        bestsmell = 1;
        smell_threshold = 400;
    }
    const bool fleeing = is_fleeing( g->u );
    if( fleeing ) {
        bestsmell = g->scent.get( pos() );
    }
    tripoint next( -1, -1, posz() );
    if( ( !fleeing && g->scent.get( pos() ) > smell_threshold ) ||
        ( fleeing && bestsmell == 0 ) ) {
        return next;
    }
    const bool can_bash = bash_skill() > 0;
    for( const auto &dest : g->m.points_in_radius( pos(), 1, SCENT_MAP_Z_REACH ) ) {
        int smell = g->scent.get( dest );
        const scenttype_id &type_scent = g->scent.get_type( dest );
        bool right_scent = false;
        // is the monster tracking this scent
        if( !tracked_scents.empty() ) {
            right_scent = tracked_scents.find( type_scent ) != tracked_scents.end();
        }
        //is this scent recognised by the monster species
        if( !type_scent.is_empty() ) {
            const std::set<species_id> &receptive_species = type_scent->receptive_species;
            const std::set<species_id> &monster_species = type->species;
            std::vector<species_id> v_intersection;
            std::set_intersection( receptive_species.begin(), receptive_species.end(), monster_species.begin(),
                                   monster_species.end(), std::back_inserter( v_intersection ) );
            if( !v_intersection.empty() ) {
                right_scent = true;
            }
        }
        // is the monster actually ignoring this scent
        if( !ignored_scents.empty() && ( ignored_scents.find( type_scent ) != ignored_scents.end() ) ) {
            right_scent = false;
        }
        if( ( !fleeing && smell < bestsmell ) || ( fleeing && smell > bestsmell ) || !right_scent ) {
            continue;
        }
        if( g->m.valid_move( pos(), dest, can_bash, true ) &&
            ( ( can_move_to( dest ) && !get_map().obstructed_by_vehicle_rotation( pos(), dest ) ) ||
              ( dest == g->u.pos() ) ||
              ( can_bash && g->m.bash_rating( bash_estimate(), dest ) > 0 ) ) ) {
            if( ( !fleeing && smell > bestsmell ) || ( fleeing && smell < bestsmell ) ) {
                smoves.clear();
                smoves.push_back( dest );
                bestsmell = smell;
            } else if( ( !fleeing && smell == bestsmell ) || ( fleeing && smell == bestsmell ) ) {
                smoves.push_back( dest );
            }
        }
    }
    return random_entry( smoves, next );
}
References bash_estimate(), bash_skill(), can_move_to(), g, get_map(), has_flag(), string_id< T >::is_empty(), is_fleeing(), MF_KEENNOSE, pos(), posz(), random_entry(), scent_type::receptive_species, SCENT_MAP_Z_REACH, mtype::scents_ignored, mtype::scents_tracked, mtype::species, and type.
Referenced by move().
serialize()
void monster::serialize (JsonOut & json) const
Definition at line 1936 of file savegame_json.cpp.
{
    json.start_object();
    // This must be after the json object has been started, so any super class
    // puts their data into the same json object.
    store( json );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::start_object(), and store().
set_dest()
void monster::set_dest (const tripoint & p)
Definition at line 263 of file monmove.cpp.
{
    goal = p;
}
References goal.
Referenced by iuse::directional_hologram(), mattack::nurse_operate(), and plan().
set_goal()
void monster::set_goal (const tripoint & p)
Definition at line 993 of file monster.cpp.
{
    goal = p;
}
References goal.
Referenced by mattack::smash_specific().
set_horde_attraction()
void monster::set_horde_attraction (monster_horde_attraction mha)
Definition at line 2977 of file monster.cpp.
{
    horde_attraction = mha;
}
References horde_attraction.
Referenced by map::spawn_monsters_submap_group().
set_hp()
void monster::set_hp (int hp)
Directly set the current hp of the monster (not capped at the maximal hp).
You might want to use heal / apply_damage or deal_damage instead.
Definition at line 1655 of file monster.cpp.
{
    this->hp = hp;
}
References hp.
Referenced by blobify(), iuse::can_goo(), game::despawn_monster(), mattack::disappear(), mattack::formblob(), trapfunc::goo(), iuse::granade_act(), map_funcs::migo_nerve_cage_removal(), mattack::mon_leech_evolution(), and mattack::plant().
set_special()
void monster::set_special (const std::string & special_name, int time)
Sets a given special to the given value.
Definition at line 2086 of file monster.cpp.
{
    const auto iter = special_attacks.find( special_name );
    if( iter != special_attacks.end() ) {
        iter->second.cooldown = time;
    } else {
        debugmsg( "%s has no special attack %s", disp_name().c_str(), special_name.c_str() );
    }
}
References debugmsg, disp_name(), special_attacks, and time.
Referenced by mattack::grab(), reset_special(), and reset_special_rng().
set_summon_time()
void monster::set_summon_time (const time_duration & length)
Definition at line 2144 of file monster.cpp.
{
    summon_time_limit = length;
}
References summon_time_limit.
Referenced by add_summoned_mon(), and iuse::directional_hologram().
setpos()
void monster::setpos (const tripoint & p) override virtual
Implements Creature.
Definition at line 238 of file monster.cpp.
{
    if( p == pos() ) {
        return;
    }
    bool wandering = wander();
    g->update_zombie_pos( *this, p );
    position = p;
    if( has_effect( effect_ridden ) && mounted_player && mounted_player->pos() != pos() ) {
        add_msg( m_debug, "Ridden monster %s moved independently and dumped player", get_name() );
        mounted_player->forced_dismount();
    }
    if( wandering ) {
        unset_dest();
    }
}
References add_msg(), effect_ridden, Character::forced_dismount(), g, get_name(), Creature::has_effect(), m_debug, mounted_player, Character::pos(), pos(), position, unset_dest(), and wander().
Referenced by leap_actor::call(), mattack::evolve_kill_strike(), mattack::grab_drag(), knock_back_to(), move_to(), game::place_player(), push_to(), mattack::tindalos_teleport(), trapfunc::tripwire(), vehicle::use_harness(), and game::vertical_move().
shift()
void monster::shift (const point & sm_shift)
Definition at line 998 of file monster.cpp.
{
    const point ms_shift = sm_to_ms_copy( sm_shift );
    position -= ms_shift;
    goal -= ms_shift;
    if( wandf > 0 ) {
        wander_pos -= ms_shift;
    }
}
References goal, position, sm_to_ms_copy(), wander_pos, and wandf.
shortest_special_cooldown()
int monster::shortest_special_cooldown () const
Return the lowest cooldown for an enabled special.
Definition at line 2106 of file monster.cpp.
{
    int countdown = std::numeric_limits<int>::max();
    for( const std::pair<const std::string, mon_special_attack> &sp_type : special_attacks ) {
        const mon_special_attack &local_attack_data = sp_type.second;
        if( !local_attack_data.enabled ) {
            continue;
        }
        countdown = std::min( countdown, local_attack_data.cooldown );
    }
    return countdown;
}
References mon_special_attack::cooldown, mon_special_attack::enabled, and special_attacks.
Referenced by behavior::monster_oracle_t::has_special().
shove_vehicle()
void monster::shove_vehicle (const tripoint & remote_destination, const tripoint & nearby_destination)
Definition at line 2080 of file monmove.cpp.
{
    if( this->has_flag( MF_PUSH_VEH ) ) {
        auto vp = g->m.veh_at( nearby_destination );
        if( vp ) {
            vehicle &veh = vp->vehicle();
            const units::mass veh_mass = veh.total_mass();
            int shove_moves_minimal = 0;
            int shove_veh_mass_moves_factor = 0;
            int shove_velocity = 0;
            float shove_damage_min = 0.00F;
            float shove_damage_max = 0.00F;
            switch( this->get_size() ) {
                case MS_TINY:
                case MS_SMALL:
                    break;
                case MS_MEDIUM:
                    if( veh_mass < 500_kilogram ) {
                        shove_moves_minimal = 150;
                        shove_veh_mass_moves_factor = 20;
                        shove_velocity = 500;
                        shove_damage_min = 0.00F;
                        shove_damage_max = 0.01F;
                    }
                    break;
                case MS_LARGE:
                    if( veh_mass < 1000_kilogram ) {
                        shove_moves_minimal = 100;
                        shove_veh_mass_moves_factor = 8;
                        shove_velocity = 1000;
                        shove_damage_min = 0.00F;
                        shove_damage_max = 0.03F;
                    }
                    break;
                case MS_HUGE:
                    if( veh_mass < 2000_kilogram ) {
                        shove_moves_minimal = 50;
                        shove_veh_mass_moves_factor = 4;
                        shove_velocity = 1500;
                        shove_damage_min = 0.00F;
                        shove_damage_max = 0.05F;
                    }
                    break;
                default:
                    break;
            }
            if( shove_velocity > 0 ) {
                if( g->u.sees( this->pos() ) ) {
                    //~ %1$s - monster name, %2$s - vehicle name
                    g->u.add_msg_if_player( m_bad, _( "%1$s shoves %2$s out of their way!" ), this->disp_name(),
                                            veh.disp_name() );
                }
                int shove_moves = shove_veh_mass_moves_factor * veh_mass / 10_kilogram;
                shove_moves = std::max( shove_moves, shove_moves_minimal );
                this->mod_moves( -shove_moves );
                const tripoint destination_delta( -nearby_destination + remote_destination );
                const tripoint shove_destination( clamp( destination_delta.x, -1, 1 ),
                                                  clamp( destination_delta.y, -1, 1 ),
                                                  clamp( destination_delta.z, -1, 1 ) );
                veh.skidding = true;
                veh.velocity = shove_velocity;
                if( shove_destination != tripoint_zero ) {
                    if( shove_destination.z != 0 ) {
                        veh.vertical_velocity = shove_destination.z < 0 ? -shove_velocity : +shove_velocity;
                    }
                    g->m.move_vehicle( veh, shove_destination, veh.face );
                }
                veh.move = tileray( destination_delta.xy() );
                veh.smash( g->m, shove_damage_min, shove_damage_max, 0.10F );
            }
        }
    }
}
References _, clamp(), vehicle::disp_name(), disp_name(), vehicle::face, g, get_size(), has_flag(), m_bad, MF_PUSH_VEH, Creature::mod_moves(), vehicle::move, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, vehicle::skidding, vehicle::smash(), vehicle::total_mass(), tripoint_zero, vehicle::vehicle(), vehicle::velocity, vehicle::vertical_velocity, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by move().
sight_range()
int monster::sight_range (int light_level) const override virtual
How far the creature sees under the given light.
Places outside this range can
Parameters
light_level See game::light_level.
Implements Creature.
Definition at line 958 of file monster.cpp.
{
    // Non-aquatic monsters can't see much when submerged
    if( !can_see() || effect_cache[VISION_IMPAIRED] ||
        ( is_underwater() && !swims() && !has_flag( MF_AQUATIC ) && !digging() ) ) {
        return 1;
    }
    static const int default_daylight = default_daylight_level();
    if( light_level == 0 ) {
        return type->vision_night;
    } else if( light_level == default_daylight ) {
        return type->vision_day;
    }
    int range = light_level * type->vision_day + ( default_daylight - light_level ) *
                type->vision_night;
    range /= default_daylight;
    return range;
}
References can_see(), default_daylight_level(), digging(), effect_cache, has_flag(), is_underwater(), MF_AQUATIC, swims(), type, mtype::vision_day, VISION_IMPAIRED, and mtype::vision_night.
skin_name()
std::string monster::skin_name () const override virtual
Implements Creature.
Definition at line 546 of file monster.cpp.
{
    return name_with_armor();
}
References name_with_armor().
spawn()
void monster::spawn (const tripoint & p)
Definition at line 482 of file monster.cpp.
{
    position = p;
    unset_dest();
}
References position, and unset_dest().
Referenced by move(), Creature_tracker::swap_positions(), and game::update_stair_monsters().
speed_rating()
float monster::speed_rating () const override virtual
Returns an approximate number of tiles this creature can travel per turn.
Implements Creature.
Definition at line 2833 of file monster.cpp.
{
    float ret = get_speed() / 100.0f;
    const auto leap = type->special_attacks.find( "leap" );
    if( leap != type->special_attacks.end() ) {
        // TODO: Make this calculate sane values here
        ret += 0.5f;
    }
    return ret;
}
References Creature::get_speed(), cata::hash64_detail::ret, mtype::special_attacks, and type.
Referenced by extended_description(), and print_info().
stability_roll()
float monster::stability_roll () const override virtual
Implements Creature.
Definition at line 1950 of file monster.cpp.
{
    int size_bonus = 0;
    switch( type->size ) {
        case MS_TINY:
            size_bonus -= 7;
            break;
        case MS_SMALL:
            size_bonus -= 3;
            break;
        case MS_LARGE:
            size_bonus += 5;
            break;
        case MS_HUGE:
            size_bonus += 10;
            break;
        default:
            break; // keep default
    }
    int stability = dice( type->melee_sides, type->melee_dice ) + size_bonus;
    if( has_effect( effect_stunned ) ) {
        stability -= rng( 1, 5 );
    }
    return stability;
}
References dice(), effect_stunned, Creature::has_effect(), mtype::melee_dice, mtype::melee_sides, MS_HUGE, MS_LARGE, MS_SMALL, MS_TINY, rng(), mtype::size, and type.
Referenced by push_to().
store()
void monster::store (JsonOut & json) const protected
Definition at line 1945 of file savegame_json.cpp.
{
    Creature::store( json );
    json.member( "typeid", type->id );
    json.member( "unique_name", unique_name );
    json.member( "posx", position.x );
    json.member( "posy", position.y );
    json.member( "posz", position.z );
    json.member( "wandx", wander_pos.x );
    json.member( "wandy", wander_pos.y );
    json.member( "wandz", wander_pos.z );
    json.member( "wandf", wandf );
    json.member( "hp", hp );
    json.member( "special_attacks", special_attacks );
    json.member( "friendly", friendly );
    json.member( "fish_population", fish_population );
    json.member( "faction", faction.id().str() );
    json.member( "mission_id", mission_id );
    json.member( "no_extra_death_drops", no_extra_death_drops );
    json.member( "dead", dead );
    json.member( "anger", anger );
    json.member( "morale", morale );
    json.member( "hallucination", hallucination );
    json.member( "stairscount", staircount );
    if( tied_item ) {
        json.member( "tied_item", *tied_item );
    }
    if( tack_item ) {
        json.member( "tack_item", *tack_item );
    }
    if( armor_item ) {
        json.member( "armor_item", *armor_item );
    }
    if( storage_item ) {
        json.member( "storage_item", *storage_item );
    }
    if( battery_item ) {
        json.member( "battery_item", *battery_item );
    }
    // Store the relative position of the goal so it loads correctly after a map shift.
    json.member( "destination", goal - pos() );
    json.member( "ammo", ammo );
    json.member( "upgrades", upgrades );
    json.member( "upgrade_time", upgrade_time );
    json.member( "last_updated", last_updated );
    json.member( "reproduces", reproduces );
    json.member( "baby_timer", baby_timer );
    json.member( "udder_timer", udder_timer );
    json.member( "summon_time_limit", summon_time_limit );
    if( horde_attraction > MHA_NULL && horde_attraction < NUM_MONSTER_HORDE_ATTRACTION ) {
        json.member( "horde_attraction", horde_attraction );
    }
    json.member( "inv", inv );
    json.member( "corpse_components", corpse_components );
    json.member( "dragged_foe_id", dragged_foe_id );
    // storing the rider
    json.member( "mounted_player_id", mounted_player_id );
    json.member( "path", path );
}
References ammo, anger, armor_item, baby_timer, battery_item, corpse_components, dead, dragged_foe_id, fish_population, friendly, goal, hallucination, horde_attraction, hp, faction_template::id, mtype::id, inv, last_updated, JsonOut::member(), MHA_NULL, mission_id, morale, mounted_player_id, no_extra_death_drops, NUM_MONSTER_HORDE_ATTRACTION, path, pos(), position, reproduces, special_attacks, staircount, storage_item, Creature::store(), string_id< T >::str(), summon_time_limit, tack_item, tied_item, type, udder_timer, unique_name, upgrade_time, upgrades, wander_pos, wandf, tripoint::x, tripoint::y, and tripoint::z.
Referenced by serialize().
stumble()
void monster::stumble ()
Stumble in a random direction, but with some caveats.
Definition at line 1893 of file monmove.cpp.
{
    // Only move every 10 turns.
    if( !one_in( 10 ) ) {
        return;
    }
    map &here = get_map();
    std::vector<tripoint> valid_stumbles;
    valid_stumbles.reserve( 11 );
    const bool avoid_water = has_flag( MF_NO_BREATHE ) && !swims() && !has_flag( MF_AQUATIC );
    for( const tripoint &dest : here.points_in_radius( pos(), 1 ) ) {
        if( dest != pos() ) {
            if( here.has_flag( TFLAG_RAMP_DOWN, dest ) ) {
                valid_stumbles.push_back( tripoint( dest.xy(), dest.z - 1 ) );
            } else if( here.has_flag( TFLAG_RAMP_UP, dest ) ) {
                valid_stumbles.push_back( tripoint( dest.xy(), dest.z + 1 ) );
            } else {
                valid_stumbles.push_back( dest );
            }
        }
    }
    if( here.has_zlevels() ) {
        tripoint below( posx(), posy(), posz() - 1 );
        if( here.valid_move( pos(), below, false, true ) ) {
            valid_stumbles.push_back( below );
        }
    }
    while( !valid_stumbles.empty() && !is_dead() ) {
        const tripoint dest = random_entry_removed( valid_stumbles );
        if( can_move_to( dest ) &&
            //Stop zombies and other non-breathing monsters wandering INTO water
            //(Unless they can swim/are aquatic)
            //But let them wander OUT of water if they are there.
            !( avoid_water &&
               here.has_flag( TFLAG_SWIMMABLE, dest ) &&
               !here.has_flag( TFLAG_SWIMMABLE, pos() ) ) &&
            ( g->critter_at( dest, is_hallucination() ) == nullptr ) ) {
            if( move_to( dest, true, false ) ) {
                break;
            }
        }
    }
}
References can_move_to(), g, get_map(), map::has_flag(), has_flag(), map::has_zlevels(), is_dead(), is_hallucination(), MF_AQUATIC, MF_NO_BREATHE, move_to(), one_in(), map::points_in_radius(), pos(), posx(), posy(), posz(), random_entry_removed(), swims(), TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, TFLAG_SWIMMABLE, and map::valid_move().
Referenced by mattack::dermatik(), move(), and trapfunc::tripwire().
swims()
bool monster::swims () const
Definition at line 946 of file monster.cpp.
{
    return has_flag( MF_SWIMS );
}
References has_flag(), and MF_SWIMS.
Referenced by calc_movecost(), can_drown(), can_submerge(), extended_description(), move_to(), sight_range(), stumble(), and Character::swim_speed().
symbol()
const std::string & monster::symbol () const override virtual
Implements Creature.
Definition at line 841 of file monster.cpp.
{
    return type->sym;
}
References mtype::sym, and type.
Referenced by anonymous_namespace{animation.cpp}::draw_hit_mon_curses().
symbol_color()
nc_color monster::symbol_color () const override virtual
Implements Creature.
Definition at line 851 of file monster.cpp.
{
    return color_with_effects();
}
References color_with_effects().
to_item()
item monster::to_item () const
Convert this monster into an item (see mtype::revert_to_itype).
Only useful for robots and the like, the monster must have at least a non-empty item id as revert_to_itype.
Definition at line 2812 of file monster.cpp.
{
    if( type->revert_to_itype.is_empty() ) {
        return item();
    }
    // Birthday is wrong, but the item created here does not use it anyway (I hope).
    item result( type->revert_to_itype, calendar::turn );
    const int damfac = std::max( 1, ( result.max_damage() + 1 ) * hp / type->hp );
    result.set_damage( std::max( 0, ( result.max_damage() + 1 ) - damfac ) );
    return result;
}
References hp, mtype::hp, string_id< T >::is_empty(), mtype::revert_to_itype, calendar::turn, and type.
Referenced by monexamine::deactivate_pet(), game::disable_robot(), and explosion_handler::emp_blast().
try_reproduce()
void monster::try_reproduce ()
Definition at line 391 of file monster.cpp.
{
    if( !reproduces ) {
        return;
    }
    // This can happen if the monster type has changed (from reproducing to non-reproducing monster)
    if( !type->baby_timer ) {
        return;
    }
    if( !baby_timer ) {
        // Assume this is a freshly spawned monster (because baby_timer is not set yet), set the point when it reproduce to somewhere in the future.
        baby_timer.emplace( calendar::turn + *type->baby_timer );
    }
    bool season_spawn = false;
    bool season_match = true;
    // only 50% of animals should reproduce
    bool female = one_in( 2 );
    for( auto &elem : type->baby_flags ) {
        if( elem == "SUMMER" || elem == "WINTER" || elem == "SPRING" || elem == "AUTUMN" ) {
            season_spawn = true;
        }
    }
    // add a decreasing chance of additional spawns when "catching up" an existing animal
    int chance = -1;
    while( true ) {
        if( *baby_timer > calendar::turn ) {
            return;
        }
        if( season_spawn ) {
            season_match = false;
            for( auto &elem : type->baby_flags ) {
                if( ( season_of_year( *baby_timer ) == SUMMER && elem == "SUMMER" ) ||
                    ( season_of_year( *baby_timer ) == WINTER && elem == "WINTER" ) ||
                    ( season_of_year( *baby_timer ) == SPRING && elem == "SPRING" ) ||
                    ( season_of_year( *baby_timer ) == AUTUMN && elem == "AUTUMN" ) ) {
                    season_match = true;
                }
            }
        }
        chance += 2;
        if( season_match && female && one_in( chance ) ) {
            int spawn_cnt = rng( 1, type->baby_count );
            if( type->baby_monster ) {
                g->m.add_spawn( type->baby_monster, spawn_cnt, pos() );
            } else {
                g->m.add_item_or_charges( pos(), item( type->baby_egg, *baby_timer, spawn_cnt ), true );
            }
        }
        *baby_timer += *type->baby_timer;
    }
}
References AUTUMN, mtype::baby_count, mtype::baby_egg, mtype::baby_flags, mtype::baby_monster, baby_timer, mtype::baby_timer, g, one_in(), pos(), reproduces, rng(), season_of_year(), SPRING, SUMMER, calendar::turn, type, and WINTER.
Referenced by on_load().
try_upgrade()
void monster::try_upgrade (bool pin_time)
Definition at line 332 of file monster.cpp.
{
    if( !can_upgrade() ) {
        return;
    }
    const int current_day = to_days<int>( calendar::turn - calendar::turn_zero );
    //This should only occur when a monster is created or upgraded to a new form
    if( upgrade_time < 0 ) {
        upgrade_time = next_upgrade_time();
        if( upgrade_time < 0 ) {
            return;
        }
        if( pin_time || type->age_grow > 0 ) {
            // offset by today, always true for growing creatures
            upgrade_time += current_day;
        } else {
            // offset by starting season
            // TODO: revisit this and make it simpler
            upgrade_time += to_days<int>( calendar::start_of_cataclysm - calendar::turn_zero );
        }
    }
    // Here we iterate until we either are before upgrade_time or can't upgrade any more.
    // This is so that late into game new monsters can 'catch up' with all that half-life
    // upgrades they'd get if we were simulating whole world.
    while( true ) {
        if( upgrade_time > current_day ) {
            // not yet
            return;
        }
        if( type->upgrade_into ) {
            //If we upgrade into a blacklisted monster, treat it as though we are non-upgradeable
            if( MonsterGroupManager::monster_is_blacklisted( type->upgrade_into ) ) {
                return;
            }
            poly( type->upgrade_into );
        } else {
            const mtype_id &new_type = MonsterGroupManager::GetRandomMonsterFromGroup( type->upgrade_group );
            if( new_type ) {
                poly( new_type );
            }
        }
        if( !upgrades ) {
            // upgraded into a non-upgradeable monster
            return;
        }
        const int next_upgrade = next_upgrade_time();
        if( next_upgrade < 0 ) {
            // hit never_upgrade
            return;
        }
        upgrade_time += next_upgrade;
    }
}
References mtype::age_grow, can_upgrade(), MonsterGroupManager::GetRandomMonsterFromGroup(), MonsterGroupManager::monster_is_blacklisted(), next_upgrade_time(), poly(), calendar::start_of_cataclysm, calendar::turn, calendar::turn_zero, type, mtype::upgrade_group, mtype::upgrade_into, upgrade_time, and upgrades.
Referenced by mattack::evolve_kill_strike(), on_load(), and mattack::upgrade().
turns_to_reach()
int monster::turns_to_reach (const point & p)
Definition at line 2055 of file monmove.cpp.
{
    // HACK: This function is a(n old) temporary hack that should soon be removed
    auto path = g->m.route( pos(), tripoint( p, posz() ), get_pathfinding_settings() );
    if( path.empty() ) {
        return 999;
    }
    double turns = 0.;
    for( size_t i = 0; i < path.size(); i++ ) {
        const tripoint &next = path[i];
        if( g->m.impassable( next ) ) {
            // No bashing through, it looks stupid when you go back and find
            // the doors intact.
            return 999;
        } else if( i == 0 ) {
            turns += static_cast<double>( calc_movecost( pos(), next ) ) / get_speed();
        } else {
            turns += static_cast<double>( calc_movecost( path[i - 1], next ) ) / get_speed();
        }
    }
    return static_cast<int>( turns + .9 ); // Halve (to get turns) and round up
}
References calc_movecost(), g, get_pathfinding_settings(), Creature::get_speed(), path, pos(), and posz().
unset_dest()
void monster::unset_dest ()
Definition at line 268 of file monmove.cpp.
{
    goal = pos();
    path.clear();
}
References goal, path, and pos().
Referenced by spell_effect::charm_monster(), make_friendly(), monster(), move(), plan(), setpos(), and spawn().
use_mech_power()
bool monster::use_mech_power (int amt)
Definition at line 2392 of file monster.cpp.
{
    if( is_hallucination() || !has_flag( MF_RIDEABLE_MECH ) || !battery_item ) {
        return false;
    }
    amt = -amt;
    battery_item->ammo_consume( amt, pos() );
    return battery_item->ammo_remaining() > 0;
}
References battery_item, has_flag(), is_hallucination(), MF_RIDEABLE_MECH, and pos().
Referenced by smash(), mattack::smash_specific(), ranged::throw_item(), and game::vertical_move().
wander()
bool monster::wander ()
Definition at line 78 of file monmove.cpp.
{
    return ( goal == pos() );
}
References goal, and pos().
Referenced by attack_target(), move(), and setpos().
wander_to()
void monster::wander_to (const tripoint & p, int f)
Set p as wander destination.
This will cause the monster to slowly move towards the destination, unless there is an overriding smell or plan.
Parameters
p Destination of monster's wanderings
f The priority of the destination, as well as how long we should wander towards there.
Definition at line 276 of file monmove.cpp.
{
    wander_pos = p;
    wandf = f;
}
References wander_pos, and wandf.
Referenced by hear_sound().
weight_capacity()
units::mass monster::weight_capacity () const override virtual
Reimplemented from Creature.
Definition at line 2702 of file monster.cpp.
{
    return type->weight * type->mountable_weight_ratio;
}
References mtype::mountable_weight_ratio, type, and mtype::weight.
Referenced by monexamine::add_armor(), monexamine::give_items_to(), and stash_on_pet().
will_join_horde()
bool monster::will_join_horde (int size)
Definition at line 2982 of file monster.cpp.
{
    const monster_horde_attraction mha = get_horde_attraction();
    if( mha == MHA_NEVER ) {
        return false;
    } else if( mha == MHA_ALWAYS ) {
        return true;
    } else if( g->m.has_flag( TFLAG_INDOORS, pos() ) && ( mha == MHA_OUTDOORS ||
               mha == MHA_OUTDOORS_AND_LARGE ) ) {
        return false;
    } else if( size < 3 && ( mha == MHA_LARGE || mha == MHA_OUTDOORS_AND_LARGE ) ) {
        return false;
    } else {
        return true;
    }
}
References g, get_horde_attraction(), MHA_ALWAYS, MHA_LARGE, MHA_NEVER, MHA_OUTDOORS, MHA_OUTDOORS_AND_LARGE, pos(), om_direction::size, and TFLAG_INDOORS.
will_move_to()
bool monster::will_move_to (const tripoint & p) const
Definition at line 119 of file monmove.cpp.
{
    if( g->m.impassable( p ) ) {
        if( digging() ) {
            if( !g->m.has_flag( "BURROWABLE", p ) ) {
                return false;
            }
        } else if( !( can_climb() && g->m.has_flag( "CLIMBABLE", p ) ) ) {
            return false;
        }
    }
    if( ( !can_submerge() && !flies() ) && g->m.has_flag( TFLAG_DEEP_WATER, p ) ) {
        return false;
    }
    if( digs() && !g->m.has_flag( "DIGGABLE", p ) && !g->m.has_flag( "BURROWABLE", p ) ) {
        return false;
    }
    if( has_flag( MF_AQUATIC ) && !g->m.has_flag( "SWIMMABLE", p ) ) {
        return false;
    }
    if( has_flag( MF_SUNDEATH ) && g->is_in_sunlight( p ) ) {
        return false;
    }
    if( get_size() > MS_MEDIUM && g->m.has_flag_ter( TFLAG_SMALL_PASSAGE, p ) ) {
        return false; // if a large critter, can't move through tight passages
    }
    // Various avoiding behaviors.
    bool avoid_fire = has_flag( MF_AVOID_FIRE );
    bool avoid_fall = has_flag( MF_AVOID_FALL );
    bool avoid_simple = has_flag( MF_AVOID_DANGER_1 );
    bool avoid_complex = has_flag( MF_AVOID_DANGER_2 );
    /*
     * Because some avoidance behaviors are supersets of others,
     * we can cascade through the implications. Complex implies simple,
     * and simple implies fire and fall.
     * unfortunately, fall does not necessarily imply fire, nor the converse.
     */
    if( avoid_complex ) {
        avoid_simple = true;
    }
    if( avoid_simple ) {
        avoid_fire = true;
        avoid_fall = true;
    }
    // technically this will shortcut in evaluation from fire or fall
    // before hitting simple or complex but this is more explicit
    if( avoid_fire || avoid_fall || avoid_simple || avoid_complex ) {
        const ter_id target = g->m.ter( p );
        // Don't enter lava if we have any concept of heat being bad
        if( avoid_fire && target == t_lava ) {
            return false;
        }
        if( avoid_fall ) {
            // Don't throw ourselves off cliffs if we have a concept of falling
            if( !g->m.has_floor( p ) && !flies() ) {
                return false;
            }
            // Don't enter open pits ever unless tiny, can fly or climb well
            if( !( type->size == MS_TINY || can_climb() ) &&
                ( target == t_pit || target == t_pit_spiked || target == t_pit_glass ) ) {
                return false;
            }
        }
        // Some things are only avoided if we're not attacking
        if( attitude( &g->u ) != MATT_ATTACK ) {
            // Sharp terrain is ignored while attacking
            if( avoid_simple && g->m.has_flag( "SHARP", p ) &&
                !( type->size == MS_TINY || flies() ) ) {
                return false;
            }
        }
        const field &target_field = g->m.field_at( p );
        // Higher awareness is needed for identifying these as threats.
        if( avoid_complex ) {
            const trap &target_trap = g->m.tr_at( p );
            // Don't enter any dangerous fields
            if( is_dangerous_fields( target_field ) ) {
                return false;
            }
            // Don't step on any traps (if we can see)
            if( has_flag( MF_SEES ) && !target_trap.is_benign() && g->m.has_floor( p ) ) {
                return false;
            }
        }
        // Without avoid_complex, only fire and electricity are checked for field avoidance.
        if( avoid_fire && target_field.find_field( fd_fire ) ) {
            return false;
        }
        if( avoid_simple && target_field.find_field( fd_electricity ) ) {
            return false;
        }
    }
    return true;
}
References attitude(), can_climb(), can_submerge(), digging(), digs(), fd_electricity, fd_fire, field::find_field(), flies(), g, get_size(), has_flag(), trap::is_benign(), Creature::is_dangerous_fields(), MATT_ATTACK, MF_AQUATIC, MF_AVOID_DANGER_1, MF_AVOID_DANGER_2, MF_AVOID_FALL, MF_AVOID_FIRE, MF_SEES, MF_SUNDEATH, MS_MEDIUM, MS_TINY, mtype::size, t_lava, t_pit, t_pit_glass, t_pit_spiked, TFLAG_DEEP_WATER, TFLAG_SMALL_PASSAGE, and type.
Referenced by can_move_to(), and can_place_monster().
will_reach()
bool monster::will_reach (const point & p)
Definition at line 2018 of file monmove.cpp.
{
    monster_attitude att = attitude( &g->u );
    if( att != MATT_FOLLOW && att != MATT_ATTACK && att != MATT_FRIEND && att != MATT_ZLAVE ) {
        return false;
    }
    if( digs() || has_flag( MF_AQUATIC ) ) {
        return false;
    }
    if( ( has_flag( MF_IMMOBILE ) || has_flag( MF_RIDEABLE_MECH ) ) && ( pos().xy() != p ) ) {
        return false;
    }
    auto path = g->m.route( pos(), tripoint( p, posz() ), get_pathfinding_settings() );
    if( path.empty() ) {
        return false;
    }
    if( has_flag( MF_SMELLS ) && g->scent.get( pos() ) > 0 &&
        g->scent.get( { p, posz() } ) > g->scent.get( pos() ) ) {
        return true;
    }
    if( can_hear() && wandf > 0 && rl_dist( wander_pos.xy(), p ) <= 2 &&
        rl_dist( point( posx(), posy() ), wander_pos.xy() ) <= wandf ) {
        return true;
    }
    if( can_see() && sees( tripoint( p, posz() ) ) ) {
        return true;
    }
    return false;
}
References attitude(), can_hear(), can_see(), digs(), g, get_pathfinding_settings(), has_flag(), MATT_ATTACK, MATT_FOLLOW, MATT_FRIEND, MATT_ZLAVE, MF_AQUATIC, MF_IMMOBILE, MF_RIDEABLE_MECH, MF_SMELLS, path, pos(), posx(), posy(), posz(), rl_dist(), Creature::sees(), wander_pos, wandf, and tripoint::xy().
Friends And Related Function Documentation
editmap
friend class editmap friend
Definition at line 86 of file monster.h.
Member Data Documentation
ammo
std::map<itype_id, int> monster::ammo
Definition at line 511 of file monster.h.
Referenced by mdeath::broken(), monexamine::deactivate_pet(), mdeath::detonate(), game::disable_robot(), explosion_handler::emp_blast(), mattack::frag(), grenade_helper(), mattack::kamikaze(), load(), activity_handlers::milk_finish(), monexamine::milk_source(), monster(), move_to(), normalize_ammo(), mattack::nurse_operate(), refill_udders(), game::revive_corpse(), mattack::rifle(), mattack::science(), gun_actor::shoot(), store(), mattack::tankgun(), Character::uninstall_bionic(), and place_monster_iuse::use().
anger
int monster::anger = 0
Definition at line 471 of file monster.h.
Referenced by attitude(), attitude_to(), mattack::copbot(), extended_description(), mattack::fungus_inject(), grenade_helper(), hear_sound(), is_fleeing(), load(), monster(), mattack::nurse_operate(), mattack::parrot_at_danger(), iuse::pheromone(), plan(), poly(), process_effects_internal(), process_trigger(), process_triggers(), mattack::resurrect(), mattack::riotbot(), defense_game::spawn_wave_monster(), store(), and mattack::upgrade().
armor_item
cata::value_ptr<item> monster::armor_item
Definition at line 462 of file monster.h.
Referenced by monexamine::add_armor(), die(), get_carried_weight(), get_worn_armor_val(), load(), process_items(), monexamine::remove_armor(), and store().
baby_timer
cata::optional<time_point> monster::baby_timer private
Definition at line 562 of file monster.h.
Referenced by extended_description(), load(), store(), and try_reproduce().
battery_item
cata::value_ptr<item> monster::battery_item
Definition at line 464 of file monster.h.
Referenced by check_mech_powered(), monexamine::insert_battery(), load(), monster(), monexamine::pet_menu(), monexamine::remove_battery(), store(), and use_mech_power().
corpse_components
std::vector<item> monster::corpse_components
Definition at line 456 of file monster.h.
Referenced by load(), make_mon_corpse(), game::revive_corpse(), and store().
dead
bool monster::dead private
Definition at line 554 of file monster.h.
Referenced by die(), is_dead(), load(), monster(), and store().
death_drops
bool monster::death_drops = true
Definition at line 483 of file monster.h.
Referenced by die(), monster(), and mattack::zombie_fuse().
dragged_foe_id
character_id monster::dragged_foe_id
Definition at line 459 of file monster.h.
Referenced by find_dragged_foe(), load(), mattack::nurse_operate(), nursebot_operate(), and store().
effect_cache
std::bitset<NUM_MEFF> monster::effect_cache private
Definition at line 567 of file monster.h.
Referenced by attitude(), can_see(), is_fleeing(), move_effects(), movement_impaired(), process_one_effect(), reset_bonuses(), and sight_range().
faction
mfaction_id monster::faction
Definition at line 474 of file monster.h.
Referenced by Creature_tracker::add_to_faction_map(), attitude_to(), make_ally(), mattack::parrot_at_danger(), plan(), and mattack::zombie_fuse().
fish_population
int monster::fish_population = 1
Definition at line 490 of file monster.h.
Referenced by iuse::fish_trap(), load(), monster(), rod_fish(), and store().
friendly
int monster::friendly
Definition at line 470 of file monster.h.
Referenced by Character::activate_mutation(), add_summoned_mon(), Creature_tracker::add_to_faction_map(), iuse::artifact(), attitude(), attitude_to(), mattack::brandish(), gun_actor::call(), mattack::callblobs(), Character::can_mount(), iuse::capture_monster_act(), spell_effect::charm_monster(), mattack::check_money_left(), mattack::chickenbot(), mattack::darkman(), iuse::directional_hologram(), game::disable_robot(), mattack::dogthing(), mattack::eat_food(), extended_description(), mattack::fear_paralyze(), feedpet(), game::find_or_make_stairs(), mattack::flamethrower(), mattack::formblob(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::grow_vine(), mattack::howl(), is_symbol_highlighted(), load(), mattack::longswipe(), make_ally(), make_fake_npc(), make_friendly(), monexamine::mech_hack(), monster(), move(), avatar_action::move(), move_effects(), mattack::multi_robot(), mattack::nurse_operate(), monexamine::pay_bot(), iuse::pheromone(), mattack::photograph(), plan(), mattack::ratking(), mattack::rattle(), wish_monster_callback::refresh(), iuse::robotcontrol_can_target(), talk_effect_fun_t::set_u_buy_monster(), gun_actor::shoot(), map::spawn_monsters_submap(), mattack::stare(), store(), mattack::tentacle(), mattack::triffid_heartbeat(), place_monster_iuse::use(), vehicle::use_harness(), Character::valid_aoe_technique(), game::vertical_move(), iuse::vortex(), and debug_menu::wishmonster().
goal
tripoint monster::goal private
Definition at line 552 of file monster.h.
Referenced by load(), move(), move_target(), nursebot_operate(), set_dest(), set_goal(), shift(), store(), unset_dest(), and wander().
hallucination
bool monster::hallucination
Definition at line 488 of file monster.h.
Referenced by is_hallucination(), load(), monster(), store(), and debug_menu::wishmonster().
horde_attraction
monster_horde_attraction monster::horde_attraction private
Definition at line 564 of file monster.h.
Referenced by get_horde_attraction(), load(), monster(), set_horde_attraction(), and store().
hp
int monster::hp private
Definition at line 550 of file monster.h.
Referenced by apply_damage(), die_in_explosion(), explode(), extended_description(), get_hp(), get_HP_Bar(), heal(), init_from_item(), is_dead_state(), load(), monster(), move(), poly(), print_info(), process_effects_internal(), set_hp(), store(), and to_item().
ignoring
short monster::ignoring
Definition at line 504 of file monster.h.
Referenced by game::handle_action(), game::mon_info_update(), and monster().
inv
std::vector<item> monster::inv
Definition at line 455 of file monster.h.
Referenced by add_item(), mattack::check_money_left(), die(), monexamine::dump_items(), mdeath::focused_beam(), get_carried_volume(), get_carried_weight(), load(), name_with_armor(), monexamine::pet_menu(), process_items(), monexamine::remove_bag_from(), mattack::searchlight(), and store().
last_updated
time_point monster::last_updated = calendar::turn_zero
Definition at line 526 of file monster.h.
Referenced by load(), monster(), on_load(), on_unload(), and store().
lastseen_turn
cata::optional<time_point> monster::lastseen_turn
Definition at line 505 of file monster.h.
Referenced by game::mon_info_update().
made_footstep
bool monster::made_footstep
Definition at line 485 of file monster.h.
Referenced by footsteps(), and monster().
mission_id
int monster::mission_id
Definition at line 476 of file monster.h.
Referenced by mission::is_complete(), load(), monster(), mission::on_creature_death(), map::spawn_monsters_submap(), and store().
morale
int monster::morale = 0
Definition at line 472 of file monster.h.
Referenced by attitude(), attitude_to(), extended_description(), hear_sound(), is_fleeing(), load(), monster(), plan(), poly(), process_effects_internal(), process_trigger(), process_triggers(), defense_game::spawn_wave_monster(), and store().
mounted_player
Character* monster::mounted_player = nullptr
Definition at line 457 of file monster.h.
Referenced by Creature::add_effect(), Creature::deal_melee_hit(), Creature::deal_projectile_attack(), die(), npc::die(), Character::dismount(), trapfunc::dissector(), ranged::hit_with_aoe(), print_info(), setpos(), and game::vertical_move().
mounted_player_id
character_id monster::mounted_player_id
Definition at line 458 of file monster.h.
Referenced by npc::die(), Character::dismount(), load(), Character::mount_creature(), and store().
no_corpse_quiet
bool monster::no_corpse_quiet = false
Definition at line 481 of file monster.h.
Referenced by mdeath::broken(), game::catch_a_monster(), mattack::disappear(), mdeath::normal(), and mattack::photograph().
no_extra_death_drops
bool monster::no_extra_death_drops
Definition at line 479 of file monster.h.
Referenced by add_summoned_mon(), die(), mattack::disappear(), load(), make_mon_corpse(), monster(), mattack::photograph(), game::revive_corpse(), and store().
path
std::vector<tripoint> monster::path private
Found path.
Note: Not used by monsters that don't pathfind!
Definition at line 566 of file monster.h.
Referenced by load(), move(), store(), turns_to_reach(), unset_dest(), and will_reach().
position
tripoint monster::position private
Definition at line 553 of file monster.h.
Referenced by load(), monster(), pos(), posx(), posy(), posz(), setpos(), shift(), spawn(), and store().
reproduces
bool monster::reproduces private
Definition at line 561 of file monster.h.
Referenced by extended_description(), load(), monster(), poly(), store(), and try_reproduce().
special_attacks
std::map<std::string, mon_special_attack> monster::special_attacks private
Definition at line 551 of file monster.h.
Referenced by disable_special(), load(), monster(), move(), poly(), process_turn(), set_special(), shortest_special_cooldown(), and store().
staircount
int monster::staircount
Definition at line 508 of file monster.h.
Referenced by load(), store(), and game::update_stair_monsters().
storage_item
cata::value_ptr<item> monster::storage_item
Definition at line 463 of file monster.h.
Referenced by monexamine::attach_bag_to(), die(), get_carried_weight(), monexamine::give_items_to(), load(), process_items(), monexamine::remove_bag_from(), stash_on_pet(), and store().
summon_time_limit
cata::optional<time_duration> monster::summon_time_limit = cata::nullopt private
Definition at line 568 of file monster.h.
Referenced by decrement_summon_timer(), die(), load(), set_summon_time(), and store().
tack_item
cata::value_ptr<item> monster::tack_item
Definition at line 461 of file monster.h.
Referenced by monexamine::attach_or_remove_saddle(), die(), get_carried_weight(), load(), process_items(), and store().
tied_item
cata::value_ptr<item> monster::tied_item
Definition at line 460 of file monster.h.
Referenced by monexamine::add_leash(), die(), load(), Character::mount_creature(), move_effects(), process_items(), monexamine::remove_leash(), store(), and vehicle::use_harness().
type
const mtype* monster::type
Definition at line 477 of file monster.h.
Referenced by mdeath::acid(), mattack::acid_barf(), Creature_tracker::add(), mdeath::amigara(), mattack::antqueen(), attack_at(), attitude(), avoid_trap(), bash_skill(), basic_symbol_color(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), mdeath::blobsplit(), bloodType(), mattack::breathe(), mdeath::broken(), melee_actor::call(), iuse::camera(), Character::can_wield(), iuse::capture_monster_act(), game::catch_a_monster(), check_mech_powered(), color_with_effects(), item::contain_monster(), mattack::copbot(), trapfunc::crossbow(), deal_projectile_attack(), mattack::dermatik(), die(), game::disable_robot(), Character::dismount(), trapfunc::dissector(), anonymous_namespace{animation.cpp}::draw_hit_mon_curses(), drop_items_on_death(), mattack::eat_food(), iuse::einktabletpc(), explosion_handler::emp_blast(), npc::evaluate_enemy(), mattack::evolve_kill_strike(), mdeath::explode(), extended_description(), fall_damage_mod(), iuse::fish_trap(), mattack::flesh_golem(), mattack::flesh_tendril(), game::fling_creature(), footsteps(), game::forced_door_closing(), mattack::formblob(), mattack::frag(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), get_armor_bash(), get_armor_bullet(), get_armor_cut(), get_armor_type(), get_dodge_base(), get_grab_strength(), get_hit_base(), get_HP_Bar(), get_hp_max(), get_melee(), get_mountable_weight_ratio(), get_pathfinding_settings(), get_size(), get_volume(), get_weight(), gibType(), trapfunc::goo(), mattack::grab(), mattack::grab_drag(), iuse::granade_act(), grenade_helper(), mdeath::guilt(), ranged::gunmode_checks_weapon(), has_flag(), hasten_upgrade(), heal(), mattack::howl(), mattack::impale(), in_species(), init_from_item(), is_immune_damage(), is_immune_field(), mdeath::kill_vines(), knock_back_to(), load(), mattack::longswipe(), mattack::lunge(), made_of(), made_of_any(), make_fungus(), make_mon_corpse(), mech_str_addition(), melee_attack(), activity_handlers::milk_finish(), monexamine::milk_source(), game::mon_info_update(), monster(), map::monster_in_field(), Character::mount_creature(), move(), move_effects(), move_to(), name(), name_with_armor(), next_upgrade_time(), mdeath::normal(), normalize_ammo(), mattack::nurse_operate(), nursebot_operate(), on_hit(), on_load(), pet_armor_loc(), monexamine::pet_menu(), petfood(), iuse::pheromone(), photo_def_for_camera_point(), mattack::photograph(), plan(), poly(), print_info(), process_effects_internal(), process_trigger(), process_triggers(), process_turn(), mattack::ranged_pull(), rate_critter(), refill_udders(), wish_monster_callback::refresh(), reset_special(), reset_special_rng(), resistances::resistances(), mattack::resurrect(), mdefense::return_fire(), mattack::riotbot(), iuse::robotcontrol_can_target(), rod_fish(), scent_move(), mattack::searchlight(), trapfunc::shotgun(), sight_range(), mattack::smash(), trapfunc::snare_heavy(), trapfunc::snare_light(), speed_rating(), mdeath::splatter(), stability_roll(), store(), mattack::stretch_attack(), mattack::stretch_bite(), symbol(), mattack::tentacle(), mattack::thrown_by_judo(), to_item(), try_reproduce(), try_upgrade(), mattack::upgrade(), place_monster_iuse::use(), vehicle::use_harness(), mattack::vine(), weight_capacity(), will_move_to(), and mdeath::worm().
udder_timer
time_point monster::udder_timer private
Definition at line 563 of file monster.h.
Referenced by load(), monster(), refill_udders(), and store().
unique_name
std::string monster::unique_name
Definition at line 487 of file monster.h.
Referenced by load(), make_mon_corpse(), name(), monexamine::rename_pet(), talk_effect_fun_t::set_u_buy_monster(), map::spawn_monsters_submap(), mdeath::splatter(), and store().
upgrade_time
int monster::upgrade_time private
Definition at line 560 of file monster.h.
Referenced by allow_upgrade(), extended_description(), get_upgrade_time(), hasten_upgrade(), init_from_item(), load(), monster(), store(), and try_upgrade().
upgrades
bool monster::upgrades private
Definition at line 559 of file monster.h.
Referenced by can_upgrade(), load(), monster(), next_upgrade_time(), poly(), store(), and try_upgrade().
wander_pos
tripoint monster::wander_pos
Definition at line 453 of file monster.h.
Referenced by load(), move(), plan(), shift(), defense_game::spawn_wave_monster(), store(), wander_to(), and will_reach().
wandf
int monster::wandf
Definition at line 454 of file monster.h.
Referenced by iuse::directional_hologram(), load(), monster(), move(), plan(), shift(), defense_game::spawn_wave_monster(), store(), wander_to(), and will_reach().
The documentation for this class was generated from the following files:
src/monster.h
src/monmove.cpp
src/monster.cpp
src/savegame_json.cpp