Cataclysm BN: cata_libintl::trans_library Class Reference
cata_libintl::trans_library Class Reference
Translation library.
#include <cata_libintl.h>
Classes
struct library_string_descr
Public Member Functions
Translation lookup
Parameters
msgid singular original string
msgid_pl plural original string
msgctxt translation context
n number to choose plural form for
Returns
If translation is found, returns translated string or correct plural form. Otherwise, returns original string or original plural string depending on n (n==1 ? msgid : msgid_pl).
const char * get (const char *msgid) const
const char * get_pl (const char *msgid, const char *msgid_pl, size_t n) const
const char * get_ctx (const char *msgctxt, const char *msgid) const
const char * get_ctx_pl (const char *msgctxt, const char *msgid, const char *msgid_pl, size_t n) const
Static Public Member Functions
static trans_library create (std::vector< trans_catalogue > catalogues)
Create new library from catalogues.
Private Member Functions
void build_string_table ()
std::vector< library_string_descr >::const_iterator find_entry (const char *id) const
const char * lookup_string (const char *id) const
const char * lookup_pl_string (const char *id, size_t n) const
Private Attributes
std::vector< library_string_descr > strings
std::vector< trans_catalogue > catalogues
Detailed Description
Translation library.
Represents collection of catalogues merged into a single pool ready for use.
Definition at line 179 of file cata_libintl.h.
Member Function Documentation
build_string_table()
void cata_libintl::trans_library::build_string_table () private
Definition at line 751 of file cata_libintl.cpp.
{
    assert( strings.empty() );
    for( size_t i_cat = 0; i_cat < catalogues.size(); i_cat++ ) {
        const trans_catalogue &cat = catalogues[i_cat];
        u32 num = cat.get_num_strings();
        // 0th entry is the metadata, we skip it
        strings.reserve( num - 1 );
        for( u32 i = 1; i < num; i++ ) {
            const char *i_cstr = cat.get_nth_orig_string( i );
            auto it = std::lower_bound( strings.begin(), strings.end(),
            i_cstr, [this]( const library_string_descr & a_descr, const char *b ) -> bool {
                const char *a = this->catalogues[a_descr.catalogue].get_nth_orig_string( a_descr.entry );
                return strcmp( a, b ) < 0;
            } );
            library_string_descr desc = { static_cast<u32>( i_cat ), i };
            if( it == strings.end() ) {
                // Not found, or all elements are greater
                strings.push_back( desc );
            } else if( strcmp( catalogues[it->catalogue].get_nth_orig_string( it->entry ), i_cstr ) == 0 ) {
                // Overwrite existing string only if new string has plural form(s),
                // but existing one does not.
                if(
                    cat.check_nth_translation_has_plf( i ) &&
                    !catalogues[it->catalogue].check_nth_translation_has_plf( it->entry )
                ) {
                    *it = desc;
                }
                continue;
            } else {
                strings.insert( it, desc );
            }
        }
    }
}
References b, catalogues, cata_libintl::trans_catalogue::check_nth_translation_has_plf(), cata_libintl::trans_catalogue::get_nth_orig_string(), cata_libintl::trans_catalogue::get_num_strings(), num, and strings.
Referenced by create().
create()
trans_library cata_libintl::trans_library::create (std::vector< trans_catalogue > catalogues) static
Create new library from catalogues.
If 2 or more catalogues have entries with same id (msgid + optional msgctxt), only the entry from the first such catalogue is used.
Definition at line 790 of file cata_libintl.cpp.
{
    trans_library lib;
    lib.catalogues = std::move( catalogues );
    lib.build_string_table();
    return lib;
}
References build_string_table(), catalogues, and avatar_action::move().
find_entry()
std::vector< trans_library::library_string_descr >::const_iterator cata_libintl::trans_library::find_entry (const char * id) const private
Definition at line 732 of file cata_libintl.cpp.
{
    auto it = std::lower_bound( strings.begin(), strings.end(),
    id, [this]( const library_string_descr & a_descr, const char *b ) -> bool {
        const char *a = this->catalogues[a_descr.catalogue].get_nth_orig_string( a_descr.entry );
        return strcmp( a, b ) < 0;
    } );
    if( it != strings.end() ) {
        const char *found = catalogues[it->catalogue].get_nth_orig_string( it->entry );
        if( strcmp( id, found ) == 0 ) {
            return it;
        }
    }
    return strings.end();
}
References b, catalogues, and strings.
Referenced by lookup_pl_string(), and lookup_string().
get()
const char * cata_libintl::trans_library::get (const char * msgid) const
Definition at line 816 of file cata_libintl.cpp.
{
    const char *ret = lookup_string( msgid );
    return ret ? ret : msgid;
}
References lookup_string(), and cata::hash64_detail::ret.
Referenced by translatable_mod_info::update().
get_ctx()
const char * cata_libintl::trans_library::get_ctx (const char * msgctxt, const char * msgid) const
Definition at line 828 of file cata_libintl.cpp.
{
    std::string buf;
    buf.reserve( strlen( msgctxt ) + 1 + strlen( msgid ) );
    buf += msgctxt;
    buf += '\4';
    buf += msgid;
    const char *ret = lookup_string( buf.c_str() );
    return ret ? ret : msgid;
}
References lookup_string(), and cata::hash64_detail::ret.
get_ctx_pl()
const char * cata_libintl::trans_library::get_ctx_pl (const char * msgctxt, const char * msgid, const char * msgid_pl, size_t n) const
Definition at line 839 of file cata_libintl.cpp.
{
    std::string buf;
    buf.reserve( strlen( msgctxt ) + 1 + strlen( msgid ) );
    buf += msgctxt;
    buf += '\4';
    buf += msgid;
    const char *ret = lookup_pl_string( buf.c_str(), n );
    return ret ? ret : ( n == 1  ? msgid : msgid_pl );
}
References lookup_pl_string(), and cata::hash64_detail::ret.
get_pl()
const char * cata_libintl::trans_library::get_pl (const char * msgid, const char * msgid_pl, size_t n) const
Definition at line 822 of file cata_libintl.cpp.
{
    const char *ret = lookup_pl_string( msgid, n );
    return ret ? ret : ( n == 1  ? msgid : msgid_pl );
}
References lookup_pl_string(), and cata::hash64_detail::ret.
lookup_pl_string()
const char * cata_libintl::trans_library::lookup_pl_string (const char * id, size_t n) const private
Definition at line 807 of file cata_libintl.cpp.
{
    auto it = find_entry( id );
    if( it == strings.end() ) {
        return nullptr;
    }
    return catalogues[it->catalogue].get_nth_pl_translation( it->entry, n );
}
References catalogues, find_entry(), and strings.
Referenced by get_ctx_pl(), and get_pl().
lookup_string()
const char * cata_libintl::trans_library::lookup_string (const char * id) const private
Definition at line 798 of file cata_libintl.cpp.
{
    auto it = find_entry( id );
    if( it == strings.end() ) {
        return nullptr;
    }
    return catalogues[it->catalogue].get_nth_translation( it->entry );
}
References catalogues, find_entry(), and strings.
Referenced by get(), and get_ctx().
Member Data Documentation
catalogues
std::vector<trans_catalogue> cata_libintl::trans_library::catalogues private
Definition at line 192 of file cata_libintl.h.
Referenced by build_string_table(), create(), find_entry(), lookup_pl_string(), and lookup_string().
strings
std::vector<library_string_descr> cata_libintl::trans_library::strings private
Definition at line 189 of file cata_libintl.h.
Referenced by build_string_table(), find_entry(), lookup_pl_string(), and lookup_string().
The documentation for this class was generated from the following files:
src/cata_libintl.h
src/cata_libintl.cpp