Cataclysm BN: field Class Reference
field Class Reference
A variable sized collection of field entries on a given map square.
#include <field.h>
Public Member Functions
field ()
field_entry * find_field (const field_type_id &field_type_to_find)
Returns a field entry corresponding to the field_type_id parameter passed in.
const field_entry * find_field_c (const field_type_id &field_type_to_find) const
Returns a field entry corresponding to the field_type_id parameter passed in.
const field_entry * find_field (const field_type_id &field_type_to_find) const
Returns a field entry corresponding to the field_type_id parameter passed in.
bool add_field (const field_type_id &field_type_to_add, int new_intensity=1, const time_duration &new_age=0_turns)
Inserts the given field_type_id into the field list for a given tile if it does not already exist.
bool remove_field (const field_type_id &field_to_remove)
Removes the field entry with a type equal to the field_type_id parameter.
void remove_field (std::map< field_type_id, field_entry >::iterator)
Make sure to decrement the field counter in the submap.
unsigned int field_count () const
field_type_id displayed_field_type () const
Returns field type that should be drawn.
description_affix displayed_description_affix () const
std::map< field_type_id, field_entry >::iterator begin ()
std::map< field_type_id, field_entry >::const_iterator begin () const
std::map< field_type_id, field_entry >::iterator end ()
std::map< field_type_id, field_entry >::const_iterator end () const
int total_move_cost () const
Returns the total move cost from all fields.
Private Attributes
std::map< field_type_id, field_entry > _field_type_list
field_type_id _displayed_field_type
Detailed Description
A variable sized collection of field entries on a given map square.
It contains one (at most) entry of each field type (e. g. one smoke entry and one fire entry, but not two fire entries). Use find_field to get the field entry of a specific type, or iterate over all entries via begin and end (allows range based iteration). There is displayed_field_type to specific which field should be drawn on the map.
Definition at line 130 of file field.h.
Constructor & Destructor Documentation
field()
field::field ()
Definition at line 143 of file field.cpp.
    : _displayed_field_type( fd_null )
{
}
Member Function Documentation
add_field()
bool field::add_field (const field_type_id & field_type_to_add, int new_intensity = 1, const time_duration & new_age = 0_turns)
Inserts the given field_type_id into the field list for a given tile if it does not already exist.
If you wish to modify an already existing field use find_field and modify the result. Intensity defaults to 1, and age to 0 (permanent) if not specified. The intensity is added to an existing field entry, but the age is only used for newly added entries.
Returns
false if the field_type_id already exists, true otherwise.
Definition at line 190 of file field.cpp.
{
    // sanity check, we don't want to store fd_null
    if( !field_type_to_add ) {
        debugmsg( "Tried to add null field" );
        return false;
    }
    auto it = _field_type_list.find( field_type_to_add );
    if( it != _field_type_list.end() ) {
        // Most fields stack intensities, but some add duration instead
        if( it->first->stacking_type == fields::stacking_type::intensity ) {
            it->second.set_field_intensity( it->second.get_field_intensity() + new_intensity );
        } else {
            time_duration half_life = field_type_to_add->half_life;
            if( new_age < half_life ) {
                it->second.mod_field_age( new_age - half_life );
            }
        }
        return false;
    }
    if( !_displayed_field_type ||
        field_type_to_add.obj().priority >= _displayed_field_type.obj().priority ) {
        _displayed_field_type = field_type_to_add;
    }
    _field_type_list[field_type_to_add] = field_entry( field_type_to_add, new_intensity, new_age );
    return true;
}
References _displayed_field_type, _field_type_list, debugmsg, field_type::half_life, fields::intensity, int_id< T >::obj(), and field_type::priority.
Referenced by map::add_field().
begin() [1/2]
std::map< field_type_id, field_entry >::iterator field::begin ()
Definition at line 251 of file field.cpp.
{
    return _field_type_list.begin();
}
References _field_type_list.
Referenced by editmap::edit_fld(), and map::process_fields_in_submap().
begin() [2/2]
std::map< field_type_id, field_entry >::const_iterator field::begin () const
Definition at line 256 of file field.cpp.
{
    return _field_type_list.begin();
}
References _field_type_list.
displayed_description_affix()
description_affix field::displayed_description_affix () const
Definition at line 280 of file field.cpp.
{
    return _displayed_field_type.obj().desc_affix;
}
References _displayed_field_type, field_type::desc_affix, and int_id< T >::obj().
Referenced by colorized_field_description_at().
displayed_field_type()
field_type_id field::displayed_field_type () const
Returns field type that should be drawn.
Definition at line 275 of file field.cpp.
{
    return _displayed_field_type;
}
References _displayed_field_type.
Referenced by colorized_field_description_at(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), and map::process_fields_in_submap().
end() [1/2]
std::map< field_type_id, field_entry >::iterator field::end ()
Definition at line 261 of file field.cpp.
{
    return _field_type_list.end();
}
References _field_type_list.
Referenced by map::process_fields_in_submap().
end() [2/2]
std::map< field_type_id, field_entry >::const_iterator field::end () const
Definition at line 266 of file field.cpp.
{
    return _field_type_list.end();
}
References _field_type_list.
field_count()
unsigned int field::field_count () const
Definition at line 246 of file field.cpp.
{
    return _field_type_list.size();
}
References _field_type_list.
Referenced by editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), map::drop_fields(), and editmap::edit_fld().
find_field() [1/2]
field_entry * field::find_field (const field_type_id & field_type_to_find)
Returns a field entry corresponding to the field_type_id parameter passed in.
If no fields are found then nullptr is returned.
Definition at line 153 of file field.cpp.
{
    if( !_displayed_field_type ) {
        return nullptr;
    }
    const auto it = _field_type_list.find( field_type_to_find );
    if( it != _field_type_list.end() ) {
        return &it->second;
    }
    return nullptr;
}
References _displayed_field_type, and _field_type_list.
Referenced by colorized_field_description_at(), npc::could_move_onto(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), editmap::edit_fld(), maptile::find_field(), map::gas_can_spread_to(), map::get_field(), map::get_field_age(), map::get_field_intensity(), map::process_fields_in_submap(), relic_funcs::process_recharge_entry(), editmap::update_fmenu_entry(), and monster::will_move_to().
find_field() [2/2]
const field_entry * field::find_field (const field_type_id & field_type_to_find) const
Returns a field entry corresponding to the field_type_id parameter passed in.
If no fields are found then nullptr is returned.
Definition at line 177 of file field.cpp.
{
    return find_field_c( field_type_to_find );
}
References find_field_c().
find_field_c()
const field_entry * field::find_field_c (const field_type_id & field_type_to_find) const
Returns a field entry corresponding to the field_type_id parameter passed in.
If no fields are found then nullptr is returned.
Definition at line 165 of file field.cpp.
{
    if( !_displayed_field_type ) {
        return nullptr;
    }
    const auto it = _field_type_list.find( field_type_to_find );
    if( it != _field_type_list.end() ) {
        return &it->second;
    }
    return nullptr;
}
References _displayed_field_type, and _field_type_list.
Referenced by find_field(), and iuse::mop().
remove_field() [1/2]
bool field::remove_field (const field_type_id & field_to_remove)
Removes the field entry with a type equal to the field_type_id parameter.
Make sure to decrement the field counter in the submap if (and only if) the function returns true.
Returns
True if the field was removed, false if it did not exist in the first place.
Definition at line 219 of file field.cpp.
{
    const auto it = _field_type_list.find( field_to_remove );
    if( it == _field_type_list.end() ) {
        return false;
    }
    remove_field( it );
    return true;
}
References _field_type_list, and remove_field().
Referenced by map::drop_fields(), map::mop_spills(), map::process_fields_in_submap(), remove_field(), and map::remove_field().
remove_field() [2/2]
void field::remove_field (std::map< field_type_id, field_entry >::iterator it)
Make sure to decrement the field counter in the submap.
Removes the field entry, the iterator must point into _field_type_list and must be valid.
Definition at line 229 of file field.cpp.
{
    _field_type_list.erase( it );
    _displayed_field_type = fd_null;
    if( !_field_type_list.empty() ) {
        for( auto &fld : _field_type_list ) {
            if( !_displayed_field_type || fld.first.obj().priority >= _displayed_field_type.obj().priority ) {
                _displayed_field_type = fld.first;
            }
        }
    }
}
References _displayed_field_type, _field_type_list, fd_null, int_id< T >::obj(), and field_type::priority.
total_move_cost()
int field::total_move_cost () const
Returns the total move cost from all fields.
Definition at line 285 of file field.cpp.
{
    int current_cost = 0;
    for( auto &fld : _field_type_list ) {
        current_cost += fld.second.move_cost();
    }
    return current_cost;
}
References _field_type_list.
Member Data Documentation
_displayed_field_type
field_type_id field::_displayed_field_type private
Definition at line 201 of file field.h.
Referenced by add_field(), displayed_description_affix(), displayed_field_type(), find_field(), find_field_c(), and remove_field().
_field_type_list
std::map<field_type_id, field_entry> field::_field_type_list private
Definition at line 199 of file field.h.
Referenced by add_field(), begin(), end(), field_count(), find_field(), find_field_c(), remove_field(), and total_move_cost().
The documentation for this class was generated from the following files:
src/field.h
src/field.cpp