Cataclysm BN: jmapgen_graffiti Class Reference
jmapgen_graffiti Class Reference
Place graffiti with some text or a snippet.
Public Member Functions
jmapgen_graffiti (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
std::string apply_all_tags (std::string graffiti, const std::string &cityname) const
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
std::string text
std::string snippet
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place graffiti with some text or a snippet.
"text": the text of the graffiti. "snippet": snippet category to pull from for text instead.
Definition at line 983 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_graffiti()
jmapgen_graffiti::jmapgen_graffiti (const JsonObject & jsi) inline
Definition at line 988 of file mapgen.cpp.
                                                  :
            text( jsi.get_string( "text", "" ) )
            , snippet( jsi.get_string( "snippet", "" ) ) {
            if( text.empty() && snippet.empty() ) {
                jsi.throw_error( "jmapgen_graffiti: needs either text or snippet" );
            }
        }
References mapgen_defer::jsi, snippet, text, and JsonObject::throw_error().
Member Function Documentation
apply()
void jmapgen_graffiti::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 995 of file mapgen.cpp.
{
            const point r{ x.get(), y.get() };
            std::string graffiti;
            if( !snippet.empty() ) {
                // select a snippet from the category
                graffiti = SNIPPET.random_from_category( snippet ).value_or( translation() ).translated();
            } else if( !text.empty() ) {
                graffiti = text;
            }
            if( !graffiti.empty() ) {
                // replace tags
                graffiti = _( graffiti );
                std::string cityname = "illegible city name";
                tripoint abs_sub = dat.m.get_abs_sub();
                // TODO: fix point types
                const city *c = overmap_buffer.closest_city( tripoint_abs_sm( abs_sub ) ).city;
                if( c != nullptr ) {
                    cityname = c->name;
                }
                graffiti = apply_all_tags( graffiti, cityname );
            }
            dat.m.set_graffiti( tripoint( r, dat.m.get_abs_sub().z ), graffiti );
        }
References _, apply_all_tags(), c, city_reference::city, overmapbuffer::closest_city(), jmapgen_int::get(), map::get_abs_sub(), mapgendata::m, overmap_buffer, snippet_library::random_from_category(), map::set_graffiti(), snippet, SNIPPET, text, and tripoint::z.
apply_all_tags()
std::string jmapgen_graffiti::apply_all_tags (std::string graffiti, const std::string & cityname) const inline
Definition at line 1021 of file mapgen.cpp.
{
            replace_city_tag( graffiti, cityname );
            replace_name_tags( graffiti );
            return graffiti;
        }
References replace_city_tag(), and replace_name_tags().
Referenced by apply().
Member Data Documentation
snippet
std::string jmapgen_graffiti::snippet
Definition at line 987 of file mapgen.cpp.
Referenced by apply(), and jmapgen_graffiti().
text
std::string jmapgen_graffiti::text
Definition at line 986 of file mapgen.cpp.
Referenced by apply(), and jmapgen_graffiti().
The documentation for this class was generated from the following file:
src/mapgen.cpp