Cataclysm BN: zone_type Class Reference
zone_type Class Reference
#include <clzones.h>
Public Member Functions
zone_type ()=default
zone_type (const std::string &name, const std::string &desc)
std::string name () const
std::string desc () const
void load (const JsonObject &jo, const std::string &)
bool is_valid () const
Static Public Member Functions
static void reset_zones ()
static void load_zones (const JsonObject &jo, const std::string &src)
static const std::vector< zone_type > & get_all ()
All spells in the game.
Public Attributes
zone_type_id id
bool was_loaded = false
Private Attributes
std::string name_
std::string desc_
Detailed Description
Definition at line 34 of file clzones.h.
Constructor & Destructor Documentation
zone_type() [1/2]
zone_type::zone_type () default
zone_type() [2/2]
zone_type::zone_type (const std::string & name, const std::string & desc) inline explicit
Definition at line 45 of file clzones.h.
                                                                           : name_( name ),
            desc_( desc ) {}
Member Function Documentation
desc()
std::string zone_type::desc () const
Definition at line 142 of file clzones.cpp.
{
    return _( desc_ );
}
References _, and desc_.
get_all()
const std::vector< zone_type > & zone_type::get_all () static
All spells in the game.
Definition at line 164 of file clzones.cpp.
{
    return zone_type_factory.get_all();
}
References anonymous_namespace{clzones.cpp}::zone_type_factory.
Referenced by zone_manager::zone_manager().
is_valid()
bool zone_type::is_valid () const
load()
void zone_type::load (const JsonObject & jo, const std::string &)
Definition at line 179 of file clzones.cpp.
{
    mandatory( jo, was_loaded, "name", name_ );
    mandatory( jo, was_loaded, "id", id );
    optional( jo, was_loaded, "description", desc_, "" );
}
References desc_, mandatory(), name_, optional(), and was_loaded.
load_zones()
void zone_type::load_zones (const JsonObject & jo, const std::string & src) static
Definition at line 169 of file clzones.cpp.
{
    zone_type_factory.load( jo, src );
}
References anonymous_namespace{clzones.cpp}::zone_type_factory.
Referenced by DynamicDataLoader::initialize().
name()
std::string zone_type::name () const
Definition at line 137 of file clzones.cpp.
{
    return _( name_ );
}
References _, and name_.
reset_zones()
void zone_type::reset_zones () static
Definition at line 174 of file clzones.cpp.
{
    zone_type_factory.reset();
}
References anonymous_namespace{clzones.cpp}::zone_type_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
desc_
std::string zone_type::desc_ private
Definition at line 38 of file clzones.h.
Referenced by desc(), and load().
id
zone_type_id zone_type::id
Definition at line 41 of file clzones.h.
name_
std::string zone_type::name_ private
Definition at line 37 of file clzones.h.
Referenced by load(), and name().
was_loaded
bool zone_type::was_loaded = false
Definition at line 42 of file clzones.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp