Cataclysm BN: JsonDeserializer Class Reference
JsonDeserializer Class Reference abstract
#include <json.h>
Public Member Functions
virtual ~JsonDeserializer ()=default
virtual void deserialize (JsonIn &jsin)=0
JsonDeserializer ()=default
JsonDeserializer (JsonDeserializer &&)=default
JsonDeserializer (const JsonDeserializer &)=default
JsonDeserializer & operator= (JsonDeserializer &&)=default
JsonDeserializer & operator= (const JsonDeserializer &)=default
Detailed Description
Definition at line 1414 of file json.h.
Constructor & Destructor Documentation
~JsonDeserializer()
virtual JsonDeserializer::~JsonDeserializer () virtual default
JsonDeserializer() [1/3]
JsonDeserializer::JsonDeserializer () default
JsonDeserializer() [2/3]
JsonDeserializer::JsonDeserializer (JsonDeserializer &&) default
JsonDeserializer() [3/3]
JsonDeserializer::JsonDeserializer (const JsonDeserializer &) default
Member Function Documentation
deserialize()
virtual void JsonDeserializer::deserialize (JsonIn & jsin) pure virtual
Implemented in extended_photo_def, and anonymous_namespace{messages.cpp}::game_message.
Referenced by JsonIn::read(), read_from_file(), and read_from_file_optional().
operator=() [1/2]
JsonDeserializer & JsonDeserializer::operator= (const JsonDeserializer &) default
operator=() [2/2]
JsonDeserializer & JsonDeserializer::operator= (JsonDeserializer &&) default
The documentation for this class was generated from the following file:
src/json.h