Cataclysm BN: advanced_inv_area Class Reference
advanced_inv_area Class Reference
Defines the source of item stacks.
#include <advanced_inv_area.h>
Public Types
using itemstack = std::vector< std::list< item * > >
Public Member Functions
advanced_inv_area (aim_location id)
advanced_inv_area (aim_location id, point hscreen, tripoint off, const std::string &name, const std::string &shortname, std::string minimapname, std::string actionname, aim_location relative_location)
void init ()
template<typename T >
advanced_inv_area::itemstack i_stacked (T items)
units::volume free_volume (bool in_vehicle=false) const
int get_item_count () const
bool is_same (const advanced_inv_area &other) const
bool canputitems (const advanced_inv_listitem *advitem=nullptr)
item * get_container (bool in_vehicle=false)
void set_container (const advanced_inv_listitem *advitem)
bool is_container_valid (const item *it) const
void set_container_position ()
bool can_store_in_vehicle () const
Public Attributes
const aim_location id
point hscreen = point_zero
tripoint off
const std::string name = "fake"
Long name, displayed, translated.
const std::string shortname = "FK"
Shorter name (2 letters)
tripoint pos
bool canputitemsloc = false
Can we put items there? Only checks if location is valid, not if selected container in pane is.
vehicle * veh = nullptr
int vstor = 0
std::array< std::string, 2 > desc
std::string flags
units::volume volume
units::mass weight
int max_size = 0
const std::string minimapname
const std::string actionname
const aim_location relative_location
Detailed Description
Defines the source of item stacks.
Definition at line 43 of file advanced_inv_area.h.
Member Typedef Documentation
itemstack
using advanced_inv_area::itemstack = std::vector<std::list<item *> >
Definition at line 47 of file advanced_inv_area.h.
Constructor & Destructor Documentation
advanced_inv_area() [1/2]
advanced_inv_area::advanced_inv_area (aim_location id) inline
Definition at line 83 of file advanced_inv_area.h.
: id(id), relative_location(id) {}
advanced_inv_area() [2/2]
advanced_inv_area::advanced_inv_area (aim_location id, point hscreen, tripoint off, const std::string & name, const std::string & shortname, std::string minimapname, std::string actionname, aim_location relative_location)
Definition at line 49 of file advanced_inv_area.cpp.
                                                                       :
    id( id ), hscreen( h ),
    off( off ), name( name ), shortname( shortname ),
    canputitemsloc( false ), veh( nullptr ), vstor( -1 ), volume( 0_ml ),
    weight( 0_gram ), max_size( 0 ), minimapname( minimapname ), actionname( actionname ),
    relative_location( relative_location )
{
}
Member Function Documentation
can_store_in_vehicle()
bool advanced_inv_area::can_store_in_vehicle () const inline
Definition at line 105 of file advanced_inv_area.h.
{
            // disallow for non-valid vehicle locations
            if( id > AIM_DRAGGED || id < AIM_SOUTHWEST ) {
                return false;
            }
            return veh != nullptr && vstor >= 0;
        }
References AIM_DRAGGED, AIM_SOUTHWEST, veh, and vstor.
Referenced by get_container(), get_item_count(), and init().
canputitems()
bool advanced_inv_area::canputitems (const advanced_inv_listitem * advitem = nullptr)
Definition at line 223 of file advanced_inv_area.cpp.
{
    bool canputitems = false;
    bool from_vehicle = false;
    item *it = nullptr;
    switch( id ) {
        case AIM_CONTAINER:
            if( advitem != nullptr && advitem->is_item_entry() ) {
                it = advitem->items.front();
                from_vehicle = advitem->from_vehicle;
            }
            if( get_container( from_vehicle ) != nullptr ) {
                it = get_container( from_vehicle );
            }
            if( it != nullptr ) {
                canputitems = it->is_watertight_container();
            }
            break;
        default:
            canputitems = canputitemsloc;
            break;
    }
    return canputitems;
}
References AIM_CONTAINER, canputitems(), canputitemsloc, advanced_inv_listitem::from_vehicle, get_container(), advanced_inv_listitem::is_item_entry(), item::is_watertight_container(), and advanced_inv_listitem::items.
Referenced by canputitems().
free_volume()
units::volume advanced_inv_area::free_volume (bool in_vehicle = false) const
Definition at line 199 of file advanced_inv_area.cpp.
{
    // should be a specific location instead
    assert( id != AIM_ALL );
    if( id == AIM_INVENTORY || id == AIM_WORN ) {
        return g->u.volume_capacity() - g->u.volume_carried();
    }
    return in_vehicle ? veh->free_volume( vstor ) : get_map().free_volume( pos );
}
References AIM_ALL, AIM_INVENTORY, AIM_WORN, map::free_volume(), vehicle::free_volume(), g, get_map(), pos, veh, and vstor.
Referenced by advanced_inventory::move_all_items(), and advanced_inventory::query_charges().
get_container()
item * advanced_inv_area::get_container (bool in_vehicle = false)
Definition at line 248 of file advanced_inv_area.cpp.
{
    item *container = nullptr;
    if( uistate.adv_inv_container_location != -1 ) {
        // try to find valid container in the area
        if( uistate.adv_inv_container_location == AIM_INVENTORY ) {
            const invslice &stacks = g->u.inv.slice();
            // check index first
            if( stacks.size() > static_cast<size_t>( uistate.adv_inv_container_index ) ) {
                auto &it = stacks[uistate.adv_inv_container_index]->front();
                if( is_container_valid( &it ) ) {
                    container = &it;
                }
            }
            // try entire area
            if( container == nullptr ) {
                for( size_t x = 0; x < stacks.size(); ++x ) {
                    auto &it = stacks[x]->front();
                    if( is_container_valid( &it ) ) {
                        container = &it;
                        uistate.adv_inv_container_index = x;
                        break;
                    }
                }
            }
        } else if( uistate.adv_inv_container_location == AIM_WORN ) {
            auto &worn = g->u.worn;
            size_t idx = static_cast<size_t>( uistate.adv_inv_container_index );
            if( worn.size() > idx ) {
                auto iter = worn.begin();
                std::advance( iter, idx );
                if( is_container_valid( &*iter ) ) {
                    container = &*iter;
                }
            }
            // no need to reinvent the wheel
            if( container == nullptr ) {
                auto iter = worn.begin();
                for( size_t i = 0; i < worn.size(); ++i, ++iter ) {
                    if( is_container_valid( &*iter ) ) {
                        container = &*iter;
                        uistate.adv_inv_container_index = i;
                        break;
                    }
                }
            }
        } else {
            map &here = get_map();
            bool is_in_vehicle = veh &&
                                 ( uistate.adv_inv_container_in_vehicle || ( can_store_in_vehicle() && in_vehicle ) );
            const itemstack &stacks = is_in_vehicle ?
                                      i_stacked( veh->get_items( vstor ) ) :
                                      i_stacked( here.i_at( pos ) );
            // check index first
            if( stacks.size() > static_cast<size_t>( uistate.adv_inv_container_index ) ) {
                auto it = stacks[uistate.adv_inv_container_index].front();
                if( is_container_valid( it ) ) {
                    container = it;
                }
            }
            // try entire area
            if( container == nullptr ) {
                for( size_t x = 0; x < stacks.size(); ++x ) {
                    auto it = stacks[x].front();
                    if( is_container_valid( it ) ) {
                        container = it;
                        uistate.adv_inv_container_index = x;
                        break;
                    }
                }
            }
        }
        // no valid container in the area, resetting container
        if( container == nullptr ) {
            set_container( nullptr );
            desc[0] = _( "Invalid container" );
        }
    }
    return container;
}
References _, uistatedata::adv_inv_container_in_vehicle, uistatedata::adv_inv_container_index, uistatedata::adv_inv_container_location, AIM_INVENTORY, AIM_WORN, can_store_in_vehicle(), desc, g, vehicle::get_items(), get_map(), map::i_at(), i_stacked(), is_container_valid(), pos, set_container(), uistate, veh, and vstor.
Referenced by canputitems(), and init().
get_item_count()
int advanced_inv_area::get_item_count () const
Definition at line 34 of file advanced_inv_area.cpp.
{
    if( id == AIM_INVENTORY ) {
        return g->u.inv.size();
    } else if( id == AIM_WORN ) {
        return g->u.worn.size();
    } else if( id == AIM_ALL ) {
        return 0;
    } else if( id == AIM_DRAGGED ) {
        return can_store_in_vehicle() ? veh->get_items( vstor ).size() : 0;
    } else {
        return get_map().i_at( pos ).size();
    }
}
References AIM_ALL, AIM_DRAGGED, AIM_INVENTORY, AIM_WORN, can_store_in_vehicle(), g, vehicle::get_items(), get_map(), map::i_at(), pos, item_stack::size(), veh, and vstor.
Referenced by advanced_inventory::query_charges().
i_stacked()
template<typename T > template advanced_inv_area::itemstack advanced_inv_area::i_stacked< map_stack > (T items)
Definition at line 426 of file advanced_inv_area.cpp.
{
    //create a new container for our stacked items
    advanced_inv_area::itemstack stacks;
    //    // make a list of the items first, so we can add non stacked items back on
    //    std::list<item> items(things.begin(), things.end());
    // used to recall indices we stored `itype_id' item at in itemstack
    std::unordered_map<itype_id, std::set<int>> cache;
    // iterate through and create stacks
    for( auto &elem : items ) {
        const auto id = elem.typeId();
        auto iter = cache.find( id );
        bool got_stacked = false;
        // cache entry exists
        if( iter != cache.end() ) {
            // check to see if it stacks with each item in a stack, not just front()
            for( auto &idx : iter->second ) {
                for( auto &it : stacks[idx] ) {
                    if( ( got_stacked = it->display_stacked_with( elem ) ) ) {
                        stacks[idx].push_back( &elem );
                        break;
                    }
                }
                if( got_stacked ) {
                    break;
                }
            }
        }
        if( !got_stacked ) {
            cache[id].insert( stacks.size() );
            stacks.push_back( { &elem } );
        }
    }
    return stacks;
}
References id.
Referenced by get_container().
init()
void advanced_inv_area::init ()
Definition at line 61 of file advanced_inv_area.cpp.
{
    pos = g->u.pos() + off;
    veh = nullptr;
    vstor = -1;
    // must update in main function
    volume = 0_ml;
    // must update in main function
    weight = 0_gram;
    map &here = get_map();
    switch( id ) {
        case AIM_INVENTORY:
        case AIM_WORN:
            canputitemsloc = true;
            break;
        case AIM_DRAGGED:
            if( g->u.get_grab_type() != OBJECT_VEHICLE ) {
                canputitemsloc = false;
                desc[0] = _( "Not dragging any vehicle!" );
                break;
            }
            // offset for dragged vehicles is not statically initialized, so get it
            off = g->u.grab_point;
            // Reset position because offset changed
            pos = g->u.pos() + off;
            if( const cata::optional<vpart_reference> vp = here.veh_at( pos ).part_with_feature( "CARGO",
                    false ) ) {
                veh = &vp->vehicle();
                vstor = vp->part_index();
            } else {
                veh = nullptr;
                vstor = -1;
            }
            if( vstor >= 0 ) {
                desc[0] = veh->name;
                canputitemsloc = true;
                max_size = MAX_ITEM_IN_VEHICLE_STORAGE;
            } else {
                veh = nullptr;
                canputitemsloc = false;
                desc[0] = _( "No dragged vehicle!" );
            }
            break;
        case AIM_CONTAINER:
            // set container position based on location
            set_container_position();
            // location always valid, actual check is done in canputitems()
            // and depends on selected item in pane (if it is valid container)
            canputitemsloc = true;
            if( get_container() == nullptr ) {
                desc[0] = _( "Invalid container!" );
            }
            break;
        case AIM_ALL:
            desc[0] = _( "All 9 squares" );
            canputitemsloc = true;
            break;
        case AIM_ABOVE:
        case AIM_BELOW:
            if( !g->m.has_zlevels() || !g->m.valid_move( g->u.pos(), pos ) ) {
                canputitemsloc = false;
                break;
            }
        // Intentional fallthrough
        case AIM_SOUTHWEST:
        case AIM_SOUTH:
        case AIM_SOUTHEAST:
        case AIM_WEST:
        case AIM_CENTER:
        case AIM_EAST:
        case AIM_NORTHWEST:
        case AIM_NORTH:
        case AIM_NORTHEAST: {
            const cata::optional<vpart_reference> vp =
                here.veh_at( pos ).part_with_feature( "CARGO", false );
            if( vp ) {
                veh = &vp->vehicle();
                vstor = vp->part_index();
            } else {
                veh = nullptr;
                vstor = -1;
            }
            canputitemsloc = can_store_in_vehicle() || here.can_put_items_ter_furn( pos );
            max_size = MAX_ITEM_IN_SQUARE;
            if( can_store_in_vehicle() ) {
                std::string part_name = vp->info().name();
                desc[1] = vp->get_label().value_or( part_name );
            }
            // get graffiti or terrain name
            desc[0] = here.has_graffiti_at( pos ) ?
                      here.graffiti_at( pos ) : here.name( pos );
        }
        default:
            break;
    }
    /* assemble a list of interesting traits of the target square */
    // fields? with a special case for fire
    bool danger_field = false;
    const field &tmpfld = here.field_at( pos );
    for( auto &fld : tmpfld ) {
        const field_entry &cur = fld.second;
        if( fld.first.obj().has_fire ) {
            flags.append( _( " <color_white_red>FIRE</color>" ) );
        } else {
            if( cur.is_dangerous() ) {
                danger_field = true;
            }
        }
    }
    if( danger_field ) {
        flags.append( _( " DANGER" ) );
    }
    // trap?
    const trap &tr = here.tr_at( pos );
    if( tr.can_see( pos, g->u ) && !tr.is_benign() ) {
        flags.append( _( " TRAP" ) );
    }
    // water?
    static const std::array<ter_id, 8> ter_water = {
        {t_water_dp, t_water_pool, t_swater_dp, t_water_sh, t_swater_sh, t_sewage, t_water_moving_dp, t_water_moving_sh }
    };
    auto ter_check = [this]
    ( const ter_id & id ) {
        return get_map().ter( this->pos ) == id;
    };
    if( std::any_of( ter_water.begin(), ter_water.end(), ter_check ) ) {
        flags.append( _( " WATER" ) );
    }
    // remove leading space
    if( !flags.empty() && flags[0] == ' ' ) {
        flags.erase( 0, 1 );
    }
}
References _, AIM_ABOVE, AIM_ALL, AIM_BELOW, AIM_CENTER, AIM_CONTAINER, AIM_DRAGGED, AIM_EAST, AIM_INVENTORY, AIM_NORTH, AIM_NORTHEAST, AIM_NORTHWEST, AIM_SOUTH, AIM_SOUTHEAST, AIM_SOUTHWEST, AIM_WEST, AIM_WORN, map::can_put_items_ter_furn(), trap::can_see(), can_store_in_vehicle(), canputitemsloc, desc, map::field_at(), flags, g, get_container(), get_map(), map::graffiti_at(), map::has_graffiti_at(), id, trap::is_benign(), field_entry::is_dangerous(), MAX_ITEM_IN_SQUARE, MAX_ITEM_IN_VEHICLE_STORAGE, max_size, map::name(), vehicle::name, OBJECT_VEHICLE, off, optional_vpart_position::part_with_feature(), pos, set_container_position(), t_sewage, t_swater_dp, t_swater_sh, t_water_dp, t_water_moving_dp, t_water_moving_sh, t_water_pool, t_water_sh, map::ter(), map::tr_at(), cata::optional< T >::value_or(), veh, map::veh_at(), vehicle::vehicle(), volume, vstor, and weight.
is_container_valid()
bool advanced_inv_area::is_container_valid (const item * it) const
Definition at line 358 of file advanced_inv_area.cpp.
{
    if( it != nullptr ) {
        if( it->typeId() == uistate.adv_inv_container_type ) {
            if( it->is_container_empty() ) {
                if( uistate.adv_inv_container_content_type.is_null() ) {
                    return true;
                }
            } else {
                if( it->contents.front().typeId() == uistate.adv_inv_container_content_type ) {
                    return true;
                }
            }
        }
    }
    return false;
}
References uistatedata::adv_inv_container_content_type, uistatedata::adv_inv_container_type, item::contents, item_contents::front(), item::is_container_empty(), string_id< T >::is_null(), item::typeId(), and uistate.
Referenced by get_container().
is_same()
bool advanced_inv_area::is_same (const advanced_inv_area & other) const
Definition at line 209 of file advanced_inv_area.cpp.
{
    // All locations (sans the below) are compared by the coordinates,
    // e.g. dragged vehicle (to the south) and AIM_SOUTH are the same.
    if( id != AIM_INVENTORY && other.id != AIM_INVENTORY &&
        id != AIM_WORN && other.id != AIM_WORN &&
        id != AIM_CONTAINER && other.id != AIM_CONTAINER ) {
        //     have a vehicle?...     ...do the cargo index and pos match?...    ...at least pos?
        return veh == other.veh ? pos == other.pos && vstor == other.vstor : pos == other.pos;
    }
    //      ...is the id?
    return id == other.id;
}
References AIM_CONTAINER, AIM_INVENTORY, AIM_WORN, other, pos, veh, and vstor.
set_container()
void advanced_inv_area::set_container (const advanced_inv_listitem * advitem)
Definition at line 338 of file advanced_inv_area.cpp.
{
    if( advitem != nullptr ) {
        item *it( advitem->items.front() );
        uistate.adv_inv_container_location = advitem->area;
        uistate.adv_inv_container_in_vehicle = advitem->from_vehicle;
        uistate.adv_inv_container_index = advitem->idx;
        uistate.adv_inv_container_type = it->typeId();
        uistate.adv_inv_container_content_type = !it->is_container_empty() ?
                it->contents.front().typeId() : itype_id::NULL_ID();
        set_container_position();
    } else {
        uistate.adv_inv_container_location = -1;
        uistate.adv_inv_container_index = 0;
        uistate.adv_inv_container_in_vehicle = false;
        uistate.adv_inv_container_type = itype_id::NULL_ID();
        uistate.adv_inv_container_content_type = itype_id::NULL_ID();
    }
}
References uistatedata::adv_inv_container_content_type, uistatedata::adv_inv_container_in_vehicle, uistatedata::adv_inv_container_index, uistatedata::adv_inv_container_location, uistatedata::adv_inv_container_type, advanced_inv_listitem::area, item::contents, advanced_inv_listitem::from_vehicle, item_contents::front(), advanced_inv_listitem::idx, item::is_container_empty(), advanced_inv_listitem::items, string_id< itype >::NULL_ID(), set_container_position(), item::typeId(), and uistate.
Referenced by get_container().
set_container_position()
void advanced_inv_area::set_container_position ()
Definition at line 404 of file advanced_inv_area.cpp.
{
    // update the offset of the container based on location
    if( uistate.adv_inv_container_location == AIM_DRAGGED ) {
        off = g->u.grab_point;
    } else {
        off = aim_vector( static_cast<aim_location>( uistate.adv_inv_container_location ) );
    }
    // update the absolute position
    pos = g->u.pos() + off;
    // update vehicle information
    if( const cata::optional<vpart_reference> vp = get_map().veh_at( pos ).part_with_feature( "CARGO",
            false ) ) {
        veh = &vp->vehicle();
        vstor = vp->part_index();
    } else {
        veh = nullptr;
        vstor = -1;
    }
}
References uistatedata::adv_inv_container_location, AIM_DRAGGED, aim_vector(), g, get_map(), off, pos, uistate, veh, vehicle::vehicle(), and vstor.
Referenced by init(), and set_container().
Member Data Documentation
actionname
const std::string advanced_inv_area::actionname
Definition at line 79 of file advanced_inv_area.h.
canputitemsloc
bool advanced_inv_area::canputitemsloc = false
Can we put items there? Only checks if location is valid, not if selected container in pane is.
For full check use canputitems()
Definition at line 63 of file advanced_inv_area.h.
Referenced by canputitems(), and init().
desc
std::array<std::string, 2> advanced_inv_area::desc
Definition at line 68 of file advanced_inv_area.h.
Referenced by get_container(), init(), and advanced_inventory::redraw_pane().
flags
std::string advanced_inv_area::flags
Definition at line 70 of file advanced_inv_area.h.
Referenced by init().
hscreen
point advanced_inv_area::hscreen = point_zero
Definition at line 51 of file advanced_inv_area.h.
id
const aim_location advanced_inv_area::id
Definition at line 49 of file advanced_inv_area.h.
Referenced by i_stacked(), init(), and advanced_inventory::redraw_pane().
max_size
int advanced_inv_area::max_size = 0
Definition at line 75 of file advanced_inv_area.h.
Referenced by init(), and advanced_inventory::query_charges().
minimapname
const std::string advanced_inv_area::minimapname
Definition at line 77 of file advanced_inv_area.h.
name
const std::string advanced_inv_area::name = "fake"
Long name, displayed, translated.
Definition at line 55 of file advanced_inv_area.h.
Referenced by advanced_inventory::redraw_pane().
off
tripoint advanced_inv_area::off
Definition at line 53 of file advanced_inv_area.h.
Referenced by init(), advanced_inventory::move_all_items(), and set_container_position().
pos
tripoint advanced_inv_area::pos
Definition at line 60 of file advanced_inv_area.h.
Referenced by free_volume(), get_container(), get_item_count(), init(), is_same(), advanced_inventory::move_all_items(), and set_container_position().
relative_location
const aim_location advanced_inv_area::relative_location
Definition at line 81 of file advanced_inv_area.h.
shortname
const std::string advanced_inv_area::shortname = "FK"
Shorter name (2 letters)
Definition at line 58 of file advanced_inv_area.h.
veh
vehicle* advanced_inv_area::veh = nullptr
Definition at line 65 of file advanced_inv_area.h.
Referenced by can_store_in_vehicle(), free_volume(), get_container(), get_item_count(), init(), is_same(), advanced_inventory::move_all_items(), advanced_inventory::redraw_pane(), and set_container_position().
volume
units::volume advanced_inv_area::volume
Definition at line 72 of file advanced_inv_area.h.
Referenced by init(), and advanced_inventory::move_all_items().
vstor
int advanced_inv_area::vstor = 0
Definition at line 66 of file advanced_inv_area.h.
Referenced by can_store_in_vehicle(), free_volume(), get_container(), get_item_count(), init(), is_same(), advanced_inventory::move_all_items(), and set_container_position().
weight
units::mass advanced_inv_area::weight
Definition at line 73 of file advanced_inv_area.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/advanced_inv_area.h
src/advanced_inv_area.cpp