Cataclysm BN: set_transformed_iuse Class Reference
set_transformed_iuse Class Reference
This is a iuse_transform used by items with transform dependencies.
#include <iuse_actor.h>
Public Member Functions
int bypass (player &p, item &it, bool t, const tripoint &pos) const
Hack: Bypasses normal checks to transform an item.
set_transformed_iuse (const std::string &type="set_transformed")
~set_transformed_iuse () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_transform
iuse_transform (const std::string &type="transform")
~iuse_transform () override=default
std::string get_name () const override
Returns the translated name of the action.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
Public Attributes
bool restricted = true
Whether the object can only be transformed externally.
std::string dependencies
String defining flag needed on activating item.
Public Attributes inherited from iuse_transform
translation msg_transform
displayed if player sees transformation with s replaced by item name
itype_id target
type of the resulting item
itype_id container
if set transform item to container and place new item (of type target) inside
int ammo_qty = -1
if zero or positive set remaining ammo of target to this (after transformation)
std::vector< int > random_ammo_qty
if this has values, set remaining ammo of target to one of them chosen at random (after transformation)
int countdown = 0
if positive set transformed item active and start countdown
itype_id ammo_type
if both this and ammo_qty are specified then set target to this specific ammo
bool active = false
used to set the active property of the transformed target
bool need_worn = false
does the item requires to be worn to be activable
bool need_wielding = false
does the item requires to be wielded to be activable
int moves = 0
subtracted from Creature::moves when transformation is successful
int need_fire = 0
minimum number of fire charges required (if any) for transformation
translation need_fire_msg
displayed if item is in player possession with s replaced by item name
int need_charges = 0
minimum charges (if any) required for transformation
translation need_charges_msg
displayed if item is in player possession with s replaced by item name
std::map< quality_id, int > qualities_needed
Tool qualities needed, e.g.
translation menu_text
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This is a iuse_transform used by items with transform dependencies.
The player activates the corresponding set_transform item, which will transform these items. They can't be used by the player normally unless restricted set false.
Definition at line 349 of file iuse_actor.h.
Constructor & Destructor Documentation
set_transformed_iuse()
set_transformed_iuse::set_transformed_iuse (const std::string & type = "set_transformed") inline
Definition at line 365 of file iuse_actor.h.
: iuse_transform(type) {}
~set_transformed_iuse()
set_transformed_iuse::~set_transformed_iuse () override default
Member Function Documentation
bypass()
int set_transformed_iuse::bypass (player & p, item & it, bool t, const tripoint & pos) const
Hack: Bypasses normal checks to transform an item.
Definition at line 983 of file iuse_actor.cpp.
{
    return iuse_transform::use( p, it, t, pos );
}
References Character::pos(), and iuse_transform::use().
Referenced by item::on_takeoff(), item::on_wear(), item::process_tool(), and set_transform_iuse::use().
can_use()
ret_val< bool > set_transformed_iuse::can_use (const Character & , const item & , bool , const tripoint &) const override virtual
Reimplemented from iuse_transform.
Definition at line 988 of file iuse_actor.cpp.
{
    if( restricted ) {
        return ret_val<bool>::make_failure( _( "Activate via main piece." ) );
    }
    return ret_val<bool>::make_success();
}
References _, ret_val< T >::make_failure(), ret_val< T >::make_success(), and restricted.
clone()
std::unique_ptr< iuse_actor > set_transformed_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Reimplemented from iuse_transform.
Definition at line 960 of file iuse_actor.cpp.
{
    return std::make_unique<set_transformed_iuse>( *this );
}
load()
void set_transformed_iuse::load (const JsonObject & obj) override virtual
Reimplemented from iuse_transform.
Definition at line 965 of file iuse_actor.cpp.
{
    iuse_transform::load( obj );
    obj.read( "restricted", restricted );
    obj.read( "dependencies", dependencies );
}
References dependencies, iuse_transform::load(), JsonObject::read(), and restricted.
use()
int set_transformed_iuse::use (player & p, item & it, bool t, const tripoint & pos) const override virtual
Reimplemented from iuse_transform.
Definition at line 972 of file iuse_actor.cpp.
{
    if( t ) {
        return 0; // invoked from active item processing, do nothing.
    }
    iuse_transform::use( p, it, t, pos );
    return 0;
}
References Character::pos(), and iuse_transform::use().
Member Data Documentation
dependencies
std::string set_transformed_iuse::dependencies
String defining flag needed on activating item.
Definition at line 360 of file iuse_actor.h.
Referenced by load(), item::on_wear(), and item::process_tool().
restricted
bool set_transformed_iuse::restricted = true
Whether the object can only be transformed externally.
Definition at line 355 of file iuse_actor.h.
Referenced by can_use(), load(), item::on_wear(), and item::process_tool().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp