Cataclysm BN: MonsterGenerator Class Reference
MonsterGenerator Class Reference
#include <monstergenerator.h>
Public Member Functions
~MonsterGenerator ()
void reset ()
void load_monster (const JsonObject &jo, const std::string &src)
void load_species (const JsonObject &jo, const std::string &src)
void load_monster_attack (const JsonObject &jo, const std::string &src)
void finalize_mtypes ()
void check_monster_definitions () const
const std::vector< mtype > & get_all_mtypes () const
mtype_id get_valid_hallucination () const
Static Public Member Functions
static MonsterGenerator & generator ()
Public Attributes
std::array< int, m_flag::MF_MAX > m_flag_usage_stats
Private Member Functions
MonsterGenerator ()
void init_phases ()
void init_death ()
void init_attack ()
void init_defense ()
void add_hardcoded_attack (const std::string &type, mon_action_attack f)
void add_attack (std::unique_ptr< mattack_actor >)
void add_attack (const mtype_special_attack &wrapper)
mtype_special_attack create_actor (const JsonObject &obj, const std::string &src) const
Gets an actor object without saving it anywhere.
void apply_species_attributes (mtype &mon)
void set_species_ids (mtype &mon)
void finalize_pathfinding_settings (mtype &mon)
Private Attributes
pimpl< generic_factory< mtype > > mon_templates
pimpl< generic_factory< species_type > > mon_species
std::vector< mtype_id > hallucination_monsters
std::map< std::string, phase_id > phase_map
std::map< std::string, mon_action_death > death_map
std::map< std::string, mon_action_defend > defense_map
std::map< std::string, mtype_special_attack > attack_map
Friends
struct mtype
struct species_type
class mattack_actor
class string_id< mtype >
class string_id< species_type >
class string_id< mattack_actor >
Detailed Description
Definition at line 49 of file monstergenerator.h.
Constructor & Destructor Documentation
~MonsterGenerator()
MonsterGenerator::~MonsterGenerator () default
MonsterGenerator()
MonsterGenerator::MonsterGenerator () private
Definition at line 218 of file monstergenerator.cpp.
    : mon_templates( "monster type" )
    , mon_species( "species" )
{
    mon_templates->insert( mtype() );
    mon_species->insert( species_type() );
    init_phases();
    init_attack();
    init_defense();
    init_death();
}
References init_attack(), init_death(), init_defense(), init_phases(), mon_species, mon_templates, mtype, and species_type.
Member Function Documentation
add_attack() [1/2]
void MonsterGenerator::add_attack (const mtype_special_attack & wrapper) private
Definition at line 1000 of file monstergenerator.cpp.
{
    if( attack_map.count( wrapper->id ) > 0 ) {
        if( test_mode ) {
            debugmsg( "Overwriting monster attack with id %s", wrapper->id.c_str() );
        }
        attack_map.erase( wrapper->id );
    }
    attack_map.emplace( wrapper->id, wrapper );
}
References attack_map, debugmsg, mattack_actor::id, and test_mode.
add_attack() [2/2]
void MonsterGenerator::add_attack (std::unique_ptr< mattack_actor > ptr) private
Definition at line 995 of file monstergenerator.cpp.
{
    add_attack( mtype_special_attack( std::move( ptr ) ) );
}
References add_attack(), avatar_action::move(), and ptr().
Referenced by add_attack(), add_hardcoded_attack(), and load_monster_attack().
add_hardcoded_attack()
void MonsterGenerator::add_hardcoded_attack (const std::string & type, mon_action_attack f) private
Definition at line 990 of file monstergenerator.cpp.
{
    add_attack( mtype_special_attack( type, f ) );
}
References add_attack(), and type.
Referenced by init_attack().
apply_species_attributes()
void MonsterGenerator::apply_species_attributes (mtype & mon) private
Definition at line 399 of file monstergenerator.cpp.
{
    for( const auto &spec : mon.species ) {
        if( !spec.is_valid() ) {
            continue;
        }
        const species_type &mspec = spec.obj();
        mon.flags |= mspec.flags;
        mon.anger |= mspec.anger;
        mon.fear |= mspec.fear;
        mon.placate |= mspec.placate;
    }
}
References species_type::anger, mtype::anger, species_type::fear, mtype::fear, species_type::flags, mtype::flags, species_type::placate, mtype::placate, and mtype::species.
Referenced by finalize_mtypes().
check_monster_definitions()
void MonsterGenerator::check_monster_definitions () const
Definition at line 1201 of file monstergenerator.cpp.
{
    for( const auto &mon : mon_templates->get_all() ) {
        if( !mon.harvest && !mon.has_flag( MF_ELECTRONIC ) && mon.id ) {
            debugmsg( "monster %s has no harvest entry", mon.id.c_str(), mon.harvest.c_str() );
        }
        if( mon.has_flag( MF_MILKABLE ) && mon.starting_ammo.empty() ) {
            debugmsg( "monster %s is flagged milkable, but has no starting ammo", mon.id.c_str() );
        }
        if( mon.has_flag( MF_MILKABLE ) && !mon.starting_ammo.empty() &&
            !item( mon.starting_ammo.begin()->first ).made_of( LIQUID ) ) {
            debugmsg( "monster % is flagged milkable, but starting ammo %s is not a liquid type",
                      mon.id.c_str(), mon.starting_ammo.begin()->first.str() );
        }
        if( mon.has_flag( MF_MILKABLE ) && mon.starting_ammo.size() > 1 ) {
            debugmsg( "monster % is flagged milkable, but has multiple starting_ammo defined", mon.id.c_str() );
        }
        for( auto &spec : mon.species ) {
            if( !spec.is_valid() ) {
                debugmsg( "monster %s has invalid species %s", mon.id.c_str(), spec.c_str() );
            }
        }
        if( mon.death_drops && !item_group::group_is_defined( mon.death_drops ) ) {
            debugmsg( "monster %s has unknown death drop item group: %s", mon.id.c_str(),
                      mon.death_drops.c_str() );
        }
        for( auto &m : mon.mat ) {
            if( m.str() == "null" || !m.is_valid() ) {
                debugmsg( "monster %s has unknown material: %s", mon.id.c_str(), m.c_str() );
            }
        }
        if( !mon.revert_to_itype.is_empty() && !mon.revert_to_itype.is_valid() ) {
            debugmsg( "monster %s has unknown revert_to_itype: %s", mon.id.c_str(),
                      mon.revert_to_itype.c_str() );
        }
        if( !mon.mech_weapon.is_empty() && !mon.mech_weapon.is_valid() ) {
            debugmsg( "monster %s has unknown mech_weapon: %s", mon.id.c_str(),
                      mon.mech_weapon.c_str() );
        }
        if( !mon.mech_battery.is_empty() && !mon.mech_battery.is_valid() ) {
            debugmsg( "monster %s has unknown mech_battery: %s", mon.id.c_str(),
                      mon.mech_battery.c_str() );
        }
        for( const scenttype_id &s_id : mon.scents_tracked ) {
            if( !s_id.is_empty() && !s_id.is_valid() ) {
                debugmsg( "monster %s has unknown scents_tracked %s", mon.id.c_str(), s_id.c_str() );
            }
        }
        for( const scenttype_id &s_id : mon.scents_ignored ) {
            if( !s_id.is_empty() && !s_id.is_valid() ) {
                debugmsg( "monster %s has unknown scents_ignored %s", mon.id.c_str(), s_id.c_str() );
            }
        }
        for( auto &s : mon.starting_ammo ) {
            if( !s.first.is_valid() ) {
                debugmsg( "starting ammo %s of monster %s is unknown", s.first.c_str(), mon.id.c_str() );
            }
        }
        for( auto &e : mon.atk_effs ) {
            if( !e.id.is_valid() ) {
                debugmsg( "attack effect %s of monster %s is unknown", e.id.c_str(), mon.id.c_str() );
            }
        }
        for( const std::pair<const emit_id, time_duration> &e : mon.emit_fields ) {
            const emit_id emid = e.first;
            if( !emid.is_valid() ) {
                debugmsg( "monster %s has invalid emit source %s", mon.id.c_str(), emid.c_str() );
            }
        }
        if( mon.upgrades ) {
            if( mon.half_life < 0 && mon.age_grow < 0 ) {
                debugmsg( "half_life %d and age_grow %d (<0) of monster %s is invalid",
                          mon.half_life, mon.age_grow, mon.id.c_str() );
            }
            if( !mon.upgrade_into && !mon.upgrade_group ) {
                debugmsg( "no into nor into_group defined for monster %s", mon.id.c_str() );
            }
            if( mon.upgrade_into && mon.upgrade_group ) {
                debugmsg( "both into and into_group defined for monster %s", mon.id.c_str() );
            }
            if( !mon.upgrade_into.is_valid() ) {
                debugmsg( "upgrade_into %s of monster %s is not a valid monster id",
                          mon.upgrade_into.c_str(), mon.id.c_str() );
            }
            if( !mon.upgrade_group.is_valid() ) {
                debugmsg( "upgrade_group %s of monster %s is not a valid monster group id",
                          mon.upgrade_group.c_str(), mon.id.c_str() );
            }
        }
        if( mon.reproduces ) {
            if( !mon.baby_timer || *mon.baby_timer <= 0_seconds ) {
                debugmsg( "Time between reproductions (%d) is invalid for %s",
                          mon.baby_timer ? to_turns<int>( *mon.baby_timer ) : -1, mon.id.c_str() );
            }
            if( mon.baby_count < 1 ) {
                debugmsg( "Number of children (%d) is invalid for %s",
                          mon.baby_count, mon.id.c_str() );
            }
            if( !mon.baby_monster && mon.baby_egg.is_null() ) {
                debugmsg( "No baby or egg defined for monster %s", mon.id.c_str() );
            }
            if( mon.baby_monster && !mon.baby_egg.is_null() ) {
                debugmsg( "Both an egg and a live birth baby are defined for %s", mon.id.c_str() );
            }
            if( !mon.baby_monster.is_valid() ) {
                debugmsg( "baby_monster %s of monster %s is not a valid monster id",
                          mon.baby_monster.c_str(), mon.id.c_str() );
            }
            if( !mon.baby_egg.is_valid() ) {
                debugmsg( "item_id %s of monster %s is not a valid item id",
                          mon.baby_egg.c_str(), mon.id.c_str() );
            }
        }
    }
}
References string_id< T >::c_str(), debugmsg, item_group::group_is_defined(), string_id< T >::is_empty(), string_id< T >::is_valid(), LIQUID, item::made_of(), MF_ELECTRONIC, MF_MILKABLE, and mon_templates.
Referenced by DynamicDataLoader::check_consistency().
create_actor()
mtype_special_attack MonsterGenerator::create_actor (const JsonObject & obj, const std::string & src) const private
Gets an actor object without saving it anywhere.
Definition at line 1013 of file monstergenerator.cpp.
{
    // Legacy support: tolerate attack types being specified as the type
    const std::string type = obj.get_string( "type", "monster_attack" );
    const std::string attack_type = obj.get_string( "attack_type", type );
    if( type != "monster_attack" && attack_type != type ) {
        obj.throw_error(
            R"(Specifying "attack_type" is only allowed when "type" is "monster_attack" or not specified)",
            "type" );
    }
    std::unique_ptr<mattack_actor> new_attack;
    if( attack_type == "monster_attack" ) {
        const std::string id = obj.get_string( "id" );
        const auto &iter = attack_map.find( id );
        if( iter == attack_map.end() ) {
            obj.throw_error( "Monster attacks must specify type and/or id", "type" );
        }
        new_attack = iter->second->clone();
    } else if( attack_type == "leap" ) {
        new_attack = std::make_unique<leap_actor>();
    } else if( attack_type == "melee" ) {
        new_attack = std::make_unique<melee_actor>();
    } else if( attack_type == "bite" ) {
        new_attack = std::make_unique<bite_actor>();
    } else if( attack_type == "gun" ) {
        new_attack = std::make_unique<gun_actor>();
    } else if( attack_type == "spell" ) {
        new_attack = std::make_unique<mon_spellcasting_actor>();
    } else {
        obj.throw_error( "unknown monster attack", "attack_type" );
    }
    new_attack->load( obj, src );
    return mtype_special_attack( std::move( new_attack ) );
}
References attack_map, JsonObject::get_string(), avatar_action::move(), JsonObject::throw_error(), and type.
Referenced by mtype::add_special_attack(), and load_monster_attack().
finalize_mtypes()
void MonsterGenerator::finalize_mtypes ()
Definition at line 345 of file monstergenerator.cpp.
{
    mon_templates->finalize();
    for( const auto &elem : mon_templates->get_all() ) {
        mtype &mon = const_cast<mtype &>( elem );
        apply_species_attributes( mon );
        set_species_ids( mon );
        mon.size = volume_to_size( mon.volume );
        // adjust for worldgen difficulty parameters
        mon.speed *= get_option<int>( "MONSTER_SPEED" )      / 100.0;
        mon.hp    *= get_option<int>( "MONSTER_RESILIENCE" ) / 100.0;
        for( monster_adjustment adj : adjustments ) {
            adj.apply( mon );
        }
        if( mon.bash_skill < 0 ) {
            mon.bash_skill = calc_bash_skill( mon );
        }
        if( mon.armor_bash < 0 ) {
            mon.armor_bash = 0;
        }
        if( mon.armor_cut < 0 ) {
            mon.armor_cut = 0;
        }
        if( mon.armor_stab < 0 ) {
            mon.armor_stab = mon.armor_cut * 0.8;
        }
        if( mon.armor_bullet < 0 ) {
            mon.armor_bullet = 0;
        }
        if( mon.armor_acid < 0 ) {
            mon.armor_acid = mon.armor_cut * 0.5;
        }
        if( mon.armor_fire < 0 ) {
            mon.armor_fire = 0;
        }
        // Lower bound for hp scaling
        mon.hp = std::max( mon.hp, 1 );
        build_behavior_tree( mon );
        finalize_pathfinding_settings( mon );
    }
    for( const auto &mon : mon_templates->get_all() ) {
        if( !mon.has_flag( MF_NOT_HALLU ) ) {
            hallucination_monsters.push_back( mon.id );
        }
    }
}
References adjustments, apply_species_attributes(), mtype::armor_acid, mtype::armor_bash, mtype::armor_bullet, mtype::armor_cut, mtype::armor_fire, mtype::armor_stab, mtype::bash_skill, build_behavior_tree(), calc_bash_skill(), finalize_pathfinding_settings(), hallucination_monsters, mtype::hp, MF_NOT_HALLU, mon_templates, set_species_ids(), mtype::size, mtype::speed, mtype::volume, and volume_to_size().
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_pathfinding_settings()
void MonsterGenerator::finalize_pathfinding_settings (mtype & mon) private
Definition at line 414 of file monstergenerator.cpp.
{
    if( mon.path_settings.max_length < 0 ) {
        mon.path_settings.max_length = mon.path_settings.max_dist * 5;
    }
    if( mon.path_settings.bash_strength < 0 ) {
        mon.path_settings.bash_strength = mon.bash_skill;
    }
    if( mon.has_flag( MF_CLIMBS ) ) {
        mon.path_settings.climb_cost = 3;
    }
}
References mtype::bash_skill, pathfinding_settings::bash_strength, pathfinding_settings::climb_cost, mtype::has_flag(), pathfinding_settings::max_dist, pathfinding_settings::max_length, MF_CLIMBS, and mtype::path_settings.
Referenced by finalize_mtypes().
generator()
static MonsterGenerator & MonsterGenerator::generator () inline static
Definition at line 52 of file monstergenerator.h.
{
            static MonsterGenerator generator;
            return generator;
        }
References generator().
Referenced by safemode::add_rules(), mtype::add_special_attack(), DynamicDataLoader::check_consistency(), debug_menu::debug(), DynamicDataLoader::finalize_loaded_data(), generator(), mtype::has_flag(), defense_game::init_mtypes(), DynamicDataLoader::initialize(), mtype::load(), game::spawn_hallucination(), safemode::test_pattern(), DynamicDataLoader::unload_data(), debug_menu::wishmonster(), and memorial_logger::write().
get_all_mtypes()
const std::vector< mtype > & MonsterGenerator::get_all_mtypes () const
Definition at line 957 of file monstergenerator.cpp.
{
    return mon_templates->get_all();
}
References mon_templates.
get_valid_hallucination()
mtype_id MonsterGenerator::get_valid_hallucination () const
Definition at line 962 of file monstergenerator.cpp.
{
    return random_entry( hallucination_monsters );
}
References hallucination_monsters, and random_entry().
Referenced by game::spawn_hallucination().
init_attack()
void MonsterGenerator::init_attack () private
Definition at line 520 of file monstergenerator.cpp.
{
    add_hardcoded_attack( "NONE", mattack::none );
    add_hardcoded_attack( "EAT_CROP", mattack::eat_crop );
    add_hardcoded_attack( "EAT_FOOD", mattack::eat_food );
    add_hardcoded_attack( "ANTQUEEN", mattack::antqueen );
    add_hardcoded_attack( "CHECK_UP", mattack::nurse_check_up );
    add_hardcoded_attack( "ASSIST", mattack::nurse_assist );
    add_hardcoded_attack( "OPERATE", mattack::nurse_operate );
    add_hardcoded_attack( "PAID_BOT", mattack::check_money_left );
    add_hardcoded_attack( "SHRIEK", mattack::shriek );
    add_hardcoded_attack( "SHRIEK_ALERT", mattack::shriek_alert );
    add_hardcoded_attack( "SHRIEK_STUN", mattack::shriek_stun );
    add_hardcoded_attack( "RATTLE", mattack::rattle );
    add_hardcoded_attack( "HOWL", mattack::howl );
    add_hardcoded_attack( "ACID", mattack::acid );
    add_hardcoded_attack( "ACID_BARF", mattack::acid_barf );
    add_hardcoded_attack( "ACID_ACCURATE", mattack::acid_accurate );
    add_hardcoded_attack( "SHOCKSTORM", mattack::shockstorm );
    add_hardcoded_attack( "SHOCKING_REVEAL", mattack::shocking_reveal );
    add_hardcoded_attack( "PULL_METAL_WEAPON", mattack::pull_metal_weapon );
    add_hardcoded_attack( "BOOMER", mattack::boomer );
    add_hardcoded_attack( "BOOMER_GLOW", mattack::boomer_glow );
    add_hardcoded_attack( "RESURRECT", mattack::resurrect );
    add_hardcoded_attack( "SMASH", mattack::smash );
    add_hardcoded_attack( "SCIENCE", mattack::science );
    add_hardcoded_attack( "GROWPLANTS", mattack::growplants );
    add_hardcoded_attack( "GROW_VINE", mattack::grow_vine );
    add_hardcoded_attack( "VINE", mattack::vine );
    add_hardcoded_attack( "SPIT_SAP", mattack::spit_sap );
    add_hardcoded_attack( "TRIFFID_HEARTBEAT", mattack::triffid_heartbeat );
    add_hardcoded_attack( "FUNGUS", mattack::fungus );
    add_hardcoded_attack( "FUNGUS_CORPORATE", mattack::fungus_corporate );
    add_hardcoded_attack( "FUNGUS_HAZE", mattack::fungus_haze );
    add_hardcoded_attack( "FUNGUS_BIG_BLOSSOM", mattack::fungus_big_blossom );
    add_hardcoded_attack( "FUNGUS_INJECT", mattack::fungus_inject );
    add_hardcoded_attack( "FUNGUS_BRISTLE", mattack::fungus_bristle );
    add_hardcoded_attack( "FUNGUS_GROWTH", mattack::fungus_growth );
    add_hardcoded_attack( "FUNGUS_SPROUT", mattack::fungus_sprout );
    add_hardcoded_attack( "FUNGUS_FORTIFY", mattack::fungus_fortify );
    add_hardcoded_attack( "DERMATIK", mattack::dermatik );
    add_hardcoded_attack( "DERMATIK_GROWTH", mattack::dermatik_growth );
    add_hardcoded_attack( "FUNGAL_TRAIL", mattack::fungal_trail );
    add_hardcoded_attack( "PLANT", mattack::plant );
    add_hardcoded_attack( "DISAPPEAR", mattack::disappear );
    add_hardcoded_attack( "FORMBLOB", mattack::formblob );
    add_hardcoded_attack( "CALLBLOBS", mattack::callblobs );
    add_hardcoded_attack( "JACKSON", mattack::jackson );
    add_hardcoded_attack( "DANCE", mattack::dance );
    add_hardcoded_attack( "DOGTHING", mattack::dogthing );
    add_hardcoded_attack( "TENTACLE", mattack::tentacle );
    add_hardcoded_attack( "GENE_STING", mattack::gene_sting );
    add_hardcoded_attack( "PARA_STING", mattack::para_sting );
    add_hardcoded_attack( "TRIFFID_GROWTH", mattack::triffid_growth );
    add_hardcoded_attack( "STARE", mattack::stare );
    add_hardcoded_attack( "FEAR_PARALYZE", mattack::fear_paralyze );
    add_hardcoded_attack( "PHOTOGRAPH", mattack::photograph );
    add_hardcoded_attack( "TAZER", mattack::tazer );
    add_hardcoded_attack( "SEARCHLIGHT", mattack::searchlight );
    add_hardcoded_attack( "FLAMETHROWER", mattack::flamethrower );
    add_hardcoded_attack( "COPBOT", mattack::copbot );
    add_hardcoded_attack( "CHICKENBOT", mattack::chickenbot );
    add_hardcoded_attack( "MULTI_ROBOT", mattack::multi_robot );
    add_hardcoded_attack( "RATKING", mattack::ratking );
    add_hardcoded_attack( "GENERATOR", mattack::generator );
    add_hardcoded_attack( "UPGRADE", mattack::upgrade );
    add_hardcoded_attack( "BREATHE", mattack::breathe );
    add_hardcoded_attack( "IMPALE", mattack::impale );
    add_hardcoded_attack( "BRANDISH", mattack::brandish );
    add_hardcoded_attack( "FLESH_GOLEM", mattack::flesh_golem );
    add_hardcoded_attack( "ABSORB_MEAT", mattack::absorb_meat );
    add_hardcoded_attack( "LUNGE", mattack::lunge );
    add_hardcoded_attack( "LONGSWIPE", mattack::longswipe );
    add_hardcoded_attack( "PARROT", mattack::parrot );
    add_hardcoded_attack( "PARROT_AT_DANGER", mattack::parrot_at_danger );
    add_hardcoded_attack( "DARKMAN", mattack::darkman );
    add_hardcoded_attack( "SLIMESPRING", mattack::slimespring );
    add_hardcoded_attack( "EVOLVE_KILL_STRIKE", mattack::evolve_kill_strike );
    add_hardcoded_attack( "LEECH_SPAWNER", mattack::leech_spawner );
    add_hardcoded_attack( "MON_LEECH_EVOLUTION", mattack::mon_leech_evolution );
    add_hardcoded_attack( "TINDALOS_TELEPORT", mattack::tindalos_teleport );
    add_hardcoded_attack( "FLESH_TENDRIL", mattack::flesh_tendril );
    add_hardcoded_attack( "BIO_OP_BIOJUTSU", mattack::bio_op_random_biojutsu );
    add_hardcoded_attack( "BIO_OP_TAKEDOWN", mattack::bio_op_takedown );
    add_hardcoded_attack( "BIO_OP_IMPALE", mattack::bio_op_impale );
    add_hardcoded_attack( "BIO_OP_DISARM", mattack::bio_op_disarm );
    add_hardcoded_attack( "SUICIDE", mattack::suicide );
    add_hardcoded_attack( "KAMIKAZE", mattack::kamikaze );
    add_hardcoded_attack( "GRENADIER", mattack::grenadier );
    add_hardcoded_attack( "GRENADIER_ELITE", mattack::grenadier_elite );
    add_hardcoded_attack( "RIOTBOT", mattack::riotbot );
    add_hardcoded_attack( "STRETCH_ATTACK", mattack::stretch_attack );
    add_hardcoded_attack( "STRETCH_BITE", mattack::stretch_bite );
    add_hardcoded_attack( "RANGED_PULL", mattack::ranged_pull );
    add_hardcoded_attack( "GRAB", mattack::grab );
    add_hardcoded_attack( "GRAB_DRAG", mattack::grab_drag );
    add_hardcoded_attack( "DOOT", mattack::doot );
    add_hardcoded_attack( "ZOMBIE_FUSE", mattack::zombie_fuse );
}
References mattack::absorb_meat(), mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), add_hardcoded_attack(), mattack::antqueen(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), mattack::breathe(), mattack::callblobs(), mattack::check_money_left(), mattack::chickenbot(), mattack::copbot(), mattack::dance(), mattack::darkman(), mattack::dermatik(), mattack::dermatik_growth(), mattack::disappear(), mattack::dogthing(), mattack::doot(), mattack::eat_crop(), mattack::eat_food(), mattack::evolve_kill_strike(), mattack::fear_paralyze(), mattack::flamethrower(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::formblob(), mattack::fungal_trail(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_growth(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), mattack::gene_sting(), mattack::generator(), mattack::grab(), mattack::grab_drag(), mattack::grenadier(), mattack::grenadier_elite(), mattack::grow_vine(), mattack::growplants(), mattack::howl(), mattack::impale(), mattack::jackson(), mattack::kamikaze(), mattack::leech_spawner(), mattack::longswipe(), mattack::lunge(), mattack::mon_leech_evolution(), mattack::multi_robot(), mattack::none(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), mattack::para_sting(), mattack::parrot(), mattack::parrot_at_danger(), mattack::photograph(), mattack::plant(), mattack::pull_metal_weapon(), mattack::ranged_pull(), mattack::ratking(), mattack::rattle(), mattack::resurrect(), mattack::riotbot(), mattack::science(), mattack::searchlight(), mattack::shocking_reveal(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::slimespring(), mattack::smash(), mattack::spit_sap(), mattack::stare(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::suicide(), mattack::tazer(), mattack::tentacle(), mattack::tindalos_teleport(), mattack::triffid_growth(), mattack::triffid_heartbeat(), mattack::upgrade(), mattack::vine(), and mattack::zombie_fuse().
Referenced by MonsterGenerator(), and reset().
init_death()
void MonsterGenerator::init_death () private
Definition at line 438 of file monstergenerator.cpp.
{
    // Drop a body
    death_map["NORMAL"] = &mdeath::normal;
    // Explodes in gibs and chunks
    death_map["SPLATTER"] = &mdeath::splatter;
    // Acid instead of a body
    death_map["ACID"] = &mdeath::acid;
    // Explodes in vomit :3
    death_map["BOOMER"] = &mdeath::boomer;
    // Explodes in glowing vomit :3
    death_map["BOOMER_GLOW"] = &mdeath::boomer_glow;
    // Kill all nearby vines
    death_map["KILL_VINES"] = &mdeath::kill_vines;
    // Kill adjacent vine if it's cut
    death_map["VINE_CUT"] = &mdeath::vine_cut;
    // Destroy all roots
    death_map["TRIFFID_HEART"] = &mdeath::triffid_heart;
    // Explodes in spores D:
    death_map["FUNGUS"] = &mdeath::fungus;
    // Falls apart
    death_map["DISINTEGRATE"] = &mdeath::disintegrate;
    // Spawns 2 half-worms
    death_map["WORM"] = &mdeath::worm;
    // Hallucination disappears
    death_map["DISAPPEAR"] = &mdeath::disappear;
    // Morale penalty
    death_map["GUILT"] = &mdeath::guilt;
    // Frees blobs, redirects to brainblob()
    death_map["BRAINBLOB"] = &mdeath::brainblob;
    // Creates more blobs
    death_map["BLOBSPLIT"] = &mdeath::blobsplit;
    // Reverts dancers
    death_map["JACKSON"] = &mdeath::jackson;
    // Normal death, but melts
    death_map["MELT"] = &mdeath::melt;
    // Removes hypnosis if last one
    death_map["AMIGARA"] = &mdeath::amigara;
    // Turn into a full thing
    death_map["THING"] = &mdeath::thing;
    // Damaging explosion
    death_map["EXPLODE"] = &mdeath::explode;
    // Blinding ray
    death_map["FOCUSEDBEAM"] = &mdeath::focused_beam;
    // Spawns a broken robot.
    death_map["BROKEN"] = &mdeath::broken;
    // Cure verminitis
    death_map["RATKING"] = &mdeath::ratking;
    // Sight returns to normal
    death_map["DARKMAN"] = &mdeath::darkman;
    // Explodes in toxic gas
    death_map["GAS"] = &mdeath::gas;
    // All breathers die
    death_map["KILL_BREATHERS"] = &mdeath::kill_breathers;
    // Gives a message about destroying ammo and then calls "BROKEN"
    death_map["BROKEN_AMMO"] = &mdeath::broken_ammo;
    // Explode like a huge smoke bomb.
    death_map["SMOKEBURST"] = &mdeath::smokeburst;
    // Explode with a cloud of fungal haze.
    death_map["FUNGALBURST"] = &mdeath::fungalburst;
    // Snicker-snack!
    death_map["JABBERWOCKY"] = &mdeath::jabberwock;
    // Take them with you
    death_map["DETONATE"] = &mdeath::detonate;
    // Game over!  Defense mode
    death_map["GAMEOVER"] = &mdeath::gameover;
    // Spawn some cockroach nymphs
    death_map["PREG_ROACH"] = &mdeath::preg_roach;
    // Explode in a fireball
    death_map["FIREBALL"] = &mdeath::fireball;
    // Explode in a huge fireball
    death_map["CONFLAGRATION"] = &mdeath::conflagration;
    /* Currently Unimplemented */
    // Screams loudly
    //death_map["SHRIEK"] = &mdeath::shriek;
    // Wolf's howling
    //death_map["HOWL"] = &mdeath::howl;
    // Rattles like a rattlesnake
    //death_map["RATTLE"] = &mdeath::rattle;
}
References mdeath::acid(), mdeath::amigara(), mdeath::blobsplit(), mdeath::boomer(), mdeath::boomer_glow(), mdeath::brainblob(), mdeath::broken(), mdeath::broken_ammo(), mdeath::conflagration(), mdeath::darkman(), death_map, mdeath::detonate(), mdeath::disappear(), mdeath::disintegrate(), mdeath::explode(), mdeath::fireball(), mdeath::focused_beam(), mdeath::fungalburst(), mdeath::fungus(), mdeath::gameover(), mdeath::gas(), mdeath::guilt(), mdeath::jabberwock(), mdeath::jackson(), mdeath::kill_breathers(), mdeath::kill_vines(), mdeath::melt(), mdeath::normal(), mdeath::preg_roach(), mdeath::ratking(), mdeath::smokeburst(), mdeath::splatter(), mdeath::thing(), mdeath::triffid_heart(), mdeath::vine_cut(), and mdeath::worm().
Referenced by MonsterGenerator().
init_defense()
void MonsterGenerator::init_defense () private
Definition at line 620 of file monstergenerator.cpp.
{
    // No special attack-back
    defense_map["NONE"] = &mdefense::none;
    // Shock attacker on hit
    defense_map["ZAPBACK"] = &mdefense::zapback;
    // Splash acid on the attacker
    defense_map["ACIDSPLASH"] = &mdefense::acidsplash;
    // Blind fire on unseen attacker
    defense_map["RETURN_FIRE"] = &mdefense::return_fire;
}
References mdefense::acidsplash(), defense_map, mdefense::none(), mdefense::return_fire(), and mdefense::zapback().
Referenced by MonsterGenerator().
init_phases()
void MonsterGenerator::init_phases () private
Definition at line 429 of file monstergenerator.cpp.
{
    phase_map["NULL"] = PNULL;
    phase_map["SOLID"] = SOLID;
    phase_map["LIQUID"] = LIQUID;
    phase_map["GAS"] = GAS;
    phase_map["PLASMA"] = PLASMA;
}
References GAS, LIQUID, phase_map, PLASMA, PNULL, and SOLID.
Referenced by MonsterGenerator().
load_monster()
void MonsterGenerator::load_monster (const JsonObject & jo, const std::string & src)
Definition at line 644 of file monstergenerator.cpp.
{
    mon_templates->load( jo, src );
}
References mon_templates.
Referenced by DynamicDataLoader::initialize().
load_monster_attack()
void MonsterGenerator::load_monster_attack (const JsonObject & jo, const std::string & src)
Definition at line 1072 of file monstergenerator.cpp.
{
    add_attack( create_actor( jo, src ) );
}
References add_attack(), and create_actor().
Referenced by DynamicDataLoader::initialize().
load_species()
void MonsterGenerator::load_species (const JsonObject & jo, const std::string & src)
Definition at line 939 of file monstergenerator.cpp.
{
    mon_species->load( jo, src );
}
References mon_species.
Referenced by DynamicDataLoader::initialize().
reset()
void MonsterGenerator::reset ()
Definition at line 232 of file monstergenerator.cpp.
{
    mon_templates->reset();
    mon_templates->insert( mtype() );
    mon_species->reset();
    mon_species->insert( species_type() );
    hallucination_monsters.clear();
    attack_map.clear();
    // Hardcode attacks need to be re-added here
    // TODO: Move initialization from constructor to init()
    init_attack();
}
References attack_map, hallucination_monsters, init_attack(), mon_species, mon_templates, mtype, and species_type.
Referenced by DynamicDataLoader::unload_data().
set_species_ids()
void MonsterGenerator::set_species_ids (mtype & mon) private
Definition at line 632 of file monstergenerator.cpp.
{
    for( const auto &s : mon.species ) {
        if( s.is_valid() ) {
            mon.species_ptrs.insert( &s.obj() );
        } else {
            debugmsg( "Tried to assign species %s to monster %s, but no entry for the species exists",
                      s.c_str(), mon.id.c_str() );
        }
    }
}
References string_id< T >::c_str(), debugmsg, mtype::id, mtype::species, and mtype::species_ptrs.
Referenced by finalize_mtypes().
Friends And Related Function Documentation
mattack_actor
friend class mattack_actor friend
Definition at line 76 of file monstergenerator.h.
mtype
friend struct mtype friend
Definition at line 74 of file monstergenerator.h.
Referenced by MonsterGenerator(), and reset().
species_type
friend struct species_type friend
Definition at line 75 of file monstergenerator.h.
Referenced by MonsterGenerator(), and reset().
string_id< mattack_actor >
friend class string_id< mattack_actor > friend
Definition at line 98 of file monstergenerator.h.
string_id< mtype >
friend class string_id< mtype > friend
Definition at line 98 of file monstergenerator.h.
string_id< species_type >
friend class string_id< species_type > friend
Definition at line 98 of file monstergenerator.h.
Member Data Documentation
attack_map
std::map<std::string, mtype_special_attack> MonsterGenerator::attack_map private
Definition at line 111 of file monstergenerator.h.
Referenced by add_attack(), mtype::add_special_attack(), create_actor(), and reset().
death_map
std::map<std::string, mon_action_death> MonsterGenerator::death_map private
Definition at line 109 of file monstergenerator.h.
Referenced by init_death(), and mtype::load().
defense_map
std::map<std::string, mon_action_defend> MonsterGenerator::defense_map private
Definition at line 110 of file monstergenerator.h.
Referenced by init_defense(), and mtype::load().
hallucination_monsters
std::vector<mtype_id> MonsterGenerator::hallucination_monsters private
Definition at line 106 of file monstergenerator.h.
Referenced by finalize_mtypes(), get_valid_hallucination(), and reset().
m_flag_usage_stats
std::array<int, m_flag::MF_MAX> MonsterGenerator::m_flag_usage_stats
Definition at line 77 of file monstergenerator.h.
Referenced by debug_menu::debug(), and mtype::has_flag().
mon_species
pimpl<generic_factory<species_type> > MonsterGenerator::mon_species private
Definition at line 105 of file monstergenerator.h.
Referenced by load_species(), MonsterGenerator(), and reset().
mon_templates
pimpl<generic_factory<mtype> > MonsterGenerator::mon_templates private
Definition at line 104 of file monstergenerator.h.
Referenced by check_monster_definitions(), finalize_mtypes(), get_all_mtypes(), load_monster(), MonsterGenerator(), and reset().
phase_map
std::map<std::string, phase_id> MonsterGenerator::phase_map private
Definition at line 108 of file monstergenerator.h.
Referenced by init_phases(), and mtype::load().
The documentation for this class was generated from the following files:
src/monstergenerator.h
src/monstergenerator.cpp