Cataclysm BN: jmapgen_place Class Reference
jmapgen_place Class Reference
Where to place something on a map.
#include <mapgen.h>
Public Member Functions
jmapgen_place ()
jmapgen_place (const point &p)
jmapgen_place (const JsonObject &jsi)
void offset (const point &)
Public Attributes
jmapgen_int x
jmapgen_int y
jmapgen_int repeat
Detailed Description
Where to place something on a map.
Definition at line 170 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_place() [1/3]
jmapgen_place::jmapgen_place () inline
Definition at line 173 of file mapgen.h.
: x(0, 0), y(0, 0), repeat(1, 1) { }
jmapgen_place() [2/3]
jmapgen_place::jmapgen_place (const point & p) inline
Definition at line 174 of file mapgen.h.
: x(p.x), y(p.y), repeat(1, 1) { }
jmapgen_place() [3/3]
jmapgen_place::jmapgen_place (const JsonObject & jsi)
Definition at line 778 of file mapgen.cpp.
    : x( jsi, "x" )
    , y( jsi, "y" )
    , repeat( jsi, "repeat", 1, 1 )
{
}
Member Function Documentation
offset()
void jmapgen_place::offset (const point & offset)
Definition at line 785 of file mapgen.cpp.
{
    x.val -= offset.x;
    x.valmax -= offset.x;
    y.val -= offset.y;
    y.valmax -= offset.y;
}
References offset(), jmapgen_int::val, jmapgen_int::valmax, x, and y.
Referenced by jmapgen_objects::load_objects(), and offset().
Member Data Documentation
repeat
jmapgen_int jmapgen_place::repeat
Definition at line 179 of file mapgen.h.
Referenced by jmapgen_objects::load_objects().
x
jmapgen_int jmapgen_place::x
Definition at line 177 of file mapgen.h.
Referenced by jmapgen_objects::check_bounds(), and offset().
y
jmapgen_int jmapgen_place::y
Definition at line 178 of file mapgen.h.
Referenced by jmapgen_objects::check_bounds(), and offset().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp