Cataclysm BN: sew_advanced_actor Class Reference
sew_advanced_actor Class Reference
Modify clothing.
#include <iuse_actor.h>
Public Member Functions
sew_advanced_actor (const std::string &type="sew_advanced")
~sew_advanced_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::set< material_id > materials
Materials.
std::vector< clothing_mod_id > clothing_mods
Clothing mods.
skill_id used_skill
Skill used.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Modify clothing.
Definition at line 1239 of file iuse_actor.h.
Constructor & Destructor Documentation
sew_advanced_actor()
sew_advanced_actor::sew_advanced_actor (const std::string & type = "sew_advanced") inline
Definition at line 1249 of file iuse_actor.h.
: iuse_actor(type) {}
~sew_advanced_actor()
sew_advanced_actor::~sew_advanced_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > sew_advanced_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4941 of file iuse_actor.cpp.
{
    return std::make_unique<sew_advanced_actor>( *this );
}
load()
void sew_advanced_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 4700 of file iuse_actor.cpp.
{
    // Mandatory:
    for( const std::string line : obj.get_array( "materials" ) ) {
        materials.emplace( line );
    }
    for( const std::string line : obj.get_array( "clothing_mods" ) ) {
        clothing_mods.push_back( clothing_mod_id( line ) );
    }
    // TODO: Make skill non-mandatory while still erroring on invalid skill
    const std::string skill_string = obj.get_string( "skill" );
    used_skill = skill_id( skill_string );
    if( !used_skill.is_valid() ) {
        obj.throw_error( "Invalid skill", "skill" );
    }
}
References JsonObject::get_array(), JsonObject::get_string(), line(), skill_id, and JsonObject::throw_error().
use()
int sew_advanced_actor::use (player & p, item & it, bool , const tripoint &) const override virtual
Tailor randomly improves clothing modification efforts Dexterity randomly improves clothing modification efforts Perception randomly improves clothing modification efforts
Implements iuse_actor.
Definition at line 4718 of file iuse_actor.cpp.
{
    if( p.is_npc() ) {
        return 0;
    }
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( p.is_underwater() ) {
        p.add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( !character_funcs::can_see_fine_details( p ) ) {
        add_msg( m_info, _( "You can't see to sew!" ) );
        return 0;
    }
    auto filter = [this]( const item & itm ) {
        return itm.is_armor() && !itm.is_firearm() && !itm.is_power_armor() &&
               itm.made_of_any( materials );
    };
    // note: if !p.is_npc() then p is avatar.
    item_location loc = game_menus::inv::titled_filter_menu(
                            filter, *p.as_avatar(), _( "Enhance which clothing?" ) );
    if( !loc ) {
        p.add_msg_if_player( m_info, _( "You do not have that item!" ) );
        return 0;
    }
    item &mod = *loc;
    if( &mod == &it ) {
        p.add_msg_if_player( m_info,
                             _( "This can be used to repair or modify other items, not itself." ) );
        return 0;
    }
    // Gives us an item with the mod added or removed (toggled)
    const auto modded_copy = []( const item & proto, const std::string & mod_type ) {
        item mcopy = proto;
        if( mcopy.has_own_flag( mod_type ) == 0 ) {
            mcopy.set_flag( mod_type );
        } else {
            mcopy.unset_flag( mod_type );
        }
        return mcopy;
    };
    // Cache available materials
    std::map< itype_id, bool > has_enough;
    const int items_needed = mod.volume() / 750_ml + 1;
    const inventory &crafting_inv = p.crafting_inventory();
    // Go through all discovered repair items and see if we have any of them available
    for( auto &cm : clothing_mods::get_all() ) {
        has_enough[cm.item_string] = crafting_inv.has_amount( cm.item_string, items_needed );
    }
    int mod_count = 0;
    for( auto &cm : clothing_mods::get_all() ) {
        mod_count += mod.has_own_flag( cm.flag );
    }
    // We need extra thread to lose it on bad rolls
    const int thread_needed = mod.volume() / 125_ml + 10;
    std::vector<std::string> valid_mods;
    if( mod.find_armor_data() ) {
        valid_mods = mod.find_armor_data()->valid_mods;
    }
    const auto get_compare_color = [&]( const int before, const int after,
    const bool higher_is_better ) {
        return before == after ? c_unset : ( ( after > before ) == higher_is_better ? c_light_green :
                                             c_red );
    };
    const auto get_volume_compare_color = [&]( const units::volume & before,
                                          const units::volume & after,
    const bool higher_is_better ) {
        return before == after ? c_unset : ( ( after > before ) == higher_is_better ? c_light_green :
                                             c_red );
    };
    const auto format_desc_string = [&]( const std::string & label, const int before, const int after,
    const bool higher_is_better ) {
        return colorize( string_format( "%s: %d->%d\n", label, before, after ), get_compare_color( before,
                         after, higher_is_better ) );
    };
    uilist tmenu;
    tmenu.text = _( "How do you want to modify it?" );
    int index = 0;
    for( auto cm : clothing_mods ) {
        auto obj = cm.obj();
        item temp_item = modded_copy( mod, obj.flag );
        temp_item.update_clothing_mod_val();
        bool enab = false;
        std::string prompt;
        if( mod.has_own_flag( obj.flag ) == 0 ) {
            // TODO: Fix for UTF-8 strings
            // TODO: find other places where this is used and make a global function for all
            static const auto tolower = []( std::string t ) {
                if( !t.empty() ) {
                    t.front() = std::tolower( t.front() );
                }
                return t;
            };
            // Mod not already present, check if modification is possible
            if( obj.restricted &&
                std::find( valid_mods.begin(), valid_mods.end(), obj.flag ) == valid_mods.end() ) {
                //~ %1$s: modification desc, %2$s: mod name
                prompt = string_format( _( "Can't %1$s (incompatible with %2$s)" ), tolower( obj.implement_prompt ),
                                        mod.tname( 1, false ) );
            } else if( it.charges < thread_needed ) {
                //~ %1$s: modification desc, %2$d: number of thread needed
                prompt = string_format( _( "Can't %1$s (need %2$d thread loaded)" ),
                                        tolower( obj.implement_prompt ), thread_needed );
            } else if( !has_enough[obj.item_string] ) {
                //~ %1$s: modification desc, %2$d: number of items needed, %3$s: items needed
                prompt = string_format( _( "Can't %1$s (need %2$d %3$s)" ), tolower( obj.implement_prompt ),
                                        items_needed, item::nname( obj.item_string, items_needed ) );
            } else {
                // Modification is possible
                enab = true;
                //~ %1$s: modification desc, %2$d: number of items needed, %3$s: items needed, %4$s: number of thread needed
                prompt = string_format( _( "%1$s (%2$d %3$s and %4$d thread)" ), tolower( obj.implement_prompt ),
                                        items_needed, item::nname( obj.item_string, items_needed ), thread_needed );
            }
        } else {
            // Mod already present, give option to destroy
            enab = true;
            prompt = _( obj.destroy_prompt );
        }
        std::string desc;
        desc += format_desc_string( _( "Bash" ), mod.bash_resist(), temp_item.bash_resist(), true );
        desc += format_desc_string( _( "Cut" ), mod.cut_resist(), temp_item.cut_resist(), true );
        desc += format_desc_string( _( "Ballistic" ), mod.bullet_resist(), temp_item.bullet_resist(),
                                    true );
        desc += format_desc_string( _( "Acid" ), mod.acid_resist(), temp_item.acid_resist(), true );
        desc += format_desc_string( _( "Fire" ), mod.fire_resist(), temp_item.fire_resist(), true );
        desc += format_desc_string( _( "Warmth" ), mod.get_warmth(), temp_item.get_warmth(), true );
        desc += format_desc_string( _( "Encumbrance" ), mod.get_encumber( p ), temp_item.get_encumber( p ),
                                    false );
        auto before = mod.get_storage();
        auto after = temp_item.get_storage();
        desc += colorize( string_format( "%s: %s %s->%s %s\n", _( "Storage" ),
                                         format_volume( before ), volume_units_abbr(), format_volume( after ),
                                         volume_units_abbr() ), get_volume_compare_color( before, after, true ) );
        tmenu.addentry_desc( index++, enab, MENU_AUTOASSIGN, prompt, desc );
    }
    tmenu.textwidth = 80;
    tmenu.desc_enabled = true;
    tmenu.query();
    const int choice = tmenu.ret;
    if( choice < 0 || choice >= static_cast<int>( clothing_mods.size() ) ) {
        return 0;
    }
    // The mod player picked
    const std::string &the_mod = clothing_mods[choice].obj().flag;
    // If the picked mod already exists, player wants to destroy it
    if( mod.has_own_flag( the_mod ) ) {
        if( query_yn( _( "Are you sure?  You will not gain any materials back." ) ) ) {
            mod.unset_flag( the_mod );
        }
        mod.update_clothing_mod_val();
        return 0;
    }
    // Get the id of the material used
    const auto &repair_item = clothing_mods[choice].obj().item_string;
    std::vector<item_comp> comps;
    comps.push_back( item_comp( repair_item, items_needed ) );
    // TODO: this may take up to 2 minutes, and so should start an activity instead
    p.moves -= to_moves<int>( 30_seconds * character_funcs::fine_detail_vision_mod( p ) );
    p.practice( used_skill, items_needed * 3 + 3 );
    /** @EFFECT_TAILOR randomly improves clothing modification efforts */
    int rn = dice( 3, 2 + p.get_skill_level( used_skill ) ); // Skill
    /** @EFFECT_DEX randomly improves clothing modification efforts */
    rn += rng( 0, p.dex_cur / 2 );                    // Dexterity
    /** @EFFECT_PER randomly improves clothing modification efforts */
    rn += rng( 0, p.per_cur / 2 );                    // Perception
    rn -= mod_count * 10;                              // Other mods
    if( rn <= 8 ) {
        const std::string startdurability = mod.durability_indicator( true );
        const auto destroyed = mod.inc_damage();
        const std::string resultdurability = mod.durability_indicator( true );
        p.add_msg_if_player( m_bad, _( "You damage your %s trying to modify it!  ( %s-> %s)" ),
                             mod.tname( 1, false ), startdurability, resultdurability );
        if( destroyed ) {
            p.add_msg_if_player( m_bad, _( "You destroy it!" ) );
            p.i_rem_keep_contents( p.get_item_position( &mod ) );
        }
        return thread_needed / 2;
    } else if( rn <= 10 ) {
        p.add_msg_if_player( m_bad,
                             _( "You fail to modify the clothing, and you waste thread and materials." ) );
        p.consume_items( comps, 1, is_crafting_component );
        return thread_needed;
    } else if( rn <= 14 ) {
        p.add_msg_if_player( m_mixed, _( "You modify your %s, but waste a lot of thread." ),
                             mod.tname() );
        p.consume_items( comps, 1, is_crafting_component );
        mod.set_flag( the_mod );
        mod.update_clothing_mod_val();
        return thread_needed;
    }
    p.add_msg_if_player( m_good, _( "You modify your %s!" ), mod.tname() );
    mod.set_flag( the_mod );
    mod.update_clothing_mod_val();
    p.consume_items( comps, 1, is_crafting_component );
    return thread_needed / 2;
}
References _, item::acid_resist(), add_msg(), player::add_msg_if_player(), uilist::addentry_desc(), Creature::as_avatar(), item::bash_resist(), item::bullet_resist(), c_light_green, c_red, c_unset, character_funcs::can_see_fine_details(), item::charges, colorize(), player::consume_items(), Character::crafting_inventory(), item::cut_resist(), uilist::desc_enabled, destroyed, Character::dex_cur, dice(), detail::find(), character_funcs::fine_detail_vision_mod(), item::fire_resist(), format_volume(), clothing_mods::get_all(), item::get_encumber(), Character::get_item_position(), Character::get_skill_level(), item::get_storage(), item::get_warmth(), visitable< T >::has_amount(), item::has_own_flag(), Character::i_rem_keep_contents(), is_crafting_component(), Character::is_mounted(), player::is_npc(), Creature::is_underwater(), m_bad, m_good, m_info, m_mixed, MENU_AUTOASSIGN, Creature::moves, item::nname(), Character::per_cur, player::practice(), pickup::prompt, uilist::query(), query_yn(), uilist::ret, rng(), item::set_flag(), string_format(), uilist::text, uilist::textwidth, game_menus::inv::titled_filter_menu(), item::unset_flag(), item::update_clothing_mod_val(), and volume_units_abbr().
Member Data Documentation
clothing_mods
std::vector<clothing_mod_id> sew_advanced_actor::clothing_mods
Clothing mods.
Definition at line 1245 of file iuse_actor.h.
materials
std::set<material_id> sew_advanced_actor::materials
Materials.
Definition at line 1243 of file iuse_actor.h.
used_skill
skill_id sew_advanced_actor::used_skill
Skill used.
Definition at line 1247 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp