Cataclysm BN: profession Class Reference
profession Class Reference
#include <profession.h>
Classes
struct itypedec
Public Types
using StartingSkill = std::pair< skill_id, int >
using StartingSkillList = std::vector< StartingSkill >
using itypedecvec = std::vector< itypedec >
Public Member Functions
profession ()
void check_definition () const
Check that item/CBM/addiction/skill definitions are valid.
const profession_id & ident () const
std::string gender_appropriate_name (bool male) const
std::string description (bool male) const
signed int point_cost () const
std::list< item > items (bool male, const std::vector< trait_id > &traits) const
std::vector< addiction > addictions () const
vproto_id vehicle () const
std::vector< mtype_id > pets () const
std::vector< bionic_id > CBMs () const
StartingSkillList skills () const
std::map< spell_id, int > spells () const
bool has_flag (const std::string &flag) const
Check if this type of profession has a certain flag set.
bool is_locked_trait (const trait_id &trait) const
bool is_forbidden_trait (const trait_id &trait) const
std::vector< trait_id > get_locked_traits () const
std::set< trait_id > get_forbidden_traits () const
Static Public Member Functions
static void load_profession (const JsonObject &jo, const std::string &src)
static void load_item_substitutions (const JsonObject &jo)
static const profession_id & generic ()
static const std::vector< profession > & get_all ()
static bool has_initialized ()
static void reset ()
static void check_definitions ()
calls check_definition for each profession
Private Member Functions
void check_item_definitions (const itypedecvec &items) const
void load (const JsonObject &jo, const std::string &src)
Private Attributes
profession_id id
bool was_loaded = false
translation _name_male
translation _name_female
translation _description_male
translation _description_female
signed int _point_cost = 0
itypedecvec legacy_starting_items
itypedecvec legacy_starting_items_male
itypedecvec legacy_starting_items_female
item_group_id _starting_items = item_group_id("EMPTY_GROUP")
item_group_id _starting_items_male = item_group_id("EMPTY_GROUP")
item_group_id _starting_items_female = item_group_id("EMPTY_GROUP")
itype_id no_bonus
std::vector< addiction > _starting_addictions
std::vector< bionic_id > _starting_CBMs
std::vector< trait_id > _starting_traits
std::set< trait_id > _forbidden_traits
std::vector< mtype_id > _starting_pets
vproto_id _starting_vehicle = vproto_id::NULL_ID()
std::map< spell_id, int > _starting_spells
std::set< std::string > flags
StartingSkillList _starting_skills
Friends
class string_id< profession >
class generic_factory< profession >
Detailed Description
Definition at line 25 of file profession.h.
Member Typedef Documentation
itypedecvec
using profession::itypedecvec = std::vector<itypedec>
Definition at line 40 of file profession.h.
StartingSkill
using profession::StartingSkill = std::pair<skill_id, int>
Definition at line 28 of file profession.h.
StartingSkillList
using profession::StartingSkillList = std::vector<StartingSkill>
Definition at line 29 of file profession.h.
Constructor & Destructor Documentation
profession()
profession::profession ()
Definition at line 75 of file profession.cpp.
    : _name_male( no_translation( "null" ) ),
      _name_female( no_translation( "null" ) ),
      _description_male( no_translation( "null" ) ),
      _description_female( no_translation( "null" ) ),
      _point_cost( 0 )
{
}
Referenced by debug_menu::wishmutate().
Member Function Documentation
addictions()
std::vector< addiction > profession::addictions () const
Definition at line 471 of file profession.cpp.
{
    return _starting_addictions;
}
References _starting_addictions.
Referenced by avatar::create().
CBMs()
std::vector< bionic_id > profession::CBMs () const
Definition at line 476 of file profession.cpp.
{
    return _starting_CBMs;
}
References _starting_CBMs.
Referenced by avatar::create(), and set_traits().
check_definition()
void profession::check_definition () const
Check that item/CBM/addiction/skill definitions are valid.
Definition at line 292 of file profession.cpp.
{
    check_item_definitions( legacy_starting_items );
    check_item_definitions( legacy_starting_items_female );
    check_item_definitions( legacy_starting_items_male );
    if( !no_bonus.is_empty() && !no_bonus.is_valid() ) {
        debugmsg( "no_bonus item '%s' is not an itype_id", no_bonus.c_str() );
    }
    if( !item_group::group_is_defined( _starting_items ) ) {
        debugmsg( "_starting_items group is undefined" );
    }
    if( !item_group::group_is_defined( _starting_items_male ) ) {
        debugmsg( "_starting_items_male group is undefined" );
    }
    if( !item_group::group_is_defined( _starting_items_female ) ) {
        debugmsg( "_starting_items_female group is undefined" );
    }
    if( _starting_vehicle && !_starting_vehicle.is_valid() ) {
        debugmsg( "vehicle prototype %s for profession %s does not exist", _starting_vehicle.c_str(),
                  id.c_str() );
    }
    for( const auto &a : _starting_CBMs ) {
        if( !a.is_valid() ) {
            debugmsg( "bionic %s for profession %s does not exist", a.c_str(), id.c_str() );
        }
    }
    for( auto &t : _starting_traits ) {
        if( !t.is_valid() ) {
            debugmsg( "trait %s for profession %s does not exist", t.c_str(), id.c_str() );
        }
    }
    for( const auto &elem : _starting_pets ) {
        if( !elem.is_valid() ) {
            debugmsg( "startng pet %s for profession %s does not exist", elem.c_str(), id.c_str() );
        }
    }
    for( const auto &elem : _starting_skills ) {
        if( !elem.first.is_valid() ) {
            debugmsg( "skill %s for profession %s does not exist", elem.first.c_str(), id.c_str() );
        }
    }
}
References _starting_CBMs, _starting_items, _starting_items_female, _starting_items_male, _starting_pets, _starting_skills, _starting_traits, _starting_vehicle, a, string_id< T >::c_str(), check_item_definitions(), debugmsg, item_group::group_is_defined(), string_id< T >::is_empty(), string_id< T >::is_valid(), legacy_starting_items, legacy_starting_items_female, legacy_starting_items_male, and no_bonus.
check_definitions()
void profession::check_definitions () static
calls check_definition for each profession
Definition at line 264 of file profession.cpp.
{
    item_substitutions.check_consistency();
    for( const auto &prof : all_profs.get_all() ) {
        prof.check_definition();
    }
}
References anonymous_namespace{profession.cpp}::all_profs, json_item_substitution::check_consistency(), and item_substitutions.
Referenced by DynamicDataLoader::check_consistency().
check_item_definitions()
void profession::check_item_definitions (const itypedecvec & items) const private
Definition at line 272 of file profession.cpp.
{
    for( auto &itd : items ) {
        if( !itd.type_id.is_valid() ) {
            debugmsg( "profession %s: item %s does not exist", id.str(), itd.type_id.str() );
        } else if( !itd.snip_id.is_null() ) {
            const itype *type = &*itd.type_id;
            if( type->snippet_category.empty() ) {
                debugmsg( "profession %s: item %s has no snippet category - no description can "
                          "be set", id.str(), itd.type_id.str() );
            } else {
                if( !itd.snip_id.is_valid() ) {
                    debugmsg( "profession %s: there's no snippet with id %s",
                              id.str(), itd.snip_id.str() );
                }
            }
        }
    }
}
References debugmsg, items(), and type.
Referenced by check_definition().
description()
std::string profession::description (bool male) const
Definition at line 356 of file profession.cpp.
{
    if( male ) {
        return _description_male.translated();
    } else {
        return _description_female.translated();
    }
}
References _description_female, _description_male, male, and translation::translated().
gender_appropriate_name()
std::string profession::gender_appropriate_name (bool male) const
Definition at line 347 of file profession.cpp.
{
    if( male ) {
        return _name_male.translated();
    } else {
        return _name_female.translated();
    }
}
References _name_female, _name_male, male, and translation::translated().
Referenced by draw_tip(), set_description(), set_traits(), and memorial_logger::write().
generic()
const profession_id & profession::generic () static
Definition at line 248 of file profession.cpp.
{
    return generic_profession_id;
}
References anonymous_namespace{profession.cpp}::generic_profession_id.
Referenced by avatar::create(), draw_tip(), tutorial_game::init(), Character::load(), player::operator()(), scenario::permitted_professions(), scenario::weighted_random_profession(), and memorial_logger::write().
get_all()
const std::vector< profession > & profession::get_all () static
Definition at line 253 of file profession.cpp.
{
    return all_profs.get_all();
}
References anonymous_namespace{profession.cpp}::all_profs.
Referenced by scenario::permitted_professions().
get_forbidden_traits()
std::set< trait_id > profession::get_forbidden_traits () const
Definition at line 486 of file profession.cpp.
{
    return _forbidden_traits;
}
References _forbidden_traits.
Referenced by scenario::scenario_traits_conflict_with_profession_traits().
get_locked_traits()
std::vector< trait_id > profession::get_locked_traits () const
Definition at line 481 of file profession.cpp.
{
    return _starting_traits;
}
References _starting_traits.
Referenced by newcharacter::add_traits(), scenario::scenario_traits_conflict_with_profession_traits(), set_profession(), and set_traits().
has_flag()
bool profession::has_flag (const std::string & flag) const
Check if this type of profession has a certain flag set.
Current flags: none
Definition at line 496 of file profession.cpp.
{
    return flags.count( flag ) != 0;
}
References flags.
has_initialized()
bool profession::has_initialized () static
Definition at line 337 of file profession.cpp.
{
    return generic_profession_id.is_valid();
}
References anonymous_namespace{profession.cpp}::generic_profession_id, and string_id< T >::is_valid().
ident()
const profession_id & profession::ident () const
Definition at line 342 of file profession.cpp.
{
    return id;
}
References id.
Referenced by scenario::weighted_random_profession().
is_forbidden_trait()
bool profession::is_forbidden_trait (const trait_id & trait) const
Definition at line 507 of file profession.cpp.
{
    return _forbidden_traits.count( trait ) != 0;
}
References _forbidden_traits.
Referenced by set_traits().
is_locked_trait()
bool profession::is_locked_trait (const trait_id & trait) const
Definition at line 501 of file profession.cpp.
{
    return std::find( _starting_traits.begin(), _starting_traits.end(), trait ) !=
           _starting_traits.end();
}
References _starting_traits, and detail::find().
Referenced by set_traits().
items()
std::list< item > profession::items (bool male, const std::vector< trait_id > & traits) const
Definition at line 386 of file profession.cpp.
{
    std::list<item> result;
    auto add_legacy_items = [&result]( const itypedecvec & vec ) {
        for( const itypedec &elem : vec ) {
            item it( elem.type_id, advanced_spawn_time(), item::default_charges_tag {} );
            if( !elem.snip_id.is_null() ) {
                it.set_snippet( elem.snip_id );
            }
            it = it.in_its_container();
            result.push_back( it );
        }
    };
    add_legacy_items( legacy_starting_items );
    add_legacy_items( male ? legacy_starting_items_male : legacy_starting_items_female );
    const std::vector<item> group_both = item_group::items_from( _starting_items,
                                         advanced_spawn_time() );
    const std::vector<item> group_gender = item_group::items_from( male ? _starting_items_male :
                                           _starting_items_female, advanced_spawn_time() );
    result.insert( result.begin(), group_both.begin(), group_both.end() );
    result.insert( result.begin(), group_gender.begin(), group_gender.end() );
    std::vector<itype_id> bonus = item_substitutions.get_bonus_items( traits );
    for( const itype_id &elem : bonus ) {
        if( elem != no_bonus ) {
            result.push_back( item( elem, advanced_spawn_time(), item::default_charges_tag {} ) );
        }
    }
    for( auto iter = result.begin(); iter != result.end(); ) {
        const auto sub = item_substitutions.get_substitution( *iter, traits );
        if( !sub.empty() ) {
            result.insert( result.begin(), sub.begin(), sub.end() );
            iter = result.erase( iter );
        } else {
            ++iter;
        }
    }
    for( item &it : result ) {
        clear_faults( it );
        if( it.is_holster() && it.contents.num_item_stacks() == 1 ) {
            clear_faults( it.contents.front() );
        }
        if( it.has_flag( "VARSIZE" ) ) {
            it.set_flag( "FIT" );
        }
    }
    if( result.empty() ) {
        // No need to do the below stuff. Plus it would cause said below stuff to crash
        return result;
    }
    // Merge charges for items that stack with each other
    for( auto outer = result.begin(); outer != result.end(); ++outer ) {
        if( !outer->count_by_charges() ) {
            continue;
        }
        for( auto inner = std::next( outer ); inner != result.end(); ) {
            if( outer->stacks_with( *inner ) ) {
                outer->merge_charges( *inner );
                inner = result.erase( inner );
            } else {
                ++inner;
            }
        }
    }
    result.sort( []( const item & first, const item & second ) {
        return first.get_layer() < second.get_layer();
    } );
    return result;
}
References _starting_items, _starting_items_female, _starting_items_male, advanced_spawn_time(), clear_faults(), json_item_substitution::get_bonus_items(), item::get_layer(), json_item_substitution::get_substitution(), item_substitutions, item_group::items_from(), legacy_starting_items, legacy_starting_items_female, legacy_starting_items_male, male, no_bonus, second, and item::set_snippet().
Referenced by check_item_definitions(), and avatar::create().
load()
void profession::load (const JsonObject & jo, const std::string & src) private
Definition at line 144 of file profession.cpp.
{
    // If the "name" is an object then we may have to deal with gender-specific titles
    bool add_name_context = false;
    if( jo.has_object( "name" ) ) {
        JsonObject name_obj = jo.get_object( "name" );
        if( name_obj.has_member( "male" ) && name_obj.has_member( "female" ) ) {
            // Gender-specific titles
            _name_male.deserialize( *name_obj.get_raw( "male" ) );
            _name_female.deserialize( *name_obj.get_raw( "female" ) );
        } else {
            // Same profession names for male and female in English
            name_obj.allow_omitted_members();
            _name_male.deserialize( *jo.get_raw( "name" ) );
            _name_female = _name_male;
        }
        add_name_context = true;
    } else if( jo.has_member( "name" ) ) {
        // Same profession names for male and female in English
        _name_male.deserialize( *jo.get_raw( "name" ) );
        _name_female = _name_male;
        add_name_context = true;
    } else if( !was_loaded ) {
        // Throw 'missing mandatory member' error
        jo.get_member( "name" );
        return;
    }
    if( add_name_context ) {
        // Other languages may have different gender-specific titles, so add gender context
        _name_male.add_context( "profession_male" );
        _name_female.add_context( "profession_female" );
    }
    if( jo.has_member( "description" ) ) {
        _description_male.deserialize( *jo.get_raw( "description" ) );
        _description_female = _description_male;
        // These also may differ in other languages!
        _description_male.add_context( "prof_desc_male" );
        _description_female.add_context( "prof_desc_female" );
    } else if( !was_loaded ) {
        // Throw 'missing mandatory member' error
        jo.get_member( "description" );
        return;
    }
    if( jo.has_string( "vehicle" ) ) {
        _starting_vehicle = vproto_id( jo.get_string( "vehicle" ) );
    }
    if( jo.has_array( "pets" ) ) {
        for( JsonObject subobj : jo.get_array( "pets" ) ) {
            int count = subobj.get_int( "amount" );
            mtype_id mon = mtype_id( subobj.get_string( "name" ) );
            for( int start = 0; start < count; ++start ) {
                _starting_pets.push_back( mon );
            }
        }
    }
    if( jo.has_array( "spells" ) ) {
        for( JsonObject subobj : jo.get_array( "spells" ) ) {
            int level = subobj.get_int( "level" );
            spell_id sp = spell_id( subobj.get_string( "id" ) );
            _starting_spells.emplace( sp, level );
        }
    }
    mandatory( jo, was_loaded, "points", _point_cost );
    if( !was_loaded || jo.has_member( "items" ) ) {
        JsonObject items_obj = jo.get_object( "items" );
        if( items_obj.has_array( "both" ) ) {
            optional( items_obj, was_loaded, "both", legacy_starting_items, item_reader {} );
        }
        if( items_obj.has_object( "both" ) ) {
            _starting_items = item_group::load_item_group( items_obj.get_member( "both" ), "collection" );
        }
        if( items_obj.has_array( "male" ) ) {
            optional( items_obj, was_loaded, "male", legacy_starting_items_male, item_reader {} );
        }
        if( items_obj.has_object( "male" ) ) {
            _starting_items_male = item_group::load_item_group( items_obj.get_member( "male" ), "collection" );
        }
        if( items_obj.has_array( "female" ) ) {
            optional( items_obj, was_loaded, "female",  legacy_starting_items_female, item_reader {} );
        }
        if( items_obj.has_object( "female" ) ) {
            _starting_items_female = item_group::load_item_group( items_obj.get_member( "female" ),
                                     "collection" );
        }
    }
    optional( jo, was_loaded, "no_bonus", no_bonus );
    optional( jo, was_loaded, "skills", _starting_skills, skilllevel_reader {} );
    optional( jo, was_loaded, "addictions", _starting_addictions, addiction_reader {} );
    // TODO: use string_id<bionic_type> or so
    optional( jo, was_loaded, "CBMs", _starting_CBMs, auto_flags_reader<bionic_id> {} );
    // TODO: use string_id<mutation_branch> or so
    optional( jo, was_loaded, "traits", _starting_traits, auto_flags_reader<trait_id> {} );
    optional( jo, was_loaded, "forbidden_traits", _forbidden_traits, auto_flags_reader<trait_id> {} );
    optional( jo, was_loaded, "flags", flags, auto_flags_reader<> {} );
}
References _description_female, _description_male, _forbidden_traits, _name_female, _name_male, _point_cost, _starting_addictions, _starting_CBMs, _starting_items, _starting_items_female, _starting_items_male, _starting_pets, _starting_skills, _starting_spells, _starting_traits, _starting_vehicle, translation::add_context(), JsonObject::allow_omitted_members(), detail::count(), translation::deserialize(), flags, JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_raw(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), legacy_starting_items, legacy_starting_items_female, legacy_starting_items_male, item_group::load_item_group(), mandatory(), mtype_id, no_bonus, optional(), spell_id, and was_loaded.
load_item_substitutions()
void profession::load_item_substitutions (const JsonObject & jo) static
Definition at line 519 of file profession.cpp.
{
    item_substitutions.load( jo );
}
References item_substitutions, and json_item_substitution::load().
Referenced by DynamicDataLoader::initialize().
load_profession()
void profession::load_profession (const JsonObject & jo, const std::string & src) static
Definition at line 84 of file profession.cpp.
{
    all_profs.load( jo, src );
}
References anonymous_namespace{profession.cpp}::all_profs.
Referenced by DynamicDataLoader::initialize().
pets()
std::vector< mtype_id > profession::pets () const
Definition at line 466 of file profession.cpp.
{
    return _starting_pets;
}
References _starting_pets.
Referenced by avatar::create().
point_cost()
signed int profession::point_cost () const
Definition at line 371 of file profession.cpp.
{
    return _point_cost;
}
References _point_cost.
Referenced by can_pick_prof(), avatar::randomize(), set_profession(), set_scenario(), and scenario::weighted_random_profession().
reset()
void profession::reset () static
Definition at line 258 of file profession.cpp.
{
    all_profs.reset();
    item_substitutions.reset();
}
References anonymous_namespace{profession.cpp}::all_profs, item_substitutions, and json_item_substitution::reset().
Referenced by DynamicDataLoader::unload_data().
skills()
profession::StartingSkillList profession::skills () const
Definition at line 491 of file profession.cpp.
{
    return _starting_skills;
}
References _starting_skills.
Referenced by avatar::create(), set_description(), and set_skills().
spells()
std::map< spell_id, int > profession::spells () const
Definition at line 512 of file profession.cpp.
{
    return _starting_spells;
}
References _starting_spells.
Referenced by learn_spells().
vehicle()
vproto_id profession::vehicle () const
Definition at line 461 of file profession.cpp.
{
    return _starting_vehicle;
}
References _starting_vehicle.
Referenced by avatar::create(), and set_description().
Friends And Related Function Documentation
generic_factory< profession >
friend class generic_factory< profession > friend
Definition at line 1 of file profession.h.
string_id< profession >
friend class string_id< profession > friend
Definition at line 1 of file profession.h.
Member Data Documentation
_description_female
translation profession::_description_female private
Definition at line 51 of file profession.h.
Referenced by description(), and load().
_description_male
translation profession::_description_male private
Definition at line 50 of file profession.h.
Referenced by description(), and load().
_forbidden_traits
std::set<trait_id> profession::_forbidden_traits private
Definition at line 66 of file profession.h.
Referenced by get_forbidden_traits(), is_forbidden_trait(), and load().
_name_female
translation profession::_name_female private
Definition at line 49 of file profession.h.
Referenced by gender_appropriate_name(), and load().
_name_male
translation profession::_name_male private
Definition at line 48 of file profession.h.
Referenced by gender_appropriate_name(), and load().
_point_cost
signed int profession::_point_cost = 0 private
Definition at line 52 of file profession.h.
Referenced by load(), and point_cost().
_starting_addictions
std::vector<addiction> profession::_starting_addictions private
Definition at line 63 of file profession.h.
Referenced by addictions(), and load().
_starting_CBMs
std::vector<bionic_id> profession::_starting_CBMs private
Definition at line 64 of file profession.h.
Referenced by CBMs(), check_definition(), and load().
_starting_items
item_group_id profession::_starting_items = item_group_id("EMPTY_GROUP") private
Definition at line 58 of file profession.h.
Referenced by check_definition(), items(), and load().
_starting_items_female
item_group_id profession::_starting_items_female = item_group_id("EMPTY_GROUP") private
Definition at line 60 of file profession.h.
Referenced by check_definition(), items(), and load().
_starting_items_male
item_group_id profession::_starting_items_male = item_group_id("EMPTY_GROUP") private
Definition at line 59 of file profession.h.
Referenced by check_definition(), items(), and load().
_starting_pets
std::vector<mtype_id> profession::_starting_pets private
Definition at line 67 of file profession.h.
Referenced by check_definition(), load(), and pets().
_starting_skills
StartingSkillList profession::_starting_skills private
Definition at line 72 of file profession.h.
Referenced by check_definition(), load(), and skills().
_starting_spells
std::map<spell_id, int> profession::_starting_spells private
Definition at line 70 of file profession.h.
Referenced by load(), and spells().
_starting_traits
std::vector<trait_id> profession::_starting_traits private
Definition at line 65 of file profession.h.
Referenced by check_definition(), get_locked_traits(), is_locked_trait(), and load().
_starting_vehicle
vproto_id profession::_starting_vehicle = vproto_id::NULL_ID() private
Definition at line 68 of file profession.h.
Referenced by check_definition(), load(), and vehicle().
flags
std::set<std::string> profession::flags private
Definition at line 71 of file profession.h.
Referenced by has_flag(), and load().
id
profession_id profession::id private
Definition at line 45 of file profession.h.
Referenced by ident().
legacy_starting_items
itypedecvec profession::legacy_starting_items private
Definition at line 55 of file profession.h.
Referenced by check_definition(), items(), and load().
legacy_starting_items_female
itypedecvec profession::legacy_starting_items_female private
Definition at line 57 of file profession.h.
Referenced by check_definition(), items(), and load().
legacy_starting_items_male
itypedecvec profession::legacy_starting_items_male private
Definition at line 56 of file profession.h.
Referenced by check_definition(), items(), and load().
no_bonus
itype_id profession::no_bonus private
Definition at line 61 of file profession.h.
Referenced by check_definition(), items(), and load().
was_loaded
bool profession::was_loaded = false private
Definition at line 46 of file profession.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/profession.h
src/profession.cpp