Cataclysm BN: panel_manager Class Reference
panel_manager Class Reference
#include <panels.h>
Public Member Functions
panel_manager ()
~panel_manager ()=default
panel_manager (panel_manager &&)=default
panel_manager (const panel_manager &)=default
panel_manager & operator= (panel_manager &&)=default
panel_manager & operator= (const panel_manager &)=default
std::vector< window_panel > & get_current_layout ()
std::string get_current_layout_id () const
int get_width_right ()
int get_width_left ()
void show_adm ()
void init ()
Static Public Member Functions
static panel_manager & get_manager ()
Private Member Functions
bool save ()
bool load ()
void serialize (JsonOut &json)
void deserialize (JsonIn &jsin)
void update_offsets (int x)
Private Attributes
int width_right = 0
int width_left = 0
std::string current_layout_id
std::map< std::string, std::vector< window_panel > > layouts
Detailed Description
Definition at line 62 of file panels.h.
Constructor & Destructor Documentation
panel_manager() [1/3]
panel_manager::panel_manager ()
Definition at line 2148 of file panels.cpp.
{
    current_layout_id = "labels";
    layouts = initialize_default_panel_layouts();
}
References current_layout_id, initialize_default_panel_layouts(), and layouts.
~panel_manager()
panel_manager::~panel_manager () default
panel_manager() [2/3]
panel_manager::panel_manager (panel_manager &&) default
panel_manager() [3/3]
panel_manager::panel_manager (const panel_manager &) default
Member Function Documentation
deserialize()
void panel_manager::deserialize (JsonIn & jsin) private
Definition at line 2250 of file panels.cpp.
{
    jsin.start_array();
    JsonObject joLayouts( jsin.get_object() );
    current_layout_id = joLayouts.get_string( "current_layout_id" );
    for( JsonObject joLayout : joLayouts.get_array( "layouts" ) ) {
        std::string layout_id = joLayout.get_string( "layout_id" );
        auto &layout = layouts.find( layout_id )->second;
        auto it = layout.begin();
        for( JsonObject joPanel : joLayout.get_array( "panels" ) ) {
            std::string name = joPanel.get_string( "name" );
            bool toggle = joPanel.get_bool( "toggle" );
            for( auto it2 = layout.begin() + std::distance( layout.begin(), it ); it2 != layout.end(); ++it2 ) {
                if( it2->get_name() == name ) {
                    if( it->get_name() != name ) {
                        window_panel panel = *it2;
                        layout.erase( it2 );
                        it = layout.insert( it, panel );
                    }
                    it->toggle = toggle;
                    ++it;
                    break;
                }
            }
        }
    }
    jsin.end_array();
}
References current_layout_id, JsonIn::end_array(), JsonObject::get_array(), JsonIn::get_object(), JsonObject::get_string(), layouts, om_direction::name(), JsonIn::start_array(), and window_panel::toggle.
Referenced by load().
get_current_layout()
std::vector< window_panel > & panel_manager::get_current_layout ()
Definition at line 2154 of file panels.cpp.
{
    auto kv = layouts.find( current_layout_id );
    if( kv != layouts.end() ) {
        return kv->second;
    }
    debugmsg( "Invalid current panel layout, defaulting to classic" );
    current_layout_id = "classic";
    return get_current_layout();
}
References current_layout_id, debugmsg, get_current_layout(), and layouts.
Referenced by get_current_layout(), init(), game::look_around(), and show_adm().
get_current_layout_id()
std::string panel_manager::get_current_layout_id () const
Definition at line 2165 of file panels.cpp.
{
    return current_layout_id;
}
References current_layout_id.
Referenced by target_ui::init_window_and_input(), and print_ranged_chance().
get_manager()
static panel_manager & panel_manager::get_manager () inline static
Definition at line 72 of file panels.h.
{
            static panel_manager single_instance;
            return single_instance;
        }
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), advanced_inventory::display(), game::draw_panels(), game::handle_action(), target_ui::init_window_and_input(), game::load_static_data(), game::look_around(), pickup::pick_up(), print_ranged_chance(), live_view::show(), and show_adm().
get_width_left()
int panel_manager::get_width_left ()
Definition at line 2178 of file panels.cpp.
{
    if( get_option<std::string>( "SIDEBAR_POSITION" ) == "left" ) {
        return width_right;
    }
    return width_left;
}
References width_left, and width_right.
Referenced by game::create_or_get_main_ui_adaptor(), game::look_around(), and pickup::pick_up().
get_width_right()
int panel_manager::get_width_right ()
Definition at line 2170 of file panels.cpp.
{
    if( get_option<std::string>( "SIDEBAR_POSITION" ) == "left" ) {
        return width_left;
    }
    return width_right;
}
References width_left, and width_right.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), and pickup::pick_up().
init()
void panel_manager::init ()
Definition at line 2186 of file panels.cpp.
{
    load();
    update_offsets( get_current_layout().begin()->get_width() );
}
References get_current_layout(), load(), and update_offsets().
Referenced by game::load_static_data().
load()
bool panel_manager::load () private
Definition at line 2206 of file panels.cpp.
{
    return read_from_file_optional_json( PATH_INFO::panel_options(), [&]( JsonIn & jsin ) {
        deserialize( jsin );
    } );
}
References deserialize(), PATH_INFO::panel_options(), and read_from_file_optional_json().
Referenced by init().
operator=() [1/2]
panel_manager & panel_manager::operator= (const panel_manager &) default
operator=() [2/2]
panel_manager & panel_manager::operator= (panel_manager &&) default
save()
bool panel_manager::save () private
Definition at line 2198 of file panels.cpp.
{
    return write_to_file( PATH_INFO::panel_options(), [&]( std::ostream & fout ) {
        JsonOut jout( fout, true );
        serialize( jout );
    }, _( "panel options" ) );
}
References _, PATH_INFO::panel_options(), serialize(), and write_to_file().
Referenced by show_adm().
serialize()
void panel_manager::serialize (JsonOut & json) private
Definition at line 2213 of file panels.cpp.
{
    json.start_array();
    json.start_object();
    json.member( "current_layout_id", current_layout_id );
    json.member( "layouts" );
    json.start_array();
    for( const auto &kv : layouts ) {
        json.start_object();
        json.member( "layout_id", kv.first );
        json.member( "panels" );
        json.start_array();
        for( const auto &panel : kv.second ) {
            json.start_object();
            json.member( "name", panel.get_name() );
            json.member( "toggle", panel.toggle );
            json.end_object();
        }
        json.end_array();
        json.end_object();
    }
    json.end_array();
    json.end_object();
    json.end_array();
}
References current_layout_id, JsonOut::end_array(), JsonOut::end_object(), layouts, JsonOut::member(), JsonOut::start_array(), and JsonOut::start_object().
Referenced by save().
show_adm()
void panel_manager::show_adm ()
Definition at line 2282 of file panels.cpp.
{
    input_context ctxt( "PANEL_MGMT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "UP" );
    ctxt.register_action( "DOWN" );
    ctxt.register_action( "LEFT" );
    ctxt.register_action( "RIGHT" );
    ctxt.register_action( "MOVE_PANEL" );
    ctxt.register_action( "TOGGLE_PANEL" );
    const std::vector<int> column_widths = { 17, 37, 17 };
    size_t current_col = 0;
    size_t current_row = 0;
    bool swapping = false;
    size_t source_row = 0;
    size_t source_index = 0;
    bool recalc = true;
    bool exit = false;
    // map of row the panel is on vs index
    // panels not renderable due to game configuration will not be in this map
    std::map<size_t, size_t> row_indices;
    g->show_panel_adm = true;
    g->invalidate_main_ui_adaptor();
    catacurses::window w;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        w = catacurses::newwin( 20, 75,
                                point( ( TERMX / 2 ) - 38, ( TERMY / 2 ) - 10 ) );
        ui.position_from_window( w );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        auto &panels = layouts[current_layout_id];
        werase( w );
        decorate_panel( _( "SIDEBAR OPTIONS" ), w );
        for( std::pair<size_t, size_t> row_indx : row_indices ) {
            std::string name = _( panels[row_indx.second].get_name() );
            if( swapping && source_index == row_indx.second ) {
                mvwprintz( w, point( 5, current_row + 1 ), c_yellow, name );
            } else {
                int offset = 0;
                if( !swapping ) {
                    offset = 0;
                } else if( current_row > source_row && row_indx.first > source_row &&
                           row_indx.first <= current_row ) {
                    offset = -1;
                } else if( current_row < source_row && row_indx.first < source_row &&
                           row_indx.first >= current_row ) {
                    offset = 1;
                }
                const nc_color toggle_color = panels[row_indx.second].toggle ? c_white : c_dark_gray;
                mvwprintz( w, point( 4, row_indx.first + 1 + offset ), toggle_color, name );
            }
        }
        size_t i = 1;
        for( const auto &layout : layouts ) {
            mvwprintz( w, point( column_widths[0] + column_widths[1] + 4, i ),
                       current_layout_id == layout.first ? c_light_blue : c_white, _( layout.first ) );
            i++;
        }
        int col_offset = 0;
        for( i = 0; i < current_col; i++ ) {
            col_offset += column_widths[i];
        }
        mvwprintz( w, point( 1 + ( col_offset ), current_row + 1 ), c_yellow, ">>" );
        mvwvline( w, point( column_widths[0], 1 ), 0, 18 );
        mvwvline( w, point( column_widths[0] + column_widths[1], 1 ), 0, 18 );
        col_offset = column_widths[0] + 2;
        int col_width = column_widths[1] - 4;
        mvwprintz( w, point( col_offset, 1 ), c_light_green, trunc_ellipse( ctxt.get_desc( "TOGGLE_PANEL" ),
                   col_width ) + ":" );
        mvwprintz( w, point( col_offset, 2 ), c_white, _( "Toggle panels on/off" ) );
        mvwprintz( w, point( col_offset, 3 ), c_light_green, trunc_ellipse( ctxt.get_desc( "MOVE_PANEL" ),
                   col_width ) + ":" );
        mvwprintz( w, point( col_offset, 4 ), c_white, _( "Change display order" ) );
        mvwprintz( w, point( col_offset, 5 ), c_light_green, trunc_ellipse( ctxt.get_desc( "QUIT" ),
                   col_width ) + ":" );
        mvwprintz( w, point( col_offset, 6 ), c_white, _( "Exit" ) );
        wnoutrefresh( w );
    } );
    while( !exit ) {
        auto &panels = layouts[current_layout_id];
        if( recalc ) {
            recalc = false;
            row_indices.clear();
            for( size_t i = 0, row = 0; i < panels.size(); i++ ) {
                if( panels[i].render() ) {
                    row_indices.emplace( row, i );
                    row++;
                }
            }
        }
        const size_t num_rows = current_col == 0 ? row_indices.size() : layouts.size();
        current_row = clamp<size_t>( current_row, 0, num_rows - 1 );
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "UP" ) {
            if( current_row > 0 ) {
                current_row -= 1;
            } else {
                current_row = num_rows - 1;
            }
        } else if( action == "DOWN" ) {
            if( current_row + 1 < num_rows ) {
                current_row += 1;
            } else {
                current_row = 0;
            }
        } else if( action == "MOVE_PANEL" && current_col == 0 ) {
            swapping = !swapping;
            if( swapping ) {
                // source window from the swap
                // saving win1 index
                source_row = current_row;
                source_index = row_indices[current_row];
            } else {
                // dest window for the swap
                // saving win2 index
                const size_t target_index = row_indices[current_row];
                int distance = target_index - source_index;
                size_t step_dir = distance > 0 ? 1 : -1;
                for( size_t i = source_index; i != target_index; i += step_dir ) {
                    std::swap( panels[i], panels[i + step_dir] );
                }
                g->invalidate_main_ui_adaptor();
                recalc = true;
            }
        } else if( !swapping && action == "MOVE_PANEL" && current_col == 2 ) {
            auto iter = std::next( layouts.begin(), current_row );
            current_layout_id = iter->first;
            int width = panel_manager::get_manager().get_current_layout().begin()->get_width();
            update_offsets( width );
            int h; // to_map_font_dimension needs a second input
            to_map_font_dimension( width, h );
            // tell the game that the main screen might have a different size now.
            g->mark_main_ui_adaptor_resize();
            recalc = true;
        } else if( !swapping && ( action == "RIGHT" || action == "LEFT" ) ) {
            // there are only two columns
            if( current_col == 0 ) {
                current_col = 2;
            } else {
                current_col = 0;
            }
        } else if( !swapping && action == "TOGGLE_PANEL" && current_col == 0 ) {
            panels[row_indices[current_row]].toggle = !panels[row_indices[current_row]].toggle;
            g->invalidate_main_ui_adaptor();
        } else if( action == "QUIT" ) {
            exit = true;
            save();
        }
    }
    g->show_panel_adm = false;
    g->invalidate_main_ui_adaptor();
}
References _, action, c_dark_gray, c_light_blue, c_light_green, c_white, c_yellow, current_layout_id, decorate_panel(), g, get_current_layout(), input_context::get_desc(), get_manager(), input_context::handle_input(), layouts, mvwprintz(), catacurses::mvwvline(), om_direction::name(), catacurses::newwin(), ui_manager::redraw(), input_context::register_action(), save(), cata::swap(), TERMX, TERMY, to_map_font_dimension(), trunc_ellipse(), update_offsets(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by game::handle_action().
update_offsets()
void panel_manager::update_offsets (int x) private
Definition at line 2192 of file panels.cpp.
{
    width_right = x;
    width_left = 0;
}
References width_left, and width_right.
Referenced by init(), and show_adm().
Member Data Documentation
current_layout_id
std::string panel_manager::current_layout_id private
Definition at line 97 of file panels.h.
Referenced by deserialize(), get_current_layout(), get_current_layout_id(), panel_manager(), serialize(), and show_adm().
layouts
std::map<std::string, std::vector<window_panel> > panel_manager::layouts private
Definition at line 98 of file panels.h.
Referenced by deserialize(), get_current_layout(), panel_manager(), serialize(), and show_adm().
width_left
int panel_manager::width_left = 0 private
Definition at line 96 of file panels.h.
Referenced by get_width_left(), get_width_right(), and update_offsets().
width_right
int panel_manager::width_right = 0 private
Definition at line 95 of file panels.h.
Referenced by get_width_left(), get_width_right(), and update_offsets().
The documentation for this class was generated from the following files:
src/panels.h
src/panels.cpp