Cataclysm BN: shape Class Reference
shape Class Reference
Class describing shapes in 3D space.
#include <shape.h>
Public Member Functions
double distance_at (const tripoint &p) const
double distance_at (const rl_vec3d &p) const
inclusive_cuboid< tripoint > bounding_box () const
Approximation of bounding box, guaranteed to contain all points.
inclusive_cuboid< rl_vec3d > bounding_box_float () const
const tripoint & get_origin () const
shape (const std::shared_ptr< shape_impl > &, const tripoint &origin)
shape (const shape &)
Private Attributes
std::shared_ptr< shape_impl > impl
tripoint origin
Detailed Description
Class describing shapes in 3D space.
The shapes can cover some points partially.
Definition at line 21 of file shape.h.
Constructor & Destructor Documentation
shape() [1/2]
shape::shape (const std::shared_ptr< shape_impl > & impl, const tripoint & origin)
Definition at line 11 of file shape.cpp.
    : impl( impl )
    , origin( origin )
{}
shape() [2/2]
shape::shape (const shape &) default
Member Function Documentation
bounding_box()
inclusive_cuboid< tripoint > shape::bounding_box () const
Approximation of bounding box, guaranteed to contain all points.
Definition at line 21 of file shape.cpp.
{
    const inclusive_cuboid<rl_vec3d> &bb_float = bounding_box_float();
    const tripoint min = tripoint( std::floor( bb_float.p_min.x ),
                                   std::floor( bb_float.p_min.y ),
                                   std::floor( bb_float.p_min.z ) );
    const tripoint max = tripoint( std::ceil( bb_float.p_max.x ),
                                   std::ceil( bb_float.p_max.y ),
                                   std::ceil( bb_float.p_max.z ) );
    return inclusive_cuboid<tripoint>( min, max );
}
References bounding_box_float(), inclusive_cuboid< Tripoint, >::p_max, and inclusive_cuboid< Tripoint, >::p_min.
Referenced by offset_shape::bounding_box(), and rotate_z_shape::bounding_box().
bounding_box_float()
inclusive_cuboid< rl_vec3d > shape::bounding_box_float () const
Definition at line 32 of file shape.cpp.
{
    return impl->bounding_box();
}
References impl.
Referenced by bounding_box().
distance_at() [1/2]
double shape::distance_at (const rl_vec3d & p) const
Definition at line 41 of file shape.cpp.
{
    return impl->signed_distance( p );
}
References impl.
distance_at() [2/2]
double shape::distance_at (const tripoint & p) const
Definition at line 37 of file shape.cpp.
{
    return distance_at( rl_vec3d( p.x, p.y, p.z ) );
}
References distance_at(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by distance_at(), ranged::execute_shaped_attack(), and ranged::expected_coverage().
get_origin()
const tripoint & shape::get_origin () const
Definition at line 16 of file shape.cpp.
{
    return origin;
}
References origin.
Referenced by ranged::execute_shaped_attack(), and ranged::expected_coverage().
Member Data Documentation
impl
std::shared_ptr<shape_impl> shape::impl private
Definition at line 37 of file shape.h.
Referenced by bounding_box_float(), and distance_at().
origin
tripoint shape::origin private
Definition at line 38 of file shape.h.
Referenced by get_origin().
The documentation for this class was generated from the following files:
src/shape.h
src/shape.cpp