Cataclysm BN: behavior::monster_oracle_t Class Reference
behavior::monster_oracle_t Class Reference
#include <monster_oracle.h>
Public Member Functions
monster_oracle_t (const monster *subject)
status_t has_special () const
Predicates used by AI to determine goals.
status_t not_hallucination () const
status_t items_available () const
Private Attributes
const monster * subject
Detailed Description
Definition at line 13 of file monster_oracle.h.
Constructor & Destructor Documentation
monster_oracle_t()
behavior::monster_oracle_t::monster_oracle_t (const monster * subject) inline
Definition at line 16 of file monster_oracle.h.
{
            this->subject = subject;
        }
References subject.
Member Function Documentation
has_special()
status_t behavior::monster_oracle_t::has_special () const
Predicates used by AI to determine goals.
Definition at line 12 of file monster_oracle.cpp.
{
    if( subject->shortest_special_cooldown() == 0 ) {
        return running;
    }
    return failure;
}
References behavior::failure, behavior::running, monster::shortest_special_cooldown(), and subject.
items_available()
status_t behavior::monster_oracle_t::items_available () const
Definition at line 25 of file monster_oracle.cpp.
{
    if( !get_map().has_flag( TFLAG_SEALED, subject->pos() ) && get_map().has_items( subject->pos() ) ) {
        return running;
    }
    return failure;
}
References behavior::failure, get_map(), monster::pos(), behavior::running, subject, and TFLAG_SEALED.
not_hallucination()
status_t behavior::monster_oracle_t::not_hallucination () const
Definition at line 20 of file monster_oracle.cpp.
{
    return subject->is_hallucination() ? failure : running;
}
References behavior::failure, monster::is_hallucination(), behavior::running, and subject.
Member Data Documentation
subject
const monster* behavior::monster_oracle_t::subject private
Definition at line 26 of file monster_oracle.h.
Referenced by has_special(), items_available(), monster_oracle_t(), and not_hallucination().
The documentation for this class was generated from the following files:
src/monster_oracle.h
src/monster_oracle.cpp