Cataclysm BN: jmapgen_sign Class Reference
jmapgen_sign Class Reference
Place a sign with some text.
Public Member Functions
jmapgen_sign (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
std::string apply_all_tags (std::string signtext, const std::string &cityname) const
bool has_vehicle_collision (mapgendata &dat, const point &p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
std::string signage
std::string snippet
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a sign with some text.
"signage": the text on the sign.
Definition at line 912 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_sign()
jmapgen_sign::jmapgen_sign (const JsonObject & jsi) inline
Definition at line 917 of file mapgen.cpp.
                                              :
            signage( jsi.get_string( "signage", "" ) )
            , snippet( jsi.get_string( "snippet", "" ) ) {
            if( signage.empty() && snippet.empty() ) {
                jsi.throw_error( "jmapgen_sign: needs either signage or snippet" );
            }
        }
References mapgen_defer::jsi, signage, snippet, and JsonObject::throw_error().
Member Function Documentation
apply()
void jmapgen_sign::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 924 of file mapgen.cpp.
{
            const point r{ x.get(), y.get() };
            dat.m.furn_set( r, f_null );
            dat.m.furn_set( r, furn_str_id( "f_sign" ) );
            std::string signtext;
            if( !snippet.empty() ) {
                // select a snippet from the category
                signtext = SNIPPET.random_from_category( snippet ).value_or( translation() ).translated();
            } else if( !signage.empty() ) {
                signtext = signage;
            }
            if( !signtext.empty() ) {
                // replace tags
                signtext = _( signtext );
                std::string cityname = "illegible city name";
                tripoint abs_sub = dat.m.get_abs_sub();
                // TODO: fix point types
                const city *c = overmap_buffer.closest_city( tripoint_abs_sm( abs_sub ) ).city;
                if( c != nullptr ) {
                    cityname = c->name;
                }
                signtext = apply_all_tags( signtext, cityname );
            }
            dat.m.set_signage( tripoint( r, dat.m.get_abs_sub().z ), signtext );
        }
References _, apply_all_tags(), c, city_reference::city, overmapbuffer::closest_city(), f_null, map::furn_set(), jmapgen_int::get(), map::get_abs_sub(), mapgendata::m, overmap_buffer, snippet_library::random_from_category(), map::set_signage(), signage, snippet, SNIPPET, and tripoint::z.
apply_all_tags()
std::string jmapgen_sign::apply_all_tags (std::string signtext, const std::string & cityname) const inline
Definition at line 952 of file mapgen.cpp.
{
            replace_city_tag( signtext, cityname );
            replace_name_tags( signtext );
            return signtext;
        }
References replace_city_tag(), and replace_name_tags().
Referenced by apply().
has_vehicle_collision()
bool jmapgen_sign::has_vehicle_collision (mapgendata & dat, const point & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 957 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
signage
std::string jmapgen_sign::signage
Definition at line 915 of file mapgen.cpp.
Referenced by apply(), and jmapgen_sign().
snippet
std::string jmapgen_sign::snippet
Definition at line 916 of file mapgen.cpp.
Referenced by apply(), and jmapgen_sign().
The documentation for this class was generated from the following file:
src/mapgen.cpp