Cataclysm BN: activity_actor Class Reference
activity_actor Class Reference abstract
#include <activity_actor.h>
Public Member Functions
virtual ~activity_actor ()=default
virtual activity_id get_type () const =0
Should return the activity id of the corresponding activity.
virtual void start (player_activity &act, Character &who)=0
Called once at the start of the activity.
virtual void do_turn (player_activity &act, Character &who)=0
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
virtual void finish (player_activity &act, Character &who)=0
Called when the activity runs out of moves, assuming that it has not already been set to null.
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::unique_ptr< activity_actor > clone () const =0
Returns a deep copy of this object.
virtual void serialize (JsonOut &jsout) const =0
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Private Member Functions
virtual bool can_resume_with_internal (const activity_actor &, const Character &) const
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Detailed Description
Definition at line 54 of file activity_actor.h.
Constructor & Destructor Documentation
~activity_actor()
virtual activity_actor::~activity_actor () virtual default
Member Function Documentation
can_resume_with()
bool activity_actor::can_resume_with (const activity_actor & other, const Character & who) const inline
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
Checks that other has the same type as this so that can_resume_with_internal can safely static_cast other.
Definition at line 110 of file activity_actor.h.
{
            if( other.get_type() == get_type() ) {
                return can_resume_with_internal( other, who );
            }
            return false;
        }
References can_resume_with_internal(), get_type(), and other.
can_resume_with_internal()
virtual bool activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented in dig_activity_actor, dig_channel_activity_actor, and toggle_gate_activity_actor.
Definition at line 65 of file activity_actor.h.
{
            return false;
        }
Referenced by can_resume_with().
canceled()
virtual void activity_actor::canceled (player_activity & , Character &) inline virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented in autodrive_activity_actor, and aim_activity_actor.
Definition at line 101 of file activity_actor.h.
{};
clone()
virtual std::unique_ptr< activity_actor > activity_actor::clone () const pure virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implemented in aim_activity_actor, autodrive_activity_actor, dig_activity_actor, dig_channel_activity_actor, disassemble_activity_actor, drop_activity_actor, hacking_activity_actor, migration_cancel_activity_actor, move_items_activity_actor, toggle_gate_activity_actor, pickup_activity_actor, stash_activity_actor, throw_activity_actor, and wash_activity_actor.
do_turn()
virtual void activity_actor::do_turn (player_activity & act, Character & who) pure virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implemented in autodrive_activity_actor, dig_activity_actor, dig_channel_activity_actor, disassemble_activity_actor, hacking_activity_actor, toggle_gate_activity_actor, wash_activity_actor, drop_activity_actor, stash_activity_actor, aim_activity_actor, migration_cancel_activity_actor, move_items_activity_actor, pickup_activity_actor, and throw_activity_actor.
finish()
virtual void activity_actor::finish (player_activity & act, Character & who) pure virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implemented in drop_activity_actor, migration_cancel_activity_actor, move_items_activity_actor, pickup_activity_actor, stash_activity_actor, throw_activity_actor, autodrive_activity_actor, toggle_gate_activity_actor, aim_activity_actor, dig_activity_actor, dig_channel_activity_actor, disassemble_activity_actor, hacking_activity_actor, and wash_activity_actor.
get_progress_message()
virtual act_progress_message activity_actor::get_progress_message (const player_activity & , const Character &) const inline virtual
Reimplemented in disassemble_activity_actor.
Definition at line 138 of file activity_actor.h.
{
            // TODO: make it create default message once migration to actors is complete.
            act_progress_message msg;
            msg.implemented = false;
            return msg;
        }
References act_progress_message::implemented.
get_type()
virtual activity_id activity_actor::get_type () const pure virtual
Should return the activity id of the corresponding activity.
Implemented in aim_activity_actor, autodrive_activity_actor, dig_activity_actor, dig_channel_activity_actor, disassemble_activity_actor, drop_activity_actor, hacking_activity_actor, migration_cancel_activity_actor, move_items_activity_actor, toggle_gate_activity_actor, pickup_activity_actor, stash_activity_actor, throw_activity_actor, and wash_activity_actor.
Referenced by can_resume_with().
serialize()
virtual void activity_actor::serialize (JsonOut & jsout) const pure virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implemented in aim_activity_actor, autodrive_activity_actor, dig_activity_actor, dig_channel_activity_actor, disassemble_activity_actor, drop_activity_actor, hacking_activity_actor, migration_cancel_activity_actor, move_items_activity_actor, toggle_gate_activity_actor, pickup_activity_actor, stash_activity_actor, throw_activity_actor, and wash_activity_actor.
start()
virtual void activity_actor::start (player_activity & act, Character & who) pure virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implemented in drop_activity_actor, migration_cancel_activity_actor, move_items_activity_actor, pickup_activity_actor, stash_activity_actor, throw_activity_actor, autodrive_activity_actor, dig_activity_actor, dig_channel_activity_actor, toggle_gate_activity_actor, wash_activity_actor, aim_activity_actor, disassemble_activity_actor, and hacking_activity_actor.
The documentation for this class was generated from the following file:
src/activity_actor.h