Cataclysm BN: input_manager Class Reference
input_manager Class Reference
Manages the translation from action IDs to associated input.
#include <input.h>
Public Member Functions
const std::vector< input_event > & get_input_for_action (const std::string &action_descriptor, const std::string &context="default", bool *overwrites_default=nullptr)
Get the input events associated with an action ID in a given context.
int get_first_char_for_action (const std::string &action_descriptor, const std::string &context="default")
Return first char associated with an action ID in a given context.
void init ()
Initializes the input manager, aka loads the input mapping configuration JSON.
void save ()
Opposite of init, save the data that has been loaded by init, and possibly been modified.
int get_previously_pressed_key () const
Return the previously pressed key, or 0 if there is no previous input or the previous input wasn't a key.
int get_keycode (const std::string &name) const
Get the keycode associated with the given key name.
std::string get_keyname (int ch, input_event_t inp_type, bool portable=false) const
Get the key name associated with the given keyboard keycode.
input_event get_input_event ()
curses getch() replacement.
void pump_events ()
Resize & refresh if necessary, process all pending window events, and ignore keypresses.
void wait_for_any_key ()
Wait until the user presses a key.
void set_timeout (int t)
Sets global input polling timeout as appropriate for the current interface system.
void reset_timeout ()
int get_timeout () const
Private Types
using t_input_event_list = std::vector< input_event >
using t_actions = std::map< std::string, action_attributes >
using t_action_contexts = std::map< std::string, t_actions >
using t_key_to_name_map = std::map< int, std::string >
using t_name_to_key_map = std::map< std::string, int >
Private Member Functions
void init_keycode_mapping ()
void add_keycode_pair (int ch, const std::string &name)
void add_gamepad_keycode_pair (int ch, const std::string &name)
void load (const std::string &file_name, bool is_user_preferences)
Load keybindings from a json file, override existing bindings.
t_input_event_list & get_or_create_event_list (const std::string &action_descriptor, const std::string &context)
void remove_input_for_action (const std::string &action_descriptor, const std::string &context)
void add_input_for_action (const std::string &action_descriptor, const std::string &context, const input_event &event)
const action_attributes & get_action_attributes (const std::string &action_id, const std::string &context="default", bool *overwrites_default=nullptr)
Get the attributes of the action associated with an action ID by searching the given context and the default context.
translation get_default_action_name (const std::string &action_id) const
Get a value to be used as the default name for a newly created action.
Private Attributes
t_action_contexts action_contexts
t_key_to_name_map keycode_to_keyname
t_key_to_name_map gamepad_keycode_to_keyname
t_name_to_key_map keyname_to_keycode
int previously_pressed_key
int input_timeout
Friends
class input_context
Detailed Description
Manages the translation from action IDs to associated input.
Planned methods of input:
Single key press: a
Multi-key combination: `a
Gamepad button: A
Definition at line 218 of file input.h.
Member Typedef Documentation
t_action_contexts
using input_manager::t_action_contexts = std::map<std::string, t_actions> private
Definition at line 307 of file input.h.
t_actions
using input_manager::t_actions = std::map<std::string, action_attributes> private
Definition at line 306 of file input.h.
t_input_event_list
using input_manager::t_input_event_list = std::vector<input_event> private
Definition at line 305 of file input.h.
t_key_to_name_map
using input_manager::t_key_to_name_map = std::map<int, std::string> private
Definition at line 310 of file input.h.
t_name_to_key_map
using input_manager::t_name_to_key_map = std::map<std::string, int> private
Definition at line 313 of file input.h.
Member Function Documentation
add_gamepad_keycode_pair()
void input_manager::add_gamepad_keycode_pair (int ch, const std::string & name) private
Definition at line 336 of file input.cpp.
{
    gamepad_keycode_to_keyname[ch] = name;
    keyname_to_keycode[name] = ch;
}
References gamepad_keycode_to_keyname, keyname_to_keycode, and om_direction::name().
Referenced by init_keycode_mapping().
add_input_for_action()
void input_manager::add_input_for_action (const std::string & action_descriptor, const std::string & context, const input_event & event) private
Definition at line 577 of file input.cpp.
{
    t_input_event_list &events = get_or_create_event_list( action_descriptor, context );
    for( auto &events_a : events ) {
        if( events_a == event ) {
            return;
        }
    }
    events.push_back( event );
}
References get_or_create_event_list().
Referenced by input_context::display_menu(), and init().
add_keycode_pair()
void input_manager::add_keycode_pair (int ch, const std::string & name) private
Definition at line 330 of file input.cpp.
{
    keycode_to_keyname[ch] = name;
    keyname_to_keycode[name] = ch;
}
References keycode_to_keyname, keyname_to_keycode, and om_direction::name().
Referenced by init_keycode_mapping().
get_action_attributes()
const action_attributes & input_manager::get_action_attributes (const std::string & action_id, const std::string & context = "default", bool * overwrites_default = nullptr) private
Get the attributes of the action associated with an action ID by searching the given context and the default context.
Parameters
action_id The action ID of the action to find.
context The context in which to get the action. If not found, the "default" context will additionally be checked. Defaults to "default".
overwrites_default If this is non-NULL, this will be used as a return parameter. It will be set to true if the found action was not in the default context. It will be set to false if the found action was in the default context.
Definition at line 479 of file input.cpp.
{
    if( context != default_context_id ) {
        // Check if the action exists in the provided context
        const t_action_contexts::const_iterator action_context = action_contexts.find( context );
        if( action_context != action_contexts.end() ) {
            const t_actions::const_iterator action = action_context->second.find( action_id );
            if( action != action_context->second.end() ) {
                if( overwrites_default ) {
                    *overwrites_default = true;
                }
                return action->second;
            }
        }
    }
    // If not, we use the default binding.
    if( overwrites_default ) {
        *overwrites_default = false;
    }
    t_actions &default_action_context = action_contexts[default_context_id];
    const t_actions::const_iterator default_action = default_action_context.find( action_id );
    if( default_action == default_action_context.end() ) {
        // A new action is created in the event that the requested action is
        // not in the keybindings configuration e.g. the entry is missing.
        default_action_context[action_id].name = get_default_action_name( action_id );
    }
    return default_action_context[action_id];
}
References action, action_contexts, default_context_id(), and get_default_action_name().
Referenced by input_context::action_uses_input(), input_context::display_menu(), input_context::get_action_name(), and get_input_for_action().
get_default_action_name()
translation input_manager::get_default_action_name (const std::string & action_id) const private
Get a value to be used as the default name for a newly created action.
This name should be used as a fallback in cases where it is necessary to create a new action.
Parameters
action_id The action ID of the action.
Returns
If the action ID exists in the default context, the name of that action's name is returned. Otherwise, no_translation(action_id) is returned.
Definition at line 516 of file input.cpp.
{
    const t_action_contexts::const_iterator default_action_context = action_contexts.find(
                default_context_id );
    if( default_action_context == action_contexts.end() ) {
        return no_translation( action_id );
    }
    const t_actions::const_iterator default_action = default_action_context->second.find( action_id );
    if( default_action != default_action_context->second.end() ) {
        return default_action->second.name;
    } else {
        return no_translation( action_id );
    }
}
References action_contexts, default_context_id(), and no_translation().
Referenced by get_action_attributes(), and get_or_create_event_list().
get_first_char_for_action()
int input_manager::get_first_char_for_action (const std::string & action_descriptor, const std::string & context = "default")
Return first char associated with an action ID in a given context.
Definition at line 472 of file input.cpp.
{
    std::vector<input_event> input_events = get_input_for_action( action_descriptor, context );
    return input_events.empty() ? 0 : input_events[0].get_first_input();
}
References get_input_for_action().
get_input_event()
input_event input_manager::get_input_event ()
curses getch() replacement.
Defined in the respective platform wrapper, e.g. sdlcurse.cpp
Definition at line 277 of file ncurses_def.cpp.
{
    int key = ERR;
    input_event rval;
    do {
        previously_pressed_key = 0;
        // flush any output
        catacurses::doupdate();
        key = getch();
        if( key != ERR ) {
            int newch;
            // Clear the buffer of characters that match the one we're going to act on.
            const int prev_timeout = input_timeout;
            set_timeout( 0 );
            do {
                newch = getch();
            } while( newch != ERR && newch == key );
            set_timeout( prev_timeout );
            // If we read a different character than the one we're going to act on, re-queue it.
            if( newch != ERR && newch != key ) {
                ungetch( newch );
            }
        }
        rval = input_event();
        if( key == ERR ) {
            if( input_timeout > 0 ) {
                rval.type = CATA_INPUT_TIMEOUT;
            } else {
                rval.type = CATA_INPUT_ERROR;
            }
            // ncurses mouse handling
        } else if( key == KEY_RESIZE ) {
            catacurses::resizeterm();
        } else if( key == KEY_MOUSE ) {
            MEVENT event;
            if( getmouse( &event ) == OK ) {
                rval.type = CATA_INPUT_MOUSE;
                rval.mouse_pos = point( event.x, event.y );
                if( event.bstate & BUTTON1_CLICKED ) {
                    rval.add_input( MOUSE_BUTTON_LEFT );
                } else if( event.bstate & BUTTON3_CLICKED ) {
                    rval.add_input( MOUSE_BUTTON_RIGHT );
                } else if( event.bstate & REPORT_MOUSE_POSITION ) {
                    rval.add_input( MOUSE_MOVE );
                    if( input_timeout > 0 ) {
                        // Mouse movement seems to clear ncurses timeout
                        set_timeout( input_timeout );
                    }
                } else {
                    rval.type = CATA_INPUT_ERROR;
                }
            } else {
                rval.type = CATA_INPUT_ERROR;
            }
        } else {
            if( key == 127 ) { // == Unicode DELETE
                previously_pressed_key = KEY_BACKSPACE;
                return input_event( KEY_BACKSPACE, CATA_INPUT_KEYBOARD );
            }
            rval.type = CATA_INPUT_KEYBOARD;
            rval.text.append( 1, static_cast<char>( key ) );
            // Read the UTF-8 sequence (if any)
            if( key < 127 ) {
                // Single byte sequence
            } else if( 194 <= key && key <= 223 ) {
                rval.text.append( 1, static_cast<char>( getch() ) );
            } else if( 224 <= key && key <= 239 ) {
                rval.text.append( 1, static_cast<char>( getch() ) );
                rval.text.append( 1, static_cast<char>( getch() ) );
            } else if( 240 <= key && key <= 244 ) {
                rval.text.append( 1, static_cast<char>( getch() ) );
                rval.text.append( 1, static_cast<char>( getch() ) );
                rval.text.append( 1, static_cast<char>( getch() ) );
            } else {
                // Other control character, etc. - no text at all, return an event
                // without the text property
                previously_pressed_key = key;
                return input_event( key, CATA_INPUT_KEYBOARD );
            }
            // Now we have loaded an UTF-8 sequence (possibly several bytes)
            // but we should only return *one* key, so return the code point of it.
            const uint32_t cp = UTF8_getch( rval.text );
            if( cp == UNKNOWN_UNICODE ) {
                // Invalid UTF-8 sequence, this should never happen, what now?
                // Maybe return any error instead?
                previously_pressed_key = key;
                return input_event( key, CATA_INPUT_KEYBOARD );
            }
            previously_pressed_key = cp;
            // for compatibility only add the first byte, not the code point
            // as it would  conflict with the special keys defined by ncurses
            rval.add_input( key );
        }
    } while( key == KEY_RESIZE );
    return rval;
}
References input_event::add_input(), CATA_INPUT_ERROR, CATA_INPUT_KEYBOARD, CATA_INPUT_MOUSE, CATA_INPUT_TIMEOUT, catacurses::doupdate(), input_timeout, KEY_BACKSPACE, MOUSE_BUTTON_LEFT, MOUSE_BUTTON_RIGHT, MOUSE_MOVE, input_event::mouse_pos, previously_pressed_key, catacurses::resizeterm(), set_timeout(), input_event::text, input_event::type, UNKNOWN_UNICODE, and UTF8_getch().
Referenced by debug_error_prompt(), input_context::handle_input(), anonymous_namespace{animation.cpp}::hit_animation(), dialogue::opt(), and wait_for_any_key().
get_input_for_action()
const std::vector< input_event > & input_manager::get_input_for_action (const std::string & action_descriptor, const std::string & context = "default", bool * overwrites_default = nullptr)
Get the input events associated with an action ID in a given context.
Parameters
action_descriptor The action ID to get the input events for.
context The context in which to get the input events. Defaults to "default".
overwrites_default If this is non-NULL, this will be used as return parameter and will be set to true if the default keybinding is overridden by something else in the given context.
Definition at line 464 of file input.cpp.
{
    const action_attributes &attributes = get_action_attributes( action_descriptor, context,
                                          overwrites_default );
    return attributes.input_events;
}
References get_action_attributes(), and action_attributes::input_events.
Referenced by input_context::get_available_single_char_hotkeys(), input_context::get_desc(), get_first_char_for_action(), input_context::input_to_action(), input_context::keys_bound_to(), and input_context::press_x().
get_keycode()
int input_manager::get_keycode (const std::string & name) const
Get the keycode associated with the given key name.
Definition at line 402 of file input.cpp.
{
    const t_name_to_key_map::const_iterator a = keyname_to_keycode.find( name );
    if( a != keyname_to_keycode.end() ) {
        return a->second;
    }
    // Not found in map, try to parse as int
    if( name.compare( 0, 8, "UNKNOWN_" ) == 0 ) {
        return str_to_int( name.substr( 8 ) );
    }
    return 0;
}
References a, keyname_to_keycode, om_direction::name(), and str_to_int().
Referenced by load().
get_keyname()
std::string input_manager::get_keyname (int ch, input_event_t inp_type, bool portable = false) const
Get the key name associated with the given keyboard keycode.
Parameters
ch Character code.
inp_type Whether the keycode is a gamepad or a keyboard code.
portable If true, return a language independent and portable name of the key. This acts as the inverse to get_keyname: get_keyname(get_keycode(a), , true) == a
Definition at line 415 of file input.cpp.
{
    cata::optional<std::string> raw;
    if( inp_type == CATA_INPUT_KEYBOARD ) {
        const t_key_to_name_map::const_iterator a = keycode_to_keyname.find( ch );
        if( a != keycode_to_keyname.end() ) {
            if( IS_F_KEY( ch ) ) {
                // special case it since F<num> key names are generated using loop
                // and not marked individually for translation
                if( portable ) {
                    return a->second;
                } else {
                    return string_format( pgettext( "function key name", "F%d" ), F_KEY_NUM( ch ) );
                }
            } else if( ch >= char_key_beg && ch <= char_key_end && ch != ' ' ) {
                // character keys except space need no translation
                return a->second;
            }
            raw = a->second;
        }
    } else if( inp_type == CATA_INPUT_MOUSE ) {
        if( ch == MOUSE_BUTTON_LEFT ) {
            raw = translate_marker_context( "key name", "MOUSE_LEFT" );
        } else if( ch == MOUSE_BUTTON_RIGHT ) {
            raw = translate_marker_context( "key name", "MOUSE_RIGHT" );
        } else if( ch == SCROLLWHEEL_UP ) {
            raw = translate_marker_context( "key name", "SCROLL_UP" );
        } else if( ch == SCROLLWHEEL_DOWN ) {
            raw = translate_marker_context( "key name", "SCROLL_DOWN" );
        } else if( ch == MOUSE_MOVE ) {
            raw = translate_marker_context( "key name", "MOUSE_MOVE" );
        }
    } else if( inp_type == CATA_INPUT_GAMEPAD ) {
        const t_key_to_name_map::const_iterator a = gamepad_keycode_to_keyname.find( ch );
        if( a != gamepad_keycode_to_keyname.end() ) {
            raw = a->second;
        }
    } else {
        raw = translate_marker_context( "key name", "UNKNOWN" );
    }
    if( !raw ) {
        if( portable ) {
            return std::string( "UNKNOWN_" ) + int_to_str( ch );
        }
        return string_format( _( "unknown key %ld" ), ch );
    }
    return portable ? *raw : pgettext( "key name", raw->c_str() );
}
References _, a, CATA_INPUT_GAMEPAD, CATA_INPUT_KEYBOARD, CATA_INPUT_MOUSE, char_key_beg, char_key_end, F_KEY_NUM(), gamepad_keycode_to_keyname, int_to_str(), IS_F_KEY(), keycode_to_keyname, MOUSE_BUTTON_LEFT, MOUSE_BUTTON_RIGHT, MOUSE_MOVE, pgettext(), SCROLLWHEEL_DOWN, SCROLLWHEEL_UP, string_format(), and translate_marker_context.
Referenced by input_context::get_desc(), game::handle_action(), input_context::press_x(), and save().
get_or_create_event_list()
input_manager::t_input_event_list & input_manager::get_or_create_event_list (const std::string & action_descriptor, const std::string & context) private
Definition at line 532 of file input.cpp.
{
    // A new context is created in the event that the user creates a local
    // keymapping in a context that doesn't yet exist e.g. a context without
    // any pre-existing keybindings.
    t_actions &actions = action_contexts[context];
    // A new action is created in the event that the user creates a local
    // keymapping that masks a global one.
    if( actions.find( action_descriptor ) == actions.end() ) {
        action_attributes &attributes = actions[action_descriptor];
        attributes.name = get_default_action_name( action_descriptor );
        attributes.is_user_created = true;
    }
    return actions[action_descriptor].input_events;
}
References action_contexts, get_default_action_name(), action_attributes::is_user_created, and action_attributes::name.
Referenced by add_input_for_action().
get_previously_pressed_key()
int input_manager::get_previously_pressed_key () const
Return the previously pressed key, or 0 if there is no previous input or the previous input wasn't a key.
Definition at line 1304 of file input.cpp.
{
    return previously_pressed_key;
}
References previously_pressed_key.
get_timeout()
int input_manager::get_timeout () const inline
Definition at line 298 of file input.h.
{
            return input_timeout;
        }
References input_timeout.
Referenced by input_context::handle_input(), and signal_handler().
init()
void input_manager::init ()
Initializes the input manager, aka loads the input mapping configuration JSON.
Definition at line 111 of file input.cpp.
{
    std::map<char, action_id> keymap;
    std::string keymap_file_loaded_from;
    std::set<action_id> unbound_keymap;
    init_keycode_mapping();
    reset_timeout();
    try {
        load( PATH_INFO::keybindings(), false );
    } catch( const JsonError &err ) {
        throw std::runtime_error( err.what() );
    }
    try {
        load( PATH_INFO::keybindings_vehicle(), false );
    } catch( const JsonError &err ) {
        throw std::runtime_error( err.what() );
    }
    try {
        load( PATH_INFO::keybindings_edit_creature(), false );
    } catch( const JsonError &err ) {
        throw std::runtime_error( err.what() );
    }
    try {
        load( PATH_INFO::user_keybindings(), true );
    } catch( const JsonError &err ) {
        throw std::runtime_error( err.what() );
    }
    if( keymap_file_loaded_from.empty() || ( keymap.empty() && unbound_keymap.empty() ) ) {
        // No keymap file was loaded, or the file has no mappings and no unmappings,
        // we can skip the remaining part of the function, especially the save function
        return;
    }
    t_actions &actions = action_contexts["DEFAULTMODE"];
    std::set<action_id> touched;
    for( std::map<char, action_id>::const_iterator a = keymap.begin(); a != keymap.end(); ++a ) {
        const std::string action_id = action_ident( a->second );
        // Put the binding from keymap either into the global context
        // (if an action with that ident already exists there - think movement keys)
        // or otherwise to the DEFAULTMODE context.
        std::string context = "DEFAULTMODE";
        if( action_contexts[default_context_id].count( action_id ) > 0 ) {
            context = default_context_id;
        } else if( touched.count( a->second ) == 0 ) {
            // Note: movement keys are somehow special as the default in keymap
            // does not contain the arrow keys, so we don't clear existing keybindings
            // for them.
            // If the keymap contains a binding for this action, erase all the
            // previously (default!) existing bindings, to only keep the bindings,
            // the user is used to
            action_contexts[action_id].clear();
            touched.insert( a->second );
        }
        add_input_for_action( action_id, context, input_event( a->first, CATA_INPUT_KEYBOARD ) );
    }
    // Unmap actions that are explicitly not mapped
    for( const auto &elem : unbound_keymap ) {
        const std::string action_id = action_ident( elem );
        actions[action_id].input_events.clear();
    }
    // Imported old bindings from old keymap file, save those to the new
    // keybindings.json file.
    try {
        save();
    } catch( std::exception &err ) {
        debugmsg( "Could not write imported keybindings: %s", err.what() );
        return;
    }
    // Finally if we did import a file, and saved it to the new keybindings
    // file, delete the old keymap file to prevent re-importing it.
    if( !keymap_file_loaded_from.empty() ) {
        remove_file( keymap_file_loaded_from );
    }
}
References a, action_contexts, action_ident(), add_input_for_action(), CATA_INPUT_KEYBOARD, detail::count(), debugmsg, default_context_id(), init_keycode_mapping(), PATH_INFO::keybindings(), PATH_INFO::keybindings_edit_creature(), PATH_INFO::keybindings_vehicle(), load(), remove_file(), reset_timeout(), save(), and PATH_INFO::user_keybindings().
Referenced by game::load_static_data().
init_keycode_mapping()
void input_manager::init_keycode_mapping () private
Definition at line 345 of file input.cpp.
{
    // Between space and tilde, all keys more or less map
    // to themselves(see ASCII table)
    for( char c = char_key_beg; c <= char_key_end; c++ ) {
        std::string name( 1, c );
        add_keycode_pair( c, name );
    }
    add_keycode_pair( '\t',          translate_marker_context( "key name", "TAB" ) );
    add_keycode_pair( KEY_BTAB,      translate_marker_context( "key name", "BACKTAB" ) );
    add_keycode_pair( ' ',           translate_marker_context( "key name", "SPACE" ) );
    add_keycode_pair( KEY_UP,        translate_marker_context( "key name", "UP" ) );
    add_keycode_pair( KEY_DOWN,      translate_marker_context( "key name", "DOWN" ) );
    add_keycode_pair( KEY_LEFT,      translate_marker_context( "key name", "LEFT" ) );
    add_keycode_pair( KEY_RIGHT,     translate_marker_context( "key name", "RIGHT" ) );
    add_keycode_pair( KEY_NPAGE,     translate_marker_context( "key name", "NPAGE" ) );
    add_keycode_pair( KEY_PPAGE,     translate_marker_context( "key name", "PPAGE" ) );
    add_keycode_pair( KEY_ESCAPE,    translate_marker_context( "key name", "ESC" ) );
    add_keycode_pair( KEY_BACKSPACE, translate_marker_context( "key name", "BACKSPACE" ) );
    add_keycode_pair( KEY_HOME,      translate_marker_context( "key name", "HOME" ) );
    add_keycode_pair( KEY_BREAK,     translate_marker_context( "key name", "BREAK" ) );
    add_keycode_pair( KEY_END,       translate_marker_context( "key name", "END" ) );
    add_keycode_pair( '\n',          translate_marker_context( "key name", "RETURN" ) );
    // function keys, as defined by ncurses
    for( int i = F_KEY_NUM_BEG; i <= F_KEY_NUM_END; i++ ) {
        // not marked for translation here, but specially handled in get_keyname so
        // it gets properly translated.
        add_keycode_pair( KEY_F( i ), string_format( "F%d", i ) );
    }
    add_gamepad_keycode_pair( JOY_LEFT,      translate_marker_context( "key name", "JOY_LEFT" ) );
    add_gamepad_keycode_pair( JOY_RIGHT,     translate_marker_context( "key name", "JOY_RIGHT" ) );
    add_gamepad_keycode_pair( JOY_UP,        translate_marker_context( "key name", "JOY_UP" ) );
    add_gamepad_keycode_pair( JOY_DOWN,      translate_marker_context( "key name", "JOY_DOWN" ) );
    add_gamepad_keycode_pair( JOY_LEFTUP,    translate_marker_context( "key name", "JOY_LEFTUP" ) );
    add_gamepad_keycode_pair( JOY_LEFTDOWN,  translate_marker_context( "key name", "JOY_LEFTDOWN" ) );
    add_gamepad_keycode_pair( JOY_RIGHTUP,   translate_marker_context( "key name", "JOY_RIGHTUP" ) );
    add_gamepad_keycode_pair( JOY_RIGHTDOWN, translate_marker_context( "key name", "JOY_RIGHTDOWN" ) );
    add_gamepad_keycode_pair( JOY_0,         translate_marker_context( "key name", "JOY_0" ) );
    add_gamepad_keycode_pair( JOY_1,         translate_marker_context( "key name", "JOY_1" ) );
    add_gamepad_keycode_pair( JOY_2,         translate_marker_context( "key name", "JOY_2" ) );
    add_gamepad_keycode_pair( JOY_3,         translate_marker_context( "key name", "JOY_3" ) );
    add_gamepad_keycode_pair( JOY_4,         translate_marker_context( "key name", "JOY_4" ) );
    add_gamepad_keycode_pair( JOY_5,         translate_marker_context( "key name", "JOY_5" ) );
    add_gamepad_keycode_pair( JOY_6,         translate_marker_context( "key name", "JOY_6" ) );
    add_gamepad_keycode_pair( JOY_7,         translate_marker_context( "key name", "JOY_7" ) );
    keyname_to_keycode["MOUSE_LEFT"] = MOUSE_BUTTON_LEFT;
    keyname_to_keycode["MOUSE_RIGHT"] = MOUSE_BUTTON_RIGHT;
    keyname_to_keycode["SCROLL_UP"] = SCROLLWHEEL_UP;
    keyname_to_keycode["SCROLL_DOWN"] = SCROLLWHEEL_DOWN;
    keyname_to_keycode["MOUSE_MOVE"] = MOUSE_MOVE;
}
References add_gamepad_keycode_pair(), add_keycode_pair(), c, char_key_beg, char_key_end, F_KEY_NUM_BEG, F_KEY_NUM_END, JOY_0, JOY_1, JOY_2, JOY_3, JOY_4, JOY_5, JOY_6, JOY_7, JOY_DOWN, JOY_LEFT, JOY_LEFTDOWN, JOY_LEFTUP, JOY_RIGHT, JOY_RIGHTDOWN, JOY_RIGHTUP, JOY_UP, KEY_BACKSPACE, KEY_BREAK, KEY_BTAB, KEY_DOWN, KEY_END, KEY_ESCAPE, KEY_F(), KEY_HOME, KEY_LEFT, KEY_NPAGE, KEY_PPAGE, KEY_RIGHT, KEY_UP, keyname_to_keycode, MOUSE_BUTTON_LEFT, MOUSE_BUTTON_RIGHT, MOUSE_MOVE, om_direction::name(), SCROLLWHEEL_DOWN, SCROLLWHEEL_UP, string_format(), and translate_marker_context.
Referenced by init().
load()
void input_manager::load (const std::string & file_name, bool is_user_preferences) private
Load keybindings from a json file, override existing bindings.
Throws std::string on errors
Definition at line 187 of file input.cpp.
{
    std::ifstream data_file( file_name.c_str(), std::ifstream::in | std::ifstream::binary );
    if( !data_file.good() ) {
        // Only throw if this is the first file to load, that file _must_ exist,
        // otherwise the keybindings can not be read at all.
        if( action_contexts.empty() ) {
            throw std::runtime_error( std::string( "Could not read " ) + file_name );
        }
        return;
    }
    JsonIn jsin( data_file, file_name );
    //Crawl through once and create an entry for every definition
    jsin.start_array();
    while( !jsin.end_array() ) {
        // JSON object representing the action
        JsonObject action = jsin.get_object();
        const std::string type = action.get_string( "type", "keybinding" );
        if( type != "keybinding" ) {
            debugmsg( "Only objects of type 'keybinding' (not %s) should appear in the "
                      "keybindings file '%s'", type, file_name );
            continue;
        }
        const std::string action_id = action.get_string( "id" );
        const std::string context = action.get_string( "category", default_context_id );
        t_actions &actions = action_contexts[context];
        if( !is_user_preferences && action.has_member( "name" ) ) {
            // Action names are not user preferences. Some experimental builds
            // post-0.A had written action names into the user preferences
            // config file. Any names that exist in user preferences will be
            // ignored.
            action.read( "name", actions[action_id].name );
        }
        t_input_event_list events;
        for( const JsonObject keybinding : action.get_array( "bindings" ) ) {
            std::string input_method = keybinding.get_string( "input_method" );
            input_event new_event;
            if( input_method == "keyboard" ) {
                new_event.type = CATA_INPUT_KEYBOARD;
            } else if( input_method == "gamepad" ) {
                new_event.type = CATA_INPUT_GAMEPAD;
            } else if( input_method == "mouse" ) {
                new_event.type = CATA_INPUT_MOUSE;
            }
            if( keybinding.has_array( "key" ) ) {
                for( const std::string line : keybinding.get_array( "key" ) ) {
                    new_event.sequence.push_back( get_keycode( line ) );
                }
            } else { // assume string if not array, and throw if not string
                new_event.sequence.push_back(
                    get_keycode( keybinding.get_string( "key" ) )
                );
            }
            events.push_back( new_event );
        }
        // An invariant of this class is that user-created, local keybindings
        // with an empty set of input_events do not exist in the
        // action_contexts map. In prior versions of this class, this was not
        // true, so users of experimental builds post-0.A will have empty
        // local keybindings saved in their keybindings.json config.
        //
        // To be backwards compatible with keybindings.json from prior
        // experimental builds, we will detect user-created, local keybindings
        // with empty input_events and disregard them. When keybindings are
        // later saved, these remnants won't be saved.
        if( !is_user_preferences ||
            !events.empty() ||
            context == default_context_id ||
            actions.count( action_id ) > 0 ) {
            // In case this is the second file containing user preferences,
            // this replaces the default bindings with the user's preferences.
            action_attributes &attributes = actions[action_id];
            attributes.input_events = events;
            if( action.has_member( "is_user_created" ) ) {
                attributes.is_user_created = action.get_bool( "is_user_created" );
            }
        }
    }
}
References action, action_contexts, CATA_INPUT_GAMEPAD, CATA_INPUT_KEYBOARD, CATA_INPUT_MOUSE, debugmsg, default_context_id(), JsonIn::end_array(), get_keycode(), JsonIn::get_object(), action_attributes::input_events, action_attributes::is_user_created, line(), om_direction::name(), input_event::sequence, JsonIn::start_array(), type, and input_event::type.
Referenced by init().
pump_events()
void input_manager::pump_events ()
Resize & refresh if necessary, process all pending window events, and ignore keypresses.
Definition at line 252 of file ncurses_def.cpp.
{
    if( test_mode ) {
        return;
    }
    // Handle all events, but ignore any keypress
    int key = ERR;
    bool resize = false;
    const int prev_timeout = input_timeout;
    set_timeout( 0 );
    do {
        key = getch();
        if( key == KEY_RESIZE ) {
            resize = true;
        }
    } while( key != ERR );
    set_timeout( prev_timeout );
    if( resize ) {
        catacurses::resizeterm();
    }
    previously_pressed_key = 0;
}
References input_timeout, previously_pressed_key, catacurses::resizeterm(), set_timeout(), and test_mode.
Referenced by debug_menu::benchmark(), calculate_mapgen_weights(), Item_factory::check_definitions(), constructions::finalize(), recipe_dictionary::finalize_internal(), game::fling_creature(), Character::hardcoded_effects(), defense_game::init_map(), map::load(), DynamicDataLoader::load_all_from_json(), DynamicDataLoader::load_deferred(), map::move_vehicle(), robot_finds_kitten::process_input(), anonymous_namespace{animation.cpp}::basic_animation::progress(), mattack::ranged_pull(), mapbuffer::save(), mapgen_factory::setup(), loading_ui::show(), and game::unserialize().
remove_input_for_action()
void input_manager::remove_input_for_action (const std::string & action_descriptor, const std::string & context) private
Definition at line 551 of file input.cpp.
{
    const t_action_contexts::iterator action_context = action_contexts.find( context );
    if( action_context != action_contexts.end() ) {
        t_actions &actions = action_context->second;
        t_actions::iterator action = actions.find( action_descriptor );
        if( action != actions.end() ) {
            if( action->second.is_user_created ) {
                // Since this is a user created hotkey, remove it so that the
                // user will fallback to the hotkey in the default context.
                actions.erase( action );
            } else {
                // If a context no longer has any keybindings remaining for an action but
                // there's an attempt to remove bindings anyway, presumably the user wants
                // to fully remove the binding from that context.
                if( action->second.input_events.empty() ) {
                    actions.erase( action );
                } else {
                    action->second.input_events.clear();
                }
            }
        }
    }
}
References action, and action_contexts.
Referenced by input_context::display_menu().
reset_timeout()
void input_manager::reset_timeout () inline
Definition at line 295 of file input.h.
{
            set_timeout( -1 );
        }
References set_timeout().
Referenced by input_context::handle_input(), anonymous_namespace{animation.cpp}::hit_animation(), init(), and signal_handler().
save()
void input_manager::save ()
Opposite of init, save the data that has been loaded by init, and possibly been modified.
Definition at line 276 of file input.cpp.
{
    write_to_file( PATH_INFO::user_keybindings(), [&]( std::ostream & data_file ) {
        JsonOut jsout( data_file, true );
        jsout.start_array();
        for( t_action_contexts::const_iterator a = action_contexts.begin(); a != action_contexts.end();
             ++a ) {
            const t_actions &actions = a->second;
            for( const auto &action : actions ) {
                const t_input_event_list &events = action.second.input_events;
                jsout.start_object();
                jsout.member( "id", action.first );
                jsout.member( "category", a->first );
                bool is_user_created = action.second.is_user_created;
                if( is_user_created ) {
                    jsout.member( "is_user_created", is_user_created );
                }
                jsout.member( "bindings" );
                jsout.start_array();
                for( const auto &event : events ) {
                    jsout.start_object();
                    switch( event.type ) {
                        case CATA_INPUT_KEYBOARD:
                            jsout.member( "input_method", "keyboard" );
                            break;
                        case CATA_INPUT_GAMEPAD:
                            jsout.member( "input_method", "gamepad" );
                            break;
                        case CATA_INPUT_MOUSE:
                            jsout.member( "input_method", "mouse" );
                            break;
                        default:
                            throw std::runtime_error( "unknown input_event_t" );
                    }
                    jsout.member( "key" );
                    jsout.start_array();
                    for( size_t i = 0; i < event.sequence.size(); i++ ) {
                        jsout.write( get_keyname( event.sequence[i], event.type, true ) );
                    }
                    jsout.end_array();
                    jsout.end_object();
                }
                jsout.end_array();
                jsout.end_object();
            }
        }
        jsout.end_array();
    }, _( "key bindings configuration" ) );
}
References _, a, action, action_contexts, CATA_INPUT_GAMEPAD, CATA_INPUT_KEYBOARD, CATA_INPUT_MOUSE, JsonOut::end_array(), JsonOut::end_object(), get_keyname(), JsonOut::member(), JsonOut::start_array(), JsonOut::start_object(), PATH_INFO::user_keybindings(), JsonOut::write(), and write_to_file().
Referenced by input_context::display_menu(), and init().
set_timeout()
void input_manager::set_timeout (int t)
Sets global input polling timeout as appropriate for the current interface system.
Use input_context::(re)set_timeout() when possible so timeout will be properly reset when entering a new input context.
Definition at line 375 of file ncurses_def.cpp.
{
    timeout( delay );
    // Use this to determine when curses should return a CATA_INPUT_TIMEOUT event.
    input_timeout = delay;
}
References input_timeout.
Referenced by get_input_event(), input_context::handle_input(), anonymous_namespace{animation.cpp}::hit_animation(), pump_events(), reset_timeout(), and signal_handler().
wait_for_any_key()
void input_manager::wait_for_any_key ()
Wait until the user presses a key.
Mouse and similar input is ignored, only input events from the keyboard are considered.
Definition at line 1309 of file input.cpp.
{
#if defined(__ANDROID__)
    input_context ctxt( "WAIT_FOR_ANY_KEY" );
#endif
    while( true ) {
        const input_event evt = inp_mngr.get_input_event();
        switch( evt.type ) {
            case CATA_INPUT_KEYBOARD:
                if( !evt.sequence.empty() ) {
                    return;
                }
                break;
            // errors are accepted as well to avoid an infinite loop
            case CATA_INPUT_ERROR:
                return;
            default:
                break;
        }
    }
}
References CATA_INPUT_ERROR, CATA_INPUT_KEYBOARD, get_input_event(), inp_mngr, input_event::sequence, and input_event::type.
Referenced by debug_menu::debug(), game::display_scent(), and computer_session::query_any().
Friends And Related Function Documentation
input_context
friend class input_context friend
Definition at line 303 of file input.h.
Member Data Documentation
action_contexts
t_action_contexts input_manager::action_contexts private
Definition at line 308 of file input.h.
Referenced by input_context::clear_conflicting_keybindings(), input_context::display_menu(), get_action_attributes(), get_default_action_name(), get_or_create_event_list(), init(), load(), remove_input_for_action(), and save().
gamepad_keycode_to_keyname
t_key_to_name_map input_manager::gamepad_keycode_to_keyname private
Definition at line 312 of file input.h.
Referenced by add_gamepad_keycode_pair(), and get_keyname().
input_timeout
int input_manager::input_timeout private
Definition at line 331 of file input.h.
Referenced by get_input_event(), get_timeout(), pump_events(), and set_timeout().
keycode_to_keyname
t_key_to_name_map input_manager::keycode_to_keyname private
Definition at line 311 of file input.h.
Referenced by add_keycode_pair(), and get_keyname().
keyname_to_keycode
t_name_to_key_map input_manager::keyname_to_keycode private
Definition at line 314 of file input.h.
Referenced by add_gamepad_keycode_pair(), add_keycode_pair(), get_keycode(), and init_keycode_mapping().
previously_pressed_key
int input_manager::previously_pressed_key private
Definition at line 317 of file input.h.
Referenced by get_input_event(), get_previously_pressed_key(), and pump_events().
The documentation for this class was generated from the following files:
src/input.h
src/input.cpp
src/ncurses_def.cpp