Cataclysm BN: jmapgen_nested::neighborhood_check Class Reference
jmapgen_nested::neighborhood_check Class Reference
Public Member Functions
neighborhood_check (const JsonObject &jsi)
bool test (mapgendata &dat) const
Private Attributes
bool has_any = false
std::array< std::set< oter_str_id >, om_direction::size > neighbors
std::set< oter_str_id > above
Detailed Description
Definition at line 1787 of file mapgen.cpp.
Constructor & Destructor Documentation
neighborhood_check()
jmapgen_nested::neighborhood_check::neighborhood_check (const JsonObject & jsi) inline
Definition at line 1795 of file mapgen.cpp.
{
                    for( om_direction::type dir : om_direction::all ) {
                        int index = static_cast<int>( dir );
                        neighbors[index] = jsi.get_tags<oter_str_id>( om_direction::id( dir ) );
                        has_any |= !neighbors[index].empty();
                        above = jsi.get_tags<oter_str_id>( "above" );
                        has_any |= !above.empty();
                    }
                }
References above, om_direction::all, JsonObject::get_tags(), has_any, om_direction::id(), mapgen_defer::jsi, and neighbors.
Member Function Documentation
test()
bool jmapgen_nested::neighborhood_check::test (mapgendata & dat) const inline
Definition at line 1806 of file mapgen.cpp.
{
                    if( !has_any ) {
                        return true;
                    }
                    bool all_directions_match  = true;
                    for( om_direction::type dir : om_direction::all ) {
                        int index = static_cast<int>( dir );
                        const std::set<oter_str_id> &allowed_neighbors = neighbors[index];
                        if( allowed_neighbors.empty() ) {
                            continue;  // no constraints on this direction, skip.
                        }
                        bool this_direction_matches = false;
                        for( const oter_str_id &allowed_neighbor : allowed_neighbors ) {
                            this_direction_matches |= is_ot_match( allowed_neighbor.str(), dat.neighbor_at( dir ).id(),
                                                                   ot_match_type::contains );
                        }
                        all_directions_match &= this_direction_matches;
                    }
                    if( !above.empty() ) {
                        bool above_matches = false;
                        for( const oter_str_id &allowed_neighbor : above ) {
                            above_matches |= is_ot_match( allowed_neighbor.str(), dat.above().id(), ot_match_type::contains );
                        }
                        all_directions_match &= above_matches;
                    }
                    return all_directions_match;
                }
References above, mapgendata::above(), om_direction::all, contains, has_any, int_id< T >::id(), is_ot_match(), mapgendata::neighbor_at(), and neighbors.
Referenced by jmapgen_nested::apply(), and jmapgen_nested::has_vehicle_collision().
Member Data Documentation
above
std::set<oter_str_id> jmapgen_nested::neighborhood_check::above private
Definition at line 1793 of file mapgen.cpp.
Referenced by neighborhood_check(), and test().
has_any
bool jmapgen_nested::neighborhood_check::has_any = false private
Definition at line 1791 of file mapgen.cpp.
Referenced by neighborhood_check(), and test().
neighbors
std::array<std::set<oter_str_id>, om_direction::size> jmapgen_nested::neighborhood_check::neighbors private
Definition at line 1792 of file mapgen.cpp.
Referenced by neighborhood_check(), and test().
The documentation for this class was generated from the following file:
src/mapgen.cpp