Cataclysm BN: jmapgen_terrain Class Reference
jmapgen_terrain Class Reference
Place terrain.
Public Member Functions
jmapgen_terrain (const JsonObject &jsi)
jmapgen_terrain (const std::string &tid)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, point p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
ter_id id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place terrain.
"ter": id of the terrain.
Definition at line 1487 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_terrain() [1/2]
jmapgen_terrain::jmapgen_terrain (const JsonObject & jsi) inline
Definition at line 1491 of file mapgen.cpp.
: jmapgen_terrain(jsi.get_string("ter")) {}
jmapgen_terrain() [2/2]
jmapgen_terrain::jmapgen_terrain (const std::string & tid) inline
Definition at line 1492 of file mapgen.cpp.
: id(ter_id(tid)) {}
Member Function Documentation
apply()
void jmapgen_terrain::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1493 of file mapgen.cpp.
{
            dat.m.ter_set( point( x.get(), y.get() ), id );
            // Delete furniture if a wall was just placed over it. TODO: need to do anything for fluid, monsters?
            if( dat.m.has_flag_ter( "WALL", point( x.get(), y.get() ) ) ) {
                dat.m.furn_set( point( x.get(), y.get() ), f_null );
                // and items, unless the wall has PLACE_ITEM flag indicating it stores things.
                if( !dat.m.has_flag_ter( "PLACE_ITEM", point( x.get(), y.get() ) ) ) {
                    dat.m.i_clear( tripoint( x.get(), y.get(), dat.m.get_abs_sub().z ) );
                }
            }
        }
References f_null, map::furn_set(), jmapgen_int::get(), map::get_abs_sub(), map::has_flag_ter(), map::i_clear(), mapgendata::m, map::ter_set(), and tripoint::z.
has_vehicle_collision()
bool jmapgen_terrain::has_vehicle_collision (mapgendata & dat, point p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1504 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
id
ter_id jmapgen_terrain::id
Definition at line 1490 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp