Cataclysm BN: tripoint_range< Tripoint > Class Template Reference
tripoint_range< Tripoint > Class Template Reference
#include <map_iterator.h>
Classes
class point_generator
Generates points in a rectangle.
Public Types
using value_type = typename point_generator::value_type
using difference_type = typename point_generator::difference_type
using pointer = typename point_generator::pointer
using reference = typename point_generator::reference
using iterator_category = typename point_generator::iterator_category
Public Member Functions
tripoint_range (const Tripoint &_minp, const Tripoint &_maxp)
point_generator begin () const
point_generator end () const
size_t size () const
bool empty () const
bool is_point_inside (const Tripoint &point) const
const Tripoint & min () const
const Tripoint & max () const
Private Types
using traits = point_traits< Tripoint >
Private Attributes
Tripoint minp
Tripoint maxp
Detailed Description
template<typename Tripoint>
class tripoint_range< Tripoint >
Definition at line 12 of file map_iterator.h.
Member Typedef Documentation
difference_type
template<typename Tripoint > using tripoint_range< Tripoint >::difference_type = typename point_generator::difference_type
Definition at line 79 of file map_iterator.h.
iterator_category
template<typename Tripoint > using tripoint_range< Tripoint >::iterator_category = typename point_generator::iterator_category
Definition at line 82 of file map_iterator.h.
pointer
template<typename Tripoint > using tripoint_range< Tripoint >::pointer = typename point_generator::pointer
Definition at line 80 of file map_iterator.h.
reference
template<typename Tripoint > using tripoint_range< Tripoint >::reference = typename point_generator::reference
Definition at line 81 of file map_iterator.h.
traits
template<typename Tripoint > using tripoint_range< Tripoint >::traits = point_traits<Tripoint> private
Definition at line 16 of file map_iterator.h.
value_type
template<typename Tripoint > using tripoint_range< Tripoint >::value_type = typename point_generator::value_type
Definition at line 78 of file map_iterator.h.
Constructor & Destructor Documentation
tripoint_range()
template<typename Tripoint > tripoint_range< Tripoint >::tripoint_range (const Tripoint & _minp, const Tripoint & _maxp) inline
Definition at line 84 of file map_iterator.h.
                                                                       :
            minp( _minp ), maxp( _maxp ) {
        }
Member Function Documentation
begin()
template<typename Tripoint > point_generator tripoint_range< Tripoint >::begin () const inline
Definition at line 88 of file map_iterator.h.
{
            return point_generator( minp, *this );
        }
References tripoint_range< Tripoint >::minp.
Referenced by npc::move_away_from().
empty()
template<typename Tripoint > bool tripoint_range< Tripoint >::empty () const inline
Definition at line 103 of file map_iterator.h.
{
            return size() == 0;
        }
References tripoint_range< Tripoint >::size().
end()
template<typename Tripoint > point_generator tripoint_range< Tripoint >::end () const inline
Definition at line 92 of file map_iterator.h.
{
            // Return the point AFTER the last one
            // That is, point under (in z-levels) the first one, but one z-level below the last one
            return point_generator( Tripoint( minp.xy(), traits::z( maxp ) + 1 ), *this );
        }
References tripoint_range< Tripoint >::maxp, tripoint_range< Tripoint >::minp, and point_traits< Point, typename >::z().
Referenced by npc::move_away_from().
is_point_inside()
template<typename Tripoint > bool tripoint_range< Tripoint >::is_point_inside (const Tripoint & point) const inline
Definition at line 107 of file map_iterator.h.
{
            for( const Tripoint &current : *this ) {
                if( current == point ) {
                    return true;
                }
            }
            return false;
        }
Referenced by iuse::camera(), debug_menu::debug(), enumerate_objects_around_point(), and distribution_grid_tracker::on_saved().
max()
template<typename Tripoint > const Tripoint & tripoint_range< Tripoint >::max () const inline
Definition at line 119 of file map_iterator.h.
{
            return maxp;
        }
References tripoint_range< Tripoint >::maxp.
Referenced by random_point(), and explosion_handler::shrapnel().
min()
template<typename Tripoint > const Tripoint & tripoint_range< Tripoint >::min () const inline
Definition at line 116 of file map_iterator.h.
{
            return minp;
        }
References tripoint_range< Tripoint >::minp.
Referenced by random_point(), and explosion_handler::shrapnel().
size()
template<typename Tripoint > size_t tripoint_range< Tripoint >::size () const inline
Definition at line 98 of file map_iterator.h.
{
            Tripoint range( maxp - minp );
            return std::max( ++traits::x( range ) * ++traits::y( range ) * ++traits::z( range ), 0 );
        }
References tripoint_range< Tripoint >::maxp, tripoint_range< Tripoint >::minp, point_traits< Point, typename >::x(), point_traits< Point, typename >::y(), and point_traits< Point, typename >::z().
Referenced by tripoint_range< Tripoint >::empty().
Member Data Documentation
maxp
template<typename Tripoint > Tripoint tripoint_range< Tripoint >::maxp private
Definition at line 76 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::end(), tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::size().
minp
template<typename Tripoint > Tripoint tripoint_range< Tripoint >::minp private
Definition at line 75 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::begin(), tripoint_range< Tripoint >::end(), tripoint_range< Tripoint >::min(), tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::size().
The documentation for this class was generated from the following files:
src/game.h
src/map_iterator.h