Cataclysm BN: item_location::impl::nowhere Class Reference
item_location::impl::nowhere Class Reference
Public Member Functions
type where () const override
tripoint position () const override
std::string describe (const Character *) const override
item_location obtain (Character &, int) override
int obtain_cost (const Character &, int) const override
void remove_item () override
item * unpack (int) const override
void serialize (JsonOut &js) const override
void make_dirty () override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual item_location parent_item () const
item * target () const
virtual bool valid () const
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 123 of file item_location.cpp.
Member Function Documentation
describe()
std::string item_location::impl::nowhere::describe (const Character *) const inline override virtual
Implements item_location::impl.
Definition at line 135 of file item_location.cpp.
{
            debugmsg( "invalid use of nowhere item_location" );
            return "";
        }
References debugmsg.
make_dirty()
void item_location::impl::nowhere::make_dirty () inline override virtual
Implements item_location::impl.
Definition at line 164 of file item_location.cpp.
{}
obtain()
item_location item_location::impl::nowhere::obtain (Character & , int) inline override virtual
Implements item_location::impl.
Definition at line 140 of file item_location.cpp.
{
            debugmsg( "invalid use of nowhere item_location" );
            return item_location();
        }
References debugmsg, and item_location::item_location().
obtain_cost()
int item_location::impl::nowhere::obtain_cost (const Character & , int) const inline override virtual
Implements item_location::impl.
Definition at line 145 of file item_location.cpp.
{
            debugmsg( "invalid use of nowhere item_location" );
            return 0;
        }
References debugmsg.
position()
tripoint item_location::impl::nowhere::position () const inline override virtual
Implements item_location::impl.
Definition at line 130 of file item_location.cpp.
{
            debugmsg( "invalid use of nowhere item_location" );
            return tripoint_min;
        }
References debugmsg, and tripoint_min.
remove_item()
void item_location::impl::nowhere::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 150 of file item_location.cpp.
{
            debugmsg( "invalid use of nowhere item_location" );
        }
References debugmsg.
serialize()
void item_location::impl::nowhere::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 158 of file item_location.cpp.
{
            js.start_object();
            js.member( "type", "null" );
            js.end_object();
        }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
unpack()
item * item_location::impl::nowhere::unpack (int) const inline override virtual
Implements item_location::impl.
Definition at line 154 of file item_location.cpp.
{
            return nullptr;
        }
where()
type item_location::impl::nowhere::where () const inline override virtual
Implements item_location::impl.
Definition at line 126 of file item_location.cpp.
{
            return type::invalid;
        }
References item_location::invalid.
The documentation for this class was generated from the following file:
src/item_location.cpp