Cataclysm BN: jmapgen_alternativly< PieceType > Class Template Reference
jmapgen_alternativly< PieceType > Class Template Reference
This is a generic mapgen piece, the template parameter PieceType should be another specific type of jmapgen_piece.
Public Member Functions
jmapgen_alternativly ()=default
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, const point &p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
std::vector< PieceType > alternatives
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
template<typename PieceType>
class jmapgen_alternativly< PieceType >
This is a generic mapgen piece, the template parameter PieceType should be another specific type of jmapgen_piece.
This class contains a vector of those objects and will chose one of it at random.
Definition at line 818 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_alternativly()
template<typename PieceType > jmapgen_alternativly< PieceType >::jmapgen_alternativly () default
Member Function Documentation
apply()
template<typename PieceType > void jmapgen_alternativly< PieceType >::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 825 of file mapgen.cpp.
{
            if( const auto chosen = random_entry_opt( alternatives ) ) {
                chosen->get().apply( dat, x, y );
            }
        }
References jmapgen_alternativly< PieceType >::alternatives, and random_entry_opt().
has_vehicle_collision()
template<typename PieceType > bool jmapgen_alternativly< PieceType >::has_vehicle_collision (mapgendata & dat, const point & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 830 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
alternatives
template<typename PieceType > std::vector<PieceType> jmapgen_alternativly< PieceType >::alternatives
Definition at line 823 of file mapgen.cpp.
Referenced by jmapgen_alternativly< PieceType >::apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp