Cataclysm BN: mon_special_attack Class Reference
mon_special_attack Class Reference
#include <monster.h>
Public Member Functions
void serialize (JsonOut &json) const
Public Attributes
int cooldown = 0
bool enabled = true
Detailed Description
Definition at line 44 of file monster.h.
Member Function Documentation
serialize()
void mon_special_attack::serialize (JsonOut & json) const
Definition at line 2014 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "cooldown", cooldown );
    json.member( "enabled", enabled );
    json.end_object();
}
References mutation_branch::cooldown, enabled, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
cooldown
int mon_special_attack::cooldown = 0
Definition at line 47 of file monster.h.
Referenced by monster::move(), monster::process_turn(), and monster::shortest_special_cooldown().
enabled
bool mon_special_attack::enabled = true
Definition at line 48 of file monster.h.
Referenced by monster::move(), monster::process_turn(), and monster::shortest_special_cooldown().
The documentation for this class was generated from the following files:
src/monster.h
src/savegame_json.cpp