Cataclysm BN: enchantment Class Reference
enchantment Class Reference
#include <magic_enchantment.h>
Public Types
enum has { WIELD , WORN , HELD , NUM_HAS }
enum condition {
ALWAYS , UNDERGROUND , UNDERWATER , ACTIVE ,
NUM_CONDITION
}
Public Member Functions
void load (const JsonObject &jo, const std::string &src="")
bool add (const enchantment &rhs)
void force_add (const enchantment &rhs)
int get_value_add (enchant_vals::mod value) const
double get_value_multiply (enchant_vals::mod value) const
double calc_bonus (enchant_vals::mod value, double base, bool round=false) const
Calculate bonus provided by this enchantment for given base value.
bool is_active (const Character &guy, const item &parent) const
bool is_active (const Character &guy, bool active) const
bool is_active_when_wielded () const
Whether this enchantment will be active if parent item is wielded.
void activate_passive (Character &guy) const
void serialize (JsonOut &jsout) const
void cast_hit_you (Character &caster, const Creature &target) const
void cast_hit_me (Character &caster, const Creature *target) const
const std::set< trait_id > & get_mutations () const
bool operator== (const enchantment &rhs) const
void check () const
Static Public Member Functions
static void load_enchantment (const JsonObject &jo, const std::string &src)
static void reset ()
static void check_consistency ()
Public Attributes
enchantment_id id
bool was_loaded = false
Private Member Functions
void add_activation (const time_duration &freq, const fake_spell &fake)
bool stacks_with (const enchantment &rhs) const
int mult_bonus (enchant_vals::mod value_type, int base_value) const
void cast_enchantment_spell (Character &caster, const Creature *target, const fake_spell &sp) const
Private Attributes
std::set< trait_id > mutations
cata::optional< emit_id > emitter
std::map< efftype_id, int > ench_effects
std::map< enchant_vals::mod, int > values_add
std::map< enchant_vals::mod, double > values_multiply
std::vector< fake_spell > hit_me_effect
std::vector< fake_spell > hit_you_effect
std::map< time_duration, std::vector< fake_spell > > intermittent_activation
std::pair< has, condition > active_conditions
Detailed Description
Definition at line 72 of file magic_enchantment.h.
Member Enumeration Documentation
condition
enum enchantment::condition
Enumerator
ALWAYS
UNDERGROUND
UNDERWATER
ACTIVE
NUM_CONDITION
Definition at line 83 of file magic_enchantment.h.
                       {
            ALWAYS,
            UNDERGROUND,
            UNDERWATER,
            ACTIVE, // the item, mutation, etc. is active
            NUM_CONDITION
        };
has
enum enchantment::has
Enumerator
WIELD
WORN
HELD
NUM_HAS
Definition at line 76 of file magic_enchantment.h.
                 {
            WIELD,
            WORN,
            HELD,
            NUM_HAS
        };
Member Function Documentation
activate_passive()
void enchantment::activate_passive (Character & guy) const
Definition at line 451 of file magic_enchantment.cpp.
{
    guy.mod_str_bonus( calc_bonus( enchant_vals::mod::STRENGTH, guy.get_str_base(), true ) );
    guy.mod_dex_bonus( calc_bonus( enchant_vals::mod::DEXTERITY, guy.get_dex_base(), true ) );
    guy.mod_per_bonus( calc_bonus( enchant_vals::mod::PERCEPTION, guy.get_per_base(), true ) );
    guy.mod_int_bonus( calc_bonus( enchant_vals::mod::INTELLIGENCE, guy.get_int_base(), true ) );
    guy.mod_num_dodges_bonus( calc_bonus(
                                  enchant_vals::mod::BONUS_DODGE,
                                  guy.get_num_dodges_base(),
                                  true
                              ) );
    if( emitter ) {
        get_map().emit_field( guy.pos(), *emitter );
    }
    for( const std::pair<efftype_id, int> eff : ench_effects ) {
        guy.add_effect( eff.first, 1_seconds, num_bp, eff.second );
    }
    for( const std::pair<const time_duration, std::vector<fake_spell>> &activation :
         intermittent_activation ) {
        // a random approximation!
        if( one_in( to_seconds<int>( activation.first ) ) ) {
            for( const fake_spell &fake : activation.second ) {
                fake.get_spell( 0 ).cast_all_effects( guy, guy.pos() );
            }
        }
    }
}
References Creature::add_effect(), enchant_vals::BONUS_DODGE, calc_bonus(), spell::cast_all_effects(), enchant_vals::DEXTERITY, map::emit_field(), emitter, ench_effects, Character::get_dex_base(), Character::get_int_base(), get_map(), Creature::get_num_dodges_base(), Character::get_per_base(), fake_spell::get_spell(), Character::get_str_base(), enchant_vals::INTELLIGENCE, intermittent_activation, Character::mod_dex_bonus(), Character::mod_int_bonus(), Creature::mod_num_dodges_bonus(), Character::mod_per_bonus(), Character::mod_str_bonus(), num_bp, one_in(), enchant_vals::PERCEPTION, Character::pos(), and enchant_vals::STRENGTH.
add()
bool enchantment::add (const enchantment & rhs)
Definition at line 362 of file magic_enchantment.cpp.
{
    if( !stacks_with( rhs ) ) {
        return false;
    }
    force_add( rhs );
    return true;
}
References force_add(), and stacks_with().
Referenced by calc_bonus(), and load().
add_activation()
void enchantment::add_activation (const time_duration & freq, const fake_spell & fake) private
Definition at line 201 of file magic_enchantment.cpp.
{
    intermittent_activation[freq].emplace_back( fake );
}
References intermittent_activation.
Referenced by load().
calc_bonus()
double enchantment::calc_bonus (enchant_vals::mod value, double base, bool round = false) const
Calculate bonus provided by this enchantment for given base value.
Definition at line 422 of file magic_enchantment.cpp.
{
    bool use_add = true;
    switch( value ) {
        case enchant_vals::mod::METABOLISM:
        case enchant_vals::mod::MANA_REGEN:
        case enchant_vals::mod::STAMINA_CAP:
        case enchant_vals::mod::STAMINA_REGEN:
        case enchant_vals::mod::THIRST:
        case enchant_vals::mod::FATIGUE:
            use_add = false;
            break;
        default:
            break;
    }
    double add = use_add ? get_value_add( value ) : 0.0;
    double mul = get_value_multiply( value );
    double ret = add + base * mul;
    if( round ) {
        ret = trunc( ret );
    }
    return ret;
}
References add(), enchant_vals::FATIGUE, get_value_add(), get_value_multiply(), enchant_vals::MANA_REGEN, enchant_vals::METABOLISM, cata::hash64_detail::ret, enchant_vals::STAMINA_CAP, enchant_vals::STAMINA_REGEN, and enchant_vals::THIRST.
Referenced by activate_passive().
cast_enchantment_spell()
void enchantment::cast_enchantment_spell (Character & caster, const Creature * target, const fake_spell & sp) const private
Definition at line 495 of file magic_enchantment.cpp.
{
    // check the chances
    if( !one_in( sp.trigger_once_in ) ) {
        return;
    }
    if( sp.self ) {
        caster.add_msg_player_or_npc( m_good,
                                      sp.trigger_message,
                                      sp.npc_trigger_message,
                                      caster.name );
        sp.get_spell( sp.level ).cast_all_effects( caster, caster.pos() );
    } else  if( target != nullptr ) {
        const Creature &trg_crtr = *target;
        const spell &spell_lvl = sp.get_spell( sp.level );
        if( !spell_lvl.is_valid_target( caster, trg_crtr.pos() ) ||
            !spell_lvl.is_target_in_range( caster, trg_crtr.pos() ) ) {
            return;
        }
        caster.add_msg_player_or_npc( m_good,
                                      sp.trigger_message,
                                      sp.npc_trigger_message,
                                      caster.name, trg_crtr.disp_name() );
        spell_lvl.cast_all_effects( caster, trg_crtr.pos() );
    }
}
References Creature::add_msg_player_or_npc(), spell::cast_all_effects(), Creature::disp_name(), fake_spell::get_spell(), spell::is_target_in_range(), spell::is_valid_target(), fake_spell::level, m_good, Character::name, fake_spell::npc_trigger_message, one_in(), Creature::pos(), Character::pos(), fake_spell::self, fake_spell::trigger_message, and fake_spell::trigger_once_in.
Referenced by cast_hit_me(), and cast_hit_you().
cast_hit_me()
void enchantment::cast_hit_me (Character & caster, const Creature * target) const
Definition at line 488 of file magic_enchantment.cpp.
{
    for( const fake_spell &sp : hit_me_effect ) {
        cast_enchantment_spell( caster, target, sp );
    }
}
References cast_enchantment_spell(), and hit_me_effect.
cast_hit_you()
void enchantment::cast_hit_you (Character & caster, const Creature & target) const
Definition at line 481 of file magic_enchantment.cpp.
{
    for( const fake_spell &sp : hit_you_effect ) {
        cast_enchantment_spell( caster, &target, sp );
    }
}
References cast_enchantment_spell(), and hit_you_effect.
check()
void enchantment::check () const
Definition at line 558 of file magic_enchantment.cpp.
{
    // TODO: Where was it declared? CONTEXT!
    const char *ench_desc = id.is_empty() ? "An inline enchantment" : "Enchantment";
    std::vector<std::string> problems;
    for( const trait_id &mut : mutations ) {
        if( !mut.is_valid() ) {
            debugmsg( "%s %s has invalid mutation %s", ench_desc, id.c_str(), mut.c_str() );
        }
        // One enchantment is fine iif it's just us
        if( mut->enchantments.size() > 1 ||
            ( mut->enchantments.size() == 1 &&
              std::count( mut->enchantments.begin(), mut->enchantments.end(), id ) == 0 ) ) {
            problems.push_back(
                string_format( "\nmutation %s which has other enchantments (not supported)", mut.str() ) );
        }
        // TODO: Implement or also list alpha-stat muts and slime perception
        if( !mut->mods.empty() ) {
            problems.push_back(
                string_format( "\nmutation %s which has stat adjustments (not supported)", mut.str() ) );
        }
        // TODO: Implement or also list glass jaw
        if( !is_set_value<&mutation_branch::hp_modifier, &mutation_branch::hp_modifier_secondary, &mutation_branch::hp_adjustment>
            ( mut, 0.0f ) ) {
            problems.push_back( string_format( "\nmutation %s which adjusts hp (not supported)",
                                               mut.str() ) );
        }
    }
    if( !problems.empty() ) {
        debugmsg( "%s %s has: %s", ench_desc, id.c_str(),
                  enumerate_as_string( problems, enumeration_conjunction::none ) );
    }
}
References detail::count(), debugmsg, enumerate_as_string(), mutations, none, and string_format().
Referenced by mutation_branch::check_consistency().
check_consistency()
void enchantment::check_consistency () static
Definition at line 596 of file magic_enchantment.cpp.
{
    enchant_factory.check();
}
References anonymous_namespace{magic_enchantment.cpp}::enchant_factory.
Referenced by DynamicDataLoader::check_consistency().
force_add()
void enchantment::force_add (const enchantment & rhs)
Definition at line 371 of file magic_enchantment.cpp.
{
    for( const std::pair<const enchant_vals::mod, int> &pair_values : rhs.values_add ) {
        values_add[pair_values.first] += pair_values.second;
    }
    for( const std::pair<const enchant_vals::mod, double> &pair_values : rhs.values_multiply ) {
        // values do not multiply against each other, they add.
        // so +10% and -10% will add to 0%
        values_multiply[pair_values.first] += pair_values.second;
    }
    hit_me_effect.insert( hit_me_effect.end(), rhs.hit_me_effect.begin(), rhs.hit_me_effect.end() );
    hit_you_effect.insert( hit_you_effect.end(), rhs.hit_you_effect.begin(), rhs.hit_you_effect.end() );
    ench_effects.insert( rhs.ench_effects.begin(), rhs.ench_effects.end() );
    if( rhs.emitter ) {
        emitter = rhs.emitter;
    }
    for( const trait_id &branch : rhs.mutations ) {
        mutations.emplace( branch );
    }
    for( const std::pair<const time_duration, std::vector<fake_spell>> &act_pair :
         rhs.intermittent_activation ) {
        for( const fake_spell &fake : act_pair.second ) {
            intermittent_activation[act_pair.first].emplace_back( fake );
        }
    }
}
References emitter, ench_effects, hit_me_effect, hit_you_effect, intermittent_activation, mutations, values_add, and values_multiply.
Referenced by add(), and inventory::get_active_enchantment_cache().
get_mutations()
const std::set< trait_id > & enchantment::get_mutations () const inline
Definition at line 138 of file magic_enchantment.h.
{
            return mutations;
        }
References mutations.
get_value_add()
int enchantment::get_value_add (enchant_vals::mod value) const
Definition at line 404 of file magic_enchantment.cpp.
{
    const auto found = values_add.find( value );
    if( found == values_add.cend() ) {
        return 0;
    }
    return found->second;
}
References values_add.
Referenced by calc_bonus(), and serialize().
get_value_multiply()
double enchantment::get_value_multiply (enchant_vals::mod value) const
Definition at line 413 of file magic_enchantment.cpp.
{
    const auto found = values_multiply.find( value );
    if( found == values_multiply.cend() ) {
        return 0;
    }
    return found->second;
}
References values_multiply.
Referenced by calc_bonus(), mult_bonus(), and serialize().
is_active() [1/2]
bool enchantment::is_active (const Character & guy, bool active) const
Definition at line 181 of file magic_enchantment.cpp.
{
    if( active_conditions.second == condition::ACTIVE ) {
        return active;
    }
    if( active_conditions.second == condition::ALWAYS ) {
        return true;
    }
    if( active_conditions.second == condition::UNDERGROUND ) {
        return guy.pos().z < 0;
    }
    if( active_conditions.second == condition::UNDERWATER ) {
        return get_map().is_divable( guy.pos() );
    }
    return false;
}
References active, active_conditions, get_map(), map::is_divable(), Character::pos(), and tripoint::z.
is_active() [2/2]
bool enchantment::is_active (const Character & guy, const item & parent) const
Definition at line 164 of file magic_enchantment.cpp.
{
    if( !guy.has_item( parent ) ) {
        return false;
    }
    if( active_conditions.first == has::WIELD && !guy.is_wielding( parent ) ) {
        return false;
    }
    if( active_conditions.first == has::WORN && !guy.is_worn( parent ) ) {
        return false;
    }
    return is_active( guy, parent.active );
}
References item::active, active_conditions, visitable< T >::has_item(), is_active(), Character::is_wielding(), Character::is_worn(), and WIELD.
Referenced by is_active().
is_active_when_wielded()
bool enchantment::is_active_when_wielded () const inline
Whether this enchantment will be active if parent item is wielded.
Assumes condition is satisfied.
Definition at line 120 of file magic_enchantment.h.
{
            return has::WIELD == active_conditions.first || has::HELD == active_conditions.first;
        }
References active_conditions, and WIELD.
load()
void enchantment::load (const JsonObject & jo, const std::string & src = "")
Definition at line 206 of file magic_enchantment.cpp.
{
    optional( jo, was_loaded, "id", id, enchantment_id( "" ) );
    jo.read( "hit_you_effect", hit_you_effect );
    jo.read( "hit_me_effect", hit_me_effect );
    jo.read( "emitter", emitter );
    if( jo.has_object( "intermittent_activation" ) ) {
        JsonObject jobj = jo.get_object( "intermittent_activation" );
        for( const JsonObject effect_obj : jobj.get_array( "effects" ) ) {
            time_duration freq = read_from_json_string<time_duration>( *effect_obj.get_raw( "frequency" ),
                                 time_duration::units );
            if( effect_obj.has_array( "spell_effects" ) ) {
                for( const JsonObject fake_spell_obj : effect_obj.get_array( "spell_effects" ) ) {
                    fake_spell fake;
                    fake.load( fake_spell_obj );
                    add_activation( freq, fake );
                }
            } else if( effect_obj.has_object( "spell_effects" ) ) {
                fake_spell fake;
                JsonObject fake_spell_obj = effect_obj.get_object( "spell_effects" );
                fake.load( fake_spell_obj );
                add_activation( freq, fake );
            }
        }
    }
    active_conditions.first = io::string_to_enum<has>( jo.get_string( "has", "HELD" ) );
    active_conditions.second = io::string_to_enum<condition>( jo.get_string( "condition",
                               "ALWAYS" ) );
    for( JsonObject jsobj : jo.get_array( "ench_effects" ) ) {
        ench_effects.emplace( efftype_id( jsobj.get_string( "effect" ) ), jsobj.get_int( "intensity" ) );
    }
    optional( jo, was_loaded, "mutations", mutations );
    if( jo.has_array( "values" ) ) {
        for( const JsonObject value_obj : jo.get_array( "values" ) ) {
            std::string value_raw = value_obj.get_string( "value" );
            std::string value_new = migrate_ench_vals_enums( value_raw );
            if( json_report_strict && value_new != value_raw ) {
                value_obj.show_warning(
                    string_format( "%s has been renamed to %s", value_raw, value_new ), "value" );
            }
            enchant_vals::mod value;
            try {
                value = io::string_to_enum<enchant_vals::mod>( value_new );
            } catch( const std::exception &e ) {
                value_obj.show_warning(
                    string_format( "Unknown enchant_val '%s', ignoring", value_new ), "value" );
                continue;
            }
            const int add = value_obj.get_int( "add", 0 );
            const double mult = value_obj.get_float( "multiply", 0.0 );
            if( add != 0 ) {
                values_add.emplace( value, add );
            }
            if( mult != 0.0 ) {
                // Limit precision to minimize inconsistencies between platforms / compilers
                const double mul = static_cast<int>( std::round( mult * 100'000 ) ) / 100'000.0;
                values_multiply.emplace( value, mul );
            }
        }
    }
}
References active_conditions, add(), add_activation(), efftype_id, emitter, ench_effects, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), hit_me_effect, hit_you_effect, json_report_strict, fake_spell::load(), migrate_ench_vals_enums(), mutations, optional(), JsonObject::read(), string_format(), time_duration::units, values_add, values_multiply, and was_loaded.
Referenced by relic::load().
load_enchantment()
void enchantment::load_enchantment (const JsonObject & jo, const std::string & src) static
Definition at line 154 of file magic_enchantment.cpp.
{
    enchant_factory.load( jo, src );
}
References anonymous_namespace{magic_enchantment.cpp}::enchant_factory.
Referenced by DynamicDataLoader::initialize().
mult_bonus()
int enchantment::mult_bonus (enchant_vals::mod value_type, int base_value) const private
Definition at line 446 of file magic_enchantment.cpp.
{
    return get_value_multiply( value_type ) * base_value;
}
References get_value_multiply().
operator==()
bool enchantment::operator== (const enchantment & rhs) const
Definition at line 526 of file magic_enchantment.cpp.
{
    return id == rhs.id &&
           mutations == rhs.mutations &&
           emitter == rhs.emitter &&
           ench_effects == rhs.ench_effects &&
           values_multiply == rhs.values_multiply &&
           values_add == rhs.values_add &&
           hit_me_effect == rhs.hit_me_effect &&
           hit_you_effect == rhs.hit_you_effect &&
           intermittent_activation == intermittent_activation &&
           active_conditions == rhs.active_conditions;
}
References active_conditions, emitter, ench_effects, hit_me_effect, hit_you_effect, id, intermittent_activation, mutations, values_add, and values_multiply.
reset()
void enchantment::reset () static
Definition at line 159 of file magic_enchantment.cpp.
{
    enchant_factory.reset();
}
References anonymous_namespace{magic_enchantment.cpp}::enchant_factory.
Referenced by DynamicDataLoader::unload_data().
serialize()
void enchantment::serialize (JsonOut & jsout) const
Definition at line 275 of file magic_enchantment.cpp.
{
    jsout.start_object();
    if( !id.is_empty() ) {
        jsout.member( "id", id );
        jsout.end_object();
        // if the enchantment has an id then it is defined elsewhere and does not need to be serialized.
        return;
    }
    jsout.member( "has", io::enum_to_string<has>( active_conditions.first ) );
    jsout.member( "condition", io::enum_to_string<condition>( active_conditions.second ) );
    if( emitter ) {
        jsout.member( "emitter", emitter );
    }
    if( !hit_you_effect.empty() ) {
        jsout.member( "hit_you_effect", hit_you_effect );
    }
    if( !hit_me_effect.empty() ) {
        jsout.member( "hit_me_effect", hit_me_effect );
    }
    if( !intermittent_activation.empty() ) {
        jsout.member( "intermittent_activation" );
        jsout.start_object();
        jsout.member( "effects" );
        jsout.start_array();
        for( const std::pair<time_duration, std::vector<fake_spell>> pair : intermittent_activation ) {
            jsout.start_object();
            jsout.member( "frequency" );
            dump_to_json_string<time_duration>( pair.first, jsout, time_duration::units );
            jsout.member( "spell_effects" );
            jsout.start_array();
            for( const fake_spell &sp : pair.second ) {
                sp.serialize( jsout );
            }
            jsout.end_array();
            jsout.end_object();
        }
        jsout.end_array();
        jsout.end_object();
    }
    if( !ench_effects.empty() ) {
        jsout.member( "ench_effects" );
        jsout.start_array();
        for( const std::pair<const efftype_id, int> &eff : ench_effects ) {
            jsout.start_object();
            jsout.member( "effect", eff.first );
            jsout.member( "intensity", eff.second );
            jsout.end_object();
        }
        jsout.end_array();
    }
    jsout.member( "mutations", mutations );
    jsout.member( "values" );
    jsout.start_array();
    for( int value = 0; value < static_cast<int>( enchant_vals::mod::NUM_MOD ); value++ ) {
        enchant_vals::mod enum_value = static_cast<enchant_vals::mod>( value );
        if( get_value_add( enum_value ) == 0 && get_value_multiply( enum_value ) == 0.0 ) {
            continue;
        }
        jsout.start_object();
        jsout.member( "value", io::enum_to_string<enchant_vals::mod>( enum_value ) );
        if( get_value_add( enum_value ) != 0 ) {
            jsout.member( "add", get_value_add( enum_value ) );
        }
        if( get_value_multiply( enum_value ) != 0 ) {
            jsout.member( "multiply", get_value_multiply( enum_value ) );
        }
        jsout.end_object();
    }
    jsout.end_array();
    jsout.end_object();
}
References active_conditions, emitter, ench_effects, JsonOut::end_array(), JsonOut::end_object(), get_value_add(), get_value_multiply(), hit_me_effect, hit_you_effect, intermittent_activation, JsonOut::member(), mutations, enchant_vals::NUM_MOD, fake_spell::serialize(), JsonOut::start_array(), JsonOut::start_object(), and time_duration::units.
stacks_with()
bool enchantment::stacks_with (const enchantment & rhs) const private
Definition at line 357 of file magic_enchantment.cpp.
{
    return active_conditions == rhs.active_conditions;
}
References active_conditions.
Referenced by add().
Member Data Documentation
active_conditions
std::pair<has, condition> enchantment::active_conditions private
Definition at line 161 of file magic_enchantment.h.
Referenced by is_active(), is_active_when_wielded(), load(), operator==(), serialize(), and stacks_with().
emitter
cata::optional<emit_id> enchantment::emitter private
Definition at line 148 of file magic_enchantment.h.
Referenced by activate_passive(), force_add(), load(), operator==(), and serialize().
ench_effects
std::map<efftype_id, int> enchantment::ench_effects private
Definition at line 149 of file magic_enchantment.h.
Referenced by activate_passive(), force_add(), load(), operator==(), and serialize().
hit_me_effect
std::vector<fake_spell> enchantment::hit_me_effect private
Definition at line 156 of file magic_enchantment.h.
Referenced by cast_hit_me(), force_add(), load(), operator==(), and serialize().
hit_you_effect
std::vector<fake_spell> enchantment::hit_you_effect private
Definition at line 157 of file magic_enchantment.h.
Referenced by cast_hit_you(), force_add(), load(), operator==(), and serialize().
id
enchantment_id enchantment::id
Definition at line 127 of file magic_enchantment.h.
Referenced by relic::load(), and operator==().
intermittent_activation
std::map<time_duration, std::vector<fake_spell> > enchantment::intermittent_activation private
Definition at line 159 of file magic_enchantment.h.
Referenced by activate_passive(), add_activation(), force_add(), operator==(), and serialize().
mutations
std::set<trait_id> enchantment::mutations private
Definition at line 147 of file magic_enchantment.h.
Referenced by check(), force_add(), get_mutations(), load(), operator==(), and serialize().
values_add
std::map<enchant_vals::mod, int> enchantment::values_add private
Definition at line 151 of file magic_enchantment.h.
Referenced by force_add(), get_value_add(), load(), and operator==().
values_multiply
std::map<enchant_vals::mod, double> enchantment::values_multiply private
Definition at line 154 of file magic_enchantment.h.
Referenced by force_add(), get_value_multiply(), load(), and operator==().
was_loaded
bool enchantment::was_loaded = false
Definition at line 129 of file magic_enchantment.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/magic_enchantment.h
src/magic_enchantment.cpp