Cataclysm BN: autodrive_activity_actor Class Reference
autodrive_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
autodrive_activity_actor ()=default
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
void finish (player_activity &act, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Attributes
vehicle * player_vehicle = nullptr
Detailed Description
Definition at line 87 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
autodrive_activity_actor()
autodrive_activity_actor::autodrive_activity_actor () default
Referenced by deserialize().
Member Function Documentation
canceled()
void autodrive_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 383 of file activity_actor.cpp.
{
    who.add_msg_if_player( m_info, _( "Auto-drive canceled." ) );
    who.omt_path.clear();
    if( player_vehicle ) {
        player_vehicle->stop_autodriving( false );
    }
    act.set_to_null();
}
References _, act, Creature::add_msg_if_player(), m_info, Character::omt_path, player_vehicle, and vehicle::stop_autodriving().
clone()
std::unique_ptr< activity_actor > autodrive_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 104 of file activity_actor_definitions.h.
{
            return std::make_unique<autodrive_activity_actor>( *this );
        }
deserialize()
std::unique_ptr< activity_actor > autodrive_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 406 of file activity_actor.cpp.
{
    return autodrive_activity_actor().clone();
}
References autodrive_activity_actor().
do_turn()
void autodrive_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 354 of file activity_actor.cpp.
{
    if( who.in_vehicle && who.controlling_vehicle && player_vehicle ) {
        if( who.moves <= 0 ) {
            // out of moves? the driver's not doing anything this turn
            // (but the vehicle will continue moving)
            return;
        }
        switch( player_vehicle->do_autodrive( who ) ) {
            case autodrive_result::ok:
                if( who.moves > 0 ) {
                    // if do_autodrive() didn't eat up all our moves, end the turn
                    // equivalent to player pressing the "pause" button
                    who.moves = 0;
                }
                sounds::reset_markers();
                break;
            case autodrive_result::abort:
                who.cancel_activity();
                break;
            case autodrive_result::finished:
                act.moves_left = 0;
                break;
        }
    } else {
        who.cancel_activity();
    }
}
References abort, act, Character::cancel_activity(), Character::controlling_vehicle, vehicle::do_autodrive(), finished, Character::in_vehicle, Creature::moves, ok, player_vehicle, and sounds::reset_markers().
finish()
void autodrive_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 393 of file activity_actor.cpp.
{
    who.add_msg_if_player( m_info, _( "You have reached your destination." ) );
    player_vehicle->stop_autodriving( false );
    act.set_to_null();
}
References _, act, Creature::add_msg_if_player(), m_info, player_vehicle, and vehicle::stop_autodriving().
get_type()
activity_id autodrive_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 95 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_AUTODRIVE" );
        }
serialize()
void autodrive_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 400 of file activity_actor.cpp.
{
    // Activity is not being saved but still provide some valid json if called.
    jsout.write_null();
}
References JsonOut::write_null().
start()
void autodrive_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 340 of file activity_actor.cpp.
{
    const bool in_vehicle = who.in_vehicle && who.controlling_vehicle;
    const optional_vpart_position vp = get_map().veh_at( who.pos() );
    if( !( vp && in_vehicle ) ) {
        who.cancel_activity();
        return;
    }
    player_vehicle = &vp->vehicle();
    player_vehicle->is_autodriving = true;
    act.moves_left = calendar::INDEFINITELY_LONG;
}
References act, Character::cancel_activity(), Character::controlling_vehicle, get_map(), Character::in_vehicle, calendar::INDEFINITELY_LONG, vehicle::is_autodriving, player_vehicle, Character::pos(), and map::veh_at().
Member Data Documentation
player_vehicle
vehicle* autodrive_activity_actor::player_vehicle = nullptr private
Definition at line 90 of file activity_actor_definitions.h.
Referenced by canceled(), do_turn(), finish(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp