Cataclysm BN: throw_activity_actor Class Reference
throw_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
throw_activity_actor ()=default
throw_activity_actor (item_location target_loc, cata::optional< tripoint > blind_throw_from_pos)
~throw_activity_actor ()=default
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Attributes
item_location target_loc
cata::optional< tripoint > blind_throw_from_pos
Detailed Description
Definition at line 473 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
throw_activity_actor() [1/2]
throw_activity_actor::throw_activity_actor () default
throw_activity_actor() [2/2]
throw_activity_actor::throw_activity_actor (item_location target_loc, cata::optional< tripoint > blind_throw_from_pos) inline
Definition at line 481 of file activity_actor_definitions.h.
          : target_loc( target_loc ),
            blind_throw_from_pos( blind_throw_from_pos ) {}
~throw_activity_actor()
throw_activity_actor::~throw_activity_actor () default
Member Function Documentation
clone()
std::unique_ptr< activity_actor > throw_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 496 of file activity_actor_definitions.h.
{
            return std::make_unique<throw_activity_actor>( *this );
        }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > throw_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 1233 of file activity_actor.cpp.
{
    throw_activity_actor actor;
    JsonObject data = jsin.get_object();
    data.read( "target_loc", actor.target_loc );
    data.read( "blind_throw_from_pos", actor.blind_throw_from_pos );
    return actor.clone();
}
References blind_throw_from_pos, clone(), JsonIn::get_object(), JsonObject::read(), and target_loc.
do_turn()
void throw_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1171 of file activity_actor.cpp.
{
    // Make copies of relevant values since the class would
    // not be available after act.set_to_null()
    item_location target = target_loc;
    cata::optional<tripoint> blind_throw_pos = blind_throw_from_pos;
    // Stop the activity. Whether we will or will not throw doesn't matter.
    act.set_to_null();
    if( !who.is_avatar() ) {
        // Sanity check
        debugmsg( "ACT_THROW is not applicable for NPCs." );
        return;
    }
    // Shift our position to our "peeking" position, so that the UI
    // for picking a throw point lets us target the location we couldn't
    // otherwise see.
    const tripoint original_player_position = who.pos();
    if( blind_throw_pos ) {
        who.setpos( *blind_throw_pos );
    }
    target_handler::trajectory trajectory = target_handler::mode_throw( *who.as_avatar(), *target,
                                            blind_throw_pos.has_value() );
    // If we previously shifted our position, put ourselves back now that we've picked our target.
    if( blind_throw_pos ) {
        who.setpos( original_player_position );
    }
    if( trajectory.empty() ) {
        return;
    }
    if( &*target != &who.weapon ) {
        // This is to represent "implicit offhand wielding"
        int extra_cost = who.item_handling_cost( *target, true, INVENTORY_HANDLING_PENALTY / 2 );
        who.mod_moves( -extra_cost );
    }
    item thrown = *target.get_item();
    if( target->count_by_charges() && target->charges > 1 ) {
        target->mod_charges( -1 );
        thrown.charges = 1;
    } else {
        target.remove_item();
    }
    ranged::throw_item( who, trajectory.back(), thrown, blind_throw_pos );
}
References act, Creature::as_avatar(), blind_throw_from_pos, item::charges, item::count_by_charges(), debugmsg, item_location::get_item(), cata::optional< T >::has_value(), INVENTORY_HANDLING_PENALTY, Creature::is_avatar(), Character::item_handling_cost(), item::mod_charges(), Creature::mod_moves(), target_handler::mode_throw(), Character::pos(), item_location::remove_item(), Character::setpos(), target_loc, ranged::throw_item(), and Character::weapon.
finish()
void throw_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 494 of file activity_actor_definitions.h.
{};
get_type()
activity_id throw_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 488 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_THROW" );
        }
serialize()
void throw_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1223 of file activity_actor.cpp.
{
    jsout.start_object();
    jsout.member( "target_loc", target_loc );
    jsout.member( "blind_throw_from_pos", blind_throw_from_pos );
    jsout.end_object();
}
References blind_throw_from_pos, JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and target_loc.
start()
void throw_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 492 of file activity_actor_definitions.h.
{};
Member Data Documentation
blind_throw_from_pos
cata::optional<tripoint> throw_activity_actor::blind_throw_from_pos private
Definition at line 477 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
target_loc
item_location throw_activity_actor::target_loc private
Definition at line 476 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp