Cataclysm BN: ascii_art Class Reference
ascii_art Class Reference
#include <ascii_art.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &)
Static Public Member Functions
static void reset ()
static void load_ascii_art (const JsonObject &jo, const std::string &src)
Public Attributes
bool was_loaded = false
ascii_art_id id
std::vector< std::string > picture
Detailed Description
Definition at line 13 of file ascii_art.h.
Member Function Documentation
load()
void ascii_art::load (const JsonObject & jo, const std::string &)
Definition at line 41 of file ascii_art.cpp.
{
    assign( jo, "id", id );
    assign( jo, "picture", picture );
    for( std::string &line : picture ) {
        if( utf8_width( remove_color_tags( line ) ) > ascii_art_width ) {
            line = trim_by_length( line, ascii_art_width );
            debugmsg( "picture in %s contains a line too long to be displayed (>%i char).", id.c_str(),
                      ascii_art_width );
        }
    }
}
References ascii_art_width, assign(), debugmsg, line(), picture, remove_color_tags(), trim_by_length(), and utf8_width().
load_ascii_art()
void ascii_art::load_ascii_art (const JsonObject & jo, const std::string & src) static
Definition at line 36 of file ascii_art.cpp.
{
    ascii_art_factory.load( jo, src );
}
References anonymous_namespace{ascii_art.cpp}::ascii_art_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void ascii_art::reset () static
Definition at line 31 of file ascii_art.cpp.
{
    ascii_art_factory.reset();
}
References anonymous_namespace{ascii_art.cpp}::ascii_art_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
id
ascii_art_id ascii_art::id
Definition at line 21 of file ascii_art.h.
picture
std::vector<std::string> ascii_art::picture
Definition at line 22 of file ascii_art.h.
Referenced by load().
was_loaded
bool ascii_art::was_loaded = false
Definition at line 19 of file ascii_art.h.
The documentation for this class was generated from the following files:
src/ascii_art.h
src/ascii_art.cpp