Cataclysm BN: battery_tile Class Reference
battery_tile Class Reference
#include <active_tile_data_def.h>
Public Member Functions
void update_internal (time_point to, const tripoint_abs_ms &p, distribution_grid &grid) override
active_tile_data * clone () const override
const std::string & get_type () const override
void store (JsonOut &jsout) const override
void load (JsonObject &jo) override
int get_resource () const
int mod_resource (int amt)
Public Member Functions inherited from active_tile_data
void update (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)
time_point get_last_updated ()
void set_last_updated (time_point t)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
virtual ~active_tile_data ()
Public Attributes
int stored
int max_stored
Additional Inherited Members
Static Public Member Functions inherited from active_tile_data
static active_tile_data * create (const std::string &id)
Detailed Description
Definition at line 20 of file active_tile_data_def.h.
Member Function Documentation
clone()
active_tile_data * battery_tile::clone () const override virtual
Implements active_tile_data.
Definition at line 170 of file active_tile_data.cpp.
{
    return new battery_tile( *this );
}
get_resource()
int battery_tile::get_resource () const
Definition at line 192 of file active_tile_data.cpp.
{
    return stored;
}
References stored.
Referenced by iexamine::check_power(), and distribution_grid::get_resource().
get_type()
const std::string & battery_tile::get_type () const override virtual
Implements active_tile_data.
Definition at line 175 of file active_tile_data.cpp.
{
    static const std::string type( "battery" );
    return type;
}
References type.
load()
void battery_tile::load (JsonObject & jo) override virtual
Implements active_tile_data.
Definition at line 186 of file active_tile_data.cpp.
{
    jo.read( "stored", stored );
    jo.read( "max_stored", max_stored );
}
References max_stored, JsonObject::read(), and stored.
mod_resource()
int battery_tile::mod_resource (int amt)
Definition at line 197 of file active_tile_data.cpp.
{
    // TODO: Avoid int64 math if possible
    std::int64_t sum = static_cast<std::int64_t>( stored ) + amt;
    if( sum >= max_stored ) {
        stored = max_stored;
        return sum - max_stored;
    } else if( sum <= 0 ) {
        stored = 0;
        return sum - stored;
    } else {
        stored = sum;
        return 0;
    }
}
References max_stored, and stored.
Referenced by distribution_grid::mod_resource().
store()
void battery_tile::store (JsonOut & jsout) const override virtual
Implements active_tile_data.
Definition at line 181 of file active_tile_data.cpp.
{
    jsout.member( "stored", stored );
    jsout.member( "max_stored", max_stored );
}
References max_stored, JsonOut::member(), and stored.
update_internal()
void battery_tile::update_internal (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) override virtual
Parameters
to the time to update to
p absolute map coordinates (map::getabs) of the tile being updated
grid distribution grid being updated, containing the tile being updated
Implements active_tile_data.
Definition at line 165 of file active_tile_data.cpp.
{
    // TODO: Shouldn't have this function!
}
Member Data Documentation
max_stored
int battery_tile::max_stored
Definition at line 25 of file active_tile_data_def.h.
Referenced by load(), mod_resource(), and store().
stored
int battery_tile::stored
Definition at line 24 of file active_tile_data_def.h.
Referenced by get_resource(), load(), mod_resource(), and store().
The documentation for this class was generated from the following files:
src/active_tile_data_def.h
src/active_tile_data.cpp