Cataclysm BN: item::reload_option Class Reference
item::reload_option Class Reference
#include <item.h>
Public Member Functions
reload_option ()=default
reload_option (const reload_option &)
reload_option & operator= (const reload_option &)
reload_option (const player *who, const item *target, const item *parent, const item_location &ammo)
int qty () const
void qty (int val)
int moves () const
operator bool () const
Public Attributes
const player * who = nullptr
const item * target = nullptr
item_location ammo
Private Attributes
int qty_ = 0
int max_qty = INT_MAX
const item * parent = nullptr
Detailed Description
Definition at line 471 of file item.h.
Constructor & Destructor Documentation
reload_option() [1/3]
item::reload_option::reload_option () default
reload_option() [2/3]
item::reload_option::reload_option (const reload_option &) default
reload_option() [3/3]
item::reload_option::reload_option (const player * who, const item * target, const item * parent, const item_location & ammo)
Definition at line 7916 of file item.cpp.
                                                                :
    who( who ), target( target ), ammo( ammo ), parent( parent )
{
    if( this->target->is_ammo_belt() && this->target->type->magazine->linkage ) {
        max_qty = this->who->charges_of( * this->target->type->magazine->linkage );
    }
    qty( max_qty );
}
References visitable< T >::charges_of(), item::is_ammo_belt(), itype::magazine, max_qty, qty(), and item::type.
Member Function Documentation
moves()
int item::reload_option::moves () const
Definition at line 7926 of file item.cpp.
{
    int mv = ammo.obtain_cost( *who, qty() ) + who->item_reload_cost( *target, *ammo, qty() );
    if( parent != target ) {
        if( parent->is_gun() ) {
            mv += parent->get_reload_time();
        } else if( parent->is_tool() ) {
            mv += 100;
        }
    }
    return mv;
}
Referenced by vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), avatar_action::reload(), bandolier_actor::reload(), and ammobelt_actor::use().
operator bool()
item::reload_option::operator bool () const inline explicit
Definition at line 493 of file item.h.
{
                    return who && target && ammo && qty_ > 0;
                }
operator=()
item::reload_option & item::reload_option::operator= (const reload_option &) default
qty() [1/2]
int item::reload_option::qty () const inline
Definition at line 486 of file item.h.
{
                    return qty_;
                }
Referenced by vehicle::interact_with(), avatar_action::reload(), bandolier_actor::reload(), reload_option(), and ammobelt_actor::use().
qty() [2/2]
void item::reload_option::qty (int val)
Definition at line 7939 of file item.cpp.
{
    bool ammo_in_container = ammo->is_ammo_container();
    bool ammo_in_liquid_container = ammo->is_watertight_container();
    item &ammo_obj = ( ammo_in_container || ammo_in_liquid_container ) ?
                     ammo->contents.front() : *ammo;
    if( ( ammo_in_container && !ammo_obj.is_ammo() ) ||
        ( ammo_in_liquid_container && !ammo_obj.made_of( LIQUID ) ) ) {
        debugmsg( "Invalid reload option: %s", ammo_obj.tname() );
        return;
    }
    // Checking ammo capacity implicitly limits guns with removable magazines to capacity 0.
    // This gets rounded up to 1 later.
    int remaining_capacity = target->is_watertight_container() ?
                             target->get_remaining_capacity_for_liquid( ammo_obj, true ) :
                             target->ammo_capacity() - target->ammo_remaining();
    if( target->has_flag( flag_RELOAD_ONE ) && !ammo->has_flag( flag_SPEEDLOADER ) ) {
        remaining_capacity = 1;
    }
    if( ammo_obj.type->ammo ) {
        if( ammo_obj.ammo_type() == ammo_plutonium ) {
            remaining_capacity = remaining_capacity / PLUTONIUM_CHARGES +
                                 ( remaining_capacity % PLUTONIUM_CHARGES != 0 );
        }
    }
    bool ammo_by_charges = ammo_obj.is_ammo() || ammo_in_liquid_container;
    int available_ammo = ammo_by_charges ? ammo_obj.charges : ammo_obj.ammo_remaining();
    // constrain by available ammo, target capacity and other external factors (max_qty)
    // @ref max_qty is currently set when reloading ammo belts and limits to available linkages
    qty_ = std::min( { val, available_ammo, remaining_capacity, max_qty } );
    // always expect to reload at least one charge
    qty_ = std::max( qty_, 1 );
}
References itype::ammo, ammo_plutonium, item::ammo_remaining(), item::ammo_type(), item::charges, item::contents, debugmsg, flag_RELOAD_ONE(), flag_SPEEDLOADER(), item_contents::front(), item::is_ammo(), LIQUID, item::made_of(), PLUTONIUM_CHARGES, item::tname(), and item::type.
Member Data Documentation
ammo
item_location item::reload_option::ammo
Definition at line 484 of file item.h.
Referenced by npc::do_reload(), npc::find_reloadable(), npc::find_usable_ammo(), vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), ranged::prompt_select_default_ammo_for(), avatar_action::reload(), bandolier_actor::reload(), player::select_ammo(), and ammobelt_actor::use().
max_qty
int item::reload_option::max_qty = INT_MAX private
Definition at line 499 of file item.h.
Referenced by reload_option().
parent
const item* item::reload_option::parent = nullptr private
Definition at line 500 of file item.h.
qty_
int item::reload_option::qty_ = 0 private
Definition at line 498 of file item.h.
target
const item* item::reload_option::target = nullptr
Definition at line 483 of file item.h.
Referenced by npc::do_reload(), and avatar_action::reload().
who
const player* item::reload_option::who = nullptr
Definition at line 482 of file item.h.
The documentation for this class was generated from the following files:
src/item.h
src/item.cpp