Cataclysm BN: generic_typed_reader< Derived > Class Template Reference
generic_typed_reader< Derived > Class Template Reference
Base class for reading generic objects from JSON.
#include <generic_readers.h>
Public Member Functions
template<typename C >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
template<typename C >
void insert_next (JsonIn &jin, C &container) const
template<typename C >
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
template<typename C >
void erase_next (JsonIn &jin, C &container) const
template<typename C , typename std::enable_if< reader_detail::handler< C >::is_container, int >::type = 0>
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
template<typename C , typename std::enable_if< !reader_detail::handler< C >::is_container, int >::type = 0, std::enable_if_t< !supports_relative< C >::value > * = nullptr>
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
template<typename C , typename std::enable_if< !reader_detail::handler< C >::is_container, int >::type = 0, std::enable_if_t< supports_relative< C >::value > * = nullptr>
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
template<typename C >
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
template<typename C , typename std::enable_if< !reader_detail::handler< C >::is_container, int >::type = 0>
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
Detailed Description
template<typename Derived>
class generic_typed_reader< Derived >
Base class for reading generic objects from JSON.
It can load members being certain containers or being a single value. The function get_next() needs to be implemented to read and convert the data from JSON. It uses the curiously recurring template pattern, you have to derive your new class MyReader from generic_typed_reader<MyReader> and implement get_next and optionally erase_next. Most function calls here are done on a Derived, which means it can "override" them. This even allows changing their signature and return type.
If the object is new (was_loaded is false), only the given JSON member is read and assigned, overriding any existing content of it.
If the object is not new and the member exists, it is read and assigned as well.
If the object is not new and the member does not exists, two further members are examined: entries from "extend" are added to the set and entries from "delete" are removed. This only works if the member is actually a container, not just a single value.
Example: The JSON { "f": ["a","b","c"] } would be loaded as the set {"a","b","c"}. Loading the set again from the JSON { "delete": { "f": ["c","x"] }, "extend": { "f": ["h"] } } would add the "h" flag and removes the "c" and the "x" flag, resulting in {"a","b","h"}.
Template Parameters
Derived The class that inherits from this. It must implement the following:
Foo get_next(JsonIn &) const: reads the next value from JSON, converts it into some type Foo and returns it. The returned value is assigned to the loaded member (see reader interface above), or is inserted into the member (if it's a container). The type Foo must be compatible with those uses (read: it should be the same type).
(optional) erase_next(JsonIn &jin, C &container) const, the default implementation here reads a value from JSON via get_next and removes the matching value in the container. The value in the container must match exactly. You may override this function to allow a different matching algorithm, e.g. reading a simple id from JSON and remove entries with the same id from the container.
Definition at line 148 of file generic_readers.h.
Member Function Documentation
do_relative() [1/2]
template<typename Derived > template<typename C , typename std::enable_if< !reader_detail::handler< C >::is_container, int >::type = 0, std::enable_if_t< !supports_relative< C >::value > * = nullptr> bool generic_typed_reader< Derived >::do_relative (const JsonObject & jo, const std::string & name, C &) const inline
Definition at line 245 of file generic_readers.h.
{
            if( jo.has_object( "relative" ) ) {
                JsonObject relative = jo.get_object( "relative" );
                relative.allow_omitted_members();
                if( !relative.has_member( name ) ) {
                    return false;
                }
                debugmsg( "Member %s of type %s does not support relative", name, typeid( C ).name() );
            }
            return false;
        }
References debugmsg, JsonObject::get_object(), JsonObject::has_object(), and om_direction::name().
Referenced by generic_typed_reader< Derived >::operator()().
do_relative() [2/2]
template<typename Derived > template<typename C , typename std::enable_if< !reader_detail::handler< C >::is_container, int >::type = 0, std::enable_if_t< supports_relative< C >::value > * = nullptr> bool generic_typed_reader< Derived >::do_relative (const JsonObject & jo, const std::string & name, C & member) const inline
Definition at line 260 of file generic_readers.h.
{
            if( jo.has_object( "relative" ) ) {
                JsonObject relative = jo.get_object( "relative" );
                relative.allow_omitted_members();
                const Derived &derived = static_cast<const Derived &>( *this );
                // This needs to happen here, otherwise we get unvisited members
                if( !relative.has_member( name ) ) {
                    return false;
                }
                C adder = derived.get_next( *relative.get_raw( name ) );
                member += adder;
                return true;
            }
            return false;
        }
References JsonObject::get_object(), JsonObject::has_object(), mapgen_defer::member, and om_direction::name().
erase_next()
template<typename Derived > template<typename C > void generic_typed_reader< Derived >::erase_next (JsonIn & jin, C & container) const inline
Definition at line 194 of file generic_readers.h.
{
            const Derived &derived = static_cast<const Derived &>( *this );
            reader_detail::handler<C>().erase( container, derived.get_next( jin ) );
        }
erase_values_from()
template<typename Derived > template<typename C > void generic_typed_reader< Derived >::erase_values_from (const JsonObject & jo, const std::string & member_name, C & container) const inline
Definition at line 177 of file generic_readers.h.
{
            const Derived &derived = static_cast<const Derived &>( *this );
            if( !jo.has_member( member_name ) ) {
                return;
            }
            JsonIn &jin = *jo.get_raw( member_name );
            // Same as for inserting: either an array or a single value, same caveat applies.
            if( jin.test_array() ) {
                jin.start_array();
                while( !jin.end_array() ) {
                    derived.erase_next( jin, container );
                }
            } else {
                derived.erase_next( jin, container );
            }
        }
References JsonIn::end_array(), JsonObject::get_raw(), JsonObject::has_member(), JsonIn::start_array(), and JsonIn::test_array().
insert_next()
template<typename Derived > template<typename C > void generic_typed_reader< Derived >::insert_next (JsonIn & jin, C & container) const inline
Definition at line 171 of file generic_readers.h.
{
            const Derived &derived = static_cast<const Derived &>( *this );
            reader_detail::handler<C>().insert( container, derived.get_next( jin ) );
        }
insert_values_from()
template<typename Derived > template<typename C > void generic_typed_reader< Derived >::insert_values_from (const JsonObject & jo, const std::string & member_name, C & container) const inline
Definition at line 152 of file generic_readers.h.
{
            const Derived &derived = static_cast<const Derived &>( *this );
            if( !jo.has_member( member_name ) ) {
                return;
            }
            JsonIn &jin = *jo.get_raw( member_name );
            // We allow either a single value or an array of values. Note that this will not work
            // correctly if the thing we load from JSON is itself an array.
            if( jin.test_array() ) {
                jin.start_array();
                while( !jin.end_array() ) {
                    derived.insert_next( jin, container );
                }
            } else {
                derived.insert_next( jin, container );
            }
        }
References JsonIn::end_array(), JsonObject::get_raw(), JsonObject::has_member(), JsonIn::start_array(), and JsonIn::test_array().
operator()() [1/2]
template<typename Derived > template<typename C , typename std::enable_if< reader_detail::handler< C >::is_container, int >::type = 0> bool generic_typed_reader< Derived >::operator() (const JsonObject & jo, const std::string & member_name, C & container, bool was_loaded) const inline
Implements the reader interface, handles members that are containers of flags.
The functions forwards the actual changes to assign(), insert() and erase(), which are specialized for various container types. The enable_if is here to prevent the compiler from considering it when called on a simple data member, the other operator() will be used.
Definition at line 207 of file generic_readers.h.
{
            const Derived &derived = static_cast<const Derived &>( *this );
            // If you get an error about "incomplete type 'struct reader_detail::handler...",
            // you have to implement a specialization of your container type, so above for
            // existing specializations in namespace reader_detail.
            if( jo.has_member( member_name ) ) {
                reader_detail::handler<C>().clear( container );
                derived.insert_values_from( jo, member_name, container );
                return true;
            } else if( !was_loaded ) {
                return false;
            } else {
                if( jo.has_object( "extend" ) ) {
                    JsonObject tmp = jo.get_object( "extend" );
                    tmp.allow_omitted_members();
                    derived.insert_values_from( tmp, member_name, container );
                }
                if( jo.has_object( "delete" ) ) {
                    JsonObject tmp = jo.get_object( "delete" );
                    tmp.allow_omitted_members();
                    derived.erase_values_from( tmp, member_name, container );
                }
                return true;
            }
        }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), and JsonObject::has_object().
operator()() [2/2]
template<typename Derived > template<typename C , typename std::enable_if< !reader_detail::handler< C >::is_container, int >::type = 0> bool generic_typed_reader< Derived >::operator() (const JsonObject & jo, const std::string & member_name, C & member, bool) const inline
Implements the reader interface, handles a simple data member.
Definition at line 293 of file generic_readers.h.
{
            return read_normal( jo, member_name, member ) ||
                   handle_proportional( jo, member_name, member ) ||
                   do_relative( jo, member_name, member );
        }
References generic_typed_reader< Derived >::do_relative(), handle_proportional(), mapgen_defer::member, and generic_typed_reader< Derived >::read_normal().
read_normal()
template<typename Derived > template<typename C > bool generic_typed_reader< Derived >::read_normal (const JsonObject & jo, const std::string & name, C & member) const inline
Definition at line 277 of file generic_readers.h.
{
            if( jo.has_member( name ) ) {
                const Derived &derived = static_cast<const Derived &>( *this );
                member = derived.get_next( *jo.get_raw( name ) );
                return true;
            }
            return false;
        }
References JsonObject::get_raw(), JsonObject::has_member(), mapgen_defer::member, and om_direction::name().
Referenced by generic_typed_reader< Derived >::operator()().
The documentation for this class was generated from the following file:
src/generic_readers.h