Cataclysm BN: scrollingcombattext Class Reference
scrollingcombattext Class Reference
#include <output.h>
Classes
class cSCT
Public Types
enum : int { iMaxSteps = 8 }
Public Member Functions
scrollingcombattext ()=default
void add (const point &pos, direction p_oDir, const std::string &p_sText, game_message_type p_gmt, const std::string &p_sText2="", game_message_type p_gmt2=m_neutral, const std::string &p_sType="")
void advanceAllSteps ()
void removeCreatureHP ()
Public Attributes
std::vector< cSCT > vSCT
Detailed Description
Definition at line 893 of file output.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int
Enumerator
iMaxSteps
Definition at line 896 of file output.h.
: int { iMaxSteps = 8 };
Constructor & Destructor Documentation
scrollingcombattext()
scrollingcombattext::scrollingcombattext () default
Member Function Documentation
add()
void scrollingcombattext::add (const point & pos, direction p_oDir, const std::string & p_sText, game_message_type p_gmt, const std::string & p_sText2 = "", game_message_type p_gmt2 = m_neutral, const std::string & p_sType = "")
Definition at line 1757 of file output.cpp.
{
    // TODO: A non-hack
    if( test_mode ) {
        return;
    }
    if( get_option<bool>( "ANIMATION_SCT" ) ) {
        int iCurStep = 0;
        bool tiled = false;
        bool iso_mode = false;
#if defined(TILES)
        tiled = use_tiles;
        iso_mode = tile_iso && use_tiles;
#endif
        if( p_sType == "hp" ) {
            //Remove old HP bar
            removeCreatureHP();
            if( p_oDir == direction::WEST || p_oDir == direction::NORTHWEST ||
                p_oDir == ( iso_mode ? direction::NORTH : direction::SOUTHWEST ) ) {
                p_oDir = ( iso_mode ? direction::NORTHWEST : direction::WEST );
            } else {
                p_oDir = ( iso_mode ? direction::SOUTHEAST : direction::EAST );
            }
        } else {
            //reserve Left/Right for creature hp display
            if( p_oDir == ( iso_mode ? direction::SOUTHEAST : direction::EAST ) ) {
                p_oDir = ( one_in( 2 ) ) ? ( iso_mode ? direction::EAST : direction::NORTHEAST ) :
                         ( iso_mode ? direction::SOUTH : direction::SOUTHEAST );
            } else if( p_oDir == ( iso_mode ? direction::NORTHWEST : direction::WEST ) ) {
                p_oDir = ( one_in( 2 ) ) ? ( iso_mode ? direction::NORTH : direction::NORTHWEST ) :
                         ( iso_mode ? direction::WEST : direction::SOUTHWEST );
            }
        }
        // in tiles, SCT that scroll downwards are inserted at the beginning of the vector to prevent
        // oversize ASCII tiles overdrawing messages below them.
        if( tiled && ( p_oDir == direction::SOUTHWEST || p_oDir == direction::SOUTH ||
                       p_oDir == ( iso_mode ? direction::WEST : direction::SOUTHEAST ) ) ) {
            //Message offset: multiple impacts in the same direction in short order overriding prior messages (mostly turrets)
            for( auto &iter : vSCT ) {
                if( iter.getDirecton() == p_oDir && ( iter.getStep() + iter.getStepOffset() ) == iCurStep ) {
                    ++iCurStep;
                    iter.advanceStepOffset();
                }
            }
            vSCT.insert( vSCT.begin(), cSCT( pos, p_oDir, p_sText, p_gmt, p_sText2, p_gmt2,
                                             p_sType ) );
        } else {
            //Message offset: this time in reverse.
            for( std::vector<cSCT>::reverse_iterator iter = vSCT.rbegin(); iter != vSCT.rend(); ++iter ) {
                if( iter->getDirecton() == p_oDir && ( iter->getStep() + iter->getStepOffset() ) == iCurStep ) {
                    ++iCurStep;
                    iter->advanceStepOffset();
                }
            }
            vSCT.push_back( cSCT( pos, p_oDir, p_sText, p_gmt, p_sText2, p_gmt2, p_sType ) );
        }
    }
}
References EAST, NORTH, NORTHEAST, NORTHWEST, one_in(), removeCreatureHP(), SOUTH, SOUTHEAST, SOUTHWEST, test_mode, tile_iso, use_tiles, vSCT, and WEST.
Referenced by Character::absorb_hit(), Character::armor_absorb(), Character::deal_damage(), player_hit_message(), and ranged::print_dmg_msg().
advanceAllSteps()
void scrollingcombattext::advanceAllSteps ()
Definition at line 1924 of file output.cpp.
{
    std::vector<cSCT>::iterator iter = vSCT.begin();
    while( iter != vSCT.end() ) {
        if( iter->advanceStep() > this->iMaxSteps ) {
            iter = vSCT.erase( iter );
        } else {
            ++iter;
        }
    }
}
References vSCT.
Referenced by game::get_player_input().
removeCreatureHP()
void scrollingcombattext::removeCreatureHP ()
Definition at line 1937 of file output.cpp.
{
    //check for previous hp display and delete it
    for( std::vector<cSCT>::iterator iter = vSCT.begin(); iter != vSCT.end(); ++iter ) {
        if( iter->getType() == "hp" ) {
            vSCT.erase( iter );
            break;
        }
    }
}
References vSCT.
Referenced by add(), player_hit_message(), and ranged::print_dmg_msg().
Member Data Documentation
vSCT
std::vector<cSCT> scrollingcombattext::vSCT
Definition at line 959 of file output.h.
Referenced by add(), advanceAllSteps(), anonymous_namespace{animation.cpp}::draw_sct_curses(), game::get_player_input(), removeCreatureHP(), and game::setup().
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp