Cataclysm BN: inventory_entry Class Reference
inventory_entry Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_entry ()=default
inventory_entry (const item_category *custom_category)
inventory_entry (const inventory_entry &entry, const item_category *custom_category)
inventory_entry (const std::vector< item_location > &locations, const item_category *custom_category=nullptr, bool enabled=true)
bool operator== (const inventory_entry &other) const
bool operator!= (const inventory_entry &other) const
operator bool () const
bool is_null () const
Whether the entry is null (dummy)
bool is_item () const
Whether the entry is an item.
bool is_category () const
Whether the entry is a category.
bool is_selectable () const
Whether the entry can be selected.
const item_location & any_item () const
const item * item_stack_on_character () const
Pointer to first item in relevant stack on character.
size_t get_stack_size () const
int get_total_charges () const
int get_selected_charges () const
size_t get_available_count () const
const item_category * get_category_ptr () const
int get_invlet () const
nc_color get_invlet_color () const
void update_cache ()
Public Attributes
std::vector< item_location > locations
size_t chosen_count = 0
int custom_invlet = INT_MIN
std::string cached_name
Private Attributes
const item_category * custom_category = nullptr
bool enabled = true
Detailed Description
Definition at line 51 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_entry() [1/4]
inventory_entry::inventory_entry () default
inventory_entry() [2/4]
inventory_entry::inventory_entry (const item_category * custom_category) inline
Definition at line 62 of file inventory_ui.h.
                                                                :
            custom_category( custom_category )
        {}
inventory_entry() [3/4]
inventory_entry::inventory_entry (const inventory_entry & entry, const item_category * custom_category) inline
Definition at line 68 of file inventory_ui.h.
                                                                                              :
            inventory_entry( entry ) {
            this->custom_category = custom_category;
        }
References custom_category.
inventory_entry() [4/4]
inventory_entry::inventory_entry (const std::vector< item_location > & locations, const item_category * custom_category = nullptr, bool enabled = true) inline
Definition at line 73 of file inventory_ui.h.
                                               :
            locations( locations ),
            custom_category( custom_category ),
            enabled( enabled )
        {}
Member Function Documentation
any_item()
const item_location & inventory_entry::any_item () const inline
Definition at line 108 of file inventory_ui.h.
{
            assert( !locations.empty() );
            return locations.front();
        }
References locations.
Referenced by inventory_selector_preset::append_cell(), inventory_pick_selector::execute(), inventory_compare_selector::execute(), inventory_iuse_selector::execute(), inventory_drop_selector::execute(), get_available_count(), inventory_selector_preset::get_caption(), selection_column_preset::get_caption(), get_category_ptr(), inventory_selector_preset::get_color(), read_inventory_preset::get_color(), selection_column_preset::get_color(), inventory_selector_preset::get_denial(), get_invlet(), inventory_iuse_selector::set_chosen_count(), inventory_selector_preset::sort_compare(), comestible_inventory_preset::sort_compare(), gunmod_inventory_preset::sort_compare(), read_inventory_preset::sort_compare(), inventory_compare_selector::toggle_entry(), and update_cache().
get_available_count()
size_t inventory_entry::get_available_count () const
Definition at line 155 of file inventory_ui.cpp.
{
    if( locations.size() == 1 ) {
        return any_item()->count();
    } else {
        return locations.size();
    }
}
References any_item(), item::count(), and locations.
Referenced by selection_column_preset::get_caption(), inventory_iuse_selector::set_chosen_count(), and inventory_drop_selector::set_chosen_count().
get_category_ptr()
const item_category * inventory_entry::get_category_ptr () const
Definition at line 191 of file inventory_ui.cpp.
{
    if( custom_category != nullptr ) {
        return custom_category;
    }
    if( !is_item() ) {
        return nullptr;
    }
    return &any_item()->get_category();
}
References any_item(), custom_category, item::get_category(), and is_item().
Referenced by inventory_selector_preset::get_cell_text(), is_null(), inventory_column::is_selected_by_category(), and operator==().
get_invlet()
int inventory_entry::get_invlet () const
Definition at line 164 of file inventory_ui.cpp.
{
    if( custom_invlet != INT_MIN ) {
        return custom_invlet;
    }
    if( !is_item() ) {
        return '\0';
    }
    return any_item()->invlet;
}
References any_item(), custom_invlet, item::invlet, and is_item().
Referenced by get_invlet_color().
get_invlet_color()
nc_color inventory_entry::get_invlet_color () const
Definition at line 175 of file inventory_ui.cpp.
{
    if( !is_selectable() ) {
        return c_dark_gray;
    } else if( g->u.inv.assigned_invlet.count( get_invlet() ) ) {
        return c_yellow;
    } else {
        return c_white;
    }
}
References c_dark_gray, c_white, c_yellow, g, get_invlet(), and is_selectable().
get_selected_charges()
int inventory_entry::get_selected_charges () const
Definition at line 144 of file inventory_ui.cpp.
{
    assert( chosen_count <= locations.size() );
    int result = 0;
    for( size_t i = 0; i < chosen_count; ++i ) {
        const item_location &location = locations[i];
        result += location->charges;
    }
    return result;
}
References item::charges, chosen_count, and locations.
Referenced by selection_column_preset::get_caption().
get_stack_size()
size_t inventory_entry::get_stack_size () const inline
Definition at line 119 of file inventory_ui.h.
{
            return locations.size();
        }
References locations.
Referenced by inventory_selector_preset::get_caption(), and selection_column_preset::get_caption().
get_total_charges()
int inventory_entry::get_total_charges () const
Definition at line 135 of file inventory_ui.cpp.
{
    int result = 0;
    for( const item_location &location : locations ) {
        result += location->charges;
    }
    return result;
}
References locations.
Referenced by inventory_selector_preset::get_caption(), and selection_column_preset::get_caption().
is_category()
bool inventory_entry::is_category () const inline
Whether the entry is a category.
Definition at line 100 of file inventory_ui.h.
{
            return !is_null() && !is_item();
        }
References is_item(), and is_null().
is_item()
bool inventory_entry::is_item () const inline
Whether the entry is an item.
Definition at line 96 of file inventory_ui.h.
{
            return !locations.empty();
        }
References locations.
Referenced by inventory_column::expand_to_fit(), get_category_ptr(), inventory_selector_preset::get_cell_text(), inventory_selector_preset::get_color(), read_inventory_preset::get_color(), selection_column_preset::get_color(), inventory_selector_preset::get_denial(), inventory_column::get_entry_indent(), get_invlet(), is_category(), is_selectable(), inventory_column::is_selected_by_category(), and inventory_selector_preset::is_stub_cell().
is_null()
bool inventory_entry::is_null () const inline
Whether the entry is null (dummy)
Definition at line 90 of file inventory_ui.h.
{
            return get_category_ptr() == nullptr;
        }
References get_category_ptr().
Referenced by is_category(), operator bool(), and selection_column::prepare_paging().
is_selectable()
bool inventory_entry::is_selectable () const inline
Whether the entry can be selected.
Definition at line 104 of file inventory_ui.h.
{
            return is_item() && enabled;
        }
References enabled, and is_item().
Referenced by inventory_selector::get_input(), get_invlet_color(), and inventory_column::prepare_paging().
item_stack_on_character()
const item * inventory_entry::item_stack_on_character () const inline
Pointer to first item in relevant stack on character.
Definition at line 114 of file inventory_ui.h.
{
            assert( !locations.empty() );
            return locations.front().get_item();
        }
References locations.
Referenced by inventory_drop_selector::set_chosen_count().
operator bool()
inventory_entry::operator bool () const inline
Definition at line 86 of file inventory_ui.h.
{
            return !is_null();
        }
References is_null().
operator!=()
bool inventory_entry::operator!= (const inventory_entry & other) const inline
Definition at line 82 of file inventory_ui.h.
{
            return !( *this == other );
        }
References other.
operator==()
bool inventory_entry::operator== (const inventory_entry & other) const
Definition at line 85 of file inventory_ui.cpp.
{
    return get_category_ptr() == other.get_category_ptr() && locations == other.locations;
}
References get_category_ptr(), locations, and other.
update_cache()
void inventory_entry::update_cache ()
Definition at line 186 of file inventory_ui.cpp.
{
    cached_name = any_item()->tname( 1 );
}
References any_item(), cached_name, and item::tname().
Member Data Documentation
cached_name
std::string inventory_entry::cached_name
Definition at line 58 of file inventory_ui.h.
Referenced by inventory_selector_preset::sort_compare(), and update_cache().
chosen_count
size_t inventory_entry::chosen_count = 0
Definition at line 56 of file inventory_ui.h.
Referenced by inventory_iuse_selector::execute(), inventory_drop_selector::execute(), selection_column_preset::get_caption(), get_selected_charges(), selection_column::on_change(), inventory_iuse_selector::set_chosen_count(), inventory_drop_selector::set_chosen_count(), and inventory_compare_selector::toggle_entry().
custom_category
const item_category* inventory_entry::custom_category = nullptr private
Definition at line 133 of file inventory_ui.h.
Referenced by get_category_ptr(), and inventory_entry().
custom_invlet
int inventory_entry::custom_invlet = INT_MIN
Definition at line 57 of file inventory_ui.h.
Referenced by get_invlet().
enabled
bool inventory_entry::enabled = true private
Definition at line 134 of file inventory_ui.h.
Referenced by is_selectable().
locations
std::vector<item_location> inventory_entry::locations
Definition at line 54 of file inventory_ui.h.
Referenced by any_item(), get_available_count(), get_selected_charges(), get_stack_size(), get_total_charges(), is_item(), item_stack_on_character(), operator==(), and inventory_iuse_selector::set_chosen_count().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp