Cataclysm BN: JsonObject Class Reference
JsonObject Class Reference
#include <json.h>
Classes
class const_iterator
Public Member Functions
JsonObject (JsonIn &jsin)
JsonObject ()
JsonObject (const JsonObject &)=default
JsonObject (JsonObject &&)=default
JsonObject & operator= (const JsonObject &)=default
JsonObject & operator= (JsonObject &&)=default
~JsonObject ()
const_iterator begin () const
const_iterator end () const
void finish ()
size_t size () const
bool empty () const
void allow_omitted_members () const
bool has_member (const std::string &name) const
std::string str () const
void throw_error (std::string err) const
void throw_error (std::string err, const std::string &name) const
void show_warning (std::string err) const
void show_warning (std::string err, const std::string &name) const
JsonIn * get_raw (const std::string &name) const
JsonValue get_member (const std::string &name) const
json_source_location get_source_location () const
bool get_bool (const std::string &name) const
bool get_bool (const std::string &name, bool fallback) const
int get_int (const std::string &name) const
int get_int (const std::string &name, int fallback) const
double get_float (const std::string &name) const
double get_float (const std::string &name, double fallback) const
std::string get_string (const std::string &name) const
std::string get_string (const std::string &name, const std::string &fallback) const
template<typename E , typename = typename std::enable_if<std::is_enum<E>::value>::type>
E get_enum_value (const std::string &name, const E fallback) const
template<typename E , typename = typename std::enable_if<std::is_enum<E>::value>::type>
E get_enum_value (const std::string &name) const
JsonArray get_array (const std::string &name) const
std::vector< int > get_int_array (const std::string &name) const
std::vector< std::string > get_string_array (const std::string &name) const
JsonObject get_object (const std::string &name) const
template<typename T = std::string>
std::set< T > get_tags (const std::string &name) const
bool has_null (const std::string &name) const
bool has_bool (const std::string &name) const
bool has_number (const std::string &name) const
bool has_int (const std::string &name) const
bool has_float (const std::string &name) const
bool has_string (const std::string &name) const
bool has_array (const std::string &name) const
bool has_object (const std::string &name) const
template<typename T >
bool read (const std::string &name, T &t, bool throw_on_error=true) const
std::string line_number () const
Public Attributes
friend const_iterator
Private Member Functions
void mark_visited (const std::string &name) const
void report_unvisited () const
int verify_position (const std::string &name, bool throw_exception=true) const
Private Attributes
std::map< std::string, int > positions
int start
int end_
bool final_separator = false
std::set< std::string > visited_members
bool report_unvisited_members = true
bool reported_unvisited_members = false
JsonIn * jsin
Detailed Description
Definition at line 827 of file json.h.
Constructor & Destructor Documentation
JsonObject() [1/4]
JsonObject::JsonObject (JsonIn & jsin)
Definition at line 80 of file json.cpp.
{
    jsin = &j;
    start = jsin->tell();
    // cache the position of the value for each member
    jsin->start_object();
    while( !jsin->end_object() ) {
        std::string n = jsin->get_member_name();
        int p = jsin->tell();
        if( positions.count( n ) > 0 ) {
            j.error( "duplicate entry in json object" );
        }
        positions[n] = p;
        jsin->skip_value();
    }
    end_ = jsin->tell();
    final_separator = jsin->get_ate_separator();
}
References end_, JsonIn::end_object(), JsonIn::error(), final_separator, JsonIn::get_ate_separator(), JsonIn::get_member_name(), jsin, positions, JsonIn::skip_value(), start, JsonIn::start_object(), and JsonIn::tell().
JsonObject() [2/4]
JsonObject::JsonObject () inline
Definition at line 848 of file json.h.
: start(0), end_(0), jsin(nullptr) {}
Referenced by get_object().
JsonObject() [3/4]
JsonObject::JsonObject (const JsonObject &) default
JsonObject() [4/4]
JsonObject::JsonObject (JsonObject &&) default
~JsonObject()
JsonObject::~JsonObject () inline
Definition at line 853 of file json.h.
                      {
            finish();
        }
References finish().
Member Function Documentation
allow_omitted_members()
void JsonObject::allow_omitted_members () const
Definition at line 150 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    report_unvisited_members = false;
#endif
}
References report_unvisited_members.
Referenced by assign(), assign_map_from_array(), assign_unit_common(), wisheffect_state::deserialize(), item::craft_data::deserialize(), kill_tracker::deserialize(), event_multiset::deserialize(), stats_tracker::deserialize(), mongroup::deserialize(), basecamp::deserialize(), char_trait_data::deserialize(), zone_data::deserialize(), consumption_event::deserialize(), faction::deserialize(), item::deserialize(), item_contents::deserialize(), mission::deserialize(), monster::deserialize(), player_morale::morale_subtype::deserialize(), player_morale::morale_point::deserialize(), job_data::deserialize(), npc_personality::deserialize(), npc_opinion::deserialize(), npc_follower_rules::deserialize(), npc_chatbin::deserialize(), npc_favor::deserialize(), options_manager::deserialize(), player_activity::deserialize(), addiction::deserialize(), requirement_data::deserialize(), SkillLevel::deserialize(), vehicle_part::deserialize(), label::deserialize(), vehicle::deserialize(), avatar::deserialize(), deserialize(), generic_factory< T >::handle_inheritance(), handle_proportional(), Character::load(), monster::load(), mission_type::load(), mtype::load(), profession::load(), vpart_info::load(), recipe_dictionary::load(), Creature::load(), player_morale::load(), Item_factory::load(), Item_factory::load_basic_info(), Item_factory::load_definition(), load_ignored_type(), load_legacy_craft_data(), load_mapgen_function(), mod_management::load_modfile(), load_nested_mapgen(), jmapgen_objects::load_objects(), WORLD::load_options(), mapgen_palette::load_place_mapings(), load_update_mapgen(), generic_typed_reader< Derived >::operator()(), mission_util::set_update_mapgen(), and str().
begin()
JsonObject::const_iterator JsonObject::begin () const inline
Definition at line 1298 of file json.h.
{
    return const_iterator( *this, positions.begin() );
}
References const_iterator, and positions.
empty()
bool JsonObject::empty () const
Definition at line 145 of file json.cpp.
{
    return positions.empty();
}
References positions.
end()
JsonObject::const_iterator JsonObject::end () const inline
Definition at line 1303 of file json.h.
{
    return const_iterator( *this, positions.end() );
}
References const_iterator, and positions.
finish()
void JsonObject::finish ()
Definition at line 132 of file json.cpp.
{
    report_unvisited();
    if( jsin && jsin->good() ) {
        jsin->seek( end_ );
        jsin->set_ate_separator( final_separator );
    }
}
References end_, final_separator, JsonIn::good(), jsin, report_unvisited(), JsonIn::seek(), and JsonIn::set_ate_separator().
Referenced by DynamicDataLoader::load_all_from_json(), color_loader< ColorType >::load_colorfile(), and ~JsonObject().
get_array()
JsonArray JsonObject::get_array (const std::string & name) const
Definition at line 399 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return JsonArray();
    }
    mark_visited( name );
    jsin->seek( pos );
    return JsonArray( *jsin );
}
References jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
Referenced by add_array_to_set(), Item_factory::add_entry(), mutation_branch::add_entry(), mtype::add_regeneration_modifiers(), mtype::add_special_attacks(), apply_region_overlay(), assign(), assign_coverage_from_json(), conditional_t< T >::conditional_t(), Item_factory::delete_qualities_from_json(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), kill_tracker::deserialize(), basecamp::deserialize(), bionic::deserialize(), diary::deserialize(), known_magic::deserialize(), teleporter_list::deserialize(), map_bash_info::deserialize(), mission::deserialize(), panel_manager::deserialize(), vehicle_part::deserialize(), vehicle::deserialize(), dynamic_line_t::dynamic_line_t(), Item_factory::extend_qualities_from_json(), extract_effect(), faction_template::faction_template(), dynamic_line_t::from_member(), get_int_array(), get_string_array(), jmapgen_computer::jmapgen_computer(), jmapgen_int::jmapgen_int(), jmapgen_monster::jmapgen_monster(), jmapgen_npc::jmapgen_npc(), jmapgen_vehicle::jmapgen_vehicle(), json_talk_repeat_response::json_talk_repeat_response(), avatar::load(), Character::load(), monster::load(), player::load(), bonus_container::load(), json_talk_topic::load(), json_item_substitution::load(), relic::load(), vehicle_prototype::load(), VehicleGroup::load(), VehiclePlacement::load(), VehicleSpawn::load(), disease_type::load(), spell_type::load(), ter_furn_transform::load(), scen_blacklist::load(), clothing_mod::load(), construction::load(), field_type::load(), generic_factory< T >::load(), map_data_common_t::load(), ma_technique::load(), martialart::load(), mtype::load(), mutation_branch::load(), npc_class::load(), profession::load(), recipe::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), quality::load(), start_location::load(), trap::load(), vpart_info::load(), weather_type::load(), harvest_list::load(), enchantment::load(), npc_template::load(), material_type::load(), iuse_transform::load(), consume_drug_iuse::load(), place_monster_iuse::load(), change_scent_iuse::load(), reveal_map_actor::load(), repair_item_actor::load(), heal_actor::load(), sew_advanced_actor::load(), Item_factory::load(), Item_factory::load_basic_info(), color_loader< ColorType >::load_colors(), load_damage_instance_inherit(), effect_type::load_decay_msgs(), load_distribution(), talk_effect_t::load_effect(), vpart_info::load_engine(), fault::load_fault(), mission_util::load_funcs(), melee_actor::load_internal(), gun_actor::load_internal(), Item_factory::load_item_group(), load_mapgen(), effect_type::load_miss_msgs(), load_mutation_attack(), jmapgen_objects::load_objects(), overmap::load_obsolete_terrains(), load_overlay_ordering_into_array(), load_overmap_feature_flag_settings(), load_overmap_lake_settings(), load_overmap_terrain_mapgens(), load_recipe_category(), load_region_overlay(), load_region_settings(), requirement_data::load_requirement(), load_season_array(), Skill::load_skill(), snippet_library::load_snippet(), Item_factory::load_string(), Item_factory::load_sub_ref(), mutation_branch::load_trait_blacklist(), mutation_branch::load_trait_group(), load_transform_results(), vitamin::load_vitamin(), load_weighted_entries(), load_world_option(), MonsterGroupManager::LoadMonsterGroup(), talk_effect_t::parse_sub_effect(), parse_vp_reqs(), talk_effect_fun_t::set_mapgen_update(), Item_factory::set_properties_from_json(), Item_factory::set_qualities_from_json(), Item_factory::set_use_methods_from_json(), mapgen_function_json_base::setup_common(), mapgen_function_json_nested::setup_internal(), talk_trial::talk_trial(), json_item_substitution::trait_requirements::trait_requirements(), game::unserialize(), and VehicleFacings::VehicleFacings().
get_bool() [1/2]
bool JsonObject::get_bool (const std::string & name) const
Definition at line 333 of file json.cpp.
{
    return get_member( name ).get_bool();
}
References JsonValue::get_bool(), get_member(), and om_direction::name().
Referenced by conditional_t< T >::conditional_t(), item::craft_data::deserialize(), auto_pickup::rule::deserialize(), bionic::deserialize(), distraction_manager::distraction_manager_gui::deserialize(), effect::deserialize(), mission::deserialize(), safemode::deserialize(), vehicle::deserialize(), dynamic_line_t::dynamic_line_t(), faction_template::faction_template(), jmapgen_computer::jmapgen_computer(), monster::load(), json_talk_topic::load(), ter_furn_data< T >::load(), mtype::load(), recipe::load(), trap::load(), mutation_category_trait::load(), map_deconstruct_info::load(), pry_result::load(), firestarter_actor::load(), cast_spell_actor::load(), heal_actor::load(), mutagen_actor::load(), Item_factory::load(), json_talk_response::load_condition(), load_effect_data(), load_explosion_data(), load_external_option(), leap_actor::load_internal(), gun_actor::load_internal(), load_mapgen_function(), load_mon_effect_data(), load_recipe_category(), faction_template::load_relations(), MonsterGroupManager::LoadMonsterGroup(), mission_util::parse_mission_om_target(), and talk_effect_t::parse_sub_effect().
get_bool() [2/2]
bool JsonObject::get_bool (const std::string & name, bool fallback) const
Definition at line 338 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return fallback;
    }
    mark_visited( name );
    jsin->seek( pos );
    return jsin->get_bool();
}
References JsonIn::get_bool(), jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
get_enum_value() [1/2]
template<typename E , typename = typename std::enable_if<std::is_enum<E>::value>::type> E JsonObject::get_enum_value (const std::string & name) const inline
Definition at line 902 of file json.h.
{
            mark_visited( name );
            jsin->seek( verify_position( name ) );
            return jsin->get_enum_value<E>();
        }
References JsonIn::get_enum_value(), jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
get_enum_value() [2/2]
template<typename E , typename = typename std::enable_if<std::is_enum<E>::value>::type> E JsonObject::get_enum_value (const std::string & name, const E fallback) const inline
Definition at line 893 of file json.h.
{
            if( !has_member( name ) ) {
                return fallback;
            }
            mark_visited( name );
            jsin->seek( verify_position( name ) );
            return jsin->get_enum_value<E>();
        }
References JsonIn::get_enum_value(), has_member(), jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
Referenced by computer_option::deserialize(), computer_failure::deserialize(), distraction_manager::distraction_manager_gui::deserialize(), computer_option::from_json(), computer_failure::from_json(), body_part_type::load(), field_type::load(), map_extra::load(), mission_type::load(), start_location::load(), reveal_map_actor::load(), Item_factory::load(), Item_factory::load_basic_info(), vitamin::load_vitamin(), and mission_util::parse_mission_om_target().
get_float() [1/2]
double JsonObject::get_float (const std::string & name) const
Definition at line 365 of file json.cpp.
{
    return get_member( name ).get_float();
}
References JsonValue::get_float(), get_member(), and om_direction::name().
Referenced by mtype::add_regeneration_modifier(), assign(), bionic::deserialize(), effect_scaling::effect_scaling(), json_item_substitution::substitution::info::info(), weather_generator::load(), trap::load(), repair_item_actor::load(), heal_actor::load(), Item_factory::load(), load_damage_array(), load_damage_unit(), load_distribution(), load_explosion_data(), load_external_option(), leap_actor::load_internal(), and melee_actor::load_internal().
get_float() [2/2]
double JsonObject::get_float (const std::string & name, double fallback) const
Definition at line 370 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return fallback;
    }
    mark_visited( name );
    jsin->seek( pos );
    return jsin->get_float();
}
References JsonIn::get_float(), jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
get_int() [1/2]
int JsonObject::get_int (const std::string & name) const
Definition at line 349 of file json.cpp.
{
    return get_member( name ).get_int();
}
References JsonValue::get_int(), get_member(), and om_direction::name().
Referenced by Item_factory::add_entry(), mutation_branch::add_entry(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), uistatedata::deserialize(), blueprint_options::deserialize(), item::craft_data::deserialize(), computer_option::deserialize(), bionic::deserialize(), effect::deserialize(), help::deserialize(), mission::deserialize(), npc_favor::deserialize(), addiction::deserialize(), safemode::deserialize(), vehicle_part::deserialize(), extended_photo_def::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), cone_factory::deserialize(), extract_mod(), computer_option::from_json(), ma_skill_reader::get_next(), ma_weapon_damage_reader::get_next(), skilllevel_reader::get_next(), addiction_reader::get_next(), jmapgen_computer::jmapgen_computer(), jmapgen_int::jmapgen_int(), jmapgen_vehicle::jmapgen_vehicle(), Character::load(), monster::load(), relic::load(), vehicle_prototype::load(), weather_generator::load(), mission_type::load(), mtype::load(), recipe::load(), trap::load(), vpart_info::load(), mutation_category_trait::load(), npc_template::load(), pry_result::load(), delayed_transform_iuse::load(), pick_lock_actor::load(), reveal_map_actor::load(), firestarter_actor::load(), fireweapon_off_actor::load(), fireweapon_on_actor::load(), manualnoise_actor::load(), musical_instrument_actor::load(), cast_spell_actor::load(), holster_actor::load(), bandolier_actor::load(), repair_item_actor::load(), heal_actor::load(), quality_requirement::load(), Item_factory::load(), projectile::load(), load_effect_data(), load_explosion_data(), load_external_option(), leap_actor::load_internal(), melee_actor::load_internal(), bite_actor::load_internal(), Item_factory::load_item_group(), load_mapgen_function(), load_mon_effect_data(), load_nested_mapgen(), Skill::load_skill(), load_speech(), vitamin::load_vitamin(), MonsterGroupManager::LoadMonsterGroup(), mission_util::parse_mission_om_target(), talk_effect_t::parse_sub_effect(), parse_vp_reqs(), talk_effect_fun_t::set_add_effect(), talk_effect_fun_t::set_adjust_var(), conditional_t< T >::set_compare_var(), conditional_t< T >::set_days_since(), conditional_t< T >::set_has_dexterity(), conditional_t< T >::set_has_intelligence(), conditional_t< T >::set_has_item_category(), conditional_t< T >::set_has_items(), conditional_t< T >::set_has_perception(), conditional_t< T >::set_has_skill(), conditional_t< T >::set_has_strength(), conditional_t< T >::set_need(), conditional_t< T >::set_npc_allies(), conditional_t< T >::set_u_are_owed(), conditional_t< T >::set_u_has_ecash(), talk_trial::talk_trial(), game::unserialize(), and VehicleFacings::VehicleFacings().
get_int() [2/2]
int JsonObject::get_int (const std::string & name, int fallback) const
Definition at line 354 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return fallback;
    }
    mark_visited( name );
    jsin->seek( pos );
    return jsin->get_int();
}
References JsonIn::get_int(), jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
get_int_array()
std::vector< int > JsonObject::get_int_array (const std::string & name) const
Definition at line 410 of file json.cpp.
{
    std::vector<int> ret;
    for( const int entry : get_array( name ) ) {
        ret.push_back( entry );
    }
    return ret;
}
References get_array(), om_direction::name(), and cata::hash64_detail::ret.
Referenced by faction::deserialize(), and player_activity::deserialize().
get_member()
JsonValue JsonObject::get_member (const std::string & name) const
Definition at line 2147 of file json.cpp.
{
    const auto iter = positions.find( name );
    if( !jsin || iter == positions.end() ) {
        throw_error( "missing required field \"" + name + "\" in object: " + str() );
    }
    mark_visited( name );
    return JsonValue( *jsin, iter->second );
}
References jsin, mark_visited(), om_direction::name(), positions, str(), and throw_error().
Referenced by map_bash_info::deserialize(), get_bool(), get_float(), get_int(), get_string(), jmapgen_item_group::jmapgen_item_group(), weather_generator::load(), construction::load(), json_flag::load(), mtype::load(), npc_class::load(), profession::load(), vpart_info::load(), map_deconstruct_info::load(), pry_result::load(), mapgen_palette::load_place_mapings(), and load_season_array().
get_object()
JsonObject JsonObject::get_object (const std::string & name) const
Definition at line 428 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return JsonObject();
    }
    mark_visited( name );
    jsin->seek( pos );
    return jsin->get_object();
}
References JsonIn::get_object(), jsin, JsonObject(), mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
Referenced by snippet_library::add_snippets_from_json(), apply_region_overlay(), assign(), assign_map_from_array(), assign_unit_common(), conditional_t< T >::conditional_t(), uistatedata::deserialize(), Messages::deserialize(), kill_tracker::deserialize(), generic_typed_reader< Derived >::do_relative(), dynamic_line_t::from_member(), handle_proportional(), handle_relative(), jmapgen_sealed_item::jmapgen_sealed_item(), json_talk_repeat_response::json_talk_repeat_response(), Character::load(), monster::load(), json_talk_topic::load(), json_item_substitution::load(), vehicle_prototype::load(), spell_type::load(), ammo_effect::load(), field_type::load(), anonymous_namespace{gates.cpp}::gate_data::load(), map_extra::load(), mission_type::load(), mtype::load(), mutation_branch::load(), npc_class::load(), profession::load(), recipe::load(), start_location::load(), trap::load(), vpart_info::load(), weather_type::load(), enchantment::load(), mut_transform::load(), map_deconstruct_info::load(), pry_result::load(), explosion_iuse::load(), reveal_map_actor::load(), heal_actor::load(), place_trap_actor::load(), Item_factory::load(), Item_factory::load_basic_info(), load_distribution(), talk_effect_t::load_effect(), load_explosion_data(), fault::load_fault(), load_forest_biome(), load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), load_forest_mapgen_settings(), load_forest_trail_settings(), mission_util::load_funcs(), mapgen_palette::load_internal(), Item_factory::load_item_group(), load_mapgen_function(), effect_type::load_mod_data(), load_monster_adjustment(), load_mutation_attack(), load_mutation_mods(), load_nested_mapgen(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), mapgen_palette::load_place_mapings(), load_place_mapings_alternatively(), load_region_settings(), load_region_terrain_and_furniture_settings(), faction_template::load_relations(), Skill::load_skill(), Item_factory::load_slot_optional(), mutation_branch::load_trait_group(), load_update_mapgen(), vpart_info::load_workbench(), generic_typed_reader< Derived >::operator()(), read_condition(), conditional_t< T >::set_has_items(), conditional_t< T >::set_has_skill(), Item_factory::set_use_methods_from_json(), talk_effect_t::talk_effect_t(), talk_response::talk_response(), and game::unserialize().
get_raw()
JsonIn * JsonObject::get_raw (const std::string & name) const
Definition at line 308 of file json.cpp.
{
    int pos = verify_position( name );
    mark_visited( name );
    jsin->seek( pos );
    return jsin;
}
References jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
Referenced by assign_map_from_array(), deserialize(), translation::deserialize(), generic_typed_reader< Derived >::erase_values_from(), generic_typed_reader< Derived >::insert_values_from(), avatar::load(), Character::load(), monster::load(), npc::load(), mtype::load(), profession::load(), recipe::load(), vpart_info::load(), furn_t::load(), Item_factory::load(), talk_effect_t::load_effect(), load_effect_data(), load_optional_enum_array(), vitamin::load_vitamin(), unit_reader< T >::operator()(), parse_vp_reqs(), generic_typed_reader< Derived >::read_normal(), and read_with_factor().
get_source_location()
json_source_location JsonObject::get_source_location () const
Definition at line 316 of file json.cpp.
{
    if( !jsin ) {
        throw JsonError( "JsonObject::get_source_location called when stream is null" );
    }
    json_source_location loc;
    loc.path = jsin->get_path();
    if( !loc.path ) {
        jsin->seek( start );
        jsin->error( "JsonObject::get_source_location called but the path is unknown" );
    }
    loc.offset = start;
    return loc;
}
References JsonIn::error(), JsonIn::get_path(), jsin, json_source_location::offset, json_source_location::path, JsonIn::seek(), and start.
Referenced by generic_factory< T >::handle_inheritance(), relic_recharge::load(), mission_type::load(), vpart_info::load(), recipe_dictionary::load(), Item_factory::load_definition(), load_mapgen_function(), load_nested_mapgen(), and load_update_mapgen().
get_string() [1/2]
std::string JsonObject::get_string (const std::string & name) const
Definition at line 381 of file json.cpp.
{
    return get_member( name ).get_string();
}
References get_member(), JsonValue::get_string(), and om_direction::name().
Referenced by Item_factory::add_entry(), mutation_branch::add_entry(), add_mapgen_update_func(), mtype::add_regeneration_modifier(), assign(), assign_coverage_from_json(), assign_function(), conditional_t< T >::conditional_t(), MonsterGenerator::create_actor(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), overmap_special_connection::deserialize(), blueprint_options::deserialize(), item::craft_data::deserialize(), computer_option::deserialize(), item_location::deserialize(), auto_pickup::rule::deserialize(), bionic::deserialize(), color_manager::deserialize(), effect::deserialize(), help::deserialize(), mission::deserialize(), player_morale::morale_subtype::deserialize(), player_morale::morale_point::deserialize(), npc_favor::deserialize(), options_manager::deserialize(), panel_manager::deserialize(), safemode::deserialize(), translation::deserialize(), extended_photo_def::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), dynamic_line_t::dynamic_line_t(), effect_scaling::effect_scaling(), ma_weapon_damage_reader::erase_next(), faction_template::faction_template(), dynamic_line_t::from_member(), ma_skill_reader::get_next(), ma_weapon_damage_reader::get_next(), ma_buff_reader::get_next(), skilllevel_reader::get_next(), addiction_reader::get_next(), get_talk_varname(), generic_factory< T >::handle_inheritance(), jmapgen_faction::jmapgen_faction(), jmapgen_gaspump::jmapgen_gaspump(), jmapgen_loot::jmapgen_loot(), jmapgen_make_rubble::jmapgen_make_rubble(), jmapgen_monster::jmapgen_monster(), jmapgen_npc::jmapgen_npc(), jmapgen_translate::jmapgen_translate(), jmapgen_trap::jmapgen_trap(), jmapgen_zone::jmapgen_zone(), json_dynamic_line_effect::json_dynamic_line_effect(), json_talk_repeat_response::json_talk_repeat_response(), monster::load(), activity_type::load(), json_talk_topic::load(), ter_furn_data< T >::load(), json_item_substitution::load(), vehicle_prototype::load(), VehicleGroup::load(), VehiclePlacement::load(), VehicleSpawn::load(), scen_blacklist::load(), behavior::node_t::load(), construction::load(), field_type::load(), generic_factory< T >::load(), map_extra::load(), map_data_common_t::load(), mattack_actor::load(), mission_type::load(), mtype::load(), oter_type_t::load(), overmap_special::load(), profession::load(), recipe::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), scenario::load(), start_location::load(), trap::load(), vpart_info::load(), ter_t::load(), harvest_list::load(), recipe_dictionary::load(), enchantment::load(), mutation_category_trait::load(), npc_template::load(), SkillDisplayType::load(), map_deconstruct_info::load(), pry_result::load(), explosion_iuse::load(), unfold_vehicle_iuse::load(), consume_drug_iuse::load(), delayed_transform_iuse::load(), place_monster_iuse::load(), change_scent_iuse::load(), place_npc_iuse::load(), deploy_furn_actor::load(), reveal_map_actor::load(), fireweapon_off_actor::load(), fireweapon_on_actor::load(), manualnoise_actor::load(), cast_spell_actor::load(), holster_actor::load(), ammobelt_actor::load(), repair_item_actor::load(), mutagen_actor::load(), mutagen_iv_actor::load(), sew_advanced_actor::load(), quality_requirement::load(), Item_factory::load(), Name::load(), ammunition_type::load_ammunition_type(), Item_factory::load_basic_info(), color_loader< ColorType >::load_colorfile(), load_damage_unit(), talk_effect_t::load_effect(), load_effect_data(), emit::load_emit(), load_external_option(), mission_util::load_funcs(), load_inline_topic(), mapgen_palette::load_internal(), item_action_generator::load_item_action(), Item_factory::load_item_group(), item_group::load_item_group(), worldfactory::load_last_world_info(), load_mapgen(), load_mapgen_function(), mod_management::load_modfile(), load_mon_effect_data(), load_monster_adjustment(), monfactions::load_monster_faction(), load_mutation_attack(), load_mutation_type(), load_nested_mapgen(), DynamicDataLoader::load_object(), WORLD::load_options(), load_recipe_category(), requirement_data::load_requirement(), load_season_array(), Skill::load_skill(), snippet_library::load_snippet(), Item_factory::load_sub_ref(), map_data_common_t::load_symbol(), load_talk_topic(), mutation_branch::load_trait_group(), trait_group::load_trait_group(), load_transform_results(), load_update_mapgen(), vitamin::load_vitamin(), vpart_info::load_wheel(), MonsterGroupManager::LoadMonsterGroup(), MonsterGroupManager::LoadMonsterWhitelist(), mission_util::parse_mission_om_target(), talk_effect_t::parse_sub_effect(), parse_vp_reqs(), read_condition(), talk_effect_fun_t::set_add_effect(), talk_effect_fun_t::set_add_trait(), talk_effect_fun_t::set_add_var(), conditional_t< T >::set_at_om_location(), conditional_t< T >::set_compare_var(), conditional_t< T >::set_has_bionics(), conditional_t< T >::set_has_effect(), conditional_t< T >::set_has_item(), conditional_t< T >::set_has_item_category(), conditional_t< T >::set_has_items(), conditional_t< T >::set_has_skill(), conditional_t< T >::set_has_trait(), conditional_t< T >::set_has_trait_flag(), conditional_t< T >::set_has_var(), conditional_t< T >::set_is_season(), conditional_t< T >::set_is_wearing(), talk_effect_fun_t::set_mapgen_update(), conditional_t< T >::set_mission_goal(), conditional_t< T >::set_need(), conditional_t< T >::set_npc_aim_rule(), conditional_t< T >::set_npc_cbm_recharge_rule(), conditional_t< T >::set_npc_cbm_reserve_rule(), conditional_t< T >::set_npc_engagement_rule(), conditional_t< T >::set_npc_has_class(), conditional_t< T >::set_npc_override(), conditional_t< T >::set_npc_role_nearby(), conditional_t< T >::set_npc_rule(), talk_effect_fun_t::set_remove_effect(), talk_effect_fun_t::set_remove_item_with(), talk_effect_fun_t::set_remove_trait(), conditional_t< T >::set_u_has_mission(), conditional_t< T >::set_u_know_recipe(), mission_util::set_update_mapgen(), Item_factory::set_use_methods_from_json(), mapgen_function_json::setup_internal(), talk_effect_t::talk_effect_t(), talk_response::talk_response(), talk_trial::talk_trial(), Item_factory::usage_from_object(), and VehicleFunction_json::VehicleFunction_json().
get_string() [2/2]
std::string JsonObject::get_string (const std::string & name, const std::string & fallback) const
Definition at line 386 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return fallback;
    }
    mark_visited( name );
    jsin->seek( pos );
    return jsin->get_string();
}
References JsonIn::get_string(), jsin, mark_visited(), om_direction::name(), JsonIn::seek(), and verify_position().
get_string_array()
std::vector< std::string > JsonObject::get_string_array (const std::string & name) const
Definition at line 419 of file json.cpp.
{
    std::vector<std::string> ret;
    for( const std::string entry : get_array( name ) ) {
        ret.push_back( entry );
    }
    return ret;
}
References get_array(), om_direction::name(), and cata::hash64_detail::ret.
Referenced by player_activity::deserialize(), vpart_info::load(), musical_instrument_actor::load(), learn_spell_actor::load(), holster_actor::load(), Item_factory::load(), mapgen_palette::load_internal(), load_overmap_lake_settings(), load_talk_topic(), and conditional_t< T >::set_has_any_trait().
get_tags()
template<typename T > std::set< T > JsonObject::get_tags (const std::string & name) const
Definition at line 1330 of file json.h.
{
    std::set<T> res;
    int pos = verify_position( name, false );
    if( !pos ) {
        return res;
    }
    mark_visited( name );
    jsin->seek( pos );
    // allow single string as tag
    if( jsin->test_string() ) {
        res.insert( T( jsin->get_string() ) );
        return res;
    }
    // otherwise assume it's an array and error if it isn't.
    for( const std::string line : jsin->get_array() ) {
        res.insert( T( line ) );
    }
    return res;
}
References JsonIn::get_array(), JsonIn::get_string(), jsin, line(), mark_visited(), om_direction::name(), JsonIn::seek(), JsonIn::test_string(), and verify_position().
Referenced by assign(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), charge_removal_blacklist::load(), to_cbc_migration::load(), mission_type::load(), recipe::load(), bandolier_actor::load(), heal_actor::load(), Item_factory::load(), Item_factory::load_basic_info(), monfactions::load_monster_faction(), Skill::load_skill(), load_speech(), jmapgen_nested::neighborhood_check::neighborhood_check(), mtype::remove_regeneration_modifiers(), and mtype::remove_special_attacks().
has_array()
bool JsonObject::has_array (const std::string & name) const
Definition at line 482 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return false;
    }
    jsin->seek( pos );
    return jsin->test_array();
}
References jsin, om_direction::name(), JsonIn::seek(), JsonIn::test_array(), and verify_position().
Referenced by mtype::add_regeneration_modifiers(), mtype::add_special_attacks(), apply_region_overlay(), assign(), assign_coverage_from_json(), assign_map_from_array(), conditional_t< T >::conditional_t(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), bionic::deserialize(), faction::deserialize(), item::deserialize(), map_bash_info::deserialize(), dynamic_line_t::dynamic_line_t(), dynamic_line_t::from_member(), jmapgen_computer::jmapgen_computer(), jmapgen_int::jmapgen_int(), jmapgen_monster::jmapgen_monster(), jmapgen_npc::jmapgen_npc(), jmapgen_vehicle::jmapgen_vehicle(), json_talk_repeat_response::json_talk_repeat_response(), avatar::load(), Character::load(), monster::load(), json_talk_topic::load(), relic::load(), vehicle_prototype::load(), spell_type::load(), behavior::node_t::load(), construction::load(), generic_factory< T >::load(), map_data_common_t::load(), mtype::load(), mutation_branch::load(), npc_class::load(), oter_type_t::load(), profession::load(), recipe::load(), trap::load(), enchantment::load(), npc_template::load(), material_type::load(), iuse_transform::load(), consume_drug_iuse::load(), place_monster_iuse::load(), change_scent_iuse::load(), salvage_actor::load(), inscribe_actor::load(), heal_actor::load(), Item_factory::load(), Item_factory::load_basic_info(), load_damage_instance_inherit(), effect_type::load_decay_msgs(), load_distribution(), talk_effect_t::load_effect(), Creature::load_hit_range(), mapgen_palette::load_internal(), melee_actor::load_internal(), gun_actor::load_internal(), load_mapgen(), Item_factory::load_migration(), effect_type::load_miss_msgs(), load_mutation_attack(), load_optional_enum_array(), load_overmap_feature_flag_settings(), load_overmap_lake_settings(), load_overmap_terrain_mapgens(), load_region_overlay(), load_region_settings(), load_season_array(), snippet_library::load_snippet(), Item_factory::load_string(), Item_factory::load_sub_ref(), load_talk_topic(), MonsterGroupManager::LoadMonsterGroup(), talk_effect_t::parse_sub_effect(), parse_vp_reqs(), talk_effect_fun_t::set_mapgen_update(), Item_factory::set_properties_from_json(), Item_factory::set_qualities_from_json(), Item_factory::set_use_methods_from_json(), mapgen_function_json_base::setup_common(), mapgen_function_json_nested::setup_internal(), and VehicleFacings::VehicleFacings().
has_bool()
bool JsonObject::has_bool (const std::string & name) const
Definition at line 452 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return false;
    }
    jsin->seek( pos );
    return jsin->test_bool();
}
References jsin, om_direction::name(), JsonIn::seek(), JsonIn::test_bool(), and verify_position().
Referenced by dynamic_line_t::dynamic_line_t(), json_talk_repeat_response::json_talk_repeat_response(), mtype::load(), and recipe::load().
has_float()
bool JsonObject::has_float (const std::string & name) const inline
Definition at line 929 of file json.h.
{
            return has_number( name );
        }
References has_number(), and om_direction::name().
Referenced by bionic::deserialize(), load_damage_unit_inherit(), and load_distribution().
has_int()
bool JsonObject::has_int (const std::string & name) const inline
Definition at line 926 of file json.h.
{
            return has_number( name );
        }
References has_number(), and om_direction::name().
Referenced by conditional_t< T >::conditional_t(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), blueprint_options::deserialize(), bionic::deserialize(), mission::deserialize(), npc_chatbin::deserialize(), npc_favor::deserialize(), vehicle_part::deserialize(), monster::load(), mtype::load(), recipe::load(), vpart_info::load(), npc_template::load(), Item_factory::load(), load_explosion_data(), talk_effect_t::parse_sub_effect(), parse_vp_reqs(), conditional_t< T >::set_has_item_category(), conditional_t< T >::set_has_items(), conditional_t< T >::set_has_skill(), and conditional_t< T >::set_need().
has_member()
bool JsonObject::has_member (const std::string & name) const
Definition at line 181 of file json.cpp.
{
    return positions.count( name ) > 0;
}
References om_direction::name(), and positions.
Referenced by Item_factory::add_entry(), mutation_branch::add_entry(), add_if_exists(), snippet_library::add_snippet_from_json(), assign(), assign_map_from_array(), assign_unit_common(), conditional_t< T >::conditional_t(), deserialize(), overmap_special_connection::deserialize(), Messages::deserialize(), zone_data::deserialize(), map_bash_info::deserialize(), npc_follower_rules::deserialize(), player_activity::deserialize(), safemode::deserialize(), translation::deserialize(), dynamic_line_t::dynamic_line_t(), generic_typed_reader< Derived >::erase_values_from(), extract_effect(), get_enum_value(), handle_proportional(), generic_typed_reader< Derived >::insert_values_from(), jmapgen_int::jmapgen_int(), avatar::load(), Character::load(), npc::load(), json_talk_topic::load(), event_source::load(), json_item_substitution::load(), vehicle_prototype::load(), ter_furn_transform::load(), ammo_effect::load(), construction::load(), field_type::load(), anonymous_namespace{gates.cpp}::gate_data::load(), generic_factory< T >::load(), map_extra::load(), map_data_common_t::load(), ma_technique::load(), mission_type::load(), mtype::load(), npc_class::load(), oter_type_t::load(), profession::load(), recipe::load(), vpart_info::load(), weather_type::load(), ter_t::load(), furn_t::load(), pry_result::load(), iuse_transform::load(), explosion_iuse::load(), Item_factory::load(), Item_factory::load_basic_info(), load_distribution(), talk_effect_t::load_effect(), load_external_option(), mission_util::load_funcs(), mapgen_palette::load_internal(), Item_factory::load_item_group(), load_legacy_craft_data(), load_monster_adjustment(), jmapgen_objects::load_objects(), load_optional_enum_array(), mapgen_palette::load_place_mapings(), load_season_array(), Item_factory::load_slot_optional(), Item_factory::load_string(), Item_factory::load_sub_ref(), map_data_common_t::load_symbol(), mutation_branch::load_trait_group(), vpart_info::load_wheel(), mandatory(), generic_typed_reader< Derived >::operator()(), unit_reader< T >::operator()(), mission_util::parse_mission_om_target(), talk_effect_t::parse_sub_effect(), io::detail::has_archive_tag< T, typename enable_if_type< typename T::archive_type_tag >::type >::read(), read_condition(), generic_typed_reader< Derived >::read_normal(), mission_util::set_update_mapgen(), Item_factory::set_use_methods_from_json(), mapgen_function_json::setup_internal(), mapgen_function_json_nested::setup_internal(), talk_response::talk_response(), and talk_trial::talk_trial().
has_null()
bool JsonObject::has_null (const std::string & name) const
Definition at line 441 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return false;
    }
    mark_visited( name );
    jsin->seek( pos );
    return jsin->test_null();
}
References jsin, mark_visited(), om_direction::name(), JsonIn::seek(), JsonIn::test_null(), and verify_position().
Referenced by assign().
has_number()
bool JsonObject::has_number (const std::string & name) const
Definition at line 462 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return false;
    }
    jsin->seek( pos );
    return jsin->test_number();
}
References jsin, om_direction::name(), JsonIn::seek(), JsonIn::test_number(), and verify_position().
Referenced by has_float(), has_int(), npc::load(), and oter_type_t::load().
has_object()
bool JsonObject::has_object (const std::string & name) const
Definition at line 492 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return false;
    }
    jsin->seek( pos );
    return jsin->test_object();
}
References jsin, om_direction::name(), JsonIn::seek(), JsonIn::test_object(), and verify_position().
Referenced by assign(), conditional_t< T >::conditional_t(), vehicle_part::deserialize(), generic_typed_reader< Derived >::do_relative(), dynamic_line_t::from_member(), handle_proportional(), handle_relative(), jmapgen_sealed_item::jmapgen_sealed_item(), json_talk_repeat_response::json_talk_repeat_response(), monster::load(), json_talk_topic::load(), field_type::load(), map_extra::load(), mtype::load(), mutation_branch::load(), npc_class::load(), profession::load(), trap::load(), enchantment::load(), Creature::load(), map_deconstruct_info::load(), pry_result::load(), explosion_iuse::load(), heal_actor::load(), Item_factory::load_basic_info(), load_distribution(), talk_effect_t::load_effect(), load_explosion_data(), load_forest_biome(), load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), load_forest_mapgen_settings(), load_forest_trail_settings(), mission_util::load_funcs(), mapgen_palette::load_internal(), melee_actor::load_internal(), effect_type::load_mod_data(), load_mutation_attack(), load_mutation_mods(), load_nested_mapgen(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), mapgen_palette::load_place_mapings(), load_region_settings(), load_region_terrain_and_furniture_settings(), Skill::load_skill(), load_update_mapgen(), generic_typed_reader< Derived >::operator()(), read_condition(), Item_factory::set_use_methods_from_json(), talk_effect_t::talk_effect_t(), talk_response::talk_response(), and game::unserialize().
has_string()
bool JsonObject::has_string (const std::string & name) const
Definition at line 472 of file json.cpp.
{
    int pos = verify_position( name, false );
    if( !pos ) {
        return false;
    }
    jsin->seek( pos );
    return jsin->test_string();
}
References jsin, om_direction::name(), JsonIn::seek(), JsonIn::test_string(), and verify_position().
Referenced by add_mapgen_update_func(), assign(), assign_coverage_from_json(), assign_function(), conditional_t< T >::conditional_t(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), overmap_special_connection::deserialize(), bionic::deserialize(), distraction_manager::distraction_manager_gui::deserialize(), mission::deserialize(), player_morale::morale_point::deserialize(), npc_favor::deserialize(), translation::deserialize(), dynamic_line_t::dynamic_line_t(), effect_scaling::effect_scaling(), faction_template::faction_template(), dynamic_line_t::from_member(), get_talk_varname(), generic_factory< T >::handle_inheritance(), jmapgen_faction::jmapgen_faction(), jmapgen_gaspump::jmapgen_gaspump(), jmapgen_make_rubble::jmapgen_make_rubble(), jmapgen_monster::jmapgen_monster(), jmapgen_npc::jmapgen_npc(), jmapgen_translate::jmapgen_translate(), jmapgen_zone::jmapgen_zone(), json_dynamic_line_effect::json_dynamic_line_effect(), json_talk_repeat_response::json_talk_repeat_response(), npc::load(), json_talk_topic::load(), fake_spell::load(), json_item_substitution::load(), vehicle_prototype::load(), behavior::node_t::load(), construction::load(), generic_factory< T >::load(), mattack_actor::load(), mission_type::load(), mtype::load(), oter_type_t::load(), profession::load(), recipe::load(), scenario::load(), vpart_info::load(), harvest_list::load(), recipe_dictionary::load(), npc_template::load(), SkillDisplayType::load(), heal_actor::load(), Item_factory::load(), Item_factory::load_basic_info(), load_damage_instance_inherit(), Item_factory::load_definition(), talk_effect_t::load_effect(), load_effect_data(), mission_util::load_funcs(), load_mapgen(), Item_factory::load_migration(), mod_management::load_modfile(), load_mutation_attack(), requirement_data::load_requirement(), load_season_array(), Skill::load_skill(), Item_factory::load_sub_ref(), load_transform_results(), vitamin::load_vitamin(), vpart_info::load_wheel(), MonsterGroupManager::LoadMonsterGroup(), MonsterGroupManager::LoadMonsterWhitelist(), talk_effect_t::parse_sub_effect(), parse_vp_reqs(), read_condition(), read_with_factor(), talk_effect_fun_t::set_add_effect(), conditional_t< T >::set_has_items(), conditional_t< T >::set_has_skill(), talk_effect_fun_t::set_mapgen_update(), conditional_t< T >::set_need(), Item_factory::set_use_methods_from_json(), mapgen_function_json::setup_internal(), talk_effect_t::talk_effect_t(), talk_response::talk_response(), and VehicleFunction_json::VehicleFunction_json().
line_number()
std::string JsonObject::line_number () const
Definition at line 186 of file json.cpp.
{
    jsin->seek( start );
    return jsin->line_number();
}
References jsin, JsonIn::line_number(), JsonIn::seek(), and start.
mark_visited()
void JsonObject::mark_visited (const std::string & name) const private
Definition at line 99 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    visited_members.emplace( name );
#else
    static_cast<void>( name );
#endif
}
References om_direction::name(), and visited_members.
Referenced by get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_member(), get_object(), get_raw(), get_string(), get_tags(), has_null(), JsonObject::const_iterator::operator*(), and read().
operator=() [1/2]
JsonObject & JsonObject::operator= (const JsonObject &) default
operator=() [2/2]
JsonObject & JsonObject::operator= (JsonObject &&) default
read()
template<typename T > bool JsonObject::read (const std::string & name, T & t, bool throw_on_error = true) const inline
Definition at line 942 of file json.h.
{
            int pos = verify_position( name, false );
            if( !pos ) {
                return false;
            }
            mark_visited( name );
            jsin->seek( pos );
            return jsin->read( t, throw_on_error );
        }
References jsin, mark_visited(), om_direction::name(), JsonIn::read(), JsonIn::seek(), and verify_position().
Referenced by snippet_library::add_snippet_from_json(), apply_region_overlay(), assign(), assign_unit_common(), deserialize(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), overmap_special_spawns::deserialize(), debug_menu_state::deserialize(), uistatedata::deserialize(), advanced_inv_pane_save_state::deserialize(), advanced_inv_save_state::deserialize(), plot_options::deserialize(), blueprint_options::deserialize(), loot_options::deserialize(), item::craft_data::deserialize(), achievement::time_bound::deserialize(), achievement_state::deserialize(), achievements_tracker::deserialize(), event_multiset::deserialize(), stats_tracker::deserialize(), achievement_requirement::deserialize(), computer::deserialize(), pickup::pick_drop_selection::deserialize(), active_tile_data::deserialize(), active_tiles::furn_transform::deserialize(), aim_activity_actor::deserialize(), dig_activity_actor::deserialize(), dig_channel_activity_actor::deserialize(), disassemble_activity_actor::deserialize(), drop_activity_actor::deserialize(), hacking_activity_actor::deserialize(), move_items_activity_actor::deserialize(), toggle_gate_activity_actor::deserialize(), pickup_activity_actor::deserialize(), stash_activity_actor::deserialize(), throw_activity_actor::deserialize(), wash_activity_actor::deserialize(), basecamp::deserialize(), bionic::deserialize(), bodypart::deserialize(), char_trait_data::deserialize(), character_martial_arts::deserialize(), zone_data::deserialize(), consumption_event::deserialize(), comp_selection< CompType >::deserialize(), diary::deserialize(), item_drop_token::deserialize(), drop_token_provider::deserialize(), effect::deserialize(), value_constraint::deserialize(), faction::deserialize(), help::deserialize(), item::deserialize(), item_contents::deserialize(), known_magic::deserialize(), mission::deserialize(), player_morale::morale_subtype::deserialize(), player_morale::morale_point::deserialize(), job_data::deserialize(), npc_personality::deserialize(), npc_opinion::deserialize(), npc_follower_rules::deserialize(), npc_chatbin::deserialize(), npc_favor::deserialize(), player_activity::deserialize(), addiction::deserialize(), requirement_data::deserialize(), SkillLevel::deserialize(), vehicle_part::deserialize(), label::deserialize(), vehicle::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), cone_factory::deserialize(), stomach_contents::deserialize(), faction_template::faction_template(), computer_option::from_json(), json_item_substitution::substitution::info::info(), jmapgen_computer::jmapgen_computer(), jmapgen_make_rubble::jmapgen_make_rubble(), legacy_volume_reader(), avatar::load(), Character::load(), monster::load(), npc::load(), player::load(), event_source::load(), dreams::load(), relic_recharge::load(), relic::load(), weather_generator::load(), field_type::load(), mtype::load(), oter_type_t::load(), recipe::load(), trap::load(), vpart_info::load(), harvest_list::load(), enchantment::load(), Creature::load(), player_morale::load(), npc_template::load(), SkillDisplayType::load(), pry_result::load(), material_type::load(), iuse_transform::load(), unpack_actor::load(), countdown_actor::load(), explosion_iuse::load(), unfold_vehicle_iuse::load(), consume_drug_iuse::load(), set_transform_iuse::load(), set_transformed_iuse::load(), place_monster_iuse::load(), place_npc_iuse::load(), fireweapon_off_actor::load(), musical_instrument_actor::load(), heal_actor::load(), Item_factory::load(), projectile::load(), battery_tile::load(), charge_watcher_tile::load(), charger_tile::load(), solar_tile::load(), steady_consumer_tile::load(), vehicle_connector_tile::load(), ammunition_type::load_ammunition_type(), Item_factory::load_basic_info(), Item_factory::load_definition(), emit::load_emit(), load_explosion_data(), Creature::load_hit_range(), gun_actor::load_internal(), item_action_generator::load_item_action(), Item_factory::load_item_blacklist(), load_mat_burn_data(), Item_factory::load_migration(), load_monster_adjustment(), load_mutation_attack(), load_mutation_social_mods(), load_region_settings(), Skill::load_skill(), load_speech(), Item_factory::load_string(), map_data_common_t::load_symbol(), vitamin::load_vitamin(), mandatory(), maybe_temperature_reader(), one_char_symbol_reader(), optional(), talk_effect_t::parse_sub_effect(), io::detail::has_archive_tag< T, E >::read(), read_and_set_or_throw(), read_with_factor(), talk_effect_fun_t::set_consume_item(), talk_response::talk_response(), unicode_codepoint_from_symbol_reader(), game::unserialize(), and game::unserialize_master().
report_unvisited()
void JsonObject::report_unvisited () const private
Definition at line 108 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    if(
        json_report_strict
        && report_unvisited_members
        && !reported_unvisited_members
        && !std::uncaught_exceptions()
    ) {
        reported_unvisited_members = true;
        for( const std::pair<const std::string, int> &p : positions ) {
            const std::string &name = p.first;
            if( !visited_members.count( name ) && !string_starts_with( name, "//" ) ) {
                try {
                    throw_error( string_format( "Invalid or misplaced field name \"%s\" in JSON data", name ), name );
                } catch( const JsonError &e ) {
                    debugmsg( "(json-error)\n%s", e.what() );
                }
            }
        }
    }
#endif
}
References debugmsg, json_report_strict, om_direction::name(), positions, report_unvisited_members, reported_unvisited_members, string_format(), string_starts_with(), throw_error(), and visited_members.
Referenced by finish().
show_warning() [1/2]
void JsonObject::show_warning (std::string err) const
Definition at line 241 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    try {
        throw_error( err );
    } catch( const std::exception &e ) {
        debugmsg( "%s", e.what() );
    }
#else
    ( void )err;
#endif // CATA_IN_TOOL
}
References debugmsg, and throw_error().
show_warning() [2/2]
void JsonObject::show_warning (std::string err, const std::string & name) const
Definition at line 254 of file json.cpp.
{
#ifndef CATA_IN_TOOL
    try {
        throw_error( err, name );
    } catch( const std::exception &e ) {
        debugmsg( "%s", e.what() );
    }
#else
    ( void )err;
    ( void )name;
#endif // CATA_IN_TOOL
}
References debugmsg, om_direction::name(), and throw_error().
size()
size_t JsonObject::size () const
Definition at line 141 of file json.cpp.
{
    return positions.size();
}
References positions.
Referenced by new_field::deserialize().
str()
std::string JsonObject::str () const
Definition at line 192 of file json.cpp.
{
    // If we're getting the string form, we might be re-parsing later, so don't
    // complain about unvisited members.
    allow_omitted_members();
    if( jsin && end_ >= start ) {
        return jsin->substr( start, end_ - start );
    } else {
        return "{}";
    }
}
References allow_omitted_members(), end_, jsin, start, and JsonIn::substr().
Referenced by conditional_t< T >::conditional_t(), get_member(), get_talk_varname(), load_mapgen(), and talk_effect_t::parse_sub_effect().
throw_error() [1/2]
void JsonObject::throw_error (std::string err) const
Definition at line 233 of file json.cpp.
{
    if( !jsin ) {
        throw JsonError( err );
    }
    jsin->error( err );
}
References JsonIn::error(), and jsin.
Referenced by snippet_library::add_snippet_from_json(), apply_region_overlay(), assign(), assign_dmg_proportional(), assign_function(), assign_map_from_array(), assign_unit_common(), check_assigned_dmg(), common_check_bounds(), conditional_t< T >::conditional_t(), MonsterGenerator::create_actor(), it_artifact_tool::deserialize(), overmap_special_connection::deserialize(), achievement::time_bound::deserialize(), achievement_requirement::deserialize(), value_constraint::deserialize(), new_field::deserialize(), translation::deserialize(), vehicle_part::deserialize(), dynamic_line_t::dynamic_line_t(), ma_weapon_damage_reader::erase_next(), get_member(), ma_weapon_damage_reader::get_next(), get_talk_varname(), generic_factory< T >::handle_inheritance(), json_item_substitution::substitution::info::info(), io::JsonObjectInputArchive::io(), jmapgen_gaspump::jmapgen_gaspump(), jmapgen_graffiti::jmapgen_graffiti(), jmapgen_int::jmapgen_int(), jmapgen_loot::jmapgen_loot(), jmapgen_sign::jmapgen_sign(), json_talk_repeat_response::json_talk_repeat_response(), event_transformation::load(), event_statistic::load(), json_talk_topic::load(), event_source::load(), json_item_substitution::load(), weather_generator::load(), scen_blacklist::load(), behavior::node_t::load(), field_type::load(), generic_factory< T >::load(), map_data_common_t::load(), mapgen_palette::load(), mtype::load(), mutation_branch::load(), oter_type_t::load(), overmap_location::load(), recipe::load(), rotatable_symbols::load(), scenario::load(), trap::load(), harvest_list::load(), iuse_transform::load(), change_scent_iuse::load(), inscribe_actor::load(), musical_instrument_actor::load(), repair_item_actor::load(), sew_advanced_actor::load(), quality_requirement::load(), Item_factory::load(), Item_factory::load_basic_info(), load_damage_unit(), load_distribution(), talk_effect_t::load_effect(), load_effect_data(), load_external_option(), fault::load_fault(), load_forest_biome(), load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), load_forest_mapgen_settings(), load_forest_trail_settings(), mapgen_palette::load_internal(), gun_actor::load_internal(), Item_factory::load_item_group(), load_mapgen_function(), Item_factory::load_migration(), mod_management::load_modfile(), load_mon_effect_data(), load_mutation_attack(), DynamicDataLoader::load_object(), load_optional_enum_array(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_recipe_category(), load_region_overlay(), load_region_settings(), load_region_terrain_and_furniture_settings(), requirement_data::load_requirement(), load_season_array(), Item_factory::load_sub_ref(), map_data_common_t::load_symbol(), mutation_branch::load_trait_group(), vitamin::load_vitamin(), vpart_info::load_wheel(), load_world_option(), mandatory(), one_char_symbol_reader(), talk_effect_t::parse_string_effect(), talk_effect_t::parse_sub_effect(), read_and_set_or_throw(), read_condition(), report_strict_violation(), report_unvisited(), talk_effect_fun_t::set_add_effect(), Item_factory::set_properties_from_json(), Item_factory::set_qualities_from_json(), Item_factory::set_use_methods_from_json(), mapgen_function_json_base::setup_common(), mapgen_function_json::setup_internal(), mapgen_function_json_nested::setup_internal(), show_warning(), talk_response::talk_response(), talk_trial::talk_trial(), and unicode_codepoint_from_symbol_reader().
throw_error() [2/2]
void JsonObject::throw_error (std::string err, const std::string & name) const
Definition at line 205 of file json.cpp.
{
    if( !jsin ) {
        throw JsonError( err );
    }
    jsin->seek( verify_position( name, false ) );
    jsin->error( err );
}
References JsonIn::error(), jsin, om_direction::name(), JsonIn::seek(), and verify_position().
verify_position()
int JsonObject::verify_position (const std::string & name, bool throw_exception = true) const private
Definition at line 157 of file json.cpp.
{
    if( !jsin ) {
        if( throw_exception ) {
            throw JsonError( std::string( "member lookup on empty object: " ) + name );
        }
        // 0 is always the opening brace,
        // so it will never indicate a valid member position
        return 0;
    }
    const auto iter = positions.find( name );
    if( iter == positions.end() ) {
        if( throw_exception ) {
            jsin->seek( start );
            jsin->error( "member not found: " + name );
        }
        // 0 is always the opening brace,
        // so it will never indicate a valid member position
        return 0;
    }
    return iter->second;
}
References JsonIn::error(), jsin, om_direction::name(), positions, JsonIn::seek(), and start.
Referenced by get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_object(), get_raw(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), read(), and throw_error().
Member Data Documentation
const_iterator
friend JsonObject::const_iterator
Definition at line 859 of file json.h.
Referenced by begin(), and end().
end_
int JsonObject::end_ private
Definition at line 832 of file json.h.
Referenced by finish(), JsonObject(), and str().
final_separator
bool JsonObject::final_separator = false private
Definition at line 833 of file json.h.
Referenced by finish(), and JsonObject().
jsin
JsonIn* JsonObject::jsin private
Definition at line 842 of file json.h.
Referenced by finish(), get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_member(), get_object(), get_raw(), get_source_location(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), JsonObject(), line_number(), JsonObject::const_iterator::operator*(), read(), str(), throw_error(), and verify_position().
positions
std::map<std::string, int> JsonObject::positions private
Definition at line 830 of file json.h.
Referenced by begin(), empty(), end(), get_member(), has_member(), JsonObject(), report_unvisited(), size(), and verify_position().
report_unvisited_members
bool JsonObject::report_unvisited_members = true mutable private
Definition at line 836 of file json.h.
Referenced by allow_omitted_members(), and report_unvisited().
reported_unvisited_members
bool JsonObject::reported_unvisited_members = false mutable private
Definition at line 837 of file json.h.
Referenced by report_unvisited().
start
int JsonObject::start private
Definition at line 831 of file json.h.
Referenced by get_source_location(), JsonObject(), line_number(), str(), and verify_position().
visited_members
std::set<std::string> JsonObject::visited_members mutable private
Definition at line 835 of file json.h.
Referenced by mark_visited(), and report_unvisited().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp