Cataclysm BN: time_point Class Reference
time_point Class Reference
A point in the game time.
#include <calendar.h>
Public Member Functions
time_point ()
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Static Public Member Functions
static constexpr time_point from_turn (const int t)
Private Member Functions
constexpr time_point (const int t)
Private Attributes
int turn_
Friends
class time_duration
template<typename T >
constexpr friend T to_turn (const time_point &point)
constexpr friend bool operator< (const time_point &lhs, const time_point &rhs)
constexpr friend bool operator<= (const time_point &lhs, const time_point &rhs)
constexpr friend bool operator> (const time_point &lhs, const time_point &rhs)
constexpr friend bool operator>= (const time_point &lhs, const time_point &rhs)
constexpr friend bool operator== (const time_point &lhs, const time_point &rhs)
constexpr friend bool operator!= (const time_point &lhs, const time_point &rhs)
constexpr friend time_duration operator- (const time_point &lhs, const time_point &rhs)
constexpr friend time_point operator+ (const time_point &lhs, const time_duration &rhs)
time_point & operator+= (time_point &lhs, const time_duration &rhs)
constexpr friend time_point operator- (const time_point &lhs, const time_duration &rhs)
time_point & operator-= (time_point &lhs, const time_duration &rhs)
Detailed Description
A point in the game time.
Use calendar::turn to get the current point. Modify it by adding/subtracting time_duration. This can be compared with the usual comparison operators. It can be (de)serialized via JSON.
Note that is does not handle variable sized season length. Changing the season length has no effect on it.
Definition at line 430 of file calendar.h.
Constructor & Destructor Documentation
time_point() [1/2]
constexpr time_point::time_point (const int t) inline explicit constexpr private
Definition at line 436 of file calendar.h.
: turn_(t) { }
time_point() [2/2]
time_point::time_point ()
Definition at line 585 of file calendar.cpp.
{
    turn_ = 0;
}
References turn_.
Referenced by from_turn().
Member Function Documentation
deserialize()
void time_point::deserialize (JsonIn & jsin)
Definition at line 2027 of file savegame_json.cpp.
{
    turn_ = jsin.get_int();
}
References JsonIn::get_int().
from_turn()
static constexpr time_point time_point::from_turn (const int t) inline static constexpr
Definition at line 443 of file calendar.h.
{
            return time_point( t );
        }
References time_point().
Referenced by editmap::edit_itm(), and solar_tile::update_internal().
serialize()
void time_point::serialize (JsonOut & jsout) const
Definition at line 2022 of file savegame_json.cpp.
{
    jsout.write( turn_ );
}
References JsonOut::write().
Friends And Related Function Documentation
operator!=
constexpr friend bool operator!= (const time_point & lhs, const time_point & rhs) friend
Definition at line 471 of file calendar.h.
{
            return to_turn<int>( lhs ) != to_turn<int>( rhs );
        }
operator+
constexpr friend time_point operator+ (const time_point & lhs, const time_duration & rhs) friend
Definition at line 479 of file calendar.h.
{
            return time_point::from_turn( to_turn<int>( lhs ) + to_turns<int>( rhs ) );
        }
operator+=
time_point & operator+= (time_point & lhs, const time_duration & rhs) friend
Definition at line 483 of file calendar.h.
{
            return lhs = time_point::from_turn( to_turn<int>( lhs ) + to_turns<int>( rhs ) );
        }
operator- [1/2]
constexpr friend time_point operator- (const time_point & lhs, const time_duration & rhs) friend
Definition at line 486 of file calendar.h.
{
            return time_point::from_turn( to_turn<int>( lhs ) - to_turns<int>( rhs ) );
        }
operator- [2/2]
constexpr friend time_duration operator- (const time_point & lhs, const time_point & rhs) friend
Definition at line 475 of file calendar.h.
{
            return time_duration::from_turns( to_turn<int>( lhs ) - to_turn<int>( rhs ) );
        }
operator-=
time_point & operator-= (time_point & lhs, const time_duration & rhs) friend
Definition at line 490 of file calendar.h.
{
            return lhs = time_point::from_turn( to_turn<int>( lhs ) - to_turns<int>( rhs ) );
        }
operator<
constexpr friend bool operator< (const time_point & lhs, const time_point & rhs) friend
Definition at line 456 of file calendar.h.
{
            return to_turn<int>( lhs ) < to_turn<int>( rhs );
        }
operator<=
constexpr friend bool operator<= (const time_point & lhs, const time_point & rhs) friend
Definition at line 459 of file calendar.h.
{
            return to_turn<int>( lhs ) <= to_turn<int>( rhs );
        }
operator==
constexpr friend bool operator== (const time_point & lhs, const time_point & rhs) friend
Definition at line 468 of file calendar.h.
{
            return to_turn<int>( lhs ) == to_turn<int>( rhs );
        }
operator>
constexpr friend bool operator> (const time_point & lhs, const time_point & rhs) friend
Definition at line 462 of file calendar.h.
{
            return to_turn<int>( lhs ) > to_turn<int>( rhs );
        }
operator>=
constexpr friend bool operator>= (const time_point & lhs, const time_point & rhs) friend
Definition at line 465 of file calendar.h.
{
            return to_turn<int>( lhs ) >= to_turn<int>( rhs );
        }
time_duration
friend class time_duration friend
Definition at line 433 of file calendar.h.
to_turn
template<typename T > constexpr friend T to_turn (const time_point & point) friend
Definition at line 452 of file calendar.h.
{
            return point.turn_;
        }
Member Data Documentation
turn_
int time_point::turn_ private
Definition at line 434 of file calendar.h.
Referenced by time_point().
The documentation for this class was generated from the following files:
src/calendar.h
src/calendar.cpp
src/savegame_json.cpp