Cataclysm BN: dialogue_window Class Reference
dialogue_window Class Reference
#include <dialogue_win.h>
Public Member Functions
dialogue_window ()=default
void resize_dialogue (ui_adaptor &ui)
void print_header (const std::string &name)
void clear_window_texts ()
void handle_scrolling (int ch)
void display_responses (const std::vector< talk_data > &responses)
void refresh_response_display ()
void add_to_history (const std::string &msg)
Adds message to history.
Private Member Functions
void print_history ()
void cache_msg (const std::string &msg, size_t idx)
Folds given message to current window width and adds it to drawing cache.
Private Attributes
catacurses::window d_win
std::vector< std::string > history
This contains the exchanged words, it is basically like the global message log.
std::vector< std::pair< std::string, size_t > > draw_cache
Drawing cache: basically all entries from history, but folded to current window width and with separators between.
size_t curr_page = 0
Scroll position in response window (page number)
bool can_scroll_up = false
bool can_scroll_down = false
std::string npc_name
Detailed Description
Definition at line 22 of file dialogue_win.h.
Constructor & Destructor Documentation
dialogue_window()
dialogue_window::dialogue_window () default
Member Function Documentation
add_to_history()
void dialogue_window::add_to_history (const std::string & msg)
Adds message to history.
It must be already translated.
Definition at line 49 of file dialogue_win.cpp.
{
    size_t idx = history.size();
    history.push_back( msg );
    cache_msg( msg, idx );
}
References cache_msg(), and history.
Referenced by dialogue::opt().
cache_msg()
void dialogue_window::cache_msg (const std::string & msg, size_t idx) private
Folds given message to current window width and adds it to drawing cache.
Also adds a separator (empty line). idx is this message's position within history_raw
Definition at line 146 of file dialogue_win.cpp.
{
    const std::vector<std::string> folded = foldstring( msg, getmaxx( d_win ) / 2 );
    draw_cache.push_back( {"", idx} );
    for( const std::string &fs : folded ) {
        draw_cache.push_back( {fs, idx} );
    }
}
References d_win, draw_cache, foldstring(), and catacurses::getmaxx().
Referenced by add_to_history(), and resize_dialogue().
clear_window_texts()
void dialogue_window::clear_window_texts ()
Definition at line 43 of file dialogue_win.cpp.
{
    werase( d_win );
    print_header( npc_name );
}
References d_win, npc_name, print_header(), and catacurses::werase().
Referenced by display_responses().
display_responses()
void dialogue_window::display_responses (const std::vector< talk_data > & responses)
Definition at line 182 of file dialogue_win.cpp.
{
    const int win_maxy = getmaxy( d_win );
    clear_window_texts();
    print_history();
    // TODO: cache paged entries
    // -2 for borders, -2 for your name + newline, -4 for keybindings
    const int page_h = getmaxy( d_win ) - 2 - 2 - 4;
    const int page_w = getmaxx( d_win ) / 2 - 4; // -4 for borders + padding
    const std::vector<page> pages = split_to_pages( responses, page_w, page_h );
    if( !pages.empty() ) {
        if( curr_page >= pages.size() ) {
            curr_page = pages.size() - 1;
        }
        print_responses( d_win, pages[curr_page] );
    }
    print_keybindings( d_win );
    can_scroll_up = curr_page > 0;
    can_scroll_down = curr_page + 1 < pages.size();
    if( can_scroll_up ) {
        mvwprintz( d_win, point( getmaxx( d_win ) - 2 - 2, 2 ), c_green, "^^" );
    }
    if( can_scroll_down ) {
        mvwprintz( d_win, point( FULL_SCREEN_WIDTH - 2 - 2, win_maxy - 2 ), c_green, "vv" );
    }
    wnoutrefresh( d_win );
}
References c_green, can_scroll_down, can_scroll_up, clear_window_texts(), curr_page, d_win, FULL_SCREEN_WIDTH, catacurses::getmaxx(), catacurses::getmaxy(), mvwprintz(), print_history(), print_keybindings(), print_responses(), split_to_pages(), and catacurses::wnoutrefresh().
Referenced by dialogue::opt().
handle_scrolling()
void dialogue_window::handle_scrolling (int ch)
Definition at line 162 of file dialogue_win.cpp.
{
    switch( ch ) {
        case KEY_DOWN:
        case KEY_NPAGE:
            if( can_scroll_down ) {
                curr_page += 1;
            }
            break;
        case KEY_UP:
        case KEY_PPAGE:
            if( can_scroll_up ) {
                curr_page -= 1;
            }
            break;
        default:
            break;
    }
}
References can_scroll_down, can_scroll_up, curr_page, KEY_DOWN, KEY_NPAGE, KEY_PPAGE, and KEY_UP.
Referenced by dialogue::opt().
print_header()
void dialogue_window::print_header (const std::string & name)
Definition at line 29 of file dialogue_win.cpp.
{
    draw_border( d_win );
    int win_midx = getmaxx( d_win ) / 2;
    int winy = getmaxy( d_win );
    mvwvline( d_win, point( win_midx + 1, 1 ), LINE_XOXO, winy - 1 );
    mvwputch( d_win, point( win_midx + 1, 0 ), BORDER_COLOR, LINE_OXXX );
    mvwputch( d_win, point( win_midx + 1, winy - 1 ), BORDER_COLOR, LINE_XXOX );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( d_win, point( 1, 1 ), c_white, _( "Dialogue: %s" ), name );
    mvwprintz( d_win, point( win_midx + 3, 1 ), c_white, _( "Your response:" ) );
    npc_name = name;
}
References _, BORDER_COLOR, c_white, d_win, draw_border(), catacurses::getmaxx(), catacurses::getmaxy(), LINE_OXXX, LINE_XOXO, LINE_XXOX, mvwprintz(), mvwputch(), catacurses::mvwvline(), om_direction::name(), and npc_name.
Referenced by clear_window_texts(), and dialogue::opt().
print_history()
void dialogue_window::print_history () private
Definition at line 56 of file dialogue_win.cpp.
{
    if( history.empty() ) {
        return;
    }
    int curline = getmaxy( d_win ) - 2;
    int curindex = draw_cache.size() - 1;
    // Highligh last message
    size_t msg_to_highlight = history.size() - 1;
    // Print at line 2 and below, line 1 contains the header, line 0 the border
    while( curindex >= 0 && curline >= 2 ) {
        const std::pair<std::string, size_t> &msg = draw_cache[curindex];
        const nc_color col = ( msg.second == msg_to_highlight ) ? c_white : c_light_gray;
        mvwprintz( d_win, point( 1, curline ), col, draw_cache[curindex].first );
        curline--;
        curindex--;
    }
}
References c_light_gray, c_white, d_win, draw_cache, catacurses::getmaxy(), history, and mvwprintz().
Referenced by display_responses().
refresh_response_display()
void dialogue_window::refresh_response_display ()
Definition at line 155 of file dialogue_win.cpp.
{
    curr_page = 0;
    can_scroll_down = false;
    can_scroll_up = false;
}
References can_scroll_down, can_scroll_up, and curr_page.
Referenced by dialogue::opt().
resize_dialogue()
void dialogue_window::resize_dialogue (ui_adaptor & ui)
Definition at line 14 of file dialogue_win.cpp.
{
    int win_beginy = TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 4 : 0;
    int win_beginx = TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 4 : 0;
    int maxy = win_beginy ? TERMY - 2 * win_beginy : FULL_SCREEN_HEIGHT;
    int maxx = win_beginx ? TERMX - 2 * win_beginx : FULL_SCREEN_WIDTH;
    d_win = catacurses::newwin( maxy, maxx, point( win_beginx, win_beginy ) );
    ui.position_from_window( d_win );
    curr_page = 0;
    draw_cache.clear();
    for( size_t idx = 0; idx < history.size(); idx++ ) {
        cache_msg( history[idx], idx );
    }
}
References cache_msg(), curr_page, d_win, draw_cache, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, history, catacurses::newwin(), TERMX, and TERMY.
Referenced by dialogue::opt().
Member Data Documentation
can_scroll_down
bool dialogue_window::can_scroll_down = false private
Definition at line 52 of file dialogue_win.h.
Referenced by display_responses(), handle_scrolling(), and refresh_response_display().
can_scroll_up
bool dialogue_window::can_scroll_up = false private
Definition at line 51 of file dialogue_win.h.
Referenced by display_responses(), handle_scrolling(), and refresh_response_display().
curr_page
size_t dialogue_window::curr_page = 0 private
Scroll position in response window (page number)
Definition at line 50 of file dialogue_win.h.
Referenced by display_responses(), handle_scrolling(), refresh_response_display(), and resize_dialogue().
d_win
catacurses::window dialogue_window::d_win private
Definition at line 37 of file dialogue_win.h.
Referenced by cache_msg(), clear_window_texts(), display_responses(), print_header(), print_history(), and resize_dialogue().
draw_cache
std::vector<std::pair<std::string, size_t> > dialogue_window::draw_cache private
Drawing cache: basically all entries from history, but folded to current window width and with separators between.
Used for rendering, recalculated each time window size changes.
Definition at line 48 of file dialogue_win.h.
Referenced by cache_msg(), print_history(), and resize_dialogue().
history
std::vector<std::string> dialogue_window::history private
This contains the exchanged words, it is basically like the global message log.
Each responses of the player character and the NPC are added as are information about what each of them does (e.g. the npc drops their weapon).
Definition at line 43 of file dialogue_win.h.
Referenced by add_to_history(), print_history(), and resize_dialogue().
npc_name
std::string dialogue_window::npc_name private
Definition at line 64 of file dialogue_win.h.
Referenced by clear_window_texts(), and print_header().
The documentation for this class was generated from the following files:
src/dialogue_win.h
src/dialogue_win.cpp