Cataclysm BN: jmapgen_vending_machine Class Reference
jmapgen_vending_machine Class Reference
Place a vending machine with content.
Public Member Functions
jmapgen_vending_machine (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, point p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
bool reinforced
item_group_id item_group
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a vending machine with content.
"item_group": the item group that is used to generate the content of the vending machine.
Definition at line 1031 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_vending_machine()
jmapgen_vending_machine::jmapgen_vending_machine (const JsonObject & jsi) inline
Definition at line 1036 of file mapgen.cpp.
                                                         :
            reinforced( jsi.get_bool( "reinforced", false ) )
            , item_group( jsi.get_string( "item_group", "default_vending_machine" ) ) {
            if( !item_group::group_is_defined( item_group ) ) {
                set_mapgen_defer( jsi, "item_group", "no such item group" );
            }
        }
References item_group::group_is_defined(), mapgen_defer::jsi, and set_mapgen_defer().
Member Function Documentation
apply()
void jmapgen_vending_machine::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1043 of file mapgen.cpp.
{
            point r{ x.get(), y.get() };
            dat.m.furn_set( r, f_null );
            dat.m.place_vending( r, item_group, reinforced );
        }
References f_null, map::furn_set(), jmapgen_int::get(), mapgendata::m, map::place_vending(), and reinforced.
has_vehicle_collision()
bool jmapgen_vending_machine::has_vehicle_collision (mapgendata & dat, point p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1048 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
item_group
item_group_id jmapgen_vending_machine::item_group
Definition at line 1035 of file mapgen.cpp.
reinforced
bool jmapgen_vending_machine::reinforced
Definition at line 1034 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp