Cataclysm BN: list_circularizer< T > Class Template Reference
list_circularizer< T > Class Template Reference
Class used to access a list as if it were circular.
#include <cata_utility.h>
Public Member Functions
list_circularizer (std::vector< T > &_list)
Construct list_circularizer from an existing std::vector.
void next ()
Advance list to next item, wrapping back to 0 at end of list.
void prev ()
Advance list to previous item, wrapping back to end at zero.
T & cur () const
Return list element at the current location.
Private Attributes
unsigned int _index = 0
std::vector< T > * _list
Detailed Description
template<typename T>
class list_circularizer< T >
Class used to access a list as if it were circular.
Some times you just want to have a list loop around on itself. This wrapper class allows you to do that. It requires the list to exist separately, but that also means any changes to the list get propagated (both ways).
Definition at line 183 of file cata_utility.h.
Constructor & Destructor Documentation
list_circularizer()
template<typename T > list_circularizer< T >::list_circularizer (std::vector< T > & _list) inline
Construct list_circularizer from an existing std::vector.
Definition at line 190 of file cata_utility.h.
                                                 : _list( &_list ) {
        }
Member Function Documentation
cur()
template<typename T > T & list_circularizer< T >::cur () const inline
Return list element at the current location.
Definition at line 204 of file cata_utility.h.
                       {
            // list could be null, but it would be a design time mistake and really, the callers fault.
            return ( *_list )[_index];
        }
References list_circularizer< T >::_index, and list_circularizer< T >::_list.
Referenced by select_crafting_recipe().
next()
template<typename T > void list_circularizer< T >::next () inline
Advance list to next item, wrapping back to 0 at end of list.
Definition at line 194 of file cata_utility.h.
                    {
            _index = ( _index == _list->size() - 1 ? 0 : _index + 1 );
        }
References list_circularizer< T >::_index, and list_circularizer< T >::_list.
Referenced by select_crafting_recipe().
prev()
template<typename T > void list_circularizer< T >::prev () inline
Advance list to previous item, wrapping back to end at zero.
Definition at line 199 of file cata_utility.h.
                    {
            _index = ( _index == 0 ? _list->size() - 1 : _index - 1 );
        }
References list_circularizer< T >::_index, and list_circularizer< T >::_list.
Referenced by select_crafting_recipe().
Member Data Documentation
_index
template<typename T > unsigned int list_circularizer< T >::_index = 0 private
Definition at line 186 of file cata_utility.h.
Referenced by list_circularizer< T >::cur(), list_circularizer< T >::next(), and list_circularizer< T >::prev().
_list
template<typename T > std::vector<T>* list_circularizer< T >::_list private
Definition at line 187 of file cata_utility.h.
Referenced by list_circularizer< T >::cur(), list_circularizer< T >::next(), and list_circularizer< T >::prev().
The documentation for this class was generated from the following file:
src/cata_utility.h