Cataclysm BN: debug_menu::effect_select_callback Class Reference
debug_menu::effect_select_callback Class Reference
Public Member Functions
effect_select_callback (Creature &c)
bool key (const input_context &ctx, const input_event &key, int entnum, uilist *parent_menu) override
void refresh (uilist *menu) override
void change_body_part (const input_context &, const input_event &, int, uilist &)
void change_intensity (const input_context &, const input_event &, int, uilist &)
void change_duration (const input_context &, const input_event &, int, uilist &)
void toggle_force (const input_context &, const input_event &, int, uilist &)
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual ~uilist_callback ()=default
Static Public Member Functions
static const std::map< std::string, effect_select_fun > & get_handled_actions ()
Private Types
using effect_select_fun = void(effect_select_callback::*)(const input_context &, const input_event &, int, uilist &)
Private Attributes
const std::vector< efftype_id > all_effects = find_all_effect_types()
Creature & c
Static Private Attributes
static const std::map< std::string, effect_select_fun > handled_actions
Detailed Description
Definition at line 145 of file wisheffect.cpp.
Member Typedef Documentation
effect_select_fun
using debug_menu::effect_select_callback::effect_select_fun = void (effect_select_callback::*)(const input_context &, const input_event &, int, uilist &) private
Definition at line 148 of file wisheffect.cpp.
Constructor & Destructor Documentation
effect_select_callback()
debug_menu::effect_select_callback::effect_select_callback (Creature & c) inline
Definition at line 161 of file wisheffect.cpp.
            : c( c )
        {}
Member Function Documentation
change_body_part()
void debug_menu::effect_select_callback::change_body_part (const input_context & , const input_event & , int , uilist &) inline
Definition at line 224 of file wisheffect.cpp.
{
            query_body_part( c );
        }
References c, and debug_menu::anonymous_namespace{wisheffect.cpp}::query_body_part().
change_duration()
void debug_menu::effect_select_callback::change_duration (const input_context & , const input_event & , int , uilist &) inline
Definition at line 232 of file wisheffect.cpp.
{
            query_duration();
        }
References debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration().
change_intensity()
void debug_menu::effect_select_callback::change_intensity (const input_context & , const input_event & , int , uilist &) inline
Definition at line 228 of file wisheffect.cpp.
{
            query_intensity();
        }
References debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity().
get_handled_actions()
static const std::map< std::string, effect_select_fun > & debug_menu::effect_select_callback::get_handled_actions () inline static
Definition at line 165 of file wisheffect.cpp.
{
            return handled_actions;
        }
key()
bool debug_menu::effect_select_callback::key (const input_context & ctx, const input_event & key, int entnum, uilist * parent_menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 169 of file wisheffect.cpp.
{
            const std::string &action = ctx.input_to_action( key );
            auto iter = handled_actions.find( action );
            if( iter != handled_actions.end() ) {
                // This ugly thing is a call to method using a pointer-to-member-method
                ( ( *this ).*( iter->second ) )( ctx, key, entnum, *parent_menu );
                return true;
            }
            return false;
        }
References action, and input_context::input_to_action().
refresh()
void debug_menu::effect_select_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 182 of file wisheffect.cpp.
{
            wisheffect_state &last_val = uistate.debug_menu.effect;
            size_t selected = clamp<size_t>( menu->selected, 0, all_effects.size() - 1 );
            input_context ctxt( menu->input_category );
            const point start( menu->w_width - menu->pad_right, 3 );
            const int width = menu->w_width - start.x;
            std::stringstream ss;
            ss << string_format( "ID: %s\n", all_effects[selected].str() );
            const auto eff_type = all_effects[static_cast<size_t>( selected )];
            ss << string_format( "[%s] <bold>Body part</bold>: %s\n",
                                 ctxt.get_desc( "CHANGE_BODY_PART" ),
                                 last_val.bodypart
                                 ? last_val.bodypart->name.translated().c_str()
                                 : "Global" );
            time_duration dur = last_val.duration <= 0_seconds
                                ? eff_type->get_max_duration()
                                : last_val.duration;
            ss << string_format( "[%s] <bold>Duration</bold>: %10d (max: %d)\n",
                                 ctxt.get_desc( "CHANGE_DURATION" ),
                                 to_turns<int>( dur ),
                                 to_turns<int>( eff_type->get_max_duration() ) );
            ss << string_format( "[%s] <bold>Intensity</bold>: %d\n",
                                 ctxt.get_desc( "CHANGE_INTENSITY" ),
                                 std::max( last_val.intensity, 1 ) );
            ss << string_format( "[%s] <bold>Force</bold>: %s\n",
                                 ctxt.get_desc( "TOGGLE_FORCE" ),
                                 last_val.force
                                 ? "Yes"
                                 : "No" );
            ss << '\n';
            ss << string_format( "Permanent: %s\n", eff_type->is_permanent()
                                 ? "Yes"
                                 : "No" );
            fold_and_print_from( menu->window, start, width, 0, c_light_gray, replace_colors( ss.str() ) );
            wnoutrefresh( menu->window );
        }
References wisheffect_state::bodypart, c_light_gray, uistatedata::debug_menu, wisheffect_state::duration, debug_menu_state::effect, fold_and_print_from(), wisheffect_state::force, input_context::get_desc(), uilist::input_category, wisheffect_state::intensity, body_part_type::name, uilist::pad_right, replace_colors(), uilist::selected, string_format(), translation::translated(), uistate, uilist::w_width, uilist::window, catacurses::wnoutrefresh(), and point::x.
toggle_force()
void debug_menu::effect_select_callback::toggle_force (const input_context & , const input_event & , int , uilist &) inline
Definition at line 236 of file wisheffect.cpp.
{
            toggle_effect_force();
        }
References debug_menu::anonymous_namespace{wisheffect.cpp}::toggle_effect_force().
Member Data Documentation
all_effects
const std::vector<efftype_id> debug_menu::effect_select_callback::all_effects = find_all_effect_types() private
Definition at line 156 of file wisheffect.cpp.
c
Creature& debug_menu::effect_select_callback::c private
Definition at line 158 of file wisheffect.cpp.
handled_actions
const std::map< std::string, effect_select_callback::effect_select_fun > debug_menu::effect_select_callback::handled_actions static private
Initial value:
= {{
        { "CHANGE_BODY_PART", &effect_select_callback::change_body_part },
        { "CHANGE_INTENSITY", &effect_select_callback::change_intensity },
        { "CHANGE_DURATION", &effect_select_callback::change_duration },
        { "TOGGLE_FORCE", &effect_select_callback::toggle_force },
    }
}
Definition at line 153 of file wisheffect.cpp.
The documentation for this class was generated from the following file:
src/wisheffect.cpp