Cataclysm BN: activatable_inventory_preset Class Reference
activatable_inventory_preset Class Reference
Public Member Functions
activatable_inventory_preset (const player &p)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from pickup_inventory_preset
pickup_inventory_preset (const player &p)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Protected Member Functions
std::string get_action_name (const item &it) const
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const player & p
Additional Inherited Members
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Detailed Description
Definition at line 829 of file game_inventory.cpp.
Constructor & Destructor Documentation
activatable_inventory_preset()
activatable_inventory_preset::activatable_inventory_preset (const player & p) inline
Definition at line 832 of file game_inventory.cpp.
                                                        : pickup_inventory_preset( p ), p( p ) {
            if( get_option<bool>( "INV_USE_ACTION_NAMES" ) ) {
                append_cell( [ this ]( const item_location & loc ) {
                    const item &it = !( *loc ).is_container_empty() && ( *loc ).get_contained().is_medication() &&
                                     ( *loc ).get_contained().type->has_use() ? ( *loc ).get_contained() : *loc;
                    return string_format( "<color_light_green>%s</color>", get_action_name( it ) );
                }, _( "ACTION" ) );
            }
        }
References _, inventory_selector_preset::append_cell(), get_action_name(), item::is_container_empty(), and string_format().
Member Function Documentation
get_action_name()
std::string activatable_inventory_preset::get_action_name (const item & it) const inline protected
Definition at line 881 of file game_inventory.cpp.
{
            const auto &uses = it.type->use_methods;
            if( uses.size() == 1 ) {
                return uses.begin()->second.get_name();
            } else if( uses.size() > 1 ) {
                return _( "…" );
            }
            return std::string();
        }
References _, item::type, and itype::use_methods.
Referenced by activatable_inventory_preset().
get_denial()
std::string activatable_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from pickup_inventory_preset.
Definition at line 850 of file game_inventory.cpp.
{
            const item &it = !( *loc ).is_container_empty() && ( *loc ).get_contained().is_medication() &&
                             ( *loc ).get_contained().type->has_use() ? ( *loc ).get_contained() : *loc;
            const auto &uses = it.type->use_methods;
            if( uses.size() == 1 ) {
                const auto ret = uses.begin()->second.can_call( p, it, false, p.pos() );
                if( !ret.success() ) {
                    return trim_punctuation_marks( ret.str() );
                }
            }
            if( it.is_medication() && !p.can_use_heal_item( it ) && !it.is_craft() ) {
                return _( "Your biology is not compatible with that item." );
            }
            if( !p.has_enough_charges( it, false ) ) {
                return string_format(
                           vgettext( "Needs at least %d charge",
                                     "Needs at least %d charges", loc->ammo_required() ),
                           loc->ammo_required() );
            }
            if( !it.has_flag( flag_ALLOWS_REMOTE_USE ) ) {
                return pickup_inventory_preset::get_denial( loc );
            }
            return std::string();
        }
References _, item::ammo_required(), Character::can_use_heal_item(), flag_ALLOWS_REMOTE_USE(), pickup_inventory_preset::get_denial(), Character::has_enough_charges(), item::has_flag(), item::is_container_empty(), item::is_craft(), item::is_medication(), p, Character::pos(), cata::hash64_detail::ret, string_format(), trim_punctuation_marks(), item::type, itype::use_methods, and vgettext().
is_shown()
bool activatable_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 842 of file game_inventory.cpp.
{
            if( !( *loc ).is_container_empty() && ( *loc ).get_contained().is_medication() &&
                ( *loc ).get_contained().type->has_use() ) {
                return true;
            }
            return loc->type->has_use();
        }
References itype::has_use(), and item::type.
Member Data Documentation
p
const player& activatable_inventory_preset::p private
Definition at line 894 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp