Cataclysm BN: pick_lock_actor Class Reference
pick_lock_actor Class Reference
This implements lock picking.
#include <iuse_actor.h>
Public Member Functions
pick_lock_actor ()
~pick_lock_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int pick_quality = 0
How good the used tool is at picking a lock.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This implements lock picking.
Definition at line 454 of file iuse_actor.h.
Constructor & Destructor Documentation
pick_lock_actor()
pick_lock_actor::pick_lock_actor () inline
Definition at line 462 of file iuse_actor.h.
: iuse_actor("picklock") {}
~pick_lock_actor()
pick_lock_actor::~pick_lock_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > pick_lock_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1138 of file iuse_actor.cpp.
{
    return std::make_unique<pick_lock_actor>( *this );
}
load()
void pick_lock_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1143 of file iuse_actor.cpp.
{
    pick_quality = obj.get_int( "pick_quality" );
}
References JsonObject::get_int(), and pick_quality.
use()
int pick_lock_actor::use (player & p, item & it, bool , const tripoint & t) const override virtual
Dexterity speeds up door lock picking Lock Picking speeds up door lock picking
Implements iuse_actor.
Definition at line 1148 of file iuse_actor.cpp.
{
    if( p.is_npc() ) {
        return 0;
    }
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    map &here = get_map();
    const std::function<bool( const tripoint & )> f = [&here]( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        const ter_id ter = here.ter( pnt );
        const furn_id furn = here.furn( pnt );
        lockpicking_open_result result = get_lockpicking_open_result( ter, furn );
        const bool is_allowed = result.new_ter_type || result.new_furn_type;
        return is_allowed;
    };
    const cata::optional<tripoint> pnt_ = ( t != p.pos() ) ? t : choose_adjacent_highlight(
            _( "Use your lockpick where?" ), _( "There is nothing to lockpick nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id type = here.ter( pnt );
    if( !f( pnt ) ) {
        if( pnt == p.pos() ) {
            p.add_msg_if_player( m_info, _( "You pick your nose and your sinuses swing open." ) );
        } else if( g->critter_at<npc>( pnt ) ) {
            p.add_msg_if_player( m_info,
                                 _( "You can pick your friends, and you can\npick your nose, but you can't pick\nyour friend's nose." ) );
        } else if( type == t_door_c ) {
            p.add_msg_if_player( m_info, _( "That door isn't locked." ) );
        } else {
            p.add_msg_if_player( m_info, _( "That cannot be picked." ) );
        }
        return 0;
    }
    /** @EFFECT_DEX speeds up door lock picking */
    /** @EFFECT_LOCKPICK speeds up door lock picking */
    const int duration = std::max( 0,
                                   to_moves<int>( 10_minutes - time_duration::from_minutes( it.get_quality( qual_LOCKPICK ) ) ) -
                                   ( p.dex_cur + 5 ) * 2300 );
    p.assign_activity( activity_id( "ACT_LOCKPICK" ), duration, -1, p.get_item_position( &it ) );
    p.activity.targets.push_back( item_location( p, &it ) );
    p.activity.placement = pnt;
    return it.type->charges_to_use();
}
References _, Character::activity, player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), Character::dex_cur, time_duration::from_minutes(), map::furn(), g, Character::get_item_position(), get_lockpicking_open_result(), get_map(), item::get_quality(), Character::is_mounted(), player::is_npc(), m_info, player_activity::placement, Character::pos(), qual_LOCKPICK, t_door_c, player_activity::targets, map::ter(), item::type, and iuse_actor::type.
Member Data Documentation
pick_quality
int pick_lock_actor::pick_quality = 0
How good the used tool is at picking a lock.
Definition at line 460 of file iuse_actor.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp