Cataclysm BN: jmapgen_spawn_item Class Reference
jmapgen_spawn_item Class Reference
Place a specific item.
Public Member Functions
jmapgen_spawn_item (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (mapgendata &, const point &) const
Public Attributes
itype_id type
jmapgen_int amount
jmapgen_int chance
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a specific item.
"item": id of item type to spawn. "chance": chance of spawning it (1 = always, otherwise one_in(chance)). "amount": amount of items to spawn. "repeat": number of times to apply this piece
Definition at line 1391 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_spawn_item()
jmapgen_spawn_item::jmapgen_spawn_item (const JsonObject & jsi) inline
Definition at line 1397 of file mapgen.cpp.
                                                    :
            type( jsi.get_string( "item" ) )
            , amount( jsi, "amount", 1, 1 )
            , chance( jsi, "chance", 100, 100 ) {
            // Itemgroups apply migrations when being loaded, but we need to migrate
            // individual items here.
            type = item_controller->migrate_id( type );
            if( !type.is_valid() ) {
                set_mapgen_defer( jsi, "item", "no such item" );
            }
            repeat = jmapgen_int( jsi, "repeat", 1, 1 );
        }
References string_id< T >::is_valid(), item_controller, mapgen_defer::jsi, jmapgen_piece::repeat, set_mapgen_defer(), and type.
Member Function Documentation
apply()
void jmapgen_spawn_item::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1409 of file mapgen.cpp.
{
            const int c = chance.get();
            // 100% chance = exactly 1 item, otherwise scale by item spawn rate.
            const float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
            int spawn_count = ( c == 100 ) ? 1 : roll_remainder( c * spawn_rate / 100.0f );
            for( int i = 0; i < spawn_count; i++ ) {
                dat.m.spawn_item( point( x.get(), y.get() ), type, amount.get() );
            }
        }
References amount, c, chance, jmapgen_int::get(), mapgendata::m, roll_remainder(), map::spawn_item(), and type.
Member Data Documentation
amount
jmapgen_int jmapgen_spawn_item::amount
Definition at line 1395 of file mapgen.cpp.
Referenced by apply().
chance
jmapgen_int jmapgen_spawn_item::chance
Definition at line 1396 of file mapgen.cpp.
Referenced by apply().
type
itype_id jmapgen_spawn_item::type
Definition at line 1394 of file mapgen.cpp.
Referenced by apply(), and jmapgen_spawn_item().
The documentation for this class was generated from the following file:
src/mapgen.cpp