Cataclysm BN: event_multiset Class Reference
event_multiset Class Reference
#include <stats_tracker.h>
Public Types
using counts_type = std::unordered_map< cata::event::data_type, int, cata::range_hash >
Public Member Functions
event_multiset ()
event_multiset (event_type type)
void set_type (event_type)
const counts_type & counts () const
int count () const
int count (const cata::event::data_type &criteria) const
int total (const std::string &field) const
int total (const std::string &field, const cata::event::data_type &criteria) const
int minimum (const std::string &field) const
int maximum (const std::string &field) const
void add (const cata::event &)
void add (const counts_type::value_type &)
void serialize (JsonOut &) const
void deserialize (JsonIn &)
Private Attributes
event_type type_
counts_type counts_
Detailed Description
Definition at line 34 of file stats_tracker.h.
Member Typedef Documentation
counts_type
using event_multiset::counts_type = std::unordered_map<cata::event::data_type, int, cata::range_hash>
Definition at line 37 of file stats_tracker.h.
Constructor & Destructor Documentation
event_multiset() [1/2]
event_multiset::event_multiset () inline
Definition at line 41 of file stats_tracker.h.
: type_(event_type::num_event_types) {}
event_multiset() [2/2]
event_multiset::event_multiset (event_type type) inline
Definition at line 42 of file stats_tracker.h.
: type_(type) {}
Member Function Documentation
add() [1/2]
void event_multiset::add (const cata::event & e)
Definition at line 102 of file stats_tracker.cpp.
{
    counts_[e.data()]++;
}
References counts_, and cata::event::data().
Referenced by event_transformation_impl::state::event_added(), and stats_tracker::notify().
add() [2/2]
void event_multiset::add (const counts_type::value_type & e)
Definition at line 107 of file stats_tracker.cpp.
{
    counts_[e.first] += e.second;
}
References counts_.
count() [1/2]
int event_multiset::count () const
Definition at line 30 of file stats_tracker.cpp.
{
    int total = 0;
    for( const auto &pair : counts_ ) {
        total += pair.second;
    }
    return total;
}
References counts_, and total().
Referenced by event_statistic_count::state::events_reset().
count() [2/2]
int event_multiset::count (const cata::event::data_type & criteria) const
Definition at line 39 of file stats_tracker.cpp.
{
    int total = 0;
    for( const auto &pair : counts_ ) {
        if( event_data_matches( pair.first, criteria ) ) {
            total += pair.second;
        }
    }
    return total;
}
References counts_, event_data_matches(), and total().
counts()
const counts_type & event_multiset::counts () const inline
Definition at line 46 of file stats_tracker.h.
{
            return counts_;
        }
References counts_.
deserialize()
void event_multiset::deserialize (JsonIn & jsin)
Definition at line 3690 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    std::vector<std::pair<cata::event::data_type, int>> copy;
    jo.read( "event_counts", copy );
    counts_ = { copy.begin(), copy.end() };
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and JsonObject::read().
maximum()
int event_multiset::maximum (const std::string & field) const
Definition at line 86 of file stats_tracker.cpp.
{
    int maximum = 0;
    for( const auto &pair : counts_ ) {
        auto it = pair.first.find( field );
        if( it == pair.first.end() ) {
            continue;
        }
        const int potential = it->second.get<cata_variant_type::int_>();
        if( potential > maximum ) {
            maximum = potential;
        }
    }
    return maximum;
}
References counts_, int_, and maximum().
Referenced by event_statistic_maximum::state::events_reset(), and maximum().
minimum()
int event_multiset::minimum (const std::string & field) const
Definition at line 70 of file stats_tracker.cpp.
{
    int minimum = 0;
    for( const auto &pair : counts_ ) {
        auto it = pair.first.find( field );
        if( it == pair.first.end() ) {
            continue;
        }
        const int potential = it->second.get<cata_variant_type::int_>();
        if( potential < minimum ) {
            minimum = potential;
        }
    }
    return minimum;
}
References counts_, int_, and minimum().
Referenced by event_statistic_minimum::state::events_reset(), and minimum().
serialize()
void event_multiset::serialize (JsonOut & jsout) const
Definition at line 3682 of file savegame_json.cpp.
{
    jsout.start_object();
    std::vector<counts_type::value_type> copy( counts_.begin(), counts_.end() );
    jsout.member( "event_counts", copy );
    jsout.end_object();
}
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
set_type()
void event_multiset::set_type (event_type type)
Definition at line 23 of file stats_tracker.cpp.
{
    // Used during stats_tracker deserialization to set the type
    assert( type_ == event_type::num_event_types );
    type_ = type;
}
References num_event_types, type, and type_.
total() [1/2]
int event_multiset::total (const std::string & field) const
Definition at line 50 of file stats_tracker.cpp.
{
    return total( field, {} );
}
References total().
Referenced by count(), event_statistic_total::state::events_reset(), and total().
total() [2/2]
int event_multiset::total (const std::string & field, const cata::event::data_type & criteria) const
Definition at line 55 of file stats_tracker.cpp.
{
    int total = 0;
    for( const auto &pair : counts_ ) {
        auto it = pair.first.find( field );
        if( it == pair.first.end() ) {
            continue;
        }
        if( event_data_matches( pair.first, criteria ) ) {
            total += pair.second * it->second.get<cata_variant_type::int_>();
        }
    }
    return total;
}
References counts_, event_data_matches(), int_, and total().
Referenced by total().
Member Data Documentation
counts_
counts_type event_multiset::counts_ private
Definition at line 78 of file stats_tracker.h.
Referenced by add(), count(), counts(), maximum(), minimum(), and total().
type_
event_type event_multiset::type_ private
Definition at line 77 of file stats_tracker.h.
Referenced by set_type().
The documentation for this class was generated from the following files:
src/stats_tracker.h
src/savegame_json.cpp
src/stats_tracker.cpp