Cataclysm BN: basic_printf_context< OutputIt, Char > Class Template Reference
basic_printf_context< OutputIt, Char > Class Template Reference
This template formats data and writes the output through an output iterator.
#include <fmtlib_printf.h>
Public Types
using char_type = Char
The character type for the output.
using iterator = OutputIt
using format_arg = basic_format_arg< basic_printf_context >
using parse_context_type = basic_printf_parse_context< Char >
template<typename T >
using formatter_type = printf_formatter< T >
Public Member Functions
basic_printf_context (OutputIt out, basic_string_view< char_type > format_str, basic_format_args< basic_printf_context > args)
\rst Constructs a printf_context object.
OutputIt out ()
void advance_to (OutputIt it)
detail::locale_ref locale ()
format_arg arg (int id) const
parse_context_type & parse_context ()
FMT_CONSTEXPR void on_error (const char *message)
template<typename ArgFormatter = printf_arg_formatter<OutputIt, Char>>
OutputIt format ()
Formats stored arguments and writes the output to the range.
Private Types
using format_specs = basic_format_specs< char_type >
Private Member Functions
format_arg get_arg (int arg_index=-1)
int parse_header (const Char *&it, const Char *end, format_specs &specs)
Static Private Member Functions
static void parse_flags (format_specs &specs, const Char *&it, const Char *end)
Private Attributes
OutputIt out_
basic_format_args< basic_printf_context > args_
parse_context_type parse_ctx_
Detailed Description
template<typename OutputIt, typename Char>
class basic_printf_context< OutputIt, Char >
This template formats data and writes the output through an output iterator.
Definition at line 373 of file fmtlib_printf.h.
Member Typedef Documentation
char_type
template<typename OutputIt , typename Char > using basic_printf_context< OutputIt, Char >::char_type = Char
The character type for the output.
Definition at line 377 of file fmtlib_printf.h.
format_arg
template<typename OutputIt , typename Char > using basic_printf_context< OutputIt, Char >::format_arg = basic_format_arg<basic_printf_context>
Definition at line 379 of file fmtlib_printf.h.
format_specs
template<typename OutputIt , typename Char > using basic_printf_context< OutputIt, Char >::format_specs = basic_format_specs<char_type> private
Definition at line 384 of file fmtlib_printf.h.
formatter_type
template<typename OutputIt , typename Char > template<typename T > using basic_printf_context< OutputIt, Char >::formatter_type = printf_formatter<T>
Definition at line 381 of file fmtlib_printf.h.
iterator
template<typename OutputIt , typename Char > using basic_printf_context< OutputIt, Char >::iterator = OutputIt
Definition at line 378 of file fmtlib_printf.h.
parse_context_type
template<typename OutputIt , typename Char > using basic_printf_context< OutputIt, Char >::parse_context_type = basic_printf_parse_context<Char>
Definition at line 380 of file fmtlib_printf.h.
Constructor & Destructor Documentation
basic_printf_context()
template<typename OutputIt , typename Char > basic_printf_context< OutputIt, Char >::basic_printf_context (OutputIt out, basic_string_view< char_type > format_str, basic_format_args< basic_printf_context< OutputIt, Char > > args) inline
\rst Constructs a printf_context object.
References to the arguments are stored in the context object so make sure they have appropriate lifetimes. \endrst
Definition at line 407 of file fmtlib_printf.h.
            : out_( out ), args_( args ), parse_ctx_( format_str ) {}
Member Function Documentation
advance_to()
template<typename OutputIt , typename Char > void basic_printf_context< OutputIt, Char >::advance_to (OutputIt it) inline
Definition at line 414 of file fmtlib_printf.h.
{
            out_ = it;
        }
References basic_printf_context< OutputIt, Char >::out_.
arg()
template<typename OutputIt , typename Char > format_arg basic_printf_context< OutputIt, Char >::arg (int id) const inline
Definition at line 422 of file fmtlib_printf.h.
{
            return args_.get( id );
        }
References basic_printf_context< OutputIt, Char >::args_.
format()
template<typename OutputIt , typename Char > template<typename ArgFormatter > OutputIt basic_printf_context< OutputIt, Char >::format
Formats stored arguments and writes the output to the range.
Definition at line 525 of file fmtlib_printf.h.
{
    auto out = this->out();
    const Char *start = parse_ctx_.begin();
    const Char *end = parse_ctx_.end();
    auto it = start;
    while( it != end ) {
        char_type c = *it++;
        if( c != '%' ) {
            continue;
        }
        if( it != end && *it == c ) {
            out = std::copy( start, it, out );
            start = ++it;
            continue;
        }
        out = std::copy( start, it - 1, out );
        format_specs specs;
        specs.align = align::right;
        // Parse argument index, flags and width.
        int arg_index = parse_header( it, end, specs );
        if( arg_index == 0 ) {
            on_error( "argument not found" );
        }
        // Parse precision.
        if( it != end && *it == '.' ) {
            ++it;
            c = it != end ? *it : 0;
            if( '0' <= c && c <= '9' ) {
                detail::error_handler eh;
                specs.precision = parse_nonnegative_int( it, end, eh );
            } else if( c == '*' ) {
                ++it;
                specs.precision = static_cast<int>(
                                      visit_format_arg( detail::printf_precision_handler(), get_arg() ) );
            } else {
                specs.precision = 0;
            }
        }
        format_arg arg = get_arg( arg_index );
        // For d, i, o, u, x, and X conversion specifiers, if a precision is
        // specified, the '0' flag is ignored
        if( specs.precision >= 0 && arg.is_integral() )
            specs.fill[0] =
                ' ';  // Ignore '0' flag for non-numeric types or if '-' present.
        if( specs.precision >= 0 && arg.type() == detail::type::cstring_type ) {
            auto str = visit_format_arg( detail::get_cstring<Char>(), arg );
            auto str_end = str + specs.precision;
            auto nul = std::find( str, str_end, Char() );
            arg = detail::make_arg<basic_printf_context>( basic_string_view<Char>(
                        str,
                        detail::to_unsigned( nul != str_end ? nul - str : specs.precision ) ) );
        }
        if( specs.alt && visit_format_arg( detail::is_zero_int(), arg ) ) {
            specs.alt = false;
        }
        if( specs.fill[0] == '0' ) {
            if( arg.is_arithmetic() && specs.align != align::left ) {
                specs.align = align::numeric;
            } else {
                specs.fill[0] = ' ';    // Ignore '0' flag for non-numeric types or if '-'
            }
            // flag is also present.
        }
        // Parse length and convert the argument to the required type.
        c = it != end ? *it++ : 0;
        char_type t = it != end ? *it : 0;
        using detail::convert_arg;
        switch( c ) {
            case 'h':
                if( t == 'h' ) {
                    ++it;
                    t = it != end ? *it : 0;
                    convert_arg<signed char>( arg, t );
                } else {
                    convert_arg<short>( arg, t );
                }
                break;
            case 'l':
                if( t == 'l' ) {
                    ++it;
                    t = it != end ? *it : 0;
                    convert_arg<long long>( arg, t );
                } else {
                    convert_arg<long>( arg, t );
                }
                break;
            case 'j':
                convert_arg<intmax_t>( arg, t );
                break;
            case 'z':
                convert_arg<size_t>( arg, t );
                break;
            case 't':
                convert_arg<std::ptrdiff_t>( arg, t );
                break;
            case 'L':
                // printf produces garbage when 'L' is omitted for long double, no
                // need to do the same.
                break;
            default:
                --it;
                convert_arg<void>( arg, c );
        }
        // Parse type.
        if( it == end ) {
            FMT_THROW( format_error( "invalid format string" ) );
        }
        specs.type = static_cast<char>( *it++ );
        if( arg.is_integral() ) {
            // Normalize type.
            switch( specs.type ) {
                case 'i':
                case 'u':
                    specs.type = 'd';
                    break;
                case 'c':
                    visit_format_arg( detail::char_converter<basic_printf_context>( arg ),
                                      arg );
                    break;
            }
        }
        start = it;
        // Format argument.
        out = visit_format_arg( ArgFormatter( out, specs, *this ), arg );
    }
    return std::copy( start, it, out );
}
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, arg(), c, detail::convert_arg(), detail::cstring_type, basic_format_specs< Char >::fill, detail::find(), FMT_THROW, detail::get_arg(), align::left, align::numeric, detail::parse_nonnegative_int(), basic_format_specs< Char >::precision, align::right, detail::to_unsigned(), basic_format_specs< Char >::type, and visit_format_arg().
get_arg()
template<typename OutputIt , typename Char > basic_printf_context< OutputIt, Char >::format_arg basic_printf_context< OutputIt, Char >::get_arg (int arg_index = -1) private
Definition at line 471 of file fmtlib_printf.h.
{
    if( arg_index < 0 ) {
        arg_index = parse_ctx_.next_arg_id();
    } else {
        parse_ctx_.check_arg_id( --arg_index );
    }
    return detail::get_arg( *this, arg_index );
}
References detail::get_arg().
locale()
template<typename OutputIt , typename Char > detail::locale_ref basic_printf_context< OutputIt, Char >::locale () inline
Definition at line 418 of file fmtlib_printf.h.
{
            return {};
        }
on_error()
template<typename OutputIt , typename Char > FMT_CONSTEXPR void basic_printf_context< OutputIt, Char >::on_error (const char * message) inline
Definition at line 430 of file fmtlib_printf.h.
{
            parse_ctx_.on_error( message );
        }
References mapgen_defer::message, basic_format_parse_context< Char, ErrorHandler >::on_error(), and basic_printf_context< OutputIt, Char >::parse_ctx_.
out()
template<typename OutputIt , typename Char > OutputIt basic_printf_context< OutputIt, Char >::out () inline
Definition at line 411 of file fmtlib_printf.h.
                       {
            return out_;
        }
References basic_printf_context< OutputIt, Char >::out_.
parse_context()
template<typename OutputIt , typename Char > parse_context_type & basic_printf_context< OutputIt, Char >::parse_context () inline
Definition at line 426 of file fmtlib_printf.h.
{
            return parse_ctx_;
        }
References basic_printf_context< OutputIt, Char >::parse_ctx_.
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
parse_flags()
template<typename OutputIt , typename Char > void basic_printf_context< OutputIt, Char >::parse_flags (format_specs & specs, const Char *& it, const Char * end) static private
Definition at line 440 of file fmtlib_printf.h.
{
    for( ; it != end; ++it ) {
        switch( *it ) {
            case '-':
                specs.align = align::left;
                break;
            case '+':
                specs.sign = sign::plus;
                break;
            case '0':
                specs.fill[0] = '0';
                break;
            case ' ':
                if( specs.sign != sign::plus ) {
                    specs.sign = sign::space;
                }
                break;
            case '#':
                specs.alt = true;
                break;
            default:
                return;
        }
    }
}
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, basic_format_specs< Char >::fill, align::left, sign::plus, basic_format_specs< Char >::sign, and sign::space.
parse_header()
template<typename OutputIt , typename Char > int basic_printf_context< OutputIt, Char >::parse_header (const Char *& it, const Char * end, format_specs & specs) private
Definition at line 482 of file fmtlib_printf.h.
{
    int arg_index = -1;
    char_type c = *it;
    if( c >= '0' && c <= '9' ) {
        // Parse an argument index (if followed by '$') or a width possibly
        // preceded with '0' flag(s).
        detail::error_handler eh;
        int value = parse_nonnegative_int( it, end, eh );
        if( it != end && *it == '$' ) { // value is an argument index
            ++it;
            arg_index = value;
        } else {
            if( c == '0' ) {
                specs.fill[0] = '0';
            }
            if( value != 0 ) {
                // Nonzero value means that we parsed width and don't need to
                // parse it or flags again, so return now.
                specs.width = value;
                return arg_index;
            }
        }
    }
    parse_flags( specs, it, end );
    // Parse width.
    if( it != end ) {
        if( *it >= '0' && *it <= '9' ) {
            detail::error_handler eh;
            specs.width = parse_nonnegative_int( it, end, eh );
        } else if( *it == '*' ) {
            ++it;
            specs.width = static_cast<int>( visit_format_arg(
                                                detail::printf_width_handler<char_type>( specs ), get_arg() ) );
        }
    }
    return arg_index;
}
References c, basic_format_specs< Char >::fill, detail::get_arg(), detail::parse_nonnegative_int(), visit_format_arg(), and basic_format_specs< Char >::width.
Member Data Documentation
args_
template<typename OutputIt , typename Char > basic_format_args<basic_printf_context> basic_printf_context< OutputIt, Char >::args_ private
Definition at line 387 of file fmtlib_printf.h.
Referenced by basic_printf_context< OutputIt, Char >::arg().
out_
template<typename OutputIt , typename Char > OutputIt basic_printf_context< OutputIt, Char >::out_ private
Definition at line 386 of file fmtlib_printf.h.
Referenced by basic_printf_context< OutputIt, Char >::advance_to(), and basic_printf_context< OutputIt, Char >::out().
parse_ctx_
template<typename OutputIt , typename Char > parse_context_type basic_printf_context< OutputIt, Char >::parse_ctx_ private
Definition at line 388 of file fmtlib_printf.h.
Referenced by basic_printf_context< OutputIt, Char >::on_error(), and basic_printf_context< OutputIt, Char >::parse_context().
The documentation for this class was generated from the following files:
src/fmtlib_ostream.h
src/fmtlib_printf.h