Cataclysm BN: recipe Class Reference
recipe Class Reference
#include <recipe.h>
Public Member Functions
recipe ()
operator bool () const
const itype_id & result () const
const requirement_data & simple_requirements () const
Fetch combined requirement data (inline and via "using" syntax).
const deduped_requirement_data & deduped_requirements () const
const recipe_id & ident () const
bool is_blacklisted () const
bool will_be_blacklisted () const
std::function< bool(const item &)> get_component_filter (recipe_filter_flags=recipe_filter_flags::none) const
requirement_data disassembly_requirements () const
If recipe can be used for disassembly fetch the combined requirements.
std::string result_name () const
std::string primary_skill_string (const Character *c, bool print_skill_level) const
std::string required_skills_string (const Character *, bool include_primary_skill, bool print_skill_level) const
std::string required_all_skills_string () const
std::string batch_savings_string () const
item create_result () const
std::vector< item > create_results (int batch=1) const
std::vector< item > create_byproducts (int batch=1) const
bool has_byproducts () const
int batch_time (int batch, float multiplier, size_t assistants) const
time_duration batch_duration (int batch=1, float multiplier=1.0, size_t assistants=0) const
bool has_flag (const std::string &flag_name) const
bool is_reversible () const
void load (const JsonObject &jo, const std::string &src)
void finalize ()
std::string get_consistency_error () const
Returns a non-empty string describing an inconsistency (if any) in the recipe.
bool is_blueprint () const
const std::string & get_blueprint () const
const translation & blueprint_name () const
const std::vector< itype_id > & blueprint_resources () const
const std::vector< std::pair< std::string, int > > & blueprint_provides () const
const std::vector< std::pair< std::string, int > > & blueprint_requires () const
const std::vector< std::pair< std::string, int > > & blueprint_excludes () const
void check_blueprint_requirements ()
Calculate blueprint requirements according to changed terrain and furniture tiles, then check the calculated requirements against blueprint requirements specified in JSON.
bool hot_result () const
int makes_amount () const
Returns the amount or charges recipe will produce.
int disassembly_batch_size () const
Returns number of charges of the item needed for single disassembly.
Public Attributes
std::vector< std::pair< recipe_id, mod_id > > src
bool obsolete = false
std::string category
std::string subcategory
translation description
int time = 0
int difficulty = 0
bool never_learn = false
Prevent this recipe from ever being added to the player's learned recipies (used for special NPC crafting)
std::map< itype_id, int > byproducts
skill_id skill_used
std::map< skill_id, int > required_skills
std::map< skill_id, int > autolearn_requirements
std::map< skill_id, int > learn_by_disassembly
std::map< itype_id, int > booksets
std::set< std::string > flags_to_delete
Private Member Functions
void add_requirements (const std::vector< std::pair< requirement_id, int > > &reqs)
Private Attributes
itype_id result_ = itype_id::NULL_ID()
recipe_id ident_ = recipe_id::NULL_ID()
abstract bool = false
Abstract recipes can be inherited from but are themselves disposed of at finalization.
bool autolearn = false
set learning requirements equal to required skills at finalization?
bool contained = false
Does the item spawn contained in container?
bool reversible = false
Can recipe be used for disassembly of result via disassembly_requirements.
itype_id container = itype_id::NULL_ID()
What does the item spawn contained in? Unset ("null") means default container.
std::vector< std::pair< requirement_id, int > > reqs_external
External requirements (via "using" syntax) where second field is multiplier.
std::vector< std::pair< requirement_id, int > > reqs_internal
Requires specified inline with the recipe (and replaced upon inheritance)
requirement_data requirements_
Combined requirements cached when recipe finalized.
deduped_requirement_data deduped_requirements_
Deduped version constructed from the above requirements_.
std::set< std::string > flags
cata::optional< int > charges
If set (zero or positive) set charges of output result for items counted by charges.
double batch_rscale = 0.0
int batch_rsize = 0
int result_mult = 1
std::string blueprint
translation bp_name
std::vector< itype_id > bp_resources
std::vector< std::pair< std::string, int > > bp_provides
std::vector< std::pair< std::string, int > > bp_requires
std::vector< std::pair< std::string, int > > bp_excludes
bool has_blueprint_needs = false
Blueprint requirements to be checked in unit test.
bool check_blueprint_needs = false
int time_blueprint = 0
std::map< skill_id, int > skills_blueprint
std::vector< std::pair< requirement_id, int > > reqs_blueprint
Friends
class recipe_dictionary
Detailed Description
Definition at line 34 of file recipe.h.
Constructor & Destructor Documentation
recipe()
recipe::recipe ()
Definition at line 41 of file recipe.cpp.
: skill_used(skill_id::NULL_ID()) {}
Member Function Documentation
add_requirements()
void recipe::add_requirements (const std::vector< std::pair< requirement_id, int > > & reqs) private
Definition at line 382 of file recipe.cpp.
{
    requirements_ = std::accumulate( reqs.begin(), reqs.end(), requirements_,
    []( const requirement_data & lhs, const std::pair<requirement_id, int> &rhs ) {
        return lhs + ( *rhs.first * rhs.second );
    } );
}
References requirements_.
Referenced by finalize().
batch_duration()
time_duration recipe::batch_duration (int batch = 1, float multiplier = 1.0, size_t assistants = 0) const
Definition at line 43 of file recipe.cpp.
{
    return time_duration::from_turns( batch_time( batch, multiplier, assistants ) / 100 );
}
References batch_time(), and time_duration::from_turns().
Referenced by basecamp::craft_description(), basecamp::om_upgrade_description(), basecamp::recipe_batch_max(), basecamp::start_crafting(), basecamp::start_fortifications(), basecamp::start_upgrade(), and basecamp::upgrade_return().
batch_savings_string()
std::string recipe::batch_savings_string () const
Definition at line 605 of file recipe.cpp.
{
    return ( batch_rsize != 0 ) ?
           string_format( _( "%s%% at >%s units" ), static_cast<int>( batch_rscale * 100 ), batch_rsize )
           : _( "none" );
}
References _, batch_rscale, batch_rsize, and string_format().
batch_time()
int recipe::batch_time (int batch, float multiplier, size_t assistants) const
Definition at line 48 of file recipe.cpp.
{
    // 1.0f is full speed
    // 0.33f is 1/3 speed
    if( multiplier == 0.0f ) {
        // If an item isn't craftable in the dark, show the time to complete as if you could craft it
        multiplier = 1.0f;
    }
    const float local_time = static_cast<float>( time ) / multiplier;
    // if recipe does not benefit from batching and we have no assistants, don't do unnecessary additional calculations
    if( batch_rscale == 0.0 && assistants == 0 ) {
        return static_cast<int>( local_time ) * batch;
    }
    float total_time = 0.0;
    // if recipe does not benefit from batching but we do have assistants, skip calculating the batching scale factor
    if( batch_rscale == 0.0 ) {
        total_time = local_time * batch;
    } else {
        // recipe benefits from batching, so batching scale factor needs to be calculated
        // At batch_rsize, incremental time increase is 99.5% of batch_rscale
        const double scale = batch_rsize / 6.0;
        for( int x = 0; x < batch; x++ ) {
            // scaled logistic function output
            const double logf = ( 2.0 / ( 1.0 + std::exp( -( x / scale ) ) ) ) - 1.0;
            total_time += local_time * ( 1.0 - ( batch_rscale * logf ) );
        }
    }
    //Assistants can decrease the time for production but never less than that of one unit
    if( assistants == 1 ) {
        total_time = total_time * .75;
    } else if( assistants >= 2 ) {
        total_time = total_time * .60;
    }
    if( total_time < local_time ) {
        total_time = local_time;
    }
    return static_cast<int>( total_time );
}
References batch_rscale, batch_rsize, and time.
Referenced by player::base_time_to_craft(), batch_duration(), activity_handlers::craft_do_turn(), craft_progress_message(), and player::expected_time_to_craft().
blueprint_excludes()
const std::vector< std::pair< std::string, int > > & recipe::blueprint_excludes () const
Definition at line 713 of file recipe.cpp.
{
    return bp_excludes;
}
References bp_excludes.
Referenced by basecamp::available_upgrades().
blueprint_name()
const translation & recipe::blueprint_name () const
Definition at line 693 of file recipe.cpp.
{
    return bp_name;
}
References bp_name.
Referenced by basecamp::available_upgrades(), and basecamp::survey_return().
blueprint_provides()
const std::vector< std::pair< std::string, int > > & recipe::blueprint_provides () const
Definition at line 703 of file recipe.cpp.
{
    return bp_provides;
}
References bp_provides.
Referenced by basecamp::update_in_progress(), and basecamp::update_provides().
blueprint_requires()
const std::vector< std::pair< std::string, int > > & recipe::blueprint_requires () const
Definition at line 708 of file recipe.cpp.
{
    return bp_requires;
}
References bp_requires.
Referenced by basecamp::available_upgrades().
blueprint_resources()
const std::vector< itype_id > & recipe::blueprint_resources () const
Definition at line 698 of file recipe.cpp.
{
    return bp_resources;
}
References bp_resources.
Referenced by basecamp::update_resources().
check_blueprint_requirements()
void recipe::check_blueprint_requirements ()
Calculate blueprint requirements according to changed terrain and furniture tiles, then check the calculated requirements against blueprint requirements specified in JSON.
If there's any inconsistency, it issues a debug message. This is only used in unit tests so as to speed up data loading in gameplay.
Definition at line 755 of file recipe.cpp.
{
    if( !blueprint.empty() && !mapgen::has_update_id( blueprint ) ) {
        debugmsg( "Blueprint %1$s has invalid mapgen id %2$s", ident_.str(), blueprint );
        return;
    }
    build_reqs total_reqs;
    const std::pair<std::map<ter_id, int>, std::map<furn_id, int>> &changed_ids
            = get_changed_ids_from_update( blueprint );
    get_build_reqs_for_furn_ter_ids( ident(), changed_ids, total_reqs );
    requirement_data req_data_blueprint = std::accumulate(
            reqs_blueprint.begin(), reqs_blueprint.end(), requirement_data(),
    []( const requirement_data & lhs, const std::pair<requirement_id, int> &rhs ) {
        return lhs + ( *rhs.first * rhs.second );
    } );
    requirement_data req_data_calc = std::accumulate(
                                         total_reqs.reqs.begin(), total_reqs.reqs.end(), requirement_data(),
    []( const requirement_data & lhs, const std::pair<requirement_id, int> &rhs ) {
        return lhs + ( *rhs.first * rhs.second );
    } );
    // do not consolidate req_data_blueprint: it actually changes the meaning of the requirement.
    // instead we enforce specifying the exact consolidated requirement.
    req_data_calc.consolidate();
    if( time_blueprint != total_reqs.time || skills_blueprint != total_reqs.skills
        || !req_data_blueprint.has_same_requirements_as( req_data_calc ) ) {
        std::string calc_req_str = dump_requirements( req_data_calc, total_reqs.time, total_reqs.skills );
        std::string got_req_str = dump_requirements( req_data_blueprint, time_blueprint, skills_blueprint );
        std::stringstream ss;
        for( auto &id_count : changed_ids.first ) {
            ss << string_format( "%s: %d\n", id_count.first.id(), id_count.second );
        }
        for( auto &id_count : changed_ids.second ) {
            ss << string_format( "%s: %d\n", id_count.first.id(), id_count.second );
        }
        debugmsg( "Specified blueprint requirements of %1$s does not match calculated requirements.  "
                  "Specify \"check_blueprint_needs\": false to disable the check or "
                  "Update \"blueprint_needs\" to the following value (you can use tools/update_blueprint_needs.py):\n"
                  // mark it for the auto-update python script
                  "~~~ auto-update-blueprint: %1$s\n"
                  "%2$s\n"
                  "~~~ end-auto-update\n"
                  "If the stated requirements match the above, but the error still appears, it is a bug.\n"
                  "Stated requirements are expanded to:\n"
                  "%3$s\n"
                  "---Begin expected tile changes---\n%4$s---End expected tile changes--",
                  ident_.str(), calc_req_str, got_req_str, ss.str() );
    }
}
References blueprint, requirement_data::consolidate(), debugmsg, dump_requirements(), get_build_reqs_for_furn_ter_ids(), get_changed_ids_from_update(), requirement_data::has_same_requirements_as(), mapgen::has_update_id(), ident(), ident_, build_reqs::reqs, reqs_blueprint, build_reqs::skills, skills_blueprint, string_id< T >::str(), string_format(), build_reqs::time, and time_blueprint.
Referenced by finalize().
create_byproducts()
std::vector< item > recipe::create_byproducts (int batch = 1) const
Definition at line 504 of file recipe.cpp.
{
    std::vector<item> bps;
    for( const auto &e : byproducts ) {
        item obj( e.first, calendar::turn, item::default_charges_tag{} );
        if( obj.has_flag( "VARSIZE" ) ) {
            obj.set_flag( "FIT" );
        }
        if( obj.count_by_charges() ) {
            obj.charges *= e.second * batch;
            bps.push_back( obj );
        } else {
            if( !obj.craft_has_charges() ) {
                obj.charges = 0;
            }
            for( int i = 0; i < e.second * batch; ++i ) {
                bps.push_back( obj );
            }
        }
    }
    return bps;
}
References byproducts, item::charges, item::count_by_charges(), item::craft_has_charges(), item::has_flag(), item::set_flag(), and calendar::turn.
Referenced by player::check_eligible_containers_for_crafting(), and complete_craft().
create_result()
item recipe::create_result () const
Definition at line 456 of file recipe.cpp.
{
    item newit( result_, calendar::turn, item::default_charges_tag{} );
    if( charges ) {
        newit.charges = *charges;
    }
    if( !newit.craft_has_charges() ) {
        newit.charges = 0;
    } else if( result_mult != 1 ) {
        // TODO: Make it work for charge-less items (update makes amount)
        newit.charges *= result_mult;
    }
    // Show crafted items as fitting
    // They might end up not fitting, but it's rare
    if( newit.has_flag( flag_VARSIZE ) ) {
        newit.item_tags.insert( flag_FIT );
    }
    if( contained ) {
        newit = newit.in_container( container );
    }
    return newit;
}
References item::charges, charges, contained, container, flag_FIT(), flag_VARSIZE(), result_, result_mult, and calendar::turn.
Referenced by Character::compute_nutrient_range(), create_results(), get_component_filter(), hot_result(), peek_related_recipe(), and select_crafting_recipe().
create_results()
std::vector< item > recipe::create_results (int batch = 1) const
Definition at line 483 of file recipe.cpp.
{
    std::vector<item> items;
    const bool by_charges = item::count_by_charges( result_ );
    if( contained || !by_charges ) {
        // by_charges items get their charges multiplied in create_result
        const int num_results = by_charges ? batch : batch * result_mult;
        for( int i = 0; i < num_results; i++ ) {
            item newit = create_result();
            items.push_back( newit );
        }
    } else {
        item newit = create_result();
        newit.charges *= batch;
        items.push_back( newit );
    }
    return items;
}
References item::charges, contained, item::count_by_charges(), create_result(), result_, and result_mult.
Referenced by player::check_eligible_containers_for_crafting(), complete_craft(), and basecamp::start_crafting().
deduped_requirements()
const deduped_requirement_data & recipe::deduped_requirements () const inline
Definition at line 73 of file recipe.h.
{
            return deduped_requirements_;
        }
References deduped_requirements_.
Referenced by basecamp::add_available_recipes(), basecamp::available_upgrades(), player::can_make(), player::can_start_craft(), basecamp_action_components::choose_components(), craft_command::execute(), iuse::multicooker(), basecamp::recipe_batch_max(), select_crafting_recipe(), basecamp::start_crafting(), basecamp::start_fortifications(), and basecamp::start_upgrade().
disassembly_batch_size()
int recipe::disassembly_batch_size () const
Returns number of charges of the item needed for single disassembly.
Definition at line 846 of file recipe.cpp.
{
    if( !result_->count_by_charges() ) {
        return 1;
    } else if( charges.has_value() ) {
        return *charges;
    } else {
        return result_->charges_default();
    }
}
References charges, itype::charges_default(), itype::count_by_charges(), and result_.
Referenced by crafting::complete_disassemble(), and prompt_disassemble_in_seq().
disassembly_requirements()
requirement_data recipe::disassembly_requirements () const inline
If recipe can be used for disassembly fetch the combined requirements.
Definition at line 96 of file recipe.h.
{
            if( reversible ) {
                return simple_requirements().disassembly_requirements();
            } else {
                return {};
            }
        }
References requirement_data::disassembly_requirements(), reversible, and simple_requirements().
Referenced by crafting::complete_disassemble(), disassemble_inventory_preset::disassemble_inventory_preset(), item::disassembly_info(), and item::get_uncraft_components().
finalize()
void recipe::finalize ()
Definition at line 326 of file recipe.cpp.
{
    // TODO: Rethink bools used for slow checks
    if( json_report_strict && check_blueprint_needs ) {
        check_blueprint_requirements();
    }
    // concatenate both external and inline requirements
    add_requirements( reqs_external );
    add_requirements( reqs_internal );
    reqs_external.clear();
    reqs_internal.clear();
    if( has_blueprint_needs ) {
        time_blueprint = 0;
        skills_blueprint.clear();
        reqs_blueprint.clear();
    }
    deduped_requirements_ = deduped_requirement_data( requirements_, ident() );
    if( contained && container.is_null() ) {
        container = result_->default_container.value_or( itype_id::NULL_ID() );
    }
    if( autolearn && autolearn_requirements.empty() ) {
        autolearn_requirements = required_skills;
        if( skill_used ) {
            autolearn_requirements[ skill_used ] = difficulty;
        }
    }
    {
        auto it = flags.find( "UNCRAFT_SINGLE_CHARGE" );
        if( it != flags.end() ) {
            flags.erase( it );
            charges = 1;
            if( json_report_strict || !result_->count_by_charges() ) {
                debugmsg( "recipe %s uses obsolete flag UNCRAFT_SINGLE_CHARGE, replace with \"charges\": 1",
                          ident() );
            }
        }
    }
    {
        auto it = flags.find( "UNCRAFT_BY_QUANTITY" );
        if( it != flags.end() ) {
            flags.erase( it );
            if( json_report_strict ) {
                debugmsg( "recipe %s uses obsolete flag UNCRAFT_BY_QUANTITY",
                          ident() );
            }
        }
    }
}
References add_requirements(), autolearn, autolearn_requirements, charges, check_blueprint_needs, check_blueprint_requirements(), contained, container, itype::count_by_charges(), debugmsg, deduped_requirements_, itype::default_container, difficulty, flags, has_blueprint_needs, ident(), string_id< T >::is_null(), json_report_strict, string_id< itype >::NULL_ID(), reqs_blueprint, reqs_external, reqs_internal, required_skills, requirements_, result_, skill_used, skills_blueprint, and time_blueprint.
get_blueprint()
const std::string & recipe::get_blueprint () const
Definition at line 688 of file recipe.cpp.
{
    return blueprint;
}
References blueprint.
Referenced by talk_function::start_camp(), and basecamp::upgrade_return().
get_component_filter()
std::function< bool(const item &)> recipe::get_component_filter (recipe_filter_flags flags = recipe_filter_flags::none) const
Definition at line 639 of file recipe.cpp.
{
    const item result = create_result();
    // Disallow crafting of non-perishables with rotten components
    // Make an exception for items with the ALLOW_ROTTEN flag such as seeds
    const bool recipe_forbids_rotten =
        result.is_food() && !result.goes_bad() && !has_flag( "ALLOW_ROTTEN" );
    const bool flags_forbid_rotten =
        static_cast<bool>( flags & recipe_filter_flags::no_rotten ) && result.goes_bad_after_opening();
    std::function<bool( const item & )> rotten_filter = return_true<item>;
    if( recipe_forbids_rotten || flags_forbid_rotten ) {
        rotten_filter = []( const item & component ) {
            return !component.rotten();
        };
    }
    // Disallow usage of non-full magazines as components
    // This is primarily used to require a fully charged battery, but works for any magazine.
    std::function<bool( const item & )> magazine_filter = return_true<item>;
    if( has_flag( "FULL_MAGAZINE" ) ) {
        magazine_filter = []( const item & component ) {
            return !component.is_magazine() || ( component.ammo_remaining() >= component.ammo_capacity() );
        };
    }
    // Filter out filthy components here instead of with is_crafting_component
    // Make an exception for recipes with the ALLOW_FILTHY flag
    std::function<bool( const item & )> filthy_filter = return_true<item>;
    if( !has_flag( flag_ALLOW_FILTHY ) ) {
        filthy_filter = []( const item & component ) {
            return !component.is_filthy();
        };
    }
    return [ rotten_filter, magazine_filter, filthy_filter ]( const item & component ) {
        return is_crafting_component_allow_filthy( component ) &&
               rotten_filter( component ) &&
               magazine_filter( component ) &&
               filthy_filter( component );
    };
}
References bool, component, create_result(), flag_ALLOW_FILTHY(), flags, has_flag(), is_crafting_component_allow_filthy(), no_rotten, and result().
Referenced by basecamp::add_available_recipes(), basecamp::available_upgrades(), player::can_continue_craft(), player::can_make(), player::can_start_craft(), craft_command::check_item_components_missing(), basecamp::craft_description(), craft_command::create_in_progress_craft(), craft_command::execute(), basecamp::om_upgrade_description(), basecamp::recipe_batch_max(), select_crafting_recipe(), basecamp::start_crafting(), basecamp::start_fortifications(), and basecamp::start_upgrade().
get_consistency_error()
std::string recipe::get_consistency_error () const
Returns a non-empty string describing an inconsistency (if any) in the recipe.
Definition at line 390 of file recipe.cpp.
{
    if( category == "CC_BUILDING" ) {
        if( is_blueprint() || oter_str_id( result_.c_str() ).is_valid() ) {
            return std::string();
        }
        return "defines invalid result";
    }
    if( !result_.is_valid() ) {
        return "defines invalid result";
    }
    if( charges && !item::count_by_charges( result_ ) ) {
        return "specifies charges but result is not counted by charges";
    }
    if( charges && result_mult != 1 ) {
        return "specifies both charges and result_mult";
    }
    if( result_mult != 1 && reversible ) {
        return "is reversible, so can't use result_mult";
    }
    const auto is_invalid_bp = []( const std::pair<itype_id, int> &elem ) {
        return !elem.first.is_valid();
    };
    if( std::any_of( byproducts.begin(), byproducts.end(), is_invalid_bp ) ) {
        return "defines invalid byproducts";
    }
    if( !contained && !container.is_null() ) {
        return "defines container but not contained";
    }
    if( !container.is_valid() ) {
        return "specifies unknown container";
    }
    const auto is_invalid_skill = []( const std::pair<skill_id, int> &elem ) {
        return !elem.first.is_valid();
    };
    if( ( skill_used && !skill_used.is_valid() ) ||
        std::any_of( required_skills.begin(), required_skills.end(), is_invalid_skill ) ) {
        return "uses invalid skill";
    }
    const auto is_invalid_book = []( const std::pair<itype_id, int> &elem ) {
        return !elem.first->book;
    };
    if( std::any_of( booksets.begin(), booksets.end(), is_invalid_book ) ) {
        return "defines invalid book";
    }
    // TODO: IDs instead of raw string
    if( !blueprint.empty() && !mapgen::has_update_id( blueprint ) ) {
        return "has invalid mapgen id";
    }
    return std::string();
}
References blueprint, booksets, byproducts, string_id< T >::c_str(), category, charges, contained, container, item::count_by_charges(), mapgen::has_update_id(), is_blueprint(), string_id< T >::is_null(), string_id< T >::is_valid(), required_skills, result_, result_mult, reversible, and skill_used.
Referenced by recipe_dictionary::finalize_internal().
has_byproducts()
bool recipe::has_byproducts () const
Definition at line 529 of file recipe.cpp.
{
    return !byproducts.empty();
}
References byproducts.
Referenced by complete_craft(), print_items(), and recipe_subset::search_result().
has_flag()
bool recipe::has_flag (const std::string & flag_name) const
Definition at line 92 of file recipe.cpp.
{
    return flags.count( flag_name );
}
References flags.
Referenced by crafting::complete_disassemble(), get_component_filter(), item::inherit_flags(), and lighting_crafting_speed_multiplier().
hot_result()
bool recipe::hot_result () const
Definition at line 807 of file recipe.cpp.
{
    // Check if the recipe tools make this food item hot upon making it.
    // We don't actually know which specific tool the player used/will use here, but
    // we're checking for a class of tools; because of the way requirements
    // processing works, the "surface_heat" id gets nuked into an actual
    // list of tools, see data/json/recipes/cooking_tools.json.
    //
    // Currently it's only checking for a hotplate because that's a
    // suitable item in both the "surface_heat" and "water_boiling_heat"
    // tools, and it's usually the first item in a list of tools so if this
    // does get heated we'll find it right away.
    //
    // TODO: Make this less of a hack
    if( create_result().is_food() ) {
        const requirement_data::alter_tool_comp_vector &tool_lists = simple_requirements().get_tools();
        for( const std::vector<tool_comp> &tools : tool_lists ) {
            for( const tool_comp &t : tools ) {
                if( t.type == itype_hotplate ) {
                    return true;
                }
            }
        }
    }
    return false;
}
References create_result(), requirement_data::get_tools(), itype_hotplate, and simple_requirements().
Referenced by complete_craft(), and Character::compute_nutrient_range().
ident()
const recipe_id & recipe::ident () const inline
Definition at line 77 of file recipe.h.
{
            return ident_;
        }
References ident_.
Referenced by check_blueprint_requirements(), crafting::complete_disassemble(), recipe_subset::contains(), player::craft(), einkpc_download_memory_card(), craft_command::execute(), recipe_subset::favorite(), finalize(), recipe_subset::hidden(), recipe_subset::include(), recipe_dictionary::load(), player::long_craft(), iuse::multicooker(), select_crafting_recipe(), and item::craft_data::serialize().
is_blacklisted()
bool recipe::is_blacklisted () const inline
Definition at line 81 of file recipe.h.
{
            return requirements_.is_blacklisted();
        }
References requirement_data::is_blacklisted(), and requirements_.
Referenced by recipe_dictionary::finalize_internal().
is_blueprint()
bool recipe::is_blueprint () const
Definition at line 683 of file recipe.cpp.
{
    return !blueprint.empty();
}
References blueprint.
Referenced by Item_factory::find_template(), and get_consistency_error().
is_reversible()
bool recipe::is_reversible () const inline
Definition at line 154 of file recipe.h.
{
            return reversible;
        }
References reversible.
Referenced by complete_craft().
load()
void recipe::load (const JsonObject & jo, const std::string & src)
Definition at line 97 of file recipe.cpp.
{
    const bool strict = is_strict_enabled( src );
    abstract = jo.has_string( "abstract" );
    if( abstract ) {
        ident_ = recipe_id( jo.get_string( "abstract" ) );
    } else {
        jo.read( "result", result_, true );
        ident_ = recipe_id( result_.str() );
    }
    if( jo.has_bool( "obsolete" ) ) {
        assign( jo, "obsolete", obsolete );
    }
    if( jo.has_int( "time" ) ) {
        // so we can specify moves that is not a multiple of 100
        time = jo.get_int( "time" );
    } else if( jo.has_string( "time" ) ) {
        time = to_moves<int>( read_from_json_string<time_duration>( *jo.get_raw( "time" ),
                              time_duration::units ) );
    }
    assign( jo, "difficulty", difficulty, strict, 0, MAX_SKILL );
    assign( jo, "flags", flags );
    // automatically set contained if we specify as container
    assign( jo, "contained", contained, strict );
    contained |= assign( jo, "container", container, strict );
    if( jo.has_array( "batch_time_factors" ) ) {
        auto batch = jo.get_array( "batch_time_factors" );
        batch_rscale = batch.get_int( 0 ) / 100.0;
        batch_rsize  = batch.get_int( 1 );
    }
    assign( jo, "charges", charges );
    assign( jo, "result_mult", result_mult );
    assign( jo, "skill_used", skill_used, strict );
    if( difficulty != 0 && !skill_used ) {
        jo.throw_error( "non-zero difficulty, but no skill_used set", "difficulty" );
    }
    if( jo.has_member( "skills_required" ) ) {
        auto sk = jo.get_array( "skills_required" );
        required_skills.clear();
        if( sk.empty() ) {
            // clear all requirements
        } else if( sk.has_array( 0 ) ) {
            // multiple requirements
            for( JsonArray arr : sk ) {
                required_skills[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
            }
        } else {
            // single requirement
            required_skills[skill_id( sk.get_string( 0 ) )] = sk.get_int( 1 );
        }
    }
    // simplified autolearn sets requirements equal to required skills at finalization
    if( jo.has_bool( "autolearn" ) ) {
        assign( jo, "autolearn", autolearn );
    } else if( jo.has_array( "autolearn" ) ) {
        autolearn = true;
        for( JsonArray arr : jo.get_array( "autolearn" ) ) {
            autolearn_requirements[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
        }
    }
    // Never let the player have a debug or NPC recipe
    if( jo.has_bool( "never_learn" ) ) {
        assign( jo, "never_learn", never_learn );
    }
    if( jo.has_member( "decomp_learn" ) ) {
        learn_by_disassembly.clear();
        if( jo.has_int( "decomp_learn" ) ) {
            if( !skill_used ) {
                jo.throw_error( "decomp_learn specified with no skill_used" );
            }
            assign( jo, "decomp_learn", learn_by_disassembly[skill_used] );
        } else if( jo.has_array( "decomp_learn" ) ) {
            for( JsonArray arr : jo.get_array( "decomp_learn" ) ) {
                learn_by_disassembly[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
            }
        }
    }
    if( jo.has_member( "book_learn" ) ) {
        booksets.clear();
        for( JsonArray arr : jo.get_array( "book_learn" ) ) {
            int booklearn_difficulty = arr.size() > 1 ? arr.get_int( 1 ) : -1;
            booksets.emplace( itype_id( arr.get_string( 0 ) ), booklearn_difficulty );
            if( booklearn_difficulty > 0 && !skill_used ) {
                arr.throw_error( "book_learn with >0 skill requirement, but no skill_used set", 1 );
            }
        }
    }
    if( jo.has_member( "delete_flags" ) ) {
        flags_to_delete = jo.get_tags( "delete_flags" );
    }
    // recipes not specifying any external requirements inherit from their parent recipe (if any)
    if( jo.has_string( "using" ) ) {
        reqs_external = { { requirement_id( jo.get_string( "using" ) ), 1 } };
    } else if( jo.has_array( "using" ) ) {
        reqs_external.clear();
        for( JsonArray cur : jo.get_array( "using" ) ) {
            reqs_external.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
        }
    }
    const std::string type = jo.get_string( "type" );
    // inline requirements are always replaced (cannot be inherited)
    reqs_internal.clear();
    // These cannot be inherited
    check_blueprint_needs = false;
    has_blueprint_needs = false;
    time_blueprint = 0;
    skills_blueprint.clear();
    reqs_blueprint.clear();
    if( type == "recipe" ) {
        if( jo.has_string( "id_suffix" ) ) {
            if( abstract ) {
                jo.throw_error( "abstract recipe cannot specify id_suffix", "id_suffix" );
            }
            ident_ = recipe_id( ident_.str() + "_" + jo.get_string( "id_suffix" ) );
        }
        assign( jo, "category", category, strict );
        assign( jo, "subcategory", subcategory, strict );
        assign( jo, "description", description, strict );
        assign( jo, "reversible", reversible, strict );
        if( jo.has_member( "byproducts" ) ) {
            if( this->reversible ) {
                jo.throw_error( "Recipe cannot be reversible and have byproducts" );
            }
            byproducts.clear();
            for( JsonArray arr : jo.get_array( "byproducts" ) ) {
                itype_id byproduct( arr.get_string( 0 ) );
                byproducts[ byproduct ] += arr.size() == 2 ? arr.get_int( 1 ) : 1;
            }
        }
        assign( jo, "construction_blueprint", blueprint );
        if( !blueprint.empty() ) {
            assign( jo, "blueprint_name", bp_name );
            bp_resources.clear();
            for( const std::string resource : jo.get_array( "blueprint_resources" ) ) {
                bp_resources.emplace_back( resource );
            }
            for( JsonObject provide : jo.get_array( "blueprint_provides" ) ) {
                bp_provides.emplace_back( std::make_pair( provide.get_string( "id" ),
                                          provide.get_int( "amount", 1 ) ) );
            }
            // all blueprints provide themselves with needing it written in JSON
            bp_provides.emplace_back( std::make_pair( result_.str(), 1 ) );
            for( JsonObject require : jo.get_array( "blueprint_requires" ) ) {
                bp_requires.emplace_back( std::make_pair( require.get_string( "id" ),
                                          require.get_int( "amount", 1 ) ) );
            }
            // all blueprints exclude themselves with needing it written in JSON
            bp_excludes.emplace_back( std::make_pair( result_.str(), 1 ) );
            for( JsonObject exclude : jo.get_array( "blueprint_excludes" ) ) {
                bp_excludes.emplace_back( std::make_pair( exclude.get_string( "id" ),
                                          exclude.get_int( "amount", 1 ) ) );
            }
            if( jo.has_member( "blueprint_needs" ) ) {
                has_blueprint_needs = true;
                const JsonObject jneeds = jo.get_object( "blueprint_needs" );
                if( jneeds.has_member( "time" ) ) {
                    if( jneeds.has_int( "time" ) ) {
                        // so we can specify moves that is not a multiple of 100
                        time_blueprint = jneeds.get_int( "time" );
                    } else {
                        time_blueprint = to_moves<int>( read_from_json_string<time_duration>( *jneeds.get_raw( "time" ),
                                                        time_duration::units ) );
                    }
                    time += time_blueprint;
                }
                if( jneeds.has_member( "skills" ) ) {
                    for( JsonArray cur : jneeds.get_array( "skills" ) ) {
                        skills_blueprint[skill_id( cur.get_string( 0 ) )] = cur.get_int( 1 );
                    }
                    for( const std::pair<const skill_id, int> &p : skills_blueprint ) {
                        const auto it = required_skills.find( p.first );
                        if( it == required_skills.end() ) {
                            required_skills.emplace( p );
                        } else {
                            it->second = std::max( it->second, p.second );
                        }
                    }
                }
                if( jneeds.has_member( "inline" ) ) {
                    const requirement_id req_id( "inline_blueprint_" + type + "_" + ident_.str() );
                    requirement_data::load_requirement( jneeds.get_object( "inline" ), req_id );
                    reqs_blueprint.emplace_back( req_id, 1 );
                    reqs_internal.emplace_back( req_id, 1 );
                }
            }
            check_blueprint_needs = jo.get_bool( "check_blueprint_needs", true );
        }
    } else if( type == "uncraft" ) {
        reversible = true;
    } else {
        jo.throw_error( "unknown recipe type", "type" );
    }
    if( reversible && time < 1 ) {
        jo.throw_error( "Non-zero time mandatory for reversible recipe or uncraft" );
    }
    const requirement_id req_id( "inline_" + type + "_" + ident_.str() );
    requirement_data::load_requirement( jo, req_id );
    reqs_internal.emplace_back( req_id, 1 );
}
References assign(), autolearn, autolearn_requirements, batch_rscale, batch_rsize, blueprint, booksets, bp_excludes, bp_name, bp_provides, bp_requires, bp_resources, byproducts, category, charges, check_blueprint_needs, contained, container, description, difficulty, flags, flags_to_delete, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_raw(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_array(), has_blueprint_needs, JsonObject::has_bool(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_string(), ident_, is_strict_enabled(), itype_id, learn_by_disassembly, requirement_data::load_requirement(), MAX_SKILL, never_learn, obsolete, JsonObject::read(), reqs_blueprint, reqs_external, reqs_internal, required_skills, result_, result_mult, reversible, skill_id, skill_used, skills_blueprint, src, string_id< T >::str(), subcategory, JsonObject::throw_error(), time, time_blueprint, type, and time_duration::units.
Referenced by recipe_dictionary::load().
makes_amount()
int recipe::makes_amount () const
Returns the amount or charges recipe will produce.
Definition at line 834 of file recipe.cpp.
{
    int makes;
    if( charges.has_value() ) {
        makes = charges.value();
    } else {
        makes = result_->charges_default();
    }
    // return either charges * mult or 1
    return makes ? makes * result_mult : 1 ;
}
References charges, itype::charges_default(), result_, and result_mult.
operator bool()
recipe::operator bool () const inline
Definition at line 44 of file recipe.h.
{
            return !result_.is_null();
        }
References string_id< T >::is_null(), and result_.
primary_skill_string()
std::string recipe::primary_skill_string (const Character * c, bool print_skill_level) const
Definition at line 572 of file recipe.cpp.
{
    std::vector< std::pair<skill_id, int> > skillList;
    if( !skill_used.is_null() ) {
        skillList.push_back( std::pair<skill_id, int>( skill_used, difficulty ) );
    }
    return required_skills_as_string( skillList.begin(), skillList.end(), c, print_skill_level );
}
References c, difficulty, string_id< T >::is_null(), required_skills_as_string(), and skill_used.
required_all_skills_string()
std::string recipe::required_all_skills_string () const
Definition at line 595 of file recipe.cpp.
{
    std::vector<std::pair<skill_id, int>> skillList = sorted_lex( required_skills );
    // There is primary skill used, add it to the front
    if( !skill_used.is_null() ) {
        skillList.insert( skillList.begin(), std::pair<skill_id, int>( skill_used, difficulty ) );
    }
    return required_skills_as_string( skillList.begin(), skillList.end() );
}
References difficulty, string_id< T >::is_null(), required_skills, required_skills_as_string(), skill_used, and sorted_lex().
Referenced by basecamp::om_upgrade_description().
required_skills_string()
std::string recipe::required_skills_string (const Character * c, bool include_primary_skill, bool print_skill_level) const
Definition at line 583 of file recipe.cpp.
{
    std::vector<std::pair<skill_id, int>> skillList = sorted_lex( required_skills );
    // There is primary skill used and it should be included: add it to the beginning
    if( !skill_used.is_null() && include_primary_skill ) {
        skillList.insert( skillList.begin(), std::pair<skill_id, int>( skill_used, difficulty ) );
    }
    return required_skills_as_string( skillList.begin(), skillList.end(), c, print_skill_level );
}
References c, difficulty, string_id< T >::is_null(), required_skills, required_skills_as_string(), skill_used, and sorted_lex().
result()
const itype_id & recipe::result () const inline
Definition at line 48 of file recipe.h.
{
            return result_;
        }
References result_.
Referenced by basecamp::available_upgrades(), complete_craft(), Item_factory::finalize(), Item_factory::finalize_item_blacklist(), get_component_filter(), iuse::multicooker(), and recipe_subset::search_result().
result_name()
std::string recipe::result_name () const
Returns
The name (item::nname) of the resulting item (result).
Definition at line 612 of file recipe.cpp.
{
    std::string name = item::nname( result_ );
    if( uistate.favorite_recipes.find( this->ident() ) != uistate.favorite_recipes.end() ) {
        name = "* " + name;
    }
    return name;
}
References uistatedata::favorite_recipes, om_direction::name(), item::nname(), result_, and uistate.
Referenced by item::book_info(), complete_craft(), iuse::craft(), einkpc_download_memory_card(), iuse::einktabletpc(), craft_command::execute(), talk_effect_fun_t::set_u_learn_recipe(), and basecamp::start_crafting().
simple_requirements()
const requirement_data & recipe::simple_requirements () const inline
Fetch combined requirement data (inline and via "using" syntax).
Use simple_requirements() for player display or when you just want to know the requirements as listed in the json files. Use deduped_requirements() to calculate actual craftability of a recipe.
Definition at line 69 of file recipe.h.
{
            return requirements_;
        }
References requirements_.
Referenced by player::can_continue_craft(), Character::compute_nutrient_range(), basecamp::craft_description(), disassembly_requirements(), recipe_dictionary::find_items_on_loops(), hot_result(), recipe_subset::include(), basecamp::om_upgrade_description(), peek_related_recipe(), and select_crafting_recipe().
will_be_blacklisted()
bool recipe::will_be_blacklisted () const
Definition at line 622 of file recipe.cpp.
{
    if( requirements_.is_blacklisted() ) {
        return true;
    }
    auto any_is_blacklisted = []( const std::vector<std::pair<requirement_id, int>> &reqs ) {
        auto req_is_blacklisted = []( const std::pair<requirement_id, int> &req ) {
            return req.first->is_blacklisted();
        };
        return std::any_of( reqs.begin(), reqs.end(), req_is_blacklisted );
    };
    return any_is_blacklisted( reqs_internal ) || any_is_blacklisted( reqs_external );
}
References requirement_data::is_blacklisted(), reqs_external, reqs_internal, and requirements_.
Referenced by Item_factory::finalize().
Friends And Related Function Documentation
recipe_dictionary
friend class recipe_dictionary friend
Definition at line 36 of file recipe.h.
Member Data Documentation
autolearn
bool recipe::autolearn = false private
set learning requirements equal to required skills at finalization?
Definition at line 196 of file recipe.h.
Referenced by finalize(), and load().
autolearn_requirements
std::map<skill_id, int> recipe::autolearn_requirements
Definition at line 112 of file recipe.h.
Referenced by finalize(), and load().
batch_rscale
double recipe::batch_rscale = 0.0 private
Definition at line 226 of file recipe.h.
Referenced by batch_savings_string(), batch_time(), and load().
batch_rsize
int recipe::batch_rsize = 0 private
Definition at line 227 of file recipe.h.
Referenced by batch_savings_string(), batch_time(), and load().
blueprint
std::string recipe::blueprint private
Definition at line 229 of file recipe.h.
Referenced by check_blueprint_requirements(), get_blueprint(), get_consistency_error(), is_blueprint(), and load().
booksets
std::map<itype_id, int> recipe::booksets
Definition at line 114 of file recipe.h.
Referenced by crafting::get_books_for_recipe(), get_consistency_error(), and load().
bool
abstract recipe::bool = false private
Abstract recipes can be inherited from but are themselves disposed of at finalization.
Definition at line 193 of file recipe.h.
Referenced by get_component_filter().
bp_excludes
std::vector<std::pair<std::string, int> > recipe::bp_excludes private
Definition at line 234 of file recipe.h.
Referenced by blueprint_excludes(), and load().
bp_name
translation recipe::bp_name private
Definition at line 230 of file recipe.h.
Referenced by blueprint_name(), and load().
bp_provides
std::vector<std::pair<std::string, int> > recipe::bp_provides private
Definition at line 232 of file recipe.h.
Referenced by blueprint_provides(), and load().
bp_requires
std::vector<std::pair<std::string, int> > recipe::bp_requires private
Definition at line 233 of file recipe.h.
Referenced by blueprint_requires(), and load().
bp_resources
std::vector<itype_id> recipe::bp_resources private
Definition at line 231 of file recipe.h.
Referenced by blueprint_resources(), and load().
byproducts
std::map<itype_id, int> recipe::byproducts
Definition at line 107 of file recipe.h.
Referenced by Character::compute_nutrient_range(), create_byproducts(), get_consistency_error(), has_byproducts(), load(), print_items(), and recipe_subset::search_result().
category
std::string recipe::category
Definition at line 56 of file recipe.h.
Referenced by crafting_allowed(), get_consistency_error(), recipe_subset::include(), and load().
charges
cata::optional<int> recipe::charges private
If set (zero or positive) set charges of output result for items counted by charges.
Definition at line 222 of file recipe.h.
Referenced by create_result(), disassembly_batch_size(), finalize(), get_consistency_error(), load(), and makes_amount().
check_blueprint_needs
bool recipe::check_blueprint_needs = false private
Definition at line 238 of file recipe.h.
Referenced by finalize(), and load().
contained
bool recipe::contained = false private
Does the item spawn contained in container?
Definition at line 199 of file recipe.h.
Referenced by create_result(), create_results(), finalize(), get_consistency_error(), and load().
container
itype_id recipe::container = itype_id::NULL_ID() private
What does the item spawn contained in? Unset ("null") means default container.
Definition at line 205 of file recipe.h.
Referenced by create_result(), finalize(), get_consistency_error(), and load().
deduped_requirements_
deduped_requirement_data recipe::deduped_requirements_ private
Deduped version constructed from the above requirements_.
Definition at line 217 of file recipe.h.
Referenced by deduped_requirements(), and finalize().
description
translation recipe::description
Definition at line 59 of file recipe.h.
Referenced by Item_factory::find_template(), load(), and basecamp::om_upgrade_description().
difficulty
int recipe::difficulty = 0
Definition at line 62 of file recipe.h.
Referenced by crafting::complete_disassemble(), basecamp::craft_description(), player::craft_skill_gain(), player::crafting_success_roll(), SkillLevelMap::exceeds_recipe_requirements(), finalize(), player::get_available_recipes(), item::get_available_recipes(), recipe_subset::get_custom_difficulty(), player::has_recipe(), recipe_subset::include(), load(), morale_crafting_speed_multiplier(), iuse::multicooker(), primary_skill_string(), required_all_skills_string(), required_skills_string(), player::start_craft(), basecamp::start_upgrade(), and basecamp::upgrade_return().
flags
std::set<std::string> recipe::flags private
Definition at line 219 of file recipe.h.
Referenced by finalize(), get_component_filter(), has_flag(), and load().
flags_to_delete
std::set<std::string> recipe::flags_to_delete
Definition at line 115 of file recipe.h.
Referenced by complete_craft(), item::item(), and load().
has_blueprint_needs
bool recipe::has_blueprint_needs = false private
Blueprint requirements to be checked in unit test.
Definition at line 237 of file recipe.h.
Referenced by finalize(), and load().
ident_
recipe_id recipe::ident_ = recipe_id::NULL_ID() private
Definition at line 190 of file recipe.h.
Referenced by check_blueprint_requirements(), ident(), and load().
learn_by_disassembly
std::map<skill_id, int> recipe::learn_by_disassembly
Definition at line 113 of file recipe.h.
Referenced by Character::can_learn_by_disassembly(), crafting::complete_disassemble(), and load().
never_learn
bool recipe::never_learn = false
Prevent this recipe from ever being added to the player's learned recipies (used for special NPC crafting)
Definition at line 93 of file recipe.h.
Referenced by Character::learn_recipe(), and load().
obsolete
bool recipe::obsolete = false
Definition at line 54 of file recipe.h.
Referenced by Item_factory::finalize(), recipe_dictionary::finalize_internal(), Item_factory::finalize_item_blacklist(), and load().
reqs_blueprint
std::vector<std::pair<requirement_id, int> > recipe::reqs_blueprint private
Definition at line 241 of file recipe.h.
Referenced by check_blueprint_requirements(), finalize(), and load().
reqs_external
std::vector<std::pair<requirement_id, int> > recipe::reqs_external private
External requirements (via "using" syntax) where second field is multiplier.
Definition at line 208 of file recipe.h.
Referenced by finalize(), load(), and will_be_blacklisted().
reqs_internal
std::vector<std::pair<requirement_id, int> > recipe::reqs_internal private
Requires specified inline with the recipe (and replaced upon inheritance)
Definition at line 211 of file recipe.h.
Referenced by finalize(), load(), and will_be_blacklisted().
required_skills
std::map<skill_id, int> recipe::required_skills
Definition at line 110 of file recipe.h.
Referenced by player::crafting_success_roll(), SkillLevelMap::exceeds_recipe_requirements(), finalize(), get_consistency_error(), load(), morale_crafting_speed_multiplier(), required_all_skills_string(), required_skills_string(), basecamp::start_crafting(), basecamp::start_fortifications(), and basecamp::start_upgrade().
requirements_
requirement_data recipe::requirements_ private
Combined requirements cached when recipe finalized.
Definition at line 214 of file recipe.h.
Referenced by add_requirements(), finalize(), is_blacklisted(), simple_requirements(), and will_be_blacklisted().
result_
itype_id recipe::result_ = itype_id::NULL_ID() private
Definition at line 39 of file recipe.h.
Referenced by create_result(), create_results(), disassembly_batch_size(), finalize(), get_consistency_error(), load(), makes_amount(), operator bool(), result(), and result_name().
result_mult
int recipe::result_mult = 1 private
Definition at line 228 of file recipe.h.
Referenced by create_result(), create_results(), get_consistency_error(), load(), and makes_amount().
reversible
bool recipe::reversible = false private
Can recipe be used for disassembly of result via disassembly_requirements.
Definition at line 202 of file recipe.h.
Referenced by disassembly_requirements(), get_consistency_error(), is_reversible(), and load().
skill_used
skill_id recipe::skill_used
Definition at line 109 of file recipe.h.
Referenced by item::book_info(), complete_craft(), crafting::complete_disassemble(), basecamp::craft_description(), player::craft_skill_gain(), player::crafting_success_roll(), SkillLevelMap::exceeds_recipe_requirements(), finalize(), player::get_available_recipes(), item::get_available_recipes(), crafting::get_books_for_recipe(), get_consistency_error(), craft_command::get_skill_id(), player::has_recipe(), load(), morale_crafting_speed_multiplier(), primary_skill_string(), required_all_skills_string(), required_skills_string(), and basecamp::start_upgrade().
skills_blueprint
std::map<skill_id, int> recipe::skills_blueprint private
Definition at line 240 of file recipe.h.
Referenced by check_blueprint_requirements(), finalize(), and load().
src
std::vector<std::pair<recipe_id, mod_id> > recipe::src
Definition at line 52 of file recipe.h.
Referenced by load(), and recipe_dictionary::load().
subcategory
std::string recipe::subcategory
Definition at line 57 of file recipe.h.
Referenced by recipe_subset::in_category(), and load().
time
int recipe::time = 0
Definition at line 61 of file recipe.h.
Referenced by add_disassemblables(), batch_time(), game::butcher(), complete_craft(), item::disassembly_info(), load(), iuse::multicooker(), and disassemble_activity_actor::try_start_single().
time_blueprint
int recipe::time_blueprint = 0 private
Definition at line 239 of file recipe.h.
Referenced by check_blueprint_requirements(), finalize(), and load().
The documentation for this class was generated from the following files:
src/recipe.h
src/recipe.cpp