Cataclysm BN: toggle_gate_activity_actor Class Reference
toggle_gate_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
toggle_gate_activity_actor (int gate_moves, const tripoint &gate_placement)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Private Attributes
int moves_total
tripoint placement
Detailed Description
Definition at line 376 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
toggle_gate_activity_actor()
toggle_gate_activity_actor::toggle_gate_activity_actor (int gate_moves, const tripoint & gate_placement) inline
Definition at line 392 of file activity_actor_definitions.h.
                                                                                     :
            moves_total( gate_moves ), placement( gate_placement ) {}
Member Function Documentation
can_resume_with_internal()
bool toggle_gate_activity_actor::can_resume_with_internal (const activity_actor & other, const Character &) const inline override private virtual
Precondition
other is a toggle_gate_activity_actor
Reimplemented from activity_actor.
Definition at line 385 of file activity_actor_definitions.h.
{
            const toggle_gate_activity_actor &og_actor = static_cast<const toggle_gate_activity_actor &>
                    ( other );
            return placement == og_actor.placement;
        }
References other, and placement.
clone()
std::unique_ptr< activity_actor > toggle_gate_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 403 of file activity_actor_definitions.h.
{
            return std::make_unique<toggle_gate_activity_actor>( *this );
        }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > toggle_gate_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 1116 of file activity_actor.cpp.
{
    toggle_gate_activity_actor actor( 0, tripoint_zero );
    JsonObject data = jsin.get_object();
    data.read( "moves", actor.moves_total );
    data.read( "placement", actor.placement );
    return actor.clone();
}
References clone(), JsonIn::get_object(), moves_total, placement, JsonObject::read(), and tripoint_zero.
do_turn()
void toggle_gate_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 400 of file activity_actor_definitions.h.
{};
finish()
void toggle_gate_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1100 of file activity_actor.cpp.
{
    gates::toggle_gate( placement );
    act.set_to_null();
}
References act, placement, and gates::toggle_gate().
get_type()
activity_id toggle_gate_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 395 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_TOGGLE_GATE" );
        }
serialize()
void toggle_gate_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1106 of file activity_actor.cpp.
{
    jsout.start_object();
    jsout.member( "moves", moves_total );
    jsout.member( "placement", placement );
    jsout.end_object();
}
References JsonOut::end_object(), JsonOut::member(), moves_total, placement, and JsonOut::start_object().
start()
void toggle_gate_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1094 of file activity_actor.cpp.
{
    act.moves_total = moves_total;
    act.moves_left = moves_total;
}
References act, and moves_total.
Member Data Documentation
moves_total
int toggle_gate_activity_actor::moves_total private
Definition at line 379 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
placement
tripoint toggle_gate_activity_actor::placement private
Definition at line 380 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp