Cataclysm BN: dependency_tree Class Reference
dependency_tree Class Reference
#include <dependency_tree.h>
Public Member Functions
dependency_tree ()
void init (std::map< mod_id, std::vector< mod_id > > key_dependency_map, std::map< mod_id, std::vector< mod_id > > key_conflict_map)
void clear ()
std::vector< mod_id > get_dependencies_of_X_as_strings (mod_id key) const
std::vector< dependency_node * > get_dependencies_of_X_as_nodes (mod_id key) const
std::vector< mod_id > get_dependents_of_X_as_strings (mod_id key) const
std::vector< dependency_node * > get_dependents_of_X_as_nodes (mod_id key) const
bool is_available (mod_id key) const
dependency_node * get_node (mod_id key) const
Public Attributes
std::map< mod_id, dependency_node, mod_id::LexCmp > master_node_map
Private Member Functions
void build_node_map (std::map< mod_id, std::vector< mod_id > > key_dependency_map)
void build_connections (std::map< mod_id, std::vector< mod_id > > key_dependency_map, std::map< mod_id, std::vector< mod_id > > key_conflict_map)
void check_for_strongly_connected_components ()
void strong_connect (dependency_node *dnode)
void check_for_conflicting_dependencies ()
Private Attributes
std::vector< std::vector< dependency_node * > > strongly_connected_components
std::stack< dependency_node * > connection_stack
std::vector< dependency_node * > nodes_on_stack
int open_index
Detailed Description
Definition at line 57 of file dependency_tree.h.
Constructor & Destructor Documentation
dependency_tree()
dependency_tree::dependency_tree () default
Member Function Documentation
build_connections()
void dependency_tree::build_connections (std::map< mod_id, std::vector< mod_id > > key_dependency_map, std::map< mod_id, std::vector< mod_id > > key_conflict_map) private
Definition at line 265 of file dependency_tree.cpp.
{
    for( auto &elem : key_dependency_map ) {
        const auto iter = master_node_map.find( elem.first );
        if( iter != master_node_map.end() ) {
            dependency_node *knode = &iter->second;
            // apply parents list
            std::vector<mod_id> vnode_parents = elem.second;
            for( auto &vnode_parent : vnode_parents ) {
                const auto iter = master_node_map.find( vnode_parent );
                if( iter != master_node_map.end() ) {
                    dependency_node *vnode = &iter->second;
                    knode->add_parent( vnode );
                    vnode->add_child( knode );
                } else {
                    // missing dependency!
                    knode->all_errors[node_error_type::missing_dep].push_back( "[" + vnode_parent.str() + "]" );
                }
            }
        }
    }
    for( const std::pair<const mod_id, std::vector<mod_id>> &elem : key_conflict_map ) {
        const auto iter = master_node_map.find( elem.first );
        if( iter != master_node_map.end() ) {
            dependency_node *knode = &iter->second;
            const std::vector<mod_id> &vnode_conflicts = elem.second;
            for( const mod_id &vnode_conflict : vnode_conflicts ) {
                const auto iter = master_node_map.find( vnode_conflict );
                if( iter != master_node_map.end() ) {
                    dependency_node *vnode = &iter->second;
                    knode->add_conflict( vnode );
                    vnode->add_conflict( knode );
                }
            }
        }
    }
    // finalize and check for circular dependencies
    check_for_strongly_connected_components();
    for( auto &elem : master_node_map ) {
        elem.second.inherit_errors();
    }
    // check for conflicts between dependencies
    check_for_conflicting_dependencies();
}
References dependency_node::add_child(), dependency_node::add_conflict(), dependency_node::add_parent(), dependency_node::all_errors, check_for_conflicting_dependencies(), check_for_strongly_connected_components(), master_node_map, and missing_dep.
Referenced by init().
build_node_map()
void dependency_tree::build_node_map (std::map< mod_id, std::vector< mod_id > > key_dependency_map) private
Definition at line 254 of file dependency_tree.cpp.
{
    for( auto &elem : key_dependency_map ) {
        // check to see if the master node map knows the key
        if( master_node_map.find( elem.first ) == master_node_map.end() ) {
            master_node_map.emplace( elem.first, elem.first );
        }
    }
}
References master_node_map.
Referenced by init().
check_for_conflicting_dependencies()
void dependency_tree::check_for_conflicting_dependencies () private
Definition at line 451 of file dependency_tree.cpp.
{
    for( auto &node : master_node_map ) {
        dependency_node *this_node = &node.second;
        std::vector<dependency_node *> all_deps = get_dependencies_of_X_as_nodes( node.first );
        std::sort( all_deps.begin(), all_deps.end(), depnode_comparator );
        for( auto dep_it = all_deps.begin(); dep_it != all_deps.end(); dep_it++ ) {
            const dependency_node *this_dep = *dep_it;
            std::vector<const dependency_node *> this_dep_conflicts = this_dep->conflicts;
            std::sort( this_dep_conflicts.begin(), this_dep_conflicts.end(), depnode_comparator );
            std::vector<const dependency_node *> both;
            std::set_intersection(
                std::next( dep_it ), all_deps.end(),
                this_dep_conflicts.begin(), this_dep_conflicts.end(),
                std::back_inserter( both ), depnode_comparator
            );
            for( const dependency_node *this_dep_conf : both ) {
                //~ Single entry in list of conflicting dependencies, both %s are mod ids.
                //~ Example of final string: "[aftershock] with [classic-zombies]"
                std::string msg = string_format( _( "[%1$s] with [%2$s]" ), this_dep->key, this_dep_conf->key );
                this_node->all_errors[node_error_type::conflicting_deps].push_back( msg );
            }
        }
    }
}
References _, dependency_node::all_errors, both, conflicting_deps, dependency_node::conflicts, depnode_comparator(), get_dependencies_of_X_as_nodes(), dependency_node::key, master_node_map, and string_format().
Referenced by build_connections().
check_for_strongly_connected_components()
void dependency_tree::check_for_strongly_connected_components () private
Definition at line 382 of file dependency_tree.cpp.
{
    strongly_connected_components = std::vector<std::vector<dependency_node * > >();
    open_index = 0;
    connection_stack = std::stack<dependency_node *>();
    for( auto &elem : master_node_map ) {
        //nodes_on_stack = std::vector<dependency_node*>();
        // clear it for the next stack to run
        if( elem.second.index < 0 ) {
            strong_connect( &elem.second );
        }
    }
    for( std::vector<dependency_node *> &list : strongly_connected_components ) {
        if( list.size() <= 1 ) {
            continue;
        }
        std::string err_msg = "/";
        for( const dependency_node *node : list ) {
            err_msg += node->key.str();
            err_msg += "/";
        }
        for( dependency_node *elem : list ) {
            elem->all_errors[node_error_type::cyclic_dep].push_back( err_msg );
        }
    }
}
References connection_stack, cyclic_dep, master_node_map, open_index, strong_connect(), and strongly_connected_components.
Referenced by build_connections().
clear()
void dependency_tree::clear ()
Definition at line 367 of file dependency_tree.cpp.
{
    master_node_map.clear();
}
References master_node_map.
get_dependencies_of_X_as_nodes()
std::vector< dependency_node * > dependency_tree::get_dependencies_of_X_as_nodes (mod_id key) const
Definition at line 330 of file dependency_tree.cpp.
{
    const auto iter = master_node_map.find( key );
    if( iter != master_node_map.end() ) {
        return iter->second.get_dependencies_as_nodes();
    }
    return std::vector<dependency_node *>();
}
References master_node_map.
Referenced by check_for_conflicting_dependencies().
get_dependencies_of_X_as_strings()
std::vector< mod_id > dependency_tree::get_dependencies_of_X_as_strings (mod_id key) const
Definition at line 321 of file dependency_tree.cpp.
{
    const auto iter = master_node_map.find( key );
    if( iter != master_node_map.end() ) {
        return iter->second.get_dependencies_as_strings();
    }
    return std::vector<mod_id>();
}
References master_node_map.
Referenced by mod_ui::can_shift_up(), init::check_mods_for_errors(), and mod_ui::try_add().
get_dependents_of_X_as_nodes()
std::vector< dependency_node * > dependency_tree::get_dependents_of_X_as_nodes (mod_id key) const
Definition at line 348 of file dependency_tree.cpp.
{
    const auto iter = master_node_map.find( key );
    if( iter != master_node_map.end() ) {
        return iter->second.get_dependents_as_nodes();
    }
    return std::vector<dependency_node *>();
}
References master_node_map.
get_dependents_of_X_as_strings()
std::vector< mod_id > dependency_tree::get_dependents_of_X_as_strings (mod_id key) const
Definition at line 339 of file dependency_tree.cpp.
{
    const auto iter = master_node_map.find( key );
    if( iter != master_node_map.end() ) {
        return iter->second.get_dependents_as_strings();
    }
    return std::vector<mod_id>();
}
References master_node_map.
Referenced by mod_ui::can_shift_down(), and mod_ui::try_rem().
get_node()
dependency_node * dependency_tree::get_node (mod_id key) const
Definition at line 372 of file dependency_tree.cpp.
{
    const auto iter = master_node_map.find( key );
    if( iter != master_node_map.end() ) {
        return const_cast<dependency_node *>( &iter->second );
    }
    return nullptr;
}
References master_node_map.
Referenced by init::check_mods_for_errors(), and mod_ui::try_add().
init()
void dependency_tree::init (std::map< mod_id, std::vector< mod_id > > key_dependency_map, std::map< mod_id, std::vector< mod_id > > key_conflict_map)
Definition at line 245 of file dependency_tree.cpp.
{
    build_node_map( key_dependency_map );
    build_connections( key_dependency_map, key_conflict_map );
}
References build_connections(), and build_node_map().
is_available()
bool dependency_tree::is_available (mod_id key) const
Definition at line 357 of file dependency_tree.cpp.
{
    const auto iter = master_node_map.find( key );
    if( iter != master_node_map.end() ) {
        return iter->second.is_available();
    }
    return false;
}
References master_node_map.
Referenced by init::check_mods_for_errors().
strong_connect()
void dependency_tree::strong_connect (dependency_node * dnode) private
Definition at line 412 of file dependency_tree.cpp.
{
    dnode->index = open_index;
    dnode->lowlink = open_index;
    ++open_index;
    connection_stack.push( dnode );
    dnode->on_stack = true;
    for( std::vector<dependency_node *>::iterator it = dnode->parents.begin();
         it != dnode->parents.end(); ++it ) {
        if( ( *it )->index < 0 ) {
            strong_connect( *it );
            dnode->lowlink = std::min( dnode->lowlink, ( *it )->lowlink );
        } else if( ( *it )->on_stack ) {
            dnode->lowlink = std::min( dnode->lowlink, ( *it )->index );
        }
    }
    if( dnode->lowlink == dnode->index ) {
        std::vector<dependency_node *> scc;
        dependency_node *d;
        do {
            d = connection_stack.top();
            scc.push_back( d );
            connection_stack.pop();
            d->on_stack = false;
        } while( dnode->key != d->key );
        strongly_connected_components.push_back( scc );
        dnode->on_stack = false;
    }
}
References connection_stack, dependency_node::index, dependency_node::key, dependency_node::lowlink, dependency_node::on_stack, open_index, dependency_node::parents, strong_connect(), and strongly_connected_components.
Referenced by check_for_strongly_connected_components(), and strong_connect().
Member Data Documentation
connection_stack
std::stack<dependency_node *> dependency_tree::connection_stack private
Definition at line 100 of file dependency_tree.h.
Referenced by check_for_strongly_connected_components(), and strong_connect().
master_node_map
std::map<mod_id, dependency_node, mod_id::LexCmp> dependency_tree::master_node_map
Definition at line 80 of file dependency_tree.h.
Referenced by build_connections(), build_node_map(), check_for_conflicting_dependencies(), check_for_strongly_connected_components(), clear(), get_dependencies_of_X_as_nodes(), get_dependencies_of_X_as_strings(), get_dependents_of_X_as_nodes(), get_dependents_of_X_as_strings(), get_node(), and is_available().
nodes_on_stack
std::vector<dependency_node *> dependency_tree::nodes_on_stack private
Definition at line 101 of file dependency_tree.h.
open_index
int dependency_tree::open_index private
Definition at line 102 of file dependency_tree.h.
Referenced by check_for_strongly_connected_components(), and strong_connect().
strongly_connected_components
std::vector<std::vector<dependency_node * > > dependency_tree::strongly_connected_components private
Definition at line 99 of file dependency_tree.h.
Referenced by check_for_strongly_connected_components(), and strong_connect().
The documentation for this class was generated from the following files:
src/dependency_tree.h
src/dependency_tree.cpp