Cataclysm BN: printf_arg_formatter< OutputIt, Char > Class Template Reference
printf_arg_formatter< OutputIt, Char > Class Template Reference
\rst The printf argument formatter.
#include <fmtlib_printf.h>
Public Types
using iterator = OutputIt
using format_specs = typename base::format_specs
Public Types inherited from detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
using iterator = OutputIt
using char_type = Char
using format_specs = basic_format_specs< Char >
Public Member Functions
printf_arg_formatter (iterator iter, format_specs &specs, context_type &ctx)
\rst Constructs an argument formatter object.
template<typename T , FMT_ENABLE_IF(fmt::detail::is_integral< T >::value) >
iterator operator() (T value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
iterator operator() (T value)
iterator operator() (const char *value)
Formats a null-terminated C string.
iterator operator() (const wchar_t *value)
Formats a null-terminated wide C string.
iterator operator() (basic_string_view< char_type > value)
iterator operator() (monostate value)
iterator operator() (const void *value)
Formats a pointer.
iterator operator() (typename basic_format_arg< context_type >::handle handle)
Formats an argument of a custom (user-defined) type.
Public Member Functions inherited from detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
arg_formatter_base (OutputIt out, format_specs *s, locale_ref loc)
iterator operator() (monostate)
template<typename T , FMT_ENABLE_IF(is_integral< T >::value) >
FMT_INLINE iterator operator() (T value)
iterator operator() (Char value)
iterator operator() (bool value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
iterator operator() (T value)
iterator operator() (const Char *value)
iterator operator() (basic_string_view< Char > value)
iterator operator() (const void *value)
Private Types
using char_type = Char
using base = detail::arg_formatter_base< OutputIt, Char >
using context_type = basic_printf_context< OutputIt, Char >
Private Member Functions
void write_null_pointer (char)
void write_null_pointer (wchar_t)
Private Attributes
context_type & context_
Additional Inherited Members
Protected Member Functions inherited from detail::arg_formatter_base< OutputIt, Char, ErrorHandler >
iterator out ()
format_specs * specs ()
void write (bool value)
void write (const Char *value)
Detailed Description
template<typename OutputIt, typename Char>
class printf_arg_formatter< OutputIt, Char >
\rst The printf argument formatter.
\endrst
Definition at line 235 of file fmtlib_printf.h.
Member Typedef Documentation
base
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::base = detail::arg_formatter_base<OutputIt, Char> private
Definition at line 242 of file fmtlib_printf.h.
char_type
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::char_type = Char private
Definition at line 241 of file fmtlib_printf.h.
context_type
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::context_type = basic_printf_context<OutputIt, Char> private
Definition at line 243 of file fmtlib_printf.h.
format_specs
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::format_specs = typename base::format_specs
Definition at line 258 of file fmtlib_printf.h.
iterator
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::iterator = OutputIt
Definition at line 238 of file fmtlib_printf.h.
Constructor & Destructor Documentation
printf_arg_formatter()
template<typename OutputIt , typename Char > printf_arg_formatter< OutputIt, Char >::printf_arg_formatter (iterator iter, format_specs & specs, context_type & ctx) inline
\rst Constructs an argument formatter object.
buffer* is a reference to the output buffer and specs contains format specifier information for standard argument types. \endrst
Definition at line 267 of file fmtlib_printf.h.
            : base( iter, &specs, detail::locale_ref() ), context_( ctx ) {}
Member Function Documentation
operator()() [1/8]
template<typename OutputIt , typename Char > iterator printf_arg_formatter< OutputIt, Char >::operator() (basic_string_view< char_type > value) inline
Definition at line 330 of file fmtlib_printf.h.
{
            return base::operator()( value );
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()().
operator()() [2/8]
template<typename OutputIt , typename Char > iterator printf_arg_formatter< OutputIt, Char >::operator() (const char * value) inline
Formats a null-terminated C string.
Definition at line 307 of file fmtlib_printf.h.
{
            if( value ) {
                base::operator()( value );
            } else if( this->specs()->type == 'p' ) {
                write_null_pointer( char_type() );
            } else {
                this->write( "(null)" );
            }
            return this->out();
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs(), type, detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
operator()() [3/8]
template<typename OutputIt , typename Char > iterator printf_arg_formatter< OutputIt, Char >::operator() (const void * value) inline
Formats a pointer.
Definition at line 339 of file fmtlib_printf.h.
{
            if( value ) {
                return base::operator()( value );
            }
            this->specs()->type = 0;
            write_null_pointer( char_type() );
            return this->out();
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs(), basic_format_specs< Char >::type, and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
operator()() [4/8]
template<typename OutputIt , typename Char > iterator printf_arg_formatter< OutputIt, Char >::operator() (const wchar_t * value) inline
Formats a null-terminated wide C string.
Definition at line 319 of file fmtlib_printf.h.
{
            if( value ) {
                base::operator()( value );
            } else if( this->specs()->type == 'p' ) {
                write_null_pointer( char_type() );
            } else {
                this->write( L"(null)" );
            }
            return this->out();
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs(), type, detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
operator()() [5/8]
template<typename OutputIt , typename Char > iterator printf_arg_formatter< OutputIt, Char >::operator() (monostate value) inline
Definition at line 334 of file fmtlib_printf.h.
{
            return base::operator()( value );
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()().
operator()() [6/8]
template<typename OutputIt , typename Char > template<typename T , FMT_ENABLE_IF(fmt::detail::is_integral< T >::value) > iterator printf_arg_formatter< OutputIt, Char >::operator() (T value) inline
Definition at line 271 of file fmtlib_printf.h.
{
            // MSVC2013 fails to compile separate overloads for bool and char_type so
            // use std::is_same instead.
            if( std::is_same<T, bool>::value ) {
                format_specs &fmt_specs = *this->specs();
                if( fmt_specs.type != 's' ) {
                    return base::operator()( value ? 1 : 0 );
                }
                fmt_specs.type = 0;
                this->write( value != 0 );
            } else if( std::is_same<T, char_type>::value ) {
                format_specs &fmt_specs = *this->specs();
                if( fmt_specs.type && fmt_specs.type != 'c' ) {
                    return ( *this )( static_cast<int>( value ) );
                }
                fmt_specs.sign = sign::none;
                fmt_specs.alt = false;
                fmt_specs.fill[0] = ' ';  // Ignore '0' flag for char types.
                // align::numeric needs to be overwritten here since the '0' flag is
                // ignored for non-numeric types
                if( fmt_specs.align == align::none || fmt_specs.align == align::numeric ) {
                    fmt_specs.align = align::right;
                }
                return base::operator()( value );
            } else {
                return base::operator()( value );
            }
            return this->out();
        }
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, basic_format_specs< Char >::fill, align::none, sign::none, align::numeric, detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out(), align::right, basic_format_specs< Char >::sign, detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs(), basic_format_specs< Char >::type, and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write().
operator()() [7/8]
template<typename OutputIt , typename Char > template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > iterator printf_arg_formatter< OutputIt, Char >::operator() (T value) inline
Definition at line 302 of file fmtlib_printf.h.
{
            return base::operator()( value );
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()().
operator()() [8/8]
template<typename OutputIt , typename Char > iterator printf_arg_formatter< OutputIt, Char >::operator() (typename basic_format_arg< context_type >::handle handle) inline
Formats an argument of a custom (user-defined) type.
Definition at line 349 of file fmtlib_printf.h.
{
            handle.format( context_.parse_context(), context_ );
            return this->out();
        }
References printf_arg_formatter< OutputIt, Char >::context_, basic_format_arg< Context >::handle::format(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::out(), and basic_printf_context< OutputIt, Char >::parse_context().
write_null_pointer() [1/2]
template<typename OutputIt , typename Char > void printf_arg_formatter< OutputIt, Char >::write_null_pointer (char) inline private
Definition at line 247 of file fmtlib_printf.h.
{
            this->specs()->type = 0;
            this->write( "(nil)" );
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs(), basic_format_specs< Char >::type, and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write().
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
write_null_pointer() [2/2]
template<typename OutputIt , typename Char > void printf_arg_formatter< OutputIt, Char >::write_null_pointer (wchar_t) inline private
Definition at line 252 of file fmtlib_printf.h.
{
            this->specs()->type = 0;
            this->write( L"(nil)" );
        }
References detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::specs(), basic_format_specs< Char >::type, and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write().
Member Data Documentation
context_
template<typename OutputIt , typename Char > context_type& printf_arg_formatter< OutputIt, Char >::context_ private
Definition at line 245 of file fmtlib_printf.h.
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
The documentation for this class was generated from the following file:
src/fmtlib_printf.h