Cataclysm BN: recipe_subset Class Reference
recipe_subset Class Reference
#include <recipe_dictionary.h>
Public Types
enum class search_type {
name , skill , primary_skill , component ,
tool , quality , quality_result , description_result
}
Public Member Functions
recipe_subset ()=default
recipe_subset (const recipe_subset &src, const std::vector< const recipe * > &recipes)
void include (const recipe *r, int custom_difficulty=-1)
Include a recipe to the subset.
void include (const recipe_subset &subset)
template<class Predicate >
void include_if (const recipe_subset &subset, Predicate pred)
Include a recipe to the subset.
bool contains (const recipe &r) const
Check if the subset contains a recipe with the specified id.
int get_custom_difficulty (const recipe *r) const
Get custom difficulty for the recipe.
bool empty_category (const std::string &cat, const std::string &subcat=std::string()) const
Check if there is any recipes in given category (optionally restricted to subcategory)
std::vector< const recipe * > in_category (const std::string &cat, const std::string &subcat=std::string()) const
Get all recipes in given category (optionally restricted to subcategory)
const std::set< const recipe * > & of_component (const itype_id &id) const
Returns all recipes which could use component.
std::vector< const recipe * > favorite () const
Find marked favorite recipes.
std::vector< const recipe * > recent () const
Find recently used recipes.
std::vector< const recipe * > hidden () const
Find hidden recipes.
std::vector< const recipe * > search (const std::string &txt, search_type key=search_type::name) const
Find recipes matching query (left anchored partial matches are supported)
recipe_subset reduce (const std::string &txt, search_type key=search_type::name) const
Find recipes matching query and return a new recipe_subset.
recipe_subset intersection (const recipe_subset &subset) const
Set intersection between recipe_subsets.
recipe_subset difference (const recipe_subset &subset) const
Set difference between recipe_subsets.
std::vector< const recipe * > search_result (const itype_id &item) const
Find recipes producing the item.
size_t size () const
void clear ()
std::set< constrecipe * >::const_iterator begin () const
std::set< constrecipe * >::const_iterator end () const
Private Attributes
std::set< const recipe * > recipes
std::map< const recipe *, int > difficulties
std::map< std::string, std::set< const recipe * > > category
std::map< itype_id, std::set< const recipe * > > component
std::unordered_set< recipe_id > ids
Detailed Description
Definition at line 79 of file recipe_dictionary.h.
Member Enumeration Documentation
search_type
enum class recipe_subset::search_type strong
Enumerator
name
skill
primary_skill
component
tool
quality
quality_result
description_result
Definition at line 129 of file recipe_dictionary.h.
{
            name,
            skill,
            primary_skill,
            component,
            tool,
            quality,
            quality_result,
            description_result
        };
Constructor & Destructor Documentation
recipe_subset() [1/2]
recipe_subset::recipe_subset () default
Referenced by difference(), intersection(), and reduce().
recipe_subset() [2/2]
recipe_subset::recipe_subset (const recipe_subset & src, const std::vector< const recipe * > & recipes)
Definition at line 207 of file recipe_dictionary.cpp.
{
    for( const auto elem : recipes ) {
        include( elem, src.get_custom_difficulty( elem ) );
    }
}
References get_custom_difficulty(), include(), and recipes.
Member Function Documentation
begin()
std::set< constrecipe * >::const_iterator recipe_subset::begin () const inline
Definition at line 172 of file recipe_dictionary.h.
{
            return recipes.begin();
        }
References recipes.
Referenced by difference(), intersection(), and select_crafting_recipe().
clear()
void recipe_subset::clear () inline
Definition at line 165 of file recipe_dictionary.h.
                     {
            component.clear();
            category.clear();
            recipes.clear();
            ids.clear();
        }
References category, ids, and recipes.
Referenced by deserialize(), and select_crafting_recipe().
contains()
bool recipe_subset::contains (const recipe & r) const inline
Check if the subset contains a recipe with the specified id.
Definition at line 106 of file recipe_dictionary.h.
{
            return ids.count( r.ident() ) != 0;
        }
References recipe::ident(), and ids.
Referenced by Character::knows_recipe().
difference()
recipe_subset recipe_subset::difference (const recipe_subset & subset) const
Set difference between recipe_subsets.
Definition at line 225 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> difference_result;
    std::set_difference( this->begin(), this->end(), subset.begin(), subset.end(),
                         std::back_inserter( difference_result ) );
    return recipe_subset( *this, difference_result );
}
References begin(), end(), and recipe_subset().
Referenced by select_crafting_recipe().
empty_category()
bool recipe_subset::empty_category (const std::string & cat, const std::string & subcat = std::string()) const
Check if there is any recipes in given category (optionally restricted to subcategory)
Definition at line 248 of file recipe_dictionary.cpp.
{
    if( subcat == "CSC_*_FAVORITE" ) {
        return uistate.favorite_recipes.empty();
    } else if( subcat == "CSC_*_RECENT" ) {
        return uistate.recent_recipes.empty();
    } else if( subcat == "CSC_*_HIDDEN" ) {
        return uistate.hidden_recipes.empty();
    }
    auto iter = category.find( cat );
    if( iter != category.end() ) {
        if( subcat.empty() ) {
            return false;
        } else {
            for( auto &e : iter->second ) {
                if( e->subcategory == subcat ) {
                    return false;
                }
            }
        }
    }
    return true;
}
References category, uistatedata::favorite_recipes, uistatedata::hidden_recipes, uistatedata::recent_recipes, and uistate.
Referenced by draw_recipe_subtabs().
end()
std::set< constrecipe * >::const_iterator recipe_subset::end () const inline
Definition at line 176 of file recipe_dictionary.h.
{
            return recipes.end();
        }
References recipes.
Referenced by difference(), intersection(), and select_crafting_recipe().
favorite()
std::vector< const recipe * > recipe_subset::favorite () const
Find marked favorite recipes.
Definition at line 117 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> res;
    std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
        if( !*r || r->obsolete ) {
            return false;
        }
        return uistate.favorite_recipes.find( r->ident() ) != uistate.favorite_recipes.end();
    } );
    return res;
}
References uistatedata::favorite_recipes, recipe::ident(), recipes, and uistate.
Referenced by select_crafting_recipe().
get_custom_difficulty()
int recipe_subset::get_custom_difficulty (const recipe * r) const
Get custom difficulty for the recipe.
Returns
Either custom difficulty if it was specified, or recipe default difficulty.
Definition at line 545 of file recipe_dictionary.cpp.
{
    const auto iter = difficulties.find( r );
    if( iter != difficulties.end() ) {
        return iter->second;
    }
    return r->difficulty;
}
References difficulties, and recipe::difficulty.
Referenced by include(), and recipe_subset().
hidden()
std::vector< const recipe * > recipe_subset::hidden () const
Find hidden recipes.
Definition at line 131 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> res;
    std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
        if( !*r || r->obsolete ) {
            return false;
        }
        return uistate.hidden_recipes.find( r->ident() ) != uistate.hidden_recipes.end();
    } );
    return res;
}
References uistatedata::hidden_recipes, recipe::ident(), recipes, and uistate.
in_category()
std::vector< const recipe * > recipe_subset::in_category (const std::string & cat, const std::string & subcat = std::string()) const
Get all recipes in given category (optionally restricted to subcategory)
Definition at line 273 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> res;
    auto iter = category.find( cat );
    if( iter != category.end() ) {
        if( subcat.empty() ) {
            std::copy_if( iter->second.begin(), iter->second.end(),
            std::back_inserter( res ), [&]( const recipe * e ) {
                return !e->obsolete;
            } );
        } else {
            std::copy_if( iter->second.begin(), iter->second.end(),
            std::back_inserter( res ), [&subcat]( const recipe * e ) {
                if( e->obsolete ) {
                    return false;
                }
                return e->subcategory == subcat;
            } );
        }
    }
    return res;
}
References category, and recipe::subcategory.
include() [1/2]
void recipe_subset::include (const recipe * r, int custom_difficulty = -1)
Include a recipe to the subset.
Parameters
r recipe to include
custom_difficulty If specified, it defines custom difficulty for the recipe
Definition at line 502 of file recipe_dictionary.cpp.
{
    if( custom_difficulty < 0 ) {
        custom_difficulty = r->difficulty;
    }
    // We always prefer lower difficulty for the subset, but we save it only if it's not default
    if( recipes.count( r ) > 0 ) {
        const auto iter = difficulties.find( r );
        // See if we need to lower the difficulty of the existing recipe
        if( iter != difficulties.end() && custom_difficulty < iter->second ) {
            if( custom_difficulty != r->difficulty ) {
                iter->second = custom_difficulty; // Added again with lower difficulty
            } else {
                difficulties.erase( iter ); // No need to keep the default difficulty. Free some memory
            }
        } else if( custom_difficulty < r->difficulty ) {
            difficulties[r] = custom_difficulty; // Added again with lower difficulty
        }
    } else {
        // add recipe to category and component caches
        for( const auto &opts : r->simple_requirements().get_components() ) {
            for( const item_comp &comp : opts ) {
                component[comp.type].insert( r );
            }
        }
        category[r->category].insert( r );
        // Set the difficulty is it's not the default
        if( custom_difficulty != r->difficulty ) {
            difficulties[r] = custom_difficulty;
        }
        // insert the recipe
        recipes.insert( r );
        ids.insert( r->ident() );
    }
}
References recipe::category, category, difficulties, recipe::difficulty, requirement_data::get_components(), recipe::ident(), ids, recipes, second, and recipe::simple_requirements().
Referenced by deserialize(), game::dump_stats(), player::get_available_recipes(), player::get_recipes_from_books(), include(), include_if(), and recipe_subset().
include() [2/2]
void recipe_subset::include (const recipe_subset & subset)
Definition at line 538 of file recipe_dictionary.cpp.
{
    for( const auto &elem : subset ) {
        include( elem, subset.get_custom_difficulty( elem ) );
    }
}
References get_custom_difficulty(), and include().
include_if()
template<class Predicate > void recipe_subset::include_if (const recipe_subset & subset, Predicate pred) inline
Include a recipe to the subset.
Based on the condition.
Parameters
subset Where to included the recipe
pred Unary predicate that accepts a recipe.
Definition at line 97 of file recipe_dictionary.h.
{
            for( const auto &elem : subset ) {
                if( pred( *elem ) ) {
                    include( elem );
                }
            }
        }
References include().
Referenced by player::get_available_recipes().
intersection()
recipe_subset recipe_subset::intersection (const recipe_subset & subset) const
Set intersection between recipe_subsets.
Definition at line 218 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> intersection_result;
    std::set_intersection( this->begin(), this->end(), subset.begin(), subset.end(),
                           std::back_inserter( intersection_result ) );
    return recipe_subset( *this, intersection_result );
}
References begin(), end(), and recipe_subset().
Referenced by select_crafting_recipe().
of_component()
const std::set< const recipe * > & recipe_subset::of_component (const itype_id & id) const
Returns all recipes which could use component.
Definition at line 297 of file recipe_dictionary.cpp.
{
    auto iter = component.find( id );
    return iter != component.end() ? iter->second : null_match;
}
References null_match.
Referenced by item::final_info(), and peek_related_recipe().
recent()
std::vector< const recipe * > recipe_subset::recent () const
Find recently used recipes.
Definition at line 145 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> res;
    for( auto rec_id = uistate.recent_recipes.rbegin(); rec_id != uistate.recent_recipes.rend();
         ++rec_id ) {
        std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ),
        [&rec_id]( const recipe * r ) {
            return *r && !( *rec_id != r->ident() || r->obsolete );
        } );
    }
    return res;
}
References uistatedata::recent_recipes, recipes, and uistate.
reduce()
recipe_subset recipe_subset::reduce (const std::string & txt, search_type key = search_type::name) const
Find recipes matching query and return a new recipe_subset.
Definition at line 214 of file recipe_dictionary.cpp.
{
    return recipe_subset( *this, search( txt, key ) );
}
References recipe_subset(), and search().
Referenced by select_crafting_recipe().
search()
std::vector< const recipe * > recipe_subset::search (const std::string & txt, search_type key = search_type::name) const
Find recipes matching query (left anchored partial matches are supported)
Definition at line 159 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> res;
    std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
        if( !*r || r->obsolete ) {
            return false;
        }
        switch( key ) {
            case search_type::name:
                return lcmatch( r->result_name(), txt );
            case search_type::skill:
                return lcmatch( r->required_skills_string( nullptr, true, false ), txt );
            case search_type::primary_skill:
                return lcmatch( r->skill_used->name(), txt );
            case search_type::component:
                return search_reqs( r->simple_requirements().get_components(), txt );
            case search_type::tool:
                return search_reqs( r->simple_requirements().get_tools(), txt );
            case search_type::quality:
                return search_reqs( r->simple_requirements().get_qualities(), txt );
            case search_type::quality_result: {
                const auto &quals = r->result()->qualities;
                return std::any_of( quals.begin(), quals.end(), [&]( const std::pair<quality_id, int> &e ) {
                    return lcmatch( e.first->name, txt );
                } );
            }
            case search_type::description_result: {
                const item result = r->create_result();
                return lcmatch( remove_color_tags( result.info( true ) ), txt );
            }
            default:
                return false;
        }
    } );
    return res;
}
References description_result, and recipes.
Referenced by reduce().
search_result()
std::vector< const recipe * > recipe_subset::search_result (const itype_id & item) const
Find recipes producing the item.
Definition at line 233 of file recipe_dictionary.cpp.
{
    std::vector<const recipe *> res;
    std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
        if( r->obsolete ) {
            return false;
        }
        return item == r->result() ||
               ( r->has_byproducts() && r->byproducts.find( item ) != r->byproducts.end() );
    } );
    return res;
}
References recipe::byproducts, recipe::has_byproducts(), recipes, and recipe::result().
size()
size_t recipe_subset::size () const inline
Definition at line 161 of file recipe_dictionary.h.
{
            return recipes.size();
        }
References recipes.
Member Data Documentation
category
std::map<std::string, std::set<const recipe *> > recipe_subset::category private
Definition at line 183 of file recipe_dictionary.h.
Referenced by clear(), empty_category(), in_category(), and include().
component
std::map<itype_id, std::set<const recipe *> > recipe_subset::component private
Definition at line 184 of file recipe_dictionary.h.
difficulties
std::map<const recipe *, int> recipe_subset::difficulties private
Definition at line 182 of file recipe_dictionary.h.
Referenced by get_custom_difficulty(), and include().
ids
std::unordered_set<recipe_id> recipe_subset::ids private
Definition at line 185 of file recipe_dictionary.h.
Referenced by clear(), contains(), and include().
recipes
std::set<const recipe *> recipe_subset::recipes private
Definition at line 181 of file recipe_dictionary.h.
Referenced by begin(), clear(), end(), favorite(), hidden(), include(), recent(), recipe_subset(), search(), search_result(), and size().
The documentation for this class was generated from the following files:
src/recipe_dictionary.h
src/recipe_dictionary.cpp