Cataclysm BN: overmap_connection::subtype Class Reference
overmap_connection::subtype Class Reference
#include <overmap_connection.h>
Public Types
enum class flag { orthogonal }
Public Member Functions
bool allows_terrain (const oter_id &oter) const
bool allows_turns () const
bool is_orthogonal () const
void load (const JsonObject &jo)
void deserialize (JsonIn &jsin)
Public Attributes
oter_type_str_id terrain
int basic_cost = 0
Private Attributes
friend overmap_connection
std::set< overmap_location_id > locations
std::set< flag > flags
Detailed Description
Definition at line 20 of file overmap_connection.h.
Member Enumeration Documentation
flag
enum class overmap_connection::subtype::flag strong
Enumerator
orthogonal
Definition at line 25 of file overmap_connection.h.
{ orthogonal };
Member Function Documentation
allows_terrain()
bool overmap_connection::subtype::allows_terrain (const oter_id & oter) const
Definition at line 38 of file overmap_connection.cpp.
{
    if( oter->type_is( terrain ) ) {
        return true;    // Can be built on similar terrains.
    }
    return std::any_of( locations.cbegin(),
    locations.cend(), [&oter]( const overmap_location_id & elem ) {
        return elem->test( oter );
    } );
}
References locations, terrain, and oter_t::type_is().
allows_turns()
bool overmap_connection::subtype::allows_turns () const inline
Definition at line 33 of file overmap_connection.h.
{
                    return terrain->is_linear();
                }
References oter_type_t::is_linear(), and terrain.
Referenced by overmap::lay_out_connection().
deserialize()
void overmap_connection::subtype::deserialize (JsonIn & jsin)
Definition at line 61 of file overmap_connection.cpp.
{
    JsonObject jo = jsin.get_object();
    load( jo );
}
References JsonIn::get_object(), and overmap_connection::load().
is_orthogonal()
bool overmap_connection::subtype::is_orthogonal () const inline
Definition at line 37 of file overmap_connection.h.
{
                    return flags.count( flag::orthogonal );
                }
References flags, and orthogonal.
Referenced by overmap::lay_out_connection().
load()
void overmap_connection::subtype::load (const JsonObject & jo)
Definition at line 50 of file overmap_connection.cpp.
{
    const auto flag_reader = make_flag_reader( connection_subtype_flag_map, "connection subtype flag" );
    mandatory( jo, false, "terrain", terrain );
    mandatory( jo, false, "locations", locations );
    optional( jo, false, "basic_cost", basic_cost, 0 );
    optional( jo, false, "flags", flags, flag_reader );
}
References connection_subtype_flag_map, anonymous_namespace{overmap_location.cpp}::locations, make_flag_reader(), mandatory(), optional(), and terrain.
Member Data Documentation
basic_cost
int overmap_connection::subtype::basic_cost = 0
Definition at line 30 of file overmap_connection.h.
Referenced by overmap::lay_out_connection().
flags
std::set<flag> overmap_connection::subtype::flags private
Definition at line 46 of file overmap_connection.h.
Referenced by is_orthogonal().
locations
std::set<overmap_location_id> overmap_connection::subtype::locations private
Definition at line 45 of file overmap_connection.h.
Referenced by allows_terrain(), and overmap_connection::check().
overmap_connection
friend overmap_connection::subtype::overmap_connection private
Definition at line 22 of file overmap_connection.h.
terrain
oter_type_str_id overmap_connection::subtype::terrain
Definition at line 28 of file overmap_connection.h.
Referenced by allows_terrain(), allows_turns(), overmap::build_connection(), and overmap_connection::check().
The documentation for this class was generated from the following files:
src/overmap_connection.h
src/overmap_connection.cpp