Cataclysm BN: weigh_self_actor Class Reference
weigh_self_actor Class Reference
Weigh yourself on a bathroom scale.
#include <iuse_actor.h>
Public Member Functions
weigh_self_actor (const std::string &type="weigh_self")
~weigh_self_actor () override=default
void load (const JsonObject &jo) override
int use (player &p, item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
units::mass max_weight
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Weigh yourself on a bathroom scale.
or something.
Definition at line 1221 of file iuse_actor.h.
Constructor & Destructor Documentation
weigh_self_actor()
weigh_self_actor::weigh_self_actor (const std::string & type = "weigh_self") inline
Definition at line 1227 of file iuse_actor.h.
: iuse_actor(type) {}
~weigh_self_actor()
weigh_self_actor::~weigh_self_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > weigh_self_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4707 of file iuse_actor.cpp.
{
    return std::make_unique<weigh_self_actor>( *this );
}
info()
void weigh_self_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 4680 of file iuse_actor.cpp.
{
    dump.emplace_back( "DESCRIPTION",
                       _( "Use this item to weigh yourself.  Includes everything you are wearing." ) );
}
References _.
load()
void weigh_self_actor::load (const JsonObject & jo) override virtual
Implements iuse_actor.
Definition at line 4702 of file iuse_actor.cpp.
{
    assign( jo, "max_weight", max_weight );
}
References assign().
use()
int weigh_self_actor::use (player & p, item & , bool , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 4686 of file iuse_actor.cpp.
{
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot weigh yourself while mounted." ) );
        return 0;
    }
    // this is a weight, either in kgs or in lbs.
    double weight = convert_weight( p.get_weight() );
    if( weight > convert_weight( max_weight ) ) {
        popup( _( "ERROR: Max weight of %.0f %s exceeded" ), convert_weight( max_weight ), weight_units() );
    } else {
        popup( "%.0f %s", weight, weight_units() );
    }
    return 0;
}
References _, player::add_msg_if_player(), convert_weight(), Character::get_weight(), Character::is_mounted(), m_info, popup(), and weight_units().
Member Data Documentation
max_weight
units::mass weigh_self_actor::max_weight
Definition at line 1225 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp