Cataclysm BN: RemovePartHandler Class Reference
RemovePartHandler Class Reference abstract
Public Member Functions
virtual ~RemovePartHandler ()=default
virtual void unboard (const tripoint &loc)=0
virtual void add_item_or_charges (const tripoint &loc, item it, bool permit_oob)=0
virtual void set_transparency_cache_dirty (int z)=0
virtual void set_floor_cache_dirty (int z)=0
virtual void removed (vehicle &veh, int part)=0
virtual void spawn_animal_from_part (item &base, const tripoint &loc)=0
Detailed Description
Definition at line 119 of file vehicle.cpp.
Constructor & Destructor Documentation
~RemovePartHandler()
virtual RemovePartHandler::~RemovePartHandler () virtual default
Member Function Documentation
add_item_or_charges()
virtual void RemovePartHandler::add_item_or_charges (const tripoint & loc, item it, bool permit_oob) pure virtual
Implemented in MapgenRemovePartHandler, and DefaultRemovePartHandler.
Referenced by vehicle::remove_part().
removed()
virtual void RemovePartHandler::removed (vehicle & veh, int part) pure virtual
Implemented in DefaultRemovePartHandler, and MapgenRemovePartHandler.
Referenced by vehicle::remove_part().
set_floor_cache_dirty()
virtual void RemovePartHandler::set_floor_cache_dirty (int z) pure virtual
Implemented in DefaultRemovePartHandler, and MapgenRemovePartHandler.
Referenced by vehicle::remove_part().
set_transparency_cache_dirty()
virtual void RemovePartHandler::set_transparency_cache_dirty (int z) pure virtual
Implemented in DefaultRemovePartHandler, and MapgenRemovePartHandler.
Referenced by vehicle::remove_part().
spawn_animal_from_part()
virtual void RemovePartHandler::spawn_animal_from_part (item & base, const tripoint & loc) pure virtual
Implemented in MapgenRemovePartHandler, and DefaultRemovePartHandler.
Referenced by vehicle::remove_part().
unboard()
virtual void RemovePartHandler::unboard (const tripoint & loc) pure virtual
Implemented in MapgenRemovePartHandler, and DefaultRemovePartHandler.
Referenced by vehicle::remove_part().
The documentation for this class was generated from the following file:
src/vehicle.cpp