Cataclysm BN: job_data Class Reference
job_data Class Reference
#include <npc.h>
Public Member Functions
bool set_task_priority (const activity_id &task, int new_priority)
void clear_all_priorities ()
bool has_job () const
int get_priority_of_job (const activity_id &req_job) const
std::vector< activity_id > get_prioritised_vector () const
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Private Attributes
std::map< activity_id, int > task_priorities
Detailed Description
Definition at line 116 of file npc.h.
Member Function Documentation
clear_all_priorities()
void job_data::clear_all_priorities () inline
Definition at line 140 of file npc.h.
{
            for( auto &elem : task_priorities ) {
                elem.second = 0;
            }
        }
References task_priorities.
Referenced by basecamp::job_assignment_ui(), talk_function::leave(), and npc::mutiny().
deserialize()
void job_data::deserialize (JsonIn & jsin)
Definition at line 1391 of file savegame_json.cpp.
{
    if( jsin.test_object() ) {
        JsonObject jo = jsin.get_object();
        jo.allow_omitted_members();
        jo.read( "task_priorities", task_priorities );
    }
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), JsonObject::read(), task_priorities, and JsonIn::test_object().
get_prioritised_vector()
std::vector< activity_id > job_data::get_prioritised_vector () const inline
Definition at line 161 of file npc.h.
{
            std::vector<std::pair<activity_id, int>> pairs( begin( task_priorities ), end( task_priorities ) );
            std::vector<activity_id> ret;
            sort( begin( pairs ), end( pairs ), []( const std::pair<activity_id, int> &a,
            const std::pair<activity_id, int> &b ) {
                return a.second > b.second;
            } );
            for( std::pair<activity_id, int> elem : pairs ) {
                ret.push_back( elem.first );
            }
            return ret;
        }
References a, b, cata::hash64_detail::ret, and task_priorities.
Referenced by npc::find_job_to_perform(), and basecamp::job_assignment_ui().
get_priority_of_job()
int job_data::get_priority_of_job (const activity_id & req_job) const inline
Definition at line 153 of file npc.h.
{
            auto it = task_priorities.find( req_job );
            if( it != task_priorities.end() ) {
                return it->second;
            } else {
                return 0;
            }
        }
References task_priorities.
Referenced by npc::find_job_to_perform(), and basecamp::job_assignment_ui().
has_job()
bool job_data::has_job () const inline
Definition at line 145 of file npc.h.
{
            for( auto &elem : task_priorities ) {
                if( elem.second > 0 ) {
                    return true;
                }
            }
            return false;
        }
References task_priorities.
Referenced by npc::has_job().
serialize()
void job_data::serialize (JsonOut & json) const
Definition at line 1385 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "task_priorities", task_priorities );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and task_priorities.
set_task_priority()
bool job_data::set_task_priority (const activity_id & task, int new_priority) inline
Definition at line 132 of file npc.h.
{
            auto it = task_priorities.find( task );
            if( it != task_priorities.end() ) {
                task_priorities[task] = new_priority;
                return true;
            }
            return false;
        }
References task_priorities.
Referenced by basecamp::job_assignment_ui().
Member Data Documentation
task_priorities
std::map<activity_id, int> job_data::task_priorities private
Initial value:
= {
            { activity_id( "ACT_MULTIPLE_BUTCHER" ), 0 },
            { activity_id( "ACT_MULTIPLE_CONSTRUCTION" ), 0 },
            { activity_id( "ACT_VEHICLE_REPAIR" ), 0 },
            { activity_id( "ACT_VEHICLE_DECONSTRUCTION" ), 0 },
            { activity_id( "ACT_MULTIPLE_FARM" ), 0 },
            { activity_id( "ACT_MULTIPLE_CHOP_TREES" ), 0 },
            { activity_id( "ACT_MULTIPLE_CHOP_PLANKS" ), 0 },
            { activity_id( "ACT_MULTIPLE_FISH" ), 0 },
            { activity_id( "ACT_MOVE_LOOT" ), 0 },
            { activity_id( "ACT_TIDY_UP" ), 0 },
        }
Definition at line 119 of file npc.h.
Referenced by clear_all_priorities(), deserialize(), get_prioritised_vector(), get_priority_of_job(), has_job(), serialize(), and set_task_priority().
The documentation for this class was generated from the following files:
src/npc.h
src/savegame_json.cpp