Cataclysm BN: inventory Class Reference
inventory Class Reference
#include <inventory.h>
Public Member Functions
invslice slice ()
const_invslice const_slice () const
const std::list< item > & const_stack (int i) const
size_t size () const
inventory ()
inventory (inventory &&)=default
inventory (const inventory &)=default
inventory & operator= (inventory &&)=default
inventory & operator= (const inventory &)=default
inventory & operator+= (const inventory &rhs)
inventory & operator+= (const item &rhs)
inventory & operator+= (const std::list< item > &rhs)
inventory & operator+= (const std::vector< item > &rhs)
inventory & operator+= (const item_stack &rhs)
inventory operator+ (const inventory &rhs)
inventory operator+ (const item &rhs)
inventory operator+ (const std::list< item > &rhs)
void unsort ()
void clear ()
void push_back (const std::list< item > &newits)
item & add_item (item newit, bool keep_invlet=false, bool assign_invlet=true, bool should_stack=true)
item & add_item_by_items_type_cache (item newit, bool keep_invlet=false, bool assign_invlet=true, bool should_stack=true)
void add_item_keep_invlet (item newit)
void push_back (item newit)
void restack (player &p)
void form_from_zone (map &m, std::unordered_set< tripoint > &zone_pts, const Character *pl=nullptr, bool assign_invlet=true)
void form_from_map (const tripoint &origin, int range, const Character *pl=nullptr, bool assign_invlet=true, bool clear_path=true)
void form_from_map (map &m, const tripoint &origin, int range, const Character *pl=nullptr, bool assign_invlet=true, bool clear_path=true)
void form_from_map (map &m, std::vector< tripoint > pts, const Character *pl, bool assign_invlet=true)
item remove_item (const item *it)
Remove a specific item from the inventory.
item remove_item (int position)
std::list< item > remove_randomly_by_volume (const units::volume &volume)
Randomly select items until the volume quota is filled.
std::list< item > reduce_stack (int position, int quantity)
const item & find_item (int position) const
item & find_item (int position)
int position_by_item (const item *it) const
Returns the item position of the stack that contains the given item (compared by pointers).
int position_by_type (const itype_id &type) const
int invlet_to_position (char invlet) const
Return the item position of the item with given invlet, return INT_MIN if the inventory does not have such an item with that invlet.
std::list< item > use_amount (itype_id it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >)
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
int leak_level (const std::string &flag) const
int worst_item_value (npc *p) const
bool has_enough_painkiller (int pain) const
item * most_appropriate_painkiller (int pain)
void rust_iron_items ()
units::mass weight () const
units::mass weight_without (const excluded_stacks &without) const
units::volume volume () const
units::volume volume_without (const excluded_stacks &without) const
void dump (std::vector< item * > &dest)
std::vector< item * > active_items ()
void json_load_invcache (JsonIn &jsin)
void json_load_items (JsonIn &jsin)
void json_save_invcache (JsonOut &json) const
void json_save_items (JsonOut &json) const
void assign_empty_invlet (item &it, const Character &p, bool force=false)
void reassign_item (item &it, char invlet, bool remove_old=true)
void update_invlet (item &it, bool assign_invlet=true)
void set_stack_favorite (int position, bool favorite)
invlets_bitset allocated_invlets () const
const itype_bin & get_binned_items () const
Returns visitable items binned by their itype.
void update_cache_with_item (item &newit)
void copy_invlet_of (const inventory &other)
enchantment get_active_enchantment_cache (const Character &owner) const
int count_item (const itype_id &item_type) const
void update_quality_cache ()
const std::map< quality_id, std::map< int, int > > & get_quality_cache () const
void build_items_type_cache ()
Public Member Functions inherited from visitable< inventory >
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
Traverses this object and any child items contained using a visitor pattern.
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
Lightweight version which provides only the current node.
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
item * find_parent (const item &it)
Determine the immediate parent container (if any) for an item.
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
Returns vector of parent containers (if any) starting with the innermost.
std::vector< const item * > parents (const item &it) const
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, std::function< void(int)> visitor=nullptr) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX)
Removes items contained by this instance which match the filter.
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Attributes
friend visitable< inventory >
std::map< char, itype_id > assigned_invlet
Private Member Functions
char find_usable_cached_invlet (const itype_id &item_type)
Private Attributes
invlet_favorites invlet_cache
invstack items
std::map< itype_id, std::list< std::list< item > * > > items_type_cache
std::map< quality_id, std::map< int, int > > quality_cache
bool items_type_cached = false
bool binned = false
itype_bin binned_items
Items binned by their type.
Additional Inherited Members
Related Functions inherited from visitable< inventory >
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
item * find_parent (const item &it)
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
std::vector< const item * > parents (const item &it) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
Detailed Description
Definition at line 89 of file inventory.h.
Constructor & Destructor Documentation
inventory() [1/3]
inventory::inventory () default
Referenced by operator+().
inventory() [2/3]
inventory::inventory (inventory &&) default
inventory() [3/3]
inventory::inventory (const inventory &) default
Member Function Documentation
active_items()
std::vector< item * > inventory::active_items ()
Definition at line 1086 of file inventory.cpp.
{
    std::vector<item *> ret;
    for( std::list<item> &elem : items ) {
        for( item &elem_stack_iter : elem ) {
            if( elem_stack_iter.needs_processing() ) {
                ret.push_back( &elem_stack_iter );
            }
        }
    }
    return ret;
}
References items, and cata::hash64_detail::ret.
Referenced by player::process_items().
add_item()
item & inventory::add_item (item newit, bool keep_invlet = false, bool assign_invlet = true, bool should_stack = true)
Definition at line 285 of file inventory.cpp.
{
    binned = false;
    items_type_cached = false;
    if( should_stack ) {
        // See if we can't stack this item.
        for( auto &elem : items ) {
            std::list<item>::iterator it_ref = elem.begin();
            if( it_ref->stacks_with( newit ) ) {
                if( it_ref->merge_charges( newit ) ) {
                    return *it_ref;
                }
                if( it_ref->invlet == '\0' ) {
                    if( !keep_invlet ) {
                        update_invlet( newit, assign_invlet );
                    }
                    update_cache_with_item( newit );
                    it_ref->invlet = newit.invlet;
                } else {
                    newit.invlet = it_ref->invlet;
                }
                elem.push_back( newit );
                return elem.back();
            } else if( keep_invlet && assign_invlet && it_ref->invlet == newit.invlet &&
                       it_ref->invlet != '\0' ) {
                // If keep_invlet is true, we'll be forcing other items out of their current invlet.
                assign_empty_invlet( *it_ref, g->u );
            }
        }
    }
    // Couldn't stack the item, proceed.
    if( !keep_invlet ) {
        update_invlet( newit, assign_invlet );
    }
    update_cache_with_item( newit );
    items.push_back( {newit} );
    return items.back().back();
}
References assign_empty_invlet(), binned, g, item::invlet, items, items_type_cached, update_cache_with_item(), and update_invlet().
Referenced by add_item_keep_invlet(), are_requirements_nearby(), Character::can_pick_volume(), Character::die(), basecamp::form_crafting_inventory(), Character::i_add(), tutorial_game::init(), om_set_hide_site(), operator+=(), push_back(), restack(), iuse::smoking(), and player::wear().
add_item_by_items_type_cache()
item & inventory::add_item_by_items_type_cache (item newit, bool keep_invlet = false, bool assign_invlet = true, bool should_stack = true)
Definition at line 337 of file inventory.cpp.
{
    binned = false;
    if( !items_type_cached ) {
        debugmsg( "Tried to add item to inventory using cache without building the items_type_cache." );
        build_items_type_cache();
    }
    itype_id type = newit.typeId();
    if( should_stack ) {
        // See if we can't stack this item.
        for( auto &elem : items_type_cache[type] ) {
            auto it_ref = elem->begin();
            if( it_ref->stacks_with( newit, false, true ) ) {
                if( it_ref->merge_charges( newit ) ) {
                    return *it_ref;
                }
                if( it_ref->invlet == '\0' ) {
                    if( !keep_invlet ) {
                        update_invlet( newit, assign_invlet );
                    }
                    update_cache_with_item( newit );
                    it_ref->invlet = newit.invlet;
                } else {
                    newit.invlet = it_ref->invlet;
                }
                elem->push_back( newit );
                return elem->back();
            } else if( keep_invlet && assign_invlet && it_ref->invlet == newit.invlet &&
                       it_ref->invlet != '\0' ) {
                // If keep_invlet is true, we'll be forcing other items out of their current invlet.
                assign_empty_invlet( *it_ref, g->u );
            }
        }
    }
    // Couldn't stack the item, proceed.
    if( !keep_invlet ) {
        update_invlet( newit, assign_invlet );
    }
    update_cache_with_item( newit );
    items.push_back( {newit} );
    items_type_cache[type].push_back( &items.back() );
    return items.back().back();
}
References assign_empty_invlet(), binned, build_items_type_cache(), debugmsg, g, item::invlet, items, items_type_cache, items_type_cached, type, item::typeId(), update_cache_with_item(), and update_invlet().
Referenced by form_from_map().
add_item_keep_invlet()
void inventory::add_item_keep_invlet (item newit)
Definition at line 384 of file inventory.cpp.
{
    add_item( newit, true );
}
References add_item().
Referenced by Character::dispose_item(), npc::dispose_item(), and player::takeoff().
allocated_invlets()
invlets_bitset inventory::allocated_invlets () const
Definition at line 1258 of file inventory.cpp.
{
    invlets_bitset invlets;
    for( const auto &stack : items ) {
        const char invlet = stack.front().invlet;
        invlets.set( invlet );
    }
    invlets[0] = false;
    return invlets;
}
References items.
Referenced by Character::allocated_invlets().
assign_empty_invlet()
void inventory::assign_empty_invlet (item & it, const Character & p, bool force = false)
Definition at line 1148 of file inventory.cpp.
{
    const std::string auto_setting = get_option<std::string>( "AUTO_INV_ASSIGN" );
    if( auto_setting == "disabled" || ( ( auto_setting == "favorites" ) && !it.is_favorite ) ) {
        return;
    }
    invlets_bitset cur_inv = p.allocated_invlets();
    itype_id target_type = it.typeId();
    for( auto iter : assigned_invlet ) {
        if( iter.second == target_type && !cur_inv[iter.first] ) {
            it.invlet = iter.first;
            return;
        }
    }
    if( cur_inv.count() < inv_chars.size() ) {
        // XXX YUCK I don't know how else to get the keybindings
        // FIXME: Find a better way to get bound keys
        avatar &u = g->u;
        inventory_selector selector( u );
        std::vector<char> binds = selector.all_bound_keys();
        for( const auto &inv_char : inv_chars ) {
            if( assigned_invlet.count( inv_char ) ) {
                // don't overwrite assigned keys
                continue;
            }
            if( std::find( binds.begin(), binds.end(), inv_char ) != binds.end() ) {
                // don't auto-assign bound keys
                continue;
            }
            if( !cur_inv[inv_char] ) {
                it.invlet = inv_char;
                return;
            }
        }
    }
    if( !force ) {
        it.invlet = 0;
        return;
    }
    // No free hotkey exist, re-use some of the existing ones
    for( auto &elem : items ) {
        item &o = elem.front();
        if( o.invlet != 0 ) {
            it.invlet = o.invlet;
            o.invlet = 0;
            return;
        }
    }
    debugmsg( "could not find a hotkey for %s", it.tname() );
}
References inventory_selector::all_bound_keys(), Character::allocated_invlets(), assigned_invlet, debugmsg, detail::find(), g, inv_chars(), item::invlet, item::is_favorite, items, item::tname(), and item::typeId().
Referenced by add_item(), add_item_by_items_type_cache(), Character::i_add_or_drop(), iuse::radiocar(), restack(), set_item_inventory(), and update_invlet().
build_items_type_cache()
void inventory::build_items_type_cache ()
Definition at line 327 of file inventory.cpp.
{
    items_type_cache.clear();
    for( auto &elem : items ) {
        itype_id type = elem.front().typeId();
        items_type_cache[type].push_back( &elem );
    }
    items_type_cached = true;
}
References items, items_type_cache, items_type_cached, and type.
Referenced by add_item_by_items_type_cache(), and form_from_map().
clear()
void inventory::clear ()
Definition at line 237 of file inventory.cpp.
{
    items.clear();
    binned = false;
    items_type_cached = false;
}
References binned, items, and items_type_cached.
Referenced by debug_menu::character_edit_menu(), talk_function::companion_return(), basecamp::finish_return(), basecamp::form_crafting_inventory(), Character::load(), npc::randomize(), npc::shop_restock(), and starting_inv().
const_slice()
const_invslice inventory::const_slice () const
Definition at line 142 of file inventory.cpp.
{
    const_invslice stacks;
    for( const auto &item : items ) {
        stacks.push_back( &item );
    }
    return stacks;
}
References items.
Referenced by behavior::character_oracle_t::can_make_fire(), behavior::character_oracle_t::can_wear_warmer_clothes(), Character::drop_invalid_inventory(), and player::get_recipes_from_books().
const_stack()
const std::list< item > & inventory::const_stack (int i) const
Definition at line 151 of file inventory.cpp.
{
    if( i < 0 || i >= static_cast<int>( items.size() ) ) {
        debugmsg( "Attempted to access stack %d in an inventory (size %d)", i, items.size() );
        static const std::list<item> nullstack{};
        return nullstack;
    }
    invstack::const_iterator iter = items.begin();
    for( int j = 0; j < i; ++j ) {
        ++iter;
    }
    return *iter;
}
References debugmsg, and items.
Referenced by talk_function::companion_return(), player::consume(), convert_to_items(), basecamp::finish_return(), player::get_eligible_containers_for_crafting(), and operator+=().
copy_invlet_of()
void inventory::copy_invlet_of (const inventory & other)
Definition at line 1289 of file inventory.cpp.
{
    assigned_invlet = other.assigned_invlet;
    invlet_cache = other.invlet_cache;
}
References assigned_invlet, invlet_cache, and other.
count_item()
int inventory::count_item (const itype_id & item_type) const
Definition at line 1134 of file inventory.cpp.
{
    int num = 0;
    const itype_bin bin = get_binned_items();
    if( bin.find( item_type ) == bin.end() ) {
        return num;
    }
    const std::list<const item *> items = get_binned_items().find( item_type )->second;
    for( const item *it : items ) {
        num += it->count();
    }
    return num;
}
References get_binned_items(), items, and num.
Referenced by select_crafting_recipe().
dump()
void inventory::dump (std::vector< item * > & dest)
Definition at line 788 of file inventory.cpp.
{
    for( auto &elem : items ) {
        for( auto &elem_stack_iter : elem ) {
            dest.push_back( &elem_stack_iter );
        }
    }
}
References items.
Referenced by Character::inv_dump(), mission::is_complete(), and mission::wrap_up().
find_item() [1/2]
item & inventory::find_item (int position)
Definition at line 809 of file inventory.cpp.
{
    return const_cast<item &>( const_cast<const inventory *>( this )->find_item( position ) );
}
References find_item().
find_item() [2/2]
const item & inventory::find_item (int position) const
Definition at line 797 of file inventory.cpp.
{
    if( position < 0 || position >= static_cast<int>( items.size() ) ) {
        return null_item_reference();
    }
    invstack::const_iterator iter = items.begin();
    for( int j = 0; j < position; ++j ) {
        ++iter;
    }
    return iter->front();
}
References items, and null_item_reference().
Referenced by find_item(), findBestGasDiscount(), npc::heal_self(), Character::i_at(), player::process_items(), and npc::wield().
find_usable_cached_invlet()
char inventory::find_usable_cached_invlet (const itype_id & item_type) private
Definition at line 267 of file inventory.cpp.
{
    // Some of our preferred letters might already be used.
    for( auto invlet : invlet_cache.invlets_for( item_type ) ) {
        // Don't overwrite user assignments.
        if( assigned_invlet.count( invlet ) ) {
            continue;
        }
        // Check if anything is using this invlet.
        if( g->u.invlet_to_item( invlet ) != nullptr ) {
            continue;
        }
        return invlet;
    }
    return 0;
}
References assigned_invlet, g, invlet_cache, and invlet_favorites::invlets_for().
Referenced by update_invlet().
form_from_map() [1/3]
void inventory::form_from_map (const tripoint & origin, int range, const Character * pl = nullptr, bool assign_invlet = true, bool clear_path = true)
Definition at line 472 of file inventory.cpp.
{
    form_from_map( g->m, origin, range, pl, assign_invlet, clear_path );
}
References form_from_map(), and g.
Referenced by player::can_continue_craft(), iuse_transform::can_use(), player::consume_items(), player::consume_tools(), player::craft_consume_tools(), Character::crafting_inventory(), craft_command::create_in_progress_craft(), craft_command::execute(), form_from_map(), form_from_zone(), mill_load_food(), veh_utils::repair_part(), smoker_load_food(), and Character::suffer_from_asthma().
form_from_map() [2/3]
void inventory::form_from_map (map & m, const tripoint & origin, int range, const Character * pl = nullptr, bool assign_invlet = true, bool clear_path = true)
Definition at line 489 of file inventory.cpp.
{
    // populate a grid of spots that can be reached
    std::vector<tripoint> reachable_pts = {};
    // If we need a clear path we care about the reachability of points
    if( clear_path ) {
        m.reachable_flood_steps( reachable_pts, origin, range, 1, 100 );
    } else {
        // Fill reachable points with points_in_radius
        tripoint_range<tripoint> in_radius = m.points_in_radius( origin, range );
        for( const tripoint &p : in_radius ) {
            reachable_pts.emplace_back( p );
        }
    }
    form_from_map( m, reachable_pts, pl, assign_invlet );
}
References form_from_map(), map::points_in_radius(), and map::reachable_flood_steps().
form_from_map() [3/3]
void inventory::form_from_map (map & m, std::vector< tripoint > pts, const Character * pl, bool assign_invlet = true)
Definition at line 508 of file inventory.cpp.
{
    const time_point bday = calendar::start_of_cataclysm;
    items.clear();
    build_items_type_cache();
    for( const tripoint &p : pts ) {
        if( m.has_furn( p ) ) {
            const furn_t &f = m.furn( p ).obj();
            const itype *type = f.crafting_pseudo_item_type();
            if( type != nullptr ) {
                const itype *ammo = f.crafting_ammo_item_type();
                item furn_item( type, calendar::turn, 0 );
                furn_item.set_flag( "PSEUDO" );
                if( furn_item.has_flag( "USES_GRID_POWER" ) ) {
                    // TODO: The grid tracker should correspond to map!
                    auto &grid = get_distribution_grid_tracker().grid_at( tripoint_abs_ms( m.getabs( p ) ) );
                    furn_item.charges = grid.get_resource();
                } else {
                    furn_item.charges = ammo ? count_charges_in_list( ammo, m.i_at( p ) ) : 0;
                }
                add_item_by_items_type_cache( furn_item );
            }
        }
        if( m.has_items( p ) && m.accessible_items( p ) ) {
            bool allow_liquids = m.has_flag_ter_or_furn( "LIQUIDCONT", p );
            for( auto &i : m.i_at( p ) ) {
                // if it's *the* player requesting this from from map inventory
                // then don't allow items owned by another faction to be factored into recipe components etc.
                if( pl && !i.is_owned_by( *pl, true ) ) {
                    continue;
                }
                if( allow_liquids || !i.made_of( LIQUID ) ) {
                    add_item_by_items_type_cache( i, false, assign_invlet );
                }
            }
        }
        // Kludges for now!
        if( m.has_nearby_fire( p, 0 ) ) {
            item fire( "fire", bday );
            fire.charges = 1;
            add_item_by_items_type_cache( fire );
        }
        // Handle any water from infinite map sources.
        item water = m.water_from( p );
        if( !water.is_null() ) {
            add_item_by_items_type_cache( water );
        }
        // kludge that can probably be done better to check specifically for toilet water to use in
        // crafting
        if( m.furn( p ).obj().examine == &iexamine::toilet ) {
            // get water charges at location
            auto toilet = m.i_at( p );
            auto water = toilet.end();
            for( auto candidate = toilet.begin(); candidate != toilet.end(); ++candidate ) {
                if( candidate->typeId() == itype_water ) {
                    water = candidate;
                    break;
                }
            }
            if( water != toilet.end() && water->charges > 0 ) {
                add_item_by_items_type_cache( *water );
            }
        }
        // WARNING: The part below has a bug that's currently quite minor
        // When a vehicle has multiple faucets in range, available water is
        //  multiplied by the number of faucets.
        // Same thing happens for all other tools and resources, but not cargo
        const optional_vpart_position vp = m.veh_at( p );
        if( !vp ) {
            continue;
        }
        vehicle *const veh = &vp->vehicle();
        //Adds faucet to kitchen stuff; may be horribly wrong to do such....
        //ShouldBreak into own variable
        const cata::optional<vpart_reference> kpart = vp.part_with_feature( "KITCHEN", true );
        const cata::optional<vpart_reference> faupart = vp.part_with_feature( "FAUCET", true );
        const cata::optional<vpart_reference> weldpart = vp.part_with_feature( "WELDRIG", true );
        const cata::optional<vpart_reference> craftpart = vp.part_with_feature( "CRAFTRIG", true );
        const cata::optional<vpart_reference> forgepart = vp.part_with_feature( "FORGE", true );
        const cata::optional<vpart_reference> kilnpart = vp.part_with_feature( "KILN", true );
        const cata::optional<vpart_reference> chempart = vp.part_with_feature( "CHEMLAB", true );
        const cata::optional<vpart_reference> autoclavepart = vp.part_with_feature( "AUTOCLAVE", true );
        const cata::optional<vpart_reference> cargo = vp.part_with_feature( "CARGO", true );
        if( cargo ) {
            const auto items = veh->get_items( cargo->part_index() );
            for( const auto &it : items ) {
                add_item_by_items_type_cache( it, false, false );
            }
        }
        if( faupart ) {
            for( const auto &it : veh->fuels_left() ) {
                item fuel( it.first, bday );
                if( fuel.made_of( LIQUID ) ) {
                    fuel.charges = it.second;
                    add_item_by_items_type_cache( fuel );
                }
            }
        }
        if( kpart ) {
            item hotplate( "hotplate", bday );
            hotplate.charges = veh->fuel_left( itype_battery, true );
            hotplate.item_tags.insert( "PSEUDO" );
            // TODO: Allow disabling
            hotplate.item_tags.insert( "HEATS_FOOD" );
            add_item_by_items_type_cache( hotplate );
            item pot( "pot", bday );
            pot.set_flag( "PSEUDO" );
            add_item_by_items_type_cache( pot );
            item pan( "pan", bday );
            pan.set_flag( "PSEUDO" );
            add_item_by_items_type_cache( pan );
        }
        if( weldpart ) {
            item welder( "welder", bday );
            welder.charges = veh->fuel_left( itype_battery, true );
            welder.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( welder );
            item soldering_iron( "soldering_iron", bday );
            soldering_iron.charges = veh->fuel_left( itype_battery, true );
            soldering_iron.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( soldering_iron );
        }
        if( craftpart ) {
            item vac_sealer( "vac_sealer", bday );
            vac_sealer.charges = veh->fuel_left( itype_battery, true );
            vac_sealer.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( vac_sealer );
            item dehydrator( "dehydrator", bday );
            dehydrator.charges = veh->fuel_left( itype_battery, true );
            dehydrator.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( dehydrator );
            item food_processor( "food_processor", bday );
            food_processor.charges = veh->fuel_left( itype_battery, true );
            food_processor.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( food_processor );
            item press( "press", bday );
            press.charges = veh->fuel_left( itype_battery, true );
            press.set_flag( "PSEUDO" );
            add_item_by_items_type_cache( press );
        }
        if( forgepart ) {
            item forge( "forge", bday );
            forge.charges = veh->fuel_left( itype_battery, true );
            forge.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( forge );
        }
        if( kilnpart ) {
            item kiln( "kiln", bday );
            kiln.charges = veh->fuel_left( itype_battery, true );
            kiln.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( kiln );
        }
        if( chempart ) {
            item chemistry_set( "chemistry_set", bday );
            chemistry_set.charges = veh->fuel_left( itype_battery, true );
            chemistry_set.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( chemistry_set );
            item electrolysis_kit( "electrolysis_kit", bday );
            electrolysis_kit.charges = veh->fuel_left( itype_battery, true );
            electrolysis_kit.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( electrolysis_kit );
        }
        if( autoclavepart ) {
            item autoclave( "autoclave", bday );
            autoclave.charges = veh->fuel_left( itype_battery, true );
            autoclave.item_tags.insert( "PSEUDO" );
            add_item_by_items_type_cache( autoclave );
        }
    }
    pts.clear();
}
References map::accessible_items(), add_item_by_items_type_cache(), itype::ammo, iuse::autoclave(), build_items_type_cache(), item::charges, count_charges_in_list(), furn_t::crafting_ammo_item_type(), furn_t::crafting_pseudo_item_type(), map_data_common_t::examine, fire(), itype::fuel, vehicle::fuel_left(), vehicle::fuels_left(), map::furn(), get_distribution_grid_tracker(), vehicle::get_items(), map::getabs(), distribution_grid_tracker::grid_at(), item::has_flag(), map::has_flag_ter_or_furn(), map::has_furn(), map::has_items(), map::has_nearby_fire(), map::i_at(), cata::flat_set< T, Compare, Data >::insert(), item::is_null(), item::item_tags, items, itype_battery, itype_water, LIQUID, int_id< T >::obj(), optional_vpart_position::part_with_feature(), item::set_flag(), calendar::start_of_cataclysm, iexamine::toilet(), calendar::turn, type, map::veh_at(), and map::water_from().
form_from_zone()
void inventory::form_from_zone (map & m, std::unordered_set< tripoint > & zone_pts, const Character * pl = nullptr, bool assign_invlet = true)
Definition at line 479 of file inventory.cpp.
{
    std::vector<tripoint> pts;
    for( const tripoint &elem : zone_pts ) {
        pts.push_back( m.getlocal( elem ) );
    }
    form_from_map( m, pts, pl, assign_invlet );
}
References form_from_map(), and map::getlocal().
Referenced by basecamp::form_crafting_inventory().
get_active_enchantment_cache()
enchantment inventory::get_active_enchantment_cache (const Character & owner) const
Definition at line 1099 of file inventory.cpp.
{
    enchantment temp_cache;
    for( const std::list<item> &elem : items ) {
        for( const item &check_item : elem ) {
            for( const enchantment &ench : check_item.get_enchantments() ) {
                if( ench.is_active( owner, check_item ) ) {
                    temp_cache.force_add( ench );
                }
            }
        }
    }
    return temp_cache;
}
References enchantment::force_add(), and items.
get_binned_items()
const itype_bin & inventory::get_binned_items () const
Returns visitable items binned by their itype.
May not contain items that wouldn't be visited by visitable methods.
Definition at line 1270 of file inventory.cpp.
{
    if( binned ) {
        return binned_items;
    }
    binned_items.clear();
    // HACK: Hack warning
    inventory *this_nonconst = const_cast<inventory *>( this );
    this_nonconst->visit_items( [ this ]( item * e ) {
        binned_items[ e->typeId() ].push_back( e );
        return VisitResponse::NEXT;
    } );
    binned = true;
    return binned_items;
}
References binned, binned_items, NEXT, item::typeId(), and visitable< T >::visit_items().
Referenced by count_item().
get_quality_cache()
const std::map< quality_id, std::map< int, int > > & inventory::get_quality_cache () const
Definition at line 1129 of file inventory.cpp.
{
    return quality_cache;
}
References quality_cache.
has_charges()
bool inventory::has_charges (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>) const
Definition at line 890 of file inventory.cpp.
{
    return ( charges_of( it, INT_MAX, filter ) >= quantity );
}
References visitable< inventory >::charges_of().
Referenced by craft_command::check_item_components_missing(), craft_command::check_tool_components_missing(), player::craft_consume_tools(), crafting::find_tool_component(), wash_activity_actor::finish(), repair_item_actor::handle_components(), item_comp::has(), mission::is_complete(), Character::suffer_from_asthma(), vehicle::use_washing_machine(), and wash_items().
has_components()
bool inventory::has_components (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>) const
Definition at line 884 of file inventory.cpp.
{
    return has_amount( it, quantity, false, filter );
}
References visitable< inventory >::has_amount().
Referenced by craft_command::check_item_components_missing(), item_comp::has(), and player::select_item_component().
has_enough_painkiller()
bool inventory::has_enough_painkiller (int pain) const
Definition at line 927 of file inventory.cpp.
{
    for( const auto &elem : items ) {
        const item &it = elem.front();
        if( ( pain <= 35 && it.typeId() == itype_aspirin ) ||
            ( pain >= 50 && it.typeId() == itype_oxycodone ) ||
            it.typeId() == itype_tramadol || it.typeId() == itype_codeine ) {
            return true;
        }
    }
    return false;
}
References items, itype_aspirin, itype_codeine, itype_oxycodone, itype_tramadol, pain, and item::typeId().
Referenced by npc::has_painkiller().
has_tools()
bool inventory::has_tools (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>) const
Definition at line 878 of file inventory.cpp.
{
    return has_amount( it, quantity, true, filter );
}
References visitable< inventory >::has_amount().
Referenced by craft_command::check_tool_components_missing(), player::craft_consume_tools(), crafting::find_tool_component(), and tool_comp::has().
invlet_to_position()
int inventory::invlet_to_position (char invlet) const
Return the item position of the item with given invlet, return INT_MIN if the inventory does not have such an item with that invlet.
Don't use this on npcs inventory.
Definition at line 814 of file inventory.cpp.
{
    int i = 0;
    for( const auto &elem : items ) {
        if( elem.begin()->invlet == invlet ) {
            return i;
        }
        ++i;
    }
    return INT_MIN;
}
References items.
json_load_invcache()
void inventory::json_load_invcache (JsonIn & jsin)
Definition at line 1726 of file savegame_json.cpp.
{
    try {
        std::unordered_map<itype_id, std::string> map;
        for( JsonObject jo : jsin.get_array() ) {
            jo.allow_omitted_members();
            for( const JsonMember member : jo ) {
                std::string invlets;
                for( const int i : member.get_array() ) {
                    invlets.push_back( i );
                }
                map[itype_id( member.name() )] = invlets;
            }
        }
        invlet_cache = { map };
    } catch( const JsonError &jsonerr ) {
        debugmsg( "bad invcache json:\n%s", jsonerr.c_str() );
    }
}
References JsonError::c_str(), debugmsg, JsonIn::get_array(), itype_id, and mapgen_defer::member.
Referenced by avatar::load().
json_load_items()
void inventory::json_load_items (JsonIn & jsin)
Definition at line 1760 of file savegame_json.cpp.
{
    jsin.start_array();
    while( !jsin.end_array() ) {
        item tmp;
        tmp.deserialize( jsin );
        add_item( tmp, true, false );
    }
}
References item::deserialize(), JsonIn::end_array(), and JsonIn::start_array().
Referenced by Character::load().
json_save_invcache()
void inventory::json_save_invcache (JsonOut & json) const
Definition at line 1707 of file savegame_json.cpp.
{
    json.start_array();
    for( const auto &elem : invlet_cache.get_invlets_by_id() ) {
        json.start_object();
        json.member( elem.first.str() );
        json.start_array();
        for( const auto &_sym : elem.second ) {
            json.write( static_cast<int>( _sym ) );
        }
        json.end_array();
        json.end_object();
    }
    json.end_array();
}
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), JsonOut::start_array(), JsonOut::start_object(), and JsonOut::write().
Referenced by avatar::store().
json_save_items()
void inventory::json_save_items (JsonOut & json) const
Definition at line 1749 of file savegame_json.cpp.
{
    json.start_array();
    for( const auto &elem : items ) {
        for( const auto &elem_stack_iter : elem ) {
            elem_stack_iter.serialize( json );
        }
    }
    json.end_array();
}
References JsonOut::end_array(), and JsonOut::start_array().
Referenced by player::store().
leak_level()
int inventory::leak_level (const std::string & flag) const
Definition at line 896 of file inventory.cpp.
{
    int ret = 0;
    for( const auto &elem : items ) {
        for( const auto &elem_stack_iter : elem ) {
            if( elem_stack_iter.has_flag( flag ) ) {
                if( elem_stack_iter.has_flag( flag_LEAK_ALWAYS ) ) {
                    ret += elem_stack_iter.volume() / units::legacy_volume_factor;
                } else if( elem_stack_iter.has_flag( flag_LEAK_DAM ) && elem_stack_iter.damage() > 0 ) {
                    ret += elem_stack_iter.damage_level( 4 );
                }
            }
        }
    }
    return ret;
}
References flag_LEAK_ALWAYS(), flag_LEAK_DAM(), items, units::legacy_volume_factor, and cata::hash64_detail::ret.
Referenced by Character::leak_level().
most_appropriate_painkiller()
item * inventory::most_appropriate_painkiller (int pain)
Definition at line 940 of file inventory.cpp.
{
    int difference = 9999;
    item *ret = &null_item_reference();
    for( auto &elem : items ) {
        int diff = 9999;
        itype_id type = elem.front().typeId();
        if( type == itype_aspirin ) {
            diff = std::abs( pain - 15 );
        } else if( type == itype_codeine ) {
            diff = std::abs( pain - 30 );
        } else if( type == itype_oxycodone ) {
            diff = std::abs( pain - 60 );
        } else if( type == itype_heroin ) {
            diff = std::abs( pain - 100 );
        } else if( type == itype_tramadol ) {
            diff = std::abs( pain - 40 ) / 2; // Bonus since it's long-acting
        }
        if( diff < difference ) {
            difference = diff;
            ret = &elem.front();
        }
    }
    return ret;
}
References items, itype_aspirin, itype_codeine, itype_heroin, itype_oxycodone, itype_tramadol, null_item_reference(), pain, cata::hash64_detail::ret, and type.
Referenced by npc::use_painkiller().
operator+() [1/3]
inventory inventory::operator+ (const inventory & rhs)
Definition at line 211 of file inventory.cpp.
{
    return inventory( *this ) += rhs;
}
References inventory().
operator+() [2/3]
inventory inventory::operator+ (const item & rhs)
Definition at line 221 of file inventory.cpp.
{
    return inventory( *this ) += rhs;
}
References inventory().
operator+() [3/3]
inventory inventory::operator+ (const std::list< item > & rhs)
Definition at line 216 of file inventory.cpp.
{
    return inventory( *this ) += rhs;
}
References inventory().
operator+=() [1/5]
inventory & inventory::operator+= (const inventory & rhs)
Definition at line 171 of file inventory.cpp.
{
    for( size_t i = 0; i < rhs.size(); i++ ) {
        push_back( rhs.const_stack( i ) );
    }
    return *this;
}
References const_stack(), push_back(), and size().
operator+=() [2/5]
inventory & inventory::operator+= (const item & rhs)
Definition at line 195 of file inventory.cpp.
{
    add_item( rhs );
    return *this;
}
References add_item().
operator+=() [3/5]
inventory & inventory::operator+= (const item_stack & rhs)
Definition at line 201 of file inventory.cpp.
{
    for( const auto &p : rhs ) {
        if( !p.made_of( LIQUID ) ) {
            add_item( p, true );
        }
    }
    return *this;
}
References add_item(), and LIQUID.
operator+=() [4/5]
inventory & inventory::operator+= (const std::list< item > & rhs)
Definition at line 179 of file inventory.cpp.
{
    for( const auto &rh : rhs ) {
        add_item( rh, false, false );
    }
    return *this;
}
References add_item().
operator+=() [5/5]
inventory & inventory::operator+= (const std::vector< item > & rhs)
Definition at line 187 of file inventory.cpp.
{
    for( const auto &rh : rhs ) {
        add_item( rh, true );
    }
    return *this;
}
References add_item().
operator=() [1/2]
inventory & inventory::operator= (const inventory &) default
operator=() [2/2]
inventory & inventory::operator= (inventory &&) default
position_by_item()
int inventory::position_by_item (const item * it) const
Returns the item position of the stack that contains the given item (compared by pointers).
Returns INT_MIN if the item is not found. Note that this may lose some information, for example the returned position is the same when the given item points to the container and when it points to the item inside the container. All items that are part of the same stack have the same item position.
Definition at line 826 of file inventory.cpp.
{
    int p = 0;
    for( const auto &stack : items ) {
        for( const auto &e : stack ) {
            if( e.has_item( *it ) ) {
                return p;
            }
        }
        p++;
    }
    return INT_MIN;
}
References items.
Referenced by player::consume(), Character::get_item_position(), restack(), and npc::wield().
position_by_type()
int inventory::position_by_type (const itype_id & type) const
Definition at line 840 of file inventory.cpp.
{
    int i = 0;
    for( auto &elem : items ) {
        if( elem.front().typeId() == type ) {
            return i;
        }
        ++i;
    }
    return INT_MIN;
}
References items, and type.
Referenced by npc::heal_self(), and iexamine::pay_gas().
push_back() [1/2]
void inventory::push_back (const std::list< item > & newits)
Definition at line 244 of file inventory.cpp.
{
    for( const auto &newit : newits ) {
        add_item( newit, true );
    }
}
References add_item().
Referenced by avatar::create(), iuse::multicooker(), om_harvest_furn(), om_harvest_ter(), operator+=(), and npc::shop_restock().
push_back() [2/2]
void inventory::push_back (item newit)
Definition at line 389 of file inventory.cpp.
{
    add_item( newit );
}
References add_item().
reassign_item()
void inventory::reassign_item (item & it, char invlet, bool remove_old = true)
Definition at line 1202 of file inventory.cpp.
{
    if( it.invlet == invlet ) { // no change needed
        return;
    }
    if( remove_old && it.invlet ) {
        invlet_cache.erase( it.invlet );
    }
    it.invlet = invlet;
    update_cache_with_item( it );
}
References invlet_favorites::erase(), item::invlet, invlet_cache, and update_cache_with_item().
Referenced by player::reassign_item(), and player::sort_armor().
reduce_stack()
std::list< item > inventory::reduce_stack (int position, int quantity)
Definition at line 692 of file inventory.cpp.
{
    int pos = 0;
    std::list<item> ret;
    for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter ) {
        if( position == pos ) {
            binned = false;
            items_type_cached = false;
            if( quantity >= static_cast<int>( iter->size() ) || quantity < 0 ) {
                ret = *iter;
                items.erase( iter );
            } else {
                for( int i = 0 ; i < quantity ; i++ ) {
                    ret.push_back( remove_item( &iter->front() ) );
                }
            }
            break;
        }
        ++pos;
    }
    return ret;
}
References binned, items, items_type_cached, remove_item(), and cata::hash64_detail::ret.
remove_item() [1/2]
item inventory::remove_item (const item * it)
Remove a specific item from the inventory.
The item is compared by pointer. Contents of the item are removed as well.
Parameters
it A pointer to the item to be removed. The item must exists in this inventory.
Returns
A copy of the removed item.
Definition at line 715 of file inventory.cpp.
{
    auto tmp = remove_items_with( [&it]( const item & i ) {
        return &i == it;
    }, 1 );
    if( !tmp.empty() ) {
        binned = false;
        items_type_cached = false;
        return tmp.front();
    }
    debugmsg( "Tried to remove a item not in inventory." );
    return item();
}
References binned, debugmsg, items_type_cached, and visitable< inventory >::remove_items_with().
Referenced by player::consume(), Character::i_rem(), player::process_items(), reduce_stack(), and player::wear().
remove_item() [2/2]
item inventory::remove_item (int position)
Definition at line 729 of file inventory.cpp.
{
    int pos = 0;
    for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter ) {
        if( position == pos ) {
            binned = false;
            items_type_cached = false;
            if( iter->size() > 1 ) {
                std::list<item>::iterator stack_member = iter->begin();
                char invlet = stack_member->invlet;
                ++stack_member;
                stack_member->invlet = invlet;
            }
            item ret = iter->front();
            iter->erase( iter->begin() );
            if( iter->empty() ) {
                items.erase( iter );
            }
            return ret;
        }
        ++pos;
    }
    return item();
}
References binned, items, items_type_cached, and cata::hash64_detail::ret.
remove_randomly_by_volume()
std::list< item > inventory::remove_randomly_by_volume (const units::volume & volume)
Randomly select items until the volume quota is filled.
Definition at line 755 of file inventory.cpp.
{
    std::list<item> result;
    units::volume volume_dropped = 0_ml;
    while( volume_dropped < volume ) {
        units::volume cumulative_volume = 0_ml;
        auto chosen_stack = items.begin();
        auto chosen_item = chosen_stack->begin();
        for( auto stack = items.begin(); stack != items.end(); ++stack ) {
            for( auto stack_it = stack->begin(); stack_it != stack->end(); ++stack_it ) {
                cumulative_volume += stack_it->volume();
                if( x_in_y( stack_it->volume().value(), cumulative_volume.value() ) ) {
                    chosen_item = stack_it;
                    chosen_stack = stack;
                }
            }
        }
        volume_dropped += chosen_item->volume();
        result.push_back( std::move( *chosen_item ) );
        chosen_item = chosen_stack->erase( chosen_item );
        if( chosen_item == chosen_stack->begin() && !chosen_stack->empty() ) {
            // preserve the invlet when removing the first item of a stack
            chosen_item->invlet = result.back().invlet;
        }
        if( chosen_stack->empty() ) {
            binned = false;
            items_type_cached = false;
            items.erase( chosen_stack );
        }
    }
    return result;
}
References binned, items, items_type_cached, avatar_action::move(), units::quantity< V, U >::value(), volume(), and x_in_y().
Referenced by Character::drop_invalid_inventory().
restack()
void inventory::restack (player & p)
Definition at line 398 of file inventory.cpp.
{
    // tasks that the old restack seemed to do:
    // 1. reassign inventory letters
    // 2. remove items from non-matching stacks
    // 3. combine matching stacks
    binned = false;
    items_type_cached = false;
    std::list<item> to_restack;
    int idx = 0;
    for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter, ++idx ) {
        std::list<item> &stack = *iter;
        item &topmost = stack.front();
        const item *invlet_item = p.invlet_to_item( topmost.invlet );
        if( !inv_chars.valid( topmost.invlet ) || ( invlet_item != nullptr &&
                position_by_item( invlet_item ) != idx ) ) {
            assign_empty_invlet( topmost, p );
            for( auto &stack_iter : stack ) {
                stack_iter.invlet = topmost.invlet;
            }
        }
        // remove non-matching items, stripping off end of stack so the first item keeps the invlet.
        while( stack.size() > 1 && !topmost.stacks_with( stack.back() ) ) {
            to_restack.splice( to_restack.begin(), *iter, --stack.end() );
        }
    }
    // combine matching stacks
    // separate loop to ensure that ALL stacks are homogeneous
    for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter ) {
        for( invstack::iterator other = iter; other != items.end(); ++other ) {
            if( iter != other && iter->front().stacks_with( other->front() ) ) {
                if( other->front().count_by_charges() ) {
                    iter->front().charges += other->front().charges;
                } else {
                    iter->splice( iter->begin(), *other );
                }
                other = items.erase( other );
                --other;
            }
        }
    }
    //re-add non-matching items
    for( auto &elem : to_restack ) {
        add_item( elem );
    }
    //Ensure that all items in the same stack have the same invlet.
    for( std::list< item > &outer : items ) {
        for( item &inner : outer ) {
            inner.invlet = outer.front().invlet;
        }
    }
    items.sort( stack_compare );
#if defined(__ANDROID__)
    remove_stale_inventory_quick_shortcuts();
#endif
}
References add_item(), assign_empty_invlet(), binned, inv_chars(), item::invlet, Character::invlet_to_item(), items, items_type_cached, other, position_by_item(), stack_compare(), item::stacks_with(), and invlet_wrapper::valid().
Referenced by autoclave_internal(), autodoc_internal(), game_menus::inv::common(), game_menus::inv::compare(), complete_craft(), player::consume(), inv_internal(), game_menus::inv::multidrop(), item::reload(), game_menus::inv::swap_letters(), wash_items(), player::wear(), and memorial_logger::write().
rust_iron_items()
void inventory::rust_iron_items ()
Definition at line 967 of file inventory.cpp.
{
    for( auto &elem : items ) {
        for( auto &elem_stack_iter : elem ) {
            if( elem_stack_iter.made_of( material_id( "iron" ) ) &&
                !elem_stack_iter.has_flag( flag_WATERPROOF_GUN ) &&
                !elem_stack_iter.has_flag( flag_WATERPROOF ) &&
                elem_stack_iter.damage() < elem_stack_iter.max_damage() / 2 &&
                //Passivation layer prevents further rusting
                one_in( 500 ) &&
                //Scale with volume, bigger = slower (see #24204)
                one_in(
                    static_cast<int>(
                        14 * std::cbrt(
                            0.5 * std::max(
                                0.05, static_cast<double>(
                                    elem_stack_iter.base_volume().value() ) / 250 ) ) ) ) &&
                //                       ^season length   ^14/5*0.75/pi (from volume of sphere)
                //Freshwater without oxygen rusts slower than air
                g->m.water_from( g->u.pos() ).typeId() == itype_salt_water ) {
                elem_stack_iter.inc_damage( DT_ACID ); // rusting never completely destroys an item
                add_msg( m_bad, _( "Your %s is damaged by rust." ), elem_stack_iter.tname() );
            }
        }
    }
}
References _, add_msg(), DT_ACID, flag_WATERPROOF(), flag_WATERPROOF_GUN(), g, items, itype_salt_water, m_bad, and one_in().
Referenced by avatar_action::swim().
set_stack_favorite()
void inventory::set_stack_favorite (int position, bool favorite)
Definition at line 1251 of file inventory.cpp.
{
    for( auto &e : *std::next( items.begin(), position ) ) {
        e.set_favorite( favorite );
    }
}
References items.
size()
size_t inventory::size () const
Definition at line 166 of file inventory.cpp.
{
    return items.size();
}
References items.
Referenced by talk_function::companion_return(), npc::drop_items(), findBestGasDiscount(), basecamp::finish_return(), player::get_eligible_containers_for_crafting(), operator+=(), and player::process_items().
slice()
invslice inventory::slice ()
Definition at line 133 of file inventory.cpp.
{
    invslice stacks;
    for( auto &elem : items ) {
        stacks.push_back( &elem );
    }
    return stacks;
}
References items.
Referenced by inventory_selector::add_character_items(), advanced_inventory_pane::add_items_from_area(), npc::alt_attack(), npc::consume_cbm_items(), npc::consume_food(), npc::decide_needs(), npc::drop_items(), player::get_artifact_items(), npc_trading::init_buying(), npc_trading::init_selling(), npc::mug_player(), pickup::reorder_for_dropping(), npc::wield_better_weapon(), and memorial_logger::write().
unsort()
void inventory::unsort ()
Definition at line 226 of file inventory.cpp.
{
    binned = false;
    items_type_cached = false;
}
References binned, and items_type_cached.
Referenced by player::consume(), Character::dispose_item(), npc::dispose_item(), Character::i_add(), Character::pour_into(), player::unwield(), and player::wield_contents().
update_cache_with_item()
void inventory::update_cache_with_item (item & newit)
Definition at line 252 of file inventory.cpp.
{
    // This function does two things:
    // 1. It adds newit's invlet to the list of favorite letters for newit's item type.
    // 2. It removes newit's invlet from the list of favorite letters for all other item types.
    // no invlet item, just return.
    // TODO: Should we instead remember that the invlet was cleared?
    if( newit.invlet == 0 ) {
        return;
    }
    invlet_cache.set( newit.invlet, newit.typeId() );
}
References item::invlet, invlet_cache, invlet_favorites::set(), and item::typeId().
Referenced by add_item(), add_item_by_items_type_cache(), reassign_item(), Character::wear_item(), avatar::wield(), and player::wield_contents().
update_invlet()
void inventory::update_invlet (item & it, bool assign_invlet = true)
Definition at line 1214 of file inventory.cpp.
{
    // Avoid letters that have been manually assigned to other things.
    if( newit.invlet && assigned_invlet.find( newit.invlet ) != assigned_invlet.end() &&
        assigned_invlet[newit.invlet] != newit.typeId() ) {
        newit.invlet = '\0';
    }
    // Remove letters that are not in the favorites cache
    if( newit.invlet ) {
        if( !invlet_cache.contains( newit.invlet, newit.typeId() ) ) {
            newit.invlet = '\0';
        }
    }
    // Remove letters that have been assigned to other items in the inventory
    if( newit.invlet ) {
        char tmp_invlet = newit.invlet;
        newit.invlet = '\0';
        if( g->u.invlet_to_item( tmp_invlet ) == nullptr ) {
            newit.invlet = tmp_invlet;
        }
    }
    if( assign_invlet ) {
        // Assign a cached letter to the item
        if( !newit.invlet ) {
            newit.invlet = find_usable_cached_invlet( newit.typeId() );
        }
        // Give the item an invlet if it has none
        if( !newit.invlet ) {
            assign_empty_invlet( newit, g->u );
        }
    }
}
References assign_empty_invlet(), assigned_invlet, invlet_favorites::contains(), find_usable_cached_invlet(), g, item::invlet, invlet_cache, and item::typeId().
Referenced by add_item(), add_item_by_items_type_cache(), Character::wear_item(), avatar::wield(), and player::wield_contents().
update_quality_cache()
void inventory::update_quality_cache ()
Definition at line 1114 of file inventory.cpp.
{
    quality_cache.clear();
    visit_items( [ this ]( const item * e ) {
        const std::map<quality_id, int> &item_qualities = e->get_qualities();
        for( const std::pair<const quality_id, int> &quality : item_qualities ) {
            const int item_count = e->count_by_charges() ? e->charges : 1;
            // quality.first is the id of the quality, quality.second is the quality level
            // the value is the number of items with that quality level
            quality_cache[quality.first][quality.second] += item_count;
        }
        return VisitResponse::NEXT;
    } );
}
References item::charges, item::count_by_charges(), item::get_qualities(), NEXT, quality_cache, and visitable< inventory >::visit_items().
Referenced by Character::crafting_inventory().
use_amount()
std::list< item > inventory::use_amount (itype_id it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>)
Definition at line 852 of file inventory.cpp.
{
    items.sort( stack_compare );
    std::list<item> ret;
    for( invstack::iterator iter = items.begin(); iter != items.end() && quantity > 0; /* noop */ ) {
        for( std::list<item>::iterator stack_iter = iter->begin();
             stack_iter != iter->end() && quantity > 0;
             /* noop */ ) {
            if( stack_iter->use_amount( it, quantity, ret, filter ) ) {
                stack_iter = iter->erase( stack_iter );
            } else {
                ++stack_iter;
            }
        }
        if( iter->empty() ) {
            binned = false;
            items_type_cached = false;
            iter = items.erase( iter );
        } else if( iter != items.end() ) {
            ++iter;
        }
    }
    return ret;
}
References binned, items, items_type_cached, cata::hash64_detail::ret, and stack_compare().
Referenced by Character::use_amount().
volume()
units::volume inventory::volume () const
Definition at line 1057 of file inventory.cpp.
{
    units::volume ret = 0_ml;
    for( const auto &elem : items ) {
        for( const auto &elem_stack_iter : elem ) {
            ret += elem_stack_iter.volume();
        }
    }
    return ret;
}
References items, and cata::hash64_detail::ret.
Referenced by Character::can_pick_volume(), item::get_encumber(), remove_randomly_by_volume(), Character::volume_carried(), Character::volume_carried_reduced_by(), and volume_without().
volume_without()
units::volume inventory::volume_without (const excluded_stacks & without) const
Definition at line 1068 of file inventory.cpp.
{
    units::volume ret = volume();
    for_each_item_in_both( items, without,
    [&]( const item & i ) {
        ret -= i.volume();
    }
                         );
    if( ret < 0_ml ) {
        debugmsg( "Negative volume after removing some of inventory" );
        ret = 0_ml;
    }
    return ret;
}
References debugmsg, for_each_item_in_both(), items, cata::hash64_detail::ret, volume(), and item::volume().
Referenced by Character::volume_carried_reduced_by().
weight()
units::mass inventory::weight () const
Definition at line 994 of file inventory.cpp.
{
    units::mass ret = 0_gram;
    for( const auto &elem : items ) {
        for( const auto &elem_stack_iter : elem ) {
            ret += elem_stack_iter.weight();
        }
    }
    return ret;
}
References items, and cata::hash64_detail::ret.
Referenced by Character::get_weight(), and weight_without().
weight_without()
units::mass inventory::weight_without (const excluded_stacks & without) const
Definition at line 1039 of file inventory.cpp.
{
    units::mass ret = weight();
    for_each_item_in_both( items, without,
    [&]( const item & i ) {
        ret -= i.weight();
    }
                         );
    if( ret < 0_gram ) {
        debugmsg( "Negative mass after removing some of inventory" );
        ret = {};
    }
    return ret;
}
References debugmsg, for_each_item_in_both(), items, cata::hash64_detail::ret, weight(), and item::weight().
Referenced by Character::weight_carried_reduced_by().
worst_item_value()
int inventory::worst_item_value (npc * p) const
Definition at line 914 of file inventory.cpp.
{
    int worst = 99999;
    for( const auto &elem : items ) {
        const item &it = elem.front();
        int val = p->value( it );
        if( val < worst ) {
            worst = val;
        }
    }
    return worst;
}
References items, and npc::value().
Referenced by npc::update_worst_item_value().
Member Data Documentation
assigned_invlet
std::map<char, itype_id> inventory::assigned_invlet
Definition at line 99 of file inventory.h.
Referenced by assign_empty_invlet(), copy_invlet_of(), find_usable_cached_invlet(), Character::i_add(), avatar::load(), player::reassign_item(), avatar::store(), and update_invlet().
binned
bool inventory::binned = false mutable private
Definition at line 255 of file inventory.h.
Referenced by add_item(), add_item_by_items_type_cache(), clear(), get_binned_items(), reduce_stack(), remove_item(), remove_randomly_by_volume(), restack(), unsort(), and use_amount().
binned_items
itype_bin inventory::binned_items mutable private
Items binned by their type.
That is, item_bin["carrot"] is a list of pointers to all carrots in inventory. mutable because this is a pure cache that doesn't affect the contained items.
Definition at line 261 of file inventory.h.
Referenced by get_binned_items().
invlet_cache
invlet_favorites inventory::invlet_cache private
Definition at line 247 of file inventory.h.
Referenced by copy_invlet_of(), find_usable_cached_invlet(), reassign_item(), update_cache_with_item(), and update_invlet().
items
invstack inventory::items private
Definition at line 250 of file inventory.h.
Referenced by active_items(), add_item(), add_item_by_items_type_cache(), allocated_invlets(), assign_empty_invlet(), build_items_type_cache(), can_butcher_at(), clear(), const_slice(), const_stack(), count_item(), dump(), find_item(), form_from_map(), get_active_enchantment_cache(), has_enough_painkiller(), invlet_to_position(), leak_level(), most_appropriate_painkiller(), position_by_item(), position_by_type(), reduce_stack(), remove_item(), remove_randomly_by_volume(), restack(), rust_iron_items(), set_stack_favorite(), size(), slice(), use_amount(), volume(), volume_without(), weight(), weight_without(), and worst_item_value().
items_type_cache
std::map<itype_id, std::list<std::list<item>*> > inventory::items_type_cache private
Definition at line 251 of file inventory.h.
Referenced by add_item_by_items_type_cache(), and build_items_type_cache().
items_type_cached
bool inventory::items_type_cached = false private
Definition at line 254 of file inventory.h.
Referenced by add_item(), add_item_by_items_type_cache(), build_items_type_cache(), clear(), reduce_stack(), remove_item(), remove_randomly_by_volume(), restack(), unsort(), and use_amount().
quality_cache
std::map<quality_id, std::map<int, int> > inventory::quality_cache private
Definition at line 252 of file inventory.h.
Referenced by get_quality_cache(), and update_quality_cache().
visitable< inventory >
friend inventory::visitable< inventory >
Definition at line 92 of file inventory.h.
The documentation for this class was generated from the following files:
src/inventory.h
src/inventory.cpp
src/savegame_json.cpp