Cataclysm BN: detail::value< Context > Class Template Reference
detail::value< Context > Class Template Reference
#include <fmtlib_core.h>
Public Types
using char_type = typename Context::char_type
Public Member Functions
constexpr FMT_INLINE value (int val=0)
constexpr FMT_INLINE value (unsigned val)
FMT_INLINE value (long long val)
FMT_INLINE value (unsigned long long val)
FMT_INLINE value (int128_t val)
FMT_INLINE value (uint128_t val)
FMT_INLINE value (float val)
FMT_INLINE value (double val)
FMT_INLINE value (long double val)
FMT_INLINE value (bool val)
FMT_INLINE value (char_type val)
FMT_INLINE value (const char_type *val)
FMT_INLINE value (basic_string_view< char_type > val)
FMT_INLINE value (const void *val)
FMT_INLINE value (const named_arg_info< char_type > *args, size_t size)
template<typename T >
FMT_INLINE value (const T &val)
Public Attributes
union {
int int_value
unsigned uint_value
long long long_long_value
unsigned long long ulong_long_value
int128_t int128_value
uint128_t uint128_value
bool bool_value
char_type char_value
float float_value
double double_value
long double long_double_value
const void * pointer
string_value< char_type > string
custom_value< Context > custom
named_arg_value< char_type > named_args
};
Static Private Member Functions
template<typename T , typename Formatter >
static void format_custom_arg (const void *arg, typename Context::parse_context_type &parse_ctx, Context &ctx)
Detailed Description
template<typename Context>
class detail::value< Context >
Definition at line 1161 of file fmtlib_core.h.
Member Typedef Documentation
char_type
template<typename Context > using detail::value< Context >::char_type = typename Context::char_type
Definition at line 1164 of file fmtlib_core.h.
Constructor & Destructor Documentation
value() [1/16]
template<typename Context > constexpr FMT_INLINE detail::value< Context >::value (int val = 0) inline constexpr
Definition at line 1184 of file fmtlib_core.h.
: int_value(val) {}
Referenced by detail::dynamic_arg_list::push().
value() [2/16]
template<typename Context > constexpr FMT_INLINE detail::value< Context >::value (unsigned val) inline constexpr
Definition at line 1185 of file fmtlib_core.h.
: uint_value(val) {}
value() [3/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (long long val) inline
Definition at line 1186 of file fmtlib_core.h.
: long_long_value(val) {}
value() [4/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (unsigned long long val) inline
Definition at line 1187 of file fmtlib_core.h.
: ulong_long_value(val) {}
value() [5/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (int128_t val) inline
Definition at line 1188 of file fmtlib_core.h.
: int128_value(val) {}
value() [6/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (uint128_t val) inline
Definition at line 1189 of file fmtlib_core.h.
: uint128_value(val) {}
value() [7/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (float val) inline
Definition at line 1190 of file fmtlib_core.h.
: float_value(val) {}
value() [8/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (double val) inline
Definition at line 1191 of file fmtlib_core.h.
: double_value(val) {}
value() [9/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (long double val) inline
Definition at line 1192 of file fmtlib_core.h.
: long_double_value(val) {}
value() [10/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (bool val) inline
Definition at line 1193 of file fmtlib_core.h.
: bool_value(val) {}
value() [11/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (char_type val) inline
Definition at line 1194 of file fmtlib_core.h.
: char_value(val) {}
value() [12/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (const char_type * val) inline
Definition at line 1195 of file fmtlib_core.h.
{
            string.data = val;
        }
value() [13/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (basic_string_view< char_type > val) inline
Definition at line 1198 of file fmtlib_core.h.
{
            string.data = val.data();
            string.size = val.size();
        }
References basic_string_view< Char >::data(), and basic_string_view< Char >::size().
value() [14/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (const void * val) inline
Definition at line 1202 of file fmtlib_core.h.
: pointer(val) {}
value() [15/16]
template<typename Context > FMT_INLINE detail::value< Context >::value (const named_arg_info< char_type > * args, size_t size) inline
Definition at line 1203 of file fmtlib_core.h.
            : named_args{args, size} {}
value() [16/16]
template<typename Context > template<typename T > FMT_INLINE detail::value< Context >::value (const T & val) inline
Definition at line 1206 of file fmtlib_core.h.
{
            custom.value = &val;
            // Get the formatter type through the context to allow different contexts
            // have different extension points, e.g. `formatter<T>` for `format` and
            // `printf_formatter<T>` for `printf`.
            custom.format = format_custom_arg <
                            T, conditional_t<has_formatter<T, Context>::value,
                            typename Context::template formatter_type<T>,
                                     fallback_formatter<T, char_type> >>;
        }
References detail::value< Context >::custom, and detail::value< Context >::format_custom_arg().
Member Function Documentation
format_custom_arg()
template<typename Context > template<typename T , typename Formatter > static void detail::value< Context >::format_custom_arg (const void * arg, typename Context::parse_context_type & parse_ctx, Context & ctx) inline static private
Definition at line 1220 of file fmtlib_core.h.
{
            Formatter f;
            parse_ctx.advance_to( f.parse( parse_ctx ) );
            ctx.advance_to( f.format( *static_cast<const T *>( arg ), ctx ) );
        }
References arg().
Referenced by detail::value< Context >::value().
Member Data Documentation
union { ... } detail::value< Context >::@8
bool_value
template<typename Context > bool detail::value< Context >::bool_value
Definition at line 1173 of file fmtlib_core.h.
char_value
template<typename Context > char_type detail::value< Context >::char_value
Definition at line 1174 of file fmtlib_core.h.
custom
template<typename Context > custom_value<Context> detail::value< Context >::custom
Definition at line 1180 of file fmtlib_core.h.
Referenced by detail::value< Context >::value().
double_value
template<typename Context > double detail::value< Context >::double_value
Definition at line 1176 of file fmtlib_core.h.
float_value
template<typename Context > float detail::value< Context >::float_value
Definition at line 1175 of file fmtlib_core.h.
int128_value
template<typename Context > int128_t detail::value< Context >::int128_value
Definition at line 1171 of file fmtlib_core.h.
int_value
template<typename Context > int detail::value< Context >::int_value
Definition at line 1167 of file fmtlib_core.h.
long_double_value
template<typename Context > long double detail::value< Context >::long_double_value
Definition at line 1177 of file fmtlib_core.h.
long_long_value
template<typename Context > long long detail::value< Context >::long_long_value
Definition at line 1169 of file fmtlib_core.h.
named_args
template<typename Context > named_arg_value<char_type> detail::value< Context >::named_args
Definition at line 1181 of file fmtlib_core.h.
pointer
template<typename Context > const void* detail::value< Context >::pointer
Definition at line 1178 of file fmtlib_core.h.
string
template<typename Context > string_value<char_type> detail::value< Context >::string
Definition at line 1179 of file fmtlib_core.h.
uint128_value
template<typename Context > uint128_t detail::value< Context >::uint128_value
Definition at line 1172 of file fmtlib_core.h.
uint_value
template<typename Context > unsigned detail::value< Context >::uint_value
Definition at line 1168 of file fmtlib_core.h.
ulong_long_value
template<typename Context > unsigned long long detail::value< Context >::ulong_long_value
Definition at line 1170 of file fmtlib_core.h.
The documentation for this class was generated from the following file:
src/fmtlib_core.h