Cataclysm BN: jmapgen_sealed_item Class Reference
jmapgen_sealed_item Class Reference
Place an item in furniture (expected to be used with NOITEM SEALED furniture like plants).
Public Member Functions
jmapgen_sealed_item (const JsonObject &jsi)
void check (const std::string &oter_name) const override
Sanity-check this piece.
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, const point &p) const override
Public Member Functions inherited from jmapgen_piece
virtual ~jmapgen_piece ()=default
Public Attributes
furn_id furniture
jmapgen_int chance
cata::optional< jmapgen_spawn_item > item_spawner
cata::optional< jmapgen_item_group > item_group_spawner
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place an item in furniture (expected to be used with NOITEM SEALED furniture like plants).
"item": item to spawn (object with usual parameters). "items": item group to spawn (object with usual parameters). "furniture": furniture to create around it.
Definition at line 1612 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_sealed_item()
jmapgen_sealed_item::jmapgen_sealed_item (const JsonObject & jsi) inline
Definition at line 1619 of file mapgen.cpp.
            : furniture( jsi.get_string( "furniture" ) )
            , chance( jsi, "chance", 100, 100 ) {
            if( jsi.has_object( "item" ) ) {
                JsonObject item_obj = jsi.get_object( "item" );
                item_spawner = jmapgen_spawn_item( item_obj );
            }
            if( jsi.has_object( "items" ) ) {
                JsonObject items_obj = jsi.get_object( "items" );
                item_group_spawner = jmapgen_item_group( items_obj );
            }
        }
References JsonObject::get_object(), JsonObject::has_object(), item_group_spawner, item_spawner, and mapgen_defer::jsi.
Member Function Documentation
apply()
void jmapgen_sealed_item::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1704 of file mapgen.cpp.
{
            const int c = chance.get();
            // 100% chance = always generate, otherwise scale by item spawn rate.
            // (except is capped at 1)
            const float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
            if( c != 100 && !x_in_y( c * spawn_rate / 100.0f, 1 ) ) {
                return;
            }
            dat.m.furn_set( point( x.get(), y.get() ), f_null );
            if( item_spawner ) {
                item_spawner->apply( dat, x, y );
            }
            if( item_group_spawner ) {
                item_group_spawner->apply( dat, x, y );
            }
            dat.m.furn_set( point( x.get(), y.get() ), furniture );
        }
References c, chance, f_null, map::furn_set(), furniture, jmapgen_int::get(), item_group_spawner, item_spawner, mapgendata::m, and x_in_y().
check()
void jmapgen_sealed_item::check (const std::string &) const inline override virtual
Sanity-check this piece.
TODO: Somehow check that the item group always produces exactly one item.
Reimplemented from jmapgen_piece.
Definition at line 1632 of file mapgen.cpp.
{
            const furn_t &furn = furniture.obj();
            std::string summary = string_format(
                                      "sealed_item special in json mapgen for overmap terrain %s using furniture %s",
                                      oter_name, furn.id.str() );
            if( !furniture.is_valid() ) {
                debugmsg( "%s which is not valid furniture", summary );
            }
            if( !item_spawner && !item_group_spawner ) {
                debugmsg( "%s specifies neither an item nor an item group.  "
                          "It should specify at least one.",
                          summary );
                return;
            }
            if( furn.has_flag( "PLANT" ) ) {
                // plant furniture requires exactly one seed item within it
                if( item_spawner && item_group_spawner ) {
                    debugmsg( "%s (with flag PLANT) specifies both an item and an item group.  "
                              "It should specify exactly one.",
                              summary );
                    return;
                }
                if( item_spawner ) {
                    int count = item_spawner->amount.get();
                    if( count != 1 ) {
                        debugmsg( "%s (with flag PLANT) spawns %d items; it should spawn exactly "
                                  "one.", summary, count );
                        return;
                    }
                    int item_chance = item_spawner->chance.get();
                    if( item_chance != 100 ) {
                        debugmsg( "%s (with flag PLANT) spawns an item (%s) with probability %d%%; "
                                  "it should always spawn.  You can move the \"chance\" up to the "
                                  "sealed_item instead of the \"item\" within.",
                                  summary, item_spawner->type, item_chance );
                        return;
                    }
                    if( !item_spawner->type->seed ) {
                        debugmsg( "%s (with flag PLANT) spawns item type %s which is not a seed.",
                                  summary, item_spawner->type );
                        return;
                    }
                }
                if( item_group_spawner ) {
                    int ig_chance = item_group_spawner->chance.get();
                    if( ig_chance != 100 ) {
                        debugmsg( "%s (with flag PLANT) spawns item group %s with chance %d.  "
                                  "It should have chance 100.  You can move the \"chance\" up to the "
                                  "sealed_item instead of the \"items\" within.",
                                  summary, item_group_spawner->group_id.str(), ig_chance );
                        return;
                    }
                    item_group_id group_id = item_group_spawner->group_id;
                    for( const itype *type : item_group::every_possible_item_from( group_id ) ) {
                        if( !type->seed ) {
                            debugmsg( "%s (with flag PLANT) spawns item group %s which can "
                                      "spawn item %s which is not a seed.",
                                      summary, group_id.str(), type->get_id() );
                            return;
                        }
                    }
                    /// TODO: Somehow check that the item group always produces exactly one item.
                }
            }
        }
References detail::count(), debugmsg, item_group::every_possible_item_from(), furniture, map_data_common_t::has_flag(), furn_t::id, int_id< T >::is_valid(), item_group_spawner, item_spawner, int_id< T >::obj(), string_id< T >::str(), string_format(), and type.
has_vehicle_collision()
bool jmapgen_sealed_item::has_vehicle_collision (mapgendata & dat, const point & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1723 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
chance
jmapgen_int jmapgen_sealed_item::chance
Definition at line 1616 of file mapgen.cpp.
Referenced by apply().
furniture
furn_id jmapgen_sealed_item::furniture
Definition at line 1615 of file mapgen.cpp.
Referenced by apply(), and check().
item_group_spawner
cata::optional<jmapgen_item_group> jmapgen_sealed_item::item_group_spawner
Definition at line 1618 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_sealed_item().
item_spawner
cata::optional<jmapgen_spawn_item> jmapgen_sealed_item::item_spawner
Definition at line 1617 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_sealed_item().
The documentation for this class was generated from the following file:
src/mapgen.cpp