Cataclysm BN: ui_adaptor Class Reference
ui_adaptor Class Reference
Adaptor between UI code and the UI management system.
#include <ui_manager.h>
Classes
struct debug_message_ui
struct disable_uis_below
Public Types
using redraw_callback_t = std::function< void(const ui_adaptor &)>
using screen_resize_callback_t = std::function< void(ui_adaptor &)>
Public Member Functions
ui_adaptor ()
Construct a ui_adaptor which is automatically added to the UI stack, and removed from the stack when it is deconstructed.
ui_adaptor (disable_uis_below)
ui_adaptor constructed this way will block any UIs below from being redrawn or resized until it is deconstructed.
ui_adaptor (debug_message_ui)
Special constructor used by debug.cpp when showing a debug message popup.
ui_adaptor (const ui_adaptor &rhs)=delete
ui_adaptor (ui_adaptor &&rhs)=delete
~ui_adaptor ()
ui_adaptor & operator= (const ui_adaptor &rhs)=delete
ui_adaptor & operator= (ui_adaptor &&rhs)=delete
void position_from_window (const catacurses::window &win)
Set the position and size of the UI to that of win.
void position (const point &topleft, const point &size)
Set the position and size of the UI to that of an imaginary catacurses::window in normal font, except that the size can be zero.
void on_redraw (const redraw_callback_t &fun)
Set redraw and resize callbacks.
void on_screen_resize (const screen_resize_callback_t &fun)
void mark_resize () const
Mark this ui_adaptor for resizing the next time it is redrawn.
void invalidate_ui () const
Invalidate this UI so it gets redrawn the next redraw unless an upper UI completely occludes this UI.
void reset ()
Reset all callbacks and dimensions.
Static Public Member Functions
static void invalidate (const rectangle< point > &rect, bool reenable_uis_below)
static void redraw ()
static void redraw_invalidated ()
static void screen_resized ()
Static Private Member Functions
static void invalidation_consistency_and_optimization ()
Private Attributes
rectangle< point > dimensions
redraw_callback_t redraw_cb
screen_resize_callback_t screen_resized_cb
bool disabling_uis_below
bool is_debug_message_ui
bool invalidated
bool deferred_resize
Detailed Description
Adaptor between UI code and the UI management system.
Using this class allows UIs to be correctly resized and redrawn when the game window is resized or when exiting from other UIs.
Usage example:
// Effective in the local scope
ui_adaptor ui;
// Ncurses window for drawing
catacurses::window win;
// Things to do when the game window changes size
ui.on_screen_resize([&](ui_adaptor & ui) {
    // Create an ncurses window
    win = catacurses::newwin( TERMX / 2, TERMY / 2, point( TERMX / 4, TERMY / 4 ) );
    // The window passed to this call must contain all the space the redraw
    // callback draws to, to ensure proper refreshing when resizing or exiting
    // from other UIs.
    ui.position_from_window( win );
});
// Mark the resize callback to be called on the first redraw
ui.mark_resize();
// Things to do when redrawing the UI
ui.on_redraw([&](const ui_adaptor &) {
    // Clear UI area
    werase( win );
    // Print things
    mvwprintw( win, point_zero, "Hello World!" );
    // Write to frame buffer
    wnoutrefresh( win );
});
input_context ctxt("<CATEGORY_NAME>");
ctxt.register_action("QUIT");
while(true) {
    // Invalidate the top UI (that is, this UI) and redraw all
    // invalidated UIs (including lower UIs that calls this UI).
    // May call the resize callbacks.
    ui_manager::redraw();
    // Get user input. Note that this may call the resize and redraw
    // callbacks multiple times due to screen resize, rendering target
    // reset, etc.
    const std::string action = ctxt.handle_input();
    if( action == "QUIT" ) {
        break;
    }
}
Definition at line 64 of file ui_manager.h.
Member Typedef Documentation
redraw_callback_t
using ui_adaptor::redraw_callback_t = std::function<void(const ui_adaptor &)>
Definition at line 67 of file ui_manager.h.
screen_resize_callback_t
using ui_adaptor::screen_resize_callback_t = std::function<void(ui_adaptor &)>
Definition at line 68 of file ui_manager.h.
Constructor & Destructor Documentation
ui_adaptor() [1/5]
ui_adaptor::ui_adaptor ()
Construct a ui_adaptor which is automatically added to the UI stack, and removed from the stack when it is deconstructed.
(When declared as a local variable, it is removed from the stack when leaving the local scope.)
Definition at line 25 of file ui_manager.cpp.
                       : disabling_uis_below( false ), is_debug_message_ui( false ),
    invalidated( false ), deferred_resize( false )
{
    ui_stack.emplace_back( *this );
}
References ui_stack.
ui_adaptor() [2/5]
ui_adaptor::ui_adaptor (ui_adaptor::disable_uis_below) explicit
ui_adaptor constructed this way will block any UIs below from being redrawn or resized until it is deconstructed.
It is used for throbber_popup.
Definition at line 31 of file ui_manager.cpp.
                                                    : disabling_uis_below( true ),
    is_debug_message_ui( false ), invalidated( false ), deferred_resize( false )
{
    ui_stack.emplace_back( *this );
}
References ui_stack.
ui_adaptor() [3/5]
ui_adaptor::ui_adaptor (ui_adaptor::debug_message_ui) explicit
Special constructor used by debug.cpp when showing a debug message popup.
If the UI is constructed when a redraw call is in progress, The redraw call will be restarted after this UI is deconstructed and the in progress callback returns, in order to prevent incorrect graphics caused by overwritten screen area and resizing.
Definition at line 37 of file ui_manager.cpp.
                                                   : disabling_uis_below( true ),
    is_debug_message_ui( true ), invalidated( false ), deferred_resize( false )
{
    assert( !showing_debug_message );
    showing_debug_message = true;
    if( redraw_in_progress ) {
        restart_redrawing = true;
    }
#if defined(TILES)
    // Reset the clip rect because the debug message UI might be created in a
    // redraw callback when a clip rect is active. When the UI is deconstructed,
    // restore the previous clip rect to prevent the redraw callback from
    // drawing outside the clip area, which will cause stuck graphics. This
    // alone does not prevent the graphics from becoming borked in other ways,
    // but `ui_manager` will redo the entire redrawing as soon as the redraw
    // callback returns.
    const SDL_Renderer_Ptr &renderer = get_sdl_renderer();
    if( SDL_RenderIsClipEnabled( renderer.get() ) ) {
        prev_clip_rect = SDL_Rect();
        SDL_RenderGetClipRect( renderer.get(), &prev_clip_rect.value() );
        SDL_RenderSetClipRect( renderer.get(), nullptr );
    } else {
        prev_clip_rect = cata::nullopt;
    }
#endif
    // The debug message might be shown during a normal UI's redraw callback,
    // so we need to invalidate the frame buffer so it does not interfere
    // with the display of the debug message.
    reinitialize_framebuffer( true );
    ui_stack.emplace_back( *this );
}
References cata::nullopt, redraw_in_progress, reinitialize_framebuffer(), restart_redrawing, showing_debug_message, ui_stack, and cata::optional< T >::value().
ui_adaptor() [4/5]
ui_adaptor::ui_adaptor (const ui_adaptor & rhs) delete
ui_adaptor() [5/5]
ui_adaptor::ui_adaptor (ui_adaptor && rhs) delete
~ui_adaptor()
ui_adaptor::~ui_adaptor ()
Definition at line 69 of file ui_manager.cpp.
{
    if( is_debug_message_ui ) {
        assert( showing_debug_message );
        showing_debug_message = false;
#if defined(TILES)
        // See ui_adaptor( debug_message_ui )
        if( prev_clip_rect.has_value() ) {
            const SDL_Renderer_Ptr &renderer = get_sdl_renderer();
            SDL_RenderSetClipRect( renderer.get(), &prev_clip_rect.value() );
        }
#endif
    }
    for( auto it = ui_stack.rbegin(); it < ui_stack.rend(); ++it ) {
        if( &it->get() == this ) {
            ui_stack.erase( std::prev( it.base() ) );
            // TODO avoid invalidating portions that do not need to be redrawn
            ui_manager::invalidate( dimensions, disabling_uis_below );
            break;
        }
    }
}
References dimensions, disabling_uis_below, cata::optional< T >::has_value(), ui_manager::invalidate(), is_debug_message_ui, showing_debug_message, ui_stack, and cata::optional< T >::value().
Member Function Documentation
invalidate()
void ui_adaptor::invalidate (const rectangle< point > & rect, bool reenable_uis_below) static
Definition at line 233 of file ui_manager.cpp.
{
    if( rect.p_min.x >= rect.p_max.x || rect.p_min.y >= rect.p_max.y ) {
        if( reenable_uis_below ) {
            invalidation_consistency_and_optimization();
        }
        return;
    }
    // Always invalidate every UI, even if it is below another UI with
    // `disable_uis_below`, so when the UI with `disable_uis_below` is removed,
    // UIs below are correctly marked for redraw.
    for( auto it_upper = ui_stack.cbegin(); it_upper < ui_stack.cend(); ++it_upper ) {
        const ui_adaptor &ui_upper = it_upper->get();
        if( !ui_upper.invalidated && overlap( ui_upper.dimensions, rect ) ) {
            // invalidated by `rect`
            ui_upper.invalidated = true;
        }
    }
    invalidation_consistency_and_optimization();
}
References dimensions, invalidated, invalidation_consistency_and_optimization(), overlap(), rectangle< Point, >::p_max, rectangle< Point, >::p_min, and ui_stack.
Referenced by ui_manager::invalidate().
invalidate_ui()
void ui_adaptor::invalidate_ui () const
Invalidate this UI so it gets redrawn the next redraw unless an upper UI completely occludes this UI.
May also cause upper UIs to redraw. Can be used to mark lower UIs for redrawing when their associated data has changed.
Definition at line 199 of file ui_manager.cpp.
{
    if( invalidated ) {
        return;
    }
    auto it = ui_stack.cbegin();
    for( ; it < ui_stack.cend(); ++it ) {
        if( &it->get() == this ) {
            break;
        }
    }
    if( it == ui_stack.end() ) {
        return;
    }
    // If an upper UI occludes this UI then nothing gets redrawn
    for( auto it_upper = std::next( it ); it_upper < ui_stack.cend(); ++it_upper ) {
        if( contains( it_upper->get().dimensions, dimensions ) ) {
            return;
        }
    }
    // Always mark this UI for redraw even if it is below another UI with
    // `disable_uis_below`, so when the UI with `disable_uis_below` is removed,
    // this UI is correctly marked for redraw.
    invalidated = true;
    invalidation_consistency_and_optimization();
}
References contains(), dimensions, invalidated, invalidation_consistency_and_optimization(), and ui_stack.
Referenced by handle_player_display_action(), overmap_ui::place_ter_or_special(), overmap_ui::search(), and diary::show_diary_ui().
invalidation_consistency_and_optimization()
void ui_adaptor::invalidation_consistency_and_optimization () static private
Definition at line 161 of file ui_manager.cpp.
{
    // Only ensure consistency and optimize for UIs not disabled by another UI
    // with `disable_uis_below`, since if a UI is disabled, it does not get
    // resized or redrawn, so the invalidation flag is not cleared, and including
    // the disabled UI in the following calculation would unnecessarily
    // invalidate any upper intersecting UIs.
    auto rfirst = ui_stack.crbegin();
    for( ; rfirst != ui_stack.crend(); ++rfirst ) {
        if( rfirst->get().disabling_uis_below ) {
            break;
        }
    }
    const auto first = rfirst == ui_stack.crend() ? ui_stack.cbegin() : std::prev( rfirst.base() );
    for( auto it_upper = first; it_upper < ui_stack.cend(); ++it_upper ) {
        const ui_adaptor &ui_upper = it_upper->get();
        for( auto it_lower = first; it_lower < it_upper; ++it_lower ) {
            const ui_adaptor &ui_lower = it_lower->get();
            if( !ui_upper.invalidated && ui_lower.invalidated &&
                overlap( ui_upper.dimensions, ui_lower.dimensions ) ) {
                // invalidated by lower invalidated UIs
                ui_upper.invalidated = true;
            }
            if( ui_upper.invalidated && ui_lower.invalidated &&
                contains( ui_upper.dimensions, ui_lower.dimensions ) ) {
                // fully obscured lower UIs do not need to be redrawn.
                ui_lower.invalidated = false;
                // Note: we don't need to re-test ui_lower from earlier iterations
                // during which ui_upper.invalidated hadn't yet been determined to
                // be true, because if the ui_lower would be obscured by ui_upper,
                // it implies that ui_lower would overlap with ui_upper, by which
                // we would have already determined ui_upper.invalidated to be true
                // then.
            }
        }
    }
}
References contains(), dimensions, invalidated, overlap(), and ui_stack.
Referenced by invalidate(), and invalidate_ui().
mark_resize()
void ui_adaptor::mark_resize () const
Mark this ui_adaptor for resizing the next time it is redrawn.
This is normally called alongside on_screen_resize to initialize the UI on the first redraw. You should also use this function to explicitly request a reinitialization if any value the screen resize callback depends on (apart from the screen size) has changed.
Definition at line 137 of file ui_manager.cpp.
{
    deferred_resize = true;
}
References deferred_resize.
Referenced by veh_interact::create_or_get_ui_adaptor(), character_display::disp_info(), and diary::show_diary_ui().
on_redraw()
void ui_adaptor::on_redraw (const redraw_callback_t & fun)
Set redraw and resize callbacks.
The resize callback should call position or position_from_window to set the size of the UI, and (re-)calculate any UI data that is related to the screen size, including catacurses::window instances. In most cases, you should also call mark_resize along with on_screen_resize so the UI is initialized by the resizing callback when redrawn for the first time.
The redraw callback should only redraw to the area specified by the position or position_from_window call. Content drawn outside this area may not render correctly when resizing or exiting from other UIs. Transparency is not currently supported.
These callbacks should NOT:
Construct new ui_adaptor instances
Deconstruct old ui_adaptor instances
Call redraw or screen_resized
(Redraw callback) call position_from_window
Call any function that does these things, except for debugmsg
Otherwise, display glitches or even crashes might happen.
Definition at line 127 of file ui_manager.cpp.
{
    redraw_cb = fun;
}
References redraw_cb.
Referenced by veh_interact::create_or_get_ui_adaptor(), character_display::disp_info(), reset(), auto_pickup::user_interface::show(), safemode::show(), and diary::show_diary_ui().
on_screen_resize()
void ui_adaptor::on_screen_resize (const screen_resize_callback_t & fun)
Definition at line 132 of file ui_manager.cpp.
{
    screen_resized_cb = fun;
}
References screen_resized_cb.
Referenced by character_display::disp_info(), reset(), auto_pickup::user_interface::show(), safemode::show(), and diary::show_diary_ui().
operator=() [1/2]
ui_adaptor & ui_adaptor::operator= (const ui_adaptor & rhs) delete
operator=() [2/2]
ui_adaptor & ui_adaptor::operator= (ui_adaptor && rhs) delete
position()
void ui_adaptor::position (const point & topleft, const point & size)
Set the position and size of the UI to that of an imaginary catacurses::window in normal font, except that the size can be zero.
Note that topleft and size are in console cells on both tiles and curses builds.
Definition at line 112 of file ui_manager.cpp.
{
    const rectangle<point> old_dimensions = dimensions;
    // ensure position is updated before calling invalidate
#ifdef TILES
    const window_dimensions dim = get_window_dimensions( topleft, size );
    dimensions = rectangle<point>( dim.window_pos_pixel,
                                   dim.window_pos_pixel + dim.window_size_pixel );
#else
    dimensions = rectangle<point>( topleft, topleft + size );
#endif
    invalidated = true;
    ui_manager::invalidate( old_dimensions, false );
}
References dimensions, ui_manager::invalidate(), invalidated, and om_direction::size.
Referenced by veh_interact::create_or_get_ui_adaptor(), position_from_window(), and reset().
position_from_window()
void ui_adaptor::position_from_window (const catacurses::window & win)
Set the position and size of the UI to that of win.
This information is used to calculate which UIs need redrawing during resizing and when exiting from other UIs, so do call this function in the resizing callback and ensure win contains all the space you will be drawing to. Transparency is not supported. If win is null, the function has the same effect as position(point_zero, point_zero)
Definition at line 92 of file ui_manager.cpp.
{
    if( !win ) {
        position( point_zero, point_zero );
    } else {
        const rectangle<point> old_dimensions = dimensions;
        // ensure position is updated before calling invalidate
#ifdef TILES
        const window_dimensions dim = get_window_dimensions( win );
        dimensions = rectangle<point>(
                         dim.window_pos_pixel, dim.window_pos_pixel + dim.window_size_pixel );
#else
        const point origin( getbegx( win ), getbegy( win ) );
        dimensions = rectangle<point>( origin, origin + point( getmaxx( win ), getmaxy( win ) ) );
#endif
        invalidated = true;
        ui_manager::invalidate( old_dimensions, false );
    }
}
References dimensions, catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), ui_manager::invalidate(), invalidated, point_zero, and position().
Referenced by veh_interact::create_or_get_ui_adaptor(), character_display::disp_info(), auto_pickup::user_interface::show(), and safemode::show().
redraw()
void ui_adaptor::redraw () static
Definition at line 254 of file ui_manager.cpp.
{
    if( !ui_stack.empty() ) {
        ui_stack.back().get().invalidated = true;
    }
    redraw_invalidated();
}
References redraw_invalidated(), and ui_stack.
Referenced by ui_manager::redraw(), and screen_resized().
redraw_invalidated()
void ui_adaptor::redraw_invalidated () static
Definition at line 262 of file ui_manager.cpp.
{
    if( test_mode || ui_stack.empty() ) {
        return;
    }
    restore_on_out_of_scope<bool> prev_redraw_in_progress( redraw_in_progress );
    restore_on_out_of_scope<bool> prev_restart_redrawing( restart_redrawing );
    redraw_in_progress = true;
    do {
        // Changed by the resize and redraw callbacks if they call `debugmsg`.
        // When this becomes true, the `debugmsg` call would have already changed
        // the resize and redraw flags according to the resized and redrawn states
        // so far, so we restart redrawing using the changed flags to redraw
        // the area invalidated by the debug message popup.
        restart_redrawing = false;
        // Find the first enabled UI. From now on enabling and disabling UIs
        // have no effect until the end of this call.
        auto first = ui_stack.rbegin();
        for( ; first != ui_stack.rend(); ++first ) {
            if( first->get().disabling_uis_below ) {
                break;
            }
        }
        // Avoid a copy if possible to improve performance. `ui_stack_orig`
        // always contains the original UI stack, and `first_enabled` always points
        // to elements of `ui_stack_orig`.
        std::unique_ptr<ui_stack_t> ui_stack_copy;
        auto first_enabled = first == ui_stack.rend() ? ui_stack.begin() : std::prev( first.base() );
        ui_stack_t *ui_stack_orig = &ui_stack;
        // Apply deferred resizing.
        bool needs_resize = false;
        for( auto it = first_enabled; !needs_resize && it != ui_stack_orig->end(); ++it ) {
            ui_adaptor &ui = *it;
            if( ui.deferred_resize && ui.screen_resized_cb ) {
                needs_resize = true;
            }
        }
        if( needs_resize ) {
            if( !ui_stack_copy ) {
                // Callbacks may modify the UI stack; make a copy of the original one.
                ui_stack_copy = std::make_unique<ui_stack_t>( *ui_stack_orig );
                first_enabled = ui_stack_copy->begin() + ( first_enabled - ui_stack_orig->begin() );
                ui_stack_orig = &*ui_stack_copy;
            }
            for( auto it = first_enabled; !restart_redrawing && it != ui_stack_orig->end(); ++it ) {
                ui_adaptor &ui = *it;
                if( ui.deferred_resize ) {
                    if( ui.screen_resized_cb ) {
                        ui.screen_resized_cb( ui );
                    }
                    if( !restart_redrawing ) {
                        ui.deferred_resize = false;
                    }
                }
            }
            // Callbacks may have changed window sizes; reinitialize the frame buffer.
            reinitialize_framebuffer();
        }
        // Redraw invalidated UIs.
        bool needs_redraw = false;
        if( !restart_redrawing ) {
            for( auto it = first_enabled; !needs_redraw && it != ui_stack_orig->end(); ++it ) {
                const ui_adaptor &ui = *it;
                if( ui.invalidated && ui.redraw_cb ) {
                    needs_redraw = true;
                }
            }
        }
        if( !restart_redrawing && needs_redraw ) {
            if( !ui_stack_copy ) {
                // Callbacks may change the UI stack; make a copy of the original one.
                ui_stack_copy = std::make_unique<ui_stack_t>( *ui_stack_orig );
                first_enabled = ui_stack_copy->begin() + ( first_enabled - ui_stack_orig->begin() );
                ui_stack_orig = &*ui_stack_copy;
            }
            for( auto it = first_enabled; !restart_redrawing && it != ui_stack_orig->end(); ++it ) {
                const ui_adaptor &ui = *it;
                if( ui.invalidated ) {
                    if( ui.redraw_cb ) {
                        ui.redraw_cb( ui );
                    }
                    if( !restart_redrawing ) {
                        ui.invalidated = false;
                    }
                }
            }
        }
    } while( restart_redrawing );
}
References redraw_in_progress, reinitialize_framebuffer(), restart_redrawing, test_mode, and ui_stack.
Referenced by redraw(), and ui_manager::redraw_invalidated().
reset()
void ui_adaptor::reset ()
Reset all callbacks and dimensions.
Will cause invalidation of the previously specified screen area.
Definition at line 226 of file ui_manager.cpp.
{
    on_screen_resize( nullptr );
    on_redraw( nullptr );
    position( point_zero, point_zero );
}
References on_redraw(), on_screen_resize(), point_zero, and position().
screen_resized()
void ui_adaptor::screen_resized () static
Definition at line 358 of file ui_manager.cpp.
{
    // Always mark every UI for resize even if it is below another UI with
    // `disable_uis_below`, so when the UI with `disable_uis_below` is removed,
    // UIs below are correctly marked for resize.
    for( ui_adaptor &ui : ui_stack ) {
        ui.deferred_resize = true;
    }
    redraw();
}
References redraw(), and ui_stack.
Referenced by ui_manager::screen_resized().
Member Data Documentation
deferred_resize
bool ui_adaptor::deferred_resize mutable private
Definition at line 185 of file ui_manager.h.
Referenced by mark_resize().
dimensions
rectangle<point> ui_adaptor::dimensions private
Definition at line 177 of file ui_manager.h.
Referenced by invalidate(), invalidate_ui(), invalidation_consistency_and_optimization(), position(), position_from_window(), and ~ui_adaptor().
disabling_uis_below
bool ui_adaptor::disabling_uis_below private
Definition at line 181 of file ui_manager.h.
Referenced by ~ui_adaptor().
invalidated
bool ui_adaptor::invalidated mutable private
Definition at line 184 of file ui_manager.h.
Referenced by invalidate(), invalidate_ui(), invalidation_consistency_and_optimization(), position(), and position_from_window().
is_debug_message_ui
bool ui_adaptor::is_debug_message_ui private
Definition at line 182 of file ui_manager.h.
Referenced by ~ui_adaptor().
redraw_cb
redraw_callback_t ui_adaptor::redraw_cb private
Definition at line 178 of file ui_manager.h.
Referenced by on_redraw().
screen_resized_cb
screen_resize_callback_t ui_adaptor::screen_resized_cb private
Definition at line 179 of file ui_manager.h.
Referenced by on_screen_resize().
The documentation for this class was generated from the following files:
src/ui_manager.h
src/ui_manager.cpp