Cataclysm BN: player_morale::morale_subtype Class Reference
player_morale::morale_subtype Class Reference
Public Member Functions
morale_subtype ()
morale_subtype (const itype &item_type)
morale_subtype (const efftype_id &eff_type)
bool has_description () const
std::string describe () const
bool matches (const morale_subtype &other) const
bool operator== (const morale_subtype &other) const
void deserialize (JsonIn &jsin)
void serialize (JsonOut &json) const
Private Attributes
morale_subtype_t subtype_type = morale_subtype_t::single
const itype * item_type = nullptr
efftype_id eff_type
Detailed Description
Definition at line 100 of file morale.h.
Constructor & Destructor Documentation
morale_subtype() [1/3]
player_morale::morale_subtype::morale_subtype () default
morale_subtype() [2/3]
player_morale::morale_subtype::morale_subtype (const itype & item_type) inline
Definition at line 104 of file morale.h.
                    : subtype_type( morale_subtype_t::by_item )
                    , item_type( &item_type ) {};
morale_subtype() [3/3]
player_morale::morale_subtype::morale_subtype (const efftype_id & eff_type) inline
Definition at line 107 of file morale.h.
                    : subtype_type( morale_subtype_t::by_effect )
                    , eff_type( eff_type ) {};
Member Function Documentation
describe()
std::string player_morale::morale_subtype::describe () const
Definition at line 1185 of file morale.cpp.
{
    switch( subtype_type ) {
        case morale_subtype_t::by_item:
            return item_type->nname( 1 );
        // TODO: Implement (may need passing an entire effect here...)
        case morale_subtype_t::by_effect:
        default:
            debugmsg( "Tried to get description from morale_subtype \"%s\"",
                      io::enum_to_string<morale_subtype_t>( subtype_type ) );
            return "ERROR";
    }
}
References by_effect, by_item, debugmsg, and io::enum_to_string< morale_subtype_t >().
Referenced by player_morale::add(), and player_morale::morale_point::get_name().
deserialize()
void player_morale::morale_subtype::deserialize (JsonIn & jsin)
Definition at line 3134 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "subtype_type", subtype_type );
    switch( subtype_type ) {
        case morale_subtype_t::single:
            break;
        case morale_subtype_t::by_item:
            item_type = &*itype_id( jo.get_string( "item_type" ) );
            break;
        case morale_subtype_t::by_effect:
            eff_type = efftype_id( jo.get_string( "eff_type" ) );
            break;
        default:
            debugmsg( "invalid or missing morale_subtype_t: %d",
                      static_cast<int>( subtype_type ) );
            subtype_type = morale_subtype_t::single;
    }
}
References JsonObject::allow_omitted_members(), by_effect, by_item, debugmsg, efftype_id, JsonIn::get_object(), JsonObject::get_string(), itype_id, JsonObject::read(), and single.
has_description()
bool player_morale::morale_subtype::has_description () const
Definition at line 1178 of file morale.cpp.
{
    return subtype_type == morale_subtype_t::by_item;
}
References by_item, and subtype_type.
Referenced by player_morale::add(), and player_morale::morale_point::get_name().
matches()
bool player_morale::morale_subtype::matches (const morale_subtype & other) const inline
Definition at line 115 of file morale.h.
{
                    return *this == other;
                }
References other.
operator==()
bool player_morale::morale_subtype::operator== (const morale_subtype & other) const inline
Definition at line 118 of file morale.h.
{
                    if( subtype_type != other.subtype_type ) {
                        return false;
                    }
                    switch( subtype_type ) {
                        case morale_subtype_t::single:
                            return true;
                        case morale_subtype_t::by_item:
                            return item_type == other.item_type;
                        case morale_subtype_t::by_effect:
                            return eff_type == other.eff_type;
                        default:
                            // Error!
                            return false;
                    }
                }
References by_effect, by_item, eff_type, item_type, other, single, and subtype_type.
serialize()
void player_morale::morale_subtype::serialize (JsonOut & json) const
Definition at line 3115 of file savegame_json.cpp.
{
    json.start_object();
    json.member_as_string( "subtype_type", subtype_type );
    switch( subtype_type ) {
        case morale_subtype_t::single:
            break;
        case morale_subtype_t::by_item:
            json.member( "item_type", item_type->get_id() );
            break;
        case morale_subtype_t::by_effect:
            json.member( "eff_type", eff_type );
            break;
        default:
            break;
    }
    json.end_object();
}
References by_effect, by_item, JsonOut::end_object(), JsonOut::member(), JsonOut::member_as_string(), single, and JsonOut::start_object().
Member Data Documentation
eff_type
efftype_id player_morale::morale_subtype::eff_type private
Definition at line 141 of file morale.h.
Referenced by operator==().
item_type
const itype* player_morale::morale_subtype::item_type = nullptr private
Definition at line 140 of file morale.h.
Referenced by operator==().
subtype_type
morale_subtype_t player_morale::morale_subtype::subtype_type = morale_subtype_t::single private
Definition at line 139 of file morale.h.
Referenced by has_description(), and operator==().
The documentation for this class was generated from the following files:
src/morale.h
src/morale.cpp
src/savegame_json.cpp