Cataclysm BN: disassemble_inventory_preset Class Reference
disassemble_inventory_preset Class Reference
Public Member Functions
disassemble_inventory_preset (const player &p, const inventory &inv)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from pickup_inventory_preset
pickup_inventory_preset (const player &p)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Protected Member Functions
const recipe & get_recipe (const item_location &loc) const
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const player & p
const inventory & inv
Additional Inherited Members
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Detailed Description
Definition at line 449 of file game_inventory.cpp.
Constructor & Destructor Documentation
disassemble_inventory_preset()
disassemble_inventory_preset::disassemble_inventory_preset (const player & p, const inventory & inv) inline
Definition at line 452 of file game_inventory.cpp.
                                                                              :
            pickup_inventory_preset( p ), p( p ), inv( inv ) {
            check_components = true;
            append_cell( [ this ]( const item_location & loc ) {
                const auto &req = get_recipe( loc ).disassembly_requirements();
                if( req.is_empty() ) {
                    return std::string();
                }
                const item *i = loc.get_item();
                const auto components = i->get_uncraft_components();
                return enumerate_as_string( components.begin(), components.end(),
                []( const decltype( components )::value_type & comps ) {
                    return comps.to_string();
                } );
            }, _( "YIELD" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return to_string_clipped( time_duration::from_turns( get_recipe( loc ).time / 100 ) );
            }, _( "TIME" ) );
        }
References _, inventory_selector_preset::append_cell(), inventory_selector_preset::check_components, recipe::disassembly_requirements(), enumerate_as_string(), time_duration::from_turns(), item_location::get_item(), get_recipe(), item::get_uncraft_components(), and to_string_clipped().
Member Function Documentation
get_denial()
std::string disassemble_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from pickup_inventory_preset.
Definition at line 479 of file game_inventory.cpp.
{
            const ret_val<bool> ret = crafting::can_disassemble( p, *loc, inv );
            if( !ret.success() ) {
                return ret.str();
            }
            return pickup_inventory_preset::get_denial( loc );
        }
References crafting::can_disassemble(), pickup_inventory_preset::get_denial(), inv, p, and cata::hash64_detail::ret.
get_recipe()
const recipe & disassemble_inventory_preset::get_recipe (const item_location & loc) const inline protected
Definition at line 488 of file game_inventory.cpp.
{
            return recipe_dictionary::get_uncraft( loc->typeId() );
        }
References recipe_dictionary::get_uncraft(), and item::typeId().
Referenced by disassemble_inventory_preset(), and is_shown().
is_shown()
bool disassemble_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 475 of file game_inventory.cpp.
{
            return get_recipe( loc );
        }
References get_recipe().
Member Data Documentation
inv
const inventory& disassemble_inventory_preset::inv private
Definition at line 494 of file game_inventory.cpp.
Referenced by get_denial().
p
const player& disassemble_inventory_preset::p private
Definition at line 493 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp