Cataclysm BN: player Class Reference
player Class Reference abstract
#include <player.h>
Public Member Functions
player ()
player (const player &)=delete
player (player &&)
~player () override
player & operator= (const player &)=delete
player & operator= (player &&)
void normalize () override
Calls Character::normalize() normalizes HP and body temperature.
bool is_player () const override
player * as_player () override
const player * as_player () const override
bool is_npc () const override
virtual void deserialize (JsonIn &jsin)=0
virtual void serialize (JsonOut &jsout) const =0
bool can_grab_break (const item &weap) const
Returns true if the player is able to use a grab breaking technique.
int gun_engagement_moves (const item &gun, int target=0, int start=MAX_RECOIL) const
How many moves does it take to aim gun to the target accuracy.
int fire_gun (const tripoint &target, int shots=1)
Fires a gun or auxiliary gunmod (ignoring any current mode)
int fire_gun (const tripoint &target, int shots, item &gun)
Fires a gun or auxiliary gunmod (ignoring any current mode)
void on_dodge (Creature *source, float difficulty) override
Called after the player has successfully dodged an attack.
void on_hit (Creature *source, bodypart_id bp_hit, float difficulty=INT_MIN, dealt_projectile_attack const *proj=nullptr) override
Handles special defenses from an attack that hit us (source can be null)
float get_melee () const override
Returns melee skill level, to be used to throttle dodge practice.
bool uncanny_dodge () override
Handles the uncanny dodge bionic and effects, returns true if the player successfully dodges.
dealt_projectile_attack throw_item (const tripoint &target, const item &to_throw, const cata::optional< tripoint > &blind_throw_from_pos=cata::nullopt)
Execute a throw.
bool immune_to (body_part bp, damage_unit dam) const
Check if a given body part is immune to a given damage type.
void knock_back_to (const tripoint &to) override
Knocks the player to a specified tile.
float fall_damage_mod () const override
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
int impact (int force, const tripoint &pos) override
Deals falling/collision damage with terrain/creature at pos.
int hp_percentage () const override
Returns overall % of HP remaining.
int drink_from_hands (item &water)
used for drinking from hands, returns how many charges were consumed
bool consume (item_location loc)
Used for eating object at pos, returns true if object is removed from inventory (last charge was consumed)
bool consume_item (item &target)
Used for eating a particular item that doesn't need to be in inventory.
bool eat (item &food, bool force=false)
Used for eating entered comestible, returns true if comestible is successfully eaten.
int get_lift_assist () const
bool list_ammo (const item &base, std::vector< item::reload_option > &ammo_list, bool include_empty_mags=true, bool include_potential=false) const
item::reload_option select_ammo (const item &base, bool prompt=false, bool include_empty_mags=true, bool include_potential=false) const
Select suitable ammo with which to reload the item.
item::reload_option select_ammo (const item &base, std::vector< item::reload_option > opts) const
Select ammo from the provided options.
bool can_lift (int lift_strength_required) const
Check player strong enough to lift an object unaided by equipment (jacks, levers etc)
ret_val< bool > can_takeoff (const item &it, const std::list< item > *res=nullptr) const
Check player capable of taking off an item.
ret_val< bool > can_wield (const item &it) const
Check player capable of wielding an item.
bool unwield ()
bool can_reload (const item &it, const itype_id &ammo=itype_id()) const
Whether a tool or gun is potentially reloadable (optionally considering a specific ammo)
void mend_item (item_location &&obj, bool interactive=true)
Attempt to mend an item (fix any current faults)
int item_reload_cost (const item &it, const item &ammo, int qty) const
Calculate (but do not deduct) the number of moves required to reload an item with specified quantity of ammo.
cata::optional< std::list< item >::iterator > wear (int pos, bool interactive=true)
Wear item; returns false on fail.
cata::optional< std::list< item >::iterator > wear (item &to_wear, bool interactive=true)
bool takeoff (item &it, std::list< item > *res=nullptr)
Takes off an item, returning false on fail.
bool takeoff (int pos)
bool add_or_drop_with_msg (item &it, bool unloading=false)
So far only called by unload() from game.cpp.
bool unload (item_location loc)
bool wield_contents (item &container, item *internal_item=nullptr, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
void store (item &container, item &put, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY)
Stores an item inside another consuming moves proportional to weapon skill and volume.
void sort_armor ()
Draws the UI and handles player input for the armor re-ordering window.
void use (int inventory_position)
Uses a tool.
void use (item_location loc)
Uses a tool at location.
void use_wielded ()
Uses the current wielded weapon.
void reassign_item (item &it, int invlet)
Reassign letter.
bool gunmod_remove (item &gun, item &mod)
Removes gunmod after first unloading any contained ammo and returns true on success.
void gunmod_add (item &gun, item &mod)
Starts activity to install gunmod having warned user about any risk of failure or irremovable mods s.
std::pair< int, int > gunmod_installation_odds (const item &gun, const item &mod) const
void toolmod_add (item_location tool, item_location mod)
Starts activity to install toolmod.
virtual bool has_identified (const itype_id &item_id) const =0
Note that we've read a book at least once.
safe_reference< player > get_safe_reference ()
bool add_faction_warning (const faction_id &id)
int current_warnings_fac (const faction_id &id)
bool beyond_final_warning (const faction_id &id)
void practice (const skill_id &id, int amount, int cap=99, bool suppress_warning=false)
This handles giving xp for a skill.
void handle_skill_warning (const skill_id &id, bool force_warning=false)
This handles warning the player that there current activity will not give them xp.
void on_worn_item_transform (const item &old_it, const item &new_it)
item reduce_charges (int position, int quantity)
Remove charges from a specific item (given by its item position).
item reduce_charges (item *it, int quantity)
Remove charges from a specific item (given by a pointer to it).
bool has_gun_for_ammo (const ammotype &at) const
Check whether the player has a gun that uses the given type of ammo.
bool has_magazine_for_ammo (const ammotype &at) const
int has_recipe (const recipe *r, const inventory &crafting_inv, const std::vector< npc * > &helpers) const
bool has_recipe_requirements (const recipe &rec) const
bool studied_all_recipes (const itype &book) const
recipe_subset get_recipes_from_books (const inventory &crafting_inv, recipe_filter filter=nullptr) const
Returns all recipes that are known from the books (either in inventory or nearby).
recipe_subset get_available_recipes (const inventory &crafting_inv, const std::vector< npc * > *helpers=nullptr, recipe_filter filter=nullptr) const
Returns all available recipes (from books and npc companions)
int available_assistant_count (const recipe &rec) const
For use with in progress crafts.
int base_time_to_craft (const recipe &rec, int batch_size=1) const
Time to craft not including speed multiplier.
int expected_time_to_craft (const recipe &rec, int batch_size=1, bool in_progress=false) const
Expected time to craft a recipe, with assumption that multipliers stay constant.
std::vector< const item * > get_eligible_containers_for_crafting () const
bool check_eligible_containers_for_crafting (const recipe &rec, int batch_size=1) const
bool can_make (const recipe *r, int batch_size=1)
bool can_start_craft (const recipe *rec, recipe_filter_flags, int batch_size=1)
Returns true if the player can start crafting the recipe with the given batch size The player is not required to have enough tool charges to finish crafting, only to complete the first step (total / 20 + total % 20 charges)
bool making_would_work (const recipe_id &id_to_make, int batch_size)
void craft (const tripoint &loc=tripoint_zero)
Start various types of crafts.
void recraft (const tripoint &loc=tripoint_zero)
void long_craft (const tripoint &loc=tripoint_zero)
void make_craft (const recipe_id &id, int batch_size, const tripoint &loc=tripoint_zero)
void make_all_craft (const recipe_id &id, int batch_size, const tripoint &loc=tripoint_zero)
item_location start_craft (craft_command &command, const tripoint &loc)
consume components and create an active, in progress craft containing them
double crafting_success_roll (const recipe &making) const
Calculate a value representing the success of the player at crafting the given recipe, taking player skill, recipe difficulty, npc helpers, and player mutations into account.
bool can_continue_craft (item &craft)
Check if the player meets the requirements to continue the in progress craft and if unable to continue print messages explaining the reason.
std::vector< npc * > get_crafting_helpers (size_t max=0) const
Returns nearby NPCs ready and willing to help with crafting or some other manual task.
void craft_skill_gain (const item &craft, const int &multiplier)
Handle skill gain for player and followers during crafting.
const requirement_data * select_requirements (const std::vector< const requirement_data * > &, int batch, const inventory &, const std::function< bool(const item &)> &filter) const
comp_selection< item_comp > select_item_component (const std::vector< item_comp > &components, int batch, inventory &map_inv, bool can_cancel=false, const std::function< bool(const item &)> &filter=return_true< item >, bool player_inv=true)
std::list< item > consume_items (const comp_selection< item_comp > &is, int batch, const std::function< bool(const item &)> &filter=return_true< item >)
std::list< item > consume_items (map &m, const comp_selection< item_comp > &is, int batch, const std::function< bool(const item &)> &filter=return_true< item >, const tripoint &origin=tripoint_zero, int radius=PICKUP_RANGE)
std::list< item > consume_items (const std::vector< item_comp > &components, int batch=1, const std::function< bool(const item &)> &filter=return_true< item >)
bool craft_consume_tools (item &craft, int mulitplier, bool start_craft)
Consume tools for the next multiplier * 5% progress of the craft.
void consume_tools (const comp_selection< tool_comp > &tool, int batch)
void consume_tools (map &m, const comp_selection< tool_comp > &tool, int batch, const tripoint &origin=tripoint_zero, int radius=PICKUP_RANGE, basecamp *bcp=nullptr)
void consume_tools (const std::vector< tool_comp > &tools, int batch=1, const std::string &hotkeys=DEFAULT_HOTKEYS)
void make_craft_with_command (const recipe_id &id_to_make, int batch_size, bool is_long=false, const tripoint &loc=tripoint_zero)
void mod_stat (const std::string &stat, float modifier) override
void add_msg_if_player (const std::string &msg) const override
void add_msg_if_player (const game_message_params &params, const std::string &msg) const override
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_str) const override
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg) const override
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech) const override
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech) const override
bool query_yn (const std::string &mes) const override
void disarm (npc &target)
Try to disarm the NPC.
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args) const
It is supposed to hide the query_yn to simplify player vs.
virtual bool query_yn (const std::string &msg) const=0
Public Member Functions inherited from Character
Character (const Character &)=delete
Character & operator= (const Character &)=delete
~Character () override
Character * as_character () override
const Character * as_character () const override
character_id getID () const
void setID (character_id i, bool force=false)
bool is_dead_state () const override
Returns true if the character should be dead.
field_type_id bloodType () const override
field_type_id gibType () const override
bool is_warm () const override
bool in_species (const species_id &spec) const override
const std::string & symbol () const override
virtual int get_str () const
Getters for stats exclusive to characters.
virtual int get_dex () const
virtual int get_per () const
virtual int get_int () const
virtual int get_str_base () const
virtual int get_dex_base () const
virtual int get_per_base () const
virtual int get_int_base () const
virtual int get_str_bonus () const
virtual int get_dex_bonus () const
virtual int get_per_bonus () const
virtual int get_int_bonus () const
int get_speed () const override
virtual int ranged_dex_mod () const
virtual int ranged_per_mod () const
virtual void set_str_bonus (int nstr)
Setters for stats exclusive to characters.
virtual void set_dex_bonus (int ndex)
virtual void set_per_bonus (int nper)
virtual void set_int_bonus (int nint)
virtual void mod_str_bonus (int nstr)
virtual void mod_dex_bonus (int ndex)
virtual void mod_per_bonus (int nper)
virtual void mod_int_bonus (int nint)
void print_health () const
virtual int get_healthy () const
Getters for health values exclusive to characters.
virtual int get_healthy_mod () const
virtual void mod_healthy (int nhealthy)
Modifiers for health values exclusive to characters.
virtual void mod_healthy_mod (int nhealthy_mod, int cap)
virtual void set_healthy (int nhealthy)
Setters for health values exclusive to characters.
virtual void set_healthy_mod (int nhealthy_mod)
int get_stored_kcal () const
Getter for need values exclusive to characters.
int max_stored_kcal () const
float get_kcal_percent () const
int get_thirst () const
std::pair< std::string, nc_color > get_thirst_description () const
std::pair< std::string, nc_color > get_hunger_description () const
std::pair< std::string, nc_color > get_fatigue_description () const
int get_fatigue () const
int get_sleep_deprivation () const
std::pair< std::string, nc_color > get_pain_description () const override
virtual void mod_stored_kcal (int nkcal)
Modifiers for need values exclusive to characters.
virtual void mod_stored_nutr (int nnutr)
virtual void mod_thirst (int nthirst)
virtual void mod_fatigue (int nfatigue)
virtual void mod_sleep_deprivation (int nsleep_deprivation)
virtual void set_stored_kcal (int kcal)
Setters for need values exclusive to characters.
virtual void set_thirst (int nthirst)
virtual void set_fatigue (int nfatigue)
virtual void set_sleep_deprivation (int nsleep_deprivation)
m_size get_size () const override
Get size class of character.
void recalculate_size ()
Recalculate size class of character.
void recalc_speed_bonus ()
Calculates the various speed bonuses we will get from mutations, etc.
std::string disp_name (bool possessive=false, bool capitalize_first=false) const override
Returns either "you" or the player's name.
std::string skin_name () const override
Returns the name of the player's outer layer, e.g.
virtual faction * get_faction () const
void set_fac_id (const std::string &my_fac_id)
int effective_dispersion (int dispersion) const
dispersion_sources get_weapon_dispersion (const item &obj) const
Returns a weapon's modified dispersion value.
std::vector< aim_type > get_aim_types (const item &gun) const
std::pair< int, int > get_fastest_sight (const item &gun, double recoil) const
int get_most_accurate_sight (const item &gun) const
double aim_speed_skill_modifier (const skill_id &gun_skill) const
double aim_speed_dex_modifier () const
double aim_speed_encumbrance_modifier () const
double aim_cap_from_volume (const item &gun) const
double aim_per_move (const item &gun, double recoil) const
double recoil_vehicle () const
Get maximum recoil penalty due to vehicle motion.
double recoil_mode () const
double recoil_total () const
Current total maximum recoil penalty from all sources.
float get_dodge_base () const override
Combat getters.
float get_hit_base () const override
float get_dodge () const override
float dodge_roll () override
const tripoint & pos () const override
int sight_range (int light_level) const override
Returns the player's sight range.
int unimpaired_range () const
Returns the player maximum vision range factoring in mutations, diseases, and other effects.
bool overmap_los (const tripoint_abs_omt &omt, int sight_points)
Returns true if overmap tile is within player line-of-sight.
int overmap_sight_range (int light_level) const
Returns the distance the player can see on the overmap.
int clairvoyance () const
Returns the distance the player can see through walls.
bool sight_impaired () const
Returns true if the player has some form of impaired sight.
bool has_alarm_clock () const
Returns true if the player or their vehicle has an alarm clock.
bool has_watch () const
Returns true if the player or their vehicle has a watch.
void action_taken ()
Called after every action, invalidates player caches.
bool is_on_ground () const override
Returns true if the player is knocked over or has broken legs.
int swim_speed () const
Returns the player's speed for swimming across water tiles.
void add_miss_reason (const std::string &reason, unsigned int weight)
Adds a reason for why the player would miss a melee attack.
void clear_miss_reasons ()
Clears the list of reasons for why the player would miss a melee attack.
std::string get_miss_reason ()
Returns an explanation for why the player would miss a melee attack.
void regen (int rate_multiplier)
Handles passive regeneration of pain and maybe hp.
void enforce_minimum_healing ()
item * best_quality_item (const quality_id &qual)
get best quality item that this character has
virtual void update_health (int external_modifiers=0)
Handles health fluctuations over time.
void update_body ()
Updates all "biology" by one turn.
void update_body (const time_point &from, const time_point &to)
Updates all "biology" as if time between from and to passed.
void update_stomach (const time_point &from, const time_point &to)
Updates the stomach to give accurate hunger messages.
void update_needs (int rate_multiplier)
Increases hunger, thirst, fatigue and stimulants wearing off.
needs_rates calc_needs_rates () const
void check_needs_extremes ()
Kills the player if too hungry, stimmed up etc., forces tired player to sleep and prints warnings.
bool is_hibernating () const
Returns if the player has hibernation mutation and is asleep and well fed.
void update_bodytemp (const map &m, const weather_manager &weather)
Maintains body temperature.
void temp_equalizer (const bodypart_id &bp1, const bodypart_id &bp2)
Equalizes heat between body parts.
int blood_loss (const bodypart_id &bp) const
Define blood loss (in percents)
void reset_bonuses () override
Resets the value of all bonus fields to 0.
void reset_stats () override
Resets stats, and applies effects in an idempotent manner.
void reset () override
Handles stat and bonus reset.
void environmental_revert_effect ()
void reset_encumbrance ()
Recalculates encumbrance cache.
int encumb (body_part bp) const
Returns ENC provided by armor, etc.
units::mass get_weight () const override
Returns body weight plus weight of inventory and worn/wielded items.
char_encumbrance_data get_encumbrance () const
Get encumbrance for all body parts.
char_encumbrance_data get_encumbrance (const item &new_item) const
Get encumbrance for all body parts as if new_item was also worn.
int extraEncumbrance (layer_level level, int bp) const
Get encumbrance penalty per layer & body part.
bool is_wearing_power_armor (bool *hasHelmet=nullptr) const
Returns true if the character is wearing power armor.
bool is_wearing_active_power_armor () const
Returns true if the character is wearing active power.
bool is_wearing_active_optcloak () const
Returns true if the player is wearing an active optical cloak.
bool in_climate_control ()
Returns true if the player is in a climate controlled area or armor.
bool is_blind () const
Returns true if the player isn't able to see.
bool is_invisible () const
int visibility (bool check_color=false, int stillness=0) const
Checks is_invisible() as well as other factors.
float active_light () const
Returns character luminosity based on the brightest active item they are carrying.
bool sees_with_specials (const Creature &critter) const
body_part_set exclusive_flag_coverage (const std::string &flag) const
Bitset of all the body parts covered only with items with flag (or nothing)
bool move_effects (bool attacking) override
Processes effects which may prevent the Character from moving (bear traps, crushed, etc.).
void wait_effects ()
bool movement_mode_is (character_movemode mode) const
Check against the character's current movement mode.
character_movemode get_movement_mode () const
virtual void set_movement_mode (character_movemode mode)=0
void expose_to_disease (diseasetype_id dis_type)
Determine if character is susceptible to dis_type and if so apply the symptoms.
void process_turn () override
Handles end-of-turn processing.
void process_effects_internal () override
Processes human-specific effects of effects before calling Creature::process_effects().
void hardcoded_effects (effect &it)
Handles the still hard-coded effects.
void process_one_effect (effect &it, bool is_new) override
Processes human-specific effects of an effect.
void process_items ()
Process active items.
void recalc_hp ()
Recalculates HP after a change to max strength.
void calc_all_parts_hp (float hp_mod=0.0, float hp_adjust=0.0, int str_max=0)
Sets hp for all body parts.
void recalc_sight_limits ()
Modifies the player's sight values Must be called when any of the following change: This must be called when any of the following change:
float get_vision_threshold (float light_level) const
Returns the apparent light level at which the player can see.
void flag_encumbrance ()
Flag encumbrance for updating.
void check_item_encumbrance_flag ()
Checks worn items for the "RESET_ENCUMBRANCE" flag, which indicates that encumbrance may have changed and require recalculating.
bool natural_attack_restricted_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body_part, ignoring items with the ALLOWS_NATURAL_ATTACKS flag.
bool can_miss_recovery (const item &weap) const
Returns true if the player is able to use a miss recovery technique.
bool is_quiet () const
Returns true if the player has quiet melee attacks.
bool is_stealthy () const
Returns true if the player has stealthy movement.
bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &dam) override
Checks for valid block abilities and reduces damage accordingly.
item & best_shield ()
Returns the best item for blocking with.
bool handle_melee_wear (item &shield, float wear_multiplier=1.0f)
Calculates melee weapon wear-and-tear through use, returns true if item is destroyed.
matec_id pick_technique (Creature &t, const item &weap, bool crit, bool dodge_counter, bool block_counter)
Returns a random valid technique.
void perform_technique (const ma_technique &technique, Creature &t, damage_instance &di, int &move_cost)
void melee_attack (Creature &t, bool allow_special, const matec_id *force_technique=nullptr, bool allow_unarmed=true)
Sets up a melee attack and handles melee attack function calls.
std::string melee_special_effects (Creature &t, damage_instance &d, item &weap)
Handles combat effects, returns a string of any valid combat effect messages.
void perform_special_attacks (Creature &t, dealt_damage_instance &dealt_dam)
Performs special attacks and their effects (poisonous, stinger, etc.)
void reach_attack (const tripoint &p)
Handles reach melee attack on point p.
float stability_roll () const override
Returns value of player's stable footing.
std::vector< special_attack > mutation_attacks (Creature &t) const
Returns a vector of valid mutation attacks.
float bonus_damage (bool random) const
Returns the bonus bashing damage the player deals based on their stats.
float get_melee_hit_base () const
Returns weapon skill.
float hit_roll () const override
Returns the player's basic hit roll that is compared to the target's dodge roll.
double crit_chance (float roll_hit, float target_dodge, const item &weap) const
Returns the chance to critical given a hit roll and target's dodge roll.
bool scored_crit (float target_dodge, const item &weap) const
Returns true if the player scores a critical hit.
int attack_cost (const item &weap) const
Returns cost (in moves) of attacking with given item (no modifiers, like stuck)
float get_hit_weapon (const item &weap) const
Gets melee accuracy component from weapon+skills.
void roll_all_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds all 3 types of physical damage to instance.
void roll_bash_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds player's total bash damage to the damage instance.
void roll_cut_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds player's total cut damage to the damage instance.
void roll_stab_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds player's total stab damage to the damage instance.
void did_hit (Creature &target)
void apply_damage (Creature *source, bodypart_id hurt, int dam, bool bypass_med=false) override
Actually hurt the player, hurts a body_part directly, no armor reduction.
dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &d) override
Calls Creature::deal_damage and handles damaged effects (waking up, etc.)
int reduce_healing_effect (const efftype_id &eff_id, int remove_med, const bodypart_id &hurt)
Reduce healing effect intensity, return initial intensity of the effect.
void cough (bool harmful=false, int loudness=4)
void passive_absorb_hit (const bodypart_id &bp, damage_unit &du) const
Check for relevant passive, non-clothing that can absorb damage, and reduce by specified damage unit.
void absorb_hit (const bodypart_id &bp, damage_instance &dam) override
Runs through all bionics and armor on a part and reduces damage through their armor_absorb.
bool armor_absorb (damage_unit &du, item &armor)
Reduces and mutates du, prints messages about armor taking damage.
float bionic_armor_bonus (const bodypart_id &bp, damage_type dt) const
Check for passive bionics that provide armor, and returns the armor bonus This is called from player::passive_absorb_hit.
int mabuff_armor_bonus (damage_type type) const
Returns the armor bonus against given type from martial arts buffs.
std::map< bodypart_id, int > get_armor_fire (const std::map< bodypart_id, std::vector< const item * > > &clothing_map) const
Returns overall fire resistance.
bool has_trait (const trait_id &b) const override
Returns true if the player has the entered trait.
bool has_base_trait (const trait_id &b) const
Returns true if the player has the entered starting trait.
bool has_trait_flag (const std::string &b) const
Returns true if player has a trait with a flag.
bool has_opposite_trait (const trait_id &flag) const
Returns true if character has a trait which cancels the entered trait.
void toggle_trait (const trait_id &)
Toggles a trait on the player and in their mutation list.
void set_mutation (const trait_id &)
Add or removes a mutation on the player, but does not trigger mutation loss/gain effects.
void unset_mutation (const trait_id &)
void switch_mutations (const trait_id &switched, const trait_id &target, bool start_powered)
Unset switched mutation and set target mutation instead.
void activate_mutation (const trait_id &mutation)
void deactivate_mutation (const trait_id &mut)
void mutation_spend_resources (const trait_id &mut)
Removes the appropriate costs (NOTE: will reapply mods & recalc sightlines in case of newly activated mutation).
bool can_mount (const monster &critter) const
void mount_creature (monster &z)
bool is_mounted () const
bool check_mount_will_move (const tripoint &dest_loc)
bool check_mount_is_spooked ()
void dismount ()
void forced_dismount ()
bool is_deaf () const
bool has_two_arms () const
Returns true if the player has two functioning arms.
int get_working_arm_count () const
Returns the number of functioning arms.
int get_working_leg_count () const
Returns the number of functioning legs.
bool is_limb_disabled (const bodypart_id &limb) const
Returns true if the limb is disabled(12.5% or less hp)
bool is_limb_hindered (hp_part limb) const
Returns true if the limb is hindered(40% or less hp)
bool is_limb_broken (const bodypart_id &limb) const
Returns true if the limb is broken.
bool can_run ()
source of truth of whether a Character can run
void hurtall (int dam, Creature *source, bool disturb=true)
Hurts all body parts for dam, no armor reduction.
int hitall (int dam, int vary, Creature *source)
Harms all body parts for dam, with armor reduction.
void on_hurt (Creature *source, bool disturb=true)
Handles effects that happen when the player is damaged and aware of the fact.
void heal (const bodypart_id &healed, int dam)
Heals a body_part for dam.
void healall (int dam)
Heals all body parts for dam.
hp_part body_window (const std::string &menu_header, bool show_all, bool precise, int normal_bonus, int head_bonus, int torso_bonus, float bleed, float bite, float infect, float bandage_power, float disinfectant_power) const
Displays menu with body part hp, optionally with hp estimation after healing.
nc_color limb_color (const bodypart_id &bp, bool bleed, bool bite, bool infect) const
bool made_of (const material_id &m) const override
bool made_of_any (const std::set< material_id > &ms) const override
int posx () const override
int posy () const override
int posz () const override
void setx (int x)
void sety (int y)
void setz (int z)
void setpos (const tripoint &p) override
virtual tripoint global_square_location () const
Global position, expressed in map square coordinate system (the most detailed coordinate system), used by the map.
tripoint global_sm_location () const
Returns the location of the player in global submap coordinates.
tripoint_abs_omt global_omt_location () const
Returns the location of the player in global overmap terrain coordinates.
void recalculate_enchantment_cache ()
void rebuild_mutation_cache ()
double bonus_from_enchantments (double base, enchant_vals::mod value, bool round=false) const
Calculate bonus from enchantments for given base value.
bool has_mabuff (const mabuff_id &buff_id) const
Returns true if the player has any martial arts buffs attached.
bool has_grab_break_tec () const override
Returns true if the player has a grab breaking technique available.
float mabuff_tohit_bonus () const
Returns the to hit bonus from martial arts buffs.
float mabuff_dodge_bonus () const
Returns the dodge bonus from martial arts buffs.
int mabuff_block_bonus () const
Returns the block bonus from martial arts buffs.
int mabuff_speed_bonus () const
Returns the speed bonus from martial arts buffs.
int mabuff_arpen_bonus (damage_type type) const
Returns the arpen bonus from martial arts buffs.
float mabuff_damage_mult (damage_type type) const
Returns the damage multiplier to given type from martial arts buffs.
int mabuff_damage_bonus (damage_type type) const
Returns the flat damage bonus to given type from martial arts buffs, applied after the multiplier.
int mabuff_attack_cost_penalty () const
Returns the flat penalty to move cost of attacks.
float mabuff_attack_cost_mult () const
Returns the multiplier on move cost of attacks.
void mutation_effect (const trait_id &mut)
Handles things like removal of armor, etc.
void mutation_loss_effect (const trait_id &mut)
Handles what happens when you lose a mutation.
bool has_active_mutation (const trait_id &b) const
void mutate ()
Picks a random valid mutation and gives it to the Character, possibly removing/changing others along the way.
bool mutation_ok (const trait_id &mutation, bool force_good, bool force_bad) const
Returns true if the player doesn't have the mutation or a conflicting one and it complies with the force typing.
void mutate_category (const std::string &mut_cat)
Picks a random valid mutation in a category and mutate_towards() it.
bool mutate_towards (std::vector< trait_id > muts, int num_tries=INT_MAX)
Mutates toward one of the given mutations, upgrading or removing conflicts if necessary.
bool mutate_towards (const trait_id &mut)
Mutates toward the entered mutation, upgrading or removing conflicts if necessary.
void remove_mutation (const trait_id &mut, bool silent=false)
Removes a mutation, downgrading to the previous level if possible.
std::map< trait_id, float > mutation_chances () const
Calculate percentage chances for mutations.
bool has_child_flag (const trait_id &flag) const
Returns true if the player has the entered mutation child flag.
void remove_child_flag (const trait_id &flag)
Removes the mutation's child flag from the player's list.
void set_highest_cat_level ()
Recalculates mutation_category_level[] values for the player.
std::string get_highest_category () const
Returns the highest mutation category.
void drench_mut_calc ()
Recalculates mutation drench protection for all bodyparts (ignored/good/neutral stats)
void build_mut_dependency_map (const trait_id &mut, std::unordered_map< trait_id, int > &dependency_map, int distance)
Recursively traverses the mutation's prerequisites and replacements, building up a map.
bool is_category_allowed (const std::vector< std::string > &category) const
Returns true if this category of mutation is allowed.
bool is_category_allowed (const std::string &category) const
bool is_weak_to_water () const
bool can_use_heal_item (const item &med) const
Check for mutation disallowing the use of an healing item.
bool can_install_cbm_on_bp (const std::vector< bodypart_id > &bps) const
resistances mutation_armor (bodypart_id bp) const
Returns resistances on a body part provided by mutations.
float mutation_armor (bodypart_id bp, damage_type dt) const
float mutation_armor (bodypart_id bp, const damage_unit &du) const
bool activate_bionic (bionic &bio, bool eff_only=false)
Handles bionic activation effects of the entered bionic, returns if anything activated.
std::vector< bionic_id > get_bionics () const
bionic & get_bionic_state (const bionic_id &id)
Get state of bionic with given id.
std::pair< int, int > amount_of_storage_bionics () const
Returns amount of Storage CBMs in the corpse.
bool has_bionic (const bionic_id &b) const
Returns true if the player has the entered bionic id.
bool has_active_bionic (const bionic_id &b) const
Returns true if the player has the entered bionic id and it is powered on.
bool has_any_bionic () const
Returns true if the player has any bionic.
bool can_fuel_bionic_with (const item &it) const
Returns true if the character can fuel a bionic with the item.
std::vector< bionic_id > get_bionic_fueled_with (const item &it) const
Return bionic_id of bionics able to use it as fuel.
std::vector< bionic_id > get_fueled_bionics () const
Return bionic_id of fueled bionics.
bionic_id get_remote_fueled_bionic () const
Returns bionic_id of first remote fueled bionic found.
bionic_id get_most_efficient_bionic (const std::vector< bionic_id > &bids) const
Return bionic_id of bionic of most fuel efficient bionic.
std::vector< itype_id > get_fuel_available (const bionic_id &bio) const
Return list of available fuel for this bionic.
int get_fuel_capacity (const itype_id &fuel) const
Return available space to store specified fuel.
int get_total_fuel_capacity (const itype_id &fuel) const
Return total space to store specified fuel.
void update_fuel_storage (const itype_id &fuel)
Updates which bionic contain fuel and which is empty.
int get_mod_stat_from_bionic (const character_stat &Stat) const
Get stat bonus from bionic.
void process_bionic (bionic &bio)
Handles bionic effects over time of the entered bionic.
bool deactivate_bionic (bionic &bio, bool eff_only=false)
Handles bionic deactivation effects of the entered bionic, returns if anything deactivated.
bool has_bionics () const
Whether character has any bionics installed.
void clear_bionics ()
Remove all bionics.
int get_used_bionics_slots (const bodypart_id &bp) const
int get_total_bionics_slots (const bodypart_id &bp) const
int get_free_bionics_slots (const bodypart_id &bp) const
bool has_enough_anesth (const itype *cbm, player &patient)
Has enough anesthetic for surgery.
void introduce_into_anesthesia (const time_duration &duration, player &installer, bool needs_anesthesia)
Handles process of introducing patient into anesthesia during Autodoc operations.
void remove_bionic (const bionic_id &b)
Removes a bionic from my_bionics[].
void add_bionic (const bionic_id &b)
Adds a bionic to my_bionics[].
float env_surgery_bonus (int radius)
Calculate skill bonus from tiles in radius.
float bionics_adjusted_skill (const skill_id &most_important_skill, const skill_id &important_skill, const skill_id &least_important_skill, int skill_level=-1)
Calculate skill for (un)installing bionics.
int bionics_pl_skill (const skill_id &most_important_skill, const skill_id &important_skill, const skill_id &least_important_skill, int skill_level=-1)
Calculate non adjusted skill for (un)installing bionics.
bool can_install_bionics (const itype &type, player &installer, bool autodoc=false, int skill_level=-1)
Is the installation possible.
std::map< bodypart_id, int > bionic_installation_issues (const bionic_id &bioid) const
bool install_bionics (const itype &type, player &installer, bool autodoc=false, int skill_level=-1)
Initialize all the values needed to start the operation player_activity.
void perform_install (bionic_id bid, bionic_id upbid, int difficulty, int success, int pl_skill, const std::string &installer_name, const std::vector< trait_id > &trait_to_rem)
Success or failure of installation happens here.
void do_damage_for_bionic_failure (int min_damage, int max_damage)
void bionics_install_failure (const std::string &installer, int difficulty, int success, float adjusted_skill)
bool can_uninstall_bionic (const bionic_id &b_id, player &installer, bool autodoc=false, int skill_level=-1)
Is The uninstallation possible.
bool uninstall_bionic (const bionic_id &b_id, player &installer, bool autodoc=false, int skill_level=-1)
Initialize all the values needed to start the operation player_activity.
void perform_uninstall (bionic_id bid, int difficulty, int success, const units::energy &power_lvl, int pl_skill)
Succes or failure of removal happens here.
void bionics_uninstall_failure (int difficulty, int success, float adjusted_skill)
When a player fails the surgery.
bool uninstall_bionic (const bionic &target_cbm, monster &installer, player &patient, float adjusted_skill)
Used by monster to perform surgery.
void bionics_uninstall_failure (monster &installer, player &patient, int difficulty, int success, float adjusted_skill)
When a monster fails the surgery.
bool burn_fuel (bionic &bio, bool start=false)
Convert fuel to bionic power.
void passive_power_gen (bionic &bio)
Passively produce power from PERPETUAL fuel.
itype_id find_remote_fuel (bool look_only=false)
Find fuel used by remote powered bionic.
int consume_remote_fuel (int amount)
Consume fuel used by remote powered bionic, return amount of request unfulfilled (0 if totally successful).
void reset_remote_fuel ()
void heat_emission (bionic &bio, int fuel_energy)
Handle heat from exothermic power generation.
float get_effective_efficiency (bionic &bio, float fuel_efficiency)
Applies modifier to fuel_efficiency and returns the resulting efficiency.
units::energy get_power_level () const
units::energy get_max_power_level () const
void mod_power_level (const units::energy &npower)
void mod_max_power_level (const units::energy &npower_max)
void set_power_level (const units::energy &npower)
void set_max_power_level (const units::energy &npower_max)
bool is_max_power () const
bool has_power () const
bool has_max_power () const
bool enough_power_for (const bionic_id &bid) const
void conduct_blood_analysis () const
bool is_worn (const item &thing) const
virtual bool invoke_item (item *, const tripoint &pt)
Asks how to use the item (if it has more than one use_method) and uses it.
virtual bool invoke_item (item *, const std::string &, const tripoint &pt)
As above, but with a pre-selected method.
virtual bool invoke_item (item *)
As above two, but with position equal to current position.
virtual bool invoke_item (item *, const std::string &)
virtual bool dispose_item (item_location &&obj, const std::string &prompt=std::string())
Drop, wear, stash or otherwise try to dispose of an item consuming appropriate moves.
bool has_enough_charges (const item &it, bool show_msg) const
Has the item enough charges to invoke its use function? Also checks if UPS from this player is used instead of item charges.
bool consume_charges (item &used, int qty)
Consume charges of a tool or comestible item, potentially destroying it in the process.
int item_handling_cost (const item &it, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY) const
Calculate (but do not deduct) the number of moves required when handling (e.g.
int item_store_cost (const item &it, const item &container, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY) const
Calculate (but do not deduct) the number of moves required when storing an item in a container.
int item_wear_cost (const item &it) const
Calculate (but do not deduct) the number of moves required to wear an item.
cata::optional< std::list< item >::iterator > wear_item (const item &to_wear, bool interactive=true)
Wear item; returns nullopt on fail, or pointer to newly worn item on success.
int amount_worn (const itype_id &id) const
Returns the amount of item ‘type’ that is currently worn.
std::vector< item_location > nearby (const std::function< bool(const item *, const item *)> &func, int radius=1) const
Returns nearby items which match the provided predicate.
std::list< item > remove_worn_items_with (std::function< bool(item &)> filter)
Similar to remove_items_with, but considers only worn items and not their content (item::contents is not checked).
item * invlet_to_item (int invlet)
Return the item pointer of the item with given invlet, return nullptr if the player does not have such an item with that invlet.
item & i_at (int position)
const item & i_at (int position) const
int get_item_position (const item *it) const
Returns the item position (suitable for i_at or similar) of a specific item.
const item & used_weapon () const
Returns a reference to the item which will be used to make attacks.
item & used_weapon ()
int i_add_to_container (const item &it, bool unloading)
Try to find a container/s on character containing ammo of type it.typeId() and add charges until the container is full.
item & i_add (item it, bool should_stack=true)
item i_rem (int pos)
Remove a specific item from player possession.
item i_rem (const item *it)
Remove a specific item from player possession.
void i_rem_keep_contents (int idx)
bool i_add_or_drop (item &it, int qty=1)
Sets invlet and adds to inventory if possible, drops otherwise, returns true if either succeeded.
std::bitset< std::numeric_limits< char >::max()> allocated_invlets () const
Only use for UI things.
bool has_active_item (const itype_id &id) const
Whether the player carries an active item of the given item type.
item remove_weapon ()
bool has_mission_item (int mission_id) const
void remove_mission_items (int mission_id)
std::vector< const item * > get_ammo (const ammotype &at) const
Returns the items that are ammo and have the matching ammo type.
std::vector< item_location > find_ammo (const item &obj, bool empty=true, int radius=1) const
Searches for ammo or magazines that can be used to reload obj.
std::vector< item_location > find_reloadables ()
Searches for weapons and magazines that can be reloaded.
int ammo_count_for (const item &gun)
Counts ammo and UPS charges (lower of) for a given gun on the character.
int throw_range (const item &) const
Maximum thrown range with a given item, taking all active effects into account.
bool unarmed_attack () const
True if unarmed or wielding a weapon with the UNARMED_WEAPON flag.
int best_nearby_lifting_assist () const
Checks for items, tools, and vehicles with the Lifting quality near the character returning the highest quality in range.
int best_nearby_lifting_assist (const tripoint &world_pos) const
Alternate version if you need to specify a different orign point for nearby vehicle sources of lifting used for operations on distant objects (e.g.
std::vector< item * > inv_dump ()
units::mass weight_carried () const
units::volume volume_carried () const
units::mass weight_carried_reduced_by (const excluded_stacks &without) const
units::volume volume_carried_reduced_by (const excluded_stacks &without) const
units::mass weight_capacity () const override
units::volume volume_capacity () const
units::volume volume_capacity_reduced_by (const units::volume &mod, const excluded_stacks &without={}) const
bool can_pick_volume (const item &it) const
bool can_pick_volume (units::volume volume) const
bool can_pick_weight (const item &it, bool safe=true) const
bool can_pick_weight (units::mass weight, bool safe=true) const
bool can_use (const item &it, const item &context=item()) const
Checks if character stats and skills meet minimum requirements for the item.
ret_val< bool > can_wear (const item &it, bool with_equip_change=false) const
Check character capable of wearing an item.
bool is_armed () const
Returns true if the character is wielding something.
virtual bool wield (item &target)=0
Removes currently wielded item (if any) and replaces it with the target item.
ret_val< bool > can_unwield (const item &it) const
Check player capable of unwielding an item.
ret_val< bool > can_swap (const item &it) const
Check player capable of swapping the side of a worn item.
void drop_invalid_inventory ()
std::list< item * > get_dependent_worn_items (const item &it) const
Returns all items that must be taken off before taking off this item.
void drop (item_location loc, const tripoint &where)
Drops an item to the specified location.
virtual void drop (const drop_locations &what, const tripoint &target, bool stash=false)
virtual bool has_artifact_with (art_effect_passive effect) const
bool is_wielding (const item &target) const
bool covered_with_flag (const std::string &flag, const body_part_set &parts) const
bool is_waterproof (const body_part_set &parts) const
int leak_level (const std::string &flag) const
bool is_wearing (const item &itm) const
Returns true if the player is wearing the item.
bool is_wearing (const itype_id &it) const
Returns true if the player is wearing an item of this type.
bool is_wearing_on_bp (const itype_id &it, const bodypart_id &bp) const
Returns true if the player is wearing the item on the given body part.
bool worn_with_flag (const std::string &flag, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns true if the player is wearing an item with the given flag.
const item * item_worn_with_flag (const std::string &flag, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the first worn item with a given flag.
std::vector< std::string > get_overlay_ids () const
Returns a list of the IDs of overlays on this character, sorted from "lowest" to "highest".
int get_skill_level (const skill_id &ident) const
int get_skill_level (const skill_id &ident, const item &context) const
const SkillLevelMap & get_all_skills () const
SkillLevel & get_skill_level_object (const skill_id &ident)
const SkillLevel & get_skill_level_object (const skill_id &ident) const
void set_skill_level (const skill_id &ident, int level)
void mod_skill_level (const skill_id &ident, int delta)
bool meets_skill_requirements (const std::map< skill_id, int > &req, const item &context=item()) const
Checks whether the character's skills meet the required.
bool meets_skill_requirements (const construction &con) const
Checks whether the character's skills meet the required.
bool meets_stat_requirements (const item &it) const
Checks whether the character's stats meets the stats required by the item.
bool meets_requirements (const item &it, const item &context=item()) const
Checks whether the character meets overall requirements to be able to use the item.
std::string enumerate_unmet_requirements (const item &it, const item &context=item()) const
Returns a string of missed requirements (both stats and skills)
int rust_rate () const
Returns the player's skill rust rate.
int read_speed (bool return_stat_effect=true) const
Returns the player's reading speed.
time_point get_time_died () const
return the calendar::turn the character expired
void set_time_died (const time_point &time)
set the turn the turn the character died if not already done
void die (Creature *nkiller) override
Empty function.
std::string get_name () const override
std::vector< std::string > get_grammatical_genders () const override
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args) const
It is supposed to hide the query_yn to simplify player vs.
bool is_immune_field (const field_type_id &fid) const override
Returns true if we are immune to the field type with the given fid.
bool is_elec_immune () const override
Returns true is the player is protected from electric shocks.
bool is_immune_effect (const efftype_id &) const override
Returns true if the player is immune to this kind of effect.
bool is_immune_damage (damage_type) const override
Returns true if the player is immune to this kind of damage.
bool is_rad_immune () const
Returns true if the player is protected from radiation.
bool is_throw_immune () const
Returns true if the player is immune to throws.
bool has_nv ()
Returns true if the player has some form of night vision.
float rest_quality () const
Returns >0 if character is sitting/lying and relatively inactive.
float healing_rate (float at_rest_quality) const
Average hit points healed per turn.
float healing_rate_medicine (float at_rest_quality, const bodypart_id &bp) const
Average hit points healed per turn from healing effects.
float mutation_value (const std::string &val) const
Goes over all mutations, gets min and max of a value with given name.
social_modifiers get_mutation_social_mods () const
Goes over all mutations, returning the sum of the social modifiers.
nc_color basic_symbol_color () const override
nc_color symbol_color () const override
std::string extended_description () const override
void pick_name (bool bUseDefault=false)
Returns a random name from NAMES_*.
std::vector< trait_id > get_base_traits () const
Get the idents of all base traits.
std::vector< trait_id > get_mutations (bool include_hidden=true) const
Get the idents of all traits/mutations.
const std::bitset< NUM_VISION_MODES > & get_vision_modes () const
void clear_skills ()
Clear the skills map, setting all levels to 0.
void clear_mutations ()
Empties the trait and mutations lists.
bool crossed_threshold () const
Returns true if the player has crossed a mutation threshold Player can only cross one mutation threshold.
void add_addiction (add_type type, int strength)
Adds an addiction to the player.
void rem_addiction (add_type type)
Removes an addition from the player.
bool has_addiction (add_type type) const
Returns true if the player has an addiction of the specified type.
int addiction_level (add_type type) const
Returns the intensity of the specified addiction.
void start_hauling ()
void stop_hauling ()
bool is_hauling () const
bool has_item_with_flag (const std::string &flag, bool need_charges=false) const
std::vector< const item * > all_items_with_flag (const std::string &flag) const
All items that have the given flag (item::has_flag).
bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
std::list< item > use_amount (itype_id it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >)
bool use_charges_if_avail (const itype_id &it, int quantity)
std::list< item > use_charges (const itype_id &what, int qty, const std::function< bool(const item &)> &filter=return_true< item >)
bool has_fire (int quantity) const
void use_fire (int quantity)
void assign_stashed_activity ()
bool check_outbounds_activity (const player_activity &act, bool check_only=false)
void assign_activity (const activity_id &type, int moves=calendar::INDEFINITELY_LONG, int index=-1, int pos=INT_MIN, const std::string &name="")
Legacy activity assignment, does not work for any activites using the new activity_actor class and may cause issues with resuming.
void assign_activity (const player_activity &act, bool allow_resume=true)
Assigns activity to player, possibly resuming old activity if it's similar enough.
bool has_activity (const activity_id &type) const
Check if player currently has a given activity.
bool has_activity (const std::vector< activity_id > &types) const
Check if player currently has any of the given activities.
void resume_backlog_activity ()
void cancel_activity ()
void cancel_stashed_activity ()
player_activity get_stashed_activity () const
void set_stashed_activity (const player_activity &act, const player_activity &act_back=player_activity())
bool has_stashed_activity () const
void initialize_stomach_contents ()
float metabolic_rate_base () const
Stable base metabolic rate due to traits.
float metabolic_rate () const
Current metabolic rate due to traits, hunger, speed, etc.
std::string get_weight_string () const
int get_max_healthy () const
float bmi () const
int bmr () const
void reset_chargen_attributes ()
int base_age () const
void set_base_age (int age)
void mod_base_age (int mod)
int age () const
std::string age_string () const
int base_height () const
void set_base_height (int height)
void mod_base_height (int mod)
std::string height_string () const
int height () const
units::mass bodyweight () const
units::mass bionics_weight () const
int get_armor_bash (bodypart_id bp) const override
Returns overall bashing resistance for the body_part.
int get_armor_cut (bodypart_id bp) const override
Returns overall cutting resistance for the body_part.
int get_armor_bullet (bodypart_id bp) const override
Returns overall bullet resistance for the body_part.
int get_armor_bash_base (bodypart_id bp) const override
Returns bashing resistance from the creature and armor only.
int get_armor_cut_base (bodypart_id bp) const override
Returns cutting resistance from the creature and armor only.
int get_armor_bullet_base (bodypart_id bp) const override
Returns cutting resistance from the creature and armor only.
int get_env_resist (bodypart_id bp) const override
Returns overall env_resist on a body_part.
int get_armor_acid (bodypart_id bp) const
Returns overall acid resistance for the body part.
int get_armor_type (damage_type dt, bodypart_id bp) const override
Returns overall resistance to given type on the bod part.
std::map< bodypart_id, int > get_all_armor_type (damage_type dt, const std::map< bodypart_id, std::vector< const item * > > &clothing_map) const
int get_stim () const
void set_stim (int new_stim)
void mod_stim (int mod)
int get_rad () const
void set_rad (int new_rad)
void mod_rad (int mod)
int get_stamina () const
int get_stamina_max () const
void set_stamina (int new_stamina)
void mod_stamina (int mod)
void burn_move_stamina (int moves)
float stamina_move_cost_modifier () const
void update_stamina (int turns)
Regenerates stamina.
void on_item_wear (const item &it)
Called when an item is worn.
void on_item_takeoff (const item &it)
Called when an item is taken off.
void on_worn_item_washed (const item &it)
Called when an item is washed.
void on_effect_int_change (const efftype_id &effect_type, int intensity, const bodypart_str_id &bp) override
Called when effect intensity has been changed.
void on_mutation_gain (const trait_id &mid)
Called when a mutation is gained.
void on_mutation_loss (const trait_id &mid)
Called when a mutation is lost.
void on_stat_change (const std::string &stat, int value) override
Called when a stat is changed.
tripoint adjacent_tile () const
Returns an unoccupied, safe adjacent point.
void wake_up ()
Removes "sleep" and "lying_down".
int get_shout_volume () const
void shout (std::string msg="", bool order=false)
void vomit ()
Handles Character vomiting effects.
void healed_bp (int bp, int amount)
int adjust_for_focus (int amount) const
void update_type_of_scent (bool init=false)
void update_type_of_scent (const trait_id &mut, bool gain=true)
void set_type_of_scent (const scenttype_id &id)
scenttype_id get_type_of_scent () const
void restore_scent ()
restore scent after masked_scent effect run out or is removed by water
void mod_painkiller (int npkill)
Modifies intensity of painkillers
void set_painkiller (int npkill)
Sets intensity of painkillers
int get_painkiller () const
Returns intensity of painkillers
void react_to_felt_pain (int intensity)
void mod_pain (int npain) override
Modifies a pain value by player traits before passing it to Creature::mod_pain()
void set_pain (int npain) override
Sets new intensity of pain an reacts to it.
int get_perceived_pain () const override
Returns perceived pain (reduced with painkillers)
void spores ()
void blossoms ()
void rooted_message () const
Handles rooting effects.
void rooted ()
void fall_asleep ()
Adds "sleep" to the player.
void fall_asleep (const time_duration &duration)
std::string is_snuggling () const
Checks to see if the player is using floor items to keep warm, and return the name of one such item if so.
float power_rating () const override
Returns an approximation of the creature's strength.
float speed_rating () const override
Returns an approximate number of tiles this creature can travel per turn.
item & item_with_best_of_quality (const quality_id &qid)
Returns the item in the player's inventory with the highest of the specified quality.
bool sees_with_infrared (const Creature &critter) const
Check whether the this player can see the other creature with infrared.
void place_corpse ()
void place_corpse (const tripoint_abs_omt &om_target)
int run_cost (int base_cost, bool diag=false) const
Returns the player's modified base movement cost.
const pathfinding_settings & get_pathfinding_settings () const override
Returns settings for pathfinding.
std::set< tripoint > get_path_avoid () const override
Returns a set of points we do not want to path through.
std::vector< Creature * > get_hostile_creatures (int range) const
Get all hostile creatures currently visible to this player.
std::vector< Creature * > get_visible_creatures (int range) const
Returns all creatures that this player can see and that are in the given range.
std::string visible_mutations (int visibility_cap) const
Returns an enumeration of visible mutations with colors.
player_activity get_destination_activity () const
void set_destination_activity (const player_activity &new_destination_activity)
void clear_destination_activity ()
std::map< bodypart_id, int > warmth (const std::map< bodypart_id, std::vector< const item * > > &clothing_map) const
Returns warmth provided by armor, etc.
bool can_use_floor_warmth () const
Can the player lie down and cover self with blankets etc.
int floor_warmth (const tripoint &pos) const
Final warmth from the floor.
int bodytemp_modifier_traits (bool overheated) const
Correction factor of the body temperature due to traits and mutations.
int bodytemp_modifier_traits_floor () const
Correction factor of the body temperature due to traits and mutations for player lying on the floor.
int temp_corrected_by_climate_control (int temperature) const
Value of the body temperature corrected by climate control.
bool in_sleep_state () const override
void update_vitamins (const vitamin_id &vit)
Set vitamin deficiency/excess disease states dependent upon current vitamin levels.
int vitamin_get (const vitamin_id &vit) const
Check current level of a vitamin.
bool vitamin_set (const vitamin_id &vit, int qty)
Sets level of a vitamin or returns false if id given in vit does not exist.
int vitamin_mod (const vitamin_id &vit, int qty, bool capped=true)
Add or subtract vitamins from character storage pools.
void vitamins_mod (const std::map< vitamin_id, int > &, bool capped=true)
time_duration vitamin_rate (const vitamin_id &vit) const
Get vitamin usage rate (minutes per unit) accounting for bionics, mutations and effects.
int nutrition_for (const item &comest) const
Handles the nutrition value for a comestible.
ret_val< edible_rating > can_eat (const item &food) const
Can the food be [theoretically] eaten no matter the consequen ces?
ret_val< edible_rating > will_eat (const item &food, bool interactive=false) const
Same as can_eat, but takes consequences into account.
bool can_feed_reactor_with (const item &it) const
Determine character's capability of recharging their CBMs.
bool can_feed_furnace_with (const item &it) const
rechargeable_cbm get_cbm_rechargeable_with (const item &it) const
int get_acquirable_energy (const item &it, rechargeable_cbm cbm) const
int get_acquirable_energy (const item &it) const
bool feed_reactor_with (item &it)
Recharge CBMs whenever possible.
bool feed_furnace_with (item &it)
bool fuel_bionic_with (item &it)
void modify_stimulation (const islot_comestible &comest)
Used to apply stimulation modifications from food and medication.
void modify_fatigue (const islot_comestible &comest)
Used to apply fatigue modifications from food and medication.
void modify_radiation (const islot_comestible &comest)
Used to apply radiation from food and medication.
void modify_addiction (const islot_comestible &comest)
Used to apply addiction modifications from food and medication.
void modify_health (const islot_comestible &comest)
Used to apply health modifications from food and medication.
bool consume_effects (item &food)
Handles the effects of consuming an item.
bool can_consume (const item &it) const
Check character's capability of consumption overall.
bool can_estimate_rot () const
True if the character has enough skill (in cooking or survival) to estimate time to rot.
bool can_consume_as_is (const item &it) const
Check whether character can consume this very item.
bool can_consume_for_bionic (const item &it) const
item & get_consumable_from (item &it) const
Returns a reference to the item itself (if it's consumable), the first of its contents (if it's consumable) or null item otherwise.
std::pair< nutrients, nutrients > compute_nutrient_range (const item &, const recipe_id &, const cata::flat_set< std::string > &extra_flags={}) const
Get calorie & vitamin contents for a comestible, taking into account character traits.
std::pair< nutrients, nutrients > compute_nutrient_range (const itype_id &, const cata::flat_set< std::string > &extra_flags={}) const
Same, but across arbitrary recipes.
morale_type allergy_type (const item &food) const
Returns allergy type or MORALE_NULL if not allergic for this character.
nutrients compute_effective_nutrients (const item &) const
bool wearing_something_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body part.
bool is_wearing_helmet () const
Returns true if the character is wearing something occupying the helmet slot.
int head_cloth_encumbrance () const
Returns the total encumbrance of all SKINTIGHT and HELMET_COMPAT items coveringi the head.
double armwear_factor () const
Same as footwear factor, but for arms.
int shoe_type_count (const itype_id &it) const
Returns 1 if the player is wearing an item of that count on one foot, 2 if on both, and zero if on neither.
double footwear_factor () const
Returns 1 if the player is wearing something on both feet, .5 if on one, and 0 if on neither.
bool is_wearing_shoes (const side &which_side=side::BOTH) const
Returns true if the player is wearing something on their feet that is not SKINTIGHT.
bool change_side (item &it, bool interactive=true)
Swap side on which item is worn; returns false on fail.
bool change_side (item_location &loc, bool interactive=true)
bool get_check_encumbrance ()
void set_check_encumbrance (bool new_check)
void update_morale ()
Ticks down morale counters and removes them.
void apply_persistent_morale ()
Ensures persistent morale effects are up-to-date.
void modify_morale (item &food, int nutr=0)
Used to apply morale modifications from food and medication.
int get_morale_level () const
void add_morale (const morale_type &type, int bonus, int max_bonus=0, const time_duration &duration=1_hours, const time_duration &decay_start=30_minutes, bool capped=false, const itype *item_type=nullptr)
bool has_morale (const morale_type &type) const
int get_morale (const morale_type &type) const
void rem_morale (const morale_type &type)
void clear_morale ()
bool has_morale_to_read () const
bool has_morale_to_craft () const
const inventory & crafting_inventory (bool clear_path)
const inventory & crafting_inventory (const tripoint &src_pos=tripoint_zero, int radius=PICKUP_RANGE, bool clear_path=true)
void invalidate_crafting_inventory ()
const recipe_subset & get_learned_recipes () const
Returns all known recipes.
bool knows_recipe (const recipe *rec) const
void learn_recipe (const recipe *rec)
bool can_learn_by_disassembly (const recipe &rec) const
bool check_and_recover_morale ()
Checks permanent morale for consistency and recovers it when an inconsistency is found.
std::pair< int, int > fun_for (const item &comest) const
Handles the enjoyability value for a comestible.
void suffer ()
Handles a large number of timers decrementing and other randomized effects.
bool irradiate (float rads, bool bypass=false)
Handles mitigation and application of radiation.
void mend (int rate_multiplier)
Handles the chance for broken limbs to spontaneously heal to 1 HP.
void sound_hallu ()
Creates an auditory hallucination.
void drench (int saturation, const body_part_set &flags, bool ignore_waterproof)
Drenches the player with water, saturation is the percent gotten wet.
void apply_wetness_morale (int temperature)
Recalculates morale penalty/bonus from wetness based on mutations, equipment and temperature.
std::vector< std::string > short_description_parts () const
std::string short_description () const
int print_info (const catacurses::window &w, int vStart, int vLines, int column) const override
Write information about this creature.
bool can_hear (const tripoint &source, int volume) const
float hearing_ability () const
bool knows_trap (const tripoint &pos) const
void add_known_trap (const tripoint &pos, const trap &t)
bool avoid_trap (const tripoint &pos, const trap &tr) const override
Called when character triggers a trap, returns true if they don't set it off.
nc_color bodytemp_color (int bp) const
Define color for displaying the body temperature.
bool sees (const tripoint &t, bool is_player=false, int range_mod=0) const override
bool sees (const Creature &critter) const override
The functions check whether this creature can see the target.
Attitude attitude_to (const Creature &other) const override
Attitude (of this creature) towards another creature.
int get_lowest_hp () const
bool has_weapon () const override
void shift_destination (const point &shift)
void set_destination (const std::vector< tripoint > &route, const player_activity &new_destination_activity=player_activity())
void clear_destination ()
bool has_distant_destination () const
bool is_auto_moving () const
bool has_destination () const
bool has_destination_activity () const
void start_destination_activity ()
std::vector< tripoint > & get_auto_move_route ()
action_id get_next_auto_move_direction ()
bool defer_move (const tripoint &next)
std::map< bodypart_id, float > bodypart_exposure ()
Map body parts to their total exposure, from 0.0 (fully covered) to 1.0 (buck naked).
void set_underwater (bool x) override
void clear_npc_ai_info_cache (const std::string &key) const
void set_npc_ai_info_cache (const std::string &key, double val) const
cata::optional< double > get_npc_ai_info_cache (const std::string &key) const
bool pour_into (item &container, item &liquid)
Try to pour the given liquid into the given container/vehicle.
bool pour_into (vehicle &veh, item &liquid)
Public Member Functions inherited from Creature
virtual ~Creature ()
virtual bool is_avatar () const
virtual bool is_monster () const
virtual monster * as_monster ()
virtual const monster * as_monster () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual avatar * as_avatar ()
virtual const avatar * as_avatar () const
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
virtual void bleed () const
Adds an appropriate blood splatter.
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
void knock_back_from (const tripoint &p)
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, const damage_instance &dam, dealt_damage_instance &dealt_dam)
virtual void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack)
Attempts to harm a creature with a projectile.
virtual void deal_damage_handle_type (const damage_unit &du, bodypart_id bp, int &damage, int &pain)
virtual bool digging () const
virtual bool is_underwater () const
virtual bool is_hallucination () const =0
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
virtual void add_effect (const efftype_id &eff_id, const time_duration &dur, const bodypart_str_id &bp, int intensity=0, bool force=false, bool deferred=false)
Adds or modifies an effect.
void add_effect (const efftype_id &eff_id, const time_duration &dur, body_part bp=num_bp, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp=num_bp, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp, bool REMOVED, int intensity=1, bool force=false)=delete
bool remove_effect (const efftype_id &eff_id, body_part bp=num_bp)
Removes a listed effect.
virtual bool remove_effect (const efftype_id &eff_id, const bodypart_str_id &bp)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id, const bodypart_str_id &bp) const
bool has_effect_with_flag (const std::string &flag, body_part bp=num_bp) const
Check if creature has any effect with the given flag.
const effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp)
std::vector< const effect * > get_all_effects_of_type (const efftype_id &eff_id) const
Returns pointers to all effects matching given type.
time_duration get_effect_dur (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
void process_effects ()
Processes through all the effects on the Creature.
virtual void mod_pain_noresist (int npain)
virtual int get_pain () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_armor_bash_bonus () const
virtual int get_armor_cut_bonus () const
virtual int get_armor_bullet_bonus () const
virtual float get_hit () const
virtual int get_hp (const bodypart_id &bp) const
virtual int get_hp () const
virtual int get_hp_max (const bodypart_id &bp) const
virtual int get_hp_max () const
virtual bool has_flag (const m_flag) const
anatomy_id get_anatomy () const
void set_anatomy (anatomy_id anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (bool only_main=false) const
Returns body parts this creature have.
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bodypart * get_part (const bodypart_id &id)
bodypart get_part (const bodypart_id &id) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
void set_part_hp_cur (const bodypart_id &id, int set)
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void mod_part_hp_cur (const bodypart_id &id, int mod)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_bash_bonus (int nbasharm)
virtual void set_armor_cut_bonus (int ncutarm)
virtual void set_armor_bullet_bonus (int nbulletarm)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
void draw (const catacurses::window &w, const point &origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
virtual bool is_symbol_highlighted () const
effects_map get_all_effects () const
body_part select_body_part (Creature *source, int hit_roll) const
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
Public Member Functions inherited from visitable< Character >
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
Traverses this object and any child items contained using a visitor pattern.
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
Lightweight version which provides only the current node.
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
item * find_parent (const item &it)
Determine the immediate parent container (if any) for an item.
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
Returns vector of parent containers (if any) starting with the innermost.
std::vector< const item * > parents (const item &it) const
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, std::function< void(int)> visitor=nullptr) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX)
Removes items contained by this instance which match the filter.
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Attributes
tripoint view_offset
tripoint grab_point
int volume = 0
bool random_start_location = false
start_location_id start_location
weak_ptr_fast< Creature > last_target
cata::optional< tripoint > last_target_pos
item_location ammo_location
int scent = 0
int cash = 0
int movecounter = 0
bool manual_examine = false
vproto_id starting_vehicle
std::vector< mtype_id > starting_pets
pimpl< craft_command > last_craft
recipe_id lastrecipe
int last_batch = 0
itype_id lastconsumed
std::set< character_id > follower_ids
Public Attributes inherited from Character
bool death_drops = true
bool controlling_vehicle = false
int str_max = 0
int dex_max = 0
int int_max = 0
int per_max = 0
int str_cur = 0
int dex_cur = 0
int int_cur = 0
int per_cur = 0
int blocks_left = 0
int dodges_left = 0
double recoil = MAX_RECOIL
profession_id prof
std::string custom_profession
bool reach_attacking = false
pimpl< known_magic > magic
std::string name
bool male = true
std::list< item > worn
std::array< int, num_hp_parts > damage_bandaged
std::array< int, num_hp_parts > damage_disinfected
bool nv_cached = false
bool in_vehicle = false
bool hauling = false
player_activity stashed_outbounds_activity
player_activity stashed_outbounds_backlog
player_activity activity
std::list< player_activity > backlog
cata::optional< tripoint > destination_point
inventory inv
itype_id last_item
item weapon
int scent = 0
pimpl< bionic_collection > my_bionics
pimpl< character_martial_arts > martial_arts_data
stomach_contents stomach
pimpl< consumption_history_t > consumption_history
int oxygen = 0
int tank_plut = 0
int reactor_plut = 0
int slow_rad = 0
int focus_pool = 0
int cash = 0
std::set< character_id > follower_ids
weak_ptr_fast< Creature > last_target
cata::optional< tripoint > last_target_pos
item_location ammo_location
std::set< tripoint_abs_omt > camps
time_point cached_time
std::vector< addiction > addictions
shared_ptr_fast< monster > mounted_creature
int mounted_creature_id = 0
int activity_vehicle_part_index = -1
std::array< int, num_hp_parts > healed_total
std::map< std::string, int > mutation_category_level
std::vector< tripoint_abs_omt > omt_path
Route for overmap scale traveling.
mutation_collection my_mutations
Traits / mutations of the character.
time_point last_sleep_check = calendar::turn_zero
bool bio_soporific_powered_at_last_sleep_check = false
std::array< int, num_bp > temp_cur
std::array< int, num_bp > frostbite_timer
std::array< int, num_bp > temp_conv
std::array< int, num_bp > body_wetness
std::array< int, num_bp > drench_capacity
time_point next_climate_control_check
bool last_climate_control_ret = false
Public Attributes inherited from Creature
FacingDirection facing = FD_RIGHT
return the direction the creature is facing, for sdl horizontal flip
int moves = 0
Protected Member Functions
void store (JsonOut &json) const
Gather variables for saving.
void load (const JsonObject &data)
Load variables from json into object.
Protected Member Functions inherited from Character
void do_skill_rust ()
void apply_mods (const trait_id &mut, bool add_remove)
Applies stat mods to character.
char_encumbrance_data calc_encumbrance () const
Recalculate encumbrance for all body parts.
char_encumbrance_data calc_encumbrance (const item &new_item) const
Recalculate encumbrance for all body parts as if new_item was also worn.
void mut_cbm_encumb (char_encumbrance_data &vals) const
Applies encumbrance from mutations and bionics only.
std::list< item >::iterator position_to_wear_new_item (const item &new_item)
Return the position in the worn list where new_item would be put by default.
void item_encumb (char_encumbrance_data &vals, const item &new_item) const
Applies encumbrance from items only If new_item is not null, then calculate under the asumption that it is added to existing work items.
void on_damage_of_type (int adjusted_damage, damage_type type, const bodypart_id &bp) override
Character ()
Character (Character &&)
Character & operator= (Character &&)
void store (JsonOut &json) const
Load variables from json into object.
void load (const JsonObject &data)
Gather variables for saving.
Protected Member Functions inherited from Creature
void set_killer (Creature *killer)
Creature ()
Creature (const Creature &)=default
Creature (Creature &&)=default
Creature & operator= (const Creature &)=default
Creature & operator= (Creature &&)=default
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Private Member Functions
bool consume_med (item &target)
Consumes an item as medication.
Private Attributes
safe_reference_anchor anchor
std::map< faction_id, std::pair< int, time_point > > warning_record
warnings from a faction about bad behavior
Related Functions
(Note that these are not member functions.)
bool operator() (const profession_id &a, const profession_id &b)
bool operator() (const scenario *a, const scenario *b)
Related Functions inherited from visitable< Character >
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
item * find_parent (const item &it)
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
std::vector< const item * > parents (const item &it) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
Additional Inherited Members
Public Types inherited from Character
enum water_tolerance { WT_IGNORED = 0 , WT_NEUTRAL , WT_GOOD , NUM_WATER_TOLERANCE }
using trap_map = std::map< tripoint, std::string >
Public Types inherited from Creature
enum Attitude : int { A_HOSTILE , A_NEUTRAL , A_FRIENDLY , A_ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Static Public Member Functions inherited from Character
static hp_part bp_to_hp (body_part bp)
Converts a body_part to an hp_part.
static body_part hp_to_bp (hp_part hpart)
Converts an hp_part to a body_part.
static int worn_position_to_index (int position)
static int floor_bedding_warmth (const tripoint &pos)
Warmth from terrain, furniture, vehicle furniture and traps.
static int floor_item_warmth (const tripoint &pos)
Warmth from clothing on the floor.
Static Public Member Functions inherited from Creature
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
static void reset_hit_range ()
Static Public Attributes inherited from Character
static const std::vector< material_id > fleshy = { material_id("flesh"), material_id("hflesh") }
Static Public Attributes inherited from Creature
static const std::map< std::string, m_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit = default_dispersion_for_ecogh
Protected Attributes inherited from Character
std::array< std::array< int, NUM_WATER_TOLERANCE >, num_bp > mut_drench
tripoint position
int str_bonus = 0
Bonuses to stats, calculated each turn.
int dex_bonus = 0
int per_bonus = 0
int int_bonus = 0
int healthy = 0
How healthy the character is.
int healthy_mod = 0
int init_age = 25
age in years at character creation
int init_height = 175
height at character creation
m_size size_class = MS_MEDIUM
Size class of character.
trap_map known_traps
pimpl< char_encumbrance_data > encumbrance_cache
std::map< faction_id, std::pair< int, time_point > > warning_record
warnings from a faction about bad behavior
std::unordered_set< trait_id > my_traits
Contains mutation ids of the base traits.
std::vector< const mutation_branch * > cached_mutations
Pointers to mutation branches in my_mutations.
pimpl< SkillLevelMap > _skills
Character skills.
pimpl< SkillLevelMap > autolearn_skills_stamp
Stamp of character skills.
pimpl< recipe_subset > learned_recipes
Subset of learned recipes.
std::bitset< NUM_VISION_MODES > vision_mode_cache
float nv_range = 0
int sight_max = 0
time_point time_died = calendar::before_time_starts
pimpl< pathfinding_settings > path_settings
Cache for pathfinding settings.
int faction_api_version = 2
faction_id fac_id
faction * my_fac = nullptr
character_movemode move_mode = CMM_WALK
std::map< vitamin_id, int > vitamin_levels
Current deficiency/excess quantity for each vitamin.
pimpl< player_morale > morale
pimpl< enchantment > enchantment_cache
std::unordered_map< point_abs_omt, time_duration > overmap_time
Amount of time the player has spent in each overmap tile.
Protected Attributes inherited from Creature
Creature * killer = nullptr
pimpl< effects_map > effects
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
int armor_bash_bonus = 0
int armor_cut_bonus = 0
int armor_bullet_bonus = 0
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0
int block_bonus = 0
float hit_bonus = 0.0
bool fake = false
Detailed Description
Definition at line 83 of file player.h.
Constructor & Destructor Documentation
player() [1/3]
player::player ()
Definition at line 126 of file player.cpp.
{
    str_cur = 8;
    str_max = 8;
    dex_cur = 8;
    dex_max = 8;
    int_cur = 8;
    int_max = 8;
    per_cur = 8;
    per_max = 8;
    dodges_left = 1;
    blocks_left = 1;
    set_power_level( 0_kJ );
    set_max_power_level( 0_kJ );
    cash = 0;
    scent = 500;
    male = true;
    start_location = start_location_id( "sloc_shelter" );
    moves = 100;
    movecounter = 0;
    oxygen = 0;
    in_vehicle = false;
    controlling_vehicle = false;
    grab_point = tripoint_zero;
    hauling = false;
    focus_pool = 100;
    last_item = itype_id( "null" );
    sight_max = 9999;
    last_batch = 0;
    lastconsumed = itype_id( "null" );
    death_drops = true;
    nv_cached = false;
    volume = 0;
    set_value( "THIEF_MODE", "THIEF_ASK" );
    for( const auto &v : vitamin::all() ) {
        vitamin_levels[ v.first ] = 0;
    }
    if( g != nullptr && json_flag::is_ready() ) {
        recalc_sight_limits();
        reset_encumbrance();
    }
}
References vitamin::all(), Character::blocks_left, cash, Character::controlling_vehicle, Character::death_drops, Character::dex_cur, Character::dex_max, Character::dodges_left, Character::focus_pool, g, grab_point, Character::hauling, Character::in_vehicle, Character::int_cur, Character::int_max, json_flag::is_ready(), itype_id, last_batch, Character::last_item, lastconsumed, Character::male, movecounter, Creature::moves, Character::nv_cached, Character::oxygen, Character::per_cur, Character::per_max, Character::recalc_sight_limits(), Character::reset_encumbrance(), scent, Character::set_max_power_level(), Character::set_power_level(), Creature::set_value(), Character::sight_max, Character::str_cur, Character::str_max, tripoint_zero, Character::vitamin_levels, and volume.
player() [2/3]
player::player (const player &) delete
player() [3/3]
player::player (player &&) default
~player()
player::~player () override default
Member Function Documentation
add_faction_warning()
bool player::add_faction_warning (const faction_id & id)
Definition at line 850 of file player.cpp.
{
    const auto it = warning_record.find( id );
    if( it != warning_record.end() ) {
        it->second.first += 1;
        if( it->second.second - calendar::turn > 5_minutes ) {
            it->second.first -= 1;
        }
        it->second.second = calendar::turn;
        if( it->second.first > 3 ) {
            return true;
        }
    } else {
        warning_record[id] = std::make_pair( 1, calendar::turn );
    }
    faction *fac = g->faction_manager_ptr->get( id );
    if( fac != nullptr && is_player() && fac->id != faction_id( "no_faction" ) ) {
        fac->likes_u -= 1;
        fac->respects_u -= 1;
    }
    return false;
}
References g, Character::id, faction_template::id, is_player(), faction_template::likes_u, faction_template::respects_u, calendar::turn, and warning_record.
Referenced by vehicle::handle_potential_theft(), prompt_disassemble_in_seq(), and query_consume_ownership().
add_msg_if_player() [1/2]
void player::add_msg_if_player (const game_message_params & params, const std::string & msg) const override virtual
Reimplemented from Creature.
Reimplemented in npc.
Definition at line 2604 of file player.cpp.
{
    Messages::add_msg( params, msg );
}
References Messages::add_msg().
add_msg_if_player() [2/2]
void player::add_msg_if_player (const std::string & msg) const override virtual
Reimplemented from Creature.
Reimplemented in npc.
Definition at line 2593 of file player.cpp.
{
    Messages::add_msg( msg );
}
References Messages::add_msg().
Referenced by iuse::adrenaline_injector(), iuse::antiasthmatic(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antifungal(), iuse::antiparasitic(), temperature_effect::apply(), apply_lock_picking_tool(), apply_prying_tool(), iuse::arrow_flammable(), iuse::artifact(), iexamine::autodoc(), iuse::blech(), iuse::blood_draw(), iuse::boltcutters(), iexamine::bulletin_board(), iuse::burrow(), activity_handlers::burrow_finish(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), iuse::c4(), iuse::cable_attach(), iuse::camera(), repair_item_actor::can_repair_target(), repair_item_actor::can_use_tool(), iuse::capture_monster_act(), iuse::capture_monster_veh(), iexamine::cardreader_foodplace(), game::catch_a_monster(), cauterize_actor::cauterize_effect(), game::chat(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), check_litcig(), iuse::chew(), iuse::chop_logs(), activity_handlers::chop_logs_finish(), chop_plank_activity(), activity_handlers::chop_planks_finish(), iuse::chop_tree(), activity_handlers::chop_tree_finish(), activity_handlers::churn_finish(), iuse::clear_rubble(), activity_handlers::clear_rubble_finish(), iuse::coin_flip(), veh_interact::complete_vehicle(), consume(), consume_item(), consume_med(), iuse::contacts(), activity_handlers::cracking_finish(), iuse::craft(), crafting_success_roll(), trapfunc::crossbow(), iuse::crowbar(), iexamine::curtains(), iuse::cut_log_into_planks(), damage_item(), iuse::datura(), iexamine::deployed_furniture(), monster::die(), iuse::dig(), iuse::dig_channel(), iuse::directional_antenna(), iuse::directional_hologram(), iuse::disassemble(), iuse::dive_tank(), explosion_handler::do_blast(), do_purify(), player_activity::do_turn(), iuse::dog_whistle(), iexamine::door_peephole(), eat(), iuse::ecig(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_hot(), eff_fun_rat(), einkpc_download_memory_card(), iuse::einktabletpc(), iuse::extinguisher(), iuse::eyedrops(), feedpet(), activity_handlers::fill_liquid_do_turn(), iuse::fill_pit(), activity_handlers::fill_pit_finish(), heal_actor::finish_using(), fire_gun(), iuse::firecracker(), iuse::firecracker_act(), iuse::firecracker_pack(), iexamine::fireplace(), activity_handlers::fish_do_turn(), activity_handlers::fish_finish(), iuse::fish_trap(), iuse::fishing_rod(), iuse::flumed(), iuse::flusleep(), iuse::foodperson(), fungal_effects::fungalize(), iuse::fungicide(), iuse::gasmask(), iuse::geiger(), generic_multi_activity_check_requirement(), generic_multi_activity_handler(), generic_multi_activity_locations(), trapfunc::glow(), trapfunc::goo(), mattack::grab(), iuse::granade(), iuse::granade_act(), iuse::grenade_inc_act(), iuse::gun_repair(), gunmod_add(), gunmod_remove(), iuse::hacksaw(), activity_handlers::hacksaw_finish(), hackveh(), activity_handlers::haircut_finish(), iuse::hairkit(), iuse::hammer(), iuse::hand_crank(), repair_item_actor::handle_components(), iuse::handle_ground_graffiti(), handle_harvest(), harvest_common(), iexamine::harvested_plant(), impact(), iexamine::intercom(), Character::introduce_into_anesthesia(), itype::invoke(), place_trap_actor::is_allowed(), item_save_monsters(), mdeath::jabberwock(), iuse::jackhammer(), iuse::jet_injector(), monexamine::kill_zslave(), iuse::ladder(), trapfunc::ledge(), iexamine::ledge(), aim_activity_actor::load_RAS_weapon(), activity_handlers::lockpicking_finish(), iuse::lumber(), iuse::magic_8_ball(), magic_train(), activity_handlers::make_zlave_finish(), iuse::makemound(), trapfunc::map_regen(), marloss_common(), marloss_prevented(), iuse::meditate(), activity_handlers::meditate_finish(), iuse::melatonin_tablet(), iuse::meth(), activity_handlers::milk_finish(), mill_load_food(), iuse::mind_splicer(), activity_handlers::mind_splicer_finish(), iuse::mininuke(), iuse::molotov_lit(), iuse::mop(), iuse::mp3(), iuse::mp3_on(), iuse::multicooker(), multicooker_hallu(), iuse::mycus(), iuse::noise_emitter_off(), iuse::noise_emitter_on(), iuse::note_bionics(), avatar::on_mission_finished(), item::on_wield(), iuse::oxytorch(), iuse::pack_cbm(), iuse::pack_item(), petfood(), game::phasing_move(), iuse::pheromone(), iuse::pickaxe(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), iuse::plantblech(), iuse::play_game(), iuse::play_music(), activity_handlers::play_with_pet_finish(), map::player_in_field(), pldrive(), iuse::portable_game(), iuse::portal(), firestarter_actor::prep_firestarter_use(), item::process_blackpowder_fouling(), item::process_cable(), item::process_corpse(), item::process_extinguish(), item::process_internal(), item::process_litcig(), sounds::process_sound_markers(), item::process_tool(), prompt_disassemble_in_seq(), ranged::prompt_select_default_ammo_for(), iuse::prozac(), activity_handlers::pry_nails_finish(), activity_handlers::pulp_do_turn(), iuse::purify_iv(), iuse::purify_smart(), iuse::radglove(), iuse::radio_mod(), iuse::radio_off(), iuse::radio_on(), iuse::radiocar(), iuse::radiocaron(), iuse::radiocontrol(), rcdrive(), avatar::read(), activity_handlers::read_do_turn(), activity_handlers::read_finish(), bandolier_actor::reload(), iuse::remoteveh(), remove_radio_mod(), repair_item_actor::repair(), activity_handlers::repair_item_finish(), veh_utils::repair_part(), iuse::report_grid_charge(), iuse::report_grid_connections(), item::reset_cable(), firestarter_actor::resolve_firestarter_use(), iuse::rm13armor_off(), iuse::rm13armor_on(), activity_handlers::robot_control_do_turn(), activity_handlers::robot_control_finish(), iuse::robotcontrol(), rod_fish(), iuse::rpgdie(), target_ui::run(), iexamine::safe(), select_ammo(), set_up_butchery_activity(), iuse::shavekit(), activity_handlers::shaving_finish(), iuse::shocktonfa_off(), iuse::shocktonfa_on(), trapfunc::shotgun(), show_photo_selection(), iexamine::sign(), sinkhole_safety_roll(), iuse::siphon(), sleep(), iuse::sleep(), smoker_load_food(), iuse::smoking(), activity_handlers::socialize_finish(), iuse::solarpack(), iuse::solarpack_off(), activity_handlers::spellcasting_finish(), start_craft(), activity_handlers::start_fire_do_turn(), iuse::stimpack(), holster_actor::store(), iuse::strong_antibiotic(), activity_handlers::study_spell_finish(), iuse::talking_doll(), iuse::tazer(), iuse::tazer2(), teleport::teleport(), iuse::teleport(), iuse::thorazine(), gates::toggle_gate(), iuse::toggle_heats_food(), toolmod_add(), activity_handlers::toolmod_add_finish(), iuse::toolmod_attach(), toolweapon_off(), toolweapon_on(), iuse::tow_attach(), iuse::towel_common(), activity_handlers::travel_do_turn(), activity_handlers::tree_communion_do_turn(), iexamine::tree_hickory(), activity_handlers::try_sleep_do_turn(), activity_handlers::try_sleep_finish(), avatar_funcs::try_to_sleep(), iuse::unfold_generic(), iuse::unpack_item(), use(), iuse_transform::use(), countdown_actor::use(), explosion_iuse::use(), unfold_vehicle_iuse::use(), consume_drug_iuse::use(), delayed_transform_iuse::use(), set_transform_iuse::use(), place_monster_iuse::use(), place_npc_iuse::use(), pick_lock_actor::use(), deploy_furn_actor::use(), reveal_map_actor::use(), firestarter_actor::use(), inscribe_actor::use(), cauterize_actor::use(), enzlave_actor::use(), fireweapon_off_actor::use(), fireweapon_on_actor::use(), manualnoise_actor::use(), holster_actor::use(), bandolier_actor::use(), ammobelt_actor::use(), heal_actor::use(), place_trap_actor::use(), mutagen_actor::use(), mutagen_iv_actor::use(), deploy_tent_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), weigh_self_actor::use(), saw_barrel_actor::use(), detach_gunmods_actor::use(), unpack_actor::use(), cast_spell_actor::use(), iuse::vaccine(), iuse::vibe(), activity_handlers::vibe_finish(), iuse::vortex(), activity_handlers::wait_finish(), activity_handlers::wait_npc_finish(), activity_handlers::wait_stamina_finish(), activity_handlers::wait_weather_finish(), iuse::wash_all_items(), iuse::wash_hard_items(), wash_items(), iuse::wash_soft_items(), iuse::water_purifier(), iuse::weak_antibiotic(), iuse::weather_tool(), iuse::weed_cake(), weed_msg(), wield_contents(), and iuse::xanax().
add_msg_player_or_npc() [1/2]
void player::add_msg_player_or_npc (const game_message_params & params, const std::string & player_msg, const std::string & npc_msg) const override virtual
Reimplemented from Creature.
Reimplemented in npc.
Definition at line 2610 of file player.cpp.
{
    Messages::add_msg( params, player_msg );
}
References Messages::add_msg().
add_msg_player_or_npc() [2/2]
void player::add_msg_player_or_npc (const std::string & player_msg, const std::string & npc_str) const override virtual
Reimplemented from Creature.
Reimplemented in npc.
Definition at line 2598 of file player.cpp.
{
    Messages::add_msg( player_msg );
}
References Messages::add_msg().
Referenced by iuse::adrenaline_injector(), iuse::antibiotic(), iexamine::autodoc(), repair_item_actor::can_use_tool(), iuse::craft(), craft_consume_tools(), activity_handlers::craft_do_turn(), trapfunc::crossbow(), map::crush(), destroy_random_component(), eat(), eff_fun_bleed(), eff_fun_fungus(), iuse::fungicide(), iuse::gasmask(), mattack::grab(), item::handle_craft_failure(), iuse::inhaler(), Character::introduce_into_anesthesia(), activity_handlers::jackhammer_finish(), knock_back_to(), trapfunc::ledge(), activity_handlers::operation_do_turn(), iuse::oxygen_bottle(), iuse::pheromone(), activity_handlers::pickaxe_finish(), activity_handlers::plant_seed_finish(), map::player_in_field(), activity_handlers::pulp_do_turn(), mattack::riotbot(), set_item_map_or_vehicle(), map::shake_vehicle(), trapfunc::shotgun(), trapfunc::sinkhole(), sinkhole_safety_roll(), start_craft(), iuse::strong_antibiotic(), takeoff(), iuse::tazer(), teleport::teleport(), musical_instrument_actor::use(), mutagen_actor::use(), heal_actor::use_healing_item(), iuse::weak_antibiotic(), and wear().
add_msg_player_or_say() [1/2]
void player::add_msg_player_or_say (const game_message_params & params, const std::string & player_msg, const std::string & npc_speech) const override virtual
Reimplemented from Creature.
Reimplemented in npc.
Definition at line 2623 of file player.cpp.
{
    Messages::add_msg( params, player_msg );
}
References Messages::add_msg().
add_msg_player_or_say() [2/2]
void player::add_msg_player_or_say (const std::string & player_msg, const std::string & npc_speech) const override virtual
Reimplemented from Creature.
Reimplemented in npc.
Definition at line 2617 of file player.cpp.
{
    Messages::add_msg( player_msg );
}
References Messages::add_msg().
Referenced by iuse::radglove(), and consume_drug_iuse::use().
add_or_drop_with_msg()
bool player::add_or_drop_with_msg (item & it, bool unloading = false)
So far only called by unload() from game.cpp.
Definition at line 1745 of file player.cpp.
{
    if( it.made_of( LIQUID ) ) {
        liquid_handler::consume_liquid( it, 1 );
        return it.charges <= 0;
    }
    it.charges = this->i_add_to_container( it, unloading );
    if( it.is_ammo() && it.charges == 0 ) {
        return true;
    } else if( !this->can_pick_volume( it ) ) {
        put_into_vehicle_or_drop( *this, item_drop_reason::too_large, { it } );
    } else if( !this->can_pick_weight( it, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
        put_into_vehicle_or_drop( *this, item_drop_reason::too_heavy, { it } );
    } else {
        auto &ni = this->i_add( it );
        add_msg( _( "You put the %s in your inventory." ), ni.tname() );
        add_msg( m_info, "%c - %s", ni.invlet == 0 ? ' ' : ni.invlet, ni.tname() );
    }
    return true;
}
References _, add_msg(), Character::can_pick_volume(), Character::can_pick_weight(), item::charges, liquid_handler::consume_liquid(), Character::i_add(), Character::i_add_to_container(), item::is_ammo(), LIQUID, m_info, item::made_of(), put_into_vehicle_or_drop(), too_heavy, and too_large.
Referenced by unload().
as_player() [1/2]
const player * player::as_player () const inline override virtual
Reimplemented from Creature.
Definition at line 105 of file player.h.
{
            return this;
        }
as_player() [2/2]
player * player::as_player () inline override virtual
Reimplemented from Creature.
Definition at line 102 of file player.h.
{
            return this;
        }
Referenced by npc::do_player_activity(), and npc::find_job_to_perform().
available_assistant_count()
int player::available_assistant_count (const recipe & rec) const
For use with in progress crafts.
Definition at line 389 of file crafting.cpp.
{
    // NPCs around you should assist in batch production if they have the skills
    // TODO: Cache them in activity, include them in modifier calculations
    const auto helpers = get_crafting_helpers();
    return std::count_if( helpers.begin(), helpers.end(),
    [&]( const npc * np ) {
        return np->get_skill_level( rec.skill_used ) >= rec.difficulty;
    } );
}
References get_crafting_helpers().
Referenced by base_time_to_craft(), activity_handlers::craft_do_turn(), craft_progress_message(), and expected_time_to_craft().
base_time_to_craft()
int player::base_time_to_craft (const recipe & rec, int batch_size = 1) const
Time to craft not including speed multiplier.
Definition at line 400 of file crafting.cpp.
{
    const size_t assistants = available_assistant_count( rec );
    return rec.batch_time( batch_size, 1.0f, assistants );
}
References available_assistant_count(), and recipe::batch_time().
Referenced by craft_skill_gain().
beyond_final_warning()
bool player::beyond_final_warning (const faction_id & id)
Definition at line 886 of file player.cpp.
{
    const auto it = warning_record.find( id );
    if( it != warning_record.end() ) {
        if( it->second.second - calendar::turn > 5_minutes ) {
            it->second.first = std::max( 0,
                                         it->second.first - 1 );
        }
        return it->second.first > 3;
    }
    return false;
}
References calendar::turn, and warning_record.
can_continue_craft()
bool player::can_continue_craft (item & craft)
Check if the player meets the requirements to continue the in progress craft and if unable to continue print messages explaining the reason.
If the craft is missing components due to messing up, prompt to consume new ones to allow the craft to be continued.
Parameters
craft the currently in progress craft
Returns
if the craft can be continued
Definition at line 1156 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "complete_craft() called on non-craft '%s.'  Aborting.", craft.tname() );
        return false;
    }
    if( has_trait( trait_DEBUG_HS ) ) {
        return true;
    }
    const recipe &rec = craft.get_making();
    const requirement_data continue_reqs = craft.get_continue_reqs();
    // Avoid building an inventory from the map if we don't have to, as it is expensive
    if( !continue_reqs.is_empty() ) {
        std::function<bool( const item & )> filter = rec.get_component_filter();
        const std::function<bool( const item & )> no_rotten_filter =
            rec.get_component_filter( recipe_filter_flags::no_rotten );
        // continue_reqs are for all batches at once
        const int batch_size = 1;
        if( !continue_reqs.can_make_with_inventory( crafting_inventory(), filter, batch_size ) ) {
            std::string buffer = _( "You don't have the required components to continue crafting!" );
            buffer += "\n";
            buffer += continue_reqs.list_missing();
            popup( buffer, PF_NONE );
            return false;
        }
        std::string buffer = _( "Consume the missing components and continue crafting?" );
        buffer += "\n";
        buffer += continue_reqs.list_all();
        if( !query_yn( buffer ) ) {
            return false;
        }
        if( continue_reqs.can_make_with_inventory( crafting_inventory(), no_rotten_filter,
                batch_size ) ) {
            filter = no_rotten_filter;
        } else {
            if( !query_yn( _( "Some components required to continue are rotten.\n"
                              "Continue crafting anyway?" ) ) ) {
                return false;
            }
        }
        inventory map_inv;
        map_inv.form_from_map( pos(), PICKUP_RANGE, this );
        std::vector<comp_selection<item_comp>> item_selections;
        for( const auto &it : continue_reqs.get_components() ) {
            comp_selection<item_comp> is = select_item_component( it, batch_size, map_inv, true, filter );
            if( is.use_from == cancel ) {
                cancel_activity();
                add_msg( _( "You stop crafting." ) );
                return false;
            }
            item_selections.push_back( is );
        }
        for( const auto &it : item_selections ) {
            craft.components.splice( craft.components.end(), consume_items( it, batch_size, filter ) );
        }
    }
    if( !craft.has_tools_to_continue() ) {
        const std::vector<std::vector<tool_comp>> &tool_reqs = rec.simple_requirements().get_tools();
        const int batch_size = craft.charges;
        std::vector<std::vector<tool_comp>> adjusted_tool_reqs;
        for( const std::vector<tool_comp> &alternatives : tool_reqs ) {
            std::vector<tool_comp> adjusted_alternatives;
            for( const tool_comp &alternative : alternatives ) {
                tool_comp adjusted_alternative = alternative;
                if( adjusted_alternative.count > 0 ) {
                    adjusted_alternative.count *= batch_size;
                    // Only for the next 5% progress
                    adjusted_alternative.count = std::max(
                                                     crafting::charges_for_continuing( adjusted_alternative.count ), 1 );
                }
                adjusted_alternatives.push_back( adjusted_alternative );
            }
            adjusted_tool_reqs.push_back( adjusted_alternatives );
        }
        const requirement_data tool_continue_reqs( adjusted_tool_reqs,
                std::vector<std::vector<quality_requirement>>(),
                std::vector<std::vector<item_comp>>() );
        if( !tool_continue_reqs.can_make_with_inventory( crafting_inventory(), return_true<item> ) ) {
            std::string buffer = _( "You don't have the necessary tools to continue crafting!" );
            buffer += "\n";
            buffer += tool_continue_reqs.list_missing();
            popup( buffer, PF_NONE );
            return false;
        }
        inventory map_inv;
        map_inv.form_from_map( pos(), PICKUP_RANGE, this );
        std::vector<comp_selection<tool_comp>> new_tool_selections;
        for( const std::vector<tool_comp> &alternatives : tool_reqs ) {
            comp_selection<tool_comp> selection =
                crafting::select_tool_component( alternatives, batch_size, map_inv, this, true, DEFAULT_HOTKEYS,
                                                 cost_adjustment::continue_only );
            if( selection.use_from == cancel ) {
                return false;
            }
            new_tool_selections.push_back( selection );
        }
        craft.set_cached_tool_selections( new_tool_selections );
        craft.set_tools_to_continue( true );
    }
    return true;
}
References _, add_msg(), requirement_data::can_make_with_inventory(), cancel, Character::cancel_activity(), crafting::charges_for_continuing(), consume_items(), continue_only, component::count, craft(), Character::crafting_inventory(), debugmsg, DEFAULT_HOTKEYS(), inventory::form_from_map(), recipe::get_component_filter(), requirement_data::get_components(), requirement_data::get_tools(), Character::has_trait(), requirement_data::is_empty(), requirement_data::list_all(), requirement_data::list_missing(), no_rotten, PF_NONE, PICKUP_RANGE, popup(), Character::pos(), query_yn(), select_item_component(), crafting::select_tool_component(), recipe::simple_requirements(), trait_DEBUG_HS, and comp_selection< CompType >::use_from.
Referenced by iuse::craft(), activity_handlers::craft_do_turn(), and item::handle_craft_failure().
can_grab_break()
bool player::can_grab_break (const item & weap) const
Returns true if the player is able to use a grab breaking technique.
Definition at line 932 of file martialarts.cpp.
{
    if( !has_grab_break_tec() ) {
        return false;
    }
    ma_technique tec = martial_arts_data->get_grab_break_tec( weap );
    return tec.is_valid_character( *this );
}
References Character::has_grab_break_tec(), ma_technique::is_valid_character(), and Character::martial_arts_data.
Referenced by mattack::grab().
can_lift()
bool player::can_lift (int lift_strength_required) const
Check player strong enough to lift an object unaided by equipment (jacks, levers etc)
Definition at line 1655 of file player.cpp.
{
    // avoid comparing by weight as different objects use differing scales (grams vs kilograms etc)
    int str = get_str();
    if( mounted_creature ) {
        auto mons = mounted_creature.get();
        str = mons->mech_str_addition() == 0 ? str : mons->mech_str_addition();
    }
    const int npc_str = get_lift_assist();
    if( has_trait( trait_id( "STRONGBACK" ) ) ) {
        str *= 1.35;
    } else if( has_trait( trait_id( "BADBACK" ) ) ) {
        str /= 1.35;
    }
    return str + npc_str >= lift_strength_required;
}
References get_lift_assist(), Character::get_str(), Character::has_trait(), Character::mounted_creature, and trait_id.
Referenced by can_do_activity_there().
can_make()
bool player::can_make (const recipe * r, int batch_size = 1)
Definition at line 530 of file crafting.cpp.
{
    const inventory &crafting_inv = crafting_inventory();
    if( has_recipe( r, crafting_inv, get_crafting_helpers() ) < 0 ) {
        return false;
    }
    return r->deduped_requirements().can_make_with_inventory(
               crafting_inv, r->get_component_filter(), batch_size );
}
References deduped_requirement_data::can_make_with_inventory(), Character::crafting_inventory(), recipe::deduped_requirements(), recipe::get_component_filter(), get_crafting_helpers(), and has_recipe().
Referenced by craft_command::execute(), and making_would_work().
can_reload()
bool player::can_reload (const item & it, const itype_id & ammo = itype_id()) const
Whether a tool or gun is potentially reloadable (optionally considering a specific ammo)
Parameters
it Thing to be reloaded
ammo if set also check item currently compatible with this specific ammo or magazine
Note
items currently loaded with a detachable magazine are considered reloadable
items with integral magazines are reloadable if free capacity permits (+/- ammo matches)
Definition at line 1381 of file player.cpp.
{
    if( !it.is_reloadable_with( ammo ) ) {
        return false;
    }
    if( it.is_ammo_belt() ) {
        const auto &linkage = it.type->magazine->linkage;
        if( linkage && !has_charges( *linkage, 1 ) ) {
            return false;
        }
    }
    return true;
}
References Character::has_charges(), item::is_ammo_belt(), item::is_reloadable_with(), itype::magazine, and item::type.
Referenced by can_reload_item_or_mods(), npc::find_usable_ammo(), list_ammo(), examine_item_menu::rate_action_reload(), ammobelt_actor::use(), and wants_to_reload().
can_start_craft()
bool player::can_start_craft (const recipe * rec, recipe_filter_flags flags, int batch_size = 1)
Returns true if the player can start crafting the recipe with the given batch size The player is not required to have enough tool charges to finish crafting, only to complete the first step (total / 20 + total % 20 charges)
Definition at line 542 of file crafting.cpp.
{
    if( !rec ) {
        return false;
    }
    const inventory &inv = crafting_inventory();
    return rec->deduped_requirements().can_make_with_inventory(
               inv, rec->get_component_filter( flags ), batch_size, cost_adjustment::start_only );
}
References deduped_requirement_data::can_make_with_inventory(), Character::crafting_inventory(), recipe::deduped_requirements(), recipe::get_component_filter(), Character::inv, and start_only.
Referenced by craft_command::execute().
can_takeoff()
ret_val< bool > player::can_takeoff (const item & it, const std::list< item > * res = nullptr) const
Check player capable of taking off an item.
Parameters
it Thing to be taken off
Definition at line 1672 of file player.cpp.
{
    auto iter = std::find_if( worn.begin(), worn.end(), [ &it ]( const item & wit ) {
        return &it == &wit;
    } );
    if( iter == worn.end() ) {
        return ret_val<bool>::make_failure( !is_npc() ? _( "You are not wearing that item." ) :
                                            _( "<npcname> is not wearing that item." ) );
    }
    if( res == nullptr && !get_dependent_worn_items( it ).empty() ) {
        return ret_val<bool>::make_failure( !is_npc() ?
                                            _( "You can't take off power armor while wearing other power armor components." ) :
                                            _( "<npcname> can't take off power armor while wearing other power armor components." ) );
    }
    if( it.has_flag( "NO_TAKEOFF" ) ) {
        return ret_val<bool>::make_failure( !is_npc() ?
                                            _( "You can't take that item off." ) :
                                            _( "<npcname> can't take that item off." ) );
    }
    return ret_val<bool>::make_success();
}
References _, Character::get_dependent_worn_items(), item::has_flag(), is_npc(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and Character::worn.
Referenced by Character::drop(), take_off_inventory_preset::get_denial(), avatar_action::plthrow(), examine_item_menu::rate_action_takeoff(), examine_item_menu::run(), takeoff(), and avatar_action::wield().
can_wield()
ret_val< bool > player::can_wield (const item & it) const
Check player capable of wielding an item.
Parameters
it Thing to be wielded
Definition at line 1234 of file player.cpp.
{
    if( it.made_of( LIQUID ) ) {
        return ret_val<bool>::make_failure( _( "Can't wield spilt liquids." ) );
    }
    if( get_working_arm_count() <= 0 ) {
        return ret_val<bool>::make_failure(
                   _( "You need at least one arm to even consider wielding something." ) );
    }
    if( is_armed() && weapon.has_flag( "NO_UNWIELD" ) ) {
        return ret_val<bool>::make_failure( _( "The %s is preventing you from wielding the %s." ),
                                            character_funcs::fmt_wielded_weapon( *this ), it.tname() );
    }
    monster *mount = mounted_creature.get();
    if( it.is_two_handed( *this ) && ( !has_two_arms() || worn_with_flag( flag_RESTRICT_HAND ) ) &&
        !( is_mounted() && mount->has_flag( MF_RIDEABLE_MECH ) &&
           mount->type->mech_weapon && it.typeId() == mount->type->mech_weapon ) ) {
        if( worn_with_flag( flag_RESTRICT_HAND ) ) {
            return ret_val<bool>::make_failure(
                       _( "Something you are wearing hinders the use of both hands." ) );
        } else if( it.has_flag( "ALWAYS_TWOHAND" ) ) {
            return ret_val<bool>::make_failure( _( "The %s can't be wielded with only one arm." ),
                                                it.tname() );
        } else {
            return ret_val<bool>::make_failure( _( "You are too weak to wield %s with only one arm." ),
                                                it.tname() );
        }
    }
    if( is_mounted() && mount->has_flag( MF_RIDEABLE_MECH ) &&
        mount->type->mech_weapon && it.typeId() != mount->type->mech_weapon ) {
        return ret_val<bool>::make_failure( _( "You cannot wield anything while piloting a mech." ) );
    }
    return ret_val<bool>::make_success();
}
References _, flag_RESTRICT_HAND(), character_funcs::fmt_wielded_weapon(), Character::get_working_arm_count(), item::has_flag(), monster::has_flag(), Character::has_two_arms(), Character::is_armed(), Character::is_mounted(), item::is_two_handed(), LIQUID, item::made_of(), ret_val< T >::make_failure(), ret_val< T >::make_success(), mtype::mech_weapon, MF_RIDEABLE_MECH, Character::mounted_creature, item::tname(), monster::type, item::typeId(), Character::weapon, and Character::worn_with_flag().
Referenced by Character::apply_damage(), find_best_bench(), weapon_inventory_preset::get_denial(), pick_one_up(), avatar::wield(), avatar_action::wield(), and wield_contents().
check_eligible_containers_for_crafting()
bool player::check_eligible_containers_for_crafting (const recipe & rec, int batch_size = 1) const
Definition at line 413 of file crafting.cpp.
{
    std::vector<const item *> conts = get_eligible_containers_for_crafting();
    const std::vector<item> res = rec.create_results( batch_size );
    const std::vector<item> bps = rec.create_byproducts( batch_size );
    std::vector<item> all;
    all.reserve( res.size() + bps.size() );
    all.insert( all.end(), res.begin(), res.end() );
    all.insert( all.end(), bps.begin(), bps.end() );
    map &here = get_map();
    for( const item &prod : all ) {
        if( !prod.made_of( LIQUID ) ) {
            continue;
        }
        // we go through half-filled containers first, then go through empty containers if we need
        std::sort( conts.begin(), conts.end(), item_ptr_compare_by_charges );
        int charges_to_store = prod.charges;
        for( const item *cont : conts ) {
            if( charges_to_store <= 0 ) {
                break;
            }
            if( !cont->is_container_empty() ) {
                if( cont->contents.front().typeId() == prod.typeId() ) {
                    charges_to_store -= cont->get_remaining_capacity_for_liquid( cont->contents.front(), true );
                }
            } else {
                charges_to_store -= cont->get_remaining_capacity_for_liquid( prod, true );
            }
        }
        // also check if we're currently in a vehicle that has the necessary storage
        if( charges_to_store > 0 ) {
            if( optional_vpart_position vp = here.veh_at( pos() ) ) {
                const itype_id &ftype = prod.typeId();
                int fuel_cap = vp->vehicle().fuel_capacity( ftype );
                int fuel_amnt = vp->vehicle().fuel_left( ftype );
                if( fuel_cap >= 0 ) {
                    int fuel_space_left = fuel_cap - fuel_amnt;
                    charges_to_store -= fuel_space_left;
                }
            }
        }
        if( charges_to_store > 0 ) {
            if( !query_yn(
                    _( "You don't have anything in which to store %s and may have to pour it out or consume it as soon as it is prepared!  Proceed?" ),
                    prod.tname() ) ) {
                return false;
            }
        }
    }
    return true;
}
References _, om_direction::all, recipe::create_byproducts(), recipe::create_results(), get_eligible_containers_for_crafting(), get_map(), item_ptr_compare_by_charges(), LIQUID, Character::pos(), query_yn(), and map::veh_at().
Referenced by making_would_work(), iuse::multicooker(), and select_crafting_recipe().
consume()
bool player::consume (item_location loc)
Used for eating object at pos, returns true if object is removed from inventory (last charge was consumed)
Definition at line 795 of file player.cpp.
{
    item &target = *loc;
    const bool wielding = is_wielding( target );
    const bool worn = is_worn( target );
    const bool inv_item = !( wielding || worn );
    if( consume_item( target ) ) {
        const bool was_in_container = !can_consume_as_is( target );
        if( was_in_container ) {
            i_rem( &target.contents.front() );
        } else {
            i_rem( &target );
        }
        //Restack and sort so that we don't lie about target's invlet
        if( inv_item ) {
            inv.restack( *this );
        }
        if( was_in_container && wielding ) {
            add_msg_if_player( _( "You are now wielding an empty %s." ), weapon.tname() );
        } else if( was_in_container && worn ) {
            add_msg_if_player( _( "You are now wearing an empty %s." ), target.tname() );
        } else if( was_in_container && !is_npc() ) {
            bool drop_it = false;
            if( get_option<std::string>( "DROP_EMPTY" ) == "no" ) {
                drop_it = false;
            } else if( get_option<std::string>( "DROP_EMPTY" ) == "watertight" ) {
                drop_it = !target.is_watertight_container();
            } else if( get_option<std::string>( "DROP_EMPTY" ) == "all" ) {
                drop_it = true;
            }
            if( drop_it ) {
                add_msg( _( "You drop the empty %s." ), target.tname() );
                put_into_vehicle_or_drop( *this, item_drop_reason::deliberate, { inv.remove_item( &target ) } );
            } else {
                int quantity = inv.const_stack( inv.position_by_item( &target ) ).size();
                char letter = target.invlet ? target.invlet : ' ';
                add_msg( m_info, _( "%c - %d empty %s" ), letter, quantity, target.tname( quantity ) );
            }
        }
    } else if( inv_item ) {
        if( pickup::handle_spillable_contents( *this, target, g->m ) ) {
            i_rem( &target );
        }
        inv.restack( *this );
        inv.unsort();
    }
    return true;
}
References _, add_msg(), add_msg_if_player(), Character::can_consume_as_is(), inventory::const_stack(), consume_item(), item::contents, deliberate, item_contents::front(), g, pickup::handle_spillable_contents(), Character::i_rem(), Character::inv, item::invlet, is_npc(), item::is_watertight_container(), Character::is_wielding(), Character::is_worn(), m_info, inventory::position_by_item(), put_into_vehicle_or_drop(), inventory::remove_item(), inventory::restack(), item::tname(), inventory::unsort(), Character::weapon, and Character::worn.
Referenced by npc::consume_cbm_items(), npc::consume_food(), avatar_action::eat(), use(), and npc::use_painkiller().
consume_item()
bool player::consume_item (item & target)
Used for eating a particular item that doesn't need to be in inventory.
Returns true if the item is to be removed (doesn't remove).
Definition at line 758 of file player.cpp.
{
    if( target.is_null() ) {
        add_msg_if_player( m_info, _( "You do not have that item." ) );
        return false;
    }
    if( is_underwater() && !has_trait( trait_WATERSLEEP ) ) {
        add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return false;
    }
    item &comest = get_consumable_from( target );
    if( comest.is_null() || target.is_craft() ) {
        add_msg_if_player( m_info, _( "You can't eat your %s." ), target.tname() );
        if( is_npc() ) {
            debugmsg( "%s tried to eat a %s", name, target.tname() );
        }
        return false;
    }
    if( is_player() && !query_consume_ownership( target, *this ) ) {
        return false;
    }
    if( consume_med( comest ) ||
        eat( comest ) || feed_reactor_with( comest ) || feed_furnace_with( comest ) ||
        fuel_bionic_with( comest ) ) {
        if( target.is_container() ) {
            target.on_contents_changed();
        }
        return comest.charges <= 0;
    }
    return false;
}
References _, add_msg_if_player(), item::charges, consume_med(), debugmsg, eat(), Character::feed_furnace_with(), Character::feed_reactor_with(), Character::fuel_bionic_with(), Character::get_consumable_from(), Character::has_trait(), item::is_container(), item::is_craft(), is_npc(), item::is_null(), is_player(), Creature::is_underwater(), m_info, Character::name, item::on_contents_changed(), query_consume_ownership(), item::tname(), and trait_WATERSLEEP.
Referenced by consume(), drink_from_hands(), and avatar_action::eat().
consume_items() [1/3]
std::list< item > player::consume_items (const comp_selection< item_comp > & is, int batch, const std::function< bool(const item &)> & filter = return_true<item>)
Definition at line 1507 of file crafting.cpp.
{
    return consume_items( get_map(), is, batch, filter, pos(), PICKUP_RANGE );
}
References consume_items(), get_map(), PICKUP_RANGE, and Character::pos().
Referenced by iexamine::autodoc(), can_continue_craft(), veh_interact::complete_vehicle(), construction_activity(), prepared_item_consumption::consume(), consume_items(), craft_command::create_in_progress_craft(), iexamine::cvdmachine(), wash_activity_actor::finish(), repair_item_actor::handle_components(), activity_handlers::mend_item_finish(), mill_load_food(), iuse::multicooker(), iexamine::nanofab(), iuse::pack_cbm(), iexamine::pit(), veh_utils::repair_part(), smoker_load_food(), iexamine::tree_maple(), and sew_advanced_actor::use().
consume_items() [2/3]
std::list< item > player::consume_items (const std::vector< item_comp > & components, int batch = 1, const std::function< bool(const item &)> & filter = return_true<item>)
Definition at line 1568 of file crafting.cpp.
{
    inventory map_inv;
    map_inv.form_from_map( pos(), PICKUP_RANGE, this );
    return consume_items( select_item_component( components, batch, map_inv, false, filter ), batch,
                          filter );
}
References consume_items(), inventory::form_from_map(), PICKUP_RANGE, Character::pos(), and select_item_component().
consume_items() [3/3]
std::list< item > player::consume_items (map & m, const comp_selection< item_comp > & is, int batch, const std::function< bool(const item &)> & filter = return_true<item>, const tripoint & origin = tripoint_zero, int radius = PICKUP_RANGE)
Definition at line 1513 of file crafting.cpp.
{
    std::list<item> ret;
    if( has_trait( trait_DEBUG_HS ) ) {
        return ret;
    }
    item_comp selected_comp = is.comp;
    const tripoint &loc = origin;
    const bool by_charges = item::count_by_charges( selected_comp.type ) && selected_comp.count > 0;
    // Count given to use_amount/use_charges, changed by those functions!
    int real_count = ( selected_comp.count > 0 ) ? selected_comp.count * batch : std::abs(
                         selected_comp.count );
    // First try to get everything from the map, than (remaining amount) from player
    if( is.use_from & use_from_map ) {
        if( by_charges ) {
            std::list<item> tmp = m.use_charges( loc, radius, selected_comp.type, real_count, filter );
            ret.splice( ret.end(), tmp );
        } else {
            std::list<item> tmp = g->m.use_amount( loc, radius, selected_comp.type, real_count, filter );
            remove_ammo( tmp, *this );
            ret.splice( ret.end(), tmp );
        }
    }
    if( is.use_from & use_from_player ) {
        if( by_charges ) {
            std::list<item> tmp = use_charges( selected_comp.type, real_count, filter );
            ret.splice( ret.end(), tmp );
        } else {
            std::list<item> tmp = use_amount( selected_comp.type, real_count, filter );
            remove_ammo( tmp, *this );
            ret.splice( ret.end(), tmp );
        }
    }
    // condense those items into one
    if( by_charges && ret.size() > 1 ) {
        std::list<item>::iterator b = ret.begin();
        b++;
        while( ret.size() > 1 ) {
            ret.front().charges += b->charges;
            b = ret.erase( b );
        }
    }
    lastconsumed = selected_comp.type;
    empty_buckets( *this );
    return ret;
}
References b, comp_selection< CompType >::comp, component::count, item::count_by_charges(), empty_buckets(), g, Character::has_trait(), lastconsumed, remove_ammo(), cata::hash64_detail::ret, trait_DEBUG_HS, component::type, Character::use_amount(), Character::use_charges(), map::use_charges(), comp_selection< CompType >::use_from, use_from_map, and use_from_player.
consume_med()
bool player::consume_med (item & target) private
Consumes an item as medication.
Parameters
target Item consumed. Must be a medication or a container of medication.
Returns
Whether the target was fully consumed.
Definition at line 678 of file player.cpp.
{
    if( !target.is_medication() ) {
        return false;
    }
    const itype_id tool_type = target.get_comestible()->tool;
    const itype *req_tool = &*tool_type;
    bool tool_override = false;
    if( tool_type == itype_syringe && has_bionic( bio_syringe ) ) {
        tool_override = true;
    }
    if( req_tool->tool ) {
        if( !( has_amount( tool_type, 1 ) && has_charges( tool_type, req_tool->tool->charges_per_use ) ) &&
            !tool_override ) {
            add_msg_if_player( m_info, _( "You need a %s to consume that!" ), req_tool->nname( 1 ) );
            return false;
        }
        use_charges( tool_type, req_tool->tool->charges_per_use );
    }
    int amount_used = 1;
    if( target.type->has_use() ) {
        amount_used = target.type->invoke( *this, target, pos() );
        if( amount_used <= 0 ) {
            return false;
        }
    }
    // TODO: Get the target it was used on
    // Otherwise injecting someone will give us addictions etc.
    if( target.has_flag( "NO_INGEST" ) ) {
        const auto &comest = *target.get_comestible();
        // Assume that parenteral meds don't spoil, so don't apply rot
        modify_health( comest );
        modify_stimulation( comest );
        modify_fatigue( comest );
        modify_radiation( comest );
        modify_addiction( comest );
        modify_morale( target );
    } else {
        // Take by mouth
        consume_effects( target );
    }
    mod_moves( -250 );
    target.charges -= amount_used;
    return target.charges <= 0;
}
References _, add_msg_if_player(), bio_syringe, item::charges, Character::consume_effects(), item::get_comestible(), visitable< Character >::has_amount(), Character::has_bionic(), Character::has_charges(), item::has_flag(), itype::has_use(), itype::invoke(), item::is_medication(), itype_syringe, m_info, Creature::mod_moves(), Character::modify_addiction(), Character::modify_fatigue(), Character::modify_health(), Character::modify_morale(), Character::modify_radiation(), Character::modify_stimulation(), itype::nname(), Character::pos(), itype::tool, item::type, and Character::use_charges().
Referenced by consume_item().
consume_tools() [1/3]
void player::consume_tools (const comp_selection< tool_comp > & tool, int batch)
Definition at line 1839 of file crafting.cpp.
{
    consume_tools( get_map(), tool, batch, pos(), PICKUP_RANGE );
}
References consume_tools(), get_map(), PICKUP_RANGE, Character::pos(), and tool.
Referenced by iexamine::autodoc(), crafting::complete_disassemble(), veh_interact::complete_vehicle(), construction_activity(), prepared_item_consumption::consume(), consume_tools(), craft_consume_tools(), iexamine::cvdmachine(), activity_handlers::mend_item_finish(), iexamine::nanofab(), veh_utils::repair_part(), and iexamine::sign().
consume_tools() [2/3]
void player::consume_tools (const std::vector< tool_comp > & tools, int batch = 1, const std::string & hotkeys = DEFAULT_HOTKEYS)
Definition at line 1866 of file crafting.cpp.
{
    inventory map_inv;
    map_inv.form_from_map( pos(), PICKUP_RANGE, this );
    consume_tools( crafting::select_tool_component( tools, batch, map_inv, this, false, hotkeys,
                   cost_adjustment::none ), batch );
}
References consume_tools(), inventory::form_from_map(), none, PICKUP_RANGE, Character::pos(), and crafting::select_tool_component().
consume_tools() [3/3]
void player::consume_tools (map & m, const comp_selection< tool_comp > & tool, int batch, const tripoint & origin = tripoint_zero, int radius = PICKUP_RANGE, basecamp * bcp = nullptr)
Definition at line 1845 of file crafting.cpp.
{
    if( has_trait( trait_DEBUG_HS ) ) {
        return;
    }
    int quantity = tool.comp.count * batch;
    if( tool.use_from & use_from_player ) {
        use_charges( tool.comp.type, quantity );
    }
    if( tool.use_from & use_from_map ) {
        m.use_charges( origin, radius, tool.comp.type, quantity, return_true<item>, bcp );
    }
    // else, use_from_none (or cancel), so we don't use up any tools;
}
References Character::has_trait(), tool, trait_DEBUG_HS, Character::use_charges(), map::use_charges(), use_from_map, and use_from_player.
craft()
void player::craft (const tripoint & loc = tripoint_zero)
Start various types of crafts.
Parameters
loc the location of the workbench. tripoint_zero indicates crafting from inventory.
Definition at line 340 of file crafting.cpp.
{
    int batch_size = 0;
    const recipe *rec = select_crafting_recipe( batch_size );
    if( rec ) {
        if( crafting_allowed( *this, *rec ) ) {
            make_craft( rec->ident(), batch_size, loc );
        }
    }
}
References crafting_allowed(), recipe::ident(), make_craft(), and select_crafting_recipe().
Referenced by can_continue_craft(), craft_consume_tools(), craft_skill_gain(), game::handle_action(), and start_craft().
craft_consume_tools()
bool player::craft_consume_tools (item & craft, int mulitplier, bool start_craft)
Consume tools for the next multiplier * 5% progress of the craft.
Definition at line 1750 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "craft_consume_tools() called on non-craft '%s.' Aborting.", craft.tname() );
        return false;
    }
    if( has_trait( trait_DEBUG_HS ) ) {
        return true;
    }
    if( start_craft && mulitplier > 1 ) {
        debugmsg( "start_craft is true, but multiplier is %d > 1", mulitplier );
        return false;
    }
    const auto calc_charges = [&craft, &start_craft, &mulitplier]( int charges ) {
        int ret = charges;
        if( charges <= 0 ) {
            return ret;
        }
        // Account for batch size
        int full_cost = charges * craft.charges;
        if( start_craft ) {
            return crafting::charges_for_starting( full_cost );
        } else {
            // In case more than 5% progress was accomplished in one turn
            return crafting::charges_for_continuing( full_cost ) * mulitplier;
        }
    };
    // First check if we still have our cached selections
    const std::vector<comp_selection<tool_comp>> &cached_tool_selections =
                craft.get_cached_tool_selections();
    inventory map_inv;
    map_inv.form_from_map( pos(), PICKUP_RANGE, this );
    for( const comp_selection<tool_comp> &tool_sel : cached_tool_selections ) {
        itype_id type = tool_sel.comp.type;
        if( tool_sel.comp.count > 0 ) {
            const int count = calc_charges( tool_sel.comp.count );
            switch( tool_sel.use_from ) {
                case use_from_player:
                    if( !has_charges( type, count ) ) {
                        add_msg_player_or_npc(
                            _( "You have insufficient %s charges and can't continue crafting" ),
                            _( "<npcname> has insufficient %s charges and can't continue crafting" ),
                            item::nname( type ) );
                        craft.set_tools_to_continue( false );
                        return false;
                    }
                    break;
                case use_from_map:
                    if( !map_inv.has_charges( type, count ) ) {
                        add_msg_player_or_npc(
                            _( "You have insufficient %s charges and can't continue crafting" ),
                            _( "<npcname> has insufficient %s charges and can't continue crafting" ),
                            item::nname( type ) );
                        craft.set_tools_to_continue( false );
                        return false;
                    }
                    break;
                case use_from_both:
                case use_from_none:
                case cancel:
                case num_usages:
                    break;
            }
        } else if( !has_amount( type, 1 ) && !map_inv.has_tools( type, 1 ) ) {
            add_msg_player_or_npc(
                _( "You no longer have a %s and can't continue crafting" ),
                _( "<npcname> no longer has a %s and can't continue crafting" ),
                item::nname( type ) );
            craft.set_tools_to_continue( false );
            return false;
        }
    }
    // We have the selections, so consume them
    for( const comp_selection<tool_comp> &tool : cached_tool_selections ) {
        comp_selection<tool_comp> to_consume = tool;
        to_consume.comp.count = calc_charges( to_consume.comp.count );
        consume_tools( to_consume, 1 );
    }
    return true;
}
References _, add_msg_player_or_npc(), cancel, crafting::charges_for_continuing(), crafting::charges_for_starting(), comp_selection< CompType >::comp, consume_tools(), detail::count(), craft(), debugmsg, inventory::form_from_map(), visitable< Character >::has_amount(), Character::has_charges(), inventory::has_charges(), inventory::has_tools(), Character::has_trait(), item::nname(), num_usages, PICKUP_RANGE, Character::pos(), cata::hash64_detail::ret, start_craft(), tool, trait_DEBUG_HS, type, use_from_both, use_from_map, use_from_none, and use_from_player.
Referenced by activity_handlers::craft_do_turn(), and craft_command::create_in_progress_craft().
craft_skill_gain()
void player::craft_skill_gain (const item & craft, const int & multiplier)
Handle skill gain for player and followers during crafting.
Parameters
craft the currently in progress craft
multiplier what factor to multiply the base skill gain by. This is used to apply multiple steps of incremental skill gain simultaneously if needed.
Definition at line 771 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "craft_skill_check() called on non-craft '%s.' Aborting.", craft.tname() );
        return;
    }
    const recipe &making = craft.get_making();
    const int batch_size = craft.charges;
    std::vector<npc *> helpers = get_crafting_helpers();
    if( making.skill_used ) {
        // Normalize experience gain to crafting time, giving a bonus for longer crafting
        const double batch_mult = batch_size + base_time_to_craft( making, batch_size ) / 30000.0;
        // This is called after every 5% crafting progress, so divide by 20
        // TODO: Don't multiply, instead divide the crafting time into more "learn bits"
        const int base_practice = roll_remainder( ( making.difficulty * 15 + 10 ) * batch_mult /
                                  20.0 ) * multiplier;
        const int skill_cap = static_cast<int>( making.difficulty * 1.25 );
        practice( making.skill_used, base_practice, skill_cap, true );
        // NPCs assisting or watching should gain experience...
        for( auto &helper : helpers ) {
            //If the NPC can understand what you are doing, they gain more exp
            if( helper->get_skill_level( making.skill_used ) >= making.difficulty ) {
                helper->practice( making.skill_used, roll_remainder( base_practice / 2.0 ),
                                  skill_cap );
                if( batch_size > 1 && one_in( 3 ) ) {
                    add_msg( m_info, _( "%s assists with crafting" ), helper->name );
                }
                if( batch_size == 1 && one_in( 3 ) ) {
                    add_msg( m_info, _( "%s could assist you with a batch" ), helper->name );
                }
                // NPCs around you understand the skill used better
            } else {
                helper->practice( making.skill_used, roll_remainder( base_practice / 10.0 ),
                                  skill_cap );
                if( one_in( 3 ) ) {
                    add_msg( m_info, _( "%s watches you craft" ), helper->name );
                }
            }
        }
    }
}
References _, add_msg(), base_time_to_craft(), craft(), debugmsg, recipe::difficulty, get_crafting_helpers(), m_info, one_in(), practice(), roll_remainder(), and recipe::skill_used.
Referenced by activity_handlers::craft_do_turn().
crafting_success_roll()
double player::crafting_success_roll (const recipe & making) const
Calculate a value representing the success of the player at crafting the given recipe, taking player skill, recipe difficulty, npc helpers, and player mutations into account.
Parameters
making the recipe for which to calculate
Returns
a value >= 0.0 with >= 1.0 representing unequivocal success
Intelligence increases crafting success chance
Definition at line 817 of file crafting.cpp.
{
    int secondary_dice = 0;
    int secondary_difficulty = 0;
    for( const auto &pr : making.required_skills ) {
        secondary_dice += get_skill_level( pr.first );
        secondary_difficulty += pr.second;
    }
    // # of dice is 75% primary skill, 25% secondary (unless secondary is null)
    int skill_dice;
    if( secondary_difficulty > 0 ) {
        skill_dice = get_skill_level( making.skill_used ) * 3 + secondary_dice;
    } else {
        skill_dice = get_skill_level( making.skill_used ) * 4;
    }
    for( const npc *np : get_crafting_helpers() ) {
        if( np->get_skill_level( making.skill_used ) >=
            get_skill_level( making.skill_used ) ) {
            // NPC assistance is worth half a skill level
            skill_dice += 2;
            add_msg_if_player( m_info, _( "%s helps with crafting" ), np->name );
            break;
        }
    }
    // farsightedness can impose a penalty on electronics and tailoring success
    // it's equivalent to a 2-rank electronics penalty, 1-rank tailoring
    if( has_trait( trait_HYPEROPIC ) && !worn_with_flag( flag_FIX_FARSIGHT ) &&
        !has_effect( effect_contacts ) ) {
        int main_rank_penalty = 0;
        if( making.skill_used == skill_electronics ) {
            main_rank_penalty = 2;
        } else if( making.skill_used == skill_tailor ) {
            main_rank_penalty = 1;
        }
        skill_dice -= main_rank_penalty * 4;
    }
    // It's tough to craft with paws.  Fortunately it's just a matter of grip and fine-motor,
    // not inability to see what you're doing
    for( const trait_id &mut : get_mutations() ) {
        for( const std::pair<const skill_id, int> &skib : mut->craft_skill_bonus ) {
            if( making.skill_used == skib.first ) {
                skill_dice += skib.second;
            }
        }
    }
    // Sides on dice is 16 plus your current intelligence
    ///\EFFECT_INT increases crafting success chance
    const int skill_sides = 16 + int_cur;
    int diff_dice;
    if( secondary_difficulty > 0 ) {
        diff_dice = making.difficulty * 3 + secondary_difficulty;
    } else {
        // Since skill level is * 4 also
        diff_dice = making.difficulty * 4;
    }
    const int diff_sides = 24; // 16 + 8 (default intelligence)
    const double skill_roll = dice( skill_dice, skill_sides );
    const double diff_roll = dice( diff_dice, diff_sides );
    if( diff_roll == 0 ) {
        // Automatic success
        return 2;
    }
    return skill_roll / diff_roll;
}
References _, add_msg_if_player(), dice(), recipe::difficulty, effect_contacts, flag_FIX_FARSIGHT(), get_crafting_helpers(), Character::get_mutations(), Character::get_skill_level(), Creature::has_effect(), Character::has_trait(), Character::int_cur, m_info, recipe::required_skills, skill_electronics, skill_tailor, recipe::skill_used, trait_HYPEROPIC, and Character::worn_with_flag().
Referenced by item::handle_craft_failure(), and item::set_next_failure_point().
current_warnings_fac()
int player::current_warnings_fac (const faction_id & id)
Definition at line 873 of file player.cpp.
{
    const auto it = warning_record.find( id );
    if( it != warning_record.end() ) {
        if( it->second.second - calendar::turn > 5_minutes ) {
            it->second.first = std::max( 0,
                                         it->second.first - 1 );
        }
        return it->second.first;
    }
    return 0;
}
References calendar::turn, and warning_record.
deserialize()
virtual void player::deserialize (JsonIn & jsin) pure virtual
Implemented in avatar, and npc.
disarm()
void player::disarm (npc & target)
Try to disarm the NPC.
May result in fail attempt, you receiving the wepon and instantly wielding it, or the weapon falling down on the floor nearby. NPC is always getting angry with you.
Parameters
target Target NPC to disarm
Strength increases chance to disarm, primary stat Dexterity increases chance to disarm, secondary stat Melee increases chance to disarm Unarmed increases chance to disarm, bonus when nothing wielded
Definition at line 2309 of file melee.cpp.
{
    if( !target.is_armed() ) {
        return;
    }
    if( target.is_hallucination() ) {
        target.on_attacked( *this );
        return;
    }
    /** @EFFECT_STR increases chance to disarm, primary stat */
    /** @EFFECT_DEX increases chance to disarm, secondary stat */
    int my_roll = dice( 3, 2 * get_str() + get_dex() );
    /** @EFFECT_MELEE increases chance to disarm */
    my_roll += dice( 3, get_skill_level( skill_melee ) );
    int their_roll = dice( 3, 2 * target.get_str() + target.get_dex() );
    their_roll += dice( 3, target.get_per() );
    their_roll += dice( 3, target.get_skill_level( skill_melee ) );
    item &it = target.weapon;
    // roll your melee and target's dodge skills to check if grab/smash attack succeeds
    int hitspread = target.deal_melee_attack( this, hit_roll() );
    if( hitspread < 0 ) {
        add_msg( _( "You lunge for the %s, but miss!" ), it.tname() );
        mod_moves( -100 - stumble( *this, weapon ) - attack_cost( weapon ) );
        target.on_attacked( *this );
        return;
    }
    // hitspread >= 0, which means we are going to disarm by grabbing target by their weapon
    if( !is_armed() ) {
        /** @EFFECT_UNARMED increases chance to disarm, bonus when nothing wielded */
        my_roll += dice( 3, get_skill_level( skill_unarmed ) );
        if( my_roll >= their_roll ) {
            //~ %s: weapon name
            add_msg( _( "You grab at %s and pull with all your force!" ), it.tname() );
            //~ %1$s: weapon name, %2$s: NPC name
            add_msg( _( "You forcefully take %1$s from %2$s!" ), it.tname(), target.name );
            // wield() will deduce our moves, consider to deduce more/less moves for balance
            item rem_it = target.i_rem( &it );
            wield( rem_it );
        } else if( my_roll >= their_roll / 2 ) {
            add_msg( _( "You grab at %s and pull with all your force, but it drops nearby!" ),
                     it.tname() );
            const tripoint tp = target.pos() + tripoint( rng( -1, 1 ), rng( -1, 1 ), 0 );
            g->m.add_item_or_charges( tp, target.i_rem( &it ) );
            mod_moves( -100 );
        } else {
            add_msg( _( "You grab at %s and pull with all your force, but in vain!" ), it.tname() );
            mod_moves( -100 );
        }
        target.on_attacked( *this );
        return;
    }
    // Make their weapon fall on floor if we've rolled enough.
    mod_moves( -100 - attack_cost( weapon ) );
    if( my_roll >= their_roll ) {
        add_msg( _( "You smash %s with all your might forcing their %s to drop down nearby!" ),
                 target.name, it.tname() );
        const tripoint tp = target.pos() + tripoint( rng( -1, 1 ), rng( -1, 1 ), 0 );
        g->m.add_item_or_charges( tp, target.i_rem( &it ) );
    } else {
        add_msg( _( "You smash %s with all your might but %s remains in their hands!" ),
                 target.name, it.tname() );
    }
    target.on_attacked( *this );
}
References _, add_msg(), Character::attack_cost(), Creature::deal_melee_attack(), dice(), g, Character::get_dex(), Character::get_per(), Character::get_skill_level(), Character::get_str(), Character::hit_roll(), Character::i_rem(), Character::is_armed(), npc::is_hallucination(), Creature::mod_moves(), Character::name, npc::on_attacked(), Character::pos(), rng(), skill_melee, skill_unarmed, stumble(), item::tname(), Character::weapon, and Character::wield().
Referenced by game::npc_menu().
drink_from_hands()
int player::drink_from_hands (item & water)
used for drinking from hands, returns how many charges were consumed
Definition at line 659 of file player.cpp.
{
    int charges_consumed = 0;
    if( query_yn( _( "Drink %s from your hands?" ),
                  colorize( water.type_name(), water.color_in_inventory() ) ) ) {
        // Create a dose of water no greater than the amount of water remaining.
        item water_temp( water );
        // If player is slaked water might not get consumed.
        consume_item( water_temp );
        charges_consumed = water.charges - water_temp.charges;
        if( charges_consumed > 0 ) {
            moves -= 350;
        }
    }
    return charges_consumed;
}
References _, item::charges, item::color_in_inventory(), colorize(), consume_item(), Creature::moves, query_yn(), and item::type_name().
eat()
bool player::eat (item & food, bool force = false)
Used for eating entered comestible, returns true if comestible is successfully eaten.
Definition at line 821 of file consumption.cpp.
{
    if( !food.is_food() ) {
        return false;
    }
    const auto ret = force ? can_eat( food ) : will_eat( food, is_player() );
    if( !ret.success() ) {
        return false;
    }
    if( has_effect( effect_bloated ) &&
        ( compute_effective_nutrients( food ).kcal > 0 || food.get_comestible()->quench > 0 ) &&
        !food.has_flag( flag_NO_BLOAT ) ) {
        add_msg_if_player( _( "You force yourself to vomit to make space for %s." ), food.tname() );
        vomit();
    }
    int charges_used = 0;
    if( food.type->has_use() ) {
        if( !food.type->can_use( "DOGFOOD" ) &&
            !food.type->can_use( "CATFOOD" ) &&
            !food.type->can_use( "BIRDFOOD" ) &&
            !food.type->can_use( "CATTLEFODDER" ) ) {
            charges_used = food.type->invoke( *this, food, pos() );
            if( charges_used <= 0 ) {
                return false;
            }
        }
    }
    // Note: the block below assumes we decided to eat it
    // No coming back from here
    const int nutr = nutrition_for( food );
    const bool spoiled = food.rotten();
    // The item is solid food
    const bool chew = food.get_comestible()->comesttype == comesttype_FOOD ||
                      food.has_flag( flag_USE_EAT_VERB );
    // This item is a drink and not a solid food (and not a thick soup)
    const bool drinkable = !chew && food.get_comestible()->comesttype == comesttype_DRINK;
    // If neither of the above is true then it's a drug and shouldn't get mealtime penalty/bonus
    const bool saprophage = has_trait( trait_SAPROPHAGE );
    if( spoiled && !saprophage ) {
        add_msg_if_player( m_bad, _( "Ick, this %s doesn't taste so good" ), food.tname() );
        if( !has_trait( trait_SAPROVORE ) && !has_trait( trait_EATDEAD ) &&
            !has_bionic( bio_digestion ) ) {
            add_effect( effect_foodpoison, rng( 6_minutes, ( nutr + 1 ) * 6_minutes ) );
        }
    } else if( spoiled && saprophage ) {
        add_msg_if_player( m_good, _( "Mmm, this %s tastes delicious" ), food.tname() );
    }
    if( !consume_effects( food ) ) {
        // Already consumed by using `food.type->invoke`?
        if( charges_used > 0 ) {
            food.mod_charges( -charges_used );
        }
        return false;
    }
    food.mod_charges( -1 );
    const bool amorphous = has_trait( trait_AMORPHOUS );
    int mealtime = 250;
    if( drinkable || chew ) {
        // Those bonuses/penalties only apply to food
        // Not to smoking weed or applying bandages!
        if( has_trait( trait_MOUTH_TENTACLES )  || has_trait( trait_MANDIBLES ) ||
            has_trait( trait_FANGS_SPIDER ) ) {
            mealtime /= 2;
        } else if( has_trait( trait_SHARKTEETH ) ) {
            // SHARKBAIT! HOO HA HA!
            mealtime /= 3;
        } else if( has_trait( trait_GOURMAND ) ) {
            // Don't stack those two - that would be 25 moves per item
            mealtime -= 100;
        }
        if( has_trait( trait_BEAK_HUM ) && !drinkable ) {
            // Much better than PROBOSCIS but still optimized for fluids
            mealtime += 200;
        } else if( has_trait( trait_SABER_TEETH ) ) {
            // They get In The Way
            mealtime += 250;
        }
        if( amorphous ) {
            mealtime *= 1.1;
            // Minor speed penalty for having to flow around it
            // rather than just grab & munch
        }
    }
    moves -= mealtime;
    // If it's poisonous... poison us.
    // TODO: Move this to a flag
    if( food.poison > 0 && !has_trait( trait_POISRESIST ) &&
        !has_trait( trait_EATDEAD ) ) {
        if( food.poison >= rng( 2, 4 ) ) {
            add_effect( effect_poison, food.poison * 10_minutes );
        }
        add_effect( effect_foodpoison, food.poison * 30_minutes );
    }
    if( food.has_flag( flag_HIDDEN_HALLU ) ) {
        if( !has_effect( effect_hallu ) ) {
            add_effect( effect_hallu, 6_hours );
        }
    }
    if( amorphous ) {
        add_msg_player_or_npc( _( "You assimilate your %s." ), _( "<npcname> assimilates a %s." ),
                               food.tname() );
    } else if( drinkable ) {
        add_msg_player_or_npc( _( "You drink your %s." ), _( "<npcname> drinks a %s." ),
                               food.tname() );
    } else if( chew ) {
        add_msg_player_or_npc( _( "You eat your %s." ), _( "<npcname> eats a %s." ),
                               food.tname() );
    }
    if( food.get_comestible()->tool->tool ) {
        // Tools like lighters get used
        use_charges( food.get_comestible()->tool, 1 );
    }
    if( food.has_flag( flag_FUNGAL_VECTOR ) && !has_trait( trait_M_IMMUNE ) ) {
        add_effect( effect_fungus, 1_turns, num_bp );
    }
    // Chance to become parasitised
    if( !( has_bionic( bio_digestion ) || has_trait( trait_PARAIMMUNE ) ) ) {
        if( food.get_comestible()->parasites > 0 && !food.has_flag( flag_NO_PARASITES ) &&
            one_in( food.get_comestible()->parasites ) ) {
            switch( rng( 0, 3 ) ) {
                case 0:
                    add_effect( effect_tapeworm, 1_turns, num_bp );
                    break;
                case 1:
                    if( !has_trait( trait_ACIDBLOOD ) ) {
                        add_effect( effect_bloodworms, 1_turns, num_bp );
                    }
                    break;
                case 2:
                    add_effect( effect_brainworms, 1_turns, num_bp );
                    break;
                case 3:
                    add_effect( effect_paincysts, 1_turns, num_bp );
            }
        }
    }
    for( const std::pair<const diseasetype_id, int> &elem : food.get_comestible()->contamination ) {
        if( rng( 1, 100 ) <= elem.second ) {
            expose_to_disease( elem.first );
        }
    }
    consumption_history->elems.emplace_back( food );
    // Clean out consumption_history so it doesn't get bigger than needed.
    while( consumption_history->elems.front().time < calendar::turn - 2_days ) {
        consumption_history->elems.pop_front();
    }
    return true;
}
References _, Creature::add_effect(), add_msg_if_player(), add_msg_player_or_npc(), bio_digestion, Character::can_eat(), itype::can_use(), iuse::chew(), comesttype_DRINK(), comesttype_FOOD(), Character::compute_effective_nutrients(), Character::consume_effects(), Character::consumption_history, effect_bloated, effect_bloodworms, effect_brainworms, effect_foodpoison, effect_fungus, effect_hallu, effect_paincysts, effect_poison, effect_tapeworm, Character::expose_to_disease(), flag_FUNGAL_VECTOR(), flag_HIDDEN_HALLU(), flag_NO_BLOAT(), flag_NO_PARASITES(), flag_USE_EAT_VERB(), item::get_comestible(), Character::has_bionic(), Creature::has_effect(), item::has_flag(), Character::has_trait(), itype::has_use(), itype::invoke(), item::is_food(), is_player(), m_bad, m_good, item::mod_charges(), Creature::moves, num_bp, Character::nutrition_for(), one_in(), item::poison, Character::pos(), cata::hash64_detail::ret, rng(), item::rotten(), item::tname(), trait_ACIDBLOOD, trait_AMORPHOUS, trait_BEAK_HUM, trait_EATDEAD, trait_FANGS_SPIDER, trait_GOURMAND, trait_M_IMMUNE, trait_MANDIBLES, trait_MOUTH_TENTACLES, trait_PARAIMMUNE, trait_POISRESIST, trait_SABER_TEETH, trait_SAPROPHAGE, trait_SAPROVORE, trait_SHARKTEETH, calendar::turn, item::type, Character::use_charges(), Character::vomit(), and Character::will_eat().
Referenced by consume_item(), drink_nectar(), avatar_action::eat_here(), iexamine::flower_poppy(), vehicle::interact_with(), iexamine::keg(), and try_consume().
expected_time_to_craft()
int player::expected_time_to_craft (const recipe & rec, int batch_size = 1, bool in_progress = false) const
Expected time to craft a recipe, with assumption that multipliers stay constant.
Definition at line 406 of file crafting.cpp.
{
    const size_t assistants = available_assistant_count( rec );
    float modifier = crafting_speed_multiplier( *this, rec, in_progress );
    return rec.batch_time( batch_size, modifier, assistants );
}
References available_assistant_count(), recipe::batch_time(), and crafting_speed_multiplier().
Referenced by select_crafting_recipe().
fall_damage_mod()
float player::fall_damage_mod () const override virtual
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
Dexterity decreases damage from falling Dodge decreases damage from falling
Implements Creature.
Definition at line 367 of file player.cpp.
{
    if( has_effect_with_flag( "EFFECT_FEATHER_FALL" ) ) {
        return 0.0f;
    }
    float ret = 1.0f;
    // Ability to land properly is 2x as important as dexterity itself
    /** @EFFECT_DEX decreases damage from falling */
    /** @EFFECT_DODGE decreases damage from falling */
    float dex_dodge = dex_cur / 2.0 + get_skill_level( skill_dodge );
    // Penalize for wearing heavy stuff
    const float average_leg_encumb = ( encumb( bp_leg_l ) + encumb( bp_leg_r ) ) / 2.0;
    dex_dodge -= ( average_leg_encumb + encumb( bp_torso ) ) / 10;
    // But prevent it from increasing damage
    dex_dodge = std::max( 0.0f, dex_dodge );
    // 100% damage at 0, 75% at 10, 50% at 20 and so on
    ret *= ( 100.0f - ( dex_dodge * 4.0f ) ) / 100.0f;
    if( has_trait( trait_PARKOUR ) ) {
        ret *= 2.0f / 3.0f;
    }
    // TODO: Bonus for Judo, mutations. Penalty for heavy weight (including mutations)
    return std::max( 0.0f, ret );
}
References bp_leg_l, bp_leg_r, bp_torso, Character::dex_cur, Character::encumb(), Character::get_skill_level(), Creature::has_effect_with_flag(), Character::has_trait(), cata::hash64_detail::ret, skill_dodge, and trait_PARKOUR.
Referenced by impact(), and iexamine::ledge().
fire_gun() [1/2]
int player::fire_gun (const tripoint & target, int shots, item & gun)
Fires a gun or auxiliary gunmod (ignoring any current mode)
Parameters
target where the first shot is aimed at (may vary for later shots)
shots maximum number of shots to fire (less may be fired in some circumstances)
gun item to fire (which does not necessary have to be in the players possession)
Returns
number of shots actually fired
Definition at line 811 of file ranged.cpp.
{
    if( !gun.is_gun() ) {
        debugmsg( "%s tried to fire non-gun (%s).", name, gun.tname() );
        return 0;
    }
    bool is_mech_weapon = false;
    if( is_mounted() &&
        mounted_creature->has_flag( MF_RIDEABLE_MECH ) ) {
        is_mech_weapon = true;
    }
    int shots = max_shots;
    // Number of shots to fire is limited by the amount of remaining ammo
    if( gun.ammo_required() ) {
        shots = std::min( shots, static_cast<int>( gun.ammo_remaining() / gun.ammo_required() ) );
    }
    // cap our maximum burst size by the amount of UPS power left
    if( !gun.has_flag( flag_VEHICLE ) && gun.get_gun_ups_drain() > 0 ) {
        shots = std::min( shots, static_cast<int>( charges_of( itype_UPS ) / gun.get_gun_ups_drain() ) );
    }
    if( shots <= 0 ) {
        debugmsg( "Attempted to fire zero or negative shots using %s", gun.tname() );
    }
    cata::optional<shape_factory> shape;
    if( gun.ammo_current() && gun.ammo_current()->ammo ) {
        shape = gun.ammo_current()->ammo->shape;
    }
    map &here = get_map();
    // Shaped attacks don't allow aiming, so they don't suffer from lack of aim either
    int character_recoil = shape ? recoil_vehicle() : recoil_total();
    // Penalty is (intentionally) based off mode shots, not ammo-limited.
    dispersion_sources dispersion = calculate_dispersion( here, *this, gun, character_recoil,
                                    max_shots > 1 );
    bool aoe_attack = gun.gun_skill() == skill_launcher || shape;
    tripoint aim = target;
    int curshot = 0;
    int hits = 0; // total shots on target
    while( curshot != shots ) {
        if( gun.faults.count( fault_gun_chamber_spent ) && curshot == 0 ) {
            moves -= 50;
            gun.faults.erase( fault_gun_chamber_spent );
            add_msg_if_player( _( "You cycle your %s manually." ), gun.tname() );
        }
        if( !ranged::handle_gun_damage( *this, gun ) ) {
            break;
        }
        // If this is a vehicle mounted turret, which vehicle is it mounted on?
        const vehicle *in_veh = has_effect( effect_on_roof ) ? veh_pointer_or_null( here.veh_at(
                                    pos() ) ) : nullptr;
        projectile projectile = make_gun_projectile( gun );
        // Damage reduction from insufficient strength, if using a STR_DRAW weapon.
        projectile.impact.mult_damage( ranged::str_draw_damage_modifier( gun, *this ) );
        if( has_trait( trait_NORANGEDCRIT ) ) {
            projectile.add_effect( ammo_effect_NO_CRIT );
        }
        if( !shape ) {
            auto shot = projectile_attack( projectile, pos(), aim, dispersion, this, in_veh );
            if( shot.missed_by <= .1 ) {
                // TODO: check head existence for headshot
                g->events().send<event_type::character_gets_headshot>( getID() );
            }
            if( shot.hit_critter ) {
                hits++;
            }
        } else {
            // 30 degree cap, like for projectiles
            double angle_offset_arcmin = std::min( dispersion.roll(), 1800.0 ) * ( one_in( 2 ) ? 1 : -1 );
            double angle_offset = units::to_radians( units::from_arcmin( angle_offset_arcmin ) );
            double dx = aim.x - pos().x;
            double dy = aim.y - pos().y;
            double new_angle = atan2( dy, dx ) + angle_offset;
            // Always using trig here, rotations in maximum metric are weird
            double length = trig_dist( pos(), aim );
            rl_vec3d vec_pos( pos() );
            rl_vec3d new_aim = vec_pos + rl_vec3d( length, 0, 0 ).rotated( new_angle );
            ranged::execute_shaped_attack( *shape->create( vec_pos, new_aim ), projectile, *this );
        }
        curshot++;
        make_gun_sound_effect( *this, shots > 1, &gun );
        sfx::generate_gun_sound( *this, gun );
        cycle_action( gun, pos() );
        if( has_trait( trait_PYROMANIA ) && !has_morale( MORALE_PYROMANIA_STARTFIRE ) ) {
            if( gun.has_flag( flag_PYROMANIAC_WEAPON ) ) {
                add_msg_if_player( m_good, _( "You feel a surge of euphoria as flames roar out of the %s!" ),
                                   gun.tname() );
                add_morale( MORALE_PYROMANIA_STARTFIRE, 15, 15, 8_hours, 6_hours );
                rem_morale( MORALE_PYROMANIA_NOFIRE );
            }
        }
        if( gun.ammo_consume( gun.ammo_required(), pos() ) != gun.ammo_required() ) {
            debugmsg( "Unexpected shortage of ammo whilst firing %s", gun.tname() );
            break;
        }
        if( !gun.has_flag( flag_VEHICLE ) ) {
            use_charges( itype_UPS, gun.get_gun_ups_drain() );
        }
        if( aoe_attack ) {
            continue; // skip retargeting for launchers
        }
    }
    if( gun.has_flag( flag_RELOAD_AND_SHOOT ) ) {
        // Reset aim for bows and other reload-and-shoot weapons.
        recoil = MAX_RECOIL;
    } else {
        // Now actually apply recoil for the future shots
        // But only for one shot, because bursts kinda suck
        int gun_recoil = gun.gun_recoil( can_use_bipod( here, pos() ) );
        // If user is currently able to fire a mounted gun freely, penalize recoil based on size class.
        if( gun.has_flag( flag_MOUNTED_GUN ) && !can_use_bipod( here, pos() ) ) {
            if( get_size() == MS_HUGE ) {
                gun_recoil = gun_recoil * 2;
            } else {
                gun_recoil = gun_recoil * 3;
            }
        }
        recoil += gun_recoil;
        if( is_mech_weapon ) {
            // mechs can handle recoil far better. they are built around their main gun.
            recoil = recoil / 2;
        }
        recoil = std::min( MAX_RECOIL, recoil );
    }
    // Use different amounts of time depending on the type of gun and our skill
    moves -= time_to_attack( *this, *gun.type );
    // Practice the base gun skill proportionally to number of hits, but always by one.
    practice( skill_gun, ( hits + 1 ) * 5 );
    // launchers train weapon skill for both hits and misses.
    int practice_units = aoe_attack ? curshot : hits;
    practice( gun.gun_skill(), ( practice_units + 1 ) * 5 );
    return curshot;
}
References _, projectile::add_effect(), Character::add_morale(), add_msg_if_player(), itype::ammo, item::ammo_consume(), item::ammo_current(), ammo_effect_NO_CRIT, item::ammo_remaining(), item::ammo_required(), atan2(), calculate_dispersion(), can_use_bipod(), character_gets_headshot, visitable< Character >::charges_of(), cycle_action(), debugmsg, effect_on_roof, ranged::execute_shaped_attack(), fault_gun_chamber_spent, item::faults, flag_MOUNTED_GUN(), flag_PYROMANIAC_WEAPON(), flag_RELOAD_AND_SHOOT(), flag_VEHICLE(), units::from_arcmin(), g, sfx::generate_gun_sound(), item::get_gun_ups_drain(), get_map(), Character::get_size(), Character::getID(), item::gun_recoil(), item::gun_skill(), ranged::handle_gun_damage(), Creature::has_effect(), item::has_flag(), Character::has_morale(), Character::has_trait(), projectile::impact, item::is_gun(), Character::is_mounted(), itype_UPS, m_good, make_gun_projectile(), make_gun_sound_effect(), MAX_RECOIL, MF_RIDEABLE_MECH, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, Character::mounted_creature, Creature::moves, MS_HUGE, damage_instance::mult_damage(), Character::name, one_in(), Character::pos(), practice(), projectile_attack(), Character::recoil, Character::recoil_total(), Character::recoil_vehicle(), Character::rem_morale(), dispersion_sources::roll(), rl_vec3d::rotated(), skill_gun, skill_launcher, ranged::str_draw_damage_modifier(), time_to_attack(), item::tname(), units::to_radians(), trait_NORANGEDCRIT, trait_PYROMANIA, trig_dist(), item::type, Character::use_charges(), map::veh_at(), veh_pointer_or_null(), tripoint::x, and tripoint::y.
fire_gun() [2/2]
int player::fire_gun (const tripoint & target, int shots = 1)
Fires a gun or auxiliary gunmod (ignoring any current mode)
Parameters
target where the first shot is aimed at (may vary for later shots)
shots maximum number of shots to fire (less may be fired in some circumstances)
Returns
number of shots actually fired
Definition at line 806 of file ranged.cpp.
{
    return fire_gun( target, shots, weapon );
}
References fire_gun(), and Character::weapon.
Referenced by npc::execute_action(), turret_data::fire(), fire_gun(), mattack::frag(), mattack::rifle(), gun_actor::shoot(), and mattack::tankgun().
get_available_recipes()
recipe_subset player::get_available_recipes (const inventory & crafting_inv, const std::vector< npc * > * helpers = nullptr, recipe_filter filter = nullptr) const
Returns all available recipes (from books and npc companions)
Parameters
crafting_inv Current available items to craft
helpers List of NPCs that could help with crafting.
filter If set, will return only recipes that match the filter (should be much faster).
Definition at line 2298 of file player.cpp.
{
    recipe_subset res;
    if( filter ) {
        res.include_if( get_learned_recipes(), filter );
    } else {
        res.include( get_learned_recipes() );
    }
    res.include( get_recipes_from_books( crafting_inv, filter ) );
    if( helpers != nullptr ) {
        for( npc *np : *helpers ) {
            // Directly form the helper's inventory
            res.include( get_recipes_from_books( np->inv, filter ) );
            // Being told what to do
            res.include_if( np->get_learned_recipes(), [ this, &filter ]( const recipe & r ) {
                if( filter && !filter( r ) ) {
                    return false;
                }
                // Skilled enough to understand
                return get_skill_level( r.skill_used ) >= static_cast<int>( r.difficulty * 0.8f );
            } );
        }
    }
    return res;
}
References recipe::difficulty, Character::get_learned_recipes(), get_recipes_from_books(), Character::get_skill_level(), recipe_subset::include(), recipe_subset::include_if(), and recipe::skill_used.
Referenced by item::final_info(), has_recipe(), and select_crafting_recipe().
get_crafting_helpers()
std::vector< npc * > player::get_crafting_helpers (size_t max = 0) const
Returns nearby NPCs ready and willing to help with crafting or some other manual task.
Parameters
max If set, limits number of helpers to that value
Definition at line 2308 of file crafting.cpp.
{
    size_t n = 0;
    return g->get_npcs_if( [ &n, max, this]( const npc & guy ) {
        // NPCs can help craft if awake, taking orders, within pickup range and have clear path
        if( max != 0 && n >= max ) {
            return false;
        }
        bool ok = !guy.in_sleep_state() && guy.is_obeying( *this ) &&
                  rl_dist( guy.pos(), pos() ) < PICKUP_RANGE &&
                  g->m.clear_path( pos(), guy.pos(), PICKUP_RANGE, 1, 100 );
        if( ok ) {
            n += 1;
        }
        return ok;
    } );
}
References g, Character::in_sleep_state(), npc::is_obeying(), ok, PICKUP_RANGE, Character::pos(), and rl_dist().
Referenced by available_assistant_count(), game::butcher(), can_make(), activity_handlers::chop_logs_finish(), complete_construction(), complete_craft(), iuse::craft(), craft_skill_gain(), crafting_success_roll(), avatar::get_book_reader(), get_lift_assist(), avatar::read(), scale_time(), and select_crafting_recipe().
get_eligible_containers_for_crafting()
std::vector< const item * > player::get_eligible_containers_for_crafting () const
Definition at line 482 of file crafting.cpp.
{
    std::vector<const item *> conts;
    if( is_container_eligible_for_crafting( weapon, true ) ) {
        conts.push_back( &weapon );
    }
    for( const auto &it : worn ) {
        if( is_container_eligible_for_crafting( it, false ) ) {
            conts.push_back( &it );
        }
    }
    for( size_t i = 0; i < inv.size(); i++ ) {
        for( const auto &it : inv.const_stack( i ) ) {
            if( is_container_eligible_for_crafting( it, false ) ) {
                conts.push_back( &it );
            }
        }
    }
    map &here = get_map();
    // get all potential containers within PICKUP_RANGE tiles including vehicles
    for( const tripoint &loc : closest_points_first( pos(), PICKUP_RANGE ) ) {
        // can not reach this -> can not access its contents
        if( pos() != loc && !here.clear_path( pos(), loc, PICKUP_RANGE, 1, 100 ) ) {
            continue;
        }
        if( here.accessible_items( loc ) ) {
            for( const auto &it : here.i_at( loc ) ) {
                if( is_container_eligible_for_crafting( it, true ) ) {
                    conts.emplace_back( &it );
                }
            }
        }
        if( const cata::optional<vpart_reference> vp = here.veh_at( loc ).part_with_feature( "CARGO",
                true ) ) {
            for( const auto &it : vp->vehicle().get_items( vp->part_index() ) ) {
                if( is_container_eligible_for_crafting( it, false ) ) {
                    conts.emplace_back( &it );
                }
            }
        }
    }
    return conts;
}
References map::accessible_items(), map::clear_path(), closest_points_first(), inventory::const_stack(), get_map(), map::i_at(), Character::inv, is_container_eligible_for_crafting(), optional_vpart_position::part_with_feature(), PICKUP_RANGE, Character::pos(), inventory::size(), map::veh_at(), Character::weapon, and Character::worn.
Referenced by check_eligible_containers_for_crafting().
get_lift_assist()
int player::get_lift_assist () const
Definition at line 340 of file player.cpp.
{
    int result = 0;
    const std::vector<npc *> helpers = get_crafting_helpers();
    for( const npc *np : helpers ) {
        result += np->get_str();
    }
    return result;
}
References get_crafting_helpers().
Referenced by can_lift().
get_melee()
float player::get_melee () const override virtual
Returns melee skill level, to be used to throttle dodge practice.
Implements Creature.
Definition at line 2559 of file player.cpp.
{
    return get_skill_level( skill_id( "melee" ) );
}
References Character::get_skill_level(), and skill_id.
get_recipes_from_books()
recipe_subset player::get_recipes_from_books (const inventory & crafting_inv, recipe_filter filter = nullptr) const
Returns all recipes that are known from the books (either in inventory or nearby).
Definition at line 2278 of file player.cpp.
{
    recipe_subset res;
    for( const auto &stack : crafting_inv.const_slice() ) {
        const item &candidate = stack->front();
        for( std::pair<const recipe *, int> recipe_entry :
             candidate.get_available_recipes( *this ) ) {
            if( filter && !filter( *recipe_entry.first ) ) {
                continue;
            }
            res.include( recipe_entry.first, recipe_entry.second );
        }
    }
    return res;
}
References inventory::const_slice(), item::get_available_recipes(), and recipe_subset::include().
Referenced by get_available_recipes().
get_safe_reference()
safe_reference< player > player::get_safe_reference ()
Definition at line 2635 of file player.cpp.
{
    return anchor.reference_to( this );
}
References anchor, and safe_reference_anchor::reference_to().
Referenced by itype::invoke().
gun_engagement_moves()
int player::gun_engagement_moves (const item & gun, int target = 0, int start = MAX_RECOIL) const
How many moves does it take to aim gun to the target accuracy.
Definition at line 572 of file ranged.cpp.
{
    int mv = 0;
    double penalty = start;
    while( penalty > target ) {
        double adj = aim_per_move( gun, penalty );
        if( adj <= 0 ) {
            break;
        }
        penalty -= adj;
        mv++;
    }
    return mv;
}
References Character::aim_per_move().
Referenced by item::gun_info(), and print_aim().
gunmod_add()
void player::gunmod_add (item & gun, item & mod)
Starts activity to install gunmod having warned user about any risk of failure or irremovable mods s.
Definition at line 2139 of file player.cpp.
{
    if( !gun.is_gunmod_compatible( mod ).success() ) {
        debugmsg( "Tried to add incompatible gunmod" );
        return;
    }
    if( !has_item( gun ) && !has_item( mod ) ) {
        debugmsg( "Tried gunmod installation but mod/gun not in player possession" );
        return;
    }
    // first check at least the minimum requirements are met
    if( !has_trait( trait_DEBUG_HS ) && !can_use( mod, gun ) ) {
        return;
    }
    // any (optional) tool charges that are used during installation
    auto odds = gunmod_installation_odds( gun, mod );
    int roll = odds.first;
    int risk = odds.second;
    std::string tool;
    int qty = 0;
    bool requery = false;
    item modded = gun;
    modded.put_in( mod );
    bool no_magazines = modded.common_ammo_default().is_null();
    std::string query_msg = mod.is_irremovable()
                            ? _( "<color_yellow>Permanently</color> install your %1$s in your %2$s?" )
                            : _( "Attach your %1$s to your %2$s?" );
    if( no_magazines ) {
        query_msg += "\n";
        query_msg += colorize(
                         _( "Warning: after installing this mod, a magazine adapter mod will be required to load it!" ),
                         c_red );
    }
    uilist prompt;
    prompt.text = string_format( query_msg,
                                 colorize( mod.tname(), mod.color_in_inventory() ),
                                 colorize( gun.tname(), gun.color_in_inventory() ) );
    std::vector<std::function<void()>> actions;
    if( roll < 100 ) {
        prompt.addentry( -1, true, 'w',
                         string_format( _( "Try without tools (%i%%) risking damage (%i%%)" ), roll, risk ) );
        actions.emplace_back( [&] {} );
        prompt.addentry( -1, has_charges( itype_small_repairkit, 100 ), 'f',
                         string_format( _( "Use 100 charges of firearm repair kit (%i%%)" ), std::min( roll * 2, 100 ) ) );
        actions.emplace_back( [&] {
            tool = "small_repairkit";
            qty = 100;
            roll *= 2; // firearm repair kit improves success...
            risk /= 2; // ...and reduces the risk of damage upon failure
        } );
        prompt.addentry( -1, has_charges( itype_large_repairkit, 25 ), 'g',
                         string_format( _( "Use 25 charges of gunsmith repair kit (%i%%)" ), std::min( roll * 3, 100 ) ) );
        actions.emplace_back( [&] {
            tool = "large_repairkit";
            qty = 25;
            roll *= 3; // gunsmith repair kit improves success markedly...
            risk = 0;  // ...and entirely prevents damage upon failure
        } );
    } else {
        prompt.addentry( -1, true, 'w', _( "Install without tools" ) );
        actions.emplace_back( [&] {} );
    }
    prompt.addentry( -1, true, 'c', _( "Compare before/after installation" ) );
    actions.emplace_back( [&] {
        requery = true;
        game_menus::inv::compare( gun, modded );
    } );
    do {
        requery = false;
        prompt.query();
        if( prompt.ret < 0 ) {
            add_msg_if_player( _( "Never mind." ) );
            return; // player canceled installation
        }
        actions[ prompt.ret ]();
    } while( requery );
    const int moves = !has_trait( trait_DEBUG_HS ) ? mod.type->gunmod->install_time : 0;
    assign_activity( activity_id( "ACT_GUNMOD_ADD" ), moves, -1, 0, tool );
    activity.targets.push_back( item_location( *this, &gun ) );
    activity.targets.push_back( item_location( *this, &mod ) );
    activity.values.push_back( 0 ); // dummy value
    activity.values.push_back( roll ); // chance of success (%)
    activity.values.push_back( risk ); // chance of damage (%)
    activity.values.push_back( qty ); // tool charges
}
References _, Character::activity, add_msg_if_player(), Character::assign_activity(), c_red, Character::can_use(), item::color_in_inventory(), colorize(), item::common_ammo_default(), game_menus::inv::compare(), debugmsg, gunmod_installation_odds(), Character::has_charges(), visitable< Character >::has_item(), Character::has_trait(), item::is_gunmod_compatible(), string_id< T >::is_null(), itype_large_repairkit, itype_small_repairkit, Creature::moves, pickup::prompt, item::put_in(), string_format(), player_activity::targets, item::tname(), tool, trait_DEBUG_HS, and player_activity::values.
Referenced by iuse::gunmod_attach().
gunmod_installation_odds()
std::pair< int, int > player::gunmod_installation_odds (const item & gun, const item & mod) const
Returns
Odds for success (pair.first) and gunmod damage (pair.second)
Definition at line 2106 of file player.cpp.
{
    // Mods with INSTALL_DIFFICULT have a chance to fail, potentially damaging the gun
    if( !mod.has_flag( "INSTALL_DIFFICULT" ) || has_trait( trait_DEBUG_HS ) ) {
        return std::make_pair( 100, 0 );
    }
    int roll = 100; // chance of success (%)
    int risk = 0;   // chance of failure (%)
    int chances = 1; // start with 1 in 6 (~17% chance)
    for( const auto &e : mod.type->min_skills ) {
        // gain an additional chance for every level above the minimum requirement
        skill_id sk = e.first == skill_weapon ? gun.gun_skill() : e.first;
        chances += std::max( get_skill_level( sk ) - e.second, 0 );
    }
    // cap success from skill alone to 1 in 5 (~83% chance)
    roll = std::min( static_cast<double>( chances ), 5.0 ) / 6.0 * 100;
    // focus is either a penalty or bonus of at most +/-10%
    roll += ( std::min( std::max( focus_pool, 140 ), 60 ) - 100 ) / 4;
    // dexterity and intelligence give +/-2% for each point above or below 12
    roll += ( get_dex() - 12 ) * 2;
    roll += ( get_int() - 12 ) * 2;
    // each level of damage to the base gun reduces success by 10%
    roll -= std::max( gun.damage_level( 4 ), 0 ) * 10;
    roll = std::min( std::max( roll, 0 ), 100 );
    // risk of causing damage on failure increases with less durable guns
    risk = ( 100 - roll ) * ( ( 10.0 - std::min( gun.type->gun->durability, 9 ) ) / 10.0 );
    return std::make_pair( roll, risk );
}
References item::damage_level(), Character::focus_pool, Character::get_dex(), Character::get_int(), Character::get_skill_level(), itype::gun, item::gun_skill(), Character::has_trait(), skill_weapon, trait_DEBUG_HS, and item::type.
Referenced by gunmod_inventory_preset::get_odds(), and gunmod_add().
gunmod_remove()
bool player::gunmod_remove (item & gun, item & mod)
Removes gunmod after first unloading any contained ammo and returns true on success.
Definition at line 2055 of file player.cpp.
{
    if( !has_mod( gun, mod ) ) {
        debugmsg( "Cannot remove non-existent gunmod" );
        return false;
    }
    item_location loc = item_location( *this, &mod );
    if( mod.ammo_remaining() && !unload( loc ) ) {
        return false;
    }
    gun.gun_set_mode( gun_mode_id( "DEFAULT" ) );
    //TODO: add activity for removing gunmods
    if( mod.typeId() == itype_brass_catcher ) {
        gun.casings_handle( [&]( item & e ) {
            return i_add_or_drop( e );
        } );
    }
    const itype *modtype = mod.type;
    i_add_or_drop( mod );
    gun.remove_item( mod );
    //If the removed gunmod added mod locations, check to see if any mods are in invalid locations
    if( !modtype->gunmod->add_mod.empty() ) {
        std::map<gunmod_location, int> mod_locations = gun.get_mod_locations();
        for( const auto &slot : mod_locations ) {
            int free_slots = gun.get_free_mod_locations( slot.first );
            for( auto the_mod : gun.gunmods() ) {
                if( the_mod->type->gunmod->location == slot.first && free_slots < 0 ) {
                    gunmod_remove( gun, *the_mod );
                    free_slots++;
                } else if( mod_locations.find( the_mod->type->gunmod->location ) ==
                           mod_locations.end() ) {
                    gunmod_remove( gun, *the_mod );
                }
            }
        }
    }
    //~ %1$s - gunmod, %2$s - gun.
    add_msg_if_player( _( "You remove your %1$s from your %2$s." ), modtype->nname( 1 ),
                       gun.tname() );
    return true;
}
References _, add_msg_if_player(), item::casings_handle(), debugmsg, item::get_free_mod_locations(), item::get_mod_locations(), item::gun_set_mode(), itype::gunmod, gunmod_remove(), item::gunmods(), has_mod(), Character::i_add_or_drop(), itype_brass_catcher, itype::nname(), visitable< T >::remove_item(), item::tname(), and unload().
Referenced by gunmod_remove(), and detach_gunmods_actor::use().
handle_skill_warning()
void player::handle_skill_warning (const skill_id & id, bool force_warning = false)
This handles warning the player that there current activity will not give them xp.
Definition at line 2411 of file player.cpp.
{
    //remind the player intermittently that no skill gain takes place
    if( is_player() && ( force_warning || one_in( 5 ) ) ) {
        SkillLevel &level = get_skill_level_object( id );
        const Skill &skill = id.obj();
        std::string skill_name = skill.name();
        int curLevel = level.level();
        add_msg( m_info, _( "This task is too simple to train your %s beyond %d." ),
                 skill_name, curLevel );
    }
}
References _, add_msg(), Character::get_skill_level_object(), is_player(), SkillLevel::level(), m_info, Skill::name(), and one_in().
Referenced by practice(), and start_craft().
has_gun_for_ammo()
bool player::has_gun_for_ammo (const ammotype & at) const
Check whether the player has a gun that uses the given type of ammo.
Definition at line 2446 of file player.cpp.
{
    return has_item_with( [at]( const item & it ) {
        // item::ammo_type considers the active gunmod.
        return it.is_gun() && it.ammo_types().count( at );
    } );
}
References item::ammo_types(), visitable< Character >::has_item_with(), and item::is_gun().
Referenced by npc::value().
has_identified()
virtual bool player::has_identified (const itype_id & item_id) const pure virtual
Note that we've read a book at least once.
Implemented in npc, and avatar.
Referenced by read_inventory_preset::is_known().
has_magazine_for_ammo()
bool player::has_magazine_for_ammo (const ammotype & at) const
Definition at line 2454 of file player.cpp.
{
    return has_item_with( [&at]( const item & it ) {
        return !it.has_flag( "NO_RELOAD" ) &&
               ( ( it.is_magazine() && it.ammo_types().count( at ) ) ||
                 ( it.is_gun() && it.magazine_integral() && it.ammo_types().count( at ) ) ||
                 ( it.is_gun() && it.magazine_current() != nullptr &&
                   it.magazine_current()->ammo_types().count( at ) ) );
    } );
}
References item::ammo_types(), item::has_flag(), visitable< Character >::has_item_with(), item::is_gun(), item::is_magazine(), item::magazine_current(), and item::magazine_integral().
has_recipe()
int player::has_recipe (const recipe * r, const inventory & crafting_inv, const std::vector< npc * > & helpers) const
Definition at line 2431 of file player.cpp.
{
    if( !r->skill_used ) {
        return 0;
    }
    if( knows_recipe( r ) ) {
        return r->difficulty;
    }
    const auto available = get_available_recipes( crafting_inv, &helpers );
    return available.contains( *r ) ? available.get_custom_difficulty( r ) : -1;
}
References available, recipe::difficulty, get_available_recipes(), Character::knows_recipe(), and recipe::skill_used.
Referenced by can_make(), complete_craft(), and iuse::craft().
has_recipe_requirements()
bool player::has_recipe_requirements (const recipe & rec) const
Definition at line 2426 of file player.cpp.
{
    return get_all_skills().has_recipe_requirements( rec );
}
References Character::get_all_skills(), and SkillLevelMap::has_recipe_requirements().
Referenced by avatar::create(), and find_repair_difficulty().
hp_percentage()
int player::hp_percentage () const override virtual
Returns overall % of HP remaining.
Implements Creature.
Definition at line 605 of file player.cpp.
{
    const bodypart_id head_id = bodypart_id( "head" );
    const bodypart_id torso_id = bodypart_id( "torso" );
    int total_cur = 0;
    int total_max = 0;
    // Head and torso HP are weighted 3x and 2x, respectively
    total_cur = get_part_hp_cur( head_id ) * 3 + get_part_hp_cur( torso_id ) * 2;
    total_max = get_part_hp_max( head_id ) * 3 + get_part_hp_max( torso_id ) * 2;
    for( const std::pair< const bodypart_str_id, bodypart> &elem : get_body() ) {
        total_cur += elem.second.get_hp_cur();
        total_max += elem.second.get_hp_max();
    }
    return ( 100 * total_cur ) / total_max;
}
References Creature::get_body(), Creature::get_part_hp_cur(), and Creature::get_part_hp_max().
Referenced by npc::character_danger(), npc::emergency(), npc::hp_description(), and npc::process_turn().
immune_to()
bool player::immune_to (body_part bp, damage_unit dam) const
Check if a given body part is immune to a given damage type.
This function checks whether a given body part cannot be damaged by a given damage_unit. Note that this refers only to reduction of hp on that part. It does not account for clothing damage, pain, status effects, etc.
Parameters
bp Body part to perform the check on
dam Type of damage to check for
Returns
true if given damage can not reduce hp of given body part
Definition at line 350 of file player.cpp.
{
    if( has_trait( trait_DEBUG_NODMG ) || is_immune_damage( dam.type ) ) {
        return true;
    }
    passive_absorb_hit( convert_bp( bp ).id(), dam );
    for( const item &cloth : worn ) {
        if( cloth.get_coverage() == 100 && cloth.covers( bp ) ) {
            cloth.mitigate_damage( dam );
        }
    }
    return dam.amount <= 0;
}
References damage_unit::amount, convert_bp(), Character::has_trait(), Character::is_immune_damage(), Character::passive_absorb_hit(), trait_DEBUG_NODMG, damage_unit::type, and Character::worn.
Referenced by game::get_dangerous_tile().
impact()
int player::impact (int force, const tripoint & pos) override virtual
Deals falling/collision damage with terrain/creature at pos.
Implements Creature.
Definition at line 396 of file player.cpp.
{
    // Falls over ~30m are fatal more often than not
    // But that would be quite a lot considering 21 z-levels in game
    // so let's assume 1 z-level is comparable to 30 force
    if( force <= 0 ) {
        return force;
    }
    // Damage modifier (post armor)
    float mod = 1.0f;
    int effective_force = force;
    int cut = 0;
    // Percentage armor penetration - armor won't help much here
    // TODO: Make cushioned items like bike helmets help more
    float armor_eff = 1.0f;
    // Shock Absorber CBM heavily reduces damage
    const bool shock_absorbers = has_active_bionic( bionic_id( "bio_shock_absorber" ) );
    // Being slammed against things rather than landing means we can't
    // control the impact as well
    const bool slam = p != pos();
    std::string target_name = "a swarm of bugs";
    Creature *critter = g->critter_at( p );
    if( critter != this && critter != nullptr ) {
        target_name = critter->disp_name();
        // Slamming into creatures and NPCs
        // TODO: Handle spikes/horns and hard materials
        armor_eff = 0.5f; // 2x as much as with the ground
        // TODO: Modify based on something?
        mod = 1.0f;
        effective_force = force;
    } else if( const optional_vpart_position vp = g->m.veh_at( p ) ) {
        // Slamming into vehicles
        // TODO: Integrate it with vehicle collision function somehow
        target_name = vp->vehicle().disp_name();
        if( vp.part_with_feature( "SHARP", true ) ) {
            // Now we're actually getting impaled
            cut = force; // Lots of fun
        }
        mod = slam ? 1.0f : fall_damage_mod();
        armor_eff = 0.25f; // Not much
        if( !slam && vp->part_with_feature( "ROOF", true ) ) {
            // Roof offers better landing than frame or pavement
            // TODO: Make this not happen with heavy duty/plated roof
            effective_force /= 2;
        }
    } else {
        // Slamming into terrain/furniture
        target_name = g->m.disp_name( p );
        int hard_ground = g->m.has_flag( TFLAG_DIGGABLE, p ) ? 0 : 3;
        armor_eff = 0.25f; // Not much
        // Get cut by stuff
        // This isn't impalement on metal wreckage, more like flying through a closed window
        cut = g->m.has_flag( TFLAG_SHARP, p ) ? 5 : 0;
        effective_force = force + hard_ground;
        mod = slam ? 1.0f : fall_damage_mod();
        if( g->m.has_furn( p ) ) {
            // TODO: Make furniture matter
        } else if( g->m.has_flag( TFLAG_SWIMMABLE, p ) ) {
            // TODO: Some formula of swimming
            effective_force /= 4;
        }
    }
    // Rescale for huge force
    // At >30 force, proper landing is impossible and armor helps way less
    if( effective_force > 30 ) {
        // Armor simply helps way less
        armor_eff *= 30.0f / effective_force;
        if( mod < 1.0f ) {
            // Everything past 30 damage gets a worse modifier
            const float scaled_mod = std::pow( mod, 30.0f / effective_force );
            const float scaled_damage = ( 30.0f * mod ) + scaled_mod * ( effective_force - 30.0f );
            mod = scaled_damage / effective_force;
        }
    }
    if( !slam && mod < 1.0f && mod * force < 5 ) {
        // Perfect landing, no damage (regardless of armor)
        add_msg_if_player( m_warning, _( "You land on %s." ), target_name );
        return 0;
    }
    // Shock absorbers kick in only when they need to, so if our other protections fail, fall back on them
    if( shock_absorbers ) {
        effective_force -= 15; // Provide a flat reduction to force
        if( mod > 0.25f ) {
            mod = 0.25f; // And provide a 75% reduction against that force if we don't have it already
        }
        if( effective_force < 0 ) {
            effective_force = 0;
        }
    }
    int total_dealt = 0;
    if( mod * effective_force >= 5 ) {
        for( int i = 0; i < num_hp_parts; i++ ) {
            const bodypart_id bp = convert_bp( hp_to_bp( static_cast<hp_part>( i ) ) ).id();
            const int bash = effective_force * rng( 60, 100 ) / 100;
            damage_instance di;
            di.add_damage( DT_BASH, bash, 0, armor_eff, mod );
            // No good way to land on sharp stuff, so here modifier == 1.0f
            di.add_damage( DT_CUT, cut, 0, armor_eff, 1.0f );
            total_dealt += deal_damage( nullptr, bp, di ).total_damage();
        }
    }
    if( total_dealt > 0 && is_player() ) {
        // "You slam against the dirt" is fine
        add_msg( m_bad, _( "You are slammed against %1$s for %2$d damage." ),
                 target_name, total_dealt );
    } else if( is_player() && shock_absorbers ) {
        add_msg( m_bad, _( "You are slammed against %s!" ),
                 target_name, total_dealt );
        add_msg( m_good, _( "but your shock absorbers negate the damage!" ) );
    } else if( slam ) {
        // Only print this line if it is a slam and not a landing
        // Non-players should only get this one: player doesn't know how much damage was dealt
        // and landing messages for each slammed creature would be too much
        add_msg_player_or_npc( m_bad,
                               _( "You are slammed against %s." ),
                               _( "<npcname> is slammed against %s." ),
                               target_name );
    } else {
        // No landing message for NPCs
        add_msg_if_player( m_warning, _( "You land on %s." ), target_name );
    }
    if( x_in_y( mod, 1.0f ) ) {
        add_effect( effect_downed, rng( 1_turns, 1_turns + mod * 3_turns ) );
    }
    return total_dealt;
}
References _, add_msg_if_player(), bionic_id, Creature::disp_name(), fall_damage_mod(), g, Character::has_active_bionic(), m_warning, num_hp_parts, Character::pos(), TFLAG_DIGGABLE, TFLAG_SHARP, and TFLAG_SWIMMABLE.
Referenced by trapfunc::ledge(), and throw_item().
is_npc()
bool player::is_npc () const inline override virtual
Reimplemented from Creature.
Definition at line 109 of file player.h.
{
            return false;    // Overloaded for NPCs in npc.h
        }
Referenced by activity_on_turn_move_loot(), iuse::adrenaline_injector(), iuse::artifact(), npc::assess_danger(), iuse::blech_because_unclean(), iuse::blood_draw(), activity_handlers::build_do_turn(), iuse::burrow(), butchery_drops_harvest(), can_do_activity_there(), can_takeoff(), debug_menu::character_edit_menu(), check_npc_revert(), activity_handlers::chop_tree_finish(), veh_interact::complete_vehicle(), consume(), consume_item(), iuse::datura(), player_activity::do_turn(), debug_menu::mission_debug::edit(), eff_fun_hallu(), iuse::einktabletpc(), extract_or_wreck_cbms(), fetch_activity(), find_auto_consume(), iuse::fishing_rod(), game::forced_door_closing(), iuse::fungicide(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), bionic_install_preset::get_denial(), bionic_install_surgeon_preset::get_denial(), iuse::hand_crank(), npc::handle_sound(), knock_back_to(), marloss_prevented(), iuse::mycus(), pickup::obtain_and_tokenize_items(), iuse::oxytorch(), iuse::pickaxe(), iuse::poison(), iuse::portable_game(), sounds::process_sound_markers(), activity_handlers::pulp_finish(), iuse::radio_mod(), activity_handlers::read_finish(), veh_utils::repair_part(), requirements_map(), iuse::seed(), select_ammo(), select_item_component(), sort_armor(), takeoff(), iuse::teleport(), Character::uninstall_bionic(), pick_lock_actor::use(), musical_instrument_actor::use(), heal_actor::use(), sew_advanced_actor::use(), heal_actor::use_healing_item(), activity_handlers::vehicle_finish(), and iuse::vibe().
is_player()
bool player::is_player () const inline override virtual
Reimplemented from Creature.
Definition at line 99 of file player.h.
{
            return true;
        }
Referenced by add_faction_warning(), Character::bionics_uninstall_failure(), iexamine::chainfence(), debug_menu::character_edit_menu(), consume_item(), monster::die(), avatar::do_read(), eat(), debug_menu::mission_debug::edit(), eff_fun_hallu(), activity_handlers::find_mount_do_turn(), heal_actor::finish_using(), game::forced_door_closing(), handle_skill_warning(), harvest_common(), mdeath::jabberwock(), trapfunc::ledge(), avatar::load(), on_hit(), Character::perform_technique(), pick_plant(), map::player_in_field(), popup_player_or_npc(), practice(), sounds::process_sound_markers(), query_for_item(), game_menus::inv::read(), activity_handlers::read_do_turn(), set_up_butchery_activity(), sort_armor(), iexamine::trap(), iexamine::tree_hickory(), Character::uninstall_bionic(), musical_instrument_actor::use(), mutagen_iv_actor::use(), and heal_actor::use_healing_item().
item_reload_cost()
int player::item_reload_cost (const item & it, const item & ammo, int qty) const
Calculate (but do not deduct) the number of moves required to reload an item with specified quantity of ammo.
Parameters
it Item to calculate reload cost for
ammo either ammo or magazine to use when reloading the item
qty maximum units of ammo to reload. Capped by remaining capacity and ignored if reloading using a magazine.
Gun decreases the time taken to reload a magazine Pistol decreases time taken to reload a pistol Smg decreases time taken to reload an SMG Rifle decreases time taken to reload a rifle Shotgun decreases time taken to reload a shotgun Launcher decreases time taken to reload a launcher Strength reduces reload time of some weapons
Definition at line 1553 of file player.cpp.
{
    if( ammo.is_ammo() ) {
        qty = std::max( std::min( ammo.charges, qty ), 1 );
    } else if( ammo.is_ammo_container() || ammo.is_container() ) {
        qty = clamp( qty, ammo.contents.front().charges, 1 );
    } else if( ammo.is_magazine() ) {
        qty = 1;
    } else {
        debugmsg( "cannot determine reload cost as %s is neither ammo or magazine", ammo.tname() );
        return 0;
    }
    // If necessary create duplicate with appropriate number of charges
    item obj = ammo;
    obj = obj.split( qty );
    if( obj.is_null() ) {
        obj = ammo;
    }
    // No base cost for handling ammo - that's already included in obtain cost
    // We have the ammo in our hands right now
    int mv = item_handling_cost( obj, true, 0 );
    if( ammo.has_flag( "MAG_BULKY" ) ) {
        mv *= 1.5; // bulky magazines take longer to insert
    }
    if( !it.is_gun() && !it.is_magazine() ) {
        return mv + 100; // reload a tool or sealable container
    }
    /** @EFFECT_GUN decreases the time taken to reload a magazine */
    /** @EFFECT_PISTOL decreases time taken to reload a pistol */
    /** @EFFECT_SMG decreases time taken to reload an SMG */
    /** @EFFECT_RIFLE decreases time taken to reload a rifle */
    /** @EFFECT_SHOTGUN decreases time taken to reload a shotgun */
    /** @EFFECT_LAUNCHER decreases time taken to reload a launcher */
    int cost = ( it.is_gun() ? it.get_reload_time() : it.type->magazine->reload_time ) * qty;
    skill_id sk = it.is_gun() ? it.type->gun->skill_used : skill_gun;
    mv += cost / ( 1.0f + std::min( get_skill_level( sk ) * 0.1f, 1.0f ) );
    if( it.has_flag( "STR_RELOAD" ) ) {
        /** @EFFECT_STR reduces reload time of some weapons */
        mv -= get_str() * 20;
    }
    return std::max( mv, 25 );
}
References item::charges, clamp(), item::contents, debugmsg, item_contents::front(), item::get_reload_time(), Character::get_skill_level(), Character::get_str(), itype::gun, item::has_flag(), item::is_ammo(), item::is_ammo_container(), item::is_container(), item::is_gun(), item::is_magazine(), item::is_null(), Character::item_handling_cost(), itype::magazine, skill_gun, item::split(), item::tname(), and item::type.
Referenced by npc::do_reload(), npc::enough_time_to_reload(), and unload().
knock_back_to()
void player::knock_back_to (const tripoint & to) override virtual
Knocks the player to a specified tile.
Maximum Strength allows knocked back player to knock back, damage, stun some monsters
Implements Creature.
Definition at line 534 of file player.cpp.
{
    if( to == pos() ) {
        return;
    }
    if( rl_dist( pos(), to ) < 2 && get_map().obstructed_by_vehicle_rotation( pos(), to ) ) {
        tripoint intervening = to;
        if( one_in( 2 ) ) {
            intervening.x = pos().x;
        } else {
            intervening.y = pos().y;
        }
        apply_damage( nullptr, bodypart_id( "torso" ), 3 );
        add_effect( effect_stunned, 2_turns );
        add_msg_player_or_npc( _( "You bounce off a %s!" ), _( "<npcname> bounces off a %s!" ),
                               g->m.obstacle_name( intervening ) );
        return;
    }
    // First, see if we hit a monster
    if( monster *const critter = g->critter_at<monster>( to ) ) {
        deal_damage( critter, bodypart_id( "torso" ), damage_instance( DT_BASH, critter->type->size ) );
        add_effect( effect_stunned, 1_turns );
        /** @EFFECT_STR_MAX allows knocked back player to knock back, damage, stun some monsters */
        if( ( str_max - 6 ) / 4 > critter->type->size ) {
            critter->knock_back_from( pos() ); // Chain reaction!
            critter->apply_damage( this, bodypart_id( "torso" ), ( str_max - 6 ) / 4 );
            critter->add_effect( effect_stunned, 1_turns );
        } else if( ( str_max - 6 ) / 4 == critter->type->size ) {
            critter->apply_damage( this, bodypart_id( "torso" ), ( str_max - 6 ) / 4 );
            critter->add_effect( effect_stunned, 1_turns );
        }
        critter->check_dead_state();
        add_msg_player_or_npc( _( "You bounce off a %s!" ), _( "<npcname> bounces off a %s!" ),
                               critter->name() );
        return;
    }
    if( npc *const np = g->critter_at<npc>( to ) ) {
        deal_damage( np, bodypart_id( "torso" ), damage_instance( DT_BASH, np->get_size() + 1 ) );
        add_effect( effect_stunned, 1_turns );
        np->deal_damage( this, bodypart_id( "torso" ), damage_instance( DT_BASH, 3 ) );
        add_msg_player_or_npc( _( "You bounce off %s!" ), _( "<npcname> bounces off %s!" ),
                               np->name );
        np->check_dead_state();
        return;
    }
    // If we're still in the function at this point, we're actually moving a tile!
    if( g->m.has_flag( "LIQUID", to ) && g->m.has_flag( TFLAG_DEEP_WATER, to ) ) {
        if( !is_npc() ) {
            avatar_action::swim( g->m, g->u, to );
        }
        // TODO: NPCs can't swim!
    } else if( g->m.impassable( to ) ) { // Wait, it's a wall
        // It's some kind of wall.
        // TODO: who knocked us back? Maybe that creature should be the source of the damage?
        apply_damage( nullptr, bodypart_id( "torso" ), 3 );
        add_effect( effect_stunned, 2_turns );
        add_msg_player_or_npc( _( "You bounce off a %s!" ), _( "<npcname> bounces off a %s!" ),
                               g->m.obstacle_name( to ) );
    } else { // It's no wall
        setpos( to );
    }
}
References _, Creature::add_effect(), add_msg_player_or_npc(), Creature::apply_damage(), Character::apply_damage(), Creature::check_dead_state(), Character::deal_damage(), DT_BASH, effect_stunned, g, get_map(), is_npc(), Creature::knock_back_from(), one_in(), Character::pos(), rl_dist(), Character::setpos(), Character::str_max, avatar_action::swim(), TFLAG_DEEP_WATER, tripoint::x, and tripoint::y.
list_ammo()
bool player::list_ammo (const item & base, std::vector< item::reload_option > & ammo_list, bool include_empty_mags = true, bool include_potential = false) const
Definition at line 1132 of file player.cpp.
{
    auto opts = base.gunmods();
    opts.push_back( &base );
    if( base.magazine_current() ) {
        opts.push_back( base.magazine_current() );
    }
    for( const auto mod : base.gunmods() ) {
        if( mod->magazine_current() ) {
            opts.push_back( mod->magazine_current() );
        }
    }
    bool ammo_match_found = false;
    int ammo_search_range = is_mounted() ? -1 : 1;
    for( const auto e : opts ) {
        for( const item_location &ammo : find_ammo( *e, include_empty_mags, ammo_search_range ) ) {
            // don't try to unload frozen liquids
            if( ammo->is_watertight_container() && ammo->contents_made_of( SOLID ) ) {
                continue;
            }
            auto id = ( ammo->is_ammo_container() || ammo->is_container() )
                      ? ammo->contents.front().typeId()
                      : ammo->typeId();
            const bool can_reload_with = e->can_reload_with( id );
            if( can_reload_with ) {
                // Speedloaders require an empty target.
                if( include_potential || !ammo->has_flag( "SPEEDLOADER" ) || e->ammo_remaining() < 1 ) {
                    ammo_match_found = true;
                }
            }
            if( ( include_potential && can_reload_with )
                || can_reload( *e, id ) || e->has_flag( "RELOAD_AND_SHOOT" ) ) {
                ammo_list.emplace_back( this, e, &base, ammo );
            }
        }
    }
    return ammo_match_found;
}
References can_reload(), item::contents, item::contents_made_of(), Character::find_ammo(), item_contents::front(), item::gunmods(), item::has_flag(), item::is_ammo_container(), item::is_container(), Character::is_mounted(), item::is_watertight_container(), item::magazine_current(), SOLID, and item::typeId().
Referenced by favorite_ammo_or_select(), and select_ammo().
load()
void player::load (const JsonObject & data) protected
Load variables from json into object.
These variables are common to both the avatar and NPCs.
Definition at line 869 of file savegame_json.cpp.
{
    Character::load( data );
    JsonArray parray;
    character_id tmpid;
    data.read( "tank_plut", tank_plut );
    data.read( "reactor_plut", reactor_plut );
    data.read( "slow_rad", slow_rad );
    data.read( "scent", scent );
    data.read( "male", male );
    data.read( "cash", cash );
    data.read( "recoil", recoil );
    data.read( "in_vehicle", in_vehicle );
    data.read( "last_sleep_check", last_sleep_check );
    if( data.read( "id", tmpid ) && tmpid.is_valid() ) {
        // Templates have invalid ids, so we only assign here when valid.
        // When the game starts, a new valid id will be assigned if not already
        // present.
        setID( tmpid );
    }
    data.read( "addictions", addictions );
    data.read( "followers", follower_ids );
    // Add the earplugs.
    if( has_bionic( bionic_id( "bio_ears" ) ) && !has_bionic( bionic_id( "bio_earplugs" ) ) ) {
        add_bionic( bionic_id( "bio_earplugs" ) );
    }
    // Add the blindfold.
    if( has_bionic( bionic_id( "bio_sunglasses" ) ) && !has_bionic( bionic_id( "bio_blindfold" ) ) ) {
        add_bionic( bionic_id( "bio_blindfold" ) );
    }
    // Fixes bugged characters for CBM's preventing mutations.
    for( const bionic_id &bid : get_bionics() ) {
        for( const trait_id &mid : bid->canceled_mutations ) {
            if( has_trait( mid ) ) {
                remove_mutation( mid );
            }
        }
    }
    if( data.has_array( "faction_warnings" ) ) {
        for( JsonObject warning_data : data.get_array( "faction_warnings" ) ) {
            warning_data.allow_omitted_members();
            std::string fac_id = warning_data.get_string( "fac_warning_id" );
            int warning_num = warning_data.get_int( "fac_warning_num" );
            time_point warning_time = calendar::before_time_starts;
            warning_data.read( "fac_warning_time", warning_time );
            warning_record[faction_id( fac_id )] = std::make_pair( warning_num, warning_time );
        }
    }
    int tmptar;
    int tmptartyp = 0;
    data.read( "last_target", tmptar );
    data.read( "last_target_type", tmptartyp );
    data.read( "last_target_pos", last_target_pos );
    data.read( "ammo_location", ammo_location );
    if( tmptartyp == +1 ) {
        // Use overmap_buffer because game::active_npc is not filled yet.
        last_target = overmap_buffer.find_npc( character_id( tmptar ) );
    } else if( tmptartyp == -1 ) {
        // Need to do this *after* the monsters have been loaded!
        last_target = g->critter_tracker->from_temporary_id( tmptar );
    }
    data.read( "destination_point", destination_point );
    // TODO: move to Character
    camps.clear();
    for( JsonObject bcdata : data.get_array( "camps" ) ) {
        bcdata.allow_omitted_members();
        tripoint_abs_omt bcpt;
        bcdata.read( "pos", bcpt );
        camps.insert( bcpt );
    }
}
References Character::add_bionic(), Character::addictions, ammo_location, calendar::before_time_starts, bionic_id, Character::camps, cash, character_id, Character::destination_point, Character::fac_id, overmapbuffer::find_npc(), follower_ids, g, JsonObject::get_array(), Character::get_bionics(), JsonObject::has_array(), Character::has_bionic(), Character::has_trait(), Character::in_vehicle, character_id::is_valid(), Character::last_sleep_check, last_target, last_target_pos, Character::load(), Character::male, overmap_buffer, Character::reactor_plut, JsonObject::read(), Character::recoil, Character::remove_mutation(), scent, Character::setID(), Character::slow_rad, Character::tank_plut, and warning_record.
Referenced by avatar::load(), and npc::load().
long_craft()
void player::long_craft (const tripoint & loc = tripoint_zero)
Definition at line 360 of file crafting.cpp.
{
    int batch_size = 0;
    const recipe *rec = select_crafting_recipe( batch_size );
    if( rec ) {
        if( crafting_allowed( *this, *rec ) ) {
            make_all_craft( rec->ident(), batch_size, loc );
        }
    }
}
References crafting_allowed(), recipe::ident(), make_all_craft(), and select_crafting_recipe().
Referenced by game::handle_action().
make_all_craft()
void player::make_all_craft (const recipe_id & id, int batch_size, const tripoint & loc = tripoint_zero)
Definition at line 606 of file crafting.cpp.
{
    make_craft_with_command( id_to_make, batch_size, true, loc );
}
References make_craft_with_command().
Referenced by long_craft().
make_craft()
void player::make_craft (const recipe_id & id, int batch_size, const tripoint & loc = tripoint_zero)
Definition at line 601 of file crafting.cpp.
{
    make_craft_with_command( id_to_make, batch_size, false, loc );
}
References make_craft_with_command().
Referenced by craft().
make_craft_with_command()
void player::make_craft_with_command (const recipe_id & id_to_make, int batch_size, bool is_long = false, const tripoint & loc = tripoint_zero)
Definition at line 611 of file crafting.cpp.
{
    const auto &recipe_to_make = *id_to_make;
    if( !recipe_to_make ) {
        return;
    }
    *last_craft = craft_command( &recipe_to_make, batch_size, is_long, this, loc );
    last_craft->execute();
}
References last_craft.
Referenced by make_all_craft(), and make_craft().
making_would_work()
bool player::making_would_work (const recipe_id & id_to_make, int batch_size)
Definition at line 371 of file crafting.cpp.
{
    const auto &making = *id_to_make;
    if( !( making && crafting_allowed( *this, making ) ) ) {
        return false;
    }
    if( !can_make( &making, batch_size ) ) {
        std::string buffer = _( "You can no longer make that craft!" );
        buffer += "\n";
        buffer += making.simple_requirements().list_missing();
        popup( buffer, PF_NONE );
        return false;
    }
    return check_eligible_containers_for_crafting( making, batch_size );
}
References _, can_make(), check_eligible_containers_for_crafting(), crafting_allowed(), PF_NONE, and popup().
Referenced by activity_handlers::craft_do_turn(), and recraft().
mend_item()
void player::mend_item (item_location && obj, bool interactive = true)
Attempt to mend an item (fix any current faults)
Parameters
obj Object to mend
interactive if true prompts player when multiple faults, otherwise mends the first
Definition at line 1397 of file player.cpp.
{
    if( has_trait( trait_DEBUG_HS ) ) {
        uilist menu;
        menu.text = _( "Toggle which fault?" );
        std::vector<std::pair<fault_id, bool>> opts;
        for( const auto &f : obj->faults_potential() ) {
            opts.emplace_back( f, !!obj->faults.count( f ) );
            menu.addentry( -1, true, -1, string_format(
                               opts.back().second ? pgettext( "fault", "Mend: %s" ) : pgettext( "fault", "Set: %s" ),
                               f.obj().name() ) );
        }
        if( opts.empty() ) {
            add_msg( m_info, _( "The %s doesn't have any faults to toggle." ), obj->tname() );
            return;
        }
        menu.query();
        if( menu.ret >= 0 ) {
            if( opts[ menu.ret ].second ) {
                obj->faults.erase( opts[ menu.ret ].first );
            } else {
                obj->faults.insert( opts[ menu.ret ].first );
            }
        }
        return;
    }
    auto inv = crafting_inventory();
    struct mending_option {
        fault_id fault;
        std::reference_wrapper<const mending_method> method;
        bool doable;
    };
    std::vector<mending_option> mending_options;
    for( const fault_id &f : obj->faults ) {
        for( const auto &m : f->mending_methods() ) {
            mending_option opt { f, m.second, true };
            for( const auto &sk : m.second.skills ) {
                if( get_skill_level( sk.first ) < sk.second ) {
                    opt.doable = false;
                    break;
                }
            }
            opt.doable = opt.doable &&
                         m.second.requirements->can_make_with_inventory( inv, is_crafting_component );
            mending_options.emplace_back( opt );
        }
    }
    if( mending_options.empty() ) {
        if( interactive ) {
            add_msg( m_info, _( "The %s doesn't have any faults to mend." ), obj->tname() );
            if( obj->damage() > 0 ) {
                const std::set<itype_id> &rep = obj->repaired_with();
                if( !rep.empty() ) {
                    const std::string repair_options =
                    enumerate_as_string( rep.begin(), rep.end(), []( const itype_id & e ) {
                        return item::nname( e );
                    }, enumeration_conjunction::or_ );
                    add_msg( m_info, _( "It is damaged, and could be repaired with %s.  "
                                        "%s to use one of those items." ),
                             repair_options, press_x( ACTION_USE ) );
                }
            }
        }
        return;
    }
    int sel = 0;
    if( interactive ) {
        uilist menu;
        menu.text = _( "Mend which fault?" );
        menu.desc_enabled = true;
        menu.desc_lines_hint = 0; // Let uilist handle description height
        constexpr int fold_width = 80;
        for( const mending_option &opt : mending_options ) {
            const mending_method &method = opt.method;
            const nc_color col = opt.doable ? c_white : c_light_gray;
            auto reqs = method.requirements.obj();
            auto tools = reqs.get_folded_tools_list( fold_width, col, inv );
            auto comps = reqs.get_folded_components_list( fold_width, col, inv, is_crafting_component );
            std::string descr;
            if( method.turns_into ) {
                descr += string_format( _( "Turns into: <color_cyan>%s</color>\n" ),
                                        method.turns_into->obj().name() );
            }
            if( method.also_mends ) {
                descr += string_format( _( "Also mends: <color_cyan>%s</color>\n" ),
                                        method.also_mends->obj().name() );
            }
            descr += string_format( _( "Time required: <color_cyan>%s</color>\n" ),
                                    to_string_approx( method.time ) );
            if( method.skills.empty() ) {
                descr += string_format( _( "Skills: <color_cyan>none</color>\n" ) );
            } else {
                descr += string_format( _( "Skills: %s\n" ),
                                        enumerate_as_string( method.skills.begin(), method.skills.end(),
                [this]( const std::pair<skill_id, int> &sk ) -> std::string {
                    if( get_skill_level( sk.first ) >= sk.second )
                    {
                        return string_format( pgettext( "skill requirement",
                                                        //~ %1$s: skill name, %2$s: current skill level, %3$s: required skill level
                                                        "<color_cyan>%1$s</color> <color_green>(%2$d/%3$d)</color>" ),
                                              sk.first->name(), get_skill_level( sk.first ), sk.second );
                    } else
                    {
                        return string_format( pgettext( "skill requirement",
                                                        //~ %1$s: skill name, %2$s: current skill level, %3$s: required skill level
                                                        "<color_cyan>%1$s</color> <color_yellow>(%2$d/%3$d)</color>" ),
                                              sk.first->name(), get_skill_level( sk.first ), sk.second );
                    }
                } ) );
            }
            for( const std::string &line : tools ) {
                descr += line + "\n";
            }
            for( const std::string &line : comps ) {
                descr += line + "\n";
            }
            const std::string desc = method.description + "\n\n" + colorize( descr, col );
            menu.addentry_desc( -1, true, -1, method.name.translated(), desc );
        }
        menu.query();
        if( menu.ret < 0 ) {
            add_msg( _( "Never mind." ) );
            return;
        }
        sel = menu.ret;
    }
    if( sel >= 0 ) {
        const mending_option &opt = mending_options[sel];
        if( !opt.doable ) {
            if( interactive ) {
                add_msg( m_info, _( "You are currently unable to mend the %s this way." ), obj->tname() );
            }
            return;
        }
        const mending_method &method = opt.method;
        assign_activity( activity_id( "ACT_MEND_ITEM" ), to_moves<int>( method.time ) );
        activity.name = opt.fault.str();
        activity.str_values.emplace_back( method.id );
        activity.targets.push_back( std::move( obj ) );
    }
}
References _, ACTION_USE, add_msg(), uilist::addentry(), uilist::addentry_desc(), mending_method::also_mends, c_light_gray, c_white, colorize(), Character::crafting_inventory(), uilist::desc_enabled, uilist::desc_lines_hint, enumerate_as_string(), iexamine::fault(), requirement_data::get_folded_tools_list(), Character::get_skill_level(), Character::has_trait(), Character::inv, is_crafting_component(), line(), m_info, fault::mending_methods(), string_id< T >::obj(), or_, pgettext(), press_x(), uilist::query(), mending_method::requirements, uilist::ret, mending_method::skills, string_format(), uilist::text, mending_method::time, to_string_approx(), trait_DEBUG_HS, and mending_method::turns_into.
Referenced by iexamine::autoclave_empty(), avatar_action::mend(), and iuse::pack_cbm().
mod_stat()
void player::mod_stat (const std::string & stat, float modifier) override virtual
Reimplemented from Character.
Definition at line 189 of file player.cpp.
{
    if( stat == "thirst" ) {
        mod_thirst( modifier );
    } else if( stat == "fatigue" ) {
        mod_fatigue( modifier );
    } else if( stat == "oxygen" ) {
        oxygen += modifier;
    } else if( stat == "stamina" ) {
        mod_stamina( modifier );
    } else {
        // Fall through to the creature method.
        Character::mod_stat( stat, modifier );
    }
}
References Character::mod_fatigue(), Character::mod_stamina(), Character::mod_stat(), Character::mod_thirst(), and Character::oxygen.
Referenced by consume_drug_iuse::use().
normalize()
void player::normalize () override virtual
Calls Character::normalize() normalizes HP and body temperature.
Reimplemented from Character.
Definition at line 178 of file player.cpp.
{
    Character::normalize();
    recalc_hp();
    temp_cur.fill( BODYTEMP_NORM );
    temp_conv.fill( BODYTEMP_NORM );
    set_stamina( get_stamina_max() );
}
References BODYTEMP_NORM, Character::get_stamina_max(), Character::normalize(), Character::recalc_hp(), Character::set_stamina(), Character::temp_conv, and Character::temp_cur.
on_dodge()
void player::on_dodge (Creature * source, float difficulty) override virtual
Called after the player has successfully dodged an attack.
Implements Creature.
Definition at line 205 of file player.cpp.
{
    static const matec_id tec_none( "tec_none" );
    // Each avoided hit consumes an available dodge
    // When no more available we are likely to fail player::dodge_roll
    dodges_left--;
    // dodging throws of our aim unless we are either skilled at dodging or using a small weapon
    if( is_armed() && weapon.is_gun() ) {
        recoil += std::max( weapon.volume() / 250_ml - get_skill_level( skill_dodge ), 0 ) * rng( 0, 100 );
        recoil = std::min( MAX_RECOIL, recoil );
    }
    // Even if we are not to train still call practice to prevent skill rust
    difficulty = std::max( difficulty, 0.0f );
    practice( skill_dodge, difficulty * 2, difficulty );
    martial_arts_data->ma_ondodge_effects( *this );
    // For adjacent attackers check for techniques usable upon successful dodge
    if( source && square_dist( pos(), source->pos() ) == 1 ) {
        matec_id tec = pick_technique( *source, used_weapon(), false, true, false );
        if( tec != tec_none && !is_dead_state() ) {
            if( get_stamina() < get_stamina_max() / 3 ) {
                add_msg( m_bad, _( "You try to counterattack but you are too exhausted!" ) );
            } else {
                melee_attack( *source, false, &tec );
            }
        }
    }
}
References _, add_msg(), Character::dodges_left, Character::get_skill_level(), Character::get_stamina(), Character::get_stamina_max(), Character::is_armed(), Character::is_dead_state(), item::is_gun(), m_bad, Character::martial_arts_data, MAX_RECOIL, Character::melee_attack(), Character::pick_technique(), Creature::pos(), Character::pos(), practice(), Character::recoil, rng(), skill_dodge, square_dist(), tec_none, Character::used_weapon(), item::volume(), and Character::weapon.
Referenced by mattack::grab().
on_hit()
void player::on_hit (Creature * source, bodypart_id bp_hit, float difficulty = INT_MIN, dealt_projectile_attack const * proj = nullptr) override virtual
Handles special defenses from an attack that hit us (source can be null)
Reimplemented from Character.
Definition at line 239 of file player.cpp.
{
    check_dead_state();
    if( source == nullptr || proj != nullptr ) {
        return;
    }
    bool u_see = g->u.sees( *this );
    if( has_active_bionic( bionic_id( "bio_ods" ) ) && get_power_level() > 5_kJ ) {
        if( is_player() ) {
            add_msg( m_good, _( "Your offensive defense system shocks %s in mid-attack!" ),
                     source->disp_name() );
        } else if( u_see ) {
            add_msg( _( "%1$s's offensive defense system shocks %2$s in mid-attack!" ),
                     disp_name(),
                     source->disp_name() );
        }
        int shock = rng( 1, 4 );
        mod_power_level( units::from_kilojoule( -shock ) );
        damage_instance ods_shock_damage;
        ods_shock_damage.add_damage( DT_ELECTRIC, shock * 5 );
        // Should hit body part used for attack
        source->deal_damage( this, bodypart_id( "torso" ), ods_shock_damage );
    }
    if( !wearing_something_on( bp_hit ) &&
        ( has_trait( trait_SPINES ) || has_trait( trait_QUILLS ) ) ) {
        int spine = rng( 1, has_trait( trait_QUILLS ) ? 20 : 8 );
        if( !is_player() ) {
            if( u_see ) {
                add_msg( _( "%1$s's %2$s puncture %3$s in mid-attack!" ), name,
                         ( has_trait( trait_QUILLS ) ? _( "quills" ) : _( "spines" ) ),
                         source->disp_name() );
            }
        } else {
            add_msg( m_good, _( "Your %1$s puncture %2$s in mid-attack!" ),
                     ( has_trait( trait_QUILLS ) ? _( "quills" ) : _( "spines" ) ),
                     source->disp_name() );
        }
        damage_instance spine_damage;
        spine_damage.add_damage( DT_STAB, spine );
        source->deal_damage( this, bodypart_id( "torso" ), spine_damage );
    }
    if( ( !( wearing_something_on( bp_hit ) ) ) && ( has_trait( trait_THORNS ) ) &&
        ( !( source->has_weapon() ) ) ) {
        if( !is_player() ) {
            if( u_see ) {
                add_msg( _( "%1$s's %2$s scrape %3$s in mid-attack!" ), name,
                         _( "thorns" ), source->disp_name() );
            }
        } else {
            add_msg( m_good, _( "Your thorns scrape %s in mid-attack!" ), source->disp_name() );
        }
        int thorn = rng( 1, 4 );
        damage_instance thorn_damage;
        thorn_damage.add_damage( DT_CUT, thorn );
        // In general, critters don't have separate limbs
        // so safer to target the torso
        source->deal_damage( this, bodypart_id( "torso" ), thorn_damage );
    }
    if( ( !( wearing_something_on( bp_hit ) ) ) && ( has_trait( trait_CF_HAIR ) ) ) {
        if( !is_player() ) {
            if( u_see ) {
                add_msg( _( "%1$s gets a load of %2$s's %3$s stuck in!" ), source->disp_name(),
                         name, ( _( "hair" ) ) );
            }
        } else {
            add_msg( m_good, _( "Your hairs detach into %s!" ), source->disp_name() );
        }
        source->add_effect( effect_stunned, 2_turns );
        if( one_in( 3 ) ) { // In the eyes!
            source->add_effect( effect_blind, 2_turns );
        }
    }
    if( worn_with_flag( "REQUIRES_BALANCE" ) && !has_effect( effect_downed ) ) {
        int rolls = 4;
        if( worn_with_flag( "ROLLER_ONE" ) ) {
            rolls += 2;
        }
        if( has_trait( trait_PROF_SKATER ) ) {
            rolls--;
        }
        if( has_trait( trait_DEFT ) ) {
            rolls--;
        }
        if( stability_roll() < dice( rolls, 10 ) ) {
            if( !is_player() ) {
                if( u_see ) {
                    add_msg( _( "%1$s loses their balance while being hit!" ), name );
                }
            } else {
                add_msg( m_bad, _( "You lose your balance while being hit!" ) );
            }
            // This kind of downing is not subject to immunity.
            add_effect( effect_downed, 2_turns, num_bp, 0, true );
        }
    }
    Character::on_hit( source, bp_hit, 0.0f, proj );
}
References _, damage_instance::add_damage(), Creature::add_effect(), add_msg(), bionic_id, Creature::check_dead_state(), Creature::deal_damage(), dice(), Creature::disp_name(), Character::disp_name(), DT_CUT, DT_ELECTRIC, DT_STAB, effect_blind, effect_downed, effect_stunned, units::from_kilojoule(), g, Character::get_power_level(), Character::has_active_bionic(), Creature::has_effect(), Character::has_trait(), Creature::has_weapon(), is_player(), m_bad, m_good, Character::mod_power_level(), Character::name, num_bp, Character::on_hit(), one_in(), rng(), Character::stability_roll(), trait_CF_HAIR, trait_DEFT, trait_PROF_SKATER, trait_QUILLS, trait_SPINES, trait_THORNS, Character::wearing_something_on(), and Character::worn_with_flag().
on_worn_item_transform()
void player::on_worn_item_transform (const item & old_it, const item & new_it)
Definition at line 622 of file player.cpp.
{
    morale->on_worn_item_transform( old_it, new_it );
}
References Character::morale.
Referenced by iuse_transform::use().
operator=() [1/2]
player & player::operator= (const player &) delete
operator=() [2/2]
player & player::operator= (player &&) default
practice()
void player::practice (const skill_id & id, int amount, int cap = 99, bool suppress_warning = false)
This handles giving xp for a skill.
Definition at line 2329 of file player.cpp.
{
    SkillLevel &level = get_skill_level_object( id );
    const Skill &skill = id.obj();
    std::string skill_name = skill.name();
    if( !level.can_train() && !in_sleep_state() ) {
        // If leveling is disabled, don't train, don't drain focus, don't print anything
        // Leaving as a skill method rather than global for possible future skill cap setting
        return;
    }
    const auto highest_skill = [&]() {
        std::pair<skill_id, int> result( skill_id::NULL_ID(), -1 );
        for( const auto &pair : *_skills ) {
            const SkillLevel &lobj = pair.second;
            if( lobj.level() > result.second ) {
                result = std::make_pair( pair.first, lobj.level() );
            }
        }
        return result.first;
    };
    const bool isSavant = has_trait( trait_SAVANT );
    const skill_id savantSkill = isSavant ? highest_skill() : skill_id::NULL_ID();
    amount = adjust_for_focus( amount );
    if( has_trait( trait_PACIFIST ) && skill.is_combat_skill() ) {
        if( !one_in( 3 ) ) {
            amount = 0;
        }
    }
    if( has_trait_flag( "PRED2" ) && skill.is_combat_skill() ) {
        if( one_in( 3 ) ) {
            amount *= 2;
        }
    }
    if( has_trait_flag( "PRED3" ) && skill.is_combat_skill() ) {
        amount *= 2;
    }
    if( has_trait_flag( "PRED4" ) && skill.is_combat_skill() ) {
        amount *= 3;
    }
    if( isSavant && id != savantSkill ) {
        amount /= 2;
    }
    if( amount > 0 && get_skill_level( id ) > cap ) { //blunt grinding cap implementation for crafting
        amount = 0;
        if( !suppress_warning ) {
            handle_skill_warning( id, false );
        }
    }
    if( amount > 0 && level.isTraining() ) {
        int oldLevel = get_skill_level( id );
        get_skill_level_object( id ).train( amount );
        int newLevel = get_skill_level( id );
        if( is_player() && newLevel > oldLevel ) {
            add_msg( m_good, _( "Your skill in %s has increased to %d!" ), skill_name, newLevel );
        }
        if( is_player() && newLevel > cap ) {
            //inform player immediately that the current recipe can't be used to train further
            add_msg( m_info, _( "You feel that %s tasks of this level are becoming trivial." ),
                     skill_name );
        }
        int chance_to_drop = focus_pool;
        focus_pool -= chance_to_drop / 100;
        // Apex Predators don't think about much other than killing.
        // They don't lose Focus when practicing combat skills.
        if( ( rng( 1, 100 ) <= ( chance_to_drop % 100 ) ) && ( !( has_trait_flag( "PRED4" ) &&
                skill.is_combat_skill() ) ) ) {
            focus_pool--;
        }
    }
    get_skill_level_object( id ).practice();
}
References _, Character::_skills, add_msg(), Character::adjust_for_focus(), SkillLevel::can_train(), Character::focus_pool, Character::get_skill_level(), Character::get_skill_level_object(), handle_skill_warning(), Character::has_trait(), Character::has_trait_flag(), Character::in_sleep_state(), Skill::is_combat_skill(), is_player(), SkillLevel::isTraining(), SkillLevel::level(), m_good, m_info, Skill::name(), string_id< Skill >::NULL_ID(), one_in(), SkillLevel::practice(), rng(), SkillLevel::train(), trait_PACIFIST, and trait_SAVANT.
Referenced by vehicle::act_on_map(), activity_handlers::butcher_finish(), butchery_drops_harvest(), talk_function::companion_skill_trainer(), crafting::complete_disassemble(), veh_interact::complete_vehicle(), craft_skill_gain(), salvage_actor::cut_up(), character_funcs::do_pause(), iuse::einktabletpc(), heal_actor::finish_using(), fire_gun(), activity_handlers::fish_do_turn(), iuse::fish_trap(), iexamine::fvat_full(), iuse::gun_repair(), hack_attempt(), computer_session::hack_attempt(), hackveh(), Character::install_bionics(), place_trap_actor::data::load(), activity_handlers::make_zlave_finish(), melee_train(), iuse::multicooker(), on_dodge(), Character::perform_special_attacks(), pick_plant(), vehicle::pldrive(), iexamine::practice_survival_while_foraging(), activity_handlers::pry_nails_finish(), activity_handlers::pulp_do_turn(), repair_item_actor::repair(), veh_utils::repair_part(), activity_handlers::robot_control_finish(), talk_trial::roll(), smash(), activity_handlers::start_fire_finish(), activity_handlers::study_spell_finish(), avatar_action::swim(), throw_item(), place_trap_actor::use(), and sew_advanced_actor::use().
query_yn() [1/3]
template<typename ... Args> bool Character::query_yn (const char *const msg, Args &&... args) const inline
It is supposed to hide the query_yn to simplify player vs.
npc code.
Definition at line 1467 of file character.h.
{
            return query_yn( string_format( msg, std::forward<Args>( args ) ... ) );
        }
query_yn() [2/3]
bool player::query_yn (const std::string & mes) const override virtual
Implements Character.
Definition at line 2630 of file player.cpp.
{
    return ::query_yn( mes );
}
References query_yn().
Referenced by iuse::blech(), iuse::blech_because_unclean(), can_continue_craft(), check_eligible_containers_for_crafting(), avatar::create(), drink_from_hands(), iuse::pack_cbm(), iuse::poison(), iexamine::reload_furniture(), iuse::sewage(), sort_armor(), takeoff(), iuse::tazer(), toolmod_add(), mutagen_actor::use(), and avatar::wield().
query_yn() [3/3]
virtual bool Character::query_yn (const std::string & msg) const virtual
Implements Character.
reassign_item()
void player::reassign_item (item & it, int invlet)
Reassign letter.
Definition at line 2021 of file player.cpp.
{
    bool remove_old = true;
    if( invlet ) {
        item *prev = invlet_to_item( invlet );
        if( prev != nullptr ) {
            remove_old = it.typeId() != prev->typeId();
            inv.reassign_item( *prev, it.invlet, remove_old );
        }
    }
    if( !invlet || inv_chars.valid( invlet ) ) {
        const auto iter = inv.assigned_invlet.find( it.invlet );
        bool found = iter != inv.assigned_invlet.end();
        if( found ) {
            inv.assigned_invlet.erase( iter );
        }
        if( invlet && ( !found || it.invlet != invlet ) ) {
            inv.assigned_invlet[invlet] = it.typeId();
        }
        inv.reassign_item( it, invlet, remove_old );
    }
}
References inventory::assigned_invlet, Character::inv, inv_chars, item::invlet, Character::invlet_to_item(), inventory::reassign_item(), item::typeId(), and invlet_wrapper::valid().
Referenced by game_menus::inv::reassign_letter().
recraft()
void player::recraft (const tripoint & loc = tripoint_zero)
Definition at line 351 of file crafting.cpp.
{
    if( lastrecipe.str().empty() ) {
        popup( _( "Craft something first" ) );
    } else if( making_would_work( lastrecipe, last_batch ) ) {
        last_craft->execute( loc );
    }
}
References _, last_batch, last_craft, lastrecipe, making_would_work(), popup(), and string_id< T >::str().
Referenced by game::handle_action().
reduce_charges() [1/2]
item player::reduce_charges (int position, int quantity)
Remove charges from a specific item (given by its item position).
The item must exist and it must be counted by charges.
Parameters
position Item position of the item.
quantity The number of charges to remove, must not be larger than the current charges of the item.
Returns
An item that contains the removed charges, it's effectively a copy of the item with the proper charges.
Definition at line 627 of file player.cpp.
{
    item &it = i_at( position );
    if( it.is_null() ) {
        debugmsg( "invalid item position %d for reduce_charges", position );
        return item();
    }
    if( it.charges <= quantity ) {
        return i_rem( position );
    }
    it.mod_charges( -quantity );
    item tmp( it );
    tmp.charges = quantity;
    return tmp;
}
References item::charges, debugmsg, Character::i_at(), Character::i_rem(), item::is_null(), item::mod_charges(), and Character::position.
Referenced by pickup::obtain_and_tokenize_items().
reduce_charges() [2/2]
item player::reduce_charges (item * it, int quantity)
Remove charges from a specific item (given by a pointer to it).
Otherwise identical to reduce_charges(int,int)
Parameters
it A pointer to the item, it must exist.
quantity How many charges to remove
Definition at line 643 of file player.cpp.
{
    if( !has_item( *it ) ) {
        debugmsg( "invalid item (name %s) for reduce_charges", it->tname() );
        return item();
    }
    if( it->charges <= quantity ) {
        return i_rem( it );
    }
    it->mod_charges( -quantity );
    item result( *it );
    result.charges = quantity;
    return result;
}
References item::charges, debugmsg, visitable< Character >::has_item(), Character::i_rem(), item::mod_charges(), and item::tname().
select_ammo() [1/2]
item::reload_option player::select_ammo (const item & base, bool prompt = false, bool include_empty_mags = true, bool include_potential = false) const
Select suitable ammo with which to reload the item.
Parameters
base Item to select ammo for
prompt Force display of the menu even if only one choice
include_empty_mags Allow selection of empty magazines
include_potential Include ammo that can potentially be used, but not right now
Definition at line 1175 of file player.cpp.
{
    std::vector<item::reload_option> ammo_list;
    const bool ammo_match_found = list_ammo( base, ammo_list, include_empty_mags, include_potential );
    if( ammo_list.empty() ) {
        if( !is_npc() ) {
            if( !base.is_magazine() && !base.magazine_integral() && !base.magazine_current() ) {
                add_msg_if_player( m_info, _( "You need a compatible magazine to reload the %s!" ),
                                   base.tname() );
            } else if( ammo_match_found ) {
                add_msg_if_player( m_info, _( "Nothing to reload!" ) );
            } else {
                std::string name;
                if( base.ammo_data() ) {
                    name = base.ammo_data()->nname( 1 );
                } else if( base.is_watertight_container() ) {
                    name = base.is_container_empty() ? "liquid" : base.contents.front().tname();
                } else {
                    name = enumerate_as_string( base.ammo_types().begin(),
                    base.ammo_types().end(), []( const ammotype & at ) {
                        return at->name();
                    }, enumeration_conjunction::none );
                }
                add_msg_if_player( m_info, _( "You don't have any %s to reload your %s!" ),
                                   name, base.tname() );
            }
        }
        return item::reload_option();
    }
    // sort in order of move cost (ascending), then remaining ammo (descending) with empty magazines always last
    std::stable_sort( ammo_list.begin(), ammo_list.end(), []( const item::reload_option & lhs,
    const item::reload_option & rhs ) {
        return lhs.ammo->ammo_remaining() > rhs.ammo->ammo_remaining();
    } );
    std::stable_sort( ammo_list.begin(), ammo_list.end(), []( const item::reload_option & lhs,
    const item::reload_option & rhs ) {
        return lhs.moves() < rhs.moves();
    } );
    std::stable_sort( ammo_list.begin(), ammo_list.end(), []( const item::reload_option & lhs,
    const item::reload_option & rhs ) {
        return ( lhs.ammo->ammo_remaining() != 0 ) > ( rhs.ammo->ammo_remaining() != 0 );
    } );
    if( is_npc() ) {
        return ammo_list[ 0 ];
    }
    if( !prompt && ammo_list.size() == 1 ) {
        // unconditionally suppress the prompt if there's only one option
        return ammo_list[ 0 ];
    }
    return select_ammo( base, std::move( ammo_list ) );
}
References _, add_msg_if_player(), item::ammo_data(), item::ammo_types(), item::contents, enumerate_as_string(), item_contents::front(), item::is_container_empty(), item::is_magazine(), is_npc(), item::is_watertight_container(), list_ammo(), m_info, item::magazine_current(), item::magazine_integral(), avatar_action::move(), Character::name, itype::nname(), none, pickup::prompt, select_ammo(), and item::tname().
Referenced by npc::do_reload(), favorite_ammo_or_select(), npc::find_reloadable(), npc::find_usable_ammo(), vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), ranged::prompt_select_default_ammo_for(), bandolier_actor::reload(), select_ammo(), and ammobelt_actor::use().
select_ammo() [2/2]
item::reload_option player::select_ammo (const item & base, std::vector< item::reload_option > opts) const
Select ammo from the provided options.
Definition at line 899 of file player.cpp.
{
    if( opts.empty() ) {
        add_msg_if_player( m_info, _( "Never mind." ) );
        return item::reload_option();
    }
    uilist menu;
    menu.text = string_format( base.is_watertight_container() ? _( "Refill %s" ) :
                               base.has_flag( "RELOAD_AND_SHOOT" ) ? _( "Select ammo for %s" ) : _( "Reload %s" ),
                               base.tname() );
    // Construct item names
    std::vector<std::string> names;
    std::transform( opts.begin(), opts.end(),
    std::back_inserter( names ), [&]( const item::reload_option & e ) {
        if( e.ammo->is_magazine() && e.ammo->ammo_data() ) {
            if( e.ammo->ammo_current() == itype_battery ) {
                // This battery ammo is not a real object that can be recovered but pseudo-object that represents charge
                //~ battery storage (charges)
                return string_format( pgettext( "magazine", "%1$s (%2$d)" ), e.ammo->type_name(),
                                      e.ammo->ammo_remaining() );
            } else {
                //~ magazine with ammo (count)
                return string_format( pgettext( "magazine", "%1$s with %2$s (%3$d)" ), e.ammo->type_name(),
                                      e.ammo->ammo_data()->nname( e.ammo->ammo_remaining() ), e.ammo->ammo_remaining() );
            }
        } else if( e.ammo->is_watertight_container() ||
                   ( e.ammo->is_ammo_container() && is_worn( *e.ammo ) ) ) {
            // worn ammo containers should be named by their contents with their location also updated below
            return e.ammo->contents.front().display_name();
        } else {
            const_cast<item_location &>( ammo_location ).make_dirty();
            return ( ammo_location && ammo_location == e.ammo ? "* " : "" ) + e.ammo->display_name();
        }
    } );
    // Get location descriptions
    std::vector<std::string> where;
    std::transform( opts.begin(), opts.end(),
    std::back_inserter( where ), [this]( const item::reload_option & e ) {
        bool is_ammo_container = e.ammo->is_ammo_container();
        if( is_ammo_container || e.ammo->is_container() ) {
            if( is_ammo_container && is_worn( *e.ammo ) ) {
                return e.ammo->type_name();
            }
            return string_format( _( "%s, %s" ), e.ammo->type_name(), e.ammo.describe( &g->u ) );
        }
        return e.ammo.describe( &g->u );
    } );
    // Pads elements to match longest member and return length
    auto pad = []( std::vector<std::string> &vec, int n, int t ) -> int {
        for( const auto &e : vec )
        {
            n = std::max( n, utf8_width( e, true ) + t );
        }
        for( auto &e : vec )
        {
            e += std::string( n - utf8_width( e, true ), ' ' );
        }
        return n;
    };
    // Pad the first column including 4 trailing spaces
    int w = pad( names, utf8_width( menu.text, true ), 6 );
    menu.text.insert( 0, 2, ' ' ); // add space for UI hotkeys
    menu.text += std::string( w + 2 - utf8_width( menu.text, true ), ' ' );
    // Pad the location similarly (excludes leading "| " and trailing " ")
    w = pad( where, utf8_width( _( "| Location " ) ) - 3, 6 );
    menu.text += _( "| Location " );
    menu.text += std::string( w + 3 - utf8_width( _( "| Location " ) ), ' ' );
    menu.text += _( "| Amount  " );
    menu.text += _( "| Moves   " );
    // We only show ammo statistics for guns and magazines
    if( base.is_gun() || base.is_magazine() ) {
        menu.text += _( "| Damage   | Pierce   " );
    }
    auto draw_row = [&]( int idx ) {
        const auto &sel = opts[ idx ];
        std::string row = string_format( "%s| %s |", names[ idx ], where[ idx ] );
        row += string_format( ( sel.ammo->is_ammo() ||
                                sel.ammo->is_ammo_container() ) ? " %-7d |" : "         |", sel.qty() );
        row += string_format( " %-7d ", sel.moves() );
        if( base.is_gun() || base.is_magazine() ) {
            const itype *ammo = sel.ammo->is_ammo_container() ? sel.ammo->contents.front().ammo_data() :
                                sel.ammo->ammo_data();
            if( ammo ) {
                const damage_instance &dam = ammo->ammo->damage;
                const damage_unit &du = dam.damage_units.front();
                if( du.damage_multiplier != 1.0f ) {
                    float dam_amt = du.amount;
                    row += string_format( "| %-3d*%3d%% ", static_cast<int>( dam_amt ),
                                          clamp( static_cast<int>( du.damage_multiplier * 100 ), 0, 999 ) );
                } else {
                    float dam_amt = dam.total_damage();
                    row += string_format( "| %-8d ", static_cast<int>( dam_amt ) );
                }
                if( du.res_mult != 1.0f ) {
                    row += string_format( "| %-3d/%3d%%",
                                          static_cast<int>( du.res_pen ), static_cast<int>( 100 * du.res_mult ) );
                } else {
                    row += string_format( "| %-8d", static_cast<int>( du.res_pen ) );
                }
            } else {
                row += "|          |          ";
            }
        }
        return row;
    };
    const ammotype base_ammotype( base.ammo_default().str() );
    itype_id last = uistate.lastreload[ base_ammotype ];
    // We keep the last key so that pressing the key twice (for example, r-r for reload)
    // will always pick the first option on the list.
    int last_key = inp_mngr.get_previously_pressed_key();
    bool last_key_bound = false;
    // This is the entry that has out default
    int default_to = 0;
    // If last_key is RETURN, don't use that to override hotkey
    if( last_key == '\n' ) {
        last_key_bound = true;
        default_to = -1;
    }
    for( auto i = 0; i < static_cast<int>( opts.size() ); ++i ) {
        const item &ammo = opts[ i ].ammo->is_ammo_container() ? opts[ i ].ammo->contents.front() :
                           *opts[ i ].ammo;
        char hotkey = -1;
        if( has_item( ammo ) ) {
            // if ammo in player possession and either it or any container has a valid invlet use this
            if( ammo.invlet ) {
                hotkey = ammo.invlet;
            } else {
                for( const auto obj : parents( ammo ) ) {
                    if( obj->invlet ) {
                        hotkey = obj->invlet;
                        break;
                    }
                }
            }
        }
        if( last == ammo.typeId() ) {
            if( !last_key_bound && hotkey == -1 ) {
                // If this is the first occurrence of the most recently used type of ammo and the hotkey
                // was not already set above then set it to the keypress that opened this prompt
                hotkey = last_key;
                last_key_bound = true;
            }
            if( !last_key_bound ) {
                // Pressing the last key defaults to the first entry of compatible type
                default_to = i;
                last_key_bound = true;
            }
        }
        if( hotkey == last_key ) {
            last_key_bound = true;
            // Prevent the default from being used: key is bound to something already
            default_to = -1;
        }
        menu.addentry( i, true, hotkey, draw_row( i ) );
    }
    struct reload_callback : public uilist_callback {
        public:
            std::vector<item::reload_option> &opts;
            const std::function<std::string( int )> draw_row;
            int last_key;
            const int default_to;
            const bool can_partial_reload;
            reload_callback( std::vector<item::reload_option> &_opts,
                             std::function<std::string( int )> _draw_row,
                             int _last_key, int _default_to, bool _can_partial_reload ) :
                opts( _opts ), draw_row( _draw_row ),
                last_key( _last_key ), default_to( _default_to ),
                can_partial_reload( _can_partial_reload )
            {}
            bool key( const input_context &, const input_event &event, int idx, uilist *menu ) override {
                auto cur_key = event.get_first_input();
                if( default_to != -1 && cur_key == last_key ) {
                    // Select the first entry on the list
                    menu->ret = default_to;
                    return true;
                }
                if( idx < 0 || idx >= static_cast<int>( opts.size() ) ) {
                    return false;
                }
                auto &sel = opts[ idx ];
                switch( cur_key ) {
                    case KEY_LEFT:
                        if( can_partial_reload ) {
                            sel.qty( sel.qty() - 1 );
                            menu->entries[ idx ].txt = draw_row( idx );
                        }
                        return true;
                    case KEY_RIGHT:
                        if( can_partial_reload ) {
                            sel.qty( sel.qty() + 1 );
                            menu->entries[ idx ].txt = draw_row( idx );
                        }
                        return true;
                }
                return false;
            }
    } cb( opts, draw_row, last_key, default_to, !base.has_flag( "RELOAD_ONE" ) );
    menu.callback = &cb;
    menu.query();
    if( menu.ret < 0 || static_cast<size_t>( menu.ret ) >= opts.size() ) {
        add_msg_if_player( m_info, _( "Never mind." ) );
        return item::reload_option();
    }
    const item_location &sel = opts[ menu.ret ].ammo;
    uistate.lastreload[ ammotype( base.ammo_default().str() ) ] = sel->is_ammo_container() ?
            sel->contents.front().typeId() :
            sel->typeId();
    return opts[ menu.ret ];
}
References _, add_msg_if_player(), item::reload_option::ammo, item::has_flag(), item::is_ammo_container(), item::is_watertight_container(), Character::is_worn(), m_info, Name::names, string_format(), uilist::text, item::tname(), and iexamine::transform().
select_item_component()
comp_selection< item_comp > player::select_item_component (const std::vector< item_comp > & components, int batch, inventory & map_inv, bool can_cancel = false, const std::function< bool(const item &)> & filter = return_true<item>, bool player_inv = true)
Definition at line 1308 of file crafting.cpp.
{
    std::vector<item_comp> player_has;
    std::vector<item_comp> map_has;
    std::vector<item_comp> mixed;
    comp_selection<item_comp> selected;
    for( const auto &component : components ) {
        itype_id type = component.type;
        int count = ( component.count > 0 ) ? component.count * batch : std::abs( component.count );
        if( item::count_by_charges( type ) && count > 0 ) {
            int map_charges = map_inv.charges_of( type, INT_MAX, filter );
            // If map has infinite charges, just use them
            if( map_charges == item::INFINITE_CHARGES ) {
                selected.use_from = use_from_map;
                selected.comp = component;
                return selected;
            }
            if( player_inv ) {
                int player_charges = charges_of( type, INT_MAX, filter );
                bool found = false;
                if( player_charges >= count ) {
                    player_has.push_back( component );
                    found = true;
                }
                if( map_charges >= count ) {
                    map_has.push_back( component );
                    found = true;
                }
                if( !found && player_charges + map_charges >= count ) {
                    mixed.push_back( component );
                }
            } else {
                if( map_charges >= count ) {
                    map_has.push_back( component );
                }
            }
        } else { // Counting by units, not charges
            // Can't use pseudo items as components
            if( player_inv ) {
                bool found = false;
                if( has_amount( type, count, false, filter ) ) {
                    player_has.push_back( component );
                    found = true;
                }
                if( map_inv.has_components( type, count, filter ) ) {
                    map_has.push_back( component );
                    found = true;
                }
                if( !found &&
                    amount_of( type, false, std::numeric_limits<int>::max(), filter ) +
                    map_inv.amount_of( type, false, std::numeric_limits<int>::max(), filter ) >= count ) {
                    mixed.push_back( component );
                }
            } else {
                if( map_inv.has_components( type, count, filter ) ) {
                    map_has.push_back( component );
                }
            }
        }
    }
    /* select 1 component to use */
    if( player_has.size() + map_has.size() + mixed.size() == 1 ) { // Only 1 choice
        if( player_has.size() == 1 ) {
            selected.use_from = use_from_player;
            selected.comp = player_has[0];
        } else if( map_has.size() == 1 ) {
            selected.use_from = use_from_map;
            selected.comp = map_has[0];
        } else {
            selected.use_from = use_from_both;
            selected.comp = mixed[0];
        }
    } else if( is_npc() ) {
        if( !player_has.empty() ) {
            selected.use_from = use_from_player;
            selected.comp = player_has[0];
        } else if( !map_has.empty() ) {
            selected.use_from = use_from_map;
            selected.comp = map_has[0];
        } else {
            debugmsg( "Attempted a recipe with no available components!" );
            selected.use_from = cancel;
            return selected;
        }
    } else { // Let the player pick which component they want to use
        uilist cmenu;
        // Populate options with the names of the items
        for( auto &map_ha : map_has ) { // Index 0-(map_has.size()-1)
            std::string tmpStr = string_format( _( "%s (%d/%d nearby)" ),
                                                item::nname( map_ha.type ),
                                                ( map_ha.count * batch ),
                                                item::count_by_charges( map_ha.type ) ?
                                                map_inv.charges_of( map_ha.type, INT_MAX, filter ) :
                                                map_inv.amount_of( map_ha.type, false, INT_MAX, filter ) );
            cmenu.addentry( tmpStr );
        }
        for( auto &player_ha : player_has ) { // Index map_has.size()-(map_has.size()+player_has.size()-1)
            std::string tmpStr = string_format( _( "%s (%d/%d on person)" ),
                                                item::nname( player_ha.type ),
                                                ( player_ha.count * batch ),
                                                item::count_by_charges( player_ha.type ) ?
                                                charges_of( player_ha.type, INT_MAX, filter ) :
                                                amount_of( player_ha.type, false, INT_MAX, filter ) );
            cmenu.addentry( tmpStr );
        }
        for( auto &component : mixed ) {
            // Index player_has.size()-(map_has.size()+player_has.size()+mixed.size()-1)
            int available = item::count_by_charges( component.type ) ?
                            map_inv.charges_of( component.type, INT_MAX, filter ) +
                            charges_of( component.type, INT_MAX, filter ) :
                            map_inv.amount_of( component.type, false, INT_MAX, filter ) +
                            amount_of( component.type, false, INT_MAX, filter );
            std::string tmpStr = string_format( _( "%s (%d/%d nearby & on person)" ),
                                                item::nname( component.type ),
                                                component.count * batch,
                                                available );
            cmenu.addentry( tmpStr );
        }
        // Unlike with tools, it's a bad thing if there aren't any components available
        if( cmenu.entries.empty() ) {
            if( player_inv ) {
                if( has_trait( trait_DEBUG_HS ) ) {
                    selected.use_from = use_from_player;
                    return selected;
                }
            }
            debugmsg( "Attempted a recipe with no available components!" );
            selected.use_from = cancel;
            return selected;
        }
        cmenu.allow_cancel = can_cancel;
        // Get the selection via a menu popup
        cmenu.title = _( "Use which component?" );
        cmenu.query();
        if( cmenu.ret < 0 ||
            static_cast<size_t>( cmenu.ret ) >= map_has.size() + player_has.size() + mixed.size() ) {
            selected.use_from = cancel;
            return selected;
        }
        size_t uselection = static_cast<size_t>( cmenu.ret );
        if( uselection < map_has.size() ) {
            selected.use_from = usage::use_from_map;
            selected.comp = map_has[uselection];
        } else if( uselection < map_has.size() + player_has.size() ) {
            uselection -= map_has.size();
            selected.use_from = usage::use_from_player;
            selected.comp = player_has[uselection];
        } else {
            uselection -= map_has.size() + player_has.size();
            selected.use_from = usage::use_from_both;
            selected.comp = mixed[uselection];
        }
    }
    return selected;
}
References _, uilist::addentry(), uilist::allow_cancel, visitable< Character >::amount_of(), visitable< T >::amount_of(), available, cancel, visitable< T >::charges_of(), visitable< Character >::charges_of(), comp_selection< CompType >::comp, component, detail::count(), component::count, item::count_by_charges(), debugmsg, uilist::entries, visitable< Character >::has_amount(), inventory::has_components(), Character::has_trait(), item::INFINITE_CHARGES, is_npc(), item::nname(), uilist::query(), uilist::ret, string_format(), uilist::title, trait_DEBUG_HS, type, component::type, comp_selection< CompType >::use_from, use_from_both, use_from_map, and use_from_player.
Referenced by can_continue_craft(), consume_items(), craft_command::execute(), mill_load_food(), veh_utils::repair_part(), and smoker_load_food().
select_requirements()
const requirement_data * player::select_requirements (const std::vector< const requirement_data * > & alternatives, int batch, const inventory & inv, const std::function< bool(const item &)> & filter) const
Definition at line 1275 of file crafting.cpp.
{
    assert( !alternatives.empty() );
    if( alternatives.size() == 1 || !is_avatar() ) {
        return alternatives.front();
    }
    uilist menu;
    for( const requirement_data *req : alternatives ) {
        // Write with a large width and then just re-join the lines, because
        // uilist does its own wrapping and we want to rely on that.
        std::vector<std::string> component_lines =
            req->get_folded_components_list( TERMX - 4, c_light_gray, inv, filter, batch, "",
                                             requirement_display_flags::no_unavailable );
        menu.addentry_desc( "", join( component_lines, "\n" ) );
    }
    menu.allow_cancel = true;
    menu.desc_enabled = true;
    menu.title = _( "Use which selection of components?" );
    menu.query();
    if( menu.ret < 0 || static_cast<size_t>( menu.ret ) >= alternatives.size() ) {
        return nullptr;
    }
    return alternatives[menu.ret];
}
References _, uilist::addentry_desc(), uilist::allow_cancel, c_light_gray, uilist::desc_enabled, Character::inv, Creature::is_avatar(), join(), no_unavailable, uilist::query(), uilist::ret, TERMX, and uilist::title.
Referenced by deduped_requirement_data::select_alternative().
serialize()
virtual void player::serialize (JsonOut & jsout) const pure virtual
Implemented in avatar, and npc.
sort_armor()
void player::sort_armor ()
Draws the UI and handles player input for the armor re-ordering window.
Definition at line 439 of file armor_layers.cpp.
{
    /* Define required height of the right pane:
    * + 3 - horizontal lines;
    * + 1 - caption line;
    * + 2 - innermost/outermost string lines;
    * + num_bp - sub-categories (torso, head, eyes, etc.);
    * + 1 - gap;
    * number of lines required for displaying all items is calculated dynamically,
    * because some items can have multiple entries (i.e. cover a few parts of body).
    */
    int req_right_h = 3 + 1 + 2 + num_bp + 1;
    for( const body_part cover : all_body_parts ) {
        for( const item &elem : worn ) {
            if( elem.covers( cover ) ) {
                req_right_h++;
            }
        }
    }
    /* Define required height of the mid pane:
    * + 3 - horizontal lines;
    * + 1 - caption line;
    * + 8 - general properties
    * + 13 - ASSUMPTION: max possible number of flags @ item
    * + num_bp+1 - warmth & enc block
    */
    const int req_mid_h = 3 + 1 + 8 + 13 + num_bp + 1;
    int win_h = 0;
    int win_w = 0;
    point win;
    int cont_h   = 0;
    int left_w   = 0;
    int right_w  = 0;
    int middle_w = 0;
    int tabindex = num_bp;
    const int tabcount = num_bp + 1;
    int leftListIndex  = 0;
    int leftListOffset = 0;
    int selected       = -1;
    int rightListOffset = 0;
    int leftListLines = 0;
    int rightListLines = 0;
    std::vector<std::list<item>::iterator> tmp_worn;
    std::array<std::string, 13> armor_cat = {{
            _( "Torso" ), _( "Head" ), _( "Eyes" ), _( "Mouth" ), _( "L. Arm" ), _( "R. Arm" ),
            _( "L. Hand" ), _( "R. Hand" ), _( "L. Leg" ), _( "R. Leg" ), _( "L. Foot" ),
            _( "R. Foot" ), _( "All" )
        }
    };
    // Layout window
    catacurses::window w_sort_armor;
    // Subwindows (between lines)
    catacurses::window w_sort_cat;
    catacurses::window w_sort_left;
    catacurses::window w_sort_middle;
    catacurses::window w_sort_right;
    catacurses::window w_encumb;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        win_h = std::min( TERMY, std::max( { FULL_SCREEN_HEIGHT, req_right_h, req_mid_h } ) );
        win_w = FULL_SCREEN_WIDTH + ( TERMX - FULL_SCREEN_WIDTH ) * 3 / 4;
        win.x = TERMX / 2 - win_w / 2;
        win.y = TERMY / 2 - win_h / 2;
        cont_h = win_h - 4;
        left_w = ( win_w - 4 ) / 3;
        right_w = left_w;
        middle_w = ( win_w - 4 ) - left_w - right_w;
        leftListLines = rightListLines = cont_h - 2;
        w_sort_armor = catacurses::newwin( win_h, win_w, win );
        w_sort_cat = catacurses::newwin( 1, win_w - 4, win + point( 2, 1 ) );
        w_sort_left = catacurses::newwin( cont_h, left_w, win + point( 1, 3 ) );
        w_sort_middle = catacurses::newwin( cont_h - num_bp - 1, middle_w,
                                            win + point( 2 + left_w, 3 ) );
        w_sort_right = catacurses::newwin( cont_h, right_w,
                                           win + point( 3 + left_w + middle_w, 3 ) );
        w_encumb = catacurses::newwin( num_bp + 1, middle_w,
                                       win + point( 2 + left_w, -1 + 3 + cont_h - num_bp ) );
        ui.position_from_window( w_sort_armor );
    } );
    ui.mark_resize();
    input_context ctxt( "SORT_ARMOR" );
    ctxt.register_cardinal();
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "PREV_TAB" );
    ctxt.register_action( "NEXT_TAB" );
    ctxt.register_action( "MOVE_ARMOR" );
    ctxt.register_action( "CHANGE_SIDE" );
    ctxt.register_action( "ASSIGN_INVLETS" );
    ctxt.register_action( "SORT_ARMOR" );
    ctxt.register_action( "EQUIP_ARMOR" );
    ctxt.register_action( "EQUIP_ARMOR_HERE" );
    ctxt.register_action( "REMOVE_ARMOR" );
    ctxt.register_action( "USAGE_HELP" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    auto do_return_entry = []() {
        g->u.assign_activity( ACT_ARMOR_LAYERS, 0 );
        g->u.activity.auto_resume = true;
        g->u.activity.moves_left = INT_MAX;
    };
    int leftListSize = 0;
    int rightListSize = 0;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        draw_grid( w_sort_armor, left_w, middle_w );
        werase( w_sort_cat );
        werase( w_sort_left );
        werase( w_sort_middle );
        werase( w_sort_right );
        werase( w_encumb );
        // top bar
        wprintz( w_sort_cat, c_white, _( "Sort Armor" ) );
        wprintz( w_sort_cat, c_yellow, "  << %s >>", armor_cat[tabindex] );
        right_print( w_sort_cat, 0, 0, c_white, string_format(
                         _( "Press [<color_yellow>%s</color>] for help.  "
                            "Press [<color_yellow>%s</color>] to change keybindings." ),
                         ctxt.get_desc( "USAGE_HELP" ),
                         ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
        if( leftListLines > leftListSize ) {
            leftListOffset = 0;
        } else if( leftListOffset + leftListLines > leftListSize ) {
            leftListOffset = leftListSize - leftListLines;
        }
        if( leftListOffset > leftListIndex ) {
            leftListOffset = leftListIndex;
        } else if( leftListOffset + leftListLines <= leftListIndex ) {
            leftListOffset = leftListIndex + 1 - leftListLines;
        }
        // Left header
        mvwprintz( w_sort_left, point_zero, c_light_gray, _( "(Innermost)" ) );
        right_print( w_sort_left, 0, 0, c_light_gray, string_format( _( "Storage (%s)" ),
                     volume_units_abbr() ) );
        // Left list
        const int max_drawindex = std::min( leftListSize - leftListOffset, leftListLines );
        for( int drawindex = 0; drawindex < max_drawindex; drawindex++ ) {
            int itemindex = leftListOffset + drawindex;
            if( itemindex == leftListIndex ) {
                mvwprintz( w_sort_left, point( 0, drawindex + 1 ), c_yellow, ">>" );
            }
            std::string worn_armor_name = tmp_worn[itemindex]->tname();
            item_penalties const penalties =
                get_item_penalties( tmp_worn[itemindex], *this, tabindex );
            const int offset_x = ( itemindex == selected ) ? 3 : 2;
            trim_and_print( w_sort_left, point( offset_x, drawindex + 1 ), left_w - offset_x - 3,
                            penalties.color_for_stacking_badness(), worn_armor_name );
            right_print( w_sort_left, drawindex + 1, 0, c_light_gray,
                         format_volume( tmp_worn[itemindex]->get_storage() ) );
        }
        // Left footer
        mvwprintz( w_sort_left, point( 0, cont_h - 1 ), c_light_gray, _( "(Outermost)" ) );
        if( leftListOffset + leftListLines < leftListSize ) {
            // TODO: replace it by right_print()
            mvwprintz( w_sort_left, point( left_w - utf8_width( _( "<more>" ) ), cont_h - 1 ),
                       c_light_blue, _( "<more>" ) );
        }
        if( leftListSize == 0 ) {
            // TODO: replace it by right_print()
            mvwprintz( w_sort_left, point( left_w - utf8_width( _( "<empty>" ) ), cont_h - 1 ),
                       c_light_blue, _( "<empty>" ) );
        }
        // Items stats
        if( leftListSize > 0 ) {
            draw_mid_pane( w_sort_middle, tmp_worn[leftListIndex], *this, tabindex );
        } else {
            // NOLINTNEXTLINE(cata-use-named-point-constants)
            fold_and_print( w_sort_middle, point( 1, 0 ), middle_w - 1, c_white,
                            _( "Nothing to see here!" ) );
        }
        mvwprintz( w_encumb, point_east, c_white, _( "Encumbrance and Warmth" ) );
        character_display::print_encumbrance( w_encumb, *this, -1,
                                              ( leftListSize > 0 ) ? &*tmp_worn[leftListIndex] : nullptr );
        // Right header
        mvwprintz( w_sort_right, point_zero, c_light_gray, _( "(Innermost)" ) );
        right_print( w_sort_right, 0, 0, c_light_gray, _( "Encumbrance" ) );
        const auto &combine_bp = [this]( const int cover ) -> bool {
            return cover > 3 && cover % 2 == 0 &&
            items_cover_bp( *this, cover ) == items_cover_bp( *this, cover + 1 );
        };
        // Right list
        rightListSize = 0;
        for( int cover = 0; cover < num_bp; cover++ ) {
            rightListSize += items_cover_bp( *this, cover ).size() + 1;
            if( combine_bp( cover ) ) {
                cover++;
            }
        }
        if( rightListLines > rightListSize ) {
            rightListOffset = 0;
        } else if( rightListOffset + rightListLines > rightListSize ) {
            rightListOffset = rightListSize - rightListLines;
        }
        for( int cover = 0, pos = 1, curr = 0; cover < num_bp; cover++ ) {
            bool combined = false;
            if( combine_bp( cover ) ) {
                combined = true;
            }
            if( curr >= rightListOffset && pos <= rightListLines ) {
                mvwprintz( w_sort_right, point( 1, pos ), ( cover == tabindex ? c_yellow : c_white ),
                           "%s:", body_part_name_as_heading( all_body_parts[cover], combined ? 2 : 1 ) );
                pos++;
            }
            curr++;
            for( layering_item_info &elem : items_cover_bp( *this, cover ) ) {
                if( curr >= rightListOffset && pos <= rightListLines ) {
                    nc_color color = elem.penalties.color_for_stacking_badness();
                    trim_and_print( w_sort_right, point( 2, pos ), right_w - 5, color,
                                    elem.name );
                    char plus = elem.penalties.badness() > 0 ? '+' : ' ';
                    mvwprintz( w_sort_right, point( right_w - 4, pos ), c_light_gray, "%3d%c",
                               elem.encumber, plus );
                    pos++;
                }
                curr++;
            }
            if( combined ) {
                cover++;
            }
        }
        // Right footer
        mvwprintz( w_sort_right, point( 0, cont_h - 1 ), c_light_gray, _( "(Outermost)" ) );
        if( rightListOffset + rightListLines < rightListSize ) {
            // TODO: replace it by right_print()
            mvwprintz( w_sort_right, point( right_w - utf8_width( _( "<more>" ) ), cont_h - 1 ), c_light_blue,
                       _( "<more>" ) );
        }
        // F5
        wnoutrefresh( w_sort_cat );
        wnoutrefresh( w_sort_left );
        wnoutrefresh( w_sort_middle );
        wnoutrefresh( w_sort_right );
        wnoutrefresh( w_encumb );
    } );
    bool exit = false;
    while( !exit ) {
        if( is_player() ) {
            // Totally hoisted this from advanced_inv
            if( g->u.moves < 0 ) {
                do_return_entry();
                return;
            }
        } else {
            // Player is sorting NPC's armor here
            if( rl_dist( g->u.pos(), pos() ) > 1 ) {
                add_msg_if_npc( m_bad, _( "%s is too far to sort armor." ), name );
                return;
            }
            if( attitude_to( g->u ) != Creature::A_FRIENDLY ) {
                add_msg_if_npc( m_bad, _( "%s is not friendly!" ), name );
                return;
            }
        }
        // Create ptr list of items to display
        tmp_worn.clear();
        if( tabindex == num_bp ) {
            // All
            for( auto it = worn.begin(); it != worn.end(); ++it ) {
                tmp_worn.push_back( it );
            }
        } else {
            // bp_*
            body_part bp = static_cast<body_part>( tabindex );
            for( auto it = worn.begin(); it != worn.end(); ++it ) {
                if( it->covers( bp ) ) {
                    tmp_worn.push_back( it );
                }
            }
        }
        leftListSize = tmp_worn.size();
        // Ensure leftListIndex is in bounds
        int new_index_upper_bound = std::max( 0, leftListSize - 1 );
        leftListIndex = std::min( leftListIndex, new_index_upper_bound );
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( is_npc() && action == "ASSIGN_INVLETS" ) {
            // It doesn't make sense to assign invlets to NPC items
            continue;
        }
        // Helper function for moving items in the list
        auto shift_selected_item = [&]() {
            if( selected >= 0 ) {
                std::list<item>::iterator to = tmp_worn[leftListIndex];
                if( leftListIndex > selected ) {
                    ++to;
                }
                worn.splice( to, worn, tmp_worn[selected] );
                selected = leftListIndex;
                reset_encumbrance();
            }
        };
        if( action == "UP" && leftListSize > 0 ) {
            if( leftListIndex > 0 ) {
                leftListIndex--;
                if( leftListIndex < leftListOffset ) {
                    leftListOffset = leftListIndex;
                }
            } else {
                leftListIndex = leftListSize - 1;
                if( leftListLines >= leftListSize ) {
                    leftListOffset = 0;
                } else {
                    leftListOffset = leftListSize - leftListLines;
                }
            }
            shift_selected_item();
        } else if( action == "DOWN" && leftListSize > 0 ) {
            if( leftListIndex + 1 < leftListSize ) {
                leftListIndex++;
                if( leftListIndex >= leftListOffset + leftListLines ) {
                    leftListOffset = leftListIndex + 1 - leftListLines;
                }
            } else {
                leftListIndex = 0;
                leftListOffset = 0;
            }
            shift_selected_item();
        } else if( action == "LEFT" ) {
            tabindex--;
            if( tabindex < 0 ) {
                tabindex = tabcount - 1;
            }
            leftListIndex = leftListOffset = 0;
            selected = -1;
        } else if( action == "RIGHT" ) {
            tabindex = ( tabindex + 1 ) % tabcount;
            leftListIndex = leftListOffset = 0;
            selected = -1;
        } else if( action == "NEXT_TAB" ) {
            if( rightListOffset + rightListLines < rightListSize ) {
                rightListOffset++;
            }
        } else if( action == "PREV_TAB" ) {
            if( rightListOffset > 0 ) {
                rightListOffset--;
            }
        } else if( action == "MOVE_ARMOR" ) {
            if( selected >= 0 ) {
                selected = -1;
            } else {
                selected = leftListIndex;
            }
        } else if( action == "CHANGE_SIDE" ) {
            if( leftListIndex < leftListSize && tmp_worn[leftListIndex]->is_sided() ) {
                if( g->u.query_yn( _( "Swap side for %s?" ),
                                   colorize( tmp_worn[leftListIndex]->tname(),
                                             tmp_worn[leftListIndex]->color_in_inventory() ) ) ) {
                    change_side( *tmp_worn[leftListIndex] );
                }
            }
        } else if( action == "SORT_ARMOR" ) {
            // Copy to a vector because stable_sort requires random-access
            // iterators
            std::vector<item> worn_copy( worn.begin(), worn.end() );
            std::stable_sort( worn_copy.begin(), worn_copy.end(),
            []( const item & l, const item & r ) {
                return l.get_layer() < r.get_layer();
            }
                            );
            std::copy( worn_copy.begin(), worn_copy.end(), worn.begin() );
            reset_encumbrance();
        } else if( action == "EQUIP_ARMOR" ) {
            // filter inventory for all items that are armor/clothing
            item_location loc = game_menus::inv::wear( *this );
            // only equip if something valid selected!
            if( loc ) {
                // wear the item
                cata::optional<std::list<item>::iterator> new_equip_it =
                    wear( *loc.obtain( *this ) );
                if( new_equip_it ) {
                    body_part bp = static_cast<body_part>( tabindex );
                    if( tabindex == num_bp || ( **new_equip_it ).covers( bp ) ) {
                        // Set ourselves up to be pointing at the new item
                        // TODO: This doesn't work yet because we don't save our
                        // state through other activities, but that's a thing
                        // that would be nice to do.
                        leftListIndex =
                            std::count_if( worn.begin(), *new_equip_it,
                        [&]( const item & i ) {
                            return tabindex == num_bp || i.covers( bp );
                        } );
                    }
                } else if( is_npc() ) {
                    // TODO: Pass the reason here
                    popup( _( "Can't put this on!" ) );
                }
            }
        } else if( action == "EQUIP_ARMOR_HERE" ) {
            // filter inventory for all items that are armor/clothing
            item_location loc = game_menus::inv::wear( *this );
            // only equip if something valid selected!
            if( loc ) {
                // wear the item
                if( cata::optional<std::list<item>::iterator> new_equip_it =
                        wear( *loc.obtain( *this ) ) ) {
                    // save iterator to cursor's position
                    std::list<item>::iterator cursor_it = tmp_worn[leftListIndex];
                    // reorder `worn` vector to place new item at cursor
                    worn.splice( cursor_it, worn, *new_equip_it );
                } else if( is_npc() ) {
                    // TODO: Pass the reason here
                    popup( _( "Can't put this on!" ) );
                }
            }
        } else if( action == "REMOVE_ARMOR" ) {
            // query (for now)
            if( leftListIndex < leftListSize ) {
                if( g->u.query_yn( _( "Remove selected armor?" ) ) ) {
                    do_return_entry();
                    // remove the item, asking to drop it if necessary
                    takeoff( *tmp_worn[leftListIndex] );
                    if( !g->u.has_activity( ACT_ARMOR_LAYERS ) ) {
                        // An activity has been created to take off the item;
                        // we must surrender control until it is done.
                        return;
                    }
                    g->u.cancel_activity();
                    selected = -1;
                }
            }
        } else if( action == "ASSIGN_INVLETS" ) {
            // prompt first before doing this (yes, yes, more popups...)
            if( query_yn( _( "Reassign invlets for armor?" ) ) ) {
                // Start with last armor (the most unimportant one?)
                auto iiter = inv_chars.rbegin();
                auto witer = worn.rbegin();
                while( witer != worn.rend() && iiter != inv_chars.rend() ) {
                    const char invlet = *iiter;
                    item &w = *witer;
                    if( invlet == w.invlet ) {
                        ++witer;
                    } else if( invlet_to_item( invlet ) != nullptr ) {
                        ++iiter;
                    } else {
                        inv.reassign_item( w, invlet );
                        ++witer;
                        ++iiter;
                    }
                }
            }
        } else if( action == "USAGE_HELP" ) {
            popup_getkey(
                _( "Use the [<color_yellow>arrow- or keypad keys</color>] to navigate the left list.\n"
                   "[<color_yellow>%s</color>] to select highlighted armor for reordering.\n"
                   "[<color_yellow>%s</color>] / [<color_yellow>%s</color>] to scroll the right list.\n"
                   "[<color_yellow>%s</color>] to assign special inventory letters to clothing.\n"
                   "[<color_yellow>%s</color>] to change the side on which item is worn.\n"
                   "[<color_yellow>%s</color>] to sort armor into natural layer order.\n"
                   "[<color_yellow>%s</color>] to equip a new item.\n"
                   "[<color_yellow>%s</color>] to equip a new item at the currently selected position.\n"
                   "[<color_yellow>%s</color>] to remove selected armor from oneself.\n"
                   "\n"
                   "\n"
                   "Encumbrance explanation:\n"
                   "\n"
                   "<color_light_gray>The first number is the summed encumbrance from all clothing "
                   "on that bodypart.  The second number is an additional encumbrance penalty "
                   "caused by wearing either multiple items on one of the bodypart's layers or "
                   "wearing items the wrong way (e.g. a shirt over a backpack).  "
                   "The sum of these values is the effective encumbrance value "
                   "your character has for that bodypart.</color>" ),
                ctxt.get_desc( "MOVE_ARMOR" ),
                ctxt.get_desc( "PREV_TAB" ),
                ctxt.get_desc( "NEXT_TAB" ),
                ctxt.get_desc( "ASSIGN_INVLETS" ),
                ctxt.get_desc( "CHANGE_SIDE" ),
                ctxt.get_desc( "SORT_ARMOR" ),
                ctxt.get_desc( "EQUIP_ARMOR" ),
                ctxt.get_desc( "EQUIP_ARMOR_HERE" ),
                ctxt.get_desc( "REMOVE_ARMOR" )
            );
        } else if( action == "QUIT" ) {
            exit = true;
        }
    }
}
References _, Creature::A_FRIENDLY, ACT_ARMOR_LAYERS, action, Creature::add_msg_if_npc(), all_body_parts, Character::attitude_to(), body_part_name_as_heading(), c_light_blue, c_light_gray, c_white, c_yellow, Character::change_side(), color(), colorize(), draw_grid(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), fold_and_print(), format_volume(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, input_context::get_desc(), anonymous_namespace{armor_layers.cpp}::get_item_penalties(), input_context::handle_input(), Character::inv, inv_chars, item::invlet, Character::invlet_to_item(), is_npc(), is_player(), items_cover_bp(), m_bad, mvwprintz(), Character::name, catacurses::newwin(), num_bp, item_location::obtain(), sign::plus, point_east, point_zero, popup(), popup_getkey(), Character::pos(), character_display::print_encumbrance(), query_yn(), inventory::reassign_item(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), Character::reset_encumbrance(), right_print(), rl_dist(), string_format(), takeoff(), TERMX, TERMY, trim_and_print(), utf8_width(), volume_units_abbr(), wear(), game_menus::inv::wear(), catacurses::werase(), catacurses::wnoutrefresh(), Character::worn, wprintz(), point::x, and point::y.
Referenced by activity_handlers::armor_layers_do_turn(), game::handle_action(), and game::npc_menu().
start_craft()
item_location player::start_craft (craft_command & command, const tripoint & loc)
consume components and create an active, in progress craft containing them
Definition at line 727 of file crafting.cpp.
{
    if( command.empty() ) {
        debugmsg( "Attempted to start craft with empty command" );
        return item_location();
    }
    item craft = command.create_in_progress_craft();
    const recipe &making = craft.get_making();
    if( get_skill_level( command.get_skill_id() ) > making.difficulty * 1.25 ) {
        handle_skill_warning( command.get_skill_id(), true );
    }
    // In case we were wearing something just consumed
    if( !craft.components.empty() ) {
        reset_encumbrance();
    }
    bench_location bench = find_best_bench( *this, craft );
    std::pair<bench_type, float> best_found_bench = best_bench_here( craft, bench.position,
            bench.type == bench_type::hands );
    if( best_found_bench.second < 1.0f ) {
        add_msg_if_player( m_info, pgettext( "in progress craft",
                                             "You can't hold %s in your hands and there is no good work surface nearby." ), craft.tname() );
    }
    // Regardless of whether a workbench exists or not,
    // we still craft in inventory or under player, because QoL.
    item_location craft_in_world = set_item_inventory( *this, craft );
    assign_activity( ACT_CRAFT );
    activity.targets.push_back( craft_in_world );
    activity.coords.push_back( bench.position );
    activity.values.push_back( command.is_long() );
    // Ugly
    activity.values.push_back( static_cast<int>( bench.type ) );
    add_msg_player_or_npc(
        pgettext( "in progress craft", "You start working on the %s." ),
        pgettext( "in progress craft", "<npcname> starts working on the %s." ),
        craft.tname() );
    return craft_in_world;
}
References ACT_CRAFT, Character::activity, add_msg_if_player(), add_msg_player_or_npc(), Character::assign_activity(), best_bench_here(), player_activity::coords, craft(), craft_command::create_in_progress_craft(), debugmsg, recipe::difficulty, craft_command::empty(), find_best_bench(), craft_command::get_skill_id(), Character::get_skill_level(), handle_skill_warning(), hands, craft_command::is_long(), m_info, pgettext(), bench_location::position, Character::reset_encumbrance(), set_item_inventory(), player_activity::targets, bench_location::type, and player_activity::values.
Referenced by craft_consume_tools(), and craft_command::execute().
store() [1/2]
void player::store (item & container, item & put, bool penalties = true, int base_cost = INVENTORY_HANDLING_PENALTY)
Stores an item inside another consuming moves proportional to weapon skill and volume.
Parameters
container Container in which to store the item
put Item to add to the container
penalties Whether item volume and temporary effects (e.g. GRABBED, DOWNED) should be considered.
base_cost Cost due to storage type.
Definition at line 2535 of file player.cpp.
{
    moves -= item_store_cost( put, container, penalties, base_cost );
    container.put_in( i_rem( &put ) );
    reset_encumbrance();
}
References Character::i_rem(), Character::item_store_cost(), Creature::moves, item::put_in(), and Character::reset_encumbrance().
Referenced by avatar::store(), npc::store(), and holster_actor::store().
store() [2/2]
void player::store (JsonOut & json) const protected
Gather variables for saving.
These variables are common to both the avatar and npcs.
Definition at line 791 of file savegame_json.cpp.
{
    Character::store( json );
    // energy
    json.member( "last_sleep_check", last_sleep_check );
    // misc levels
    json.member( "tank_plut", tank_plut );
    json.member( "reactor_plut", reactor_plut );
    json.member( "slow_rad", slow_rad );
    json.member( "scent", static_cast<int>( scent ) );
    // gender
    json.member( "male", male );
    json.member( "cash", cash );
    json.member( "recoil", recoil );
    json.member( "in_vehicle", in_vehicle );
    json.member( "id", getID() );
    // potential incompatibility with future expansion
    json.member( "damage_bandaged", damage_bandaged );
    json.member( "damage_disinfected", damage_disinfected );
    // "Looks like I picked the wrong week to quit smoking." - Steve McCroskey
    json.member( "addictions", addictions );
    json.member( "followers", follower_ids );
    json.member( "worn", worn ); // also saves contents
    json.member( "inv" );
    inv.json_save_items( json );
    if( !weapon.is_null() ) {
        json.member( "weapon", weapon ); // also saves contents
    }
    if( const auto lt_ptr = last_target.lock() ) {
        if( const npc *const guy = dynamic_cast<const npc *>( lt_ptr.get() ) ) {
            json.member( "last_target", guy->getID() );
            json.member( "last_target_type", +1 );
        } else if( const monster *const mon = dynamic_cast<const monster *>( lt_ptr.get() ) ) {
            // monsters don't have IDs, so get its index in the Creature_tracker instead
            json.member( "last_target", g->critter_tracker->temporary_id( *mon ) );
            json.member( "last_target_type", -1 );
        }
    } else {
        json.member( "last_target_pos", last_target_pos );
    }
    json.member( "destination_point", destination_point );
    // faction warnings
    json.member( "faction_warnings" );
    json.start_array();
    for( const auto &elem : warning_record ) {
        json.start_object();
        json.member( "fac_warning_id", elem.first );
        json.member( "fac_warning_num", elem.second.first );
        json.member( "fac_warning_time", elem.second.second );
        json.end_object();
    }
    json.end_array();
    json.member( "ammo_location", ammo_location );
    // TODO: move to Character
    json.member( "camps" );
    json.start_array();
    for( const tripoint_abs_omt &bcpt : camps ) {
        json.start_object();
        json.member( "pos", bcpt );
        json.end_object();
    }
    json.end_array();
}
References Character::addictions, ammo_location, Character::camps, cash, Character::damage_bandaged, Character::damage_disinfected, Character::destination_point, JsonOut::end_array(), JsonOut::end_object(), follower_ids, g, Character::getID(), Character::in_vehicle, Character::inv, item::is_null(), inventory::json_save_items(), Character::last_sleep_check, last_target, last_target_pos, Character::male, JsonOut::member(), Character::reactor_plut, Character::recoil, scent, Character::slow_rad, JsonOut::start_array(), JsonOut::start_object(), Character::store(), Character::tank_plut, warning_record, Character::weapon, and Character::worn.
studied_all_recipes()
bool player::studied_all_recipes (const itype & book) const
Definition at line 2265 of file player.cpp.
{
    if( !book.book ) {
        return true;
    }
    for( auto &elem : book.book->recipes ) {
        if( !knows_recipe( elem.recipe ) ) {
            return false;
        }
    }
    return true;
}
References itype::book, and Character::knows_recipe().
Referenced by item::color_in_inventory().
takeoff() [1/2]
bool player::takeoff (int pos)
Definition at line 1740 of file player.cpp.
{
    return takeoff( i_at( pos ) );
}
References Character::i_at(), Character::pos(), and takeoff().
takeoff() [2/2]
bool player::takeoff (item & it, std::list< item > * res = nullptr)
Takes off an item, returning false on fail.
The taken off item is processed in the interact
Definition at line 1696 of file player.cpp.
{
    const auto ret = can_takeoff( it, res );
    if( !ret.success() ) {
        add_msg( m_info, "%s", ret.c_str() );
        return false;
    }
    auto iter = std::find_if( worn.begin(), worn.end(), [ &it ]( const item & wit ) {
        return &it == &wit;
    } );
    if( res == nullptr ) {
        if( volume_carried() + it.volume() > volume_capacity_reduced_by( it.get_storage() ) ) {
            if( is_npc() || query_yn( _( "No room in inventory for your %s.  Drop it?" ),
                                      colorize( it.tname(), it.color_in_inventory() ) ) ) {
                item_location loc( *this, &it );
                drop( loc, pos() );
                return true; // the drop activity ends up taking off the item anyway so shouldn't try to do it again here
            } else {
                return false;
            }
        }
        iter->on_takeoff( *this );
        inv.add_item_keep_invlet( it );
    } else {
        iter->on_takeoff( *this );
        res->push_back( it );
    }
    add_msg_player_or_npc( _( "You take off your %s." ),
                           _( "<npcname> takes off their %s." ),
                           it.tname() );
    // TODO: Make this variable
    mod_moves( -250 );
    worn.erase( iter );
    recalc_sight_limits();
    reset_encumbrance();
    return true;
}
References _, inventory::add_item_keep_invlet(), add_msg(), add_msg_player_or_npc(), can_takeoff(), item::color_in_inventory(), colorize(), Character::drop(), item::get_storage(), Character::inv, is_npc(), m_info, Creature::mod_moves(), Character::pos(), query_yn(), Character::recalc_sight_limits(), Character::reset_encumbrance(), cata::hash64_detail::ret, item::tname(), item::volume(), Character::volume_capacity_reduced_by(), Character::volume_carried(), and Character::worn.
Referenced by npc::adjust_worn(), pickup::obtain_and_tokenize_items(), examine_item_menu::run(), sort_armor(), takeoff(), takeoff(), and npc::wear_if_wanted().
throw_item()
dealt_projectile_attack player::throw_item (const tripoint & target, const item & to_throw, const cata::optional< tripoint > & blind_throw_from_pos = cata::nullopt)
Execute a throw.
Strength increases throwing damage Strength increases chance of shattering thrown glass items (NEGATIVE)
Definition at line 1111 of file ranged.cpp.
{
    // Copy the item, we may alter it before throwing
    item thrown = to_throw;
    const int move_cost = ranged::throw_cost( *this, to_throw );
    mod_moves( -move_cost );
    const int throwing_skill = get_skill_level( skill_throw );
    units::volume volume = to_throw.volume();
    units::mass weight = to_throw.weight();
    // Previously calculated as 2_gram * std::max( 1, str_cur )
    // using 16_gram normalizes it to 8 str. Same effort expenditure
    // for being able to throw farther.
    const int weight_cost = weight / ( 16_gram );
    const int encumbrance_cost = roll_remainder( ( encumb( bp_arm_l ) + encumb( bp_arm_r ) ) * 2.0f );
    const int stamina_cost = ( weight_cost + encumbrance_cost - throwing_skill + 50 ) * -1;
    bool throw_assist = false;
    int throw_assist_str = 0;
    if( is_mounted() ) {
        auto mons = mounted_creature.get();
        if( mons->mech_str_addition() != 0 ) {
            throw_assist = true;
            throw_assist_str = mons->mech_str_addition();
            mons->use_mech_power( -3 );
        }
    }
    if( !throw_assist ) {
        mod_stamina( stamina_cost );
    }
    const skill_id &skill_used = skill_throw;
    int skill_level = std::min( MAX_SKILL, get_skill_level( skill_throw ) );
    // if you are lying on the floor, you can't really throw that well
    if( has_effect( effect_downed ) ) {
        skill_level = std::max( 0, skill_level - 5 );
    }
    // We'll be constructing a projectile
    projectile proj;
    proj.impact = thrown.base_damage_thrown();
    proj.speed = 10 + skill_level;
    auto &impact = proj.impact;
    static const std::set<material_id> ferric = { material_id( "iron" ), material_id( "steel" ) };
    bool do_railgun = has_active_bionic( bio_railgun ) && thrown.made_of_any( ferric ) &&
                      !throw_assist;
    // The damage dealt due to item's weight, player's strength, and skill level
    // Up to str/2 or weight/100g (lower), so 10 str is 5 damage before multipliers
    // Railgun doubles the effective strength
    ///\EFFECT_STR increases throwing damage
    double stats_mod = do_railgun ? get_str() : ( get_str() / 2.0 );
    stats_mod = throw_assist ? throw_assist_str / 2.0 : stats_mod;
    // modify strength impact based on skill level, clamped to [0.15 - 1]
    // mod = mod * [ ( ( skill / max_skill ) * 0.85 ) + 0.15 ]
    stats_mod *= ( std::min( MAX_SKILL,
                             get_skill_level( skill_throw ) ) /
                   static_cast<double>( MAX_SKILL ) ) * 0.85 + 0.15;
    impact.add_damage( DT_BASH, std::min( weight / 100.0_gram, stats_mod ) );
    if( thrown.has_flag( "ACT_ON_RANGED_HIT" ) ) {
        proj.add_effect( ammo_effect_ACT_ON_RANGED_HIT );
        thrown.active = true;
    }
    // Item will shatter upon landing, destroying the item, dealing damage, and making noise
    /** @EFFECT_STR increases chance of shattering thrown glass items (NEGATIVE) */
    const bool shatter = !thrown.active && thrown.made_of( material_id( "glass" ) ) &&
                         rng( 0, units::to_milliliter( 2_liter - volume ) ) < get_str() * 100;
    // Item will burst upon landing, destroying the item, and spilling its contents
    const bool burst = thrown.has_property( "burst_when_filled" ) && thrown.is_container() &&
                       thrown.get_property_int64_t( "burst_when_filled" ) <= static_cast<double>
                       ( thrown.get_contained().volume().value() ) / thrown.get_container_capacity().value() * 100;
    // Add some flags to the projectile
    if( weight > 500_gram ) {
        proj.add_effect( ammo_effect_HEAVY_HIT );
    }
    proj.add_effect( ammo_effect_NO_ITEM_DAMAGE );
    if( thrown.active ) {
        // Can't have Molotovs embed into monsters
        // Monsters don't have inventory processing
        proj.add_effect( ammo_effect_NO_EMBED );
    }
    if( do_railgun ) {
        proj.add_effect( ammo_effect_LIGHTNING );
    }
    if( volume > 500_ml ) {
        proj.add_effect( ammo_effect_WIDE );
    }
    // Deal extra cut damage if the item breaks
    if( shatter ) {
        impact.add_damage( DT_CUT, units::to_milliliter( volume ) / 500.0f );
        proj.add_effect( ammo_effect_SHATTER_SELF );
    }
    // TODO: Add wet effect if other things care about that
    if( burst ) {
        proj.add_effect( ammo_effect_BURST );
    }
    // Some minor (skill/2) armor piercing for skillful throws
    // Not as much as in melee, though
    for( damage_unit &du : impact.damage_units ) {
        du.res_pen += skill_level / 2.0f;
    }
    // handling for tangling thrown items
    if( thrown.has_flag( "TANGLE" ) ) {
        proj.add_effect( ammo_effect_TANGLE );
    }
    Creature *critter = g->critter_at( target, true );
    const dispersion_sources dispersion( ranged::throwing_dispersion( *this, thrown, critter,
                                         blind_throw_from_pos.has_value() ) );
    const itype *thrown_type = thrown.type;
    // Put the item into the projectile
    proj.set_drop( std::move( thrown ) );
    if( thrown_type->has_flag( "CUSTOM_EXPLOSION" ) ) {
        proj.set_custom_explosion( thrown_type->explosion );
    }
    // Throw from the player's position, unless we're blind throwing, in which case
    // throw from the the blind throw position instead.
    const tripoint throw_from = blind_throw_from_pos ? *blind_throw_from_pos : pos();
    float range = rl_dist( throw_from, target );
    proj.range = range;
    int skill_lvl = get_skill_level( skill_used );
    // Avoid awarding tons of xp for lucky throws against hard to hit targets
    const float range_factor = std::min<float>( range, skill_lvl + 3 );
    // We're aiming to get a damaging hit, not just an accurate one - reward proper weapons
    const float damage_factor = 5.0f * std::sqrt( proj.impact.total_damage() / 5.0f );
    // This should generally have values below ~20*sqrt(skill_lvl)
    const float final_xp_mult = range_factor * damage_factor;
    auto dealt_attack = projectile_attack( proj, throw_from, target, dispersion, this );
    const double missed_by = dealt_attack.missed_by;
    if( missed_by <= 0.1 && dealt_attack.hit_critter != nullptr ) {
        practice( skill_used, final_xp_mult, MAX_SKILL );
        // TODO: Check target for existence of head
        g->events().send<event_type::character_gets_headshot>( getID() );
    } else if( dealt_attack.hit_critter != nullptr && missed_by > 0.0f ) {
        practice( skill_used, final_xp_mult / ( 1.0f + missed_by ), MAX_SKILL );
    } else {
        // Pure grindy practice - cap gain at lvl 2
        practice( skill_used, 5, 2 );
    }
    // Reset last target pos
    last_target_pos = cata::nullopt;
    recoil = MAX_RECOIL;
    return dealt_attack;
}
References item::active, projectile::add_effect(), ammo_effect_ACT_ON_RANGED_HIT, ammo_effect_BURST, ammo_effect_HEAVY_HIT, ammo_effect_LIGHTNING, ammo_effect_NO_EMBED, ammo_effect_NO_ITEM_DAMAGE, ammo_effect_SHATTER_SELF, ammo_effect_TANGLE, ammo_effect_WIDE, item::base_damage_thrown(), bio_railgun, bp_arm_l, bp_arm_r, character_gets_headshot, DT_BASH, DT_CUT, effect_downed, Character::encumb(), itype::explosion, g, item::get_contained(), item::get_container_capacity(), item::get_property_int64_t(), Character::get_skill_level(), Character::get_str(), Character::getID(), Character::has_active_bionic(), Creature::has_effect(), item::has_flag(), itype::has_flag(), item::has_property(), cata::optional< T >::has_value(), impact(), projectile::impact, item::is_container(), Character::is_mounted(), last_target_pos, item::made_of(), item::made_of_any(), MAX_RECOIL, MAX_SKILL, Creature::mod_moves(), Character::mod_stamina(), Character::mounted_creature, avatar_action::move(), move_cost(), cata::nullopt, Character::pos(), practice(), projectile_attack(), projectile::range, Character::recoil, damage_unit::res_pen, rl_dist(), rng(), roll_remainder(), projectile::set_custom_explosion(), projectile::set_drop(), skill_throw, projectile::speed, ranged::throw_cost(), ranged::throwing_dispersion(), units::to_milliliter(), damage_instance::total_damage(), item::type, units::quantity< V, U >::value(), item::volume(), volume, and item::weight().
Referenced by throw_activity_actor::do_turn(), and npc_throw().
toolmod_add()
void player::toolmod_add (item_location tool, item_location mod)
Starts activity to install toolmod.
Definition at line 2242 of file player.cpp.
{
    if( !tool && !mod ) {
        debugmsg( "Tried toolmod installation but mod/tool not available" );
        return;
    }
    // first check at least the minimum requirements are met
    if( !has_trait( trait_DEBUG_HS ) && !can_use( *mod, *tool ) ) {
        return;
    }
    if( !query_yn( _( "Permanently install your %1$s in your %2$s?" ),
                   colorize( mod->tname(), mod->color_in_inventory() ),
                   colorize( tool->tname(), tool->color_in_inventory() ) ) ) {
        add_msg_if_player( _( "Never mind." ) );
        return; // player canceled installation
    }
    assign_activity( activity_id( "ACT_TOOLMOD_ADD" ), 1, -1 );
    activity.targets.emplace_back( std::move( tool ) );
    activity.targets.emplace_back( std::move( mod ) );
}
References _, Character::activity, add_msg_if_player(), Character::assign_activity(), Character::can_use(), colorize(), debugmsg, Character::has_trait(), avatar_action::move(), query_yn(), player_activity::targets, tool, and trait_DEBUG_HS.
Referenced by iuse::toolmod_attach().
uncanny_dodge()
bool player::uncanny_dodge () override virtual
Handles the uncanny dodge bionic and effects, returns true if the player successfully dodges.
Reimplemented from Creature.
Definition at line 2564 of file player.cpp.
{
    bool is_u = this == &g->u;
    bool seen = g->u.sees( *this );
    if( this->get_power_level() < 74_kJ || !this->has_active_bionic( bio_uncanny_dodge ) ) {
        return false;
    }
    tripoint adjacent = adjacent_tile();
    mod_power_level( -75_kJ );
    if( adjacent.x != posx() || adjacent.y != posy() ) {
        position.x = adjacent.x;
        position.y = adjacent.y;
        if( is_u ) {
            add_msg( _( "Time seems to slow down and you instinctively dodge!" ) );
        } else if( seen ) {
            add_msg( _( "%s dodges so fast!" ), this->disp_name() );
        }
        return true;
    }
    if( is_u ) {
        add_msg( _( "You try to dodge but there's no room!" ) );
    } else if( seen ) {
        add_msg( _( "%s tries to dodge but there's no room!" ), this->disp_name() );
    }
    return false;
}
References _, add_msg(), Character::adjacent_tile(), bio_uncanny_dodge, Character::disp_name(), g, Character::get_power_level(), Character::has_active_bionic(), Character::mod_power_level(), Character::position, Character::posx(), Character::posy(), tripoint::x, and tripoint::y.
Referenced by mattack::grab(), and mattack::science().
unload()
bool player::unload (item_location loc)
Definition at line 1766 of file player.cpp.
{
    item &it = *loc.get_item();
    // Unload a container consuming moves per item successfully removed
    if( it.is_container() || it.is_bandolier() ) {
        if( it.contents.empty() ) {
            add_msg( m_info, _( "The %s is already empty!" ), it.tname() );
            return false;
        }
        if( !it.can_unload_liquid() ) {
            add_msg( m_info, _( "The liquid can't be unloaded in its current state!" ) );
            return false;
        }
        bool changed = false;
        for( item *contained : it.contents.all_items_top() ) {
            int old_charges = contained->charges;
            const bool consumed = this->add_or_drop_with_msg( *contained, true );
            changed = changed || consumed || contained->charges != old_charges;
            if( consumed ) {
                this->mod_moves( -this->item_handling_cost( *contained ) );
                it.remove_item( *contained );
            }
        }
        if( changed ) {
            it.on_contents_changed();
        }
        return true;
    }
    // If item can be unloaded more than once (currently only guns) prompt user to choose
    std::vector<std::string> msgs( 1, it.tname() );
    std::vector<item *> opts( 1, &it );
    for( auto e : it.gunmods() ) {
        if( e->is_gun() && !e->has_flag( "NO_UNLOAD" ) &&
            ( e->magazine_current() || e->ammo_remaining() > 0 || e->casings_count() > 0 ) ) {
            msgs.emplace_back( e->tname() );
            opts.emplace_back( e );
        }
    }
    item *target = nullptr;
    if( opts.size() > 1 ) {
        const int ret = uilist( _( "Unload what?" ), msgs );
        if( ret >= 0 ) {
            target = opts[ret];
        }
    } else {
        target = &it;
    }
    if( target == nullptr ) {
        return false;
    }
    // Next check for any reasons why the item cannot be unloaded
    if( target->ammo_types().empty() || target->ammo_capacity() <= 0 ) {
        add_msg( m_info, _( "You can't unload a %s!" ), target->tname() );
        return false;
    }
    if( target->has_flag( "NO_UNLOAD" ) ) {
        if( target->has_flag( "RECHARGE" ) || target->has_flag( "USE_UPS" ) ) {
            add_msg( m_info, _( "You can't unload a rechargeable %s!" ), target->tname() );
        } else {
            add_msg( m_info, _( "You can't unload a %s!" ), target->tname() );
        }
        return false;
    }
    if( !target->magazine_current() && target->ammo_remaining() <= 0 && target->casings_count() <= 0 ) {
        if( target->is_tool() ) {
            add_msg( m_info, _( "Your %s isn't charged." ), target->tname() );
        } else {
            add_msg( m_info, _( "Your %s isn't loaded." ), target->tname() );
        }
        return false;
    }
    target->casings_handle( [&]( item & e ) {
        return this->i_add_or_drop( e );
    } );
    if( target->is_magazine() ) {
        // Calculate the time to remove the contained ammo (consuming half as much time as required to load the magazine)
        int mv = 0;
        int qty = 0;
        std::vector<item *> remove_contained;
        for( item *contained : it.contents.all_items_top() ) {
            mv += this->item_reload_cost( it, *contained, contained->charges ) / 2;
            if( add_or_drop_with_msg( *contained, true ) ) {
                qty += contained->charges;
                remove_contained.push_back( contained );
            }
        }
        // remove the ammo leads in the belt
        for( item *remove : remove_contained ) {
            it.remove_item( *remove );
        }
        // remove the belt linkage
        if( it.is_ammo_belt() ) {
            if( it.type->magazine->linkage ) {
                item link( *it.type->magazine->linkage, calendar::turn, qty );
                add_or_drop_with_msg( link, true );
            }
            add_msg( _( "You disassemble your %s." ), it.tname() );
        } else {
            add_msg( _( "You unload your %s." ), it.tname() );
        }
        mod_moves( -std::min( 200, mv ) );
        if( loc->has_flag( "MAG_DESTROY" ) && loc->ammo_remaining() == 0 ) {
            loc.remove_item();
        }
        return true;
    } else if( target->magazine_current() ) {
        if( !this->add_or_drop_with_msg( *target->magazine_current(), true ) ) {
            return false;
        }
        // Eject magazine consuming half as much time as required to insert it
        this->moves -= this->item_reload_cost( *target, *target->magazine_current(), -1 ) / 2;
        target->remove_items_with( [&target]( const item & e ) {
            return target->magazine_current() == &e;
        } );
    } else if( target->ammo_remaining() ) {
        int qty = target->ammo_remaining();
        if( target->ammo_current() == itype_plut_cell ) {
            qty = target->ammo_remaining() / PLUTONIUM_CHARGES;
            if( qty > 0 ) {
                add_msg( _( "You recover %i unused plutonium." ), qty );
            } else {
                add_msg( m_info, _( "You can't remove partially depleted plutonium!" ) );
                return false;
            }
        }
        // Construct a new ammo item and try to drop it
        item ammo( target->ammo_current(), calendar::turn, qty );
        if( target->is_filthy() ) {
            ammo.set_flag( "FILTHY" );
        }
        if( ammo.made_of( LIQUID ) ) {
            if( !this->add_or_drop_with_msg( ammo ) ) {
                qty -= ammo.charges; // only handled part (or none) of the liquid
            }
            if( qty <= 0 ) {
                return false; // no liquid was moved
            }
        } else if( !this->add_or_drop_with_msg( ammo, qty > 1 ) ) {
            return false;
        }
        // If successful remove appropriate qty of ammo consuming half as much time as required to load it
        this->moves -= this->item_reload_cost( *target, ammo, qty ) / 2;
        if( target->ammo_current() == itype_plut_cell ) {
            qty *= PLUTONIUM_CHARGES;
        }
        target->ammo_set( target->ammo_current(), target->ammo_remaining() - qty );
    }
    // Turn off any active tools
    if( target->is_tool() && target->active && target->ammo_remaining() == 0 ) {
        target->type->invoke( *this, *target, this->pos() );
    }
    add_msg( _( "You unload your %s." ), target->tname() );
    return true;
}
References _, item::active, add_msg(), add_or_drop_with_msg(), item_contents::all_items_top(), item::ammo_capacity(), item::ammo_current(), item::ammo_remaining(), item::ammo_set(), item::ammo_types(), item::can_unload_liquid(), item::casings_count(), item::casings_handle(), item::charges, item::contents, item_contents::empty(), item_location::get_item(), item::gunmods(), item::has_flag(), Character::i_add_or_drop(), itype::invoke(), item::is_ammo_belt(), item::is_bandolier(), item::is_container(), item::is_filthy(), item::is_magazine(), item::is_tool(), Character::item_handling_cost(), item_reload_cost(), itype_plut_cell, LIQUID, m_info, item::made_of(), itype::magazine, item::magazine_current(), Creature::mod_moves(), Creature::moves, item::on_contents_changed(), PLUTONIUM_CHARGES, Character::pos(), item_location::remove_item(), visitable< T >::remove_item(), visitable< T >::remove_items_with(), cata::hash64_detail::ret, item::set_flag(), item::tname(), calendar::turn, and item::type.
Referenced by gunmod_remove(), vehicle::interact_with(), examine_item_menu::run(), iuse::toolmod_attach(), avatar_action::unload(), aim_activity_actor::unload_RAS_weapon(), and use().
unwield()
bool player::unwield ()
Definition at line 1273 of file player.cpp.
{
    if( weapon.is_null() ) {
        return true;
    }
    if( !can_unwield( weapon ).success() ) {
        return false;
    }
    const std::string query = string_format( _( "Stop wielding %s?" ), weapon.tname() );
    if( !dispose_item( item_location( *this, &weapon ), query ) ) {
        return false;
    }
    inv.unsort();
    return true;
}
References _, Character::can_unwield(), Character::dispose_item(), Character::inv, item::is_null(), string_format(), behavior::success, item::tname(), inventory::unsort(), and Character::weapon.
Referenced by avatar::wield(), avatar_action::wield(), and wield_contents().
use() [1/2]
void player::use (int inventory_position)
Uses a tool.
Definition at line 1953 of file player.cpp.
{
    item &used = i_at( inventory_position );
    auto loc = item_location( *this, &used );
    use( loc );
}
References Character::i_at(), and use().
Referenced by npc::find_dangerous_explosives(), npc::get_healing_item(), npc::has_healing_options(), use(), avatar_action::use_item(), and use_wielded().
use() [2/2]
void player::use (item_location loc)
Uses a tool at location.
Definition at line 1969 of file player.cpp.
{
    item &used = *loc.get_item();
    if( used.is_null() ) {
        add_msg( m_info, _( "You do not have that item." ) );
        return;
    }
    last_item = used.typeId();
    if( used.is_tool() ) {
        if( !used.type->has_use() ) {
            add_msg_if_player( _( "You can't do anything interesting with your %s." ), used.tname() );
            return;
        }
        invoke_item( &used, loc.position() );
    } else if( is_pet_food( used ) ) {
        invoke_item( &used, loc.position() );
    } else if( !used.is_container_empty() && is_pet_food( used.get_contained() ) ) {
        unload( loc );
    } else if( !used.is_craft() && ( used.is_medication() || ( !used.type->has_use() &&
                                     ( used.is_food() ||
                                       used.get_contained().is_food() ||
                                       used.get_contained().is_medication() ) ) ) ) {
        consume( loc );
    } else if( used.is_book() ) {
        // TODO: Handle this with dynamic dispatch.
        if( avatar *u = as_avatar() ) {
            u->read( loc );
        }
    } else if( used.type->has_use() ) {
        invoke_item( &used, loc.position() );
    } else if( used.has_flag( flag_SPLINT ) ) {
        ret_val<bool> need_splint = can_wear( used );
        if( need_splint.success() ) {
            wear_item( used );
            loc.remove_item();
        } else {
            add_msg( m_info, need_splint.str() );
        }
    } else {
        add_msg( m_info, _( "You can't do anything interesting with your %s." ),
                 used.tname() );
    }
    recalculate_enchantment_cache();
}
References _, add_msg(), add_msg_if_player(), Creature::as_avatar(), Character::can_wear(), consume(), flag_SPLINT(), item::get_contained(), item_location::get_item(), item::has_flag(), itype::has_use(), Character::invoke_item(), item::is_book(), item::is_container_empty(), item::is_craft(), item::is_food(), item::is_medication(), item::is_null(), is_pet_food(), item::is_tool(), Character::last_item, m_info, item_location::position(), Character::recalculate_enchantment_cache(), item_location::remove_item(), ret_val< T >::str(), ret_val< T >::success(), item::tname(), item::type, item::typeId(), unload(), and Character::wear_item().
use_wielded()
void player::use_wielded ()
Uses the current wielded weapon.
Definition at line 1948 of file player.cpp.
{
    use( -1 );
}
References use().
Referenced by game::handle_action().
wear() [1/2]
cata::optional< std::list< item >::iterator > player::wear (int pos, bool interactive = true)
Wear item; returns false on fail.
If interactive is false, don't alert the player or drain moves on completion.
Definition at line 1605 of file player.cpp.
{
    return wear( i_at( pos ), interactive );
}
References Character::i_at(), Character::pos(), and wear().
Referenced by examine_item_menu::run(), sort_armor(), wear(), and wear().
wear() [2/2]
cata::optional< std::list< item >::iterator > player::wear (item & to_wear, bool interactive = true)
Definition at line 1611 of file player.cpp.
{
    if( is_worn( to_wear ) ) {
        if( interactive ) {
            add_msg_player_or_npc( m_info,
                                   _( "You are already wearing that." ),
                                   _( "<npcname> is already wearing that." )
                                 );
        }
        return cata::nullopt;
    }
    if( to_wear.is_null() ) {
        if( interactive ) {
            add_msg_player_or_npc( m_info,
                                   _( "You don't have that item." ),
                                   _( "<npcname> doesn't have that item." ) );
        }
        return cata::nullopt;
    }
    bool was_weapon;
    item to_wear_copy( to_wear );
    if( &to_wear == &weapon ) {
        weapon = item();
        was_weapon = true;
    } else {
        inv.remove_item( &to_wear );
        inv.restack( *this );
        was_weapon = false;
    }
    auto result = wear_item( to_wear_copy, interactive );
    if( !result ) {
        if( was_weapon ) {
            weapon = to_wear_copy;
        } else {
            inv.add_item( to_wear_copy, true );
        }
        return cata::nullopt;
    }
    return result;
}
References _, inventory::add_item(), add_msg_player_or_npc(), Character::inv, item::is_null(), Character::is_worn(), m_info, cata::nullopt, inventory::remove_item(), inventory::restack(), Character::weapon, and Character::wear_item().
wield_contents()
bool player::wield_contents (item & container, item * internal_item = nullptr, bool penalties = true, int base_cost = INVENTORY_HANDLING_PENALTY)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
Parameters
container Container containing the item to be wielded
internal_item reference to contained item to wield.
penalties Whether item volume and temporary effects (e.g. GRABBED, DOWNED) should be considered.
base_cost Cost due to storage type.
Pistol decreases time taken to draw pistols from holsters Smg decreases time taken to draw smgs from holsters Rifle decreases time taken to draw rifles from holsters Shotgun decreases time taken to draw shotguns from holsters Launcher decreases time taken to draw launchers from holsters Stabbing decreases time taken to draw stabbing weapons from sheathes Cutting decreases time taken to draw cutting weapons from scabbards Bashing decreases time taken to draw bashing weapons from holsters
Definition at line 2465 of file player.cpp.
{
    // if index not specified and container has multiple items then ask the player to choose one
    if( internal_item == nullptr ) {
        std::vector<std::string> opts;
        std::list<item *> container_contents = container.contents.all_items_top();
        std::transform( container_contents.begin(), container_contents.end(),
        std::back_inserter( opts ), []( const item * elem ) {
            return elem->display_name();
        } );
        if( opts.size() > 1 ) {
            int pos = uilist( _( "Wield what?" ), opts );
            if( pos < 0 ) {
                return false;
            }
            internal_item = *std::next( container_contents.begin(), pos );
        } else {
            internal_item = &container.contents.front();
        }
    }
    if( !container.has_item( *internal_item ) ) {
        debugmsg( "Tried to wield non-existent item from container (player::wield_contents)" );
        return false;
    }
    const ret_val<bool> ret = can_wield( *internal_item );
    if( !ret.success() ) {
        add_msg_if_player( m_info, "%s", ret.c_str() );
        return false;
    }
    int mv = 0;
    if( is_armed() ) {
        if( !unwield() ) {
            return false;
        }
        inv.unsort();
    }
    weapon = std::move( *internal_item );
    container.remove_item( *internal_item );
    container.on_contents_changed();
    inv.update_invlet( weapon );
    inv.update_cache_with_item( weapon );
    last_item = weapon.typeId();
    /**
     * @EFFECT_PISTOL decreases time taken to draw pistols from holsters
     * @EFFECT_SMG decreases time taken to draw smgs from holsters
     * @EFFECT_RIFLE decreases time taken to draw rifles from holsters
     * @EFFECT_SHOTGUN decreases time taken to draw shotguns from holsters
     * @EFFECT_LAUNCHER decreases time taken to draw launchers from holsters
     * @EFFECT_STABBING decreases time taken to draw stabbing weapons from sheathes
     * @EFFECT_CUTTING decreases time taken to draw cutting weapons from scabbards
     * @EFFECT_BASHING decreases time taken to draw bashing weapons from holsters
     */
    int lvl = get_skill_level( weapon.is_gun() ? weapon.gun_skill() : weapon.melee_skill() );
    mv += item_handling_cost( weapon, penalties, base_cost ) / ( ( lvl + 10.0f ) / 10.0f );
    moves -= mv;
    weapon.on_wield( *this, mv );
    return true;
}
References _, add_msg_if_player(), item_contents::all_items_top(), can_wield(), item::contents, debugmsg, item_contents::front(), Character::get_skill_level(), item::gun_skill(), visitable< T >::has_item(), Character::inv, Character::is_armed(), item::is_gun(), Character::item_handling_cost(), Character::last_item, m_info, item::melee_skill(), avatar_action::move(), Creature::moves, item::on_contents_changed(), item::on_wield(), Character::pos(), visitable< T >::remove_item(), cata::hash64_detail::ret, iexamine::transform(), item::typeId(), inventory::unsort(), unwield(), inventory::update_cache_with_item(), inventory::update_invlet(), and Character::weapon.
Referenced by holster_actor::use().
Friends And Related Function Documentation
operator()() [1/2]
bool operator() (const profession_id & a, const profession_id & b) related
Definition at line 1338 of file newcharacter.cpp.
{
        // The generic ("Unemployed") profession should be listed first.
        const profession_id &gen = profession::generic();
        if( b == gen ) {
            return false;
        } else if( a == gen ) {
            return true;
        }
        if( sort_by_points ) {
            return a->point_cost() < b->point_cost();
        } else {
            return localized_compare( a->gender_appropriate_name( male ),
                                      b->gender_appropriate_name( male ) );
        }
    }
References a, b, profession::generic(), localized_compare, male, and sort_by_points.
operator()() [2/2]
bool operator() (const scenario * a, const scenario * b) related
Definition at line 1990 of file newcharacter.cpp.
{
        if( cities_enabled ) {
            // The generic ("Unemployed") profession should be listed first.
            const scenario *gen = scenario::generic();
            if( b == gen ) {
                return false;
            } else if( a == gen ) {
                return true;
            }
        }
        if( !cities_enabled && a->has_flag( "CITY_START" ) != b->has_flag( "CITY_START" ) ) {
            return a->has_flag( "CITY_START" ) < b->has_flag( "CITY_START" );
        } else if( sort_by_points ) {
            return a->point_cost() < b->point_cost();
        } else {
            return localized_compare( a->gender_appropriate_name( male ),
                                      b->gender_appropriate_name( male ) );
        }
    }
References a, b, cities_enabled, scenario::generic(), localized_compare, male, and sort_by_points.
Member Data Documentation
ammo_location
item_location player::ammo_location
Definition at line 474 of file player.h.
Referenced by favorite_ammo_or_select(), load(), aim_activity_actor::load_RAS_weapon(), ranged::prompt_select_default_ammo_for(), avatar_action::reload(), and store().
anchor
safe_reference_anchor player::anchor private
Definition at line 316 of file player.h.
Referenced by get_safe_reference().
cash
int player::cash = 0
Definition at line 476 of file player.h.
Referenced by avatar::create(), talk_function::follow(), load(), npc::mug_player(), player(), npc::randomize(), iexamine::slot_machine(), store(), and memorial_logger::write().
follower_ids
std::set<character_id> player::follower_ids
Definition at line 491 of file player.h.
Referenced by game::add_npc_follower(), load(), game::remove_npc_follower(), store(), and game::validate_npc_followers().
grab_point
tripoint player::grab_point
Definition at line 465 of file player.h.
Referenced by map::board_vehicle(), grab(), avatar::grab(), game::grabbed_furn_move(), game::grabbed_move(), game::grabbed_veh_move(), avatar::load(), player(), avatar::store(), game::vertical_move(), and game::walk_move().
last_batch
int player::last_batch = 0
Definition at line 488 of file player.h.
Referenced by craft_command::execute(), player(), and recraft().
last_craft
pimpl<craft_command> player::last_craft
Definition at line 485 of file player.h.
Referenced by activity_handlers::craft_do_turn(), make_craft_with_command(), and recraft().
last_target
weak_ptr_fast<Creature> player::last_target
Definition at line 471 of file player.h.
Referenced by target_ui::choose_initial_target(), game::list_monsters(), load(), target_ui::on_target_accepted(), target_ui::recalc_aim_turning_penalty(), target_ui::set_last_target(), store(), and target_ui::try_reacquire_target().
last_target_pos
cata::optional<tripoint> player::last_target_pos
Definition at line 472 of file player.h.
Referenced by load(), target_ui::recalc_aim_turning_penalty(), target_ui::set_last_target(), store(), throw_item(), target_ui::try_reacquire_target(), and game::walk_move().
lastconsumed
itype_id player::lastconsumed
Definition at line 489 of file player.h.
Referenced by consume_items(), construct::done_vehicle(), and player().
lastrecipe
recipe_id player::lastrecipe
Definition at line 487 of file player.h.
Referenced by activity_handlers::craft_do_turn(), craft_command::execute(), and recraft().
manual_examine
bool player::manual_examine = false
Definition at line 479 of file player.h.
Referenced by game::examine(), and harvest_common().
movecounter
int player::movecounter = 0
Definition at line 477 of file player.h.
Referenced by draw_char_narrow(), draw_char_wide(), draw_health_classic(), draw_stealth(), game::handle_action(), and player().
random_start_location
bool player::random_start_location = false
Definition at line 468 of file player.h.
Referenced by avatar::load_template(), avatar::randomize(), reset_scenario(), avatar::save_template(), set_description(), and game::start_game().
scent
int player::scent = 0
Definition at line 475 of file player.h.
Referenced by avatar::create(), game::do_turn(), load(), player(), and store().
start_location
start_location_id player::start_location
Definition at line 469 of file player.h.
Referenced by set_description(), and game::start_game().
starting_pets
std::vector<mtype_id> player::starting_pets
Definition at line 481 of file player.h.
Referenced by avatar::create(), and game::start_game().
starting_vehicle
vproto_id player::starting_vehicle
Definition at line 480 of file player.h.
Referenced by avatar::create(), and game::start_game().
view_offset
tripoint player::view_offset
Definition at line 463 of file player.h.
Referenced by aim_activity_actor::aim_activity_actor(), centerlistview(), debug_menu::character_edit_menu(), veh_interact::complete_vehicle(), debug_menu::debug(), game::display_scent(), game::draw(), draw_cone_aoe_curses(), game::draw_look_around_cursor(), game::draw_ter(), target_ui::draw_terrain_overlay(), game::draw_veh_dir_indicator(), generate_weather_anim_frame(), game::handle_action(), target_ui::handle_cursor_movement(), game::is_in_viewport(), game::list_items(), game::list_monsters(), game::look_around(), game::mon_info_update(), debug_menu::pick_character(), aim_activity_actor::restore_view(), target_ui::run(), game::set_driving_view_offset(), target_ui::set_view_offset(), and game::zones_manager().
volume
int player::volume = 0
Definition at line 466 of file player.h.
Referenced by game::do_turn(), draw_char_narrow(), draw_char_wide(), draw_lighting_classic(), draw_sound_labels(), draw_sound_narrow(), draw_stealth(), player(), sounds::process_sound_markers(), and throw_item().
warning_record
std::map<faction_id, std::pair<int, time_point> > player::warning_record private
warnings from a faction about bad behavior
Definition at line 537 of file player.h.
Referenced by add_faction_warning(), beyond_final_warning(), current_warnings_fac(), load(), and store().
The documentation for this class was generated from the following files:
src/player.h
src/armor_layers.cpp
src/consumption.cpp
src/crafting.cpp
src/martialarts.cpp
src/melee.cpp
src/newcharacter.cpp
src/player.cpp
src/ranged.cpp
src/savegame_json.cpp