Cataclysm BN: inventory_pick_selector Class Reference
inventory_pick_selector Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_pick_selector (player &p, const inventory_selector_preset &preset=default_preset)
item_location execute ()
Public Member Functions inherited from inventory_selector
inventory_selector (player &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
void add_character_items (Character &character)
These functions add items from map / vehicles.
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
bool select (const item_location &loc)
Select a location.
const inventory_entry & get_selected ()
void select_position (std::pair< size_t, size_t > position)
std::pair< size_t, size_t > get_selection_position ()
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void set_active_column (size_t index)
std::string action_bound_to_key (char key) const
std::vector< char > all_bound_keys () const
Returns all keys in the current context which are bound to an action.
Additional Inherited Members
Public Types inherited from inventory_selector
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 2 >
Public Attributes inherited from inventory_selector
bool keep_open = false
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
void add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr)
void add_item (inventory_column &target_column, item_location &&location, const item_category *custom_category=nullptr)
void add_items (inventory_column &target_column, const std::function< item_location(item *)> &locator, const std::vector< std::list< item * > > &stacks, const item_category *custom_category=nullptr)
inventory_input get_input ()
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
void set_filter ()
virtual void rearrange_columns (size_t client_width)
Tackles screen overflow.
virtual stats get_raw_stats () const
Get stats to display in top right.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Static Protected Member Functions inherited from inventory_selector
static stats get_weight_and_volume_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity)
Protected Attributes inherited from inventory_selector
player & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
Detailed Description
Definition at line 654 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_pick_selector()
inventory_pick_selector::inventory_pick_selector (player & p, const inventory_selector_preset & preset = default_preset) inline
Definition at line 657 of file inventory_ui.h.
                                                                                            :
            inventory_selector( p, preset ) {}
Member Function Documentation
execute()
item_location inventory_pick_selector::execute ()
Definition at line 1904 of file inventory_ui.cpp.
{
    shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
    while( true ) {
        ui_manager::redraw();
        const inventory_input input = get_input();
        if( input.entry != nullptr ) {
            if( select( input.entry->any_item() ) ) {
                ui_manager::redraw();
            }
            return input.entry->any_item();
        } else if( input.action == "QUIT" ) {
            return item_location();
        } else if( input.action == "CONFIRM" ) {
            const inventory_entry &selected = get_active_column().get_selected();
            if( selected ) {
                return selected.any_item();
            }
        } else if( input.action == "INVENTORY_FILTER" ) {
            set_filter();
        } else {
            on_input( input );
        }
        if( input.action == "TOGGLE_FAVORITE" ) {
            return item_location();
        }
    }
}
References inventory_input::action, inventory_entry::any_item(), inventory_selector::create_or_get_ui_adaptor(), inventory_input::entry, inventory_selector::get_active_column(), inventory_selector::get_input(), inventory_column::get_selected(), inventory_selector::on_input(), ui_manager::redraw(), inventory_selector::select(), and inventory_selector::set_filter().
Referenced by autoclave_internal(), autodoc_internal(), game_menus::inv::common(), inv_internal(), and game_menus::inv::swap_letters().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp