Cataclysm BN: SkillDisplayType Class Reference
SkillDisplayType Class Reference
#include <skill.h>
Public Member Functions
SkillDisplayType ()
SkillDisplayType (const skill_displayType_id &ident, const translation &display_string)
const skill_displayType_id & ident () const
std::string display_string () const
Static Public Member Functions
static void load (const JsonObject &jsobj)
static void reset ()
static const SkillDisplayType & get_skill_type (const skill_displayType_id &)
Static Public Attributes
static std::vector< SkillDisplayType > skillTypes
Private Attributes
skill_displayType_id _ident
translation _display_string
Friends
class string_id< SkillDisplayType >
Detailed Description
Definition at line 225 of file skill.h.
Constructor & Destructor Documentation
SkillDisplayType() [1/2]
SkillDisplayType::SkillDisplayType ()
Definition at line 130 of file skill.cpp.
                                   : SkillDisplayType( skill_displayType_id::NULL_ID(),
            to_translation( "invalid" ) )
{
}
SkillDisplayType() [2/2]
SkillDisplayType::SkillDisplayType (const skill_displayType_id & ident, const translation & display_string)
Definition at line 135 of file skill.cpp.
    : _ident( ident ), _display_string( display_string )
{
}
Member Function Documentation
display_string()
std::string SkillDisplayType::display_string () const inline
Definition at line 243 of file skill.h.
{
            return _display_string.translated();
        }
References _display_string, and translation::translated().
Referenced by draw_skills_tab(), load(), and set_skills().
get_skill_type()
const SkillDisplayType & SkillDisplayType::get_skill_type (const skill_displayType_id & id) static
Definition at line 176 of file skill.cpp.
{
    for( auto &i : skillTypes ) {
        if( i._ident == id ) {
            return i;
        }
    }
    return invalid_skill_type;
}
References invalid_skill_type, and skillTypes.
Referenced by draw_skills_tab().
ident()
const skill_displayType_id & SkillDisplayType::ident () const inline
Definition at line 240 of file skill.h.
{
            return _ident;
        }
References _ident.
Referenced by load().
load()
void SkillDisplayType::load (const JsonObject & jsobj) static
Definition at line 154 of file skill.cpp.
{
    // TEMPORARY until 0.G: Remove "ident" support
    skill_displayType_id ident = skill_displayType_id(
                                     jsobj.has_string( "ident" ) ? jsobj.get_string( "ident" ) :
                                     jsobj.get_string( "id" ) );
    skillTypes.erase( std::remove_if( begin( skillTypes ),
    end( skillTypes ), [&]( const SkillDisplayType & s ) {
        return s._ident == ident;
    } ), end( skillTypes ) );
    translation display_string;
    jsobj.read( "display_string", display_string );
    const SkillDisplayType sk( ident, display_string );
    skillTypes.push_back( sk );
}
References _ident, display_string(), JsonObject::get_string(), JsonObject::has_string(), ident(), JsonObject::read(), and skillTypes.
Referenced by DynamicDataLoader::initialize().
reset()
void SkillDisplayType::reset () static
Definition at line 171 of file skill.cpp.
{
    skillTypes.clear();
}
References skillTypes.
Referenced by DynamicDataLoader::unload_data().
Friends And Related Function Documentation
string_id< SkillDisplayType >
friend class string_id< SkillDisplayType > friend
Definition at line 222 of file skill.h.
Member Data Documentation
_display_string
translation SkillDisplayType::_display_string private
Definition at line 229 of file skill.h.
Referenced by display_string().
_ident
skill_displayType_id SkillDisplayType::_ident private
Definition at line 228 of file skill.h.
Referenced by ident(), and load().
skillTypes
std::vector< SkillDisplayType > SkillDisplayType::skillTypes static
Definition at line 231 of file skill.h.
Referenced by get_skill_type(), load(), and reset().
The documentation for this class was generated from the following files:
src/skill.h
src/skill.cpp