Cataclysm BN: item_reload_option Class Reference
item_reload_option Class Reference
#include <item.h>
Public Member Functions
item_reload_option ()=default
item_reload_option (const item_reload_option &)
item_reload_option & operator= (const item_reload_option &)
item_reload_option (const player *who, const item *target, const item *parent, const item_location &ammo)
int qty () const
void qty (int val)
int moves () const
operator bool () const
Public Attributes
const player * who = nullptr
const item * target = nullptr
item_location ammo
Private Attributes
int qty_ = 0
int max_qty = INT_MAX
const item * parent = nullptr
Detailed Description
Definition at line 176 of file item.h.
Constructor & Destructor Documentation
item_reload_option() [1/3]
item_reload_option::item_reload_option () default
item_reload_option() [2/3]
item_reload_option::item_reload_option (const item_reload_option &) default
item_reload_option() [3/3]
item_reload_option::item_reload_option (const player * who, const item * target, const item * parent, const item_location & ammo)
Definition at line 8028 of file item.cpp.
                                                                    :
    who( who ), target( target ), ammo( ammo ), parent( parent )
{
    if( this->target->is_ammo_belt() && this->target->type->magazine->linkage ) {
        max_qty = this->who->charges_of( * this->target->type->magazine->linkage );
    }
    qty( max_qty );
}
References visitable< T >::charges_of(), item::is_ammo_belt(), itype::magazine, max_qty, qty(), and item::type.
Member Function Documentation
moves()
int item_reload_option::moves () const
Definition at line 8038 of file item.cpp.
{
    int mv = ammo.obtain_cost( *who, qty() ) + who->item_reload_cost( *target, *ammo, qty() );
    if( parent != target ) {
        if( parent->is_gun() ) {
            mv += parent->get_reload_time();
        } else if( parent->is_tool() ) {
            mv += 100;
        }
    }
    return mv;
}
References ammo, item::get_reload_time(), item::is_gun(), item::is_tool(), Character::item_reload_cost(), item_location::obtain_cost(), parent, qty(), target, and who.
Referenced by vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), avatar_action::reload(), bandolier_actor::reload(), and ammobelt_actor::use().
operator bool()
item_reload_option::operator bool () const inline explicit
Definition at line 198 of file item.h.
{
            return who && target && ammo && qty_ > 0;
        }
operator=()
item_reload_option & item_reload_option::operator= (const item_reload_option &) default
qty() [1/2]
int item_reload_option::qty () const inline
Definition at line 191 of file item.h.
{
            return qty_;
        }
Referenced by vehicle::interact_with(), item_reload_option(), moves(), avatar_action::reload(), bandolier_actor::reload(), and ammobelt_actor::use().
qty() [2/2]
void item_reload_option::qty (int val)
Definition at line 8051 of file item.cpp.
{
    bool ammo_in_container = ammo->is_ammo_container();
    bool ammo_in_liquid_container = ammo->is_watertight_container();
    item &ammo_obj = ( ammo_in_container || ammo_in_liquid_container ) ?
                     ammo->contents.front() : *ammo;
    if( ( ammo_in_container && !ammo_obj.is_ammo() ) ||
        ( ammo_in_liquid_container && !ammo_obj.made_of( LIQUID ) ) ) {
        debugmsg( "Invalid reload option: %s", ammo_obj.tname() );
        return;
    }
    // Checking ammo capacity implicitly limits guns with removable magazines to capacity 0.
    // This gets rounded up to 1 later.
    int remaining_capacity = target->is_watertight_container() ?
                             target->get_remaining_capacity_for_liquid( ammo_obj, true ) :
                             target->ammo_capacity() - target->ammo_remaining();
    if( target->has_flag( flag_RELOAD_ONE ) && !ammo->has_flag( flag_SPEEDLOADER ) ) {
        remaining_capacity = 1;
    }
    if( ammo_obj.type->ammo ) {
        if( ammo_obj.ammo_type() == ammo_plutonium ) {
            remaining_capacity = remaining_capacity / PLUTONIUM_CHARGES +
                                 ( remaining_capacity % PLUTONIUM_CHARGES != 0 );
        }
    }
    bool ammo_by_charges = ammo_obj.is_ammo() || ammo_in_liquid_container;
    int available_ammo = ammo_by_charges ? ammo_obj.charges : ammo_obj.ammo_remaining();
    // constrain by available ammo, target capacity and other external factors (max_qty)
    // @ref max_qty is currently set when reloading ammo belts and limits to available linkages
    qty_ = std::min( { val, available_ammo, remaining_capacity, max_qty } );
    // always expect to reload at least one charge
    qty_ = std::max( qty_, 1 );
}
References ammo, itype::ammo, item::ammo_capacity(), ammo_plutonium, item::ammo_remaining(), item::ammo_type(), item::charges, item::contents, debugmsg, flag_RELOAD_ONE(), flag_SPEEDLOADER(), item_contents::front(), item::get_remaining_capacity_for_liquid(), item::has_flag(), item::is_ammo(), item::is_ammo_container(), item::is_watertight_container(), LIQUID, item::made_of(), max_qty, PLUTONIUM_CHARGES, qty_, target, item::tname(), and item::type.
Member Data Documentation
ammo
item_location item_reload_option::ammo
Definition at line 189 of file item.h.
Referenced by npc::do_reload(), npc::find_reloadable(), npc::find_usable_ammo(), vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), moves(), ranged::prompt_select_default_ammo_for(), qty(), avatar_action::reload(), bandolier_actor::reload(), character_funcs::select_ammo(), and ammobelt_actor::use().
max_qty
int item_reload_option::max_qty = INT_MAX private
Definition at line 204 of file item.h.
Referenced by item_reload_option(), and qty().
parent
const item* item_reload_option::parent = nullptr private
Definition at line 205 of file item.h.
Referenced by moves().
qty_
int item_reload_option::qty_ = 0 private
Definition at line 203 of file item.h.
Referenced by qty().
target
const item* item_reload_option::target = nullptr
Definition at line 188 of file item.h.
Referenced by npc::do_reload(), moves(), qty(), and avatar_action::reload().
who
const player* item_reload_option::who = nullptr
Definition at line 187 of file item.h.
Referenced by moves().
The documentation for this class was generated from the following files:
src/item.h
src/item.cpp