Cataclysm BN: visitable< T > Class Template Reference
visitable< T > Class Template Reference
#include <visitable.h>
Public Member Functions
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
Traverses this object and any child items contained using a visitor pattern.
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
Lightweight version which provides only the current node.
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
item * find_parent (const item &it)
Determine the immediate parent container (if any) for an item.
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
Returns vector of parent containers (if any) starting with the innermost.
std::vector< const item * > parents (const item &it) const
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, std::function< void(int)> visitor=nullptr) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX)
Removes items contained by this instance which match the filter.
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Related Functions
(Note that these are not member functions.)
template<typename T >
item * find_parent (const item &it)
template<typename T >
const item * find_parent (const item &it) const
template<typename T >
std::vector< item * > parents (const item &it)
template<typename T >
std::vector< const item * > parents (const item &it) const
template<typename T >
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
template<typename T >
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
template<typename T >
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
template<typename T >
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
template<typename T >
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
template<>
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
template<>
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
Detailed Description
template<typename T>
class visitable< T >
Definition at line 23 of file visitable.h.
Member Function Documentation
amount_of()
template<typename T > int amount_of (const itype_id & what, bool pseudo = true, int limit = INT_MAX, const std::function< bool(const item &)> & filter = return_true<item>) const
Count items matching id including both this instance and any contained items.
Parameters
what ID of items to count. "any" will count all items (usually used with a filter)
pseudo whether pseudo-items (from map/vehicle tiles, bionics etc) are considered
limit stop searching after this many matches
filter only count items that match the filter
Note
items must be empty to be considered a match
Definition at line 1048 of file visitable.cpp.
{
    return amount_of_internal( *this, what, pseudo, limit, filter );
}
References amount_of_internal().
Referenced by craft_command::check_item_components_missing(), crafting::get_books_for_recipe(), requirement_data::get_folded_list(), repair_item_actor::handle_components(), mill_load_food(), player::select_item_component(), and smoker_load_food().
charges_of()
template<typename T > int charges_of (const itype_id & what, int limit = INT_MAX, const std::function< bool(const item &)> & filter = return_true<item>, std::function< void(int)> visitor = nullptr) const
Count maximum available charges from this instance and any contained items.
Parameters
what ID of item to count charges of
limit stop searching after this many charges have been found
filter only count charges of items that match the filter
visitor is called when UPS charge is used (parameter is the charge itself)
Definition at line 943 of file visitable.cpp.
{
    return charges_of_internal( *this, *this, what, limit, filter, visitor );
}
References charges_of_internal().
Referenced by character_funcs::ammo_count_for(), craft_command::check_item_components_missing(), crafting::find_tool_component(), ranged::fire_gun(), iexamine::fvat_empty(), json_talk_topic::gen_responses(), requirement_data::get_folded_list(), repair_item_actor::handle_components(), tool_comp::has(), requirement_data::has_comps(), item_reload_option::item_reload_option(), iexamine::keg(), mill_load_food(), parse_tags(), monexamine::pay_bot(), iexamine::pay_gas(), iexamine::reload_furniture(), player::select_item_component(), talk_effect_fun_t::set_bulk_trade_accept(), conditional_t< T >::set_has_item(), smoker_load_food(), iexamine::smoker_options(), item::units_remaining(), place_monster_iuse::use(), iexamine::vending(), and wash_items().
find_parent() [1/2]
template<typename T > item * find_parent (const item & it)
Determine the immediate parent container (if any) for an item.
Parameters
it item to search for which must be contained (at any depth) by this object
Returns
parent container or nullptr if the item is not within a container
Definition at line 49 of file visitable.cpp.
{
    item *res = nullptr;
    if( visit_items( [&]( item * node, item * parent ) {
    if( node == &it ) {
            res = parent;
            return VisitResponse::ABORT;
        }
        return VisitResponse::NEXT;
    } ) != VisitResponse::ABORT ) {
        debugmsg( "Tried to find item parent using an object that doesn't contain it" );
    }
    return res;
}
Referenced by ranged::get_weapon_dispersion().
find_parent() [2/2]
template<typename T > const item * find_parent (const item & it) const
Definition at line 66 of file visitable.cpp.
{
    return const_cast<visitable<T> *>( this )->find_parent( it );
}
has_amount()
template<typename T > bool has_amount (const itype_id & what, int qty, bool pseudo = true, const std::function< bool(const item &)> & filter = return_true<item>) const
Check instance provides at least qty of an item (.
See also
amount_of)
Definition at line 1108 of file visitable.cpp.
{
    return amount_of( what, pseudo, qty, filter ) == qty;
}
Referenced by computer_session::action_srcf_elevator(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), craft_command::check_item_components_missing(), craft_command::check_tool_components_missing(), game::cleanup_at_end(), consider_butchery(), game::find_or_make_stairs(), crafting::find_tool_component(), json_talk_topic::gen_responses(), repair_item_actor::handle_components(), mission::is_complete(), iexamine::ledge(), monexamine::mech_hack(), iuse::meth(), iuse::multicooker(), iexamine::pedestal_temple(), monexamine::pet_menu(), iexamine::pit(), query_for_item(), talk_effect_fun_t::set_consume_item(), conditional_t< T >::set_has_item(), conditional_t< T >::set_has_items(), talk_effect_fun_t::set_u_sell_item(), iexamine::tree_maple(), try_consume(), unfold_vehicle_iuse::use(), consume_drug_iuse::use(), sew_advanced_actor::use(), and weed_msg().
has_item()
template<typename T > bool has_item (const item & it) const
Returns true if this visitable instance contains the item.
Definition at line 95 of file visitable.cpp.
{
    return visit_items( [&it]( const item * node ) {
        return node == &it ? VisitResponse::ABORT : VisitResponse::NEXT;
    } ) == VisitResponse::ABORT;
}
Referenced by iuse::acidbomb_act(), iuse::cable_attach(), iuse::craft(), iuse::disassemble(), iuse::ehandcuffs(), pickup_inventory_preset::get_denial(), get_item_location(), Character::get_item_position(), item::get_remaining_capacity_for_liquid(), ranged::get_weapon_dispersion(), avatar_funcs::gunmod_add(), Character::irradiate(), enchantment::is_active(), avatar_action::mend(), iuse::molotov_lit(), iuse::mp3_on(), iuse::note_bionics(), item::process_cable(), item::process_extinguish(), ranged::prompt_select_default_ammo_for(), inventory_column::reassign_custom_invlets(), examine_item_menu::run(), iuse::tow_attach(), character_funcs::try_wield_contents(), iuse_transform::use(), explosion_iuse::use(), and set_transform_iuse::use().
has_item_with()
template<typename T > bool has_item_with (const std::function< bool(const item &)> & filter) const
Returns true if any item (including those within a container) matches the filter.
Definition at line 104 of file visitable.cpp.
{
    return visit_items( [&filter]( const item * node ) {
        return filter( *node ) ? VisitResponse::ABORT : VisitResponse::NEXT;
    } ) == VisitResponse::ABORT;
}
References ABORT, NEXT, and visitable< T >::visit_items().
Referenced by can_do_activity_there(), item::color_in_inventory(), consider_butchery(), behavior::character_oracle_t::has_food(), behavior::character_oracle_t::has_water(), iexamine::keg(), ma_style_callback::key(), item::process_cable(), and item::process_UPS().
has_quality()
template<typename T > bool has_quality (const quality_id & qual, int level = 1, int qty = 1) const
Returns true if instance has amount (or more) items of at least quality level.
Definition at line 169 of file visitable.cpp.
{
    return has_quality_internal( *this, qual, level, qty ) == qty;
}
References has_quality_internal().
Referenced by iexamine::autodoc(), autodoc_internal(), Character::best_quality_item(), can_do_activity_there(), iuse_transform::can_use(), veh_interact::cant_do(), cast_spell(), requirement_data::check_enough_materials(), iuse::dig(), find_best_prying_tool(), iexamine::flower_dahlia(), generic_multi_activity_do(), quality_requirement::has(), vehicle::interact_vehicle_locked(), Character::item_with_best_of_quality(), iuse::multicooker(), iuse::oxytorch(), monexamine::pet_menu(), requirements_map(), iexamine::rubble(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), and place_trap_actor::use().
items_with() [1/2]
template<typename T > std::vector< item * > items_with (const std::function< bool(const item &)> & filter)
Returns all items (including those within a container) matching the filter.
Definition at line 324 of file visitable.cpp.
{
    std::vector<item *> res;
    visit_items( [&res, &filter]( item * node, item * ) {
        if( filter( *node ) ) {
            res.push_back( node );
        }
        return VisitResponse::NEXT;
    } );
    return res;
}
References NEXT, and visitable< T >::visit_items().
Referenced by game::add_artifact_dreams(), monexamine::add_leash(), iexamine::autodoc(), autodoc_internal(), game::butcher(), can_do_activity_there(), check_litcig(), activity_handlers::cracking_do_turn(), iuse::directional_antenna(), iexamine::dirtmound(), farm_action(), find_best_lock_picking_tool(), find_best_prying_tool(), find_food_heater(), iexamine::fireplace(), iexamine::fvat_empty(), json_talk_topic::gen_responses(), generic_multi_activity_do(), character_funcs::get_ammo_items(), bionic_install_preset::get_failure_chance(), monexamine::insert_battery(), iexamine::keg(), mill_load_food(), mine_activity(), monexamine::pet_menu(), item::process_cable(), plot_options::query_seed(), iuse::radiocontrol(), vehicle::reload_seeds(), iexamine::safe(), conditional_t< T >::set_has_item_category(), iexamine::sign(), smoker_load_food(), basecamp::start_farm_op(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), and vehicle::use_washing_machine().
items_with() [2/2]
template<typename T > std::vector< const item * > items_with (const std::function< bool(const item &)> & filter) const
Definition at line 339 of file visitable.cpp.
{
    std::vector<const item *> res;
    visit_items( [&res, &filter]( const item * node, const item * ) {
        if( filter( *node ) ) {
            res.push_back( node );
        }
        return VisitResponse::NEXT;
    } );
    return res;
}
References NEXT, and visitable< T >::visit_items().
max_quality()
template<typename T > int max_quality (const quality_id & qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
Definition at line 276 of file visitable.cpp.
{
    return max_quality_internal( *this, qual );
}
References max_quality_internal().
Referenced by Character::best_nearby_lifting_assist(), game::butcher(), activity_handlers::butcher_finish(), butcher_submenu(), butcher_time_to_cut(), veh_interact::cache_tool_availability(), can_butcher_at(), consider_butchery(), game::place_player(), and monexamine::shear_animal().
parents() [1/2]
template<typename T > std::vector< item * > parents (const item & it)
Returns vector of parent containers (if any) starting with the innermost.
Parameters
it item to search for which must be contained (at any depth) by this object
Definition at line 73 of file visitable.cpp.
{
    std::vector<item *> res;
    for( item *obj = find_parent( it ); obj; obj = find_parent( *obj ) ) {
        res.push_back( obj );
    }
    return res;
}
References visitable< T >::find_parent(), and int_id< T >::obj().
Referenced by item_location::impl::item_on_person::describe(), and item_location::impl::item_on_person::obtain_cost().
parents() [2/2]
template<typename T > std::vector< const item * > parents (const item & it) const
Definition at line 84 of file visitable.cpp.
{
    std::vector<const item *> res;
    for( const item *obj = find_parent( it ); obj; obj = find_parent( *obj ) ) {
        res.push_back( obj );
    }
    return res;
}
References visitable< T >::find_parent(), and int_id< T >::obj().
remove_item()
template<typename T > item remove_item (item & it)
Removes and returns the item which must be contained by this instance.
Definition at line 563 of file visitable.cpp.
{
    auto obj = remove_items_with( [&it]( const item & e ) {
        return &e == &it;
    }, 1 );
    if( !obj.empty() ) {
        return obj.front();
    } else {
        debugmsg( "Tried removing item from object which did not contain it" );
        return item();
    }
}
References debugmsg, int_id< T >::obj(), and visitable< T >::remove_items_with().
Referenced by veh_interact::complete_vehicle(), Character::dispose_item(), avatar_action::eat(), talk_function::give_equipment(), activity_handlers::gunmod_add_finish(), avatar_funcs::gunmod_remove(), liquid_handler::handle_liquid_from_container(), iuse::multicooker(), iuse::radiocar(), item::reload(), item_location::impl::item_on_map::remove_item(), item_location::impl::item_on_person::remove_item(), item_location::impl::item_on_vehicle::remove_item(), item_location::impl::item_in_container::remove_item(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), try_consume(), character_funcs::try_wield_contents(), avatar_funcs::unload_item(), and bandolier_actor::use().
remove_items_with()
template<typename T > std::list< item > visitable< T >::remove_items_with (const std::function< bool(const item &)> & filter, int count = INT_MAX)
Removes items contained by this instance which match the filter.
Note
if this instance itself is an item it will not be considered by the filter
Parameters
filter a UnaryPredicate which should return true if the item is to be removed
count maximum number of items to if unspecified unlimited. A count of zero is a no-op
Returns
any items removed (items counted by charges are not guaranteed to be stacked)
Referenced by empty_buckets(), mill_load_food(), remove_ammo(), talk_effect_fun_t::set_remove_item_with(), smoker_load_food(), and avatar_funcs::unload_item().
visit_items() [1/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(const item *)> & func) const
Definition at line 363 of file visitable.cpp.
{
    return const_cast<visitable<T> *>( this )->visit_items(
               static_cast<const std::function<VisitResponse( item * )>&>( func ) );
}
References visitable< T >::visit_items().
visit_items() [2/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> & func) const
Definition at line 354 of file visitable.cpp.
{
    return const_cast<visitable<T> *>( this )->visit_items(
               static_cast<const std::function<VisitResponse( item *, item * )>&>( func ) );
}
References visitable< T >::visit_items().
visit_items() [3/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(item *)> & func)
Lightweight version which provides only the current node.
Definition at line 371 of file visitable.cpp.
{
    return visit_items( [&func]( item * it, item * ) {
        return func( it );
    } );
}
References visitable< T >::visit_items().
visit_items() [4/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> & func)
Traverses this object and any child items contained using a visitor pattern.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any)
The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Definition at line 422 of file visitable.cpp.
{
    auto it = static_cast<item *>( this );
    return visit_internal( func, it );
}
References visit_internal().
Referenced by inventory_selector::add_character_items(), emit_radio_signal(), character_funcs::find_reloadables(), inventory::get_binned_items(), and get_item_location().
Friends And Related Function Documentation
find_parent() [1/2]
template<typename T > item * find_parent (const item & it) related
Definition at line 49 of file visitable.cpp.
{
    item *res = nullptr;
    if( visit_items( [&]( item * node, item * parent ) {
    if( node == &it ) {
            res = parent;
            return VisitResponse::ABORT;
        }
        return VisitResponse::NEXT;
    } ) != VisitResponse::ABORT ) {
        debugmsg( "Tried to find item parent using an object that doesn't contain it" );
    }
    return res;
}
Referenced by visitable< Character >::has_quality(), and visitable< T >::parents().
find_parent() [2/2]
template<typename T > const item * find_parent (const item & it) const related
Definition at line 66 of file visitable.cpp.
{
    return const_cast<visitable<T> *>( this )->find_parent( it );
}
items_with() [1/2]
template<typename T > std::vector< item * > items_with (const std::function< bool(const item &)> & filter) related
Definition at line 324 of file visitable.cpp.
{
    std::vector<item *> res;
    visit_items( [&res, &filter]( item * node, item * ) {
        if( filter( *node ) ) {
            res.push_back( node );
        }
        return VisitResponse::NEXT;
    } );
    return res;
}
Referenced by conditional_t< T >::set_has_item_category().
items_with() [2/2]
template<typename T > std::vector< const item * > items_with (const std::function< bool(const item &)> & filter) const related
Definition at line 339 of file visitable.cpp.
{
    std::vector<const item *> res;
    visit_items( [&res, &filter]( const item * node, const item * ) {
        if( filter( *node ) ) {
            res.push_back( node );
        }
        return VisitResponse::NEXT;
    } );
    return res;
}
parents() [1/2]
template<typename T > std::vector< item * > parents (const item & it) related
Definition at line 73 of file visitable.cpp.
{
    std::vector<item *> res;
    for( item *obj = find_parent( it ); obj; obj = find_parent( *obj ) ) {
        res.push_back( obj );
    }
    return res;
}
Referenced by pickup::pick_up().
parents() [2/2]
template<typename T > std::vector< const item * > parents (const item & it) const related
Definition at line 84 of file visitable.cpp.
{
    std::vector<const item *> res;
    for( const item *obj = find_parent( it ); obj; obj = find_parent( *obj ) ) {
        res.push_back( obj );
    }
    return res;
}
remove_items_with()
std::list< item > remove_items_with (const std::function< bool(const item &e)> & filter, int count) related
Definition at line 596 of file visitable.cpp.
{
    item *it = static_cast<item *>( this );
    std::list<item> res;
    if( count <= 0 ) {
        // nothing to do
        return res;
    }
    it->contents.remove_internal( filter, count, res );
    return res;
}
References item::contents, detail::count(), and item_contents::remove_internal().
Referenced by visitable< T >::remove_item().
visit_items() [1/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(const item *)> & func) const related
Definition at line 363 of file visitable.cpp.
{
    return const_cast<visitable<T> *>( this )->visit_items(
               static_cast<const std::function<VisitResponse( item * )>&>( func ) );
}
visit_items() [2/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> & func) const related
Definition at line 354 of file visitable.cpp.
{
    return const_cast<visitable<T> *>( this )->visit_items(
               static_cast<const std::function<VisitResponse( item *, item * )>&>( func ) );
}
Referenced by visitable< Character >::has_amount(), visitable< T >::has_item_with(), visitable< T >::items_with(), and visitable< T >::visit_items().
visit_items() [3/4]
template<typename T > VisitResponse visit_items (const std::function< VisitResponse(item *)> & func) related
Definition at line 371 of file visitable.cpp.
{
    return visit_items( [&func]( item * it, item * ) {
        return func( it );
    } );
}
visit_items() [4/4]
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> & func) related
Definition at line 422 of file visitable.cpp.
{
    auto it = static_cast<item *>( this );
    return visit_internal( func, it );
}
The documentation for this class was generated from the following files:
src/map.h
src/visitable.h
src/visitable.cpp