Cataclysm BN: enzlave_actor Class Reference
enzlave_actor Class Reference
Makes a zombie corpse into a zombie slave.
#include <iuse_actor.h>
Public Member Functions
enzlave_actor (const std::string &type="enzlave")
~enzlave_actor () override=default
void load (const JsonObject &obj) override
int use (player &, item &, bool, const tripoint &) const override
ret_val< bool > can_use (const Character &, const item &, bool, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Makes a zombie corpse into a zombie slave.
Definition at line 669 of file iuse_actor.h.
Constructor & Destructor Documentation
enzlave_actor()
enzlave_actor::enzlave_actor (const std::string & type = "enzlave") inline
Definition at line 672 of file iuse_actor.h.
: iuse_actor(type) {}
~enzlave_actor()
enzlave_actor::~enzlave_actor () override default
Member Function Documentation
can_use()
ret_val< bool > enzlave_actor::can_use (const Character & p, const item & , bool , const tripoint &) const override virtual
Survival >=1 allows enzlavement Firstaid >=1 allows enzlavement
Reimplemented from iuse_actor.
Definition at line 2139 of file iuse_actor.cpp.
{
    /** @EFFECT_SURVIVAL >=1 allows enzlavement */
    /** @EFFECT_FIRSTAID >=1 allows enzlavement */
    // TODO: Extract such checks into some kind of 'stat_requirements' class.
    if( p.get_skill_level( skill_survival ) < 1 ) {
        //~ %s - name of the required skill.
        return ret_val<bool>::make_failure( _( "You need at least %s 1." ),
                                            skill_survival->name() );
    }
    if( p.is_mounted() ) {
        return ret_val<bool>::make_failure( _( "You cannot do that while mounted." ) );
    }
    if( p.get_skill_level( skill_firstaid ) < 1 ) {
        //~ %s - name of the required skill.
        return ret_val<bool>::make_failure( _( "You need at least %s 1." ),
                                            skill_firstaid->name() );
    }
    return ret_val<bool>::make_success();
}
References _, Character::get_skill_level(), Character::is_mounted(), ret_val< T >::make_failure(), ret_val< T >::make_success(), Skill::name(), skill_firstaid, and skill_survival.
clone()
std::unique_ptr< iuse_actor > enzlave_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2018 of file iuse_actor.cpp.
{
    return std::make_unique<enzlave_actor>( *this );
}
load()
void enzlave_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2013 of file iuse_actor.cpp.
{
    assign( obj, "cost", cost );
}
References assign(), and iuse_actor::cost.
use()
int enzlave_actor::use (player & p, item & it, bool t, const tripoint &) const override virtual
Survival increases tolerance for enzlavement Survival decreases moral penalty and duration for enzlavement Dexterity increases chance of success for enzlavement Survival increases chance of success for enzlavement Firstaid increases chance of success for enzlavement Firstaid speeds up enzlavement
Implements iuse_actor.
Definition at line 2023 of file iuse_actor.cpp.
{
    if( t ) {
        return 0;
    }
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    map_stack items = get_map().i_at( point( p.posx(), p.posy() ) );
    std::vector<const item *> corpses;
    for( item &corpse_candidate : items ) {
        const mtype *mt = corpse_candidate.get_mtype();
        if( corpse_candidate.is_corpse() && mt->in_species( ZOMBIE ) &&
            mt->made_of( material_id( "flesh" ) ) &&
            mt->in_species( HUMAN ) && corpse_candidate.active && !corpse_candidate.has_var( "zlave" ) ) {
            corpses.push_back( &corpse_candidate );
        }
    }
    if( corpses.empty() ) {
        p.add_msg_if_player( _( "No suitable corpses" ) );
        return 0;
    }
    int tolerance_level = 9;
    if( p.has_trait( trait_PSYCHOPATH ) || p.has_trait( trait_SAPIOVORE ) ) {
        tolerance_level = 0;
    } else if( p.has_trait_flag( "PRED4" ) ) {
        tolerance_level = 5;
    } else if( p.has_trait_flag( "PRED3" ) ) {
        tolerance_level = 7;
    }
    // Survival skill increases your willingness to get things done,
    // but it doesn't make you feel any less bad about it.
    /** @EFFECT_SURVIVAL increases tolerance for enzlavement */
    if( p.get_morale_level() <= ( 15 * ( tolerance_level - p.get_skill_level(
            skill_survival ) ) ) - 150 ) {
        add_msg( m_neutral,
                 _( "The prospect of cutting up the corpse and letting it rise again as a slave is too much for you to deal with right now." ) );
        return 0;
    }
    uilist amenu;
    amenu.text = _( "Selectively butcher the downed zombie into a zombie slave?" );
    for( size_t i = 0; i < corpses.size(); i++ ) {
        amenu.addentry( i, true, -1, corpses[i]->display_name() );
    }
    amenu.query();
    if( amenu.ret < 0 ) {
        p.add_msg_if_player( _( "Make love, not zlave." ) );
        return 0;
    }
    if( tolerance_level == 0 ) {
        // You just don't care, no message.
    } else if( tolerance_level <= 5 ) {
        add_msg( m_neutral, _( "Well, it's more constructive than just chopping 'em into gooey meat…" ) );
    } else {
        add_msg( m_bad, _( "You feel horrible for mutilating and enslaving someone's corpse." ) );
        /** @EFFECT_SURVIVAL decreases moral penalty and duration for enzlavement */
        int moraleMalus = -50 * ( 5.0 / p.get_skill_level( skill_survival ) );
        int maxMalus = -250 * ( 5.0 / p.get_skill_level( skill_survival ) );
        time_duration duration = 30_minutes * ( 5.0 / p.get_skill_level( skill_survival ) );
        time_duration decayDelay = 3_minutes * ( 5.0 / p.get_skill_level( skill_survival ) );
        if( p.has_trait( trait_PACIFIST ) ) {
            moraleMalus *= 5;
            maxMalus *= 3;
        } else if( p.has_trait_flag( "PRED1" ) ) {
            moraleMalus /= 4;
        } else if( p.has_trait_flag( "PRED2" ) ) {
            moraleMalus /= 5;
        }
        p.add_morale( MORALE_MUTILATE_CORPSE, moraleMalus, maxMalus, duration, decayDelay );
    }
    const int selected_corpse = amenu.ret;
    const item *body = corpses[selected_corpse];
    const mtype *mt = body->get_mtype();
    // HP range for zombies is roughly 36 to 120, with the really big ones having 180 and 480 hp.
    // Speed range is 20 - 120 (for humanoids, dogs get way faster)
    // This gives us a difficulty ranging roughly from 10 - 40, with up to +25 for corpse damage.
    // An average zombie with an undamaged corpse is 0 + 8 + 14 = 22.
    int difficulty = ( body->damage_level( 4 ) * 5 ) + ( mt->hp / 10 ) + ( mt->speed / 5 );
    // 0 - 30
    /** @EFFECT_DEX increases chance of success for enzlavement */
    /** @EFFECT_SURVIVAL increases chance of success for enzlavement */
    /** @EFFECT_FIRSTAID increases chance of success for enzlavement */
    int skills = p.get_skill_level( skill_survival ) + p.get_skill_level( skill_firstaid ) +
                 ( p.dex_cur / 2 );
    skills *= 2;
    int success = rng( 0, skills ) - rng( 0, difficulty );
    /** @EFFECT_FIRSTAID speeds up enzlavement */
    const int moves = difficulty * to_moves<int>( 12_seconds ) / p.get_skill_level( skill_firstaid );
    p.assign_activity( ACT_MAKE_ZLAVE, moves );
    p.activity.values.push_back( success );
    p.activity.str_values.push_back( corpses[selected_corpse]->display_name() );
    return cost >= 0 ? cost : it.ammo_required();
}
References _, ACT_MAKE_ZLAVE, Character::activity, Character::add_morale(), add_msg(), player::add_msg_if_player(), uilist::addentry(), item::ammo_required(), Character::assign_activity(), Creature::body, iuse_actor::cost, Character::dex_cur, get_map(), Character::get_morale_level(), Character::get_skill_level(), Character::has_trait(), Character::has_trait_flag(), mtype::hp, HUMAN, map::i_at(), mtype::in_species(), Character::is_mounted(), m_bad, m_info, m_neutral, mtype::made_of(), MORALE_MUTILATE_CORPSE, Creature::moves, Character::posx(), Character::posy(), uilist::query(), uilist::ret, rng(), skill_firstaid, skill_survival, mtype::speed, player_activity::str_values, behavior::success, uilist::text, trait_PACIFIST, trait_PSYCHOPATH, trait_SAPIOVORE, player_activity::values, and ZOMBIE.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp