Cataclysm BN: mattack_actor Class Reference
mattack_actor Class Reference abstract
#include <mattack_common.h>
Public Member Functions
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
virtual bool call (monster &) const =0
virtual std::unique_ptr< mattack_actor > clone () const =0
virtual void load_internal (const JsonObject &jo, const std::string &src)=0
Public Attributes
mattack_id id
bool was_loaded = false
int cooldown = 0
Protected Member Functions
mattack_actor ()=default
Detailed Description
Definition at line 17 of file mattack_common.h.
Constructor & Destructor Documentation
mattack_actor() [1/2]
mattack_actor::mattack_actor () protected default
mattack_actor() [2/2]
mattack_actor::mattack_actor (const mattack_id & new_id) inline
Definition at line 22 of file mattack_common.h.
: id(new_id) { }
~mattack_actor()
virtual mattack_actor::~mattack_actor () virtual default
Member Function Documentation
call()
virtual bool mattack_actor::call (monster &) const pure virtual
Implemented in leap_actor, mon_spellcasting_actor, melee_actor, gun_actor, and mattack_hardcoded_wrapper.
clone()
virtual std::unique_ptr< mattack_actor > mattack_actor::clone () const pure virtual
Implemented in leap_actor, mon_spellcasting_actor, melee_actor, bite_actor, gun_actor, and mattack_hardcoded_wrapper.
load()
void mattack_actor::load (const JsonObject & jo, const std::string & src)
Definition at line 1053 of file monstergenerator.cpp.
{
    const bool strict = is_strict_enabled( src );
    // Legacy support
    if( !jo.has_string( "id" ) ) {
        id = jo.get_string( "type" );
    } else {
        // Loading ids can't be strict at the moment, since it has to match the stored version
        assign( jo, "id", id, false );
    }
    assign( jo, "cooldown", cooldown, strict );
    load_internal( jo, src );
    // Set was_loaded manually because we don't have generic_factory to do it for us
    was_loaded = true;
}
References assign(), cooldown, JsonObject::get_string(), JsonObject::has_string(), is_strict_enabled(), load_internal(), and was_loaded.
load_internal()
virtual void mattack_actor::load_internal (const JsonObject & jo, const std::string & src) pure virtual
Implemented in mattack_hardcoded_wrapper, leap_actor, mon_spellcasting_actor, melee_actor, bite_actor, and gun_actor.
Referenced by load().
Member Data Documentation
cooldown
int mattack_actor::cooldown = 0
Definition at line 27 of file mattack_common.h.
Referenced by load().
id
mattack_id mattack_actor::id
Definition at line 24 of file mattack_common.h.
Referenced by MonsterGenerator::add_attack(), and mtype::add_special_attack().
was_loaded
bool mattack_actor::was_loaded = false
Definition at line 25 of file mattack_common.h.
Referenced by load(), mon_spellcasting_actor::load_internal(), and melee_actor::load_internal().
The documentation for this class was generated from the following files:
src/mattack_common.h
src/monstergenerator.cpp