Cataclysm BN: dig_activity_actor Class Reference
dig_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
dig_activity_actor (int dig_moves, const tripoint &dig_loc, const std::string &resulting_ter, const tripoint &dump_loc, int dump_spawn_count, const std::string &dump_item_group)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual act_progress_message get_progress_message (const player_activity &, const Character &) const
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonIn &jsin)
Private Member Functions
bool equivalent_activity (const dig_activity_actor &other) const
Returns true if other and this are "equivalent" in the sense that this can be resumed instead of starting other.
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Private Attributes
int moves_total
tripoint location
location of the dig
std::string result_terrain
tripoint byproducts_location
int byproducts_count
std::string byproducts_item_group
Detailed Description
Definition at line 111 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
dig_activity_actor()
dig_activity_actor::dig_activity_actor (int dig_moves, const tripoint & dig_loc, const std::string & resulting_ter, const tripoint & dump_loc, int dump_spawn_count, const std::string & dump_item_group) inline
Definition at line 143 of file activity_actor_definitions.h.
         :
            moves_total( dig_moves ), location( dig_loc ),
            result_terrain( resulting_ter ),
            byproducts_location( dump_loc ),
            byproducts_count( dump_spawn_count ),
            byproducts_item_group( dump_item_group ) {}
Member Function Documentation
can_resume_with_internal()
bool dig_activity_actor::can_resume_with_internal (const activity_actor & other, const Character &) const inline override private virtual
Precondition
other is a dig_activity_actor
Reimplemented from activity_actor.
Definition at line 137 of file activity_actor_definitions.h.
{
            const dig_activity_actor &d_actor = static_cast<const dig_activity_actor &>( other );
            return equivalent_activity( d_actor );
        }
References equivalent_activity(), and other.
clone()
std::unique_ptr< activity_actor > dig_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 162 of file activity_actor_definitions.h.
{
            return std::make_unique<dig_activity_actor>( *this );
        }
deserialize()
std::unique_ptr< activity_actor > dig_activity_actor::deserialize (JsonIn & jsin) static
Definition at line 486 of file activity_actor.cpp.
{
    dig_activity_actor actor( 0, tripoint_zero,
                              {}, tripoint_zero, 0, {} );
    JsonObject data = jsin.get_object();
    data.read( "moves", actor.moves_total );
    data.read( "location", actor.location );
    data.read( "result_terrain", actor.result_terrain );
    data.read( "byproducts_location", actor.byproducts_location );
    data.read( "byproducts_count", actor.byproducts_count );
    data.read( "byproducts_item_group", actor.byproducts_item_group );
    return actor.clone();
}
References JsonIn::get_object(), JsonObject::read(), and tripoint_zero.
do_turn()
void dig_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 406 of file activity_actor.cpp.
{
    sfx::play_activity_sound( "tool", "shovel", sfx::get_heard_volume( location ) );
    if( calendar::once_every( 1_minutes ) ) {
        //~ Sound of a shovel digging a pit at work!
        sounds::sound( location, 10, sounds::sound_t::activity, _( "hsh!" ) );
    }
}
References _, sounds::activity, sfx::get_heard_volume(), location, calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
equivalent_activity()
bool dig_activity_actor::equivalent_activity (const dig_activity_actor & other) const inline private
Returns true if other and this are "equivalent" in the sense that this can be resumed instead of starting other.
Definition at line 126 of file activity_actor_definitions.h.
{
            return  location == other.location &&
                    result_terrain == other.result_terrain &&
                    byproducts_location == other.byproducts_location &&
                    byproducts_count == other.byproducts_count &&
                    byproducts_item_group == other.byproducts_item_group;
        }
References byproducts_count, byproducts_item_group, byproducts_location, location, other, and result_terrain.
Referenced by can_resume_with_internal().
finish()
void dig_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 415 of file activity_actor.cpp.
{
    map &here = get_map();
    const bool grave = here.ter( location ) == t_grave;
    if( grave ) {
        if( one_in( 10 ) ) {
            static const std::array<mtype_id, 5> monids = { {
                    mon_zombie, mon_zombie_fat,
                    mon_zombie_rot, mon_skeleton,
                    mon_zombie_crawler
                }
            };
            g->place_critter_at( random_entry( monids ), byproducts_location );
            here.furn_set( location, f_coffin_o );
            who.add_msg_if_player( m_warning, _( "Something crawls out of the coffin!" ) );
        } else {
            here.spawn_item( location, itype_bone_human, rng( 5, 15 ) );
            here.furn_set( location, f_coffin_c );
        }
        std::vector<item *> dropped = g->m.place_items( item_group_id( "allclothes" ), 50, location,
                                      location, false,
                                      calendar::turn );
        g->m.place_items( item_group_id( "grave" ), 25, location, location, false, calendar::turn );
        g->m.place_items( item_group_id( "jewelry_front" ), 20, location, location, false, calendar::turn );
        for( item * const &it : dropped ) {
            if( it->is_armor() ) {
                it->item_tags.insert( "FILTHY" );
                it->set_damage( rng( 1, it->max_damage() - 1 ) );
            }
        }
        g->events().send<event_type::exhumes_grave>( who.getID() );
    }
    here.ter_set( location, ter_id( result_terrain ) );
    for( int i = 0; i < byproducts_count; i++ ) {
        here.spawn_items( byproducts_location,
                          item_group::items_from( item_group_id( byproducts_item_group ),
                                  calendar::turn ) );
    }
    const int helpersize = g->u.get_crafting_helpers( 3 ).size();
    who.mod_stored_nutr( 5 - helpersize );
    who.mod_thirst( 5 - helpersize );
    who.mod_fatigue( 10 - ( helpersize * 2 ) );
    if( grave ) {
        who.add_msg_if_player( m_good, _( "You finish exhuming a grave." ) );
    } else {
        who.add_msg_if_player( m_good, _( "You finish digging the %s." ),
                               here.ter( location ).obj().name() );
    }
    act.set_to_null();
}
References _, act, Creature::add_msg_if_player(), byproducts_count, byproducts_item_group, byproducts_location, exhumes_grave, f_coffin_c, f_coffin_o, map::furn_set(), g, get_map(), Character::getID(), item_group::items_from(), itype_bone_human, location, m_good, m_warning, Character::mod_fatigue(), Character::mod_stored_nutr(), Character::mod_thirst(), mon_skeleton, mon_zombie, mon_zombie_crawler, mon_zombie_fat, mon_zombie_rot, map_data_common_t::name(), int_id< T >::obj(), one_in(), random_entry(), result_terrain, rng(), map::spawn_item(), map::spawn_items(), t_grave, map::ter(), ter_id, map::ter_set(), and calendar::turn.
get_type()
activity_id dig_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 154 of file activity_actor_definitions.h.
{
            return activity_id( "ACT_DIG" );
        }
serialize()
void dig_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 472 of file activity_actor.cpp.
{
    jsout.start_object();
    jsout.member( "moves", moves_total );
    jsout.member( "location", location );
    jsout.member( "result_terrain", result_terrain );
    jsout.member( "byproducts_location", byproducts_location );
    jsout.member( "byproducts_count", byproducts_count );
    jsout.member( "byproducts_item_group", byproducts_item_group );
    jsout.end_object();
}
References byproducts_count, byproducts_item_group, byproducts_location, JsonOut::end_object(), location, JsonOut::member(), moves_total, result_terrain, and JsonOut::start_object().
start()
void dig_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 400 of file activity_actor.cpp.
{
    act.moves_total = moves_total;
    act.moves_left = moves_total;
}
References act, and moves_total.
Member Data Documentation
byproducts_count
int dig_activity_actor::byproducts_count private
Definition at line 119 of file activity_actor_definitions.h.
Referenced by equivalent_activity(), finish(), and serialize().
byproducts_item_group
std::string dig_activity_actor::byproducts_item_group private
Definition at line 120 of file activity_actor_definitions.h.
Referenced by equivalent_activity(), finish(), and serialize().
byproducts_location
tripoint dig_activity_actor::byproducts_location private
Definition at line 118 of file activity_actor_definitions.h.
Referenced by equivalent_activity(), finish(), and serialize().
location
tripoint dig_activity_actor::location private
location of the dig
Definition at line 116 of file activity_actor_definitions.h.
Referenced by do_turn(), equivalent_activity(), finish(), and serialize().
moves_total
int dig_activity_actor::moves_total private
Definition at line 114 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
result_terrain
std::string dig_activity_actor::result_terrain private
Definition at line 117 of file activity_actor_definitions.h.
Referenced by equivalent_activity(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp