Cataclysm BN: item_reader Class Reference
item_reader Class Reference
Public Member Functions
profession::itypedec get_next (JsonIn &jin) const
template<typename C >
void erase_next (JsonIn &jin, C &container) const
Public Member Functions inherited from generic_typed_reader< item_reader >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Detailed Description
Definition at line 121 of file profession.cpp.
Member Function Documentation
erase_next()
template<typename C > void item_reader::erase_next (JsonIn & jin, C & container) const inline
Definition at line 136 of file profession.cpp.
{
            const std::string id = jin.get_string();
            reader_detail::handler<C>().erase_if( container, [&id]( const profession::itypedec & e ) {
                return e.type_id.str() == id;
            } );
        }
References JsonIn::get_string(), string_id< T >::str(), and profession::itypedec::type_id.
get_next()
profession::itypedec item_reader::get_next (JsonIn & jin) const inline
Definition at line 124 of file profession.cpp.
{
            // either a plain item type id string, or an array with item type id
            // and as second entry the item description.
            if( jin.test_string() ) {
                return profession::itypedec( jin.get_string() );
            }
            JsonArray jarr = jin.get_array();
            const auto id = jarr.get_string( 0 );
            const snippet_id snippet( jarr.get_string( 1 ) );
            return profession::itypedec( id, snippet );
        }
References JsonIn::get_array(), JsonIn::get_string(), JsonArray::get_string(), and JsonIn::test_string().
The documentation for this class was generated from the following file:
src/profession.cpp