Cataclysm BN: ma_skill_reader Class Reference
ma_skill_reader Class Reference
Public Member Functions
std::pair< skill_id, int > get_next (JsonIn &jin) const
template<typename C >
void erase_next (JsonIn &jin, C &container) const
Public Member Functions inherited from generic_typed_reader< ma_skill_reader >
void insert_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void insert_next (JsonIn &jin, C &container) const
void erase_values_from (const JsonObject &jo, const std::string &member_name, C &container) const
void erase_next (JsonIn &jin, C &container) const
bool operator() (const JsonObject &jo, const std::string &member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string &member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string &name, C &) const
bool do_relative (const JsonObject &jo, const std::string &name, C &member) const
bool read_normal (const JsonObject &jo, const std::string &name, C &member) const
Detailed Description
Definition at line 85 of file martialarts.cpp.
Member Function Documentation
erase_next()
template<typename C > void ma_skill_reader::erase_next (JsonIn & jin, C & container) const inline
Definition at line 93 of file martialarts.cpp.
{
            const skill_id id = skill_id( jin.get_string() );
            reader_detail::handler<C>().erase_if( container, [&id]( const std::pair<skill_id, int> &e ) {
                return e.first == id;
            } );
        }
References JsonIn::get_string(), base_camps::id, and skill_id.
get_next()
std::pair< skill_id, int > ma_skill_reader::get_next (JsonIn & jin) const inline
Definition at line 88 of file martialarts.cpp.
{
            JsonObject jo = jin.get_object();
            return std::pair<skill_id, int>( skill_id( jo.get_string( "name" ) ), jo.get_int( "level" ) );
        }
References JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), and skill_id.
The documentation for this class was generated from the following file:
src/martialarts.cpp