Cataclysm BN: weapon_inventory_preset Class Reference
weapon_inventory_preset Class Reference
Public Member Functions
weapon_inventory_preset (const player &p)
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool is_shown (const item_location &) const
Does this entry satisfy the basic preset conditions?
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
Private Member Functions
bool deals_melee_damage (const item &it) const
std::string get_damage_string (float damage, bool display_zeroes=false) const
Private Attributes
const player & p
Additional Inherited Members
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
Detailed Description
Definition at line 1249 of file game_inventory.cpp.
Constructor & Destructor Documentation
weapon_inventory_preset()
weapon_inventory_preset::weapon_inventory_preset (const player & p) inline
Definition at line 1252 of file game_inventory.cpp.
                                                   : p( p ) {
            append_cell( [ this ]( const item_location & loc ) {
                if( !loc->is_gun() ) {
                    return std::string();
                }
                const int total_damage = loc->gun_damage( true ).total_damage();
                if( loc->ammo_data() && loc->ammo_remaining() ) {
                    const int basic_damage = loc->gun_damage( false ).total_damage();
                    if( loc->ammo_data()->ammo->damage.damage_units.front().damage_multiplier != 1.0f ) {
                        const float ammo_mult =
                            loc->ammo_data()->ammo->damage.damage_units.front().damage_multiplier;
                        return string_format( "%s<color_light_gray>*</color>%s <color_light_gray>=</color> %s",
                                              get_damage_string( basic_damage, true ),
                                              get_damage_string( ammo_mult, true ),
                                              get_damage_string( total_damage, true )
                                            );
                    } else {
                        const int ammo_damage = loc->ammo_data()->ammo->damage.total_damage();
                        return string_format( "%s<color_light_gray>+</color>%s <color_light_gray>=</color> %s",
                                              get_damage_string( basic_damage, true ),
                                              get_damage_string( ammo_damage, true ),
                                              get_damage_string( total_damage, true )
                                            );
                    }
                } else {
                    return get_damage_string( total_damage );
                }
            }, pgettext( "Shot as damage", "SHOT" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_damage_string( loc->damage_melee( DT_BASH ) );
            }, _( "BASH" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_damage_string( loc->damage_melee( DT_CUT ) );
            }, _( "CUT" ) );
            append_cell( [ this ]( const item_location & loc ) {
                return get_damage_string( loc->damage_melee( DT_STAB ) );
            }, _( "STAB" ) );
            append_cell( [ this ]( const item_location & loc ) {
                if( deals_melee_damage( *loc ) ) {
                    return good_bad_none( loc->type->m_to_hit );
                }
                return std::string();
            }, _( "MELEE" ) );
            append_cell( [ this ]( const item_location & loc ) {
                if( deals_melee_damage( *loc ) ) {
                    return string_format( "<color_yellow>%d</color>", this->p.attack_cost( *loc ) );
                }
                return std::string();
            }, _( "MOVES" ) );
        }
References item::ammo_data(), item::ammo_remaining(), inventory_selector_preset::append_cell(), get_damage_string(), item::gun_damage(), item::is_gun(), and damage_instance::total_damage().
Member Function Documentation
deals_melee_damage()
bool weapon_inventory_preset::deals_melee_damage (const item & it) const inline private
Definition at line 1323 of file game_inventory.cpp.
{
            return it.damage_melee( DT_BASH ) || it.damage_melee( DT_CUT ) || it.damage_melee( DT_STAB );
        }
References item::damage_melee(), DT_BASH, DT_CUT, and DT_STAB.
get_damage_string()
std::string weapon_inventory_preset::get_damage_string (float damage, bool display_zeroes = false) const inline private
Definition at line 1327 of file game_inventory.cpp.
{
            return damage ||
                   display_zeroes ? string_format( "<color_yellow>%g</color>", damage ) : std::string();
        }
References string_format().
Referenced by weapon_inventory_preset().
get_denial()
std::string weapon_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Reimplemented in saw_barrel_inventory_preset.
Definition at line 1312 of file game_inventory.cpp.
{
            const auto ret = p.can_wield( *loc );
            if( !ret.success() ) {
                return trim_punctuation_marks( ret.str() );
            }
            return std::string();
        }
References player::can_wield(), cata::hash64_detail::ret, and trim_punctuation_marks().
Member Data Documentation
p
const player& weapon_inventory_preset::p private
Definition at line 1332 of file game_inventory.cpp.
The documentation for this class was generated from the following file:
src/game_inventory.cpp