Cataclysm BN: charger_tile Class Reference
charger_tile Class Reference
#include <active_tile_data_def.h>
Public Member Functions
void update_internal (time_point to, const tripoint_abs_ms &p, distribution_grid &grid) override
active_tile_data * clone () const override
const std::string & get_type () const override
void store (JsonOut &jsout) const override
void load (JsonObject &jo) override
Public Member Functions inherited from active_tile_data
void update (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)
time_point get_last_updated ()
void set_last_updated (time_point t)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
virtual ~active_tile_data ()
Public Attributes
int power
Additional Inherited Members
Static Public Member Functions inherited from active_tile_data
static active_tile_data * create (const std::string &id)
Detailed Description
Definition at line 51 of file active_tile_data_def.h.
Member Function Documentation
clone()
active_tile_data * charger_tile::clone () const override virtual
Implements active_tile_data.
Definition at line 286 of file active_tile_data.cpp.
{
    return new charger_tile( *this );
}
get_type()
const std::string & charger_tile::get_type () const override virtual
Implements active_tile_data.
Definition at line 291 of file active_tile_data.cpp.
{
    static const std::string type( "charger" );
    return type;
}
References type.
load()
void charger_tile::load (JsonObject & jo) override virtual
Implements active_tile_data.
Definition at line 302 of file active_tile_data.cpp.
{
    jo.read( "power", power );
}
References power, and JsonObject::read().
store()
void charger_tile::store (JsonOut & jsout) const override virtual
Implements active_tile_data.
Definition at line 297 of file active_tile_data.cpp.
{
    jsout.member( "power", power );
}
References JsonOut::member(), and power.
update_internal()
void charger_tile::update_internal (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) override virtual
Parameters
to the time to update to
p absolute map coordinates (map::getabs) of the tile being updated
grid distribution grid being updated, containing the tile being updated
Implements active_tile_data.
Definition at line 246 of file active_tile_data.cpp.
{
    tripoint_abs_sm p_abs_sm;
    point_sm_ms p_within_sm;
    std::tie( p_abs_sm, p_within_sm ) = project_remain<coords::sm>( p );
    submap *sm = MAPBUFFER.lookup_submap( p_abs_sm );
    if( sm == nullptr ) {
        return;
    }
    std::int64_t power = this->power * to_seconds<std::int64_t>( to - get_last_updated() );
    // TODO: Make not a copy from map.cpp
    for( item &outer : sm->get_items( p_within_sm.raw() ) ) {
        outer.visit_items( [&power, &grid]( item * it ) {
            item &n = *it;
            if( !n.has_flag( flag_RECHARGE ) && !n.has_flag( flag_USE_UPS ) ) {
                return VisitResponse::NEXT;
            }
            if( n.ammo_capacity() > n.ammo_remaining() ||
                ( n.type->battery && n.type->battery->max_capacity > n.energy_remaining() ) ) {
                while( power >= 1000 || x_in_y( power, 1000 ) ) {
                    const int missing = grid.mod_resource( -1 );
                    if( missing == 0 ) {
                        if( n.is_battery() ) {
                            n.mod_energy( 1_kJ );
                        } else {
                            n.ammo_set( itype_battery, n.ammo_remaining() + 1 );
                        }
                    }
                    power -= 1000;
                }
                return VisitResponse::ABORT;
            }
            return VisitResponse::SKIP;
        } );
    }
}
References ABORT, item::ammo_capacity(), item::ammo_remaining(), itype::battery, item::energy_remaining(), flag_RECHARGE(), flag_USE_UPS(), active_tile_data::get_last_updated(), item::has_flag(), mapbuffer::lookup_submap(), MAPBUFFER, power, coords::coord_point< Point, Origin, Scale >::raw(), SKIP, coords::sm, and item::type.
Member Data Documentation
power
int charger_tile::power
Definition at line 55 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
The documentation for this class was generated from the following files:
src/active_tile_data_def.h
src/active_tile_data.cpp