Cataclysm BN: relic Class Reference
relic Class Reference
#include <relic.h>
Public Member Functions
bool operator== (const relic &rhs) const
std::string name () const
int activate (Creature &caster, const tripoint &target) const
void load (const JsonObject &jo)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
void add_passive_effect (const enchantment &ench)
void add_active_effect (const fake_spell &sp)
void add_recharge_scheme (const relic_recharge &r)
const std::vector< enchantment > & get_enchantments () const
const std::vector< relic_recharge > & get_recharge_scheme () const
void check () const
Private Attributes
std::vector< fake_spell > active_effects
std::vector< enchantment > passive_effects
std::vector< relic_recharge > recharge_scheme
translation item_name_override
int charges_per_activation
int moves
Detailed Description
Definition at line 102 of file relic.h.
Member Function Documentation
activate()
int relic::activate (Creature & caster, const tripoint & target) const
Definition at line 239 of file relic.cpp.
{
    caster.moves -= moves;
    for( const fake_spell &sp : active_effects ) {
        sp.get_spell( sp.level ).cast_all_effects( caster, target );
    }
    return charges_per_activation;
}
References active_effects, charges_per_activation, Creature::moves, and moves.
add_active_effect()
void relic::add_active_effect (const fake_spell & sp)
Definition at line 143 of file relic.cpp.
{
    active_effects.emplace_back( sp );
}
References active_effects.
Referenced by load().
add_passive_effect()
void relic::add_passive_effect (const enchantment & ench)
Definition at line 148 of file relic.cpp.
{
    for( enchantment &ench : passive_effects ) {
        if( ench.add( nench ) ) {
            return;
        }
    }
    passive_effects.emplace_back( nench );
}
References passive_effects.
Referenced by load().
add_recharge_scheme()
void relic::add_recharge_scheme (const relic_recharge & r)
Definition at line 158 of file relic.cpp.
{
    recharge_scheme.emplace_back( r );
}
References recharge_scheme.
Referenced by load().
check()
void relic::check () const
Definition at line 263 of file relic.cpp.
{
    for( const enchantment &ench : passive_effects ) {
        ench.check();
    }
    for( const relic_recharge &rech : recharge_scheme ) {
        rech.check();
    }
}
References passive_effects, and recharge_scheme.
deserialize()
void relic::deserialize (JsonIn & jsin)
Definition at line 194 of file relic.cpp.
{
    JsonObject jobj = jsin.get_object();
    load( jobj );
}
References JsonIn::get_object(), and load().
get_enchantments()
const std::vector< enchantment > & relic::get_enchantments () const inline
Definition at line 131 of file relic.h.
{
            return passive_effects;
        }
References passive_effects.
get_recharge_scheme()
const std::vector< relic_recharge > & relic::get_recharge_scheme () const inline
Definition at line 134 of file relic.h.
{
            return recharge_scheme;
        }
References recharge_scheme.
load()
void relic::load (const JsonObject & jo)
Definition at line 163 of file relic.cpp.
{
    if( jo.has_array( "active_effects" ) ) {
        for( JsonObject jobj : jo.get_array( "active_effects" ) ) {
            fake_spell sp;
            sp.load( jobj );
            add_active_effect( sp );
        }
    }
    if( jo.has_array( "passive_effects" ) ) {
        for( JsonObject jobj : jo.get_array( "passive_effects" ) ) {
            enchantment ench;
            ench.load( jobj );
            if( !ench.id.is_empty() ) {
                ench = ench.id.obj();
            }
            add_passive_effect( ench );
        }
    }
    if( jo.has_array( "recharge_scheme" ) ) {
        for( JsonObject jobj : jo.get_array( "recharge_scheme" ) ) {
            relic_recharge recharge;
            recharge.load( jobj );
            add_recharge_scheme( recharge );
        }
    }
    jo.read( "name", item_name_override );
    charges_per_activation = jo.get_int( "charges_per_activation", 1 );
    moves = jo.get_int( "moves", 100 );
}
References add_active_effect(), add_passive_effect(), add_recharge_scheme(), charges_per_activation, JsonObject::get_array(), JsonObject::get_int(), JsonObject::has_array(), enchantment::id, string_id< T >::is_empty(), item_name_override, fake_spell::load(), relic_recharge::load(), enchantment::load(), moves, string_id< T >::obj(), and JsonObject::read().
Referenced by deserialize(), and Item_factory::load().
name()
std::string relic::name () const
Definition at line 258 of file relic.cpp.
{
    return item_name_override.translated();
}
References item_name_override, and translation::translated().
operator==()
bool relic::operator== (const relic & rhs) const
Definition at line 248 of file relic.cpp.
{
    return charges_per_activation == rhs.charges_per_activation &&
           moves == rhs.moves &&
           item_name_override == rhs.item_name_override &&
           active_effects == rhs.active_effects &&
           passive_effects == rhs.passive_effects &&
           recharge_scheme == rhs.recharge_scheme;
}
References active_effects, charges_per_activation, item_name_override, moves, passive_effects, and recharge_scheme.
serialize()
void relic::serialize (JsonOut & jsout) const
Definition at line 200 of file relic.cpp.
{
    jsout.start_object();
    jsout.member( "moves", moves );
    jsout.member( "charges_per_activation", charges_per_activation );
    // item_name_override is not saved, in case the original json text changes:
    // in such case names read back from a save wouold no longer be properly translated.
    if( !passive_effects.empty() ) {
        jsout.member( "passive_effects" );
        jsout.start_array();
        for( const enchantment &ench : passive_effects ) {
            ench.serialize( jsout );
        }
        jsout.end_array();
    }
    if( !active_effects.empty() ) {
        jsout.member( "active_effects" );
        jsout.start_array();
        for( const fake_spell &sp : active_effects ) {
            sp.serialize( jsout );
        }
        jsout.end_array();
    }
    if( !recharge_scheme.empty() ) {
        jsout.member( "recharge_scheme" );
        jsout.start_array();
        for( const relic_recharge &sp : recharge_scheme ) {
            sp.serialize( jsout );
        }
        jsout.end_array();
    }
    jsout.end_object();
}
References active_effects, charges_per_activation, JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), moves, passive_effects, recharge_scheme, JsonOut::start_array(), and JsonOut::start_object().
Member Data Documentation
active_effects
std::vector<fake_spell> relic::active_effects private
Definition at line 105 of file relic.h.
Referenced by activate(), add_active_effect(), operator==(), and serialize().
charges_per_activation
int relic::charges_per_activation private
Definition at line 112 of file relic.h.
Referenced by activate(), load(), operator==(), and serialize().
item_name_override
translation relic::item_name_override private
Definition at line 110 of file relic.h.
Referenced by load(), name(), and operator==().
moves
int relic::moves private
Definition at line 114 of file relic.h.
Referenced by activate(), load(), operator==(), and serialize().
passive_effects
std::vector<enchantment> relic::passive_effects private
Definition at line 106 of file relic.h.
Referenced by add_passive_effect(), check(), get_enchantments(), operator==(), and serialize().
recharge_scheme
std::vector<relic_recharge> relic::recharge_scheme private
Definition at line 107 of file relic.h.
Referenced by add_recharge_scheme(), check(), get_recharge_scheme(), operator==(), and serialize().
The documentation for this class was generated from the following files:
src/relic.h
src/relic.cpp