Cataclysm BN: jmapgen_vehicle Class Reference
jmapgen_vehicle Class Reference
Place a vehicle.
Public Member Functions
jmapgen_vehicle (const JsonObject &jsi)
void apply (mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (mapgendata &dat, const point &p) const override
Public Member Functions inherited from jmapgen_piece
virtual void check (const std::string &) const
Sanity-check this piece.
virtual ~jmapgen_piece ()=default
Public Attributes
vgroup_id type
jmapgen_int chance
std::vector< units::angle > rotation
int fuel
int status
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a vehicle.
"vehicle": id of the vehicle. "chance": chance of spawning the vehicle: 0...100 "rotation": rotation of the vehicle, see fuel: fuel status of the vehicle, see status: overall (damage) status of the vehicle, see vehicle::vehicle
Definition at line 1347 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_vehicle()
jmapgen_vehicle::jmapgen_vehicle (const JsonObject & jsi) inline
Definition at line 1355 of file mapgen.cpp.
                                                 :
            type( jsi.get_string( "vehicle" ) )
            , chance( jsi, "chance", 1, 1 )
            //, rotation( jsi.get_int( "rotation", 0 ) ) // unless there is a way for the json parser to
            // return a single int as a list, we have to manually check this in the constructor below
            , fuel( jsi.get_int( "fuel", -1 ) )
            , status( jsi.get_int( "status", -1 ) ) {
            if( jsi.has_array( "rotation" ) ) {
                for( const JsonValue &elt : jsi.get_array( "rotation" ) ) {
                    rotation.push_back( units::from_degrees( elt.get_int() ) );
                }
            } else {
                rotation.push_back( units::from_degrees( jsi.get_int( "rotation", 0 ) ) );
            }
            if( !type.is_valid() ) {
                set_mapgen_defer( jsi, "vehicle", "no such vehicle type or group" );
            }
        }
References units::from_degrees(), JsonObject::get_array(), JsonObject::get_int(), JsonObject::has_array(), string_id< T >::is_valid(), mapgen_defer::jsi, rotation, set_mapgen_defer(), and type.
Member Function Documentation
apply()
void jmapgen_vehicle::apply (mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1374 of file mapgen.cpp.
{
            if( !x_in_y( chance.get(), 100 ) ) {
                return;
            }
            dat.m.add_vehicle( type, point( x.get(), y.get() ), random_entry( rotation ), fuel, status );
        }
References map::add_vehicle(), chance, fuel, jmapgen_int::get(), mapgendata::m, random_entry(), rotation, status, type, and x_in_y().
has_vehicle_collision()
bool jmapgen_vehicle::has_vehicle_collision (mapgendata & dat, const point & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1380 of file mapgen.cpp.
{
            return dat.m.veh_at( tripoint( p, dat.zlevel() ) ).has_value();
        }
References cata::optional< T >::has_value(), mapgendata::m, map::veh_at(), and mapgendata::zlevel().
Member Data Documentation
chance
jmapgen_int jmapgen_vehicle::chance
Definition at line 1351 of file mapgen.cpp.
Referenced by apply().
fuel
int jmapgen_vehicle::fuel
Definition at line 1353 of file mapgen.cpp.
Referenced by apply().
rotation
std::vector<units::angle> jmapgen_vehicle::rotation
Definition at line 1352 of file mapgen.cpp.
Referenced by apply(), and jmapgen_vehicle().
status
int jmapgen_vehicle::status
Definition at line 1354 of file mapgen.cpp.
Referenced by apply().
type
vgroup_id jmapgen_vehicle::type
Definition at line 1350 of file mapgen.cpp.
Referenced by apply(), and jmapgen_vehicle().
The documentation for this class was generated from the following file:
src/mapgen.cpp