Cataclysm BN: basecamp Class Reference
basecamp Class Reference
#include <basecamp.h>
Public Member Functions
basecamp ()
basecamp (const std::string &name_, const tripoint_abs_omt &omt_pos)
basecamp (const std::string &name_, const tripoint &bb_pos_, const std::vector< point > &directions_, const std::map< point, expansion_data > &expansions_)
bool is_valid () const
int board_x () const
int board_y () const
tripoint_abs_omt camp_omt_pos () const
const std::string & camp_name () const
tripoint get_bb_pos () const
void validate_bb_pos (const tripoint &new_abs_pos)
void set_bb_pos (const tripoint &new_abs_pos)
void set_by_radio (bool access_by_radio)
std::string board_name () const
void faction_display (const catacurses::window &fac_w, int width) const
void set_name (const std::string &new_name)
void query_new_name ()
void abandon_camp ()
void add_expansion (const std::string &terrain, const tripoint_abs_omt &new_pos)
void add_expansion (const std::string &bldg, const tripoint_abs_omt &new_pos, const point &dir)
void define_camp (const tripoint_abs_omt &p, const std::string &camp_type="default")
std::string expansion_tab (const point &dir) const
bool has_provides (const std::string &req, const expansion_data &e_data, int level=0) const
bool has_provides (const std::string &req, const cata::optional< point > &dir=cata::nullopt, int level=0) const
void update_resources (const std::string &bldg)
void update_provides (const std::string &bldg, expansion_data &e_data)
void update_in_progress (const std::string &bldg, const point &dir)
bool can_expand ()
std::string next_upgrade (const point &dir, int offset=1) const
Returns the name of the building the current building dir upgrades into, "null" if there isn't one.
std::vector< basecamp_upgrade > available_upgrades (const point &dir)
int recruit_evaluation () const
int recruit_evaluation (int &sbase, int &sexpansions, int &sfaction, int &sbonus) const
bool validate_sort_points ()
expansion_data parse_expansion (const std::string &terrain, const tripoint_abs_omt &new_pos)
bool set_sort_points ()
Invokes the zone manager and validates that the necessary sort zones exist.
bool distribute_food ()
Takes all the food from the camp_food zone and increases the faction food_supply.
bool has_water ()
std::map< recipe_id, translation > recipe_deck (const point &dir) const
std::map< recipe_id, translation > recipe_deck (const std::string &bldg) const
int recipe_batch_max (const recipe &making) const
void form_crafting_inventory ()
void form_crafting_inventory (map &target_map)
std::list< item > use_charges (const itype_id &fake_id, int &quantity)
item_group_id get_gatherlist () const
void search_results (int skill, const item_group_id &group_id, int attempts, int difficulty)
spawn items or corpses based on search attempts
void hunting_results (int skill, const std::string &task, int attempts, int difficulty)
spawn items or corpses based on search attempts
const tripoint & get_dumping_spot () const
void set_dumping_spot (const tripoint &spot)
void place_results (item result)
void add_available_recipes (mission_data &mission_key, const point &dir, const std::map< recipe_id, translation > &craft_recipes)
std::string recruit_description (int npc_count)
std::string gathering_description (const std::string &bldg)
Provides a "guess" for some of the things your gatherers will return with to upgrade the camp.
std::string farm_description (const tripoint_abs_omt &farm_pos, size_t &plots_count, farm_ops operation)
Returns a string for the number of plants that are harvestable, plots ready to plant, and ground that needs tilling.
std::string craft_description (const recipe_id &itm)
Returns the description of a camp crafting options.
void get_available_missions (mission_data &mission_key)
void get_available_missions_by_dir (mission_data &mission_key, const point &dir)
void reset_camp_workers ()
comp_list get_mission_workers (const std::string &mission_id, bool contains=false)
bool handle_mission (const std::string &miss_id, const cata::optional< point > &opt_miss_dir)
npc_ptr start_mission (const std::string &miss_id, time_duration duration, bool must_feed, const std::string &desc, bool group, const std::vector< item * > &equipment, const skill_id &skill_tested, int skill_level)
generic mission start function that wraps individual mission
npc_ptr start_mission (const std::string &miss_id, time_duration duration, bool must_feed, const std::string &desc, bool group, const std::vector< item * > &equipment, const std::map< skill_id, int > &required_skills={})
void start_upgrade (const std::string &bldg, const point &dir, const std::string &key)
std::string om_upgrade_description (const std::string &bldg, bool trunc=false) const
Returns the description for the recipe of the next building bldg.
void start_menial_labor ()
void worker_assignment_ui ()
void job_assignment_ui ()
void start_crafting (const std::string &cur_id, const point &cur_dir, const std::string &type, const std::string &miss_id)
void start_cut_logs ()
Called when a companion is sent to cut logs.
void start_clearcut ()
void start_setup_hide_site ()
void start_relay_hide_site ()
void start_fortifications (std::string &bldg_exp)
Called when a compansion is sent to start fortifications.
void start_combat_mission (const std::string &miss)
bool start_garage_chop (const point &dir, const tripoint_abs_omt &omt_tgt)
Called when a companion starts a chop shop task mission.
void start_farm_op (const point &dir, const tripoint_abs_omt &omt_tgt, farm_ops op)
std::vector< item * > give_equipment (std::vector< item * > equipment, const std::string &msg)
Display items listed in equipment to let the player pick what to give the departing NPC, loops until quit or empty.
npc_ptr companion_choose_return (const std::string &miss_id, time_duration min_duration)
called to select a companion to return to the base
void finish_return (npc &comp, bool fixed_time, const std::string &return_msg, const std::string &skill, int difficulty, bool cancel=false)
called with a companion comp who is not the camp manager, finishes updating their skills, consuming food, and returning them to the base.
npc_ptr mission_return (const std::string &miss_id, time_duration min_duration, bool fixed_time, const std::string &return_msg, const std::string &skill, int difficulty)
a wrapper function for companion_choose_return and finish_return
npc_ptr emergency_recall ()
select a companion for any mission to return to base
bool upgrade_return (const point &dir, const std::string &miss)
Called to close upgrade missions, miss is the name of the mission id and dir is the direction of the location to be upgraded.
bool upgrade_return (const point &dir, const std::string &miss, const std::string &bldg)
As above, but with an explicit blueprint recipe to upgrade.
bool survey_return ()
Choose which expansion you should start, called when a survey mission is completed.
bool menial_return ()
bool gathering_return (const std::string &task, time_duration min_time)
Called when a companion completes a gathering task mission.
void recruit_return (const std::string &task, int score)
bool farm_return (const std::string &task, const tripoint_abs_omt &omt_tgt, farm_ops op)
Perform any mix of the three farm tasks.
void fortifications_return ()
void combat_mission_return (const std::string &miss)
void validate_assignees ()
void add_assignee (character_id id)
void remove_assignee (character_id id)
std::vector< npc_ptr > get_npcs_assigned ()
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
void load_data (const std::string &data)
Public Attributes
std::vector< point > directions
std::vector< tripoint_abs_omt > fortifications
std::string name
Static Public Attributes
static constexpr int inv_range = 20
Private Member Functions
void reset_camp_resources ()
void add_resource (const itype_id &camp_resource)
Private Attributes
bool resources_updated = false
tripoint_abs_omt omt_pos
std::vector< npc_ptr > assigned_npcs
tripoint bb_pos
std::map< point, expansion_data > expansions
comp_list camp_workers
tripoint dumping_spot
std::set< itype_id > fuel_types
std::vector< basecamp_fuel > fuels
std::vector< basecamp_resource > resources
inventory _inv
bool by_radio = false
Friends
class basecamp_action_components
Detailed Description
Definition at line 116 of file basecamp.h.
Constructor & Destructor Documentation
basecamp() [1/3]
basecamp::basecamp () default
basecamp() [2/3]
basecamp::basecamp (const std::string & name_, const tripoint_abs_omt & omt_pos)
Definition at line 114 of file basecamp.cpp.
                                                                            : name( name_ ),
    omt_pos( omt_pos_ )
{
}
basecamp() [3/3]
basecamp::basecamp (const std::string & name_, const tripoint & bb_pos_, const std::vector< point > & directions_, const std::map< point, expansion_data > & expansions_)
Definition at line 119 of file basecamp.cpp.
    : directions( directions_ ), name( name_ ), bb_pos( bb_pos_ ), expansions( expansions_ )
{
}
Member Function Documentation
abandon_camp()
void basecamp::abandon_camp ()
Definition at line 1629 of file faction_camp.cpp.
{
    validate_assignees();
    for( npc_ptr &guy : overmap_buffer.get_companion_mission_npcs( 10 ) ) {
        npc_companion_mission c_mission = guy->get_companion_mission();
        if( c_mission.role_id != base_camps::id ) {
            continue;
        }
        const std::string return_msg = _( "responds to the emergency recall" );
        finish_return( *guy, false, return_msg, "menial", 0, true );
    }
    for( npc_ptr &guy : get_npcs_assigned() ) {
        talk_function::stop_guard( *guy );
    }
    overmap_buffer.remove_camp( *this );
    map &here = get_map();
    here.remove_submap_camp( here.getlocal( bb_pos ) );
    add_msg( m_info, _( "You abandon %s." ), name );
}
References _, add_msg(), bb_pos, finish_return(), overmapbuffer::get_companion_mission_npcs(), get_map(), get_npcs_assigned(), map::getlocal(), base_camps::id, m_info, name, overmap_buffer, overmapbuffer::remove_camp(), map::remove_submap_camp(), npc_companion_mission::role_id, talk_function::stop_guard(), and validate_assignees().
Referenced by talk_function::abandon_camp(), and handle_mission().
add_assignee()
void basecamp::add_assignee (character_id id)
Definition at line 486 of file basecamp.cpp.
{
    npc_ptr npc_to_add = overmap_buffer.find_npc( id );
    if( !npc_to_add ) {
        debugmsg( "cant find npc to assign to basecamp, on the overmap_buffer" );
        return;
    }
    npc_to_add->assigned_camp = omt_pos;
    assigned_npcs.push_back( npc_to_add );
}
References assigned_npcs, debugmsg, overmapbuffer::find_npc(), omt_pos, and overmap_buffer.
Referenced by talk_function::assign_camp().
add_available_recipes()
void basecamp::add_available_recipes (mission_data & mission_key, const point & dir, const std::map< recipe_id, translation > & craft_recipes)
Definition at line 676 of file faction_camp.cpp.
{
    const std::string dir_id = base_camps::all_directions.at( dir ).id;
    const std::string dir_abbr = base_camps::all_directions.at( dir ).bracket_abbr.translated();
    for( const auto &recipe_data : craft_recipes ) {
        const std::string id = dir_id + recipe_data.first.str();
        const std::string &title_e = dir_abbr + recipe_data.second;
        const std::string &entry = craft_description( recipe_data.first );
        const recipe &recp = recipe_data.first.obj();
        bool craftable = recp.deduped_requirements().can_make_with_inventory(
                             _inv, recp.get_component_filter() );
        mission_key.add_start( id, title_e, dir, entry, craftable );
    }
}
References _inv, mission_data::add_start(), base_camps::all_directions, deduped_requirement_data::can_make_with_inventory(), craft_description(), recipe::deduped_requirements(), and recipe::get_component_filter().
Referenced by get_available_missions(), and get_available_missions_by_dir().
add_expansion() [1/2]
void basecamp::add_expansion (const std::string & bldg, const tripoint_abs_omt & new_pos, const point & dir)
Definition at line 166 of file basecamp.cpp.
{
    expansion_data e;
    e.type = base_camps::faction_decode( bldg );
    e.cur_level = -1;
    e.pos = new_pos;
    expansions[ dir ] = e;
    directions.push_back( dir );
    update_provides( bldg, expansions[ dir ] );
    update_resources( bldg );
}
References expansion_data::cur_level, directions, expansions, base_camps::faction_decode(), expansion_data::pos, expansion_data::type, update_provides(), and update_resources().
add_expansion() [2/2]
void basecamp::add_expansion (const std::string & terrain, const tripoint_abs_omt & new_pos)
Definition at line 152 of file basecamp.cpp.
{
    if( terrain.find( base_camps::prefix ) == std::string::npos ) {
        return;
    }
    const point dir = talk_function::om_simple_dir( omt_pos, new_pos );
    expansions[ dir ] = parse_expansion( terrain, new_pos );
    resources_updated = false;
    reset_camp_resources();
    update_provides( terrain, expansions[ dir ] );
    directions.push_back( dir );
}
References directions, expansions, talk_function::om_simple_dir(), omt_pos, parse_expansion(), base_camps::prefix, reset_camp_resources(), resources_updated, terrain, and update_provides().
Referenced by define_camp(), and survey_return().
add_resource()
void basecamp::add_resource (const itype_id & camp_resource) private
Definition at line 394 of file basecamp.cpp.
{
    basecamp_resource bcp_r;
    bcp_r.fake_id = camp_resource;
    item camp_item( bcp_r.fake_id, calendar::start_of_cataclysm );
    bcp_r.ammo_id = camp_item.ammo_default();
    resources.emplace_back( bcp_r );
    fuel_types.insert( bcp_r.ammo_id );
}
References item::ammo_default(), basecamp_resource::ammo_id, basecamp_resource::fake_id, fuel_types, resources, and calendar::start_of_cataclysm.
Referenced by update_resources().
available_upgrades()
std::vector< basecamp_upgrade > basecamp::available_upgrades (const point & dir)
Definition at line 299 of file basecamp.cpp.
{
    std::vector<basecamp_upgrade> ret_data;
    auto e = expansions.find( dir );
    if( e != expansions.end() ) {
        expansion_data &e_data = e->second;
        for( const recipe *recp_p : recipe_dict.all_blueprints() ) {
            const recipe &recp = *recp_p;
            const std::string &bldg = recp.result().str();
            // skip buildings that are completed
            if( e_data.provides.find( bldg ) != e_data.provides.end() ) {
                continue;
            }
            // skip building that have unmet requirements
            size_t needed_requires = recp.blueprint_requires().size();
            size_t met_requires = 0;
            for( const auto &bp_require : recp.blueprint_requires() ) {
                if( e_data.provides.find( bp_require.first ) == e_data.provides.end() ) {
                    break;
                }
                if( e_data.provides[bp_require.first] < bp_require.second ) {
                    break;
                }
                met_requires += 1;
            }
            if( met_requires < needed_requires ) {
                continue;
            }
            bool should_display = true;
            bool in_progress = false;
            for( const auto &bp_exclude : recp.blueprint_excludes() ) {
                // skip buildings that are excluded by previous builds
                if( e_data.provides.find( bp_exclude.first ) != e_data.provides.end() ) {
                    if( e_data.provides[bp_exclude.first] >= bp_exclude.second ) {
                        should_display = false;
                        break;
                    }
                }
                // track buildings that are currently being built
                if( e_data.in_progress.find( bp_exclude.first ) != e_data.in_progress.end() ) {
                    if( e_data.in_progress[bp_exclude.first] >= bp_exclude.second ) {
                        in_progress = true;
                        break;
                    }
                }
            }
            if( !should_display ) {
                continue;
            }
            basecamp_upgrade data;
            data.bldg = bldg;
            data.name = recp.blueprint_name();
            const auto &reqs = recp.deduped_requirements();
            data.avail = reqs.can_make_with_inventory( _inv, recp.get_component_filter(), 1 );
            data.in_progress = in_progress;
            ret_data.emplace_back( data );
        }
    }
    return ret_data;
}
References _inv, recipe_dictionary::all_blueprints(), basecamp_upgrade::avail, basecamp_upgrade::bldg, recipe::blueprint_excludes(), recipe::blueprint_name(), recipe::blueprint_requires(), recipe::deduped_requirements(), expansions, recipe::get_component_filter(), expansion_data::in_progress, basecamp_upgrade::in_progress, basecamp_upgrade::name, expansion_data::provides, recipe_dict, recipe::result(), and string_id< T >::str().
Referenced by get_available_missions(), and get_available_missions_by_dir().
board_name()
std::string basecamp::board_name () const
Definition at line 126 of file basecamp.cpp.
{
    //~ Name of a basecamp
    return string_format( _( "%s Board" ), name );
}
References _, name, and string_format().
board_x()
int basecamp::board_x () const inline
Definition at line 128 of file basecamp.h.
{
            return bb_pos.x;
        }
References bb_pos, and tripoint::x.
board_y()
int basecamp::board_y () const inline
Definition at line 131 of file basecamp.h.
{
            return bb_pos.y;
        }
References bb_pos, and tripoint::y.
camp_name()
const std::string & basecamp::camp_name () const inline
Definition at line 137 of file basecamp.h.
{
            return name;
        }
References name.
Referenced by talk_function::assign_camp(), npc::faction_display(), and query_new_name().
camp_omt_pos()
tripoint_abs_omt basecamp::camp_omt_pos () const inline
Definition at line 134 of file basecamp.h.
{
            return omt_pos;
        }
References omt_pos.
Referenced by overmapbuffer::add_camp(), iexamine::bulletin_board(), basecamp_action_components::consume_components(), faction_display(), overmapbuffer::remove_camp(), and game::validate_camps().
can_expand()
bool basecamp::can_expand ()
Definition at line 287 of file basecamp.cpp.
{
    return has_provides( "bed", base_camps::base_dir, directions.size() * 2 );
}
References base_camps::base_dir, directions, and has_provides().
Referenced by get_available_missions().
combat_mission_return()
void basecamp::combat_mission_return (const std::string & miss)
Definition at line 2882 of file faction_camp.cpp.
{
    npc_ptr comp = companion_choose_return( miss, 3_hours );
    if( comp != nullptr ) {
        bool patrolling = miss == "_faction_camp_combat_0";
        comp_list patrol;
        npc_ptr guy = overmap_buffer.find_npc( comp->getID() );
        if( guy ) {
            patrol.push_back( guy );
        }
        for( auto pt : comp->companion_mission_points ) {
            const oter_id &omt_ref = overmap_buffer.ter( pt );
            int swim = comp->get_skill_level( skill_swimming );
            if( is_river( omt_ref ) && swim < 2 ) {
                if( swim == 0 ) {
                    popup( _( "Your companion hit a river and didn't know how to swim" ) );
                } else {
                    popup( _( "Your companion hit a river and didn't know how to swim well "
                              "enough to cross" ) );
                }
                break;
            }
            comp->death_drops = false;
            bool outcome = talk_function::companion_om_combat_check( patrol, pt, patrolling );
            comp->death_drops = true;
            if( outcome ) {
                overmap_buffer.reveal( pt, 2 );
            } else if( comp->is_dead() ) {
                popup( _( "%s didn't return from patrol" ), comp->name );
                comp->place_corpse( pt );
                overmap_buffer.add_note( pt, "DEAD NPC" );
                overmap_buffer.remove_npc( comp->getID() );
                return;
            }
        }
        const std::string msg = _( "returns from patrol" );
        finish_return( *comp, true, msg, "combat", 4 );
    }
}
References _, overmapbuffer::add_note(), companion_choose_return(), talk_function::companion_om_combat_check(), overmapbuffer::find_npc(), finish_return(), is_river(), overmap_buffer, popup(), overmapbuffer::remove_npc(), overmapbuffer::reveal(), skill_swimming, avatar_action::swim(), and overmapbuffer::ter().
Referenced by handle_mission().
companion_choose_return()
npc_ptr basecamp::companion_choose_return (const std::string & miss_id, time_duration min_duration)
called to select a companion to return to the base
Definition at line 2518 of file faction_camp.cpp.
{
    return talk_function::companion_choose_return( omt_pos, base_camps::id, miss_id,
            calendar::turn - min_duration );
}
References talk_function::companion_choose_return(), base_camps::id, omt_pos, and calendar::turn.
Referenced by combat_mission_return(), farm_return(), fortifications_return(), gathering_return(), mission_return(), survey_return(), and upgrade_return().
craft_description()
std::string basecamp::craft_description (const recipe_id & itm)
Returns the description of a camp crafting options.
converts fire charges to charcoal, allows dark crafting
Definition at line 3672 of file faction_camp.cpp.
{
    const recipe &making = itm.obj();
    std::vector<std::string> component_print_buffer;
    int pane = FULL_SCREEN_WIDTH;
    const requirement_data &req = making.simple_requirements();
    auto tools = req.get_folded_tools_list( pane, c_white, _inv, 1 );
    auto comps = req.get_folded_components_list( pane, c_white, _inv,
                 making.get_component_filter(), 1 );
    component_print_buffer.insert( component_print_buffer.end(), tools.begin(), tools.end() );
    component_print_buffer.insert( component_print_buffer.end(), comps.begin(), comps.end() );
    std::string comp;
    for( auto &elem : component_print_buffer ) {
        comp = comp + elem + "\n";
    }
    comp = string_format( _( "Skill used: %s\nDifficulty: %d\n%s\nTime: %s\n" ),
                          making.skill_used.obj().name(), making.difficulty, comp,
                          to_string( base_camps::to_workdays( making.batch_duration() ) ) );
    return comp;
}
References _, _inv, recipe::batch_duration(), c_white, recipe::difficulty, FULL_SCREEN_WIDTH, recipe::get_component_filter(), requirement_data::get_folded_components_list(), requirement_data::get_folded_tools_list(), Skill::name(), string_id< T >::obj(), recipe::simple_requirements(), recipe::skill_used, string_format(), to_string(), and base_camps::to_workdays().
Referenced by add_available_recipes().
define_camp()
void basecamp::define_camp (const tripoint_abs_omt & p, const std::string & camp_type = "default")
Definition at line 179 of file basecamp.cpp.
{
    query_new_name();
    omt_pos = p;
    const oter_id &omt_ref = overmap_buffer.ter( omt_pos );
    // purging the regions guarantees all entries will start with faction_base_
    for( const std::pair<std::string, tripoint_abs_omt> &expansion :
         talk_function::om_building_region( omt_pos, 1, true ) ) {
        add_expansion( expansion.first, expansion.second );
    }
    const std::string om_cur = omt_ref.id().c_str();
    if( om_cur.find( base_camps::prefix ) == std::string::npos ) {
        expansion_data e;
        e.type = base_camps::faction_decode( camp_type );
        e.cur_level = -1;
        e.pos = omt_pos;
        expansions[base_camps::base_dir] = e;
        const std::string &direction = oter_get_rotation_string( omt_ref );
        const oter_id bcid( direction.empty() ? "faction_base_camp_0" : "faction_base_camp_new_0" +
                            direction );
        overmap_buffer.ter_set( omt_pos, bcid );
        update_provides( base_camps::faction_encode_abs( e, 0 ),
                         expansions[base_camps::base_dir] );
    } else {
        expansions[base_camps::base_dir] = parse_expansion( om_cur, omt_pos );
    }
}
References add_expansion(), base_camps::base_dir, string_id< T >::c_str(), expansion_data::cur_level, expansions, base_camps::faction_decode(), base_camps::faction_encode_abs(), int_id< T >::id(), talk_function::om_building_region(), omt_pos, oter_get_rotation_string(), overmap_buffer, parse_expansion(), expansion_data::pos, base_camps::prefix, query_new_name(), overmapbuffer::ter(), overmapbuffer::ter_set(), expansion_data::type, and update_provides().
Referenced by get_basecamp().
deserialize()
void basecamp::deserialize (JsonIn & jsin)
Definition at line 3581 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    data.read( "name", name );
    data.read( "pos", omt_pos );
    data.read( "bb_pos", bb_pos );
    for( JsonObject edata : data.get_array( "expansions" ) ) {
        edata.allow_omitted_members();
        expansion_data e;
        point dir;
        if( edata.has_string( "dir" ) ) {
            // old save compatibility
            const std::string dir_id = edata.get_string( "dir" );
            dir = base_camps::direction_from_id( dir_id );
        } else {
            edata.read( "dir", dir );
        }
        edata.read( "type", e.type );
        if( edata.has_int( "cur_level" ) ) {
            edata.read( "cur_level", e.cur_level );
        }
        if( edata.has_array( "provides" ) ) {
            e.cur_level = -1;
            for( JsonObject provide_data : edata.get_array( "provides" ) ) {
                provide_data.allow_omitted_members();
                std::string id = provide_data.get_string( "id" );
                int amount = provide_data.get_int( "amount" );
                e.provides[ id ] = amount;
            }
        }
        // incase of save corruption, sanity check provides from expansions
        const std::string &initial_provide = base_camps::faction_encode_abs( e, 0 );
        if( e.provides.find( initial_provide ) == e.provides.end() ) {
            e.provides[ initial_provide ] = 1;
        }
        for( JsonObject in_progress_data : edata.get_array( "in_progress" ) ) {
            in_progress_data.allow_omitted_members();
            std::string id = in_progress_data.get_string( "id" );
            int amount = in_progress_data.get_int( "amount" );
            e.in_progress[ id ] = amount;
        }
        edata.read( "pos", e.pos );
        expansions[ dir ] = e;
        if( dir != base_camps::base_dir ) {
            directions.push_back( dir );
        }
    }
    for( JsonObject edata : data.get_array( "fortifications" ) ) {
        edata.allow_omitted_members();
        tripoint_abs_omt restore_pos;
        edata.read( "pos", restore_pos );
        fortifications.push_back( restore_pos );
    }
}
References JsonObject::allow_omitted_members(), base_camps::base_dir, expansion_data::cur_level, base_camps::direction_from_id(), base_camps::faction_encode_abs(), JsonObject::get_array(), JsonIn::get_object(), Character::id, expansion_data::in_progress, Character::name, expansion_data::pos, expansion_data::provides, JsonObject::read(), and expansion_data::type.
Referenced by overmap::unserialize().
distribute_food()
bool basecamp::distribute_food ()
Takes all the food from the camp_food zone and increases the faction food_supply.
Definition at line 3887 of file faction_camp.cpp.
{
    if( !validate_sort_points() ) {
        popup( _( "You do not have a camp food zone.  Aborting" ) );
        return false;
    }
    zone_manager &mgr = zone_manager::get_manager();
    map &here = get_map();
    if( here.check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    const tripoint abspos = get_dumping_spot();
    const std::unordered_set<tripoint> z_food = mgr.get_near( zone_type_camp_food, abspos, 60 );
    bool has_items = false;
    for( const tripoint &p_food_stock_abs : z_food ) {
        const tripoint p_food_stock = here.getlocal( p_food_stock_abs );
        if( !here.i_at( p_food_stock ).empty() ) {
            has_items = true;
            break;
        }
    }
    if( !has_items ) {
        popup( _( "No items are located at the drop point" ) );
        return false;
    }
    const double quick_rot_coeff = 0.6 + ( has_provides( "pantry" ) ? 0.1 : 0 );
    const double slow_rot_coeff = 0.8 + ( has_provides( "pantry" ) ? 0.05 : 0 );
    int total = 0;
    std::vector<item> keep_me;
    for( const tripoint &p_food_stock_abs : z_food ) {
        const tripoint p_food_stock = here.getlocal( p_food_stock_abs );
        map_stack initial_items = here.i_at( p_food_stock );
        for( item &i : initial_items ) {
            const bool is_contained_food = i.is_container() && i.get_contained().is_food();
            const item &innermost_item = is_contained_food ? i.get_contained() : i;
            const bool would_npcs_eat = innermost_item.is_food()
                                        && !innermost_item.rotten()
                                        && innermost_item.get_comestible_fun() >= -6;
            if( !would_npcs_eat ) {
                keep_me.push_back( std::move( i ) );
                continue;
            }
            constexpr time_duration full_calories_threshold = 5_days;
            constexpr time_duration slow_rot_threshold = 2_days;
            // Containers handle spoilage logic internally.
            // so we would get very large time duration for canned or unspoilable foods.
            const time_duration rots_in = time_duration::from_turns( i.spoilage_sort_order() );
            const double rot_multiplier = ( rots_in >= full_calories_threshold ) ?
                                          1.0 :
                                          ( ( rots_in >= slow_rot_threshold ) ? slow_rot_coeff : quick_rot_coeff );
            // Comestible is not null for food.
            assert( innermost_item.get_comestible() );
            // TODO: Probably better use component based nutrition
            // like in `Character::compute_effective_nutrients`.
            const int kcal_per_item = innermost_item.get_comestible()->default_nutrition.kcal;
            const double kcal_from_current = kcal_per_item * innermost_item.count() * rot_multiplier;
            total += static_cast<int>( std::round( kcal_from_current ) );
            // Leave empty container.
            // TODO: make NPCs leave empty food containers elsewhere?
            if( i.is_container() ) {
                i.contents.clear_items();
                i.on_contents_changed();
                keep_me.push_back( std::move( i ) );
            }
        }
        here.i_clear( p_food_stock );
        for( item &i : keep_me ) {
            here.add_item_or_charges( p_food_stock, std::move( i ), false );
        }
        keep_me.clear();
    }
    popup( _( "You distribute %d kcal worth of food to your companions." ), total );
    camp_food_supply( total );
    return true;
}
References _, map::add_item_or_charges(), zone_manager::cache_vzones(), camp_food_supply(), map::check_vehicle_zones(), item::count(), item_stack::empty(), time_duration::from_turns(), g, item::get_comestible(), item::get_comestible_fun(), item::get_contained(), get_dumping_spot(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), map::getlocal(), has_provides(), map::i_at(), map::i_clear(), item::is_food(), avatar_action::move(), popup(), item::rotten(), validate_sort_points(), and zone_type_camp_food.
Referenced by handle_mission().
emergency_recall()
npc_ptr basecamp::emergency_recall ()
select a companion for any mission to return to base
Definition at line 2585 of file faction_camp.cpp.
{
    npc_ptr comp = talk_function::companion_choose_return( omt_pos, base_camps::id, "",
                   calendar::turn - 24_hours, false );
    if( comp != nullptr ) {
        const std::string return_msg = _( "responds to the emergency recall" );
        finish_return( *comp, false, return_msg, "menial", 0, true );
    }
    return comp;
}
References _, talk_function::companion_choose_return(), finish_return(), base_camps::id, omt_pos, and calendar::turn.
Referenced by handle_mission().
expansion_tab()
std::string basecamp::expansion_tab (const point & dir) const
Definition at line 678 of file basecamp.cpp.
{
    if( dir == base_camps::base_dir ) {
        return _( "Base Missions" );
    }
    const auto &expansion_types = recipe_group::get_recipes_by_id( "all_faction_base_expansions" );
    const auto &e = expansions.find( dir );
    if( e != expansions.end() ) {
        recipe_id id( base_camps::faction_encode_abs( e->second, 0 ) );
        const auto e_type = expansion_types.find( id );
        if( e_type != expansion_types.end() ) {
            return e_type->second + _( "Expansion" );
        }
    }
    return _( "Empty Expansion" );
}
References _, base_camps::base_dir, expansions, base_camps::faction_encode_abs(), recipe_group::get_recipes_by_id(), and base_camps::id.
Referenced by talk_function::name_mission_tabs().
faction_display()
void basecamp::faction_display (const catacurses::window & fac_w, int width) const
Definition at line 461 of file faction.cpp.
{
    int y = 2;
    const nc_color col = c_white;
    Character &player_character = get_player_character();
    const tripoint_abs_omt player_abspos = player_character.global_omt_location();
    tripoint_abs_omt camp_pos = camp_omt_pos();
    std::string direction = direction_name( direction_from( player_abspos, camp_pos ) );
    mvwprintz( fac_w, point( width, ++y ), c_light_gray, _( "Press enter to rename this camp" ) );
    if( direction != "center" ) {
        mvwprintz( fac_w, point( width, ++y ), c_light_gray, _( "Direction: to the " ) + direction );
    }
    mvwprintz( fac_w, point( width, ++y ), col, _( "Location: %s" ), camp_pos.to_string() );
    faction *yours = player_character.get_faction();
    std::string food_text = string_format( _( "Food Supply: %s %d calories" ),
                                           yours->food_supply_text(), yours->food_supply );
    nc_color food_col = yours->food_supply_color();
    mvwprintz( fac_w, point( width, ++y ), food_col, food_text );
    std::string bldg = next_upgrade( base_camps::base_dir, 1 );
    std::string bldg_full = _( "Next Upgrade: " ) + bldg;
    mvwprintz( fac_w, point( width, ++y ), col, bldg_full );
    std::string requirements = om_upgrade_description( bldg, true );
    fold_and_print( fac_w, point( width, ++y ), getmaxx( fac_w ) - width - 2, col, requirements );
}
References _, base_camps::base_dir, c_light_gray, c_white, camp_omt_pos(), direction_from(), direction_name(), fold_and_print(), faction_template::food_supply, faction::food_supply_color(), faction::food_supply_text(), Character::get_faction(), get_player_character(), catacurses::getmaxx(), Character::global_omt_location(), mvwprintz(), next_upgrade(), om_upgrade_description(), string_format(), and coords::coord_point< Point, Origin, Scale >::to_string().
Referenced by faction_manager::display().
farm_description()
std::string basecamp::farm_description (const tripoint_abs_omt & farm_pos, size_t & plots_count, farm_ops operation)
Returns a string for the number of plants that are harvestable, plots ready to plant, and ground that needs tilling.
Definition at line 3803 of file faction_camp.cpp.
{
    std::pair<size_t, std::string> farm_data = farm_action( farm_pos, operation );
    std::string entry;
    plots_count = farm_data.first;
    switch( operation ) {
        case farm_ops::harvest:
            entry += _( "Harvestable: " ) + std::to_string( plots_count ) + "\n" + farm_data.second;
            break;
        case farm_ops::plant:
            entry += _( "Ready for Planting: " ) + std::to_string( plots_count ) + "\n";
            break;
        case farm_ops::plow:
            entry += _( "Needs Plowing: " ) + std::to_string( plots_count ) + "\n";
            break;
        default:
            debugmsg( "Farm operations called with no operation" );
            break;
    }
    return entry;
}
References _, debugmsg, farm_action(), harvest, plant, plow, and to_string().
Referenced by get_available_missions_by_dir().
farm_return()
bool basecamp::farm_return (const std::string & task, const tripoint_abs_omt & omt_tgt, farm_ops op)
Perform any mix of the three farm tasks.
Parameters
task
omt_tgt the overmap pos3 of the farm_ops
op whether to plow, plant, or harvest
Definition at line 2974 of file faction_camp.cpp.
{
    const std::string msg = _( "returns from working your fields" );
    npc_ptr comp = companion_choose_return( task, 15_minutes );
    if( comp == nullptr ) {
        return false;
    }
    farm_action( omt_tgt, op, comp );
    //Give any seeds the NPC didn't use back to you.
    for( size_t i = 0; i < comp->companion_mission_inv.size(); i++ ) {
        for( const auto &it : comp->companion_mission_inv.const_stack( i ) ) {
            if( it.charges > 0 ) {
                g->u.i_add( it );
            }
        }
    }
    finish_return( *comp, true, msg, "survival", 2 );
    return true;
}
References _, companion_choose_return(), farm_action(), finish_return(), and g.
Referenced by handle_mission().
finish_return()
void basecamp::finish_return (npc & comp, bool fixed_time, const std::string & return_msg, const std::string & skill, int difficulty, bool cancel = false)
called with a companion comp who is not the camp manager, finishes updating their skills, consuming food, and returning them to the base.
Definition at line 2524 of file faction_camp.cpp.
{
    popup( "%s %s", comp.name, return_msg );
    // this is the time the mission was expected to take, or did take for fixed time missions
    time_duration reserve_time = comp.companion_mission_time_ret - comp.companion_mission_time;
    time_duration mission_time = reserve_time;
    if( !fixed_time ) {
        mission_time = calendar::turn - comp.companion_mission_time;
    }
    if( !cancel ) {
        talk_function::companion_skill_trainer( comp, skill, mission_time, difficulty );
    }
    // companions subtracted food when they started the mission, but didn't mod their hunger for
    // that food.  so add it back in.
    int need_food = time_to_food( mission_time - reserve_time );
    if( camp_food_supply() < need_food ) {
        popup( _( "Your companion seems disappointed that your pantry is empty" ) );
    }
    int avail_food = std::min( need_food, camp_food_supply() ) + time_to_food( reserve_time );
    // movng all the logic from talk_function::companion return here instead of polluting
    // mission_companion
    comp.reset_companion_mission();
    comp.companion_mission_time = calendar::before_time_starts;
    comp.companion_mission_time_ret = calendar::before_time_starts;
    if( !cancel ) {
        for( size_t i = 0; i < comp.companion_mission_inv.size(); i++ ) {
            for( const auto &it : comp.companion_mission_inv.const_stack( i ) ) {
                if( !it.count_by_charges() || it.charges > 0 ) {
                    place_results( it );
                }
            }
        }
    }
    comp.companion_mission_inv.clear();
    comp.companion_mission_points.clear();
    // npc *may* be active, or not if outside the reality bubble
    g->reload_npcs();
    validate_assignees();
    camp_food_supply( -need_food );
    comp.mod_stored_kcal( avail_food );
    if( has_water() ) {
        comp.set_thirst( 0 );
    }
    comp.set_fatigue( 0 );
    comp.set_sleep_deprivation( 0 );
}
References _, calendar::before_time_starts, camp_food_supply(), cancel, inventory::clear(), npc::companion_mission_inv, npc::companion_mission_points, npc::companion_mission_time, npc::companion_mission_time_ret, talk_function::companion_skill_trainer(), inventory::const_stack(), g, has_water(), Character::mod_stored_kcal(), Character::name, need_food, place_results(), popup(), npc::reset_companion_mission(), Character::set_fatigue(), Character::set_sleep_deprivation(), Character::set_thirst(), inventory::size(), time_to_food(), calendar::turn, and validate_assignees().
Referenced by abandon_camp(), combat_mission_return(), emergency_recall(), farm_return(), fortifications_return(), gathering_return(), mission_return(), survey_return(), and upgrade_return().
form_crafting_inventory() [1/2]
void basecamp::form_crafting_inventory ()
Definition at line 666 of file basecamp.cpp.
{
    if( by_radio ) {
        tinymap target_map;
        target_map.load( project_to<coords::sm>( omt_pos ), false );
        form_crafting_inventory( target_map );
    } else {
        form_crafting_inventory( get_map() );
    }
}
References by_radio, form_crafting_inventory(), get_map(), map::load(), and omt_pos.
Referenced by form_crafting_inventory(), and reset_camp_resources().
form_crafting_inventory() [2/2]
void basecamp::form_crafting_inventory (map & target_map)
Definition at line 606 of file basecamp.cpp.
{
    _inv.clear();
    const tripoint &dump_spot = get_dumping_spot();
    const tripoint &origin = target_map.getlocal( dump_spot );
    auto &mgr = zone_manager::get_manager();
    if( get_map().check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    if( mgr.has_near( zone_type_camp_storage, dump_spot, 60 ) ) {
        std::unordered_set<tripoint> src_set = mgr.get_near( zone_type_camp_storage, dump_spot, 60 );
        _inv.form_from_zone( target_map, src_set, nullptr, false );
    }
    /*
     * something of a hack: add the resources we know the camp has
     * the hacky part is that we're adding resources based on the camp's flags, which were
     * generated based on upgrade missions, instead of having resources added when the
     * map changes
     */
    // make sure the array is empty
    fuels.clear();
    for( const itype_id &fuel_id : fuel_types ) {
        basecamp_fuel bcp_f;
        bcp_f.available = 0;
        bcp_f.ammo_id = fuel_id;
        fuels.emplace_back( bcp_f );
    }
    // find available fuel
    for( const tripoint &pt : target_map.points_in_radius( origin, inv_range ) ) {
        if( target_map.accessible_items( pt ) ) {
            for( const item &i : target_map.i_at( pt ) ) {
                for( basecamp_fuel &bcp_f : fuels ) {
                    if( bcp_f.ammo_id == i.typeId() ) {
                        bcp_f.available += i.charges;
                        break;
                    }
                }
            }
        }
    }
    for( basecamp_resource &bcp_r : resources ) {
        bcp_r.consumed = 0;
        item camp_item( bcp_r.fake_id, calendar::start_of_cataclysm );
        camp_item.set_flag( "PSEUDO" );
        if( !bcp_r.ammo_id.is_null() ) {
            for( basecamp_fuel &bcp_f : fuels ) {
                if( bcp_f.ammo_id == bcp_r.ammo_id ) {
                    if( bcp_f.available > 0 ) {
                        bcp_r.available = bcp_f.available;
                        camp_item = camp_item.ammo_set( bcp_f.ammo_id, bcp_f.available );
                    }
                    break;
                }
            }
        }
        _inv.add_item( camp_item );
    }
}
References _inv, map::accessible_items(), inventory::add_item(), basecamp_fuel::ammo_id, item::ammo_set(), basecamp_fuel::available, inventory::clear(), inventory::form_from_zone(), fuel_types, fuels, g, get_dumping_spot(), zone_manager::get_manager(), get_map(), map::getlocal(), map::i_at(), inv_range, map::points_in_radius(), resources, item::set_flag(), calendar::start_of_cataclysm, and zone_type_camp_storage.
fortifications_return()
void basecamp::fortifications_return ()
Definition at line 2724 of file faction_camp.cpp.
{
    npc_ptr comp = companion_choose_return( "_faction_camp_om_fortifications", 3_hours );
    if( comp != nullptr ) {
        std::string build_n = "faction_wall_level_N_0";
        std::string build_e = "faction_wall_level_E_0";
        std::string build_s = "faction_wall_level_S_0";
        std::string build_w = "faction_wall_level_W_0";
        if( comp->companion_mission_role_id == "faction_wall_level_N_1" ) {
            build_n = "faction_wall_level_N_1";
            build_e = "faction_wall_level_E_1";
            build_s = "faction_wall_level_S_1";
            build_w = "faction_wall_level_W_1";
        }
        std::string build_first = build_e;
        std::string build_second = build_w;
        bool build_dir_NS = comp->companion_mission_points[0].y() !=
                            comp->companion_mission_points[1].y();
        if( build_dir_NS ) {
            build_first = build_s;
            build_second = build_n;
        }
        //Add fences
        auto build_point = comp->companion_mission_points;
        for( size_t pt = 0; pt < build_point.size(); pt++ ) {
            //First point is always at top or west since they are built in a line and sorted
            if( pt == 0 ) {
                run_mapgen_update_func( build_first, build_point[pt] );
            } else if( pt == build_point.size() - 1 ) {
                run_mapgen_update_func( build_second, build_point[pt] );
            } else {
                run_mapgen_update_func( build_first, build_point[pt] );
                run_mapgen_update_func( build_second, build_point[pt] );
            }
            if( comp->companion_mission_role_id == "faction_wall_level_N_0" ) {
                tripoint_abs_omt fort_point = build_point[pt];
                fortifications.push_back( fort_point );
            }
        }
        const std::string msg = _( "returns from constructing fortifications" );
        finish_return( *comp, true, msg, "construction", 2 );
    }
}
References _, companion_choose_return(), finish_return(), fortifications, and run_mapgen_update_func().
Referenced by handle_mission().
gathering_description()
std::string basecamp::gathering_description (const std::string & bldg)
Provides a "guess" for some of the things your gatherers will return with to upgrade the camp.
Definition at line 3773 of file faction_camp.cpp.
{
    item_group_id itemlist;
    if( item_group::group_is_defined( item_group_id( "gathering_" + bldg ) ) ) {
        itemlist = item_group_id( "gathering_" + bldg );
    } else {
        itemlist = item_group_id( "forest" );
    }
    std::string output;
    // Functions like the debug item group tester but only rolls 6 times so the player
    // doesn't have perfect knowledge
    std::map<std::string, int> itemnames;
    for( size_t a = 0; a < 6; a++ ) {
        const auto items = item_group::items_from( itemlist, calendar::turn );
        for( auto &it : items ) {
            itemnames[it.display_name()]++;
        }
    }
    // Invert the map to get sorting!
    std::multimap<int, std::string> itemnames2;
    for( const auto &e : itemnames ) {
        itemnames2.insert( std::pair<int, std::string>( e.second, e.first ) );
    }
    for( const auto &e : itemnames2 ) {
        output = output + "> " + e.second + "\n";
    }
    return output;
}
References a, item_group::group_is_defined(), item_group::items_from(), and calendar::turn.
Referenced by get_available_missions_by_dir().
gathering_return()
bool basecamp::gathering_return (const std::string & task, time_duration min_time)
Called when a companion completes a gathering task mission.
Definition at line 2649 of file faction_camp.cpp.
{
    npc_ptr comp = companion_choose_return( task, min_time );
    if( comp == nullptr ) {
        return false;
    }
    std::string task_description = _( "gathering materials" );
    int danger = 20;
    int favor = 2;
    int threat = 10;
    std::string skill_group = "gathering";
    int skill = 2 * comp->get_skill_level( skill_survival ) + comp->per_cur;
    int checks_per_cycle = 6;
    if( task == "_faction_camp_foraging" ) {
        task_description = _( "foraging for edible plants" );
        danger = 15;
        checks_per_cycle = 12;
    } else if( task == "_faction_camp_trapping" ) {
        task_description = _( "trapping small animals" );
        favor = 1;
        danger = 15;
        skill_group = "trapping";
        skill = 2 * comp->get_skill_level( skill_traps ) + comp->per_cur;
        checks_per_cycle = 4;
    } else if( task == "_faction_camp_hunting" ) {
        task_description = _( "hunting for meat" );
        danger = 10;
        favor = 0;
        skill_group = "hunting";
        skill = 1.5 * comp->get_skill_level( skill_gun ) + comp->per_cur / 2.0;
        threat = 12;
        checks_per_cycle = 2;
    }
    time_duration mission_time = calendar::turn - comp->companion_mission_time;
    if( one_in( danger ) && !survive_random_encounter( *comp, task_description, favor, threat ) ) {
        return false;
    }
    const std::string msg = string_format( _( "returns from %s carrying supplies and has a bit "
                                           "more experience" ), task_description );
    finish_return( *comp, false, msg, skill_group, 1 );
    item_group_id itemlist = item_group_id( "forest" );
    if( task == "_faction_camp_firewood" ) {
        itemlist = item_group_id( "gathering_faction_base_camp_firewood" );
    } else if( task == "_faction_camp_gathering" ) {
        itemlist = get_gatherlist();
    } else if( task == "_faction_camp_foraging" ) {
        switch( season_of_year( calendar::turn ) ) {
            case SPRING:
                itemlist = item_group_id( "foraging_faction_camp_spring" );
                break;
            case SUMMER:
                itemlist = item_group_id( "foraging_faction_camp_summer" );
                break;
            case AUTUMN:
                itemlist = item_group_id( "foraging_faction_camp_autumn" );
                break;
            case WINTER:
                itemlist = item_group_id( "foraging_faction_camp_winter" );
                break;
            default:
                debugmsg( "Invalid season" );
        }
    }
    if( task == "_faction_camp_trapping" || task == "_faction_camp_hunting" ) {
        hunting_results( skill, task, checks_per_cycle * mission_time / min_time, 30 );
    } else {
        search_results( skill, itemlist, checks_per_cycle * mission_time / min_time, 15 );
    }
    return true;
}
References _, AUTUMN, companion_choose_return(), debugmsg, finish_return(), get_gatherlist(), hunting_results(), one_in(), search_results(), season_of_year(), skill_gun, skill_survival, skill_traps, SPRING, string_format(), SUMMER, survive_random_encounter(), calendar::turn, and WINTER.
Referenced by handle_mission().
get_available_missions()
void basecamp::get_available_missions (mission_data & mission_key)
Definition at line 1210 of file faction_camp.cpp.
{
    std::string entry;
    const point &base_dir = base_camps::base_dir;
    const base_camps::direction_data &base_data = base_camps::all_directions.at( base_dir );
    const std::string base_dir_id = base_data.id;
    const std::string base_dir_abbr = base_data.bracket_abbr.translated();
    reset_camp_resources();
    std::string gather_bldg = "null";
    // Handling for the central tile
    // return legacy workers
    comp_list legacy_npc_list = get_mission_workers( "_faction_upgrade_camp" );
    if( !legacy_npc_list.empty() ) {
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_upgrade_camp" ];
        entry = miss_info.action.translated();
        bool avail = update_time_left( entry, legacy_npc_list );
        mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                base_camps::base_dir, entry, avail );
    }
    for( const basecamp_upgrade &upgrade : available_upgrades( base_camps::base_dir ) ) {
        gather_bldg = upgrade.bldg;
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_upgrade_camp" ];
        comp_list npc_list = get_mission_workers( upgrade.bldg + "_faction_upgrade_camp" );
        if( npc_list.empty() && !upgrade.in_progress ) {
            entry = om_upgrade_description( upgrade.bldg );
            mission_key.add_start( miss_info.miss_id + upgrade.bldg,
                                   miss_info.desc + " " + upgrade.name, base_camps::base_dir,
                                   entry, upgrade.avail );
        } else if( !npc_list.empty() && upgrade.in_progress ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id + upgrade.bldg,
                                    miss_info.ret_desc + " " + upgrade.name, base_camps::base_dir,
                                    entry, avail );
        }
    }
    // Missions that belong exclusively to the central tile
    comp_list npc_list = get_mission_workers( "_faction_camp_crafting_" + base_dir_id );
    const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_crafting_" ];
    //This handles all crafting by the base, regardless of level
    if( npc_list.empty() ) {
        std::map<recipe_id, translation> craft_recipes = recipe_deck( base_camps::base_dir );
        add_available_recipes( mission_key, base_camps::base_dir, craft_recipes );
    } else {
        entry = miss_info.action.translated();
        bool avail = update_time_left( entry, npc_list );
        mission_key.add_return( base_dir_id + miss_info.ret_miss_id,
                                base_dir_abbr + miss_info.ret_desc, base_camps::base_dir, entry,
                                avail );
    }
    if( can_expand() ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_expansion" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_expansion" ];
        entry = string_format( _( "Notes:\n"
                                  "Your base has become large enough to support an expansion.  "
                                  "Expansions open up new opportunities but can be expensive and "
                                  "time consuming.  Pick them carefully, only 8 can be built at "
                                  "each camp.\n\n"
                                  "Skill used: N/A\n"
                                  "Effects:\n"
                                  "> Choose any one of the available expansions.  Starting with "
                                  "a farm is always a solid choice since food is used to support "
                                  "companion missions and little is needed to get it going.  "
                                  "With minimal investment, a mechanic can be useful as a "
                                  "chop-shop to rapidly dismantle large vehicles, and a forge "
                                  "provides the resources to make charcoal.\n\n"
                                  "NOTE: Actions available through expansions are located in "
                                  "separate tabs of the Camp Manager window.\n\n"
                                  "Risk: None\n"
                                  "Time: 3 Hours\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(),
                               base_camps::base_dir, entry, npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    base_camps::base_dir, entry, avail );
        }
    }
    if( !by_radio ) {
        entry = string_format( _( "Notes:\n"
                                  "Distribute food to your follower and fill you larders.  "
                                  "Place the food you wish to distribute in the camp food zone.  "
                                  "You must have a camp food zone, and a camp storage zone, "
                                  "or you will be prompted to create them using the zone manager.\n"
                                  "Effects:\n"
                                  "> Increases your faction's food supply value which in "
                                  "turn is used to pay laborers for their time\n\n"
                                  "Must have enjoyability >= -6\n"
                                  "Perishable food liquidated at penalty depending on "
                                  "upgrades and rot time:\n"
                                  "> Rotten: 0%%\n"
                                  "> Rots in < 2 days: 60%%\n"
                                  "> Rots in < 5 days: 80%%\n\n"
                                  "Total faction food stock: %d kcal\nor %d day's rations" ),
                               camp_food_supply(), camp_food_supply( 0, true ) );
        mission_key.add( "Distribute Food", _( "Distribute Food" ), entry );
        validate_assignees();
        entry = string_format( _( "Notes:\n"
                                  "Assign repeating job duties to NPCs stationed here.\n"
                                  "Difficulty: N/A\n"
                                  "Effects:\n"
                                  "\n\nRisk: None\n"
                                  "Time: Ongoing" ) );
        mission_key.add( "Assign Jobs", _( "Assign Jobs" ), entry );
        entry = string_format( _( "Notes:\n"
                                  "Assign followers to work at this camp." ) );
        mission_key.add( "Assign Workers", _( "Assign Workers" ), entry );
        entry = _( "Notes:\nAbandon this camp" );
        mission_key.add( "Abandon Camp", _( "Abandon Camp" ), entry );
    }
    // Missions assigned to the central tile that could be done by an expansion
    get_available_missions_by_dir( mission_key, base_camps::base_dir );
    // Loop over expansions
    for( const point &dir : directions ) {
        get_available_missions_by_dir( mission_key, dir );
    }
    if( !camp_workers.empty() ) {
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_recall" ];
        entry = string_format( _( "Notes:\n"
                                  "Cancel a current mission and force the immediate return of a "
                                  "companion.  No work will be done on the mission and all "
                                  "resources used on the mission will be lost.\n\n"
                                  "WARNING: All resources used on the mission will be lost and "
                                  "no work will be done.  Only use this mission to recover a "
                                  "companion who cannot otherwise be recovered.\n\n"
                                  "Companions must be on missions for at least 24 hours before "
                                  "emergency recall becomes available." ) );
        bool avail = update_time_fixed( entry, camp_workers, 24_hours );
        mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                base_camps::base_dir, entry, avail );
    }
}
References _, mission_data::add(), add_available_recipes(), mission_data::add_return(), mission_data::add_start(), base_camps::all_directions, available_upgrades(), base_camps::base_dir, base_camps::direction_data::bracket_abbr, by_radio, camp_food_supply(), camp_workers, can_expand(), directions, get_available_missions_by_dir(), get_mission_workers(), base_camps::direction_data::id, base_camps::miss_info, om_upgrade_description(), recipe_deck(), reset_camp_resources(), string_format(), translation::translated(), update_time_fixed(), update_time_left(), mattack::upgrade(), and validate_assignees().
Referenced by talk_function::basecamp_mission(), and iexamine::bulletin_board().
get_available_missions_by_dir()
void basecamp::get_available_missions_by_dir (mission_data & mission_key, const point & dir)
Definition at line 692 of file faction_camp.cpp.
{
    std::string entry;
    std::string gather_bldg = "null";
    const std::string dir_id = base_camps::all_directions.at( dir ).id;
    const std::string dir_abbr = base_camps::all_directions.at( dir ).bracket_abbr.translated();
    const tripoint_abs_omt omt_trg = omt_pos + dir;
    if( dir != base_camps::base_dir ) {
        // return legacy workers
        comp_list npc_list = get_mission_workers( "_faction_upgrade_exp_" + dir_id );
        if( !npc_list.empty() ) {
            const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_upgrade_exp_" ];
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( "Recover Ally, " + dir_id + " Expansion",
                                    _( "Recover Ally, " ) + dir_abbr + _( " Expansion" ), dir,
                                    entry, avail );
        }
        // Generate upgrade missions for expansions
        for( const basecamp_upgrade &upgrade : available_upgrades( dir ) ) {
            const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_upgrade_exp_" ];
            comp_list npc_list = get_mission_workers( upgrade.bldg + "_faction_upgrade_exp_" +
                                 dir_id );
            if( npc_list.empty() ) {
                entry = om_upgrade_description( upgrade.bldg );
                mission_key.add_start( dir_id + miss_info.miss_id + upgrade.bldg,
                                       dir_abbr + miss_info.desc + " " + upgrade.name, dir, entry,
                                       upgrade.avail );
            } else {
                entry = miss_info.action.translated();
                bool avail = update_time_left( entry, npc_list );
                mission_key.add_return( "Recover Ally, " + dir_id + " Expansion" + upgrade.bldg,
                                        _( "Recover Ally, " ) + dir_abbr + _( " Expansion" ) +
                                        " " + upgrade.name, dir, entry, avail );
            }
        }
    }
    if( has_provides( "gathering", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_gathering" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_gathering" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to gather materials for the next camp "
                                  "upgrade.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: N/A\n"
                                  "Gathering Possibilities:\n"
                                  "%s\n"
                                  "Risk: Very Low\n"
                                  "Time: 3 Hours, Repeated\n"
                                  "Positions: %d/3\n" ), gathering_description( gather_bldg ),
                               npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), dir,
                               entry, npc_list.size() < 3 );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_fixed( entry, npc_list, 3_hours );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    dir, entry, avail );
        }
    }
    if( has_provides( "firewood", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_firewood" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_firewood" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to gather light brush and heavy sticks.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: N/A\n"
                                  "Gathering Possibilities:\n"
                                  "> heavy sticks\n"
                                  "> withered plants\n"
                                  "> splintered wood\n\n"
                                  "Risk: Very Low\n"
                                  "Time: 3 Hours, Repeated\n"
                                  "Positions: %d/3\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt,
                               entry, npc_list.size() < 3 );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_fixed( entry, npc_list, 3_hours );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "sorting", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_menial" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_menial" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to do low level chores and sort "
                                  "supplies.\n\n"
                                  "Skill used: fabrication\n"
                                  "Difficulty: N/A\n"
                                  "Effects:\n"
                                  "> Material left in the unsorted loot zone will be sorted "
                                  "into a defined loot zone."
                                  "\n\nRisk: None\n"
                                  "Time: 3 Hours\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt,
                               entry, npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "logging", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_cut_log" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_cut_log" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to a nearby forest to cut logs.\n\n"
                                  "Skill used: fabrication\n"
                                  "Difficulty: 1\n"
                                  "Effects:\n"
                                  "> 50%% of trees/trunks at the forest position will be "
                                  "cut down.\n"
                                  "> 100%% of total material will be brought back.\n"
                                  "> Repeatable with diminishing returns.\n"
                                  "> Will eventually turn forests into fields.\n"
                                  "Risk: None\n"
                                  "Time: 6 Hour Base + Travel Time + Cutting Time\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt,
                               entry, npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "logging", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_clearcut" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_clearcut" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to a clear a nearby forest.\n\n"
                                  "Skill used: fabrication\n"
                                  "Difficulty: 1\n"
                                  "Effects:\n"
                                  "> 95%% of trees/trunks at the forest position"
                                  " will be cut down.\n"
                                  "> 0%% of total material will be brought back.\n"
                                  "> Forest should become a field tile.\n"
                                  "> Useful for clearing land for another faction camp.\n\n"
                                  "Risk: None\n"
                                  "Time: 6 Hour Base + Travel Time + Cutting Time\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt,
                               entry, npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "relaying", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_hide_site" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_hide_site" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to build an improvised shelter and stock it "
                                  "with equipment at a distant map location.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: 3\n"
                                  "Effects:\n"
                                  "> Good for setting up resupply or contingency points.\n"
                                  "> Gear is left unattended and could be stolen.\n"
                                  "> Time dependent on weight of equipment being sent forward.\n\n"
                                  "Risk: Medium\n"
                                  "Time: 6 Hour Construction + Travel\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt,
                               entry, npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "relaying", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_hide_trans" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_hide_trans" ];
        entry = string_format( _( "Notes:\n"
                                  "Push gear out to a hide site or bring gear back from one.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: 1\n"
                                  "Effects:\n"
                                  "> Good for returning equipment you left in the hide site "
                                  "shelter.\n"
                                  "> Gear is left unattended and could be stolen.\n"
                                  "> Time dependent on weight of equipment being sent forward or "
                                  "back.\n\n"
                                  "Risk: Medium\n"
                                  "Time: 1 Hour Base + Travel\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt, entry,
                               npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "foraging", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_foraging" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_foraging" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to forage for edible plants.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: N/A\n"
                                  "Foraging Possibilities:\n"
                                  "> wild vegetables\n"
                                  "> fruits and nuts depending on season\n"
                                  "May produce less food than consumed!\n"
                                  "Risk: Very Low\n"
                                  "Time: 4 Hours, Repeated\n"
                                  "Positions: %d/3\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), dir,
                               entry, npc_list.size() < 3 );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_fixed( entry, npc_list, 4_hours );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    dir, entry, avail );
        }
    }
    if( has_provides( "trapping", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_trapping" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_trapping" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to set traps for small game.\n\n"
                                  "Skill used: trapping\n"
                                  "Difficulty: N/A\n"
                                  "Trapping Possibilities:\n"
                                  "> small and tiny animal corpses\n"
                                  "May produce less food than consumed!\n"
                                  "Risk: Low\n"
                                  "Time: 6 Hours, Repeated\n"
                                  "Positions: %d/2\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), dir,
                               entry, npc_list.size() < 2 );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_fixed( entry, npc_list, 6_hours );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    dir, entry, avail );
        }
    }
    if( has_provides( "hunting", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_hunting" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_hunting" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to hunt large animals.\n\n"
                                  "Skill used: marksmanship\n"
                                  "Difficulty: N/A\n"
                                  "Hunting Possibilities:\n"
                                  "> small, medium, or large animal corpses\n"
                                  "May produce less food than consumed!\n"
                                  "Risk: Medium\n"
                                  "Time: 6 Hours, Repeated\n"
                                  "Positions: %d/1\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), dir,
                               entry, npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_fixed( entry, npc_list, 6_hours );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    dir, entry, avail );
        }
    }
    if( has_provides( "walls", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_om_fortifications" );
        const base_camps::miss_data &miss_info =
            base_camps::miss_info[ "_faction_camp_om_fortifications" ];
        entry = om_upgrade_description( "faction_wall_level_N_0" );
        mission_key.add_start( "Construct Map Fort", _( "Construct Map Fortifications" ),
                               dir, entry, npc_list.empty() );
        entry = om_upgrade_description( "faction_wall_level_N_1" );
        mission_key.add_start( "Construct Trench", _( "Construct Spiked Trench" ), dir, entry,
                               npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "recruiting", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_recruit_0" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_recruit_0" ];
        entry = recruit_description( npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), dir, entry,
                               npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "scouting", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_scout_0" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_scout_0" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion out into the great unknown.  High survival "
                                  "skills are needed to avoid combat but you should expect an "
                                  "encounter or two.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: 3\n"
                                  "Effects:\n"
                                  "> Select checkpoints to customize path.\n"
                                  "> Reveals terrain around the path.\n"
                                  "> Can bounce off hide sites to extend range.\n\n"
                                  "Risk: High\n"
                                  "Time: Travel\n"
                                  "Positions: %d/3\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), dir,
                               entry, npc_list.size() < 3 );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id,  miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "patrolling", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_camp_combat_0" );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_combat_0" ];
        entry = string_format( _( "Notes:\n"
                                  "Send a companion to purge the wasteland.  Their goal is to "
                                  "kill anything hostile they encounter and return when "
                                  "their wounds are too great or the odds are stacked against "
                                  "them.\n\n"
                                  "Skill used: survival\n"
                                  "Difficulty: 4\n"
                                  "Effects:\n"
                                  "> Pulls creatures encountered into combat instead of "
                                  "fleeing.\n"
                                  "> Select checkpoints to customize path.\n"
                                  "> Can bounce off hide sites to extend range.\n\n"
                                  "Risk: Very High\n"
                                  "Time: Travel\n"
                                  "Positions: %d/3\n" ), npc_list.size() );
        mission_key.add_start( miss_info.miss_id, miss_info.desc.translated(), cata::nullopt,
                               entry, npc_list.size() < 3 );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( miss_info.ret_miss_id, miss_info.ret_desc.translated(),
                                    cata::nullopt, entry, avail );
        }
    }
    if( has_provides( "dismantling", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_exp_chop_shop_" + dir_id );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_exp_chop_shop_" ];
        entry = _( "Notes:\n"
                   "Have a companion attempt to completely dissemble a vehicle into "
                   "components.\n\n"
                   "Skill used: mechanics\n"
                   "Difficulty: 2\n"
                   "Effects:\n"
                   "> Removed parts placed on the furniture in the garage.\n"
                   "> Skill plays a huge role to determine what is salvaged.\n\n"
                   "Risk: None\n"
                   "Time: 5 days\n" );
        mission_key.add_start( dir_id + miss_info.miss_id, dir_abbr + miss_info.desc, dir, entry,
                               npc_list.empty() );
        if( !npc_list.empty() ) {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
    std::map<recipe_id, translation> craft_recipes = recipe_deck( dir );
    if( has_provides( "kitchen", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_exp_kitchen_cooking_" + dir_id );
        const base_camps::miss_data &miss_info =
            base_camps::miss_info[ "_faction_exp_kitchen_cooking_" ];
        if( npc_list.empty() ) {
            add_available_recipes( mission_key, dir, craft_recipes );
        } else {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
    if( has_provides( "blacksmith", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_exp_blacksmith_crafting_" + dir_id );
        const base_camps::miss_data &miss_info =
            base_camps::miss_info[ "_faction_exp_blacksmith_crafting_" ];
        if( npc_list.empty() ) {
            add_available_recipes( mission_key, dir, craft_recipes );
        } else {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
    if( has_provides( "farming", dir ) ) {
        size_t plots = 0;
        comp_list npc_list = get_mission_workers( "_faction_exp_plow_" + dir_id );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_exp_plow_" ];
        if( npc_list.empty() ) {
            entry = _( "Notes:\n"
                       "Plow any spaces that have reverted to dirt or grass.\n\n" ) +
                    farm_description( omt_trg, plots, farm_ops::plow ) +
                    _( "\n\n"
                       "Skill used: fabrication\n"
                       "Difficulty: N/A\n"
                       "Effects:\n"
                       "> Restores only the plots created in the last expansion upgrade.\n"
                       "> Does not damage existing crops.\n\n"
                       "Risk: None\n"
                       "Time: 5 Min / Plot\n"
                       "Positions: 0/1\n" );
            mission_key.add_start( dir_id + miss_info.miss_id, dir_abbr + miss_info.desc, dir,
                                   entry, plots > 0 );
        } else {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
    if( has_provides( "farming", dir ) ) {
        size_t plots = 0;
        comp_list npc_list = get_mission_workers( "_faction_exp_plant_" + dir_id );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_exp_plant_" ];
        if( npc_list.empty() ) {
            entry = _( "Notes:\n"
                       "Plant designated seeds in the spaces that have already been "
                       "tilled.\n\n" ) +
                    farm_description( omt_trg, plots, farm_ops::plant ) +
                    _( "\n\n"
                       "Skill used: survival\n"
                       "Difficulty: N/A\n"
                       "Effects:\n"
                       "> Choose which seed type or all of your seeds.\n"
                       "> Stops when out of seeds or planting locations.\n"
                       "> Will plant in ALL dirt mounds in the expansion.\n\n"
                       "Risk: None\n"
                       "Time: 1 Min / Plot\n"
                       "Positions: 0/1\n" );
            mission_key.add_start( dir_id + miss_info.miss_id,
                                   dir_abbr + miss_info.desc, dir, entry,
                                   plots > 0 && warm_enough_to_plant( omt_trg ) );
        } else {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
    if( has_provides( "farming", dir ) ) {
        size_t plots = 0;
        comp_list npc_list = get_mission_workers( "_faction_exp_harvest_" + dir_id );
        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_exp_harvest_" ];
        if( npc_list.empty() ) {
            entry = _( "Notes:\n"
                       "Harvest any plants that are ripe and bring the produce back.\n\n" ) +
                    farm_description( omt_trg, plots, farm_ops::harvest ) +
                    _( "\n\n"
                       "Skill used: survival\n"
                       "Difficulty: N/A\n"
                       "Effects:\n"
                       "> Will dump all harvesting products onto your location.\n\n"
                       "Risk: None\n"
                       "Time: 3 Min / Plot\n"
                       "Positions: 0/1\n" );
            mission_key.add_start( dir_id + miss_info.miss_id,
                                   dir_abbr + miss_info.desc, dir, entry,
                                   plots > 0 );
        } else {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
    if( has_provides( "reseeding", dir ) ) {
        comp_list npc_list = get_mission_workers( "_faction_exp_farm_crafting_" + dir_id );
        const base_camps::miss_data &miss_info =
            base_camps::miss_info[ "_faction_exp_farm_crafting_" ];
        if( npc_list.empty() ) {
            add_available_recipes( mission_key, dir, craft_recipes );
        } else {
            entry = miss_info.action.translated();
            bool avail = update_time_left( entry, npc_list );
            mission_key.add_return( dir_id + miss_info.ret_miss_id,
                                    dir_abbr + miss_info.ret_desc, dir, entry, avail );
        }
    }
}
References _, add_available_recipes(), mission_data::add_return(), mission_data::add_start(), base_camps::all_directions, available_upgrades(), base_camps::base_dir, farm_description(), gathering_description(), get_mission_workers(), harvest, has_provides(), base_camps::miss_info, cata::nullopt, om_upgrade_description(), omt_pos, plant, plow, recipe_deck(), recruit_description(), string_format(), update_time_fixed(), update_time_left(), mattack::upgrade(), and warm_enough_to_plant().
Referenced by get_available_missions().
get_bb_pos()
tripoint basecamp::get_bb_pos () const inline
Definition at line 140 of file basecamp.h.
{
            return bb_pos;
        }
References bb_pos.
Referenced by npc::worker_downtime().
get_dumping_spot()
const tripoint & basecamp::get_dumping_spot () const inline
Definition at line 231 of file basecamp.h.
{
            return dumping_spot;
        }
References dumping_spot.
Referenced by talk_function::basecamp_mission(), basecamp_action_components::consume_components(), distribute_food(), form_crafting_inventory(), and place_results().
get_gatherlist()
item_group_id basecamp::get_gatherlist () const
Definition at line 381 of file basecamp.cpp.
{
    const auto &e = expansions.find( base_camps::base_dir );
    if( e != expansions.end() ) {
        const std::string gatherlist = "gathering_" +
                                       base_camps::faction_encode_abs( e->second, 4 );
        if( item_group::group_is_defined( item_group_id( gatherlist ) ) ) {
            return item_group_id( gatherlist );
        }
    }
    return item_group_id( "forest" );
}
References base_camps::base_dir, expansions, base_camps::faction_encode_abs(), and item_group::group_is_defined().
Referenced by gathering_return().
get_mission_workers()
comp_list basecamp::get_mission_workers (const std::string & mission_id, bool contains = false)
Definition at line 545 of file basecamp.cpp.
{
    comp_list available;
    for( const auto &elem : camp_workers ) {
        npc_companion_mission c_mission = elem->get_companion_mission();
        if( ( c_mission.mission_id == mission_id ) ||
            ( contains && c_mission.mission_id.find( mission_id ) != std::string::npos ) ) {
            available.push_back( elem );
        }
    }
    return available;
}
References available, camp_workers, contains, and npc_companion_mission::mission_id.
Referenced by get_available_missions(), and get_available_missions_by_dir().
get_npcs_assigned()
std::vector< npc_ptr > basecamp::get_npcs_assigned ()
Definition at line 538 of file basecamp.cpp.
{
    validate_assignees();
    return assigned_npcs;
}
References assigned_npcs, and validate_assignees().
Referenced by abandon_camp(), talk_function::companion_choose(), and job_assignment_ui().
give_equipment()
std::vector< item * > basecamp::give_equipment (std::vector< item * > equipment, const std::string & msg)
Display items listed in equipment to let the player pick what to give the departing NPC, loops until quit or empty.
Definition at line 3564 of file faction_camp.cpp.
{
    std::vector<item *> equipment_lost;
    do {
        std::vector<std::string> names;
        names.reserve( equipment.size() );
        for( auto &i : equipment ) {
            names.push_back( i->tname() + " [" + std::to_string( i->charges ) + "]" );
        }
        // Choose item if applicable
        const int i_index = uilist( msg, names );
        if( i_index < 0 || static_cast<size_t>( i_index ) >= equipment.size() ) {
            return equipment_lost;
        }
        equipment_lost.push_back( equipment[i_index] );
        equipment.erase( equipment.begin() + i_index );
    } while( !equipment.empty() );
    return equipment_lost;
}
References Name::names, and to_string().
Referenced by start_farm_op(), start_relay_hide_site(), and start_setup_hide_site().
handle_mission()
bool basecamp::handle_mission (const std::string & miss_id, const cata::optional< point > & opt_miss_dir)
Definition at line 1351 of file faction_camp.cpp.
{
    const point &miss_dir = opt_miss_dir ? *opt_miss_dir : base_camps::base_dir;
    if( miss_id == "Distribute Food" ) {
        distribute_food();
    }
    if( miss_id.size() > 12 && miss_id.substr( 0, 12 ) == "Upgrade Camp" ) {
        const std::string bldg = miss_id.substr( 12 );
        start_upgrade( bldg, base_camps::base_dir, bldg + "_faction_upgrade_camp" );
    } else if( miss_id == "Recover Ally from Upgrading" ) {
        upgrade_return( base_camps::base_dir, "_faction_upgrade_camp" );
    } else if( miss_id.size() > 27 && miss_id.substr( 0, 27 ) == "Recover Ally from Upgrading" ) {
        const std::string bldg = miss_id.substr( 27 );
        upgrade_return( base_camps::base_dir, bldg + "_faction_upgrade_camp", bldg );
    }
    if( miss_id == "Menial Labor" ) {
        start_menial_labor();
    } else if( miss_id == "Recover Menial Laborer" ) {
        menial_return();
    }
    if( miss_id == "Assign Jobs" ) {
        job_assignment_ui();
    }
    if( miss_id == "Assign Workers" ) {
        worker_assignment_ui();
    }
    if( miss_id == "Abandon Camp" ) {
        abandon_camp();
    }
    if( miss_id == "Expand Base" ) {
        start_mission( "_faction_camp_expansion", 3_hours, true,
                       _( "departs to survey land" ), false, {}, skill_gun, 0 );
    } else if( miss_id == "Recover Surveyor" ) {
        survey_return();
    }
    if( miss_id == "Gather Materials" ) {
        start_mission( "_faction_camp_gathering", 3_hours, true,
                       _( "departs to search for materials" ), false, {}, skill_survival, 0 );
    } else if( miss_id == "Recover Ally from Gathering" ) {
        gathering_return( "_faction_camp_gathering", 3_hours );
    }
    if( miss_id == "Collect Firewood" ) {
        start_mission( "_faction_camp_firewood", 3_hours, true,
                       _( "departs to search for firewood" ), false, {}, skill_survival, 0 );
    } else if( miss_id == "Recover Firewood Gatherers" ) {
        gathering_return( "_faction_camp_firewood", 3_hours );
    }
    if( miss_id == "Cut Logs" ) {
        start_cut_logs();
    } else if( miss_id == "Recover Log Cutter" ) {
        const std::string msg = _( "returns from working in the woods" );
        mission_return( "_faction_camp_cut_log", 6_hours, true, msg, "construction", 2 );
    }
    if( miss_id == "Clearcut" ) {
        start_clearcut();
    } else if( miss_id == "Recover Clearcutter" ) {
        const std::string msg = _( "returns from working in the woods" );
        mission_return( "_faction_camp_clearcut", 6_hours, true, msg, "construction", 1 );
    }
    if( miss_id == "Setup Hide Site" ) {
        start_setup_hide_site();
    } else if( miss_id == "Recover Hide Setup" ) {
        const std::string msg = _( "returns from working on the hide site" );
        mission_return( "_faction_camp_hide_site", 3_hours, true, msg, "survival", 3 );
    }
    if( miss_id == "Relay Hide Site" ) {
        start_relay_hide_site();
    } else if( miss_id == "Recover Hide Transport" ) {
        const std::string msg = _( "returns from shuttling gear between the hide site" );
        mission_return( "_faction_camp_hide_trans", 3_hours, true, msg, "survival", 3 );
    }
    if( miss_id == "Camp Forage" ) {
        start_mission( "_faction_camp_foraging", 4_hours, true,
                       _( "departs to search for edible plants" ), false, {}, skill_survival, 0 );
    } else if( miss_id == "Recover Foragers" ) {
        gathering_return( "_faction_camp_foraging", 4_hours );
    }
    if( miss_id == "Trap Small Game" ) {
        start_mission( "_faction_camp_trapping", 6_hours, true,
                       _( "departs to set traps for small animals" ), false, {}, skill_traps, 0 );
    } else if( miss_id == "Recover Trappers" ) {
        gathering_return( "_faction_camp_trapping", 6_hours );
    }
    if( miss_id == "Hunt Large Animals" ) {
        start_mission( "_faction_camp_hunting", 6_hours, true,
                       _( "departs to hunt for meat" ), false, {}, skill_gun, 0 );
    } else if( miss_id == "Recover Hunter" ) {
        gathering_return( "_faction_camp_hunting", 6_hours );
    }
    if( miss_id == "Construct Map Fort" || miss_id == "Construct Trench" ) {
        std::string bldg_exp = "faction_wall_level_N_0";
        if( miss_id == "Construct Trench" ) {
            bldg_exp = "faction_wall_level_N_1";
        }
        start_fortifications( bldg_exp );
    } else if( miss_id == "Finish Map Fort" ) {
        fortifications_return();
    }
    if( miss_id == "Recruit Companions" ) {
        start_mission( "_faction_camp_recruit_0", 4_days, true,
                       _( "departs to search for recruits" ), false, {}, skill_gun, 0 );
    } else if( miss_id == "Recover Recruiter" ) {
        recruit_return( "_faction_camp_recruit_0", recruit_evaluation() );
    }
    if( miss_id == "Scout Mission" ) {
        start_combat_mission( "_faction_camp_scout_0" );
    } else if( miss_id == "Combat Patrol" ) {
        start_combat_mission( "_faction_camp_combat_0" );
    } else if( miss_id == "Recover Scout" ) {
        combat_mission_return( "_faction_camp_scout_0" );
    } else if( miss_id == "Recover Combat Patrol" ) {
        combat_mission_return( "_faction_camp_combat_0" );
    }
    const std::string base_dir_id = base_camps::all_directions.at( base_camps::base_dir ).id;
    const std::string miss_dir_id = base_camps::all_directions.at( miss_dir ).id;
    const tripoint_abs_omt omt_trg = omt_pos + miss_dir;
    if( miss_id.substr( 0, 18 + miss_dir_id.size() ) == miss_dir_id + " Expansion Upgrade" ) {
        const std::string bldg = miss_id.substr( 18 + miss_dir_id.size() );
        start_upgrade( bldg, miss_dir, bldg + "_faction_upgrade_exp_" + miss_dir_id );
    } else if( miss_id == "Recover Ally, " + miss_dir_id + " Expansion" ) {
        upgrade_return( miss_dir, "_faction_upgrade_exp_" + miss_dir_id );
    } else {
        const std::string search_str = "Recover Ally, " + miss_dir_id + " Expansion";
        size_t search_len = search_str.size();
        if( miss_id.size() > search_len && miss_id.substr( 0, search_len ) == search_str ) {
            const std::string bldg = miss_id.substr( search_len );
            upgrade_return( miss_dir, bldg + "_faction_upgrade_exp_" + miss_dir_id, bldg );
        }
    }
    start_crafting( miss_id, miss_dir, "BASE", "_faction_camp_crafting_" );
    start_crafting( miss_id, miss_dir, "FARM", "_faction_exp_farm_crafting_" );
    if( miss_id == base_dir_id + " (Finish) Crafting" ) {
        const std::string msg = _( "returns to you with something" );
        mission_return( "_faction_camp_crafting_" + miss_dir_id, 1_minutes, true, msg,
                        "construction", 2 );
    } else if( miss_id == miss_dir_id + " (Finish) Crafting" ) {
        const std::string msg = _( "returns from your farm with something" );
        mission_return( "_faction_exp_farm_crafting_" + miss_dir_id, 1_minutes, true, msg,
                        "construction", 2 );
    }
    start_crafting( miss_id, miss_dir, "COOK", "_faction_exp_kitchen_cooking_" );
    if( miss_id == miss_dir_id + " (Finish) Cooking" ) {
        const std::string msg = _( "returns from your kitchen with something" );
        mission_return( "_faction_exp_kitchen_cooking_" + miss_dir_id, 1_minutes,
                        true, msg, "cooking", 2 );
    }
    start_crafting( miss_id, miss_dir, "SMITH", "_faction_exp_blacksmith_crafting_" );
    if( miss_id == miss_dir_id + " (Finish) Smithing" ) {
        const std::string msg = _( "returns from your blacksmith shop with something" );
        mission_return( "_faction_exp_blacksmith_crafting_" + miss_dir_id, 1_minutes,
                        true, msg, "fabrication", 2 );
    }
    if( miss_id == miss_dir_id + " Plow Fields" ) {
        start_farm_op( miss_dir, omt_trg, farm_ops::plow );
    } else if( miss_id == miss_dir_id + " (Finish) Plow Fields" ) {
        farm_return( "_faction_exp_plow_" + miss_dir_id, omt_trg, farm_ops::plow );
    }
    if( miss_id == miss_dir_id + " Plant Fields" ) {
        start_farm_op( miss_dir, omt_trg, farm_ops::plant );
    } else if( miss_id == miss_dir_id + " (Finish) Plant Fields" ) {
        farm_return( "_faction_exp_plant_" + miss_dir_id, omt_trg, farm_ops::plant );
    }
    if( miss_id == miss_dir_id + " Harvest Fields" ) {
        start_farm_op( miss_dir, omt_trg, farm_ops::harvest );
    }  else if( miss_id == miss_dir_id + " (Finish) Harvest Fields" ) {
        farm_return( "_faction_exp_harvest_" + miss_dir_id, omt_trg, farm_ops::harvest );
    }
    if( miss_id == miss_dir_id + " Chop Shop" ) {
        start_garage_chop( miss_dir, omt_trg );
    } else if( miss_id == miss_dir_id + " (Finish) Chop Shop" ) {
        const std::string msg = _( "returns from your garage" );
        mission_return( "_faction_exp_chop_shop_" + miss_dir_id, 5_days, true, msg,
                        "mechanics", 2 );
    }
    if( miss_id == "Emergency Recall" ) {
        emergency_recall();
    }
    return true;
}
References _, abandon_camp(), base_camps::all_directions, base_camps::base_dir, combat_mission_return(), distribute_food(), emergency_recall(), farm_return(), fortifications_return(), gathering_return(), harvest, job_assignment_ui(), menial_return(), mission_return(), omt_pos, plant, plow, recruit_evaluation(), recruit_return(), skill_gun, skill_survival, skill_traps, start_clearcut(), start_combat_mission(), start_crafting(), start_cut_logs(), start_farm_op(), start_fortifications(), start_garage_chop(), start_menial_labor(), start_mission(), start_relay_hide_site(), start_setup_hide_site(), start_upgrade(), survey_return(), upgrade_return(), and worker_assignment_ui().
Referenced by talk_function::basecamp_mission(), and iexamine::bulletin_board().
has_provides() [1/2]
bool basecamp::has_provides (const std::string & req, const cata::optional< point > & dir = cata::nullopt, int level = 0) const
Definition at line 269 of file basecamp.cpp.
{
    if( !dir ) {
        for( const auto &e : expansions ) {
            if( has_provides( req, e.second, level ) ) {
                return true;
            }
        }
    } else {
        const auto &e = expansions.find( *dir );
        if( e != expansions.end() ) {
            return has_provides( req, e->second, level );
        }
    }
    return false;
}
References expansions, and has_provides().
has_provides() [2/2]
bool basecamp::has_provides (const std::string & req, const expansion_data & e_data, int level = 0) const
Definition at line 259 of file basecamp.cpp.
{
    for( const auto &provide : e_data.provides ) {
        if( provide.first == req && provide.second > level ) {
            return true;
        }
    }
    return false;
}
References expansion_data::provides.
Referenced by can_expand(), distribute_food(), npc::faction_display(), get_available_missions_by_dir(), has_provides(), has_water(), and recruit_evaluation().
has_water()
bool basecamp::has_water ()
Definition at line 292 of file basecamp.cpp.
{
    return has_provides( "water_well" ) || has_provides( "fbmh_well_north" ) ||
           has_provides( "faction_base_camp_12" ) || has_provides( "faction_base_kitchen_6" ) ||
           has_provides( "faction_base_blacksmith_11" );
}
References has_provides().
Referenced by npc::consume_food_from_camp(), and finish_return().
hunting_results()
void basecamp::hunting_results (int skill, const std::string & task, int attempts, int difficulty)
spawn items or corpses based on search attempts
Parameters
skill skill level of the search
task string to identify what types of corpses to provide (_faction_camp_hunting or _faction_camp_trapping)
attempts number of skill checks to make
difficulty a random number from 0 to difficulty is created for each attempt, and if skill is higher, an item or corpse is spawned
Definition at line 3076 of file faction_camp.cpp.
{
    // no item groups for corpses, so we'll have to improvise
    weighted_int_list<mtype_id> hunting_targets;
    hunting_targets.add( mon_beaver, 10 );
    hunting_targets.add( mon_fox_red, 10 );
    hunting_targets.add( mon_fox_gray, 10 );
    hunting_targets.add( mon_mink, 5 );
    hunting_targets.add( mon_muskrat, 10 );
    hunting_targets.add( mon_otter, 10 );
    hunting_targets.add( mon_duck, 10 );
    hunting_targets.add( mon_cockatrice, 1 );
    if( task == "_faction_camp_trapping" ) {
        hunting_targets.add( mon_black_rat, 40 );
        hunting_targets.add( mon_chipmunk, 30 );
        hunting_targets.add( mon_groundhog, 30 );
        hunting_targets.add( mon_hare, 20 );
        hunting_targets.add( mon_lemming, 40 );
        hunting_targets.add( mon_opossum, 10 );
        hunting_targets.add( mon_rabbit, 20 );
        hunting_targets.add( mon_squirrel, 20 );
        hunting_targets.add( mon_weasel, 20 );
        hunting_targets.add( mon_chicken, 10 );
        hunting_targets.add( mon_grouse, 10 );
        hunting_targets.add( mon_pheasant, 10 );
        hunting_targets.add( mon_turkey, 20 );
    } else if( task == "_faction_camp_hunting" ) {
        hunting_targets.add( mon_chicken, 20 );
        // good luck hunting upland game birds without dogs
        hunting_targets.add( mon_grouse, 2 );
        hunting_targets.add( mon_pheasant, 2 );
        hunting_targets.add( mon_turkey, 10 );
        hunting_targets.add( mon_bear, 1 );
        hunting_targets.add( mon_cougar, 5 );
        hunting_targets.add( mon_cow, 1 );
        hunting_targets.add( mon_coyote, 15 );
        hunting_targets.add( mon_deer, 2 );
        hunting_targets.add( mon_moose, 1 );
        hunting_targets.add( mon_pig, 1 );
        hunting_targets.add( mon_wolf, 10 );
    }
    for( int i = 0; i < attempts; i++ ) {
        if( skill > rng( 0, difficulty ) ) {
            const mtype_id *target = hunting_targets.pick();
            auto result = item::make_corpse( *target, calendar::turn, "" );
            if( !result.is_null() ) {
                place_results( result );
            }
        }
    }
}
References weighted_list< W, T >::add(), item::make_corpse(), mon_bear, mon_beaver, mon_black_rat, mon_chicken, mon_chipmunk, mon_cockatrice, mon_cougar, mon_cow, mon_coyote, mon_deer, mon_duck, mon_fox_gray, mon_fox_red, mon_groundhog, mon_grouse, mon_hare, mon_lemming, mon_mink, mon_moose, mon_muskrat, mon_opossum, mon_otter, mon_pheasant, mon_pig, mon_rabbit, mon_squirrel, mon_turkey, mon_weasel, mon_wolf, weighted_list< W, T >::pick(), place_results(), rng(), and calendar::turn.
Referenced by gathering_return().
is_valid()
bool basecamp::is_valid () const inline
Definition at line 125 of file basecamp.h.
{
            return !name.empty() && omt_pos != tripoint_abs_omt();
        }
References name, and omt_pos.
Referenced by update_in_progress(), update_provides(), update_resources(), and game::validate_camps().
job_assignment_ui()
void basecamp::job_assignment_ui ()
Definition at line 1746 of file faction_camp.cpp.
{
    int entries_per_page = 0;
    catacurses::window w_jobs;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const point term( TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0,
                          TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 );
        w_jobs = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                     point( term.y, term.x ) );
        entries_per_page = FULL_SCREEN_HEIGHT - 4;
        ui.position_from_window( w_jobs );
    } );
    ui.mark_resize();
    size_t selection = 0;
    input_context ctxt( "FACTION MANAGER" );
    ctxt.register_updown();
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    validate_assignees();
    std::vector<npc *> stationed_npcs;
    npc *cur_npc = nullptr;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_jobs );
        const size_t top_of_page = entries_per_page * ( selection / entries_per_page );
        for( int i = 0; i < FULL_SCREEN_HEIGHT - 1; i++ ) {
            mvwputch( w_jobs, point( 45, i ), BORDER_COLOR, LINE_XOXO );
        }
        draw_border( w_jobs );
        mvwprintz( w_jobs, point( 46, 1 ), c_white, _( "Job/Priority" ) );
        const nc_color col = c_white;
        const std::string no_npcs = _( "There are no npcs stationed here" );
        if( !stationed_npcs.empty() ) {
            draw_scrollbar( w_jobs, selection, entries_per_page, stationed_npcs.size(),
                            point( 0, 3 ) );
            for( size_t i = top_of_page; i < stationed_npcs.size(); i++ ) {
                const int y = i - top_of_page + 3;
                trim_and_print( w_jobs, point( 1, y ), 43, selection == i ? hilite( col ) : col,
                                stationed_npcs[i]->disp_name() );
            }
            if( selection < stationed_npcs.size() ) {
                int start_y = 3;
                if( cur_npc ) {
                    if( cur_npc->has_job() ) {
                        for( activity_id &elem : cur_npc->job.get_prioritised_vector() ) {
                            const int priority = cur_npc->job.get_priority_of_job( elem );
                            player_activity test_act = player_activity( elem );
                            mvwprintz( w_jobs, point( 46, start_y ), c_light_gray, string_format( _( "%s : %s" ),
                                       test_act.get_verb(), std::to_string( priority ) ) );
                            start_y++;
                        }
                    } else {
                        mvwprintz( w_jobs, point( 46, start_y ), c_light_red, _( "No current job." ) );
                    }
                }
            } else {
                mvwprintz( w_jobs, point( 46, 4 ), c_light_red, no_npcs );
            }
        } else {
            mvwprintz( w_jobs, point( 46, 4 ), c_light_red, no_npcs );
        }
        mvwprintz( w_jobs, point( 1, FULL_SCREEN_HEIGHT - 1 ), c_light_gray,
                   _( "Press %s to change this workers job priorities." ), ctxt.get_desc( "CONFIRM" ) );
        wnoutrefresh( w_jobs );
    } );
    while( true ) {
        // create a list of npcs stationed at this camp
        stationed_npcs.clear();
        for( const auto &elem : get_npcs_assigned() ) {
            if( elem ) {
                stationed_npcs.push_back( elem.get() );
            }
        }
        cur_npc = nullptr;
        // entries_per_page * page number
        if( !stationed_npcs.empty() ) {
            cur_npc = stationed_npcs[selection];
        }
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "DOWN" ) {
            selection++;
            if( selection >= stationed_npcs.size() ) {
                selection = 0;
            }
        } else if( action == "UP" ) {
            if( selection == 0 ) {
                selection = stationed_npcs.empty() ? 0 : stationed_npcs.size() - 1;
            } else {
                selection--;
            }
        } else if( action == "CONFIRM" ) {
            if( cur_npc ) {
                while( true ) {
                    uilist smenu;
                    smenu.text = _( "Assign job priority ( 0 to disable )" );
                    int count = 0;
                    std::vector<activity_id> job_vec = cur_npc->job.get_prioritised_vector();
                    smenu.addentry( count, true, 'C', _( "Clear all priorities" ) );
                    count++;
                    for( const activity_id &elem : job_vec ) {
                        player_activity test_act = player_activity( elem );
                        const int priority = cur_npc->job.get_priority_of_job( elem );
                        smenu.addentry( count, true, MENU_AUTOASSIGN, string_format( _( "%s : %s" ), test_act.get_verb(),
                                        std::to_string( priority ) ) );
                        count++;
                    }
                    smenu.query();
                    if( smenu.ret == UILIST_CANCEL ) {
                        break;
                    } else if( smenu.ret == 0 ) {
                        cur_npc->job.clear_all_priorities();
                    } else if( smenu.ret > 0 && smenu.ret <= static_cast<int>( job_vec.size() ) ) {
                        activity_id sel_job = job_vec[smenu.ret - 1];
                        player_activity test_act = player_activity( sel_job );
                        const std::string formatted = string_format( _( "Priority for %s " ), test_act.get_verb() );
                        const int amount = string_input_popup()
                                           .title( formatted )
                                           .width( 20 )
                                           .only_digits( true )
                                           .query_int();
                        cur_npc->job.set_task_priority( sel_job, amount );
                    } else {
                        break;
                    }
                }
            }
        } else if( action == "QUIT" ) {
            break;
        }
    }
}
References _, action, uilist::addentry(), BORDER_COLOR, c_light_gray, c_light_red, c_white, job_data::clear_all_priorities(), detail::count(), draw_border(), draw_scrollbar(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::get_desc(), get_npcs_assigned(), job_data::get_prioritised_vector(), job_data::get_priority_of_job(), player_activity::get_verb(), input_context::handle_input(), npc::has_job(), hilite(), npc::job, LINE_XOXO, MENU_AUTOASSIGN, mvwprintz(), mvwputch(), catacurses::newwin(), string_input_popup::only_digits(), uilist::query(), string_input_popup::query_int(), ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), uilist::ret, job_data::set_task_priority(), string_format(), TERMX, TERMY, uilist::text, string_input_popup::title(), to_string(), trim_and_print(), UILIST_CANCEL, validate_assignees(), catacurses::werase(), string_input_popup::width(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by talk_function::assign_camp(), and handle_mission().
load_data()
void basecamp::load_data (const std::string & data)
Definition at line 697 of file basecamp.cpp.
{
    std::stringstream stream( data );
    stream >> name >> bb_pos.x >> bb_pos.y;
    // add space to name
    replace( name.begin(), name.end(), '_', ' ' );
}
References bb_pos, name, tripoint::x, and tripoint::y.
menial_return()
bool basecamp::menial_return ()
Definition at line 2638 of file faction_camp.cpp.
{
    const std::string msg = _( "returns from doing the dirty work to keep the camp running" );
    npc_ptr comp = mission_return( "_faction_camp_menial", 3_hours, true, msg, "menial", 2 );
    if( comp == nullptr ) {
        return false;
    }
    comp->revert_after_activity();
    return true;
}
References _, and mission_return().
Referenced by handle_mission().
mission_return()
npc_ptr basecamp::mission_return (const std::string & miss_id, time_duration min_duration, bool fixed_time, const std::string & return_msg, const std::string & skill, int difficulty)
a wrapper function for companion_choose_return and finish_return
Definition at line 2574 of file faction_camp.cpp.
{
    npc_ptr comp = companion_choose_return( miss_id, min_duration );
    if( comp != nullptr ) {
        finish_return( *comp, fixed_time, return_msg, skill, difficulty );
    }
    return comp;
}
References companion_choose_return(), and finish_return().
Referenced by handle_mission(), menial_return(), and recruit_return().
next_upgrade()
std::string basecamp::next_upgrade (const point & dir, int offset = 1) const
Returns the name of the building the current building dir upgrades into, "null" if there isn't one.
Definition at line 236 of file basecamp.cpp.
{
    const auto &e = expansions.find( dir );
    if( e == expansions.end() ) {
        return "null";
    }
    const expansion_data &e_data = e->second;
    int cur_level = -1;
    for( int i = 0; i < base_camps::max_upgrade_by_type( e_data.type ); i++ ) {
        const std::string candidate = base_camps::faction_encode_abs( e_data, i );
        if( e_data.provides.find( candidate ) == e_data.provides.end() ) {
            break;
        } else {
            cur_level = i;
        }
    }
    if( cur_level >= 0 ) {
        return base_camps::faction_encode_abs( e_data, cur_level + offset );
    }
    return "null";
}
References expansions, base_camps::faction_encode_abs(), base_camps::max_upgrade_by_type(), expansion_data::provides, and expansion_data::type.
Referenced by faction_display(), and upgrade_return().
om_upgrade_description()
std::string basecamp::om_upgrade_description (const std::string & bldg, bool trunc = false) const
Returns the description for the recipe of the next building bldg.
Definition at line 208 of file basecamp.cpp.
{
    const recipe &making = recipe_id( bldg ).obj();
    std::vector<std::string> component_print_buffer;
    const int pane = FULL_SCREEN_WIDTH;
    const auto tools = making.simple_requirements().get_folded_tools_list( pane, c_white, _inv, 1 );
    const auto comps = making.simple_requirements().get_folded_components_list( pane, c_white, _inv,
                       making.get_component_filter(), 1 );
    component_print_buffer.insert( component_print_buffer.end(), tools.begin(), tools.end() );
    component_print_buffer.insert( component_print_buffer.end(), comps.begin(), comps.end() );
    std::string comp;
    for( auto &elem : component_print_buffer ) {
        comp = comp + elem + "\n";
    }
    comp = string_format( _( "Notes:\n%s\n\nSkills used: %s\n%s\n" ),
                          making.description, making.required_all_skills_string(), comp );
    if( !trunc ) {
        time_duration base_time = making.batch_duration();
        comp += string_format( _( "Risk: None\nTime: %s\n" ),
                               to_string( base_camps::to_workdays( base_time ) ) );
    }
    return comp;
}
References _, _inv, recipe::batch_duration(), c_white, recipe::description, FULL_SCREEN_WIDTH, recipe::get_component_filter(), requirement_data::get_folded_components_list(), requirement_data::get_folded_tools_list(), string_id< T >::obj(), recipe::required_all_skills_string(), recipe::simple_requirements(), string_format(), to_string(), and base_camps::to_workdays().
Referenced by faction_display(), get_available_missions(), and get_available_missions_by_dir().
parse_expansion()
expansion_data basecamp::parse_expansion (const std::string & terrain, const tripoint_abs_omt & new_pos)
Definition at line 141 of file basecamp.cpp.
{
    expansion_data e;
    int last_bar = terrain.find_last_of( '_' );
    e.type = terrain.substr( base_camps::prefix_len, last_bar - base_camps::prefix_len );
    e.cur_level = std::stoi( terrain.substr( last_bar + 1 ) );
    e.pos = new_pos;
    return e;
}
References expansion_data::cur_level, expansion_data::pos, base_camps::prefix_len, terrain, and expansion_data::type.
Referenced by add_expansion(), and define_camp().
place_results()
void basecamp::place_results (item result)
Definition at line 3989 of file faction_camp.cpp.
{
    if( by_radio ) {
        tinymap target_bay;
        target_bay.load( project_to<coords::sm>( omt_pos ), false );
        const tripoint &new_spot = target_bay.getlocal( get_dumping_spot() );
        target_bay.add_item_or_charges( new_spot, result, true );
        apply_camp_ownership( new_spot, 10 );
        target_bay.save();
    } else {
        map &here = get_map();
        auto &mgr = zone_manager::get_manager();
        if( here.check_vehicle_zones( g->get_levz() ) ) {
            mgr.cache_vzones();
        }
        const auto abspos = here.getabs( g->u.pos() );
        if( mgr.has_near( zone_type_camp_storage, abspos ) ) {
            const auto &src_set = mgr.get_near( zone_type_camp_storage, abspos );
            const auto &src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
            // Find the nearest unsorted zone to dump objects at
            for( auto &src : src_sorted ) {
                const auto &src_loc = here.getlocal( src );
                here.add_item_or_charges( src_loc, result, true );
                apply_camp_ownership( src_loc, 10 );
                break;
            }
            //or dump them at players feet
        } else {
            here.add_item_or_charges( g->u.pos(), result, true );
            apply_camp_ownership( g->u.pos(), 0 );
        }
    }
}
References map::add_item_or_charges(), apply_camp_ownership(), by_radio, map::check_vehicle_zones(), g, get_dumping_spot(), zone_manager::get_manager(), get_map(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), map::load(), omt_pos, map::save(), and zone_type_camp_storage.
Referenced by finish_return(), hunting_results(), and search_results().
query_new_name()
void basecamp::query_new_name ()
Definition at line 558 of file basecamp.cpp.
{
    std::string camp_name;
    string_input_popup popup;
    popup.title( _( "Name this camp" ) )
    .width( 40 )
    .text( "" )
    .max_length( 25 )
    .query();
    if( popup.canceled() || popup.text().empty() ) {
        camp_name = "faction_camp";
    } else {
        camp_name = popup.text();
    }
    name = camp_name;
}
References _, camp_name(), name, and popup().
Referenced by define_camp(), and faction_manager::display().
recipe_batch_max()
int basecamp::recipe_batch_max (const recipe & making) const
Definition at line 3042 of file faction_camp.cpp.
{
    int max_batch = 0;
    const int max_checks = 9;
    for( size_t batch_size = 1000; batch_size > 0; batch_size /= 10 ) {
        for( int iter = 0; iter < max_checks; iter++ ) {
            time_duration work_days = base_camps::to_workdays( making.batch_duration(
                                          max_batch + batch_size ) );
            int food_req = time_to_food( work_days );
            bool can_make = making.deduped_requirements().can_make_with_inventory(
                                _inv, making.get_component_filter(), max_batch + batch_size );
            if( can_make && camp_food_supply() > food_req ) {
                max_batch += batch_size;
            } else {
                break;
            }
        }
    }
    return max_batch;
}
References _inv, recipe::batch_duration(), camp_food_supply(), deduped_requirement_data::can_make_with_inventory(), recipe::deduped_requirements(), recipe::get_component_filter(), time_to_food(), and base_camps::to_workdays().
Referenced by start_crafting().
recipe_deck() [1/2]
std::map< recipe_id, translation > basecamp::recipe_deck (const point & dir) const
Definition at line 361 of file basecamp.cpp.
{
    std::map<recipe_id, translation> recipes;
    const auto &e = expansions.find( dir );
    if( e == expansions.end() ) {
        return recipes;
    }
    for( const auto &provides : e->second.provides ) {
        const auto &test_s = recipe_group::get_recipes_by_id( provides.first );
        recipes.insert( test_s.cbegin(), test_s.cend() );
    }
    return recipes;
}
References expansions, and recipe_group::get_recipes_by_id().
Referenced by get_available_missions(), get_available_missions_by_dir(), and start_crafting().
recipe_deck() [2/2]
std::map< recipe_id, translation > basecamp::recipe_deck (const std::string & bldg) const
Definition at line 375 of file basecamp.cpp.
{
    const std::map<recipe_id, translation> recipes = recipe_group::get_recipes_by_bldg( bldg );
    return recipes;
}
References recipe_group::get_recipes_by_bldg().
recruit_description()
std::string basecamp::recruit_description (int npc_count)
Definition at line 3747 of file faction_camp.cpp.
{
    int sbase;
    int sexpansions;
    int sfaction;
    int sbonus;
    int total = recruit_evaluation( sbase, sexpansions, sfaction, sbonus );
    std::string desc = string_format( _( "Notes:\n"
                                         "Recruiting additional followers is very dangerous and "
                                         "expensive.  The outcome is heavily dependent on the "
                                         "skill of the  companion you send and the appeal of "
                                         "your base.\n\n"
                                         "Skill used: speech\n"
                                         "Difficulty: 2\n"
                                         "Base Score:                   +%3d%%\n"
                                         "> Expansion Bonus:            +%3d%%\n"
                                         "> Faction Bonus:              +%3d%%\n"
                                         "> Special Bonus:              +%3d%%\n\n"
                                         "Total: Skill                  +%3d%%\n\n"
                                         "Risk: High\n"
                                         "Time: 4 Days\n"
                                         "Positions: %d/1\n" ), sbase, sexpansions, sfaction,
                                      sbonus, total, npc_count );
    return desc;
}
References _, recruit_evaluation(), and string_format().
Referenced by get_available_missions_by_dir().
recruit_evaluation() [1/2]
int basecamp::recruit_evaluation () const
Definition at line 3738 of file faction_camp.cpp.
{
    int sbase;
    int sexpansions;
    int sfaction;
    int sbonus;
    return recruit_evaluation( sbase, sexpansions, sfaction, sbonus );
}
References recruit_evaluation().
Referenced by handle_mission(), recruit_description(), and recruit_evaluation().
recruit_evaluation() [2/2]
int basecamp::recruit_evaluation (int & sbase, int & sexpansions, int & sfaction, int & sbonus) const
Definition at line 3696 of file faction_camp.cpp.
{
    auto e = expansions.find( base_camps::base_dir );
    if( e == expansions.end() ) {
        sbase = 0;
        sexpansions = 0;
        sfaction = 0;
        sbonus = 0;
        return 0;
    }
    sbase = e->second.cur_level * 5;
    sexpansions = expansions.size() * 2;
    //How could we ever starve?
    //More than 5 farms at recruiting base
    int farm = 0;
    for( const point &dir : directions ) {
        if( has_provides( "farming", dir ) ) {
            farm++;
        }
    }
    sfaction = std::min( camp_food_supply() / 10000, 10 );
    sfaction += std::min( camp_discipline() / 10, 5 );
    sfaction += std::min( camp_morale() / 10, 5 );
    //Secret or Hidden Bonus
    //Please avoid openly discussing so that there is some mystery to the system
    sbonus = 0;
    if( farm >= 5 ) {
        sbonus += 10;
    }
    //More machine than man
    //Bionics count > 10, respect > 75
    if( g->u.get_bionics().size() > 10 && camp_discipline() > 75 ) {
        sbonus += 10;
    }
    //Survival of the fittest
    if( g->get_kill_tracker().npc_kill_count() > 10 ) {
        sbonus += 10;
    }
    return sbase + sexpansions + sfaction + sbonus;
}
References base_camps::base_dir, camp_discipline(), camp_food_supply(), camp_morale(), directions, expansions, g, and has_provides().
recruit_return()
void basecamp::recruit_return (const std::string & task, int score)
Definition at line 2768 of file faction_camp.cpp.
{
    const std::string msg = _( "returns from searching for recruits with "
                               "a bit more experience" );
    npc_ptr comp = mission_return( task, 4_days, true, msg, "recruiting", 2 );
    if( comp == nullptr ) {
        return;
    }
    npc_ptr recruit;
    //Success of finding an NPC to recruit, based on survival/tracking
    int skill = comp->get_skill_level( skill_survival );
    if( rng( 1, 20 ) + skill > 17 ) {
        recruit = make_shared_fast<npc>();
        recruit->normalize();
        recruit->randomize();
        popup( _( "%s encountered %s" ), comp->name, recruit->name );
    } else {
        popup( _( "%s didn't find anyone to recruit" ), comp->name );
        return;
    }
    //Chance of convincing them to come back
    skill = ( 100 * comp->get_skill_level( skill_speech ) + score ) / 100;
    if( rng( 1, 20 ) + skill  > 19 ) {
        popup( _( "%s convinced %s to hear a recruitment offer from you" ), comp->name,
               recruit->name );
    } else {
        popup( _( "%s wasn't interested in anything %s had to offer" ), recruit->name,
               comp->name );
        return;
    }
    //Stat window
    int rec_m = 0;
    int appeal = rng( -5, 3 ) + std::min( skill / 3, 3 );
    int food_desire = rng( 0, 5 );
    while( rec_m >= 0 ) {
        std::string description = _( "NPC Overview:\n\n" );
        description += string_format( _( "Name:  %s\n\n" ), right_justify( recruit->name, 20 ) );
        description += string_format( _( "Strength:        %10d\n" ), recruit->str_max );
        description += string_format( _( "Dexterity:       %10d\n" ), recruit->dex_max );
        description += string_format( _( "Intelligence:    %10d\n" ), recruit->int_max );
        description += string_format( _( "Perception:      %10d\n\n" ), recruit->per_max );
        description += _( "Top 3 Skills:\n" );
        const auto skillslist = Skill::get_skills_sorted_by(
        [&]( const Skill & a, const Skill & b ) {
            const int level_a = recruit->get_skill_level( a.ident() );
            const int level_b = recruit->get_skill_level( b.ident() );
            return localized_compare( std::make_pair( -level_a, a.name() ),
                                      std::make_pair( -level_b, b.name() ) );
        } );
        description += string_format( "%s:          %4d\n", right_justify( skillslist[0]->name(), 12 ),
                                      recruit->get_skill_level( skillslist[0]->ident() ) );
        description += string_format( "%s:          %4d\n", right_justify( skillslist[1]->name(), 12 ),
                                      recruit->get_skill_level( skillslist[1]->ident() ) );
        description += string_format( "%s:          %4d\n\n", right_justify( skillslist[2]->name(), 12 ),
                                      recruit->get_skill_level( skillslist[2]->ident() ) );
        description += _( "Asking for:\n" );
        description += string_format( _( "> Food:     %10d days\n\n" ), food_desire );
        description += string_format( _( "Faction Food:%9d days\n\n" ),
                                      camp_food_supply( 0, true ) );
        description += string_format( _( "Recruit Chance: %10d%%\n\n" ),
                                      std::min( 100 * ( 10 + appeal ) / 20, 100 ) );
        description += _( "Select an option:" );
        std::vector<std::string> rec_options;
        rec_options.push_back( _( "Increase Food" ) );
        rec_options.push_back( _( "Decrease Food" ) );
        rec_options.push_back( _( "Make Offer" ) );
        rec_options.push_back( _( "Not Interested" ) );
        rec_m = uilist( description, rec_options );
        if( rec_m < 0 || rec_m == 3 || static_cast<size_t>( rec_m ) >= rec_options.size() ) {
            popup( _( "You decide you aren't interested" ) );
            return;
        }
        if( rec_m == 0 && food_desire + 1 <= camp_food_supply( 0, true ) ) {
            food_desire++;
            appeal++;
        }
        if( rec_m == 1 ) {
            if( food_desire > 0 ) {
                food_desire--;
                appeal--;
            }
        }
        if( rec_m == 2 ) {
            break;
        }
    }
    // Roll for recruitment
    if( rng( 1, 20 ) + appeal >= 10 ) {
        popup( _( "%s has been convinced to join!" ), recruit->name );
    } else {
        popup( _( "%s wasn't interested" ), recruit->name );
        // nullptr;
        return;
    }
    // Time durations always subtract from camp food supply
    camp_food_supply( 1_days * food_desire );
    recruit->spawn_at_precise( { g->get_levx(), g->get_levy() }, g->u.pos() + point( -4, -4 ) );
    overmap_buffer.insert_npc( recruit );
    recruit->form_opinion( g->u );
    recruit->mission = NPC_MISSION_NULL;
    recruit->add_new_mission( mission::reserve_random( ORIGIN_ANY_NPC,
                              recruit->global_omt_location(),
                              recruit->getID() ) );
    talk_function::follow( *recruit );
    g->load_npcs();
}
References _, a, b, camp_food_supply(), talk_function::follow(), g, Skill::get_skills_sorted_by(), overmapbuffer::insert_npc(), localized_compare, mission_return(), name, NPC_MISSION_NULL, ORIGIN_ANY_NPC, overmap_buffer, popup(), mission::reserve_random(), right_justify(), rng(), skill_speech, skill_survival, and string_format().
Referenced by handle_mission().
remove_assignee()
void basecamp::remove_assignee (character_id id)
Definition at line 497 of file basecamp.cpp.
{
    npc_ptr npc_to_remove = overmap_buffer.find_npc( id );
    if( !npc_to_remove ) {
        debugmsg( "cant find npc to remove from basecamp, on the overmap_buffer" );
        return;
    }
    npc_to_remove->assigned_camp = cata::nullopt;
    assigned_npcs.erase( std::remove( assigned_npcs.begin(), assigned_npcs.end(), npc_to_remove ),
                         assigned_npcs.end() );
}
References assigned_npcs, debugmsg, overmapbuffer::find_npc(), cata::nullopt, and overmap_buffer.
reset_camp_resources()
void basecamp::reset_camp_resources () private
Definition at line 451 of file basecamp.cpp.
{
    reset_camp_workers();
    if( !resources_updated ) {
        resources_updated = true;
        for( auto &e : expansions ) {
            expansion_data &e_data = e.second;
            for( int level = 0; level <= e_data.cur_level; level++ ) {
                const std::string &bldg = base_camps::faction_encode_abs( e_data, level );
                if( bldg == "null" ) {
                    break;
                }
                update_provides( bldg, e_data );
            }
            for( const auto &bp_provides : e_data.provides ) {
                update_resources( bp_provides.first );
            }
        }
    }
    form_crafting_inventory();
}
References expansion_data::cur_level, expansions, base_camps::faction_encode_abs(), form_crafting_inventory(), expansion_data::provides, reset_camp_workers(), resources_updated, update_provides(), and update_resources().
Referenced by add_expansion(), and get_available_missions().
reset_camp_workers()
void basecamp::reset_camp_workers ()
Definition at line 475 of file basecamp.cpp.
{
    camp_workers.clear();
    for( const auto &elem : overmap_buffer.get_companion_mission_npcs() ) {
        npc_companion_mission c_mission = elem->get_companion_mission();
        if( c_mission.position == omt_pos && c_mission.role_id == "FACTION_CAMP" ) {
            camp_workers.push_back( elem );
        }
    }
}
References camp_workers, overmapbuffer::get_companion_mission_npcs(), omt_pos, overmap_buffer, npc_companion_mission::position, and npc_companion_mission::role_id.
Referenced by reset_camp_resources().
search_results()
void basecamp::search_results (int skill, const item_group_id & group_id, int attempts, int difficulty)
spawn items or corpses based on search attempts
Parameters
skill skill level of the search
group_id name of the item_group that provides the items
attempts number of skill checks to make
difficulty a random number from 0 to difficulty is created for each attempt, and if skill is higher, an item or corpse is spawned
Definition at line 3063 of file faction_camp.cpp.
{
    for( int i = 0; i < attempts; i++ ) {
        if( skill > rng( 0, difficulty ) ) {
            auto result = item_group::item_from( group_id, calendar::turn );
            if( !result.is_null() ) {
                place_results( result );
            }
        }
    }
}
References item_group::item_from(), place_results(), rng(), and calendar::turn.
Referenced by gathering_return().
serialize()
void basecamp::serialize (JsonOut & json) const
Definition at line 3532 of file savegame_json.cpp.
{
    if( omt_pos != tripoint_abs_omt() ) {
        json.start_object();
        json.member( "name", name );
        json.member( "pos", omt_pos );
        json.member( "bb_pos", bb_pos );
        json.member( "expansions" );
        json.start_array();
        for( const auto &expansion : expansions ) {
            json.start_object();
            json.member( "dir", expansion.first );
            json.member( "type", expansion.second.type );
            json.member( "provides" );
            json.start_array();
            for( const auto &provide : expansion.second.provides ) {
                json.start_object();
                json.member( "id", provide.first );
                json.member( "amount", provide.second );
                json.end_object();
            }
            json.end_array();
            json.member( "in_progress" );
            json.start_array();
            for( const auto &working : expansion.second.in_progress ) {
                json.start_object();
                json.member( "id", working.first );
                json.member( "amount", working.second );
                json.end_object();
            }
            json.end_array();
            json.member( "pos", expansion.second.pos );
            json.end_object();
        }
        json.end_array();
        json.member( "fortifications" );
        json.start_array();
        for( const auto &fortification : fortifications ) {
            json.start_object();
            json.member( "pos", fortification );
            json.end_object();
        }
        json.end_array();
        json.end_object();
    } else {
        return;
    }
}
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), Character::name, JsonOut::start_array(), JsonOut::start_object(), and working.
set_bb_pos()
void basecamp::set_bb_pos (const tripoint & new_abs_pos) inline
Definition at line 148 of file basecamp.h.
{
            bb_pos = new_abs_pos;
        }
References bb_pos.
set_by_radio()
void basecamp::set_by_radio (bool access_by_radio)
Definition at line 132 of file basecamp.cpp.
{
    by_radio = access_by_radio;
}
References by_radio.
Referenced by talk_function::basecamp_mission(), and iexamine::bulletin_board().
set_dumping_spot()
void basecamp::set_dumping_spot (const tripoint & spot) inline
Definition at line 235 of file basecamp.h.
{
            dumping_spot = spot;
        }
References dumping_spot.
Referenced by talk_function::basecamp_mission(), and validate_sort_points().
set_name()
void basecamp::set_name (const std::string & new_name)
Definition at line 575 of file basecamp.cpp.
{
    name = new_name;
}
References name.
Referenced by game::validate_camps().
set_sort_points()
bool basecamp::set_sort_points ()
Invokes the zone manager and validates that the necessary sort zones exist.
Definition at line 3615 of file faction_camp.cpp.
{
    popup( _( "Sorting zones have changed.  Please create some sorting zones.  "
              "You must create a camp food zone, and a camp storage zone." ) );
    g->zones_manager();
    return validate_sort_points();
}
References _, g, popup(), and validate_sort_points().
Referenced by validate_sort_points().
start_clearcut()
void basecamp::start_clearcut ()
Definition at line 1953 of file faction_camp.cpp.
{
    std::vector<std::string> log_sources = { "forest", "forest_thick" };
    popup( _( "Forests are the only valid cutting locations." ) );
    tripoint_abs_omt forest = om_target_tile( omt_pos, 1, 50, log_sources );
    if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
        standard_npc sample_npc( "Temp" );
        sample_npc.set_fake( true );
        int tree_est = om_cutdown_trees_est( forest, 95 );
        int tree_young_est = om_harvest_ter_est( sample_npc, forest,
                             ter_id( "t_tree_young" ), 95 );
        int dist = rl_dist( forest.xy(), omt_pos.xy() );
        //Very roughly what the player does + 6 hours for prep, clean up, breaks
        time_duration chop_time = 6_hours + 1_hours * tree_est + 7_minutes * tree_young_est;
        time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, 2 );
        time_duration work_time = travel_time + chop_time;
        if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time,
                       chop_time, travel_time, dist, 2, time_to_food( work_time ) ) ) ) {
            return;
        }
        npc_ptr comp = start_mission( "_faction_camp_clearcut", work_time,
                                      true, _( "departs to clear a forest" ), false, {},
                                      skill_fabrication, 1 );
        if( comp != nullptr ) {
            om_cutdown_trees_trunks( forest, 95 );
            om_harvest_ter_break( *comp, forest, ter_id( "t_tree_young" ), 95 );
            //If we cleared a forest...
            if( om_cutdown_trees_est( forest ) < 5 ) {
                overmap_buffer.ter_set( forest, oter_id( "field" ) );
            }
        }
    }
}
References _, camp_trip_description(), companion_travel_time_calc(), om_cutdown_trees_est(), om_cutdown_trees_trunks(), om_harvest_ter_break(), om_harvest_ter_est(), om_target_tile(), omt_pos, oter_id, overmap_buffer, popup(), query_yn(), rl_dist(), Creature::set_fake(), skill_fabrication, start_mission(), ter_id, overmapbuffer::ter_set(), time_to_food(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by handle_mission().
start_combat_mission()
void basecamp::start_combat_mission (const std::string & miss)
Definition at line 2195 of file faction_camp.cpp.
{
    popup( _( "Select checkpoints until you reach maximum range or select the last point again "
              "to end." ) );
    tripoint_abs_omt start = omt_pos;
    std::vector<tripoint_abs_omt> scout_points = om_companion_path( start, 90, true );
    if( scout_points.empty() ) {
        return;
    }
    int dist = scout_points.size();
    int trips = 2;
    time_duration travel_time = companion_travel_time_calc( scout_points, 0_minutes, trips );
    if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( 0_hours, 0_hours,
                   travel_time, dist, trips, time_to_food( travel_time ) ) ) ) {
        return;
    }
    npc_ptr comp = start_mission( miss, travel_time, true, _( "departs on patrol" ),
                                  false, {}, skill_survival, 3 );
    if( comp != nullptr ) {
        comp->companion_mission_points = scout_points;
    }
}
References _, camp_trip_description(), companion_travel_time_calc(), om_companion_path(), omt_pos, popup(), query_yn(), skill_survival, start_mission(), and time_to_food().
Referenced by handle_mission().
start_crafting()
void basecamp::start_crafting (const std::string & cur_id, const point & cur_dir, const std::string & type, const std::string & miss_id)
Definition at line 2223 of file faction_camp.cpp.
{
    const std::string cur_dir_id = base_camps::all_directions.at( cur_dir ).id;
    const std::map<recipe_id, translation> &recipes = recipe_deck( type );
    if( cur_id.substr( 0, cur_dir_id.size() ) != cur_dir_id ) {
        // not a crafting mission or has the wrong direction
        return;
    }
    const auto it = recipes.find( recipe_id( cur_id.substr( cur_dir_id.size() ) ) );
    if( it != recipes.end() ) {
        const recipe &making = it->first.obj();
        if( !making.deduped_requirements().can_make_with_inventory(
                _inv, making.get_component_filter() ) ) {
            popup( _( "You don't have the materials to craft that" ) );
            return;
        }
        int batch_size = 1;
        string_input_popup popup_input;
        int batch_max = recipe_batch_max( making );
        const std::string title = string_format( _( "Batch crafting %s [MAX: %d]: " ),
                                  making.result_name(), batch_max );
        popup_input.title( title ).edit( batch_size );
        if( popup_input.canceled() || batch_size <= 0 ) {
            return;
        }
        if( batch_size > recipe_batch_max( making ) ) {
            popup( _( "Your batch is too large!" ) );
            return;
        }
        basecamp_action_components components( making, batch_size, *this );
        if( !components.choose_components() ) {
            return;
        }
        time_duration work_days = base_camps::to_workdays( making.batch_duration( batch_size ) );
        npc_ptr comp = start_mission( miss_id + cur_dir_id, work_days, true,
                                      _( "begins to work" ), false, {},
                                      making.required_skills );
        if( comp != nullptr ) {
            components.consume_components();
            for( const item &results : making.create_results( batch_size ) ) {
                comp->companion_mission_inv.add_item( results );
            }
        }
        return;
    }
}
References _, _inv, base_camps::all_directions, recipe::batch_duration(), deduped_requirement_data::can_make_with_inventory(), string_input_popup::canceled(), basecamp_action_components::choose_components(), basecamp_action_components::consume_components(), recipe::create_results(), recipe::deduped_requirements(), string_input_popup::edit(), recipe::get_component_filter(), popup(), recipe_batch_max(), recipe_deck(), recipe::required_skills, recipe::result_name(), start_mission(), string_format(), string_input_popup::title(), PATH_INFO::title(), base_camps::to_workdays(), and type.
Referenced by handle_mission().
start_cut_logs()
void basecamp::start_cut_logs ()
Called when a companion is sent to cut logs.
Definition at line 1906 of file faction_camp.cpp.
{
    std::vector<std::string> log_sources = { "forest", "forest_thick", "forest_water" };
    popup( _( "Forests and swamps are the only valid cutting locations." ) );
    tripoint_abs_omt forest = om_target_tile( omt_pos, 1, 50, log_sources );
    if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
        standard_npc sample_npc( "Temp" );
        sample_npc.set_fake( true );
        int tree_est = om_cutdown_trees_est( forest, 50 );
        int tree_young_est = om_harvest_ter_est( sample_npc, forest,
                             ter_id( "t_tree_young" ), 50 );
        int dist = rl_dist( forest.xy(), omt_pos.xy() );
        //Very roughly what the player does + 6 hours for prep, clean up, breaks
        time_duration chop_time = 6_hours + 1_hours * tree_est + 7_minutes * tree_young_est;
        int haul_items = 2 * tree_est + 3 * tree_young_est;
        time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes,
                                    2, haul_items );
        time_duration work_time = travel_time + chop_time;
        if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time,
                       chop_time, travel_time, dist, 2, time_to_food( work_time ) ) ) ) {
            return;
        }
        npc_ptr comp = start_mission( "_faction_camp_cut_log", work_time, true,
                                      _( "departs to cut logs" ), false, {},
                                      skill_fabrication, 2 );
        if( comp != nullptr ) {
            om_cutdown_trees_logs( forest, 50 );
            om_harvest_ter( *comp, forest, ter_id( "t_tree_young" ), 50 );
            mass_volume harvest = om_harvest_itm( comp, forest, 95 );
            // recalculate trips based on actual load and capacity
            travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, 2,
                          harvest.count );
            work_time = travel_time + chop_time;
            comp->companion_mission_time_ret = calendar::turn + work_time;
            //If we cleared a forest...
            if( om_cutdown_trees_est( forest ) < 5 ) {
                const oter_id &omt_trees = overmap_buffer.ter( forest );
                //Do this for swamps "forest_wet" if we have a swamp without trees...
                if( omt_trees.id() == "forest" || omt_trees.id() == "forest_thick" ) {
                    overmap_buffer.ter_set( forest, oter_id( "field" ) );
                }
            }
        }
    }
}
References _, camp_trip_description(), companion_travel_time_calc(), harvest, int_id< T >::id(), om_cutdown_trees_est(), om_cutdown_trees_logs(), om_harvest_itm(), om_harvest_ter(), om_harvest_ter_est(), om_target_tile(), omt_pos, oter_id, overmap_buffer, popup(), query_yn(), rl_dist(), Creature::set_fake(), skill_fabrication, start_mission(), overmapbuffer::ter(), ter_id, overmapbuffer::ter_set(), time_to_food(), calendar::turn, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by handle_mission().
start_farm_op()
void basecamp::start_farm_op (const point & dir, const tripoint_abs_omt & omt_tgt, farm_ops op)
Definition at line 2401 of file faction_camp.cpp.
{
    const std::string &dir_id = base_camps::all_directions.at( dir ).id;
    std::pair<size_t, std::string> farm_data = farm_action( omt_tgt, op );
    size_t plots_cnt = farm_data.first;
    if( !plots_cnt ) {
        return;
    }
    time_duration work = 0_minutes;
    switch( op ) {
        case farm_ops::harvest:
            work += 3_minutes * plots_cnt;
            start_mission( "_faction_exp_harvest_" + dir_id, work, true,
                           _( "begins to harvest the field" ), false, {}, skill_survival, 1 );
            break;
        case farm_ops::plant: {
            std::vector<item *> seed_inv = _inv.items_with( farm_valid_seed );
            if( seed_inv.empty() ) {
                popup( _( "You have no additional seeds to give your companions" ) );
                return;
            }
            std::vector<item *> plant_these = give_equipment( seed_inv,
                                              _( "Which seeds do you wish to have planted?" ) );
            size_t seed_cnt = 0;
            for( item *seeds : plant_these ) {
                seed_cnt += seeds->count();
            }
            size_t plots_seeded = std::min( seed_cnt, plots_cnt );
            if( !seed_cnt ) {
                return;
            }
            work += 1_minutes * plots_seeded;
            start_mission( "_faction_exp_plant_" + dir_id, work, true,
                           _( "begins planting the field" ), false, plant_these,
                           skill_survival, 1 );
            break;
        }
        case farm_ops::plow:
            work += 5_minutes * plots_cnt;
            start_mission( "_faction_exp_plow_" + dir_id, work, true,
                           _( "begins plowing the field" ), false, {} );
            break;
        default:
            debugmsg( "Farm operations called with no operation" );
    }
}
References _, _inv, base_camps::all_directions, debugmsg, farm_action(), farm_valid_seed(), give_equipment(), harvest, visitable< T >::items_with(), plant, plow, popup(), skill_survival, and start_mission().
Referenced by handle_mission().
start_fortifications()
void basecamp::start_fortifications (std::string & bldg_exp)
Called when a compansion is sent to start fortifications.
Definition at line 2097 of file faction_camp.cpp.
{
    std::vector<std::string> allowed_locations = {
        "forest", "forest_thick", "forest_water", "field"
    };
    popup( _( "Select a start and end point.  Line must be straight.  Fields, forests, and "
              "swamps are valid fortification locations.  In addition to existing fortification "
              "constructions." ) );
    tripoint_abs_omt start = om_target_tile( omt_pos, 2, 90, allowed_locations );
    popup( _( "Select an end point." ) );
    tripoint_abs_omt stop = om_target_tile( omt_pos, 2, 90, allowed_locations, true, false, start );
    if( start != tripoint_abs_omt( -999, -999, -999 ) &&
        stop != tripoint_abs_omt( -999, -999, -999 ) ) {
        const recipe &making = recipe_id( bldg_exp ).obj();
        bool change_x = ( start.x() != stop.x() );
        bool change_y = ( start.y() != stop.y() );
        if( change_x && change_y ) {
            popup( "Construction line must be straight!" );
            return;
        }
        if( bldg_exp == "faction_wall_level_N_1" ) {
            std::vector<tripoint_abs_omt> tmp_line = line_to( stop, start );
            int line_count = tmp_line.size();
            int yes_count = 0;
            for( auto elem : tmp_line ) {
                if( std::find( fortifications.begin(), fortifications.end(), elem ) != fortifications.end() ) {
                    yes_count += 1;
                }
            }
            if( yes_count < line_count ) {
                popup( _( "Spiked pits must be built over existing trenches!" ) );
                return;
            }
        }
        std::vector<tripoint_abs_omt> fortify_om;
        if( ( change_x && stop.x() < start.x() ) || ( change_y && stop.y() < start.y() ) ) {
            //line_to doesn't include the origin point
            fortify_om.push_back( stop );
            std::vector<tripoint_abs_omt> tmp_line = line_to( stop, start );
            fortify_om.insert( fortify_om.end(), tmp_line.begin(), tmp_line.end() );
        } else {
            fortify_om.push_back( start );
            std::vector<tripoint_abs_omt> tmp_line = line_to( start, stop );
            fortify_om.insert( fortify_om.end(), tmp_line.begin(), tmp_line.end() );
        }
        int trips = 0;
        time_duration build_time = 0_hours;
        time_duration travel_time = 0_hours;
        int dist = 0;
        for( auto fort_om : fortify_om ) {
            bool valid = false;
            const oter_id &omt_ref = overmap_buffer.ter( fort_om );
            for( const std::string &pos_om : allowed_locations ) {
                if( omt_ref.id().c_str() == pos_om ) {
                    valid = true;
                    break;
                }
            }
            if( !valid ) {
                popup( _( "Invalid terrain in construction path." ) );
                return;
            }
            trips += 2;
            build_time += making.batch_duration();
            dist += rl_dist( fort_om.xy(), omt_pos.xy() );
            travel_time += companion_travel_time_calc( fort_om, omt_pos, 0_minutes, 2 );
        }
        time_duration total_time = base_camps::to_workdays( travel_time + build_time );
        int need_food = time_to_food( total_time );
        if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( total_time, build_time,
                       travel_time, dist, trips, need_food ) ) ) {
            return;
        } else if( !making.deduped_requirements().can_make_with_inventory( _inv,
                   making.get_component_filter(), ( fortify_om.size() * 2 ) - 2 ) ) {
            popup( _( "You don't have the material to build the fortification." ) );
            return;
        }
        const int batch_size = fortify_om.size() * 2 - 2;
        basecamp_action_components components( making, batch_size, *this );
        if( !components.choose_components() ) {
            return;
        }
        npc_ptr comp = start_mission( "_faction_camp_om_fortifications", total_time, true,
                                      _( "begins constructing fortifications" ), false, {},
                                      making.required_skills );
        if( comp != nullptr ) {
            components.consume_components();
            comp->companion_mission_role_id = bldg_exp;
            for( auto pt : fortify_om ) {
                comp->companion_mission_points.push_back( pt );
            }
        }
    }
}
References _, _inv, recipe::batch_duration(), string_id< T >::c_str(), camp_trip_description(), deduped_requirement_data::can_make_with_inventory(), basecamp_action_components::choose_components(), companion_travel_time_calc(), basecamp_action_components::consume_components(), recipe::deduped_requirements(), detail::find(), fortifications, recipe::get_component_filter(), int_id< T >::id(), line_to(), need_food, string_id< T >::obj(), om_target_tile(), omt_pos, overmap_buffer, popup(), query_yn(), recipe::required_skills, rl_dist(), start_mission(), overmapbuffer::ter(), time_to_food(), base_camps::to_workdays(), coords::coord_point< Point, Origin, Scale >::x(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by handle_mission().
start_garage_chop()
bool basecamp::start_garage_chop (const point & dir, const tripoint_abs_omt & omt_tgt)
Called when a companion starts a chop shop task mission.
Definition at line 2449 of file faction_camp.cpp.
{
    editmap edit;
    vehicle *car = edit.mapgen_veh_query( omt_tgt );
    if( car == nullptr ) {
        return false;
    }
    if( !query_yn( _( "       Chopping this vehicle:\n%s" ), camp_car_description( car ) ) ) {
        return false;
    }
    const std::string dir_id = base_camps::all_directions.at( dir ).id;
    npc_ptr comp = start_mission( "_faction_exp_chop_shop_" + dir_id, 5_days, true,
                                  _( "begins working in the garage" ), false, {},
                                  skill_mechanics, 2 );
    if( comp == nullptr ) {
        return false;
    }
    // FIXME: use ranges, do this sensibly
    //Chopping up the car!
    int skillLevel = comp->get_skill_level( skill_mechanics );
    for( int prt = 0; prt < car->part_count(); prt++ ) {
        vehicle_stack contents = car->get_items( prt );
        for( auto iter = contents.begin(); iter != contents.end(); ) {
            comp->companion_mission_inv.add_item( *iter );
            iter = contents.erase( iter );
        }
        bool broken = car->part( prt ).is_broken();
        bool skill_break = false;
        bool skill_destroy = false;
        int dice = rng( 1, 20 );
        dice += skillLevel - car->part( prt ).info().difficulty;
        if( dice >= 20 ) {
            skill_break = false;
            skill_destroy = false;
            talk_function::companion_skill_trainer( *comp, skill_mechanics, 1_hours,
                                                    car->part( prt ).info().difficulty );
        } else if( dice > 15 ) {
            skill_break = false;
        } else if( dice > 9 ) {
            skill_break = true;
            skill_destroy = false;
        } else {
            skill_break = true;
            skill_destroy = true;
        }
        if( !broken && !skill_break ) {
            //Higher level garages will salvage liquids from tanks
            if( !car->part( prt ).is_battery() ) {
                car->part( prt ).ammo_consume( car->part( prt ).ammo_capacity(),
                                               car->global_part_pos3( car->part( prt ) ) );
            }
            comp->companion_mission_inv.add_item( car->part( prt ).properties_to_item() );
        } else if( !skill_destroy ) {
            for( const item &itm : car->part( prt ).pieces_for_broken_part() ) {
                comp->companion_mission_inv.add_item( itm );
            }
        }
    }
    talk_function::companion_skill_trainer( *comp, skill_mechanics, 5_days, 2 );
    edit.mapgen_veh_destroy( omt_tgt, car );
    return true;
}
References _, base_camps::all_directions, vehicle_part::ammo_capacity(), vehicle_part::ammo_consume(), item_stack::begin(), broken, camp_car_description(), talk_function::companion_skill_trainer(), dice(), vpart_info::difficulty, item_stack::end(), vehicle_stack::erase(), vehicle::get_items(), vehicle::global_part_pos3(), vehicle_part::info(), vehicle_part::is_battery(), vehicle_part::is_broken(), editmap::mapgen_veh_destroy(), editmap::mapgen_veh_query(), vehicle::part(), vehicle::part_count(), vehicle_part::pieces_for_broken_part(), vehicle_part::properties_to_item(), query_yn(), rng(), skill_mechanics, and start_mission().
Referenced by handle_mission().
start_menial_labor()
void basecamp::start_menial_labor ()
Definition at line 1890 of file faction_camp.cpp.
{
    if( camp_food_supply() < time_to_food( 3_hours ) ) {
        popup( _( "You don't have enough food stored to feed your companion." ) );
        return;
    }
    shared_ptr_fast<npc> comp = talk_function::companion_choose();
    if( comp == nullptr ) {
        return;
    }
    validate_sort_points();
    comp->assign_activity( ACT_MOVE_LOOT );
    popup( _( "%s goes off to clean toilets and sort loot." ), comp->disp_name() );
}
References _, ACT_MOVE_LOOT, camp_food_supply(), talk_function::companion_choose(), popup(), time_to_food(), and validate_sort_points().
Referenced by handle_mission().
start_mission() [1/2]
npc_ptr basecamp::start_mission (const std::string & miss_id, time_duration duration, bool must_feed, const std::string & desc, bool group, const std::vector< item * > & equipment, const skill_id & skill_tested, int skill_level)
generic mission start function that wraps individual mission
Definition at line 1560 of file faction_camp.cpp.
{
    std::map<skill_id, int> required_skills;
    required_skills[ skill_tested ] = skill_level;
    return start_mission( miss_id, duration, must_feed, desc, false, equipment, required_skills );
}
References start_mission().
Referenced by handle_mission(), start_clearcut(), start_combat_mission(), start_crafting(), start_cut_logs(), start_farm_op(), start_fortifications(), start_garage_chop(), start_mission(), start_relay_hide_site(), start_setup_hide_site(), and start_upgrade().
start_mission() [2/2]
npc_ptr basecamp::start_mission (const std::string & miss_id, time_duration duration, bool must_feed, const std::string & desc, bool group, const std::vector< item * > & equipment, const std::map< skill_id, int > & required_skills = {})
Definition at line 1570 of file faction_camp.cpp.
{
    if( must_feed && camp_food_supply() < time_to_food( duration ) ) {
        popup( _( "You don't have enough food stored to feed your companion." ) );
        return nullptr;
    }
    npc_ptr comp = talk_function::individual_mission( omt_pos, base_camps::id, desc, miss_id,
                   false, equipment, required_skills );
    if( comp != nullptr ) {
        comp->companion_mission_time_ret = calendar::turn + duration;
        if( must_feed ) {
            camp_food_supply( duration );
        }
    }
    return comp;
}
References _, camp_food_supply(), base_camps::id, talk_function::individual_mission(), omt_pos, popup(), time_to_food(), and calendar::turn.
start_relay_hide_site()
void basecamp::start_relay_hide_site ()
Definition at line 2033 of file faction_camp.cpp.
{
    std::vector<std::string> hide_locations = { "faction_hide_site_0" };
    popup( _( "You must select an existing hide site." ) );
    tripoint_abs_omt forest = om_target_tile( omt_pos, 10, 90, hide_locations, true, true,
                              omt_pos, true );
    if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
        int dist = rl_dist( forest.xy(), omt_pos.xy() );
        inventory tgt_inv = g->u.inv;
        std::vector<item *> pos_inv = tgt_inv.items_with( []( const item & itm ) {
            return !itm.can_revive();
        } );
        std::vector<item *> losing_equipment;
        if( !pos_inv.empty() ) {
            losing_equipment = give_equipment( pos_inv,
                                               _( "Do you wish to give your companion "
                                                  "additional items?" ) );
        }
        //Check items in improvised shelters at hide site
        tinymap target_bay;
        target_bay.load( project_to<coords::sm>( forest ), false );
        std::vector<item *> hide_inv;
        for( item &i : target_bay.i_at( point( 11, 10 ) ) ) {
            hide_inv.push_back( &i );
        }
        std::vector<item *> gaining_equipment;
        if( !hide_inv.empty() ) {
            gaining_equipment = give_equipment( hide_inv, _( "Bring gear back?" ) );
        }
        if( !losing_equipment.empty() || !gaining_equipment.empty() ) {
            //Only get charged the greater trips since return is free for both
            int trips = std::max( om_carry_weight_to_trips( gaining_equipment ),
                                  om_carry_weight_to_trips( losing_equipment ) );
            int haulage = trips <= 2 ? 0 : std::max( gaining_equipment.size(),
                          losing_equipment.size() );
            time_duration build_time = 6_hours;
            time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes,
                                        trips, haulage );
            time_duration work_time = travel_time + build_time;
            if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time, build_time,
                           travel_time, dist, trips, time_to_food( work_time ) ) ) ) {
                return;
            }
            npc_ptr comp = start_mission( "_faction_camp_hide_trans", work_time, true,
                                          _( "departs for the hide site" ), false, {},
                                          skill_survival, 3 );
            if( comp != nullptr ) {
                // recalculate trips based on actual load
                trips = std::max( om_carry_weight_to_trips( gaining_equipment, comp ),
                                  om_carry_weight_to_trips( losing_equipment, comp ) );
                int haulage = trips <= 2 ? 0 : std::max( gaining_equipment.size(),
                              losing_equipment.size() );
                work_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, trips,
                                                        haulage ) + build_time;
                comp->companion_mission_time_ret = calendar::turn + work_time;
                om_set_hide_site( *comp, forest, losing_equipment, gaining_equipment );
            }
        } else {
            popup( _( "You need equipment to transport between the hide site" ) );
        }
    }
}
References _, camp_trip_description(), item::can_revive(), companion_travel_time_calc(), g, give_equipment(), map::i_at(), visitable< T >::items_with(), map::load(), om_carry_weight_to_trips(), om_set_hide_site(), om_target_tile(), omt_pos, popup(), query_yn(), rl_dist(), skill_survival, start_mission(), time_to_food(), calendar::turn, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by handle_mission().
start_setup_hide_site()
void basecamp::start_setup_hide_site ()
Definition at line 1988 of file faction_camp.cpp.
{
    std::vector<std::string> hide_locations = { "forest", "forest_thick", "forest_water",
                                                "field"
                                              };
    popup( _( "Forests, swamps, and fields are valid hide site locations." ) );
    tripoint_abs_omt forest = om_target_tile( omt_pos, 10, 90, hide_locations, true, true,
                              omt_pos, true );
    if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
        int dist = rl_dist( forest.xy(), omt_pos.xy() );
        inventory tgt_inv = g->u.inv;
        std::vector<item *> pos_inv = tgt_inv.items_with( []( const item & itm ) {
            return !itm.can_revive();
        } );
        if( !pos_inv.empty() ) {
            std::vector<item *> losing_equipment = give_equipment( pos_inv,
                                                   _( "Do you wish to give your companion "
                                                           "additional items?" ) );
            int trips = om_carry_weight_to_trips( losing_equipment );
            int haulage = trips <= 2 ? 0 : losing_equipment.size();
            time_duration build_time = 6_hours;
            time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes,
                                        2, haulage );
            time_duration work_time = travel_time + build_time;
            if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time,
                           build_time, travel_time, dist, trips, time_to_food( work_time ) ) ) ) {
                return;
            }
            npc_ptr comp = start_mission( "_faction_camp_hide_site", work_time, true,
                                          _( "departs to build a hide site" ), false, {},
                                          skill_survival, 3 );
            if( comp != nullptr ) {
                trips = om_carry_weight_to_trips( losing_equipment, comp );
                haulage = trips <= 2 ? 0 : losing_equipment.size();
                work_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, 2, haulage ) +
                            build_time;
                comp->companion_mission_time_ret = calendar::turn + work_time;
                om_set_hide_site( *comp, forest, losing_equipment );
            }
        } else {
            popup( _( "You need equipment to setup a hide site" ) );
        }
    }
}
References _, camp_trip_description(), item::can_revive(), companion_travel_time_calc(), g, give_equipment(), visitable< T >::items_with(), om_carry_weight_to_trips(), om_set_hide_site(), om_target_tile(), omt_pos, popup(), query_yn(), rl_dist(), skill_survival, start_mission(), time_to_food(), calendar::turn, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by handle_mission().
start_upgrade()
void basecamp::start_upgrade (const std::string & bldg, const point & dir, const std::string & key)
Definition at line 1590 of file faction_camp.cpp.
{
    const recipe &making = recipe_id( bldg ).obj();
    //Stop upgrade if you don't have materials
    if( making.deduped_requirements().can_make_with_inventory(
            _inv, making.get_component_filter() ) ) {
        bool must_feed = bldg != "faction_base_camp_1";
        basecamp_action_components components( making, 1, *this );
        if( !components.choose_components() ) {
            return;
        }
        time_duration work_days = base_camps::to_workdays( making.batch_duration() );
        npc_ptr comp = nullptr;
        if( making.required_skills.empty() ) {
            if( making.skill_used.is_valid() ) {
                comp = start_mission( key, work_days, must_feed,
                                      _( "begins to upgrade the camp" ), false, {},
                                      making.skill_used, making.difficulty );
            } else {
                comp = start_mission( key, work_days, must_feed,
                                      _( "begins to upgrade the camp" ), false, {} );
            }
        } else {
            comp = start_mission( key, work_days, must_feed, _( "begins to upgrade the camp" ),
                                  false, {}, making.required_skills );
        }
        if( comp == nullptr ) {
            return;
        }
        components.consume_components();
        update_in_progress( bldg, dir );
    } else {
        popup( _( "You don't have the materials for the upgrade." ) );
    }
}
References _, _inv, recipe::batch_duration(), deduped_requirement_data::can_make_with_inventory(), basecamp_action_components::choose_components(), basecamp_action_components::consume_components(), recipe::deduped_requirements(), recipe::difficulty, recipe::get_component_filter(), string_id< T >::is_valid(), string_id< T >::obj(), popup(), recipe::required_skills, recipe::skill_used, start_mission(), base_camps::to_workdays(), and update_in_progress().
Referenced by handle_mission().
survey_return()
bool basecamp::survey_return ()
Choose which expansion you should start, called when a survey mission is completed.
Definition at line 2922 of file faction_camp.cpp.
{
    npc_ptr comp = companion_choose_return( "_faction_camp_expansion", 3_hours );
    if( comp == nullptr ) {
        return false;
    }
    popup( _( "Select a tile up to %d tiles away." ), 1 );
    const tripoint_abs_omt where( ui::omap::choose_point() );
    if( where == overmap::invalid_tripoint ) {
        return false;
    }
    int dist = rl_dist( where.xy(), omt_pos.xy() );
    if( dist != 1 ) {
        popup( _( "You must select a tile within %d range of the camp" ), 1 );
        return false;
    }
    if( omt_pos.z() != where.z() ) {
        popup( _( "Expansions must be on the same level as the camp" ) );
        return false;
    }
    const point dir = talk_function::om_simple_dir( omt_pos, where );
    if( expansions.find( dir ) != expansions.end() ) {
        popup( _( "You already have an expansion at that location" ) );
        return false;
    }
    const oter_id &omt_ref = overmap_buffer.ter( where );
    const auto &pos_expansions = recipe_group::get_recipes_by_id( "all_faction_base_expansions",
                                 omt_ref.id().c_str() );
    if( pos_expansions.empty() ) {
        popup( _( "You can't build any expansions in a %s." ), omt_ref.id().c_str() );
        return false;
    }
    const recipe_id expansion_type = base_camps::select_camp_option( pos_expansions,
                                     _( "Select an expansion:" ) );
    if( !run_mapgen_update_func( expansion_type.str(), where ) ) {
        popup( _( "%s failed to add the %s expansion, perhaps there is a vehicle in the way." ),
               comp->disp_name(),
               expansion_type->blueprint_name() );
        return false;
    }
    overmap_buffer.ter_set( where, oter_id( expansion_type.str() ) );
    add_expansion( expansion_type.str(), where, dir );
    const std::string msg = _( "returns from surveying for the expansion." );
    finish_return( *comp, true, msg, "construction", 2 );
    return true;
}
References _, add_expansion(), recipe::blueprint_name(), string_id< T >::c_str(), ui::omap::choose_point(), companion_choose_return(), expansions, finish_return(), recipe_group::get_recipes_by_id(), int_id< T >::id(), overmap::invalid_tripoint, talk_function::om_simple_dir(), omt_pos, oter_id, overmap_buffer, popup(), rl_dist(), run_mapgen_update_func(), base_camps::select_camp_option(), string_id< T >::str(), overmapbuffer::ter(), overmapbuffer::ter_set(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by handle_mission().
update_in_progress()
void basecamp::update_in_progress (const std::string & bldg, const point & dir)
Definition at line 431 of file basecamp.cpp.
{
    if( !recipe_id( bldg ).is_valid() ) {
        return;
    }
    auto e = expansions.find( dir );
    if( e == expansions.end() ) {
        return;
    }
    expansion_data &e_data = e->second;
    const recipe &making = recipe_id( bldg ).obj();
    for( const auto &bp_provides : making.blueprint_provides() ) {
        if( e_data.in_progress.find( bp_provides.first ) == e_data.in_progress.end() ) {
            e_data.in_progress[bp_provides.first] = 0;
        }
        e_data.in_progress[bp_provides.first] += bp_provides.second;
    }
}
References recipe::blueprint_provides(), expansions, expansion_data::in_progress, is_valid(), and string_id< T >::obj().
Referenced by start_upgrade().
update_provides()
void basecamp::update_provides (const std::string & bldg, expansion_data & e_data)
Definition at line 416 of file basecamp.cpp.
{
    if( !recipe_id( bldg ).is_valid() ) {
        return;
    }
    const recipe &making = recipe_id( bldg ).obj();
    for( const auto &bp_provides : making.blueprint_provides() ) {
        if( e_data.provides.find( bp_provides.first ) == e_data.provides.end() ) {
            e_data.provides[bp_provides.first] = 0;
        }
        e_data.provides[bp_provides.first] += bp_provides.second;
    }
}
References recipe::blueprint_provides(), is_valid(), string_id< T >::obj(), and expansion_data::provides.
Referenced by add_expansion(), define_camp(), reset_camp_resources(), and upgrade_return().
update_resources()
void basecamp::update_resources (const std::string & bldg)
Definition at line 404 of file basecamp.cpp.
{
    if( !recipe_id( bldg ).is_valid() ) {
        return;
    }
    const recipe &making = recipe_id( bldg ).obj();
    for( const itype_id &bp_resource : making.blueprint_resources() ) {
        add_resource( bp_resource );
    }
}
References add_resource(), recipe::blueprint_resources(), is_valid(), and string_id< T >::obj().
Referenced by add_expansion(), reset_camp_resources(), and upgrade_return().
upgrade_return() [1/2]
bool basecamp::upgrade_return (const point & dir, const std::string & miss)
Called to close upgrade missions, miss is the name of the mission id and dir is the direction of the location to be upgraded.
Definition at line 2597 of file faction_camp.cpp.
{
    const std::string bldg = next_upgrade( dir, 1 );
    if( bldg == "null" ) {
        return false;
    }
    return upgrade_return( dir, miss, bldg );
}
References next_upgrade(), and upgrade_return().
Referenced by handle_mission(), and upgrade_return().
upgrade_return() [2/2]
bool basecamp::upgrade_return (const point & dir, const std::string & miss, const std::string & bldg)
As above, but with an explicit blueprint recipe to upgrade.
Definition at line 2606 of file faction_camp.cpp.
{
    auto e = expansions.find( dir );
    if( e == expansions.end() ) {
        return false;
    }
    const tripoint_abs_omt upos = e->second.pos;
    const recipe &making = recipe_id( bldg ).obj();
    time_duration work_days = base_camps::to_workdays( making.batch_duration() );
    npc_ptr comp = companion_choose_return( miss, work_days );
    if( comp == nullptr ) {
        return false;
    }
    if( !run_mapgen_update_func( making.get_blueprint(), upos ) ) {
        popup( _( "%s failed to build the %s upgrade, perhaps there is a vehicle in the way." ),
               comp->disp_name(),
               making.get_blueprint() );
        return false;
    }
    update_provides( bldg, e->second );
    update_resources( bldg );
    const std::string msg = _( "returns from upgrading the camp having earned a bit of "
                               "experience" );
    finish_return( *comp, false, msg, "construction", making.difficulty );
    return true;
}
References _, recipe::batch_duration(), companion_choose_return(), recipe::difficulty, expansions, finish_return(), recipe::get_blueprint(), string_id< T >::obj(), popup(), run_mapgen_update_func(), base_camps::to_workdays(), update_provides(), and update_resources().
use_charges()
std::list< item > basecamp::use_charges (const itype_id & fake_id, int & quantity)
Definition at line 584 of file basecamp.cpp.
{
    std::list<item> ret;
    if( quantity <= 0 ) {
        return ret;
    }
    for( basecamp_resource &bcp_r : resources ) {
        if( bcp_r.fake_id == fake_id ) {
            item camp_item( bcp_r.fake_id, calendar::start_of_cataclysm );
            camp_item.charges = std::min( bcp_r.available, quantity );
            quantity -= camp_item.charges;
            bcp_r.available -= camp_item.charges;
            bcp_r.consumed += camp_item.charges;
            ret.push_back( camp_item );
            if( quantity <= 0 ) {
                break;
            }
        }
    }
    return ret;
}
References item::charges, resources, cata::hash64_detail::ret, and calendar::start_of_cataclysm.
Referenced by map::use_charges().
validate_assignees()
void basecamp::validate_assignees ()
Definition at line 509 of file basecamp.cpp.
{
    std::vector<npc_ptr>::iterator iter = assigned_npcs.begin();
    while( iter != assigned_npcs.end() ) {
        if( !( *iter ) || !( *iter )->assigned_camp || *( *iter )->assigned_camp != omt_pos ) {
            iter = assigned_npcs.erase( iter );
        } else {
            ++iter;
        }
    }
    for( character_id elem : g->get_follower_list() ) {
        npc_ptr npc_to_add = overmap_buffer.find_npc( elem );
        if( !npc_to_add ) {
            continue;
        }
        if( std::find( assigned_npcs.begin(), assigned_npcs.end(), npc_to_add ) != assigned_npcs.end() ) {
            continue;
        } else {
            if( npc_to_add->assigned_camp && *npc_to_add->assigned_camp == omt_pos ) {
                assigned_npcs.push_back( npc_to_add );
            }
        }
    }
    // remove duplicates - for legacy handling.
    std::sort( assigned_npcs.begin(), assigned_npcs.end() );
    auto last = std::unique( assigned_npcs.begin(), assigned_npcs.end() );
    assigned_npcs.erase( last, assigned_npcs.end() );
}
References assigned_npcs, detail::find(), overmapbuffer::find_npc(), g, last, omt_pos, and overmap_buffer.
Referenced by abandon_camp(), talk_function::assign_camp(), iexamine::bulletin_board(), finish_return(), get_available_missions(), get_npcs_assigned(), job_assignment_ui(), and worker_assignment_ui().
validate_bb_pos()
void basecamp::validate_bb_pos (const tripoint & new_abs_pos) inline
Definition at line 143 of file basecamp.h.
{
            if( bb_pos == tripoint_zero ) {
                bb_pos = new_abs_pos;
            }
        }
References bb_pos, and tripoint_zero.
Referenced by iexamine::bulletin_board().
validate_sort_points()
bool basecamp::validate_sort_points ()
Definition at line 3586 of file faction_camp.cpp.
{
    auto &mgr = zone_manager::get_manager();
    map &here = get_map();
    if( here.check_vehicle_zones( g->get_levz() ) ) {
        mgr.cache_vzones();
    }
    tripoint src_loc = here.getlocal( bb_pos ) + point_north;
    const tripoint abspos = here.getabs( g->u.pos() );
    if( !mgr.has_near( zone_type_camp_storage, abspos, 60 ) ||
        !mgr.has_near( zone_type_camp_food, abspos, 60 ) ) {
        if( query_yn( _( "You do not have sufficient sort zones.  Do you want to add them?" ) ) ) {
            return set_sort_points();
        } else {
            return false;
        }
    } else {
        const std::unordered_set<tripoint> &src_set = mgr.get_near( zone_type_camp_storage, abspos );
        const std::vector<tripoint> &src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
        // Find the nearest unsorted zone to dump objects at
        for( auto &src : src_sorted ) {
            src_loc = here.getlocal( src );
            break;
        }
    }
    set_dumping_spot( here.getabs( src_loc ) );
    return true;
}
References _, bb_pos, map::check_vehicle_zones(), g, zone_manager::get_manager(), get_map(), get_sorted_tiles_by_distance(), map::getabs(), map::getlocal(), point_north, query_yn(), set_dumping_spot(), set_sort_points(), zone_type_camp_food, and zone_type_camp_storage.
Referenced by iexamine::bulletin_board(), distribute_food(), set_sort_points(), and start_menial_labor().
worker_assignment_ui()
void basecamp::worker_assignment_ui ()
Definition at line 1649 of file faction_camp.cpp.
{
    int entries_per_page = 0;
    catacurses::window w_followers;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const point term( TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0,
                          TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 );
        w_followers = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                          point( term.y, term.x ) );
        entries_per_page = FULL_SCREEN_HEIGHT - 4;
        ui.position_from_window( w_followers );
    } );
    ui.mark_resize();
    size_t selection = 0;
    input_context ctxt( "FACTION MANAGER" );
    ctxt.register_updown();
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    validate_assignees();
    g->validate_npc_followers();
    std::vector<npc *> followers;
    npc *cur_npc = nullptr;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w_followers );
        // entries_per_page * page number
        const size_t top_of_page = entries_per_page * ( selection / entries_per_page );
        for( int i = 0; i < FULL_SCREEN_HEIGHT - 1; i++ ) {
            mvwputch( w_followers, point( 45, i ), BORDER_COLOR, LINE_XOXO );
        }
        draw_border( w_followers );
        const nc_color col = c_white;
        const std::string no_npcs = _( "You have no companions following you." );
        if( !followers.empty() ) {
            draw_scrollbar( w_followers, selection, entries_per_page, followers.size(),
                            point( 0, 3 ) );
            for( size_t i = top_of_page; i < followers.size(); i++ ) {
                const int y = i - top_of_page + 3;
                trim_and_print( w_followers, point( 1, y ), 43, selection == i ? hilite( col ) : col,
                                followers[i]->disp_name() );
            }
        } else {
            mvwprintz( w_followers, point( 1, 4 ), c_light_red, no_npcs );
        }
        mvwprintz( w_followers, point( 1, FULL_SCREEN_HEIGHT - 1 ), c_light_gray,
                   _( "Press %s to assign this follower to this camp." ), ctxt.get_desc( "CONFIRM" ) );
        wnoutrefresh( w_followers );
    } );
    while( true ) {
        // create a list of npcs stationed at this camp
        followers.clear();
        for( const character_id &elem : g->get_follower_list() ) {
            shared_ptr_fast<npc> npc_to_get = overmap_buffer.find_npc( elem );
            if( !npc_to_get || !npc_to_get->is_following() ) {
                continue;
            }
            npc *npc_to_add = npc_to_get.get();
            followers.push_back( npc_to_add );
        }
        cur_npc = nullptr;
        if( !followers.empty() ) {
            cur_npc = followers[selection];
        }
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "DOWN" ) {
            selection++;
            if( selection >= followers.size() ) {
                selection = 0;
            }
        } else if( action == "UP" ) {
            if( selection == 0 ) {
                selection = followers.empty() ? 0 : followers.size() - 1;
            } else {
                selection--;
            }
        } else if( action == "CONFIRM" ) {
            if( !followers.empty() && cur_npc ) {
                talk_function::assign_camp( *cur_npc );
            }
        } else if( action == "QUIT" ) {
            break;
        }
    }
}
References _, action, talk_function::assign_camp(), BORDER_COLOR, c_light_gray, c_light_red, c_white, draw_border(), draw_scrollbar(), overmapbuffer::find_npc(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, input_context::get_desc(), input_context::handle_input(), hilite(), LINE_XOXO, mvwprintz(), mvwputch(), catacurses::newwin(), overmap_buffer, ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), TERMX, TERMY, trim_and_print(), validate_assignees(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by handle_mission().
Friends And Related Function Documentation
basecamp_action_components
friend class basecamp_action_components friend
Definition at line 345 of file basecamp.h.
Member Data Documentation
_inv
inventory basecamp::_inv private
Definition at line 363 of file basecamp.h.
Referenced by add_available_recipes(), available_upgrades(), basecamp_action_components::choose_components(), craft_description(), form_crafting_inventory(), om_upgrade_description(), recipe_batch_max(), start_crafting(), start_farm_op(), start_fortifications(), and start_upgrade().
assigned_npcs
std::vector<npc_ptr> basecamp::assigned_npcs private
Definition at line 353 of file basecamp.h.
Referenced by add_assignee(), get_npcs_assigned(), remove_assignee(), and validate_assignees().
bb_pos
tripoint basecamp::bb_pos private
Definition at line 355 of file basecamp.h.
Referenced by abandon_camp(), board_x(), board_y(), get_bb_pos(), load_data(), set_bb_pos(), validate_bb_pos(), and validate_sort_points().
by_radio
bool basecamp::by_radio = false private
Definition at line 364 of file basecamp.h.
Referenced by basecamp_action_components::choose_components(), basecamp_action_components::consume_components(), form_crafting_inventory(), get_available_missions(), place_results(), and set_by_radio().
camp_workers
comp_list basecamp::camp_workers private
Definition at line 357 of file basecamp.h.
Referenced by get_available_missions(), get_mission_workers(), and reset_camp_workers().
directions
std::vector<point> basecamp::directions
Definition at line 154 of file basecamp.h.
Referenced by add_expansion(), can_expand(), get_available_missions(), and recruit_evaluation().
dumping_spot
tripoint basecamp::dumping_spot private
Definition at line 358 of file basecamp.h.
Referenced by get_dumping_spot(), and set_dumping_spot().
expansions
std::map<point, expansion_data> basecamp::expansions private
Definition at line 356 of file basecamp.h.
Referenced by add_expansion(), available_upgrades(), define_camp(), expansion_tab(), get_gatherlist(), has_provides(), next_upgrade(), recipe_deck(), recruit_evaluation(), reset_camp_resources(), survey_return(), update_in_progress(), and upgrade_return().
fortifications
std::vector<tripoint_abs_omt> basecamp::fortifications
Definition at line 155 of file basecamp.h.
Referenced by fortifications_return(), and start_fortifications().
fuel_types
std::set<itype_id> basecamp::fuel_types private
Definition at line 360 of file basecamp.h.
Referenced by add_resource(), and form_crafting_inventory().
fuels
std::vector<basecamp_fuel> basecamp::fuels private
Definition at line 361 of file basecamp.h.
Referenced by form_crafting_inventory().
inv_range
constexpr int basecamp::inv_range = 20 static constexpr
Definition at line 343 of file basecamp.h.
Referenced by basecamp_action_components::consume_components(), and form_crafting_inventory().
name
std::string basecamp::name
Definition at line 156 of file basecamp.h.
Referenced by abandon_camp(), board_name(), camp_name(), is_valid(), load_data(), query_new_name(), recruit_return(), and set_name().
omt_pos
tripoint_abs_omt basecamp::omt_pos private
Definition at line 352 of file basecamp.h.
Referenced by add_assignee(), add_expansion(), camp_omt_pos(), companion_choose_return(), define_camp(), emergency_recall(), form_crafting_inventory(), get_available_missions_by_dir(), handle_mission(), is_valid(), place_results(), reset_camp_workers(), start_clearcut(), start_combat_mission(), start_cut_logs(), start_fortifications(), start_mission(), start_relay_hide_site(), start_setup_hide_site(), survey_return(), and validate_assignees().
resources
std::vector<basecamp_resource> basecamp::resources private
Definition at line 362 of file basecamp.h.
Referenced by add_resource(), basecamp_action_components::consume_components(), form_crafting_inventory(), and use_charges().
resources_updated
bool basecamp::resources_updated = false private
Definition at line 350 of file basecamp.h.
Referenced by add_expansion(), and reset_camp_resources().
The documentation for this class was generated from the following files:
src/basecamp.h
src/basecamp.cpp
src/faction.cpp
src/faction_camp.cpp
src/savegame_json.cpp