Cataclysm BN: avatar Class Reference
avatar Class Reference
#include <avatar.h>
Public Member Functions
avatar ()
avatar (const avatar &)=delete
avatar (avatar &&)
~avatar () override
avatar & operator= (const avatar &)=delete
avatar & operator= (avatar &&)
void store (JsonOut &json) const
void load (const JsonObject &data)
void serialize (JsonOut &json) const override
void deserialize (JsonIn &jsin) override
bool save_map_memory ()
void load_map_memory ()
bool create (character_type type, const std::string &tempname="")
void randomize (bool random_scenario, points_left &points, bool play_now=false)
bool load_template (const std::string &template_name, points_left &points)
void save_template (const std::string &name, const points_left &points)
bool is_avatar () const override
avatar * as_avatar () override
const avatar * as_avatar () const override
void toggle_map_memory ()
bool should_show_map_memory ()
void prepare_map_memory_region (const tripoint &p1, const tripoint &p2)
void memorize_tile (const tripoint &pos, const std::string &ter, int subtile, int rotation)
Memorizes a given tile in tiles mode; finalize_tile_memory needs to be called after it.
const memorized_terrain_tile & get_memorized_tile (const tripoint &p) const
Returns last stored map tile in given location in tiles mode.
void memorize_symbol (const tripoint &pos, int symbol)
Memorizes a given tile in curses mode; finalize_terrain_memory_curses needs to be called after it.
int get_memorized_symbol (const tripoint &p) const
Returns last stored map tile in given location in curses mode.
void clear_memorized_tile (const tripoint &pos)
bool has_memorized_tile_for_autodrive (const tripoint &p) const
Returns last stored map tile in given location in tiles mode.
void disp_morale ()
Provides the window and detailed morale data.
void reset_all_misions ()
Resets all missions before saving character to template.
std::vector< mission * > get_active_missions () const
std::vector< mission * > get_completed_missions () const
std::vector< mission * > get_failed_missions () const
mission * get_active_mission () const
Returns the mission that is currently active.
tripoint_abs_omt get_active_mission_target () const
Returns the target of the active mission or overmap::invalid_tripoint if there is no active mission.
void set_active_mission (mission &cur_mission)
Set which mission is active.
void on_mission_assignment (mission &new_mission)
Called when a mission has been assigned to the player.
void on_mission_finished (mission &cur_mission)
Called when a mission has been completed or failed.
diary * get_avatar_diary ()
const player * get_book_reader (const item &book, std::vector< std::string > &reasons) const
Helper function for player::read.
int time_to_read (const item &book, const player &reader, const player *learner=nullptr) const
Helper function for get_book_reader.
bool read (item_location loc, bool continuous=false)
Handles reading effects and returns true if activity started.
void do_read (item_location loc)
Completes book reading action.
bool has_identified (const itype_id &item_id) const
Note that we've read a book at least once.
void wake_up ()
void grab (object_type grab_type, const tripoint &grab_point=tripoint_zero)
object_type get_grab_type () const
void vomit ()
Handles player vomiting effects.
bool is_hallucination () const override
int get_str_base () const override
int get_dex_base () const override
int get_int_base () const override
int get_per_base () const override
int free_upgrade_points () const
int kill_xp () const
cata::optional< int > kill_xp_for_next_point () const
void upgrade_stat (character_stat stat)
faction * get_faction () const override
void set_movement_mode (character_movemode mode) override
void cycle_move_mode ()
void reset_move_mode ()
void toggle_run_mode ()
void toggle_crouch_mode ()
bool wield (item &target) override
Removes currently wielded item (if any) and replaces it with the target item.
bool add_faction_warning (const faction_id &id)
Add warning from faction.
bool invoke_item (item *, const tripoint &pt) override
Asks how to use the item (if it has more than one use_method) and uses it.
bool invoke_item (item *) override
As above two, but with position equal to current position.
bool invoke_item (item *, const std::string &, const tripoint &pt) override
As above, but with a pre-selected method.
bool invoke_item (item *, const std::string &) override
monster_visible_info & get_mon_visible ()
virtual bool invoke_item (item *, const tripoint &pt)
Asks how to use the item (if it has more than one use_method) and uses it.
virtual bool invoke_item (item *, const std::string &, const tripoint &pt)
As above, but with a pre-selected method.
virtual bool invoke_item (item *)
As above two, but with position equal to current position.
virtual bool invoke_item (item *, const std::string &)
Public Member Functions inherited from player
player ()
player (const player &)=delete
player (player &&)
~player () override
player & operator= (const player &)=delete
player & operator= (player &&)
bool is_player () const override
player * as_player () override
const player * as_player () const override
bool is_npc () const override
item reduce_charges (int position, int quantity)
Remove charges from a specific item (given by its item position).
item reduce_charges (item *it, int quantity)
Remove charges from a specific item (given by a pointer to it).
int has_recipe (const recipe *r, const inventory &crafting_inv, const std::vector< npc * > &helpers) const
bool has_recipe_requirements (const recipe &rec) const
bool studied_all_recipes (const itype &book) const
recipe_subset get_recipes_from_books (const inventory &crafting_inv, recipe_filter filter=nullptr) const
Returns all recipes that are known from the books (either in inventory or nearby).
recipe_subset get_available_recipes (const inventory &crafting_inv, const std::vector< npc * > *helpers=nullptr, recipe_filter filter=nullptr) const
Returns all available recipes (from books and npc companions)
int available_assistant_count (const recipe &rec) const
For use with in progress crafts.
int base_time_to_craft (const recipe &rec, int batch_size=1) const
Time to craft not including speed multiplier.
int expected_time_to_craft (const recipe &rec, int batch_size=1, bool in_progress=false) const
Expected time to craft a recipe, with assumption that multipliers stay constant.
std::vector< const item * > get_eligible_containers_for_crafting () const
bool check_eligible_containers_for_crafting (const recipe &rec, int batch_size=1) const
bool can_make (const recipe *r, int batch_size=1)
bool can_start_craft (const recipe *rec, recipe_filter_flags, int batch_size=1)
Returns true if the player can start crafting the recipe with the given batch size The player is not required to have enough tool charges to finish crafting, only to complete the first step (total / 20 + total % 20 charges)
bool making_would_work (const recipe_id &id_to_make, int batch_size)
void craft (const tripoint &loc=tripoint_zero)
Start various types of crafts.
void recraft (const tripoint &loc=tripoint_zero)
void long_craft (const tripoint &loc=tripoint_zero)
void make_craft (const recipe_id &id, int batch_size, const tripoint &loc=tripoint_zero)
void make_all_craft (const recipe_id &id, int batch_size, const tripoint &loc=tripoint_zero)
item_location start_craft (craft_command &command, const tripoint &loc)
consume components and create an active, in progress craft containing them
double crafting_success_roll (const recipe &making) const
Calculate a value representing the success of the player at crafting the given recipe, taking player skill, recipe difficulty, npc helpers, and player mutations into account.
bool can_continue_craft (item &craft)
Check if the player meets the requirements to continue the in progress craft and if unable to continue print messages explaining the reason.
void craft_skill_gain (const item &craft, const int &multiplier)
Handle skill gain for player and followers during crafting.
const requirement_data * select_requirements (const std::vector< const requirement_data * > &, int batch, const inventory &, const std::function< bool(const item &)> &filter) const
comp_selection< item_comp > select_item_component (const std::vector< item_comp > &components, int batch, inventory &map_inv, bool can_cancel=false, const std::function< bool(const item &)> &filter=return_true< item >, bool player_inv=true)
std::list< item > consume_items (const comp_selection< item_comp > &is, int batch, const std::function< bool(const item &)> &filter=return_true< item >)
std::list< item > consume_items (map &m, const comp_selection< item_comp > &is, int batch, const std::function< bool(const item &)> &filter=return_true< item >, const tripoint &origin=tripoint_zero, int radius=PICKUP_RANGE)
std::list< item > consume_items (const std::vector< item_comp > &components, int batch=1, const std::function< bool(const item &)> &filter=return_true< item >)
bool craft_consume_tools (item &craft, int mulitplier, bool start_craft)
Consume tools for the next multiplier * 5% progress of the craft.
void consume_tools (const comp_selection< tool_comp > &tool, int batch)
void consume_tools (map &m, const comp_selection< tool_comp > &tool, int batch, const tripoint &origin=tripoint_zero, int radius=PICKUP_RANGE, basecamp *bcp=nullptr)
void consume_tools (const std::vector< tool_comp > &tools, int batch=1, const std::string &hotkeys=DEFAULT_HOTKEYS)
void make_craft_with_command (const recipe_id &id_to_make, int batch_size, bool is_long=false, const tripoint &loc=tripoint_zero)
void add_msg_if_player (const std::string &msg) const override
void add_msg_if_player (const game_message_params &params, const std::string &msg) const override
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_str) const override
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg) const override
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech) const override
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech) const override
bool query_yn (const std::string &mes) const override
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args) const
It is supposed to hide the query_yn to simplify player vs.
virtual bool query_yn (const std::string &msg) const=0
Public Member Functions inherited from Character
Character (const Character &)=delete
Character & operator= (const Character &)=delete
~Character () override
Character * as_character () override
const Character * as_character () const override
character_id getID () const
void setID (character_id i, bool force=false)
bool is_dead_state () const override
Returns true if the character should be dead.
field_type_id bloodType () const override
field_type_id gibType () const override
bool is_warm () const override
bool in_species (const species_id &spec) const override
const std::string & symbol () const override
virtual int get_str () const
Getters for stats exclusive to characters.
virtual int get_dex () const
virtual int get_per () const
virtual int get_int () const
virtual int get_str_bonus () const
virtual int get_dex_bonus () const
virtual int get_per_bonus () const
virtual int get_int_bonus () const
int get_speed () const override
virtual int ranged_dex_mod () const
virtual int ranged_per_mod () const
virtual void set_str_bonus (int nstr)
Setters for stats exclusive to characters.
virtual void set_dex_bonus (int ndex)
virtual void set_per_bonus (int nper)
virtual void set_int_bonus (int nint)
virtual void mod_str_bonus (int nstr)
virtual void mod_dex_bonus (int ndex)
virtual void mod_per_bonus (int nper)
virtual void mod_int_bonus (int nint)
void print_health () const
virtual int get_healthy () const
Getters for health values exclusive to characters.
virtual int get_healthy_mod () const
virtual void mod_healthy (int nhealthy)
Modifiers for health values exclusive to characters.
virtual void mod_healthy_mod (int nhealthy_mod, int cap)
virtual void set_healthy (int nhealthy)
Setters for health values exclusive to characters.
virtual void set_healthy_mod (int nhealthy_mod)
int get_stored_kcal () const
Getter for need values exclusive to characters.
int max_stored_kcal () const
float get_kcal_percent () const
int get_thirst () const
std::pair< std::string, nc_color > get_thirst_description () const
std::pair< std::string, nc_color > get_hunger_description () const
std::pair< std::string, nc_color > get_fatigue_description () const
int get_fatigue () const
int get_sleep_deprivation () const
std::pair< std::string, nc_color > get_pain_description () const override
virtual void mod_stored_kcal (int nkcal)
Modifiers for need values exclusive to characters.
virtual void mod_stored_nutr (int nnutr)
virtual void mod_thirst (int nthirst)
virtual void mod_fatigue (int nfatigue)
virtual void mod_sleep_deprivation (int nsleep_deprivation)
virtual void set_stored_kcal (int kcal)
Setters for need values exclusive to characters.
virtual void set_thirst (int nthirst)
virtual void set_fatigue (int nfatigue)
virtual void set_sleep_deprivation (int nsleep_deprivation)
void mod_stat (const std::string &stat, float modifier) override
m_size get_size () const override
Get size class of character.
void recalculate_size ()
Recalculate size class of character.
void recalc_speed_bonus ()
Calculates the various speed bonuses we will get from mutations, etc.
std::string disp_name (bool possessive=false, bool capitalize_first=false) const override
Returns either "you" or the player's name.
std::string skin_name () const override
Returns the name of the player's outer layer, e.g.
void set_fac_id (const std::string &my_fac_id)
float get_dodge_base () const override
Combat getters.
float get_hit_base () const override
float get_dodge () const override
float dodge_roll () override
float get_melee () const override
Returns melee skill level, to be used to throttle dodge practice.
const tripoint & pos () const override
int sight_range (int light_level) const override
Returns the player's sight range.
int unimpaired_range () const
Returns the player maximum vision range factoring in mutations, diseases, and other effects.
bool overmap_los (const tripoint_abs_omt &omt, int sight_points)
Returns true if overmap tile is within player line-of-sight.
int overmap_sight_range (int light_level) const
Returns the distance the player can see on the overmap.
int clairvoyance () const
Returns the distance the player can see through walls.
bool sight_impaired () const
Returns true if the player has some form of impaired sight.
bool has_alarm_clock () const
Returns true if the player or their vehicle has an alarm clock.
bool has_watch () const
Returns true if the player or their vehicle has a watch.
void action_taken ()
Called after every action, invalidates player caches.
bool is_on_ground () const override
Returns true if the player is knocked over or has broken legs.
int swim_speed () const
Returns the player's speed for swimming across water tiles.
void add_miss_reason (const std::string &reason, unsigned int weight)
Adds a reason for why the player would miss a melee attack.
void clear_miss_reasons ()
Clears the list of reasons for why the player would miss a melee attack.
std::string get_miss_reason ()
Returns an explanation for why the player would miss a melee attack.
void knock_back_to (const tripoint &to) override
Knocks the character to a specified tile.
float fall_damage_mod () const override
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
int impact (int force, const tripoint &pos) override
Deals falling/collision damage with terrain/creature at pos.
int hp_percentage () const override
Returns overall % of HP remaining.
void regen (int rate_multiplier)
Handles passive regeneration of pain and maybe hp.
void enforce_minimum_healing ()
item * best_quality_item (const quality_id &qual)
get best quality item that this character has
virtual void update_health (int external_modifiers=0)
Handles health fluctuations over time.
void update_body ()
Updates all "biology" by one turn.
void update_body (const time_point &from, const time_point &to)
Updates all "biology" as if time between from and to passed.
void update_stomach (const time_point &from, const time_point &to)
Updates the stomach to give accurate hunger messages.
void update_needs (int rate_multiplier)
Increases hunger, thirst, fatigue and stimulants wearing off.
needs_rates calc_needs_rates () const
void check_needs_extremes ()
Kills the player if too hungry, stimmed up etc., forces tired player to sleep and prints warnings.
bool is_hibernating () const
Returns if the player has hibernation mutation and is asleep and well fed.
void update_bodytemp (const map &m, const weather_manager &weather)
Maintains body temperature.
void temp_equalizer (const bodypart_id &bp1, const bodypart_id &bp2)
Equalizes heat between body parts.
int blood_loss (const bodypart_id &bp) const
Define blood loss (in percents)
void reset_bonuses () override
Resets the value of all bonus fields to 0.
void reset_stats () override
Resets stats, and applies effects in an idempotent manner.
void reset () override
Handles stat and bonus reset.
void environmental_revert_effect ()
void reset_encumbrance ()
Recalculates encumbrance cache.
int encumb (body_part bp) const
Returns ENC provided by armor, etc.
units::mass get_weight () const override
Returns body weight plus weight of inventory and worn/wielded items.
char_encumbrance_data get_encumbrance () const
Get encumbrance for all body parts.
char_encumbrance_data get_encumbrance (const item &new_item) const
Get encumbrance for all body parts as if new_item was also worn.
int extraEncumbrance (layer_level level, int bp) const
Get encumbrance penalty per layer & body part.
bool is_wearing_power_armor (bool *hasHelmet=nullptr) const
Returns true if the character is wearing power armor.
bool is_wearing_active_power_armor () const
Returns true if the character is wearing active power.
bool is_wearing_active_optcloak () const
Returns true if the player is wearing an active optical cloak.
bool in_climate_control ()
Returns true if the player is in a climate controlled area or armor.
bool is_blind () const
Returns true if the player isn't able to see.
bool is_invisible () const
int visibility (bool check_color=false, int stillness=0) const
Checks is_invisible() as well as other factors.
float active_light () const
Returns character luminosity based on the brightest active item they are carrying.
bool sees_with_specials (const Creature &critter) const
body_part_set exclusive_flag_coverage (const std::string &flag) const
Bitset of all the body parts covered only with items with flag (or nothing)
bool move_effects (bool attacking) override
Processes effects which may prevent the Character from moving (bear traps, crushed, etc.).
void wait_effects ()
bool movement_mode_is (character_movemode mode) const
Check against the character's current movement mode.
character_movemode get_movement_mode () const
void expose_to_disease (diseasetype_id dis_type)
Determine if character is susceptible to dis_type and if so apply the symptoms.
void process_turn () override
Handles end-of-turn processing.
void process_effects_internal () override
Processes human-specific effects of effects before calling Creature::process_effects().
void hardcoded_effects (effect &it)
Handles the still hard-coded effects.
void process_one_effect (effect &it, bool is_new) override
Processes human-specific effects of an effect.
void process_items ()
Process active items.
void recalc_hp ()
Recalculates HP after a change to max strength.
void calc_all_parts_hp (float hp_mod=0.0, float hp_adjust=0.0, int str_max=0)
Sets hp for all body parts.
void recalc_sight_limits ()
Modifies the player's sight values Must be called when any of the following change: This must be called when any of the following change:
float get_vision_threshold (float light_level) const
Returns the apparent light level at which the player can see.
void flag_encumbrance ()
Flag encumbrance for updating.
void check_item_encumbrance_flag ()
Checks worn items for the "RESET_ENCUMBRANCE" flag, which indicates that encumbrance may have changed and require recalculating.
bool natural_attack_restricted_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body_part, ignoring items with the ALLOWS_NATURAL_ATTACKS flag.
bool can_use_grab_break_tec (const item &weap) const
Returns true if the player is able to use a grab breaking technique.
bool can_miss_recovery (const item &weap) const
Returns true if the player is able to use a miss recovery technique.
bool is_quiet () const
Returns true if the player has quiet melee attacks.
bool is_stealthy () const
Returns true if the player has stealthy movement.
bool uncanny_dodge () override
Handles the uncanny dodge bionic and effects, returns true if the creature successfully dodges.
bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &dam) override
Checks for valid block abilities and reduces damage accordingly.
item & best_shield ()
Returns the best item for blocking with.
bool handle_melee_wear (item &shield, float wear_multiplier=1.0f)
Calculates melee weapon wear-and-tear through use, returns true if item is destroyed.
matec_id pick_technique (Creature &t, const item &weap, bool crit, bool dodge_counter, bool block_counter)
Returns a random valid technique.
void perform_technique (const ma_technique &technique, Creature &t, damage_instance &di, int &move_cost)
void melee_attack (Creature &t, bool allow_special, const matec_id *force_technique=nullptr, bool allow_unarmed=true)
Sets up a melee attack and handles melee attack function calls.
std::string melee_special_effects (Creature &t, damage_instance &d, item &weap)
Handles combat effects, returns a string of any valid combat effect messages.
void perform_special_attacks (Creature &t, dealt_damage_instance &dealt_dam)
Performs special attacks and their effects (poisonous, stinger, etc.)
void reach_attack (const tripoint &p)
Handles reach melee attack on point p.
float stability_roll () const override
Returns value of player's stable footing.
std::vector< special_attack > mutation_attacks (Creature &t) const
Returns a vector of valid mutation attacks.
float bonus_damage (bool random) const
Returns the bonus bashing damage the player deals based on their stats.
float get_melee_hit_base () const
Returns weapon skill.
float hit_roll () const override
Returns the player's basic hit roll that is compared to the target's dodge roll.
double crit_chance (float roll_hit, float target_dodge, const item &weap) const
Returns the chance to critical given a hit roll and target's dodge roll.
bool scored_crit (float target_dodge, const item &weap) const
Returns true if the player scores a critical hit.
int attack_cost (const item &weap) const
Returns cost (in moves) of attacking with given item (no modifiers, like stuck)
float get_hit_weapon (const item &weap) const
Gets melee accuracy component from weapon+skills.
void roll_all_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds all 3 types of physical damage to instance.
void roll_bash_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds player's total bash damage to the damage instance.
void roll_cut_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds player's total cut damage to the damage instance.
void roll_stab_damage (bool crit, damage_instance &di, bool average, const item &weap) const
Adds player's total stab damage to the damage instance.
void on_dodge (Creature *source, int difficulty) override
This creature just dodged an attack - possibly special/ranged attack - from source.
void on_hit (Creature *source, bodypart_id bp_hit, dealt_projectile_attack const *proj) override
This creature just got hit by an attack - possibly special/ranged attack - from source.
void did_hit (Creature &target)
Handles special effects when the Character hits a Creature.
void apply_damage (Creature *source, bodypart_id hurt, int dam, bool bypass_med=false) override
Actually hurt the player, hurts a body_part directly, no armor reduction.
dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &d) override
Calls Creature::deal_damage and handles damaged effects (waking up, etc.)
int reduce_healing_effect (const efftype_id &eff_id, int remove_med, const bodypart_id &hurt)
Reduce healing effect intensity, return initial intensity of the effect.
void cough (bool harmful=false, int loudness=4)
void passive_absorb_hit (const bodypart_id &bp, damage_unit &du) const
Check for relevant passive, non-clothing that can absorb damage, and reduce by specified damage unit.
void absorb_hit (const bodypart_id &bp, damage_instance &dam) override
Runs through all bionics and armor on a part and reduces damage through their armor_absorb.
bool armor_absorb (damage_unit &du, item &armor)
Reduces and mutates du, prints messages about armor taking damage.
float bionic_armor_bonus (const bodypart_id &bp, damage_type dt) const
Check for passive bionics that provide armor, and returns the armor bonus This is called from player::passive_absorb_hit.
int mabuff_armor_bonus (damage_type type) const
Returns the armor bonus against given type from martial arts buffs.
std::map< bodypart_id, int > get_armor_fire (const std::map< bodypart_id, std::vector< const item * > > &clothing_map) const
Returns overall fire resistance.
bool has_trait (const trait_id &b) const override
Returns true if the player has the entered trait.
bool has_base_trait (const trait_id &b) const
Returns true if the player has the entered starting trait.
bool has_trait_flag (const std::string &b) const
Returns true if player has a trait with a flag.
bool has_opposite_trait (const trait_id &flag) const
Returns true if character has a trait which cancels the entered trait.
void toggle_trait (const trait_id &)
Toggles a trait on the player and in their mutation list.
void set_mutation (const trait_id &)
Add or removes a mutation on the player, but does not trigger mutation loss/gain effects.
void unset_mutation (const trait_id &)
void switch_mutations (const trait_id &switched, const trait_id &target, bool start_powered)
Unset switched mutation and set target mutation instead.
void activate_mutation (const trait_id &mutation)
void deactivate_mutation (const trait_id &mut)
void mutation_spend_resources (const trait_id &mut)
Removes the appropriate costs (NOTE: will reapply mods & recalc sightlines in case of newly activated mutation).
bool can_mount (const monster &critter) const
void mount_creature (monster &z)
bool is_mounted () const
bool check_mount_will_move (const tripoint &dest_loc)
bool check_mount_is_spooked ()
void dismount ()
void forced_dismount ()
bool is_deaf () const
bool has_two_arms () const
Returns true if the player has two functioning arms.
int get_working_arm_count () const
Returns the number of functioning arms.
int get_working_leg_count () const
Returns the number of functioning legs.
bool is_limb_disabled (const bodypart_id &limb) const
Returns true if the limb is disabled(12.5% or less hp)
bool is_limb_hindered (hp_part limb) const
Returns true if the limb is hindered(40% or less hp)
bool is_limb_broken (const bodypart_id &limb) const
Returns true if the limb is broken.
bool can_run ()
source of truth of whether a Character can run
void hurtall (int dam, Creature *source, bool disturb=true)
Hurts all body parts for dam, no armor reduction.
int hitall (int dam, int vary, Creature *source)
Harms all body parts for dam, with armor reduction.
void on_hurt (Creature *source, bool disturb=true)
Handles effects that happen when the player is damaged and aware of the fact.
void heal (const bodypart_id &healed, int dam)
Heals a body_part for dam.
void healall (int dam)
Heals all body parts for dam.
hp_part body_window (const std::string &menu_header, bool show_all, bool precise, int normal_bonus, int head_bonus, int torso_bonus, float bleed, float bite, float infect, float bandage_power, float disinfectant_power) const
Displays menu with body part hp, optionally with hp estimation after healing.
nc_color limb_color (const bodypart_id &bp, bool bleed, bool bite, bool infect) const
bool made_of (const material_id &m) const override
bool made_of_any (const std::set< material_id > &ms) const override
int posx () const override
int posy () const override
int posz () const override
void setx (int x)
void sety (int y)
void setz (int z)
void setpos (const tripoint &p) override
virtual tripoint global_square_location () const
Global position, expressed in map square coordinate system (the most detailed coordinate system), used by the map.
tripoint global_sm_location () const
Returns the location of the player in global submap coordinates.
tripoint_abs_omt global_omt_location () const
Returns the location of the player in global overmap terrain coordinates.
void recalculate_enchantment_cache ()
void rebuild_mutation_cache ()
double bonus_from_enchantments (double base, enchant_vals::mod value, bool round=false) const
Calculate bonus from enchantments for given base value.
bool has_mabuff (const mabuff_id &buff_id) const
Returns true if the player has any martial arts buffs attached.
bool has_grab_break_tec () const override
Returns true if the player has a grab breaking technique available.
float mabuff_tohit_bonus () const
Returns the to hit bonus from martial arts buffs.
float mabuff_dodge_bonus () const
Returns the dodge bonus from martial arts buffs.
int mabuff_block_bonus () const
Returns the block bonus from martial arts buffs.
int mabuff_speed_bonus () const
Returns the speed bonus from martial arts buffs.
int mabuff_arpen_bonus (damage_type type) const
Returns the arpen bonus from martial arts buffs.
float mabuff_damage_mult (damage_type type) const
Returns the damage multiplier to given type from martial arts buffs.
int mabuff_damage_bonus (damage_type type) const
Returns the flat damage bonus to given type from martial arts buffs, applied after the multiplier.
int mabuff_attack_cost_penalty () const
Returns the flat penalty to move cost of attacks.
float mabuff_attack_cost_mult () const
Returns the multiplier on move cost of attacks.
void mutation_effect (const trait_id &mut)
Handles things like removal of armor, etc.
void mutation_loss_effect (const trait_id &mut)
Handles what happens when you lose a mutation.
bool has_active_mutation (const trait_id &b) const
void mutate ()
Picks a random valid mutation and gives it to the Character, possibly removing/changing others along the way.
bool mutation_ok (const trait_id &mutation, bool force_good, bool force_bad) const
Returns true if the player doesn't have the mutation or a conflicting one and it complies with the force typing.
void mutate_category (const std::string &mut_cat)
Picks a random valid mutation in a category and mutate_towards() it.
bool mutate_towards (std::vector< trait_id > muts, int num_tries=INT_MAX)
Mutates toward one of the given mutations, upgrading or removing conflicts if necessary.
bool mutate_towards (const trait_id &mut)
Mutates toward the entered mutation, upgrading or removing conflicts if necessary.
void remove_mutation (const trait_id &mut, bool silent=false)
Removes a mutation, downgrading to the previous level if possible.
std::map< trait_id, float > mutation_chances () const
Calculate percentage chances for mutations.
bool has_child_flag (const trait_id &flag) const
Returns true if the player has the entered mutation child flag.
void remove_child_flag (const trait_id &flag)
Removes the mutation's child flag from the player's list.
void set_highest_cat_level ()
Recalculates mutation_category_level[] values for the player.
std::string get_highest_category () const
Returns the highest mutation category.
void drench_mut_calc ()
Recalculates mutation drench protection for all bodyparts (ignored/good/neutral stats)
void build_mut_dependency_map (const trait_id &mut, std::unordered_map< trait_id, int > &dependency_map, int distance)
Recursively traverses the mutation's prerequisites and replacements, building up a map.
bool is_category_allowed (const std::vector< std::string > &category) const
Returns true if this category of mutation is allowed.
bool is_category_allowed (const std::string &category) const
bool is_weak_to_water () const
bool can_use_heal_item (const item &med) const
Check for mutation disallowing the use of an healing item.
bool can_install_cbm_on_bp (const std::vector< bodypart_id > &bps) const
resistances mutation_armor (bodypart_id bp) const
Returns resistances on a body part provided by mutations.
float mutation_armor (bodypart_id bp, damage_type dt) const
float mutation_armor (bodypart_id bp, const damage_unit &du) const
bool activate_bionic (bionic &bio, bool eff_only=false)
Handles bionic activation effects of the entered bionic, returns if anything activated.
std::vector< bionic_id > get_bionics () const
bionic & get_bionic_state (const bionic_id &id)
Get state of bionic with given id.
std::pair< int, int > amount_of_storage_bionics () const
Returns amount of Storage CBMs in the corpse.
bool has_bionic (const bionic_id &b) const
Returns true if the player has the entered bionic id.
bool has_active_bionic (const bionic_id &b) const
Returns true if the player has the entered bionic id and it is powered on.
bool has_any_bionic () const
Returns true if the player has any bionic.
bool can_fuel_bionic_with (const item &it) const
Returns true if the character can fuel a bionic with the item.
std::vector< bionic_id > get_bionic_fueled_with (const item &it) const
Return bionic_id of bionics able to use it as fuel.
std::vector< bionic_id > get_fueled_bionics () const
Return bionic_id of fueled bionics.
bionic_id get_remote_fueled_bionic () const
Returns bionic_id of first remote fueled bionic found.
bionic_id get_most_efficient_bionic (const std::vector< bionic_id > &bids) const
Return bionic_id of bionic of most fuel efficient bionic.
std::vector< itype_id > get_fuel_available (const bionic_id &bio) const
Return list of available fuel for this bionic.
int get_fuel_capacity (const itype_id &fuel) const
Return available space to store specified fuel.
int get_total_fuel_capacity (const itype_id &fuel) const
Return total space to store specified fuel.
void update_fuel_storage (const itype_id &fuel)
Updates which bionic contain fuel and which is empty.
int get_mod_stat_from_bionic (const character_stat &Stat) const
Get stat bonus from bionic.
void process_bionic (bionic &bio)
Handles bionic effects over time of the entered bionic.
bool deactivate_bionic (bionic &bio, bool eff_only=false)
Handles bionic deactivation effects of the entered bionic, returns if anything deactivated.
bool has_bionics () const
Whether character has any bionics installed.
void clear_bionics ()
Remove all bionics.
int get_used_bionics_slots (const bodypart_id &bp) const
int get_total_bionics_slots (const bodypart_id &bp) const
int get_free_bionics_slots (const bodypart_id &bp) const
bool has_enough_anesth (const itype *cbm, player &patient)
Has enough anesthetic for surgery.
void introduce_into_anesthesia (const time_duration &duration, player &installer, bool needs_anesthesia)
Handles process of introducing patient into anesthesia during Autodoc operations.
void remove_bionic (const bionic_id &b)
Removes a bionic from my_bionics[].
void add_bionic (const bionic_id &b)
Adds a bionic to my_bionics[].
float env_surgery_bonus (int radius)
Calculate skill bonus from tiles in radius.
float bionics_adjusted_skill (const skill_id &most_important_skill, const skill_id &important_skill, const skill_id &least_important_skill, int skill_level=-1)
Calculate skill for (un)installing bionics.
int bionics_pl_skill (const skill_id &most_important_skill, const skill_id &important_skill, const skill_id &least_important_skill, int skill_level=-1)
Calculate non adjusted skill for (un)installing bionics.
bool can_install_bionics (const itype &type, player &installer, bool autodoc=false, int skill_level=-1)
Is the installation possible.
std::map< bodypart_id, int > bionic_installation_issues (const bionic_id &bioid) const
bool install_bionics (const itype &type, player &installer, bool autodoc=false, int skill_level=-1)
Initialize all the values needed to start the operation player_activity.
void perform_install (bionic_id bid, bionic_id upbid, int difficulty, int success, int pl_skill, const std::string &installer_name, const std::vector< trait_id > &trait_to_rem)
Success or failure of installation happens here.
void do_damage_for_bionic_failure (int min_damage, int max_damage)
void bionics_install_failure (const std::string &installer, int difficulty, int success, float adjusted_skill)
bool can_uninstall_bionic (const bionic_id &b_id, player &installer, bool autodoc=false, int skill_level=-1)
Is The uninstallation possible.
bool uninstall_bionic (const bionic_id &b_id, player &installer, bool autodoc=false, int skill_level=-1)
Initialize all the values needed to start the operation player_activity.
void perform_uninstall (bionic_id bid, int difficulty, int success, const units::energy &power_lvl, int pl_skill)
Succes or failure of removal happens here.
void bionics_uninstall_failure (int difficulty, int success, float adjusted_skill)
When a player fails the surgery.
bool uninstall_bionic (const bionic &target_cbm, monster &installer, player &patient, float adjusted_skill)
Used by monster to perform surgery.
void bionics_uninstall_failure (monster &installer, player &patient, int difficulty, int success, float adjusted_skill)
When a monster fails the surgery.
bool burn_fuel (bionic &bio, bool start=false)
Convert fuel to bionic power.
void passive_power_gen (bionic &bio)
Passively produce power from PERPETUAL fuel.
itype_id find_remote_fuel (bool look_only=false)
Find fuel used by remote powered bionic.
int consume_remote_fuel (int amount)
Consume fuel used by remote powered bionic, return amount of request unfulfilled (0 if totally successful).
void reset_remote_fuel ()
void heat_emission (bionic &bio, int fuel_energy)
Handle heat from exothermic power generation.
float get_effective_efficiency (bionic &bio, float fuel_efficiency)
Applies modifier to fuel_efficiency and returns the resulting efficiency.
units::energy get_power_level () const
units::energy get_max_power_level () const
void mod_power_level (const units::energy &npower)
void mod_max_power_level (const units::energy &npower_max)
void set_power_level (const units::energy &npower)
void set_max_power_level (const units::energy &npower_max)
bool is_max_power () const
bool has_power () const
bool has_max_power () const
bool enough_power_for (const bionic_id &bid) const
void conduct_blood_analysis () const
bool is_worn (const item &thing) const
virtual bool dispose_item (item_location &&obj, const std::string &prompt=std::string())
Drop, wear, stash or otherwise try to dispose of an item consuming appropriate moves.
bool has_enough_charges (const item &it, bool show_msg) const
Has the item enough charges to invoke its use function? Also checks if UPS from this player is used instead of item charges.
bool consume_charges (item &used, int qty)
Consume charges of a tool or comestible item, potentially destroying it in the process.
int item_handling_cost (const item &it, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY) const
Calculate (but do not deduct) the number of moves required when handling (e.g.
int item_store_cost (const item &it, const item &container, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY) const
Calculate (but do not deduct) the number of moves required when storing an item in a container.
int item_wear_cost (const item &it) const
Calculate (but do not deduct) the number of moves required to wear an item.
int amount_worn (const itype_id &id) const
Returns the amount of item ‘type’ that is currently worn.
std::vector< item_location > nearby (const std::function< bool(const item *, const item *)> &func, int radius=1) const
Returns nearby items which match the provided predicate.
std::list< item > remove_worn_items_with (std::function< bool(item &)> filter)
Similar to remove_items_with, but considers only worn items and not their content (item::contents is not checked).
item * invlet_to_item (int invlet)
Return the item pointer of the item with given invlet, return nullptr if the player does not have such an item with that invlet.
item & i_at (int position)
const item & i_at (int position) const
int get_item_position (const item *it) const
Returns the item position (suitable for i_at or similar) of a specific item.
const item & used_weapon () const
Returns a reference to the item which will be used to make attacks.
item & used_weapon ()
int i_add_to_container (const item &it, bool unloading)
Try to find a container/s on character containing ammo of type it.typeId() and add charges until the container is full.
item & i_add (item it, bool should_stack=true)
item i_rem (int pos)
Remove a specific item from player possession.
item i_rem (const item *it)
Remove a specific item from player possession.
void i_rem_keep_contents (int idx)
bool i_add_or_drop (item &it, int qty=1)
Sets invlet and adds to inventory if possible, drops otherwise, returns true if either succeeded.
std::bitset< std::numeric_limits< char >::max()> allocated_invlets () const
Only use for UI things.
bool has_active_item (const itype_id &id) const
Whether the player carries an active item of the given item type.
item remove_weapon ()
bool has_mission_item (int mission_id) const
void remove_mission_items (int mission_id)
int throw_range (const item &) const
Maximum thrown range with a given item, taking all active effects into account.
bool unarmed_attack () const
True if unarmed or wielding a weapon with the UNARMED_WEAPON flag.
int best_nearby_lifting_assist () const
Checks for items, tools, and vehicles with the Lifting quality near the character returning the highest quality in range.
int best_nearby_lifting_assist (const tripoint &world_pos) const
Alternate version if you need to specify a different orign point for nearby vehicle sources of lifting used for operations on distant objects (e.g.
std::vector< item * > inv_dump ()
units::mass weight_carried () const
units::volume volume_carried () const
units::mass weight_carried_reduced_by (const excluded_stacks &without) const
units::volume volume_carried_reduced_by (const excluded_stacks &without) const
units::mass weight_capacity () const override
units::volume volume_capacity () const
units::volume volume_capacity_reduced_by (const units::volume &mod, const excluded_stacks &without={}) const
bool can_pick_volume (const item &it) const
bool can_pick_volume (units::volume volume) const
bool can_pick_weight (const item &it, bool safe=true) const
bool can_pick_weight (units::mass weight, bool safe=true) const
bool can_use (const item &it, const item &context=item()) const
Checks if character stats and skills meet minimum requirements for the item.
ret_val< bool > can_wear (const item &it, bool with_equip_change=false) const
Check character capable of wearing an item.
cata::optional< std::list< item >::iterator > wear_possessed (item &to_wear, bool interactive=true)
Wear specified item.
cata::optional< std::list< item >::iterator > wear_item (const item &to_wear, bool interactive=true)
Wear a copy of specified item.
ret_val< bool > can_takeoff (const item &it, const std::list< item > *res=nullptr) const
Check if character is capable of taking off given item.
bool takeoff (item &it, std::list< item > *res=nullptr)
Take off an item.
bool is_armed () const
Returns true if the character is wielding something.
ret_val< bool > can_wield (const item &it) const
Check whether character is capable of wielding given item.
ret_val< bool > can_unwield (const item &it) const
Check whether character is capable of unwielding given item.
bool unwield ()
Removes currently wielded item (if any)
ret_val< bool > can_swap (const item &it) const
Check player capable of swapping the side of a worn item.
void drop_invalid_inventory ()
std::list< item * > get_dependent_worn_items (const item &it) const
Returns all items that must be taken off before taking off this item.
void drop (item_location loc, const tripoint &where)
Drops an item to the specified location.
virtual void drop (const drop_locations &what, const tripoint &target, bool stash=false)
virtual bool has_artifact_with (art_effect_passive effect) const
bool is_wielding (const item &target) const
bool covered_with_flag (const std::string &flag, const body_part_set &parts) const
bool is_waterproof (const body_part_set &parts) const
int leak_level (const std::string &flag) const
bool can_reload (const item &it, const itype_id &ammo=itype_id()) const
Whether a tool or gun is potentially reloadable (optionally considering a specific ammo)
int item_reload_cost (const item &it, const item &ammo, int qty) const
Calculate (but do not deduct) the number of moves required to reload an item with specified quantity of ammo.
bool is_wearing (const item &itm) const
Returns true if the player is wearing the item.
bool is_wearing (const itype_id &it) const
Returns true if the player is wearing an item of this type.
bool is_wearing_on_bp (const itype_id &it, const bodypart_id &bp) const
Returns true if the player is wearing the item on the given body part.
bool worn_with_flag (const std::string &flag, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns true if the player is wearing an item with the given flag.
const item * item_worn_with_flag (const std::string &flag, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the first worn item with a given flag.
std::vector< std::string > get_overlay_ids () const
Returns a list of the IDs of overlays on this character, sorted from "lowest" to "highest".
int get_skill_level (const skill_id &ident) const
int get_skill_level (const skill_id &ident, const item &context) const
const SkillLevelMap & get_all_skills () const
SkillLevel & get_skill_level_object (const skill_id &ident)
const SkillLevel & get_skill_level_object (const skill_id &ident) const
void set_skill_level (const skill_id &ident, int level)
void mod_skill_level (const skill_id &ident, int delta)
bool meets_skill_requirements (const std::map< skill_id, int > &req, const item &context=item()) const
Checks whether the character's skills meet the required.
bool meets_skill_requirements (const construction &con) const
Checks whether the character's skills meet the required.
bool meets_stat_requirements (const item &it) const
Checks whether the character's stats meets the stats required by the item.
bool meets_requirements (const item &it, const item &context=item()) const
Checks whether the character meets overall requirements to be able to use the item.
std::string enumerate_unmet_requirements (const item &it, const item &context=item()) const
Returns a string of missed requirements (both stats and skills)
int rust_rate () const
Returns the player's skill rust rate.
void practice (const skill_id &id, int amount, int cap=99, bool suppress_warning=false)
This handles giving xp for a skill.
int read_speed (bool return_stat_effect=true) const
Returns the player's reading speed.
time_point get_time_died () const
return the calendar::turn the character expired
void set_time_died (const time_point &time)
set the turn the turn the character died if not already done
void die (Creature *nkiller) override
Empty function.
std::string get_name () const override
std::vector< std::string > get_grammatical_genders () const override
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args) const
It is supposed to hide the query_yn to simplify player vs.
bool is_immune_field (const field_type_id &fid) const override
Returns true if we are immune to the field type with the given fid.
bool is_elec_immune () const override
Returns true is the player is protected from electric shocks.
bool is_immune_effect (const efftype_id &) const override
Returns true if the player is immune to this kind of effect.
bool is_immune_damage (damage_type) const override
Returns true if the player is immune to this kind of damage.
bool is_rad_immune () const
Returns true if the player is protected from radiation.
bool is_throw_immune () const
Returns true if the player is immune to throws.
bool has_nv ()
Returns true if the player has some form of night vision.
float rest_quality () const
Returns >0 if character is sitting/lying and relatively inactive.
float healing_rate (float at_rest_quality) const
Average hit points healed per turn.
float healing_rate_medicine (float at_rest_quality, const bodypart_id &bp) const
Average hit points healed per turn from healing effects.
float mutation_value (const std::string &val) const
Goes over all mutations, gets min and max of a value with given name.
social_modifiers get_mutation_social_mods () const
Goes over all mutations, returning the sum of the social modifiers.
nc_color basic_symbol_color () const override
nc_color symbol_color () const override
std::string extended_description () const override
void pick_name (bool bUseDefault=false)
Returns a random name from NAMES_*.
std::vector< trait_id > get_base_traits () const
Get the idents of all base traits.
std::vector< trait_id > get_mutations (bool include_hidden=true) const
Get the idents of all traits/mutations.
const std::bitset< NUM_VISION_MODES > & get_vision_modes () const
void clear_skills ()
Clear the skills map, setting all levels to 0.
void clear_mutations ()
Empties the trait and mutations lists.
bool crossed_threshold () const
Returns true if the player has crossed a mutation threshold Player can only cross one mutation threshold.
void add_addiction (add_type type, int strength)
Adds an addiction to the player.
void rem_addiction (add_type type)
Removes an addition from the player.
bool has_addiction (add_type type) const
Returns true if the player has an addiction of the specified type.
int addiction_level (add_type type) const
Returns the intensity of the specified addiction.
void start_hauling ()
void stop_hauling ()
bool is_hauling () const
bool has_item_with_flag (const std::string &flag, bool need_charges=false) const
std::vector< const item * > all_items_with_flag (const std::string &flag) const
All items that have the given flag (item::has_flag).
bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
std::list< item > use_amount (itype_id it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >)
bool use_charges_if_avail (const itype_id &it, int quantity)
std::list< item > use_charges (const itype_id &what, int qty, const std::function< bool(const item &)> &filter=return_true< item >)
bool has_fire (int quantity) const
void use_fire (int quantity)
void assign_stashed_activity ()
bool check_outbounds_activity (const player_activity &act, bool check_only=false)
void assign_activity (const activity_id &type, int moves=calendar::INDEFINITELY_LONG, int index=-1, int pos=INT_MIN, const std::string &name="")
Legacy activity assignment, does not work for any activites using the new activity_actor class and may cause issues with resuming.
void assign_activity (const player_activity &act, bool allow_resume=true)
Assigns activity to player, possibly resuming old activity if it's similar enough.
bool has_activity (const activity_id &type) const
Check if player currently has a given activity.
bool has_activity (const std::vector< activity_id > &types) const
Check if player currently has any of the given activities.
void resume_backlog_activity ()
void cancel_activity ()
void cancel_stashed_activity ()
player_activity get_stashed_activity () const
void set_stashed_activity (const player_activity &act, const player_activity &act_back=player_activity())
bool has_stashed_activity () const
void initialize_stomach_contents ()
float metabolic_rate_base () const
Stable base metabolic rate due to traits.
float metabolic_rate () const
Current metabolic rate due to traits, hunger, speed, etc.
std::string get_weight_string () const
int get_max_healthy () const
float bmi () const
int bmr () const
void reset_chargen_attributes ()
int base_age () const
void set_base_age (int age)
void mod_base_age (int mod)
int age () const
std::string age_string () const
int base_height () const
void set_base_height (int height)
void mod_base_height (int mod)
std::string height_string () const
int height () const
units::mass bodyweight () const
units::mass bionics_weight () const
int get_armor_bash (bodypart_id bp) const override
Returns overall bashing resistance for the body_part.
int get_armor_cut (bodypart_id bp) const override
Returns overall cutting resistance for the body_part.
int get_armor_bullet (bodypart_id bp) const override
Returns overall bullet resistance for the body_part.
int get_armor_bash_base (bodypart_id bp) const override
Returns bashing resistance from the creature and armor only.
int get_armor_cut_base (bodypart_id bp) const override
Returns cutting resistance from the creature and armor only.
int get_armor_bullet_base (bodypart_id bp) const override
Returns cutting resistance from the creature and armor only.
int get_env_resist (bodypart_id bp) const override
Returns overall env_resist on a body_part.
int get_armor_acid (bodypart_id bp) const
Returns overall acid resistance for the body part.
int get_armor_type (damage_type dt, bodypart_id bp) const override
Returns overall resistance to given type on the bod part.
std::map< bodypart_id, int > get_all_armor_type (damage_type dt, const std::map< bodypart_id, std::vector< const item * > > &clothing_map) const
int get_stim () const
void set_stim (int new_stim)
void mod_stim (int mod)
int get_rad () const
void set_rad (int new_rad)
void mod_rad (int mod)
int get_stamina () const
int get_stamina_max () const
void set_stamina (int new_stamina)
void mod_stamina (int mod)
void burn_move_stamina (int moves)
float stamina_move_cost_modifier () const
void update_stamina (int turns)
Regenerates stamina.
void on_item_wear (const item &it)
Called when an item is worn.
void on_item_takeoff (const item &it)
Called when an item is taken off.
void on_worn_item_washed (const item &it)
Called when an item is washed.
void on_effect_int_change (const efftype_id &effect_type, int intensity, const bodypart_str_id &bp) override
Called when effect intensity has been changed.
void on_mutation_gain (const trait_id &mid)
Called when a mutation is gained.
void on_mutation_loss (const trait_id &mid)
Called when a mutation is lost.
void on_stat_change (const std::string &stat, int value) override
Called when a stat is changed.
void on_worn_item_transform (const item &old_it, const item &new_it)
Called when a worn item is transformed.
void wake_up ()
Removes "sleep" and "lying_down".
int get_shout_volume () const
void shout (std::string msg="", bool order=false)
void vomit ()
Handles Character vomiting effects.
void healed_bp (int bp, int amount)
int adjust_for_focus (int amount) const
void update_type_of_scent (bool init=false)
void update_type_of_scent (const trait_id &mut, bool gain=true)
void set_type_of_scent (const scenttype_id &id)
scenttype_id get_type_of_scent () const
void restore_scent ()
restore scent after masked_scent effect run out or is removed by water
void mod_painkiller (int npkill)
Modifies intensity of painkillers
void set_painkiller (int npkill)
Sets intensity of painkillers
int get_painkiller () const
Returns intensity of painkillers
void react_to_felt_pain (int intensity)
void mod_pain (int npain) override
Modifies a pain value by player traits before passing it to Creature::mod_pain()
void set_pain (int npain) override
Sets new intensity of pain an reacts to it.
int get_perceived_pain () const override
Returns perceived pain (reduced with painkillers)
void spores ()
void blossoms ()
void rooted_message () const
Handles rooting effects.
void rooted ()
void fall_asleep ()
Adds "sleep" to the player.
void fall_asleep (const time_duration &duration)
std::string is_snuggling () const
Checks to see if the player is using floor items to keep warm, and return the name of one such item if so.
float power_rating () const override
Returns an approximation of the creature's strength.
float speed_rating () const override
Returns an approximate number of tiles this creature can travel per turn.
item & item_with_best_of_quality (const quality_id &qid)
Returns the item in the player's inventory with the highest of the specified quality.
bool sees_with_infrared (const Creature &critter) const
Check whether the this player can see the other creature with infrared.
void place_corpse ()
void place_corpse (const tripoint_abs_omt &om_target)
int run_cost (int base_cost, bool diag=false) const
Returns the player's modified base movement cost.
const pathfinding_settings & get_pathfinding_settings () const override
Returns settings for pathfinding.
std::set< tripoint > get_path_avoid () const override
Returns a set of points we do not want to path through.
std::vector< Creature * > get_hostile_creatures (int range) const
Get all hostile creatures currently visible to this player.
std::vector< Creature * > get_visible_creatures (int range) const
Returns all creatures that this player can see and that are in the given range.
std::string visible_mutations (int visibility_cap) const
Returns an enumeration of visible mutations with colors.
player_activity get_destination_activity () const
void set_destination_activity (const player_activity &new_destination_activity)
void clear_destination_activity ()
std::map< bodypart_id, int > warmth (const std::map< bodypart_id, std::vector< const item * > > &clothing_map) const
Returns warmth provided by armor, etc.
bool can_use_floor_warmth () const
Can the player lie down and cover self with blankets etc.
int floor_warmth (const tripoint &pos) const
Final warmth from the floor.
int bodytemp_modifier_traits (bool overheated) const
Correction factor of the body temperature due to traits and mutations.
int bodytemp_modifier_traits_floor () const
Correction factor of the body temperature due to traits and mutations for player lying on the floor.
int temp_corrected_by_climate_control (int temperature) const
Value of the body temperature corrected by climate control.
bool in_sleep_state () const override
void update_vitamins (const vitamin_id &vit)
Set vitamin deficiency/excess disease states dependent upon current vitamin levels.
int vitamin_get (const vitamin_id &vit) const
Check current level of a vitamin.
bool vitamin_set (const vitamin_id &vit, int qty)
Sets level of a vitamin or returns false if id given in vit does not exist.
int vitamin_mod (const vitamin_id &vit, int qty, bool capped=true)
Add or subtract vitamins from character storage pools.
void vitamins_mod (const std::map< vitamin_id, int > &, bool capped=true)
time_duration vitamin_rate (const vitamin_id &vit) const
Get vitamin usage rate (minutes per unit) accounting for bionics, mutations and effects.
int nutrition_for (const item &comest) const
Handles the nutrition value for a comestible.
ret_val< edible_rating > can_eat (const item &food) const
Can the food be [theoretically] eaten no matter the consequen ces?
ret_val< edible_rating > will_eat (const item &food, bool interactive=false) const
Same as can_eat, but takes consequences into account.
bool can_feed_reactor_with (const item &it) const
Determine character's capability of recharging their CBMs.
bool can_feed_furnace_with (const item &it) const
rechargeable_cbm get_cbm_rechargeable_with (const item &it) const
int get_acquirable_energy (const item &it, rechargeable_cbm cbm) const
int get_acquirable_energy (const item &it) const
bool feed_reactor_with (item &it)
Recharge CBMs whenever possible.
bool feed_furnace_with (item &it)
bool fuel_bionic_with (item &it)
void modify_stimulation (const islot_comestible &comest)
Used to apply stimulation modifications from food and medication.
void modify_fatigue (const islot_comestible &comest)
Used to apply fatigue modifications from food and medication.
void modify_radiation (const islot_comestible &comest)
Used to apply radiation from food and medication.
void modify_addiction (const islot_comestible &comest)
Used to apply addiction modifications from food and medication.
void modify_health (const islot_comestible &comest)
Used to apply health modifications from food and medication.
bool consume_effects (item &food)
Handles the effects of consuming an item.
bool can_consume (const item &it) const
Check character's capability of consumption overall.
bool can_estimate_rot () const
True if the character has enough skill (in cooking or survival) to estimate time to rot.
bool can_consume_as_is (const item &it) const
Check whether character can consume this very item.
bool can_consume_for_bionic (const item &it) const
item & get_consumable_from (item &it) const
Returns a reference to the item itself (if it's consumable), the first of its contents (if it's consumable) or null item otherwise.
void consume (item_location loc)
Consume item (food, fuel, medicine, ...) at given location loc .
bool consume_item (item &target)
Consume given item (food, fuel, medicine, ...).
bool consume_med (item &target)
Consume an item as medication.
bool eat (item &food, bool force=false)
Used for eating entered comestible, returns true if comestible is successfully eaten.
std::pair< nutrients, nutrients > compute_nutrient_range (const item &, const recipe_id &, const cata::flat_set< std::string > &extra_flags={}) const
Get calorie & vitamin contents for a comestible, taking into account character traits.
std::pair< nutrients, nutrients > compute_nutrient_range (const itype_id &, const cata::flat_set< std::string > &extra_flags={}) const
Same, but across arbitrary recipes.
morale_type allergy_type (const item &food) const
Returns allergy type or MORALE_NULL if not allergic for this character.
nutrients compute_effective_nutrients (const item &) const
bool wearing_something_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body part.
bool is_wearing_helmet () const
Returns true if the character is wearing something occupying the helmet slot.
int head_cloth_encumbrance () const
Returns the total encumbrance of all SKINTIGHT and HELMET_COMPAT items coveringi the head.
double armwear_factor () const
Same as footwear factor, but for arms.
int shoe_type_count (const itype_id &it) const
Returns 1 if the player is wearing an item of that count on one foot, 2 if on both, and zero if on neither.
double footwear_factor () const
Returns 1 if the player is wearing something on both feet, .5 if on one, and 0 if on neither.
bool is_wearing_shoes (const side &which_side=side::BOTH) const
Returns true if the player is wearing something on their feet that is not SKINTIGHT.
bool change_side (item &it, bool interactive=true)
Swap side on which item is worn; returns false on fail.
bool change_side (item_location &loc, bool interactive=true)
bool get_check_encumbrance ()
void set_check_encumbrance (bool new_check)
void update_morale ()
Ticks down morale counters and removes them.
void apply_persistent_morale ()
Ensures persistent morale effects are up-to-date.
void modify_morale (item &food, int nutr=0)
Used to apply morale modifications from food and medication.
int get_morale_level () const
void add_morale (const morale_type &type, int bonus, int max_bonus=0, const time_duration &duration=1_hours, const time_duration &decay_start=30_minutes, bool capped=false, const itype *item_type=nullptr)
bool has_morale (const morale_type &type) const
int get_morale (const morale_type &type) const
void rem_morale (const morale_type &type)
void clear_morale ()
bool has_morale_to_read () const
bool has_morale_to_craft () const
const inventory & crafting_inventory (bool clear_path)
const inventory & crafting_inventory (const tripoint &src_pos=tripoint_zero, int radius=PICKUP_RANGE, bool clear_path=true)
void invalidate_crafting_inventory ()
const recipe_subset & get_learned_recipes () const
Returns all known recipes.
bool knows_recipe (const recipe *rec) const
void learn_recipe (const recipe *rec)
bool can_learn_by_disassembly (const recipe &rec) const
bool check_and_recover_morale ()
Checks permanent morale for consistency and recovers it when an inconsistency is found.
std::pair< int, int > fun_for (const item &comest) const
Handles the enjoyability value for a comestible.
void suffer ()
Handles a large number of timers decrementing and other randomized effects.
bool irradiate (float rads, bool bypass=false)
Handles mitigation and application of radiation.
void mend (int rate_multiplier)
Handles the chance for broken limbs to spontaneously heal to 1 HP.
void sound_hallu ()
Creates an auditory hallucination.
void drench (int saturation, const body_part_set &flags, bool ignore_waterproof)
Drenches the player with water, saturation is the percent gotten wet.
void apply_wetness_morale (int temperature)
Recalculates morale penalty/bonus from wetness based on mutations, equipment and temperature.
std::vector< std::string > short_description_parts () const
std::string short_description () const
int print_info (const catacurses::window &w, int vStart, int vLines, int column) const override
Write information about this creature.
bool can_hear (const tripoint &source, int volume) const
float hearing_ability () const
bool knows_trap (const tripoint &pos) const
void add_known_trap (const tripoint &pos, const trap &t)
bool avoid_trap (const tripoint &pos, const trap &tr) const override
Called when character triggers a trap, returns true if they don't set it off.
nc_color bodytemp_color (int bp) const
Define color for displaying the body temperature.
bool sees (const tripoint &t, bool is_player=false, int range_mod=0) const override
bool sees (const Creature &critter) const override
The functions check whether this creature can see the target.
Attitude attitude_to (const Creature &other) const override
Attitude (of this creature) towards another creature.
int get_lowest_hp () const
bool has_weapon () const override
void shift_destination (const point &shift)
void set_destination (const std::vector< tripoint > &route, const player_activity &new_destination_activity=player_activity())
void clear_destination ()
bool has_distant_destination () const
bool is_auto_moving () const
bool has_destination () const
bool has_destination_activity () const
void start_destination_activity ()
std::vector< tripoint > & get_auto_move_route ()
action_id get_next_auto_move_direction ()
bool defer_move (const tripoint &next)
std::map< bodypart_id, float > bodypart_exposure ()
Map body parts to their total exposure, from 0.0 (fully covered) to 1.0 (buck naked).
void set_underwater (bool x) override
void clear_npc_ai_info_cache (const std::string &key) const
void set_npc_ai_info_cache (const std::string &key, double val) const
cata::optional< double > get_npc_ai_info_cache (const std::string &key) const
safe_reference< Character > get_safe_reference ()
bool pour_into (item &container, item &liquid)
Try to pour the given liquid into the given container/vehicle.
bool pour_into (vehicle &veh, item &liquid)
Public Member Functions inherited from Creature
virtual ~Creature ()
virtual bool is_monster () const
virtual monster * as_monster ()
virtual const monster * as_monster () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
virtual void bleed () const
Adds an appropriate blood splatter.
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
void knock_back_from (const tripoint &p)
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, const damage_instance &dam, dealt_damage_instance &dealt_dam)
virtual void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack)
Attempts to harm a creature with a projectile.
virtual void deal_damage_handle_type (const damage_unit &du, bodypart_id bp, int &damage, int &pain)
virtual bool digging () const
virtual bool is_underwater () const
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
virtual void add_effect (const efftype_id &eff_id, const time_duration &dur, const bodypart_str_id &bp, int intensity=0, bool force=false, bool deferred=false)
Adds or modifies an effect.
void add_effect (const efftype_id &eff_id, const time_duration &dur, body_part bp=num_bp, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp=num_bp, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, body_part vector, int strength, const time_duration &dur, body_part bp, bool REMOVED, int intensity=1, bool force=false)=delete
bool remove_effect (const efftype_id &eff_id, body_part bp=num_bp)
Removes a listed effect.
virtual bool remove_effect (const efftype_id &eff_id, const bodypart_str_id &bp)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id, const bodypart_str_id &bp) const
bool has_effect_with_flag (const std::string &flag, body_part bp=num_bp) const
Check if creature has any effect with the given flag.
const effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, body_part bp=num_bp)
std::vector< const effect * > get_all_effects_of_type (const efftype_id &eff_id) const
Returns pointers to all effects matching given type.
time_duration get_effect_dur (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, body_part bp=num_bp) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
void process_effects ()
Processes through all the effects on the Creature.
virtual void mod_pain_noresist (int npain)
virtual int get_pain () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_armor_bash_bonus () const
virtual int get_armor_cut_bonus () const
virtual int get_armor_bullet_bonus () const
virtual float get_hit () const
virtual int get_hp (const bodypart_id &bp) const
virtual int get_hp () const
virtual int get_hp_max (const bodypart_id &bp) const
virtual int get_hp_max () const
virtual bool has_flag (const m_flag) const
anatomy_id get_anatomy () const
void set_anatomy (anatomy_id anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (bool only_main=false) const
Returns body parts this creature have.
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bodypart * get_part (const bodypart_id &id)
bodypart get_part (const bodypart_id &id) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
void set_part_hp_cur (const bodypart_id &id, int set)
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void mod_part_hp_cur (const bodypart_id &id, int mod)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_bash_bonus (int nbasharm)
virtual void set_armor_cut_bonus (int ncutarm)
virtual void set_armor_bullet_bonus (int nbulletarm)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
void draw (const catacurses::window &w, const point &origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
virtual bool is_symbol_highlighted () const
effects_map get_all_effects () const
body_part select_body_part (Creature *source, int hit_roll) const
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
Public Member Functions inherited from visitable< Character >
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
Traverses this object and any child items contained using a visitor pattern.
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
Lightweight version which provides only the current node.
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
item * find_parent (const item &it)
Determine the immediate parent container (if any) for an item.
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
Returns vector of parent containers (if any) starting with the innermost.
std::vector< const item * > parents (const item &it) const
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, std::function< void(int)> visitor=nullptr) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX)
Removes items contained by this instance which match the filter.
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Attributes
pimpl< teleporter_list > translocators
bool dialogue_by_radio = false
std::string preferred_aiming_mode
Public Attributes inherited from player
tripoint view_offset
tripoint grab_point
int volume = 0
bool random_start_location = false
start_location_id start_location
weak_ptr_fast< Creature > last_target
cata::optional< tripoint > last_target_pos
item_location ammo_location
int scent = 0
int cash = 0
int movecounter = 0
bool manual_examine = false
vproto_id starting_vehicle
std::vector< mtype_id > starting_pets
pimpl< craft_command > last_craft
recipe_id lastrecipe
int last_batch = 0
itype_id lastconsumed
std::set< character_id > follower_ids
Public Attributes inherited from Character
bool death_drops = true
bool controlling_vehicle = false
int str_max = 0
int dex_max = 0
int int_max = 0
int per_max = 0
int str_cur = 0
int dex_cur = 0
int int_cur = 0
int per_cur = 0
int blocks_left = 0
int dodges_left = 0
double recoil = MAX_RECOIL
profession_id prof
std::string custom_profession
bool reach_attacking = false
pimpl< known_magic > magic
std::string name
bool male = true
std::list< item > worn
std::array< int, num_hp_parts > damage_bandaged
std::array< int, num_hp_parts > damage_disinfected
bool nv_cached = false
bool in_vehicle = false
bool hauling = false
player_activity stashed_outbounds_activity
player_activity stashed_outbounds_backlog
player_activity activity
std::list< player_activity > backlog
cata::optional< tripoint > destination_point
inventory inv
itype_id last_item
item weapon
int scent = 0
pimpl< bionic_collection > my_bionics
pimpl< character_martial_arts > martial_arts_data
stomach_contents stomach
pimpl< consumption_history_t > consumption_history
int oxygen = 0
int tank_plut = 0
int reactor_plut = 0
int slow_rad = 0
int focus_pool = 0
int cash = 0
std::set< character_id > follower_ids
weak_ptr_fast< Creature > last_target
cata::optional< tripoint > last_target_pos
item_location ammo_location
std::set< tripoint_abs_omt > camps
time_point cached_time
std::vector< addiction > addictions
shared_ptr_fast< monster > mounted_creature
int mounted_creature_id = 0
int activity_vehicle_part_index = -1
std::array< int, num_hp_parts > healed_total
std::map< std::string, int > mutation_category_level
std::vector< tripoint_abs_omt > omt_path
Route for overmap scale traveling.
mutation_collection my_mutations
Traits / mutations of the character.
time_point last_sleep_check = calendar::turn_zero
bool bio_soporific_powered_at_last_sleep_check = false
std::array< int, num_bp > temp_cur
std::array< int, num_bp > frostbite_timer
std::array< int, num_bp > temp_conv
std::array< int, num_bp > body_wetness
std::array< int, num_bp > drench_capacity
time_point next_climate_control_check
bool last_climate_control_ret = false
Public Attributes inherited from Creature
FacingDirection facing = FD_RIGHT
return the direction the creature is facing, for sdl horizontal flip
int moves = 0
Private Attributes
std::unique_ptr< map_memory > player_map_memory
bool show_map_memory = true
std::vector< mission * > active_missions
Missions that the player has accepted and that are not finished (one way or the other).
std::unique_ptr< diary > a_diary
Diary to track player progression and to write the player's story.
std::vector< mission * > completed_missions
Missions that the player has successfully completed.
std::vector< mission * > failed_missions
Missions that have failed while being assigned to the player.
mission * active_mission = nullptr
The currently active mission, or null if no mission is currently in progress.
std::unordered_set< itype_id > items_identified
object_type grab_type = OBJECT_NONE
int str_upgrade = 0
int dex_upgrade = 0
int int_upgrade = 0
int per_upgrade = 0
monster_visible_info mon_visible
std::map< faction_id, std::pair< int, time_point > > warning_record
Warnings from factions about bad behavior.
Friends
class debug_menu::mission_debug
Additional Inherited Members
Public Types inherited from Character
enum water_tolerance { WT_IGNORED = 0 , WT_NEUTRAL , WT_GOOD , NUM_WATER_TOLERANCE }
using trap_map = std::map< tripoint, std::string >
Public Types inherited from Creature
enum Attitude : int { A_HOSTILE , A_NEUTRAL , A_FRIENDLY , A_ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Static Public Member Functions inherited from Character
static hp_part bp_to_hp (body_part bp)
Converts a body_part to an hp_part.
static body_part hp_to_bp (hp_part hpart)
Converts an hp_part to a body_part.
static int worn_position_to_index (int position)
static int floor_bedding_warmth (const tripoint &pos)
Warmth from terrain, furniture, vehicle furniture and traps.
static int floor_item_warmth (const tripoint &pos)
Warmth from clothing on the floor.
Static Public Member Functions inherited from Creature
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
static void reset_hit_range ()
Static Public Attributes inherited from Character
static const std::vector< material_id > fleshy = { material_id("flesh"), material_id("hflesh") }
Static Public Attributes inherited from Creature
static const std::map< std::string, m_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit = default_dispersion_for_ecogh
Protected Member Functions inherited from player
void store (JsonOut &json) const
Gather variables for saving.
void load (const JsonObject &data)
Load variables from json into object.
Protected Member Functions inherited from Character
void do_skill_rust ()
void apply_mods (const trait_id &mut, bool add_remove)
Applies stat mods to character.
char_encumbrance_data calc_encumbrance () const
Recalculate encumbrance for all body parts.
char_encumbrance_data calc_encumbrance (const item &new_item) const
Recalculate encumbrance for all body parts as if new_item was also worn.
void mut_cbm_encumb (char_encumbrance_data &vals) const
Applies encumbrance from mutations and bionics only.
std::list< item >::iterator position_to_wear_new_item (const item &new_item)
Return the position in the worn list where new_item would be put by default.
void item_encumb (char_encumbrance_data &vals, const item &new_item) const
Applies encumbrance from items only If new_item is not null, then calculate under the asumption that it is added to existing work items.
void on_damage_of_type (int adjusted_damage, damage_type type, const bodypart_id &bp) override
Character ()
Character (Character &&)
Character & operator= (Character &&)
void store (JsonOut &json) const
Load variables from json into object.
void load (const JsonObject &data)
Gather variables for saving.
Protected Member Functions inherited from Creature
void set_killer (Creature *killer)
Creature ()
Creature (const Creature &)=default
Creature (Creature &&)=default
Creature & operator= (const Creature &)=default
Creature & operator= (Creature &&)=default
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Protected Attributes inherited from Character
std::array< std::array< int, NUM_WATER_TOLERANCE >, num_bp > mut_drench
tripoint position
int str_bonus = 0
Bonuses to stats, calculated each turn.
int dex_bonus = 0
int per_bonus = 0
int int_bonus = 0
int healthy = 0
How healthy the character is.
int healthy_mod = 0
int init_age = 25
age in years at character creation
int init_height = 175
height at character creation
m_size size_class = MS_MEDIUM
Size class of character.
trap_map known_traps
pimpl< char_encumbrance_data > encumbrance_cache
std::unordered_set< trait_id > my_traits
Contains mutation ids of the base traits.
std::vector< const mutation_branch * > cached_mutations
Pointers to mutation branches in my_mutations.
pimpl< SkillLevelMap > _skills
Character skills.
pimpl< SkillLevelMap > autolearn_skills_stamp
Stamp of character skills.
pimpl< recipe_subset > learned_recipes
Subset of learned recipes.
std::bitset< NUM_VISION_MODES > vision_mode_cache
float nv_range = 0
int sight_max = 0
time_point time_died = calendar::before_time_starts
pimpl< pathfinding_settings > path_settings
Cache for pathfinding settings.
int faction_api_version = 2
faction_id fac_id
faction * my_fac = nullptr
character_movemode move_mode = CMM_WALK
std::map< vitamin_id, int > vitamin_levels
Current deficiency/excess quantity for each vitamin.
pimpl< player_morale > morale
pimpl< enchantment > enchantment_cache
std::unordered_map< point_abs_omt, time_duration > overmap_time
Amount of time the player has spent in each overmap tile.
Protected Attributes inherited from Creature
Creature * killer = nullptr
pimpl< effects_map > effects
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
int armor_bash_bonus = 0
int armor_cut_bonus = 0
int armor_bullet_bonus = 0
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0
int block_bonus = 0
float hit_bonus = 0.0
bool fake = false
Related Functions inherited from player
bool operator() (const profession_id &a, const profession_id &b)
bool operator() (const scenario *a, const scenario *b)
Related Functions inherited from visitable< Character >
VisitResponse visit_items (const std::function< VisitResponse(const item *, const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(const item *)> &func) const
VisitResponse visit_items (const std::function< VisitResponse(item *)> &func)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func)
item * find_parent (const item &it)
const item * find_parent (const item &it) const
std::vector< item * > parents (const item &it)
std::vector< const item * > parents (const item &it) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
Detailed Description
Definition at line 54 of file avatar.h.
Constructor & Destructor Documentation
avatar() [1/3]
avatar::avatar ()
Definition at line 109 of file avatar.cpp.
{
    player_map_memory = std::make_unique<map_memory>();
    show_map_memory = true;
    active_mission = nullptr;
    grab_type = OBJECT_NONE;
    a_diary = nullptr;
}
References a_diary, active_mission, grab_type, OBJECT_NONE, player_map_memory, and show_map_memory.
Referenced by randomize().
avatar() [2/3]
avatar::avatar (const avatar &) delete
avatar() [3/3]
avatar::avatar (avatar &&) default
~avatar()
avatar::~avatar () override default
Member Function Documentation
add_faction_warning()
bool avatar::add_faction_warning (const faction_id & id)
Add warning from faction.
Returns
true if the warning is now beyond final and results in hostility
Definition at line 1309 of file avatar.cpp.
{
    const auto it = warning_record.find( id );
    if( it != warning_record.end() ) {
        it->second.first += 1;
        if( it->second.second - calendar::turn > 5_minutes ) {
            it->second.first -= 1;
        }
        it->second.second = calendar::turn;
        if( it->second.first > 3 ) {
            return true;
        }
    } else {
        warning_record[id] = std::make_pair( 1, calendar::turn );
    }
    faction *fac = g->faction_manager_ptr->get( id );
    if( fac != nullptr && is_player() && fac->id != faction_id( "no_faction" ) ) {
        fac->likes_u -= 1;
        fac->respects_u -= 1;
    }
    return false;
}
References g, Character::id, faction_template::id, player::is_player(), faction_template::likes_u, faction_template::respects_u, calendar::turn, and warning_record.
Referenced by avatar_funcs::handle_theft_witnesses().
as_avatar() [1/2]
const avatar * avatar::as_avatar () const inline override virtual
Reimplemented from Creature.
Definition at line 83 of file avatar.h.
{
            return this;
        }
as_avatar() [2/2]
avatar * avatar::as_avatar () inline override virtual
Reimplemented from Creature.
Definition at line 80 of file avatar.h.
{
            return this;
        }
clear_memorized_tile()
void avatar::clear_memorized_tile (const tripoint & pos)
Definition at line 168 of file avatar.cpp.
{
    player_map_memory->clear_memorized_tile( pos );
}
References player_map_memory, and Character::pos().
Referenced by game::control_vehicle().
create()
bool avatar::create (character_type type, const std::string & tempname = "")
Definition at line 400 of file newcharacter.cpp.
{
    weapon = item( "null", calendar::start_of_cataclysm );
    prof = profession::generic();
    g->scen = scenario::generic();
    const bool interactive = type != character_type::NOW &&
                             type != character_type::FULL_RANDOM;
    int tab = 0;
    points_left points = points_left();
    switch( type ) {
        case character_type::CUSTOM:
            break;
        case character_type::RANDOM:
            //random scenario, default name if exist
            randomize( true, points );
            tab = NEWCHAR_TAB_MAX;
            break;
        case character_type::NOW:
            //default world, fixed scenario, random name
            randomize( false, points, true );
            break;
        case character_type::FULL_RANDOM:
            //default world, random scenario, random name
            randomize( true, points, true );
            break;
        case character_type::TEMPLATE:
            if( !load_template( tempname, points ) ) {
                return false;
            }
            // We want to prevent recipes known by the template from being applied to the
            // new character. The recipe list will be rebuilt when entering the game.
            // Except if it is a character transfer template
            if( points.limit != points_left::TRANSFER ) {
                learned_recipes->clear();
            }
            tab = NEWCHAR_TAB_MAX;
            break;
    }
    auto nameExists = [&]( const std::string & name ) {
        return world_generator->active_world->save_exists( save_t::from_player_name( name ) ) &&
               !query_yn( _( "A character with the name '%s' already exists in this world.\n"
                             "Saving will override the already existing character.\n\n"
                             "Continue anyways?" ), name );
    };
    set_body();
    const bool allow_reroll = type == character_type::RANDOM;
    tab_direction result = tab_direction::QUIT;
    do {
        if( !interactive ) {
            // no window is created because "Play now"  does not require any configuration
            if( nameExists( name ) ) {
                return false;
            }
            break;
        }
        if( points.limit == points_left::TRANSFER ) {
            tab = 6;
        }
        switch( tab ) {
            case 0:
                result = set_points( *this, points );
                break;
            case 1:
                result = set_scenario( *this, points, result );
                break;
            case 2:
                result = set_profession( *this, points, result );
                break;
            case 3:
                result = set_stats( *this, points );
                break;
            case 4:
                result = set_traits( *this, points );
                break;
            case 5:
                result = set_skills( *this, points );
                break;
            case 6:
                result = set_description( *this, allow_reroll, points );
                break;
        }
        switch( result ) {
            case tab_direction::NONE:
                break;
            case tab_direction::FORWARD:
                tab++;
                break;
            case tab_direction::BACKWARD:
                tab--;
                break;
            case tab_direction::QUIT:
                tab = -1;
                break;
        }
        if( !( tab >= 0 && tab <= NEWCHAR_TAB_MAX ) ) {
            if( tab != -1 && nameExists( name ) ) {
                tab = NEWCHAR_TAB_MAX;
            } else {
                break;
            }
        }
    } while( true );
    if( tab < 0 ) {
        return false;
    }
    if( points.limit == points_left::TRANSFER ) {
        return true;
    }
    save_template( _( "Last Character" ), points );
    recalc_hp();
    if( has_trait( trait_SMELLY ) ) {
        scent = 800;
    }
    if( has_trait( trait_WEAKSCENT ) ) {
        scent = 300;
    }
    weapon = item( "null", calendar::start_of_cataclysm );
    // Grab the skills from the profession, if there are any
    // We want to do this before the recipes
    for( const profession::StartingSkill &e : prof->skills() ) {
        mod_skill_level( e.first, e.second );
    }
    // setup staring bank money
    cash = rng( -200000, 200000 );
    if( has_trait( trait_XS ) ) {
        set_stored_kcal( 10000 );
        toggle_trait( trait_XS );
    }
    if( has_trait( trait_XXXL ) ) {
        set_stored_kcal( 125000 );
        toggle_trait( trait_XXXL );
    }
    // Learn recipes
    for( const auto &e : recipe_dict ) {
        const auto &r = e.second;
        if( !r.has_flag( flag_SECRET ) && !knows_recipe( &r ) && has_recipe_requirements( r ) ) {
            learn_recipe( &r );
        }
    }
    for( mtype_id elem : prof->pets() ) {
        starting_pets.push_back( elem );
    }
    if( g->scen->vehicle() != vproto_id::NULL_ID() ) {
        starting_vehicle = g->scen->vehicle();
    } else {
        starting_vehicle = prof->vehicle();
    }
    std::list<item> prof_items = prof->items( male, get_mutations() );
    for( item &it : prof_items ) {
        if( it.has_flag( flag_WET ) ) {
            it.active = true;
            it.item_counter = 450; // Give it some time to dry off
        }
        // TODO: debugmsg if food that isn't a seed is inedible
        if( it.has_flag( "no_auto_equip" ) ) {
            it.unset_flag( "no_auto_equip" );
            inv.push_back( it );
        } else if( it.has_flag( "auto_wield" ) ) {
            it.unset_flag( "auto_wield" );
            if( !is_armed() ) {
                wield( it );
            } else {
                inv.push_back( it );
            }
        } else if( it.is_armor() ) {
            // TODO: debugmsg if wearing fails
            wear_item( it, false );
        } else {
            inv.push_back( it );
        }
        if( it.is_book() ) {
            items_identified.insert( it.typeId() );
        }
    }
    std::vector<addiction> prof_addictions = prof->addictions();
    for( std::vector<addiction>::const_iterator iter = prof_addictions.begin();
         iter != prof_addictions.end(); ++iter ) {
        addictions.push_back( *iter );
    }
    for( const bionic_id &bio : prof->CBMs() ) {
        add_bionic( bio );
    }
    // Adjust current energy level to maximum
    set_power_level( get_max_power_level() );
    for( const trait_id &t : get_base_traits() ) {
        std::vector<matype_id> styles;
        for( const matype_id &s : t->initial_ma_styles ) {
            if( !martial_arts_data->has_martialart( s ) ) {
                styles.push_back( s );
            }
        }
        if( !styles.empty() ) {
            const matype_id ma_type = choose_ma_style( type, styles, *this );
            martial_arts_data->add_martialart( ma_type );
            martial_arts_data->set_style( ma_type );
        }
    }
    // Activate some mutations right from the start.
    for( const trait_id &mut : get_mutations() ) {
        const auto &branch = mut.obj();
        if( branch.starts_active ) {
            my_mutations[mut].powered = true;
        }
    }
    learn_spells( *prof, *this );
    // Ensure that persistent morale effects (e.g. Optimist) are present at the start.
    apply_persistent_morale();
    return true;
}
References _, Character::add_bionic(), Character::addictions, profession::addictions(), Character::apply_persistent_morale(), BACKWARD, player::cash, profession::CBMs(), choose_ma_style(), CUSTOM, flag_SECRET(), flag_WET(), FORWARD, save_t::from_player_name(), FULL_RANDOM, g, profession::generic(), scenario::generic(), Character::get_base_traits(), Character::get_max_power_level(), Character::get_mutations(), player::has_recipe_requirements(), Character::has_trait(), Character::inv, Character::is_armed(), profession::items(), items_identified, Character::knows_recipe(), Character::learn_recipe(), learn_spells(), Character::learned_recipes, points_left::limit, load_template(), Character::male, Character::martial_arts_data, Character::mod_skill_level(), Character::my_mutations, Character::name, NEWCHAR_TAB_MAX, NONE, NOW, string_id< vehicle_prototype >::NULL_ID(), profession::pets(), Character::prof, inventory::push_back(), player::query_yn(), QUIT, RANDOM, randomize(), Character::recalc_hp(), recipe_dict, rng(), save_template(), player::scent, Creature::set_body(), set_description(), set_points(), Character::set_power_level(), set_profession(), set_scenario(), set_skills(), set_stats(), Character::set_stored_kcal(), set_traits(), profession::skills(), calendar::start_of_cataclysm, player::starting_pets, player::starting_vehicle, TEMPLATE, Character::toggle_trait(), trait_SMELLY, trait_WEAKSCENT, trait_XS, trait_XXXL, points_left::TRANSFER, type, profession::vehicle(), Character::weapon, Character::wear_item(), wield(), and world_generator.
cycle_move_mode()
void avatar::cycle_move_mode ()
Definition at line 1187 of file avatar.cpp.
{
    unsigned char as_uchar = static_cast<unsigned char>( move_mode );
    as_uchar = ( as_uchar + 1 + CMM_COUNT ) % CMM_COUNT;
    set_movement_mode( static_cast<character_movemode>( as_uchar ) );
    // if a movemode is disabled then just cycle to the next one
    if( !movement_mode_is( static_cast<character_movemode>( as_uchar ) ) ) {
        as_uchar = ( as_uchar + 1 + CMM_COUNT ) % CMM_COUNT;
        set_movement_mode( static_cast<character_movemode>( as_uchar ) );
    }
}
References CMM_COUNT, Character::move_mode, Character::movement_mode_is(), and set_movement_mode().
Referenced by game::handle_action(), and open_movement_mode_menu().
deserialize()
void avatar::deserialize (JsonIn & jsin) override virtual
Implements player.
Definition at line 1002 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    load( data );
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and load().
disp_morale()
void avatar::disp_morale ()
Provides the window and detailed morale data.
Definition at line 1001 of file avatar.cpp.
{
    int equilibrium = character_effects::calc_focus_equilibrium( *this );
    int fatigue_cap = character_effects::calc_morale_fatigue_cap( this->get_fatigue() );
    int pain_penalty = has_trait( trait_CENOBITE ) ? 0 : get_perceived_pain();
    morale->display( equilibrium, pain_penalty, fatigue_cap );
}
References character_effects::calc_focus_equilibrium(), character_effects::calc_morale_fatigue_cap(), Character::get_fatigue(), Character::get_perceived_pain(), Character::has_trait(), Character::morale, and trait_CENOBITE.
Referenced by game::handle_action().
do_read()
void avatar::do_read (item_location loc)
Completes book reading action.
Intelligence increases reading comprehension
Definition at line 742 of file avatar.cpp.
{
    if( !loc ) {
        activity.set_to_null();
        return;
    }
    item &book = *loc;
    const auto &reading = book.type->book;
    if( !reading ) {
        activity.set_to_null();
        return;
    }
    const skill_id &skill = reading->skill;
    if( !has_identified( book.typeId() ) ) {
        // Note that we've read the book.
        items_identified.insert( book.typeId() );
        skim_book_msg( book, *this );
        activity.set_to_null();
        return;
    }
    const bool allow_recipes = get_option<bool>( "ALLOW_LEARNING_BOOK_RECIPES" );
    //learners and their penalties
    std::vector<std::pair<player *, double>> learners;
    for( size_t i = 0; i < activity.values.size(); i++ ) {
        player *n = g->find_npc( character_id( activity.values[i] ) );
        if( n != nullptr ) {
            const std::string &s = activity.get_str_value( i, "1" );
            learners.push_back( { n, strtod( s.c_str(), nullptr ) } );
        }
        // Otherwise they must have died/teleported or something
    }
    learners.push_back( { this, 1.0 } );
    //whether to continue reading or not
    bool continuous = false;
    // NPCs who learned a little about the skill
    std::set<std::string> little_learned;
    std::set<std::string> cant_learn;
    std::list<std::string> out_of_chapters;
    for( auto &elem : learners ) {
        player *learner = elem.first;
        int book_fun_for = character_funcs::get_book_fun_for( *learner, book );
        if( book_fun_for != 0 ) {
            learner->add_morale( MORALE_BOOK, book_fun_for * 5, book_fun_for * 15, 1_hours, 30_minutes, true,
                                 book.type );
        }
        book.mark_chapter_as_read( *learner );
        const auto available_recipes = book.get_available_recipes( *learner );
        std::vector<const recipe *> learnable_recipes;
        for( const std::pair<const recipe *, int> &p : available_recipes ) {
            if( allow_recipes && !learner->knows_recipe( p.first ) ) {
                learnable_recipes.push_back( p.first );
                learner->learn_recipe( p.first );
                if( learner->is_player() ) {
                    add_msg( m_info, _( "You memorize a recipe for %s." ), p.first->result_name() );
                }
            }
        }
        if( skill && learner->get_skill_level( skill ) < reading->level &&
            learner->get_skill_level_object( skill ).can_train() ) {
            SkillLevel &skill_level = learner->get_skill_level_object( skill );
            const int originalSkillLevel = skill_level.level();
            // Calculate experience gained
            /** @EFFECT_INT increases reading comprehension */
            // Enhanced Memory Banks modestly boosts experience
            int min_ex = std::max( 1, reading->time / 10 + learner->get_int() / 4 );
            int max_ex = reading->time /  5 + learner->get_int() / 2 - originalSkillLevel;
            if( has_active_bionic( bio_memory ) ) {
                min_ex += 2;
            }
            min_ex = adjust_for_focus( min_ex );
            max_ex = adjust_for_focus( max_ex );
            if( max_ex < 2 ) {
                max_ex = 2;
            }
            if( max_ex > 10 ) {
                max_ex = 10;
            }
            if( max_ex < min_ex ) {
                max_ex = min_ex;
            }
            min_ex *= ( originalSkillLevel + 1 ) * elem.second;
            min_ex = std::max( min_ex, 1 );
            max_ex *= ( originalSkillLevel + 1 ) * elem.second;
            max_ex = std::max( min_ex, max_ex );
            skill_level.readBook( min_ex, max_ex, reading->level );
            std::string skill_name = skill.obj().name();
            if( skill_level != originalSkillLevel ) {
                g->events().send<event_type::gains_skill_level>(
                    learner->getID(), skill, skill_level.level() );
                if( learner->is_player() ) {
                    add_msg( m_good, _( "You increase %s to level %d." ), skill.obj().name(),
                             originalSkillLevel + 1 );
                } else {
                    add_msg( m_good, _( "%s increases their %s level." ), learner->disp_name(), skill_name );
                }
            } else {
                //skill_level == originalSkillLevel
                if( activity.index == learner->getID().get_value() ) {
                    continuous = true;
                }
                if( learner->is_player() ) {
                    add_msg( m_info, _( "You learn a little about %s!  (%d%%)" ), skill_name, skill_level.exercise() );
                } else {
                    little_learned.insert( learner->disp_name() );
                }
            }
            if( learnable_recipes.empty() && ( skill_level == reading->level || !skill_level.can_train() ) ) {
                if( learner->is_player() ) {
                    add_msg( m_info, _( "You can no longer learn from %s." ), book.type_name() );
                } else {
                    cant_learn.insert( learner->disp_name() );
                }
            }
        } else if( learnable_recipes.empty() && skill ) {
            if( learner->is_player() ) {
                add_msg( m_info, _( "You can no longer learn from %s." ), book.type_name() );
            } else {
                cant_learn.insert( learner->disp_name() );
            }
        }
    }
    //end for all learners
    if( little_learned.size() == 1 ) {
        add_msg( m_info, _( "%s learns a little about %s!" ), little_learned.begin()->c_str(),
                 skill.obj().name() );
    } else if( !little_learned.empty() ) {
        const std::string little_learned_msg = enumerate_as_string( little_learned );
        add_msg( m_info, _( "%s learn a little about %s!" ), little_learned_msg, skill.obj().name() );
    }
    if( !cant_learn.empty() ) {
        const std::string names = enumerate_as_string( cant_learn );
        add_msg( m_info, _( "%s can no longer learn from %s." ), names, book.type_name() );
    }
    if( !out_of_chapters.empty() ) {
        const std::string names = enumerate_as_string( out_of_chapters );
        add_msg( m_info, _( "Rereading the %s isn't as much fun for %s." ),
                 book.type_name(), names );
        if( out_of_chapters.front() == disp_name() && one_in( 6 ) ) {
            add_msg( m_info, _( "Maybe you should find something new to read" ) );
        }
    }
    // NPCs can't learn martial arts from manuals (yet).
    auto m = book.type->use_methods.find( "MA_MANUAL" );
    if( m != book.type->use_methods.end() ) {
        const matype_id style_to_learn = martial_art_learned_from( *book.type );
        skill_id skill_used = style_to_learn->primary_skill;
        int difficulty = std::max( 1, style_to_learn->learn_difficulty );
        difficulty = std::max( 1, 20 + difficulty * 2 - get_skill_level( skill_used ) * 2 );
        add_msg( m_debug, _( "Chance to learn one in: %d" ), difficulty );
        if( one_in( difficulty ) ) {
            m->second.call( *this, book, false, pos() );
            continuous = false;
        } else {
            if( activity.index == getID().get_value() ) {
                continuous = true;
                switch( rng( 1, 5 ) ) {
                    case 1:
                        add_msg( m_info,
                                 _( "You train the moves according to the book, but can't get a grasp of the style, so you start from the beginning." ) );
                        break;
                    case 2:
                        add_msg( m_info,
                                 _( "This martial art is not easy to grasp.  You start training the moves from the beginning." ) );
                        break;
                    case 3:
                        add_msg( m_info,
                                 _( "You decide to read the manual and train even more.  In martial arts, patience leads to mastery." ) );
                        break;
                    case 4:
                    case 5:
                        add_msg( m_info, _( "You try again.  This training will finally pay off." ) );
                        break;
                }
            } else {
                add_msg( m_info, _( "You train for a while." ) );
            }
        }
    }
    if( continuous ) {
        activity.set_to_null();
        read( loc, true );
        if( activity ) {
            return;
        }
    }
    activity.set_to_null();
}
References _, Character::activity, Character::add_morale(), add_msg(), Character::adjust_for_focus(), bio_memory, itype::book, SkillLevel::can_train(), character_id, Character::disp_name(), enumerate_as_string(), SkillLevel::exercise(), g, gains_skill_level, item::get_available_recipes(), character_funcs::get_book_fun_for(), Character::get_int(), Character::get_skill_level(), Character::get_skill_level_object(), player_activity::get_str_value(), character_id::get_value(), Creature::get_value(), Character::getID(), Character::has_active_bionic(), has_identified(), player_activity::index, player::is_player(), items_identified, Character::knows_recipe(), martialart::learn_difficulty, Character::learn_recipe(), SkillLevel::level(), m_debug, m_good, m_info, item::mark_chapter_as_read(), martial_art_learned_from(), MORALE_BOOK, Skill::name(), Name::names, string_id< T >::obj(), one_in(), Character::pos(), martialart::primary_skill, read(), SkillLevel::readBook(), rng(), player_activity::set_to_null(), skim_book_msg(), item::type, item::type_name(), item::typeId(), itype::use_methods, and player_activity::values.
free_upgrade_points()
int avatar::free_upgrade_points () const
Definition at line 1046 of file avatar.cpp.
{
    const int xp = kill_xp();
    int lvl = 0;
    for( const int &xp_lvl : xp_cutoffs ) {
        if( xp >= xp_lvl ) {
            lvl++;
        } else {
            break;
        }
    }
    return lvl - str_upgrade - dex_upgrade - int_upgrade - per_upgrade;
}
References dex_upgrade, int_upgrade, kill_xp(), per_upgrade, str_upgrade, and xp_cutoffs.
Referenced by character_display::upgrade_stat_prompt().
get_active_mission()
mission * avatar::get_active_mission () const
Returns the mission that is currently active.
Returns null if mission is active.
Definition at line 193 of file avatar.cpp.
{
    return active_mission;
}
References active_mission.
Referenced by game::list_missions().
get_active_mission_target()
tripoint_abs_omt avatar::get_active_mission_target () const
Returns the target of the active mission or overmap::invalid_tripoint if there is no active mission.
Definition at line 206 of file avatar.cpp.
{
    if( active_mission == nullptr ) {
        return overmap::invalid_tripoint;
    }
    return active_mission->get_target();
}
References active_mission, mission::get_target(), and overmap::invalid_tripoint.
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), and overmap_ui::draw_overmap_chunk().
get_active_missions()
std::vector< mission * > avatar::get_active_missions () const
Definition at line 178 of file avatar.cpp.
{
    return active_missions;
}
References active_missions.
Referenced by overmap_ui::draw_om_sidebar(), game::list_missions(), diary::new_page(), and npc::talk_to_u().
get_avatar_diary()
diary * avatar::get_avatar_diary ()
Definition at line 369 of file avatar.cpp.
{
    if( a_diary == nullptr ) {
        a_diary = std::make_unique<diary>();
    }
    return a_diary.get();
}
References a_diary.
Referenced by game::death_screen(), game::handle_action(), game::load(), and game::save_player_data().
get_book_reader()
const player * avatar::get_book_reader (const item & book, std::vector< std::string > & reasons) const
Helper function for player::read.
Parameters
book Book to read
reasons Starting with g->u, for each player/NPC who cannot read, a message will be pushed back here.
Returns
nullptr, if neither the player nor his followers can read to the player, otherwise the player/NPC who can read and can read the fastest
Definition at line 255 of file avatar.cpp.
{
    const player *reader = nullptr;
    if( !book.is_book() ) {
        reasons.push_back( string_format( _( "Your %s is not good reading material." ),
                                          book.tname() ) );
        return nullptr;
    }
    // Check for conditions that immediately disqualify the player from reading:
    const optional_vpart_position vp = get_map().veh_at( pos() );
    if( vp && vp->vehicle().player_in_control( *this ) ) {
        reasons.emplace_back( _( "It's a bad idea to read while driving!" ) );
        return nullptr;
    }
    const auto &type = book.type->book;
    if( !character_funcs::is_fun_to_read( *this, book ) && !has_morale_to_read() ) {
        // Low morale still permits skimming
        reasons.emplace_back( _( "What's the point of studying?  (Your morale is too low!)" ) );
        return nullptr;
    }
    const skill_id &skill = type->skill;
    const int skill_level = get_skill_level( skill );
    if( skill && skill_level < type->req ) {
        reasons.push_back( string_format( _( "%s %d needed to understand.  You have %d" ),
                                          skill.obj().name(), type->req, skill_level ) );
        return nullptr;
    }
    // Check for conditions that disqualify us only if no NPCs can read to us
    if( type->intel > 0 && has_trait( trait_ILLITERATE ) ) {
        reasons.emplace_back( _( "You're illiterate!" ) );
    } else if( has_trait( trait_HYPEROPIC ) && !worn_with_flag( flag_FIX_FARSIGHT ) &&
               !has_effect( effect_contacts ) && !has_bionic( bio_eye_optic ) ) {
        reasons.emplace_back( _( "Your eyes won't focus without reading glasses." ) );
    } else if( !character_funcs::can_see_fine_details( *this ) ) {
        // Too dark to read only applies if the player can read to himself
        reasons.emplace_back( _( "It's too dark to read!" ) );
        return nullptr;
    } else {
        return this;
    }
    //Check for NPCs to read for you, negates Illiterate and Far Sighted
    //The fastest-reading NPC is chosen
    if( is_deaf() ) {
        reasons.emplace_back( _( "Maybe someone could read that to you, but you're deaf!" ) );
        return nullptr;
    }
    int time_taken = INT_MAX;
    auto candidates = character_funcs::get_crafting_helpers( *this );
    for( const npc *elem : candidates ) {
        // Check for disqualifying factors:
        if( type->intel > 0 && elem->has_trait( trait_ILLITERATE ) ) {
            reasons.push_back( string_format( _( "%s is illiterate!" ),
                                              elem->disp_name() ) );
        } else if( skill && elem->get_skill_level( skill ) < type->req ) {
            reasons.push_back( string_format( _( "%s %d needed to understand.  %s has %d" ),
                                              skill.obj().name(), type->req, elem->disp_name(), elem->get_skill_level( skill ) ) );
        } else if( elem->has_trait( trait_HYPEROPIC ) && !elem->worn_with_flag( flag_FIX_FARSIGHT ) &&
                   !elem->has_effect( effect_contacts ) ) {
            reasons.push_back( string_format( _( "%s needs reading glasses!" ),
                                              elem->disp_name() ) );
        } else if( !character_funcs::fine_detail_vision_mod( *this ) &&
                   !character_funcs::fine_detail_vision_mod( *elem ) ) {
            reasons.push_back( string_format(
                                   _( "It's too dark for %s to read!" ),
                                   elem->disp_name() ) );
        } else if( !elem->sees( *this ) ) {
            reasons.push_back( string_format( _( "%s could read that to you, but they can't see you." ),
                                              elem->disp_name() ) );
        } else if( !character_funcs::is_fun_to_read( *elem, book ) && !elem->has_morale_to_read() ) {
            // Low morale still permits skimming
            reasons.push_back( string_format( _( "%s morale is too low!" ), elem->disp_name( true ) ) );
        } else if( elem->is_blind() ) {
            reasons.push_back( string_format( _( "%s is blind." ), elem->disp_name() ) );
        } else {
            int proj_time = time_to_read( book, *elem );
            if( proj_time < time_taken ) {
                reader = elem;
                time_taken = proj_time;
            }
        }
    }
    //end for all candidates
    return reader;
}
References _, bio_eye_optic, itype::book, character_funcs::can_see_fine_details(), effect_contacts, character_funcs::fine_detail_vision_mod(), flag_FIX_FARSIGHT(), character_funcs::get_crafting_helpers(), get_map(), Character::get_skill_level(), Character::has_bionic(), Creature::has_effect(), Character::has_morale_to_read(), Character::has_trait(), item::is_book(), Character::is_deaf(), character_funcs::is_fun_to_read(), Skill::name(), string_id< T >::obj(), Character::pos(), string_format(), time_to_read(), item::tname(), trait_HYPEROPIC, trait_ILLITERATE, type, item::type, map::veh_at(), and Character::worn_with_flag().
Referenced by read_inventory_preset::get_denial(), examine_item_menu::rate_action_read(), and read().
get_completed_missions()
std::vector< mission * > avatar::get_completed_missions () const
Definition at line 183 of file avatar.cpp.
{
    return completed_missions;
}
References completed_missions.
Referenced by game::list_missions(), and diary::new_page().
get_dex_base()
int avatar::get_dex_base () const override virtual
Reimplemented from Character.
Definition at line 1017 of file avatar.cpp.
{
    return Character::get_dex_base() + std::max( 0, dex_upgrade );
}
References dex_upgrade, and Character::get_dex_base().
Referenced by dex_string(), and diary::new_page().
get_faction()
faction * avatar::get_faction () const override virtual
Reimplemented from Character.
Definition at line 1092 of file avatar.cpp.
{
    return g->faction_manager_ptr->get( faction_id( "your_followers" ) );
}
References g.
Referenced by vehicle::handle_potential_theft().
get_failed_missions()
std::vector< mission * > avatar::get_failed_missions () const
Definition at line 188 of file avatar.cpp.
{
    return failed_missions;
}
References failed_missions.
Referenced by game::list_missions(), and diary::new_page().
get_grab_type()
object_type avatar::get_grab_type () const
Definition at line 672 of file avatar.cpp.
{
    return grab_type;
}
References grab_type.
Referenced by grab(), game::grabbed_move(), and game::walk_move().
get_int_base()
int avatar::get_int_base () const override virtual
Reimplemented from Character.
Definition at line 1022 of file avatar.cpp.
{
    return Character::get_int_base() + std::max( 0, int_upgrade );
}
References Character::get_int_base(), and int_upgrade.
Referenced by game::check_safe_mode_allowed(), int_string(), and diary::new_page().
get_memorized_symbol()
int avatar::get_memorized_symbol (const tripoint & p) const
Returns last stored map tile in given location in curses mode.
Definition at line 163 of file avatar.cpp.
{
    return player_map_memory->get_symbol( p );
}
References player_map_memory.
get_memorized_tile()
const memorized_terrain_tile & avatar::get_memorized_tile (const tripoint & p) const
Returns last stored map tile in given location in tiles mode.
Definition at line 147 of file avatar.cpp.
{
    return player_map_memory->get_tile( pos );
}
References player_map_memory, and Character::pos().
get_mon_visible()
monster_visible_info & avatar::get_mon_visible () inline
Definition at line 218 of file avatar.h.
{
            return mon_visible;
        }
References mon_visible.
Referenced by game::check_safe_mode_allowed(), game::handle_action(), game::mon_info(), and game::mon_info_update().
get_per_base()
int avatar::get_per_base () const override virtual
Reimplemented from Character.
Definition at line 1027 of file avatar.cpp.
{
    return Character::get_per_base() + std::max( 0, per_upgrade );
}
References Character::get_per_base(), and per_upgrade.
Referenced by diary::new_page(), and per_string().
get_str_base()
int avatar::get_str_base () const override virtual
Reimplemented from Character.
Definition at line 1012 of file avatar.cpp.
{
    return Character::get_str_base() + std::max( 0, str_upgrade );
}
References Character::get_str_base(), and str_upgrade.
Referenced by diary::new_page(), and str_string().
grab()
void avatar::grab (object_type grab_type, const tripoint & grab_point = tripoint_zero)
Definition at line 664 of file avatar.cpp.
{
    this->grab_type = grab_type;
    this->grab_point = grab_point;
    path_settings->avoid_rough_terrain = grab_type != OBJECT_NONE;
}
References player::grab_point, grab_type, OBJECT_NONE, and Character::path_settings.
Referenced by grab(), game::grabbed_furn_move(), game::grabbed_move(), game::grabbed_veh_move(), load(), game::phasing_move(), game::vertical_move(), game::vertical_shift(), and game::walk_move().
has_identified()
bool avatar::has_identified (const itype_id & item_id) const
Note that we've read a book at least once.
Definition at line 953 of file avatar.cpp.
{
    return items_identified.count( item_id ) > 0;
}
References items_identified.
Referenced by item::book_info(), do_read(), read_inventory_preset::get_denial(), examine_item_menu::rate_action_read(), read(), and item::tname().
has_memorized_tile_for_autodrive()
bool avatar::has_memorized_tile_for_autodrive (const tripoint & p) const
Returns last stored map tile in given location in tiles mode.
Definition at line 173 of file avatar.cpp.
{
    return player_map_memory->has_memory_for_autodrive( p );
}
References player_map_memory.
invoke_item() [1/8]
bool Character::invoke_item (item * used) virtual
As above two, but with position equal to current position.
Reimplemented from Character.
Definition at line 1104 of file character.cpp.
{
    return invoke_item( used, pos() );
}
invoke_item() [2/8]
bool avatar::invoke_item (item * used) override virtual
As above two, but with position equal to current position.
Reimplemented from Character.
Definition at line 1294 of file avatar.cpp.
{
    return Character::invoke_item( used );
}
References Character::invoke_item().
invoke_item() [3/8]
bool Character::invoke_item (item * used, const std::string & method) virtual
Reimplemented from Character.
Definition at line 1105 of file character.cpp.
{
    return invoke_item( used, method, pos() );
}
invoke_item() [4/8]
bool avatar::invoke_item (item * used, const std::string & method) override virtual
Reimplemented from Character.
Definition at line 1304 of file avatar.cpp.
{
    return Character::invoke_item( used, method );
}
References Character::invoke_item().
invoke_item() [5/8]
bool Character::invoke_item (item * used, const std::string & method, const tripoint & pt) virtual
As above, but with a pre-selected method.
Debugmsg if this item doesn't have this method.
Reimplemented from Character.
Definition at line 1102 of file character.cpp.
{
    if( !has_enough_charges( *used, true ) ) {
        return false;
    }
    item *actually_used = used->get_usable_item( method );
    if( actually_used == nullptr ) {
        debugmsg( "Tried to invoke a method %s on item %s, which doesn't have this method",
                  method.c_str(), used->tname() );
        return false;
    }
    int charges_used = actually_used->type->invoke( *this->as_player(), *actually_used, pt, method );
    if( charges_used == 0 ) {
        return false;
    }
    // Prevent accessing the item as it may have been deleted by the invoked iuse function.
    if( used->is_tool() || used->is_medication() || used->get_contained().is_medication() ) {
        return consume_charges( *actually_used, charges_used );
    } else if( used->is_bionic() || used->is_deployable() || method == "place_trap" ) {
        i_rem( used );
        return true;
    }
    return false;
}
invoke_item() [6/8]
bool avatar::invoke_item (item * used, const std::string & method, const tripoint & pt) override virtual
As above, but with a pre-selected method.
Debugmsg if this item doesn't have this method.
Reimplemented from Character.
Definition at line 1299 of file avatar.cpp.
{
    return Character::invoke_item( used, method, pt );
}
References Character::invoke_item().
invoke_item() [7/8]
bool Character::invoke_item (item * , const tripoint & pt) virtual
Asks how to use the item (if it has more than one use_method) and uses it.
Returns true if it destroys the item. Consumes charges from the item. Multi-use items are ONLY supported when all use_methods are iuse_actor!
Reimplemented from Character.
Definition at line 1100 of file character.cpp.
{
    return false;
}
invoke_item() [8/8]
bool avatar::invoke_item (item * , const tripoint & pt) override virtual
Asks how to use the item (if it has more than one use_method) and uses it.
Returns true if it destroys the item. Consumes charges from the item. Multi-use items are ONLY supported when all use_methods are iuse_actor!
Reimplemented from Character.
Definition at line 1256 of file avatar.cpp.
{
    const std::map<std::string, use_function> &use_methods = used->type->use_methods;
    if( use_methods.empty() ) {
        return false;
    } else if( use_methods.size() == 1 ) {
        return invoke_item( used, use_methods.begin()->first, pt );
    }
    uilist umenu;
    umenu.text = string_format( _( "What to do with your %s?" ), used->tname() );
    umenu.hilight_disabled = true;
    for( const auto &e : use_methods ) {
        const auto res = e.second.can_call( *this, *used, false, pt );
        umenu.addentry_desc( MENU_AUTOASSIGN, res.success(), MENU_AUTOASSIGN, e.second.get_name(),
                             res.str() );
    }
    umenu.desc_enabled = std::any_of( umenu.entries.begin(),
    umenu.entries.end(), []( const uilist_entry & elem ) {
        return !elem.desc.empty();
    } );
    umenu.query();
    int choice = umenu.ret;
    if( choice < 0 || choice >= static_cast<int>( use_methods.size() ) ) {
        return false;
    }
    const std::string &method = std::next( use_methods.begin(), choice )->first;
    return invoke_item( used, method, pt );
}
References _, uilist::addentry_desc(), uilist::desc_enabled, uilist::entries, uilist::hilight_disabled, invoke_item(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, string_format(), uilist::text, item::tname(), item::type, and itype::use_methods.
Referenced by fire(), vehicle::interact_with(), invoke_item(), avatar_action::move(), game::npc_menu(), avatar_funcs::use_item(), wield(), and avatar_action::wield().
is_avatar()
bool avatar::is_avatar () const inline override virtual
Reimplemented from Creature.
Definition at line 77 of file avatar.h.
{
            return true;
        }
is_hallucination()
bool avatar::is_hallucination () const override virtual
Implements Creature.
Definition at line 996 of file avatar.cpp.
{
    return false;
}
kill_xp()
int avatar::kill_xp () const
Definition at line 1032 of file avatar.cpp.
{
    return g->get_kill_tracker().kill_xp();
}
References g.
Referenced by debug_menu::debug(), free_upgrade_points(), and kill_xp_for_next_point().
kill_xp_for_next_point()
cata::optional< int > avatar::kill_xp_for_next_point () const
Definition at line 1060 of file avatar.cpp.
{
    auto it = std::lower_bound( xp_cutoffs.begin(), xp_cutoffs.end(), kill_xp() );
    if( it == xp_cutoffs.end() ) {
        return cata::nullopt;
    } else {
        return *it - kill_xp();
    }
}
References kill_xp(), cata::nullopt, and xp_cutoffs.
Referenced by character_display::upgrade_stat_prompt().
load()
void avatar::load (const JsonObject & data)
Definition at line 1009 of file savegame_json.cpp.
{
    player::load( data );
    data.read( "controlling_vehicle", controlling_vehicle );
    data.read( "grab_point", grab_point );
    std::string grab_typestr = "OBJECT_NONE";
    if( grab_point.x != 0 || grab_point.y != 0 ) {
        grab_typestr = "OBJECT_VEHICLE";
        data.read( "grab_type", grab_typestr );
    }
    const auto iter = std::find( obj_type_name.begin(), obj_type_name.end(), grab_typestr );
    grab( iter == obj_type_name.end() ?
          OBJECT_NONE : static_cast<object_type>( std::distance( obj_type_name.begin(), iter ) ),
          grab_point );
    data.read( "focus_pool", focus_pool );
    // stats through kills
    data.read( "str_upgrade", str_upgrade );
    data.read( "dex_upgrade", dex_upgrade );
    data.read( "int_upgrade", int_upgrade );
    data.read( "per_upgrade", per_upgrade );
    // this is so we don't need to call get_option in a draw function
    if( !get_option<bool>( "STATS_THROUGH_KILLS" ) )         {
        str_upgrade = -str_upgrade;
        dex_upgrade = -dex_upgrade;
        int_upgrade = -int_upgrade;
        per_upgrade = -per_upgrade;
    }
    data.read( "magic", magic );
    set_highest_cat_level();
    drench_mut_calc();
    std::string scen_ident = "(null)";
    if( data.read( "scenario", scen_ident ) && string_id<scenario>( scen_ident ).is_valid() ) {
        g->scen = &string_id<scenario>( scen_ident ).obj();
        if( !g->scen->allowed_start( start_location ) ) {
            start_location = g->scen->random_start_location();
        }
    } else {
        const scenario *generic_scenario = scenario::generic();
        // Only display error message if from a game file after scenarios existed.
        if( savegame_loading_version > 20 ) {
            debugmsg( "Tried to use non-existent scenario '%s'. Setting to generic '%s'.",
                      scen_ident.c_str(), generic_scenario->ident().c_str() );
        }
        g->scen = generic_scenario;
    }
    items_identified.clear();
    data.read( "items_identified", items_identified );
    data.read( "translocators", translocators );
    std::vector<int> tmpmissions;
    if( data.read( "active_missions", tmpmissions ) ) {
        active_missions = mission::to_ptr_vector( tmpmissions );
    }
    if( data.read( "failed_missions", tmpmissions ) ) {
        failed_missions = mission::to_ptr_vector( tmpmissions );
    }
    if( data.read( "completed_missions", tmpmissions ) ) {
        completed_missions = mission::to_ptr_vector( tmpmissions );
    }
    int tmpactive_mission = 0;
    if( data.read( "active_mission", tmpactive_mission ) ) {
        if( savegame_loading_version <= 23 ) {
            // In 0.C, active_mission was an index of the active_missions array (-1 indicated no active mission).
            // And it would as often as not be out of bounds (e.g. when a questgiver died).
            // Later, it became a mission * and stored as the mission's uid, and this change broke backward compatibility.
            // Unfortunately, nothing can be done about savegames between the bump to version 24 and 83808a941.
            if( tmpactive_mission >= 0 && tmpactive_mission < static_cast<int>( active_missions.size() ) ) {
                active_mission = active_missions[tmpactive_mission];
            } else if( !active_missions.empty() ) {
                active_mission = active_missions.back();
            }
        } else if( tmpactive_mission != -1 ) {
            active_mission = mission::find( tmpactive_mission );
        }
    }
    // Normally there is only one player character loaded, so if a mission that is assigned to
    // another character (not the current one) fails, the other character(s) are not informed.
    // We must inform them when they get loaded the next time.
    // Only active missions need checking, failed/complete will not change anymore.
    const auto last = std::remove_if( active_missions.begin(),
    active_missions.end(), []( mission const * m ) {
        return m->has_failed();
    } );
    std::copy( last, active_missions.end(), std::back_inserter( failed_missions ) );
    active_missions.erase( last, active_missions.end() );
    if( active_mission && active_mission->has_failed() ) {
        if( active_missions.empty() ) {
            active_mission = nullptr;
        } else {
            active_mission = active_missions.front();
        }
    }
    if( savegame_loading_version <= 23 && is_player() ) {
        // In 0.C there was no player_id member of mission, so it'll be the default -1.
        // When the member was introduced, no steps were taken to ensure compatibility with 0.C, so
        // missions will be buggy for saves between experimental commits bd2088c033 and dd83800.
        // see npc_chatbin::check_missions and npc::talk_to_u
        for( mission *miss : active_missions ) {
            miss->set_player_id_legacy_0c( getID() );
        }
    }
    data.read( "show_map_memory", show_map_memory );
    for( JsonArray pair : data.get_array( "assigned_invlet" ) ) {
        inv.assigned_invlet[static_cast<char>( pair.get_int( 0 ) )] =
            itype_id( pair.get_string( 1 ) );
    }
    if( data.has_member( "invcache" ) ) {
        JsonIn *jip = data.get_raw( "invcache" );
        inv.json_load_invcache( *jip );
    }
    data.read( "preferred_aiming_mode", preferred_aiming_mode );
    if( data.has_array( "faction_warnings" ) ) {
        for( JsonObject warning_data : data.get_array( "faction_warnings" ) ) {
            warning_data.allow_omitted_members();
            std::string fac_id = warning_data.get_string( "fac_warning_id" );
            int warning_num = warning_data.get_int( "fac_warning_num" );
            time_point warning_time = calendar::before_time_starts;
            warning_data.read( "fac_warning_time", warning_time );
            warning_record[faction_id( fac_id )] = std::make_pair( warning_num, warning_time );
        }
    }
}
References active_mission, active_missions, inventory::assigned_invlet, calendar::before_time_starts, completed_missions, Character::controlling_vehicle, debugmsg, dex_upgrade, Character::drench_mut_calc(), Character::fac_id, failed_missions, mission::find(), detail::find(), Character::focus_pool, g, scenario::generic(), JsonObject::get_array(), JsonObject::get_raw(), Character::getID(), grab(), player::grab_point, JsonObject::has_array(), mission::has_failed(), JsonObject::has_member(), scenario::ident(), int_upgrade, Character::inv, player::is_player(), string_id< T >::is_valid(), items_identified, itype_id, inventory::json_load_invcache(), last, player::load(), Character::magic, string_id< T >::obj(), obj_type_name, OBJECT_NONE, per_upgrade, preferred_aiming_mode, JsonObject::read(), savegame_loading_version, Character::set_highest_cat_level(), show_map_memory, str_upgrade, mission::to_ptr_vector(), translocators, warning_record, tripoint::x, and tripoint::y.
Referenced by deserialize().
load_map_memory()
void avatar::load_map_memory ()
Definition at line 137 of file avatar.cpp.
{
    player_map_memory->load( g->m.getabs( pos() ) );
}
References g, player_map_memory, and Character::pos().
Referenced by game::load().
load_template()
bool avatar::load_template (const std::string & template_name, points_left & points)
Definition at line 3007 of file newcharacter.cpp.
{
    return read_from_file_json( PATH_INFO::templatedir() + template_name +
    ".template", [&]( JsonIn & jsin ) {
        if( jsin.test_array() ) {
            // not a legacy template
            jsin.start_array();
            if( jsin.end_array() ) {
                return;
            }
            JsonObject jobj = jsin.get_object();
            points.stat_points = jobj.get_int( "stat_points" );
            points.trait_points = jobj.get_int( "trait_points" );
            points.skill_points = jobj.get_int( "skill_points" );
            points.limit = static_cast<points_left::point_limit>( jobj.get_int( "limit" ) );
            random_start_location = jobj.get_bool( "random_start_location", true );
            const std::string jobj_start_location = jobj.get_string( "start_location", "" );
            // g->scen->allowed_start( loc.ident() ) is checked once scenario loads in avatar::load()
            for( const auto &loc : start_locations::get_all() ) {
                if( loc.id.str() == jobj_start_location ) {
                    random_start_location = false;
                    this->start_location = loc.id;
                    break;
                }
            }
            if( jsin.end_array() ) {
                return;
            }
        } else {
            points.stat_points = 0;
            points.trait_points = 0;
            points.skill_points = 0;
        }
        deserialize( jsin );
        if( MAP_SHARING::isSharing() ) {
            // just to make sure we have the right name
            name = MAP_SHARING::getUsername();
        }
    } );
}
References JsonIn::end_array(), start_locations::get_all(), JsonIn::get_object(), points_left::limit, player::random_start_location, read_from_file_json(), points_left::skill_points, points_left::stat_points, PATH_INFO::templatedir(), JsonIn::test_array(), and points_left::trait_points.
Referenced by create().
memorize_symbol()
void avatar::memorize_symbol (const tripoint & pos, int symbol)
Memorizes a given tile in curses mode; finalize_terrain_memory_curses needs to be called after it.
Definition at line 158 of file avatar.cpp.
{
    player_map_memory->memorize_symbol( pos, symbol );
}
References player_map_memory, Character::pos(), and Character::symbol().
memorize_tile()
void avatar::memorize_tile (const tripoint & pos, const std::string & ter, int subtile, int rotation)
Memorizes a given tile in tiles mode; finalize_tile_memory needs to be called after it.
Definition at line 152 of file avatar.cpp.
{
    player_map_memory->memorize_tile( pos, ter, subtile, rotation );
}
References player_map_memory, and Character::pos().
on_mission_assignment()
void avatar::on_mission_assignment (mission & new_mission)
Called when a mission has been assigned to the player.
Definition at line 224 of file avatar.cpp.
{
    active_missions.push_back( &new_mission );
    set_active_mission( new_mission );
}
References active_missions, and set_active_mission().
Referenced by mission::assign().
on_mission_finished()
void avatar::on_mission_finished (mission & cur_mission)
Called when a mission has been completed or failed.
Either way it's finished. Check mission::has_failed to see which case it is.
Definition at line 230 of file avatar.cpp.
{
    if( cur_mission.has_failed() ) {
        failed_missions.push_back( &cur_mission );
        add_msg_if_player( m_bad, _( "Mission \"%s\" is failed." ), cur_mission.name() );
    } else {
        completed_missions.push_back( &cur_mission );
        add_msg_if_player( m_good, _( "Mission \"%s\" is successfully completed." ),
                           cur_mission.name() );
    }
    const auto iter = std::find( active_missions.begin(), active_missions.end(), &cur_mission );
    if( iter == active_missions.end() ) {
        debugmsg( "completed mission %d was not in the active_missions list", cur_mission.get_id() );
    } else {
        active_missions.erase( iter );
    }
    if( &cur_mission == active_mission ) {
        if( active_missions.empty() ) {
            active_mission = nullptr;
        } else {
            active_mission = active_missions.front();
        }
    }
}
References _, active_mission, active_missions, player::add_msg_if_player(), completed_missions, debugmsg, failed_missions, detail::find(), mission::get_id(), mission::has_failed(), m_bad, m_good, and mission::name().
operator=() [1/2]
avatar & avatar::operator= (avatar &&) default
operator=() [2/2]
avatar & avatar::operator= (const avatar &) delete
prepare_map_memory_region()
void avatar::prepare_map_memory_region (const tripoint & p1, const tripoint & p2)
Definition at line 142 of file avatar.cpp.
{
    player_map_memory->prepare_region( p1, p2 );
}
References player_map_memory.
randomize()
void avatar::randomize (bool random_scenario, points_left & points, bool play_now = false)
Definition at line 201 of file newcharacter.cpp.
{
    const int max_stat_points = points.is_freeform() ? 20 : MAX_STAT;
    const int max_trait_points = get_option<int>( "MAX_TRAIT_POINTS" );
    // Reset everything to the defaults to have a clean state.
    *this = avatar();
    male = ( rng( 1, 100 ) > 50 );
    if( !MAP_SHARING::isSharing() ) {
        play_now ? pick_name() : pick_name( true );
    } else {
        name = MAP_SHARING::getUsername();
    }
    // if adjusting min and max age from 16 and 55, make sure to see set_description()
    init_age = rng( 16, 55 );
    // if adjusting min and max height from 145 and 200, make sure to see set_description()
    init_height = rng( 145, 200 );
    bool cities_enabled = world_generator->active_world->WORLD_OPTIONS["CITY_SIZE"].getValue() != "0";
    if( random_scenario ) {
        std::vector<const scenario *> scenarios;
        for( const auto &scen : scenario::get_all() ) {
            if( !scen.has_flag( flag_CHALLENGE ) &&
                ( !scen.has_flag( flag_CITY_START ) || cities_enabled ) ) {
                scenarios.emplace_back( &scen );
            }
        }
        g->scen = random_entry( scenarios );
    } else if( !cities_enabled ) {
        static const string_id<scenario> wilderness_only_scenario( "wilderness" );
        g->scen = &wilderness_only_scenario.obj();
    }
    prof = g->scen->weighted_random_profession();
    random_start_location = true;
    str_max = rng( 6, HIGH_STAT - 2 );
    dex_max = rng( 6, HIGH_STAT - 2 );
    int_max = rng( 6, HIGH_STAT - 2 );
    per_max = rng( 6, HIGH_STAT - 2 );
    points.stat_points = points.stat_points - str_max - dex_max - int_max - per_max;
    points.skill_points = points.skill_points - prof->point_cost() - g->scen->point_cost();
    // The default for each stat is 8, and that default does not cost any points.
    // Values below give points back, values above require points. The line above has removed
    // to many points, therefore they are added back.
    points.stat_points += 8 * 4;
    int num_gtraits = 0;
    int num_btraits = 0;
    int tries = 0;
    newcharacter::add_traits( *this, points ); // adds mandatory profession/scenario traits.
    for( const trait_id &mut : get_mutations() ) {
        const mutation_branch &mut_info = mut.obj();
        if( mut_info.profession ) {
            continue;
        }
        // Scenario/profession traits do not cost any points, but they are counted toward
        // the limit (MAX_TRAIT_POINTS)
        if( mut_info.points >= 0 ) {
            num_gtraits += mut_info.points;
        } else {
            num_btraits -= mut_info.points;
        }
    }
    /* The loops variable is used to prevent the algorithm running in an infinite loop */
    unsigned int loops = 0;
    while( loops <= 100000 && ( !points.is_valid() || rng( -3, 20 ) > points.skill_points_left() ) ) {
        loops++;
        trait_id rn;
        if( num_btraits < max_trait_points && one_in( 3 ) ) {
            tries = 0;
            do {
                rn = newcharacter::random_bad_trait();
                tries++;
            } while( ( has_trait( rn ) || num_btraits - rn->points > max_trait_points ) &&
                     tries < 5 );
            if( tries < 5 && !newcharacter::has_conflicting_trait( *this, rn ) ) {
                toggle_trait( rn );
                points.trait_points -= rn->points;
                num_btraits -= rn->points;
            }
        } else {
            switch( rng( 1, 4 ) ) {
                case 1:
                    if( str_max > 5 ) {
                        str_max--;
                        points.stat_points++;
                    }
                    break;
                case 2:
                    if( dex_max > 5 ) {
                        dex_max--;
                        points.stat_points++;
                    }
                    break;
                case 3:
                    if( int_max > 5 ) {
                        int_max--;
                        points.stat_points++;
                    }
                    break;
                case 4:
                    if( per_max > 5 ) {
                        per_max--;
                        points.stat_points++;
                    }
                    break;
            }
        }
    }
    loops = 0;
    while( points.has_spare() && loops <= 100000 ) {
        const bool allow_stats = points.stat_points_left() > 0;
        const bool allow_traits = points.trait_points_left() > 0 && num_gtraits < max_trait_points;
        int r = rng( 1, 9 );
        trait_id rn;
        switch( r ) {
            case 1:
            case 2:
            case 3:
            case 4:
                if( allow_traits ) {
                    rn = newcharacter::random_good_trait();
                    auto &mdata = rn.obj();
                    if( !has_trait( rn ) && points.trait_points_left() >= mdata.points &&
                        num_gtraits + mdata.points <= max_trait_points &&
                        !newcharacter::has_conflicting_trait( *this, rn ) ) {
                        toggle_trait( rn );
                        points.trait_points -= mdata.points;
                        num_gtraits += mdata.points;
                    }
                    break;
                }
            /* fallthrough */
            case 5:
                if( allow_stats ) {
                    switch( rng( 1, 4 ) ) {
                        case 1:
                            if( str_max < HIGH_STAT ) {
                                str_max++;
                                points.stat_points--;
                            } else if( points.stat_points_left() >= 2 && str_max < max_stat_points ) {
                                str_max++;
                                points.stat_points = points.stat_points - 2;
                            }
                            break;
                        case 2:
                            if( dex_max < HIGH_STAT ) {
                                dex_max++;
                                points.stat_points--;
                            } else if( points.stat_points_left() >= 2 && dex_max < max_stat_points ) {
                                dex_max++;
                                points.stat_points = points.stat_points - 2;
                            }
                            break;
                        case 3:
                            if( int_max < HIGH_STAT ) {
                                int_max++;
                                points.stat_points--;
                            } else if( points.stat_points_left() >= 2 && int_max < max_stat_points ) {
                                int_max++;
                                points.stat_points = points.stat_points - 2;
                            }
                            break;
                        case 4:
                            if( per_max < HIGH_STAT ) {
                                per_max++;
                                points.stat_points--;
                            } else if( points.stat_points_left() >= 2 && per_max < max_stat_points ) {
                                per_max++;
                                points.stat_points = points.stat_points - 2;
                            }
                            break;
                    }
                    break;
                }
            /* fallthrough */
            case 6:
            case 7:
            case 8:
            case 9:
                const skill_id aSkill = Skill::random_skill();
                const int level = get_skill_level( aSkill );
                if( level < points.skill_points_left() && level < MAX_SKILL && loops > 10000 ) {
                    points.skill_points -= skill_increment_cost( *this, aSkill );
                    // For balance reasons, increasing a skill from level 0 gives you 1 extra level for free
                    set_skill_level( aSkill, ( level == 0 ? 2 : level + 1 ) );
                }
                break;
        }
        loops++;
    }
    set_body();
}
References newcharacter::add_traits(), avatar(), cities_enabled, Character::dex_max, flag_CHALLENGE(), flag_CITY_START(), g, scenario::get_all(), Character::get_mutations(), Character::get_skill_level(), MAP_SHARING::getUsername(), newcharacter::has_conflicting_trait(), points_left::has_spare(), Character::has_trait(), HIGH_STAT, Character::init_age, Character::init_height, Character::int_max, points_left::is_freeform(), points_left::is_valid(), MAP_SHARING::isSharing(), Character::male, MAX_STAT, Character::name, string_id< T >::obj(), one_in(), Character::per_max, Character::pick_name(), profession::point_cost(), mutation_branch::points, Character::prof, mutation_branch::profession, newcharacter::random_bad_trait(), random_entry(), newcharacter::random_good_trait(), Skill::random_skill(), player::random_start_location, rng(), Creature::set_body(), Character::set_skill_level(), skill_increment_cost(), points_left::skill_points, points_left::skill_points_left(), points_left::stat_points, points_left::stat_points_left(), Character::str_max, Character::toggle_trait(), points_left::trait_points, points_left::trait_points_left(), and world_generator.
Referenced by create(), and set_description().
read()
bool avatar::read (item_location loc, bool continuous = false)
Handles reading effects and returns true if activity started.
Explanation of ACT_READ activity values:
position: ID of the reader targets: 1-element vector with the item_location (always in inventory/wielded) of the book being read index: We are studying until the player with this ID gains a level; 0 indicates reading once values: IDs of the NPCs who will learn something str_values: Parallel to values, these contain the learning penalties (as doubles in string form) as follows: Experience gained = Experience normally gained * penalty
Definition at line 387 of file avatar.cpp.
{
    if( !loc ) {
        add_msg( m_info, _( "Never mind." ) );
        return false;
    }
    item &it = *loc;
    if( !has_identified( it.typeId() ) ) {
        // We insta-identify the book, then try to read it
        items_identified.insert( it.typeId() );
        skim_book_msg( it, *this );
    }
    std::vector<std::string> fail_messages;
    const player *reader = get_book_reader( it, fail_messages );
    if( reader == nullptr ) {
        // We can't read, and neither can our followers
        for( const std::string &reason : fail_messages ) {
            add_msg( m_bad, reason );
        }
        return false;
    }
    const int time_taken = time_to_read( it, *reader );
    add_msg( m_debug, "avatar::read: time_taken = %d", time_taken );
    player_activity act( ACT_READ, time_taken, continuous ? activity.index : 0,
                         reader->getID().get_value() );
    act.targets.emplace_back( loc );
    if( it.typeId() == itype_guidebook ) {
        // special guidebook effect: print a misc. hint when read
        if( reader != this ) {
            add_msg( m_info, fail_messages[0] );
            dynamic_cast<const npc *>( reader )->say( get_hint() );
        } else {
            add_msg( m_info, get_hint() );
        }
        mod_moves( -100 );
        return false;
    }
    const auto &type = it.type->book;
    const skill_id &skill = type->skill;
    const std::string skill_name = skill ? skill.obj().name() : "";
    // Find NPCs to join the study session:
    std::map<npc *, std::string> learners;
    //reading only for fun
    std::map<npc *, std::string> fun_learners;
    std::map<npc *, std::string> nonlearners;
    auto candidates = character_funcs::get_crafting_helpers( *this );
    for( npc *elem : candidates ) {
        const int lvl = elem->get_skill_level( skill );
        const bool is_fun_to_read = character_funcs::is_fun_to_read( *elem, it );
        const bool skill_req = ( is_fun_to_read && ( !skill || lvl >= type->req ) ) ||
                               ( skill && lvl < type->level && lvl >= type->req );
        const bool morale_req = is_fun_to_read || elem->has_morale_to_read();
        if( !skill_req && elem != reader ) {
            if( skill && lvl < type->req ) {
                nonlearners.insert( { elem, string_format( _( " (needs %d %s)" ), type->req, skill_name ) } );
            } else if( skill ) {
                nonlearners.insert( { elem, string_format( _( " (already has %d %s)" ), type->level, skill_name ) } );
            } else {
                nonlearners.insert( { elem, _( " (uninterested)" ) } );
            }
        } else if( elem->is_deaf() && reader != elem ) {
            nonlearners.insert( { elem, _( " (deaf)" ) } );
        } else if( !morale_req ) {
            nonlearners.insert( { elem, _( " (too sad)" ) } );
        } else if( skill && lvl < type->level ) {
            const double penalty = static_cast<double>( time_taken ) / time_to_read( it, *reader, elem );
            learners.insert( {elem, elem == reader ? _( " (reading aloud to you)" ) : ""} );
            act.values.push_back( elem->getID().get_value() );
            act.str_values.push_back( std::to_string( penalty ) );
        } else {
            fun_learners.insert( {elem, elem == reader ? _( " (reading aloud to you)" ) : "" } );
            act.values.push_back( elem->getID().get_value() );
            act.str_values.emplace_back( "1" );
        }
    }
    if( !continuous ) {
        //only show the menu if there's useful information or multiple options
        if( skill || !nonlearners.empty() || !fun_learners.empty() ) {
            uilist menu;
            // Some helpers to reduce repetition:
            auto length = []( const std::pair<npc *, std::string> &elem ) {
                return utf8_width( elem.first->disp_name() ) + utf8_width( elem.second );
            };
            auto max_length = [&length]( const std::map<npc *, std::string> &m ) {
                auto max_ele = std::max_element( m.begin(),
                                                 m.end(), [&length]( const std::pair<npc *, std::string> &left,
                const std::pair<npc *, std::string> &right ) {
                    return length( left ) < length( right );
                } );
                return max_ele == m.end() ? 0 : length( *max_ele );
            };
            auto get_text =
            [&]( const std::map<npc *, std::string> &m, const std::pair<npc *, std::string> &elem ) {
                const int lvl = elem.first->get_skill_level( skill );
                const std::string lvl_text = skill ? string_format( _( " | current level: %d" ), lvl ) : "";
                const std::string name_text = elem.first->disp_name() + elem.second;
                return string_format( "%s%s", left_justify( name_text, max_length( m ) ), lvl_text );
            };
            auto add_header = [&menu]( const std::string & str ) {
                menu.addentry( -1, false, -1, "" );
                uilist_entry header( -1, false, -1, str, c_yellow, c_yellow );
                header.force_color = true;
                menu.entries.push_back( header );
            };
            menu.title = !skill ? string_format( _( "Reading %s" ), it.type_name() ) :
                         //~ %1$s: book name, %2$s: skill name, %3$d and %4$d: skill levels
                         string_format( _( "Reading %1$s (can train %2$s from %3$d to %4$d)" ), it.type_name(),
                                        skill_name, type->req, type->level );
            if( skill ) {
                const int lvl = get_skill_level( skill );
                menu.addentry( getID().get_value(), lvl < type->level, '0',
                               string_format( _( "Read until you gain a level | current level: %d" ), lvl ) );
            } else {
                menu.addentry( -1, false, '0', _( "Read until you gain a level" ) );
            }
            menu.addentry( 0, true, '1', _( "Read once" ) );
            if( skill && !learners.empty() ) {
                add_header( _( "Read until this NPC gains a level:" ) );
                for( const auto &elem : learners ) {
                    menu.addentry( elem.first->getID().get_value(), true, -1,
                                   get_text( learners, elem ) );
                }
            }
            if( !fun_learners.empty() ) {
                add_header( _( "Reading for fun:" ) );
                for( const auto &elem : fun_learners ) {
                    menu.addentry( -1, false, -1, get_text( fun_learners, elem ) );
                }
            }
            if( !nonlearners.empty() ) {
                add_header( _( "Not participating:" ) );
                for( const auto &elem : nonlearners ) {
                    menu.addentry( -1, false, -1, get_text( nonlearners, elem ) );
                }
            }
            menu.query( true );
            if( menu.ret == UILIST_CANCEL ) {
                add_msg( m_info, _( "Never mind." ) );
                return false;
            }
            act.index = menu.ret;
        }
        if( it.type->use_methods.count( "MA_MANUAL" ) ) {
            if( martial_arts_data->has_martialart( martial_art_learned_from( *it.type ) ) ) {
                add_msg_if_player( m_info, _( "You already know all this book has to teach." ) );
                activity.set_to_null();
                return false;
            }
            uilist menu;
            menu.title = string_format( _( "Train %s from manual:" ),
                                        martial_art_learned_from( *it.type )->name );
            menu.addentry( -1, true, '1', _( "Train once" ) );
            menu.addentry( getID().get_value(), true, '0', _( "Train until tired or success" ) );
            menu.query( true );
            if( menu.ret == UILIST_CANCEL ) {
                add_msg( m_info, _( "Never mind." ) );
                return false;
            }
            act.index = menu.ret;
        }
        add_msg( m_info, _( "Now reading %s, %s to stop early." ),
                 it.type_name(), press_x( ACTION_PAUSE ) );
    }
    // Print some informational messages, but only the first time or if the information changes
    if( !continuous || activity.position != act.position ) {
        if( reader != this ) {
            add_msg( m_info, fail_messages[0] );
            add_msg( m_info, _( "%s reads aloud" ), reader->disp_name() );
        } else if( !learners.empty() || !fun_learners.empty() ) {
            add_msg( m_info, _( "You read aloud" ) );
        }
    }
    if( !continuous ||
    !std::all_of( learners.begin(), learners.end(), [&]( const std::pair<npc *, std::string> &elem ) {
    return std::count( activity.values.begin(), activity.values.end(),
                       elem.first->getID().get_value() ) != 0;
    } ) ||
    !std::all_of( activity.values.begin(), activity.values.end(), [&]( int elem ) {
        return learners.find( g->find_npc( character_id( elem ) ) ) != learners.end();
    } ) ) {
        if( learners.size() == 1 ) {
            add_msg( m_info, _( "%s studies with you." ), learners.begin()->first->disp_name() );
        } else if( !learners.empty() ) {
            const std::string them = enumerate_as_string( learners.begin(),
            learners.end(), [&]( const std::pair<npc *, std::string> &elem ) {
                return elem.first->disp_name();
            } );
            add_msg( m_info, _( "%s study with you." ), them );
        }
        // Don't include the reader as it would be too redundant.
        std::set<std::string> readers;
        for( const auto &elem : fun_learners ) {
            if( elem.first != reader ) {
                readers.insert( elem.first->disp_name() );
            }
        }
        if( readers.size() == 1 ) {
            add_msg( m_info, _( "%s reads with you for fun." ), readers.begin()->c_str() );
        } else if( !readers.empty() ) {
            const std::string them = enumerate_as_string( readers );
            add_msg( m_info, _( "%s read with you for fun." ), them );
        }
    }
    const float vision_mod = std::min(
                                 character_funcs::fine_detail_vision_mod( *this ),
                                 character_funcs::fine_detail_vision_mod( *reader )
                             );
    if( vision_mod > character_funcs::FINE_VISION_PERFECT ) {
        add_msg( m_warning,
                 _( "It's difficult for %s to see fine details right now.  Reading will take longer than usual." ),
                 reader->disp_name() );
    }
    const int intelligence = get_int();
    const bool complex_penalty = type->intel > std::min( intelligence, reader->get_int() ) &&
                                 !reader->has_trait( trait_PROF_DICEMASTER );
    const player *complex_player = reader->get_int() < intelligence ? reader : this;
    if( complex_penalty && !continuous ) {
        add_msg( m_warning,
                 _( "This book is too complex for %s to easily understand.  It will take longer to read." ),
                 complex_player->disp_name() );
    }
    // push an indentifier of martial art book to the action handling
    if( it.type->use_methods.count( "MA_MANUAL" ) ) {
        if( get_stamina() < get_stamina_max() / 10 ) {
            add_msg( m_info, _( "You are too exhausted to train martial arts." ) );
            return false;
        }
        act.str_values.clear();
        act.str_values.emplace_back( "martial_art" );
    }
    assign_activity( act );
    // Reinforce any existing morale bonus/penalty, so it doesn't decay
    // away while you read more.
    const time_duration decay_start = 1_turns * time_taken / 1000;
    std::set<Character *> apply_morale = { this };
    for( const auto &elem : learners ) {
        apply_morale.insert( elem.first );
    }
    for( const auto &elem : fun_learners ) {
        apply_morale.insert( elem.first );
    }
    for( Character *ch : apply_morale ) {
        int fun = character_funcs::get_book_fun_for( *ch, it );
        ch->add_morale( MORALE_BOOK, 0, fun * 15, decay_start + 30_minutes,
                        decay_start, false, it.type );
    }
    return true;
}
References _, act, ACT_READ, ACTION_PAUSE, Character::activity, debug_menu::add_header(), add_msg(), player::add_msg_if_player(), uilist::addentry(), Character::assign_activity(), itype::book, c_yellow, Character::disp_name(), uilist::entries, enumerate_as_string(), character_funcs::fine_detail_vision_mod(), character_funcs::FINE_VISION_PERFECT, uilist_entry::force_color, character_funcs::get_book_fun_for(), get_book_reader(), character_funcs::get_crafting_helpers(), get_hint(), Character::get_int(), Character::get_skill_level(), Character::get_stamina(), Character::get_stamina_max(), character_id::get_value(), Creature::get_value(), Character::getID(), has_identified(), Character::has_trait(), player_activity::index, character_funcs::is_fun_to_read(), items_identified, itype_guidebook, left, left_justify(), m_bad, m_debug, m_info, m_warning, martial_art_learned_from(), Character::martial_arts_data, Creature::mod_moves(), MORALE_BOOK, martialart::name, Skill::name(), string_id< T >::obj(), player_activity::position, press_x(), uilist::query(), uilist::ret, right, player_activity::set_to_null(), skim_book_msg(), string_format(), time_to_read(), uilist::title, to_string(), trait_PROF_DICEMASTER, type, item::type, item::type_name(), item::typeId(), UILIST_CANCEL, itype::use_methods, utf8_width(), and player_activity::values.
Referenced by do_read(), read(), examine_item_menu::run(), and avatar_funcs::use_item().
reset_all_misions()
void avatar::reset_all_misions ()
Resets all missions before saving character to template.
Definition at line 198 of file avatar.cpp.
{
    active_mission = nullptr;
    active_missions.clear();
    completed_missions.clear();
    failed_missions.clear();
}
References active_mission, active_missions, completed_missions, and failed_missions.
reset_move_mode()
void avatar::reset_move_mode ()
Definition at line 1180 of file avatar.cpp.
{
    if( move_mode != CMM_WALK ) {
        set_movement_mode( CMM_WALK );
    }
}
References CMM_WALK, Character::move_mode, and set_movement_mode().
Referenced by overmap_ui::display(), and game::handle_action().
save_map_memory()
bool avatar::save_map_memory ()
Definition at line 132 of file avatar.cpp.
{
    return player_map_memory->save( g->m.getabs( pos() ) );
}
References g, player_map_memory, and Character::pos().
Referenced by game::save_player_data().
save_template()
void avatar::save_template (const std::string & name, const points_left & points)
Definition at line 2982 of file newcharacter.cpp.
{
    std::string name_san = ensure_valid_file_name( name );
    write_to_file( PATH_INFO::templatedir() + name_san + ".template", [&]( std::ostream & fout ) {
        JsonOut jsout( fout, true );
        jsout.start_array();
        jsout.start_object();
        jsout.member( "stat_points", points.stat_points );
        jsout.member( "trait_points", points.trait_points );
        jsout.member( "skill_points", points.skill_points );
        jsout.member( "limit", points.limit );
        jsout.member( "random_start_location", random_start_location );
        if( !random_start_location ) {
            jsout.member( "start_location", start_location );
        }
        jsout.end_object();
        serialize( jsout );
        jsout.end_array();
    }, _( "player template" ) );
}
References _, JsonOut::end_array(), JsonOut::end_object(), ensure_valid_file_name(), points_left::limit, JsonOut::member(), Character::name, player::random_start_location, serialize(), points_left::skill_points, JsonOut::start_array(), JsonOut::start_object(), points_left::stat_points, PATH_INFO::templatedir(), points_left::trait_points, and write_to_file().
Referenced by create(), and set_description().
serialize()
void avatar::serialize (JsonOut & json) const override virtual
Implements player.
Definition at line 929 of file savegame_json.cpp.
{
    json.start_object();
    store( json );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::start_object(), and store().
Referenced by save_template().
set_active_mission()
void avatar::set_active_mission (mission & cur_mission)
Set which mission is active.
The mission must be listed in active_missions.
Definition at line 214 of file avatar.cpp.
{
    const auto iter = std::find( active_missions.begin(), active_missions.end(), &cur_mission );
    if( iter == active_missions.end() ) {
        debugmsg( "new active mission %d is not in the active_missions list", cur_mission.get_id() );
    } else {
        active_mission = &cur_mission;
    }
}
References active_mission, active_missions, debugmsg, detail::find(), and mission::get_id().
Referenced by game::list_missions(), and on_mission_assignment().
set_movement_mode()
void avatar::set_movement_mode (character_movemode mode) override virtual
Implements Character.
Definition at line 1097 of file avatar.cpp.
{
    switch( new_mode ) {
        case CMM_WALK: {
            if( is_mounted() ) {
                if( mounted_creature->has_flag( MF_RIDEABLE_MECH ) ) {
                    add_msg( _( "You set your mech's leg power to a loping fast walk." ) );
                } else {
                    add_msg( _( "You nudge your steed into a steady trot." ) );
                }
            } else {
                add_msg( _( "You start walking." ) );
            }
            break;
        }
        case CMM_RUN: {
            if( can_run() ) {
                if( is_hauling() ) {
                    stop_hauling();
                }
                if( is_mounted() ) {
                    if( mounted_creature->has_flag( MF_RIDEABLE_MECH ) ) {
                        add_msg( _( "You set the power of your mech's leg servos to maximum." ) );
                    } else {
                        add_msg( _( "You spur your steed into a gallop." ) );
                    }
                } else {
                    add_msg( _( "You start running." ) );
                }
            } else {
                if( is_mounted() ) {
                    // mounts don't currently have stamina, but may do in future.
                    add_msg( m_bad, _( "Your steed is too tired to go faster." ) );
                } else if( get_working_leg_count() < 2 ) {
                    add_msg( m_bad, _( "You need two functional legs to run." ) );
                } else {
                    add_msg( m_bad, _( "You're too tired to run." ) );
                }
                return;
            }
            break;
        }
        case CMM_CROUCH: {
            if( is_mounted() ) {
                if( mounted_creature->has_flag( MF_RIDEABLE_MECH ) ) {
                    add_msg( _( "You reduce the power of your mech's leg servos to minimum." ) );
                } else {
                    add_msg( _( "You slow your steed to a walk." ) );
                }
            } else {
                add_msg( _( "You start crouching." ) );
            }
            break;
        }
        default: {
            return;
        }
    }
    if( move_mode == CMM_CROUCH || new_mode == CMM_CROUCH ) {
        // crouching affects visibility
        get_map().set_seen_cache_dirty( pos().z );
    }
    move_mode = new_mode;
}
References _, add_msg(), Character::can_run(), CMM_CROUCH, CMM_RUN, CMM_WALK, get_map(), Character::get_working_leg_count(), Character::is_hauling(), Character::is_mounted(), m_bad, MF_RIDEABLE_MECH, Character::mounted_creature, Character::move_mode, Character::pos(), map::set_seen_cache_dirty(), and Character::stop_hauling().
Referenced by cycle_move_mode(), open_movement_mode_menu(), reset_move_mode(), toggle_crouch_mode(), and toggle_run_mode().
should_show_map_memory()
bool avatar::should_show_map_memory ()
Definition at line 127 of file avatar.cpp.
{
    return show_map_memory;
}
References show_map_memory.
store()
void avatar::store (JsonOut & json) const
Definition at line 938 of file savegame_json.cpp.
{
    player::store( json );
    if( g->scen != nullptr ) {
        json.member( "scenario", g->scen->ident() );
    }
    // someday, npcs may drive
    json.member( "controlling_vehicle", controlling_vehicle );
    // shopping carts, furniture etc
    json.member( "grab_point", grab_point );
    json.member( "grab_type", obj_type_name[static_cast<int>( grab_type ) ] );
    // misc player specific stuff
    json.member( "focus_pool", focus_pool );
    // stats through kills
    json.member( "str_upgrade", std::abs( str_upgrade ) );
    json.member( "dex_upgrade", std::abs( dex_upgrade ) );
    json.member( "int_upgrade", std::abs( int_upgrade ) );
    json.member( "per_upgrade", std::abs( per_upgrade ) );
    // Player only, books they have read at least once.
    json.member( "items_identified", items_identified );
    json.member( "translocators", translocators );
    // mission stuff
    json.member( "active_mission", active_mission == nullptr ? -1 : active_mission->get_id() );
    json.member( "active_missions", mission::to_uid_vector( active_missions ) );
    json.member( "completed_missions", mission::to_uid_vector( completed_missions ) );
    json.member( "failed_missions", mission::to_uid_vector( failed_missions ) );
    json.member( "show_map_memory", show_map_memory );
    json.member( "assigned_invlet" );
    json.start_array();
    for( auto iter : inv.assigned_invlet ) {
        json.start_array();
        json.write( iter.first );
        json.write( iter.second );
        json.end_array();
    }
    json.end_array();
    json.member( "invcache" );
    inv.json_save_invcache( json );
    json.member( "preferred_aiming_mode", preferred_aiming_mode );
    json.member( "faction_warnings" );
    json.start_array();
    for( const auto &elem : warning_record ) {
        json.start_object();
        json.member( "fac_warning_id", elem.first );
        json.member( "fac_warning_num", elem.second.first );
        json.member( "fac_warning_time", elem.second.second );
        json.end_object();
    }
    json.end_array();
}
References active_mission, active_missions, inventory::assigned_invlet, completed_missions, Character::controlling_vehicle, dex_upgrade, JsonOut::end_array(), JsonOut::end_object(), failed_missions, Character::focus_pool, g, mission::get_id(), player::grab_point, grab_type, int_upgrade, Character::inv, items_identified, inventory::json_save_invcache(), JsonOut::member(), obj_type_name, per_upgrade, preferred_aiming_mode, show_map_memory, JsonOut::start_array(), JsonOut::start_object(), player::store(), str_upgrade, mission::to_uid_vector(), translocators, warning_record, and JsonOut::write().
Referenced by serialize().
time_to_read()
int avatar::time_to_read (const item & book, const player & reader, const player * learner = nullptr) const
Helper function for get_book_reader.
Warning
This function assumes that the everyone is able to read
Parameters
book The book being read
reader the player/NPC who's reading to the caller
learner if not nullptr, assume that the caller and reader read at a pace that isn't too fast for him
Definition at line 345 of file avatar.cpp.
{
    const auto &type = book.type->book;
    const skill_id &skill = type->skill;
    // The reader's reading speed has an effect only if they're trying to understand the book as they read it
    // Reading speed is assumed to be how well you learn from books (as opposed to hands-on experience)
    const bool try_understand = character_funcs::is_fun_to_read( reader, book ) ||
                                reader.get_skill_level( skill ) < type->level;
    int reading_speed = try_understand ? std::max( reader.read_speed(), read_speed() ) : read_speed();
    if( learner ) {
        reading_speed = std::max( reading_speed, learner->read_speed() );
    }
    int retval = type->time * reading_speed;
    retval *= std::min( character_funcs::fine_detail_vision_mod( *this ),
                        character_funcs::fine_detail_vision_mod( reader ) );
    const int effective_int = std::min( { get_int(), reader.get_int(), learner ? learner->get_int() : INT_MAX } );
    if( type->intel > effective_int && !reader.has_trait( trait_PROF_DICEMASTER ) ) {
        retval += type->time * ( type->intel - effective_int ) * 100;
    }
    return retval;
}
References itype::book, character_funcs::fine_detail_vision_mod(), Character::get_int(), Character::get_skill_level(), Character::has_trait(), character_funcs::is_fun_to_read(), Character::read_speed(), trait_PROF_DICEMASTER, type, and item::type.
Referenced by get_book_reader(), and read().
toggle_crouch_mode()
void avatar::toggle_crouch_mode ()
Definition at line 1171 of file avatar.cpp.
{
    if( move_mode == CMM_CROUCH ) {
        set_movement_mode( CMM_WALK );
    } else {
        set_movement_mode( CMM_CROUCH );
    }
}
References CMM_CROUCH, CMM_WALK, Character::move_mode, and set_movement_mode().
Referenced by game::handle_action().
toggle_map_memory()
void avatar::toggle_map_memory ()
Definition at line 122 of file avatar.cpp.
{
    show_map_memory = !show_map_memory;
}
References show_map_memory.
Referenced by game::handle_action().
toggle_run_mode()
void avatar::toggle_run_mode ()
Definition at line 1162 of file avatar.cpp.
{
    if( move_mode == CMM_RUN ) {
        set_movement_mode( CMM_WALK );
    } else {
        set_movement_mode( CMM_RUN );
    }
}
References CMM_RUN, CMM_WALK, Character::move_mode, and set_movement_mode().
Referenced by game::handle_action(), and game::on_move_effects().
upgrade_stat()
void avatar::upgrade_stat (character_stat stat)
Definition at line 1070 of file avatar.cpp.
{
    switch( stat ) {
        case character_stat::STRENGTH:
            str_upgrade++;
            break;
        case character_stat::DEXTERITY:
            dex_upgrade++;
            break;
        case character_stat::INTELLIGENCE:
            int_upgrade++;
            break;
        case character_stat::PERCEPTION:
            per_upgrade++;
            break;
        case character_stat::DUMMY_STAT:
            debugmsg( "Tried to use invalid stat" );
            break;
    }
    recalc_hp();
}
References debugmsg, dex_upgrade, DEXTERITY, DUMMY_STAT, int_upgrade, INTELLIGENCE, per_upgrade, PERCEPTION, Character::recalc_hp(), str_upgrade, and STRENGTH.
Referenced by character_display::upgrade_stat_prompt().
vomit()
void avatar::vomit ()
Handles player vomiting effects.
Definition at line 979 of file avatar.cpp.
{
    if( stomach.get_calories() > 0 ) {
        // Remove all joy from previously eaten food and apply the penalty
        rem_morale( MORALE_FOOD_GOOD );
        rem_morale( MORALE_FOOD_HOT );
        // bears must suffer too
        rem_morale( MORALE_HONEY );
        // 1.5 times longer
        add_morale( MORALE_VOMITED, -20, -40, 90_minutes, 45_minutes, false );
    } else {
        add_msg( m_warning, _( "You retched, but your stomach is empty." ) );
    }
    Character::vomit();
}
References _, Character::add_morale(), add_msg(), stomach_contents::get_calories(), m_warning, MORALE_FOOD_GOOD, MORALE_FOOD_HOT, MORALE_HONEY, MORALE_VOMITED, Character::rem_morale(), Character::stomach, and Character::vomit().
wake_up()
void avatar::wake_up ()
Definition at line 958 of file avatar.cpp.
{
    if( has_effect( effect_sleep ) ) {
        if( calendar::turn - get_effect( effect_sleep ).get_start_time() > 2_hours ) {
            print_health();
        }
        // alarm was set and player hasn't slept through the alarm.
        if( has_effect( effect_alarm_clock ) && !has_effect( effect_slept_through_alarm ) ) {
            add_msg( _( "It looks like you woke up before your alarm." ) );
            remove_effect( effect_alarm_clock );
        } else if( has_effect( effect_slept_through_alarm ) ) {
            if( has_bionic( bio_watch ) ) {
                add_msg( m_warning, _( "It looks like you've slept through your internal alarm" ) );
            } else {
                add_msg( m_warning, _( "It looks like you've slept through the alarm" ) );
            }
        }
    }
    Character::wake_up();
}
References _, add_msg(), bio_watch, effect_alarm_clock, effect_sleep, effect_slept_through_alarm, Creature::get_effect(), Character::has_bionic(), Creature::has_effect(), m_warning, Character::print_health(), Creature::remove_effect(), calendar::turn, and Character::wake_up().
Referenced by game::monmove().
wield()
bool avatar::wield (item & target) override virtual
Removes currently wielded item (if any) and replaces it with the target item.
Parameters
target replacement item to wield or null item to remove existing weapon without replacing it
Returns
whether both removal and replacement were successful (they are performed atomically)
Implements Character.
Definition at line 1199 of file avatar.cpp.
{
    if( is_wielding( target ) ) {
        return true;
    }
    if( !can_wield( target ).success() ) {
        return false;
    }
    if( !unwield() ) {
        return false;
    }
    clear_npc_ai_info_cache( "weapon_value" );
    if( target.is_null() ) {
        return true;
    }
    // Query whether to draw an item from a holster when attempting to wield the holster
    if( target.get_use( "holster" ) && !target.contents.empty() ) {
        //~ %1$s: weapon name, %2$s: holster name
        if( query_yn( pgettext( "holster", "Draw %1$s from %2$s?" ), target.get_contained().tname(),
                      target.tname() ) ) {
            invoke_item( &target );
            return false;
        }
    }
    // Wielding from inventory is relatively slow and does not improve with increasing weapon skill.
    // Worn items (including guns with shoulder straps) are faster but still slower
    // than a skilled player with a holster.
    // There is an additional penalty when wielding items from the inventory whilst currently grabbed.
    bool worn = is_worn( target );
    int mv = item_handling_cost( target, true,
                                 worn ? INVENTORY_HANDLING_PENALTY / 2 : INVENTORY_HANDLING_PENALTY );
    add_msg( m_debug, "wielding took %d moves", mv );
    moves -= mv;
    if( has_item( target ) ) {
        weapon = i_rem( &target );
    } else {
        weapon = target;
    }
    last_item = weapon.typeId();
    recoil = MAX_RECOIL;
    weapon.on_wield( *this, mv );
    inv.update_invlet( weapon );
    inv.update_cache_with_item( weapon );
    return true;
}
References add_msg(), Character::can_wield(), Character::clear_npc_ai_info_cache(), item::contents, item_contents::empty(), item::get_contained(), item::get_use(), visitable< Character >::has_item(), Character::i_rem(), Character::inv, INVENTORY_HANDLING_PENALTY, invoke_item(), item::is_null(), Character::is_wielding(), Character::is_worn(), Character::item_handling_cost(), Character::last_item, m_debug, MAX_RECOIL, Creature::moves, item::on_wield(), pgettext(), player::query_yn(), Character::recoil, behavior::success, item::tname(), item::typeId(), Character::unwield(), inventory::update_cache_with_item(), inventory::update_invlet(), Character::weapon, and Character::worn.
Referenced by create(), fire(), avatar_action::plthrow(), avatar_funcs::try_disarm_npc(), and avatar_action::wield().
Friends And Related Function Documentation
debug_menu::mission_debug
friend class debug_menu::mission_debug friend
Definition at line 226 of file avatar.h.
Member Data Documentation
a_diary
std::unique_ptr<diary> avatar::a_diary private
Diary to track player progression and to write the player's story.
Definition at line 235 of file avatar.h.
Referenced by avatar(), and get_avatar_diary().
active_mission
mission* avatar::active_mission = nullptr private
The currently active mission, or null if no mission is currently in progress.
Definition at line 247 of file avatar.h.
Referenced by avatar(), get_active_mission(), get_active_mission_target(), load(), on_mission_finished(), reset_all_misions(), set_active_mission(), and store().
active_missions
std::vector<mission *> avatar::active_missions private
Missions that the player has accepted and that are not finished (one way or the other).
Definition at line 231 of file avatar.h.
Referenced by get_active_missions(), load(), on_mission_assignment(), on_mission_finished(), reset_all_misions(), set_active_mission(), and store().
completed_missions
std::vector<mission *> avatar::completed_missions private
Missions that the player has successfully completed.
Definition at line 239 of file avatar.h.
Referenced by get_completed_missions(), load(), on_mission_finished(), reset_all_misions(), and store().
dex_upgrade
int avatar::dex_upgrade = 0 private
Definition at line 257 of file avatar.h.
Referenced by free_upgrade_points(), get_dex_base(), load(), store(), and upgrade_stat().
dialogue_by_radio
bool avatar::dialogue_by_radio = false
Definition at line 189 of file avatar.h.
Referenced by npc::talk_to_u().
failed_missions
std::vector<mission *> avatar::failed_missions private
Missions that have failed while being assigned to the player.
Definition at line 243 of file avatar.h.
Referenced by get_failed_missions(), load(), on_mission_finished(), reset_all_misions(), and store().
grab_type
object_type avatar::grab_type = OBJECT_NONE private
Definition at line 252 of file avatar.h.
Referenced by avatar(), get_grab_type(), grab(), and store().
int_upgrade
int avatar::int_upgrade = 0 private
Definition at line 258 of file avatar.h.
Referenced by free_upgrade_points(), get_int_base(), load(), store(), and upgrade_stat().
items_identified
std::unordered_set<itype_id> avatar::items_identified private
Definition at line 250 of file avatar.h.
Referenced by create(), do_read(), has_identified(), load(), read(), and store().
mon_visible
monster_visible_info avatar::mon_visible private
Definition at line 261 of file avatar.h.
Referenced by get_mon_visible().
per_upgrade
int avatar::per_upgrade = 0 private
Definition at line 259 of file avatar.h.
Referenced by free_upgrade_points(), get_per_base(), load(), store(), and upgrade_stat().
player_map_memory
std::unique_ptr<map_memory> avatar::player_map_memory private
Definition at line 223 of file avatar.h.
Referenced by avatar(), clear_memorized_tile(), get_memorized_symbol(), get_memorized_tile(), has_memorized_tile_for_autodrive(), load_map_memory(), memorize_symbol(), memorize_tile(), prepare_map_memory_region(), and save_map_memory().
preferred_aiming_mode
std::string avatar::preferred_aiming_mode
Definition at line 191 of file avatar.h.
Referenced by target_ui::action_switch_mode(), target_ui::init_window_and_input(), load(), and store().
show_map_memory
bool avatar::show_map_memory = true private
Definition at line 224 of file avatar.h.
Referenced by avatar(), load(), should_show_map_memory(), store(), and toggle_map_memory().
str_upgrade
int avatar::str_upgrade = 0 private
Definition at line 256 of file avatar.h.
Referenced by free_upgrade_points(), get_str_base(), load(), store(), and upgrade_stat().
translocators
pimpl<teleporter_list> avatar::translocators
Definition at line 171 of file avatar.h.
Referenced by load(), store(), spell_effect::translocate(), and iexamine::translocator().
warning_record
std::map<faction_id, std::pair<int, time_point> > avatar::warning_record private
Warnings from factions about bad behavior.
Definition at line 264 of file avatar.h.
Referenced by add_faction_warning(), load(), and store().
The documentation for this class was generated from the following files:
src/avatar.h
src/avatar.cpp
src/newcharacter.cpp
src/savegame_json.cpp