Cataclysm BN: detail::utf8_to_utf16 Class Reference
detail::utf8_to_utf16 Class Reference
#include <fmtlib_format.h>
Public Member Functions
FMT_API utf8_to_utf16 (string_view s)
operator wstring_view () const
size_t size () const
const wchar_t * c_str () const
std::wstring str () const
Private Attributes
wmemory_buffer buffer_
Detailed Description
Definition at line 1292 of file fmtlib_format.h.
Constructor & Destructor Documentation
utf8_to_utf16()
FMT_FUNC detail::utf8_to_utf16::utf8_to_utf16 (string_view s) explicit
Definition at line 2920 of file fmtlib_format-inl.h.
{
    auto transcode = [this]( const char *p ) {
        auto cp = uint32_t();
        auto error = 0;
        p = utf8_decode( p, &cp, &error );
        if( error != 0 ) {
            FMT_THROW( std::runtime_error( "invalid utf8" ) );
        }
        if( cp <= 0xFFFF ) {
            buffer_.push_back( static_cast<wchar_t>( cp ) );
        } else {
            cp -= 0x10000;
            buffer_.push_back( static_cast<wchar_t>( 0xD800 + ( cp >> 10 ) ) );
            buffer_.push_back( static_cast<wchar_t>( 0xDC00 + ( cp & 0x3FF ) ) );
        }
        return p;
    };
    auto p = s.data();
    const size_t block_size = 4;  // utf8_decode always reads blocks of 4 chars.
    if( s.size() >= block_size ) {
        for( auto end = p + s.size() - block_size + 1; p < end; ) {
            p = transcode( p );
        }
    }
    if( auto num_chars_left = s.data() + s.size() - p ) {
        char buf[2 * block_size - 1] = {};
        memcpy( buf, p, to_unsigned( num_chars_left ) );
        p = buf;
        do {
            p = transcode( p );
        } while( p - buf < num_chars_left );
    }
    buffer_.push_back( 0 );
}
References buffer_, basic_string_view< Char >::data(), detail::digits::error, FMT_THROW, detail::buffer< T >::push_back(), basic_string_view< Char >::size(), detail::to_unsigned(), and detail::utf8_decode().
Member Function Documentation
c_str()
const wchar_t * detail::utf8_to_utf16::c_str () const inline
Definition at line 1305 of file fmtlib_format.h.
{
            return &buffer_[0];
        }
Referenced by vprint().
operator wstring_view()
detail::utf8_to_utf16::operator wstring_view () const inline
Definition at line 1299 of file fmtlib_format.h.
{
            return {&buffer_[0], size()};
        }
References om_direction::size.
size()
size_t detail::utf8_to_utf16::size () const inline
Definition at line 1302 of file fmtlib_format.h.
{
            return buffer_.size() - 1;
        }
References detail::buffer< T >::size().
Referenced by vprint().
str()
std::wstring detail::utf8_to_utf16::str () const inline
Definition at line 1308 of file fmtlib_format.h.
{
            return {&buffer_[0], size()};
        }
References om_direction::size.
Member Data Documentation
buffer_
wmemory_buffer detail::utf8_to_utf16::buffer_ private
Definition at line 1295 of file fmtlib_format.h.
Referenced by utf8_to_utf16().
The documentation for this class was generated from the following files:
src/fmtlib_format.h
src/fmtlib_format-inl.h