Cataclysm BN: update_mapgen_function_json Class Reference
update_mapgen_function_json Class Reference
#include <mapgen.h>
Public Member Functions
update_mapgen_function_json (const json_source_location &jsrcloc)
~update_mapgen_function_json () override=default
void setup ()
bool setup_update (const JsonObject &jo)
void check (const std::string &oter_name) const
bool update_map (const tripoint_abs_omt &omt_pos, const point &offset, mission *miss, bool verify=false) const
bool update_map (mapgendata &md, const point &offset=point_zero, bool verify=false) const
Public Member Functions inherited from mapgen_function_json_base
bool check_inbounds (const jmapgen_int &x, const jmapgen_int &y, const JsonObject &jso) const
size_t calc_index (const point &p) const
bool has_vehicle_collision (mapgendata &dat, const point &offset) const
Protected Member Functions
bool setup_internal (const JsonObject &) override
Protected Member Functions inherited from mapgen_function_json_base
mapgen_function_json_base (const json_source_location &jsrcloc)
virtual ~mapgen_function_json_base ()
void setup_common ()
bool setup_common (const JsonObject &jo)
void setup_setmap (const JsonArray &parray)
virtual void setup_setmap_internal ()
void check_common (const std::string &oter_name) const
void formatted_set_incredibly_simple (map &m, const point &offset) const
Protected Attributes
ter_id fill_ter
Protected Attributes inherited from mapgen_function_json_base
bool do_format
bool is_ready
point mapgensize
point m_offset
std::vector< ter_furn_id > format
std::vector< jmapgen_setmap > setmap_points
jmapgen_objects objects
Detailed Description
Definition at line 366 of file mapgen.h.
Constructor & Destructor Documentation
update_mapgen_function_json()
update_mapgen_function_json::update_mapgen_function_json (const json_source_location & jsrcloc) explicit
Definition at line 6513 of file mapgen.cpp.
                                                                                              :
    mapgen_function_json_base( jsrcloc )
{
}
~update_mapgen_function_json()
update_mapgen_function_json::~update_mapgen_function_json () override default
Member Function Documentation
check()
void update_mapgen_function_json::check (const std::string & oter_name) const
Definition at line 6518 of file mapgen.cpp.
{
    check_common( oter_name );
}
References mapgen_function_json_base::check_common().
setup()
void update_mapgen_function_json::setup ()
Definition at line 2360 of file mapgen.cpp.
{
    setup_common();
}
References mapgen_function_json_base::setup_common().
setup_internal()
bool update_mapgen_function_json::setup_internal (const JsonObject &) override protected virtual
Implements mapgen_function_json_base.
Definition at line 6528 of file mapgen.cpp.
{
    fill_ter = t_null;
    /* update_mapgen doesn't care about fill_ter or rows */
    return true;
}
References fill_ter, and t_null.
setup_update()
bool update_mapgen_function_json::setup_update (const JsonObject & jo)
Definition at line 6523 of file mapgen.cpp.
{
    return setup_common( jo );
}
References mapgen_function_json_base::setup_common().
update_map() [1/2]
bool update_mapgen_function_json::update_map (const tripoint_abs_omt & omt_pos, const point & offset, mission * miss, bool verify = false) const
Definition at line 6535 of file mapgen.cpp.
{
    if( omt_pos == overmap::invalid_tripoint ) {
        debugmsg( "Mapgen update function called with overmap::invalid_tripoint" );
        return false;
    }
    tinymap update_tmap;
    // TODO: fix point types
    const tripoint sm_pos = project_to<coords::sm>( omt_pos ).raw();
    update_tmap.load( sm_pos, true );
    mapgendata md( omt_pos, update_tmap, 0.0f, calendar::start_of_cataclysm, miss );
    return update_map( md, offset, verify );
}
References debugmsg, overmap::invalid_tripoint, map::load(), calendar::start_of_cataclysm, and update_map().
Referenced by update_map().
update_map() [2/2]
bool update_mapgen_function_json::update_map (mapgendata & md, const point & offset = point_zero, bool verify = false) const
Definition at line 6552 of file mapgen.cpp.
{
    class rotation_guard
    {
        public:
            rotation_guard( const mapgendata &md )
                : md( md ), rotation( oter_get_rotations( md.terrain_type() ) ) {
                // If the existing map is rotated, we need to rotate it back to the north
                // orientation before applying our updates.
                if( rotation != 0 ) {
                    md.m.rotate( 4 - rotation, true );
                }
            }
            ~rotation_guard() {
                // If we rotated the map before applying updates, we now need to rotate
                // it back to where we found it.
                if( rotation != 0 ) {
                    md.m.rotate( rotation, true );
                }
            }
        private:
            const mapgendata &md;
            const int rotation;
    };
    rotation_guard rot( md );
    for( auto &elem : setmap_points ) {
        if( verify && elem.has_vehicle_collision( md, offset ) ) {
            return false;
        }
        elem.apply( md, offset );
    }
    if( verify && objects.has_vehicle_collision( md, offset ) ) {
        return false;
    }
    objects.apply( md, offset );
    resolve_regional_terrain_and_furniture( md );
    return true;
}
References jmapgen_objects::apply(), jmapgen_objects::has_vehicle_collision(), mapgendata::m, mapgen_function_json_base::objects, oter_get_rotations(), resolve_regional_terrain_and_furniture(), map::rotate(), mapgen_function_json_base::setmap_points, and mapgendata::terrain_type().
Member Data Documentation
fill_ter
ter_id update_mapgen_function_json::fill_ter protected
Definition at line 382 of file mapgen.h.
Referenced by setup_internal().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp