Cataclysm BN: fault Class Reference
fault Class Reference
#include <fault.h>
Public Member Functions
fault ()
const fault_id & id () const
bool is_null () const
std::string name () const
std::string description () const
const std::map< std::string, mending_method > & mending_methods () const
const mending_method * find_mending_method (const std::string &id) const
bool has_flag (const std::string &flag) const
Static Public Member Functions
static void load_fault (const JsonObject &jo)
Load fault from JSON definition.
static const std::map< fault_id, fault > & all ()
Get all currently loaded faults.
static void reset ()
Clear all loaded faults (invalidating any pointers)
static void check_consistency ()
Checks all loaded from JSON are valid.
Private Attributes
fault_id id_
translation name_
translation description_
std::map< std::string, mending_method > mending_methods_
std::set< std::string > flags
Detailed Description
Definition at line 28 of file fault.h.
Constructor & Destructor Documentation
fault()
fault::fault () inline
Definition at line 31 of file fault.h.
: id_(fault_id("null")) {}
Member Function Documentation
all()
const std::map< fault_id, fault > & fault::all () static
Get all currently loaded faults.
Definition at line 80 of file fault.cpp.
{
    return faults_all;
}
References faults_all.
check_consistency()
void fault::check_consistency () static
Checks all loaded from JSON are valid.
Definition at line 90 of file fault.cpp.
{
    for( const auto &f : faults_all ) {
        for( const auto &m : f.second.mending_methods_ ) {
            if( !m.second.requirements.is_valid() ) {
                debugmsg( "fault %s has invalid requirement id %s for mending method %s",
                          f.second.id_.str(), m.second.requirements.str(), m.first );
            }
            if( m.second.time < 0_turns ) {
                debugmsg( "fault %s requires negative mending time for mending method %s",
                          f.second.id_.str(), m.first );
            }
            for( const auto &sk : m.second.skills ) {
                if( !sk.first.is_valid() ) {
                    debugmsg( "fault %s requires unknown skill %s for mending method %s",
                              f.second.id_.str(), sk.first.str(), m.first );
                }
                if( sk.second <= 0 ) {
                    debugmsg( "fault %s requires non-positive level of skill %s for mending method %s",
                              f.second.id_.str(), sk.first.str(), m.first );
                }
            }
            if( m.second.turns_into && !m.second.turns_into->is_valid() ) {
                debugmsg( "fault %s has invalid turns_into fault id %s for mending method %s",
                          f.second.id_.str(), m.second.turns_into->str(), m.first );
            }
            if( m.second.also_mends && !m.second.also_mends->is_valid() ) {
                debugmsg( "fault %s has invalid also_mends fault id %s for mending method %s",
                          f.second.id_.str(), m.second.also_mends->str(), m.first );
            }
        }
    }
}
References debugmsg, and faults_all.
Referenced by DynamicDataLoader::check_consistency().
description()
std::string fault::description () const inline
Definition at line 45 of file fault.h.
{
            return description_.translated();
        }
References description_, and translation::translated().
find_mending_method()
const mending_method * fault::find_mending_method (const std::string & id) const inline
Definition at line 53 of file fault.h.
{
            if( mending_methods_.find( id ) != mending_methods_.end() ) {
                return &mending_methods_.at( id );
            } else {
                return nullptr;
            }
        }
References mending_methods_.
Referenced by activity_handlers::mend_item_finish().
has_flag()
bool fault::has_flag (const std::string & flag) const inline
Definition at line 61 of file fault.h.
{
            return flags.count( flag );
        }
References flags.
Referenced by item::tname().
id()
const fault_id & fault::id () const inline
Definition at line 33 of file fault.h.
{
            return id_;
        }
References id_.
is_null()
bool fault::is_null () const inline
Definition at line 37 of file fault.h.
{
            return id_ == fault_id( "null" );
        }
References id_.
load_fault()
void fault::load_fault (const JsonObject & jo) static
Load fault from JSON definition.
Definition at line 34 of file fault.cpp.
{
    fault f;
    mandatory( jo, false, "id", f.id_ );
    mandatory( jo, false, "name", f.name_ );
    mandatory( jo, false, "description", f.description_ );
    for( const JsonObject jo_method : jo.get_array( "mending_methods" ) ) {
        mending_method m;
        mandatory( jo_method, false, "id", m.id );
        optional( jo_method, false, "name", m.name, f.name_ );
        optional( jo_method, false, "description", m.description, f.description_ );
        mandatory( jo_method, false, "success_msg", m.success_msg );
        mandatory( jo_method, false, "time", m.time );
        for( const JsonObject jo_skill : jo_method.get_array( "skills" ) ) {
            skill_id sk_id;
            mandatory( jo_skill, false, "id", sk_id );
            m.skills.emplace( sk_id, jo_skill.get_int( "level" ) );
        }
        if( jo_method.has_string( "requirements" ) ) {
            mandatory( jo_method, false, "requirements", m.requirements );
        } else {
            JsonObject jo_req = jo_method.get_object( "requirements" );
            m.requirements = requirement_id( m.id );
            requirement_data::load_requirement( jo_req, m.requirements );
        }
        optional( jo_method, false, "turns_into", m.turns_into, cata::nullopt );
        optional( jo_method, false, "also_mends", m.also_mends, cata::nullopt );
        f.mending_methods_.emplace( m.id, m );
    }
    optional( jo, false, "flags", f.flags );
    if( faults_all.find( f.id_ ) != faults_all.end() ) {
        jo.throw_error( "parsed fault overwrites existing definition", "id" );
    } else {
        faults_all[f.id_] = f;
    }
}
References mending_method::also_mends, mending_method::description, description_, faults_all, flags, JsonObject::get_array(), JsonObject::get_object(), mending_method::id, id_, requirement_data::load_requirement(), mandatory(), mending_methods_, mending_method::name, name_, cata::nullopt, optional(), mending_method::requirements, mending_method::skills, mending_method::success_msg, JsonObject::throw_error(), mending_method::time, and mending_method::turns_into.
Referenced by DynamicDataLoader::initialize().
mending_methods()
const std::map< std::string, mending_method > & fault::mending_methods () const inline
Definition at line 49 of file fault.h.
{
            return mending_methods_;
        }
References mending_methods_.
Referenced by player::mend_item().
name()
std::string fault::name () const inline
Definition at line 41 of file fault.h.
{
            return name_.translated();
        }
References name_, and translation::translated().
reset()
void fault::reset () static
Clear all loaded faults (invalidating any pointers)
Definition at line 85 of file fault.cpp.
{
    faults_all.clear();
}
References faults_all.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
description_
translation fault::description_ private
Definition at line 80 of file fault.h.
Referenced by description(), and load_fault().
flags
std::set<std::string> fault::flags private
Definition at line 82 of file fault.h.
Referenced by has_flag(), and load_fault().
id_
fault_id fault::id_ private
Definition at line 78 of file fault.h.
Referenced by id(), is_null(), and load_fault().
mending_methods_
std::map<std::string, mending_method> fault::mending_methods_ private
Definition at line 81 of file fault.h.
Referenced by find_mending_method(), load_fault(), and mending_methods().
name_
translation fault::name_ private
Definition at line 79 of file fault.h.
Referenced by load_fault(), and name().
The documentation for this class was generated from the following files:
src/fault.h
src/fault.cpp