Cataclysm BN: tileray Class Reference
tileray Class Reference
#include <tileray.h>
Public Member Functions
tileray ()
tileray (const point &ad)
tileray (units::angle adir)
void init (const point &ad)
void init (units::angle adir)
int dx () const
int dy () const
units::angle dir () const
int quadrant () const
int dir4 () const
int dir8 () const
int dir_symbol (int sym) const
std::string to_string_azimuth_from_north () const
convert to a string representation of the azimuth from north, in integer degrees
int ortho_dx (int od) const
int ortho_dy (int od) const
bool mostly_vertical () const
void advance (int num=1)
void clear_advance ()
int get_steps () const
Private Attributes
point delta
int leftover = 0
point abs_d
units::angle direction = 0_degrees
point last_d
int steps = 0
bool infinite = false
Detailed Description
Definition at line 26 of file tileray.h.
Constructor & Destructor Documentation
tileray() [1/3]
tileray::tileray ()
Definition at line 13 of file tileray.cpp.
                : leftover( 0 ), direction( 0_degrees ), steps( 0 ), infinite( false )
{
}
tileray() [2/3]
tileray::tileray (const point & ad)
Definition at line 17 of file tileray.cpp.
{
    init( ad );
}
References init().
tileray() [3/3]
tileray::tileray (units::angle adir)
Definition at line 22 of file tileray.cpp.
                                 : direction( adir )
{
    init( adir );
}
References init().
Member Function Documentation
advance()
void tileray::advance (int num = 1)
Definition at line 194 of file tileray.cpp.
{
    last_d = point_zero;
    if( num == 0 ) {
        return;
    }
    int anum = std::abs( num );
    steps += anum;
    const bool vertical = mostly_vertical();
    if( abs_d.x && abs_d.y ) {
        for( int i = 0; i < anum; i++ ) {
            if( vertical ) {
                // mostly vertical line
                leftover += abs_d.x;
                if( leftover >= abs_d.y ) {
                    last_d.x++;
                    leftover -= abs_d.y;
                }
            } else {
                // mostly horizontal line
                leftover += abs_d.y;
                if( leftover >= abs_d.x ) {
                    last_d.y++;
                    leftover -= abs_d.x;
                }
            }
        }
    }
    if( vertical ) {
        last_d.y = anum;
    } else {
        last_d.x = anum;
    }
    // offset calculated for 0-90 deg quadrant, we need to adjust if direction is other
    int quadr = quadrant();
    last_d.x *= sx[quadr];
    last_d.y *= sy[quadr];
    if( num < 0 ) {
        last_d = -last_d;
    }
}
References abs_d, last_d, leftover, mostly_vertical(), num, point_zero, quadrant(), steps, sx, sy, point::x, and point::y.
Referenced by vehicle::act_on_map(), vehicle::autodrive_controller::check_collision_zone(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_profile(), game::fling_creature(), vehicle::immediate_path(), mattack::ranged_pull(), and vehicle_movement::scan_rails_at_shift().
clear_advance()
void tileray::clear_advance ()
Definition at line 57 of file tileray.cpp.
{
    leftover = 0;
    last_d = point_zero;
    steps = 0;
}
References last_d, leftover, point_zero, and steps.
dir()
units::angle tileray::dir () const
Definition at line 74 of file tileray.cpp.
{
    return direction;
}
References direction.
Referenced by vehicle::act_on_map(), vehicle::autodrive_controller::check_collision_zone(), veh_interact::complete_vehicle(), dir8(), editmap::draw_main_ui_overlay(), vehicle::face_vec(), map::generate_lightmap(), vehicle::get_debug_overlay_data(), game::grabbed_veh_move(), vehicle::immediate_path(), vehicle_movement::is_on_rails(), vehicle::merge_rackable_vehicle(), vehicle::move_vec(), map::move_vehicle(), game::moving_vehicle_dismount(), vehicle::part_collision(), vehicle_movement::process_movement_on_rails(), vehicle::remove_carried_vehicle(), vehicle::slowdown(), vehicle::split_vehicles(), vehicle::thrust(), to_string_azimuth_from_north(), and npc::vehicle_danger().
dir4()
int tileray::dir4 () const
Definition at line 84 of file tileray.cpp.
{
    if( direction >= 45_degrees && direction <= 135_degrees ) {
        return 1;
    } else if( direction > 135_degrees && direction < 225_degrees ) {
        return 2;
    } else if( direction >= 225_degrees && direction <= 315_degrees ) {
        return 3;
    } else {
        return 0;
    }
}
Referenced by dir_symbol().
dir8()
int tileray::dir8 () const
Definition at line 97 of file tileray.cpp.
{
    int oct = 0;
    units::angle dir = direction;
    if( dir < 23_degrees || dir > 337_degrees ) {
        return 0;
    }
    while( dir > 22_degrees ) {
        dir -= 45_degrees;
        oct += 1;
    }
    return oct;
}
References dir(), and direction.
Referenced by dir_symbol().
dir_symbol()
int tileray::dir_symbol (int sym) const
Definition at line 113 of file tileray.cpp.
{
    switch( sym ) {
        // output.cpp special_symbol() converts yubn to corners, hj to lines, c to cross
        case 'j':
            // vertical line
            return "h\\j/h\\j/"[dir8()];
        case 'h':
            // horizontal line
            return "jhjh"[dir4()];
        case 'y':
            // top left corner
            return "unby"[dir4()];
        case 'u':
            // top right corner
            return "nbyu"[dir4()];
        case 'n':
            // bottom right corner
            return "byun"[dir4()];
        case 'b':
            // bottom left corner
            return "yunb"[dir4()];
        case '^':
            return ">v<^"[dir4()];
        case '>':
            return "v<^>"[dir4()];
        case 'v':
            return "<^>v"[dir4()];
        case '<':
            return "^>v<"[dir4()];
        case 'c':
            // +
            return "cXcXcXcX"[dir8()];
        case 'X':
            return "XcXcXcXc"[dir8()];
        case '[':
            // [ not rotated to ] because they might represent different items
            return "-\\[/-\\[/"[dir8()];
        case ']':
            return "-\\]/-\\]/"[dir8()];
        case '|':
            return "-\\|/-\\|/"[dir8()];
        case '-':
            return "|/-\\|/-\\"[dir8()];
        case '=':
            return "H=H="[dir4()];
        case 'H':
            return "=H=H"[dir4()];
        case '\\':
            return "/-\\|/-\\|"[dir8()];
        case '/':
            return "\\|/-\\|/-"[dir8()];
        default:
            ;
    }
    return sym;
}
References dir4(), and dir8().
Referenced by map::draw_from_above(), and map::draw_maptile().
dx()
int tileray::dx () const
Definition at line 64 of file tileray.cpp.
{
    return last_d.x;
}
References last_d, and point::x.
Referenced by vehicle::act_on_map(), vehicle::autodrive_controller::check_collision_zone(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_profile(), game::fling_creature(), vehicle::immediate_path(), mattack::ranged_pull(), and vehicle_movement::scan_rails_at_shift().
dy()
int tileray::dy () const
Definition at line 69 of file tileray.cpp.
{
    return last_d.y;
}
References last_d, and point::y.
Referenced by vehicle::act_on_map(), vehicle::autodrive_controller::check_collision_zone(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_profile(), game::fling_creature(), vehicle::immediate_path(), mattack::ranged_pull(), and vehicle_movement::scan_rails_at_shift().
get_steps()
int tileray::get_steps () const
Definition at line 237 of file tileray.cpp.
{
    return steps;
}
References steps.
Referenced by make_start_node().
init() [1/2]
void tileray::init (const point & ad)
Definition at line 27 of file tileray.cpp.
{
    delta = ad;
    abs_d = delta.abs();
    if( delta == point_zero ) {
        direction = 0_degrees;
    } else {
        direction = atan2( delta );
        if( direction < 0_degrees ) {
            direction += 360_degrees;
        }
    }
    last_d = point_zero;
    steps = 0;
    infinite = false;
}
References point::abs(), abs_d, atan2(), delta, infinite, last_d, point_zero, and steps.
Referenced by vehicle::act_on_map(), game::grabbed_veh_move(), vehicle::immediate_path(), map::move_vehicle(), vehicle::pldrive(), vehicle::restore(), vehicle::selfdrive(), vehicle::set_facing(), tileray(), vehicle::vehicle(), and map::vehicle_vehicle_collision().
init() [2/2]
void tileray::init (units::angle adir)
Definition at line 44 of file tileray.cpp.
{
    leftover = 0;
    // Clamp adir to the range [0, 360)
    direction = normalize( adir );
    last_d = point_zero;
    rl_vec2d delta_f( units::cos( direction ), units::sin( direction ) );
    delta = ( delta_f * 100 ).as_point();
    abs_d = delta.abs();
    steps = 0;
    infinite = true;
}
References point::abs(), abs_d, units::cos(), delta, infinite, last_d, leftover, detail::normalize(), point_zero, units::sin(), and steps.
mostly_vertical()
bool tileray::mostly_vertical () const
Definition at line 189 of file tileray.cpp.
{
    return abs_d.x <= abs_d.y;
}
References abs_d, point::x, and point::y.
Referenced by advance(), ortho_dx(), and ortho_dy().
ortho_dx()
int tileray::ortho_dx (int od) const
Definition at line 177 of file tileray.cpp.
{
    od *= -sy[quadrant()];
    return mostly_vertical() ? od : 0;
}
References mostly_vertical(), quadrant(), and sy.
ortho_dy()
int tileray::ortho_dy (int od) const
Definition at line 183 of file tileray.cpp.
{
    od *= sx[quadrant()];
    return mostly_vertical() ? 0 : od;
}
References mostly_vertical(), quadrant(), and sx.
quadrant()
int tileray::quadrant () const
Definition at line 79 of file tileray.cpp.
{
    return static_cast<int>( std::floor( direction / 90_degrees ) ) % 4;
}
Referenced by advance(), ortho_dx(), and ortho_dy().
to_string_azimuth_from_north()
std::string tileray::to_string_azimuth_from_north () const
convert to a string representation of the azimuth from north, in integer degrees
Definition at line 172 of file tileray.cpp.
{
    return std::to_string( std::lround( to_degrees( dir() + 90_degrees ) ) % 360 ) + "";
}
References dir(), units::to_degrees(), and to_string().
Referenced by draw_health_classic(), draw_veh_compact(), and draw_veh_padding().
Member Data Documentation
abs_d
point tileray::abs_d private
Definition at line 31 of file tileray.h.
Referenced by advance(), init(), and mostly_vertical().
delta
point tileray::delta private
Definition at line 29 of file tileray.h.
Referenced by init().
direction
units::angle tileray::direction = 0_degrees private
Definition at line 32 of file tileray.h.
Referenced by dir(), and dir8().
infinite
bool tileray::infinite = false private
Definition at line 35 of file tileray.h.
Referenced by init().
last_d
point tileray::last_d private
Definition at line 33 of file tileray.h.
Referenced by advance(), clear_advance(), dx(), dy(), and init().
leftover
int tileray::leftover = 0 private
Definition at line 30 of file tileray.h.
Referenced by advance(), clear_advance(), and init().
steps
int tileray::steps = 0 private
Definition at line 34 of file tileray.h.
Referenced by advance(), clear_advance(), get_steps(), and init().
The documentation for this class was generated from the following files:
src/tileray.h
src/tileray.cpp