Cataclysm BN: om_noise::om_noise_layer Class Reference
om_noise::om_noise_layer Class Reference abstract
Abstract base class for generating noise for usage in overmap generation.
#include <overmap_noise.h>
Public Member Functions
virtual float noise_at (const point_om_omt &omt_local) const =0
Noise value at the provided overmap terrain location.
virtual ~om_noise_layer ()=default
Protected Member Functions
om_noise_layer (const point_abs_omt &global_base_point, const unsigned seed)
Providing the global base point of the overmap and a common seed across overmaps will ensure that the noise is continuous across overmap boundaries.
point_abs_omt global_omt_pos (const point_om_omt &local_omt_pos) const
float get_seed () const
Private Attributes
point_abs_omt om_global_base_point
float seed
Detailed Description
Abstract base class for generating noise for usage in overmap generation.
Subclass it and implement noise_at.
Definition at line 16 of file overmap_noise.h.
Constructor & Destructor Documentation
~om_noise_layer()
virtual om_noise::om_noise_layer::~om_noise_layer () virtual default
om_noise_layer()
om_noise::om_noise_layer::om_noise_layer (const point_abs_omt & global_base_point, const unsigned seed) inline protected
Providing the global base point of the overmap and a common seed across overmaps will ensure that the noise is continuous across overmap boundaries.
Parameters
global_base_point the (0, 0) corner of the overmap in global coordinates.
seed the seed to use for seeding the noise–conventionally the game's seed.
Definition at line 32 of file overmap_noise.h.
                                                                                      :
            om_global_base_point( global_base_point ),
            // Narrowing conversion into float, as the noise functions we use only accept floats.
            seed( seed % SIMPLEX_NOISE_RANDOM_SEED_LIMIT ) {
        }
Member Function Documentation
get_seed()
float om_noise::om_noise_layer::get_seed () const inline protected
Definition at line 42 of file overmap_noise.h.
{
            return seed;
        }
References seed.
Referenced by om_noise::om_noise_layer_forest::noise_at(), om_noise::om_noise_layer_floodplain::noise_at(), and om_noise::om_noise_layer_lake::noise_at().
global_omt_pos()
point_abs_omt om_noise::om_noise_layer::global_omt_pos (const point_om_omt & local_omt_pos) const inline protected
Definition at line 38 of file overmap_noise.h.
{
            return om_global_base_point + local_omt_pos.raw();
        }
References om_global_base_point, and coords::coord_point< Point, Origin, Scale >::raw().
Referenced by om_noise::om_noise_layer_forest::noise_at(), om_noise::om_noise_layer_floodplain::noise_at(), and om_noise::om_noise_layer_lake::noise_at().
noise_at()
virtual float om_noise::om_noise_layer::noise_at (const point_om_omt & omt_local) const pure virtual
Noise value at the provided overmap terrain location.
Parameters
omt_local point location in overmap terrain local coordinates.
Implemented in om_noise::om_noise_layer_forest, om_noise::om_noise_layer_floodplain, and om_noise::om_noise_layer_lake.
Member Data Documentation
om_global_base_point
point_abs_omt om_noise::om_noise_layer::om_global_base_point private
Definition at line 47 of file overmap_noise.h.
Referenced by global_omt_pos().
seed
float om_noise::om_noise_layer::seed private
Definition at line 48 of file overmap_noise.h.
Referenced by get_seed().
The documentation for this class was generated from the following file:
src/overmap_noise.h