Cataclysm BN: charge_watcher_tile Class Reference
charge_watcher_tile Class Reference
#include <active_tile_data_def.h>
Public Member Functions
void update_internal (time_point to, const tripoint_abs_ms &p, distribution_grid &grid) override
active_tile_data * clone () const override
const std::string & get_type () const override
void store (JsonOut &jsout) const override
void load (JsonObject &jo) override
Public Member Functions inherited from active_tile_data
void update (time_point to, const tripoint_abs_ms &p, distribution_grid &grid)
time_point get_last_updated ()
void set_last_updated (time_point t)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
virtual ~active_tile_data ()
Public Attributes
int min_power
active_tiles::furn_transform transform
Additional Inherited Members
Static Public Member Functions inherited from active_tile_data
static active_tile_data * create (const std::string &id)
Detailed Description
Definition at line 37 of file active_tile_data_def.h.
Member Function Documentation
clone()
active_tile_data * charge_watcher_tile::clone () const override virtual
Implements active_tile_data.
Definition at line 223 of file active_tile_data.cpp.
{
    return new charge_watcher_tile( *this );
}
get_type()
const std::string & charge_watcher_tile::get_type () const override virtual
Implements active_tile_data.
Definition at line 228 of file active_tile_data.cpp.
{
    static const std::string type( "charge_watcher" );
    return type;
}
References type.
load()
void charge_watcher_tile::load (JsonObject & jo) override virtual
Implements active_tile_data.
Definition at line 240 of file active_tile_data.cpp.
{
    jo.read( "min_power", min_power );
    jo.read( "transform", transform );
}
References min_power, JsonObject::read(), and transform.
store()
void charge_watcher_tile::store (JsonOut & jsout) const override virtual
Implements active_tile_data.
Definition at line 234 of file active_tile_data.cpp.
{
    jsout.member( "min_power", min_power );
    jsout.member( "transform", transform );
}
References JsonOut::member(), min_power, and transform.
update_internal()
void charge_watcher_tile::update_internal (time_point to, const tripoint_abs_ms & p, distribution_grid & grid) override virtual
Parameters
to the time to update to
p absolute map coordinates (map::getabs) of the tile being updated
grid distribution grid being updated, containing the tile being updated
Implements active_tile_data.
Definition at line 213 of file active_tile_data.cpp.
{
    int amt_stored = grid.get_resource();
    if( amt_stored >= min_power ) {
        get_distribution_grid_tracker().get_transform_queue().add( p, transform.id, transform.msg );
    }
}
References grid_furn_transform_queue::add(), get_distribution_grid_tracker(), distribution_grid::get_resource(), distribution_grid_tracker::get_transform_queue(), active_tiles::furn_transform::id, min_power, active_tiles::furn_transform::msg, and transform.
Member Data Documentation
min_power
int charge_watcher_tile::min_power
Definition at line 41 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
transform
active_tiles::furn_transform charge_watcher_tile::transform
Definition at line 42 of file active_tile_data_def.h.
Referenced by load(), store(), and update_internal().
The documentation for this class was generated from the following files:
src/active_tile_data_def.h
src/active_tile_data.cpp