Cataclysm BN: item_location::impl::item_in_container Class Reference
item_location::impl::item_in_container Class Reference
Public Member Functions
item_location parent_item () const override
item_in_container (const item_location &container, item *which)
void serialize (JsonOut &js) const override
item * unpack (int idx) const override
std::string describe (const Character *) const override
type where () const override
tripoint position () const override
void remove_item () override
item_location obtain (Character &ch, int qty) override
int obtain_cost (const Character &ch, int qty) const override
void make_dirty () override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
item * target () const
virtual bool valid () const
Private Member Functions
int calc_index () const
Private Attributes
item_location container
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 517 of file item_location.cpp.
Constructor & Destructor Documentation
item_in_container()
item_location::impl::item_in_container::item_in_container (const item_location & container, item * which) inline
Definition at line 542 of file item_location.cpp.
                                                                         :
            impl( which ), container( container ) {}
Member Function Documentation
calc_index()
int item_location::impl::item_in_container::calc_index () const inline private
Definition at line 524 of file item_location.cpp.
{
            int idx = 0;
            for( const item *it : container->contents.all_items_top() ) {
                if( target() == it ) {
                    return idx;
                }
                idx++;
            }
            if( container->contents.empty() ) {
                return -1;
            }
            return idx;
        }
References item_contents::all_items_top(), container, item::contents, item_contents::empty(), item_location::impl::idx, and item_location::impl::target().
Referenced by serialize().
describe()
std::string item_location::impl::item_in_container::describe (const Character *) const inline override virtual
Implements item_location::impl.
Definition at line 567 of file item_location.cpp.
{
            if( !target() ) {
                return std::string();
            }
            return string_format( _( "inside %s" ), container->tname() );
        }
References _, container, string_format(), item_location::impl::target(), and item::tname().
make_dirty()
void item_location::impl::item_in_container::make_dirty () inline override virtual
Implements item_location::impl.
Definition at line 607 of file item_location.cpp.
{
            needs_unpacking = true;
            idx = 0;
            for( const item *it : container->contents.all_items_top() ) {
                if( what.get() == it ) {
                    return;
                }
                idx++;
            }
            if( container->contents.empty() ) {
                idx = -1;
            }
        }
References item_contents::all_items_top(), container, item::contents, item_contents::empty(), item_location::impl::idx, item_location::impl::needs_unpacking, and item_location::impl::what.
obtain()
item_location item_location::impl::item_in_container::obtain (Character & ch, int qty) inline override virtual
Implements item_location::impl.
Definition at line 586 of file item_location.cpp.
{
            ch.mod_moves( -obtain_cost( ch, qty ) );
            item obj = target()->split( qty );
            if( !obj.is_null() ) {
                return item_location( ch, &ch.i_add( obj, should_stack ) );
            } else {
                item *inv = &ch.i_add( *target(), should_stack );
                remove_item();
                return item_location( ch, inv );
            }
        }
References Character::i_add(), item::is_null(), item_location::item_location(), Creature::mod_moves(), obtain_cost(), remove_item(), item_location::impl::should_stack, item::split(), and item_location::impl::target().
obtain_cost()
int item_location::impl::item_in_container::obtain_cost (const Character & ch, int qty) const inline override virtual
Implements item_location::impl.
Definition at line 599 of file item_location.cpp.
{
            if( !target() ) {
                return 0;
            }
            return INVENTORY_HANDLING_PENALTY + container.obtain_cost( ch, qty );
        }
References container, INVENTORY_HANDLING_PENALTY, item_location::obtain_cost(), and item_location::impl::target().
Referenced by obtain().
parent_item()
item_location item_location::impl::item_in_container::parent_item () const inline override virtual
Reimplemented from item_location::impl.
Definition at line 538 of file item_location.cpp.
{
            return container;
        }
References container.
position()
tripoint item_location::impl::item_in_container::position () const inline override virtual
Implements item_location::impl.
Definition at line 578 of file item_location.cpp.
{
            return container.position();
        }
References container, and item_location::position().
remove_item()
void item_location::impl::item_in_container::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 582 of file item_location.cpp.
{
            container->remove_item( *target() );
        }
References container, visitable< T >::remove_item(), and item_location::impl::target().
Referenced by obtain().
serialize()
void item_location::impl::item_in_container::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 545 of file item_location.cpp.
{
            js.start_object();
            js.member( "idx", calc_index() );
            js.member( "type", "in_container" );
            js.member( "parent", container );
            js.end_object();
        }
References calc_index(), container, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
unpack()
item * item_location::impl::item_in_container::unpack (int idx) const inline override virtual
Implements item_location::impl.
Definition at line 553 of file item_location.cpp.
{
            if( idx < 0 || static_cast<size_t>( idx ) >= target()->contents.num_item_stacks() ) {
                return nullptr;
            }
            std::list<const item *> all_items = container->contents.all_items_ptr();
            auto iter = all_items.begin();
            std::advance( iter, idx );
            if( iter != all_items.end() ) {
                return const_cast<item *>( *iter );
            } else {
                return nullptr;
            }
        }
References item_contents::all_items_ptr(), container, item::contents, item_location::impl::idx, and item_location::impl::target().
where()
type item_location::impl::item_in_container::where () const inline override virtual
Implements item_location::impl.
Definition at line 574 of file item_location.cpp.
{
            return type::container;
        }
References item_location::container.
Member Data Documentation
container
item_location item_location::impl::item_in_container::container private
Definition at line 520 of file item_location.cpp.
Referenced by calc_index(), describe(), make_dirty(), obtain_cost(), parent_item(), position(), remove_item(), serialize(), and unpack().
The documentation for this class was generated from the following file:
src/item_location.cpp