Cataclysm BN: detail::iterator_buffer< OutputIt, T, Traits > Class Template Reference
detail::iterator_buffer< OutputIt, T, Traits > Class Template Reference final
#include <fmtlib_core.h>
Public Member Functions
iterator_buffer (OutputIt out, size_t n=buffer_size)
~iterator_buffer ()
OutputIt out ()
size_t count () const
Public Member Functions inherited from detail::buffer_traits
buffer_traits (size_t)
size_t count () const
size_t limit (size_t size)
Public Member Functions inherited from detail::buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
T * begin () FMT_NOEXCEPT
T * end () FMT_NOEXCEPT
const T * begin () const FMT_NOEXCEPT
const T * end () const FMT_NOEXCEPT
size_t size () const FMT_NOEXCEPT
Returns the size of this buffer.
size_t capacity () const FMT_NOEXCEPT
Returns the capacity of this buffer.
T * data () FMT_NOEXCEPT
Returns a pointer to the buffer data.
const T * data () const FMT_NOEXCEPT
Returns a pointer to the buffer data.
void clear ()
Clears this buffer.
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename I >
T & operator[] (I index)
template<typename I >
const T & operator[] (I index) const
Protected Member Functions
void grow (size_t) final FMT_OVERRIDE
Increases the buffer capacity to hold at least capacity elements.
void flush ()
Protected Member Functions inherited from detail::buffer< T >
buffer (size_t sz) FMT_NOEXCEPT
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
~buffer ()=default
void set (T *buf_data, size_t buf_capacity) FMT_NOEXCEPT
Sets the buffer data and capacity.
Private Types
enum { buffer_size = 256 }
Private Attributes
OutputIt out_
T data_ [buffer_size]
Additional Inherited Members
Public Types inherited from detail::buffer< T >
using value_type = T
using const_reference = const T &
Detailed Description
template<typename OutputIt, typename T, typename Traits = buffer_traits>
class detail::iterator_buffer< OutputIt, T, Traits >
Definition at line 842 of file fmtlib_core.h.
Member Enumeration Documentation
anonymous enum
template<typename OutputIt , typename T , typename Traits = buffer_traits> anonymous enum private
Enumerator
buffer_size
Definition at line 846 of file fmtlib_core.h.
{ buffer_size = 256 };
Constructor & Destructor Documentation
iterator_buffer()
template<typename OutputIt , typename T , typename Traits = buffer_traits> detail::iterator_buffer< OutputIt, T, Traits >::iterator_buffer (OutputIt out, size_t n = buffer_size) inline explicit
Definition at line 859 of file fmtlib_core.h.
            : Traits( n ),
              buffer<T>( data_, 0, buffer_size ),
              out_( out ) {}
~iterator_buffer()
template<typename OutputIt , typename T , typename Traits = buffer_traits> detail::iterator_buffer< OutputIt, T, Traits >::~iterator_buffer () inline
Definition at line 863 of file fmtlib_core.h.
{
            flush();
        }
References detail::iterator_buffer< OutputIt, T, Traits >::flush().
Member Function Documentation
count()
template<typename OutputIt , typename T , typename Traits = buffer_traits> size_t detail::iterator_buffer< OutputIt, T, Traits >::count () const inline
Definition at line 871 of file fmtlib_core.h.
{
            return Traits::count() + this->size();
        }
References detail::count(), and detail::buffer< T >::size().
Referenced by vformat_to_n().
flush()
template<typename OutputIt , typename T , typename Traits > void detail::iterator_buffer< OutputIt, T, Traits >::flush protected
Definition at line 698 of file fmtlib_format.h.
{
    out_ = std::copy_n( data_, this->limit( this->size() ), out_ );
    this->clear();
}
References catacurses::clear(), and om_direction::size.
Referenced by detail::iterator_buffer< OutputIt, T, Traits >::grow(), detail::iterator_buffer< OutputIt, T, Traits >::out(), and detail::iterator_buffer< OutputIt, T, Traits >::~iterator_buffer().
grow()
template<typename OutputIt , typename T , typename Traits = buffer_traits> void detail::iterator_buffer< OutputIt, T, Traits >::grow (size_t capacity) inline final protected virtual
Increases the buffer capacity to hold at least capacity elements.
Implements detail::buffer< T >.
Definition at line 851 of file fmtlib_core.h.
{
            if( this->size() == buffer_size ) {
                flush();
            }
        }
References detail::iterator_buffer< OutputIt, T, Traits >::buffer_size, detail::iterator_buffer< OutputIt, T, Traits >::flush(), and detail::buffer< T >::size().
out()
template<typename OutputIt , typename T , typename Traits = buffer_traits> OutputIt detail::iterator_buffer< OutputIt, T, Traits >::out () inline
Definition at line 867 of file fmtlib_core.h.
                       {
            flush();
            return out_;
        }
References detail::iterator_buffer< OutputIt, T, Traits >::flush(), and detail::iterator_buffer< OutputIt, T, Traits >::out_.
Referenced by vformat_to_n().
Member Data Documentation
data_
template<typename OutputIt , typename T , typename Traits = buffer_traits> T detail::iterator_buffer< OutputIt, T, Traits >::data_[buffer_size] private
Definition at line 847 of file fmtlib_core.h.
out_
template<typename OutputIt , typename T , typename Traits = buffer_traits> OutputIt detail::iterator_buffer< OutputIt, T, Traits >::out_ private
Definition at line 845 of file fmtlib_core.h.
Referenced by detail::iterator_buffer< OutputIt, T, Traits >::out().
The documentation for this class was generated from the following files:
src/fmtlib_core.h
src/fmtlib_format.h