Cataclysm BN: dynamic_formatter< Char > Class Template Reference
dynamic_formatter< Char > Class Template Reference
#include <fmtlib_format.h>
Classes
struct null_handler
Public Member Functions
template<typename ParseContext >
auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename T , typename FormatContext >
auto format (const T &val, FormatContext &ctx) -> decltype(ctx.out())
Private Member Functions
template<typename Context >
void handle_specs (Context &ctx)
Private Attributes
detail::dynamic_format_specs< Char > specs_
const Char * format_str_
Detailed Description
template<typename Char = char>
class dynamic_formatter< Char >
Definition at line 4020 of file fmtlib_format.h.
Member Function Documentation
format()
template<typename Char = char> template<typename T , typename FormatContext > auto dynamic_formatter< Char >::format (const T & val, FormatContext & ctx) -> decltype(ctx.out()) inline
Definition at line 4041 of file fmtlib_format.h.
{
            handle_specs( ctx );
            detail::specs_checker<null_handler> checker(
                null_handler(), detail::mapped_type_constant<T, FormatContext>::value );
            checker.on_align( specs_.align );
            switch( specs_.sign ) {
                case sign::none:
                    break;
                case sign::plus:
                    checker.on_plus();
                    break;
                case sign::minus:
                    checker.on_minus();
                    break;
                case sign::space:
                    checker.on_space();
                    break;
            }
            if( specs_.alt ) {
                checker.on_hash();
            }
            if( specs_.precision >= 0 ) {
                checker.end_precision();
            }
            using af = detail::arg_formatter<typename FormatContext::iterator,
                  typename FormatContext::char_type>;
            visit_format_arg( af( ctx, nullptr, &specs_ ),
                              detail::make_arg<FormatContext>( val ) );
            return ctx.out();
        }
References detail::specs_checker< Handler >::end_precision(), dynamic_formatter< Char >::handle_specs(), sign::minus, sign::none, detail::specs_checker< Handler >::on_align(), detail::specs_checker< Handler >::on_hash(), detail::specs_checker< Handler >::on_minus(), detail::specs_checker< Handler >::on_plus(), detail::specs_checker< Handler >::on_space(), sign::plus, sign::space, dynamic_formatter< Char >::specs_, and visit_format_arg().
handle_specs()
template<typename Char = char> template<typename Context > void dynamic_formatter< Char >::handle_specs (Context & ctx) inline private
Definition at line 4073 of file fmtlib_format.h.
{
            detail::handle_dynamic_spec<detail::width_checker>( specs_.width,
                    specs_.width_ref, ctx );
            detail::handle_dynamic_spec<detail::precision_checker>(
                specs_.precision, specs_.precision_ref, ctx );
        }
References dynamic_formatter< Char >::specs_.
Referenced by dynamic_formatter< Char >::format().
parse()
template<typename Char = char> template<typename ParseContext > auto dynamic_formatter< Char >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 4033 of file fmtlib_format.h.
{
            format_str_ = ctx.begin();
            // Checks are deferred to formatting time when the argument type is known.
            detail::dynamic_specs_handler<ParseContext> handler( specs_, ctx );
            return parse_format_specs( ctx.begin(), ctx.end(), handler );
        }
References dynamic_formatter< Char >::format_str_, detail::parse_format_specs(), and dynamic_formatter< Char >::specs_.
Member Data Documentation
format_str_
template<typename Char = char> const Char* dynamic_formatter< Char >::format_str_ private
Definition at line 4081 of file fmtlib_format.h.
Referenced by dynamic_formatter< Char >::parse().
specs_
template<typename Char = char> detail::dynamic_format_specs<Char> dynamic_formatter< Char >::specs_ private
Definition at line 4080 of file fmtlib_format.h.
Referenced by dynamic_formatter< Char >::format(), dynamic_formatter< Char >::handle_specs(), and dynamic_formatter< Char >::parse().
The documentation for this class was generated from the following file:
src/fmtlib_format.h