Cataclysm BN: src/clzones.cpp File Reference
clzones.cpp File Reference
#include "clzones.h"
#include <algorithm>
#include <climits>
#include <iosfwd>
#include <iterator>
#include <string>
#include <tuple>
#include "avatar.h"
#include "cata_utility.h"
#include "construction.h"
#include "construction_group.h"
#include "cursesdef.h"
#include "debug.h"
#include "faction.h"
#include "fstream_utils.h"
#include "game.h"
#include "generic_factory.h"
#include "iexamine.h"
#include "int_id.h"
#include "item.h"
#include "item_category.h"
#include "item_search.h"
#include "itype.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "memory_fast.h"
#include "output.h"
#include "player.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
namespace anonymous_namespace{clzones.cpp}
Functions
static const std::string flag_FIREWOOD ("FIREWOOD")
Variables
static const item_category_id itcat_food ("food")
static const zone_type_id zone_CAMP_FOOD ("CAMP_FOOD")
static const zone_type_id zone_CONSTRUCTION_BLUEPRINT ("CONSTRUCTION_BLUEPRINT")
static const zone_type_id zone_FARM_PLOT ("FARM_PLOT")
static const zone_type_id zone_LOOT_CORPSE ("LOOT_CORPSE")
static const zone_type_id zone_LOOT_CUSTOM ("LOOT_CUSTOM")
static const zone_type_id zone_LOOT_DRINK ("LOOT_DRINK")
static const zone_type_id zone_LOOT_FOOD ("LOOT_FOOD")
static const zone_type_id zone_LOOT_IGNORE ("LOOT_IGNORE")
static const zone_type_id zone_LOOT_PDRINK ("LOOT_PDRINK")
static const zone_type_id zone_LOOT_PFOOD ("LOOT_PFOOD")
static const zone_type_id zone_LOOT_SEEDS ("LOOT_SEEDS")
static const zone_type_id zone_LOOT_UNSORTED ("LOOT_UNSORTED")
static const zone_type_id zone_LOOT_WOOD ("LOOT_WOOD")
static const zone_type_id zone_NO_AUTO_PICKUP ("NO_AUTO_PICKUP")
static const zone_type_id zone_NO_NPC_PICKUP ("NO_NPC_PICKUP")
generic_factory< zone_type > anonymous_namespace{clzones.cpp}::zone_type_factory ("zone_type")
Function Documentation
flag_FIREWOOD()
static const std::string flag_FIREWOOD ("FIREWOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
Variable Documentation
itcat_food
const item_category_id itcat_food("food") ("food") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_CAMP_FOOD
const zone_type_id zone_CAMP_FOOD("CAMP_FOOD") ("CAMP_FOOD") static
Referenced by zone_manager::has_loot_dest_near(), and zone_manager::zone_manager().
zone_CONSTRUCTION_BLUEPRINT
const zone_type_id zone_CONSTRUCTION_BLUEPRINT("CONSTRUCTION_BLUEPRINT") ("CONSTRUCTION_BLUEPRINT") static
Referenced by zone_manager::add(), zone_options::create(), zone_manager::has_loot_dest_near(), zone_options::is_valid(), and zone_manager::zone_manager().
zone_FARM_PLOT
const zone_type_id zone_FARM_PLOT("FARM_PLOT") ("FARM_PLOT") static
Referenced by zone_manager::add(), zone_options::create(), zone_manager::has_loot_dest_near(), zone_options::is_valid(), and zone_manager::zone_manager().
zone_LOOT_CORPSE
const zone_type_id zone_LOOT_CORPSE("LOOT_CORPSE") ("LOOT_CORPSE") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_LOOT_CUSTOM
const zone_type_id zone_LOOT_CUSTOM("LOOT_CUSTOM") ("LOOT_CUSTOM") static
Referenced by zone_options::create(), zone_manager::custom_loot_has(), zone_manager::get_near(), zone_manager::get_near_zone_type_for_item(), and zone_options::is_valid().
zone_LOOT_DRINK
const zone_type_id zone_LOOT_DRINK("LOOT_DRINK") ("LOOT_DRINK") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_LOOT_FOOD
const zone_type_id zone_LOOT_FOOD("LOOT_FOOD") ("LOOT_FOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_LOOT_IGNORE
const zone_type_id zone_LOOT_IGNORE("LOOT_IGNORE") ("LOOT_IGNORE") static
Referenced by zone_manager::has_loot_dest_near().
zone_LOOT_PDRINK
const zone_type_id zone_LOOT_PDRINK("LOOT_PDRINK") ("LOOT_PDRINK") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_LOOT_PFOOD
const zone_type_id zone_LOOT_PFOOD("LOOT_PFOOD") ("LOOT_PFOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_LOOT_SEEDS
const zone_type_id zone_LOOT_SEEDS("LOOT_SEEDS") ("LOOT_SEEDS") static
Referenced by plot_options::query_seed().
zone_LOOT_UNSORTED
const zone_type_id zone_LOOT_UNSORTED("LOOT_UNSORTED") ("LOOT_UNSORTED") static
Referenced by zone_manager::has_loot_dest_near().
zone_LOOT_WOOD
const zone_type_id zone_LOOT_WOOD("LOOT_WOOD") ("LOOT_WOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_NO_AUTO_PICKUP
const zone_type_id zone_NO_AUTO_PICKUP("NO_AUTO_PICKUP") ("NO_AUTO_PICKUP") static
Referenced by zone_manager::has_loot_dest_near(), and zone_manager::zone_manager().
zone_NO_NPC_PICKUP
const zone_type_id zone_NO_NPC_PICKUP("NO_NPC_PICKUP") ("NO_NPC_PICKUP") static
Referenced by zone_manager::get_point_set_loot(), zone_manager::has_loot_dest_near(), and zone_manager::zone_manager().