Cataclysm BN: src/color.cpp File Reference
color.cpp File Reference
#include "color.h"
#include <algorithm>
#include <cstdlib>
#include <iterator>
#include <map>
#include <vector>
#include "cata_utility.h"
#include "cursesdef.h"
#include "debug.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "input.h"
#include "json.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
Functions
color_manager & get_all_colors ()
void init_colors ()
nc_color invert_color (const nc_color &c)
nc_color hilite (const nc_color &c)
nc_color red_background (const nc_color &c)
nc_color white_background (const nc_color &c)
nc_color green_background (const nc_color &c)
nc_color yellow_background (const nc_color &c)
nc_color magenta_background (const nc_color &c)
nc_color cyan_background (const nc_color &c)
nc_color color_from_string (const std::string &color, const report_color_error color_error)
Given the name of a foreground color, returns the nc_color value that matches.
std::string string_from_color (const nc_color &color)
The reverse of color_from_string.
nc_color bgcolor_from_string (const std::string &color)
Given the name of a background color (that is, one of the i_xxxxx colors), returns the nc_color constant that matches.
color_tag_parse_result get_color_from_tag (const std::string &s, const report_color_error color_error)
std::string get_tag_from_color (const nc_color &color)
std::string colorize (const std::string &text, const nc_color &color)
std::string colorize (const translation &text, const nc_color &color)
std::string get_note_string_from_color (const nc_color &color)
nc_color get_note_color (const std::string &note_id)
std::list< std::pair< std::string, std::string > > get_note_color_names ()
static void draw_header (const catacurses::window &w)
Variables
std::unordered_map< std::string, note_color > color_by_string_map
Function Documentation
bgcolor_from_string()
nc_color bgcolor_from_string (const std::string & color)
Given the name of a background color (that is, one of the i_xxxxx colors), returns the nc_color constant that matches.
If no match is found, i_white is returned.
Parameters
color The color to get, as a std::string.
Returns
The nc_color constant that matches the input.
Definition at line 615 of file color.cpp.
{
    std::string new_color = "i_" + color;
    const std::pair<std::string, std::string> pSearch[2] = { { "light_", "lt" }, { "dark_", "dk" } };
    for( const auto &i : pSearch ) {
        size_t pos = 0;
        while( ( pos = new_color.find( i.second, pos ) ) != std::string::npos ) {
            new_color.replace( pos, i.second.length(), i.first );
            pos += i.first.length();
            debugmsg( "Deprecated background color suffix was used: (%s) in (%s).  Please update mod that uses that.",
                      i.second, color );
        }
    }
    const nc_color col = all_colors.name_to_color( new_color );
    if( col > 0 ) {
        return col;
    }
    return i_white;
}
References all_colors, color(), debugmsg, and i_white.
Referenced by map_data_common_t::load_symbol().
color_from_string()
nc_color color_from_string (const std::string & color, const report_color_error color_error)
Given the name of a foreground color, returns the nc_color value that matches.
If no match is found, c_unset is returned. Special cases: {"black" , c_black}, // missing default prefix c_ {"<c|h|i>_black" , h_black}, // has prefix c_ or h_ or i_ {"dark_gray_red" , c_dark_gray_red}, // use dark_ instead of dk as the latter is being deprecated {"light_blue_red" , c_light_blue_red}, // use light_ instead of lt as the latter is being deprecated
Parameters
color The color to get, as a std::string.
Returns
The nc_color constant that matches the input.
Definition at line 562 of file color.cpp.
{
    if( color.empty() ) {
        return c_unset;
    }
    std::string new_color = color;
    if( new_color.substr( 1, 1 ) != "_" ) { //c_  //i_  //h_
        new_color = "c_" + new_color;
    }
    const std::pair<std::string, std::string> pSearch[2] = { { "light_", "lt" }, { "dark_", "dk" } };
    for( const auto &i : pSearch ) {
        size_t pos = 0;
        while( ( pos = new_color.find( i.second, pos ) ) != std::string::npos ) {
            new_color.replace( pos, i.second.length(), i.first );
            pos += i.first.length();
            if( color_error == report_color_error::yes ) {
                debugmsg( "Deprecated foreground color suffix was used: (%s) in (%s).  Please update mod that uses that.",
                          i.second, color );
            }
        }
    }
    const nc_color col = all_colors.name_to_color( new_color, color_error );
    if( col > 0 ) {
        return col;
    }
    return c_unset;
}
References all_colors, c_unset, color(), debugmsg, and yes.
Referenced by assign(), nc_color::deserialize(), get_color_from_tag(), field_type::load(), map_extra::load(), vpart_info::load(), explosion_iuse::load(), Item_factory::load_basic_info(), and map_data_common_t::load_symbol().
colorize() [1/2]
std::string colorize (const std::string & text, const nc_color & color)
Definition at line 669 of file color.cpp.
{
    return get_tag_from_color( color ) + text + "</color>";
}
References color(), and get_tag_from_color().
Referenced by Character::activate_bionic(), vehicle::add_toggle_to_opts(), iexamine::autodoc(), item::basic_info(), iuse::blood_draw(), blood_magic(), Character::body_window(), butcher_submenu(), veh_interact::calc_overview(), veh_interact::can_remove_part(), color_number(), colorize(), spell::colorized_fail_percent(), colorized_feature_description_at(), colorized_field_description_at(), colorized_item_name(), colorized_ter_name_flags_at(), colorized_trap_name_at(), construction_menu(), item::contents_info(), craft_progress_message(), item_location::impl::item_on_vehicle::describe(), input_context::display_menu(), display_stat(), veh_interact::do_repair(), draw_bionics_titlebar(), target_ui::draw_controls_list(), spellcasting_callback::draw_spell_info(), draw_spellbook_info(), draw_traits_info(), item::durability_indicator(), effects_description_for_creature(), spell::energy_cost_string(), spell::energy_cur_string(), enumerate_objects_around_point(), Character::extended_description(), monster::extended_description(), npc::extended_description(), game::extended_description(), format_item_info(), get_consume_needs_hint(), overmapbuffer::get_description_at(), requirement_data::get_folded_components_list(), requirement_data::get_folded_list(), requirement_data::get_folded_tools_list(), mod_ui::get_information(), kill_tracker::get_kills_text(), help::get_note_colors(), construction::get_time_string(), avatar_funcs::gunmod_add(), main_menu::init_strings(), item_save_monsters(), diary::kill_changes(), iuse::marloss_seed(), avatar_funcs::mend_item(), iuse::mind_splicer(), vehicle_part::name(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_spell_info(), photo_def_for_camera_point(), character_martial_arts::pick_style(), pickup::pick_up(), overmap_ui::place_ter_or_special(), computer_session::print_error(), computer_session::print_gibberish_line(), print_mana(), main_menu::print_menu_items(), game::print_terrain_info(), vehicle::print_vparts_descs(), prompt_disassemble_in_seq(), iexamine::quern_examine(), veh_utils::repair_part(), iuse::seed(), select_crafting_recipe(), vehicle::set_electronics_menu_options(), set_profession(), set_skills(), shortcut_text(), show_armor_layers_ui(), show_mutations_titlebar(), overmap_ui::show_notes_manager(), iexamine::smoker_options(), Character::takeoff(), texitify_base_healing_power(), texitify_healing_power(), text_for_requirement(), avatar_funcs::toolmod_add(), diary::trait_changes(), achievement_tracker::ui_text(), achievement_state::ui_text(), achievements_tracker::ui_text_for(), veh_interact::update_part_requirements(), sew_advanced_actor::use(), query_popup::wait_text(), Character::will_eat(), and game::win_screen().
colorize() [2/2]
std::string colorize (const translation & text, const nc_color & color)
Definition at line 674 of file color.cpp.
{
    return colorize( text.translated(), color );
}
References color(), colorize(), and translation::translated().
cyan_background()
nc_color cyan_background (const nc_color & c)
Definition at line 545 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_CYAN );
    return static_cast<int>( color ) > 0 ? color : c_black_cyan;
}
References all_colors, c, c_black_cyan, color(), and HL_CYAN.
Referenced by map::draw_from_above(), editmap::draw_main_ui_overlay(), editmap_hilight::setup(), and Character::symbol_color().
draw_header()
static void draw_header (const catacurses::window & w) static
Definition at line 721 of file color.cpp.
{
    int tmpx = 0;
    tmpx += shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green,
                            _( "<R>emove custom color" ) ) + 2;
    tmpx += shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green,
                            _( "<Arrow Keys> To navigate" ) ) + 2;
    tmpx += shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green, _( "<Enter>-Edit" ) ) + 2;
    shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green, _( "Load <T>emplate" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 0, 1 ), c_white, _( "Some color changes may require a restart." ) );
    mvwhline( w, point( 0, 2 ), LINE_OXOX, getmaxx( w ) ); // Draw line under header
    mvwputch( w, point( 48, 2 ), BORDER_COLOR, LINE_OXXX ); //^|^
    mvwprintz( w, point( 3, 3 ), c_white, _( "Colorname" ) );
    mvwprintz( w, point( 21, 3 ), c_white, _( "Normal" ) );
    mvwprintz( w, point( 52, 3 ), c_white, _( "Invert" ) );
    wnoutrefresh( w );
}
References _, BORDER_COLOR, c_light_green, c_white, catacurses::getmaxx(), LINE_OXOX, LINE_OXXX, catacurses::mvwhline(), mvwprintz(), mvwputch(), shortcut_print(), and catacurses::wnoutrefresh().
Referenced by color_manager::show_gui().
get_all_colors()
color_manager & get_all_colors ()
Definition at line 45 of file color.cpp.
{
    static color_manager single_instance;
    return single_instance;
}
Referenced by colorize_symbols(), Messages::dialog::filter_help_text(), overmap_ui::get_scent_glyph(), vehicle::interact_with(), Character::pour_into(), and replace_colors().
get_color_from_tag()
color_tag_parse_result get_color_from_tag (const std::string & s, const report_color_error color_error)
Definition at line 639 of file color.cpp.
{
    if( s.empty() || s[0] != '<' ) {
        return { color_tag_parse_result::non_color_tag, {} };
    }
    if( s.substr( 0, 8 ) == "</color>" ) {
        return { color_tag_parse_result::close_color_tag, {} };
    }
    if( s.substr( 0, 7 ) != "<color_" ) {
        return { color_tag_parse_result::non_color_tag, {} };
    }
    size_t tag_close = s.find( '>' );
    if( tag_close == std::string::npos ) {
        return { color_tag_parse_result::non_color_tag, {} };
    }
    std::string color_name = s.substr( 7, tag_close - 7 );
    const nc_color color = color_from_string( color_name, color_error );
    if( color != c_unset ) {
        return { color_tag_parse_result::open_color_tag, color };
    } else {
        return { color_tag_parse_result::non_color_tag, color };
    }
}
References c_unset, color_tag_parse_result::close_color_tag, color(), color_from_string(), color_tag_parse_result::non_color_tag, and color_tag_parse_result::open_color_tag.
Referenced by update_color_stack().
get_note_color()
nc_color get_note_color (const std::string & note_id)
Definition at line 690 of file color.cpp.
{
    const auto candidate_color = color_by_string_map.find( note_id );
    if( candidate_color != std::end( color_by_string_map ) ) {
        return candidate_color->second.color;
    }
    // The default note color.
    return c_yellow;
}
References c_yellow, and color_by_string_map.
Referenced by overmap_ui::draw_overmap_chunk(), help::get_note_colors(), and overmap_ui::get_note_display_info().
get_note_color_names()
std::list< std::pair< std::string, std::string > > get_note_color_names ()
Definition at line 700 of file color.cpp.
{
    auto color_list = std::list<std::pair<std::string, std::string>> {};
    for( const auto &color_pair : color_by_string_map ) {
        color_list.emplace_back( color_pair.first, color_pair.second.name );
    }
    return color_list;
}
References color_by_string_map.
Referenced by overmap_ui::create_note(), and help::get_note_colors().
get_note_string_from_color()
std::string get_note_string_from_color (const nc_color & color)
Definition at line 679 of file color.cpp.
{
    for( const auto &pair : color_by_string_map ) {
        if( pair.second.color == color ) {
            return pair.first;
        }
    }
    // The default note string.
    return "Y";
}
References color(), and color_by_string_map.
Referenced by MapExtras::apply_function().
get_tag_from_color()
std::string get_tag_from_color (const nc_color & color)
Definition at line 664 of file color.cpp.
{
    return "<color_" + string_from_color( color ) + ">";
}
References color(), and string_from_color().
Referenced by colorize(), and requirement_data::get_folded_list().
green_background()
nc_color green_background (const nc_color & c)
Definition at line 527 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_GREEN );
    return static_cast<int>( color ) > 0 ? color : c_black_green;
}
References all_colors, c, c_black_green, color(), and HL_GREEN.
Referenced by editmap::draw_main_ui_overlay(), editmap_hilight::setup(), and Character::symbol_color().
hilite()
nc_color hilite (const nc_color & c)
Definition at line 509 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_BLUE );
    return static_cast<int>( color ) > 0 ? color : h_white;
}
References all_colors, c, color(), h_white, and HL_BLUE.
Referenced by monster::color_with_effects(), construction_color(), faction_manager::display(), veh_interact::display_list(), veh_interact::display_overview(), veh_interact::display_veh(), draw_bionics_tab(), lightson_game::draw_level(), map::draw_maptile(), draw_time_graphic(), draw_traits_tab(), requirement_data::get_folded_components_list(), requirement_data::get_folded_list(), basecamp::job_assignment_ui(), game::list_missions(), game::list_monsters(), mvwputch_hi(), pickup::pick_up(), worldfactory::pick_world(), advanced_inventory::print_items(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), vehicle::print_part_list(), set_points(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), query_popup::show(), options_manager::show(), safemode::show(), worldfactory::show_modselection_window(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), Character::symbol_color(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and basecamp::worker_assignment_ui().
init_colors()
void init_colors ()
Definition at line 401 of file color.cpp.
{
    using namespace catacurses; // to get the base_color enumeration
    init_pair( 1, white,      black );
    init_pair( 2, red,        black );
    init_pair( 3, green,      black );
    init_pair( 4, blue,       black );
    init_pair( 5, cyan,       black );
    init_pair( 6, magenta,    black );
    init_pair( 7, yellow,     black );
    // Inverted Colors
    init_pair( 8, black,      white );
    init_pair( 9, black,      red );
    init_pair( 10, black,      green );
    init_pair( 11, black,      blue );
    init_pair( 12, black,      cyan );
    init_pair( 13, black,      magenta );
    init_pair( 14, black,      yellow );
    // Highlighted - blue background
    init_pair( 15, white,      blue );
    init_pair( 16, red,        blue );
    init_pair( 17, green,      blue );
    init_pair( 18, blue,       blue );
    init_pair( 19, cyan,       blue );
    init_pair( 20, black,      blue );
    init_pair( 21, magenta,    blue );
    init_pair( 22, yellow,     blue );
    // Red background - for monsters on fire
    init_pair( 23, white,      red );
    init_pair( 24, red,        red );
    init_pair( 25, green,      red );
    init_pair( 26, blue,       red );
    init_pair( 27, cyan,       red );
    init_pair( 28, magenta,    red );
    init_pair( 29, yellow,     red );
    init_pair( 30, black,      black );
    init_pair( 31, white,      black );
    init_pair( 32, black,      white );
    init_pair( 33, white,      white );
    init_pair( 34, red,        white );
    init_pair( 35, green,      white );
    init_pair( 36, yellow,     white );
    init_pair( 37, blue,       white );
    init_pair( 38, magenta,    white );
    init_pair( 39, cyan,       white );
    init_pair( 40, black,      green );
    init_pair( 41, white,      green );
    init_pair( 42, red,        green );
    init_pair( 43, green,      green );
    init_pair( 44, yellow,     green );
    init_pair( 45, blue,       green );
    init_pair( 46, magenta,    green );
    init_pair( 47, cyan,       green );
    init_pair( 48, black,      yellow );
    init_pair( 49, white,      yellow );
    init_pair( 50, red,        yellow );
    init_pair( 51, green,      yellow );
    init_pair( 52, yellow,     yellow );
    init_pair( 53, blue,       yellow );
    init_pair( 54, magenta,    yellow );
    init_pair( 55, cyan,       yellow );
    init_pair( 56, black,      magenta );
    init_pair( 57, white,      magenta );
    init_pair( 58, red,        magenta );
    init_pair( 59, green,      magenta );
    init_pair( 60, yellow,     magenta );
    init_pair( 61, blue,       magenta );
    init_pair( 62, magenta,    magenta );
    init_pair( 63, cyan,       magenta );
    init_pair( 64, black,      cyan );
    init_pair( 65, white,      cyan );
    init_pair( 66, red,        cyan );
    init_pair( 67, green,      cyan );
    init_pair( 68, yellow,     cyan );
    init_pair( 69, blue,       cyan );
    init_pair( 70, magenta,    cyan );
    init_pair( 71, cyan,       cyan );
    all_colors.load_default();
    all_colors.load_custom();
    // The short color codes (e.g. "br") are intentionally untranslatable.
    color_by_string_map = {
        {"br", {c_brown, translate_marker( "brown" )}}, {"lg", {c_light_gray, translate_marker( "light gray" )}},
        {"dg", {c_dark_gray, translate_marker( "dark gray" )}}, {"r", {c_light_red, translate_marker( "light red" )}},
        {"R", {c_red, translate_marker( "red" )}}, {"g", {c_light_green, translate_marker( "light green" )}},
        {"G", {c_green, translate_marker( "green" )}}, {"b", {c_light_blue, translate_marker( "light blue" )}},
        {"B", {c_blue, translate_marker( "blue" )}}, {"W", {c_white, translate_marker( "white" )}},
        {"C", {c_cyan, translate_marker( "cyan" )}}, {"c", {c_light_cyan, translate_marker( "light cyan" )}},
        {"P", {c_pink, translate_marker( "pink" )}}, {"m", {c_magenta, translate_marker( "magenta" )}}
    };
}
References all_colors, catacurses::black, catacurses::blue, c_blue, c_brown, c_cyan, c_dark_gray, c_green, c_light_blue, c_light_cyan, c_light_gray, c_light_green, c_light_red, c_magenta, c_pink, c_red, c_white, color_by_string_map, catacurses::cyan, catacurses::green, catacurses::init_pair(), catacurses::magenta, catacurses::red, translate_marker, catacurses::white, and catacurses::yellow.
Referenced by catacurses::init_interface(), and main().
invert_color()
nc_color invert_color (const nc_color & c)
Definition at line 503 of file color.cpp.
{
    const nc_color color = all_colors.get_invert( c );
    return static_cast<int>( color ) > 0 ? color : c_pink;
}
References all_colors, c, c_pink, and color().
Referenced by monster::color_with_effects(), map::draw_from_above(), map::draw_maptile(), advanced_inventory::draw_minimap(), anonymous_namespace{animation.cpp}::draw_zones_curses(), mvwputch_inv(), and vehicle::part_color().
magenta_background()
nc_color magenta_background (const nc_color & c)
Definition at line 539 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_MAGENTA );
    return static_cast<int>( color ) > 0 ? color : c_black_magenta;
}
References all_colors, c, c_black_magenta, color(), and HL_MAGENTA.
Referenced by advanced_inventory::print_items(), and editmap_hilight::setup().
red_background()
nc_color red_background (const nc_color & c)
Definition at line 515 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_RED );
    return static_cast<int>( color ) > 0 ? color : c_white_red;
}
References all_colors, c, c_white_red, color(), and HL_RED.
Referenced by monster::color_with_effects(), veh_interact::display_veh(), overmap_ui::draw_ascii(), anonymous_namespace{animation.cpp}::draw_hit_mon_curses(), anonymous_namespace{animation.cpp}::draw_hit_player_curses(), sokoban_game::draw_level(), map::draw_maptile(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), editmap_hilight::setup(), Character::symbol_color(), auto_pickup::rule::test_pattern(), and safemode::test_pattern().
string_from_color()
std::string string_from_color (const nc_color & color)
The reverse of color_from_string.
Definition at line 597 of file color.cpp.
{
    std::string sColor = all_colors.get_name( color );
    if( sColor != "c_unset" ) {
        return sColor;
    }
    return "c_white";
}
References all_colors, and color().
Referenced by vpart_info::format_description(), get_moon_graphic(), get_tag_from_color(), and overmap_ui::place_ter_or_special().
white_background()
nc_color white_background (const nc_color & c)
Definition at line 521 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_WHITE );
    return static_cast<int>( color ) > 0 ? color : c_black_white;
}
References all_colors, c, c_black_white, color(), and HL_WHITE.
Referenced by Character::symbol_color().
yellow_background()
nc_color yellow_background (const nc_color & c)
Definition at line 533 of file color.cpp.
{
    const nc_color color = all_colors.get_highlight( c, HL_YELLOW );
    return static_cast<int>( color ) > 0 ? color : c_black_yellow;
}
References all_colors, c, c_black_yellow, color(), and HL_YELLOW.
Referenced by anonymous_namespace{animation.cpp}::draw_hit_player_curses(), requirement_data::get_folded_list(), and editmap_hilight::setup().
Variable Documentation
color_by_string_map
std::unordered_map<std::string, note_color> color_by_string_map
Definition at line 51 of file color.cpp.
Referenced by get_note_color(), get_note_color_names(), get_note_string_from_color(), and init_colors().