Cataclysm BN: src/computer_session.cpp File Reference
computer_session.cpp File Reference
#include "computer_session.h"
#include <algorithm>
#include <cstdlib>
#include <functional>
#include <memory>
#include <string>
#include <utility>
#include "avatar.h"
#include "calendar.h"
#include "character_id.h"
#include "colony.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "mtype.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "player.h"
#include "point.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "text_snippets.h"
#include "timed_event.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
Functions
static const std::string flag_CONSOLE ("CONSOLE")
static catacurses::window init_window ()
static item * pick_usb ()
static void remove_submap_turrets ()
Variables
static const efftype_id effect_amigara ("amigara")
static const itype_id itype_black_box ("black_box")
static const itype_id itype_blood ("blood")
static const itype_id itype_c4 ("c4")
static const itype_id itype_cobalt_60 ("cobalt_60")
static const itype_id itype_mininuke ("mininuke")
static const itype_id itype_mininuke_act ("mininuke_act")
static const itype_id itype_radio_repeater_mod ("radio_repeater_mod")
static const itype_id itype_sarcophagus_access_code ("sarcophagus_access_code")
static const itype_id itype_sewage ("sewage")
static const itype_id itype_usb_drive ("usb_drive")
static const itype_id itype_vacutainer ("vacutainer")
static const skill_id skill_computer ("computer")
static const species_id HUMAN ("HUMAN")
static const species_id ZOMBIE ("ZOMBIE")
static const mtype_id mon_manhack ("mon_manhack")
static const mtype_id mon_secubot ("mon_secubot")
Function Documentation
flag_CONSOLE()
static const std::string flag_CONSOLE ("CONSOLE") static
Referenced by computer_session::failure_shutdown().
init_window()
static catacurses::window init_window () static
Definition at line 82 of file computer_session.cpp.
{
    const int width = FULL_SCREEN_WIDTH;
    const int height = FULL_SCREEN_HEIGHT;
    const point p( std::max( 0, ( TERMX - width ) / 2 ), std::max( 0, ( TERMY - height ) / 2 ) );
    return catacurses::newwin( height, width, p );
}
References FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, catacurses::newwin(), TERMX, and TERMY.
Referenced by debug_error_prompt(), draw_item_info(), and scrollable_text().
pick_usb()
static item * pick_usb () static
Definition at line 229 of file computer_session.cpp.
{
    auto filter = []( const item & it ) {
        return it.typeId() == itype_usb_drive;
    };
    item_location loc = game_menus::inv::titled_filter_menu( filter, g->u, _( "Choose drive:" ) );
    if( loc ) {
        return &*loc;
    }
    return nullptr;
}
References _, g, itype_usb_drive, game_menus::inv::titled_filter_menu(), and item::typeId().
Referenced by computer_session::action_blood_anal(), and computer_session::action_download_software().
remove_submap_turrets()
static void remove_submap_turrets () static
Definition at line 242 of file computer_session.cpp.
{
    map &here = get_map();
    for( monster &critter : g->all_monsters() ) {
        // Check 1) same overmap coords, 2) turret, 3) hostile
        if( ms_to_omt_copy( here.getabs( critter.pos() ) ) == ms_to_omt_copy( here.getabs( g->u.pos() ) ) &&
            critter.has_flag( MF_CONSOLE_DESPAWN ) &&
            critter.attitude_to( g->u ) == Creature::Attitude::A_HOSTILE ) {
            g->remove_zombie( critter );
        }
    }
}
References g, get_map(), map::getabs(), MF_CONSOLE_DESPAWN, and ms_to_omt_copy().
Referenced by computer_session::action_open_disarm(), computer_session::action_release_disarm(), and computer_session::action_unlock_disarm().
Variable Documentation
effect_amigara
const efftype_id effect_amigara("amigara") ("amigara") static
Referenced by computer_session::failure_amigara().
HUMAN
const species_id HUMAN("HUMAN") ("HUMAN") static
Referenced by computer_session::action_blood_anal().
itype_black_box
const itype_id itype_black_box("black_box") ("black_box") static
Referenced by computer_session::action_data_anal().
itype_blood
const itype_id itype_blood("blood") ("blood") static
Referenced by computer_session::action_blood_anal(), and computer_session::failure_destroy_blood().
itype_c4
const itype_id itype_c4("c4") ("c4") static
Referenced by computer_session::action_irradiator().
itype_cobalt_60
const itype_id itype_cobalt_60("cobalt_60") ("cobalt_60") static
Referenced by computer_session::action_extract_rad_source().
itype_mininuke
const itype_id itype_mininuke("mininuke") ("mininuke") static
Referenced by computer_session::action_irradiator().
itype_mininuke_act
const itype_id itype_mininuke_act("mininuke_act") ("mininuke_act") static
Referenced by computer_session::action_irradiator().
itype_radio_repeater_mod
const itype_id itype_radio_repeater_mod("radio_repeater_mod") ("radio_repeater_mod") static
Referenced by computer_session::action_repeater_mod().
itype_sarcophagus_access_code
const itype_id itype_sarcophagus_access_code("sarcophagus_access_code") ("sarcophagus_access_code") static
Referenced by computer_session::action_srcf_elevator().
itype_sewage
const itype_id itype_sewage("sewage") ("sewage") static
Referenced by computer_session::action_sample().
itype_usb_drive
const itype_id itype_usb_drive("usb_drive") ("usb_drive") static
Referenced by computer_session::action_data_anal(), computer_session::failure_destroy_data(), and pick_usb().
itype_vacutainer
const itype_id itype_vacutainer("vacutainer") ("vacutainer") static
Referenced by computer_session::failure_destroy_blood().
mon_manhack
const mtype_id mon_manhack("mon_manhack") ("mon_manhack") static
Referenced by computer_session::failure_manhacks().
mon_secubot
const mtype_id mon_secubot("mon_secubot") ("mon_secubot") static
Referenced by computer_session::failure_secubots().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by computer_session::hack_attempt().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by computer_session::action_blood_anal().