Cataclysm BN: src/condition.cpp File Reference
condition.cpp File Reference
#include "condition.h"
#include <climits>
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "auto_pickup.h"
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "debug.h"
#include "dialogue.h"
#include "enum_conversions.h"
#include "game.h"
#include "item.h"
#include "item_category.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "mapdata.h"
#include "mission.h"
#include "npc.h"
#include "optional.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "recipe_groups.h"
#include "string_id.h"
#include "type_id.h"
#include "vehicle.h"
#include "vpart_position.h"
Functions
std::string get_talk_varname (const JsonObject &jo, const std::string &member, bool check_value)
template<class T >
void read_condition (const JsonObject &jo, const std::string &member_name, std::function< bool(const T &)> &condition, bool default_val)
template void read_condition< dialogue > (const JsonObject &jo, const std::string &member_name, std::function< bool(const dialogue &)> &condition, bool default_val)
template void read_condition< mission_goal_condition_context > (const JsonObject &jo, const std::string &member_name, std::function< bool(const mission_goal_condition_context &)> &condition, bool default_val)
Variables
static const efftype_id effect_currently_busy ("currently_busy")
Function Documentation
get_talk_varname()
std::string get_talk_varname (const JsonObject & jo, const std::string & member, bool check_value)
Definition at line 50 of file condition.cpp.
{
    if( !jo.has_string( "type" ) || !jo.has_string( "context" ) ||
        ( check_value && !jo.has_string( "value" ) ) ) {
        jo.throw_error( "invalid " + member + " condition in " + jo.str() );
    }
    const std::string &var_basename = jo.get_string( member );
    const std::string &type_var = jo.get_string( "type" );
    const std::string &var_context = jo.get_string( "context" );
    return "npctalk_var_" + type_var + "_" + var_context + "_" + var_basename;
}
References JsonObject::get_string(), JsonObject::has_string(), mapgen_defer::member, JsonObject::str(), and JsonObject::throw_error().
Referenced by talk_effect_fun_t::set_add_var(), talk_effect_fun_t::set_adjust_var(), conditional_t< T >::set_compare_var(), conditional_t< T >::set_has_var(), and talk_effect_fun_t::set_remove_var().
read_condition()
template<class T > void read_condition (const JsonObject & jo, const std::string & member_name, std::function< bool(const T &)> & condition, bool default_val)
Definition at line 63 of file condition.cpp.
{
    const auto null_function = [default_val]( const T & ) {
        return default_val;
    };
    if( !jo.has_member( member_name ) ) {
        condition = null_function;
    } else if( jo.has_string( member_name ) ) {
        const std::string type = jo.get_string( member_name );
        conditional_t<T> sub_condition( type );
        condition = [sub_condition]( const T & d ) {
            return sub_condition( d );
        };
    } else if( jo.has_object( member_name ) ) {
        JsonObject con_obj = jo.get_object( member_name );
        conditional_t<T> sub_condition( con_obj );
        condition = [sub_condition]( const T & d ) {
            return sub_condition( d );
        };
    } else {
        jo.throw_error( "invalid condition syntax", member_name );
    }
}
References JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), JsonObject::throw_error(), and type.
read_condition< dialogue >()
template void read_condition< dialogue > (const JsonObject & jo, const std::string & member_name, std::function< bool(const dialogue &)> & condition, bool default_val)
Referenced by json_dynamic_line_effect::json_dynamic_line_effect(), json_talk_response::load_condition(), talk_response::talk_response(), and talk_trial::talk_trial().
read_condition< mission_goal_condition_context >()
template void read_condition< mission_goal_condition_context > (const JsonObject & jo, const std::string & member_name, std::function< bool(const mission_goal_condition_context &)> & condition, bool default_val)
Referenced by mission_type::load().
Variable Documentation
effect_currently_busy
const efftype_id effect_currently_busy("currently_busy") ("currently_busy") static
Referenced by conditional_t< T >::set_npc_available().