Cataclysm BN: src/construction.cpp File Reference
construction.cpp File Reference
#include "construction.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <iterator>
#include <memory>
#include <numeric>
#include <utility>
#include "action.h"
#include "avatar.h"
#include "calendar.h"
#include "character_functions.h"
#include "colony.h"
#include "color.h"
#include "construction_category.h"
#include "coordinate_conversions.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "item_group.h"
#include "item_stack.h"
#include "iuse.h"
#include "json.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "requirements.h"
#include "rng.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "translations.h"
#include "trap.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "units_serde.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
namespace construct
Functions
static const std::string flag_FLAT ("FLAT")
static const std::string flag_INITIAL_PART ("INITIAL_PART")
static const std::string flag_SUPPORTS_ROOF ("SUPPORTS_ROOF")
static bool construct::check_nothing (const tripoint &)
bool construct::check_empty (const tripoint &)
bool construct::check_support (const tripoint &)
bool construct::check_deconstruct (const tripoint &)
bool construct::check_empty_up_OK (const tripoint &)
bool construct::check_up_OK (const tripoint &)
bool construct::check_down_OK (const tripoint &)
bool construct::check_no_trap (const tripoint &)
bool construct::check_ramp_low (const tripoint &)
bool construct::check_ramp_high (const tripoint &)
static void construct::done_nothing (const tripoint &)
void construct::done_trunk_plank (const tripoint &)
void construct::done_grave (const tripoint &)
void construct::done_vehicle (const tripoint &)
void construct::done_deconstruct (const tripoint &)
void construct::done_digormine_stair (const tripoint &, bool)
void construct::done_dig_stair (const tripoint &)
void construct::done_mine_downstair (const tripoint &)
void construct::done_mine_upstair (const tripoint &)
void construct::done_wood_stairs (const tripoint &)
void construct::done_window_curtains (const tripoint &)
void construct::done_extract_maybe_revert_to_dirt (const tripoint &)
void construct::done_mark_firewood (const tripoint &)
void construct::done_mark_practice_target (const tripoint &)
void construct::done_ramp_low (const tripoint &)
void construct::done_ramp_high (const tripoint &)
void construct::failure_standard (const tripoint &)
void construct::failure_deconstruct (const tripoint &)
static bool can_construct (const std::string &desc)
static bool can_construct (const construction &con)
static bool player_can_build (player &p, const inventory &inv, const std::string &desc)
static void place_construction (const std::string &desc)
static bool has_pre_terrain (const construction &con, const tripoint &p)
static bool has_pre_terrain (const construction &con)
void standardize_construction_times (const int time)
Set all constructions to take the specified time.
static std::vector< construction * > constructions_by_desc (const std::string &description)
static void load_available_constructions (std::vector< std::string > &available, std::map< construction_category_id, std::vector< std::string > > &cat_available, bool hide_unconstructable)
static void draw_grid (const catacurses::window &w, const int list_width)
static nc_color construction_color (const std::string &con_name, bool highlight)
const std::vector< construction > & get_constructions ()
construction_id construction_menu (const bool blueprint)
bool player_can_build (player &p, const inventory &inv, const construction &con)
bool player_can_see_to_build (player &p, const std::string &desc)
bool can_construct (const construction &con, const tripoint &p)
void complete_construction (player *p)
std::array< tripoint, 4 > get_orthogonal_neighbors (const tripoint &p)
static vpart_id vpart_from_item (const itype_id &item_id)
static void unroll_digging (const int numer_of_2x4s)
template<typename T >
void assign_or_debugmsg (T &dest, const std::string &fun_id, const std::map< std::string, T > &possible)
void load_construction (const JsonObject &jo)
void reset_constructions ()
void check_constructions ()
void finalize_constructions ()
void get_build_reqs_for_furn_ter_ids (const std::pair< std::map< ter_id, int >, std::map< furn_id, int > > &changed_ids, build_reqs &total_reqs)
Variables
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const construction_category_id construction_category_ALL ("ALL")
static const construction_category_id construction_category_FILTER ("FILTER")
static const construction_category_id construction_category_REPAIR ("REPAIR")
static const itype_id itype_2x4 ("2x4")
static const itype_id itype_nail ("nail")
static const itype_id itype_sheet ("sheet")
static const itype_id itype_stick ("stick")
static const itype_id itype_string_36 ("string_36")
static const trap_str_id tr_firewood_source ("tr_firewood_source")
static const trap_str_id tr_practice_target ("tr_practice_target")
static const trap_str_id tr_unfinished_construction ("tr_unfinished_construction")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_fabrication ("fabrication")
static const quality_id qual_CUT ("CUT")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_PAINRESIST_TROGLO ("PAINRESIST_TROGLO")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_STOCKY_TROGLO ("STOCKY_TROGLO")
static bool finalized = false
static std::vector< construction > constructions
static std::map< construction_str_id, construction_id > construction_id_map
static const deferred_color color_title = def_c_light_red
static const deferred_color color_data = def_c_cyan
static const construction null_construction {}
Function Documentation
assign_or_debugmsg()
template<typename T > void assign_or_debugmsg (T & dest, const std::string & fun_id, const std::map< std::string, T > & possible)
Definition at line 1490 of file construction.cpp.
{
    const auto iter = possible.find( fun_id );
    if( iter != possible.end() ) {
        dest = iter->second;
    } else {
        dest = possible.find( "" )->second;
        const std::string list_available = enumerate_as_string( possible.begin(), possible.end(),
        []( const std::pair<std::string, T> &pr ) {
            return pr.first;
        } );
        debugmsg( "Unknown function: %s, available values are %s", fun_id.c_str(), list_available );
    }
}
References debugmsg, and enumerate_as_string().
Referenced by load_construction().
can_construct() [1/3]
bool can_construct (const construction & con) static
Definition at line 884 of file construction.cpp.
{
    for( const tripoint &p : get_map().points_in_radius( g->u.pos(), 1 ) ) {
        if( p != g->u.pos() && can_construct( con, p ) ) {
            return true;
        }
    }
    return false;
}
References can_construct(), g, get_map(), and points_in_radius().
can_construct() [2/3]
bool can_construct (const construction & con, const tripoint & p)
Definition at line 859 of file construction.cpp.
{
    // see if the special pre-function checks out
    bool place_okay = con.pre_special( p );
    // see if the terrain type checks out
    place_okay &= has_pre_terrain( con, p );
    // see if the flags check out
    place_okay &= std::all_of( con.pre_flags.begin(), con.pre_flags.end(),
    [&p]( const std::string & flag ) {
        return get_map().has_flag( flag, p );
    } );
    // make sure the construction would actually do something
    if( !con.post_terrain.empty() ) {
        map &here = get_map();
        if( con.post_is_furniture ) {
            furn_id f = furn_id( con.post_terrain );
            place_okay &= here.furn( p ) != f;
        } else {
            ter_id t = ter_id( con.post_terrain );
            place_okay &= here.ter( p ) != t;
        }
    }
    return place_okay;
}
References map::furn(), get_map(), has_pre_terrain(), construction::post_is_furniture, construction::post_terrain, construction::pre_flags, construction::pre_special, and map::ter().
can_construct() [3/3]
bool can_construct (const std::string & desc) static
Definition at line 847 of file construction.cpp.
{
    // check all with the same desc to see if player can build any
    std::vector<construction *> cons = constructions_by_desc( desc );
    for( auto &con : cons ) {
        if( can_construct( *con ) ) {
            return true;
        }
    }
    return false;
}
References can_construct(), and constructions_by_desc().
Referenced by can_construct(), construction_color(), construction_menu(), find_base_construction(), load_available_constructions(), and place_construction().
check_constructions()
void check_constructions ()
Definition at line 1636 of file construction.cpp.
{
    for( size_t i = 0; i < constructions.size(); i++ ) {
        const construction &c = constructions[ i ];
        const std::string display_name = std::string( "construction " ) + c.description;
        // Note: print the description as the id is just a generated number,
        // the description can be searched for in the json files.
        for( const auto &pr : c.required_skills ) {
            if( !pr.first.is_valid() ) {
                debugmsg( "Unknown skill %s in %s", pr.first.c_str(), display_name );
            }
        }
        if( !c.requirements.is_valid() ) {
            debugmsg( "construction %s has missing requirement data %s",
                      display_name, c.requirements.c_str() );
        }
        if( !c.pre_terrain.empty() ) {
            if( c.pre_is_furniture ) {
                if( !furn_str_id( c.pre_terrain ).is_valid() ) {
                    debugmsg( "Unknown pre_terrain (furniture) %s in %s", c.pre_terrain, display_name );
                }
            } else if( !ter_str_id( c.pre_terrain ).is_valid() ) {
                debugmsg( "Unknown pre_terrain (terrain) %s in %s", c.pre_terrain, display_name );
            }
        }
        if( !c.post_terrain.empty() ) {
            if( c.post_is_furniture ) {
                if( !furn_str_id( c.post_terrain ).is_valid() ) {
                    debugmsg( "Unknown post_terrain (furniture) %s in %s", c.post_terrain, display_name );
                }
            } else if( !ter_str_id( c.post_terrain ).is_valid() ) {
                debugmsg( "Unknown post_terrain (terrain) %s in %s", c.post_terrain, display_name );
            }
        }
        if( c.id != construction_id( i ) ) {
            debugmsg( "Construction \"%s\" has id %u, but should have %u",
                      c.description, c.id.to_i(), i );
        }
        if( construction_id_map.find( c.str_id ) == construction_id_map.end() ) {
            debugmsg( "Construction \"%s\" has invalid string id %s",
                      c.description, c.str_id.str() );
        } else if( construction_id_map[c.str_id] != construction_id( i ) ) {
            debugmsg( "Construction \"%s\" has string id \"%s\" that points to int id %u, but should point to %u",
                      c.description, c.str_id.str(), construction_id_map[c.str_id].to_i(), i );
        }
    }
}
References c, construction_id_map, constructions, debugmsg, and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
complete_construction()
void complete_construction (player * p)
Definition at line 963 of file construction.cpp.
{
    if( !finalized ) {
        debugmsg( "complete_construction called before finalization" );
        return;
    }
    map &here = get_map();
    const tripoint terp = here.getlocal( p->activity.placement );
    partial_con *pc = here.partial_con_at( terp );
    if( !pc ) {
        debugmsg( "No partial construction found at activity placement in complete_construction()" );
        if( here.tr_at( terp ).loadid == tr_unfinished_construction ) {
            here.remove_trap( terp );
        }
        if( p->is_npc() ) {
            npc *guy = dynamic_cast<npc *>( p );
            guy->current_activity_id = activity_id::NULL_ID();
            guy->revert_after_activity();
            guy->set_moves( 0 );
        }
        return;
    }
    const construction &built = pc->id.obj();
    const auto award_xp = [&]( player & c ) {
        for( const auto &pr : built.required_skills ) {
            c.practice( pr.first, static_cast<int>( ( 10 + 15 * pr.second ) * ( 1 + built.time / 180000.0 ) ),
                        static_cast<int>( pr.second * 1.25 ) );
        }
    };
    award_xp( *p );
    // Friendly NPCs gain exp from assisting or watching...
    // TODO: NPCs watching other NPCs do stuff and learning from it
    if( p->is_player() ) {
        for( auto &elem : g->u.get_crafting_helpers() ) {
            if( elem->meets_skill_requirements( built ) ) {
                add_msg( m_info, _( "%s assists you with the work" ), elem->name );
            } else {
                //NPC near you isn't skilled enough to help
                add_msg( m_info, _( "%s watches you work" ), elem->name );
            }
            award_xp( *elem );
        }
    }
    if( here.tr_at( terp ).loadid == tr_unfinished_construction ) {
        here.remove_trap( terp );
    }
    here.partial_con_remove( terp );
    // Some constructions are allowed to have items left on the tile.
    if( built.post_flags.count( "keep_items" ) == 0 ) {
        // Move any items that have found their way onto the construction site.
        std::vector<tripoint> dump_spots;
        for( const tripoint &pt : here.points_in_radius( terp, 1 ) ) {
            if( here.can_put_items( pt ) && pt != terp ) {
                dump_spots.push_back( pt );
            }
        }
        if( !dump_spots.empty() ) {
            tripoint dump_spot = random_entry( dump_spots );
            map_stack items = here.i_at( terp );
            for( map_stack::iterator it = items.begin(); it != items.end(); ) {
                here.add_item_or_charges( dump_spot, *it );
                it = items.erase( it );
            }
        } else {
            debugmsg( "No space to displace items from construction finishing" );
        }
    }
    // Make the terrain change
    if( !built.post_terrain.empty() ) {
        if( built.post_is_furniture ) {
            here.furn_set( terp, furn_str_id( built.post_terrain ) );
            active_tile_data *active = active_tiles::furn_at<active_tile_data>(
                                           tripoint_abs_ms( here.getabs( terp ) ) );
            if( active != nullptr ) {
                active->set_last_updated( calendar::turn );
            }
        } else {
            const ter_id new_ter = ter_str_id( built.post_terrain );
            here.ter_set( terp, new_ter );
            const tripoint above = terp + tripoint_above;
            // TODO: What to do if tile above has no floor, but isn't open air?
            if( new_ter->roof && here.ter( above ) == t_open_air ) {
                here.ter_set( above, new_ter->roof );
            }
        }
    }
    // Spawn byproducts
    if( built.byproduct_item_group ) {
        here.spawn_items( p->pos(), item_group::items_from( built.byproduct_item_group, calendar::turn ) );
    }
    add_msg( m_info, _( "%s finished construction: %s." ), p->disp_name(), _( built.description ) );
    // clear the activity
    p->activity.set_to_null();
    // This comes after clearing the activity, in case the function interrupts
    // activities
    built.post_special( terp );
    // npcs will automatically resume backlog, players wont.
    if( p->is_player() && !p->backlog.empty() &&
        p->backlog.front().id() == ACT_MULTIPLE_CONSTRUCTION ) {
        p->backlog.clear();
        p->assign_activity( ACT_MULTIPLE_CONSTRUCTION );
    }
}
References _, ACT_MULTIPLE_CONSTRUCTION, active, Character::activity, map::add_item_or_charges(), add_msg(), Character::assign_activity(), Character::backlog, item_stack::begin(), construction::byproduct_item_group, c, map::can_put_items(), npc::current_activity_id, debugmsg, construction::description, Character::disp_name(), item_stack::end(), map_stack::erase(), finalized, active_tiles::furn_at< active_tile_data >(), map::furn_set(), g, get_map(), map::getabs(), map::getlocal(), map::i_at(), partial_con::id, player::is_npc(), player::is_player(), item_group::items_from(), trap::loadid, m_info, string_id< activity_type >::NULL_ID(), int_id< T >::obj(), map::partial_con_at(), map::partial_con_remove(), player_activity::placement, map::points_in_radius(), Character::pos(), construction::post_flags, construction::post_is_furniture, construction::post_special, construction::post_terrain, random_entry(), map::remove_trap(), construction::required_skills, npc::revert_after_activity(), ter_t::roof, Creature::set_moves(), player_activity::set_to_null(), map::spawn_items(), t_open_air, map::ter(), map::ter_set(), construction::time, map::tr_at(), tr_unfinished_construction, tripoint_above, and calendar::turn.
Referenced by activity_handlers::build_do_turn().
construction_color()
static nc_color construction_color (const std::string & con_name, bool highlight) static
Definition at line 246 of file construction.cpp.
{
    nc_color col = c_dark_gray;
    if( g->u.has_trait( trait_DEBUG_HS ) ) {
        col = c_white;
    } else if( can_construct( con_name ) ) {
        construction *con_first = nullptr;
        std::vector<construction *> cons = constructions_by_desc( con_name );
        const inventory &total_inv = g->u.crafting_inventory();
        for( auto &con : cons ) {
            if( con->requirements->can_make_with_inventory( total_inv, is_crafting_component ) ) {
                con_first = con;
                break;
            }
        }
        if( con_first != nullptr ) {
            col = c_white;
            for( const auto &pr : con_first->required_skills ) {
                int s_lvl = g->u.get_skill_level( pr.first );
                if( s_lvl < pr.second ) {
                    col = c_red;
                } else if( s_lvl < pr.second * 1.25 ) {
                    col = c_light_blue;
                }
            }
        }
    }
    return highlight ? hilite( col ) : col;
}
References c_dark_gray, c_light_blue, c_red, c_white, can_construct(), constructions_by_desc(), g, hilite(), is_crafting_component(), construction::required_skills, and trait_DEBUG_HS.
construction_menu()
construction_id construction_menu (const bool blueprint)
Definition at line 286 of file construction.cpp.
{
    if( !finalized ) {
        debugmsg( "construction_menu called before finalization" );
        return construction_id( -1 );
    }
    static bool hide_unconstructable = false;
    // only display constructions the player can theoretically perform
    std::vector<std::string> available;
    std::map<construction_category_id, std::vector<std::string>> cat_available;
    load_available_constructions( available, cat_available, hide_unconstructable );
    if( available.empty() ) {
        popup( _( "You can not construct anything here." ) );
        return construction_id( -1 );
    }
    int w_height = 0;
    int w_width = 0;
    catacurses::window w_con;
    int w_list_width = 0;
    int w_list_height = 0;
    const int w_list_x0 = 1;
    catacurses::window w_list;
    std::vector<std::string> notes;
    int pos_x = 0;
    int available_window_width = 0;
    int available_buffer_height = 0;
    construction_id ret( -1 );
    bool update_info = true;
    bool update_cat = true;
    bool isnew = true;
    int tabindex = 0;
    int select = 0;
    int offset = 0;
    bool exit = false;
    construction_category_id category_id;
    std::vector<std::string> constructs;
    //storage for the color text so it can be scrolled
    std::vector< std::vector < std::string > > construct_buffers;
    std::vector<std::string> full_construct_buffer;
    std::vector<int> construct_buffer_breakpoints;
    int total_project_breakpoints = 0;
    int current_construct_breakpoint = 0;
    const inventory &total_inv = g->u.crafting_inventory();
    input_context ctxt( "CONSTRUCTION" );
    ctxt.register_action( "UP", to_translation( "Move cursor up" ) );
    ctxt.register_action( "DOWN", to_translation( "Move cursor down" ) );
    ctxt.register_action( "RIGHT", to_translation( "Move tab right" ) );
    ctxt.register_action( "LEFT", to_translation( "Move tab left" ) );
    ctxt.register_action( "PAGE_UP" );
    ctxt.register_action( "PAGE_DOWN" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ctxt.register_action( "FILTER" );
    ctxt.register_action( "RESET_FILTER" );
    const std::vector<construction_category> &construct_cat = construction_categories::get_all();
    const int tabcount = static_cast<int>( construction_category::count() );
    std::string filter;
    const nc_color color_stage = c_white;
    ui_adaptor ui;
    const auto recalc_buffer = [&]() {
        //leave room for top and bottom UI text
        available_buffer_height = w_height - 3 - 3 - static_cast<int>( notes.size() );
        if( !constructs.empty() ) {
            if( select >= static_cast<int>( constructs.size() ) ) {
                select = 0;
            }
            std::string current_desc = constructs[select];
            //construct the project list buffer
            // Print stages and their requirement.
            std::vector<construction *> options = constructions_by_desc( current_desc );
            construct_buffers.clear();
            current_construct_breakpoint = 0;
            construct_buffer_breakpoints.clear();
            full_construct_buffer.clear();
            int stage_counter = 0;
            for( std::vector<construction *>::iterator it = options.begin();
                 it != options.end(); ++it ) {
                stage_counter++;
                construction *current_con = *it;
                if( hide_unconstructable && !can_construct( *current_con ) ) {
                    continue;
                }
                // Update the cached availability of components and tools in the requirement object
                current_con->requirements->can_make_with_inventory( total_inv, is_crafting_component );
                std::vector<std::string> current_buffer;
                const auto add_folded = [&]( const std::vector<std::string> &folded ) {
                    current_buffer.insert( current_buffer.end(), folded.begin(), folded.end() );
                };
                const auto add_line = [&]( const std::string & line ) {
                    add_folded( foldstring( line, available_window_width ) );
                };
                // display final product name only if more than one step.
                // Assume single stage constructions should be clear
                // in their title what their result is.
                if( !current_con->post_terrain.empty() && options.size() > 1 ) {
                    //also print out stage number when multiple stages are available
                    std::string current_line = string_format( _( "Stage/Variant #%d: " ), stage_counter );
                    // print name of the result of each stage
                    std::string result_string;
                    if( current_con->post_is_furniture ) {
                        result_string = furn_str_id( current_con->post_terrain ).obj().name();
                    } else {
                        result_string = ter_str_id( current_con->post_terrain ).obj().name();
                    }
                    current_line += colorize( result_string, color_title );
                    add_line( current_line );
                    // display description of the result for multi-stages
                    current_line = _( "Result: " );
                    if( current_con->post_is_furniture ) {
                        current_line += colorize(
                                            furn_str_id( current_con->post_terrain ).obj().description,
                                            color_data
                                        );
                    } else {
                        current_line += colorize(
                                            ter_str_id( current_con->post_terrain ).obj().description,
                                            color_data
                                        );
                    }
                    add_line( current_line );
                    // display description of the result for single stages
                } else if( !current_con->post_terrain.empty() ) {
                    std::string current_line = _( "Result: " );
                    if( current_con->post_is_furniture ) {
                        current_line += colorize(
                                            furn_str_id( current_con->post_terrain ).obj().description,
                                            color_data
                                        );
                    } else {
                        current_line += colorize(
                                            ter_str_id( current_con->post_terrain ).obj().description,
                                            color_data
                                        );
                    }
                    add_line( current_line );
                }
                // display required skill and difficulty
                if( current_con->required_skills.empty() ) {
                    add_line( _( "N/A" ) );
                } else {
                    std::string current_line = _( "Required skills: " ) + enumerate_as_string(
                                                   current_con->required_skills.begin(), current_con->required_skills.end(),
                    []( const std::pair<skill_id, int> &skill ) {
                        nc_color col;
                        int s_lvl = g->u.get_skill_level( skill.first );
                        if( s_lvl < skill.second ) {
                            col = c_red;
                        } else if( s_lvl < skill.second * 1.25 ) {
                            col = c_light_blue;
                        } else {
                            col = c_green;
                        }
                        return colorize( string_format( "%s (%d)", skill.first.obj().name(), skill.second ), col );
                    }, enumeration_conjunction::none );
                    add_line( current_line );
                }
                // TODO: Textify pre_flags to provide a bit more information.
                // Example: First step of dig pit could say something about
                // requiring diggable ground.
                if( !current_con->pre_terrain.empty() ) {
                    std::string require_string;
                    if( current_con->pre_is_furniture ) {
                        require_string = furn_str_id( current_con->pre_terrain )->name();
                    } else {
                        require_string = ter_str_id( current_con->pre_terrain )->name();
                    }
                    nc_color pre_color = has_pre_terrain( *current_con ) ? c_green : c_red;
                    add_line( _( "Requires: " ) + colorize( require_string, pre_color ) );
                }
                if( !current_con->pre_note.empty() ) {
                    add_line( _( "Annotation: " ) + colorize( _( current_con->pre_note ), color_data ) );
                }
                // get pre-folded versions of the rest of the construction project to be displayed later
                // get time needed
                add_folded( current_con->get_folded_time_string( available_window_width ) );
                add_folded( current_con->requirements->get_folded_tools_list( available_window_width, color_stage,
                            total_inv ) );
                add_folded( current_con->requirements->get_folded_components_list( available_window_width,
                            color_stage, total_inv, is_crafting_component ) );
                construct_buffers.push_back( current_buffer );
            }
            //determine where the printing starts for each project, so it can be scrolled to those points
            size_t current_buffer_location = 0;
            for( size_t i = 0; i < construct_buffers.size(); i++ ) {
                construct_buffer_breakpoints.push_back( static_cast<int>( current_buffer_location ) );
                full_construct_buffer.insert( full_construct_buffer.end(), construct_buffers[i].begin(),
                                              construct_buffers[i].end() );
                //handle text too large for one screen
                if( construct_buffers[i].size() > static_cast<size_t>( available_buffer_height ) ) {
                    construct_buffer_breakpoints.push_back( static_cast<int>( current_buffer_location +
                                                            static_cast<size_t>( available_buffer_height ) ) );
                }
                current_buffer_location += construct_buffers[i].size();
                if( i < construct_buffers.size() - 1 ) {
                    full_construct_buffer.push_back( std::string() );
                    current_buffer_location++;
                }
            }
            total_project_breakpoints = static_cast<int>( construct_buffer_breakpoints.size() );
        }
    };
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        w_height = TERMY;
        if( static_cast<int>( available.size() ) + 2 < w_height ) {
            w_height = available.size() + 2;
        }
        if( w_height < FULL_SCREEN_HEIGHT ) {
            w_height = FULL_SCREEN_HEIGHT;
        }
        w_width = std::max( FULL_SCREEN_WIDTH, TERMX * 2 / 3 );
        const int w_y0 = ( TERMY > w_height ) ? ( TERMY - w_height ) / 2 : 0;
        const int w_x0 = ( TERMX > w_width ) ? ( TERMX - w_width ) / 2 : 0;
        w_con = catacurses::newwin( w_height, w_width, point( w_x0, w_y0 ) );
        w_list_width = static_cast<int>( .375 * w_width );
        w_list_height = w_height - 4;
        w_list = catacurses::newwin( w_list_height, w_list_width,
                                     point( w_x0 + w_list_x0, w_y0 + 3 ) );
        pos_x = w_list_width + w_list_x0 + 2;
        available_window_width = w_width - pos_x - 1;
        recalc_buffer();
        ui.position_from_window( w_con );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        draw_grid( w_con, w_list_width + w_list_x0 );
        // Erase existing tab selection & list of constructions
        mvwhline( w_con, point_south_east, ' ', w_list_width );
        werase( w_list );
        // Print new tab listing
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        mvwprintz( w_con, point( 1, 1 ), c_yellow, "<< %s >>", construct_cat[tabindex].name() );
        // Determine where in the master list to start printing
        calcStartPos( offset, select, w_list_height, constructs.size() );
        // Print the constructions between offset and max (or how many will fit)
        cata::optional<point> cursor_pos;
        for( size_t i = 0; static_cast<int>( i ) < w_list_height &&
             ( i + offset ) < constructs.size(); i++ ) {
            int current = i + offset;
            std::string con_name = constructs[current];
            bool highlight = ( current == select );
            const point print_from( 0, i );
            if( highlight ) {
                cursor_pos = print_from;
            }
            trim_and_print( w_list, print_from, w_list_width,
                            construction_color( con_name, highlight ), _( con_name ) );
        }
        // Clear out lines for tools & materials
        for( int i = 1; i < w_height - 1; i++ ) {
            mvwhline( w_con, point( pos_x, i ), ' ', available_window_width );
        }
        // print the hotkeys regardless of if there are constructions
        for( size_t i = 0; i < notes.size(); ++i ) {
            trim_and_print( w_con, point( pos_x,
                                          w_height - 1 - static_cast<int>( notes.size() ) + static_cast<int>( i ) ),
                            available_window_width, c_white, notes[i] );
        }
        if( !constructs.empty() ) {
            if( select >= static_cast<int>( constructs.size() ) ) {
                select = 0;
            }
            std::string current_desc = constructs[select];
            // Print construction name
            trim_and_print( w_con, point( pos_x, 1 ), available_window_width, c_white, _( current_desc ) );
            if( current_construct_breakpoint > 0 ) {
                // Print previous stage indicator if breakpoint is past the beginning
                trim_and_print( w_con, point( pos_x, 2 ), available_window_width, c_white,
                                _( "Press %s to show previous stage(s)." ),
                                ctxt.get_desc( "PAGE_UP" ) );
            }
            if( static_cast<size_t>( construct_buffer_breakpoints[current_construct_breakpoint] +
                                     available_buffer_height ) < full_construct_buffer.size() ) {
                // Print next stage indicator if more breakpoints are remaining after screen height
                trim_and_print( w_con, point( pos_x, w_height - 2 - static_cast<int>( notes.size() ) ),
                                available_window_width,
                                c_white, _( "Press %s to show next stage(s)." ),
                                ctxt.get_desc( "PAGE_DOWN" ) );
            }
            // Leave room for above/below indicators
            int ypos = 3;
            nc_color stored_color = color_stage;
            for( size_t i = static_cast<size_t>( construct_buffer_breakpoints[current_construct_breakpoint] );
                 i < full_construct_buffer.size(); i++ ) {
                //the value of 3 is from leaving room at the top of window
                if( ypos > available_buffer_height + 3 ) {
                    break;
                }
                print_colored_text( w_con, point( w_list_width + w_list_x0 + 2, ypos++ ), stored_color, color_stage,
                                    full_construct_buffer[i] );
            }
        }
        draw_scrollbar( w_con, select, w_list_height, constructs.size(), point( 0, 3 ) );
        wnoutrefresh( w_con );
        // place the cursor at the selected construction name as expected by screen readers
        if( cursor_pos ) {
            wmove( w_list, cursor_pos.value() );
        }
        wnoutrefresh( w_list );
    } );
    do {
        if( update_cat ) {
            update_cat = false;
            cata::optional<std::string> last_construction;
            if( isnew ) {
                filter = uistate.construction_filter;
                tabindex = uistate.construction_tab.is_valid()
                           ? uistate.construction_tab.id().to_i() : 0;
                last_construction = uistate.last_construction;
            } else if( select >= 0 && static_cast<size_t>( select ) < constructs.size() ) {
                last_construction = constructs[select];
            }
            category_id = construct_cat[tabindex].id;
            if( category_id == construction_category_ALL ) {
                constructs = available;
            } else if( category_id == construction_category_FILTER ) {
                constructs.clear();
                std::copy_if( available.begin(), available.end(),
                              std::back_inserter( constructs ),
                [&]( const std::string & a ) {
                    return lcmatch( _( a ), filter );
                } );
            } else {
                constructs = cat_available[category_id];
            }
            select = 0;
            if( last_construction ) {
                const auto it = std::find( constructs.begin(), constructs.end(),
                                           *last_construction );
                if( it != constructs.end() ) {
                    select = std::distance( constructs.begin(), it );
                }
            }
        }
        isnew = false;
        if( update_info ) {
            update_info = false;
            notes.clear();
            if( tabindex == tabcount - 1 && !filter.empty() ) {
                notes.push_back( string_format( _( "Press [<color_red>%s</color>] to clear filter." ),
                                                ctxt.get_desc( "RESET_FILTER" ) ) );
            }
            notes.push_back( string_format( _( "Press [<color_yellow>%s or %s</color>] to tab." ),
                                            ctxt.get_desc( "LEFT" ),
                                            ctxt.get_desc( "RIGHT" ) ) );
            notes.push_back( string_format( _( "Press [<color_yellow>%s</color>] to search." ),
                                            ctxt.get_desc( "FILTER" ) ) );
            if( !hide_unconstructable ) {
                notes.push_back( string_format(
                                     _( "Press [<color_yellow>%s</color>] to hide unavailable constructions." ),
                                     ctxt.get_desc( "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" ) ) );
            } else {
                notes.push_back( string_format(
                                     _( "Press [<color_red>%s</color>] to show unavailable constructions." ),
                                     ctxt.get_desc( "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" ) ) );
            }
            notes.push_back( string_format(
                                 _( "Press [<color_yellow>%s</color>] to view and edit keybindings." ),
                                 ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
            recalc_buffer();
        } // Finished updating
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "FILTER" ) {
            string_input_popup popup;
            popup
            .title( _( "Search" ) )
            .width( 50 )
            .description( _( "Filter" ) )
            .max_length( 100 )
            .text( tabindex == tabcount - 1 ? filter : std::string() )
            .query();
            if( popup.confirmed() ) {
                filter = popup.text();
                uistate.construction_filter = filter;
                update_info = true;
                update_cat = true;
                tabindex = tabcount - 1;
            }
        } else if( action == "RESET_FILTER" ) {
            if( tabindex == tabcount - 1 && !filter.empty() ) {
                filter.clear();
                uistate.construction_filter.clear();
                update_info = true;
                update_cat = true;
            }
        } else if( action == "DOWN" ) {
            update_info = true;
            if( select < static_cast<int>( constructs.size() ) - 1 ) {
                select++;
            } else {
                select = 0;
            }
        } else if( action == "UP" ) {
            update_info = true;
            if( select > 0 ) {
                select--;
            } else {
                select = constructs.size() - 1;
            }
        } else if( action == "LEFT" ) {
            update_info = true;
            update_cat = true;
            tabindex--;
            if( tabindex < 0 ) {
                tabindex = tabcount - 1;
            }
        } else if( action == "RIGHT" ) {
            update_info = true;
            update_cat = true;
            tabindex = ( tabindex + 1 ) % tabcount;
        } else if( action == "PAGE_UP" ) {
            if( current_construct_breakpoint > 0 ) {
                current_construct_breakpoint--;
            }
            if( current_construct_breakpoint < 0 ) {
                current_construct_breakpoint = 0;
            }
        } else if( action == "PAGE_DOWN" ) {
            if( current_construct_breakpoint < total_project_breakpoints - 1 ) {
                current_construct_breakpoint++;
            }
            if( current_construct_breakpoint >= total_project_breakpoints ) {
                current_construct_breakpoint = total_project_breakpoints - 1;
            }
        } else if( action == "QUIT" ) {
            exit = true;
        } else if( action == "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" ) {
            update_info = true;
            update_cat = true;
            hide_unconstructable = !hide_unconstructable;
            offset = 0;
            load_available_constructions( available, cat_available, hide_unconstructable );
        } else if( action == "CONFIRM" ) {
            if( constructs.empty() || select >= static_cast<int>( constructs.size() ) ) {
                // Nothing to be done here
                continue;
            }
            if( !blueprint ) {
                if( player_can_build( g->u, total_inv, constructs[select] ) ) {
                    if( !player_can_see_to_build( g->u, constructs[select] ) ) {
                        add_msg( m_info, _( "It is too dark to construct right now." ) );
                    } else {
                        ui.reset();
                        place_construction( constructs[select] );
                        uistate.last_construction = constructs[select];
                    }
                    exit = true;
                } else {
                    popup( _( "You can't build that!" ) );
                    update_info = true;
                }
            } else {
                // get the index of the overall constructions list from current_desc
                const std::vector<construction> &list_constructions = get_constructions();
                for( int i = 0; i < static_cast<int>( list_constructions.size() ); ++i ) {
                    if( constructs[select] == list_constructions[i].description ) {
                        ret = construction_id( i );
                        break;
                    }
                }
                exit = true;
            }
        }
    } while( !exit );
    uistate.construction_tab = int_id<construction_category>( tabindex ).id();
    return ret;
}
References _, available, c_green, c_red, c_white, can_construct(), requirement_data::can_make_with_inventory(), color_data, color_title, colorize(), constructions_by_desc(), construction_category::count(), debugmsg, map_data_common_t::description, enumerate_as_string(), finalized, foldstring(), g, construction_categories::get_all(), has_pre_terrain(), is_crafting_component(), line(), load_available_constructions(), map_data_common_t::name(), none, string_id< T >::obj(), PATH_INFO::options(), popup(), construction::post_is_furniture, construction::post_terrain, input_context::register_action(), construction::required_skills, construction::requirements, cata::hash64_detail::ret, om_direction::size, string_format(), and to_translation().
Referenced by game::handle_action(), and blueprint_options::query_con().
constructions_by_desc()
static std::vector< construction * > constructions_by_desc (const std::string & description) static
Definition at line 187 of file construction.cpp.
{
    if( !finalized ) {
        debugmsg( "constructions_by_desc called before finalization" );
        return {};
    }
    std::vector<construction *> result;
    for( auto &constructions_a : constructions ) {
        if( constructions_a.description == description ) {
            result.push_back( &constructions_a );
        }
    }
    return result;
}
References constructions, debugmsg, and finalized.
Referenced by can_construct(), construction_color(), construction_menu(), place_construction(), player_can_build(), and player_can_see_to_build().
draw_grid()
static void draw_grid (const catacurses::window & w, const int list_width) static
Definition at line 230 of file construction.cpp.
{
    draw_border( w );
    mvwprintz( w, point( 2, 0 ), c_light_red, _( " Construction " ) );
    // draw internal lines
    mvwvline( w, point( list_width, 1 ), LINE_XOXO, getmaxy( w ) - 2 );
    mvwhline( w, point( 1, 2 ), LINE_OXOX, list_width );
    // draw intersections
    mvwputch( w, point( list_width, 0 ), c_light_gray, LINE_OXXX );
    mvwputch( w, point( list_width, getmaxy( w ) - 1 ), c_light_gray, LINE_XXOX );
    mvwputch( w, point( 0, 2 ), c_light_gray, LINE_XXXO );
    mvwputch( w, point( list_width, 2 ), c_light_gray, LINE_XOXX );
    wnoutrefresh( w );
}
References _, c_light_gray, c_light_red, draw_border(), catacurses::getmaxy(), LINE_OXOX, LINE_OXXX, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, catacurses::mvwhline(), mvwprintz(), mvwputch(), catacurses::mvwvline(), and catacurses::wnoutrefresh().
finalize_constructions()
void finalize_constructions ()
Definition at line 1738 of file construction.cpp.
{
    std::vector<item_comp> frame_items;
    for( const auto &e : vpart_info::all() ) {
        const vpart_info &vp = e.second;
        if( !vp.has_flag( flag_INITIAL_PART ) ) {
            continue;
        }
        frame_items.push_back( item_comp( vp.item, 1 ) );
    }
    if( frame_items.empty() ) {
        debugmsg( "No valid frames detected for vehicle construction" );
    }
    for( construction &con : constructions ) {
        if( con.vehicle_start ) {
            const_cast<requirement_data &>( con.requirements.obj() ).get_components().push_back( frame_items );
        }
        bool is_valid_construction_category = false;
        for( const construction_category &cc : construction_categories::get_all() ) {
            if( con.category == cc.id ) {
                is_valid_construction_category = true;
                break;
            }
        }
        if( !is_valid_construction_category ) {
            debugmsg( "Invalid construction category (%s) defined for construction (%s)", con.category.str(),
                      con.description );
        }
        requirement_data requirements_ = std::accumulate( con.reqs_using.begin(), con.reqs_using.end(),
                                         *con.requirements,
        []( const requirement_data & lhs, const std::pair<requirement_id, int> &rhs ) {
            return lhs + ( *rhs.first * rhs.second );
        } );
        requirement_data::save_requirement( requirements_, con.requirements );
        con.reqs_using.clear();
    }
    constructions.erase( std::remove_if( constructions.begin(), constructions.end(),
    [&]( const construction & c ) {
        return c.requirements->is_blacklisted();
    } ), constructions.end() );
    construction_id_map.clear();
    for( size_t i = 0; i < constructions.size(); i++ ) {
        constructions[ i ].id = construction_id( i );
        construction_id_map.emplace( constructions[i].str_id, constructions[i].id );
    }
    finalized = true;
}
References vpart_info::all(), c, construction_id_map, constructions, debugmsg, finalized, flag_INITIAL_PART(), construction_categories::get_all(), vpart_info::has_flag(), vpart_info::item, and requirement_data::save_requirement().
Referenced by DynamicDataLoader::finalize_loaded_data().
flag_FLAT()
static const std::string flag_FLAT ("FLAT") static
Referenced by construct::check_empty().
flag_INITIAL_PART()
static const std::string flag_INITIAL_PART ("INITIAL_PART") static
Referenced by finalize_constructions(), and vpart_from_item().
flag_SUPPORTS_ROOF()
static const std::string flag_SUPPORTS_ROOF ("SUPPORTS_ROOF") static
Referenced by construct::check_support().
get_build_reqs_for_furn_ter_ids()
void get_build_reqs_for_furn_ter_ids (const std::pair< std::map< ter_id, int >, std::map< furn_id, int > > & changed_ids, build_reqs & total_reqs)
Definition at line 1792 of file construction.cpp.
{
    if( !finalized ) {
        debugmsg( "get_build_reqs_for_furn_ter_ids called before finalization" );
        return;
    }
    std::map<construction_id, int> total_builds;
    // iteratively recurse through the pre-terrains until the pre-terrain is empty, adding
    // the constructions to the total_builds map
    const auto add_builds = [&total_builds]( const construction & build, int count ) {
        if( total_builds.find( build.id ) == total_builds.end() ) {
            total_builds[build.id] = 0;
        }
        total_builds[build.id] += count;
        std::string build_pre_ter = build.pre_terrain;
        while( !build_pre_ter.empty() ) {
            for( const construction &pre_build : constructions ) {
                if( pre_build.category == construction_category_REPAIR ) {
                    continue;
                }
                if( pre_build.post_terrain == build_pre_ter ) {
                    if( total_builds.find( pre_build.id ) == total_builds.end() ) {
                        total_builds[pre_build.id] = 0;
                    }
                    total_builds[pre_build.id] += count;
                    build_pre_ter = pre_build.pre_terrain;
                    break;
                }
            }
            break;
        }
    };
    // go through the list of terrains and add their constructions and any pre-constructions
    // to the map of total builds
    for( const auto &ter_data : changed_ids.first ) {
        for( const construction &build : constructions ) {
            if( build.post_terrain.empty() || build.post_is_furniture ||
                build.category == construction_category_REPAIR ) {
                continue;
            }
            if( ter_id( build.post_terrain ) == ter_data.first ) {
                add_builds( build, ter_data.second );
                break;
            }
        }
    }
    // same, but for furniture
    for( const auto &furn_data : changed_ids.second ) {
        for( const construction &build : constructions ) {
            if( build.post_terrain.empty() || !build.post_is_furniture ||
                build.category == construction_category_REPAIR ) {
                continue;
            }
            if( furn_id( build.post_terrain ) == furn_data.first ) {
                add_builds( build, furn_data.second );
                break;
            }
        }
    }
    for( const auto &build_data : total_builds ) {
        const construction &build = build_data.first.obj();
        const int count = build_data.second;
        total_reqs.time += build.time * count;
        if( total_reqs.reqs.find( build.requirements ) == total_reqs.reqs.end() ) {
            total_reqs.reqs[build.requirements] = 0;
        }
        total_reqs.reqs[build.requirements] += count;
        for( const auto &req_skill : build.required_skills ) {
            if( total_reqs.skills.find( req_skill.first ) == total_reqs.skills.end() ) {
                total_reqs.skills[req_skill.first] = req_skill.second;
            } else if( total_reqs.skills[req_skill.first] < req_skill.second ) {
                total_reqs.skills[req_skill.first] = req_skill.second;
            }
        }
    }
}
References construction::category, construction_category_REPAIR, constructions, detail::count(), debugmsg, finalized, construction::id, construction::post_is_furniture, construction::post_terrain, construction::pre_terrain, build_reqs::reqs, construction::required_skills, construction::requirements, build_reqs::skills, build_reqs::time, and construction::time.
Referenced by recipe::check_blueprint_requirements().
get_constructions()
const std::vector< construction > & get_constructions ()
Definition at line 276 of file construction.cpp.
{
    if( !finalized ) {
        debugmsg( "get_constructions called before finalization" );
        static std::vector<construction> fake_constructions;
        return fake_constructions;
    }
    return constructions;
}
References constructions, debugmsg, and finalized.
Referenced by can_do_activity_there(), and blueprint_options::query_con().
get_orthogonal_neighbors()
std::array< tripoint, 4 > get_orthogonal_neighbors (const tripoint & p) inline
Definition at line 1080 of file construction.cpp.
{
    return {{
            p + point_north,
            p + point_south,
            p + point_west,
            p + point_east
        }};
}
References point_east, point_north, point_south, and point_west.
Referenced by construct::check_support().
has_pre_terrain() [1/2]
static bool has_pre_terrain (const construction & con) static
Definition at line 166 of file construction.cpp.
{
    for( const tripoint &p : get_map().points_in_radius( g->u.pos(), 1 ) ) {
        if( p != g->u.pos() && has_pre_terrain( con, p ) ) {
            return true;
        }
    }
    return false;
}
References g, get_map(), has_pre_terrain(), and points_in_radius().
has_pre_terrain() [2/2]
static bool has_pre_terrain (const construction & con, const tripoint & p) static
Definition at line 150 of file construction.cpp.
{
    if( con.pre_terrain.empty() ) {
        return true;
    }
    map &here = get_map();
    if( con.pre_is_furniture ) {
        furn_id f = furn_id( con.pre_terrain );
        return here.furn( p ) == f;
    } else {
        ter_id t = ter_id( con.pre_terrain );
        return here.ter( p ) == t;
    }
}
References map::furn(), get_map(), construction::pre_is_furniture, construction::pre_terrain, and map::ter().
Referenced by can_construct(), construction_menu(), and has_pre_terrain().
load_available_constructions()
static void load_available_constructions (std::vector< std::string > & available, std::map< construction_category_id, std::vector< std::string > > & cat_available, bool hide_unconstructable) static
Definition at line 202 of file construction.cpp.
{
    cat_available.clear();
    available.clear();
    if( !finalized ) {
        debugmsg( "load_available_constructions called before finalization" );
        return;
    }
    for( auto &it : constructions ) {
        if( it.on_display && ( !hide_unconstructable ||
                               ( can_construct( it ) && player_can_build( g->u, g->u.crafting_inventory(), it ) ) ) ) {
            bool already_have_it = false;
            for( auto &avail_it : available ) {
                if( avail_it == it.description ) {
                    already_have_it = true;
                    break;
                }
            }
            if( !already_have_it ) {
                available.push_back( it.description );
                cat_available[it.category].push_back( it.description );
            }
        }
    }
}
References available, can_construct(), constructions, debugmsg, finalized, g, and player_can_build().
Referenced by construction_menu().
load_construction()
void load_construction (const JsonObject & jo)
Definition at line 1506 of file construction.cpp.
{
    construction con;
    // These ids are only temporary. The actual ids are determined in finalize_construction,
    // after removing blacklisted constructions.
    con.id = construction_id( -1 );
    con.str_id = construction_str_id( jo.get_string( "id" ) );
    if( con.str_id.is_null() ) {
        jo.throw_error( "Null construction id specified", "id" );
    } else if( construction_id_map.find( con.str_id ) != construction_id_map.end() ) {
        jo.throw_error( "Duplicate construction id", "id" );
    }
    con.description = jo.get_string( "description" );
    if( jo.has_member( "required_skills" ) ) {
        for( JsonArray arr : jo.get_array( "required_skills" ) ) {
            con.required_skills[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
        }
    } else {
        skill_id legacy_skill( jo.get_string( "skill", skill_fabrication.str() ) );
        int legacy_diff = jo.get_int( "difficulty" );
        con.required_skills[ legacy_skill ] = legacy_diff;
    }
    con.category = construction_category_id( jo.get_string( "category", "OTHER" ) );
    if( jo.has_int( "time" ) ) {
        con.time = to_moves<int>( time_duration::from_minutes( jo.get_int( "time" ) ) );
    } else if( jo.has_string( "time" ) ) {
        con.time = to_moves<int>( read_from_json_string<time_duration>( *jo.get_raw( "time" ),
                                  time_duration::units ) );
    }
    const requirement_id req_id( "inline_construction_" + con.str_id.str() );
    requirement_data::load_requirement( jo, req_id );
    con.requirements = req_id;
    if( jo.has_string( "using" ) ) {
        con.reqs_using = { { requirement_id( jo.get_string( "using" ) ), 1} };
    } else if( jo.has_array( "using" ) ) {
        for( JsonArray cur : jo.get_array( "using" ) ) {
            con.reqs_using.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
        }
    }
    con.pre_note = jo.get_string( "pre_note", "" );
    con.pre_terrain = jo.get_string( "pre_terrain", "" );
    if( con.pre_terrain.size() > 1
        && con.pre_terrain[0] == 'f'
        && con.pre_terrain[1] == '_' ) {
        con.pre_is_furniture = true;
    } else {
        con.pre_is_furniture = false;
    }
    con.post_terrain = jo.get_string( "post_terrain", "" );
    if( con.post_terrain.size() > 1
        && con.post_terrain[0] == 'f'
        && con.post_terrain[1] == '_' ) {
        con.post_is_furniture = true;
    } else {
        con.post_is_furniture = false;
    }
    con.pre_flags = jo.get_tags( "pre_flags" );
    con.post_flags = jo.get_tags( "post_flags" );
    if( jo.has_member( "byproducts" ) ) {
        con.byproduct_item_group = item_group::load_item_group( jo.get_member( "byproducts" ),
                                   "collection" );
    }
    static const std::map<std::string, std::function<bool( const tripoint & )>> pre_special_map = {{
            { "", construct::check_nothing },
            { "check_empty", construct::check_empty },
            { "check_support", construct::check_support },
            { "check_deconstruct", construct::check_deconstruct },
            { "check_empty_up_OK", construct::check_empty_up_OK },
            { "check_up_OK", construct::check_up_OK },
            { "check_down_OK", construct::check_down_OK },
            { "check_no_trap", construct::check_no_trap },
            { "check_ramp_low", construct::check_ramp_low },
            { "check_ramp_high", construct::check_ramp_high }
        }
    };
    static const std::map<std::string, std::function<void( const tripoint & )>> post_special_map = {{
            { "", construct::done_nothing },
            { "done_trunk_plank", construct::done_trunk_plank },
            { "done_grave", construct::done_grave },
            { "done_vehicle", construct::done_vehicle },
            { "done_deconstruct", construct::done_deconstruct },
            { "done_dig_stair", construct::done_dig_stair },
            { "done_mine_downstair", construct::done_mine_downstair },
            { "done_mine_upstair", construct::done_mine_upstair },
            { "done_wood_stairs", construct::done_wood_stairs },
            { "done_window_curtains", construct::done_window_curtains },
            { "done_extract_maybe_revert_to_dirt", construct::done_extract_maybe_revert_to_dirt },
            { "done_mark_firewood", construct::done_mark_firewood },
            { "done_mark_practice_target", construct::done_mark_practice_target },
            { "done_ramp_low", construct::done_ramp_low },
            { "done_ramp_high", construct::done_ramp_high }
        }
    };
    std::map<std::string, std::function<void( const tripoint & )>> explain_fail_map;
    if( jo.has_string( "pre_special" ) &&
        jo.get_string( "pre_special" )  == std::string( "check_deconstruct" ) ) {
        explain_fail_map[""] = construct::failure_deconstruct;
    } else {
        explain_fail_map[""] = construct::failure_standard;
    }
    assign_or_debugmsg( con.pre_special, jo.get_string( "pre_special", "" ), pre_special_map );
    assign_or_debugmsg( con.post_special, jo.get_string( "post_special", "" ), post_special_map );
    assign_or_debugmsg( con.explain_failure, jo.get_string( "explain_failure", "" ), explain_fail_map );
    con.vehicle_start = jo.get_bool( "vehicle_start", false );
    con.on_display = jo.get_bool( "on_display", true );
    con.dark_craftable = jo.get_bool( "dark_craftable", false );
    constructions.push_back( con );
    construction_id_map.emplace( con.str_id, con.id );
}
References assign_or_debugmsg(), construction::byproduct_item_group, construction::category, construct::check_deconstruct(), construct::check_down_OK(), construct::check_empty(), construct::check_empty_up_OK(), construct::check_no_trap(), construct::check_nothing(), construct::check_ramp_high(), construct::check_ramp_low(), construct::check_support(), construct::check_up_OK(), construction_id_map, constructions, construction::dark_craftable, construction::description, construct::done_deconstruct(), construct::done_dig_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_downstair(), construct::done_mine_upstair(), construct::done_nothing(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_trunk_plank(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wood_stairs(), construction::explain_failure, construct::failure_deconstruct(), construct::failure_standard(), time_duration::from_minutes(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_raw(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_string(), construction::id, string_id< T >::is_null(), item_group::load_item_group(), requirement_data::load_requirement(), construction::on_display, construction::post_flags, construction::post_is_furniture, construction::post_special, construction::post_terrain, construction::pre_flags, construction::pre_is_furniture, construction::pre_note, construction::pre_special, construction::pre_terrain, construction::reqs_using, construction::required_skills, construction::requirements, skill_fabrication, string_id< T >::str(), construction::str_id, JsonObject::throw_error(), construction::time, time_duration::units, and construction::vehicle_start.
Referenced by DynamicDataLoader::initialize().
place_construction()
void place_construction (const std::string & desc) static
Definition at line 894 of file construction.cpp.
{
    const inventory &total_inv = g->u.crafting_inventory();
    std::vector<construction *> cons = constructions_by_desc( desc );
    std::map<tripoint, const construction *> valid;
    map &here = get_map();
    for( const tripoint &p : here.points_in_radius( g->u.pos(), 1 ) ) {
        for( const auto *con : cons ) {
            if( p != g->u.pos() && can_construct( *con, p ) && player_can_build( g->u, total_inv, *con ) ) {
                valid[ p ] = con;
            }
        }
    }
    shared_ptr_fast<game::draw_callback_t> draw_valid = make_shared_fast<game::draw_callback_t>( [&]() {
        map &here = get_map();
        for( auto &elem : valid ) {
            here.drawsq( g->w_terrain, elem.first, drawsq_params().highlight( true ).show_items( true ) );
        }
    } );
    g->add_draw_callback( draw_valid );
    const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Construct where?" ) );
    if( !pnt_ ) {
        return;
    }
    const tripoint pnt = *pnt_;
    if( valid.find( pnt ) == valid.end() ) {
        cons.front()->explain_failure( pnt );
        return;
    }
    // Maybe there is already a partial_con on an existing trap, that isn't caught by the usual trap-checking.
    // because the pre-requisite construction is already a trap anyway.
    // This shouldn't normally happen, unless it's a spike pit being built on a pit for example.
    partial_con *pre_c = here.partial_con_at( pnt );
    if( pre_c ) {
        add_msg( m_info,
                 _( "There is already an unfinished construction there, examine it to continue working on it" ) );
        return;
    }
    std::list<item> used;
    const construction &con = *valid.find( pnt )->second;
    // create the partial construction struct
    partial_con pc;
    pc.id = con.id;
    pc.counter = 0;
    // Set the trap that has the examine function
    // Special handling for constructions that take place on existing traps.
    // Basically just don't add the unfinished construction trap.
    // TODO: handle this cleaner, instead of adding a special case to pit iexamine.
    if( here.tr_at( pnt ).loadid == tr_null ) {
        here.trap_set( pnt, tr_unfinished_construction );
    }
    // Use up the components
    for( const auto &it : con.requirements->get_components() ) {
        std::list<item> tmp = g->u.consume_items( it, 1, is_crafting_component );
        used.splice( used.end(), tmp );
    }
    pc.components = used;
    here.partial_con_set( pnt, pc );
    for( const auto &it : con.requirements->get_tools() ) {
        g->u.consume_tools( it );
    }
    g->u.assign_activity( ACT_BUILD );
    g->u.activity.placement = here.getabs( pnt );
}
References _, ACT_BUILD, add_msg(), can_construct(), choose_adjacent(), partial_con::components, constructions_by_desc(), partial_con::counter, map::drawsq(), g, requirement_data::get_components(), get_map(), requirement_data::get_tools(), map::getabs(), partial_con::id, construction::id, is_crafting_component(), trap::loadid, m_info, map::partial_con_at(), map::partial_con_set(), player_can_build(), map::points_in_radius(), construction::requirements, map::tr_at(), tr_null, tr_unfinished_construction, and map::trap_set().
player_can_build() [1/2]
bool player_can_build (player & p, const inventory & inv, const construction & con)
Definition at line 820 of file construction.cpp.
{
    if( p.has_trait( trait_DEBUG_HS ) ) {
        return true;
    }
    if( !p.meets_skill_requirements( con ) ) {
        return false;
    }
    return con.requirements->can_make_with_inventory( inv, is_crafting_component );
}
References requirement_data::can_make_with_inventory(), Character::has_trait(), is_crafting_component(), Character::meets_skill_requirements(), construction::requirements, and trait_DEBUG_HS.
player_can_build() [2/2]
bool player_can_build (player & p, const inventory & inv, const std::string & desc) static
Definition at line 808 of file construction.cpp.
{
    // check all with the same desc to see if player can build any
    std::vector<construction *> cons = constructions_by_desc( desc );
    for( auto &con : cons ) {
        if( player_can_build( p, inv, *con ) ) {
            return true;
        }
    }
    return false;
}
References constructions_by_desc(), and player_can_build().
Referenced by find_base_construction(), load_available_constructions(), place_construction(), and player_can_build().
player_can_see_to_build()
bool player_can_see_to_build (player & p, const std::string & desc)
Definition at line 833 of file construction.cpp.
{
    if( character_funcs::can_see_fine_details( p ) || p.has_trait( trait_DEBUG_HS ) ) {
        return true;
    }
    std::vector<construction *> cons = constructions_by_desc( desc );
    for( construction *&con : cons ) {
        if( con->dark_craftable ) {
            return true;
        }
    }
    return false;
}
References character_funcs::can_see_fine_details(), constructions_by_desc(), Character::has_trait(), and trait_DEBUG_HS.
reset_constructions()
void reset_constructions ()
Definition at line 1629 of file construction.cpp.
{
    constructions.clear();
    construction_id_map.clear();
    finalized = false;
}
References construction_id_map, constructions, and finalized.
Referenced by DynamicDataLoader::unload_data().
standardize_construction_times()
void standardize_construction_times (const int time)
Set all constructions to take the specified time.
Definition at line 176 of file construction.cpp.
{
    if( !finalized ) {
        debugmsg( "standardize_construction_times called before finalization" );
        return;
    }
    for( auto &c : constructions ) {
        c.time = time;
    }
}
References c, constructions, debugmsg, and finalized.
Referenced by defense_game::init_constructions().
unroll_digging()
static void unroll_digging (const int numer_of_2x4s) static
Definition at line 1313 of file construction.cpp.
{
    // refund components!
    item rope( "rope_30" );
    map &here = get_map();
    here.add_item_or_charges( g->u.pos(), rope );
    // presuming 2x4 to conserve lumber.
    here.spawn_item( g->u.pos(), itype_2x4, numer_of_2x4s );
}
References map::add_item_or_charges(), g, get_map(), itype_2x4, and map::spawn_item().
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
vpart_from_item()
static vpart_id vpart_from_item (const itype_id & item_id) static
Definition at line 1206 of file construction.cpp.
{
    for( const auto &e : vpart_info::all() ) {
        const vpart_info &vp = e.second;
        if( vp.item == item_id && vp.has_flag( flag_INITIAL_PART ) ) {
            return vp.get_id();
        }
    }
    // The INITIAL_PART flag is optional, if no part (based on the given item) has it, just use the
    // first part that is based in the given item (this is fine for example if there is only one
    // such type anyway).
    for( const auto &e : vpart_info::all() ) {
        const vpart_info &vp = e.second;
        if( vp.item == item_id ) {
            return vp.get_id();
        }
    }
    debugmsg( "item %s used by construction is not base item of any vehicle part!", item_id.c_str() );
    static const vpart_id frame_id( "frame_vertical_2" );
    return frame_id;
}
References vpart_info::all(), string_id< T >::c_str(), debugmsg, flag_INITIAL_PART(), vpart_info::get_id(), vpart_info::has_flag(), and vpart_info::item.
Referenced by construct::done_vehicle().
Variable Documentation
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by place_construction().
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
Referenced by complete_construction().
color_data
const deferred_color color_data = def_c_cyan static
Definition at line 148 of file construction.cpp.
Referenced by construction_menu(), and construction::get_time_string().
color_title
const deferred_color color_title = def_c_light_red static
Definition at line 147 of file construction.cpp.
Referenced by construction_menu().
construction_category_ALL
const construction_category_id construction_category_ALL("ALL") ("ALL") static
construction_category_FILTER
const construction_category_id construction_category_FILTER("FILTER") ("FILTER") static
construction_category_REPAIR
const construction_category_id construction_category_REPAIR("REPAIR") ("REPAIR") static
Referenced by get_build_reqs_for_furn_ter_ids().
construction_id_map
std::map<construction_str_id, construction_id> construction_id_map static
Definition at line 138 of file construction.cpp.
Referenced by check_constructions(), finalize_constructions(), load_construction(), and reset_constructions().
constructions
std::vector<construction> constructions static
Definition at line 137 of file construction.cpp.
Referenced by check_constructions(), constructions_by_desc(), finalize_constructions(), get_build_reqs_for_furn_ter_ids(), get_constructions(), load_available_constructions(), load_construction(), reset_constructions(), and standardize_construction_times().
finalized
bool finalized = false static
Definition at line 95 of file construction.cpp.
Referenced by complete_construction(), construction_menu(), constructions_by_desc(), finalize_constructions(), get_build_reqs_for_furn_ter_ids(), get_constructions(), load_available_constructions(), reset_constructions(), and standardize_construction_times().
itype_2x4
const itype_id itype_2x4("2x4") ("2x4") static
Referenced by unroll_digging().
itype_nail
const itype_id itype_nail("nail") ("nail") static
Referenced by construct::done_window_curtains().
itype_sheet
const itype_id itype_sheet("sheet") ("sheet") static
Referenced by construct::done_window_curtains().
itype_stick
const itype_id itype_stick("stick") ("stick") static
Referenced by construct::done_window_curtains().
itype_string_36
const itype_id itype_string_36("string_36") ("string_36") static
Referenced by construct::done_window_curtains().
null_construction
const construction null_construction {} static
Definition at line 1874 of file construction.cpp.
qual_CUT
const quality_id qual_CUT("CUT") ("CUT") static
Referenced by construct::done_grave().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by construct::done_deconstruct().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by load_construction().
tr_firewood_source
const trap_str_id tr_firewood_source("tr_firewood_source") ("tr_firewood_source") static
Referenced by construct::done_mark_firewood().
tr_practice_target
const trap_str_id tr_practice_target("tr_practice_target") ("tr_practice_target") static
Referenced by construct::done_mark_practice_target().
tr_unfinished_construction
const trap_str_id tr_unfinished_construction("tr_unfinished_construction") ("tr_unfinished_construction") static
Referenced by complete_construction(), and place_construction().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by construction_color(), construct::done_vehicle(), player_can_build(), and player_can_see_to_build().
trait_PAINRESIST_TROGLO
const trait_id trait_PAINRESIST_TROGLO("PAINRESIST_TROGLO") ("PAINRESIST_TROGLO") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by construct::done_grave().
trait_STOCKY_TROGLO
const trait_id trait_STOCKY_TROGLO("STOCKY_TROGLO") ("STOCKY_TROGLO") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().