Cataclysm BN: src/coordinate_conversions.cpp File Reference
coordinate_conversions.cpp File Reference
#include "coordinate_conversions.h"
#include "game_constants.h"
Functions
static int divide (int v, int m)
static int divide (int v, int m, int &r)
point omt_to_om_copy (const point &p)
This file defines legacy coordinate conversion functions.
tripoint omt_to_om_copy (const tripoint &p)
void omt_to_om (int &x, int &y)
point omt_to_om_remain (int &x, int &y)
point om_to_omt_copy (const point &p)
point sm_to_omt_copy (const point &p)
tripoint sm_to_omt_copy (const tripoint &p)
void sm_to_omt (int &x, int &y)
point sm_to_omt_remain (int &x, int &y)
point sm_to_om_copy (const point &p)
tripoint sm_to_om_copy (const tripoint &p)
void sm_to_om (int &x, int &y)
point sm_to_om_remain (int &x, int &y)
point omt_to_ms_copy (const point &p)
point omt_to_sm_copy (const point &p)
tripoint omt_to_sm_copy (const tripoint &p)
void omt_to_sm (int &x, int &y)
point om_to_sm_copy (const point &p)
tripoint om_to_sm_copy (const tripoint &p)
void om_to_sm (int &x, int &y)
point ms_to_sm_copy (const point &p)
tripoint ms_to_sm_copy (const tripoint &p)
void ms_to_sm (int &x, int &y)
point ms_to_sm_remain (int &x, int &y)
point sm_to_ms_copy (const point &p)
tripoint sm_to_ms_copy (const tripoint &p)
void sm_to_ms (int &x, int &y)
point ms_to_omt_copy (const point &p)
tripoint ms_to_omt_copy (const tripoint &p)
void ms_to_omt (int &x, int &y)
point ms_to_omt_remain (int &x, int &y)
tripoint omt_to_seg_copy (const tripoint &p)
point sm_to_mmr_remain (int &x, int &y)
tripoint mmr_to_sm_copy (const tripoint &p)
Function Documentation
divide() [1/2]
static int divide (int v, int m) static
Definition at line 5 of file coordinate_conversions.cpp.
{
    if( v >= 0 ) {
        return v / m;
    }
    return ( v - m + 1 ) / m;
}
Referenced by divide(), ms_to_omt(), ms_to_omt_copy(), ms_to_omt_remain(), ms_to_sm(), ms_to_sm_copy(), ms_to_sm_remain(), omt_to_om(), omt_to_om_copy(), omt_to_om_remain(), omt_to_seg_copy(), sm_to_mmr_remain(), sm_to_om(), sm_to_om_copy(), sm_to_om_remain(), sm_to_omt(), sm_to_omt_copy(), and sm_to_omt_remain().
divide() [2/2]
static int divide (int v, int m, int & r) static
Definition at line 13 of file coordinate_conversions.cpp.
{
    const int result = divide( v, m );
    r = v - result * m;
    return result;
}
References divide().
mmr_to_sm_copy()
tripoint mmr_to_sm_copy (const tripoint & p)
Definition at line 193 of file coordinate_conversions.cpp.
{
    return tripoint( p.x * MM_REG_SIZE, p.y * MM_REG_SIZE, p.z );
}
References MM_REG_SIZE, tripoint::x, tripoint::y, and tripoint::z.
Referenced by map_memory::allocate_submap(), map_memory::load_submap(), and map_memory::save().
ms_to_omt()
void ms_to_omt (int & x, int & y)
Definition at line 172 of file coordinate_conversions.cpp.
{
    x = divide( x, SEEX * 2 );
    y = divide( y, SEEY * 2 );
}
References divide(), SEEX, and SEEY.
Referenced by ms_to_omt().
ms_to_omt_copy() [1/2]
point ms_to_omt_copy (const point & p)
Definition at line 162 of file coordinate_conversions.cpp.
{
    return point( divide( p.x, SEEX * 2 ), divide( p.y, SEEY * 2 ) );
}
References divide(), SEEX, SEEY, point::x, and point::y.
Referenced by map::add_item(), iexamine::bulletin_board(), iexamine::cardreader(), iexamine::elevator(), Character::global_omt_location(), good_fishing_spot(), photo_def_for_camera_point(), map::point_within_camp(), game::pre_print_all_tile_info(), remove_submap_turrets(), map::spread_gas(), sum_conditions(), map::translate_radius(), iexamine::translocator(), and game::zones_manager().
ms_to_omt_copy() [2/2]
tripoint ms_to_omt_copy (const tripoint & p)
Definition at line 167 of file coordinate_conversions.cpp.
{
    return tripoint( divide( p.x, SEEX * 2 ), divide( p.y, SEEY * 2 ), p.z );
}
References divide(), SEEX, SEEY, tripoint::x, tripoint::y, and tripoint::z.
ms_to_omt_remain()
point ms_to_omt_remain (int & x, int & y)
Definition at line 178 of file coordinate_conversions.cpp.
{
    return point( divide( x, SEEX * 2, x ), divide( y, SEEY * 2, y ) );
}
References divide(), SEEX, and SEEY.
Referenced by ms_to_omt_remain().
ms_to_sm()
void ms_to_sm (int & x, int & y)
Definition at line 135 of file coordinate_conversions.cpp.
{
    x = divide( x, SEEX );
    y = divide( y, SEEY );
}
References divide(), SEEX, and SEEY.
Referenced by ms_to_sm().
ms_to_sm_copy() [1/2]
point ms_to_sm_copy (const point & p)
Definition at line 125 of file coordinate_conversions.cpp.
{
    return point( divide( p.x, SEEX ), divide( p.y, SEEY ) );
}
References divide(), SEEX, SEEY, point::x, and point::y.
Referenced by map::bash_ter_furn(), overmapbuffer::despawn_monster(), monster::die(), construct::done_digormine_stair(), construct::done_mine_upstair(), Character::global_sm_location(), is_sm_tile_outside(), is_sm_tile_over_water(), sounds::process_sounds(), map::set_transparency_cache_dirty(), and map::shoot().
ms_to_sm_copy() [2/2]
tripoint ms_to_sm_copy (const tripoint & p)
Definition at line 130 of file coordinate_conversions.cpp.
{
    return tripoint( divide( p.x, SEEX ), divide( p.y, SEEY ), p.z );
}
References divide(), SEEX, SEEY, tripoint::x, tripoint::y, and tripoint::z.
ms_to_sm_remain()
point ms_to_sm_remain (int & x, int & y)
Definition at line 141 of file coordinate_conversions.cpp.
{
    return point( divide( x, SEEX, x ), divide( y, SEEY, y ) );
}
References divide(), SEEX, and SEEY.
Referenced by map::add_vehicle(), map_memory::coord_pair::coord_pair(), vehicle::find_vehicle(), ms_to_sm_remain(), and game::place_vehicle_nearby().
om_to_omt_copy()
point om_to_omt_copy (const point & p)
Definition at line 41 of file coordinate_conversions.cpp.
{
    return point( p.x * OMAPX, p.y * OMAPY );
}
References OMAPX, OMAPY, point::x, and point::y.
Referenced by real_coords::fromomap().
om_to_sm()
void om_to_sm (int & x, int & y)
Definition at line 119 of file coordinate_conversions.cpp.
{
    x *= 2 * OMAPX;
    y *= 2 * OMAPY;
}
References OMAPX, and OMAPY.
Referenced by om_to_sm().
om_to_sm_copy() [1/2]
point om_to_sm_copy (const point & p)
Definition at line 109 of file coordinate_conversions.cpp.
{
    return point( p.x * 2 * OMAPX, p.y * 2 * OMAPX );
}
References OMAPX, point::x, and point::y.
om_to_sm_copy() [2/2]
tripoint om_to_sm_copy (const tripoint & p)
Definition at line 114 of file coordinate_conversions.cpp.
{
    return tripoint( p.x * 2 * OMAPX, p.y * 2 * OMAPX, p.z );
}
References OMAPX, tripoint::x, tripoint::y, and tripoint::z.
omt_to_ms_copy()
point omt_to_ms_copy (const point & p)
Definition at line 88 of file coordinate_conversions.cpp.
{
    return point( p.x * 2 * SEEX, p.y * 2 * SEEY );
}
References SEEX, SEEY, point::x, and point::y.
Referenced by real_coords::fromomap(), and editmap::mapgen_retarget().
omt_to_om()
void omt_to_om (int & x, int & y)
Definition at line 30 of file coordinate_conversions.cpp.
{
    x = divide( x, OMAPX );
    y = divide( y, OMAPY );
}
References divide(), OMAPX, and OMAPY.
Referenced by omt_to_om().
omt_to_om_copy() [1/2]
point omt_to_om_copy (const point & p)
This file defines legacy coordinate conversion functions.
We should be migrating to the new functions defined in coordinates.h.
For documentation on coordinate systems in general see doc/POINTS_COORDINATES.md.
TODO: type for mmr coords, also add them to doc/POINTS_COORDINATES.md memory map region (mmr): Memory map region is a unit of tile memory saved to a directory. Each region contains MM_REG_SIZExMM_REG_SIZE memorized submaps, and is used only for saving/loading memorized submaps, see map_memory.cpp. Translation from sm to mmr: sm.x /= MM_REG_SIZE sm.y /= MM_REG_SIZE (with special handling for negative values).
This file provides static translation functions, named like this:
static point <from>_to_<to>_copy(int x, int y);
static point <from>_to_<to>_copy(const point& p);
static tripoint <from>_to_<to>_copy(const tripoint& p);
static void <from>_to_<to>(int &x, int &y);
static void <from>_to_<to>(point& p);
static void <from>_to_<to>(tripoint& p);
static point <from>_to_<to>_remain(int &x, int &y);
static point <from>_to_<to>_remain(point& p);
Functions ending with _copy return the translated coordinates, other functions change the parameters itself and don't return anything. Functions ending with _remain return the translated coordinates and store the remainder in the parameters.
Definition at line 20 of file coordinate_conversions.cpp.
{
    return point( divide( p.x, OMAPX ), divide( p.y, OMAPY ) );
}
References divide(), OMAPX, OMAPY, point::x, and point::y.
omt_to_om_copy() [2/2]
tripoint omt_to_om_copy (const tripoint & p)
Definition at line 25 of file coordinate_conversions.cpp.
{
    return tripoint( divide( p.x, OMAPX ), divide( p.y, OMAPY ), p.z );
}
References divide(), OMAPX, OMAPY, tripoint::x, tripoint::y, and tripoint::z.
omt_to_om_remain()
point omt_to_om_remain (int & x, int & y)
Definition at line 36 of file coordinate_conversions.cpp.
{
    return point( divide( x, OMAPX, x ), divide( y, OMAPY, y ) );
}
References divide(), OMAPX, and OMAPY.
Referenced by omt_to_om_remain().
omt_to_seg_copy()
tripoint omt_to_seg_copy (const tripoint & p)
Definition at line 183 of file coordinate_conversions.cpp.
{
    return tripoint( divide( p.x, SEG_SIZE ), divide( p.y, SEG_SIZE ), p.z );
}
References divide(), SEG_SIZE, tripoint::x, tripoint::y, and tripoint::z.
Referenced by find_dirname().
omt_to_sm()
void omt_to_sm (int & x, int & y)
Definition at line 103 of file coordinate_conversions.cpp.
{
    x *= 2;
    y *= 2;
}
Referenced by omt_to_sm().
omt_to_sm_copy() [1/2]
point omt_to_sm_copy (const point & p)
Definition at line 93 of file coordinate_conversions.cpp.
{
    return point( p.x * 2, p.y * 2 );
}
References point::x, and point::y.
Referenced by overmapbuffer::closest_city(), overmapbuffer::closest_known_city(), overmapbuffer::get_description_at(), city_reference::get_distance_from_bounds(), camp_reference::get_distance_from_bounds(), map::loadn(), game::perhaps_add_random_npc(), overmapbuffer::place_special(), and mapbuffer::save_quad().
omt_to_sm_copy() [2/2]
tripoint omt_to_sm_copy (const tripoint & p)
Definition at line 98 of file coordinate_conversions.cpp.
{
    return tripoint( p.x * 2, p.y * 2, p.z );
}
References tripoint::x, tripoint::y, and tripoint::z.
sm_to_mmr_remain()
point sm_to_mmr_remain (int & x, int & y)
Definition at line 188 of file coordinate_conversions.cpp.
{
    return point( divide( x, MM_REG_SIZE, x ), divide( y, MM_REG_SIZE, y ) );
}
References divide(), and MM_REG_SIZE.
Referenced by reg_coord_pair::reg_coord_pair().
sm_to_ms()
void sm_to_ms (int & x, int & y)
Definition at line 156 of file coordinate_conversions.cpp.
{
    x *= SEEX;
    y *= SEEY;
}
References SEEX, and SEEY.
Referenced by sm_to_ms(), and map::spawn_monsters_submap_group().
sm_to_ms_copy() [1/2]
point sm_to_ms_copy (const point & p)
Definition at line 146 of file coordinate_conversions.cpp.
{
    return point( p.x * SEEX, p.y * SEEY );
}
References SEEX, SEEY, point::x, and point::y.
Referenced by map::actualize(), map::build_transparency_cache(), map::getabs(), map::getlocal(), vehicle::global_pos3(), npc::global_square_location(), map::saven(), map::scent_blockers(), npc::shift(), monster::shift(), map::spawn_monsters_submap(), game::update_map(), game::vertical_move(), and game::walk_move().
sm_to_ms_copy() [2/2]
tripoint sm_to_ms_copy (const tripoint & p)
Definition at line 151 of file coordinate_conversions.cpp.
{
    return tripoint( p.x * SEEX, p.y * SEEY, p.z );
}
References SEEX, SEEY, tripoint::x, tripoint::y, and tripoint::z.
sm_to_om()
void sm_to_om (int & x, int & y)
Definition at line 77 of file coordinate_conversions.cpp.
{
    x = divide( x, 2 * OMAPX );
    y = divide( y, 2 * OMAPY );
}
References divide(), OMAPX, and OMAPY.
Referenced by sm_to_om().
sm_to_om_copy() [1/2]
point sm_to_om_copy (const point & p)
Definition at line 67 of file coordinate_conversions.cpp.
{
    return point( divide( p.x, 2 * OMAPX ), divide( p.y, 2 * OMAPY ) );
}
References divide(), OMAPX, OMAPY, point::x, and point::y.
Referenced by game::get_cur_om(), npc::setpos(), and npc::travel_overmap().
sm_to_om_copy() [2/2]
tripoint sm_to_om_copy (const tripoint & p)
Definition at line 72 of file coordinate_conversions.cpp.
{
    return tripoint( divide( p.x, 2 * OMAPX ), divide( p.y, 2 * OMAPY ), p.z );
}
References divide(), OMAPX, OMAPY, tripoint::x, tripoint::y, and tripoint::z.
sm_to_om_remain()
point sm_to_om_remain (int & x, int & y)
Definition at line 83 of file coordinate_conversions.cpp.
{
    return point( divide( x, 2 * OMAPX, x ), divide( y, 2 * OMAPY, y ) );
}
References divide(), OMAPX, and OMAPY.
Referenced by game::serialize(), and sm_to_om_remain().
sm_to_omt()
void sm_to_omt (int & x, int & y)
Definition at line 56 of file coordinate_conversions.cpp.
{
    x = divide( x, 2 );
    y = divide( y, 2 );
}
References divide().
Referenced by sm_to_omt().
sm_to_omt_copy() [1/2]
point sm_to_omt_copy (const point & p)
Definition at line 46 of file coordinate_conversions.cpp.
{
    return point( divide( p.x, 2 ), divide( p.y, 2 ) );
}
References divide(), point::x, and point::y.
Referenced by MapExtras::apply_function(), map::generate(), map::loadn(), MapExtras::mx_bandits_block(), MapExtras::mx_minefield(), MapExtras::mx_roadblock(), MapExtras::mx_roadworks(), map::place_items(), map::place_spawns(), mapbuffer::save(), mapbuffer::unserialize_submaps(), and map::update_visibility_cache().
sm_to_omt_copy() [2/2]
tripoint sm_to_omt_copy (const tripoint & p)
Definition at line 51 of file coordinate_conversions.cpp.
{
    return tripoint( divide( p.x, 2 ), divide( p.y, 2 ), p.z );
}
References divide(), tripoint::x, tripoint::y, and tripoint::z.
sm_to_omt_remain()
point sm_to_omt_remain (int & x, int & y)
Definition at line 62 of file coordinate_conversions.cpp.
{
    return point( divide( x, 2, x ), divide( y, 2, y ) );
}
References divide().
Referenced by sm_to_omt_remain().