Cataclysm BN: src/coordinates.h File Reference
coordinates.h File Reference
#include <algorithm>
#include <cstdlib>
#include <iterator>
#include "coordinate_conversions.h"
#include "cuboid_rectangle.h"
#include "enums.h"
#include "game_constants.h"
#include "point.h"
#include "debug.h"
Classes
class coords::coord_point< Point, Origin, Scale >
A generic coordinate-type-safe point.
struct coords::project_to_impl< ScaleUp, 0, ResultScale >
struct coords::project_to_impl< 0, ScaleDown, ResultScale >
struct coords::quotient_remainder_helper< Origin, CoarseScale, FineScale >
struct coords::quotient_remainder_point< Origin, CoarseScale, FineScale >
struct coords::quotient_remainder_tripoint< Origin, CoarseScale, FineScale >
struct std::hash< coords::coord_point< Point, Origin, Scale > >
struct real_coords
Namespaces
namespace coords
namespace std
STL namespace.
Macros
#define CATA_SRC_COORDINATES_H
Typedefs
using point_rel_ms = coords::coord_point< point, coords::origin::relative, coords::ms >
Typedefs for point types with coordinate mnemonics.
using point_abs_ms = coords::coord_point< point, coords::origin::abs, coords::ms >
using point_sm_ms = coords::coord_point< point, coords::origin::submap, coords::ms >
using point_omt_ms = coords::coord_point< point, coords::origin::overmap_terrain, coords::ms >
using point_abs_sm = coords::coord_point< point, coords::origin::abs, coords::sm >
using point_omt_sm = coords::coord_point< point, coords::origin::overmap_terrain, coords::sm >
using point_om_sm = coords::coord_point< point, coords::origin::overmap, coords::sm >
using point_rel_omt = coords::coord_point< point, coords::origin::relative, coords::omt >
using point_abs_omt = coords::coord_point< point, coords::origin::abs, coords::omt >
using point_om_omt = coords::coord_point< point, coords::origin::overmap, coords::omt >
using point_abs_seg = coords::coord_point< point, coords::origin::abs, coords::seg >
using point_rel_om = coords::coord_point< point, coords::origin::relative, coords::om >
using point_abs_om = coords::coord_point< point, coords::origin::abs, coords::om >
using tripoint_rel_ms = coords::coord_point< tripoint, coords::origin::relative, coords::ms >
using tripoint_abs_ms = coords::coord_point< tripoint, coords::origin::abs, coords::ms >
using tripoint_sm_ms = coords::coord_point< tripoint, coords::origin::submap, coords::ms >
using tripoint_omt_ms = coords::coord_point< tripoint, coords::origin::overmap_terrain, coords::ms >
using tripoint_rel_sm = coords::coord_point< tripoint, coords::origin::relative, coords::sm >
using tripoint_abs_sm = coords::coord_point< tripoint, coords::origin::abs, coords::sm >
using tripoint_om_sm = coords::coord_point< tripoint, coords::origin::overmap, coords::sm >
using tripoint_rel_omt = coords::coord_point< tripoint, coords::origin::relative, coords::omt >
using tripoint_abs_omt = coords::coord_point< tripoint, coords::origin::abs, coords::omt >
using tripoint_om_omt = coords::coord_point< tripoint, coords::origin::overmap, coords::omt >
using tripoint_abs_seg = coords::coord_point< tripoint, coords::origin::abs, coords::seg >
using tripoint_abs_om = coords::coord_point< tripoint, coords::origin::abs, coords::om >
Enumerations
enum class coords::scale {
coords::map_square , coords::submap , coords::overmap_terrain , coords::segment ,
coords::overmap , coords::vehicle
}
enum class coords::origin {
coords::relative , coords::abs , coords::submap , coords::overmap_terrain ,
coords::overmap
}
Functions
constexpr int coords::map_squares_per (scale s)
constexpr origin coords::origin_from_scale (scale s)
template<typename Point , origin Origin, scale Scale>
constexpr bool coords::operator== (const coord_point< Point, Origin, Scale > &l, const coord_point< Point, Origin, Scale > &r)
template<typename Point , origin Origin, scale Scale>
constexpr bool coords::operator!= (const coord_point< Point, Origin, Scale > &l, const coord_point< Point, Origin, Scale > &r)
template<typename Point , origin Origin, scale Scale>
constexpr bool coords::operator< (const coord_point< Point, Origin, Scale > &l, const coord_point< Point, Origin, Scale > &r)
template<typename PointL , typename PointR , origin OriginL, scale Scale>
constexpr auto coords::operator+ (const coord_point< PointL, OriginL, Scale > &l, const coord_point< PointR, origin::relative, Scale > &r)
template<typename PointL , typename PointR , origin OriginR, scale Scale, typename = std::enable_if_t < OriginR != origin::relative >>
constexpr auto coords::operator+ (const coord_point< PointL, origin::relative, Scale > &l, const coord_point< PointR, OriginR, Scale > &r)
template<typename PointL , typename PointR , origin OriginL, scale Scale>
constexpr auto coords::operator- (const coord_point< PointL, OriginL, Scale > &l, const coord_point< PointR, origin::relative, Scale > &r)
template<typename PointL , typename PointR , origin Origin, scale Scale, typename = std::enable_if_t < Origin != origin::relative >>
constexpr auto coords::operator- (const coord_point< PointL, Origin, Scale > &l, const coord_point< PointR, Origin, Scale > &r)
template<typename Point , scale Scale>
constexpr coord_point< Point, origin::relative, Scale > coords::operator* (int l, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , scale Scale>
constexpr coord_point< Point, origin::relative, Scale > coords::operator* (const coord_point< Point, origin::relative, Scale > &r, int l)
template<typename Point , origin Origin, scale Scale>
std::ostream & coords::operator<< (std::ostream &os, const coord_point< Point, Origin, Scale > &p)
template<scale ResultScale, typename Point , origin Origin, scale SourceScale>
coord_point< Point, Origin, ResultScale > coords::project_to (const coord_point< Point, Origin, SourceScale > &src)
template<scale ResultScale, origin Origin, scale SourceScale>
quotient_remainder_point< Origin, ResultScale, SourceScale > coords::project_remain (const coord_point< point, Origin, SourceScale > &src)
template<scale ResultScale, origin Origin, scale SourceScale>
quotient_remainder_tripoint< Origin, ResultScale, SourceScale > coords::project_remain (const coord_point< tripoint, Origin, SourceScale > &src)
template<typename PointL , typename PointR , origin CoarseOrigin, scale CoarseScale, origin FineOrigin, scale FineScale>
auto coords::project_combine (const coord_point< PointL, CoarseOrigin, CoarseScale > &coarse, const coord_point< PointR, FineOrigin, FineScale > &fine)
template<scale FineScale, origin Origin, scale CoarseScale>
auto coords::project_bounds (const coord_point< point, Origin, CoarseScale > &coarse)
template<scale FineScale, origin Origin, scale CoarseScale>
auto coords::project_bounds (const coord_point< tripoint, Origin, CoarseScale > &coarse)
template<typename Point , coords::origin Origin, coords::scale Scale>
int square_dist (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale>
int trig_dist (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale>
int rl_dist (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale>
int manhattan_dist (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale>
int octile_dist (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2, int multiplier=1)
template<typename Point , coords::origin Origin, coords::scale Scale>
direction direction_from (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale>
std::vector< coords::coord_point< Point, Origin, Scale > > line_to (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale>
coords::coord_point< Point, Origin, Scale > midpoint (const coords::coord_point< Point, Origin, Scale > &loc1, const coords::coord_point< Point, Origin, Scale > &loc2)
template<typename Point >
Point midpoint (const inclusive_rectangle< Point > &box)
template<typename Point >
Point midpoint (const half_open_rectangle< Point > &box)
template<typename Tripoint >
Tripoint midpoint (const inclusive_cuboid< Tripoint > &box)
template<typename Tripoint >
Tripoint midpoint (const half_open_cuboid< Tripoint > &box)
template<typename Point , coords::origin Origin, coords::scale Scale>
std::vector< coords::coord_point< Point, Origin, Scale > > closest_points_first (const coords::coord_point< Point, Origin, Scale > &loc, int min_dist, int max_dist)
template<typename Point , coords::origin Origin, coords::scale Scale>
std::vector< coords::coord_point< Point, Origin, Scale > > closest_points_first (const coords::coord_point< Point, Origin, Scale > &loc, int max_dist)
Variables
constexpr scale coords::ms = scale::map_square
constexpr scale coords::sm = scale::submap
constexpr scale coords::omt = scale::overmap_terrain
constexpr scale coords::seg = scale::segment
constexpr scale coords::om = scale::overmap
Macro Definition Documentation
CATA_SRC_COORDINATES_H
#define CATA_SRC_COORDINATES_H
Definition at line 3 of file coordinates.h.
Typedef Documentation
point_abs_ms
using point_abs_ms = coords::coord_point<point, coords::origin::abs, coords::ms>
Definition at line 472 of file coordinates.h.
point_abs_om
using point_abs_om = coords::coord_point<point, coords::origin::abs, coords::om>
Definition at line 483 of file coordinates.h.
point_abs_omt
using point_abs_omt = coords::coord_point<point, coords::origin::abs, coords::omt>
Definition at line 479 of file coordinates.h.
point_abs_seg
using point_abs_seg = coords::coord_point<point, coords::origin::abs, coords::seg>
Definition at line 481 of file coordinates.h.
point_abs_sm
using point_abs_sm = coords::coord_point<point, coords::origin::abs, coords::sm>
Definition at line 475 of file coordinates.h.
point_om_omt
using point_om_omt = coords::coord_point<point, coords::origin::overmap, coords::omt>
Definition at line 480 of file coordinates.h.
point_om_sm
using point_om_sm = coords::coord_point<point, coords::origin::overmap, coords::sm>
Definition at line 477 of file coordinates.h.
point_omt_ms
using point_omt_ms = coords::coord_point<point, coords::origin::overmap_terrain, coords::ms>
Definition at line 474 of file coordinates.h.
point_omt_sm
using point_omt_sm = coords::coord_point<point, coords::origin::overmap_terrain, coords::sm>
Definition at line 476 of file coordinates.h.
point_rel_ms
using point_rel_ms = coords::coord_point<point, coords::origin::relative, coords::ms>
Typedefs for point types with coordinate mnemonics.
Each name is of the form (tri)point_<origin>_<scale> where <origin> tells you the context in which the point has meaning, and <scale> tells you what one unit of the point means.
For example: point_omt_ms is the position of a map square within an overmap terrain. tripoint_rel_sm is a relative tripoint submap offset.
For more details see doc/POINTS_COORDINATES.md.
Definition at line 471 of file coordinates.h.
point_rel_om
using point_rel_om = coords::coord_point<point, coords::origin::relative, coords::om>
Definition at line 482 of file coordinates.h.
point_rel_omt
using point_rel_omt = coords::coord_point<point, coords::origin::relative, coords::omt>
Definition at line 478 of file coordinates.h.
point_sm_ms
using point_sm_ms = coords::coord_point<point, coords::origin::submap, coords::ms>
Definition at line 473 of file coordinates.h.
tripoint_abs_ms
using tripoint_abs_ms = coords::coord_point<tripoint, coords::origin::abs, coords::ms>
Definition at line 486 of file coordinates.h.
tripoint_abs_om
using tripoint_abs_om = coords::coord_point<tripoint, coords::origin::abs, coords::om>
Definition at line 496 of file coordinates.h.
tripoint_abs_omt
using tripoint_abs_omt = coords::coord_point<tripoint, coords::origin::abs, coords::omt>
Definition at line 493 of file coordinates.h.
tripoint_abs_seg
using tripoint_abs_seg = coords::coord_point<tripoint, coords::origin::abs, coords::seg>
Definition at line 495 of file coordinates.h.
tripoint_abs_sm
using tripoint_abs_sm = coords::coord_point<tripoint, coords::origin::abs, coords::sm>
Definition at line 490 of file coordinates.h.
tripoint_om_omt
using tripoint_om_omt = coords::coord_point<tripoint, coords::origin::overmap, coords::omt>
Definition at line 494 of file coordinates.h.
tripoint_om_sm
using tripoint_om_sm = coords::coord_point<tripoint, coords::origin::overmap, coords::sm>
Definition at line 491 of file coordinates.h.
tripoint_omt_ms
using tripoint_omt_ms = coords::coord_point<tripoint, coords::origin::overmap_terrain, coords::ms>
Definition at line 488 of file coordinates.h.
tripoint_rel_ms
using tripoint_rel_ms = coords::coord_point<tripoint, coords::origin::relative, coords::ms>
Definition at line 485 of file coordinates.h.
tripoint_rel_omt
using tripoint_rel_omt = coords::coord_point<tripoint, coords::origin::relative, coords::omt>
Definition at line 492 of file coordinates.h.
tripoint_rel_sm
using tripoint_rel_sm = coords::coord_point<tripoint, coords::origin::relative, coords::sm>
Definition at line 489 of file coordinates.h.
tripoint_sm_ms
using tripoint_sm_ms = coords::coord_point<tripoint, coords::origin::submap, coords::ms>
Definition at line 487 of file coordinates.h.
Function Documentation
closest_points_first() [1/2]
template<typename Point , coords::origin Origin, coords::scale Scale> std::vector< coords::coord_point< Point, Origin, Scale > > closest_points_first (const coords::coord_point< Point, Origin, Scale > & loc, int max_dist)
Definition at line 610 of file coordinates.h.
{
    return closest_points_first( loc, 0, max_dist );
}
References closest_points_first().
closest_points_first() [2/2]
template<typename Point , coords::origin Origin, coords::scale Scale> std::vector< coords::coord_point< Point, Origin, Scale > > closest_points_first (const coords::coord_point< Point, Origin, Scale > & loc, int min_dist, int max_dist)
Definition at line 596 of file coordinates.h.
{
    std::vector<Point> raw_result = closest_points_first( loc.raw(), min_dist, max_dist );
    std::vector<coords::coord_point<Point, Origin, Scale>> result;
    result.reserve( raw_result.size() );
    std::transform( raw_result.begin(), raw_result.end(), std::back_inserter( result ),
    []( const Point & p ) {
        return coords::coord_point<Point, Origin, Scale>( p );
    } );
    return result;
}
References closest_points_first(), coords::coord_point< Point, Origin, Scale >::raw(), and iexamine::transform().
Referenced by mdefense::acidsplash(), map::add_item_or_charges(), inventory_selector::add_nearby_items(), iuse::artifact(), npc::avoid_friendly_fire(), overmap::build_lab(), mattack::callblobs(), target_ui::choose_initial_target(), closest_points_first(), cycle_action(), iexamine::egg_sack_generic(), iexamine::elevator(), npc::execute_action(), overmapbuffer::find_all(), overmapbuffer::find_closest(), find_closest_stair(), npc::find_item(), game::find_nearby_items(), start_location::find_player_initial_location(), mattack::formblob(), map::get_dir_circle(), player::get_eligible_containers_for_crafting(), mattack::jackson(), vehicle::leak_fuel(), map_selector::map_selector(), mapgen_lake_shore(), nearest_passable(), minesweeper_game::new_level(), overmap::place_forest_trailheads(), npc::place_on_map(), overmap::place_specials(), overmap::place_swamps(), mattack::plant(), points_for_gas_cloud(), npc::see_item_say_smth(), set_item_map(), spawn_spores(), minesweeper_game::start_game(), try_fuel_fire(), vehicle_selector::vehicle_selector(), game::vertical_move(), and debug_menu::wishmonster().
direction_from()
template<typename Point , coords::origin Origin, coords::scale Scale> direction direction_from (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2)
Definition at line 540 of file coordinates.h.
{
    return direction_from( loc1.raw(), loc2.raw() );
}
References direction_from(), and coords::coord_point< Point, Origin, Scale >::raw().
Referenced by npc::assess_danger(), overmap_special::check(), vehicle::check_heli_ascend(), Character::deal_damage(), direction_from(), iuse::directional_antenna(), overmap_ui::draw_ascii(), basecamp::faction_display(), npc::faction_display(), overmap_special::finalize(), overmapbuffer::get_description_at(), liquid_handler::get_liquid_target(), vehicle::handle_trap(), game::list_items(), game::list_monsters(), game::mon_info_update(), iuse::note_bionics(), player_hit_message(), point_selection_menu(), ranged::print_dmg_msg(), sounds::process_sound_markers(), iuse::report_grid_connections(), pf::anonymous_namespace{simple_pathfinding.cpp}::reverse_direction(), overmap_ui::search(), character_funcs::search_surroundings(), overmap_ui::show_notes_manager(), npc::warn_about(), and game::zones_manager().
line_to()
template<typename Point , coords::origin Origin, coords::scale Scale> std::vector< coords::coord_point< Point, Origin, Scale > > line_to (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2)
Definition at line 548 of file coordinates.h.
{
    std::vector<Point> raw_result = line_to( loc1.raw(), loc2.raw() );
    std::vector<coords::coord_point<Point, Origin, Scale>> result;
    std::transform( raw_result.begin(), raw_result.end(), std::back_inserter( result ),
    []( const Point & p ) {
        return coords::coord_point<Point, Origin, Scale>( p );
    } );
    return result;
}
References line_to(), coords::coord_point< Point, Origin, Scale >::raw(), and iexamine::transform().
Referenced by map::add_splatter_trail(), jmapgen_setmap::apply(), Creature::auto_find_hostile_target(), iuse::camera(), activity_handlers::chop_tree_finish(), clear_shot_reach(), companion_travel_time_calc(), explosion_handler::do_blast_new(), vehicle::do_towing_move(), draw_line(), draw_trail(), map::find_clear_path(), mdeath::focused_beam(), map::get_dir_circle(), iuse::grenade_inc_act(), monster::group_bash_skill(), vehicle::immediate_path(), in_spell_aoe(), game::knockback(), line_to(), mapgen_lake_shore(), MapExtras::mx_casings(), MapExtras::mx_minefield(), MapExtras::mx_portal_in(), om_companion_path(), om_cutdown_trees(), om_line_mark(), Character::overmap_los(), MapExtras::place_fumarole(), projectile_attack(), spell_effect::projectile_attack(), Character::reach_attack(), editmap::recalc_target(), mattack::riotbot(), map::route(), scatter_chunks(), mattack::shockstorm(), Messages::dialog::show(), explosion_handler::shrapnel(), spell_effect::spell_effect_cone(), spell_effect::spell_effect_line(), basecamp::start_fortifications(), editmap::uber_draw_ter(), game::update_overmap_seen(), and target_ui::update_turrets_in_range().
manhattan_dist()
template<typename Point , coords::origin Origin, coords::scale Scale> int manhattan_dist (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2) inline
Definition at line 526 of file coordinates.h.
{
    return manhattan_dist( loc1.raw(), loc2.raw() );
}
References manhattan_dist(), and coords::coord_point< Point, Origin, Scale >::raw().
Referenced by overmap::build_lab(), overmap::lay_out_connection(), manhattan_dist(), and overmapbuffer::reveal_route().
midpoint() [1/5]
template<typename Point , coords::origin Origin, coords::scale Scale> coords::coord_point< Point, Origin, Scale > midpoint (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2)
Definition at line 562 of file coordinates.h.
{
    return coords::coord_point<Point, Origin, Scale>( ( loc1.raw() + loc2.raw() ) / 2 );
}
References coords::coord_point< Point, Origin, Scale >::raw().
Referenced by mapgen_lake_shore(), midpoint(), overmap::signal_hordes(), activity_handlers::travel_do_turn(), and map::valid_move().
midpoint() [2/5]
template<typename Tripoint > Tripoint midpoint (const half_open_cuboid< Tripoint > & box)
Definition at line 589 of file coordinates.h.
{
    return midpoint( box.p_min, box.p_max );
}
References midpoint(), half_open_cuboid< Tripoint, >::p_max, and half_open_cuboid< Tripoint, >::p_min.
midpoint() [3/5]
template<typename Point > Point midpoint (const half_open_rectangle< Point > & box)
Definition at line 576 of file coordinates.h.
{
    return midpoint( box.p_min, box.p_max );
}
References midpoint(), half_open_rectangle< Point, >::p_max, and half_open_rectangle< Point, >::p_min.
midpoint() [4/5]
template<typename Tripoint > Tripoint midpoint (const inclusive_cuboid< Tripoint > & box)
Definition at line 582 of file coordinates.h.
{
    constexpr tripoint one( 1, 1, 1 );
    return midpoint( box.p_min, box.p_max + one );
}
References midpoint(), inclusive_cuboid< Tripoint, >::p_max, and inclusive_cuboid< Tripoint, >::p_min.
midpoint() [5/5]
template<typename Point > Point midpoint (const inclusive_rectangle< Point > & box)
Definition at line 569 of file coordinates.h.
{
    constexpr point one( 1, 1 ); // NOLINT(cata-use-named-point-constants)
    return midpoint( box.p_min, box.p_max + one );
}
References midpoint(), inclusive_rectangle< Point, >::p_max, and inclusive_rectangle< Point, >::p_min.
octile_dist()
template<typename Point , coords::origin Origin, coords::scale Scale> int octile_dist (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2, int multiplier = 1) inline
Definition at line 533 of file coordinates.h.
{
    return octile_dist( loc1.raw(), loc2.raw(), multiplier );
}
References octile_dist(), and coords::coord_point< Point, Origin, Scale >::raw().
Referenced by pf::find_overmap_path(), and octile_dist().
rl_dist()
template<typename Point , coords::origin Origin, coords::scale Scale> int rl_dist (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2) inline
Definition at line 519 of file coordinates.h.
{
    return rl_dist( loc1.raw(), loc2.raw() );
}
References coords::coord_point< Point, Origin, Scale >::raw(), and rl_dist().
Referenced by mattack::acid_accurate(), computer_session::action_irradiator(), Character::activate_bionic(), timed_event::actualize(), inventory_selector::add_nearby_items(), npc::address_player(), npc::alt_attack(), map::apparent_light_at(), map::apply_light_ray(), Character::apply_persistent_morale(), npc::assess_danger(), Creature::auto_find_hostile_target(), vehicle::autopilot_patrol(), map::bash_ter_furn(), mdeath::boomer(), mattack::boomer(), mattack::boomer_glow(), map::build_seen_cache(), calculate_aim_cap(), leap_actor::call(), mon_spellcasting_actor::call(), gun_actor::call(), iuse::camera(), Character::can_hear(), npc::can_move_to(), talk_function::caravan_dist(), cast_zlight_segment(), castLight(), game::chat(), Character::check_mount_is_spooked(), Character::check_mount_will_move(), mattack::chickenbot(), map::clear_path(), talk_function::companion_choose(), npc::consume_food_from_camp(), mattack::copbot(), map::create_anomaly(), create_radio_tower_reference(), mattack::darkman(), Character::deal_damage(), trap::detect_trap(), npc::do_pulp(), vehicle::do_towing_move(), game::do_turn(), move_items_activity_actor::do_turn(), mattack::doot(), overmap_ui::draw_om_sidebar(), draw_throw_aim(), vehicle::drive_to_local_target(), Character::drop(), dialogue::dynamic_line(), mattack::eat_food(), npc::enough_time_to_reload(), enumerate_objects_around_point(), npc::faction_display(), find_auto_consume(), map::find_clear_path(), npc::find_dangerous_explosives(), npc::find_item(), activity_handlers::find_mount_do_turn(), game::find_or_make_stairs(), find_target_vehicle(), mattack::flame(), explosion_handler::explosion_funcs::flashbang(), mattack::flesh_golem(), mattack::flesh_tendril(), monster::footsteps(), mattack::fungus(), mattack::fungus_fortify(), mattack::fungus_inject(), map::get_active_items_in_radius(), character_funcs::get_crafting_helpers(), get_sorted_tiles_by_distance(), get_stagger_adjust(), Character::get_visible_creatures(), iexamine::getNearFilledGasTank(), talk_function::give_all_aid(), mattack::grab_drag(), monster::group_bash_skill(), mattack::grow_vine(), mdeath::guilt(), game::handle_action(), item::handle_pickup_ownership(), npc::handle_sound(), npc::heal_player(), mattack::howl(), spell::in_aoe(), turret_data::in_range(), in_spell_aoe(), iexamine::intercom(), is_adjacent(), mission::is_complete(), monster::is_fleeing(), spell::is_target_in_range(), Character::is_visible_in_range(), mdeath::kill_vines(), Character::knock_back_to(), game::list_items(), game::list_monsters(), avatar_funcs::list_potential_theft_witnesses(), mattack::longswipe(), mattack::lunge(), mapgen_lake_shore(), npc::method_of_attack(), target_handler::mode_turrets(), game::mon_info_update(), mattack::mon_leech_evolution(), game::monmove(), monster::move(), npc::move(), avatar_action::move(), npc::move_away_from(), move_cost_cart(), move_cost_inv(), npc::move_to(), npc::mug_player(), mattack::multi_robot(), inventory_selector::naturalize_category(), vehicle::no_towing_slack(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), item_location::impl::item_on_map::obtain_cost(), item_location::impl::item_on_vehicle::obtain_cost(), om_companion_path(), om_target_tile(), vehicle::open_or_close(), game::overmap_npc_move(), photo_def_for_camera_point(), npc::pick_up_item(), pickveh(), monster::plan(), print_aim(), npc::print_info(), item::process_cable(), map::process_fields_in_submap(), projectile_attack(), map::propagate_field(), monster::push_to(), avatar_action::ramp_move(), mattack::ranged_pull(), mattack::ratking(), mattack::rattle(), npc::reach_omt_destination(), item::ready_to_revive(), editmap::recalc_target(), teleporter_callback::refresh(), vehicle::remote_controlled(), mdefense::return_fire(), mattack::riotbot(), rl_dist(), iuse::robotcontrol_can_target(), map::route(), area_expander::run(), mattack::science(), mattack::searchlight(), Creature::sees(), map::sees(), Character::sees(), conditional_t< T >::set_npc_role_nearby(), explosion_handler::explosion_funcs::shockwave(), show_armor_layers_ui(), overmap_ui::show_notes_manager(), explosion_handler::shrapnel(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), overmap::signal_hordes(), mattack::slimespring(), sound_distance(), map::spawn_monsters_submap_group(), spawn_spores(), mattack::spit_sap(), basecamp::start_clearcut(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), sting_get_target(), mattack::stretch_attack(), mattack::stretch_bite(), basecamp::survey_return(), mattack::tankgun(), mattack::tentacle(), ranged::throw_item(), ranged::throwing_dispersion(), mattack::tindalos_teleport(), too_close(), vehicle::tow_cable_too_far(), mattack::triffid_heartbeat(), npc::update_path(), game::update_stair_monsters(), editmap::update_view_with_help(), map::use_amount(), game::vertical_move(), mattack::vine(), mongroup::wander(), monster::will_reach(), within_target_range(), within_visual_range(), npc::wont_hit_friend(), and game::zones_manager().
square_dist()
template<typename Point , coords::origin Origin, coords::scale Scale> int square_dist (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2) inline
Definition at line 505 of file coordinates.h.
{
    return square_dist( loc1.raw(), loc2.raw() );
}
References coords::coord_point< Point, Origin, Scale >::raw(), and square_dist().
Referenced by activity_on_turn_move_loot(), overmap::add_mon_group(), map::apply_light_ray(), map::build_seen_cache(), overmap::build_slimepit(), leap_actor::call(), deploy_tent_actor::check_intact(), vehicle::damage_all(), Character::defer_move(), direction_suffix(), explosion_handler::do_blast_new(), npc::faction_display(), overmapbuffer::find_closest(), npc::find_corpse_to_pulp(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_heat_radiation(), zone_manager::get_near(), zone_manager::get_nearest(), overmapbuffer::get_npcs_near(), overmapbuffer::get_npcs_near_omt(), zone_manager::has_near(), line_to(), aim_activity_actor::load_RAS_weapon(), game::look_around(), map_item_stack::map_item_stack_sort(), Character::on_dodge(), npc_dist_to_player::operator()(), map::pl_line_of_sight(), map::pl_sees(), overmap::place_lakes(), overmap::place_specials(), rl_dist_exact(), target_ui::set_cursor_pos(), explosion_handler::shrapnel(), spell_effect::spell_effect_line(), square_dist(), mission_util::target_closest_lab_entrance(), game::try_get_right_click_action(), iuse_transform::use(), and set_transform_iuse::use().
trig_dist()
template<typename Point , coords::origin Origin, coords::scale Scale> int trig_dist (const coords::coord_point< Point, Origin, Scale > & loc1, const coords::coord_point< Point, Origin, Scale > & loc2) inline
Definition at line 512 of file coordinates.h.
{
    return trig_dist( loc1.raw(), loc2.raw() );
}
References coords::coord_point< Point, Origin, Scale >::raw(), and trig_dist().
Referenced by overmap::add_mon_group(), map::add_splash(), leap_actor::call(), overmap::connect_closest_points(), explosion_handler::do_blast_new(), draw_circle(), draw_rough_circle(), ranged::fire_gun(), city::get_distance_from(), get_stagger_adjust(), overmap::lay_out_connection(), mapgen_ants_generic(), mapgen_sewer_four_way(), npc::method_of_attack(), monster::move(), MapExtras::mx_portal_in(), overmap::place_building(), explosion_handler::explosion_funcs::resonance_cascade(), rl_dist_exact(), area_expander::run(), overmap_ui::search(), explosion_handler::shrapnel(), slope_of(), vehicle::smash(), map::translate_radius(), trig_dist(), and game::zones_manager().