Cataclysm BN: src/crafting.h File Reference
crafting.h File Reference
#include <list>
#include <set>
#include <vector>
#include "point.h"
#include "ret_val.h"
#include "type_id.h"
Classes
struct bench_location
Namespaces
namespace crafting
Macros
#define CATA_SRC_CRAFTING_H
Enumerations
enum class bench_type : int { ground = 0 , hands , furniture , vehicle }
Functions
void remove_ammo (item &dis_item, Character &who)
Removes any (removable) ammo and stores it in character's inventory.
void remove_ammo (std::list< item > &dis_items, Character &who)
Removes any (removable) ammo from each item and stores it in character's inventory.
bench_location find_best_bench (const player &p, const item &craft)
float workbench_crafting_speed_multiplier (const item &craft, const bench_location &bench)
float morale_crafting_speed_multiplier (const Character &who, const recipe &rec)
float lighting_crafting_speed_multiplier (const Character &who, const recipe &rec)
float crafting_speed_multiplier (const Character &who, const recipe &rec, bool in_progress)
float crafting_speed_multiplier (const Character &who, const item &craft, const bench_location &bench)
void complete_craft (player &p, item &craft, const bench_location &bench)
std::set< itype_id > crafting::get_books_for_recipe (const Character &c, const inventory &crafting_inv, const recipe *r)
Returns the set of book types in crafting_inv that provide the given recipe.
std::set< itype_id > crafting::get_books_for_recipe (const recipe *r)
Returns the set of book types that provide the given recipe.
int crafting::charges_for_complete (int full_charges)
int crafting::charges_for_starting (int full_charges)
int crafting::charges_for_continuing (int full_charges)
comp_selection< tool_comp > crafting::select_tool_component (const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, const Character *player_with_inv, bool can_cancel, const std::string &hotkeys, cost_adjustment adjustment)
Returns selected tool component that matches one of the expected ones.
comp_selection< tool_comp > crafting::select_tool_component (const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, const Character *player_with_inv, bool can_cancel)
ret_val< bool > crafting::can_disassemble (const Character &who, const item &obj, const inventory &inv)
Check if character can disassemble an item using the given crafting inventory.
bool crafting::disassemble (avatar &you)
Prompt for an item to disassemble, then start activity.
bool crafting::disassemble (avatar &you, item_location target)
Prompt to disassemble given item, then start activity.
bool crafting::disassemble_all (avatar &you, bool recursively)
Start an activity to disassemble all items in avatar's square.
void crafting::complete_disassemble (Character &who, iuse_location target, const tripoint &pos)
Complete disassembly of target item.
Macro Definition Documentation
CATA_SRC_CRAFTING_H
#define CATA_SRC_CRAFTING_H
Definition at line 3 of file crafting.h.
Enumeration Type Documentation
bench_type
enum class bench_type : int strong
Enumerator
ground
hands
furniture
vehicle
Definition at line 25 of file crafting.h.
                      : int {
    ground = 0,
    hands,
    furniture,
    vehicle
};
Function Documentation
complete_craft()
void complete_craft (player & p, item & craft, const bench_location & bench)
Intelligence increases chance to learn recipe when crafting from a book
Definition at line 1017 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "complete_craft() called on non-craft '%s.'  Aborting.", craft.tname() );
        return;
    }
    const recipe &making = craft.get_making();
    const int batch_size = craft.charges;
    std::list<item> &used = craft.components;
    const double relative_rot = craft.get_relative_rot();
    // Set up the new item, and assign an inventory letter if available
    std::vector<item> newits = making.create_results( batch_size );
    const bool should_heat = making.hot_result();
    bool first = true;
    size_t newit_counter = 0;
    for( item &newit : newits ) {
        // Points to newit unless newit is a non-empty container, then it points to newit's contents.
        // Necessary for things like canning soup; sometimes we want to operate on the soup, not the can.
        item &food_contained = ( newit.is_container() && !newit.contents.empty() ) ?
                               newit.contents.back() : newit;
        // messages, learning of recipe, food spoilage calculation only once
        if( first ) {
            first = false;
            // TODO: reconsider recipe memorization
            if( p.knows_recipe( &making ) ) {
                add_msg( _( "You craft %s from memory." ), making.result_name() );
            } else {
                add_msg( _( "You craft %s using a book as a reference." ), making.result_name() );
                // If we made it, but we don't know it,
                // we're making it from a book and have a chance to learn it.
                // Base expected time to learn is 1000*(difficulty^4)/skill/int moves.
                // This means time to learn is greatly decreased with higher skill level,
                // but also keeps going up as difficulty goes up.
                // Worst case is lvl 10, which will typically take
                // 10^4/10 (1,000) minutes, or about 16 hours of crafting it to learn.
                int difficulty = p.has_recipe( &making, p.crafting_inventory(),
                                               character_funcs::get_crafting_helpers( p ) );
                ///\EFFECT_INT increases chance to learn recipe when crafting from a book
                const double learning_speed =
                    std::max( p.get_skill_level( making.skill_used ), 1 ) *
                    std::max( p.get_int(), 1 );
                const double time_to_learn = 1000 * 8 * std::pow( difficulty, 4 ) / learning_speed;
                if( x_in_y( making.time, time_to_learn ) ) {
                    p.learn_recipe( &making );
                    add_msg( m_good, _( "You memorized the recipe for %s!" ),
                             making.result_name() );
                }
            }
        }
        food_contained.inherit_flags( used, making );
        for( const std::string &flag : making.flags_to_delete ) {
            food_contained.unset_flag( flag );
        }
        // Don't store components for things made by charges,
        // Don't store components for things that can't be uncrafted.
        if( recipe_dictionary::get_uncraft( making.result() ) && !food_contained.count_by_charges() &&
            making.is_reversible() ) {
            // Setting this for items counted by charges gives only problems:
            // those items are automatically merged everywhere (map/vehicle/inventory),
            // which would either lose this information or merge it somehow.
            set_components( food_contained.components, used, batch_size, newit_counter );
            newit_counter++;
        } else if( food_contained.is_food() && !food_contained.has_flag( flag_NUTRIENT_OVERRIDE ) ) {
            // if a component item has "cooks_like" it will be replaced by that item as a component
            for( item &comp : used ) {
                // only comestibles have cooks_like.  any other type of item will throw an exception, so filter those out
                if( comp.is_comestible() && !comp.get_comestible()->cooks_like.is_empty() ) {
                    comp = item( comp.get_comestible()->cooks_like, comp.birthday(), comp.charges );
                }
                // If this recipe is cooked, components are no longer raw.
                if( should_heat ) {
                    comp.set_flag_recursive( flag_COOKED );
                }
            }
            // use a copy of the used list so that the byproducts don't build up over iterations (#38071)
            std::list<item> usedbp = used;
            // byproducts get stored as a "component" but with a byproduct flag for consumption purposes
            if( making.has_byproducts() ) {
                for( item &byproduct : making.create_byproducts( batch_size ) ) {
                    byproduct.set_flag( flag_BYPRODUCT );
                    usedbp.push_back( byproduct );
                }
            }
            // store components for food recipes that do not have the override flag
            set_components( food_contained.components, usedbp, batch_size, newit_counter );
            // store the number of charges the recipe would create with batch size 1.
            if( &newit != &food_contained ) {  // If a canned/contained item was crafted…
                // … the container holds exactly one completion of the recipe, no matter the batch size.
                food_contained.recipe_charges = food_contained.charges;
            } else { // Otherwise, the item is already stacked so we need to divide by batch size.
                newit.recipe_charges = newit.charges / batch_size;
            }
            newit_counter++;
        }
        if( food_contained.goes_bad() ) {
            food_contained.set_relative_rot( relative_rot );
        }
        newit.set_owner( p.get_faction()->id );
        // If these aren't equal, newit is a container, so finalize its contents too.
        if( &newit != &food_contained ) {
            food_contained.set_owner( p.get_faction()->id );
        }
        if( newit.made_of( LIQUID ) ) {
            liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
        } else {
            set_item_inventory( p, newit );
        }
    }
    if( making.has_byproducts() ) {
        std::vector<item> bps = making.create_byproducts( batch_size );
        for( auto &bp : bps ) {
            if( bp.goes_bad() ) {
                bp.set_relative_rot( relative_rot );
            }
            bp.set_owner( p.get_faction()->id );
            if( bp.made_of( LIQUID ) ) {
                liquid_handler::handle_all_liquid( bp, PICKUP_RANGE );
            } else {
                set_item_inventory( p, bp );
            }
        }
    }
    p.inv.restack( p );
}
References _, add_msg(), item_contents::back(), item::charges, item::components, item::contents, item::count_by_charges(), iuse::craft(), Character::crafting_inventory(), recipe::create_byproducts(), recipe::create_results(), debugmsg, flag_BYPRODUCT(), flag_COOKED(), flag_NUTRIENT_OVERRIDE(), recipe::flags_to_delete, character_funcs::get_crafting_helpers(), Character::get_faction(), Character::get_int(), Character::get_skill_level(), recipe_dictionary::get_uncraft(), item::goes_bad(), liquid_handler::handle_all_liquid(), recipe::has_byproducts(), item::has_flag(), player::has_recipe(), recipe::hot_result(), faction_template::id, item::inherit_flags(), Character::inv, item::is_food(), recipe::is_reversible(), Character::knows_recipe(), Character::learn_recipe(), LIQUID, m_good, PICKUP_RANGE, item::recipe_charges, inventory::restack(), recipe::result(), recipe::result_name(), set_components(), set_item_inventory(), item::set_owner(), item::set_relative_rot(), recipe::skill_used, recipe::time, item::unset_flag(), and x_in_y().
Referenced by activity_handlers::craft_do_turn().
crafting_speed_multiplier() [1/2]
float crafting_speed_multiplier (const Character & who, const item & craft, const bench_location & bench)
Definition at line 283 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "Can't calculate crafting speed multiplier of non-craft '%s'", craft.tname() );
        return 1.0f;
    }
    const recipe &rec = craft.get_making();
    const float light_multi = lighting_crafting_speed_multiplier( who, rec );
    const float bench_multi = workbench_crafting_speed_multiplier( craft, bench );
    const float morale_multi = morale_crafting_speed_multiplier( who, rec );
    const float total_multi = light_multi * bench_multi * morale_multi;
    if( light_multi <= 0.0f ) {
        who.add_msg_if_player( m_bad, _( "You can no longer see well enough to keep crafting." ) );
        return 0.0f;
    }
    if( bench_multi <= 0.1f || ( bench_multi <= 0.33f && total_multi <= 0.2f ) ) {
        who.add_msg_if_player( m_bad, _( "The %s is too large and/or heavy to work on.  You may want to"
                                         " use a workbench or a smaller batch size" ), craft.tname() );
        return 0.0f;
    }
    if( morale_multi <= 0.2f || ( morale_multi <= 0.33f && total_multi <= 0.2f ) ) {
        who.add_msg_if_player( m_bad, _( "Your morale is too low to continue crafting." ) );
        return 0.0f;
    }
    // If we're working below 20% speed, just give up
    if( total_multi <= 0.2f ) {
        who.add_msg_if_player( m_bad, _( "You are too frustrated to continue and just give up." ) );
        return 0.0f;
    }
    if( calendar::once_every( 1_hours ) && total_multi < 0.75f ) {
        if( light_multi <= 0.5f ) {
            who.add_msg_if_player( m_bad, _( "You can't see well and are working slowly." ) );
        }
        if( bench_multi <= 0.5f ) {
            who.add_msg_if_player( m_bad,
                                   _( "The %s is to large and/or heavy to work on comfortably.  You are"
                                      " working slowly." ), craft.tname() );
        }
        if( morale_multi <= 0.5f ) {
            who.add_msg_if_player( m_bad, _( "You can't focus and are working slowly." ) );
        }
    }
    return total_multi;
}
References _, Creature::add_msg_if_player(), iuse::craft(), debugmsg, lighting_crafting_speed_multiplier(), m_bad, morale_crafting_speed_multiplier(), calendar::once_every(), and workbench_crafting_speed_multiplier().
crafting_speed_multiplier() [2/2]
float crafting_speed_multiplier (const Character & who, const recipe & rec, bool in_progress)
Definition at line 267 of file crafting.cpp.
{
    const float result = morale_crafting_speed_multiplier( who, rec ) *
                         lighting_crafting_speed_multiplier( who, rec );
    // Can't start if we'd need 300% time, but we can still finish the job
    if( !in_progress && result < 0.33f ) {
        return 0.0f;
    }
    // If we're working below 10% speed, just give up
    if( result < 0.1f ) {
        return 0.0f;
    }
    return result;
}
References lighting_crafting_speed_multiplier(), and morale_crafting_speed_multiplier().
Referenced by activity_handlers::craft_do_turn(), draw_can_craft_indicator(), and player::expected_time_to_craft().
find_best_bench()
bench_location find_best_bench (const player & p, const item & craft)
Definition at line 2327 of file crafting.cpp.
{
    bool can_lift = p.can_wield( craft ).success() && p.weight_capacity() >= craft.weight();
    std::pair<bench_type, float> bench_here = best_bench_here( craft, p.pos(), can_lift );
    bench_type best_type = bench_here.first;
    float best_bench_multi = bench_here.second;
    tripoint best_loc = p.pos();
    std::vector<tripoint> reachable( PICKUP_RANGE * PICKUP_RANGE );
    g->m.reachable_flood_steps( reachable, p.pos(), PICKUP_RANGE, 1, 100 );
    for( const tripoint &adj : reachable ) {
        if( const cata::value_ptr<furn_workbench_info> &wb = g->m.furn( adj ).obj().workbench ) {
            if( wb->multiplier > best_bench_multi ) {
                best_type = bench_type::furniture;
                best_bench_multi = wb->multiplier;
                best_loc = adj;
            }
        }
        if( const cata::optional<vpart_reference> vp = g->m.veh_at(
                    adj ).part_with_feature( "WORKBENCH", true ) ) {
            if( const cata::optional<vpslot_workbench> &wb_info = vp->part().info().get_workbench_info() ) {
                if( wb_info->multiplier > best_bench_multi ) {
                    best_type = bench_type::vehicle;
                    best_bench_multi = wb_info->multiplier;
                    best_loc = adj;
                }
            } else {
                debugmsg( "part '%S' with WORKBENCH flag has no workbench info", vp->part().name() );
            }
        }
    }
    return bench_location{best_type, best_loc};
}
References best_bench_here(), Character::can_wield(), iuse::craft(), debugmsg, furniture, g, PICKUP_RANGE, Character::pos(), vehicle, and Character::weight_capacity().
Referenced by iuse::craft(), and player::start_craft().
lighting_crafting_speed_multiplier()
float lighting_crafting_speed_multiplier (const Character & who, const recipe & rec)
Definition at line 132 of file crafting.cpp.
{
    if( character_funcs::can_see_fine_details( who ) ) {
        return 1.0f;
    }
    const SkillLevelMap &char_skills = who.get_all_skills();
    int skill_bonus = char_skills.exceeds_recipe_requirements( rec );
    // This value whould be within [0,1]
    const float darkness =
        (
            character_funcs::fine_detail_vision_mod( who ) -
            character_funcs::FINE_VISION_THRESHOLD
        ) / 7.0f;
    if( rec.has_flag( flag_BLIND_EASY ) ) {
        // 100% speed in well lit area at skill+0
        // 25% speed in pitch black at skill+0
        // skill+2 removes speed penalty
        return 1.0f - darkness * 0.75f * std::max( 0, 2 - skill_bonus ) / 2.0f;
    } else if( rec.has_flag( flag_BLIND_HARD ) && skill_bonus >= 2 ) {
        // 100% speed in well lit area at skill+2
        // 25% speed in pitch black at skill+2
        // skill+8 removes speed penalty
        return 1.0f - darkness * 0.75f * std::max( 0, 8 - skill_bonus ) / 6.0f;
    } else {
        // Needs proper vision or the character is not skilled enough
        return 0.0f;
    }
}
References character_funcs::can_see_fine_details(), SkillLevelMap::exceeds_recipe_requirements(), character_funcs::fine_detail_vision_mod(), character_funcs::FINE_VISION_THRESHOLD, flag_BLIND_EASY(), flag_BLIND_HARD(), Character::get_all_skills(), and recipe::has_flag().
Referenced by crafting::can_disassemble(), craft_progress_message(), crafting_allowed(), crafting_speed_multiplier(), and draw_can_craft_indicator().
morale_crafting_speed_multiplier()
float morale_crafting_speed_multiplier (const Character & who, const recipe & rec)
Definition at line 164 of file crafting.cpp.
{
    int morale = who.get_morale_level();
    if( morale >= 0 ) {
        // No bonus for being happy yet
        return 1.0f;
    }
    // Harder jobs are more frustrating, even when skilled
    // For each skill where skill=difficulty, multiply effective morale by 200%
    float morale_mult = std::max( 1.0f, 2.0f * rec.difficulty / std::max( 1,
                                  who.get_skill_level( rec.skill_used ) ) );
    for( const std::pair<const skill_id, int> &pr : rec.required_skills ) {
        morale_mult *= std::max( 1.0f, 2.0f * pr.second / std::max( 1, who.get_skill_level( pr.first ) ) );
    }
    // Halve speed at -50 effective morale, quarter at -150
    float morale_effect = 1.0f + ( morale_mult * morale ) / -50.0f;
    return 1.0f / morale_effect;
}
References recipe::difficulty, Character::get_morale_level(), Character::get_skill_level(), spell_effect::morale(), recipe::required_skills, and recipe::skill_used.
Referenced by craft_progress_message(), crafting_allowed(), and crafting_speed_multiplier().
remove_ammo() [1/2]
void remove_ammo (item & dis_item, Character & who)
Removes any (removable) ammo and stores it in character's inventory.
Definition at line 2265 of file crafting.cpp.
{
    dis_item.remove_items_with( [&who]( const item & it ) {
        if( it.is_irremovable() ) {
            return false;
        }
        drop_or_handle( it, who );
        return true;
    } );
    if( dis_item.has_flag( flag_NO_UNLOAD ) ) {
        return;
    }
    if( dis_item.is_gun() && !dis_item.ammo_current().is_null() ) {
        item ammodrop( dis_item.ammo_current(), calendar::turn );
        ammodrop.charges = dis_item.charges;
        drop_or_handle( ammodrop, who );
        dis_item.charges = 0;
    }
    if( dis_item.is_tool() && dis_item.charges > 0 && !dis_item.ammo_current().is_null() ) {
        item ammodrop( dis_item.ammo_current(), calendar::turn );
        ammodrop.charges = dis_item.charges;
        if( dis_item.ammo_current() == itype_plut_cell ) {
            ammodrop.charges /= PLUTONIUM_CHARGES;
        }
        drop_or_handle( ammodrop, who );
        dis_item.charges = 0;
    }
}
References item::ammo_current(), item::charges, drop_or_handle(), flag_NO_UNLOAD(), item::has_flag(), item::is_gun(), item::is_irremovable(), string_id< T >::is_null(), item::is_tool(), itype_plut_cell, PLUTONIUM_CHARGES, visitable< T >::remove_items_with(), and calendar::turn.
remove_ammo() [2/2]
void remove_ammo (std::list< item > & dis_items, Character & who)
Removes any (removable) ammo from each item and stores it in character's inventory.
Definition at line 2258 of file crafting.cpp.
{
    for( auto &dis_item : dis_items ) {
        remove_ammo( dis_item, who );
    }
}
References remove_ammo().
Referenced by crafting::complete_disassemble(), player::consume_items(), salvage_actor::cut_up(), and remove_ammo().
workbench_crafting_speed_multiplier()
float workbench_crafting_speed_multiplier (const item & craft, const bench_location & bench)
Definition at line 202 of file crafting.cpp.
{
    float multiplier = 0.0f;
    units::mass allowed_mass;
    units::volume allowed_volume;
    const units::mass &craft_mass = craft.weight();
    const units::volume &craft_volume = craft.volume();
    // The whole block below is so ugly because all the benches have different structs with same content
    map &here = get_map();
    switch( bench.type ) {
        case bench_type::hands: {
            const furn_t &f = string_id<furn_t>( "f_fake_bench_hands" ).obj();
            multiplier = f.workbench->multiplier;
            allowed_mass = f.workbench->allowed_mass;
            allowed_volume = f.workbench->allowed_volume;
        }
        break;
        case bench_type::ground: {
            // Ground - we can always use this, but it's bad
            const furn_t &f = string_id<furn_t>( "f_ground_crafting_spot" ).obj();
            multiplier = f.workbench->multiplier;
            allowed_mass = f.workbench->allowed_mass;
            allowed_volume = f.workbench->allowed_volume;
        }
        break;
        case bench_type::furniture:
            if( here.furn( bench.position ).obj().workbench ) {
                // Furniture workbench
                const furn_t &f = here.furn( bench.position ).obj();
                multiplier = f.workbench->multiplier;
                allowed_mass = f.workbench->allowed_mass;
                allowed_volume = f.workbench->allowed_volume;
            } else {
                return 0.0f;
            }
            break;
        case bench_type::vehicle:
            if( const cata::optional<vpart_reference> vp = here.veh_at(
                        bench.position ).part_with_feature( "WORKBENCH", true ) ) {
                // Vehicle workbench
                const vpart_info &vp_info = vp->part().info();
                if( const cata::optional<vpslot_workbench> &wb_info = vp_info.get_workbench_info() ) {
                    multiplier = wb_info->multiplier;
                    allowed_mass = wb_info->allowed_mass;
                    allowed_volume = wb_info->allowed_volume;
                } else {
                    debugmsg( "part '%S' with WORKBENCH flag has no workbench info", vp->part().name() );
                    return 0.0f;
                }
            }
            break;
        default:
            debugmsg( "Invalid workbench type %d", static_cast<int>( bench.type ) );
            return 0.0f;
    }
    multiplier *= lerped_multiplier( craft_mass, allowed_mass, 1000_kilogram );
    multiplier *= lerped_multiplier( craft_volume, allowed_volume, 1000_liter );
    return multiplier;
}
References iuse::craft(), debugmsg, map::furn(), furniture, get_map(), vpart_info::get_workbench_info(), ground, hands, lerped_multiplier(), int_id< T >::obj(), string_id< T >::obj(), optional_vpart_position::part_with_feature(), bench_location::position, bench_location::type, map::veh_at(), vehicle, and furn_t::workbench.
Referenced by best_bench_here(), craft_progress_message(), and crafting_speed_multiplier().