Cataclysm BN: src/crafting_gui.h File Reference
crafting_gui.h File Reference
Macros
#define CATA_SRC_CRAFTING_GUI_H
Functions
const recipe * select_crafting_recipe (int &batch_size)
void load_recipe_category (const JsonObject &jsobj)
void reset_recipe_categories ()
Macro Definition Documentation
CATA_SRC_CRAFTING_GUI_H
#define CATA_SRC_CRAFTING_GUI_H
Definition at line 3 of file crafting_gui.h.
Function Documentation
load_recipe_category()
void load_recipe_category (const JsonObject & jsobj)
Definition at line 79 of file crafting_gui.cpp.
{
    const std::string category = jsobj.get_string( "id" );
    const bool is_hidden = jsobj.get_bool( "is_hidden", false );
    if( category.find( "CC_" ) != 0 ) {
        jsobj.throw_error( "Crafting category id has to be prefixed with 'CC_'" );
    }
    if( !is_hidden ) {
        if( std::find( craft_cat_list.begin(), craft_cat_list.end(), category ) == craft_cat_list.end() ) {
            craft_cat_list.push_back( category );
        }
        const std::string cat_name = get_cat_unprefixed( category );
        for( const std::string subcat_id : jsobj.get_array( "recipe_subcategories" ) ) {
            if( subcat_id.find( "CSC_" + cat_name + "_" ) != 0 && subcat_id != "CSC_ALL" ) {
                jsobj.throw_error( "Crafting sub-category id has to be prefixed with CSC_<category_name>_" );
            }
            if( std::find( craft_subcat_list[category].begin(), craft_subcat_list[category].end(),
                           subcat_id ) == craft_subcat_list[category].end() ) {
                craft_subcat_list[category].push_back( subcat_id );
            }
        }
    }
}
References craft_cat_list, craft_subcat_list, detail::find(), JsonObject::get_array(), JsonObject::get_bool(), get_cat_unprefixed(), JsonObject::get_string(), and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
reset_recipe_categories()
void reset_recipe_categories ()
Definition at line 129 of file crafting_gui.cpp.
{
    craft_cat_list.clear();
    craft_subcat_list.clear();
}
References craft_cat_list, and craft_subcat_list.
Referenced by DynamicDataLoader::unload_data().
select_crafting_recipe()
const recipe * select_crafting_recipe (int & batch_size)
Definition at line 162 of file crafting_gui.cpp.
{
    struct {
        const recipe *last_recipe = nullptr;
        item dummy;
    } item_info_cache;
    int item_info_scroll = 0;
    int item_info_scroll_popup = 0;
    const auto item_info_data_from_recipe =
    [&]( const recipe * rec, const int count, int &scroll_pos ) {
        if( item_info_cache.last_recipe != rec ) {
            item_info_cache.last_recipe = rec;
            item_info_cache.dummy = rec->create_result();
            item_info_cache.dummy.set_var( "recipe_exemplar", rec->ident().str() );
            item_info_scroll = 0;
            item_info_scroll_popup = 0;
        }
        std::vector<iteminfo> info = item_info_cache.dummy.info( count );
        item_info_data data( item_info_cache.dummy.tname( count ),
                             item_info_cache.dummy.type_name( count ),
                             info, {}, scroll_pos );
        return data;
    };
    avatar &u = get_avatar();
    // always re-translate the category names in case the language has changed
    translate_all();
    const int headHeight = 3;
    const int subHeadHeight = 2;
    bool isWide = false;
    int width = 0;
    int dataLines = 0;
    int dataHalfLines = 0;
    int dataHeight = 0;
    int componentPrintHeight = 0;
    int item_info_width = 0;
    catacurses::window w_head;
    catacurses::window w_subhead;
    catacurses::window w_data;
    catacurses::window w_iteminfo;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const int freeWidth = TERMX - FULL_SCREEN_WIDTH;
        isWide = ( TERMX > FULL_SCREEN_WIDTH && freeWidth > 15 );
        width = isWide ? ( freeWidth > FULL_SCREEN_WIDTH ? FULL_SCREEN_WIDTH * 2 : TERMX ) :
                FULL_SCREEN_WIDTH;
        const int wStart = ( TERMX - width ) / 2;
        const int tailHeight = isWide ? 3 : 4;
        dataLines = TERMY - ( headHeight + subHeadHeight ) - tailHeight;
        dataHalfLines = dataLines / 2;
        dataHeight = TERMY - ( headHeight + subHeadHeight );
        componentPrintHeight = dataHeight - tailHeight - 1;
        w_head = catacurses::newwin( headHeight, width, point( wStart, 0 ) );
        w_subhead = catacurses::newwin( subHeadHeight, width, point( wStart, 3 ) );
        w_data = catacurses::newwin( dataHeight, width, point( wStart,
                                     headHeight + subHeadHeight ) );
        if( isWide ) {
            item_info_width = width - FULL_SCREEN_WIDTH - 2;
            const int item_info_height = dataHeight - 3;
            const point item_info( wStart + width - item_info_width, headHeight + subHeadHeight );
            w_iteminfo = catacurses::newwin( item_info_height, item_info_width,
                                             item_info );
        } else {
            item_info_width = 0;
            w_iteminfo = {};
        }
        ui.position( point( wStart, 0 ), point( width, TERMY ) );
    } );
    ui.mark_resize();
    list_circularizer<std::string> tab( craft_cat_list );
    list_circularizer<std::string> subtab( craft_subcat_list[tab.cur()] );
    std::vector<const recipe *> current;
    struct availability {
        availability( const recipe *r, int batch_size, bool known ) {
            this->known = known;
            const inventory &inv = get_avatar().crafting_inventory();
            auto all_items_filter = r->get_component_filter( recipe_filter_flags::none );
            auto no_rotten_filter = r->get_component_filter( recipe_filter_flags::no_rotten );
            const deduped_requirement_data &req = r->deduped_requirements();
            could_craft_if_knew = req.can_make_with_inventory(
                                      inv, all_items_filter, batch_size, cost_adjustment::start_only );
            can_craft = known && could_craft_if_knew;
            can_craft_non_rotten = req.can_make_with_inventory(
                                       inv, no_rotten_filter, batch_size, cost_adjustment::start_only );
            const requirement_data &simple_req = r->simple_requirements();
            apparently_craftable = simple_req.can_make_with_inventory(
                                       inv, all_items_filter, batch_size, cost_adjustment::start_only );
        }
        bool can_craft;
        bool can_craft_non_rotten;
        bool could_craft_if_knew;
        bool apparently_craftable;
        bool known;
        nc_color selected_color() const {
            return can_craft
                   ? ( can_craft_non_rotten ? h_white : h_brown )
                   : ( could_craft_if_knew ? h_yellow : h_dark_gray );
        }
        nc_color color() const {
            return can_craft
                   ? ( can_craft_non_rotten ? c_white : c_brown )
                   : ( could_craft_if_knew ? c_yellow : c_dark_gray );
        }
    };
    std::vector<availability> available;
    //preserves component color printout between mode rotations
    nc_color rotated_color = c_white;
    int previous_item_line = -1;
    std::string previous_tab;
    std::string previous_subtab;
    int line = 0;
    bool recalc = true;
    bool keepline = false;
    bool done = false;
    bool batch = false;
    bool show_hidden = false;
    bool show_unavailable = false;
    size_t num_hidden = 0;
    int num_recipe = 0;
    int batch_line = 0;
    int display_mode = 0;
    const recipe *chosen = nullptr;
    input_context ctxt( "CRAFTING" );
    ctxt.register_cardinal();
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "CYCLE_MODE" );
    ctxt.register_action( "SCROLL_UP" );
    ctxt.register_action( "SCROLL_DOWN" );
    ctxt.register_action( "PREV_TAB" );
    ctxt.register_action( "NEXT_TAB" );
    ctxt.register_action( "FILTER" );
    ctxt.register_action( "RESET_FILTER" );
    ctxt.register_action( "TOGGLE_FAVORITE" );
    ctxt.register_action( "HELP_RECIPE" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ctxt.register_action( "CYCLE_BATCH" );
    ctxt.register_action( "RELATED_RECIPES" );
    ctxt.register_action( "HIDE_SHOW_RECIPE" );
    ctxt.register_action( "TOGGLE_UNAVAILABLE" );
    const inventory &crafting_inv = u.crafting_inventory();
    const std::vector<npc *> helpers = character_funcs::get_crafting_helpers( u );
    std::string filterstring;
    const auto &available_recipes = u.get_available_recipes( crafting_inv, &helpers );
    std::unordered_map<const recipe *, availability> availability_cache( available_recipes.size() );
    std::vector<const recipe *> all_recipes_flat;
    for( const auto &pr : recipe_dict ) {
        all_recipes_flat.emplace_back( &pr.second );
    }
    const auto &all_recipes = recipe_subset( {}, all_recipes_flat );
    int recipe_scroll_window_min = 0;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        const TAB_MODE m = ( batch ) ? BATCH : ( filterstring.empty() ) ? NORMAL : FILTERED;
        draw_recipe_tabs( w_head, tab.cur(), m );
        const auto &shown_recipes = show_unavailable ? all_recipes : available_recipes;
        draw_recipe_subtabs( w_subhead, tab.cur(), subtab.cur(), shown_recipes, m );
        if( !show_hidden ) {
            draw_hidden_amount( w_head, num_hidden, num_recipe );
        }
        // Clear the screen of recipe data, and draw it anew
        werase( w_data );
        if( isWide ) {
            if( !filterstring.empty() ) {
                fold_and_print( w_data, point( 5, dataLines + 1 ), 0, c_white,
                                _( "Press [<color_yellow>ENTER</color>] to attempt to craft object.  "
                                   "D[<color_yellow>e</color>]scribe, [<color_yellow>F</color>]ind, "
                                   "[<color_red>R</color>]eset, [<color_yellow>m</color>]ode, "
                                   "[<color_yellow>s</color>]how/hide, Re[<color_yellow>L</color>]ated, "
                                   "[<color_yellow>*</color>]Favorite, %s, [<color_yellow>u</color>]navailable, "
                                   "[<color_yellow>?</color>]keybindings" ),
                                ( batch ) ? _( "<color_red>cancel</color> "
                                               "[<color_yellow>b</color>]atch" ) : _( "[<color_yellow>b</color>]atch" ) );
            } else {
                fold_and_print( w_data, point( 5, dataLines + 1 ), 0, c_white,
                                _( "Press [<color_yellow>ENTER</color>] to attempt to craft object.  "
                                   "D[<color_yellow>e</color>]scribe, [<color_yellow>F</color>]ind, "
                                   "[<color_yellow>m</color>]ode, [<color_yellow>s</color>]how/hide, "
                                   "Re[<color_yellow>L</color>]ated, [<color_yellow>*</color>]Favorite, "
                                   "%s, [<color_yellow>u</color>]navailable, "
                                   "[<color_yellow>?</color>]keybindings" ),
                                ( batch ) ? _( "<color_red>cancel</color> "
                                               "[<color_yellow>b</color>]atch" ) : _( "[<color_yellow>b</color>]atch" ) );
            }
        } else {
            if( !filterstring.empty() ) {
                mvwprintz( w_data, point( 2, dataLines + 2 ), c_white,
                           _( "[F]ind, [R]eset, [m]ode, [s]how/hide, Re[L]ated, [*]Fav, [b]atch." ) );
            } else {
                mvwprintz( w_data, point( 2, dataLines + 2 ), c_white,
                           _( "[F]ind, [m]ode, [s]how/hide, Re[L]ated, [*]Fav, [b]atch." ) );
            }
            mvwprintz( w_data, point( 2, dataLines + 1 ), c_white,
                       _( "Press [ENTER] to attempt to craft object.  D[e]scribe, [?]keybindings," ) );
        }
        // Draw borders
        for( int i = 1; i < width - 1; ++i ) { // -
            mvwputch( w_data, point( i, dataHeight - 1 ), BORDER_COLOR, LINE_OXOX );
        }
        for( int i = 0; i < dataHeight - 1; ++i ) { // |
            mvwputch( w_data, point( 0, i ), BORDER_COLOR, LINE_XOXO );
            mvwputch( w_data, point( width - 1, i ), BORDER_COLOR, LINE_XOXO );
        }
        mvwputch( w_data, point( 0, dataHeight - 1 ), BORDER_COLOR, LINE_XXOO ); // |_
        mvwputch( w_data, point( width - 1, dataHeight - 1 ), BORDER_COLOR, LINE_XOOX ); // _|
        cata::optional<point> cursor_pos;
        int recmax = current.size();
        // Draw recipes with scroll list
        // get subset to draw
        calcStartPos( recipe_scroll_window_min, line, dataLines, recmax );
        int recipe_scroll_window_max = std::min( recmax, recipe_scroll_window_min + dataLines );
        for( int i = recipe_scroll_window_min; i < recipe_scroll_window_max; ++i ) {
            std::string tmp_name = current[i]->result_name();
            if( batch ) {
                tmp_name = string_format( _( "%2dx %s" ), i + 1, tmp_name );
            }
            const point print_from( 2, i - recipe_scroll_window_min );
            const bool highlight = i == line;
            const nc_color col = highlight ? available[i].selected_color() : available[i].color();
            if( highlight ) {
                cursor_pos = print_from;
            }
            mvwprintz( w_data, print_from, col, trim_by_length( tmp_name, 27 ) );
        }
        const int count = batch ? line + 1 : 1; // batch size
        if( !current.empty() ) {
            int pane = FULL_SCREEN_WIDTH - 30 - 1;
            nc_color col = available[line].color();
            const auto &req = current[line]->simple_requirements();
            draw_can_craft_indicator( w_head, *current[line] );
            wnoutrefresh( w_head );
            int ypos = 0;
            auto qry = trim( filterstring );
            std::string qry_comps;
            if( qry.compare( 0, 2, "c:" ) == 0 ) {
                qry_comps = qry.substr( 2 );
            }
            std::vector<std::string> component_print_buffer;
            auto tools = req.get_folded_tools_list( pane, col, crafting_inv, count );
            auto comps = req.get_folded_components_list( pane, col, crafting_inv,
                         current[line]->get_component_filter(), count, qry_comps );
            component_print_buffer.insert( component_print_buffer.end(), tools.begin(), tools.end() );
            component_print_buffer.insert( component_print_buffer.end(), comps.begin(), comps.end() );
            if( !u.knows_recipe( current[line] ) ) {
                component_print_buffer.push_back( _( "Recipe not memorized yet" ) );
                auto books_with_recipe = show_unavailable
                                         ? crafting::get_books_for_recipe( current[line] )
                                         : crafting::get_books_for_recipe( u, crafting_inv, current[line] );
                std::string enumerated_books =
                    enumerate_as_string( books_with_recipe.begin(), books_with_recipe.end(),
                []( itype_id type_id ) {
                    return colorize( item::nname( type_id ), c_cyan );
                } );
                const std::string text = string_format( _( "Written in: %s" ), enumerated_books );
                std::vector<std::string> folded_lines = foldstring( text, pane );
                component_print_buffer.insert(
                    component_print_buffer.end(), folded_lines.begin(), folded_lines.end() );
            }
            //handle positioning of component list if it needed to be scrolled
            int componentPrintOffset = 0;
            if( display_mode > 1 ) {
                componentPrintOffset = ( display_mode - 1 ) * componentPrintHeight;
            }
            if( component_print_buffer.size() < static_cast<size_t>( componentPrintOffset ) ) {
                componentPrintOffset = 0;
                if( previous_tab != tab.cur() || previous_subtab != subtab.cur() || previous_item_line != line ) {
                    display_mode = 1;
                } else {
                    display_mode = 0;
                }
            }
            //only used to preserve mode position on components when
            //moving to another item and the view is already scrolled
            previous_tab = tab.cur();
            previous_subtab = subtab.cur();
            previous_item_line = line;
            const int xpos = 30;
            if( display_mode == 0 ) {
                print_colored_text(
                    w_data, point( xpos, ypos++ ), col, col,
                    string_format( _( "Primary skill: %s" ),
                                   current[line]->primary_skill_string( &u, false ) ) );
                ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                        _( "Other skills: %s" ),
                                        current[line]->required_skills_string( &u, false, false ) );
                const int expected_turns = u.expected_time_to_craft( *current[line],
                                           count ) / to_moves<int>( 1_turns );
                ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                        _( "Time to complete: <color_cyan>%s</color>" ),
                                        to_string( time_duration::from_turns( expected_turns ) ) );
                ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                        _( "Batch time savings: <color_cyan>%s</color>" ),
                                        current[line]->batch_savings_string() );
                const int makes = current[line]->makes_amount();
                if( makes > 1 ) {
                    ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                            _( "One batch makes: <color_cyan>%d</color>" ),
                                            makes );
                }
                print_colored_text(
                    w_data, point( xpos, ypos++ ), col, col,
                    string_format( _( "Dark craftable?  <color_cyan>%s</color>" ),
                                   current[line]->has_flag( flag_BLIND_EASY ) ? _( "Easy" ) :
                                   current[line]->has_flag( flag_BLIND_HARD ) ? _( "Hard" ) :
                                   _( "Impossible" ) ) );
                std::string nearby_string;
                const int nearby_amount = crafting_inv.count_item( current[line]->result() );
                if( nearby_amount == 0 ) {
                    nearby_string = "<color_light_gray>0</color>";
                } else if( nearby_amount > 9000 ) {
                    // at some point you get too many to count at a glance and just know you have a lot
                    nearby_string = _( "<color_red>It's Over 9000!!!</color>" );
                } else {
                    nearby_string = string_format( "<color_yellow>%d</color>", nearby_amount );
                }
                ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                        _( "Nearby: %s" ), nearby_string );
                if( available[line].can_craft && !available[line].can_craft_non_rotten ) {
                    ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                            _( "<color_red>Will use rotten ingredients</color>" ) );
                }
                const bool too_complex = current[line]->deduped_requirements().is_too_complex();
                if( available[line].can_craft && too_complex ) {
                    ypos += fold_and_print( w_data, point( xpos, ypos ), pane, col,
                                            _( "Due to the complex overlapping requirements, this "
                                               "recipe <color_yellow>may appear to be craftable "
                                               "when it is not</color>." ) );
                }
                if( !available[line].can_craft &&
                    available[line].apparently_craftable &&
                    available[line].known ) {
                    ypos += fold_and_print(
                                w_data, point( xpos, ypos ), pane, col,
                                _( "<color_red>Cannot be crafted because the same item is needed "
                                   "for multiple components</color>" ) );
                }
                if( !available[line].known ) {
                    ypos += fold_and_print(
                                w_data, point( xpos, ypos ), pane, col,
                                _( "<color_red>Not known</color>" ) );
                }
                ypos += print_items( *current[line], w_data, point( xpos, ypos ), col, batch ? line + 1 : 1 );
            }
            //color needs to be preserved in case part of the previous page was cut off
            nc_color stored_color = col;
            if( display_mode > 1 ) {
                stored_color = rotated_color;
            } else {
                rotated_color = col;
            }
            int components_printed = 0;
            for( size_t i = static_cast<size_t>( componentPrintOffset );
                 i < component_print_buffer.size(); i++ ) {
                if( ypos >= componentPrintHeight ) {
                    break;
                }
                components_printed++;
                print_colored_text( w_data, point( xpos, ypos++ ), stored_color, col, component_print_buffer[i] );
            }
            if( ypos >= componentPrintHeight &&
                component_print_buffer.size() > static_cast<size_t>( components_printed ) ) {
                mvwprintz( w_data, point( xpos, ypos++ ), col,
                           _( "v (%s for more)" ),
                           ctxt.press_x( "CYCLE_MODE" ) );
                rotated_color = stored_color;
            }
        }
        draw_scrollbar( w_data, line, dataLines, recmax, point_zero );
        wnoutrefresh( w_data );
        if( isWide && !current.empty() ) {
            item_info_data data = item_info_data_from_recipe( current[line], count, item_info_scroll );
            data.without_getch = true;
            data.without_border = true;
            data.scrollbar_left = false;
            data.use_full_win = true;
            draw_item_info( w_iteminfo, data );
        }
        if( cursor_pos ) {
            // place the cursor at the selected item name as expected by screen readers
            wmove( w_data, cursor_pos.value() );
            wnoutrefresh( w_data );
        }
    } );
    do {
        const auto &shown_recipes = show_unavailable ? all_recipes : available_recipes;
        if( recalc ) {
            // When we switch tabs, redraw the header
            recalc = false;
            if( !keepline ) {
                line = 0;
            } else {
                keepline = false;
            }
            if( display_mode > 1 ) {
                display_mode = 1;
            }
            show_hidden = false;
            available.clear();
            if( batch ) {
                current.clear();
                for( int i = 1; i <= 50; i++ ) {
                    current.push_back( chosen );
                    available.push_back( availability( chosen, i,
                                                       !show_unavailable || available_recipes.contains( *chosen ) ) );
                }
            } else {
                std::vector<const recipe *> picking;
                if( !filterstring.empty() ) {
                    auto qry = trim( filterstring );
                    size_t qry_begin = 0;
                    size_t qry_end = 0;
                    recipe_subset filtered_recipes = shown_recipes;
                    do {
                        // Find next ','
                        qry_end = qry.find_first_of( ',', qry_begin );
                        auto qry_filter_str = trim( qry.substr( qry_begin, qry_end - qry_begin ) );
                        // Process filter
                        if( qry_filter_str.size() > 2 && qry_filter_str[1] == ':' ) {
                            switch( qry_filter_str[0] ) {
                                case 't':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::tool );
                                    break;
                                case 'c':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::component );
                                    break;
                                case 's':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::skill );
                                    break;
                                case 'p':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::primary_skill );
                                    break;
                                case 'Q':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::quality );
                                    break;
                                case 'q':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::quality_result );
                                    break;
                                case 'd':
                                    filtered_recipes = filtered_recipes.reduce( qry_filter_str.substr( 2 ),
                                                       recipe_subset::search_type::description_result );
                                    break;
                                case 'm': {
                                    auto &learned = u.get_learned_recipes();
                                    recipe_subset temp_subset;
                                    if( query_is_yes( qry_filter_str ) ) {
                                        temp_subset = shown_recipes.intersection( learned );
                                    } else {
                                        temp_subset = shown_recipes.difference( learned );
                                    }
                                    filtered_recipes = filtered_recipes.intersection( temp_subset );
                                    break;
                                }
                                default:
                                    current.clear();
                            }
                        } else {
                            filtered_recipes = filtered_recipes.reduce( qry_filter_str );
                        }
                        qry_begin = qry_end + 1;
                    } while( qry_end != std::string::npos );
                    picking.insert( picking.end(), filtered_recipes.begin(), filtered_recipes.end() );
                } else if( subtab.cur() == "CSC_*_FAVORITE" ) {
                    picking = shown_recipes.favorite();
                } else if( subtab.cur() == "CSC_*_RECENT" ) {
                    picking = shown_recipes.recent();
                } else if( subtab.cur() == "CSC_*_HIDDEN" ) {
                    current = shown_recipes.hidden();
                    show_hidden = true;
                } else {
                    picking = shown_recipes.in_category( tab.cur(), subtab.cur() != "CSC_ALL" ? subtab.cur() : "" );
                }
                if( !show_hidden ) {
                    current.clear();
                    for( auto i : picking ) {
                        if( uistate.hidden_recipes.find( i->ident() ) == uistate.hidden_recipes.end() ) {
                            current.push_back( i );
                        }
                    }
                    num_hidden = picking.size() - current.size();
                    num_recipe = picking.size();
                }
                available.reserve( current.size() );
                // cache recipe availability on first display
                for( const recipe *e : current ) {
                    if( availability_cache.count( e ) == 0 ) {
                        availability_cache.emplace( e, availability( e, 1,
                                                    !show_unavailable || available_recipes.contains( *e ) ) );
                    }
                }
                if( subtab.cur() != "CSC_*_RECENT" ) {
                    std::stable_sort( current.begin(), current.end(),
                    []( const recipe * a, const recipe * b ) {
                        return b->difficulty < a->difficulty;
                    } );
                    std::stable_sort( current.begin(), current.end(),
                    [&]( const recipe * a, const recipe * b ) {
                        return availability_cache.at( a ).can_craft &&
                               !availability_cache.at( b ).can_craft;
                    } );
                }
                std::transform( current.begin(), current.end(),
                std::back_inserter( available ), [&]( const recipe * e ) {
                    return availability_cache.at( e );
                } );
            }
            // current/available have been rebuilt, make sure our cursor is still in range
            if( current.empty() ) {
                line = 0;
            } else {
                line = std::min( line, static_cast<int>( current.size() ) - 1 );
            }
        }
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "CYCLE_MODE" ) {
            display_mode = display_mode + 1;
            if( display_mode <= 0 ) {
                display_mode = 0;
            }
        } else if( action == "LEFT" ) {
            std::string start = subtab.cur();
            do {
                subtab.prev();
            } while( subtab.cur() != start && shown_recipes.empty_category( tab.cur(),
                     subtab.cur() != "CSC_ALL" ? subtab.cur() : "" ) );
            recalc = true;
        } else if( action == "SCROLL_UP" ) {
            item_info_scroll--;
        } else if( action == "SCROLL_DOWN" ) {
            item_info_scroll++;
        } else if( action == "PREV_TAB" ) {
            tab.prev();
            // Default ALL
            subtab = list_circularizer<std::string>( craft_subcat_list[tab.cur()] );
            recalc = true;
        } else if( action == "RIGHT" ) {
            std::string start = subtab.cur();
            do {
                subtab.next();
            } while( subtab.cur() != start && shown_recipes.empty_category( tab.cur(),
                     subtab.cur() != "CSC_ALL" ? subtab.cur() : "" ) );
            recalc = true;
        } else if( action == "NEXT_TAB" ) {
            tab.next();
            // Default ALL
            subtab = list_circularizer<std::string>( craft_subcat_list[tab.cur()] );
            recalc = true;
        } else if( action == "DOWN" ) {
            line++;
        } else if( action == "UP" ) {
            line--;
        } else if( action == "CONFIRM" ) {
            if( available.empty() || !available[line].can_craft ) {
                popup( _( "You can't do that!  Press [<color_yellow>ESC</color>]!" ) );
            } else if( !u.check_eligible_containers_for_crafting( *current[line],
                       ( batch ) ? line + 1 : 1 ) ) {
                // popup is already inside check
            } else {
                chosen = current[line];
                batch_size = ( batch ) ? line + 1 : 1;
                done = true;
            }
        } else if( action == "HELP_RECIPE" ) {
            if( current.empty() ) {
                popup( _( "Nothing selected!  Press [<color_yellow>ESC</color>]!" ) );
                recalc = true;
                continue;
            }
            item_info_data data = item_info_data_from_recipe( current[line], 1, item_info_scroll_popup );
            data.handle_scrolling = true;
            draw_item_info( []() -> catacurses::window {
                const int width = std::min( TERMX, FULL_SCREEN_WIDTH );
                const int height = std::min( TERMY, FULL_SCREEN_HEIGHT );
                return catacurses::newwin( height, width, point( ( TERMX - width ) / 2, ( TERMY - height ) / 2 ) );
            }, data );
            recalc = true;
            keepline = true;
        } else if( action == "FILTER" ) {
            struct SearchPrefix {
                char key;
                std::string example;
                std::string description;
            };
            std::vector<SearchPrefix> prefixes = {
                { 'q', _( "metal sawing" ), _( "<color_cyan>quality</color> of resulting item" ) },
                //~ Example result description search term
                { 'd', _( "reach attack" ), _( "<color_cyan>full description</color> of resulting item (slow)" ) },
                { 'c', _( "two by four" ), _( "<color_cyan>component</color> required to craft" ) },
                { 'p', _( "tailoring" ), _( "<color_cyan>primary skill</color> used to craft" ) },
                { 's', _( "cooking" ), _( "<color_cyan>any skill</color> used to craft" ) },
                { 'Q', _( "fine bolt turning" ), _( "<color_cyan>quality</color> required to craft" ) },
                { 't', _( "soldering iron" ), _( "<color_cyan>tool</color> required to craft" ) },
                { 'm', _( "yes" ), _( "recipes which are <color_cyan>memorized</color> or not" ) },
            };
            int max_example_length = 0;
            for( const auto &prefix : prefixes ) {
                max_example_length = std::max( max_example_length, utf8_width( prefix.example ) );
            }
            std::string spaces( max_example_length, ' ' );
            std::string description =
                _( "The default is to search result names.  Some single-character prefixes "
                   "can be used with a colon <color_red>:</color> to search in other ways.  Additional filters "
                   "are separated by commas <color_red>,</color>.\n"
                   "\n\n"
                   "<color_white>Examples:</color>\n" );
            {
                std::string example_name = _( "shirt" );
                auto padding = max_example_length - utf8_width( example_name );
                description += string_format(
                                   _( "  <color_white>%s</color>%.*s    %s\n" ),
                                   example_name, padding, spaces,
                                   _( "<color_cyan>name</color> of resulting item" ) );
            }
            for( const auto &prefix : prefixes ) {
                auto padding = max_example_length - utf8_width( prefix.example );
                description += string_format(
                                   _( "  <color_yellow>%c</color><color_white>:%s</color>%.*s  %s\n" ),
                                   prefix.key, prefix.example, padding, spaces, prefix.description );
            }
            description +=
                _( "\nUse <color_red>up/down arrow</color> to go through your search history." );
            description += "\n\n\n";
            string_input_popup()
            .title( _( "Search:" ) )
            .width( 85 )
            .description( description )
            .desc_color( c_light_gray )
            .identifier( "craft_recipe_filter" )
            .hist_use_uilist( false )
            .edit( filterstring );
            recalc = true;
        } else if( action == "QUIT" ) {
            chosen = nullptr;
            done = true;
        } else if( action == "RESET_FILTER" ) {
            filterstring.clear();
            recalc = true;
        } else if( action == "CYCLE_BATCH" ) {
            if( current.empty() ) {
                popup( _( "Nothing selected!  Press [<color_yellow>ESC</color>]!" ) );
                recalc = true;
                continue;
            }
            batch = !batch;
            if( batch ) {
                batch_line = line;
                chosen = current[batch_line];
            } else {
                line = batch_line;
                keepline = true;
            }
            recalc = true;
        } else if( action == "TOGGLE_FAVORITE" ) {
            keepline = true;
            recalc = true;
            if( current.empty() ) {
                popup( _( "Nothing selected!  Press [<color_yellow>ESC</color>]!" ) );
                continue;
            }
            if( uistate.favorite_recipes.find( current[line]->ident() ) != uistate.favorite_recipes.end() ) {
                uistate.favorite_recipes.erase( current[line]->ident() );
            } else {
                uistate.favorite_recipes.insert( current[line]->ident() );
            }
        } else if( action == "HIDE_SHOW_RECIPE" ) {
            if( current.empty() ) {
                popup( _( "Nothing selected!  Press [<color_yellow>ESC</color>]!" ) );
                recalc = true;
                continue;
            }
            if( show_hidden ) {
                uistate.hidden_recipes.erase( current[line]->ident() );
            } else {
                uistate.hidden_recipes.insert( current[line]->ident() );
            }
            recalc = true;
        } else if( action == "RELATED_RECIPES" ) {
            if( current.empty() ) {
                popup( _( "Nothing selected!  Press [<color_yellow>ESC</color>]!" ) );
                recalc = true;
                continue;
            }
            std::string recipe_name = peek_related_recipe( current[line], shown_recipes );
            if( recipe_name.empty() ) {
                keepline = true;
            } else {
                filterstring = recipe_name;
            }
            recalc = true;
        } else if( action == "TOGGLE_UNAVAILABLE" ) {
            show_unavailable = !show_unavailable;
            recalc = true;
        }
        if( line < 0 ) {
            line = current.size() - 1;
        } else if( line >= static_cast<int>( current.size() ) ) {
            line = 0;
        }
    } while( !done );
    return chosen;
}
References _, a, action, available, b, BATCH, recipe_subset::begin(), BORDER_COLOR, c_brown, c_dark_gray, c_light_gray, c_white, c_yellow, calcStartPos(), requirement_data::can_make_with_inventory(), deduped_requirement_data::can_make_with_inventory(), player::check_eligible_containers_for_crafting(), recipe_subset::clear(), color(), recipe_subset::component, detail::count(), inventory::count_item(), craft_cat_list, craft_subcat_list, Character::crafting_inventory(), recipe::create_result(), list_circularizer< T >::cur(), recipe::deduped_requirements(), string_input_popup::desc_color(), string_input_popup::description(), recipe_subset::description_result, recipe_subset::difference(), detail::digits::done, draw_can_craft_indicator(), draw_hidden_amount(), draw_item_info(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_scrollbar(), string_input_popup::edit(), recipe_subset::end(), enumerate_as_string(), player::expected_time_to_craft(), recipe_subset::favorite(), uistatedata::favorite_recipes, FILTERED, flag_BLIND_EASY(), flag_BLIND_HARD(), fold_and_print(), foldstring(), time_duration::from_turns(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, player::get_available_recipes(), get_avatar(), crafting::get_books_for_recipe(), recipe::get_component_filter(), character_funcs::get_crafting_helpers(), Character::get_learned_recipes(), h_brown, h_dark_gray, h_white, h_yellow, input_context::handle_input(), item_info_data::handle_scrolling, uistatedata::hidden_recipes, string_input_popup::hist_use_uilist(), recipe::ident(), string_input_popup::identifier(), recipe_subset::intersection(), Character::knows_recipe(), line(), LINE_OXOX, LINE_XOOX, LINE_XOXO, LINE_XXOO, mvwprintz(), mvwputch(), catacurses::newwin(), list_circularizer< T >::next(), no_rotten, none, NORMAL, peek_related_recipe(), point_zero, popup(), prefix, input_context::press_x(), list_circularizer< T >::prev(), recipe_subset::primary_skill, print_colored_text(), print_items(), recipe_subset::quality, recipe_subset::quality_result, query_is_yes(), recipe_dict, ui_manager::redraw(), recipe_subset::reduce(), input_context::register_action(), input_context::register_cardinal(), item_info_data::scrollbar_left, item::set_var(), recipe::simple_requirements(), recipe_subset::skill, start_only, string_id< T >::str(), string_format(), TERMX, TERMY, string_input_popup::title(), to_string(), recipe_subset::tool, iexamine::transform(), translate_all(), trim(), trim_by_length(), uistate, item_info_data::use_full_win, utf8_width(), cata::optional< T >::value(), catacurses::werase(), string_input_popup::width(), item_info_data::without_border, item_info_data::without_getch, catacurses::wmove(), and catacurses::wnoutrefresh().
Referenced by player::craft(), and player::long_craft().