Cataclysm BN: src/crafting.cpp File Reference
crafting.cpp File Reference
#include "crafting.h"
#include <algorithm>
#include <cassert>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "avatar.h"
#include "bionics.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "color.h"
#include "character_functions.h"
#include "craft_command.h"
#include "crafting_gui.h"
#include "debug.h"
#include "enums.h"
#include "faction.h"
#include "flag.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "line.h"
#include "map.h"
#include "map_selector.h"
#include "mapdata.h"
#include "messages.h"
#include "mutation.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
Classes
struct avail_tool_comp
struct disass_prompt_result
Namespaces
namespace crafting
Functions
static const std::string flag_BLIND_EASY ("BLIND_EASY")
static const std::string flag_BLIND_HARD ("BLIND_HARD")
static const std::string flag_BYPRODUCT ("BYPRODUCT")
static const std::string flag_COOKED ("COOKED")
static const std::string flag_ETHEREAL_ITEM ("ETHEREAL_ITEM")
static const std::string flag_FIT ("FIT")
static const std::string flag_FIX_FARSIGHT ("FIX_FARSIGHT")
static const std::string flag_FULL_MAGAZINE ("FULL_MAGAZINE")
static const std::string flag_HIDDEN_POISON ("HIDDEN_POISON")
static const std::string flag_NO_RESIZE ("NO_RESIZE")
static const std::string flag_NO_UNLOAD ("NO_UNLOAD")
static const std::string flag_NUTRIENT_OVERRIDE ("NUTRIENT_OVERRIDE")
static const std::string flag_UNCRAFT_LIQUIDS_CONTAINED ("UNCRAFT_LIQUIDS_CONTAINED")
static const std::string flag_VARSIZE ("VARSIZE")
static std::pair< bench_type, float > best_bench_here (const item &craft, const tripoint &loc, bool can_lift)
static bool crafting_allowed (const Character &who, const recipe &rec)
float lighting_crafting_speed_multiplier (const Character &who, const recipe &rec)
float morale_crafting_speed_multiplier (const Character &who, const recipe &rec)
template<typename T >
static float lerped_multiplier (const T &value, const T &low, const T &high)
float workbench_crafting_speed_multiplier (const item &craft, const bench_location &bench)
float crafting_speed_multiplier (const Character &who, const recipe &rec, bool in_progress)
float crafting_speed_multiplier (const Character &who, const item &craft, const bench_location &bench)
static bool is_container_eligible_for_crafting (const item &cont, bool allow_bucket)
static void set_components (std::list< item > &components, const std::list< item > &used, const int batch_size, const size_t offset)
static item_location set_item_map (const tripoint &loc, item &newit)
Helper for set_item_map_or_vehicle This is needed to still get a vaild item_location if overflow occurs.
static item_location set_item_map_or_vehicle (const player &p, const tripoint &loc, item &newit)
Set an item on the map or in a vehicle and return the new location.
static item_location set_item_inventory (player &p, item &newit)
static void destroy_random_component (item &craft, const player &crafter)
void complete_craft (player &p, item &craft, const bench_location &)
static void drop_or_handle (const item &newit, Character &who)
static void empty_buckets (player &p)
static std::vector< avail_tool_comp > crafting::find_tool_component (const Character *player_with_inv, const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, cost_adjustment charge_mod)
static comp_selection< tool_comp > crafting::query_tool_selection (const std::vector< avail_tool_comp > &available_tools, const std::string &hotkeys, bool can_cancel, bool is_npc)
comp_selection< tool_comp > crafting::select_tool_component (const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, const Character *player_with_inv, bool can_cancel, const std::string &hotkeys, cost_adjustment adjustment)
Returns selected tool component that matches one of the expected ones.
comp_selection< tool_comp > crafting::select_tool_component (const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, const Character *player_with_inv, bool can_cancel)
static disass_prompt_result prompt_disassemble_in_seq (avatar &you, const item &obj, bool interactive, bool autoselect_max)
static bool prompt_disassemble_single (avatar &you, item_location target, bool interactive)
void remove_ammo (std::list< item > &dis_items, Character &who)
Removes any (removable) ammo from each item and stores it in character's inventory.
void remove_ammo (item &dis_item, Character &who)
Removes any (removable) ammo and stores it in character's inventory.
bench_location find_best_bench (const player &p, const item &craft)
std::set< itype_id > crafting::get_books_for_recipe (const Character &c, const inventory &crafting_inv, const recipe *r)
Returns the set of book types in crafting_inv that provide the given recipe.
std::set< itype_id > crafting::get_books_for_recipe (const recipe *r)
Returns the set of book types that provide the given recipe.
int crafting::charges_for_complete (int full_charges)
int crafting::charges_for_starting (int full_charges)
int crafting::charges_for_continuing (int full_charges)
Variables
static const activity_id ACT_CRAFT ("ACT_CRAFT")
static const efftype_id effect_contacts ("contacts")
static const itype_id itype_plut_cell ("plut_cell")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_tailor ("tailor")
static const trait_id trait_BURROW ("BURROW")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_HYPEROPIC ("HYPEROPIC")
Function Documentation
best_bench_here()
static std::pair< bench_type, float > best_bench_here (const item & craft, const tripoint & loc, bool can_lift) static
Definition at line 2326 of file crafting.cpp.
{
    bench_type best_type = bench_type::ground;
    float best_mult = workbench_crafting_speed_multiplier( craft, bench_location{bench_type::ground, loc} );
    if( can_lift ) {
        float hands_mult = workbench_crafting_speed_multiplier( craft, bench_location{bench_type::hands, loc} );
        if( hands_mult > best_mult ) {
            best_type = bench_type::hands;
            best_mult = hands_mult;
        }
    }
    if( g->m.furn( loc ).obj().workbench ) {
        float furn_mult = workbench_crafting_speed_multiplier( craft, bench_location{bench_type::furniture, loc} );
        if( furn_mult > best_mult ) {
            best_type = bench_type::furniture;
            best_mult = furn_mult;
        }
    }
    if( const cata::optional<vpart_reference> vp = g->m.veh_at(
                loc ).part_with_feature( "WORKBENCH", true ) ) {
        float veh_mult = workbench_crafting_speed_multiplier( craft, bench_location{bench_type::vehicle, loc} );
        if( veh_mult > best_mult ) {
            best_type = bench_type::vehicle;
            best_mult = veh_mult;
        }
    }
    return std::make_pair( best_type, best_mult );
}
References iuse::craft(), furniture, g, ground, hands, vehicle, and workbench_crafting_speed_multiplier().
Referenced by find_best_bench(), and player::start_craft().
complete_craft()
void complete_craft (player & p, item & craft, const bench_location & bench)
Intelligence increases chance to learn recipe when crafting from a book
Definition at line 1016 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "complete_craft() called on non-craft '%s.'  Aborting.", craft.tname() );
        return;
    }
    const recipe &making = craft.get_making();
    const int batch_size = craft.charges;
    std::list<item> &used = craft.components;
    const double relative_rot = craft.get_relative_rot();
    // Set up the new item, and assign an inventory letter if available
    std::vector<item> newits = making.create_results( batch_size );
    const bool should_heat = making.hot_result();
    bool first = true;
    size_t newit_counter = 0;
    for( item &newit : newits ) {
        // Points to newit unless newit is a non-empty container, then it points to newit's contents.
        // Necessary for things like canning soup; sometimes we want to operate on the soup, not the can.
        item &food_contained = ( newit.is_container() && !newit.contents.empty() ) ?
                               newit.contents.back() : newit;
        // messages, learning of recipe, food spoilage calculation only once
        if( first ) {
            first = false;
            // TODO: reconsider recipe memorization
            if( p.knows_recipe( &making ) ) {
                add_msg( _( "You craft %s from memory." ), making.result_name() );
            } else {
                add_msg( _( "You craft %s using a book as a reference." ), making.result_name() );
                // If we made it, but we don't know it,
                // we're making it from a book and have a chance to learn it.
                // Base expected time to learn is 1000*(difficulty^4)/skill/int moves.
                // This means time to learn is greatly decreased with higher skill level,
                // but also keeps going up as difficulty goes up.
                // Worst case is lvl 10, which will typically take
                // 10^4/10 (1,000) minutes, or about 16 hours of crafting it to learn.
                int difficulty = p.has_recipe( &making, p.crafting_inventory(), p.get_crafting_helpers() );
                ///\EFFECT_INT increases chance to learn recipe when crafting from a book
                const double learning_speed =
                    std::max( p.get_skill_level( making.skill_used ), 1 ) *
                    std::max( p.get_int(), 1 );
                const double time_to_learn = 1000 * 8 * std::pow( difficulty, 4 ) / learning_speed;
                if( x_in_y( making.time, time_to_learn ) ) {
                    p.learn_recipe( &making );
                    add_msg( m_good, _( "You memorized the recipe for %s!" ),
                             making.result_name() );
                }
            }
        }
        food_contained.inherit_flags( used, making );
        for( const std::string &flag : making.flags_to_delete ) {
            food_contained.unset_flag( flag );
        }
        // Don't store components for things made by charges,
        // Don't store components for things that can't be uncrafted.
        if( recipe_dictionary::get_uncraft( making.result() ) && !food_contained.count_by_charges() &&
            making.is_reversible() ) {
            // Setting this for items counted by charges gives only problems:
            // those items are automatically merged everywhere (map/vehicle/inventory),
            // which would either lose this information or merge it somehow.
            set_components( food_contained.components, used, batch_size, newit_counter );
            newit_counter++;
        } else if( food_contained.is_food() && !food_contained.has_flag( flag_NUTRIENT_OVERRIDE ) ) {
            // if a component item has "cooks_like" it will be replaced by that item as a component
            for( item &comp : used ) {
                // only comestibles have cooks_like.  any other type of item will throw an exception, so filter those out
                if( comp.is_comestible() && !comp.get_comestible()->cooks_like.is_empty() ) {
                    comp = item( comp.get_comestible()->cooks_like, comp.birthday(), comp.charges );
                }
                // If this recipe is cooked, components are no longer raw.
                if( should_heat ) {
                    comp.set_flag_recursive( flag_COOKED );
                }
            }
            // use a copy of the used list so that the byproducts don't build up over iterations (#38071)
            std::list<item> usedbp = used;
            // byproducts get stored as a "component" but with a byproduct flag for consumption purposes
            if( making.has_byproducts() ) {
                for( item &byproduct : making.create_byproducts( batch_size ) ) {
                    byproduct.set_flag( flag_BYPRODUCT );
                    usedbp.push_back( byproduct );
                }
            }
            // store components for food recipes that do not have the override flag
            set_components( food_contained.components, usedbp, batch_size, newit_counter );
            // store the number of charges the recipe would create with batch size 1.
            if( &newit != &food_contained ) {  // If a canned/contained item was crafted
                //  the container holds exactly one completion of the recipe, no matter the batch size.
                food_contained.recipe_charges = food_contained.charges;
            } else { // Otherwise, the item is already stacked so we need to divide by batch size.
                newit.recipe_charges = newit.charges / batch_size;
            }
            newit_counter++;
        }
        if( food_contained.goes_bad() ) {
            food_contained.set_relative_rot( relative_rot );
        }
        newit.set_owner( p.get_faction()->id );
        // If these aren't equal, newit is a container, so finalize its contents too.
        if( &newit != &food_contained ) {
            food_contained.set_owner( p.get_faction()->id );
        }
        if( newit.made_of( LIQUID ) ) {
            liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
        } else {
            set_item_inventory( p, newit );
        }
    }
    if( making.has_byproducts() ) {
        std::vector<item> bps = making.create_byproducts( batch_size );
        for( auto &bp : bps ) {
            if( bp.goes_bad() ) {
                bp.set_relative_rot( relative_rot );
            }
            bp.set_owner( p.get_faction()->id );
            if( bp.made_of( LIQUID ) ) {
                liquid_handler::handle_all_liquid( bp, PICKUP_RANGE );
            } else {
                set_item_inventory( p, bp );
            }
        }
    }
    p.inv.restack( p );
}
References _, add_msg(), item_contents::back(), item::charges, item::components, item::contents, item::count_by_charges(), iuse::craft(), Character::crafting_inventory(), recipe::create_byproducts(), recipe::create_results(), debugmsg, flag_BYPRODUCT(), flag_COOKED(), flag_NUTRIENT_OVERRIDE(), recipe::flags_to_delete, player::get_crafting_helpers(), Character::get_faction(), Character::get_int(), Character::get_skill_level(), recipe_dictionary::get_uncraft(), item::goes_bad(), liquid_handler::handle_all_liquid(), recipe::has_byproducts(), item::has_flag(), player::has_recipe(), recipe::hot_result(), faction_template::id, item::inherit_flags(), Character::inv, item::is_food(), recipe::is_reversible(), Character::knows_recipe(), Character::learn_recipe(), LIQUID, m_good, PICKUP_RANGE, item::recipe_charges, inventory::restack(), recipe::result(), recipe::result_name(), set_components(), set_item_inventory(), item::set_owner(), item::set_relative_rot(), recipe::skill_used, recipe::time, item::unset_flag(), and x_in_y().
Referenced by activity_handlers::craft_do_turn().
crafting_allowed()
static bool crafting_allowed (const Character & who, const recipe & rec) static
Definition at line 112 of file crafting.cpp.
{
    if( morale_crafting_speed_multiplier( who, rec ) <= 0.0f ) {
        add_msg( m_info, _( "Your morale is too low to craft such a difficult thing" ) );
        return false;
    }
    if( lighting_crafting_speed_multiplier( who, rec ) <= 0.0f ) {
        add_msg( m_info, _( "You can't see to craft!" ) );
        return false;
    }
    if( rec.category == "CC_BUILDING" ) {
        add_msg( m_info, _( "Overmap terrain building recipes are not implemented yet!" ) );
        return false;
    }
    return true;
}
References _, add_msg(), recipe::category, lighting_crafting_speed_multiplier(), m_info, and morale_crafting_speed_multiplier().
Referenced by player::craft(), player::long_craft(), and player::making_would_work().
crafting_speed_multiplier() [1/2]
float crafting_speed_multiplier (const Character & who, const item & craft, const bench_location & bench)
Definition at line 282 of file crafting.cpp.
{
    if( !craft.is_craft() ) {
        debugmsg( "Can't calculate crafting speed multiplier of non-craft '%s'", craft.tname() );
        return 1.0f;
    }
    const recipe &rec = craft.get_making();
    const float light_multi = lighting_crafting_speed_multiplier( who, rec );
    const float bench_multi = workbench_crafting_speed_multiplier( craft, bench );
    const float morale_multi = morale_crafting_speed_multiplier( who, rec );
    const float total_multi = light_multi * bench_multi * morale_multi;
    if( light_multi <= 0.0f ) {
        who.add_msg_if_player( m_bad, _( "You can no longer see well enough to keep crafting." ) );
        return 0.0f;
    }
    if( bench_multi <= 0.1f || ( bench_multi <= 0.33f && total_multi <= 0.2f ) ) {
        who.add_msg_if_player( m_bad, _( "The %s is too large and/or heavy to work on.  You may want to"
                                         " use a workbench or a smaller batch size" ), craft.tname() );
        return 0.0f;
    }
    if( morale_multi <= 0.2f || ( morale_multi <= 0.33f && total_multi <= 0.2f ) ) {
        who.add_msg_if_player( m_bad, _( "Your morale is too low to continue crafting." ) );
        return 0.0f;
    }
    // If we're working below 20% speed, just give up
    if( total_multi <= 0.2f ) {
        who.add_msg_if_player( m_bad, _( "You are too frustrated to continue and just give up." ) );
        return 0.0f;
    }
    if( calendar::once_every( 1_hours ) && total_multi < 0.75f ) {
        if( light_multi <= 0.5f ) {
            who.add_msg_if_player( m_bad, _( "You can't see well and are working slowly." ) );
        }
        if( bench_multi <= 0.5f ) {
            who.add_msg_if_player( m_bad,
                                   _( "The %s is to large and/or heavy to work on comfortably.  You are"
                                      " working slowly." ), craft.tname() );
        }
        if( morale_multi <= 0.5f ) {
            who.add_msg_if_player( m_bad, _( "You can't focus and are working slowly." ) );
        }
    }
    return total_multi;
}
References _, Creature::add_msg_if_player(), iuse::craft(), debugmsg, lighting_crafting_speed_multiplier(), m_bad, morale_crafting_speed_multiplier(), calendar::once_every(), and workbench_crafting_speed_multiplier().
crafting_speed_multiplier() [2/2]
float crafting_speed_multiplier (const Character & who, const recipe & rec, bool in_progress)
Definition at line 266 of file crafting.cpp.
{
    const float result = morale_crafting_speed_multiplier( who, rec ) *
                         lighting_crafting_speed_multiplier( who, rec );
    // Can't start if we'd need 300% time, but we can still finish the job
    if( !in_progress && result < 0.33f ) {
        return 0.0f;
    }
    // If we're working below 10% speed, just give up
    if( result < 0.1f ) {
        return 0.0f;
    }
    return result;
}
References lighting_crafting_speed_multiplier(), and morale_crafting_speed_multiplier().
Referenced by activity_handlers::craft_do_turn(), draw_can_craft_indicator(), and player::expected_time_to_craft().
destroy_random_component()
static void destroy_random_component (item & craft, const player & crafter) static
Definition at line 914 of file crafting.cpp.
{
    if( craft.components.empty() ) {
        debugmsg( "destroy_random_component() called on craft with no components!  Aborting" );
        return;
    }
    item destroyed = random_entry_removed( craft.components );
    crafter.add_msg_player_or_npc( _( "You mess up and destroy the %s." ),
                                   _( "<npcname> messes up and destroys the %s" ), destroyed.tname() );
}
References _, player::add_msg_player_or_npc(), iuse::craft(), debugmsg, destroyed, and random_entry_removed().
Referenced by item::handle_craft_failure().
drop_or_handle()
static void drop_or_handle (const item & newit, Character & who) static
Definition at line 1478 of file crafting.cpp.
{
    if( newit.made_of( LIQUID ) && who.is_avatar() ) {
        // TODO: what about NPCs?
        liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
    } else {
        item tmp( newit );
        who.as_player()->i_add_or_drop( tmp );
    }
}
References Creature::as_player(), liquid_handler::handle_all_liquid(), Character::i_add_or_drop(), Creature::is_avatar(), LIQUID, item::made_of(), and PICKUP_RANGE.
Referenced by empty_buckets(), and remove_ammo().
empty_buckets()
static void empty_buckets (player & p) static
Definition at line 1491 of file crafting.cpp.
{
    // First grab (remove) all items that are non-empty buckets and not wielded
    auto buckets = p.remove_items_with( [&p]( const item & it ) {
        return it.is_bucket_nonempty() && &it != &p.weapon;
    }, INT_MAX );
    for( auto &it : buckets ) {
        for( const item *in : it.contents.all_items_top() ) {
            drop_or_handle( *in, p );
        }
        it.contents.clear_items();
        drop_or_handle( it, p );
    }
}
References item_contents::all_items_top(), item_contents::clear_items(), item::contents, drop_or_handle(), item::is_bucket_nonempty(), visitable< T >::remove_items_with(), and Character::weapon.
Referenced by player::consume_items().
find_best_bench()
bench_location find_best_bench (const player & p, const item & craft)
Definition at line 2358 of file crafting.cpp.
{
    bool can_lift = p.can_wield( craft ).success() && p.weight_capacity() >= craft.weight();
    std::pair<bench_type, float> bench_here = best_bench_here( craft, p.pos(), can_lift );
    bench_type best_type = bench_here.first;
    float best_bench_multi = bench_here.second;
    tripoint best_loc = p.pos();
    std::vector<tripoint> reachable( PICKUP_RANGE * PICKUP_RANGE );
    g->m.reachable_flood_steps( reachable, p.pos(), PICKUP_RANGE, 1, 100 );
    for( const tripoint &adj : reachable ) {
        if( const cata::value_ptr<furn_workbench_info> &wb = g->m.furn( adj ).obj().workbench ) {
            if( wb->multiplier > best_bench_multi ) {
                best_type = bench_type::furniture;
                best_bench_multi = wb->multiplier;
                best_loc = adj;
            }
        }
        if( const cata::optional<vpart_reference> vp = g->m.veh_at(
                    adj ).part_with_feature( "WORKBENCH", true ) ) {
            if( const cata::optional<vpslot_workbench> &wb_info = vp->part().info().get_workbench_info() ) {
                if( wb_info->multiplier > best_bench_multi ) {
                    best_type = bench_type::vehicle;
                    best_bench_multi = wb_info->multiplier;
                    best_loc = adj;
                }
            } else {
                debugmsg( "part '%S' with WORKBENCH flag has no workbench info", vp->part().name() );
            }
        }
    }
    return bench_location{best_type, best_loc};
}
References best_bench_here(), player::can_wield(), iuse::craft(), debugmsg, furniture, g, PICKUP_RANGE, Character::pos(), vehicle, and Character::weight_capacity().
Referenced by iuse::craft(), and player::start_craft().
flag_BLIND_EASY()
static const std::string flag_BLIND_EASY ("BLIND_EASY") static
Referenced by lighting_crafting_speed_multiplier().
flag_BLIND_HARD()
static const std::string flag_BLIND_HARD ("BLIND_HARD") static
Referenced by lighting_crafting_speed_multiplier().
flag_BYPRODUCT()
static const std::string flag_BYPRODUCT ("BYPRODUCT") static
Referenced by complete_craft().
flag_COOKED()
static const std::string flag_COOKED ("COOKED") static
Referenced by complete_craft().
flag_ETHEREAL_ITEM()
static const std::string flag_ETHEREAL_ITEM ("ETHEREAL_ITEM") static
Referenced by crafting::can_disassemble().
flag_FIT()
static const std::string flag_FIT ("FIT") static
Referenced by crafting::complete_disassemble(), and item::inherit_flags().
flag_FIX_FARSIGHT()
static const std::string flag_FIX_FARSIGHT ("FIX_FARSIGHT") static
Referenced by player::crafting_success_roll().
flag_FULL_MAGAZINE()
static const std::string flag_FULL_MAGAZINE ("FULL_MAGAZINE") static
Referenced by crafting::complete_disassemble().
flag_HIDDEN_POISON()
static const std::string flag_HIDDEN_POISON ("HIDDEN_POISON") static
Referenced by item::inherit_flags().
flag_NO_RESIZE()
static const std::string flag_NO_RESIZE ("NO_RESIZE") static
Referenced by item::inherit_flags().
flag_NO_UNLOAD()
static const std::string flag_NO_UNLOAD ("NO_UNLOAD") static
Referenced by remove_ammo().
flag_NUTRIENT_OVERRIDE()
static const std::string flag_NUTRIENT_OVERRIDE ("NUTRIENT_OVERRIDE") static
Referenced by complete_craft().
flag_UNCRAFT_LIQUIDS_CONTAINED()
static const std::string flag_UNCRAFT_LIQUIDS_CONTAINED ("UNCRAFT_LIQUIDS_CONTAINED") static
Referenced by crafting::complete_disassemble().
flag_VARSIZE()
static const std::string flag_VARSIZE ("VARSIZE") static
Referenced by crafting::complete_disassemble(), and item::inherit_flags().
is_container_eligible_for_crafting()
static bool is_container_eligible_for_crafting (const item & cont, bool allow_bucket) static
Definition at line 473 of file crafting.cpp.
{
    if( cont.is_watertight_container() || ( allow_bucket && cont.is_bucket() ) ) {
        return !cont.is_container_full( allow_bucket );
    }
    return false;
}
References item::is_bucket(), item::is_container_full(), and item::is_watertight_container().
Referenced by player::get_eligible_containers_for_crafting().
lerped_multiplier()
template<typename T > static float lerped_multiplier (const T & value, const T & low, const T & high) static
Definition at line 186 of file crafting.cpp.
{
    // No effect if less than allowed value
    if( value < low ) {
        return 1.0f;
    }
    // Bottom out at 25% speed
    if( value > high ) {
        return 0.25f;
    }
    // Linear interpolation between high and low
    // y = y0 + ( x - x0 ) * ( y1 - y0 ) / ( x1 - x0 )
    return 1.0f + ( value - low ) * ( 0.25f - 1.0f ) / ( high - low );
}
References high.
Referenced by workbench_crafting_speed_multiplier().
lighting_crafting_speed_multiplier()
float lighting_crafting_speed_multiplier (const Character & who, const recipe & rec)
Definition at line 131 of file crafting.cpp.
{
    if( character_funcs::can_see_fine_details( who ) ) {
        return 1.0f;
    }
    const SkillLevelMap &char_skills = who.get_all_skills();
    int skill_bonus = char_skills.exceeds_recipe_requirements( rec );
    // This value whould be within [0,1]
    const float darkness =
        (
            character_funcs::fine_detail_vision_mod( who ) -
            character_funcs::FINE_VISION_THRESHOLD
        ) / 7.0f;
    if( rec.has_flag( flag_BLIND_EASY ) ) {
        // 100% speed in well lit area at skill+0
        // 25% speed in pitch black at skill+0
        // skill+2 removes speed penalty
        return 1.0f - darkness * 0.75f * std::max( 0, 2 - skill_bonus ) / 2.0f;
    } else if( rec.has_flag( flag_BLIND_HARD ) && skill_bonus >= 2 ) {
        // 100% speed in well lit area at skill+2
        // 25% speed in pitch black at skill+2
        // skill+8 removes speed penalty
        return 1.0f - darkness * 0.75f * std::max( 0, 8 - skill_bonus ) / 6.0f;
    } else {
        // Needs proper vision or the character is not skilled enough
        return 0.0f;
    }
}
References character_funcs::can_see_fine_details(), SkillLevelMap::exceeds_recipe_requirements(), character_funcs::fine_detail_vision_mod(), character_funcs::FINE_VISION_THRESHOLD, flag_BLIND_EASY(), flag_BLIND_HARD(), Character::get_all_skills(), and recipe::has_flag().
Referenced by crafting::can_disassemble(), craft_progress_message(), crafting_allowed(), crafting_speed_multiplier(), and draw_can_craft_indicator().
morale_crafting_speed_multiplier()
float morale_crafting_speed_multiplier (const Character & who, const recipe & rec)
Definition at line 163 of file crafting.cpp.
{
    int morale = who.get_morale_level();
    if( morale >= 0 ) {
        // No bonus for being happy yet
        return 1.0f;
    }
    // Harder jobs are more frustrating, even when skilled
    // For each skill where skill=difficulty, multiply effective morale by 200%
    float morale_mult = std::max( 1.0f, 2.0f * rec.difficulty / std::max( 1,
                                  who.get_skill_level( rec.skill_used ) ) );
    for( const std::pair<const skill_id, int> &pr : rec.required_skills ) {
        morale_mult *= std::max( 1.0f, 2.0f * pr.second / std::max( 1, who.get_skill_level( pr.first ) ) );
    }
    // Halve speed at -50 effective morale, quarter at -150
    float morale_effect = 1.0f + ( morale_mult * morale ) / -50.0f;
    return 1.0f / morale_effect;
}
References recipe::difficulty, Character::get_morale_level(), Character::get_skill_level(), spell_effect::morale(), recipe::required_skills, and recipe::skill_used.
Referenced by craft_progress_message(), crafting_allowed(), and crafting_speed_multiplier().
prompt_disassemble_in_seq()
static disass_prompt_result prompt_disassemble_in_seq (avatar & you, const item & obj, bool interactive, bool autoselect_max) static
Definition at line 1952 of file crafting.cpp.
{
    disass_prompt_result res;
    const ret_val<bool> can_do = crafting::can_disassemble( you, obj, you.crafting_inventory() );
    if( !can_do.success() ) {
        if( interactive ) {
            you.add_msg_if_player( m_info, "%s", can_do.c_str() );
        }
        return res;
    }
    const recipe &r = recipe_dictionary::get_uncraft( obj.typeId() );
    res.r = &r;
    if( !obj.is_owned_by( you, true ) ) {
        if( !query_yn( _( "Disassembling the %s may anger the people who own it, continue?" ),
                       obj.tname() ) ) {
            return res;
        } else {
            if( obj.get_owner() ) {
                std::vector<npc *> witnesses;
                for( npc &elem : g->all_npcs() ) {
                    if( rl_dist( elem.pos(), you.pos() ) < MAX_VIEW_DISTANCE && elem.get_faction() &&
                        obj.is_owned_by( elem ) && elem.sees( you.pos() ) ) {
                        elem.say( "<witnessed_thievery>", 7 );
                        npc *npc_to_add = &elem;
                        witnesses.push_back( npc_to_add );
                    }
                }
                if( !witnesses.empty() ) {
                    if( you.add_faction_warning( obj.get_owner() ) ) {
                        for( npc *elem : witnesses ) {
                            elem->make_angry();
                        }
                    }
                }
            }
        }
    }
    int batch_size = r.disassembly_batch_size();
    if( interactive && get_option<bool>( "QUERY_DISASSEMBLE" ) ) {
        std::string msg;
        msg += string_format( _( "Disassembling the %s may yield:\n" ),
                              colorize( obj.tname(), obj.color_in_inventory() ) );
        const std::vector<item_comp> components = obj.get_uncraft_components();
        for( const item_comp &component : components ) {
            msg += "- " + component.to_string() + "\n";
        }
        if( batch_size != 1 ) {
            msg += string_format( _( "(per batch of %d)\n" ), batch_size );
        }
        msg += "\n";
        msg += _( "Really disassemble?\n" );
        if( !query_yn( msg ) ) {
            add_msg( _( "Never mind." ) );
            return res;
        }
    }
    if( obj.count_by_charges() ) {
        int num_batches = obj.charges / batch_size;
        if( num_batches == 0 ) {
            // Not enough charges for even one disassembly
            return res;
        } else if( num_batches == 1 || autoselect_max ) {
            // Skip prompt if can only do 1, or if we're doing all
            res.batches = num_batches;
        } else {
            string_input_popup popup_input;
            std::string title;
            std::string descr;
            if( batch_size != 1 ) {
                descr = string_format( _( "Disassembly will be done in batches of %d." ), batch_size );
                title = string_format(
                            _( "Disassemble how many batches of %s [MAX: %d]: " ),
                            obj.type_name( 1 ), num_batches );
            } else {
                title = string_format( _( "Disassemble how many %s [MAX: %d]: " ),
                                       obj.type_name( 1 ), num_batches );
            }
            int result = num_batches;
            popup_input.title( title ).description( descr ).edit( result );
            if( popup_input.canceled() || result <= 0 ) {
                add_msg( _( "Never mind." ) );
                return res;
            }
            res.batches = std::min( result, num_batches );
        }
    }
    res.success = true;
    return res;
}
References _, player::add_faction_warning(), add_msg(), player::add_msg_if_player(), disass_prompt_result::batches, ret_val< T >::c_str(), crafting::can_disassemble(), string_input_popup::canceled(), colorize(), Character::crafting_inventory(), string_input_popup::description(), recipe::disassembly_batch_size(), string_input_popup::edit(), g, recipe_dictionary::get_uncraft(), m_info, npc::make_angry(), MAX_VIEW_DISTANCE, int_id< T >::obj(), Character::pos(), query_yn(), disass_prompt_result::r, rl_dist(), string_format(), disass_prompt_result::success, ret_val< T >::success(), string_input_popup::title(), and PATH_INFO::title().
Referenced by crafting::disassemble_all(), and prompt_disassemble_single().
prompt_disassemble_single()
static bool prompt_disassemble_single (avatar & you, item_location target, bool interactive) static
Definition at line 2050 of file crafting.cpp.
{
    if( !target ) {
        add_msg( _( "Never mind." ) );
        return false;
    }
    disass_prompt_result res = prompt_disassemble_in_seq( you, *target, interactive, false );
    if( !res.success ) {
        return false;
    }
    iuse_location loc;
    loc.loc = target;
    loc.count = res.batches ? *res.batches : 1;
    tripoint_abs_ms pos_abs( get_map().getabs( you.pos() ) );
    you.assign_activity( disassemble_activity_actor( {{ loc }}, pos_abs, false ) );
    return true;
}
References _, add_msg(), Character::assign_activity(), disass_prompt_result::batches, iuse_location::count, get_map(), iuse_location::loc, Character::pos(), prompt_disassemble_in_seq(), and disass_prompt_result::success.
Referenced by crafting::disassemble().
remove_ammo() [1/2]
void remove_ammo (item & dis_item, Character & who)
Removes any (removable) ammo and stores it in character's inventory.
Definition at line 2278 of file crafting.cpp.
{
    dis_item.remove_items_with( [&who]( const item & it ) {
        if( it.is_irremovable() ) {
            return false;
        }
        drop_or_handle( it, who );
        return true;
    } );
    if( dis_item.has_flag( flag_NO_UNLOAD ) ) {
        return;
    }
    if( dis_item.is_gun() && !dis_item.ammo_current().is_null() ) {
        item ammodrop( dis_item.ammo_current(), calendar::turn );
        ammodrop.charges = dis_item.charges;
        drop_or_handle( ammodrop, who );
        dis_item.charges = 0;
    }
    if( dis_item.is_tool() && dis_item.charges > 0 && !dis_item.ammo_current().is_null() ) {
        item ammodrop( dis_item.ammo_current(), calendar::turn );
        ammodrop.charges = dis_item.charges;
        if( dis_item.ammo_current() == itype_plut_cell ) {
            ammodrop.charges /= PLUTONIUM_CHARGES;
        }
        drop_or_handle( ammodrop, who );
        dis_item.charges = 0;
    }
}
References item::ammo_current(), item::charges, drop_or_handle(), flag_NO_UNLOAD(), item::has_flag(), item::is_gun(), item::is_irremovable(), string_id< T >::is_null(), item::is_tool(), itype_plut_cell, PLUTONIUM_CHARGES, visitable< T >::remove_items_with(), and calendar::turn.
remove_ammo() [2/2]
void remove_ammo (std::list< item > & dis_items, Character & who)
Removes any (removable) ammo from each item and stores it in character's inventory.
Definition at line 2271 of file crafting.cpp.
{
    for( auto &dis_item : dis_items ) {
        remove_ammo( dis_item, who );
    }
}
References remove_ammo().
Referenced by crafting::complete_disassemble(), player::consume_items(), salvage_actor::cut_up(), and remove_ammo().
set_components()
static void set_components (std::list< item > & components, const std::list< item > & used, const int batch_size, const size_t offset) static
Definition at line 626 of file crafting.cpp.
{
    if( batch_size <= 1 ) {
        components.insert( components.begin(), used.begin(), used.end() );
        return;
    }
    // This count does *not* include items counted by charges!
    size_t non_charges_counter = 0;
    for( auto &tmp : used ) {
        if( tmp.count_by_charges() ) {
            components.push_back( tmp );
            // This assumes all (count-by-charges) items of the same type have been merged into one,
            // which has a charges value that can be evenly divided by batch_size.
            components.back().charges = tmp.charges / batch_size;
        } else {
            if( ( non_charges_counter + offset ) % batch_size == 0 ) {
                components.push_back( tmp );
            }
            non_charges_counter++;
        }
    }
}
Referenced by complete_craft().
set_item_inventory()
static item_location set_item_inventory (player & p, item & newit) static
Definition at line 712 of file crafting.cpp.
{
    p.inv.assign_empty_invlet( newit, p );
    // We might not have space for the item
    if( p.can_pick_volume( newit ) &&
        p.can_pick_weight( newit, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
        item &item_in_inv = p.i_add( newit );
        add_msg( m_info, "%c - %s", item_in_inv.invlet == 0 ? ' ' : item_in_inv.invlet,
                 item_in_inv.tname() );
        return item_location( p, &item_in_inv );
    }
    return set_item_map_or_vehicle( p, p.pos(), newit );
}
References add_msg(), inventory::assign_empty_invlet(), Character::can_pick_volume(), Character::can_pick_weight(), Character::i_add(), Character::inv, item::invlet, m_info, Character::pos(), set_item_map_or_vehicle(), and item::tname().
Referenced by complete_craft(), and player::start_craft().
set_item_map()
static item_location set_item_map (const tripoint & loc, item & newit) static
Helper for set_item_map_or_vehicle This is needed to still get a vaild item_location if overflow occurs.
Definition at line 654 of file crafting.cpp.
{
    // Includes loc
    for( const tripoint &tile : closest_points_first( loc, 2 ) ) {
        // Pass false to disallow overflow, null_item_reference indicates failure.
        item *it_on_map = &get_map().add_item_or_charges( tile, newit, false );
        if( it_on_map != &null_item_reference() ) {
            return item_location( map_cursor( tile ), it_on_map );
        }
    }
    debugmsg( "Could not place %s on map near (%d, %d, %d)", newit.tname(), loc.x, loc.y, loc.z );
    return item_location();
}
References map::add_item_or_charges(), closest_points_first(), debugmsg, get_map(), null_item_reference(), item::tname(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by set_item_map_or_vehicle().
set_item_map_or_vehicle()
static item_location set_item_map_or_vehicle (const player & p, const tripoint & loc, item & newit) static
Set an item on the map or in a vehicle and return the new location.
Definition at line 671 of file crafting.cpp.
{
    map &here = get_map();
    if( const cata::optional<vpart_reference> vp = here.veh_at( loc ).part_with_feature( "CARGO",
            false ) ) {
        if( const cata::optional<vehicle_stack::iterator> it = vp->vehicle().add_item( vp->part_index(),
                newit ) ) {
            p.add_msg_player_or_npc(
                pgettext( "item, furniture", "You put the %1$s on the %2$s." ),
                pgettext( "item, furniture", "<npcname> puts the %1$s on the %2$s." ),
                ( *it )->tname(), vp->part().name() );
            return item_location( vehicle_cursor( vp->vehicle(), vp->part_index() ), & **it );
        }
        // Couldn't add the in progress craft to the target part, so drop it to the map.
        p.add_msg_player_or_npc(
            pgettext( "furniture, item", "Not enough space on the %s. You drop the %s on the ground." ),
            pgettext( "furniture, item", "Not enough space on the %s. <npcname> drops the %s on the ground." ),
            vp->part().name(), newit.tname() );
        return set_item_map( loc, newit );
    } else {
        if( here.has_furn( loc ) ) {
            const furn_t &workbench = here.furn( loc ).obj();
            p.add_msg_player_or_npc(
                pgettext( "item, furniture", "You put the %1$s on the %2$s." ),
                pgettext( "item, furniture", "<npcname> puts the %1$s on the %2$s." ),
                newit.tname(), workbench.name() );
        } else {
            p.add_msg_player_or_npc(
                pgettext( "item", "You put the %s on the ground." ),
                pgettext( "item", "<npcname> puts the %s on the ground." ),
                newit.tname() );
        }
        return set_item_map( loc, newit );
    }
}
References player::add_msg_player_or_npc(), map::furn(), get_map(), map::has_furn(), int_id< T >::obj(), optional_vpart_position::part_with_feature(), pgettext(), set_item_map(), item::tname(), map::veh_at(), and iexamine::workbench().
Referenced by set_item_inventory().
workbench_crafting_speed_multiplier()
float workbench_crafting_speed_multiplier (const item & craft, const bench_location & bench)
Definition at line 201 of file crafting.cpp.
{
    float multiplier = 0.0f;
    units::mass allowed_mass;
    units::volume allowed_volume;
    const units::mass &craft_mass = craft.weight();
    const units::volume &craft_volume = craft.volume();
    // The whole block below is so ugly because all the benches have different structs with same content
    map &here = get_map();
    switch( bench.type ) {
        case bench_type::hands: {
            const furn_t &f = string_id<furn_t>( "f_fake_bench_hands" ).obj();
            multiplier = f.workbench->multiplier;
            allowed_mass = f.workbench->allowed_mass;
            allowed_volume = f.workbench->allowed_volume;
        }
        break;
        case bench_type::ground: {
            // Ground - we can always use this, but it's bad
            const furn_t &f = string_id<furn_t>( "f_ground_crafting_spot" ).obj();
            multiplier = f.workbench->multiplier;
            allowed_mass = f.workbench->allowed_mass;
            allowed_volume = f.workbench->allowed_volume;
        }
        break;
        case bench_type::furniture:
            if( here.furn( bench.position ).obj().workbench ) {
                // Furniture workbench
                const furn_t &f = here.furn( bench.position ).obj();
                multiplier = f.workbench->multiplier;
                allowed_mass = f.workbench->allowed_mass;
                allowed_volume = f.workbench->allowed_volume;
            } else {
                return 0.0f;
            }
            break;
        case bench_type::vehicle:
            if( const cata::optional<vpart_reference> vp = here.veh_at(
                        bench.position ).part_with_feature( "WORKBENCH", true ) ) {
                // Vehicle workbench
                const vpart_info &vp_info = vp->part().info();
                if( const cata::optional<vpslot_workbench> &wb_info = vp_info.get_workbench_info() ) {
                    multiplier = wb_info->multiplier;
                    allowed_mass = wb_info->allowed_mass;
                    allowed_volume = wb_info->allowed_volume;
                } else {
                    debugmsg( "part '%S' with WORKBENCH flag has no workbench info", vp->part().name() );
                    return 0.0f;
                }
            }
            break;
        default:
            debugmsg( "Invalid workbench type %d", static_cast<int>( bench.type ) );
            return 0.0f;
    }
    multiplier *= lerped_multiplier( craft_mass, allowed_mass, 1000_kilogram );
    multiplier *= lerped_multiplier( craft_volume, allowed_volume, 1000_liter );
    return multiplier;
}
References iuse::craft(), debugmsg, map::furn(), furniture, get_map(), vpart_info::get_workbench_info(), ground, hands, lerped_multiplier(), int_id< T >::obj(), string_id< T >::obj(), optional_vpart_position::part_with_feature(), bench_location::position, bench_location::type, map::veh_at(), vehicle, and furn_t::workbench.
Referenced by best_bench_here(), craft_progress_message(), and crafting_speed_multiplier().
Variable Documentation
ACT_CRAFT
const activity_id ACT_CRAFT("ACT_CRAFT") ("ACT_CRAFT") static
Referenced by player::start_craft().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by player::crafting_success_roll().
itype_plut_cell
const itype_id itype_plut_cell("plut_cell") ("plut_cell") static
Referenced by remove_ammo().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by player::crafting_success_roll().
skill_tailor
const skill_id skill_tailor("tailor") ("tailor") static
Referenced by player::crafting_success_roll().
trait_BURROW
const trait_id trait_BURROW("BURROW") ("BURROW") static
Referenced by Character::crafting_inventory().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by player::can_continue_craft(), player::consume_items(), player::consume_tools(), player::craft_consume_tools(), and player::select_item_component().
trait_HYPEROPIC
const trait_id trait_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by player::crafting_success_roll().