Cataclysm BN: src/cuboid_rectangle.h File Reference
cuboid_rectangle.h File Reference
#include "cata_utility.h"
#include "point.h"
#include "point_traits.h"
Classes
struct rectangle< Point, >
struct half_open_rectangle< Point, >
struct inclusive_rectangle< Point, >
struct cuboid< Tripoint, >
struct half_open_cuboid< Tripoint, >
struct inclusive_cuboid< Tripoint, >
Functions
template<typename Point >
Point clamp (const Point &p, const half_open_rectangle< Point > &r)
template<typename Point >
Point clamp (const Point &p, const inclusive_rectangle< Point > &r)
template<typename Tripoint >
Tripoint clamp (const Tripoint &p, const half_open_cuboid< Tripoint > &c)
template<typename Tripoint >
Tripoint clamp (const Tripoint &p, const inclusive_cuboid< Tripoint > &c)
static constexpr rectangle< point > rectangle_zero (point_zero, point_zero)
static constexpr cuboid< tripoint > cuboid_zero (tripoint_zero, tripoint_zero)
Function Documentation
clamp() [1/4]
template<typename Point > Point clamp (const Point & p, const half_open_rectangle< Point > & r)
Definition at line 124 of file cuboid_rectangle.h.
{
    using Traits = point_traits<Point>;
    return Point( ::clamp( Traits::x( p ), Traits::x( r.p_min ), Traits::x( r.p_max ) - 1 ),
                  ::clamp( Traits::y( p ), Traits::y( r.p_min ), Traits::y( r.p_max ) - 1 ) );
}
References clamp(), half_open_rectangle< Point, >::p_max, and half_open_rectangle< Point, >::p_min.
Referenced by clamp().
clamp() [2/4]
template<typename Point > Point clamp (const Point & p, const inclusive_rectangle< Point > & r)
Definition at line 132 of file cuboid_rectangle.h.
{
    using Traits = point_traits<Point>;
    return Point( ::clamp( Traits::x( p ), Traits::x( r.p_min ), Traits::x( r.p_max ) ),
                  ::clamp( Traits::y( p ), Traits::y( r.p_min ), Traits::y( r.p_max ) ) );
}
References clamp(), inclusive_rectangle< Point, >::p_max, and inclusive_rectangle< Point, >::p_min.
clamp() [3/4]
template<typename Tripoint > Tripoint clamp (const Tripoint & p, const half_open_cuboid< Tripoint > & c)
Definition at line 140 of file cuboid_rectangle.h.
{
    using Traits = point_traits<Tripoint>;
    return Tripoint( ::clamp( Traits::x( p ), Traits::x( c.p_min ), Traits::x( c.p_max ) - 1 ),
                     ::clamp( Traits::y( p ), Traits::y( c.p_min ), Traits::y( c.p_max ) - 1 ),
                     ::clamp( Traits::z( p ), Traits::z( c.p_min ), Traits::z( c.p_max ) - 1 ) );
}
References c, and clamp().
clamp() [4/4]
template<typename Tripoint > Tripoint clamp (const Tripoint & p, const inclusive_cuboid< Tripoint > & c)
Definition at line 149 of file cuboid_rectangle.h.
{
    using Traits = point_traits<Tripoint>;
    return Tripoint( ::clamp( Traits::x( p ), Traits::x( c.p_min ), Traits::x( c.p_max ) ),
                     ::clamp( Traits::y( p ), Traits::y( c.p_min ), Traits::y( c.p_max ) ),
                     ::clamp( Traits::z( p ), Traits::z( c.p_min ), Traits::z( c.p_max ) ) );
}
References c, and clamp().
cuboid_zero()
static constexpr cuboid< tripoint > cuboid_zero (tripoint_zero , tripoint_zero) static constexpr
rectangle_zero()
static constexpr rectangle< point > rectangle_zero (point_zero , point_zero) static constexpr