Cataclysm BN: src/damage.h File Reference
damage.h File Reference
#include <array>
#include <map>
#include <vector>
#include <string>
#include "type_id.h"
Classes
struct damage_unit
struct damage_instance
struct dealt_damage_instance
struct resistances
Macros
#define CATA_SRC_DAMAGE_H
Enumerations
enum damage_type : int {
DT_NULL = 0 , DT_TRUE , DT_BIOLOGICAL , DT_BASH ,
DT_CUT , DT_ACID , DT_STAB , DT_HEAT ,
DT_COLD , DT_ELECTRIC , DT_BULLET , NUM_DT
}
Functions
const std::map< std::string, damage_type > & get_dt_map ()
damage_type dt_by_name (const std::string &name)
std::string name_by_dt (const damage_type &dt)
const skill_id & skill_by_dt (damage_type dt)
damage_instance load_damage_instance (const JsonObject &jo)
damage_instance load_damage_instance (const JsonArray &jarr)
damage_instance load_damage_instance_inherit (const JsonObject &jo, const damage_instance &parent)
damage_instance load_damage_instance_inherit (const JsonArray &jarr, const damage_instance &parent)
resistances load_resistances_instance (const JsonObject &jo)
std::array< float, NUM_DT > load_damage_array (const JsonObject &jo)
Macro Definition Documentation
CATA_SRC_DAMAGE_H
#define CATA_SRC_DAMAGE_H
Definition at line 3 of file damage.h.
Enumeration Type Documentation
damage_type
enum damage_type : int
Enumerator
DT_NULL
DT_TRUE
DT_BIOLOGICAL
DT_BASH
DT_CUT
DT_ACID
DT_STAB
DT_HEAT
DT_COLD
DT_ELECTRIC
DT_BULLET
NUM_DT
Definition at line 20 of file damage.h.
                 : int {
    DT_NULL = 0, // null damage, doesn't exist
    DT_TRUE, // typeless damage, should always go through
    DT_BIOLOGICAL, // internal damage, like from smoke or poison
    DT_BASH, // bash damage
    DT_CUT, // cut damage
    DT_ACID, // corrosive damage, e.g. acid
    DT_STAB, // stabbing/piercing damage
    DT_HEAT, // e.g. fire, plasma
    DT_COLD, // e.g. heatdrain, cryogrenades
    DT_ELECTRIC, // e.g. electrical discharge
    DT_BULLET, // bullets and other fast moving projectiles
    NUM_DT
};
Function Documentation
dt_by_name()
damage_type dt_by_name (const std::string & name)
Definition at line 250 of file damage.cpp.
{
    const auto &iter = dt_map.find( name );
    if( iter == dt_map.end() ) {
        return DT_NULL;
    }
    return iter->second;
}
References dt_map, DT_NULL, and om_direction::name().
Referenced by bonus_container::load(), and load_damage_unit().
get_dt_map()
const std::map< std::string, damage_type > & get_dt_map ()
Definition at line 245 of file damage.cpp.
{
    return dt_map;
}
References dt_map.
Referenced by ma_weapon_damage_reader::erase_next(), and ma_weapon_damage_reader::get_next().
load_damage_array()
std::array< float, NUM_DT > load_damage_array (const JsonObject & jo)
Definition at line 391 of file damage.cpp.
{
    std::array<float, NUM_DT> ret;
    float init_val = jo.get_float( "all", 0.0f );
    float phys = jo.get_float( "physical", init_val );
    ret[ DT_BASH ] = jo.get_float( "bash", phys );
    ret[ DT_CUT ] = jo.get_float( "cut", phys );
    ret[ DT_STAB ] = jo.get_float( "stab", phys );
    ret[ DT_BULLET ] = jo.get_float( "bullet", phys );
    float non_phys = jo.get_float( "non_physical", init_val );
    ret[ DT_BIOLOGICAL ] = jo.get_float( "biological", non_phys );
    ret[ DT_ACID ] = jo.get_float( "acid", non_phys );
    ret[ DT_HEAT ] = jo.get_float( "heat", non_phys );
    ret[ DT_COLD ] = jo.get_float( "cold", non_phys );
    ret[ DT_ELECTRIC ] = jo.get_float( "electric", non_phys );
    // DT_TRUE should never be resisted
    ret[ DT_TRUE ] = 0.0f;
    return ret;
}
References DT_ACID, DT_BASH, DT_BIOLOGICAL, DT_BULLET, DT_COLD, DT_CUT, DT_ELECTRIC, DT_HEAT, DT_STAB, DT_TRUE, JsonObject::get_float(), and cata::hash64_detail::ret.
Referenced by vpart_info::load(), and load_resistances_instance().
load_damage_instance() [1/2]
damage_instance load_damage_instance (const JsonArray & jarr)
Definition at line 361 of file damage.cpp.
{
    return load_damage_instance_inherit( jarr, blank_damage_instance() );
}
References blank_damage_instance(), and load_damage_instance_inherit().
load_damage_instance() [2/2]
damage_instance load_damage_instance (const JsonObject & jo)
Definition at line 356 of file damage.cpp.
{
    return load_damage_instance_inherit( jo, blank_damage_instance() );
}
References blank_damage_instance(), and load_damage_instance_inherit().
Referenced by assign(), damage_instance::deserialize(), mtype::load(), Item_factory::load_basic_info(), melee_actor::load_internal(), and load_mutation_attack().
load_damage_instance_inherit() [1/2]
damage_instance load_damage_instance_inherit (const JsonArray & jarr, const damage_instance & parent)
Definition at line 381 of file damage.cpp.
{
    damage_instance di;
    for( const JsonObject curr : jarr ) {
        di.damage_units.push_back( load_damage_unit_inherit( curr, parent ) );
    }
    return di;
}
References damage_instance::damage_units, and load_damage_unit_inherit().
load_damage_instance_inherit() [2/2]
damage_instance load_damage_instance_inherit (const JsonObject & jo, const damage_instance & parent)
Definition at line 367 of file damage.cpp.
{
    damage_instance di;
    if( jo.has_array( "values" ) ) {
        for( const JsonObject curr : jo.get_array( "values" ) ) {
            di.damage_units.push_back( load_damage_unit_inherit( curr, parent ) );
        }
    } else if( jo.has_string( "damage_type" ) ) {
        di.damage_units.push_back( load_damage_unit_inherit( jo, parent ) );
    }
    return di;
}
References damage_instance::damage_units, JsonObject::get_array(), JsonObject::has_array(), JsonObject::has_string(), and load_damage_unit_inherit().
Referenced by assign(), and load_damage_instance().
load_resistances_instance()
resistances load_resistances_instance (const JsonObject & jo)
Definition at line 414 of file damage.cpp.
{
    resistances ret;
    ret.resist_vals = load_damage_array( jo );
    return ret;
}
References load_damage_array(), and cata::hash64_detail::ret.
Referenced by mutation_branch::load().
name_by_dt()
std::string name_by_dt (const damage_type & dt)
Definition at line 260 of file damage.cpp.
{
    auto iter = dt_map.cbegin();
    while( iter != dt_map.cend() ) {
        if( iter->second == dt ) {
            return pgettext( "damage type", iter->first.c_str() );
        }
        iter++;
    }
    static const std::string err_msg( "dt_not_found" );
    return err_msg;
}
References dt_map, and pgettext().
Referenced by monster::absorb_hit(), spell::damage_type_string(), bonus_container::get_description(), and print_damage_info().
skill_by_dt()
const skill_id & skill_by_dt (damage_type dt)
Definition at line 273 of file damage.cpp.
{
    static skill_id skill_bashing( "bashing" );
    static skill_id skill_cutting( "cutting" );
    static skill_id skill_stabbing( "stabbing" );
    switch( dt ) {
        case DT_BASH:
            return skill_bashing;
        case DT_CUT:
            return skill_cutting;
        case DT_STAB:
            return skill_stabbing;
        default:
            return skill_id::NULL_ID();
    }
}
References DT_BASH, DT_CUT, DT_STAB, string_id< Skill >::NULL_ID(), skill_bashing, skill_cutting, and skill_stabbing.
Referenced by item::melee_skill().