Cataclysm BN: src/descriptions.cpp File Reference
descriptions.cpp File Reference
#include "game.h"
#include <algorithm>
#include <sstream>
#include <type_traits>
#include <utility>
#include "avatar.h"
#include "calendar.h"
#include "color.h"
#include "harvest.h"
#include "input.h"
#include "map.h"
#include "mapdata.h"
#include "mod_manager.h"
#include "output.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_utils.h"
#include "translations.h"
#include "ui_manager.h"
#include "item_group.h"
#include "itype.h"
Enumerations
enum class description_target : int { creature , furniture , terrain }
Functions
static bool debug_vision ()
static const Creature * seen_critter (const game &g, const tripoint &p)
Variables
static const skill_id skill_survival ("survival")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_DEBUG_NIGHTVISION ("DEBUG_NIGHTVISION")
Enumeration Type Documentation
description_target
enum class description_target : int strong
Enumerator
creature
furniture
terrain
Definition at line 30 of file descriptions.cpp.
                              : int {
    creature,
    furniture,
    terrain
};
Function Documentation
debug_vision()
static bool debug_vision () static
Definition at line 36 of file descriptions.cpp.
{
    return debug_mode || get_player_character().has_trait( trait_DEBUG_NIGHTVISION );
}
References debug_mode, get_player_character(), Character::has_trait(), and trait_DEBUG_NIGHTVISION.
seen_critter()
static const Creature * seen_critter (const game & g, const tripoint & p) static
Definition at line 41 of file descriptions.cpp.
{
    const Creature *critter = g.critter_at( p, true );
    if( critter != nullptr && g.u.sees( *critter ) ) {
        return critter;
    }
    return nullptr;
}
References g.
Referenced by game::extended_description().
Variable Documentation
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by map_data_common_t::extended_description().
trait_DEBUG_NIGHTVISION
const trait_id trait_DEBUG_NIGHTVISION("DEBUG_NIGHTVISION") ("DEBUG_NIGHTVISION") static
Referenced by debug_vision().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by game::extended_description().