Cataclysm BN: src/dialogue_win.cpp File Reference
dialogue_win.cpp File Reference
#include "dialogue_win.h"
#include <algorithm>
#include <memory>
#include <string>
#include <vector>
#include "input.h"
#include "output.h"
#include "point.h"
#include "translations.h"
#include "ui_manager.h"
Classes
struct page_entry
struct page
Functions
static std::vector< page > split_to_pages (const std::vector< talk_data > &responses, int page_w, int page_h)
static void print_responses (const catacurses::window &w, const page &responses)
static void print_keybindings (const catacurses::window &w)
Function Documentation
print_keybindings()
static void print_keybindings (const catacurses::window & w) static
Definition at line 135 of file dialogue_win.cpp.
{
    // Responses go on the right side of the window, add 2 for border + space
    const size_t x = getmaxx( w ) / 2 + 2;
    const size_t y = getmaxy( w ) - 5;
    mvwprintz( w, point( x, y ), c_magenta, _( "Shift+L: Look at" ) );
    mvwprintz( w, point( x, y + 1 ), c_magenta, _( "Shift+S: Size up stats" ) );
    mvwprintz( w, point( x, y + 2 ), c_magenta, _( "Shift+Y: Yell" ) );
    mvwprintz( w, point( x, y + 3 ), c_magenta, _( "Shift+O: Check opinion" ) );
}
References _, c_magenta, catacurses::getmaxx(), catacurses::getmaxy(), and mvwprintz().
Referenced by dialogue_window::display_responses().
print_responses()
static void print_responses (const catacurses::window & w, const page & responses) static
Definition at line 118 of file dialogue_win.cpp.
{
    // Responses go on the right side of the window, add 2 for border + space
    const size_t x_start = getmaxx( w ) / 2 + 2;
    // First line we can print on, +1 for border, +2 for your name + newline
    const int y_start = 2 + 1;
    int curr_y = y_start;
    for( const page_entry &entry : responses.entries ) {
        const nc_color col = entry.col;
        for( const std::string &line : entry.lines ) {
            mvwprintz( w, point( x_start, curr_y ), col, line );
            curr_y += 1;
        }
    }
}
References page_entry::col, page::entries, catacurses::getmaxx(), line(), page_entry::lines, and mvwprintz().
Referenced by dialogue_window::display_responses().
split_to_pages()
static std::vector< page > split_to_pages (const std::vector< talk_data > & responses, int page_w, int page_h) static
Definition at line 84 of file dialogue_win.cpp.
{
    page this_page;
    std::vector<page> ret;
    int fold_width = page_w - 3;
    int this_h = 0;
    for( const talk_data &resp : responses ) {
        // Assemble single entry for printing
        const std::vector<std::string> folded = foldstring( resp.text, fold_width );
        page_entry this_entry;
        this_entry.col = resp.col;
        if( !folded.empty() ) {
            this_entry.lines.push_back( string_format( "%c: %s", resp.letter, folded[0] ) );
            for( size_t i = 1; i < folded.size(); i++ ) {
                this_entry.lines.push_back( string_format( "   %s", folded[i] ) );
            }
        }
        // Add entry to current / new page
        if( this_h + static_cast<int>( folded.size() ) > page_h ) {
            ret.push_back( this_page );
            this_page = page();
            this_h = 0;
        }
        this_h += this_entry.lines.size();
        this_page.entries.push_back( this_entry );
    }
    if( !this_page.entries.empty() ) {
        ret.push_back( this_page );
    }
    return ret;
}
References page_entry::col, page::entries, foldstring(), page_entry::lines, cata::hash64_detail::ret, and string_format().
Referenced by dialogue_window::display_responses().