Cataclysm BN: src/distraction_manager.cpp File Reference
distraction_manager.cpp File Reference
#include "distraction_manager.h"
#include <functional>
#include <fstream>
#include <string>
#include "cata_utility.h"
#include "color.h"
#include "cursesdef.h"
#include "input.h"
#include "json.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "fstream_utils.h"
Namespaces
namespace io
namespace distraction_manager
Functions
template<>
std::string io::enum_to_string< distraction_type > (distraction_type data)
distraction_manager::distraction_manager_gui & get_distraction_manager ()
Variables
static const std::map< distraction_type, std::pair< std::string, std::string > > distraction_manager::distraction_desc
Function Documentation
get_distraction_manager()
distraction_manager::distraction_manager_gui & get_distraction_manager ()
Definition at line 270 of file distraction_manager.cpp.
{
    static distraction_manager::distraction_manager_gui staticSettings;
    return staticSettings;
}
Referenced by game::cancel_activity_or_ignore_query(), game::handle_action(), player_activity::is_distraction_ignored(), game::load_static_data(), main_menu::opening_screen(), and game::start_game().