Cataclysm BN: src/distribution_grid.h File Reference
distribution_grid.h File Reference
#include <cstdint>
#include <vector>
#include <map>
#include <unordered_set>
#include "calendar.h"
#include "coordinates.h"
#include "cuboid_rectangle.h"
#include "memory_fast.h"
#include "point.h"
#include "type_id.h"
Classes
struct tile_location
class distribution_grid
A cache that organizes producers, storage and consumers of some resource, like electricity.
struct transform_queue_entry
class grid_furn_transform_queue
Represents queued active tile / furniture transformations.
class distribution_grid_tracker
Contains and manages all the active distribution grids.
Namespaces
namespace distribution_graph
Macros
#define CATA_SRC_DISTRIBUTION_GRID_H
Enumerations
enum class distribution_graph::traverse_visitor_result { distribution_graph::stop , distribution_graph::continue_further }
Functions
template<typename VehFunc , typename GridFunc , typename StartPoint >
void distribution_graph::traverse (StartPoint &start, VehFunc veh_action, GridFunc grid_action)
Traverses the graph of connected vehicles and grids.
constexpr traverse_visitor_result distribution_graph::noop_visitor_grid (const distribution_grid &)
constexpr traverse_visitor_result distribution_graph::noop_visitor_veh (const vehicle &)
distribution_grid_tracker & get_distribution_grid_tracker ()
Returns distribution grid tracker that is a part of the global game *g.
Macro Definition Documentation
CATA_SRC_DISTRIBUTION_GRID_H
#define CATA_SRC_DISTRIBUTION_GRID_H
Definition at line 3 of file distribution_grid.h.
Function Documentation
get_distribution_grid_tracker()
distribution_grid_tracker & get_distribution_grid_tracker ()
Returns distribution grid tracker that is a part of the global game *g.
game TODO: This wouldn't be required in an ideal world
Definition at line 12024 of file game.cpp.
{
    return *g->grid_tracker_ptr;
}
Referenced by overmapbuffer::add_grid_connection(), iexamine::check_power(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source(), inventory::form_from_map(), map::furn_set(), overmap_ui::grids_draw_data::get_active(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), overmapbuffer::remove_grid_connection(), iuse::report_grid_charge(), mapbuffer::save(), distribution_graph::traverse(), charge_watcher_tile::update_internal(), steady_consumer_tile::update_internal(), use_charges_from_furn(), and iexamine::use_furn_fake_item().