Cataclysm BN: src/drawing_primitives.h File Reference
drawing_primitives.h File Reference
#include <functional>
Macros
#define CATA_SRC_DRAWING_PRIMITIVES_H
Functions
void draw_line (std::function< void(const point &)>set, const point &p1, const point &p2)
void draw_square (std::function< void(const point &)>set, point p1, point p2)
void draw_rough_circle (std::function< void(const point &)>set, const point &p, int rad)
void draw_circle (std::function< void(const point &)>set, const rl_vec2d &p, double rad)
void draw_circle (std::function< void(const point &)>set, const point &p, int rad)
Macro Definition Documentation
CATA_SRC_DRAWING_PRIMITIVES_H
#define CATA_SRC_DRAWING_PRIMITIVES_H
Definition at line 3 of file drawing_primitives.h.
Function Documentation
draw_circle() [1/2]
void draw_circle (std::function< void(const point &)> set, const point & p, int rad)
Definition at line 58 of file drawing_primitives.cpp.
{
    for( int i = p.x - rad; i <= p.x + rad; i++ ) {
        for( int j = p.y - rad; j <= p.y + rad; j++ ) {
            if( trig_dist( p, point( i, j ) ) <= rad ) {
                set( point( i, j ) );
            }
        }
    }
}
References trig_dist(), point::x, and point::y.
draw_circle() [2/2]
void draw_circle (std::function< void(const point &)> set, const rl_vec2d & p, double rad)
Definition at line 47 of file drawing_primitives.cpp.
{
    for( int i = p.x - rad - 1; i <= p.x + rad + 1; i++ ) {
        for( int j = p.y - rad - 1; j <= p.y + rad + 1; j++ ) {
            if( ( p.x - i ) * ( p.x - i ) + ( p.y - j ) * ( p.y - j ) <= rad * rad ) {
                set( point( i, j ) );
            }
        }
    }
}
References rl_vec2d::x, and rl_vec2d::y.
Referenced by map::draw_circle_furn(), map::draw_circle_ter(), and map::draw_lab().
draw_line()
void draw_line (std::function< void(const point &)> set, const point & p1, const point & p2)
Definition at line 12 of file drawing_primitives.cpp.
{
    std::vector<point> line = line_to( p1, p2, 0 );
    for( auto &i : line ) {
        set( i );
    }
    set( p1 );
}
References line(), and line_to().
Referenced by map::draw_line_furn(), and map::draw_line_ter().
draw_rough_circle()
void draw_rough_circle (std::function< void(const point &)> set, const point & p, int rad)
Definition at line 36 of file drawing_primitives.cpp.
{
    for( int i = p.x - rad; i <= p.x + rad; i++ ) {
        for( int j = p.y - rad; j <= p.y + rad; j++ ) {
            if( trig_dist( p, point( i, j ) ) + rng( 0, 3 ) <= rad ) {
                set( point( i, j ) );
            }
        }
    }
}
References rng(), trig_dist(), point::x, and point::y.
Referenced by map::draw_lab(), map::draw_rough_circle_furn(), and map::draw_rough_circle_ter().
draw_square()
void draw_square (std::function< void(const point &)> set, point p1, point p2)
Definition at line 21 of file drawing_primitives.cpp.
{
    if( p1.x > p2.x ) {
        std::swap( p1.x, p2.x );
    }
    if( p1.y > p2.y ) {
        std::swap( p1.y, p2.y );
    }
    for( int x = p1.x; x <= p2.x; x++ ) {
        for( int y = p1.y; y <= p2.y; y++ ) {
            set( point( x, y ) );
        }
    }
}
References cata::swap(), point::x, and point::y.
Referenced by map::draw_square_furn(), and map::draw_square_ter().