Cataclysm BN: src/editmap.cpp File Reference
editmap.cpp File Reference
#include "editmap.h"
#include <cstdlib>
#include <cstring>
#include <exception>
#include <iosfwd>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <tuple>
#include <typeinfo>
#include <utility>
#include <vector>
#include "avatar.h"
#include "calendar.h"
#include "cata_utility.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "debug.h"
#include "debug_menu.h"
#include "field.h"
#include "field_type.h"
#include "fstream_utils.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "omdata.h"
#include "output.h"
#include "overmapbuffer.h"
#include "scent_map.h"
#include "shadowcasting.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "submap.h"
#include "tileray.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
class editmap::game_draw_callback_t_container
Enumerations
enum editmap_imenu_ent {
imenu_bday , imenu_damage , imenu_burnt , imenu_sep ,
imenu_savetest , imenu_exit
}
Functions
static constexpr tripoint editmap_boundary_min (0, 0, -OVERMAP_DEPTH)
static constexpr tripoint editmap_boundary_max (MAPSIZE_X, MAPSIZE_Y, OVERMAP_HEIGHT+1)
static constexpr half_open_cuboid< tripoint > editmap_boundaries (editmap_boundary_min, editmap_boundary_max)
static std::vector< std::string > fld_string (const std::string &str, int width)
template<class SAVEOBJ >
void edit_json (SAVEOBJ &it)
static ter_id get_alt_ter (bool isvert, ter_id sel_ter)
template<typename T_t >
static std::string info_title ()
template<>
std::string info_title< ter_t > ()
template<>
std::string info_title< furn_t > ()
template<>
std::string info_title< trap > ()
template<typename T_id >
static T_id feature (const tripoint &p)
template<>
ter_id feature< ter_id > (const tripoint &p)
template<>
furn_id feature< furn_id > (const tripoint &p)
template<>
trap_id feature< trap_id > (const tripoint &p)
template<typename T_t >
static int symbol (const T_t &t)
template<>
int symbol (const ter_t &t)
template<>
int symbol (const furn_t &t)
template<>
int symbol (const trap &t)
template<typename T_t >
static nc_color color (const T_t &t)
template<>
nc_color color (const ter_t &t)
template<>
nc_color color (const furn_t &t)
template<>
nc_color color (const trap &t)
template<typename T_t >
static std::string describe (const T_t &t)
template<>
std::string describe (const ter_t &type)
template<>
std::string describe (const furn_t &type)
template<>
std::string describe (const trap &type)
template<typename T_id >
static void draw_override (const tripoint &p, const T_id &id)
template<>
void draw_override< ter_id > (const tripoint &p, const ter_id &id)
template<>
void draw_override< furn_id > (const tripoint &p, const furn_id &id)
template<>
void draw_override< trap_id > (const tripoint &p, const trap_id &id)
template<typename T_t >
static void apply (const T_t &t, shapetype editshape, const tripoint &target, const tripoint &origin, const std::vector< tripoint > &target_list)
template<>
void apply< ter_t > (const ter_t &t, const shapetype editshape, const tripoint &target, const tripoint &origin, const std::vector< tripoint > &target_list)
template<>
void apply< furn_t > (const furn_t &t, const shapetype, const tripoint &, const tripoint &, const std::vector< tripoint > &target_list)
template<>
void apply< trap > (const trap &t, const shapetype, const tripoint &, const tripoint &, const std::vector< tripoint > &target_list)
static int limited_shift (int var, int &shift, int min, int max)
Variables
static const ter_id undefined_ter_id (-1)
Enumeration Type Documentation
editmap_imenu_ent
enum editmap_imenu_ent
Enumerator
imenu_bday
imenu_damage
imenu_burnt
imenu_sep
imenu_savetest
imenu_exit
Definition at line 1384 of file editmap.cpp.
                       {
    imenu_bday, imenu_damage, imenu_burnt,
    imenu_sep,
    imenu_savetest,
    imenu_exit,
};
Function Documentation
apply()
template<typename T_t > static void apply (const T_t & t, shapetype editshape, const tripoint & target, const tripoint & origin, const std::vector< tripoint > & target_list) static
Referenced by scrolling_text_view::draw(), editmap::edit_feature(), filter_from_string(), cata::tuple_hash::operator()(), and character_display::print_encumbrance().
apply< furn_t >()
template<> void apply< furn_t > (const furn_t & t, const shapetype, const tripoint & , const tripoint & , const std::vector< tripoint > & target_list)
Definition at line 1052 of file editmap.cpp.
{
    const furn_id sel_frn = t.id.id();
    map &here = get_map();
    for( auto &elem : target_list ) {
        here.furn_set( elem, sel_frn );
    }
}
References map::furn_set(), get_map(), furn_t::id, string_id< T >::id(), and editmap::target_list.
apply< ter_t >()
template<> void apply< ter_t > (const ter_t & t, const shapetype editshape, const tripoint & target, const tripoint & origin, const std::vector< tripoint > & target_list)
Definition at line 1002 of file editmap.cpp.
{
    bool isvert = false;
    bool ishori = false;
    bool doalt = false;
    ter_id teralt = undefined_ter_id;
    int alta = -1;
    int altb = -1;
    const ter_id sel_ter = t.id.id();
    if( editshape == editmap_rect ) {
        if( t.symbol() == LINE_XOXO || t.symbol() == '|' ) {
            isvert = true;
            teralt = get_alt_ter( isvert, sel_ter );
        } else if( t.symbol() == LINE_OXOX || t.symbol() == '-' ) {
            ishori = true;
            teralt = get_alt_ter( isvert, sel_ter );
        }
        if( teralt != undefined_ter_id ) {
            if( isvert ) {
                alta = target.y;
                altb = origin.y;
            } else {
                alta = target.x;
                altb = origin.x;
            }
            doalt = true;
        }
    }
    map &here = get_map();
    for( auto &elem : target_list ) {
        ter_id wter = sel_ter;
        if( doalt ) {
            if( isvert && ( elem.y == alta || elem.y == altb ) ) {
                wter = teralt;
            } else if( ishori && ( elem.x == alta || elem.x == altb ) ) {
                wter = teralt;
            }
        }
        here.ter_set( elem, wter );
        const tripoint above = elem + tripoint_above;
        if( wter->roof && here.ter( above ) == t_open_air ) {
            here.ter_set( above, wter->roof );
        }
    }
}
References editmap_rect, editmap::editshape, get_alt_ter(), get_map(), ter_t::id, string_id< T >::id(), LINE_OXOX, LINE_XOXO, editmap::origin, ter_t::roof, map_data_common_t::symbol(), t_open_air, editmap::target, editmap::target_list, map::ter(), map::ter_set(), tripoint_above, undefined_ter_id, tripoint::x, and tripoint::y.
apply< trap >()
template<> void apply< trap > (const trap & t, const shapetype, const tripoint & , const tripoint & , const std::vector< tripoint > & target_list)
Definition at line 1063 of file editmap.cpp.
{
    map &here = get_map();
    for( auto &elem : target_list ) {
        here.trap_set( elem, t.loadid );
    }
}
References get_map(), trap::loadid, editmap::target_list, and map::trap_set().
color() [1/4]
template<> nc_color color (const furn_t & t)
Definition at line 938 of file editmap.cpp.
{
    return t.color();
}
References map_data_common_t::color().
color() [2/4]
template<typename T_t > static nc_color color (const T_t & t) static
Referenced by adjust_color_brightness(), average_pixel_color(), bgcolor_from_string(), Character::bodytemp_color(), color_loader< ColorType >::ccolor(), color_from_string(), color_pixel_darken(), color_pixel_grayscale(), color_pixel_nightvision(), color_pixel_overexposed(), color_pixel_sepia(), color_pixel_z_overlay(), color_manager::color_to_id(), colorize(), spell::colorized_fail_percent(), colorized_item_name(), talk_response::create_option_line(), string_input_popup::cursor_color(), cyan_background(), string_input_popup::desc_color(), player_morale::display(), display_stat(), veh_interact::display_stats(), inventory_column::draw(), scrolling_text_view::draw(), draw_armor(), draw_armor_padding(), overmap_ui::draw_ascii(), target_ui::draw_controls_list(), draw_limb_health(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), overmap_ui::draw_om_sidebar(), draw_points(), draw_traits_tab(), editmap::edit_feature(), fold_and_print(), fold_and_print_from(), get_color_from_tag(), vehicle::get_debug_overlay_data(), requirement_data::get_folded_list(), inventory_selector::get_footer(), color_manager::get_highlight(), monster::get_HP_Bar(), color_manager::get_invert(), kill_tracker::get_kills_text(), color_manager::get_name(), get_note_string_from_color(), get_tag_from_color(), green_background(), hilite(), invert_color(), is_black(), game::list_monsters(), color_loader< ColorType >::load_colors(), magenta_background(), iuse::magic_8_ball(), target_ui::panel_spell_info(), pickup::pick_up(), print_colored_text(), npc::print_info(), advanced_inventory::print_items(), print_scrollable(), red_background(), robot_finds_kitten::robot_finds_kitten(), select_crafting_recipe(), set_points(), set_skills(), auto_pickup::user_interface::show(), robot_finds_kitten::show(), worldfactory::show_modselection_window(), player::sort_armor(), string_input_popup::string_color(), string_from_color(), string_input_popup::title_color(), string_input_popup::underscore_color(), trading_window::update_win(), iexamine::vending(), white_background(), and yellow_background().
color() [3/4]
template<> nc_color color (const ter_t & t)
Definition at line 932 of file editmap.cpp.
{
    return t.color();
}
References map_data_common_t::color().
color() [4/4]
template<> nc_color color (const trap & t)
Definition at line 944 of file editmap.cpp.
{
    return t.color;
}
References trap::color.
describe() [1/4]
template<> std::string describe (const furn_t & type)
Definition at line 961 of file editmap.cpp.
{
    return string_format( _( "Move cost: %d\nIndoors: %s\nRoof: %s" ), type.movecost,
                          type.has_flag( TFLAG_INDOORS ) ? _( "Yes" ) : _( "No" ),
                          type.has_flag( TFLAG_SUPPORTS_ROOF ) ? _( "Yes" ) : _( "No" ) );
}
References _, string_format(), TFLAG_INDOORS, TFLAG_SUPPORTS_ROOF, and type.
describe() [2/4]
template<typename T_t > static std::string describe (const T_t & t) static
Referenced by editmap::edit_feature().
describe() [3/4]
template<> std::string describe (const ter_t & type)
Definition at line 953 of file editmap.cpp.
{
    return string_format( _( "Move cost: %d\nIndoors: %s\nRoof: %s" ), type.movecost,
                          type.has_flag( TFLAG_INDOORS ) ? _( "Yes" ) : _( "No" ),
                          type.has_flag( TFLAG_SUPPORTS_ROOF ) ? _( "Yes" ) : _( "No" ) );
}
References _, string_format(), TFLAG_INDOORS, TFLAG_SUPPORTS_ROOF, and type.
describe() [4/4]
template<> std::string describe (const trap & type)
Definition at line 969 of file editmap.cpp.
{
    return string_format( _( "Visible: %d\nAvoidance: %d\nDifficulty: %d\nBenign: %s" ),
                          type.get_visibility(), type.get_avoidance(), type.get_difficulty(),
                          type.is_benign() ? _( "Yes" ) : _( "No" ) );
}
References _, string_format(), and type.
draw_override()
template<typename T_id > static void draw_override (const tripoint & p, const T_id & id) static
Referenced by editmap::edit_feature().
draw_override< furn_id >()
template<> void draw_override< furn_id > (const tripoint & p, const furn_id & id)
Definition at line 986 of file editmap.cpp.
{
    g->draw_furniture_override( p, id );
}
References g.
draw_override< ter_id >()
template<> void draw_override< ter_id > (const tripoint & p, const ter_id & id)
Definition at line 980 of file editmap.cpp.
{
    g->draw_terrain_override( p, id );
}
References g.
draw_override< trap_id >()
template<> void draw_override< trap_id > (const tripoint & p, const trap_id & id)
Definition at line 992 of file editmap.cpp.
{
    g->draw_trap_override( p, id );
}
References g.
edit_json()
template<class SAVEOBJ > void edit_json (SAVEOBJ & it)
Definition at line 107 of file editmap.cpp.
{
    int tmret = -1;
    std::string save1 = serialize( it );
    std::string osave1 = save1;
    std::vector<std::string> fs1 = fld_string( save1, TERMX - 10 );
    do {
        uilist tm;
        for( auto &elem : fs1 ) {
            tm.addentry( -1, false, -2, elem );
        }
        if( tmret == 0 ) {
            try {
                SAVEOBJ tmp;
                deserialize( tmp, save1 );
                it = std::move( tmp );
            } catch( const std::exception &err ) {
                popup( "Error on deserialization: %s", err.what() );
            }
            std::string save2 = serialize( it );
            std::vector<std::string> fs2 = fld_string( save2, TERMX - 10 );
            tm.addentry( -1, false, -2, "== Reloaded: =====================" );
            for( size_t s = 0; s < fs2.size(); ++s ) {
                tm.addentry( -1, false, -2, fs2[s] );
                if( s < fs1.size() && fs2[s] != fs1[s] ) {
                    tm.entries.back().force_color = true;
                    tm.entries.back().text_color = c_light_green;
                    tm.entries[s].force_color = true;
                    tm.entries[s].text_color = c_light_red;
                }
            }
            fs2.clear();
        } else if( tmret == 1 ) {
            string_input_popup popup;
            std::string ret = popup
                              .text( save1 )
                              .query_string();
            if( popup.confirmed() ) {
                fs1 = fld_string( ret, TERMX - 10 );
                save1 = ret;
                tmret = -2;
            }
        } else if( tmret == 2 ) {
            write_to_file( "save/jtest-1j.txt", [&]( std::ostream & fout ) {
                fout << osave1;
            }, nullptr );
            write_to_file( "save/jtest-2j.txt", [&]( std::ostream & fout ) {
                fout << serialize( it );
            }, nullptr );
        }
        tm.addentry( 0, true, 'r', pgettext( "item manipulation debug menu entry", "rehash" ) );
        tm.addentry( 1, true, 'e', pgettext( "item manipulation debug menu entry", "edit" ) );
        tm.addentry( 2, true, 'd', pgettext( "item manipulation debug menu entry",
                                             "dump to save/jtest-*.txt" ) );
        if( tmret != -2 ) {
            tm.query();
            if( tm.ret < 0 ) {
                tmret = 3;
            } else {
                tmret = tm.ret;
            }
        } else {
            tmret = 0;
        }
    } while( tmret != 3 );
}
References uilist::addentry(), c_light_green, c_light_red, deserialize(), uilist::entries, fld_string(), avatar_action::move(), pgettext(), popup(), uilist::query(), cata::hash64_detail::ret, uilist::ret, serialize(), TERMX, and write_to_file().
Referenced by editmap::edit_critter(), editmap::edit_itm(), and editmap::edit_veh().
editmap_boundaries()
static constexpr half_open_cuboid< tripoint > editmap_boundaries (editmap_boundary_min , editmap_boundary_max) static constexpr
Referenced by editmap::mapgen_retarget(), and editmap::recalc_target().
editmap_boundary_max()
static constexpr tripoint editmap_boundary_max (MAPSIZE_X , MAPSIZE_Y , OVERMAP_HEIGHT+ 1) static constexpr
editmap_boundary_min()
static constexpr tripoint editmap_boundary_min (0 , 0 , - OVERMAP_DEPTH) static constexpr
feature()
template<typename T_id > static T_id feature (const tripoint & p) static
Referenced by vehicle::get_any_parts(), vehicle::get_avail_parts(), vehicle::get_enabled_parts(), vehicle::get_parts_including_carried(), and mapgen_forest().
feature< furn_id >()
template<> furn_id feature< furn_id > (const tripoint & p)
Definition at line 896 of file editmap.cpp.
{
    return get_map().furn( p );
}
References map::furn(), and get_map().
feature< ter_id >()
template<> ter_id feature< ter_id > (const tripoint & p)
Definition at line 890 of file editmap.cpp.
{
    return get_map().ter( p );
}
References get_map(), and map::ter().
feature< trap_id >()
template<> trap_id feature< trap_id > (const tripoint & p)
Definition at line 902 of file editmap.cpp.
{
    return get_map().tr_at( p ).loadid;
}
References get_map(), trap::loadid, and map::tr_at().
fld_string()
static std::vector< std::string > fld_string (const std::string & str, int width) static
Definition at line 66 of file editmap.cpp.
{
    std::vector<std::string> lines;
    if( width < 1 ) {
        lines.push_back( str );
        return lines;
    }
    int linepos = width;
    int linestart = 0;
    int crpos = -2;
    while( linepos < static_cast<int>( str.length() ) || crpos != -1 ) {
        crpos = str.find( '\n', linestart );
        if( crpos != -1 && crpos <= linepos ) {
            lines.push_back( str.substr( linestart, crpos - linestart ) );
            linepos = crpos + width + 1;
            linestart = crpos + 1;
        } else {
            int spacepos = str.rfind( ',', linepos );
            if( spacepos == -1 ) {
                spacepos = str.find( ',', linepos );
            }
            if( spacepos < linestart ) {
                spacepos = linestart + width;
                if( spacepos < static_cast<int>( str.length() ) ) {
                    lines.push_back( str.substr( linestart, width ) );
                    linepos = spacepos + width;
                    linestart = spacepos;
                }
            } else {
                lines.push_back( str.substr( linestart, spacepos - linestart ) );
                linepos = spacepos + width;
                linestart = spacepos;
            }
        }
    }
    lines.push_back( str.substr( linestart ) );
    return lines;
}
Referenced by edit_json().
get_alt_ter()
static ter_id get_alt_ter (bool isvert, ter_id sel_ter) static
Definition at line 840 of file editmap.cpp.
{
    std::map<std::string, std::string> alts;
    alts["_v"] = "_h";
    alts["_vertical"] = "_horizontal";
    alts["_v_alarm"] = "_h_alarm";
    const std::string tersid = sel_ter.obj().id.str();
    const int sidlen = tersid.size();
    for( std::map<std::string, std::string>::const_iterator it = alts.begin(); it != alts.end();
         ++it ) {
        const std::string suffix = isvert ? it->first : it->second;
        const int slen = suffix.size();
        if( sidlen > slen && tersid.substr( sidlen - slen, slen ) == suffix ) {
            const std::string asuffix = isvert ? it->second : it->first;
            const std::string terasid = tersid.substr( 0, sidlen - slen ) + asuffix;
            const ter_str_id tid( terasid );
            if( tid.is_valid() ) {
                return tid.id();
            }
        }
    }
    return undefined_ter_id;
}
References ter_t::id, string_id< T >::id(), string_id< T >::is_valid(), int_id< T >::obj(), string_id< T >::str(), and undefined_ter_id.
Referenced by apply< ter_t >().
info_title()
template<typename T_t > static std::string info_title () static
info_title< furn_t >()
template<> std::string info_title< furn_t > ()
Definition at line 875 of file editmap.cpp.
{
    return pgettext( "map editor state", "Furniture" );
}
References pgettext().
info_title< ter_t >()
template<> std::string info_title< ter_t > ()
Definition at line 869 of file editmap.cpp.
{
    return pgettext( "map editor state", "Terrain" );
}
References pgettext().
info_title< trap >()
template<> std::string info_title< trap > ()
Definition at line 881 of file editmap.cpp.
{
    return pgettext( "map editor: traps editing", "Traps" );
}
References pgettext().
limited_shift()
static int limited_shift (int var, int & shift, int min, int max) static
Definition at line 1592 of file editmap.cpp.
{
    if( var + shift < min ) {
        shift = min - var;
    } else if( var + shift >= max ) {
        shift = shift + ( max - 1 - ( var + shift ) );
    }
    return var += shift;
}
Referenced by editmap::move_target().
symbol() [1/4]
template<> int symbol (const furn_t & t)
Definition at line 917 of file editmap.cpp.
{
    return t.symbol();
}
References map_data_common_t::symbol().
symbol() [2/4]
template<typename T_t > static int symbol (const T_t & t) static
Referenced by lightson_game::draw_level(), editmap::edit_feature(), snippet_library::expand(), kill_tracker::get_kills_text(), field_type::get_symbol(), map_memory::memorize_symbol(), anonymous_namespace{rotatable_symbols.cpp}::rotatable_symbol::operator<(), overmap_ui::show_notes_manager(), text_style_check(), and overmap_ui::update_note_preview().
symbol() [3/4]
template<> int symbol (const ter_t & t)
Definition at line 911 of file editmap.cpp.
{
    return t.symbol();
}
References map_data_common_t::symbol().
Referenced by rotatable_symbols::get().
symbol() [4/4]
template<> int symbol (const trap & t)
Definition at line 923 of file editmap.cpp.
{
    return t.sym;
}
References trap::sym.
Variable Documentation
undefined_ter_id
const ter_id undefined_ter_id(-1) (- 1) static
Referenced by apply< ter_t >(), and get_alt_ter().