Cataclysm BN: src/effect.h File Reference
effect.h File Reference
#include <set>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "hash_utils.h"
#include "translations.h"
#include "type_id.h"
Classes
class effect_type
class effect
class effects_map
Macros
#define CATA_SRC_EFFECT_H
Enumerations
enum effect_rating { e_good , e_neutral , e_bad , e_mixed }
Functions
void weed_msg (player &p)
Handles the large variety of weed messages.
void load_effect_type (const JsonObject &jo)
void reset_effect_types ()
std::vector< efftype_id > find_all_effect_types ()
std::string texitify_base_healing_power (int power)
std::string texitify_healing_power (int power)
Macro Definition Documentation
CATA_SRC_EFFECT_H
#define CATA_SRC_EFFECT_H
Definition at line 3 of file effect.h.
Enumeration Type Documentation
effect_rating
enum effect_rating
Enumerator
e_good
e_neutral
e_bad
e_mixed
Definition at line 28 of file effect.h.
                   {
    e_good,     // The effect is good for the one who has it.
    e_neutral,  // There is no effect or the effect is very nominal. This is the default.
    e_bad,      // The effect is bad for the one who has it.
    e_mixed     // The effect has good and bad parts to the one who has it.
};
Function Documentation
find_all_effect_types()
std::vector< efftype_id > find_all_effect_types ()
Definition at line 67 of file effect.cpp.
{
    std::vector<efftype_id> all;
    all.reserve( effect_types.size() );
    std::transform( effect_types.begin(), effect_types.end(), std::back_inserter( all ),
    []( const std::pair<efftype_id, effect_type> &pr ) {
        return pr.first;
    } );
    return all;
}
References om_direction::all, anonymous_namespace{effect.cpp}::effect_types, and iexamine::transform().
load_effect_type()
void load_effect_type (const JsonObject & jo)
Definition at line 37 of file effect.cpp.
{
    effect_type new_etype;
    new_etype.id = efftype_id( jo.get_string( "id" ) );
    if( jo.has_member( "name" ) ) {
        for( const JsonValue entry : jo.get_array( "name" ) ) {
            translation name;
            if( !entry.read( name ) ) {
                entry.throw_error( "Error reading effect names" );
            }
            new_etype.name.emplace_back( name );
        }
    } else {
        new_etype.name.emplace_back();
    }
    new_etype.speed_mod_name = jo.get_string( "speed_name", "" );
    if( jo.has_member( "desc" ) ) {
        for( const std::string line : jo.get_array( "desc" ) ) {
            new_etype.desc.push_back( line );
        }
    } else {
        new_etype.desc.push_back( "" );
    }
    if( jo.has_member( "reduced_desc" ) ) {
        for( const std::string line : jo.get_array( "reduced_desc" ) ) {
            new_etype.reduced_desc.push_back( line );
        }
    } else {
        new_etype.reduced_desc = new_etype.desc;
    }
    new_etype.part_descs = jo.get_bool( "part_descs", false );
    if( jo.has_member( "rating" ) ) {
        std::string r = jo.get_string( "rating" );
        if( r == "good" ) {
            new_etype.rating = e_good;
        } else if( r == "neutral" ) {
            new_etype.rating = e_neutral;
        } else if( r == "bad" ) {
            new_etype.rating = e_bad;
        } else if( r == "mixed" ) {
            new_etype.rating = e_mixed;
        } else {
            new_etype.rating = e_neutral;
        }
    } else {
        new_etype.rating = e_neutral;
    }
    new_etype.apply_message = jo.get_string( "apply_message", "" );
    new_etype.remove_message = jo.get_string( "remove_message", "" );
    new_etype.apply_memorial_log = jo.get_string( "apply_memorial_log", "" );
    new_etype.remove_memorial_log = jo.get_string( "remove_memorial_log", "" );
    new_etype.blood_analysis_description = jo.get_string( "blood_analysis_description", "" );
    for( auto &&f : jo.get_string_array( "resist_traits" ) ) { // *NOPAD*
        new_etype.resist_traits.push_back( trait_id( f ) );
    }
    for( auto &&f : jo.get_string_array( "resist_effects" ) ) { // *NOPAD*
        new_etype.resist_effects.push_back( efftype_id( f ) );
    }
    for( auto &&f : jo.get_string_array( "removes_effects" ) ) { // *NOPAD*
        new_etype.removes_effects.push_back( efftype_id( f ) );
    }
    for( auto &&f : jo.get_string_array( "blocks_effects" ) ) { // *NOPAD*
        new_etype.blocks_effects.push_back( efftype_id( f ) );
    }
    if( jo.has_string( "max_duration" ) ) {
        new_etype.max_duration = read_from_json_string<time_duration>( *jo.get_raw( "max_duration" ),
                                 time_duration::units );
    } else {
        new_etype.max_duration = time_duration::from_turns( jo.get_int( "max_duration", 0 ) );
    }
    if( jo.has_string( "int_dur_factor" ) ) {
        new_etype.int_dur_factor = read_from_json_string<time_duration>( *jo.get_raw( "int_dur_factor" ),
                                   time_duration::units );
    } else {
        new_etype.int_dur_factor = time_duration::from_turns( jo.get_int( "int_dur_factor", 0 ) );
    }
    new_etype.max_intensity = jo.get_int( "max_intensity", 1 );
    new_etype.dur_add_perc = jo.get_int( "dur_add_perc", 100 );
    new_etype.int_add_val = jo.get_int( "int_add_val", 0 );
    new_etype.int_decay_step = jo.get_int( "int_decay_step", -1 );
    new_etype.int_decay_tick = jo.get_int( "int_decay_tick", 0 );
    new_etype.load_miss_msgs( jo, "miss_messages" );
    new_etype.load_decay_msgs( jo, "decay_messages" );
    new_etype.main_parts_only = jo.get_bool( "main_parts_only", false );
    new_etype.show_in_info = jo.get_bool( "show_in_info", false );
    new_etype.permanent = jo.get_bool( "permanent", false );
    new_etype.pkill_addict_reduces = jo.get_bool( "pkill_addict_reduces", false );
    new_etype.pain_sizing = jo.get_bool( "pain_sizing", false );
    new_etype.hurt_sizing = jo.get_bool( "hurt_sizing", false );
    new_etype.harmful_cough = jo.get_bool( "harmful_cough", false );
    new_etype.max_effective_intensity = jo.get_int( "max_effective_intensity", 0 );
    new_etype.load_mod_data( jo, "base_mods" );
    new_etype.load_mod_data( jo, "scaling_mods" );
    new_etype.impairs_movement = hardcoded_movement_impairing.count( new_etype.id ) > 0;
    new_etype.flags = jo.get_tags( "flags" );
    assign( jo, "morale", new_etype.morale );
    const auto morale_effect = std::find_if( new_etype.mod_data.begin(),
    new_etype.mod_data.end(), []( decltype( *new_etype.mod_data.begin() ) & pr ) {
        return std::get<2>( pr.first ) == "MORALE";
    } );
    bool has_morale_effect = morale_effect != new_etype.mod_data.end();
    if( new_etype.morale && !has_morale_effect ) {
        jo.throw_error( "Morale type set, but no MORALE base/scaling effect", "morale" );
    } else if( !new_etype.morale && has_morale_effect ) {
        jo.throw_error( "MORALE base/scaling effect present, but no morale type set",
                        std::get<0>( morale_effect->first ) );
    }
    // TODO: Implement handling of reduced morale, remove this
    static const std::vector<std::string> mod_types = {{
            {"base_mods"}, {"scaling_mods"}
        }
    };
    if( has_morale_effect ) {
        for( const std::string &cur_mod : mod_types ) {
            auto reduced_tuple = std::make_tuple( cur_mod, true, "MORALE", "amount" );
            auto reduced = new_etype.mod_data.find( reduced_tuple );
            auto non_reduced_tuple = std::make_tuple( cur_mod, false, "MORALE", "amount" );
            auto non_reduced = new_etype.mod_data.find( non_reduced_tuple );
            bool has_reduced = reduced != new_etype.mod_data.end();
            bool has_non_reduced = non_reduced != new_etype.mod_data.end();
            if( ( has_reduced && has_non_reduced && reduced->second != non_reduced->second )
                || has_reduced != has_non_reduced ) {
                jo.throw_error( "MORALE doesn't support different amounts for resisted effects yet",
                                cur_mod );
            }
        }
    }
    effect_types[new_etype.id] = new_etype;
}
Referenced by DynamicDataLoader::initialize().
reset_effect_types()
void reset_effect_types ()
Definition at line 1415 of file effect.cpp.
{
    effect_types.clear();
}
References anonymous_namespace{effect.cpp}::effect_types.
Referenced by DynamicDataLoader::unload_data().
texitify_base_healing_power()
std::string texitify_base_healing_power (int power)
Definition at line 1459 of file effect.cpp.
{
    if( power == 1 ) {
        return colorize( _( "very poor" ), c_red );
    } else if( power == 2 ) {
        return colorize( _( "poor" ), c_light_red );
    } else if( power == 3 ) {
        return colorize( _( "average" ), c_yellow );
    } else if( power == 4 ) {
        return colorize( _( "good" ), c_light_green );
    } else if( power >= 5 ) {
        return colorize( _( "great" ), c_green );
    }
    if( power < 1 ) {
        debugmsg( "Tried to convert zero or negative value." );
    }
    return "";
}
References _, c_green, c_light_green, c_light_red, c_red, c_yellow, colorize(), and debugmsg.
Referenced by heal_actor::info().
texitify_healing_power()
std::string texitify_healing_power (int power)
Definition at line 1478 of file effect.cpp.
{
    if( power >= 1 && power <= 2 ) {
        return colorize( _( "very poor" ), c_red );
    } else if( power >= 3 && power <= 4 ) {
        return colorize( _( "poor" ), c_light_red );
    } else if( power >= 5 && power <= 6 ) {
        return colorize( _( "average" ), c_yellow );
    } else if( power >= 7 && power <= 8 ) {
        return colorize( _( "good" ), c_yellow );
    } else if( power >= 9 && power <= 10 ) {
        return colorize( _( "very good" ), c_light_green );
    } else if( power >= 11 && power <= 12 ) {
        return colorize( _( "great" ), c_light_green );
    } else if( power >= 13 && power <= 14 ) {
        return colorize( _( "outstanding" ), c_green );
    } else if( power >= 15 ) {
        return colorize( _( "perfect" ), c_green );
    }
    if( power < 1 ) {
        debugmsg( "Converted value out of bounds." );
    }
    return "";
}
References _, c_green, c_light_green, c_light_red, c_red, c_yellow, colorize(), and debugmsg.
Referenced by Character::body_window(), effect::disp_name(), and heal_actor::info().
weed_msg()
void weed_msg (player & p)
Handles the large variety of weed messages.
Intelligence changes messages when smoking weed
Definition at line 78 of file effect.cpp.
{
    const time_duration howhigh = p.get_effect_dur( effect_weed_high );
    ///\EFFECT_INT changes messages when smoking weed
    int smarts = p.get_int();
    if( howhigh > 12_minutes && one_in( 7 ) ) {
        int msg = rng( 0, 5 );
        switch( msg ) {
            case 0:
                // Freakazoid
                p.add_msg_if_player(
                    _( "The scariest thing in the world would be if all the air in the world turned to WOOD!" ) );
                return;
            case 1:
                // Simpsons
                p.add_msg_if_player(
                    _( "Could Jesus microwave a burrito so hot, that he himself couldn't eat it?" ) );
                p.mod_stored_kcal( -20 );
                return;
            case 2:
                if( smarts > 8 ) {
                    // Timothy Leary
                    p.add_msg_if_player( _( "Science is all metaphor." ) );
                } else if( smarts < 3 ) {
                    // It's Always Sunny in Philadelphia
                    p.add_msg_if_player( _( "Science is a liar sometimes." ) );
                } else {
                    // Durr
                    p.add_msg_if_player( _( "Science is wait, what was I talking about again?" ) );
                }
                return;
            case 3:
                // Dazed and Confused
                p.add_msg_if_player(
                    _( "Behind every good man there is a woman, and that woman was Martha Washington, man." ) );
                if( one_in( 2 ) ) {
                    p.add_msg_if_player(
                        _( "Every day, George would come home, and she would have a big fat bowl waiting for him when he came in the door, man." ) );
                    if( one_in( 2 ) ) {
                        p.add_msg_if_player( _( "She was a hip, hip, hip lady, man." ) );
                    }
                }
                return;
            case 4:
                if( p.has_amount( itype_money_bundle, 1 ) ) { // Half Baked
                    p.add_msg_if_player( _( "You ever see the back of a twenty dollar bill on weed?" ) );
                    if( one_in( 2 ) ) {
                        p.add_msg_if_player(
                            _( "Oh, there's some crazy shit, man.  There's a dude in the bushes.  Has he got a gun?  I dunno!" ) );
                        if( one_in( 3 ) ) {
                            p.add_msg_if_player( _( "RED TEAM GO, RED TEAM GO!" ) );
                        }
                    }
                } else if( p.has_amount( itype_holybook_bible, 1 ) ) {
                    p.add_msg_if_player( _( "You have a sudden urge to flip your bible open to Genesis 1:29" ) );
                } else { // Big Lebowski
                    p.add_msg_if_player( _( "That rug really tied the room together" ) );
                }
                return;
            case 5:
                p.add_msg_if_player( _( "I used to do drugs  I still do, but I used to, too." ) );
            default:
                return;
        }
    } else if( howhigh > 10_minutes && one_in( 5 ) ) {
        int msg = rng( 0, 5 );
        switch( msg ) {
            case 0:
                // Bob Marley
                p.add_msg_if_player( _( "The herb reveals you to yourself." ) );
                return;
            case 1:
                // Freakazoid
                p.add_msg_if_player(
                    _( "Okay, like, the scariest thing in the world would be if like you went to grab something and it wasn't there!" ) );
                return;
            case 2:
                // Simpsons
                p.add_msg_if_player( _( "They call them fingers, but I never see them fing." ) );
                if( smarts > 2 && one_in( 2 ) ) {
                    p.add_msg_if_player( _( "oh, there they go." ) );
                }
                return;
            case 3:
                // Bill Hicks
                p.add_msg_if_player(
                    _( "You suddenly realize that all matter is merely energy condensed to a slow vibration, and we are all one consciousness experiencing itself subjectively." ) );
                return;
            case 4:
                // Steve Martin
                p.add_msg_if_player( _( "I usually only smoke in the late evening." ) );
                if( one_in( 4 ) ) {
                    p.add_msg_if_player(
                        _( "Oh, occasionally the early evening, but usually the late evening, or the mid-evening." ) );
                }
                if( one_in( 4 ) ) {
                    p.add_msg_if_player( _( "Just the early evening, mid-evening and late evening." ) );
                }
                if( one_in( 4 ) ) {
                    p.add_msg_if_player(
                        _( "Occasionally, early afternoon, early mid-afternoon, or perhaps the late mid-afternoon." ) );
                }
                if( one_in( 4 ) ) {
                    p.add_msg_if_player( _( "Oh, sometimes the early-mid-late-early-morning." ) );
                }
                if( smarts > 2 ) {
                    p.add_msg_if_player( _( "But never at dusk." ) );
                }
                return;
            case 5:
            default:
                return;
        }
    } else if( howhigh > 5_minutes && one_in( 3 ) ) {
        int msg = rng( 0, 5 );
        switch( msg ) {
            case 0:
                // Cheech and Chong
                p.add_msg_if_player( _( "Dave's not here, man." ) );
                return;
            case 1:
                // Real Life
                p.add_msg_if_player( _( "Man, a cheeseburger sounds SO awesome right now." ) );
                p.mod_stored_kcal( -40 );
                if( p.has_trait( trait_VEGETARIAN ) ) {
                    p.add_msg_if_player( _( "Eh maybe not." ) );
                } else if( p.has_trait( trait_LACTOSE ) ) {
                    p.add_msg_if_player( _( "I guess, maybe, without the cheese yeah." ) );
                }
                return;
            case 2:
                // Dazed and Confused
                p.add_msg_if_player( _( "Walkin' down the hall, by myself, smokin' a j with fifty elves." ) );
                return;
            case 3:
                // Half Baked
                p.add_msg_if_player( _( "That weed was the shiz-nittlebam snip-snap-sack." ) );
                return;
            case 4:
                // re-roll
                weed_msg( p );
            case 5:
            default:
                return;
        }
    }
}
References _, player::add_msg_if_player(), effect_weed_high, Creature::get_effect_dur(), Character::get_int(), visitable< T >::has_amount(), Character::has_trait(), itype_holybook_bible, itype_money_bundle, Character::mod_stored_kcal(), one_in(), rng(), trait_LACTOSE, trait_VEGETARIAN, and weed_msg().
Referenced by item::process_litcig(), iuse::smoking(), iuse::weed_cake(), and weed_msg().