Cataclysm BN: src/event_bus.h File Reference
event_bus.h File Reference
#include <utility>
#include <vector>
#include "event.h"
Classes
class event_subscriber
class event_bus
Macros
#define CATA_SRC_EVENT_BUS_H
Functions
event_bus & get_event_bus ()
Macro Definition Documentation
CATA_SRC_EVENT_BUS_H
#define CATA_SRC_EVENT_BUS_H
Definition at line 3 of file event_bus.h.
Function Documentation
get_event_bus()
event_bus & get_event_bus ()
Definition at line 12621 of file game.cpp.
{
    return g->events();
}
References g.
Referenced by Character::apply_damage(), iexamine::pedestal_wyrm(), and trap::trigger().