Cataclysm BN: src/faction_camp.cpp File Reference
faction_camp.cpp File Reference
#include "faction_camp.h"
#include <algorithm>
#include <cstddef>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <unordered_set>
#include <vector>
#include "activity_handlers.h"
#include "avatar.h"
#include "basecamp.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "cursesdef.h"
#include "debug.h"
#include "editmap.h"
#include "enums.h"
#include "faction.h"
#include "game.h"
#include "game_constants.h"
#include "iexamine.h"
#include "input.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_group.h"
#include "item_stack.h"
#include "itype.h"
#include "kill_tracker.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapgen_functions.h"
#include "memory_fast.h"
#include "messages.h"
#include "mission.h"
#include "mission_companion.h"
#include "npc.h"
#include "npctalk.h"
#include "optional.h"
#include "output.h"
#include "overmap.h"
#include "overmap_ui.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "recipe_groups.h"
#include "requirements.h"
#include "rng.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weighted_list.h"
Classes
struct mass_volume
struct base_camps::miss_data
Namespaces
namespace base_camps
Functions
static const std::string flag_PLOWABLE ("PLOWABLE")
static const std::string flag_TREE ("TREE")
recipe_id base_camps::select_camp_option (const std::map< recipe_id, translation > &pos_options, const std::string &option)
int om_harvest_furn (npc &comp, const tripoint &omt_tgt, const furn_id &f, int chance=100, bool estimate=false, bool bring_back=true)
Counts or destroys and drops the bash items of all furniture that matches f in the map tile.
int om_harvest_furn_est (npc &comp, const tripoint &omt_tgt, const furn_id &f, int chance=100)
int om_harvest_furn_break (npc &comp, const tripoint &omt_tgt, const furn_id &f, int chance=100)
int om_harvest_ter (npc &comp, const tripoint_abs_omt &omt_tgt, const ter_id &t, int chance=100, bool estimate=false, bool bring_back=true)
Exact same as om_harvest_furn but functions on terrain.
int om_harvest_ter_est (npc &comp, const tripoint_abs_omt &omt_tgt, const ter_id &t, int chance=100)
int om_harvest_ter_break (npc &comp, const tripoint_abs_omt &omt_tgt, const ter_id &t, int chance=100)
mass_volume om_harvest_itm (npc_ptr comp, const tripoint_abs_omt &omt_tgt, int chance=100, bool take=true)
Collects all items in omt_tgt with a chance between 0 - 1.0, returns total mass and volume take, whether you take the item or count it.
void apply_camp_ownership (const tripoint &camp_pos, int radius)
int om_cutdown_trees (const tripoint_abs_omt &omt_tgt, int chance=100, bool estimate=false, bool force_cut_trunk=true)
int om_cutdown_trees_est (const tripoint_abs_omt &omt_tgt, int chance=100)
int om_cutdown_trees_logs (const tripoint_abs_omt &omt_tgt, int chance=100)
int om_cutdown_trees_trunks (const tripoint_abs_omt &omt_tgt, int chance=100)
bool om_set_hide_site (npc &comp, const tripoint_abs_omt &omt_tgt, const std::vector< item * > &itms, const std::vector< item * > &itms_rem={})
Creates an improvised shelter at omt_tgt and dumps the itms into the building.
tripoint_abs_omt om_target_tile (const tripoint_abs_omt &omt_pos, int min_range=1, int range=1, const std::vector< std::string > &possible_om_types={}, bool must_see=true, bool popup_notice=true, const tripoint_abs_omt &source=tripoint_abs_omt(-999, -999, -999), bool bounce=false)
Opens the overmap so that you can select points for missions or constructions.
void om_range_mark (const tripoint_abs_omt &origin, int range, bool add_notes=true, const std::string &message="Y;X: MAX RANGE")
void om_line_mark (const tripoint_abs_omt &origin, const tripoint_abs_omt &dest, bool add_notes=true, const std::string &message="R;X: PATH")
std::vector< tripoint_abs_omt > om_companion_path (const tripoint_abs_omt &start, int range_start=90, bool bounce=true)
time_duration companion_travel_time_calc (const tripoint_abs_omt &pos, const tripoint_abs_omt &tgt, time_duration work, int trips=1, int haulage=0)
Can be used to calculate total trip time for an NPC mission or just the traveling portion.
time_duration companion_travel_time_calc (const std::vector< tripoint_abs_omt > &journey, time_duration work, int trips=1, int haulage=0)
int om_carry_weight_to_trips (const std::vector< item * > &itms, npc_ptr comp=nullptr)
Determines how many round trips a given NPC comp will take to move all of the items itms.
int om_carry_weight_to_trips (units::mass mass, units::volume volume, units::mass carry_mass, units::volume carry_volume)
Determines how many trips it takes to move mass and volume of items with carry_mass and carry_volume moved per trip.
std::string camp_trip_description (const time_duration &total_time, const time_duration &working_time, const time_duration &travel_time, int distance, int trips, int need_food)
Formats the variables into a standard looking description to be displayed in a ynquery window.
std::string camp_car_description (vehicle *car)
Returns a string for display of the selected car so you don't chop shop the wrong one.
std::string camp_farm_act (const tripoint &omt_pos, size_t &plots_count, farm_ops operation)
int camp_food_supply (int change=0, bool return_days=false)
Changes the faction food supply by change, 0 returns total food supply, a negative total food supply hurts morale.
int camp_food_supply (time_duration work)
Same as above but takes a time_duration and consumes from faction food supply for that duration of work.
int time_to_food (time_duration work)
Returns the total charges of food time_duration work costs.
int camp_discipline (int change=0)
Changes the faction respect for you by change, returns repect.
int camp_morale (int change=0)
Changes the faction opinion for you by change, returns opinion.
bool survive_random_encounter (npc &comp, std::string &situation, int favor, int threat)
static bool update_time_left (std::string &entry, const comp_list &npc_list)
static bool update_time_fixed (std::string &entry, const comp_list &npc_list, const time_duration &duration)
static cata::optional< basecamp * > get_basecamp (npc &p, const std::string &camp_type="default")
static bool farm_valid_seed (const item &itm)
static std::pair< size_t, std::string > farm_action (const tripoint_abs_omt &omt_tgt, farm_ops op, npc_ptr comp=nullptr)
std::string get_mission_action_string (const std::string &input_mission)
Variables
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const itype_id itype_fungal_seeds ("fungal_seeds")
static const itype_id itype_log ("log")
static const itype_id itype_marloss_seed ("marloss_seed")
static const zone_type_id zone_type_camp_food ("CAMP_FOOD")
static const zone_type_id zone_type_camp_storage ("CAMP_STORAGE")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_gun ("gun")
static const skill_id skill_mechanics ("mechanics")
static const skill_id skill_melee ("melee")
static const skill_id skill_speech ("speech")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_survival ("survival")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_traps ("traps")
static const skill_id skill_unarmed ("unarmed")
static const mtype_id mon_bear ("mon_bear")
static const mtype_id mon_beaver ("mon_beaver")
static const mtype_id mon_black_rat ("mon_black_rat")
static const mtype_id mon_chicken ("mon_chicken")
static const mtype_id mon_chipmunk ("mon_chipmunk")
static const mtype_id mon_cockatrice ("mon_cockatrice")
static const mtype_id mon_cougar ("mon_cougar")
static const mtype_id mon_cow ("mon_cow")
static const mtype_id mon_coyote ("mon_coyote")
static const mtype_id mon_deer ("mon_deer")
static const mtype_id mon_duck ("mon_duck")
static const mtype_id mon_fox_gray ("mon_fox_gray")
static const mtype_id mon_fox_red ("mon_fox_red")
static const mtype_id mon_groundhog ("mon_groundhog")
static const mtype_id mon_grouse ("mon_grouse")
static const mtype_id mon_hare ("mon_hare")
static const mtype_id mon_lemming ("mon_lemming")
static const mtype_id mon_mink ("mon_mink")
static const mtype_id mon_moose ("mon_moose")
static const mtype_id mon_muskrat ("mon_muskrat")
static const mtype_id mon_opossum ("mon_opossum")
static const mtype_id mon_otter ("mon_otter")
static const mtype_id mon_pheasant ("mon_pheasant")
static const mtype_id mon_pig ("mon_pig")
static const mtype_id mon_rabbit ("mon_rabbit")
static const mtype_id mon_squirrel ("mon_squirrel")
static const mtype_id mon_turkey ("mon_turkey")
static const mtype_id mon_weasel ("mon_weasel")
static const mtype_id mon_wolf ("mon_wolf")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
std::map< std::string, miss_data > base_camps::miss_info
Function Documentation
apply_camp_ownership()
void apply_camp_ownership (const tripoint & camp_pos, int radius)
Definition at line 4022 of file faction_camp.cpp.
{
    map &here = get_map();
    for( const tripoint &p : here.points_in_rectangle( camp_pos + point( -radius, -radius ),
            camp_pos + point( radius, radius ) ) ) {
        auto items = here.i_at( p.xy() );
        for( item &elem : items ) {
            elem.set_owner( g->u );
        }
    }
}
References g, get_map(), map::i_at(), and map::points_in_rectangle().
Referenced by basecamp::place_results().
camp_car_description()
std::string camp_car_description (vehicle * car)
Returns a string for display of the selected car so you don't chop shop the wrong one.
Definition at line 3825 of file faction_camp.cpp.
{
    std::string entry = string_format( _( "Name:     %s\n" ), right_justify( car->name, 25 ) );
    entry += _( "----          Engines          ----\n" );
    for( const vpart_reference &vpr : car->get_any_parts( "ENGINE" ) ) {
        const vehicle_part &pt = vpr.part();
        const vpart_info &vp = pt.info();
        entry += string_format( _( "Engine:   %s\n" ), right_justify( vp.name(), 25 ) );
        entry += string_format( _( ">Status:  %24d%%\n" ),
                                static_cast<int>( 100 * pt.health_percent() ) );
        entry += string_format( _( ">Fuel:    %s\n" ), right_justify( item::nname( vp.fuel_type ), 25 ) );
    }
    std::map<itype_id, int> fuels = car->fuels_left();
    entry += _( "----  Fuel Storage & Battery   ----\n" );
    for( auto &fuel : fuels ) {
        std::string fuel_entry = string_format( "%d/%d", car->fuel_left( fuel.first ),
                                                car->fuel_capacity( fuel.first ) );
        entry += string_format( ">%s:%s\n", item( fuel.first ).tname(),
                                right_justify( fuel_entry, 33 - utf8_width( item( fuel.first ).tname() ) ) );
    }
    for( const vpart_reference &vpr : car->get_all_parts() ) {
        if( vpr.part().is_battery() ) {
            const vpart_info &vp = vpr.part().info();
            entry += string_format( ">%s:%*d%%\n", vp.name(), 32 - utf8_width( vp.name() ),
                                    static_cast<int>( 100.0 * vpr.part().ammo_remaining() /
                                            vpr.part().ammo_capacity() ) );
        }
    }
    entry += "\n";
    entry += _( "Estimated Chop Time:         5 Days\n" );
    return entry;
}
References _, vehicle::fuel_capacity(), vehicle::fuel_left(), vpart_info::fuel_type, vehicle::fuels_left(), vehicle::get_all_parts(), vehicle::get_any_parts(), vehicle_part::health_percent(), vehicle_part::info(), vpart_info::name(), vehicle::name, item::nname(), right_justify(), string_format(), item::tname(), and utf8_width().
Referenced by basecamp::start_garage_chop().
camp_discipline()
int camp_discipline (int change = 0)
Changes the faction respect for you by change, returns repect.
Definition at line 3974 of file faction_camp.cpp.
{
    faction *yours = g->u.get_faction();
    yours->respects_u += change;
    return yours->respects_u;
}
References g, and faction_template::respects_u.
Referenced by basecamp::recruit_evaluation().
camp_farm_act()
std::string camp_farm_act (const tripoint & omt_pos, size_t & plots_count, farm_ops operation)
camp_food_supply() [1/2]
int camp_food_supply (int change = 0, bool return_days = false)
Changes the faction food supply by change, 0 returns total food supply, a negative total food supply hurts morale.
Definition at line 3859 of file faction_camp.cpp.
{
    faction *yours = g->u.get_faction();
    yours->food_supply += change;
    if( yours->food_supply < 0 ) {
        yours->likes_u += yours->food_supply / 1250;
        yours->respects_u += yours->food_supply / 625;
        yours->food_supply = 0;
    }
    if( return_days ) {
        return yours->food_supply / 2500;
    }
    return yours->food_supply;
}
References faction_template::food_supply, g, faction_template::likes_u, and faction_template::respects_u.
Referenced by camp_food_supply(), basecamp::distribute_food(), basecamp::finish_return(), basecamp::get_available_missions(), basecamp::recipe_batch_max(), basecamp::recruit_evaluation(), basecamp::recruit_return(), basecamp::start_menial_labor(), and basecamp::start_mission().
camp_food_supply() [2/2]
int camp_food_supply (time_duration work)
Same as above but takes a time_duration and consumes from faction food supply for that duration of work.
Definition at line 3875 of file faction_camp.cpp.
{
    return camp_food_supply( -time_to_food( work ) );
}
References camp_food_supply(), and time_to_food().
camp_morale()
int camp_morale (int change = 0)
Changes the faction opinion for you by change, returns opinion.
Definition at line 3981 of file faction_camp.cpp.
{
    faction *yours = g->u.get_faction();
    yours->likes_u += change;
    return yours->likes_u;
}
References g, and faction_template::likes_u.
Referenced by basecamp::recruit_evaluation().
camp_trip_description()
std::string camp_trip_description (const time_duration & total_time, const time_duration & working_time, const time_duration & travel_time, int distance, int trips, int need_food)
Formats the variables into a standard looking description to be displayed in a ynquery window.
Definition at line 3646 of file faction_camp.cpp.
{
    std::string entry = "\n";
    //A square is roughly 3 m
    int dist_m = distance * SEEX * 2 * 3;
    if( dist_m > 1000 ) {
        entry += string_format( _( ">Distance:%15.2f (km)\n" ), dist_m / 1000.0 );
        entry += string_format( _( ">One Way: %15d (trips)\n" ), trips );
        entry += string_format( _( ">Covered: %15.2f (km)\n" ), dist_m / 1000.0 * trips );
    } else {
        entry += string_format( _( ">Distance:%15d (m)\n" ), dist_m );
        entry += string_format( _( ">One Way: %15d (trips)\n" ), trips );
        entry += string_format( _( ">Covered: %15d (m)\n" ), dist_m * trips );
    }
    entry += string_format( _( ">Travel:  %s\n" ), right_justify( to_string( travel_time ), 23 ) );
    entry += string_format( _( ">Working: %s\n" ), right_justify( to_string( working_time ), 23 ) );
    entry += "----                   ----\n";
    entry += string_format( _( "Total:    %s\n" ), right_justify( to_string( total_time ), 23 ) );
    entry += string_format( _( "Food:     %15d (kcal)\n\n" ), need_food );
    return entry;
}
References _, need_food, right_justify(), SEEX, string_format(), and to_string().
Referenced by basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
companion_travel_time_calc() [1/2]
time_duration companion_travel_time_calc (const std::vector< tripoint_abs_omt > & journey, time_duration work, int trips = 1, int haulage = 0)
Definition at line 3475 of file faction_camp.cpp.
{
    int one_way = 0;
    for( auto &om : journey ) {
        const oter_id &omt_ref = overmap_buffer.ter( om );
        std::string om_id = omt_ref.id().c_str();
        //Player walks 1 om is roughly 30 seconds
        if( om_id == "field" ) {
            one_way += 30 + 30 * haulage;
        } else if( om_id == "forest" ) {
            one_way += 40 + 30 * haulage;
        } else if( om_id == "forest_thick" ) {
            one_way += 50 + 30 * haulage;
        } else if( om_id == "forest_water" ) {
            one_way += 60 + 30 * haulage;
        } else if( is_river( omt_ref ) ) {
            // hauling stuff over a river is slow, because you have to portage most items
            one_way += 200 + 40 * haulage;
        } else {
            one_way += 40 + 30 * haulage;
        }
    }
    return work + one_way * trips * 1_seconds;
}
References string_id< T >::c_str(), int_id< T >::id(), is_river(), coords::om, overmap_buffer, and overmapbuffer::ter().
companion_travel_time_calc() [2/2]
time_duration companion_travel_time_calc (const tripoint_abs_omt & pos, const tripoint_abs_omt & tgt, time_duration work, int trips = 1, int haulage = 0)
Can be used to calculate total trip time for an NPC mission or just the traveling portion.
Doesn't use the pathingalgorithms yet.
Parameters
omt_pos start point
omt_tgt target point
work how much time the NPC will stay at the target
trips how many trips back and forth the NPC will make
Definition at line 3468 of file faction_camp.cpp.
{
    std::vector<tripoint_abs_omt> journey = line_to( omt_pos, omt_tgt );
    return companion_travel_time_calc( journey, work, trips, haulage );
}
References companion_travel_time_calc(), and line_to().
Referenced by companion_travel_time_calc(), basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
farm_action()
static std::pair< size_t, std::string > farm_action (const tripoint_abs_omt & omt_tgt, farm_ops op, npc_ptr comp = nullptr) static
Survival increases number of plants harvested from a seed
Definition at line 2281 of file faction_camp.cpp.
{
    size_t plots_cnt = 0;
    std::string crops;
    const auto is_dirtmound = []( const tripoint & pos, tinymap & bay1, tinymap & bay2 ) {
        return ( bay1.ter( pos ) == t_dirtmound ) && ( !bay2.has_furn( pos ) );
    };
    const auto is_unplowed = []( const tripoint & pos, tinymap & farm_map ) {
        const ter_id &farm_ter = farm_map.ter( pos );
        return farm_ter->has_flag( flag_PLOWABLE );
    };
    std::set<std::string> plant_names;
    std::vector<item *> seed_inv;
    if( comp ) {
        seed_inv = comp->companion_mission_inv.items_with( farm_valid_seed );
    }
    //farm_json is what the area should look like according to jsons
    tinymap farm_json;
    // TODO: fix point types
    farm_json.generate( project_to<coords::sm>( omt_tgt ).raw(), calendar::turn );
    //farm_map is what the area actually looks like
    tinymap farm_map;
    farm_map.load( project_to<coords::sm>( omt_tgt ), false );
    tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
    tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
    bool done_planting = false;
    map &here = get_map();
    for( const tripoint &pos : farm_map.points_in_rectangle( mapmin, mapmax ) ) {
        if( done_planting ) {
            break;
        }
        switch( op ) {
            case farm_ops::plow:
                //Needs to be plowed to match json
                if( is_dirtmound( pos, farm_json, farm_map ) && is_unplowed( pos, farm_map ) ) {
                    plots_cnt += 1;
                    if( comp ) {
                        farm_map.ter_set( pos, t_dirtmound );
                    }
                }
                break;
            case farm_ops::plant:
                if( is_dirtmound( pos, farm_map, farm_map ) ) {
                    plots_cnt += 1;
                    if( comp ) {
                        if( seed_inv.empty() ) {
                            done_planting = true;
                            break;
                        }
                        item *tmp_seed = seed_inv.back();
                        seed_inv.pop_back();
                        std::list<item> used_seed;
                        if( tmp_seed->count_by_charges() ) {
                            used_seed.push_back( *tmp_seed );
                            tmp_seed->charges -= 1;
                            if( tmp_seed->charges > 0 ) {
                                seed_inv.push_back( tmp_seed );
                            }
                        }
                        used_seed.front().set_age( 0_turns );
                        farm_map.add_item_or_charges( pos, used_seed.front() );
                        farm_map.set( pos, t_dirt, f_plant_seed );
                    }
                }
                break;
            case farm_ops::harvest:
                if( farm_map.furn( pos ) == f_plant_harvest ) {
                    // Can't use item_stack::only_item() since there might be fertilizer
                    map_stack items = farm_map.i_at( pos );
                    const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
                        return it.is_seed();
                    } );
                    if( seed != items.end() && farm_valid_seed( *seed ) ) {
                        plots_cnt += 1;
                        if( comp ) {
                            int skillLevel = comp->get_skill_level( skill_survival );
                            ///\EFFECT_SURVIVAL increases number of plants harvested from a seed
                            int plant_cnt = rng( skillLevel / 2, skillLevel );
                            plant_cnt = std::min( std::max( plant_cnt, 1 ), 9 );
                            int seed_cnt = std::max( 1, rng( plant_cnt / 4, plant_cnt / 2 ) );
                            for( auto &i : iexamine::get_harvest_items( *seed->type, plant_cnt,
                                    seed_cnt, true ) ) {
                                here.add_item_or_charges( g->u.pos(), i );
                            }
                            farm_map.i_clear( pos );
                            farm_map.furn_set( pos, f_null );
                            farm_map.ter_set( pos, t_dirt );
                        } else {
                            plant_names.insert( item::nname( itype_id( seed->type->seed->fruit_id ) ) );
                        }
                    }
                }
                break;
            default:
                // let the callers handle no op argument
                break;
        }
    }
    if( comp ) {
        farm_map.save();
    }
    int total_c = 0;
    for( const std::string &i : plant_names ) {
        if( total_c < 5 ) {
            crops += "    " + i + "\n";
            total_c++;
        } else if( total_c == 5 ) {
            crops += _( "+ more\n" );
            break;
        }
    }
    return std::make_pair( plots_cnt, crops );
}
References _, map::add_item_or_charges(), item_stack::begin(), item::charges, npc::companion_mission_inv, item::count_by_charges(), item_stack::end(), f_null, f_plant_harvest, f_plant_seed, farm_valid_seed(), flag_PLOWABLE(), map::furn(), map::furn_set(), g, map::generate(), iexamine::get_harvest_items(), get_map(), Character::get_skill_level(), harvest, map_data_common_t::has_flag(), map::i_at(), map::i_clear(), visitable< T >::items_with(), map::load(), item::nname(), plant, plow, map::points_in_rectangle(), rng(), map::save(), iuse::seed(), SEEX, SEEY, map::set(), skill_survival, t_dirt, t_dirtmound, map::ter_set(), calendar::turn, and coords::coord_point< Point, Origin, Scale >::z().
Referenced by basecamp::farm_description(), basecamp::farm_return(), and basecamp::start_farm_op().
farm_valid_seed()
static bool farm_valid_seed (const item & itm) static
Definition at line 2276 of file faction_camp.cpp.
{
    return itm.is_seed() && itm.typeId() != itype_marloss_seed && itm.typeId() != itype_fungal_seeds;
}
References item::is_seed(), itype_fungal_seeds, itype_marloss_seed, and item::typeId().
Referenced by farm_action(), and basecamp::start_farm_op().
flag_PLOWABLE()
static const std::string flag_PLOWABLE ("PLOWABLE") static
Referenced by farm_action().
flag_TREE()
static const std::string flag_TREE ("TREE") static
Referenced by om_cutdown_trees().
get_basecamp()
static cata::optional< basecamp * > get_basecamp (npc & p, const std::string & camp_type = "default") static
Definition at line 509 of file faction_camp.cpp.
{
    tripoint_abs_omt omt_pos = p.global_omt_location();
    cata::optional<basecamp *> bcp = overmap_buffer.find_camp( omt_pos.xy() );
    if( bcp ) {
        return bcp;
    }
    get_map().add_camp( omt_pos, "faction_camp" );
    bcp = overmap_buffer.find_camp( omt_pos.xy() );
    if( !bcp ) {
        return cata::nullopt;
    }
    basecamp *temp_camp = *bcp;
    temp_camp->define_camp( omt_pos, camp_type );
    return temp_camp;
}
References map::add_camp(), basecamp::define_camp(), overmapbuffer::find_camp(), get_map(), Character::global_omt_location(), cata::nullopt, overmap_buffer, and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by talk_function::basecamp_mission(), talk_function::recover_camp(), and talk_function::start_camp().
get_mission_action_string()
std::string get_mission_action_string (const std::string & input_mission)
Definition at line 3437 of file faction_camp.cpp.
{
    const base_camps::miss_data &miss_info = base_camps::miss_info[ input_mission ];
    return miss_info.action.translated();
}
References base_camps::miss_info.
Referenced by npc::faction_display().
om_carry_weight_to_trips() [1/2]
int om_carry_weight_to_trips (const std::vector< item * > & itms, npc_ptr comp = nullptr)
Determines how many round trips a given NPC comp will take to move all of the items itms.
Definition at line 3510 of file faction_camp.cpp.
{
    units::mass total_m = 0_gram;
    units::volume total_v = 0_ml;
    for( auto &i : itms ) {
        total_m += i->weight( true );
        total_v += i->volume( true );
    }
    units::mass max_m = comp ? comp->weight_capacity() - comp->weight_carried() : 30_kilogram;
    //Assume an additional pack will be carried in addition to normal gear
    units::volume sack_v = item( itype_id( "makeshift_sling" ) ).get_storage();
    units::volume max_v = comp ? comp->volume_capacity() - comp->volume_carried() : sack_v;
    max_v += sack_v;
    return om_carry_weight_to_trips( total_m, total_v, max_m, max_v );
}
References item::get_storage(), and om_carry_weight_to_trips().
Referenced by om_carry_weight_to_trips(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
om_carry_weight_to_trips() [2/2]
int om_carry_weight_to_trips (units::mass mass, units::volume volume, units::mass carry_mass, units::volume carry_volume)
Determines how many trips it takes to move mass and volume of items with carry_mass and carry_volume moved per trip.
Definition at line 3501 of file faction_camp.cpp.
{
    int trips_m = 1 + mass / carry_mass;
    int trips_v = 1 + volume / carry_volume;
    // return the number of round trips
    return 2 * std::max( trips_m, trips_v );
}
om_companion_path()
std::vector< tripoint_abs_omt > om_companion_path (const tripoint_abs_omt & start, int range_start = 90, bool bounce = true)
Definition at line 3526 of file faction_camp.cpp.
{
    std::vector<tripoint_abs_omt> scout_points;
    tripoint_abs_omt last = start;
    int range = range_start;
    int def_range = range_start;
    while( range > 3 ) {
        tripoint_abs_omt spt = om_target_tile( last, 0, range, {}, false, true, last, false );
        if( spt == tripoint_abs_omt( -999, -999, -999 ) ) {
            scout_points.clear();
            return scout_points;
        }
        if( last == spt ) {
            break;
        }
        std::vector<tripoint_abs_omt> note_pts = line_to( last, spt );
        scout_points.insert( scout_points.end(), note_pts.begin(), note_pts.end() );
        om_line_mark( last, spt );
        range -= rl_dist( spt.xy(), last.xy() );
        last = spt;
        const oter_id &omt_ref = overmap_buffer.ter( last );
        if( bounce && omt_ref.id() == "faction_hide_site_0" ) {
            range = def_range * .75;
            def_range = range;
        }
    }
    for( auto pt : scout_points ) {
        om_line_mark( pt, pt, false );
    }
    return scout_points;
}
References int_id< T >::id(), last, line_to(), om_line_mark(), om_target_tile(), overmap_buffer, rl_dist(), overmapbuffer::ter(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by basecamp::start_combat_mission().
om_cutdown_trees()
int om_cutdown_trees (const tripoint_abs_omt & omt_tgt, int chance = 100, bool estimate = false, bool force_cut_trunk = true)
Definition at line 3223 of file faction_camp.cpp.
{
    tinymap target_bay;
    target_bay.load( project_to<coords::sm>( omt_tgt ), false );
    int harvested = 0;
    int total = 0;
    tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
    tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
    for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
        if( target_bay.ter( p ).obj().has_flag( flag_TREE ) && rng( 0, 100 ) < chance ) {
            total++;
            if( estimate ) {
                continue;
            }
            tripoint delta{
                3 * ( 2 * rng( 0, 1 ) - 1 ) + rng( -1, 1 ),
                3 * rng( -1, 1 ) + rng( -1, 1 ),
                omt_tgt.z()
            };
            std::vector<tripoint> tree = line_to( p, p + delta, rng( 1, 8 ) );
            for( auto &elem : tree ) {
                target_bay.destroy( elem );
                target_bay.ter_set( elem, t_trunk );
            }
            target_bay.ter_set( p, t_dirt );
            harvested++;
        }
    }
    if( estimate ) {
        return total;
    }
    if( !force_cut_trunk ) {
        target_bay.save();
        return harvested;
    }
    // having cut down the trees, cut the trunks into logs
    for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
        if( target_bay.ter( p ) == ter_id( "t_trunk" ) ) {
            target_bay.ter_set( p, t_dirt );
            target_bay.spawn_item( p, itype_log, rng( 2, 3 ), 0, calendar::turn );
            harvested++;
        }
    }
    target_bay.save();
    return harvested;
}
References map::destroy(), flag_TREE(), map_data_common_t::has_flag(), itype_log, line_to(), map::load(), int_id< T >::obj(), map::points_in_rectangle(), rng(), map::save(), SEEX, SEEY, map::spawn_item(), t_dirt, t_trunk, map::ter(), map::ter_set(), calendar::turn, and coords::coord_point< Point, Origin, Scale >::z().
Referenced by om_cutdown_trees_est(), om_cutdown_trees_logs(), and om_cutdown_trees_trunks().
om_cutdown_trees_est()
int om_cutdown_trees_est (const tripoint_abs_omt & omt_tgt, int chance = 100)
Definition at line 3211 of file faction_camp.cpp.
{
    return om_cutdown_trees( omt_tgt, chance, true, false );
}
References om_cutdown_trees().
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
om_cutdown_trees_logs()
int om_cutdown_trees_logs (const tripoint_abs_omt & omt_tgt, int chance = 100)
Definition at line 3215 of file faction_camp.cpp.
{
    return om_cutdown_trees( omt_tgt, chance, false, true );
}
References om_cutdown_trees().
Referenced by basecamp::start_cut_logs().
om_cutdown_trees_trunks()
int om_cutdown_trees_trunks (const tripoint_abs_omt & omt_tgt, int chance = 100)
Definition at line 3219 of file faction_camp.cpp.
{
    return om_cutdown_trees( omt_tgt, chance, false, false );
}
References om_cutdown_trees().
Referenced by basecamp::start_clearcut().
om_harvest_furn()
int om_harvest_furn (npc & comp, const tripoint & omt_tgt, const furn_id & f, int chance = 100, bool estimate = false, bool bring_back = true)
Counts or destroys and drops the bash items of all furniture that matches f in the map tile.
Parameters
comp NPC companion
omt_tgt the targeted OM tile
f furniture you are looking for
chance chance of destruction, 0 to 100
estimate if true, non-destructive count of the furniture
bring_back force the destruction of the furniture and bring back the drop items
Definition at line 3135 of file faction_camp.cpp.
{
    const furn_t &furn_tgt = f.obj();
    tinymap target_bay;
    target_bay.load( tripoint( omt_tgt.x * 2, omt_tgt.y * 2, omt_tgt.z ), false );
    int harvested = 0;
    int total = 0;
    tripoint mapmin = tripoint( 0, 0, omt_tgt.z );
    tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z );
    for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
        if( target_bay.furn( p ) == f && x_in_y( chance, 100 ) ) {
            total++;
            if( estimate ) {
                continue;
            }
            if( bring_back ) {
                for( const item &itm : item_group::items_from( furn_tgt.bash.drop_group,
                        calendar::turn ) ) {
                    comp.companion_mission_inv.push_back( itm );
                }
                harvested++;
            }
            if( bring_back || comp.str_cur > furn_tgt.bash.str_min + rng( -2, 2 ) ) {
                target_bay.furn_set( p, furn_tgt.bash.furn_set );
            }
        }
    }
    target_bay.save();
    if( bring_back ) {
        return harvested;
    }
    return total;
}
References map_data_common_t::bash, npc::companion_mission_inv, map_bash_info::drop_group, map::furn(), map::furn_set(), map_bash_info::furn_set, item_group::items_from(), map::load(), int_id< T >::obj(), map::points_in_rectangle(), inventory::push_back(), rng(), map::save(), SEEX, SEEY, Character::str_cur, map_bash_info::str_min, calendar::turn, tripoint::x, x_in_y(), tripoint::y, and tripoint::z.
Referenced by om_harvest_furn_break(), and om_harvest_furn_est().
om_harvest_furn_break()
int om_harvest_furn_break (npc & comp, const tripoint & omt_tgt, const furn_id & f, int chance = 100)
Definition at line 3131 of file faction_camp.cpp.
{
    return om_harvest_furn( comp, omt_tgt, f, chance, false, false );
}
References om_harvest_furn().
om_harvest_furn_est()
int om_harvest_furn_est (npc & comp, const tripoint & omt_tgt, const furn_id & f, int chance = 100)
Definition at line 3127 of file faction_camp.cpp.
{
    return om_harvest_furn( comp, omt_tgt, f, chance, true, false );
}
References om_harvest_furn().
om_harvest_itm()
mass_volume om_harvest_itm (npc_ptr comp, const tripoint_abs_omt & omt_tgt, int chance = 100, bool take = true)
Collects all items in omt_tgt with a chance between 0 - 1.0, returns total mass and volume take, whether you take the item or count it.
Definition at line 3271 of file faction_camp.cpp.
{
    tinymap target_bay;
    target_bay.load( project_to<coords::sm>( omt_tgt ), false );
    units::mass harvested_m = 0_gram;
    units::volume harvested_v = 0_ml;
    units::mass total_m = 0_gram;
    units::volume total_v = 0_ml;
    int total_num = 0;
    int harvested_num = 0;
    tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
    tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
    for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
        for( const item &i : target_bay.i_at( p ) ) {
            total_m += i.weight( true );
            total_v += i.volume( true );
            total_num += 1;
            if( take && x_in_y( chance, 100 ) ) {
                if( comp ) {
                    comp->companion_mission_inv.push_back( i );
                }
                harvested_m += i.weight( true );
                harvested_v += i.volume( true );
                harvested_num += 1;
            }
        }
        if( take ) {
            target_bay.i_clear( p );
        }
    }
    target_bay.save();
    mass_volume results;
    if( take ) {
        results.wgt = harvested_m;
        results.vol = harvested_v;
        results.count = harvested_num;
    } else {
        results.wgt = total_m;
        results.vol = total_v;
        results.count = total_num;
    }
    return results;
}
References mass_volume::count, map::i_at(), map::i_clear(), map::load(), map::points_in_rectangle(), map::save(), SEEX, SEEY, mass_volume::vol, mass_volume::wgt, x_in_y(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by basecamp::start_cut_logs().
om_harvest_ter()
int om_harvest_ter (npc & comp, const tripoint_abs_omt & omt_tgt, const ter_id & t, int chance = 100, bool estimate = false, bool bring_back = true)
Exact same as om_harvest_furn but functions on terrain.
Definition at line 3178 of file faction_camp.cpp.
{
    const ter_t &ter_tgt = t.obj();
    tinymap target_bay;
    target_bay.load( project_to<coords::sm>( omt_tgt ), false );
    int harvested = 0;
    int total = 0;
    tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
    tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
    for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
        if( target_bay.ter( p ) == t && x_in_y( chance, 100 ) ) {
            total++;
            if( estimate ) {
                continue;
            }
            if( bring_back ) {
                for( const item &itm : item_group::items_from( ter_tgt.bash.drop_group,
                        calendar::turn ) ) {
                    comp.companion_mission_inv.push_back( itm );
                }
                harvested++;
                target_bay.ter_set( p, ter_tgt.bash.ter_set );
            }
        }
    }
    target_bay.save();
    if( bring_back ) {
        return harvested;
    }
    return total;
}
References map_data_common_t::bash, npc::companion_mission_inv, map_bash_info::drop_group, item_group::items_from(), map::load(), int_id< T >::obj(), map::points_in_rectangle(), inventory::push_back(), map::save(), SEEX, SEEY, map::ter(), map::ter_set(), map_bash_info::ter_set, calendar::turn, x_in_y(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by om_harvest_ter_break(), om_harvest_ter_est(), and basecamp::start_cut_logs().
om_harvest_ter_break()
int om_harvest_ter_break (npc & comp, const tripoint_abs_omt & omt_tgt, const ter_id & t, int chance = 100)
Definition at line 3174 of file faction_camp.cpp.
{
    return om_harvest_ter( comp, omt_tgt, t, chance, false, false );
}
References om_harvest_ter().
Referenced by basecamp::start_clearcut().
om_harvest_ter_est()
int om_harvest_ter_est (npc & comp, const tripoint_abs_omt & omt_tgt, const ter_id & t, int chance = 100)
Definition at line 3170 of file faction_camp.cpp.
{
    return om_harvest_ter( comp, omt_tgt, t, chance, true, false );
}
References om_harvest_ter().
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
om_line_mark()
void om_line_mark (const tripoint_abs_omt & origin, const tripoint_abs_omt & dest, bool add_notes = true, const std::string & message = "R;X: PATH")
Definition at line 3419 of file faction_camp.cpp.
{
    std::vector<tripoint_abs_omt> note_pts = line_to( origin, dest );
    for( auto pt : note_pts ) {
        if( add_notes ) {
            if( !overmap_buffer.has_note( pt ) ) {
                overmap_buffer.add_note( pt, message );
            }
        } else {
            if( overmap_buffer.has_note( pt ) && overmap_buffer.note( pt ) == message ) {
                overmap_buffer.delete_note( pt );
            }
        }
    }
}
References overmapbuffer::add_note(), overmapbuffer::delete_note(), overmapbuffer::has_note(), line_to(), mapgen_defer::message, overmapbuffer::note(), and overmap_buffer.
Referenced by om_companion_path(), and om_target_tile().
om_range_mark()
void om_range_mark (const tripoint_abs_omt & origin, int range, bool add_notes = true, const std::string & message = "Y;X: MAX RANGE")
Definition at line 3385 of file faction_camp.cpp.
{
    std::vector<tripoint_abs_omt> note_pts;
    //North Limit
    for( int x = origin.x() - range; x < origin.x() + range + 1; x++ ) {
        note_pts.push_back( tripoint_abs_omt( x, origin.y() - range, origin.z() ) );
    }
    //South
    for( int x = origin.x() - range; x < origin.x() + range + 1; x++ ) {
        note_pts.push_back( tripoint_abs_omt( x, origin.y() + range, origin.z() ) );
    }
    //West
    for( int y = origin.y() - range; y < origin.y() + range + 1; y++ ) {
        note_pts.push_back( tripoint_abs_omt( origin.x() - range, y, origin.z() ) );
    }
    //East
    for( int y = origin.y() - range; y < origin.y() + range + 1; y++ ) {
        note_pts.push_back( tripoint_abs_omt( origin.x() + range, y, origin.z() ) );
    }
    for( auto pt : note_pts ) {
        if( add_notes ) {
            if( !overmap_buffer.has_note( pt ) ) {
                overmap_buffer.add_note( pt, message );
            }
        } else {
            if( overmap_buffer.has_note( pt ) && overmap_buffer.note( pt ) == message ) {
                overmap_buffer.delete_note( pt );
            }
        }
    }
}
References overmapbuffer::add_note(), overmapbuffer::delete_note(), overmapbuffer::has_note(), mapgen_defer::message, overmapbuffer::note(), and overmap_buffer.
Referenced by om_target_tile().
om_set_hide_site()
bool om_set_hide_site (npc & comp, const tripoint_abs_omt & omt_tgt, const std::vector< item * > & itms, const std::vector< item * > & itms_rem = {})
Creates an improvised shelter at omt_tgt and dumps the itms into the building.
Definition at line 3444 of file faction_camp.cpp.
{
    tinymap target_bay;
    target_bay.load( project_to<coords::sm>( omt_tgt ), false );
    target_bay.ter_set( point( 11, 10 ), t_improvised_shelter );
    for( auto i : itms_rem ) {
        comp.companion_mission_inv.add_item( *i );
        target_bay.i_rem( point( 11, 10 ), i );
    }
    for( auto i : itms ) {
        target_bay.add_item_or_charges( point( 11, 10 ), *i );
        g->u.use_amount( i->typeId(), 1 );
    }
    target_bay.save();
    overmap_buffer.ter_set( omt_tgt, oter_id( "faction_hide_site_0" ) );
    overmap_buffer.reveal( omt_tgt.xy(), 3, 0 );
    return true;
}
References inventory::add_item(), map::add_item_or_charges(), npc::companion_mission_inv, g, map::i_rem(), map::load(), overmap_buffer, overmapbuffer::reveal(), map::save(), t_improvised_shelter, map::ter_set(), overmapbuffer::ter_set(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
om_target_tile()
tripoint_abs_omt om_target_tile (const tripoint_abs_omt & omt_pos, int min_range = 1, int range = 1, const std::vector< std::string > & possible_om_types = {}, bool must_see = true, bool popup_notice = true, const tripoint_abs_omt & source = tripoint_abs_omt(-999, -999, -999), bool bounce = false)
Opens the overmap so that you can select points for missions or constructions.
Parameters
omt_pos where your camp is, used for calculating travel distances
min_range
range max number of OM tiles the user can select
possible_om_types requires the user to reselect if the OM picked isn't in the list
must_see whether the user can select points in the unknown/fog of war
popup_notice toggles if the user should be shown ranges before being allowed to pick
source if you are selecting multiple points this is where the OM is centered to start
bounce
Definition at line 3316 of file faction_camp.cpp.
{
    bool errors = false;
    if( popup_notice ) {
        popup( _( "Select a location between  %d and  %d tiles away." ), min_range, range );
    }
    std::vector<std::string> bounce_locations = { "faction_hide_site_0" };
    tripoint_abs_omt where;
    om_range_mark( omt_pos, range );
    om_range_mark( omt_pos, min_range, true, "Y;X: MIN RANGE" );
    if( source == tripoint_abs_omt( -999, -999, -999 ) ) {
        where = ui::omap::choose_point();
    } else {
        where = ui::omap::choose_point( source );
    }
    om_range_mark( omt_pos, range, false );
    om_range_mark( omt_pos, min_range, false, "Y;X: MIN RANGE" );
    if( where == overmap::invalid_tripoint ) {
        return tripoint_abs_omt( -999, -999, -999 );
    }
    int dist = rl_dist( where.xy(), omt_pos.xy() );
    if( dist > range || dist < min_range ) {
        popup( _( "You must select a target between %d and %d range from the base.  Range: %d" ),
               min_range, range, dist );
        errors = true;
    }
    tripoint_abs_omt omt_tgt = where;
    const oter_id &omt_ref = overmap_buffer.ter( omt_tgt );
    if( must_see && !overmap_buffer.seen( omt_tgt ) ) {
        errors = true;
        popup( _( "You must be able to see the target that you select." ) );
    }
    if( !errors ) {
        for( const std::string &pos_om : bounce_locations ) {
            if( bounce && omt_ref.id().c_str() == pos_om && range > 5 ) {
                if( query_yn( _( "Do you want to bounce off this location to extend range?" ) ) ) {
                    om_line_mark( omt_pos, omt_tgt );
                    tripoint_abs_omt dest =
                        om_target_tile( omt_tgt, 2, range * .75, possible_om_types, true, false,
                                        omt_tgt, true );
                    om_line_mark( omt_pos, omt_tgt, false );
                    return dest;
                }
            }
        }
        if( possible_om_types.empty() ) {
            return omt_tgt;
        }
        for( const std::string &pos_om : possible_om_types ) {
            if( omt_ref.id().c_str() == pos_om ) {
                return omt_tgt;
            }
        }
    }
    return om_target_tile( omt_pos, min_range, range, possible_om_types );
}
References _, string_id< T >::c_str(), ui::omap::choose_point(), int_id< T >::id(), overmap::invalid_tripoint, om_line_mark(), om_range_mark(), om_target_tile(), overmap_buffer, popup(), query_yn(), rl_dist(), overmapbuffer::seen(), overmapbuffer::ter(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by om_companion_path(), om_target_tile(), basecamp::start_clearcut(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
survive_random_encounter()
bool survive_random_encounter (npc & comp, std::string & situation, int favor, int threat)
Definition at line 4036 of file faction_camp.cpp.
{
    popup( _( "While %s, a silent specter approaches %s" ), situation, comp.name );
    int skill_1 = comp.get_skill_level( skill_survival );
    int skill_2 = comp.get_skill_level( skill_speech );
    if( skill_1 + favor > rng( 0, 10 ) ) {
        popup( _( "%s notices the antlered horror and slips away before it gets too close." ),
               comp.name );
        talk_function::companion_skill_trainer( comp, "gathering", 10_minutes, 10 - favor );
    } else if( skill_2 + favor > rng( 0, 10 ) ) {
        popup( _( "Another survivor approaches %s asking for directions." ), comp.name );
        popup( _( "Fearful that he may be an agent of some hostile faction, "
                  "%s doesn't mention the camp." ), comp.name );
        popup( _( "The two part on friendly terms and the survivor isn't seen again." ) );
        talk_function::companion_skill_trainer( comp, "recruiting", 10_minutes, 10 - favor );
    } else {
        popup( _( "%s didn't detect the ambush until it was too late!" ), comp.name );
        int skill = comp.get_skill_level( skill_melee ) +
                    0.5 * comp.get_skill_level( skill_survival ) +
                    comp.get_skill_level( skill_bashing ) +
                    comp.get_skill_level( skill_cutting ) +
                    comp.get_skill_level( skill_stabbing ) +
                    comp.get_skill_level( skill_unarmed ) + comp.get_skill_level( skill_dodge );
        int monsters = rng( 0, threat );
        if( skill * rng( 8, 12 ) > ( monsters * rng( 8, 12 ) ) ) {
            if( one_in( 2 ) ) {
                popup( _( "The bull moose charged %s from the tree line" ), comp.name );
                popup( _( "Despite being caught off guard %s was able to run away until the "
                          "moose gave up pursuit." ), comp.name );
            } else {
                popup( _( "The jabberwock grabbed %s by the arm from behind and "
                          "began to scream." ), comp.name );
                popup( _( "Terrified, %s spun around and delivered a massive kick "
                          "to the creature's torso" ), comp.name );
                popup( _( "Collapsing into a pile of gore, %s walked away unscathed" ),
                       comp.name );
                popup( _( "(Sounds like bullshit, you wonder what really happened.)" ) );
            }
            talk_function::companion_skill_trainer( comp, "combat", 10_minutes, 10 - favor );
        } else {
            if( one_in( 2 ) ) {
                popup( _( "%s turned to find the hideous black eyes of a giant wasp "
                          "staring back from only a few feet away" ), comp.name );
                popup( _( "The screams were terrifying, there was nothing anyone could do." ) );
            } else {
                popup( _( "Pieces of %s were found strewn across a few bushes." ), comp.name );
                popup( _( "(You wonder if your companions are fit to work on their own)" ) );
            }
            overmap_buffer.remove_npc( comp.getID() );
            return false;
        }
    }
    return true;
}
References _, talk_function::companion_skill_trainer(), Character::get_skill_level(), Character::getID(), Character::name, one_in(), overmap_buffer, popup(), overmapbuffer::remove_npc(), rng(), skill_bashing, skill_cutting, skill_dodge, skill_melee, skill_speech, skill_stabbing, skill_survival, and skill_unarmed.
Referenced by basecamp::gathering_return().
time_to_food()
int time_to_food (time_duration work)
Returns the total charges of food time_duration work costs.
Definition at line 3880 of file faction_camp.cpp.
{
    return 2500 * to_hours<int>( work ) / 24;
}
Referenced by camp_food_supply(), basecamp::finish_return(), basecamp::recipe_batch_max(), basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_menial_labor(), basecamp::start_mission(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
update_time_fixed()
static bool update_time_fixed (std::string & entry, const comp_list & npc_list, const time_duration & duration) static
Definition at line 495 of file faction_camp.cpp.
{
    bool avail = false;
    for( auto &comp : npc_list ) {
        time_duration elapsed = calendar::turn - comp->companion_mission_time;
        entry = entry + " " +  comp->name + " [" + to_string( elapsed ) + "/" +
                to_string( duration ) + "]\n";
        avail |= elapsed >= duration;
    }
    entry = entry + _( "\n\nDo you wish to bring your allies back into your party?" );
    return avail;
}
References _, npc::companion_mission_time, Character::name, to_string(), and calendar::turn.
Referenced by basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
update_time_left()
static bool update_time_left (std::string & entry, const comp_list & npc_list) static
Definition at line 477 of file faction_camp.cpp.
{
    bool avail = false;
    for( auto &comp : npc_list ) {
        if( comp->companion_mission_time_ret < calendar:: turn ) {
            entry = entry +  _( " [DONE]\n" );
            avail = true;
        } else {
            entry = entry + " [" +
                    to_string( comp->companion_mission_time_ret - calendar::turn ) +
                    _( " left]\n" );
            avail = g->u.has_trait( trait_DEBUG_HS );
        }
    }
    entry = entry + _( "\n\nDo you wish to bring your allies back into your party?" );
    return avail;
}
References _, npc::companion_mission_time_ret, g, to_string(), trait_DEBUG_HS, and calendar::turn.
Referenced by basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
Variable Documentation
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
Referenced by basecamp::start_menial_labor().
itype_fungal_seeds
const itype_id itype_fungal_seeds("fungal_seeds") ("fungal_seeds") static
Referenced by farm_valid_seed().
itype_log
const itype_id itype_log("log") ("log") static
Referenced by om_cutdown_trees().
itype_marloss_seed
const itype_id itype_marloss_seed("marloss_seed") ("marloss_seed") static
Referenced by farm_valid_seed().
mon_bear
const mtype_id mon_bear("mon_bear") ("mon_bear") static
Referenced by basecamp::hunting_results().
mon_beaver
const mtype_id mon_beaver("mon_beaver") ("mon_beaver") static
Referenced by basecamp::hunting_results().
mon_black_rat
const mtype_id mon_black_rat("mon_black_rat") ("mon_black_rat") static
Referenced by basecamp::hunting_results().
mon_chicken
const mtype_id mon_chicken("mon_chicken") ("mon_chicken") static
Referenced by basecamp::hunting_results().
mon_chipmunk
const mtype_id mon_chipmunk("mon_chipmunk") ("mon_chipmunk") static
Referenced by basecamp::hunting_results().
mon_cockatrice
const mtype_id mon_cockatrice("mon_cockatrice") ("mon_cockatrice") static
Referenced by basecamp::hunting_results().
mon_cougar
const mtype_id mon_cougar("mon_cougar") ("mon_cougar") static
Referenced by basecamp::hunting_results().
mon_cow
const mtype_id mon_cow("mon_cow") ("mon_cow") static
Referenced by basecamp::hunting_results().
mon_coyote
const mtype_id mon_coyote("mon_coyote") ("mon_coyote") static
Referenced by basecamp::hunting_results().
mon_deer
const mtype_id mon_deer("mon_deer") ("mon_deer") static
Referenced by basecamp::hunting_results().
mon_duck
const mtype_id mon_duck("mon_duck") ("mon_duck") static
Referenced by basecamp::hunting_results().
mon_fox_gray
const mtype_id mon_fox_gray("mon_fox_gray") ("mon_fox_gray") static
Referenced by basecamp::hunting_results().
mon_fox_red
const mtype_id mon_fox_red("mon_fox_red") ("mon_fox_red") static
Referenced by basecamp::hunting_results().
mon_groundhog
const mtype_id mon_groundhog("mon_groundhog") ("mon_groundhog") static
Referenced by basecamp::hunting_results().
mon_grouse
const mtype_id mon_grouse("mon_grouse") ("mon_grouse") static
Referenced by basecamp::hunting_results().
mon_hare
const mtype_id mon_hare("mon_hare") ("mon_hare") static
Referenced by basecamp::hunting_results().
mon_lemming
const mtype_id mon_lemming("mon_lemming") ("mon_lemming") static
Referenced by basecamp::hunting_results().
mon_mink
const mtype_id mon_mink("mon_mink") ("mon_mink") static
Referenced by basecamp::hunting_results().
mon_moose
const mtype_id mon_moose("mon_moose") ("mon_moose") static
Referenced by basecamp::hunting_results().
mon_muskrat
const mtype_id mon_muskrat("mon_muskrat") ("mon_muskrat") static
Referenced by basecamp::hunting_results().
mon_opossum
const mtype_id mon_opossum("mon_opossum") ("mon_opossum") static
Referenced by basecamp::hunting_results().
mon_otter
const mtype_id mon_otter("mon_otter") ("mon_otter") static
Referenced by basecamp::hunting_results().
mon_pheasant
const mtype_id mon_pheasant("mon_pheasant") ("mon_pheasant") static
Referenced by basecamp::hunting_results().
mon_pig
const mtype_id mon_pig("mon_pig") ("mon_pig") static
Referenced by basecamp::hunting_results().
mon_rabbit
const mtype_id mon_rabbit("mon_rabbit") ("mon_rabbit") static
Referenced by basecamp::hunting_results().
mon_squirrel
const mtype_id mon_squirrel("mon_squirrel") ("mon_squirrel") static
Referenced by basecamp::hunting_results().
mon_turkey
const mtype_id mon_turkey("mon_turkey") ("mon_turkey") static
Referenced by basecamp::hunting_results().
mon_weasel
const mtype_id mon_weasel("mon_weasel") ("mon_weasel") static
Referenced by basecamp::hunting_results().
mon_wolf
const mtype_id mon_wolf("mon_wolf") ("mon_wolf") static
Referenced by basecamp::hunting_results().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by skill_by_dt(), and survive_random_encounter().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by skill_by_dt(), and survive_random_encounter().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by survive_random_encounter().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by basecamp::gathering_return(), and basecamp::handle_mission().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by basecamp::start_garage_chop().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by survive_random_encounter().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by basecamp::recruit_return(), and survive_random_encounter().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by skill_by_dt(), and survive_random_encounter().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by farm_action(), basecamp::gathering_return(), basecamp::handle_mission(), basecamp::recruit_return(), basecamp::start_combat_mission(), basecamp::start_farm_op(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), and survive_random_encounter().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by basecamp::combat_mission_return().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by basecamp::gathering_return(), and basecamp::handle_mission().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by survive_random_encounter().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by update_time_left().
zone_type_camp_food
const zone_type_id zone_type_camp_food("CAMP_FOOD") ("CAMP_FOOD") static
Referenced by basecamp::distribute_food(), and basecamp::validate_sort_points().
zone_type_camp_storage
const zone_type_id zone_type_camp_storage("CAMP_STORAGE") ("CAMP_STORAGE") static
Referenced by talk_function::basecamp_mission(), basecamp::place_results(), and basecamp::validate_sort_points().