Cataclysm BN: src/filesystem.cpp File Reference
filesystem.cpp File Reference
#include "filesystem.h"
#include <sys/stat.h>
#include <cstdlib>
#include <algorithm>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <deque>
#include <fstream>
#include <string>
#include <vector>
#include <iterator>
#include <utility>
#include "debug.h"
#include "catacharset.h"
#include "fstream_utils.h"
#include "string_utils.h"
#include <dirent.h>
#include <unistd.h>
Namespaces
namespace anonymous_namespace{filesystem.cpp}
Macros
#define dbg(x) DebugLog((x), DC::Main)
Functions
static bool do_mkdir (const std::string &path)
bool assure_dir_exist (const std::string &path)
Create directory if it does not exist.
bool dir_exist (const std::string &path)
Check if directory exists.
bool file_exist (const std::string &path)
Check if file exists.
bool remove_file (const std::string &path)
Remove a file.
bool rename_file (const std::string &old_path, const std::string &new_path)
Rename a file, overwriting the target.
bool remove_directory (const std::string &path)
Remove an empty directory.
std::string read_entire_file (const std::string &path)
Read entire file to string.
template<typename T , size_t N>
size_t anonymous_namespace{filesystem.cpp}::sizeof_array (T const(&)[N]) noexcept
template<typename Function >
void anonymous_namespace{filesystem.cpp}::for_each_dir_entry (const std::string &path, Function function)
std::string anonymous_namespace{filesystem.cpp}::resolve_path (const std::string &full_path)
bool anonymous_namespace{filesystem.cpp}::is_directory_stat (const std::string &full_path)
bool anonymous_namespace{filesystem.cpp}::is_directory (const dirent &entry, const std::string &full_path)
bool anonymous_namespace{filesystem.cpp}::is_special_dir (const dirent &entry)
bool anonymous_namespace{filesystem.cpp}::name_contains (const dirent &entry, const std::string &match, const bool at_end)
template<typename Predicate >
std::vector< std::string > anonymous_namespace{filesystem.cpp}::find_file_if_bfs (const std::string &root_path, const bool recursive_search, Predicate predicate)
std::vector< std::string > get_files_from_path (const std::string &pattern, const std::string &root_path, const bool recursive_search, const bool match_extension)
Returns a vector of files or directories matching pattern at root_path.
std::vector< std::string > get_directories_with (const std::string &pattern, const std::string &root_path, const bool recursive_search)
Find directories which containing pattern.
std::vector< std::string > get_directories_with (const std::vector< std::string > &patterns, const std::string &root_path, const bool recursive_search)
Find directories which containing pattern.
bool copy_file (const std::string &source_path, const std::string &dest_path)
Copy file, overwriting the target.
std::string ensure_valid_file_name (const std::string &file_name)
Replace invalid characters in a string with a default character; can be used to ensure that a file name is compliant with most file systems.
bool can_write_to_dir (const std::string &dir_path)
Check if can write to the given directory (write permission, disk space).
std::string get_pid_string ()
Get process id string.
Variables
const char * CBN = "Q2F0YWNseXNtQnJpZ2h0TmlnaHRz"
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x), DC::Main)
Definition at line 34 of file filesystem.cpp.
Function Documentation
assure_dir_exist()
bool assure_dir_exist (const std::string & path)
Create directory if it does not exist.
Returns
true if directory exists or was successfully created.
Definition at line 48 of file filesystem.cpp.
{
    if( dir_exist( path ) ) {
        return true;
    }
    return do_mkdir( path );
}
References dir_exist(), and do_mkdir().
Referenced by main(), game::move_save_to_graveyard(), main_menu::opening_screen(), mapbuffer::save(), WORLD::save(), map_memory::save(), mapbuffer::save_quad(), and game::write_memorial_file().
can_write_to_dir()
bool can_write_to_dir (const std::string & dir_path)
Check if can write to the given directory (write permission, disk space).
Returns
false if cannot write or if unable to check.
Definition at line 466 of file filesystem.cpp.
{
    std::string dummy_file;
    if( string_ends_with( dir_path, "/" ) ) {
        dummy_file = dir_path + CBN;
    } else {
        dummy_file = dir_path + "/" + CBN;
    }
    if( file_exist( dummy_file ) ) {
        if( !remove_file( dummy_file ) ) {
            return false;
        }
    }
    const auto writer = []( std::ostream & s ) {
        // Write at least something to check if there is free space on disk
        s << CBN << std::endl;
    };
    if( !write_to_file( dummy_file, writer, nullptr ) ) {
        return false;
    }
    return remove_file( dummy_file );
}
References CBN, file_exist(), remove_file(), string_ends_with(), and write_to_file().
Referenced by main().
copy_file()
bool copy_file (const std::string & source_path, const std::string & dest_path)
Copy file, overwriting the target.
Does not overwrite directories.
Returns
true on success, false on failure.
Definition at line 432 of file filesystem.cpp.
{
    cata_ifstream source_stream = std::move( cata_ifstream().mode( cata_ios_mode::binary ).open(
                                      source_path ) );
    if( !source_stream.is_open() ) {
        return false;
    }
    bool res = write_to_file( dest_path, [&]( std::ostream & dest_stream ) {
        dest_stream << source_stream->rdbuf();
    }, nullptr );
    return res && !source_stream.fail();
}
References binary, cata_ifstream::fail(), cata_ifstream::is_open(), avatar_action::move(), open(), and write_to_file().
Referenced by font_loader::load(), and color_loader< ColorType >::load().
dir_exist()
bool dir_exist (const std::string & path)
Check if directory exists.
Returns
false if directory does not exist or if unable to check.
Definition at line 56 of file filesystem.cpp.
{
    DIR *dir = opendir( path.c_str() );
    if( dir != nullptr ) {
        closedir( dir );
        return true;
    }
    return false;
}
References closedir(), and opendir().
Referenced by assure_dir_exist(), map_memory::load(), map_memory::load_submap(), main(), and ofstream_wrapper::open().
do_mkdir()
static bool do_mkdir (const std::string & path) static
Definition at line 42 of file filesystem.cpp.
{
    return mkdir( path.c_str(), 0777 ) == 0;
}
Referenced by assure_dir_exist().
ensure_valid_file_name()
std::string ensure_valid_file_name (const std::string & file_name)
Replace invalid characters in a string with a default character; can be used to ensure that a file name is compliant with most file systems.
Parameters
file_name Name of the file to check.
Returns
A string with all invalid characters replaced with the replacement character, if any change was made.
Note
The default replacement character is space (0x20) and the invalid characters are "\\/:?\"<>|".
Definition at line 445 of file filesystem.cpp.
{
    const char replacement_char = ' ';
    const std::string invalid_chars = "\\/:?\"<>|";
    // do any replacement in the file name, if needed.
    std::string new_file_name = file_name;
    std::transform( new_file_name.begin(), new_file_name.end(),
    new_file_name.begin(), [&]( const char c ) {
        if( invalid_chars.find( c ) != std::string::npos ) {
            return replacement_char;
        }
        return c;
    } );
    return new_file_name;
}
References c, and iexamine::transform().
Referenced by generate_memorial_filename(), and avatar::save_template().
file_exist()
bool file_exist (const std::string & path)
Check if file exists.
Returns
false if file does not exist or if unable to check.
Definition at line 75 of file filesystem.cpp.
{
    struct stat buffer;
    bool success = stat( path.c_str(), &buffer ) == 0;
    return success && S_ISREG( buffer.st_mode );
}
References S_ISREG, and behavior::success.
Referenced by l10n_data::add_cat_if_exists(), can_write_to_dir(), find_translated_file(), overmapbuffer::get_existing(), font_loader::load(), map_memory::load(), color_loader< ColorType >::load(), ofstream_wrapper::open(), read_from_file_optional(), auto_notes::auto_note_settings::save(), auto_pickup::player_settings::save(), safemode::save(), translations_exists_for_lang(), and mapbuffer::unserialize_submaps().
get_directories_with() [1/2]
std::vector< std::string > get_directories_with (const std::string & pattern, const std::string & root_path, const bool recursive_search)
Find directories which containing pattern.
Parameters
pattern Search pattern.
root_path Search root.
recursive_search Be recurse or not.
Returns
vector or directories without pattern filename at end.
Definition at line 377 of file filesystem.cpp.
{
    if( pattern.empty() ) {
        return std::vector<std::string>();
    }
    auto files = find_file_if_bfs( root_path, recursive_search, [&]( const dirent & entry, bool ) {
        return name_contains( entry, pattern, true );
    } );
    // Chop off the file names. Dir path MUST be splitted by '/'
    for( auto &file : files ) {
        file.erase( file.rfind( '/' ), std::string::npos );
    }
    files.erase( std::unique( std::begin( files ), std::end( files ) ), std::end( files ) );
    return files;
}
References file, anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
Referenced by build_resource_list(), and worldfactory::init().
get_directories_with() [2/2]
std::vector< std::string > get_directories_with (const std::vector< std::string > & patterns, const std::string & root_path, const bool recursive_search)
Find directories which containing pattern.
Returns a vector of directories which contain files matching any of patterns.
Parameters
patterns Search patterns.
root_path Search root.
recursive_search Be recurse or not.
Returns
vector or directories without pattern filename at end.
Definition at line 405 of file filesystem.cpp.
{
    if( patterns.empty() ) {
        return std::vector<std::string>();
    }
    const auto ext_beg = std::begin( patterns );
    const auto ext_end = std::end( patterns );
    auto files = find_file_if_bfs( root_path, recursive_search, [&]( const dirent & entry, bool ) {
        return std::any_of( ext_beg, ext_end, [&]( const std::string & ext ) {
            return name_contains( entry, ext, true );
        } );
    } );
    //chop off the file names
    for( auto &file : files ) {
        file.erase( file.rfind( '/' ), std::string::npos );
    }
    //remove resulting duplicates
    files.erase( std::unique( std::begin( files ), std::end( files ) ), std::end( files ) );
    return files;
}
References file, anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
get_files_from_path()
std::vector< std::string > get_files_from_path (const std::string & pattern, const std::string & root_path = "", bool recursive_search = false, bool match_extension = false)
Returns a vector of files or directories matching pattern at root_path.
Searches through the directory tree breadth-first. Directories are searched in lexical order. Matching files within in each directory are also ordered lexically.
Parameters
pattern The sub-string to match.
root_path The path relative to the current working directory to search; empty means ".".
recursive_search Whether to recursively search sub directories.
match_extension If true, match pattern at the end of file names. Otherwise, match anywhere in the file name.
Definition at line 362 of file filesystem.cpp.
{
    return find_file_if_bfs( root_path, recursive_search, [&]( const dirent & entry, bool ) {
        return name_contains( entry, pattern, match_extension );
    } );
}
References anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
Referenced by worldfactory::delete_world(), worldfactory::init(), main_menu::load_char_templates(), DynamicDataLoader::load_data_from_path(), mod_management::load_mods_from(), game::move_save_to_graveyard(), and color_manager::show_gui().
get_pid_string()
std::string get_pid_string ()
Get process id string.
Used for temporary file paths.
Definition at line 493 of file filesystem.cpp.
{
#if defined _WIN32
    return std::to_string( GetCurrentProcessId() );
#else
    return std::to_string( getpid() );
#endif
}
References to_string().
Referenced by ofstream_wrapper::open().
read_entire_file()
std::string read_entire_file (const std::string & path)
Read entire file to string.
Returns
empty string on failure.
Definition at line 131 of file filesystem.cpp.
{
    cata_ifstream infile;
    infile.mode( cata_ios_mode::binary ).open( path );
    if( !infile.is_open() ) {
        return "";
    }
    std::string ret = std::string( std::istreambuf_iterator<char>( *infile ),
                                   std::istreambuf_iterator<char>() );
    if( infile.fail() ) {
        return "";
    }
    return ret;
}
References binary, cata_ifstream::fail(), cata_ifstream::is_open(), cata_ifstream::mode(), cata_ifstream::open(), and cata::hash64_detail::ret.
Referenced by DynamicDataLoader::get_cached_stream().
remove_directory()
bool remove_directory (const std::string & path)
Remove an empty directory.
Returns
true on success, false on failure (e.g. directory is not empty).
Definition at line 111 of file filesystem.cpp.
{
#if defined(_WIN32)
    return RemoveDirectoryW( utf8_to_wstr( path ).c_str() ) != 0;
#else
    return remove( path.c_str() ) == 0;
#endif
}
References utf8_to_wstr().
Referenced by worldfactory::delete_world().
remove_file()
bool remove_file (const std::string & path)
Remove a file.
Does not remove directories.
Returns
true on success.
Definition at line 89 of file filesystem.cpp.
{
    return unlink( path.c_str() ) == 0;
}
Referenced by can_write_to_dir(), ofstream_wrapper::close(), worldfactory::delete_world(), input_manager::init(), game::move_save_to_graveyard(), main_menu::new_character_tab(), ofstream_wrapper::open(), and mod_manager::save_mods_list().
rename_file()
bool rename_file (const std::string & old_path, const std::string & new_path)
Rename a file, overwriting the target.
Does not overwrite directories.
Returns
true on success, false on failure.
Definition at line 105 of file filesystem.cpp.
{
    return rename( old_path.c_str(), new_path.c_str() ) == 0;
}
Referenced by ofstream_wrapper::close(), DebugFile::init(), and game::move_save_to_graveyard().
Variable Documentation
CBN
const char* CBN = "Q2F0YWNseXNtQnJpZ2h0TmlnaHRz"
Definition at line 464 of file filesystem.cpp.
Referenced by can_write_to_dir().