Cataclysm BN: src/fmtlib_format-inl.h File Reference
fmtlib_format-inl.h File Reference
#include <cassert>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstdarg>
#include <cstring>
#include <cwchar>
#include <exception>
#include <locale>
#include "fmtlib_format.h"
Classes
struct detail::bits< T >
struct detail::boundaries
class detail::fp
struct detail::accumulator
class detail::bigint
struct detail::fixed_handler
struct detail::dragonbox::cache_accessor< float >
struct detail::dragonbox::cache_accessor< double >
struct detail::stringifier
struct formatter< detail::bigint >
Namespaces
namespace detail
namespace detail::digits
namespace detail::dragonbox
Macros
#define CATA_SRC_FMTLIB_FORMAT_INL_H
#define FMT_SNPRINTF snprintf
#define FMT_POWERS_OF_10(factor)
Enumerations
enum class detail::round_direction { detail::unknown , detail::up , detail::down }
enum detail::digits::result { detail::digits::more , detail::digits::done , detail::digits::error }
Functions
fmt::detail::null strerror_r (int, char *,...)
fmt::detail::null strerror_s (char *, size_t,...)
FMT_NORETURN FMT_API void detail::assert_fail (const char *file, int line, const char *message)
int detail::safe_strerror (int error_code, char *&buffer, size_t buffer_size) FMT_NOEXCEPT
FMT_FUNC void detail::format_error_code (detail::buffer< char > &out, int error_code, string_view message) FMT_NOEXCEPT
FMT_FUNC void detail::report_error (format_func func, int error_code, string_view message) FMT_NOEXCEPT
void detail::fwrite_fully (const void *ptr, size_t size, size_t count, FILE *stream)
template<typename Char >
FMT_FUNC std::string detail::grouping_impl (locale_ref loc)
template<typename Char >
FMT_FUNC Char detail::thousands_sep_impl (locale_ref loc)
template<typename Char >
FMT_FUNC Char detail::decimal_point_impl (locale_ref loc)
template<>
FMT_FUNC int detail::count_digits< 4 > (detail::fallback_uintptr n)
template<int SHIFT = 0>
fp detail::normalize (fp value)
bool detail::operator== (fp x, fp y)
uint64_t detail::multiply (uint64_t lhs, uint64_t rhs)
fp detail::operator* (fp x, fp y)
fp detail::get_cached_power (int min_exponent, int &pow10_exponent)
round_direction detail::get_round_direction (uint64_t divisor, uint64_t remainder, uint64_t error)
template<typename Handler >
FMT_ALWAYS_INLINE digits::result detail::grisu_gen_digits (fp value, uint64_t error, int &exp, Handler &handler)
FMT_SAFEBUFFERS uint128_wrapper detail::dragonbox::umul128 (uint64_t x, uint64_t y) FMT_NOEXCEPT
FMT_SAFEBUFFERS uint64_t detail::dragonbox::umul128_upper64 (uint64_t x, uint64_t y) FMT_NOEXCEPT
FMT_SAFEBUFFERS uint64_t detail::dragonbox::umul192_upper64 (uint64_t x, uint128_wrapper y) FMT_NOEXCEPT
uint32_t detail::dragonbox::umul96_upper32 (uint32_t x, uint64_t y) FMT_NOEXCEPT
FMT_SAFEBUFFERS uint64_t detail::dragonbox::umul192_middle64 (uint64_t x, uint128_wrapper y) FMT_NOEXCEPT
uint64_t detail::dragonbox::umul96_lower64 (uint32_t x, uint64_t y) FMT_NOEXCEPT
int detail::dragonbox::floor_log10_pow2 (int e) FMT_NOEXCEPT
int detail::dragonbox::floor_log2_pow10 (int e) FMT_NOEXCEPT
int detail::dragonbox::floor_log10_pow2_minus_log10_4_over_3 (int e) FMT_NOEXCEPT
bool detail::dragonbox::divisible_by_power_of_2 (uint32_t x, int exp) FMT_NOEXCEPT
bool detail::dragonbox::divisible_by_power_of_2 (uint64_t x, int exp) FMT_NOEXCEPT
bool detail::dragonbox::divisible_by_power_of_5 (uint32_t x, int exp) FMT_NOEXCEPT
bool detail::dragonbox::divisible_by_power_of_5 (uint64_t x, int exp) FMT_NOEXCEPT
template<int N>
bool detail::dragonbox::check_divisibility_and_divide_by_pow5 (uint32_t &n) FMT_NOEXCEPT
template<int N>
uint32_t detail::dragonbox::small_division_by_pow10 (uint32_t n) FMT_NOEXCEPT
uint32_t detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint32_t n) FMT_NOEXCEPT
uint64_t detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint64_t n) FMT_NOEXCEPT
template<class T >
bool detail::dragonbox::is_left_endpoint_integer_shorter_interval (int exponent) FMT_NOEXCEPT
template<class T >
bool detail::dragonbox::is_endpoint_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k) FMT_NOEXCEPT
template<class T >
bool detail::dragonbox::is_center_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k) FMT_NOEXCEPT
FMT_ALWAYS_INLINE int detail::dragonbox::remove_trailing_zeros (uint32_t &n) FMT_NOEXCEPT
FMT_ALWAYS_INLINE int detail::dragonbox::remove_trailing_zeros (uint64_t &n) FMT_NOEXCEPT
template<class T >
FMT_ALWAYS_INLINE FMT_SAFEBUFFERS decimal_fp< T > detail::dragonbox::shorter_interval_case (int exponent) FMT_NOEXCEPT
template<typename T >
FMT_SAFEBUFFERS decimal_fp< T > detail::dragonbox::to_decimal (T x) FMT_NOEXCEPT
template<typename Double >
void detail::fallback_format (Double d, int num_digits, bool binary32, buffer< char > &buf, int &exp10)
template<typename T >
int detail::format_float (T value, int precision, float_specs specs, buffer< char > &buf)
template<typename T >
int detail::snprintf_float (T value, int precision, float_specs specs, buffer< char > &buf)
const char * detail::utf8_decode (const char *buf, uint32_t *c, int *e)
FMT_FUNC void format_system_error (detail::buffer< char > &out, int error_code, string_view message) FMT_NOEXCEPT
\rst Formats an error returned by an operating system or a language runtime, for example a file opening error, and writes it to out in the following form:
FMT_FUNC void report_system_error (int error_code, fmt::string_view message) FMT_NOEXCEPT
FMT_FUNC void vprint (std::FILE *f, string_view format_str, format_args args)
FMT_FUNC void vprint (string_view format_str, format_args args)
Macro Definition Documentation
CATA_SRC_FMTLIB_FORMAT_INL_H
#define CATA_SRC_FMTLIB_FORMAT_INL_H
Definition at line 10 of file fmtlib_format-inl.h.
FMT_POWERS_OF_10
#define FMT_POWERS_OF_10 (factor)
Value:
    factor * 10, (factor)*100, (factor)*1000, (factor)*10000, (factor)*100000, \
    (factor)*1000000, (factor)*10000000, (factor)*100000000,               \
    (factor)*1000000000
Definition at line 301 of file fmtlib_format-inl.h.
FMT_SNPRINTF
#define FMT_SNPRINTF snprintf
Definition at line 59 of file fmtlib_format-inl.h.
Function Documentation
format_system_error()
FMT_FUNC void format_system_error (detail::buffer< char > & out, int error_code, string_view message)
\rst Formats an error returned by an operating system or a language runtime, for example a file opening error, and writes it to out in the following form:
.. parsed-literal:: <message>*: *<system-message>*
where *<message>* is the passed message and *<system-message>* is the system message corresponding to the error code. error_code* is a system error code as given by errno. If error_code is not a valid error code such as -1, the system message may look like "Unknown error -1" and is platform-dependent. \endrst
Definition at line 2957 of file fmtlib_format-inl.h.
{
    FMT_TRY {
        memory_buffer buf;
        buf.resize( inline_buffer_size );
        for( ;; )
        {
            char *system_message = &buf[0];
            int result =
            detail::safe_strerror( error_code, system_message, buf.size() );
            if( result == 0 ) {
                format_to( detail::buffer_appender<char>( out ), "{}: {}", message,
                           system_message );
                return;
            }
            if( result != ERANGE ) {
                break;    // Can't get error message, report error code instead.
            }
            buf.resize( buf.size() * 2 );
        }
    }
    FMT_CATCH( ... ) {}
    format_error_code( out, error_code, message );
}
References FMT_CATCH, FMT_TRY, detail::format_error_code(), format_to(), inline_buffer_size, mapgen_defer::message, basic_memory_buffer< T, SIZE, Allocator >::resize(), detail::safe_strerror(), and detail::buffer< T >::size().
Referenced by system_error::init(), and report_system_error().
report_system_error()
FMT_FUNC void report_system_error (int error_code, fmt::string_view message)
Definition at line 2989 of file fmtlib_format-inl.h.
{
    report_error( format_system_error, error_code, message );
}
References format_system_error(), mapgen_defer::message, and detail::report_error().
strerror_r()
fmt::detail::null strerror_r (int , char * , ...) inline
Definition at line 34 of file fmtlib_format-inl.h.
{
    return {};
}
Referenced by detail::safe_strerror().
strerror_s()
fmt::detail::null strerror_s (char * , size_t , ...) inline
Definition at line 39 of file fmtlib_format-inl.h.
{
    return {};
}
Referenced by detail::safe_strerror().
vprint() [1/2]
FMT_FUNC void vprint (std::FILE * f, string_view format_str, format_args args)
Definition at line 3019 of file fmtlib_format-inl.h.
{
    memory_buffer buffer;
    detail::vformat_to( buffer, format_str,
                        basic_format_args<buffer_context<char>>( args ) );
#ifdef _WIN32
    auto fd = _fileno( f );
    if( _isatty( fd ) ) {
        detail::utf8_to_utf16 u16( string_view( buffer.data(), buffer.size() ) );
        auto written = detail::dword();
        if( !detail::WriteConsoleW( reinterpret_cast<void *>( _get_osfhandle( fd ) ),
                                    u16.c_str(), static_cast<uint32_t>( u16.size() ),
                                    &written, nullptr ) ) {
            FMT_THROW( format_error( "failed to write to console" ) );
        }
        return;
    }
#endif
    detail::fwrite_fully( buffer.data(), 1, buffer.size(), f );
}
References detail::utf8_to_utf16::c_str(), detail::buffer< T >::data(), FMT_THROW, detail::fwrite_fully(), detail::utf8_to_utf16::size(), detail::buffer< T >::size(), and detail::vformat_to().
Referenced by vprint().
vprint() [2/2]
FMT_FUNC void vprint (string_view format_str, format_args args)
Definition at line 3053 of file fmtlib_format-inl.h.
{
    vprint( stdout, format_str, args );
}
References vprint().
Referenced by print().