Cataclysm BN: src/fmtlib_printf.h File Reference
fmtlib_printf.h File Reference
#include <algorithm>
#include <limits>
#include "fmtlib_ostream.h"
Classes
struct detail::int_checker< IsSigned >
struct detail::int_checker< true >
class detail::printf_precision_handler
class detail::is_zero_int
struct detail::make_unsigned_or_bool< T >
struct detail::make_unsigned_or_bool< bool >
class detail::arg_converter< T, Context >
class detail::char_converter< Context >
struct detail::get_cstring< Char >
class detail::printf_width_handler< Char >
class basic_printf_parse_context< Char >
class printf_arg_formatter< OutputIt, Char >
\rst The printf argument formatter.
struct printf_formatter< T >
class basic_printf_context< OutputIt, Char >
This template formats data and writes the output through an output iterator.
Namespaces
namespace detail
Macros
#define CATA_SRC_FMTLIB_PRINTF_H
Typedefs
template<typename Char >
using basic_printf_context_t = basic_printf_context< detail::buffer_appender< Char >, Char >
using printf_context = basic_printf_context_t< char >
using wprintf_context = basic_printf_context_t< wchar_t >
using printf_args = basic_format_args< printf_context >
using wprintf_args = basic_format_args< wprintf_context >
Functions
template<typename T , typename Context , typename Char >
void detail::convert_arg (basic_format_arg< Context > &arg, Char type)
template<typename Char , typename Context >
void detail::vprintf (buffer< Char > &buf, basic_string_view< Char > format, basic_format_args< Context > args)
template<typename Char , typename Context >
FMT_DEPRECATED void printf (detail::buffer< Char > &buf, basic_string_view< Char > format, basic_format_args< Context > args)
template<typename... Args>
format_arg_store< printf_context, Args... > make_printf_args (const Args &... args)
\rst Constructs an ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtprintf_args.
template<typename... Args>
format_arg_store< wprintf_context, Args... > make_wprintf_args (const Args &... args)
\rst Constructs an ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtwprintf_args.
template<typename S , typename Char = char_t<S>>
std::basic_string< Char > vsprintf (const S &format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args)
template<typename S , typename... Args, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>>
std::basic_string< Char > sprintf (const S &format, const Args &... args)
\rst Formats arguments and returns the result as a string.
template<typename S , typename Char = char_t<S>>
int vfprintf (std::FILE *f, const S &format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args)
template<typename S , typename... Args, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>>
int fprintf (std::FILE *f, const S &format, const Args &... args)
\rst Prints formatted data to the file f.
template<typename S , typename Char = char_t<S>>
int vprintf (const S &format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args)
template<typename S , typename... Args, FMT_ENABLE_IF(detail::is_string< S >::value) >
int printf (const S &format_str, const Args &... args)
\rst Prints formatted data to stdout.
template<typename S , typename Char = char_t<S>>
int vfprintf (std::basic_ostream< Char > &os, const S &format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args)
template<typename ArgFormatter , typename Char , typename Context = basic_printf_context<typename ArgFormatter::iterator, Char>>
ArgFormatter::iterator vprintf (detail::buffer< Char > &out, basic_string_view< Char > format_str, basic_format_args< type_identity_t< Context > > args)
Formats arguments and writes the output to the range.
template<typename S , typename... Args, typename Char = char_t<S>>
int fprintf (std::basic_ostream< Char > &os, const S &format_str, const Args &... args)
\rst Prints formatted data to the stream os.
Macro Definition Documentation
CATA_SRC_FMTLIB_PRINTF_H
#define CATA_SRC_FMTLIB_PRINTF_H
Definition at line 10 of file fmtlib_printf.h.
Typedef Documentation
basic_printf_context_t
template<typename Char > using basic_printf_context_t = basic_printf_context<detail::buffer_appender<Char>, Char>
Definition at line 663 of file fmtlib_printf.h.
printf_args
using printf_args = basic_format_args<printf_context>
Definition at line 669 of file fmtlib_printf.h.
printf_context
using printf_context = basic_printf_context_t<char>
Definition at line 666 of file fmtlib_printf.h.
wprintf_args
using wprintf_args = basic_format_args<wprintf_context>
Definition at line 670 of file fmtlib_printf.h.
wprintf_context
using wprintf_context = basic_printf_context_t<wchar_t>
Definition at line 667 of file fmtlib_printf.h.
Function Documentation
fprintf() [1/2]
template<typename S , typename... Args, typename Char = char_t<S>> int fprintf (std::basic_ostream< Char > & os, const S & format_str, const Args &... args) inline
\rst Prints formatted data to the stream os.
Example**::
fmt::fprintf(cerr, "Don't %s!", "panic"); \endrst
Definition at line 816 of file fmtlib_printf.h.
{
    using context = basic_printf_context_t<Char>;
    return vfprintf( os, to_string_view( format_str ),
                     make_format_args<context>( args... ) );
}
References to_string_view(), and vfprintf().
fprintf() [2/2]
template<typename S , typename... Args, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>> int fprintf (std::FILE * f, const S & format, const Args &... args) inline
\rst Prints formatted data to the file f.
Example**::
fmt::fprintf(stderr, "Don't %s!", "panic"); \endrst
Definition at line 749 of file fmtlib_printf.h.
{
    using context = basic_printf_context_t<Char>;
    return vfprintf( f, to_string_view( format ),
                     make_format_args<context>( args... ) );
}
References format(), to_string_view(), and vfprintf().
Referenced by detail::assert_fail().
make_printf_args()
template<typename... Args> format_arg_store< printf_context, Args... > make_printf_args (const Args &... args) inline
\rst Constructs an ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtprintf_args.
\endrst
Definition at line 679 of file fmtlib_printf.h.
{
    return {args...};
}
make_wprintf_args()
template<typename... Args> format_arg_store< wprintf_context, Args... > make_wprintf_args (const Args &... args) inline
\rst Constructs an ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtwprintf_args.
\endrst
Definition at line 692 of file fmtlib_printf.h.
{
    return {args...};
}
printf() [1/2]
template<typename S , typename... Args, FMT_ENABLE_IF(detail::is_string< S >::value) > int printf (const S & format_str, const Args &... args) inline
\rst Prints formatted data to stdout.
Example**::
fmt::printf("Elapsed time: %.2f seconds", 1.23); \endrst
Definition at line 775 of file fmtlib_printf.h.
{
    using context = basic_printf_context_t<char_t<S>>;
    return vprintf( to_string_view( format_str ),
                    make_format_args<context>( args... ) );
}
References to_string_view(), and vprintf().
printf() [2/2]
template<typename Char , typename Context > FMT_DEPRECATED void printf (detail::buffer< Char > & buf, basic_string_view< Char > format, basic_format_args< Context > args)
Definition at line 214 of file fmtlib_printf.h.
{
    return detail::vprintf( buf, format, args );
}
References format(), and detail::vprintf().
sprintf()
template<typename S , typename... Args, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>> std::basic_string< Char > sprintf (const S & format, const Args &... args) inline
\rst Formats arguments and returns the result as a string.
Example**::
std::string message = fmt::sprintf("The answer is %d", 42); \endrst
Definition at line 719 of file fmtlib_printf.h.
{
    using context = basic_printf_context_t<Char>;
    return vsprintf( to_string_view( format ), make_format_args<context>( args... ) );
}
References format(), to_string_view(), and vsprintf().
Referenced by cata::string_formatter::do_formating().
vfprintf() [1/2]
template<typename S , typename Char = char_t<S>> int vfprintf (std::basic_ostream< Char > & os, const S & format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args) inline
Definition at line 783 of file fmtlib_printf.h.
{
    basic_memory_buffer<Char> buffer;
    vprintf( buffer, to_string_view( format ), args );
    detail::write_buffer( os, buffer );
    return static_cast<int>( buffer.size() );
}
References format(), detail::buffer< T >::size(), to_string_view(), vprintf(), and detail::write_buffer().
vfprintf() [2/2]
template<typename S , typename Char = char_t<S>> int vfprintf (std::FILE * f, const S & format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args) inline
Definition at line 726 of file fmtlib_printf.h.
{
    basic_memory_buffer<Char> buffer;
    vprintf( buffer, to_string_view( format ), args );
    size_t size = buffer.size();
    return std::fwrite( buffer.data(), sizeof( Char ), size, f ) < size
           ? -1
           : static_cast<int>( size );
}
References detail::buffer< T >::data(), format(), detail::buffer< T >::size(), om_direction::size, to_string_view(), and vprintf().
Referenced by fprintf(), and vprintf().
vprintf() [1/2]
template<typename S , typename Char = char_t<S>> int vprintf (const S & format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args) inline
Definition at line 757 of file fmtlib_printf.h.
{
    return vfprintf( stdout, to_string_view( format ), args );
}
References format(), to_string_view(), and vfprintf().
Referenced by printf(), vfprintf(), and vsprintf().
vprintf() [2/2]
template<typename ArgFormatter , typename Char , typename Context = basic_printf_context<typename ArgFormatter::iterator, Char>> ArgFormatter::iterator vprintf (detail::buffer< Char > & out, basic_string_view< Char > format_str, basic_format_args< type_identity_t< Context > > args)
Formats arguments and writes the output to the range.
Definition at line 797 of file fmtlib_printf.h.
{
    typename ArgFormatter::iterator iter( out );
    Context( iter, format_str, args ).template format<ArgFormatter>();
    return iter;
}
vsprintf()
template<typename S , typename Char = char_t<S>> std::basic_string< Char > vsprintf (const S & format, basic_format_args< basic_printf_context_t< type_identity_t< Char > > > args) inline
Definition at line 699 of file fmtlib_printf.h.
{
    basic_memory_buffer<Char> buffer;
    vprintf( buffer, to_string_view( format ), args );
    return to_string( buffer );
}
References format(), to_string(), to_string_view(), and vprintf().
Referenced by sprintf().