Cataclysm BN: src/font_loader.h File Reference
font_loader.h File Reference
#include <algorithm>
#include <stdexcept>
#include <string>
#include <vector>
#include "debug.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "json.h"
#include "path_info.h"
#include "cata_utility.h"
Classes
class font_loader
Macros
#define CATA_SRC_FONT_LOADER_H
Functions
static void ensure_unifont_loaded (std::vector< std::string > &font_list)
Macro Definition Documentation
CATA_SRC_FONT_LOADER_H
#define CATA_SRC_FONT_LOADER_H
Definition at line 3 of file font_loader.h.
Function Documentation
ensure_unifont_loaded()
static void ensure_unifont_loaded (std::vector< std::string > & font_list) static
Definition at line 18 of file font_loader.h.
{
    if( std::find( std::begin( font_list ), std::end( font_list ), "unifont" ) == font_list.end() ) {
        font_list.emplace_back( PATH_INFO::fontdir() + "unifont.ttf" );
    }
}
References detail::find(), and PATH_INFO::fontdir().
Referenced by font_loader::load_throws().