Cataclysm BN: src/fragment_cloud.h File Reference
fragment_cloud.h File Reference
Macros
#define CATA_SRC_FRAGMENT_CLOUD_H
Functions
float shrapnel_calc (const float &intensity, const float &last_obstacle, const int &distance)
bool shrapnel_check (const float &obstacle, const float &intensity)
void update_fragment_cloud (float &output, const float &new_intensity, quadrant)
float accumulate_fragment_cloud (const float &cumulative_obstacle, const float &current_obstacle, const int &distance)
Macro Definition Documentation
CATA_SRC_FRAGMENT_CLOUD_H
#define CATA_SRC_FRAGMENT_CLOUD_H
Definition at line 3 of file fragment_cloud.h.
Function Documentation
accumulate_fragment_cloud()
float accumulate_fragment_cloud (const float & cumulative_obstacle, const float & current_obstacle, const int & distance)
Definition at line 1309 of file explosion.cpp.
{
    return std::max( cumulative_obstacle, current_obstacle ) + 1;
}
Referenced by explosion_handler::shrapnel().
shrapnel_calc()
float shrapnel_calc (const float & intensity, const float & last_obstacle, const int & distance)
Definition at line 1294 of file explosion.cpp.
{
    return intensity - last_obstacle;
}
Referenced by explosion_handler::shrapnel().
shrapnel_check()
bool shrapnel_check (const float & obstacle, const float & intensity)
Definition at line 1299 of file explosion.cpp.
{
    return last_intensity - obstacle > 0.0f;
}
Referenced by explosion_handler::shrapnel().
update_fragment_cloud()
void update_fragment_cloud (float & output, const float & new_intensity, quadrant)
Definition at line 1304 of file explosion.cpp.
{
    output = std::max( output, new_intensity );
}
Referenced by explosion_handler::shrapnel().