Cataclysm BN: src/fstream_utils.h File Reference
fstream_utils.h File Reference
#include <iosfwd>
#include <string>
#include <memory>
#include <functional>
Classes
struct cata_ofstream
Wrapper around std::ofstream that provides cross-platform support for UTF-8 paths.
struct cata_ifstream
Wrapper around std::ifstream that provides cross-platform support for UTF-8 paths.
class ofstream_wrapper
Wrapper around std::ofstream that handles error checking and throws on errors.
Macros
#define CATA_SRC_FSTREAM_UTILS_H
Enumerations
enum class cata_ios_mode : int { none = 0 , app = 1 << 0 , binary = 1 << 1 }
Functions
std::istream & safe_getline (std::istream &ins, std::string &str)
bool write_to_file (const std::string &path, const std::function< void(std::ostream &)> &writer, const char *fail_message)
Open a file for writing, calls the writer on that stream.
void write_to_file (const std::string &path, const std::function< void(std::ostream &)> &writer)
bool read_from_file (const std::string &path, const std::function< void(std::istream &)> &reader)
Try to open and read from given file using the given callback.
bool read_from_file_json (const std::string &path, const std::function< void(JsonIn &)> &reader)
bool read_from_file (const std::string &path, JsonDeserializer &reader)
bool read_from_file_optional (const std::string &path, const std::function< void(std::istream &)> &reader)
bool read_from_file_optional_json (const std::string &path, const std::function< void(JsonIn &)> &reader)
bool read_from_file_optional (const std::string &path, JsonDeserializer &reader)
std::string serialize_wrapper (const std::function< void(JsonOut &)> &callback)
@group JSON (de)serialization wrappers.
void deserialize_wrapper (const std::function< void(JsonIn &)> &callback, const std::string &data)
template<typename T >
std::string serialize (const T &obj)
template<typename T >
void deserialize (T &obj, const std::string &data)
Macro Definition Documentation
CATA_SRC_FSTREAM_UTILS_H
#define CATA_SRC_FSTREAM_UTILS_H
Definition at line 3 of file fstream_utils.h.
Enumeration Type Documentation
cata_ios_mode
enum class cata_ios_mode : int strong
Enumerator
none
app
binary
Definition at line 21 of file fstream_utils.h.
                         : int {
    none = 0,
    app = 1 << 0,
    binary = 1 << 1
};
Function Documentation
deserialize()
template<typename T > void deserialize (T & obj, const std::string & data) inline
Definition at line 218 of file fstream_utils.h.
{
    deserialize_wrapper( [&obj]( JsonIn & jsin ) {
        obj.deserialize( jsin );
    }, data );
}
References deserialize_wrapper(), and int_id< T >::obj().
deserialize_wrapper()
void deserialize_wrapper (const std::function< void(JsonIn &)> & callback, const std::string & data)
Definition at line 667 of file cata_utility.cpp.
{
    std::istringstream buffer( data );
    JsonIn jsin( buffer );
    callback( jsin );
}
Referenced by deserialize(), and rcdrive().
read_from_file() [1/2]
bool read_from_file (const std::string & path, const std::function< void(std::istream &)> & reader)
Try to open and read from given file using the given callback.
The file is opened for reading (binary mode), given to the callback (which does the actual reading) and closed. Any exceptions from the callbacks are caught and reported as debugmsg. If the stream is in a fail state (other than EOF) after the callback returns, it is handled as error as well.
The callback can either be a generic std::istream, a JsonIn stream (which has been initialized from the std::istream) or a JsonDeserializer object (in case of the later, it's JsonDeserializer::deserialize method will be invoked).
The functions with the "_optional" prefix do not show a debug message when the file does not exist. They simply ignore the call and return false immediately (without calling the callback). They can be used for loading legacy files.
Returns
true is the file was read without any errors, false upon any error.
Definition at line 519 of file cata_utility.cpp.
{
    try {
        cata_ifstream fin = std::move( cata_ifstream().mode( cata_ios_mode::binary ).open( path ) );
        if( !fin.is_open() ) {
            throw std::runtime_error( "opening file failed" );
        }
        reader( *fin );
        if( fin.bad() ) {
            throw std::runtime_error( "reading file failed" );
        }
        return true;
    } catch( const std::exception &err ) {
        debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.c_str(), err.what() );
        return false;
    }
}
References _, cata_ifstream::bad(), binary, debugmsg, cata_ifstream::is_open(), avatar_action::move(), and open().
Referenced by build_resource_list(), diary::load(), game::load(), read_from_file_json(), read_from_file_optional(), and sokoban_game::start_game().
read_from_file() [2/2]
bool read_from_file (const std::string & path, JsonDeserializer & reader)
Definition at line 546 of file cata_utility.cpp.
{
    return read_from_file_json( path, [&reader]( JsonIn & jsin ) {
        reader.deserialize( jsin );
    } );
}
References JsonDeserializer::deserialize(), and read_from_file_json().
read_from_file_json()
bool read_from_file_json (const std::string & path, const std::function< void(JsonIn &)> & reader)
Definition at line 538 of file cata_utility.cpp.
{
    return read_from_file( path, [&]( std::istream & fin ) {
        JsonIn jsin( fin, path );
        reader( jsin );
    } );
}
References read_from_file().
Referenced by get_random_tip_of_the_day(), Name::load_from_file(), avatar::load_template(), and read_from_file().
read_from_file_optional() [1/2]
bool read_from_file_optional (const std::string & path, const std::function< void(std::istream &)> & reader)
Definition at line 553 of file cata_utility.cpp.
{
    // Note: slight race condition here, but we'll ignore it. Worst case: the file
    // exists and got removed before reading it -> reading fails with a message
    // Or file does not exists, than everything works fine because it's optional anyway.
    return file_exist( path ) && read_from_file( path, reader );
}
References file_exist(), and read_from_file().
Referenced by get_input_string_from_file(), main_menu::init_strings(), game::load(), main_menu::load_file(), game::load_master(), zone_manager::load_zones(), overmap::open(), and read_from_file_optional_json().
read_from_file_optional() [2/2]
bool read_from_file_optional (const std::string & path, JsonDeserializer & reader)
Definition at line 571 of file cata_utility.cpp.
{
    return read_from_file_optional_json( path, [&reader]( JsonIn & jsin ) {
        reader.deserialize( jsin );
    } );
}
References JsonDeserializer::deserialize(), and read_from_file_optional_json().
read_from_file_optional_json()
bool read_from_file_optional_json (const std::string & path, const std::function< void(JsonIn &)> & reader)
Definition at line 562 of file cata_utility.cpp.
{
    return read_from_file_optional( path, [&]( std::istream & fin ) {
        JsonIn jsin( fin, path );
        reader( jsin );
    } );
}
References read_from_file_optional().
Referenced by auto_notes::auto_note_settings::load(), help::load(), options_manager::load(), panel_manager::load(), auto_pickup::player_settings::load(), map_memory::load(), load_artifacts(), color_manager::load_custom(), mod_management::load_mod_info(), mod_management::load_mod_list(), mod_manager::load_mods_list(), WORLD::load_options(), mod_manager::load_replacement_mods(), map_memory::load_submap(), read_from_file_optional(), and mapbuffer::unserialize_submaps().
safe_getline()
std::istream & safe_getline (std::istream & ins, std::string & str)
Definition at line 492 of file cata_utility.cpp.
{
    str.clear();
    std::istream::sentry se( ins, true );
    std::streambuf *sb = ins.rdbuf();
    while( true ) {
        int c = sb->sbumpc();
        switch( c ) {
            case '\n':
                return ins;
            case '\r':
                if( sb->sgetc() == '\n' ) {
                    sb->sbumpc();
                }
                return ins;
            case EOF:
                if( str.empty() ) {
                    ins.setstate( std::ios::eofbit );
                }
                return ins;
            default:
                str += static_cast<char>( c );
        }
    }
}
References c.
Referenced by sokoban_game::parse_level().
serialize()
template<typename T > std::string serialize (const T & obj) inline
Definition at line 210 of file fstream_utils.h.
{
    return serialize_wrapper( [&obj]( JsonOut & jsout ) {
        obj.serialize( jsout );
    } );
}
References int_id< T >::obj(), and serialize_wrapper().
serialize_wrapper()
std::string serialize_wrapper (const std::function< void(JsonOut &)> & callback)
@group JSON (de)serialization wrappers.
The functions here provide a way to (de)serialize objects without actually including "json.h". The *_wrapper function create the JSON stream instances and therefor require "json.h", but the caller doesn't. Callers should just forward the stream reference to the actual (de)serialization function.
The inline function do this by calling T::(de)serialize (which is assumed to exist with the proper signature).
Exceptions
std::exception Deserialization functions may throw upon malformed JSON or unexpected/invalid content.
Definition at line 659 of file cata_utility.cpp.
{
    std::ostringstream buffer;
    JsonOut jsout( buffer );
    callback( jsout );
    return buffer.str();
}
Referenced by iuse::radiocontrol(), rcdrive(), map_memory::save(), and serialize().
write_to_file() [1/2]
void write_to_file (const std::string & path, const std::function< void(std::ostream &)> & writer)
Definition at line 453 of file cata_utility.cpp.
{
    // Any of the below may throw. ofstream_wrapper will clean up the temporary path on its own.
    ofstream_wrapper fout( path, cata_ios_mode::binary );
    writer( fout.stream() );
    fout.close();
}
References binary, ofstream_wrapper::close(), and ofstream_wrapper::stream().
Referenced by can_write_to_dir(), copy_file(), edit_json(), auto_notes::auto_note_settings::save(), distraction_manager::distraction_manager_gui::save(), game::save(), input_manager::save(), options_manager::save(), panel_manager::save(), overmap::save(), auto_pickup::player_settings::save(), safemode::save(), WORLD::save(), map_memory::save(), save_artifacts(), color_manager::save_custom(), game::save_factions_missions_npcs(), worldfactory::save_last_world_info(), mod_management::save_mod_list(), mod_manager::save_mods_list(), game::save_player_data(), mapbuffer::save_quad(), avatar::save_template(), zone_manager::save_zones(), diary::store(), weather_generator::test_weather(), game::write_memorial_file(), and write_to_file().
write_to_file() [2/2]
bool write_to_file (const std::string & path, const std::function< void(std::ostream &)> & writer, const char * fail_message)
Open a file for writing, calls the writer on that stream.
If the writer throws, or if the file could not be opened or if any I/O error happens, the function shows a popup containing the fail_message, the error text and the path.
Returns
Whether saving succeeded (no error was caught).
Exceptions
The void function throws when writing failes or when the writer throws. The other function catches all exceptions and returns false.
Definition at line 461 of file cata_utility.cpp.
{
    try {
        write_to_file( path, writer );
        return true;
    } catch( const std::exception &err ) {
        if( fail_message ) {
            popup( _( "Failed to write %1$s to \"%2$s\": %3$s" ), fail_message, path.c_str(), err.what() );
        }
        return false;
    }
}
References _, popup(), and write_to_file().