Cataclysm BN: src/fungal_effects.cpp File Reference
fungal_effects.cpp File Reference
#include "fungal_effects.h"
#include <algorithm>
#include <memory>
#include <ostream>
#include <string>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "field_type.h"
#include "game.h"
#include "item.h"
#include "item_stack.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "player.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
Macros
#define dbg(x) DebugLogFL((x), DC::Game)
Functions
static const std::string flag_DIGGABLE ("DIGGABLE")
static const std::string flag_FLAMMABLE ("FLAMMABLE")
static const std::string flag_FLOWER ("FLOWER")
static const std::string flag_FUNGUS ("FUNGUS")
static const std::string flag_ORGANIC ("ORGANIC")
static const std::string flag_PLANT ("PLANT")
static const std::string flag_SHRUB ("SHRUB")
static const std::string flag_THIN_OBSTACLE ("THIN_OBSTACLE")
static const std::string flag_TREE ("TREE")
static const std::string flag_WALL ("WALL")
static const std::string flag_YOUNG ("YOUNG")
Variables
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_spores ("spores")
static const efftype_id effect_stunned ("stunned")
static const skill_id skill_melee ("melee")
static const mtype_id mon_fungal_blossom ("mon_fungal_blossom")
static const mtype_id mon_spore ("mon_spore")
static const species_id FUNGUS ("FUNGUS")
static const trait_id trait_TAIL_CATTLE ("TAIL_CATTLE")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
Macro Definition Documentation
dbg
#define dbg (x) DebugLogFL((x), DC::Game)
Definition at line 31 of file fungal_effects.cpp.
Function Documentation
flag_DIGGABLE()
static const std::string flag_DIGGABLE ("DIGGABLE") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_FLAMMABLE()
static const std::string flag_FLAMMABLE ("FLAMMABLE") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_FLOWER()
static const std::string flag_FLOWER ("FLOWER") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_FUNGUS()
static const std::string flag_FUNGUS ("FUNGUS") static
Referenced by fungal_effects::marlossify(), and fungal_effects::spread_fungus().
flag_ORGANIC()
static const std::string flag_ORGANIC ("ORGANIC") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_PLANT()
static const std::string flag_PLANT ("PLANT") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_SHRUB()
static const std::string flag_SHRUB ("SHRUB") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_THIN_OBSTACLE()
static const std::string flag_THIN_OBSTACLE ("THIN_OBSTACLE") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_TREE()
static const std::string flag_TREE ("TREE") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_WALL()
static const std::string flag_WALL ("WALL") static
Referenced by fungal_effects::spread_fungus_one_tile().
flag_YOUNG()
static const std::string flag_YOUNG ("YOUNG") static
Referenced by fungal_effects::spread_fungus_one_tile().
Variable Documentation
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by fungal_effects::fungalize().
effect_spores
const efftype_id effect_spores("spores") ("spores") static
Referenced by fungal_effects::fungalize().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by fungal_effects::fungalize().
FUNGUS
const species_id FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by fungal_effects::fungalize().
mon_fungal_blossom
const mtype_id mon_fungal_blossom("mon_fungal_blossom") ("mon_fungal_blossom") static
Referenced by fungal_effects::spread_fungus_one_tile().
mon_spore
const mtype_id mon_spore("mon_spore") ("mon_spore") static
Referenced by fungal_effects::fungalize().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by fungal_effects::fungalize().
trait_TAIL_CATTLE
const trait_id trait_TAIL_CATTLE("TAIL_CATTLE") ("TAIL_CATTLE") static
Referenced by fungal_effects::fungalize().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by fungal_effects::fungalize().