Cataclysm BN: src/gamemode_defense.cpp File Reference
gamemode_defense.cpp File Reference
#include "gamemode_defense.h"
#include <cassert>
#include <cstddef>
#include <memory>
#include <ostream>
#include <set>
#include "action.h"
#include "avatar.h"
#include "basecamp.h"
#include "color.h"
#include "construction.h"
#include "coordinate_conversions.h"
#include "cursesdef.h"
#include "debug.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "item.h"
#include "item_group.h"
#include "iteminfo_query.h"
#include "map.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "monstergenerator.h"
#include "mtype.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "player.h"
#include "pldata.h"
#include "point.h"
#include "popup.h"
#include "rng.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_utils.h"
#include "translations.h"
#include "ui_manager.h"
#include "weather.h"
Macros
#define SELCOL(n) (selection == (n) ? c_yellow : c_blue)
#define TOGCOL(n, b)
#define NUMALIGN(n)
Functions
std::string caravan_category_name (caravan_category cat)
std::vector< itype_id > caravan_items (caravan_category cat)
int caravan_price (player &u, int price)
void draw_caravan_borders (const catacurses::window &w, int current_window)
void draw_caravan_categories (const catacurses::window &w, int category_selected, int total_price, int cash)
void draw_caravan_items (const catacurses::window &w, std::vector< itype_id > *items, std::vector< int > *counts, int offset, int item_selected)
std::string defense_style_name (defense_style style)
std::string defense_style_description (defense_style style)
std::string defense_location_name (defense_location location)
std::string defense_location_description (defense_location location)
Variables
static const skill_id skill_barter ("barter")
static const mongroup_id GROUP_NETHER ("GROUP_NETHER")
static const mongroup_id GROUP_ROBOT ("GROUP_ROBOT")
static const mongroup_id GROUP_SPIDER ("GROUP_SPIDER")
static const mongroup_id GROUP_TRIFFID ("GROUP_TRIFFID")
static const mongroup_id GROUP_VANILLA ("GROUP_VANILLA")
static const mongroup_id GROUP_ZOMBIE ("GROUP_ZOMBIE")
static constexpr int SPECIAL_WAVE_CHANCE = 5
static constexpr int SPECIAL_WAVE_MIN = 5
std::set< m_flag > monflags_to_add
Macro Definition Documentation
NUMALIGN
#define NUMALIGN (n)
Value:
                     ((n) >= 10000 ? 20 : ((n) >= 1000 ? 21 :\
                     ((n) >= 100 ? 22 : ((n) >= 10 ? 23 : 24))))
Definition at line 61 of file gamemode_defense.cpp.
SELCOL
#define SELCOL (n) (selection == (n) ? c_yellow : c_blue)
Definition at line 58 of file gamemode_defense.cpp.
TOGCOL
#define TOGCOL (n, b)
Value:
                      (selection == (n) ? ((b) ? c_light_green : c_yellow) :\
                      ((b) ? c_green : c_dark_gray))
Definition at line 59 of file gamemode_defense.cpp.
Function Documentation
caravan_category_name()
std::string caravan_category_name (caravan_category cat)
Definition at line 1084 of file gamemode_defense.cpp.
{
    switch( cat ) {
        case CARAVAN_CART:
            return _( "Shopping Cart" );
        case CARAVAN_MELEE:
            return _( "Melee Weapons" );
        case CARAVAN_RANGED:
            return _( "Ranged Weapons" );
        case CARAVAN_AMMUNITION:
            return _( "Ammuniton" );
        case CARAVAN_COMPONENTS:
            return _( "Crafting & Construction Components" );
        case CARAVAN_FOOD:
            return _( "Food & Drugs" );
        case CARAVAN_CLOTHES:
            return _( "Clothing & Armor" );
        case CARAVAN_TOOLS:
            return _( "Tools, Traps & Grenades" );
        case NUM_CARAVAN_CATEGORIES:
            break; // error message below
    }
    return "BUG (defense.cpp:caravan_category_name)";
}
References _, CARAVAN_AMMUNITION, CARAVAN_CART, CARAVAN_CLOTHES, CARAVAN_COMPONENTS, CARAVAN_FOOD, CARAVAN_MELEE, CARAVAN_RANGED, CARAVAN_TOOLS, and NUM_CARAVAN_CATEGORIES.
Referenced by draw_caravan_categories().
caravan_items()
std::vector< itype_id > caravan_items (caravan_category cat)
Definition at line 1109 of file gamemode_defense.cpp.
{
    std::vector<itype_id> ret;
    std::string group_id;
    switch( cat ) {
        case CARAVAN_CART:
            return ret;
        case CARAVAN_MELEE:
            group_id = "defense_caravan_melee" ;
            break;
        case CARAVAN_RANGED:
            group_id = "defense_caravan_ranged" ;
            break;
        case CARAVAN_AMMUNITION:
            group_id = "defense_caravan_ammunition" ;
            break;
        case CARAVAN_COMPONENTS:
            group_id = "defense_caravan_components" ;
            break;
        case CARAVAN_FOOD:
            group_id = "defense_caravan_food" ;
            break;
        case CARAVAN_CLOTHES:
            group_id = "defense_caravan_clothes" ;
            break;
        case CARAVAN_TOOLS:
            group_id = "defense_caravan_tools" ;
            break;
        case NUM_CARAVAN_CATEGORIES:
            debugmsg( "Invalid caravan category %d", cat );
            return ret;
    }
    item_group::ItemList item_list = item_group::items_from( item_group_id( group_id ) );
    for( auto &it : item_list ) {
        itype_id item_type = it.typeId();
        ret.emplace_back( item_type );
        // Add the default magazine types for each gun.
        if( it.is_gun() && !it.magazine_integral() ) {
            ret.emplace_back( it.magazine_default() );
        }
    }
    return ret;
}
References CARAVAN_AMMUNITION, CARAVAN_CART, CARAVAN_CLOTHES, CARAVAN_COMPONENTS, CARAVAN_FOOD, CARAVAN_MELEE, CARAVAN_RANGED, CARAVAN_TOOLS, debugmsg, item_group::items_from(), NUM_CARAVAN_CATEGORIES, and cata::hash64_detail::ret.
Referenced by defense_game::caravan().
caravan_price()
int caravan_price (player & u, int price)
Barter reduces caravan prices, 5% per point, up to 50%
Definition at line 1272 of file gamemode_defense.cpp.
{
    ///\EFFECT_BARTER reduces caravan prices, 5% per point, up to 50%
    if( u.get_skill_level( skill_barter ) > 10 ) {
        return static_cast<int>( static_cast<double>( price ) * .5 );
    }
    return price * ( 1.0 - u.get_skill_level( skill_barter ) * .05 );
}
References Character::get_skill_level(), and skill_barter.
Referenced by defense_game::caravan(), and draw_caravan_items().
defense_location_description()
std::string defense_location_description (defense_location location)
Definition at line 839 of file gamemode_defense.cpp.
{
    switch( location ) {
        case DEFLOC_NULL:
            return "NULL Bug.  (defense.cpp:defense_location_description)";
        case DEFLOC_HOSPITAL:
            return                 _( "One entrance and many rooms.  Some medical supplies." );
        case DEFLOC_WORKS:
            return                 _( "Easily fortifiable building.  Lots of useful tools." );
        case DEFLOC_MALL:
            return                 _( "A large building with various supplies." );
        case DEFLOC_BAR:
            return                 _( "A small building with plenty of alcohol." );
        case DEFLOC_MANSION:
            return                 _( "A large house with many rooms." );
        case NUM_DEFENSE_LOCATIONS:
            break;
    }
    return "Unknown data bug.  (defense.cpp:defense_location_description)";
}
References _, DEFLOC_BAR, DEFLOC_HOSPITAL, DEFLOC_MALL, DEFLOC_MANSION, DEFLOC_NULL, DEFLOC_WORKS, and NUM_DEFENSE_LOCATIONS.
Referenced by defense_game::refresh_setup().
defense_location_name()
std::string defense_location_name (defense_location location)
Definition at line 818 of file gamemode_defense.cpp.
{
    switch( location ) {
        case DEFLOC_NULL:
            return "Nowhere?!  (bug in defense.cpp:defense_location_name)";
        case DEFLOC_HOSPITAL:
            return _( "Hospital" );
        case DEFLOC_WORKS:
            return _( "Public Works" );
        case DEFLOC_MALL:
            return _( "Megastore" );
        case DEFLOC_BAR:
            return _( "Bar" );
        case DEFLOC_MANSION:
            return _( "Mansion" );
        case NUM_DEFENSE_LOCATIONS:
            break;
    }
    return "a ghost's house (bug in defense.cpp:defense_location_name)";
}
References _, DEFLOC_BAR, DEFLOC_HOSPITAL, DEFLOC_MALL, DEFLOC_MANSION, DEFLOC_NULL, DEFLOC_WORKS, and NUM_DEFENSE_LOCATIONS.
Referenced by defense_game::pre_action(), and defense_game::refresh_setup().
defense_style_description()
std::string defense_style_description (defense_style style)
Definition at line 788 of file gamemode_defense.cpp.
{
    // 51 Characters Max!
    switch( style ) {
        case DEFENSE_CUSTOM:
            return _( "A custom game." );
        case DEFENSE_EASY:
            return _( "Easy monsters and lots of money." );
        case DEFENSE_MEDIUM:
            return _( "Harder monsters.  You have to eat." );
        case DEFENSE_HARD:
            return _( "All monsters.  You have to eat and drink." );
        case DEFENSE_SHAUN:
            return _( "Defend a bar against classic zombies.  Easy and fun." );
        case DEFENSE_DAWN:
            return _( "Classic zombies.  Slower and more realistic." );
        case DEFENSE_SPIDERS:
            return _( "Fast-paced spider-fighting fun!" );
        case DEFENSE_TRIFFIDS:
            return _( "Defend your mansion against the triffids." );
        case DEFENSE_SKYNET:
            return _( "The robots have decided that humans are the enemy!" );
        case DEFENSE_LOVECRAFT:
            return _( "Ward off legions of eldritch horrors." );
        case NUM_DEFENSE_STYLES:
            break;
    }
    return "What the heck is this I don't even know.  (defense.cpp:defense_style_description)";
}
References _, DEFENSE_CUSTOM, DEFENSE_DAWN, DEFENSE_EASY, DEFENSE_HARD, DEFENSE_LOVECRAFT, DEFENSE_MEDIUM, DEFENSE_SHAUN, DEFENSE_SKYNET, DEFENSE_SPIDERS, DEFENSE_TRIFFIDS, and NUM_DEFENSE_STYLES.
Referenced by defense_game::refresh_setup().
defense_style_name()
std::string defense_style_name (defense_style style)
Definition at line 758 of file gamemode_defense.cpp.
{
    // 24 Characters Max!
    switch( style ) {
        case DEFENSE_CUSTOM:
            return _( "Custom" );
        case DEFENSE_EASY:
            return _( "Easy" );
        case DEFENSE_MEDIUM:
            return _( "Medium" );
        case DEFENSE_HARD:
            return _( "Hard" );
        case DEFENSE_SHAUN:
            return _( "Shaun of the Dead" );
        case DEFENSE_DAWN:
            return _( "Dawn of the Dead" );
        case DEFENSE_SPIDERS:
            return _( "Eight-Legged Freaks" );
        case DEFENSE_TRIFFIDS:
            return _( "Day of the Triffids" );
        case DEFENSE_SKYNET:
            return _( "Skynet" );
        case DEFENSE_LOVECRAFT:
            return _( "The Call of Cthulhu" );
        case NUM_DEFENSE_STYLES:
            break;
    }
    return "Bug!  (bug in defense.cpp:defense_style_name)";
}
References _, DEFENSE_CUSTOM, DEFENSE_DAWN, DEFENSE_EASY, DEFENSE_HARD, DEFENSE_LOVECRAFT, DEFENSE_MEDIUM, DEFENSE_SHAUN, DEFENSE_SKYNET, DEFENSE_SPIDERS, DEFENSE_TRIFFIDS, and NUM_DEFENSE_STYLES.
Referenced by defense_game::refresh_setup().
draw_caravan_borders()
void draw_caravan_borders (const catacurses::window & w, int current_window)
Definition at line 1163 of file gamemode_defense.cpp.
{
    // First, do the borders for the category window
    nc_color col = c_light_gray;
    if( current_window == 0 ) {
        col = c_yellow;
    }
    mvwputch( w, point_zero, col, LINE_OXXO );
    for( int i = 1; i <= 38; i++ ) {
        mvwputch( w, point( i, 0 ), col, LINE_OXOX );
        mvwputch( w, point( i, 11 ), col, LINE_OXOX );
    }
    for( int i = 1; i <= 10; i++ ) {
        mvwputch( w, point( 0, i ), col, LINE_XOXO );
        mvwputch( w, point( 39, i ), c_yellow, LINE_XOXO ); // Shared border, always yellow
    }
    mvwputch( w, point( 0, 11 ), col, LINE_XXXO );
    // These are shared with the items window, and so are always "on"
    mvwputch( w, point( 39, 0 ), c_yellow, LINE_OXXX );
    mvwputch( w, point( 39, 11 ), c_yellow, LINE_XOXX );
    col = ( current_window == 1 ? c_yellow : c_light_gray );
    // Next, draw the borders for the item description window--always "off" & gray
    for( int i = 12; i <= 23; i++ ) {
        mvwputch( w, point( 0, i ), c_light_gray, LINE_XOXO );
        mvwputch( w, point( 39, i ), col,      LINE_XOXO );
    }
    for( int i = 1; i <= 38; i++ ) {
        mvwputch( w, point( i, FULL_SCREEN_HEIGHT - 1 ), c_light_gray, LINE_OXOX );
    }
    mvwputch( w, point( 0, FULL_SCREEN_HEIGHT - 1 ), c_light_gray, LINE_XXOO );
    mvwputch( w, point( 39, FULL_SCREEN_HEIGHT - 1 ), c_light_gray, LINE_XXOX );
    // Finally, draw the item section borders
    for( int i = 40; i <= FULL_SCREEN_WIDTH - 2; i++ ) {
        mvwputch( w, point( i, 0 ), col, LINE_OXOX );
        mvwputch( w, point( i, FULL_SCREEN_HEIGHT - 1 ), col, LINE_OXOX );
    }
    for( int i = 1; i <= FULL_SCREEN_HEIGHT - 2; i++ ) {
        mvwputch( w, point( FULL_SCREEN_WIDTH - 1, i ), col, LINE_XOXO );
    }
    mvwputch( w, point( 39, FULL_SCREEN_HEIGHT - 1 ), col, LINE_XXOX );
    mvwputch( w, point( FULL_SCREEN_WIDTH - 1, 0 ), col, LINE_OOXX );
    mvwputch( w, point( FULL_SCREEN_WIDTH - 1, FULL_SCREEN_HEIGHT - 1 ), col, LINE_XOOX );
    // Quick reminded about help.
    // NOLINTNEXTLINE(cata-text-style): literal question mark
    mvwprintz( w, point( 2, FULL_SCREEN_HEIGHT - 1 ), c_red, _( "Press ? for help." ) );
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_OXXX, LINE_XOOX, LINE_XOXO, LINE_XOXX, LINE_XXOO, LINE_XXOX, LINE_XXXO, mvwprintz(), mvwputch(), point_zero, and catacurses::wnoutrefresh().
Referenced by defense_game::caravan().
draw_caravan_categories()
void draw_caravan_categories (const catacurses::window & w, int category_selected, int total_price, int cash)
Definition at line 1218 of file gamemode_defense.cpp.
{
    // Clear the window
    for( int i = 1; i <= 10; i++ ) {
        mvwprintz( w, point( 1, i ), c_black, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" );
    }
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_white, _( "Your Cash: %s" ), format_money( cash ) );
    wprintz( w, c_light_gray, " -> " );
    wprintz( w, ( total_price > cash ? c_red : c_green ), "%s",
             format_money( static_cast<int>( cash ) - static_cast<int>( total_price ) ) );
    for( int i = 0; i < NUM_CARAVAN_CATEGORIES; i++ ) {
        mvwprintz( w, point( 1, i + 3 ), ( i == category_selected ? h_white : c_white ),
                   caravan_category_name( static_cast<caravan_category>( i ) ) );
    }
    wnoutrefresh( w );
}
References _, c_black, c_green, c_light_gray, c_red, c_white, caravan_category_name(), format_money(), h_white, mvwprintz(), NUM_CARAVAN_CATEGORIES, catacurses::wnoutrefresh(), and wprintz().
Referenced by defense_game::caravan().
draw_caravan_items()
void draw_caravan_items (const catacurses::window & w, std::vector< itype_id > * items, std::vector< int > * counts, int offset, int item_selected)
Definition at line 1238 of file gamemode_defense.cpp.
{
    // Print the item info first.  This is important, because it contains \n which
    // will corrupt the item list.
    // Actually, clear the item info first.
    for( int i = 12; i <= FULL_SCREEN_HEIGHT - 2; i++ ) {
        mvwprintz( w, point( 1, i ), c_black, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" );
    }
    // THEN print it--if item_selected is valid
    if( item_selected < static_cast<int>( items->size() ) ) {
        item tmp( ( *items )[item_selected], calendar::start_of_cataclysm );
        fold_and_print( w, point( 1, 12 ), 38, c_white, tmp.info_string( iteminfo_query::no_text ) );
    }
    // Next, clear the item list on the right
    for( int i = 1; i <= FULL_SCREEN_HEIGHT - 2; i++ ) {
        mvwprintz( w, point( 40, i ), c_black, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" );
    }
    // Finally, print the item list on the right
    for( int i = offset; i <= offset + FULL_SCREEN_HEIGHT - 2 &&
         i < static_cast<int>( items->size() ); i++ ) {
        mvwprintz( w, point( 40, i - offset + 1 ), ( item_selected == i ? h_white : c_white ),
                   item::nname( ( *items )[i], ( *counts )[i] ) );
        wprintz( w, c_white, " x %2d", ( *counts )[i] );
        if( ( *counts )[i] > 0 ) {
            int item_price = item( ( *items )[i], calendar::start_of_cataclysm ).price( false );
            int price = caravan_price( g->u, item_price * ( *counts )[i] );
            wprintz( w, ( price > g->u.cash ? c_red : c_green ), " (%s)", format_money( price ) );
        }
    }
    wnoutrefresh( w );
}
References c_black, c_green, c_red, c_white, caravan_price(), fold_and_print(), format_money(), FULL_SCREEN_HEIGHT, g, h_white, item::info_string(), mvwprintz(), item::nname(), iteminfo_query::no_text, item::price(), calendar::start_of_cataclysm, catacurses::wnoutrefresh(), and wprintz().
Referenced by defense_game::caravan().
Variable Documentation
GROUP_NETHER
const mongroup_id GROUP_NETHER("GROUP_NETHER") ("GROUP_NETHER") static
Referenced by defense_game::pick_monster_wave().
GROUP_ROBOT
const mongroup_id GROUP_ROBOT("GROUP_ROBOT") ("GROUP_ROBOT") static
Referenced by defense_game::pick_monster_wave().
GROUP_SPIDER
const mongroup_id GROUP_SPIDER("GROUP_SPIDER") ("GROUP_SPIDER") static
Referenced by defense_game::pick_monster_wave().
GROUP_TRIFFID
const mongroup_id GROUP_TRIFFID("GROUP_TRIFFID") ("GROUP_TRIFFID") static
Referenced by defense_game::pick_monster_wave().
GROUP_VANILLA
const mongroup_id GROUP_VANILLA("GROUP_VANILLA") ("GROUP_VANILLA") static
Referenced by defense_game::pick_monster_wave().
GROUP_ZOMBIE
const mongroup_id GROUP_ZOMBIE("GROUP_ZOMBIE") ("GROUP_ZOMBIE") static
Referenced by defense_game::pick_monster_wave().
monflags_to_add
std::set<m_flag> monflags_to_add
Definition at line 66 of file gamemode_defense.cpp.
skill_barter
const skill_id skill_barter("barter") ("barter") static
Referenced by caravan_price().
SPECIAL_WAVE_CHANCE
constexpr int SPECIAL_WAVE_CHANCE = 5 static constexpr
Definition at line 54 of file gamemode_defense.cpp.
Referenced by defense_game::spawn_wave().
SPECIAL_WAVE_MIN
constexpr int SPECIAL_WAVE_MIN = 5 static constexpr
Definition at line 56 of file gamemode_defense.cpp.
Referenced by defense_game::spawn_wave().