Cataclysm BN: src/game_ui.cpp File Reference
game_ui.cpp File Reference
#include "game_ui.h"
Functions
void reinitialize_framebuffer (const bool)
void to_map_font_dim_width (int &)
void to_map_font_dim_height (int &)
void to_map_font_dimension (int &, int &)
void from_map_font_dimension (int &, int &)
void to_overmap_font_dimension (int &, int &)
Function Documentation
from_map_font_dimension()
void from_map_font_dimension (int & w, int & h)
Definition at line 24 of file game_ui.cpp.
{
    return;
}
reinitialize_framebuffer()
void reinitialize_framebuffer (const bool force_invalidate)
Definition at line 5 of file game_ui.cpp.
{
    return;
}
Referenced by ui_adaptor::redraw_invalidated(), and ui_adaptor::ui_adaptor().
to_map_font_dim_height()
void to_map_font_dim_height (int & h)
Definition at line 15 of file game_ui.cpp.
{
    return;
}
to_map_font_dim_width()
void to_map_font_dim_width (int & w)
Definition at line 10 of file game_ui.cpp.
{
    return;
}
Referenced by centerlistview().
to_map_font_dimension()
void to_map_font_dimension (int & w, int & h)
Definition at line 20 of file game_ui.cpp.
{
    return;
}
Referenced by game::create_or_get_main_ui_adaptor(), and panel_manager::show_adm().
to_overmap_font_dimension()
void to_overmap_font_dimension (int & w, int & h)
Definition at line 28 of file game_ui.cpp.
{
    return;
}
Referenced by overmap_ui::display().