Cataclysm BN: src/game_ui.h File Reference
game_ui.h File Reference
Namespaces
namespace game_ui
Macros
#define CATA_SRC_GAME_UI_H
Functions
void game_ui::init_ui ()
void to_map_font_dim_width (int &w)
void to_map_font_dim_height (int &h)
void to_map_font_dimension (int &w, int &h)
void from_map_font_dimension (int &w, int &h)
void to_overmap_font_dimension (int &w, int &h)
void reinitialize_framebuffer (bool force_invalidate=false)
Macro Definition Documentation
CATA_SRC_GAME_UI_H
#define CATA_SRC_GAME_UI_H
Definition at line 3 of file game_ui.h.
Function Documentation
from_map_font_dimension()
void from_map_font_dimension (int & w, int & h)
Definition at line 24 of file game_ui.cpp.
{
    return;
}
reinitialize_framebuffer()
void reinitialize_framebuffer (bool force_invalidate = false)
Definition at line 5 of file game_ui.cpp.
{
    return;
}
Referenced by ui_adaptor::redraw_invalidated(), and ui_adaptor::ui_adaptor().
to_map_font_dim_height()
void to_map_font_dim_height (int & h)
Definition at line 15 of file game_ui.cpp.
{
    return;
}
to_map_font_dim_width()
void to_map_font_dim_width (int & w)
Definition at line 10 of file game_ui.cpp.
{
    return;
}
Referenced by centerlistview().
to_map_font_dimension()
void to_map_font_dimension (int & w, int & h)
Definition at line 20 of file game_ui.cpp.
{
    return;
}
Referenced by game::create_or_get_main_ui_adaptor(), and panel_manager::show_adm().
to_overmap_font_dimension()
void to_overmap_font_dimension (int & w, int & h)
Definition at line 28 of file game_ui.cpp.
{
    return;
}
Referenced by overmap_ui::display().