Cataclysm BN: src/game_inventory.cpp File Reference
game_inventory.cpp File Reference
#include "game_inventory.h"
#include <algorithm>
#include <bitset>
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>
#include "avatar.h"
#include "avatar_functions.h"
#include "bionics.h"
#include "calendar.h"
#include "cata_utility.h"
#include "crafting.h"
#include "character.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "color.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "examine_item_menu.h"
#include "game.h"
#include "input.h"
#include "inventory.h"
#include "inventory_ui.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "map.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_utils.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
Classes
class inventory_filter_preset
class armor_inventory_preset
class wear_inventory_preset
class take_off_inventory_preset
class pickup_inventory_preset
class disassemble_inventory_preset
class comestible_inventory_preset
class comestible_filtered_inventory_preset
class activatable_inventory_preset
class gunmod_inventory_preset
class read_inventory_preset
class steal_inventory_preset
class weapon_inventory_preset
class holster_inventory_preset
class saw_barrel_inventory_preset
class saw_stock_inventory_preset
class salvage_inventory_preset
class repair_inventory_preset
class bionic_install_preset
class bionic_install_surgeon_preset
class bionic_uninstall_preset
class bionic_sterilize_preset
Namespaces
namespace anonymous_namespace{game_inventory.cpp}
Typedefs
using item_filter = std::function< bool(const item &)>
using item_location_filter = std::function< bool(const item_location &)>
Functions
static const std::string flag_ALLOWS_REMOTE_USE ("ALLOWS_REMOTE_USE")
static const std::string flag_FILTHY ("FILTHY")
static const std::string flag_IN_CBM ("IN_CBM")
static const std::string flag_MUSHY ("MUSHY")
static const std::string flag_LIQUIDCONT ("LIQUIDCONT")
static const std::string flag_USE_EAT_VERB ("USE_EAT_VERB")
std::string anonymous_namespace{game_inventory.cpp}::good_bad_none (int value)
std::string anonymous_namespace{game_inventory.cpp}::highlight_good_bad_none (int value)
int anonymous_namespace{game_inventory.cpp}::anesthetic_requirement (int mult)
static item_location_filter convert_filter (const item_filter &filter)
static item_location inv_internal (player &u, const inventory_selector_preset &preset, const std::string &title, int radius, const std::string &none_message, const std::string &hint=std::string())
static std::string get_consume_needs_hint (player &p)
static item_location autodoc_internal (player &u, player &patient, const inventory_selector_preset &preset, int radius, bool uninstall=false, bool surgeon=false)
static item_location autoclave_internal (player &u, const inventory_selector_preset &preset, int radius)
Variables
static const activity_id ACT_EAT_MENU ("ACT_EAT_MENU")
static const activity_id ACT_CONSUME_FOOD_MENU ("ACT_CONSUME_FOOD_MENU")
static const activity_id ACT_CONSUME_DRINK_MENU ("ACT_CONSUME_DRINK_MENU")
static const activity_id ACT_CONSUME_MEDS_MENU ("ACT_CONSUME_MEDS_MENU")
static const fault_id fault_bionic_nonsterile ("fault_bionic_nonsterile")
static const skill_id skill_computer ("computer")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_firstaid ("firstaid")
static const quality_id qual_ANESTHESIA ("ANESTHESIA")
static const bionic_id bio_painkiller ("bio_painkiller")
static const bionic_id bio_taste_blocker ("bio_taste_blocker")
static const trait_id trait_DEBUG_BIONICS ("DEBUG_BIONICS")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_SAPROPHAGE ("SAPROPHAGE")
static const trait_id trait_SAPROVORE ("SAPROVORE")
static const flag_str_id flag_BIONIC_NPC_USABLE ("BIONIC_NPC_USABLE")
Typedef Documentation
item_filter
using item_filter = std::function<bool (const item &)>
Definition at line 91 of file game_inventory.cpp.
item_location_filter
using item_location_filter = std::function<bool (const item_location &)>
Definition at line 92 of file game_inventory.cpp.
Function Documentation
autoclave_internal()
static item_location autoclave_internal (player & u, const inventory_selector_preset & preset, int radius) static
Definition at line 2162 of file game_inventory.cpp.
{
    inventory_pick_selector inv_s( u, preset );
    inv_s.set_title( _( "Sterilization" ) );
    inv_s.set_hint( _( "<color_yellow>Select one CBM to sterilize</color>" ) );
    inv_s.set_display_stats( false );
    do {
        u.inv.restack( u );
        inv_s.clear_items();
        inv_s.add_character_items( u );
        inv_s.add_nearby_items( radius );
        if( inv_s.empty() ) {
            popup( _( "You don't have any CBM to sterilize." ), PF_GET_KEY );
            return item_location();
        }
        item_location location = inv_s.execute();
        if( inv_s.keep_open ) {
            inv_s.keep_open = false;
            continue;
        }
        return location;
    } while( true );
}
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), inventory_selector::clear_items(), inventory_selector::empty(), inventory_pick_selector::execute(), Character::inv, inventory_selector::keep_open, PF_GET_KEY, popup(), inventory::restack(), inventory_selector::set_display_stats(), inventory_selector::set_hint(), and inventory_selector::set_title().
Referenced by game_menus::inv::sterilize_cbm().
autodoc_internal()
static item_location autodoc_internal (player & u, player & patient, const inventory_selector_preset & preset, int radius, bool uninstall = false, bool surgeon = false) static
Definition at line 1788 of file game_inventory.cpp.
{
    inventory_pick_selector inv_s( u, preset );
    std::string hint;
    int drug_count = 0;
    if( !surgeon ) {//surgeon use their own anesthetic, player just need money
        if( patient.has_trait( trait_NOPAIN ) ) {
            hint = _( "<color_yellow>Patient has Deadened nerves.  Anesthesia unneeded.</color>" );
        } else if( patient.has_bionic( bio_painkiller ) ) {
            hint = _( "<color_yellow>Patient has Sensory Dulling CBM installed.  Anesthesia unneeded.</color>" );
        } else {
            const inventory &crafting_inv = u.crafting_inventory();
            std::vector<const item *> a_filter = crafting_inv.items_with( []( const item & it ) {
                return it.has_quality( qual_ANESTHESIA );
            } );
            for( const item *anesthesia_item : a_filter ) {
                if( anesthesia_item->ammo_remaining() >= 1 ) {
                    drug_count += anesthesia_item->ammo_remaining();
                }
            }
            hint = string_format( _( "<color_yellow>Available anesthetic: %i mL</color>" ), drug_count );
        }
    }
    std::vector<const item *> install_programs = patient.crafting_inventory().items_with( [](
                const item & it ) -> bool { return it.has_flag( "BIONIC_INSTALLATION_DATA" ); } );
    if( !install_programs.empty() ) {
        hint += string_format(
                    _( "\n<color_light_green>Found bionic installation data.  Affected CBMs are marked with an asterisk.</color>" ) );
    }
    if( uninstall ) {
        inv_s.set_title( string_format( _( "Bionic removal patient: %s" ), patient.get_name() ) );
    } else {
        inv_s.set_title( string_format( _( "Bionic installation patient: %s" ), patient.get_name() ) );
    }
    inv_s.set_hint( hint );
    inv_s.set_display_stats( false );
    do {
        u.inv.restack( u );
        inv_s.clear_items();
        inv_s.add_character_items( u );
        inv_s.add_nearby_items( radius );
        if( inv_s.empty() ) {
            popup( _( "You don't have any bionics to install." ), PF_GET_KEY );
            return item_location();
        }
        item_location location = inv_s.execute();
        if( inv_s.keep_open ) {
            inv_s.keep_open = false;
            continue;
        }
        return location;
    } while( true );
}
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), bio_painkiller, inventory_selector::clear_items(), Character::crafting_inventory(), inventory_selector::empty(), inventory_pick_selector::execute(), Character::get_name(), Character::has_bionic(), item::has_flag(), visitable< T >::has_quality(), Character::has_trait(), Character::inv, visitable< T >::items_with(), inventory_selector::keep_open, PF_GET_KEY, popup(), qual_ANESTHESIA, inventory::restack(), inventory_selector::set_display_stats(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), and trait_NOPAIN.
Referenced by game_menus::inv::install_bionic(), and game_menus::inv::uninstall_bionic().
convert_filter()
static item_location_filter convert_filter (const item_filter & filter) static
Definition at line 149 of file game_inventory.cpp.
{
    return [ &filter ]( const item_location & loc ) {
        return filter( *loc );
    };
}
Referenced by game::inv_map_splice(), and game_menus::inv::titled_filter_menu().
flag_ALLOWS_REMOTE_USE()
static const std::string flag_ALLOWS_REMOTE_USE ("ALLOWS_REMOTE_USE") static
Referenced by activatable_inventory_preset::get_denial().
flag_FILTHY()
static const std::string flag_FILTHY ("FILTHY") static
Referenced by bionic_sterilize_preset::get_denial().
flag_IN_CBM()
static const std::string flag_IN_CBM ("IN_CBM") static
Referenced by bionic_uninstall_preset::is_shown().
flag_LIQUIDCONT()
static const std::string flag_LIQUIDCONT ("LIQUIDCONT") static
Referenced by comestible_inventory_preset::get_denial().
flag_MUSHY()
static const std::string flag_MUSHY ("MUSHY") static
Referenced by comestible_inventory_preset::comestible_inventory_preset().
flag_USE_EAT_VERB()
static const std::string flag_USE_EAT_VERB ("USE_EAT_VERB") static
Referenced by game_menus::inv::consume_drink(), and game_menus::inv::consume_food().
get_consume_needs_hint()
static std::string get_consume_needs_hint (player & p) static
Definition at line 742 of file game_inventory.cpp.
{
    auto hint = std::string();
    auto desc = p.get_hunger_description();
    hint.append( string_format( "%s %s", _( "Food :" ), colorize( desc.first, desc.second ) ) );
    hint.append( string_format( " %s ", LINE_XOXO_S ) );
    desc = p.get_thirst_description();
    hint.append( string_format( "%s %s", _( "Drink:" ), colorize( desc.first, desc.second ) ) );
    hint.append( string_format( " %s ", LINE_XOXO_S ) );
    desc = p.get_pain_description();
    hint.append( string_format( "%s %s", _( "Pain :" ), colorize( desc.first, desc.second ) ) );
    hint.append( string_format( " %s ", LINE_XOXO_S ) );
    desc = p.get_fatigue_description();
    hint.append( string_format( "%s %s", _( "Rest :" ), colorize( desc.first, desc.second ) ) );
    return hint;
}
References _, colorize(), Character::get_fatigue_description(), Character::get_hunger_description(), Character::get_pain_description(), Character::get_thirst_description(), LINE_XOXO_S, and string_format().
Referenced by game_menus::inv::consume(), game_menus::inv::consume_drink(), game_menus::inv::consume_food(), and game_menus::inv::consume_meds().
inv_internal()
static item_location inv_internal (player & u, const inventory_selector_preset & preset, const std::string & title, int radius, const std::string & none_message, const std::string & hint = std::string()) static
Definition at line 156 of file game_inventory.cpp.
{
    inventory_pick_selector inv_s( u, preset );
    inv_s.set_title( title );
    inv_s.set_hint( hint );
    inv_s.set_display_stats( false );
    std::pair<size_t, size_t> init_pair;
    bool init_selection = false;
    std::string init_filter;
    bool has_init_filter = false;
    const std::vector<activity_id> consuming {
        ACT_EAT_MENU,
        ACT_CONSUME_FOOD_MENU,
        ACT_CONSUME_DRINK_MENU,
        ACT_CONSUME_MEDS_MENU };
    if( u.has_activity( consuming ) && u.activity.values.size() >= 2 ) {
        init_pair.first = u.activity.values[0];
        init_pair.second = u.activity.values[1];
        init_selection = true;
    }
    if( u.has_activity( consuming ) && !u.activity.str_values.empty() ) {
        init_filter = u.activity.str_values[0];
        has_init_filter = true;
    }
    do {
        u.inv.restack( u );
        inv_s.clear_items();
        inv_s.add_character_items( u );
        inv_s.add_nearby_items( radius );
        if( has_init_filter ) {
            inv_s.set_filter( init_filter );
            has_init_filter = false;
        }
        // Set position after filter to keep cursor at the right position
        if( init_selection ) {
            inv_s.select_position( init_pair );
            init_selection = false;
        }
        if( inv_s.empty() ) {
            const std::string msg = none_message.empty()
                                    ? _( "You don't have the necessary item at hand." )
                                    : none_message;
            popup( msg, PF_GET_KEY );
            return item_location();
        }
        item_location location = inv_s.execute();
        if( inv_s.keep_open ) {
            inv_s.keep_open = false;
            continue;
        }
        if( u.has_activity( consuming ) ) {
            u.activity.values.clear();
            init_pair = inv_s.get_selection_position();
            u.activity.values.push_back( init_pair.first );
            u.activity.values.push_back( init_pair.second );
            u.activity.str_values.clear();
            u.activity.str_values.emplace_back( inv_s.get_filter() );
        }
        return location;
    } while( true );
}
References _, ACT_CONSUME_DRINK_MENU, ACT_CONSUME_FOOD_MENU, ACT_CONSUME_MEDS_MENU, ACT_EAT_MENU, Character::activity, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), inventory_selector::clear_items(), inventory_selector::empty(), inventory_pick_selector::execute(), inventory_selector::get_filter(), inventory_selector::get_selection_position(), Character::has_activity(), catacurses::init_pair(), Character::inv, inventory_selector::keep_open, PF_GET_KEY, popup(), inventory::restack(), inventory_selector::select_position(), inventory_selector::set_display_stats(), inventory_selector::set_filter(), inventory_selector::set_hint(), inventory_selector::set_title(), player_activity::str_values, PATH_INFO::title(), and player_activity::values.
Referenced by game_menus::inv::consume(), game_menus::inv::consume_drink(), game_menus::inv::consume_food(), game_menus::inv::consume_meds(), game_menus::inv::container_for(), game_menus::inv::disassemble(), game_menus::inv::gun_to_modify(), game_menus::inv::holster(), game::inv_map_splice(), game_menus::inv::read(), game_menus::inv::repair(), game_menus::inv::salvage(), game_menus::inv::saw_barrel(), game_menus::inv::saw_stock(), game_menus::inv::steal(), game_menus::inv::take_off(), game_menus::inv::titled_filter_menu(), game_menus::inv::titled_menu(), game_menus::inv::use(), game_menus::inv::wear(), and game_menus::inv::wield().
Variable Documentation
ACT_CONSUME_DRINK_MENU
const activity_id ACT_CONSUME_DRINK_MENU("ACT_CONSUME_DRINK_MENU") ("ACT_CONSUME_DRINK_MENU") static
Referenced by game_menus::inv::consume_drink(), and inv_internal().
ACT_CONSUME_FOOD_MENU
const activity_id ACT_CONSUME_FOOD_MENU("ACT_CONSUME_FOOD_MENU") ("ACT_CONSUME_FOOD_MENU") static
Referenced by game_menus::inv::consume_food(), and inv_internal().
ACT_CONSUME_MEDS_MENU
const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU") ("ACT_CONSUME_MEDS_MENU") static
Referenced by game_menus::inv::consume_meds(), and inv_internal().
ACT_EAT_MENU
const activity_id ACT_EAT_MENU("ACT_EAT_MENU") ("ACT_EAT_MENU") static
Referenced by game_menus::inv::consume(), and inv_internal().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by autodoc_internal().
bio_taste_blocker
const bionic_id bio_taste_blocker("bio_taste_blocker") ("bio_taste_blocker") static
Referenced by comestible_inventory_preset::comestible_inventory_preset().
fault_bionic_nonsterile
const fault_id fault_bionic_nonsterile("fault_bionic_nonsterile") ("fault_bionic_nonsterile") static
Referenced by bionic_install_preset::get_denial(), bionic_install_surgeon_preset::get_denial(), and bionic_sterilize_preset::is_shown().
flag_BIONIC_NPC_USABLE
const flag_str_id flag_BIONIC_NPC_USABLE("BIONIC_NPC_USABLE") ("BIONIC_NPC_USABLE") static
Referenced by bionic_install_preset::get_denial(), and bionic_install_surgeon_preset::get_denial().
qual_ANESTHESIA
const quality_id qual_ANESTHESIA("ANESTHESIA") ("ANESTHESIA") static
Referenced by autodoc_internal().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), and bionic_uninstall_preset::get_failure_chance().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), and bionic_uninstall_preset::get_failure_chance().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), and bionic_uninstall_preset::get_failure_chance().
trait_DEBUG_BIONICS
const trait_id trait_DEBUG_BIONICS("DEBUG_BIONICS") ("DEBUG_BIONICS") static
Referenced by bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), and bionic_uninstall_preset::get_failure_chance().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by autodoc_internal().
trait_SAPROPHAGE
const trait_id trait_SAPROPHAGE("SAPROPHAGE") ("SAPROPHAGE") static
Referenced by comestible_inventory_preset::get_order().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by comestible_inventory_preset::get_order().