Cataclysm BN: src/generic_readers.h File Reference
generic_readers.h File Reference
#include <map>
#include <vector>
#include "cata_void.h"
#include "json.h"
#include "units.h"
Classes
struct supports_relative< T, typename >
struct supports_relative< T, cata::void_t< decltype(std::declval< T & >()+=std::declval< T & >())> >
struct supports_relative< bool >
struct supports_relative< std::string >
struct reader_detail::handler< T >
struct reader_detail::handler< std::set< T > >
struct reader_detail::handler< std::bitset< N > >
struct reader_detail::handler< enum_bitset< E > >
struct reader_detail::handler< std::vector< T > >
class generic_typed_reader< Derived >
Base class for reading generic objects from JSON.
class auto_flags_reader< FlagType >
Converts the JSON string to some type that must be construable from a std::string, e.g.
class unit_reader< T >
class volume_reader
class mass_reader
class temperature_reader
class typed_flag_reader< T >
Uses a map (unordered or standard) to convert strings from JSON to some other type (the mapped type of the map: C::mapped_type).
class enum_flags_reader< E >
Uses io::string_to_enum to convert the string from JSON to a C++ enum.
class string_id_reader< T >
A generic class to store objects identified by a string_id.
Namespaces
namespace reader_detail
Macros
#define CATA_SRC_GENERIC_READERS_H
Typedefs
using string_reader = auto_flags_reader<>
Functions
template<typename T >
typed_flag_reader< T > make_flag_reader (const std::map< std::string, T > &m, const std::string &e)
bool legacy_volume_reader (const JsonObject &jo, const std::string &member_name, units::volume &value, bool)
Reads a volume value from legacy format: JSON contains a integer which represents multiples of units::legacy_volume_factor (250 ml).
Macro Definition Documentation
CATA_SRC_GENERIC_READERS_H
#define CATA_SRC_GENERIC_READERS_H
Definition at line 3 of file generic_readers.h.
Typedef Documentation
string_reader
using string_reader = auto_flags_reader<>
Definition at line 322 of file generic_readers.h.
Function Documentation
legacy_volume_reader()
bool legacy_volume_reader (const JsonObject & jo, const std::string & member_name, units::volume & value, bool) inline
Reads a volume value from legacy format: JSON contains a integer which represents multiples of units::legacy_volume_factor (250 ml).
Definition at line 461 of file generic_readers.h.
{
    int legacy_value;
    if( !jo.read( member_name, legacy_value ) ) {
        return false;
    }
    value = legacy_value * units::legacy_volume_factor;
    return true;
}
References units::legacy_volume_factor, and JsonObject::read().
Referenced by furn_t::load().
make_flag_reader()
template<typename T > typed_flag_reader< T > make_flag_reader (const std::map< std::string, T > & m, const std::string & e)
Definition at line 414 of file generic_readers.h.
{
    return typed_flag_reader<T> { m, e };
}
Referenced by overmap_connection::subtype::load(), mtype::load(), and oter_type_t::load().