Cataclysm BN: src/generic_factory.h File Reference
generic_factory.h File Reference
Helper for loading from JSON.
#include <algorithm>
#include <bitset>
#include <set>
#include <unordered_map>
#include <vector>
#include "assign.h"
#include "catacharset.h"
#include "cata_void.h"
#include "debug.h"
#include "enum_bitset.h"
#include "generic_readers.h"
#include "init.h"
#include "int_id.h"
#include "json.h"
#include "mod_tracker.h"
#include "output.h"
#include "string_id.h"
#include "translations.h"
#include "units.h"
#include "wcwidth.h"
Classes
class generic_factory< T >
class generic_factory< T >::Version
Wrapper around generic_factory::version.
struct supports_proportional< T, typename >
struct supports_proportional< T, cata::void_t< decltype(std::declval< T & >() *=std::declval< float >())> >
struct supports_proportional< bool >
Macros
#define CATA_SRC_GENERIC_FACTORY_H
Functions
bool one_char_symbol_reader (const JsonObject &jo, const std::string &member_name, int &sym, bool)
Reads a string and stores the first byte of it in sym.
bool unicode_codepoint_from_symbol_reader (const JsonObject &jo, const std::string &member_name, uint32_t &member, bool)
Reads a UTF-8 string (or int as legacy fallback) and stores Unicode codepoint of it in symbol.
Implementation of <tt>mandatory</tt> and <tt>optional</tt>.
template<typename MemberType >
void mandatory (const JsonObject &jo, const bool was_loaded, const std::string &name, MemberType &member)
template<typename MemberType , typename ReaderType >
void mandatory (const JsonObject &jo, const bool was_loaded, const std::string &name, MemberType &member, const ReaderType &reader)
template<typename MemberType , std::enable_if_t< !supports_proportional< MemberType >::value > * = nullptr>
bool handle_proportional (const JsonObject &jo, const std::string &name, MemberType &)
template<typename MemberType , std::enable_if_t< !supports_relative< MemberType >::value > * = nullptr>
bool handle_relative (const JsonObject &jo, const std::string &name, MemberType &)
template<typename MemberType >
void optional (const JsonObject &jo, const bool was_loaded, const std::string &name, MemberType &member)
template<typename MemberType , typename DefaultType = MemberType, typename = typename std::enable_if<std::is_constructible<MemberType, const DefaultType &>::value>::type>
void optional (const JsonObject &jo, const bool was_loaded, const std::string &name, MemberType &member, const DefaultType &default_value)
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType, typename = typename std::enable_if < !std::is_constructible<MemberType, const ReaderType &>::value >::type>
void optional (const JsonObject &jo, const bool was_loaded, const std::string &name, MemberType &member, const ReaderType &reader)
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType>
void optional (const JsonObject &jo, const bool was_loaded, const std::string &name, MemberType &member, const ReaderType &reader, const DefaultType &default_value)
Detailed Description
Helper for loading from JSON.
Loading (inside a T::load(JsonObject &jo) function) can be done with two functions (defined here):
mandatory loads required data and throws an error if the JSON data does not contain the required data.
optional is for optional data, it has the same parameters and an additional default value that will be used if the JSON data does not contain the requested data. It may throw an error if the existing data is not valid (e.g. string instead of requested int).
The functions are designed to work with the generic_factory and therefor support the was_loaded parameter (set be generic_factory::load). If that parameter is true, it is assumed the object has already been loaded and missing JSON data is simply ignored (the default value is not applied and no error is thrown upon missing mandatory data).
The parameters are this:
JsonObject jo the object to load from.
bool was_loaded whether the object had already been loaded completely.
std::string member_name the name of the JSON member to load from.
T &member a reference to the C++ object to store the loaded data.
(for optional) a default value of any type that can be assigned to member.
Both functions use the native read functions of JsonIn (see there) to load the value.
Example:
class Dummy {
    bool was_loaded = false;
    int a;
    std::string b;
    void load(JsonObject &jo) {
        mandatory(jo, was_loaded, "a", a);
        optional(jo, was_loaded, "b", b, "default value of b");
    }
};
This only works if there is function with the matching type defined in JsonIn. For other types, or if the loaded value needs to be converted (e.g. to nc_color), one can use the reader classes/functions. mandatory and optional have an overload that requires the same parameters and an additional reference to such a reader object.
class Dummy2 {
    bool was_loaded = false;
    int b;
    nc_color c;
    void load(JsonObject &jo) {
        mandatory(jo, was_loaded, "b", b); // uses JsonIn::read(int&)
    }
};
Both versions of optional have yet another overload that does not require an explicit default value, a default initialized object of the member type will be used instead.
Readers must provide the following function: `bool operator()(const JsonObject &jo, const std::string &member_name, T &member, bool was_loaded) const
(This can be implemented as free function or as operator in a class.)
The parameters are the same as the for the mandatory function (see above). The function shall returntrueif the loading was done, orfalse` if the JSON data did not contain the requested member. If loading fails because of invalid data (but not missing data), it should throw.
Definition in file generic_factory.h.
Macro Definition Documentation
CATA_SRC_GENERIC_FACTORY_H
#define CATA_SRC_GENERIC_FACTORY_H
Definition at line 3 of file generic_factory.h.
Function Documentation
handle_proportional()
template<typename MemberType , std::enable_if_t< !supports_proportional< MemberType >::value > * = nullptr> bool handle_proportional (const JsonObject & jo, const std::string & name, MemberType & member) inline
Definition at line 703 of file generic_factory.h.
{
    if( jo.has_object( "proportional" ) ) {
        JsonObject proportional = jo.get_object( "proportional" );
        proportional.allow_omitted_members();
        if( proportional.has_member( name ) ) {
            debugmsg( "Member %s of type %s does not support proportional", name, typeid( MemberType ).name() );
        }
    }
    return false;
}
References JsonObject::allow_omitted_members(), debugmsg, JsonObject::get_object(), JsonObject::has_member(), JsonObject::has_object(), and om_direction::name().
Referenced by generic_typed_reader< Derived >::operator()(), and optional().
handle_relative()
template<typename MemberType , std::enable_if_t< !supports_relative< MemberType >::value > * = nullptr> bool handle_relative (const JsonObject & jo, const std::string & name, MemberType & member) inline
Definition at line 751 of file generic_factory.h.
{
    if( jo.has_object( "relative" ) ) {
        JsonObject relative = jo.get_object( "relative" );
        relative.allow_omitted_members();
        if( !relative.has_member( name ) ) {
            return false;
        }
        debugmsg( "Member %s of type %s does not support relative", name, typeid( MemberType ).name() );
    }
    return false;
}
References debugmsg, JsonObject::get_object(), JsonObject::has_object(), and om_direction::name().
Referenced by optional().
mandatory() [1/2]
template<typename MemberType > void mandatory (const JsonObject & jo, const bool was_loaded, const std::string & name, MemberType & member) inline
Definition at line 611 of file generic_factory.h.
{
    if( !jo.read( name, member ) ) {
        if( !was_loaded ) {
            if( jo.has_member( name ) ) {
                jo.throw_error( "failed to read mandatory member \"" + name + "\"" );
            } else {
                jo.throw_error( "missing mandatory member \"" + name + "\"" );
            }
        }
    }
}
References JsonObject::has_member(), mapgen_defer::member, om_direction::name(), JsonObject::read(), and JsonObject::throw_error().
Referenced by add_if_exists(), snippet_library::add_snippet_from_json(), overmap_spawns::deserialize(), overmap_static_spawns::deserialize(), overmap_special_terrain::deserialize(), overmap_special_connection::deserialize(), achievement::load(), event_statistic::load(), score::load(), islot_ammo::load(), fake_spell::load(), overmap_connection::subtype::load(), zone_type::load(), item_category::load(), spell_type::load(), ter_furn_transform::load(), anatomy::load(), body_part_type::load(), clothing_mod::load(), construction::load(), construction_category::load(), construction_group::load(), construction_sequence::load(), field_type::load(), anonymous_namespace{gates.cpp}::gate_data::load(), map_extra::load(), map_data_common_t::load(), ma_technique::load(), ma_buff::load(), martialart::load(), mission_type::load(), morale_type_data::load(), mtype::load(), mutation_branch::load(), npc_class::load(), overmap_connection::load(), overmap_special::load(), profession::load(), quality::load(), rotatable_symbols::load(), scenario::load(), skill_boost::load(), start_location::load(), trap::load(), weather_type::load(), ter_t::load(), furn_t::load(), material_type::load(), bionic_data::load(), zone_priority_data::load(), fault::load_fault(), and mon_spellcasting_actor::load_internal().
mandatory() [2/2]
template<typename MemberType , typename ReaderType > void mandatory (const JsonObject & jo, const bool was_loaded, const std::string & name, MemberType & member, const ReaderType & reader) inline
Definition at line 625 of file generic_factory.h.
{
    if( !reader( jo, name, member, was_loaded ) ) {
        if( !was_loaded ) {
            if( jo.has_member( name ) ) {
                jo.throw_error( "failed to read mandatory member \"" + name + "\"" );
            } else {
                jo.throw_error( "missing mandatory member \"" + name + "\"" );
            }
        }
    }
}
References JsonObject::has_member(), mapgen_defer::member, om_direction::name(), and JsonObject::throw_error().
one_char_symbol_reader()
bool one_char_symbol_reader (const JsonObject & jo, const std::string & member_name, int & sym, bool) inline
Reads a string and stores the first byte of it in sym.
Throws if the input contains more or less than one byte.
Definition at line 851 of file generic_factory.h.
{
    std::string sym_as_string;
    if( !jo.read( member_name, sym_as_string ) ) {
        return false;
    }
    if( sym_as_string.size() != 1 ) {
        jo.throw_error( member_name + " must be exactly one ASCII character", member_name );
    }
    sym = sym_as_string.front();
    return true;
}
References JsonObject::read(), and JsonObject::throw_error().
Referenced by trap::load().
optional() [1/4]
template<typename MemberType > void optional (const JsonObject & jo, const bool was_loaded, const std::string & name, MemberType & member) inline
Definition at line 791 of file generic_factory.h.
{
    if( !jo.read( name, member ) && !handle_proportional( jo, name, member ) &&
        !handle_relative( jo, name, member ) ) {
        if( !was_loaded ) {
            member = MemberType();
        }
    }
}
References handle_proportional(), handle_relative(), mapgen_defer::member, om_direction::name(), and JsonObject::read().
Referenced by overmap_special_terrain::deserialize(), overmap_special_connection::deserialize(), achievement::load(), event_transformation::load(), event_statistic::load(), score::load(), islot_ammo::load(), fake_spell::load(), overmap_connection::subtype::load(), zone_type::load(), item_category::load(), spell_type::load(), ter_furn_transform::load(), ammo_effect::load(), behavior::node_t::load(), body_part_type::load(), clothing_mod::load(), construction::load(), construction_sequence::load(), field_type::load(), json_flag::load(), anonymous_namespace{gates.cpp}::gate_data::load(), map_extra::load(), map_data_common_t::load(), ma_requirements::load(), ma_technique::load(), ma_buff::load(), martialart::load(), mission_type::load(), species_type::load(), morale_type_data::load(), mtype::load(), mutation_branch::load(), npc_class::load(), overmap_land_use_code::load(), oter_type_t::load(), overmap_location::load(), overmap_special::load(), profession::load(), scenario::load(), start_location::load(), trap::load(), weather_type::load(), ter_t::load(), furn_t::load(), enchantment::load(), material_type::load(), zone_priority_data::load(), fault::load_fault(), mon_spellcasting_actor::load_internal(), and melee_actor::load_internal().
optional() [2/4]
template<typename MemberType , typename DefaultType = MemberType, typename = typename std::enable_if<std::is_constructible<MemberType, const DefaultType &>::value>::type> void optional (const JsonObject & jo, const bool was_loaded, const std::string & name, MemberType & member, const DefaultType & default_value) inline
Definition at line 813 of file generic_factory.h.
{
    if( !jo.read( name, member ) && !handle_proportional( jo, name, member ) &&
        !handle_relative( jo, name, member ) ) {
        if( !was_loaded ) {
            member = default_value;
        }
    }
}
References handle_proportional(), handle_relative(), mapgen_defer::member, om_direction::name(), and JsonObject::read().
optional() [3/4]
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType, typename = typename std::enable_if < !std::is_constructible<MemberType, const ReaderType &>::value >::type> void optional (const JsonObject & jo, const bool was_loaded, const std::string & name, MemberType & member, const ReaderType & reader) inline
Definition at line 826 of file generic_factory.h.
{
    if( !reader( jo, name, member, was_loaded ) ) {
        if( !was_loaded ) {
            member = MemberType();
        }
    }
}
References mapgen_defer::member, and om_direction::name().
optional() [4/4]
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType> void optional (const JsonObject & jo, const bool was_loaded, const std::string & name, MemberType & member, const ReaderType & reader, const DefaultType & default_value) inline
Definition at line 836 of file generic_factory.h.
{
    if( !reader( jo, name, member, was_loaded ) ) {
        if( !was_loaded ) {
            member = default_value;
        }
    }
}
References mapgen_defer::member, and om_direction::name().
unicode_codepoint_from_symbol_reader()
bool unicode_codepoint_from_symbol_reader (const JsonObject & jo, const std::string & member_name, uint32_t & member, bool) inline
Reads a UTF-8 string (or int as legacy fallback) and stores Unicode codepoint of it in symbol.
Throws if the inputs width is more than one console cell wide.
Definition at line 869 of file generic_factory.h.
{
    int sym_as_int;
    std::string sym_as_string;
    if( !jo.read( member_name, sym_as_string, false ) ) {
        // Legacy fallback to integer `sym`.
        if( !jo.read( member_name, sym_as_int ) ) {
            return false;
        } else {
            sym_as_string = string_from_int( sym_as_int );
        }
    }
    uint32_t sym_as_codepoint = UTF8_getch( sym_as_string );
    if( mk_wcwidth( sym_as_codepoint ) != 1 ) {
        jo.throw_error( member_name + " must be exactly one console cell wide", member_name );
    }
    member = sym_as_codepoint;
    return true;
}
References mapgen_defer::member, mk_wcwidth(), JsonObject::read(), string_from_int(), JsonObject::throw_error(), and UTF8_getch().
Referenced by field_type::load(), map_extra::load(), overmap_land_use_code::load(), oter_type_t::load(), and weather_type::load().