Cataclysm BN: "Weather and its implications."
"Weather and its implications."
Namespaces
namespace weather
Classes
struct forecast_period
Functions
weather_manager & get_weather ()
static bool is_player_outside ()
void glare (const weather_type_id &w)
Glare.
int incident_sunlight (const weather_type_id &wtype, const time_point &t)
Amount of sunlight incident at the ground, taking weather and time of day into account.
void proc_weather_sum (const weather_type_id wtype, weather_sum &data, const time_point &t, const time_duration &tick_size)
const weather_type_id & current_weather (const tripoint &location, const time_point &t)
weather_sum sum_conditions (const time_point &start, const time_point &end, const tripoint &location)
void retroactively_fill_from_funnel (item &it, const trap &tr, const time_point &start, const time_point &end, const tripoint &pos)
Determine what a funnel has filled out of game, using funnelcontainer.bday as a starting point.
double funnel_charges_per_turn (const double surface_area_mm2, const double rain_depth_mm_per_hour)
static void fill_funnels (int rain_depth_mm_per_hour, bool acid, const trap &tr)
Main routine for filling funnels from weather effects.
static void fill_water_collectors (int mmPerHour, bool acid)
Fill funnels and makeshift funnels from weather effects.
double precip_mm_per_hour (precip_class const p)
void handle_weather_effects (const weather_type_id &w)
static std::string to_string (const weekdays &d)
static std::string print_time_just_hour (const time_point &p)
std::string weather_forecast (const point_abs_sm &abs_sm_pos)
Generate textual weather forecast for the specified radio tower.
std::string print_temperature (double fahrenheit, int decimals)
Print temperature (and convert to Celsius if Celsius display is enabled.)
std::string print_temperature (units::temperature temperature, int decimals)
std::string print_humidity (double humidity, int decimals)
Print relative humidity (no conversions.)
std::string print_pressure (double pressure, int decimals)
Print pressure (no conversions.)
static double local_windchill_lowtemp (double temperature_f, double, double wind_mph)
static double local_windchill_hightemp (double temperature_f, double humidity, double wind_mph)
int get_local_windchill (double temperature_f, double humidity, double wind_mph)
nc_color get_wind_color (double windpower)
std::string get_shortdirstring (int angle)
std::string get_dirstring (int angle)
std::string get_wind_arrow (int dirangle)
int get_local_humidity (double humidity, const weather_type_id &weather, bool sheltered)
double get_local_windpower (double windpower, const oter_id &omter, const tripoint &location, const int &winddirection, bool sheltered)
bool is_wind_blocker (const tripoint &location)
std::string get_wind_desc (double windpower)
rl_vec2d convert_wind_to_coord (const int angle)
bool warm_enough_to_plant (const tripoint &pos)
Is it warm enough to plant seeds?
bool warm_enough_to_plant (const tripoint_abs_omt &pos)
void weather_effect::wet_player (int amount)
Main routine for wet effects caused by weather.
void weather_effect::thunder (int intensity)
Thunder.
void weather_effect::lightning (int intensity)
Lightning.
void weather_effect::light_acid (int intensity)
Acid drizzle.
void weather_effect::acid (int intensity)
Acid rain.
weather_manager::weather_manager ()
weather_manager::~weather_manager ()
const weather_generator & weather_manager::get_cur_weather_gen () const
void weather_manager::update_weather ()
void weather_manager::set_nextweather (time_point t)
int weather_manager::get_temperature (const tripoint &location) const
int weather_manager::get_temperature (const tripoint_abs_omt &location)
int weather_manager::get_water_temperature (const tripoint &location) const
void weather_manager::clear_temp_cache ()
Variables
constexpr int NUM_FORECAST_PERIODS = 6
Containers
Containers come in two flavors:
suitable for liquids (is_watertight_container),
and the remaining one (they are for currently only for flavor).
void item::add_rain_to_container (bool acid, int charges=1)
Add charge(s) of rain to given container, possibly contaminating it.
Funnels
Traps can act as funnels, for this they need a trap::funnel_radius_mm > 0.
Funnels are usual not hidden at all (trap::visibility == 0), are trap::benign and can be picked up easily (trap::difficulty == 0). The funnel filling is handled in weather.cpp. is_funnel is used the check whether the funnel specific code should be run for this trap.
double trap::funnel_turns_per_charge (double rain_depth_mm_per_hour) const
Detailed Description
Function Documentation
acid()
void weather_effect::acid (int intensity)
Acid rain.
Causes major pain. Damages non acid-proof mobs. Very wet (acid).
Definition at line 488 of file weather.cpp.
{
    if( calendar::once_every( time_duration::from_seconds( intensity ) ) && is_player_outside() ) {
        if( g->u.weapon.has_flag( "RAIN_PROTECT" ) && one_in( 4 ) ) {
            add_msg( _( "Your umbrella protects you from the acid rain." ) );
        } else {
            if( g->u.worn_with_flag( "RAINPROOF" ) && one_in( 2 ) ) {
                add_msg( _( "Your clothing protects you from the acid rain." ) );
            } else {
                bool has_helmet = false;
                if( g->u.is_wearing_power_armor( &has_helmet ) && ( has_helmet || !one_in( 2 ) ) ) {
                    add_msg( _( "Your power armor protects you from the acid rain." ) );
                } else {
                    add_msg( m_bad, _( "The acid rain burns!" ) );
                    if( one_in( 2 ) && ( g->u.get_pain() < 100 ) ) {
                        g->u.mod_pain( rng( 1, 5 ) );
                    }
                }
            }
        }
    }
}
References _, add_msg(), time_duration::from_seconds(), g, is_player_outside(), m_bad, calendar::once_every(), one_in(), and rng().
Referenced by weather_type::load().
add_rain_to_container()
void item::add_rain_to_container (bool acid, int charges = 1)
Add charge(s) of rain to given container, possibly contaminating it.
Definition at line 211 of file weather.cpp.
{
    if( charges <= 0 ) {
        return;
    }
    item ret( acid ? itype_water_acid : itype_water, calendar::turn );
    const int capa = get_remaining_capacity_for_liquid( ret, true );
    if( contents.empty() ) {
        // This is easy. Just add 1 charge of the rain liquid to the container.
        if( !acid ) {
            // Funnels aren't always clean enough for water. // TODO: disinfectant squeegie->funnel
            ret.poison = one_in( 10 ) ? 1 : 0;
        }
        ret.charges = std::min( charges, capa );
        put_in( ret );
    } else {
        // The container already has a liquid.
        item &liq = contents.front();
        int orig = liq.charges;
        int added = std::min( charges, capa );
        if( capa > 0 ) {
            liq.charges += added;
        }
        if( liq.typeId() == ret.typeId() || liq.typeId() == itype_water_acid_weak ) {
            // The container already contains this liquid or weakly acidic water.
            // Don't do anything special -- we already added liquid.
        } else {
            // The rain is different from what's in the container.
            // Turn the container's liquid into weak acid with a probability
            // based on its current volume.
            // If it's raining acid and this container started with 7
            // charges of water, the liquid will now be 1/8th acid or,
            // equivalently, 1/4th weak acid (the rest being water). A
            // stochastic approach gives the liquid a 1 in 4 (or 2 in
            // liquid.charges) chance of becoming weak acid.
            const bool transmute = x_in_y( 2 * added, liq.charges );
            if( transmute ) {
                contents.front() = item( itype_water_acid_weak, calendar::turn, liq.charges );
            } else if( liq.typeId() == itype_water ) {
                // The container has water, and the acid rain didn't turn it
                // into weak acid. Poison the water instead, assuming 1
                // charge of acid would act like a charge of water with poison 5.
                int total_poison = liq.poison * orig + 5 * added;
                liq.poison = total_poison / liq.charges;
                int leftover_poison = total_poison - liq.poison * liq.charges;
                if( leftover_poison > rng( 0, liq.charges ) ) {
                    liq.poison++;
                }
            }
        }
    }
}
References mattack::acid(), item::charges, item::contents, item_contents::empty(), item_contents::front(), item::get_remaining_capacity_for_liquid(), item::item(), itype_water, itype_water_acid, itype_water_acid_weak, one_in(), item::poison, item::put_in(), cata::hash64_detail::ret, rng(), calendar::turn, item::typeId(), and x_in_y().
Referenced by retroactively_fill_from_funnel().
clear_temp_cache()
void weather_manager::clear_temp_cache ()
Definition at line 1145 of file weather.cpp.
{
    temperature_cache.clear();
}
References weather_manager::temperature_cache.
convert_wind_to_coord()
rl_vec2d convert_wind_to_coord (const int angle)
Definition at line 1005 of file weather.cpp.
{
    static const std::array<std::pair<int, rl_vec2d>, 9> outputs = {{
            { 330, rl_vec2d( 0, -1 ) },
            { 301, rl_vec2d( -1, -1 ) },
            { 240, rl_vec2d( -1, 0 ) },
            { 211, rl_vec2d( -1, 1 ) },
            { 150, rl_vec2d( 0, 1 ) },
            { 121, rl_vec2d( 1, 1 ) },
            { 60, rl_vec2d( 1, 0 ) },
            { 31, rl_vec2d( 1, -1 ) },
            { 0, rl_vec2d( 0, -1 ) }
        }
    };
    for( const std::pair<int, rl_vec2d> &val : outputs ) {
        if( angle >= val.first ) {
            return val.second;
        }
    }
    return rl_vec2d( 0, 0 );
}
Referenced by get_local_windpower().
current_weather()
const weather_type_id & current_weather (const tripoint & location, const time_point & t)
Definition at line 143 of file weather.cpp.
{
    const weather_manager &weather = get_weather();
    const auto wgen = weather.get_cur_weather_gen();
    if( weather.weather_override ) {
        return weather.weather_override;
    }
    return wgen.get_weather_conditions( location, t, g->get_seed() );
}
References g, and get_weather().
Referenced by Character::burn_fuel(), sum_conditions(), and vehicle::total_solar_epower_w().
fill_funnels()
static void fill_funnels (int rain_depth_mm_per_hour, bool acid, const trap & tr) static
Main routine for filling funnels from weather effects.
Definition at line 319 of file weather.cpp.
{
    const double turns_per_charge = tr.funnel_turns_per_charge( rain_depth_mm_per_hour );
    // Give each funnel on the map a chance to collect the rain.
    const std::vector<tripoint> &funnel_locs = g->m.trap_locations( tr.loadid );
    for( const tripoint &loc : funnel_locs ) {
        units::volume maxcontains = 0_ml;
        if( one_in( turns_per_charge ) ) {
            // FIXME:
            //add_msg("%d mm/h %d tps %.4f: fill",int(calendar::turn),rain_depth_mm_per_hour,turns_per_charge);
            // This funnel has collected some rain! Put the rain in the largest
            // container here which is either empty or contains some mixture of
            // impure water and acid.
            map_stack items = g->m.i_at( loc );
            auto container = items.end();
            for( auto candidate_container = items.begin(); candidate_container != items.end();
                 ++candidate_container ) {
                if( candidate_container->is_funnel_container( maxcontains ) ) {
                    container = candidate_container;
                }
            }
            if( container != items.end() ) {
                container->add_rain_to_container( acid, 1 );
                container->set_age( 0_turns );
            }
        }
    }
}
References mattack::acid(), item_stack::begin(), item_stack::end(), trap::funnel_turns_per_charge(), g, trap::loadid, and one_in().
Referenced by fill_water_collectors().
fill_water_collectors()
static void fill_water_collectors (int mmPerHour, bool acid) static
Fill funnels and makeshift funnels from weather effects.
See also
fill_funnels
Definition at line 353 of file weather.cpp.
{
    for( auto &e : trap::get_funnels() ) {
        fill_funnels( mmPerHour, acid, *e );
    }
}
References mattack::acid(), fill_funnels(), and trap::get_funnels().
Referenced by handle_weather_effects().
funnel_charges_per_turn()
double funnel_charges_per_turn (const double surface_area_mm2, const double rain_depth_mm_per_hour)
Definition at line 267 of file weather.cpp.
{
    // 1mm rain on 1m^2 == 1 liter water == 1000ml
    // 1 liter == 4 volume
    // 1 volume == 250ml: containers
    // 1 volume == 200ml: water
    // How many charges of water can we collect in a turn (usually <1.0)?
    if( rain_depth_mm_per_hour == 0.0 ) {
        return 0.0;
    }
    // Calculate once, because that part is expensive
    // FIXME: make non-static
    static const item water( itype_water, calendar::start_of_cataclysm );
    // 250ml
    static const double charge_ml = static_cast<double>( to_gram( water.weight() ) ) /
                                    water.charges;
    const double vol_mm3_per_hour = surface_area_mm2 * rain_depth_mm_per_hour;
    const double vol_mm3_per_turn = vol_mm3_per_hour / to_turns<int>( 1_hours );
    const double ml_to_mm3 = 1000;
    const double charges_per_turn = vol_mm3_per_turn / ( charge_ml * ml_to_mm3 );
    return charges_per_turn;
}
References item::charges, itype_water, calendar::start_of_cataclysm, units::to_gram(), and item::weight().
Referenced by trap::funnel_turns_per_charge(), and vehicle::update_time().
funnel_turns_per_charge()
double trap::funnel_turns_per_charge (double rain_depth_mm_per_hour) const
Definition at line 294 of file weather.cpp.
{
    // 1mm rain on 1m^2 == 1 liter water == 1000ml
    // 1 liter == 4 volume
    // 1 volume == 250ml: containers
    // 1 volume == 200ml: water
    // How many turns should it take for us to collect 1 charge of rainwater?
    // "..."
    if( rain_depth_mm_per_hour == 0.0 ) {
        return 0.0;
    }
    const double surface_area_mm2 = M_PI * ( funnel_radius_mm * funnel_radius_mm );
    const double charges_per_turn = funnel_charges_per_turn( surface_area_mm2, rain_depth_mm_per_hour );
    if( charges_per_turn > 0.0 ) {
        return 1.0 / charges_per_turn;
    }
    return 0.0;
}
References funnel_charges_per_turn(), trap::funnel_radius_mm, and M_PI.
Referenced by fill_funnels(), and retroactively_fill_from_funnel().
get_cur_weather_gen()
const weather_generator & weather_manager::get_cur_weather_gen () const
Definition at line 1049 of file weather.cpp.
{
    const overmap &om = g->get_cur_om();
    const regional_settings &settings = om.get_settings();
    return settings.weather;
}
References g, coords::om, and regional_settings::weather.
Referenced by debug_menu::debug(), weather_manager::get_temperature(), Character::suffer_from_artifacts(), and weather_manager::update_weather().
get_dirstring()
std::string get_dirstring (int angle)
Definition at line 874 of file weather.cpp.
{
    // Convert angle to cardinal directions
    std::string dirstring;
    int dirangle = angle;
    if( dirangle <= 23 || dirangle > 338 ) {
        dirstring = _( "North" );
    } else if( dirangle <= 68 ) {
        dirstring = _( "North-East" );
    } else if( dirangle <= 113 ) {
        dirstring = _( "East" );
    } else if( dirangle <= 158 ) {
        dirstring = _( "South-East" );
    } else if( dirangle <= 203 ) {
        dirstring = _( "South" );
    } else if( dirangle <= 248 ) {
        dirstring = _( "South-West" );
    } else if( dirangle <= 293 ) {
        dirstring = _( "West" );
    } else {
        dirstring = _( "North-West" );
    }
    return dirstring;
}
References _.
Referenced by Character::activate_bionic(), and iuse::weather_tool().
get_local_humidity()
int get_local_humidity (double humidity, const weather_type_id & weather, bool sheltered)
Definition at line 924 of file weather.cpp.
{
    int tmphumidity = humidity;
    if( sheltered ) {
        // Norm for a house?
        tmphumidity = humidity * ( 100 - humidity ) / 100 + humidity;
    } else if( weather->rains &&
               weather->precip >= precip_class::light ) {
        tmphumidity = 100;
    }
    return tmphumidity;
}
References light.
Referenced by Character::activate_bionic(), Character::process_bionic(), Character::update_bodytemp(), and iuse::weather_tool().
get_local_windchill()
int get_local_windchill (double temperature_f, double humidity, double wind_mph)
Definition at line 797 of file weather.cpp.
{
    // The function must be continuous and strictly non-decreasing with temperature
    constexpr double low_temp = 30.0;
    constexpr double high_temp = 70.0;
    if( temperature_f >= high_temp ) {
        return std::ceil( local_windchill_hightemp( temperature_f, humidity, wind_mph ) );
    }
    // lerp-ing both functions results in a non-monotonous function
    double windchill_f_hightemp = local_windchill_hightemp( high_temp, humidity, wind_mph );
    double windchill_f_lowtemp = std::min( windchill_f_hightemp, local_windchill_lowtemp( low_temp,
                                           humidity, wind_mph ) );
    double t = ( temperature_f - low_temp ) / ( high_temp - low_temp );
    return std::ceil( lerp( std::min( windchill_f_lowtemp, windchill_f_hightemp ),
                            windchill_f_hightemp,
                            t ) );
}
References lerp(), local_windchill_hightemp(), and local_windchill_lowtemp().
Referenced by Character::activate_bionic(), Character::update_bodytemp(), and iuse::weather_tool().
get_local_windpower()
double get_local_windpower (double windpower, const oter_id & omter, const tripoint & location, const int & winddirection, bool sheltered)
A player is sheltered if he is underground, in a car, or indoors.
Definition at line 938 of file weather.cpp.
{
    /**
    *  A player is sheltered if he is underground, in a car, or indoors.
    **/
    if( sheltered ) {
        return 0;
    }
    rl_vec2d windvec = convert_wind_to_coord( winddirection );
    int tmpwind = static_cast<int>( windpower );
    tripoint triblocker( location + point( windvec.x, windvec.y ) );
    // Over map terrain may modify the effect of wind.
    if( is_ot_match( "forest", omter, ot_match_type::type ) ||
        is_ot_match( "forest_water", omter, ot_match_type::type ) ) {
        tmpwind = tmpwind / 2;
    }
    if( location.z > 0 ) {
        tmpwind = tmpwind + ( location.z * std::min( 5, tmpwind ) );
    }
    // An adjacent wall will block wind
    if( is_wind_blocker( triblocker ) ) {
        tmpwind = tmpwind / 10;
    }
    return static_cast<double>( tmpwind );
}
References convert_wind_to_coord(), is_ot_match(), is_wind_blocker(), type, rl_vec2d::x, rl_vec2d::y, and tripoint::z.
Referenced by Character::activate_bionic(), Character::burn_fuel(), draw_env_compact(), Character::passive_power_gen(), render_wind(), map::spread_gas(), sum_conditions(), vehicle::total_wind_epower_w(), Character::update_bodytemp(), and iuse::weather_tool().
get_shortdirstring()
std::string get_shortdirstring (int angle)
Definition at line 850 of file weather.cpp.
{
    std::string dirstring;
    int dirangle = angle;
    if( dirangle <= 23 || dirangle > 338 ) {
        dirstring = _( "N" );
    } else if( dirangle <= 68 ) {
        dirstring = _( "NE" );
    } else if( dirangle <= 113 ) {
        dirstring = _( "E" );
    } else if( dirangle <= 158 ) {
        dirstring = _( "SE" );
    } else if( dirangle <= 203 ) {
        dirstring = _( "S" );
    } else if( dirangle <= 248 ) {
        dirstring = _( "SW" );
    } else if( dirangle <= 293 ) {
        dirstring = _( "W" );
    } else {
        dirstring = _( "NW" );
    }
    return dirstring;
}
References _.
get_temperature() [1/2]
int weather_manager::get_temperature (const tripoint & location) const
Definition at line 1107 of file weather.cpp.
{
    const auto &cached = temperature_cache.find( location );
    if( cached != temperature_cache.end() ) {
        return cached->second;
    }
    // local modifier
    int temp_mod = 0;
    if( !g->new_game ) {
        temp_mod += get_heat_radiation( location, false );
        temp_mod += get_convection_temperature( location );
    }
    //underground temperature = average New England temperature = 43F/6C rounded to int
    const int temp = ( location.z < 0 ? AVERAGE_ANNUAL_TEMPERATURE : temperature ) +
                     ( g->new_game ? 0 : g->m.get_temperature( location ) + temp_mod );
    temperature_cache.emplace( std::make_pair( location, temp ) );
    return temp;
}
References AVERAGE_ANNUAL_TEMPERATURE, g, get_convection_temperature(), get_heat_radiation(), weather_manager::temperature, weather_manager::temperature_cache, and tripoint::z.
Referenced by Character::calc_needs_rates(), draw_speed_tab(), vehicle::engine_cold_factor(), Character::recalc_speed_bonus(), Character::suffer_in_sunlight(), and warm_enough_to_plant().
get_temperature() [2/2]
int weather_manager::get_temperature (const tripoint_abs_omt & location)
Definition at line 1129 of file weather.cpp.
{
    if( location.z() < 0 ) {
        return AVERAGE_ANNUAL_TEMPERATURE;
    }
    tripoint abs_ms = project_to<coords::ms>( location ).raw();
    w_point w = get_cur_weather_gen().get_weather( abs_ms, calendar::turn, g->get_seed() );
    return units::to_fahrenheit( w.temperature );
}
References AVERAGE_ANNUAL_TEMPERATURE, g, weather_manager::get_cur_weather_gen(), weather_generator::get_weather(), w_point::temperature, units::to_fahrenheit(), calendar::turn, and coords::coord_point< Point, Origin, Scale >::z().
get_water_temperature()
int weather_manager::get_water_temperature (const tripoint & location) const
Definition at line 1140 of file weather.cpp.
{
    return water_temperature;
}
References weather_manager::water_temperature.
get_weather()
weather_manager & get_weather ()
Definition at line 64 of file weather.cpp.
{
    return *g->weather_manager_ptr;
}
Referenced by Character::activate_bionic(), map::build_sunlight_cache(), map::build_transparency_cache(), Character::burn_fuel(), Character::calc_needs_rates(), Character::can_hear(), relic_funcs::check_recharge_reqs(), current_weather(), debug_menu::debug(), character_display::disp_info(), vehicle::do_environmental_effects(), draw_env_compact(), draw_loc_labels(), draw_speed_tab(), draw_time_classic(), draw_weather_classic(), vehicle::engine_cold_factor(), get_signal_for_hordes(), get_temp(), Character::hardcoded_effects(), defense_game::init(), tutorial_game::init(), firestarter_actor::light_mod(), weather_effect::lightning(), vehicle::part_vpower_w(), Character::passive_power_gen(), photo_def_for_camera_point(), item::process(), Character::process_bionic(), item::process_extinguish(), item::process_rot(), sounds::process_sound_markers(), sounds::process_sounds(), monster::process_turn(), Character::recalc_speed_bonus(), map::remove_rotten_items(), render_wind(), map::spread_gas(), Character::suffer_from_artifacts(), Character::suffer_in_sunlight(), sum_conditions(), vehicle::total_wind_epower_w(), Character::update_bodytemp(), iuse_transform::use(), warm_enough_to_plant(), weather_forecast(), and iuse::weather_tool().
get_wind_arrow()
std::string get_wind_arrow (int dirangle)
Definition at line 899 of file weather.cpp.
{
    std::string wind_arrow;
    if( dirangle < 0 || dirangle >= 360 ) {
        wind_arrow.clear();
    } else if( dirangle <= 23 || dirangle > 338 ) {
        wind_arrow = "\u21D3";
    } else if( dirangle <= 68 ) {
        wind_arrow = "\u21D9";
    } else if( dirangle <= 113 ) {
        wind_arrow = "\u21D0";
    } else if( dirangle <= 158 ) {
        wind_arrow = "\u21D6";
    } else if( dirangle <= 203 ) {
        wind_arrow = "\u21D1";
    } else if( dirangle <= 248 ) {
        wind_arrow = "\u21D7";
    } else if( dirangle <= 293 ) {
        wind_arrow = "\u21D2";
    } else {
        wind_arrow = "\u21D8";
    }
    return wind_arrow;
}
Referenced by debug_menu::debug(), draw_env_compact(), and render_wind().
get_wind_color()
nc_color get_wind_color (double windpower)
Definition at line 817 of file weather.cpp.
{
    nc_color windcolor;
    if( windpower < 1 ) {
        windcolor = c_dark_gray;
    } else if( windpower < 3 ) {
        windcolor = c_dark_gray;
    } else if( windpower < 7 ) {
        windcolor = c_light_gray;
    } else if( windpower < 12 ) {
        windcolor = c_light_gray;
    } else if( windpower < 18 ) {
        windcolor = c_blue;
    } else if( windpower < 24 ) {
        windcolor = c_blue;
    } else if( windpower < 31 ) {
        windcolor = c_light_blue;
    } else if( windpower < 38 ) {
        windcolor = c_light_blue;
    } else if( windpower < 46 ) {
        windcolor = c_cyan;
    } else if( windpower < 54 ) {
        windcolor = c_cyan;
    } else if( windpower < 63 ) {
        windcolor = c_light_cyan;
    } else if( windpower < 72 ) {
        windcolor = c_light_cyan;
    } else if( windpower > 72 ) {
        windcolor = c_white;
    }
    return windcolor;
}
References c_blue, c_cyan, c_dark_gray, c_light_blue, c_light_cyan, c_light_gray, and c_white.
Referenced by draw_env_compact(), and render_wind().
get_wind_desc()
std::string get_wind_desc (double windpower)
Definition at line 971 of file weather.cpp.
{
    std::string winddesc;
    if( windpower < 1 ) {
        winddesc = _( "Calm" );
    } else if( windpower <= 3 ) {
        winddesc = _( "Light Air" );
    } else if( windpower <= 7 ) {
        winddesc = _( "Light Breeze" );
    } else if( windpower <= 12 ) {
        winddesc = _( "Gentle Breeze" );
    } else if( windpower <= 18 ) {
        winddesc = _( "Moderate Breeze" );
    } else if( windpower <= 24 ) {
        winddesc = _( "Fresh Breeze" );
    } else if( windpower <= 31 ) {
        winddesc = _( "Strong Breeze" );
    } else if( windpower <= 38 ) {
        winddesc = _( "Moderate Gale" );
    } else if( windpower <= 46 ) {
        winddesc = _( "Gale" );
    } else if( windpower <= 54 ) {
        winddesc = _( "Strong Gale" );
    } else if( windpower <= 63 ) {
        winddesc = _( "Whole Gale" );
    } else if( windpower <= 72 ) {
        winddesc = _( "Violent Storm" );
    } else if( windpower > 72 ) {
        // Anything above Whole Gale is very unlikely to happen and has no additional effects.
        winddesc = _( "Hurricane" );
    }
    return winddesc;
}
References _.
Referenced by draw_env_compact(), weather_generator::get_weather(), and render_wind().
glare()
void glare (const weather_type_id & w)
Glare.
Causes glare effect to player's eyes if they are not wearing applicable eye protection.
Parameters
intensity Level of sun brighthess
Definition at line 75 of file weather.cpp.
{
    //General prepequisites for glare
    if( !is_player_outside() || !g->is_in_sunlight( g->u.pos() ) || g->u.in_sleep_state() ||
        g->u.worn_with_flag( flag_SUN_GLASSES ) ||
        g->u.has_bionic( bio_sunglasses ) ||
        g->u.is_blind() ) {
        return;
    }
    time_duration dur = 0_turns;
    const efftype_id *effect = nullptr;
    season_type season = season_of_year( calendar::turn );
    if( season == WINTER ) {
        //Winter snow glare: for both clear & sunny weather
        effect = &effect_snow_glare;
        dur = g->u.has_effect( *effect ) ? 1_turns : 2_turns;
    } else if( w->sun_intensity == sun_intensity_type::high ) {
        //Sun glare: only for bright sunny weather
        effect = &effect_glare;
        dur = g->u.has_effect( *effect ) ? 1_turns : 2_turns;
    }
    //apply final glare effect
    if( dur > 0_turns && effect != nullptr ) {
        //enhance/reduce by some traits
        if( g->u.has_trait( trait_CEPH_VISION ) ) {
            dur = dur * 2;
        }
        g->u.add_env_effect( *effect, bp_eyes, 2, dur );
    }
}
References bio_sunglasses, bp_eyes, effect_glare, effect_snow_glare, flag_SUN_GLASSES(), g, high, is_player_outside(), season, season_of_year(), weather_type::sun_intensity, trait_CEPH_VISION, calendar::turn, and WINTER.
Referenced by handle_weather_effects().
handle_weather_effects()
void handle_weather_effects (const weather_type_id & w)
Definition at line 522 of file weather.cpp.
{
    if( w->rains && w->precip != precip_class::none ) {
        fill_water_collectors( precip_mm_per_hour( w->precip ),
                               w->acidic );
        int wetness = 0;
        time_duration decay_time = 60_turns;
        if( w->precip == precip_class::very_light ) {
            wetness = 5;
            decay_time = 5_turns;
        } else if( w->precip == precip_class::light ) {
            wetness = 30;
            decay_time = 15_turns;
        } else if( w->precip == precip_class::heavy ) {
            decay_time = 45_turns;
            wetness = 60;
        }
        g->m.decay_fields_and_scent( decay_time );
        weather_effect::wet_player( wetness );
    }
    glare( w );
    for( const auto &effect : w->effects ) {
        effect.first( effect.second );
    }
}
References weather_type::acidic, weather_type::effects, fill_water_collectors(), g, glare(), heavy, light, none, weather_type::precip, precip_mm_per_hour(), weather_type::rains, very_light, and weather_effect::wet_player().
Referenced by game::do_turn().
incident_sunlight()
int incident_sunlight (const weather_type_id & wtype, const time_point & t)
Amount of sunlight incident at the ground, taking weather and time of day into account.
Definition at line 107 of file weather.cpp.
{
    return std::max<float>( 0.0f, sunlight( t, false ) + wtype->light_modifier );
}
References weather_type::light_modifier, and sunlight().
Referenced by Character::burn_fuel(), proc_weather_sum(), and vehicle::total_solar_epower_w().
is_player_outside()
static bool is_player_outside () static
Definition at line 69 of file weather.cpp.
{
    return get_map().is_outside( point( get_player_character().posx(),
                                        get_player_character().posy() ) ) && g->get_levz() >= 0;
}
References g, get_map(), get_player_character(), and map::is_outside().
Referenced by weather_effect::acid(), glare(), weather_effect::light_acid(), and weather_effect::wet_player().
is_wind_blocker()
bool is_wind_blocker (const tripoint & location)
Definition at line 965 of file weather.cpp.
{
    return g->m.has_flag( "BLOCK_WIND", location );
}
References g.
Referenced by get_local_windpower().
light_acid()
void weather_effect::light_acid (int intensity)
Acid drizzle.
Causes minor pain only.
Definition at line 461 of file weather.cpp.
{
    if( calendar::once_every( time_duration::from_seconds( intensity ) ) && is_player_outside() ) {
        if( g->u.weapon.has_flag( "RAIN_PROTECT" ) && !one_in( 3 ) ) {
            add_msg( _( "Your %s protects you from the acidic drizzle." ), g->u.weapon.tname() );
        } else {
            if( g->u.worn_with_flag( "RAINPROOF" ) && !one_in( 4 ) ) {
                add_msg( _( "Your clothing protects you from the acidic drizzle." ) );
            } else {
                bool has_helmet = false;
                if( g->u.is_wearing_power_armor( &has_helmet ) && ( has_helmet || !one_in( 4 ) ) ) {
                    add_msg( _( "Your power armor protects you from the acidic drizzle." ) );
                } else {
                    add_msg( m_warning, _( "The acid rain stings, but is mostly harmless for now" ) );
                    if( one_in( 10 ) && ( g->u.get_pain() < 10 ) ) {
                        g->u.mod_pain( 1 );
                    }
                }
            }
        }
    }
}
References _, add_msg(), time_duration::from_seconds(), g, is_player_outside(), m_warning, calendar::once_every(), and one_in().
Referenced by weather_type::load().
lightning()
void weather_effect::lightning (int intensity)
Lightning.
Chance of lightning illumination for the current turn when aboveground. Thunder.
This used to manifest actual lightning on the map, causing fires and such, but since such effects only manifest properly near the player due to the "reality bubble", this was causing undesired metagame tactics such as players leaving their shelter for a more "expendable" area during lightning storms.
Definition at line 445 of file weather.cpp.
{
    if( one_in( intensity ) ) {
        if( g->get_levz() >= 0 ) {
            add_msg( _( "A flash of lightning illuminates your surroundings!" ) );
            sfx::play_variant_sound( "environment", "thunder_near", 100, random_direction() );
            get_weather().lightning_active = true;
        }
    } else {
        get_weather().lightning_active = false;
    }
}
References _, add_msg(), g, get_weather(), weather_manager::lightning_active, one_in(), sfx::play_variant_sound(), and random_direction().
Referenced by weather_type::load().
local_windchill_hightemp()
static double local_windchill_hightemp (double temperature_f, double humidity, double wind_mph) static
Model 2, warm wind chill
Definition at line 775 of file weather.cpp.
{
    /// Model 2, warm wind chill
    // Source : http://en.wikipedia.org/wiki/Wind_chill#Australian_Apparent_Temperature
    // Convert to meters per second.
    double wind_meters_per_sec = wind_mph * 0.44704;
    double temperature_c = units::fahrenheit_to_celsius( temperature_f );
    // Cap the vapor pressure term to 50C of extra heat, as this term
    // otherwise grows logistically to an asymptotic value of about 2e7
    // for large values of temperature. This is presumably due to the
    // model being designed for reasonable ambient temperature values,
    // rather than extremely high ones.
    double windchill_c = 0.33 * std::min<float>( 150.00, humidity / 100.00 * 6.105 *
                         std::exp( 17.27 * temperature_c / ( 237.70 + temperature_c ) ) )
                         - 0.70 * wind_meters_per_sec
                         - 4.00;
    // Convert to Fahrenheit, but omit the '+ 32' because we are only dealing with a piece of the felt air temperature equation.
    return windchill_c * 9 / 5;
}
References units::fahrenheit_to_celsius().
Referenced by get_local_windchill().
local_windchill_lowtemp()
static double local_windchill_lowtemp (double temperature_f, double , double wind_mph) static
Model 1, cold wind chill (only valid for temps below 50F) Is also used as a standard in North America.
Definition at line 758 of file weather.cpp.
{
    /// Model 1, cold wind chill (only valid for temps below 50F)
    /// Is also used as a standard in North America.
    // This model fails when wind is less than 3 mph
    double wind_mph_lowcapped = std::max( 3.0, wind_mph );
    // Temperature is removed at the end, because get_local_windchill is meant to calculate the difference.
    // Source : http://en.wikipedia.org/wiki/Wind_chill#North_American_and_United_Kingdom_wind_chill_index
    return 35.74
           + 0.6215 * temperature_f
           - 35.75 * std::pow( wind_mph_lowcapped, 0.16 )
           + 0.4275 * temperature_f * std::pow( wind_mph_lowcapped, 0.16 )
           - temperature_f;
}
Referenced by get_local_windchill().
precip_mm_per_hour()
double precip_mm_per_hour (precip_class const p)
Definition at line 511 of file weather.cpp.
{
    return
        p == precip_class::very_light ? 0.5 :
        p == precip_class::light ? 1.5 :
        p == precip_class::heavy ? 3   :
        0;
}
References heavy, light, and very_light.
Referenced by handle_weather_effects().
print_humidity()
std::string print_humidity (double humidity, int decimals)
Print relative humidity (no conversions.)
Definition at line 743 of file weather.cpp.
{
    const std::string ret = string_format( "%.*f", decimals, humidity );
    return string_format( pgettext( "humidity in percent", "%s%%" ), ret );
}
References pgettext(), cata::hash64_detail::ret, and string_format().
Referenced by Character::activate_bionic(), and iuse::weather_tool().
print_pressure()
std::string print_pressure (double pressure, int decimals)
Print pressure (no conversions.)
Definition at line 752 of file weather.cpp.
{
    const std::string ret = string_format( "%.*f", decimals, pressure / 10 );
    return string_format( pgettext( "air pressure in kPa", "%s kPa" ), ret );
}
References pgettext(), cata::hash64_detail::ret, and string_format().
Referenced by Character::activate_bionic(), and iuse::weather_tool().
print_temperature() [1/2]
std::string print_temperature (double fahrenheit, int decimals)
Print temperature (and convert to Celsius if Celsius display is enabled.)
Definition at line 717 of file weather.cpp.
{
    return print_temperature( units::from_fahrenheit( fahrenheit ), decimals );
}
References units::from_fahrenheit(), and print_temperature().
Referenced by Character::activate_bionic(), draw_env_compact(), draw_time_classic(), get_temp(), print_temperature(), weather_forecast(), and iuse::weather_tool().
print_temperature() [2/2]
std::string print_temperature (units::temperature temperature, int decimals)
Definition at line 722 of file weather.cpp.
{
    const auto text = [&]( const double value ) {
        return string_format( "%.*f", decimals, value );
    };
    if( get_option<std::string>( "USE_CELSIUS" ) == "celsius" ) {
        return string_format( pgettext( "temperature in Celsius", "%sC" ),
                              text( units::to_celsius<double>( temperature ) ) );
    } else if( get_option<std::string>( "USE_CELSIUS" ) == "kelvin" ) {
        return string_format( pgettext( "temperature in Kelvin", "%sK" ),
                              text( units::to_kelvins<double>( temperature ) ) );
    } else {
        return string_format( pgettext( "temperature in Fahrenheit", "%sF" ),
                              text( units::to_fahrenheit<double>( temperature ) ) );
    }
}
References pgettext(), and string_format().
print_time_just_hour()
static std::string print_time_just_hour (const time_point & p) static
Definition at line 563 of file weather.cpp.
{
    const int hour = to_hours<int>( time_past_midnight( p ) );
    int hour_param = hour % 12;
    if( hour_param == 0 ) {
        hour_param = 12;
    }
    return string_format( hour < 12 ? _( "%d AM" ) : _( "%d PM" ), hour_param );
}
References _, hour, string_format(), and time_past_midnight().
Referenced by weather_forecast().
proc_weather_sum()
void proc_weather_sum (const weather_type_id wtype, weather_sum & data, const time_point & t, const time_duration & tick_size) inline
Definition at line 112 of file weather.cpp.
{
    int amount = 0;
    if( wtype->rains ) {
        switch( wtype->precip ) {
            case precip_class::very_light:
                amount = 1 * to_turns<int>( tick_size );
                break;
            case precip_class::light:
                amount = 4 * to_turns<int>( tick_size );
                break;
            case precip_class::heavy:
                amount = 8 * to_turns<int>( tick_size );
                break;
            default:
                break;
        }
    }
    if( wtype->acidic ) {
        data.acid_amount += amount;
    } else {
        data.rain_amount += amount;
    }
    // TODO: Change this sunlight "sampling" here into a proper interpolation
    const float tick_sunlight = incident_sunlight( wtype, t );
    data.sunlight += tick_sunlight * to_turns<int>( tick_size );
}
References weather_sum::acid_amount, weather_type::acidic, heavy, incident_sunlight(), light, weather_type::precip, weather_sum::rain_amount, weather_type::rains, weather_sum::sunlight, and very_light.
Referenced by sum_conditions().
retroactively_fill_from_funnel()
void retroactively_fill_from_funnel (item & it, const trap & tr, const time_point & start, const time_point & end, const tripoint & pos)
Determine what a funnel has filled out of game, using funnelcontainer.bday as a starting point.
Parameters
it The container item which is to be filled.
pos The absolute position of the funnel (in the map square system, the one used by the map, but absolute).
tr The funnel (trap which acts as a funnel).
Definition at line 184 of file weather.cpp.
{
    if( start > end || !tr.is_funnel() ) {
        return;
    }
    // bday == last fill check
    it.set_birthday( end );
    weather_sum data = sum_conditions( start, end, pos );
    // Technically 0.0 division is OK, but it will be cleaner without it
    if( data.rain_amount > 0 ) {
        const int rain = roll_remainder( 1.0 / tr.funnel_turns_per_charge( data.rain_amount ) );
        it.add_rain_to_container( false, rain );
        // add_msg(m_debug, "Retroactively adding %d water from turn %d to %d", rain, startturn, endturn);
    }
    if( data.acid_amount > 0 ) {
        const int acid = roll_remainder( 1.0 / tr.funnel_turns_per_charge( data.acid_amount ) );
        it.add_rain_to_container( true, acid );
    }
}
References mattack::acid(), weather_sum::acid_amount, item::add_rain_to_container(), trap::funnel_turns_per_charge(), trap::is_funnel(), weather_sum::rain_amount, roll_remainder(), item::set_birthday(), and sum_conditions().
Referenced by map::fill_funnels().
set_nextweather()
void weather_manager::set_nextweather (time_point t)
Definition at line 1101 of file weather.cpp.
{
    nextweather = t;
    update_weather();
}
References weather_manager::nextweather, and weather_manager::update_weather().
Referenced by Character::suffer_from_artifacts().
sum_conditions()
weather_sum sum_conditions (const time_point & start, const time_point & end, const tripoint & location)
Definition at line 153 of file weather.cpp.
{
    time_duration tick_size = 0_turns;
    weather_sum data;
    for( time_point t = start; t < end; t += tick_size ) {
        const time_duration diff = end - t;
        if( diff < 10_turns ) {
            tick_size = 1_turns;
        } else if( diff > 7_days ) {
            tick_size = 1_hours;
        } else {
            tick_size = 1_minutes;
        }
        weather_type_id wtype = current_weather( location, t );
        proc_weather_sum( wtype, data, t, tick_size );
        const weather_manager &weather = get_weather();
        data.wind_amount += get_local_windpower( weather.windspeed,
                            // TODO: fix point types
                            overmap_buffer.ter( tripoint_abs_omt( ms_to_omt_copy( location ) ) ),
                            location,
                            weather.winddirection, false ) * to_turns<int>( tick_size );
    }
    return data;
}
References current_weather(), get_local_windpower(), get_weather(), ms_to_omt_copy(), overmap_buffer, proc_weather_sum(), overmapbuffer::ter(), and weather_sum::wind_amount.
Referenced by check_art_charge_req(), iexamine::flower_poppy(), retroactively_fill_from_funnel(), solar_tile::update_internal(), and vehicle::update_time().
thunder()
void weather_effect::thunder (int intensity)
Thunder.
Flavor messages. Very wet.
Definition at line 422 of file weather.cpp.
{
    if( !g->u.has_effect( effect_sleep ) && !g->u.is_deaf() && one_in( intensity ) ) {
        if( g->get_levz() >= 0 ) {
            add_msg( _( "You hear a distant rumble of thunder." ) );
            sfx::play_variant_sound( "environment", "thunder_far", 80, random_direction() );
        } else if( one_in( std::max( roll_remainder( 2.0f * g->get_levz() /
                                     g->u.mutation_value( "hearing_modifier" ) ), 1 ) ) ) {
            add_msg( _( "You hear a rumble of thunder from above." ) );
            sfx::play_variant_sound( "environment", "thunder_far",
                                     ( 80 * g->u.mutation_value( "hearing_modifier" ) ), random_direction() );
        }
    }
}
References _, add_msg(), effect_sleep, g, one_in(), sfx::play_variant_sound(), random_direction(), and roll_remainder().
Referenced by weather_type::load().
to_string()
static std::string to_string (const weekdays & d) static
Definition at line 549 of file weather.cpp.
{
    static const std::array<std::string, 7> weekday_names = {{
            translate_marker( "Sunday" ), translate_marker( "Monday" ),
            translate_marker( "Tuesday" ), translate_marker( "Wednesday" ),
            translate_marker( "Thursday" ), translate_marker( "Friday" ),
            translate_marker( "Saturday" )
        }
    };
    static_assert( static_cast<int>( weekdays::SUNDAY ) == 0,
                   "weekday_names array is out of sync with weekdays enumeration values" );
    return _( weekday_names[ static_cast<int>( d ) ] );
}
References _, SUNDAY, and translate_marker.
Referenced by weather_forecast().
update_weather()
void weather_manager::update_weather ()
Definition at line 1056 of file weather.cpp.
{
    w_point &w = weather_precise;
    winddirection = wind_direction_override ? *wind_direction_override : w.winddirection;
    windspeed = windspeed_override ? *windspeed_override : w.windpower;
    if( !weather_id || calendar::turn >= nextweather ) {
        const weather_generator &weather_gen = get_cur_weather_gen();
        w = weather_gen.get_weather( g->u.global_square_location(), calendar::turn, g->get_seed() );
        weather_type_id old_weather = weather_id;
        weather_id = weather_override ? weather_override : weather_gen.get_weather_conditions( w );
        if( !g->u.has_artifact_with( AEP_BAD_WEATHER ) ) {
            weather_override = weather_type_id::NULL_ID();
        }
        sfx::do_ambient();
        temperature = units::to_fahrenheit( w.temperature );
        lightning_active = false;
        // Check weather every few turns, instead of every turn.
        // TODO: predict when the weather changes and use that time.
        nextweather = calendar::turn + 5_minutes;
        if( weather_id != old_weather && weather_id->dangerous &&
            g->get_levz() >= 0 && get_map().is_outside( g->u.pos() )
            && !g->u.has_activity( ACT_WAIT_WEATHER ) ) {
            g->cancel_activity_or_ignore_query( distraction_type::weather_change,
                                                string_format( _( "The weather changed to %s!" ), weather_id->name ) );
        }
        if( weather_id != old_weather && g->u.has_activity( ACT_WAIT_WEATHER ) ) {
            g->u.assign_activity( ACT_WAIT_WEATHER, 0, 0 );
        }
        if( weather_id->sight_penalty !=
            old_weather->sight_penalty ) {
            for( int i = -OVERMAP_DEPTH; i <= OVERMAP_HEIGHT; i++ ) {
                get_map().set_transparency_cache_dirty( i );
            }
            get_map().set_seen_cache_dirty( tripoint_zero );
        }
        water_temperature = units::to_fahrenheit(
                                weather_gen.get_water_temperature(
                                    tripoint_abs_ms( g->u.global_square_location() ),
                                    calendar::turn, calendar::config, g->get_seed() ) );
    }
}
References _, ACT_WAIT_WEATHER, AEP_BAD_WEATHER, calendar::config, weather_type::dangerous, sfx::do_ambient(), g, weather_manager::get_cur_weather_gen(), get_map(), weather_generator::get_water_temperature(), weather_generator::get_weather(), weather_generator::get_weather_conditions(), weather_manager::lightning_active, weather_type::name, weather_manager::nextweather, string_id< weather_type >::NULL_ID(), OVERMAP_DEPTH, OVERMAP_HEIGHT, map::set_seen_cache_dirty(), map::set_transparency_cache_dirty(), weather_type::sight_penalty, string_format(), weather_manager::temperature, w_point::temperature, units::to_fahrenheit(), tripoint_zero, calendar::turn, weather_manager::water_temperature, weather_change, weather_manager::weather_id, weather_manager::weather_override, weather_manager::weather_precise, weather_manager::wind_direction_override, weather_manager::winddirection, w_point::winddirection, w_point::windpower, weather_manager::windspeed, and weather_manager::windspeed_override.
Referenced by weather_manager::set_nextweather(), and game::start_game().
warm_enough_to_plant() [1/2]
bool warm_enough_to_plant (const tripoint & pos)
Is it warm enough to plant seeds?
The first overload is in map-square coords, the second for larger scale queries.
Definition at line 1027 of file weather.cpp.
{
    // semi-appropriate temperature for most plants
    return get_weather().get_temperature( pos ) >= 50;
}
References weather_manager::get_temperature(), and get_weather().
Referenced by can_do_activity_there(), vehicle::can_enable(), iexamine::dirtmound(), talk_function::field_plant(), basecamp::get_available_missions_by_dir(), and vehicle::idle().
warm_enough_to_plant() [2/2]
bool warm_enough_to_plant (const tripoint_abs_omt & pos)
Definition at line 1033 of file weather.cpp.
{
    return get_weather().get_temperature( pos ) >= 50;
}
References weather_manager::get_temperature(), and get_weather().
weather_forecast()
std::string weather_forecast (const point_abs_sm & abs_sm_pos)
Generate textual weather forecast for the specified radio tower.
Definition at line 611 of file weather.cpp.
{
    std::string weather_report;
    // Local conditions
    const auto cref = overmap_buffer.closest_city( tripoint_abs_sm( abs_sm_pos, 0 ) );
    const std::string city_name = cref ? cref.city->name : std::string( _( "middle of nowhere" ) );
    // Current time
    const weather_manager &weather = get_weather();
    weather_report += string_format(
                          //~ %1$s: time of day, %2$s: hour of day, %3$s: city name, %4$s: weather name, %5$s: temperature value
                          _( "The current time is %1$s Eastern Standard Time.  At %2$s in %3$s, it was %4$s.  The temperature was %5$s. " ),
                          to_string_time_of_day( calendar::turn ), print_time_just_hour( calendar::turn ),
                          city_name,
                          get_weather().weather_id->name, print_temperature( get_weather().temperature )
                      );
    //weather_report += ", the dewpoint ???, and the relative humidity ???.  ";
    //weather_report += "The wind was <direction> at ? mi/km an hour.  ";
    //weather_report += "The pressure was ??? in/mm and steady/rising/falling.";
    // TODO: wind direction and speed
    // Regional conditions (simulated by choosing a random range containing the current conditions).
    // Adjusted for weather volatility based on how many weather changes are coming up.
    //weather_report += "Across <region>, skies ranged from <cloudiest> to <clearest>.  ";
    // TODO: Add fake reports for nearby cities
    // TODO: fix point types
    const tripoint abs_ms_pos = tripoint( project_to<coords::ms>( abs_sm_pos ).raw(), 0 );
    const time_point now_hour = calendar::turn - time_duration::from_minutes( minute_of_hour<int>
                                ( calendar::turn ) );
    bool now_is_day = is_day( now_hour );
    int last_idx = -1;
    bool last_is_day = now_is_day;
    time_point last_hour = now_hour;
    std::array<forecast_period, NUM_FORECAST_PERIODS> periods = { {} };
    const auto &wgen = weather.get_cur_weather_gen();
    while( true ) {
        last_hour += 1_hours;
        // Some types of weather may happen only during the night or during the day,
        // so skip dusk and dawn just to be safe.
        if( is_dusk( last_hour ) || is_dawn( last_hour ) ) {
            continue;
        }
        bool new_is_day = is_day( last_hour );
        if( new_is_day != last_is_day ) {
            last_is_day = new_is_day;
            last_idx += 1;
            if( last_idx >= NUM_FORECAST_PERIODS ) {
                break;
            }
            periods[last_idx].is_day = last_is_day;
            periods[last_idx].week_day = day_of_week( last_hour );
        }
        if( last_idx < 0 ) {
            continue;
        }
        forecast_period &period = periods[last_idx];
        w_point w = wgen.get_weather( abs_ms_pos, last_hour, g->get_seed() );
        const weather_type_id &new_type = wgen.get_weather_conditions( w );
        int new_priority = wgen.forecast_priority( new_type );
        if( !period.type || new_priority > period.type_priority ) {
            period.type_priority = new_priority;
            period.type = &new_type.obj();
        }
        period.temp_high = std::max( period.temp_high, w.temperature );
        period.temp_low = std::min( period.temp_low, w.temperature );
    }
    for( int i = 0; i < NUM_FORECAST_PERIODS; i++ ) {
        const forecast_period &period = periods[i];
        std::string day;
        if( i == 0 ) {
            if( period.is_day ) {
                day = _( "Today" );
            } else {
                day = _( "Tonight" );
            }
        } else {
            if( period.is_day ) {
                day = to_string( period.week_day );
            } else {
                //~ %s is day of week (e.g. Friday Night)
                day = string_format( pgettext( "Forecast", "%s Night" ), to_string( period.week_day ) );
            }
        }
        weather_report += string_format(
                              //~ %1 is day or night of week (e.g. "Monday", or "Friday Night"),
                              //~ %2 is weather type, %3 and %4 are temperatures.
                              _( "%1$s %2$s. Highs of %3$s. Lows of %4$s. " ),
                              day, period.type->name,
                              print_temperature( period.temp_high ),
                              print_temperature( period.temp_low )
                          );
    }
    return weather_report;
}
References _, city_reference::city, overmapbuffer::closest_city(), day, day_of_week(), time_duration::from_minutes(), g, get_weather(), is_dawn(), is_day(), forecast_period::is_day, is_dusk(), city::name, weather_type::name, NUM_FORECAST_PERIODS, string_id< T >::obj(), overmap_buffer, pgettext(), print_temperature(), print_time_just_hour(), string_format(), forecast_period::temp_high, forecast_period::temp_low, w_point::temperature, to_string(), to_string_time_of_day(), calendar::turn, forecast_period::type, forecast_period::type_priority, and forecast_period::week_day.
Referenced by iuse::radio_on().
weather_manager()
weather_manager::weather_manager ()
Definition at line 1038 of file weather.cpp.
{
    lightning_active = false;
    weather_override = weather_type_id::NULL_ID();
    nextweather = calendar::before_time_starts;
    temperature = 0;
    weather_id = weather_type_id::NULL_ID();
}
References calendar::before_time_starts, weather_manager::lightning_active, weather_manager::nextweather, string_id< weather_type >::NULL_ID(), weather_manager::temperature, weather_manager::weather_id, and weather_manager::weather_override.
wet_player()
void weather_effect::wet_player (int amount)
Main routine for wet effects caused by weather.
Drenching the player is applied after checks against worn and held items.
The warmth of armor is considered when determining how much drench happens per tick.
Note that this is not the only place where drenching can happen. For example, moving or swimming into water tiles will also cause drenching.
See also
fill_water_collectors
map::decay_fields_and_scent
player::drench
Definition at line 372 of file weather.cpp.
{
    Character &target = get_avatar();
    if( !is_player_outside() ||
        target.has_trait( trait_FEATHERS ) ||
        target.weapon.has_flag( "RAIN_PROTECT" ) ||
        ( !one_in( 50 ) && target.worn_with_flag( "RAINPROOF" ) ) ) {
        return;
    }
    // Coarse correction to get us back to previously intended soaking rate.
    if( !calendar::once_every( 6_seconds ) ) {
        return;
    }
    std::map<bodypart_id, std::vector<const item *>> clothing_map;
    for( const bodypart_id &bp : target.get_all_body_parts() ) {
        clothing_map.emplace( bp, std::vector<const item *>() );
    }
    for( const item &it : target.worn ) {
        // TODO: Port body part set id changes
        const body_part_set &covered = it.get_covered_body_parts();
        for( size_t i = 0; i < num_bp; i++ ) {
            body_part token = static_cast<body_part>( i );
            if( covered.test( token ) ) {
                clothing_map[convert_bp( token )].emplace_back( &it );
            }
        }
    }
    std::map<bodypart_id, int> warmth_bp = target.warmth( clothing_map );
    const int warmth_delay = warmth_bp[body_part_torso] * 0.8 +
                             warmth_bp[body_part_head] * 0.2;
    if( rng( 0, 100 - amount + warmth_delay ) > 10 ) {
        // Thick clothing slows down (but doesn't cap) soaking
        return;
    }
    const auto &wet = g->u.body_wetness;
    const auto &capacity = g->u.drench_capacity;
    body_part_set drenched_parts{ { bp_torso, bp_arm_l, bp_arm_r, bp_head } };
    if( wet[bp_torso] * 100 >= capacity[bp_torso] * 50 ) {
        // Once upper body is 50%+ drenched, start soaking the legs too
        drenched_parts |= { { bp_leg_l, bp_leg_r } };
    }
    g->u.drench( amount, drenched_parts, false );
}
References body_part_head, body_part_torso, bp_arm_l, bp_arm_r, bp_head, bp_leg_l, bp_leg_r, bp_torso, convert_bp(), g, Creature::get_all_body_parts(), get_avatar(), item::get_covered_body_parts(), item::has_flag(), Character::has_trait(), is_player_outside(), num_bp, calendar::once_every(), one_in(), rng(), body_part_set::test(), trait_FEATHERS, Character::warmth(), Character::weapon, wet, Character::worn, and Character::worn_with_flag().
Referenced by handle_weather_effects(), and weather_type::load().
~weather_manager()
weather_manager::~weather_manager () default
Variable Documentation
NUM_FORECAST_PERIODS
constexpr int NUM_FORECAST_PERIODS = 6 constexpr
Definition at line 573 of file weather.cpp.
Referenced by weather_forecast().