Cataclysm BN: Convert functions for @ref string_formatter
Convert functions for @ref string_formatter
The convert functions here are used to convert the input value of string_formatter::parse into the requested type, as defined by the format specifiers.
Classes
struct cata::is_instance_of< typename, class >
struct cata::is_instance_of< TMPL< T >, TMPL >
Typedefs
template<typename T >
using cata::is_numeric = typename std::conditional< std::is_arithmetic< typename std::decay< T >::type >::value &&!std::is_same< typename std::decay< T >::type, bool >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_integer = typename std::conditional< is_numeric< T >::value &&!std::is_floating_point< typename std::decay< T >::type >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_char = typename std::conditional< std::is_same< typename std::decay< T >::type, char >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_string = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_string_view = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string_view >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_cstring = typename std::conditional< std::is_same< typename std::decay< T >::type, const char * >::value||std::is_same< typename std::decay< T >::type, char * >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_translation = typename std::conditional< std::is_same< typename std::decay< T >::type, translation >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_string_id = typename std::conditional< is_instance_of< typename std::decay< T >::type, string_id >::value, std::true_type, std::false_type >::type
Functions
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&is_integer< T >::value, RT >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
RT cata::convert (RT *, const string_formatter &sf, T &&,...)
Detailed Description
The convert functions here are used to convert the input value of string_formatter::parse into the requested type, as defined by the format specifiers.
Template Parameters
T the input type, as given by the call to string_format.
RT the requested type. The convert functions return such a value or they throw an exception via throw_error.
Each function has the same parameters: First parameter defined the requested type. The value of the pointer is ignored, callers should use a (properly casted) nullptr. It is required to "simulate" overloading the return value. E.g. long convert(long*, int) and short convert(short*, int) both convert a input value of type int, but the first converts to long and the second converts to short. Without the first parameters their signature would be identical. The second parameter is used to call throw_error / string_formatter_set_temp_buffer. The third parameter is the input value that is to be converted. The fourth parameter is a dummy value, it is always ignored, callers should use 0 here. It is used so the fallback with the variadic arguments is only chosen when no other overload matches.
Typedef Documentation
is_char
template<typename T > using cata::is_char = typedef typename std::conditional<std::is_same<typename std::decay<T>::type, char>::value, std::true_type, std::false_type>::type
Definition at line 66 of file string_formatter.h.
is_cstring
template<typename T > using cata::is_cstring = typedef typename std::conditional < std::is_same<typename std::decay<T>::type, const char *>::value || std::is_same<typename std::decay<T>::type, char *>::value, std::true_type, std::false_type >::type
Definition at line 78 of file string_formatter.h.
is_integer
template<typename T > using cata::is_integer = typedef typename std::conditional < is_numeric<T>::value && !std::is_floating_point<typename std::decay<T>::type>::value, std::true_type, std::false_type >::type
Definition at line 62 of file string_formatter.h.
is_numeric
template<typename T > using cata::is_numeric = typedef typename std::conditional < std::is_arithmetic<typename std::decay<T>::type>::value && !std::is_same<typename std::decay<T>::type, bool>::value, std::true_type, std::false_type >::type
Definition at line 57 of file string_formatter.h.
is_string
template<typename T > using cata::is_string = typedef typename std::conditional<std::is_same<typename std::decay<T>::type, std::string>::value, std::true_type, std::false_type>::type
Definition at line 70 of file string_formatter.h.
is_string_id
template<typename T > using cata::is_string_id = typedef typename std::conditional < is_instance_of<typename std::decay<T>::type, string_id>::value, std::true_type, std::false_type >::type
Definition at line 92 of file string_formatter.h.
is_string_view
template<typename T > using cata::is_string_view = typedef typename std::conditional<std::is_same<typename std::decay<T>::type, std::string_view>::value, std::true_type, std::false_type>::type
Definition at line 74 of file string_formatter.h.
is_translation
template<typename T > using cata::is_translation = typedef typename std::conditional < std::is_same<typename std::decay<T>::type, translation>::value, std::true_type, std::false_type >::type
Definition at line 83 of file string_formatter.h.
Function Documentation
convert() [1/2]
template<typename RT , typename T > std::enable_if< is_integer< RT >::value &&is_integer< T >::value, RT >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 98 of file string_formatter.h.
{
    return value;
}
Referenced by overmap::convert_terrain(), and cata::string_formatter::get_nth_arg_as().
convert() [2/2]
template<typename RT , typename T > RT cata::convert (RT * , const string_formatter & sf, T && , ...) inline
Definition at line 175 of file string_formatter.h.
{
    static_assert( std::is_pointer<typename std::decay<T>::type>::value ||
                   is_numeric<T>::value ||
                   is_string<T>::value ||
                   is_string_view<T>::value ||
                   is_char<T>::value ||
                   std::is_enum<typename std::decay<T>::type>::value ||
                   is_cstring<T>::value ||
                   is_translation<T>::value ||
                   is_string_id<T>::value,
                   "Unsupported argument type" );
    throw_error( sf, "Tried to convert argument of type " +
                 std::string( typeid( T ).name() ) + " to " +
                 std::string( typeid( RT ).name() ) + ", which is not possible" );
}
References cata::throw_error(), and type.