Cataclysm BN: src/help.h File Reference
help.h File Reference
#include <map>
#include <string>
#include <vector>
#include <utility>
#include "cursesdef.h"
#include "input.h"
Classes
class help
Macros
#define CATA_SRC_HELP_H
Functions
help & get_help ()
std::string get_hint ()
Macro Definition Documentation
CATA_SRC_HELP_H
#define CATA_SRC_HELP_H
Definition at line 3 of file help.h.
Function Documentation
get_help()
help & get_help ()
Definition at line 30 of file help.cpp.
{
    static help single_instance;
    return single_instance;
}
Referenced by input_context::display_menu(), game::handle_action(), game::handle_key_blocking_activity(), and main_menu::opening_screen().
get_hint()
std::string get_hint ()
Definition at line 228 of file help.cpp.
{
    return SNIPPET.random_from_category( "hint" ).value_or( translation() ).translated();
}
References snippet_library::random_from_category(), and SNIPPET.
Referenced by dynamic_line_t::dynamic_line_t(), and avatar::read().