Cataclysm BN: src/iexamine.h File Reference
iexamine.h File Reference
#include <list>
#include <string>
#include <tuple>
#include <vector>
#include "calendar.h"
#include "itype.h"
#include "optional.h"
#include "ret_val.h"
#include "type_id.h"
Namespaces
namespace iexamine
Macros
#define CATA_SRC_IEXAMINE_H
Typedefs
using seed_tuple = std::tuple< itype_id, std::string, int >
using iexamine_function = void(*)(player &, const tripoint &)
Functions
void iexamine::egg_sack_generic (player &p, const tripoint &examp, const mtype_id &montype)
Spawn spiders from a spider egg sack in radius 1 around the egg sack.
void iexamine::none (player &p, const tripoint &examp)
Nothing player can interact with here.
void iexamine::gaspump (player &p, const tripoint &examp)
Use "gas pump." Will pump any liquids on tile.
void iexamine::atm (player &p, const tripoint &examp)
launches the atm menu class which then handles all the atm interactions.
void iexamine::vending (player &p, const tripoint &examp)
Generates vending machine UI and allows players to purchase contained items with a cash card.
void iexamine::toilet (player &p, const tripoint &examp)
If there's water, allow its usage but add chance of poison.
void iexamine::elevator (player &p, const tripoint &examp)
If underground, move 2 levels up else move 2 levels down.
void iexamine::nanofab (player &p, const tripoint &examp)
UI FOR LAB_FINALE NANO FABRICATOR.
void iexamine::controls_gate (player &p, const tripoint &examp)
Open or close gate.
void iexamine::cardreader (player &p, const tripoint &examp)
Use id/hack reader.
void iexamine::cardreader_robofac (player &p, const tripoint &examp)
void iexamine::cardreader_foodplace (player &p, const tripoint &examp)
void iexamine::intercom (player &p, const tripoint &examp)
void iexamine::cvdmachine (player &p, const tripoint &examp)
Pick an appropriate item and apply diamond coating if possible.
void iexamine::rubble (player &p, const tripoint &examp)
Prompt removal of rubble.
void iexamine::chainfence (player &p, const tripoint &examp)
Prompt climbing over fence.
void iexamine::bars (player &p, const tripoint &examp)
If player has amorphous trait, slip through the bars.
void iexamine::deployed_furniture (player &p, const tripoint &pos)
void iexamine::portable_structure (player &p, const tripoint &examp)
Determine structure's type and prompts its removal.
void iexamine::pit (player &p, const tripoint &examp)
If there is a 2x4 around, prompt placing it across pit.
void iexamine::pit_covered (player &p, const tripoint &examp)
Prompt removing the 2x4 placed across the pit.
void iexamine::slot_machine (player &p, const tripoint &examp)
Loop prompt to bet $10.
void iexamine::safe (player &p, const tripoint &examp)
Attempt to crack safe through audio-feedback manual lock manipulation.
void iexamine::gunsafe_el (player &p, const tripoint &examp)
Attempt to "hack" the gunsafe's electronic lock and open it.
void iexamine::harvest_furn_nectar (player &p, const tripoint &examp)
void iexamine::harvest_furn (player &p, const tripoint &examp)
void iexamine::harvest_ter_nectar (player &p, const tripoint &examp)
void iexamine::harvest_ter (player &p, const tripoint &examp)
void iexamine::harvested_plant (player &p, const tripoint &examp)
Only harvest a plant once per season.
void iexamine::locked_object (player &p, const tripoint &examp)
Checks whether PC has a crowbar then calls iuse.crowbar.
void iexamine::locked_object_pickable (player &p, const tripoint &examp)
Checks whether PC has picklocks then calls pick_lock_actor.
void iexamine::bulletin_board (player &p, const tripoint &examp)
void iexamine::fault (player &p, const tripoint &examp)
Display popup with reference to "The Enigma of Amigara Fault.".
void iexamine::notify (player &p, const tripoint &pos)
Display popup message pulled from the object's message property.
void iexamine::transform (player &p, const tripoint &pos)
Transform the examined object into the object specified by its transforms_into property.
void iexamine::pedestal_wyrm (player &p, const tripoint &examp)
Spawn 1d4 wyrms and sink pedestal into ground.
void iexamine::pedestal_temple (player &p, const tripoint &examp)
Put petrified eye on pedestal causing it to sink into ground and open temple.
void iexamine::door_peephole (player &p, const tripoint &examp)
Unlock/open door or attempt to peek through peephole.
void iexamine::fswitch (player &p, const tripoint &examp)
void iexamine::flower_tulip (player &p, const tripoint &examp)
void iexamine::flower_spurge (player &p, const tripoint &examp)
void iexamine::flower_poppy (player &p, const tripoint &examp)
Prompt pick (or drink nectar if able) poppy bud.
void iexamine::flower_cactus (player &p, const tripoint &examp)
Prompt pick cactus pad.
void iexamine::flower_bluebell (player &p, const tripoint &examp)
void iexamine::flower_dahlia (player &p, const tripoint &examp)
Dig up its roots or drink its nectar if you can.
void iexamine::flower_marloss (player &p, const tripoint &examp)
void iexamine::egg_sackbw (player &p, const tripoint &examp)
void iexamine::egg_sackcs (player &p, const tripoint &examp)
void iexamine::egg_sackws (player &p, const tripoint &examp)
void iexamine::fungus (player &p, const tripoint &examp)
Remove furniture.
void iexamine::dirtmound (player &p, const tripoint &examp)
If it's warm enough, pick one of the player's seeds and plant it.
void iexamine::aggie_plant (player &p, const tripoint &examp)
void iexamine::tree_hickory (player &p, const tripoint &examp)
void iexamine::tree_maple (player &p, const tripoint &examp)
void iexamine::tree_maple_tapped (player &p, const tripoint &examp)
void iexamine::shrub_marloss (player &p, const tripoint &examp)
void iexamine::tree_marloss (player &p, const tripoint &examp)
void iexamine::shrub_wildveggies (player &p, const tripoint &examp)
void iexamine::recycle_compactor (player &p, const tripoint &examp)
void iexamine::trap (player &p, const tripoint &examp)
void iexamine::water_source (player &p, const tripoint &examp)
void iexamine::clean_water_source (player &, const tripoint &examp)
void iexamine::kiln_empty (player &p, const tripoint &examp)
void iexamine::kiln_full (player &p, const tripoint &examp)
void iexamine::arcfurnace_empty (player &p, const tripoint &examp)
void iexamine::arcfurnace_full (player &p, const tripoint &examp)
void iexamine::autoclave_empty (player &p, const tripoint &)
void iexamine::autoclave_full (player &, const tripoint &examp)
void iexamine::fireplace (player &p, const tripoint &examp)
void iexamine::fvat_empty (player &p, const tripoint &examp)
void iexamine::fvat_full (player &p, const tripoint &examp)
void iexamine::keg (player &p, const tripoint &examp)
void iexamine::reload_furniture (player &p, const tripoint &examp)
void iexamine::use_furn_fake_item (player &p, const tripoint &examp)
void iexamine::curtains (player &p, const tripoint &examp)
void iexamine::sign (player &p, const tripoint &examp)
void iexamine::pay_gas (player &p, const tripoint &examp)
void iexamine::ledge (player &p, const tripoint &examp)
void iexamine::autodoc (player &p, const tripoint &examp)
void iexamine::translocator (player &p, const tripoint &examp)
void iexamine::on_smoke_out (const tripoint &examp, const time_point &start_time)
void iexamine::mill_finalize (player &, const tripoint &examp, const time_point &start_time)
void iexamine::quern_examine (player &p, const tripoint &examp)
void iexamine::smoker_options (player &p, const tripoint &examp)
void iexamine::open_safe (player &p, const tripoint &examp)
void iexamine::workbench (player &p, const tripoint &examp)
void iexamine::dimensional_portal (player &p, const tripoint &examp)
void iexamine::check_power (player &p, const tripoint &examp)
void iexamine::migo_nerve_cluster (player &p, const tripoint &examp)
bool iexamine::pour_into_keg (const tripoint &pos, item &liquid)
Pour liquid into a keg (furniture) on the map.
cata::optional< tripoint > iexamine::getGasPumpByNumber (const tripoint &p, int number)
bool iexamine::toPumpFuel (const tripoint &src, const tripoint &dst, int units)
cata::optional< tripoint > iexamine::getNearFilledGasTank (const tripoint &center, int &gas_units)
bool iexamine::has_keg (const tripoint &pos)
Check whether there is a keg on the map that can be filled via pour_into_keg.
std::list< item > iexamine::get_harvest_items (const itype &type, int plant_count, int seed_count, bool byproducts)
Items that appear when a generic plant is harvested.
std::vector< seed_tuple > iexamine::get_seed_entries (const std::vector< item * > &seed_inv)
Make lists of unique seed types and names for the menu(no multiple hemp seeds etc)
int iexamine::query_seed (const std::vector< seed_tuple > &seed_entries)
Choose seed for planting.
void iexamine::plant_seed (player &p, const tripoint &examp, const itype_id &seed_id)
Actual planting of selected seed.
void iexamine::harvest_plant (player &p, const tripoint &examp, bool from_activity=false)
Actual harvesting of selected plant.
void iexamine::fertilize_plant (player &p, const tripoint &tile, const itype_id &fertilizer)
itype_id iexamine::choose_fertilizer (player &p, const std::string &pname, bool ask_player)
ret_val< bool > iexamine::can_fertilize (player &p, const tripoint &tile, const itype_id &fertilizer)
void iexamine::practice_survival_while_foraging (player *p)
iexamine_function iexamine_function_from_string (const std::string &function_name)
Given then name of one of the above functions, returns the matching function pointer.
Macro Definition Documentation
CATA_SRC_IEXAMINE_H
#define CATA_SRC_IEXAMINE_H
Definition at line 3 of file iexamine.h.
Typedef Documentation
iexamine_function
using iexamine_function = void (*)(player &, const tripoint &)
Definition at line 142 of file iexamine.h.
seed_tuple
using seed_tuple = std::tuple<itype_id, std::string, int>
Definition at line 20 of file iexamine.h.
Function Documentation
iexamine_function_from_string()
iexamine_function iexamine_function_from_string (const std::string & function_name)
Given then name of one of the above functions, returns the matching function pointer.
If no match is found, defaults to iexamine::none but prints out a debug message as a warning.
Parameters
function_name The name of the function to get.
Returns
A function pointer to the specified function.
Definition at line 6154 of file iexamine.cpp.
{
    static const std::map<std::string, iexamine_function> function_map = {{
            { "none", &iexamine::none },
            { "deployed_furniture", &iexamine::deployed_furniture },
            { "cvdmachine", &iexamine::cvdmachine },
            { "nanofab", &iexamine::nanofab },
            { "gaspump", &iexamine::gaspump },
            { "atm", &iexamine::atm },
            { "vending", &iexamine::vending },
            { "toilet", &iexamine::toilet },
            { "elevator", &iexamine::elevator },
            { "controls_gate", &iexamine::controls_gate },
            { "cardreader", &iexamine::cardreader },
            { "cardreader_robofac", &iexamine::cardreader_robofac },
            { "cardreader_fp", &iexamine::cardreader_foodplace },
            { "intercom", &iexamine::intercom },
            { "rubble", &iexamine::rubble },
            { "chainfence", &iexamine::chainfence },
            { "bars", &iexamine::bars },
            { "portable_structure", &iexamine::portable_structure },
            { "pit", &iexamine::pit },
            { "pit_covered", &iexamine::pit_covered },
            { "slot_machine", &iexamine::slot_machine },
            { "safe", &iexamine::safe },
            { "bulletin_board", &iexamine::bulletin_board },
            { "fault", &iexamine::fault },
            { "notify", &iexamine::notify },
            { "transform", &iexamine::transform },
            { "pedestal_wyrm", &iexamine::pedestal_wyrm },
            { "pedestal_temple", &iexamine::pedestal_temple },
            { "door_peephole", &iexamine::door_peephole },
            { "fswitch", &iexamine::fswitch },
            { "flower_poppy", &iexamine::flower_poppy },
            { "flower_cactus", &iexamine::flower_cactus },
            { "fungus", &iexamine::fungus },
            { "flower_dahlia", &iexamine::flower_dahlia },
            { "flower_marloss", &iexamine::flower_marloss },
            { "egg_sackbw", &iexamine::egg_sackbw },
            { "egg_sackcs", &iexamine::egg_sackcs },
            { "egg_sackws", &iexamine::egg_sackws },
            { "dirtmound", &iexamine::dirtmound },
            { "aggie_plant", &iexamine::aggie_plant },
            { "fvat_empty", &iexamine::fvat_empty },
            { "fvat_full", &iexamine::fvat_full },
            { "keg", &iexamine::keg },
            { "harvest_furn_nectar", &iexamine::harvest_furn_nectar },
            { "harvest_furn", &iexamine::harvest_furn },
            { "harvest_ter_nectar", &iexamine::harvest_ter_nectar },
            { "harvest_ter", &iexamine::harvest_ter },
            { "harvested_plant", &iexamine::harvested_plant },
            { "shrub_marloss", &iexamine::shrub_marloss },
            { "translocator", &iexamine::translocator },
            { "tree_marloss", &iexamine::tree_marloss },
            { "tree_hickory", &iexamine::tree_hickory },
            { "tree_maple", &iexamine::tree_maple },
            { "tree_maple_tapped", &iexamine::tree_maple_tapped },
            { "shrub_wildveggies", &iexamine::shrub_wildveggies },
            { "recycle_compactor", &iexamine::recycle_compactor },
            { "trap", &iexamine::trap },
            { "water_source", &iexamine::water_source },
            { "clean_water_source", &iexamine::clean_water_source },
            { "reload_furniture", &iexamine::reload_furniture },
            { "use_furn_fake_item", &iexamine::use_furn_fake_item },
            { "curtains", &iexamine::curtains },
            { "sign", &iexamine::sign },
            { "pay_gas", &iexamine::pay_gas },
            { "gunsafe_el", &iexamine::gunsafe_el },
            { "locked_object", &iexamine::locked_object },
            { "locked_object_pickable", &iexamine::locked_object_pickable },
            { "kiln_empty", &iexamine::kiln_empty },
            { "kiln_full", &iexamine::kiln_full },
            { "arcfurnace_empty", &iexamine::arcfurnace_empty },
            { "arcfurnace_full", &iexamine::arcfurnace_full },
            { "autoclave_empty", &iexamine::autoclave_empty },
            { "autoclave_full", &iexamine::autoclave_full },
            { "fireplace", &iexamine::fireplace },
            { "ledge", &iexamine::ledge },
            { "autodoc", &iexamine::autodoc },
            { "quern_examine", &iexamine::quern_examine },
            { "smoker_options", &iexamine::smoker_options },
            { "open_safe", &iexamine::open_safe },
            { "workbench", &iexamine::workbench },
            { "dimensional_portal", &iexamine::dimensional_portal },
            { "check_power", &iexamine::check_power },
            { "migo_nerve_cluster", &iexamine::migo_nerve_cluster },
        }
    };
    auto iter = function_map.find( function_name );
    if( iter != function_map.end() ) {
        return iter->second;
    }
    //No match found
    debugmsg( "Could not find an iexamine function matching '%s'!", function_name );
    return &iexamine::none;
}
References iexamine::aggie_plant(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::atm(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), iexamine::bars(), iexamine::bulletin_board(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), iexamine::check_power(), iexamine::clean_water_source(), iexamine::controls_gate(), iexamine::curtains(), iexamine::cvdmachine(), debugmsg, iexamine::deployed_furniture(), iexamine::dimensional_portal(), iexamine::dirtmound(), iexamine::door_peephole(), iexamine::egg_sackbw(), iexamine::egg_sackcs(), iexamine::egg_sackws(), iexamine::elevator(), iexamine::fault(), iexamine::fireplace(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), iexamine::fswitch(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), iexamine::gunsafe_el(), iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), iexamine::harvested_plant(), iexamine::intercom(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), iexamine::ledge(), iexamine::locked_object(), iexamine::locked_object_pickable(), iexamine::migo_nerve_cluster(), iexamine::nanofab(), iexamine::none(), iexamine::notify(), iexamine::open_safe(), iexamine::pay_gas(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), iexamine::pit(), iexamine::pit_covered(), iexamine::portable_structure(), iexamine::quern_examine(), iexamine::recycle_compactor(), iexamine::reload_furniture(), iexamine::rubble(), iexamine::safe(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), iexamine::sign(), iexamine::slot_machine(), iexamine::smoker_options(), iexamine::toilet(), iexamine::transform(), iexamine::translocator(), iexamine::trap(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), iexamine::use_furn_fake_item(), iexamine::vending(), iexamine::water_source(), and iexamine::workbench().
Referenced by anonymous_namespace{gates.cpp}::gate_data::check(), and map_data_common_t::load().