Cataclysm BN: src/iexamine.cpp File Reference
iexamine.cpp File Reference
#include "iexamine.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <map>
#include <memory>
#include <set>
#include <type_traits>
#include <utility>
#include "activity_actor.h"
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "active_tile_data_def.h"
#include "ammo.h"
#include "avatar.h"
#include "avatar_action.h"
#include "avatar_functions.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_functions.h"
#include "colony.h"
#include "flag.h"
#include "color.h"
#include "construction.h"
#include "construction_group.h"
#include "construction_partial.h"
#include "coordinate_conversions.h"
#include "craft_command.h"
#include "creature.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "distribution_grid.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "field_type.h"
#include "flat_set.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "harvest.h"
#include "input.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_stack.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "magic_teleporter_list.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "map_functions.h"
#include "mapdata.h"
#include "material.h"
#include "messages.h"
#include "mission_companion.h"
#include "monster.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pickup.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "pldata.h"
#include "point.h"
#include "recipe.h"
#include "relic.h"
#include "requirements.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "timed_event.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather.h"
Classes
class anonymous_namespace{iexamine.cpp}::atm_menu
Implements iexamine::atm(...)
Namespaces
namespace anonymous_namespace{iexamine.cpp}
namespace sm_rack
Functions
static const std::string flag_AUTODOC ("AUTODOC")
static const std::string flag_AUTODOC_COUCH ("AUTODOC_COUCH")
static const std::string flag_BARRICADABLE_WINDOW_CURTAINS ("BARRICADABLE_WINDOW_CURTAINS")
static const std::string flag_CLOSES_PORTAL ("CLOSES_PORTAL")
static const std::string flag_CLIMB_SIMPLE ("CLIMB_SIMPLE")
static const std::string flag_COOKED ("COOKED")
static const std::string flag_DIAMOND ("DIAMOND")
static const std::string flag_FERTILIZER ("FERTILIZER")
static const std::string flag_FIRE ("FIRE")
static const std::string flag_FIRESTARTER ("FIRESTARTER")
static const std::string flag_GROWTH_HARVEST ("GROWTH_HARVEST")
static const std::string flag_IN_CBM ("IN_CBM")
static const std::string flag_NO_CVD ("NO_CVD")
static const std::string flag_NO_PACKED ("NO_PACKED")
static const std::string flag_NO_STERILE ("NO_STERILE")
static const std::string flag_NUTRIENT_OVERRIDE ("NUTRIENT_OVERRIDE")
static const std::string flag_OPENCLOSE_INSIDE ("OPENCLOSE_INSIDE")
static const std::string flag_PROCESSING ("PROCESSING")
static const std::string flag_PROCESSING_RESULT ("PROCESSING_RESULT")
static const std::string flag_SAFECRACK ("SAFECRACK")
static const std::string flag_SMOKABLE ("SMOKABLE")
static const std::string flag_SMOKED ("SMOKED")
static const std::string flag_SPLINT ("SPLINT")
static const std::string flag_VARSIZE ("VARSIZE")
static const std::string flag_WALL ("WALL")
static const std::string flag_WRITE_MESSAGE ("WRITE_MESSAGE")
static const std::string flag_ELEVATOR ("ELEVATOR")
static bool try_start_hacking (player &p, const tripoint &examp)
static std::pair< itype_id, const deploy_tent_actor * > find_tent_itype (const furn_str_id &id)
static safe_reference< item > find_best_prying_tool (player &p)
static safe_reference< item > find_best_lock_picking_tool (player &p)
static void apply_prying_tool (player &p, item *it, const tripoint &examp)
static void apply_lock_picking_tool (player &p, item *it, const tripoint &examp)
static bool dead_plant (bool flower, player &p, const tripoint &examp)
If it's winter: show msg and return true.
static bool can_drink_nectar (const player &p, const item &nectar)
Helper method to see if player has traits, hunger and mouthwear for drinking nectar.
static bool drink_nectar (player &p)
Consume Nectar.
static void handle_harvest (player &p, const std::string &itemid, bool force_drop)
Spawn an item after harvesting the plant.
static bool harvest_common (player &p, const tripoint &examp, bool furn, bool nectar, bool auto_forage=false)
static units::volume get_keg_capacity (const tripoint &pos)
static void displace_items_except_one_liquid (const tripoint &examp)
static void pick_plant (player &p, const tripoint &examp, const itype_id &itemType, ter_id new_ter, bool seeds=false)
static item_location maple_tree_sap_container ()
static int count_charges_in_list (const itype *type, const map_stack &items)
static int getNearPumpCount (const tripoint &p)
static int getGasDiscountCardQuality (const item &it)
static int findBestGasDiscount (player &p)
static std::string str_to_illiterate_str (std::string s)
static std::string getGasDiscountName (int discount)
static int getGasPricePerLiter (int discount)
static int fromPumpFuel (const tripoint &dst, const tripoint &src)
static void turnOnSelectedPump (const tripoint &p, int number)
static player & player_on_couch (player &p, const tripoint &autodoc_loc, player &null_patient, bool &adjacent_couch, tripoint &couch_pos)
static Character & operator_present (Character &p, const tripoint &autodoc_loc, Character &null_patient)
static item & cyborg_on_couch (const tripoint &couch_pos, item &null_cyborg)
static player & best_installer (player &p, player &null_player, int difficulty)
template<typename ... Args>
void popup_player_or_npc (player &p, const char *player_mes, const char *npc_mes, Args &&... args)
static int get_charcoal_charges (units::volume food)
static bool is_non_rotten_crafting_component (const item &it)
static void mill_activate (player &p, const tripoint &examp)
static void smoker_activate (player &p, const tripoint &examp)
static void smoker_finalize (player &, const tripoint &examp, const time_point &start_time)
static void smoker_load_food (player &p, const tripoint &examp, const units::volume &remaining_capacity)
static void mill_load_food (player &p, const tripoint &examp, const units::volume &remaining_capacity)
iexamine_function iexamine_function_from_string (const std::string &function_name)
Given then name of one of the above functions, returns the matching function pointer.
Variables
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_CLEAR_RUBBLE ("ACT_CLEAR_RUBBLE")
static const activity_id ACT_CRACKING ("ACT_CRACKING")
static const activity_id ACT_FORAGE ("ACT_FORAGE")
static const activity_id ACT_PLANT_SEED ("ACT_PLANT_SEED")
static const efftype_id effect_antibiotic ("antibiotic")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_earphones ("earphones")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_pblue ("pblue")
static const efftype_id effect_pkill2 ("pkill2")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_strong_antibiotic ("strong_antibiotic")
static const efftype_id effect_teleglow ("teleglow")
static const efftype_id effect_weak_antibiotic ("weak_antibiotic")
static const itype_id itype_2x4 ("2x4")
static const itype_id itype_arm_splint ("arm_splint")
static const itype_id itype_battery ("battery")
static const itype_id itype_bot_broken_cyborg ("bot_broken_cyborg")
static const itype_id itype_bot_prototype_cyborg ("bot_prototype_cyborg")
static const itype_id itype_cash_card ("cash_card")
static const itype_id itype_charcoal ("charcoal")
static const itype_id itype_chem_carbide ("chem_carbide")
static const itype_id itype_corpse ("corpse")
static const itype_id itype_electrohack ("electrohack")
static const itype_id itype_fake_milling_item ("fake_milling_item")
static const itype_id itype_fake_smoke_plume ("fake_smoke_plume")
static const itype_id itype_fertilizer ("fertilizer")
static const itype_id itype_fire ("fire")
static const itype_id itype_fungal_seeds ("fungal_seeds")
static const itype_id itype_grapnel ("grapnel")
static const itype_id itype_hickory_root ("hickory_root")
static const itype_id itype_id_industrial ("id_industrial")
static const itype_id itype_id_military ("id_military")
static const itype_id itype_id_science ("id_science")
static const itype_id itype_leg_splint ("leg_splint")
static const itype_id itype_maple_sap ("maple_sap")
static const itype_id itype_marloss_berry ("marloss_berry")
static const itype_id itype_marloss_seed ("marloss_seed")
static const itype_id itype_mycus_fruit ("mycus_fruit")
static const itype_id itype_nail ("nail")
static const itype_id itype_petrified_eye ("petrified_eye")
static const itype_id itype_sheet ("sheet")
static const itype_id itype_stick ("stick")
static const itype_id itype_string_36 ("string_36")
static const itype_id itype_tree_spile ("tree_spile")
static const itype_id itype_unfinished_cac2 ("unfinished_cac2")
static const itype_id itype_unfinished_charcoal ("unfinished_charcoal")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_water ("water")
static const trap_str_id tr_unfinished_construction ("tr_unfinished_construction")
static const skill_id skill_computer ("computer")
static const skill_id skill_cooking ("cooking")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_mechanics ("mechanics")
static const skill_id skill_survival ("survival")
static const ter_str_id t_dimensional_portal ("t_dimensional_portal")
static const ter_str_id t_web_bridge ("t_web_bridge")
static const trait_id trait_AMORPHOUS ("AMORPHOUS")
static const trait_id trait_ARACHNID_ARMS_OK ("ARACHNID_ARMS_OK")
static const trait_id trait_BADKNEES ("BADKNEES")
static const trait_id trait_BEAK_HUM ("BEAK_HUM")
static const trait_id trait_BURROW ("BURROW")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_INSECT_ARMS_OK ("INSECT_ARMS_OK")
static const trait_id trait_M_DEFENDER ("M_DEFENDER")
static const trait_id trait_M_DEPENDENT ("M_DEPENDENT")
static const trait_id trait_M_FERTILE ("M_FERTILE")
static const trait_id trait_M_SPORES ("M_SPORES")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PARKOUR ("PARKOUR")
static const trait_id trait_PROBOSCIS ("PROBOSCIS")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const trait_id trait_WEB_BRDIGE ("WEB_BRIDGE")
static const quality_id qual_ANESTHESIA ("ANESTHESIA")
static const quality_id qual_DIG ("DIG")
static const mtype_id mon_broken_cyborg ("mon_broken_cyborg")
static const mtype_id mon_dark_wyrm ("mon_dark_wyrm")
static const mtype_id mon_fungal_blossom ("mon_fungal_blossom")
static const mtype_id mon_prototype_cyborg ("mon_prototype_cyborg")
static const mtype_id mon_spider_cellar_giant_s ("mon_spider_cellar_giant_s")
static const mtype_id mon_spider_web_s ("mon_spider_web_s")
static const mtype_id mon_spider_widow_giant_s ("mon_spider_widow_giant_s")
static const bionic_id bio_ears ("bio_ears")
static const bionic_id bio_fingerhack ("bio_fingerhack")
static const bionic_id bio_lighter ("bio_lighter")
static const bionic_id bio_painkiller ("bio_painkiller")
static const bionic_id bio_power_storage ("bio_power_storage")
static const bionic_id bio_power_storage_mkII ("bio_power_storage_mkII")
static const time_duration milling_time = 6_hours
const int sm_rack::MIN_CHARCOAL = 100
const int sm_rack::CHARCOAL_PER_LITER = 25
const units::volume sm_rack::MAX_FOOD_VOLUME = units::from_liter(20)
const units::volume sm_rack::MAX_FOOD_VOLUME_PORTABLE = units::from_liter(15)
Function Documentation
apply_lock_picking_tool()
static void apply_lock_picking_tool (player & p, item * it, const tripoint & examp) static
Definition at line 1523 of file iexamine.cpp.
{
    map &here = get_map();
    const auto actor = dynamic_cast<const pick_lock_actor *>
                       ( it->type->get_use( "picklock" )->get_actor_ptr() );
    p.add_msg_if_player( _( "You attempt to pick lock of %1$s using your %2$s" ),
                         here.has_furn( examp ) ? here.furnname( examp ) : here.tername( examp ), it->tname() );
    const ret_val<bool> can_use = actor->can_use( p, *it, false, examp );
    if( can_use.success() ) {
        actor->use( p, *it, false, examp );
        return;
    } else {
        p.add_msg_if_player( m_bad, can_use.str() );
    }
}
References _, player::add_msg_if_player(), map::furnname(), use_function::get_actor_ptr(), get_map(), itype::get_use(), map::has_furn(), m_bad, ret_val< T >::str(), ret_val< T >::success(), map::tername(), item::tname(), and item::type.
Referenced by iexamine::locked_object(), and iexamine::locked_object_pickable().
apply_prying_tool()
static void apply_prying_tool (player & p, item * it, const tripoint & examp) static
Definition at line 1511 of file iexamine.cpp.
{
    map &here = get_map();
    //~ %1$s: terrain/furniture name, %2$s: prying tool name
    p.add_msg_if_player( _( "You attempt to pry open the %1$s using your %2$s" ),
                         here.has_furn( examp ) ? here.furnname( examp ) : here.tername( examp ), it->tname() );
    // if crowbar() ever eats charges or otherwise alters the passed item, rewrite this to reflect
    // changes to the original item.
    iuse::crowbar( &p, it, false, examp );
}
References _, player::add_msg_if_player(), iuse::crowbar(), map::furnname(), get_map(), map::has_furn(), map::tername(), and item::tname().
Referenced by iexamine::locked_object().
best_installer()
static player & best_installer (player & p, player & null_player, int difficulty) static
Definition at line 4808 of file iexamine.cpp.
{
    float player_skill = p.bionics_adjusted_skill( skill_firstaid,
                         skill_computer,
                         skill_electronics );
    std::vector< std::pair<float, int>> ally_skills;
    ally_skills.reserve( g->allies().size() );
    for( size_t i = 0; i < g->allies().size() ; i ++ ) {
        std::pair<float, int> ally_skill;
        const npc *e = g->allies()[ i ];
        player &ally = *g->critter_by_id<player>( e->getID() );
        ally_skill.second = i;
        ally_skill.first = ally.bionics_adjusted_skill( skill_firstaid,
                           skill_computer,
                           skill_electronics );
        ally_skills.push_back( ally_skill );
    }
    std::sort( ally_skills.begin(), ally_skills.end(), [&]( const std::pair<float, int> &lhs,
    const std::pair<float, int> &rhs ) {
        return rhs.first < lhs.first;
    } );
    int player_cos = bionic_manip_cos( player_skill, difficulty );
    for( size_t i = 0; i < g->allies().size() ; i ++ ) {
        if( ally_skills[ i ].first > player_skill ) {
            const npc *e = g->allies()[ ally_skills[ i ].second ];
            player &ally = *g->critter_by_id<player>( e->getID() );
            int ally_cos = bionic_manip_cos( ally_skills[ i ].first, difficulty );
            if( e->has_effect( effect_sleep ) ) {
                if( !g->u.query_yn(
                        //~ %1$s is the name of the ally
                        _( "<color_white>%1$s is asleep, but has a <color_green>%2$d<color_white> chance of success compared to your <color_red>%3$d<color_white> chance of success.  Continue with a higher risk of failure?</color>" ),
                        ally.disp_name(), ally_cos, player_cos ) ) {
                    return null_player;
                } else {
                    continue;
                }
            }
            //~ %1$s is the name of the ally
            add_msg( _( "%1$s will perform the operation with a %2$d chance of success." ), ally.disp_name(),
                     ally_cos );
            return ally;
        } else {
            break;
        }
    }
    return p;
}
References _, add_msg(), bionic_manip_cos(), Character::bionics_adjusted_skill(), Character::disp_name(), effect_sleep, g, Character::getID(), Creature::has_effect(), om_direction::size, skill_computer, skill_electronics, and skill_firstaid.
Referenced by iexamine::autodoc().
can_drink_nectar()
static bool can_drink_nectar (const player & p, const item & nectar) static
Helper method to see if player has traits, hunger and mouthwear for drinking nectar.
Definition at line 1865 of file iexamine.cpp.
{
    return ( p.has_active_mutation( trait_PROBOSCIS )  ||
             p.has_active_mutation( trait_BEAK_HUM ) ) &&
           ( ( p.max_stored_kcal() - p.get_stored_kcal() ) >
             nectar.get_comestible()->default_nutrition.kcal ) &&
           ( !( p.wearing_something_on( bodypart_id( "mouth" ) ) ) );
}
References item::get_comestible(), Character::get_stored_kcal(), Character::has_active_mutation(), Character::max_stored_kcal(), trait_BEAK_HUM, trait_PROBOSCIS, and Character::wearing_something_on().
Referenced by drink_nectar(), iexamine::flower_marloss(), and iexamine::flower_poppy().
count_charges_in_list()
static int count_charges_in_list (const itype * type, const map_stack & items) static
Definition at line 3909 of file iexamine.cpp.
{
    for( const auto &candidate : items ) {
        if( candidate.type == type ) {
            return candidate.charges;
        }
    }
    return 0;
}
References type.
Referenced by iexamine::reload_furniture(), smoker_activate(), iexamine::smoker_options(), and iexamine::use_furn_fake_item().
cyborg_on_couch()
static item & cyborg_on_couch (const tripoint & couch_pos, item & null_cyborg) static
Definition at line 4777 of file iexamine.cpp.
{
    for( item &it : get_map().i_at( couch_pos ) ) {
        if( it.typeId() == itype_bot_broken_cyborg || it.typeId() == itype_bot_prototype_cyborg ) {
            return it;
        }
        if( it.typeId() == itype_corpse ) {
            if( it.get_mtype()->id == mon_broken_cyborg || it.get_mtype()->id == mon_prototype_cyborg ) {
                return it;
            }
        }
    }
    // if we're in a autodoc couch on a vehicle, go through the items in it, and return the item if's a cyborg
    if( const cata::optional<vpart_reference> vp = get_map().veh_at( couch_pos ).part_with_feature(
                flag_AUTODOC_COUCH, false ) ) {
        auto dest_veh = &vp->vehicle();
        int dest_part = vp->part_index();
        for( item &it : dest_veh->get_items( dest_part ) ) {
            if( it.typeId() == itype_bot_broken_cyborg || it.typeId() == itype_bot_prototype_cyborg ) {
                return it;
            }
            if( it.typeId() == itype_corpse ) {
                if( it.get_mtype()->id == mon_broken_cyborg || it.get_mtype()->id == mon_prototype_cyborg ) {
                    return it;
                }
            }
        }
    }
    return null_cyborg;
}
References flag_AUTODOC_COUCH(), get_map(), mtype::id, itype_bot_broken_cyborg, itype_bot_prototype_cyborg, itype_corpse, mon_broken_cyborg, and mon_prototype_cyborg.
Referenced by iexamine::autodoc().
dead_plant()
static bool dead_plant (bool flower, player & p, const tripoint & examp) static
If it's winter: show msg and return true.
Otherwise return false
Definition at line 1846 of file iexamine.cpp.
{
    if( season_of_year( calendar::turn ) == WINTER ) {
        if( flower ) {
            add_msg( m_info, _( "This flower is dead.  You can't get it." ) );
        } else {
            add_msg( m_info, _( "This plant is dead.  You can't get it." ) );
        }
        iexamine::none( p, examp );
        return true;
    }
    return false;
}
References _, add_msg(), m_info, iexamine::none(), season_of_year(), calendar::turn, and WINTER.
Referenced by iexamine::flower_cactus(), iexamine::flower_dahlia(), and iexamine::flower_poppy().
displace_items_except_one_liquid()
static void displace_items_except_one_liquid (const tripoint & examp) static
Definition at line 3227 of file iexamine.cpp.
{
    map &here = get_map();
    // Temporarily replace the real furniture with a fake furniture with NOITEM
    const furn_id previous_furn = here.furn( examp );
    here.furn_set( examp, furn_id( "f_no_item" ) );
    bool liquid_present = false;
    map_stack items = here.i_at( examp );
    for( map_stack::iterator it = items.begin(); it != items.end(); ) {
        if( !it->made_of( LIQUID ) || liquid_present ) {
            // This isn't a liquid or there was already another kind of liquid inside,
            // so this has to be moved.
            // This will add items to a space near the vat, because it's flagged as NOITEM.
            items.insert( *it );
            it = items.erase( it );
        } else {
            it++;
            liquid_present = true;
        }
    }
    // Replace the real furniture
    here.furn_set( examp, previous_furn );
}
References item_stack::begin(), item_stack::end(), map_stack::erase(), map::furn(), map::furn_set(), get_map(), map::i_at(), map_stack::insert(), and LIQUID.
Referenced by iexamine::keg().
drink_nectar()
static bool drink_nectar (player & p) static
Consume Nectar.
-15 hunger.
Definition at line 1877 of file iexamine.cpp.
{
    item nectar( "nectar", calendar::turn, 1 );
    if( can_drink_nectar( p, nectar ) ) {
        p.moves -= to_moves<int>( 30_seconds );
        add_msg( _( "You drink some nectar." ) );
        p.eat( nectar );
        return true;
    }
    return false;
}
References _, add_msg(), can_drink_nectar(), Character::eat(), Creature::moves, and calendar::turn.
Referenced by iexamine::flower_dahlia(), and harvest_common().
find_best_lock_picking_tool()
static safe_reference< item > find_best_lock_picking_tool (player & p) static
Definition at line 1488 of file iexamine.cpp.
{
    std::vector<item *> picklocks = p.items_with( []( const item & it ) {
        // we want to get worn items (eg hairpin), so no check on item position
        return it.type->get_use( "picklock" ) != nullptr;
    } );
    // Sort by their picklock level.
    std::sort( picklocks.begin(), picklocks.end(), [&]( const item * a, const item * b ) {
        const auto actor_a = dynamic_cast<const pick_lock_actor *>
                             ( a->type->get_use( "picklock" )->get_actor_ptr() );
        const auto actor_b = dynamic_cast<const pick_lock_actor *>
                             ( b->type->get_use( "picklock" )->get_actor_ptr() );
        return actor_a->pick_quality > actor_b->pick_quality;
    } );
    if( picklocks.empty() ) {
        return safe_reference<item>();
    }
    return ( *picklocks[0] ).get_safe_reference();
}
References a, b, itype::get_use(), visitable< T >::items_with(), and item::type.
Referenced by iexamine::locked_object(), and iexamine::locked_object_pickable().
find_best_prying_tool()
static safe_reference< item > find_best_prying_tool (player & p) static
Definition at line 1468 of file iexamine.cpp.
{
    std::vector<item *> prying_items = p.items_with( []( const item & it ) {
        // we want to get worn items (eg crowbar in toolbelt), so no check on item position
        return it.has_quality( quality_id( "PRY" ), 1 );
    } );
    // Sort by their quality level.
    std::sort( prying_items.begin(), prying_items.end(), []( const item * a, const item * b ) -> bool {
        return a->get_quality( quality_id( "PRY" ) ) > b->get_quality( quality_id( "PRY" ) );
    } );
    // if crowbar() ever eats charges or otherwise alters the passed item, rewrite this to reflect
    // changes to the original item.
    if( prying_items.empty() ) {
        return safe_reference<item>();
    }
    return ( *prying_items[0] ).get_safe_reference();
}
References a, b, visitable< T >::has_quality(), and visitable< T >::items_with().
Referenced by iexamine::locked_object().
find_tent_itype()
static std::pair< itype_id, const deploy_tent_actor * > find_tent_itype (const furn_str_id & id) static
Definition at line 1250 of file iexamine.cpp.
{
    const itype_id &iid = id->deployed_item;
    if( iid.is_valid() ) {
        const itype &type = *iid;
        for( const auto &pair : type.use_methods ) {
            const auto actor = dynamic_cast<const deploy_tent_actor *>( pair.second.get_actor_ptr() );
            if( !actor ) {
                continue;
            }
            if( ( actor->floor_center && *actor->floor_center == id ) || ( !actor->floor_center &&
                    actor->floor == id ) ) {
                return std::make_pair( iid, actor );
            }
        }
    }
    return std::make_pair( iid, nullptr );
}
References int_id< T >::id(), string_id< T >::is_valid(), and type.
Referenced by iexamine::portable_structure().
findBestGasDiscount()
static int findBestGasDiscount (player & p) static
Definition at line 4292 of file iexamine.cpp.
{
    int discount = 0;
    for( size_t i = 0; i < p.inv.size(); i++ ) {
        item &it = p.inv.find_item( i );
        if( it.has_flag( "GAS_DISCOUNT" ) ) {
            int q = getGasDiscountCardQuality( it );
            if( q > discount ) {
                discount = q;
            }
        }
    }
    return discount;
}
References inventory::find_item(), getGasDiscountCardQuality(), item::has_flag(), Character::inv, and inventory::size().
Referenced by iexamine::pay_gas().
flag_AUTODOC()
static const std::string flag_AUTODOC ("AUTODOC") static
Referenced by iexamine::autodoc().
flag_AUTODOC_COUCH()
static const std::string flag_AUTODOC_COUCH ("AUTODOC_COUCH") static
Referenced by cyborg_on_couch(), operator_present(), and player_on_couch().
flag_BARRICADABLE_WINDOW_CURTAINS()
static const std::string flag_BARRICADABLE_WINDOW_CURTAINS ("BARRICADABLE_WINDOW_CURTAINS") static
Referenced by iexamine::curtains().
flag_CLIMB_SIMPLE()
static const std::string flag_CLIMB_SIMPLE ("CLIMB_SIMPLE") static
Referenced by iexamine::chainfence().
flag_CLOSES_PORTAL()
static const std::string flag_CLOSES_PORTAL ("CLOSES_PORTAL") static
Referenced by iexamine::dimensional_portal().
flag_COOKED()
static const std::string flag_COOKED ("COOKED") static
Referenced by smoker_finalize().
flag_DIAMOND()
static const std::string flag_DIAMOND ("DIAMOND") static
Referenced by iexamine::cvdmachine().
flag_ELEVATOR()
static const std::string flag_ELEVATOR ("ELEVATOR") static
Referenced by iexamine::elevator().
flag_FERTILIZER()
static const std::string flag_FERTILIZER ("FERTILIZER") static
Referenced by iexamine::choose_fertilizer().
flag_FIRE()
static const std::string flag_FIRE ("FIRE") static
flag_FIRESTARTER()
static const std::string flag_FIRESTARTER ("FIRESTARTER") static
flag_GROWTH_HARVEST()
static const std::string flag_GROWTH_HARVEST ("GROWTH_HARVEST") static
Referenced by iexamine::aggie_plant().
flag_IN_CBM()
static const std::string flag_IN_CBM ("IN_CBM") static
Referenced by iexamine::autodoc().
flag_NO_CVD()
static const std::string flag_NO_CVD ("NO_CVD") static
Referenced by iexamine::cvdmachine().
flag_NO_PACKED()
static const std::string flag_NO_PACKED ("NO_PACKED") static
Referenced by iexamine::autoclave_full(), and iexamine::autodoc().
flag_NO_STERILE()
static const std::string flag_NO_STERILE ("NO_STERILE") static
Referenced by iexamine::autoclave_full(), and iexamine::autodoc().
flag_NUTRIENT_OVERRIDE()
static const std::string flag_NUTRIENT_OVERRIDE ("NUTRIENT_OVERRIDE") static
Referenced by smoker_finalize().
flag_OPENCLOSE_INSIDE()
static const std::string flag_OPENCLOSE_INSIDE ("OPENCLOSE_INSIDE") static
Referenced by iexamine::door_peephole().
flag_PROCESSING()
static const std::string flag_PROCESSING ("PROCESSING") static
Referenced by mill_activate(), smoker_activate(), and smoker_finalize().
flag_PROCESSING_RESULT()
static const std::string flag_PROCESSING_RESULT ("PROCESSING_RESULT") static
Referenced by iexamine::mill_finalize(), and smoker_finalize().
flag_SAFECRACK()
static const std::string flag_SAFECRACK ("SAFECRACK") static
Referenced by iexamine::safe().
flag_SMOKABLE()
static const std::string flag_SMOKABLE ("SMOKABLE") static
Referenced by smoker_activate(), smoker_finalize(), and smoker_load_food().
flag_SMOKED()
static const std::string flag_SMOKED ("SMOKED") static
Referenced by smoker_activate().
flag_SPLINT()
static const std::string flag_SPLINT ("SPLINT") static
Referenced by iexamine::autodoc().
flag_VARSIZE()
static const std::string flag_VARSIZE ("VARSIZE") static
Referenced by iexamine::nanofab().
flag_WALL()
static const std::string flag_WALL ("WALL") static
Referenced by iexamine::curtains().
flag_WRITE_MESSAGE()
static const std::string flag_WRITE_MESSAGE ("WRITE_MESSAGE") static
Referenced by iexamine::sign().
fromPumpFuel()
static int fromPumpFuel (const tripoint & dst, const tripoint & src) static
Definition at line 4397 of file iexamine.cpp.
{
    map &here = get_map();
    auto items = here.i_at( src );
    for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
        if( item_it->made_of( LIQUID ) ) {
            // how much do we have in the pump?
            item liq_d( item_it->type, calendar::turn, item_it->charges );
            // add the charges to the destination
            const auto backup_tank = here.ter( dst );
            here.ter_set( dst, ter_str_id::NULL_ID() );
            here.add_item_or_charges( dst, liq_d );
            here.ter_set( dst, backup_tank );
            // remove the liquid from the pump
            int amount = item_it->charges;
            items.erase( item_it );
            return amount;
        }
    }
    return -1;
}
References map::add_item_or_charges(), get_map(), map::i_at(), LIQUID, string_id< ter_t >::NULL_ID(), map::ter(), map::ter_set(), and calendar::turn.
Referenced by iexamine::pay_gas().
get_charcoal_charges()
static int get_charcoal_charges (units::volume food) static
Definition at line 5290 of file iexamine.cpp.
{
    const int charcoal = to_liter( food ) * sm_rack::CHARCOAL_PER_LITER;
    return  std::max( charcoal, sm_rack::MIN_CHARCOAL );
}
References sm_rack::CHARCOAL_PER_LITER, sm_rack::MIN_CHARCOAL, and units::to_liter().
Referenced by smoker_activate(), and iexamine::smoker_options().
get_keg_capacity()
static units::volume get_keg_capacity (const tripoint & pos) static
Definition at line 3213 of file iexamine.cpp.
{
    const furn_t &furn = get_map().furn( pos ).obj();
    return furn.keg_capacity;
}
References map::furn(), get_map(), furn_t::keg_capacity, and int_id< T >::obj().
Referenced by iexamine::has_keg(), iexamine::keg(), and iexamine::pour_into_keg().
getGasDiscountCardQuality()
static int getGasDiscountCardQuality (const item & it) static
Definition at line 4278 of file iexamine.cpp.
{
    const auto &tags = it.type->get_flags();
    for( const std::string &tag : tags ) {
        if( tag.size() > 15 && tag.substr( 0, 15 ) == "DISCOUNT_VALUE_" ) {
            return atoi( tag.substr( 15 ).c_str() );
        }
    }
    return 0;
}
References itype::get_flags(), and item::type.
Referenced by findBestGasDiscount().
getGasDiscountName()
static std::string getGasDiscountName (int discount) static
Definition at line 4330 of file iexamine.cpp.
{
    if( discount == 3 ) {
        return str_to_illiterate_str( _( "Platinum member" ) );
    } else if( discount == 2 ) {
        return str_to_illiterate_str( _( "Gold member" ) );
    } else if( discount == 1 ) {
        return str_to_illiterate_str( _( "Silver member" ) );
    } else {
        return str_to_illiterate_str( _( "Beloved customer" ) );
    }
}
References _, and str_to_illiterate_str().
Referenced by iexamine::pay_gas().
getGasPricePerLiter()
static int getGasPricePerLiter (int discount) static
Definition at line 4343 of file iexamine.cpp.
{
    // Those prices are in cents
    static const int prices[4] = { 1400, 1320, 1200, 1000 };
    if( discount < 0 || discount > 3 ) {
        return prices[0];
    } else {
        return prices[discount];
    }
}
Referenced by iexamine::pay_gas().
getNearPumpCount()
static int getNearPumpCount (const tripoint & p) static
Definition at line 4232 of file iexamine.cpp.
{
    int result = 0;
    map &here = get_map();
    for( const tripoint &tmp : here.points_in_radius( p, 12 ) ) {
        const auto t = here.ter( tmp );
        if( t == ter_str_id( "t_gas_pump" ) || t == ter_str_id( "t_gas_pump_a" ) ) {
            result++;
        }
    }
    return result;
}
References get_map(), map::points_in_radius(), and map::ter().
Referenced by iexamine::pay_gas().
handle_harvest()
static void handle_harvest (player & p, const std::string & itemid, bool force_drop) static
Spawn an item after harvesting the plant.
Definition at line 1893 of file iexamine.cpp.
{
    item harvest = item( itemid );
    if( !force_drop && p.can_pick_volume( harvest ) &&
        p.can_pick_weight( harvest, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
        p.i_add( harvest );
        p.add_msg_if_player( _( "You harvest: %s." ), harvest.tname() );
    } else {
        get_map().add_item_or_charges( p.pos(), harvest );
        p.add_msg_if_player( _( "You harvest and drop: %s." ), harvest.tname() );
    }
}
References _, map::add_item_or_charges(), player::add_msg_if_player(), Character::can_pick_volume(), Character::can_pick_weight(), get_map(), harvest, Character::i_add(), and Character::pos().
Referenced by iexamine::egg_sack_generic(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), and harvest_common().
harvest_common()
static bool harvest_common (player & p, const tripoint & examp, bool furn, bool nectar, bool auto_forage = false) static
Definition at line 2034 of file iexamine.cpp.
{
    map &here = get_map();
    const auto hid = here.get_harvest( examp );
    if( hid.is_null() || hid->empty() ) {
        if( !auto_forage ) {
            p.add_msg_if_player( m_info, _( "Nothing can be harvested from this plant in current season." ) );
        }
        if( p.manual_examine ) {
            iexamine::none( p, examp );
        }
        return false;
    }
    const auto &harvest = hid.obj();
    // If nothing can be harvested, neither can nectar
    // Incredibly low priority TODO: Allow separating nectar seasons
    if( nectar && drink_nectar( p ) ) {
        return false;
    }
    if( p.is_player() && !auto_forage &&
        !query_yn( _( "Pick %s?" ), furn ? here.furnname( examp ) : here.tername(
                       examp ) ) ) {
        iexamine::none( p, examp );
        return false;
    }
    int lev = p.get_skill_level( skill_survival );
    bool got_anything = false;
    for( const auto &entry : harvest ) {
        float min_num = entry.base_num.first + lev * entry.scale_num.first;
        float max_num = entry.base_num.second + lev * entry.scale_num.second;
        int roll = std::min<int>( entry.max, std::round( rng_float( min_num, max_num ) ) );
        if( roll >= 1 ) {
            got_anything = true;
            for( int i = 0; i < roll; i++ ) {
                handle_harvest( p, entry.drop, false );
            }
        }
    }
    if( !got_anything ) {
        p.add_msg_if_player( m_bad, _( "You couldn't harvest anything." ) );
    }
    iexamine::practice_survival_while_foraging( &p );
    p.mod_moves( -to_moves<int>( rng( 5_seconds, 15_seconds ) ) );
    return true;
}
References _, player::add_msg_if_player(), drink_nectar(), Character::drop(), map::furnname(), map::get_harvest(), get_map(), Character::get_skill_level(), handle_harvest(), harvest, player::is_player(), m_bad, m_info, player::manual_examine, Creature::mod_moves(), iexamine::none(), iexamine::practice_survival_while_foraging(), query_yn(), rng(), rng_float(), skill_survival, and map::tername().
Referenced by iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), and iexamine::tree_hickory().
iexamine_function_from_string()
iexamine_function iexamine_function_from_string (const std::string & function_name)
Given then name of one of the above functions, returns the matching function pointer.
If no match is found, defaults to iexamine::none but prints out a debug message as a warning.
Parameters
function_name The name of the function to get.
Returns
A function pointer to the specified function.
Definition at line 6268 of file iexamine.cpp.
{
    static const std::map<std::string, iexamine_function> function_map = {{
            { "none", &iexamine::none },
            { "deployed_furniture", &iexamine::deployed_furniture },
            { "cvdmachine", &iexamine::cvdmachine },
            { "nanofab", &iexamine::nanofab },
            { "gaspump", &iexamine::gaspump },
            { "atm", &iexamine::atm },
            { "vending", &iexamine::vending },
            { "toilet", &iexamine::toilet },
            { "elevator", &iexamine::elevator },
            { "controls_gate", &iexamine::controls_gate },
            { "cardreader", &iexamine::cardreader },
            { "cardreader_robofac", &iexamine::cardreader_robofac },
            { "cardreader_fp", &iexamine::cardreader_foodplace },
            { "intercom", &iexamine::intercom },
            { "rubble", &iexamine::rubble },
            { "chainfence", &iexamine::chainfence },
            { "bars", &iexamine::bars },
            { "portable_structure", &iexamine::portable_structure },
            { "pit", &iexamine::pit },
            { "pit_covered", &iexamine::pit_covered },
            { "slot_machine", &iexamine::slot_machine },
            { "safe", &iexamine::safe },
            { "bulletin_board", &iexamine::bulletin_board },
            { "fault", &iexamine::fault },
            { "notify", &iexamine::notify },
            { "transform", &iexamine::transform },
            { "pedestal_wyrm", &iexamine::pedestal_wyrm },
            { "pedestal_temple", &iexamine::pedestal_temple },
            { "door_peephole", &iexamine::door_peephole },
            { "fswitch", &iexamine::fswitch },
            { "flower_poppy", &iexamine::flower_poppy },
            { "flower_cactus", &iexamine::flower_cactus },
            { "fungus", &iexamine::fungus },
            { "flower_dahlia", &iexamine::flower_dahlia },
            { "flower_marloss", &iexamine::flower_marloss },
            { "egg_sackbw", &iexamine::egg_sackbw },
            { "egg_sackcs", &iexamine::egg_sackcs },
            { "egg_sackws", &iexamine::egg_sackws },
            { "dirtmound", &iexamine::dirtmound },
            { "aggie_plant", &iexamine::aggie_plant },
            { "fvat_empty", &iexamine::fvat_empty },
            { "fvat_full", &iexamine::fvat_full },
            { "keg", &iexamine::keg },
            { "harvest_furn_nectar", &iexamine::harvest_furn_nectar },
            { "harvest_furn", &iexamine::harvest_furn },
            { "harvest_ter_nectar", &iexamine::harvest_ter_nectar },
            { "harvest_ter", &iexamine::harvest_ter },
            { "harvested_plant", &iexamine::harvested_plant },
            { "shrub_marloss", &iexamine::shrub_marloss },
            { "translocator", &iexamine::translocator },
            { "tree_marloss", &iexamine::tree_marloss },
            { "tree_hickory", &iexamine::tree_hickory },
            { "tree_maple", &iexamine::tree_maple },
            { "tree_maple_tapped", &iexamine::tree_maple_tapped },
            { "shrub_wildveggies", &iexamine::shrub_wildveggies },
            { "recycle_compactor", &iexamine::recycle_compactor },
            { "trap", &iexamine::trap },
            { "water_source", &iexamine::water_source },
            { "clean_water_source", &iexamine::clean_water_source },
            { "reload_furniture", &iexamine::reload_furniture },
            { "use_furn_fake_item", &iexamine::use_furn_fake_item },
            { "curtains", &iexamine::curtains },
            { "sign", &iexamine::sign },
            { "pay_gas", &iexamine::pay_gas },
            { "gunsafe_el", &iexamine::gunsafe_el },
            { "locked_object", &iexamine::locked_object },
            { "locked_object_pickable", &iexamine::locked_object_pickable },
            { "kiln_empty", &iexamine::kiln_empty },
            { "kiln_full", &iexamine::kiln_full },
            { "arcfurnace_empty", &iexamine::arcfurnace_empty },
            { "arcfurnace_full", &iexamine::arcfurnace_full },
            { "autoclave_empty", &iexamine::autoclave_empty },
            { "autoclave_full", &iexamine::autoclave_full },
            { "fireplace", &iexamine::fireplace },
            { "ledge", &iexamine::ledge },
            { "autodoc", &iexamine::autodoc },
            { "quern_examine", &iexamine::quern_examine },
            { "smoker_options", &iexamine::smoker_options },
            { "open_safe", &iexamine::open_safe },
            { "workbench", &iexamine::workbench },
            { "dimensional_portal", &iexamine::dimensional_portal },
            { "check_power", &iexamine::check_power },
            { "migo_nerve_cluster", &iexamine::migo_nerve_cluster },
        }
    };
    auto iter = function_map.find( function_name );
    if( iter != function_map.end() ) {
        return iter->second;
    }
    //No match found
    debugmsg( "Could not find an iexamine function matching '%s'!", function_name );
    return &iexamine::none;
}
References iexamine::aggie_plant(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::atm(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), iexamine::bars(), iexamine::bulletin_board(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), iexamine::check_power(), iexamine::clean_water_source(), iexamine::controls_gate(), iexamine::curtains(), iexamine::cvdmachine(), debugmsg, iexamine::deployed_furniture(), iexamine::dimensional_portal(), iexamine::dirtmound(), iexamine::door_peephole(), iexamine::egg_sackbw(), iexamine::egg_sackcs(), iexamine::egg_sackws(), iexamine::elevator(), iexamine::fault(), iexamine::fireplace(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), iexamine::fswitch(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), iexamine::gunsafe_el(), iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), iexamine::harvested_plant(), iexamine::intercom(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), iexamine::ledge(), iexamine::locked_object(), iexamine::locked_object_pickable(), iexamine::migo_nerve_cluster(), iexamine::nanofab(), iexamine::none(), iexamine::notify(), iexamine::open_safe(), iexamine::pay_gas(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), iexamine::pit(), iexamine::pit_covered(), iexamine::portable_structure(), iexamine::quern_examine(), iexamine::recycle_compactor(), iexamine::reload_furniture(), iexamine::rubble(), iexamine::safe(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), iexamine::sign(), iexamine::slot_machine(), iexamine::smoker_options(), iexamine::toilet(), iexamine::transform(), iexamine::translocator(), iexamine::trap(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), iexamine::use_furn_fake_item(), iexamine::vending(), iexamine::water_source(), and iexamine::workbench().
Referenced by anonymous_namespace{gates.cpp}::gate_data::check(), and map_data_common_t::load().
is_non_rotten_crafting_component()
static bool is_non_rotten_crafting_component (const item & it) static
Definition at line 5297 of file iexamine.cpp.
{
    return is_crafting_component( it ) && !it.rotten();
}
References is_crafting_component(), and item::rotten().
Referenced by mill_load_food(), and smoker_load_food().
maple_tree_sap_container()
static item_location maple_tree_sap_container () static
Definition at line 3505 of file iexamine.cpp.
{
    const item maple_sap = item( itype_maple_sap, calendar::start_of_cataclysm );
    return g->inv_map_splice( [&]( const item & it ) {
        return it.get_remaining_capacity_for_liquid( maple_sap, true ) > 0;
    }, _( "Which container?" ), PICKUP_RANGE );
}
References _, g, item::get_remaining_capacity_for_liquid(), itype_maple_sap, PICKUP_RANGE, and calendar::start_of_cataclysm.
Referenced by iexamine::tree_maple(), and iexamine::tree_maple_tapped().
mill_activate()
static void mill_activate (player & p, const tripoint & examp) static
Definition at line 5302 of file iexamine.cpp.
{
    map &here = get_map();
    const furn_id cur_mill_type = here.furn( examp );
    furn_id next_mill_type = f_null;
    if( cur_mill_type == f_wind_mill ) {
        next_mill_type = f_wind_mill_active;
    } else if( cur_mill_type == f_water_mill ) {
        next_mill_type = f_water_mill_active;
    } else {
        debugmsg( "Examined furniture has action mill_activate, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    bool food_present = false;
    map_stack items = here.i_at( examp );
    units::volume food_volume = 0_ml;
    for( item &it : items ) {
        if( it.type->milling_data ) {
            food_present = true;
            food_volume += it.volume();
            continue;
        } else {
            add_msg( m_bad, _( "This mill contains %s, which can't be milled!" ), it.tname( 1, false ) );
            add_msg( _( "You remove the %s from the mill." ), it.tname() );
            here.add_item_or_charges( p.pos(), it );
            p.mod_moves( -p.item_handling_cost( it ) );
            here.i_rem( examp, &it );
            return;
        }
    }
    if( !food_present ) {
        add_msg( _( "This mill is empty.  Fill it with starchy products such as wheat, barley or oats and try again." ) );
        return;
    }
    // TODO: currently mill just uses sm_rack defined max volume
    if( food_volume > sm_rack::MAX_FOOD_VOLUME ) {
        add_msg( _( "This mill is overloaded with products, and the millstone can't turn.  Remove some and try again." ) );
        add_msg( pgettext( "volume units", "You think that you can load about %s %s in it." ),
                 format_volume( sm_rack::MAX_FOOD_VOLUME ), volume_units_long() );
        return;
    }
    for( auto &it : here.i_at( examp ) ) {
        if( it.type->milling_data ) {
            // Do one final rot check before milling, then apply the PROCESSING flag to prevent further checks.
            it.process_rot( examp );
            it.set_flag( flag_PROCESSING );
        }
    }
    here.furn_set( examp, next_mill_type );
    item result( "fake_milling_item", calendar::turn );
    result.item_counter = to_turns<int>( milling_time );
    result.activate();
    here.add_item( examp, result );
    add_msg( _( "You remove the brake on the millstone and it slowly starts to turn." ) );
}
References _, map::add_item(), map::add_item_or_charges(), add_msg(), string_id< T >::c_str(), debugmsg, f_null, f_water_mill, f_water_mill_active, f_wind_mill, f_wind_mill_active, flag_PROCESSING(), format_volume(), map::furn(), map::furn_set(), get_map(), map::i_at(), map::i_rem(), int_id< T >::id(), Character::item_handling_cost(), m_bad, sm_rack::MAX_FOOD_VOLUME, milling_time, Creature::mod_moves(), pgettext(), Character::pos(), calendar::turn, and volume_units_long().
Referenced by iexamine::quern_examine().
mill_load_food()
static void mill_load_food (player & p, const tripoint & examp, const units::volume & remaining_capacity) static
Definition at line 5676 of file iexamine.cpp.
{
    std::vector<item_comp> comps;
    map &here = get_map();
    if( here.furn( examp ) == furn_str_id( "f_wind_mill_active" ) ||
        here.furn( examp ) == furn_str_id( "f_water_mill_active" ) ) {
        p.add_msg_if_player( _( "You can't place more food while it's milling." ) );
        return;
    }
    // filter millable food
    inventory inv = p.crafting_inventory();
    inv.remove_items_with( []( const item & it ) {
        return it.rotten();
    } );
    std::vector<const item *> filtered = p.crafting_inventory().items_with( []( const item & it ) {
        return static_cast<bool>( it.type->milling_data );
    } );
    uilist smenu;
    smenu.text = _( "Load mill with what kind of product?" );
    // count and ask for item to be placed ...
    std::list<std::string> names;
    std::vector<const item *> entries;
    for( const item *millable_item : filtered ) {
        int count;
        if( millable_item->count_by_charges() ) {
            count = inv.charges_of( millable_item->typeId() );
        } else {
            count = inv.amount_of( millable_item->typeId() );
        }
        if( count != 0 ) {
            auto on_list = std::find( names.begin(), names.end(), item::nname( millable_item->typeId(), 1 ) );
            if( on_list == names.end() ) {
                smenu.addentry( item::nname( millable_item->typeId(), 1 ) );
                entries.push_back( millable_item );
            }
            names.push_back( item::nname( millable_item->typeId(), 1 ) );
            comps.push_back( item_comp( millable_item->typeId(), count ) );
        }
    }
    if( comps.empty() ) {
        p.add_msg_if_player( _( "You don't have any materials that can be milled." ) );
        return;
    }
    smenu.query();
    if( smenu.ret < 0 || static_cast<size_t>( smenu.ret ) >= entries.size() ) {
        add_msg( m_info, _( "Never mind." ) );
        return;
    }
    int count = 0;
    auto what = entries[smenu.ret];
    for( const auto &c : comps ) {
        if( c.type == what->typeId() ) {
            count = c.count;
        }
    }
    const int max_count_for_capacity = remaining_capacity / what->base_volume();
    const int max_count = std::min( count, max_count_for_capacity );
    // ... then ask how many to put it
    const std::string popupmsg = string_format( _( "Insert how many %s into the mill?" ),
                                 item::nname( what->typeId(), count ) );
    int amount = string_input_popup()
                 .title( popupmsg )
                 .width( 20 )
                 .text( std::to_string( max_count ) )
                 .only_digits( true )
                 .query_int();
    if( amount == 0 ) {
        add_msg( m_info, _( "Never mind." ) );
        return;
    } else if( amount > count ) {
        add_msg( m_info, _( "You don't have that many." ) );
        return;
    } else if( amount > max_count_for_capacity ) {
        add_msg( m_info, _( "You can't place that many." ) );
        return;
    }
    // reload comps with chosen items and quantity
    comps.clear();
    comps.push_back( item_comp( what->typeId(), amount ) );
    // select from where to get the items from and place them
    inv.form_from_map( g->u.pos(), PICKUP_RANGE, &g->u );
    inv.remove_items_with( []( const item & it ) {
        return it.rotten();
    } );
    comp_selection<item_comp> selected = p.select_item_component( comps, 1, inv, true,
                                         is_non_rotten_crafting_component );
    std::list<item> moved = p.consume_items( selected, 1, is_non_rotten_crafting_component );
    for( const item &m : moved ) {
        here.add_item( examp, m );
        p.mod_moves( -p.item_handling_cost( m ) );
        add_msg( m_info, pgettext( "item amount and name", "You carefully place %s %s in the mill." ),
                 amount, item::nname( m.typeId(), amount ) );
    }
    p.invalidate_crafting_inventory();
}
References _, map::add_item(), add_msg(), player::add_msg_if_player(), uilist::addentry(), visitable< T >::amount_of(), c, visitable< T >::charges_of(), player::consume_items(), detail::count(), Character::crafting_inventory(), detail::find(), inventory::form_from_map(), map::furn(), g, get_map(), Character::invalidate_crafting_inventory(), is_non_rotten_crafting_component(), Character::item_handling_cost(), visitable< T >::items_with(), m_info, itype::milling_data, Creature::mod_moves(), Name::names, item::nname(), string_input_popup::only_digits(), pgettext(), PICKUP_RANGE, uilist::query(), string_input_popup::query_int(), visitable< T >::remove_items_with(), uilist::ret, item::rotten(), player::select_item_component(), string_format(), string_input_popup::text(), uilist::text, string_input_popup::title(), to_string(), item::type, and string_input_popup::width().
Referenced by iexamine::quern_examine().
operator_present()
static Character & operator_present (Character & p, const tripoint & autodoc_loc, Character & null_patient) static
Definition at line 4758 of file iexamine.cpp.
{
    map &here = get_map();
    for( const auto &loc : here.points_in_radius( autodoc_loc, 1 ) ) {
        if( !here.has_flag_furn_or_vpart( flag_AUTODOC_COUCH, loc ) ) {
            if( p.pos() == loc ) {
                return p;
            }
            for( const npc *e : g->allies() ) {
                if( e->pos() == loc ) {
                    return  *g->critter_by_id<player>( e->getID() );
                }
            }
        }
    }
    return null_patient;
}
References flag_AUTODOC_COUCH(), g, get_map(), map::has_flag_furn_or_vpart(), map::points_in_radius(), and Character::pos().
Referenced by iexamine::autodoc().
pick_plant()
static void pick_plant (player & p, const tripoint & examp, const itype_id & itemType, ter_id new_ter, bool seeds = false) static
Survival increases number of plants harvested
Definition at line 3451 of file iexamine.cpp.
{
    map &here = get_map();
    bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                       get_option<std::string>( "AUTO_FORAGING" ) != "off";
    if( p.is_player() && !auto_forage &&
        !query_yn( _( "Harvest the %s?" ), here.tername( examp ) ) ) {
        iexamine::none( p, examp );
        return;
    }
    const int survival = p.get_skill_level( skill_survival );
    p.practice( skill_survival, 6 );
    int plantBase = rng( 2, 5 );
    ///\EFFECT_SURVIVAL increases number of plants harvested
    int plantCount = rng( plantBase, plantBase + survival / 2 );
    plantCount = std::min( plantCount, 12 );
    here.spawn_item( p.pos(), itemType, plantCount, 0, calendar::turn );
    if( seeds ) {
        // FIXME: shouldn't derive seed type by string manipulation
        here.spawn_item( p.pos(), itype_id( "seed_" + itemType.str() ), 1,
                         rng( plantCount / 4, plantCount / 2 ), calendar::turn );
    }
    here.ter_set( examp, new_ter );
}
References _, get_map(), Character::get_skill_level(), player::is_player(), iexamine::none(), Character::pos(), Character::practice(), query_yn(), rng(), skill_survival, map::spawn_item(), string_id< T >::str(), map::ter_set(), map::tername(), and calendar::turn.
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
player_on_couch()
static player & player_on_couch (player & p, const tripoint & autodoc_loc, player & null_patient, bool & adjacent_couch, tripoint & couch_pos) static
Definition at line 4738 of file iexamine.cpp.
{
    map &here = get_map();
    for( const auto &couch_loc : here.find_furnitures_or_vparts_with_flag_in_radius( autodoc_loc, 1,
            flag_AUTODOC_COUCH ) ) {
        adjacent_couch = true;
        couch_pos = couch_loc;
        if( p.pos() == couch_loc ) {
            return p;
        }
        for( const npc *e : g->allies() ) {
            if( e->pos() == couch_loc ) {
                return  *g->critter_by_id<player>( e->getID() );
            }
        }
    }
    return null_patient;
}
References map::find_furnitures_or_vparts_with_flag_in_radius(), flag_AUTODOC_COUCH(), g, get_map(), and Character::pos().
Referenced by iexamine::autodoc().
popup_player_or_npc()
template<typename ... Args> void popup_player_or_npc (player & p, const char * player_mes, const char * npc_mes, Args &&... args) inline
Definition at line 4860 of file iexamine.cpp.
{
    if( p.is_player() ) {
        popup( player_mes, std::forward<Args>( args )... );
    } else {
        popup( p.replace_with_npc_name( string_format( npc_mes, std::forward<Args>( args )... ) ) );
    }
}
References player::is_player(), popup(), Creature::replace_with_npc_name(), and string_format().
Referenced by iexamine::autodoc().
smoker_activate()
static void smoker_activate (player & p, const tripoint & examp) static
Definition at line 5361 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_smoker_type = here.furn( examp );
    furn_id next_smoker_type = f_null;
    const bool portable = here.furn( examp ) == furn_str_id( "f_metal_smoking_rack" ) ||
                          here.furn( examp ) == furn_str_id( "f_metal_smoking_rack_active" );
    if( cur_smoker_type == f_smoking_rack ) {
        next_smoker_type = f_smoking_rack_active;
    } else if( cur_smoker_type == f_metal_smoking_rack ) {
        next_smoker_type = f_metal_smoking_rack_active;
    } else {
        debugmsg( "Examined furniture has action smoker_activate, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    bool food_present = false;
    bool charcoal_present = false;
    map_stack items = here.i_at( examp );
    units::volume food_volume = 0_ml;
    item *charcoal = nullptr;
    for( item &it : items ) {
        if( it.has_flag( flag_SMOKED ) && !it.has_flag( flag_SMOKABLE ) ) {
            add_msg( _( "This rack already contains smoked food." ) );
            add_msg( _( "Remove it before firing the smoking rack again." ) );
            return;
        }
        if( it.has_flag( flag_SMOKABLE ) ) {
            food_present = true;
            food_volume += it.volume();
            continue;
        }
        if( it.typeId() == itype_charcoal ) {
            charcoal_present = true;
            charcoal = &it;
        }
        if( it.typeId() != itype_charcoal && !it.has_flag( flag_SMOKABLE ) ) {
            add_msg( m_bad, _( "This rack contains %s, which can't be smoked!" ), it.tname( 1,
                     false ) );
            add_msg( _( "You remove %s from the rack." ), it.tname() );
            here.add_item_or_charges( p.pos(), it );
            p.mod_moves( -p.item_handling_cost( it ) );
            here.i_rem( examp, &it );
            return;
        }
        if( it.has_flag( flag_SMOKED ) && it.has_flag( flag_SMOKABLE ) ) {
            add_msg( _( "This rack has some smoked food that might be dehydrated by smoking it again." ) );
        }
    }
    if( !food_present ) {
        add_msg( _( "This rack is empty.  Fill it with raw meat, fish or sausages and try again." ) );
        return;
    }
    if( !charcoal_present ) {
        add_msg( _( "There is no charcoal in the rack." ) );
        return;
    }
    if( portable && food_volume > sm_rack::MAX_FOOD_VOLUME_PORTABLE ) {
        add_msg( _( "This rack is overloaded with food, and it blocks the flow of smoke.  Remove some and try again." ) );
        add_msg( _( "You think that you can load about %s %s in it." ),
                 format_volume( sm_rack::MAX_FOOD_VOLUME_PORTABLE ), volume_units_long() );
        return;
    } else if( food_volume > sm_rack::MAX_FOOD_VOLUME ) {
        add_msg( _( "This rack is overloaded with food, and it blocks the flow of smoke.  Remove some and try again." ) );
        add_msg( _( "You think that you can load about %s %s in it." ),
                 format_volume( sm_rack::MAX_FOOD_VOLUME ), volume_units_long() );
        return;
    }
    int char_charges = get_charcoal_charges( food_volume );
    if( count_charges_in_list( charcoal->type, here.i_at( examp ) ) < char_charges ) {
        add_msg( _( "There is not enough charcoal in the rack to smoke this much food." ) );
        add_msg( _( "You need at least %1$s pieces of charcoal, and the smoking rack has %2$s inside." ),
                 char_charges, count_charges_in_list( charcoal->type, here.i_at( examp ) ) );
        return;
    }
    if( !p.has_charges( itype_fire, 1 ) ) {
        add_msg( _( "This smoking rack is ready to be fired, but you have no fire source." ) );
        return;
    } else if( !query_yn( _( "Fire the smoking rack?" ) ) ) {
        return;
    }
    p.use_charges( itype_fire, 1 );
    for( auto &it : here.i_at( examp ) ) {
        if( it.has_flag( flag_SMOKABLE ) ) {
            it.process_rot( examp );
            it.set_flag( flag_PROCESSING );
        }
    }
    here.furn_set( examp, next_smoker_type );
    if( charcoal->charges == char_charges ) {
        here.i_rem( examp, charcoal );
    } else {
        charcoal->charges -= char_charges;
    }
    item result( "fake_smoke_plume", calendar::turn );
    result.item_counter = to_turns<int>( 6_hours );
    result.activate();
    here.add_item( examp, result );
    add_msg( _( "You light a small fire under the rack and it starts to smoke." ) );
}
References _, map::add_item(), map::add_item_or_charges(), add_msg(), string_id< T >::c_str(), item::charges, count_charges_in_list(), debugmsg, f_metal_smoking_rack, f_metal_smoking_rack_active, f_null, f_smoking_rack, f_smoking_rack_active, flag_PROCESSING(), flag_SMOKABLE(), flag_SMOKED(), format_volume(), map::furn(), map::furn_set(), get_charcoal_charges(), get_map(), Character::has_charges(), map::i_at(), map::i_rem(), int_id< T >::id(), Character::item_handling_cost(), itype_charcoal, itype_fire, m_bad, sm_rack::MAX_FOOD_VOLUME, sm_rack::MAX_FOOD_VOLUME_PORTABLE, Creature::mod_moves(), Character::pos(), query_yn(), calendar::turn, item::type, Character::use_charges(), and volume_units_long().
Referenced by iexamine::smoker_options().
smoker_finalize()
static void smoker_finalize (player & , const tripoint & examp, const time_point & start_time) static
Definition at line 5511 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_smoker_type = here.furn( examp );
    furn_id next_smoker_type = f_null;
    if( cur_smoker_type == f_smoking_rack_active ) {
        next_smoker_type = f_smoking_rack;
    } else if( cur_smoker_type == f_metal_smoking_rack_active ) {
        next_smoker_type = f_metal_smoking_rack;
    } else {
        debugmsg( "Furniture executed action smoker_finalize, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    map_stack items = here.i_at( examp );
    if( items.empty() ) {
        here.furn_set( examp, next_smoker_type );
        return;
    }
    for( item &it : items ) {
        if( it.has_flag( flag_SMOKABLE ) && it.get_comestible() ) {
            if( it.get_comestible()->smoking_result.is_empty() ) {
                it.unset_flag( flag_PROCESSING );
            } else {
                it.mod_last_rot_check( 6_hours );
                item result( it.get_comestible()->smoking_result, start_time + 6_hours, it.charges );
                // Set flag to tell set_relative_rot() to calc from bday not now
                result.set_flag( flag_PROCESSING_RESULT );
                result.set_relative_rot( it.get_relative_rot() );
                result.unset_flag( flag_PROCESSING_RESULT );
                recipe rec;
                result.inherit_flags( it, rec );
                if( !result.has_flag( flag_NUTRIENT_OVERRIDE ) ) {
                    // If the item has "cooks_like" it will be replaced by that item as a component.
                    if( !it.get_comestible()->cooks_like.is_empty() ) {
                        // Set charges to 1 for stacking purposes.
                        it = item( it.get_comestible()->cooks_like, it.birthday(), 1 );
                    }
                    result.components.push_back( it );
                    // Smoking is always 1:1, so these must be equal for correct kcal/vitamin calculation.
                    result.recipe_charges = it.charges;
                    result.set_flag_recursive( flag_COOKED );
                }
                it = result;
            }
        }
    }
    here.furn_set( examp, next_smoker_type );
}
References string_id< T >::c_str(), debugmsg, item_stack::empty(), f_metal_smoking_rack, f_metal_smoking_rack_active, f_null, f_smoking_rack, f_smoking_rack_active, flag_COOKED(), flag_NUTRIENT_OVERRIDE(), flag_PROCESSING(), flag_PROCESSING_RESULT(), flag_SMOKABLE(), map::furn(), map::furn_set(), get_map(), map::i_at(), and int_id< T >::id().
Referenced by iexamine::on_smoke_out().
smoker_load_food()
static void smoker_load_food (player & p, const tripoint & examp, const units::volume & remaining_capacity) static
Definition at line 5567 of file iexamine.cpp.
{
    std::vector<item_comp> comps;
    map &here = get_map();
    if( here.furn( examp ) == furn_str_id( "f_smoking_rack_active" ) ||
        here.furn( examp ) == furn_str_id( "f_metal_smoking_rack_active" ) ) {
        p.add_msg_if_player( _( "You can't place more food while it's smoking." ) );
        return;
    }
    // filter SMOKABLE food
    inventory inv = p.crafting_inventory();
    inv.remove_items_with( []( const item & it ) {
        return it.rotten();
    } );
    std::vector<const item *> filtered = p.crafting_inventory().items_with( []( const item & it ) {
        return it.has_flag( flag_SMOKABLE );
    } );
    uilist smenu;
    smenu.text = _( "Load smoking rack with what kind of food?" );
    // count and ask for item to be placed ...
    std::list<std::string> names;
    std::vector<const item *> entries;
    for( const item *smokable_item : filtered ) {
        int count;
        if( smokable_item->count_by_charges() ) {
            count = inv.charges_of( smokable_item->typeId() );
        } else {
            count = inv.amount_of( smokable_item->typeId() );
        }
        if( count != 0 ) {
            auto on_list = std::find( names.begin(), names.end(), item::nname( smokable_item->typeId(), 1 ) );
            if( on_list == names.end() ) {
                smenu.addentry( item::nname( smokable_item->typeId(), 1 ) );
                entries.push_back( smokable_item );
            }
            names.push_back( item::nname( smokable_item->typeId(), 1 ) );
            comps.push_back( item_comp( smokable_item->typeId(), count ) );
        }
    }
    if( comps.empty() ) {
        p.add_msg_if_player( _( "You don't have any food that can be smoked." ) );
        return;
    }
    smenu.query();
    if( smenu.ret < 0 || static_cast<size_t>( smenu.ret ) >= entries.size() ) {
        add_msg( m_info, _( "Never mind." ) );
        return;
    }
    int count = 0;
    auto what = entries[smenu.ret];
    for( const auto &c : comps ) {
        if( c.type == what->typeId() ) {
            count = c.count;
        }
    }
    const int max_count_for_capacity = remaining_capacity / what->base_volume();
    const int max_count = std::min( count, max_count_for_capacity );
    // ... then ask how many to put it
    const std::string popupmsg = string_format( _( "Insert how many %s into the rack?" ),
                                 item::nname( what->typeId(), count ) );
    int amount = string_input_popup()
                 .title( popupmsg )
                 .width( 20 )
                 .text( std::to_string( max_count ) )
                 .only_digits( true )
                 .query_int();
    if( amount == 0 ) {
        add_msg( m_info, _( "Never mind." ) );
        return;
    } else if( amount > count ) {
        add_msg( m_info, _( "You don't have that many." ) );
        return;
    } else if( amount > max_count_for_capacity ) {
        add_msg( m_info, _( "You can't place that many." ) );
        return;
    }
    // reload comps with chosen items and quantity
    comps.clear();
    comps.push_back( item_comp( what->typeId(), amount ) );
    // select from where to get the items from and place them
    inv.form_from_map( g->u.pos(), PICKUP_RANGE, &g->u );
    inv.remove_items_with( []( const item & it ) {
        return it.rotten();
    } );
    comp_selection<item_comp> selected = p.select_item_component( comps, 1, inv, true,
                                         is_non_rotten_crafting_component );
    std::list<item> moved = p.consume_items( selected, 1, is_non_rotten_crafting_component );
    for( const item &m : moved ) {
        here.add_item( examp, m );
        p.mod_moves( -p.item_handling_cost( m ) );
        add_msg( m_info, _( "You carefully place %s %s in the rack." ), amount,
                 item::nname( m.typeId(), amount ) );
    }
    p.invalidate_crafting_inventory();
}
References _, map::add_item(), add_msg(), player::add_msg_if_player(), uilist::addentry(), visitable< T >::amount_of(), c, visitable< T >::charges_of(), player::consume_items(), detail::count(), Character::crafting_inventory(), detail::find(), flag_SMOKABLE(), inventory::form_from_map(), map::furn(), g, get_map(), item::has_flag(), Character::invalidate_crafting_inventory(), is_non_rotten_crafting_component(), Character::item_handling_cost(), visitable< T >::items_with(), m_info, Creature::mod_moves(), Name::names, item::nname(), string_input_popup::only_digits(), PICKUP_RANGE, uilist::query(), string_input_popup::query_int(), visitable< T >::remove_items_with(), uilist::ret, item::rotten(), player::select_item_component(), string_format(), string_input_popup::text(), uilist::text, string_input_popup::title(), to_string(), and string_input_popup::width().
Referenced by iexamine::smoker_options().
str_to_illiterate_str()
static std::string str_to_illiterate_str (std::string s) static
Definition at line 4311 of file iexamine.cpp.
{
    if( !g->u.has_trait( trait_ILLITERATE ) ) {
        return s;
    } else {
        for( auto &i : s ) {
            i = i + rng( 0, 5 ) - rng( 0, 5 );
            if( i < ' ' ) {
                // some control character, most likely not handled correctly be the print functions
                i = ' ';
            } else if( i == '%' ) {
                // avoid characters that trigger formatting in the various print functions
                i++;
            }
        }
        return s;
    }
}
References g, rng(), and trait_ILLITERATE.
Referenced by getGasDiscountName(), and iexamine::pay_gas().
try_start_hacking()
static bool try_start_hacking (player & p, const tripoint & examp) static
Definition at line 976 of file iexamine.cpp.
{
    if( p.has_trait( trait_ILLITERATE ) ) {
        add_msg( _( "You cannot read!" ) );
        return false;
    }
    const bool has_item = p.has_charges( itype_electrohack, 25 );
    const bool has_bionic = p.has_bionic( bio_fingerhack ) && p.get_power_level() >= 25_kJ;
    if( !has_item && !has_bionic ) {
        add_msg( _( "You don't have a hacking tool with enough charges!" ) );
        return false;
    }
    bool use_bionic = has_bionic;
    if( has_item && has_bionic ) {
        uilist menu;
        menu.settext( _( "Use which hacking tool?" ) );
        menu.addentry( 0, true, MENU_AUTOASSIGN, "%s", itype_electrohack->nname( 1 ) );
        menu.addentry( 1, true, MENU_AUTOASSIGN, "%s", bio_fingerhack->name );
        menu.query();
        switch( menu.ret ) {
            case 0:
                use_bionic = false;
                break;
            case 1:
                use_bionic = true;
                break;
            default:
                return false;
        }
    }
    if( use_bionic ) {
        p.mod_power_level( -25_kJ );
        p.assign_activity( player_activity( hacking_activity_actor(
                                                hacking_activity_actor::use_bionic {} ) ) );
    } else {
        p.use_charges( itype_electrohack, 25 );
        p.assign_activity( player_activity( hacking_activity_actor() ) );
    }
    p.activity.placement = examp;
    return true;
}
References _, Character::activity, add_msg(), uilist::addentry(), Character::assign_activity(), bio_fingerhack, Character::get_power_level(), Character::has_bionic(), Character::has_charges(), Character::has_trait(), itype_electrohack, MENU_AUTOASSIGN, Character::mod_power_level(), bionic_data::name, itype::nname(), player_activity::placement, uilist::query(), uilist::ret, uilist::settext(), trait_ILLITERATE, and Character::use_charges().
Referenced by iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::gunsafe_el(), and iexamine::pay_gas().
turnOnSelectedPump()
static void turnOnSelectedPump (const tripoint & p, int number) static
Definition at line 4421 of file iexamine.cpp.
{
    map &here = get_map();
    int k = 0;
    for( const tripoint &tmp : here.points_in_radius( p, 12 ) ) {
        const auto t = here.ter( tmp );
        if( t == ter_str_id( "t_gas_pump" ) || t == ter_str_id( "t_gas_pump_a" ) ) {
            if( number == k++ ) {
                here.ter_set( tmp, ter_str_id( "t_gas_pump_a" ) );
            } else {
                here.ter_set( tmp, ter_str_id( "t_gas_pump" ) );
            }
        }
    }
}
References get_map(), map::points_in_radius(), map::ter(), and map::ter_set().
Referenced by iexamine::pay_gas().
Variable Documentation
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::choose_option(), and anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money().
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by iexamine::trap().
ACT_CLEAR_RUBBLE
const activity_id ACT_CLEAR_RUBBLE("ACT_CLEAR_RUBBLE") ("ACT_CLEAR_RUBBLE") static
Referenced by iexamine::rubble().
ACT_CRACKING
const activity_id ACT_CRACKING("ACT_CRACKING") ("ACT_CRACKING") static
Referenced by iexamine::safe().
ACT_FORAGE
const activity_id ACT_FORAGE("ACT_FORAGE") ("ACT_FORAGE") static
Referenced by iexamine::shrub_wildveggies().
ACT_PLANT_SEED
const activity_id ACT_PLANT_SEED("ACT_PLANT_SEED") ("ACT_PLANT_SEED") static
Referenced by iexamine::plant_seed().
bio_ears
const bionic_id bio_ears("bio_ears") ("bio_ears") static
Referenced by iexamine::safe().
bio_fingerhack
const bionic_id bio_fingerhack("bio_fingerhack") ("bio_fingerhack") static
Referenced by iexamine::pay_gas(), and try_start_hacking().
bio_lighter
const bionic_id bio_lighter("bio_lighter") ("bio_lighter") static
Referenced by iexamine::fireplace().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by iexamine::autodoc().
bio_power_storage
const bionic_id bio_power_storage("bio_power_storage") ("bio_power_storage") static
Referenced by iexamine::autodoc().
bio_power_storage_mkII
const bionic_id bio_power_storage_mkII("bio_power_storage_mkII") ("bio_power_storage_mkII") static
Referenced by iexamine::autodoc().
effect_antibiotic
const efftype_id effect_antibiotic("antibiotic") ("antibiotic") static
Referenced by iexamine::autodoc().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by iexamine::autodoc().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by iexamine::autodoc().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by iexamine::autodoc().
effect_earphones
const efftype_id effect_earphones("earphones") ("earphones") static
Referenced by iexamine::safe().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by iexamine::autodoc().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by iexamine::autodoc().
effect_pblue
const efftype_id effect_pblue("pblue") ("pblue") static
Referenced by iexamine::autodoc().
effect_pkill2
const efftype_id effect_pkill2("pkill2") ("pkill2") static
Referenced by iexamine::flower_poppy().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by best_installer().
effect_strong_antibiotic
const efftype_id effect_strong_antibiotic("strong_antibiotic") ("strong_antibiotic") static
Referenced by iexamine::autodoc().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by iexamine::flower_marloss().
effect_weak_antibiotic
const efftype_id effect_weak_antibiotic("weak_antibiotic") ("weak_antibiotic") static
Referenced by iexamine::autodoc().
itype_2x4
const itype_id itype_2x4("2x4") ("2x4") static
Referenced by iexamine::pit().
itype_arm_splint
const itype_id itype_arm_splint("arm_splint") ("arm_splint") static
Referenced by iexamine::autodoc().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by iexamine::reload_furniture().
itype_bot_broken_cyborg
const itype_id itype_bot_broken_cyborg("bot_broken_cyborg") ("bot_broken_cyborg") static
Referenced by iexamine::autodoc(), and cyborg_on_couch().
itype_bot_prototype_cyborg
const itype_id itype_bot_prototype_cyborg("bot_prototype_cyborg") ("bot_prototype_cyborg") static
Referenced by cyborg_on_couch().
itype_cash_card
const itype_id itype_cash_card("cash_card") ("cash_card") static
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), iexamine::pay_gas(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), and iexamine::vending().
itype_charcoal
const itype_id itype_charcoal("charcoal") ("charcoal") static
Referenced by iexamine::kiln_empty(), iexamine::kiln_full(), smoker_activate(), and iexamine::smoker_options().
itype_chem_carbide
const itype_id itype_chem_carbide("chem_carbide") ("chem_carbide") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::arcfurnace_full().
itype_corpse
const itype_id itype_corpse("corpse") ("corpse") static
Referenced by iexamine::autodoc(), and cyborg_on_couch().
itype_electrohack
const itype_id itype_electrohack("electrohack") ("electrohack") static
Referenced by iexamine::pay_gas(), and try_start_hacking().
itype_fake_milling_item
const itype_id itype_fake_milling_item("fake_milling_item") ("fake_milling_item") static
Referenced by iexamine::quern_examine().
itype_fake_smoke_plume
const itype_id itype_fake_smoke_plume("fake_smoke_plume") ("fake_smoke_plume") static
Referenced by iexamine::smoker_options().
itype_fertilizer
const itype_id itype_fertilizer("fertilizer") ("fertilizer") static
Referenced by iexamine::fertilize_plant().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by iexamine::kiln_empty(), and smoker_activate().
itype_fungal_seeds
const itype_id itype_fungal_seeds("fungal_seeds") ("fungal_seeds") static
Referenced by iexamine::harvest_plant().
itype_grapnel
const itype_id itype_grapnel("grapnel") ("grapnel") static
Referenced by iexamine::ledge().
itype_hickory_root
const itype_id itype_hickory_root("hickory_root") ("hickory_root") static
Referenced by iexamine::tree_hickory().
itype_id_industrial
const itype_id itype_id_industrial("id_industrial") ("id_industrial") static
Referenced by iexamine::cardreader().
itype_id_military
const itype_id itype_id_military("id_military") ("id_military") static
Referenced by iexamine::cardreader().
itype_id_science
const itype_id itype_id_science("id_science") ("id_science") static
Referenced by iexamine::cardreader(), and iexamine::cardreader_robofac().
itype_leg_splint
const itype_id itype_leg_splint("leg_splint") ("leg_splint") static
Referenced by iexamine::autodoc().
itype_maple_sap
const itype_id itype_maple_sap("maple_sap") ("maple_sap") static
Referenced by maple_tree_sap_container(), and iexamine::tree_maple_tapped().
itype_marloss_berry
const itype_id itype_marloss_berry("marloss_berry") ("marloss_berry") static
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
itype_marloss_seed
const itype_id itype_marloss_seed("marloss_seed") ("marloss_seed") static
Referenced by iexamine::flower_marloss(), and iexamine::harvest_plant().
itype_mycus_fruit
const itype_id itype_mycus_fruit("mycus_fruit") ("mycus_fruit") static
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
itype_nail
const itype_id itype_nail("nail") ("nail") static
Referenced by iexamine::curtains().
itype_petrified_eye
const itype_id itype_petrified_eye("petrified_eye") ("petrified_eye") static
Referenced by iexamine::pedestal_temple(), and iexamine::pedestal_wyrm().
itype_sheet
const itype_id itype_sheet("sheet") ("sheet") static
Referenced by iexamine::curtains().
itype_stick
const itype_id itype_stick("stick") ("stick") static
Referenced by iexamine::curtains().
itype_string_36
const itype_id itype_string_36("string_36") ("string_36") static
Referenced by iexamine::curtains().
itype_tree_spile
const itype_id itype_tree_spile("tree_spile") ("tree_spile") static
Referenced by iexamine::tree_maple().
itype_unfinished_cac2
const itype_id itype_unfinished_cac2("unfinished_cac2") ("unfinished_cac2") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::arcfurnace_full().
itype_unfinished_charcoal
const itype_id itype_unfinished_charcoal("unfinished_charcoal") ("unfinished_charcoal") static
Referenced by iexamine::kiln_empty(), and iexamine::kiln_full().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by iexamine::arcfurnace_empty().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by iexamine::toilet().
milling_time
const time_duration milling_time = 6_hours static
Definition at line 247 of file iexamine.cpp.
Referenced by mill_activate(), iexamine::mill_finalize(), and iexamine::quern_examine().
mon_broken_cyborg
const mtype_id mon_broken_cyborg("mon_broken_cyborg") ("mon_broken_cyborg") static
Referenced by cyborg_on_couch().
mon_dark_wyrm
const mtype_id mon_dark_wyrm("mon_dark_wyrm") ("mon_dark_wyrm") static
Referenced by iexamine::pedestal_wyrm().
mon_fungal_blossom
const mtype_id mon_fungal_blossom("mon_fungal_blossom") ("mon_fungal_blossom") static
Referenced by iexamine::harvest_plant().
mon_prototype_cyborg
const mtype_id mon_prototype_cyborg("mon_prototype_cyborg") ("mon_prototype_cyborg") static
Referenced by cyborg_on_couch().
mon_spider_cellar_giant_s
const mtype_id mon_spider_cellar_giant_s("mon_spider_cellar_giant_s") ("mon_spider_cellar_giant_s") static
Referenced by iexamine::egg_sackcs().
mon_spider_web_s
const mtype_id mon_spider_web_s("mon_spider_web_s") ("mon_spider_web_s") static
Referenced by iexamine::egg_sackws().
mon_spider_widow_giant_s
const mtype_id mon_spider_widow_giant_s("mon_spider_widow_giant_s") ("mon_spider_widow_giant_s") static
Referenced by iexamine::egg_sackbw().
qual_ANESTHESIA
const quality_id qual_ANESTHESIA("ANESTHESIA") ("ANESTHESIA") static
Referenced by iexamine::autodoc().
qual_DIG
const quality_id qual_DIG("DIG") ("DIG") static
Referenced by iexamine::flower_dahlia(), iexamine::rubble(), and iexamine::tree_hickory().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by best_installer().
skill_cooking
const skill_id skill_cooking("cooking") ("cooking") static
Referenced by iexamine::fvat_full().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by best_installer().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::kiln_empty().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by best_installer().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by iexamine::safe().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by harvest_common(), iexamine::harvest_plant(), pick_plant(), iexamine::practice_survival_while_foraging(), iexamine::shrub_wildveggies(), and iexamine::tree_hickory().
t_dimensional_portal
const ter_str_id t_dimensional_portal("t_dimensional_portal") ("t_dimensional_portal") static
Referenced by iexamine::dimensional_portal().
t_web_bridge
const ter_str_id t_web_bridge("t_web_bridge") ("t_web_bridge") static
Referenced by iexamine::ledge().
tr_unfinished_construction
const trap_str_id tr_unfinished_construction("tr_unfinished_construction") ("tr_unfinished_construction") static
Referenced by iexamine::trap().
trait_AMORPHOUS
const trait_id trait_AMORPHOUS("AMORPHOUS") ("AMORPHOUS") static
Referenced by iexamine::bars().
trait_ARACHNID_ARMS_OK
const trait_id trait_ARACHNID_ARMS_OK("ARACHNID_ARMS_OK") ("ARACHNID_ARMS_OK") static
Referenced by iexamine::chainfence().
trait_BADKNEES
const trait_id trait_BADKNEES("BADKNEES") ("BADKNEES") static
Referenced by iexamine::chainfence().
trait_BEAK_HUM
const trait_id trait_BEAK_HUM("BEAK_HUM") ("BEAK_HUM") static
Referenced by can_drink_nectar().
trait_BURROW
const trait_id trait_BURROW("BURROW") ("BURROW") static
Referenced by iexamine::flower_dahlia(), and iexamine::rubble().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by iexamine::trap().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by iexamine::pay_gas(), iexamine::sign(), str_to_illiterate_str(), and try_start_hacking().
trait_INSECT_ARMS_OK
const trait_id trait_INSECT_ARMS_OK("INSECT_ARMS_OK") ("INSECT_ARMS_OK") static
Referenced by iexamine::chainfence().
trait_M_DEFENDER
const trait_id trait_M_DEFENDER("M_DEFENDER") ("M_DEFENDER") static
Referenced by iexamine::harvest_plant().
trait_M_DEPENDENT
const trait_id trait_M_DEPENDENT("M_DEPENDENT") ("M_DEPENDENT") static
Referenced by iexamine::harvest_plant(), and iexamine::tree_marloss().
trait_M_FERTILE
const trait_id trait_M_FERTILE("M_FERTILE") ("M_FERTILE") static
Referenced by iexamine::harvest_plant().
trait_M_SPORES
const trait_id trait_M_SPORES("M_SPORES") ("M_SPORES") static
Referenced by iexamine::harvest_plant().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by iexamine::autodoc().
trait_PARKOUR
const trait_id trait_PARKOUR("PARKOUR") ("PARKOUR") static
Referenced by iexamine::chainfence().
trait_PROBOSCIS
const trait_id trait_PROBOSCIS("PROBOSCIS") ("PROBOSCIS") static
Referenced by can_drink_nectar().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by iexamine::harvest_plant(), iexamine::shrub_marloss(), and iexamine::tree_marloss().
trait_WEB_BRDIGE
const trait_id trait_WEB_BRDIGE("WEB_BRIDGE") ("WEB_BRIDGE") static
Referenced by iexamine::ledge().