Cataclysm BN: src/ime.cpp File Reference
ime.cpp File Reference
#include "ime.h"
Functions
static bool ime_enabled ()
void enable_ime ()
Enable or disable IME for text/keyboard input.
void disable_ime ()
Function Documentation
disable_ime()
void disable_ime ()
Definition at line 127 of file ime.cpp.
{
#if defined(__ANDROID__)
    // the original android code did nothing, so don't change it
#elif defined(_WIN32)
    imm.disable_ime();
#endif
    // TODO: other platforms?
}
Referenced by overmap_ui::create_note(), ime_sentry::ime_sentry(), Messages::dialog::input(), main_menu::opening_screen(), and ime_sentry::~ime_sentry().
enable_ime()
void enable_ime ()
Enable or disable IME for text/keyboard input.
Definition at line 115 of file ime.cpp.
{
#if defined(__ANDROID__)
    if( get_option<bool>( "ANDROID_AUTO_KEYBOARD" ) ) {
        SDL_StartTextInput();
    }
#elif defined(_WIN32)
    imm.enable_ime();
#endif
    // TODO: other platforms?
}
Referenced by ime_sentry::ime_sentry(), Messages::dialog::input(), and ime_sentry::~ime_sentry().
ime_enabled()
static bool ime_enabled () static
Definition at line 104 of file ime.cpp.
{
#if defined(__ANDROID__)
    return false; // always call disable_ime() (i.e. do nothing) on return
#elif defined(_WIN32)
    return imm.ime_enabled();
#endif
    return false;
    // TODO: other platforms?
}