Cataclysm BN: src/inventory_ui.cpp File Reference
inventory_ui.cpp File Reference
#include "inventory_ui.h"
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "colony.h"
#include "debug.h"
#include "game.h"
#include "ime.h"
#include "inventory.h"
#include "item.h"
#include "item_category.h"
#include "item_search.h"
#include "item_stack.h"
#include "line.h"
#include "map.h"
#include "map_selector.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "player.h"
#include "point.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "units_utility.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "visitable.h"
#include "vpart_position.h"
#include <algorithm>
#include <iterator>
#include <limits>
#include <map>
#include <numeric>
#include <set>
#include <string>
#include <type_traits>
#include <vector>
Classes
struct navigation_mode_data
struct inventory_input
class selection_column_preset
Functions
static std::vector< std::list< item * > > restack_items (const std::list< item >::const_iterator &from, const std::list< item >::const_iterator &to, bool check_components=false)
static std::vector< std::list< item * > > restack_items (const item_stack::const_iterator &from, const item_stack::const_iterator &to, bool check_components=false)
inventory_selector::stat display_stat (const std::string &caption, int cur_value, int max_value, const std::function< std::string(int)> &disp_func)
Variables
static const size_t max_win_snap_distance = 4
The maximum distance from the screen edge, to snap a window to it.
static const int min_cell_gap = 2
The minimal gap between two cells.
static const int normal_cell_gap = 4
The gap between two cells when screen space is limited.
static const int min_denial_gap = 2
The minimal gap between the first cell and denial.
static const int min_column_gap = 2
The minimal gap between two columns.
static const int normal_column_gap = 8
The gap between two columns when there's enough space, but they are not centered.
static const double min_ratio_to_center = 0.85
The minimal occupancy ratio to align columns to the center.
static const std::set< std::string > ordered_categories = {{ "ITEMS_WORN" }}
These categories should keep their original order and can't be re-sorted by inventory presets.
constexpr int max_chosen_count = std::numeric_limits<int>::max()
static const selection_column_preset selection_preset {}
Function Documentation
display_stat()
inventory_selector::stat display_stat (const std::string & caption, int cur_value, int max_value, const std::function< std::string(int)> & disp_func)
Definition at line 1446 of file inventory_ui.cpp.
{
    const nc_color color = cur_value > max_value ? c_red : c_light_gray;
    return {{
            caption,
            colorize( disp_func( cur_value ), color ), "/",
            colorize( disp_func( max_value ), c_light_gray )
        }};
}
References c_light_gray, c_red, color(), colorize(), and detail::max_value().
Referenced by draw_stats_tab(), inventory_selector::get_weight_and_volume_stats(), and game_menus::inv::multiwash().
restack_items() [1/2]
static std::vector< std::list< item * > > restack_items (const item_stack::const_iterator & from, const item_stack::const_iterator & to, bool check_components = false) static
Definition at line 1078 of file inventory_ui.cpp.
{
    std::vector<std::list<item *>> res;
    for( auto it = from; it != to; ++it ) {
        auto match = std::find_if( res.begin(), res.end(),
        [ &it, check_components ]( const std::list<item *> &e ) {
            return it->display_stacked_with( *const_cast<item *>( e.back() ), check_components );
        } );
        if( match != res.end() ) {
            match->push_back( const_cast<item *>( &*it ) );
        } else {
            res.emplace_back( 1, const_cast<item *>( &*it ) );
        }
    }
    return res;
}
restack_items() [2/2]
static std::vector< std::list< item * > > restack_items (const std::list< item >::const_iterator & from, const std::list< item >::const_iterator & to, bool check_components = false) static
Definition at line 1056 of file inventory_ui.cpp.
{
    std::vector<std::list<item *>> res;
    for( auto it = from; it != to; ++it ) {
        auto match = std::find_if( res.begin(), res.end(),
        [ &it, check_components ]( const std::list<item *> &e ) {
            return it->display_stacked_with( *const_cast<item *>( e.back() ), check_components );
        } );
        if( match != res.end() ) {
            match->push_back( const_cast<item *>( &*it ) );
        } else {
            res.emplace_back( 1, const_cast<item *>( &*it ) );
        }
    }
    return res;
}
Referenced by inventory_selector::add_character_items(), inventory_selector::add_map_items(), and inventory_selector::add_vehicle_items().
Variable Documentation
max_chosen_count
constexpr int max_chosen_count = std::numeric_limits<int>::max() constexpr
Definition at line 71 of file inventory_ui.cpp.
Referenced by inventory_iuse_selector::execute(), inventory_drop_selector::execute(), inventory_drop_selector::process_selected(), inventory_iuse_selector::set_chosen_count(), and inventory_drop_selector::set_chosen_count().
max_win_snap_distance
const size_t max_win_snap_distance = 4 static
The maximum distance from the screen edge, to snap a window to it.
Definition at line 51 of file inventory_ui.cpp.
Referenced by inventory_selector::prepare_layout().
min_cell_gap
const int min_cell_gap = 2 static
The minimal gap between two cells.
Definition at line 53 of file inventory_ui.cpp.
Referenced by inventory_column::draw(), and inventory_column::set_width().
min_column_gap
const int min_column_gap = 2 static
The minimal gap between two columns.
Definition at line 59 of file inventory_ui.cpp.
Referenced by inventory_selector::get_columns_occupancy_ratio().
min_denial_gap
const int min_denial_gap = 2 static
The minimal gap between the first cell and denial.
Definition at line 57 of file inventory_ui.cpp.
Referenced by inventory_column::draw(), and inventory_column::expand_to_fit().
min_ratio_to_center
const double min_ratio_to_center = 0.85 static
The minimal occupancy ratio to align columns to the center.
See also
inventory_selector::get_columens_occupancy_ratio()
Definition at line 66 of file inventory_ui.cpp.
Referenced by inventory_selector::are_columns_centered().
normal_cell_gap
const int normal_cell_gap = 4 static
The gap between two cells when screen space is limited.
Definition at line 55 of file inventory_ui.cpp.
Referenced by inventory_column::expand_to_fit().
normal_column_gap
const int normal_column_gap = 8 static
The gap between two columns when there's enough space, but they are not centered.
Definition at line 61 of file inventory_ui.cpp.
Referenced by inventory_selector::draw_columns(), and inventory_selector::get_layout_width().
ordered_categories
const std::set<std::string> ordered_categories = {{ "ITEMS_WORN" }} static
These categories should keep their original order and can't be re-sorted by inventory presets.
Definition at line 69 of file inventory_ui.cpp.
Referenced by inventory_column::prepare_paging().
selection_preset
const selection_column_preset selection_preset {} static
Definition at line 133 of file inventory_ui.cpp.