Cataclysm BN: src/inventory_ui.h File Reference
inventory_ui.h File Reference
#include <cassert>
#include <climits>
#include <cstddef>
#include <functional>
#include <limits>
#include <memory>
#include <array>
#include <list>
#include <map>
#include <string>
#include <utility>
#include <vector>
#include "color.h"
#include "cursesdef.h"
#include "input.h"
#include "item_handling_util.h"
#include "item_location.h"
#include "memory_fast.h"
#include "pimpl.h"
#include "units.h"
Classes
class inventory_entry
class inventory_selector_preset
class inventory_selector_preset::cell_t
class inventory_column
struct inventory_column::entry_cell_cache_t
struct inventory_column::cell_t
class selection_column
class inventory_selector
class inventory_pick_selector
class inventory_multiselector
class inventory_compare_selector
class inventory_iuse_selector
class inventory_drop_selector
Macros
#define CATA_SRC_INVENTORY_UI_H
Typedefs
using excluded_stack = std::pair< const item *, int >
using excluded_stacks = std::map< const item *, int >
Enumerations
enum class navigation_mode : int { ITEM = 0 , CATEGORY }
enum class scroll_direction : int { FORWARD = 1 , BACKWARD = -1 }
Functions
inventory_selector::stat display_stat (const std::string &caption, int cur_value, int max_value, const std::function< std::string(int)> &disp_func)
Variables
const inventory_selector_preset default_preset
Macro Definition Documentation
CATA_SRC_INVENTORY_UI_H
#define CATA_SRC_INVENTORY_UI_H
Definition at line 3 of file inventory_ui.h.
Typedef Documentation
excluded_stack
using excluded_stack = std::pair<const item *, int>
Definition at line 35 of file inventory_ui.h.
excluded_stacks
using excluded_stacks = std::map<const item *, int>
Definition at line 36 of file inventory_ui.h.
Enumeration Type Documentation
navigation_mode
enum class navigation_mode : int strong
Enumerator
ITEM
CATEGORY
Definition at line 38 of file inventory_ui.h.
                           : int {
    ITEM = 0,
    CATEGORY
};
scroll_direction
enum class scroll_direction : int strong
Enumerator
FORWARD
BACKWARD
Definition at line 43 of file inventory_ui.h.
                            : int {
    FORWARD = 1,
    BACKWARD = -1
};
Function Documentation
display_stat()
inventory_selector::stat display_stat (const std::string & caption, int cur_value, int max_value, const std::function< std::string(int)> & disp_func)
Definition at line 1446 of file inventory_ui.cpp.
{
    const nc_color color = cur_value > max_value ? c_red : c_light_gray;
    return {{
            caption,
            colorize( disp_func( cur_value ), color ), "/",
            colorize( disp_func( max_value ), c_light_gray )
        }};
}
References c_light_gray, c_red, color(), colorize(), and detail::max_value().
Referenced by draw_stats_tab(), inventory_selector::get_weight_and_volume_stats(), and game_menus::inv::multiwash().
Variable Documentation
default_preset
const inventory_selector_preset default_preset
Definition at line 217 of file inventory_ui.h.