Cataclysm BN: src/item.cpp File Reference
item.cpp File Reference
#include "item.h"
#include <algorithm>
#include <array>
#include <cassert>
#include <cctype>
#include <cmath>
#include <cstdlib>
#include <iomanip>
#include <iterator>
#include <limits>
#include <locale>
#include <memory>
#include <set>
#include <sstream>
#include <tuple>
#include <unordered_set>
#include "advanced_inv.h"
#include "ammo.h"
#include "ascii_art.h"
#include "avatar.h"
#include "bionics.h"
#include "bodypart.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "character_encumbrance.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "character_stat.h"
#include "clothing_mod.h"
#include "clzones.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "craft_command.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "drop_token.h"
#include "effect.h"
#include "enums.h"
#include "explosion.h"
#include "faction.h"
#include "fault.h"
#include "field_type.h"
#include "fire.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "gun_mode.h"
#include "iexamine.h"
#include "int_id.h"
#include "inventory.h"
#include "item_category.h"
#include "item_factory.h"
#include "item_group.h"
#include "iteminfo_query.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "martialarts.h"
#include "material.h"
#include "messages.h"
#include "mod_manager.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player.h"
#include "pldata.h"
#include "point.h"
#include "projectile.h"
#include "ranged.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "relic.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id_utils.h"
#include "string_utils.h"
#include "text_snippets.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
Classes
struct item_internal::scoped_goes_bad_cache
struct dps_comp_data
Namespaces
namespace item_internal
Typedefs
using npc_class_id = string_id< npc_class >
Functions
static const std::string GUN_MODE_VAR_NAME ("item::mode")
static const std::string CLOTHING_MOD_VAR_PREFIX ("clothing_mod_")
static const std::string trait_flag_CANNIBAL ("CANNIBAL")
static const std::string flag_ALWAYS_TWOHAND ("ALWAYS_TWOHAND")
static const std::string flag_AURA ("AURA")
static const std::string flag_BELTED ("BELTED")
static const std::string flag_BIPOD ("BIPOD")
static const std::string flag_BYPRODUCT ("BYPRODUCT")
static const std::string flag_CABLE_SPOOL ("CABLE_SPOOL")
static const std::string flag_CANNIBALISM ("CANNIBALISM")
static const std::string flag_CBM_SCANNED ("CBM_SCANNED")
static const std::string flag_CHARGEDIM ("CHARGEDIM")
static const std::string flag_COLLAPSIBLE_STOCK ("COLLAPSIBLE_STOCK")
static const std::string flag_CONDUCTIVE ("CONDUCTIVE")
static const std::string flag_CONSUMABLE ("CONSUMABLE")
static const std::string flag_CORPSE ("CORPSE")
static const std::string flag_CROSSBOW ("CROSSBOW")
static const std::string flag_DANGEROUS ("DANGEROUS")
static const std::string flag_DEEP_WATER ("DEEP_WATER")
static const std::string flag_DIAMOND ("DIAMOND")
static const std::string flag_DISABLE_SIGHTS ("DISABLE_SIGHTS")
static const std::string flag_ETHEREAL_ITEM ("ETHEREAL_ITEM")
static const std::string flag_FAKE_MILL ("FAKE_MILL")
static const std::string flag_FAKE_SMOKE ("FAKE_SMOKE")
static const std::string flag_FIELD_DRESS ("FIELD_DRESS")
static const std::string flag_FIELD_DRESS_FAILED ("FIELD_DRESS_FAILED")
static const std::string flag_FILTHY ("FILTHY")
static const std::string flag_FIRE_100 ("FIRE_100")
static const std::string flag_FIRE_20 ("FIRE_20")
static const std::string flag_FIRE_50 ("FIRE_50")
static const std::string flag_FIRE_TWOHAND ("FIRE_TWOHAND")
static const std::string flag_FIT ("FIT")
static const std::string flag_FLAMMABLE ("FLAMMABLE")
static const std::string flag_FLAMMABLE_ASH ("FLAMMABLE_ASH")
static const std::string flag_GIBBED ("GIBBED")
static const std::string flag_HEATS_FOOD ("HEATS_FOOD")
static const std::string flag_HELMET_COMPAT ("HELMET_COMPAT")
static const std::string flag_HIDDEN_HALLU ("HIDDEN_HALLU")
static const std::string flag_HIDDEN_POISON ("HIDDEN_POISON")
static const std::string flag_IRREMOVABLE ("IRREMOVABLE")
static const std::string flag_IS_ARMOR ("IS_ARMOR")
static const std::string flag_IS_PET_ARMOR ("IS_PET_ARMOR")
static const std::string flag_IS_UPS ("IS_UPS")
static const std::string flag_LEAK_ALWAYS ("LEAK_ALWAYS")
static const std::string flag_LEAK_DAM ("LEAK_DAM")
static const std::string flag_LIQUID ("LIQUID")
static const std::string flag_LIQUIDCONT ("LIQUIDCONT")
static const std::string flag_LITCIG ("LITCIG")
static const std::string flag_MAG_BELT ("MAG_BELT")
static const std::string flag_MAG_DESTROY ("MAG_DESTROY")
static const std::string flag_MAG_EJECT ("MAG_EJECT")
static const std::string flag_NANOFAB_TEMPLATE ("NANOFAB_TEMPLATE")
static const std::string flag_NEEDS_UNFOLD ("NEEDS_UNFOLD")
static const std::string flag_NEVER_JAMS ("NEVER_JAMS")
static const std::string flag_NONCONDUCTIVE ("NONCONDUCTIVE")
static const std::string flag_NO_DISPLAY ("NO_DISPLAY")
static const std::string flag_NO_DROP ("NO_DROP")
static const std::string flag_NO_PARASITES ("NO_PARASITES")
static const std::string flag_NO_RELOAD ("NO_RELOAD")
static const std::string flag_NO_REPAIR ("NO_REPAIR")
static const std::string flag_NO_SALVAGE ("NO_SALVAGE")
static const std::string flag_NO_UNLOAD ("NO_UNLOAD")
static const std::string flag_OUTER ("OUTER")
static const std::string flag_OVERSIZE ("OVERSIZE")
static const std::string flag_PERSONAL ("PERSONAL")
static const std::string flag_POWERARMOR_EXO ("POWERARMOR_EXO")
static const std::string flag_POWERARMOR_EXTERNAL ("POWERARMOR_EXTERNAL")
static const std::string flag_POWERARMOR_MOD ("POWERARMOR_MOD")
static const std::string flag_PROCESSING ("PROCESSING")
static const std::string flag_PROCESSING_RESULT ("PROCESSING_RESULT")
static const std::string flag_PULPED ("PULPED")
static const std::string flag_PUMP_ACTION ("PUMP_ACTION")
static const std::string flag_PUMP_RAIL_COMPATIBLE ("PUMP_RAIL_COMPATIBLE")
static const std::string flag_QUARTERED ("QUARTERED")
static const std::string flag_RADIOACTIVE ("RADIOACTIVE")
static const std::string flag_RADIOSIGNAL_1 ("RADIOSIGNAL_1")
static const std::string flag_RADIOSIGNAL_2 ("RADIOSIGNAL_2")
static const std::string flag_RADIOSIGNAL_3 ("RADIOSIGNAL_3")
static const std::string flag_RADIO_ACTIVATION ("RADIO_ACTIVATION")
static const std::string flag_RADIO_INVOKE_PROC ("RADIO_INVOKE_PROC")
static const std::string flag_RADIO_MOD ("RADIO_MOD")
static const std::string flag_RAIN_PROTECT ("RAIN_PROTECT")
static const std::string flag_REACH3 ("REACH3")
static const std::string flag_REACH_ATTACK ("REACH_ATTACK")
static const std::string flag_RECHARGE ("RECHARGE")
static const std::string flag_REDUCED_BASHING ("REDUCED_BASHING")
static const std::string flag_REDUCED_WEIGHT ("REDUCED_WEIGHT")
static const std::string flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT")
static const std::string flag_RELOAD_EJECT ("RELOAD_EJECT")
static const std::string flag_RELOAD_ONE ("RELOAD_ONE")
static const std::string flag_REVIVE_SPECIAL ("REVIVE_SPECIAL")
static const std::string flag_SILENT ("SILENT")
static const std::string flag_SKINNED ("SKINNED")
static const std::string flag_SKINTIGHT ("SKINTIGHT")
static const std::string flag_SLOW_WIELD ("SLOW_WIELD")
static const std::string flag_SPEEDLOADER ("SPEEDLOADER")
static const std::string flag_SPLINT ("SPLINT")
static const std::string flag_STR_DRAW ("STR_DRAW")
static const std::string flag_TOBACCO ("TOBACCO")
static const std::string flag_UNARMED_WEAPON ("UNARMED_WEAPON")
static const std::string flag_UNDERSIZE ("UNDERSIZE")
static const std::string flag_USES_BIONIC_POWER ("USES_BIONIC_POWER")
static const std::string flag_USE_UPS ("USE_UPS")
static const std::string flag_NAT_UPS ("NAT_UPS")
static const std::string flag_VARSIZE ("VARSIZE")
static const std::string flag_VEHICLE ("VEHICLE")
static const std::string flag_WAIST ("WAIST")
static const std::string flag_WATERPROOF_GUN ("WATERPROOF_GUN")
static const std::string flag_WATER_EXTINGUISH ("WATER_EXTINGUISH")
static const std::string flag_WET ("WET")
static const std::string flag_WIND_EXTINGUISH ("WIND_EXTINGUISH")
static const std::string has_thievery_witness ("has_thievery_witness")
std::string rad_badge_color (const int rad)
static const itype * nullitem ()
item & null_item_reference ()
Returns a reference to a null item (see item::is_null).
bool item_internal::goes_bad_cache_fetch ()
void item_internal::goes_bad_cache_set (const item *i)
void item_internal::goes_bad_cache_unset ()
bool item_internal::goes_bad_cache_is_for (const item *i)
static const item * get_most_rotten_component (const item &craft)
static int get_ranged_pierce (const common_ranged_data &ranged)
static float get_ranged_armor_mult (const common_ranged_data &ranged)
static std::string get_freshness_description (const item &food_item)
static int get_base_env_resist (const item &it)
static void insert_separation_line (std::vector< iteminfo > &info)
static int calc_hourly_rotpoints_at_temp (const int temp)
Food decay calculation.
static std::vector< int > calc_rot_array (const size_t cap)
Initialize the rot table.
int get_hourly_rotpoints_at_temp (const int temp)
Get the hourly rot for a given temperature from the precomputed table.
static int temperature_flag_to_highest_temperature (temperature_flag temperature)
template<typename Item >
static Item * get_food_impl (Item *it)
bool item_ptr_compare_by_charges (const item *left, const item *right)
bool item_compare_by_charges (const item &left, const item &right)
static const std::string USED_BY_IDS ("USED_BY_IDS")
static units::temperature clip_by_temperature_flag (units::temperature temperature, temperature_flag flag)
Variables
static const ammo_effect_str_id ammo_effect_BLACKPOWDER ("BLACKPOWDER")
static const ammo_effect_str_id ammo_effect_INCENDIARY ("INCENDIARY")
static const ammo_effect_str_id ammo_effect_NEVER_MISFIRES ("NEVER_MISFIRES")
static const ammo_effect_str_id ammo_effect_RECYCLED ("RECYCLED")
static const ammotype ammo_battery ("battery")
static const ammotype ammo_plutonium ("plutonium")
static const item_category_id itemcat_drugs ("drugs")
static const item_category_id itemcat_food ("food")
static const item_category_id itemcat_maps ("maps")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_shakes ("shakes")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_weed_high ("weed_high")
static const fault_id fault_gun_blackpowder ("fault_gun_blackpowder")
static const fault_id fault_bionic_nonsterile ("fault_bionic_nonsterile")
static const gun_mode_id gun_mode_REACH ("REACH")
static const itype_id itype_barrel_small ("barrel_small")
static const itype_id itype_blood ("blood")
static const itype_id itype_brass_catcher ("brass_catcher")
static const itype_id itype_cig_butt ("cig_butt")
static const itype_id itype_cig_lit ("cig_lit")
static const itype_id itype_cigar_butt ("cigar_butt")
static const itype_id itype_cigar_lit ("cigar_lit")
static const itype_id itype_hand_crossbow ("hand_crossbow")
static const itype_id itype_joint_roach ("joint_roach")
static const itype_id itype_plut_cell ("plut_cell")
static const itype_id itype_rad_badge ("rad_badge")
static const itype_id itype_tuned_mechanism ("tuned_mechanism")
static const itype_id itype_stock_small ("stock_small")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_bio_armor ("bio_armor")
static const itype_id itype_waterproof_gunmod ("waterproof_gunmod")
static const itype_id itype_water ("water")
static const itype_id itype_water_acid ("water_acid")
static const itype_id itype_water_acid_weak ("water_acid_weak")
static const skill_id skill_survival ("survival")
static const skill_id skill_unarmed ("unarmed")
static const skill_id skill_weapon ("weapon")
static const quality_id qual_JACK ("JACK")
static const quality_id qual_LIFT ("LIFT")
static const species_id ROBOT ("ROBOT")
static const bionic_id bio_digestion ("bio_digestion")
static const trait_id trait_CARNIVORE ("CARNIVORE")
static const trait_id trait_LIGHTWEIGHT ("LIGHTWEIGHT")
static const trait_id trait_SAPROVORE ("SAPROVORE")
static const trait_id trait_SQUEAMISH ("SQUEAMISH")
static const trait_id trait_TOLERANCE ("TOLERANCE")
static const trait_id trait_WOOLALLERGY ("WOOLALLERGY")
static const flag_str_id flag_MELEE_GUNMOD ("MELEE_GUNMOD")
static const activity_id ACT_PICKUP ("ACT_PICKUP")
static const matec_id rapid_strike ("RAPID")
light_emission nolight = {0, 0, 0}
bool item_internal::goes_bad_temp_cache = false
const item * item_internal::goes_bad_temp_cache_for = nullptr
static const double hits_by_accuracy [41]
static const std::vector< std::pair< translation, dps_comp_data > > dps_comp_monsters
Typedef Documentation
npc_class_id
using npc_class_id = string_id<npc_class>
Definition at line 287 of file item.cpp.
Function Documentation
calc_hourly_rotpoints_at_temp()
static int calc_hourly_rotpoints_at_temp (const int temp) static
Food decay calculation.
Calculate how much food rots per hour, based on 10 = 1 minute of decay @ 65 F. IRL this tends to double every 10c a few degrees above freezing, but past a certain point the rate decreases until even extremophiles find it too hot. Here we just stop further acceleration at 105 F. This should only need to run once when the game starts.
See also
calc_rot_array
rot_chart
Definition at line 5596 of file item.cpp.
{
    // default temp = 65, so generic->rotten() assumes 600 decay points per hour
    const int dropoff = 38;     // ditch our fancy equation and do a linear approach to 0 rot at 31f
    const int cutoff = 105;     // stop torturing the player at this temperature, which is
    const int cutoffrot = 21240; // ..almost 6 times the base rate. bacteria hate the heat too
    const int dsteps = dropoff - units::to_fahrenheit( temperatures::freezing );
    const int dstep = ( 215.46 * std::pow( 2.0, static_cast<float>( dropoff ) / 16.0 ) / dsteps );
    if( temp < units::to_fahrenheit( temperatures::freezing ) ) {
        return 0;
    } else if( temp > cutoff ) {
        return cutoffrot;
    } else if( temp < dropoff ) {
        return ( temp - units::to_fahrenheit( temperatures::freezing ) ) * dstep;
    } else {
        return std::lround( 215.46 * std::pow( 2.0, static_cast<float>( temp ) / 16.0 ) );
    }
}
References temperatures::freezing, and units::to_fahrenheit().
Referenced by calc_rot_array().
calc_rot_array()
static std::vector< int > calc_rot_array (const size_t cap) static
Initialize the rot table.
See also
rot_chart
Definition at line 5621 of file item.cpp.
{
    std::vector<int> ret;
    ret.reserve( cap );
    for( size_t i = 0; i < cap; ++i ) {
        ret.push_back( calc_hourly_rotpoints_at_temp( static_cast<int>( i ) ) );
    }
    return ret;
}
References calc_hourly_rotpoints_at_temp(), and cata::hash64_detail::ret.
Referenced by get_hourly_rotpoints_at_temp().
clip_by_temperature_flag()
static units::temperature clip_by_temperature_flag (units::temperature temperature, temperature_flag flag) static
Definition at line 8951 of file item.cpp.
{
    switch( flag ) {
        case temperature_flag::TEMP_NORMAL:
            // Just use the temperature normally
            return temperature;
        case temperature_flag::TEMP_FRIDGE:
            return std::min( temperature, temperatures::fridge );
        case temperature_flag::TEMP_FREEZER:
            return std::min( temperature, temperatures::freezer );
        case temperature_flag::TEMP_HEATER:
            return std::max( temperature, temperatures::normal );
        case temperature_flag::TEMP_ROOT_CELLAR:
            return temperatures::root_cellar;
        default:
            debugmsg( "Temperature flag enum not valid: %d.  Using current temperature.",
                      static_cast<int>( flag ) );
            break;
    }
    return temperature;
}
References debugmsg, temperatures::freezer, temperatures::fridge, temperatures::normal, temperatures::root_cellar, TEMP_FREEZER, TEMP_FRIDGE, TEMP_HEATER, TEMP_NORMAL, and TEMP_ROOT_CELLAR.
Referenced by item::process_rot().
CLOTHING_MOD_VAR_PREFIX()
static const std::string CLOTHING_MOD_VAR_PREFIX ("clothing_mod_") static
Referenced by item::get_clothing_mod_val(), and item::update_clothing_mod_val().
flag_ALWAYS_TWOHAND()
static const std::string flag_ALWAYS_TWOHAND ("ALWAYS_TWOHAND") static
Referenced by item::is_two_handed().
flag_AURA()
static const std::string flag_AURA ("AURA") static
Referenced by item::armor_info(), and item::get_layer().
flag_BELTED()
static const std::string flag_BELTED ("BELTED") static
Referenced by item::armor_info(), and item::get_layer().
flag_BIPOD()
static const std::string flag_BIPOD ("BIPOD") static
Referenced by item::gun_info(), and item::gun_recoil_multiplier().
flag_BYPRODUCT()
static const std::string flag_BYPRODUCT ("BYPRODUCT") static
Referenced by item::components_to_string().
flag_CABLE_SPOOL()
static const std::string flag_CABLE_SPOOL ("CABLE_SPOOL") static
Referenced by item::process_internal(), and item::process_UPS().
flag_CANNIBALISM()
static const std::string flag_CANNIBALISM ("CANNIBALISM") static
Referenced by item::food_info().
flag_CBM_SCANNED()
static const std::string flag_CBM_SCANNED ("CBM_SCANNED") static
Referenced by item::tname().
flag_CHARGEDIM()
static const std::string flag_CHARGEDIM ("CHARGEDIM") static
Referenced by item::getlight_emit().
flag_COLLAPSIBLE_STOCK()
static const std::string flag_COLLAPSIBLE_STOCK ("COLLAPSIBLE_STOCK") static
Referenced by item::volume().
flag_CONDUCTIVE()
static const std::string flag_CONDUCTIVE ("CONDUCTIVE") static
Referenced by item::conductive(), and item::final_info().
flag_CONSUMABLE()
static const std::string flag_CONSUMABLE ("CONSUMABLE") static
Referenced by item::final_info().
flag_CORPSE()
static const std::string flag_CORPSE ("CORPSE") static
Referenced by item::durability_indicator(), item::is_corpse(), item::item(), and item::type_name().
flag_CROSSBOW()
static const std::string flag_CROSSBOW ("CROSSBOW") static
Referenced by item::gun_type().
flag_DANGEROUS()
static const std::string flag_DANGEROUS ("DANGEROUS") static
Referenced by item::is_dangerous().
flag_DEEP_WATER()
static const std::string flag_DEEP_WATER ("DEEP_WATER") static
Referenced by item::process_extinguish().
flag_DIAMOND()
static const std::string flag_DIAMOND ("DIAMOND") static
Referenced by item::damage_melee(), and item::tname().
flag_DISABLE_SIGHTS()
static const std::string flag_DISABLE_SIGHTS ("DISABLE_SIGHTS") static
Referenced by item::final_info(), and item::sight_dispersion().
flag_ETHEREAL_ITEM()
static const std::string flag_ETHEREAL_ITEM ("ETHEREAL_ITEM") static
Referenced by item::needs_processing(), item::process_internal(), and item::tname().
flag_FAKE_MILL()
static const std::string flag_FAKE_MILL ("FAKE_MILL") static
Referenced by item::process_internal().
flag_FAKE_SMOKE()
static const std::string flag_FAKE_SMOKE ("FAKE_SMOKE") static
Referenced by item::process_internal().
flag_FIELD_DRESS()
static const std::string flag_FIELD_DRESS ("FIELD_DRESS") static
Referenced by item::calc_rot(), item::can_revive(), item::corpse_volume(), and item::weight().
flag_FIELD_DRESS_FAILED()
static const std::string flag_FIELD_DRESS_FAILED ("FIELD_DRESS_FAILED") static
Referenced by item::can_revive(), item::corpse_volume(), and item::weight().
flag_FILTHY()
static const std::string flag_FILTHY ("FILTHY") static
Referenced by item::is_filthy().
flag_FIRE_100()
static const std::string flag_FIRE_100 ("FIRE_100") static
Referenced by item::ammo_required().
flag_FIRE_20()
static const std::string flag_FIRE_20 ("FIRE_20") static
Referenced by item::ammo_required().
flag_FIRE_50()
static const std::string flag_FIRE_50 ("FIRE_50") static
Referenced by item::ammo_required().
flag_FIRE_TWOHAND()
static const std::string flag_FIRE_TWOHAND ("FIRE_TWOHAND") static
Referenced by item::final_info().
flag_FIT()
static const std::string flag_FIT ("FIT") static
Referenced by item::armor_fit_info(), item::armor_info(), item::get_encumber_when_containing(), and item::tname().
flag_FLAMMABLE()
static const std::string flag_FLAMMABLE ("FLAMMABLE") static
Referenced by item::process_litcig().
flag_FLAMMABLE_ASH()
static const std::string flag_FLAMMABLE_ASH ("FLAMMABLE_ASH") static
Referenced by item::process_litcig().
flag_GIBBED()
static const std::string flag_GIBBED ("GIBBED") static
Referenced by item::corpse_volume(), and item::weight().
flag_HEATS_FOOD()
static const std::string flag_HEATS_FOOD ("HEATS_FOOD") static
Referenced by item::tname().
flag_HELMET_COMPAT()
static const std::string flag_HELMET_COMPAT ("HELMET_COMPAT") static
Referenced by item::armor_fit_info().
flag_HIDDEN_HALLU()
static const std::string flag_HIDDEN_HALLU ("HIDDEN_HALLU") static
Referenced by item::food_info(), and item::tname().
flag_HIDDEN_POISON()
static const std::string flag_HIDDEN_POISON ("HIDDEN_POISON") static
Referenced by item::food_info(), and item::tname().
flag_IRREMOVABLE()
static const std::string flag_IRREMOVABLE ("IRREMOVABLE") static
Referenced by item::is_irremovable().
flag_IS_ARMOR()
static const std::string flag_IS_ARMOR ("IS_ARMOR") static
Referenced by item::is_armor().
flag_IS_PET_ARMOR()
static const std::string flag_IS_PET_ARMOR ("IS_PET_ARMOR") static
Referenced by item::is_pet_armor().
flag_IS_UPS()
static const std::string flag_IS_UPS ("IS_UPS") static
Referenced by item::process_internal(), and item::tname().
flag_LEAK_ALWAYS()
static const std::string flag_LEAK_ALWAYS ("LEAK_ALWAYS") static
Referenced by item::final_info().
flag_LEAK_DAM()
static const std::string flag_LEAK_DAM ("LEAK_DAM") static
Referenced by item::color_in_inventory(), and item::final_info().
flag_LIQUID()
static const std::string flag_LIQUID ("LIQUID") static
Referenced by item::process_extinguish().
flag_LIQUIDCONT()
static const std::string flag_LIQUIDCONT ("LIQUIDCONT") static
Referenced by item::on_drop().
flag_LITCIG()
static const std::string flag_LITCIG ("LITCIG") static
Referenced by item::color_in_inventory(), item::process_extinguish(), item::process_internal(), and item::tname().
flag_MAG_BELT()
static const std::string flag_MAG_BELT ("MAG_BELT") static
Referenced by item::is_ammo_belt().
flag_MAG_DESTROY()
static const std::string flag_MAG_DESTROY ("MAG_DESTROY") static
Referenced by item::ammo_consume().
flag_MAG_EJECT()
static const std::string flag_MAG_EJECT ("MAG_EJECT") static
Referenced by item::ammo_consume().
flag_NANOFAB_TEMPLATE()
static const std::string flag_NANOFAB_TEMPLATE ("NANOFAB_TEMPLATE") static
Referenced by item::item().
flag_NAT_UPS()
static const std::string flag_NAT_UPS ("NAT_UPS") static
Referenced by item::tname().
flag_NEEDS_UNFOLD()
static const std::string flag_NEEDS_UNFOLD ("NEEDS_UNFOLD") static
Referenced by item::on_wield().
flag_NEVER_JAMS()
static const std::string flag_NEVER_JAMS ("NEVER_JAMS") static
Referenced by item::is_gunmod_compatible().
flag_NO_DISPLAY()
static const std::string flag_NO_DISPLAY ("NO_DISPLAY") static
Referenced by item::food_info().
flag_NO_DROP()
static const std::string flag_NO_DROP ("NO_DROP") static
Referenced by item::weight().
flag_NO_PARASITES()
static const std::string flag_NO_PARASITES ("NO_PARASITES") static
Referenced by item::food_info().
flag_NO_RELOAD()
static const std::string flag_NO_RELOAD ("NO_RELOAD") static
Referenced by item::final_info(), item::is_reloadable(), and item::magazine_info().
flag_NO_REPAIR()
static const std::string flag_NO_REPAIR ("NO_REPAIR") static
Referenced by item::reinforceable(), and item::repaired_with().
flag_NO_SALVAGE()
static const std::string flag_NO_SALVAGE ("NO_SALVAGE") static
Referenced by item::is_salvageable().
flag_NO_UNLOAD()
static const std::string flag_NO_UNLOAD ("NO_UNLOAD") static
Referenced by item::ammo_set().
flag_NONCONDUCTIVE()
static const std::string flag_NONCONDUCTIVE ("NONCONDUCTIVE") static
Referenced by item::conductive().
flag_OUTER()
static const std::string flag_OUTER ("OUTER") static
Referenced by item::armor_info(), and item::get_layer().
flag_OVERSIZE()
static const std::string flag_OVERSIZE ("OVERSIZE") static
Referenced by item::get_sizing().
flag_PERSONAL()
static const std::string flag_PERSONAL ("PERSONAL") static
Referenced by item::armor_info(), and item::get_layer().
flag_POWERARMOR_EXO()
static const std::string flag_POWERARMOR_EXO ("POWERARMOR_EXO") static
Referenced by item::armor_fit_info(), item::is_power_armor(), and item::is_worn_only_with().
flag_POWERARMOR_EXTERNAL()
static const std::string flag_POWERARMOR_EXTERNAL ("POWERARMOR_EXTERNAL") static
Referenced by item::armor_fit_info(), item::is_power_armor(), and item::is_worn_only_with().
flag_POWERARMOR_MOD()
static const std::string flag_POWERARMOR_MOD ("POWERARMOR_MOD") static
Referenced by item::is_power_armor(), item::is_worn_only_with(), and item::on_wear().
flag_PROCESSING()
static const std::string flag_PROCESSING ("PROCESSING") static
Referenced by item::goes_bad().
flag_PROCESSING_RESULT()
static const std::string flag_PROCESSING_RESULT ("PROCESSING_RESULT") static
Referenced by item::set_relative_rot().
flag_PULPED()
static const std::string flag_PULPED ("PULPED") static
Referenced by item::can_revive(), and item::on_damage().
flag_PUMP_ACTION()
static const std::string flag_PUMP_ACTION ("PUMP_ACTION") static
Referenced by item::is_gunmod_compatible().
flag_PUMP_RAIL_COMPATIBLE()
static const std::string flag_PUMP_RAIL_COMPATIBLE ("PUMP_RAIL_COMPATIBLE") static
Referenced by item::is_gunmod_compatible().
flag_QUARTERED()
static const std::string flag_QUARTERED ("QUARTERED") static
Referenced by item::can_revive(), item::corpse_volume(), and item::weight().
flag_RADIO_ACTIVATION()
static const std::string flag_RADIO_ACTIVATION ("RADIO_ACTIVATION") static
Referenced by item::final_info(), and item::needs_processing().
flag_RADIO_INVOKE_PROC()
static const std::string flag_RADIO_INVOKE_PROC ("RADIO_INVOKE_PROC") static
Referenced by item::final_info().
flag_RADIO_MOD()
static const std::string flag_RADIO_MOD ("RADIO_MOD") static
Referenced by item::final_info(), and item::tname().
flag_RADIOACTIVE()
static const std::string flag_RADIOACTIVE ("RADIOACTIVE") static
Referenced by item::color_in_inventory(), and item::final_info().
flag_RADIOSIGNAL_1()
static const std::string flag_RADIOSIGNAL_1 ("RADIOSIGNAL_1") static
Referenced by item::final_info(), and item::tname().
flag_RADIOSIGNAL_2()
static const std::string flag_RADIOSIGNAL_2 ("RADIOSIGNAL_2") static
Referenced by item::final_info(), and item::tname().
flag_RADIOSIGNAL_3()
static const std::string flag_RADIOSIGNAL_3 ("RADIOSIGNAL_3") static
Referenced by item::final_info(), and item::tname().
flag_RAIN_PROTECT()
static const std::string flag_RAIN_PROTECT ("RAIN_PROTECT") static
Referenced by item::process_extinguish().
flag_REACH3()
static const std::string flag_REACH3 ("REACH3") static
Referenced by item::combat_info(), and item::reach_range().
flag_REACH_ATTACK()
static const std::string flag_REACH_ATTACK ("REACH_ATTACK") static
Referenced by item::combat_info(), item::gunmod_info(), and item::reach_range().
flag_RECHARGE()
static const std::string flag_RECHARGE ("RECHARGE") static
Referenced by item::final_info().
flag_REDUCED_BASHING()
static const std::string flag_REDUCED_BASHING ("REDUCED_BASHING") static
Referenced by item::damage_melee().
flag_REDUCED_WEIGHT()
static const std::string flag_REDUCED_WEIGHT ("REDUCED_WEIGHT") static
Referenced by item::weight().
flag_RELOAD_AND_SHOOT()
static const std::string flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT") static
Referenced by item::display_name().
flag_RELOAD_EJECT()
static const std::string flag_RELOAD_EJECT ("RELOAD_EJECT") static
Referenced by item::is_gunmod_compatible().
flag_RELOAD_ONE()
static const std::string flag_RELOAD_ONE ("RELOAD_ONE") static
Referenced by item::gun_info(), and item_reload_option::qty().
flag_REVIVE_SPECIAL()
static const std::string flag_REVIVE_SPECIAL ("REVIVE_SPECIAL") static
Referenced by item::ready_to_revive().
flag_SILENT()
static const std::string flag_SILENT ("SILENT") static
Referenced by item::tname().
flag_SKINNED()
static const std::string flag_SKINNED ("SKINNED") static
Referenced by item::can_revive(), item::corpse_volume(), and item::weight().
flag_SKINTIGHT()
static const std::string flag_SKINTIGHT ("SKINTIGHT") static
Referenced by item::armor_info(), and item::get_layer().
flag_SLOW_WIELD()
static const std::string flag_SLOW_WIELD ("SLOW_WIELD") static
Referenced by item::on_wield().
flag_SPEEDLOADER()
static const std::string flag_SPEEDLOADER ("SPEEDLOADER") static
Referenced by item_reload_option::qty(), and item::reload().
flag_SPLINT()
static const std::string flag_SPLINT ("SPLINT") static
Referenced by item::on_wear().
flag_STR_DRAW()
static const std::string flag_STR_DRAW ("STR_DRAW") static
Referenced by item::basic_info().
flag_TOBACCO()
static const std::string flag_TOBACCO ("TOBACCO") static
Referenced by item::process_litcig().
flag_UNARMED_WEAPON()
static const std::string flag_UNARMED_WEAPON ("UNARMED_WEAPON") static
Referenced by item::is_unarmed_weapon(), and item::melee_skill().
flag_UNDERSIZE()
static const std::string flag_UNDERSIZE ("UNDERSIZE") static
Referenced by item::get_sizing().
flag_USE_UPS()
static const std::string flag_USE_UPS ("USE_UPS") static
Referenced by item::final_info(), item::getlight_emit(), item::process_tool(), item::tname(), and item::units_remaining().
flag_USES_BIONIC_POWER()
static const std::string flag_USES_BIONIC_POWER ("USES_BIONIC_POWER") static
Referenced by item::ammo_consume(), item::ammo_remaining(), item::final_info(), and item::tool_info().
flag_VARSIZE()
static const std::string flag_VARSIZE ("VARSIZE") static
Referenced by item::armor_fit_info(), item::armor_info(), item::get_encumber_when_containing(), and item::tname().
flag_VEHICLE()
static const std::string flag_VEHICLE ("VEHICLE") static
Referenced by item::is_reloadable().
flag_WAIST()
static const std::string flag_WAIST ("WAIST") static
Referenced by item::armor_info(), and item::get_layer().
flag_WATER_EXTINGUISH()
static const std::string flag_WATER_EXTINGUISH ("WATER_EXTINGUISH") static
Referenced by item::process_internal(), and item::tname().
flag_WATERPROOF_GUN()
static const std::string flag_WATERPROOF_GUN ("WATERPROOF_GUN") static
Referenced by item::is_gunmod_compatible().
flag_WET()
static const std::string flag_WET ("WET") static
Referenced by item::color_in_inventory(), item::process_internal(), and item::tname().
flag_WIND_EXTINGUISH()
static const std::string flag_WIND_EXTINGUISH ("WIND_EXTINGUISH") static
Referenced by item::process_extinguish(), and item::process_internal().
get_base_env_resist()
static int get_base_env_resist (const item & it) static
Definition at line 1220 of file item.cpp.
{
    const islot_armor *t = it.find_armor_data();
    if( t == nullptr ) {
        if( it.is_pet_armor() ) {
            return it.type->pet_armor->env_resist * it.get_relative_health();
        } else {
            return 0;
        }
    }
    return t->env_resist * it.get_relative_health();
}
References islot_armor::env_resist, item::find_armor_data(), item::get_relative_health(), item::is_pet_armor(), itype::pet_armor, and item::type.
Referenced by item::armor_protection_info().
get_food_impl()
template<typename Item > static Item * get_food_impl (Item * it) static
Definition at line 6631 of file item.cpp.
{
    if( it->is_food() ) {
        return it;
    } else if( it->is_food_container() && !it->contents.empty() ) {
        return &it->contents.front();
    } else {
        return nullptr;
    }
}
Referenced by item::get_food().
get_freshness_description()
static std::string get_freshness_description (const item & food_item) static
Definition at line 1111 of file item.cpp.
{
    // So, skilled characters looking at food that is neither super-fresh nor about to rot
    // can guess its age as one of {quite fresh,midlife,past midlife,old soon}, and also
    // guess about how long until it spoils.
    const double rot_progress = food_item.get_relative_rot();
    const time_duration shelf_life = food_item.get_shelf_life();
    time_duration time_left = shelf_life - ( shelf_life * rot_progress );
    // Correct for an estimate that exceeds shelf life -- this happens especially with
    // fresh items.
    if( time_left > shelf_life ) {
        time_left = shelf_life;
    }
    avatar &you = get_avatar();
    if( food_item.is_fresh() ) {
        // Fresh food is assumed to be obviously so regardless of skill.
        if( you.can_estimate_rot() ) {
            return string_format( _( "* This food looks as <good>fresh</good> as it can be.  "
                                     "It still has <info>%s</info> until it spoils." ),
                                  to_string_approx( time_left ) );
        } else {
            return _( "* This food looks as <good>fresh</good> as it can be." );
        }
    } else if( food_item.is_going_bad() ) {
        // Old food likewise is assumed to be fairly obvious.
        if( you.can_estimate_rot() ) {
            return string_format( _( "* This food looks <bad>old</bad>.  "
                                     "It's just <info>%s</info> from becoming inedible." ),
                                  to_string_approx( time_left ) );
        } else {
            return _( "* This food looks <bad>old</bad>.  "
                      "It's on the brink of becoming inedible." );
        }
    }
    if( !you.can_estimate_rot() ) {
        // Unskilled characters only get a hint that more information exists...
        return _( "* This food looks <info>fine</info>.  If you were more skilled in "
                  "cooking or survival, you might be able to make a better estimation." );
    }
    // Otherwise, a skilled character can determine the below options:
    if( rot_progress < 0.3 ) {
        //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
        return string_format( _( "* This food looks <good>quite fresh</good>.  "
                                 "It has <info>%s</info> until it spoils." ),
                              to_string_approx( time_left ) );
    } else if( rot_progress < 0.5 ) {
        //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
        return string_format( _( "* This food looks like it is reaching its <neutral>midlife</neutral>.  "
                                 "There's <info>%s</info> before it spoils." ),
                              to_string_approx( time_left ) );
    } else if( rot_progress < 0.7 ) {
        //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
        return string_format( _( "* This food looks like it has <neutral>passed its midlife</neutral>.  "
                                 "Edible, but will go bad in <info>%s</info>." ),
                              to_string_approx( time_left ) );
    } else {
        //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
        return string_format( _( "* This food looks like it <bad>will be old soon</bad>.  "
                                 "It has <info>%s</info>, so if you plan to use it, it's now or never." ),
                              to_string_approx( time_left ) );
    }
}
References _, Character::can_estimate_rot(), get_avatar(), item::get_relative_rot(), item::get_shelf_life(), item::is_fresh(), item::is_going_bad(), string_format(), and to_string_approx().
Referenced by item::food_info().
get_hourly_rotpoints_at_temp()
int get_hourly_rotpoints_at_temp (const int temp)
Get the hourly rot for a given temperature from the precomputed table.
Calculates rot per hour at given temperature.
See also
rot_chart
Precomputed rot lookup table.
Definition at line 5635 of file item.cpp.
{
    /**
     * Precomputed rot lookup table.
     */
    static const std::vector<int> rot_chart = calc_rot_array( 200 );
    if( temp < 0 ) {
        return 0;
    }
    if( temp > 150 ) {
        return 21240;
    }
    return rot_chart[temp];
}
References calc_rot_array().
Referenced by item::calc_rot(), and item::minimum_freshness_duration().
get_most_rotten_component()
static const item * get_most_rotten_component (const item & craft) static
Definition at line 451 of file item.cpp.
{
    const item *most_rotten = nullptr;
    for( const item &it : craft.components ) {
        if( it.goes_bad() ) {
            if( !most_rotten || it.get_relative_rot() > most_rotten->get_relative_rot() ) {
                most_rotten = &it;
            }
        }
    }
    return most_rotten;
}
References iuse::craft(), item::get_relative_rot(), and item::goes_bad().
Referenced by item::item().
get_ranged_armor_mult()
static float get_ranged_armor_mult (const common_ranged_data & ranged) static
Definition at line 1100 of file item.cpp.
{
    if( ranged.damage.empty() ) {
        return 0.0f;
    }
    return ranged.damage.damage_units.front().res_mult;
}
Referenced by item::ammo_info().
get_ranged_pierce()
static int get_ranged_pierce (const common_ranged_data & ranged) static
Definition at line 1091 of file item.cpp.
{
    if( ranged.damage.empty() ) {
        return 0;
    }
    return ranged.damage.damage_units.front().res_pen;
}
Referenced by item::ammo_info(), item::gun_info(), and item::gunmod_info().
GUN_MODE_VAR_NAME()
static const std::string GUN_MODE_VAR_NAME ("item::mode") static
Referenced by item::gun_get_mode_id(), and item::gun_set_mode().
has_thievery_witness()
static const std::string has_thievery_witness ("has_thievery_witness") static
Referenced by item::handle_pickup_ownership().
insert_separation_line()
static void insert_separation_line (std::vector< iteminfo > & info) static
Definition at line 1301 of file item.cpp.
{
    if( info.empty() || info.back().sName != "--" ) {
        info.push_back( iteminfo( "DESCRIPTION", "--" ) );
    }
}
Referenced by item::ammo_info(), item::armor_info(), item::basic_info(), item::battery_info(), item::bionic_info(), item::book_info(), item::combat_info(), item::container_info(), item::contents_info(), item::disassembly_info(), item::final_info(), item::food_info(), item::gun_info(), item::gunmod_info(), item::info(), item::magazine_info(), item::qualities_info(), item::repair_info(), and item::tool_info().
item_compare_by_charges()
bool item_compare_by_charges (const item & left, const item & right)
Definition at line 8842 of file item.cpp.
{
    return item_ptr_compare_by_charges( &left, &right );
}
References item_ptr_compare_by_charges(), left, and align::right.
item_ptr_compare_by_charges()
bool item_ptr_compare_by_charges (const item * left, const item * right)
Definition at line 8831 of file item.cpp.
{
    if( left->contents.empty() ) {
        return false;
    } else if( right->contents.empty() ) {
        return true;
    } else {
        return right->contents.front().charges < left->contents.front().charges;
    }
}
References left, and align::right.
Referenced by player::check_eligible_containers_for_crafting(), and item_compare_by_charges().
null_item_reference()
item & null_item_reference ()
Returns a reference to a null item (see item::is_null).
The reference is always valid and stays valid until the program ends.
Definition at line 322 of file item.cpp.
{
    static item result{};
    // reset it, in case a previous caller has changed it
    result = item();
    return result;
}
Referenced by target_ui::action_aim_and_shoot(), map::add_item(), map::add_item_or_charges(), Character::best_shield(), inventory::find_item(), npc::find_reloadable(), item::get_contained(), npc::get_healing_item(), npc::heal_self(), Character::item_with_best_of_quality(), inventory::most_appropriate_painkiller(), item_stack::only_item(), set_item_map(), map::spawn_an_item(), Character::used_weapon(), and npc::wield_better_weapon().
nullitem()
static const itype * nullitem () static
Definition at line 316 of file item.cpp.
{
    static itype nullitem_m;
    return &nullitem_m;
}
Referenced by item::is_null(), and item::item().
rad_badge_color()
std::string rad_badge_color (const int rad)
Definition at line 289 of file item.cpp.
{
    using pair_t = std::pair<const int, const translation>;
    static const std::array<pair_t, 6> values = {{
            pair_t {  0, to_translation( "color", "green" ) },
            pair_t { 30, to_translation( "color", "blue" )  },
            pair_t { 60, to_translation( "color", "yellow" )},
            pair_t {120, to_translation( "color", "orange" )},
            pair_t {240, to_translation( "color", "red" )   },
            pair_t {500, to_translation( "color", "black" ) },
        }
    };
    for( const auto &i : values ) {
        if( rad <= i.first ) {
            return i.second.translated();
        }
    }
    return values.back().second.translated();
}
References rad, to_translation(), and translation::translated().
Referenced by item::armor_fit_info(), and Character::irradiate().
temperature_flag_to_highest_temperature()
static int temperature_flag_to_highest_temperature (temperature_flag temperature) static
Definition at line 5682 of file item.cpp.
{
    switch( temperature ) {
        case temperature_flag::TEMP_NORMAL:
            return INT_MAX;
        case temperature_flag::TEMP_HEATER:
            return INT_MAX;
        case temperature_flag::TEMP_FRIDGE:
            return to_fahrenheit( temperatures::fridge );
        case temperature_flag::TEMP_FREEZER:
            return to_fahrenheit( temperatures::freezer );
        case temperature_flag::TEMP_ROOT_CELLAR:
            return to_fahrenheit( temperatures::root_cellar );
    }
    return INT_MAX;
}
References temperatures::freezer, temperatures::fridge, temperatures::root_cellar, TEMP_FREEZER, TEMP_FRIDGE, TEMP_HEATER, TEMP_NORMAL, TEMP_ROOT_CELLAR, and units::to_fahrenheit().
Referenced by item::minimum_freshness_duration().
trait_flag_CANNIBAL()
static const std::string trait_flag_CANNIBAL ("CANNIBAL") static
Referenced by item::food_info().
USED_BY_IDS()
static const std::string USED_BY_IDS ("USED_BY_IDS") static
Referenced by item::already_used_by_player(), and item::mark_as_used_by_player().
Variable Documentation
ACT_PICKUP
const activity_id ACT_PICKUP("ACT_PICKUP") ("ACT_PICKUP") static
Referenced by item::handle_pickup_ownership().
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by item::allow_crafting_component().
ammo_effect_BLACKPOWDER
const ammo_effect_str_id ammo_effect_BLACKPOWDER("BLACKPOWDER") ("BLACKPOWDER") static
Referenced by item::ammo_info().
ammo_effect_INCENDIARY
const ammo_effect_str_id ammo_effect_INCENDIARY("INCENDIARY") ("INCENDIARY") static
Referenced by item::ammo_info().
ammo_effect_NEVER_MISFIRES
const ammo_effect_str_id ammo_effect_NEVER_MISFIRES("NEVER_MISFIRES") ("NEVER_MISFIRES") static
Referenced by item::ammo_info().
ammo_effect_RECYCLED
const ammo_effect_str_id ammo_effect_RECYCLED("RECYCLED") ("RECYCLED") static
Referenced by item::ammo_info().
ammo_plutonium
const ammotype ammo_plutonium("plutonium") ("plutonium") static
Referenced by item_reload_option::qty(), and item::reload().
bio_digestion
const bionic_id bio_digestion("bio_digestion") ("bio_digestion") static
Referenced by item::food_info().
dps_comp_monsters
const std::vector<std::pair<translation, dps_comp_data> > dps_comp_monsters static
Initial value:
= {
    { to_translation( "Best" ), { mtype_id( "debug_mon" ), true, false } },
    { to_translation( "Vs. Agile" ), { mtype_id( "mon_zombie_smoker" ), true, true } },
    { to_translation( "Vs. Armored" ), { mtype_id( "mon_zombie_soldier" ), true, true } },
    { to_translation( "Vs. Mixed" ), { mtype_id( "mon_zombie_survivor" ), false, true } },
}
Definition at line 1421 of file item.cpp.
Referenced by item::dps().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by item::process_litcig().
effect_shakes
const efftype_id effect_shakes("shakes") ("shakes") static
Referenced by item::process_litcig().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by item::process_litcig().
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by item::process_litcig().
fault_bionic_nonsterile
const fault_id fault_bionic_nonsterile("fault_bionic_nonsterile") ("fault_bionic_nonsterile") static
Referenced by item::color_in_inventory(), and item::tname().
fault_gun_blackpowder
const fault_id fault_gun_blackpowder("fault_gun_blackpowder") ("fault_gun_blackpowder") static
Referenced by item::process_internal().
flag_MELEE_GUNMOD
const flag_str_id flag_MELEE_GUNMOD("MELEE_GUNMOD") ("MELEE_GUNMOD") static
gun_mode_REACH
const gun_mode_id gun_mode_REACH("REACH") ("REACH") static
Referenced by item::gun_all_modes().
hits_by_accuracy
const double hits_by_accuracy[41] static
Initial value:
= {
    0,    1,   2,   3,   7,
    13,   26,  47,   82,  139,
    228,   359,  548,  808, 1151,
    1587, 2119, 2743, 3446, 4207,
    5000,
    5793, 6554, 7257, 7881, 8413,
    8849, 9192, 9452, 9641, 9772,
    9861, 9918, 9953, 9974, 9987,
    9993, 9997, 9998, 9999, 10000
}
Definition at line 1313 of file item.cpp.
Referenced by item::effective_dps().
itemcat_drugs
const item_category_id itemcat_drugs("drugs") ("drugs") static
Referenced by item::spoilage_sort_order().
itemcat_food
const item_category_id itemcat_food("food") ("food") static
Referenced by item::spoilage_sort_order().
itemcat_maps
const item_category_id itemcat_maps("maps") ("maps") static
Referenced by item::is_map().
itype_barrel_small
const itype_id itype_barrel_small("barrel_small") ("barrel_small") static
Referenced by item::tname(), item::volume(), and item::weight().
itype_bio_armor
const itype_id itype_bio_armor("bio_armor") ("bio_armor") static
Referenced by item::process_tool(), and item::units_remaining().
itype_blood
const itype_id itype_blood("blood") ("blood") static
Referenced by item::tname(), and item::type_name().
itype_brass_catcher
const itype_id itype_brass_catcher("brass_catcher") ("brass_catcher") static
Referenced by item::is_gunmod_compatible().
itype_cig_butt
const itype_id itype_cig_butt("cig_butt") ("cig_butt") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_cig_lit
const itype_id itype_cig_lit("cig_lit") ("cig_lit") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_cigar_butt
const itype_id itype_cigar_butt("cigar_butt") ("cigar_butt") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_cigar_lit
const itype_id itype_cigar_lit("cigar_lit") ("cigar_lit") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_hand_crossbow
const itype_id itype_hand_crossbow("hand_crossbow") ("hand_crossbow") static
Referenced by item::is_gunmod_compatible().
itype_joint_roach
const itype_id itype_joint_roach("joint_roach") ("joint_roach") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_plut_cell
const itype_id itype_plut_cell("plut_cell") ("plut_cell") static
Referenced by item::weight().
itype_rad_badge
const itype_id itype_rad_badge("rad_badge") ("rad_badge") static
Referenced by item::armor_fit_info().
itype_stock_small
const itype_id itype_stock_small("stock_small") ("stock_small") static
Referenced by item::tname().
itype_tuned_mechanism
const itype_id itype_tuned_mechanism("tuned_mechanism") ("tuned_mechanism") static
Referenced by item::is_gunmod_compatible().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by item::process_tool(), and item::units_remaining().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by item::is_funnel_container().
itype_water_acid
const itype_id itype_water_acid("water_acid") ("water_acid") static
Referenced by item::is_funnel_container().
itype_water_acid_weak
const itype_id itype_water_acid_weak("water_acid_weak") ("water_acid_weak") static
Referenced by item::is_funnel_container().
itype_waterproof_gunmod
const itype_id itype_waterproof_gunmod("waterproof_gunmod") ("waterproof_gunmod") static
Referenced by item::is_gunmod_compatible().
nolight
light_emission nolight = {0, 0, 0}
Definition at line 312 of file item.cpp.
Referenced by item::io().
qual_JACK
const quality_id qual_JACK("JACK") ("JACK") static
Referenced by item::qualities_info().
qual_LIFT
const quality_id qual_LIFT("LIFT") ("LIFT") static
Referenced by item::qualities_info().
rapid_strike
const matec_id rapid_strike("RAPID") ("RAPID") static
Referenced by item::effective_dps().
ROBOT
const species_id ROBOT("ROBOT") ("ROBOT") static
Referenced by item::process_corpse().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by item::food_info(), and item::tname().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by item::melee_skill().
skill_weapon
const skill_id skill_weapon("weapon") ("weapon") static
Referenced by item::contextualize_skill().
trait_CARNIVORE
const trait_id trait_CARNIVORE("CARNIVORE") ("CARNIVORE") static
Referenced by item::food_info().
trait_LIGHTWEIGHT
const trait_id trait_LIGHTWEIGHT("LIGHTWEIGHT") ("LIGHTWEIGHT") static
Referenced by item::process_litcig().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by item::food_info().
trait_SQUEAMISH
const trait_id trait_SQUEAMISH("SQUEAMISH") ("SQUEAMISH") static
Referenced by item::is_filthy().
trait_TOLERANCE
const trait_id trait_TOLERANCE("TOLERANCE") ("TOLERANCE") static
Referenced by item::process_litcig().
trait_WOOLALLERGY
const trait_id trait_WOOLALLERGY("WOOLALLERGY") ("WOOLALLERGY") static
Referenced by item::color_in_inventory(), and item::final_info().