Cataclysm BN: src/item_group.cpp File Reference
item_group.cpp File Reference
#include "item_group.h"
#include <algorithm>
#include <cassert>
#include <set>
#include "calendar.h"
#include "debug.h"
#include "enums.h"
#include "flat_set.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "json.h"
#include "rng.h"
#include "type_id.h"
#include "value_ptr.h"
Functions
static const std::string flag_NEEDS_NO_LUBE ("NEEDS_NO_LUBE")
static const std::string flag_NON_FOULING ("NON-FOULING")
static const std::string flag_PRIMITIVE_RANGED_WEAPON ("PRIMITIVE_RANGED_WEAPON")
static const std::string flag_VARSIZE ("VARSIZE")
static item_group_id get_unique_group_id ()
Function Documentation
flag_NEEDS_NO_LUBE()
static const std::string flag_NEEDS_NO_LUBE ("NEEDS_NO_LUBE") static
Referenced by Item_modifier::modify().
flag_NON_FOULING()
static const std::string flag_NON_FOULING ("NON-FOULING") static
Referenced by Item_modifier::modify().
flag_PRIMITIVE_RANGED_WEAPON()
static const std::string flag_PRIMITIVE_RANGED_WEAPON ("PRIMITIVE_RANGED_WEAPON") static
Referenced by Item_modifier::modify().
flag_VARSIZE()
static const std::string flag_VARSIZE ("VARSIZE") static
Referenced by Single_item_creator::create_single().
get_unique_group_id()
static item_group_id get_unique_group_id () static
Definition at line 632 of file item_group.cpp.
{
    // This is just a hint what id to use next. Overflow of it is defined and if the group
    // name is already used, we simply go the next id.
    static unsigned int next_id = 0;
    // Prefixing with a character outside the ASCII range, so it is hopefully unique and
    // (if actually printed somewhere) stands out. Theoretically those auto-generated group
    // names should not be seen anywhere.
    static const std::string unique_prefix = "\u01F7 ";
    while( true ) {
        const item_group_id new_group = item_group_id( unique_prefix + std::to_string( next_id++ ) );
        if( !item_group::group_is_defined( new_group ) ) {
            return new_group;
        }
    }
}
References item_group::group_is_defined(), and to_string().
Referenced by item_group::load_item_group().