Cataclysm BN: src/item_action.cpp File Reference
item_action.cpp File Reference
#include "item_action.h"
#include <algorithm>
#include <iterator>
#include <list>
#include <memory>
#include <set>
#include <tuple>
#include <unordered_set>
#include <utility>
#include "avatar.h"
#include "calendar.h"
#include "catacharset.h"
#include "clone_ptr.h"
#include "cursesdef.h"
#include "debug.h"
#include "game.h"
#include "input.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_factory.h"
#include "itype.h"
#include "iuse.h"
#include "json.h"
#include "output.h"
#include "player.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
Classes
class actmenu_cb
Functions
static const std::string errstring ("ERROR")
static char key_bound_to (const input_context &ctxt, const item_action_id &act)
Variables
static const bionic_id bio_tools ("bio_tools")
static const bionic_id bio_claws ("bio_claws")
static const bionic_id bio_claws_weapon ("bio_claws_weapon")
static item_action nullaction
Function Documentation
errstring()
static const std::string errstring ("ERROR") static
Referenced by use_function::get_name(), and use_function::get_type().
key_bound_to()
static char key_bound_to (const input_context & ctxt, const item_action_id & act) static
Definition at line 47 of file item_action.cpp.
{
    auto keys = ctxt.keys_bound_to( act );
    return keys.empty() ? '\0' : keys[0];
}
References act, and input_context::keys_bound_to().
Variable Documentation
bio_claws
const bionic_id bio_claws("bio_claws") ("bio_claws") static
Referenced by game::item_action_menu().
bio_claws_weapon
const bionic_id bio_claws_weapon("bio_claws_weapon") ("bio_claws_weapon") static
Referenced by game::item_action_menu().
bio_tools
const bionic_id bio_tools("bio_tools") ("bio_tools") static
Referenced by game::item_action_menu().
nullaction
item_action nullaction static
Definition at line 45 of file item_action.cpp.
Referenced by item_action_generator::get_action().