Cataclysm BN: src/item.h File Reference
item.h File Reference
#include <climits>
#include <cstdint>
#include <functional>
#include <list>
#include <map>
#include <set>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "calendar.h"
#include "enums.h"
#include "flat_set.h"
#include "gun_mode.h"
#include "io_tags.h"
#include "item_contents.h"
#include "item_location.h"
#include "optional.h"
#include "pimpl.h"
#include "safe_reference.h"
#include "string_id.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
#include "visitable.h"
Classes
struct light_emission
struct iteminfo
Value and metadata for one property of an item.
class item_reload_option
class item
struct item::default_charges_tag
Suppress randomization and always start with default quantity of charges.
struct item::solitary_tag
Default (or randomized) charges except if counted by charges then only one charge.
struct item::sound_data
class item::craft_data
Data for items that represent in-progress crafts.
Namespaces
namespace enchant_vals
namespace charge_removal_blacklist
namespace to_cbc_migration
Macros
#define CATA_SRC_ITEM_H
Typedefs
using bodytype_id = std::string
using faction_id = string_id< faction >
Functions
enum damage_type int enum clothing_mod_type int std::string rad_badge_color (int rad)
iteminfo::flags operator| (iteminfo::flags l, iteminfo::flags r)
iteminfo::flags & operator|= (iteminfo::flags &l, iteminfo::flags r)
bool is_crafting_component (const item &component)
Default filter for crafting component searches.
bool item_compare_by_charges (const item &left, const item &right)
bool item_ptr_compare_by_charges (const item *left, const item *right)
item & null_item_reference ()
Returns a reference to a null item (see item::is_null).
bool is_crafting_component_allow_filthy (const item &component)
This is used in recipes, all other cases use is_crafting_component instead.
const std::set< itype_id > & charge_removal_blacklist::get ()
void charge_removal_blacklist::load (const JsonObject &jo)
void charge_removal_blacklist::reset ()
void to_cbc_migration::load (const JsonObject &jo)
void to_cbc_migration::reset ()
Variables
light_emission nolight
Macro Definition Documentation
CATA_SRC_ITEM_H
#define CATA_SRC_ITEM_H
Definition at line 3 of file item.h.
Typedef Documentation
bodytype_id
using bodytype_id = std::string
Definition at line 66 of file item.h.
faction_id
using faction_id = string_id<faction>
Definition at line 67 of file item.h.
Function Documentation
is_crafting_component()
bool is_crafting_component (const item & component) inline
Default filter for crafting component searches.
Definition at line 2262 of file item.h.
{
    return ( component.allow_crafting_component() || component.count_by_charges() ) &&
           !component.is_filthy();
}
Referenced by are_requirements_nearby(), iexamine::autodoc(), can_do_activity_there(), veh_interact::can_potentially_install(), basecamp_action_components::choose_components(), veh_interact::complete_vehicle(), construction_activity(), construction_color(), construction_menu(), prepared_item_consumption::consume(), basecamp_action_components::consume_components(), iexamine::cvdmachine(), find_food_heater(), wash_activity_actor::finish(), veh_interact::format_reqs(), repair_item_actor::handle_components(), Character::has_enough_anesth(), is_non_rotten_crafting_component(), avatar_funcs::mend_item(), activity_handlers::mend_item_finish(), veh_utils::most_repairable_part(), iuse::multicooker(), iexamine::nanofab(), iuse::pack_cbm(), iexamine::pit(), place_construction(), player_can_build(), veh_utils::repair_part(), iexamine::tree_maple(), sew_advanced_actor::use(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
is_crafting_component_allow_filthy()
bool is_crafting_component_allow_filthy (const item & component) inline
This is used in recipes, all other cases use is_crafting_component instead.
This allows filthy components to be filtered out in a different manner that allows exceptions.
Definition at line 2272 of file item.h.
{
    return ( component.allow_crafting_component() || component.count_by_charges() );
}
Referenced by recipe::get_component_filter().
item_compare_by_charges()
bool item_compare_by_charges (const item & left, const item & right)
Definition at line 8834 of file item.cpp.
{
    return item_ptr_compare_by_charges( &left, &right );
}
References item_ptr_compare_by_charges(), left, and align::right.
item_ptr_compare_by_charges()
bool item_ptr_compare_by_charges (const item * left, const item * right)
Definition at line 8823 of file item.cpp.
{
    if( left->contents.empty() ) {
        return false;
    } else if( right->contents.empty() ) {
        return true;
    } else {
        return right->contents.front().charges < left->contents.front().charges;
    }
}
References left, and align::right.
Referenced by player::check_eligible_containers_for_crafting(), and item_compare_by_charges().
null_item_reference()
item & null_item_reference ()
Returns a reference to a null item (see item::is_null).
The reference is always valid and stays valid until the program ends.
Definition at line 322 of file item.cpp.
{
    static item result{};
    // reset it, in case a previous caller has changed it
    result = item();
    return result;
}
Referenced by target_ui::action_aim_and_shoot(), map::add_item(), map::add_item_or_charges(), Character::best_shield(), inventory::find_item(), npc::find_reloadable(), item::get_contained(), npc::get_healing_item(), npc::heal_self(), Character::item_with_best_of_quality(), inventory::most_appropriate_painkiller(), item_stack::only_item(), set_item_map(), map::spawn_an_item(), Character::used_weapon(), and npc::wield_better_weapon().
operator|()
iteminfo::flags operator| (iteminfo::flags l, iteminfo::flags r) inline
Definition at line 165 of file item.h.
{
    using I = std::underlying_type<iteminfo::flags>::type;
    return static_cast<iteminfo::flags>( static_cast<I>( l ) | r );
}
References type.
operator|=()
iteminfo::flags & operator|= (iteminfo::flags & l, iteminfo::flags r) inline
Definition at line 171 of file item.h.
{
    return l = l | r;
}
rad_badge_color()
enum damage_type int enum clothing_mod_type int std::string rad_badge_color (int rad)
Definition at line 289 of file item.cpp.
{
    using pair_t = std::pair<const int, const translation>;
    static const std::array<pair_t, 6> values = {{
            pair_t {  0, to_translation( "color", "green" ) },
            pair_t { 30, to_translation( "color", "blue" )  },
            pair_t { 60, to_translation( "color", "yellow" )},
            pair_t {120, to_translation( "color", "orange" )},
            pair_t {240, to_translation( "color", "red" )   },
            pair_t {500, to_translation( "color", "black" ) },
        }
    };
    for( const auto &i : values ) {
        if( rad <= i.first ) {
            return i.second.translated();
        }
    }
    return values.back().second.translated();
}
References rad, to_translation(), and translation::translated().
Referenced by item::armor_fit_info(), and Character::irradiate().
Variable Documentation
nolight
light_emission nolight extern
Definition at line 312 of file item.cpp.
Referenced by item::io().