Cataclysm BN: src/item_search.cpp File Reference
item_search.cpp File Reference
#include "item_search.h"
#include <map>
#include <utility>
#include "cata_utility.h"
#include "item.h"
#include "item_category.h"
#include "item_factory.h"
#include "material.h"
#include "requirements.h"
#include "skill.h"
#include "string_id.h"
#include "type_id.h"
Functions
std::pair< std::string, std::string > get_both (const std::string &a)
std::function< bool(const item &)> basic_item_filter (std::string filter)
Get a function that returns true if the value matches the basic query (no commas or minuses).
std::function< bool(const item &)> item_filter_from_string (const std::string &filter)
Get a function that returns true if the item matches the query.
Function Documentation
basic_item_filter()
std::function< bool(const item &)> basic_item_filter (std::string filter)
Get a function that returns true if the value matches the basic query (no commas or minuses).
Definition at line 18 of file item_search.cpp.
{
    size_t colon;
    char flag = '\0';
    if( ( colon = filter.find( ':' ) ) != std::string::npos ) {
        if( colon >= 1 ) {
            flag = filter[colon - 1];
            filter = filter.substr( colon + 1 );
        }
    }
    switch( flag ) {
        // category
        case 'c':
            return [filter]( const item & i ) {
                return lcmatch( i.get_category().name(), filter );
            };
        // material
        case 'm':
            return [filter]( const item & i ) {
                return std::any_of( i.made_of().begin(), i.made_of().end(),
                [&filter]( const material_id & mat ) {
                    return lcmatch( mat->name(), filter );
                } );
            };
        // qualities
        case 'q':
            return [filter]( const item & i ) {
                return std::any_of( i.quality_of().begin(), i.quality_of().end(),
                [&filter]( const std::pair<quality_id, int> &e ) {
                    return lcmatch( e.first->name, filter );
                } );
            };
        // both
        case 'b':
            return [filter]( const item & i ) {
                auto pair = get_both( filter );
                return item_filter_from_string( pair.first )( i )
                       && item_filter_from_string( pair.second )( i );
            };
        // disassembled components
        case 'd':
            return [filter]( const item & i ) {
                const auto &components = i.get_uncraft_components();
                for( auto &component : components ) {
                    if( lcmatch( component.to_string(), filter ) ) {
                        return true;
                    }
                }
                return false;
            };
        // item notes
        case 'n':
            return [filter]( const item & i ) {
                const std::string note = i.get_var( "item_note" );
                return !note.empty() && lcmatch( note, filter );
            };
        // skill taught
        case 'k':
            return [filter]( const item & i ) {
                if( i.is_book() ) {
                    const islot_book &book = *i.type->book;
                    return lcmatch( book.skill->name(), filter );
                }
                return false;
            };
        // by name
        default:
            return [filter]( const item & a ) {
                return lcmatch( a.tname(), filter );
            };
    }
}
References a, get_both(), item_filter_from_string(), lcmatch(), Skill::name(), and islot_book::skill.
Referenced by inventory_selector_preset::get_filter(), and item_filter_from_string().
get_both()
std::pair< std::string, std::string > get_both (const std::string & a)
Definition at line 96 of file item_search.cpp.
{
    size_t split_mark = a.find( ';' );
    return std::make_pair( a.substr( 0, split_mark - 1 ),
                           a.substr( split_mark + 1 ) );
}
References a.
Referenced by basic_item_filter().
item_filter_from_string()
std::function< bool(const item &)> item_filter_from_string (const std::string & filter)
Get a function that returns true if the item matches the query.
Definition at line 91 of file item_search.cpp.
{
    return filter_from_string<item>( filter, basic_item_filter );
}
References basic_item_filter().
Referenced by basic_item_filter(), zone_manager::custom_loot_has(), filter_item_stacks(), advanced_inventory_pane::is_filtered(), list_filter_high_priority(), list_filter_low_priority(), and pickup::pick_up().