Cataclysm BN: src/item_search.h File Reference
item_search.h File Reference
#include <cstddef>
#include <algorithm>
#include <functional>
#include <string>
#include <vector>
#include "string_utils.h"
Macros
#define CATA_SRC_ITEM_SEARCH_H
Functions
template<typename T >
std::function< bool(const T &)> filter_from_string (std::string filter, std::function< std::function< bool(const T &)>(const std::string &)> basic_filter)
Get a function that returns true if the value matches the query.
std::function< bool(const item &)> item_filter_from_string (const std::string &filter)
Get a function that returns true if the item matches the query.
std::function< bool(const item &)> basic_item_filter (std::string filter)
Get a function that returns true if the value matches the basic query (no commas or minuses).
Macro Definition Documentation
CATA_SRC_ITEM_SEARCH_H
#define CATA_SRC_ITEM_SEARCH_H
Definition at line 3 of file item_search.h.
Function Documentation
basic_item_filter()
std::function< bool(const item &)> basic_item_filter (std::string filter)
Get a function that returns true if the value matches the basic query (no commas or minuses).
Definition at line 18 of file item_search.cpp.
{
    size_t colon;
    char flag = '\0';
    if( ( colon = filter.find( ':' ) ) != std::string::npos ) {
        if( colon >= 1 ) {
            flag = filter[colon - 1];
            filter = filter.substr( colon + 1 );
        }
    }
    switch( flag ) {
        // category
        case 'c':
            return [filter]( const item & i ) {
                return lcmatch( i.get_category().name(), filter );
            };
        // material
        case 'm':
            return [filter]( const item & i ) {
                return std::any_of( i.made_of().begin(), i.made_of().end(),
                [&filter]( const material_id & mat ) {
                    return lcmatch( mat->name(), filter );
                } );
            };
        // qualities
        case 'q':
            return [filter]( const item & i ) {
                return std::any_of( i.quality_of().begin(), i.quality_of().end(),
                [&filter]( const std::pair<quality_id, int> &e ) {
                    return lcmatch( e.first->name, filter );
                } );
            };
        // both
        case 'b':
            return [filter]( const item & i ) {
                auto pair = get_both( filter );
                return item_filter_from_string( pair.first )( i )
                       && item_filter_from_string( pair.second )( i );
            };
        // disassembled components
        case 'd':
            return [filter]( const item & i ) {
                const auto &components = i.get_uncraft_components();
                for( auto &component : components ) {
                    if( lcmatch( component.to_string(), filter ) ) {
                        return true;
                    }
                }
                return false;
            };
        // item notes
        case 'n':
            return [filter]( const item & i ) {
                const std::string note = i.get_var( "item_note" );
                return !note.empty() && lcmatch( note, filter );
            };
        // skill taught
        case 'k':
            return [filter]( const item & i ) {
                if( i.is_book() ) {
                    const islot_book &book = *i.type->book;
                    return lcmatch( book.skill->name(), filter );
                }
                return false;
            };
        // by name
        default:
            return [filter]( const item & a ) {
                return lcmatch( a.tname(), filter );
            };
    }
}
References a, get_both(), item_filter_from_string(), lcmatch(), Skill::name(), and islot_book::skill.
Referenced by inventory_selector_preset::get_filter(), and item_filter_from_string().
filter_from_string()
template<typename T > std::function< bool(const T &)> filter_from_string (std::string filter, std::function< std::function< bool(const T &)>(const std::string &)> basic_filter)
Get a function that returns true if the value matches the query.
Definition at line 17 of file item_search.h.
{
    if( filter.empty() ) {
        // Variable without name prevents unused parameter warning
        return []( const T & ) {
            return true;
        };
    }
    // remove curly braces (they only get in the way)
    if( filter.find( '{' ) != std::string::npos ) {
        filter.erase( std::remove( filter.begin(), filter.end(), '{' ), filter.end() );
    }
    if( filter.find( '}' ) != std::string::npos ) {
        filter.erase( std::remove( filter.begin(), filter.end(), '}' ), filter.end() );
    }
    if( filter.find( ',' ) != std::string::npos ) {
        // functions which only one of which must return true
        std::vector<std::function<bool( const T & )> > functions;
        // Functions that must all return true
        std::vector<std::function<bool( const T & )> > inv_functions;
        size_t comma = filter.find( ',' );
        while( !filter.empty() ) {
            const auto &current_filter = trim( filter.substr( 0, comma ) );
            if( !current_filter.empty() ) {
                auto current_func = filter_from_string( current_filter, basic_filter );
                if( current_filter[0] == '-' ) {
                    inv_functions.push_back( current_func );
                } else {
                    functions.push_back( current_func );
                }
            }
            if( comma != std::string::npos ) {
                filter = trim( filter.substr( comma + 1 ) );
                comma = filter.find( ',' );
            } else {
                break;
            }
        }
        return [functions, inv_functions]( const T & it ) {
            auto apply = [&]( const std::function<bool( const T & )> &func ) {
                return func( it );
            };
            const bool p_result = std::any_of( functions.begin(), functions.end(),
                                               apply );
            const bool n_result = std::all_of(
                                      inv_functions.begin(),
                                      inv_functions.end(),
                                      apply );
            if( !functions.empty() && inv_functions.empty() ) {
                return p_result;
            }
            if( functions.empty() && !inv_functions.empty() ) {
                return n_result;
            }
            return p_result && n_result;
        };
    }
    const bool exclude = filter[0] == '-';
    if( exclude ) {
        return [filter, basic_filter]( const T & i ) {
            return !filter_from_string( filter.substr( 1 ), basic_filter )( i );
        };
    }
    return basic_filter( filter );
}
References apply(), filter_from_string(), and trim().
Referenced by filter_from_string().
item_filter_from_string()
std::function< bool(const item &)> item_filter_from_string (const std::string & filter)
Get a function that returns true if the item matches the query.
Definition at line 91 of file item_search.cpp.
{
    return filter_from_string<item>( filter, basic_item_filter );
}
References basic_item_filter().
Referenced by basic_item_filter(), zone_manager::custom_loot_has(), filter_item_stacks(), advanced_inventory_pane::is_filtered(), list_filter_high_priority(), list_filter_low_priority(), and pickup::pick_up().