var itype_8h =
[
    [ "gun_modifier_data", "classgun__modifier__data.html", "classgun__modifier__data" ],
    [ "gunmod_location", "classgunmod__location.html", "classgunmod__location" ],
    [ "islot_tool", "structislot__tool.html", "structislot__tool" ],
    [ "islot_comestible", "structislot__comestible.html", "structislot__comestible" ],
    [ "islot_brewable", "structislot__brewable.html", "structislot__brewable" ],
    [ "islot_container", "structislot__container.html", "structislot__container" ],
    [ "islot_armor", "structislot__armor.html", "structislot__armor" ],
    [ "islot_pet_armor", "structislot__pet__armor.html", "structislot__pet__armor" ],
    [ "islot_book", "structislot__book.html", "structislot__book" ],
    [ "islot_book::recipe_with_description_t", "structislot__book_1_1recipe__with__description__t.html", "structislot__book_1_1recipe__with__description__t" ],
    [ "islot_mod", "structislot__mod.html", "structislot__mod" ],
    [ "common_ranged_data", "structcommon__ranged__data.html", "structcommon__ranged__data" ],
    [ "islot_engine", "structislot__engine.html", "structislot__engine" ],
    [ "islot_wheel", "structislot__wheel.html", "structislot__wheel" ],
    [ "fuel_explosion", "structfuel__explosion.html", "structfuel__explosion" ],
    [ "islot_fuel", "structislot__fuel.html", "structislot__fuel" ],
    [ "islot_gun", "structislot__gun.html", "structislot__gun" ],
    [ "gun_type_type", "classgun__type__type.html", "classgun__type__type" ],
    [ "std::hash< gun_type_type >", "structstd_1_1hash_3_01gun__type__type_01_4.html", "structstd_1_1hash_3_01gun__type__type_01_4" ],
    [ "islot_gunmod", "structislot__gunmod.html", "structislot__gunmod" ],
    [ "islot_magazine", "structislot__magazine.html", "structislot__magazine" ],
    [ "islot_battery", "structislot__battery.html", "structislot__battery" ],
    [ "islot_ammo", "structislot__ammo.html", "structislot__ammo" ],
    [ "islot_bionic", "structislot__bionic.html", "structislot__bionic" ],
    [ "islot_seed", "structislot__seed.html", "structislot__seed" ],
    [ "islot_artifact", "structislot__artifact.html", "structislot__artifact" ],
    [ "enum_traits< condition_type >", "structenum__traits_3_01condition__type_01_4.html", "structenum__traits_3_01condition__type_01_4" ],
    [ "conditional_name", "structconditional__name.html", "structconditional__name" ],
    [ "islot_milling", "classislot__milling.html", "classislot__milling" ],
    [ "itype", "structitype.html", "structitype" ],
    [ "CATA_SRC_ITYPE_H", "itype_8h.html#ace8a6e1e7fecf6448f065604b34e2195", null ],
    [ "condition_type", "itype_8h.html#afc401f615ea14e8e1ee24cf7068b7716", [
      [ "FLAG", "itype_8h.html#afc401f615ea14e8e1ee24cf7068b7716a391ad3dbcf1f6d5c27590a7e511a1667", null ],
      [ "COMPONENT_ID", "itype_8h.html#afc401f615ea14e8e1ee24cf7068b7716a0232b08080d33dfe8f01eb0b16c09492", null ],
      [ "num_condition_types", "itype_8h.html#afc401f615ea14e8e1ee24cf7068b7716aa76e4df6fe28cbd3f3c95e56f20637a5", null ]
    ] ]
];