Cataclysm BN: src/iuse.h File Reference
iuse.h File Reference
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "clone_ptr.h"
#include "type_id.h"
#include "units.h"
Classes
struct washing_requirements
class iuse_actor
struct use_function
Namespaces
namespace iuse
Macros
#define CATA_SRC_IUSE_H
Typedefs
using use_function_pointer = int(*)(player *, item *, bool, const tripoint &)
Functions
int iuse::sewage (player *, item *, bool, const tripoint &)
int iuse::honeycomb (player *, item *, bool, const tripoint &)
int iuse::alcohol_weak (player *, item *, bool, const tripoint &)
int iuse::alcohol_medium (player *, item *, bool, const tripoint &)
int iuse::alcohol_strong (player *, item *, bool, const tripoint &)
int iuse::xanax (player *, item *, bool, const tripoint &)
int iuse::smoking (player *, item *, bool, const tripoint &)
Entry point for intentional bodily intake of smoke via paper wrapped one time use items: cigars, cigarettes, etc.
int iuse::ecig (player *, item *, bool, const tripoint &)
int iuse::antibiotic (player *, item *, bool, const tripoint &)
int iuse::eyedrops (player *, item *, bool, const tripoint &)
int iuse::fungicide (player *, item *, bool, const tripoint &)
int iuse::antifungal (player *, item *, bool, const tripoint &)
int iuse::antiparasitic (player *, item *, bool, const tripoint &)
int iuse::anticonvulsant (player *, item *, bool, const tripoint &)
int iuse::weed_cake (player *, item *, bool, const tripoint &)
int iuse::meth (player *, item *, bool, const tripoint &)
int iuse::vaccine (player *, item *, bool, const tripoint &)
int iuse::poison (player *, item *, bool, const tripoint &)
int iuse::meditate (player *, item *, bool, const tripoint &)
int iuse::thorazine (player *, item *, bool, const tripoint &)
int iuse::prozac (player *, item *, bool, const tripoint &)
int iuse::sleep (player *, item *, bool, const tripoint &)
int iuse::datura (player *, item *, bool, const tripoint &)
int iuse::flumed (player *, item *, bool, const tripoint &)
int iuse::flusleep (player *, item *, bool, const tripoint &)
int iuse::inhaler (player *, item *, bool, const tripoint &)
int iuse::blech (player *, item *, bool, const tripoint &)
int iuse::blech_because_unclean (player *, item *, bool, const tripoint &)
int iuse::plantblech (player *, item *, bool, const tripoint &)
int iuse::chew (player *, item *, bool, const tripoint &)
int iuse::purifier (player *, item *, bool, const tripoint &)
int iuse::purify_iv (player *, item *, bool, const tripoint &)
int iuse::purify_smart (player *, item *, bool, const tripoint &)
int iuse::marloss (player *, item *, bool, const tripoint &)
int iuse::marloss_seed (player *, item *, bool, const tripoint &)
int iuse::marloss_gel (player *, item *, bool, const tripoint &)
int iuse::mycus (player *, item *, bool, const tripoint &)
int iuse::dogfood (player *, item *, bool, const tripoint &)
int iuse::catfood (player *, item *, bool, const tripoint &)
int iuse::feedcattle (player *, item *, bool, const tripoint &)
int iuse::feedbird (player *, item *, bool, const tripoint &)
int iuse::antiasthmatic (player *, item *, bool, const tripoint &)
int iuse::extinguisher (player *, item *, bool, const tripoint &)
int iuse::hammer (player *, item *, bool, const tripoint &)
int iuse::water_purifier (player *, item *, bool, const tripoint &)
int iuse::directional_antenna (player *, item *, bool, const tripoint &)
int iuse::radio_off (player *, item *, bool, const tripoint &)
int iuse::radio_on (player *, item *, bool, const tripoint &)
int iuse::noise_emitter_off (player *, item *, bool, const tripoint &)
int iuse::noise_emitter_on (player *, item *, bool, const tripoint &)
int iuse::note_bionics (player *, item *, bool, const tripoint &)
int iuse::ma_manual (player *, item *, bool, const tripoint &)
int iuse::crowbar (player *, item *, bool, const tripoint &)
int iuse::makemound (player *, item *, bool, const tripoint &)
int iuse::dig (player *, item *, bool, const tripoint &)
int iuse::dig_channel (player *, item *, bool, const tripoint &)
int iuse::fill_pit (player *, item *, bool, const tripoint &)
int iuse::clear_rubble (player *, item *, bool, const tripoint &)
Explanation of ACT_CLEAR_RUBBLE activity values:
int iuse::siphon (player *, item *, bool, const tripoint &)
int iuse::chainsaw_off (player *, item *, bool, const tripoint &)
int iuse::chainsaw_on (player *, item *, bool, const tripoint &)
int iuse::elec_chainsaw_off (player *, item *, bool, const tripoint &)
int iuse::elec_chainsaw_on (player *, item *, bool, const tripoint &)
int iuse::cs_lajatang_off (player *, item *, bool, const tripoint &)
int iuse::cs_lajatang_on (player *, item *, bool, const tripoint &)
int iuse::ecs_lajatang_off (player *, item *, bool, const tripoint &)
int iuse::ecs_lajatang_on (player *, item *, bool, const tripoint &)
int iuse::carver_off (player *, item *, bool, const tripoint &)
int iuse::carver_on (player *, item *, bool, const tripoint &)
int iuse::trimmer_off (player *, item *, bool, const tripoint &)
int iuse::trimmer_on (player *, item *, bool, const tripoint &)
int iuse::circsaw_on (player *, item *, bool, const tripoint &)
int iuse::combatsaw_off (player *, item *, bool, const tripoint &)
int iuse::combatsaw_on (player *, item *, bool, const tripoint &)
int iuse::e_combatsaw_off (player *, item *, bool, const tripoint &)
int iuse::e_combatsaw_on (player *, item *, bool, const tripoint &)
int iuse::jackhammer (player *, item *, bool, const tripoint &)
int iuse::pickaxe (player *, item *, bool, const tripoint &)
int iuse::burrow (player *, item *, bool, const tripoint &)
int iuse::geiger (player *, item *, bool, const tripoint &)
int iuse::teleport (player *, item *, bool, const tripoint &)
int iuse::can_goo (player *, item *, bool, const tripoint &)
int iuse::throwable_extinguisher_act (player *, item *, bool, const tripoint &)
int iuse::directional_hologram (player *, item *, bool, const tripoint &)
int iuse::capture_monster_veh (player *, item *, bool, const tripoint &)
int iuse::capture_monster_act (player *, item *, bool, const tripoint &)
int iuse::granade (player *, item *, bool, const tripoint &)
int iuse::granade_act (player *, item *, bool, const tripoint &)
int iuse::c4 (player *, item *, bool, const tripoint &)
int iuse::arrow_flammable (player *, item *, bool, const tripoint &)
int iuse::acidbomb_act (player *, item *, bool, const tripoint &)
int iuse::grenade_inc_act (player *, item *, bool, const tripoint &)
int iuse::molotov_lit (player *, item *, bool, const tripoint &)
int iuse::firecracker_pack (player *, item *, bool, const tripoint &)
int iuse::firecracker_pack_act (player *, item *, bool, const tripoint &)
int iuse::firecracker (player *, item *, bool, const tripoint &)
int iuse::firecracker_act (player *, item *, bool, const tripoint &)
int iuse::mininuke (player *, item *, bool, const tripoint &)
int iuse::pheromone (player *, item *, bool, const tripoint &)
int iuse::portal (player *, item *, bool, const tripoint &)
int iuse::tazer (player *, item *, bool, const tripoint &)
int iuse::tazer2 (player *, item *, bool, const tripoint &)
int iuse::shocktonfa_off (player *, item *, bool, const tripoint &)
int iuse::shocktonfa_on (player *, item *, bool, const tripoint &)
int iuse::mp3 (player *, item *, bool, const tripoint &)
int iuse::mp3_on (player *, item *, bool, const tripoint &)
int iuse::rpgdie (player *, item *, bool, const tripoint &)
int iuse::dive_tank (player *, item *, bool, const tripoint &)
int iuse::gasmask (player *, item *, bool, const tripoint &)
int iuse::portable_game (player *, item *, bool, const tripoint &)
int iuse::fitness_check (player *p, item *it, bool, const tripoint &)
int iuse::vibe (player *, item *, bool, const tripoint &)
int iuse::hand_crank (player *, item *, bool, const tripoint &)
int iuse::vortex (player *, item *, bool, const tripoint &)
int iuse::dog_whistle (player *, item *, bool, const tripoint &)
int iuse::call_of_tindalos (player *, item *, bool, const tripoint &)
int iuse::blood_draw (player *, item *, bool, const tripoint &)
int iuse::mind_splicer (player *, item *, bool, const tripoint &)
void iuse::cut_log_into_planks (player &)
int iuse::lumber (player *, item *, bool, const tripoint &)
int iuse::chop_tree (player *, item *, bool, const tripoint &)
int iuse::chop_logs (player *, item *, bool, const tripoint &)
int iuse::oxytorch (player *, item *, bool, const tripoint &)
int iuse::hacksaw (player *, item *, bool, const tripoint &)
int iuse::boltcutters (player *, item *, bool, const tripoint &)
int iuse::mop (player *, item *, bool, const tripoint &)
int iuse::spray_can (player *, item *, bool, const tripoint &)
int iuse::towel (player *, item *, bool, const tripoint &)
int iuse::unfold_generic (player *, item *, bool, const tripoint &)
int iuse::adrenaline_injector (player *, item *, bool, const tripoint &)
int iuse::jet_injector (player *, item *, bool, const tripoint &)
int iuse::stimpack (player *, item *, bool, const tripoint &)
int iuse::contacts (player *, item *, bool, const tripoint &)
int iuse::talking_doll (player *, item *, bool, const tripoint &)
int iuse::bell (player *, item *, bool, const tripoint &)
int iuse::seed (player *, item *, bool, const tripoint &)
int iuse::oxygen_bottle (player *, item *, bool, const tripoint &)
int iuse::radio_mod (player *, item *, bool, const tripoint &)
int iuse::remove_all_mods (player *, item *, bool, const tripoint &)
int iuse::fishing_rod (player *, item *, bool, const tripoint &)
int iuse::fish_trap (player *, item *, bool, const tripoint &)
int iuse::gun_repair (player *, item *, bool, const tripoint &)
int iuse::gunmod_attach (player *, item *, bool, const tripoint &)
int iuse::toolmod_attach (player *, item *, bool, const tripoint &)
int iuse::rm13armor_off (player *, item *, bool, const tripoint &)
int iuse::rm13armor_on (player *, item *, bool, const tripoint &)
int iuse::unpack_item (player *, item *, bool, const tripoint &)
int iuse::pack_cbm (player *p, item *it, bool, const tripoint &)
int iuse::pack_item (player *, item *, bool, const tripoint &)
int iuse::radglove (player *, item *, bool, const tripoint &)
int iuse::robotcontrol (player *, item *, bool, const tripoint &)
bool iuse::robotcontrol_can_target (player *, const monster &)
int iuse::einktabletpc (player *, item *, bool, const tripoint &)
int iuse::camera (player *, item *, bool, const tripoint &)
int iuse::ehandcuffs (player *, item *, bool, const tripoint &)
int iuse::foodperson (player *, item *, bool, const tripoint &)
int iuse::tow_attach (player *, item *, bool, const tripoint &)
int iuse::cable_attach (player *, item *, bool, const tripoint &)
int iuse::shavekit (player *, item *, bool, const tripoint &)
int iuse::hairkit (player *, item *, bool, const tripoint &)
int iuse::weather_tool (player *, item *, bool, const tripoint &)
int iuse::ladder (player *, item *, bool, const tripoint &)
int iuse::wash_soft_items (player *, item *, bool, const tripoint &)
int iuse::wash_hard_items (player *, item *, bool, const tripoint &)
int iuse::wash_all_items (player *, item *, bool, const tripoint &)
int iuse::solarpack (player *, item *, bool, const tripoint &)
int iuse::solarpack_off (player *, item *, bool, const tripoint &)
int iuse::weak_antibiotic (player *, item *, bool, const tripoint &)
int iuse::strong_antibiotic (player *, item *, bool, const tripoint &)
int iuse::melatonin_tablet (player *, item *, bool, const tripoint &)
int iuse::coin_flip (player *, item *, bool, const tripoint &)
int iuse::play_game (player *, item *, bool, const tripoint &)
int iuse::magic_8_ball (player *, item *, bool, const tripoint &)
int iuse::toggle_heats_food (player *, item *, bool, const tripoint &)
int iuse::report_grid_charge (player *, item *, bool, const tripoint &)
int iuse::report_grid_connections (player *, item *, bool, const tripoint &)
int iuse::radiocar (player *, item *, bool, const tripoint &)
int iuse::radiocaron (player *, item *, bool, const tripoint &)
int iuse::radiocontrol (player *, item *, bool, const tripoint &)
int iuse::autoclave (player *, item *, bool, const tripoint &)
int iuse::multicooker (player *, item *, bool, const tripoint &)
int iuse::remoteveh (player *, item *, bool, const tripoint &)
int iuse::craft (player *, item *, bool, const tripoint &)
int iuse::disassemble (player *, item *, bool, const tripoint &)
int iuse::artifact (player *, item *, bool, const tripoint &)
void iuse::play_music (player &p, const tripoint &source, int volume, int max_morale)
int iuse::towel_common (player *, item *, bool)
int iuse::handle_ground_graffiti (player &p, item *it, const std::string &prefix, const tripoint &where)
int iuse::chop_moves (Character &ch, item &tool)
int iuse::cauterize_hotplate (player *, item *, bool, const tripoint &)
void remove_radio_mod (item &it, player &p)
washing_requirements washing_requirements_for_volume (const units::volume &)
Macro Definition Documentation
CATA_SRC_IUSE_H
#define CATA_SRC_IUSE_H
Definition at line 3 of file iuse.h.
Typedef Documentation
use_function_pointer
using use_function_pointer = int (*)(player *, item *, bool, const tripoint &)
Definition at line 254 of file iuse.h.
Function Documentation
remove_radio_mod()
void remove_radio_mod (item & it, player & p)
Definition at line 419 of file iuse.cpp.
{
    if( !it.has_flag( "RADIO_MOD" ) ) {
        return;
    }
    p.add_msg_if_player( _( "You remove the radio modification from your %s!" ), it.tname() );
    item mod( "radio_mod" );
    p.i_add_or_drop( mod, 1 );
    it.unset_flag( "RADIO_ACTIVATION" );
    it.unset_flag( "RADIO_MOD" );
    it.unset_flag( "RADIOSIGNAL_1" );
    it.unset_flag( "RADIOSIGNAL_2" );
    it.unset_flag( "RADIOSIGNAL_3" );
    it.unset_flag( "RADIOCARITEM" );
}
References _, player::add_msg_if_player(), item::has_flag(), Character::i_add_or_drop(), item::tname(), and item::unset_flag().
Referenced by crafting::complete_disassemble(), and iuse::radio_mod().
washing_requirements_for_volume()
washing_requirements washing_requirements_for_volume (const units::volume & vol)
Definition at line 9382 of file iuse.cpp.
{
    int water = divide_round_up( vol, 125_ml );
    int cleanser = divide_round_up( vol, 1_liter );
    int time = to_moves<int>( 10_seconds * ( vol / 250_ml ) );
    return { water, cleanser, time };
}
References divide_round_up(), and time.
Referenced by wash_activity_actor::finish(), game_menus::inv::multiwash(), and wash_items().