Cataclysm BN: src/iuse.cpp File Reference
iuse.cpp File Reference
#include "iuse.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <exception>
#include <functional>
#include <iterator>
#include <list>
#include <map>
#include <set>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "action.h"
#include "activity_actor.h"
#include "activity_actor_definitions.h"
#include "active_tile_data_def.h"
#include "animation.h"
#include "artifact.h"
#include "avatar.h"
#include "avatar_action.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "colony.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "crafting.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "distribution_grid.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "fstream_utils.h"
#include "flat_set.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "iexamine.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "iteminfo_query.h"
#include "itype.h"
#include "iuse_actor.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "martialarts.h"
#include "memorial_logger.h"
#include "memory_fast.h"
#include "messages.h"
#include "monattack.h"
#include "mongroup.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "omdata.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "pldata.h"
#include "point.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "sounds.h"
#include "speech.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "teleport.h"
#include "text_snippets.h"
#include "timed_event.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "visitable.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weather_gen.h"
#include "iuse_software.h"
Classes
struct digging_moves_and_byproducts
struct extended_photo_def
struct object_names_collection
Enumerations
enum Petfood { DOGFOOD , CATFOOD , CATTLEFODDER , BIRDFOOD }
Functions
static const std::string flag_ACID ("ACID")
static const std::string flag_CURRENT ("CURRENT")
static const std::string flag_DIGGABLE ("DIGGABLE")
static const std::string flag_FISHABLE ("FISHABLE")
static const std::string flag_FIX_FARSIGHT ("FIX_FARSIGHT")
static const std::string flag_HEATS_FOOD ("HEATS_FOOD")
static const std::string flag_PLANT ("PLANT")
static const std::string flag_PLOWABLE ("PLOWABLE")
static void item_save_monsters (player &p, item &it, const std::vector< monster * > &monster_vec, int photo_quality)
static bool show_photo_selection (player &p, item &it, const std::string &var_name)
static bool item_read_extended_photos (item &, std::vector< extended_photo_def > &, const std::string &, bool=false)
static void item_write_extended_photos (item &, const std::vector< extended_photo_def > &, const std::string &)
static std::string format_object_pair (const std::pair< std::string, int > &pair, const std::string &article)
static std::string format_object_pair_article (const std::pair< std::string, int > &pair)
static std::string format_object_pair_no_article (const std::pair< std::string, int > &pair)
static std::string colorized_field_description_at (const tripoint &point)
static std::string colorized_trap_name_at (const tripoint &point)
static std::string colorized_ter_name_flags_at (const tripoint &point, const std::vector< std::string > &flags={}, const std::vector< ter_str_id > &ter_whitelist={})
static std::string colorized_feature_description_at (const tripoint &center_point, bool &item_found, const units::volume &min_visible_volume)
static std::string colorized_item_name (const item &item)
static std::string colorized_item_description (const item &item)
static item get_top_item_at_point (const tripoint &point, const units::volume &min_visible_volume)
static std::string effects_description_for_creature (Creature *creature, std::string &pose, const std::string &pronoun_sex)
static object_names_collection enumerate_objects_around_point (const tripoint &point, int radius, const tripoint &bounds_center_point, int bounds_radius, const tripoint &camera_pos, const units::volume &min_visible_volume, bool create_figure_desc, std::unordered_set< tripoint > &ignored_points, std::unordered_set< const vehicle * > &vehicles_recorded)
static extended_photo_def photo_def_for_camera_point (const tripoint &aim_point, const tripoint &camera_pos, std::vector< monster * > &monster_vec, std::vector< player * > &player_vec)
void remove_radio_mod (item &it, player &p)
static bool check_litcig (player &u)
static constexpr time_duration alc_strength (const int strength, const time_duration &weak, const time_duration &medium, const time_duration &strong)
static int alcohol (player &p, const item &it, const int strength)
static void do_purify (player &p)
static void spawn_spores (const player &p)
static void marloss_common (player &p, item &it, const trait_id &current_color)
static bool marloss_prevented (const player &p)
static int feedpet (player &p, monster &mon, item &it, m_flag food_flag, const char *message)
static int petfood (player &p, item &it, Petfood animal_food_type)
static bool good_fishing_spot (tripoint pos)
static digging_moves_and_byproducts dig_pit_moves_and_byproducts (player *p, item *it, bool deep, bool channel)
void act_vehicle_siphon (vehicle *)
static int toolweapon_off (player &p, item &it, const bool fast_startup, const bool condition, const int volume, const std::string &msg_success, const std::string &msg_failure)
static int toolweapon_on (player &p, item &it, const bool t, const std::string &tname, const bool works_underwater, const int sound_chance, const int volume, const std::string &sound, const bool double_charge_cost=false)
static std::string get_music_description ()
static void init_memory_card_with_random_stuff (item &it)
static bool einkpc_download_memory_card (player &p, item &eink, item &mc)
static std::string photo_quality_name (const int index)
static void emit_radio_signal (player &p, const std::string &signal)
Send radio signal from player.
static bool hackveh (player &p, item &it, vehicle &veh)
static vehicle * pickveh (const tripoint &center, bool advanced)
static bool multicooker_hallu (player &p)
washing_requirements washing_requirements_for_volume (const units::volume &vol)
static int wash_items (player *p, bool soft_items, bool hard_items)
Variables
static const activity_id ACT_BURROW ("ACT_BURROW")
static const activity_id ACT_CHOP_LOGS ("ACT_CHOP_LOGS")
static const activity_id ACT_CHOP_PLANKS ("ACT_CHOP_PLANKS")
static const activity_id ACT_CHOP_TREE ("ACT_CHOP_TREE")
static const activity_id ACT_CHURN ("ACT_CHURN")
static const activity_id ACT_CLEAR_RUBBLE ("ACT_CLEAR_RUBBLE")
static const activity_id ACT_CRAFT ("ACT_CRAFT")
static const activity_id ACT_FILL_PIT ("ACT_FILL_PIT")
static const activity_id ACT_FISH ("ACT_FISH")
static const activity_id ACT_GAME ("ACT_GAME")
static const activity_id ACT_GENERIC_GAME ("ACT_GENERIC_GAME")
static const activity_id ACT_HACKSAW ("ACT_HACKSAW")
static const activity_id ACT_HAIRCUT ("ACT_HAIRCUT")
static const activity_id ACT_HAND_CRANK ("ACT_HAND_CRANK")
static const activity_id ACT_JACKHAMMER ("ACT_JACKHAMMER")
static const activity_id ACT_MEDITATE ("ACT_MEDITATE")
static const activity_id ACT_MIND_SPLICER ("ACT_MIND_SPLICER")
static const activity_id ACT_OXYTORCH ("ACT_OXYTORCH")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_PRY_NAILS ("ACT_PRY_NAILS")
static const activity_id ACT_ROBOT_CONTROL ("ACT_ROBOT_CONTROL")
static const activity_id ACT_SHAVE ("ACT_SHAVE")
static const activity_id ACT_VIBE ("ACT_VIBE")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_antibiotic ("antibiotic")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_attention ("attention")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bloodworms ("bloodworms")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_brainworms ("brainworms")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_corroding ("corroding")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_datura ("datura")
static const efftype_id effect_dazed ("dazed")
static const efftype_id effect_dermatik ("dermatik")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_earphones ("earphones")
static const efftype_id effect_foodpoison ("foodpoison")
static const efftype_id effect_formication ("formication")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_glowing ("glowing")
static const efftype_id effect_glowy_led ("glowy_led")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_happy ("happy")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_has_bag ("has_bag")
static const efftype_id effect_haslight ("haslight")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_jetinjector ("jetinjector")
static const efftype_id effect_lack_sleep ("lack_sleep")
static const efftype_id effect_laserlocked ("laserlocked")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_melatonin_supplements ("melatonin")
static const efftype_id effect_meth ("meth")
static const efftype_id effect_monster_armor ("monster_armor")
static const efftype_id effect_music ("music")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_paincysts ("paincysts")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_run ("run")
static const efftype_id effect_sad ("sad")
static const efftype_id effect_saddled ("monster_saddled")
static const efftype_id effect_sap ("sap")
static const efftype_id effect_shakes ("shakes")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_slimed ("slimed")
static const efftype_id effect_smoke ("smoke")
static const efftype_id effect_spores ("spores")
static const efftype_id effect_stimpack ("stimpack")
static const efftype_id effect_strong_antibiotic ("strong_antibiotic")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_tapeworm ("tapeworm")
static const efftype_id effect_teargas ("teargas")
static const efftype_id effect_teleglow ("teleglow")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_took_antiasthmatic ("took_antiasthmatic")
static const efftype_id effect_took_flumed ("took_flumed")
static const efftype_id effect_took_prozac ("took_prozac")
static const efftype_id effect_took_prozac_bad ("took_prozac_bad")
static const efftype_id effect_took_thorazine ("took_thorazine")
static const efftype_id effect_took_xanax ("took_xanax")
static const efftype_id effect_valium ("valium")
static const efftype_id effect_visuals ("visuals")
static const efftype_id effect_weak_antibiotic ("weak_antibiotic")
static const efftype_id effect_webbed ("webbed")
static const efftype_id effect_weed_high ("weed_high")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_advanced_ecig ("advanced_ecig")
static const itype_id itype_afs_atomic_smartphone ("afs_atomic_smartphone")
static const itype_id itype_afs_atomic_smartphone_music ("afs_atomic_smartphone_music")
static const itype_id itype_afs_wraitheon_smartphone ("afs_wraitheon_smartphone")
static const itype_id itype_afs_atomic_wraitheon_music ("afs_atomic_wraitheon_music")
static const itype_id itype_apparatus ("apparatus")
static const itype_id itype_arrow_flamming ("arrow_flamming")
static const itype_id itype_battery ("battery")
static const itype_id itype_barometer ("barometer")
static const itype_id itype_c4armed ("c4armed")
static const itype_id itype_canister_empty ("canister_empty")
static const itype_id itype_chainsaw_off ("chainsaw_off")
static const itype_id itype_chainsaw_on ("chainsaw_on")
static const itype_id itype_cig ("cig")
static const itype_id itype_cigar ("cigar")
static const itype_id itype_cow_bell ("cow_bell")
static const itype_id itype_data_card ("data_card")
static const itype_id itype_detergent ("detergent")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const itype_id itype_ecig ("ecig")
static const itype_id itype_fire ("fire")
static const itype_id itype_firecracker_act ("firecracker_act")
static const itype_id itype_firecracker_pack_act ("firecracker_pack_act")
static const itype_id itype_geiger_off ("geiger_off")
static const itype_id itype_geiger_on ("geiger_on")
static const itype_id itype_granade_act ("granade_act")
static const itype_id itype_handrolled_cig ("handrolled_cig")
static const itype_id itype_hygrometer ("hygrometer")
static const itype_id itype_joint ("joint")
static const itype_id itype_log ("log")
static const itype_id itype_mask_h20survivor_on ("mask_h20survivor_on")
static const itype_id itype_mininuke_act ("mininuke_act")
static const itype_id itype_molotov ("molotov")
static const itype_id itype_mobile_memory_card ("mobile_memory_card")
static const itype_id itype_mobile_memory_card_used ("mobile_memory_card_used")
static const itype_id itype_mp3 ("mp3")
static const itype_id itype_mp3_on ("mp3_on")
static const itype_id itype_multi_cooker ("multi_cooker")
static const itype_id itype_multi_cooker_filled ("multi_cooker_filled")
static const itype_id itype_nicotine_liquid ("nicotine_liquid")
static const itype_id itype_noise_emitter ("noise_emitter")
static const itype_id itype_noise_emitter_on ("noise_emitter_on")
static const itype_id itype_radio ("radio")
static const itype_id itype_radio_car ("radio_car")
static const itype_id itype_radio_car_on ("radio_car_on")
static const itype_id itype_radio_on ("radio_on")
static const itype_id itype_rebreather_on ("rebreather_on")
static const itype_id itype_rebreather_xl_on ("rebreather_xl_on")
static const itype_id itype_rmi2_corpse ("rmi2_corpse")
static const itype_id itype_shocktonfa_off ("shocktonfa_off")
static const itype_id itype_shocktonfa_on ("shocktonfa_on")
static const itype_id itype_smart_phone ("smart_phone")
static const itype_id itype_smartphone_music ("smartphone_music")
static const itype_id itype_soap ("soap")
static const itype_id itype_soldering_iron ("soldering_iron")
static const itype_id itype_spiral_stone ("spiral_stone")
static const itype_id itype_thermometer ("thermometer")
static const itype_id itype_towel ("towel")
static const itype_id itype_towel_soiled ("towel_soiled")
static const itype_id itype_towel_wet ("towel_wet")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_UPS_off ("UPS_off")
static const itype_id itype_water ("water")
static const itype_id itype_water_clean ("water_clean")
static const itype_id itype_wax ("wax")
static const itype_id itype_weather_reader ("weather_reader")
static const skill_id skill_computer ("computer")
static const skill_id skill_cooking ("cooking")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_mechanics ("mechanics")
static const skill_id skill_melee ("melee")
static const skill_id skill_survival ("survival")
static const trait_id trait_ACIDBLOOD ("ACIDBLOOD")
static const trait_id trait_ACIDPROOF ("ACIDPROOF")
static const trait_id trait_ALCMET ("ALCMET")
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_EATDEAD ("EATDEAD")
static const trait_id trait_GILLS ("GILLS")
static const trait_id trait_GILLS_CEPH ("GILLS_CEPH")
static const trait_id trait_HYPEROPIC ("HYPEROPIC")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_LIGHTWEIGHT ("LIGHTWEIGHT")
static const trait_id trait_M_DEPENDENT ("M_DEPENDENT")
static const trait_id trait_MARLOSS ("MARLOSS")
static const trait_id trait_MARLOSS_AVOID ("MARLOSS_AVOID")
static const trait_id trait_MARLOSS_BLUE ("MARLOSS_BLUE")
static const trait_id trait_MARLOSS_YELLOW ("MARLOSS_YELLOW")
static const trait_id trait_MYOPIC ("MYOPIC")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_POISRESIST ("POISRESIST")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_SAPROVORE ("SAPROVORE")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const trait_id trait_THRESH_PLANT ("THRESH_PLANT")
static const trait_id trait_TOLERANCE ("TOLERANCE")
static const trait_id trait_URSINE_EYE ("URSINE_EYE")
static const trait_id trait_WAYFARER ("WAYFARER")
static const quality_id qual_AXE ("AXE")
static const quality_id qual_DIG ("DIG")
static const species_id FUNGUS ("FUNGUS")
static const species_id HALLUCINATION ("HALLUCINATION")
static const species_id INSECT ("INSECT")
static const species_id ROBOT ("ROBOT")
static const species_id ZOMBIE ("ZOMBIE")
static const mongroup_id GROUP_FISH ("GROUP_FISH")
static const mtype_id mon_bee ("mon_bee")
static const mtype_id mon_blob ("mon_blob")
static const mtype_id mon_dog_thing ("mon_dog_thing")
static const mtype_id mon_fly ("mon_fly")
static const mtype_id mon_hallu_multicooker ("mon_hallu_multicooker")
static const mtype_id mon_hologram ("mon_hologram")
static const mtype_id mon_shadow ("mon_shadow")
static const mtype_id mon_spore ("mon_spore")
static const mtype_id mon_vortex ("mon_vortex")
static const mtype_id mon_wasp ("mon_wasp")
static const bionic_id bio_eye_optic ("bio_eye_optic")
static const bionic_id bio_shock ("bio_shock")
static constexpr int RADIO_PER_TURN = 25
static const std::vector< std::string > camera_ter_whitelist_flags
static const std::vector< ter_str_id > camera_ter_whitelist_types
Enumeration Type Documentation
Petfood
enum Petfood
Enumerator
DOGFOOD
CATFOOD
CATTLEFODDER
BIRDFOOD
Definition at line 1527 of file iuse.cpp.
             {
    DOGFOOD,
    CATFOOD,
    CATTLEFODDER,
    BIRDFOOD
};
Function Documentation
act_vehicle_siphon()
void act_vehicle_siphon (vehicle * veh)
Definition at line 2899 of file veh_interact.cpp.
{
    std::vector<itype_id> fuels;
    bool has_liquid = false;
    for( const vpart_reference &vp : veh->get_any_parts( VPFLAG_FLUIDTANK ) ) {
        if( vp.part().get_base().contents_made_of( LIQUID ) ) {
            has_liquid = true;
            break;
        }
    }
    if( !has_liquid ) {
        add_msg( m_info, _( "The vehicle has no liquid fuel left to siphon." ) );
        return;
    }
    std::string title = _( "Select tank to siphon:" );
    auto sel = []( const vehicle_part & pt ) {
        return pt.is_tank() && pt.get_base().contents_made_of( LIQUID );
    };
    vehicle_part &tank = veh_interact::select_part( *veh, sel, title );
    if( tank ) {
        const item &base = tank.get_base();
        const int idx = veh->find_part( base );
        item liquid( base.contents.back() );
        const int liq_charges = liquid.charges;
        if( liquid_handler::handle_liquid( liquid, nullptr, 1, nullptr, veh, idx ) ) {
            veh->drain( idx, liq_charges - liquid.charges );
            veh->invalidate_mass();
        }
    }
}
References _, add_msg(), item_contents::back(), item::charges, item::contents, vehicle::drain(), vehicle::find_part(), vehicle::get_any_parts(), vehicle_part::get_base(), liquid_handler::handle_liquid(), vehicle::invalidate_mass(), LIQUID, m_info, veh_interact::select_part(), PATH_INFO::title(), and VPFLAG_FLUIDTANK.
Referenced by iuse::siphon().
alc_strength()
static constexpr time_duration alc_strength (const int strength, const time_duration & weak, const time_duration & medium, const time_duration & strong) static constexpr
Definition at line 479 of file iuse.cpp.
{
    return strength == 0 ? weak : strength == 1 ? medium : strong;
}
Referenced by alcohol().
alcohol()
static int alcohol (player & p, const item & it, const int strength) static
Maximum Strength reduces drunkenness duration
Definition at line 485 of file iuse.cpp.
{
    // Weaker characters are cheap drunks
    /** @EFFECT_STR_MAX reduces drunkenness duration */
    time_duration duration = alc_strength( strength, 22_minutes, 34_minutes,
                                           45_minutes ) - ( alc_strength( strength, 36_seconds, 1_minutes, 72_seconds ) * p.str_max );
    if( p.has_trait( trait_ALCMET ) ) {
        duration = alc_strength( strength, 6_minutes, 14_minutes, 18_minutes ) - ( alc_strength( strength,
                   36_seconds, 1_minutes, 1_minutes ) * p.str_max );
        // Metabolizing the booze improves the nutritional value;
        // might not be healthy, and still causes Thirst problems, though
        p.mod_stored_kcal( 10 * ( std::abs( it.get_comestible() ? it.type->comestible->stim : 0 ) ) );
        // Metabolizing it cancels out the depressant
        p.mod_stim( std::abs( it.get_comestible() ? it.get_comestible()->stim : 0 ) );
    } else if( p.has_trait( trait_TOLERANCE ) ) {
        duration -= alc_strength( strength, 9_minutes, 16_minutes, 24_minutes );
    } else if( p.has_trait( trait_LIGHTWEIGHT ) ) {
        duration += alc_strength( strength, 9_minutes, 16_minutes, 24_minutes );
    }
    p.add_effect( effect_drunk, duration );
    return it.type->charges_to_use();
}
References Creature::add_effect(), alc_strength(), itype::charges_to_use(), itype::comestible, effect_drunk, item::get_comestible(), Character::has_trait(), Character::mod_stim(), Character::mod_stored_kcal(), Character::str_max, trait_ALCMET, trait_LIGHTWEIGHT, trait_TOLERANCE, and item::type.
Referenced by iuse::alcohol_medium(), iuse::alcohol_strong(), and iuse::alcohol_weak().
check_litcig()
static bool check_litcig (player & u) static
Definition at line 435 of file iuse.cpp.
{
    auto cigs = u.items_with( []( const item & it ) {
        return it.active && it.has_flag( "LITCIG" );
    } );
    if( cigs.empty() ) {
        return true;
    }
    u.add_msg_if_player( m_info, _( "You're already smoking a %s!" ), cigs[0]->tname() );
    return false;
}
References _, item::active, player::add_msg_if_player(), item::has_flag(), visitable< T >::items_with(), and m_info.
Referenced by iuse::smoking().
colorized_feature_description_at()
static std::string colorized_feature_description_at (const tripoint & center_point, bool & item_found, const units::volume & min_visible_volume) static
Definition at line 6812 of file iuse.cpp.
{
    item_found = false;
    const furn_id furn = g->m.furn( center_point );
    if( furn != f_null && furn.is_valid() ) {
        std::string furn_str = colorize( furn->name(), c_yellow );
        std::string sign_message = g->m.get_signage( center_point );
        if( !sign_message.empty() ) {
            furn_str += string_format( _( " with message \"%s\"" ), sign_message );
        }
        if( !furn->has_flag( "CONTAINER" ) && !furn->has_flag( "SEALED" ) ) {
            const item item = get_top_item_at_point( center_point, min_visible_volume );
            if( !item.is_null() ) {
                furn_str += string_format( _( " with %s on it" ), colorized_item_name( item ) );
                item_found = true;
            }
        }
        return furn_str;
    }
    return std::string();
}
References _, c_yellow, colorize(), colorized_item_name(), f_null, g, get_top_item_at_point(), map_data_common_t::has_flag(), item::is_null(), int_id< T >::is_valid(), map_data_common_t::name(), and string_format().
Referenced by enumerate_objects_around_point(), and photo_def_for_camera_point().
colorized_field_description_at()
static std::string colorized_field_description_at (const tripoint & point) static
Definition at line 6733 of file iuse.cpp.
{
    std::string field_text;
    const field &field = g->m.field_at( point );
    const field_entry *entry = field.find_field( field.displayed_field_type() );
    if( entry ) {
        field_text = string_format( _( description_affixes.at( field.displayed_description_affix() ) ),
                                    colorize( entry->name(), entry->color() ) );
    }
    return field_text;
}
References _, field_entry::color(), colorize(), description_affixes, field::displayed_description_affix(), field::displayed_field_type(), field::find_field(), g, field_entry::name(), and string_format().
Referenced by enumerate_objects_around_point(), and photo_def_for_camera_point().
colorized_item_description()
static std::string colorized_item_description (const item & item) static
Definition at line 6752 of file iuse.cpp.
{
    std::vector<iteminfo> dummy;
    iteminfo_query query = iteminfo_query(
    std::vector<iteminfo_parts> {
        iteminfo_parts::DESCRIPTION,
        iteminfo_parts::DESCRIPTION_NOTES,
        iteminfo_parts::DESCRIPTION_CONTENTS
    } );
    return item.info( dummy, &query, 1 );
}
References DESCRIPTION, DESCRIPTION_CONTENTS, DESCRIPTION_NOTES, and item::info().
Referenced by photo_def_for_camera_point().
colorized_item_name()
static std::string colorized_item_name (const item & item) static
Definition at line 6745 of file iuse.cpp.
{
    nc_color color = item.color_in_inventory();
    std::string damtext = item.damage() != 0 ? item.durability_indicator() : "";
    return damtext + colorize( item.tname( 1, false ), color );
}
References color(), item::color_in_inventory(), colorize(), item::damage(), item::durability_indicator(), and item::tname().
Referenced by colorized_feature_description_at(), enumerate_objects_around_point(), and photo_def_for_camera_point().
colorized_ter_name_flags_at()
static std::string colorized_ter_name_flags_at (const tripoint & point, const std::vector< std::string > & flags = {}, const std::vector< ter_str_id > & ter_whitelist = {}) static
Definition at line 6778 of file iuse.cpp.
{
    const ter_id ter = g->m.ter( point );
    std::string name = colorize( ter->name(), ter->color() );
    const std::string &graffiti_message = g->m.graffiti_at( point );
    if( !graffiti_message.empty() ) {
        name += string_format( _( " with graffiti \"%s\"" ), graffiti_message );
        return name;
    }
    if( ter_whitelist.empty() && flags.empty() ) {
        return name;
    }
    if( !ter->open.is_null() || ( ter->examine != iexamine::none &&
                                  ter->examine != iexamine::fungus &&
                                  ter->examine != iexamine::water_source &&
                                  ter->examine != iexamine::dirtmound ) ) {
        return name;
    }
    for( const ter_str_id &ter_good : ter_whitelist ) {
        if( ter->id == ter_good ) {
            return name;
        }
    }
    for( const std::string &flag : flags ) {
        if( ter->has_flag( flag ) ) {
            return name;
        }
    }
    return std::string();
}
References _, map_data_common_t::color(), colorize(), iexamine::dirtmound(), map_data_common_t::examine, iexamine::fungus(), g, map_data_common_t::has_flag(), ter_t::id, string_id< T >::is_null(), map_data_common_t::name(), om_direction::name(), iexamine::none(), ter_t::open, string_format(), and iexamine::water_source().
Referenced by enumerate_objects_around_point(), and photo_def_for_camera_point().
colorized_trap_name_at()
static std::string colorized_trap_name_at (const tripoint & point) static
Definition at line 6723 of file iuse.cpp.
{
    const trap &trap = g->m.tr_at( point );
    std::string name;
    if( !trap.is_null() && trap.get_visibility() <= 1 ) {
        name = colorize( trap.name(), trap.color ) + _( " on " );
    }
    return name;
}
References _, trap::color, colorize(), g, trap::get_visibility(), trap::is_null(), trap::name(), and om_direction::name().
Referenced by enumerate_objects_around_point(), and photo_def_for_camera_point().
dig_pit_moves_and_byproducts()
static digging_moves_and_byproducts dig_pit_moves_and_byproducts (player * p, item * it, bool deep, bool channel) static
Strength modifies dig rate
Definition at line 2589 of file iuse.cpp.
{
    // When we dig, we're generally digging out either a deep or shallow pit.
    //
    // The dimensions are a little hand-wavey... based on our exactly
    // as-big-as-they-need-to-be tile sizes, we could assume that the width and height
    // are 1 meter each. Our pit could be a square as well, or we could assume it's
    // circular and 1 meter in diameter.
    //
    // Depth is even less rigidly defined, both in terms of "what is a z-level", and in
    // terms of how the deep and shallow pits are used in game.
    //
    // A shallow pit gets used to do things like build an improvised shelter or start
    // the foundation for a wall, and is ostensibly a relatively quick effort: a
    // survivor might get a crude digging implement (e.g. digging stick) and attempt to
    // dig out the start of an improvised shelter, or they might have a proper shovel
    // and be digging a foundation footing. Referencing the 2018 IBC
    // https://codes.iccsafe.org/content/IRC2018/chapter-4-foundations we can see in
    // R403.1.4 the requirement that "exterior footings shall be placed not less than
    // 12 inches (305 mm) below the undisturbed ground surface. You'd need even more
    // space for the actual footing, but that's close enough. I don't think survivors
    // care about building to code, but let's call it 12 inches (0.3048 meters) at the
    // maximum for a shallow pit depth.
    //
    // The deep pit is a little more complicated because it gets used for more complex
    // constructions like traps, reinforced concrete wall footings, palisades, wells,
    // root cellars, and the like. The depth requirements for those are quite varied,
    // but let's just throw some number around to get a feel for it: say at least 2
    // meters deep to be an effective pit trap. The USGS maintains
    // depth-to-ground-water-level records and provides them at
    // https://waterdata.usgs.gov/nwis/current/?type=gw. A cursory review (and
    // remembering it's seasonal) shows values in Massachusetts ranging from 122 feet
    // and 1 foot, and values between 3 to 9 feet aren't uncommon. Root cellars are
    // ideally constructed where the ground temperature has stabilized, below the frost
    // line. This depth varies by location, but is somewhere in the 1 to 3 meter range.
    //
    // With all of that in hand, let's make some estimates.
    //
    // A shallow pit is a circular pit 1 meter in diameter and 0.3048 meters deep,
    // which works out to... ~0.239 m^3. That's so close, let's just call it 0.25 m^3
    // or 250 liters.
    //
    // A deep pit is a rectangular pit 1m x 1m x 2m, or 2 m^3, or 2000 liters.
    //
    // Now, for how long that takes, things are going to get even more subjective and
    // couched in assumptions. Let's assume a single individual, digging in optimally
    // diggable soil(rather than something requiring a pickaxe to break the soil or
    // requiring saws to remove tree roots), using an appropriate (but manual)
    // implement designed for the task (e.g. a shovel). The Canadian Centre for
    // Occupational Health and Safety has some interesting recommendations on the rate
    // of shoveling, weight of the load, and throw distance at
    // https://www.ccohs.ca/oshanswers/ergonomics/shovel.html. Of particular interest
    // is the table of "recommended workload for continuous shoveling", which gives a
    // weight per minute and a total weight per 15 minutes, as well as a description of
    // the conditions. It also discusses the need to take breaks, for example
    // alternating 15 minutes of shoveling and 15 minutes of rest in extreme
    // conditions. Taking all that into consideration, I'm going to call it 10
    // scoops/min * 5 kg/scoop for 15 minutes followed by 15 minutes of rest, or
    // effectively 25 kg/min.
    //
    // Now we need to bring the weights and volumes together. Again, more hand waving
    // as the soil composition is going to have a big influence on this. The
    // engineering toolbox https://www.engineeringtoolbox.com/dirt-mud-densities-d_1727.html
    // lists the density of wet and dry versions of many materials. I'm going with the
    // assumption that this is moist/wet soil that includes clay, silt, load, as well as
    // some rock, so I'll just call it 1700 kg/m^3 on average.
    //
    // Shallow pit is 0.25 m^3 * 1700 kg/m^3, or 425 kg.
    // Deep pit is 2 m^3 * 1700 kg/m^3, or 3400 kg.
    //
    // We'll do some variables below, but for reference:
    // Shallow pit: 425 kg / 25 kg/min = 17 minutes
    // Deep pit: 3400 kg / 25 kg/min = 136 minutes
    //
    // Now, one addendum: we're digging our deep pit in the location that we've already
    // dug the shallow pit, so really we should exclude the shallow pit volume from the
    // deep when counting the amount of work we need to do.
    //
    // Adjusted deep pit: ( 3400 kg - 425 kg ) / 25 kg/min = 119 minutes
    constexpr double shallow_pit_volume_m3 = 0.25;
    constexpr double deep_pit_volume_m3 = 2;
    constexpr int dig_rate_kg_min = 25;
    constexpr int material_density_kg_m3 = 1700;
    // At the time of writing this, a shovel is DIG 3, which is what the numbers are
    // balanced around.
    constexpr double baseline_dig_quality = 3;
    // Get the dig quality of the tool.
    const int quality = it->get_quality( qual_DIG );
    // Dig quality affects the dig rate linearly relative to baseline dig quality
    const double tool_dig_rate = dig_rate_kg_min * quality / baseline_dig_quality;
    ///\EFFECT_STR modifies dig rate
    // Adjust the dig rate by 2 kg/min per point of strength more/less than 10.
    const double player_dig_rate = std::max( 1.0, tool_dig_rate + ( p->str_cur - 10 ) * 2 );
    // Figure out the volume of the pit we're digging.
    // Subtract the shallow volume from the deep, since we already dug that.
    const double volume_m3 = deep ? ( deep_pit_volume_m3 - shallow_pit_volume_m3 ) :
                             shallow_pit_volume_m3;
    // And now determine the moves...
    int dig_minutes = volume_m3 * material_density_kg_m3 / player_dig_rate;
    int moves = to_moves<int>( time_duration::from_minutes( dig_minutes ) );
    ter_id result_terrain;
    if( channel ) {
        result_terrain = ter_id( "t_water_moving_sh" );
    } else {
        result_terrain = deep ? ter_id( "t_pit" ) : ter_id( "t_pit_shallow" );
    }
    return { moves, static_cast<int>( volume_m3 / 0.05 ), "digging_soil_loam_50L", result_terrain };
}
References time_duration::from_minutes(), item::get_quality(), qual_DIG, and Character::str_cur.
Referenced by iuse::dig(), and iuse::dig_channel().
do_purify()
static void do_purify (player & p) static
Definition at line 1105 of file iuse.cpp.
{
    std::vector<trait_id> valid; // Which flags the player has
    for( auto &traits_iter : mutation_branch::get_all() ) {
        if( p.has_trait( traits_iter.id ) && !p.has_base_trait( traits_iter.id ) ) {
            //Looks for active mutation
            valid.push_back( traits_iter.id );
        }
    }
    if( valid.empty() ) {
        p.add_msg_if_player( _( "You feel cleansed." ) );
        return;
    }
    int num_cured = rng( 1, valid.size() );
    num_cured = std::min( 4, num_cured );
    for( int i = 0; i < num_cured && !valid.empty(); i++ ) {
        const trait_id id = random_entry_removed( valid );
        if( id->purifiable ) {
            p.remove_mutation( id );
        } else {
            p.add_msg_if_player( m_warning, _( "You feel a slight itching inside, but it passes." ) );
        }
    }
}
References _, player::add_msg_if_player(), mutation_branch::get_all(), Character::has_base_trait(), Character::has_trait(), int_id< T >::id(), m_warning, random_entry_removed(), Character::remove_mutation(), and rng().
Referenced by iuse::granade_act(), and iuse::purifier().
effects_description_for_creature()
static std::string effects_description_for_creature (Creature * creature, std::string & pose, const std::string & pronoun_sex) static
Definition at line 6855 of file iuse.cpp.
{
    struct ef_con { // effect constraint
        translation status;
        translation pose;
        int intensity_lower_limit;
        ef_con( const translation &status, const translation &pose, int intensity_lower_limit ) :
            status( status ), pose( pose ), intensity_lower_limit( intensity_lower_limit ) {}
        ef_con( const translation &status, const translation &pose ) :
            status( status ), pose( pose ), intensity_lower_limit( 0 ) {}
        ef_con( const translation &status, int intensity_lower_limit ) :
            status( status ), intensity_lower_limit( intensity_lower_limit ) {}
        ef_con( const translation &status ) :
            status( status ), intensity_lower_limit( 0 ) {}
    };
    static const std::unordered_map<efftype_id, ef_con> vec_effect_status = {
        { effect_onfire, ef_con( to_translation( " is on <color_red>fire</color>. " ) ) },
        { effect_bleed, ef_con( to_translation( " is <color_red>bleeding</color>. " ), 1 ) },
        { effect_happy, ef_con( to_translation( " looks <color_green>happy</color>. " ), 13 ) },
        { effect_downed, ef_con( translation(), to_translation( "downed" ) ) },
        { effect_in_pit, ef_con( translation(), to_translation( "stuck" ) ) },
        { effect_stunned, ef_con( to_translation( " is <color_blue>stunned</color>. " ) ) },
        { effect_dazed, ef_con( to_translation( " is <color_blue>dazed</color>. " ) ) },
        { effect_beartrap, ef_con( to_translation( " is stuck in beartrap. " ) ) },
        { effect_laserlocked, ef_con( to_translation( " have tiny <color_red>red dot</color> on body. " ) ) },
        { effect_boomered, ef_con( to_translation( " is covered in <color_magenta>bile</color>. " ) ) },
        { effect_glowing, ef_con( to_translation( " is covered in <color_yellow>glowing goo</color>. " ) ) },
        { effect_slimed, ef_con( to_translation( " is covered in <color_green>thick goo</color>. " ) ) },
        { effect_corroding, ef_con( to_translation( " is covered in <color_light_green>acid</color>. " ) ) },
        { effect_sap, ef_con( to_translation( " is coated in <color_brown>sap</color>. " ) ) },
        { effect_webbed, ef_con( to_translation( " is covered in <color_dark_gray>webs</color>. " ) ) },
        { effect_spores, ef_con( to_translation( " is covered in <color_green>spores</color>. " ), 1 ) },
        { effect_crushed, ef_con( to_translation( " lies under <color_dark_gray>collapsed debris</color>. " ), to_translation( "lies" ) ) },
        { effect_lack_sleep, ef_con( to_translation( " looks <color_dark_gray>very tired</color>. " ) ) },
        { effect_lying_down, ef_con( to_translation( " is <color_dark_blue>sleeping</color>. " ), to_translation( "lies" ) ) },
        { effect_sleep, ef_con( to_translation( " is <color_dark_blue>sleeping</color>. " ), to_translation( "lies" ) ) },
        { effect_haslight, ef_con( to_translation( " is <color_yellow>lit</color>. " ) ) },
        { effect_saddled, ef_con( to_translation( " is <color_dark_gray>saddled</color>. " ) ) },
        { effect_harnessed, ef_con( to_translation( " is being <color_dark_gray>harnessed</color> by a vehicle. " ) ) },
        { effect_monster_armor, ef_con( to_translation( " is <color_dark_gray>wearing armor</color>. " ) ) },
        { effect_has_bag, ef_con( to_translation( " have <color_dark_gray>bag</color> attached. " ) ) },
        { effect_tied, ef_con( to_translation( " is <color_dark_gray>tied</color>. " ) ) },
        { effect_bouldering, ef_con( translation(), to_translation( "balancing" ) ) }
    };
    std::string figure_effects;
    if( creature ) {
        for( const auto &pair : vec_effect_status ) {
            if( creature->get_effect_int( pair.first ) > pair.second.intensity_lower_limit ) {
                if( !pair.second.status.empty() ) {
                    figure_effects += pronoun_sex + pair.second.status;
                }
                if( !pair.second.pose.empty() ) {
                    pose = pair.second.pose.translated();
                }
            }
        }
        if( creature->has_effect( effect_sad ) ) {
            int intensity = creature->get_effect_int( effect_sad );
            if( intensity > 500 && intensity <= 950 ) {
                figure_effects += pronoun_sex + pgettext( "Someone", " looks <color_blue>sad</color>. " );
            } else if( intensity > 950 ) {
                figure_effects += pronoun_sex + pgettext( "Someone", " looks <color_blue>depressed</color>. " );
            }
        }
        float pain = creature->get_pain() / 10.f;
        if( pain > 3 ) {
            figure_effects += pronoun_sex + pgettext( "Someone", " is writhing in <color_red>pain</color>. " );
        }
        if( creature->has_effect( effect_riding ) ) {
            pose = _( "rides" );
            monster *const mon = g->critter_at<monster>( creature->pos(), false );
            figure_effects += pronoun_sex + string_format( _( " is riding %s. " ),
                              colorize( mon->name(), c_light_blue ) );
        }
        if( creature->has_effect( effect_glowy_led ) ) {
            figure_effects += _( "A bionic LED is <color_yellow>glowing</color> softly. " );
        }
    }
    if( !figure_effects.empty() && figure_effects.back() == ' ' ) { // remove last space
        figure_effects.erase( figure_effects.end() - 1 );
    }
    return figure_effects;
}
References _, c_light_blue, colorize(), creature, effect_beartrap, effect_bleed, effect_boomered, effect_bouldering, effect_corroding, effect_crushed, effect_dazed, effect_downed, effect_glowing, effect_glowy_led, effect_happy, effect_harnessed, effect_has_bag, effect_haslight, effect_in_pit, effect_lack_sleep, effect_laserlocked, effect_lying_down, effect_monster_armor, effect_onfire, effect_riding, effect_sad, effect_saddled, effect_sap, effect_sleep, effect_slimed, effect_spores, effect_stunned, effect_tied, effect_webbed, g, monster::name(), pain, pgettext(), string_format(), and to_translation().
Referenced by photo_def_for_camera_point().
einkpc_download_memory_card()
static bool einkpc_download_memory_card (player & p, item & eink, item & mc) static
Definition at line 6204 of file iuse.cpp.
{
    bool something_downloaded = false;
    if( mc.get_var( "MC_PHOTOS", 0 ) > 0 ) {
        something_downloaded = true;
        int new_photos = mc.get_var( "MC_PHOTOS", 0 );
        mc.erase_var( "MC_PHOTOS" );
        p.add_msg_if_player( m_good, vgettext( "You download %d new photo into internal memory.",
                                               "You download %d new photos into internal memory.", new_photos ), new_photos );
        const int old_photos = eink.get_var( "EIPC_PHOTOS", 0 );
        eink.set_var( "EIPC_PHOTOS", old_photos + new_photos );
    }
    if( mc.get_var( "MC_MUSIC", 0 ) > 0 ) {
        something_downloaded = true;
        int new_songs = mc.get_var( "MC_MUSIC", 0 );
        mc.erase_var( "MC_MUSIC" );
        p.add_msg_if_player( m_good, vgettext( "You download %d new song into internal memory.",
                                               "You download %d new songs into internal memory.", new_songs ), new_songs );
        const int old_songs = eink.get_var( "EIPC_MUSIC", 0 );
        eink.set_var( "EIPC_MUSIC", old_songs + new_songs );
    }
    if( !mc.get_var( "MC_RECIPE" ).empty() ) {
        const bool science = mc.get_var( "MC_RECIPE" ) == "SCIENCE";
        mc.erase_var( "MC_RECIPE" );
        std::vector<const recipe *> candidates;
        for( const auto &e : recipe_dict ) {
            const auto &r = e.second;
            if( r.never_learn ) {
                continue;
            }
            if( science ) {
                if( r.difficulty >= 3 && one_in( r.difficulty + 1 ) ) {
                    candidates.push_back( &r );
                }
            } else {
                if( r.category == "CC_FOOD" ) {
                    if( r.difficulty <= 3 && one_in( r.difficulty ) ) {
                        candidates.push_back( &r );
                    }
                }
            }
        }
        if( !candidates.empty() ) {
            const recipe *r = random_entry( candidates );
            const recipe_id &rident = r->ident();
            const auto old_recipes = eink.get_var( "EIPC_RECIPES" );
            if( old_recipes.empty() ) {
                something_downloaded = true;
                eink.set_var( "EIPC_RECIPES", "," + rident.str() + "," );
                p.add_msg_if_player( m_good, _( "You download a recipe for %s into the tablet's memory." ),
                                     r->result_name() );
            } else {
                if( old_recipes.find( "," + rident.str() + "," ) == std::string::npos ) {
                    something_downloaded = true;
                    eink.set_var( "EIPC_RECIPES", old_recipes + rident.str() + "," );
                    p.add_msg_if_player( m_good, _( "You download a recipe for %s into the tablet's memory." ),
                                         r->result_name() );
                } else {
                    p.add_msg_if_player( m_good, _( "Your tablet already has a recipe for %s." ),
                                         r->result_name() );
                }
            }
        }
    }
    if( mc.has_var( "MC_EXTENDED_PHOTOS" ) ) {
        std::vector<extended_photo_def> extended_photos;
        try {
            item_read_extended_photos( mc, extended_photos, "MC_EXTENDED_PHOTOS" );
            item_read_extended_photos( eink, extended_photos, "EIPC_EXTENDED_PHOTOS", true );
            item_write_extended_photos( eink, extended_photos, "EIPC_EXTENDED_PHOTOS" );
            something_downloaded = true;
            p.add_msg_if_player( m_good, _( "You have downloaded your photos." ) );
        } catch( const JsonError &e ) {
            debugmsg( "Error card reading photos (loaded photos = %i) : %s", extended_photos.size(),
                      e.c_str() );
        }
    }
    const auto monster_photos = mc.get_var( "MC_MONSTER_PHOTOS" );
    if( !monster_photos.empty() ) {
        something_downloaded = true;
        p.add_msg_if_player( m_good, _( "You have updated your monster collection." ) );
        auto photos = eink.get_var( "EINK_MONSTER_PHOTOS" );
        if( photos.empty() ) {
            eink.set_var( "EINK_MONSTER_PHOTOS", monster_photos );
        } else {
            std::istringstream f( monster_photos );
            std::string s;
            while( getline( f, s, ',' ) ) {
                if( s.empty() ) {
                    continue;
                }
                const std::string mtype = s;
                getline( f, s, ',' );
                char *chq = &s[0];
                const int quality = atoi( chq );
                const size_t eink_strpos = photos.find( "," + mtype + "," );
                if( eink_strpos == std::string::npos ) {
                    photos += mtype + "," + string_format( "%d", quality ) + ",";
                } else {
                    const size_t strqpos = eink_strpos + mtype.size() + 2;
                    char *chq = &photos[strqpos];
                    const int old_quality = atoi( chq );
                    if( quality > old_quality ) {
                        chq = &string_format( "%d", quality )[0];
                        photos[strqpos] = *chq;
                    }
                }
            }
            eink.set_var( "EINK_MONSTER_PHOTOS", photos );
        }
    }
    if( mc.has_flag( "MC_TURN_USED" ) ) {
        mc.clear_vars();
        mc.unset_flags();
        mc.convert( itype_mobile_memory_card_used );
    }
    if( !something_downloaded ) {
        p.add_msg_if_player( m_info, _( "This memory card does not contain any new data." ) );
        return false;
    }
    return true;
}
References _, player::add_msg_if_player(), JsonError::c_str(), item::clear_vars(), item::convert(), debugmsg, item::erase_var(), item::get_var(), item::has_flag(), item::has_var(), recipe::ident(), item_read_extended_photos(), item_write_extended_photos(), itype_mobile_memory_card_used, m_good, m_info, one_in(), random_entry(), recipe_dict, recipe::result_name(), mattack::science(), item::set_var(), mtype::size, string_id< T >::str(), string_format(), item::unset_flags(), and vgettext().
Referenced by iuse::einktabletpc().
emit_radio_signal()
static void emit_radio_signal (player & p, const std::string & signal) static
Send radio signal from player.
Definition at line 8005 of file iuse.cpp.
{
    const auto visitor = [&]( item & it, const tripoint & loc ) -> VisitResponse {
        if( it.has_flag( "RADIO_ACTIVATION" ) && it.has_flag( signal ) )
        {
            sounds::sound( p.pos(), 6, sounds::sound_t::alarm, _( "beep" ), true, "misc", "beep" );
            bool invoke_proc = it.has_flag( "RADIO_INVOKE_PROC" );
            // Invoke to transform item
            it.type->invoke( p, it, loc );
            if( invoke_proc ) {
                // Cause invocation of transformed item on next turn processing
                it.ammo_unset();
            }
        }
        return VisitResponse::NEXT;
    };
    int z_min = g->m.has_zlevels() ? -OVERMAP_DEPTH : 0;
    int z_max = g->m.has_zlevels() ? OVERMAP_HEIGHT : 0;
    for( int zlev = z_min; zlev <= z_max; zlev++ ) {
        for( tripoint loc : g->m.points_on_zlevel( zlev ) ) {
            // Items on ground
            map_cursor mc( loc );
            mc.visit_items( [&]( item * it ) {
                return visitor( *it, loc );
            } );
            // Items in vehicles
            optional_vpart_position vp = g->m.veh_at( loc );
            if( !vp ) {
                continue;
            }
            cata::optional<vpart_reference> vpr = vp.part_with_feature( "CARGO", false );
            if( !vpr ) {
                continue;
            }
            vehicle_cursor vc( vp->vehicle(), vpr->part_index() );
            vc.visit_items( [&]( item * it ) {
                return visitor( *it, loc );
            } );
        }
    }
    // Items on creatures
    for( Creature &cr : g->all_creatures() ) {
        const tripoint &cr_pos = cr.pos();
        if( cr.is_monster() ) {
            monster &mon = *cr.as_monster();
            mon.visit_items( [&]( item * it ) {
                return visitor( *it, cr_pos );
            } );
        } else {
            Character &ch = *cr.as_character();
            ch.visit_items( [&]( item * it ) {
                return visitor( *it, cr_pos );
            } );
        }
    }
}
References _, sounds::alarm, item::ammo_unset(), Character::as_character(), monster::as_monster(), g, item::has_flag(), itype::invoke(), NEXT, OVERMAP_DEPTH, OVERMAP_HEIGHT, optional_vpart_position::part_with_feature(), Character::pos(), sounds::sound(), item::type, and visitable< T >::visit_items().
Referenced by iuse::radiocontrol().
enumerate_objects_around_point()
static object_names_collection enumerate_objects_around_point (const tripoint & point, int radius, const tripoint & bounds_center_point, int bounds_radius, const tripoint & camera_pos, const units::volume & min_visible_volume, bool create_figure_desc, std::unordered_set< tripoint > & ignored_points, std::unordered_set< const vehicle * > & vehicles_recorded) static
Definition at line 6952 of file iuse.cpp.
{
    map &here = get_map();
    const tripoint_range<tripoint> bounds =
        here.points_in_radius( bounds_center_point, bounds_radius );
    const tripoint_range<tripoint> points_in_radius = here.points_in_radius( point, radius );
    int dist = rl_dist( camera_pos, point );
    bool item_found = false;
    std::unordered_set<const vehicle *> local_vehicles_recorded( vehicles_recorded );
    object_names_collection ret_obj;
    std::string description_part_on_figure;
    std::string description_furniture_on_figure;
    std::string description_terrain_on_figure;
    // store objects in radius
    for( const tripoint &point_around_figure : points_in_radius ) {
        if( !bounds.is_point_inside( point_around_figure ) ||
            !g->m.sees( camera_pos, point_around_figure, dist + radius ) ||
            ( ignored_points.find( point_around_figure ) != ignored_points.end() &&
              !( point_around_figure == point && create_figure_desc ) ) ) {
            continue; // disallow photos with not visible objects
        }
        units::volume volume_to_search = point_around_figure == bounds_center_point ? 0_ml :
                                         min_visible_volume;
        std::string furn_desc = colorized_feature_description_at( point_around_figure, item_found,
                                volume_to_search );
        const item item = get_top_item_at_point( point_around_figure, volume_to_search );
        const optional_vpart_position veh_part_pos = g->m.veh_at( point_around_figure );
        std::string unusual_ter_desc = colorized_ter_name_flags_at( point_around_figure,
                                       camera_ter_whitelist_flags,
                                       camera_ter_whitelist_types );
        std::string ter_desc = colorized_ter_name_flags_at( point_around_figure );
        const std::string trap_name = colorized_trap_name_at( point_around_figure );
        const std::string field_desc = colorized_field_description_at( point_around_figure );
        if( !furn_desc.empty() ) {
            furn_desc = trap_name + furn_desc + field_desc;
            if( point == point_around_figure && create_figure_desc ) {
                description_furniture_on_figure = furn_desc;
            } else {
                ret_obj.furniture[ furn_desc ] ++;
            }
        } else if( veh_part_pos.has_value() ) {
            const vehicle &veh = veh_part_pos->vehicle();
            const std::string veh_name = colorize( veh.disp_name(), c_light_blue );
            const vehicle *veh_hash = &veh_part_pos->vehicle();
            if( local_vehicles_recorded.find( veh_hash ) == local_vehicles_recorded.end() &&
                point != point_around_figure ) {
                // new vehicle, point is not center
                ret_obj.vehicles[ veh_name ] ++;
            } else if( point == point_around_figure ) {
                // point is center
                //~ %1$s: vehicle part name, %2$s: vehicle name
                description_part_on_figure = string_format( pgettext( "vehicle part", "%1$s from %2$s" ),
                                             veh_part_pos.part_displayed()->part().name(), veh_name );
                if( ret_obj.vehicles.find( veh_name ) != ret_obj.vehicles.end() &&
                    local_vehicles_recorded.find( veh_hash ) != local_vehicles_recorded.end() ) {
                    // remove vehicle name only if we previously added THIS vehicle name (in case of same name)
                    ret_obj.vehicles[ veh_name ] --;
                    if( ret_obj.vehicles[ veh_name ] <= 0 ) {
                        ret_obj.vehicles.erase( veh_name );
                    }
                }
            }
            vehicles_recorded.insert( veh_hash );
            local_vehicles_recorded.insert( veh_hash );
        } else if( !item.is_null() ) {
            std::string item_name = colorized_item_name( item );
            item_name = trap_name + item_name + field_desc;
            if( point == point_around_figure && create_figure_desc ) {
                //~ %1$s: terrain description, %2$s: item name
                description_terrain_on_figure = string_format( pgettext( "terrain and item", "%1$s with a %2$s" ),
                                                ter_desc, item_name );
            } else {
                ret_obj.items[ item_name ] ++;
            }
        } else if( !unusual_ter_desc.empty() ) {
            unusual_ter_desc = trap_name + unusual_ter_desc + field_desc;
            if( point == point_around_figure && create_figure_desc ) {
                description_furniture_on_figure = unusual_ter_desc;
            } else {
                ret_obj.furniture[ unusual_ter_desc ] ++;
            }
        } else if( !ter_desc.empty() && ( !field_desc.empty() || !trap_name.empty() ) ) {
            ter_desc = trap_name + ter_desc + field_desc;
            if( point == point_around_figure && create_figure_desc ) {
                description_terrain_on_figure = ter_desc;
            } else {
                ret_obj.terrain[ ter_desc ] ++;
            }
        } else {
            ter_desc = trap_name + ter_desc + field_desc;
            if( point == point_around_figure && create_figure_desc ) {
                description_terrain_on_figure = ter_desc;
            }
        }
        ignored_points.insert( point_around_figure );
    }
    if( create_figure_desc ) {
        std::vector<std::string> objects_combined_desc;
        int objects_combined_num = 0;
        std::unordered_map<std::string, int> vecs_to_retrieve[4] = {
            ret_obj.furniture, ret_obj.vehicles, ret_obj.items, ret_obj.terrain
        };
        for( int i = 0; i < 4; i++ ) {
            for( const auto &p : vecs_to_retrieve[ i ] ) {
                objects_combined_desc.push_back( i == 1 ?  // vehicle name already includes "the"
                                                 format_object_pair_no_article( p ) : format_object_pair_article( p ) );
                objects_combined_num += p.second;
            }
        }
        const char *transl_str = pgettext( "someone stands/sits *on* something", " on a %s." );
        if( !description_part_on_figure.empty() ) {
            ret_obj.figure_text = string_format( transl_str, description_part_on_figure );
        } else {
            if( !description_furniture_on_figure.empty() ) {
                ret_obj.figure_text = string_format( transl_str, description_furniture_on_figure );
            } else {
                ret_obj.figure_text = string_format( transl_str, description_terrain_on_figure );
            }
        }
        if( !objects_combined_desc.empty() ) {
            // store objects to description_figures_status
            std::string objects_text = enumerate_as_string( objects_combined_desc );
            ret_obj.obj_nearby_text = string_format( vgettext( "Nearby is %s.", "Nearby are %s.",
                                      objects_combined_num ), objects_text );
        }
    }
    return ret_obj;
}
References c_light_blue, camera_ter_whitelist_flags, camera_ter_whitelist_types, colorize(), colorized_feature_description_at(), colorized_field_description_at(), colorized_item_name(), colorized_ter_name_flags_at(), colorized_trap_name_at(), vehicle::disp_name(), enumerate_as_string(), object_names_collection::figure_text, format_object_pair_article(), format_object_pair_no_article(), object_names_collection::furniture, g, get_map(), get_top_item_at_point(), cata::optional< T >::has_value(), item::is_null(), tripoint_range< Tripoint >::is_point_inside(), object_names_collection::items, object_names_collection::obj_nearby_text, optional_vpart_position::part_displayed(), pgettext(), points_in_radius(), map::points_in_radius(), rl_dist(), string_format(), object_names_collection::terrain, object_names_collection::vehicles, and vgettext().
Referenced by photo_def_for_camera_point().
feedpet()
static int feedpet (player & p, monster & mon, item & it, m_flag food_flag, const char * message) static
Definition at line 1534 of file iuse.cpp.
{
    if( mon.has_flag( food_flag ) ) {
        p.add_msg_if_player( m_good, message, mon.get_name() );
        mon.friendly = -1;
        mon.add_effect( effect_pet, 1_turns, num_bp );
        p.consume_charges( it, 1 );
        return 0;
    } else {
        p.add_msg_if_player( _( "The %s doesn't want that kind of food." ), mon.get_name() );
        return 0;
    }
}
References _, monster::add_effect(), player::add_msg_if_player(), Character::consume_charges(), effect_pet, monster::friendly, monster::get_name(), monster::has_flag(), m_good, mapgen_defer::message, and num_bp.
Referenced by petfood().
flag_ACID()
static const std::string flag_ACID ("ACID") static
Referenced by iuse::blech().
flag_CURRENT()
static const std::string flag_CURRENT ("CURRENT") static
Referenced by iuse::dig_channel().
flag_DIGGABLE()
static const std::string flag_DIGGABLE ("DIGGABLE") static
Referenced by iuse::dig_channel().
flag_FISHABLE()
static const std::string flag_FISHABLE ("FISHABLE") static
Referenced by iuse::fishing_rod().
flag_FIX_FARSIGHT()
static const std::string flag_FIX_FARSIGHT ("FIX_FARSIGHT") static
Referenced by iuse::einktabletpc(), and iuse::robotcontrol().
flag_HEATS_FOOD()
static const std::string flag_HEATS_FOOD ("HEATS_FOOD") static
Referenced by iuse::toggle_heats_food().
flag_PLANT()
static const std::string flag_PLANT ("PLANT") static
Referenced by iuse::makemound().
flag_PLOWABLE()
static const std::string flag_PLOWABLE ("PLOWABLE") static
Referenced by iuse::makemound().
format_object_pair()
static std::string format_object_pair (const std::pair< std::string, int > & pair, const std::string & article) static
Definition at line 6835 of file iuse.cpp.
{
    if( pair.second == 1 ) {
        return article + pair.first;
    } else if( pair.second > 1 ) {
        return string_format( "%i %s", pair.second, pair.first );
    }
    return std::string();
}
References string_format().
Referenced by format_object_pair_article(), and format_object_pair_no_article().
format_object_pair_article()
static std::string format_object_pair_article (const std::pair< std::string, int > & pair) static
Definition at line 6845 of file iuse.cpp.
{
    return format_object_pair( pair, pgettext( "Article 'a', replace it with empty "
                               "string if it is not used in language", "a " ) );
}
References format_object_pair(), and pgettext().
Referenced by enumerate_objects_around_point(), and photo_def_for_camera_point().
format_object_pair_no_article()
static std::string format_object_pair_no_article (const std::pair< std::string, int > & pair) static
Definition at line 6850 of file iuse.cpp.
{
    return format_object_pair( pair, "" );
}
References format_object_pair().
Referenced by enumerate_objects_around_point(), and photo_def_for_camera_point().
get_music_description()
static std::string get_music_description () static
Definition at line 4137 of file iuse.cpp.
{
    const std::array<std::string, 5> descriptions = {{
            translate_marker( "a sweet guitar solo!" ),
            translate_marker( "a funky bassline." ),
            translate_marker( "some amazing vocals." ),
            translate_marker( "some pumping bass." ),
            translate_marker( "dramatic classical music." )
        }
    };
    if( one_in( 50 ) ) {
        return _( "some bass-heavy post-glam speed polka." );
    }
    size_t i = static_cast<size_t>( rng( 0, descriptions.size() * 2 ) );
    if( i < descriptions.size() ) {
        return _( descriptions[i] );
    }
    // Not one of the hard-coded versions, let's apply a random string made up
    // of snippets {a, b, c}, but only a 50% chance
    // Actual chance = 24.5% of being selected
    if( one_in( 2 ) ) {
        return SNIPPET.expand( SNIPPET.random_from_category( "<music_description>" ).value_or(
                                   translation() ).translated() );
    }
    return _( "a sweet guitar solo!" );
}
References _, snippet_library::expand(), one_in(), snippet_library::random_from_category(), rng(), SNIPPET, and translate_marker.
Referenced by iuse::play_music().
get_top_item_at_point()
static item get_top_item_at_point (const tripoint & point, const units::volume & min_visible_volume) static
Definition at line 6764 of file iuse.cpp.
{
    map_stack items = g->m.i_at( point );
    // iterate from topmost item down to ground
    for( const item &it : items ) {
        if( it.volume() > min_visible_volume ) {
            // return top (or first big enough) item to the list
            return it;
        }
    }
    return item();
}
References g.
Referenced by colorized_feature_description_at(), enumerate_objects_around_point(), and photo_def_for_camera_point().
good_fishing_spot()
static bool good_fishing_spot (tripoint pos) static
Definition at line 1746 of file iuse.cpp.
{
    std::unordered_set<tripoint> fishable_locations = g->get_fishable_locations( 60, pos );
    std::vector<monster *> fishables = g->get_fishable_monsters( fishable_locations );
    map &here = get_map();
    // isolated little body of water with no definite fish population
    // TODO: fix point types
    const oter_id &cur_omt =
        overmap_buffer.ter( tripoint_abs_omt( ms_to_omt_copy( here.getabs( pos ) ) ) );
    std::string om_id = cur_omt.id().c_str();
    if( fishables.empty() && !g->m.has_flag( "CURRENT", pos ) &&
        om_id.find( "river_" ) == std::string::npos && !cur_omt->is_lake() && !cur_omt->is_lake_shore() ) {
        g->u.add_msg_if_player( m_info, _( "You doubt you will have much luck catching fish here" ) );
        return false;
    }
    return true;
}
References _, string_id< T >::c_str(), g, get_map(), map::getabs(), int_id< T >::id(), oter_t::is_lake(), oter_t::is_lake_shore(), m_info, ms_to_omt_copy(), overmap_buffer, and overmapbuffer::ter().
Referenced by iuse::fish_trap(), and iuse::fishing_rod().
hackveh()
static bool hackveh (player & p, item & it, vehicle & veh) static
Intelligence increases chance of bypassing vehicle security system Computer increases chance of bypassing vehicle security system
Definition at line 8159 of file iuse.cpp.
{
    if( !veh.is_locked || !veh.has_security_working() ) {
        return true;
    }
    const bool advanced = !empty( veh.get_avail_parts( "REMOTE_CONTROLS" ) );
    if( advanced && veh.is_alarm_on ) {
        p.add_msg_if_player( m_bad, _( "This vehicle's security system has locked you out!" ) );
        return false;
    }
    /** @EFFECT_INT increases chance of bypassing vehicle security system */
    /** @EFFECT_COMPUTER increases chance of bypassing vehicle security system */
    int roll = dice( p.get_skill_level( skill_computer ) + 2, p.int_cur ) - ( advanced ? 50 : 25 );
    int effort = 0;
    bool success = false;
    if( roll < -20 ) { // Really bad rolls will trigger the alarm before you know it exists
        effort = 1;
        p.add_msg_if_player( m_bad, _( "You trigger the alarm!" ) );
        veh.is_alarm_on = true;
    } else if( roll >= 20 ) { // Don't bother the player if it's trivial
        effort = 1;
        p.add_msg_if_player( m_good, _( "You quickly bypass the security system!" ) );
        success = true;
    }
    if( effort == 0 && !query_yn( _( "Try to hack this car's security system?" ) ) ) {
        // Scanning for security systems isn't free
        p.moves -= to_moves<int>( 1_seconds );
        it.charges -= 1;
        return false;
    }
    p.practice( skill_computer, advanced ? 10 : 3 );
    if( roll < -10 ) {
        effort = rng( 4, 8 );
        p.add_msg_if_player( m_bad, _( "You waste some time, but fail to affect the security system." ) );
    } else if( roll < 0 ) {
        effort = 1;
        p.add_msg_if_player( m_bad, _( "You fail to affect the security system." ) );
    } else if( roll < 20 ) {
        effort = rng( 2, 8 );
        p.add_msg_if_player( m_mixed,
                             _( "You take some time, but manage to bypass the security system!" ) );
        success = true;
    }
    p.moves -= to_moves<int>( time_duration::from_seconds( effort ) );
    it.charges -= effort;
    if( success && advanced ) { // Unlock controls, but only if they're drive-by-wire
        veh.is_locked = false;
    }
    return success;
}
References _, player::add_msg_if_player(), item::charges, dice(), time_duration::from_seconds(), vehicle::get_avail_parts(), Character::get_skill_level(), vehicle::has_security_working(), Character::int_cur, vehicle::is_alarm_on, vehicle::is_locked, m_bad, m_good, m_mixed, Creature::moves, player::practice(), query_yn(), rng(), skill_computer, and behavior::success.
Referenced by iuse::remoteveh().
init_memory_card_with_random_stuff()
static void init_memory_card_with_random_stuff (item & it) static
Definition at line 6129 of file iuse.cpp.
{
    if( it.has_flag( "MC_MOBILE" ) && ( it.has_flag( "MC_RANDOM_STUFF" ) ||
                                        it.has_flag( "MC_SCIENCE_STUFF" ) ) && !( it.has_flag( "MC_USED" ) ||
                                                it.has_flag( "MC_HAS_DATA" ) ) ) {
        it.set_flag( "MC_HAS_DATA" );
        bool encrypted = false;
        if( it.has_flag( "MC_MAY_BE_ENCRYPTED" ) && one_in( 8 ) ) {
            it.convert( itype_id( it.typeId().str() + "_encrypted" ) );
        }
        //some special cards can contain "MC_ENCRYPTED" flag
        if( it.has_flag( "MC_ENCRYPTED" ) ) {
            encrypted = true;
        }
        int data_chance = 2;
        //encrypted memory cards often contain data
        if( encrypted && !one_in( 3 ) ) {
            data_chance--;
        }
        //just empty memory card
        if( !one_in( data_chance ) ) {
            return;
        }
        //add someone's personal photos
        if( one_in( data_chance ) ) {
            //decrease chance to more data
            data_chance++;
            if( encrypted && one_in( 3 ) ) {
                data_chance--;
            }
            const int duckfaces_count = rng( 5, 30 );
            it.set_var( "MC_PHOTOS", duckfaces_count );
        }
        //decrease chance to music and other useful data
        data_chance++;
        if( encrypted && one_in( 2 ) ) {
            data_chance--;
        }
        if( one_in( data_chance ) ) {
            data_chance++;
            if( encrypted && one_in( 3 ) ) {
                data_chance--;
            }
            const int new_songs_count = rng( 5, 15 );
            it.set_var( "MC_MUSIC", new_songs_count );
        }
        data_chance++;
        if( encrypted && one_in( 2 ) ) {
            data_chance--;
        }
        if( one_in( data_chance ) ) {
            it.set_var( "MC_RECIPE", "SIMPLE" );
        }
        if( it.has_flag( "MC_SCIENCE_STUFF" ) ) {
            it.set_var( "MC_RECIPE", "SCIENCE" );
        }
    }
}
References item::convert(), item::has_flag(), one_in(), rng(), item::set_flag(), item::set_var(), string_id< T >::str(), and item::typeId().
Referenced by iuse::camera(), and iuse::einktabletpc().
item_read_extended_photos()
static bool item_read_extended_photos (item & it, std::vector< extended_photo_def > & extended_photos, const std::string & var_name, bool insert_at_begin = false) static
Definition at line 7408 of file iuse.cpp.
{
    bool result = false;
    std::istringstream extended_photos_data( it.get_var( var_name ) );
    JsonIn json( extended_photos_data );
    if( insert_at_begin ) {
        std::vector<extended_photo_def> temp_vec;
        result = json.read( temp_vec );
        extended_photos.insert( std::begin( extended_photos ), std::begin( temp_vec ),
                                std::end( temp_vec ) );
    } else {
        result = json.read( extended_photos );
    }
    return result;
}
References item::get_var(), and JsonIn::read().
Referenced by iuse::camera(), einkpc_download_memory_card(), and show_photo_selection().
item_save_monsters()
static void item_save_monsters (player & p, item & it, const std::vector< monster * > & monster_vec, int photo_quality) static
Definition at line 7365 of file iuse.cpp.
{
    std::string monster_photos = it.get_var( "CAMERA_MONSTER_PHOTOS" );
    if( monster_photos.empty() ) {
        monster_photos = ",";
    }
    for( monster * const &monster_p : monster_vec ) {
        const std::string mtype = monster_p->type->id.str();
        const std::string name = monster_p->name();
        // position of <monster type string>
        const size_t mon_str_pos = monster_photos.find( "," + mtype + "," );
        if( mon_str_pos == std::string::npos ) { // new monster
            monster_photos += string_format( "%s,%d,", mtype, photo_quality );
        } else { // replace quality character, if new photo is better
            const size_t quality_num_pos = mon_str_pos + mtype.size() + 2;
            char *quality_char = &monster_photos[ quality_num_pos ];
            const int old_quality = atoi( quality_char ); // get qual number from char
            if( photo_quality > old_quality ) {
                monster_photos[ quality_num_pos ] = string_format( "%d", photo_quality )[ 0 ];
            }
            if( !p.is_blind() ) {
                if( photo_quality > old_quality ) {
                    p.add_msg_if_player( m_good, _( "The quality of %s image is better than the previous one." ),
                                         colorize( name, c_light_blue ) );
                } else if( old_quality == 5 ) {
                    p.add_msg_if_player( _( "The quality of stored %s image is already maximally detailed." ),
                                         colorize( name, c_light_blue ) );
                } else {
                    p.add_msg_if_player( m_bad, _( "But the quality of %s image is worse than the previous one." ),
                                         colorize( name, c_light_blue ) );
                }
            }
        }
    }
    it.set_var( "CAMERA_MONSTER_PHOTOS", monster_photos );
}
References _, player::add_msg_if_player(), c_light_blue, colorize(), item::get_var(), mtype::id, Character::is_blind(), m_bad, m_good, om_direction::name(), item::set_var(), mtype::size, string_id< T >::str(), and string_format().
Referenced by iuse::camera().
item_write_extended_photos()
static void item_write_extended_photos (item & it, const std::vector< extended_photo_def > & extended_photos, const std::string & var_name) static
Definition at line 7426 of file iuse.cpp.
{
    std::ostringstream extended_photos_data;
    JsonOut json( extended_photos_data );
    json.write( extended_photos );
    it.set_var( var_name, extended_photos_data.str() );
}
References item::set_var(), and JsonOut::write().
Referenced by iuse::camera(), einkpc_download_memory_card(), and show_photo_selection().
marloss_common()
static void marloss_common (player & p, item & it, const trait_id & current_color) static
Intelligence slightly reduces sleep duration when eating mycus+goo Intelligence reduces sleep duration when eating wrong color marloss
Definition at line 1259 of file iuse.cpp.
{
    static const std::map<trait_id, add_type> mycus_colors = {{
            { trait_MARLOSS_BLUE, add_type::MARLOSS_B }, { trait_MARLOSS_YELLOW, add_type::MARLOSS_Y }, { trait_MARLOSS, add_type::MARLOSS_R }
        }
    };
    if( p.has_trait( current_color ) || p.has_trait( trait_THRESH_MARLOSS ) ) {
        p.add_msg_if_player( m_good,
                             _( "As you eat the %s, you have a near-religious experience, feeling at one with your surroundings" ),
                             it.tname() );
        p.add_morale( MORALE_MARLOSS, 100, 1000 );
        for( const std::pair<const trait_id, add_type> &pr : mycus_colors ) {
            if( pr.first != current_color ) {
                p.add_addiction( pr.second, 50 );
            }
        }
        p.set_stored_kcal( p.max_stored_kcal() );
        spawn_spores( p );
        return;
    }
    int marloss_count = std::count_if( mycus_colors.begin(), mycus_colors.end(),
    [&p]( const std::pair<trait_id, add_type> &pr ) {
        return p.has_trait( pr.first );
    } );
    /* If we're not already carriers of current type of Marloss, roll for a random effect:
     * 1 - Mutate
     * 2 - Mutate
     * 3 - Mutate
     * 4 - Purify
     * 5 - Purify
     * 6 - Cleanse radiation + Purify
     * 7 - Fully satiate
     * 8 - Vomit
     * 9-12 - Give Marloss mutation
     */
    int effect = rng( 1, 12 );
    if( effect <= 3 ) {
        p.add_msg_if_player( _( "It tastes extremely strange!" ) );
        p.mutate();
        // Gruss dich, mutation drain, missed you!
        p.mod_pain( 2 * rng( 1, 5 ) );
        p.mod_stored_nutr( 10 );
        p.mod_thirst( 10 );
        p.mod_fatigue( 5 );
    } else if( effect <= 6 ) { // Radiation cleanse is below
        p.add_msg_if_player( m_good, _( "You feel better all over." ) );
        p.mod_painkiller( 30 );
        iuse::purifier( &p, &it, false, p.pos() );
        if( effect == 6 ) {
            p.set_rad( 0 );
        }
    } else if( effect == 7 ) {
        p.add_msg_if_player( m_good, _( "It is delicious, and very filling!" ) );
        p.set_stored_kcal( p.max_stored_kcal() );
    } else if( effect == 8 ) {
        p.add_msg_if_player( m_bad, _( "You take one bite, and immediately vomit!" ) );
        p.vomit();
    } else if( p.crossed_threshold() ) {
        // Mycus Rejection.  Goo already present fights off the fungus.
        p.add_msg_if_player( m_bad,
                             _( "You feel a familiar warmth, but suddenly it surges into an excruciating burn as you convulse, vomiting, and black out" ) );
        if( p.is_avatar() ) {
            g->memorial().add(
                pgettext( "memorial_male", "Suffered Marloss Rejection." ),
                pgettext( "memorial_female", "Suffered Marloss Rejection." ) );
        }
        p.vomit();
        p.mod_pain( 90 );
        p.hurtall( rng( 40, 65 ), nullptr ); // No good way to say "lose half your current HP"
        /** @EFFECT_INT slightly reduces sleep duration when eating mycus+goo */
        p.fall_asleep( 10_hours - p.int_cur *
                       1_minutes ); // Hope you were eating someplace safe.  Mycus v. Goo in your guts is no joke.
        for( const std::pair<const trait_id, add_type> &pr : mycus_colors ) {
            p.unset_mutation( pr.first );
            p.rem_addiction( pr.second );
        }
        p.set_mutation(
            trait_MARLOSS_AVOID ); // And if you survive it's etched in your RNA, so you're unlikely to repeat the experiment.
    } else if( marloss_count >= 2 ) {
        p.add_msg_if_player( m_bad,
                             _( "You feel a familiar warmth, but suddenly it surges into painful burning as you convulse and collapse to the ground" ) );
        /** @EFFECT_INT reduces sleep duration when eating wrong color marloss */
        p.fall_asleep( 40_minutes - 1_minutes * p.int_cur / 2 );
        for( const std::pair<const trait_id, add_type> &pr : mycus_colors ) {
            p.unset_mutation( pr.first );
            p.rem_addiction( pr.second );
        }
        p.set_mutation( trait_THRESH_MARLOSS );
        g->m.ter_set( p.pos(), t_marloss );
        g->events().send<event_type::crosses_marloss_threshold>( p.getID() );
        p.add_msg_if_player( m_good,
                             _( "You wake up in a marloss bush.  Almost *cradled* in it, actually, as though it grew there for you." ) );
        p.add_msg_if_player( m_good,
                             //~ Beginning to hear the Mycus while conscious: that's it speaking
                             _( "unity.  together we have reached the door.  we provide the final key.  now to pass through" ) );
    } else {
        p.add_msg_if_player( _( "You feel a strange warmth spreading throughout your body" ) );
        p.set_mutation( current_color );
        // Give us addictions to the other two colors, but cure one for current color
        for( const std::pair<const trait_id, add_type> &pr : mycus_colors ) {
            if( pr.first == current_color ) {
                p.rem_addiction( pr.second );
            } else {
                p.add_addiction( pr.second, 60 );
            }
        }
    }
}
References _, Character::add_addiction(), Character::add_morale(), player::add_msg_if_player(), Character::crossed_threshold(), crosses_marloss_threshold, Character::fall_asleep(), g, Character::getID(), Character::has_trait(), Character::hurtall(), Character::int_cur, Creature::is_avatar(), m_bad, m_good, MARLOSS_B, MARLOSS_R, MARLOSS_Y, Character::max_stored_kcal(), Character::mod_fatigue(), Character::mod_pain(), Character::mod_painkiller(), Character::mod_stored_nutr(), Character::mod_thirst(), MORALE_MARLOSS, Character::mutate(), pgettext(), Character::pos(), iuse::purifier(), Character::rem_addiction(), rng(), Character::set_mutation(), Character::set_rad(), Character::set_stored_kcal(), spawn_spores(), t_marloss, item::tname(), trait_MARLOSS, trait_MARLOSS_AVOID, trait_MARLOSS_BLUE, trait_MARLOSS_YELLOW, trait_THRESH_MARLOSS, Character::unset_mutation(), and Character::vomit().
Referenced by iuse::marloss(), iuse::marloss_gel(), and iuse::marloss_seed().
marloss_prevented()
static bool marloss_prevented (const player & p) static
Definition at line 1373 of file iuse.cpp.
{
    if( p.is_npc() ) {
        return true;
    }
    if( p.has_trait( trait_MARLOSS_AVOID ) ) {
        p.add_msg_if_player( m_warning,
                             //~ "Uh-uh" is a sound used for "nope", "no", etc.
                             _( "After what happened that last time?  uh-uh.  You're not eating that alien poison." ) );
        return true;
    }
    if( p.has_trait( trait_THRESH_MYCUS ) ) {
        p.add_msg_if_player( m_info,
                             _( "We no longer require this scaffolding.  We reserve it for other uses." ) );
        return true;
    }
    return false;
}
References _, player::add_msg_if_player(), Character::has_trait(), player::is_npc(), m_info, m_warning, trait_MARLOSS_AVOID, and trait_THRESH_MYCUS.
Referenced by iuse::marloss(), iuse::marloss_gel(), and iuse::marloss_seed().
multicooker_hallu()
static bool multicooker_hallu (player & p) static
Definition at line 8334 of file iuse.cpp.
{
    p.moves -= to_moves<int>( 2_seconds );
    const int random_hallu = rng( 1, 7 );
    switch( random_hallu ) {
        case 1:
            add_msg( m_info, _( "And when you gaze long into a screen, the screen also gazes into you." ) );
            return true;
        case 2:
            add_msg( m_bad, _( "The multi-cooker boiled your head!" ) );
            return true;
        case 3:
            add_msg( m_info, _( "The characters on the screen display an obscene joke.  Strange humor." ) );
            return true;
        case 4:
            //~ Single-spaced & lowercase are intentional, conveying hurried speech-KA101
            add_msg( m_warning, _( "Are you sure?!  the multi-cooker wants to poison your food!" ) );
            return true;
        case 5:
            add_msg( m_info,
                     _( "The multi-cooker argues with you about the taste preferences.  You don't want to deal with it." ) );
            return true;
        case 6:
            if( !one_in( 5 ) ) {
                add_msg( m_warning, _( "The multi-cooker runs away!" ) );
                if( monster *const m = g->place_critter_around( mon_hallu_multicooker, p.pos(), 1 ) ) {
                    m->hallucination = true;
                    m->add_effect( effect_run, 100_turns, num_bp );
                }
            } else {
                p.add_msg_if_player( m_info, _( "You're surrounded by aggressive multi-cookers!" ) );
                for( const tripoint &pn : g->m.points_in_radius( p.pos(), 1 ) ) {
                    if( monster *const m = g->place_critter_at( mon_hallu_multicooker, pn ) ) {
                        m->hallucination = true;
                    }
                }
            }
            return true;
        default:
            return false;
    }
}
References _, add_msg(), player::add_msg_if_player(), effect_run, g, m_bad, m_info, m_warning, mon_hallu_multicooker, Creature::moves, num_bp, one_in(), Character::pos(), and rng().
Referenced by iuse::multicooker().
petfood()
static int petfood (player & p, item & it, Petfood animal_food_type) static
Definition at line 1548 of file iuse.cpp.
{
    const cata::optional<tripoint> pnt_ = choose_adjacent( string_format(
            _( "Tame which animal with the %s?" ),
            it.tname() ) );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint pnt = *pnt_;
    p.moves -= to_moves<int>( 1_seconds );
    // First a check to see if we are trying to feed a NPC dog food.
    if( animal_food_type == DOGFOOD && g->critter_at<npc>( pnt ) != nullptr ) {
        if( npc *const person_ = g->critter_at<npc>( pnt ) ) {
            npc &person = *person_;
            if( query_yn( _( "Are you sure you want to feed a person the dog food?" ) ) ) {
                p.add_msg_if_player( _( "You put your %1$s into %2$s's mouth!" ), it.tname(),
                                     person.name );
                if( person.is_ally( p ) || x_in_y( 9, 10 ) ) {
                    person.say(
                        _( "Okay, but please, don't give me this again.  I don't want to eat dog food in the cataclysm all day." ) );
                    p.consume_charges( it, 1 );
                    return 0;
                } else {
                    p.add_msg_if_player( _( "%s knocks it out from your hand!" ), person.name );
                    person.make_angry();
                    p.consume_charges( it, 1 );
                    return 0;
                }
            } else {
                p.add_msg_if_player( _( "Never mind." ) );
                return 0;
            }
        }
        // Then monsters.
    } else if( monster *const mon_ptr = g->critter_at<monster>( pnt, true ) ) {
        monster &mon = *mon_ptr;
        if( mon.is_hallucination() ) {
            p.add_msg_if_player( _( "You try to feed the %s some %s, but it vanishes!" ),
                                 mon.type->nname(), it.tname() );
            mon.die( nullptr );
            return 0;
        }
        // This switch handles each petfood for each type of tameable monster.
        switch( animal_food_type ) {
            case DOGFOOD:
                if( mon.type->id == mon_dog_thing ) {
                    p.deal_damage( &mon, bodypart_id( "hand_r" ), damage_instance( DT_CUT, rng( 1, 10 ) ) );
                    p.add_msg_if_player( m_bad, _( "You want to feed it the dog food, but it bites your fingers!" ) );
                    if( one_in( 5 ) ) {
                        p.add_msg_if_player(
                            _( "Apparently it's more interested in your flesh than the dog food in your hand!" ) );
                        p.consume_charges( it, 1 );
                        return 0;
                    }
                } else {
                    return feedpet( p, mon, it, MF_DOGFOOD,
                                    _( "The %s seems to like you!  It lets you pat its head and seems friendly." ) );
                }
                break;
            case CATFOOD:
                return feedpet( p, mon, it, MF_CATFOOD,
                                _( "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines." ) );
            case CATTLEFODDER:
                return feedpet( p, mon, it, MF_CATTLEFODDER,
                                _( "The %s seems to like you!  It lets you pat its head and seems friendly." ) );
            case BIRDFOOD:
                return feedpet( p, mon, it, MF_BIRDFOOD,
                                _( "The %s seems to like you!  It runs around your legs and seems friendly." ) );
        }
    } else {
        p.add_msg_if_player( _( "There is nothing to be fed here." ) );
        return 0;
    }
    return 1;
}
References _, player::add_msg_if_player(), BIRDFOOD, CATFOOD, CATTLEFODDER, choose_adjacent(), Character::consume_charges(), Character::deal_damage(), monster::die(), DOGFOOD, DT_CUT, feedpet(), g, mtype::id, npc::is_ally(), monster::is_hallucination(), m_bad, npc::make_angry(), MF_BIRDFOOD, MF_CATFOOD, MF_CATTLEFODDER, MF_DOGFOOD, mon_dog_thing, Creature::moves, Character::name, mtype::nname(), one_in(), query_yn(), rng(), npc::say(), string_format(), item::tname(), monster::type, and x_in_y().
Referenced by iuse::catfood(), iuse::dogfood(), iuse::feedbird(), and iuse::feedcattle().
photo_def_for_camera_point()
static extended_photo_def photo_def_for_camera_point (const tripoint & aim_point, const tripoint & camera_pos, std::vector< monster * > & monster_vec, std::vector< player * > & player_vec) static
Definition at line 7097 of file iuse.cpp.
{
    // look for big items on top of stacks in the background for the selfie description
    const units::volume min_visible_volume = 490_ml;
    std::unordered_set<tripoint> ignored_points;
    std::unordered_set<const vehicle *> vehicles_recorded;
    std::unordered_map<std::string, std::string> description_figures_appearance;
    std::vector<std::pair<std::string, std::string>> description_figures_status;
    std::string timestamp = to_string( time_point( calendar::turn ) );
    int dist = rl_dist( camera_pos, aim_point );
    map &here = get_map();
    const tripoint_range<tripoint> bounds = here.points_in_radius( aim_point, 2 );
    extended_photo_def photo;
    bool need_store_weather = false;
    int outside_tiles_num = 0;
    int total_tiles_num = 0;
    const auto map_deincrement_or_erase = []( std::unordered_map<std::string, int> &obj_map,
    const std::string & key ) {
        if( obj_map.find( key ) != obj_map.end() ) {
            obj_map[ key ] --;
            if( obj_map[ key ] <= 0 ) {
                obj_map.erase( key );
            }
        }
    };
    // first scan for critters and mark nearby furniture, vehicles and items
    for( const tripoint &current : bounds ) {
        if( !g->m.sees( camera_pos, current, dist + 3 ) ) {
            continue; // disallow photos with non-visible objects
        }
        monster *const mon = g->critter_at<monster>( current, false );
        avatar *guy = g->critter_at<avatar>( current );
        total_tiles_num++;
        if( g->m.is_outside( current ) ) {
            need_store_weather = true;
            outside_tiles_num++;
        }
        if( guy || mon ) {
            std::string figure_appearance, figure_name, pose, pronoun_sex, figure_effects;
            Creature *creature;
            if( mon && mon->has_effect( effect_ridden ) ) {
                // only player can ride, see monexamine::mount_pet
                guy = &g->u;
                description_figures_appearance[ mon->name() ] = "\"" + mon->type->get_description() + "\"";
            }
            if( guy ) {
                if( guy->is_hallucination() ) {
                    continue; // do not include hallucinations
                }
                if( guy->movement_mode_is( CMM_CROUCH ) ) {
                    pose = _( "sits" );
                } else {
                    pose = _( "stands" );
                }
                const std::vector<std::string> vec = guy->short_description_parts();
                figure_appearance = join( vec, "\n\n" );
                figure_name = guy->name;
                pronoun_sex = guy->male ? _( "He" ) : _( "She" );
                creature = guy;
                player_vec.push_back( guy );
            } else {
                if( mon->is_hallucination() || mon->type->in_species( HALLUCINATION ) ) {
                    continue; // do not include hallucinations
                }
                pose = _( "stands" );
                figure_appearance = "\"" + mon->type->get_description() + "\"";
                figure_name = mon->name();
                pronoun_sex = pgettext( "Pronoun", "It" );
                creature = mon;
                monster_vec.push_back( mon );
            }
            figure_effects = effects_description_for_creature( creature, pose, pronoun_sex );
            description_figures_appearance[ figure_name ] = figure_appearance;
            object_names_collection obj_collection = enumerate_objects_around_point( current, 1, aim_point, 2,
                    camera_pos, min_visible_volume, true,
                    ignored_points, vehicles_recorded );
            std::string figure_text = pose + obj_collection.figure_text;
            if( !figure_effects.empty() ) {
                figure_text += " " + figure_effects;
            }
            if( !obj_collection.obj_nearby_text.empty() ) {
                figure_text += " " + obj_collection.obj_nearby_text;
            }
            auto name_text_pair = std::pair<std::string, std::string>( figure_name, figure_text );
            if( current == aim_point ) {
                description_figures_status.insert( description_figures_status.begin(), name_text_pair );
            } else {
                description_figures_status.push_back( name_text_pair );
            }
        }
    }
    // scan for everythin NOT near critters
    object_names_collection obj_coll = enumerate_objects_around_point( aim_point, 2, aim_point, 2,
                                       camera_pos, min_visible_volume, false,
                                       ignored_points, vehicles_recorded );
    std::string photo_text = _( "This is a photo of " );
    bool found_item_aim_point;
    std::string furn_desc = colorized_feature_description_at( aim_point, found_item_aim_point,
                            0_ml );
    const item item = get_top_item_at_point( aim_point, 0_ml );
    const std::string trap_name = colorized_trap_name_at( aim_point );
    std::string ter_name = colorized_ter_name_flags_at( aim_point, {}, {} );
    const std::string field_desc = colorized_field_description_at( aim_point );
    bool found_vehicle_aim_point = g->m.veh_at( aim_point ).has_value(),
         found_furniture_aim_point = !furn_desc.empty();
    // colorized_feature_description_at do not update flag if no furniture found, so need to check again
    if( !found_furniture_aim_point ) {
        found_item_aim_point = !item.is_null();
    }
    const ter_id ter_aim = g->m.ter( aim_point );
    const furn_id furn_aim = g->m.furn( aim_point );
    if( !description_figures_status.empty() ) {
        std::string names = enumerate_as_string( description_figures_status.begin(),
                            description_figures_status.end(),
        []( const std::pair<std::string, std::string> &it ) {
            return colorize( it.first, c_light_blue );
        } );
        photo.name = names;
        photo_text += names + ".";
        for( const auto &figure_status : description_figures_status ) {
            photo_text += "\n\n" + colorize( figure_status.first, c_light_blue )
                          + " " + figure_status.second;
        }
    } else if( found_vehicle_aim_point ) {
        const optional_vpart_position veh_part_pos = g->m.veh_at( aim_point );
        const std::string veh_name = colorize( veh_part_pos->vehicle().disp_name(), c_light_blue );
        photo.name = veh_name;
        photo_text += veh_name + ".";
        map_deincrement_or_erase( obj_coll.vehicles, veh_name );
    } else if( found_furniture_aim_point || found_item_aim_point )  {
        std::string item_name = colorized_item_name( item );
        if( found_furniture_aim_point ) {
            furn_desc = trap_name + furn_desc + field_desc;
            photo.name = furn_desc;
            photo_text += photo.name + ".";
            map_deincrement_or_erase( obj_coll.furniture, furn_desc );
        } else if( found_item_aim_point ) {
            item_name = trap_name + item_name + field_desc;
            photo.name = item_name;
            photo_text += item_name + ". " + string_format( _( "It lies on the %s." ),
                          ter_name );
            map_deincrement_or_erase( obj_coll.items, item_name );
        }
        if( found_furniture_aim_point && !furn_aim->description.empty() ) {
            photo_text += "\n\n" + colorize( furn_aim->name(), c_yellow ) + ":\n" + furn_aim->description;
        }
        if( found_item_aim_point ) {
            photo_text += "\n\n" + item_name + ":\n" + colorized_item_description( item );
        }
    } else {
        ter_name = trap_name + ter_name + field_desc;
        photo.name = ter_name;
        photo_text += photo.name + ".";
        map_deincrement_or_erase( obj_coll.terrain, ter_name );
        map_deincrement_or_erase( obj_coll.furniture, ter_name );
        if( !ter_aim->description.empty() ) {
            photo_text += "\n\n" + photo.name + ":\n" + ter_aim->description;
        }
    }
    auto num_of = []( const std::unordered_map<std::string, int> &m ) -> int {
        int ret = 0;
        for( const auto &it : m )
        {
            ret += it.second;
        }
        return ret;
    };
    if( !obj_coll.items.empty() ) {
        std::string obj_list = enumerate_as_string( obj_coll.items.begin(), obj_coll.items.end(),
                               format_object_pair_article );
        photo_text += "\n\n" + string_format( vgettext( "There is something lying on the ground: %s.",
                                              "There are some things lying on the ground: %s.", num_of( obj_coll.items ) ),
                                              obj_list );
    }
    if( !obj_coll.furniture.empty() ) {
        std::string obj_list = enumerate_as_string( obj_coll.furniture.begin(), obj_coll.furniture.end(),
                               format_object_pair_article );
        photo_text += "\n\n" + string_format( vgettext( "Something is visible in the background: %s.",
                                              "Some objects are visible in the background: %s.", num_of( obj_coll.furniture ) ),
                                              obj_list );
    }
    if( !obj_coll.vehicles.empty() ) {
        std::string obj_list = enumerate_as_string( obj_coll.vehicles.begin(), obj_coll.vehicles.end(),
                               format_object_pair_no_article );
        photo_text += "\n\n" + string_format( vgettext( "There is %s parked in the background.",
                                              "There are %s parked in the background.", num_of( obj_coll.vehicles ) ),
                                              obj_list );
    }
    if( !obj_coll.terrain.empty() ) {
        std::string obj_list = enumerate_as_string( obj_coll.terrain.begin(), obj_coll.terrain.end(),
                               format_object_pair_article );
        photo_text += "\n\n" + string_format( vgettext( "There is %s in the background.",
                                              "There are %s in the background.", num_of( obj_coll.terrain ) ),
                                              obj_list );
    }
    // TODO: fix point types
    const oter_id &cur_ter =
        overmap_buffer.ter( tripoint_abs_omt( ms_to_omt_copy( g->m.getabs( aim_point ) ) ) );
    std::string overmap_desc = string_format( _( "In the background you can see a %s" ),
                               colorize( cur_ter->get_name(), cur_ter->get_color() ) );
    if( outside_tiles_num == total_tiles_num ) {
        photo_text += _( "\n\nThis photo was taken <color_dark_gray>outside</color>." );
    } else if( outside_tiles_num == 0 ) {
        photo_text += _( "\n\nThis photo was taken <color_dark_gray>inside</color>." );
        overmap_desc += _( " interior" );
    } else if( outside_tiles_num < total_tiles_num / 2.0 ) {
        photo_text += _( "\n\nThis photo was taken mostly <color_dark_gray>inside</color>,"
                         " but <color_dark_gray>outside</color> can be seen." );
        overmap_desc += _( " interior" );
    } else if( outside_tiles_num >= total_tiles_num / 2.0 ) {
        photo_text += _( "\n\nThis photo was taken mostly <color_dark_gray>outside</color>,"
                         " but <color_dark_gray>inside</color> can be seen." );
    }
    photo_text += "\n" + overmap_desc + ".";
    if( g->get_levz() >= 0 && need_store_weather ) {
        photo_text += "\n\n";
        if( is_dawn( calendar::turn ) ) {
            photo_text += _( "It is <color_yellow>sunrise</color>. " );
        } else if( is_dusk( calendar::turn ) ) {
            photo_text += _( "It is <color_light_red>sunset</color>. " );
        } else if( is_night( calendar::turn ) ) {
            photo_text += _( "It is <color_dark_gray>night</color>. " );
        } else {
            photo_text += _( "It is day. " );
        }
        photo_text += string_format( _( "The weather is %s." ), colorize( get_weather().weather_id->name,
                                     get_weather().weather_id->color ) );
    }
    for( const auto &figure : description_figures_appearance ) {
        photo_text += "\n\n" + string_format( _( "%s appearance:" ),
                                              colorize( figure.first, c_light_blue ) ) + "\n" + figure.second;
    }
    photo_text += "\n\n" + string_format( pgettext( "Date", "The photo was taken on %s." ),
                                          colorize( timestamp, c_light_blue ) );
    photo.description = photo_text;
    return photo;
}
References _, c_light_blue, c_yellow, CMM_CROUCH, colorize(), colorized_feature_description_at(), colorized_field_description_at(), colorized_item_description(), colorized_item_name(), colorized_ter_name_flags_at(), colorized_trap_name_at(), creature, extended_photo_def::description, map_data_common_t::description, effect_ridden, effects_description_for_creature(), translation::empty(), enumerate_as_string(), enumerate_objects_around_point(), object_names_collection::figure_text, format_object_pair_article(), format_object_pair_no_article(), object_names_collection::furniture, g, oter_t::get_color(), mtype::get_description(), get_map(), oter_t::get_name(), get_top_item_at_point(), get_weather(), HALLUCINATION, Creature::has_effect(), mtype::in_species(), is_dawn(), is_dusk(), monster::is_hallucination(), is_night(), item::is_null(), object_names_collection::items, join(), ms_to_omt_copy(), extended_photo_def::name, map_data_common_t::name(), monster::name(), Name::names, object_names_collection::obj_nearby_text, overmap_buffer, pgettext(), map::points_in_radius(), cata::hash64_detail::ret, rl_dist(), string_format(), overmapbuffer::ter(), object_names_collection::terrain, to_string(), calendar::turn, monster::type, object_names_collection::vehicles, and vgettext().
Referenced by iuse::camera().
photo_quality_name()
static std::string photo_quality_name (const int index) static
Definition at line 6359 of file iuse.cpp.
{
    static const std::array<std::string, 6> names {
        {
            //~ photo quality adjective
            { translate_marker( "awful" ) }, { translate_marker( "bad" ) }, { translate_marker( "not bad" ) }, { translate_marker( "good" ) }, { translate_marker( "fine" ) }, { translate_marker( "exceptional" ) }
        }
    };
    return _( names[index] );
}
References _, Name::names, and translate_marker.
Referenced by iuse::camera(), iuse::einktabletpc(), and show_photo_selection().
pickveh()
static vehicle * pickveh (const tripoint & center, bool advanced) static
Definition at line 8215 of file iuse.cpp.
{
    static const std::string ctrl = "CTRL_ELECTRONIC";
    static const std::string advctrl = "REMOTE_CONTROLS";
    uilist pmenu;
    pmenu.title = _( "Select vehicle to access" );
    std::vector< vehicle * > vehs;
    for( auto &veh : g->m.get_vehicles() ) {
        auto &v = veh.v;
        if( rl_dist( center, v->global_pos3() ) < 40 &&
            v->fuel_left( itype_battery, true ) > 0 &&
            ( !empty( v->get_avail_parts( advctrl ) ) ||
              ( !advanced && !empty( v->get_avail_parts( ctrl ) ) ) ) ) {
            vehs.push_back( v );
        }
    }
    std::vector<tripoint> locations;
    for( int i = 0; i < static_cast<int>( vehs.size() ); i++ ) {
        auto veh = vehs[i];
        locations.push_back( veh->global_pos3() );
        pmenu.addentry( i, true, MENU_AUTOASSIGN, veh->name );
    }
    if( vehs.empty() ) {
        add_msg( m_bad, _( "No vehicle available." ) );
        return nullptr;
    }
    pointmenu_cb callback( locations );
    pmenu.callback = &callback;
    pmenu.w_y_setup = 0;
    pmenu.query();
    if( pmenu.ret < 0 || pmenu.ret >= static_cast<int>( vehs.size() ) ) {
        return nullptr;
    } else {
        return vehs[pmenu.ret];
    }
}
References _, add_msg(), uilist::addentry(), uilist::callback, center, g, itype_battery, anonymous_namespace{overmap_location.cpp}::locations, m_bad, MENU_AUTOASSIGN, uilist::query(), uilist::ret, rl_dist(), uilist::title, and uilist::w_y_setup.
Referenced by iuse::remoteveh().
remove_radio_mod()
void remove_radio_mod (item & it, player & p)
Definition at line 418 of file iuse.cpp.
{
    if( !it.has_flag( "RADIO_MOD" ) ) {
        return;
    }
    p.add_msg_if_player( _( "You remove the radio modification from your %s!" ), it.tname() );
    item mod( "radio_mod" );
    p.i_add_or_drop( mod, 1 );
    it.unset_flag( "RADIO_ACTIVATION" );
    it.unset_flag( "RADIO_MOD" );
    it.unset_flag( "RADIOSIGNAL_1" );
    it.unset_flag( "RADIOSIGNAL_2" );
    it.unset_flag( "RADIOSIGNAL_3" );
    it.unset_flag( "RADIOCARITEM" );
}
References _, player::add_msg_if_player(), item::has_flag(), Character::i_add_or_drop(), item::tname(), and item::unset_flag().
Referenced by crafting::complete_disassemble(), and iuse::radio_mod().
show_photo_selection()
static bool show_photo_selection (player & p, item & it, const std::string & var_name) static
Definition at line 7436 of file iuse.cpp.
{
    if( p.is_blind() ) {
        p.add_msg_if_player( _( "You can't see the camera screen, you're blind." ) );
        return false;
    }
    uilist pmenu;
    pmenu.text = _( "Photos saved on camera:" );
    std::vector<std::string> descriptions;
    std::vector<extended_photo_def> extended_photos;
    try {
        item_read_extended_photos( it, extended_photos, var_name );
    } catch( const JsonError &e ) {
        debugmsg( "Error reading photos: %s", e.c_str() );
    }
    try { // if there is old photos format, append them; delete old and save new
        if( item_read_extended_photos( it, extended_photos, "CAMERA_NPC_PHOTOS", true ) ) {
            it.erase_var( "CAMERA_NPC_PHOTOS" );
            item_write_extended_photos( it, extended_photos, var_name );
        }
    } catch( const JsonError &e ) {
        debugmsg( "Error migrating old photo format: %s", e.c_str() );
    }
    int k = 0;
    for( const extended_photo_def &extended_photo : extended_photos ) {
        std::string menu_str = extended_photo.name;
        size_t index = menu_str.find( p.name );
        if( index != std::string::npos ) {
            menu_str.replace( index, p.name.length(), _( "You" ) );
        }
        descriptions.push_back( extended_photo.description );
        menu_str += " [" + photo_quality_name( extended_photo.quality ) + "]";
        pmenu.addentry( k++, true, -1, menu_str.c_str() );
    }
    int choice;
    do {
        pmenu.query();
        choice = pmenu.ret;
        if( choice < 0 ) {
            break;
        }
        popup( "%s", descriptions[choice].c_str() );
    } while( true );
    return true;
}
References _, player::add_msg_if_player(), uilist::addentry(), JsonError::c_str(), debugmsg, item::erase_var(), Character::is_blind(), item_read_extended_photos(), item_write_extended_photos(), Character::name, photo_quality_name(), popup(), uilist::query(), uilist::ret, and uilist::text.
Referenced by iuse::camera(), and iuse::einktabletpc().
spawn_spores()
static void spawn_spores (const player & p) static
Definition at line 1234 of file iuse.cpp.
{
    int spores_spawned = 0;
    map &here = get_map();
    fungal_effects fe( *g, here );
    for( const tripoint &dest : closest_points_first( p.pos(), 4 ) ) {
        if( here.impassable( dest ) ) {
            continue;
        }
        float dist = rl_dist( dest, p.pos() );
        if( x_in_y( 1, dist ) ) {
            fe.marlossify( dest );
        }
        if( g->critter_at( dest ) != nullptr ) {
            continue;
        }
        if( one_in( 10 + 5 * dist ) && one_in( spores_spawned * 2 ) ) {
            if( monster *const spore = g->place_critter_at( mon_spore, dest ) ) {
                spore->friendly = -1;
                spores_spawned++;
            }
        }
    }
}
References closest_points_first(), g, get_map(), map::impassable(), fungal_effects::marlossify(), mon_spore, one_in(), Character::pos(), rl_dist(), and x_in_y().
Referenced by marloss_common().
toolweapon_off()
static int toolweapon_off (player & p, item & it, const bool fast_startup, const bool condition, const int volume, const std::string & msg_success, const std::string & msg_failure) static
Definition at line 3031 of file iuse.cpp.
{
    p.moves -= fast_startup ? 60 : 80;
    if( condition && it.units_sufficient( p ) ) {
        if( it.typeId() == itype_chainsaw_off ) {
            sfx::play_variant_sound( "chainsaw_cord", "chainsaw_on", sfx::get_heard_volume( p.pos() ) );
            sfx::play_variant_sound( "chainsaw_start", "chainsaw_on", sfx::get_heard_volume( p.pos() ) );
            sfx::play_ambient_variant_sound( "chainsaw_idle", "chainsaw_on", sfx::get_heard_volume( p.pos() ),
                                             sfx::channel::idle_chainsaw, 1000 );
            sfx::play_ambient_variant_sound( "weapon_theme", "chainsaw", sfx::get_heard_volume( p.pos() ),
                                             sfx::channel::chainsaw_theme,
                                             3000 );
        }
        sounds::sound( p.pos(), volume, sounds::sound_t::combat, msg_success );
        p.add_msg_if_player( msg_success );
        // 4 is the length of "_off".
        it.convert( itype_id( it.typeId().str().substr( 0, it.typeId().str().size() - 4 ) + "_on" ) );
        it.active = true;
        return it.type->charges_to_use();
    } else {
        if( it.typeId() == itype_chainsaw_off ) {
            sfx::play_variant_sound( "chainsaw_cord", "chainsaw_on", sfx::get_heard_volume( p.pos() ) );
        }
        p.add_msg_if_player( msg_failure );
        return 0; // No charges consumed on failure.
    }
}
References item::active, player::add_msg_if_player(), sfx::chainsaw_theme, itype::charges_to_use(), sounds::combat, item::convert(), sfx::get_heard_volume(), sfx::idle_chainsaw, itype_chainsaw_off, Creature::moves, sfx::play_ambient_variant_sound(), sfx::play_variant_sound(), Character::pos(), sounds::sound(), string_id< T >::str(), item::type, item::typeId(), and item::units_sufficient().
Referenced by iuse::carver_off(), iuse::chainsaw_off(), iuse::combatsaw_off(), iuse::cs_lajatang_off(), iuse::e_combatsaw_off(), iuse::ecs_lajatang_off(), iuse::elec_chainsaw_off(), and iuse::trimmer_off().
toolweapon_on()
static int toolweapon_on (player & p, item & it, const bool t, const std::string & tname, const bool works_underwater, const int sound_chance, const int volume, const std::string & sound, const bool double_charge_cost = false) static
Definition at line 3134 of file iuse.cpp.
{
    std::string off_type =
        it.typeId().str().substr( 0, it.typeId().str().size() - 3 ) +
        // 3 is the length of "_on".
        "_off";
    if( t ) { // Effects while simply on
        if( double_charge_cost && it.units_sufficient( p ) ) {
            it.ammo_consume( 1, p.pos() );
        }
        if( !works_underwater && p.is_underwater() ) {
            p.add_msg_if_player( _( "Your %s gurgles in the water and stops." ), tname );
            it.convert( itype_id( off_type ) ).active = false;
        } else if( one_in( sound_chance ) ) {
            sounds::ambient_sound( p.pos(), volume, sounds::sound_t::activity, sound );
        }
    } else { // Toggling
        if( it.typeId() == itype_chainsaw_on ) {
            sfx::play_variant_sound( "chainsaw_stop", "chainsaw_on", sfx::get_heard_volume( p.pos() ) );
            sfx::fade_audio_channel( sfx::channel::idle_chainsaw, 100 );
            sfx::fade_audio_channel( sfx::channel::chainsaw_theme, 3000 );
        }
        p.add_msg_if_player( _( "Your %s goes quiet." ), tname );
        it.convert( itype_id( off_type ) ).active = false;
        return 0; // Don't consume charges when turning off.
    }
    return it.type->charges_to_use();
}
References _, item::active, sounds::activity, player::add_msg_if_player(), sounds::ambient_sound(), item::ammo_consume(), sfx::chainsaw_theme, itype::charges_to_use(), item::convert(), sfx::fade_audio_channel(), sfx::get_heard_volume(), sfx::idle_chainsaw, Creature::is_underwater(), itype_chainsaw_on, one_in(), sfx::play_variant_sound(), Character::pos(), sounds::sound(), string_id< T >::str(), item::type, item::typeId(), and item::units_sufficient().
Referenced by iuse::carver_on(), iuse::chainsaw_on(), iuse::circsaw_on(), iuse::combatsaw_on(), iuse::cs_lajatang_on(), iuse::e_combatsaw_on(), iuse::ecs_lajatang_on(), iuse::elec_chainsaw_on(), and iuse::trimmer_on().
wash_items()
int wash_items (player * p, bool soft_items, bool hard_items) static
Definition at line 9452 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    p->inv.restack( *p );
    const inventory &crafting_inv = p->crafting_inventory();
    auto is_liquid = []( const item & it ) {
        return it.made_of( LIQUID ) || it.contents_made_of( LIQUID );
    };
    int available_water = std::max(
                              crafting_inv.charges_of( itype_water, INT_MAX, is_liquid ),
                              crafting_inv.charges_of( itype_water_clean, INT_MAX, is_liquid )
                          );
    int available_cleanser = std::max( crafting_inv.charges_of( itype_soap ),
                                       crafting_inv.charges_of( itype_detergent ) );
    iuse_locations to_clean = game_menus::inv::multiwash( *p, available_water, available_cleanser,
                              soft_items,
                              hard_items );
    if( to_clean.empty() ) {
        return 0;
    }
    // Determine if we have enough water and cleanser for all the items.
    units::volume total_volume = 0_ml;
    for( iuse_location iloc : to_clean ) {
        if( !iloc.loc ) {
            p->add_msg_if_player( m_info, _( "Never mind." ) );
            return 0;
        }
        item &i = *iloc.loc;
        total_volume += i.volume() * iloc.count / i.count();
    }
    washing_requirements required = washing_requirements_for_volume( total_volume );
    if( !crafting_inv.has_charges( itype_water, required.water, is_liquid ) &&
        !crafting_inv.has_charges( itype_water_clean, required.water, is_liquid ) ) {
        p->add_msg_if_player( _( "You need %1$i charges of water or clean water to wash these items." ),
                              required.water );
        return 0;
    } else if( !crafting_inv.has_charges( itype_soap, required.cleanser ) &&
               !crafting_inv.has_charges( itype_detergent, required.cleanser ) ) {
        p->add_msg_if_player( _( "You need %1$i charges of cleansing agent to wash these items." ),
                              required.cleanser );
        return 0;
    }
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    required.time = required.time * ( 10 - helpers.size() ) / 10;
    // Assign the activity values.
    p->assign_activity( wash_activity_actor( to_clean, required.time ) );
    return 0;
}
References _, add_msg(), player::add_msg_if_player(), Character::assign_activity(), visitable< T >::charges_of(), washing_requirements::cleanser, item::count(), Character::crafting_inventory(), g, inventory::has_charges(), Character::inv, Character::is_mounted(), itype_detergent, itype_soap, itype_water, itype_water_clean, LIQUID, m_info, game_menus::inv::multiwash(), inventory::restack(), washing_requirements::time, item::volume(), washing_requirements_for_volume(), and washing_requirements::water.
Referenced by iuse::wash_all_items(), iuse::wash_hard_items(), and iuse::wash_soft_items().
washing_requirements_for_volume()
washing_requirements washing_requirements_for_volume (const units::volume & vol)
Definition at line 9382 of file iuse.cpp.
{
    int water = divide_round_up( vol, 125_ml );
    int cleanser = divide_round_up( vol, 1_liter );
    int time = to_moves<int>( 10_seconds * ( vol / 250_ml ) );
    return { water, cleanser, time };
}
References divide_round_up(), and time.
Referenced by wash_activity_actor::finish(), game_menus::inv::multiwash(), and wash_items().
Variable Documentation
ACT_BURROW
const activity_id ACT_BURROW("ACT_BURROW") ("ACT_BURROW") static
Referenced by iuse::burrow().
ACT_CHOP_LOGS
const activity_id ACT_CHOP_LOGS("ACT_CHOP_LOGS") ("ACT_CHOP_LOGS") static
Referenced by iuse::chop_logs().
ACT_CHOP_PLANKS
const activity_id ACT_CHOP_PLANKS("ACT_CHOP_PLANKS") ("ACT_CHOP_PLANKS") static
Referenced by iuse::cut_log_into_planks().
ACT_CHOP_TREE
const activity_id ACT_CHOP_TREE("ACT_CHOP_TREE") ("ACT_CHOP_TREE") static
Referenced by iuse::chop_tree().
ACT_CHURN
const activity_id ACT_CHURN("ACT_CHURN") ("ACT_CHURN") static
Referenced by iuse::makemound().
ACT_CLEAR_RUBBLE
const activity_id ACT_CLEAR_RUBBLE("ACT_CLEAR_RUBBLE") ("ACT_CLEAR_RUBBLE") static
Referenced by iuse::clear_rubble().
ACT_CRAFT
const activity_id ACT_CRAFT("ACT_CRAFT") ("ACT_CRAFT") static
Referenced by iuse::craft().
ACT_FILL_PIT
const activity_id ACT_FILL_PIT("ACT_FILL_PIT") ("ACT_FILL_PIT") static
Referenced by iuse::fill_pit().
ACT_FISH
const activity_id ACT_FISH("ACT_FISH") ("ACT_FISH") static
Referenced by iuse::fishing_rod().
ACT_GAME
const activity_id ACT_GAME("ACT_GAME") ("ACT_GAME") static
Referenced by iuse::portable_game().
ACT_GENERIC_GAME
const activity_id ACT_GENERIC_GAME("ACT_GENERIC_GAME") ("ACT_GENERIC_GAME") static
Referenced by iuse::play_game().
ACT_HACKSAW
const activity_id ACT_HACKSAW("ACT_HACKSAW") ("ACT_HACKSAW") static
Referenced by iuse::hacksaw().
ACT_HAIRCUT
const activity_id ACT_HAIRCUT("ACT_HAIRCUT") ("ACT_HAIRCUT") static
Referenced by iuse::hairkit().
ACT_HAND_CRANK
const activity_id ACT_HAND_CRANK("ACT_HAND_CRANK") ("ACT_HAND_CRANK") static
Referenced by iuse::hand_crank().
ACT_JACKHAMMER
const activity_id ACT_JACKHAMMER("ACT_JACKHAMMER") ("ACT_JACKHAMMER") static
Referenced by iuse::jackhammer().
ACT_MEDITATE
const activity_id ACT_MEDITATE("ACT_MEDITATE") ("ACT_MEDITATE") static
Referenced by iuse::meditate().
ACT_MIND_SPLICER
const activity_id ACT_MIND_SPLICER("ACT_MIND_SPLICER") ("ACT_MIND_SPLICER") static
Referenced by iuse::mind_splicer().
ACT_OXYTORCH
const activity_id ACT_OXYTORCH("ACT_OXYTORCH") ("ACT_OXYTORCH") static
Referenced by iuse::oxytorch().
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
Referenced by iuse::pickaxe().
ACT_PRY_NAILS
const activity_id ACT_PRY_NAILS("ACT_PRY_NAILS") ("ACT_PRY_NAILS") static
Referenced by iuse::hammer().
ACT_ROBOT_CONTROL
const activity_id ACT_ROBOT_CONTROL("ACT_ROBOT_CONTROL") ("ACT_ROBOT_CONTROL") static
Referenced by iuse::robotcontrol().
ACT_SHAVE
const activity_id ACT_SHAVE("ACT_SHAVE") ("ACT_SHAVE") static
Referenced by iuse::shavekit().
ACT_VIBE
const activity_id ACT_VIBE("ACT_VIBE") ("ACT_VIBE") static
Referenced by iuse::vibe().
bio_eye_optic
const bionic_id bio_eye_optic("bio_eye_optic") ("bio_eye_optic") static
Referenced by iuse::einktabletpc(), and iuse::robotcontrol().
bio_shock
const bionic_id bio_shock("bio_shock") ("bio_shock") static
Referenced by iuse::ehandcuffs(), and Character::melee_special_effects().
camera_ter_whitelist_flags
const std::vector<std::string> camera_ter_whitelist_flags static
Initial value:
= {
    "HIDE_PLACE", "FUNGUS", "TREE", "PERMEABLE", "SHRUB",
    "PLACE_ITEM", "GROWTH_HARVEST", "GROWTH_MATURE", "GOES_UP",
    "GOES_DOWN", "RAMP", "SHARP", "SIGN", "CLIMBABLE"
}
Definition at line 407 of file iuse.cpp.
Referenced by enumerate_objects_around_point().
camera_ter_whitelist_types
const std::vector<ter_str_id> camera_ter_whitelist_types static
Initial value:
= {
    ter_str_id( "t_pit_covered" ), ter_str_id( "t_grave_new" ), ter_str_id( "t_grave" ), ter_str_id( "t_pit" ),
    ter_str_id( "t_pit_shallow" ), ter_str_id( "t_pit_corpsed" ), ter_str_id( "t_pit_spiked" ),
    ter_str_id( "t_pit_spiked_covered" ), ter_str_id( "t_pit_glass" ), ter_str_id( "t_pit_glass" ), ter_str_id( "t_utility_light" )
}
Definition at line 412 of file iuse.cpp.
Referenced by enumerate_objects_around_point().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by iuse::adrenaline_injector(), and iuse::artifact().
effect_antibiotic
const efftype_id effect_antibiotic("antibiotic") ("antibiotic") static
Referenced by iuse::antibiotic().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by iuse::inhaler(), and iuse::oxygen_bottle().
effect_attention
const efftype_id effect_attention("attention") ("attention") static
Referenced by iuse::artifact().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by effects_description_for_creature().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by effects_description_for_creature().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by iuse::camera(), and iuse::extinguisher().
effect_bloodworms
const efftype_id effect_bloodworms("bloodworms") ("bloodworms") static
Referenced by iuse::antiparasitic().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by effects_description_for_creature(), iuse::eyedrops(), and iuse::towel_common().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by effects_description_for_creature().
effect_brainworms
const efftype_id effect_brainworms("brainworms") ("brainworms") static
Referenced by iuse::antiparasitic().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by iuse::ecig(), and iuse::smoking().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by iuse::contacts(), iuse::einktabletpc(), iuse::multicooker(), and iuse::robotcontrol().
effect_corroding
const efftype_id effect_corroding("corroding") ("corroding") static
Referenced by effects_description_for_creature().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by effects_description_for_creature().
effect_datura
const efftype_id effect_datura("datura") ("datura") static
Referenced by iuse::datura().
effect_dazed
const efftype_id effect_dazed("dazed") ("dazed") static
Referenced by effects_description_for_creature().
effect_dermatik
const efftype_id effect_dermatik("dermatik") ("dermatik") static
Referenced by iuse::antiparasitic(), and iuse::thorazine().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by iuse::directional_hologram(), iuse::dog_whistle(), and iuse::robotcontrol().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by effects_description_for_creature().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by alcohol().
effect_earphones
const efftype_id effect_earphones("earphones") ("earphones") static
Referenced by iuse::play_music().
effect_foodpoison
const efftype_id effect_foodpoison("foodpoison") ("foodpoison") static
Referenced by iuse::poison().
effect_formication
const efftype_id effect_formication("formication") ("formication") static
Referenced by iuse::thorazine().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by iuse::antifungal(), and iuse::fungicide().
effect_glowing
const efftype_id effect_glowing("glowing") ("glowing") static
Referenced by effects_description_for_creature(), and iuse::towel_common().
effect_glowy_led
const efftype_id effect_glowy_led("glowy_led") ("glowy_led") static
Referenced by effects_description_for_creature().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by iuse::multicooker(), and iuse::thorazine().
effect_happy
const efftype_id effect_happy("happy") ("happy") static
Referenced by effects_description_for_creature().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by effects_description_for_creature().
effect_has_bag
const efftype_id effect_has_bag("has_bag") ("has_bag") static
Referenced by effects_description_for_creature().
effect_haslight
const efftype_id effect_haslight("haslight") ("haslight") static
Referenced by effects_description_for_creature().
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
Referenced by effects_description_for_creature().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by iuse::antibiotic(), iuse::strong_antibiotic(), and iuse::weak_antibiotic().
effect_jetinjector
const efftype_id effect_jetinjector("jetinjector") ("jetinjector") static
Referenced by iuse::jet_injector().
effect_lack_sleep
const efftype_id effect_lack_sleep("lack_sleep") ("lack_sleep") static
Referenced by effects_description_for_creature().
effect_laserlocked
const efftype_id effect_laserlocked("laserlocked") ("laserlocked") static
Referenced by effects_description_for_creature().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by effects_description_for_creature().
effect_melatonin_supplements
const efftype_id effect_melatonin_supplements("melatonin") ("melatonin") static
Referenced by iuse::melatonin_tablet().
effect_meth
const efftype_id effect_meth("meth") ("meth") static
Referenced by iuse::meth().
effect_monster_armor
const efftype_id effect_monster_armor("monster_armor") ("monster_armor") static
Referenced by effects_description_for_creature().
effect_music
const efftype_id effect_music("music") ("music") static
Referenced by iuse::play_music().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by effects_description_for_creature().
effect_paincysts
const efftype_id effect_paincysts("paincysts") ("paincysts") static
Referenced by iuse::antiparasitic().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by iuse::artifact(), and feedpet().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by iuse::blech(), and iuse::poison().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by photo_def_for_camera_point().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by effects_description_for_creature().
effect_run
const efftype_id effect_run("run") ("run") static
Referenced by multicooker_hallu().
effect_sad
const efftype_id effect_sad("sad") ("sad") static
Referenced by effects_description_for_creature().
effect_saddled
const efftype_id effect_saddled("monster_saddled") ("monster_saddled") static
Referenced by effects_description_for_creature().
effect_sap
const efftype_id effect_sap("sap") ("sap") static
Referenced by effects_description_for_creature().
effect_shakes
const efftype_id effect_shakes("shakes") ("shakes") static
Referenced by iuse::anticonvulsant(), and iuse::inhaler().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by effects_description_for_creature().
effect_slimed
const efftype_id effect_slimed("slimed") ("slimed") static
Referenced by effects_description_for_creature(), and iuse::towel_common().
effect_smoke
const efftype_id effect_smoke("smoke") ("smoke") static
Referenced by iuse::inhaler(), and iuse::oxygen_bottle().
effect_spores
const efftype_id effect_spores("spores") ("spores") static
Referenced by iuse::antifungal(), effects_description_for_creature(), and iuse::fungicide().
effect_stimpack
const efftype_id effect_stimpack("stimpack") ("stimpack") static
Referenced by iuse::stimpack().
effect_strong_antibiotic
const efftype_id effect_strong_antibiotic("strong_antibiotic") ("strong_antibiotic") static
Referenced by iuse::strong_antibiotic().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by iuse::artifact(), and effects_description_for_creature().
effect_tapeworm
const efftype_id effect_tapeworm("tapeworm") ("tapeworm") static
Referenced by iuse::antiparasitic().
effect_teargas
const efftype_id effect_teargas("teargas") ("teargas") static
Referenced by iuse::oxygen_bottle().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by iuse::artifact().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by effects_description_for_creature().
effect_took_antiasthmatic
const efftype_id effect_took_antiasthmatic("took_antiasthmatic") ("took_antiasthmatic") static
Referenced by iuse::antiasthmatic().
effect_took_flumed
const efftype_id effect_took_flumed("took_flumed") ("took_flumed") static
Referenced by iuse::flumed(), and iuse::flusleep().
effect_took_prozac
const efftype_id effect_took_prozac("took_prozac") ("took_prozac") static
Referenced by iuse::prozac().
effect_took_prozac_bad
const efftype_id effect_took_prozac_bad("took_prozac_bad") ("took_prozac_bad") static
Referenced by iuse::prozac().
effect_took_thorazine
const efftype_id effect_took_thorazine("took_thorazine") ("took_thorazine") static
Referenced by iuse::thorazine().
effect_took_xanax
const efftype_id effect_took_xanax("took_xanax") ("took_xanax") static
Referenced by iuse::xanax().
effect_valium
const efftype_id effect_valium("valium") ("valium") static
Referenced by iuse::anticonvulsant().
effect_visuals
const efftype_id effect_visuals("visuals") ("visuals") static
Referenced by iuse::multicooker(), and iuse::thorazine().
effect_weak_antibiotic
const efftype_id effect_weak_antibiotic("weak_antibiotic") ("weak_antibiotic") static
Referenced by iuse::weak_antibiotic().
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
Referenced by effects_description_for_creature().
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by iuse::weed_cake().
FUNGUS
const species_id FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by iuse::fungicide().
GROUP_FISH
const mongroup_id GROUP_FISH("GROUP_FISH") ("GROUP_FISH") static
Referenced by iuse::fish_trap().
HALLUCINATION
const species_id HALLUCINATION("HALLUCINATION") ("HALLUCINATION") static
Referenced by iuse::camera(), and photo_def_for_camera_point().
INSECT
const species_id INSECT("INSECT") ("INSECT") static
Referenced by iuse::granade_act().
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
Referenced by iuse::cable_attach(), and iuse::toolmod_attach().
itype_advanced_ecig
const itype_id itype_advanced_ecig("advanced_ecig") ("advanced_ecig") static
Referenced by iuse::ecig().
itype_afs_atomic_smartphone
const itype_id itype_afs_atomic_smartphone("afs_atomic_smartphone") ("afs_atomic_smartphone") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_afs_atomic_smartphone_music
const itype_id itype_afs_atomic_smartphone_music("afs_atomic_smartphone_music") ("afs_atomic_smartphone_music") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_afs_atomic_wraitheon_music
const itype_id itype_afs_atomic_wraitheon_music("afs_atomic_wraitheon_music") ("afs_atomic_wraitheon_music") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_afs_wraitheon_smartphone
const itype_id itype_afs_wraitheon_smartphone("afs_wraitheon_smartphone") ("afs_wraitheon_smartphone") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_apparatus
const itype_id itype_apparatus("apparatus") ("apparatus") static
Referenced by iuse::meth().
itype_arrow_flamming
const itype_id itype_arrow_flamming("arrow_flamming") ("arrow_flamming") static
Referenced by iuse::arrow_flammable().
itype_barometer
const itype_id itype_barometer("barometer") ("barometer") static
Referenced by iuse::weather_tool().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by pickveh(), and iuse::remoteveh().
itype_c4armed
const itype_id itype_c4armed("c4armed") ("c4armed") static
Referenced by iuse::c4().
itype_canister_empty
const itype_id itype_canister_empty("canister_empty") ("canister_empty") static
Referenced by iuse::can_goo().
itype_chainsaw_off
const itype_id itype_chainsaw_off("chainsaw_off") ("chainsaw_off") static
Referenced by toolweapon_off().
itype_chainsaw_on
const itype_id itype_chainsaw_on("chainsaw_on") ("chainsaw_on") static
Referenced by toolweapon_on().
itype_cig
const itype_id itype_cig("cig") ("cig") static
Referenced by iuse::smoking().
itype_cigar
const itype_id itype_cigar("cigar") ("cigar") static
Referenced by iuse::smoking().
itype_cow_bell
const itype_id itype_cow_bell("cow_bell") ("cow_bell") static
Referenced by iuse::bell().
itype_data_card
const itype_id itype_data_card("data_card") ("data_card") static
Referenced by iuse::mind_splicer().
itype_detergent
const itype_id itype_detergent("detergent") ("detergent") static
Referenced by wash_items().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by iuse::ehandcuffs().
itype_ecig
const itype_id itype_ecig("ecig") ("ecig") static
Referenced by iuse::ecig().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by iuse::arrow_flammable(), iuse::firecracker(), iuse::firecracker_pack(), iuse::meth(), and iuse::smoking().
itype_firecracker_act
const itype_id itype_firecracker_act("firecracker_act") ("firecracker_act") static
Referenced by iuse::firecracker().
itype_firecracker_pack_act
const itype_id itype_firecracker_pack_act("firecracker_pack_act") ("firecracker_pack_act") static
Referenced by iuse::firecracker_pack().
itype_geiger_off
const itype_id itype_geiger_off("geiger_off") ("geiger_off") static
Referenced by iuse::geiger().
itype_geiger_on
const itype_id itype_geiger_on("geiger_on") ("geiger_on") static
Referenced by iuse::geiger().
itype_granade_act
const itype_id itype_granade_act("granade_act") ("granade_act") static
Referenced by iuse::granade().
itype_handrolled_cig
const itype_id itype_handrolled_cig("handrolled_cig") ("handrolled_cig") static
Referenced by iuse::smoking().
itype_hygrometer
const itype_id itype_hygrometer("hygrometer") ("hygrometer") static
Referenced by iuse::weather_tool().
itype_joint
const itype_id itype_joint("joint") ("joint") static
Referenced by iuse::smoking().
itype_log
const itype_id itype_log("log") ("log") static
Referenced by iuse::lumber().
itype_mask_h20survivor_on
const itype_id itype_mask_h20survivor_on("mask_h20survivor_on") ("mask_h20survivor_on") static
Referenced by iuse::vibe().
itype_mininuke_act
const itype_id itype_mininuke_act("mininuke_act") ("mininuke_act") static
Referenced by iuse::mininuke().
itype_mobile_memory_card
const itype_id itype_mobile_memory_card("mobile_memory_card") ("mobile_memory_card") static
Referenced by iuse::camera().
itype_mobile_memory_card_used
const itype_id itype_mobile_memory_card_used("mobile_memory_card_used") ("mobile_memory_card_used") static
Referenced by einkpc_download_memory_card(), and iuse::einktabletpc().
itype_molotov
const itype_id itype_molotov("molotov") ("molotov") static
Referenced by iuse::molotov_lit().
itype_mp3
const itype_id itype_mp3("mp3") ("mp3") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_mp3_on
const itype_id itype_mp3_on("mp3_on") ("mp3_on") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_multi_cooker
const itype_id itype_multi_cooker("multi_cooker") ("multi_cooker") static
Referenced by iuse::multicooker().
itype_multi_cooker_filled
const itype_id itype_multi_cooker_filled("multi_cooker_filled") ("multi_cooker_filled") static
Referenced by iuse::multicooker().
itype_nicotine_liquid
const itype_id itype_nicotine_liquid("nicotine_liquid") ("nicotine_liquid") static
Referenced by iuse::ecig().
itype_noise_emitter
const itype_id itype_noise_emitter("noise_emitter") ("noise_emitter") static
Referenced by iuse::noise_emitter_on().
itype_noise_emitter_on
const itype_id itype_noise_emitter_on("noise_emitter_on") ("noise_emitter_on") static
Referenced by iuse::noise_emitter_off().
itype_radio
const itype_id itype_radio("radio") ("radio") static
Referenced by iuse::radio_on().
itype_radio_car
const itype_id itype_radio_car("radio_car") ("radio_car") static
Referenced by iuse::radiocaron().
itype_radio_car_on
const itype_id itype_radio_car_on("radio_car_on") ("radio_car_on") static
Referenced by iuse::radiocar().
itype_radio_on
const itype_id itype_radio_on("radio_on") ("radio_on") static
Referenced by iuse::directional_antenna(), and iuse::radio_off().
itype_rebreather_on
const itype_id itype_rebreather_on("rebreather_on") ("rebreather_on") static
Referenced by iuse::vibe().
itype_rebreather_xl_on
const itype_id itype_rebreather_xl_on("rebreather_xl_on") ("rebreather_xl_on") static
Referenced by iuse::vibe().
itype_rmi2_corpse
const itype_id itype_rmi2_corpse("rmi2_corpse") ("rmi2_corpse") static
Referenced by iuse::mind_splicer().
itype_shocktonfa_off
const itype_id itype_shocktonfa_off("shocktonfa_off") ("shocktonfa_off") static
Referenced by iuse::shocktonfa_on().
itype_shocktonfa_on
const itype_id itype_shocktonfa_on("shocktonfa_on") ("shocktonfa_on") static
Referenced by iuse::shocktonfa_off().
itype_smart_phone
const itype_id itype_smart_phone("smart_phone") ("smart_phone") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_smartphone_music
const itype_id itype_smartphone_music("smartphone_music") ("smartphone_music") static
Referenced by iuse::mp3(), and iuse::mp3_on().
itype_soap
const itype_id itype_soap("soap") ("soap") static
Referenced by wash_items().
itype_soldering_iron
const itype_id itype_soldering_iron("soldering_iron") ("soldering_iron") static
Referenced by iuse::multicooker().
itype_spiral_stone
const itype_id itype_spiral_stone("spiral_stone") ("spiral_stone") static
Referenced by iuse::vortex().
itype_thermometer
const itype_id itype_thermometer("thermometer") ("thermometer") static
Referenced by iuse::weather_tool().
itype_towel
const itype_id itype_towel("towel") ("towel") static
Referenced by iuse::towel_common().
itype_towel_soiled
const itype_id itype_towel_soiled("towel_soiled") ("towel_soiled") static
Referenced by iuse::towel_common().
itype_towel_wet
const itype_id itype_towel_wet("towel_wet") ("towel_wet") static
Referenced by iuse::towel_common().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by iuse::note_bionics().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by iuse::cable_attach(), and iuse::toolmod_attach().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by wash_items(), and iuse::water_purifier().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by wash_items(), and iuse::water_purifier().
itype_wax
const itype_id itype_wax("wax") ("wax") static
Referenced by iuse::honeycomb().
itype_weather_reader
const itype_id itype_weather_reader("weather_reader") ("weather_reader") static
Referenced by iuse::weather_tool().
mon_bee
const mtype_id mon_bee("mon_bee") ("mon_bee") static
Referenced by iuse::artifact().
mon_blob
const mtype_id mon_blob("mon_blob") ("mon_blob") static
Referenced by iuse::can_goo().
mon_dog_thing
const mtype_id mon_dog_thing("mon_dog_thing") ("mon_dog_thing") static
Referenced by petfood().
mon_fly
const mtype_id mon_fly("mon_fly") ("mon_fly") static
Referenced by iuse::artifact().
mon_hallu_multicooker
const mtype_id mon_hallu_multicooker("mon_hallu_multicooker") ("mon_hallu_multicooker") static
Referenced by multicooker_hallu().
mon_hologram
const mtype_id mon_hologram("mon_hologram") ("mon_hologram") static
Referenced by iuse::directional_hologram().
mon_shadow
const mtype_id mon_shadow("mon_shadow") ("mon_shadow") static
Referenced by iuse::artifact().
mon_spore
const mtype_id mon_spore("mon_spore") ("mon_spore") static
Referenced by iuse::fungicide(), and spawn_spores().
mon_vortex
const mtype_id mon_vortex("mon_vortex") ("mon_vortex") static
Referenced by iuse::vortex().
mon_wasp
const mtype_id mon_wasp("mon_wasp") ("mon_wasp") static
Referenced by iuse::artifact().
qual_AXE
const quality_id qual_AXE("AXE") ("AXE") static
Referenced by iuse::chop_moves().
qual_DIG
const quality_id qual_DIG("DIG") ("DIG") static
Referenced by iuse::dig(), and dig_pit_moves_and_byproducts().
RADIO_PER_TURN
constexpr int RADIO_PER_TURN = 25 static constexpr
Definition at line 361 of file iuse.cpp.
Referenced by iuse::radio_on().
ROBOT
const species_id ROBOT("ROBOT") ("ROBOT") static
Referenced by iuse::robotcontrol(), and iuse::robotcontrol_can_target().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by iuse::einktabletpc(), hackveh(), and iuse::robotcontrol().
skill_cooking
const skill_id skill_cooking("cooking") ("cooking") static
Referenced by iuse::multicooker().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by iuse::multicooker().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by iuse::multicooker().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by iuse::mind_splicer(), and iuse::pack_cbm().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by iuse::crowbar(), and iuse::gun_repair().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by iuse::tazer().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by iuse::fish_trap(), and iuse::multicooker().
trait_ACIDBLOOD
const trait_id trait_ACIDBLOOD("ACIDBLOOD") ("ACIDBLOOD") static
Referenced by iuse::blech(), and iuse::blood_draw().
trait_ACIDPROOF
const trait_id trait_ACIDPROOF("ACIDPROOF") ("ACIDPROOF") static
Referenced by iuse::blech().
trait_ALCMET
const trait_id trait_ALCMET("ALCMET") ("ALCMET") static
Referenced by alcohol().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by iuse::plantblech().
trait_EATDEAD
const trait_id trait_EATDEAD("EATDEAD") ("EATDEAD") static
Referenced by iuse::dig(), and iuse::poison().
trait_GILLS
const trait_id trait_GILLS("GILLS") ("GILLS") static
Referenced by iuse::vibe().
trait_GILLS_CEPH
const trait_id trait_GILLS_CEPH("GILLS_CEPH") ("GILLS_CEPH") static
Referenced by iuse::vibe().
trait_HYPEROPIC
const trait_id trait_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by iuse::contacts(), iuse::einktabletpc(), iuse::multicooker(), and iuse::robotcontrol().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by iuse::einktabletpc(), iuse::multicooker(), iuse::portable_game(), and iuse::robotcontrol().
trait_LIGHTWEIGHT
const trait_id trait_LIGHTWEIGHT("LIGHTWEIGHT") ("LIGHTWEIGHT") static
Referenced by alcohol(), iuse::anticonvulsant(), iuse::meth(), and iuse::weed_cake().
trait_M_DEPENDENT
const trait_id trait_M_DEPENDENT("M_DEPENDENT") ("M_DEPENDENT") static
Referenced by iuse::mycus().
trait_MARLOSS
const trait_id trait_MARLOSS("MARLOSS") ("MARLOSS") static
Referenced by iuse::marloss(), and marloss_common().
trait_MARLOSS_AVOID
const trait_id trait_MARLOSS_AVOID("MARLOSS_AVOID") ("MARLOSS_AVOID") static
Referenced by marloss_common(), and marloss_prevented().
trait_MARLOSS_BLUE
const trait_id trait_MARLOSS_BLUE("MARLOSS_BLUE") ("MARLOSS_BLUE") static
Referenced by marloss_common(), and iuse::marloss_seed().
trait_MARLOSS_YELLOW
const trait_id trait_MARLOSS_YELLOW("MARLOSS_YELLOW") ("MARLOSS_YELLOW") static
Referenced by marloss_common(), and iuse::marloss_gel().
trait_MYOPIC
const trait_id trait_MYOPIC("MYOPIC") ("MYOPIC") static
Referenced by iuse::contacts().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by iuse::antiparasitic(), and iuse::purify_iv().
trait_POISRESIST
const trait_id trait_POISRESIST("POISRESIST") ("POISRESIST") static
Referenced by iuse::poison().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by iuse::dig(), and iuse::einktabletpc().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by iuse::dig().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by iuse::datura(), iuse::dig(), and iuse::meditate().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by marloss_common(), and iuse::mycus().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by marloss_prevented(), and iuse::mycus().
trait_THRESH_PLANT
const trait_id trait_THRESH_PLANT("THRESH_PLANT") ("THRESH_PLANT") static
Referenced by iuse::plantblech().
trait_TOLERANCE
const trait_id trait_TOLERANCE("TOLERANCE") ("TOLERANCE") static
Referenced by alcohol(), iuse::anticonvulsant(), iuse::meth(), and iuse::weed_cake().
trait_URSINE_EYE
const trait_id trait_URSINE_EYE("URSINE_EYE") ("URSINE_EYE") static
Referenced by iuse::contacts().
trait_WAYFARER
const trait_id trait_WAYFARER("WAYFARER") ("WAYFARER") static
Referenced by iuse::remoteveh().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by iuse::pheromone().