Cataclysm BN: src/json_source_location.h File Reference
json_source_location.h File Reference
#include <string>
#include "memory_fast.h"
Classes
struct json_source_location
Macros
#define CATA_SRC_JSON_SOURCE_LOCATION_H
Functions
void throw_error_at_json_loc (const json_source_location &loc, const std::string &message)
Throw error at given JSON location.
void show_warning_at_json_loc (const json_source_location &loc, const std::string &message)
Show warning at given JSON location.
Macro Definition Documentation
CATA_SRC_JSON_SOURCE_LOCATION_H
#define CATA_SRC_JSON_SOURCE_LOCATION_H
Definition at line 3 of file json_source_location.h.
Function Documentation
show_warning_at_json_loc()
void show_warning_at_json_loc (const json_source_location & loc, const std::string & message)
Show warning at given JSON location.
Definition at line 22 of file json_source_location.cpp.
{
    try {
        throw_error_at_json_loc( loc, message );
    } catch( const JsonError &err ) {
        debugmsg( "%s", err.what() );
    }
}
References debugmsg, mapgen_defer::message, and throw_error_at_json_loc().
Referenced by relic_recharge::check().
throw_error_at_json_loc()
void throw_error_at_json_loc (const json_source_location & loc, const std::string & message)
Throw error at given JSON location.
Definition at line 6 of file json_source_location.cpp.
{
    if( !loc.path ) {
        throw JsonError( string_format( "Json error: (unknown pos): %s", message ) );
    }
    shared_ptr_fast<std::istream> stream = DynamicDataLoader::get_instance().get_cached_stream(
            *loc.path );
    if( !stream ) {
        throw JsonError( string_format( "Json error: (%s:%d): %s", *loc.path, loc.offset, message ) );
    }
    // Pass a new location with offset 0 so JsonIn stream would begin from the beginning of the file
    // and not from some old cached position.
    JsonIn jsin( *stream, json_source_location{ loc.path, 0 } );
    jsin.error( message, loc.offset );
}
References JsonIn::error(), DynamicDataLoader::get_cached_stream(), DynamicDataLoader::get_instance(), mapgen_defer::message, json_source_location::offset, json_source_location::path, and string_format().
Referenced by show_warning_at_json_loc().