Cataclysm BN: src/json.h File Reference
json.h File Reference
#include <array>
#include <bitset>
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "enum_conversions.h"
#include "json_source_location.h"
#include "memory_fast.h"
#include "string_id.h"
Classes
class JsonError
struct key_from_json_string< std::string, void >
struct key_from_json_string< string_id< T >, void >
struct key_from_json_string< Enum, std::enable_if_t< std::is_enum< Enum >::value > >
struct number_sci_notation
class JsonIn
class JsonOut
class JsonObject
class JsonArray
class JsonValue
class JsonArray::const_iterator
class JsonMember
Represents a member of a JsonObject.
class JsonObject::const_iterator
class JsonSerializer
class JsonDeserializer
Namespaces
namespace cata
Macros
#define CATA_SRC_JSON_H
Functions
void add_array_to_set (std::set< std::string > &, const JsonObject &json, const std::string &name)
Get an array member from json with name name.
std::ostream & operator<< (std::ostream &stream, const JsonError &err)
template<typename T >
void serialize (const cata::optional< T > &obj, JsonOut &jsout)
template<typename T >
void deserialize (cata::optional< T > &obj, JsonIn &jsin)
Macro Definition Documentation
CATA_SRC_JSON_H
#define CATA_SRC_JSON_H
Definition at line 3 of file json.h.
Function Documentation
add_array_to_set()
void add_array_to_set (std::set< std::string > & s, const JsonObject & json, const std::string & name)
Get an array member from json with name name.
For each element of that array (which should be a string) add it to the given set.
Definition at line 788 of file json.cpp.
{
    for( const std::string line : json.get_array( name ) ) {
        s.insert( line );
    }
}
References JsonObject::get_array(), line(), and om_direction::name().
Referenced by MonsterGroupManager::LoadMonsterBlacklist(), and MonsterGroupManager::LoadMonsterWhitelist().
deserialize()
template<typename T > void deserialize (cata::optional< T > & obj, JsonIn & jsin)
Definition at line 1439 of file json.h.
{
    if( jsin.test_null() ) {
        obj.reset();
    } else {
        obj.emplace();
        jsin.read( *obj, true );
    }
}
References int_id< T >::obj(), JsonIn::read(), and JsonIn::test_null().
Referenced by JsonIn::read().
operator<<()
std::ostream & operator<< (std::ostream & stream, const JsonError & err)
Definition at line 2130 of file json.cpp.
{
    return stream << err.what();
}
serialize()
template<typename T > void serialize (const cata::optional< T > & obj, JsonOut & jsout)
Definition at line 1429 of file json.h.
{
    if( obj ) {
        jsout.write( *obj );
    } else {
        jsout.write_null();
    }
}
References int_id< T >::obj(), JsonOut::write(), and JsonOut::write_null().
Referenced by JsonOut::write().