Cataclysm BN: src/language.cpp File Reference
language.cpp File Reference
#include "language.h"
#include <algorithm>
#include <fstream>
#include "cached_options.h"
#include "cata_libintl.h"
#include "catacharset.h"
#include "debug.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "json.h"
#include "mod_manager.h"
#include "name.h"
#include "options.h"
#include "path_info.h"
#include "string_utils.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "worldfactory.h"
Namespaces
namespace l10n_data
Macros
#define dbg(x) DebugLog((x), DC::Main)
Functions
std::string to_valid_language (const std::string &lang)
void update_global_locale ()
static language_info const * get_lang_info (const std::string &lang)
const std::vector< language_info > & list_available_languages ()
List of loaded language definitions.
static void reload_names ()
static std::string getSystemUILang ()
void set_language ()
Set language and locale to current value of USE_LANG option.
static std::vector< language_info > load_languages (const std::string &filepath)
bool init_language_system ()
Initialize language system (detect system UI language, load definitions).
void prompt_select_lang_on_startup ()
Prompt for explicit language selection.
const language_info & get_language ()
Current game language.
std::vector< std::string > get_lang_path_substring (const std::string &lang_id)
Get prioritized list of substrings for language-dependent file paths.
bool translations_exists_for_lang (const std::string &lang_id)
Check whether language has translation files compiled for it.
const trans_library & l10n_data::get_library ()
static void l10n_data::set_library (trans_library lib)
static void l10n_data::add_cat_if_exists (std::vector< trans_catalogue > &list, const std::string &lang_id, const std::string &path_start, const std::string &path_end)
static void l10n_data::add_mod_catalogue_if_exists (std::vector< trans_catalogue > &list, const std::string &lang_id, const std::string &mod_path)
static void l10n_data::add_base_catalogue (std::vector< trans_catalogue > &list, const std::string &lang_id)
static bool l10n_data::add_mod_catalogues (std::vector< trans_catalogue > &list, const std::string &lang_id)
void l10n_data::reload_catalogues ()
void l10n_data::unload_catalogues ()
void l10n_data::load_mod_catalogues ()
void l10n_data::unload_mod_catalogues ()
Variables
static std::string sys_c_locale
static std::string sys_cpp_locale
static language_info const * system_language = nullptr
static language_info const * current_language = nullptr
static language_info fallback_language = { "en", R"(English)", "en_US.UTF-8", { "n" }, "", { 1033 } }
std::vector< language_info > lang_options = { fallback_language }
static trans_library l10n_data::trans_lib_singleton
static bool l10n_data::mod_catalogues_loaded = false
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x), DC::Main)
Definition at line 36 of file language.cpp.
Function Documentation
get_lang_info()
static language_info const * get_lang_info (const std::string & lang) static
Definition at line 57 of file language.cpp.
{
    for( const language_info &li : lang_options ) {
        if( li.id == lang ) {
            return &li;
        }
    }
    return &fallback_language;
}
References fallback_language, and lang_options.
Referenced by init_language_system(), set_language(), and update_global_locale().
get_lang_path_substring()
std::vector< std::string > get_lang_path_substring (const std::string & lang_id)
Get prioritized list of substrings for language-dependent file paths.
The substrings can be used as file/folder names or as prefixes/suffixes.
Definition at line 381 of file language.cpp.
{
    std::vector<std::string> ret;
    const size_t p = lang_id.find( '_' );
    if( p == std::string::npos ) {
        // Dialect-agnostic id ('en', 'fr', 'de', etc.)
        ret.push_back( lang_id );
    } else {
        // Id with dialect specified ('en_US', 'fr_FR', etc.)
        // First try loading exact resource, then try dialect-agnostic resource.
        std::string lang_only = lang_id.substr( 0, p );
        ret.push_back( lang_id );
        ret.push_back( lang_only );
    }
    return ret;
}
References cata::hash64_detail::ret.
Referenced by l10n_data::add_cat_if_exists(), find_translated_file(), and translations_exists_for_lang().
get_language()
const language_info & get_language ()
Current game language.
May differ from USE_LANG option value if the option has been changed without subsequent set_language() call. If lang system has not been initialized, falls back to English.
Definition at line 329 of file language.cpp.
{
    if( current_language ) {
        return *current_language;
    } else {
        return fallback_language;
    }
}
References current_language, and fallback_language.
Referenced by find_translated_file(), gettext_gendered(), l10n_data::load_mod_catalogues(), l10n_data::reload_catalogues(), l10n_data::unload_mod_catalogues(), and translatable_mod_info::update().
getSystemUILang()
static std::string getSystemUILang () static
Definition at line 159 of file language.cpp.
{
    std::string ret;
    const char *language = getenv( "LANGUAGE" );
    if( language && language[0] != '\0' ) {
        ret = language;
    } else {
        const char *loc = setlocale( LC_MESSAGES, nullptr );
        if( loc != nullptr ) {
            ret = loc;
        }
    }
    if( ret == "C" || string_starts_with( ret, "C." ) ) {
        ret = "en";
    }
    return to_valid_language( ret );
}
References cata::hash64_detail::ret, string_starts_with(), and to_valid_language().
Referenced by init_language_system().
init_language_system()
bool init_language_system ()
Initialize language system (detect system UI language, load definitions).
Does not change current language/locale.
Definition at line 252 of file language.cpp.
{
    // OS X does not populate locale env vars correctly
    // (they usually default to "C") so don't bother
    // trying to set the locale based on them.
#if !defined(MACOSX)
    if( setlocale( LC_ALL, "" ) == nullptr ) {
        dbg( DL::Warn ) << "Error while setlocale(LC_ALL, '').";
    } else {
#endif
        try {
            std::locale::global( std::locale( "" ) );
        } catch( const std::exception & ) {
            // if user default locale retrieval isn't implemented by system
            try {
                // default to basic C locale
                std::locale::global( std::locale::classic() );
            } catch( const std::exception &err ) {
                dbg( DL::Error ) << err.what();
                return false;
            }
        }
#if !defined(MACOSX)
    }
#endif
    sys_c_locale = setlocale( LC_ALL, nullptr );
    sys_cpp_locale = std::locale().name();
    dbg( DL::Info ) << "C locale on startup: '" << sys_c_locale << "'";
    dbg( DL::Info ) << "C++ locale on startup: '" << sys_cpp_locale << "'";
    lang_options = load_languages( PATH_INFO::language_defs_file() );
    if( lang_options.empty() ) {
        lang_options = { fallback_language };
    }
    std::string lang = getSystemUILang();
    if( lang.empty() ) {
        system_language = nullptr;
        dbg( DL::Warn ) << "Failed to detect system UI language.";
    } else {
        system_language = get_lang_info( lang );
        dbg( DL::Info ) << "Detected system UI language as '" << lang << "'";
    }
    return true;
}
References dbg, Error, fallback_language, get_lang_info(), getSystemUILang(), Info, lang_options, PATH_INFO::language_defs_file(), load_languages(), sys_c_locale, sys_cpp_locale, system_language, and Warn.
Referenced by main().
list_available_languages()
const std::vector< language_info > & list_available_languages ()
List of loaded language definitions.
Always contains at least 1 language (English).
Definition at line 67 of file language.cpp.
{
    return lang_options;
}
References lang_options.
Referenced by options_manager::add_options_interface(), and game_info::game_report().
load_languages()
static std::vector< language_info > load_languages (const std::string & filepath) static
Definition at line 209 of file language.cpp.
{
    std::vector<language_info> ret;
    try {
        std::ifstream stream( filepath, std::ios_base::binary );
        if( !stream.is_open() ) {
            throw std::runtime_error( string_format( "File '%s' not found", filepath ) );
        }
        JsonIn json( stream );
        JsonArray arr = json.get_array();
        for( const JsonObject &obj : arr ) {
            language_info info;
            info.id = obj.get_string( "id" );
            info.name = obj.get_string( "name" );
            info.locale = obj.get_string( "locale" );
            info.genders = obj.get_string_array( "genders" );
            info.osx = obj.get_string( "osx", "" );
            info.lcids = obj.get_int_array( "lcids" );
            ret.push_back( info );
        }
    } catch( const std::exception &e ) {
        debugmsg( "[lang] Failed to read language definitions: %s", e.what() );
        return std::vector<language_info>();
    }
    // Sanity check genders
    const std::vector<std::string> all_genders = {{"f", "m", "n"}};
    for( language_info &info : ret ) {
        for( const std::string &g : info.genders ) {
            if( find( all_genders.begin(), all_genders.end(), g ) == all_genders.end() ) {
                debugmsg( "Unexpected gender '%s' in grammatical gender list for language '%d'",
                          g, info.id );
            }
        }
        if( info.genders.empty() ) {
            info.genders.push_back( "n" );
        }
    }
    return ret;
}
References debugmsg, detail::find(), g, language_info::genders, JsonIn::get_array(), language_info::id, language_info::lcids, language_info::locale, language_info::name, int_id< T >::obj(), language_info::osx, cata::hash64_detail::ret, and string_format().
Referenced by init_language_system().
prompt_select_lang_on_startup()
void prompt_select_lang_on_startup ()
Prompt for explicit language selection.
The prompt is skipped if using lang other than 'System language', or if lang autodetection succeeded.
Definition at line 300 of file language.cpp.
{
    if( !get_option<std::string>( "USE_LANG" ).empty() || system_language ) {
        return;
    }
    std::string res;
    if( lang_options.empty() ) {
        res = fallback_language.id;
    } else if( lang_options.size() == 1 ) {
        res = lang_options[0].id;
    } else {
        uilist sm;
        sm.allow_cancel = false;
        sm.text = _( "Select your language" );
        for( size_t i = 0; i < lang_options.size(); i++ ) {
            sm.addentry( i, true, MENU_AUTOASSIGN, lang_options[i].name );
        }
        sm.query();
        res = lang_options[sm.ret].id;
    }
    get_options().get_option( "USE_LANG" ).setValue( res );
    get_options().save();
    set_language();
}
References _, fallback_language, options_manager::get_option(), get_options(), language_info::id, lang_options, MENU_AUTOASSIGN, om_direction::name(), options_manager::save(), set_language(), options_manager::cOpt::setValue(), coords::sm, and system_language.
Referenced by main().
reload_names()
static void reload_names () static
Definition at line 75 of file language.cpp.
{
    Name::clear();
    Name::load_from_file( PATH_INFO::names() );
}
References Name::clear(), Name::load_from_file(), and PATH_INFO::names().
Referenced by set_language().
set_language()
void set_language ()
Set language and locale to current value of USE_LANG option.
If the value is empty, uses autodetected system language (or English, if autodetection failed) and system locale.
Definition at line 181 of file language.cpp.
{
    // Step 1. Choose language id
    std::string lang_opt = get_option<std::string>( "USE_LANG" );
    if( lang_opt.empty() ) {
        if( system_language ) {
            lang_opt = system_language->id;
            current_language = system_language;
        } else {
            lang_opt = fallback_language.id;
            current_language = &fallback_language;
        }
    } else {
        current_language = get_lang_info( lang_opt );
    }
    dbg( DL::Info ) << "Language set to '" << lang_opt << "'";
    // Step 2. Setup locale
    update_global_locale();
    // Step 3. Load translations for game and, possibly, mods
    l10n_data::reload_catalogues();
    // Step 4. Finalize
    reload_names();
}
References current_language, dbg, fallback_language, get_lang_info(), language_info::id, Info, l10n_data::reload_catalogues(), reload_names(), system_language, and update_global_locale().
Referenced by main(), prompt_select_lang_on_startup(), and options_manager::show().
to_valid_language()
std::string to_valid_language (const std::string & lang)
Definition at line 118 of file language.cpp.
{
    if( lang.empty() ) {
        return lang;
    }
    for( const language_info &info : lang_options ) {
        if( string_starts_with( lang, info.id ) ) {
            return info.id;
        }
    }
    const size_t p = lang.find( '_' );
    if( p != std::string::npos ) {
        std::string lang2 = lang.substr( 0, p );
        for( const language_info &info : lang_options ) {
            if( string_starts_with( lang2, info.id ) ) {
                return info.id;
            }
        }
    }
    return "";
}
References lang_options, and string_starts_with().
Referenced by getSystemUILang().
translations_exists_for_lang()
bool translations_exists_for_lang (const std::string & lang_id)
Check whether language has translation files compiled for it.
Definition at line 399 of file language.cpp.
{
    std::vector<std::string> opts = get_lang_path_substring( lang_id );
    for( const std::string &s : opts ) {
        std::string path = PATH_INFO::base_path() + "lang/mo/" + s + "/LC_MESSAGES/cataclysm-bn.mo";
        if( file_exist( path ) ) {
            return true;
        }
    }
    return false;
}
References PATH_INFO::base_path(), file_exist(), and get_lang_path_substring().
update_global_locale()
void update_global_locale ()
Definition at line 338 of file language.cpp.
{
#if defined(_WIN32)
    // Use the ANSI code page 1252 to work around some language output bugs.
    if( setlocale( LC_ALL, ".1252" ) == nullptr ) {
        dbg( DL::Warn ) << "Error while setlocale(LC_ALL, '.1252').";
    }
#else // _WIN32
    std::string lang = ::get_option<std::string>( "USE_LANG" );
    bool set_user = false;
    if( lang.empty() ) {
        // Restore user locale
        set_user = true;
    } else {
        // Try specific locale
        try {
            std::locale::global( std::locale( get_lang_info( lang )->locale ) );
        } catch( std::runtime_error &e ) {
            // Try fairly neutral UTF-8 locale
            try {
                std::locale::global( std::locale( fallback_language.locale ) );
            } catch( std::runtime_error &e ) {
                // No choice left
                set_user = true;
            }
        }
    }
    if( set_user ) {
        setlocale( LC_ALL, sys_c_locale.c_str() );
        try {
            std::locale::global( std::locale( sys_cpp_locale ) );
        } catch( std::runtime_error &e ) {
            std::locale::global( std::locale::classic() );
        }
    }
#endif // _WIN32
    dbg( DL::Info ) << "C locale set to '" << setlocale( LC_ALL, nullptr ) << "'";
    dbg( DL::Info ) << "C++ locale set to '" << std::locale().name() << "'";
}
References dbg, fallback_language, get_lang_info(), Info, language_info::locale, sys_c_locale, sys_cpp_locale, and Warn.
Referenced by set_language().
Variable Documentation
current_language
language_info const* current_language = nullptr static
Definition at line 51 of file language.cpp.
Referenced by get_language(), and set_language().
fallback_language
language_info fallback_language = { "en", R"(English)", "en_US.UTF-8", { "n" }, "", { 1033 } } static
Definition at line 53 of file language.cpp.
Referenced by get_lang_info(), get_language(), init_language_system(), prompt_select_lang_on_startup(), set_language(), and update_global_locale().
lang_options
std::vector<language_info> lang_options = { fallback_language }
Definition at line 55 of file language.cpp.
Referenced by options_manager::add_options_interface(), get_lang_info(), init_language_system(), list_available_languages(), prompt_select_lang_on_startup(), and to_valid_language().
sys_c_locale
std::string sys_c_locale static
Definition at line 41 of file language.cpp.
Referenced by init_language_system(), and update_global_locale().
sys_cpp_locale
std::string sys_cpp_locale static
Definition at line 42 of file language.cpp.
Referenced by init_language_system(), and update_global_locale().
system_language
language_info const* system_language = nullptr static
Definition at line 45 of file language.cpp.
Referenced by init_language_system(), prompt_select_lang_on_startup(), and set_language().