Cataclysm BN: src/language.h File Reference
language.h File Reference
#include <string>
#include <vector>
Classes
struct language_info
Contains information on a language supported by the game.
Namespaces
namespace cata_libintl
Runtime localization system for Cataclysm: Bright Nights.
namespace l10n_data
Macros
#define CATA_SRC_LANGUAGE_H
Functions
bool init_language_system ()
Initialize language system (detect system UI language, load definitions).
void prompt_select_lang_on_startup ()
Prompt for explicit language selection.
const std::vector< language_info > & list_available_languages ()
List of loaded language definitions.
void set_language ()
Set language and locale to current value of USE_LANG option.
const language_info & get_language ()
Current game language.
std::vector< std::string > get_lang_path_substring (const std::string &lang_id)
Get prioritized list of substrings for language-dependent file paths.
bool translations_exists_for_lang (const std::string &lang_id)
Check whether language has translation files compiled for it.
const trans_library & l10n_data::get_library ()
void l10n_data::reload_catalogues ()
void l10n_data::unload_catalogues ()
void l10n_data::load_mod_catalogues ()
void l10n_data::unload_mod_catalogues ()
Macro Definition Documentation
CATA_SRC_LANGUAGE_H
#define CATA_SRC_LANGUAGE_H
Definition at line 3 of file language.h.
Function Documentation
get_lang_path_substring()
std::vector< std::string > get_lang_path_substring (const std::string & lang_id)
Get prioritized list of substrings for language-dependent file paths.
The substrings can be used as file/folder names or as prefixes/suffixes.
Definition at line 381 of file language.cpp.
{
    std::vector<std::string> ret;
    const size_t p = lang_id.find( '_' );
    if( p == std::string::npos ) {
        // Dialect-agnostic id ('en', 'fr', 'de', etc.)
        ret.push_back( lang_id );
    } else {
        // Id with dialect specified ('en_US', 'fr_FR', etc.)
        // First try loading exact resource, then try dialect-agnostic resource.
        std::string lang_only = lang_id.substr( 0, p );
        ret.push_back( lang_id );
        ret.push_back( lang_only );
    }
    return ret;
}
References cata::hash64_detail::ret.
Referenced by l10n_data::add_cat_if_exists(), find_translated_file(), and translations_exists_for_lang().
get_language()
const language_info & get_language ()
Current game language.
May differ from USE_LANG option value if the option has been changed without subsequent set_language() call. If lang system has not been initialized, falls back to English.
Definition at line 329 of file language.cpp.
{
    if( current_language ) {
        return *current_language;
    } else {
        return fallback_language;
    }
}
References current_language, and fallback_language.
Referenced by find_translated_file(), gettext_gendered(), l10n_data::load_mod_catalogues(), l10n_data::reload_catalogues(), l10n_data::unload_mod_catalogues(), and translatable_mod_info::update().
init_language_system()
bool init_language_system ()
Initialize language system (detect system UI language, load definitions).
Does not change current language/locale.
Definition at line 252 of file language.cpp.
{
    // OS X does not populate locale env vars correctly
    // (they usually default to "C") so don't bother
    // trying to set the locale based on them.
#if !defined(MACOSX)
    if( setlocale( LC_ALL, "" ) == nullptr ) {
        dbg( DL::Warn ) << "Error while setlocale(LC_ALL, '').";
    } else {
#endif
        try {
            std::locale::global( std::locale( "" ) );
        } catch( const std::exception & ) {
            // if user default locale retrieval isn't implemented by system
            try {
                // default to basic C locale
                std::locale::global( std::locale::classic() );
            } catch( const std::exception &err ) {
                dbg( DL::Error ) << err.what();
                return false;
            }
        }
#if !defined(MACOSX)
    }
#endif
    sys_c_locale = setlocale( LC_ALL, nullptr );
    sys_cpp_locale = std::locale().name();
    dbg( DL::Info ) << "C locale on startup: '" << sys_c_locale << "'";
    dbg( DL::Info ) << "C++ locale on startup: '" << sys_cpp_locale << "'";
    lang_options = load_languages( PATH_INFO::language_defs_file() );
    if( lang_options.empty() ) {
        lang_options = { fallback_language };
    }
    std::string lang = getSystemUILang();
    if( lang.empty() ) {
        system_language = nullptr;
        dbg( DL::Warn ) << "Failed to detect system UI language.";
    } else {
        system_language = get_lang_info( lang );
        dbg( DL::Info ) << "Detected system UI language as '" << lang << "'";
    }
    return true;
}
References dbg, Error, fallback_language, get_lang_info(), getSystemUILang(), Info, lang_options, PATH_INFO::language_defs_file(), load_languages(), sys_c_locale, sys_cpp_locale, system_language, and Warn.
Referenced by main().
list_available_languages()
const std::vector< language_info > & list_available_languages ()
List of loaded language definitions.
Always contains at least 1 language (English).
Definition at line 67 of file language.cpp.
{
    return lang_options;
}
References lang_options.
Referenced by options_manager::add_options_interface(), and game_info::game_report().
prompt_select_lang_on_startup()
void prompt_select_lang_on_startup ()
Prompt for explicit language selection.
The prompt is skipped if using lang other than 'System language', or if lang autodetection succeeded.
Definition at line 300 of file language.cpp.
{
    if( !get_option<std::string>( "USE_LANG" ).empty() || system_language ) {
        return;
    }
    std::string res;
    if( lang_options.empty() ) {
        res = fallback_language.id;
    } else if( lang_options.size() == 1 ) {
        res = lang_options[0].id;
    } else {
        uilist sm;
        sm.allow_cancel = false;
        sm.text = _( "Select your language" );
        for( size_t i = 0; i < lang_options.size(); i++ ) {
            sm.addentry( i, true, MENU_AUTOASSIGN, lang_options[i].name );
        }
        sm.query();
        res = lang_options[sm.ret].id;
    }
    get_options().get_option( "USE_LANG" ).setValue( res );
    get_options().save();
    set_language();
}
References _, fallback_language, options_manager::get_option(), get_options(), language_info::id, lang_options, MENU_AUTOASSIGN, om_direction::name(), options_manager::save(), set_language(), options_manager::cOpt::setValue(), coords::sm, and system_language.
Referenced by main().
set_language()
void set_language ()
Set language and locale to current value of USE_LANG option.
If the value is empty, uses autodetected system language (or English, if autodetection failed) and system locale.
Definition at line 181 of file language.cpp.
{
    // Step 1. Choose language id
    std::string lang_opt = get_option<std::string>( "USE_LANG" );
    if( lang_opt.empty() ) {
        if( system_language ) {
            lang_opt = system_language->id;
            current_language = system_language;
        } else {
            lang_opt = fallback_language.id;
            current_language = &fallback_language;
        }
    } else {
        current_language = get_lang_info( lang_opt );
    }
    dbg( DL::Info ) << "Language set to '" << lang_opt << "'";
    // Step 2. Setup locale
    update_global_locale();
    // Step 3. Load translations for game and, possibly, mods
    l10n_data::reload_catalogues();
    // Step 4. Finalize
    reload_names();
}
References current_language, dbg, fallback_language, get_lang_info(), language_info::id, Info, l10n_data::reload_catalogues(), reload_names(), system_language, and update_global_locale().
Referenced by main(), prompt_select_lang_on_startup(), and options_manager::show().
translations_exists_for_lang()
bool translations_exists_for_lang (const std::string & lang_id)
Check whether language has translation files compiled for it.
Definition at line 399 of file language.cpp.
{
    std::vector<std::string> opts = get_lang_path_substring( lang_id );
    for( const std::string &s : opts ) {
        std::string path = PATH_INFO::base_path() + "lang/mo/" + s + "/LC_MESSAGES/cataclysm-bn.mo";
        if( file_exist( path ) ) {
            return true;
        }
    }
    return false;
}
References PATH_INFO::base_path(), file_exist(), and get_lang_path_substring().