Cataclysm BN: src/lightmap.cpp File Reference
lightmap.cpp File Reference
#include "lightmap.h"
#include "shadowcasting.h"
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <optional>
#include <utility>
#include <vector>
#include "avatar.h"
#include "calendar.h"
#include "cata_unreachable.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "cuboid_rectangle.h"
#include "field.h"
#include "fragment_cloud.h"
#include "game.h"
#include "int_id.h"
#include "item.h"
#include "item_stack.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "math_defines.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "player.h"
#include "point.h"
#include "string_formatter.h"
#include "submap.h"
#include "tileray.h"
#include "type_id.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
Classes
struct transparency_exp_lookup< n >
Functions
static constexpr point lightmap_boundary_max (LIGHTMAP_CACHE_X, LIGHTMAP_CACHE_Y)
template<int start, int iterations>
static int fast_rl_dist (tripoint to)
static constexpr quadrant quadrant_from_x_y (int x, int y)
template<int xx, int xy, int xz, int yx, int yy, int yz, int zz, typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate>
void cast_zlight_segment (const array_of_grids_of< T > &output_caches, const array_of_grids_of< const T > &input_arrays, const array_of_grids_of< const bool > &floor_caches, const array_of_grids_of< const diagonal_blocks > &blocked_caches, const tripoint &offset, int offset_distance, T numerator=1.0f, int row=1, float start_major=0.0f, float end_major=1.0f, float start_minor=0.0f, float end_minor=1.0f, T cumulative_transparency=LIGHT_TRANSPARENCY_OPEN_AIR, int x_skip=-1, int z_skip=-1)
template<typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate>
void cast_zlight (const array_of_grids_of< T > &output_caches, const array_of_grids_of< const T > &input_arrays, const array_of_grids_of< const bool > &floor_caches, const array_of_grids_of< const diagonal_blocks > &blocked_caches, const tripoint &origin, const int offset_distance, const T numerator)
template void cast_zlight< float, sight_calc, sight_check, accumulate_transparency > (const array_of_grids_of< float > &output_caches, const array_of_grids_of< const float > &input_arrays, const array_of_grids_of< const bool > &floor_caches, const array_of_grids_of< const diagonal_blocks > &blocked_caches, const tripoint &origin, int offset_distance, float numerator)
template void cast_zlight< float, shrapnel_calc, shrapnel_check, accumulate_fragment_cloud > (const array_of_grids_of< float > &output_caches, const array_of_grids_of< const float > &input_arrays, const array_of_grids_of< const bool > &floor_caches, const array_of_grids_of< const diagonal_blocks > &blocked_caches, const tripoint &origin, int offset_distance, float numerator)
static bool eq_nullptr_gcc_hack (const void *check)
template<int xx, int xy, int yx, int yy, typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, const transparency_exp_lookup< 90 > * lookup, T(*)(const T &, const T &, const int &) lookup_calc>
void castLight (Out(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const T(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, T numerator=VISIBILITY_FULL, int row=1, float start=1.0f, float end=0.0f, T cumulative_transparency=LIGHT_TRANSPARENCY_OPEN_AIR)
template<int xx, int xy, int yx, int yy, typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, T(*)(const T &, const T &, const int &) lookup_calc>
void castLightWithLookup (Out(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const T(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], const point &offset, int offsetDistance, T numerator=VISIBILITY_FULL, int row=1, float start=1.0f, float end=0.0f, T cumulative_transparency=LIGHT_TRANSPARENCY_OPEN_AIR)
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate>
void castLightAll (Out(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const T(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, T numerator)
template void castLightAll< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency > (four_quadrants(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const float(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, float numerator)
template void castLightAll< float, float, shrapnel_calc, shrapnel_check, update_fragment_cloud, accumulate_fragment_cloud > (float(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const float(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, float numerator)
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, T(*)(const T &, const T &, const int &) lookup_calc>
void castLightAllWithLookup (Out(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const T(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], const point &offset, int offsetDistance, T numerator)
template void castLightAllWithLookup< float, float, sight_calc, sight_check, update_light, accumulate_transparency, sight_from_lookup > (float(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const float(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], const point &offset, int offsetDistance, float numerator)
template void castLightAllWithLookup< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency, sight_from_lookup > (four_quadrants(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const float(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], const point &offset, int offsetDistance, float numerator)
static float fastexp (float x)
static float light_calc (const float &numerator, const float &transparency, const int &distance)
static bool light_check (const float &transparency, const float &intensity)
static float light_from_lookup (const float &numerator, const float &transparency, const int &distance)
Variables
static const efftype_id effect_haslight ("haslight")
static const efftype_id effect_onfire ("onfire")
static constexpr int LIGHTMAP_CACHE_X = MAPSIZE_X
static constexpr int LIGHTMAP_CACHE_Y = MAPSIZE_Y
static constexpr point lightmap_boundary_min {}
const half_open_rectangle< point > lightmap_boundaries (lightmap_boundary_min, lightmap_boundary_max)
const transparency_exp_lookup< 90 > openair_transparency_lookup (LIGHT_TRANSPARENCY_OPEN_AIR)
transparency_exp_lookup< 90 > weather_transparency_lookup (LIGHT_TRANSPARENCY_OPEN_AIR *1.1)
Function Documentation
cast_zlight()
template<typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate> void cast_zlight (const array_of_grids_of< T > & output_caches, const array_of_grids_of< const T > & input_arrays, const array_of_grids_of< const bool > & floor_caches, const array_of_grids_of< const diagonal_blocks > & blocked_caches, const tripoint & origin, const int offset_distance, const T numerator)
Definition at line 1116 of file lightmap.cpp.
{
    // Down
    cast_zlight_segment < 0, 1, 0, 1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 1, 0, 0, 0, 1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, 1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, 1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, 1, 0, -1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 1, 0, 0, 0, -1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, -1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, -1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    // Up
    cast_zlight_segment<0, 1, 0, 1, 0, 0, 1, T, calc, check, accumulate>(
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment<1, 0, 0, 0, 1, 0, 1, T, calc, check, accumulate>(
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, 1, 0, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, 1, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, 1, 0, -1, 0, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 1, 0, 0, 0, -1, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, -1, 0, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, -1, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
}
References cast_zlight_segment(), and detail::check().
cast_zlight< float, shrapnel_calc, shrapnel_check, accumulate_fragment_cloud >()
template void cast_zlight< float, shrapnel_calc, shrapnel_check, accumulate_fragment_cloud > (const array_of_grids_of< float > & output_caches, const array_of_grids_of< const float > & input_arrays, const array_of_grids_of< const bool > & floor_caches, const array_of_grids_of< const diagonal_blocks > & blocked_caches, const tripoint & origin, int offset_distance, float numerator)
cast_zlight< float, sight_calc, sight_check, accumulate_transparency >()
template void cast_zlight< float, sight_calc, sight_check, accumulate_transparency > (const array_of_grids_of< float > & output_caches, const array_of_grids_of< const float > & input_arrays, const array_of_grids_of< const bool > & floor_caches, const array_of_grids_of< const diagonal_blocks > & blocked_caches, const tripoint & origin, int offset_distance, float numerator)
Referenced by map::build_seen_cache().
cast_zlight_segment()
template<int xx, int xy, int xz, int yx, int yy, int yz, int zz, typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate> void cast_zlight_segment (const array_of_grids_of< T > & output_caches, const array_of_grids_of< const T > & input_arrays, const array_of_grids_of< const bool > & floor_caches, const array_of_grids_of< const diagonal_blocks > & blocked_caches, const tripoint & offset, int offset_distance, T numerator = 1.0f, int row = 1, float start_major = 0.0f, float end_major = 1.0f, float start_minor = 0.0f, float end_minor = 1.0f, T cumulative_transparency = LIGHT_TRANSPARENCY_OPEN_AIR, int x_skip = -1, int z_skip = -1)
Definition at line 903 of file lightmap.cpp.
{
    if( start_major >= end_major || start_minor > end_minor ) {
        return;
    }
    constexpr quadrant quad = quadrant_from_x_y( xx + xy, yx + yy );
    const auto check_blocked = [ =, &blocked_caches]( const tripoint & p ) -> bool{
        switch( quad )
        {
            case quadrant::NW:
                return ( *blocked_caches[p.z + OVERMAP_DEPTH] )[p.x][p.y].nw;
                break;
            case quadrant::NE:
                return ( *blocked_caches[p.z + OVERMAP_DEPTH] )[p.x][p.y].ne;
                break;
            case quadrant::SE:
                return ( p.x < MAPSIZE_X - 1 && p.y < MAPSIZE_Y - 1 &&
                         ( *blocked_caches[p.z + OVERMAP_DEPTH] )[p.x + 1][p.y + 1].nw );
                break;
            case quadrant::SW:
                return ( p.x > 1 && p.y < MAPSIZE_Y - 1 &&
                         ( *blocked_caches[p.z + OVERMAP_DEPTH] )[p.x - 1][p.y + 1].ne );
                break;
        }
        cata::unreachable();
    };
    int radius = 60 - offset_distance;
    constexpr int min_z = -OVERMAP_DEPTH;
    constexpr int max_z = OVERMAP_HEIGHT;
    T last_intensity = 0.0f;
    tripoint delta;
    tripoint current;
    for( int distance = row; distance <= radius; distance++ ) {
        delta.y = distance;
        bool started_block = false;
        T current_transparency = 0.0f;
        bool current_floor = false;
        int z_start = z_skip != -1 ? z_skip : std::max( 0,
                      static_cast<int>( std::ceil( ( ( distance - 0.5f ) * start_major ) - 0.5f ) ) );
        int z_limit = std::min( distance,
                                static_cast<int>( std::ceil( ( ( distance + 0.5f ) * end_major ) + 0.5f ) ) - 1 );
        for( delta.z = z_start; delta.z <= std::min( fov_3d_z_range, z_limit ); delta.z++ ) {
            current.z = offset.z + delta.x * 00 + delta.y * 00 + delta.z * zz;
            if( current.z > max_z || current.z < min_z ) {
                continue;
            }
            const int z_index = current.z + OVERMAP_DEPTH;
            int x_start = x_skip != -1 ? x_skip : std::max( 0,
                          static_cast<int>( std::ceil( ( ( distance - 0.5f ) * start_minor ) - 0.5f ) ) );
            int x_limit = std::min( distance,
                                    static_cast<int>( std::ceil( ( ( distance + 0.5f ) * end_minor ) + 0.5f ) ) - 1 );
            for( delta.x = x_start; delta.x <= x_limit; delta.x++ ) {
                current.x = offset.x + delta.x * xx + delta.y * xy + delta.z * xz;
                current.y = offset.y + delta.x * yx + delta.y * yy + delta.z * yz;
                if( !( current.x >= 0 && current.y >= 0 &&
                       current.x < MAPSIZE_X &&
                       current.y < MAPSIZE_Y ) ) {
                    continue;
                }
                if( check_blocked( current ) ) {
                    //We can just ignore the sliver of light that goes through vehicle holes
                    return;
                }
                T new_transparency = ( *input_arrays[z_index] )[current.x][current.y];
                bool new_floor;
                if( zz < 0 ) {
                    //Going down it's the current level's floor
                    new_floor = ( *floor_caches[z_index] )[current.x][current.y];
                } else {
                    //Going up it's the next level's floor
                    new_floor = z_index < OVERMAP_LAYERS - 1 ? ( *floor_caches[z_index + 1] )[current.x][current.y] :
                                false;
                }
                if( !started_block ) {
                    started_block = true;
                    current_transparency = new_transparency;
                    current_floor = new_floor;
                }
                const int dist = rl_dist( tripoint_zero, delta ) + offset_distance;
                T last_intensity = calc( numerator, cumulative_transparency, dist );
                ( *output_caches[z_index] )[current.x][current.y] =
                    std::max( ( *output_caches[z_index] )[current.x][current.y], last_intensity );
                //Check if this tile matches the previous one
                if( new_transparency != current_transparency || new_floor != current_floor ) {
                    // If not we need to split the blocks
                    // We split the block into 3 sub-blocks.
                    // +---+---+ <- end major
                    // | B | C |
                    // +---+---+ <- mid major
                    // |   A   |
                    // +-------+ <- start major
                    // ^   ^   ^
                    // |   |   end minor
                    // |   mid minor
                    // start minor
                    // A is any previously completed rows, it will be recursively cast a level deeper
                    // B is already processed tiles from the current row, this call will continue to process this
                    // C is the rest of the current row, including the current tile
                    // The seams could be incorrect, there's no promise the relationship between the unchecked blocks holds, it's minor error though
                    // Because A and B are the same transparency it doesn't matter where the seam between them goes, so we make sure it's correct for the seam with C
                    const float mid_major = current_transparency < new_transparency ? ( delta.z - 0.5f ) /
                                            ( delta.y - 0.5f ) : ( delta.z - 0.5f ) / ( delta.y + 0.5f );
                    if( delta.z != z_start && check( current_transparency, last_intensity ) ) {
                        //We don't need to cast section A if it's 0 height or opaque
                        T next_cumulative_transparency = accumulate( cumulative_transparency, current_transparency,
                                                         distance );
                        cast_zlight_segment<xx, xy, xz, yx, yy, yz, zz, T, calc, check, accumulate>(
                            output_caches, input_arrays, floor_caches, blocked_caches,
                            offset, offset_distance, numerator, distance + 1,
                            start_major, std::min( mid_major, end_major ), start_minor, end_minor,
                            next_cumulative_transparency );
                    }
                    const float mid_minor = current_transparency < new_transparency ? ( delta.x - 0.5f ) /
                                            ( delta.y - 0.5f ) : ( delta.x - 0.5f ) / ( delta.y + 0.5f );
                    //Section C is always cast.
                    cast_zlight_segment<xx, xy, xz, yx, yy, yz, zz, T, calc, check, accumulate>(
                        output_caches, input_arrays, floor_caches, blocked_caches,
                        offset, offset_distance, numerator, distance,
                        std::max( mid_major, start_major ), end_major, std::max( mid_minor, start_minor ), end_minor,
                        cumulative_transparency, delta.x, delta.z );
                    //Go on to handle section B
                    //This doesn't count as starting a new block, as we've already done one line of this block
                    if( delta.x == x_start ) {
                        //If B is 0 width we're done
                        return;
                    }
                    start_major = std::max( start_major, mid_major );
                    end_minor = std::min( end_minor, mid_minor );
                    //We check start and end minor for equality as well here
                    //This prevents an artifact where a transparent wall meeting an opaque wall at a corner allows you to see the corner of the roof
                    if( start_major >= end_major || start_minor >= end_minor ) {
                        return;
                    }
                    z_start = delta.z;
                    break;
                }
            }
            //Before we start the next z level we need to check there isn't a floor splitting up our blocks.
            if( current_floor ) {
                if( check( current_transparency, last_intensity ) ) {
                    //If there is we cast the current z level 1 deeper trimming it for the floor
                    T next_cumulative_transparency = accumulate( cumulative_transparency, current_transparency,
                                                     distance );
                    const float top_edge = ( delta.z + 0.5f ) / ( delta.y + 0.5001f );
                    cast_zlight_segment<xx, xy, xz, yx, yy, yz, zz, T, calc, check, accumulate>(
                        output_caches, input_arrays, floor_caches, blocked_caches,
                        offset, offset_distance, numerator, distance + 1,
                        start_major, top_edge, start_minor, end_minor,
                        next_cumulative_transparency );
                }
                //And then continue with the remaining z levels ourselves in a new block
                start_major = ( delta.z + 0.5f ) / ( delta.y - 0.5001f );
                if( start_major >= end_major ) {
                    return;
                }
                z_start = delta.z + 1;
                started_block = false;
                z_skip = -1;
            }
        }
        if( !check( current_transparency, last_intensity ) ) {
            // If we reach the end of the span with terrain being opaque, we don't iterate further.
            break;
        }
        // Cumulative average of the values encountered.
        cumulative_transparency = accumulate( cumulative_transparency, current_transparency, distance );
        z_skip = -1;
        x_skip = -1;
    }
}
References detail::check(), fov_3d_z_range, MAPSIZE_X, MAPSIZE_Y, NE, NW, OVERMAP_DEPTH, OVERMAP_HEIGHT, OVERMAP_LAYERS, quadrant_from_x_y(), rl_dist(), SE, SW, tripoint_zero, cata::unreachable(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by cast_zlight().
castLight()
template<int xx, int xy, int yx, int yy, typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, const transparency_exp_lookup< 90 > * lookup, T(*)(const T &, const T &, const int &) lookup_calc> void castLight (Out(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const T(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, T numerator = VISIBILITY_FULL, int row = 1, float start = 1.0f, float end = 0.0f, T cumulative_transparency = LIGHT_TRANSPARENCY_OPEN_AIR)
Definition at line 1215 of file lightmap.cpp.
{
    constexpr quadrant quad = quadrant_from_x_y( -xx - xy, -yx - yy );
    const auto check_blocked = [ =, &blocked_array]( point  p ) {
        switch( quad ) {
            case quadrant::NW:
                return blocked_array[p.x][p.y].nw;
                break;
            case quadrant::NE:
                return blocked_array[p.x][p.y].ne;
                break;
            case quadrant::SE:
                return ( p.x < MAPSIZE_X - 1 && p.y < MAPSIZE_Y - 1 && blocked_array[p.x + 1][p.y + 1].nw );
                break;
            case quadrant::SW:
                return ( p.x > 1 && p.y < MAPSIZE_Y - 1 && blocked_array[p.x - 1][p.y + 1].ne );
                break;
        }
        cata::unreachable();
    };
    int radius = 60 - offsetDistance;
    if( start < end ) {
        return;
    }
    T last_intensity = 0.0;
    tripoint delta;
    for( int distance = row; distance <= radius; distance++ ) {
        delta.y = -distance;
        bool started_row = false;
        T current_transparency = 0.0;
        //We initialize delta.x to -distance adjusted so that the commented start < leadingEdge condition below is never false
        delta.x = std::ceil( std::max( static_cast<float>( -distance ),
                                       ( ( -distance - 0.5f ) * start ) - 0.5f ) );
        //And a limit so that the commented end > trailingEdge is never true
        int x_limit = std::floor( std::min( 0.0f,
                                            ( ( -distance + 0.5f ) * end ) - 0.5f ) ) + 1;
        int last_dist = -1;
        for( ; delta.x <= x_limit; delta.x++ ) {
            point current( offset.x + delta.x * xx + delta.y * xy, offset.y + delta.x * yx + delta.y * yy );
            if( !( current.x >= 0 && current.y >= 0 && current.x < MAPSIZE_X &&
                   current.y < MAPSIZE_Y ) /* || start < leadingEdge */ ) {
                continue;
            } /*else if( end > trailingEdge ) {
                break;
            }*/
            if( check_blocked( current ) ) {
                continue;
            }
            if( !started_row ) {
                started_row = true;
                current_transparency = input_array[ current.x ][ current.y ];
            }
            if( !eq_nullptr_gcc_hack( lookup ) ) {
                //Only use fast dist on fast paths, it's slower otherwise. Floating point conversion thing maybe?
                const int dist = fast_rl_dist<21, 4>( delta ) + offsetDistance;
                last_intensity = lookup_calc( numerator, lookup->values[dist], dist );
            } else {
                const int dist = rl_dist( tripoint_zero, delta ) + offsetDistance;
                //Only avoid recalculation on the slow path, it's faster to avoid the branch on the fast path
                if( last_dist != dist ) {
                    last_intensity = calc( numerator, cumulative_transparency, dist );
                    last_dist = dist;
                }
            }
            T new_transparency = input_array[ current.x ][ current.y ];
            if( check( new_transparency, last_intensity ) ) {
                update_output( output_cache[current.x][current.y], last_intensity,
                               quadrant::default_ );
            } else {
                update_output( output_cache[current.x][current.y], last_intensity, quad );
            }
            if( new_transparency == current_transparency ) {
                continue;
            }
            float trailingEdge = ( delta.x - 0.5f ) / ( delta.y + 0.5f );
            // Only cast recursively if previous span was not opaque.
            if( check( current_transparency, last_intensity ) ) {
                //Are we moving off a fast path?
                if( !eq_nullptr_gcc_hack( lookup ) && current_transparency != lookup->transparency ) {
                    castLight < xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate, nullptr, nullptr >
                    (
                        output_cache, input_array, blocked_array, offset, offsetDistance,
                        numerator, distance + 1, start, trailingEdge,
                        accumulate( lookup->transparency, current_transparency, distance ) );
                } else {
                    T recursive_transparency = cumulative_transparency;
                    if( eq_nullptr_gcc_hack( lookup ) ) {
                        recursive_transparency = accumulate( cumulative_transparency, current_transparency, distance );
                    }
                    //Stay on path
                    castLight < xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate, lookup, lookup_calc > (
                        output_cache, input_array, blocked_array, offset, offsetDistance,
                        numerator, distance + 1, start, trailingEdge,
                        recursive_transparency );
                }
            }
            // The new span starts at the leading edge of the previous square if it is opaque,
            // and at the trailing edge of the current square if it is transparent.
            if( !check( current_transparency, last_intensity ) ) {
                start = ( delta.x - 0.5f ) / ( delta.y - 0.5f );
            } else {
                // Note this is the same slope as the recursive call we just made.
                start = trailingEdge;
            }
            // Trailing edge ahead of leading edge means this span is fully processed.
            if( start < end ) {
                return;
            }
            current_transparency = new_transparency;
        }
        if( !check( current_transparency, last_intensity ) ) {
            // If we reach the end of the span with terrain being opaque, we don't iterate further.
            break;
        }
        //We can't iterate normally if we're coming off a fast path, we have to recur
        if( !eq_nullptr_gcc_hack( lookup ) && current_transparency != lookup->transparency ) {
            castLight<xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate, nullptr, nullptr>
            (
                output_cache, input_array, blocked_array, offset, offsetDistance,
                numerator, distance + 1, start, end,
                accumulate( lookup->transparency, current_transparency, distance ) );
            return;
        }
        // Cumulative average of the transparency values encountered, not needed on fast paths
        if( eq_nullptr_gcc_hack( lookup ) ) {
            cumulative_transparency = accumulate( cumulative_transparency, current_transparency, distance );
        }
    }
}
References detail::check(), default_, eq_nullptr_gcc_hack(), MAPSIZE_X, MAPSIZE_Y, NE, NW, quadrant_from_x_y(), rl_dist(), SE, SW, transparency_exp_lookup< n >::transparency, tripoint_zero, cata::unreachable(), transparency_exp_lookup< n >::values, point::x, tripoint::x, point::y, and tripoint::y.
Referenced by castLightAll().
castLightAll()
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate> void castLightAll (Out(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const T(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, T numerator)
Definition at line 1423 of file lightmap.cpp.
{
    castLight< 0, 1, 1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight< 1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 0, -1, 1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < -1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 0, 1, -1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 0, -1, -1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < -1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
}
References castLight(), and detail::check().
Referenced by explosion_handler::shrapnel().
castLightAll< float, float, shrapnel_calc, shrapnel_check, update_fragment_cloud, accumulate_fragment_cloud >()
template void castLightAll< float, float, shrapnel_calc, shrapnel_check, update_fragment_cloud, accumulate_fragment_cloud > (float(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const float(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, float numerator)
castLightAll< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency >()
template void castLightAll< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency > (four_quadrants(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const float(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance, float numerator)
castLightAllWithLookup()
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, T(*)(const T &, const T &, const int &) lookup_calc> void castLightAllWithLookup (Out(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const T(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], const point & offset, int offsetDistance, T numerator)
Definition at line 1538 of file lightmap.cpp.
{
    castLightWithLookup< 0, 1, 1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup< 1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, lookup_calc>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 0, -1, 1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < -1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 0, 1, -1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 0, -1, -1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < -1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
}
References castLightWithLookup(), and detail::check().
castLightAllWithLookup< float, float, sight_calc, sight_check, update_light, accumulate_transparency, sight_from_lookup >()
template void castLightAllWithLookup< float, float, sight_calc, sight_check, update_light, accumulate_transparency, sight_from_lookup > (float(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const float(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], const point & offset, int offsetDistance, float numerator)
Referenced by map::build_seen_cache().
castLightAllWithLookup< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency, sight_from_lookup >()
template void castLightAllWithLookup< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency, sight_from_lookup > (four_quadrants(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const float(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], const point & offset, int offsetDistance, float numerator)
castLightWithLookup()
template<int xx, int xy, int yx, int yy, typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, T(*)(const T &, const T &, const int &) lookup_calc> void castLightWithLookup (Out(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const T(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], const point & offset, int offsetDistance, T numerator = VISIBILITY_FULL, int row = 1, float start = 1.0f, float end = 0.0f, T cumulative_transparency = LIGHT_TRANSPARENCY_OPEN_AIR)
Definition at line 1382 of file lightmap.cpp.
{
    //Find the first tile
    point delta;
    delta.y = -row;
    float away = start - ( -row + 0.5f ) / ( -row - 0.5f );
    delta.x = -row + std::max( static_cast<int>( std::ceil( away * ( -row - 0.5f ) ) ), 0 );
    point first( offset.x + delta.x * xx + delta.y * xy, offset.y + delta.x * yx + delta.y * yy );
    if( cumulative_transparency == LIGHT_TRANSPARENCY_OPEN_AIR && first.x >= 0 && first.y >= 0 &&
        first.x < MAPSIZE_X && first.y < MAPSIZE_Y ) {
        if( input_array[first.x][first.y] == LIGHT_TRANSPARENCY_OPEN_AIR ) {
            castLight<xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate, &openair_transparency_lookup, lookup_calc>
            ( output_cache, input_array, blocked_array, offset, offsetDistance, numerator, row, start, end,
              cumulative_transparency );
            return;
        } else if( input_array[first.x][first.y] == weather_transparency_lookup.transparency ) {
            castLight<xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate, &weather_transparency_lookup, lookup_calc>
            ( output_cache, input_array, blocked_array, offset, offsetDistance, numerator, row, start, end,
              weather_transparency_lookup.transparency );
            return;
        }
    }
    castLight <xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate, nullptr, nullptr>
    ( output_cache, input_array, blocked_array, offset, offsetDistance, numerator, row, start, end,
      cumulative_transparency );
    return;
}
References LIGHT_TRANSPARENCY_OPEN_AIR, MAPSIZE_X, MAPSIZE_Y, weather_transparency_lookup, point::x, and point::y.
Referenced by map::apply_directional_light(), map::apply_light_source(), and castLightAllWithLookup().
eq_nullptr_gcc_hack()
static bool eq_nullptr_gcc_hack (const void * check) inline static
Definition at line 1186 of file lightmap.cpp.
{
    return check == nullptr;
}
References detail::check().
Referenced by castLight().
fast_rl_dist()
template<int start, int iterations> static int fast_rl_dist (tripoint to) inline static
Definition at line 850 of file lightmap.cpp.
{
    if( !trigdist ) {
        return square_dist( tripoint_zero, to );
    }
    int val = to.x * to.x + to.y * to.y + to.z * to.z;
    if( val < 2 ) {
        return val;
    }
    int a = start;
    for( int i = 0; i < iterations; i++ ) {
        int b = val / a;
        a = ( a + b ) / 2;
    }
    return a;
}
References a, b, square_dist(), trigdist, tripoint_zero, tripoint::x, tripoint::y, and tripoint::z.
fastexp()
static float fastexp (float x) inline static
Definition at line 1715 of file lightmap.cpp.
{
    union {
        float f;
        int i;
    } u, v;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Wimplicit-int-float-conversion"
    u.i = static_cast<long long>( 6051102 * x + 1056478197 );
    v.i = static_cast<long long>( 1056478197 - 6051102 * x );
#pragma GCC diagnostic pop
    return u.f / v.f;
}
Referenced by map::apply_light_ray(), and light_calc().
light_calc()
static float light_calc (const float & numerator, const float & transparency, const int & distance) static
Definition at line 1731 of file lightmap.cpp.
{
    // Light needs inverse square falloff in addition to attenuation.
    return numerator  / ( fastexp( transparency * distance ) * distance );
}
References fastexp().
Referenced by map::apply_directional_light(), and map::apply_light_source().
light_check()
static bool light_check (const float & transparency, const float & intensity) static
Definition at line 1738 of file lightmap.cpp.
{
    return transparency > LIGHT_TRANSPARENCY_SOLID && intensity > LIGHT_AMBIENT_LOW;
}
References LIGHT_AMBIENT_LOW, and LIGHT_TRANSPARENCY_SOLID.
Referenced by map::apply_directional_light(), and map::apply_light_source().
light_from_lookup()
static float light_from_lookup (const float & numerator, const float & transparency, const int & distance) static
Definition at line 1743 of file lightmap.cpp.
{
    return numerator *  transparency  / distance ;
}
Referenced by map::apply_directional_light(), and map::apply_light_source().
lightmap_boundary_max()
static constexpr point lightmap_boundary_max (LIGHTMAP_CACHE_X , LIGHTMAP_CACHE_Y) static constexpr
quadrant_from_x_y()
static constexpr quadrant quadrant_from_x_y (int x, int y) static constexpr
Definition at line 875 of file lightmap.cpp.
{
    return ( x > 0 ) ?
           ( ( y > 0 ) ? quadrant::NW : quadrant::SW ) :
           ( ( y > 0 ) ? quadrant::NE : quadrant::SE );
}
References NE, NW, SE, and SW.
Referenced by map::apply_light_ray(), cast_zlight_segment(), and castLight().
Variable Documentation
effect_haslight
const efftype_id effect_haslight("haslight") ("haslight") static
Referenced by map::apply_character_light().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by map::apply_character_light(), and map::generate_lightmap().
lightmap_boundaries
const half_open_rectangle< point > lightmap_boundaries(lightmap_boundary_min, lightmap_boundary_max) (lightmap_boundary_min , lightmap_boundary_max)
Referenced by map::apparent_light_helper(), map::apply_light_ray(), and map::generate_lightmap().
lightmap_boundary_min
constexpr point lightmap_boundary_min {} static constexpr
Definition at line 51 of file lightmap.cpp.
LIGHTMAP_CACHE_X
constexpr int LIGHTMAP_CACHE_X = MAPSIZE_X static constexpr
Definition at line 48 of file lightmap.cpp.
Referenced by map::apply_light_arc(), map::apply_light_source(), and map::generate_lightmap().
LIGHTMAP_CACHE_Y
constexpr int LIGHTMAP_CACHE_Y = MAPSIZE_Y static constexpr
Definition at line 49 of file lightmap.cpp.
Referenced by map::apply_light_arc(), and map::generate_lightmap().
openair_transparency_lookup
const transparency_exp_lookup< 90 > openair_transparency_lookup(LIGHT_TRANSPARENCY_OPEN_AIR) (LIGHT_TRANSPARENCY_OPEN_AIR)
Referenced by map::build_transparency_cache().
weather_transparency_lookup
transparency_exp_lookup< 90 > weather_transparency_lookup(LIGHT_TRANSPARENCY_OPEN_AIR *1.1) (LIGHT_TRANSPARENCY_OPEN_AIR *1. 1)
Referenced by map::build_transparency_cache(), and castLightWithLookup().