Cataclysm BN: src/line.h File Reference
line.h File Reference
#include <cmath>
#include <functional>
#include <string>
#include <vector>
#include <algorithm>
#include "math_defines.h"
#include "point.h"
#include "cached_options.h"
#include "units_angle.h"
Classes
struct FastDistanceApproximation
Helper type for the return value of dist_fast().
Macros
#define CATA_SRC_LINE_H
Enumerations
enum class direction : unsigned {
ABOVENORTHWEST = make_xyz_unit(tripoint_above + tripoint_north_west) , NORTHWEST = make_xyz_unit(tripoint_north_west) , BELOWNORTHWEST = make_xyz_unit(tripoint_below + tripoint_north_west) , ABOVENORTH = make_xyz_unit(tripoint_above + tripoint_north) ,
NORTH = make_xyz_unit(tripoint_north) , BELOWNORTH = make_xyz_unit(tripoint_below + tripoint_north) , ABOVENORTHEAST = make_xyz_unit(tripoint_above + tripoint_north_east) , NORTHEAST = make_xyz_unit(tripoint_north_east) ,
BELOWNORTHEAST = make_xyz_unit(tripoint_below + tripoint_north_east) , ABOVEWEST = make_xyz_unit(tripoint_above + tripoint_west) , WEST = make_xyz_unit(tripoint_west) , BELOWWEST = make_xyz_unit(tripoint_below + tripoint_west) ,
ABOVECENTER = make_xyz_unit(tripoint_above) , CENTER = make_xyz_unit(tripoint_zero) , BELOWCENTER = make_xyz_unit(tripoint_below) , ABOVEEAST = make_xyz_unit(tripoint_above + tripoint_east) ,
EAST = make_xyz_unit(tripoint_east) , BELOWEAST = make_xyz_unit(tripoint_below + tripoint_east) , ABOVESOUTHWEST = make_xyz_unit(tripoint_above + tripoint_south_west) , SOUTHWEST = make_xyz_unit(tripoint_south_west) ,
BELOWSOUTHWEST = make_xyz_unit(tripoint_below + tripoint_south_west) , ABOVESOUTH = make_xyz_unit(tripoint_above + tripoint_south) , SOUTH = make_xyz_unit(tripoint_south) , BELOWSOUTH = make_xyz_unit(tripoint_below + tripoint_south) ,
ABOVESOUTHEAST = make_xyz_unit(tripoint_above + tripoint_south_east) , SOUTHEAST = make_xyz_unit(tripoint_south_east) , BELOWSOUTHEAST = make_xyz_unit(tripoint_below + tripoint_south_east)
}
Functions
double iso_tangent (double distance, units::angle vertex)
Calculate base of an isosceles triangle.
constexpr unsigned make_xyz_unit (const tripoint &p) noexcept
This compile-time usable function combines the sign of each (x, y, z) component into a single integer to allow simple runtime and compile-time mapping of (x, y, z) tuples to direction enumerators.
unsigned make_xyz (const tripoint &)
template<class T >
constexpr direction operator% (const direction &lhs, const T &rhs)
template<class T >
constexpr T operator+ (const direction &lhs, const T &rhs)
template<class T >
constexpr bool operator== (const direction &lhs, const T &rhs)
template<class T >
constexpr bool operator== (const T &lhs, const direction &rhs)
template<class T >
constexpr bool operator!= (const T &lhs, const direction &rhs)
template<class T >
constexpr bool operator!= (const direction &lhs, const T &rhs)
direction direction_from (const point &p) noexcept
direction direction_from (const tripoint &p) noexcept
direction direction_from (const point &p1, const point &p2) noexcept
direction direction_from (const tripoint &p, const tripoint &q)
point direction_XY (direction dir)
std::string direction_name (direction dir)
std::string direction_name_short (direction dir)
std::string direction_suffix (const tripoint &p, const tripoint &q)
void bresenham (const point &p1, const point &p2, int t, const std::function< bool(const point &)> &interact)
The actual Bresenham algorithm in 2D and 3D, everything else should call these and pass in an interact functor to iterate across a line between two points.
void bresenham (const tripoint &loc1, const tripoint &loc2, int t, int t2, const std::function< bool(const tripoint &)> &interact)
tripoint move_along_line (const tripoint &loc, const std::vector< tripoint > &line, int distance)
std::vector< point > line_to (const point &p1, const point &p2, int t=0)
std::vector< tripoint > line_to (const tripoint &loc1, const tripoint &loc2, int t=0, int t2=0)
int trig_dist_squared (const tripoint &loc1, const tripoint &loc2)
float trig_dist (const tripoint &loc1, const tripoint &loc2)
float trig_dist (const point &loc1, const point &loc2)
int square_dist (const tripoint &loc1, const tripoint &loc2)
int square_dist (const point &loc1, const point &loc2)
int rl_dist (const tripoint &loc1, const tripoint &loc2)
int rl_dist (const point &a, const point &b)
FastDistanceApproximation trig_dist_fast (const tripoint &loc1, const tripoint &loc2)
FastDistanceApproximation square_dist_fast (const tripoint &loc1, const tripoint &loc2)
FastDistanceApproximation rl_dist_fast (const tripoint &loc1, const tripoint &loc2)
FastDistanceApproximation rl_dist_fast (const point &a, const point &b)
float rl_dist_exact (const tripoint &loc1, const tripoint &loc2)
int manhattan_dist (const point &loc1, const point &loc2)
int octile_dist (const point &loc1, const point &loc2, int multiplier=1)
float octile_dist_exact (const point &loc1, const point &loc2)
units::angle atan2 (const point &)
float get_normalized_angle (const point &start, const point &end)
std::vector< tripoint > continue_line (const std::vector< tripoint > &line, int distance)
std::vector< point > squares_in_direction (const point &p1, const point &p2)
std::vector< tripoint > squares_closer_to (const tripoint &from, const tripoint &to)
void calc_ray_end (units::angle, int range, const tripoint &p, tripoint &out)
units::angle coord_to_angle (const tripoint &a, const tripoint &b)
Calculates the horizontal angle between the lines from (0,0,0) to a and the line from (0,0,0) to b.
Macro Definition Documentation
CATA_SRC_LINE_H
#define CATA_SRC_LINE_H
Definition at line 3 of file line.h.
Enumeration Type Documentation
direction
enum class direction : unsigned strong
Enumerator
ABOVENORTHWEST
NORTHWEST
BELOWNORTHWEST
ABOVENORTH
NORTH
BELOWNORTH
ABOVENORTHEAST
NORTHEAST
BELOWNORTHEAST
ABOVEWEST
WEST
BELOWWEST
ABOVECENTER
CENTER
BELOWCENTER
ABOVEEAST
EAST
BELOWEAST
ABOVESOUTHWEST
SOUTHWEST
BELOWSOUTHWEST
ABOVESOUTH
SOUTH
BELOWSOUTH
ABOVESOUTHEAST
SOUTHEAST
BELOWSOUTHEAST
Definition at line 39 of file line.h.
                     : unsigned {
    ABOVENORTHWEST = make_xyz_unit( tripoint_above + tripoint_north_west ),
    NORTHWEST      = make_xyz_unit( tripoint_north_west ),
    BELOWNORTHWEST = make_xyz_unit( tripoint_below + tripoint_north_west ),
    ABOVENORTH     = make_xyz_unit( tripoint_above + tripoint_north ),
    NORTH          = make_xyz_unit( tripoint_north ),
    BELOWNORTH     = make_xyz_unit( tripoint_below + tripoint_north ),
    ABOVENORTHEAST = make_xyz_unit( tripoint_above + tripoint_north_east ),
    NORTHEAST      = make_xyz_unit( tripoint_north_east ),
    BELOWNORTHEAST = make_xyz_unit( tripoint_below + tripoint_north_east ),
    ABOVEWEST      = make_xyz_unit( tripoint_above + tripoint_west ),
    WEST           = make_xyz_unit( tripoint_west ),
    BELOWWEST      = make_xyz_unit( tripoint_below + tripoint_west ),
    ABOVECENTER    = make_xyz_unit( tripoint_above ),
    CENTER         = make_xyz_unit( tripoint_zero ),
    BELOWCENTER    = make_xyz_unit( tripoint_below ),
    ABOVEEAST      = make_xyz_unit( tripoint_above + tripoint_east ),
    EAST           = make_xyz_unit( tripoint_east ),
    BELOWEAST      = make_xyz_unit( tripoint_below + tripoint_east ),
    ABOVESOUTHWEST = make_xyz_unit( tripoint_above + tripoint_south_west ),
    SOUTHWEST      = make_xyz_unit( tripoint_south_west ),
    BELOWSOUTHWEST = make_xyz_unit( tripoint_below + tripoint_south_west ),
    ABOVESOUTH     = make_xyz_unit( tripoint_above + tripoint_south ),
    SOUTH          = make_xyz_unit( tripoint_south ),
    BELOWSOUTH     = make_xyz_unit( tripoint_below + tripoint_south ),
    ABOVESOUTHEAST = make_xyz_unit( tripoint_above + tripoint_south_east ),
    SOUTHEAST      = make_xyz_unit( tripoint_south_east ),
    BELOWSOUTHEAST = make_xyz_unit( tripoint_below + tripoint_south_east ),
};
Function Documentation
atan2()
units::angle atan2 (const point & p)
Definition at line 321 of file line.cpp.
{
    return units::atan2( p.y, p.x );
}
References units::atan2(), point::x, and point::y.
Referenced by calculate_aim_cap(), veh_interact::complete_vehicle(), ranged::fire_gun(), tileray::init(), and make_xyz().
bresenham() [1/2]
void bresenham (const point & p1, const point & p2, int t, const std::function< bool(const point &)> & interact)
The actual Bresenham algorithm in 2D and 3D, everything else should call these and pass in an interact functor to iterate across a line between two points.
Definition at line 24 of file line.cpp.
{
    // The slope components.
    const point d = p2 - p1;
    // Signs of slope values.
    const point s( ( d.x == 0 ) ? 0 : sgn( d.x ), ( d.y == 0 ) ? 0 : sgn( d.y ) );
    // Absolute values of slopes x2 to avoid rounding errors.
    const point a = d.abs() * 2;
    point cur = p1;
    if( a.x == a.y ) {
        while( cur.x != p2.x ) {
            cur.y += s.y;
            cur.x += s.x;
            if( !interact( cur ) ) {
                break;
            }
        }
    } else if( a.x > a.y ) {
        while( cur.x != p2.x ) {
            if( t > 0 ) {
                cur.y += s.y;
                t -= a.x;
            }
            cur.x += s.x;
            t += a.y;
            if( !interact( cur ) ) {
                break;
            }
        }
    } else {
        while( cur.y != p2.y ) {
            if( t > 0 ) {
                cur.x += s.x;
                t -= a.y;
            }
            cur.y += s.y;
            t += a.x;
            if( !interact( cur ) ) {
                break;
            }
        }
    }
}
References a, point::abs(), sgn(), point::x, and point::y.
Referenced by map::clear_path(), line_to(), map::obstacle_coverage(), and map::sees().
bresenham() [2/2]
void bresenham (const tripoint & loc1, const tripoint & loc2, int t, int t2, const std::function< bool(const tripoint &)> & interact)
Definition at line 71 of file line.cpp.
{
    // The slope components.
    const tripoint d( -loc1 + loc2 );
    // The signs of the slopes.
    const tripoint s( ( d.x == 0 ? 0 : sgn( d.x ) ), ( d.y == 0 ? 0 : sgn( d.y ) ),
                      ( d.z == 0 ? 0 : sgn( d.z ) ) );
    // Absolute values of slope components, x2 to avoid rounding errors.
    const tripoint a( std::abs( d.x ) * 2, std::abs( d.y ) * 2, std::abs( d.z ) * 2 );
    tripoint cur( loc1 );
    if( a.z == 0 ) {
        if( a.x == a.y ) {
            while( cur.x != loc2.x ) {
                cur.y += s.y;
                cur.x += s.x;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( a.x > a.y ) {
            while( cur.x != loc2.x ) {
                if( t > 0 ) {
                    cur.y += s.y;
                    t -= a.x;
                }
                cur.x += s.x;
                t += a.y;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else {
            while( cur.y != loc2.y ) {
                if( t > 0 ) {
                    cur.x += s.x;
                    t -= a.y;
                }
                cur.y += s.y;
                t += a.x;
                if( !interact( cur ) ) {
                    break;
                }
            }
        }
    } else {
        if( a.x == a.y && a.y == a.z ) {
            while( cur.x != loc2.x ) {
                cur.z += s.z;
                cur.y += s.y;
                cur.x += s.x;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( ( a.z > a.x ) && ( a.z > a.y ) ) {
            while( cur.z != loc2.z ) {
                if( t > 0 ) {
                    cur.x += s.x;
                    t -= a.z;
                }
                if( t2 > 0 ) {
                    cur.y += s.y;
                    t2 -= a.z;
                }
                cur.z += s.z;
                t += a.x;
                t2 += a.y;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( ( a.x > a.y ) && ( a.x > a.z ) ) {
            while( cur.x != loc2.x ) {
                if( t > 0 ) {
                    cur.y += s.y;
                    t -= a.x;
                }
                if( t2 > 0 ) {
                    cur.z += s.z;
                    t2 -= a.x;
                }
                cur.x += s.x;
                t += a.y;
                t2 += a.z;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( ( a.y > a.z ) && ( a.y > a.x ) ) {
            while( cur.y != loc2.y ) {
                if( t > 0 ) {
                    cur.z += s.z;
                    t -= a.y;
                }
                if( t2 > 0 ) {
                    cur.x += s.x;
                    t2 -= a.y;
                }
                cur.y += s.y;
                t += a.z;
                t2 += a.x;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( a.x == a.y ) {
            while( cur.x != loc2.x ) {
                if( t > 0 ) {
                    cur.z += s.z;
                    t -= a.x;
                }
                cur.y += s.y;
                cur.x += s.x;
                t += a.z;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( a.x == a.z ) {
            while( cur.x != loc2.x ) {
                if( t > 0 ) {
                    cur.y += s.y;
                    t -= a.x;
                }
                cur.z += s.z;
                cur.x += s.x;
                t += a.y;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( a.y == a.z ) {
            while( cur.y != loc2.y ) {
                if( t > 0 ) {
                    cur.x += s.x;
                    t -= a.z;
                }
                cur.y += s.y;
                cur.z += s.z;
                t += a.x;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else if( a.x > a.y ) {
            while( cur.x != loc2.x ) {
                if( t > 0 ) {
                    cur.y += s.y;
                    t -= a.x;
                }
                if( t2 > 0 ) {
                    cur.z += s.z;
                    t2 -= a.x;
                }
                cur.x += s.x;
                t += a.y;
                t2 += a.z;
                if( !interact( cur ) ) {
                    break;
                }
            }
        } else { //dy > dx >= dz
            while( cur.y != loc2.y ) {
                if( t > 0 ) {
                    cur.x += s.x;
                    t -= a.y;
                }
                if( t2 > 0 ) {
                    cur.z += s.z;
                    t2 -= a.y;
                }
                cur.y += s.y;
                t += a.x;
                t2 += a.z;
                if( !interact( cur ) ) {
                    break;
                }
            }
        }
    }
}
References a, sgn(), tripoint::x, tripoint::y, and tripoint::z.
calc_ray_end()
void calc_ray_end (units::angle angle, int range, const tripoint & p, tripoint & out)
Definition at line 751 of file line.cpp.
{
    // forces input angle to be between 0 and 360, calculated from actual input
    angle = fmod( angle, 360_degrees );
    if( angle < 0_degrees ) {
        angle += 360_degrees;
    }
    out.z = p.z;
    if( trigdist ) {
        out.x = p.x + range * cos( angle );
        out.y = p.y + range * sin( angle );
    } else {
        int mult = 0;
        if( angle >= 135_degrees && angle <= 315_degrees ) {
            mult = -1;
        } else {
            mult = 1;
        }
        if( angle <= 45_degrees || ( 135_degrees <= angle && angle <= 215_degrees ) ||
            315_degrees < angle ) {
            out.x = p.x + range * mult;
            out.y = p.y + range * tan( angle ) * mult;
        } else {
            out.x = p.x + range * 1 / tan( angle ) * mult;
            out.y = p.y + range * mult;
        }
    }
}
References units::cos(), units::fmod(), units::sin(), units::tan(), trigdist, tripoint::x, tripoint::y, and tripoint::z.
Referenced by map::apply_light_arc(), vehicle::part_collision(), and spell_effect::spell_effect_cone().
continue_line()
std::vector< tripoint > continue_line (const std::vector< tripoint > & line, int distance)
Definition at line 408 of file line.cpp.
{
    return line_to( line.back(), move_along_line( line.back(), line, distance ) );
}
References line(), line_to(), and move_along_line().
Referenced by get_bashing_zone(), game::knockback(), and projectile_attack().
coord_to_angle()
units::angle coord_to_angle (const tripoint & a, const tripoint & b)
Calculates the horizontal angle between the lines from (0,0,0) to a and the line from (0,0,0) to b.
Returned value is in degree and in the range 0....360. Example: if a is (0,1) and b is (1,0), the result will 90 degree The function currently ignores the z component.
Definition at line 781 of file line.cpp.
{
    units::angle rad = units::atan2( b.y - a.y, b.x - a.x );
    if( rad < 0_degrees ) {
        rad += 2_pi_radians;
    }
    return rad;
}
References a, units::atan2(), b, and rad.
Referenced by Creature::auto_find_hostile_target(), mattack::flesh_tendril(), mattack::fungus_fortify(), mattack::fungus_sprout(), sfx::get_heard_angle(), mattack::ranged_pull(), target_ui::recalc_aim_turning_penalty(), mattack::shriek_stun(), mattack::smash(), spell_effect::spell_effect_cone(), and npc::wont_hit_friend().
direction_from() [1/4]
direction direction_from (const point & p) noexcept
Definition at line 413 of file line.cpp.
{
    return static_cast<direction>( make_xyz( tripoint( p, 0 ) ) );
}
References make_xyz().
Referenced by direction_from(), and direction_suffix().
direction_from() [2/4]
direction direction_from (const point & p1, const point & p2) noexcept
Definition at line 423 of file line.cpp.
{
    return direction_from( p2 - p1 );
}
References direction_from().
direction_from() [3/4]
direction direction_from (const tripoint & p) noexcept
Definition at line 418 of file line.cpp.
{
    return static_cast<direction>( make_xyz( p ) );
}
References make_xyz().
direction_from() [4/4]
direction direction_from (const tripoint & p, const tripoint & q)
Definition at line 428 of file line.cpp.
{
    return direction_from( q - p );
}
References direction_from().
direction_name()
std::string direction_name (direction dir)
Definition at line 528 of file line.cpp.
{
    return direction_name_impl( dir, false );
}
References anonymous_namespace{line.cpp}::direction_name_impl().
Referenced by vehicle::check_heli_ascend(), iuse::directional_antenna(), basecamp::faction_display(), npc::faction_display(), overmapbuffer::get_description_at(), liquid_handler::get_liquid_target(), vehicle::handle_trap(), iuse::note_bionics(), point_selection_menu(), sounds::process_sound_markers(), iuse::report_grid_connections(), character_funcs::search_surroundings(), and npc::warn_about().
direction_name_short()
std::string direction_name_short (direction dir)
Definition at line 533 of file line.cpp.
{
    return direction_name_impl( dir, true );
}
References anonymous_namespace{line.cpp}::direction_name_impl().
Referenced by direction_suffix(), game::list_items(), game::list_monsters(), overmap_ui::search(), overmap_ui::show_notes_manager(), and game::zones_manager().
direction_suffix()
std::string direction_suffix (const tripoint & p, const tripoint & q)
Definition at line 538 of file line.cpp.
{
    int dist = square_dist( p, q );
    if( dist <= 0 ) {
        return std::string();
    }
    return string_format( "%d%s", dist, trim( direction_name_short( direction_from( p, q ) ) ) );
}
References direction_from(), direction_name_short(), square_dist(), string_format(), and trim().
Referenced by item_location::impl::item_on_map::describe(), item_location::impl::item_on_vehicle::describe(), and inventory_selector::naturalize_category().
direction_XY()
point direction_XY (direction dir)
Definition at line 433 of file line.cpp.
{
    switch( dir % 9 ) {
        case direction::NORTHWEST:
        case direction::ABOVENORTHWEST:
        case direction::BELOWNORTHWEST:
            return point_north_west;
        case direction::NORTH:
        case direction::ABOVENORTH:
        case direction::BELOWNORTH:
            return point_north;
        case direction::NORTHEAST:
        case direction::ABOVENORTHEAST:
        case direction::BELOWNORTHEAST:
            return point_north_east;
        case direction::WEST:
        case direction::ABOVEWEST:
        case direction::BELOWWEST:
            return point_west;
        case direction::CENTER:
        case direction::ABOVECENTER:
        case direction::BELOWCENTER:
            return point_zero;
        case direction::EAST:
        case direction::ABOVEEAST:
        case direction::BELOWEAST:
            return point_east;
        case direction::SOUTHWEST:
        case direction::ABOVESOUTHWEST:
        case direction::BELOWSOUTHWEST:
            return point_south_west;
        case direction::SOUTH:
        case direction::ABOVESOUTH:
        case direction::BELOWSOUTH:
            return point_south;
        case direction::SOUTHEAST:
        case direction::ABOVESOUTHEAST:
        case direction::BELOWSOUTHEAST:
            return point_south_east;
    }
    return point_zero;
}
References ABOVECENTER, ABOVEEAST, ABOVENORTH, ABOVENORTHEAST, ABOVENORTHWEST, ABOVESOUTH, ABOVESOUTHEAST, ABOVESOUTHWEST, ABOVEWEST, BELOWCENTER, BELOWEAST, BELOWNORTH, BELOWNORTHEAST, BELOWNORTHWEST, BELOWSOUTH, BELOWSOUTHEAST, BELOWSOUTHWEST, BELOWWEST, CENTER, EAST, NORTH, NORTHEAST, NORTHWEST, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, point_zero, SOUTH, SOUTHEAST, SOUTHWEST, and WEST.
Referenced by scrollingcombattext::cSCT::cSCT(), npc::good_escape_direction(), pickup::pick_up(), and game::place_player().
get_normalized_angle()
float get_normalized_angle (const point & start, const point & end)
Definition at line 382 of file line.cpp.
{
    // Taking the abs value of the difference puts the values in the first quadrant.
    const float absx = std::abs( std::max( start.x, end.x ) - std::min( start.x, end.x ) );
    const float absy = std::abs( std::max( start.y, end.y ) - std::min( start.y, end.y ) );
    const float max = std::max( absx, absy );
    if( max == 0 ) {
        return 0;
    }
    const float min = std::min( absx, absy );
    return min / max;
}
References point::x, and point::y.
iso_tangent()
double iso_tangent (double distance, units::angle vertex)
Calculate base of an isosceles triangle.
Parameters
distance one of the equal lengths
vertex the unequal angle
Returns
base in equivalent units to distance
Definition at line 18 of file line.cpp.
{
    // we can use the cosine formula (a = b + c - 2bccos) to calculate the tangent
    return std::sqrt( 2 * std::pow( distance, 2 ) * ( 1 - cos( vertex ) ) );
}
References units::cos().
Referenced by confidence_estimate(), and projectile_attack_roll().
line_to() [1/2]
std::vector< point > line_to (const point & p1, const point & p2, int t = 0)
Definition at line 258 of file line.cpp.
{
    std::vector<point> line;
    // Preallocate the number of cells we need instead of allocating them piecewise.
    const int numCells = square_dist( p1, p2 );
    if( numCells == 0 ) {
        line.push_back( p1 );
    } else {
        line.reserve( numCells );
        bresenham( p1, p2, t, [&line]( const point & new_point ) {
            line.push_back( new_point );
            return true;
        } );
    }
    return line;
}
References bresenham(), line(), and square_dist().
Referenced by continue_line(), and squares_in_direction().
line_to() [2/2]
std::vector< tripoint > line_to (const tripoint & loc1, const tripoint & loc2, int t = 0, int t2 = 0)
Definition at line 275 of file line.cpp.
{
    std::vector<tripoint> line;
    // Preallocate the number of cells we need instead of allocating them piecewise.
    const int numCells = square_dist( loc1, loc2 );
    if( numCells == 0 ) {
        line.push_back( loc1 );
    } else {
        line.reserve( numCells );
        bresenham( loc1, loc2, t, t2, [&line]( const tripoint & new_point ) {
            line.push_back( new_point );
            return true;
        } );
    }
    return line;
}
References bresenham(), line(), and square_dist().
make_xyz()
unsigned make_xyz (const tripoint & p)
Definition at line 327 of file line.cpp.
{
    static constexpr double sixteenth_arc = M_PI / 8;
    int vertical_position = ( ( p.z > 0 ) ? 2u : ( p.z < 0 ) ? 1u : 0u ) * 9u;
    if( p.xy() == point_zero ) {
        return vertical_position;
    }
    // Get the arctan of the angle and divide by approximately 22.5 deg to get the octant.
    // the angle is in, then truncate it and map to the right direction.
    // You can read 'octant' as being "number of 22.5 degree sections away from due south".
    // FIXME: atan2 normally takes arguments in ( y, x ) order.  This is
    // passing ( x, y ).
    int octant = atan2( p.x, p.y ) / sixteenth_arc;
    switch( octant ) {
        case 0:
            return direction::SOUTH + vertical_position;
        case 1:
        case 2:
            return direction::SOUTHEAST + vertical_position;
        case 3:
        case 4:
            return direction::EAST + vertical_position;
        case 5:
        case 6:
            return direction::NORTHEAST + vertical_position;
        case -1:
        case -2:
            return direction::SOUTHWEST + vertical_position;
        case -3:
        case -4:
            return direction::WEST + vertical_position;
        case -5:
        case -6:
            return direction::NORTHWEST + vertical_position;
        case 7:
        case 8:
        case -7:
        case -8:
        default:
            return direction::NORTH + vertical_position;
    }
}
References atan2(), EAST, M_PI, NORTH, NORTHEAST, NORTHWEST, point_zero, SOUTH, SOUTHEAST, SOUTHWEST, WEST, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by direction_from().
make_xyz_unit()
constexpr unsigned make_xyz_unit (const tripoint & p) inline constexpr noexcept
This compile-time usable function combines the sign of each (x, y, z) component into a single integer to allow simple runtime and compile-time mapping of (x, y, z) tuples to direction enumerators.
Specifically, (0, -, +) => (0, 1, 2); a base-3 number. This only works correctly for inputs between -1,-1,-1 and 1,1,1. For numbers outside that range, use make_xyz().
Definition at line 29 of file line.h.
{
    return ( ( p.x > 0 ) ? 2u : ( p.x < 0 ) ? 1u : 0u ) * 1u +
           ( ( p.y > 0 ) ? 2u : ( p.y < 0 ) ? 1u : 0u ) * 3u +
           ( ( p.z > 0 ) ? 2u : ( p.z < 0 ) ? 1u : 0u ) * 9u;
}
manhattan_dist()
int manhattan_dist (const point & loc1, const point & loc2)
Definition at line 300 of file line.cpp.
{
    const point d = ( loc1 - loc2 ).abs();
    return d.x + d.y;
}
References point::x, and point::y.
move_along_line()
tripoint move_along_line (const tripoint & loc, const std::vector< tripoint > & line, int distance)
Definition at line 395 of file line.cpp.
{
    // May want to optimize this, but it's called fairly infrequently as part of specific attack
    // routines, erring on the side of readability.
    tripoint res( loc );
    const auto slope = slope_of( line );
    res.x += distance * std::get<0>( slope );
    res.y += distance * std::get<1>( slope );
    res.z += distance * std::get<2>( slope );
    return res;
}
References line(), slope_of(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by continue_line(), and projectile_attack().
octile_dist()
int octile_dist (const point & loc1, const point & loc2, int multiplier = 1)
Definition at line 306 of file line.cpp.
{
    const point d = ( loc1 - loc2 ).abs();
    const int mind = std::min( d.x, d.y );
    // sqrt(2) is approximately 99 / 70
    return ( d.x + d.y - 2 * mind ) * multiplier + mind * multiplier * 99 / 70;
}
References point::x, and point::y.
octile_dist_exact()
float octile_dist_exact (const point & loc1, const point & loc2)
Definition at line 314 of file line.cpp.
{
    const point d = ( loc1 - loc2 ).abs();
    const int mind = std::min( d.x, d.y );
    return d.x + d.y - 2 * mind + mind * M_SQRT2;
}
References M_SQRT2, point::x, and point::y.
operator!=() [1/2]
template<class T > constexpr bool operator!= (const direction & lhs, const T & rhs) inline constexpr
Definition at line 102 of file line.h.
{
    return !operator==( lhs, rhs );
}
References operator==().
operator!=() [2/2]
template<class T > constexpr bool operator!= (const T & lhs, const direction & rhs) inline constexpr
Definition at line 96 of file line.h.
{
    return !operator==( rhs, lhs );
}
References operator==().
operator%()
template<class T > constexpr direction operator% (const direction & lhs, const T & rhs) inline constexpr
Definition at line 72 of file line.h.
{
    return static_cast<direction>( static_cast<T>( lhs ) % rhs );
}
operator+()
template<class T > constexpr T operator+ (const direction & lhs, const T & rhs) inline constexpr
Definition at line 78 of file line.h.
{
    return static_cast<T>( lhs ) + rhs;
}
operator==() [1/2]
template<class T > constexpr bool operator== (const direction & lhs, const T & rhs) inline constexpr
Definition at line 84 of file line.h.
{
    return static_cast<T>( lhs ) == rhs;
}
Referenced by operator!=(), and operator==().
operator==() [2/2]
template<class T > constexpr bool operator== (const T & lhs, const direction & rhs) inline constexpr
Definition at line 90 of file line.h.
{
    return operator==( rhs, lhs );
}
References operator==().
rl_dist() [1/2]
int rl_dist (const point & a, const point & b) inline
Definition at line 171 of file line.h.
{
    return rl_dist( tripoint( a, 0 ), tripoint( b, 0 ) );
}
References a, b, and rl_dist().
rl_dist() [2/2]
int rl_dist (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 164 of file line.h.
{
    if( trigdist ) {
        return trig_dist( loc1, loc2 );
    }
    return square_dist( loc1, loc2 );
}
References square_dist(), trig_dist(), and trigdist.
Referenced by rl_dist().
rl_dist_exact()
float rl_dist_exact (const tripoint & loc1, const tripoint & loc2)
Definition at line 292 of file line.cpp.
{
    if( trigdist ) {
        return trig_dist( loc1, loc2 );
    }
    return square_dist( loc1, loc2 );
}
References square_dist(), trig_dist(), and trigdist.
Referenced by target_ui::dist_fn(), Character::get_hostile_creatures(), and ranged::targetable_creatures().
rl_dist_fast() [1/2]
FastDistanceApproximation rl_dist_fast (const point & a, const point & b) inline
Definition at line 226 of file line.h.
{
    return rl_dist_fast( tripoint( a, 0 ), tripoint( b, 0 ) );
}
References a, b, and rl_dist_fast().
rl_dist_fast() [2/2]
FastDistanceApproximation rl_dist_fast (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 219 of file line.h.
{
    if( trigdist ) {
        return trig_dist_fast( loc1, loc2 );
    }
    return square_dist_fast( loc1, loc2 );
}
References square_dist_fast(), trig_dist_fast(), and trigdist.
Referenced by monster::rate_target(), and rl_dist_fast().
square_dist() [1/2]
int square_dist (const point & loc1, const point & loc2) inline
Definition at line 157 of file line.h.
{
    const point d = ( loc1 - loc2 ).abs();
    return std::max( d.x, d.y );
}
References point::x, and point::y.
square_dist() [2/2]
int square_dist (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 152 of file line.h.
{
    const tripoint d = ( loc1 - loc2 ).abs();
    return std::max( { d.x, d.y, d.z } );
}
References tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist().
square_dist_fast()
FastDistanceApproximation square_dist_fast (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 214 of file line.h.
{
    const tripoint d = ( loc1 - loc2 ).abs();
    return std::max( { d.x, d.y, d.z } );
}
References tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist_fast().
squares_closer_to()
std::vector< tripoint > squares_closer_to (const tripoint & from, const tripoint & to)
Definition at line 552 of file line.cpp.
{
    std::vector<tripoint> adjacent_closer_squares;
    const tripoint d( -from + to );
    const point a( std::abs( d.x ), std::abs( d.y ) );
    if( d.z != 0 ) {
        adjacent_closer_squares.push_back( from + tripoint( sgn( d.x ), sgn( d.y ), sgn( d.z ) ) );
    }
    if( a.x > a.y ) {
        // X dominant.
        adjacent_closer_squares.push_back( from + point( sgn( d.x ), 0 ) );
        adjacent_closer_squares.push_back( from + point( sgn( d.x ), 1 ) );
        adjacent_closer_squares.push_back( from + point( sgn( d.x ), -1 ) );
        if( d.y != 0 ) {
            adjacent_closer_squares.push_back( from + point( 0, sgn( d.y ) ) );
        }
    } else if( a.x < a.y ) {
        // Y dominant.
        adjacent_closer_squares.push_back( from + point( 0, sgn( d.y ) ) );
        adjacent_closer_squares.push_back( from + point( 1, sgn( d.y ) ) );
        adjacent_closer_squares.push_back( from + point( -1, sgn( d.y ) ) );
        if( d.x != 0 ) {
            adjacent_closer_squares.push_back( from + point( sgn( d.x ), 0 ) );
        }
    } else if( d.x != 0 ) {
        // Pure diagonal.
        adjacent_closer_squares.push_back( from + point( sgn( d.x ), sgn( d.y ) ) );
        adjacent_closer_squares.push_back( from + point( sgn( d.x ), 0 ) );
        adjacent_closer_squares.push_back( from + point( 0, sgn( d.y ) ) );
    }
    return adjacent_closer_squares;
}
References a, sgn(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by monster::move().
squares_in_direction()
std::vector< point > squares_in_direction (const point & p1, const point & p2)
Definition at line 588 of file line.cpp.
{
    int junk = 0;
    point center_square = line_to( p1, p2, junk )[0];
    std::vector<point> adjacent_squares;
    adjacent_squares.push_back( center_square );
    if( p1.x == center_square.x ) {
        // Horizontally adjacent.
        adjacent_squares.push_back( point( p1.x + 1, center_square.y ) );
        adjacent_squares.push_back( point( p1.x - 1, center_square.y ) );
    } else if( p1.y == center_square.y ) {
        // Vertically adjacent.
        adjacent_squares.push_back( point( center_square.x, p1.y + 1 ) );
        adjacent_squares.push_back( point( center_square.x, p1.y - 1 ) );
    } else {
        // Diagonally adjacent.
        adjacent_squares.push_back( point( p1.x, center_square.y ) );
        adjacent_squares.push_back( point( center_square.x, p1.y ) );
    }
    return adjacent_squares;
}
References line_to(), point::x, and point::y.
Referenced by get_bashing_zone(), MapExtras::mx_minefield(), and map::process_fields_in_submap().
trig_dist() [1/2]
float trig_dist (const point & loc1, const point & loc2) inline
Definition at line 146 of file line.h.
{
    return trig_dist( tripoint( loc1, 0 ), tripoint( loc2, 0 ) );
}
References trig_dist().
trig_dist() [2/2]
float trig_dist (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 142 of file line.h.
{
    return std::sqrt( static_cast<double>( trig_dist_squared( loc1, loc2 ) ) );
}
References trig_dist_squared().
Referenced by rl_dist(), and trig_dist().
trig_dist_fast()
FastDistanceApproximation trig_dist_fast (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 208 of file line.h.
{
    return ( loc1.x - loc2.x ) * ( loc1.x - loc2.x ) +
           ( loc1.y - loc2.y ) * ( loc1.y - loc2.y ) +
           ( loc1.z - loc2.z ) * ( loc1.z - loc2.z );
}
References tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist_fast().
trig_dist_squared()
int trig_dist_squared (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 136 of file line.h.
{
    return ( ( loc1.x - loc2.x ) * ( loc1.x - loc2.x ) ) +
           ( ( loc1.y - loc2.y ) * ( loc1.y - loc2.y ) ) +
           ( ( loc1.z - loc2.z ) * ( loc1.z - loc2.z ) );
}
References tripoint::x, tripoint::y, and tripoint::z.
Referenced by bucket_by_distance(), ranged::execute_shaped_attack(), ranged::expected_coverage(), and trig_dist().