Cataclysm BN: src/magic_ter_fur_transform.cpp File Reference
magic_ter_fur_transform.cpp File Reference
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "creature.h"
#include "enums.h"
#include "generic_factory.h"
#include "json.h"
#include "magic_ter_furn_transform.h"
#include "map.h"
#include "mapdata.h"
#include "optional.h"
#include "string_id.h"
#include "type_id.h"
Namespaces
namespace anonymous_namespace{magic_ter_fur_transform.cpp}
Functions
template<class T >
static void load_transform_results (const JsonObject &jsi, const std::string &json_key, weighted_int_list< T > &list)
Variables
generic_factory< ter_furn_transform > anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory ("ter_furn_transform")
Function Documentation
load_transform_results()
template<class T > static void load_transform_results (const JsonObject & jsi, const std::string & json_key, weighted_int_list< T > & list) static
Definition at line 60 of file magic_ter_fur_transform.cpp.
{
    if( jsi.has_string( json_key ) ) {
        list.add( T( jsi.get_string( json_key ) ), 1 );
        return;
    }
    for( const JsonValue entry : jsi.get_array( json_key ) ) {
        if( entry.test_array() ) {
            JsonArray inner = entry.get_array();
            list.add( T( inner.get_string( 0 ) ), inner.get_int( 1 ) );
        } else {
            list.add( T( entry.get_string() ), 1 );
        }
    }
}
References weighted_list< W, T >::add(), JsonObject::get_array(), JsonArray::get_array(), JsonArray::get_int(), JsonObject::get_string(), JsonArray::get_string(), JsonObject::has_string(), and mapgen_defer::jsi.
Referenced by ter_furn_data< T >::load().