Cataclysm BN: src/magic_spell_effect.cpp File Reference
magic_spell_effect.cpp File Reference
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <iterator>
#include <map>
#include <memory>
#include <queue>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "animation.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "character.h"
#include "color.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "game.h"
#include "item.h"
#include "line.h"
#include "magic.h"
#include "magic_spell_effect_helpers.h"
#include "magic_teleporter_list.h"
#include "magic_ter_furn_transform.h"
#include "map.h"
#include "map_iterator.h"
#include "messages.h"
#include "monster.h"
#include "optional.h"
#include "overmapbuffer.h"
#include "player.h"
#include "point.h"
#include "projectile.h"
#include "ret_val.h"
#include "rng.h"
#include "string_id.h"
#include "teleport.h"
#include "timed_event.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
struct spell_detail::line_iterable
Namespaces
namespace spell_detail
Functions
static int spell_detail::side_of (const point &a, const point &b, const point &c)
static bool spell_detail::between_or_on (const point &a0, const point &a1, const point &d, const point &c)
static void spell_detail::build_line (spell_detail::line_iterable line, const tripoint &source, const point &delta, const point &delta_perp, bool(*test)(const tripoint &, const tripoint &), std::set< tripoint > &result)
static void swap_pos (Creature &caster, const tripoint &target)
static bool in_spell_aoe (const tripoint &start, const tripoint &end, const int &radius, const bool ignore_walls)
static bool test_always_true (const tripoint &, const tripoint &)
static bool test_passable (const tripoint &p, const tripoint &prev)
std::set< tripoint > calculate_spell_effect_area (const spell &sp, const tripoint &target, std::function< std::set< tripoint >(const spell &, const tripoint &, const tripoint &, int, bool)> aoe_func, const Creature &caster, bool ignore_walls)
static std::set< tripoint > spell_effect_area (const spell &sp, const tripoint &target, std::function< std::set< tripoint >(const spell &, const tripoint &, const tripoint &, int, bool)> aoe_func, const Creature &caster, bool ignore_walls=false)
static void add_effect_to_target (const tripoint &target, const spell &sp)
static void damage_targets (const spell &sp, Creature &caster, const std::set< tripoint > &targets)
static void spell_move (const spell &sp, const Creature &caster, const tripoint &from, const tripoint &to)
static bool is_summon_friendly (const spell &sp)
static bool add_summoned_mon (const mtype_id &id, const tripoint &pos, const time_duration &time, const spell &sp)
Variables
static const ammo_effect_str_id ammo_effect_magic ("magic")
Function Documentation
add_effect_to_target()
static void add_effect_to_target (const tripoint & target, const spell & sp) static
Definition at line 425 of file magic_spell_effect.cpp.
{
    Creature *const critter = g->critter_at<Creature>( target );
    Character *const guy = g->critter_at<Character>( target );
    efftype_id spell_effect( sp.effect_data() );
    // TODO: migrate duration from moves to time_duration
    const int dur_turns = sp.duration() / 100;
    // Ensure permanent effect has at last 1 second of duration,
    // so it won't be instantly removed as expired.
    time_duration dur_td = ( spell_effect->is_permanent() && dur_turns == 0 )
                           ? 1_seconds
                           : 1_turns * dur_turns;
    bool bodypart_effected = false;
    if( guy ) {
        for( const body_part bp : all_body_parts ) {
            if( sp.bp_is_affected( bp ) ) {
                guy->add_effect( spell_effect, dur_td, bp );
                bodypart_effected = true;
            }
        }
    }
    if( !bodypart_effected ) {
        critter->add_effect( spell_effect, dur_td, num_bp );
    }
}
References Creature::add_effect(), all_body_parts, spell::bp_is_affected(), spell::duration(), spell::effect_data(), g, and num_bp.
Referenced by damage_targets().
add_summoned_mon()
static bool add_summoned_mon (const mtype_id & id, const tripoint & pos, const time_duration & time, const spell & sp) static
Definition at line 824 of file magic_spell_effect.cpp.
{
    monster *const mon_ptr = g->place_critter_at( id, pos );
    if( !mon_ptr ) {
        return false;
    }
    const bool permanent = sp.has_flag( spell_flag::PERMANENT );
    monster &spawned_mon = *mon_ptr;
    if( is_summon_friendly( sp ) ) {
        spawned_mon.friendly = INT_MAX;
    } else {
        spawned_mon.friendly = 0;
    }
    if( !permanent ) {
        spawned_mon.set_summon_time( time );
    }
    spawned_mon.no_extra_death_drops = true;
    return true;
}
References monster::friendly, g, spell::has_flag(), is_summon_friendly(), monster::no_extra_death_drops, PERMANENT, and monster::set_summon_time().
Referenced by spell_effect::spawn_summoned_monster().
calculate_spell_effect_area()
std::set< tripoint > calculate_spell_effect_area (const spell & sp, const tripoint & target, std::function< std::set< tripoint >(const spell &, const tripoint &, const tripoint &, int, bool)> aoe_func, const Creature & caster, bool ignore_walls)
Definition at line 379 of file magic_spell_effect.cpp.
{
    std::set<tripoint> targets = { target }; // initialize with epicenter
    if( sp.aoe() <= 1 && sp.effect() != "line_attack" ) {
        return targets;
    }
    const int aoe_radius = sp.aoe();
    targets = aoe_func( sp, caster.pos(), target, aoe_radius, ignore_walls );
    for( std::set<tripoint>::iterator it = targets.begin(); it != targets.end(); ) {
        if( !sp.is_valid_target( caster, *it ) ) {
            it = targets.erase( it );
        } else {
            ++it;
        }
    }
    return targets;
}
References spell::aoe(), spell::effect(), spell::is_valid_target(), and Creature::pos().
Referenced by spell_effect_area().
damage_targets()
static void damage_targets (const spell & sp, Creature & caster, const std::set< tripoint > & targets) static
Definition at line 454 of file magic_spell_effect.cpp.
{
    for( const tripoint &target : targets ) {
        if( !sp.is_valid_target( caster, target ) ) {
            continue;
        }
        sp.make_sound( target );
        sp.create_field( target );
        Creature *const cr = g->critter_at<Creature>( target );
        if( !cr ) {
            continue;
        }
        projectile bolt;
        bolt.speed = 10000;
        bolt.impact = sp.get_damage_instance();
        bolt.add_effect( ammo_effect_magic );
        dealt_projectile_attack atk;
        atk.end_point = target;
        atk.hit_critter = cr;
        atk.proj = bolt;
        atk.missed_by = 0.0;
        if( !sp.effect_data().empty() ) {
            add_effect_to_target( target, sp );
        }
        if( sp.damage() > 0 ) {
            cr->deal_projectile_attack( &caster, atk );
        } else if( sp.damage() < 0 ) {
            sp.heal( target );
            if( g->u.sees( cr->pos() ) ) {
                add_msg( m_good, _( "%s wounds are closing up!" ), cr->disp_name( true ) );
            }
        }
    }
}
References _, projectile::add_effect(), add_effect_to_target(), add_msg(), ammo_effect_magic, spell::create_field(), spell::damage(), Creature::deal_projectile_attack(), Creature::disp_name(), spell::effect_data(), dealt_projectile_attack::end_point, g, spell::get_damage_instance(), spell::heal(), dealt_projectile_attack::hit_critter, projectile::impact, spell::is_valid_target(), m_good, spell::make_sound(), dealt_projectile_attack::missed_by, Creature::pos(), dealt_projectile_attack::proj, and projectile::speed.
Referenced by spell_effect::cone_attack(), spell_effect::line_attack(), and spell_effect::target_attack().
in_spell_aoe()
static bool in_spell_aoe (const tripoint & start, const tripoint & end, const int & radius, const bool ignore_walls) static
Definition at line 158 of file magic_spell_effect.cpp.
{
    if( rl_dist( start, end ) > radius ) {
        return false;
    }
    if( ignore_walls ) {
        return true;
    }
    const std::vector<tripoint> trajectory = line_to( start, end );
    tripoint last_point = start;
    for( const tripoint &pt : trajectory ) {
        if( ( g->m.impassable( pt ) && !g->m.has_flag( "THIN_OBSTACLE", pt ) ) ||
            g->m.obstructed_by_vehicle_rotation( pt, last_point ) ) {
            return false;
        }
        last_point = pt;
    }
    return true;
}
References g, line_to(), and rl_dist().
Referenced by spell_effect::spell_effect_blast().
is_summon_friendly()
static bool is_summon_friendly (const spell & sp) static
Definition at line 814 of file magic_spell_effect.cpp.
{
    const bool hostile = sp.has_flag( spell_flag::HOSTILE_SUMMON );
    bool friendly = !hostile;
    if( sp.has_flag( spell_flag::HOSTILE_50 ) ) {
        friendly = friendly && rng( 0, 1000 ) < 500;
    }
    return friendly;
}
References friendly, spell::has_flag(), hostile, HOSTILE_50, HOSTILE_SUMMON, and rng().
Referenced by add_summoned_mon().
spell_effect_area()
static std::set< tripoint > spell_effect_area (const spell & sp, const tripoint & target, std::function< std::set< tripoint >(const spell &, const tripoint &, const tripoint &, int, bool)> aoe_func, const Creature & caster, bool ignore_walls = false) static
Definition at line 402 of file magic_spell_effect.cpp.
{
    // calculate spell's effect area
    std::set<tripoint> targets = calculate_spell_effect_area( sp, target, aoe_func, caster,
                                 ignore_walls );
    // Draw the explosion
    std::map<tripoint, nc_color> explosion_colors;
    for( auto &pt : targets ) {
        explosion_colors[pt] = sp.damage_type_color();
    }
    if( sp.id()->sprite.length() > 0 ) {
        explosion_handler::draw_custom_explosion( g->u.pos(), explosion_colors, sp.id()->sprite );
    } else {
        explosion_handler::draw_custom_explosion( g->u.pos(), explosion_colors, "explosion" );
    }
    return targets;
}
References calculate_spell_effect_area(), spell::damage_type_color(), explosion_handler::draw_custom_explosion(), g, spell::id(), and spell_type::sprite.
Referenced by spell_effect::cone_attack(), spell_effect::line_attack(), spell_effect::spawn_summoned_monster(), spell_effect::target_attack(), and spell_effect::translocate().
spell_move()
static void spell_move (const spell & sp, const Creature & caster, const tripoint & from, const tripoint & to) static
Definition at line 633 of file magic_spell_effect.cpp.
{
    if( from == to ) {
        return;
    }
    // Moving creatures
    bool can_target_creature = sp.is_valid_effect_target( target_self ) ||
                               sp.is_valid_effect_target( target_ally ) ||
                               sp.is_valid_effect_target( target_hostile );
    if( can_target_creature ) {
        if( Creature *victim = g->critter_at<Creature>( from ) ) {
            Creature::Attitude cr_att = victim->attitude_to( g->u );
            bool valid = cr_att != Creature::A_FRIENDLY && sp.is_valid_effect_target( target_hostile );
            valid |= cr_att == Creature::A_FRIENDLY && sp.is_valid_effect_target( target_ally );
            valid |= victim == &caster && sp.is_valid_effect_target( target_self );
            if( valid ) {
                victim->knock_back_to( to );
            }
        }
    }
    // Moving items
    if( sp.is_valid_effect_target( target_item ) ) {
        auto src_items = g->m.i_at( from );
        auto dst_items = g->m.i_at( to );
        for( const item &item : src_items ) {
            dst_items.insert( item );
        }
        src_items.clear();
    }
    // Helper function to move particular field type if corresponding target flag is enabled.
    auto move_field = [&sp, from, to]( valid_target target, field_type_id fid ) {
        if( !sp.is_valid_effect_target( target ) ) {
            return;
        }
        auto &src_field = g->m.field_at( from );
        if( field_entry *entry = src_field.find_field( fid ) ) {
            int intensity = entry->get_field_intensity();
            g->m.remove_field( from, fid );
            g->m.set_field_intensity( to, fid, intensity );
        }
    };
    // Moving fields.
    move_field( target_fd_fire, fd_fire );
    move_field( target_fd_blood, fd_blood );
    move_field( target_fd_blood, fd_gibs_flesh );
}
References Creature::A_FRIENDLY, fd_blood, fd_fire, fd_gibs_flesh, g, spell::is_valid_effect_target(), target_ally, target_fd_blood, target_fd_fire, target_hostile, target_item, and target_self.
Referenced by spell_effect::area_pull(), and spell_effect::area_push().
swap_pos()
static void swap_pos (Creature & caster, const tripoint & target) static
Definition at line 127 of file magic_spell_effect.cpp.
{
    Creature *const critter = g->critter_at<Creature>( target );
    critter->setpos( caster.pos() );
    caster.setpos( target );
    //update map in case a monster swapped positions with the player
    g->update_map( g->u );
}
References g, Creature::pos(), and Creature::setpos().
Referenced by monexamine::mfriend_menu(), game::npc_menu(), monexamine::pet_menu(), and spell_effect::target_attack().
test_always_true()
static bool test_always_true (const tripoint & , const tripoint &) static
Definition at line 226 of file magic_spell_effect.cpp.
{
    return true;
}
Referenced by spell_effect::spell_effect_line().
test_passable()
static bool test_passable (const tripoint & p, const tripoint & prev) static
Definition at line 230 of file magic_spell_effect.cpp.
{
    return ( !g->m.obstructed_by_vehicle_rotation( prev, p ) && ( g->m.passable( p ) ||
             g->m.has_flag( "THIN_OBSTACLE", p ) ) );
}
References g.
Referenced by spell_effect::spell_effect_line().
Variable Documentation
ammo_effect_magic
const ammo_effect_str_id ammo_effect_magic("magic") ("magic") static
Referenced by damage_targets().