Cataclysm BN: src/magic_teleporter_list.cpp File Reference
magic_teleporter_list.cpp File Reference
#include "magic_teleporter_list.h"
#include <cstddef>
#include <algorithm>
#include <map>
#include <memory>
#include <utility>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "cursesdef.h"
#include "enums.h"
#include "game.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "messages.h"
#include "output.h"
#include "panels.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
Classes
class teleporter_callback
Functions
static bool popup_string (std::string &result, std::string &title)
static cata::optional< tripoint > find_valid_teleporters_omt (const tripoint_abs_omt &omt_pt)
Function Documentation
find_valid_teleporters_omt()
static cata::optional< tripoint > find_valid_teleporters_omt (const tripoint_abs_omt & omt_pt) static
Definition at line 61 of file magic_teleporter_list.cpp.
{
    // this is the top left hand square of the global absolute coordinate
    // of the overmap terrain we want to try to teleport to.
    // an OMT is SEEX * SEEY in size
    const tripoint_abs_sm sm_pt = project_to<coords::sm>( omt_pt );
    tinymap checker;
    // TODO: fix point types
    checker.load( sm_pt.raw(), true );
    for( const tripoint &p : checker.points_on_zlevel() ) {
        if( checker.has_flag_furn( "TRANSLOCATOR", p ) ) {
            return checker.getabs( p );
        }
    }
    return cata::nullopt;
}
References map::getabs(), map::has_flag_furn(), map::load(), cata::nullopt, map::points_on_zlevel(), and coords::coord_point< Point, Origin, Scale >::raw().
Referenced by teleporter_list::place_avatar_overmap().
popup_string()
static bool popup_string (std::string & result, std::string & title) static
Definition at line 33 of file magic_teleporter_list.cpp.
{
    string_input_popup popup;
    popup.title( title );
    popup.text( "" ).only_digits( false );
    popup.query();
    if( popup.canceled() ) {
        return false;
    }
    result = popup.text();
    return true;
}
References popup(), and PATH_INFO::title().
Referenced by teleporter_list::activate_teleporter().