Cataclysm BN: src/main_menu.cpp File Reference
main_menu.cpp File Reference
#include "main_menu.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <exception>
#include <functional>
#include <istream>
#include <memory>
#include <ctime>
#include "auto_pickup.h"
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_id.h"
#include "color.h"
#include "debug.h"
#include "distraction_manager.h"
#include "enums.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "game.h"
#include "gamemode.h"
#include "get_version.h"
#include "help.h"
#include "loading_ui.h"
#include "mapbuffer.h"
#include "mapsharing.h"
#include "messages.h"
#include "newcharacter.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "path_info.h"
#include "pldata.h"
#include "popup.h"
#include "safemode_ui.h"
#include "scenario.h"
#include "sdlsound.h"
#include "sounds.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui_manager.h"
#include "ui.h"
#include "wcwidth.h"
#include "worldfactory.h"
Classes
class sound_on_move_uilist_callback
Enumerations
enum class main_menu_opts : int {
MOTD = 0 , NEWCHAR = 1 , LOADCHAR = 2 , WORLD = 3 ,
SETTINGS = 4 , HELP = 5 , CREDITS = 6 , QUIT = 7
}
Functions
static int getopt (main_menu_opts o)
static int utf8_width_notags (const char *s)
Variables
static constexpr int max_menu_opts = 7
Enumeration Type Documentation
main_menu_opts
enum class main_menu_opts : int strong
Enumerator
MOTD
NEWCHAR
LOADCHAR
WORLD
SETTINGS
HELP
CREDITS
QUIT
Definition at line 53 of file main_menu.cpp.
                          : int {
    MOTD = 0,
    NEWCHAR = 1,
    LOADCHAR = 2,
    WORLD = 3,
    SETTINGS = 4,
    HELP = 5,
    CREDITS = 6,
    QUIT = 7
};
Function Documentation
getopt()
static int getopt (main_menu_opts o) static
Definition at line 65 of file main_menu.cpp.
{
    return static_cast<int>( o );
}
Referenced by main_menu::display_sub_menu(), main_menu::opening_screen(), and main_menu::print_menu().
utf8_width_notags()
static int utf8_width_notags (const char * s) static
Definition at line 100 of file main_menu.cpp.
{
    int len = strlen( s );
    const char *ptr = s;
    int w = 0;
    bool inside_tag = false;
    while( len > 0 ) {
        uint32_t ch = UTF8_getch( &ptr, &len );
        if( ch == UNKNOWN_UNICODE ) {
            continue;
        }
        if( ch == '<' ) {
            inside_tag = true;
        } else if( ch == '>' ) {
            inside_tag = false;
            continue;
        }
        if( inside_tag ) {
            continue;
        }
        w += mk_wcwidth( ch );
    }
    return w;
}
References mk_wcwidth(), ptr(), UNKNOWN_UNICODE, and UTF8_getch().
Referenced by main_menu::print_menu(), and main_menu::print_menu_items().
Variable Documentation
max_menu_opts
constexpr int max_menu_opts = 7 static constexpr
Definition at line 63 of file main_menu.cpp.
Referenced by main_menu::opening_screen().