Cataclysm BN: src/map_field.cpp File Reference
map_field.cpp File Reference
#include <algorithm>
#include <array>
#include <bitset>
#include <cstddef>
#include <list>
#include <memory>
#include <queue>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "avatar.h"
#include "basecamp.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "emit.h"
#include "enums.h"
#include "field.h"
#include "field_type.h"
#include "fire.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "item.h"
#include "item_contents.h"
#include "itype.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "optional.h"
#include "overmapbuffer.h"
#include "player.h"
#include "pldata.h"
#include "point.h"
#include "rng.h"
#include "scent_block.h"
#include "string_id.h"
#include "submap.h"
#include "teleport.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather.h"
Functions
static const std::string flag_FUNGUS ("FUNGUS")
static const std::string flag_GAS_PROOF ("GAS_PROOF")
bool ter_furn_has_flag (const ter_t &ter, const furn_t &furn, const ter_bitflags flag)
static int ter_furn_movecost (const ter_t &ter, const furn_t &furn)
static bool check_flammable (const map_data_common_t &t)
Variables
static const itype_id itype_rm13_armor_on ("rm13_armor_on")
static const itype_id itype_rock ("rock")
static const species_id FUNGUS ("FUNGUS")
static const species_id INSECT ("INSECT")
static const species_id SPIDER ("SPIDER")
static const bionic_id bio_heatsink ("bio_heatsink")
static const efftype_id effect_badpoison ("badpoison")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_corroding ("corroding")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_stung ("stung")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_teargas ("teargas")
static const efftype_id effect_webbed ("webbed")
static const trait_id trait_ACIDPROOF ("ACIDPROOF")
static const trait_id trait_ELECTRORECEPTORS ("ELECTRORECEPTORS")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_M_SKIN2 ("M_SKIN2")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const trait_id trait_WEB_WALKER ("WEB_WALKER")
Function Documentation
check_flammable()
static bool check_flammable (const map_data_common_t & t) inline static
Definition at line 354 of file map_field.cpp.
{
    return t.has_flag( TFLAG_FLAMMABLE ) || t.has_flag( TFLAG_FLAMMABLE_ASH ) ||
           t.has_flag( TFLAG_FLAMMABLE_HARD );
}
References map_data_common_t::has_flag(), TFLAG_FLAMMABLE, TFLAG_FLAMMABLE_ASH, and TFLAG_FLAMMABLE_HARD.
Referenced by map::process_fields_in_submap().
flag_FUNGUS()
static const std::string flag_FUNGUS ("FUNGUS") static
Referenced by map::process_fields_in_submap().
flag_GAS_PROOF()
static const std::string flag_GAS_PROOF ("GAS_PROOF") static
Referenced by map::player_in_field().
ter_furn_has_flag()
bool ter_furn_has_flag (const ter_t & ter, const furn_t & furn, const ter_bitflags flag)
Definition at line 161 of file map_field.cpp.
{
    return ter.has_flag( flag ) || furn.has_flag( flag );
}
References map_data_common_t::has_flag().
Referenced by MapExtras::burned_ground_parser(), map::gas_can_spread_to(), and map::process_fields_in_submap().
ter_furn_movecost()
static int ter_furn_movecost (const ter_t & ter, const furn_t & furn) static
Definition at line 166 of file map_field.cpp.
{
    if( ter.movecost == 0 ) {
        return 0;
    }
    if( furn.movecost < 0 ) {
        return 0;
    }
    return ter.movecost + furn.movecost;
}
References map_data_common_t::movecost.
Referenced by map::gas_can_spread_to().
Variable Documentation
bio_heatsink
const bionic_id bio_heatsink("bio_heatsink") ("bio_heatsink") static
Referenced by map::player_in_field().
effect_badpoison
const efftype_id effect_badpoison("badpoison") ("badpoison") static
Referenced by map::player_in_field().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by map::monster_in_field(), and map::player_in_field().
effect_corroding
const efftype_id effect_corroding("corroding") ("corroding") static
Referenced by map::burn_body_part(), and map::monster_in_field().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by map::player_in_field().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by map::monster_in_field(), and map::player_in_field().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by map::player_in_field().
effect_stung
const efftype_id effect_stung("stung") ("stung") static
Referenced by map::player_in_field().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by map::monster_in_field().
effect_teargas
const efftype_id effect_teargas("teargas") ("teargas") static
Referenced by map::player_in_field().
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
Referenced by map::monster_in_field(), and map::player_in_field().
FUNGUS
const species_id FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by map::monster_in_field().
INSECT
const species_id INSECT("INSECT") ("INSECT") static
Referenced by map::monster_in_field().
itype_rm13_armor_on
const itype_id itype_rm13_armor_on("rm13_armor_on") ("rm13_armor_on") static
Referenced by map::player_in_field().
itype_rock
const itype_id itype_rock("rock") ("rock") static
Referenced by map::process_fields_in_submap().
SPIDER
const species_id SPIDER("SPIDER") ("SPIDER") static
Referenced by map::monster_in_field().
trait_ACIDPROOF
const trait_id trait_ACIDPROOF("ACIDPROOF") ("ACIDPROOF") static
Referenced by map::player_in_field().
trait_ELECTRORECEPTORS
const trait_id trait_ELECTRORECEPTORS("ELECTRORECEPTORS") ("ELECTRORECEPTORS") static
Referenced by map::player_in_field().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by map::player_in_field().
trait_M_SKIN2
const trait_id trait_M_SKIN2("M_SKIN2") ("M_SKIN2") static
Referenced by map::player_in_field().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by map::player_in_field().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by map::player_in_field().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by map::player_in_field().
trait_WEB_WALKER
const trait_id trait_WEB_WALKER("WEB_WALKER") ("WEB_WALKER") static
Referenced by map::player_in_field().