Cataclysm BN: src/map_iterator.h File Reference
map_iterator.h File Reference
#include <cstddef>
#include "enums.h"
#include "point.h"
#include "point_traits.h"
Classes
class tripoint_range< Tripoint >
class tripoint_range< Tripoint >::point_generator
Generates points in a rectangle.
Macros
#define CATA_SRC_MAP_ITERATOR_H
Functions
template<typename Tripoint >
tripoint_range< Tripoint > points_in_radius (const Tripoint &center, const int radius, const int radiusz=0)
Macro Definition Documentation
CATA_SRC_MAP_ITERATOR_H
#define CATA_SRC_MAP_ITERATOR_H
Definition at line 3 of file map_iterator.h.
Function Documentation
points_in_radius()
template<typename Tripoint > tripoint_range< Tripoint > points_in_radius (const Tripoint & center, const int radius, const int radiusz = 0) inline
Definition at line 125 of file map_iterator.h.
{
    static_assert( Tripoint::dimension == 3, "Requires tripoint type" );
    const tripoint offset( radius, radius, radiusz );
    return tripoint_range<Tripoint>( center - offset, center + offset );
}
References center.
Referenced by timed_event::actualize(), Character::apply_persistent_morale(), board_up(), overmap::build_slimepit(), can_construct(), vehicle::autodrive_controller::compute_profile(), fungal_effects::create_spores(), monster::die(), enumerate_objects_around_point(), Character::forced_dismount(), has_pre_terrain(), talk_function::om_building_region(), sounds::process_sound_markers(), random_house_in_city(), overmap_ui::search(), spell_effect::spell_effect_blast(), start_location::surround_with_monsters(), activity_handlers::tree_communion_do_turn(), game::update_overmap_seen(), place_npc_iuse::use(), and game::vertical_notes().