Cataclysm BN: src/map_extras.cpp File Reference
map_extras.cpp File Reference
#include "map_extras.h"
#include <array>
#include <cstdlib>
#include <map>
#include <memory>
#include <set>
#include <unordered_map>
#include <utility>
#include <vector>
#include "auto_note.h"
#include "calendar.h"
#include "cata_utility.h"
#include "cellular_automata.h"
#include "character_id.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "debug.h"
#include "enum_conversions.h"
#include "enums.h"
#include "field_type.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "int_id.h"
#include "item.h"
#include "item_group.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapgen.h"
#include "mapgen_functions.h"
#include "mapgendata.h"
#include "mongroup.h"
#include "optional.h"
#include "options.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "point_float.h"
#include "regional_settings.h"
#include "rng.h"
#include "string_formatter.h"
#include "string_id.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_group.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weighted_list.h"
Namespaces
namespace io
namespace anonymous_namespace{map_extras.cpp}
namespace MapExtras
Functions
static const std::string flag_DIGGABLE ("DIGGABLE")
static const std::string flag_FLAT ("FLAT")
static const std::string flag_FLOWER ("FLOWER")
static const std::string flag_FUNGUS ("FUNGUS")
static const std::string flag_LIQUID ("LIQUID")
static const std::string flag_ORGANIC ("ORGANIC")
static const std::string flag_PLANT ("PLANT")
static const std::string flag_SHRUB ("SHRUB")
static const std::string flag_TREE ("TREE")
static const std::string flag_YOUNG ("YOUNG")
template<>
std::string io::enum_to_string< map_extra_method > (map_extra_method data)
const generic_factory< map_extra > & MapExtras::mapExtraFactory ()
This function provides access to all loaded map extras.
static bool MapExtras::mx_null (map &, const tripoint &)
static void MapExtras::dead_vegetation_parser (map &m, const tripoint &loc)
static bool MapExtras::mx_house_wasp (map &m, const tripoint &loc)
static bool MapExtras::mx_house_spider (map &m, const tripoint &loc)
static bool MapExtras::mx_helicopter (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_military (map &m, const tripoint &)
static bool MapExtras::mx_science (map &m, const tripoint &)
static bool MapExtras::mx_collegekids (map &m, const tripoint &)
static bool MapExtras::mx_roadblock (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_marloss_pilgrimage (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_bandits_block (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_drugdeal (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_supplydrop (map &m, const tripoint &)
static bool MapExtras::mx_portal (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_minefield (map &m_orig, const tripoint &abs_sub)
static bool MapExtras::mx_crater (map &m, const tripoint &abs_sub)
static void MapExtras::place_fumarole (map &m, const point &p1, const point &p2, std::set< point > &ignited)
static bool MapExtras::mx_portal_in (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_shia (map &m, const tripoint &loc)
static bool MapExtras::mx_spider (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_jabberwock (map &m, const tripoint &loc)
static bool MapExtras::mx_grove (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_shrubbery (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_clearcut (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_pond (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_clay_deposit (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_dead_vegetation (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_point_dead_vegetation (map &m, const tripoint &abs_sub)
static void MapExtras::burned_ground_parser (map &m, const tripoint &loc)
static bool MapExtras::mx_point_burned_ground (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_burned_ground (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_roadworks (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_mayhem (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_casings (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_looters (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_corpses (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_grave (map &m, const tripoint &abs_sub)
map_extra_pointer MapExtras::get_function (const std::string &name)
std::vector< std::string > MapExtras::get_all_function_names ()
void MapExtras::apply_function (const string_id< map_extra > &id, map &m, const tripoint &abs_sub)
void MapExtras::apply_function (const std::string &id, map &m, const tripoint &abs_sub)
FunctionMap MapExtras::all_functions ()
void MapExtras::load (const JsonObject &jo, const std::string &src)
void MapExtras::check_consistency ()
void MapExtras::reset ()
void MapExtras::debug_spawn_test ()
Variables
static const itype_id itype_223_casing ("223_casing")
static const itype_id itype_762_51_casing ("762_51_casing")
static const itype_id itype_9mm_casing ("9mm_casing")
static const itype_id itype_acoustic_guitar ("acoustic_guitar")
static const itype_id itype_anbc_suit ("anbc_suit")
static const itype_id itype_ash ("ash")
static const itype_id itype_bag_canvas ("bag_canvas")
static const itype_id itype_bottle_glass ("bottle_glass")
static const itype_id itype_bullwhip ("bullwhip")
static const itype_id itype_chunk_sulfur ("chunk_sulfur")
static const itype_id itype_coke ("coke")
static const itype_id itype_crowbar ("crowbar")
static const itype_id itype_fedora ("fedora")
static const itype_id itype_glasses_eye ("glasses_eye")
static const itype_id itype_hatchet ("hatchet")
static const itype_id itype_heroin ("heroin")
static const itype_id itype_holybook_bible1 ("holybook_bible1")
static const itype_id itype_indoor_volleyball ("indoor_volleyball")
static const itype_id itype_jacket_leather ("jacket_leather")
static const itype_id itype_katana ("katana")
static const itype_id itype_landmine ("landmine")
static const itype_id itype_machete ("machete")
static const itype_id itype_material_sand ("material_sand")
static const itype_id itype_material_soil ("material_soil")
static const itype_id itype_meth ("meth")
static const itype_id itype_rag_bloody ("rag_bloody")
static const itype_id itype_remington_870_breacher ("remington_870_breacher")
static const itype_id itype_shot_hull ("shot_hull")
static const itype_id itype_splinter ("splinter")
static const itype_id itype_stanag30 ("stanag30")
static const itype_id itype_stick ("stick")
static const itype_id itype_stick_long ("stick_long")
static const itype_id itype_sunglasses ("sunglasses")
static const itype_id itype_sw_619 ("sw_619")
static const itype_id itype_touring_suit ("touring_suit")
static const itype_id itype_tux ("tux")
static const itype_id itype_umbrella ("umbrella")
static const itype_id itype_usp_45 ("usp_45")
static const itype_id itype_vodka ("vodka")
static const itype_id itype_weed ("weed")
static const itype_id itype_wheel ("wheel")
static const itype_id itype_withered ("withered")
static const itype_id itype_wrench ("wrench")
static const ter_str_id ter_dirt ("t_dirt")
static const ter_str_id ter_grass_dead ("t_grass_dead")
static const ter_str_id ter_stump ("t_stump")
static const ter_str_id ter_tree_dead ("t_tree_dead")
static const ter_str_id ter_tree_deadpine ("t_tree_deadpine")
static const ter_str_id ter_tree_birch_harvested ("t_tree_birch_harvested")
static const ter_str_id ter_tree_hickory_dead ("t_tree_hickory_dead")
static const ter_str_id ter_trunk ("t_trunk")
static const mongroup_id GROUP_FISH ("GROUP_FISH")
static const mongroup_id GROUP_FUNGI_FUNGALOID ("GROUP_FUNGI_FUNGALOID")
static const mongroup_id GROUP_MAYBE_MIL ("GROUP_MAYBE_MIL")
static const mongroup_id GROUP_MI_GO_CAMP_OM ("GROUP_MI-GO_CAMP_OM")
static const mongroup_id GROUP_NETHER_CAPTURED ("GROUP_NETHER_CAPTURED")
static const mongroup_id GROUP_NETHER_PORTAL ("GROUP_NETHER_PORTAL")
static const mongroup_id GROUP_PETS ("GROUP_PETS")
static const mongroup_id GROUP_STRAY_DOGS ("GROUP_STRAY_DOGS")
static const mtype_id mon_dispatch ("mon_dispatch")
static const mtype_id mon_fleshy_shambler ("mon_fleshy_shambler")
static const mtype_id mon_marloss_zealot_f ("mon_marloss_zealot_f")
static const mtype_id mon_marloss_zealot_m ("mon_marloss_zealot_m")
static const mtype_id mon_shia ("mon_shia")
static const mtype_id mon_spider_cellar_giant ("mon_spider_cellar_giant")
static const mtype_id mon_spider_web ("mon_spider_web")
static const mtype_id mon_spider_widow_giant ("mon_spider_widow_giant")
static const mtype_id mon_turret_medium ("mon_turret_medium")
static const mtype_id mon_turret_searchlight ("mon_turret_searchlight")
static const mtype_id mon_turret_longrange ("mon_turret_longrange")
static const mtype_id mon_turret_riot ("mon_turret_riot")
static const mtype_id mon_wasp ("mon_wasp")
static const mtype_id mon_wolf ("mon_wolf")
static const mtype_id mon_zombie_bio_op ("mon_zombie_bio_op")
static const mtype_id mon_zombie_military_pilot ("mon_zombie_military_pilot")
static const mtype_id mon_zombie_scientist ("mon_zombie_scientist")
static const mtype_id mon_zombie_smoker ("mon_zombie_smoker")
static const mtype_id mon_zombie_soldier ("mon_zombie_soldier")
static const mtype_id mon_zombie_spitter ("mon_zombie_spitter")
static const mtype_id mon_zombie_tough ("mon_zombie_tough")
generic_factory< map_extra > anonymous_namespace{map_extras.cpp}::extras ("map extra")
FunctionMap MapExtras::builtin_functions
std::vector< std::string > MapExtras::all_function_names
std::map< std::string, std::vector< std::unique_ptr< update_mapgen_function_json > > > update_mapgen
Function Documentation
flag_DIGGABLE()
static const std::string flag_DIGGABLE ("DIGGABLE") static
Referenced by MapExtras::mx_minefield().
flag_FLAT()
static const std::string flag_FLAT ("FLAT") static
Referenced by MapExtras::mx_spider().
flag_FLOWER()
static const std::string flag_FLOWER ("FLOWER") static
Referenced by MapExtras::dead_vegetation_parser().
flag_FUNGUS()
static const std::string flag_FUNGUS ("FUNGUS") static
Referenced by MapExtras::burned_ground_parser().
flag_LIQUID()
static const std::string flag_LIQUID ("LIQUID") static
Referenced by MapExtras::burned_ground_parser().
flag_ORGANIC()
static const std::string flag_ORGANIC ("ORGANIC") static
Referenced by MapExtras::dead_vegetation_parser().
flag_PLANT()
static const std::string flag_PLANT ("PLANT") static
Referenced by MapExtras::dead_vegetation_parser().
flag_SHRUB()
static const std::string flag_SHRUB ("SHRUB") static
Referenced by MapExtras::dead_vegetation_parser(), MapExtras::mx_grove(), MapExtras::mx_shrubbery(), and MapExtras::mx_spider().
flag_TREE()
static const std::string flag_TREE ("TREE") static
Referenced by MapExtras::burned_ground_parser(), MapExtras::dead_vegetation_parser(), MapExtras::mx_clearcut(), MapExtras::mx_grove(), MapExtras::mx_shrubbery(), and MapExtras::mx_spider().
flag_YOUNG()
static const std::string flag_YOUNG ("YOUNG") static
Referenced by MapExtras::dead_vegetation_parser(), MapExtras::mx_clearcut(), MapExtras::mx_grove(), and MapExtras::mx_shrubbery().
Variable Documentation
GROUP_FISH
const mongroup_id GROUP_FISH("GROUP_FISH") ("GROUP_FISH") static
Referenced by MapExtras::mx_pond().
GROUP_FUNGI_FUNGALOID
const mongroup_id GROUP_FUNGI_FUNGALOID("GROUP_FUNGI_FUNGALOID") ("GROUP_FUNGI_FUNGALOID") static
Referenced by MapExtras::mx_portal_in().
GROUP_MAYBE_MIL
const mongroup_id GROUP_MAYBE_MIL("GROUP_MAYBE_MIL") ("GROUP_MAYBE_MIL") static
Referenced by MapExtras::mx_military().
GROUP_MI_GO_CAMP_OM
const mongroup_id GROUP_MI_GO_CAMP_OM("GROUP_MI-GO_CAMP_OM") ("GROUP_MI-GO_CAMP_OM") static
Referenced by MapExtras::mx_portal_in().
GROUP_NETHER_CAPTURED
const mongroup_id GROUP_NETHER_CAPTURED("GROUP_NETHER_CAPTURED") ("GROUP_NETHER_CAPTURED") static
Referenced by MapExtras::mx_collegekids(), MapExtras::mx_drugdeal(), MapExtras::mx_military(), and MapExtras::mx_science().
GROUP_NETHER_PORTAL
const mongroup_id GROUP_NETHER_PORTAL("GROUP_NETHER_PORTAL") ("GROUP_NETHER_PORTAL") static
Referenced by MapExtras::mx_portal(), and MapExtras::mx_portal_in().
GROUP_PETS
const mongroup_id GROUP_PETS("GROUP_PETS") ("GROUP_PETS") static
Referenced by MapExtras::mx_grave().
GROUP_STRAY_DOGS
const mongroup_id GROUP_STRAY_DOGS("GROUP_STRAY_DOGS") ("GROUP_STRAY_DOGS") static
Referenced by MapExtras::mx_corpses().
itype_223_casing
const itype_id itype_223_casing("223_casing") ("223_casing") static
Referenced by MapExtras::mx_mayhem(), and MapExtras::mx_minefield().
itype_762_51_casing
const itype_id itype_762_51_casing("762_51_casing") ("762_51_casing") static
Referenced by MapExtras::mx_minefield().
itype_9mm_casing
const itype_id itype_9mm_casing("9mm_casing") ("9mm_casing") static
Referenced by MapExtras::mx_mayhem().
itype_acoustic_guitar
const itype_id itype_acoustic_guitar("acoustic_guitar") ("acoustic_guitar") static
Referenced by MapExtras::mx_grave(), and MapExtras::mx_minefield().
itype_anbc_suit
const itype_id itype_anbc_suit("anbc_suit") ("anbc_suit") static
Referenced by MapExtras::mx_grave().
itype_ash
const itype_id itype_ash("ash") ("ash") static
Referenced by MapExtras::burned_ground_parser().
itype_bag_canvas
const itype_id itype_bag_canvas("bag_canvas") ("bag_canvas") static
Referenced by MapExtras::mx_minefield().
itype_bottle_glass
const itype_id itype_bottle_glass("bottle_glass") ("bottle_glass") static
Referenced by MapExtras::mx_minefield().
itype_bullwhip
const itype_id itype_bullwhip("bullwhip") ("bullwhip") static
Referenced by MapExtras::mx_grave().
itype_chunk_sulfur
const itype_id itype_chunk_sulfur("chunk_sulfur") ("chunk_sulfur") static
Referenced by MapExtras::place_fumarole().
itype_coke
const itype_id itype_coke("coke") ("coke") static
Referenced by MapExtras::mx_drugdeal().
itype_crowbar
const itype_id itype_crowbar("crowbar") ("crowbar") static
Referenced by MapExtras::mx_grave().
itype_fedora
const itype_id itype_fedora("fedora") ("fedora") static
Referenced by MapExtras::mx_grave().
itype_glasses_eye
const itype_id itype_glasses_eye("glasses_eye") ("glasses_eye") static
Referenced by MapExtras::mx_grave().
itype_hatchet
const itype_id itype_hatchet("hatchet") ("hatchet") static
Referenced by MapExtras::mx_minefield().
itype_heroin
const itype_id itype_heroin("heroin") ("heroin") static
Referenced by MapExtras::mx_drugdeal().
itype_holybook_bible1
const itype_id itype_holybook_bible1("holybook_bible1") ("holybook_bible1") static
Referenced by MapExtras::mx_grave().
itype_indoor_volleyball
const itype_id itype_indoor_volleyball("indoor_volleyball") ("indoor_volleyball") static
Referenced by MapExtras::mx_grave().
itype_jacket_leather
const itype_id itype_jacket_leather("jacket_leather") ("jacket_leather") static
Referenced by MapExtras::mx_grave().
itype_katana
const itype_id itype_katana("katana") ("katana") static
Referenced by MapExtras::mx_grave().
itype_landmine
const itype_id itype_landmine("landmine") ("landmine") static
Referenced by MapExtras::mx_minefield().
itype_machete
const itype_id itype_machete("machete") ("machete") static
Referenced by MapExtras::mx_grave().
itype_material_sand
const itype_id itype_material_sand("material_sand") ("material_sand") static
Referenced by MapExtras::mx_minefield().
itype_material_soil
const itype_id itype_material_soil("material_soil") ("material_soil") static
Referenced by MapExtras::mx_roadworks().
itype_meth
const itype_id itype_meth("meth") ("meth") static
Referenced by MapExtras::mx_drugdeal().
itype_rag_bloody
const itype_id itype_rag_bloody("rag_bloody") ("rag_bloody") static
Referenced by MapExtras::mx_casings().
itype_remington_870_breacher
const itype_id itype_remington_870_breacher("remington_870_breacher") ("remington_870_breacher") static
Referenced by MapExtras::mx_grave().
itype_shot_hull
const itype_id itype_shot_hull("shot_hull") ("shot_hull") static
Referenced by MapExtras::mx_mayhem().
itype_splinter
const itype_id itype_splinter("splinter") ("splinter") static
Referenced by MapExtras::mx_minefield().
itype_stanag30
const itype_id itype_stanag30("stanag30") ("stanag30") static
Referenced by MapExtras::mx_minefield().
itype_stick
const itype_id itype_stick("stick") ("stick") static
Referenced by MapExtras::dead_vegetation_parser().
itype_stick_long
const itype_id itype_stick_long("stick_long") ("stick_long") static
Referenced by MapExtras::dead_vegetation_parser().
itype_sunglasses
const itype_id itype_sunglasses("sunglasses") ("sunglasses") static
Referenced by MapExtras::mx_grave().
itype_sw_619
const itype_id itype_sw_619("sw_619") ("sw_619") static
Referenced by MapExtras::mx_grave().
itype_touring_suit
const itype_id itype_touring_suit("touring_suit") ("touring_suit") static
Referenced by MapExtras::mx_grave().
itype_tux
const itype_id itype_tux("tux") ("tux") static
Referenced by MapExtras::mx_grave().
itype_umbrella
const itype_id itype_umbrella("umbrella") ("umbrella") static
Referenced by MapExtras::mx_grave().
itype_usp_45
const itype_id itype_usp_45("usp_45") ("usp_45") static
Referenced by MapExtras::mx_grave().
itype_vodka
const itype_id itype_vodka("vodka") ("vodka") static
Referenced by MapExtras::mx_minefield().
itype_weed
const itype_id itype_weed("weed") ("weed") static
Referenced by MapExtras::mx_drugdeal().
itype_wheel
const itype_id itype_wheel("wheel") ("wheel") static
Referenced by MapExtras::mx_mayhem().
itype_withered
const itype_id itype_withered("withered") ("withered") static
Referenced by MapExtras::dead_vegetation_parser().
itype_wrench
const itype_id itype_wrench("wrench") ("wrench") static
Referenced by MapExtras::mx_mayhem().
mon_dispatch
const mtype_id mon_dispatch("mon_dispatch") ("mon_dispatch") static
Referenced by MapExtras::mx_military().
mon_fleshy_shambler
const mtype_id mon_fleshy_shambler("mon_fleshy_shambler") ("mon_fleshy_shambler") static
Referenced by MapExtras::mx_jabberwock().
mon_marloss_zealot_f
const mtype_id mon_marloss_zealot_f("mon_marloss_zealot_f") ("mon_marloss_zealot_f") static
Referenced by MapExtras::mx_marloss_pilgrimage().
mon_marloss_zealot_m
const mtype_id mon_marloss_zealot_m("mon_marloss_zealot_m") ("mon_marloss_zealot_m") static
Referenced by MapExtras::mx_marloss_pilgrimage().
mon_shia
const mtype_id mon_shia("mon_shia") ("mon_shia") static
Referenced by MapExtras::mx_shia().
mon_spider_cellar_giant
const mtype_id mon_spider_cellar_giant("mon_spider_cellar_giant") ("mon_spider_cellar_giant") static
Referenced by MapExtras::mx_house_spider().
mon_spider_web
const mtype_id mon_spider_web("mon_spider_web") ("mon_spider_web") static
Referenced by MapExtras::mx_spider().
mon_spider_widow_giant
const mtype_id mon_spider_widow_giant("mon_spider_widow_giant") ("mon_spider_widow_giant") static
Referenced by MapExtras::mx_house_spider().
mon_turret_longrange
const mtype_id mon_turret_longrange("mon_turret_longrange") ("mon_turret_longrange") static
Referenced by MapExtras::mx_roadblock().
mon_turret_medium
const mtype_id mon_turret_medium("mon_turret_medium") ("mon_turret_medium") static
Referenced by MapExtras::mx_roadblock().
mon_turret_riot
const mtype_id mon_turret_riot("mon_turret_riot") ("mon_turret_riot") static
Referenced by MapExtras::mx_roadblock().
mon_turret_searchlight
const mtype_id mon_turret_searchlight("mon_turret_searchlight") ("mon_turret_searchlight") static
Referenced by MapExtras::mx_roadblock().
mon_wasp
const mtype_id mon_wasp("mon_wasp") ("mon_wasp") static
Referenced by MapExtras::mx_house_wasp().
mon_wolf
const mtype_id mon_wolf("mon_wolf") ("mon_wolf") static
Referenced by MapExtras::mx_mayhem().
mon_zombie_bio_op
const mtype_id mon_zombie_bio_op("mon_zombie_bio_op") ("mon_zombie_bio_op") static
Referenced by MapExtras::mx_helicopter(), and MapExtras::mx_military().
mon_zombie_military_pilot
const mtype_id mon_zombie_military_pilot("mon_zombie_military_pilot") ("mon_zombie_military_pilot") static
Referenced by MapExtras::mx_helicopter().
mon_zombie_scientist
const mtype_id mon_zombie_scientist("mon_zombie_scientist") ("mon_zombie_scientist") static
Referenced by MapExtras::mx_helicopter(), and MapExtras::mx_science().
mon_zombie_smoker
const mtype_id mon_zombie_smoker("mon_zombie_smoker") ("mon_zombie_smoker") static
Referenced by MapExtras::mx_drugdeal().
mon_zombie_soldier
const mtype_id mon_zombie_soldier("mon_zombie_soldier") ("mon_zombie_soldier") static
Referenced by MapExtras::mx_helicopter(), and MapExtras::mx_military().
mon_zombie_spitter
const mtype_id mon_zombie_spitter("mon_zombie_spitter") ("mon_zombie_spitter") static
Referenced by MapExtras::mx_drugdeal().
mon_zombie_tough
const mtype_id mon_zombie_tough("mon_zombie_tough") ("mon_zombie_tough") static
Referenced by MapExtras::mx_collegekids().
ter_dirt
const ter_str_id ter_dirt("t_dirt") ("t_dirt") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_grass_dead
const ter_str_id ter_grass_dead("t_grass_dead") ("t_grass_dead") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_stump
const ter_str_id ter_stump("t_stump") ("t_stump") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_tree_birch_harvested
const ter_str_id ter_tree_birch_harvested("t_tree_birch_harvested") ("t_tree_birch_harvested") static
Referenced by MapExtras::dead_vegetation_parser().
ter_tree_dead
const ter_str_id ter_tree_dead("t_tree_dead") ("t_tree_dead") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_tree_deadpine
const ter_str_id ter_tree_deadpine("t_tree_deadpine") ("t_tree_deadpine") static
Referenced by MapExtras::dead_vegetation_parser().
ter_tree_hickory_dead
const ter_str_id ter_tree_hickory_dead("t_tree_hickory_dead") ("t_tree_hickory_dead") static
Referenced by MapExtras::dead_vegetation_parser().
ter_trunk
const ter_str_id ter_trunk("t_trunk") ("t_trunk") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
update_mapgen
std::map<std::string, std::vector<std::unique_ptr<update_mapgen_function_json> > > update_mapgen extern
Definition at line 362 of file mapgen.cpp.
Referenced by calculate_mapgen_weights(), check_mapgen_definitions(), get_changed_ids_from_update(), mapgen::has_update_id(), mission_util::load_funcs(), load_update_mapgen(), reset_mapgens(), and run_mapgen_update_func().