Cataclysm BN: src/map_selector.cpp File Reference
map_selector.cpp File Reference
#include "map_selector.h"
#include <algorithm>
#include <functional>
#include <memory>
#include <vector>
#include "game.h"
#include "game_constants.h"
#include "map.h"
#include "map_iterator.h"
#include "optional.h"
#include "rng.h"
Functions
tripoint_range< tripoint > points_in_range (const map &m)
Returns a range enclosing all valid points of the map.
cata::optional< tripoint > random_point (const map &m, const std::function< bool(const tripoint &)> &predicate)
Same as other random_point with a range enclosing all valid points of the map.
cata::optional< tripoint > random_point (const tripoint_range< tripoint > &range, const std::function< bool(const tripoint &)> &predicate)
Returns a random point in the given range that satisfies the given predicate (if any).
Function Documentation
points_in_range()
tripoint_range< tripoint > points_in_range (const map & m)
Returns a range enclosing all valid points of the map.
Definition at line 24 of file map_selector.cpp.
{
    const int z = m.get_abs_sub().z;
    const bool hasz = m.has_zlevels();
    return tripoint_range<tripoint>(
               tripoint( 0, 0, hasz ? -OVERMAP_DEPTH : z ),
               tripoint( SEEX * m.getmapsize() - 1, SEEY * m.getmapsize() - 1, hasz ? OVERMAP_HEIGHT : z ) );
}
References map::get_abs_sub(), map::getmapsize(), map::has_zlevels(), OVERMAP_DEPTH, OVERMAP_HEIGHT, SEEX, SEEY, and tripoint::z.
Referenced by random_point().
random_point() [1/2]
cata::optional< tripoint > random_point (const map & m, const std::function< bool(const tripoint &)> & predicate)
Same as other random_point with a range enclosing all valid points of the map.
Definition at line 33 of file map_selector.cpp.
{
    return random_point( points_in_range( m ), predicate );
}
References points_in_range(), and random_point().
Referenced by choose_where_to_place_monster(), map::draw_connections(), map::draw_lab(), map::draw_mine(), game::forced_door_closing(), map::generate(), MapExtras::mx_collegekids(), MapExtras::mx_looters(), MapExtras::mx_marloss_pilgrimage(), MapExtras::mx_military(), MapExtras::mx_portal(), MapExtras::mx_roadblock(), MapExtras::mx_science(), MapExtras::mx_supplydrop(), overmap::place_forest_trails(), map::process_fields_in_submap(), random_point(), map::spawn_monsters_submap(), and place_npc_iuse::use().
random_point() [2/2]
cata::optional< tripoint > random_point (const tripoint_range< tripoint > & range, const std::function< bool(const tripoint &)> & predicate)
Returns a random point in the given range that satisfies the given predicate (if any).
Definition at line 39 of file map_selector.cpp.
{
    // Optimist approach: just assume there are plenty of suitable places and a randomly
    // chosen point will have a good chance to hit one of them.
    // If there are only few suitable places, we have to find them all, otherwise this loop may never finish.
    for( int tries = 0; tries < 10; ++tries ) {
        const tripoint p( rng( range.min().x, range.max().x ), rng( range.min().y, range.max().y ),
                          rng( range.min().z, range.max().z ) );
        if( predicate( p ) ) {
            return p;
        }
    }
    std::vector<tripoint> suitable;
    for( const auto &p : range ) {
        if( predicate( p ) ) {
            suitable.push_back( p );
        }
    }
    if( suitable.empty() ) {
        return {};
    }
    return random_entry( suitable );
}
References tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::min(), random_entry(), and rng().