Cataclysm BN: src/map.h File Reference
map.h File Reference
#include <array>
#include <bitset>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "enums.h"
#include "filter_utils.h"
#include "game_constants.h"
#include "item.h"
#include "item_stack.h"
#include "lightmap.h"
#include "line.h"
#include "lru_cache.h"
#include "mapdata.h"
#include "memory_fast.h"
#include "point.h"
#include "shadowcasting.h"
#include "type_id.h"
#include "units.h"
Classes
struct wrapped_vehicle
class map_stack
struct visibility_variables
struct bash_params
struct bash_results
struct drawsq_params
Draw parameters used by map::drawsq() and similar methods.
struct diagonal_blocks
struct level_cache
class map
Manage and cache data about a part of the map.
struct map::apparent_light_info
class tinymap
class fake_map
Namespaces
namespace catacurses
Contains the curses interface used by the whole game.
namespace cata
Macros
#define CATA_SRC_MAP_H
Typedefs
using VehicleList = std::vector< wrapped_vehicle >
Functions
map & get_map ()
template<int SIZE, int MULTIPLIER>
void shift_bitset_cache (std::bitset< SIZE *SIZE > &cache, const point &s)
bool ter_furn_has_flag (const ter_t &ter, const furn_t &furn, ter_bitflags flag)
Variables
bool disable_mapgen
Causes all generated maps to be empty grass and prevents saved maps from being loaded, used by the test suite.
Macro Definition Documentation
CATA_SRC_MAP_H
#define CATA_SRC_MAP_H
Definition at line 3 of file map.h.
Typedef Documentation
VehicleList
using VehicleList = std::vector<wrapped_vehicle>
Definition at line 85 of file map.h.
Function Documentation
get_map()
map & get_map ()
Definition at line 149 of file map.cpp.
{
    return g->m;
}
Referenced by basecamp::abandon_camp(), Character::absorb_hit(), vehicle::act_on_map(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_elevator_on(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_lock(), computer_session::action_open(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_sample(), computer_session::action_shutters(), computer_session::action_srcf_seal(), computer_session::action_terminate(), computer_session::action_unlock(), Character::activate_bionic(), enchantment::activate_passive(), activity_on_turn_move_loot(), zone_manager::add(), ter_furn_transform::add_all_messages(), add_basecamp_storage_to_loot_zone_list(), map::add_field(), advanced_inventory_pane::add_items_from_area(), Character::add_known_trap(), vehicle::adjust_zlevel(), vehicle::advance_precalc_mounts(), iexamine::aggie_plant(), npc::alt_attack(), item::ammo_consume(), apply< furn_t >(), apply< ter_t >(), apply< trap >(), apply_ammo_effects(), apply_camp_ownership(), apply_lock_picking_tool(), apply_prying_tool(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), are_requirements_nearby(), npc::assess_danger(), assign_veh_to_follow(), Creature::auto_find_hostile_target(), iexamine::autoclave_full(), iexamine::autodoc(), iexamine::bars(), character_funcs::base_comfort_value(), talk_function::basecamp_mission(), spell_effect::bash(), Creature::bleed(), Character::blossoms(), mattack::boomer(), mattack::boomer_glow(), activity_handlers::build_do_turn(), iexamine::bulletin_board(), Character::burn_fuel(), activity_handlers::burrow_finish(), butcher_corpse_activity(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), zone_manager::cache_vzones(), leap_actor::call(), can_butcher_at(), can_construct(), can_do_activity_there(), can_examine_at(), iexamine::can_fertilize(), can_interact_at(), Character::can_mount(), npc::can_move_to(), can_move_vertical_at(), npc::can_open_door(), can_pickup_at(), monster::can_reach_to(), monster::can_squeeze_to(), defense_game::caravan(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), advanced_inventory::change_square(), construct::check_deconstruct(), vehicle::autodrive_controller::check_drivable(), player::check_eligible_containers_for_crafting(), construct::check_empty(), vehicle::check_falling_or_floating(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), deploy_tent_actor::check_intact(), vehicle::check_is_heli_landed(), construct::check_no_trap(), Character::check_outbounds_activity(), construct::check_ramp_high(), relic_funcs::check_recharge_reqs(), construct::check_support(), choose_adjacent(), choose_adjacent_highlight(), target_ui::choose_initial_target(), activity_handlers::chop_logs_finish(), chop_plank_activity(), activity_handlers::chop_planks_finish(), chop_tree_activity(), activity_handlers::chop_tree_do_turn(), activity_handlers::chop_tree_finish(), activity_handlers::churn_finish(), cleanup_tiles(), activity_handlers::clear_rubble_finish(), clear_shot_reach(), close(), talk_function::companion_return(), complete_construction(), veh_interact::complete_vehicle(), vehicle::autodrive_controller::compute_obstacles(), consider_butchery(), construction_activity(), basecamp_action_components::consume_components(), player::consume_items(), Character::consume_remote_fuel(), player::consume_tools(), iexamine::controls_gate(), npc::could_move_onto(), activity_handlers::cracking_finish(), spell::create_field(), fungal_effects::create_spores(), zone_manager::create_vehicle_loot_zone(), iexamine::curtains(), salvage_actor::cut_up(), cyborg_on_couch(), cycle_action(), vehicle::damage_direct(), monexamine::deactivate_pet(), debug_menu::debug(), iexamine::deployed_furniture(), item_location::impl::item_on_map::describe(), item_location::deserialize(), overmapbuffer::despawn_monster(), iuse::directional_antenna(), iexamine::dirtmound(), crafting::disassemble_all(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source(), displace_items_except_one_liquid(), basecamp::distribute_food(), explosion_handler::do_blast(), explosion_handler::do_blast_new(), character_funcs::do_pause(), npc::do_pulp(), aim_activity_actor::do_turn(), construct::done_deconstruct(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_upstair(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wood_stairs(), iexamine::door_peephole(), editmap_hilight::draw(), draw_health_classic(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), target_ui::draw_terrain_overlay(), draw_veh_compact(), draw_veh_padding(), Character::drop(), Character::drop_invalid_inventory(), npc::drop_items(), drop_on_map(), drop_or_embed_projectile(), talk_function::drop_stolen_item(), talk_function::drop_weapon(), monexamine::dump_items(), avatar_action::eat_here(), editmap::edit(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), editmap::edit_veh(), iexamine::egg_sack_generic(), iexamine::elevator(), explosion_handler::emp_blast(), enumerate_objects_around_point(), Character::env_surgery_bonus(), npc::execute_action(), ranged::execute_shaped_attack(), ranged::expected_coverage(), extract_or_wreck_cbms(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_secubots(), computer_session::failure_shutdown(), farm_action(), feature< furn_id >(), feature< ter_id >(), feature< trap_id >(), iexamine::fertilize_plant(), fetch_activity(), activity_handlers::fill_liquid_do_turn(), activity_handlers::fill_pit_finish(), find_auto_consume(), find_base_construction(), find_best_fire(), find_closest_stair(), npc::find_corpse_to_pulp(), npc::find_dangerous_explosives(), npc::find_item(), find_refuel_spot_zone(), Character::find_remote_fuel(), find_target_vehicle(), character_funcs::fine_detail_vision_mod(), dig_activity_actor::finish(), dig_channel_activity_actor::finish(), disassemble_activity_actor::finish(), hacking_activity_actor::finish(), fire(), ranged::fire_gun(), iexamine::fireplace(), mattack::flame(), explosion_handler::explosion_funcs::flashbang(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), mdeath::focused_beam(), activity_handlers::forage_finish(), Character::forced_dismount(), basecamp::form_crafting_inventory(), advanced_inv_area::free_volume(), fromPumpFuel(), iexamine::fswitch(), iuse::fungicide(), mdeath::fungus(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), generate_weather_anim_frame(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_basecamp(), avatar::get_book_reader(), zone_manager::get_bottom_zone(), item::get_cable_target(), advanced_inv_area::get_container(), get_convection_temperature(), character_funcs::get_crafting_helpers(), player::get_eligible_containers_for_crafting(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), anonymous_namespace{gates.cpp}::get_gate_id(), get_hack_type(), get_heat_radiation(), advanced_inv_area::get_item_count(), get_item_location(), get_keg_capacity(), liquid_handler::get_liquid_target(), overmapbuffer::get_npcs_near_player(), overmap_ui::get_overmap_path_to(), zone_manager::get_point_set_loot(), player_activity::get_progress_message(), map_memory::get_submap(), ranged::get_weapon_dispersion(), zone_manager::get_zone_at(), get_zone_for_act(), zone_manager::get_zones(), iexamine::getGasPumpByNumber(), iexamine::getNearFilledGasTank(), getNearPumpCount(), Character::global_square_location(), vehicle::global_square_location(), npc::go_to_omt_destination(), npc::good_escape_direction(), good_fishing_spot(), grab(), npc::guard_current_pos(), activity_handlers::hacksaw_finish(), handbrake(), handle_action_menu(), handle_harvest(), liquid_handler::handle_liquid_from_ground(), npc::handle_sound(), vehicle::handle_trap(), harvest_common(), iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_plant(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), Character::has_alarm_clock(), has_clear_path_to_pickup_items(), Character::has_destination_activity(), Character::has_fire(), has_neighbor(), has_pre_terrain(), Character::has_watch(), haul(), Character::heat_emission(), Character::i_add_or_drop(), Character::in_climate_control(), in_spell_aoe(), scent_map::inbounds(), talk_function::individual_mission(), advanced_inv_area::init(), vehicle::interact_with(), enchantment::is_active(), place_trap_actor::is_allowed(), Character::is_deaf(), is_driving(), is_player_outside(), Character::is_snuggling(), is_solid_neighbor(), anonymous_namespace{gates.cpp}::gate_data::is_suitable_wall(), ma_requirements::is_valid_character(), behavior::monster_oracle_t::items_available(), activity_handlers::jackhammer_do_turn(), activity_handlers::jackhammer_finish(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), Character::knock_back_to(), Character::knows_trap(), iexamine::ledge(), firestarter_actor::light_mod(), advanced_inventory_pane::load_settings(), iexamine::locked_object(), iexamine::locked_object_pickable(), activity_handlers::longsalvage_finish(), mattack::longswipe(), make_active(), make_mon_corpse(), trapfunc::map_regen(), map_selector::map_selector(), editmap::mapgen_preview(), editmap::mapgen_veh_destroy(), vehicle::merge_rackable_vehicle(), iexamine::migo_nerve_cluster(), activity_handlers::milk_finish(), monexamine::milk_source(), mill_activate(), iexamine::mill_finalize(), mill_load_food(), mine_activity(), Character::modify_morale(), monster::move(), npc::move(), avatar_action::move(), advanced_inventory::move_all_items(), npc::move_away_from(), move_cost(), move_item(), npc::move_to(), firestarter_actor::moves_cost_by_fuel(), Character::mutation_effect(), iexamine::nanofab(), nearest_passable(), iexamine::none(), iuse::note_bionics(), item::on_drop(), iexamine::on_smoke_out(), open(), vehicle::open_or_close(), iexamine::open_safe(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), map_cursor::operator tripoint(), operator_present(), activity_handlers::oxytorch_finish(), vehicle::part_collision(), vehicle::part_removal_cleanup(), Character::passive_power_gen(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), tutorial_game::per_turn(), Character::perform_install(), liquid_handler::perform_liquid_transfer(), Character::perform_uninstall(), perform_zone_activity_turn(), photo_def_for_camera_point(), pick_plant(), character_funcs::pick_safe_adjacent_tile(), npc::pick_up_item(), npc::pick_up_item_map(), activity_handlers::pickaxe_do_turn(), activity_handlers::pickaxe_finish(), iexamine::pit(), iexamine::pit_covered(), place_and_add_as_known(), place_construction(), Character::place_corpse(), basecamp::place_results(), iexamine::plant_seed(), activity_handlers::plant_seed_finish(), player_on_couch(), talk_function::player_weapon_drop(), pldrive(), points_for_gas_cloud(), iexamine::portable_structure(), tutorial_game::post_action(), iexamine::pour_into_keg(), firestarter_actor::prep_firestarter_use(), map_memory::prepare_region(), print_aim(), advanced_inventory::print_items(), item::process_cable(), item::process_extinguish(), item::process_fake_mill(), item::process_fake_smoke(), map::process_fields_in_submap(), item::process_internal(), item::process_litcig(), relic_funcs::process_recharge_entry(), item::process_rot(), sounds::process_sound_markers(), sounds::process_sounds(), projectile_attack(), spell_effect::projectile_attack(), prompt_disassemble_single(), vehicle_part::properties_to_item(), activity_handlers::pry_nails_finish(), activity_handlers::pulp_do_turn(), monster::push_to(), put_into_vehicle(), put_into_vehicle_or_drop(), iexamine::quern_examine(), plot_options::query_seed(), mattack::ranged_pull(), character_funcs::rate_sleep_spot(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), item::ready_to_revive(), target_ui::recalc_aim_turning_penalty(), editmap::recalc_target(), ranged::recoil_vehicle(), iexamine::recycle_compactor(), npc::regen_ai_cache(), iexamine::reload_furniture(), avatar_action::reload_weapon(), zone_manager::remove(), monexamine::remove_armor(), monexamine::remove_bag_from(), monexamine::remove_battery(), remove_submap_turrets(), map::remove_trap(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), iuse::report_grid_charge(), iuse::report_grid_connections(), requirements_map(), firestarter_actor::resolve_firestarter_use(), explosion_handler::explosion_funcs::resonance_cascade(), aim_activity_actor::restore_view(), zone_manager::revert_vzones(), mattack::riotbot(), rod_fish(), Character::rooted(), Character::rooted_message(), map::rotate(), route_adjacent(), iexamine::rubble(), target_ui::run(), area_expander::run(), examine_item_menu::run(), Character::run_cost(), iexamine::safe(), mapbuffer::save(), npc::saw_player_recently(), scatter_chunks(), monster::scent_move(), character_funcs::search_surroundings(), npc::see_item_say_smth(), Creature::sees(), Character::sees(), npc::sees_dangerous_field(), Character::sees_with_infrared(), serialize_liquid_source(), advanced_inv_area::set_container_position(), target_ui::set_cursor_pos(), Character::set_destination(), DefaultRemovePartHandler::set_floor_cache_dirty(), conditional_t< T >::set_is_driving(), conditional_t< T >::set_is_outside(), set_item_map(), set_item_map_or_vehicle(), target_ui::set_last_target(), avatar::set_movement_mode(), npc::set_omt_destination(), DefaultRemovePartHandler::set_transparency_cache_dirty(), target_ui::set_view_offset(), editmap::setup_fmenu(), monexamine::shear_animal(), activity_handlers::shear_finish(), vehicle::shift_zlevel(), live_view::show(), explosion_handler::shrapnel(), mattack::shriek_stun(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), Character::sight_range(), iexamine::sign(), sinkhole_safety_roll(), vehicle::slowdown(), smash(), smoker_activate(), smoker_finalize(), smoker_load_food(), iexamine::smoker_options(), map::spawn_monsters_submap(), debug_menu::spawn_nested_mapgen(), spawn_spores(), spell_effect::spawn_summoned_vehicle(), spell_effect::spell_effect_blast(), spell_effect::spell_effect_cone(), spell_move(), item::spill_contents(), item_contents::spill_contents(), mdeath::splatter(), vehicle::split_vehicles(), Character::spores(), fungal_effects::spread_fungus(), map::spread_gas(), autodrive_activity_actor::start(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), stash_on_pet(), vehicle::stop(), mattack::stretch_bite(), monster::stumble(), Character::suffer_from_asthma(), Character::suffer_from_other_mutations(), Character::suffer_from_radiation(), Character::suffer_in_sunlight(), Character::suffer_while_underwater(), Character::symbol_color(), ranged::targetable_creatures(), teleport::teleport(), tell_magic_veh_stop_following(), tell_magic_veh_to_follow(), tell_veh_stop_following(), terrain_collision_data(), test_passable(), vehicle::thrust(), tidy_activity(), gates::toggle_gate(), iexamine::toilet(), iexamine::toPumpFuel(), vehicle::total_wind_epower_w(), ter_furn_transform::transform(), iexamine::translocator(), iexamine::trap(), activity_handlers::travel_do_turn(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), explosion_iuse::trigger_explosion(), try_fuel_fire(), target_ui::try_reacquire_target(), try_remove_bear_trap(), try_remove_grab(), try_remove_heavysnare(), try_remove_lightsnare(), avatar_funcs::try_to_sleep(), turnOnSelectedPump(), editmap::uber_draw_ter(), iuse::unfold_generic(), Character::uninstall_bionic(), unroll_digging(), distribution_grid_tracker::update(), update_lum(), Character::update_needs(), npc::update_path(), target_ui::update_status(), editmap::update_view_with_help(), weather_manager::update_weather(), iuse_transform::use(), unfold_vehicle_iuse::use(), consume_drug_iuse::use(), place_npc_iuse::use(), pick_lock_actor::use(), deploy_furn_actor::use(), firestarter_actor::use(), enzlave_actor::use(), place_trap_actor::use(), emit_actor::use(), deploy_tent_actor::use(), unpack_actor::use(), vehicle::use_bike_rack(), Character::use_fire(), iexamine::use_furn_fake_item(), basecamp::validate_sort_points(), vehicle_activity(), activity_handlers::vehicle_finish(), vehicle_selector::vehicle_selector(), iexamine::vending(), Character::vomit(), wait(), iexamine::water_source(), iuse::weather_tool(), avatar_action::wield(), workbench_crafting_speed_multiplier(), and npc::worker_downtime().
shift_bitset_cache()
template<int SIZE, int MULTIPLIER> void shift_bitset_cache (std::bitset< SIZE *SIZE > & cache, const point & s)
Definition at line 6680 of file map.cpp.
{
    // sx shifts by MULTIPLIER rows, sy shifts by MULTIPLIER columns.
    int shift_amount = s.x * MULTIPLIER + s.y * SIZE * MULTIPLIER;
    if( shift_amount > 0 ) {
        cache >>= static_cast<size_t>( shift_amount );
    } else if( shift_amount < 0 ) {
        cache <<= static_cast<size_t>( -shift_amount );
    }
    // Shifting in the y direction shifted in 0 values, no no additional clearing is necessary, but
    // a shift in the x direction makes values "wrap" to the next row, and they need to be zeroed.
    if( s.x == 0 ) {
        return;
    }
    const size_t x_offset = s.x > 0 ? SIZE - MULTIPLIER : 0;
    for( size_t y = 0; y < SIZE; ++y ) {
        size_t y_offset = y * SIZE;
        for( size_t x = 0; x < MULTIPLIER; ++x ) {
            cache.reset( y_offset + x_offset + x );
        }
    }
}
References point::x, and point::y.
ter_furn_has_flag()
bool ter_furn_has_flag (const ter_t & ter, const furn_t & furn, ter_bitflags flag)
Definition at line 161 of file map_field.cpp.
{
    return ter.has_flag( flag ) || furn.has_flag( flag );
}
References map_data_common_t::has_flag().
Referenced by MapExtras::burned_ground_parser(), map::gas_can_spread_to(), and map::process_fields_in_submap().
Variable Documentation
disable_mapgen
bool disable_mapgen extern
Causes all generated maps to be empty grass and prevents saved maps from being loaded, used by the test suite.
Definition at line 144 of file map.cpp.
Referenced by mapgen_factory::generate(), and mapbuffer::save_quad().