Cataclysm BN: src/map_memory.cpp File Reference
map_memory.cpp File Reference
#include "map_memory.h"
#include "coordinate_conversions.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "game.h"
#include "line.h"
#include "translations.h"
#include "map.h"
Classes
struct reg_coord_pair
Helper class for converting global sm coord into global mm_region coord + sm coord within the region.
Macros
#define MM_SIZE (MAPSIZE * 2)
#define dbg(x) DebugLog((x),DC::MapMem)
Functions
static std::string find_legacy_mm_file ()
static std::string find_mm_dir ()
static std::string find_region_path (const std::string &dirname, const tripoint &p)
static void temp_remove_open_air (shared_ptr_fast< mm_submap > sm)
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),DC::MapMem)
Definition at line 17 of file map_memory.cpp.
MM_SIZE
#define MM_SIZE (MAPSIZE * 2)
Definition at line 15 of file map_memory.cpp.
Function Documentation
find_legacy_mm_file()
static std::string find_legacy_mm_file () static
Definition at line 19 of file map_memory.cpp.
{
    return g->get_player_base_save_path() + ".mm";
}
References g.
Referenced by map_memory::load().
find_mm_dir()
static std::string find_mm_dir () static
Definition at line 24 of file map_memory.cpp.
{
    return string_format( "%s.mm1", g->get_player_base_save_path() );
}
References g, and string_format().
Referenced by map_memory::load(), map_memory::load_submap(), and map_memory::save().
find_region_path()
static std::string find_region_path (const std::string & dirname, const tripoint & p) static
Definition at line 29 of file map_memory.cpp.
{
    return string_format( "%s/%d.%d.%d.mmr", dirname, p.x, p.y, p.z );
}
References string_format(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by map_memory::load_submap(), and map_memory::save().
temp_remove_open_air()
static void temp_remove_open_air (shared_ptr_fast< mm_submap > sm) static
Definition at line 214 of file map_memory.cpp.
{
    if( sm->is_empty() ) {
        return;
    }
    for( int x = 0; x < SEEX; x++ ) {
        for( int y = 0; y < SEEY; y++ ) {
            const memorized_terrain_tile &t = sm->tile( {x, y} );
            if( !t.tile.empty() && t.tile == "t_open_air" ) {
                sm->set_tile( {x, y}, mm_submap::default_tile );
            }
        }
    }
}
References mm_submap::default_tile, SEEX, SEEY, coords::sm, and memorized_terrain_tile::tile.
Referenced by map_memory::load_submap().