Cataclysm BN: src/mattack_actors.cpp File Reference
mattack_actors.cpp File Reference
#include "mattack_actors.h"
#include <algorithm>
#include <limits>
#include <memory>
#include <optional>
#include "avatar.h"
#include "calendar.h"
#include "creature.h"
#include "enums.h"
#include "game.h"
#include "generic_factory.h"
#include "gun_mode.h"
#include "int_id.h"
#include "item.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "material.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "player.h"
#include "point.h"
#include "ranged.h"
#include "rng.h"
#include "sounds.h"
#include "translations.h"
#include "vehicle.h"
#include "vpart_range.h"
#include "effect.h"
Functions
static bool is_adjacent (const monster &z, const Creature &target)
static std::optional< tripoint > find_target_vehicle (monster &z, int range)
Variables
static const efftype_id effect_badpoison ("badpoison")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_laserlocked ("laserlocked")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_targeted ("targeted")
static const efftype_id effect_was_laserlocked ("was_laserlocked")
static const trait_id trait_TOXICFLESH ("TOXICFLESH")
static const trait_id trait_NORANGEDCRIT ("NO_RANGED_CRIT")
Function Documentation
find_target_vehicle()
static std::optional< tripoint > find_target_vehicle (monster & z, int range) static
Definition at line 485 of file mattack_actors.cpp.
{
    map &here = get_map();
    bool found = false;
    tripoint aim_at;
    for( wrapped_vehicle &v : here.get_vehicles() ) {
        if( ( !fov_3d && v.pos.z != z.pos().z ) || v.v->velocity == 0 ) {
            continue;
        }
        bool found_controls = false;
        for( const vpart_reference &vp : v.v->get_avail_parts( "CONTROLS" ) ) {
            if( z.sees( vp.pos() ) ) {
                int new_dist = rl_dist( z.pos(), vp.pos() );
                if( new_dist <= range ) {
                    aim_at = vp.pos();
                    range = new_dist;
                    found = true;
                    found_controls = true;
                }
            }
        }
        if( !found_controls ) {
            std::vector<tripoint> line = here.find_clear_path( z.pos(), v.v->global_pos3() );
            tripoint prev_point = z.pos();
            for( tripoint &i : line ) {
                if( here.floor_between( prev_point, i ) ) {
                    break;
                }
                optional_vpart_position vp = here.veh_at( i );
                if( vp && &vp->vehicle() == v.v ) {
                    int new_dist = rl_dist( z.pos(), i );
                    if( new_dist <= range ) {
                        aim_at = i;
                        range = new_dist;
                        found = true;
                    }
                    break;
                }
                if( !here.is_transparent( i ) ) {
                    break;
                }
                prev_point = i;
            }
        }
    }
    if( found ) {
        return std::make_optional( aim_at );
    } else {
        return std::optional<tripoint>();
    }
}
References map::find_clear_path(), map::floor_between(), fov_3d, get_map(), map::get_vehicles(), map::is_transparent(), line(), monster::pos(), rl_dist(), Creature::sees(), map::veh_at(), and tripoint::z.
Referenced by gun_actor::call().
is_adjacent()
static bool is_adjacent (const monster & z, const Creature & target) static
Definition at line 48 of file mattack_actors.cpp.
{
    if( rl_dist( z.pos(), target.pos() ) != 1 ) {
        return false;
    }
    if( !z.can_squeeze_to( target.pos() ) ) {
        return false;
    }
    return z.posz() == target.posz();
}
References monster::can_squeeze_to(), Creature::pos(), monster::pos(), Creature::posz(), monster::posz(), and rl_dist().
Referenced by melee_actor::find_target(), and game::try_get_right_click_action().
Variable Documentation
effect_badpoison
const efftype_id effect_badpoison("badpoison") ("badpoison") static
Referenced by bite_actor::on_damage().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by bite_actor::on_damage().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by bite_actor::on_damage().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by bite_actor::on_damage().
effect_laserlocked
const efftype_id effect_laserlocked("laserlocked") ("laserlocked") static
Referenced by gun_actor::try_target().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by bite_actor::on_damage().
effect_targeted
const efftype_id effect_targeted("targeted") ("targeted") static
Referenced by gun_actor::try_target().
effect_was_laserlocked
const efftype_id effect_was_laserlocked("was_laserlocked") ("was_laserlocked") static
Referenced by gun_actor::try_target().
trait_NORANGEDCRIT
const trait_id trait_NORANGEDCRIT("NO_RANGED_CRIT") ("NO_RANGED_CRIT") static
Referenced by gun_actor::shoot().
trait_TOXICFLESH
const trait_id trait_TOXICFLESH("TOXICFLESH") ("TOXICFLESH") static
Referenced by bite_actor::on_damage().