Cataclysm BN: src/memorial_logger.cpp File Reference
memorial_logger.cpp File Reference
#include "memorial_logger.h"
#include <istream>
#include <list>
#include <map>
#include <memory>
#include <tuple>
#include <utility>
#include "addiction.h"
#include "avatar.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_variant.h"
#include "character_id.h"
#include "debug.h"
#include "effect.h"
#include "event.h"
#include "event_statistics.h"
#include "filesystem.h"
#include "game.h"
#include "get_version.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "itype.h"
#include "kill_tracker.h"
#include "magic.h"
#include "martialarts.h"
#include "messages.h"
#include "monstergenerator.h"
#include "mtype.h"
#include "mutation.h"
#include "omdata.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pldata.h"
#include "profession.h"
#include "skill.h"
#include "stats_tracker.h"
#include "string_id.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
Variables
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_datura ("datura")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_jetinjector ("jetinjector")
static const trap_str_id tr_bubblewrap ("tr_bubblewrap")
static const trap_str_id tr_glass ("tr_glass")
static const trap_str_id tr_beartrap ("tr_beartrap")
static const trap_str_id tr_nailboard ("tr_nailboard")
static const trap_str_id tr_caltrops ("tr_caltrops")
static const trap_str_id tr_caltrops_glass ("tr_caltrops_glass")
static const trap_str_id tr_tripwire ("tr_tripwire")
static const trap_str_id tr_crossbow ("tr_crossbow")
static const trap_str_id tr_shotgun_2 ("tr_shotgun_2")
static const trap_str_id tr_shotgun_1 ("tr_shotgun_1")
static const trap_str_id tr_blade ("tr_blade")
static const trap_str_id tr_landmine ("tr_landmine")
static const trap_str_id tr_light_snare ("tr_light_snare")
static const trap_str_id tr_heavy_snare ("tr_heavy_snare")
static const trap_str_id tr_telepad ("tr_telepad")
static const trap_str_id tr_goo ("tr_goo")
static const trap_str_id tr_dissector ("tr_dissector")
static const trap_str_id tr_sinkhole ("tr_sinkhole")
static const trap_str_id tr_pit ("tr_pit")
static const trap_str_id tr_spike_pit ("tr_spike_pit")
static const trap_str_id tr_lava ("tr_lava")
static const trap_str_id tr_portal ("tr_portal")
static const trap_str_id tr_ledge ("tr_ledge")
static const trap_str_id tr_boobytrap ("tr_boobytrap")
static const trap_str_id tr_temple_flood ("tr_temple_flood")
static const trap_str_id tr_shadow ("tr_shadow")
static const trap_str_id tr_drain ("tr_drain")
static const trap_str_id tr_snake ("tr_snake")
static const trap_str_id tr_glass_pit ("tr_glass_pit")
static const trait_id trait_CANNIBAL ("CANNIBAL")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_SAPIOVORE ("SAPIOVORE")
Variable Documentation
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by memorial_logger::notify().
effect_datura
const efftype_id effect_datura("datura") ("datura") static
Referenced by memorial_logger::notify().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by memorial_logger::notify().
effect_jetinjector
const efftype_id effect_jetinjector("jetinjector") ("jetinjector") static
Referenced by memorial_logger::notify().
tr_beartrap
const trap_str_id tr_beartrap("tr_beartrap") ("tr_beartrap") static
Referenced by memorial_logger::notify().
tr_blade
const trap_str_id tr_blade("tr_blade") ("tr_blade") static
Referenced by memorial_logger::notify().
tr_boobytrap
const trap_str_id tr_boobytrap("tr_boobytrap") ("tr_boobytrap") static
Referenced by memorial_logger::notify().
tr_bubblewrap
const trap_str_id tr_bubblewrap("tr_bubblewrap") ("tr_bubblewrap") static
Referenced by memorial_logger::notify().
tr_caltrops
const trap_str_id tr_caltrops("tr_caltrops") ("tr_caltrops") static
Referenced by memorial_logger::notify().
tr_caltrops_glass
const trap_str_id tr_caltrops_glass("tr_caltrops_glass") ("tr_caltrops_glass") static
Referenced by memorial_logger::notify().
tr_crossbow
const trap_str_id tr_crossbow("tr_crossbow") ("tr_crossbow") static
Referenced by memorial_logger::notify().
tr_dissector
const trap_str_id tr_dissector("tr_dissector") ("tr_dissector") static
Referenced by map::draw_lab(), memorial_logger::notify(), and science_room().
tr_drain
const trap_str_id tr_drain("tr_drain") ("tr_drain") static
Referenced by map::create_anomaly(), and memorial_logger::notify().
tr_glass
const trap_str_id tr_glass("tr_glass") ("tr_glass") static
Referenced by memorial_logger::notify().
tr_glass_pit
const trap_str_id tr_glass_pit("tr_glass_pit") ("tr_glass_pit") static
Referenced by memorial_logger::notify().
tr_goo
const trap_str_id tr_goo("tr_goo") ("tr_goo") static
Referenced by iuse::can_goo(), memorial_logger::notify(), explosion_handler::explosion_funcs::resonance_cascade(), and science_room().
tr_heavy_snare
const trap_str_id tr_heavy_snare("tr_heavy_snare") ("tr_heavy_snare") static
Referenced by memorial_logger::notify().
tr_landmine
const trap_str_id tr_landmine("tr_landmine") ("tr_landmine") static
Referenced by MapExtras::mx_minefield(), and memorial_logger::notify().
tr_lava
const trap_str_id tr_lava("tr_lava") ("tr_lava") static
Referenced by get_convection_temperature(), and memorial_logger::notify().
tr_ledge
const trap_str_id tr_ledge("tr_ledge") ("tr_ledge") static
Referenced by map::actualize(), game::fling_creature(), game::get_dangerous_tile(), iexamine::ledge(), memorial_logger::notify(), game::prompt_dangerous_tile(), map::ter_set(), and map::valid_move().
tr_light_snare
const trap_str_id tr_light_snare("tr_light_snare") ("tr_light_snare") static
Referenced by memorial_logger::notify().
tr_nailboard
const trap_str_id tr_nailboard("tr_nailboard") ("tr_nailboard") static
Referenced by memorial_logger::notify().
tr_pit
const trap_str_id tr_pit("tr_pit") ("tr_pit") static
Referenced by memorial_logger::notify(), and sinkhole_safety_roll().
tr_portal
const trap_str_id tr_portal("tr_portal") ("tr_portal") static
Referenced by computer_session::action_portal(), map::draw_lab(), MapExtras::mx_portal(), memorial_logger::notify(), iuse::portal(), game::process_artifact(), and explosion_handler::explosion_funcs::resonance_cascade().
tr_shadow
const trap_str_id tr_shadow("tr_shadow") ("tr_shadow") static
Referenced by map::create_anomaly(), and memorial_logger::notify().
tr_shotgun_1
const trap_str_id tr_shotgun_1("tr_shotgun_1") ("tr_shotgun_1") static
Referenced by memorial_logger::notify(), and trapfunc::shotgun().
tr_shotgun_2
const trap_str_id tr_shotgun_2("tr_shotgun_2") ("tr_shotgun_2") static
Referenced by memorial_logger::notify(), and trapfunc::shotgun().
tr_sinkhole
const trap_str_id tr_sinkhole("tr_sinkhole") ("tr_sinkhole") static
Referenced by memorial_logger::notify(), and character_funcs::search_surroundings().
tr_snake
const trap_str_id tr_snake("tr_snake") ("tr_snake") static
Referenced by map::create_anomaly(), and memorial_logger::notify().
tr_spike_pit
const trap_str_id tr_spike_pit("tr_spike_pit") ("tr_spike_pit") static
Referenced by memorial_logger::notify().
tr_telepad
const trap_str_id tr_telepad("tr_telepad") ("tr_telepad") static
Referenced by memorial_logger::notify(), and science_room().
tr_temple_flood
const trap_str_id tr_temple_flood("tr_temple_flood") ("tr_temple_flood") static
Referenced by map::draw_temple(), memorial_logger::notify(), and trapfunc::temple_flood().
tr_tripwire
const trap_str_id tr_tripwire("tr_tripwire") ("tr_tripwire") static
Referenced by memorial_logger::notify().
trait_CANNIBAL
const trait_id trait_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by memorial_logger::notify().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by memorial_logger::notify().
trait_SAPIOVORE
const trait_id trait_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by memorial_logger::notify().