Cataclysm BN: src/mission_util.cpp File Reference
mission_util.cpp File Reference
#include <algorithm>
#include <cassert>
#include <functional>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "avatar.h"
#include "coordinate_conversions.h"
#include "debug.h"
#include "dialogue.h"
#include "enum_conversions.h"
#include "enums.h"
#include "game.h"
#include "json.h"
#include "line.h"
#include "map_iterator.h"
#include "mapgen_functions.h"
#include "messages.h"
#include "mission.h"
#include "npc.h"
#include "omdata.h"
#include "optional.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "popup.h"
#include "rng.h"
#include "translations.h"
#include "type_id.h"
Functions
static tripoint_abs_omt reveal_destination (const std::string &type)
static void reveal_target (mission *miss, const std::string &omter_id)
static void reveal_any_target (mission *miss, const std::vector< std::string > &omter_ids)
static tripoint_abs_omt random_house_in_city (const city_reference &cref)
Given a (valid!) city reference, select a random house within the city borders.
static cata::optional< tripoint_abs_omt > find_or_create_om_terrain (const tripoint_abs_omt &origin_pos, const mission_target_params &params)
static tripoint_abs_omt get_mission_om_origin (const mission_target_params &params)
Function Documentation
find_or_create_om_terrain()
static cata::optional< tripoint_abs_omt > find_or_create_om_terrain (const tripoint_abs_omt & origin_pos, const mission_target_params & params) static
Definition at line 161 of file mission_util.cpp.
{
    tripoint_abs_omt target_pos = overmap::invalid_tripoint;
    omt_find_params find_params;
    std::vector<std::pair<std::string, ot_match_type>> temp_types;
    std::pair<std::string, ot_match_type> temp_pair;
    temp_pair.first = params.overmap_terrain;
    temp_pair.second = params.overmap_terrain_match_type;
    temp_types.push_back( temp_pair );
    find_params.types = temp_types;
    find_params.search_range = params.search_range;
    find_params.min_distance = params.min_distance;
    find_params.must_see = params.must_see;
    find_params.cant_see = params.cant_see;
    find_params.existing_only = true;
    find_params.popup = make_shared_fast<throbber_popup>( _( "Please wait…" ) );
    auto get_target_position = [&]() {
        // Either find a random or closest match, based on the criteria.
        if( params.random ) {
            target_pos = overmap_buffer.find_random( origin_pos, find_params );
        } else {
            target_pos = overmap_buffer.find_closest( origin_pos, find_params );
        }
        // If we didn't find a match, and we're allowed to create new terrain, and the player didn't
        // have to see the location beforehand, then we can attempt to create the new terrain.
        if( target_pos == overmap::invalid_tripoint && params.create_if_necessary &&
            !params.must_see ) {
            // If this terrain is part of an overmap special...
            if( params.overmap_special ) {
                // ...then attempt to place the whole special.
                const bool placed = overmap_buffer.place_special( *params.overmap_special, origin_pos,
                                    params.search_range );
                // If we succeeded in placing the special, then try and find the particular location
                // we're interested in.
                if( placed ) {
                    find_params.must_see = false;
                    target_pos = overmap_buffer.find_closest( origin_pos, find_params );
                }
            } else if( params.replaceable_overmap_terrain ) {
                // This terrain wasn't part of an overmap special, but we do have a replacement
                // terrain specified. Find a random location of that replacement type.
                find_params.must_see = false;
                find_params.types.front().first = *params.replaceable_overmap_terrain;
                target_pos = overmap_buffer.find_random( origin_pos, find_params );
                // We didn't find it, so allow this search to create new overmaps and try again.
                find_params.existing_only = true;
                if( target_pos == overmap::invalid_tripoint ) {
                    target_pos = overmap_buffer.find_random( origin_pos, find_params );
                }
                // We found a match, so set this position (which was our replacement terrain)
                // to our desired mission terrain.
                if( target_pos != overmap::invalid_tripoint ) {
                    overmap_buffer.ter_set( target_pos, oter_id( params.overmap_terrain ) );
                }
            }
        }
    };
    // First try to get the position where we only allow existing overmaps.
    get_target_position();
    if( target_pos == overmap::invalid_tripoint ) {
        // If it's invalid, then that means we couldn't find it or create it (if allowed) on
        // our current overmap. We'll now go ahead and try again but allow it to create new overmaps.
        find_params.existing_only = false;
        get_target_position();
    }
    // If we got here and this is still invalid, it means that we couldn't find it nor create it
    // on any overmap (new or existing) within the allowed search range.
    if( target_pos == overmap::invalid_tripoint ) {
        debugmsg( "Unable to find and assign mission target %s.", params.overmap_terrain );
        return cata::nullopt;
    }
    return target_pos;
}
References _, mission_target_params::cant_see, omt_find_params::cant_see, mission_target_params::create_if_necessary, debugmsg, omt_find_params::existing_only, overmapbuffer::find_closest(), overmapbuffer::find_random(), overmap::invalid_tripoint, mission_target_params::min_distance, omt_find_params::min_distance, mission_target_params::must_see, omt_find_params::must_see, cata::nullopt, overmap_buffer, mission_target_params::overmap_special, mission_target_params::overmap_terrain, mission_target_params::overmap_terrain_match_type, overmapbuffer::place_special(), omt_find_params::popup, mission_target_params::random, mission_target_params::replaceable_overmap_terrain, mission_target_params::search_range, omt_find_params::search_range, overmapbuffer::ter_set(), and omt_find_params::types.
Referenced by mission_util::assign_mission_target(), and mission_util::get_om_terrain_pos().
get_mission_om_origin()
static tripoint_abs_omt get_mission_om_origin (const mission_target_params & params) static
Definition at line 244 of file mission_util.cpp.
{
    // use the player or NPC's current position, adjust for the z value if any
    tripoint_abs_omt origin_pos = get_player_character().global_omt_location();
    if( !params.origin_u ) {
        npc *guy = nullptr;
        if( params.guy ) {
            guy = params.guy;
        } else if( params.mission_pointer ) {
            guy = g->find_npc( params.mission_pointer->get_npc_id() );
        }
        if( guy ) {
            origin_pos = guy->global_omt_location();
        }
    }
    if( params.z ) {
        origin_pos.z() = *params.z;
    }
    return origin_pos;
}
References g, mission::get_npc_id(), get_player_character(), Character::global_omt_location(), mission_target_params::guy, mission_target_params::mission_pointer, mission_target_params::origin_u, coords::coord_point< Point, Origin, Scale >::z(), and mission_target_params::z.
Referenced by mission_util::assign_mission_target(), and mission_util::get_om_terrain_pos().
random_house_in_city()
static tripoint_abs_omt random_house_in_city (const city_reference & cref) static
Given a (valid!) city reference, select a random house within the city borders.
Returns
global overmap terrain coordinates of the house.
Definition at line 105 of file mission_util.cpp.
{
    // TODO: fix point types
    const tripoint_abs_omt city_center_omt =
        project_to<coords::omt>( cref.abs_sm_pos );
    std::vector<tripoint_abs_omt> valid;
    for( const tripoint_abs_omt &p : points_in_radius( city_center_omt, cref.city->size ) ) {
        if( overmap_buffer.check_ot( "house", ot_match_type::prefix, p ) ) {
            valid.push_back( p );
        }
    }
    return random_entry( valid, city_center_omt ); // center of the city is a good fallback
}
References city_reference::abs_sm_pos, overmapbuffer::check_ot(), city_reference::city, overmap_buffer, points_in_radius(), prefix, random_entry(), and city::size.
Referenced by mission_util::random_house_in_closest_city().
reveal_any_target()
static void reveal_any_target (mission * miss, const std::vector< std::string > & omter_ids) static
Definition at line 68 of file mission_util.cpp.
{
    reveal_target( miss, random_entry( omter_ids ) );
}
References random_entry(), and reveal_target().
Referenced by mission_util::set_reveal_any().
reveal_destination()
static tripoint_abs_omt reveal_destination (const std::string & type) static
Definition at line 33 of file mission_util.cpp.
{
    const tripoint_abs_omt your_pos = get_player_character().global_omt_location();
    const tripoint_abs_omt center_pos =
        overmap_buffer.find_random( your_pos, type, rng( 40, 80 ), false );
    if( center_pos != overmap::invalid_tripoint ) {
        overmap_buffer.reveal( center_pos, 2 );
        return center_pos;
    }
    return overmap::invalid_tripoint;
}
References overmapbuffer::find_random(), get_player_character(), Character::global_omt_location(), overmap::invalid_tripoint, overmap_buffer, overmapbuffer::reveal(), rng(), and type.
Referenced by reveal_target().
reveal_target()
static void reveal_target (mission * miss, const std::string & omter_id) static
Definition at line 47 of file mission_util.cpp.
{
    const npc *p = g->find_npc( miss->get_npc_id() );
    if( p == nullptr ) {
        debugmsg( "couldn't find an NPC!" );
        return;
    }
    const tripoint_abs_omt destination = reveal_destination( omter_id );
    if( destination != overmap::invalid_tripoint ) {
        const oter_id oter = overmap_buffer.ter( destination );
        add_msg( _( "%s has marked the only %s known to them on your map." ), p->name,
                 oter->get_name() );
        miss->set_target( destination );
        if( one_in( 3 ) &&
            mission_util::reveal_road( g->u.global_omt_location(), destination, overmap_buffer ) ) {
            add_msg( _( "%s also marks the road that leads to it…" ), p->name );
        }
    }
}
References _, add_msg(), debugmsg, g, oter_t::get_name(), mission::get_npc_id(), overmap::invalid_tripoint, Character::name, one_in(), overmap_buffer, reveal_destination(), mission_util::reveal_road(), mission::set_target(), and overmapbuffer::ter().
Referenced by reveal_any_target(), and mission_util::set_reveal().