Cataclysm BN: src/mission_start.cpp File Reference
mission_start.cpp File Reference
#include "coordinates.h"
#include "mission.h"
#include <algorithm>
#include <memory>
#include <vector>
#include "avatar.h"
#include "computer.h"
#include "debug.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "item.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "name.h"
#include "npc.h"
#include "npc_class.h"
#include "omdata.h"
#include "optional.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "popup.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
Functions
static tripoint find_potential_computer_point (const tinymap &compmap)
static void create_lab_consoles (mission *miss, const tripoint_abs_omt &place, const std::string &otype, int security, const std::string &comp_name, const std::string &download_name)
Variables
static const itype_id itype_software_hacking ("software_hacking")
static const itype_id itype_software_math ("software_math")
static const itype_id itype_software_medical ("software_medical")
static const itype_id itype_software_useless ("software_useless")
static const mtype_id mon_dog ("mon_dog")
static const mtype_id mon_zombie ("mon_zombie")
static const mtype_id mon_zombie_brute ("mon_zombie_brute")
static const mtype_id mon_zombie_dog ("mon_zombie_dog")
static const mtype_id mon_zombie_hulk ("mon_zombie_hulk")
static const mtype_id mon_zombie_master ("mon_zombie_master")
static const mtype_id mon_zombie_necro ("mon_zombie_necro")
const int RANCH_SIZE = 5
Function Documentation
create_lab_consoles()
static void create_lab_consoles (mission * miss, const tripoint_abs_omt & place, const std::string & otype, int security, const std::string & comp_name, const std::string & download_name) static
Definition at line 648 of file mission_start.cpp.
{
    // Drop four computers in nearby lab spaces so the player can stumble upon one of them.
    for( int i = 0; i < 4; ++i ) {
        tripoint_abs_omt om_place = mission_util::target_om_ter_random(
                                        otype, -1, miss, false, 4, place );
        tinymap compmap;
        compmap.load( project_to<coords::sm>( om_place ), false );
        tripoint comppoint = find_potential_computer_point( compmap );
        computer *tmpcomp = compmap.add_computer( comppoint, _( comp_name ), security );
        tmpcomp->set_mission( miss->get_id() );
        tmpcomp->add_option( _( download_name ), COMPACT_DOWNLOAD_SOFTWARE, security );
        tmpcomp->add_failure( COMPFAIL_ALARM );
        tmpcomp->add_failure( COMPFAIL_DAMAGE );
        tmpcomp->add_failure( COMPFAIL_MANHACKS );
        compmap.save();
    }
}
References _, map::add_computer(), computer::add_failure(), computer::add_option(), COMPACT_DOWNLOAD_SOFTWARE, COMPFAIL_ALARM, COMPFAIL_DAMAGE, COMPFAIL_MANHACKS, find_potential_computer_point(), mission::get_id(), map::load(), map::save(), computer::set_mission(), and mission_util::target_om_ter_random().
Referenced by mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), and mission_start::create_lab_console().
find_potential_computer_point()
static tripoint find_potential_computer_point (const tinymap & compmap) static
Definition at line 136 of file mission_start.cpp.
{
    constexpr int rng_x_min = 10;
    constexpr int rng_x_max = SEEX * 2 - 11;
    constexpr int rng_y_min = 10;
    constexpr int rng_y_max = SEEY * 2 - 11;
    static_assert( rng_x_min <= rng_x_max && rng_y_min <= rng_y_max, "invalid randomization range" );
    std::vector<tripoint> broken;
    std::vector<tripoint> potential;
    std::vector<tripoint> last_resort;
    for( const tripoint &p : compmap.points_on_zlevel() ) {
        if( compmap.ter( p ) == t_console_broken ) {
            broken.emplace_back( p );
        } else if( broken.empty() && compmap.ter( p ) == t_floor && compmap.furn( p ) == f_null ) {
            for( const tripoint &p2 : compmap.points_in_radius( p, 1 ) ) {
                if( compmap.furn( p2 ) == f_bed || compmap.furn( p2 ) == f_dresser ) {
                    potential.emplace_back( p );
                    break;
                }
            }
            int wall = 0;
            for( const tripoint &p2 : compmap.points_in_radius( p, 1 ) ) {
                if( compmap.has_flag_ter( "WALL", p2 ) ) {
                    wall++;
                }
            }
            if( wall == 5 ) {
                if( compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::NORTH ) &&
                    compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::SOUTH ) &&
                    compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::WEST ) &&
                    compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::EAST ) ) {
                    potential.emplace_back( p );
                }
            }
        } else if( broken.empty() && potential.empty() && p.x >= rng_x_min && p.x <= rng_x_max
                   && p.y >= rng_y_min && p.y <= rng_y_max && compmap.ter( p ) != t_console ) {
            last_resort.emplace_back( p );
        }
    }
    std::vector<tripoint> *used = &broken;
    if( used->empty() ) {
        used = &potential;
    }
    if( used->empty() ) {
        used = &last_resort;
    }
    // if there's no possible location, then we have to overwrite an existing console...
    const tripoint fallback( rng( rng_x_min, rng_x_max ), rng( rng_y_min, rng_y_max ),
                             compmap.get_abs_sub().z );
    return random_entry( *used, fallback );
}
References broken, EAST, f_bed, f_dresser, f_null, map::furn(), map::get_abs_sub(), map::has_flag_ter(), map::is_last_ter_wall(), NORTH, map::points_in_radius(), map::points_on_zlevel(), random_entry(), rng(), SEEX, SEEY, SOUTH, t_console, t_console_broken, t_floor, map::ter(), WEST, and tripoint::z.
Referenced by create_lab_consoles(), and mission_start::place_npc_software().
Variable Documentation
itype_software_hacking
const itype_id itype_software_hacking("software_hacking") ("software_hacking") static
Referenced by mission_start::place_npc_software().
itype_software_math
const itype_id itype_software_math("software_math") ("software_math") static
Referenced by mission_start::place_npc_software().
itype_software_medical
const itype_id itype_software_medical("software_medical") ("software_medical") static
Referenced by mission_start::place_npc_software().
itype_software_useless
const itype_id itype_software_useless("software_useless") ("software_useless") static
Referenced by mission_start::place_npc_software().
mon_dog
const mtype_id mon_dog("mon_dog") ("mon_dog") static
Referenced by mission_start::place_dog().
mon_zombie
const mtype_id mon_zombie("mon_zombie") ("mon_zombie") static
Referenced by mission_start::kill_horde_master(), and mission_start::place_zombie_mom().
mon_zombie_brute
const mtype_id mon_zombie_brute("mon_zombie_brute") ("mon_zombie_brute") static
Referenced by mission_start::kill_horde_master().
mon_zombie_dog
const mtype_id mon_zombie_dog("mon_zombie_dog") ("mon_zombie_dog") static
Referenced by mission_start::kill_horde_master().
mon_zombie_hulk
const mtype_id mon_zombie_hulk("mon_zombie_hulk") ("mon_zombie_hulk") static
Referenced by mission_start::kill_horde_master().
mon_zombie_master
const mtype_id mon_zombie_master("mon_zombie_master") ("mon_zombie_master") static
Referenced by mission_start::kill_horde_master().
mon_zombie_necro
const mtype_id mon_zombie_necro("mon_zombie_necro") ("mon_zombie_necro") static
Referenced by mission_start::kill_horde_master().
RANCH_SIZE
const int RANCH_SIZE = 5
Definition at line 352 of file mission_start.cpp.
Referenced by mission_start::ranch_nurse_1(), mission_start::ranch_nurse_2(), mission_start::ranch_nurse_3(), mission_start::ranch_nurse_4(), mission_start::ranch_nurse_5(), mission_start::ranch_nurse_6(), mission_start::ranch_nurse_7(), mission_start::ranch_nurse_8(), mission_start::ranch_nurse_9(), mission_start::ranch_scavenger_1(), mission_start::ranch_scavenger_2(), and mission_start::ranch_scavenger_3().