Cataclysm BN: src/mod_manager.cpp File Reference
mod_manager.cpp File Reference
#include "mod_manager.h"
#include <algorithm>
#include <iterator>
#include <memory>
#include <ostream>
#include <queue>
#include "assign.h"
#include "cata_utility.h"
#include "debug.h"
#include "dependency_tree.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "json.h"
#include "path_info.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "worldfactory.h"
Namespaces
namespace mod_management
Functions
static const std::string MOD_SEARCH_FILE ("modinfo.json")
const std::vector< std::pair< std::string, std::string > > & get_mod_list_categories ()
const std::vector< std::pair< std::string, std::string > > & get_mod_list_tabs ()
const std::map< std::string, std::string > & get_mod_list_cat_tab ()
std::vector< MOD_INFORMATION > mod_management::load_mods_from (const std::string &path)
Load all modinfo.json files (recursively) from the given root.
cata::optional< MOD_INFORMATION > mod_management::load_modfile (const JsonObject &jo, const std::string &path)
Load mod info from a json object.
void mod_management::load_mod_info (const std::string &info_file_path, std::vector< MOD_INFORMATION > &out)
Load all mod information from a json file.
bool mod_management::save_mod_list (const t_mod_list &list, const std::string &path)
Save mod list to file.
cata::optional< t_mod_list > mod_management::load_mod_list (const std::string &path)
Load mod list from file.
mod_id mod_management::get_default_core_content_pack ()
Get id of default core content pack.
bool is_strict_enabled (const std::string &src)
Check whether strict checks are enabled for given mod.
bool compare_mod_by_name_and_category (const MOD_INFORMATION *const a, const MOD_INFORMATION *const b)
Function Documentation
compare_mod_by_name_and_category()
bool compare_mod_by_name_and_category (const MOD_INFORMATION *const a, const MOD_INFORMATION *const b) inline
Definition at line 473 of file mod_manager.cpp.
{
    return localized_compare( std::make_pair( a->category, a->name() ),
                              std::make_pair( b->category, b->name() ) );
}
References a, b, and localized_compare.
Referenced by mod_manager::get_all_sorted().
get_mod_list_cat_tab()
const std::map< std::string, std::string > & get_mod_list_cat_tab ()
Definition at line 91 of file mod_manager.cpp.
{
    static const std::map<std::string, std::string> mod_list_cat_tab = {
        {"item_exclude", "tab_blacklist"},
        {"monster_exclude", "tab_blacklist"},
        {"rebalance", "tab_balance"}
    };
    return mod_list_cat_tab;
}
Referenced by worldfactory::show_modselection_window().
get_mod_list_categories()
const std::vector< std::pair< std::string, std::string > > & get_mod_list_categories ()
Definition at line 59 of file mod_manager.cpp.
{
    static const std::vector<std::pair<std::string, std::string> > mod_list_categories = {
        {"core", translate_marker( "CORE GAME DATA" )},
        {"content", translate_marker( "CONTENT PACKS" )},
        {"items", translate_marker( "ITEM ADDITION MODS" )},
        {"creatures", translate_marker( "CREATURE MODS" )},
        {"misc_additions", translate_marker( "MISC ADDITIONS" )},
        {"buildings", translate_marker( "BUILDINGS MODS" )},
        {"vehicles", translate_marker( "VEHICLE MODS" )},
        {"rebalance", translate_marker( "REBALANCING MODS" )},
        {"magical", translate_marker( "MAGICAL MODS" )},
        {"item_exclude", translate_marker( "ITEM EXCLUSION MODS" )},
        {"monster_exclude", translate_marker( "MONSTER EXCLUSION MODS" )},
        {"graphical", translate_marker( "GRAPHICAL MODS" )},
        {"", translate_marker( "NO CATEGORY" )}
    };
    return mod_list_categories;
}
References translate_marker.
Referenced by mod_management::load_modfile(), and worldfactory::show_modselection_window().
get_mod_list_tabs()
const std::vector< std::pair< std::string, std::string > > & get_mod_list_tabs ()
Definition at line 80 of file mod_manager.cpp.
{
    static const std::vector<std::pair<std::string, std::string> > mod_list_tabs = {
        {"tab_default", translate_marker( "Default" )},
        {"tab_blacklist", translate_marker( "Blacklist" )},
        {"tab_balance", translate_marker( "Balance" )}
    };
    return mod_list_tabs;
}
References translate_marker.
Referenced by worldfactory::show_modselection_window().
is_strict_enabled()
bool is_strict_enabled (const std::string & src)
Check whether strict checks are enabled for given mod.
Definition at line 368 of file mod_manager.cpp.
{
    return src == mod_management::get_default_core_content_pack().str();
}
References mod_management::get_default_core_content_pack(), and string_id< T >::str().
Referenced by anonymous_namespace{mapdata.cpp}::is_json_check_strict(), generic_factory< T >::load(), harvest_entry::load(), mattack_actor::load(), mission_type::load(), mtype::load(), overmap_land_use_code::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), rotatable_symbols::load(), bionic_data::load(), Item_factory::load(), Item_factory::load_ammo(), Item_factory::load_basic_info(), and Item_factory::load_comestible().
MOD_SEARCH_FILE()
static const std::string MOD_SEARCH_FILE ("modinfo.json") static
Referenced by mod_management::load_mods_from().