Cataclysm BN: src/mod_manager_ui.cpp File Reference
mod_manager_ui.cpp File Reference
#include "mod_manager.h"
#include <algorithm>
#include <exception>
#include "color.h"
#include "debug.h"
#include "dependency_tree.h"
#include "output.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
Classes
struct conflict_pair
Functions
static std::string fmt_conflicts (const std::vector< conflict_pair > &list)
static void check_conflict (const mod_id &what, const mod_id &with, std::vector< conflict_pair > &ret)
static void check_conflicts (const mod_id &mod, const std::vector< mod_id > &active_list, std::vector< conflict_pair > &ret)
Function Documentation
check_conflict()
static void check_conflict (const mod_id & what, const mod_id & with, std::vector< conflict_pair > & ret) static
Definition at line 116 of file mod_manager_ui.cpp.
{
    auto it = std::find( what->conflicts.begin(), what->conflicts.end(), with );
    if( it != what->conflicts.end() ) {
        ret.emplace_back( conflict_pair{ what, with } );
        return;
    }
    it = std::find( with->conflicts.begin(), with->conflicts.end(), what );
    if( it != with->conflicts.end() ) {
        ret.emplace_back( conflict_pair{ what, with } );
    }
}
References MOD_INFORMATION::conflicts, detail::find(), and cata::hash64_detail::ret.
Referenced by check_conflicts().
check_conflicts()
static void check_conflicts (const mod_id & mod, const std::vector< mod_id > & active_list, std::vector< conflict_pair > & ret) static
Definition at line 131 of file mod_manager_ui.cpp.
{
    for( const auto &elem : active_list ) {
        check_conflict( mod, elem, ret );
    }
}
References check_conflict(), and cata::hash64_detail::ret.
Referenced by mod_ui::try_add().
fmt_conflicts()
static std::string fmt_conflicts (const std::vector< conflict_pair > & list) static
Definition at line 99 of file mod_manager_ui.cpp.
{
    std::string ret;
    for( const conflict_pair &elem : list ) {
        //~ Single entry in the list of which mods conflict with which mods.
        //~ Please be mindful of spaces.
        //~ "%s [%s]" parts are mod names with internal ids.
        //~ The final result reads as "Mod X [id_x] with Mod Y [id_y]"
        ret += string_format( _( "  %s [%s]\n    with %s [%s]\n" ),
                              elem.what->name(), elem.what,
                              elem.with->name(), elem.with );
    }
    return ret;
}
References _, cata::hash64_detail::ret, and string_format().
Referenced by mod_ui::try_add().