Cataclysm BN: src/mondeath.h File Reference
mondeath.h File Reference
Namespaces
namespace mdeath
Macros
#define CATA_SRC_MONDEATH_H
Functions
void mdeath::normal (monster &z)
void mdeath::splatter (monster &z)
void mdeath::acid (monster &z)
void mdeath::boomer (monster &z)
void mdeath::boomer_glow (monster &z)
void mdeath::kill_vines (monster &z)
void mdeath::vine_cut (monster &z)
void mdeath::triffid_heart (monster &z)
void mdeath::fungus (monster &z)
void mdeath::disintegrate (monster &z)
void mdeath::shriek (monster &z)
void mdeath::howl (monster &z)
void mdeath::rattle (monster &z)
void mdeath::worm (monster &z)
void mdeath::disappear (monster &z)
void mdeath::guilt (monster &z)
void mdeath::brainblob (monster &z)
void mdeath::blobsplit (monster &z)
void mdeath::jackson (monster &z)
void mdeath::melt (monster &z)
void mdeath::amigara (monster &z)
void mdeath::thing (monster &z)
void mdeath::explode (monster &z)
void mdeath::focused_beam (monster &z)
void mdeath::broken (monster &z)
void mdeath::ratking (monster &z)
void mdeath::darkman (monster &z)
void mdeath::gas (monster &z)
void mdeath::kill_breathers (monster &z)
void mdeath::smokeburst (monster &z)
void mdeath::fungalburst (monster &z)
void mdeath::jabberwock (monster &z)
void mdeath::detonate (monster &z)
void mdeath::broken_ammo (monster &z)
void mdeath::preg_roach (monster &z)
void mdeath::fireball (monster &z)
void mdeath::conflagration (monster &z)
void mdeath::gameover (monster &z)
void make_mon_corpse (monster &z, int damageLvl)
Macro Definition Documentation
CATA_SRC_MONDEATH_H
#define CATA_SRC_MONDEATH_H
Definition at line 3 of file mondeath.h.
Function Documentation
make_mon_corpse()
void make_mon_corpse (monster & z, int damageLvl)
Definition at line 912 of file mondeath.cpp.
{
    item corpse = item::make_corpse( z.type->id, calendar::turn, z.unique_name, z.get_upgrade_time() );
    corpse.set_damage( damageLvl );
    if( z.has_effect( effect_pacified ) && z.type->in_species( ZOMBIE ) ) {
        // Pacified corpses have a chance of becoming unpacified when regenerating.
        corpse.set_var( "zlave", one_in( 2 ) ? "zlave" : "mutilated" );
    }
    if( z.has_effect( effect_no_ammo ) ) {
        corpse.set_var( "no_ammo", "no_ammo" );
    }
    if( !z.no_extra_death_drops ) {
        // Pre-gen bionic on death rather than on butcher
        for( const harvest_entry &entry : *z.type->harvest ) {
            if( entry.type == "bionic" || entry.type == "bionic_group" ) {
                std::vector<item> contained_bionics =
                    entry.type == "bionic"
                    ? butcher_cbm_item( itype_id( entry.drop ), calendar::turn, entry.flags, entry.faults )
                    : butcher_cbm_group( item_group_id( entry.drop ), calendar::turn, entry.flags, entry.faults );
                for( const item &it : contained_bionics ) {
                    // Disgusting hack: use components instead of contents to hide stuff
                    corpse.components.push_back( it );
                }
            }
        }
    }
    for( const item &it : z.corpse_components ) {
        corpse.components.push_back( it );
    }
    get_map().add_item_or_charges( z.pos(), corpse );
}
References map::add_item_or_charges(), butcher_cbm_group(), butcher_cbm_item(), corpse, monster::corpse_components, harvest_entry::drop, effect_no_ammo, effect_pacified, harvest_entry::faults, harvest_entry::flags, get_map(), monster::get_upgrade_time(), mtype::harvest, Creature::has_effect(), mtype::id, mtype::in_species(), item::make_corpse(), monster::no_extra_death_drops, one_in(), monster::pos(), calendar::turn, harvest_entry::type, monster::type, monster::unique_name, and ZOMBIE.
Referenced by mdeath::normal().