Cataclysm BN: src/mondeath.cpp File Reference
mondeath.cpp File Reference
#include "mondeath.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "colony.h"
#include "creature.h"
#include "enums.h"
#include "explosion.h"
#include "field_type.h"
#include "fungal_effects.h"
#include "game.h"
#include "harvest.h"
#include "item.h"
#include "item_group.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "kill_tracker.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mattack_actors.h"
#include "mattack_common.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "player.h"
#include "pldata.h"
#include "point.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "timed_event.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
#include "weighted_list.h"
Functions
static void scatter_chunks (const itype_id &chunk_name, int chunk_amt, monster &z, int distance, int pile_size=1)
static std::vector< item > butcher_cbm_item (const itype_id &what, const time_point &birthday, const std::vector< std::string > &flags, const std::vector< fault_id > &faults)
static std::vector< item > butcher_cbm_group (const item_group_id &group, const time_point &birthday, const std::vector< std::string > &flags, const std::vector< fault_id > &faults)
void make_mon_corpse (monster &z, int damageLvl)
Variables
static const efftype_id effect_ai_controlled ("ai_controlled")
static const efftype_id effect_amigara ("amigara")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_darkness ("darkness")
static const efftype_id effect_glowing ("glowing")
static const efftype_id effect_no_ammo ("no_ammo")
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_rat ("rat")
static const itype_id itype_processor ("processor")
static const species_id species_BLOB ("BLOB")
static const species_id ZOMBIE ("ZOMBIE")
static const mtype_id mon_blob ("mon_blob")
static const mtype_id mon_blob_brain ("mon_blob_brain")
static const mtype_id mon_blob_small ("mon_blob_small")
static const mtype_id mon_breather ("mon_breather")
static const mtype_id mon_breather_hub ("mon_breather_hub")
static const mtype_id mon_creeper_hub ("mon_creeper_hub")
static const mtype_id mon_creeper_vine ("mon_creeper_vine")
static const mtype_id mon_giant_cockroach_nymph ("mon_giant_cockroach_nymph")
static const mtype_id mon_halfworm ("mon_halfworm")
static const mtype_id mon_sewer_rat ("mon_sewer_rat")
static const mtype_id mon_thing ("mon_thing")
static const mtype_id mon_zombie_dancer ("mon_zombie_dancer")
static const mtype_id mon_zombie_hulk ("mon_zombie_hulk")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_PACIFIST ("PACIFIST")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
Function Documentation
butcher_cbm_group()
static std::vector< item > butcher_cbm_group (const item_group_id & group, const time_point & birthday, const std::vector< std::string > & flags, const std::vector< fault_id > & faults) static
Definition at line 894 of file mondeath.cpp.
{
    std::vector<item> spawned = item_group::items_from( group, birthday );
    for( item &it : spawned ) {
        for( const std::string &flg : flags ) {
            it.set_flag( flg );
        }
        for( const fault_id &flt : faults ) {
            it.faults.emplace( flt );
        }
    }
    return spawned;
}
References item_group::items_from().
Referenced by make_mon_corpse().
butcher_cbm_item()
static std::vector< item > butcher_cbm_item (const itype_id & what, const time_point & birthday, const std::vector< std::string > & flags, const std::vector< fault_id > & faults) static
Definition at line 879 of file mondeath.cpp.
{
    item something( what, birthday );
    for( const std::string &flg : flags ) {
        something.set_flag( flg );
    }
    for( const fault_id &flt : faults ) {
        something.faults.emplace( flt );
    }
    return {something};
}
References item::faults, and item::set_flag().
Referenced by make_mon_corpse().
make_mon_corpse()
void make_mon_corpse (monster & z, int damageLvl)
Definition at line 910 of file mondeath.cpp.
{
    item corpse = item::make_corpse( z.type->id, calendar::turn, z.unique_name, z.get_upgrade_time() );
    corpse.set_damage( damageLvl );
    if( z.has_effect( effect_pacified ) && z.type->in_species( ZOMBIE ) ) {
        // Pacified corpses have a chance of becoming unpacified when regenerating.
        corpse.set_var( "zlave", one_in( 2 ) ? "zlave" : "mutilated" );
    }
    if( z.has_effect( effect_no_ammo ) ) {
        corpse.set_var( "no_ammo", "no_ammo" );
    }
    if( !z.no_extra_death_drops ) {
        // Pre-gen bionic on death rather than on butcher
        for( const harvest_entry &entry : *z.type->harvest ) {
            if( entry.type == "bionic" || entry.type == "bionic_group" ) {
                std::vector<item> contained_bionics =
                    entry.type == "bionic"
                    ? butcher_cbm_item( itype_id( entry.drop ), calendar::turn, entry.flags, entry.faults )
                    : butcher_cbm_group( item_group_id( entry.drop ), calendar::turn, entry.flags, entry.faults );
                for( const item &it : contained_bionics ) {
                    // Disgusting hack: use components instead of contents to hide stuff
                    corpse.components.push_back( it );
                }
            }
        }
    }
    for( const item &it : z.corpse_components ) {
        corpse.components.push_back( it );
    }
    get_map().add_item_or_charges( z.pos(), corpse );
}
References map::add_item_or_charges(), butcher_cbm_group(), butcher_cbm_item(), corpse, monster::corpse_components, harvest_entry::drop, effect_no_ammo, effect_pacified, harvest_entry::faults, harvest_entry::flags, get_map(), monster::get_upgrade_time(), mtype::harvest, Creature::has_effect(), mtype::id, mtype::in_species(), item::make_corpse(), monster::no_extra_death_drops, one_in(), monster::pos(), calendar::turn, harvest_entry::type, monster::type, monster::unique_name, and ZOMBIE.
Referenced by mdeath::normal().
scatter_chunks()
static void scatter_chunks (const itype_id & chunk_name, int chunk_amt, monster & z, int distance, int pile_size = 1) static
Definition at line 125 of file mondeath.cpp.
{
    // can't have less than one item in a pile or it would cause an infinite loop
    pile_size = std::max( pile_size, 1 );
    // can't have more items in a pile than total items
    pile_size = std::min( chunk_amt, pile_size );
    distance = std::abs( distance );
    map &here = get_map();
    const item chunk( chunk_name, calendar::turn, pile_size );
    for( int i = 0; i < chunk_amt; i += pile_size ) {
        bool drop_chunks = true;
        tripoint tarp( z.pos() + point( rng( -distance, distance ), rng( -distance, distance ) ) );
        const auto traj = line_to( z.pos(), tarp );
        tripoint prev_point = z.pos();
        for( size_t j = 0; j < traj.size(); j++ ) {
            tarp = traj[j];
            bool obstructed = false;
            if( here.obstructed_by_vehicle_rotation( prev_point, tarp ) ) {
                if( one_in( 2 ) ) {
                    tarp.x = prev_point.x;
                } else {
                    tarp.y = prev_point.y;
                }
                obstructed = true;
            }
            if( one_in( 2 ) && z.bloodType() ) {
                here.add_splatter( z.bloodType(), tarp );
            } else if( z.gibType() ) {
                here.add_splatter( z.gibType(), tarp, rng( 1, j + 1 ) );
            }
            if( here.impassable( tarp ) ) {
                here.bash( tarp, distance );
                if( here.impassable( tarp ) ) {
                    // Target is obstacle, not destroyed by bashing,
                    // stop trajectory in front of it, if this is the first
                    // point (e.g. wall adjacent to monster), don't drop anything on it
                    if( j > 0 ) {
                        tarp = traj[j - 1];
                    } else {
                        drop_chunks = false;
                    }
                    break;
                }
            }
            //Don't lower j until after it's used in bashing
            if( obstructed ) {
                j--;
            }
            prev_point = tarp;
        }
        if( drop_chunks ) {
            here.add_item_or_charges( tarp, chunk );
        }
    }
}
References map::add_item_or_charges(), map::add_splatter(), map::bash(), monster::bloodType(), get_map(), monster::gibType(), map::impassable(), line_to(), map::obstructed_by_vehicle_rotation(), one_in(), monster::pos(), rng(), calendar::turn, tripoint::x, and tripoint::y.
Referenced by mdeath::splatter().
Variable Documentation
effect_ai_controlled
const efftype_id effect_ai_controlled("ai_controlled") ("ai_controlled") static
Referenced by mdeath::brainblob(), and mdeath::jackson().
effect_amigara
const efftype_id effect_amigara("amigara") ("amigara") static
Referenced by mdeath::amigara().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by mdeath::boomer(), and mdeath::boomer_glow().
effect_darkness
const efftype_id effect_darkness("darkness") ("darkness") static
Referenced by mdeath::darkman().
effect_glowing
const efftype_id effect_glowing("glowing") ("glowing") static
Referenced by mdeath::boomer_glow().
effect_no_ammo
const efftype_id effect_no_ammo("no_ammo") ("no_ammo") static
Referenced by mdeath::detonate(), make_mon_corpse(), and mdeath::splatter().
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by make_mon_corpse().
effect_rat
const efftype_id effect_rat("rat") ("rat") static
Referenced by mdeath::ratking().
itype_processor
const itype_id itype_processor("processor") ("processor") static
Referenced by mdeath::focused_beam().
mon_blob
const mtype_id mon_blob("mon_blob") ("mon_blob") static
Referenced by mdeath::blobsplit().
mon_blob_brain
const mtype_id mon_blob_brain("mon_blob_brain") ("mon_blob_brain") static
Referenced by mdeath::brainblob().
mon_blob_small
const mtype_id mon_blob_small("mon_blob_small") ("mon_blob_small") static
Referenced by mdeath::blobsplit().
mon_breather
const mtype_id mon_breather("mon_breather") ("mon_breather") static
Referenced by mdeath::kill_breathers().
mon_breather_hub
const mtype_id mon_breather_hub("mon_breather_hub") ("mon_breather_hub") static
Referenced by mdeath::kill_breathers().
mon_creeper_hub
const mtype_id mon_creeper_hub("mon_creeper_hub") ("mon_creeper_hub") static
Referenced by mdeath::kill_vines(), and mdeath::vine_cut().
mon_creeper_vine
const mtype_id mon_creeper_vine("mon_creeper_vine") ("mon_creeper_vine") static
Referenced by mdeath::kill_vines(), and mdeath::vine_cut().
mon_giant_cockroach_nymph
const mtype_id mon_giant_cockroach_nymph("mon_giant_cockroach_nymph") ("mon_giant_cockroach_nymph") static
Referenced by mdeath::preg_roach().
mon_halfworm
const mtype_id mon_halfworm("mon_halfworm") ("mon_halfworm") static
Referenced by mdeath::worm().
mon_sewer_rat
const mtype_id mon_sewer_rat("mon_sewer_rat") ("mon_sewer_rat") static
Referenced by mdeath::ratking().
mon_thing
const mtype_id mon_thing("mon_thing") ("mon_thing") static
Referenced by mdeath::thing().
mon_zombie_dancer
const mtype_id mon_zombie_dancer("mon_zombie_dancer") ("mon_zombie_dancer") static
Referenced by mdeath::jackson().
mon_zombie_hulk
const mtype_id mon_zombie_hulk("mon_zombie_hulk") ("mon_zombie_hulk") static
Referenced by mdeath::jackson().
species_BLOB
const species_id species_BLOB("BLOB") ("BLOB") static
Referenced by mdeath::brainblob().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by mdeath::guilt().
trait_PACIFIST
const trait_id trait_PACIFIST("PACIFIST") ("PACIFIST") static
Referenced by mdeath::guilt().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by mdeath::guilt().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by mdeath::guilt(), make_mon_corpse(), and mdeath::normal().