Cataclysm BN: src/monexamine.cpp File Reference
monexamine.cpp File Reference
#include "monexamine.h"
#include <climits>
#include <map>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "game_inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "map.h"
#include "material.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "output.h"
#include "player_activity.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
Functions
static item_location pet_armor_loc (monster &z)
static item_location tack_loc ()
static int prompt_for_amount (const char *const msg, const int max)
Variables
static const quality_id qual_shear ("SHEAR")
static const efftype_id effect_sheared ("sheared")
static const activity_id ACT_MILK ("ACT_MILK")
static const activity_id ACT_PLAY_WITH_PET ("ACT_PLAY_WITH_PET")
static const efftype_id effect_ai_waiting ("ai_waiting")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_has_bag ("has_bag")
static const efftype_id effect_monster_armor ("monster_armor")
static const efftype_id effect_paid ("paid")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_saddled ("monster_saddled")
static const efftype_id effect_leashed ("leashed")
static const efftype_id effect_led_by_leash ("led_by_leash")
static const efftype_id effect_tied ("tied")
static const itype_id itype_cash_card ("cash_card")
static const itype_id itype_id_military ("id_military")
static const skill_id skill_survival ("survival")
static const species_id ZOMBIE ("ZOMBIE")
Function Documentation
pet_armor_loc()
static item_location pet_armor_loc (monster & z) static
Definition at line 366 of file monexamine.cpp.
{
    auto filter = [z]( const item & it ) {
        return z.type->bodytype == it.get_pet_armor_bodytype() &&
               z.get_volume() >= it.get_pet_armor_min_vol() &&
               z.get_volume() <= it.get_pet_armor_max_vol();
    };
    return game_menus::inv::titled_filter_menu( filter, get_avatar(), _( "Pet armor" ) );
}
References _, mtype::bodytype, get_avatar(), monster::get_volume(), game_menus::inv::titled_filter_menu(), and monster::type.
Referenced by monexamine::add_armor().
prompt_for_amount()
static int prompt_for_amount (const char *const msg, const int max) static
Definition at line 448 of file monexamine.cpp.
{
    const std::string formatted = string_format( msg, max );
    const int amount = string_input_popup()
                       .title( formatted )
                       .width( 20 )
                       .text( std::to_string( max ) )
                       .only_digits( true )
                       .query_int();
    return clamp( amount, 0, max );
}
References clamp(), string_input_popup::only_digits(), string_input_popup::query_int(), string_format(), string_input_popup::text(), string_input_popup::title(), to_string(), and string_input_popup::width().
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), and monexamine::pay_bot().
tack_loc()
static item_location tack_loc () static
Definition at line 377 of file monexamine.cpp.
{
    auto filter = []( const item & it ) {
        return it.has_flag( "TACK" );
    };
    return game_menus::inv::titled_filter_menu( filter, get_avatar(), _( "Tack" ) );
}
References _, get_avatar(), and game_menus::inv::titled_filter_menu().
Referenced by monexamine::attach_or_remove_saddle().
Variable Documentation
ACT_MILK
const activity_id ACT_MILK("ACT_MILK") ("ACT_MILK") static
Referenced by monexamine::milk_source().
ACT_PLAY_WITH_PET
const activity_id ACT_PLAY_WITH_PET("ACT_PLAY_WITH_PET") ("ACT_PLAY_WITH_PET") static
Referenced by monexamine::play_with().
effect_ai_waiting
const efftype_id effect_ai_waiting("ai_waiting") ("ai_waiting") static
Referenced by Character::can_mount(), and monexamine::give_items_to().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by monexamine::pet_menu(), and monexamine::remove_harness().
effect_has_bag
const efftype_id effect_has_bag("has_bag") ("has_bag") static
Referenced by monexamine::attach_bag_to(), monexamine::deactivate_pet(), monexamine::pet_menu(), and monexamine::remove_bag_from().
effect_leashed
const efftype_id effect_leashed("leashed") ("leashed") static
Referenced by monexamine::add_leash(), monexamine::deactivate_pet(), monexamine::pet_menu(), monexamine::remove_leash(), and monexamine::untie_pet().
effect_led_by_leash
const efftype_id effect_led_by_leash("led_by_leash") ("led_by_leash") static
Referenced by monexamine::pet_menu(), monexamine::remove_leash(), monexamine::start_leading(), and monexamine::stop_leading().
effect_monster_armor
const efftype_id effect_monster_armor("monster_armor") ("monster_armor") static
Referenced by monexamine::add_armor(), monexamine::deactivate_pet(), monexamine::pet_menu(), and monexamine::remove_armor().
effect_paid
const efftype_id effect_paid("paid") ("paid") static
Referenced by monexamine::pay_bot().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by monexamine::mech_hack(), and monexamine::pay_bot().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by Character::can_mount().
effect_saddled
const efftype_id effect_saddled("monster_saddled") ("monster_saddled") static
Referenced by monexamine::attach_or_remove_saddle(), Character::can_mount(), monexamine::deactivate_pet(), and monexamine::pet_menu().
effect_sheared
const efftype_id effect_sheared("sheared") ("sheared") static
Referenced by monexamine::pet_menu().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by monexamine::deactivate_pet(), monexamine::milk_source(), monexamine::pet_menu(), monexamine::shear_animal(), monexamine::start_leading(), monexamine::swap(), monexamine::tie_pet(), and monexamine::untie_pet().
itype_cash_card
const itype_id itype_cash_card("cash_card") ("cash_card") static
Referenced by monexamine::pay_bot().
itype_id_military
const itype_id itype_id_military("id_military") ("id_military") static
Referenced by monexamine::mech_hack().
qual_shear
const quality_id qual_shear("SHEAR") ("SHEAR") static
Referenced by monexamine::pet_menu(), and monexamine::shear_animal().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by Character::can_mount(), and monexamine::pet_menu().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by monexamine::pet_menu().