Cataclysm BN: src/monfaction.cpp File Reference
monfaction.cpp File Reference
#include "monfaction.h"
#include <cstddef>
#include <map>
#include <queue>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "debug.h"
#include "int_id.h"
#include "json.h"
#include "string_id.h"
Functions
void add_to_attitude_map (const std::set< std::string > &keys, mfaction_att_map &map, mf_attitude value)
void apply_base_faction (const monfaction &base, monfaction &faction)
static void apply_base_faction (mfaction_id base, mfaction_id faction_id)
static void prealloc (const std::set< std::string > &facs)
Variables
std::unordered_map< mfaction_str_id, mfaction_id > faction_map
std::vector< monfaction > faction_list
Function Documentation
add_to_attitude_map()
void add_to_attitude_map (const std::set< std::string > & keys, mfaction_att_map & map, mf_attitude value)
Definition at line 223 of file monfaction.cpp.
{
    for( const auto &k : keys ) {
        const auto &faction = mfaction_str_id( k ).id();
        map[faction] = value;
    }
}
References string_id< T >::id().
Referenced by monfactions::load_monster_faction().
apply_base_faction() [1/2]
void apply_base_faction (const monfaction & base, monfaction & faction)
Referenced by monfactions::finalize().
apply_base_faction() [2/2]
static void apply_base_faction (mfaction_id base, mfaction_id faction_id) static
Definition at line 95 of file monfaction.cpp.
{
    for( const auto &pair : base.obj().attitude_map ) {
        // Fill in values set in base faction, but not in derived one
        auto &faction = faction_list[faction_id.to_i()];
        if( faction.attitude_map.count( pair.first ) == 0 ) {
            faction.attitude_map.insert( pair );
        }
    }
}
References monfaction::attitude_map, faction_list, and int_id< T >::obj().
prealloc()
static void prealloc (const std::set< std::string > & facs) static
Definition at line 215 of file monfaction.cpp.
{
    for( const auto &f : facs ) {
        monfactions::get_or_add_faction( mfaction_str_id( f ) );
    }
}
References monfactions::get_or_add_faction().
Referenced by monfactions::load_monster_faction().
Variable Documentation
faction_list
std::vector< monfaction > faction_list
Definition at line 17 of file monfaction.cpp.
Referenced by apply_base_faction(), monfactions::finalize(), monfactions::get_or_add_faction(), monfactions::load_monster_faction(), int_id< T >::obj(), and monfactions::reset().
faction_map
std::unordered_map< mfaction_str_id, mfaction_id > faction_map
Definition at line 16 of file monfaction.cpp.
Referenced by monfactions::get_or_add_faction(), string_id< T >::id(), and monfactions::reset().