Cataclysm BN: src/monmove.cpp File Reference
monmove.cpp File Reference
#include "monster.h"
#include <algorithm>
#include <cfloat>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <list>
#include <memory>
#include <ostream>
#include <unordered_map>
#include "avatar.h"
#include "behavior.h"
#include "bionics.h"
#include "cata_utility.h"
#include "creature_tracker.h"
#include "debug.h"
#include "effect.h"
#include "field.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "messages.h"
#include "monfaction.h"
#include "monster_oracle.h"
#include "mtype.h"
#include "npc.h"
#include "pathfinding.h"
#include "pimpl.h"
#include "player.h"
#include "rng.h"
#include "scent_map.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "tileray.h"
#include "translations.h"
#include "trap.h"
#include "vehicle.h"
#include "vpart_position.h"
Macros
#define MONSTER_FOLLOW_DIST 8
Functions
static const std::string flag_AUTODOC_COUCH ("AUTODOC_COUCH")
static const std::string flag_LIQUID ("LIQUID")
static bool z_is_valid (int z)
static float get_stagger_adjust (const tripoint &source, const tripoint &destination, const tripoint &next_step)
Method to make monster movement speed consistent in the face of staggering behavior and differing distance metrics.
static std::vector< tripoint > get_bashing_zone (const tripoint &bashee, const tripoint &basher, int maxdepth)
static tripoint find_closest_stair (const tripoint &near_this, const ter_bitflags stair_type)
Variables
static const efftype_id effect_ai_waiting ("ai_waiting")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_countdown ("countdown")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_dragging ("dragging")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_operating ("operating")
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_pushed ("pushed")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_led_by_leash ("led_by_leash")
static const itype_id itype_pressurized_tank ("pressurized_tank")
static const species_id FUNGUS ("FUNGUS")
static const species_id INSECT ("INSECT")
static const species_id SPIDER ("SPIDER")
static const species_id ZOMBIE ("ZOMBIE")
Macro Definition Documentation
MONSTER_FOLLOW_DIST
#define MONSTER_FOLLOW_DIST 8
Definition at line 76 of file monmove.cpp.
Function Documentation
find_closest_stair()
static tripoint find_closest_stair (const tripoint & near_this, const ter_bitflags stair_type) static
Definition at line 1505 of file monmove.cpp.
{
    map &here = get_map();
    for( const tripoint &candidate : closest_points_first( near_this, 10 ) ) {
        if( here.has_flag( stair_type, candidate ) ) {
            return candidate;
        }
    }
    // we didn't find it
    return near_this;
}
References closest_points_first(), get_map(), and map::has_flag().
Referenced by monster::move_to().
flag_AUTODOC_COUCH()
static const std::string flag_AUTODOC_COUCH ("AUTODOC_COUCH") static
Referenced by monster::nursebot_operate(), and monster::plan().
flag_LIQUID()
static const std::string flag_LIQUID ("LIQUID") static
Referenced by monster::is_aquatic_danger().
get_bashing_zone()
static std::vector< tripoint > get_bashing_zone (const tripoint & bashee, const tripoint & basher, int maxdepth) static
Definition at line 1325 of file monmove.cpp.
{
    std::vector<tripoint> direction;
    direction.push_back( bashee );
    direction.push_back( basher );
    // Draw a line from the target through the attacker.
    std::vector<tripoint> path = continue_line( direction, maxdepth );
    // Remove the target.
    path.insert( path.begin(), basher );
    std::vector<tripoint> zone;
    // Go ahead and reserve enough room for all the points since
    // we know how many it will be.
    zone.reserve( 3 * maxdepth );
    tripoint previous = bashee;
    for( const tripoint &p : path ) {
        std::vector<point> swath = squares_in_direction( previous.xy(), p.xy() );
        for( const point &q : swath ) {
            zone.push_back( tripoint( q, bashee.z ) );
        }
        previous = p;
    }
    return zone;
}
References continue_line(), squares_in_direction(), tripoint::xy(), and tripoint::z.
Referenced by monster::group_bash_skill().
get_stagger_adjust()
static float get_stagger_adjust (const tripoint & source, const tripoint & destination, const tripoint & next_step) static
Method to make monster movement speed consistent in the face of staggering behavior and differing distance metrics.
It works by scaling the cost to take a step by how much that step reduces the distance to your goal. Since it incorporates the current distance metric, it also scales for diagonal vs orthogonal movement.
Definition at line 608 of file monmove.cpp.
{
    // TODO: push this down into rl_dist
    const float initial_dist =
        trigdist ? trig_dist( source, destination ) : rl_dist( source, destination );
    const float new_dist =
        trigdist ? trig_dist( next_step, destination ) : rl_dist( next_step, destination );
    // If we return 0, it wil cancel the action.
    return std::max( 0.01f, initial_dist - new_dist );
}
References rl_dist(), trig_dist(), and trigdist.
Referenced by monster::move().
z_is_valid()
static bool z_is_valid (int z) static
Definition at line 114 of file monmove.cpp.
{
    return z >= -OVERMAP_DEPTH && z <= OVERMAP_HEIGHT;
}
References OVERMAP_DEPTH, and OVERMAP_HEIGHT.
Referenced by monster::can_reach_to().
Variable Documentation
effect_ai_waiting
const efftype_id effect_ai_waiting("ai_waiting") ("ai_waiting") static
Referenced by monster::move(), and monster::plan().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by monster::move_to().
effect_countdown
const efftype_id effect_countdown("countdown") ("countdown") static
Referenced by monster::nursebot_operate().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by monster::plan().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by monster::push_to().
effect_dragging
const efftype_id effect_dragging("dragging") ("dragging") static
Referenced by monster::find_dragged_foe(), monster::move(), monster::nursebot_operate(), and monster::plan().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by monster::move(), and monster::nursebot_operate().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by monster::move().
effect_led_by_leash
const efftype_id effect_led_by_leash("led_by_leash") ("led_by_leash") static
Referenced by monster::move(), and monster::plan().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by monster::move_to().
effect_operating
const efftype_id effect_operating("operating") ("operating") static
Referenced by monster::nursebot_operate(), and monster::plan().
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by monster::move().
effect_pushed
const efftype_id effect_pushed("pushed") ("pushed") static
Referenced by monster::push_to().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by monster::knock_back_to(), monster::move(), and monster::push_to().
FUNGUS
const species_id FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by monster::is_immune_field().
INSECT
const species_id INSECT("INSECT") ("INSECT") static
Referenced by monster::is_immune_field().
itype_pressurized_tank
const itype_id itype_pressurized_tank("pressurized_tank") ("pressurized_tank") static
Referenced by monster::move_to().
SPIDER
const species_id SPIDER("SPIDER") ("SPIDER") static
Referenced by monster::is_immune_field().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by monster::plan().