Cataclysm BN: src/monster.cpp File Reference
monster.cpp File Reference
#include "monster.h"
#include <algorithm>
#include <limits>
#include <memory>
#include <tuple>
#include <unordered_map>
#include "avatar.h"
#include "character.h"
#include "coordinate_conversions.h"
#include "cursesdef.h"
#include "debug.h"
#include "effect.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field_type.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "melee.h"
#include "messages.h"
#include "mission.h"
#include "mod_manager.h"
#include "mondeath.h"
#include "mondefense.h"
#include "monfaction.h"
#include "mongroup.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player.h"
#include "projectile.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_utils.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "weather.h"
Macros
#define UPGRADE_MAX_ITERS 5
Functions
static std::vector< player * > find_targets_to_ungrab (const tripoint &pos)
static std::pair< std::string, nc_color > hp_description (int cur_hp, int max_hp)
static std::pair< std::string, nc_color > speed_description (float mon_speed_rating, bool immobile=false)
static void process_item_valptr (cata::value_ptr< item > &ptr, monster &mon)
Variables
static const ammo_effect_str_id ammo_effect_WHIP ("WHIP")
static const efftype_id effect_badpoison ("badpoison")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_emp ("emp")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_grabbing ("grabbing")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_monster_armor ("monster_armor")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_paralyzepoison ("paralyzepoison")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_run ("run")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_supercharged ("supercharged")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_webbed ("webbed")
static const itype_id itype_corpse ("corpse")
static const itype_id itype_milk ("milk")
static const itype_id itype_milk_raw ("milk_raw")
static const species_id FISH ("FISH")
static const species_id FUNGUS ("FUNGUS")
static const species_id INSECT ("INSECT")
static const species_id MAMMAL ("MAMMAL")
static const species_id MOLLUSK ("MOLLUSK")
static const species_id ROBOT ("ROBOT")
static const species_id ZOMBIE ("ZOMBIE")
static const trait_id trait_ANIMALDISCORD ("ANIMALDISCORD")
static const trait_id trait_ANIMALDISCORD2 ("ANIMALDISCORD2")
static const trait_id trait_ANIMALEMPATH ("ANIMALEMPATH")
static const trait_id trait_ANIMALEMPATH2 ("ANIMALEMPATH2")
static const trait_id trait_BEE ("BEE")
static const trait_id trait_FLOWERS ("FLOWERS")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_MYCUS_FRIEND ("MYCUS_FRIEND")
static const trait_id trait_PACIFIST ("PACIFIST")
static const trait_id trait_PHEROMONE_INSECT ("PHEROMONE_INSECT")
static const trait_id trait_PHEROMONE_MAMMAL ("PHEROMONE_MAMMAL")
static const trait_id trait_TERRIFYING ("TERRIFYING")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const std::map< m_size, translation > size_names
static const std::map< monster_attitude, std::pair< std::string, color_id > > attitude_names
Macro Definition Documentation
UPGRADE_MAX_ITERS
#define UPGRADE_MAX_ITERS 5
Definition at line 122 of file monster.cpp.
Function Documentation
find_targets_to_ungrab()
static std::vector< player * > find_targets_to_ungrab (const tripoint & pos) static
Definition at line 144 of file monster.cpp.
{
    std::vector<player *> result;
    for( auto &player_pos : g->m.points_in_radius( pos, 1, 0 ) ) {
        player *p = g->critter_at<player>( player_pos );
        if( !p || !p->has_effect( effect_grabbed ) ) {
            continue;
        }
        bool grabbed = false;
        for( auto &mon_pos : g->m.points_in_radius( player_pos, 1, 0 ) ) {
            const monster *const mon = g->critter_at<monster>( mon_pos );
            if( mon && mon->has_effect( effect_grabbing ) ) {
                grabbed = true;
                break;
            }
        }
        if( !grabbed ) {
            result.push_back( p );
        }
    }
    return result;
}
References effect_grabbed, effect_grabbing, g, and Creature::has_effect().
Referenced by monster::die(), and monster::on_damage_of_type().
hp_description()
static std::pair< std::string, nc_color > hp_description (int cur_hp, int max_hp) static
Definition at line 565 of file monster.cpp.
{
    std::string damage_info;
    nc_color col;
    if( cur_hp >= max_hp ) {
        damage_info = _( "It is uninjured." );
        col = c_green;
    } else if( cur_hp >= max_hp * 0.8 ) {
        damage_info = _( "It is lightly injured." );
        col = c_light_green;
    } else if( cur_hp >= max_hp * 0.6 ) {
        damage_info = _( "It is moderately injured." );
        col = c_yellow;
    } else if( cur_hp >= max_hp * 0.3 ) {
        damage_info = _( "It is heavily injured." );
        col = c_yellow;
    } else if( cur_hp >= max_hp * 0.1 ) {
        damage_info = _( "It is severely injured." );
        col = c_light_red;
    } else {
        damage_info = _( "It is nearly dead!" );
        col = c_red;
    }
    // show exact monster HP if in debug mode
    if( debug_mode ) {
        damage_info += " ";
        damage_info += string_format( _( "%1$d/%2$d HP" ), cur_hp, max_hp );
    }
    return std::make_pair( damage_info, col );
}
References _, c_green, c_light_green, c_light_red, c_red, c_yellow, debug_mode, and string_format().
Referenced by monster::extended_description(), and monster::print_info().
process_item_valptr()
static void process_item_valptr (cata::value_ptr< item > & ptr, monster & mon) static
Definition at line 2423 of file monster.cpp.
{
    if( ptr && ptr->needs_processing() && ptr->process( nullptr, mon.pos(), false ) ) {
        ptr.reset();
    }
}
References monster::pos(), and ptr().
Referenced by monster::process_items().
speed_description()
static std::pair< std::string, nc_color > speed_description (float mon_speed_rating, bool immobile = false) static
Definition at line 598 of file monster.cpp.
{
    if( immobile ) {
        return std::make_pair( _( "It is immobile." ), c_green );
    }
    const std::array<std::tuple<float, nc_color, std::string>, 8> cases = {{
            std::make_tuple( 1.40f, c_red, _( "It looks much faster than you." ) ),
            std::make_tuple( 1.15f, c_light_red, _( "It looks faster than you." ) ),
            std::make_tuple( 1.05f, c_yellow, _( "It looks slightly faster than you." ) ),
            std::make_tuple( 0.90f, c_white, _( "It looks about as fast as you." ) ),
            std::make_tuple( 0.80f, c_light_cyan, _( "It looks slightly slower than you." ) ),
            std::make_tuple( 0.60f, c_cyan, _( "It looks slower than you." ) ),
            std::make_tuple( 0.30f, c_light_green, _( "It looks much slower than you." ) ),
            std::make_tuple( 0.00f, c_green, _( "It seems to be barely moving." ) )
        }
    };
    const avatar &ply = get_avatar();
    float player_runcost = ply.run_cost( 100 );
    if( player_runcost == 0 ) {
        player_runcost = 1.0f;
    }
    // determine tiles per turn (tpt)
    const float player_tpt = ply.get_speed() / player_runcost;
    const float ratio = player_tpt == 0 ?
                        2.00f : mon_speed_rating / player_tpt;
    for( const std::tuple<float, nc_color, std::string> &speed_case : cases ) {
        if( ratio >= std::get<0>( speed_case ) ) {
            return std::make_pair( std::get<2>( speed_case ), std::get<1>( speed_case ) );
        }
    }
    debugmsg( "speed_description: no ratio value matched" );
    return std::make_pair( _( "Unknown" ), c_white );
}
References _, c_cyan, c_green, c_light_cyan, c_light_green, c_light_red, c_red, c_white, c_yellow, debugmsg, get_avatar(), Character::get_speed(), and Character::run_cost().
Referenced by monster::extended_description(), and monster::print_info().
Variable Documentation
ammo_effect_WHIP
const ammo_effect_str_id ammo_effect_WHIP("WHIP") ("WHIP") static
Referenced by monster::deal_projectile_attack().
attitude_names
const std::map<monster_attitude, std::pair<std::string, color_id> > attitude_names static
Initial value:
{
    {monster_attitude::MATT_FRIEND, {translate_marker( "Friendly." ), def_h_white}},
    {monster_attitude::MATT_FPASSIVE, {translate_marker( "Passive." ), def_h_white}},
    {monster_attitude::MATT_FLEE, {translate_marker( "Fleeing!" ), def_c_green}},
    {monster_attitude::MATT_FOLLOW, {translate_marker( "Tracking." ), def_c_yellow}},
    {monster_attitude::MATT_IGNORE, {translate_marker( "Ignoring." ), def_c_light_gray}},
    {monster_attitude::MATT_ZLAVE, {translate_marker( "Zombie slave." ), def_c_green}},
    {monster_attitude::MATT_ATTACK, {translate_marker( "Hostile!" ), def_c_red}},
    {monster_attitude::MATT_NULL, {translate_marker( "BUG: Behavior unnamed." ), def_h_red}},
}
Definition at line 132 of file monster.cpp.
Referenced by monster::get_attitude().
effect_badpoison
const efftype_id effect_badpoison("badpoison") ("badpoison") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by monster::color_with_effects(), monster::die(), monster::get_dodge(), and monster::move_effects().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by monster::process_one_effect(), and monster::process_turn().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by monster::get_dodge(), and monster::hit_roll().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by monster::move_effects().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by monster::can_hear().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by monster::attitude().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by monster::can_act(), monster::color_with_effects(), monster::get_dodge(), monster::impact(), and monster::move_effects().
effect_emp
const efftype_id effect_emp("emp") ("emp") static
Referenced by monster::process_turn().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by monster::die(), find_targets_to_ungrab(), monster::move_effects(), monster::on_damage_of_type(), and monster::process_turn().
effect_grabbing
const efftype_id effect_grabbing("grabbing") ("grabbing") static
Referenced by monster::die(), find_targets_to_ungrab(), monster::on_damage_of_type(), and monster::process_turn().
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
Referenced by monster::color_with_effects(), monster::die(), monster::get_dodge(), and monster::move_effects().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by monster::melee_attack().
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
Referenced by monster::move_effects().
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
Referenced by monster::color_with_effects(), monster::die(), monster::get_dodge(), and monster::move_effects().
effect_monster_armor
const efftype_id effect_monster_armor("monster_armor") ("monster_armor") static
Referenced by monster::get_worn_armor_val(), and monster::name_with_armor().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by monster::process_one_effect().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by monster::color_with_effects(), monster::is_immune_effect(), and monster::process_one_effect().
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by monster::attitude(), and monster::color_with_effects().
effect_paralyzepoison
const efftype_id effect_paralyzepoison("paralyzepoison") ("paralyzepoison") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by monster::die(), monster::melee_attack(), monster::print_info(), and monster::setpos().
effect_run
const efftype_id effect_run("run") ("run") static
Referenced by monster::deal_projectile_attack(), monster::melee_attack(), and monster::process_one_effect().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by monster::can_act(), monster::color_with_effects(), monster::is_immune_effect(), and monster::stability_roll().
effect_supercharged
const efftype_id effect_supercharged("supercharged") ("supercharged") static
Referenced by monster::process_turn().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by monster::color_with_effects(), monster::get_dodge(), and monster::move_effects().
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
Referenced by monster::can_act(), and monster::move_effects().
FISH
const species_id FISH("FISH") ("FISH") static
Referenced by monster::move_effects().
FUNGUS
const species_id FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by monster::attitude(), and monster::make_fungus().
INSECT
const species_id INSECT("INSECT") ("INSECT") static
Referenced by monster::attitude(), and monster::name_with_armor().
itype_corpse
const itype_id itype_corpse("corpse") ("corpse") static
Referenced by monster::init_from_item().
itype_milk
const itype_id itype_milk("milk") ("milk") static
Referenced by monster::refill_udders().
itype_milk_raw
const itype_id itype_milk_raw("milk_raw") ("milk_raw") static
Referenced by monster::refill_udders().
MAMMAL
const species_id MAMMAL("MAMMAL") ("MAMMAL") static
Referenced by monster::attitude().
MOLLUSK
const species_id MOLLUSK("MOLLUSK") ("MOLLUSK") static
Referenced by monster::move_effects().
ROBOT
const species_id ROBOT("ROBOT") ("ROBOT") static
Referenced by monster::move_effects().
size_names
const std::map<m_size, translation> size_names static
Initial value:
{
    { m_size::MS_TINY, to_translation( "size adj", "tiny" ) },
    { m_size::MS_SMALL, to_translation( "size adj", "small" ) },
    { m_size::MS_MEDIUM, to_translation( "size adj", "medium" ) },
    { m_size::MS_LARGE, to_translation( "size adj", "large" ) },
    { m_size::MS_HUGE, to_translation( "size adj", "huge" ) },
}
Definition at line 124 of file monster.cpp.
Referenced by monster::extended_description().
trait_ANIMALDISCORD
const trait_id trait_ANIMALDISCORD("ANIMALDISCORD") ("ANIMALDISCORD") static
Referenced by monster::attitude().
trait_ANIMALDISCORD2
const trait_id trait_ANIMALDISCORD2("ANIMALDISCORD2") ("ANIMALDISCORD2") static
Referenced by monster::attitude().
trait_ANIMALEMPATH
const trait_id trait_ANIMALEMPATH("ANIMALEMPATH") ("ANIMALEMPATH") static
Referenced by monster::attitude().
trait_ANIMALEMPATH2
const trait_id trait_ANIMALEMPATH2("ANIMALEMPATH2") ("ANIMALEMPATH2") static
Referenced by monster::attitude().
trait_BEE
const trait_id trait_BEE("BEE") ("BEE") static
Referenced by monster::attitude().
trait_FLOWERS
const trait_id trait_FLOWERS("FLOWERS") ("FLOWERS") static
Referenced by monster::attitude().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by monster::die().
trait_MYCUS_FRIEND
const trait_id trait_MYCUS_FRIEND("MYCUS_FRIEND") ("MYCUS_FRIEND") static
Referenced by monster::attitude().
trait_PACIFIST
const trait_id trait_PACIFIST("PACIFIST") ("PACIFIST") static
Referenced by monster::die().
trait_PHEROMONE_INSECT
const trait_id trait_PHEROMONE_INSECT("PHEROMONE_INSECT") ("PHEROMONE_INSECT") static
Referenced by monster::attitude().
trait_PHEROMONE_MAMMAL
const trait_id trait_PHEROMONE_MAMMAL("PHEROMONE_MAMMAL") ("PHEROMONE_MAMMAL") static
Referenced by monster::attitude().
trait_TERRIFYING
const trait_id trait_TERRIFYING("TERRIFYING") ("TERRIFYING") static
Referenced by monster::attitude().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by monster::attitude().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by monster::attitude().