Cataclysm BN: src/morale.cpp File Reference
morale.cpp File Reference
#include "morale.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <numeric>
#include <set>
#include <utility>
#include "bodypart.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "effect.h"
#include "enum_conversions.h"
#include "enums.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "morale_types.h"
#include "options.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui_manager.h"
#include "itype.h"
Classes
struct morale_mult
Namespaces
namespace io
namespace morale_mults
Functions
template<>
std::string io::enum_to_string< morale_subtype_t > (morale_subtype_t data)
double operator* (double morale, const morale_mult &mult)
double operator* (const morale_mult &mult, double morale)
double operator*= (double &morale, const morale_mult &mult)
int operator*= (int &morale, const morale_mult &mult)
Variables
static const efftype_id effect_cold ("cold")
static const efftype_id effect_hot ("hot")
static const efftype_id effect_took_prozac ("took_prozac")
static const efftype_id effect_took_prozac_bad ("took_prozac_bad")
static const trait_id trait_BADTEMPER ("BADTEMPER")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_FLOWERS ("FLOWERS")
static const trait_id trait_LEAVES2 ("LEAVES2")
static const trait_id trait_LEAVES3 ("LEAVES3")
static const trait_id trait_MASOCHIST ("MASOCHIST")
static const trait_id trait_MASOCHIST_MED ("MASOCHIST_MED")
static const trait_id trait_OPTIMISTIC ("OPTIMISTIC")
static const trait_id trait_ROOTS1 ("ROOTS1")
static const trait_id trait_ROOTS2 ("ROOTS2")
static const trait_id trait_ROOTS3 ("ROOTS3")
static const trait_id trait_STYLISH ("STYLISH")
static const morale_mult morale_mults::optimist (1.2, 0.8)
static const morale_mult morale_mults::badtemper (0.8, 1.2)
static const morale_mult morale_mults::prozac (1.0, 0.25)
static const morale_mult morale_mults::prozac_bad (0.25, 1.0)
Function Documentation
operator*() [1/2]
double operator* (const morale_mult & mult, double morale) inline
Definition at line 97 of file morale.cpp.
{
    return morale * mult;
}
References spell_effect::morale().
operator*() [2/2]
double operator* (double morale, const morale_mult & mult) inline
Definition at line 92 of file morale.cpp.
{
    return morale * ( ( morale >= 0.0 ) ? mult.good : mult.bad );
}
References morale_mult::bad, morale_mult::good, and spell_effect::morale().
operator*=() [1/2]
double operator*= (double & morale, const morale_mult & mult) inline
Definition at line 102 of file morale.cpp.
{
    morale = morale * mult;
    return morale;
}
References spell_effect::morale().
operator*=() [2/2]
int operator*= (int & morale, const morale_mult & mult) inline
Definition at line 108 of file morale.cpp.
{
    morale = morale * mult;
    return morale;
}
References spell_effect::morale().
Variable Documentation
effect_cold
const efftype_id effect_cold("cold") ("cold") static
Referenced by player_morale::on_effect_int_change().
effect_hot
const efftype_id effect_hot("hot") ("hot") static
Referenced by player_morale::on_effect_int_change().
effect_took_prozac
const efftype_id effect_took_prozac("took_prozac") ("took_prozac") static
Referenced by player_morale::on_effect_int_change().
effect_took_prozac_bad
const efftype_id effect_took_prozac_bad("took_prozac_bad") ("took_prozac_bad") static
Referenced by player_morale::on_effect_int_change().
trait_BADTEMPER
const trait_id trait_BADTEMPER("BADTEMPER") ("BADTEMPER") static
Referenced by player_morale::player_morale().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by player_morale::player_morale(), and player_morale::update_masochist_bonus().
trait_FLOWERS
const trait_id trait_FLOWERS("FLOWERS") ("FLOWERS") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_LEAVES2
const trait_id trait_LEAVES2("LEAVES2") ("LEAVES2") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_LEAVES3
const trait_id trait_LEAVES3("LEAVES3") ("LEAVES3") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_MASOCHIST
const trait_id trait_MASOCHIST("MASOCHIST") ("MASOCHIST") static
Referenced by player_morale::player_morale(), and player_morale::update_masochist_bonus().
trait_MASOCHIST_MED
const trait_id trait_MASOCHIST_MED("MASOCHIST_MED") ("MASOCHIST_MED") static
Referenced by player_morale::player_morale(), and player_morale::update_masochist_bonus().
trait_OPTIMISTIC
const trait_id trait_OPTIMISTIC("OPTIMISTIC") ("OPTIMISTIC") static
Referenced by player_morale::player_morale().
trait_ROOTS1
const trait_id trait_ROOTS1("ROOTS1") ("ROOTS1") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_ROOTS2
const trait_id trait_ROOTS2("ROOTS2") ("ROOTS2") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_ROOTS3
const trait_id trait_ROOTS3("ROOTS3") ("ROOTS3") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_STYLISH
const trait_id trait_STYLISH("STYLISH") ("STYLISH") static
Referenced by player_morale::player_morale().