Cataclysm BN: src/mtype.cpp File Reference
mtype.cpp File Reference
#include "mtype.h"
#include <algorithm>
#include <cmath>
#include <unordered_map>
#include "behavior_strategy.h"
#include "creature.h"
#include "field_type.h"
#include "item.h"
#include "itype.h"
#include "mondeath.h"
#include "monstergenerator.h"
#include "string_id.h"
#include "translations.h"
Variables
static const itype_id itype_bone ("bone")
static const itype_id itype_bone_tainted ("bone_tainted")
static const itype_id itype_fish ("fish")
static const itype_id itype_human_flesh ("human_flesh")
static const itype_id itype_meat ("meat")
static const itype_id itype_meat_tainted ("meat_tainted")
static const itype_id itype_veggy ("veggy")
static const itype_id itype_veggy_tainted ("veggy_tainted")
static const species_id MOLLUSK ("MOLLUSK")
Variable Documentation
itype_bone
const itype_id itype_bone("bone") ("bone") static
Referenced by mtype::get_meat_itype().
itype_bone_tainted
const itype_id itype_bone_tainted("bone_tainted") ("bone_tainted") static
Referenced by mtype::get_meat_itype().
itype_fish
const itype_id itype_fish("fish") ("fish") static
Referenced by mtype::get_meat_itype().
itype_human_flesh
const itype_id itype_human_flesh("human_flesh") ("human_flesh") static
Referenced by mtype::get_meat_itype().
itype_meat
const itype_id itype_meat("meat") ("meat") static
Referenced by mtype::get_meat_itype().
itype_meat_tainted
const itype_id itype_meat_tainted("meat_tainted") ("meat_tainted") static
Referenced by mtype::get_meat_itype().
itype_veggy
const itype_id itype_veggy("veggy") ("veggy") static
Referenced by mtype::get_meat_itype().
itype_veggy_tainted
const itype_id itype_veggy_tainted("veggy_tainted") ("veggy_tainted") static
Referenced by mtype::get_meat_itype().
MOLLUSK
const species_id MOLLUSK("MOLLUSK") ("MOLLUSK") static
Referenced by mtype::gibType().