Cataclysm BN: src/mtype.h File Reference
mtype.h File Reference
#include <map>
#include <set>
#include <string>
#include <vector>
#include "behavior.h"
#include "calendar.h"
#include "color.h"
#include "damage.h"
#include "enum_bitset.h"
#include "enums.h"
#include "mattack_common.h"
#include "optional.h"
#include "pathfinding.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
Classes
struct enum_traits< mon_trigger >
struct enum_traits< m_flag >
struct mon_effect_data
Used to store monster effects placed on attack.
struct regen_modifier
struct mtype
Macros
#define CATA_SRC_MTYPE_H
Typedefs
using mon_action_death = int void(*)(monster &)
using mon_action_attack = bool(*)(monster *)
using mon_action_defend = void(*)(monster &, Creature *, dealt_projectile_attack const *)
using bodytype_id = std::string
Enumerations
enum class mon_trigger : int {
STALK , MEAT , HOSTILE_WEAK , HOSTILE_CLOSE ,
HURT , FIRE , FRIEND_DIED , FRIEND_ATTACKED ,
SOUND , PLAYER_NEAR_BABY , MATING_SEASON , _LAST
}
enum m_flag : int {
MF_SEES , MF_HEARS , MF_GOODHEARING , MF_SMELLS ,
MF_KEENNOSE , MF_STUMBLES , MF_WARM , MF_NOHEAD ,
MF_HARDTOSHOOT , MF_GRABS , MF_BASHES , MF_DESTROYS ,
MF_BORES , MF_POISON , MF_VENOM , MF_BADVENOM ,
MF_PARALYZE , MF_BLEED , MF_WEBWALK , MF_DIGS ,
MF_CAN_DIG , MF_FLIES , MF_AQUATIC , MF_SWIMS ,
MF_ATTACKMON , MF_ANIMAL , MF_PLASTIC , MF_SUNDEATH ,
MF_ELECTRIC , MF_ACIDPROOF , MF_ACIDTRAIL , MF_SHORTACIDTRAIL ,
MF_FIREPROOF , MF_SLUDGEPROOF , MF_SLUDGETRAIL , MF_COLDPROOF ,
MF_FIREY , MF_QUEEN , MF_ELECTRONIC , MF_FUR ,
MF_LEATHER , MF_WOOL , MF_FEATHER , MF_BONES ,
MF_FAT , MF_CONSOLE_DESPAWN , MF_IMMOBILE , MF_ID_CARD_DESPAWN ,
MF_RIDEABLE_MECH , MF_MILITARY_MECH , MF_MECH_RECON_VISION , MF_MECH_DEFENSIVE ,
MF_HIT_AND_RUN , MF_GUILT , MF_PAY_BOT , MF_HUMAN ,
MF_NO_BREATHE , MF_FLAMMABLE , MF_REVIVES , MF_CHITIN ,
MF_VERMIN , MF_NOGIB , MF_LARVA , MF_ARTHROPOD_BLOOD ,
MF_ACID_BLOOD , MF_BILE_BLOOD , MF_ABSORBS , MF_ABSORBS_SPLITS ,
MF_CBM_CIV , MF_CBM_POWER , MF_CBM_SCI , MF_CBM_OP ,
MF_CBM_TECH , MF_CBM_SUBS , MF_FILTHY , MF_FISHABLE ,
MF_GROUP_BASH , MF_SWARMS , MF_GROUP_MORALE , MF_INTERIOR_AMMO ,
MF_CLIMBS , MF_PACIFIST , MF_PUSH_MON , MF_PUSH_VEH ,
MF_NIGHT_INVISIBILITY , MF_REVIVES_HEALTHY , MF_NO_NECRO , MF_AVOID_DANGER_1 ,
MF_AVOID_DANGER_2 , MF_AVOID_FIRE , MF_AVOID_FALL , MF_PRIORITIZE_TARGETS ,
MF_NOT_HALLU , MF_CATFOOD , MF_CATTLEFODDER , MF_BIRDFOOD ,
MF_CANPLAY , MF_PET_MOUNTABLE , MF_PET_HARNESSABLE , MF_DOGFOOD ,
MF_MILKABLE , MF_SHEARABLE , MF_NO_BREED , MF_NO_FUNG_DMG ,
MF_PET_WONT_FOLLOW , MF_DRIPS_NAPALM , MF_DRIPS_GASOLINE , MF_ELECTRIC_FIELD ,
MF_LOUDMOVES , MF_CAN_OPEN_DOORS , MF_STUN_IMMUNE , MF_DROPS_AMMO ,
MF_MAX
}
Functions
mon_effect_data load_mon_effect_data (const JsonObject &e)
Macro Definition Documentation
CATA_SRC_MTYPE_H
#define CATA_SRC_MTYPE_H
Definition at line 3 of file mtype.h.
Typedef Documentation
bodytype_id
using bodytype_id = std::string
Definition at line 35 of file mtype.h.
mon_action_attack
using mon_action_attack = bool (*)(monster *)
Definition at line 33 of file mtype.h.
mon_action_death
using mon_action_death = int void (*)(monster &)
Definition at line 32 of file mtype.h.
mon_action_defend
using mon_action_defend = void (*)(monster &, Creature *, dealt_projectile_attack const *)
Definition at line 34 of file mtype.h.
Enumeration Type Documentation
m_flag
enum m_flag : int
Enumerator
MF_SEES
MF_HEARS
MF_GOODHEARING
MF_SMELLS
MF_KEENNOSE
MF_STUMBLES
MF_WARM
MF_NOHEAD
MF_HARDTOSHOOT
MF_GRABS
MF_BASHES
MF_DESTROYS
MF_BORES
MF_POISON
MF_VENOM
MF_BADVENOM
MF_PARALYZE
MF_BLEED
MF_WEBWALK
MF_DIGS
MF_CAN_DIG
MF_FLIES
MF_AQUATIC
MF_SWIMS
MF_ATTACKMON
MF_ANIMAL
MF_PLASTIC
MF_SUNDEATH
MF_ELECTRIC
MF_ACIDPROOF
MF_ACIDTRAIL
MF_SHORTACIDTRAIL
MF_FIREPROOF
MF_SLUDGEPROOF
MF_SLUDGETRAIL
MF_COLDPROOF
MF_FIREY
MF_QUEEN
MF_ELECTRONIC
MF_FUR
MF_LEATHER
MF_WOOL
MF_FEATHER
MF_BONES
MF_FAT
MF_CONSOLE_DESPAWN
MF_IMMOBILE
MF_ID_CARD_DESPAWN
MF_RIDEABLE_MECH
MF_MILITARY_MECH
MF_MECH_RECON_VISION
MF_MECH_DEFENSIVE
MF_HIT_AND_RUN
MF_GUILT
MF_PAY_BOT
MF_HUMAN
MF_NO_BREATHE
MF_FLAMMABLE
MF_REVIVES
MF_CHITIN
MF_VERMIN
MF_NOGIB
MF_LARVA
MF_ARTHROPOD_BLOOD
MF_ACID_BLOOD
MF_BILE_BLOOD
MF_ABSORBS
MF_ABSORBS_SPLITS
MF_CBM_CIV
MF_CBM_POWER
MF_CBM_SCI
MF_CBM_OP
MF_CBM_TECH
MF_CBM_SUBS
MF_FILTHY
MF_FISHABLE
MF_GROUP_BASH
MF_SWARMS
MF_GROUP_MORALE
MF_INTERIOR_AMMO
MF_CLIMBS
MF_PACIFIST
MF_PUSH_MON
MF_PUSH_VEH
MF_NIGHT_INVISIBILITY
MF_REVIVES_HEALTHY
MF_NO_NECRO
MF_AVOID_DANGER_1
MF_AVOID_DANGER_2
MF_AVOID_FIRE
MF_AVOID_FALL
MF_PRIORITIZE_TARGETS
MF_NOT_HALLU
MF_CATFOOD
MF_CATTLEFODDER
MF_BIRDFOOD
MF_CANPLAY
MF_PET_MOUNTABLE
MF_PET_HARNESSABLE
MF_DOGFOOD
MF_MILKABLE
MF_SHEARABLE
MF_NO_BREED
MF_NO_FUNG_DMG
MF_PET_WONT_FOLLOW
MF_DRIPS_NAPALM
MF_DRIPS_GASOLINE
MF_ELECTRIC_FIELD
MF_LOUDMOVES
MF_CAN_OPEN_DOORS
MF_STUN_IMMUNE
MF_DROPS_AMMO
MF_MAX
Definition at line 66 of file mtype.h.
            : int {
    MF_SEES,                // It can see you (and will run/follow)
    MF_HEARS,               // It can hear you
    MF_GOODHEARING,         // Pursues sounds more than most monsters
    MF_SMELLS,              // It can smell you
    MF_KEENNOSE,            //Keen sense of smell
    MF_STUMBLES,            // Stumbles in its movement
    MF_WARM,                // Warm blooded
    MF_NOHEAD,              // Headshots not allowed!
    MF_HARDTOSHOOT,         // It's one size smaller for ranged attacks, no less then MS_TINY
    MF_GRABS,               // Its attacks may grab us!
    MF_BASHES,              // Bashes down doors
    MF_DESTROYS,            // Bashes down walls and more
    MF_BORES,               // Tunnels through just about anything
    MF_POISON,              // Poisonous to eat
    MF_VENOM,               // Attack may poison the player
    MF_BADVENOM,            // Attack may SEVERELY poison the player
    MF_PARALYZE,            // Attack may paralyze the player with venom
    MF_BLEED,               // Causes player to bleed
    MF_WEBWALK,             // Doesn't destroy webs
    MF_DIGS,                // Digs through the ground
    MF_CAN_DIG,             // Can dig and walk
    MF_FLIES,               // Can fly (over water, etc)
    MF_AQUATIC,             // Confined to water
    MF_SWIMS,               // Treats water as 50 movement point terrain
    MF_ATTACKMON,           // Attacks other monsters
    MF_ANIMAL,              // Is an "animal" for purposes of the Animal Empath trait
    MF_PLASTIC,             // Absorbs physical damage to a great degree
    MF_SUNDEATH,            // Dies in full sunlight
    MF_ELECTRIC,            // Shocks unarmed attackers
    MF_ACIDPROOF,           // Immune to acid
    MF_ACIDTRAIL,           // Leaves a trail of acid
    MF_SHORTACIDTRAIL,       // Leaves an intermittent trail of acid
    MF_FIREPROOF,           // Immune to fire
    MF_SLUDGEPROOF,         // Ignores the effect of sludge trails
    MF_SLUDGETRAIL,         // Causes monster to leave a sludge trap trail when moving
    MF_COLDPROOF,           // Immune to cold damage
    MF_FIREY,               // Burns stuff and is immune to fire
    MF_QUEEN,               // When it dies, local populations start to die off too
    MF_ELECTRONIC,          // e.g. a robot; affected by EMP blasts, and other stuff
    MF_FUR,                 // May produce fur when butchered
    MF_LEATHER,             // May produce leather when butchered
    MF_WOOL,                // May produce wool when butchered
    MF_FEATHER,             // May produce feather when butchered
    MF_BONES,               // May produce bones and sinews when butchered; if combined with POISON flag, tainted bones, if combined with HUMAN, human bones
    MF_FAT,                 // May produce fat when butchered; if combined with POISON flag, tainted fat
    MF_CONSOLE_DESPAWN,     // Despawns when a nearby console is properly hacked
    MF_IMMOBILE,            // Doesn't move (e.g. turrets)
    MF_ID_CARD_DESPAWN,      // Despawns when a science ID card is used on a nearby console
    MF_RIDEABLE_MECH,       // A rideable mech that is immobile until ridden.
    MF_MILITARY_MECH,        // A rideable mech that was designed for military work.
    MF_MECH_RECON_VISION,   // This mech gives you IR night-vision.
    MF_MECH_DEFENSIVE,      // This mech gives you thorough protection.
    MF_HIT_AND_RUN,         // Flee for several turns after a melee attack
    MF_GUILT,               // You feel guilty for killing it
    MF_PAY_BOT,             // You can pay this bot to be your friend for a time
    MF_HUMAN,               // It's a live human, as long as it's alive
    MF_NO_BREATHE,          // Creature can't drown and is unharmed by gas, smoke, or poison
    MF_FLAMMABLE,           // Monster catches fire, burns, and spreads fire to nearby objects
    MF_REVIVES,             // Monster corpse will revive after a short period of time
    MF_CHITIN,              // May produce chitin when butchered
    MF_VERMIN,              // Obsolete flag labeling "nuisance" or "scenery" monsters, now used to prevent loading the same.
    MF_NOGIB,               // Creature won't leave gibs / meat chunks when killed with huge damage.
    MF_LARVA,               // Creature is a larva. Currently used for gib and blood handling.
    MF_ARTHROPOD_BLOOD,     // Forces monster to bleed hemolymph.
    MF_ACID_BLOOD,          // Makes monster bleed acid. Fun stuff! Does not automatically dissolve in a pool of acid on death.
    MF_BILE_BLOOD,          // Makes monster bleed bile.
    MF_ABSORBS,             // Consumes objects it moves over which gives bonus hp.
    MF_ABSORBS_SPLITS,      // Consumes objects it moves over which gives bonus hp. If it gets enough bonus HP, it spawns a copy of itself.
    MF_CBM_CIV,             // May produce a common CBM a power CBM when butchered.
    MF_CBM_POWER,           // May produce a power CBM when butchered, independent of MF_CBM_wev.
    MF_CBM_SCI,             // May produce a bionic from bionics_sci when butchered.
    MF_CBM_OP,              // May produce a bionic from bionics_op when butchered, and the power storage is mk 2.
    MF_CBM_TECH,            // May produce a bionic from bionics_tech when butchered.
    MF_CBM_SUBS,            // May produce a bionic from bionics_subs when butchered.
    MF_FILTHY,              // Any clothing it drops will be filthy.
    MF_FISHABLE,            // It is fishable.
    MF_GROUP_BASH,          // Monsters that can pile up against obstacles and add their strength together to break them.
    MF_SWARMS,              // Monsters that like to group together and form loose packs
    MF_GROUP_MORALE,        // Monsters that are more courageous when near friends
    MF_INTERIOR_AMMO,       // Monster contain's its ammo inside itself, no need to load on launch. Prevents ammo from being dropped on disable.
    MF_CLIMBS,              // Monsters that can climb certain terrain and furniture
    MF_PACIFIST,            // Monsters that will never use melee attack, useful for having them use grab without attacking the player
    MF_PUSH_MON,            // Monsters that can push creatures out of their way
    MF_PUSH_VEH,            // Monsters that can push vehicles out of their way
    MF_NIGHT_INVISIBILITY,  // Monsters that are invisible in poor light conditions
    MF_REVIVES_HEALTHY,     // When revived, this monster has full hitpoints and speed
    MF_NO_NECRO,            // This monster can't be revived by necros. It will still rise on its own.
    MF_AVOID_DANGER_1,      // This monster will path around some dangers instead of through them.
    MF_AVOID_DANGER_2,      // This monster will path around most dangers instead of through them.
    MF_AVOID_FIRE,          // This monster will path around heat-related dangers instead of through them.
    MF_AVOID_FALL,          // This monster will path around cliffs instead of off of them.
    MF_PRIORITIZE_TARGETS,  // This monster will prioritize targets depending on their danger levels
    MF_NOT_HALLU,           // Monsters that will NOT appear when player's producing hallucinations
    MF_CATFOOD,             // This monster will become friendly when fed cat food.
    MF_CATTLEFODDER,        // This monster will become friendly when fed cattle fodder.
    MF_BIRDFOOD,            // This monster will become friendly when fed bird food.
    MF_CANPLAY,             // This monster can be played with if it's a pet.
    MF_PET_MOUNTABLE,       // This monster can be mounted and ridden when tamed.
    MF_PET_HARNESSABLE,     // This monster can be harnessed when tamed.
    MF_DOGFOOD,             // This monster will become friendly when fed dog food.
    MF_MILKABLE,            // This monster is milkable.
    MF_SHEARABLE,           // This monster is shearable.
    MF_NO_BREED,            // This monster doesn't breed, even though it has breed data
    MF_NO_FUNG_DMG,         // This monster can't be fungalized or damaged by fungal spores.
    MF_PET_WONT_FOLLOW,     // This monster won't follow the player automatically when tamed.
    MF_DRIPS_NAPALM,        // This monster ocassionally drips napalm on move
    MF_DRIPS_GASOLINE,      // This monster occasionally drips gasoline on move
    MF_ELECTRIC_FIELD,      // This monster is surrounded by an electrical field that ignites flammable liquids near it
    MF_LOUDMOVES,           // This monster makes move noises as if ~2 sizes louder, even if flying.
    MF_CAN_OPEN_DOORS,      // This monster can open doors.
    MF_STUN_IMMUNE,         // This monster is immune to the stun effect
    MF_DROPS_AMMO,          // This monster drops ammo. Check to make sure starting_ammo paramter is present for this monster type!
    MF_MAX                  // Sets the length of the flags - obviously must be LAST
};
mon_trigger
enum class mon_trigger : int strong
Enumerator
STALK
MEAT
HOSTILE_WEAK
HOSTILE_CLOSE
HURT
FIRE
FRIEND_DIED
FRIEND_ATTACKED
SOUND
PLAYER_NEAR_BABY
MATING_SEASON
_LAST
Definition at line 41 of file mtype.h.
                       : int {
    STALK,              // Increases when following the player
    MEAT,               // Meat or a corpse nearby
    HOSTILE_WEAK,       // Hurt hostile player/npc/monster seen
    HOSTILE_CLOSE,      // Hostile creature within a few tiles
    HURT,               // We are hurt
    FIRE,               // Fire nearby
    FRIEND_DIED,        // A monster of the same type died
    FRIEND_ATTACKED,    // A monster of the same type attacked
    SOUND,              // Heard a sound
    PLAYER_NEAR_BABY,   // Player/npc is near a baby monster of this type
    MATING_SEASON,      // It's the monster's mating season (defined by baby_flags)
    _LAST               // This item must always remain last.
};
Function Documentation
load_mon_effect_data()
mon_effect_data load_mon_effect_data (const JsonObject & e)
Definition at line 649 of file monstergenerator.cpp.
{
    bool permanent = e.get_bool( "permanent", false );
    if( permanent && json_report_strict ) {
        try {
            e.throw_error( "Effect permanence has been moved to effect_type.  Set permanence there.",
                           "permanent" );
        } catch( const JsonError &ex ) {
            debugmsg( "\n%s", ex.what() );
        }
    }
    return mon_effect_data( efftype_id( e.get_string( "id" ) ), e.get_int( "duration", 0 ),
                            e.get_bool( "affect_hit_bp", false ),
                            get_body_part_token( e.get_string( "bp", "NUM_BP" ) ),
                            e.get_int( "chance", 100 ),
                            permanent );
}
References debugmsg, get_body_part_token(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_string(), json_report_strict, and JsonObject::throw_error().
Referenced by mon_attack_effect_reader::get_next(), and melee_actor::load_internal().