Cataclysm BN: src/mutation.h File Reference
mutation.h File Reference
#include <map>
#include <memory>
#include <set>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "creature.h"
#include "damage.h"
#include "hash_utils.h"
#include "memory_fast.h"
#include "optional.h"
#include "point.h"
#include "pldata.h"
#include "translations.h"
#include "type_id.h"
#include "value_ptr.h"
Classes
struct mut_attack
struct mut_transform
struct mutation_branch
struct mutation_category_trait
struct enum_traits< mutagen_technique >
struct mutagen_attempt
Macros
#define CATA_SRC_MUTATION_H
Enumerations
enum class mutagen_technique : int {
consumed_mutagen , injected_mutagen , consumed_purifier , injected_purifier ,
injected_smart_purifier , num_mutagen_techniques
}
enum class mutagen_rejection { accepted , rejected , destroyed }
Functions
void load_mutation_type (const JsonObject &jsobj)
void reset_mutation_types ()
bool mutation_category_is_valid (const std::string &cat)
bool mutation_type_exists (const std::string &id)
std::vector< trait_id > get_mutations_in_types (const std::set< std::string > &ids)
std::vector< trait_id > get_mutations_in_type (const std::string &id)
bool trait_display_sort (const trait_id &a, const trait_id &b) noexcept
bool trait_display_nocolor_sort (const trait_id &a, const trait_id &b) noexcept
bool are_conflicting_traits (const trait_id &trait_a, const trait_id &trait_b)
bool b_is_lower_trait_of_a (const trait_id &trait_a, const trait_id &trait_b)
bool b_is_higher_trait_of_a (const trait_id &trait_a, const trait_id &trait_b)
bool are_opposite_traits (const trait_id &trait_a, const trait_id &trait_b)
bool are_same_type_traits (const trait_id &trait_a, const trait_id &trait_b)
bool contains_trait (std::vector< string_id< mutation_branch > > traits, const trait_id &trait)
bool can_use_mutation (const trait_id &mut, const Character &character)
Check to see if the specified character has enough resources to use that mutation.
bool can_use_mutation_warn (const trait_id &mut, const Character &character)
Calls can_use_mutation and if it fails, print a standard message.
mutagen_attempt mutagen_common_checks (Character &guy, const item &it, bool strong, mutagen_technique technique)
void test_crossing_threshold (Character &guy, const mutation_category_trait &m_category)
Variables
std::map< std::string, std::vector< trait_id > > mutations_category
Macro Definition Documentation
CATA_SRC_MUTATION_H
#define CATA_SRC_MUTATION_H
Definition at line 3 of file mutation.h.
Enumeration Type Documentation
mutagen_rejection
enum class mutagen_rejection strong
Enumerator
accepted
rejected
destroyed
Definition at line 503 of file mutation.h.
{
    accepted,
    rejected,
    destroyed
};
mutagen_technique
enum class mutagen_technique : int strong
Enumerator
consumed_mutagen
injected_mutagen
consumed_purifier
injected_purifier
injected_smart_purifier
num_mutagen_techniques
Definition at line 489 of file mutation.h.
                             : int {
    consumed_mutagen,
    injected_mutagen,
    consumed_purifier,
    injected_purifier,
    injected_smart_purifier,
    num_mutagen_techniques // last
};
Function Documentation
are_conflicting_traits()
bool are_conflicting_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1661 of file mutation.cpp.
{
    return ( are_opposite_traits( trait_a, trait_b ) || b_is_lower_trait_of_a( trait_a, trait_b )
             || b_is_higher_trait_of_a( trait_a, trait_b ) || are_same_type_traits( trait_a, trait_b ) );
}
References are_opposite_traits(), are_same_type_traits(), b_is_higher_trait_of_a(), and b_is_lower_trait_of_a().
Referenced by scenario::scenario_traits_conflict_with_profession_traits().
are_opposite_traits()
bool are_opposite_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1667 of file mutation.cpp.
{
    return contains_trait( trait_a->cancels, trait_b );
}
References mutation_branch::cancels, and contains_trait().
Referenced by are_conflicting_traits().
are_same_type_traits()
bool are_same_type_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1682 of file mutation.cpp.
{
    return contains_trait( get_mutations_in_types( trait_a->types ), trait_b );
}
References contains_trait(), get_mutations_in_types(), and mutation_branch::types.
Referenced by are_conflicting_traits().
b_is_higher_trait_of_a()
bool b_is_higher_trait_of_a (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1677 of file mutation.cpp.
{
    return contains_trait( trait_a->replacements, trait_b );
}
References contains_trait(), and mutation_branch::replacements.
Referenced by are_conflicting_traits().
b_is_lower_trait_of_a()
bool b_is_lower_trait_of_a (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1672 of file mutation.cpp.
{
    return contains_trait( trait_a->prereqs, trait_b );
}
References contains_trait(), and mutation_branch::prereqs.
Referenced by are_conflicting_traits().
can_use_mutation()
bool can_use_mutation (const trait_id & mut, const Character & character)
Check to see if the specified character has enough resources to use that mutation.
Definition at line 1692 of file mutation.cpp.
{
    const mutation_branch &mdata = mut.obj();
    // You can take yourself halfway to Near Death levels of hunger/thirst.
    // Fatigue can go to Exhausted.
    return !( ( mdata.hunger && character.get_kcal_percent() < 0.5f ) ||
              ( mdata.thirst && character.get_thirst() >= thirst_levels::dehydrated ) ||
              ( mdata.fatigue && character.get_fatigue() >= fatigue_levels::exhausted ) );
}
References dehydrated, exhausted, mutation_branch::fatigue, Character::get_fatigue(), Character::get_kcal_percent(), Character::get_thirst(), mutation_branch::hunger, string_id< T >::obj(), and mutation_branch::thirst.
Referenced by can_use_mutation_warn().
can_use_mutation_warn()
bool can_use_mutation_warn (const trait_id & mut, const Character & character)
Calls can_use_mutation and if it fails, print a standard message.
Definition at line 1702 of file mutation.cpp.
{
    const bool result = can_use_mutation( mut, character );
    if( !result ) {
        character.add_msg_if_player( m_warning, _( "You feel like using your %s would kill you!" ),
                                     mut.obj().name() );
    }
    return result;
}
References _, Creature::add_msg_if_player(), can_use_mutation(), m_warning, mutation_branch::name(), and string_id< T >::obj().
Referenced by Character::activate_mutation(), iexamine::ledge(), detail::show_mutations_ui_internal(), and game::vertical_move().
contains_trait()
bool contains_trait (std::vector< string_id< mutation_branch > > traits, const trait_id & trait)
Definition at line 1687 of file mutation.cpp.
{
    return std::find( traits.begin(), traits.end(), trait ) != traits.end();
}
References detail::find().
Referenced by are_opposite_traits(), are_same_type_traits(), b_is_higher_trait_of_a(), and b_is_lower_trait_of_a().
get_mutations_in_type()
std::vector< trait_id > get_mutations_in_type (const std::string & id)
Definition at line 29 of file mutation_type.cpp.
{
    std::vector<trait_id> ret;
    for( const mutation_branch &it : mutation_branch::get_all() ) {
        if( it.types.find( id ) != it.types.end() ) {
            ret.push_back( it.id );
        }
    }
    return ret;
}
References mutation_branch::get_all(), and cata::hash64_detail::ret.
Referenced by generic_barber(), and get_mutations_in_types().
get_mutations_in_types()
std::vector< trait_id > get_mutations_in_types (const std::set< std::string > & ids)
Definition at line 40 of file mutation_type.cpp.
{
    std::vector<trait_id> ret;
    for( const std::string &it : ids ) {
        std::vector<trait_id> this_id = get_mutations_in_type( it );
        ret.insert( ret.end(), this_id.begin(), this_id.end() );
    }
    return ret;
}
References get_mutations_in_type(), and cata::hash64_detail::ret.
Referenced by are_same_type_traits(), newcharacter::has_same_type_trait(), and Character::mutate_towards().
load_mutation_type()
void load_mutation_type (const JsonObject & jsobj)
Definition at line 11 of file mutation_type.cpp.
{
    mutation_type new_type;
    new_type.id = jsobj.get_string( "id" );
    mutation_types[new_type.id] = new_type;
}
References JsonObject::get_string(), mutation_type::id, and mutation_types.
Referenced by DynamicDataLoader::initialize().
mutagen_common_checks()
mutagen_attempt mutagen_common_checks (Character & guy, const item & it, bool strong, mutagen_technique technique)
Definition at line 1580 of file mutation.cpp.
{
    g->events().send<event_type::administers_mutagen>( guy.getID(), technique );
    mutagen_rejection status = try_reject_mutagen( guy, it, strong );
    if( status == mutagen_rejection::rejected ) {
        return mutagen_attempt( false, 0 );
    }
    if( status == mutagen_rejection::destroyed ) {
        return mutagen_attempt( false, it.type->charges_to_use() );
    }
    return mutagen_attempt( true, 0 );
}
References administers_mutagen, itype::charges_to_use(), destroyed, g, Character::getID(), rejected, try_reject_mutagen(), and item::type.
Referenced by iuse::purifier(), iuse::purify_iv(), iuse::purify_smart(), mutagen_actor::use(), and mutagen_iv_actor::use().
mutation_category_is_valid()
bool mutation_category_is_valid (const std::string & cat)
Definition at line 894 of file mutation_data.cpp.
{
    return mutation_category_traits.count( cat );
}
References mutation_category_traits.
mutation_type_exists()
bool mutation_type_exists (const std::string & id)
Definition at line 24 of file mutation_type.cpp.
{
    return mutation_types.find( id ) != mutation_types.end();
}
References mutation_types.
Referenced by mutation_branch::check_consistency().
reset_mutation_types()
void reset_mutation_types ()
Definition at line 19 of file mutation_type.cpp.
{
    mutation_types.clear();
}
References mutation_types.
Referenced by DynamicDataLoader::unload_data().
test_crossing_threshold()
void test_crossing_threshold (Character & guy, const mutation_category_trait & m_category)
Definition at line 1595 of file mutation.cpp.
{
    // Threshold-check.  You only get to cross once!
    if( guy.crossed_threshold() ) {
        return;
    }
    // If there is no threshold for this category, don't check it
    const trait_id &mutation_thresh = m_category.threshold_mut;
    if( mutation_thresh.is_empty() ) {
        return;
    }
    std::string mutation_category = m_category.id;
    int total = 0;
    for( const auto &iter : mutation_category_trait::get_all() ) {
        total += guy.mutation_category_level[ iter.first ];
    }
    // Threshold-breaching
    const std::string &primary = guy.get_highest_category();
    int breach_power = guy.mutation_category_level[primary];
    // Only if you were pushing for more in your primary category.
    // You wanted to be more like it and less human.
    // That said, you're required to have hit third-stage dreams first.
    if( ( mutation_category == primary ) && ( breach_power > 50 ) ) {
        // Little help for the categories that have a lot of crossover.
        // Starting with Ursine as that's... a bear to get.  8-)
        // Alpha is similarly eclipsed by other mutation categories.
        // Will add others if there's serious/demonstrable need.
        int booster = 0;
        if( mutation_category == "URSINE"  || mutation_category == "ALPHA" ) {
            booster = 50;
        }
        int breacher = breach_power + booster;
        if( x_in_y( breacher, total ) ) {
            guy.add_msg_if_player( m_good,
                                   _( "Something strains mightily for a moment and then you're FREE!" ) );
            guy.set_mutation( mutation_thresh );
            g->events().send<event_type::crosses_mutation_threshold>( guy.getID(), m_category.id );
            // Manually removing Carnivore, since it tends to creep in
            // This is because carnivore is a prerequisite for the
            // predator-style post-threshold mutations.
            if( mutation_category == "URSINE" && guy.has_trait( trait_CARNIVORE ) ) {
                guy.unset_mutation( trait_CARNIVORE );
                guy.add_msg_if_player( _( "Your appetite for blood fades." ) );
            }
        }
    } else if( guy.has_trait( trait_NOPAIN ) ) {
        //~NOPAIN is a post-Threshold trait, so you shouldn't
        //~legitimately have it and get here!
        guy.add_msg_if_player( m_bad, _( "You feel extremely Bugged." ) );
    } else if( breach_power > 100 ) {
        guy.add_msg_if_player( m_bad, _( "You stagger with a piercing headache!" ) );
        guy.mod_pain_noresist( 8 );
        guy.add_effect( effect_stunned, rng( 3_turns, 5_turns ) );
    } else if( breach_power > 80 ) {
        guy.add_msg_if_player( m_bad,
                               _( "Your head throbs with memories of your life, before all this" ) );
        guy.mod_pain_noresist( 6 );
        guy.add_effect( effect_stunned, rng( 2_turns, 4_turns ) );
    } else if( breach_power > 60 ) {
        guy.add_msg_if_player( m_bad, _( "Images of your past life flash before you." ) );
        guy.add_effect( effect_stunned, rng( 2_turns, 3_turns ) );
    }
}
References _, Creature::add_effect(), Creature::add_msg_if_player(), Character::crossed_threshold(), crosses_mutation_threshold, effect_stunned, g, mutation_category_trait::get_all(), Character::get_highest_category(), Character::getID(), Character::has_trait(), mutation_category_trait::id, string_id< T >::is_empty(), m_bad, m_good, Creature::mod_pain_noresist(), Character::mutation_category_level, rng(), Character::set_mutation(), mutation_category_trait::threshold_mut, trait_CARNIVORE, trait_NOPAIN, Character::unset_mutation(), and x_in_y().
Referenced by mutagen_iv_actor::use().
trait_display_nocolor_sort()
bool trait_display_nocolor_sort (const trait_id & a, const trait_id & b) noexcept
Definition at line 701 of file mutation_data.cpp.
{
    return localized_compare( a->name(), b->name() );
}
References a, b, and localized_compare.
trait_display_sort()
bool trait_display_sort (const trait_id & a, const trait_id & b) noexcept
Definition at line 689 of file mutation_data.cpp.
{
    if( a->get_display_color() > b->get_display_color() ) {
        return true;
    }
    if( a->get_display_color() < b->get_display_color() ) {
        return false;
    }
    return localized_compare( a->name(), b->name() );
}
References a, b, and localized_compare.
Referenced by character_display::disp_info(), and set_description().
Variable Documentation
mutations_category
std::map<std::string, std::vector<trait_id> > mutations_category extern
Definition at line 64 of file mutation_data.cpp.
Referenced by mutation_branch::finalize(), Character::mutate_category(), Character::old_mutate(), mutation_branch::reset_all(), and DynamicDataLoader::unload_data().