Cataclysm BN: src/mutation_ui.h File Reference
mutation_ui.h File Reference
#include "type_id.h"
Classes
struct detail::mutations_ui_result
Namespaces
namespace detail
Macros
#define CATA_SRC_MUTATION_UI_H
Enumerations
enum class detail::mutations_ui_cmd { detail::exit , detail::activate , detail::deactivate }
Functions
mutations_ui_result detail::show_mutations_ui_internal (Character &who)
void show_mutations_ui (Character &who)
Macro Definition Documentation
CATA_SRC_MUTATION_UI_H
#define CATA_SRC_MUTATION_UI_H
Definition at line 3 of file mutation_ui.h.
Function Documentation
show_mutations_ui()
void show_mutations_ui (Character & who)
Definition at line 100 of file mutation_ui.cpp.
{
    if( !who.is_avatar() ) {
        // TODO: Implement NPCs activating mutations
        return;
    }
    // Mutation selection UI obscures the terrain,
    // but some mutations may ask to select a tile when activated.
    // As such, we must (de-)activate only after destroying the UI.
    detail::mutations_ui_result res = detail::show_mutations_ui_internal( who );
    switch( res.cmd ) {
        case detail::mutations_ui_cmd::exit:
            break;
        case detail::mutations_ui_cmd::deactivate:
            who.deactivate_mutation( res.mut );
            break;
        case detail::mutations_ui_cmd::activate:
            who.activate_mutation( res.mut );
            break;
    }
}
References detail::activate, Character::activate_mutation(), detail::mutations_ui_result::cmd, detail::deactivate, Character::deactivate_mutation(), detail::exit, Creature::is_avatar(), detail::mutations_ui_result::mut, and detail::show_mutations_ui_internal().
Referenced by game::handle_action().