Cataclysm BN: src/mutation.cpp File Reference
mutation.cpp File Reference
#include "mutation.h"
#include <cmath>
#include <algorithm>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <numeric>
#include <unordered_set>
#include "avatar_action.h"
#include "basecamp.h"
#include "bionics.h"
#include "character.h"
#include "color.h"
#include "creature.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "field_type.h"
#include "game.h"
#include "item.h"
#include "item_contents.h"
#include "itype.h"
#include "magic_enchantment.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "math_defines.h"
#include "memorial_logger.h"
#include "monster.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "rng.h"
#include "string_id.h"
#include "translations.h"
#include "units.h"
#include "weighted_list.h"
Classes
struct potential_mutation
Namespaces
namespace io
Functions
template<>
std::string io::enum_to_string< mutagen_technique > (mutagen_technique data)
static int sum_of_mutation_costs (const Character &c)
static int genetic_score (const Character &c)
static float score_difference_to_chance (float diff)
template<class T , class V = typename T::value_type>
static T normalized_map (const T &ctn)
static std::map< std::string, float > calc_category_weights (const std::map< std::string, int > &mcl, bool addition)
static std::vector< trait_id > get_all_mutation_prereqs (const trait_id &id)
static mutagen_rejection try_reject_mutagen (Character &guy, const item &it, bool strong)
mutagen_attempt mutagen_common_checks (Character &guy, const item &it, bool strong, const mutagen_technique technique)
void test_crossing_threshold (Character &guy, const mutation_category_trait &m_category)
bool are_conflicting_traits (const trait_id &trait_a, const trait_id &trait_b)
bool are_opposite_traits (const trait_id &trait_a, const trait_id &trait_b)
bool b_is_lower_trait_of_a (const trait_id &trait_a, const trait_id &trait_b)
bool b_is_higher_trait_of_a (const trait_id &trait_a, const trait_id &trait_b)
bool are_same_type_traits (const trait_id &trait_a, const trait_id &trait_b)
bool contains_trait (std::vector< string_id< mutation_branch > > traits, const trait_id &trait)
bool can_use_mutation (const trait_id &mut, const Character &character)
Check to see if the specified character has enough resources to use that mutation.
bool can_use_mutation_warn (const trait_id &mut, const Character &character)
Calls can_use_mutation and if it fails, print a standard message.
Variables
static const activity_id ACT_TREE_COMMUNION ("ACT_TREE_COMMUNION")
static const efftype_id effect_accumulated_mutagen ("accumulated_mutagen")
static const efftype_id effect_stunned ("stunned")
static const trait_id trait_BURROW ("BURROW")
static const trait_id trait_CARNIVORE ("CARNIVORE")
static const trait_id trait_CHAOTIC_BAD ("CHAOTIC_BAD")
static const trait_id trait_DEBUG_BIONIC_POWER ("DEBUG_BIONIC_POWER")
static const trait_id trait_DEBUG_BIONIC_POWERGEN ("DEBUG_BIONIC_POWERGEN")
static const trait_id trait_DEX_ALPHA ("DEX_ALPHA")
static const trait_id trait_GLASSJAW ("GLASSJAW")
static const trait_id trait_INT_ALPHA ("INT_ALPHA")
static const trait_id trait_INT_SLIME ("INT_SLIME")
static const trait_id trait_M_BLOOM ("M_BLOOM")
static const trait_id trait_M_BLOSSOMS ("M_BLOSSOMS")
static const trait_id trait_M_FERTILE ("M_FERTILE")
static const trait_id trait_M_PROVENANCE ("M_PROVENANCE")
static const trait_id trait_M_SPORES ("M_SPORES")
static const trait_id trait_MUTAGEN_AVOID ("MUTAGEN_AVOID")
static const trait_id trait_NAUSEA ("NAUSEA")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PER_ALPHA ("PER_ALPHA")
static const trait_id trait_ROBUST ("ROBUST")
static const trait_id trait_ROOTS2 ("ROOTS2")
static const trait_id trait_ROOTS3 ("ROOTS3")
static const trait_id trait_SELFAWARE ("SELFAWARE")
static const trait_id trait_SLIMESPAWNER ("SLIMESPAWNER")
static const trait_id trait_STR_ALPHA ("STR_ALPHA")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const trait_id trait_TREE_COMMUNION ("TREE_COMMUNION")
static const trait_id trait_VOMITOUS ("VOMITOUS")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
Function Documentation
are_conflicting_traits()
bool are_conflicting_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1661 of file mutation.cpp.
{
    return ( are_opposite_traits( trait_a, trait_b ) || b_is_lower_trait_of_a( trait_a, trait_b )
             || b_is_higher_trait_of_a( trait_a, trait_b ) || are_same_type_traits( trait_a, trait_b ) );
}
References are_opposite_traits(), are_same_type_traits(), b_is_higher_trait_of_a(), and b_is_lower_trait_of_a().
Referenced by scenario::scenario_traits_conflict_with_profession_traits().
are_opposite_traits()
bool are_opposite_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1667 of file mutation.cpp.
{
    return contains_trait( trait_a->cancels, trait_b );
}
References mutation_branch::cancels, and contains_trait().
Referenced by are_conflicting_traits().
are_same_type_traits()
bool are_same_type_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1682 of file mutation.cpp.
{
    return contains_trait( get_mutations_in_types( trait_a->types ), trait_b );
}
References contains_trait(), get_mutations_in_types(), and mutation_branch::types.
Referenced by are_conflicting_traits().
b_is_higher_trait_of_a()
bool b_is_higher_trait_of_a (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1677 of file mutation.cpp.
{
    return contains_trait( trait_a->replacements, trait_b );
}
References contains_trait(), and mutation_branch::replacements.
Referenced by are_conflicting_traits().
b_is_lower_trait_of_a()
bool b_is_lower_trait_of_a (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 1672 of file mutation.cpp.
{
    return contains_trait( trait_a->prereqs, trait_b );
}
References contains_trait(), and mutation_branch::prereqs.
Referenced by are_conflicting_traits().
calc_category_weights()
static std::map< std::string, float > calc_category_weights (const std::map< std::string, int > & mcl, bool addition) static
Definition at line 709 of file mutation.cpp.
{
    std::map<std::string, float> category_weights;
    auto max_lvl_iter = std::max_element( mcl.begin(), mcl.end(),
    []( const auto & best, const auto & current ) {
        return current.second > best.second;
    } );
    float h_lvl = std::max<float>( max_lvl_iter->second, 20.0f );
    for( const auto &cat_lvl : mcl ) {
        float weight = addition ? ( 1 + 4 * ( cat_lvl.second / h_lvl ) )
                       : ( 5 - 4 * ( cat_lvl.second / h_lvl ) );
        category_weights[cat_lvl.first] = weight;
    }
    category_weights[max_lvl_iter->first] *= 2;
    return normalized_map( category_weights );
}
References normalized_map().
Referenced by Character::mutation_chances().
can_use_mutation()
bool can_use_mutation (const trait_id & mut, const Character & character)
Check to see if the specified character has enough resources to use that mutation.
Definition at line 1692 of file mutation.cpp.
{
    const mutation_branch &mdata = mut.obj();
    // You can take yourself halfway to Near Death levels of hunger/thirst.
    // Fatigue can go to Exhausted.
    return !( ( mdata.hunger && character.get_kcal_percent() < 0.5f ) ||
              ( mdata.thirst && character.get_thirst() >= thirst_levels::dehydrated ) ||
              ( mdata.fatigue && character.get_fatigue() >= fatigue_levels::exhausted ) );
}
References dehydrated, exhausted, mutation_branch::fatigue, Character::get_fatigue(), Character::get_kcal_percent(), Character::get_thirst(), mutation_branch::hunger, string_id< T >::obj(), and mutation_branch::thirst.
Referenced by can_use_mutation_warn().
can_use_mutation_warn()
bool can_use_mutation_warn (const trait_id & mut, const Character & character)
Calls can_use_mutation and if it fails, print a standard message.
Definition at line 1702 of file mutation.cpp.
{
    const bool result = can_use_mutation( mut, character );
    if( !result ) {
        character.add_msg_if_player( m_warning, _( "You feel like using your %s would kill you!" ),
                                     mut.obj().name() );
    }
    return result;
}
References _, Creature::add_msg_if_player(), can_use_mutation(), m_warning, mutation_branch::name(), and string_id< T >::obj().
Referenced by Character::activate_mutation(), iexamine::ledge(), detail::show_mutations_ui_internal(), and game::vertical_move().
contains_trait()
bool contains_trait (std::vector< string_id< mutation_branch > > traits, const trait_id & trait)
Definition at line 1687 of file mutation.cpp.
{
    return std::find( traits.begin(), traits.end(), trait ) != traits.end();
}
References detail::find().
Referenced by are_opposite_traits(), are_same_type_traits(), b_is_higher_trait_of_a(), and b_is_lower_trait_of_a().
genetic_score()
static int genetic_score (const Character & c) static
Definition at line 673 of file mutation.cpp.
{
    // Assumes 4*8+6 stats
    // TODO: Get actual starting stats
    return 38 + sum_of_mutation_costs( c );
}
References c, and sum_of_mutation_costs().
Referenced by Character::mutation_chances().
get_all_mutation_prereqs()
static std::vector< trait_id > get_all_mutation_prereqs (const trait_id & id) static
Definition at line 1071 of file mutation.cpp.
{
    std::vector<trait_id> ret;
    for( const trait_id &it : id->prereqs ) {
        ret.push_back( it );
        std::vector<trait_id> these_prereqs = get_all_mutation_prereqs( it );
        ret.insert( ret.end(), these_prereqs.begin(), these_prereqs.end() );
    }
    for( const trait_id &it : id->prereqs2 ) {
        ret.push_back( it );
        std::vector<trait_id> these_prereqs = get_all_mutation_prereqs( it );
        ret.insert( ret.end(), these_prereqs.begin(), these_prereqs.end() );
    }
    return ret;
}
References get_all_mutation_prereqs(), int_id< T >::id(), and cata::hash64_detail::ret.
Referenced by get_all_mutation_prereqs(), and Character::mutate_towards().
mutagen_common_checks()
mutagen_attempt mutagen_common_checks (Character & guy, const item & it, bool strong, const mutagen_technique technique)
Definition at line 1580 of file mutation.cpp.
{
    g->events().send<event_type::administers_mutagen>( guy.getID(), technique );
    mutagen_rejection status = try_reject_mutagen( guy, it, strong );
    if( status == mutagen_rejection::rejected ) {
        return mutagen_attempt( false, 0 );
    }
    if( status == mutagen_rejection::destroyed ) {
        return mutagen_attempt( false, it.type->charges_to_use() );
    }
    return mutagen_attempt( true, 0 );
}
References administers_mutagen, itype::charges_to_use(), destroyed, g, Character::getID(), rejected, try_reject_mutagen(), and item::type.
Referenced by iuse::purifier(), iuse::purify_iv(), iuse::purify_smart(), mutagen_actor::use(), and mutagen_iv_actor::use().
normalized_map()
template<class T , class V = typename T::value_type> static T normalized_map (const T & ctn) static
Definition at line 689 of file mutation.cpp.
{
    T ret;
    float sum = std::accumulate( std::begin( ctn ), std::end( ctn ), 0.0f,
    []( float acc, const V & v ) {
        return acc + v.second;
    } );
    std::transform( std::begin( ctn ), std::end( ctn ), std::inserter( ret, ret.end() ),
    [sum]( const V & v ) {
        return V( v.first, v.second / sum );
    } );
    return ret;
}
References cata::hash64_detail::ret, and iexamine::transform().
Referenced by calc_category_weights(), and Character::mutation_chances().
score_difference_to_chance()
static float score_difference_to_chance (float diff) static
Definition at line 680 of file mutation.cpp.
{
    const float M_SQRT_PI_2 = std::sqrt( 2 * M_PI );
    constexpr float mean = 0.0f;
    constexpr float sigma = 5.0f;
    return ( 1 / ( sigma * M_SQRT_PI_2 ) ) * exp( -0.5 * pow( ( diff - mean ) / sigma, 2.0 ) );
}
References M_PI.
Referenced by Character::mutation_chances().
sum_of_mutation_costs()
static int sum_of_mutation_costs (const Character & c) static
Definition at line 664 of file mutation.cpp.
{
    const auto mutations = c.get_mutations();
    return std::accumulate( mutations.begin(), mutations.end(), 0, []( int i, const trait_id & tr ) {
        return i + tr->cost;
    } );
}
References c.
Referenced by genetic_score().
test_crossing_threshold()
void test_crossing_threshold (Character & guy, const mutation_category_trait & m_category)
Definition at line 1595 of file mutation.cpp.
{
    // Threshold-check.  You only get to cross once!
    if( guy.crossed_threshold() ) {
        return;
    }
    // If there is no threshold for this category, don't check it
    const trait_id &mutation_thresh = m_category.threshold_mut;
    if( mutation_thresh.is_empty() ) {
        return;
    }
    std::string mutation_category = m_category.id;
    int total = 0;
    for( const auto &iter : mutation_category_trait::get_all() ) {
        total += guy.mutation_category_level[ iter.first ];
    }
    // Threshold-breaching
    const std::string &primary = guy.get_highest_category();
    int breach_power = guy.mutation_category_level[primary];
    // Only if you were pushing for more in your primary category.
    // You wanted to be more like it and less human.
    // That said, you're required to have hit third-stage dreams first.
    if( ( mutation_category == primary ) && ( breach_power > 50 ) ) {
        // Little help for the categories that have a lot of crossover.
        // Starting with Ursine as that's... a bear to get.  8-)
        // Alpha is similarly eclipsed by other mutation categories.
        // Will add others if there's serious/demonstrable need.
        int booster = 0;
        if( mutation_category == "URSINE"  || mutation_category == "ALPHA" ) {
            booster = 50;
        }
        int breacher = breach_power + booster;
        if( x_in_y( breacher, total ) ) {
            guy.add_msg_if_player( m_good,
                                   _( "Something strains mightily for a moment and then you're FREE!" ) );
            guy.set_mutation( mutation_thresh );
            g->events().send<event_type::crosses_mutation_threshold>( guy.getID(), m_category.id );
            // Manually removing Carnivore, since it tends to creep in
            // This is because carnivore is a prerequisite for the
            // predator-style post-threshold mutations.
            if( mutation_category == "URSINE" && guy.has_trait( trait_CARNIVORE ) ) {
                guy.unset_mutation( trait_CARNIVORE );
                guy.add_msg_if_player( _( "Your appetite for blood fades." ) );
            }
        }
    } else if( guy.has_trait( trait_NOPAIN ) ) {
        //~NOPAIN is a post-Threshold trait, so you shouldn't
        //~legitimately have it and get here!
        guy.add_msg_if_player( m_bad, _( "You feel extremely Bugged." ) );
    } else if( breach_power > 100 ) {
        guy.add_msg_if_player( m_bad, _( "You stagger with a piercing headache!" ) );
        guy.mod_pain_noresist( 8 );
        guy.add_effect( effect_stunned, rng( 3_turns, 5_turns ) );
    } else if( breach_power > 80 ) {
        guy.add_msg_if_player( m_bad,
                               _( "Your head throbs with memories of your life, before all this" ) );
        guy.mod_pain_noresist( 6 );
        guy.add_effect( effect_stunned, rng( 2_turns, 4_turns ) );
    } else if( breach_power > 60 ) {
        guy.add_msg_if_player( m_bad, _( "Images of your past life flash before you." ) );
        guy.add_effect( effect_stunned, rng( 2_turns, 3_turns ) );
    }
}
References _, Creature::add_effect(), Creature::add_msg_if_player(), Character::crossed_threshold(), crosses_mutation_threshold, effect_stunned, g, mutation_category_trait::get_all(), Character::get_highest_category(), Character::getID(), Character::has_trait(), mutation_category_trait::id, string_id< T >::is_empty(), m_bad, m_good, Creature::mod_pain_noresist(), Character::mutation_category_level, rng(), Character::set_mutation(), mutation_category_trait::threshold_mut, trait_CARNIVORE, trait_NOPAIN, Character::unset_mutation(), and x_in_y().
Referenced by mutagen_iv_actor::use().
try_reject_mutagen()
static mutagen_rejection try_reject_mutagen (Character & guy, const item & it, bool strong) static
Definition at line 1500 of file mutation.cpp.
{
    if( guy.has_trait( trait_MUTAGEN_AVOID ) ) {
        guy.add_msg_if_player( m_warning,
                               //~ "Uh-uh" is a sound used for "nope", "no", etc.
                               _( "After what happened that last time?  uh-uh.  You're not drinking that chemical stuff." ) );
        return mutagen_rejection::rejected;
    }
    static const std::vector<std::string> safe = {{
            "MYCUS", "MARLOSS", "MARLOSS_SEED", "MARLOSS_GEL"
        }
    };
    if( std::any_of( safe.begin(), safe.end(), [it]( const std::string & flag ) {
    return it.type->can_use( flag );
    } ) ) {
        return mutagen_rejection::accepted;
    }
    if( guy.has_trait( trait_THRESH_MYCUS ) ) {
        guy.add_msg_if_player( m_info, _( "This is a contaminant.  We reject it from the Mycus." ) );
        if( guy.has_trait( trait_M_SPORES ) || guy.has_trait( trait_M_FERTILE ) ||
            guy.has_trait( trait_M_BLOSSOMS ) || guy.has_trait( trait_M_BLOOM ) ) {
            guy.add_msg_if_player( m_good, _( "We decontaminate it with spores." ) );
            g->m.ter_set( guy.pos(), t_fungus );
            if( guy.is_avatar() ) {
                g->memorial().add(
                    pgettext( "memorial_male", "Destroyed a harmful invader." ),
                    pgettext( "memorial_female", "Destroyed a harmful invader." ) );
            }
            return mutagen_rejection::destroyed;
        } else {
            guy.add_msg_if_player( m_bad,
                                   _( "We must eliminate this contaminant at the earliest opportunity." ) );
            return mutagen_rejection::rejected;
        }
    }
    if( guy.has_trait( trait_THRESH_MARLOSS ) ) {
        guy.add_msg_player_or_npc( m_warning,
                                   _( "The %s sears your insides white-hot, and you collapse to the ground!" ),
                                   _( "<npcname> writhes in agony and collapses to the ground!" ),
                                   it.tname() );
        guy.vomit();
        guy.mod_pain( 35 + ( strong ? 20 : 0 ) );
        // Lose a significant amount of HP, probably about 25-33%
        guy.hurtall( rng( 20, 35 ) + ( strong ? 10 : 0 ), nullptr );
        // Hope you were eating someplace safe.  Mycus v. Goo in your guts is no joke.
        guy.fall_asleep( 5_hours - 1_minutes * ( guy.int_cur + ( strong ? 100 : 0 ) ) );
        guy.set_mutation( trait_MUTAGEN_AVOID );
        // Injected mutagen purges marloss, ingested doesn't
        if( strong ) {
            guy.unset_mutation( trait_THRESH_MARLOSS );
            guy.add_msg_if_player( m_warning,
                                   _( "It was probably that marloss -- how did you know to call it \"marloss\" anyway?" ) );
            guy.add_msg_if_player( m_warning, _( "Best to stay clear of that alien crap in future." ) );
            if( guy.is_avatar() ) {
                g->memorial().add(
                    pgettext( "memorial_male",
                              "Burned out a particularly nasty fungal infestation." ),
                    pgettext( "memorial_female",
                              "Burned out a particularly nasty fungal infestation." ) );
            }
        } else {
            guy.add_msg_if_player( m_warning,
                                   _( "That was some toxic %s!  Let's stick with Marloss next time, that's safe." ),
                                   it.tname() );
            if( guy.is_avatar() ) {
                g->memorial().add(
                    pgettext( "memorial_male", "Suffered a toxic marloss/mutagen reaction." ),
                    pgettext( "memorial_female", "Suffered a toxic marloss/mutagen reaction." ) );
            }
        }
        return mutagen_rejection::destroyed;
    }
    return mutagen_rejection::accepted;
}
References _, accepted, Creature::add_msg_if_player(), Creature::add_msg_player_or_npc(), destroyed, Character::fall_asleep(), g, Character::has_trait(), Character::hurtall(), Character::int_cur, Creature::is_avatar(), m_bad, m_good, m_info, m_warning, Character::mod_pain(), pgettext(), Character::pos(), rejected, rng(), iexamine::safe(), Character::set_mutation(), t_fungus, item::tname(), trait_M_BLOOM, trait_M_BLOSSOMS, trait_M_FERTILE, trait_M_SPORES, trait_MUTAGEN_AVOID, trait_THRESH_MARLOSS, trait_THRESH_MYCUS, Character::unset_mutation(), and Character::vomit().
Referenced by mutagen_common_checks().
Variable Documentation
ACT_TREE_COMMUNION
const activity_id ACT_TREE_COMMUNION("ACT_TREE_COMMUNION") ("ACT_TREE_COMMUNION") static
Referenced by Character::activate_mutation().
effect_accumulated_mutagen
const efftype_id effect_accumulated_mutagen("accumulated_mutagen") ("accumulated_mutagen") static
Referenced by Character::mutate().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by test_crossing_threshold().
trait_BURROW
const trait_id trait_BURROW("BURROW") ("BURROW") static
Referenced by Character::activate_mutation().
trait_CARNIVORE
const trait_id trait_CARNIVORE("CARNIVORE") ("CARNIVORE") static
Referenced by test_crossing_threshold().
trait_CHAOTIC_BAD
const trait_id trait_CHAOTIC_BAD("CHAOTIC_BAD") ("CHAOTIC_BAD") static
Referenced by Character::mutate_category(), Character::mutation_chances(), and Character::old_mutate().
trait_DEBUG_BIONIC_POWER
const trait_id trait_DEBUG_BIONIC_POWER("DEBUG_BIONIC_POWER") ("DEBUG_BIONIC_POWER") static
Referenced by Character::activate_mutation().
trait_DEBUG_BIONIC_POWERGEN
const trait_id trait_DEBUG_BIONIC_POWERGEN("DEBUG_BIONIC_POWERGEN") ("DEBUG_BIONIC_POWERGEN") static
Referenced by Character::activate_mutation().
trait_DEX_ALPHA
const trait_id trait_DEX_ALPHA("DEX_ALPHA") ("DEX_ALPHA") static
Referenced by Character::mutation_effect(), and Character::mutation_loss_effect().
trait_GLASSJAW
const trait_id trait_GLASSJAW("GLASSJAW") ("GLASSJAW") static
Referenced by Character::mutation_effect(), and Character::mutation_loss_effect().
trait_INT_ALPHA
const trait_id trait_INT_ALPHA("INT_ALPHA") ("INT_ALPHA") static
Referenced by Character::mutation_effect(), and Character::mutation_loss_effect().
trait_INT_SLIME
const trait_id trait_INT_SLIME("INT_SLIME") ("INT_SLIME") static
Referenced by Character::mutation_effect(), and Character::mutation_loss_effect().
trait_M_BLOOM
const trait_id trait_M_BLOOM("M_BLOOM") ("M_BLOOM") static
Referenced by Character::activate_mutation(), and try_reject_mutagen().
trait_M_BLOSSOMS
const trait_id trait_M_BLOSSOMS("M_BLOSSOMS") ("M_BLOSSOMS") static
Referenced by try_reject_mutagen().
trait_M_FERTILE
const trait_id trait_M_FERTILE("M_FERTILE") ("M_FERTILE") static
Referenced by Character::activate_mutation(), and try_reject_mutagen().
trait_M_PROVENANCE
const trait_id trait_M_PROVENANCE("M_PROVENANCE") ("M_PROVENANCE") static
Referenced by Character::activate_mutation().
trait_M_SPORES
const trait_id trait_M_SPORES("M_SPORES") ("M_SPORES") static
Referenced by try_reject_mutagen().
trait_MUTAGEN_AVOID
const trait_id trait_MUTAGEN_AVOID("MUTAGEN_AVOID") ("MUTAGEN_AVOID") static
Referenced by try_reject_mutagen().
trait_NAUSEA
const trait_id trait_NAUSEA("NAUSEA") ("NAUSEA") static
Referenced by Character::activate_mutation().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by test_crossing_threshold().
trait_PER_ALPHA
const trait_id trait_PER_ALPHA("PER_ALPHA") ("PER_ALPHA") static
Referenced by Character::mutation_effect(), and Character::mutation_loss_effect().
trait_ROBUST
const trait_id trait_ROBUST("ROBUST") ("ROBUST") static
Referenced by Character::mutate_category(), and Character::old_mutate().
trait_ROOTS2
const trait_id trait_ROOTS2("ROOTS2") ("ROOTS2") static
Referenced by Character::activate_mutation().
trait_ROOTS3
const trait_id trait_ROOTS3("ROOTS3") ("ROOTS3") static
Referenced by Character::activate_mutation().
trait_SELFAWARE
const trait_id trait_SELFAWARE("SELFAWARE") ("SELFAWARE") static
Referenced by Character::activate_mutation().
trait_SLIMESPAWNER
const trait_id trait_SLIMESPAWNER("SLIMESPAWNER") ("SLIMESPAWNER") static
Referenced by Character::activate_mutation().
trait_STR_ALPHA
const trait_id trait_STR_ALPHA("STR_ALPHA") ("STR_ALPHA") static
Referenced by Character::mutation_effect(), and Character::mutation_loss_effect().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by try_reject_mutagen().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by try_reject_mutagen().
trait_TREE_COMMUNION
const trait_id trait_TREE_COMMUNION("TREE_COMMUNION") ("TREE_COMMUNION") static
Referenced by Character::activate_mutation().
trait_VOMITOUS
const trait_id trait_VOMITOUS("VOMITOUS") ("VOMITOUS") static
Referenced by Character::activate_mutation().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by Character::activate_mutation().