Cataclysm BN: src/mutation_ui.cpp File Reference
mutation_ui.cpp File Reference
#include "mutation_ui.h"
#include <algorithm>
#include <cstddef>
#include <memory>
#include <unordered_map>
#include "character.h"
#include "enums.h"
#include "input.h"
#include "inventory.h"
#include "mutation.h"
#include "output.h"
#include "popup.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "ui_manager.h"
#include "value_ptr.h"
Enumerations
enum class mutation_menu_mode { activating , examining , reassigning }
enum class mutation_tab_mode { active , passive , none }
Functions
static void draw_exam_window (const catacurses::window &win, const int border_y)
static trait_id GetTrait (std::vector< trait_id > active, std::vector< trait_id > passive, int cursor, mutation_tab_mode tab_mode)
static void show_mutations_titlebar (const catacurses::window &window, const mutation_menu_mode menu_mode, const input_context &ctxt)
static cata::optional< trait_id > trait_by_invlet (const mutation_collection &mutations, int ch)
void show_mutations_ui (Character &who)
Variables
const invlet_wrapper mutation_chars ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\"#&()*+./:;@[\\]^_{|}")
const auto shortcut_desc
Enumeration Type Documentation
mutation_menu_mode
enum class mutation_menu_mode strong
Enumerator
activating
examining
reassigning
Definition at line 38 of file mutation_ui.cpp.
{
    activating,
    examining,
    reassigning,
};
mutation_tab_mode
enum class mutation_tab_mode strong
Enumerator
active
passive
none
Definition at line 43 of file mutation_ui.cpp.
{
    active,
    passive,
    none
};
Function Documentation
draw_exam_window()
static void draw_exam_window (const catacurses::window & win, const int border_y) static
Definition at line 25 of file mutation_ui.cpp.
{
    const int width = getmaxx( win );
    mvwputch( win, point( 0, border_y ), BORDER_COLOR, LINE_XXXO );
    mvwhline( win, point( 1, border_y ), LINE_OXOX, width - 2 );
    mvwputch( win, point( width - 1, border_y ), BORDER_COLOR, LINE_XOXX );
}
References BORDER_COLOR, catacurses::getmaxx(), LINE_OXOX, LINE_XOXX, LINE_XXXO, catacurses::mvwhline(), and mvwputch().
Referenced by detail::show_mutations_ui_internal().
GetTrait()
static trait_id GetTrait (std::vector< trait_id > active, std::vector< trait_id > passive, int cursor, mutation_tab_mode tab_mode) static
Definition at line 50 of file mutation_ui.cpp.
{
    trait_id mut_id;
    if( tab_mode == mutation_tab_mode::active ) {
        mut_id = active[cursor];
    } else {
        mut_id = passive[cursor];
    }
    return mut_id;
}
References active, and passive.
Referenced by detail::show_mutations_ui_internal().
show_mutations_titlebar()
static void show_mutations_titlebar (const catacurses::window & window, const mutation_menu_mode menu_mode, const input_context & ctxt) static
Definition at line 62 of file mutation_ui.cpp.
{
    werase( window );
    std::string desc;
    if( menu_mode == mutation_menu_mode::reassigning ) {
        desc += std::string( _( "Reassigning." ) ) + "  " +
                _( "Select a mutation to reassign or press [<color_yellow>SPACE</color>] to cancel. " );
    }
    if( menu_mode == mutation_menu_mode::activating ) {
        desc += colorize( _( "Activating" ),
                          c_green ) + "  " + shortcut_desc( _( "%s to examine mutation, " ),
                                  ctxt.get_desc( "TOGGLE_EXAMINE" ) );
    }
    if( menu_mode == mutation_menu_mode::examining ) {
        desc += colorize( _( "Examining" ),
                          c_light_blue ) + "  " + shortcut_desc( _( "%s to activate mutation, " ),
                                  ctxt.get_desc( "TOGGLE_EXAMINE" ) );
    }
    if( menu_mode != mutation_menu_mode::reassigning ) {
        desc += shortcut_desc( _( "%s to reassign invlet, " ), ctxt.get_desc( "REASSIGN" ) );
    }
    desc += shortcut_desc( _( "%s to change keybindings." ), ctxt.get_desc( "HELP_KEYBINDINGS" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    fold_and_print( window, point( 1, 0 ), getmaxx( window ) - 1, c_white, desc );
    wnoutrefresh( window );
}
References _, activating, c_green, c_light_blue, c_white, colorize(), examining, fold_and_print(), input_context::get_desc(), catacurses::getmaxx(), reassigning, shortcut_desc, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by detail::show_mutations_ui_internal().
show_mutations_ui()
void show_mutations_ui (Character & who)
Definition at line 100 of file mutation_ui.cpp.
{
    if( !who.is_avatar() ) {
        // TODO: Implement NPCs activating mutations
        return;
    }
    // Mutation selection UI obscures the terrain,
    // but some mutations may ask to select a tile when activated.
    // As such, we must (de-)activate only after destroying the UI.
    detail::mutations_ui_result res = detail::show_mutations_ui_internal( who );
    switch( res.cmd ) {
        case detail::mutations_ui_cmd::exit:
            break;
        case detail::mutations_ui_cmd::deactivate:
            who.deactivate_mutation( res.mut );
            break;
        case detail::mutations_ui_cmd::activate:
            who.activate_mutation( res.mut );
            break;
    }
}
References detail::activate, Character::activate_mutation(), detail::mutations_ui_result::cmd, detail::deactivate, Character::deactivate_mutation(), detail::exit, Creature::is_avatar(), detail::mutations_ui_result::mut, and detail::show_mutations_ui_internal().
Referenced by game::handle_action().
trait_by_invlet()
static cata::optional< trait_id > trait_by_invlet (const mutation_collection & mutations, int ch) static
Definition at line 90 of file mutation_ui.cpp.
{
    for( const std::pair<const trait_id, char_trait_data> &mut : mutations ) {
        if( mut.second.key == ch ) {
            return mut.first;
        }
    }
    return cata::nullopt;
}
References cata::nullopt.
Referenced by detail::show_mutations_ui_internal().
Variable Documentation
mutation_chars
const invlet_wrapper mutation_chars("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\"#&()*+./:;@[\\]^_{|}") ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\"#&()*+./:;@^_{|}" [\\])
Referenced by detail::show_mutations_ui_internal().
shortcut_desc
const auto shortcut_desc
Initial value:
= [](const std::string &comment, const std::string &keys)
{
    return string_format( comment, string_format( "[<color_yellow>%s</color>]", keys ) );
}
Definition at line 33 of file mutation_ui.cpp.
Referenced by show_mutations_titlebar().