Cataclysm BN: newcharacter Namespace Reference
newcharacter Namespace Reference
Functions
bool has_conflicting_trait (const Character &ch, const trait_id &t)
Returns true if character has a conflicting trait to the entered trait.
bool has_lower_trait (const Character &ch, const trait_id &t)
Returns true if charcater has a trait which upgrades into the entered trait.
bool has_higher_trait (const Character &ch, const trait_id &t)
Returns true if character has a trait which is an upgrade of the entered trait.
bool has_same_type_trait (const Character &ch, const trait_id &t)
Returns true if character has a trait that shares a type with the entered trait.
trait_id random_good_trait ()
Returns the id of a random starting trait that costs >= 0 points.
trait_id random_bad_trait ()
Returns the id of a random starting trait that costs < 0 points.
void add_traits (Character &ch)
Adds mandatory scenario and profession traits unless character already has them.
void add_traits (Character &ch, points_left &points)
Function Documentation
add_traits() [1/2]
void newcharacter::add_traits (Character & ch)
Adds mandatory scenario and profession traits unless character already has them.
And if they do, refunds the points.
Definition at line 2900 of file newcharacter.cpp.
{
    points_left points = points_left();
    add_traits( ch, points );
}
References add_traits().
Referenced by add_traits(), avatar::randomize(), reset_scenario(), and set_profession().
add_traits() [2/2]
void newcharacter::add_traits (Character & ch, points_left & points)
Definition at line 2906 of file newcharacter.cpp.
{
    for( const trait_id &tr : ch.prof->get_locked_traits() ) {
        if( !ch.has_trait( tr ) ) {
            ch.toggle_trait( tr );
        } else {
            points.trait_points += tr->points;
        }
    }
    for( const trait_id &tr : g->scen->get_locked_traits() ) {
        if( !ch.has_trait( tr ) ) {
            ch.toggle_trait( tr );
        }
    }
}
References g, profession::get_locked_traits(), Character::has_trait(), Character::prof, Character::toggle_trait(), and points_left::trait_points.
has_conflicting_trait()
bool newcharacter::has_conflicting_trait (const Character & ch, const trait_id & t)
Returns true if character has a conflicting trait to the entered trait.
Definition at line 3173 of file newcharacter.cpp.
{
    return ch.has_opposite_trait( t ) ||
           has_lower_trait( ch, t ) ||
           has_higher_trait( ch, t ) ||
           has_same_type_trait( ch, t ) ;
}
References has_higher_trait(), has_lower_trait(), Character::has_opposite_trait(), and has_same_type_trait().
Referenced by avatar::randomize(), and set_traits().
has_higher_trait()
bool newcharacter::has_higher_trait (const Character & ch, const trait_id & t)
Returns true if character has a trait which is an upgrade of the entered trait.
Definition at line 3191 of file newcharacter.cpp.
{
    for( const trait_id &it : t->replacements ) {
        if( ch.has_trait( it ) || has_higher_trait( ch, it ) ) {
            return true;
        }
    }
    return false;
}
References has_higher_trait(), Character::has_trait(), and mutation_branch::replacements.
Referenced by has_conflicting_trait(), and has_higher_trait().
has_lower_trait()
bool newcharacter::has_lower_trait (const Character & ch, const trait_id & t)
Returns true if charcater has a trait which upgrades into the entered trait.
Definition at line 3181 of file newcharacter.cpp.
{
    for( const trait_id &it : t->prereqs ) {
        if( ch.has_trait( it ) || has_lower_trait( ch, it ) ) {
            return true;
        }
    }
    return false;
}
References has_lower_trait(), Character::has_trait(), and mutation_branch::prereqs.
Referenced by has_conflicting_trait(), and has_lower_trait().
has_same_type_trait()
bool newcharacter::has_same_type_trait (const Character & ch, const trait_id & t)
Returns true if character has a trait that shares a type with the entered trait.
Definition at line 3201 of file newcharacter.cpp.
{
    for( const trait_id &it : get_mutations_in_types( t->types ) ) {
        if( ch.has_trait( it ) && t != it ) {
            return true;
        }
    }
    return false;
}
References get_mutations_in_types(), Character::has_trait(), and mutation_branch::types.
Referenced by has_conflicting_trait().
random_bad_trait()
trait_id newcharacter::random_bad_trait ()
Returns the id of a random starting trait that costs < 0 points.
Definition at line 2935 of file newcharacter.cpp.
{
    std::vector<trait_id> vTraitsBad;
    for( auto &traits_iter : mutation_branch::get_all() ) {
        if( traits_iter.points < 0 && g->scen->traitquery( traits_iter.id ) ) {
            vTraitsBad.push_back( traits_iter.id );
        }
    }
    return random_entry( vTraitsBad );
}
References g, mutation_branch::get_all(), and random_entry().
Referenced by avatar::randomize().
random_good_trait()
trait_id newcharacter::random_good_trait ()
Returns the id of a random starting trait that costs >= 0 points.
Definition at line 2922 of file newcharacter.cpp.
{
    std::vector<trait_id> vTraitsGood;
    for( auto &traits_iter : mutation_branch::get_all() ) {
        if( traits_iter.points >= 0 && g->scen->traitquery( traits_iter.id ) ) {
            vTraitsGood.push_back( traits_iter.id );
        }
    }
    return random_entry( vTraitsGood );
}
References g, mutation_branch::get_all(), and random_entry().
Referenced by avatar::randomize().