Cataclysm BN: cata Namespace Reference
cata Namespace Reference
Namespaces
namespace event_detail
namespace hash64_detail
namespace tuple_hash_detail
Classes
struct auto_hash
struct auto_hash< std::pair< T, U > >
struct auto_hash< std::tuple< T... > >
class bad_optional_access
class clone_ptr
class colony
class event
class flat_set
A SimpleAssociativeContainer implemented as a sorted vector.
struct in_place_t
struct is_instance_of
struct is_instance_of< TMPL< T >, TMPL >
class list
struct nullopt_t
class optional
class poly_serialized
Copyable unique_ptr that writes and reads objects of derived types.
struct range_hash
class string_formatter
Type-safe and undefined-behavior free wrapper over sprintf.
struct transparent_less_than
struct tuple_hash
class value_ptr
This class is essentially a copyable unique pointer.
Typedefs
template<typename... >
using void_t = void
template<typename T >
using is_numeric = typename std::conditional< std::is_arithmetic< typename std::decay< T >::type >::value &&!std::is_same< typename std::decay< T >::type, bool >::value, std::true_type, std::false_type >::type
template<typename T >
using is_integer = typename std::conditional< is_numeric< T >::value &&!std::is_floating_point< typename std::decay< T >::type >::value, std::true_type, std::false_type >::type
template<typename T >
using is_char = typename std::conditional< std::is_same< typename std::decay< T >::type, char >::value, std::true_type, std::false_type >::type
template<typename T >
using is_string = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string >::value, std::true_type, std::false_type >::type
template<typename T >
using is_string_view = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string_view >::value, std::true_type, std::false_type >::type
template<typename T >
using is_cstring = typename std::conditional< std::is_same< typename std::decay< T >::type, const char * >::value||std::is_same< typename std::decay< T >::type, char * >::value, std::true_type, std::false_type >::type
template<typename T >
using is_translation = typename std::conditional< std::is_same< typename std::decay< T >::type, translation >::value, std::true_type, std::false_type >::type
template<typename T >
using is_string_id = typename std::conditional< is_instance_of< typename std::decay< T >::type, string_id >::value, std::true_type, std::false_type >::type
Functions
template<typename Iterator , typename RatingFunction >
void sort_by_rating (Iterator begin, Iterator end, RatingFunction rating_func)
Sort elements of a sequence by their rating (the smaller the better).
template<typename T >
void find_cycles_impl (const std::unordered_map< T, std::vector< T > > &edges, const T &v, std::unordered_set< T > &visited, std::unordered_map< T, T > &on_current_branch, std::vector< std::vector< T > > &result)
template<typename T >
std::vector< std::vector< T > > find_cycles (const std::unordered_map< T, std::vector< T > > &edges)
void unreachable ()
Marks unreachable code.
template<class element_type , class element_allocator_type , typename element_skipfield_type >
void swap (colony< element_type, element_allocator_type, element_skipfield_type > &a, colony< element_type, element_allocator_type, element_skipfield_type > &b) COLONY_NOEXCEPT_SWAP(element_allocator_type)
Swaps colony A's contents with that of colony B.
template<event_type Type>
static void get_fields_if_match (event_type type, event::fields_type &out)
template<int... I>
static event::fields_type get_fields_helper (event_type type, std::integer_sequence< int, I... >)
template<class T , typename Hash = std::hash<T>>
void hash_combine (std::size_t &seed, const T &v, const Hash &hash=std::hash< T >())
std::size_t hash64 (std::uint64_t val)
template<class swap_element_type , class swap_element_allocator_type >
void swap (list< swap_element_type, swap_element_allocator_type > &a, list< swap_element_type, swap_element_allocator_type > &b) LIST_NOEXCEPT_SWAP(swap_element_allocator_type)
template<class T , class U >
constexpr bool operator== (const optional< T > &lhs, const optional< U > &rhs)
template<class T , class U >
constexpr bool operator!= (const optional< T > &lhs, const optional< U > &rhs)
template<class T , class... Args>
poly_serialized< T > make_poly_serialized (Args &&...args)
void throw_error (const string_formatter &, const std::string &)
std::string_view string_formatter_set_temp_buffer (const string_formatter &, std::string_view)
std::string handle_string_format_error ()
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&is_integer< T >::value, RT >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&std::is_enum< typenamestd::decay< T >::type >::value, RT >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_floating_point< RT >::value &&is_numeric< T >::value &&!is_integer< T >::value, RT >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, void * >::value &&std::is_pointer< typenamestd::decay< T >::type >::value, void * >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_string< T >::value, std::string_view >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_view< T >::value, std::string_view >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_cstring< T >::value, std::string_view >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_translation< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_id< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&!is_char< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&is_char< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
RT convert (RT *, const string_formatter &sf, T &&,...)
template<class T , class... Args>
value_ptr< T > make_value (Args &&...args)
template<class T >
bool value_ptr_equals (const value_ptr< T > &lhs, const value_ptr< T > &rhs)
Variables
static constexpr nullopt_t nullopt { 0 }
static constexpr in_place_t in_place { }
Typedef Documentation
void_t
template<typename... > using cata::void_t = typedef void
Definition at line 10 of file cata_void.h.
Function Documentation
convert() [1/10]
template<typename RT , typename T > std::enable_if< is_integer< RT >::value &&std::is_enum< typenamestd::decay< T >::type >::value, RT >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 105 of file string_formatter.h.
{
    return static_cast<RT>( value );
}
convert() [2/10]
template<typename RT , typename T > std::enable_if< std::is_floating_point< RT >::value &&is_numeric< T >::value &&!is_integer< T >::value, RT >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 111 of file string_formatter.h.
{
    return value;
}
convert() [3/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, void * >::value &&std::is_pointer< typenamestd::decay< T >::type >::value, void * >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 117 of file string_formatter.h.
{
    return const_cast<typename std::remove_const<typename std::remove_pointer<typename std::decay<T>::type>::type>::type *>
           ( value );
}
References type.
convert() [4/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_string< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 125 of file string_formatter.h.
{
    return value;
}
convert() [5/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_view< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 132 of file string_formatter.h.
{
    return value;
}
convert() [6/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_cstring< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 138 of file string_formatter.h.
{
    return value;
}
convert() [7/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_translation< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 145 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, value.translated() );
}
References string_formatter_set_temp_buffer().
convert() [8/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_id< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 151 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, value.str() );
}
References string_formatter_set_temp_buffer().
convert() [9/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&!is_char< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 157 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, std::to_string( value ) );
}
References string_formatter_set_temp_buffer(), and to_string().
convert() [10/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&is_char< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 164 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, std::string( 1, value ) );
}
References string_formatter_set_temp_buffer().
find_cycles()
template<typename T > std::vector< std::vector< T > > cata::find_cycles (const std::unordered_map< T, std::vector< T > > & edges)
Definition at line 105 of file cata_algo.h.
{
    std::unordered_set<T> visited;
    std::unordered_map<T, T> on_current_branch;
    std::vector<std::vector<T>> result;
    for( const auto &p : edges ) {
        const T &root = p.first;
        on_current_branch.emplace( root, root );
        find_cycles_impl( edges, root, visited, on_current_branch, result );
        on_current_branch.erase( root );
        assert( on_current_branch.empty() );
    }
    return result;
}
References find_cycles_impl().
Referenced by recipe_dictionary::find_items_on_loops().
find_cycles_impl()
template<typename T > void cata::find_cycles_impl (const std::unordered_map< T, std::vector< T > > & edges, const T & v, std::unordered_set< T > & visited, std::unordered_map< T, T > & on_current_branch, std::vector< std::vector< T > > & result)
Definition at line 50 of file cata_algo.h.
{
    bool new_vertex = visited.insert( v ).second;
    if( !new_vertex ) {
        return;
    }
    auto it = edges.find( v );
    if( it == edges.end() ) {
        return;
    }
    for( const T &next_v : it->second ) {
        if( next_v == v ) {
            // Trivial self-loop
            result.push_back( { v } );
            continue;
        }
        auto previous_match = on_current_branch.find( next_v );
        if( previous_match != on_current_branch.end() ) {
            // We have looped back to somewhere along the branch we took to
            // reach this vertex, so reconstruct the loop and save it.
            std::vector<T> loop;
            T on_path = v;
            while( true ) {
                loop.push_back( on_path );
                if( on_path == next_v ) {
                    break;
                }
                on_path = on_current_branch[on_path];
            }
            std::reverse( loop.begin(), loop.end() );
            result.push_back( loop );
        } else {
            on_current_branch.emplace( next_v, v );
            find_cycles_impl( edges, next_v, visited, on_current_branch, result );
            on_current_branch.erase( next_v );
        }
    }
}
References find_cycles_impl().
Referenced by find_cycles(), and find_cycles_impl().
get_fields_helper()
template<int... I> static event::fields_type cata::get_fields_helper (event_type type, std::integer_sequence< int, I... >) static
Definition at line 154 of file event.cpp.
{
    event::fields_type result;
    bool discard[] = {
        ( get_fields_if_match<static_cast<event_type>( I )>( type, result ), true )...
    };
    ( void ) discard;
    return result;
}
References type.
Referenced by cata::event::get_fields().
get_fields_if_match()
template<event_type Type> static void cata::get_fields_if_match (event_type type, event::fields_type & out) static
Definition at line 143 of file event.cpp.
{
    if( Type == type ) {
        out = { event_detail::event_spec<Type>::fields.begin(),
                event_detail::event_spec<Type>::fields.end()
              };
    }
}
References type.
handle_string_format_error()
std::string cata::handle_string_format_error ()
Definition at line 120 of file string_formatter.cpp.
{
    try {
        throw;
    } catch( const std::exception &err ) {
        return err.what();
    }
}
Referenced by string_format().
hash64()
std::size_t cata::hash64 (std::uint64_t val) inline
Definition at line 112 of file hash_utils.h.
{
    return hash64_detail::maybe_mix_bits<std::size_t>( val );
}
Referenced by node_address_hasher::operator()().
hash_combine()
template<class T , typename Hash = std::hash<T>> void cata::hash_combine (std::size_t & seed, const T & v, const Hash & hash = std::hash<T>()) inline
Definition at line 19 of file hash_utils.h.
{
    seed ^= hash( v ) + 0x9e3779b9 + ( seed << 6 ) + ( seed >> 2 );
}
References iuse::seed().
Referenced by cata::tuple_hash_detail::Impl< Tuple, Index >::apply(), cata::tuple_hash_detail::Impl< Tuple, 0 >::apply(), mongroup_hash::operator()(), cata::range_hash::operator()(), and cata::tuple_hash::operator()().
make_poly_serialized()
template<class T , class... Args> poly_serialized< T > cata::make_poly_serialized (Args &&... args)
Definition at line 61 of file poly_serialized.h.
{
    return poly_serialized<T>( new T( std::forward<Args>( args )... ) );
}
make_value()
template<class T , class... Args> value_ptr< T > cata::make_value (Args &&... args)
Definition at line 51 of file value_ptr.h.
{
    return value_ptr<T>( new T( std::forward<Args>( args )... ) );
}
operator!=()
template<class T , class U > constexpr bool cata::operator!= (const optional< T > & lhs, const optional< U > & rhs) constexpr
Definition at line 253 of file optional.h.
{
    return !operator==( lhs, rhs );
}
References operator==().
operator==()
template<class T , class U > constexpr bool cata::operator== (const optional< T > & lhs, const optional< U > & rhs) constexpr
Definition at line 241 of file optional.h.
{
    if( lhs.has_value() != rhs.has_value() ) {
        return false;
    } else if( !lhs ) {
        return true;
    } else {
        return *lhs == *rhs;
    }
}
References cata::optional< T >::has_value().
Referenced by operator!=().
sort_by_rating()
template<typename Iterator , typename RatingFunction > void cata::sort_by_rating (Iterator begin, Iterator end, RatingFunction rating_func)
Sort elements of a sequence by their rating (the smaller the better).
Parameters
begin An input/output iterator.
end An input/output iterator.
rating_func A functor which calculates ratings (the outcome must be comparable using '<' operator).
The rating is calculated only once per each element.
Definition at line 25 of file cata_algo.h.
{
    using value_t = typename Iterator::value_type;
    using pair_t = std::pair<value_t, decltype( rating_func( *begin ) )>;
    std::vector<pair_t> rated_entries;
    rated_entries.reserve( std::distance( begin, end ) );
    std::transform( begin, end, std::back_inserter( rated_entries ),
    [ &rating_func ]( const value_t &elem ) {
        return std::make_pair( elem, rating_func( elem ) );
    } );
    std::sort( rated_entries.begin(), rated_entries.end(), []( const pair_t &lhs, const pair_t &rhs ) {
        return lhs.second < rhs.second;
    } );
    std::transform( rated_entries.begin(), rated_entries.end(), begin, []( const pair_t &elem ) {
        return elem.first;
    } );
}
References iexamine::transform().
Referenced by npc::move_away_from().
string_formatter_set_temp_buffer()
std::string_view cata::string_formatter_set_temp_buffer (const string_formatter & , std::string_view)
This is used for printing non-strings through "%s". It only works because this prints each format specifier separately, so the content of temp_buffer is only used once.
Definition at line 264 of file string_formatter.h.
{
            sf.temp_buffer = text;
            return std::string_view( sf.temp_buffer );
        }
Referenced by convert().
swap() [1/2]
template<class element_type , class element_allocator_type , typename element_skipfield_type > void cata::swap (colony< element_type, element_allocator_type, element_skipfield_type > & a, colony< element_type, element_allocator_type, element_skipfield_type > & b) inline
Swaps colony A's contents with that of colony B.
Assumes both colonies have same element type, allocator type, etc.
Definition at line 3496 of file colony.h.
{
    a.swap( b );
}
Referenced by approx_orientation(), assign(), closest_points_first(), consolidate(), vehicle::coord_translate(), vehicle::coord_translate_reverse(), vehicle::damage_all(), draw_speed_tab(), draw_square(), detail::fallback_uintptr::fallback_uintptr(), Item_factory::finalize_pre(), CellularAutomata::generate_cellular_automaton(), item::io(), mutation_branch::load(), editmap::mapgen_preview(), monexamine::mfriend_menu(), monexamine::pet_menu(), rng(), rng_float(), rng_normal(), map::rotate(), auto_pickup::user_interface::show(), Messages::dialog::show(), safemode::show(), panel_manager::show_adm(), show_bionics_ui(), detail::show_mutations_ui_internal(), cata::list< element_type, element_allocator_type >::splice(), cata::optional< T >::swap(), zone_manager::swap(), advanced_inventory::swap_panes(), maptile_soa< sx, sy >::swap_soa_tile(), and Character::update_fuel_storage().
swap() [2/2]
template<class swap_element_type , class swap_element_allocator_type > void cata::swap (list< swap_element_type, swap_element_allocator_type > & a, list< swap_element_type, swap_element_allocator_type > & b) inline
Definition at line 2446 of file list.h.
{
    a.swap( b );
}
throw_error()
void cata::throw_error (const string_formatter & , const std::string &)
Definition at line 257 of file string_formatter.h.
{
            sf.throw_error( msg );
        }
Referenced by convert(), and cata::string_formatter::read_number_or_argument_index().
unreachable()
void cata::unreachable () inline
Marks unreachable code.
Utility function to mark unreachable code to help compiler with optimizations.
Usage: void (bool always_true) { if (always_true) { return; } else { // If always_true happens to be false, this will cause Undefined Behavior. cata::unreachable(); } }
Source: https://stackoverflow.com/a/65258501
Definition at line 37 of file cata_unreachable.h.
{}
Referenced by cast_zlight_segment(), castLight(), and relic_funcs::check_recharge_reqs().
value_ptr_equals()
template<class T > bool cata::value_ptr_equals (const value_ptr< T > & lhs, const value_ptr< T > & rhs)
Definition at line 57 of file value_ptr.h.
{
    return ( !lhs && !rhs ) || ( lhs && rhs && *lhs == *rhs );
}
Referenced by translation::operator==().
Variable Documentation
in_place
constexpr in_place_t cata::in_place { } static constexpr
Definition at line 27 of file optional.h.
nullopt
constexpr nullopt_t cata::nullopt { 0 } static constexpr
Definition at line 22 of file optional.h.
Referenced by mission_data::add(), vehicle::add_item(), snippet_library::add_snippet_from_json(), snippet_library::add_snippets_from_json(), choose_adjacent(), choose_adjacent_highlight(), choose_direction(), teleporter_list::choose_teleport_location(), Character::clear_destination(), snippet_library::clear_snippets(), vehicle::autodrive_controller::compute_next_step(), vehicle::autodrive_controller::compute_path(), debug_menu::debug(), pickup_activity_actor::deserialize(), npc::die(), editmap::edit(), npc::execute_action(), overmap::find_camp(), overmapbuffer::find_camp(), find_empty_spot_nearby(), find_food_heater(), find_or_create_om_terrain(), game::find_or_make_stairs(), ter_furn_transform::find_transform(), find_valid_teleporters_omt(), options_manager::cOpt::findInt(), skill_boost::get(), overmap_ui::grids_draw_data::get_active(), basecamp::get_available_missions_by_dir(), get_basecamp(), item::get_cable_target(), input_context::get_coordinates(), input_context::get_direction(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_hack_type(), overmap_ui::grids_draw_data::get_inactive(), vpart_position::get_label(), optional_vpart_position::get_label(), npc::get_mission_destination(), zone_manager::get_nearest(), Character::get_npc_ai_info_cache(), player_activity::get_progress_message(), snippet_library::get_snippet_by_id(), game::get_veh_dir_indicator_location(), iexamine::getGasPumpByNumber(), npc::go_to_omt_destination(), pf::greedy_path(), game::handle_action(), overmapbuffer::has_note_with_danger_radius(), overmap::has_note_with_danger_radius(), avatar::kill_xp_for_next_point(), game::list_items(), game::list_monsters(), islot_ammo::load(), fake_spell::load(), item_category::load(), mutation_branch::load(), fault::load_fault(), mod_management::load_mod_list(), mod_management::load_modfile(), snippet_library::load_snippet(), game::look_around(), advanced_inventory::move_all_items(), npc::mutiny(), nearest_passable(), ter_furn_transform::next(), npc::npc(), npc_throw(), vpart_position::obstacle_at_part(), optional_vpart_position::obstacle_at_part(), vpart_position::part_displayed(), optional_vpart_position::part_displayed(), vpart_position::part_with_feature(), optional_vpart_position::part_with_feature(), ter_furn_data< T >::pick(), overmap_ui::grids_draw_data::pick_char(), pickup::pick_up(), point_selection_menu(), press_x_if_bound(), item_category::priority_zone(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_body_part(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration(), query_for_template_name(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), random_entry_opt(), snippet_library::random_from_category(), spell::random_valid_target(), Character::reach_attack(), cata::string_formatter::read_argument_index(), cata::string_formatter::read_number_or_argument_index(), cata::string_formatter::read_precision(), npc::reboot(), iexamine::reload_furniture(), basecamp::remove_assignee(), vehicle::remove_old_owner(), activity_handlers::repair_item_finish(), npc::reset_companion_mission(), detail::show_mutations_ui_internal(), advanced_inventory::start_activity(), talk_function::stop_guard(), ranged::throw_item(), game::debug_hour_timer::toggle(), trait_by_invlet(), iexamine::tree_maple_tapped(), debug_menu::anonymous_namespace{wisheffect.cpp}::try_read_time_string(), ui_adaptor::ui_adaptor(), map::veh_at(), game::walk_move(), Character::wear_item(), Character::wear_possessed(), npc::worker_downtime(), and game::zones_manager().