Cataclysm BN: dreams Namespace Reference
dreams Namespace Reference
Functions
void load (const JsonObject &jo)
void clear ()
std::string get_random_for_category (const std::string &cat, int strength)
Returns a random dream description that matches given category and strength.
Function Documentation
clear()
void dreams::clear ()
Definition at line 669 of file mutation_data.cpp.
{
    all_dreams.clear();
}
References all_dreams.
Referenced by DynamicDataLoader::unload_data().
get_random_for_category()
std::string dreams::get_random_for_category (const std::string & cat, int strength)
Returns a random dream description that matches given category and strength.
Definition at line 674 of file mutation_data.cpp.
{
    std::vector<const dream *> valid_dreams;
    for( const dream &d : all_dreams ) {
        if( ( d.category == cat ) && ( d.strength == strength ) ) {
            valid_dreams.push_back( &d );
        }
    }
    if( valid_dreams.empty() ) {
        return "";
    }
    const dream *selected_dream = random_entry( valid_dreams );
    return random_entry( selected_dream->messages ).translated();
}
References all_dreams, dream::messages, and random_entry().
Referenced by Character::hardcoded_effects().
load()
void dreams::load (const JsonObject & jo)
Definition at line 658 of file mutation_data.cpp.
{
    dream newdream;
    jo.read( "strength", newdream.strength );
    jo.read( "category", newdream.category );
    jo.read( "messages", newdream.messages );
    all_dreams.push_back( newdream );
}
References all_dreams, dream::category, dream::messages, JsonObject::read(), and dream::strength.
Referenced by DynamicDataLoader::initialize().