Cataclysm BN: field_types Namespace Reference
field_types Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize_all ()
void check_consistency ()
void reset ()
const std::vector< field_type > & get_all ()
void set_field_type_ids ()
field_type get_field_type_by_legacy_enum (int legacy_enum_id)
Function Documentation
check_consistency()
void field_types::check_consistency ()
Definition at line 320 of file field_type.cpp.
{
    all_field_types.check();
}
References anonymous_namespace{field_type.cpp}::all_field_types.
Referenced by DynamicDataLoader::check_consistency().
finalize_all()
void field_types::finalize_all ()
Definition at line 311 of file field_type.cpp.
{
    set_field_type_ids();
    all_field_types.finalize();
    for( const field_type &fd : all_field_types.get_all() ) {
        const_cast<field_type &>( fd ).finalize();
    }
}
References anonymous_namespace{field_type.cpp}::all_field_types, behavior::finalize(), and set_field_type_ids().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< field_type > & field_types::get_all ()
Definition at line 330 of file field_type.cpp.
{
    return all_field_types.get_all();
}
References anonymous_namespace{field_type.cpp}::all_field_types.
get_field_type_by_legacy_enum()
field_type field_types::get_field_type_by_legacy_enum (int legacy_enum_id)
Definition at line 446 of file field_type.cpp.
{
    for( const auto &ft : all_field_types.get_all() ) {
        if( legacy_enum_id == ft.legacy_enum_id ) {
            return ft;
        }
    }
    debugmsg( "Cannot find field_type for legacy enum: %d.", legacy_enum_id );
    return field_type();
}
References anonymous_namespace{field_type.cpp}::all_field_types, and debugmsg.
Referenced by submap::load().
load()
void field_types::load (const JsonObject & jo, const std::string & src)
Definition at line 306 of file field_type.cpp.
{
    all_field_types.load( jo, src );
}
References anonymous_namespace{field_type.cpp}::all_field_types.
Referenced by DynamicDataLoader::initialize().
reset()
void field_types::reset ()
Definition at line 325 of file field_type.cpp.
{
    all_field_types.reset();
}
References anonymous_namespace{field_type.cpp}::all_field_types.
Referenced by DynamicDataLoader::unload_data().
set_field_type_ids()
void field_types::set_field_type_ids ()
Definition at line 389 of file field_type.cpp.
{
    fd_null = field_type_id( "fd_null" );
    fd_blood = field_type_id( "fd_blood" );
    fd_bile = field_type_id( "fd_bile" );
    fd_gibs_flesh = field_type_id( "fd_gibs_flesh" );
    fd_gibs_veggy = field_type_id( "fd_gibs_veggy" );
    fd_web = field_type_id( "fd_web" );
    fd_slime = field_type_id( "fd_slime" );
    fd_acid = field_type_id( "fd_acid" );
    fd_sap = field_type_id( "fd_sap" );
    fd_sludge = field_type_id( "fd_sludge" );
    fd_fire = field_type_id( "fd_fire" );
    fd_smoke = field_type_id( "fd_smoke" );
    fd_toxic_gas = field_type_id( "fd_toxic_gas" );
    fd_tear_gas = field_type_id( "fd_tear_gas" );
    fd_nuke_gas = field_type_id( "fd_nuke_gas" );
    fd_gas_vent = field_type_id( "fd_gas_vent" );
    fd_fire_vent = field_type_id( "fd_fire_vent" );
    fd_flame_burst = field_type_id( "fd_flame_burst" );
    fd_electricity = field_type_id( "fd_electricity" );
    fd_fatigue = field_type_id( "fd_fatigue" );
    fd_push_items = field_type_id( "fd_push_items" );
    fd_shock_vent = field_type_id( "fd_shock_vent" );
    fd_acid_vent = field_type_id( "fd_acid_vent" );
    fd_plasma = field_type_id( "fd_plasma" );
    fd_laser = field_type_id( "fd_laser" );
    fd_spotlight = field_type_id( "fd_spotlight" );
    fd_dazzling = field_type_id( "fd_dazzling" );
    fd_blood_veggy = field_type_id( "fd_blood_veggy" );
    fd_blood_insect = field_type_id( "fd_blood_insect" );
    fd_blood_invertebrate = field_type_id( "fd_blood_invertebrate" );
    fd_gibs_insect = field_type_id( "fd_gibs_insect" );
    fd_gibs_invertebrate = field_type_id( "fd_gibs_invertebrate" );
    fd_cigsmoke = field_type_id( "fd_cigsmoke" );
    fd_weedsmoke = field_type_id( "fd_weedsmoke" );
    fd_cracksmoke = field_type_id( "fd_cracksmoke" );
    fd_methsmoke = field_type_id( "fd_methsmoke" );
    fd_bees = field_type_id( "fd_bees" );
    fd_incendiary = field_type_id( "fd_incendiary" );
    fd_relax_gas = field_type_id( "fd_relax_gas" );
    fd_fungal_haze = field_type_id( "fd_fungal_haze" );
    fd_cold_air1 = field_type_id( "fd_cold_air1" );
    fd_cold_air2 = field_type_id( "fd_cold_air2" );
    fd_cold_air3 = field_type_id( "fd_cold_air3" );
    fd_cold_air4 = field_type_id( "fd_cold_air4" );
    fd_hot_air1 = field_type_id( "fd_hot_air1" );
    fd_hot_air2 = field_type_id( "fd_hot_air2" );
    fd_hot_air3 = field_type_id( "fd_hot_air3" );
    fd_hot_air4 = field_type_id( "fd_hot_air4" );
    fd_fungicidal_gas = field_type_id( "fd_fungicidal_gas" );
    fd_insecticidal_gas = field_type_id( "fd_insecticidal_gas" );
    fd_smoke_vent = field_type_id( "fd_smoke_vent" );
    fd_tindalos_rift = field_type_id( "fd_tindalos_rift" );
}
References fd_acid, fd_acid_vent, fd_bees, fd_bile, fd_blood, fd_blood_insect, fd_blood_invertebrate, fd_blood_veggy, fd_cigsmoke, fd_cold_air1, fd_cold_air2, fd_cold_air3, fd_cold_air4, fd_cracksmoke, fd_dazzling, fd_electricity, fd_fatigue, fd_fire, fd_fire_vent, fd_flame_burst, fd_fungal_haze, fd_fungicidal_gas, fd_gas_vent, fd_gibs_flesh, fd_gibs_insect, fd_gibs_invertebrate, fd_gibs_veggy, fd_hot_air1, fd_hot_air2, fd_hot_air3, fd_hot_air4, fd_incendiary, fd_insecticidal_gas, fd_laser, fd_methsmoke, fd_nuke_gas, fd_null, fd_plasma, fd_push_items, fd_relax_gas, fd_sap, fd_shock_vent, fd_slime, fd_sludge, fd_smoke, fd_smoke_vent, fd_spotlight, fd_tear_gas, fd_tindalos_rift, fd_toxic_gas, fd_web, and fd_weedsmoke.
Referenced by finalize_all().