Cataclysm BN: item_internal Namespace Reference
item_internal Namespace Reference
Classes
struct scoped_goes_bad_cache
Functions
bool goes_bad_cache_fetch ()
void goes_bad_cache_set (const item *i)
void goes_bad_cache_unset ()
bool goes_bad_cache_is_for (const item *i)
Variables
bool goes_bad_temp_cache = false
const item * goes_bad_temp_cache_for = nullptr
Function Documentation
goes_bad_cache_fetch()
bool item_internal::goes_bad_cache_fetch () inline
Definition at line 334 of file item.cpp.
{
    return goes_bad_temp_cache;
}
References goes_bad_temp_cache.
Referenced by item::goes_bad().
goes_bad_cache_is_for()
bool item_internal::goes_bad_cache_is_for (const item * i) inline
Definition at line 348 of file item.cpp.
{
    return goes_bad_temp_cache_for == i;
}
References goes_bad_temp_cache_for.
Referenced by item::goes_bad().
goes_bad_cache_set()
void item_internal::goes_bad_cache_set (const item * i) inline
Definition at line 338 of file item.cpp.
{
    goes_bad_temp_cache = i->goes_bad();
    goes_bad_temp_cache_for = i;
}
References item::goes_bad(), goes_bad_temp_cache, and goes_bad_temp_cache_for.
Referenced by item_internal::scoped_goes_bad_cache::scoped_goes_bad_cache().
goes_bad_cache_unset()
void item_internal::goes_bad_cache_unset () inline
Definition at line 343 of file item.cpp.
{
    goes_bad_temp_cache = false;
    goes_bad_temp_cache_for = nullptr;
}
References goes_bad_temp_cache, and goes_bad_temp_cache_for.
Referenced by item_internal::scoped_goes_bad_cache::~scoped_goes_bad_cache().
Variable Documentation
goes_bad_temp_cache
bool item_internal::goes_bad_temp_cache = false
Definition at line 332 of file item.cpp.
Referenced by goes_bad_cache_fetch(), goes_bad_cache_set(), and goes_bad_cache_unset().
goes_bad_temp_cache_for
const item* item_internal::goes_bad_temp_cache_for = nullptr
Definition at line 333 of file item.cpp.
Referenced by goes_bad_cache_is_for(), goes_bad_cache_set(), and goes_bad_cache_unset().