Cataclysm BN: cata_event_dispatch Namespace Reference
cata_event_dispatch Namespace Reference
Functions
void avatar_moves (const avatar &u, const map &m, const tripoint &p)
Function Documentation
avatar_moves()
void cata_event_dispatch::avatar_moves (const avatar & u, const map & m, const tripoint & p)
Definition at line 12008 of file game.cpp.
{
    mtype_id mount_type;
    if( u.is_mounted() ) {
        mount_type = u.mounted_creature->type->id;
    }
    g->events().send<event_type::avatar_moves>( mount_type, m.ter( p ).id(),
            u.get_movement_mode(), u.is_underwater(), p.z );
}
References avatar_moves, g, Character::get_movement_mode(), int_id< T >::id(), Character::is_mounted(), Creature::is_underwater(), game::m, Character::mounted_creature, map::ter(), game::u, and tripoint::z.
Referenced by avatar_action::swim(), game::vertical_move(), and game::walk_move().