Cataclysm BN: vision Namespace Reference
vision Namespace Reference
Functions
float threshold_for_nv_range (float range)
Returns the light level that darkness will have at this range from player.
float nv_range_from_per (int per)
float nv_range_from_eye_encumbrance (int enc)
Function Documentation
nv_range_from_eye_encumbrance()
float vision::nv_range_from_eye_encumbrance (int enc)
Definition at line 1709 of file character.cpp.
{
    return -( enc / 10.0f );
}
Referenced by get_encumbrance_description(), and Character::recalc_sight_limits().
nv_range_from_per()
float vision::nv_range_from_per (int per)
Definition at line 1703 of file character.cpp.
{
    // The -1 is because the math is incorrect, but we want the UI to show correct numbers
    return per / 3.0f - 1.0f;
}
Referenced by draw_stats_info(), Character::recalc_sight_limits(), and set_stats().
threshold_for_nv_range()
float vision::threshold_for_nv_range (float range)
Returns the light level that darkness will have at this range from player.
Assumes pure air transparency.
Definition at line 1696 of file character.cpp.
{
    constexpr float epsilon = 0.0001f;
    return LIGHT_AMBIENT_LOW / std::exp( range * LIGHT_TRANSPARENCY_OPEN_AIR )
           - epsilon;
}
References LIGHT_AMBIENT_LOW, and LIGHT_TRANSPARENCY_OPEN_AIR.
Referenced by Character::get_vision_threshold().