Cataclysm BN: rot Namespace Reference
rot Namespace Reference
Functions
temperature_flag temperature_flag_for_location (const map &m, const item_location &loc)
temperature_flag temperature_flag_for_part (const vehicle &veh, size_t part_index)
Function Documentation
temperature_flag_for_location()
temperature_flag rot::temperature_flag_for_location (const map & m, const item_location & loc)
Definition at line 12 of file rot.cpp.
{
    switch( loc.where() ) {
        case item_location::type::invalid:
            return temperature_flag::TEMP_NORMAL;
        case item_location::type::character:
            return temperature_flag::TEMP_NORMAL;
        case item_location::type::map: {
            tripoint pos = loc.position();
            if( m.has_flag_furn( TFLAG_FREEZER, pos ) ) {
                return temperature_flag::TEMP_FREEZER;
            }
            if( m.has_flag_furn( TFLAG_FRIDGE, pos ) ) {
                return temperature_flag::TEMP_FRIDGE;
            }
            if( m.ter( pos ) == t_rootcellar ) {
                return temperature_flag::TEMP_ROOT_CELLAR;
            }
            return temperature_flag::TEMP_NORMAL;
        }
        case item_location::type::vehicle: {
            tripoint pos = loc.position();
            optional_vpart_position veh = m.veh_at( pos );
            if( !veh ) {
                debugmsg( "Expected vehicle at %d, %d, %d, but couldn't find any", pos.x, pos.y, pos.z );
                return temperature_flag::TEMP_NORMAL;
            }
            int cargo_index = veh->vehicle().part_with_feature( veh->part_index(), VPFLAG_CARGO, true );
            if( cargo_index < 0 ) {
                debugmsg( "Expected cargo part at %d, %d, %d, but couldn't find any", pos.x, pos.y, pos.z );
                return temperature_flag::TEMP_NORMAL;
            }
            return temperature_flag_for_part( veh->vehicle(), cargo_index );
        }
        case item_location::type::container:
            return temperature_flag_for_location( m, loc.parent_item() );
        default:
            debugmsg( "Invalid item location %d", static_cast<int>( loc.where() ) );
            return temperature_flag::TEMP_NORMAL;
    }
}
References item_location::character, item_location::container, debugmsg, map::has_flag_furn(), item_location::invalid, item_location::map, item_location::parent_item(), optional_vpart_position::part_with_feature(), item_location::position(), t_rootcellar, TEMP_FREEZER, TEMP_FRIDGE, TEMP_NORMAL, TEMP_ROOT_CELLAR, temperature_flag_for_location(), temperature_flag_for_part(), map::ter(), TFLAG_FREEZER, TFLAG_FRIDGE, map::veh_at(), item_location::vehicle, VPFLAG_CARGO, item_location::where(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by game::list_items(), examine_item_menu::run(), and temperature_flag_for_location().
temperature_flag_for_part()
temperature_flag rot::temperature_flag_for_part (const vehicle & veh, size_t part_index)
Definition at line 56 of file rot.cpp.
{
    const vehicle_part &part = veh.cpart( part_index );
    if( !part.enabled ) {
        return temperature_flag::TEMP_NORMAL;
    }
    if( part.has_flag( VPFLAG_FREEZER ) ) {
        return temperature_flag::TEMP_FREEZER;
    }
    if( part.has_flag( VPFLAG_FRIDGE ) ) {
        return temperature_flag::TEMP_FRIDGE;
    }
    return temperature_flag::TEMP_NORMAL;
}
References vehicle::cpart(), vehicle_part::enabled, vehicle_part::has_flag(), TEMP_FREEZER, TEMP_FRIDGE, TEMP_NORMAL, VPFLAG_FREEZER, and VPFLAG_FRIDGE.
Referenced by temperature_flag_for_location().