Cataclysm BN: npc_ai Namespace Reference
npc_ai Namespace Reference
Functions
double weapon_value (const Character &who, const item &weap, int ammo=10)
Evaluate item as weapon (melee or gun)
double gun_value (const Character &who, const item &weap, int ammo=10)
Evaluates item as a gun.
double melee_value (const Character &who, const item &weap)
Evaluate item as a melee weapon.
double unarmed_value (const Character &who)
Evaluate unarmed melee value.
Function Documentation
gun_value()
double npc_ai::gun_value (const Character & who, const item & weap, int ammo = 10)
Evaluates item as a gun.
Definition at line 1938 of file ranged.cpp.
{
    // TODO: Mods
    // TODO: Allow using a specified type of ammo rather than default or current
    if( !weap.type->gun ) {
        return 0.0;
    }
    if( ammo <= 0 ) {
        return 0.0;
    }
    const islot_gun &gun = *weap.type->gun;
    itype_id ammo_type;
    if( !weap.ammo_current().is_null() ) {
        ammo_type = weap.ammo_current();
    } else if( weap.magazine_current() ) {
        ammo_type = weap.common_ammo_default();
    } else {
        ammo_type = weap.ammo_default();
    }
    const itype *def_ammo_i = ammo_type.is_null() ? nullptr : &*ammo_type;
    damage_instance gun_damage = weap.gun_damage();
    item tmp = weap;
    tmp.ammo_set( ammo_type );
    int total_dispersion = ranged::get_weapon_dispersion( who, tmp ).max() +
                           ranged::effective_dispersion( who, tmp.sight_dispersion() );
    if( def_ammo_i != nullptr && def_ammo_i->ammo ) {
        const islot_ammo &def_ammo = *def_ammo_i->ammo;
        gun_damage.add( def_ammo.damage );
        total_dispersion += def_ammo.dispersion;
    }
    float damage_factor = gun_damage.total_damage();
    if( damage_factor > 0 ) {
        // TODO: Multiple damage types
        damage_factor += 0.5f * gun_damage.damage_units.front().res_pen;
    }
    int move_cost = time_to_attack( who, *weap.type );
    if( gun.clip != 0 && gun.clip < 10 ) {
        // TODO: RELOAD_ONE should get a penalty here
        int reload_cost = gun.reload_time + who.encumb( bp_hand_l ) + who.encumb( bp_hand_r );
        reload_cost /= gun.clip;
        move_cost += reload_cost;
    }
    // "Medium range" below means 9 tiles, "short range" means 4
    // Those are guarantees (assuming maximum time spent aiming)
    static const std::vector<std::pair<float, float>> dispersion_thresholds = {{
            // Headshots all the time
            { 0.0f, 5.0f },
            // Critical at medium range
            { 100.0f, 4.5f },
            // Critical at short range or good hit at medium
            { 200.0f, 3.5f },
            // OK hits at medium
            { 300.0f, 3.0f },
            // Point blank headshots
            { 450.0f, 2.5f },
            // OK hits at short
            { 700.0f, 1.5f },
            // Glances at medium, criticals at point blank
            { 1000.0f, 1.0f },
            // Nothing guaranteed, pure gamble
            { 2000.0f, 0.1f },
        }
    };
    static const std::vector<std::pair<float, float>> move_cost_thresholds = {{
            { 10.0f, 4.0f },
            { 25.0f, 3.0f },
            { 100.0f, 1.0f },
            { 500.0f, 5.0f },
        }
    };
    float move_cost_factor = multi_lerp( move_cost_thresholds, move_cost );
    // Penalty for dodging in melee makes the gun unusable in melee
    // Until NPCs get proper kiting, at least
    int melee_penalty = who.weapon.volume() / 250_ml - who.get_skill_level( skill_dodge );
    if( melee_penalty <= 0 ) {
        // Dispersion matters less if you can just use the gun in melee
        total_dispersion = std::min<int>( total_dispersion / move_cost_factor, total_dispersion );
    }
    float dispersion_factor = multi_lerp( dispersion_thresholds, total_dispersion );
    float damage_and_accuracy = damage_factor * dispersion_factor;
    // TODO: Some better approximation of the ability to keep on shooting
    static const std::vector<std::pair<float, float>> capacity_thresholds = {{
            { 1.0f, 0.5f },
            { 5.0f, 1.0f },
            { 10.0f, 1.5f },
            { 20.0f, 2.0f },
            { 50.0f, 3.0f },
        }
    };
    // How much until reload
    float capacity = gun.clip > 0 ? std::min<float>( gun.clip, ammo ) : ammo;
    // How much until dry and a new weapon is needed
    capacity += std::min<float>( 1.0, ammo / 20.0 );
    double capacity_factor = multi_lerp( capacity_thresholds, capacity );
    double gun_value = damage_and_accuracy * capacity_factor;
    add_msg( m_debug, "%s as gun: %.1f total, %.1f dispersion, %.1f damage, %.1f capacity",
             weap.type->get_id().str(), gun_value, dispersion_factor, damage_factor,
             capacity_factor );
    return std::max( 0.0, gun_value );
}
References damage_instance::add(), add_msg(), itype::ammo, item::ammo_current(), item::ammo_default(), item::ammo_set(), bp_hand_l, bp_hand_r, islot_gun::clip, item::common_ammo_default(), common_ranged_data::damage, damage_instance::damage_units, common_ranged_data::dispersion, ranged::effective_dispersion(), Character::encumb(), itype::get_id(), Character::get_skill_level(), ranged::get_weapon_dispersion(), itype::gun, item::gun_damage(), gun_value(), string_id< T >::is_null(), m_debug, item::magazine_current(), dispersion_sources::max(), move_cost(), multi_lerp(), islot_gun::reload_time, item::sight_dispersion(), skill_dodge, string_id< T >::str(), time_to_attack(), damage_instance::total_damage(), item::type, item::volume(), and Character::weapon.
Referenced by gun_value(), and weapon_value().
melee_value()
double npc_ai::melee_value (const Character & who, const item & weap)
Evaluate item as a melee weapon.
Definition at line 2288 of file melee.cpp.
{
    // start with average effective dps against a range of enemies
    double my_value = weap.average_dps( *who.as_player() );
    float reach = weap.reach_range( who );
    // value reach weapons more
    if( reach > 1.0f ) {
        my_value *= 1.0f + 0.5f * ( std::sqrt( reach ) - 1.0f );
    }
    // value polearms less to account for the trickiness of keeping the right range
    if( weap.has_flag( "POLEARM" ) ) {
        my_value *= 0.8;
    }
    // value style weapons more
    if( !who.martial_arts_data->enumerate_known_styles( weap.type->get_id() ).empty() ) {
        my_value *= 1.5;
    }
    add_msg( m_debug, "%s as melee: %.1f", weap.type->get_id().str(), my_value );
    return std::max( 0.0, my_value );
}
References add_msg(), Creature::as_player(), item::average_dps(), itype::get_id(), item::has_flag(), m_debug, Character::martial_arts_data, item::reach_range(), string_id< T >::str(), and item::type.
Referenced by npc::average_damage_dealt(), unarmed_value(), and weapon_value().
unarmed_value()
double npc_ai::unarmed_value (const Character & who)
Evaluate unarmed melee value.
Definition at line 2313 of file melee.cpp.
{
    // TODO: Martial arts
    return melee_value( who, item() );
}
References melee_value().
weapon_value()
double npc_ai::weapon_value (const Character & who, const item & weap, int ammo = 10)
Evaluate item as weapon (melee or gun)
Definition at line 2260 of file melee.cpp.
{
    if( who.is_wielding( weap ) ) {
        auto cached = who.get_npc_ai_info_cache( "weapon_value" );
        if( cached ) {
            return *cached;
        }
    }
    const double val_gun = gun_value( who, weap, ammo );
    const double val_melee = melee_value( who, weap );
    const double more = std::max( val_gun, val_melee );
    const double less = std::min( val_gun, val_melee );
    // discourage wielding helmets, but not worn firearms
    int armor_penalty = 1;
    if( weap.is_armor() && !weap.is_gun() ) {
        armor_penalty = 0;
    }
    // A small bonus for guns you can also use to hit stuff with (bayonets etc.)
    const double my_val = ( more + ( less / 2.0 ) ) * armor_penalty;
    add_msg( m_debug, "%s (%ld ammo) sum value: %.1f", weap.type->get_id().str(), ammo, my_val );
    if( who.is_wielding( weap ) ) {
        who.set_npc_ai_info_cache( "weapon_value", my_val );
    }
    return my_val;
}
References add_msg(), itype::get_id(), Character::get_npc_ai_info_cache(), gun_value(), item::is_armor(), item::is_gun(), Character::is_wielding(), m_debug, melee_value(), detail::digits::more, Character::set_npc_ai_info_cache(), string_id< T >::str(), and item::type.
Referenced by npc::character_danger(), npc::check_or_use_weapon_cbm(), npc::decide_needs(), npc::form_opinion(), give_item_to(), rate_critter(), npc::regen_ai_cache(), npc::value(), and npc::wield_better_weapon().