Cataclysm BN: pf Namespace Reference
pf Namespace Reference
Namespaces
namespace anonymous_namespace{simple_pathfinding.cpp}
Classes
struct directed_node
struct directed_path
struct node_score
struct omt_score
struct simple_path
Typedefs
template<typename Point >
using two_node_scoring_fn = std::function< node_score(directed_node< Point >, cata::optional< directed_node< Point > >)>
using omt_scoring_fn = std::function< omt_score(tripoint_abs_omt)>
Functions
directed_path< point > greedy_path (const point &source, const point &dest, const point &max, two_node_scoring_fn< point > scorer)
simple_path< tripoint_abs_omt > find_overmap_path (const tripoint_abs_omt &source, const tripoint_abs_omt &dest, int radius, omt_scoring_fn scorer, cata::optional< int > max_cost=cata::nullopt)
Uses A* to find an approximately-cheapest path from source to destination (in 3D).
template<typename Point , typename = std::enable_if_t<Point::dimension == 2>>
directed_path< Point > greedy_path (const Point &source, const Point &dest, const Point &max, two_node_scoring_fn< Point > scorer)
Uses Greedy Best-First-Search to find a short path from source to destination [2D only].
Typedef Documentation
omt_scoring_fn
using pf::omt_scoring_fn = typedef std::function<omt_score(tripoint_abs_omt)>
Definition at line 117 of file simple_pathfinding.h.
two_node_scoring_fn
template<typename Point > using pf::two_node_scoring_fn = typedef std::function<node_score(directed_node<Point>, cata::optional<directed_node<Point> >)>
Definition at line 66 of file simple_pathfinding.h.
Function Documentation
find_overmap_path()
simple_path< tripoint_abs_omt > pf::find_overmap_path (const tripoint_abs_omt & source, const tripoint_abs_omt & dest, int radius, omt_scoring_fn scorer, cata::optional< int > max_cost = cata::nullopt)
Uses A* to find an approximately-cheapest path from source to destination (in 3D).
Parameters
source Starting point of path
dest End point of path
radius Maximum search radius
scorer function that returns the omt_score for the given OMT
max_cost Maximum path cost (optional)
Definition at line 243 of file simple_pathfinding.cpp.
{
    constexpr size_t max_search_count = 100000;
    simple_path<tripoint_abs_omt> ret;
    bool meet = false;
    auto do_astar = [&]( const tripoint_abs_omt & start,
                         std::unordered_map<tripoint_abs_omt, navigation_node> &known_nodes,
                         std::priority_queue<scored_address, std::vector<scored_address>, std::greater<>> &open_set,
    std::unordered_map<tripoint_abs_omt, navigation_node> &other_known_nodes ) {
        const tripoint_abs_omt cur_addr = open_set.top().addr;
        open_set.pop();
        if( other_known_nodes.find( cur_addr ) != other_known_nodes.end() ) {
            meet = true;
            tripoint_abs_omt addr = cur_addr;
            tripoint_abs_omt other_start = start == source ? dest : source;
            while( addr != other_start ) {
                ret.points.emplace_back( addr );
                addr = addr + direction_to_tripoint( other_known_nodes.at( addr ).get_prev_dir() );
            }
            ret.points.emplace_back( addr );
            addr = cur_addr;
            while( addr != start ) {
                addr = addr + direction_to_tripoint( known_nodes.at( addr ).get_prev_dir() );
                ret.points.emplace_back( addr );
            }
            return;
        }
        const navigation_node &cur_node = known_nodes.at( cur_addr );
        for( direction dir : enumerate_directions( cur_node.allow_z_change ) ) {
            if( dir == cur_node.prev_dir ) {
                continue; // don't go back the way we just came
            }
            const direction rev_dir = reverse_direction( dir );
            const tripoint_abs_omt next_addr = cur_addr + direction_to_tripoint( dir );
            const int cumulative_cost = cur_node.cumulative_cost + adjust_omt_cost( cur_node.node_cost, rev_dir,
                                        cur_node.get_prev_dir() );
            auto iter = known_nodes.find( next_addr );
            if( iter != known_nodes.end() ) {
                navigation_node &next_node = iter->second;
                if( next_node.cumulative_cost > cumulative_cost ) {
                    next_node.cumulative_cost = cumulative_cost;
                    next_node.prev_dir = static_cast<int8_t>( rev_dir );
                }
            } else if( known_nodes.size() < max_search_count ) {
                if( octile_dist( source.xy(), next_addr.xy() ) > radius ) {
                    continue;
                }
                const omt_score next_score = scorer( next_addr );
                if( next_score.node_cost < 0 ) {
                    // TODO: add to closed set to avoid re-visiting
                    continue;
                }
                // TODO: pass in the 10 (default terrain cost)
                const int xy_score = octile_dist( next_addr.xy(), dest.xy(), 10 );
                const int z_score = std::abs( next_addr.z() - dest.z() ) * 10;
                const int estimated_total_cost = cumulative_cost + next_score.node_cost + xy_score + z_score;
                if( max_cost && estimated_total_cost > *max_cost ) {
                    continue;
                }
                navigation_node &next_node = known_nodes[next_addr];
                next_node.cumulative_cost = cumulative_cost;
                next_node.node_cost = next_score.node_cost;
                next_node.prev_dir = static_cast<int8_t>( rev_dir );
                next_node.allow_z_change = next_score.allow_z_change;
                open_set.push( scored_address{ next_addr, estimated_total_cost } );
            }
        }
    };
    const omt_score start_score = scorer( source );
    const omt_score end_score = scorer( dest );
    if( start_score.node_cost < 0 || end_score.node_cost < 0 ) {
        return ret;
    }
    std::unordered_map<tripoint_abs_omt, navigation_node> known_nodes_src;
    std::priority_queue<scored_address, std::vector<scored_address>, std::greater<>> open_set_src;
    known_nodes_src.emplace( source, navigation_node{0, 0, -1, start_score.allow_z_change} );
    open_set_src.push( scored_address{ source, 0 } );
    std::unordered_map<tripoint_abs_omt, navigation_node> known_nodes_dest;
    std::priority_queue<scored_address, std::vector<scored_address>, std::greater<>> open_set_dest;
    known_nodes_dest.emplace( dest, navigation_node{0, 0, -1, end_score.allow_z_change} );
    open_set_dest.push( scored_address{ dest, 0 } );
    int search_count = 0;
    while( !open_set_src.empty() && !open_set_dest.empty() && !meet ) {
        search_count++;
        do_astar( source, known_nodes_src, open_set_src, known_nodes_dest );
        if( meet ) {
            return ret;
        }
        if( search_count > 10000 ) {
            do_astar( dest, known_nodes_dest, open_set_dest, known_nodes_src );
        }
    }
    return ret;
}
References pf::anonymous_namespace{simple_pathfinding.cpp}::adjust_omt_cost(), pf::omt_score::allow_z_change, pf::anonymous_namespace{simple_pathfinding.cpp}::direction_to_tripoint(), pf::anonymous_namespace{simple_pathfinding.cpp}::enumerate_directions(), pf::omt_score::node_cost, octile_dist(), cata::hash64_detail::ret, pf::anonymous_namespace{simple_pathfinding.cpp}::reverse_direction(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::z().
Referenced by overmapbuffer::get_travel_path().
greedy_path() [1/2]
directed_path< point > pf::greedy_path (const point & source, const point & dest, const point & max, two_node_scoring_fn< point > scorer)
Definition at line 43 of file simple_pathfinding.cpp.
{
    using Node = point_node;
    const auto inbounds = [ max ]( const point & p ) {
        return p.x >= 0 && p.x < max.x && p.y >= 0 && p.y < max.y;
    };
    const auto map_index = [ max ]( const point & p ) {
        return p.y * max.x + p.x;
    };
    directed_path<point> res;
    if( source == dest ) {
        return res;
    }
    if( !inbounds( source ) || !inbounds( dest ) ) {
        return res;
    }
    const Node first_node( source, om_direction::type::invalid, 1000 );
    if( scorer( directed_node<point>( first_node.pos, first_node.dir ),
                cata::nullopt ).node_cost < 0 ) {
        return res;
    }
    const size_t map_size = static_cast<size_t>( max.x * max.y );
    std::vector<bool> closed( map_size, false );
    std::vector<int> open( map_size, 0 );
    std::vector<short> dirs( map_size, 0 );
    std::priority_queue<Node, std::vector<Node>> nodes[2];
    int i = 0;
    nodes[i].push( first_node );
    open[map_index( source )] = std::numeric_limits<int>::max();
    while( !nodes[i].empty() ) {
        const Node mn( nodes[i].top() ); // get the best-looking node
        nodes[i].pop();
        // mark it visited
        closed[map_index( mn.pos )] = true;
        // if we've reached the end, draw the path and return
        if( mn.pos == dest ) {
            point p = mn.pos;
            res.nodes.reserve( nodes[i].size() );
            while( p != source ) {
                const int n = map_index( p );
                const om_direction::type dir = static_cast<om_direction::type>( dirs[n] );
                res.nodes.emplace_back( p, dir );
                p += om_direction::displace( dir );
            }
            res.nodes.emplace_back( p );
            return res;
        }
        for( om_direction::type dir : om_direction::all ) {
            const point p = mn.pos + om_direction::displace( dir );
            const int n = map_index( p );
            // don't allow out of bounds or already traversed tiles
            if( !inbounds( p ) || closed[n] ) {
                continue;
            }
            const node_score score = scorer( directed_node<point>( p, dir ), directed_node<point>( mn.pos,
                                             mn.dir ) );
            if( score.node_cost < 0 ) {
                continue;
            }
            const int priority = score.node_cost + score.estimated_dest_cost;
            // record direction to shortest path
            if( open[n] == 0 || open[n] > priority ) {
                dirs[n] = ( static_cast<int>( dir ) + 2 ) % 4;
                if( open[n] != 0 ) {
                    while( nodes[i].top().pos != p ) {
                        nodes[1 - i].push( nodes[i].top() );
                        nodes[i].pop();
                    }
                    nodes[i].pop();
                    if( nodes[i].size() > nodes[1 - i].size() ) {
                        i = 1 - i;
                    }
                    while( !nodes[i].empty() ) {
                        nodes[1 - i].push( nodes[i].top() );
                        nodes[i].pop();
                    }
                    i = 1 - i;
                }
                open[n] = priority;
                nodes[i].emplace( p, dir, priority );
            }
        }
    }
    return res;
}
References om_direction::all, om_direction::displace(), om_direction::invalid, pf::directed_path< Point >::nodes, cata::nullopt, open(), om_direction::size, point::x, and point::y.
Referenced by greedy_path(), overmap::lay_out_connection(), and overmapbuffer::reveal_route().
greedy_path() [2/2]
template<typename Point , typename = std::enable_if_t<Point::dimension == 2>> directed_path< Point > pf::greedy_path (const Point & source, const Point & dest, const Point & max, two_node_scoring_fn< Point > scorer)
Uses Greedy Best-First-Search to find a short path from source to destination [2D only].
The search area is a rectangle with corners at (0,0) and max.
Parameters
source Starting point of path
dest End point of path
max Max permissible coordinates for a point on the path
scorer function of (node &current, node *previous) that returns node_score.
Definition at line 83 of file simple_pathfinding.h.
{
    directed_path<Point> res;
    const two_node_scoring_fn<point> point_scorer
    = [scorer]( directed_node<point> current, cata::optional<directed_node<point>> prev ) {
        cata::optional<directed_node<Point>> prev_node;
        if( prev ) {
            prev_node = directed_node<Point>( Point( prev->pos ), prev->dir );
        }
        return scorer( directed_node<Point>( Point( current.pos ), current.dir ), prev_node );
    };
    directed_path<point> path = greedy_path( source.raw(), dest.raw(), max.raw(), point_scorer );
    res.nodes.reserve( path.nodes.size() );
    for( const auto &node : path.nodes ) {
        res.nodes.emplace_back( Point( node.pos ), node.dir );
    }
    return res;
}
References pf::directed_node< Point >::dir, greedy_path(), pf::directed_path< Point >::nodes, and pf::directed_node< Point >::pos.