Cataclysm BN: relic_funcs Namespace Reference
relic_funcs Namespace Reference
Functions
bool check_recharge_reqs (const item &itm, const relic_recharge &rech, const Character &carrier)
bool process_recharge_entry (item &itm, const relic_recharge &rech, Character &carrier)
void process_recharge (item &itm, Character &carrier)
Function Documentation
check_recharge_reqs()
bool relic_funcs::check_recharge_reqs (const item & itm, const relic_recharge & rech, const Character & carrier)
Definition at line 276 of file relic.cpp.
{
    switch( rech.req ) {
        case relic_recharge_req::none: {
            return true;
        }
        case relic_recharge_req::equipped: {
            if( itm.is_armor() ) {
                return carrier.is_wearing( itm );
            } else {
                return carrier.is_wielding( itm );
            }
        }
        case relic_recharge_req::close_to_skin: {
            if( itm.is_armor() ) {
                if( !carrier.is_wearing( itm ) ) {
                    return false;
                }
                for( const bodypart_id &bp : carrier.get_all_body_parts() ) {
                    if( !itm.covers( bp ) ) {
                        continue;
                    }
                    bool this_bp_good = true;
                    for( const item &wi : carrier.worn ) {
                        if( wi.get_coverage() == 0 ) {
                            continue;
                        }
                        if( &wi == &itm ) {
                            break;
                        } else if( wi.covers( bp ) ) {
                            this_bp_good = false;
                            break;
                        }
                    }
                    if( this_bp_good ) {
                        return true;
                    }
                }
                return false;
            } else {
                if( !carrier.is_wielding( itm ) ) {
                    return false;
                }
                bool hand_l_ok = true;
                bool hand_r_ok = true;
                for( const item &wi : carrier.worn ) {
                    if( wi.get_coverage() == 0 ) {
                        continue;
                    }
                    if( wi.covers( body_part_hand_l ) ) {
                        hand_l_ok = false;
                    }
                    if( wi.covers( body_part_hand_r ) ) {
                        hand_r_ok = false;
                    }
                }
                return hand_l_ok || hand_r_ok;
            }
        }
        case relic_recharge_req::sleep: {
            return carrier.has_effect( effect_sleep );
        }
        case relic_recharge_req::rad: {
            return get_map().get_radiation( carrier.pos() ) > 0 || carrier.get_rad() > 0;
        }
        case relic_recharge_req::wet: {
            bool has_wet = std::any_of( carrier.body_wetness.begin(), carrier.body_wetness.end(),
            []( const int w ) {
                return w != 0;
            } );
            if( has_wet ) {
                return true;
            } else {
                const weather_type &wt = get_weather().weather_id.obj();
                if( !wt.rains || wt.acidic || wt.precip == precip_class::none ) {
                    return false;
                }
                return get_map().is_outside( carrier.pos() );
            }
        }
        case relic_recharge_req::sky: {
            return carrier.posz() > 0;
        }
        default: {
            std::abort();
        }
    }
    cata::unreachable();
}
References weather_type::acidic, body_part_hand_l, body_part_hand_r, Character::body_wetness, close_to_skin, item::covers(), effect_sleep, equipped, Creature::get_all_body_parts(), item::get_coverage(), get_map(), Character::get_rad(), map::get_radiation(), get_weather(), Creature::has_effect(), item::is_armor(), map::is_outside(), Character::is_wearing(), Character::is_wielding(), none, string_id< T >::obj(), Character::pos(), Character::posz(), weather_type::precip, rad, weather_type::rains, relic_recharge::req, sky, sleep, cata::unreachable(), weather_manager::weather_id, wet, and Character::worn.
Referenced by process_recharge_entry().
process_recharge()
void relic_funcs::process_recharge (item & itm, Character & carrier)
Definition at line 449 of file relic.cpp.
{
    if( !itm.is_tool() ) {
        return;
    }
    if( itm.ammo_remaining() >= itm.ammo_capacity() ) {
        return;
    }
    for( const relic_recharge &rech : itm.get_relic_recharge_scheme() ) {
        process_recharge_entry( itm, rech, carrier );
    }
}
References item::ammo_capacity(), item::ammo_remaining(), item::get_relic_recharge_scheme(), item::is_tool(), and process_recharge_entry().
Referenced by item::process_relic().
process_recharge_entry()
bool relic_funcs::process_recharge_entry (item & itm, const relic_recharge & rech, Character & carrier)
Definition at line 366 of file relic.cpp.
{
    if( !calendar::once_every( rech.interval ) ) {
        return false;
    }
    if( !check_recharge_reqs( itm, rech, carrier ) ) {
        return false;
    }
    map &here = get_map();
    switch( rech.type ) {
        case relic_recharge_type::time: {
            break;
        }
        case relic_recharge_type::solar: {
            if( !g->is_in_sunlight( carrier.pos() ) ) {
                return false;
            }
            break;
        }
        case relic_recharge_type::pain: {
            carrier.add_msg_if_player( m_bad, _( "You suddenly feel sharp pain for no reason." ) );
            carrier.mod_pain_noresist( rng( rech.intensity_min, rech.intensity_max ) );
            break;
        }
        case relic_recharge_type::hp: {
            carrier.add_msg_if_player( m_bad, _( "You feel your body decaying." ) );
            carrier.hurtall( rng( rech.intensity_min, rech.intensity_max ), nullptr );
            break;
        }
        case relic_recharge_type::fatigue: {
            carrier.add_msg_if_player( m_bad, _( "You feel fatigue seeping into your body." ) );
            carrier.mod_fatigue( rng( rech.intensity_min, rech.intensity_max ) );
            carrier.mod_stamina( -100 * rng( rech.intensity_min, rech.intensity_max ) );
            break;
        }
        case relic_recharge_type::field: {
            bool consumed = false;
            for( const tripoint &dest : here.points_in_radius( carrier.pos(), 1 ) ) {
                field_entry *field_at = here.field_at( dest ).find_field( rech.field_type );
                if( !field_at ) {
                    continue;
                }
                int int_here = field_at->get_field_intensity();
                if( int_here >= rech.intensity_min && int_here <= rech.intensity_max ) {
                    here.remove_field( dest, rech.field_type );
                    consumed = true;
                    break;
                }
            }
            if( !consumed ) {
                return false;
            }
            break;
        }
        case relic_recharge_type::trap: {
            bool consumed = false;
            for( const tripoint &dest : here.points_in_radius( carrier.pos(), 1 ) ) {
                if( here.tr_at( dest ).id == rech.trap_type ) {
                    here.remove_trap( dest );
                    consumed = true;
                }
            }
            if( !consumed ) {
                return false;
            }
            break;
        }
        default: {
            std::abort();
        }
    }
    // If relic has a valid ammo type, make sure the first charge loaded isn't a "none"
    bool was_zero = itm.charges == 0;
    itm.charges = clamp( itm.charges + rech.rate, 0, itm.ammo_capacity() );
    if( was_zero && !itm.ammo_types().empty() ) {
        itm.ammo_set( itm.ammo_default(), itm.charges );
    }
    if( rech.message ) {
        carrier.add_msg_if_player( _( *rech.message ) );
    }
    return true;
}
References _, Creature::add_msg_if_player(), item::ammo_capacity(), item::ammo_default(), item::ammo_set(), item::ammo_types(), item::charges, check_recharge_reqs(), clamp(), fatigue, field, map::field_at(), relic_recharge::field_type, field::find_field(), g, field_entry::get_field_intensity(), get_map(), hp, Character::hurtall(), trap::id, relic_recharge::intensity_max, relic_recharge::intensity_min, relic_recharge::interval, m_bad, relic_recharge::message, Character::mod_fatigue(), Creature::mod_pain_noresist(), Character::mod_stamina(), calendar::once_every(), pain, map::points_in_radius(), Character::pos(), relic_recharge::rate, map::remove_field(), map::remove_trap(), rng(), solar, time, map::tr_at(), trap, relic_recharge::trap_type, and relic_recharge::type.
Referenced by process_recharge().