Cataclysm BN: monexamine Namespace Reference
monexamine Namespace Reference
Functions
bool pet_menu (monster &z)
bool mech_hack (monster &z)
bool pay_bot (monster &z)
bool mfriend_menu (monster &z)
void remove_battery (monster &z)
void insert_battery (monster &z)
void swap (monster &z)
void push (monster &z)
void rename_pet (monster &z)
void attach_bag_to (monster &z)
void remove_bag_from (monster &z)
void dump_items (monster &z)
bool give_items_to (monster &z)
bool add_armor (monster &z)
void remove_armor (monster &z)
void remove_harness (monster &z)
void play_with (monster &z)
void kill_zslave (monster &z)
void add_leash (monster &z)
void remove_leash (monster &z)
void start_leading (monster &z)
void stop_leading (monster &z)
void tie_pet (monster &z)
void untie_pet (monster &z)
void shear_animal (monster &z)
void mount_pet (monster &z)
void attach_or_remove_saddle (monster &z)
void deactivate_pet (monster &z)
void milk_source (monster &source_mon)
Function Documentation
add_armor()
bool monexamine::add_armor (monster & z)
Definition at line 724 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    item_location loc = pet_armor_loc( z );
    if( !loc ) {
        add_msg( _( "Never mind." ) );
        return true;
    }
    item &armor = *loc;
    units::mass max_weight = z.weight_capacity() - z.get_carried_weight();
    if( max_weight <= armor.weight() ) {
        add_msg( pgettext( "pet armor", "Your %1$s is too heavy for your %2$s." ), armor.tname( 1 ),
                 pet_name );
        return true;
    }
    armor.set_var( "pet_armor", "true" );
    z.armor_item = cata::make_value<item>( armor );
    add_msg( pgettext( "pet armor", "You put the %1$s on your %2$s." ), armor.display_name(),
             pet_name );
    loc.remove_item();
    z.add_effect( effect_monster_armor, 1_turns, num_bp );
    // TODO: armoring a horse takes a lot longer than 2 seconds. This should be a long action.
    g->u.moves -= 200;
    return true;
}
References _, monster::add_effect(), add_msg(), monster::armor_item, item::display_name(), effect_monster_armor, g, monster::get_carried_weight(), monster::get_name(), num_bp, pet_armor_loc(), pgettext(), item_location::remove_item(), item::set_var(), item::tname(), item::weight(), and monster::weight_capacity().
Referenced by pet_menu().
add_leash()
void monexamine::add_leash (monster & z)
Definition at line 797 of file monexamine.cpp.
{
    if( z.has_effect( effect_leashed ) ) {
        return;
    }
    Character &player = get_player_character();
    std::vector<item *> rope_inv = player.items_with( []( const item & it ) {
        return it.has_flag( "TIE_UP" );
    } );
    if( rope_inv.empty() ) {
        return;
    }
    int i = 0;
    uilist selection_menu;
    selection_menu.text = string_format( _( "Select an item to leash your %s with." ), z.get_name() );
    selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Cancel" ) );
    for( const item *iter : rope_inv ) {
        selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Use %s" ), iter->tname() );
    }
    selection_menu.selected = 1;
    selection_menu.query();
    int index = selection_menu.ret;
    if( index == 0 || index == UILIST_CANCEL || index < 0 ||
        index > static_cast<int>( rope_inv.size() ) ) {
        return;
    }
    item *rope_item = rope_inv[index - 1];
    z.tied_item = cata::make_value<item>( *rope_item );
    player.i_rem( rope_item );
    z.add_effect( effect_leashed, 1_turns );
    z.get_effect( effect_leashed ).set_permanent();
    add_msg( _( "You add a leash to your %s." ), z.get_name() );
}
References _, monster::add_effect(), add_msg(), uilist::addentry(), effect_leashed, Creature::get_effect(), monster::get_name(), get_player_character(), Creature::has_effect(), item::has_flag(), Character::i_rem(), visitable< T >::items_with(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::selected, effect::set_permanent(), string_format(), uilist::text, monster::tied_item, and UILIST_CANCEL.
Referenced by pet_menu().
attach_bag_to()
void monexamine::attach_bag_to (monster & z)
Definition at line 632 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    auto filter = []( const item & it ) {
        return it.is_armor() && it.get_storage() > 0_ml;
    };
    item_location loc = game_menus::inv::titled_filter_menu( filter, g->u, _( "Bag item" ) );
    if( !loc ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    item &it = *loc;
    z.storage_item = cata::make_value<item>( it );
    add_msg( _( "You mount the %1$s on your %2$s." ), it.display_name(), pet_name );
    g->u.i_rem( &it );
    z.add_effect( effect_has_bag, 1_turns, num_bp );
    // Update encumbrance in case we were wearing it
    g->u.flag_encumbrance();
    g->u.moves -= 200;
}
References _, monster::add_effect(), add_msg(), item::display_name(), effect_has_bag, g, monster::get_name(), num_bp, monster::storage_item, and game_menus::inv::titled_filter_menu().
Referenced by pet_menu().
attach_or_remove_saddle()
void monexamine::attach_or_remove_saddle (monster & z)
Definition at line 541 of file monexamine.cpp.
{
    if( z.has_effect( effect_saddled ) ) {
        z.remove_effect( effect_saddled );
        g->u.i_add( *z.tack_item );
        z.tack_item.reset();
    } else {
        item_location loc = tack_loc();
        if( !loc ) {
            add_msg( _( "Never mind." ) );
            return;
        }
        z.add_effect( effect_saddled, 1_turns, num_bp );
        z.tack_item = cata::make_value<item>( *loc.get_item() );
        loc.remove_item();
    }
}
References _, monster::add_effect(), add_msg(), effect_saddled, g, item_location::get_item(), Creature::has_effect(), num_bp, Creature::remove_effect(), item_location::remove_item(), monster::tack_item, and tack_loc().
Referenced by deactivate_pet(), and pet_menu().
deactivate_pet()
void monexamine::deactivate_pet (monster & z)
Definition at line 896 of file monexamine.cpp.
{
    if( z.has_effect( effect_has_bag ) ) {
        remove_bag_from( z );
    }
    if( z.has_effect( effect_monster_armor ) ) {
        remove_armor( z );
    }
    if( z.has_effect( effect_tied ) ) {
        untie_pet( z );
    }
    if( z.has_effect( effect_leashed ) ) {
        remove_leash( z );
    }
    if( z.has_effect( effect_saddled ) ) {
        attach_or_remove_saddle( z );
    }
    g->m.add_item_or_charges( z.pos(), z.to_item() );
    if( !z.has_flag( MF_INTERIOR_AMMO ) ) {
        for( auto &ammodef : z.ammo ) {
            if( ammodef.second > 0 ) {
                g->m.spawn_item( z.pos(), ammodef.first, 1, ammodef.second, calendar::turn );
            }
        }
    }
    g->u.moves -= 100;
    g->remove_zombie( z );
}
References monster::ammo, attach_or_remove_saddle(), effect_has_bag, effect_leashed, effect_monster_armor, effect_saddled, effect_tied, g, Creature::has_effect(), monster::has_flag(), MF_INTERIOR_AMMO, monster::pos(), remove_armor(), remove_bag_from(), remove_leash(), monster::to_item(), calendar::turn, and untie_pet().
Referenced by pet_menu().
dump_items()
void monexamine::dump_items (monster & z)
Definition at line 674 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    for( auto &it : z.inv ) {
        g->m.add_item_or_charges( g->u.pos(), it );
    }
    z.inv.clear();
    add_msg( _( "You dump the contents of the %s's bag on the ground." ), pet_name );
    g->u.moves -= 200;
}
References _, add_msg(), g, monster::get_name(), and monster::inv.
Referenced by pet_menu(), and remove_bag_from().
give_items_to()
bool monexamine::give_items_to (monster & z)
Definition at line 685 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    if( !z.storage_item ) {
        add_msg( _( "There is no container on your %s to put things in!" ), pet_name );
        return true;
    }
    item &storage = *z.storage_item;
    units::mass max_weight = z.weight_capacity() - z.get_carried_weight();
    units::volume max_volume = storage.get_storage() - z.get_carried_volume();
    drop_locations items = game_menus::inv::multidrop( g->u );
    drop_locations to_move;
    for( const drop_location &itq : items ) {
        item it_copy = *itq.loc;
        if( it_copy.count_by_charges() ) {
            it_copy.charges = itq.count;
        }
        units::volume item_volume = it_copy.volume();
        units::mass item_weight = it_copy.weight();
        if( max_weight < item_weight ) {
            add_msg( _( "The %1$s is too heavy for the %2$s to carry." ), it_copy.tname(), pet_name );
            continue;
        } else if( max_volume < item_volume ) {
            add_msg( _( "The %1$s is too big to fit in the %2$s." ), it_copy.tname(), storage.tname() );
            continue;
        } else {
            max_weight -= item_weight;
            max_volume -= item_volume;
            to_move.insert( to_move.end(), itq );
        }
    }
    z.add_effect( effect_ai_waiting, 5_turns );
    g->u.drop( to_move, z.pos(), true );
    return false;
}
References _, monster::add_effect(), add_msg(), item::charges, item::count_by_charges(), effect_ai_waiting, g, monster::get_carried_volume(), monster::get_carried_weight(), monster::get_name(), item::get_storage(), game_menus::inv::multidrop(), monster::pos(), monster::storage_item, item::tname(), item::volume(), item::weight(), and monster::weight_capacity().
Referenced by pet_menu().
insert_battery()
void monexamine::insert_battery (monster & z)
Definition at line 390 of file monexamine.cpp.
{
    if( z.battery_item ) {
        // already has a battery, shouldn't be called with one, but just incase.
        return;
    }
    std::vector<item *> bat_inv = g->u.items_with( []( const item & itm ) {
        return itm.has_flag( "MECH_BAT" );
    } );
    if( bat_inv.empty() ) {
        return;
    }
    int i = 0;
    uilist selection_menu;
    selection_menu.text = string_format( _( "Select an battery to insert into your %s." ),
                                         z.get_name() );
    selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Cancel" ) );
    for( auto iter : bat_inv ) {
        selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Use %s" ), iter->tname() );
    }
    selection_menu.selected = 1;
    selection_menu.query();
    auto index = selection_menu.ret;
    if( index == 0 || index == UILIST_CANCEL || index < 0 ||
        index > static_cast<int>( bat_inv.size() ) ) {
        return;
    }
    item *bat_item = bat_inv[index - 1];
    int item_pos = g->u.get_item_position( bat_item );
    if( item_pos != INT_MIN ) {
        z.battery_item = cata::make_value<item>( *bat_item );
        g->u.i_rem( item_pos );
    }
}
References _, uilist::addentry(), monster::battery_item, g, monster::get_name(), item::has_flag(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::selected, string_format(), uilist::text, and UILIST_CANCEL.
Referenced by pet_menu().
kill_zslave()
void monexamine::kill_zslave (monster & z)
Definition at line 783 of file monexamine.cpp.
{
    z.apply_damage( &g->u, bodypart_id( "torso" ), 100 ); // damage the monster (and its corpse)
    z.die( &g->u ); // and make sure it's really dead
    g->u.moves -= 150;
    if( !one_in( 3 ) ) {
        g->u.add_msg_if_player( _( "You tear out the pheromone ball from the zombie slave." ) );
        item ball( "pheromone", calendar::start_of_cataclysm );
        iuse::pheromone( &g->u, &ball, true, g->u.pos() );
    }
}
References _, monster::apply_damage(), monster::die(), g, one_in(), iuse::pheromone(), and calendar::start_of_cataclysm.
Referenced by pet_menu().
mech_hack()
bool monexamine::mech_hack (monster & z)
Definition at line 425 of file monexamine.cpp.
{
    itype_id card_type = itype_id_military;
    if( g->u.has_amount( card_type, 1 ) ) {
        if( query_yn( _( "Swipe your ID card into the mech's security port?" ) ) ) {
            g->u.mod_moves( -100 );
            z.add_effect( effect_pet, 1_turns, num_bp );
            z.friendly = -1;
            add_msg( m_good, _( "The %s whirs into life and opens its restraints to accept a pilot." ),
                     z.get_name() );
            g->u.use_amount( card_type, 1 );
            return true;
        }
    } else {
        add_msg( m_info, _( "You do not have the required ID card to activate this mech." ) );
    }
    return false;
}
References _, monster::add_effect(), add_msg(), effect_pet, monster::friendly, g, monster::get_name(), itype_id_military, m_good, m_info, num_bp, and query_yn().
Referenced by game::examine().
mfriend_menu()
bool monexamine::mfriend_menu (monster & z)
Definition at line 497 of file monexamine.cpp.
{
    enum choices {
        swap_pos = 0,
        push_monster,
        rename,
        attack
    };
    uilist amenu;
    const std::string pet_name = z.get_name();
    amenu.text = string_format( _( "What to do with your %s?" ), pet_name );
    amenu.addentry( swap_pos, true, 's', _( "Swap positions" ) );
    amenu.addentry( push_monster, true, 'p', _( "Push %s" ), pet_name );
    amenu.addentry( rename, true, 'e', _( "Rename" ) );
    amenu.addentry( attack, true, 'a', _( "Attack" ) );
    amenu.query();
    const int choice = amenu.ret;
    switch( choice ) {
        case swap_pos:
            swap( z );
            break;
        case push_monster:
            push( z );
            break;
        case rename:
            rename_pet( z );
            break;
        case attack:
            if( query_yn( _( "You may be attacked!  Proceed?" ) ) ) {
                get_player_character().melee_attack( z, true );
            }
            break;
        default:
            break;
    }
    return true;
}
References _, uilist::addentry(), monster::get_name(), get_player_character(), Character::melee_attack(), push(), uilist::query(), query_yn(), rename_pet(), uilist::ret, string_format(), cata::swap(), swap_pos(), and uilist::text.
Referenced by game::examine().
milk_source()
void monexamine::milk_source (monster & source_mon)
Definition at line 925 of file monexamine.cpp.
{
    itype_id milked_item = source_mon.type->starting_ammo.begin()->first;
    auto milkable_ammo = source_mon.ammo.find( milked_item );
    if( milkable_ammo == source_mon.ammo.end() ) {
        debugmsg( "The %s has no milkable %s.", source_mon.get_name(), milked_item.str() );
        return;
    }
    if( milkable_ammo->second > 0 ) {
        const int moves = to_moves<int>( time_duration::from_minutes( milkable_ammo->second / 2 ) );
        g->u.assign_activity( ACT_MILK, moves, -1 );
        g->u.activity.coords.push_back( g->m.getabs( source_mon.pos() ) );
        // pin the cow in place if it isn't already
        bool temp_tie = !source_mon.has_effect( effect_tied );
        if( temp_tie ) {
            source_mon.add_effect( effect_tied, 1_turns, num_bp );
            g->u.activity.str_values.push_back( "temp_tie" );
        }
        add_msg( _( "You milk the %s." ), source_mon.get_name() );
    } else {
        add_msg( _( "The %s has no more milk." ), source_mon.get_name() );
    }
}
References _, ACT_MILK, monster::add_effect(), add_msg(), monster::ammo, debugmsg, effect_tied, time_duration::from_minutes(), g, monster::get_name(), Creature::has_effect(), num_bp, monster::pos(), mtype::starting_ammo, string_id< T >::str(), and monster::type.
Referenced by pet_menu().
mount_pet()
void monexamine::mount_pet (monster & z)
Definition at line 575 of file monexamine.cpp.
{
    g->u.mount_creature( z );
}
References g.
Referenced by pet_menu().
pay_bot()
bool monexamine::pay_bot (monster & z)
Definition at line 457 of file monexamine.cpp.
{
    time_duration friend_time = z.get_effect_dur( effect_pet );
    const int charge_count = g->u.charges_of( itype_cash_card );
    int amount = 0;
    uilist bot_menu;
    bot_menu.text = string_format(
                        _( "Welcome to the %s Friendship Interface.  What would you like to do?\n"
                           "Your current friendship will last: %s" ), z.get_name(), to_string( friend_time ) );
    if( charge_count > 0 ) {
        bot_menu.addentry( 1, true, 'b', _( "Get more friendship.  10 cents/min" ) );
    } else {
        bot_menu.addentry( 2, true, 'q',
                           _( "Sadly you're not currently able to extend your friendship.  - Quit menu" ) );
    }
    bot_menu.query();
    switch( bot_menu.ret ) {
        case 1:
            amount = prompt_for_amount(
                         vgettext( "How much friendship do you get?  Max: %d minute.  (0 to cancel)",
                                   "How much friendship do you get?  Max: %d minutes.", charge_count / 10 ), charge_count / 10 );
            if( amount > 0 ) {
                time_duration time_bought = time_duration::from_minutes( amount );
                g->u.use_charges( itype_cash_card, amount * 10 );
                z.add_effect( effect_pet, time_bought );
                z.add_effect( effect_paid, time_bought, num_bp );
                z.friendly = -1;
                popup( _( "Your friendship grows stronger!\n This %s will follow you for %s." ), z.get_name(),
                       to_string( z.get_effect_dur( effect_pet ) ) );
                return true;
            }
            break;
        case 2:
            break;
    }
    return false;
}
References _, monster::add_effect(), uilist::addentry(), effect_paid, effect_pet, monster::friendly, time_duration::from_minutes(), g, Creature::get_effect_dur(), monster::get_name(), itype_cash_card, num_bp, popup(), prompt_for_amount(), uilist::query(), uilist::ret, string_format(), uilist::text, to_string(), and vgettext().
Referenced by game::examine(), and pet_menu().
pet_menu()
bool monexamine::pet_menu (monster & z)
Definition at line 67 of file monexamine.cpp.
{
    enum choices {
        swap_pos = 0,
        push_zlave,
        lead,
        stop_lead,
        rename,
        attach_bag,
        remove_bag,
        drop_all,
        give_items,
        mon_armor_add,
        mon_harness_remove,
        mon_armor_remove,
        leash,
        unleash,
        play_with_pet,
        pheromone,
        milk,
        shear,
        pay,
        attach_saddle,
        remove_saddle,
        mount,
        tie,
        untie,
        remove_bat,
        insert_bat,
        check_bat,
        disable_pet,
        attack
    };
    uilist amenu;
    std::string pet_name = z.get_name();
    bool is_zombie = z.type->in_species( ZOMBIE );
    const auto mon_item_id = z.type->revert_to_itype;
    if( is_zombie ) {
        pet_name = _( "zombie slave" );
    }
    amenu.text = string_format( _( "What to do with your %s?" ), pet_name );
    amenu.addentry( swap_pos, true, 's', _( "Swap positions" ) );
    amenu.addentry( push_zlave, true, 'p', _( "Push %s" ), pet_name );
    if( z.has_effect( effect_leashed ) ) {
        if( z.has_effect( effect_led_by_leash ) ) {
            amenu.addentry( stop_lead, true, 'p', _( "Stop leading %s" ), pet_name );
        } else {
            amenu.addentry( lead, true, 'p', _( "Lead %s by the leash" ), pet_name );
        }
    }
    amenu.addentry( rename, true, 'e', _( "Rename" ) );
    amenu.addentry( attack, true, 'A', _( "Attack" ) );
    if( z.has_effect( effect_has_bag ) ) {
        amenu.addentry( give_items, true, 'g', _( "Place items into bag" ) );
        amenu.addentry( remove_bag, true, 'b', _( "Remove bag from %s" ), pet_name );
        if( !z.inv.empty() ) {
            amenu.addentry( drop_all, true, 'd', _( "Remove all items from bag" ) );
        }
    } else if( !z.has_flag( MF_RIDEABLE_MECH ) ) {
        amenu.addentry( attach_bag, true, 'b', _( "Attach bag to %s" ), pet_name );
    }
    if( z.has_effect( effect_harnessed ) ) {
        amenu.addentry( mon_harness_remove, true, 'H', _( "Remove vehicle harness from %s" ), pet_name );
    }
    if( z.has_effect( effect_monster_armor ) ) {
        amenu.addentry( mon_armor_remove, true, 'a', _( "Remove armor from %s" ), pet_name );
    } else if( !z.has_flag( MF_RIDEABLE_MECH ) ) {
        amenu.addentry( mon_armor_add, true, 'a', _( "Equip %s with armor" ), pet_name );
    }
    if( z.has_flag( MF_BIRDFOOD ) || z.has_flag( MF_CATFOOD ) || z.has_flag( MF_DOGFOOD ) ||
        z.has_flag( MF_CANPLAY ) ) {
        amenu.addentry( play_with_pet, true, 'y', _( "Play with %s" ), pet_name );
    }
    if( z.has_effect( effect_tied ) ) {
        amenu.addentry( untie, true, 'u', _( "Untie" ) );
    }
    if( z.has_effect( effect_leashed ) && !z.has_effect( effect_tied ) ) {
        amenu.addentry( tie, true, 't', _( "Tie" ) );
        amenu.addentry( unleash, true, 'T', _( "Remove leash from %s" ), pet_name );
    }
    if( !z.has_effect( effect_leashed ) && !z.has_flag( MF_RIDEABLE_MECH ) ) {
        Character &player_character = g->u;
        std::vector<item *> rope_inv = player_character.items_with( []( const item & it ) {
            return it.has_flag( "TIE_UP" );
        } );
        if( !rope_inv.empty() ) {
            amenu.addentry( leash, true, 'l', _( "Attach leash to %s" ), pet_name );
        } else {
            amenu.addentry( leash, false, 'l', _( "You need any type of rope to tie %s in place" ),
                            pet_name );
        }
    }
    if( is_zombie ) {
        amenu.addentry( pheromone, true, 'z', _( "Tear out pheromone ball" ) );
    }
    if( z.has_flag( MF_MILKABLE ) ) {
        amenu.addentry( milk, true, 'm', _( "Milk %s" ), pet_name );
    }
    if( z.has_flag( MF_SHEARABLE ) ) {
        bool available = true;
        if( season_of_year( calendar::turn ) == WINTER ) {
            amenu.addentry( shear, false, 'S',
                            _( "This animal would freeze if you shear it during winter." ) );
            available = false;
        } else if( z.has_effect( effect_sheared ) ) {
            amenu.addentry( shear, false, 'S', _( "This animal is not ready to be sheared again yet." ) );
            available = false;
        }
        if( available ) {
            if( g->u.has_quality( qual_shear, 1 ) ) {
                amenu.addentry( shear, true, 'S', _( "Shear %s." ), pet_name );
            } else {
                amenu.addentry( shear, false, 'S', _( "You cannot shear this animal without shears." ) );
            }
        }
    }
    if( z.has_flag( MF_PET_MOUNTABLE ) && !z.has_effect( effect_saddled ) &&
        g->u.has_item_with_flag( "TACK" ) && g->u.get_skill_level( skill_survival ) >= 1 ) {
        amenu.addentry( attach_saddle, true, 'h', _( "Tack up %s" ), pet_name );
    } else if( z.has_flag( MF_PET_MOUNTABLE ) && z.has_effect( effect_saddled ) ) {
        amenu.addentry( remove_saddle, true, 'h', _( "Remove tack from %s" ), pet_name );
    } else if( z.has_flag( MF_PET_MOUNTABLE ) && !z.has_effect( effect_saddled ) &&
               g->u.has_item_with_flag( "TACK" ) && g->u.get_skill_level( skill_survival ) < 1 ) {
        amenu.addentry( remove_saddle, false, 'h', _( "You don't know how to saddle %s" ), pet_name );
    }
    if( z.has_flag( MF_PAY_BOT ) ) {
        amenu.addentry( pay, true, 'f', _( "Manage your friendship with %s" ), pet_name );
    }
    if( !z.has_flag( MF_RIDEABLE_MECH ) ) {
        if( z.has_flag( MF_PET_MOUNTABLE ) && g->u.can_mount( z ) ) {
            amenu.addentry( mount, true, 'r', _( "Mount %s" ), pet_name );
        } else if( !z.has_flag( MF_PET_MOUNTABLE ) ) {
            amenu.addentry( mount, false, 'r', _( "%s cannot be mounted" ), pet_name );
        } else if( z.get_size() <= g->u.get_size() ) {
            amenu.addentry( mount, false, 'r', _( "%s is too small to carry your weight" ), pet_name );
        } else if( g->u.get_skill_level( skill_survival ) < 1 ) {
            amenu.addentry( mount, false, 'r', _( "You have no knowledge of riding at all" ) );
        } else if( g->u.get_weight() >= z.get_weight() * z.get_mountable_weight_ratio() ) {
            amenu.addentry( mount, false, 'r', _( "You are too heavy to mount %s" ), pet_name );
        } else if( !z.has_effect( effect_saddled ) && g->u.get_skill_level( skill_survival ) < 4 ) {
            amenu.addentry( mount, false, 'r', _( "You are not skilled enough to ride without a saddle" ) );
        }
    } else {
        const itype &type = *z.type->mech_battery;
        int max_charge = type.magazine->capacity;
        float charge_percent;
        if( z.battery_item ) {
            charge_percent = static_cast<float>( z.battery_item->ammo_remaining() ) / max_charge * 100;
        } else {
            charge_percent = 0.0;
        }
        amenu.addentry( check_bat, false, 'c', _( "%s battery level is %d%%" ), z.get_name(),
                        static_cast<int>( charge_percent ) );
        if( g->u.weapon.is_null() && z.battery_item ) {
            amenu.addentry( mount, true, 'r', _( "Climb into the mech and take control" ) );
        } else if( !g->u.weapon.is_null() ) {
            amenu.addentry( mount, false, 'r', _( "You cannot pilot the mech whilst wielding something" ) );
        } else if( !z.battery_item ) {
            amenu.addentry( mount, false, 'r', _( "This mech has a dead battery and won't turn on" ) );
        }
        if( z.battery_item ) {
            amenu.addentry( remove_bat, true, 'x', _( "Remove the mech's battery pack" ) );
        } else if( g->u.has_amount( z.type->mech_battery, 1 ) ) {
            amenu.addentry( insert_bat, true, 'x', _( "Insert a new battery pack" ) );
        } else {
            amenu.addentry( insert_bat, false, 'x', _( "You need a %s to power this mech" ), type.nname( 1 ) );
        }
    }
    if( !mon_item_id.is_empty() && !z.has_flag( MF_RIDEABLE_MECH ) ) {
        if( z.has_effect( effect_has_bag ) || z.has_effect( effect_monster_armor ) ||
            z.has_effect( effect_leashed ) || z.has_effect( effect_saddled ) ) {
            amenu.addentry( disable_pet, true, 'D', _( "Remove items and deactivate the %s" ), pet_name );
        } else {
            amenu.addentry( disable_pet, true, 'D', _( "Deactivate the %s" ), pet_name );
        }
    }
    amenu.query();
    int choice = amenu.ret;
    switch( choice ) {
        case swap_pos:
            swap( z );
            break;
        case push_zlave:
            push( z );
            break;
        case lead:
            start_leading( z );
            break;
        case stop_lead:
            stop_leading( z );
            break;
        case rename:
            rename_pet( z );
            break;
        case attach_bag:
            attach_bag_to( z );
            break;
        case remove_bag:
            remove_bag_from( z );
            break;
        case drop_all:
            dump_items( z );
            break;
        case give_items:
            return give_items_to( z );
        case mon_armor_add:
            return add_armor( z );
        case mon_harness_remove:
            remove_harness( z );
            break;
        case mon_armor_remove:
            remove_armor( z );
            break;
        case play_with_pet:
            if( query_yn( _( "Spend a few minutes to play with your %s?" ), pet_name ) ) {
                play_with( z );
            }
            break;
        case pheromone:
            if( query_yn( _( "Really kill the zombie slave?" ) ) ) {
                kill_zslave( z );
            }
            break;
        case leash:
            add_leash( z );
            break;
        case unleash:
            remove_leash( z );
            break;
        case attach_saddle:
        case remove_saddle:
            attach_or_remove_saddle( z );
            break;
        case mount:
            mount_pet( z );
            break;
        case tie:
            tie_pet( z );
            break;
        case untie:
            untie_pet( z );
            break;
        case milk:
            milk_source( z );
            break;
        case shear:
            shear_animal( z );
            break;
        case pay:
            pay_bot( z );
            break;
        case remove_bat:
            remove_battery( z );
            break;
        case insert_bat:
            insert_battery( z );
            break;
        case check_bat:
            break;
        case disable_pet:
            if( query_yn( _( "Really deactivate your %s?" ), pet_name ) ) {
                deactivate_pet( z );
            }
            break;
        case attack:
            if( query_yn( _( "You may be attacked!  Proceed?" ) ) ) {
                get_player_character().melee_attack( z, true );
            }
            break;
        default:
            break;
    }
    return true;
}
References _, add_armor(), add_leash(), uilist::addentry(), attach_bag_to(), attach_or_remove_saddle(), available, monster::battery_item, deactivate_pet(), dump_items(), effect_harnessed, effect_has_bag, effect_leashed, effect_led_by_leash, effect_monster_armor, effect_saddled, effect_sheared, effect_tied, g, monster::get_mountable_weight_ratio(), monster::get_name(), get_player_character(), monster::get_size(), monster::get_weight(), give_items_to(), Creature::has_effect(), item::has_flag(), monster::has_flag(), mtype::in_species(), insert_battery(), monster::inv, visitable< T >::items_with(), kill_zslave(), mtype::mech_battery, Character::melee_attack(), MF_BIRDFOOD, MF_CANPLAY, MF_CATFOOD, MF_DOGFOOD, MF_MILKABLE, MF_PAY_BOT, MF_PET_MOUNTABLE, MF_RIDEABLE_MECH, MF_SHEARABLE, milk_source(), mount_pet(), pay_bot(), iuse::pheromone(), play_with(), push(), qual_shear, uilist::query(), query_yn(), remove_armor(), remove_bag_from(), remove_battery(), remove_harness(), remove_leash(), rename_pet(), uilist::ret, mtype::revert_to_itype, season_of_year(), shear_animal(), skill_survival, start_leading(), stop_leading(), string_format(), cata::swap(), swap_pos(), uilist::text, tie_pet(), calendar::turn, type, monster::type, untie_pet(), WINTER, and ZOMBIE.
Referenced by game::examine().
play_with()
void monexamine::play_with (monster & z)
Definition at line 776 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    g->u.assign_activity( ACT_PLAY_WITH_PET, rng( 50, 125 ) * 100 );
    g->u.activity.str_values.push_back( pet_name );
}
References ACT_PLAY_WITH_PET, g, monster::get_name(), and rng().
Referenced by pet_menu().
push()
void monexamine::push (monster & z)
Strength increases chance to successfully push your pet
Definition at line 604 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    g->u.moves -= 30;
    ///\EFFECT_STR increases chance to successfully push your pet
    if( !one_in( g->u.str_cur ) ) {
        add_msg( _( "You pushed the %s." ), pet_name );
    } else {
        add_msg( _( "You pushed the %s, but it resisted." ), pet_name );
        return;
    }
    point delta( z.posx() - g->u.posx(), z.posy() - g->u.posy() );
    z.move_to( tripoint( z.posx() + delta.x, z.posy() + delta.y, z.posz() ) );
}
References _, add_msg(), g, monster::get_name(), monster::move_to(), one_in(), monster::posx(), monster::posy(), monster::posz(), point::x, and point::y.
Referenced by mfriend_menu(), game::npc_menu(), pet_menu(), and game::update_stair_monsters().
remove_armor()
void monexamine::remove_armor (monster & z)
Definition at line 759 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    if( z.armor_item ) {
        z.armor_item->erase_var( "pet_armor" );
        g->m.add_item_or_charges( z.pos(), *z.armor_item );
        add_msg( pgettext( "pet armor", "You remove the %1$s from %2$s." ), z.armor_item->display_name(),
                 pet_name );
        z.armor_item.reset();
        // TODO: removing armor from a horse takes a lot longer than 2 seconds. This should be a long action.
        g->u.moves -= 200;
    } else {
        add_msg( m_bad, _( "Your %1$s isn't wearing armor!" ), pet_name );
    }
    z.remove_effect( effect_monster_armor );
}
References _, add_msg(), monster::armor_item, effect_monster_armor, g, monster::get_name(), m_bad, pgettext(), monster::pos(), and Creature::remove_effect().
Referenced by deactivate_pet(), and pet_menu().
remove_bag_from()
void monexamine::remove_bag_from (monster & z)
Definition at line 657 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    if( z.storage_item ) {
        if( !z.inv.empty() ) {
            dump_items( z );
        }
        g->m.add_item_or_charges( g->u.pos(), *z.storage_item );
        add_msg( _( "You remove the %1$s from %2$s." ), z.storage_item->display_name(), pet_name );
        z.storage_item.reset();
        g->u.moves -= 200;
    } else {
        add_msg( m_bad, _( "Your %1$s doesn't have a bag!" ), pet_name );
    }
    z.remove_effect( effect_has_bag );
}
References _, add_msg(), dump_items(), effect_has_bag, g, monster::get_name(), monster::inv, m_bad, Creature::remove_effect(), and monster::storage_item.
Referenced by deactivate_pet(), and pet_menu().
remove_battery()
void monexamine::remove_battery (monster & z)
Definition at line 384 of file monexamine.cpp.
{
    g->m.add_item_or_charges( g->u.pos(), *z.battery_item );
    z.battery_item.reset();
}
References monster::battery_item, and g.
Referenced by pet_menu().
remove_harness()
void monexamine::remove_harness (monster & z)
Definition at line 753 of file monexamine.cpp.
{
    z.remove_effect( effect_harnessed );
    add_msg( m_info, _( "You unhitch %s from the vehicle." ), z.get_name() );
}
References _, add_msg(), effect_harnessed, monster::get_name(), m_info, and Creature::remove_effect().
Referenced by pet_menu().
remove_leash()
void monexamine::remove_leash (monster & z)
Definition at line 832 of file monexamine.cpp.
{
    if( !z.has_effect( effect_leashed ) ) {
        return;
    }
    z.remove_effect( effect_led_by_leash );
    z.remove_effect( effect_leashed );
    if( z.tied_item ) {
        get_player_character().i_add( *z.tied_item );
        z.tied_item.reset();
    }
    add_msg( _( "You remove the leash from your %s." ), z.get_name() );
}
References _, add_msg(), effect_leashed, effect_led_by_leash, monster::get_name(), get_player_character(), Creature::has_effect(), Character::i_add(), Creature::remove_effect(), and monster::tied_item.
Referenced by deactivate_pet(), and pet_menu().
rename_pet()
void monexamine::rename_pet (monster & z)
Definition at line 621 of file monexamine.cpp.
{
    std::string unique_name = string_input_popup()
                              .title( _( "Enter new pet name:" ) )
                              .width( 20 )
                              .query_string();
    if( !unique_name.empty() ) {
        z.unique_name = unique_name;
    }
}
References _, string_input_popup::query_string(), string_input_popup::title(), monster::unique_name, and string_input_popup::width().
Referenced by mfriend_menu(), and pet_menu().
shear_animal()
void monexamine::shear_animal (monster & z)
Definition at line 348 of file monexamine.cpp.
{
    const int moves = to_moves<int>( time_duration::from_minutes( 30 / g->u.max_quality(
                                         qual_shear ) ) );
    g->u.assign_activity( activity_id( "ACT_SHEAR" ), moves, -1 );
    g->u.activity.coords.push_back( g->m.getabs( z.pos() ) );
    // pin the sheep in place if it isn't already
    if( !z.has_effect( effect_tied ) ) {
        z.add_effect( effect_tied, 1_turns );
        g->u.activity.str_values.push_back( "temp_tie" );
    }
    g->u.activity.targets.push_back( item_location( g->u, g->u.best_quality_item( qual_shear ) ) );
    add_msg( _( "You start shearing the %s." ), z.get_name() );
}
References _, monster::add_effect(), add_msg(), effect_tied, time_duration::from_minutes(), g, monster::get_name(), Creature::has_effect(), monster::pos(), and qual_shear.
Referenced by pet_menu().
start_leading()
void monexamine::start_leading (monster & z)
Definition at line 871 of file monexamine.cpp.
{
    if( z.has_effect( effect_led_by_leash ) ) {
        return;
    }
    if( z.has_effect( effect_tied ) ) {
        monexamine::untie_pet( z );
    }
    z.add_effect( effect_led_by_leash, 1_turns );
    z.get_effect( effect_led_by_leash ).set_permanent();
    add_msg( _( "You take hold of the %s's leash to make it follow you." ), z.get_name() );
}
References _, monster::add_effect(), add_msg(), effect_led_by_leash, effect_tied, Creature::get_effect(), monster::get_name(), Creature::has_effect(), effect::set_permanent(), and untie_pet().
Referenced by pet_menu().
stop_leading()
void monexamine::stop_leading (monster & z)
Definition at line 885 of file monexamine.cpp.
{
    if( !z.has_effect( effect_led_by_leash ) ) {
        return;
    }
    z.remove_effect( effect_led_by_leash );
    // The pet may or may not stop following so don't print that here
    add_msg( _( "You release the %s's leash." ), z.get_name() );
}
References _, add_msg(), effect_led_by_leash, monster::get_name(), Creature::has_effect(), and Creature::remove_effect().
Referenced by pet_menu().
swap()
void monexamine::swap (monster & z)
Strength increases chance to successfully swap positions with your pet \EFFECT_DEX increases chance to successfully swap positions with your pet
Definition at line 580 of file monexamine.cpp.
{
    std::string pet_name = z.get_name();
    g->u.moves -= 150;
    ///\EFFECT_STR increases chance to successfully swap positions with your pet
    ///\EFFECT_DEX increases chance to successfully swap positions with your pet
    if( !one_in( ( g->u.str_cur + g->u.dex_cur ) / 6 ) ) {
        bool t = z.has_effect( effect_tied );
        if( t ) {
            z.remove_effect( effect_tied );
        }
        g->swap_critters( g->u, z );
        if( t ) {
            z.add_effect( effect_tied, 1_turns, num_bp );
        }
        add_msg( _( "You swap positions with your %s." ), pet_name );
    } else {
        add_msg( _( "You fail to budge your %s!" ), pet_name );
    }
}
References _, monster::add_effect(), add_msg(), effect_tied, g, monster::get_name(), Creature::has_effect(), num_bp, one_in(), and Creature::remove_effect().
tie_pet()
void monexamine::tie_pet (monster & z)
Definition at line 847 of file monexamine.cpp.
{
    if( z.has_effect( effect_tied ) ) {
        return;
    }
    z.add_effect( effect_tied, 1_turns );
    z.get_effect( effect_tied ).set_permanent();
    add_msg( _( "You tie your %s." ), z.get_name() );
}
References _, monster::add_effect(), add_msg(), effect_tied, Creature::get_effect(), monster::get_name(), Creature::has_effect(), and effect::set_permanent().
Referenced by pet_menu().
untie_pet()
void monexamine::untie_pet (monster & z)
Definition at line 857 of file monexamine.cpp.
{
    if( !z.has_effect( effect_tied ) ) {
        return;
    }
    z.remove_effect( effect_tied );
    if( !z.has_effect( effect_leashed ) ) {
        // migration code dealing with animals tied before leashing was introduced
        z.add_effect( effect_leashed, 1_turns );
        z.get_effect( effect_leashed ).set_permanent();
    }
    add_msg( _( "You untie your %s." ), z.get_name() );
}
References _, monster::add_effect(), add_msg(), effect_leashed, effect_tied, Creature::get_effect(), monster::get_name(), Creature::has_effect(), Creature::remove_effect(), and effect::set_permanent().
Referenced by deactivate_pet(), pet_menu(), and start_leading().