Cataclysm BN: anonymous_namespace{game_inventory.cpp} Namespace Reference
anonymous_namespace{game_inventory.cpp} Namespace Reference
Functions
std::string good_bad_none (int value)
std::string highlight_good_bad_none (int value)
int anesthetic_requirement (int mult)
Function Documentation
anesthetic_requirement()
int anonymous_namespace{game_inventory.cpp}::anesthetic_requirement (int mult)
Definition at line 128 of file game_inventory.cpp.
{
    const requirement_data req_anesth = *requirement_id( "anesthetic" ) * mult;
    if( !req_anesth.get_tools().empty() && !req_anesth.get_tools().front().empty() ) {
        return req_anesth.get_tools().front().front().count;
    }
    return 0;
}
References requirement_data::get_tools().
Referenced by bionic_install_preset::get_anesth_amount(), bionic_uninstall_preset::get_anesth_amount(), bionic_install_preset::get_denial(), and bionic_uninstall_preset::get_denial().
good_bad_none()
std::string anonymous_namespace{game_inventory.cpp}::good_bad_none (int value)
Definition at line 108 of file game_inventory.cpp.
{
    if( value > 0 ) {
        return string_format( "<good>+%d</good>", value );
    } else if( value < 0 ) {
        return string_format( "<bad>%d</bad>", value );
    }
    return std::string();
}
References string_format().
Referenced by comestible_inventory_preset::comestible_inventory_preset(), gunmod_inventory_preset::gunmod_inventory_preset(), and read_inventory_preset::read_inventory_preset().
highlight_good_bad_none()
std::string anonymous_namespace{game_inventory.cpp}::highlight_good_bad_none (int value)
Definition at line 118 of file game_inventory.cpp.
{
    if( value > 0 ) {
        return string_format( "<color_yellow_green>+%d</color>", value );
    } else if( value < 0 ) {
        return string_format( "<color_yellow_red>%d</color>", value );
    }
    return string_format( "<color_yellow>%d</color>", value );
}
References string_format().
Referenced by comestible_inventory_preset::comestible_inventory_preset().