Cataclysm BN: anonymous_namespace{profession.cpp} Namespace Reference
anonymous_namespace{profession.cpp} Namespace Reference
Variables
generic_factory< profession > all_profs ("profession")
const profession_id generic_profession_id ("unemployed")
Variable Documentation
all_profs
generic_factory< profession > anonymous_namespace{profession.cpp}::all_profs("profession") ("profession")
Referenced by profession::check_definitions(), profession::get_all(), string_id< T >::is_valid(), profession::load_profession(), string_id< T >::obj(), and profession::reset().
generic_profession_id
const profession_id anonymous_namespace{profession.cpp}::generic_profession_id("unemployed") ("unemployed")
Referenced by profession::generic(), and profession::has_initialized().