Cataclysm BN: detail::dragonbox Namespace Reference
detail::dragonbox Namespace Reference
Classes
struct cache_accessor
struct cache_accessor< double >
struct cache_accessor< float >
struct decimal_fp
struct float_info
struct float_info< double >
struct float_info< float >
Functions
FMT_SAFEBUFFERS uint128_wrapper umul128 (uint64_t x, uint64_t y) FMT_NOEXCEPT
FMT_SAFEBUFFERS uint64_t umul128_upper64 (uint64_t x, uint64_t y) FMT_NOEXCEPT
FMT_SAFEBUFFERS uint64_t umul192_upper64 (uint64_t x, uint128_wrapper y) FMT_NOEXCEPT
uint32_t umul96_upper32 (uint32_t x, uint64_t y) FMT_NOEXCEPT
FMT_SAFEBUFFERS uint64_t umul192_middle64 (uint64_t x, uint128_wrapper y) FMT_NOEXCEPT
uint64_t umul96_lower64 (uint32_t x, uint64_t y) FMT_NOEXCEPT
int floor_log10_pow2 (int e) FMT_NOEXCEPT
int floor_log2_pow10 (int e) FMT_NOEXCEPT
int floor_log10_pow2_minus_log10_4_over_3 (int e) FMT_NOEXCEPT
bool divisible_by_power_of_2 (uint32_t x, int exp) FMT_NOEXCEPT
bool divisible_by_power_of_2 (uint64_t x, int exp) FMT_NOEXCEPT
bool divisible_by_power_of_5 (uint32_t x, int exp) FMT_NOEXCEPT
bool divisible_by_power_of_5 (uint64_t x, int exp) FMT_NOEXCEPT
template<int N>
bool check_divisibility_and_divide_by_pow5 (uint32_t &n) FMT_NOEXCEPT
template<int N>
uint32_t small_division_by_pow10 (uint32_t n) FMT_NOEXCEPT
uint32_t divide_by_10_to_kappa_plus_1 (uint32_t n) FMT_NOEXCEPT
uint64_t divide_by_10_to_kappa_plus_1 (uint64_t n) FMT_NOEXCEPT
template<class T >
bool is_left_endpoint_integer_shorter_interval (int exponent) FMT_NOEXCEPT
template<class T >
bool is_endpoint_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k) FMT_NOEXCEPT
template<class T >
bool is_center_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k) FMT_NOEXCEPT
FMT_ALWAYS_INLINE int remove_trailing_zeros (uint32_t &n) FMT_NOEXCEPT
FMT_ALWAYS_INLINE int remove_trailing_zeros (uint64_t &n) FMT_NOEXCEPT
template<class T >
FMT_ALWAYS_INLINE FMT_SAFEBUFFERS decimal_fp< T > shorter_interval_case (int exponent) FMT_NOEXCEPT
template<typename T >
FMT_SAFEBUFFERS decimal_fp< T > to_decimal (T x) FMT_NOEXCEPT
template<typename T >
FMT_API decimal_fp< T > to_decimal (T x) FMT_NOEXCEPT
Function Documentation
check_divisibility_and_divide_by_pow5()
template<int N> bool detail::dragonbox::check_divisibility_and_divide_by_pow5 (uint32_t & n)
Definition at line 1944 of file fmtlib_format-inl.h.
{
    static constexpr struct {
        uint32_t magic_number;
        int bits_for_comparison;
        uint32_t threshold;
        int shift_amount;
    } infos[] = {{0xcccd, 16, 0x3333, 18}, {0xa429, 8, 0x0a, 20}};
    constexpr auto info = infos[N - 1];
    n *= info.magic_number;
    const uint32_t comparison_mask = ( 1u << info.bits_for_comparison ) - 1;
    bool result = ( n & comparison_mask ) <= info.threshold;
    n >>= info.shift_amount;
    return result;
}
Referenced by to_decimal().
divide_by_10_to_kappa_plus_1() [1/2]
uint32_t detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint32_t n) inline
Definition at line 1973 of file fmtlib_format-inl.h.
{
    return n / float_info<float>::big_divisor;
}
Referenced by to_decimal().
divide_by_10_to_kappa_plus_1() [2/2]
uint64_t detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint64_t n) inline
Definition at line 1977 of file fmtlib_format-inl.h.
{
    return umul128_upper64( n, 0x83126e978d4fdf3c ) >> 9;
}
References umul128_upper64().
divisible_by_power_of_2() [1/2]
bool detail::dragonbox::divisible_by_power_of_2 (uint32_t x, int exp) inline
Definition at line 1909 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( exp >= 1, "" );
    FMT_ASSERT( x != 0, "" );
#ifdef FMT_BUILTIN_CTZ
    return FMT_BUILTIN_CTZ( x ) >= exp;
#else
    return exp < num_bits<uint32_t>() && x == ( ( x >> exp ) << exp );
#endif
}
References detail::exp, and FMT_ASSERT.
Referenced by is_center_integer().
divisible_by_power_of_2() [2/2]
bool detail::dragonbox::divisible_by_power_of_2 (uint64_t x, int exp) inline
Definition at line 1918 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( exp >= 1, "" );
    FMT_ASSERT( x != 0, "" );
#ifdef FMT_BUILTIN_CTZLL
    return FMT_BUILTIN_CTZLL( x ) >= exp;
#else
    return exp < num_bits<uint64_t>() && x == ( ( x >> exp ) << exp );
#endif
}
References detail::exp, and FMT_ASSERT.
divisible_by_power_of_5() [1/2]
bool detail::dragonbox::divisible_by_power_of_5 (uint32_t x, int exp) inline
Definition at line 1929 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( exp <= 10, "too large exponent" );
    return x * data::divtest_table_for_pow5_32[exp].mod_inv <=
    data::divtest_table_for_pow5_32[exp].max_quotient;
}
References detail::basic_data< T >::divtest_table_for_pow5_32, detail::exp, and FMT_ASSERT.
Referenced by is_center_integer(), and is_endpoint_integer().
divisible_by_power_of_5() [2/2]
bool detail::dragonbox::divisible_by_power_of_5 (uint64_t x, int exp) inline
Definition at line 1934 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( exp <= 23, "too large exponent" );
    return x * data::divtest_table_for_pow5_64[exp].mod_inv <=
    data::divtest_table_for_pow5_64[exp].max_quotient;
}
References detail::basic_data< T >::divtest_table_for_pow5_64, detail::exp, and FMT_ASSERT.
floor_log10_pow2()
int detail::dragonbox::floor_log10_pow2 (int e) inline
Definition at line 1879 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( e <= 1700 && e >= -1700, "too large exponent" );
    const int shift = 22;
    return ( e * static_cast<int>( data::log10_2_significand >>( 64 - shift ) ) ) >>
            shift;
}
References FMT_ASSERT, and detail::basic_data< T >::log10_2_significand.
Referenced by to_decimal().
floor_log10_pow2_minus_log10_4_over_3()
int detail::dragonbox::floor_log10_pow2_minus_log10_4_over_3 (int e) inline
Definition at line 1897 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( e <= 1700 && e >= -1700, "too large exponent" );
    const uint64_t log10_4_over_3_fractional_digits = 0x1ffbfc2bbc780375;
    const int shift_amount = 22;
    return ( e * static_cast<int>( data::log10_2_significand >>
                                   ( 64 - shift_amount ) ) -
             static_cast<int>( log10_4_over_3_fractional_digits >>
                               ( 64 - shift_amount ) ) ) >>
                                       shift_amount;
}
References FMT_ASSERT, and detail::basic_data< T >::log10_2_significand.
Referenced by shorter_interval_case().
floor_log2_pow10()
int detail::dragonbox::floor_log2_pow10 (int e) inline
Definition at line 1887 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( e <= 1233 && e >= -1233, "too large exponent" );
    const uint64_t log2_10_integer_part = 3;
    const uint64_t log2_10_fractional_digits = 0x5269e12f346e2bf9;
    const int shift_amount = 19;
    return ( e * static_cast<int>(
                 ( log2_10_integer_part << shift_amount ) |
                 ( log2_10_fractional_digits >> ( 64 - shift_amount ) ) ) ) >>
                         shift_amount;
}
References FMT_ASSERT.
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), shorter_interval_case(), and to_decimal().
is_center_integer()
template<class T > bool detail::dragonbox::is_center_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k)
Definition at line 2171 of file fmtlib_format-inl.h.
{
    // Exponent for 5 is negative.
    if( exponent > float_info<T>::divisibility_check_by_5_threshold )
    {
        return false;
    }
    if( exponent > float_info<T>::case_fc_upper_threshold )
    {
        return divisible_by_power_of_5( two_f, minus_k );
    }
    // Both exponents are nonnegative.
    if( exponent >= float_info<T>::case_fc_lower_threshold )
    {
        return true;
    }
    // Exponent for 2 is negative.
    return divisible_by_power_of_2( two_f, minus_k - exponent + 1 );
}
References divisible_by_power_of_2(), and divisible_by_power_of_5().
is_endpoint_integer()
template<class T > bool detail::dragonbox::is_endpoint_integer (typename float_info< T >::carrier_uint two_f, int exponent, int minus_k)
Definition at line 2151 of file fmtlib_format-inl.h.
{
    if( exponent < float_info<T>::case_fc_pm_half_lower_threshold )
    {
        return false;
    }
    // For k >= 0.
    if( exponent <= float_info<T>::case_fc_pm_half_upper_threshold )
    {
        return true;
    }
    // For k < 0.
    if( exponent > float_info<T>::divisibility_check_by_5_threshold )
    {
        return false;
    }
    return divisible_by_power_of_5( two_f, minus_k );
}
References divisible_by_power_of_5().
is_left_endpoint_integer_shorter_interval()
template<class T > bool detail::dragonbox::is_left_endpoint_integer_shorter_interval (int exponent)
Definition at line 2143 of file fmtlib_format-inl.h.
{
    return exponent >=
    float_info <
    T >::case_shorter_interval_left_endpoint_lower_threshold &&
    exponent <=
    float_info<T>::case_shorter_interval_left_endpoint_upper_threshold;
}
remove_trailing_zeros() [1/2]
FMT_ALWAYS_INLINE int detail::dragonbox::remove_trailing_zeros (uint32_t & n)
Definition at line 2192 of file fmtlib_format-inl.h.
{
#ifdef FMT_BUILTIN_CTZ
    int t = FMT_BUILTIN_CTZ( n );
#else
    int t = ctz( n );
#endif
    if( t > float_info<float>::max_trailing_zeros )
    {
        t = float_info<float>::max_trailing_zeros;
    }
    const uint32_t mod_inv1 = 0xcccccccd;
    const uint32_t max_quotient1 = 0x33333333;
    const uint32_t mod_inv2 = 0xc28f5c29;
    const uint32_t max_quotient2 = 0x0a3d70a3;
    int s = 0;
    for( ; s < t - 1; s += 2 )
    {
        if( n * mod_inv2 > max_quotient2 ) {
            break;
        }
        n *= mod_inv2;
    }
    if( s < t && n * mod_inv1 <= max_quotient1 )
    {
        n *= mod_inv1;
        ++s;
    }
    n >>= s;
    return s;
}
Referenced by shorter_interval_case(), and to_decimal().
remove_trailing_zeros() [2/2]
FMT_ALWAYS_INLINE int detail::dragonbox::remove_trailing_zeros (uint64_t & n)
Definition at line 2226 of file fmtlib_format-inl.h.
{
#ifdef FMT_BUILTIN_CTZLL
    int t = FMT_BUILTIN_CTZLL( n );
#else
    int t = ctzll( n );
#endif
    if( t > float_info<double>::max_trailing_zeros )
    {
        t = float_info<double>::max_trailing_zeros;
    }
    // Divide by 10^8 and reduce to 32-bits
    // Since ret_value.significand <= (2^64 - 1) / 1000 < 10^17,
    // both of the quotient and the r should fit in 32-bits
    const uint32_t mod_inv1 = 0xcccccccd;
    const uint32_t max_quotient1 = 0x33333333;
    const uint64_t mod_inv8 = 0xc767074b22e90e21;
    const uint64_t max_quotient8 = 0x00002af31dc46118;
    // If the number is divisible by 1'0000'0000, work with the quotient
    if( t >= 8 )
    {
        auto quotient_candidate = n * mod_inv8;
        if( quotient_candidate <= max_quotient8 ) {
            auto quotient = static_cast<uint32_t>( quotient_candidate >> 8 );
            int s = 8;
            for( ; s < t; ++s ) {
                if( quotient * mod_inv1 > max_quotient1 ) {
                    break;
                }
                quotient *= mod_inv1;
            }
            quotient >>= ( s - 8 );
            n = quotient;
            return s;
        }
    }
    // Otherwise, work with the remainder
    auto quotient = static_cast<uint32_t>( n / 100000000 );
    auto remainder = static_cast<uint32_t>( n - 100000000 * quotient );
    if( t == 0 || remainder * mod_inv1 > max_quotient1 )
    {
        return 0;
    }
    remainder *= mod_inv1;
    if( t == 1 || remainder * mod_inv1 > max_quotient1 )
    {
        n = ( remainder >> 1 ) + quotient * 10000000ULL;
        return 1;
    }
    remainder *= mod_inv1;
    if( t == 2 || remainder * mod_inv1 > max_quotient1 )
    {
        n = ( remainder >> 2 ) + quotient * 1000000ULL;
        return 2;
    }
    remainder *= mod_inv1;
    if( t == 3 || remainder * mod_inv1 > max_quotient1 )
    {
        n = ( remainder >> 3 ) + quotient * 100000ULL;
        return 3;
    }
    remainder *= mod_inv1;
    if( t == 4 || remainder * mod_inv1 > max_quotient1 )
    {
        n = ( remainder >> 4 ) + quotient * 10000ULL;
        return 4;
    }
    remainder *= mod_inv1;
    if( t == 5 || remainder * mod_inv1 > max_quotient1 )
    {
        n = ( remainder >> 5 ) + quotient * 1000ULL;
        return 5;
    }
    remainder *= mod_inv1;
    if( t == 6 || remainder * mod_inv1 > max_quotient1 )
    {
        n = ( remainder >> 6 ) + quotient * 100ULL;
        return 6;
    }
    remainder *= mod_inv1;
    n = ( remainder >> 7 ) + quotient * 10ULL;
    return 7;
}
shorter_interval_case()
template<class T > FMT_ALWAYS_INLINE FMT_SAFEBUFFERS decimal_fp< T > detail::dragonbox::shorter_interval_case (int exponent)
Definition at line 2324 of file fmtlib_format-inl.h.
{
    decimal_fp<T> ret_value;
    // Compute k and beta
    const int minus_k = floor_log10_pow2_minus_log10_4_over_3( exponent );
    const int beta_minus_1 = exponent + floor_log2_pow10( -minus_k );
    // Compute xi and zi
    using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
    const cache_entry_type cache = cache_accessor<T>::get_cached_power( -minus_k );
    auto xi = cache_accessor<T>::compute_left_endpoint_for_shorter_interval_case(
        cache, beta_minus_1 );
    auto zi = cache_accessor<T>::compute_right_endpoint_for_shorter_interval_case(
        cache, beta_minus_1 );
    // If the left endpoint is not an integer, increase it
    if( !is_left_endpoint_integer_shorter_interval<T>( exponent ) )
    {
        ++xi;
    }
    // Try bigger divisor
    ret_value.significand = zi / 10;
    // If succeed, remove trailing zeros if necessary and return
    if( ret_value.significand * 10 >= xi )
    {
        ret_value.exponent = minus_k + 1;
        ret_value.exponent += remove_trailing_zeros( ret_value.significand );
        return ret_value;
    }
    // Otherwise, compute the round-up of y
    ret_value.significand =
    cache_accessor<T>::compute_round_up_for_shorter_interval_case(
        cache, beta_minus_1 );
    ret_value.exponent = minus_k;
    // When tie occurs, choose one of them according to the rule
    if( exponent >= float_info<T>::shorter_interval_tie_lower_threshold &&
        exponent <= float_info<T>::shorter_interval_tie_upper_threshold )
    {
        ret_value.significand = ret_value.significand % 2 == 0
        ? ret_value.significand
        : ret_value.significand - 1;
    } else if( ret_value.significand < xi )
    {
        ++ret_value.significand;
    }
    return ret_value;
}
References detail::dragonbox::decimal_fp< T >::exponent, floor_log10_pow2_minus_log10_4_over_3(), floor_log2_pow10(), detail::get_cached_power(), remove_trailing_zeros(), and detail::dragonbox::decimal_fp< T >::significand.
small_division_by_pow10()
template<int N> uint32_t detail::dragonbox::small_division_by_pow10 (uint32_t n)
Definition at line 1961 of file fmtlib_format-inl.h.
{
    static constexpr struct {
        uint32_t magic_number;
        int shift_amount;
        uint32_t divisor_times_10;
    } infos[] = {{0xcccd, 19, 100}, {0xa3d8, 22, 1000}};
    constexpr auto info = infos[N - 1];
    FMT_ASSERT( n <= info.divisor_times_10, "n is too large" );
    return n * info.magic_number >> info.shift_amount;
}
References FMT_ASSERT.
to_decimal() [1/2]
template<typename T > FMT_SAFEBUFFERS decimal_fp< T > detail::dragonbox::to_decimal (T x)
Definition at line 2378 of file fmtlib_format-inl.h.
{
    // Step 1: integer promotion & Schubfach multiplier calculation.
    using carrier_uint = typename float_info<T>::carrier_uint;
    using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
    auto br = bit_cast<carrier_uint>( x );
    // Extract significand bits and exponent bits.
    const carrier_uint significand_mask =
    ( static_cast<carrier_uint>( 1 ) << float_info<T>::significand_bits ) - 1;
    carrier_uint significand = ( br & significand_mask );
    int exponent = static_cast<int>( ( br & exponent_mask<T>() ) >>
                                     float_info<T>::significand_bits );
    if( exponent != 0 )   // Check if normal.
    {
        exponent += float_info<T>::exponent_bias - float_info<T>::significand_bits;
        // Shorter interval case; proceed like Schubfach.
        if( significand == 0 ) {
            return shorter_interval_case<T>( exponent );
        }
        significand |=
            ( static_cast<carrier_uint>( 1 ) << float_info<T>::significand_bits );
    } else
    {
        // Subnormal case; the interval is always regular.
        if( significand == 0 ) return {0, 0};
        exponent = float_info<T>::min_exponent - float_info<T>::significand_bits;
    }
    const bool include_left_endpoint = ( significand % 2 == 0 );
    const bool include_right_endpoint = include_left_endpoint;
    // Compute k and beta.
    const int minus_k = floor_log10_pow2( exponent ) - float_info<T>::kappa;
    const cache_entry_type cache = cache_accessor<T>::get_cached_power( -minus_k );
    const int beta_minus_1 = exponent + floor_log2_pow10( -minus_k );
    // Compute zi and deltai
    // 10^kappa <= deltai < 10^(kappa + 1)
    const uint32_t deltai = cache_accessor<T>::compute_delta( cache, beta_minus_1 );
    const carrier_uint two_fc = significand << 1;
    const carrier_uint two_fr = two_fc | 1;
    const carrier_uint zi =
        cache_accessor<T>::compute_mul( two_fr << beta_minus_1, cache );
    // Step 2: Try larger divisor; remove trailing zeros if necessary
    // Using an upper bound on zi, we might be able to optimize the division
    // better than the compiler; we are computing zi / big_divisor here
    decimal_fp<T> ret_value;
    ret_value.significand = divide_by_10_to_kappa_plus_1( zi );
    uint32_t r = static_cast<uint32_t>( zi - float_info<T>::big_divisor *
                                        ret_value.significand );
    if( r > deltai )
    {
        goto small_divisor_case_label;
    } else if( r < deltai )
    {
        // Exclude the right endpoint if necessary
        if( r == 0 && !include_right_endpoint &&
            is_endpoint_integer<T>( two_fr, exponent, minus_k ) ) {
            --ret_value.significand;
            r = float_info<T>::big_divisor;
            goto small_divisor_case_label;
        }
    } else
    {
        // r == deltai; compare fractional parts
        // Check conditions in the order different from the paper
        // to take advantage of short-circuiting
        const carrier_uint two_fl = two_fc - 1;
        if( ( !include_left_endpoint ||
              !is_endpoint_integer<T>( two_fl, exponent, minus_k ) ) &&
            !cache_accessor<T>::compute_mul_parity( two_fl, cache, beta_minus_1 ) ) {
            goto small_divisor_case_label;
        }
    }
    ret_value.exponent = minus_k + float_info<T>::kappa + 1;
    // We may need to remove trailing zeros
    ret_value.exponent += remove_trailing_zeros( ret_value.significand );
    return ret_value;
    // Step 3: Find the significand with the smaller divisor
small_divisor_case_label:
    ret_value.significand *= 10;
    ret_value.exponent = minus_k + float_info<T>::kappa;
    const uint32_t mask = ( 1u << float_info<T>::kappa ) - 1;
    auto dist = r - ( deltai / 2 ) + ( float_info<T>::small_divisor / 2 );
    // Is dist divisible by 2^kappa?
    if( ( dist & mask ) == 0 )
    {
        const bool approx_y_parity =
            ( ( dist ^ ( float_info<T>::small_divisor / 2 ) ) & 1 ) != 0;
        dist >>= float_info<T>::kappa;
        // Is dist divisible by 5^kappa?
        if( check_divisibility_and_divide_by_pow5<float_info<T>::kappa>( dist ) ) {
            ret_value.significand += dist;
            // Check z^(f) >= epsilon^(f)
            // We have either yi == zi - epsiloni or yi == (zi - epsiloni) - 1,
            // where yi == zi - epsiloni if and only if z^(f) >= epsilon^(f)
            // Since there are only 2 possibilities, we only need to care about the
            // parity. Also, zi and r should have the same parity since the divisor
            // is an even number
            if( cache_accessor<T>::compute_mul_parity( two_fc, cache, beta_minus_1 ) !=
                approx_y_parity ) {
                --ret_value.significand;
            } else {
                // If z^(f) >= epsilon^(f), we might have a tie
                // when z^(f) == epsilon^(f), or equivalently, when y is an integer
                if( is_center_integer<T>( two_fc, exponent, minus_k ) ) {
                    ret_value.significand = ret_value.significand % 2 == 0
                                            ? ret_value.significand
                                            : ret_value.significand - 1;
                }
            }
        }
        // Is dist not divisible by 5^kappa?
        else {
            ret_value.significand += dist;
        }
    }
    // Is dist not divisible by 2^kappa?
    else
    {
        // Since we know dist is small, we might be able to optimize the division
        // better than the compiler; we are computing dist / small_divisor here
        ret_value.significand +=
            small_division_by_pow10<float_info<T>::kappa>( dist );
    }
    return ret_value;
}
References check_divisibility_and_divide_by_pow5(), divide_by_10_to_kappa_plus_1(), detail::dragonbox::decimal_fp< T >::exponent, floor_log10_pow2(), floor_log2_pow10(), detail::get_cached_power(), remove_trailing_zeros(), and detail::dragonbox::decimal_fp< T >::significand.
Referenced by detail::format_float(), and detail::write().
to_decimal() [2/2]
template<typename T > FMT_API decimal_fp< T > detail::dragonbox::to_decimal (T x)
Definition at line 2378 of file fmtlib_format-inl.h.
{
    // Step 1: integer promotion & Schubfach multiplier calculation.
    using carrier_uint = typename float_info<T>::carrier_uint;
    using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
    auto br = bit_cast<carrier_uint>( x );
    // Extract significand bits and exponent bits.
    const carrier_uint significand_mask =
    ( static_cast<carrier_uint>( 1 ) << float_info<T>::significand_bits ) - 1;
    carrier_uint significand = ( br & significand_mask );
    int exponent = static_cast<int>( ( br & exponent_mask<T>() ) >>
                                     float_info<T>::significand_bits );
    if( exponent != 0 )   // Check if normal.
    {
        exponent += float_info<T>::exponent_bias - float_info<T>::significand_bits;
        // Shorter interval case; proceed like Schubfach.
        if( significand == 0 ) {
            return shorter_interval_case<T>( exponent );
        }
        significand |=
            ( static_cast<carrier_uint>( 1 ) << float_info<T>::significand_bits );
    } else
    {
        // Subnormal case; the interval is always regular.
        if( significand == 0 ) return {0, 0};
        exponent = float_info<T>::min_exponent - float_info<T>::significand_bits;
    }
    const bool include_left_endpoint = ( significand % 2 == 0 );
    const bool include_right_endpoint = include_left_endpoint;
    // Compute k and beta.
    const int minus_k = floor_log10_pow2( exponent ) - float_info<T>::kappa;
    const cache_entry_type cache = cache_accessor<T>::get_cached_power( -minus_k );
    const int beta_minus_1 = exponent + floor_log2_pow10( -minus_k );
    // Compute zi and deltai
    // 10^kappa <= deltai < 10^(kappa + 1)
    const uint32_t deltai = cache_accessor<T>::compute_delta( cache, beta_minus_1 );
    const carrier_uint two_fc = significand << 1;
    const carrier_uint two_fr = two_fc | 1;
    const carrier_uint zi =
        cache_accessor<T>::compute_mul( two_fr << beta_minus_1, cache );
    // Step 2: Try larger divisor; remove trailing zeros if necessary
    // Using an upper bound on zi, we might be able to optimize the division
    // better than the compiler; we are computing zi / big_divisor here
    decimal_fp<T> ret_value;
    ret_value.significand = divide_by_10_to_kappa_plus_1( zi );
    uint32_t r = static_cast<uint32_t>( zi - float_info<T>::big_divisor *
                                        ret_value.significand );
    if( r > deltai )
    {
        goto small_divisor_case_label;
    } else if( r < deltai )
    {
        // Exclude the right endpoint if necessary
        if( r == 0 && !include_right_endpoint &&
            is_endpoint_integer<T>( two_fr, exponent, minus_k ) ) {
            --ret_value.significand;
            r = float_info<T>::big_divisor;
            goto small_divisor_case_label;
        }
    } else
    {
        // r == deltai; compare fractional parts
        // Check conditions in the order different from the paper
        // to take advantage of short-circuiting
        const carrier_uint two_fl = two_fc - 1;
        if( ( !include_left_endpoint ||
              !is_endpoint_integer<T>( two_fl, exponent, minus_k ) ) &&
            !cache_accessor<T>::compute_mul_parity( two_fl, cache, beta_minus_1 ) ) {
            goto small_divisor_case_label;
        }
    }
    ret_value.exponent = minus_k + float_info<T>::kappa + 1;
    // We may need to remove trailing zeros
    ret_value.exponent += remove_trailing_zeros( ret_value.significand );
    return ret_value;
    // Step 3: Find the significand with the smaller divisor
small_divisor_case_label:
    ret_value.significand *= 10;
    ret_value.exponent = minus_k + float_info<T>::kappa;
    const uint32_t mask = ( 1u << float_info<T>::kappa ) - 1;
    auto dist = r - ( deltai / 2 ) + ( float_info<T>::small_divisor / 2 );
    // Is dist divisible by 2^kappa?
    if( ( dist & mask ) == 0 )
    {
        const bool approx_y_parity =
            ( ( dist ^ ( float_info<T>::small_divisor / 2 ) ) & 1 ) != 0;
        dist >>= float_info<T>::kappa;
        // Is dist divisible by 5^kappa?
        if( check_divisibility_and_divide_by_pow5<float_info<T>::kappa>( dist ) ) {
            ret_value.significand += dist;
            // Check z^(f) >= epsilon^(f)
            // We have either yi == zi - epsiloni or yi == (zi - epsiloni) - 1,
            // where yi == zi - epsiloni if and only if z^(f) >= epsilon^(f)
            // Since there are only 2 possibilities, we only need to care about the
            // parity. Also, zi and r should have the same parity since the divisor
            // is an even number
            if( cache_accessor<T>::compute_mul_parity( two_fc, cache, beta_minus_1 ) !=
                approx_y_parity ) {
                --ret_value.significand;
            } else {
                // If z^(f) >= epsilon^(f), we might have a tie
                // when z^(f) == epsilon^(f), or equivalently, when y is an integer
                if( is_center_integer<T>( two_fc, exponent, minus_k ) ) {
                    ret_value.significand = ret_value.significand % 2 == 0
                                            ? ret_value.significand
                                            : ret_value.significand - 1;
                }
            }
        }
        // Is dist not divisible by 5^kappa?
        else {
            ret_value.significand += dist;
        }
    }
    // Is dist not divisible by 2^kappa?
    else
    {
        // Since we know dist is small, we might be able to optimize the division
        // better than the compiler; we are computing dist / small_divisor here
        ret_value.significand +=
            small_division_by_pow10<float_info<T>::kappa>( dist );
    }
    return ret_value;
}
References check_divisibility_and_divide_by_pow5(), divide_by_10_to_kappa_plus_1(), detail::dragonbox::decimal_fp< T >::exponent, floor_log10_pow2(), floor_log2_pow10(), detail::get_cached_power(), remove_trailing_zeros(), and detail::dragonbox::decimal_fp< T >::significand.
Referenced by detail::format_float(), and detail::write().
umul128()
FMT_SAFEBUFFERS uint128_wrapper detail::dragonbox::umul128 (uint64_t x, uint64_t y) inline
Definition at line 1802 of file fmtlib_format-inl.h.
{
#if FMT_USE_INT128
    return static_cast<uint128_t>( x ) * static_cast<uint128_t>( y );
#elif defined(_MSC_VER) && defined(_M_X64)
    uint128_wrapper result;
    result.low_ = _umul128( x, y, &result.high_ );
    return result;
#else
    const uint64_t mask = ( uint64_t( 1 ) << 32 ) - uint64_t( 1 );
    uint64_t a = x >> 32;
    uint64_t b = x & mask;
    uint64_t c = y >> 32;
    uint64_t d = y & mask;
    uint64_t ac = a * c;
    uint64_t bc = b * c;
    uint64_t ad = a * d;
    uint64_t bd = b * d;
    uint64_t intermediate = ( bd >> 32 ) + ( ad & mask ) + ( bc & mask );
    return {
        ac + ( intermediate >> 32 ) + ( ad >> 32 ) + ( bc >> 32 ),
        ( intermediate << 32 ) + ( bd & mask )};
#endif
}
References a, b, and c.
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), umul128_upper64(), and umul192_upper64().
umul128_upper64()
FMT_SAFEBUFFERS uint64_t detail::dragonbox::umul128_upper64 (uint64_t x, uint64_t y) inline
Definition at line 1832 of file fmtlib_format-inl.h.
{
#if FMT_USE_INT128
    auto p = static_cast<uint128_t>( x ) * static_cast<uint128_t>( y );
    return static_cast<uint64_t>( p >> 64 );
#elif defined(_MSC_VER) && defined(_M_X64)
    return __umulh( x, y );
#else
    return umul128( x, y ).high();
#endif
}
References detail::uint128_wrapper::high(), and umul128().
Referenced by divide_by_10_to_kappa_plus_1(), umul192_middle64(), umul192_upper64(), and umul96_upper32().
umul192_middle64()
FMT_SAFEBUFFERS uint64_t detail::dragonbox::umul192_middle64 (uint64_t x, uint128_wrapper y) inline
Definition at line 1863 of file fmtlib_format-inl.h.
             {
    uint64_t g01 = x * y.high();
    uint64_t g10 = umul128_upper64( x, y.low() );
    return g01 + g10;
}
References umul128_upper64().
Referenced by detail::dragonbox::cache_accessor< double >::compute_mul_parity().
umul192_upper64()
FMT_SAFEBUFFERS uint64_t detail::dragonbox::umul192_upper64 (uint64_t x, uint128_wrapper y) inline
Definition at line 1846 of file fmtlib_format-inl.h.
             {
    uint128_wrapper g0 = umul128( x, y.high() );
    g0 += umul128_upper64( x, y.low() );
    return g0.high();
}
References detail::uint128_wrapper::high(), umul128(), and umul128_upper64().
Referenced by detail::dragonbox::cache_accessor< double >::compute_mul().
umul96_lower64()
uint64_t detail::dragonbox::umul96_lower64 (uint32_t x, uint64_t y) inline
Definition at line 1873 of file fmtlib_format-inl.h.
{
    return x * y;
}
Referenced by detail::dragonbox::cache_accessor< float >::compute_mul_parity().
umul96_upper32()
uint32_t detail::dragonbox::umul96_upper32 (uint32_t x, uint64_t y) inline
Definition at line 1856 of file fmtlib_format-inl.h.
{
    return static_cast<uint32_t>( umul128_upper64( x, y ) );
}
References umul128_upper64().
Referenced by detail::dragonbox::cache_accessor< float >::compute_mul().