Cataclysm BN: activity_handlers::repair_activity_hack Namespace Reference
activity_handlers::repair_activity_hack Namespace Reference
Namespaces
namespace anonymous_namespace{activity_handlers.cpp}
Functions
void patch_activity_for_vehicle_welder (player_activity &activity, const tripoint &veh_part_position, const vehicle &veh, int interact_part_idx)
void patch_activity_for_furniture (player_activity &activity, const tripoint &furniture_position)
Function Documentation
patch_activity_for_furniture()
void activity_handlers::repair_activity_hack::patch_activity_for_furniture (player_activity & activity, const tripoint & furniture_position)
Definition at line 2779 of file activity_handlers.cpp.
{
    // Player may start another activity on welder/soldering iron
    // Check it here instead of furniture interaction code
    // because we want to encapsulate hack here.
    if( activity.id() != ACT_REPAIR_ITEM ) {
        return;
    }
    // This tells activity, that real item doesn't exists in inventory.
    activity.index = INT_MIN;
    // Data for lookup furniture
    activity.coords = { furniture_position };
    activity.values = {
        // Because we called only on start of repair
        static_cast<int>( repeat_type::REPEAT_INIT ),
        0, // Useless for us, set only to be compatible with vehicle
        static_cast<int>( hack_type_t::furniture )
    };
}
References ACT_REPAIR_ITEM, and REPEAT_INIT.
Referenced by iexamine::use_furn_fake_item().
patch_activity_for_vehicle_welder()
void activity_handlers::repair_activity_hack::patch_activity_for_vehicle_welder (player_activity & activity, const tripoint & veh_part_position, const vehicle & veh, int interact_part_idx)
Definition at line 2752 of file activity_handlers.cpp.
{
    // Player may start another activity on welder/soldering iron
    // Check it here instead of vehicle interaction code
    // because we want to encapsulate hack here.
    if( activity.id() != ACT_REPAIR_ITEM ) {
        return;
    }
    const int welding_rig_index = veh.part_with_feature( interact_part_idx, "WELDRIG", true );
    // This tells activity, that real item doesn't exists in inventory.
    activity.index = INT_MIN;
    // Data for lookup vehicle part
    activity.coords = { veh_part_position };
    activity.values = {
        // Because we called only on start of repair
        static_cast<int>( repeat_type::REPEAT_INIT ),
        welding_rig_index,
        static_cast<int>( hack_type_t::vehicle_weldrig )
    };
}
References ACT_REPAIR_ITEM, vehicle::part_with_feature(), and REPEAT_INIT.
Referenced by vehicle::interact_with().