Cataclysm BN: materials Namespace Reference
materials Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check ()
void reset ()
material_list get_all ()
material_list get_compactable ()
std::set< material_id > get_rotting ()
Function Documentation
check()
void materials::check ()
Definition at line 301 of file material.cpp.
{
    material_data.check();
}
References anonymous_namespace{material.cpp}::material_data.
Referenced by DynamicDataLoader::check_consistency().
get_all()
material_list materials::get_all ()
Definition at line 311 of file material.cpp.
{
    return material_data.get_all();
}
References anonymous_namespace{material.cpp}::material_data.
get_compactable()
material_list materials::get_compactable ()
Definition at line 316 of file material.cpp.
{
    material_list all = get_all();
    material_list compactable;
    std::copy_if( all.begin(), all.end(),
    std::back_inserter( compactable ), []( const material_type & mt ) {
        return !mt.compacts_into().empty();
    } );
    return compactable;
}
References om_direction::all, and ammo_effects::get_all().
Referenced by iexamine::recycle_compactor().
get_rotting()
std::set< material_id > materials::get_rotting ()
Definition at line 327 of file material.cpp.
{
    static generic_factory<material_type>::Version version;
    static std::set<material_id> rotting;
    // freshly created version is guaranteed to be invalid
    if( !material_data.is_valid( version ) ) {
        material_list all = get_all();
        rotting.clear();
        for( const material_type &m : all ) {
            if( m.rotting() ) {
                rotting.emplace( m.ident() );
            }
        }
        version = material_data.get_version();
    }
    return rotting;
}
References om_direction::all, ammo_effects::get_all(), and anonymous_namespace{material.cpp}::material_data.
Referenced by item::goes_bad().
load()
void materials::load (const JsonObject & jo, const std::string & src)
Definition at line 296 of file material.cpp.
{
    material_data.load( jo, src );
}
References anonymous_namespace{material.cpp}::material_data.
Referenced by DynamicDataLoader::initialize().
reset()
void materials::reset ()
Definition at line 306 of file material.cpp.
{
    material_data.reset();
}
References anonymous_namespace{material.cpp}::material_data.
Referenced by DynamicDataLoader::unload_data().