Cataclysm BN: activity_handlers Namespace Reference
activity_handlers Namespace Reference
Namespaces
namespace repair_activity_hack
Functions
bool resume_for_multi_activities (player &p)
void burrow_do_turn (player_activity *act, player *p)
activity_do_turn functions:
void craft_do_turn (player_activity *act, player *p)
void fill_liquid_do_turn (player_activity *act, player *p)
void pickaxe_do_turn (player_activity *act, player *p)
void drop_do_turn (player_activity *act, player *p)
void stash_do_turn (player_activity *act, player *p)
void pulp_do_turn (player_activity *act, player *p)
void game_do_turn (player_activity *act, player *p)
void generic_game_do_turn (player_activity *act, player *p)
void churn_do_turn (player_activity *act, player *p)
void start_fire_do_turn (player_activity *act, player *p)
void vibe_do_turn (player_activity *act, player *p)
void hand_crank_do_turn (player_activity *act, player *p)
void multiple_chop_planks_do_turn (player_activity *act, player *p)
void oxytorch_do_turn (player_activity *act, player *p)
void wear_do_turn (player_activity *act, player *p)
void eat_menu_do_turn (player_activity *act, player *p)
void consume_food_menu_do_turn (player_activity *act, player *p)
void consume_drink_menu_do_turn (player_activity *act, player *p)
void consume_meds_menu_do_turn (player_activity *act, player *p)
void move_items_do_turn (player_activity *act, player *p)
void multiple_farm_do_turn (player_activity *act, player *p)
void multiple_fish_do_turn (player_activity *act, player *p)
void multiple_construction_do_turn (player_activity *act, player *p)
void multiple_mine_do_turn (player_activity *act, player *p)
void multiple_butcher_do_turn (player_activity *act, player *p)
void vehicle_deconstruction_do_turn (player_activity *act, player *p)
void vehicle_repair_do_turn (player_activity *act, player *p)
void chop_trees_do_turn (player_activity *act, player *p)
void fetch_do_turn (player_activity *act, player *p)
void move_loot_do_turn (player_activity *act, player *p)
void travel_do_turn (player_activity *act, player *p)
void adv_inventory_do_turn (player_activity *act, player *p)
void armor_layers_do_turn (player_activity *act, player *p)
void atm_do_turn (player_activity *act, player *p)
void fish_do_turn (player_activity *act, player *p)
void cracking_do_turn (player_activity *act, player *p)
void repair_item_do_turn (player_activity *act, player *p)
void butcher_do_turn (player_activity *act, player *p)
void pry_nails_do_turn (player_activity *act, player *p)
void hacksaw_do_turn (player_activity *act, player *p)
void chop_tree_do_turn (player_activity *act, player *p)
void jackhammer_do_turn (player_activity *act, player *p)
void find_mount_do_turn (player_activity *act, player *p)
void tidy_up_do_turn (player_activity *act, player *p)
void build_do_turn (player_activity *act, player *p)
void fill_pit_do_turn (player_activity *act, player *p)
void fertilize_plot_do_turn (player_activity *act, player *p)
void try_sleep_do_turn (player_activity *act, player *p)
void operation_do_turn (player_activity *act, player *p)
void robot_control_do_turn (player_activity *act, player *p)
void tree_communion_do_turn (player_activity *act, player *p)
void spellcasting_do_turn (player_activity *act, player *p)
void study_spell_do_turn (player_activity *act, player *p)
void read_do_turn (player_activity *act, player *p)
void wait_stamina_do_turn (player_activity *act, player *p)
void burrow_finish (player_activity *act, player *p)
activity_finish functions:
void butcher_finish (player_activity *act, player *p)
void firstaid_finish (player_activity *act, player *p)
void fish_finish (player_activity *act, player *p)
void forage_finish (player_activity *act, player *p)
void hotwire_finish (player_activity *act, player *p)
void longsalvage_finish (player_activity *act, player *p)
void pulp_finish (player_activity *act, player *p)
void make_zlave_finish (player_activity *act, player *p)
void pickaxe_finish (player_activity *act, player *p)
void reload_finish (player_activity *act, player *p)
void start_fire_finish (player_activity *act, player *p)
void train_finish (player_activity *act, player *p)
void milk_finish (player_activity *act, player *p)
void shear_finish (player_activity *act, player *p)
void vehicle_finish (player_activity *act, player *p)
void start_engines_finish (player_activity *act, player *p)
void churn_finish (player_activity *act, player *p)
void plant_seed_finish (player_activity *act, player *p)
void oxytorch_finish (player_activity *act, player *p)
void cracking_finish (player_activity *act, player *p)
void lockpicking_finish (player_activity *act, player *p)
void repair_item_finish (player_activity *act, player *p)
void mend_item_finish (player_activity *act, player *p)
void gunmod_add_finish (player_activity *act, player *p)
void toolmod_add_finish (player_activity *act, player *p)
void clear_rubble_finish (player_activity *act, player *p)
void meditate_finish (player_activity *act, player *p)
void read_finish (player_activity *act, player *p)
void wait_finish (player_activity *act, player *p)
void wait_weather_finish (player_activity *act, player *p)
void wait_npc_finish (player_activity *act, player *p)
void wait_stamina_finish (player_activity *act, player *p)
void socialize_finish (player_activity *act, player *p)
void try_sleep_finish (player_activity *act, player *p)
void operation_finish (player_activity *act, player *p)
void vibe_finish (player_activity *act, player *p)
void hand_crank_finish (player_activity *act, player *p)
void atm_finish (player_activity *act, player *p)
void eat_menu_finish (player_activity *act, player *p)
void washing_finish (player_activity *act, player *p)
void hacksaw_finish (player_activity *act, player *p)
void pry_nails_finish (player_activity *act, player *p)
void chop_tree_finish (player_activity *act, player *p)
void chop_logs_finish (player_activity *act, player *p)
void chop_planks_finish (player_activity *act, player *p)
void jackhammer_finish (player_activity *act, player *p)
void fill_pit_finish (player_activity *act, player *p)
void play_with_pet_finish (player_activity *act, player *p)
void shaving_finish (player_activity *act, player *p)
void haircut_finish (player_activity *act, player *p)
void unload_mag_finish (player_activity *act, player *p)
void robot_control_finish (player_activity *act, player *p)
void mind_splicer_finish (player_activity *act, player *p)
void spellcasting_finish (player_activity *act, player *p)
void study_spell_finish (player_activity *act, player *p)
void try_sleep_query (player_activity *act, player *p)
Variables
const std::map< activity_id, std::function< void(player_activity *, player *)> > do_turn_functions
const std::map< activity_id, std::function< void(player_activity *, player *)> > finish_functions
Function Documentation
adv_inventory_do_turn()
void activity_handlers::adv_inventory_do_turn (player_activity * act, player * p)
Definition at line 3163 of file activity_handlers.cpp.
{
    p->cancel_activity();
    create_advanced_inv();
}
References Character::cancel_activity(), and create_advanced_inv().
armor_layers_do_turn()
void activity_handlers::armor_layers_do_turn (player_activity * act, player * p)
Definition at line 3216 of file activity_handlers.cpp.
{
    p->cancel_activity();
    p->sort_armor();
}
References Character::cancel_activity(), and player::sort_armor().
atm_do_turn()
void activity_handlers::atm_do_turn (player_activity * act, player * p)
Definition at line 3222 of file activity_handlers.cpp.
{
    iexamine::atm( *p, p->pos() );
}
References iexamine::atm(), and Character::pos().
atm_finish()
void activity_handlers::atm_finish (player_activity * act, player * p)
Definition at line 4001 of file activity_handlers.cpp.
{
    // ATM sets index to 0 to indicate it's finished.
    if( !act->index ) {
        act->set_to_null();
    }
}
References act.
build_do_turn()
void activity_handlers::build_do_turn (player_activity * act, player * p)
Definition at line 3779 of file activity_handlers.cpp.
{
    map &here = get_map();
    partial_con *pc = here.partial_con_at( here.getlocal( act->placement ) );
    // Maybe the player and the NPC are working on the same construction at the same time
    if( !pc ) {
        if( p->is_npc() ) {
            // if player completes the work while NPC still in activity loop
            p->activity = player_activity();
            p->set_moves( 0 );
        } else {
            p->cancel_activity();
        }
        add_msg( m_info, _( "%s did not find an unfinished construction at the activity spot." ),
                 p->disp_name() );
        return;
    }
    // if you ( or NPC ) are finishing someone else's started construction...
    const construction &built = pc->id.obj();
    if( !p->has_trait( trait_DEBUG_HS ) && !p->meets_skill_requirements( built ) ) {
        add_msg( m_info, _( "%s can't work on this construction anymore." ), p->disp_name() );
        p->cancel_activity();
        if( p->is_npc() ) {
            p->activity = player_activity();
            p->set_moves( 0 );
        }
        return;
    }
    // item_counter represents the percent progress relative to the base batch time
    // stored precise to 5 decimal places ( e.g. 67.32 percent would be stored as 6732000 )
    const int old_counter = pc->counter;
    // Base moves for construction with no speed modifier or assistants
    // Must ensure >= 1 so we don't divide by 0;
    const double base_total_moves = std::max( 1, to_moves<int>( built.time ) );
    // Current expected total moves, includes construction speed modifiers and assistants
    const double cur_total_moves = std::max( 1, built.adjusted_time() );
    // Delta progress in moves adjusted for current crafting speed
    const double delta_progress = p->get_moves() * base_total_moves / cur_total_moves;
    // Current progress in moves
    const double current_progress = old_counter * base_total_moves / 10000000.0 +
                                    delta_progress;
    // Current progress as a percent of base_total_moves to 2 decimal places
    pc->counter = std::round( current_progress / base_total_moves * 10000000.0 );
    p->set_moves( 0 );
    pc->counter = std::min( pc->counter, 10000000 );
    // If construction_progress has reached 100% or more
    if( pc->counter >= 10000000 ) {
        // Activity is canceled in complete_construction()
        complete_construction( *p );
    }
}
References _, act, Character::activity, add_msg(), construction::adjusted_time(), Character::cancel_activity(), complete_construction(), partial_con::counter, Character::disp_name(), get_map(), Creature::get_moves(), map::getlocal(), Character::has_trait(), partial_con::id, player::is_npc(), m_info, Character::meets_skill_requirements(), int_id< T >::obj(), map::partial_con_at(), Creature::set_moves(), construction::time, and trait_DEBUG_HS.
burrow_do_turn()
void activity_handlers::burrow_do_turn (player_activity * act, player * p)
activity_do_turn functions:
Definition at line 430 of file activity_handlers.cpp.
{
    sfx::play_activity_sound( "activity", "burrow", sfx::get_heard_volume( act->placement ) );
    if( calendar::once_every( 1_minutes ) ) {
        sounds::sound( act->placement, 10, sounds::sound_t::movement,
                       //~ Sound of a Rat mutant burrowing!
                       _( "ScratchCrunchScrabbleScurry." ) );
    }
}
References _, act, sfx::get_heard_volume(), sounds::movement, calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
burrow_finish()
void activity_handlers::burrow_finish (player_activity * act, player * p)
activity_finish functions:
Definition at line 440 of file activity_handlers.cpp.
{
    tripoint pos = act->placement; // make a copy to avoid use-after-free
    map &here = get_map();
    act->set_to_null(); // kill activity before inflicting pain
    if( here.is_bashable( pos ) && here.has_flag( flag_SUPPORTS_ROOF, pos ) &&
        here.ter( pos ) != t_tree ) {
        // Tunneling through solid rock is hungry, sweaty, tiring, backbreaking work
        // Not quite as bad as the pickaxe, though
        p->mod_stored_nutr( 10 );
        p->mod_thirst( 10 );
        p->mod_fatigue( 15 );
        p->mod_pain( 3 * rng( 1, 3 ) );
    } else if( here.move_cost( pos ) == 2 && g->get_levz() == 0 &&
               here.ter( pos ) != t_dirt && here.ter( pos ) != t_grass ) {
        //Breaking up concrete on the surface? not nearly as bad
        p->mod_stored_nutr( 5 );
        p->mod_thirst( 5 );
        p->mod_fatigue( 10 );
    }
    p->add_msg_if_player( m_good, _( "You finish burrowing." ) );
    here.destroy( pos, true );
}
References _, act, player::add_msg_if_player(), map::destroy(), flag_SUPPORTS_ROOF(), g, get_map(), map::has_flag(), map::is_bashable(), m_good, Character::mod_fatigue(), player::mod_pain(), Character::mod_stored_nutr(), Character::mod_thirst(), map::move_cost(), rng(), t_dirt, t_grass, t_tree, and map::ter().
butcher_do_turn()
void activity_handlers::butcher_do_turn (player_activity * act, player * p)
Definition at line 3330 of file activity_handlers.cpp.
{
    p->mod_stamina( -20 );
}
References Character::mod_stamina().
butcher_finish()
void activity_handlers::butcher_finish (player_activity * act, player * p)
Survival randomly increases butcher rolls Dexterity >8 randomly increases butcher rolls, slightly, <8 decreases
Definition at line 1130 of file activity_handlers.cpp.
{
    // No targets means we are done
    if( act->targets.empty() ) {
        act->set_to_null();
        resume_for_multi_activities( *p );
        return;
    }
    map &here = get_map();
    item_location target = act->targets.back();
    const inventory &inv = p->crafting_inventory();
    // Corpses can disappear (rezzing!), so check for that
    if( !target || !target->is_corpse() ) {
        p->add_msg_if_player( m_info, _( "There's no corpse to butcher!" ) );
        act->set_to_null();
        return;
    }
    butcher_type action = BUTCHER;
    if( act->id() == ACT_BUTCHER ) {
        action = BUTCHER;
    } else if( act->id() == ACT_BUTCHER_FULL ) {
        action = BUTCHER_FULL;
    } else if( act->id() == ACT_FIELD_DRESS ) {
        action = F_DRESS;
    } else if( act->id() == ACT_QUARTER ) {
        action = QUARTER;
    } else if( act->id() == ACT_DISSECT ) {
        action = DISSECT;
    } else if( act->id() == ACT_SKIN ) {
        action = SKIN;
    } else if( act->id() == ACT_DISMEMBER ) {
        action = DISMEMBER;
    }
    // index is a bool that determines if we are ready to start the next target
    if( act->index ) {
        const butchery_setup setup = consider_butchery( *target, *p, action );
        set_up_butchery_activity( *act, *p, setup );
        return;
    }
    item &corpse_item = *target;
    const mtype *corpse = corpse_item.get_mtype();
    const field_type_id type_blood = corpse->bloodType();
    const field_type_id type_gib = corpse->gibType();
    if( action == QUARTER ) {
        butchery_quarter( &corpse_item, *p );
        act->index = true;
        return;
    }
    int skill_level = p->get_skill_level( skill_survival );
    int factor = inv.max_quality( action == DISSECT ? qual_CUT_FINE :
                                  qual_BUTCHER );
    // DISSECT has special case factor calculation and results.
    if( action == DISSECT ) {
        skill_level = p->get_skill_level( skill_firstaid );
        skill_level += inv.max_quality( qual_CUT_FINE );
        skill_level += p->get_skill_level( skill_electronics ) / 2;
        add_msg( m_debug, _( "Skill: %s" ), skill_level );
    }
    const auto roll_butchery = [&]() {
        double skill_shift = 0.0;
        ///\EFFECT_SURVIVAL randomly increases butcher rolls
        skill_shift += rng_float( 0, skill_level - 3 );
        ///\EFFECT_DEX >8 randomly increases butcher rolls, slightly, <8 decreases
        skill_shift += rng_float( 0, p->get_dex() - 8 ) / 4.0;
        if( factor < 0 ) {
            skill_shift -= rng_float( 0, -factor / 5.0 );
        }
        return static_cast<int>( std::round( skill_shift ) );
    };
    if( action == DISMEMBER ) {
        here.add_splatter( type_gib, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
    }
    //all BUTCHERY types - FATAL FAILURE
    if( action != DISSECT && roll_butchery() <= ( -15 ) && one_in( 2 ) ) {
        switch( rng( 1, 3 ) ) {
            case 1:
                p->add_msg_if_player( m_warning,
                                      _( "You hack up the corpse so unskillfully, that there is nothing left to salvage from this bloody mess." ) );
                break;
            case 2:
                p->add_msg_if_player( m_warning,
                                      _( "You wanted to cut the corpse, but instead you hacked the meat, spilled the guts all over it, and made a bloody mess." ) );
                break;
            case 3:
                p->add_msg_if_player( m_warning,
                                      _( "You made so many mistakes during the process that you doubt even vultures will be interested in what's left of it." ) );
                break;
        }
        // Remove the target from the map
        target.remove_item();
        act->targets.pop_back();
        here.add_splatter( type_gib, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
        here.add_splatter( type_blood, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
        for( int i = 1; i <= corpse->size; i++ ) {
            here.add_splatter_trail( type_gib, p->pos(), random_entry( here.points_in_radius( p->pos(),
                                     corpse->size + 1 ) ) );
            here.add_splatter_trail( type_blood, p->pos(), random_entry( here.points_in_radius( p->pos(),
                                     corpse->size + 1 ) ) );
        }
        // Ready to move on to the next item, if there is one
        act->index = true;
        return;
    }
    // function just for drop yields
    const auto roll_drops = [&]() {
        factor = std::max( factor, -50 );
        return 0.5 * skill_level / 10 + 0.3 * ( factor + 50 ) / 100 + 0.2 * p->dex_cur / 20;
    };
    // all action types - yields
    butchery_drops_harvest( &corpse_item, *corpse, *p, roll_butchery, action, roll_drops );
    // after this point, if there was a liquid handling from the harvest,
    // and the liquid handling was interrupted, then the activity was canceled,
    // therefore operations on this activities targets and values may be invalidated.
    // reveal hidden items / hidden content
    if( action == DISSECT ) {
        int roll = roll_butchery() - corpse_item.damage_level( 4 );
        roll = roll < 0 ? 0 : roll;
        add_msg( m_debug, _( "Roll penalty for corpse damage = %s" ), 0 - corpse_item.damage_level( 4 ) );
        std::list<item> cbms = corpse_item.components;
        for( const item *it : corpse_item.contents.all_items_top() ) {
            cbms.push_back( *it );
        }
        extract_or_wreck_cbms( cbms, roll, *p );
        // those lines are for XP gain with dissecting. It depends on the size of the corpse, time to dissect the corpse and the amount of bionics you would gather.
        int time_to_cut = size_factor_in_time_to_cut( corpse->size );
        int level_cap = std::min<int>( MAX_SKILL, ( corpse->size + ( cbms.size() * 2 + 1 ) ) );
        int size_mult = corpse->size > MS_MEDIUM ? ( corpse->size * corpse->size ) : 8;
        int practice_amt = ( size_mult + 1 ) * ( ( time_to_cut / 150 ) + 1 ) *
                           ( cbms.size() * cbms.size() / 2 + 1 );
        p->practice( skill_firstaid, practice_amt, level_cap );
        add_msg( m_debug, "Experience: %d, Level cap: %d, Time to cut: %d", practice_amt, level_cap,
                 time_to_cut );
    }
    //end messages and effects
    switch( action ) {
        case QUARTER:
            break;
        case BUTCHER:
            p->add_msg_if_player( m_good,
                                  _( "You apply few quick cuts to the %s and leave what's left of it for scavengers." ),
                                  corpse_item.tname() );
            // Remove the target from the map
            target.remove_item();
            if( !act->targets.empty() ) {
                act->targets.pop_back();
            }
            break;
        case BUTCHER_FULL:
            p->add_msg_if_player( m_good, _( "You finish butchering the %s." ), corpse_item.tname() );
            // Remove the target from the map
            target.remove_item();
            if( !act->targets.empty() ) {
                act->targets.pop_back();
            }
            break;
        case F_DRESS:
            // partial failure
            if( roll_butchery() < 0 ) {
                switch( rng( 1, 3 ) ) {
                    case 1:
                        p->add_msg_if_player( m_warning,
                                              _( "You unskillfully hack up the corpse and chop off some excess body parts.  You're left wondering how you did so poorly." ) );
                        break;
                    case 2:
                        p->add_msg_if_player( m_warning,
                                              _( "Your unskilled hands slip and damage the corpse.  You still hope it's not a total waste though." ) );
                        break;
                    case 3:
                        p->add_msg_if_player( m_warning,
                                              _( "You did something wrong and hacked the corpse badly.  Maybe it's still recoverable." ) );
                        break;
                }
                corpse_item.set_flag( "FIELD_DRESS_FAILED" );
                here.add_splatter( type_gib, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
                here.add_splatter( type_blood, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
                for( int i = 1; i <= corpse->size; i++ ) {
                    here.add_splatter_trail( type_gib, p->pos(), random_entry( here.points_in_radius( p->pos(),
                                             corpse->size + 1 ) ) );
                    here.add_splatter_trail( type_blood, p->pos(), random_entry( here.points_in_radius( p->pos(),
                                             corpse->size + 1 ) ) );
                }
            } else {
                // success
                switch( rng( 1, 3 ) ) {
                    case 1:
                        p->add_msg_if_player( m_good, _( "You field dress the %s." ), corpse->nname() );
                        break;
                    case 2:
                        p->add_msg_if_player( m_good,
                                              _( "You slice the corpse's belly and remove intestines and organs, until you're confident that it will not rot from inside." ) );
                        break;
                    case 3:
                        p->add_msg_if_player( m_good,
                                              _( "You remove guts and excess parts, preparing the corpse for later use." ) );
                        break;
                }
                corpse_item.set_flag( flag_FIELD_DRESS );
                here.add_splatter( type_gib, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
                here.add_splatter( type_blood, p->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
                for( int i = 1; i <= corpse->size; i++ ) {
                    here.add_splatter_trail( type_gib, p->pos(), random_entry( here.points_in_radius( p->pos(),
                                             corpse->size + 1 ) ) );
                    here.add_splatter_trail( type_blood, p->pos(), random_entry( here.points_in_radius( p->pos(),
                                             corpse->size + 1 ) ) );
                }
            }
            if( !act->targets.empty() ) {
                act->targets.pop_back();
            }
            break;
        case SKIN:
            switch( rng( 1, 4 ) ) {
                case 1:
                    p->add_msg_if_player( m_good, _( "You skin the %s." ), corpse->nname() );
                    break;
                case 2:
                    p->add_msg_if_player( m_good, _( "You carefully remove the hide from the %s" ),
                                          corpse->nname() );
                    break;
                case 3:
                    p->add_msg_if_player( m_good,
                                          _( "The %s is challenging to skin, but you get a good hide from it." ),
                                          corpse->nname() );
                    break;
                case 4:
                    p->add_msg_if_player( m_good, _( "With a few deft slices you take the skin from the %s" ),
                                          corpse->nname() );
                    break;
            }
            corpse_item.set_flag( flag_SKINNED );
            if( !act->targets.empty() ) {
                act->targets.pop_back();
            }
            break;
        case DISMEMBER:
            switch( rng( 1, 3 ) ) {
                case 1:
                    p->add_msg_if_player( m_good, _( "You hack the %s apart." ), corpse_item.tname() );
                    break;
                case 2:
                    p->add_msg_if_player( m_good, _( "You lop the limbs off the %s." ), corpse_item.tname() );
                    break;
                case 3:
                    p->add_msg_if_player( m_good, _( "You cleave the %s into pieces." ), corpse_item.tname() );
            }
            // Remove the target from the map
            target.remove_item();
            if( !act->targets.empty() ) {
                act->targets.pop_back();
            }
            break;
        case DISSECT:
            p->add_msg_if_player( m_good, _( "You finish dissecting the %s." ), corpse_item.tname() );
            // Remove the target from the map
            target.remove_item();
            if( !act->targets.empty() ) {
                act->targets.pop_back();
            }
            break;
    }
    // Ready to move on to the next item, if there is one (for example if multibutchering)
    act->index = true;
    // if its mutli-tile butchering,then restart the backlog.
    resume_for_multi_activities( *p );
}
References _, act, ACT_BUTCHER, ACT_BUTCHER_FULL, ACT_DISMEMBER, ACT_DISSECT, ACT_FIELD_DRESS, ACT_QUARTER, ACT_SKIN, action, add_msg(), player::add_msg_if_player(), map::add_splatter(), map::add_splatter_trail(), item_contents::all_items_top(), BUTCHER, BUTCHER_FULL, butchery_drops_harvest(), butchery_quarter(), item::components, consider_butchery(), item::contents, corpse, Character::crafting_inventory(), item::damage_level(), Character::dex_cur, DISMEMBER, DISSECT, extract_or_wreck_cbms(), F_DRESS, flag_FIELD_DRESS(), flag_SKINNED(), Character::get_dex(), get_map(), item::get_mtype(), Character::get_skill_level(), activity_type::id(), item::is_corpse(), m_debug, m_good, m_info, m_warning, visitable< T >::max_quality(), MAX_SKILL, MS_MEDIUM, one_in(), map::points_in_radius(), Character::pos(), player::practice(), qual_BUTCHER, qual_CUT_FINE, QUARTER, random_entry(), item_location::remove_item(), resume_for_multi_activities(), rng(), rng_float(), item::set_flag(), set_up_butchery_activity(), size_factor_in_time_to_cut(), skill_electronics, skill_firstaid, skill_survival, SKIN, and item::tname().
chop_logs_finish()
void activity_handlers::chop_logs_finish (player_activity * act, player * p)
Definition at line 4205 of file activity_handlers.cpp.
{
    map &here = get_map();
    const tripoint &pos = here.getlocal( act->placement );
    int log_quan;
    int stick_quan;
    int splint_quan;
    if( here.ter( pos ) == t_trunk ) {
        log_quan = rng( 2, 3 );
        stick_quan = rng( 0, 1 );
        splint_quan = 0;
    } else if( here.ter( pos ) == t_stump ) {
        log_quan = rng( 0, 2 );
        stick_quan = 0;
        splint_quan = rng( 5, 15 );
    } else {
        log_quan = 0;
        stick_quan = 0;
        splint_quan = 0;
    }
    for( int i = 0; i != log_quan; ++i ) {
        item obj( itype_log, calendar::turn );
        obj.set_var( "activity_var", p->name );
        here.add_item_or_charges( pos, obj );
    }
    for( int i = 0; i != stick_quan; ++i ) {
        item obj( itype_stick_long, calendar::turn );
        obj.set_var( "activity_var", p->name );
        here.add_item_or_charges( pos, obj );
    }
    for( int i = 0; i != splint_quan; ++i ) {
        item obj( itype_splinter, calendar::turn );
        obj.set_var( "activity_var", p->name );
        here.add_item_or_charges( pos, obj );
    }
    here.ter_set( pos, t_dirt );
    const int helpersize = p->get_crafting_helpers( 3 ).size();
    p->mod_stored_nutr( 5 - helpersize );
    p->mod_thirst( 5 - helpersize );
    p->mod_fatigue( 10 - ( helpersize * 2 ) );
    p->add_msg_if_player( m_good, _( "You finish chopping wood." ) );
    act->set_to_null();
    resume_for_multi_activities( *p );
}
References _, act, map::add_item_or_charges(), player::add_msg_if_player(), player::get_crafting_helpers(), get_map(), map::getlocal(), itype_log, itype_splinter, itype_stick_long, m_good, Character::mod_fatigue(), Character::mod_stored_nutr(), Character::mod_thirst(), Character::name, int_id< T >::obj(), resume_for_multi_activities(), rng(), t_dirt, t_stump, t_trunk, map::ter(), map::ter_set(), and calendar::turn.
chop_planks_finish()
void activity_handlers::chop_planks_finish (player_activity * act, player * p)
Fabrication increases number of planks cut from a log
Definition at line 4251 of file activity_handlers.cpp.
{
    const int max_planks = 10;
    /** @EFFECT_FABRICATION increases number of planks cut from a log */
    int planks = normal_roll( 2 + p->get_skill_level( skill_id( "fabrication" ) ), 1 );
    int wasted_planks = max_planks - planks;
    int scraps = rng( wasted_planks, wasted_planks * 3 );
    planks = std::min( planks, max_planks );
    map &here = get_map();
    if( planks > 0 ) {
        here.spawn_item( here.getlocal( act->placement ), itype_2x4, planks, 0, calendar::turn );
        p->add_msg_if_player( m_good, _( "You produce %d planks." ), planks );
    }
    if( scraps > 0 ) {
        here.spawn_item( here.getlocal( act->placement ), itype_splinter, scraps, 0, calendar::turn );
        p->add_msg_if_player( m_good, _( "You produce %d splinters." ), scraps );
    }
    if( planks < max_planks / 2 ) {
        p->add_msg_if_player( m_bad, _( "You waste a lot of the wood." ) );
    }
    act->set_to_null();
    resume_for_multi_activities( *p );
}
References _, act, player::add_msg_if_player(), get_map(), Character::get_skill_level(), map::getlocal(), itype_2x4, itype_splinter, m_bad, m_good, normal_roll(), resume_for_multi_activities(), rng(), map::spawn_item(), and calendar::turn.
chop_tree_do_turn()
void activity_handlers::chop_tree_do_turn (player_activity * act, player * p)
Definition at line 4137 of file activity_handlers.cpp.
{
    map &here = get_map();
    sfx::play_activity_sound( "tool", "axe", sfx::get_heard_volume( here.getlocal( act->placement ) ) );
    if( calendar::once_every( 1_minutes ) ) {
        //~ Sound of a wood chopping tool at work!
        sounds::sound( here.getlocal( act->placement ), 15, sounds::sound_t::activity, _( "CHK!" ) );
    }
    if( calendar::once_every( 6_minutes ) ) {
        p->mod_fatigue( 1 );
    }
    if( calendar::once_every( 12_minutes ) ) {
        p->mod_stored_nutr( 1 );
        p->mod_thirst( 1 );
    }
}
References _, act, sounds::activity, sfx::get_heard_volume(), get_map(), map::getlocal(), Character::mod_fatigue(), Character::mod_stored_nutr(), Character::mod_thirst(), calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
chop_tree_finish()
void activity_handlers::chop_tree_finish (player_activity * act, player * p)
Definition at line 4154 of file activity_handlers.cpp.
{
    map &here = get_map();
    const tripoint &pos = here.getlocal( act->placement );
    tripoint direction;
    if( !p->is_npc() ) {
        if( p->backlog.empty() || p->backlog.front().id() != ACT_MULTIPLE_CHOP_TREES ) {
            while( true ) {
                if( const cata::optional<tripoint> dir = choose_direction(
                            _( "Select a direction for the tree to fall in." ) ) ) {
                    direction = *dir;
                    break;
                }
                // try again
            }
        }
    } else {
        for( const tripoint &elem : here.points_in_radius( pos, 1 ) ) {
            bool cantuse = false;
            tripoint direc = elem - pos;
            tripoint proposed_to = pos + point( 3 * direction.x, 3 * direction.y );
            std::vector<tripoint> rough_tree_line = line_to( pos, proposed_to );
            for( const tripoint &elem : rough_tree_line ) {
                if( g->critter_at( elem ) ) {
                    cantuse = true;
                    break;
                }
            }
            if( !cantuse ) {
                direction = direc;
            }
        }
    }
    const tripoint to = pos + 3 * direction.xy() + point( rng( -1, 1 ), rng( -1, 1 ) );
    std::vector<tripoint> tree = line_to( pos, to, rng( 1, 8 ) );
    for( const tripoint &elem : tree ) {
        here.batter( elem, 300, 5 );
        here.ter_set( elem, t_trunk );
    }
    here.ter_set( pos, t_stump );
    p->add_msg_if_player( m_good, _( "You finish chopping down a tree." ) );
    // sound of falling tree
    sfx::play_variant_sound( "misc", "timber",
                             sfx::get_heard_volume( here.getlocal( act->placement ) ) );
    act->set_to_null();
    resume_for_multi_activities( *p );
}
References _, act, ACT_MULTIPLE_CHOP_TREES, player::add_msg_if_player(), Character::backlog, map::batter(), choose_direction(), g, sfx::get_heard_volume(), get_map(), map::getlocal(), player::is_npc(), line_to(), m_good, sfx::play_variant_sound(), map::points_in_radius(), resume_for_multi_activities(), rng(), t_stump, t_trunk, map::ter_set(), and tripoint::xy().
chop_trees_do_turn()
void activity_handlers::chop_trees_do_turn (player_activity * act, player * p)
Definition at line 3874 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
churn_do_turn()
void activity_handlers::churn_do_turn (player_activity * act, player * p)
churn_finish()
void activity_handlers::churn_finish (player_activity * act, player * p)
Definition at line 3736 of file activity_handlers.cpp.
{
    map &here = get_map();
    p->add_msg_if_player( _( "You finish churning up the earth here." ) );
    here.ter_set( here.getlocal( act->placement ), t_dirtmound );
    // Go back to what we were doing before
    // could be player zone activity, or could be NPC multi-farming
    act->set_to_null();
    resume_for_multi_activities( *p );
}
References _, act, player::add_msg_if_player(), get_map(), map::getlocal(), resume_for_multi_activities(), t_dirtmound, and map::ter_set().
clear_rubble_finish()
void activity_handlers::clear_rubble_finish (player_activity * act, player * p)
Definition at line 3114 of file activity_handlers.cpp.
{
    const tripoint &pos = act->placement;
    map &here = get_map();
    p->add_msg_if_player( m_info, _( "You clear up the %s." ),
                          here.furnname( pos ) );
    here.furn_set( pos, f_null );
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), f_null, map::furn_set(), map::furnname(), get_map(), and m_info.
consume_drink_menu_do_turn()
void activity_handlers::consume_drink_menu_do_turn (player_activity * act, player * p)
Definition at line 3148 of file activity_handlers.cpp.
{
    avatar_action::eat( g->u, game_menus::inv::consume_drink( g->u ) );
}
References game_menus::inv::consume_drink(), avatar_action::eat(), and g.
consume_food_menu_do_turn()
void activity_handlers::consume_food_menu_do_turn (player_activity * act, player * p)
Definition at line 3143 of file activity_handlers.cpp.
{
    avatar_action::eat( g->u, game_menus::inv::consume_food( g->u ) );
}
References game_menus::inv::consume_food(), avatar_action::eat(), and g.
consume_meds_menu_do_turn()
void activity_handlers::consume_meds_menu_do_turn (player_activity * act, player * p)
Definition at line 3153 of file activity_handlers.cpp.
{
    avatar_action::eat( g->u, game_menus::inv::consume_meds( g->u ) );
}
References game_menus::inv::consume_meds(), avatar_action::eat(), and g.
cracking_do_turn()
void activity_handlers::cracking_do_turn (player_activity * act, player * p)
Definition at line 3303 of file activity_handlers.cpp.
{
    auto cracking_tool = p->crafting_inventory().items_with( []( const item & it ) -> bool {
        item temporary_item( it.type );
        return temporary_item.has_flag( flag_SAFECRACK );
    } );
    if( cracking_tool.empty() && !p->has_bionic( bio_ears ) ) {
        // We lost our cracking tool somehow, bail out.
        act->set_to_null();
        return;
    }
}
References act, bio_ears, Character::crafting_inventory(), flag_SAFECRACK(), Character::has_bionic(), item::has_flag(), visitable< T >::items_with(), and item::type.
cracking_finish()
void activity_handlers::cracking_finish (player_activity * act, player * p)
Definition at line 2513 of file activity_handlers.cpp.
{
    p->add_msg_if_player( m_good, _( "With a satisfying click, the lock on the safe opens!" ) );
    get_map().furn_set( act->placement, f_safe_c );
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), f_safe_c, map::furn_set(), get_map(), and m_good.
craft_do_turn()
void activity_handlers::craft_do_turn (player_activity * act, player * p)
Definition at line 3889 of file activity_handlers.cpp.
{
    item *craft = act->targets.front().get_item();
    // item_location::get_item() will return nullptr if the item is lost
    if( !craft ) {
        p->add_msg_player_or_npc(
            _( "You no longer have the in progress craft in your possession.  "
               "You stop crafting.  "
               "Reactivate the in progress craft to continue crafting." ),
            _( "<npcname> no longer has the in progress craft in their possession.  "
               "<npcname> stops crafting." ) );
        p->cancel_activity();
        return;
    }
    if( !craft->is_craft() ) {
        debugmsg( "ACT_CRAFT target '%s' is not a craft.  Aborting ACT_CRAFT.", craft->tname() );
        p->cancel_activity();
        return;
    }
    if( !p->can_continue_craft( *craft ) ) {
        p->cancel_activity();
        return;
    }
    const recipe &rec = craft->get_making();
    const tripoint bench_pos = act->coords.front();
    // Ugly
    bench_type bench_t = bench_type( act->values[1] );
    const float crafting_speed = crafting_speed_multiplier( *p, *craft, bench_location{bench_t, bench_pos} );
    const int assistants = p->available_assistant_count( craft->get_making() );
    const bool is_long = act->values[0];
    if( crafting_speed <= 0.0f ) {
        p->cancel_activity();
        return;
    }
    // item_counter represents the percent progress relative to the base batch time
    // stored precise to 5 decimal places ( e.g. 67.32 percent would be stored as 6'732'000 )
    const int old_counter = craft->item_counter;
    // Base moves for batch size with no speed modifier or assistants
    // Must ensure >= 1 so we don't divide by 0;
    const double base_total_moves = std::max( 1, rec.batch_time( craft->charges, 1.0f, 0 ) );
    // Current expected total moves, includes crafting speed modifiers and assistants
    const double cur_total_moves = std::max( 1, rec.batch_time( craft->charges, crafting_speed,
                                   assistants ) );
    // Delta progress in moves adjusted for current crafting speed
    const double delta_progress = p->get_moves() * base_total_moves / cur_total_moves;
    // Current progress in moves
    const double current_progress = craft->item_counter * base_total_moves / 10'000'000.0 +
                                    delta_progress;
    // Current progress as a percent of base_total_moves to 2 decimal places
    craft->item_counter = std::round( current_progress / base_total_moves * 10'000'000.0 );
    p->set_moves( 0 );
    // This is to ensure we don't over count skill steps
    craft->item_counter = std::min( craft->item_counter, 10'000'000 );
    // Skill and tools are gained/consumed after every 5% progress
    int five_percent_steps = craft->item_counter / 500'000 - old_counter / 500'000;
    if( five_percent_steps > 0 ) {
        p->craft_skill_gain( *craft, five_percent_steps );
    }
    // Unlike skill, tools are consumed once at the start and should not be consumed at the end
    if( craft->item_counter >= 10'000'000 ) {
        --five_percent_steps;
    }
    if( five_percent_steps > 0 ) {
        if( !p->craft_consume_tools( *craft, five_percent_steps, false ) ) {
            // So we don't skip over any tool comsuption
            craft->item_counter -= craft->item_counter % 500000 + 1;
            p->cancel_activity();
            return;
        }
    }
    // if item_counter has reached 100% or more
    if( craft->item_counter >= 10'000'000 ) {
        item craft_copy = *craft;
        act->targets.front().remove_item();
        p->cancel_activity();
        complete_craft( *p, craft_copy, bench_location{bench_t, bench_pos} );
        if( is_long ) {
            if( p->making_would_work( p->lastrecipe, craft_copy.charges ) ) {
                p->last_craft->execute( bench_pos );
            }
        }
    } else if( craft->item_counter >= craft->get_next_failure_point() ) {
        bool destroy = craft->handle_craft_failure( *p );
        // If the craft needs to be destroyed, do it and stop crafting.
        if( destroy ) {
            p->add_msg_player_or_npc( _( "There is nothing left of the %s to craft from." ),
                                      _( "There is nothing left of the %s <npcname> was crafting." ), craft->tname() );
            act->targets.front().remove_item();
            p->cancel_activity();
        }
    }
}
References _, act, player::add_msg_player_or_npc(), player::available_assistant_count(), recipe::batch_time(), player::can_continue_craft(), Character::cancel_activity(), item::charges, complete_craft(), iuse::craft(), player::craft_consume_tools(), player::craft_skill_gain(), crafting_speed_multiplier(), debugmsg, Creature::get_moves(), player::last_craft, player::lastrecipe, player::making_would_work(), and Creature::set_moves().
drop_do_turn()
void activity_handlers::drop_do_turn (player_activity * act, player * p)
eat_menu_do_turn()
void activity_handlers::eat_menu_do_turn (player_activity * act, player * p)
Definition at line 3138 of file activity_handlers.cpp.
{
    avatar_action::eat( g->u );
}
References avatar_action::eat(), and g.
eat_menu_finish()
void activity_handlers::eat_menu_finish (player_activity * act, player * p)
Definition at line 4009 of file activity_handlers.cpp.
{
    // Only exists to keep the eat activity alive between turns
    return;
}
fertilize_plot_do_turn()
void activity_handlers::fertilize_plot_do_turn (player_activity * act, player * p)
Definition at line 4443 of file activity_handlers.cpp.
{
    itype_id fertilizer;
    auto check_fertilizer = [&]( bool ask_user = true ) -> void {
        if( act->str_values.empty() )
        {
            act->str_values.push_back( "" );
        }
        fertilizer = itype_id( act->str_values[0] );
        /* If unspecified, or if we're out of what we used before, ask */
        if( ask_user && ( fertilizer.is_empty() || !p->has_charges( fertilizer, 1 ) ) )
        {
            fertilizer = iexamine::choose_fertilizer( *p, "plant",
                    false /* Don't confirm action with player */ );
            act->str_values[0] = fertilizer.str();
        }
    };
    auto have_fertilizer = [&]() {
        return !fertilizer.is_empty() && p->has_charges( fertilizer, 1 );
    };
    const auto reject_tile = [&]( const tripoint & tile ) {
        check_fertilizer();
        ret_val<bool> can_fert = iexamine::can_fertilize( *p, tile, fertilizer );
        return !can_fert.success();
    };
    const auto fertilize = [&]( player & p, const tripoint & tile ) {
        check_fertilizer();
        if( have_fertilizer() ) {
            iexamine::fertilize_plant( p, tile, fertilizer );
            if( !have_fertilizer() ) {
                add_msg( m_info, _( "You have run out of %s." ), item::nname( fertilizer ) );
            }
        }
    };
    check_fertilizer();
    if( !have_fertilizer() ) {
        act->set_to_null();
        return;
    }
    perform_zone_activity_turn( p,
                                zone_type_FARM_PLOT,
                                reject_tile,
                                fertilize,
                                _( "You fertilized every plot you could." ) );
}
References _, act, add_msg(), iexamine::can_fertilize(), iexamine::choose_fertilizer(), iexamine::fertilize_plant(), Character::has_charges(), string_id< T >::is_empty(), m_info, item::nname(), perform_zone_activity_turn(), string_id< T >::str(), ret_val< T >::success(), and zone_type_FARM_PLOT.
fetch_do_turn()
void activity_handlers::fetch_do_turn (player_activity * act, player * p)
Definition at line 3884 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
fill_liquid_do_turn()
void activity_handlers::fill_liquid_do_turn (player_activity * act, player * p)
Definition at line 1495 of file activity_handlers.cpp.
{
    player_activity &act_ref = *act;
    try {
        // 1. Gather the source item.
        vehicle *source_veh = nullptr;
        const tripoint source_pos = act_ref.coords.at( 0 );
        map &here = get_map();
        map_stack source_stack = here.i_at( source_pos );
        map_stack::iterator on_ground;
        monster *source_mon = nullptr;
        item liquid;
        const liquid_source_type source_type = static_cast<liquid_source_type>( act_ref.values.at( 0 ) );
        int part_num = -1;
        int veh_charges = 0;
        switch( source_type ) {
            case LST_VEHICLE:
                source_veh = veh_pointer_or_null( here.veh_at( source_pos ) );
                if( source_veh == nullptr ) {
                    throw std::runtime_error( "could not find source vehicle for liquid transfer" );
                }
                deserialize( liquid, act_ref.str_values.at( 0 ) );
                part_num = static_cast<int>( act_ref.values.at( 1 ) );
                veh_charges = liquid.charges;
                break;
            case LST_INFINITE_MAP:
                deserialize( liquid, act_ref.str_values.at( 0 ) );
                liquid.charges = item::INFINITE_CHARGES;
                break;
            case LST_MAP_ITEM:
                if( static_cast<size_t>( act_ref.values.at( 1 ) ) >= source_stack.size() ) {
                    throw std::runtime_error( "could not find source item on ground for liquid transfer" );
                }
                on_ground = source_stack.begin();
                std::advance( on_ground, act_ref.values.at( 1 ) );
                liquid = *on_ground;
                break;
            case LST_MONSTER:
                Creature *c = g->critter_at( source_pos );
                source_mon = dynamic_cast<monster *>( c );
                if( source_mon == nullptr ) {
                    debugmsg( "could not find source creature for liquid transfer" );
                    act_ref.set_to_null();
                }
                deserialize( liquid, act_ref.str_values.at( 0 ) );
                liquid.charges = 1;
                break;
        }
        static const units::volume volume_per_second = units::from_liter( 4.0F / 6.0F );
        const int charges_per_second = std::max( 1, liquid.charges_per_volume( volume_per_second ) );
        liquid.charges = std::min( charges_per_second, liquid.charges );
        const int original_charges = liquid.charges;
        // 2. Transfer charges.
        switch( static_cast<liquid_target_type>( act_ref.values.at( 2 ) ) ) {
            case LTT_VEHICLE:
                if( const optional_vpart_position vp = here.veh_at( act_ref.coords.at( 1 ) ) ) {
                    p->pour_into( vp->vehicle(), liquid );
                } else {
                    throw std::runtime_error( "could not find target vehicle for liquid transfer" );
                }
                break;
            case LTT_CONTAINER:
                p->pour_into( p->i_at( act_ref.values.at( 3 ) ), liquid );
                break;
            case LTT_MAP:
                if( iexamine::has_keg( act_ref.coords.at( 1 ) ) ) {
                    iexamine::pour_into_keg( act_ref.coords.at( 1 ), liquid );
                } else {
                    here.add_item_or_charges( act_ref.coords.at( 1 ), liquid );
                    p->add_msg_if_player( _( "You pour %1$s onto the ground." ), liquid.tname() );
                    liquid.charges = 0;
                }
                break;
            case LTT_MONSTER:
                liquid.charges = 0;
                break;
        }
        const int removed_charges = original_charges - liquid.charges;
        if( removed_charges == 0 ) {
            // Nothing has been transferred, target must be full.
            act_ref.set_to_null();
            return;
        }
        // 3. Remove charges from source.
        switch( source_type ) {
            case LST_VEHICLE:
                if( part_num != -1 ) {
                    source_veh->drain( part_num, removed_charges );
                    liquid.charges = veh_charges - removed_charges;
                    // If there's no liquid left in this tank we're done, otherwise
                    // we need to update our liquid serialization to reflect how
                    // many charges are actually left for the next time we come
                    // around this loop.
                    if( !liquid.charges ) {
                        act_ref.set_to_null();
                    } else {
                        if( act_ref.str_values.empty() ) {
                            act_ref.str_values.push_back( std::string() );
                        }
                        act_ref.str_values.at( 0 ) = serialize( liquid );
                    }
                } else {
                    source_veh->drain( liquid.typeId(), removed_charges );
                }
                if( source_veh->fuel_left( liquid.typeId() ) <= 0 ) {
                    act_ref.set_to_null();
                }
                break;
            case LST_MAP_ITEM:
                on_ground->charges -= removed_charges;
                if( on_ground->charges <= 0 ) {
                    source_stack.erase( on_ground );
                    if( here.ter( source_pos ).obj().examine == &iexamine::gaspump ) {
                        add_msg( _( "With a clang and a shudder, the %s pump goes silent." ),
                                 liquid.type_name( 1 ) );
                    } else if( here.furn( source_pos ).obj().examine == &iexamine::fvat_full ) {
                        add_msg( _( "You squeeze the last drops of %s from the vat." ),
                                 liquid.type_name( 1 ) );
                        map_stack items_here = here.i_at( source_pos );
                        if( items_here.empty() ) {
                            here.furn_set( source_pos, f_fvat_empty );
                        }
                    }
                    act_ref.set_to_null();
                }
                break;
            case LST_INFINITE_MAP:
                // nothing, the liquid source is infinite
                break;
            case LST_MONSTER:
                // liquid source charges handled in monexamine::milk_source
                if( liquid.charges == 0 ) {
                    act_ref.set_to_null();
                }
                break;
        }
        if( removed_charges < original_charges ) {
            // Transferred less than the available charges -> target must be full
            act_ref.set_to_null();
        }
    } catch( const std::runtime_error &err ) {
        debugmsg( "error in activity data: \"%s\"", err.what() );
        act_ref.set_to_null();
        return;
    }
}
References _, act, map::add_item_or_charges(), add_msg(), player::add_msg_if_player(), item_stack::begin(), c, item::charges, item::charges_per_volume(), player_activity::coords, debugmsg, deserialize(), vehicle::drain(), item_stack::empty(), map_stack::erase(), map_data_common_t::examine, f_fvat_empty, units::from_liter(), vehicle::fuel_left(), map::furn(), map::furn_set(), iexamine::fvat_full(), g, iexamine::gaspump(), get_map(), iexamine::has_keg(), map::i_at(), Character::i_at(), item::INFINITE_CHARGES, LST_INFINITE_MAP, LST_MAP_ITEM, LST_MONSTER, LST_VEHICLE, LTT_CONTAINER, LTT_MAP, LTT_MONSTER, LTT_VEHICLE, int_id< T >::obj(), Character::pour_into(), iexamine::pour_into_keg(), serialize(), player_activity::set_to_null(), item_stack::size(), player_activity::str_values, map::ter(), item::tname(), item::type_name(), item::typeId(), player_activity::values, map::veh_at(), and veh_pointer_or_null().
fill_pit_do_turn()
void activity_handlers::fill_pit_do_turn (player_activity * act, player * p)
Definition at line 4318 of file activity_handlers.cpp.
{
    sfx::play_activity_sound( "tool", "shovel", 100 );
    if( calendar::once_every( 1_minutes ) ) {
        //~ Sound of a shovel filling a pit or mound at work!
        sounds::sound( act->placement, 10, sounds::sound_t::activity, _( "hsh!" ) );
    }
}
References _, act, sounds::activity, calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
fill_pit_finish()
void activity_handlers::fill_pit_finish (player_activity * act, player * p)
Definition at line 4327 of file activity_handlers.cpp.
{
    const tripoint &pos = act->placement;
    map &here = get_map();
    const ter_id ter = here.ter( pos );
    const ter_id old_ter = ter;
    if( ter == t_pit || ter == t_pit_spiked || ter == t_pit_glass ||
        ter == t_pit_corpsed ) {
        here.ter_set( pos, t_pit_shallow );
    } else {
        here.ter_set( pos, t_dirt );
    }
    const int helpersize = g->u.get_crafting_helpers( 3 ).size();
    p->mod_stored_nutr( 5 - helpersize );
    p->mod_thirst( 5 - helpersize );
    p->mod_fatigue( 10 - ( helpersize * 2 ) );
    p->add_msg_if_player( m_good, _( "You finish filling up %s." ), old_ter.obj().name() );
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), g, get_map(), m_good, Character::mod_fatigue(), Character::mod_stored_nutr(), Character::mod_thirst(), map_data_common_t::name(), int_id< T >::obj(), t_dirt, t_pit, t_pit_corpsed, t_pit_glass, t_pit_shallow, t_pit_spiked, map::ter(), and map::ter_set().
find_mount_do_turn()
void activity_handlers::find_mount_do_turn (player_activity * act, player * p)
Definition at line 3391 of file activity_handlers.cpp.
{
    //npc only activity
    if( p->is_player() ) {
        act->set_to_null();
        return;
    }
    npc &guy = dynamic_cast<npc &>( *p );
    monster *mon = guy.chosen_mount.lock().get();
    if( !mon ) {
        act->set_to_null();
        guy.revert_after_activity();
        return;
    }
    if( rl_dist( guy.pos(), mon->pos() ) <= 1 ) {
        if( mon->has_effect( effect_ai_waiting ) ) {
            mon->remove_effect( effect_ai_waiting );
        }
        if( p->can_mount( *mon ) ) {
            act->set_to_null();
            guy.revert_after_activity();
            guy.chosen_mount = weak_ptr_fast<monster>();
            p->mount_creature( *mon );
        } else {
            act->set_to_null();
            guy.revert_after_activity();
            return;
        }
    } else {
        const std::vector<tripoint> route = route_adjacent( *p, guy.chosen_mount.lock()->pos() );
        if( route.empty() ) {
            act->set_to_null();
            guy.revert_after_activity();
            mon->remove_effect( effect_ai_waiting );
            return;
        } else {
            p->activity = player_activity();
            mon->add_effect( effect_ai_waiting, 40_turns );
            p->set_destination( route, player_activity( ACT_FIND_MOUNT ) );
        }
    }
}
References act, ACT_FIND_MOUNT, Character::activity, monster::add_effect(), Character::can_mount(), npc::chosen_mount, effect_ai_waiting, Creature::has_effect(), player::is_player(), Character::mount_creature(), Character::pos(), monster::pos(), Creature::remove_effect(), npc::revert_after_activity(), rl_dist(), route_adjacent(), and Character::set_destination().
firstaid_finish()
void activity_handlers::firstaid_finish (player_activity * act, player * p)
Definition at line 1648 of file activity_handlers.cpp.
{
    static const std::string iuse_name_string( "heal" );
    item &it = *act->targets.front();
    item *used_tool = it.get_usable_item( iuse_name_string );
    if( used_tool == nullptr ) {
        debugmsg( "Lost tool used for healing" );
        act->set_to_null();
        return;
    }
    const use_function *use_fun = used_tool->get_use( iuse_name_string );
    const heal_actor *actor = dynamic_cast<const heal_actor *>( use_fun->get_actor_ptr() );
    if( actor == nullptr ) {
        debugmsg( "iuse_actor type descriptor and actual type mismatch" );
        act->set_to_null();
        return;
    }
    // TODO: Store the patient somehow, retrieve here
    player &patient = *p;
    const hp_part healed = static_cast<hp_part>( act->values[0] );
    const int charges_consumed = actor->finish_using( *p, patient, *used_tool, healed );
    p->consume_charges( it, charges_consumed );
    // Erase activity and values.
    act->set_to_null();
    act->values.clear();
}
References act, Character::consume_charges(), debugmsg, heal_actor::finish_using(), use_function::get_actor_ptr(), item::get_usable_item(), and item::get_use().
fish_do_turn()
void activity_handlers::fish_do_turn (player_activity * act, player * p)
Definition at line 3258 of file activity_handlers.cpp.
{
    item &it = *act->targets.front();
    int fish_chance = 1;
    int survival_skill = p->get_skill_level( skill_survival );
    if( it.has_flag( flag_FISH_POOR ) ) {
        survival_skill += dice( 1, 6 );
    } else if( it.has_flag( flag_FISH_GOOD ) ) {
        // Much better chances with a good fishing implement.
        survival_skill += dice( 4, 9 );
        survival_skill *= 2;
    }
    std::vector<monster *> fishables = g->get_fishable_monsters( act->coord_set );
    // Fish are always there, even if it dosnt seem like they are visible!
    if( fishables.empty() ) {
        fish_chance += survival_skill / 2;
    } else {
        // if they are visible however, it implies a larger population
        for( monster *elem : fishables ) {
            fish_chance += elem->fish_population;
        }
        fish_chance += survival_skill;
    }
    // no matter the population of fish, your skill and tool limits the ease of catching.
    fish_chance = std::min( survival_skill * 10, fish_chance );
    if( x_in_y( fish_chance, 600000 ) ) {
        p->add_msg_if_player( m_good, _( "You feel a tug on your line!" ) );
        rod_fish( p, fishables );
    }
    if( calendar::once_every( 60_minutes ) ) {
        p->practice( skill_survival, rng( 1, 3 ) );
    }
}
References _, act, player::add_msg_if_player(), dice(), flag_FISH_GOOD(), flag_FISH_POOR(), g, Character::get_skill_level(), item::has_flag(), m_good, calendar::once_every(), player::practice(), rng(), rod_fish(), skill_survival, and x_in_y().
fish_finish()
void activity_handlers::fish_finish (player_activity * act, player * p)
Definition at line 3293 of file activity_handlers.cpp.
{
    act->set_to_null();
    p->add_msg_if_player( m_info, _( "You finish fishing" ) );
    if( !p->backlog.empty() && p->backlog.front().id() == ACT_MULTIPLE_FISH ) {
        p->backlog.clear();
        p->assign_activity( ACT_TIDY_UP );
    }
}
References _, act, ACT_MULTIPLE_FISH, ACT_TIDY_UP, player::add_msg_if_player(), Character::assign_activity(), Character::backlog, and m_info.
forage_finish()
void activity_handlers::forage_finish (player_activity * act, player * p)
Perception slightly increases forage success chance \EFFECT_SURVIVAL increases forage success chance
Definition at line 1679 of file activity_handlers.cpp.
{
    // Don't forage if we aren't next to the bush - otherwise we get weird bugs
    bool next_to_bush = false;
    map &here = get_map();
    for( const tripoint &pnt : here.points_in_radius( p->pos(), 1 ) ) {
        if( here.getabs( pnt ) == act->placement ) {
            next_to_bush = true;
            break;
        }
    }
    if( !next_to_bush ) {
        act->set_to_null();
        return;
    }
    const int veggy_chance = rng( 1, 100 );
    bool found_something = false;
    item_group_id loc;
    ter_str_id next_ter;
    switch( season_of_year( calendar::turn ) ) {
        case SPRING:
            loc = item_group_id( "forage_spring" );
            next_ter = ter_str_id( "t_underbrush_harvested_spring" );
            break;
        case SUMMER:
            loc = item_group_id( "forage_summer" );
            next_ter = ter_str_id( "t_underbrush_harvested_summer" );
            break;
        case AUTUMN:
            loc = item_group_id( "forage_autumn" );
            next_ter = ter_str_id( "t_underbrush_harvested_autumn" );
            break;
        case WINTER:
            loc = item_group_id( "forage_winter" );
            next_ter = ter_str_id( "t_underbrush_harvested_winter" );
            break;
        default:
            debugmsg( "Invalid season" );
    }
    here.ter_set( here.getlocal( act->placement ), next_ter );
    // Survival gives a bigger boost, and Perception is leveled a bit.
    // Both survival and perception affect time to forage
    ///\EFFECT_PER slightly increases forage success chance
    ///\EFFECT_SURVIVAL increases forage success chance
    if( veggy_chance < p->get_skill_level( skill_survival ) * 3 + p->per_cur - 2 ) {
        const std::vector<item *> dropped = here.put_items_from_loc( loc, p->pos(), calendar::turn );
        for( item *it : dropped ) {
            add_msg( m_good, _( "You found: %s!" ), it->tname() );
            found_something = true;
            if( it->has_flag( flag_FORAGE_POISON ) && one_in( 10 ) ) {
                it->set_flag( flag_HIDDEN_POISON );
                it->poison = rng( 2, 7 );
            }
            if( it->has_flag( flag_FORAGE_HALLU ) && !it->has_flag( flag_HIDDEN_POISON ) && one_in( 10 ) ) {
                it->set_flag( flag_HIDDEN_HALLU );
            }
        }
    }
    // 10% to drop a item/items from this group.
    if( one_in( 10 ) ) {
        const std::vector<item *> dropped = here.put_items_from_loc( item_group_id( "trash_forest" ),
                                            p->pos(),
                                            calendar::turn );
        for( item * const &it : dropped ) {
            add_msg( m_good, _( "You found: %s!" ), it->tname() );
            found_something = true;
        }
    }
    if( !found_something ) {
        add_msg( _( "You didn't find anything." ) );
    }
    iexamine::practice_survival_while_foraging( p );
    act->set_to_null();
}
References _, act, add_msg(), AUTUMN, debugmsg, flag_FORAGE_HALLU(), flag_FORAGE_POISON(), flag_HIDDEN_HALLU(), flag_HIDDEN_POISON(), get_map(), map::getabs(), map::getlocal(), m_good, one_in(), Character::per_cur, map::points_in_radius(), Character::pos(), iexamine::practice_survival_while_foraging(), map::put_items_from_loc(), rng(), season_of_year(), skill_survival, SPRING, SUMMER, map::ter_set(), calendar::turn, and WINTER.
game_do_turn()
void activity_handlers::game_do_turn (player_activity * act, player * p)
Definition at line 1773 of file activity_handlers.cpp.
{
    item &game_item = *act->targets.front();
    // Consume battery charges for every minute spent playing
    if( calendar::once_every( 1_minutes ) ) {
        int energy = game_item.ammo_required();
        energy -= game_item.ammo_consume( energy, p->pos() );
        if( energy > 0 && game_item.has_flag( flag_USE_UPS ) ) {
            if( p->use_charges_if_avail( itype_UPS, energy ) ) {
                energy = 0;
            }
        }
        // Morale boost from game is handled in iuse::portable_game
        if( energy ) {
            act->moves_left = 0;
            add_msg( m_info, _( "The %s runs out of batteries." ), game_item.tname() );
        }
    }
}
References _, act, add_msg(), item::ammo_consume(), item::ammo_required(), flag_USE_UPS(), item::has_flag(), itype_UPS, m_info, calendar::once_every(), Character::pos(), item::tname(), and Character::use_charges_if_avail().
generic_game_do_turn()
void activity_handlers::generic_game_do_turn (player_activity * act, player * p)
Definition at line 1764 of file activity_handlers.cpp.
{
    if( calendar::once_every( 1_minutes ) ) {
        // So 30 points per play
        p->add_morale( MORALE_GAME, 2, 60, 2_hours, 30_minutes, true );
        return;
    }
}
References Character::add_morale(), MORALE_GAME, and calendar::once_every().
gunmod_add_finish()
void activity_handlers::gunmod_add_finish (player_activity * act, player * p)
Definition at line 3042 of file activity_handlers.cpp.
{
    act->set_to_null();
    // first unpack all of our arguments
    if( act->values.size() != 4 ) {
        debugmsg( "Insufficient arguments to ACT_GUNMOD_ADD" );
        return;
    }
    item &gun = *act->targets.at( 0 );
    item &mod = *act->targets.at( 1 );
    // chance of success (%)
    const int roll = act->values[1];
    // chance of damage (%)
    const int risk = act->values[2];
    // any tool charges used during installation
    const itype_id tool( act->name );
    const int qty = act->values[3];
    if( !gun.is_gunmod_compatible( mod ).success() ) {
        debugmsg( "Invalid arguments in ACT_GUNMOD_ADD" );
        return;
    }
    if( !tool.is_empty() && qty > 0 ) {
        p->use_charges( tool, qty );
    }
    if( rng( 0, 100 ) <= roll ) {
        add_msg( m_good, _( "You successfully attached the %1$s to your %2$s." ), mod.tname(),
                 gun.tname() );
        gun.put_in( p->i_rem( &mod ) );
    } else if( rng( 0, 100 ) <= risk ) {
        if( gun.inc_damage() ) {
            // Remove irremovable mods prior to destroying the gun
            for( item *mod : gun.gunmods() ) {
                if( mod->is_irremovable() ) {
                    p->remove_item( *mod );
                }
            }
            add_msg( m_bad, _( "You failed at installing the %s and destroyed your %s!" ), mod.tname(),
                     gun.tname() );
            p->i_rem( &gun );
        } else {
            add_msg( m_bad, _( "You failed at installing the %s and damaged your %s!" ), mod.tname(),
                     gun.tname() );
        }
    } else {
        add_msg( m_info, _( "You failed at installing the %s." ), mod.tname() );
    }
}
References _, act, add_msg(), debugmsg, item::gunmods(), Character::i_rem(), item::inc_damage(), item::is_gunmod_compatible(), m_bad, m_good, m_info, item::put_in(), visitable< T >::remove_item(), rng(), item::tname(), tool, and Character::use_charges().
hacksaw_do_turn()
void activity_handlers::hacksaw_do_turn (player_activity * act, player * p)
Definition at line 4015 of file activity_handlers.cpp.
{
    sfx::play_activity_sound( "tool", "hacksaw", sfx::get_heard_volume( act->placement ) );
    if( calendar::once_every( 1_minutes ) ) {
        //~ Sound of a metal sawing tool at work!
        sounds::sound( act->placement, 15, sounds::sound_t::destructive_activity, _( "grnd grnd grnd" ) );
    }
}
References _, act, sounds::destructive_activity, sfx::get_heard_volume(), calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
hacksaw_finish()
void activity_handlers::hacksaw_finish (player_activity * act, player * p)
Definition at line 4024 of file activity_handlers.cpp.
{
    const tripoint &pos = act->placement;
    map &here = get_map();
    const ter_id ter = here.ter( pos );
    if( here.furn( pos ) == f_rack ) {
        here.furn_set( pos, f_null );
        here.spawn_item( p->pos(), itype_pipe, rng( 1, 3 ) );
        here.spawn_item( p->pos(), itype_steel_chunk );
    } else if( ter == t_chainfence || ter == t_chaingate_c || ter == t_chaingate_l ) {
        here.ter_set( pos, t_dirt );
        here.spawn_item( p->pos(), itype_pipe, 6 );
        here.spawn_item( p->pos(), itype_wire, 20 );
    } else if( ter == t_chainfence_posts ) {
        here.ter_set( pos, t_dirt );
        here.spawn_item( p->pos(), itype_pipe, 6 );
    } else if( ter == t_window_bars_alarm ) {
        here.ter_set( pos, t_window_alarm );
        here.spawn_item( p->pos(), itype_pipe, 6 );
    } else if( ter == t_window_bars ) {
        here.ter_set( pos, t_window_empty );
        here.spawn_item( p->pos(), itype_pipe, 6 );
    } else if( ter == t_window_enhanced ) {
        here.ter_set( pos, t_window_reinforced );
        here.spawn_item( p->pos(), itype_spike, rng( 1, 4 ) );
    } else if( ter == t_window_enhanced_noglass ) {
        here.ter_set( pos, t_window_reinforced_noglass );
        here.spawn_item( p->pos(), itype_spike, rng( 1, 4 ) );
    } else if( ter == t_reb_cage ) {
        here.ter_set( pos, t_pit );
        here.spawn_item( p->pos(), itype_spike, 19 );
        here.spawn_item( p->pos(), itype_scrap, 8 );
    } else if( ter == t_bars ) {
        if( here.ter( pos + point_east ) == t_sewage || here.ter( pos + point_south )
            == t_sewage ||
            here.ter( pos + point_west ) == t_sewage || here.ter( pos + point_north ) ==
            t_sewage ) {
            here.ter_set( pos, t_sewage );
            here.spawn_item( p->pos(), itype_pipe, 3 );
        } else {
            here.ter_set( pos, t_floor );
            here.spawn_item( p->pos(), itype_pipe, 3 );
        }
    } else if( ter == t_door_bar_c || ter == t_door_bar_locked ) {
        here.ter_set( pos, t_mdoor_frame );
        here.spawn_item( p->pos(), itype_pipe, 12 );
    }
    p->mod_stored_nutr( 5 );
    p->mod_thirst( 5 );
    p->mod_fatigue( 10 );
    p->add_msg_if_player( m_good, _( "You finish cutting the metal." ) );
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), f_null, f_rack, map::furn(), map::furn_set(), get_map(), itype_pipe, itype_scrap, itype_spike, itype_steel_chunk, itype_wire, m_good, Character::mod_fatigue(), Character::mod_stored_nutr(), Character::mod_thirst(), point_east, point_north, point_south, point_west, Character::pos(), rng(), map::spawn_item(), t_bars, t_chainfence, t_chainfence_posts, t_chaingate_c, t_chaingate_l, t_dirt, t_door_bar_c, t_door_bar_locked, t_floor, t_mdoor_frame, t_pit, t_reb_cage, t_sewage, t_window_alarm, t_window_bars, t_window_bars_alarm, t_window_empty, t_window_enhanced, t_window_enhanced_noglass, t_window_reinforced, t_window_reinforced_noglass, map::ter(), and map::ter_set().
haircut_finish()
void activity_handlers::haircut_finish (player_activity * act, player * p)
Definition at line 4364 of file activity_handlers.cpp.
{
    p->add_msg_if_player( _( "You give your hair a trim." ) );
    p->add_morale( MORALE_HAIRCUT, 3, 3, 480_minutes, 3_minutes );
    act->set_to_null();
}
References _, act, Character::add_morale(), player::add_msg_if_player(), and MORALE_HAIRCUT.
hand_crank_do_turn()
void activity_handlers::hand_crank_do_turn (player_activity * act, player * p)
Definition at line 2309 of file activity_handlers.cpp.
{
    // Hand-crank chargers seem to range from 2 watt (very common easily verified)
    // to 10 watt (suspicious claims from some manufacturers) sustained output.
    // It takes 2.4 minutes to produce 1kj at just slightly under 7 watts (25 kj per hour)
    // time-based instead of speed based because it's a sustained activity
    item &hand_crank_item = *act->targets.front();
    if( calendar::once_every( 144_seconds ) ) {
        p->mod_fatigue( 1 );
        if( hand_crank_item.ammo_capacity() > hand_crank_item.ammo_remaining() ) {
            hand_crank_item.ammo_set( itype_battery, hand_crank_item.ammo_remaining() + 1 );
        } else {
            act->moves_left = 0;
            add_msg( m_info, _( "You've charged the battery completely." ) );
        }
    }
    if( p->get_fatigue() >= fatigue_levels::dead_tired ) {
        act->moves_left = 0;
        add_msg( m_info, _( "You're too exhausted to keep cranking." ) );
    }
}
References _, act, add_msg(), item::ammo_capacity(), item::ammo_remaining(), item::ammo_set(), dead_tired, Character::get_fatigue(), itype_battery, m_info, Character::mod_fatigue(), and calendar::once_every().
hand_crank_finish()
void activity_handlers::hand_crank_finish (player_activity * act, player * p)
hotwire_finish()
void activity_handlers::hotwire_finish (player_activity * act, player * p)
Definition at line 1794 of file activity_handlers.cpp.
{
    //Grab this now, in case the vehicle gets shifted
    if( const optional_vpart_position vp = g->m.veh_at( g->m.getlocal( tripoint( act->values[0],
                                           act->values[1],
                                           p->posz() ) ) ) ) {
        vehicle *const veh = &vp->vehicle();
        const int mech_skill = act->values[2];
        if( mech_skill > static_cast<int>( rng( 1, 6 ) ) ) {
            //success
            veh->is_locked = false;
            add_msg( _( "This wire will start the engine." ) );
        } else if( mech_skill > static_cast<int>( rng( 0, 4 ) ) ) {
            //soft fail
            veh->is_locked = false;
            veh->is_alarm_on = veh->has_security_working();
            add_msg( _( "This wire will probably start the engine." ) );
        } else if( veh->is_alarm_on ) {
            veh->is_locked = false;
            add_msg( _( "By process of elimination, this wire will start the engine." ) );
        } else {
            //hard fail
            veh->is_alarm_on = veh->has_security_working();
            add_msg( _( "The red wire always starts the engine, doesn't it?" ) );
        }
    } else {
        debugmsg( "process_activity ACT_HOTWIRE_CAR: vehicle not found" );
    }
    act->set_to_null();
}
References _, act, add_msg(), debugmsg, g, vehicle::has_security_working(), vehicle::is_alarm_on, vehicle::is_locked, Character::posz(), rng(), and vehicle::vehicle().
jackhammer_do_turn()
void activity_handlers::jackhammer_do_turn (player_activity * act, player * p)
Definition at line 4276 of file activity_handlers.cpp.
{
    map &here = get_map();
    sfx::play_activity_sound( "tool", "jackhammer",
                              sfx::get_heard_volume( here.getlocal( act->placement ) ) );
    if( calendar::once_every( 1_minutes ) ) {
        sounds::sound( here.getlocal( act->placement ), 15, sounds::sound_t::destructive_activity,
                       //~ Sound of a jackhammer at work!
                       _( "TATATATATATATAT!" ) );
    }
}
References _, act, sounds::destructive_activity, sfx::get_heard_volume(), get_map(), map::getlocal(), calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
jackhammer_finish()
void activity_handlers::jackhammer_finish (player_activity * act, player * p)
Definition at line 4288 of file activity_handlers.cpp.
{
    map &here = get_map();
    const tripoint &pos = here.getlocal( act->placement );
    here.destroy( pos, true );
    if( p->is_avatar() ) {
        const int helpersize = g->u.get_crafting_helpers( 3 ).size();
        p->mod_stored_nutr( 5 - helpersize );
        p->mod_thirst( 5 - helpersize );
        p->mod_fatigue( 10 - ( helpersize * 2 ) );
    }
    p->add_msg_player_or_npc( m_good,
                              _( "You finish drilling." ),
                              _( "<npcname> finishes drilling." ) );
    act->set_to_null();
    if( !act->targets.empty() ) {
        item &it = *act->targets.front();
        p->consume_charges( it, it.ammo_required() );
    } else {
        debugmsg( "jackhammer activity targets empty" );
    }
    if( resume_for_multi_activities( *p ) ) {
        for( item &elem : here.i_at( pos ) ) {
            elem.set_var( "activity_var", p->name );
        }
    }
}
References _, act, player::add_msg_player_or_npc(), item::ammo_required(), Character::consume_charges(), debugmsg, map::destroy(), g, get_map(), map::getlocal(), map::i_at(), Creature::is_avatar(), m_good, Character::mod_fatigue(), Character::mod_stored_nutr(), Character::mod_thirst(), Character::name, and resume_for_multi_activities().
lockpicking_finish()
void activity_handlers::lockpicking_finish (player_activity * act, player * p)
Dexterity improves chances of successfully picking door lock, reduces chances of bad outcomes Mechanics improves chances of successfully picking door lock, reduces chances of bad outcomes
Definition at line 2520 of file activity_handlers.cpp.
{
    item_location &loc = act->targets[ 0 ];
    item *it = loc.get_item();
    if( it == nullptr ) {
        debugmsg( "lockpick item location lost" );
        return;
    }
    const ter_id ter_type = g->m.ter( act->placement );
    const furn_id furn_type = g->m.furn( act->placement );
    lockpicking_open_result lr = get_lockpicking_open_result( ter_type, furn_type );
    ter_id new_ter_type = lr.new_ter_type;
    furn_id new_furn_type = lr.new_furn_type;
    std::string open_message = lr.open_message;
    if( new_ter_type == t_null && new_furn_type == f_null ) {
        act->set_to_null();
    }
    bool destroy = false;
    /** @EFFECT_DEX improves chances of successfully picking door lock, reduces chances of bad outcomes */
    /** @EFFECT_MECHANICS improves chances of successfully picking door lock, reduces chances of bad outcomes */
    int pick_roll = 5 *
                    ( std::pow( 1.3, p->get_skill_level( skill_mechanics ) ) +
                      it->get_quality( qual_LOCKPICK ) - it->damage() / 2000.0 ) +
                    p->dex_cur / 4.0;
    int lock_roll = rng( 1, 120 );
    if( pick_roll >= lock_roll ) {
        g->m.has_furn( act->placement ) ?
        g->m.furn_set( act->placement, new_furn_type ) :
        static_cast<void>( g->m.ter_set( act->placement, new_ter_type ) );
        p->add_msg_if_player( m_good, open_message );
    } else if( furn_type == f_gunsafe_ml && lock_roll > ( 3 * pick_roll ) ) {
        p->add_msg_if_player( m_bad, _( "Your clumsy attempt jams the lock!" ) );
        g->m.furn_set( act->placement, furn_str_id( "f_gunsafe_mj" ) );
    } else if( lock_roll > ( 1.5 * pick_roll ) ) {
        if( it->inc_damage() ) {
            p->add_msg_if_player( m_bad,
                                  _( "The lock stumps your efforts to pick it, and you destroy your tool." ) );
            destroy = true;
        } else {
            p->add_msg_if_player( m_bad,
                                  _( "The lock stumps your efforts to pick it, and you damage your tool." ) );
        }
    } else {
        p->add_msg_if_player( m_bad, _( "The lock stumps your efforts to pick it." ) );
    }
    if( ter_type == t_door_locked_alarm && ( lock_roll + dice( 1, 30 ) ) > pick_roll ) {
        sounds::sound( p->pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), true, "environment",
                       "alarm" );
        if( !g->timed_events.queued( TIMED_EVENT_WANTED ) ) {
            g->timed_events.add( TIMED_EVENT_WANTED, calendar::turn + 30_minutes, 0,
                                 p->global_sm_location() );
        }
    }
    if( destroy ) {
        p->i_rem( it );
    }
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), sounds::alarm, item::damage(), debugmsg, Character::dex_cur, dice(), f_gunsafe_ml, f_null, g, item_location::get_item(), get_lockpicking_open_result(), item::get_quality(), Character::get_skill_level(), Character::global_sm_location(), Character::i_rem(), item::inc_damage(), m_bad, m_good, lockpicking_open_result::new_furn_type, lockpicking_open_result::new_ter_type, lockpicking_open_result::open_message, Character::pos(), qual_LOCKPICK, rng(), skill_mechanics, sounds::sound(), t_door_locked_alarm, t_null, TIMED_EVENT_WANTED, and calendar::turn.
longsalvage_finish()
void activity_handlers::longsalvage_finish (player_activity * act, player * p)
Definition at line 1825 of file activity_handlers.cpp.
{
    static const std::string salvage_string = "salvage";
    item &main_tool = p->i_at( act->index );
    map &here = get_map();
    map_stack items = here.i_at( p->pos() );
    item *salvage_tool = main_tool.get_usable_item( salvage_string );
    if( salvage_tool == nullptr ) {
        debugmsg( "Lost tool used for long salvage" );
        act->set_to_null();
        return;
    }
    const use_function *use_fun = salvage_tool->get_use( salvage_string );
    const salvage_actor *actor = dynamic_cast<const salvage_actor *>( use_fun->get_actor_ptr() );
    if( actor == nullptr ) {
        debugmsg( "iuse_actor type descriptor and actual type mismatch" );
        act->set_to_null();
        return;
    }
    for( item &it : items ) {
        if( actor->valid_to_cut_up( it ) ) {
            item_location item_loc( map_cursor( p->pos() ), &it );
            actor->cut_up( *p, *salvage_tool, item_loc );
            return;
        }
    }
    add_msg( _( "You finish salvaging." ) );
    act->set_to_null();
}
References _, act, add_msg(), salvage_actor::cut_up(), debugmsg, use_function::get_actor_ptr(), get_map(), item::get_usable_item(), item::get_use(), map::i_at(), Character::i_at(), Character::pos(), and salvage_actor::valid_to_cut_up().
make_zlave_finish()
void activity_handlers::make_zlave_finish (player_activity * act, player * p)
Definition at line 1858 of file activity_handlers.cpp.
{
    act->set_to_null();
    map_stack items = g->m.i_at( p->pos() );
    const std::string corpse_name = act->str_values[0];
    item *body = nullptr;
    for( item &it : items ) {
        if( it.display_name() == corpse_name ) {
            body = &it;
        }
    }
    if( body == nullptr ) {
        add_msg( m_info, _( "There's no corpse to make into a zombie slave!" ) );
        return;
    }
    int success = act->values[0];
    if( success > 0 ) {
        p->practice( skill_firstaid, rng( 2, 5 ) );
        p->practice( skill_survival, rng( 2, 5 ) );
        p->add_msg_if_player( m_good,
                              _( "You slice muscles and tendons, and remove body parts until you're confident the zombie won't be able to attack you when it reanimates." ) );
        body->set_var( "zlave", "zlave" );
        //take into account the chance that the body yet can regenerate not as we need.
        if( one_in( 10 ) ) {
            body->set_var( "zlave", "mutilated" );
        }
    } else if( success > -20 ) {
        p->practice( skill_firstaid, rng( 3, 6 ) );
        p->practice( skill_survival, rng( 3, 6 ) );
        p->add_msg_if_player( m_warning,
                              _( "You hack into the corpse and chop off some body parts.  You think the zombie won't be able to attack when it reanimates." ) );
        success += rng( 1, 20 );
        if( success > 0 && !one_in( 5 ) ) {
            body->set_var( "zlave", "zlave" );
        } else {
            body->set_var( "zlave", "mutilated" );
        }
    } else {
        p->practice( skill_firstaid, rng( 1, 8 ) );
        p->practice( skill_survival, rng( 1, 8 ) );
        body->mod_damage( rng( 0, body->max_damage() - body->damage() ), DT_STAB );
        if( body->damage() == body->max_damage() ) {
            body->active = false;
            p->add_msg_if_player( m_warning, _( "You cut up the corpse too much, it is thoroughly pulped." ) );
        } else {
            p->add_msg_if_player( m_warning,
                                  _( "You cut into the corpse trying to make it unable to attack, but you don't think you have it right." ) );
        }
    }
}
References _, act, item::active, add_msg(), player::add_msg_if_player(), item::damage(), DT_STAB, g, m_good, m_info, m_warning, item::max_damage(), item::mod_damage(), one_in(), Character::pos(), player::practice(), rng(), item::set_var(), skill_firstaid, skill_survival, and behavior::success.
meditate_finish()
void activity_handlers::meditate_finish (player_activity * act, player * p)
Definition at line 3125 of file activity_handlers.cpp.
{
    p->add_msg_if_player( m_good, _( "You pause to engage in spiritual contemplation." ) );
    p->add_morale( MORALE_FEELING_GOOD, 5, 10 );
    act->set_to_null();
}
References _, act, Character::add_morale(), player::add_msg_if_player(), m_good, and MORALE_FEELING_GOOD.
mend_item_finish()
void activity_handlers::mend_item_finish (player_activity * act, player * p)
Definition at line 2988 of file activity_handlers.cpp.
{
    act->set_to_null();
    if( act->targets.size() != 1 ) {
        debugmsg( "invalid arguments to ACT_MEND_ITEM" );
        return;
    }
    item_location &target = act->targets[ 0 ];
    const auto f = target->faults.find( fault_id( act->name ) );
    if( f == target->faults.end() ) {
        debugmsg( "item %s does not have fault %s", target->tname(), act->name );
        return;
    }
    if( act->str_values.empty() ) {
        debugmsg( "missing mending_method id for ACT_MEND_ITEM." );
        return;
    }
    const mending_method *method = fault_id( act->name )->find_mending_method( act->str_values[0] );
    if( !method ) {
        debugmsg( "invalid mending_method id for ACT_MEND_ITEM." );
        return;
    }
    const inventory inv = p->crafting_inventory();
    const requirement_data &reqs = method->requirements.obj();
    if( !reqs.can_make_with_inventory( inv, is_crafting_component ) ) {
        add_msg( m_info, _( "You are currently unable to mend the %s." ), target->tname() );
    }
    for( const auto &e : reqs.get_components() ) {
        p->consume_items( e );
    }
    for( const auto &e : reqs.get_tools() ) {
        p->consume_tools( e );
    }
    p->invalidate_crafting_inventory();
    target->faults.erase( *f );
    if( method->turns_into ) {
        target->faults.emplace( *method->turns_into );
    }
    // also_mends removes not just the fault picked to be mended, but this as well.
    if( method->also_mends ) {
        target->faults.erase( *method->also_mends );
    }
    if( act->name == "fault_gun_blackpowder" || act->name == "fault_gun_dirt" ) {
        target->set_var( "dirt", 0 );
    }
    add_msg( m_good, method->success_msg.translated(), target->tname() );
}
References _, act, add_msg(), mending_method::also_mends, requirement_data::can_make_with_inventory(), player::consume_items(), player::consume_tools(), Character::crafting_inventory(), debugmsg, item::faults, fault::find_mending_method(), requirement_data::get_components(), requirement_data::get_tools(), Character::invalidate_crafting_inventory(), is_crafting_component(), m_good, m_info, string_id< T >::obj(), mending_method::requirements, item::set_var(), mending_method::success_msg, item::tname(), translation::translated(), and mending_method::turns_into.
milk_finish()
void activity_handlers::milk_finish (player_activity * act, player * p)
Definition at line 1456 of file activity_handlers.cpp.
{
    if( act->coords.empty() ) {
        debugmsg( "milking activity with no position of monster stored" );
        return;
    }
    map &here = get_map();
    const tripoint source_pos = here.getlocal( act->coords.at( 0 ) );
    monster *source_mon = g->critter_at<monster>( source_pos );
    if( source_mon == nullptr ) {
        debugmsg( "could not find source creature for liquid transfer" );
        return;
    }
    auto milked_item = source_mon->ammo.find( source_mon->type->starting_ammo.begin()->first );
    if( milked_item == source_mon->ammo.end() ) {
        debugmsg( "animal has no milkable ammo type" );
        return;
    }
    if( milked_item->second <= 0 ) {
        debugmsg( "started milking but udders are now empty before milking finishes" );
        return;
    }
    item milk( milked_item->first, calendar::turn, milked_item->second );
    if( liquid_handler::handle_liquid( milk, nullptr, 1, nullptr, nullptr, -1, source_mon ) ) {
        milked_item->second = 0;
        if( milk.charges > 0 ) {
            milked_item->second = milk.charges;
        } else {
            p->add_msg_if_player( _( "The %s's udders run dry." ), source_mon->get_name() );
        }
    }
    // if the monster was not manually tied up, but needed to be fixed in place temporarily then
    // remove that now.
    if( !act->str_values.empty() && act->str_values[0] == "temp_tie" ) {
        source_mon->remove_effect( effect_tied );
    }
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), monster::ammo, item::charges, debugmsg, effect_tied, g, get_map(), monster::get_name(), map::getlocal(), liquid_handler::handle_liquid(), Creature::remove_effect(), mtype::starting_ammo, calendar::turn, and monster::type.
mind_splicer_finish()
void activity_handlers::mind_splicer_finish (player_activity * act, player * p)
Definition at line 4821 of file activity_handlers.cpp.
{
    act->set_to_null();
    if( act->targets.size() != 1 || !act->targets[0] ) {
        debugmsg( "Incompatible arguments to: activity_handlers::mind_splicer_finish" );
        return;
    }
    item &data_card = *act->targets[0];
    p->add_msg_if_player( m_info, _( "you finally find the memory banks." ) );
    p->add_msg_if_player( m_info, _( "The kit makes a copy of the data inside the bionic." ) );
    data_card.contents.clear_items();
    data_card.put_in( item( itype_mind_scan_robofac ) );
}
References _, act, player::add_msg_if_player(), item_contents::clear_items(), item::contents, debugmsg, itype_mind_scan_robofac, m_info, and item::put_in().
move_items_do_turn()
void activity_handlers::move_items_do_turn (player_activity * act, player * p)
move_loot_do_turn()
void activity_handlers::move_loot_do_turn (player_activity * act, player * p)
Definition at line 3158 of file activity_handlers.cpp.
{
    activity_on_turn_move_loot( *act, *p );
}
References act, and activity_on_turn_move_loot().
multiple_butcher_do_turn()
void activity_handlers::multiple_butcher_do_turn (player_activity * act, player * p)
Definition at line 3859 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
multiple_chop_planks_do_turn()
void activity_handlers::multiple_chop_planks_do_turn (player_activity * act, player * p)
Definition at line 3854 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
multiple_construction_do_turn()
void activity_handlers::multiple_construction_do_turn (player_activity * act, player * p)
Definition at line 3844 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
multiple_farm_do_turn()
void activity_handlers::multiple_farm_do_turn (player_activity * act, player * p)
Definition at line 3879 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
multiple_fish_do_turn()
void activity_handlers::multiple_fish_do_turn (player_activity * act, player * p)
Definition at line 3839 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
multiple_mine_do_turn()
void activity_handlers::multiple_mine_do_turn (player_activity * act, player * p)
Definition at line 3849 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
operation_do_turn()
void activity_handlers::operation_do_turn (player_activity * act, player * p)
values[0]: Difficulty
values[1]: success
values[2]: max_power_level
values[3]: pl_skill
str_values[0]: install/uninstall
str_values[1]: bionic_id
str_values[2]: installer_name
str_values[3]: bool autodoc
Definition at line 3520 of file activity_handlers.cpp.
{
    /**
    - values[0]: Difficulty
    - values[1]: success
    - values[2]: max_power_level
    - values[3]: pl_skill
    - str_values[0]: install/uninstall
    - str_values[1]: bionic_id
    - str_values[2]: installer_name
    - str_values[3]: bool autodoc
    */
    enum operation_values_ids {
        operation_type = 0,
        cbm_id = 1,
        installer_name = 2,
        is_autodoc = 3
    };
    const bionic_id bid( act->str_values[cbm_id] );
    const bionic_id upbid = bid->upgraded_bionic;
    const bool autodoc = act->str_values[is_autodoc] == "true";
    const bool u_see = g->u.sees( p->pos() ) && ( !g->u.has_effect( effect_narcosis ) ||
                       g->u.has_bionic( bio_painkiller ) || g->u.has_trait( trait_NOPAIN ) );
    const int difficulty = act->values.front();
    const std::vector<bodypart_id> bps = get_occupied_bodyparts( bid );
    const time_duration half_op_duration = difficulty * 10_minutes;
    const time_duration message_freq = difficulty * 2_minutes;
    time_duration time_left = time_duration::from_turns( act->moves_left / 100 );
    map &here = get_map();
    if( autodoc && here.inbounds( p->pos() ) ) {
        const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( p->pos(), 1,
                                             flag_AUTODOC );
        if( !here.has_flag_furn( flag_AUTODOC_COUCH, p->pos() ) || autodocs.empty() ) {
            p->remove_effect( effect_under_op );
            act->set_to_null();
            if( u_see ) {
                add_msg( m_bad, _( "The autodoc suffers a catastrophic failure." ) );
                p->add_msg_player_or_npc( m_bad,
                                          _( "The Autodoc's failure damages you greatly." ),
                                          _( "The Autodoc's failure damages <npcname> greatly." ) );
            }
            if( !bps.empty() ) {
                for( const bodypart_id &bp : bps ) {
                    p->add_effect( effect_bleed, 1_hours, bp->token, difficulty );
                    p->apply_damage( nullptr, bp, 20 * difficulty );
                    if( u_see ) {
                        p->add_msg_player_or_npc( m_bad, _( "Your %s is ripped open." ),
                                                  _( "<npcname>'s %s is ripped open." ), body_part_name_accusative( bp->token ) );
                    }
                    if( bp == bodypart_id( "eyes" ) ) {
                        p->add_effect( effect_blind, 1_hours, num_bp );
                    }
                }
            } else {
                p->add_effect( effect_bleed, 1_hours, num_bp, difficulty );
                p->apply_damage( nullptr, bodypart_id( "torso" ), 20 * difficulty );
            }
        }
    }
    if( time_left > half_op_duration ) {
        if( !bps.empty() ) {
            for( const bodypart_id &bp : bps ) {
                if( calendar::once_every( message_freq ) && u_see && autodoc ) {
                    p->add_msg_player_or_npc( m_info,
                                              _( "The Autodoc is meticulously cutting your %s open." ),
                                              _( "The Autodoc is meticulously cutting <npcname>'s %s open." ),
                                              body_part_name_accusative( bp->token ) );
                }
            }
        } else {
            if( calendar::once_every( message_freq ) && u_see ) {
                p->add_msg_player_or_npc( m_info,
                                          _( "The Autodoc is meticulously cutting you open." ),
                                          _( "The Autodoc is meticulously cutting <npcname> open." ) );
            }
        }
    } else if( time_left == half_op_duration ) {
        if( act->str_values[operation_type] == "uninstall" ) {
            if( u_see && autodoc ) {
                add_msg( m_info, _( "The Autodoc attempts to carefully extract the bionic." ) );
            }
            if( p->has_bionic( bid ) ) {
                p->perform_uninstall( bid, act->values[0], act->values[1],
                                      units::from_joule( act->values[2] ), act->values[3] );
            } else {
                debugmsg( _( "Tried to uninstall %s, but you don't have this bionic installed." ), bid.c_str() );
                p->remove_effect( effect_under_op );
                act->set_to_null();
            }
        } else {
            if( u_see && autodoc ) {
                add_msg( m_info, _( "The Autodoc attempts to carefully insert the bionic." ) );
            }
            if( bid.is_valid() ) {
                p->perform_install( bid, upbid, act->values[0], act->values[1], act->values[3],
                                    act->str_values[installer_name], bid->canceled_mutations );
            } else {
                debugmsg( _( "%s is no a valid bionic_id" ), bid.c_str() );
                p->remove_effect( effect_under_op );
                act->set_to_null();
            }
        }
    } else if( act->values[1] > 0 ) {
        if( !bps.empty() ) {
            for( const bodypart_id &bp : bps ) {
                if( calendar::once_every( message_freq ) && u_see && autodoc ) {
                    p->add_msg_player_or_npc( m_info,
                                              _( "The Autodoc is stitching your %s back up." ),
                                              _( "The Autodoc is stitching <npcname>'s %s back up." ),
                                              body_part_name_accusative( bp->token ) );
                }
            }
        } else {
            if( calendar::once_every( message_freq ) && u_see && autodoc ) {
                p->add_msg_player_or_npc( m_info,
                                          _( "The Autodoc is stitching you back up." ),
                                          _( "The Autodoc is stitching <npcname> back up." ) );
            }
        }
    } else {
        if( calendar::once_every( message_freq ) && u_see && autodoc ) {
            p->add_msg_player_or_npc( m_bad,
                                      _( "The Autodoc is moving erratically through the rest of its program, not actually stitching your wounds." ),
                                      _( "The Autodoc is moving erratically through the rest of its program, not actually stitching <npcname>'s wounds." ) );
        }
    }
    // Makes sure NPC is still under anesthesia
    if( p->has_effect( effect_narcosis ) ) {
        const time_duration remaining_time = p->get_effect_dur( effect_narcosis );
        if( remaining_time <= time_left ) {
            const time_duration top_off_time = time_left - remaining_time;
            p->add_effect( effect_narcosis, top_off_time );
            p->add_effect( effect_sleep, top_off_time );
        }
    } else {
        p->add_effect( effect_narcosis, time_left );
        p->add_effect( effect_sleep, time_left );
    }
}
References _, act, Creature::add_effect(), add_msg(), player::add_msg_player_or_npc(), Character::apply_damage(), iexamine::autodoc(), bio_painkiller, body_part_name_accusative(), string_id< T >::c_str(), bionic_data::canceled_mutations, debugmsg, effect_bleed, effect_blind, effect_narcosis, effect_sleep, effect_under_op, map::find_furnitures_with_flag_in_radius(), flag_AUTODOC(), flag_AUTODOC_COUCH(), units::from_joule(), time_duration::from_turns(), g, Creature::get_effect_dur(), get_map(), get_occupied_bodyparts(), Character::has_bionic(), Creature::has_effect(), map::has_flag_furn(), map::inbounds(), string_id< T >::is_valid(), m_bad, m_info, num_bp, calendar::once_every(), Character::perform_install(), Character::perform_uninstall(), Character::pos(), Creature::remove_effect(), trait_NOPAIN, and bionic_data::upgraded_bionic.
operation_finish()
void activity_handlers::operation_finish (player_activity * act, player * p)
Definition at line 3681 of file activity_handlers.cpp.
{
    map &here = get_map();
    if( act->str_values[3] == "true" ) {
        if( act->values[1] > 0 ) {
            add_msg( m_good,
                     _( "The Autodoc returns to its resting position after successfully performing the operation." ) );
            const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( p->pos(), 1,
                                                 flag_AUTODOC );
            sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
                           _( "a short upbeat jingle: \"Operation successful\"" ), true,
                           "Autodoc",
                           "success" );
        } else {
            if( act->str_values[0] == "install" ) {
                add_msg( m_warning,
                         _( "The Autodoc completes installation and activates bionic but reports about complications during operation." ) );
                const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( p->pos(), 1,
                                                     flag_AUTODOC );
                sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
                               _( "a sad beeping noise: \"Complications detected!  Report to medical personnel immediately!\"" ),
                               true,
                               "Autodoc",
                               "failure" );
            } else {
                add_msg( m_bad,
                         _( "The Autodoc jerks back to its resting position after failing the operation." ) );
                const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( p->pos(), 1,
                                                     flag_AUTODOC );
                sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
                               _( "a sad beeping noise: \"Operation failed\"" ), true,
                               "Autodoc",
                               "failure" );
            }
        }
    } else {
        if( act->values[1] > 0 ) {
            add_msg( m_good,
                     _( "The operation is a success." ) );
        } else {
            if( act->str_values[0] == "install" ) {
                add_msg( m_warning,
                         _( "Bionic was installed and activated but a complication happened during operation!" ) );
            } else {
                add_msg( m_bad,
                         _( "The operation is a failure." ) );
            }
        }
    }
    p->remove_effect( effect_under_op );
    act->set_to_null();
}
References _, act, add_msg(), effect_under_op, map::find_furnitures_with_flag_in_radius(), flag_AUTODOC(), get_map(), m_bad, m_good, m_warning, sounds::music, Character::pos(), Creature::remove_effect(), and sounds::sound().
oxytorch_do_turn()
void activity_handlers::oxytorch_do_turn (player_activity * act, player * p)
Definition at line 2441 of file activity_handlers.cpp.
{
    if( act->values[0] <= 0 ) {
        return;
    }
    item &it = *act->targets.front();
    // act->values[0] is the number of charges yet to be consumed
    const int charges_used = std::min( act->values[0], it.ammo_required() );
    it.ammo_consume( charges_used, p->pos() );
    act->values[0] -= static_cast<int>( charges_used );
    sfx::play_activity_sound( "tool", "oxytorch", sfx::get_heard_volume( act->placement ) );
    if( calendar::once_every( 2_turns ) ) {
        sounds::sound( act->placement, 10, sounds::sound_t::destructive_activity, _( "hissssssssss!" ) );
    }
}
References _, act, item::ammo_consume(), item::ammo_required(), sounds::destructive_activity, sfx::get_heard_volume(), calendar::once_every(), sfx::play_activity_sound(), Character::pos(), and sounds::sound().
oxytorch_finish()
void activity_handlers::oxytorch_finish (player_activity * act, player * p)
Definition at line 2460 of file activity_handlers.cpp.
{
    act->set_to_null();
    map &here = get_map();
    const tripoint &pos = act->placement;
    const ter_id ter = here.ter( pos );
    // fast players might still have some charges left to be consumed
    act->targets.front()->ammo_consume( act->values[0], p->pos() );
    if( here.furn( pos ) == f_rack ) {
        here.furn_set( pos, f_null );
        here.spawn_item( p->pos(), itype_steel_chunk, rng( 2, 6 ) );
    } else if( ter == t_chainfence || ter == t_chaingate_c || ter == t_chaingate_l ) {
        here.ter_set( pos, t_dirt );
        here.spawn_item( pos, itype_pipe, rng( 1, 4 ) );
        here.spawn_item( pos, itype_wire, rng( 4, 16 ) );
    } else if( ter == t_chainfence_posts ) {
        here.ter_set( pos, t_dirt );
        here.spawn_item( pos, itype_pipe, rng( 1, 4 ) );
    } else if( ter == t_door_metal_locked || ter == t_door_metal_c || ter == t_door_bar_c ||
               ter == t_door_bar_locked || ter == t_door_metal_pickable ) {
        here.ter_set( pos, t_mdoor_frame );
        here.spawn_item( pos, itype_steel_plate, rng( 0, 1 ) );
        here.spawn_item( pos, itype_steel_chunk, rng( 3, 8 ) );
    } else if( ter == t_window_enhanced || ter == t_window_enhanced_noglass ) {
        here.ter_set( pos, t_window_empty );
        here.spawn_item( pos, itype_steel_plate, rng( 0, 1 ) );
        here.spawn_item( pos, itype_sheet_metal, rng( 1, 3 ) );
    } else if( ter == t_reb_cage ) {
        here.ter_set( pos, t_pit );
        here.spawn_item( pos, itype_spike, rng( 1, 19 ) );
        here.spawn_item( pos, itype_scrap, rng( 1, 8 ) );
    } else if( ter == t_bars ) {
        if( here.ter( pos + point_east ) == t_sewage || here.ter( pos + point_south ) ==
            t_sewage ||
            here.ter( pos + point_west ) == t_sewage || here.ter( pos + point_north ) ==
            t_sewage ) {
            here.ter_set( pos, t_sewage );
            here.spawn_item( p->pos(), itype_pipe, rng( 1, 2 ) );
        } else {
            here.ter_set( pos, t_floor );
            here.spawn_item( p->pos(), itype_pipe, rng( 1, 2 ) );
        }
    } else if( ter == t_window_bars_alarm ) {
        here.ter_set( pos, t_window_alarm );
        here.spawn_item( p->pos(), itype_pipe, rng( 1, 2 ) );
    } else if( ter == t_window_bars ) {
        here.ter_set( pos, t_window_empty );
        here.spawn_item( p->pos(), itype_pipe, rng( 1, 2 ) );
    }
}
References act, f_null, f_rack, map::furn(), map::furn_set(), get_map(), itype_pipe, itype_scrap, itype_sheet_metal, itype_spike, itype_steel_chunk, itype_steel_plate, itype_wire, point_east, point_north, point_south, point_west, Character::pos(), rng(), map::spawn_item(), t_bars, t_chainfence, t_chainfence_posts, t_chaingate_c, t_chaingate_l, t_dirt, t_door_bar_c, t_door_bar_locked, t_door_metal_c, t_door_metal_locked, t_door_metal_pickable, t_floor, t_mdoor_frame, t_pit, t_reb_cage, t_sewage, t_window_alarm, t_window_bars, t_window_bars_alarm, t_window_empty, t_window_enhanced, t_window_enhanced_noglass, map::ter(), and map::ter_set().
pickaxe_do_turn()
void activity_handlers::pickaxe_do_turn (player_activity * act, player * p)
Definition at line 1924 of file activity_handlers.cpp.
{
    const tripoint &pos = get_map().getlocal( act->placement );
    sfx::play_activity_sound( "tool", "pickaxe", sfx::get_heard_volume( pos ) );
    // each turn is too much
    if( calendar::once_every( 1_minutes ) ) {
        //~ Sound of a Pickaxe at work!
        sounds::sound( pos, 30, sounds::sound_t::destructive_activity, _( "CHNK!  CHNK!  CHNK!" ) );
    }
}
References _, act, sounds::destructive_activity, sfx::get_heard_volume(), get_map(), map::getlocal(), calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
pickaxe_finish()
void activity_handlers::pickaxe_finish (player_activity * act, player * p)
Definition at line 1935 of file activity_handlers.cpp.
{
    map &here = get_map();
    const tripoint pos( here.getlocal( act->placement ) );
    // Invalidate the activity early to prevent a query from mod_pain()
    act->set_to_null();
    if( p->is_avatar() ) {
        const int helpersize = g->u.get_crafting_helpers( 3 ).size();
        if( here.is_bashable( pos ) && here.has_flag( flag_SUPPORTS_ROOF, pos ) &&
            here.ter( pos ) != t_tree ) {
            // Tunneling through solid rock is hungry, sweaty, tiring, backbreaking work
            // Betcha wish you'd opted for the J-Hammer ;P
            p->mod_stored_nutr( 15 - ( helpersize * 3 ) );
            p->mod_thirst( 15 - ( helpersize * 3 ) );
            if( p->has_trait( trait_STOCKY_TROGLO ) ) {
                // Yep, dwarves can dig longer before tiring
                p->mod_fatigue( 20 - ( helpersize  * 3 ) );
            } else {
                p->mod_fatigue( 30 - ( helpersize  * 3 ) );
            }
            p->mod_pain( std::max( 0, ( 2 * static_cast<int>( rng( 1, 3 ) ) ) - helpersize ) );
        } else if( here.move_cost( pos ) == 2 && g->get_levz() == 0 &&
                   here.ter( pos ) != t_dirt && here.ter( pos ) != t_grass ) {
            //Breaking up concrete on the surface? not nearly as bad
            p->mod_stored_nutr( 5 - ( helpersize ) );
            p->mod_thirst( 5 - ( helpersize ) );
            p->mod_fatigue( 10 - ( helpersize  * 2 ) );
        }
    }
    p->add_msg_player_or_npc( m_good,
                              _( "You finish digging." ),
                              _( "<npcname> finishes digging." ) );
    here.destroy( pos, true );
    if( !act->targets.empty() ) {
        item &it = *act->targets.front();
        p->consume_charges( it, it.ammo_required() );
    } else {
        debugmsg( "pickaxe activity targets empty" );
    }
    if( resume_for_multi_activities( *p ) ) {
        for( item &elem : here.i_at( pos ) ) {
            elem.set_var( "activity_var", p->name );
        }
    }
}
References _, act, player::add_msg_player_or_npc(), item::ammo_required(), Character::consume_charges(), debugmsg, map::destroy(), flag_SUPPORTS_ROOF(), g, get_map(), map::getlocal(), map::has_flag(), Character::has_trait(), map::i_at(), Creature::is_avatar(), map::is_bashable(), m_good, Character::mod_fatigue(), player::mod_pain(), Character::mod_stored_nutr(), Character::mod_thirst(), map::move_cost(), Character::name, resume_for_multi_activities(), rng(), t_dirt, t_grass, t_tree, map::ter(), and trait_STOCKY_TROGLO.
plant_seed_finish()
void activity_handlers::plant_seed_finish (player_activity * act, player * p)
Definition at line 3747 of file activity_handlers.cpp.
{
    map &here = get_map();
    tripoint examp = here.getlocal( act->placement );
    const itype_id seed_id( act->str_values[0] );
    std::list<item> used_seed;
    if( item::count_by_charges( seed_id ) ) {
        used_seed = p->use_charges( seed_id, 1 );
    } else {
        used_seed = p->use_amount( seed_id, 1 );
    }
    if( !used_seed.empty() ) {
        used_seed.front().set_age( 0_turns );
        if( used_seed.front().has_var( "activity_var" ) ) {
            used_seed.front().erase_var( "activity_var" );
        }
        used_seed.front().set_flag( flag_HIDDEN_ITEM );
        here.add_item_or_charges( examp, used_seed.front() );
        if( here.has_flag_furn( flag_PLANTABLE, examp ) ) {
            here.furn_set( examp, furn_str_id( here.furn( examp )->plant->transform ) );
        } else {
            here.set( examp, t_dirt, f_plant_seed );
        }
        p->add_msg_player_or_npc( _( "You plant some %s." ), _( "<npcname> plants some %s." ),
                                  item::nname( seed_id ) );
    }
    // Go back to what we were doing before
    // could be player zone activity, or could be NPC multi-farming
    act->set_to_null();
    resume_for_multi_activities( *p );
}
References _, act, map::add_item_or_charges(), player::add_msg_player_or_npc(), item::count_by_charges(), f_plant_seed, flag_HIDDEN_ITEM(), flag_PLANTABLE(), map::furn(), map::furn_set(), get_map(), map::getlocal(), map::has_flag_furn(), item::nname(), furn_t::plant, resume_for_multi_activities(), map::set(), t_dirt, Character::use_amount(), and Character::use_charges().
play_with_pet_finish()
void activity_handlers::play_with_pet_finish (player_activity * act, player * p)
Definition at line 4349 of file activity_handlers.cpp.
{
    p->add_morale( MORALE_PLAY_WITH_PET, rng( 3, 10 ), 10, 5_hours, 25_minutes );
    p->add_msg_if_player( m_good, _( "Playing with your %s has lifted your spirits a bit." ),
                          act->str_values[0] );
    act->set_to_null();
}
References _, act, Character::add_morale(), player::add_msg_if_player(), m_good, MORALE_PLAY_WITH_PET, and rng().
pry_nails_do_turn()
void activity_handlers::pry_nails_do_turn (player_activity * act, player * p)
Definition at line 4081 of file activity_handlers.cpp.
{
    sfx::play_activity_sound( "tool", "hammer", sfx::get_heard_volume( act->placement ) );
}
References act, sfx::get_heard_volume(), and sfx::play_activity_sound().
pry_nails_finish()
void activity_handlers::pry_nails_finish (player_activity * act, player * p)
Definition at line 4086 of file activity_handlers.cpp.
{
    const tripoint &pnt = act->placement;
    map &here = get_map();
    const ter_id type = here.ter( pnt );
    int nails = 0;
    int boards = 0;
    ter_id newter;
    if( type == t_fence ) {
        nails = 6;
        boards = 3;
        newter = t_fence_post;
        p->add_msg_if_player( _( "You pry out the fence post." ) );
    } else if( type == t_window_boarded ) {
        nails = 8;
        boards = 4;
        newter = t_window_frame;
        p->add_msg_if_player( _( "You pry the boards from the window." ) );
    } else if( type == t_window_boarded_noglass ) {
        nails = 8;
        boards = 4;
        newter = t_window_empty;
        p->add_msg_if_player( _( "You pry the boards from the window frame." ) );
    } else if( type == t_door_boarded || type == t_door_boarded_damaged ||
               type == t_rdoor_boarded || type == t_rdoor_boarded_damaged ||
               type == t_door_boarded_peep || type == t_door_boarded_damaged_peep ) {
        nails = 8;
        boards = 4;
        if( type == t_door_boarded ) {
            newter = t_door_c;
        } else if( type == t_door_boarded_damaged ) {
            newter = t_door_b;
        } else if( type == t_door_boarded_peep ) {
            newter = t_door_c_peep;
        } else if( type == t_door_boarded_damaged_peep ) {
            newter = t_door_b_peep;
        } else if( type == t_rdoor_boarded ) {
            newter = t_rdoor_c;
        } else { // if (type == t_rdoor_boarded_damaged)
            newter = t_rdoor_b;
        }
        p->add_msg_if_player( _( "You pry the boards from the door." ) );
    }
    p->practice( skill_fabrication, 1, 1 );
    here.spawn_item( p->pos(), itype_nail, 0, nails );
    here.spawn_item( p->pos(), itype_2x4, boards );
    here.ter_set( pnt, newter );
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), get_map(), itype_2x4, itype_nail, Character::pos(), player::practice(), skill_fabrication, map::spawn_item(), t_door_b, t_door_b_peep, t_door_boarded, t_door_boarded_damaged, t_door_boarded_damaged_peep, t_door_boarded_peep, t_door_c, t_door_c_peep, t_fence, t_fence_post, t_rdoor_b, t_rdoor_boarded, t_rdoor_boarded_damaged, t_rdoor_c, t_window_boarded, t_window_boarded_noglass, t_window_empty, t_window_frame, map::ter(), map::ter_set(), and type.
pulp_do_turn()
void activity_handlers::pulp_do_turn (player_activity * act, player * p)
Strength increases pulping power, with diminishing returns
Definition at line 1981 of file activity_handlers.cpp.
{
    map &here = get_map();
    const tripoint &pos = here.getlocal( act->placement );
    // Stabbing weapons are a lot less effective at pulping
    const int cut_power = std::max( p->weapon.damage_melee( DT_CUT ),
                                    p->weapon.damage_melee( DT_STAB ) / 2 );
    ///\EFFECT_STR increases pulping power, with diminishing returns
    float pulp_power = std::sqrt( ( p->str_cur + p->weapon.damage_melee( DT_BASH ) ) *
                                  ( cut_power + 1.0f ) );
    float pulp_effort = p->str_cur + p->weapon.damage_melee( DT_BASH );
    // Multiplier to get the chance right + some bonus for survival skill
    pulp_power *= 40 + p->get_skill_level( skill_survival ) * 5;
    const int mess_radius = p->weapon.has_flag( flag_MESSY ) ? 2 : 1;
    int moves = 0;
    // use this to collect how many corpse are pulped
    int &num_corpses = act->index;
    map_stack corpse_pile = here.i_at( pos );
    for( item &corpse : corpse_pile ) {
        const mtype *corpse_mtype = corpse.get_mtype();
        if( !corpse.is_corpse() || !corpse_mtype->has_flag( MF_REVIVES ) ||
            ( std::find( act->str_values.begin(), act->str_values.end(), "auto_pulp_no_acid" ) !=
              act->str_values.end() && corpse_mtype->bloodType().obj().has_acid ) ) {
            // Don't smash non-rezing corpses //don't smash acid zombies when auto pulping
            continue;
        }
        while( corpse.damage() < corpse.max_damage() ) {
            // Increase damage as we keep smashing ensuring we eventually smash the target.
            if( x_in_y( pulp_power, corpse.volume() / units::legacy_volume_factor ) ) {
                corpse.inc_damage( DT_BASH );
                if( corpse.damage() == corpse.max_damage() ) {
                    num_corpses++;
                }
            }
            if( x_in_y( pulp_power, corpse.volume() / units::legacy_volume_factor ) ) {
                // Splatter some blood around
                // Splatter a bit more randomly, so that it looks cooler
                const int radius = mess_radius + x_in_y( pulp_power, 500 ) + x_in_y( pulp_power, 1000 );
                const tripoint dest( pos + point( rng( -radius, radius ), rng( -radius, radius ) ) );
                const field_type_id type_blood = ( mess_radius > 1 && x_in_y( pulp_power, 10000 ) ) ?
                                                 corpse.get_mtype()->gibType() :
                                                 corpse.get_mtype()->bloodType();
                here.add_splatter_trail( type_blood, pos, dest );
            }
            p->mod_stamina( -pulp_effort );
            if( one_in( 4 ) ) {
                // Smashing may not be butchery, but it involves some zombie anatomy
                p->practice( skill_survival, 2, 2 );
            }
            float stamina_ratio = static_cast<float>( p->get_stamina() ) / p->get_stamina_max();
            moves += 100 / std::max( 0.25f, stamina_ratio );
            if( stamina_ratio < 0.33 || p->is_npc() ) {
                p->moves = std::min( 0, p->moves - moves );
                return;
            }
            if( moves >= p->moves ) {
                // Enough for this turn;
                p->moves -= moves;
                return;
            }
        }
        corpse.set_flag( flag_PULPED );
    }
    // If we reach this, all corpses have been pulped, finish the activity
    act->moves_left = 0;
    if( num_corpses == 0 ) {
        p->add_msg_if_player( m_bad, _( "The corpse moved before you could finish smashing it!" ) );
        return;
    }
    // TODO: Factor in how long it took to do the smashing.
    p->add_msg_player_or_npc( vgettext( "The corpse is thoroughly pulped.",
                                        "The corpses are thoroughly pulped.", num_corpses ),
                              vgettext( "<npcname> finished pulping the corpse.",
                                        "<npcname> finished pulping the corpses.", num_corpses ) );
}
References _, act, player::add_msg_if_player(), player::add_msg_player_or_npc(), map::add_splatter_trail(), mtype::bloodType(), corpse, item::damage_melee(), DT_BASH, DT_CUT, DT_STAB, detail::find(), flag_MESSY(), flag_PULPED(), get_map(), Character::get_skill_level(), Character::get_stamina(), Character::get_stamina_max(), map::getlocal(), field_type::has_acid, item::has_flag(), mtype::has_flag(), map::i_at(), units::legacy_volume_factor, m_bad, MF_REVIVES, Character::mod_stamina(), Creature::moves, int_id< T >::obj(), one_in(), player::practice(), rng(), skill_survival, Character::str_cur, vgettext(), Character::weapon, and x_in_y().
pulp_finish()
void activity_handlers::pulp_finish (player_activity * act, player * p)
Definition at line 2066 of file activity_handlers.cpp.
{
    if( p->is_npc() ) {
        npc *guy = dynamic_cast<npc *>( p );
        guy->revert_after_activity();
    } else {
        act->set_to_null();
    }
}
References act, player::is_npc(), and npc::revert_after_activity().
read_do_turn()
void activity_handlers::read_do_turn (player_activity * act, player * p)
Definition at line 3335 of file activity_handlers.cpp.
{
    if( p->is_player() ) {
        if( !act->str_values.empty() && act->str_values[0] == "martial_art" && one_in( 3 ) ) {
            if( act->values.empty() ) {
                act->values.push_back( p->get_stamina() );
            }
            p->set_stamina( act->values[0] - 1 );
            act->values[0] = p->get_stamina();
        }
    } else {
        p->moves = 0;
    }
    if( calendar::once_every( 1_minutes ) ) {
        item_location loc = act->targets[0];
        if( !loc || !loc->is_book() ) {
            p->add_msg_if_player( m_bad, _( "You lost your book!  You stop reading." ) );
            act->set_to_null();
        }
    }
}
References _, act, player::add_msg_if_player(), Character::get_stamina(), item::is_book(), player::is_player(), m_bad, Creature::moves, calendar::once_every(), one_in(), and Character::set_stamina().
read_finish()
void activity_handlers::read_finish (player_activity * act, player * p)
Definition at line 3358 of file activity_handlers.cpp.
{
    if( !act || !act->targets.front() ) {
        debugmsg( "Lost target of ACT_READ" );
        return;
    }
    if( p->is_npc() ) {
        npc *guy = dynamic_cast<npc *>( p );
        guy->finish_read( act->targets.front() );
    } else {
        if( avatar *u = dynamic_cast<avatar *>( p ) ) {
            u->do_read( act->targets.front() );
        } else {
            act->set_to_null();
        }
        if( !act ) {
            p->add_msg_if_player( m_info, _( "You finish reading." ) );
        }
    }
}
References _, act, player::add_msg_if_player(), debugmsg, npc::finish_read(), player::is_npc(), and m_info.
reload_finish()
void activity_handlers::reload_finish (player_activity * act, player * p)
Definition at line 2076 of file activity_handlers.cpp.
{
    act->set_to_null();
    if( act->targets.size() != 2 || act->index <= 0 ) {
        debugmsg( "invalid arguments to ACT_RELOAD" );
        return;
    }
    if( !act->targets[0] ) {
        debugmsg( "reload target is null, failed to reload" );
        return;
    }
    if( !act->targets[1] ) {
        debugmsg( "ammo target is null, failed to reload" );
        return;
    }
    item &reloadable = *act->targets[ 0 ];
    item &ammo = *act->targets[1];
    std::string ammo_name = ammo.tname();
    const int qty = act->index;
    const bool is_speedloader = ammo.has_flag( flag_SPEEDLOADER );
    const bool ammo_is_filthy = ammo.is_filthy();
    if( !reloadable.reload( *p, std::move( act->targets[ 1 ] ), qty ) ) {
        add_msg( m_info, _( "Can't reload the %s." ), reloadable.tname() );
        return;
    }
    std::string msg = _( "You reload the %s." );
    if( ammo_is_filthy ) {
        reloadable.set_flag( "FILTHY" );
    }
    if( reloadable.get_var( "dirt", 0 ) > 7800 ) {
        msg =
            _( "You manage to loosen some debris and make your %s somewhat operational." );
        reloadable.set_var( "dirt", ( reloadable.get_var( "dirt", 0 ) - rng( 790, 2750 ) ) );
    }
    if( reloadable.is_gun() ) {
        p->recoil = MAX_RECOIL;
        if( reloadable.has_flag( flag_RELOAD_ONE ) && !is_speedloader ) {
            for( int i = 0; i != qty; ++i ) {
                msg = _( "You insert one %2$s into the %1$s." );
            }
        }
        if( reloadable.type->gun->reload_noise_volume > 0 ) {
            sfx::play_variant_sound( "reload", reloadable.typeId().str(),
                                     sfx::get_heard_volume( p->pos() ) );
            sounds::ambient_sound( p->pos(), reloadable.type->gun->reload_noise_volume,
                                   sounds::sound_t::activity, reloadable.type->gun->reload_noise );
        }
    } else if( reloadable.is_watertight_container() ) {
        msg = _( "You refill the %s." );
    }
    add_msg( m_neutral, msg, reloadable.tname(), ammo_name );
}
References _, act, sounds::activity, add_msg(), sounds::ambient_sound(), debugmsg, flag_RELOAD_ONE(), flag_SPEEDLOADER(), sfx::get_heard_volume(), item::get_var(), itype::gun, item::has_flag(), item::is_filthy(), item::is_gun(), item::is_watertight_container(), m_info, m_neutral, MAX_RECOIL, avatar_action::move(), sfx::play_variant_sound(), Character::pos(), Character::recoil, item::reload(), rng(), item::set_flag(), item::set_var(), string_id< T >::str(), item::tname(), item::type, and item::typeId().
repair_item_do_turn()
void activity_handlers::repair_item_do_turn (player_activity * act, player * p)
Definition at line 3316 of file activity_handlers.cpp.
{
    // Moves are decremented based on a combination of speed and good vision (not in the dark, farsighted, etc)
    const float vision_mod = character_funcs::fine_detail_vision_mod( *p );
    const int effective_moves = p->moves / vision_mod;
    if( effective_moves <= act->moves_left ) {
        act->moves_left -= effective_moves;
        p->moves = 0;
    } else {
        p->moves -= act->moves_left * vision_mod;
        act->moves_left = 0;
    }
}
References act, character_funcs::fine_detail_vision_mod(), and Creature::moves.
repair_item_finish()
void activity_handlers::repair_item_finish (player_activity * act, player * p)
Definition at line 2804 of file activity_handlers.cpp.
{
    namespace hack = activity_handlers::repair_activity_hack;
    const std::string iuse_name_string = act->get_str_value( 0, "repair_item" );
    repeat_type repeat = static_cast<repeat_type>( act->get_value( 0, REPEAT_INIT ) );
    item_location *ploc = nullptr;
    if( !act->targets.empty() ) {
        ploc = &act->targets[0];
    }
    // nullopt if used real tool
    cata::optional<hack::hack_type_t> hack_type = hack::get_hack_type( *act );
    cata::optional<item> fake_tool = cata::nullopt;
    if( hack_type ) {
        fake_tool = hack::get_fake_tool( hack_type.value(), *act );
    }
    const tripoint hack_position = hack_type ? hack::get_position( *act ) : tripoint{};
    const int hack_original_charges = fake_tool ? fake_tool->charges : 0;
    item *main_tool = nullptr;
    if( hack_type.has_value() ) {
        main_tool = &fake_tool.value();
    }
    if( main_tool == nullptr && ploc ) {
        main_tool = & **ploc;
    }
    if( main_tool == nullptr ) {
        main_tool = &p->i_at( act->index );
    }
    if( main_tool == nullptr ) {
        debugmsg( "Failed to get main_tool for long repair" );
        act->set_to_null();
        return;
    }
    item *used_tool = main_tool->get_usable_item( iuse_name_string );
    if( used_tool == nullptr ) {
        debugmsg( "Lost tool used for long repair" );
        act->set_to_null();
        return;
    }
    const use_function *use_fun = used_tool->get_use( iuse_name_string );
    // TODO: De-uglify this block. Something like get_use<iuse_actor_type>() maybe?
    const repair_item_actor *actor = dynamic_cast<const repair_item_actor *>
                                     ( use_fun->get_actor_ptr() );
    if( actor == nullptr ) {
        debugmsg( "iuse_actor type descriptor and actual type mismatch" );
        act->set_to_null();
        return;
    }
    // Valid Repeat choice and target, attempt repair.
    if( repeat != REPEAT_INIT && act->targets.size() >= 2 ) {
        item_location &fix_location = act->targets[1];
        // Remember our level: we want to stop retrying on level up
        const int old_level = p->get_skill_level( actor->used_skill );
        const repair_item_actor::attempt_hint attempt = actor->repair( *p, *used_tool, fix_location );
        if( attempt != repair_item_actor::AS_CANT ) {
            if( ploc && ploc->where() == item_location::type::map ) {
                used_tool->ammo_consume( used_tool->ammo_required(), ploc->position() );
            } else {
                p->consume_charges( *used_tool, used_tool->ammo_required() );
            }
            if( hack_type.has_value() ) {
                hack::discharge_real_power_source(
                    hack_type.value(),
                    hack_position,
                    *used_tool,
                    hack_original_charges
                );
            }
        }
        // TODO: Allow setting this in the actor
        // TODO: Don't use charges_to_use: welder has 50 charges per use, soldering iron has 1
        if( !used_tool->units_sufficient( *p ) ) {
            p->add_msg_if_player( _( "Your %s ran out of charges" ), used_tool->tname() );
            act->set_to_null();
            return;
        }
        // Print message explaining why we stopped
        // But only if we didn't destroy the item (because then it's obvious)
        const bool destroyed = attempt == repair_item_actor::AS_DESTROYED;
        const bool cannot_continue_repair = attempt == repair_item_actor::AS_CANT ||
                                            destroyed || !actor->can_repair_target( *p, *fix_location, !destroyed );
        if( cannot_continue_repair ) {
            // Cannot continue to repair target, select another target.
            // **Warning**: as soon as the item is popped back, it is destroyed and can't be used anymore!
            act->targets.pop_back();
        }
        const bool event_happened = attempt == repair_item_actor::AS_FAILURE ||
                                    attempt == repair_item_actor::AS_SUCCESS ||
                                    old_level != p->get_skill_level( actor->used_skill );
        const bool need_input =
            ( repeat == REPEAT_ONCE ) ||
            ( repeat == REPEAT_EVENT && event_happened ) ||
            ( repeat == REPEAT_FULL && ( cannot_continue_repair || fix_location->damage() <= 0 ) );
        if( need_input ) {
            repeat = REPEAT_INIT;
        }
    }
    // Check tool is valid before we query target and Repeat choice.
    if( !actor->can_use_tool( *p, *used_tool, true ) ) {
        act->set_to_null();
        return;
    }
    // target selection and validation.
    while( act->targets.size() < 2 ) {
        item_location item_loc = game_menus::inv::repair( *p, actor, main_tool );
        if( item_loc == item_location::nowhere ) {
            p->add_msg_if_player( m_info, _( "Never mind." ) );
            act->set_to_null();
            return;
        }
        if( actor->can_repair_target( *p, *item_loc, true ) ) {
            act->targets.emplace_back( item_loc );
            repeat = REPEAT_INIT;
        }
    }
    const item &fix = *act->targets[1];
    if( repeat == REPEAT_INIT ) {
        const int level = p->get_skill_level( actor->used_skill );
        repair_item_actor::repair_type action_type = actor->default_action( fix, level );
        if( action_type == repair_item_actor::RT_NOTHING ) {
            p->add_msg_if_player( _( "You won't learn anything more by doing that." ) );
        }
        const std::pair<float, float> chance = actor->repair_chance( *p, fix, action_type );
        if( chance.first <= 0.0f ) {
            action_type = repair_item_actor::RT_PRACTICE;
        }
        std::string title = string_format( _( "%s %s\n" ),
                                           repair_item_actor::action_description( action_type ),
                                           fix.tname() );
        title += string_format( _( "Charges: <color_light_blue>%s/%s</color> %s (%s per use)\n" ),
                                used_tool->ammo_remaining(), used_tool->ammo_capacity(),
                                item::nname( used_tool->ammo_current() ),
                                used_tool->ammo_required() );
        title += string_format( _( "Skill used: <color_light_blue>%s (%s)</color>\n" ),
                                actor->used_skill.obj().name(), level );
        title += string_format( _( "Success chance: <color_light_blue>%.1f</color>%%\n" ),
                                100.0f * chance.first );
        title += string_format( _( "Damage chance: <color_light_blue>%.1f</color>%%" ),
                                100.0f * chance.second );
        if( act->values.empty() ) {
            act->values.resize( 1 );
        }
        do {
            repeat = repeat_menu( title, repeat );
            if( repeat == REPEAT_CANCEL ) {
                act->set_to_null();
                return;
            }
            act->values[0] = static_cast<int>( repeat );
            // BACK selected, redo target selection next.
            if( repeat == REPEAT_INIT ) {
                p->activity.targets.pop_back();
                return;
            }
            if( repeat == REPEAT_FULL && fix.damage() <= 0 ) {
                p->add_msg_if_player( m_info, _( "Your %s is already fully repaired." ), fix.tname() );
                repeat = REPEAT_INIT;
            }
        } while( repeat == REPEAT_INIT );
    }
    // Otherwise keep retrying
    act->moves_left = actor->move_cost;
}
References _, act, repair_item_actor::action_description(), Character::activity, player::add_msg_if_player(), item::ammo_capacity(), item::ammo_consume(), item::ammo_current(), item::ammo_remaining(), item::ammo_required(), repair_item_actor::AS_CANT, repair_item_actor::AS_DESTROYED, repair_item_actor::AS_FAILURE, repair_item_actor::AS_SUCCESS, repair_item_actor::can_repair_target(), repair_item_actor::can_use_tool(), Character::consume_charges(), item::damage(), debugmsg, repair_item_actor::default_action(), destroyed, activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source(), use_function::get_actor_ptr(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool(), get_hack_type(), activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_position(), Character::get_skill_level(), item::get_usable_item(), item::get_use(), Character::i_at(), m_info, item_location::map, repair_item_actor::move_cost, Skill::name(), item::nname(), item_location::nowhere, cata::nullopt, string_id< T >::obj(), game_menus::inv::repair(), repair_item_actor::repair(), repair_item_actor::repair_chance(), REPEAT_CANCEL, REPEAT_EVENT, REPEAT_FULL, REPEAT_INIT, repeat_menu(), REPEAT_ONCE, repair_item_actor::RT_NOTHING, repair_item_actor::RT_PRACTICE, string_format(), player_activity::targets, PATH_INFO::title(), item::tname(), item::units_sufficient(), repair_item_actor::used_skill, and cata::optional< T >::value().
resume_for_multi_activities()
bool activity_handlers::resume_for_multi_activities (player & p)
Definition at line 417 of file activity_handlers.cpp.
{
    if( !p.backlog.empty() ) {
        player_activity &back_act = p.backlog.front();
        if( back_act.is_multi_type() ) {
            p.assign_activity( p.backlog.front().id() );
            p.backlog.clear();
            return true;
        }
    }
    return false;
}
References Character::assign_activity(), Character::backlog, and player_activity::is_multi_type().
Referenced by butcher_finish(), chop_logs_finish(), chop_planks_finish(), chop_tree_finish(), churn_finish(), generic_multi_activity_do(), jackhammer_finish(), pickaxe_finish(), plant_seed_finish(), and vehicle_finish().
robot_control_do_turn()
void activity_handlers::robot_control_do_turn (player_activity * act, player * p)
Definition at line 4495 of file activity_handlers.cpp.
{
    if( act->monsters.empty() ) {
        debugmsg( "No monster assigned in ACT_ROBOT_CONTROL" );
        act->set_to_null();
        return;
    }
    const shared_ptr_fast<monster> z = act->monsters[0].lock();
    if( !z || !iuse::robotcontrol_can_target( p, *z ) ) {
        p->add_msg_if_player( _( "Target lost.  IFF override failed." ) );
        act->set_to_null();
        return;
    }
    // TODO: Add some kind of chance of getting the target's attention
}
References _, act, player::add_msg_if_player(), debugmsg, and iuse::robotcontrol_can_target().
robot_control_finish()
void activity_handlers::robot_control_finish (player_activity * act, player * p)
Intelligence increases chance of successful robot reprogramming, vs difficulty Computer increases chance of successful robot reprogramming, vs difficulty
Definition at line 4513 of file activity_handlers.cpp.
{
    act->set_to_null();
    if( act->monsters.empty() ) {
        debugmsg( "No monster assigned in ACT_ROBOT_CONTROL" );
        return;
    }
    shared_ptr_fast<monster> z = act->monsters[0].lock();
    act->monsters.clear();
    if( !z || !iuse::robotcontrol_can_target( p, *z ) ) {
        p->add_msg_if_player( _( "Target lost.  IFF override failed." ) );
        return;
    }
    p->add_msg_if_player( _( "You unleash your override attack on the %s." ), z->name() );
    /** @EFFECT_INT increases chance of successful robot reprogramming, vs difficulty */
    /** @EFFECT_COMPUTER increases chance of successful robot reprogramming, vs difficulty */
    const int computer_skill = p->get_skill_level( skill_id( "computer" ) );
    const float randomized_skill = rng( 2, p->int_cur ) + computer_skill;
    float success = computer_skill - 3 * z->type->difficulty / randomized_skill;
    if( z->has_flag( MF_RIDEABLE_MECH ) ) {
        success = randomized_skill - rng( 1, 11 );
    }
    // rideable mechs are not hostile, they have no AI, they do not resist control as much.
    if( success >= 0 ) {
        p->add_msg_if_player( _( "You successfully override the %s's IFF protocols!" ),
                              z->name() );
        z->friendly = -1;
        if( z->has_flag( MF_RIDEABLE_MECH ) ) {
            z->add_effect( effect_pet, 1_turns, num_bp );
        }
    } else if( success >= -2 ) {
        //A near success
        p->add_msg_if_player( _( "The %s short circuits as you attempt to reprogram it!" ), z->name() );
        //damage it a little
        z->apply_damage( p, bodypart_id( "torso" ), rng( 1, 10 ) );
        if( z->is_dead() ) {
            p->practice( skill_id( "computer" ), 10 );
            // Do not do the other effects if the robot died
            return;
        }
        if( one_in( 3 ) ) {
            p->add_msg_if_player( _( "and turns friendly!" ) );
            //did the robot became friendly permanently?
            if( one_in( 3 ) ) {
                //it did
                z->friendly = -1;
            } else {
                // it didn't
                z->friendly = rng( 5, 40 );
            }
        }
    } else {
        p->add_msg_if_player( _( "but the robot refuses to acknowledge you as an ally!" ) );
    }
    p->practice( skill_computer, 10 );
}
References _, act, player::add_msg_if_player(), debugmsg, effect_pet, Character::get_skill_level(), Character::int_cur, MF_RIDEABLE_MECH, num_bp, one_in(), player::practice(), rng(), iuse::robotcontrol_can_target(), skill_computer, and behavior::success.
shaving_finish()
void activity_handlers::shaving_finish (player_activity * act, player * p)
Definition at line 4357 of file activity_handlers.cpp.
{
    p->add_msg_if_player( _( "You open up your kit and shave." ) );
    p->add_morale( MORALE_SHAVE, 8, 8, 240_minutes, 3_minutes );
    act->set_to_null();
}
References _, act, Character::add_morale(), player::add_msg_if_player(), and MORALE_SHAVE.
shear_finish()
void activity_handlers::shear_finish (player_activity * act, player * p)
Definition at line 1422 of file activity_handlers.cpp.
{
    if( act->coords.empty() ) {
        debugmsg( "shearing activity with no position of monster stored" );
        return;
    }
    item_location &loc = act->targets[ 0 ];
    item *shears = loc.get_item();
    if( shears == nullptr ) {
        debugmsg( "shearing item location lost" );
        return;
    }
    map &here = get_map();
    const tripoint source_pos = here.getlocal( act->coords.at( 0 ) );
    monster *source_mon = g->critter_at<monster>( source_pos );
    if( source_mon == nullptr ) {
        debugmsg( "could not find source creature for shearing" );
        return;
    }
    // 22 wool staples corresponds to an average wool-producing sheep yield of 10 lbs or so
    for( int i = 0; i != 22; ++i ) {
        item wool_staple( itype_wool_staple, calendar::turn );
        here.add_item_or_charges( p->pos(), wool_staple );
    }
    source_mon->add_effect( effect_sheared, calendar::season_length() );
    if( !act->str_values.empty() && act->str_values[0] == "temp_tie" ) {
        source_mon->remove_effect( effect_tied );
    }
    act->set_to_null();
    if( shears->type->can_have_charges() ) {
        p->consume_charges( *shears, shears->type->charges_to_use() );
    }
}
References act, monster::add_effect(), map::add_item_or_charges(), itype::can_have_charges(), itype::charges_to_use(), Character::consume_charges(), debugmsg, effect_sheared, effect_tied, g, item_location::get_item(), get_map(), map::getlocal(), itype_wool_staple, Character::pos(), Creature::remove_effect(), calendar::season_length(), calendar::turn, and item::type.
socialize_finish()
void activity_handlers::socialize_finish (player_activity * act, player * p)
Definition at line 3472 of file activity_handlers.cpp.
{
    p->add_msg_if_player( _( "%s finishes chatting with you." ), act->str_values[0] );
    act->set_to_null();
}
References _, act, and player::add_msg_if_player().
spellcasting_do_turn()
void activity_handlers::spellcasting_do_turn (player_activity * act, player * p)
spellcasting_finish()
void activity_handlers::spellcasting_finish (player_activity * act, player * p)
Definition at line 4655 of file activity_handlers.cpp.
{
    act->set_to_null();
    const int level_override = act->get_value( 0 );
    spell_id sp( act->name );
    // if level is -1 then we know it's a player spell, otherwise we build it from the ground up
    spell temp_spell( sp );
    spell &spell_being_cast = ( level_override == -1 ) ? p->magic->get_spell( sp ) : temp_spell;
    // if level != 1 then we need to set the spell's level
    if( level_override != -1 ) {
        while( spell_being_cast.get_level() < level_override && !spell_being_cast.is_max_level() ) {
            spell_being_cast.gain_level();
        }
    }
    const bool no_fail = act->get_value( 1 ) == 1;
    const bool no_mana = act->get_value( 2 ) == 0;
    // choose target for spell (if the spell has a range > 0)
    tripoint target = p->pos();
    bool target_is_valid = false;
    if( spell_being_cast.range() > 0 && !spell_being_cast.is_valid_target( target_none ) &&
        !spell_being_cast.has_flag( RANDOM_TARGET ) ) {
        do {
            avatar &you = *p->as_avatar();
            std::vector<tripoint> trajectory = target_handler::mode_spell( you, spell_being_cast, no_fail,
                                               no_mana );
            if( !trajectory.empty() ) {
                target = trajectory.back();
                target_is_valid = spell_being_cast.is_valid_target( *p, target );
                if( !( spell_being_cast.is_valid_target( target_ground ) || p->sees( target ) ) ) {
                    target_is_valid = false;
                }
            } else {
                target_is_valid = false;
            }
            if( !target_is_valid ) {
                if( query_yn( _( "Stop casting spell?  Time spent will be lost." ) ) ) {
                    return;
                }
            }
        } while( !target_is_valid );
    } else if( spell_being_cast.has_flag( RANDOM_TARGET ) ) {
        const cata::optional<tripoint> target_ = spell_being_cast.random_valid_target( *p, p->pos() );
        if( !target_ ) {
            p->add_msg_if_player( game_message_params{ m_bad, gmf_bypass_cooldown },
                                  _( "Your spell can't find a suitable target." ) );
            return;
        }
        target = *target_;
    }
    // no turning back now. it's all said and done.
    bool success = no_fail || rng_float( 0.0f, 1.0f ) >= spell_being_cast.spell_fail( *p );
    int exp_gained = spell_being_cast.casting_exp( *p );
    if( !success ) {
        p->add_msg_if_player( game_message_params{ m_bad, gmf_bypass_cooldown },
                              _( "You lose your concentration!" ) );
        if( !spell_being_cast.is_max_level() && level_override == -1 ) {
            // still get some experience for trying
            spell_being_cast.gain_exp( exp_gained / 5 );
            p->add_msg_if_player( m_good, _( "You gain %i experience.  New total %i." ), exp_gained / 5,
                                  spell_being_cast.xp() );
        }
        return;
    }
    if( spell_being_cast.has_flag( spell_flag::VERBAL ) ) {
        sounds::sound( p->pos(), p->get_shout_volume() / 2, sounds::sound_t::speech, _( "cast a spell" ),
                       false );
    }
    p->add_msg_if_player( spell_being_cast.message(), spell_being_cast.name() );
    spell_being_cast.cast_all_effects( *p, target );
    if( !no_mana ) {
        // pay the cost
        int cost = spell_being_cast.energy_cost( *p );
        switch( spell_being_cast.energy_source() ) {
            case mana_energy:
                p->magic->mod_mana( *p, -cost );
                break;
            case stamina_energy:
                p->mod_stamina( -cost );
                break;
            case bionic_energy:
                p->mod_power_level( -units::from_kilojoule( cost ) );
                break;
            case hp_energy:
                blood_magic( p, cost );
                break;
            case fatigue_energy:
                p->mod_fatigue( cost );
                break;
            case none_energy:
            default:
                break;
        }
    }
    if( level_override == -1 ) {
        if( !spell_being_cast.is_max_level() ) {
            // reap the reward
            int old_level = spell_being_cast.get_level();
            if( old_level == 0 ) {
                spell_being_cast.gain_level();
                p->add_msg_if_player( m_good,
                                      _( "Something about how this spell works just clicked!  You gained a level!" ) );
            } else {
                spell_being_cast.gain_exp( exp_gained );
                p->add_msg_if_player( m_good, _( "You gain %i experience.  New total %i." ), exp_gained,
                                      spell_being_cast.xp() );
            }
            if( spell_being_cast.get_level() != old_level ) {
                g->events().send<event_type::player_levels_spell>( spell_being_cast.id(),
                        spell_being_cast.get_level() );
            }
        }
    }
}
References _, act, player::add_msg_if_player(), Creature::as_avatar(), bionic_energy, blood_magic(), spell::cast_all_effects(), spell::casting_exp(), spell::energy_cost(), spell::energy_source(), fatigue_energy, units::from_kilojoule(), g, spell::gain_exp(), spell::gain_level(), spell::get_level(), Character::get_shout_volume(), gmf_bypass_cooldown, spell::has_flag(), hp_energy, spell::id(), spell::is_max_level(), spell::is_valid_target(), m_bad, m_good, Character::magic, mana_energy, spell::message(), Character::mod_fatigue(), Character::mod_power_level(), Character::mod_stamina(), target_handler::mode_spell(), spell::name(), none_energy, player_levels_spell, Character::pos(), query_yn(), RANDOM_TARGET, spell::random_valid_target(), spell::range(), rng_float(), Character::sees(), sounds::sound(), sounds::speech, spell::spell_fail(), stamina_energy, behavior::success, target_ground, target_none, VERBAL, and spell::xp().
start_engines_finish()
void activity_handlers::start_engines_finish (player_activity * act, player * p)
Definition at line 2368 of file activity_handlers.cpp.
{
    act->set_to_null();
    // Find the vehicle by looking for a remote vehicle first, then by player relative coordinates
    vehicle *veh = g->remoteveh();
    map &here = get_map();
    if( !veh ) {
        const tripoint pos = act->placement + g->u.pos();
        veh = veh_pointer_or_null( here.veh_at( pos ) );
        if( !veh ) {
            return;
        }
    }
    int attempted = 0;
    int non_muscle_attempted = 0;
    int started = 0;
    int non_muscle_started = 0;
    int non_combustion_started = 0;
    const bool take_control = act->values[0];
    for( size_t e = 0; e < veh->engines.size(); ++e ) {
        if( veh->is_engine_on( e ) ) {
            attempted++;
            if( !veh->is_engine_type( e, itype_muscle ) &&
                !veh->is_engine_type( e, itype_animal ) ) {
                non_muscle_attempted++;
            }
            if( veh->start_engine( e ) ) {
                started++;
                if( !veh->is_engine_type( e, itype_muscle ) &&
                    !veh->is_engine_type( e, itype_animal ) ) {
                    non_muscle_started++;
                } else {
                    non_combustion_started++;
                }
            }
        }
    }
    //Did any engines start?
    veh->engine_on = started;
    //init working engine noise
    sfx::do_vehicle_engine_sfx();
    if( attempted == 0 ) {
        add_msg( m_info, _( "The %s doesn't have an engine!" ), veh->name );
    } else if( non_muscle_attempted > 0 ) {
        //Some non-muscle engines tried to start
        if( non_muscle_attempted == non_muscle_started ) {
            //All of the non-muscle engines started
            add_msg( vgettext( "The %s's engine starts up.",
                               "The %s's engines start up.", non_muscle_started ), veh->name );
        } else if( non_muscle_started > 0 ) {
            //Only some of the non-muscle engines started
            add_msg( vgettext( "One of the %s's engines start up.",
                               "Some of the %s's engines start up.", non_muscle_started ), veh->name );
        } else if( non_combustion_started > 0 ) {
            //Non-combustions "engines" started
            add_msg( _( "The %s is ready for movement." ), veh->name );
        } else {
            //All of the non-muscle engines failed
            add_msg( m_bad, vgettext( "The %s's engine fails to start.",
                                      "The %s's engines fail to start.", non_muscle_attempted ), veh->name );
        }
    }
    if( take_control && !veh->engine_on && !veh->velocity ) {
        p->controlling_vehicle = false;
        add_msg( _( "You let go of the controls." ) );
    }
}
References _, act, add_msg(), Character::controlling_vehicle, sfx::do_vehicle_engine_sfx(), vehicle::engine_on, vehicle::engines, g, get_map(), vehicle::is_engine_on(), vehicle::is_engine_type(), itype_animal, itype_muscle, m_bad, m_info, vehicle::name, vehicle::start_engine(), map::veh_at(), veh_pointer_or_null(), vehicle::velocity, and vgettext().
start_fire_do_turn()
void activity_handlers::start_fire_do_turn (player_activity * act, player * p)
Definition at line 2169 of file activity_handlers.cpp.
{
    map &here = get_map();
    if( !here.is_flammable( act->placement ) ) {
        try_fuel_fire( *act, *p, true );
        if( !here.is_flammable( act->placement ) ) {
            p->add_msg_if_player( m_info, _( "There's nothing to light there." ) );
            p->cancel_activity();
            return;
        }
    }
    item &firestarter = *act->targets.front();
    if( firestarter.has_flag( flag_REQUIRES_TINDER ) ) {
        if( !here.tinder_at( act->placement ) ) {
            p->add_msg_if_player( m_info, _( "This item requires tinder to light." ) );
            p->cancel_activity();
            return;
        }
    }
    const use_function *usef = firestarter.type->get_use( "firestarter" );
    if( usef == nullptr || usef->get_actor_ptr() == nullptr ) {
        add_msg( m_bad, _( "You have lost the item you were using to start the fire." ) );
        p->cancel_activity();
        return;
    }
    p->mod_moves( -p->moves );
    const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
    const float light = actor->light_mod( p->pos() );
    act->moves_left -= light * 100;
    if( light < 0.1 ) {
        add_msg( m_bad, _( "There is not enough sunlight to start a fire now.  You stop trying." ) );
        p->cancel_activity();
    }
}
References _, act, add_msg(), player::add_msg_if_player(), Character::cancel_activity(), flag_REQUIRES_TINDER(), use_function::get_actor_ptr(), get_map(), itype::get_use(), item::has_flag(), map::is_flammable(), light, firestarter_actor::light_mod(), m_bad, m_info, Creature::mod_moves(), Creature::moves, Character::pos(), map::tinder_at(), try_fuel_fire(), and item::type.
start_fire_finish()
void activity_handlers::start_fire_finish (player_activity * act, player * p)
Definition at line 2139 of file activity_handlers.cpp.
{
    static const std::string iuse_name_string( "firestarter" );
    item &it = *act->targets.front();
    item *used_tool = it.get_usable_item( iuse_name_string );
    if( used_tool == nullptr ) {
        debugmsg( "Lost tool used for starting fire" );
        act->set_to_null();
        return;
    }
    const use_function *use_fun = used_tool->get_use( iuse_name_string );
    const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>
                                     ( use_fun->get_actor_ptr() );
    if( actor == nullptr ) {
        debugmsg( "iuse_actor type descriptor and actual type mismatch" );
        act->set_to_null();
        return;
    }
    if( it.type->can_have_charges() ) {
        p->consume_charges( it, it.type->charges_to_use() );
    }
    p->practice( skill_survival, act->index, 5 );
    firestarter_actor::resolve_firestarter_use( *p, act->placement );
    act->set_to_null();
}
References act, itype::can_have_charges(), itype::charges_to_use(), Character::consume_charges(), debugmsg, use_function::get_actor_ptr(), item::get_usable_item(), item::get_use(), player::practice(), firestarter_actor::resolve_firestarter_use(), skill_survival, and item::type.
stash_do_turn()
void activity_handlers::stash_do_turn (player_activity * act, player * p)
study_spell_do_turn()
void activity_handlers::study_spell_do_turn (player_activity * act, player * p)
Definition at line 4780 of file activity_handlers.cpp.
{
    if( !character_funcs::can_see_fine_details( *p ) ) {
        act->values[2] = -1;
        act->moves_left = 0;
        return;
    }
    if( act->get_str_value( 1 ) == "study" ) {
        spell &studying = p->magic->get_spell( spell_id( act->name ) );
        if( act->get_str_value( 0 ) == "gain_level" ) {
            if( studying.get_level() < act->get_value( 1 ) ) {
                act->moves_left = 1000000;
            } else {
                act->moves_left = 0;
            }
        }
        const int xp = roll_remainder( studying.exp_modifier( *p ) / to_turns<float>( 6_seconds ) );
        act->values[0] += xp;
        studying.gain_exp( xp );
    }
}
References act, character_funcs::can_see_fine_details(), spell::exp_modifier(), spell::gain_exp(), spell::get_level(), Character::magic, and roll_remainder().
study_spell_finish()
void activity_handlers::study_spell_finish (player_activity * act, player * p)
Definition at line 4802 of file activity_handlers.cpp.
{
    act->set_to_null();
    const int total_exp_gained = act->get_value( 0 );
    if( act->get_str_value( 1 ) == "study" ) {
        p->add_msg_if_player( m_good, _( "You gained %i experience from your study session." ),
                              total_exp_gained );
        const spell &sp = p->magic->get_spell( spell_id( act->name ) );
        p->practice( sp.skill(), total_exp_gained, sp.get_difficulty() );
    } else if( act->get_str_value( 1 ) == "learn" && act->values[2] == 0 ) {
        p->magic->learn_spell( act->name, *p );
    }
    if( act->values[2] == -1 ) {
        p->add_msg_if_player( m_bad, _( "It's too dark to read." ) );
    }
}
References _, act, player::add_msg_if_player(), spell::get_difficulty(), m_bad, m_good, Character::magic, player::practice(), and spell::skill().
tidy_up_do_turn()
void activity_handlers::tidy_up_do_turn (player_activity * act, player * p)
Definition at line 3834 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
toolmod_add_finish()
void activity_handlers::toolmod_add_finish (player_activity * act, player * p)
Definition at line 3098 of file activity_handlers.cpp.
{
    act->set_to_null();
    if( act->targets.size() != 2 || !act->targets[0] || !act->targets[1] ) {
        debugmsg( "Incompatible arguments to ACT_TOOLMOD_ADD" );
        return;
    }
    item &tool = *act->targets[0];
    item &mod = *act->targets[1];
    p->add_msg_if_player( m_good, _( "You successfully attached the %1$s to your %2$s." ),
                          mod.tname(), tool.tname() );
    mod.set_flag( "IRREMOVABLE" );
    tool.put_in( mod );
    act->targets[1].remove_item();
}
References _, act, player::add_msg_if_player(), debugmsg, m_good, and tool.
train_finish()
void activity_handlers::train_finish (player_activity * act, player * p)
Definition at line 2236 of file activity_handlers.cpp.
{
    const skill_id sk( act->name );
    if( sk.is_valid() ) {
        const Skill &skill = sk.obj();
        std::string skill_name = skill.name();
        int old_skill_level = p->get_skill_level( sk );
        p->get_skill_level_object( sk ).train( 100, true );
        int new_skill_level = p->get_skill_level( sk );
        if( old_skill_level != new_skill_level ) {
            add_msg( m_good, _( "You finish training %s to level %d." ),
                     skill_name, new_skill_level );
            g->events().send<event_type::gains_skill_level>( p->getID(), sk, new_skill_level );
        } else {
            add_msg( m_good, _( "You get some training in %s." ), skill_name );
        }
        act->set_to_null();
        return;
    }
    const matype_id &ma_id = matype_id( act->name );
    if( ma_id.is_valid() ) {
        const martialart &mastyle = ma_id.obj();
        // Trained martial arts,
        g->events().send<event_type::learns_martial_art>( p->getID(), ma_id );
        p->martial_arts_data->learn_style( mastyle.id, p->is_avatar() );
    } else if( !magic_train( act, p ) ) {
        debugmsg( "train_finish without a valid skill or style or spell name" );
    }
    act->set_to_null();
    return;
}
References _, act, add_msg(), debugmsg, g, gains_skill_level, Character::get_skill_level(), Character::get_skill_level_object(), Character::getID(), martialart::id, Creature::is_avatar(), string_id< T >::is_valid(), learns_martial_art, m_good, magic_train(), Character::martial_arts_data, Skill::name(), string_id< T >::obj(), and SkillLevel::train().
travel_do_turn()
void activity_handlers::travel_do_turn (player_activity * act, player * p)
Definition at line 3169 of file activity_handlers.cpp.
{
    if( !p->omt_path.empty() ) {
        p->omt_path.pop_back();
        if( p->omt_path.empty() ) {
            p->add_msg_if_player( m_info, _( "You have reached your destination." ) );
            act->set_to_null();
            return;
        }
        const tripoint_abs_omt next_omt = p->omt_path.back();
        tripoint_abs_ms waypoint;
        if( p->omt_path.size() == 1 ) {
            // if next omt is the final one, target its midpoint
            waypoint = midpoint( project_bounds<coords::ms>( next_omt ) );
        } else {
            // otherwise target the middle of the edge nearest to our current location
            const tripoint_abs_ms cur_omt_mid = midpoint( project_bounds<coords::ms>
                                                ( p->global_omt_location() ) );
            waypoint = clamp( cur_omt_mid, project_bounds<coords::ms>( next_omt ) );
        }
        map &here = get_map();
        // TODO: fix point types
        tripoint centre_sub = here.getlocal( waypoint.raw() );
        if( !here.passable( centre_sub ) ) {
            tripoint_range<tripoint> candidates = here.points_in_radius( centre_sub, 2 );
            for( const tripoint &elem : candidates ) {
                if( here.passable( elem ) ) {
                    centre_sub = elem;
                    break;
                }
            }
        }
        const std::vector<tripoint> route_to = here.route( p->pos(), centre_sub,
                                               p->get_pathfinding_settings(),
                                               p->get_path_avoid() );
        if( !route_to.empty() ) {
            const activity_id act_travel = ACT_TRAVELLING;
            p->set_destination( route_to, player_activity( act_travel ) );
        } else {
            p->add_msg_if_player( _( "You cannot reach that destination" ) );
        }
    } else {
        p->add_msg_if_player( m_info, _( "You have reached your destination." ) );
    }
    act->set_to_null();
}
References _, act, ACT_TRAVELLING, player::add_msg_if_player(), clamp(), get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), map::getlocal(), Character::global_omt_location(), m_info, midpoint(), Character::omt_path, map::passable(), map::points_in_radius(), Character::pos(), coords::coord_point< Point, Origin, Scale >::raw(), map::route(), and Character::set_destination().
tree_communion_do_turn()
void activity_handlers::tree_communion_do_turn (player_activity * act, player * p)
Definition at line 4575 of file activity_handlers.cpp.
{
    // There's an initial rooting process.
    if( act->values.front() > 0 ) {
        act->values.front() -= 1;
        if( act->values.front() == 0 ) {
            if( p->has_trait( trait_id( trait_SPIRITUAL ) ) ) {
                p->add_msg_if_player( m_good, _( "The ancient tree spirits answer your call." ) );
            } else {
                p->add_msg_if_player( m_good, _( "Your communion with the trees has begun." ) );
            }
        }
        return;
    }
    // Information is received every minute.
    if( !calendar::once_every( 1_minutes ) ) {
        return;
    }
    // Breadth-first search forest tiles until one reveals new overmap tiles.
    std::queue<tripoint_abs_omt> q;
    std::unordered_set<tripoint_abs_omt> seen;
    tripoint_abs_omt loc = p->global_omt_location();
    q.push( loc );
    seen.insert( loc );
    const std::function<bool( const oter_id & )> filter = []( const oter_id & ter ) {
        return ter.obj().is_wooded() || ter.obj().get_name() == "field";
    };
    while( !q.empty() ) {
        tripoint_abs_omt tpt = q.front();
        if( overmap_buffer.reveal( tpt, 3, filter ) ) {
            if( p->has_trait( trait_SPIRITUAL ) ) {
                p->add_morale( MORALE_TREE_COMMUNION, 2, 30, 8_hours, 6_hours );
            } else {
                p->add_morale( MORALE_TREE_COMMUNION, 1, 15, 2_hours, 1_hours );
            }
            if( one_in( 128 ) ) {
                p->add_msg_if_player( "%s", SNIPPET.random_from_category( "tree_communion" ).value_or(
                                          translation() ) );
            }
            return;
        }
        for( const tripoint_abs_omt &neighbor : points_in_radius( tpt, 1 ) ) {
            if( seen.find( neighbor ) != seen.end() ) {
                continue;
            }
            seen.insert( neighbor );
            if( !overmap_buffer.ter( neighbor ).obj().is_wooded() ) {
                continue;
            }
            q.push( neighbor );
        }
        q.pop();
    }
    p->add_msg_if_player( m_info, _( "The trees have shown you what they will." ) );
    act->set_to_null();
}
References _, act, Character::add_morale(), player::add_msg_if_player(), Character::global_omt_location(), Character::has_trait(), oter_t::is_wooded(), m_good, m_info, MORALE_TREE_COMMUNION, int_id< T >::obj(), calendar::once_every(), one_in(), overmap_buffer, points_in_radius(), snippet_library::random_from_category(), overmapbuffer::reveal(), SNIPPET, overmapbuffer::ter(), and trait_SPIRITUAL.
try_sleep_do_turn()
void activity_handlers::try_sleep_do_turn (player_activity * act, player * p)
Definition at line 3478 of file activity_handlers.cpp.
{
    if( !p->has_effect( effect_sleep ) ) {
        if( p->can_sleep() ) {
            act->set_to_null();
            p->fall_asleep();
            p->remove_value( "sleep_query" );
        } else if( one_in( 1000 ) ) {
            p->add_msg_if_player( _( "You toss and turn" ) );
        }
        if( calendar::once_every( 30_minutes ) ) {
            try_sleep_query( act, p );
        }
    }
}
References _, act, player::add_msg_if_player(), player::can_sleep(), effect_sleep, Character::fall_asleep(), Creature::has_effect(), calendar::once_every(), one_in(), Creature::remove_value(), and try_sleep_query().
try_sleep_finish()
void activity_handlers::try_sleep_finish (player_activity * act, player * p)
Definition at line 3673 of file activity_handlers.cpp.
{
    if( !p->has_effect( effect_sleep ) ) {
        p->add_msg_if_player( _( "You try to sleep, but can't" ) );
    }
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), effect_sleep, and Creature::has_effect().
try_sleep_query()
void activity_handlers::try_sleep_query (player_activity * act, player * p)
Definition at line 3494 of file activity_handlers.cpp.
{
    if( p->get_value( "sleep_query" ) == "false" ) {
        return;
    }
    uilist sleep_query;
    sleep_query.text = _( "You have trouble sleeping, keep trying?" );
    sleep_query.addentry( 1, true, 'S', _( "Stop trying to fall asleep and get up." ) );
    sleep_query.addentry( 2, true, 'c', _( "Continue trying to fall asleep." ) );
    sleep_query.addentry( 3, true, 'C',
                          _( "Continue trying to fall asleep and don't ask again." ) );
    sleep_query.query();
    switch( sleep_query.ret ) {
        case UILIST_CANCEL:
        case 1:
            act->set_to_null();
            break;
        case 3:
            p->set_value( "sleep_query", "false" );
            break;
        case 2:
        default:
            break;
    }
}
References _, act, uilist::addentry(), Creature::get_value(), uilist::query(), uilist::ret, Creature::set_value(), uilist::text, and UILIST_CANCEL.
Referenced by try_sleep_do_turn().
unload_mag_finish()
void activity_handlers::unload_mag_finish (player_activity * act, player * p)
vehicle_deconstruction_do_turn()
void activity_handlers::vehicle_deconstruction_do_turn (player_activity * act, player * p)
Definition at line 3864 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
vehicle_finish()
void activity_handlers::vehicle_finish (player_activity * act, player * p)
Definition at line 2270 of file activity_handlers.cpp.
{
    map &here = get_map();
    //Grab this now, in case the vehicle gets shifted
    const optional_vpart_position vp = here.veh_at( here.getlocal( tripoint( act->values[0],
                                       act->values[1],
                                       act->values[7] ) ) );
    veh_interact::complete_vehicle( *p );
    // complete_vehicle set activity type to NULL if the vehicle
    // was completely dismantled, otherwise the vehicle still exist and
    // is to be examined again.
    if( act->is_null() ) {
        if( npc *guy = dynamic_cast<npc *>( p ) ) {
            guy->revert_after_activity();
            guy->set_moves( 0 );
        }
        return;
    }
    act->set_to_null();
    if( !p->is_npc() ) {
        if( act->values.size() < 8 ) {
            debugmsg( "process_activity invalid ACT_VEHICLE values:%d",
                      act->values.size() );
        } else {
            if( vp ) {
                here.invalidate_map_cache( g->get_levz() );
                // TODO: Z (and also where the activity is queued)
                // Or not, because the vehicle coordinates are dropped anyway
                if( !resume_for_multi_activities( *p ) ) {
                    g->exam_vehicle( vp->vehicle(), point( act->values[ 2 ], act->values[ 3 ] ) );
                }
                return;
            } else {
                debugmsg( "process_activity ACT_VEHICLE: vehicle not found" );
            }
        }
    }
}
References act, veh_interact::complete_vehicle(), debugmsg, g, get_map(), map::getlocal(), map::invalidate_map_cache(), player::is_npc(), resume_for_multi_activities(), and map::veh_at().
vehicle_repair_do_turn()
void activity_handlers::vehicle_repair_do_turn (player_activity * act, player * p)
Definition at line 3869 of file activity_handlers.cpp.
{
    generic_multi_activity_handler( *act, *p );
}
References act, and generic_multi_activity_handler().
vibe_do_turn()
void activity_handlers::vibe_do_turn (player_activity * act, player * p)
Definition at line 2333 of file activity_handlers.cpp.
{
    //Using a vibrator takes time (10 minutes), not speed
    //Linear increase in morale during action with a small boost at end
    //Deduct 1 battery charge for every minute in use, or vibrator is much less effective
    item &vibrator_item = *act->targets.front();
    if( p->encumb( bp_mouth ) >= 30 ) {
        act->moves_left = 0;
        add_msg( m_bad, _( "You have trouble breathing, and stop." ) );
    }
    if( calendar::once_every( 1_minutes ) ) {
        p->mod_fatigue( 1 );
        if( vibrator_item.ammo_remaining() > 0 ) {
            vibrator_item.ammo_consume( 1, p->pos() );
            p->add_morale( MORALE_FEELING_GOOD, 3, 40 );
            if( vibrator_item.ammo_remaining() == 0 ) {
                add_msg( m_info, _( "The %s runs out of batteries." ), vibrator_item.tname() );
            }
        } else {
            //twenty minutes to fill
            p->add_morale( MORALE_FEELING_GOOD, 1, 40 );
        }
    }
    // Dead Tired: different kind of relaxation needed
    if( p->get_fatigue() >= fatigue_levels::dead_tired ) {
        act->moves_left = 0;
        add_msg( m_info, _( "You're too tired to continue." ) );
    }
    // Vibrator requires that you be able to move around, stretch, etc, so doesn't play
    // well with roots.  Sorry.  :-(
}
References _, act, Character::add_morale(), add_msg(), item::ammo_consume(), item::ammo_remaining(), bp_mouth, dead_tired, Character::encumb(), Character::get_fatigue(), m_bad, m_info, Character::mod_fatigue(), MORALE_FEELING_GOOD, calendar::once_every(), Character::pos(), and item::tname().
vibe_finish()
void activity_handlers::vibe_finish (player_activity * act, player * p)
Definition at line 3994 of file activity_handlers.cpp.
{
    p->add_msg_if_player( m_good, _( "You feel much better." ) );
    p->add_morale( MORALE_FEELING_GOOD, 10, 40 );
    act->set_to_null();
}
References _, act, Character::add_morale(), player::add_msg_if_player(), m_good, and MORALE_FEELING_GOOD.
wait_finish()
void activity_handlers::wait_finish (player_activity * act, player * p)
Definition at line 3379 of file activity_handlers.cpp.
{
    p->add_msg_if_player( _( "You finish waiting." ) );
    act->set_to_null();
}
References _, act, and player::add_msg_if_player().
wait_npc_finish()
void activity_handlers::wait_npc_finish (player_activity * act, player * p)
Definition at line 3434 of file activity_handlers.cpp.
{
    p->add_msg_if_player( _( "%s finishes with you" ), act->str_values[0] );
    act->set_to_null();
}
References _, act, and player::add_msg_if_player().
wait_stamina_do_turn()
void activity_handlers::wait_stamina_do_turn (player_activity * act, player * p)
Definition at line 3440 of file activity_handlers.cpp.
{
    int stamina_threshold = p->get_stamina_max();
    if( !act->values.empty() ) {
        stamina_threshold = act->values[0];
        // remember initial stamina, only for waiting-with-threshold
        if( act->values.size() == 1 ) {
            act->values.push_back( p->get_stamina() );
        }
    }
    if( p->get_stamina() >= stamina_threshold ) {
        wait_stamina_finish( act, p );
    }
}
References act, Character::get_stamina(), Character::get_stamina_max(), and wait_stamina_finish().
wait_stamina_finish()
void activity_handlers::wait_stamina_finish (player_activity * act, player * p)
Definition at line 3455 of file activity_handlers.cpp.
{
    if( !act->values.empty() ) {
        const int stamina_threshold = act->values[0];
        const int stamina_initial = ( act->values.size() > 1 ) ? act->values[1] : p->get_stamina();
        if( p->get_stamina() < stamina_threshold && p->get_stamina() <= stamina_initial ) {
            debugmsg( "Failed to wait until stamina threshold %d reached, only at %d. You may not be regaining stamina.",
                      act->values.front(), p->get_stamina() );
        }
    } else if( p->get_stamina() < p->get_stamina_max() ) {
        p->add_msg_if_player( _( "You are bored of waiting, so you stop." ) );
    } else {
        p->add_msg_if_player( _( "You finish waiting and feel refreshed." ) );
    }
    act->set_to_null();
}
References _, act, player::add_msg_if_player(), debugmsg, Character::get_stamina(), and Character::get_stamina_max().
Referenced by wait_stamina_do_turn().
wait_weather_finish()
void activity_handlers::wait_weather_finish (player_activity * act, player * p)
Definition at line 3385 of file activity_handlers.cpp.
{
    p->add_msg_if_player( _( "You finish waiting." ) );
    act->set_to_null();
}
References _, act, and player::add_msg_if_player().
washing_finish()
void activity_handlers::washing_finish (player_activity * act, player * p)
wear_do_turn()
void activity_handlers::wear_do_turn (player_activity * act, player * p)
Definition at line 3132 of file activity_handlers.cpp.
{
    activity_on_turn_wear( *act, *p );
}
References act, and activity_on_turn_wear().
Variable Documentation
do_turn_functions
const std::map< activity_id, std::function< void(player_activity *, player *)> > activity_handlers::do_turn_functions extern
Definition at line 288 of file activity_handlers.cpp.
Referenced by activity_type::call_do_turn(), and activity_type::check_consistency().
finish_functions
const std::map< activity_id, std::function< void(player_activity *, player *)> > activity_handlers::finish_functions extern
Definition at line 352 of file activity_handlers.cpp.
Referenced by activity_type::call_finish(), and activity_type::check_consistency().