Cataclysm BN: clothing_mods Namespace Reference
clothing_mods Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void reset ()
const std::vector< clothing_mod > & get_all ()
const std::vector< clothing_mod > & get_all_with (clothing_mod_type type)
std::string string_from_clothing_mod_type (clothing_mod_type type)
Variables
constexpr std::array< clothing_mod_type, 9 > all_clothing_mod_types
Function Documentation
get_all()
const std::vector< clothing_mod > & clothing_mods::get_all ()
Definition at line 145 of file clothing_mod.cpp.
{
    return all_clothing_mods.get_all();
}
References anonymous_namespace{clothing_mod.cpp}::all_clothing_mods.
Referenced by item::has_clothing_mod(), and sew_advanced_actor::use().
get_all_with()
const std::vector< clothing_mod > & clothing_mods::get_all_with (clothing_mod_type type)
Definition at line 150 of file clothing_mod.cpp.
{
    const auto iter = clothing_mods_by_type.find( type );
    if( iter != clothing_mods_by_type.end() ) {
        return iter->second;
    } else {
        // Build cache
        std::vector<clothing_mod> list;
        for( auto &cm : get_all() ) {
            if( cm.has_mod_type( type ) ) {
                list.push_back( cm );
            }
        }
        clothing_mods_by_type.emplace( type, std::move( list ) );
        return clothing_mods_by_type[type];
    }
}
References clothing_mods_by_type, ammo_effects::get_all(), avatar_action::move(), and type.
Referenced by item::update_clothing_mod_val().
load()
void clothing_mods::load (const JsonObject & jo, const std::string & src)
Definition at line 134 of file clothing_mod.cpp.
{
    all_clothing_mods.load( jo, src );
}
References anonymous_namespace{clothing_mod.cpp}::all_clothing_mods.
Referenced by DynamicDataLoader::initialize().
reset()
void clothing_mods::reset ()
Definition at line 139 of file clothing_mod.cpp.
{
    all_clothing_mods.reset();
    clothing_mods_by_type.clear();
}
References anonymous_namespace{clothing_mod.cpp}::all_clothing_mods, and clothing_mods_by_type.
Referenced by DynamicDataLoader::unload_data().
string_from_clothing_mod_type()
std::string clothing_mods::string_from_clothing_mod_type (clothing_mod_type type)
Definition at line 168 of file clothing_mod.cpp.
{
    return io::enum_to_string<clothing_mod_type>( type );
}
References io::enum_to_string< clothing_mod_type >(), and type.
Referenced by item::get_clothing_mod_val(), and item::update_clothing_mod_val().
Variable Documentation
all_clothing_mod_types
constexpr std::array<clothing_mod_type, 9> clothing_mods::all_clothing_mod_types constexpr
Initial value:
= {{
        clothing_mod_type_acid,
        clothing_mod_type_fire,
        clothing_mod_type_bash,
        clothing_mod_type_cut,
        clothing_mod_type_bullet,
        clothing_mod_type_encumbrance,
        clothing_mod_type_warmth,
        clothing_mod_type_storage,
        clothing_mod_type_invalid
    }
}
Definition at line 63 of file clothing_mod.h.
Referenced by item::update_clothing_mod_val().