Cataclysm BN: pickup Namespace Reference
pickup Namespace Reference
Classes
struct act_item
Activity-associated item.
struct parent_child_check_t
struct pick_drop_selection
struct stacked_items
struct unstacked_items
Enumerations
enum from_where : int { from_cargo = 0 , from_ground , prompt }
Functions
std::list< act_item > reorder_for_dropping (Character &p, const drop_locations &drop)
static bool try_rebuild_if_needed (item_location &loc)
std::list< item > obtain_and_tokenize_items (player &p, std::list< act_item > &items)
bool do_pickup (std::vector< pick_drop_selection > &targets, bool autopickup)
Returns false if the player was presented a prompt and decided to cancel the pickup.
static std::vector< cata::optional< size_t > > calculate_parents (const std::vector< std::list< item_stack::iterator > > &stacked_here)
std::vector< stacked_items > stack_for_pickup_ui (const std::vector< item_stack::iterator > &unstacked)
std::vector< std::list< item_stack::iterator > > flatten (const std::vector< stacked_items > &stacked)
std::vector< pick_drop_selection > optimize_pickup (const std::vector< item_location > &targets, const std::vector< int > &quantities)
Finds possible parent-child relations in picked up items to save moves.
bool query_thief ()
void pick_up (const tripoint &p, int min, from_where get_items_from=prompt)
Pick up items; 'g' or ',' or via examine()
int cost_to_move_item (const Character &who, const item &it)
Determines the cost of moving an item by a character.
bool handle_spillable_contents (Character &c, item &it, map &m)
If character is handling a potentially spillable bucket, gracefully handle what to do with the contents.
Enumeration Type Documentation
from_where
enum pickup::from_where : int
Enumerator
from_cargo
from_ground
prompt
Definition at line 27 of file pickup.h.
                : int {
    from_cargo = 0,
    from_ground,
    prompt
};
Function Documentation
calculate_parents()
static std::vector< cata::optional< size_t > > pickup::calculate_parents (const std::vector< std::list< item_stack::iterator > > & stacked_here) static
Definition at line 448 of file pickup.cpp.
{
    std::vector<cata::optional<size_t>> parents( stacked_here.size() );
    if( !stacked_here.empty() ) {
        size_t last_parent_index = 0;
        item_drop_token last_parent_token = *stacked_here.front().front()->drop_token;
        for( size_t i = 1; i < stacked_here.size(); i++ ) {
            auto item_iter = stacked_here[i].front();
            const item_drop_token &this_token = *item_iter->drop_token;
            if( this_token.is_child_of( last_parent_token ) ) {
                parents[i] = last_parent_index;
            } else {
                last_parent_token = this_token;
                last_parent_index = i;
            }
        }
    }
    return parents;
}
References item_drop_token::is_child_of().
Referenced by pick_up().
cost_to_move_item()
int pickup::cost_to_move_item (const Character & who, const item & it)
Determines the cost of moving an item by a character.
Definition at line 1267 of file pickup.cpp.
{
    // Do not involve inventory capacity, it's not like you put it in backpack
    int ret = 50;
    if( who.is_armed() ) {
        // No free hand? That will cost you extra
        ret += 20;
    }
    const int delta_weight = units::to_gram( it.weight() - who.weight_capacity() );
    // Is it too heavy? It'll take 10 moves per kg over limit
    ret += std::max( 0, delta_weight / 100 );
    // Keep it sane - it's not a long activity
    return std::min( 400, ret );
}
References Character::is_armed(), cata::hash64_detail::ret, units::to_gram(), item::weight(), and Character::weight_capacity().
Referenced by move_items_activity_actor::do_turn(), find_auto_consume(), and move_cost_cart().
do_pickup()
bool pickup::do_pickup (std::vector< pick_drop_selection > & targets, bool autopickup)
Returns false if the player was presented a prompt and decided to cancel the pickup.
true in other cases.
Definition at line 404 of file pickup.cpp.
{
    bool got_water = false;
    Character &u = get_avatar();
    bool weight_was_okay = ( u.weight_carried() <= u.weight_capacity() );
    bool volume_was_okay = ( u.volume_carried() <= u.volume_capacity() );
    bool offered_swap = false;
    // Map of items picked up so we can output them all at the end and
    // merge dropping items with the same name.
    pickup_map map_pickup;
    bool problem = false;
    while( !problem && u.get_moves() >= 0 && !targets.empty() ) {
        pick_drop_selection current_target = std::move( targets.back() );
        // Whether we pick the item up or not, we're done trying to do so,
        // so remove it from the list.
        targets.pop_back();
        if( !current_target.target ) {
            debugmsg( "lost target item of ACT_PICKUP" );
            continue;
        }
        // TODO: This invocation is very ugly, should get a proper structure or something
        problem = !pick_one_up( current_target, got_water, offered_swap, map_pickup, autopickup );
    }
    if( !map_pickup.empty() ) {
        show_pickup_message( map_pickup );
    }
    if( got_water ) {
        add_msg( m_info, _( "You can't pick up a liquid!" ) );
    }
    if( weight_was_okay && u.weight_carried() > u.weight_capacity() ) {
        add_msg( m_bad, _( "You're overburdened!" ) );
    }
    if( volume_was_okay && u.volume_carried() > u.volume_capacity() ) {
        add_msg( m_bad, _( "You struggle to carry such a large volume!" ) );
    }
    return !problem;
}
References _, add_msg(), PATH_INFO::autopickup(), debugmsg, get_avatar(), Creature::get_moves(), m_bad, m_info, avatar_action::move(), pick_one_up(), show_pickup_message(), pickup::pick_drop_selection::target, Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), and Character::weight_carried().
Referenced by pickup_activity_actor::do_turn(), and select_autopickup_items().
flatten()
std::vector< std::list< item_stack::iterator > > pickup::flatten (const std::vector< stacked_items > & stacked)
Definition at line 554 of file pickup.cpp.
{
    std::vector<std::list<item_stack::iterator>> flat;
    for( const stacked_items &s : stacked ) {
        if( s.parent ) {
            flat.emplace_back( std::list<item_stack::iterator>( { *s.parent } ) );
        }
        flat.insert( flat.end(), s.stacked_children.begin(), s.stacked_children.end() );
    }
    return flat;
}
Referenced by pick_up().
handle_spillable_contents()
bool pickup::handle_spillable_contents (Character & c, item & it, map & m)
If character is handling a potentially spillable bucket, gracefully handle what to do with the contents.
Returns true if we handled the container, false if we chose to spill the contents and the container still needs to be put somewhere.
Parameters
c Character handling the spillable item
it item to handle
m map they are on
Definition at line 1238 of file pickup.cpp.
{
    if( it.is_bucket_nonempty() ) {
        const item &it_cont = it.contents.front();
        int num_charges = it_cont.charges;
        while( !it.spill_contents( c ) ) {
            if( num_charges > it_cont.charges ) {
                num_charges = it_cont.charges;
            } else {
                break;
            }
        }
        // If bucket is still not empty then player opted not to handle the
        // rest of the contents
        if( it.is_bucket_nonempty() ) {
            c.add_msg_player_or_npc(
                _( "To avoid spilling its contents, you set your %1$s on the %2$s." ),
                _( "To avoid spilling its contents, <npcname> sets their %1$s on the %2$s." ),
                it.display_name(), m.name( c.pos() )
            );
            m.add_item_or_charges( c.pos(), it );
            return true;
        }
    }
    return false;
}
References _, map::add_item_or_charges(), c, item::charges, item::contents, item::display_name(), item_contents::front(), item::is_bucket_nonempty(), map::name(), and item::spill_contents().
Referenced by player::consume(), and put_into_vehicle().
obtain_and_tokenize_items()
std::list< item > pickup::obtain_and_tokenize_items (player & p, std::list< act_item > & items)
Definition at line 590 of file activity_item_handling.cpp.
{
    std::list<item> res;
    drop_token_provider &token_provider = drop_token::get_provider();
    item_drop_token last_token = token_provider.make_next( calendar::turn );
    if( !try_rebuild_if_needed( items.front().loc ) ) {
        return res;
    }
    units::volume last_storage_volume = items.front().loc->get_storage();
    while( !items.empty() && ( p.is_npc() || p.moves > 0 || items.front().consumed_moves == 0 ) ) {
        act_item &ait = items.front();
        if( !try_rebuild_if_needed( ait.loc ) ) {
            debugmsg( "Lost target item of ACT_DROP" );
            items.pop_front();
            return res;
        }
        p.mod_moves( -ait.consumed_moves );
        if( p.is_worn( *ait.loc ) ) {
            if( !p.takeoff( *ait.loc, &res ) ) {
                // Skip item if failed to take it off
                debugmsg( "Failed to obtain worn target item of ACT_DROP" );
                items.pop_front();
                continue;
            }
        } else if( ait.loc->count_by_charges() ) {
            res.push_back( p.reduce_charges( const_cast<item *>( &*ait.loc ), ait.count ) );
        } else {
            res.push_back( p.i_rem( &*ait.loc ) );
        }
        // TODO: Get the item consistently instead of using back()
        item &current_drop = res.back();
        // Hack: if it consumes zero moves, it must have been contained
        // TODO: Properly mark containment somehow
        *current_drop.drop_token = token_provider.make_next( calendar::turn );;
        if( ait.consumed_moves == 0 && last_storage_volume >= current_drop.volume() ) {
            last_storage_volume -= current_drop.volume();
            current_drop.drop_token->parent_number = last_token.parent_number;
        } else {
            last_token = *current_drop.drop_token;
            last_storage_volume = current_drop.get_storage();
        }
        items.pop_front();
    }
    return res;
}
References pickup::act_item::consumed_moves, pickup::act_item::count, item::count_by_charges(), debugmsg, item::drop_token, drop_token::get_provider(), item::get_storage(), Character::i_rem(), player::is_npc(), Character::is_worn(), pickup::act_item::loc, drop_token_provider::make_next(), Creature::mod_moves(), Creature::moves, item_drop_token::parent_number, player::reduce_charges(), player::takeoff(), try_rebuild_if_needed(), calendar::turn, and item::volume().
Referenced by obtain_activity_items().
optimize_pickup()
std::vector< pick_drop_selection > pickup::optimize_pickup (const std::vector< item_location > & targets, const std::vector< int > & quantities)
Finds possible parent-child relations in picked up items to save moves.
Definition at line 1305 of file pickup.cpp.
{
    // This is essentially legacy code handling, so checks are good design
    if( targets.size() != quantities.size() ) {
        debugmsg( "Sizes of targets and quantity vectors don't match: %x != %x",
                  targets.size(), quantities.size() );
        return {};
    }
    item_drop_token last_token;
    std::vector<pick_drop_selection> optimized;
    for( size_t i = 0; i < targets.size(); i++ ) {
        const item_location &loc = targets[i];
        // If it was possible, the two locations should be required to be consecutive
        if( loc->drop_token->is_child_of( last_token ) ) {
            optimized.back().children.emplace_back( loc );
        } else {
            last_token = *loc->drop_token;
            cata::optional<int> q = quantities[i] != 0 ? quantities[i] : cata::optional<int>();
            optimized.push_back( {loc, q, {}} );
        }
    }
    return optimized;
}
References debugmsg, and item::drop_token.
Referenced by advanced_inventory::move_all_items(), and advanced_inventory::start_activity().
pick_up()
void pickup::pick_up (const tripoint & p, int min, from_where get_items_from = prompt)
Pick up items; 'g' or ',' or via examine()
Definition at line 571 of file pickup.cpp.
{
    int cargo_part = -1;
    const optional_vpart_position vp = g->m.veh_at( p );
    vehicle *const veh = veh_pointer_or_null( vp );
    bool from_vehicle = false;
    if( min != -1 ) {
        if( veh != nullptr && get_items_from == prompt ) {
            const cata::optional<vpart_reference> carg = vp.part_with_feature( "CARGO", false );
            const bool veh_has_items = carg && !veh->get_items( carg->part_index() ).empty();
            const bool map_has_items = g->m.has_items( p );
            if( veh_has_items && map_has_items ) {
                uilist amenu( _( "Get items from where?" ), { _( "Get items from vehicle cargo" ), _( "Get items on the ground" ) } );
                if( amenu.ret == UILIST_CANCEL ) {
                    return;
                }
                get_items_from = static_cast<from_where>( amenu.ret );
            } else if( veh_has_items ) {
                get_items_from = from_cargo;
            }
        }
        if( get_items_from == from_cargo ) {
            const cata::optional<vpart_reference> carg = vp.part_with_feature( "CARGO", false );
            cargo_part = carg ? carg->part_index() : -1;
            from_vehicle = cargo_part >= 0;
        } else {
            // Nothing to change, default is to pick from ground anyway.
            if( g->m.has_flag( "SEALED", p ) ) {
                return;
            }
        }
    }
    if( !from_vehicle ) {
        bool isEmpty = ( g->m.i_at( p ).empty() );
        // Hide the pickup window if this is a toilet and there's nothing here
        // but non-frozen water.
        if( ( !isEmpty ) && g->m.furn( p ) == f_toilet ) {
            isEmpty = true;
            for( const item &maybe_water : g->m.i_at( p ) ) {
                if( maybe_water.typeId() != itype_id( "water" ) ) {
                    isEmpty = false;
                    break;
                }
            }
        }
        if( isEmpty && ( min != -1 || !get_option<bool>( "AUTO_PICKUP_ADJACENT" ) ) ) {
            return;
        }
    }
    // which items are we grabbing?
    std::vector<item_stack::iterator> here;
    if( from_vehicle ) {
        vehicle_stack vehitems = veh->get_items( cargo_part );
        for( item_stack::iterator it = vehitems.begin(); it != vehitems.end(); ++it ) {
            here.push_back( it );
        }
    } else {
        map_stack mapitems = g->m.i_at( p );
        for( item_stack::iterator it = mapitems.begin(); it != mapitems.end(); ++it ) {
            here.push_back( it );
        }
    }
    if( min == -1 ) {
        // Recursively pick up adjacent items if that option is on.
        if( get_option<bool>( "AUTO_PICKUP_ADJACENT" ) && g->u.pos() == p ) {
            //Autopickup adjacent
            direction adjacentDir[8] = {direction::NORTH, direction::NORTHEAST, direction::EAST, direction::SOUTHEAST, direction::SOUTH, direction::SOUTHWEST, direction::WEST, direction::NORTHWEST};
            for( auto &elem : adjacentDir ) {
                tripoint apos = tripoint( direction_XY( elem ), 0 );
                apos += p;
                pick_up( apos, min );
            }
        }
        // Bail out if this square cannot be auto-picked-up
        if( g->check_zone( zone_type_id( "NO_AUTO_PICKUP" ), p ) ) {
            return;
        } else if( g->m.has_flag( "SEALED", p ) ) {
            return;
        }
    }
    // Not many items, just grab them
    if( static_cast<int>( here.size() ) <= min && min != -1 ) {
        if( from_vehicle ) {
            g->u.assign_activity( player_activity( pickup_activity_actor(
            { { item_location( vehicle_cursor( *veh, cargo_part ), &*here.front() ), cata::nullopt, {} } },
            cata::nullopt
                                                   ) ) );
        } else {
            g->u.assign_activity( player_activity( pickup_activity_actor(
            { { item_location( map_cursor( p ), &*here.front() ), cata::nullopt, {} } },
            g->u.pos()
                                                   ) ) );
        }
        return;
    }
    const std::vector<stacked_items> &stacked_here_new = stack_for_pickup_ui( here );
    // To avoid having to rewrite things.
    // TODO: Remove flattening
    const std::vector<std::list<item_stack::iterator>> &stacked_here = flatten( stacked_here_new );
    std::vector<pickup_count> getitem( stacked_here.size() );
    std::vector<cata::optional<size_t>> parents = calculate_parents( stacked_here );
    for( size_t i = 0; i < getitem.size(); i++ ) {
        getitem[i].parent = parents[i];
        if( parents[i] ) {
            getitem[*parents[i]].children.push_back( i );
        }
    }
    if( min == -1 ) { //Auto Pickup, select matching items
        if( !select_autopickup_items( stacked_here, getitem ) ) {
            // If we didn't find anything, bail out now.
            return;
        }
    } else {
        g->temp_exit_fullscreen();
        int start = 0;
        int selected = 0;
        int maxitems = 0;
        int pickupH = 0;
        int pickupW = 44;
        int pickupX = 0;
        catacurses::window w_pickup;
        catacurses::window w_item_info;
        ui_adaptor ui;
        ui.on_screen_resize( [&]( ui_adaptor & ui ) {
            const int itemsH = std::min( 25, TERMY / 2 );
            const int pickupBorderRows = 3;
            // The pickup list may consume the entire terminal, minus space needed for its
            // header/footer and the item info window.
            const int minleftover = itemsH + pickupBorderRows;
            const int maxmaxitems = TERMY - minleftover;
            const int minmaxitems = 9;
            maxitems = clamp<int>( stacked_here.size(), minmaxitems, maxmaxitems );
            start = selected - selected % maxitems;
            pickupH = maxitems + pickupBorderRows;
            //find max length of item name and resize pickup window width
            for( const std::list<item_stack::iterator> &cur_list : stacked_here ) {
                const item &this_item = *cur_list.front();
                const int item_len = utf8_width( remove_color_tags( this_item.display_name() ) ) + 10;
                if( item_len > pickupW && item_len < TERMX ) {
                    pickupW = item_len;
                }
            }
            pickupX = 0;
            std::string position = get_option<std::string>( "PICKUP_POSITION" );
            if( position == "left" ) {
                pickupX = panel_manager::get_manager().get_width_left();
            } else if( position == "right" ) {
                pickupX = TERMX - panel_manager::get_manager().get_width_right() - pickupW;
            } else if( position == "overlapping" ) {
                if( get_option<std::string>( "SIDEBAR_POSITION" ) == "right" ) {
                    pickupX = TERMX - pickupW;
                }
            }
            w_pickup = catacurses::newwin( pickupH, pickupW, point( pickupX, 0 ) );
            w_item_info = catacurses::newwin( TERMY - pickupH, pickupW,
                                              point( pickupX, pickupH ) );
            ui.position( point( pickupX, 0 ), point( pickupW, TERMY ) );
        } );
        ui.mark_resize();
        cata::optional<int> itemcount;
        std::string action;
        int raw_input_char = ' ';
        input_context ctxt( "PICKUP" );
        ctxt.register_action( "UP" );
        ctxt.register_action( "DOWN" );
        ctxt.register_action( "RIGHT" );
        ctxt.register_action( "LEFT" );
        ctxt.register_action( "NEXT_TAB", to_translation( "Next page" ) );
        ctxt.register_action( "PREV_TAB", to_translation( "Previous page" ) );
        ctxt.register_action( "SCROLL_UP" );
        ctxt.register_action( "SCROLL_DOWN" );
        ctxt.register_action( "CONFIRM" );
        ctxt.register_action( "SELECT_ALL" );
        ctxt.register_action( "QUIT", to_translation( "Cancel" ) );
        ctxt.register_action( "ANY_INPUT" );
        ctxt.register_action( "HELP_KEYBINDINGS" );
        ctxt.register_action( "FILTER" );
#if defined(__ANDROID__)
        ctxt.allow_text_entry = true; // allow user to specify pickup amount
#endif
        bool update = true;
        int iScrollPos = 0;
        std::string filter;
        std::string new_filter;
        // Indexes of items that match the filter
        std::vector<int> matches;
        bool filter_changed = true;
        units::mass weight_predict = 0_gram;
        units::volume volume_predict = 0_ml;
        const std::string all_pickup_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:;";
        ui.on_redraw( [&]( const ui_adaptor & ) {
            const item &selected_item = *stacked_here[matches[selected]].front();
            if( selected >= 0 && selected <= static_cast<int>( stacked_here.size() ) - 1 ) {
                std::vector<iteminfo> vThisItem;
                selected_item.info( true, vThisItem );
                item_info_data dummy( {}, {}, vThisItem, {}, iScrollPos );
                dummy.without_getch = true;
                dummy.without_border = true;
                draw_item_info( w_item_info, dummy );
            } else {
                werase( w_item_info );
                wnoutrefresh( w_item_info );
            }
            draw_custom_border( w_item_info, 0 );
            // print info window title: < item name >
            mvwprintw( w_item_info, point( 2, 0 ), "< " );
            trim_and_print( w_item_info, point( 4, 0 ), pickupW - 8, selected_item.color_in_inventory(),
                            selected_item.display_name() );
            wprintw( w_item_info, " >" );
            wnoutrefresh( w_item_info );
            const std::string pickup_chars = ctxt.get_available_single_char_hotkeys( all_pickup_chars );
            werase( w_pickup );
            for( int cur_it = start; cur_it < start + maxitems; cur_it++ ) {
                if( cur_it < static_cast<int>( matches.size() ) ) {
                    int true_it = matches[cur_it];
                    const item &this_item = *stacked_here[true_it].front();
                    nc_color icolor = this_item.color_in_inventory();
                    if( cur_it == selected ) {
                        icolor = hilite( c_white );
                    }
                    if( cur_it < static_cast<int>( pickup_chars.size() ) ) {
                        mvwputch( w_pickup, point( 0, 1 + ( cur_it % maxitems ) ), icolor,
                                  static_cast<char>( pickup_chars[cur_it] ) );
                    } else if( cur_it < static_cast<int>( pickup_chars.size() ) + static_cast<int>
                               ( pickup_chars.size() ) *
                               static_cast<int>( pickup_chars.size() ) ) {
                        int p = cur_it - pickup_chars.size();
                        int p1 = p / pickup_chars.size();
                        int p2 = p % pickup_chars.size();
                        mvwprintz( w_pickup, point( 0, 1 + ( cur_it % maxitems ) ), icolor, "`%c%c",
                                   static_cast<char>( pickup_chars[p1] ), static_cast<char>( pickup_chars[p2] ) );
                    } else {
                        mvwputch( w_pickup, point( 0, 1 + ( cur_it % maxitems ) ), icolor, ' ' );
                    }
                    if( getitem[true_it].parent ) {
                        const pickup_count &parent = getitem[*getitem[true_it].parent];
                        nc_color color = parent.pick ?
                                         ( parent.all_children_picked ? c_light_blue : c_yellow ) :
                                         c_dark_gray;
                        // TODO: Cute symbol here
                        wprintz( w_pickup, color, "\\" );
                    } else {
                        wprintw( w_pickup, " " );
                    }
                    if( getitem[true_it].pick ) {
                        if( getitem[true_it].count ) {
                            wprintz( w_pickup, c_light_blue, "# " );
                        } else {
                            wprintz( w_pickup, c_light_blue, "+ " );
                        }
                    } else {
                        wprintw( w_pickup, "- " );
                    }
                    std::string item_name;
                    if( stacked_here[true_it].front()->is_money() ) {
                        //Count charges
                        // TODO: transition to the item_location system used for the inventory
                        unsigned int charges_total = 0;
                        for( const item_stack::iterator &it : stacked_here[true_it] ) {
                            charges_total += it->charges;
                        }
                        //Picking up none or all the cards in a stack
                        if( !getitem[true_it].pick || !getitem[true_it].count ) {
                            item_name = stacked_here[true_it].front()->display_money( stacked_here[true_it].size(),
                                        charges_total );
                        } else {
                            unsigned int charges = 0;
                            int item_count = getitem[true_it].count ? *getitem[true_it].count : 0;
                            int c = item_count;
                            for( std::list<item_stack::iterator>::const_iterator it = stacked_here[true_it].begin();
                                 it != stacked_here[true_it].end() && c > 0; ++it, --c ) {
                                charges += ( *it )->charges;
                            }
                            item_name = stacked_here[true_it].front()->display_money( item_count, charges_total, charges );
                        }
                    } else {
                        item_name = this_item.display_name( stacked_here[true_it].size() );
                    }
                    if( stacked_here[true_it].size() > 1 ) {
                        item_name = string_format( "%d %s", stacked_here[true_it].size(), item_name );
                    }
                    if( get_option<bool>( "ITEM_SYMBOLS" ) ) {
                        item_name = string_format( "%s %s", this_item.symbol().c_str(),
                                                   item_name );
                    }
                    // if the item does not belong to your fraction then add the stolen symbol
                    if( !this_item.is_owned_by( g->u, true ) ) {
                        item_name = string_format( "<color_light_red>!</color> %s", item_name );
                    }
                    trim_and_print( w_pickup, point( 6, 1 + ( cur_it % maxitems ) ), pickupW - 4, icolor,
                                    item_name );
                }
            }
            mvwprintw( w_pickup, point( 0, maxitems + 1 ), _( "[%s] Unmark" ),
                       ctxt.get_desc( "LEFT", 1 ) );
            center_print( w_pickup, maxitems + 1, c_light_gray, string_format( _( "[%s] Help" ),
                          ctxt.get_desc( "HELP_KEYBINDINGS", 1 ) ) );
            right_print( w_pickup, maxitems + 1, 0, c_light_gray, string_format( _( "[%s] Mark" ),
                         ctxt.get_desc( "RIGHT", 1 ) ) );
            mvwprintw( w_pickup, point( 0, maxitems + 2 ), _( "[%s] Prev" ),
                       ctxt.get_desc( "PREV_TAB", 1 ) );
            center_print( w_pickup, maxitems + 2, c_light_gray, string_format( _( "[%s] All" ),
                          ctxt.get_desc( "SELECT_ALL", 1 ) ) );
            right_print( w_pickup, maxitems + 2, 0, c_light_gray, string_format( _( "[%s] Next" ),
                         ctxt.get_desc( "NEXT_TAB", 1 ) ) );
            const std::string fmted_weight_predict = colorize(
                        string_format( "%.1f", round_up( convert_weight( weight_predict ), 1 ) ),
                        weight_predict > g->u.weight_capacity() ? c_red : c_white );
            const std::string fmted_weight_capacity = string_format(
                        "%.1f", round_up( convert_weight( g->u.weight_capacity() ), 1 ) );
            const std::string fmted_volume_predict = colorize(
                        format_volume( volume_predict ),
                        volume_predict > g->u.volume_capacity() ? c_red : c_white );
            const std::string fmted_volume_capacity = format_volume( g->u.volume_capacity() );
            trim_and_print( w_pickup, point_zero, pickupW, c_white,
                            string_format( _( "PICK Wgt %1$s/%2$s  Vol %3$s/%4$s" ),
                                           fmted_weight_predict, fmted_weight_capacity,
                                           fmted_volume_predict, fmted_volume_capacity ) );
            wnoutrefresh( w_pickup );
        } );
        // Now print the two lists; those on the ground and about to be added to inv
        // Continue until we hit return or space
        do {
            const std::string pickup_chars = ctxt.get_available_single_char_hotkeys( all_pickup_chars );
            int idx = -1;
            if( action == "ANY_INPUT" &&
                raw_input_char >= '0' && raw_input_char <= '9' ) {
                int raw_input_char_value = static_cast<char>( raw_input_char ) - '0';
                if( !itemcount ) {
                    itemcount.emplace( 0 );
                }
                *itemcount *= 10;
                *itemcount += raw_input_char_value;
                if( *itemcount < 0 ) {
                    *itemcount = 0;
                }
                if( *itemcount == 0 ) {
                    itemcount.reset();
                }
            } else if( action == "SCROLL_UP" ) {
                iScrollPos--;
            } else if( action == "SCROLL_DOWN" ) {
                iScrollPos++;
            } else if( action == "PREV_TAB" ) {
                if( start > 0 ) {
                    start -= maxitems;
                } else {
                    start = static_cast<int>( ( matches.size() - 1 ) / maxitems ) * maxitems;
                }
                selected = start;
            } else if( action == "NEXT_TAB" ) {
                if( start + maxitems < static_cast<int>( matches.size() ) ) {
                    start += maxitems;
                } else {
                    start = 0;
                }
                iScrollPos = 0;
                selected = start;
            } else if( action == "UP" ) {
                selected--;
                iScrollPos = 0;
                if( selected < 0 ) {
                    selected = matches.size() - 1;
                    start = static_cast<int>( matches.size() / maxitems ) * maxitems;
                    if( start >= static_cast<int>( matches.size() ) ) {
                        start -= maxitems;
                    }
                } else if( selected < start ) {
                    start -= maxitems;
                }
            } else if( action == "DOWN" ) {
                selected++;
                iScrollPos = 0;
                if( selected >= static_cast<int>( matches.size() ) ) {
                    selected = 0;
                    start = 0;
                } else if( selected >= start + maxitems ) {
                    start += maxitems;
                }
            } else if( selected >= 0 && selected < static_cast<int>( matches.size() ) &&
                       ( ( action == "RIGHT" && !getitem[matches[selected]].pick ) ||
                         ( action == "LEFT" && getitem[matches[selected]].pick ) ) ) {
                idx = selected;
            } else if( action == "FILTER" ) {
                new_filter = filter;
                string_input_popup popup;
                popup
                .title( _( "Set filter" ) )
                .width( 30 )
                .edit( new_filter );
                if( !popup.canceled() ) {
                    filter_changed = true;
                }
            } else if( action == "ANY_INPUT" && raw_input_char == '`' ) {
                std::string ext = string_input_popup()
                                  .title( _( "Enter 2 letters (case sensitive):" ) )
                                  .width( 3 )
                                  .max_length( 2 )
                                  .query_string();
                if( ext.size() == 2 ) {
                    int p1 = pickup_chars.find( ext.at( 0 ) );
                    int p2 = pickup_chars.find( ext.at( 1 ) );
                    if( p1 != -1 && p2 != -1 ) {
                        idx = pickup_chars.size() + ( p1 * pickup_chars.size() ) + p2;
                    }
                }
            } else if( action == "ANY_INPUT" ) {
                idx = ( raw_input_char <= 127 ) ? pickup_chars.find( raw_input_char ) : -1;
                iScrollPos = 0;
            } else if( action == "SELECT_ALL" ) {
                int count = 0;
                for( auto i : matches ) {
                    if( getitem[i].pick ) {
                        count++;
                    }
                    getitem[i].pick = true;
                    getitem[i].count.reset();
                    // TODO: What about containers with children?
                    // TODO: Recalc all_children_picked
                }
                if( count == static_cast<int>( stacked_here.size() ) ) {
                    for( size_t i = 0; i < stacked_here.size(); i++ ) {
                        getitem[i].pick = false;
                        getitem[i].all_children_picked = false;
                    }
                }
                update = true;
            }
            if( idx >= 0 && idx < static_cast<int>( matches.size() ) ) {
                size_t true_idx = matches[idx];
                pickup_count &selected_stack = getitem[true_idx];
                if( itemcount || selected_stack.count ) {
                    const item &temp = *stacked_here[true_idx].front();
                    int amount_available = temp.count_by_charges() ? temp.charges : stacked_here[true_idx].size();
                    if( itemcount && *itemcount >= amount_available ) {
                        itemcount.reset();
                    }
                    selected_stack.count = itemcount;
                    itemcount.reset();
                }
                // Note: this might not change the value of getitem[idx] at all!
                selected_stack.pick = ( action == "RIGHT" ? true :
                                        ( action == "LEFT" ? false :
                                          !selected_stack.pick ) );
                if( action != "RIGHT" && action != "LEFT" ) {
                    selected = idx;
                    start = static_cast<int>( idx / maxitems ) * maxitems;
                }
                if( !selected_stack.pick ) {
                    selected_stack.count.reset();
                }
                selected_stack.all_children_picked = selected_stack.pick;
                for( size_t child_index : selected_stack.children ) {
                    pickup_count &child_stack = getitem[child_index];
                    child_stack.pick = selected_stack.pick;
                    child_stack.count.reset();
                }
                if( selected_stack.parent ) {
                    pickup_count &parent_stack = getitem[*selected_stack.parent];
                    if( selected_stack.pick ) {
                        parent_stack.all_children_picked = std::all_of(
                                                               parent_stack.children.begin(), parent_stack.children.end(),
                        [&]( size_t child_index ) {
                            return getitem[child_index].pick;
                        } );
                    } else {
                        parent_stack.all_children_picked = false;
                    }
                }
                update = true;
            }
            if( filter_changed ) {
                matches.clear();
                while( matches.empty() ) {
                    auto filter_func = item_filter_from_string( new_filter );
                    for( size_t index = 0; index < stacked_here.size(); index++ ) {
                        if( filter_func( *stacked_here[index].front() ) ) {
                            matches.push_back( index );
                        }
                    }
                    if( matches.empty() ) {
                        popup( _( "Your filter returned no results" ) );
                        // The filter must have results, or simply be emptied or canceled,
                        // as this screen can't be reached without there being
                        // items available
                        string_input_popup popup;
                        popup
                        .title( _( "Set filter" ) )
                        .width( 30 )
                        .edit( new_filter );
                        if( popup.canceled() ) {
                            new_filter = filter;
                            filter_changed = false;
                        }
                    }
                }
                if( filter_changed ) {
                    filter = new_filter;
                    filter_changed = false;
                    selected = 0;
                    start = 0;
                    iScrollPos = 0;
                }
            }
            if( update ) { // Update weight & volume information
                update = false;
                units::mass weight_picked_up = 0_gram;
                units::volume volume_picked_up = 0_ml;
                for( size_t i = 0; i < getitem.size(); i++ ) {
                    if( getitem[i].pick ) {
                        // Make a copy for calculating weight/volume
                        item temp = *stacked_here[i].front();
                        if( temp.count_by_charges() && getitem[i].count && *getitem[i].count < temp.charges ) {
                            temp.charges = *getitem[i].count;
                        }
                        int num_picked = std::min( stacked_here[i].size(),
                                                   getitem[i].count ? *getitem[i].count : stacked_here[i].size() );
                        weight_picked_up += temp.weight() * num_picked;
                        volume_picked_up += temp.volume() * num_picked;
                    }
                }
                weight_predict = g->u.weight_carried() + weight_picked_up;
                volume_predict = g->u.volume_carried() + volume_picked_up;
            }
            ui_manager::redraw();
            action = ctxt.handle_input();
            raw_input_char = ctxt.get_raw_input().get_first_input();
        } while( action != "QUIT" && action != "CONFIRM" );
        bool item_selected = false;
        // Check if we have selected an item.
        for( const pickup_count &selection : getitem ) {
            if( selection.pick ) {
                item_selected = true;
            }
        }
        if( action != "CONFIRM" || !item_selected ) {
            add_msg( _( "Never mind." ) );
            g->reenter_fullscreen();
            return;
        }
    }
    // At this point we've selected our items, register an activity to pick them up.
    std::vector<std::pair<item_stack::iterator, int>> pick_values;
    for( size_t i = 0; i < stacked_here.size(); i++ ) {
        const pickup_count &selection = getitem[i];
        if( !selection.pick ) {
            continue;
        }
        const std::list<item_stack::iterator> &stack = stacked_here[i];
        // Note: items can be both charged and stacked
        // For robustness, let's assume they can be both in the same stack
        int count = selection.count ? *selection.count : 0;
        for( const item_stack::iterator &it : stack ) {
            if( selection.count && count == 0 ) {
                break;
            }
            if( it->count_by_charges() ) {
                int num_picked = std::min( it->charges, count );
                pick_values.emplace_back( it, num_picked );
                count -= num_picked;
            } else {
                pick_values.emplace_back( it, 0 );
                --count;
            }
        }
    }
    std::vector<item_location> locations;
    std::vector<int> quantities;
    for( std::pair<item_stack::iterator, int> &iter_qty : pick_values ) {
        item_location loc;
        if( from_vehicle ) {
            loc = item_location( vehicle_cursor( *veh, cargo_part ), &*iter_qty.first );
        } else {
            loc = item_location( map_cursor( p ), &*iter_qty.first );
        }
        locations.push_back( loc );
        quantities.push_back( iter_qty.second );
    }
    std::vector<pickup::pick_drop_selection> targets = pickup::optimize_pickup( locations, quantities );
    g->u.assign_activity( player_activity( pickup_activity_actor( targets, g->u.pos() ) ) );
    if( min == -1 ) {
        // Auto pickup will need to auto resume since there can be several of them on the stack.
        g->u.activity.auto_resume = true;
    }
    g->reenter_fullscreen();
}
References _, action, add_msg(), pickup_count::all_children_picked, item_stack::begin(), c, c_dark_gray, c_light_blue, c_light_gray, c_red, c_white, c_yellow, calculate_parents(), center_print(), item::charges, pickup_count::children, color(), item::color_in_inventory(), colorize(), convert_weight(), detail::count(), pickup_count::count, item::count_by_charges(), direction_XY(), item::display_name(), draw_custom_border(), draw_item_info(), EAST, item_stack::empty(), item_stack::end(), f_toilet, flatten(), format_volume(), from_cargo, g, input_context::get_available_single_char_hotkeys(), input_context::get_desc(), vehicle::get_items(), panel_manager::get_manager(), panel_manager::get_width_left(), panel_manager::get_width_right(), hilite(), item::is_owned_by(), item_filter_from_string(), string_input_popup::max_length(), catacurses::mvwprintw(), mvwprintz(), mvwputch(), catacurses::newwin(), NORTH, NORTHEAST, NORTHWEST, cata::nullopt, pickup_count::parent, visitable< T >::parents(), optional_vpart_position::part_with_feature(), pickup_count::pick, pick_up(), point_zero, popup(), prompt, string_input_popup::query_string(), ui_manager::redraw(), input_context::register_action(), remove_color_tags(), right_print(), round_up(), select_autopickup_items(), om_direction::size, SOUTH, SOUTHEAST, SOUTHWEST, stack_for_pickup_ui(), string_format(), item::symbol(), TERMX, TERMY, string_input_popup::title(), to_translation(), trim_and_print(), UILIST_CANCEL, utf8_width(), veh_pointer_or_null(), item::volume(), item::weight(), catacurses::werase(), WEST, string_input_popup::width(), catacurses::wnoutrefresh(), catacurses::wprintw(), and wprintz().
Referenced by game::examine(), iexamine::fireplace(), vehicle::interact_with(), pick_up(), game::pickup(), game::pickup_feet(), and game::place_player().
query_thief()
bool pickup::query_thief ()
Definition at line 186 of file pickup.cpp.
{
    player &u = g->u;
    const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
    const auto &allow_key = force_uc ? input_context::disallow_lower_case
                            : input_context::allow_all_keys;
    std::string answer = query_popup()
                         .allow_cancel( false )
                         .context( "YES_NO_ALWAYS_NEVER" )
                         .message( "%s", force_uc
                                   ? _( "Picking up this item will be considered stealing, continue?  (Case sensitive)" )
                                   : _( "Picking up this item will be considered stealing, continue?" ) )
                         .option( "YES", allow_key ) // yes, steal all items in this location that is selected
                         .option( "NO", allow_key ) // no, pick up only what is free
                         .option( "ALWAYS", allow_key ) // Yes, steal all items and stop asking me this question
                         .option( "NEVER", allow_key ) // no, only grab free item and never ask me again
                         .cursor( 1 ) // default to the second option `NO`
                         .query()
                         .action; // retrieve the input action
    if( answer == "YES" ) {
        u.set_value( "THIEF_MODE", "THIEF_STEAL" );
        u.set_value( "THIEF_MODE_KEEP", "NO" );
        return true;
    } else if( answer == "NO" ) {
        u.set_value( "THIEF_MODE", "THIEF_HONEST" );
        u.set_value( "THIEF_MODE_KEEP", "NO" );
        return false;
    } else if( answer == "ALWAYS" ) {
        u.set_value( "THIEF_MODE", "THIEF_STEAL" );
        u.set_value( "THIEF_MODE_KEEP", "YES" );
        return true;
    } else if( answer == "NEVER" ) {
        u.set_value( "THIEF_MODE", "THIEF_HONEST" );
        u.set_value( "THIEF_MODE_KEEP", "YES" );
        return false;
    } else {
        // error
        debugmsg( "Not a valid option [ %s ]", answer );
    }
    return false;
}
References _, query_popup::result::action, input_context::allow_all_keys, query_popup::allow_cancel(), query_popup::context(), query_popup::cursor(), debugmsg, input_context::disallow_lower_case, g, query_popup::message(), query_popup::option(), query_popup::query(), and Creature::set_value().
Referenced by pick_one_up(), and query_consume_ownership().
reorder_for_dropping()
std::list< act_item > pickup::reorder_for_dropping (Character & p, const drop_locations & drop)
Definition at line 458 of file activity_item_handling.cpp.
{
    std::list<act_item> res = convert_to_items( p, drop,
    [&p]( item_location loc ) {
        return p.is_wielding( *loc );
    } );
    std::list<act_item> inv = convert_to_items( p, drop,
    [&p]( item_location loc ) {
        return !p.is_wielding( *loc ) && !p.is_worn( *loc );
    } );
    std::list<act_item> worn = convert_to_items( p, drop,
    [&p]( item_location loc ) {
        return p.is_worn( *loc );
    } );
    // Sort inventory items by volume in ascending order
    inv.sort( []( const act_item & first, const act_item & second ) {
        return first.loc->volume() < second.loc->volume();
    } );
    // Add missing dependent worn items (if any).
    for( const auto &wait : worn ) {
        for( item *dit : p.get_dependent_worn_items( *wait.loc ) ) {
            const auto iter = std::find_if( worn.begin(), worn.end(),
            [dit]( const act_item & ait ) {
                return &*ait.loc == dit;
            } );
            if( iter == worn.end() ) {
                // TODO: Use a calculated cost
                const item_location loc( p, dit );
                act_item act( loc, loc->count(), loc.obtain_cost( p, loc->count() ) );
                worn.emplace_front( loc, loc->count(), loc.obtain_cost( p ) );
            }
        }
    }
    // Sort worn items by storage in descending order, but dependent items always go first.
    worn.sort( []( const act_item & first, const act_item & second ) {
        return first.loc->is_worn_only_with( *second.loc )
               || ( first.loc->get_storage() > second.loc->get_storage()
                    && !second.loc->is_worn_only_with( *first.loc ) );
    } );
    // Avoid tumbling to the ground. Unload cleanly.
    units::volume dropped_inv_contents = std::accumulate( inv.begin(), inv.end(), 0_ml,
    []( units::volume acc, const act_item & ait ) {
        return acc + ait.loc->volume();
    } );
    const units::volume dropped_worn_storage = std::accumulate( worn.begin(), worn.end(), 0_ml,
    []( units::volume acc, const act_item & ait ) {
        return acc + ait.loc->get_storage();
    } );
    std::set<int> inv_indices;
    std::transform( inv.begin(), inv.end(), std::inserter( inv_indices, inv_indices.begin() ),
    [&p]( const act_item & ait ) {
        return p.get_item_position( &*ait.loc );
    } );
    units::volume excessive_volume = p.volume_carried() - dropped_inv_contents
                                     - p.volume_capacity_reduced_by( dropped_worn_storage );
    if( excessive_volume > 0_ml ) {
        invslice old_inv = p.inv.slice();
        for( size_t i = 0; i < old_inv.size() && excessive_volume > 0_ml; i++ ) {
            // TODO: Reimplement random dropping?
            if( inv_indices.count( i ) != 0 ) {
                continue;
            }
            std::list<item> &inv_stack = *old_inv[i];
            for( item &item : inv_stack ) {
                // Note: zero cost, but won't be contained on drop
                act_item to_drop = act_item( item_location( p, &item ), item.count(), 0 );
                inv.push_back( to_drop );
                excessive_volume -= to_drop.loc->volume();
                if( excessive_volume <= 0_ml ) {
                    break;
                }
            }
        }
        // Need to re-sort
        inv.sort( []( const act_item & first, const act_item & second ) {
            return first.loc->volume() < second.loc->volume();
        } );
    }
    // Cumulatively decreases
    units::volume remaining_dropped_storage = dropped_worn_storage;
    while( !worn.empty() && !inv.empty() ) {
        units::volume front_storage = worn.front().loc->get_storage();
        // Does not fit
        // TODO: but maybe an item further down the line does
        if( remaining_dropped_storage < inv.front().loc->volume() ) {
            break;
        }
        res.push_back( worn.front() );
        worn.pop_front();
        remaining_dropped_storage -= front_storage;
        while( !inv.empty() ) {
            units::volume inventory_item_volume = inv.front().loc->volume();
            if( front_storage < inventory_item_volume ) {
                break;
            }
            front_storage -= inventory_item_volume;
            res.push_back( inv.front() );
            // Free of charge
            res.back().consumed_moves = 0;
            inv.pop_front();
        }
    }
    // Now insert everything that remains
    std::copy( inv.begin(), inv.end(), std::back_inserter( res ) );
    std::copy( worn.begin(), worn.end(), std::back_inserter( res ) );
    return res;
}
References act, convert_to_items(), item::count(), Character::get_dependent_worn_items(), item::get_storage(), Character::inv, Character::is_wielding(), Character::is_worn(), item::is_worn_only_with(), pickup::act_item::loc, item_location::obtain_cost(), second, inventory::slice(), iexamine::transform(), item::volume(), Character::volume_capacity_reduced_by(), Character::volume_carried(), and wait().
Referenced by drop_activity_actor::drop_activity_actor(), and stash_activity_actor::stash_activity_actor().
stack_for_pickup_ui()
std::vector< stacked_items > pickup::stack_for_pickup_ui (const std::vector< item_stack::iterator > & unstacked)
Definition at line 480 of file pickup.cpp.
{
    const std::pair<time_point, int> no_parent = std::make_pair(
                calendar::before_time_starts, 0 );
    std::map<std::pair<time_point, int>, parent_child_check_t> parent_child_check;
    // First, we need to check which parent-child groups exist
    for( item_stack::iterator it : unstacked ) {
        const auto &token = *it->drop_token;
        if( token.drop_number > 0 ) {
            std::pair<time_point, int> turn_and_drop = std::make_pair( token.turn, token.drop_number );
            parent_child_check[turn_and_drop].parent_exists = true;
        }
        if( token.parent_number != token.drop_number && token.parent_number > 0 ) {
            std::pair<time_point, int> turn_and_parent = std::make_pair( token.turn, token.parent_number );
            parent_child_check[turn_and_parent].child_exists = true;
        }
    }
    // Second pass: we group children and parents together, but only if both sides are known to exist
    std::map<std::pair<time_point, int>, unstacked_items> children_by_parent;
    for( item_stack::iterator it : unstacked ) {
        const auto &token = *it->drop_token;
        std::pair<time_point, int> turn_and_drop = std::make_pair( token.turn, token.drop_number );
        if( token.drop_number > 0 && parent_child_check[turn_and_drop].child_exists ) {
            children_by_parent[turn_and_drop].parent = it;
            continue;
        }
        std::pair<time_point, int> turn_and_parent = std::make_pair( token.turn, token.parent_number );
        if( token.parent_number > 0 && token.parent_number != token.drop_number &&
            parent_child_check[turn_and_parent].parent_exists ) {
            children_by_parent[turn_and_parent].unstacked_children.push_back( it );
        } else {
            children_by_parent[no_parent].unstacked_children.push_back( it );
        }
    }
    std::vector<stacked_items> restacked_with_parents;
    for( const auto &pr : children_by_parent ) {
        std::vector<std::list<item_stack::iterator>> restacked_children;
        for( item_stack::iterator it : pr.second.unstacked_children ) {
            bool found_stack = false;
            for( std::list<item_stack::iterator> &stack : restacked_children ) {
                const item &stack_top = *stack.front();
                if( stack_top.display_stacked_with( *it ) ) {
                    stack.push_back( it );
                    found_stack = true;
                    break;
                }
            }
            if( !found_stack ) {
                restacked_children.emplace_back( std::list<item_stack::iterator>( { it } ) );
            }
        }
        // Each sub-stack has to be sorted separately
        std::sort( restacked_children.begin(), restacked_children.end(),
        []( const std::list<item_stack::iterator> &lhs, const std::list<item_stack::iterator> &rhs ) {
            return *lhs.front() < *rhs.front();
        } );
        restacked_with_parents.emplace_back( stacked_items{ pr.second.parent, restacked_children } );
    }
    // Sorting by parent is a bit arbitrary (parent-less go last) - sort by count?
    std::sort( restacked_with_parents.begin(), restacked_with_parents.end(),
    []( const stacked_items & lhs, stacked_items & rhs ) {
        return lhs.parent.has_value() && ( !rhs.parent.has_value() || *lhs.parent < *rhs.parent );
    } );
    return restacked_with_parents;
}
References calendar::before_time_starts, item::display_stacked_with(), and pickup::stacked_items::parent.
Referenced by pick_up().
try_rebuild_if_needed()
static bool pickup::try_rebuild_if_needed (item_location & loc) static
Definition at line 577 of file activity_item_handling.cpp.
{
    if( loc ) {
        return true;
    }
    loc.make_dirty();
    if( !loc ) {
        debugmsg( "Lost target item of ACT_DROP and couldn't rebuild item_location!" );
    }
    return static_cast<bool>( loc );
}
References debugmsg, and item_location::make_dirty().
Referenced by obtain_and_tokenize_items().