var namespacecata__variant__detail =
[
    [ "convert", "structcata__variant__detail_1_1convert.html", null ],
    [ "convert< cata_variant_type::add_type >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1add__type_01_4.html", null ],
    [ "convert< cata_variant_type::bionic_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1bionic__id_01_4.html", null ],
    [ "convert< cata_variant_type::body_part >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1body__part_01_4.html", null ],
    [ "convert< cata_variant_type::bool_ >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1bool___01_4.html", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1bool___01_4" ],
    [ "convert< cata_variant_type::character_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1character__id_01_4.html", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1character__id_01_4" ],
    [ "convert< cata_variant_type::character_movemode >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1character__movemode_01_4.html", null ],
    [ "convert< cata_variant_type::efftype_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1efftype__id_01_4.html", null ],
    [ "convert< cata_variant_type::hp_part >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1hp__part_01_4.html", null ],
    [ "convert< cata_variant_type::int_ >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1int___01_4.html", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1int___01_4" ],
    [ "convert< cata_variant_type::itype_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1itype__id_01_4.html", null ],
    [ "convert< cata_variant_type::matype_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1matype__id_01_4.html", null ],
    [ "convert< cata_variant_type::mtype_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mtype__id_01_4.html", null ],
    [ "convert< cata_variant_type::mutagen_technique >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mutagen__technique_01_4.html", null ],
    [ "convert< cata_variant_type::mutation_category_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mutation__category__id_01_4.html", null ],
    [ "convert< cata_variant_type::oter_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1oter__id_01_4.html", null ],
    [ "convert< cata_variant_type::skill_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1skill__id_01_4.html", null ],
    [ "convert< cata_variant_type::species_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1species__id_01_4.html", null ],
    [ "convert< cata_variant_type::spell_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1spell__id_01_4.html", null ],
    [ "convert< cata_variant_type::string >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1string_01_4.html", null ],
    [ "convert< cata_variant_type::ter_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1ter__id_01_4.html", null ],
    [ "convert< cata_variant_type::trait_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1trait__id_01_4.html", null ],
    [ "convert< cata_variant_type::trap_str_id >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1trap__str__id_01_4.html", null ],
    [ "convert< cata_variant_type::void_ >", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1void___01_4.html", "structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1void___01_4" ],
    [ "convert_enum", "structcata__variant__detail_1_1convert__enum.html", "structcata__variant__detail_1_1convert__enum" ],
    [ "convert_int_id", "structcata__variant__detail_1_1convert__int__id.html", "structcata__variant__detail_1_1convert__int__id" ],
    [ "convert_string", "structcata__variant__detail_1_1convert__string.html", "structcata__variant__detail_1_1convert__string" ],
    [ "convert_string_id", "structcata__variant__detail_1_1convert__string__id.html", "structcata__variant__detail_1_1convert__string__id" ],
    [ "type_for", "namespacecata__variant__detail.html#abe34c52ddc3072a83f18c8e2cded7bfe", null ],
    [ "type_for_impl", "namespacecata__variant__detail.html#aae4d595dd9f6f3122dd80ecfbbb12796", null ]
];