Cataclysm BN: debug_menu::anonymous_namespace{wisheffect.cpp} Namespace Reference
debug_menu::anonymous_namespace{wisheffect.cpp} Namespace Reference
Classes
struct entry_data
Functions
template<class T , typename F = std::pair<const std::string, void (T::*)(const input_context &, const input_event &, int, uilist &)>>
void register_callback (uilist &menu, T &callback)
void foreach_effect (Creature &c, const entry_data &entry, const std::function< void(const effect &)> &fun)
cata::optional< bodypart_str_id > query_body_part (Creature &c)
cata::optional< int > query_intensity ()
cata::optional< time_duration > try_read_time_string (const std::string &ts)
cata::optional< time_duration > query_duration ()
bool toggle_effect_force ()
Function Documentation
foreach_effect()
void debug_menu::anonymous_namespace{wisheffect.cpp}::foreach_effect (Creature & c, const entry_data & entry, const std::function< void(const effect &)> & fun)
Definition at line 53 of file wisheffect.cpp.
{
    if( entry.eff ) {
        fun( **entry.eff );
    } else {
        // Body part, so apply to all effects on it
        for( const auto &pr : c.get_all_effects() ) {
            for( const std::pair<const bodypart_str_id, effect> &inner : pr.second ) {
                if( inner.first == entry.body_part ) {
                    fun( inner.second );
                }
            }
        }
    }
}
References debug_menu::anonymous_namespace{wisheffect.cpp}::entry_data::body_part, c, and debug_menu::anonymous_namespace{wisheffect.cpp}::entry_data::eff.
Referenced by debug_menu::effect_edit_callback::change_body_part(), debug_menu::effect_edit_callback::change_duration(), debug_menu::effect_edit_callback::change_intensity(), and debug_menu::effect_edit_callback::remove().
query_body_part()
cata::optional< bodypart_str_id > debug_menu::anonymous_namespace{wisheffect.cpp}::query_body_part (Creature & c)
Definition at line 71 of file wisheffect.cpp.
{
    wisheffect_state &last_val = uistate.debug_menu.effect;
    const std::vector<bodypart_id> &all_bps = c.get_all_body_parts();
    uilist menu;
    size_t i = 0;
    for( const bodypart_id &bp : all_bps ) {
        menu.addentry( i++, true, -1, bp.id().str() );
    }
    menu.query();
    if( menu.ret >= 0 && menu.ret < static_cast<int>( all_bps.size() ) ) {
        last_val.bodypart = all_bps[static_cast<size_t>( menu.ret )].id();
    } else {
        return cata::nullopt;
    }
    return last_val.bodypart;
}
References uilist::addentry(), wisheffect_state::bodypart, c, uistatedata::debug_menu, debug_menu_state::effect, cata::nullopt, uilist::query(), uilist::ret, and uistate.
Referenced by debug_menu::effect_edit_callback::change_body_part(), and debug_menu::effect_select_callback::change_body_part().
query_duration()
cata::optional< time_duration > debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration ()
Definition at line 120 of file wisheffect.cpp.
{
    wisheffect_state &last_val = uistate.debug_menu.effect;
    string_input_popup popup;
    popup.title( _( "Input new duration followed by unit (s, m, h, d)" ) );
    std::string dur_string = popup.query_string();
    if( !popup.confirmed() ) {
        return cata::nullopt;
    }
    cata::optional<time_duration> dur = try_read_time_string( dur_string );
    if( dur ) {
        last_val.duration = *dur;
        return dur;
    } else {
        return cata::nullopt;
    }
}
References _, uistatedata::debug_menu, wisheffect_state::duration, debug_menu_state::effect, cata::nullopt, popup(), try_read_time_string(), and uistate.
Referenced by debug_menu::effect_edit_callback::change_duration(), and debug_menu::effect_select_callback::change_duration().
query_intensity()
cata::optional< int > debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity ()
Definition at line 88 of file wisheffect.cpp.
{
    wisheffect_state &last_val = uistate.debug_menu.effect;
    try {
        last_val.intensity = string_input_popup()
                             .title( _( "Input new intensity" ) )
                             .only_digits( true )
                             .query_int();
    } catch( std::exception & ) {
        return cata::nullopt;
    }
    return last_val.intensity;
}
References _, uistatedata::debug_menu, debug_menu_state::effect, wisheffect_state::intensity, cata::nullopt, string_input_popup::only_digits(), string_input_popup::query_int(), string_input_popup::title(), and uistate.
Referenced by debug_menu::effect_edit_callback::change_intensity(), and debug_menu::effect_select_callback::change_intensity().
register_callback()
template<class T , typename F = std::pair<const std::string, void (T::*)(const input_context &, const input_event &, int, uilist &)>> void debug_menu::anonymous_namespace{wisheffect.cpp}::register_callback (uilist & menu, T & callback)
Definition at line 45 of file wisheffect.cpp.
{
    menu.callback = &callback;
    for( const F &action : T::get_handled_actions() ) {
        menu.additional_actions.emplace_back( action.first, translation() );
    }
}
References action, uilist::additional_actions, and uilist::callback.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), and debug_menu::effect_edit_menu().
toggle_effect_force()
bool debug_menu::anonymous_namespace{wisheffect.cpp}::toggle_effect_force ()
Definition at line 137 of file wisheffect.cpp.
{
    uistate.debug_menu.effect.force = !uistate.debug_menu.effect.force;
    return uistate.debug_menu.effect.force;
}
References uistatedata::debug_menu, debug_menu_state::effect, wisheffect_state::force, and uistate.
Referenced by debug_menu::effect_select_callback::toggle_force(), and debug_menu::effect_edit_callback::toggle_force().
try_read_time_string()
cata::optional< time_duration > debug_menu::anonymous_namespace{wisheffect.cpp}::try_read_time_string (const std::string & ts)
Definition at line 101 of file wisheffect.cpp.
{
    // Ugly hack, but does the job (it's debug anyway)
    // Have to wrap it in quotes because we're reading a raw string
    const std::string quoted_ts = '"' + ts + '"';
    try {
        std::istringstream iss( quoted_ts );
        JsonIn jsin( iss );
        return read_from_json_string<time_duration>( jsin, time_duration::units );
    } catch( const JsonError &e ) {
        // Try unit-less conversion
        try {
            return time_duration::from_turns( std::stoi( ts ) );
        } catch( std::exception & ) {
        }
        popup( e.c_str() );
        return cata::nullopt;
    }
}
References JsonError::c_str(), time_duration::from_turns(), cata::nullopt, popup(), and time_duration::units.
Referenced by query_duration().