Cataclysm BN: catacurses Namespace Reference
catacurses Namespace Reference
Contains the curses interface used by the whole game.
Classes
class window
A wrapper over a pointer to a curses window.
Typedefs
using chtype = int
using attr_t = unsigned short
Enumerations
enum base_color : short {
black = 0x00 , red = 0x01 , green = 0x02 , yellow = 0x03 ,
blue = 0x04 , magenta = 0x05 , cyan = 0x06 , white = 0x07
}
Functions
void init_interface ()
window newwin (int nlines, int ncols, const point &begin)
void wborder (const window &win, chtype ls, chtype rs, chtype ts, chtype bs, chtype tl, chtype tr, chtype bl, chtype br)
void mvwhline (const window &win, const point &p, chtype ch, int n)
void mvwvline (const window &win, const point &p, chtype ch, int n)
void wnoutrefresh (const window &win)
void wrefresh (const window &win)
void refresh ()
void doupdate ()
void wredrawln (const window &win, int beg_line, int num_lines)
void mvwprintw (const window &win, const point &p, const std::string &text)
template<typename ... Args>
void mvwprintw (const window &win, const point &p, const char *const fmt, Args &&... args)
void wprintw (const window &win, const std::string &text)
template<typename ... Args>
void wprintw (const window &win, const char *const fmt, Args &&... args)
void resizeterm ()
void werase (const window &win)
void init_pair (short pair, base_color f, base_color b)
void wmove (const window &win, const point &p)
void clear ()
void erase ()
void endwin ()
void mvwaddch (const window &win, const point &p, chtype ch)
void wclear (const window &win)
void curs_set (int visibility)
void wattron (const window &win, const nc_color &attrs)
void wattroff (const window &win, int attrs)
void waddch (const window &win, chtype ch)
int getmaxy (const window &win)
int getmaxx (const window &win)
int getbegx (const window &win)
int getbegy (const window &win)
int getcurx (const window &win)
int getcury (const window &win)
Variables
window stdscr
Detailed Description
Contains the curses interface used by the whole game.
All code (except platform/OS/build type specific code) should use functions/ types from this namespace only. The input_manager and input_context should be used for user input.
There are currently (Nov 2017) two implementations for most of this interface:
ncurses (mostly in ncurses_def.cpp). The interface originates from there, so it's mostly just forwarding to ncurses functions of the same name.
our own curses library cata_cursesport (mostly in cursesport.cpp), cursesport.h contains the structures and some functions specific to that.
A few (system specific) functions are implemented in three versions:
ncurses (ncurses_def.cpp),
Windows curses (no SDL, using cata_cursesport, see wincurses.cpp), and
SDL curses (using cata_cursesport, see sdltiles.cpp).
As this interface is derived from ncurses, refer to documentation of that.
The interface is in a separate namespace we can link with the ncurses library, which exports its functions globally.
Typedef Documentation
attr_t
using catacurses::attr_t = typedef unsigned short
Definition at line 90 of file cursesdef.h.
chtype
typedef int catacurses::chtype
Definition at line 89 of file cursesdef.h.
Enumeration Type Documentation
base_color
enum catacurses::base_color : short
Enumerator
black
red
green
yellow
blue
magenta
cyan
white
Definition at line 78 of file cursesdef.h.
                : short {
    black = 0x00,    // RGB{0, 0, 0}
    red = 0x01,      // RGB{196, 0, 0}
    green = 0x02,    // RGB{0, 196, 0}
    yellow = 0x03,   // RGB{196, 180, 30}
    blue = 0x04,     // RGB{0, 0, 196}
    magenta = 0x05,  // RGB{196, 0, 180}
    cyan = 0x06,     // RGB{0, 170, 200}
    white = 0x07,    // RGB{196, 196, 196}
};
Function Documentation
clear()
void catacurses::clear ()
Definition at line 130 of file ncurses_def.cpp.
{
    return curses_check_result( ::clear(), OK, "clear" );
}
References clear(), and curses_check_result().
Referenced by cata::list< element_type, element_allocator_type >::assign(), clear(), auto_pickup::rule_list::deserialize(), cata::list< element_type, element_allocator_type >::group_vector::destroy_all_data(), cata::list< element_type, element_allocator_type >::erase(), inventory_iuse_selector::execute(), detail::iterator_buffer< OutputIt, T, Traits >::flush(), inventory_column::move_entries_to(), cata::list< element_type, element_allocator_type >::operator=(), inventory_drop_selector::process_selected(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), and cata::list< element_type, element_allocator_type >::resize().
curs_set()
void catacurses::curs_set (int visibility)
Definition at line 185 of file ncurses_def.cpp.
{
    return curses_check_result( ::curs_set( visibility ), OK, "curs_set" );
}
References curs_set(), and curses_check_result().
Referenced by curs_set(), and main().
doupdate()
void catacurses::doupdate ()
Definition at line 125 of file ncurses_def.cpp.
{
    return curses_check_result( ::doupdate(), OK, "doupdate" );
}
References curses_check_result(), and doupdate().
Referenced by doupdate(), input_manager::get_input_event(), and refresh_display().
endwin()
void catacurses::endwin ()
Definition at line 140 of file ncurses_def.cpp.
{
    return curses_check_result( ::endwin(), OK, "endwin" );
}
References curses_check_result(), and endwin().
Referenced by endwin(), and exit_handler().
erase()
void catacurses::erase ()
Definition at line 135 of file ncurses_def.cpp.
{
    return curses_check_result( ::erase(), OK, "erase" );
}
References curses_check_result(), and erase().
Referenced by background_pane::background_pane(), check_encoding(), debug_error_prompt(), ensure_term_size(), erase(), cata::list< element_type, element_allocator_type >::erase(), cata::list< element_type, element_allocator_type >::pop_back(), cata::list< element_type, element_allocator_type >::pop_front(), cata::list< element_type, element_allocator_type >::remove_if(), cata::list< element_type, element_allocator_type >::resize(), cata::flat_set< T, Compare, Data >::sort_data(), and cata::list< element_type, element_allocator_type >::unique().
getbegx()
int catacurses::getbegx (const window & win)
Definition at line 68 of file ncurses_def.cpp.
{
    return ::getbegx( win.get<::WINDOW>() );
}
References catacurses::window::get(), and getbegx().
Referenced by veh_interact::do_change_shape(), veh_interact::do_install(), border_helper::draw_border(), input_context::get_coordinates(), getbegx(), ui_adaptor::position_from_window(), string_input_popup::show_history(), and show_scores_ui().
getbegy()
int catacurses::getbegy (const window & win)
Definition at line 73 of file ncurses_def.cpp.
{
    return ::getbegy( win.get<::WINDOW>() );
}
References catacurses::window::get(), and getbegy().
Referenced by veh_interact::display_grid(), veh_interact::do_change_shape(), veh_interact::do_install(), border_helper::draw_border(), input_context::get_coordinates(), getbegy(), ui_adaptor::position_from_window(), string_input_popup::show_history(), and show_scores_ui().
getcurx()
int catacurses::getcurx (const window & win)
Definition at line 78 of file ncurses_def.cpp.
{
    return ::getcurx( win.get<::WINDOW>() );
}
References catacurses::window::get(), and getcurx().
Referenced by getcurx().
getcury()
int catacurses::getcury (const window & win)
Definition at line 83 of file ncurses_def.cpp.
{
    return ::getcury( win.get<::WINDOW>() );
}
References catacurses::window::get(), and getcury().
Referenced by getcury().
getmaxx()
int catacurses::getmaxx (const window & win)
Definition at line 58 of file ncurses_def.cpp.
{
    return ::getmaxx( win.get<::WINDOW>() );
}
References catacurses::window::get(), and getmaxx().
Referenced by dialogue_window::cache_msg(), game::calc_driving_offset(), veh_interact::calc_overview(), veh_interact::can_remove_part(), center_print(), check_encoding(), editmap::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), create_zone_callback(), debug_error_prompt(), decorate_panel(), player_morale::display(), veh_interact::display_details(), veh_interact::display_esc(), veh_interact::display_grid(), veh_interact::display_list(), veh_interact::display_overview(), dialogue_window::display_responses(), veh_interact::display_stats(), veh_interact::display_veh(), veh_interact::do_change_shape(), veh_interact::do_install(), veh_interact::do_repair(), map::draw(), Creature::draw(), scent_map::draw(), draw_armor(), draw_armor_padding(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), border_helper::draw_border(), draw_border_below_tabs(), draw_borders_external(), draw_borders_internal(), overmap_ui::draw_camp_labels(), talk_function::draw_camp_tabs(), overmap_ui::draw_city_labels(), inventory_selector::draw_columns(), draw_cone_aoe_curses(), draw_custom_border(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), draw_description(), draw_effects_tab(), draw_env_compact(), draw_exam_window(), inventory_selector::draw_footer(), inventory_selector::draw_frame(), draw_grid(), draw_header(), inventory_selector::draw_header(), target_ui::draw_help_notice(), draw_item_filter_rules(), draw_item_info(), anonymous_namespace{animation.cpp}::draw_line_curses(), draw_loc_labels(), draw_location_classic(), help::draw_menu(), draw_messages(), draw_messages_classic(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), advanced_inventory::draw_minimap(), worldfactory::draw_mod_list(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), draw_points(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_tabs(), draw_traits_tab(), target_ui::draw_ui_window(), draw_weapon_classic(), draw_weapon_classic_alt(), draw_weapon_labels(), target_ui::draw_window_title(), map::drawsq(), ensure_term_size(), basecamp::faction_display(), faction::faction_display(), npc::faction_display(), veh_interact::format_reqs(), generate_weather_anim_frame(), input_context::get_coordinates(), getmaxx(), game_ui::init_ui(), insert_table(), game::is_in_viewport(), game::list_missions(), game::mon_info(), target_ui::panel_cursor_info(), target_ui::panel_spell_info(), worldfactory::pick_world(), ui_adaptor::position_from_window(), player::power_bionics(), character_display::print_encumbrance(), game::print_fields_info(), game::print_graffiti_info(), advanced_inventory::print_header(), dialogue_window::print_header(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), game::print_items_info(), print_keybindings(), main_menu::print_menu(), main_menu::print_menu_items(), vehicle::print_part_list(), print_ranged_chance(), print_responses(), print_scrollable(), print_steadiness(), game::print_terrain_info(), game::print_vehicle_info(), advanced_inventory::redraw_pane(), wish_monster_callback::refresh(), game::reset_item_list_state(), inventory_selector::resize_window(), resizeterm(), right_print(), scrollable_text(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), uilist::show(), robot_finds_kitten::show(), options_manager::show(), color_manager::show_gui(), worldfactory::show_modselection_window(), show_mutations_titlebar(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), scrolling_text_view::text_width(), editmap::uber_draw_ter(), veh_interact::update_part_requirements(), editmap::update_view_with_help(), trading_window::update_win(), and computer_session::use().
getmaxy()
int catacurses::getmaxy (const window & win)
Definition at line 63 of file ncurses_def.cpp.
{
    return ::getmaxy( win.get<::WINDOW>() );
}
References catacurses::window::get(), and getmaxy().
Referenced by game::calc_driving_offset(), editmap::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), create_zone_callback(), advanced_inventory::display(), veh_interact::display_grid(), veh_interact::display_overview(), dialogue_window::display_responses(), veh_interact::display_stats(), veh_interact::display_veh(), map::draw(), Creature::draw(), scent_map::draw(), scrolling_text_view::draw(), draw_bionics_tabs(), border_helper::draw_border(), draw_border_below_tabs(), draw_borders_external(), overmap_ui::draw_camp_labels(), overmap_ui::draw_city_labels(), inventory_selector::draw_columns(), draw_cone_aoe_curses(), target_ui::draw_controls_list(), draw_custom_border(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), draw_description(), inventory_selector::draw_footer(), draw_grid(), target_ui::draw_help_notice(), draw_item_info(), anonymous_namespace{animation.cpp}::draw_line_curses(), draw_messages(), draw_messages_classic(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), advanced_inventory::draw_minimap(), worldfactory::draw_mod_list(), overmap_ui::draw_om_sidebar(), draw_recipe_tabs(), target_ui::draw_ui_window(), map::drawsq(), ensure_term_size(), fold_and_print_from(), generate_weather_anim_frame(), input_context::get_coordinates(), getmaxy(), game_ui::init_ui(), insert_table(), game::is_in_viewport(), ma_style_callback::key(), game::list_monsters(), game::look_around(), scrolling_text_view::max_offset(), game::mon_info(), main_menu::new_character_tab(), scrolling_text_view::page_down(), scrolling_text_view::page_up(), ui_adaptor::position_from_window(), character_display::print_encumbrance(), dialogue_window::print_header(), dialogue_window::print_history(), print_keybindings(), main_menu::print_menu(), print_scrollable(), advanced_inventory::redraw_pane(), wish_monster_callback::refresh(), inventory_selector::resize_window(), resizeterm(), scrollable_text(), set_description(), set_profession(), set_scenario(), live_view::show(), worldfactory::show_modselection_window(), show_scores_ui(), editmap::uber_draw_ter(), editmap::update_view_with_help(), and computer_session::use().
init_interface()
void catacurses::init_interface ()
Exceptions
std::exception upon any errors. The caller should display / log it and abort the program. Only continue the program when this returned normally.
Definition at line 229 of file ncurses_def.cpp.
{
    // ::endwin will free the pointer returned by ::initscr
    stdscr = std::shared_ptr<void>( ::initscr(), []( void *const ) { } );
    if( !stdscr ) {
        throw std::runtime_error( "initscr failed" );
    }
#if !defined(__CYGWIN__)
    // ncurses mouse registration
    mousemask( BUTTON1_CLICKED | BUTTON3_CLICKED | REPORT_MOUSE_POSITION, nullptr );
#endif
    // our curses wrapper does not support changing this behavior, ncurses must
    // behave exactly like the wrapper, therefor:
    noecho();  // Don't echo keypresses
    cbreak();  // C-style breaks (e.g. ^C to SIGINT)
    keypad( stdscr.get<::WINDOW>(), true ); // Numpad is numbers
    set_escdelay( 10 ); // Make Escape actually responsive
    // TODO: error checking
    start_color();
    init_colors();
}
References catacurses::window::get(), init_colors(), and stdscr.
Referenced by main().
init_pair()
void catacurses::init_pair (short pair, base_color f, base_color b)
Definition at line 209 of file ncurses_def.cpp.
{
    return curses_check_result( ::init_pair( pair, static_cast<short>( f ), static_cast<short>( b ) ),
                                OK, "init_pair" );
}
References b, curses_check_result(), and init_pair().
Referenced by init_colors(), init_pair(), and inv_internal().
mvwaddch()
void catacurses::mvwaddch (const window & win, const point & p, chtype ch)
Definition at line 164 of file ncurses_def.cpp.
{
    return curses_check_result( ::mvwaddch( win.get<::WINDOW>(), p.y, p.x, ch ), OK, "mvwaddch" );
}
References curses_check_result(), catacurses::window::get(), mvwaddch(), point::x, and point::y.
Referenced by draw_rectangle(), mvwaddch(), mvwputch(), mvwputch_hi(), mvwputch_inv(), Messages::dialog::show(), and iexamine::vending().
mvwhline()
void catacurses::mvwhline (const window & win, const point & p, chtype ch, int n)
Definition at line 152 of file ncurses_def.cpp.
{
    return curses_check_result( ::mvwhline( win.get<::WINDOW>(), p.y, p.x, ch, n ), OK,
                                "mvwhline" );
}
References curses_check_result(), catacurses::window::get(), mvwhline(), point::x, and point::y.
Referenced by player_morale::display(), veh_interact::display_stats(), talk_function::draw_camp_tabs(), draw_connectors(), draw_exam_window(), inventory_selector::draw_frame(), draw_grid(), draw_header(), inventory_selector::draw_header(), draw_recipe_tabs(), mvwhline(), player::power_mutations_ui(), wish_item_callback::refresh(), and iexamine::vending().
mvwprintw() [1/2]
template<typename ... Args> void catacurses::mvwprintw (const window & win, const point & p, const char *const fmt, Args &&... args) inline
Definition at line 106 of file cursesdef.h.
{
    return mvwprintw( win, p, string_format( fmt, std::forward<Args>( args )... ) );
}
References mvwprintw(), and string_format().
mvwprintw() [2/2]
void catacurses::mvwprintw (const window & win, const point & p, const std::string & text)
Definition at line 103 of file ncurses_def.cpp.
{
    return curses_check_result( ::mvwprintw( win.get<::WINDOW>(), p.y, p.x, "%s", text.c_str() ),
                                OK, "mvwprintw" );
}
References curses_check_result(), catacurses::window::get(), mvwprintw(), point::x, and point::y.
Referenced by inventory_column::draw(), string_input_popup::draw(), game::list_items(), game::list_monsters(), mvwprintw(), mvwprintz(), mvwputch(), mvwputch_hi(), mvwputch_inv(), target_ui::panel_fire_mode_aim(), target_ui::panel_target_info(), target_ui::panel_turret_list(), pickup::pick_up(), game::print_all_tile_info(), Character::print_info(), game::print_items_info(), print_ranged_chance(), print_steadiness(), game::print_terrain_info(), game::print_vehicle_info(), game::print_visibility_info(), advanced_inventory::redraw_pane(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), editmap::update_view_with_help(), trading_window::update_win(), and iexamine::vending().
mvwvline()
void catacurses::mvwvline (const window & win, const point & p, chtype ch, int n)
Definition at line 158 of file ncurses_def.cpp.
{
    return curses_check_result( ::mvwvline( win.get<::WINDOW>(), p.y, p.x, ch, n ), OK,
                                "mvwvline" );
}
References curses_check_result(), catacurses::window::get(), mvwvline(), point::x, and point::y.
Referenced by draw_connectors(), draw_grid(), mvwvline(), dialogue_window::print_header(), and panel_manager::show_adm().
newwin()
catacurses::window catacurses::newwin (int nlines, int ncols, const point & begin)
Definition at line 34 of file ncurses_def.cpp.
{
    // TODO: check for errors
    const auto w = ::newwin( nlines, ncols, begin.y, begin.x );
    return std::shared_ptr<void>( w, []( void *const w ) {
        ::curses_check_result( ::delwin( static_cast<::WINDOW *>( w ) ), OK, "delwin" );
    } );
}
References curses_check_result(), newwin(), point::x, and point::y.
Referenced by advanced_inventory::action_examine(), veh_interact::allocate_windows(), defense_game::caravan(), game::cleanup_at_end(), game_menus::inv::compare(), Character::conduct_blood_analysis(), overmap_ui::create_note(), game::create_or_get_main_ui_adaptor(), editmap::create_or_get_ui_adaptor(), string_input_popup::create_window(), character_display::disp_info(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), input_context::display_menu(), main_menu::display_text(), draw_item_info(), game::draw_panels(), worldfactory::edit_active_world_mods(), game::extended_description(), query_popup::init(), Messages::dialog::init(), init_window(), target_ui::init_window_and_input(), main_menu::init_windows(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), worldfactory::make_new_world(), overmap_ui::map_notes_callback::map_notes_callback(), new_centered_win(), newwin(), pickup::pick_up(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), player::power_bionics(), player::power_mutations_ui(), loot_options::query_loot(), wish_monster_callback::refresh(), dialogue_window::resize_dialogue(), inventory_selector::resize_window(), robot_finds_kitten::robot_finds_kitten(), examine_item_menu::run(), overmap_ui::search(), select_crafting_recipe(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), defense_game::setup(), uilist::setup(), trading_window::setup_win(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), computer_session::use(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
refresh()
void catacurses::refresh ()
Definition at line 115 of file ncurses_def.cpp.
{
    return curses_check_result( ::refresh(), OK, "refresh" );
}
References curses_check_result(), and refresh().
Referenced by check_encoding(), debug_error_prompt(), vehicle::deserialize(), ensure_term_size(), game::handle_key_blocking_activity(), and refresh().
resizeterm()
void catacurses::resizeterm ()
Definition at line 217 of file ncurses_def.cpp.
{
    const int new_x = ::getmaxx( stdscr.get<::WINDOW>() );
    const int new_y = ::getmaxy( stdscr.get<::WINDOW>() );
    if( ::is_term_resized( new_x, new_y ) ) {
        game_ui::init_ui();
        ui_manager::screen_resized();
    }
}
References catacurses::window::get(), getmaxx(), getmaxy(), game_ui::init_ui(), ui_manager::screen_resized(), and stdscr.
Referenced by input_manager::get_input_event().
waddch()
void catacurses::waddch (const window & win, chtype ch)
Definition at line 169 of file ncurses_def.cpp.
{
    return curses_check_result( ::waddch( win.get<::WINDOW>(), ch ), OK, "waddch" );
}
References curses_check_result(), catacurses::window::get(), and waddch().
Referenced by waddch(), and wputch().
wattroff()
void catacurses::wattroff (const window & win, int attrs)
Definition at line 88 of file ncurses_def.cpp.
{
    return curses_check_result( ::wattroff( win.get<::WINDOW>(), attrs ), OK, "wattroff" );
}
References curses_check_result(), catacurses::window::get(), and wattroff().
Referenced by draw_border(), draw_custom_border(), insert_table(), mvwprintz(), mvwputch(), mvwputch_hi(), mvwputch_inv(), advanced_inventory::redraw_pane(), Messages::dialog::show(), wattroff(), wprintz(), and wputch().
wattron()
void catacurses::wattron (const window & win, const nc_color & attrs)
Definition at line 93 of file ncurses_def.cpp.
{
    return curses_check_result( ::wattron( win.get<::WINDOW>(), attrs ), OK, "wattron" );
}
References curses_check_result(), catacurses::window::get(), and wattron().
Referenced by draw_border(), draw_custom_border(), insert_table(), mvwprintz(), mvwputch(), mvwputch_hi(), mvwputch_inv(), advanced_inventory::redraw_pane(), Messages::dialog::show(), wattron(), wprintz(), and wputch().
wborder()
void catacurses::wborder (const window & win, chtype ls, chtype rs, chtype ts, chtype bs, chtype tl, chtype tr, chtype bl, chtype br)
Definition at line 145 of file ncurses_def.cpp.
{
    return curses_check_result( ::wborder( win.get<::WINDOW>(), ls, rs, ts, bs, tl, tr, bl, br ), OK,
                                "wborder" );
}
References curses_check_result(), catacurses::window::get(), and wborder().
Referenced by veh_interact::display_details(), draw_border(), iexamine::vending(), and wborder().
wclear()
void catacurses::wclear (const window & win)
Definition at line 180 of file ncurses_def.cpp.
{
    return curses_check_result( ::wclear( win.get<::WINDOW>() ), OK, "wclear" );
}
References curses_check_result(), catacurses::window::get(), and wclear().
Referenced by draw_item_info(), set_description(), and wclear().
werase()
void catacurses::werase (const window & win)
Definition at line 53 of file ncurses_def.cpp.
{
    return curses_check_result( ::werase( win.get<::WINDOW>() ), OK, "werase" );
}
References curses_check_result(), catacurses::window::get(), and werase().
Referenced by dialogue_window::clear_window_texts(), veh_interact::create_or_get_ui_adaptor(), decorate_panel(), game::disp_NPCs(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), veh_interact::display_details(), veh_interact::display_list(), input_context::display_menu(), veh_interact::display_mode(), veh_interact::display_name(), veh_interact::display_overview(), veh_interact::display_stats(), veh_interact::display_veh(), game::draw(), scrolling_text_view::draw(), overmap_ui::draw(), char_creation::draw_age(), draw_ai_goal(), draw_armor(), draw_armor_padding(), draw_bionics_info(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), talk_function::draw_camp_tabs(), draw_char_narrow(), draw_char_wide(), draw_compass(), draw_compass_padding(), draw_description(), draw_effects_info(), draw_effects_tab(), draw_encumbrance_info(), draw_encumbrance_tab(), draw_env_compact(), draw_health_classic(), char_creation::draw_height(), draw_hint(), draw_item_info(), lightson_game::draw_level(), draw_lighting_classic(), draw_limb2(), draw_limb_narrow(), draw_limb_wide(), draw_loc_labels(), draw_location_classic(), help::draw_menu(), draw_messages(), draw_messages_classic(), game::draw_minimap(), worldfactory::draw_mod_list(), draw_moon_narrow(), draw_moon_wide(), draw_needs_compact(), draw_needs_labels(), draw_needs_narrow(), game::draw_panels(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_skills_info(), draw_skills_tab(), draw_sound_labels(), draw_sound_narrow(), draw_speed_tab(), draw_stat_narrow(), draw_stat_wide(), draw_stats(), draw_stats_info(), draw_stats_tab(), draw_stealth(), draw_time(), draw_time_classic(), draw_tip(), draw_traits_info(), draw_traits_tab(), draw_veh_compact(), draw_veh_padding(), draw_weapon_classic(), draw_weapon_classic_alt(), draw_weapon_labels(), draw_weather_classic(), draw_weightvolume_classic(), draw_weightvolume_compact(), draw_weightvolume_labels(), draw_weightvolume_narrow(), worldfactory::draw_worldgen_tabs(), game::extended_description(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_missions(), game::list_monsters(), game::look_around(), pickup::pick_up(), player::power_bionics(), player::power_mutations_ui(), print_mana(), main_menu::print_menu(), vehicle::print_vparts_descs(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), computer_session::refresh(), wish_monster_callback::refresh(), defense_game::refresh_setup(), inventory_selector::refresh_window(), render_wind(), scrollable_text(), select_crafting_recipe(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), Messages::dialog::show(), uilist::show(), robot_finds_kitten::show(), query_popup::show(), options_manager::show(), live_view::show(), panel_manager::show_adm(), trading_window::show_item_data(), worldfactory::show_modselection_window(), show_mutations_titlebar(), show_scores_ui(), snake_game::snake_over(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), trading_window::update_win(), iexamine::vending(), werase(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_shortcuts().
wmove()
void catacurses::wmove (const window & win, const point & p)
Definition at line 98 of file ncurses_def.cpp.
{
    return curses_check_result( ::wmove( win.get<::WINDOW>(), p.y, p.x ), OK, "wmove" );
}
References curses_check_result(), catacurses::window::get(), wmove(), point::x, and point::y.
Referenced by map::draw(), overmap_ui::draw_ascii(), draw_health_classic(), draw_limb2(), draw_limb_narrow(), game::draw_ter(), draw_time(), draw_time_classic(), map::drawsq(), fold_and_print_from(), worldfactory::pick_world(), print_colored_text(), select_crafting_recipe(), shortcut_print(), robot_finds_kitten::show(), worldfactory::show_modselection_window(), wmove(), and main_menu::world_tab().
wnoutrefresh()
void catacurses::wnoutrefresh (const window & win)
Definition at line 43 of file ncurses_def.cpp.
{
    return curses_check_result( ::wnoutrefresh( win.get<::WINDOW>() ), OK, "wnoutrefresh" );
}
References curses_check_result(), catacurses::window::get(), and wnoutrefresh().
Referenced by background_pane::background_pane(), Character::conduct_blood_analysis(), veh_interact::create_or_get_ui_adaptor(), character_display::disp_info(), game::disp_NPCs(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), veh_interact::display_details(), veh_interact::display_grid(), help::display_help(), veh_interact::display_list(), veh_interact::display_mode(), veh_interact::display_name(), veh_interact::display_overview(), dialogue_window::display_responses(), veh_interact::display_stats(), main_menu::display_text(), veh_interact::display_veh(), game::draw(), scrolling_text_view::draw(), overmap_ui::draw(), string_input_popup::draw(), char_creation::draw_age(), draw_ai_goal(), draw_armor(), draw_armor_padding(), overmap_ui::draw_ascii(), draw_bionics_info(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), draw_borders_external(), draw_borders_internal(), talk_function::draw_camp_tabs(), draw_caravan_borders(), draw_caravan_categories(), draw_caravan_items(), draw_char_narrow(), draw_char_wide(), draw_compass(), draw_compass_padding(), draw_description(), draw_effects_info(), draw_effects_tab(), draw_encumbrance_info(), draw_encumbrance_tab(), draw_env_compact(), draw_grid(), draw_header(), draw_health_classic(), char_creation::draw_height(), draw_hint(), draw_item_filter_rules(), draw_item_info(), lightson_game::draw_level(), draw_lighting_classic(), draw_limb2(), draw_limb_narrow(), draw_limb_wide(), draw_loc_labels(), draw_location_classic(), help::draw_menu(), draw_messages(), draw_messages_classic(), game::draw_minimap(), worldfactory::draw_mod_list(), worldfactory::draw_modselection_borders(), draw_moon_narrow(), draw_moon_wide(), draw_needs_compact(), draw_needs_labels(), draw_needs_narrow(), overmap_ui::draw_om_sidebar(), game::draw_panels(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_skills_info(), draw_skills_tab(), draw_sound_labels(), draw_sound_narrow(), draw_speed_tab(), query_destination_callback::draw_squares(), draw_stat_narrow(), draw_stat_wide(), draw_stats(), draw_stats_info(), draw_stats_tab(), draw_stealth(), draw_time(), draw_time_classic(), draw_tip(), draw_traits_info(), draw_traits_tab(), target_ui::draw_ui_window(), draw_veh_compact(), draw_veh_padding(), draw_weapon_classic(), draw_weapon_classic_alt(), draw_weapon_labels(), draw_weather_classic(), draw_weightvolume_classic(), draw_weightvolume_compact(), draw_weightvolume_labels(), draw_weightvolume_narrow(), worldfactory::edit_active_world_mods(), game::extended_description(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_missions(), game::list_monsters(), main_menu::load_character_tab(), game::look_around(), worldfactory::make_new_world(), main_menu::new_character_tab(), main_menu::opening_screen(), pickup::pick_up(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), player::power_bionics(), player::power_mutations_ui(), print_mana(), main_menu::print_menu(), vehicle::print_vparts_descs(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), computer_session::refresh(), spellcasting_callback::refresh(), spellbook_callback::refresh(), teleporter_callback::refresh(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), debug_menu::effect_select_callback::refresh(), advanced_inventory::refresh_minimap(), defense_game::refresh_setup(), inventory_selector::refresh_window(), render_wind(), scrollable_text(), overmap_ui::search(), select_crafting_recipe(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), Messages::dialog::show(), uilist::show(), robot_finds_kitten::show(), query_popup::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), show_mutations_titlebar(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), snake_game::snake_over(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), trading_window::update_win(), iexamine::vending(), wnoutrefresh(), basecamp::worker_assignment_ui(), main_menu::world_tab(), game::zones_manager(), zones_manager_draw_borders(), and zones_manager_shortcuts().
wprintw() [1/2]
template<typename ... Args> void catacurses::wprintw (const window & win, const char *const fmt, Args &&... args) inline
Definition at line 114 of file cursesdef.h.
{
    return wprintw( win, string_format( fmt, std::forward<Args>( args )... ) );
}
References string_format(), and wprintw().
wprintw() [2/2]
void catacurses::wprintw (const window & win, const std::string & text)
Definition at line 109 of file ncurses_def.cpp.
{
    return curses_check_result( ::wprintw( win.get<::WINDOW>(), "%s", text.c_str() ),
                                OK, "wprintw" );
}
References curses_check_result(), catacurses::window::get(), and wprintw().
Referenced by game::list_items(), game::list_monsters(), pickup::pick_up(), monster::print_info(), sokoban_game::print_score(), wprintw(), and wprintz().
wredrawln()
void catacurses::wredrawln (const window & win, int beg_line, int num_lines)
Definition at line 174 of file ncurses_def.cpp.
{
    return curses_check_result( ::wredrawln( win.get<::WINDOW>(), beg_line, num_lines ), OK,
                                "wredrawln" );
}
References curses_check_result(), catacurses::window::get(), and wredrawln().
Referenced by Messages::display_messages(), and wredrawln().
wrefresh()
void catacurses::wrefresh (const window & win)
Definition at line 48 of file ncurses_def.cpp.
{
    return curses_check_result( ::wrefresh( win.get<::WINDOW>() ), OK, "wrefresh" );
}
References curses_check_result(), catacurses::window::get(), and wrefresh().
Referenced by wrefresh().
Variable Documentation
stdscr
catacurses::window catacurses::stdscr extern
Definition at line 215 of file ncurses_def.cpp.
Referenced by background_pane::background_pane(), check_encoding(), game::create_or_get_main_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), debug_error_prompt(), overmap_ui::display(), ensure_term_size(), init_interface(), game_ui::init_ui(), and resizeterm().