Cataclysm BN: Name Namespace Reference
Name Namespace Reference
Typedefs
using names_vec = std::vector< decltype(names.cbegin()) >
Functions
static nameFlags usage_flag (const std::string &usage)
static nameFlags gender_flag (const std::string &gender)
static void load (JsonIn &jsin)
void load_from_file (const std::string &filename)
Load names from given json file to use for generation.
static names_vec get_matching_groups (nameFlags searchFlags)
std::string get (nameFlags searchFlags)
Return a random name given search flags.
std::string generate (bool is_male)
Return a random full name given gender.
void clear ()
Clear names used for generation.
Variables
static std::map< nameFlags, std::vector< std::string > > names
static const std::map< std::string, nameFlags > usage_flags
static const std::map< std::string, nameFlags > gender_flags
Typedef Documentation
names_vec
using Name::names_vec = typedef std::vector< decltype(names.cbegin()) >
Definition at line 89 of file name.cpp.
Function Documentation
clear()
void Name::clear ()
Clear names used for generation.
Definition at line 150 of file name.cpp.
{
    names.clear();
}
References names.
Referenced by reload_names().
gender_flag()
static nameFlags Name::gender_flag (const std::string & gender) static
Definition at line 45 of file name.cpp.
{
    const auto it = gender_flags.find( gender );
    if( it != gender_flags.end() ) {
        return it->second;
    }
    return static_cast< nameFlags >( 0 );
}
References gender_flags.
Referenced by load().
generate()
std::string Name::generate (bool is_male)
Return a random full name given gender.
Definition at line 128 of file name.cpp.
{
    const nameFlags baseSearchFlags = is_male ? nameIsMaleName : nameIsFemaleName;
    //One in twenty chance to pull from the backer list, otherwise generate a name from the parts list
    if( one_in( 20 ) ) {
        return get( baseSearchFlags | nameIsFullName );
    } else {
        //~ Used for constructing full name: %1$s is `given name`, %2$s is `family name`
        translation full_name_format = to_translation( "Full Name", "%1$s %2$s" );
        //One in three chance to add a nickname to full name
        if( one_in( 3 ) ) {
            //~ Used for constructing full name with nickname: %1$s is `given name`, %2$s is `family name`, %3$s is `nickname`
            full_name_format = to_translation( "Full Name", "%1$s '%3$s' %2$s" );
        }
        return string_format( full_name_format,
                              get( baseSearchFlags | nameIsGivenName ).c_str(),
                              get( baseSearchFlags | nameIsFamilyName ).c_str(),
                              get( nameIsNickName ).c_str()
                            );
    }
}
References get(), nameIsFamilyName, nameIsFemaleName, nameIsFullName, nameIsGivenName, nameIsMaleName, nameIsNickName, one_in(), string_format(), and to_translation().
Referenced by mattack::nurse_assist(), mattack::photograph(), Character::pick_name(), and Character::suffer_from_schizophrenia().
get()
std::string Name::get (nameFlags searchFlags)
Return a random name given search flags.
Definition at line 103 of file name.cpp.
{
    auto matching_groups = get_matching_groups( searchFlags );
    if( !matching_groups.empty() ) {
        // get number of choices
        size_t nChoices = 0;
        for( const auto &i : matching_groups ) {
            const auto &group = i->second;
            nChoices += group.size();
        }
        // make random selection and return result.
        size_t choice = rng( 0, nChoices - 1 );
        for( const auto &i : matching_groups ) {
            const auto &group = i->second;
            if( choice < group.size() ) {
                return group[choice];
            }
            choice -= group.size();
        }
    }
    // BUG, no matching name found.
    return std::string( _( "Tom" ) );
}
References _, get_matching_groups(), and rng().
Referenced by generate(), get_next_valid_worldname(), mission_start::place_zombie_mom(), and replace_name_tags().
get_matching_groups()
static names_vec Name::get_matching_groups (nameFlags searchFlags) static
Definition at line 90 of file name.cpp.
{
    names_vec matching_groups;
    for( auto it = names.cbegin(), end = names.cend(); it != end; ++it ) {
        const nameFlags type = it->first;
        if( ( searchFlags & type ) == searchFlags ) {
            matching_groups.push_back( it );
        }
    }
    return matching_groups;
}
References names, and type.
Referenced by get().
load()
static void Name::load (JsonIn & jsin) static
Definition at line 63 of file name.cpp.
{
    jsin.start_array();
    while( !jsin.end_array() ) {
        JsonObject jo = jsin.get_object();
        // get flags of name.
        const nameFlags type =
            usage_flag( jo.get_string( "usage" ) )
            | gender_flag( jo.get_string( "gender", "" ) );
        // find group type and add name to group
        names[type].push_back( jo.get_string( "name" ) );
    }
}
References JsonIn::end_array(), gender_flag(), JsonIn::get_object(), JsonObject::get_string(), names, JsonIn::start_array(), type, and usage_flag().
Referenced by load_from_file().
load_from_file()
void Name::load_from_file (const std::string & filename)
Load names from given json file to use for generation.
Definition at line 80 of file name.cpp.
{
    read_from_file_json( filename, load );
}
References load(), and read_from_file_json().
Referenced by l10n_data::add_cat_if_exists(), and reload_names().
usage_flag()
static nameFlags Name::usage_flag (const std::string & usage) static
Definition at line 36 of file name.cpp.
{
    const auto it = usage_flags.find( usage );
    if( it != usage_flags.end() ) {
        return it->second;
    }
    return static_cast< nameFlags >( 0 );
}
References usage_flags.
Referenced by load().
Variable Documentation
gender_flags
const std::map< std::string, nameFlags > Name::gender_flags static
Initial value:
{
    { "male",   nameIsMaleName },
    { "female", nameIsFemaleName },
    { "unisex", nameIsUnisexName }
}
Definition at line 30 of file name.cpp.
Referenced by gender_flag().
names
std::map< nameFlags, std::vector< std::string > > Name::names static
Definition at line 18 of file name.cpp.
Referenced by computer_session::action_list_bionics(), anonymous_namespace{armor_layers.cpp}::body_part_names(), clear(), anonymous_namespace{line.cpp}::direction_name_impl(), avatar::do_read(), monfactions::finalize(), get_matching_groups(), basecamp::give_equipment(), load(), color_loader< ColorType >::main_color_names(), mill_load_food(), om_direction::name(), photo_def_for_camera_point(), photo_quality_name(), game::place_player(), player::select_ammo(), MAP_SHARING::setAdmins(), MAP_SHARING::setDebuggers(), and smoker_load_food().
usage_flags
const std::map< std::string, nameFlags > Name::usage_flags static
Initial value:
= {
    { "given",     nameIsGivenName },
    { "family",    nameIsFamilyName },
    { "universal", nameIsGivenName | nameIsFamilyName },
    { "nick",      nameIsNickName },
    { "backer",    nameIsFullName },
    { "city",      nameIsTownName },
    { "world",     nameIsWorldName }
}
Definition at line 20 of file name.cpp.
Referenced by usage_flag().