Cataclysm BN: activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp} Namespace Reference
activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp} Namespace Reference
Enumerations
enum class hack_type_t : int { vehicle_weldrig = 0 , furniture = 1 }
Functions
cata::optional< hack_type_t > get_hack_type (const player_activity &activity)
tripoint get_position (const player_activity &activity)
item get_fake_tool (hack_type_t hack_type, const player_activity &activity)
void discharge_real_power_source (hack_type_t hack_type, const tripoint &position, item &tool, const int original_charges)
Enumeration Type Documentation
hack_type_t
enum class activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::hack_type_t : int strong
Enumerator
vehicle_weldrig
furniture
Definition at line 2635 of file activity_handlers.cpp.
                       : int {
    vehicle_weldrig = 0,
    furniture = 1
};
Function Documentation
discharge_real_power_source()
void activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::discharge_real_power_source (hack_type_t hack_type, const tripoint & position, item & tool, const int original_charges)
Definition at line 2714 of file activity_handlers.cpp.
{
    const int used_charges = original_charges - tool.charges;
    if( used_charges <= 0 ) {
        return;
    }
    const map &m = get_map();
    int unfulfilled_demand = 0;
    switch( hack_type ) {
        case hack_type_t::vehicle_weldrig: {
            optional_vpart_position pos = m.veh_at( position );
            if( !pos ) {
                return;
            }
            vehicle &veh = pos->vehicle();
            unfulfilled_demand = veh.discharge_battery( used_charges );
            break;
        }
        case hack_type_t::furniture: {
            const tripoint_abs_ms abspos( m.getabs( position ) );
            distribution_grid &grid = get_distribution_grid_tracker().grid_at( abspos );
            unfulfilled_demand = grid.mod_resource( -used_charges );
            break;
        }
    }
    if( unfulfilled_demand != 0 ) {
        debugmsg(
            "Fake tool discharged grid/veh more than grid/veh had!  Unfulfilled demand %d kJ",
            unfulfilled_demand
        );
    }
}
References debugmsg, vehicle::discharge_battery(), get_distribution_grid_tracker(), get_map(), map::getabs(), distribution_grid_tracker::grid_at(), distribution_grid::mod_resource(), tool, and map::veh_at().
Referenced by activity_handlers::repair_item_finish().
get_fake_tool()
item activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_fake_tool (hack_type_t hack_type, const player_activity & activity)
Definition at line 2659 of file activity_handlers.cpp.
{
    const tripoint position = get_position( activity );
    const map &m = get_map();
    item fake_item;
    switch( hack_type ) {
        case hack_type_t::vehicle_weldrig: {
            const optional_vpart_position pos = m.veh_at( position );
            if( !pos ) {
                debugmsg( "Failed to find vehicle while using it for repair at %s", position.to_string() );
                return fake_item;
            }
            const vehicle &veh = pos->vehicle();
            fake_item = item( itype_welder, calendar::turn, 0 );
            fake_item.charges = veh.fuel_left( itype_battery );
            break;
        }
        case hack_type_t::furniture: {
            if( !m.has_furn( position ) ) {
                debugmsg( "Failed to find furniture while using it for repair at %s", position.to_string() );
                // Return nullitem in that case
                return fake_item;
            }
            const furn_t &furniture = m.furn( position ).obj();
            const std::vector<itype> item_type_list = furniture.crafting_pseudo_item_types();
            if( item_type_list.empty() ) {
                return fake_item;
            }
            for( const itype &item_type : item_type_list ) {
                if( item_type.get_id() == static_cast<itype_id>( activity.str_values[1] ) ) {
                    if( !item_type.has_flag( "USES_GRID_POWER" ) ) {
                        debugmsg( "Non grid powered furniture for long repairs is not supported yet." );
                        return fake_item;
                    }
                    const tripoint_abs_ms abspos( m.getabs( position ) );
                    const distribution_grid &grid = get_distribution_grid_tracker().grid_at( abspos );
                    fake_item = item( item_type.get_id(), calendar::turn, 0 );
                    fake_item.charges = grid.get_resource( true );
                    break;
                }
            }
            break;
        }
    }
    fake_item.set_flag( "PSEUDO" );
    return fake_item;
}
References item::charges, debugmsg, vehicle::fuel_left(), map::furn(), furniture, get_distribution_grid_tracker(), get_map(), get_position(), distribution_grid::get_resource(), map::getabs(), distribution_grid_tracker::grid_at(), map::has_furn(), itype_battery, itype_welder, int_id< T >::obj(), item::set_flag(), tripoint::to_string(), calendar::turn, and map::veh_at().
Referenced by activity_handlers::repair_item_finish().
get_hack_type()
cata::optional< hack_type_t > activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_hack_type (const player_activity & activity)
Definition at line 2640 of file activity_handlers.cpp.
{
    // Uses real tool
    if( activity.values.size() < 2 ) {
        return cata::nullopt;
    }
    assert( !activity.coords.empty() );
    // Old save data, probably
    if( activity.values.size() == 2 ) {
        return hack_type_t::vehicle_weldrig;
    }
    return static_cast<hack_type_t>( activity.values[2] );
}
References cata::nullopt.
get_position()
tripoint activity_handlers::repair_activity_hack::anonymous_namespace{activity_handlers.cpp}::get_position (const player_activity & activity)
Definition at line 2654 of file activity_handlers.cpp.
{
    return activity.coords.at( 0 );
}
Referenced by get_fake_tool(), and activity_handlers::repair_item_finish().