Cataclysm BN: iuse Namespace Reference
iuse Namespace Reference
Functions
int sewage (player *, item *, bool, const tripoint &)
int honeycomb (player *, item *, bool, const tripoint &)
int alcohol_weak (player *, item *, bool, const tripoint &)
int alcohol_medium (player *, item *, bool, const tripoint &)
int alcohol_strong (player *, item *, bool, const tripoint &)
int xanax (player *, item *, bool, const tripoint &)
int smoking (player *, item *, bool, const tripoint &)
Entry point for intentional bodily intake of smoke via paper wrapped one time use items: cigars, cigarettes, etc.
int ecig (player *, item *, bool, const tripoint &)
int antibiotic (player *, item *, bool, const tripoint &)
int eyedrops (player *, item *, bool, const tripoint &)
int fungicide (player *, item *, bool, const tripoint &)
int antifungal (player *, item *, bool, const tripoint &)
int antiparasitic (player *, item *, bool, const tripoint &)
int anticonvulsant (player *, item *, bool, const tripoint &)
int weed_cake (player *, item *, bool, const tripoint &)
int meth (player *, item *, bool, const tripoint &)
int vaccine (player *, item *, bool, const tripoint &)
int poison (player *, item *, bool, const tripoint &)
int meditate (player *, item *, bool, const tripoint &)
int thorazine (player *, item *, bool, const tripoint &)
int prozac (player *, item *, bool, const tripoint &)
int sleep (player *, item *, bool, const tripoint &)
int datura (player *, item *, bool, const tripoint &)
int flumed (player *, item *, bool, const tripoint &)
int flusleep (player *, item *, bool, const tripoint &)
int inhaler (player *, item *, bool, const tripoint &)
int blech (player *, item *, bool, const tripoint &)
int blech_because_unclean (player *, item *, bool, const tripoint &)
int plantblech (player *, item *, bool, const tripoint &)
int chew (player *, item *, bool, const tripoint &)
int purifier (player *, item *, bool, const tripoint &)
int purify_iv (player *, item *, bool, const tripoint &)
int purify_smart (player *, item *, bool, const tripoint &)
int marloss (player *, item *, bool, const tripoint &)
int marloss_seed (player *, item *, bool, const tripoint &)
int marloss_gel (player *, item *, bool, const tripoint &)
int mycus (player *, item *, bool, const tripoint &)
int dogfood (player *, item *, bool, const tripoint &)
int catfood (player *, item *, bool, const tripoint &)
int feedcattle (player *, item *, bool, const tripoint &)
int feedbird (player *, item *, bool, const tripoint &)
int antiasthmatic (player *, item *, bool, const tripoint &)
int extinguisher (player *, item *, bool, const tripoint &)
int hammer (player *, item *, bool, const tripoint &)
int water_purifier (player *, item *, bool, const tripoint &)
int directional_antenna (player *, item *, bool, const tripoint &)
int radio_off (player *, item *, bool, const tripoint &)
int radio_on (player *, item *, bool, const tripoint &)
int noise_emitter_off (player *, item *, bool, const tripoint &)
int noise_emitter_on (player *, item *, bool, const tripoint &)
int note_bionics (player *, item *, bool, const tripoint &)
int ma_manual (player *, item *, bool, const tripoint &)
int crowbar (player *, item *, bool, const tripoint &)
int makemound (player *, item *, bool, const tripoint &)
int dig (player *, item *, bool, const tripoint &)
int dig_channel (player *, item *, bool, const tripoint &)
int fill_pit (player *, item *, bool, const tripoint &)
int clear_rubble (player *, item *, bool, const tripoint &)
Explanation of ACT_CLEAR_RUBBLE activity values:
int siphon (player *, item *, bool, const tripoint &)
int chainsaw_off (player *, item *, bool, const tripoint &)
int chainsaw_on (player *, item *, bool, const tripoint &)
int elec_chainsaw_off (player *, item *, bool, const tripoint &)
int elec_chainsaw_on (player *, item *, bool, const tripoint &)
int cs_lajatang_off (player *, item *, bool, const tripoint &)
int cs_lajatang_on (player *, item *, bool, const tripoint &)
int ecs_lajatang_off (player *, item *, bool, const tripoint &)
int ecs_lajatang_on (player *, item *, bool, const tripoint &)
int carver_off (player *, item *, bool, const tripoint &)
int carver_on (player *, item *, bool, const tripoint &)
int trimmer_off (player *, item *, bool, const tripoint &)
int trimmer_on (player *, item *, bool, const tripoint &)
int circsaw_on (player *, item *, bool, const tripoint &)
int combatsaw_off (player *, item *, bool, const tripoint &)
int combatsaw_on (player *, item *, bool, const tripoint &)
int e_combatsaw_off (player *, item *, bool, const tripoint &)
int e_combatsaw_on (player *, item *, bool, const tripoint &)
int jackhammer (player *, item *, bool, const tripoint &)
int pickaxe (player *, item *, bool, const tripoint &)
int burrow (player *, item *, bool, const tripoint &)
int geiger (player *, item *, bool, const tripoint &)
int teleport (player *, item *, bool, const tripoint &)
int can_goo (player *, item *, bool, const tripoint &)
int throwable_extinguisher_act (player *, item *, bool, const tripoint &)
int directional_hologram (player *, item *, bool, const tripoint &)
int capture_monster_veh (player *, item *, bool, const tripoint &)
int capture_monster_act (player *, item *, bool, const tripoint &)
int granade (player *, item *, bool, const tripoint &)
int granade_act (player *, item *, bool, const tripoint &)
int c4 (player *, item *, bool, const tripoint &)
int arrow_flammable (player *, item *, bool, const tripoint &)
int acidbomb_act (player *, item *, bool, const tripoint &)
int grenade_inc_act (player *, item *, bool, const tripoint &)
int molotov_lit (player *, item *, bool, const tripoint &)
int firecracker_pack (player *, item *, bool, const tripoint &)
int firecracker_pack_act (player *, item *, bool, const tripoint &)
int firecracker (player *, item *, bool, const tripoint &)
int firecracker_act (player *, item *, bool, const tripoint &)
int mininuke (player *, item *, bool, const tripoint &)
int pheromone (player *, item *, bool, const tripoint &)
int portal (player *, item *, bool, const tripoint &)
int tazer (player *, item *, bool, const tripoint &)
int tazer2 (player *, item *, bool, const tripoint &)
int shocktonfa_off (player *, item *, bool, const tripoint &)
int shocktonfa_on (player *, item *, bool, const tripoint &)
int mp3 (player *, item *, bool, const tripoint &)
int mp3_on (player *, item *, bool, const tripoint &)
int rpgdie (player *, item *, bool, const tripoint &)
int dive_tank (player *, item *, bool, const tripoint &)
int gasmask (player *, item *, bool, const tripoint &)
int portable_game (player *, item *, bool, const tripoint &)
int fitness_check (player *p, item *it, bool, const tripoint &)
int vibe (player *, item *, bool, const tripoint &)
int hand_crank (player *, item *, bool, const tripoint &)
int vortex (player *, item *, bool, const tripoint &)
int dog_whistle (player *, item *, bool, const tripoint &)
int call_of_tindalos (player *, item *, bool, const tripoint &)
int blood_draw (player *, item *, bool, const tripoint &)
int mind_splicer (player *, item *, bool, const tripoint &)
void cut_log_into_planks (player &)
int lumber (player *, item *, bool, const tripoint &)
int chop_tree (player *, item *, bool, const tripoint &)
int chop_logs (player *, item *, bool, const tripoint &)
int oxytorch (player *, item *, bool, const tripoint &)
int hacksaw (player *, item *, bool, const tripoint &)
int boltcutters (player *, item *, bool, const tripoint &)
int mop (player *, item *, bool, const tripoint &)
int spray_can (player *, item *, bool, const tripoint &)
int towel (player *, item *, bool, const tripoint &)
int unfold_generic (player *, item *, bool, const tripoint &)
int adrenaline_injector (player *, item *, bool, const tripoint &)
int jet_injector (player *, item *, bool, const tripoint &)
int stimpack (player *, item *, bool, const tripoint &)
int contacts (player *, item *, bool, const tripoint &)
int talking_doll (player *, item *, bool, const tripoint &)
int bell (player *, item *, bool, const tripoint &)
int seed (player *, item *, bool, const tripoint &)
int oxygen_bottle (player *, item *, bool, const tripoint &)
int radio_mod (player *, item *, bool, const tripoint &)
int remove_all_mods (player *, item *, bool, const tripoint &)
int fishing_rod (player *, item *, bool, const tripoint &)
int fish_trap (player *, item *, bool, const tripoint &)
int gun_repair (player *, item *, bool, const tripoint &)
int gunmod_attach (player *, item *, bool, const tripoint &)
int toolmod_attach (player *, item *, bool, const tripoint &)
int rm13armor_off (player *, item *, bool, const tripoint &)
int rm13armor_on (player *, item *, bool, const tripoint &)
int unpack_item (player *, item *, bool, const tripoint &)
int pack_cbm (player *p, item *it, bool, const tripoint &)
int pack_item (player *, item *, bool, const tripoint &)
int radglove (player *, item *, bool, const tripoint &)
int robotcontrol (player *, item *, bool, const tripoint &)
bool robotcontrol_can_target (player *, const monster &)
int einktabletpc (player *, item *, bool, const tripoint &)
int camera (player *, item *, bool, const tripoint &)
int ehandcuffs (player *, item *, bool, const tripoint &)
int foodperson (player *, item *, bool, const tripoint &)
int tow_attach (player *, item *, bool, const tripoint &)
int cable_attach (player *, item *, bool, const tripoint &)
int shavekit (player *, item *, bool, const tripoint &)
int hairkit (player *, item *, bool, const tripoint &)
int weather_tool (player *, item *, bool, const tripoint &)
int ladder (player *, item *, bool, const tripoint &)
int wash_soft_items (player *, item *, bool, const tripoint &)
int wash_hard_items (player *, item *, bool, const tripoint &)
int wash_all_items (player *, item *, bool, const tripoint &)
int solarpack (player *, item *, bool, const tripoint &)
int solarpack_off (player *, item *, bool, const tripoint &)
int weak_antibiotic (player *, item *, bool, const tripoint &)
int strong_antibiotic (player *, item *, bool, const tripoint &)
int melatonin_tablet (player *, item *, bool, const tripoint &)
int coin_flip (player *, item *, bool, const tripoint &)
int play_game (player *, item *, bool, const tripoint &)
int magic_8_ball (player *, item *, bool, const tripoint &)
int toggle_heats_food (player *, item *, bool, const tripoint &)
int report_grid_charge (player *, item *, bool, const tripoint &)
int report_grid_connections (player *, item *, bool, const tripoint &)
int radiocar (player *, item *, bool, const tripoint &)
int radiocaron (player *, item *, bool, const tripoint &)
int radiocontrol (player *, item *, bool, const tripoint &)
int autoclave (player *, item *, bool, const tripoint &)
int multicooker (player *, item *, bool, const tripoint &)
int remoteveh (player *, item *, bool, const tripoint &)
int craft (player *, item *, bool, const tripoint &)
int disassemble (player *, item *, bool, const tripoint &)
int artifact (player *, item *, bool, const tripoint &)
void play_music (player &p, const tripoint &source, int volume, int max_morale)
int towel_common (player *, item *, bool)
int handle_ground_graffiti (player &p, item *it, const std::string &prefix, const tripoint &where)
int chop_moves (Character &ch, item &tool)
int cauterize_hotplate (player *, item *, bool, const tripoint &)
Function Documentation
acidbomb_act()
int iuse::acidbomb_act (player * p, item * it, bool , const tripoint & pos)
Definition at line 3735 of file iuse.cpp.
{
    if( !p->has_item( *it ) ) {
        it->charges = -1;
        for( const tripoint &tmp : g->m.points_in_radius( pos.x == -999 ? p->pos() : pos, 1 ) ) {
            g->m.add_field( tmp, fd_acid, 3 );
        }
        return 1;
    }
    return 0;
}
References item::charges, fd_acid, g, visitable< T >::has_item(), Character::pos(), and tripoint::x.
Referenced by Item_factory::init().
adrenaline_injector()
int iuse::adrenaline_injector (player * p, item * it, bool , const tripoint &)
Definition at line 5686 of file iuse.cpp.
{
    if( p->is_npc() && p->get_effect_dur( effect_adrenaline ) >= 30_minutes ) {
        return 0;
    }
    p->moves -= to_moves<int>( 1_seconds );
    p->add_msg_player_or_npc( _( "You inject yourself with adrenaline." ),
                              _( "<npcname> injects themselves with adrenaline." ) );
    item syringe( "syringe", it->birthday() );
    p->i_add( syringe );
    if( p->has_effect( effect_adrenaline ) ) {
        p->add_msg_if_player( m_bad, _( "Your heart spasms!" ) );
        // Note: not the mod, the health
        p->mod_healthy( -20 );
    }
    p->add_effect( effect_adrenaline, 20_minutes );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), player::add_msg_player_or_npc(), item::birthday(), itype::charges_to_use(), effect_adrenaline, Creature::get_effect_dur(), Creature::has_effect(), Character::i_add(), player::is_npc(), m_bad, Character::mod_healthy(), Creature::moves, and item::type.
Referenced by Item_factory::init().
alcohol_medium()
int iuse::alcohol_medium (player * p, item * it, bool , const tripoint &)
Definition at line 512 of file iuse.cpp.
{
    return alcohol( *p, *it, 1 );
}
References alcohol().
Referenced by Item_factory::init().
alcohol_strong()
int iuse::alcohol_strong (player * p, item * it, bool , const tripoint &)
Definition at line 517 of file iuse.cpp.
{
    return alcohol( *p, *it, 2 );
}
References alcohol().
Referenced by Item_factory::init().
alcohol_weak()
int iuse::alcohol_weak (player * p, item * it, bool , const tripoint &)
Definition at line 507 of file iuse.cpp.
{
    return alcohol( *p, *it, 0 );
}
References alcohol().
Referenced by Item_factory::init().
antiasthmatic()
int iuse::antiasthmatic (player * p, item * it, bool , const tripoint &)
Definition at line 867 of file iuse.cpp.
{
    p->add_msg_if_player( m_good,
                          _( "You no longer need to worry about asthma attacks, at least for a while." ) );
    p->add_effect( effect_took_antiasthmatic, 1_days, num_bp );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_took_antiasthmatic, m_good, num_bp, and item::type.
Referenced by Item_factory::init().
antibiotic()
int iuse::antibiotic (player * p, item * it, bool , const tripoint &)
Definition at line 624 of file iuse.cpp.
{
    p->add_msg_player_or_npc( m_neutral,
                              _( "You take some antibiotics." ),
                              _( "<npcname> takes some antibiotics." ) );
    if( p->has_effect( effect_infected ) && !p->has_effect( effect_antibiotic ) ) {
        p->add_msg_if_player( m_good,
                              _( "Maybe just placebo effect, but you feel a little better as the dose settles in." ) );
    }
    p->add_effect( effect_antibiotic, 12_hours );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), player::add_msg_player_or_npc(), itype::charges_to_use(), effect_antibiotic, effect_infected, Creature::has_effect(), m_good, m_neutral, and item::type.
Referenced by Item_factory::init().
anticonvulsant()
int iuse::anticonvulsant (player * p, item * it, bool , const tripoint &)
Strength reduces duration of anticonvulsant medication
Definition at line 776 of file iuse.cpp.
{
    p->add_msg_if_player( _( "You take some anticonvulsant medication." ) );
    /** @EFFECT_STR reduces duration of anticonvulsant medication */
    time_duration duration = 8_hours - p->str_cur * rng( 0_turns, 10_minutes );
    if( p->has_trait( trait_TOLERANCE ) ) {
        duration -= 1_hours;
    }
    if( p->has_trait( trait_LIGHTWEIGHT ) ) {
        duration += 2_hours;
    }
    p->add_effect( effect_valium, duration );
    if( p->has_effect( effect_shakes ) ) {
        p->remove_effect( effect_shakes );
        p->add_msg_if_player( m_good, _( "You stop shaking." ) );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_shakes, effect_valium, Creature::has_effect(), Character::has_trait(), m_good, Creature::remove_effect(), rng(), Character::str_cur, trait_LIGHTWEIGHT, trait_TOLERANCE, and item::type.
Referenced by Item_factory::init().
antifungal()
int iuse::antifungal (player * p, item * it, bool , const tripoint &)
Definition at line 711 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    p->add_msg_if_player( _( "You take some antifungal medication." ) );
    if( p->has_effect( effect_fungus ) ) {
        p->remove_effect( effect_fungus );
        p->add_msg_if_player( m_warning,
                              _( "You feel a burning sensation under your skin that quickly fades away." ) );
    }
    if( p->has_effect( effect_spores ) ) {
        if( !p->has_effect( effect_fungus ) ) {
            p->add_msg_if_player( m_warning, _( "Your skin grows warm for a moment." ) );
        }
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), effect_fungus, effect_spores, Creature::has_effect(), Creature::is_underwater(), m_info, m_warning, Creature::remove_effect(), and item::type.
Referenced by Item_factory::init().
antiparasitic()
int iuse::antiparasitic (player * p, item * it, bool , const tripoint &)
Definition at line 731 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    p->add_msg_if_player( _( "You take some antiparasitic medication." ) );
    if( p->has_effect( effect_dermatik ) ) {
        p->remove_effect( effect_dermatik );
        p->add_msg_if_player( m_good, _( "The itching sensation under your skin fades away." ) );
    }
    if( p->has_effect( effect_tapeworm ) ) {
        p->remove_effect( effect_tapeworm );
        if( p->has_trait( trait_NOPAIN ) ) {
            p->add_msg_if_player( m_good, _( "Your bowels clench as something inside them dies." ) );
        } else {
            p->add_msg_if_player( m_mixed, _( "Your bowels spasm painfully as something inside them dies." ) );
            p->mod_pain( rng( 8, 24 ) );
        }
    }
    if( p->has_effect( effect_bloodworms ) ) {
        p->remove_effect( effect_bloodworms );
        p->add_msg_if_player( _( "Your skin prickles and your veins itch for a few moments." ) );
    }
    if( p->has_effect( effect_brainworms ) ) {
        p->remove_effect( effect_brainworms );
        if( p->has_trait( trait_NOPAIN ) ) {
            p->add_msg_if_player( m_good, _( "The pressure inside your head feels better already." ) );
        } else {
            p->add_msg_if_player( m_mixed,
                                  _( "Your head pounds like a sore tooth as something inside of it dies." ) );
            p->mod_pain( rng( 8, 24 ) );
        }
    }
    if( p->has_effect( effect_paincysts ) ) {
        p->remove_effect( effect_paincysts );
        if( p->has_trait( trait_NOPAIN ) ) {
            p->add_msg_if_player( m_good, _( "The stiffness in your joints goes away." ) );
        } else {
            p->add_msg_if_player( m_good, _( "The pain in your joints goes away." ) );
        }
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), effect_bloodworms, effect_brainworms, effect_dermatik, effect_paincysts, effect_tapeworm, Creature::has_effect(), Character::has_trait(), Creature::is_underwater(), m_good, m_info, m_mixed, player::mod_pain(), Creature::remove_effect(), rng(), trait_NOPAIN, and item::type.
Referenced by Item_factory::init().
arrow_flammable()
int iuse::arrow_flammable (player * p, item * it, bool , const tripoint &)
Definition at line 3777 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( !p->use_charges_if_avail( itype_fire, 1 ) ) {
        p->add_msg_if_player( m_info, _( "You need a source of fire!" ) );
        return 0;
    }
    p->add_msg_if_player( _( "You light the arrow!" ) );
    p->moves -= to_moves<int>( 1_seconds );
    if( it->charges == 1 ) {
        it->convert( itype_arrow_flamming );
        return 0;
    }
    item lit_arrow( *it );
    lit_arrow.convert( itype_arrow_flamming ).charges = 1;
    p->i_add( lit_arrow );
    return 1;
}
References _, player::add_msg_if_player(), item::charges, item::convert(), Character::i_add(), Creature::is_underwater(), itype_arrow_flamming, itype_fire, m_info, Creature::moves, and Character::use_charges_if_avail().
Referenced by Item_factory::init().
artifact()
int iuse::artifact (player * p, item * it, bool , const tripoint &)
Definition at line 5171 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // TODO: Allow this for trusting NPCs
        return 0;
    }
    if( !it->is_artifact() ) {
        debugmsg( "iuse::artifact called on a non-artifact item!  %s",
                  it->tname() );
        return 0;
    } else if( !it->is_tool() ) {
        debugmsg( "iuse::artifact called on a non-tool artifact!  %s",
                  it->tname() );
        return 0;
    }
    g->events().send<event_type::activates_artifact>( p->getID(), it->tname( 1, false ) );
    const auto &art = it->type->artifact;
    size_t num_used = rng( 1, art->effects_activated.size() );
    if( num_used < art->effects_activated.size() ) {
        num_used += rng( 1, art->effects_activated.size() - num_used );
    }
    std::vector<art_effect_active> effects = art->effects_activated;
    for( size_t i = 0; i < num_used && !effects.empty(); i++ ) {
        const art_effect_active used = random_entry_removed( effects );
        switch( used ) {
            case AEA_STORM: {
                sounds::sound( p->pos(), 10, sounds::sound_t::combat, _( "Ka-BOOM!" ), true, "environment",
                               "thunder_near" );
                int num_bolts = rng( 2, 4 );
                for( int j = 0; j < num_bolts; j++ ) {
                    point dir;
                    while( dir.x == 0 && dir.y == 0 ) {
                        dir.x = rng( -1, 1 );
                        dir.y = rng( -1, 1 );
                    }
                    int dist = rng( 4, 12 );
                    point bolt( p->posx(), p->posy() );
                    for( int n = 0; n < dist; n++ ) {
                        bolt.x += dir.x;
                        bolt.y += dir.y;
                        g->m.add_field( {bolt, p->posz()}, fd_electricity, rng( 2, 3 ) );
                        if( one_in( 4 ) ) {
                            if( dir.x == 0 ) {
                                dir.x = rng( 0, 1 ) * 2 - 1;
                            } else {
                                dir.x = 0;
                            }
                        }
                        if( one_in( 4 ) ) {
                            if( dir.y == 0 ) {
                                dir.y = rng( 0, 1 ) * 2 - 1;
                            } else {
                                dir.y = 0;
                            }
                        }
                    }
                }
            }
            break;
            case AEA_FIREBALL: {
                if( const cata::optional<tripoint> fireball = g->look_around() ) {
                    explosion_handler::explosion( *fireball, 180, 0.5, true );
                }
            }
            break;
            case AEA_ADRENALINE:
                p->add_msg_if_player( m_good, _( "You're filled with a roaring energy!" ) );
                p->add_effect( effect_adrenaline, rng( 20_minutes, 25_minutes ) );
                break;
            case AEA_MAP: {
                const tripoint_abs_omt center = p->global_omt_location();
                const bool new_map = overmap_buffer.reveal( center.xy(), 20, center.z() );
                if( new_map ) {
                    p->add_msg_if_player( m_warning, _( "You have a vision of the surrounding area" ) );
                    p->moves -= to_moves<int>( 1_seconds );
                }
            }
            break;
            case AEA_BLOOD: {
                bool blood = false;
                for( const tripoint &tmp : g->m.points_in_radius( p->pos(), 4 ) ) {
                    if( !one_in( 4 ) && g->m.add_field( tmp, fd_blood, 3 ) &&
                        ( blood || g->u.sees( tmp ) ) ) {
                        blood = true;
                    }
                }
                if( blood ) {
                    p->add_msg_if_player( m_warning, _( "Blood soaks out of the ground and walls." ) );
                }
            }
            break;
            case AEA_FATIGUE: {
                p->add_msg_if_player( m_warning, _( "The fabric of space seems to decay." ) );
                point p2{ rng( p->posx() - 3, p->posx() + 3 ), rng( p->posy() - 3, p->posy() + 3 ) };
                g->m.add_field( {p2, p->posz()}, fd_fatigue, rng( 1, 2 ) );
            }
            break;
            case AEA_ACIDBALL: {
                if( const cata::optional<tripoint> acidball = g->look_around() ) {
                    for( const tripoint &tmp : g->m.points_in_radius( *acidball, 1 ) ) {
                        g->m.add_field( tmp, fd_acid, rng( 2, 3 ) );
                    }
                }
            }
            break;
            case AEA_PULSE:
                sounds::sound( p->pos(), 30, sounds::sound_t::combat, _( "The earth shakes!" ), true, "misc",
                               "earthquake" );
                for( const tripoint &pt : g->m.points_in_radius( p->pos(), 2 ) ) {
                    g->m.bash( pt, 40 );
                    g->m.bash( pt, 40 );  // Multibash effect, so that doors &c will fall
                    g->m.bash( pt, 40 );
                    if( g->m.is_bashable( pt ) && rng( 1, 10 ) >= 3 ) {
                        g->m.bash( pt, 999, false, true );
                    }
                }
                break;
            case AEA_HEAL:
                p->add_msg_if_player( m_good, _( "You feel healed." ) );
                p->healall( 2 );
                break;
            case AEA_CONFUSED:
                for( const tripoint &dest : g->m.points_in_radius( p->pos(), 8 ) ) {
                    if( monster *const mon = g->critter_at<monster>( dest, true ) ) {
                        mon->add_effect( effect_stunned, rng( 5_turns, 15_turns ) );
                    }
                }
                break;
            case AEA_ENTRANCE:
                for( const tripoint &dest : g->m.points_in_radius( p->pos(), 8 ) ) {
                    monster *const mon = g->critter_at<monster>( dest, true );
                    if( mon && mon->friendly == 0 && rng( 0, 600 ) > mon->get_hp() ) {
                        mon->make_friendly();
                    }
                }
                break;
            case AEA_BUGS: {
                int roll = rng( 1, 10 );
                mtype_id bug = mtype_id::NULL_ID();
                int num = 0;
                if( roll <= 4 ) {
                    p->add_msg_if_player( m_warning, _( "Flies buzz around you." ) );
                } else if( roll <= 7 ) {
                    p->add_msg_if_player( m_warning, _( "Giant flies appear!" ) );
                    bug = mon_fly;
                    num = rng( 2, 4 );
                } else if( roll <= 9 ) {
                    p->add_msg_if_player( m_warning, _( "Giant bees appear!" ) );
                    bug = mon_bee;
                    num = rng( 1, 3 );
                } else {
                    p->add_msg_if_player( m_warning, _( "Giant wasps appear!" ) );
                    bug = mon_wasp;
                    num = rng( 1, 2 );
                }
                if( bug ) {
                    for( int j = 0; j < num; j++ ) {
                        if( monster *const b = g->place_critter_around( bug, p->pos(), 1 ) ) {
                            b->friendly = -1;
                            b->add_effect( effect_pet, 1_turns, num_bp );
                        }
                    }
                }
            }
            break;
            case AEA_TELEPORT:
                teleport::teleport( *p );
                break;
            case AEA_LIGHT:
                p->add_msg_if_player( _( "The %s glows brightly!" ), it->tname() );
                g->timed_events.add( TIMED_EVENT_ARTIFACT_LIGHT, calendar::turn + 3_minutes );
                break;
            case AEA_GROWTH: {
                monster tmptriffid( mtype_id::NULL_ID(), p->pos() );
                mattack::growplants( &tmptriffid );
            }
            break;
            case AEA_HURTALL:
                for( monster &critter : g->all_monsters() ) {
                    critter.apply_damage( nullptr, bodypart_id( "torso" ), rng( 0, 5 ) );
                }
                break;
            case AEA_RADIATION:
                add_msg( m_warning, _( "Horrible gases are emitted!" ) );
                for( const tripoint &dest : g->m.points_in_radius( p->pos(), 1 ) ) {
                    g->m.add_field( dest, fd_nuke_gas, rng( 2, 3 ) );
                }
                break;
            case AEA_PAIN:
                p->add_msg_if_player( m_bad, _( "You're wracked with pain!" ) );
                // OK, the Lovecraftian thingamajig can bring Deadened
                // masochists & Cenobites the stimulation they've been
                // craving ;)
                p->mod_pain_noresist( rng( 5, 15 ) );
                break;
            case AEA_MUTATE:
                if( !one_in( 3 ) ) {
                    p->mutate();
                }
                break;
            case AEA_PARALYZE:
                p->add_msg_if_player( m_bad, _( "You're paralyzed!" ) );
                p->moves -= rng( 50, 200 );
                break;
            case AEA_FIRESTORM: {
                p->add_msg_if_player( m_bad, _( "Fire rains down around you!" ) );
                std::vector<tripoint> ps = closest_points_first( p->pos(), 3 );
                for( auto p_it : ps ) {
                    if( !one_in( 3 ) ) {
                        g->m.add_field( p_it, fd_fire, 1 + rng( 0, 1 ) * rng( 0, 1 ), 3_minutes );
                    }
                }
                break;
            }
            case AEA_ATTENTION:
                p->add_msg_if_player( m_warning, _( "You feel like your action has attracted attention." ) );
                p->add_effect( effect_attention, rng( 1_hours, 3_hours ) );
                break;
            case AEA_TELEGLOW:
                p->add_msg_if_player( m_warning, _( "You feel unhinged." ) );
                p->add_effect( effect_teleglow, rng( 30_minutes, 120_minutes ) );
                break;
            case AEA_NOISE:
                sounds::sound( p->pos(), 100, sounds::sound_t::combat,
                               string_format( _( "a deafening boom from %s %s" ),
                                              p->disp_name( true ), it->tname() ), true, "misc", "shockwave" );
                break;
            case AEA_SCREAM:
                sounds::sound( p->pos(), 40, sounds::sound_t::alert,
                               string_format( _( "a disturbing scream from %s %s" ),
                                              p->disp_name( true ), it->tname() ), true, "shout", "scream" );
                if( !p->is_deaf() ) {
                    p->add_morale( MORALE_SCREAM, -10, 0, 30_minutes, 1_minutes );
                }
                break;
            case AEA_DIM:
                p->add_msg_if_player( _( "The sky starts to dim." ) );
                g->timed_events.add( TIMED_EVENT_DIM, calendar::turn + 5_minutes );
                break;
            case AEA_FLASH:
                p->add_msg_if_player( _( "The %s flashes brightly!" ), it->tname() );
                explosion_handler::flashbang( p->pos(), false, "explosion" );
                break;
            case AEA_VOMIT:
                p->add_msg_if_player( m_bad, _( "A wave of nausea passes through you!" ) );
                p->vomit();
                break;
            case AEA_SHADOWS: {
                int num_shadows = rng( 4, 8 );
                int num_spawned = 0;
                for( int j = 0; j < num_shadows; j++ ) {
                    for( int tries = 0; tries < 10; ++tries ) {
                        tripoint monp = p->pos();
                        if( one_in( 2 ) ) {
                            monp.x = rng( p->posx() - 5, p->posx() + 5 );
                            monp.y = ( one_in( 2 ) ? p->posy() - 5 : p->posy() + 5 );
                        } else {
                            monp.x = ( one_in( 2 ) ? p->posx() - 5 : p->posx() + 5 );
                            monp.y = rng( p->posy() - 5, p->posy() + 5 );
                        }
                        if( !g->m.sees( monp, p->pos(), 10 ) ) {
                            continue;
                        }
                        if( monster *const  spawned = g->place_critter_at( mon_shadow, monp ) ) {
                            num_spawned++;
                            spawned->reset_special_rng( "DISAPPEAR" );
                            break;
                        }
                    }
                }
                if( num_spawned > 1 ) {
                    p->add_msg_if_player( m_warning, _( "Shadows form around you." ) );
                } else if( num_spawned == 1 ) {
                    p->add_msg_if_player( m_warning, _( "A shadow forms nearby." ) );
                }
            }
            break;
            case AEA_STAMINA_EMPTY:
                p->add_msg_if_player( m_bad, _( "Your body feels like jelly." ) );
                p->set_stamina( p->get_stamina() * 1 / ( rng( 3, 8 ) ) );
                break;
            case AEA_FUN:
                p->add_msg_if_player( m_good, _( "You're filled with euphoria!" ) );
                p->add_morale( MORALE_FEELING_GOOD, rng( 20, 50 ), 0, 5_minutes, 5_turns, false );
                break;
            case AEA_SPLIT:
                // TODO: Add something
                break;
            case AEA_NULL:
            // BUG
            case NUM_AEAS:
            default:
                debugmsg( "iuse::artifact(): wrong artifact type (%d)", used );
                break;
        }
    }
    return it->type->charges_to_use();
}
References _, activates_artifact, Creature::add_effect(), Character::add_morale(), add_msg(), player::add_msg_if_player(), AEA_ACIDBALL, AEA_ADRENALINE, AEA_ATTENTION, AEA_BLOOD, AEA_BUGS, AEA_CONFUSED, AEA_DIM, AEA_ENTRANCE, AEA_FATIGUE, AEA_FIREBALL, AEA_FIRESTORM, AEA_FLASH, AEA_FUN, AEA_GROWTH, AEA_HEAL, AEA_HURTALL, AEA_LIGHT, AEA_MAP, AEA_MUTATE, AEA_NOISE, AEA_NULL, AEA_PAIN, AEA_PARALYZE, AEA_PULSE, AEA_RADIATION, AEA_SCREAM, AEA_SHADOWS, AEA_SPLIT, AEA_STAMINA_EMPTY, AEA_STORM, AEA_TELEGLOW, AEA_TELEPORT, AEA_VOMIT, sounds::alert, itype::artifact, b, center, itype::charges_to_use(), closest_points_first(), sounds::combat, debugmsg, Character::disp_name(), effect_adrenaline, effect_attention, effect_pet, effect_stunned, effect_teleglow, explosion_handler::explosion(), fd_acid, fd_blood, fd_electricity, fd_fatigue, fd_fire, fd_nuke_gas, mdeath::fireball(), explosion_handler::flashbang(), monster::friendly, g, monster::get_hp(), Character::get_stamina(), Character::getID(), Character::global_omt_location(), mattack::growplants(), Character::healall(), item::is_artifact(), Character::is_deaf(), player::is_npc(), item::is_tool(), m_bad, m_good, m_warning, monster::make_friendly(), Creature::mod_pain_noresist(), mon_bee, mon_fly, mon_shadow, mon_wasp, MORALE_FEELING_GOOD, MORALE_SCREAM, Creature::moves, Character::mutate(), string_id< mtype >::NULL_ID(), num, NUM_AEAS, num_bp, one_in(), overmap_buffer, Character::pos(), Character::posx(), Character::posy(), Character::posz(), random_entry_removed(), overmapbuffer::reveal(), rng(), Character::set_stamina(), sounds::sound(), string_format(), teleport::teleport(), TIMED_EVENT_ARTIFACT_LIGHT, TIMED_EVENT_DIM, item::tname(), calendar::turn, item::type, Character::vomit(), point::x, tripoint::x, point::y, and tripoint::y.
Referenced by Item_factory::init(), and it_artifact_tool::it_artifact_tool().
autoclave()
int iuse::autoclave (player * p, item * , bool , const tripoint & pos)
Definition at line 8383 of file iuse.cpp.
{
    iexamine::autoclave_empty( *p, pos );
    return 0;
}
References iexamine::autoclave_empty().
Referenced by inventory::form_from_map(), and Item_factory::init().
bell()
int iuse::bell (player * p, item * it, bool , const tripoint &)
Definition at line 5977 of file iuse.cpp.
{
    if( it->typeId() == itype_cow_bell ) {
        sounds::sound( p->pos(), 12, sounds::sound_t::music, _( "Clank!  Clank!" ), true, "misc",
                       "cow_bell" );
        if( !p->is_deaf() ) {
            const int cow_factor = 1 + ( p->mutation_category_level.find( "CATTLE" ) ==
                                         p->mutation_category_level.end() ?
                                         0 :
                                         ( p->mutation_category_level.find( "CATTLE" )->second ) / 8
                                       );
            if( x_in_y( cow_factor, 1 + cow_factor ) ) {
                p->add_morale( MORALE_MUSIC, 1, 15 * ( cow_factor > 10 ? 10 : cow_factor ) );
            }
        }
    } else {
        sounds::sound( p->pos(), 4, sounds::sound_t::music, _( "Ring!  Ring!" ), true, "misc", "bell" );
    }
    return it->type->charges_to_use();
}
References _, Character::add_morale(), itype::charges_to_use(), Character::is_deaf(), itype_cow_bell, MORALE_MUSIC, sounds::music, Character::mutation_category_level, Character::pos(), sounds::sound(), item::type, item::typeId(), and x_in_y().
Referenced by Item_factory::init().
blech()
int iuse::blech (player * p, item * it, bool , const tripoint &)
Definition at line 1023 of file iuse.cpp.
{
    // TODO: Add more effects?
    if( it->made_of( LIQUID ) ) {
        if( !p->query_yn( _( "This looks unhealthy, sure you want to drink it?" ) ) ) {
            return 0;
        }
    } else { //Assume that if a blech consumable isn't a drink, it will be eaten.
        if( !p->query_yn( _( "This looks unhealthy, sure you want to eat it?" ) ) ) {
            return 0;
        }
    }
    if( it->has_flag( flag_ACID ) && ( p->has_trait( trait_ACIDPROOF ) ||
                                       p->has_trait( trait_ACIDBLOOD ) ) ) {
        p->add_msg_if_player( m_bad, _( "Blech, that tastes gross!" ) );
        //reverse the harmful values of drinking this acid.
        double multiplier = -1;
        p->mod_stored_kcal( 10 * p->nutrition_for( *it ) * multiplier );
        p->mod_thirst( -it->get_comestible()->quench * multiplier + 20 );
        p->mod_healthy_mod( it->get_comestible()->healthy * multiplier,
                            it->get_comestible()->healthy * multiplier );
        p->add_morale( MORALE_FOOD_BAD, it->get_comestible_fun() * multiplier, 60, 1_hours, 30_minutes,
                       false, it->type );
    } else {
        p->add_msg_if_player( m_bad, _( "Blech, that burns your throat!" ) );
        p->mod_pain( rng( 32, 64 ) );
        p->add_effect( effect_poison, 1_hours );
        p->apply_damage( nullptr, bodypart_id( "torso" ), rng( 4, 12 ) );
        p->vomit();
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), Character::add_morale(), player::add_msg_if_player(), Character::apply_damage(), itype::charges_to_use(), effect_poison, flag_ACID(), item::get_comestible(), item::get_comestible_fun(), item::has_flag(), Character::has_trait(), LIQUID, m_bad, item::made_of(), Character::mod_healthy_mod(), player::mod_pain(), Character::mod_stored_kcal(), Character::mod_thirst(), MORALE_FOOD_BAD, Character::nutrition_for(), player::query_yn(), rng(), trait_ACIDBLOOD, trait_ACIDPROOF, item::type, and Character::vomit().
Referenced by Item_factory::init(), and plantblech().
blech_because_unclean()
int iuse::blech_because_unclean (player * p, item * it, bool , const tripoint &)
Definition at line 1057 of file iuse.cpp.
{
    if( !p->is_npc() ) {
        if( it->made_of( LIQUID ) ) {
            if( !p->query_yn( _( "This looks unclean, sure you want to drink it?" ) ) ) {
                return 0;
            }
        } else { //Assume that if a blech consumable isn't a drink, it will be eaten.
            if( !p->query_yn( _( "This looks unclean, sure you want to eat it?" ) ) ) {
                return 0;
            }
        }
    }
    return it->type->charges_to_use();
}
References _, itype::charges_to_use(), player::is_npc(), LIQUID, item::made_of(), player::query_yn(), and item::type.
Referenced by Item_factory::init().
blood_draw()
int iuse::blood_draw (player * p, item * it, bool , const tripoint &)
Definition at line 4599 of file iuse.cpp.
{
    if( p->is_npc() ) {
        return 0;    // No NPCs for now!
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( !it->contents.empty() ) {
        p->add_msg_if_player( m_info, _( "That %s is full!" ), it->tname() );
        return 0;
    }
    item blood( "blood", calendar::turn );
    bool drew_blood = false;
    bool acid_blood = false;
    for( auto &map_it : g->m.i_at( point( p->posx(), p->posy() ) ) ) {
        if( map_it.is_corpse() &&
            query_yn( _( "Draw blood from %s?" ),
                      colorize( map_it.tname(), map_it.color_in_inventory() ) ) ) {
            p->add_msg_if_player( m_info, _( "You drew blood from the %s" ), map_it.tname() );
            drew_blood = true;
            auto bloodtype( map_it.get_mtype()->bloodType() );
            if( bloodtype.obj().has_acid ) {
                acid_blood = true;
            } else {
                blood.set_mtype( map_it.get_mtype() );
            }
        }
    }
    if( !drew_blood && query_yn( _( "Draw your own blood?" ) ) ) {
        p->add_msg_if_player( m_info, _( "You drew your own blood" ) );
        drew_blood = true;
        if( p->has_trait( trait_ACIDBLOOD ) ) {
            acid_blood = true;
        }
        p->mod_stored_nutr( 10 );
        p->mod_thirst( 10 );
        p->mod_pain( 3 );
    }
    if( acid_blood ) {
        item acid( "acid", calendar::turn );
        it->put_in( acid );
        if( one_in( 3 ) ) {
            if( it->inc_damage( DT_ACID ) ) {
                p->add_msg_if_player( m_info, _( "but acidic blood melts the %s, destroying it!" ),
                                      it->tname() );
                p->i_rem( it );
                return 0;
            }
            p->add_msg_if_player( m_info, _( "but acidic blood damages the %s!" ), it->tname() );
        }
        return it->type->charges_to_use();
    }
    if( !drew_blood ) {
        return it->type->charges_to_use();
    }
    it->put_in( blood );
    return it->type->charges_to_use();
}
References _, mattack::acid(), player::add_msg_if_player(), itype::charges_to_use(), colorize(), item::contents, DT_ACID, item_contents::empty(), g, Character::has_trait(), Character::i_rem(), item::inc_damage(), Character::is_mounted(), player::is_npc(), m_info, player::mod_pain(), Character::mod_stored_nutr(), Character::mod_thirst(), one_in(), Character::posx(), Character::posy(), item::put_in(), query_yn(), item::set_mtype(), item::tname(), trait_ACIDBLOOD, calendar::turn, and item::type.
Referenced by Item_factory::init().
boltcutters()
int iuse::boltcutters (player * p, item * it, bool , const tripoint &)
Definition at line 5033 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::set<ter_id> allowed_ter_id {
        t_chaingate_l,
        t_chainfence
    };
    const std::function<bool( const tripoint & )> f = [&allowed_ter_id]( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        const ter_id ter = g->m.ter( pnt );
        const bool is_allowed = allowed_ter_id.find( ter ) != allowed_ter_id.end();
        return is_allowed;
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Cut up metal where?" ), _( "There is no metal to cut up nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id type = g->m.ter( pnt );
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info,
                                  _( "You neatly sever all of the veins and arteries in your body.  Oh wait, Never mind." ) );
        } else {
            p->add_msg_if_player( m_info, _( "You can't cut that." ) );
        }
        return 0;
    }
    if( type == t_chaingate_l ) {
        p->moves -= to_moves<int>( 1_seconds );
        g->m.ter_set( pnt, t_chaingate_c );
        sounds::sound( pnt, 5, sounds::sound_t::combat, _( "Gachunk!" ), true, "tool", "boltcutters" );
        g->m.spawn_item( point( p->posx(), p->posy() ), "scrap", 3 );
    } else if( type == t_chainfence ) {
        p->moves -= to_moves<int>( 5_seconds );
        g->m.ter_set( pnt, t_chainfence_posts );
        sounds::sound( pnt, 5, sounds::sound_t::combat, _( "Snick, snick, gachunk!" ), true, "tool",
                       "boltcutters" );
        g->m.spawn_item( pnt, "wire", 20 );
    } else {
        return 0;
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), choose_adjacent_highlight(), sounds::combat, g, Character::is_mounted(), m_info, Creature::moves, Character::pos(), Character::posx(), Character::posy(), sounds::sound(), t_chainfence, t_chainfence_posts, t_chaingate_c, t_chaingate_l, type, and item::type.
Referenced by Item_factory::init().
burrow()
int iuse::burrow (player * p, item * it, bool , const tripoint & pos)
Definition at line 3342 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Long action
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    tripoint pnt = pos;
    if( pos == p->pos() ) {
        const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Burrow where?" ) );
        if( !pnt_ ) {
            return 0;
        }
        pnt = *pnt_;
    }
    if( !g->m.has_flag( "MINEABLE", pnt ) ) {
        p->add_msg_if_player( m_info, _( "You can't burrow there." ) );
        return 0;
    }
    if( g->m.veh_at( pnt ) ) {
        p->add_msg_if_player( _( "There's a vehicle in the way!" ) );
        return 0;
    }
    int moves = to_moves<int>( 5_minutes );
    moves += ( ( MAX_STAT + 3 ) - std::min( p->str_cur, MAX_STAT ) ) * to_moves<int>( 2_minutes );
    if( g->m.move_cost( pnt ) == 2 ) {
        // We're breaking up some flat surface like pavement, which is much easier
        moves /= 2;
    }
    p->assign_activity( ACT_BURROW, moves, -1, 0 );
    p->activity.placement = pnt;
    p->add_msg_if_player( _( "You start tearing into the %1$s with your %2$s." ),
                          g->m.tername( pnt ), it->tname() );
    return 0; // handled when the activity finishes
}
References _, ACT_BURROW, Character::activity, player::add_msg_if_player(), Character::assign_activity(), choose_adjacent(), g, Character::is_mounted(), player::is_npc(), Creature::is_underwater(), m_info, MAX_STAT, player_activity::placement, Character::pos(), Character::str_cur, and item::tname().
Referenced by Item_factory::init().
c4()
int iuse::c4 (player * p, item * it, bool , const tripoint &)
Definition at line 3720 of file iuse.cpp.
{
    int time;
    bool got_value = query_int( time, _( "Set the timer to (0 to cancel)?" ) );
    if( !got_value || time <= 0 ) {
        p->add_msg_if_player( _( "Never mind." ) );
        return 0;
    }
    p->add_msg_if_player( _( "You set the timer to %d." ), time );
    it->convert( itype_c4armed );
    it->charges = time;
    it->active = true;
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::charges, itype::charges_to_use(), item::convert(), itype_c4armed, query_int(), and item::type.
Referenced by Item_factory::init(), and raw_noise_4d().
cable_attach()
int iuse::cable_attach (player * p, item * it, bool , const tripoint &)
Definition at line 8816 of file iuse.cpp.
{
    std::string initial_state = it->get_var( "state", "attach_first" );
    const bool has_bio_cable = !p->get_remote_fueled_bionic().is_empty();
    const bool has_solar_pack = p->worn_with_flag( "SOLARPACK" );
    const bool has_solar_pack_on = p->worn_with_flag( "SOLARPACK_ON" );
    const bool wearing_solar_pack = has_solar_pack || has_solar_pack_on;
    const bool has_ups = p->has_charges( itype_UPS_off, 1 ) || p->has_charges( itype_adv_UPS_off, 1 );
    item_location loc;
    avatar *you = p->as_avatar();
    auto filter = [&]( const item & itm ) {
        return itm.has_flag( "IS_UPS" );
    };
    const std::string choose_ups = _( "Choose UPS:" );
    const std::string dont_have_ups = _( "You don't have any UPS." );
    const auto set_cable_active = []( player * p, item * it, const std::string & state ) {
        const std::string prev_state = it->get_var( "state" );
        it->set_var( "state", state );
        it->active = true;
        it->process( p, p->pos(), false );
        p->moves -= 15;
        if( !prev_state.empty() && ( prev_state == "cable_charger" || ( prev_state != "attach_first" &&
                                     ( state == "cable_charger_link" || state == "cable_charger" ) ) ) ) {
            p->find_remote_fuel();
        }
    };
    if( initial_state == "attach_first" ) {
        if( has_bio_cable ) {
            uilist kmenu;
            kmenu.text = _( "Using cable:" );
            kmenu.addentry( 0, true, -1, _( "Attach cable to vehicle" ) );
            kmenu.addentry( 1, true, -1, _( "Attach cable to self" ) );
            if( wearing_solar_pack ) {
                kmenu.addentry( 2, has_solar_pack_on, -1, _( "Attach cable to solar pack" ) );
            }
            if( has_ups ) {
                kmenu.addentry( 3, true, -1, _( "Attach cable to UPS" ) );
            }
            kmenu.query();
            int choice = kmenu.ret;
            if( choice < 0 ) {
                return 0; // we did nothing.
            } else if( choice == 1 ) {
                set_cable_active( p, it, "cable_charger" );
                p->add_msg_if_player( m_info, _( "You attach the cable to your Cable Charger System." ) );
                return 0;
            } else if( choice == 2 ) {
                set_cable_active( p, it, "solar_pack" );
                p->add_msg_if_player( m_info, _( "You attach the cable to the solar pack." ) );
                return 0;
            } else if( choice == 3 ) {
                if( you != nullptr )                     {
                    loc = game_menus::inv::titled_filter_menu( filter, *you, choose_ups, dont_have_ups );
                }
                if( !loc ) {
                    add_msg( _( "Never mind" ) );
                    return 0;
                }
                item &chosen = *loc;
                chosen.set_var( "cable", "plugged_in" );
                chosen.activate();
                set_cable_active( p, it, "UPS" );
                p->add_msg_if_player( m_info, _( "You attach the cable to the UPS." ) );
                return 0;
            }
            // fall through for attaching to a vehicle
        }
        const cata::optional<tripoint> posp_ = choose_adjacent( _( "Attach cable to vehicle where?" ) );
        if( !posp_ ) {
            return 0;
        }
        const tripoint posp = *posp_;
        const optional_vpart_position vp = g->m.veh_at( posp );
        if( !vp ) {
            p->add_msg_if_player( _( "There's no vehicle there." ) );
            return 0;
        } else {
            const auto abspos = g->m.getabs( posp );
            it->set_var( "source_x", abspos.x );
            it->set_var( "source_y", abspos.y );
            it->set_var( "source_z", abspos.z );
            set_cable_active( p, it, "pay_out_cable" );
        }
    } else {
        const auto confirm_source_vehicle = []( player * p, item * it, const bool detach_if_missing ) {
            tripoint source_global( it->get_var( "source_x", 0 ),
                                    it->get_var( "source_y", 0 ),
                                    it->get_var( "source_z", 0 ) );
            tripoint source_local = g->m.getlocal( source_global );
            const optional_vpart_position source_vp = g->m.veh_at( source_local );
            vehicle *const source_veh = veh_pointer_or_null( source_vp );
            if( detach_if_missing && source_veh == nullptr ) {
                if( p != nullptr && p->has_item( *it ) ) {
                    p->add_msg_if_player( m_bad, _( "You notice the cable has come loose!" ) );
                }
                it->reset_cable( p );
            }
            return source_vp;
        };
        const bool paying_out = initial_state == "pay_out_cable";
        const bool cable_cbm = initial_state == "cable_charger";
        const bool solar_pack = initial_state == "solar_pack";
        const bool UPS = initial_state == "UPS";
        bool loose_ends = paying_out || cable_cbm || solar_pack || UPS;
        uilist kmenu;
        kmenu.text = _( "Using cable:" );
        kmenu.addentry( 0, true, -1, _( "Detach and re-spool the cable" ) );
        kmenu.addentry( 1, ( paying_out || cable_cbm ) && !solar_pack &&
                        !UPS, -1, _( "Attach loose end to vehicle or grid connector" ) );
        if( has_bio_cable && loose_ends ) {
            kmenu.addentry( 2, !cable_cbm, -1, _( "Attach loose end to self" ) );
            if( wearing_solar_pack ) {
                kmenu.addentry( 3, !solar_pack && !paying_out && !UPS, -1, _( "Attach loose end to solar pack" ) );
            }
            if( has_ups ) {
                kmenu.addentry( 4, !UPS && !solar_pack && !paying_out, -1, _( "Attach loose end to UPS" ) );
            }
        }
        kmenu.query();
        int choice = kmenu.ret;
        if( choice < 0 ) {
            return 0; // we did nothing.
        } else if( choice == 0 ) { // unconnect & respool
            p->reset_remote_fuel();
            it->reset_cable( p );
            return 0;
        } else if( choice == 2 ) { // connect self while other end already connected
            p->add_msg_if_player( m_info, _( "You attach the cable to the Cable Charger System." ) );
            // connecting self, solar backpack connected
            if( solar_pack ) {
                set_cable_active( p, it, "solar_pack_link" );
                p->add_msg_if_player( m_good, _( "You are now plugged to the solar backpack." ) );
                return 0;
            }
            // connecting self, UPS connected
            if( UPS ) {
                set_cable_active( p, it, "UPS_link" );
                p->add_msg_if_player( m_good, _( "You are now plugged to the UPS." ) );
                return 0;
            }
            // connecting self, vehicle connected
            const optional_vpart_position source_vp = confirm_source_vehicle( p, it, true );
            if( veh_pointer_or_null( source_vp ) != nullptr ) {
                set_cable_active( p, it, "cable_charger_link" );
                p->add_msg_if_player( m_good, _( "You are now plugged to the vehicle." ) );
            }
            return 0;
        } else if( choice == 3 ) {
            // connecting self to solar backpack
            set_cable_active( p, it, "solar_pack_link" );
            p->add_msg_if_player( m_good, _( "You are now plugged to the solar backpack." ) );
            return 0;
        } else if( choice == 4 ) {
            loc = game_menus::inv::titled_filter_menu( filter, *you, choose_ups, dont_have_ups );
            // connecting self to UPS
            if( !loc ) {
                add_msg( _( "Never mind" ) );
                return 0;
            }
            item &chosen = *loc;
            chosen.set_var( "cable", "plugged_in" );
            chosen.activate();
            set_cable_active( p, it, "UPS_link" );
            p->add_msg_if_player( m_good, _( "You are now plugged to the UPS." ) );
            return 0;
        }
        // connecting self to vehicle
        const optional_vpart_position source_vp = confirm_source_vehicle( p, it, paying_out );
        vehicle *const source_veh = veh_pointer_or_null( source_vp );
        if( source_veh == nullptr && paying_out ) {
            return 0;
        }
        const cata::optional<tripoint> vpos_ = choose_adjacent( _( "Attach cable where?" ) );
        if( !vpos_ ) {
            return 0;
        }
        const tripoint vpos = *vpos_;
        const optional_vpart_position target_vp = g->m.veh_at( vpos );
        tripoint_abs_ms target_global( g->m.getabs( vpos ) );
        vehicle_connector_tile *grid_connection = active_tiles::furn_at<vehicle_connector_tile>
                ( target_global );
        if( !target_vp && !grid_connection ) {
            p->add_msg_if_player( _( "There's no vehicle or grid connection there." ) );
            return 0;
        } else if( cable_cbm ) {
            const auto abspos = g->m.getabs( vpos );
            it->set_var( "source_x", abspos.x );
            it->set_var( "source_y", abspos.y );
            it->set_var( "source_z", g->get_levz() );
            set_cable_active( p, it, "cable_charger_link" );
            p->add_msg_if_player( m_good, _( "You are now plugged to the vehicle." ) );
            return 0;
        } else {
            tripoint source_global( it->get_var( "source_x", 0 ),
                                    it->get_var( "source_y", 0 ),
                                    it->get_var( "source_z", 0 ) );
            const vpart_id vpid( it->typeId().str() );
            point vcoords = source_vp->mount();
            vehicle_part source_part( vpid, vcoords, item( *it ) );
            if( grid_connection != nullptr ) {
                source_part.target.first = target_global.raw();
                source_part.target.second = target_global.raw();
                source_part.set_flag( vehicle_part::targets_grid );
                if( p != nullptr && p->has_item( *it ) ) {
                    p->add_msg_if_player( m_good, _( "You connect the %s to the electric grid." ),
                                          source_veh->name );
                    grid_connection->connected_vehicles.emplace_back( g->m.getabs( source_veh->global_pos3() ) );
                    source_veh->install_part( vcoords, source_part );
                }
            } else {
                vehicle *const target_veh = &target_vp->vehicle();
                if( source_veh == target_veh ) {
                    if( p != nullptr && p->has_item( *it ) ) {
                        p->add_msg_if_player( m_warning, _( "The %s already has access to its own electric system!" ),
                                              source_veh->name );
                    }
                    return 0;
                }
                source_part.target.first = target_global.raw();
                source_part.target.second = target_veh->global_square_location().raw();
                source_veh->install_part( vcoords, source_part );
                if( target_vp ) {
                    vcoords = target_vp->mount();
                    vehicle_part target_part( vpid, vcoords, item( *it ) );
                    target_part.target.first = source_global;
                    target_part.target.second = source_veh->global_square_location().raw();
                    target_veh->install_part( vcoords, target_part );
                    if( p != nullptr && p->has_item( *it ) ) {
                        p->add_msg_if_player( m_good, _( "You link up the electric systems of the %1$s and the %2$s." ),
                                              source_veh->name, target_veh->name );
                    }
                }
            }
            return 1; // Let the cable be destroyed.
        }
    }
    return 0;
}
References _, item::activate(), item::active, add_msg(), player::add_msg_if_player(), uilist::addentry(), Creature::as_avatar(), choose_adjacent(), vehicle_connector_tile::connected_vehicles, Character::find_remote_fuel(), active_tiles::furn_at< vehicle_connector_tile >(), g, Character::get_remote_fueled_bionic(), item::get_var(), vehicle::global_pos3(), vehicle::global_square_location(), Character::has_charges(), Creature::has_flag(), visitable< T >::has_item(), vehicle::install_part(), string_id< T >::is_empty(), itype_adv_UPS_off, itype_UPS_off, m_bad, m_good, m_info, m_warning, Creature::moves, vehicle::name, Character::pos(), item::process(), uilist::query(), coords::coord_point< Point, Origin, Scale >::raw(), Character::reset_remote_fuel(), uilist::ret, vehicle_part::set_flag(), item::set_var(), vehicle_part::target, vehicle_part::targets_grid, uilist::text, game_menus::inv::titled_filter_menu(), veh_pointer_or_null(), and Character::worn_with_flag().
Referenced by Item_factory::init().
call_of_tindalos()
int iuse::call_of_tindalos (player * p, item * it, bool , const tripoint &)
Definition at line 4588 of file iuse.cpp.
{
    for( const tripoint &dest : g->m.points_in_radius( p->pos(), 12 ) ) {
        if( g->m.is_cornerfloor( dest ) ) {
            g->m.add_field( dest, fd_tindalos_rift, 3 );
            add_msg( m_info, _( "You hear a low-pitched echoing howl." ) );
        }
    }
    return it->type->charges_to_use();
}
References _, add_msg(), itype::charges_to_use(), fd_tindalos_rift, g, m_info, Character::pos(), and item::type.
Referenced by Item_factory::init().
camera()
int iuse::camera (player * p, item * it, bool , const tripoint &)
Definition at line 7489 of file iuse.cpp.
{
    enum {c_shot, c_photos, c_monsters, c_upload};
    // CAMERA_NPC_PHOTOS is old save variable
    bool found_extended_photos = !it->get_var( "CAMERA_NPC_PHOTOS" ).empty() ||
                                 !it->get_var( "CAMERA_EXTENDED_PHOTOS" ).empty();
    bool found_monster_photos = !it->get_var( "CAMERA_MONSTER_PHOTOS" ).empty();
    uilist amenu;
    amenu.text = _( "What to do with camera?" );
    amenu.addentry( c_shot, true, 't', _( "Take a photo" ) );
    if( !found_extended_photos && !found_monster_photos ) {
        amenu.addentry( c_photos, false, 'l', _( "No photos in memory" ) );
    } else {
        if( found_extended_photos ) {
            amenu.addentry( c_photos, true, 'l', _( "List photos" ) );
        }
        if( found_monster_photos ) {
            amenu.addentry( c_monsters, true, 'm', _( "Your collection of monsters" ) );
        }
        amenu.addentry( c_upload, true, 'u', _( "Upload photos to memory card" ) );
    }
    amenu.query();
    const int choice = amenu.ret;
    if( choice < 0 ) {
        return 0;
    }
    if( c_shot == choice ) {
        const cata::optional<tripoint> aim_point_ = g->look_around();
        if( !aim_point_ ) {
            p->add_msg_if_player( _( "Never mind." ) );
            return 0;
        }
        tripoint aim_point = *aim_point_;
        bool incorrect_focus = false;
        tripoint_range<tripoint> aim_bounds = g->m.points_in_radius( aim_point, 2 );
        std::vector<tripoint> trajectory = line_to( p->pos(), aim_point, 0, 0 );
        trajectory.push_back( aim_point );
        p->moves -= 50;
        sounds::sound( p->pos(), 8, sounds::sound_t::activity, _( "Click." ), true, "tool",
                       "camera_shutter" );
        for( std::vector<tripoint>::iterator point_it = trajectory.begin();
             point_it != trajectory.end();
             ++point_it ) {
            const tripoint trajectory_point = *point_it;
            if( point_it != trajectory.end() ) {
                const tripoint next_point = *( point_it + 1 ); // Trajectory ends on last visible tile
                if( !g->m.sees( p->pos(), next_point, rl_dist( p->pos(), next_point ) + 3 ) ) {
                    p->add_msg_if_player( _( "You have the wrong camera focus." ) );
                    incorrect_focus = true;
                    // recalculate target point
                    aim_point = trajectory_point;
                    aim_bounds = g->m.points_in_radius( trajectory_point, 2 );
                }
            }
            monster *const mon = g->critter_at<monster>( trajectory_point, true );
            player *const guy = g->critter_at<player>( trajectory_point );
            if( mon || guy || trajectory_point == aim_point ) {
                int dist = rl_dist( p->pos(), trajectory_point );
                int camera_bonus = it->has_flag( "CAMERA_PRO" ) ? 10 : 0;
                int photo_quality = 20 - rng( dist, dist * 2 ) * 2 + rng( camera_bonus / 2, camera_bonus );
                if( photo_quality > 5 ) {
                    photo_quality = 5;
                }
                if( photo_quality < 0 ) {
                    photo_quality = 0;
                }
                if( p->is_blind() ) {
                    photo_quality /= 2;
                }
                if( mon ) {
                    monster &z = *mon;
                    // shoot past small monsters and hallucinations
                    if( trajectory_point != aim_point && ( z.type->size <= MS_SMALL || z.is_hallucination() ||
                                                           z.type->in_species( HALLUCINATION ) ) ) {
                        continue;
                    }
                    if( !aim_bounds.is_point_inside( trajectory_point ) ) {
                        // take a photo of the monster that's in the way
                        p->add_msg_if_player( m_warning, _( "A %s got in the way of your photo." ), z.name() );
                        incorrect_focus = true;
                    } else if( trajectory_point != aim_point ) { // shoot past mon that will be in photo anyway
                        continue;
                    }
                    // get an special message if the target is a hallucination
                    if( trajectory_point == aim_point && ( z.is_hallucination() ||
                                                           z.type->in_species( HALLUCINATION ) ) ) {
                        p->add_msg_if_player( _( "Strange there's nothing in the center of picture?" ) );
                    }
                } else if( guy ) {
                    if( trajectory_point == aim_point && guy->is_hallucination() ) {
                        p->add_msg_if_player( _( "Strange %s's not visible on the picture?" ), guy->name );
                    } else if( !aim_bounds.is_point_inside( trajectory_point ) ) {
                        // take a photo of the monster that's in the way
                        p->add_msg_if_player( m_warning, _( "%s got in the way of your photo." ), guy->name );
                        incorrect_focus = true;
                    } else if( trajectory_point != aim_point ) {  // shoot past guy that will be in photo anyway
                        continue;
                    }
                }
                if( incorrect_focus ) {
                    photo_quality = photo_quality == 0 ? 0 : photo_quality - 1;
                }
                std::vector<extended_photo_def> extended_photos;
                std::vector<monster *> monster_vec;
                std::vector<player *> player_vec;
                extended_photo_def photo = photo_def_for_camera_point( trajectory_point, p->pos(), monster_vec,
                                           player_vec );
                photo.quality = photo_quality;
                try {
                    item_read_extended_photos( *it, extended_photos, "CAMERA_EXTENDED_PHOTOS" );
                    extended_photos.push_back( photo );
                    item_write_extended_photos( *it, extended_photos, "CAMERA_EXTENDED_PHOTOS" );
                } catch( const JsonError &e ) {
                    debugmsg( "Error when adding new photo (loaded photos = %i): %s", extended_photos.size(),
                              e.c_str() );
                }
                const bool selfie = std::find( player_vec.begin(), player_vec.end(), p ) != player_vec.end();
                if( selfie ) {
                    p->add_msg_if_player( _( "You took a selfie." ) );
                } else {
                    if( p->is_blind() ) {
                        p->add_msg_if_player( _( "You took a photo of %s." ), photo.name );
                    } else {
                        p->add_msg_if_player( _( "You took a photo of %1$s. It is %2$s." ), photo.name,
                                              photo_quality_name( photo_quality ) );
                    }
                    std::vector<std::string> blinded_names;
                    for( monster * const &monster_p : monster_vec ) {
                        if( dist < 4 && one_in( dist + 2 ) && monster_p->has_flag( MF_SEES ) ) {
                            monster_p->add_effect( effect_blind, rng( 5_turns, 10_turns ) );
                            blinded_names.push_back( monster_p->name() );
                        }
                    }
                    for( player * const &player_p : player_vec ) {
                        if( dist < 4 && one_in( dist + 2 ) && !player_p->is_blind() ) {
                            player_p->add_effect( effect_blind, rng( 5_turns, 10_turns ) );
                            blinded_names.push_back( player_p->name );
                        }
                    }
                    if( !blinded_names.empty() ) {
                        p->add_msg_if_player( _( "%s looks blinded." ), enumerate_as_string( blinded_names.begin(),
                        blinded_names.end(), []( const std::string & it ) {
                            return colorize( it, c_light_blue );
                        } ) );
                    }
                }
                if( !monster_vec.empty() ) {
                    item_save_monsters( *p, *it, monster_vec, photo_quality );
                }
                return it->type->charges_to_use();
            }
        }
        return it->type->charges_to_use();
    }
    if( c_photos == choice ) {
        show_photo_selection( *p, *it, "CAMERA_EXTENDED_PHOTOS" );
        return it->type->charges_to_use();
    }
    if( c_monsters == choice ) {
        if( p->is_blind() ) {
            p->add_msg_if_player( _( "You can't see the camera screen, you're blind." ) );
            return 0;
        }
        uilist pmenu;
        pmenu.text = _( "Your collection of monsters:" );
        std::vector<mtype_id> monster_photos;
        std::vector<std::string> descriptions;
        std::istringstream f_mon( it->get_var( "CAMERA_MONSTER_PHOTOS" ) );
        std::string s;
        int k = 0;
        while( getline( f_mon, s, ',' ) ) {
            if( s.empty() ) {
                continue;
            }
            monster_photos.push_back( mtype_id( s ) );
            std::string menu_str;
            const monster dummy( monster_photos.back() );
            menu_str = dummy.name();
            descriptions.push_back( dummy.type->get_description() );
            getline( f_mon, s, ',' );
            char *chq = &s[0];
            const int quality = atoi( chq );
            menu_str += " [" + photo_quality_name( quality ) + "]";
            pmenu.addentry( k++, true, -1, menu_str.c_str() );
        }
        int choice;
        do {
            pmenu.query();
            choice = pmenu.ret;
            if( choice < 0 ) {
                break;
            }
            popup( "%s", descriptions[choice].c_str() );
        } while( true );
        return it->type->charges_to_use();
    }
    if( c_upload == choice ) {
        if( p->is_blind() ) {
            p->add_msg_if_player( _( "You can't see the camera screen, you're blind." ) );
            return 0;
        }
        p->moves -= to_moves<int>( 2_seconds );
        avatar *you = p->as_avatar();
        item_location loc;
        if( you != nullptr ) {
            loc = game_menus::inv::titled_filter_menu( []( const item & it ) {
                return it.has_flag( "MC_MOBILE" );
            }, *you, _( "Insert memory card" ) );
        }
        if( !loc ) {
            p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
            return it->type->charges_to_use();
        }
        item &mc = *loc;
        if( !mc.has_flag( "MC_MOBILE" ) ) {
            p->add_msg_if_player( m_info, _( "This is not a compatible memory card." ) );
            return it->type->charges_to_use();
        }
        init_memory_card_with_random_stuff( mc );
        if( mc.has_flag( "MC_ENCRYPTED" ) ) {
            if( !query_yn( _( "This memory card is encrypted.  Format and clear data?" ) ) ) {
                return it->type->charges_to_use();
            }
        }
        if( mc.has_flag( "MC_HAS_DATA" ) ) {
            if( !query_yn( _( "Are you sure you want to clear the old data on the card?" ) ) ) {
                return it->type->charges_to_use();
            }
        }
        mc.convert( itype_mobile_memory_card );
        mc.clear_vars();
        mc.unset_flags();
        mc.set_flag( "MC_HAS_DATA" );
        mc.set_var( "MC_MONSTER_PHOTOS", it->get_var( "CAMERA_MONSTER_PHOTOS" ) );
        mc.set_var( "MC_EXTENDED_PHOTOS", it->get_var( "CAMERA_EXTENDED_PHOTOS" ) );
        p->add_msg_if_player( m_info,
                              _( "You upload your photos and monster collection to memory card." ) );
        return it->type->charges_to_use();
    }
    return it->type->charges_to_use();
}
References _, sounds::activity, player::add_msg_if_player(), uilist::addentry(), Creature::as_avatar(), JsonError::c_str(), itype::charges_to_use(), item::clear_vars(), item::convert(), debugmsg, effect_blind, enumerate_as_string(), detail::find(), g, mtype::get_description(), item::get_var(), HALLUCINATION, item::has_flag(), mtype::in_species(), init_memory_card_with_random_stuff(), Character::is_blind(), monster::is_hallucination(), tripoint_range< Tripoint >::is_point_inside(), item_read_extended_photos(), item_save_monsters(), item_write_extended_photos(), itype_mobile_memory_card, line_to(), m_info, m_warning, MF_SEES, Creature::moves, MS_SMALL, extended_photo_def::name, monster::name(), one_in(), photo_def_for_camera_point(), photo_quality_name(), popup(), Character::pos(), extended_photo_def::quality, uilist::query(), query_yn(), uilist::ret, rl_dist(), rng(), item::set_flag(), item::set_var(), show_photo_selection(), mtype::size, sounds::sound(), uilist::text, game_menus::inv::titled_filter_menu(), item::type, monster::type, and item::unset_flags().
Referenced by Item_factory::init().
can_goo()
int iuse::can_goo (player * p, item * it, bool , const tripoint &)
Definition at line 3491 of file iuse.cpp.
{
    it->convert( itype_canister_empty );
    int tries = 0;
    tripoint goop;
    goop.z = p->posz();
    do {
        goop.x = p->posx() + rng( -2, 2 );
        goop.y = p->posy() + rng( -2, 2 );
        tries++;
    } while( g->m.impassable( goop ) && tries < 10 );
    if( tries == 10 ) {
        return 0;
    }
    if( monster *const mon_ptr = g->critter_at<monster>( goop ) ) {
        monster &critter = *mon_ptr;
        if( g->u.sees( goop ) ) {
            add_msg( _( "Black goo emerges from the canister and envelopes a %s!" ),
                     critter.name() );
        }
        critter.poly( mon_blob );
        critter.set_speed_base( critter.get_speed_base() - rng( 5, 25 ) );
        critter.set_hp( critter.get_speed() );
    } else {
        if( g->u.sees( goop ) ) {
            add_msg( _( "Living black goo emerges from the canister!" ) );
        }
        if( monster *const goo = g->place_critter_at( mon_blob, goop ) ) {
            goo->friendly = -1;
        }
    }
    if( x_in_y( 3.0, 4.0 ) ) {
        tries = 0;
        bool found = false;
        do {
            goop.x = p->posx() + rng( -2, 2 );
            goop.y = p->posy() + rng( -2, 2 );
            tries++;
            found = g->m.passable( goop ) && g->m.tr_at( goop ).is_null();
        } while( !found && tries < 10 );
        if( found ) {
            if( g->u.sees( goop ) ) {
                add_msg( m_warning, _( "A nearby splatter of goo forms into a goo pit." ) );
            }
            g->m.trap_set( goop, tr_goo );
        } else {
            return 0;
        }
    }
    return it->type->charges_to_use();
}
References _, add_msg(), itype::charges_to_use(), item::convert(), g, Creature::get_speed(), Creature::get_speed_base(), trapfunc::goo(), itype_canister_empty, m_warning, mon_blob, monster::name(), monster::poly(), Character::posx(), Character::posy(), Character::posz(), rng(), monster::set_hp(), Creature::set_speed_base(), tr_goo, item::type, tripoint::x, x_in_y(), tripoint::y, and tripoint::z.
Referenced by Item_factory::init().
capture_monster_act()
int iuse::capture_monster_act (player * p, item * it, bool , const tripoint & pos)
Definition at line 9263 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot capture a creature mounted." ) );
        return 0;
    }
    if( it->has_var( "contained_name" ) ) {
        // Remember contained_name for messages after release_monster erases it
        const std::string contained_name = it->get_var( "contained_name", "" );
        if( it->release_monster( pos ) ) {
            // It's been activated somewhere where there isn't a player or monster, good.
            return 0;
        }
        if( it->has_flag( "PLACE_RANDOMLY" ) ) {
            if( it->release_monster( p->pos(), 1 ) ) {
                return 0;
            }
            p->add_msg_if_player( _( "There is no place to put the %s." ), contained_name );
            return 0;
        } else {
            const std::string query = string_format( _( "Place the %s where?" ), contained_name );
            const cata::optional<tripoint> pos_ = choose_adjacent( query );
            if( !pos_ ) {
                return 0;
            }
            if( it->release_monster( *pos_ ) ) {
                p->add_msg_if_player( _( "You release the %s." ), contained_name );
                return 0;
            }
            p->add_msg_if_player( m_info, _( "You cannot place the %s there!" ), contained_name );
            return 0;
        }
    } else {
        if( !it->has_property( "monster_size_capacity" ) ) {
            debugmsg( "%s has no monster_size_capacity.", it->tname() );
            return 0;
        }
        const std::string capacity = it->get_property_string( "monster_size_capacity" );
        if( Creature::size_map.count( capacity ) == 0 ) {
            debugmsg( "%s has invalid monster_size_capacity %s.",
                      it->tname(), capacity.c_str() );
            return 0;
        }
        const std::function<bool( const tripoint & )> adjacent_capturable = []( const tripoint & pnt ) {
            const monster *mon_ptr = g->critter_at<monster>( pnt );
            return mon_ptr != nullptr;
        };
        const std::string query = string_format( _( "Grab which creature to place in the %s?" ),
                                  it->tname() );
        const cata::optional<tripoint> target_ = choose_adjacent_highlight( query,
                _( "There is no creature nearby you can capture." ), adjacent_capturable, false );
        if( !target_ ) {
            p->add_msg_if_player( m_info, _( "You cannot use a %s there." ), it->tname() );
            return 0;
        }
        const tripoint target = *target_;
        // Capture the thing, if it's on the target square.
        if( const monster *const mon_ptr = g->critter_at<monster>( target ) ) {
            const monster &f = *mon_ptr;
            if( f.get_size() > Creature::size_map.find( capacity )->second ) {
                p->add_msg_if_player( m_info, _( "The %1$s is too big to put in your %2$s." ),
                                      f.type->nname(), it->tname() );
                return 0;
            }
            // TODO: replace this with some kind of melee check.
            int chance = f.hp_percentage() / 10;
            // A weaker monster is easier to capture.
            // If the monster is friendly, then put it in the item
            // without checking if it rolled a success.
            if( f.friendly != 0 || one_in( chance ) ) {
                p->add_msg_if_player( _( "You capture the %1$s in your %2$s." ),
                                      f.type->nname(), it->tname() );
                return it->contain_monster( target );
            } else {
                p->add_msg_if_player( m_bad, _( "The %1$s avoids your attempts to put it in the %2$s." ),
                                      f.type->nname(), it->type->nname( 1 ) );
            }
            p->moves -= to_moves<int>( 1_seconds );
        } else {
            add_msg( _( "The %s can't capture nothing" ), it->tname() );
            return 0;
        }
    }
    return 0;
}
References _, add_msg(), player::add_msg_if_player(), choose_adjacent(), choose_adjacent_highlight(), item::contain_monster(), detail::count(), debugmsg, monster::friendly, g, item::get_property_string(), monster::get_size(), item::get_var(), item::has_flag(), item::has_property(), item::has_var(), monster::hp_percentage(), Character::is_mounted(), m_bad, m_info, Creature::moves, itype::nname(), mtype::nname(), one_in(), Character::pos(), item::release_monster(), Creature::size_map, string_format(), item::tname(), item::type, and monster::type.
Referenced by capture_monster_veh(), and Item_factory::init().
capture_monster_veh()
int iuse::capture_monster_veh (player * p, item * it, bool , const tripoint & pos)
Definition at line 9209 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( !it->has_flag( "VEHICLE" ) ) {
        p->add_msg_if_player( m_info, _( "The %s must be installed in a vehicle before being loaded." ),
                              it->tname() );
        return 0;
    }
    capture_monster_act( p, it, false, pos );
    return 0;
}
References _, player::add_msg_if_player(), capture_monster_act(), item::has_flag(), Character::is_mounted(), m_info, and item::tname().
Referenced by Item_factory::init().
carver_off()
int iuse::carver_off (player * p, item * it, bool , const tripoint &)
Definition at line 3114 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           false,
                           true,
                           20, _( "The electric carver's serrated blades start buzzing!" ),
                           _( "You pull the trigger, but nothing happens." ) );
}
References _, and toolweapon_off().
Referenced by Item_factory::init().
carver_on()
int iuse::carver_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3212 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "electric carver" ),
                          true,
                          10, 8, _( "Your electric carver buzzes." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
catfood()
int iuse::catfood (player * p, item * it, bool , const tripoint &)
Definition at line 1632 of file iuse.cpp.
{
    return petfood( *p, *it, CATFOOD );
}
References CATFOOD, and petfood().
Referenced by Item_factory::init().
cauterize_hotplate()
int iuse::cauterize_hotplate (player * , item * , bool , const tripoint &)
chainsaw_off()
int iuse::chainsaw_off (player * p, item * it, bool , const tripoint &)
Definition at line 3078 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           false,
                           rng( 0, 10 ) - it->damage_level( 4 ) > 5 && !p->is_underwater(),
                           20, _( "With a roar, the chainsaw leaps to life!" ),
                           _( "You yank the cord, but nothing happens." ) );
}
References _, item::damage_level(), Creature::is_underwater(), rng(), and toolweapon_off().
Referenced by Item_factory::init().
chainsaw_on()
int iuse::chainsaw_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3178 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "chainsaw" ),
                          false,
                          15, 12, _( "Your chainsaw rumbles." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
chew()
int iuse::chew (player * p, item * it, bool , const tripoint &)
Definition at line 1096 of file iuse.cpp.
{
    // TODO: Add more effects?
    p->add_msg_if_player( _( "You chew your %s." ), it->tname() );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), item::tname(), and item::type.
Referenced by player::eat(), Item_factory::init(), and Character::modify_morale().
chop_logs()
int iuse::chop_logs (player * p, item * it, bool t, const tripoint &)
Definition at line 4810 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::set<ter_id> allowed_ter_id {
        t_trunk,
        t_stump
    };
    const std::function<bool( const tripoint & )> f = [&allowed_ter_id]( const tripoint & pnt ) {
        const ter_id type = g->m.ter( pnt );
        const bool is_allowed_terrain = allowed_ter_id.find( type ) != allowed_ter_id.end();
        return is_allowed_terrain;
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Chop which tree trunk?" ), _( "There is no tree trunk to chop nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    if( !f( pnt ) ) {
        p->add_msg_if_player( m_info, _( "You can't chop that." ) );
        return 0;
    }
    int moves = chop_moves( *p, *it );
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves = moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( ACT_CHOP_LOGS, moves, -1, p->get_item_position( it ) );
    p->activity.placement = g->m.getabs( pnt );
    return it->type->charges_to_use();
}
References _, ACT_CHOP_LOGS, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), chop_moves(), g, Character::get_item_position(), Character::is_mounted(), m_info, player_activity::placement, t_stump, t_trunk, type, and item::type.
Referenced by Item_factory::init().
chop_moves()
int iuse::chop_moves (Character & ch, item & tool)
Definition at line 4755 of file iuse.cpp.
{
    // quality of tool
    const int quality = tool.get_quality( qual_AXE );
    // attribute; regular tools - based on STR, powered tools - based on DEX
    const int attr = tool.has_flag( "POWERED" ) ? ch.dex_cur : ch.str_cur;
    return to_moves<int>( std::max( 10_minutes, time_duration::from_minutes( 60 - attr ) / quality ) );
}
References Character::dex_cur, time_duration::from_minutes(), qual_AXE, Character::str_cur, and tool.
Referenced by chop_logs(), chop_tree(), and chop_tree_activity().
chop_tree()
int iuse::chop_tree (player * p, item * it, bool t, const tripoint &)
Definition at line 4766 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::function<bool( const tripoint & )> f = []( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        return g->m.has_flag( "TREE", pnt );
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Chop down which tree?" ), _( "There is no tree to chop down nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info, _( "You're not stern enough to shave yourself with THIS." ) );
        } else {
            p->add_msg_if_player( m_info, _( "You can't chop down that." ) );
        }
        return 0;
    }
    int moves = chop_moves( *p, *it );
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves = moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( ACT_CHOP_TREE, moves, -1, p->get_item_position( it ) );
    p->activity.placement = g->m.getabs( pnt );
    return it->type->charges_to_use();
}
References _, ACT_CHOP_TREE, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), chop_moves(), g, Character::get_item_position(), Character::is_mounted(), m_info, player_activity::placement, Character::pos(), and item::type.
Referenced by Item_factory::init().
circsaw_on()
int iuse::circsaw_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3226 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "circular saw" ),
                          true,
                          15, 7, _( "Your circular saw buzzes." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
clear_rubble()
int iuse::clear_rubble (player * p, item * it, bool , const tripoint &)
Explanation of ACT_CLEAR_RUBBLE activity values:
coords[0]: Where the rubble is. index: The bonus, for calculating hunger and thirst penalties.
Definition at line 2941 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::function<bool( const tripoint & )> f = []( const tripoint & pnt ) {
        return g->m.has_flag( "RUBBLE", pnt );
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Clear rubble where?" ), _( "There is no rubble to clear nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    if( !f( pnt ) ) {
        p->add_msg_if_player( m_bad, _( "There's no rubble to clear." ) );
        return 0;
    }
    int moves = to_moves<int>( 30_seconds );
    int bonus = std::max( it->get_quality( quality_id( "DIG" ) ) - 1, 1 );
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves = moves * ( 10 - helpers.size() ) / 10;
    player_activity act( ACT_CLEAR_RUBBLE, moves / bonus, bonus );
    p->assign_activity( act );
    p->activity.placement = pnt;
    return it->type->charges_to_use();
}
References _, act, ACT_CLEAR_RUBBLE, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), g, item::get_quality(), Character::is_mounted(), m_bad, m_info, player_activity::placement, and item::type.
Referenced by Item_factory::init().
coin_flip()
int iuse::coin_flip (player * p, item * it, bool , const tripoint &)
Definition at line 9628 of file iuse.cpp.
{
    p->add_msg_if_player( m_info, _( "You flip a %s." ), it->tname() );
    p->add_msg_if_player( m_info, one_in( 2 ) ? _( "Heads!" ) : _( "Tails!" ) );
    return 0;
}
References _, player::add_msg_if_player(), m_info, one_in(), and item::tname().
Referenced by Item_factory::init().
combatsaw_off()
int iuse::combatsaw_off (player * p, item * it, bool , const tripoint &)
Definition at line 3060 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           true,
                           !p->is_underwater(),
                           30, _( "With a snarl, the combat chainsaw screams to life!" ),
                           _( "You yank the cord, but nothing happens." ) );
}
References _, Creature::is_underwater(), and toolweapon_off().
Referenced by Item_factory::init().
combatsaw_on()
int iuse::combatsaw_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3164 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "combat chainsaw" ),
                          false,
                          12, 18, _( "Your combat chainsaw growls." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
contacts()
int iuse::contacts (player * p, item * it, bool , const tripoint &)
Definition at line 5782 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    const time_duration duration = rng( 6_days, 8_days );
    if( p->has_effect( effect_contacts ) ) {
        if( query_yn( _( "Replace your current lenses?" ) ) ) {
            p->moves -= to_moves<int>( 20_seconds );
            p->add_msg_if_player( _( "You replace your current %s." ), it->tname() );
            p->remove_effect( effect_contacts );
            p->add_effect( effect_contacts, duration );
            return it->type->charges_to_use();
        } else {
            p->add_msg_if_player( _( "You don't do anything with your %s." ), it->tname() );
            return 0;
        }
    } else if( p->has_trait( trait_HYPEROPIC ) || p->has_trait( trait_MYOPIC ) ||
               p->has_trait( trait_URSINE_EYE ) ) {
        p->moves -= to_moves<int>( 20_seconds );
        p->add_msg_if_player( _( "You put the %s in your eyes." ), it->tname() );
        p->add_effect( effect_contacts, duration );
        return it->type->charges_to_use();
    } else {
        p->add_msg_if_player( m_info, _( "Your vision is fine already." ) );
        return 0;
    }
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_contacts, Creature::has_effect(), Character::has_trait(), Creature::is_underwater(), m_info, Creature::moves, query_yn(), Creature::remove_effect(), rng(), item::tname(), trait_HYPEROPIC, trait_MYOPIC, trait_URSINE_EYE, and item::type.
Referenced by Item_factory::init().
craft()
int iuse::craft (player * p, item * it, bool , const tripoint & pos)
Definition at line 9537 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::string craft_name = it->tname();
    if( !it->is_craft() ) {
        debugmsg( "Attempted to start working on non craft '%s.'  Aborting.", craft_name );
        return 0;
    }
    if( !p->can_continue_craft( *it ) ) {
        return 0;
    }
    const recipe &rec = it->get_making();
    if( p->has_recipe( &rec, p->crafting_inventory(), p->get_crafting_helpers() ) == -1 ) {
        p->add_msg_player_or_npc(
            _( "You don't know the recipe for the %s and can't continue crafting." ),
            _( "<npcname> doesn't know the recipe for the %s and can't continue crafting." ),
            rec.result_name() );
        return 0;
    }
    bench_location best_bench = find_best_bench( *p, *it );
    p->add_msg_player_or_npc(
        pgettext( "in progress craft", "You start working on the %s." ),
        pgettext( "in progress craft", "<npcname> starts working on the %s." ), craft_name );
    p->assign_activity( ACT_CRAFT );
    // Horrible! We have to find the item again...
    item_location where;
    if( p->has_item( *it ) ) {
        where = item_location( *p, it );
    } else if( const cata::optional<vpart_reference> vp = g->m.veh_at( pos ).part_with_feature( "CARGO",
               false ) ) {
        const vehicle_cursor vc = vehicle_cursor( vp->vehicle(), vp->part_index() );
        if( vc.has_item( *it ) ) {
            where = item_location( vc, it ) ;
        }
    }
    if( !where ) {
        map_cursor mc = map_cursor( pos );
        if( mc.has_item( *it ) ) {
            where = item_location( map_cursor( pos ), it );
        } else {
            debugmsg( "Incomplete item couldn't be found" );
            return 0;
        }
    }
    p->activity.targets.push_back( where );
    p->activity.coords.push_back( best_bench.position );
    p->activity.values.push_back( 0 ); // Not a long craft
    // Ugly
    p->activity.values.push_back( static_cast<int>( best_bench.type ) );
    return 0;
}
References _, ACT_CRAFT, Character::activity, player::add_msg_if_player(), player::add_msg_player_or_npc(), Character::assign_activity(), player::can_continue_craft(), player_activity::coords, Character::crafting_inventory(), debugmsg, find_best_bench(), g, player::get_crafting_helpers(), item::get_making(), visitable< T >::has_item(), player::has_recipe(), item::is_craft(), Character::is_mounted(), m_info, pgettext(), bench_location::position, recipe::result_name(), player_activity::targets, item::tname(), bench_location::type, and player_activity::values.
Referenced by best_bench_here(), complete_craft(), activity_handlers::craft_do_turn(), craft_progress_message(), crafting_speed_multiplier(), destroy_random_component(), find_best_bench(), get_most_rotten_component(), Item_factory::init(), and workbench_crafting_speed_multiplier().
crowbar()
int iuse::crowbar (player * p, item * it, bool , const tripoint & pos)
Strength speeds up crowbar prying attempts Strength increases chance of crowbar prying success Strength reduces chance of breaking window with crowbar Mechanics reduces chance of breaking window with crowbar
Definition at line 2417 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const pry_result *pry = nullptr;
    bool pry_furn;
    const std::function<bool( const tripoint & )> can_pry = [&p]( const tripoint & pnt ) {
        if( pnt == p->pos() ) {
            return false;
        }
        const ter_id ter = g->m.ter( pnt );
        const furn_id furn = g->m.furn( pnt );
        const bool is_allowed = ter->pry.pry_quality != -1 || furn->pry.pry_quality != -1;
        return is_allowed;
    };
    const cata::optional<tripoint> pnt_ = ( pos != p->pos() ) ? pos : choose_adjacent_highlight(
            _( "Pry where?" ), _( "There is nothing to pry nearby." ), can_pry, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id ter = g->m.ter( pnt );
    const furn_id furn = g->m.furn( pnt );
    if( !can_pry( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info, _( "You attempt to pry open your wallet "
                                             "but alas.  You are just too miserly." ) );
        } else if( !ter->has_flag( "LOCKED" ) && ter->open ) {
            p->add_msg_if_player( m_info, _( "You notice the door is unlocked, so you simply open it." ) );
            g->m.ter_set( pnt, ter->open );
        } else {
            p->add_msg_if_player( m_info, _( "You can't pry that." ) );
        }
        return 0;
    }
    if( furn->pry.pry_quality != -1 ) {
        pry_furn = true;
        pry = &furn->pry;
    } else {
        pry_furn = false;
        pry = &ter->pry;
    }
    // Doors need PRY 2 which is on a crowbar, crates need PRY 1 which is on a crowbar
    // & a claw hammer.
    // The iexamine function for crate supplies a hammer object.
    // So this stops the player (A)ctivating a Hammer with a Crowbar in their backpack
    // then managing to open a door.
    const int pry_level = it->get_quality( quality_id( "PRY" ) );
    if( pry_level < pry->pry_quality ) {
        p->add_msg_if_player( _( "You can't get sufficient leverage to open that with your %s." ),
                              it->tname() );
        p->mod_moves( 10 ); // spend a few moves trying it.
        return 0;
    }
    // For every level of PRY over the requirement, remove n from the difficulty.
    // Then multiply n by pry_bonus_mult. It's recommended that you don't allow
    // the result to be negative if you can help it.
    int diff = pry->difficulty;
    diff -= ( ( pry_level - pry->pry_quality ) * pry->pry_bonus_mult );
    /** @EFFECT_STR speeds up crowbar prying attempts */
    p->mod_moves( -std::max( 20, diff * 50 - p->str_cur * 10 ) );
    /** @EFFECT_STR increases chance of crowbar prying success */
    if( dice( 4, diff ) < dice( 4, p->str_cur ) ) {
        p->add_msg_if_player( m_good, pry->success_message );
        if( pry_furn ) {
            g->m.furn_set( pnt, pry->new_furn_type );
        } else {
            g->m.ter_set( pnt, pry->new_ter_type );
        }
        if( pry->noise > 0 ) {
            sounds::sound( pnt, pry->noise, sounds::sound_t::combat, pry->sound, true, "tool", "crowbar" );
        }
        g->m.spawn_items( pnt, item_group::items_from( pry->pry_items, calendar::turn ) );
        if( pry->alarm ) {
            g->events().send<event_type::triggers_alarm>( p->getID() );
            sounds::sound( p->pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), true, "environment",
                           "alarm" );
            if( !g->timed_events.queued( TIMED_EVENT_WANTED ) ) {
                g->timed_events.add( TIMED_EVENT_WANTED, calendar::turn + 30_minutes, 0,
                                     p->global_sm_location() );
            }
        }
    } else {
        if( pry->breakable ) {
            //chance of breaking the glass if pry attempt fails
            /** @EFFECT_STR reduces chance of breaking window with crowbar */
            /** @EFFECT_MECHANICS reduces chance of breaking window with crowbar */
            if( dice( 4, diff ) > ( dice( 2, p->get_skill_level( skill_mechanics ) ) + dice( 2,
                                    p->str_cur ) ) * pry_level ) {
                p->add_msg_if_player( m_mixed, pry->break_message );
                sounds::sound( pnt, pry->break_noise, sounds::sound_t::combat, pry->break_sound, true, "smash",
                               "door" );
                if( pry_furn ) {
                    g->m.furn_set( pnt, pry->break_furn_type );
                } else {
                    g->m.ter_set( pnt, pry->break_ter_type );
                }
                g->m.spawn_items( pnt, item_group::items_from( pry->break_items, calendar::turn ) );
                if( pry->alarm ) {
                    g->events().send<event_type::triggers_alarm>( p->getID() );
                    sounds::sound( p->pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), true, "environment",
                                   "alarm" );
                    if( !g->timed_events.queued( TIMED_EVENT_WANTED ) ) {
                        g->timed_events.add( TIMED_EVENT_WANTED, calendar::turn + 30_minutes, 0,
                                             p->global_sm_location() );
                    }
                }
                return it->type->charges_to_use();
            }
        }
        p->add_msg_if_player( pry->fail_message );
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), pry_result::alarm, sounds::alarm, pry_result::break_furn_type, pry_result::break_items, pry_result::break_message, pry_result::break_noise, pry_result::break_sound, pry_result::break_ter_type, pry_result::breakable, itype::charges_to_use(), choose_adjacent_highlight(), sounds::combat, dice(), pry_result::difficulty, pry_result::fail_message, g, item::get_quality(), Character::get_skill_level(), Character::getID(), Character::global_sm_location(), map_data_common_t::has_flag(), Character::is_mounted(), item_group::items_from(), m_good, m_info, m_mixed, Creature::mod_moves(), pry_result::new_furn_type, pry_result::new_ter_type, pry_result::noise, ter_t::open, Character::pos(), map_data_common_t::pry, pry_result::pry_bonus_mult, pry_result::pry_items, pry_result::pry_quality, skill_mechanics, pry_result::sound, sounds::sound(), Character::str_cur, pry_result::success_message, TIMED_EVENT_WANTED, item::tname(), triggers_alarm, calendar::turn, and item::type.
Referenced by apply_prying_tool(), and Item_factory::init().
cs_lajatang_off()
int iuse::cs_lajatang_off (player * p, item * it, bool , const tripoint &)
Definition at line 3096 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           false,
                           rng( 0, 10 ) - it->damage_level( 4 ) > 5 && it->ammo_remaining() > 1 && !p->is_underwater(),
                           40, _( "With a roar, the chainsaws leap to life!" ),
                           _( "You yank the cords, but nothing happens." ) );
}
References _, item::ammo_remaining(), item::damage_level(), Creature::is_underwater(), rng(), and toolweapon_off().
Referenced by Item_factory::init().
cs_lajatang_on()
int iuse::cs_lajatang_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3192 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "chainsaw lajatang" ),
                          false,
                          15, 12, _( "Your chainsaws rumble." ),
                          true );
    // The chainsaw lajatang drains 2 charges per turn, since
    // there are two chainsaws.
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
cut_log_into_planks()
void iuse::cut_log_into_planks (player & p)
Definition at line 4705 of file iuse.cpp.
{
    if( p.is_mounted() ) {
        p.add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return;
    }
    const int moves = to_moves<int>( 20_minutes );
    p.add_msg_if_player( _( "You cut the log into planks." ) );
    p.assign_activity( ACT_CHOP_PLANKS, moves, -1 );
    p.activity.placement = g->m.getabs( p.pos() );
}
References _, ACT_CHOP_PLANKS, Character::activity, player::add_msg_if_player(), Character::assign_activity(), g, Character::is_mounted(), m_info, player_activity::placement, and Character::pos().
Referenced by construct::done_trunk_plank(), and lumber().
datura()
int iuse::datura (player * p, item * it, bool , const tripoint &)
Definition at line 958 of file iuse.cpp.
{
    if( p->is_npc() ) {
        return 0;
    }
    p->add_effect( effect_datura, rng( 3_hours, 13_hours ) );
    p->add_msg_if_player( _( "You eat the datura seed." ) );
    if( p->has_trait( trait_SPIRITUAL ) ) {
        p->add_morale( MORALE_FOOD_GOOD, 36, 72, 2_hours, 1_hours, false, it->type );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), Character::add_morale(), player::add_msg_if_player(), itype::charges_to_use(), effect_datura, Character::has_trait(), player::is_npc(), MORALE_FOOD_GOOD, rng(), trait_SPIRITUAL, and item::type.
Referenced by Item_factory::init().
dig()
int iuse::dig (player * p, item * it, bool t, const tripoint &)
Definition at line 2706 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const tripoint dig_point = p->pos();
    const bool can_dig_here = g->m.has_flag( "DIGGABLE", dig_point ) &&
                              !g->m.has_furn( dig_point ) &&
                              g->m.tr_at( dig_point ).is_null() &&
                              ( g->m.ter( dig_point ) == t_grave_new || g->m.i_at( dig_point ).empty() ) &&
                              !g->m.veh_at( dig_point );
    if( !can_dig_here ) {
        p->add_msg_if_player(
            _( "You can't dig a pit in this location.  Ensure it is clear diggable ground with no items or obstacles." ) );
        return 0;
    }
    const bool can_deepen = g->m.has_flag( "DIGGABLE_CAN_DEEPEN", dig_point );
    const bool grave = g->m.ter( dig_point ) == t_grave;
    if( !p->crafting_inventory().has_quality( qual_DIG, 2 ) ) {
        if( can_deepen ) {
            p->add_msg_if_player( _( "You can't deepen this pit without a proper shovel." ) );
            return 0;
        } else if( grave ) {
            p->add_msg_if_player( _( "You can't exhume a grave without a proper shovel." ) );
            return 0;
        }
    }
    const std::function<bool( const tripoint & )> f = []( const tripoint & pnt ) {
        return g->m.passable( pnt );
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Deposit excavated materials where?" ),
            _( "There is nowhere to deposit the excavated materials." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint deposit_point = *pnt_;
    if( !f( deposit_point ) ) {
        p->add_msg_if_player(
            _( "You can't deposit the excavated materials onto an impassable location." ) );
        return 0;
    }
    if( grave ) {
        if( g->u.has_trait( trait_SPIRITUAL ) && !g->u.has_trait( trait_PSYCHOPATH ) &&
            g->u.query_yn( _( "Would you really touch the sacred resting place of the dead?" ) ) ) {
            add_msg( m_info, _( "Exhuming a grave is really against your beliefs." ) );
            g->u.add_morale( MORALE_GRAVEDIGGER, -50, -100, 48_hours, 12_hours );
            if( one_in( 3 ) ) {
                g->u.vomit();
            }
        } else if( g->u.has_trait( trait_PSYCHOPATH ) ) {
            p->add_msg_if_player( m_good,
                                  _( "Exhuming a grave is fun now, where there is no one to object." ) );
            g->u.add_morale( MORALE_GRAVEDIGGER, 25, 50, 2_hours, 1_hours );
        } else if( !g->u.has_trait( trait_EATDEAD ) &&
                   !g->u.has_trait( trait_SAPROVORE ) ) {
            p->add_msg_if_player( m_bad, _( "Exhuming this grave is utterly disgusting!" ) );
            g->u.add_morale( MORALE_GRAVEDIGGER, -25, -50, 2_hours, 1_hours );
            if( one_in( 5 ) ) {
                p->vomit();
            }
        }
    }
    digging_moves_and_byproducts moves_and_byproducts = dig_pit_moves_and_byproducts( p, it,
            can_deepen, false );
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves_and_byproducts.moves = moves_and_byproducts.moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( player_activity( dig_activity_actor(
            moves_and_byproducts.moves,
            dig_point,
            moves_and_byproducts.result_terrain.id().str(),
            deposit_point,
            moves_and_byproducts.spawn_count,
            moves_and_byproducts.byproducts_item_group
                                         ) ) );
    return it->type->charges_to_use();
}
References _, add_msg(), player::add_msg_if_player(), Character::assign_activity(), digging_moves_and_byproducts::byproducts_item_group, itype::charges_to_use(), choose_adjacent_highlight(), Character::crafting_inventory(), dig_pit_moves_and_byproducts(), g, visitable< T >::has_quality(), int_id< T >::id(), Character::is_mounted(), m_bad, m_good, m_info, MORALE_GRAVEDIGGER, digging_moves_and_byproducts::moves, one_in(), Character::pos(), qual_DIG, digging_moves_and_byproducts::result_terrain, digging_moves_and_byproducts::spawn_count, string_id< T >::str(), t_grave, t_grave_new, trait_EATDEAD, trait_PSYCHOPATH, trait_SAPROVORE, trait_SPIRITUAL, item::type, and Character::vomit().
Referenced by construct::done_digormine_stair(), and Item_factory::init().
dig_channel()
int iuse::dig_channel (player * p, item * it, bool t, const tripoint &)
Definition at line 2802 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const tripoint dig_point = p->pos();
    tripoint north = dig_point + point_north;
    tripoint south = dig_point + point_south;
    tripoint west = dig_point + point_west;
    tripoint east = dig_point + point_east;
    const bool can_dig_here = g->m.has_flag( flag_DIGGABLE, dig_point ) &&
                              !g->m.has_furn( dig_point ) &&
                              g->m.tr_at( dig_point ).is_null() && g->m.i_at( dig_point ).empty() && !g->m.veh_at( dig_point ) &&
                              ( g->m.has_flag( flag_CURRENT, north ) ||  g->m.has_flag( flag_CURRENT, south ) ||
                                g->m.has_flag( flag_CURRENT, east ) ||  g->m.has_flag( flag_CURRENT, west ) );
    if( !can_dig_here ) {
        p->add_msg_if_player(
            _( "You can't dig a channel in this location.  Ensure it is clear diggable ground with no items or obstacles, adjacent to flowing water." ) );
        return 0;
    }
    const std::function<bool( const tripoint & )> f = []( const tripoint & pnt ) {
        return g->m.passable( pnt );
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Deposit excavated materials where?" ),
            _( "There is nowhere to deposit the excavated materials." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint deposit_point = *pnt_;
    if( !f( deposit_point ) ) {
        p->add_msg_if_player(
            _( "You can't deposit the excavated materials onto an impassable location." ) );
        return 0;
    }
    digging_moves_and_byproducts moves_and_byproducts = dig_pit_moves_and_byproducts( p, it, false,
            true );
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves_and_byproducts.moves = moves_and_byproducts.moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( player_activity( dig_channel_activity_actor(
            moves_and_byproducts.moves,
            dig_point,
            moves_and_byproducts.result_terrain.id().str(),
            deposit_point,
            moves_and_byproducts.spawn_count,
            moves_and_byproducts.byproducts_item_group
                                         ) ) );
    return it->type->charges_to_use();
}
References _, add_msg(), player::add_msg_if_player(), Character::assign_activity(), digging_moves_and_byproducts::byproducts_item_group, itype::charges_to_use(), choose_adjacent_highlight(), dig_pit_moves_and_byproducts(), flag_CURRENT(), flag_DIGGABLE(), g, int_id< T >::id(), Character::is_mounted(), m_info, digging_moves_and_byproducts::moves, point_east, point_north, point_south, point_west, Character::pos(), digging_moves_and_byproducts::result_terrain, digging_moves_and_byproducts::spawn_count, string_id< T >::str(), and item::type.
Referenced by Item_factory::init().
directional_antenna()
int iuse::directional_antenna (player * p, item * it, bool , const tripoint &)
Definition at line 2128 of file iuse.cpp.
{
    // Find out if we have an active radio
    auto radios = p->items_with( []( const item & it ) {
        return it.typeId() == itype_radio_on;
    } );
    // If we don't wield the radio, also check on the ground
    if( radios.empty() ) {
        map_stack items = get_map().i_at( p->pos() );
        for( item &an_item : items ) {
            if( an_item.typeId() == itype_radio_on ) {
                radios.push_back( &an_item );
            }
        }
    }
    if( radios.empty() ) {
        add_msg( m_info, _( "Must have an active radio to check for signal direction." ) );
        return 0;
    }
    const item radio = *radios.front();
    // Find the radio station its tuned to (if any)
    const auto tref = overmap_buffer.find_radio_station( radio.frequency );
    if( !tref ) {
        p->add_msg_if_player( m_info, _( "You can't find the direction if your radio isn't tuned." ) );
        return 0;
    }
    // Report direction.
    // TODO: fix point types
    const tripoint_abs_sm player_pos( p->global_sm_location() );
    direction angle = direction_from( player_pos.xy(), tref.abs_sm_pos );
    add_msg( _( "The signal seems strongest to the %s." ), direction_name( angle ) );
    return it->type->charges_to_use();
}
References _, add_msg(), player::add_msg_if_player(), itype::charges_to_use(), direction_from(), direction_name(), overmapbuffer::find_radio_station(), get_map(), Character::global_sm_location(), map::i_at(), object_names_collection::items, visitable< T >::items_with(), itype_radio_on, m_info, overmap_buffer, Character::pos(), item::type, item::typeId(), and coords::coord_point< Point, Origin, Scale >::xy().
Referenced by Item_factory::init().
directional_hologram()
int iuse::directional_hologram (player * p, item * it, bool , const tripoint & pos)
Definition at line 9179 of file iuse.cpp.
{
    if( it->is_armor() &&  !( p->is_worn( *it ) ) ) {
        p->add_msg_if_player( m_neutral, _( "You need to wear the %1$s before activating it." ),
                              it->tname() );
        return 0;
    }
    const cata::optional<tripoint> posp_ = choose_adjacent( _( "Choose hologram direction." ) );
    if( !posp_ ) {
        return 0;
    }
    const tripoint posp = *posp_;
    monster *const hologram = g->place_critter_at( mon_hologram, posp );
    if( !hologram ) {
        p->add_msg_if_player( m_info, _( "Can't create a hologram there." ) );
        return 0;
    }
    tripoint target = pos;
    target.x = p->posx() + 4 * SEEX * ( posp.x - p->posx() );
    target.y = p->posy() + 4 * SEEY * ( posp.y - p->posy() );
    hologram->friendly = -1;
    hologram->add_effect( effect_docile, 1_hours );
    hologram->wandf = -30;
    hologram->set_summon_time( 60_seconds );
    hologram->set_dest( target );
    p->mod_moves( -to_turns<int>( 1_seconds ) );
    return it->type->charges_to_use();
}
References _, monster::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), choose_adjacent(), effect_docile, monster::friendly, g, item::is_armor(), Character::is_worn(), m_info, m_neutral, Creature::mod_moves(), mon_hologram, Character::posx(), Character::posy(), SEEX, SEEY, monster::set_dest(), monster::set_summon_time(), item::tname(), item::type, monster::wandf, tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
disassemble()
int iuse::disassemble (player * p, item * it, bool , const tripoint &)
Definition at line 9598 of file iuse.cpp.
{
    if( !p->is_avatar() ) {
        debugmsg( "disassemble iuse is not implemented for NPCs." );
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( !p->has_item( *it ) ) {
        return 0;
    }
    crafting::disassemble( *p->as_avatar(), item_location( *p, it ) );
    return 0;
}
References _, player::add_msg_if_player(), Creature::as_avatar(), debugmsg, crafting::disassemble(), visitable< T >::has_item(), Creature::is_avatar(), Character::is_mounted(), and m_info.
Referenced by Item_factory::init().
dive_tank()
int iuse::dive_tank (player * p, item * it, bool t, const tripoint &)
Definition at line 4245 of file iuse.cpp.
{
    if( t ) { // Normal use
        if( p->is_worn( *it ) ) {
            if( p->is_underwater() && p->oxygen < 10 ) {
                p->oxygen += 20;
            }
            if( one_in( 15 ) ) {
                p->add_msg_if_player( m_bad, _( "You take a deep breath from your %s." ), it->tname() );
            }
            if( it->charges == 0 ) {
                p->add_msg_if_player( m_bad, _( "Air in your %s runs out." ), it->tname() );
                it->set_var( "overwrite_env_resist", 0 );
                it->convert( itype_id( it->typeId().str().substr( 0,
                                       it->typeId().str().size() - 3 ) ) ).active = false; // 3 = "_on"
            }
        } else { // not worn = off thanks to on-demand regulator
            it->set_var( "overwrite_env_resist", 0 );
            it->convert( itype_id( it->typeId().str().substr( 0,
                                   it->typeId().str().size() - 3 ) ) ).active = false; // 3 = "_on"
        }
    } else { // Turning it on/off
        if( it->charges == 0 ) {
            p->add_msg_if_player( _( "Your %s is empty." ), it->tname() );
        } else if( it->active ) { //off
            p->add_msg_if_player( _( "You turn off the regulator and close the air valve." ) );
            it->set_var( "overwrite_env_resist", 0 );
            it->convert( itype_id( it->typeId().str().substr( 0,
                                   it->typeId().str().size() - 3 ) ) ).active = false; // 3 = "_on"
        } else { //on
            if( !p->is_worn( *it ) ) {
                p->add_msg_if_player( _( "You should wear it first." ) );
            } else {
                p->add_msg_if_player( _( "You turn on the regulator and open the air valve." ) );
                it->set_var( "overwrite_env_resist", it->get_base_env_resist_w_filter() );
                it->convert( itype_id( it->typeId().str() + "_on" ) ).active = true;
            }
        }
    }
    if( it->charges == 0 ) {
        it->set_var( "overwrite_env_resist", 0 );
        it->convert( itype_id( it->typeId().str().substr( 0,
                               it->typeId().str().size() - 3 ) ) ).active = false; // 3 = "_on"
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::charges, itype::charges_to_use(), item::convert(), item::get_base_env_resist_w_filter(), Creature::is_underwater(), Character::is_worn(), m_bad, one_in(), Character::oxygen, item::set_var(), string_id< T >::str(), item::tname(), item::type, and item::typeId().
Referenced by Item_factory::init().
dog_whistle()
int iuse::dog_whistle (player * p, item * it, bool , const tripoint &)
Definition at line 4562 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    p->add_msg_if_player( _( "You blow your dog whistle." ) );
    for( monster &critter : g->all_monsters() ) {
        if( critter.friendly != 0 && critter.has_flag( MF_DOGFOOD ) ) {
            bool u_see = g->u.sees( critter );
            if( critter.has_effect( effect_docile ) ) {
                if( u_see ) {
                    p->add_msg_if_player( _( "Your %s looks ready to attack." ), critter.name() );
                }
                critter.remove_effect( effect_docile );
            } else {
                if( u_see ) {
                    p->add_msg_if_player( _( "Your %s goes docile." ), critter.name() );
                }
                critter.add_effect( effect_docile, 1_turns, num_bp );
            }
        }
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), effect_docile, g, Creature::is_underwater(), m_info, MF_DOGFOOD, num_bp, and item::type.
Referenced by Item_factory::init().
dogfood()
int iuse::dogfood (player * p, item * it, bool , const tripoint &)
Definition at line 1627 of file iuse.cpp.
{
    return petfood( *p, *it, DOGFOOD );
}
References DOGFOOD, and petfood().
Referenced by Item_factory::init().
e_combatsaw_off()
int iuse::e_combatsaw_off (player * p, item * it, bool , const tripoint &)
Definition at line 3069 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           true,
                           !p->is_underwater(),
                           30, _( "With a snarl, the electric combat chainsaw screams to life!" ),
                           _( "You pull the trigger, but nothing happens." ) );
}
References _, Creature::is_underwater(), and toolweapon_off().
Referenced by Item_factory::init().
e_combatsaw_on()
int iuse::e_combatsaw_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3171 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "electric combat chainsaw" ),
                          false,
                          12, 18, _( "Your electric combat chainsaw growls." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
ecig()
int iuse::ecig (player * p, item * it, bool , const tripoint &)
Definition at line 597 of file iuse.cpp.
{
    if( it->typeId() == itype_ecig ) {
        p->add_msg_if_player( m_neutral, _( "You take a puff from your electronic cigarette." ) );
    } else if( it->typeId() == itype_advanced_ecig ) {
        if( p->has_charges( itype_nicotine_liquid, 1 ) ) {
            p->add_msg_if_player( m_neutral,
                                  _( "You inhale some vapor from your advanced electronic cigarette." ) );
            p->use_charges( itype_nicotine_liquid, 1 );
            item dummy_ecig = item( "ecig", calendar::turn );
            p->consume_effects( dummy_ecig );
        } else {
            p->add_msg_if_player( m_info, _( "You don't have any nicotine liquid!" ) );
            return 0;
        }
    }
    p->mod_thirst( 1 );
    p->mod_stored_kcal( 10 );
    p->add_effect( effect_cig, 10_minutes );
    if( p->get_effect_dur( effect_cig ) > 10_minutes * ( p->addiction_level(
                add_type::CIG ) + 1 ) ) {
        p->add_msg_if_player( m_bad, _( "Ugh, too much nicotine you feel nasty." ) );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), Character::addiction_level(), itype::charges_to_use(), CIG, Character::consume_effects(), effect_cig, Creature::get_effect_dur(), Character::has_charges(), itype_advanced_ecig, itype_ecig, itype_nicotine_liquid, m_bad, m_info, m_neutral, Character::mod_stored_kcal(), Character::mod_thirst(), calendar::turn, item::type, item::typeId(), and Character::use_charges().
Referenced by Item_factory::init().
ecs_lajatang_off()
int iuse::ecs_lajatang_off (player * p, item * it, bool , const tripoint &)
Definition at line 3105 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           false,
                           it->ammo_remaining() > 1 && !p->is_underwater(),
                           40, _( "With a buzz, the chainsaws leap to life!" ),
                           _( "You pull the trigger, but nothing happens." ) );
}
References _, item::ammo_remaining(), Creature::is_underwater(), and toolweapon_off().
Referenced by Item_factory::init().
ecs_lajatang_on()
int iuse::ecs_lajatang_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3202 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "electric chainsaw lajatang" ),
                          false,
                          15, 12, _( "Your chainsaws buzz." ),
                          true );
    // The chainsaw lajatang drains 2 charges per turn, since
    // there are two chainsaws.
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
ehandcuffs()
int iuse::ehandcuffs (player * p, item * it, bool t, const tripoint & pos)
Definition at line 7776 of file iuse.cpp.
{
    if( t ) {
        if( g->m.has_flag( "SWIMMABLE", pos.xy() ) ) {
            it->unset_flag( "NO_UNWIELD" );
            it->ammo_unset();
            it->active = false;
            add_msg( m_good, _( "%s automatically turned off!" ), it->tname() );
            return it->type->charges_to_use();
        }
        if( it->charges == 0 ) {
            sounds::sound( pos, 2, sounds::sound_t::combat, "Click.", true, "tools", "handcuffs" );
            it->unset_flag( "NO_UNWIELD" );
            it->active = false;
            if( p->has_item( *it ) && p->weapon.typeId() == itype_e_handcuffs ) {
                add_msg( m_good, _( "%s on your hands opened!" ), it->tname() );
            }
            return it->type->charges_to_use();
        }
        if( p->has_item( *it ) ) {
            if( p->has_active_bionic( bio_shock ) && p->get_power_level() >= 2_kJ &&
                one_in( 5 ) ) {
                p->mod_power_level( -2_kJ );
                it->unset_flag( "NO_UNWIELD" );
                it->ammo_unset();
                it->active = false;
                add_msg( m_good, _( "The %s crackle with electricity from your bionic, then come off your hands!" ),
                         it->tname() );
                return it->type->charges_to_use();
            }
        }
        if( calendar::once_every( 1_minutes ) ) {
            sounds::sound( pos, 10, sounds::sound_t::alarm, _( "a police siren, whoop WHOOP." ), true,
                           "environment", "police_siren" );
        }
        const point p2( it->get_var( "HANDCUFFS_X", 0 ), it->get_var( "HANDCUFFS_Y", 0 ) );
        if( ( it->ammo_remaining() > it->type->maximum_charges() - 1000 ) && ( p2.x != pos.x ||
                p2.y != pos.y ) ) {
            if( p->has_item( *it ) && p->weapon.typeId() == itype_e_handcuffs ) {
                if( p->is_elec_immune() ) {
                    if( one_in( 10 ) ) {
                        add_msg( m_good, _( "The cuffs try to shock you, but you're protected from electricity." ) );
                    }
                } else {
                    add_msg( m_bad, _( "Ouch, the cuffs shock you!" ) );
                    p->apply_damage( nullptr, bodypart_id( "arm_l" ), rng( 0, 2 ) );
                    p->apply_damage( nullptr, bodypart_id( "arm_r" ), rng( 0, 2 ) );
                    p->mod_pain( rng( 2, 5 ) );
                }
            } else {
                add_msg( m_bad, _( "The %s spark with electricity!" ), it->tname() );
            }
            it->charges -= 50;
            if( it->charges < 1 ) {
                it->charges = 1;
            }
            it->set_var( "HANDCUFFS_X", pos.x );
            it->set_var( "HANDCUFFS_Y", pos.y );
            return it->type->charges_to_use();
        }
        return it->type->charges_to_use();
    }
    if( it->active ) {
        add_msg( _( "The %s are clamped tightly on your wrists.  You can't take them off." ),
                 it->tname() );
    } else {
        add_msg( _( "The %s have discharged and can be taken off." ), it->tname() );
    }
    return it->type->charges_to_use();
}
References _, item::active, add_msg(), sounds::alarm, item::ammo_remaining(), item::ammo_unset(), Character::apply_damage(), bio_shock, item::charges, itype::charges_to_use(), sounds::combat, g, Character::get_power_level(), item::get_var(), Character::has_active_bionic(), visitable< T >::has_item(), Character::is_elec_immune(), itype_e_handcuffs, m_bad, m_good, itype::maximum_charges(), player::mod_pain(), Character::mod_power_level(), calendar::once_every(), one_in(), rng(), item::set_var(), sounds::sound(), item::tname(), item::type, item::typeId(), item::unset_flag(), Character::weapon, point::x, tripoint::x, tripoint::xy(), point::y, and tripoint::y.
Referenced by Item_factory::init().
einktabletpc()
int iuse::einktabletpc (player * p, item * it, bool t, const tripoint & pos)
Computer >2 allows decrypting memory cards more easily Intelligence increases chance of safely decrypting memory card Computer increases chance of safely decrypting memory card
Definition at line 6367 of file iuse.cpp.
{
    if( t ) {
        if( !it->get_var( "EIPC_MUSIC_ON" ).empty() && ( it->ammo_remaining() > 0 ) ) {
            if( calendar::once_every( 5_minutes ) ) {
                it->ammo_consume( 1, p->pos() );
            }
            //the more varied music, the better max mood.
            const int songs = it->get_var( "EIPC_MUSIC", 0 );
            play_music( *p, pos, 8, std::min( 25, songs ) );
        } else {
            it->active = false;
            it->erase_var( "EIPC_MUSIC_ON" );
            p->add_msg_if_player( m_info, _( "Tablet's batteries are dead." ) );
        }
        return 0;
    } else if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    } else if( !p->is_npc() ) {
        enum {
            ei_invalid, ei_photo, ei_music, ei_recipe, ei_uploaded_photos, ei_monsters, ei_download, ei_decrypt
        };
        if( p->is_underwater() ) {
            p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
            return 0;
        }
        if( p->has_trait( trait_ILLITERATE ) ) {
            p->add_msg_if_player( m_info, _( "You cannot read a computer screen." ) );
            return 0;
        }
        if( p->has_trait( trait_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
            !p->has_effect( effect_contacts ) && !p->has_bionic( bio_eye_optic ) ) {
            p->add_msg_if_player( m_info,
                                  _( "You'll need to put on reading glasses before you can see the screen." ) );
            return 0;
        }
        uilist amenu;
        amenu.text = _( "Choose menu option:" );
        const int photos = it->get_var( "EIPC_PHOTOS", 0 );
        if( photos > 0 ) {
            amenu.addentry( ei_photo, true, 'p', _( "Unsorted photos [%d]" ), photos );
        } else {
            amenu.addentry( ei_photo, false, 'p', _( "No photos on device" ) );
        }
        const int songs = it->get_var( "EIPC_MUSIC", 0 );
        if( songs > 0 ) {
            if( it->active ) {
                amenu.addentry( ei_music, true, 'm', _( "Turn music off" ) );
            } else {
                amenu.addentry( ei_music, true, 'm', _( "Turn music on [%d]" ), songs );
            }
        } else {
            amenu.addentry( ei_music, false, 'm', _( "No music on device" ) );
        }
        if( !it->get_var( "EIPC_RECIPES" ).empty() ) {
            amenu.addentry( ei_recipe, true, 'r', _( "View recipes on E-ink screen" ) );
        }
        if( !it->get_var( "EIPC_EXTENDED_PHOTOS" ).empty() ) {
            amenu.addentry( ei_uploaded_photos, true, 'l', _( "Your photos" ) );
        }
        if( !it->get_var( "EINK_MONSTER_PHOTOS" ).empty() ) {
            amenu.addentry( ei_monsters, true, 'y', _( "Your collection of monsters" ) );
        } else {
            amenu.addentry( ei_monsters, false, 'y', _( "Collection of monsters is empty" ) );
        }
        amenu.addentry( ei_download, true, 'w', _( "Download data from memory card" ) );
        /** @EFFECT_COMPUTER >2 allows decrypting memory cards more easily */
        if( p->get_skill_level( skill_computer ) > 2 ) {
            amenu.addentry( ei_decrypt, true, 'd', _( "Decrypt memory card" ) );
        } else {
            amenu.addentry( ei_decrypt, false, 'd', _( "Decrypt memory card (low skill)" ) );
        }
        amenu.query();
        const int choice = amenu.ret;
        if( ei_photo == choice ) {
            const int photos = it->get_var( "EIPC_PHOTOS", 0 );
            const int viewed = std::min( photos, static_cast<int>( rng( 10, 30 ) ) );
            const int count = photos - viewed;
            if( count == 0 ) {
                it->erase_var( "EIPC_PHOTOS" );
            } else {
                it->set_var( "EIPC_PHOTOS", count );
            }
            p->moves -= to_moves<int>( rng( 3_seconds, 7_seconds ) );
            if( p->has_trait( trait_PSYCHOPATH ) ) {
                p->add_msg_if_player( m_info, _( "Wasted time, these pictures do not provoke your senses." ) );
            } else {
                p->add_morale( MORALE_PHOTOS, rng( 15, 30 ), 100 );
                const int random_photo = rng( 1, 20 );
                switch( random_photo ) {
                    case 1:
                        p->add_msg_if_player( m_good, _( "You used to have a dog like this" ) );
                        break;
                    case 2:
                        p->add_msg_if_player( m_good, _( "Ha-ha!  An amusing cat photo." ) );
                        break;
                    case 3:
                        p->add_msg_if_player( m_good, _( "Excellent pictures of nature." ) );
                        break;
                    case 4:
                        p->add_msg_if_player( m_good, _( "Food photos your stomach rumbles!" ) );
                        break;
                    case 5:
                        p->add_msg_if_player( m_good, _( "Some very interesting travel photos." ) );
                        break;
                    case 6:
                        p->add_msg_if_player( m_good, _( "Pictures of a concert of popular band." ) );
                        break;
                    case 7:
                        p->add_msg_if_player( m_good, _( "Photos of someone's luxurious house." ) );
                        break;
                    default:
                        p->add_msg_if_player( m_good, _( "You feel nostalgic as you stare at the photo." ) );
                        break;
                }
            }
            return it->type->charges_to_use();
        }
        if( ei_music == choice ) {
            p->moves -= 30;
            if( it->active ) {
                it->active = false;
                it->erase_var( "EIPC_MUSIC_ON" );
                p->add_msg_if_player( m_info, _( "You turned off music on your %s." ), it->tname() );
            } else {
                it->active = true;
                it->set_var( "EIPC_MUSIC_ON", "1" );
                p->add_msg_if_player( m_info, _( "You turned on music on your %s." ), it->tname() );
            }
            return it->type->charges_to_use();
        }
        if( ei_recipe == choice ) {
            p->moves -= 50;
            uilist rmenu;
            rmenu.text = _( "List recipes:" );
            std::vector<recipe_id> candidate_recipes;
            std::istringstream f( it->get_var( "EIPC_RECIPES" ) );
            std::string s;
            int k = 0;
            while( getline( f, s, ',' ) ) {
                if( s.empty() ) {
                    continue;
                }
                candidate_recipes.emplace_back( s );
                const auto &recipe = *candidate_recipes.back();
                if( recipe ) {
                    rmenu.addentry( k++, true, -1, recipe.result_name() );
                }
            }
            rmenu.query();
            return it->type->charges_to_use();
        }
        if( ei_uploaded_photos == choice ) {
            show_photo_selection( *p, *it, "EIPC_EXTENDED_PHOTOS" );
            return it->type->charges_to_use();
        }
        if( ei_monsters == choice ) {
            uilist pmenu;
            pmenu.text = _( "Your collection of monsters:" );
            std::vector<mtype_id> monster_photos;
            std::istringstream f( it->get_var( "EINK_MONSTER_PHOTOS" ) );
            std::string s;
            int k = 0;
            while( getline( f, s, ',' ) ) {
                if( s.empty() ) {
                    continue;
                }
                monster_photos.push_back( mtype_id( s ) );
                std::string menu_str;
                const monster dummy( monster_photos.back() );
                menu_str = dummy.name();
                getline( f, s, ',' );
                char *chq = &s[0];
                const int quality = atoi( chq );
                menu_str += " [" + photo_quality_name( quality ) + "]";
                pmenu.addentry( k++, true, -1, menu_str.c_str() );
            }
            int choice;
            do {
                pmenu.query();
                choice = pmenu.ret;
                if( choice < 0 ) {
                    break;
                }
                const monster dummy( monster_photos[choice] );
                popup( dummy.type->get_description() );
            } while( true );
            return it->type->charges_to_use();
        }
        avatar *you = p->as_avatar();
        item_location loc;
        auto filter = []( const item & it ) {
            return it.has_flag( "MC_MOBILE" );
        };
        const std::string title = _( "Insert memory card" );
        if( ei_download == choice ) {
            p->moves -= to_moves<int>( 2_seconds );
            if( you != nullptr ) {
                loc = game_menus::inv::titled_filter_menu( filter, *you, title );
            }
            if( !loc ) {
                p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
                return it->type->charges_to_use();
            }
            item &mc = *loc;
            if( !mc.has_flag( "MC_MOBILE" ) ) {
                p->add_msg_if_player( m_info, _( "This is not a compatible memory card." ) );
                return it->type->charges_to_use();
            }
            init_memory_card_with_random_stuff( mc );
            if( mc.has_flag( "MC_ENCRYPTED" ) ) {
                p->add_msg_if_player( m_info, _( "This memory card is encrypted." ) );
                return it->type->charges_to_use();
            }
            if( !mc.has_flag( "MC_HAS_DATA" ) ) {
                p->add_msg_if_player( m_info, _( "This memory card does not contain any new data." ) );
                return it->type->charges_to_use();
            }
            einkpc_download_memory_card( *p, *it, mc );
            return it->type->charges_to_use();
        }
        if( ei_decrypt == choice ) {
            p->moves -= to_moves<int>( 2_seconds );
            if( you != nullptr ) {
                loc = game_menus::inv::titled_filter_menu( filter, *you, title );
            }
            if( !loc ) {
                p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
                return it->type->charges_to_use();
            }
            item &mc = *loc;
            if( !mc.has_flag( "MC_MOBILE" ) ) {
                p->add_msg_if_player( m_info, _( "This is not a compatible memory card." ) );
                return it->type->charges_to_use();
            }
            init_memory_card_with_random_stuff( mc );
            if( !mc.has_flag( "MC_ENCRYPTED" ) ) {
                p->add_msg_if_player( m_info, _( "This memory card is not encrypted." ) );
                return it->type->charges_to_use();
            }
            p->practice( skill_computer, rng( 2, 5 ) );
            /** @EFFECT_INT increases chance of safely decrypting memory card */
            /** @EFFECT_COMPUTER increases chance of safely decrypting memory card */
            const int success = p->get_skill_level( skill_computer ) * rng( 1,
                                p->get_skill_level( skill_computer ) ) *
                                rng( 1, p->int_cur ) - rng( 30, 80 );
            if( success > 0 ) {
                p->practice( skill_computer, rng( 5, 10 ) );
                p->add_msg_if_player( m_good, _( "You successfully decrypted content on %s!" ),
                                      mc.tname() );
                einkpc_download_memory_card( *p, *it, mc );
            } else {
                if( success > -10 || one_in( 5 ) ) {
                    p->add_msg_if_player( m_neutral, _( "You failed to decrypt the %s." ), mc.tname() );
                } else {
                    p->add_msg_if_player( m_bad,
                                          _( "You tripped the firmware protection, and the card deleted its data!" ) );
                    mc.clear_vars();
                    mc.unset_flags();
                    mc.convert( itype_mobile_memory_card_used );
                }
            }
            return it->type->charges_to_use();
        }
    }
    return 0;
}
References _, item::active, Character::add_morale(), player::add_msg_if_player(), uilist::addentry(), item::ammo_consume(), item::ammo_remaining(), Creature::as_avatar(), bio_eye_optic, itype::charges_to_use(), item::clear_vars(), item::convert(), detail::count(), effect_contacts, einkpc_download_memory_card(), item::erase_var(), flag_FIX_FARSIGHT(), mtype::get_description(), Character::get_skill_level(), item::get_var(), Character::has_bionic(), Creature::has_effect(), item::has_flag(), Character::has_trait(), init_memory_card_with_random_stuff(), Character::int_cur, Character::is_mounted(), player::is_npc(), Creature::is_underwater(), itype_mobile_memory_card_used, m_bad, m_good, m_info, m_neutral, MORALE_PHOTOS, Creature::moves, monster::name(), calendar::once_every(), one_in(), photo_quality_name(), play_music(), popup(), Character::pos(), player::practice(), uilist::query(), recipe::result_name(), uilist::ret, rng(), item::set_var(), show_photo_selection(), skill_computer, behavior::success, uilist::text, PATH_INFO::title(), game_menus::inv::titled_filter_menu(), item::tname(), trait_HYPEROPIC, trait_ILLITERATE, trait_PSYCHOPATH, item::type, monster::type, item::unset_flags(), and Character::worn_with_flag().
Referenced by Item_factory::init().
elec_chainsaw_off()
int iuse::elec_chainsaw_off (player * p, item * it, bool , const tripoint &)
Definition at line 3087 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           false,
                           !p->is_underwater(),
                           20, _( "With a roar, the electric chainsaw leaps to life!" ),
                           _( "You pull the trigger, but nothing happens." ) );
}
References _, Creature::is_underwater(), and toolweapon_off().
Referenced by Item_factory::init().
elec_chainsaw_on()
int iuse::elec_chainsaw_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3185 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "electric chainsaw" ),
                          false,
                          15, 12, _( "Your electric chainsaw rumbles." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
extinguisher()
int iuse::extinguisher (player * p, item * it, bool , const tripoint &)
Definition at line 1924 of file iuse.cpp.
{
    if( !it->ammo_sufficient() ) {
        return 0;
    }
    // If anyone other than the player wants to use one of these,
    // they're going to need to figure out how to aim it.
    const cata::optional<tripoint> dest_ = choose_adjacent( _( "Spray where?" ) );
    if( !dest_ ) {
        return 0;
    }
    tripoint dest = *dest_;
    p->moves -= to_moves<int>( 2_seconds );
    // Reduce the strength of fire (if any) in the target tile.
    g->m.mod_field_intensity( dest, fd_fire, 0 - rng( 2, 3 ) );
    // Also spray monsters in that tile.
    if( monster *const mon_ptr = g->critter_at<monster>( dest, true ) ) {
        monster &critter = *mon_ptr;
        critter.moves -= to_moves<int>( 2_seconds );
        bool blind = false;
        if( one_in( 2 ) && critter.has_flag( MF_SEES ) ) {
            blind = true;
            critter.add_effect( effect_blind, rng( 1_minutes, 2_minutes ) );
        }
        if( g->u.sees( critter ) ) {
            p->add_msg_if_player( _( "The %s is sprayed!" ), critter.name() );
            if( blind ) {
                p->add_msg_if_player( _( "The %s looks blinded." ), critter.name() );
            }
        }
        if( critter.made_of( LIQUID ) ) {
            if( g->u.sees( critter ) ) {
                p->add_msg_if_player( _( "The %s is frozen!" ), critter.name() );
            }
            critter.apply_damage( p, bodypart_id( "torso" ), rng( 20, 60 ) );
            critter.set_speed_base( critter.get_speed_base() / 2 );
        }
    }
    // Slightly reduce the strength of fire immediately behind the target tile.
    if( g->m.passable( dest ) ) {
        dest.x += ( dest.x - p->posx() );
        dest.y += ( dest.y - p->posy() );
        g->m.mod_field_intensity( dest, fd_fire, std::min( 0 - rng( 0, 1 ) + rng( 0, 1 ), 0 ) );
    }
    return it->type->charges_to_use();
}
References _, monster::add_effect(), player::add_msg_if_player(), item::ammo_sufficient(), monster::apply_damage(), itype::charges_to_use(), choose_adjacent(), effect_blind, fd_fire, g, Creature::get_speed_base(), monster::has_flag(), LIQUID, monster::made_of(), MF_SEES, Creature::moves, monster::name(), one_in(), Character::posx(), Character::posy(), rng(), Creature::set_speed_base(), item::type, tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
eyedrops()
int iuse::eyedrops (player * p, item * it, bool , const tripoint &)
Definition at line 637 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( it->charges < it->type->charges_to_use() ) {
        p->add_msg_if_player( _( "You're out of %s." ), it->tname() );
        return 0;
    }
    p->add_msg_if_player( _( "You use your %s." ), it->tname() );
    p->moves -= to_moves<int>( 10_seconds );
    if( p->has_effect( effect_boomered ) ) {
        p->remove_effect( effect_boomered );
        p->add_msg_if_player( m_good, _( "You wash the slime from your eyes." ) );
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), item::charges, itype::charges_to_use(), effect_boomered, Creature::has_effect(), Creature::is_underwater(), m_good, m_info, Creature::moves, Creature::remove_effect(), item::tname(), and item::type.
Referenced by Item_factory::init().
feedbird()
int iuse::feedbird (player * p, item * it, bool , const tripoint &)
Definition at line 1642 of file iuse.cpp.
{
    return petfood( *p, *it, BIRDFOOD );
}
References BIRDFOOD, and petfood().
Referenced by Item_factory::init().
feedcattle()
int iuse::feedcattle (player * p, item * it, bool , const tripoint &)
Definition at line 1637 of file iuse.cpp.
{
    return petfood( *p, *it, CATTLEFODDER );
}
References CATTLEFODDER, and petfood().
Referenced by Item_factory::init().
fill_pit()
int iuse::fill_pit (player * p, item * it, bool t, const tripoint &)
Definition at line 2868 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::set<ter_id> allowed_ter_id {
        t_pit,
        t_pit_spiked,
        t_pit_glass,
        t_pit_corpsed,
        t_pit_shallow,
        t_dirtmound
    };
    const std::function<bool( const tripoint & )> f = [&allowed_ter_id]( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        const ter_id type = g->m.ter( pnt );
        return ( allowed_ter_id.find( type ) != allowed_ter_id.end() );
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Fill which pit or mound?" ), _( "There is no pit or mound to fill nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id ter = g->m.ter( pnt );
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info, _( "You decide not to bury yourself that early." ) );
        } else {
            p->add_msg_if_player( m_info, _( "There is nothing to fill." ) );
        }
        return 0;
    }
    int moves;
    if( ter == t_pit || ter == t_pit_spiked ||
        ter == t_pit_glass || ter == t_pit_corpsed ) {
        moves = to_moves<int>( time_duration::from_minutes( 15 ) );
    } else if( ter == t_pit_shallow ) {
        moves = to_moves<int>( time_duration::from_minutes( 10 ) );
    } else if( ter == t_dirtmound ) {
        moves = to_moves<int>( time_duration::from_minutes( 5 ) );
    } else {
        return 0;
    }
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves = moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( ACT_FILL_PIT, moves, -1, p->get_item_position( it ) );
    p->activity.placement = pnt;
    return it->type->charges_to_use();
}
References _, ACT_FILL_PIT, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), time_duration::from_minutes(), g, Character::get_item_position(), Character::is_mounted(), m_info, player_activity::placement, Character::pos(), t_dirtmound, t_pit, t_pit_corpsed, t_pit_glass, t_pit_shallow, t_pit_spiked, type, and item::type.
Referenced by Item_factory::init().
firecracker()
int iuse::firecracker (player * p, item * it, bool , const tripoint &)
Definition at line 3865 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( !p->use_charges_if_avail( itype_fire, 1 ) ) {
        p->add_msg_if_player( m_info, _( "You need a source of fire!" ) );
        return 0;
    }
    p->add_msg_if_player( _( "You light the firecracker." ) );
    it->convert( itype_firecracker_act );
    it->charges = 2;
    it->active = true;
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::charges, itype::charges_to_use(), item::convert(), Creature::is_underwater(), itype_fire, itype_firecracker_act, m_info, item::type, and Character::use_charges_if_avail().
Referenced by Item_factory::init().
firecracker_act()
int iuse::firecracker_act (player * p, item * it, bool t, const tripoint & pos)
Definition at line 3882 of file iuse.cpp.
{
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    }
    if( t ) { // Simple timer effects
        sounds::sound( pos, 0,  sounds::sound_t::alarm, _( "ssss" ), true, "misc", "lit_fuse" );
    } else if( it->charges > 0 ) {
        p->add_msg_if_player( m_info, _( "You've already lit the %s, try throwing it instead." ),
                              it->tname() );
        return 0;
    } else { // When that timer runs down...
        sounds::sound( pos, 20, sounds::sound_t::combat, _( "Bang!" ), true, "explosion", "small" );
    }
    return 0;
}
References _, player::add_msg_if_player(), sounds::alarm, item::charges, sounds::combat, m_info, sounds::sound(), item::tname(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
firecracker_pack()
int iuse::firecracker_pack (player * p, item * it, bool , const tripoint &)
Definition at line 3824 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( !p->has_charges( itype_fire, 1 ) ) {
        p->add_msg_if_player( m_info, _( "You need a source of fire!" ) );
        return 0;
    }
    p->add_msg_if_player( _( "You light the pack of firecrackers." ) );
    it->convert( itype_firecracker_pack_act );
    it->charges = 26;
    it->set_age( 0_turns );
    it->active = true;
    return 0; // don't use any charges at all. it has became a new item
}
References _, item::active, player::add_msg_if_player(), item::charges, item::convert(), Character::has_charges(), Creature::is_underwater(), itype_fire, itype_firecracker_pack_act, m_info, and item::set_age().
Referenced by Item_factory::init().
firecracker_pack_act()
int iuse::firecracker_pack_act (player * , item * it, bool , const tripoint & pos)
Definition at line 3842 of file iuse.cpp.
{
    time_duration timer = it->age();
    if( timer < 2_turns ) {
        sounds::sound( pos, 0, sounds::sound_t::alarm, _( "ssss" ), true, "misc", "lit_fuse" );
        it->inc_damage();
    } else if( it->charges > 0 ) {
        int ex = rng( 4, 6 );
        int i = 0;
        if( ex > it->charges ) {
            ex = it->charges;
        }
        for( i = 0; i < ex; i++ ) {
            sounds::sound( pos, 20, sounds::sound_t::combat, _( "Bang!" ), false, "explosion", "small" );
        }
        it->charges -= ex;
    }
    if( it->charges == 0 ) {
        it->charges = -1;
    }
    return 0;
}
References _, item::age(), sounds::alarm, item::charges, sounds::combat, item::inc_damage(), rng(), and sounds::sound().
Referenced by Item_factory::init().
fish_trap()
int iuse::fish_trap (player * p, item * it, bool t, const tripoint & pos)
Survival randomly increases number of fish caught in fishing trap
Definition at line 1790 of file iuse.cpp.
{
    if( !t ) {
        // Handle deploying fish trap.
        if( it->active ) {
            it->active = false;
            return 0;
        }
        if( it->charges < 0 ) {
            it->charges = 0;
            return 0;
        }
        if( p->is_mounted() ) {
            p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
            return 0;
        }
        if( p->is_underwater() ) {
            p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
            return 0;
        }
        if( it->charges == 0 ) {
            p->add_msg_if_player( _( "Fish are not foolish enough to go in here without bait." ) );
            return 0;
        }
        const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Put fish trap where?" ) );
        if( !pnt_ ) {
            return 0;
        }
        const tripoint pnt = *pnt_;
        if( !g->m.has_flag( "FISHABLE", pnt ) ) {
            p->add_msg_if_player( m_info, _( "You can't fish there!" ) );
            return 0;
        }
        if( !good_fishing_spot( pnt ) ) {
            return 0;
        }
        it->active = true;
        it->set_age( 0_turns );
        g->m.add_item_or_charges( pnt, *it );
        p->i_rem( it );
        p->add_msg_if_player( m_info,
                              _( "You place the fish trap, in three hours or so you may catch some fish." ) );
        return 0;
    } else {
        // Handle processing fish trap over time.
        if( it->charges == 0 ) {
            it->active = false;
            return 0;
        }
        if( it->age() > 3_hours ) {
            it->active = false;
            if( !g->m.has_flag( "FISHABLE", pos ) ) {
                return 0;
            }
            int success = -50;
            const int surv = p->get_skill_level( skill_survival );
            const int attempts = rng( it->charges, it->charges * it->charges );
            for( int i = 0; i < attempts; i++ ) {
                /** @EFFECT_SURVIVAL randomly increases number of fish caught in fishing trap */
                success += rng( surv, surv * surv );
            }
            it->charges = rng( -1, it->charges );
            if( it->charges < 0 ) {
                it->charges = 0;
            }
            int fishes = 0;
            if( success < 0 ) {
                fishes = 0;
            } else if( success < 300 ) {
                fishes = 1;
            } else if( success < 1500 ) {
                fishes = 2;
            } else {
                fishes = rng( 3, 5 );
            }
            if( fishes == 0 ) {
                it->charges = 0;
                p->practice( skill_survival, rng( 5, 15 ) );
                return 0;
            }
            //get the fishables around the trap's spot
            std::unordered_set<tripoint> fishable_locations = g->get_fishable_locations( 60, pos );
            std::vector<monster *> fishables = g->get_fishable_monsters( fishable_locations );
            for( int i = 0; i < fishes; i++ ) {
                p->practice( skill_survival, rng( 3, 10 ) );
                if( !fishables.empty() ) {
                    monster *chosen_fish = random_entry( fishables );
                    // reduce the abstract fish_population marker of that fish
                    chosen_fish->fish_population -= 1;
                    if( chosen_fish->fish_population <= 0 ) {
                        g->catch_a_monster( chosen_fish, pos, p, 300_hours ); //catch the fish!
                    } else {
                        g->m.add_item_or_charges( pos, item::make_corpse( chosen_fish->type->id,
                                                  calendar::turn + rng( 0_turns,
                                                          3_hours ) ) );
                    }
                } else {
                    //there will always be a chance that the player will get lucky and catch a fish
                    //not existing in the fishables vector. (maybe it was in range, but wandered off)
                    //lets say it is a 5% chance per fish to catch
                    if( one_in( 20 ) ) {
                        const std::vector<mtype_id> fish_group = MonsterGroupManager::GetMonstersFromGroup(
                                    GROUP_FISH );
                        const mtype_id &fish_mon = random_entry_ref( fish_group );
                        //Yes, we can put fishes in the trap like knives in the boot,
                        //and then get fishes via activation of the item,
                        //but it's not as comfortable as if you just put fishes in the same tile with the trap.
                        //Also: corpses and comestibles do not rot in containers like this, but on the ground they will rot.
                        //we don't know when it was caught so use a random turn
                        g->m.add_item_or_charges( pos, item::make_corpse( fish_mon, it->birthday() + rng( 0_turns,
                                                  3_hours ) ) );
                        break; //this can happen only once
                    }
                }
            }
        }
        return 0;
    }
}
References _, item::active, player::add_msg_if_player(), item::age(), item::birthday(), item::charges, choose_adjacent(), monster::fish_population, g, Character::get_skill_level(), MonsterGroupManager::GetMonstersFromGroup(), good_fishing_spot(), GROUP_FISH, Character::i_rem(), mtype::id, Character::is_mounted(), Creature::is_underwater(), m_info, item::make_corpse(), one_in(), player::practice(), random_entry(), random_entry_ref(), rng(), item::set_age(), skill_survival, behavior::success, calendar::turn, and monster::type.
Referenced by Item_factory::init().
fishing_rod()
int iuse::fishing_rod (player * p, item * it, bool , const tripoint &)
Definition at line 1762 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Long actions - NPCs don't like those yet.
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    cata::optional<tripoint> found;
    for( const tripoint &pnt : g->m.points_in_radius( p->pos(), 1 ) ) {
        if( g->m.has_flag( flag_FISHABLE, pnt ) && good_fishing_spot( pnt ) ) {
            found = pnt;
            break;
        }
    }
    if( !found ) {
        p->add_msg_if_player( m_info, _( "You can't fish there!" ) );
        return 0;
    }
    p->add_msg_if_player( _( "You cast your line and wait to hook something" ) );
    p->assign_activity( ACT_FISH, to_moves<int>( 5_hours ), 0, 0, it->tname() );
    p->activity.targets.push_back( item_location( *p, it ) );
    p->activity.coord_set = g->get_fishable_locations( 60, *found );
    return 0;
}
References _, ACT_FISH, Character::activity, player::add_msg_if_player(), Character::assign_activity(), player_activity::coord_set, flag_FISHABLE(), g, good_fishing_spot(), Character::is_mounted(), player::is_npc(), m_info, Character::pos(), player_activity::targets, and item::tname().
Referenced by Item_factory::init().
fitness_check()
int iuse::fitness_check (player * p, item * it, bool , const tripoint &)
flumed()
int iuse::flumed (player * p, item * it, bool , const tripoint &)
Definition at line 972 of file iuse.cpp.
{
    p->add_effect( effect_took_flumed, 10_hours );
    p->add_msg_if_player( _( "You take some %s" ), it->tname() );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_took_flumed, item::tname(), and item::type.
Referenced by Item_factory::init().
flusleep()
int iuse::flusleep (player * p, item * it, bool , const tripoint &)
Definition at line 979 of file iuse.cpp.
{
    p->add_effect( effect_took_flumed, 12_hours );
    p->mod_fatigue( 30 );
    p->add_msg_if_player( _( "You take some %s" ), it->tname() );
    p->add_msg_if_player( m_warning, _( "You feel very sleepy" ) );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_took_flumed, m_warning, Character::mod_fatigue(), item::tname(), and item::type.
Referenced by Item_factory::init().
foodperson()
int iuse::foodperson (player * p, item * it, bool t, const tripoint & pos)
Definition at line 7872 of file iuse.cpp.
{
    if( t ) {
        if( calendar::once_every( 1_minutes ) ) {
            const SpeechBubble &speech = get_speech( "foodperson_mask" );
            sounds::sound( pos, speech.volume, sounds::sound_t::alarm, speech.text.translated(), true, "speech",
                           "foodperson_mask" );
        }
        return it->type->charges_to_use();
    }
    time_duration shift = time_duration::from_turns( it->magazine_current()->ammo_remaining() *
                          it->type->tool->turns_per_charge );
    p->add_msg_if_player( m_info, _( "Your HUD lights-up: \"Your shift ends in %s\"." ),
                          to_string( shift ) );
    return 0;
}
References _, player::add_msg_if_player(), sounds::alarm, item::ammo_remaining(), itype::charges_to_use(), time_duration::from_turns(), get_speech(), m_info, item::magazine_current(), calendar::once_every(), sounds::sound(), speech, to_string(), itype::tool, and item::type.
Referenced by Item_factory::init().
fungicide()
int iuse::fungicide (player * p, item * it, bool , const tripoint &)
Definition at line 656 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    const bool has_fungus = p->has_effect( effect_fungus );
    const bool has_spores = p->has_effect( effect_spores );
    if( p->is_npc() && !has_fungus && !has_spores ) {
        return 0;
    }
    p->add_msg_player_or_npc( _( "You use your fungicide." ), _( "<npcname> uses some fungicide" ) );
    if( has_fungus && ( one_in( 3 ) ) ) {
        p->remove_effect( effect_fungus );
        p->add_msg_if_player( m_warning,
                              _( "You feel a burning sensation under your skin that quickly fades away." ) );
    }
    if( has_spores && ( one_in( 2 ) ) ) {
        if( !p->has_effect( effect_fungus ) ) {
            p->add_msg_if_player( m_warning, _( "Your skin grows warm for a moment." ) );
        }
        p->remove_effect( effect_spores );
        int spore_count = rng( 1, 6 );
        for( const tripoint &dest : g->m.points_in_radius( p->pos(), 1 ) ) {
            if( spore_count == 0 ) {
                break;
            }
            if( dest == p->pos() ) {
                continue;
            }
            if( g->m.passable( dest ) && !get_map().obstructed_by_vehicle_rotation( p->pos(), dest ) &&
                x_in_y( spore_count, 8 ) ) {
                if( monster *const mon_ptr = g->critter_at<monster>( dest ) ) {
                    monster &critter = *mon_ptr;
                    if( g->u.sees( dest ) &&
                        !critter.type->in_species( FUNGUS ) ) {
                        add_msg( m_warning, _( "The %s is covered in tiny spores!" ),
                                 critter.name() );
                    }
                    if( !critter.make_fungus() ) {
                        critter.die( p ); // counts as kill by player
                    }
                } else {
                    g->place_critter_at( mon_spore, dest );
                }
                spore_count--;
            }
        }
    }
    return it->type->charges_to_use();
}
References _, add_msg(), player::add_msg_if_player(), player::add_msg_player_or_npc(), itype::charges_to_use(), monster::die(), effect_fungus, effect_spores, FUNGUS, g, get_map(), Creature::has_effect(), mtype::in_species(), player::is_npc(), Creature::is_underwater(), m_info, m_warning, monster::make_fungus(), mon_spore, monster::name(), one_in(), Character::pos(), Creature::remove_effect(), rng(), item::type, monster::type, and x_in_y().
Referenced by Item_factory::init().
gasmask()
int iuse::gasmask (player * p, item * it, bool t, const tripoint & pos)
Definition at line 4336 of file iuse.cpp.
{
    if( t ) { // Normal use
        if( p->is_worn( *it ) ) {
            // calculate amount of absorbed gas per filter charge
            const field &gasfield = g->m.field_at( pos );
            for( auto &dfield : gasfield ) {
                const field_entry &entry = dfield.second;
                if( entry.get_gas_absorption_factor() > 0 ) {
                    it->set_var( "gas_absorbed", it->get_var( "gas_absorbed", 0 ) + entry.get_gas_absorption_factor() );
                }
            }
            if( it->get_var( "gas_absorbed", 0 ) >= 100 ) {
                it->ammo_consume( 1, p->pos() );
                it->set_var( "gas_absorbed", 0 );
            }
            if( it->charges == 0 ) {
                p->add_msg_player_or_npc(
                    m_bad,
                    _( "Your %s requires new filter!" ),
                    _( "<npcname> needs new gas mask filter!" )
                    , it->tname() );
            }
        }
    } else { // activate
        if( it->charges == 0 ) {
            p->add_msg_if_player( _( "Your %s don't have a filter." ), it->tname() );
        } else {
            p->add_msg_if_player( _( "You prepared your %s." ), it->tname() );
            it->active = true;
            it->set_var( "overwrite_env_resist", it->get_base_env_resist_w_filter() );
        }
    }
    if( it->charges == 0 ) {
        it->set_var( "overwrite_env_resist", 0 );
        it->active = false;
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), player::add_msg_player_or_npc(), item::ammo_consume(), item::charges, itype::charges_to_use(), g, item::get_base_env_resist_w_filter(), field_entry::get_gas_absorption_factor(), item::get_var(), Character::is_worn(), m_bad, Character::pos(), item::set_var(), item::tname(), and item::type.
Referenced by Item_factory::init().
geiger()
int iuse::geiger (player * p, item * it, bool t, const tripoint & pos)
Definition at line 3388 of file iuse.cpp.
{
    if( t ) { // Every-turn use when it's on
        const int rads = g->m.get_radiation( pos );
        if( rads == 0 ) {
            return it->type->charges_to_use();
        }
        std::string description = rads > 50 ? _( "buzzing" ) :
                                  rads > 25 ? _( "rapid clicking" ) : _( "clicking" );
        std::string sound_var = rads > 50 ? _( "geiger_high" ) :
                                rads > 25 ? _( "geiger_medium" ) : _( "geiger_low" );
        sounds::sound( pos, 6, sounds::sound_t::alarm, description, true, "tool", sound_var );
        if( !p->can_hear( pos, 6 ) ) {
            // can not hear it, but may have alarmed other creatures
            return it->type->charges_to_use();
        }
        if( rads > 50 ) {
            add_msg( m_warning, _( "The geiger counter buzzes intensely." ) );
        } else if( rads > 35 ) {
            add_msg( m_warning, _( "The geiger counter clicks wildly." ) );
        } else if( rads > 25 ) {
            add_msg( m_warning, _( "The geiger counter clicks rapidly." ) );
        } else if( rads > 15 ) {
            add_msg( m_warning, _( "The geiger counter clicks steadily." ) );
        } else if( rads > 8 ) {
            add_msg( m_warning, _( "The geiger counter clicks slowly." ) );
        } else if( rads > 4 ) {
            add_msg( _( "The geiger counter clicks intermittently." ) );
        } else {
            add_msg( _( "The geiger counter clicks once." ) );
        }
        return it->type->charges_to_use();
    }
    // Otherwise, we're activating the geiger counter
    if( it->typeId() == itype_geiger_on ) {
        add_msg( _( "The geiger counter's SCANNING LED turns off." ) );
        it->convert( itype_geiger_off ).active = false;
        return 0;
    }
    int ch = uilist( _( "Geiger counter:" ), {
        _( "Scan yourself or other person" ), _( "Scan the ground" ), _( "Turn continuous scan on" )
    } );
    switch( ch ) {
        case 0: {
            const std::function<bool( const tripoint & )> f = [&]( const tripoint & pnt ) {
                return g->critter_at<npc>( pnt ) != nullptr || g->critter_at<player>( pnt ) != nullptr;
            };
            const cata::optional<tripoint> pnt_ = choose_adjacent_highlight( _( "Scan whom?" ),
                                                  _( "There is no one to scan nearby." ), f, false );
            if( !pnt_ ) {
                return 0;
            }
            const tripoint &pnt = *pnt_;
            if( pnt == g->u.pos() ) {
                p->add_msg_if_player( m_info, _( "Your radiation level: %d mSv (%d mSv from items)" ), p->get_rad(),
                                      p->leak_level( "RADIOACTIVE" ) );
                break;
            }
            if( npc *const person_ = g->critter_at<npc>( pnt ) ) {
                npc &person = *person_;
                p->add_msg_if_player( m_info, _( "%s's radiation level: %d mSv (%d mSv from items)" ),
                                      person.name, person.get_rad(),
                                      person.leak_level( "RADIOACTIVE" ) );
            }
            break;
        }
        case 1:
            p->add_msg_if_player( m_info, _( "The ground's radiation level: %d mSv/h" ),
                                  g->m.get_radiation( p->pos() ) );
            break;
        case 2:
            p->add_msg_if_player( _( "The geiger counter's scan LED turns on." ) );
            it->convert( itype_geiger_on ).active = true;
            break;
        default:
            return 0;
    }
    p->mod_moves( -100 );
    return it->type->charges_to_use();
}
References _, item::active, add_msg(), player::add_msg_if_player(), sounds::alarm, Character::can_hear(), itype::charges_to_use(), choose_adjacent_highlight(), item::convert(), g, Character::get_rad(), itype_geiger_off, itype_geiger_on, Character::leak_level(), m_info, m_warning, Creature::mod_moves(), Character::name, Character::pos(), sounds::sound(), item::type, and item::typeId().
Referenced by Item_factory::init().
granade()
int iuse::granade (player * p, item * it, bool , const tripoint &)
Definition at line 3566 of file iuse.cpp.
{
    p->add_msg_if_player( _( "You pull the pin on the Granade." ) );
    it->convert( itype_granade_act );
    it->charges = 5;
    it->active = true;
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::charges, itype::charges_to_use(), item::convert(), itype_granade_act, and item::type.
Referenced by Item_factory::init().
granade_act()
int iuse::granade_act (player * p, item * it, bool t, const tripoint & pos)
Maximum Strength increases possible granade str buff for NPCs Maximum Dexterity increases possible granade dex buff for NPCs Maximum Intelligence increases possible granade int buff for NPCs Maximum Perception increases possible granade per buff for NPCs Maximum Strength increases possible granade str buff Maximum Dexterity increases possible granade dex buff Maximum Intelligence increases possible granade int buff Maximum Perception increases possible granade per buff Maximum Strength increases possible granade str debuff for NPCs (NEGATIVE) Maximum Dexterity increases possible granade dex debuff for NPCs (NEGATIVE) Maximum Intelligence increases possible granade int debuff for NPCs (NEGATIVE) Maximum Perception increases possible granade per debuff for NPCs (NEGATIVE) Maximum Strength increases possible granade str debuff (NEGATIVE) Maximum Dexterity increases possible granade dex debuff (NEGATIVE) Maximum Intelligence increases possible granade int debuff (NEGATIVE) Maximum Perception increases possible granade per debuff (NEGATIVE)
Definition at line 3575 of file iuse.cpp.
{
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    }
    if( t ) { // Simple timer effects
        // Vol 0 = only heard if you hold it
        sounds::sound( pos, 0, sounds::sound_t::electronic_speech, _( "Merged!" ),
                       true, "speech", it->typeId().str() );
    } else if( it->charges > 0 ) {
        p->add_msg_if_player( m_info, _( "You've already pulled the %s's pin, try throwing it instead." ),
                              it->tname() );
        return 0;
    } else { // When that timer runs down...
        int explosion_radius = 3;
        int effect_roll = rng( 1, 5 );
        auto buff_stat = [&]( int &current_stat, int modify_by ) {
            auto modified_stat = current_stat + modify_by;
            current_stat = std::max( current_stat, std::min( 15, modified_stat ) );
        };
        switch( effect_roll ) {
            case 1:
                sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "BUGFIXES!" ),
                               true, "speech", it->typeId().str() );
                explosion_handler::draw_explosion( pos, explosion_radius, c_light_cyan, "explosion" );
                for( const tripoint &dest : g->m.points_in_radius( pos, explosion_radius ) ) {
                    monster *const mon = g->critter_at<monster>( dest, true );
                    if( mon && ( mon->type->in_species( INSECT ) || mon->is_hallucination() ) ) {
                        mon->die_in_explosion( nullptr );
                    }
                }
                break;
            case 2:
                sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "BUFFS!" ),
                               true, "speech", it->typeId().str() );
                explosion_handler::draw_explosion( pos, explosion_radius, c_green, "explosion" );
                for( const tripoint &dest : g->m.points_in_radius( pos, explosion_radius ) ) {
                    if( monster *const mon_ptr = g->critter_at<monster>( dest ) ) {
                        monster &critter = *mon_ptr;
                        critter.set_speed_base(
                            critter.get_speed_base() * rng_float( 1.1, 2.0 ) );
                        critter.set_hp( critter.get_hp() * rng_float( 1.1, 2.0 ) );
                    } else if( npc *const person = g->critter_at<npc>( dest ) ) {
                        /** @EFFECT_STR_MAX increases possible granade str buff for NPCs */
                        buff_stat( person->str_max, rng( 0, person->str_max / 2 ) );
                        /** @EFFECT_DEX_MAX increases possible granade dex buff for NPCs */
                        buff_stat( person->dex_max, rng( 0, person->dex_max / 2 ) );
                        /** @EFFECT_INT_MAX increases possible granade int buff for NPCs */
                        buff_stat( person->int_max, rng( 0, person->int_max / 2 ) );
                        /** @EFFECT_PER_MAX increases possible granade per buff for NPCs */
                        buff_stat( person->per_max, rng( 0, person->per_max / 2 ) );
                    } else if( g->u.pos() == dest ) {
                        /** @EFFECT_STR_MAX increases possible granade str buff */
                        buff_stat( g->u.str_max, rng( 0, g->u.str_max / 2 ) );
                        /** @EFFECT_DEX_MAX increases possible granade dex buff */
                        buff_stat( g->u.dex_max, rng( 0, g->u.dex_max / 2 ) );
                        /** @EFFECT_INT_MAX increases possible granade int buff */
                        buff_stat( g->u.int_max, rng( 0, g->u.int_max / 2 ) );
                        /** @EFFECT_PER_MAX increases possible granade per buff */
                        buff_stat( g->u.per_max, rng( 0, g->u.per_max / 2 ) );
                        g->u.recalc_hp();
                        for( const bodypart_id &bp : g->u.get_all_body_parts() ) {
                            g->u.set_part_hp_cur( bp, g->u.get_part_hp_cur( bp ) * rng_float( 1, 1.2 ) );
                            const int hp_max = g->u.get_part_hp_max( bp );
                            if( g->u.get_part_hp_cur( bp ) > hp_max ) {
                                g->u.set_part_hp_cur( bp, hp_max );
                            }
                        }
                    }
                }
                break;
            case 3:
                sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "NERFS!" ),
                               true, "speech", it->typeId().str() );
                explosion_handler::draw_explosion( pos, explosion_radius, c_red, "explosion" );
                for( const tripoint &dest : g->m.points_in_radius( pos, explosion_radius ) ) {
                    if( monster *const mon_ptr = g->critter_at<monster>( dest ) ) {
                        monster &critter = *mon_ptr;
                        critter.set_speed_base(
                            rng( 0, critter.get_speed_base() ) );
                        critter.set_hp( rng( 1, critter.get_hp() ) );
                    } else if( npc *const person = g->critter_at<npc>( dest ) ) {
                        /** @EFFECT_STR_MAX increases possible granade str debuff for NPCs (NEGATIVE) */
                        person->str_max -= rng( 0, person->str_max / 2 );
                        /** @EFFECT_DEX_MAX increases possible granade dex debuff for NPCs (NEGATIVE) */
                        person->dex_max -= rng( 0, person->dex_max / 2 );
                        /** @EFFECT_INT_MAX increases possible granade int debuff for NPCs (NEGATIVE) */
                        person->int_max -= rng( 0, person->int_max / 2 );
                        /** @EFFECT_PER_MAX increases possible granade per debuff for NPCs (NEGATIVE) */
                        person->per_max -= rng( 0, person->per_max / 2 );
                    } else if( g->u.pos() == dest ) {
                        /** @EFFECT_STR_MAX increases possible granade str debuff (NEGATIVE) */
                        g->u.str_max -= rng( 0, g->u.str_max / 2 );
                        /** @EFFECT_DEX_MAX increases possible granade dex debuff (NEGATIVE) */
                        g->u.dex_max -= rng( 0, g->u.dex_max / 2 );
                        /** @EFFECT_INT_MAX increases possible granade int debuff (NEGATIVE) */
                        g->u.int_max -= rng( 0, g->u.int_max / 2 );
                        /** @EFFECT_PER_MAX increases possible granade per debuff (NEGATIVE) */
                        g->u.per_max -= rng( 0, g->u.per_max / 2 );
                        g->u.recalc_hp();
                        for( const bodypart_id &bp : g->u.get_all_body_parts() ) {
                            const int hp_cur = g->u.get_part_hp_cur( bp );
                            if( hp_cur > 0 ) {
                                g->u.set_part_hp_cur( bp, rng( 1, hp_cur ) );
                            }
                        }
                    }
                }
                break;
            case 4:
                sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "REVERTS!" ),
                               true, "speech", it->typeId().str() );
                explosion_handler::draw_explosion( pos, explosion_radius, c_pink, "explosion" );
                for( const tripoint &dest : g->m.points_in_radius( pos, explosion_radius ) ) {
                    if( monster *const mon_ptr = g->critter_at<monster>( dest ) ) {
                        monster &critter = *mon_ptr;
                        critter.set_speed_base( critter.type->speed );
                        critter.set_hp( critter.get_hp_max() );
                        critter.clear_effects();
                    } else if( npc *const person = g->critter_at<npc>( dest ) ) {
                        person->environmental_revert_effect();
                    } else if( g->u.pos() == dest ) {
                        g->u.environmental_revert_effect();
                        do_purify( g->u );
                    }
                }
                break;
            case 5:
                sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "BEES!" ),
                               true, "speech", it->typeId().str() );
                explosion_handler::draw_explosion( pos, explosion_radius, c_yellow, "explosion" );
                for( const tripoint &dest : g->m.points_in_radius( pos, explosion_radius ) ) {
                    if( one_in( 5 ) && !g->critter_at( dest ) ) {
                        g->m.add_field( dest, fd_bees, rng( 1, 3 ) );
                    }
                }
                break;
        }
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), c_green, c_light_cyan, c_pink, c_red, c_yellow, item::charges, itype::charges_to_use(), Creature::clear_effects(), monster::die_in_explosion(), do_purify(), explosion_handler::draw_explosion(), sounds::electronic_speech, fd_bees, g, monster::get_hp(), monster::get_hp_max(), Creature::get_speed_base(), mtype::in_species(), INSECT, monster::is_hallucination(), m_info, one_in(), rng(), rng_float(), monster::set_hp(), Creature::set_speed_base(), sounds::sound(), mtype::speed, string_id< T >::str(), item::tname(), item::type, monster::type, item::typeId(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
grenade_inc_act()
int iuse::grenade_inc_act (player * p, item * it, bool t, const tripoint & pos)
Definition at line 3747 of file iuse.cpp.
{
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    }
    if( t ) { // Simple timer effects
        // Vol 0 = only heard if you hold it
        sounds::sound( pos, 0, sounds::sound_t::alarm, _( "Tick!" ), true, "misc", "bomb_ticking" );
    } else if( it->charges > 0 ) {
        p->add_msg_if_player( m_info, _( "You've already released the handle, try throwing it instead." ) );
        return 0;
    } else {  // blow up
        int num_flames = rng( 3, 5 );
        for( int current_flame = 0; current_flame < num_flames; current_flame++ ) {
            tripoint dest( pos + point( rng( -5, 5 ), rng( -5, 5 ) ) );
            std::vector<tripoint> flames = line_to( pos, dest, 0, 0 );
            for( auto &flame : flames ) {
                g->m.add_field( flame, fd_fire, rng( 0, 2 ) );
            }
        }
        explosion_handler::explosion( pos, 8, 0.8, true );
        for( const tripoint &dest : g->m.points_in_radius( pos, 2 ) ) {
            g->m.add_field( dest, fd_incendiary, 3 );
        }
    }
    return 0;
}
References _, player::add_msg_if_player(), sounds::alarm, item::charges, explosion_handler::explosion(), fd_fire, fd_incendiary, mattack::flame(), g, line_to(), m_info, rng(), sounds::sound(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
gun_repair()
int iuse::gun_repair (player * p, item * it, bool , const tripoint &)
Mechanics >1 allows gun repair Mechanics >=8 allows accurizing ranged weapons
Definition at line 5832 of file iuse.cpp.
{
    if( !it->units_sufficient( *p ) ) {
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    /** @EFFECT_MECHANICS >1 allows gun repair */
    if( p->get_skill_level( skill_mechanics ) < 2 ) {
        p->add_msg_if_player( m_info, _( "You need a mechanics skill of 2 to use this repair kit." ) );
        return 0;
    }
    item_location loc = game_menus::inv::titled_menu( g->u, ( "Select the firearm to repair" ) );
    if( !loc ) {
        p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
        return 0;
    }
    item &fix = *loc;
    if( !fix.is_firearm() ) {
        p->add_msg_if_player( m_info, _( "That isn't a firearm!" ) );
        return 0;
    }
    if( fix.has_flag( "NO_REPAIR" ) ) {
        p->add_msg_if_player( m_info, _( "You cannot repair your %s." ), fix.tname() );
        return 0;
    }
    if( fix.damage() <= fix.min_damage() ) {
        p->add_msg_if_player( m_info, _( "You cannot improve your %s any more this way." ),
                              fix.tname() );
        return 0;
    }
    if( fix.damage() <= 0 && p->get_skill_level( skill_mechanics ) < 8 ) {
        p->add_msg_if_player( m_info, _( "Your %s is already in peak condition." ), fix.tname() );
        p->add_msg_if_player( m_info,
                              _( "With a higher mechanics skill, you might be able to improve it." ) );
        return 0;
    }
    /** @EFFECT_MECHANICS >=8 allows accurizing ranged weapons */
    const std::string startdurability = fix.durability_indicator( true );
    std::string resultdurability;
    const float vision_mod = character_funcs::fine_detail_vision_mod( *p );
    // TODO: this may render player unable to move for minutes, and so should start an activity instead
    if( fix.damage() <= 0 ) {
        sounds::sound( p->pos(), 6, sounds::sound_t::activity, "crunch", true, "tool", "repair_kit" );
        p->moves -= to_moves<int>( 20_seconds * vision_mod );
        p->practice( skill_mechanics, 10 );
        fix.mod_damage( -itype::damage_scale );
        p->add_msg_if_player( m_good, _( "You accurize your %s." ), fix.tname( 1, false ) );
    } else if( fix.damage() > itype::damage_scale ) {
        sounds::sound( p->pos(), 8, sounds::sound_t::activity, "crunch", true, "tool", "repair_kit" );
        p->moves -= to_moves<int>( 10_seconds * vision_mod );
        p->practice( skill_mechanics, 10 );
        fix.mod_damage( -itype::damage_scale );
        resultdurability = fix.durability_indicator( true );
        p->add_msg_if_player( m_good, _( "You repair your %s!  ( %s-> %s)" ), fix.tname( 1, false ),
                              startdurability, resultdurability );
    } else {
        sounds::sound( p->pos(), 8, sounds::sound_t::activity, "crunch", true, "tool", "repair_kit" );
        p->moves -= to_moves<int>( 5_seconds * vision_mod );
        p->practice( skill_mechanics, 10 );
        fix.set_damage( 0 );
        resultdurability = fix.durability_indicator( true );
        p->add_msg_if_player( m_good, _( "You repair your %s completely!  ( %s-> %s)" ),
                              fix.tname( 1, false ), startdurability, resultdurability );
    }
    return it->type->charges_to_use();
}
References _, sounds::activity, player::add_msg_if_player(), itype::charges_to_use(), item::damage(), itype::damage_scale, item::durability_indicator(), character_funcs::fine_detail_vision_mod(), g, Character::get_skill_level(), item::has_flag(), item::is_firearm(), Character::is_mounted(), Creature::is_underwater(), m_good, m_info, item::min_damage(), item::mod_damage(), Creature::moves, Character::pos(), player::practice(), item::set_damage(), skill_mechanics, sounds::sound(), game_menus::inv::titled_menu(), item::tname(), item::type, and item::units_sufficient().
Referenced by Item_factory::init().
gunmod_attach()
int iuse::gunmod_attach (player * p, item * it, bool , const tripoint &)
Definition at line 5908 of file iuse.cpp.
{
    if( !it || !it->is_gunmod() ) {
        debugmsg( "tried to attach non-gunmod" );
        return 0;
    }
    if( !p ) {
        return 0;
    }
    auto loc = game_menus::inv::gun_to_modify( *p, *it );
    if( !loc ) {
        add_msg( m_info, _( "Never mind." ) );
        return 0;
    }
    p->gunmod_add( *loc, *it );
    return 0;
}
References _, add_msg(), debugmsg, game_menus::inv::gun_to_modify(), player::gunmod_add(), item::is_gunmod(), and m_info.
Referenced by Item_factory::init().
hacksaw()
int iuse::hacksaw (player * p, item * it, bool t, const tripoint &)
Definition at line 4956 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::set<ter_id> allowed_ter_id {
        t_chainfence_posts,
        t_window_enhanced,
        t_window_enhanced_noglass,
        t_chainfence,
        t_chaingate_c,
        t_chaingate_l,
        t_window_bars_alarm,
        t_window_bars,
        t_reb_cage,
        t_door_bar_c,
        t_door_bar_locked,
        t_bars
    };
    const std::set<furn_id> allowed_furn_id {
        f_rack
    };
    const std::function<bool( const tripoint & )> f = [&allowed_ter_id,
    &allowed_furn_id]( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        const ter_id ter = g->m.ter( pnt );
        const auto furn = g->m.furn( pnt );
        const bool is_allowed = ( allowed_ter_id.find( ter ) != allowed_ter_id.end() ) ||
                                ( allowed_furn_id.find( furn ) != allowed_furn_id.end() );
        return is_allowed;
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Cut up metal where?" ), _( "There is no metal to cut up nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id ter = g->m.ter( pnt );
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info, _( "Why would you do that?" ) );
            p->add_msg_if_player( m_info, _( "You're not even chained to a boiler." ) );
        } else {
            p->add_msg_if_player( m_info, _( "You can't cut that." ) );
        }
        return 0;
    }
    int moves;
    if( ter == t_chainfence_posts || g->m.furn( pnt ) == f_rack ) {
        moves = to_moves<int>( 2_minutes );
    } else if( ter == t_window_enhanced || ter == t_window_enhanced_noglass ) {
        moves = to_moves<int>( 5_minutes );
    } else if( ter == t_chainfence || ter == t_chaingate_c ||
               ter == t_chaingate_l || ter == t_window_bars_alarm || ter == t_window_bars || ter == t_reb_cage ) {
        moves = to_moves<int>( 10_minutes );
    } else if( ter == t_door_bar_c || ter == t_door_bar_locked || ter == t_bars ) {
        moves = to_moves<int>( 15_minutes );
    } else {
        return 0;
    }
    p->assign_activity( ACT_HACKSAW, moves, static_cast<int>( ter ),
                        p->get_item_position( it ) );
    p->activity.placement = pnt;
    return it->type->charges_to_use();
}
References _, ACT_HACKSAW, Character::activity, player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), f_rack, g, Character::get_item_position(), Character::is_mounted(), m_info, player_activity::placement, Character::pos(), t_bars, t_chainfence, t_chainfence_posts, t_chaingate_c, t_chaingate_l, t_door_bar_c, t_door_bar_locked, t_reb_cage, t_window_bars, t_window_bars_alarm, t_window_enhanced, t_window_enhanced_noglass, and item::type.
Referenced by Item_factory::init().
hairkit()
int iuse::hairkit (player * p, item * it, bool , const tripoint &)
Definition at line 9087 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const int moves = to_moves<int>( 30_minutes );
    p->assign_activity( ACT_HAIRCUT, moves );
    return it->type->charges_to_use();
}
References _, ACT_HAIRCUT, player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), Character::is_mounted(), m_info, and item::type.
Referenced by Item_factory::init().
hammer()
int iuse::hammer (player * p, item * it, bool , const tripoint &)
Definition at line 2358 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::set<ter_id> allowed_ter_id {
        t_fence,
        t_window_boarded,
        t_window_boarded_noglass,
        t_door_boarded,
        t_door_boarded_damaged,
        t_door_boarded_peep,
        t_door_boarded_damaged_peep,
        t_rdoor_boarded,
        t_rdoor_boarded_damaged
    };
    const std::function<bool( const tripoint & )> f = [&allowed_ter_id]( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        const ter_id ter = g->m.ter( pnt );
        const bool is_allowed = allowed_ter_id.find( ter ) != allowed_ter_id.end();
        return is_allowed;
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Pry where?" ), _( "There is nothing to pry nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id type = g->m.ter( pnt );
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( _( "You try to hit yourself with the hammer." ) );
            p->add_msg_if_player( _( "But you can't touch this." ) );
        } else {
            p->add_msg_if_player( m_info, _( "You can't pry that." ) );
        }
        return 0;
    }
    if( type == t_fence || type == t_window_boarded || type == t_window_boarded_noglass ||
        type == t_door_boarded || type == t_door_boarded_damaged ||
        type == t_rdoor_boarded || type == t_rdoor_boarded_damaged ||
        type == t_door_boarded_peep || type == t_door_boarded_damaged_peep ) {
        // pry action
        player_activity act( ACT_PRY_NAILS, to_moves<int>( 30_seconds ), -1 );
        act.placement = pnt;
        p->assign_activity( act );
        return it->type->charges_to_use();
    } else {
        return 0;
    }
}
References _, act, ACT_PRY_NAILS, player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent_highlight(), g, Character::is_mounted(), m_info, Character::pos(), t_door_boarded, t_door_boarded_damaged, t_door_boarded_damaged_peep, t_door_boarded_peep, t_fence, t_rdoor_boarded, t_rdoor_boarded_damaged, t_window_boarded, t_window_boarded_noglass, type, and item::type.
Referenced by Item_factory::init().
hand_crank()
int iuse::hand_crank (player * p, item * it, bool , const tripoint &)
Definition at line 4459 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Long action
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "It's not waterproof enough to work underwater." ) );
        return 0;
    }
    if( p->get_fatigue() >= fatigue_levels::dead_tired ) {
        p->add_msg_if_player( m_info, _( "You're too exhausted to keep cranking." ) );
        return 0;
    }
    item *magazine = it->magazine_current();
    if( magazine && magazine->has_flag( "RECHARGE" ) ) {
        // 1600 minutes. It shouldn't ever run this long, but it's an upper bound.
        // expectation is it runs until the player is too tired.
        int moves = to_moves<int>( 1600_minutes );
        if( it->ammo_capacity() > it->ammo_remaining() ) {
            p->add_msg_if_player( _( "You start cranking the %s to charge its %s." ), it->tname(),
                                  it->magazine_current()->tname() );
            p->assign_activity( ACT_HAND_CRANK, moves, -1, 0, "hand-cranking" );
            p->activity.targets.push_back( item_location( *p, it ) );
        } else {
            p->add_msg_if_player( _( "You could use the %s to charge its %s, but it's already charged." ),
                                  it->tname(), magazine->tname() );
        }
    } else {
        p->add_msg_if_player( m_info, _( "You need a rechargeable battery cell to charge." ) );
    }
    return 0;
}
References _, ACT_HAND_CRANK, Character::activity, player::add_msg_if_player(), item::ammo_capacity(), item::ammo_remaining(), Character::assign_activity(), dead_tired, Character::get_fatigue(), item::has_flag(), player::is_npc(), Creature::is_underwater(), m_info, item::magazine_current(), player_activity::targets, and item::tname().
Referenced by Item_factory::init().
handle_ground_graffiti()
int iuse::handle_ground_graffiti (player & p, item * it, const std::string & prefix, const tripoint & where)
Definition at line 5515 of file iuse.cpp.
{
    string_input_popup popup;
    std::string message = popup
                          .title( prefix + " " + _( "(To delete, clear the text and confirm)" ) )
                          .text( g->m.has_graffiti_at( where ) ? g->m.graffiti_at( where ) : std::string() )
                          .identifier( "graffiti" )
                          .query_string();
    if( popup.canceled() ) {
        return 0;
    }
    bool grave = g->m.ter( where ) == t_grave_new;
    int move_cost;
    if( message.empty() ) {
        if( g->m.has_graffiti_at( where ) ) {
            move_cost = 3 * g->m.graffiti_at( where ).length();
            g->m.delete_graffiti( where );
            if( grave ) {
                p.add_msg_if_player( m_info, _( "You blur the inscription on the grave." ) );
            } else {
                p.add_msg_if_player( m_info, _( "You manage to get rid of the message on the surface." ) );
            }
        } else {
            return 0;
        }
    } else {
        g->m.set_graffiti( where, message );
        if( grave ) {
            p.add_msg_if_player( m_info, _( "You carve an inscription on the grave." ) );
        } else {
            p.add_msg_if_player( m_info, _( "You write a message on the surface." ) );
        }
        move_cost = 2 * message.length();
    }
    p.moves -= move_cost;
    if( it != nullptr ) {
        return it->type->charges_to_use();
    } else {
        return 0;
    }
}
References _, player::add_msg_if_player(), itype::charges_to_use(), g, m_info, mapgen_defer::message, move_cost(), Creature::moves, popup(), prefix, t_grave_new, and item::type.
Referenced by construct::done_grave(), spray_can(), and inscribe_actor::use().
honeycomb()
int iuse::honeycomb (player * p, item * it, bool , const tripoint &)
Definition at line 465 of file iuse.cpp.
{
    g->m.spawn_item( p->pos(), itype_wax, 2 );
    return it->type->charges_to_use();
}
References itype::charges_to_use(), g, itype_wax, Character::pos(), and item::type.
Referenced by Item_factory::init().
inhaler()
int iuse::inhaler (player * p, item * it, bool , const tripoint &)
Definition at line 988 of file iuse.cpp.
{
    p->add_msg_player_or_npc( m_neutral, _( "You take a puff from your inhaler." ),
                              _( "<npcname> takes a puff from their inhaler." ) );
    if( !p->remove_effect( effect_asthma ) ) {
        p->mod_fatigue( -3 ); // if we don't have asthma can be used as stimulant
        if( one_in( 20 ) ) {   // with a small but significant risk of adverse reaction
            p->add_effect( effect_shakes, rng( 2_minutes, 5_minutes ) );
        }
    }
    p->remove_effect( effect_smoke );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_player_or_npc(), itype::charges_to_use(), effect_asthma, effect_shakes, effect_smoke, m_neutral, Character::mod_fatigue(), one_in(), Creature::remove_effect(), rng(), and item::type.
Referenced by Item_factory::init().
jackhammer()
int iuse::jackhammer (player * p, item * it, bool , const tripoint & pos)
Definition at line 3233 of file iuse.cpp.
{
    // use has_enough_charges to check for UPS availability
    // p is assumed to exist for iuse cases
    if( !p->has_enough_charges( *it, false ) ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    tripoint pnt = pos;
    if( pos == p->pos() ) {
        const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Drill where?" ) );
        if( !pnt_ ) {
            return 0;
        }
        pnt = *pnt_;
    }
    if( !g->m.has_flag( "MINEABLE", pnt ) ) {
        p->add_msg_if_player( m_info, _( "You can't drill there." ) );
        return 0;
    }
    if( g->m.veh_at( pnt ) ) {
        p->add_msg_if_player( _( "There's a vehicle in the way!" ) );
        return 0;
    }
    int moves = to_moves<int>( 30_minutes );
    if( g->m.move_cost( pnt ) == 2 ) {
        // We're breaking up some flat surface like pavement, which is much easier
        moves /= 2;
    }
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves = moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( ACT_JACKHAMMER, moves );
    p->activity.targets.push_back( item_location( *p, it ) );
    p->activity.placement = g->m.getabs( pnt );
    p->add_msg_if_player( _( "You start drilling into the %1$s with your %2$s." ),
                          g->m.tername( pnt ), it->tname() );
    return it->type->charges_to_use();
}
References _, ACT_JACKHAMMER, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent(), g, Character::has_enough_charges(), Character::is_mounted(), Creature::is_underwater(), m_info, player_activity::placement, Character::pos(), player_activity::targets, item::tname(), and item::type.
Referenced by Item_factory::init().
jet_injector()
int iuse::jet_injector (player * p, item * it, bool , const tripoint &)
Definition at line 5709 of file iuse.cpp.
{
    if( !it->ammo_sufficient() ) {
        p->add_msg_if_player( m_info, _( "The jet injector is empty." ) );
        return 0;
    } else {
        p->add_msg_if_player( _( "You inject yourself with the jet injector." ) );
        // Intensity is 2 here because intensity = 1 is the comedown
        p->add_effect( effect_jetinjector, 20_minutes, num_bp, 2 );
        p->mod_painkiller( 20 );
        p->mod_stim( 10 );
        p->healall( 20 );
    }
    if( p->has_effect( effect_jetinjector ) ) {
        if( p->get_effect_dur( effect_jetinjector ) > 20_minutes ) {
            p->add_msg_if_player( m_warning, _( "Your heart is beating alarmingly fast!" ) );
        }
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), item::ammo_sufficient(), itype::charges_to_use(), effect_jetinjector, Creature::get_effect_dur(), Creature::has_effect(), Character::healall(), m_info, m_warning, Character::mod_painkiller(), Character::mod_stim(), num_bp, and item::type.
Referenced by Item_factory::init().
ladder()
int iuse::ladder (player * p, item * , bool , const tripoint &)
Definition at line 9352 of file iuse.cpp.
{
    if( !g->m.has_zlevels() ) {
        debugmsg( "Ladder can't be used in non-z-level mode" );
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Put the ladder where?" ) );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint pnt = *pnt_;
    if( !g->is_empty( pnt ) || g->m.has_furn( pnt ) ) {
        p->add_msg_if_player( m_bad, _( "Can't place it there." ) );
        return 0;
    }
    p->add_msg_if_player( _( "You set down the ladder." ) );
    p->moves -= to_moves<int>( 5_seconds );
    g->m.furn_set( pnt, furn_str_id( "f_ladder" ) );
    return 1;
}
References _, player::add_msg_if_player(), choose_adjacent(), debugmsg, g, Character::is_mounted(), m_bad, m_info, and Creature::moves.
Referenced by Item_factory::init(), and game::vertical_move().
lumber()
int iuse::lumber (player * p, item * it, bool t, const tripoint &)
Definition at line 4718 of file iuse.cpp.
{
    if( t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    // Check if player is standing on any lumber
    for( auto &i : g->m.i_at( p->pos() ) ) {
        if( i.typeId() == itype_log ) {
            g->m.i_rem( p->pos(), &i );
            cut_log_into_planks( *p );
            return it->type->charges_to_use();
        }
    }
    // If the player is not standing on a log, check inventory
    avatar *you = p->as_avatar();
    item_location loc;
    auto filter = []( const item & it ) {
        return it.typeId() == itype_log;
    };
    if( you != nullptr ) {
        loc = game_menus::inv::titled_filter_menu( filter, *you, _( "Cut up what?" ) );
    }
    if( !loc ) {
        p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
        return 0;
    }
    p->i_rem( &*loc );
    cut_log_into_planks( *p );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), Creature::as_avatar(), itype::charges_to_use(), cut_log_into_planks(), g, Character::i_rem(), Character::is_mounted(), itype_log, m_info, Character::pos(), game_menus::inv::titled_filter_menu(), item::type, and item::typeId().
Referenced by Item_factory::init().
ma_manual()
int iuse::ma_manual (player * p, item * it, bool , const tripoint &)
Definition at line 2342 of file iuse.cpp.
{
    // [CR] - should NPCs just be allowed to learn this stuff? Just like that?
    const matype_id style_to_learn = martial_art_learned_from( *it->type );
    if( !style_to_learn.is_valid() ) {
        debugmsg( "ERROR: Invalid martial art" );
        return 0;
    }
    p->martial_arts_data->learn_style( style_to_learn, p->is_avatar() );
    return 1;
}
References debugmsg, Creature::is_avatar(), string_id< T >::is_valid(), martial_art_learned_from(), Character::martial_arts_data, and item::type.
Referenced by Item_factory::init().
magic_8_ball()
int iuse::magic_8_ball (player * p, item * it, bool , const tripoint &)
Definition at line 9649 of file iuse.cpp.
{
    enum {
        BALL8_GOOD,
        BALL8_UNK = 10,
        BALL8_BAD = 15
    };
    static const std::array<const char *, 20> tab = {{
            translate_marker( "It is certain." ),
            translate_marker( "It is decidedly so." ),
            translate_marker( "Without a doubt." ),
            translate_marker( "Yes - definitely." ),
            translate_marker( "You may rely on it." ),
            translate_marker( "As I see it, yes." ),
            translate_marker( "Most likely." ),
            translate_marker( "Outlook good." ),
            translate_marker( "Yes." ),
            translate_marker( "Signs point to yes." ),
            translate_marker( "Reply hazy, try again." ),
            translate_marker( "Ask again later." ),
            translate_marker( "Better not tell you now." ),
            translate_marker( "Cannot predict now." ),
            translate_marker( "Concentrate and ask again." ),
            translate_marker( "Don't count on it." ),
            translate_marker( "My reply is no." ),
            translate_marker( "My sources say no." ),
            translate_marker( "Outlook not so good." ),
            translate_marker( "Very doubtful." )
        }
    };
    p->add_msg_if_player( m_info, _( "You ask the %s, then flip it." ), it->tname() );
    int rn = rng( 0, tab.size() - 1 );
    auto color = ( rn >= BALL8_BAD ? m_bad : rn >= BALL8_UNK ? m_info : m_good );
    p->add_msg_if_player( color, _( "The %s says: %s" ), it->tname(), _( tab[rn] ) );
    return 0;
}
References _, player::add_msg_if_player(), color(), m_bad, m_good, m_info, rng(), item::tname(), and translate_marker.
Referenced by Item_factory::init().
makemound()
int iuse::makemound (player * p, item * it, bool t, const tripoint &)
Definition at line 2548 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Till soil where?" ) );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint pnt = *pnt_;
    if( pnt == p->pos() ) {
        p->add_msg_if_player( m_info,
                              _( "You think about jumping on a shovel, but then change up your mind." ) );
        return 0;
    }
    if( g->m.has_flag( flag_PLOWABLE, pnt ) && !g->m.has_flag( flag_PLANT, pnt ) ) {
        p->add_msg_if_player( _( "You start churning up the earth here." ) );
        p->assign_activity( ACT_CHURN, 18000, -1, p->get_item_position( it ) );
        p->activity.placement = g->m.getabs( pnt );
        return it->type->charges_to_use();
    } else {
        p->add_msg_if_player( _( "You can't churn up this ground." ) );
        return 0;
    }
}
References _, ACT_CHURN, Character::activity, player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), choose_adjacent(), flag_PLANT(), flag_PLOWABLE(), g, Character::get_item_position(), Character::is_mounted(), m_info, player_activity::placement, Character::pos(), and item::type.
Referenced by Item_factory::init().
marloss()
int iuse::marloss (player * p, item * it, bool , const tripoint &)
Definition at line 1392 of file iuse.cpp.
{
    if( marloss_prevented( *p ) ) {
        return 0;
    }
    g->events().send<event_type::consumes_marloss_item>( p->getID(), it->typeId() );
    marloss_common( *p, *it, trait_MARLOSS );
    return it->type->charges_to_use();
}
References itype::charges_to_use(), consumes_marloss_item, g, Character::getID(), marloss_common(), marloss_prevented(), trait_MARLOSS, item::type, and item::typeId().
Referenced by Item_factory::init().
marloss_gel()
int iuse::marloss_gel (player * p, item * it, bool , const tripoint &)
Definition at line 1421 of file iuse.cpp.
{
    if( marloss_prevented( *p ) ) {
        return 0;
    }
    g->events().send<event_type::consumes_marloss_item>( p->getID(), it->typeId() );
    marloss_common( *p, *it, trait_MARLOSS_YELLOW );
    return it->type->charges_to_use();
}
References itype::charges_to_use(), consumes_marloss_item, g, Character::getID(), marloss_common(), marloss_prevented(), trait_MARLOSS_YELLOW, item::type, and item::typeId().
Referenced by Item_factory::init().
marloss_seed()
int iuse::marloss_seed (player * p, item * it, bool , const tripoint &)
Definition at line 1404 of file iuse.cpp.
{
    if( !query_yn( _( "Sure you want to eat the %s?  You could plant it in a mound of dirt." ),
                   colorize( it->tname(), it->color_in_inventory() ) ) ) {
        return 0; // Save the seed for later!
    }
    if( marloss_prevented( *p ) ) {
        return 0;
    }
    g->events().send<event_type::consumes_marloss_item>( p->getID(), it->typeId() );
    marloss_common( *p, *it, trait_MARLOSS_BLUE );
    return it->type->charges_to_use();
}
References _, itype::charges_to_use(), item::color_in_inventory(), colorize(), consumes_marloss_item, g, Character::getID(), marloss_common(), marloss_prevented(), query_yn(), item::tname(), trait_MARLOSS_BLUE, item::type, and item::typeId().
Referenced by Item_factory::init().
meditate()
int iuse::meditate (player * p, item * it, bool t, const tripoint &)
Definition at line 896 of file iuse.cpp.
{
    if( !p || t ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( p->has_trait( trait_SPIRITUAL ) ) {
        const int moves = to_moves<int>( 20_minutes );
        p->assign_activity( ACT_MEDITATE, moves );
    } else {
        p->add_msg_if_player( _( "This %s probably meant a lot to someone at one time." ),
                              it->tname() );
    }
    return it->type->charges_to_use();
}
References _, ACT_MEDITATE, player::add_msg_if_player(), Character::assign_activity(), itype::charges_to_use(), Character::has_trait(), Character::is_mounted(), m_info, item::tname(), trait_SPIRITUAL, and item::type.
Referenced by Item_factory::init().
melatonin_tablet()
int iuse::melatonin_tablet (player * p, item * it, bool , const tripoint &)
Definition at line 9617 of file iuse.cpp.
{
    p->add_msg_if_player( _( "You pop a %s." ), it->tname() );
    if( p->has_effect( effect_melatonin_supplements ) ) {
        p->add_msg_if_player( m_warning,
                              _( "Simply taking more melatonin won't help.  You have to go to sleep for it to work." ) );
    }
    p->add_effect( effect_melatonin_supplements, 16_hours );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_melatonin_supplements, Creature::has_effect(), m_warning, item::tname(), and item::type.
meth()
int iuse::meth (player * p, item * it, bool , const tripoint &)
Strength reduces duration of meth Maximum Strength >4 experiences less hunger benefit from meth
Definition at line 819 of file iuse.cpp.
{
    /** @EFFECT_STR reduces duration of meth */
    time_duration duration = 1_minutes * ( 60 - p->str_cur );
    if( p->has_amount( itype_apparatus, 1 ) && p->use_charges_if_avail( itype_fire, 1 ) ) {
        p->add_msg_if_player( m_neutral, _( "You smoke your meth." ) );
        p->add_msg_if_player( m_good, _( "The world seems to sharpen." ) );
        p->mod_fatigue( -375 );
        if( p->has_trait( trait_TOLERANCE ) ) {
            duration *= 1.2;
        } else {
            duration *= ( p->has_trait( trait_LIGHTWEIGHT ) ? 1.8 : 1.5 );
        }
        // breathe out some smoke
        for( int i = 0; i < 3; i++ ) {
            g->m.add_field( {p->posx() + static_cast<int>( rng( -2, 2 ) ), p->posy() + static_cast<int>( rng( -2, 2 ) ), p->posz()},
                            fd_methsmoke, 2 );
        }
    } else {
        p->add_msg_if_player( _( "You snort some crystal meth." ) );
        p->mod_fatigue( -300 );
    }
    if( !p->has_effect( effect_meth ) ) {
        duration += 1_hours;
    }
    if( duration > 0_turns ) {
        // meth actually inhibits hunger, weaker characters benefit more
        /** @EFFECT_STR_MAX >4 experiences less hunger benefit from meth */
        int hungerpen = ( p->str_max < 5 ? 35 : 40 - ( 2 * p->str_max ) );
        if( hungerpen > 0 ) {
            p->mod_stored_kcal( 10 * hungerpen );
        }
        p->add_effect( effect_meth, duration );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_meth, fd_methsmoke, g, visitable< T >::has_amount(), Creature::has_effect(), Character::has_trait(), itype_apparatus, itype_fire, m_good, m_neutral, Character::mod_fatigue(), Character::mod_stored_kcal(), Character::posx(), Character::posy(), Character::posz(), rng(), Character::str_cur, Character::str_max, trait_LIGHTWEIGHT, trait_TOLERANCE, item::type, and Character::use_charges_if_avail().
Referenced by Item_factory::init().
mind_splicer()
int iuse::mind_splicer (player * p, item * it, bool , const tripoint &)
Dexterity makes using the mind splicer faster \EFFECT_FIRSTAID makes using the mind splicer faster
Definition at line 4666 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    for( auto &map_it : g->m.i_at( point( p->posx(), p->posy() ) ) ) {
        if( map_it.typeId() == itype_rmi2_corpse &&
            query_yn( _( "Use the mind splicer kit on the %s?" ), colorize( map_it.tname(),
                      map_it.color_in_inventory() ) ) ) {
            auto filter = []( const item & it ) {
                return it.typeId() == itype_data_card;
            };
            avatar *you = p->as_avatar();
            item_location loc;
            if( you != nullptr ) {
                loc = game_menus::inv::titled_filter_menu( filter, *you, _( "Select storage media" ) );
            }
            if( !loc ) {
                add_msg( m_info, _( "Nevermind." ) );
                return 0;
            }
            item &data_card = *loc;
            ///\EFFECT_DEX makes using the mind splicer faster
            ///\EFFECT_FIRSTAID makes using the mind splicer faster
            const time_duration time = std::max( 150_minutes - 20_minutes * ( p->get_skill_level(
                    skill_firstaid ) - 1 ) - 10_minutes * ( p->get_dex() - 8 ), 30_minutes );
            player_activity act( ACT_MIND_SPLICER, to_moves<int>( time ) );
            act.targets.push_back( item_location( *p, &data_card ) );
            p->assign_activity( act );
            return it->type->charges_to_use();
        }
    }
    add_msg( m_info, _( "There's nothing to use the %s on here." ), it->tname() );
    return 0;
}
References _, act, ACT_MIND_SPLICER, add_msg(), player::add_msg_if_player(), Creature::as_avatar(), Character::assign_activity(), itype::charges_to_use(), colorize(), g, Character::get_dex(), Character::get_skill_level(), Character::is_mounted(), itype_data_card, itype_rmi2_corpse, m_info, Character::posx(), Character::posy(), query_yn(), skill_firstaid, game_menus::inv::titled_filter_menu(), item::tname(), item::type, and item::typeId().
Referenced by Item_factory::init().
mininuke()
int iuse::mininuke (player * p, item * it, bool , const tripoint &)
Definition at line 3899 of file iuse.cpp.
{
    int time;
    bool got_value = query_int( time, _( "Set the timer to ___ turns (0 to cancel)?" ) );
    if( !got_value || time <= 0 ) {
        p->add_msg_if_player( _( "Never mind." ) );
        return 0;
    }
    p->add_msg_if_player( _( "You set the timer to %s." ),
                          to_string( time_duration::from_turns( time ) ) );
    g->events().send<event_type::activates_mininuke>( p->getID() );
    it->convert( itype_mininuke_act );
    it->charges = time;
    it->active = true;
    return it->type->charges_to_use();
}
References _, activates_mininuke, item::active, player::add_msg_if_player(), item::charges, itype::charges_to_use(), item::convert(), time_duration::from_turns(), g, Character::getID(), itype_mininuke_act, query_int(), to_string(), and item::type.
Referenced by Item_factory::init().
molotov_lit()
int iuse::molotov_lit (player * p, item * it, bool t, const tripoint & pos)
Definition at line 3799 of file iuse.cpp.
{
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    } else if( !t ) {
        for( const tripoint &pt : g->m.points_in_radius( pos, 1, 0 ) ) {
            const int intensity = 1 + one_in( 3 ) + one_in( 5 );
            g->m.add_field( pt, fd_fire, intensity );
        }
        return 1;
    } else if( it->charges > 0 ) {
        p->add_msg_if_player( m_info, _( "You've already lit the %s, try throwing it instead." ),
                              it->tname() );
        return 0;
    } else if( p->has_item( *it ) && it->charges == 0 ) {
        it->charges += 1;
        if( one_in( 5 ) ) {
            p->add_msg_if_player( _( "Your lit Molotov goes out." ) );
            it->convert( itype_molotov ).active = false;
        }
        return 0;
    }
    return 0;
}
References _, item::active, player::add_msg_if_player(), item::charges, item::convert(), fd_fire, g, visitable< T >::has_item(), itype_molotov, m_info, one_in(), item::tname(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
mop()
int iuse::mop (player * p, item * it, bool , const tripoint &)
Definition at line 5087 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::vector<field_type_id> to_check = {
        fd_blood,
        fd_blood_veggy,
        fd_blood_insect,
        fd_blood_invertebrate,
        fd_gibs_flesh,
        fd_gibs_veggy,
        fd_gibs_insect,
        fd_gibs_invertebrate,
        fd_bile,
        fd_slime,
        fd_sludge
    };
    const std::function<bool( const tripoint & )> f = [&to_check]( const tripoint & pnt ) {
        if( !g->m.has_flag( "LIQUIDCONT", pnt ) && !g->m.has_flag( "SEALED", pnt ) ) {
            map_stack items = g->m.i_at( pnt );
            auto found = std::find_if( items.begin(), items.end(), []( const item & it ) {
                return it.made_of( LIQUID );
            } );
            if( found != items.end() ) {
                return true;
            }
        }
        field &fld = g->m.field_at( pnt );
        for( field_type_id fid : to_check ) {
            if( fld.find_field_c( fid ) ) {
                return true;
            }
        }
        if( const optional_vpart_position vp = g->m.veh_at( pnt ) ) {
            vehicle *const veh = &vp->vehicle();
            std::vector<int> parts_here = veh->parts_at_relative( vp->mount(), true );
            for( int elem : parts_here ) {
                if( veh->part( elem ).blood > 0 ) {
                    return true;
                }
                vehicle_stack items = veh->get_items( elem );
                auto found = std::find_if( items.begin(), items.end(), []( const item & it ) {
                    return it.made_of( LIQUID );
                } );
                if( found != items.end() ) {
                    return true;
                }
            }
        }
        return false;
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Mop where?" ), _( "There is nothing to mop nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info, _( "You mop yourself up." ) );
            p->add_msg_if_player( m_info, _( "The universe implodes and reforms around you." ) );
        } else {
            p->add_msg_if_player( m_bad, _( "There's nothing to mop there." ) );
        }
        return 0;
    }
    if( p->is_blind() ) {
        p->add_msg_if_player( m_info, _( "You move the mop around, unsure whether it's doing any good." ) );
        p->moves -= 15;
        if( one_in( 3 ) ) {
            g->m.mop_spills( pnt );
        }
    } else if( g->m.mop_spills( pnt ) ) {
        p->add_msg_if_player( m_info, _( "You mop up the spill." ) );
        p->moves -= 15;
    } else {
        return 0;
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), item_stack::begin(), vehicle_part::blood, itype::charges_to_use(), choose_adjacent_highlight(), item_stack::end(), fd_bile, fd_blood, fd_blood_insect, fd_blood_invertebrate, fd_blood_veggy, fd_gibs_flesh, fd_gibs_insect, fd_gibs_invertebrate, fd_gibs_veggy, fd_slime, fd_sludge, field::find_field_c(), g, vehicle::get_items(), Character::is_blind(), Character::is_mounted(), m_bad, m_info, Creature::moves, one_in(), vehicle::part(), vehicle::parts_at_relative(), Character::pos(), item::type, and vehicle::vehicle().
Referenced by Item_factory::init().
mp3()
int iuse::mp3 (player * p, item * it, bool , const tripoint &)
Definition at line 4110 of file iuse.cpp.
{
    // TODO: avoid item id hardcoding to make this function usable for pure json-defined devices.
    if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( m_info, _( "The device's batteries are dead." ) );
    } else if( p->has_active_item( itype_mp3_on ) || p->has_active_item( itype_smartphone_music ) ||
               p->has_active_item( itype_afs_atomic_smartphone_music ) ||
               p->has_active_item( itype_afs_atomic_wraitheon_music ) ) {
        p->add_msg_if_player( m_info, _( "You are already listening to music!" ) );
    } else {
        p->add_msg_if_player( m_info, _( "You put in the earbuds and start listening to music." ) );
        if( it->typeId() == itype_mp3 ) {
            it->convert( itype_mp3_on ).active = true;
        } else if( it->typeId() == itype_smart_phone ) {
            it->convert( itype_smartphone_music ).active = true;
        } else if( it->typeId() == itype_afs_atomic_smartphone ) {
            it->convert( itype_afs_atomic_smartphone_music ).active = true;
        } else if( it->typeId() == itype_afs_wraitheon_smartphone ) {
            it->convert( itype_afs_atomic_wraitheon_music ).active = true;
        }
        p->mod_moves( -200 );
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), Character::has_active_item(), itype_afs_atomic_smartphone, itype_afs_atomic_smartphone_music, itype_afs_atomic_wraitheon_music, itype_afs_wraitheon_smartphone, itype_mp3, itype_mp3_on, itype_smart_phone, itype_smartphone_music, m_info, Creature::mod_moves(), item::type, item::typeId(), and item::units_sufficient().
Referenced by Item_factory::init(), and mapgen_lake_shore().
mp3_on()
int iuse::mp3_on (player * p, item * it, bool t, const tripoint & pos)
Definition at line 4196 of file iuse.cpp.
{
    if( t ) { // Normal use
        if( p->has_item( *it ) ) {
            // mp3 player in inventory, we can listen
            play_music( *p, pos, 0, 20 );
        }
    } else { // Turning it off
        if( it->typeId() == itype_mp3_on ) {
            p->add_msg_if_player( _( "The mp3 player turns off." ) );
            it->convert( itype_mp3 ).active = false;
        } else if( it->typeId() == itype_smartphone_music ) {
            p->add_msg_if_player( _( "The phone turns off." ) );
            it->convert( itype_smart_phone ).active = false;
        } else if( it->typeId() == itype_afs_atomic_smartphone_music ) {
            p->add_msg_if_player( _( "The phone turns off." ) );
            it->convert( itype_afs_atomic_smartphone ).active = false;
        } else if( it->typeId() == itype_afs_atomic_wraitheon_music ) {
            p->add_msg_if_player( _( "The phone turns off." ) );
            it->convert( itype_afs_wraitheon_smartphone ).active = false;
        }
        p->mod_moves( -200 );
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), visitable< T >::has_item(), itype_afs_atomic_smartphone, itype_afs_atomic_smartphone_music, itype_afs_atomic_wraitheon_music, itype_afs_wraitheon_smartphone, itype_mp3, itype_mp3_on, itype_smart_phone, itype_smartphone_music, Creature::mod_moves(), play_music(), item::type, and item::typeId().
Referenced by Item_factory::init().
multicooker()
int iuse::multicooker (player * p, item * it, bool t, const tripoint & pos)
Intelligence increases chance of checking multi-cooker on time Survival increases chance of checking multi-cooker on time Electronics >3 allows multicooker upgrade Fabrication >3 allows multicooker upgrade Intelligence increases chance to successfully upgrade multi-cooker Electronics increases chance to successfully upgrade multi-cooker Fabrication increases chance to successfully upgrade multi-cooker
Definition at line 8389 of file iuse.cpp.
{
    static const std::set<std::string> multicooked_subcats = { "CSC_FOOD_MEAT", "CSC_FOOD_VEGGI", "CSC_FOOD_PASTA" };
    static const int charges_to_start = 50;
    if( t ) {
        if( !it->units_sufficient( *p ) ) {
            it->active = false;
            return 0;
        }
        int cooktime = it->get_var( "COOKTIME", 0 );
        cooktime -= 100;
        if( cooktime >= 300 && cooktime < 400 ) {
            //Smart or good cook or careful
            /** @EFFECT_INT increases chance of checking multi-cooker on time */
            /** @EFFECT_SURVIVAL increases chance of checking multi-cooker on time */
            if( p->int_cur + p->get_skill_level( skill_cooking ) + p->get_skill_level( skill_survival ) > 16 ) {
                add_msg( m_info, _( "The multi-cooker should be finishing shortly" ) );
            }
        }
        if( cooktime <= 0 ) {
            item meal( it->get_var( "DISH" ) );
            it->active = false;
            it->erase_var( "DISH" );
            it->erase_var( "COOKTIME" );
            it->put_in( meal );
            //~ sound of a multi-cooker finishing its cycle!
            sounds::sound( pos, 8, sounds::sound_t::alarm, _( "ding!" ), true, "misc", "ding" );
            return 0;
        } else {
            it->set_var( "COOKTIME", cooktime );
            return 0;
        }
    } else {
        enum {
            mc_start, mc_stop, mc_take, mc_upgrade
        };
        if( p->is_underwater() ) {
            p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
            return 0;
        }
        if( p->has_trait( trait_ILLITERATE ) ) {
            p->add_msg_if_player( m_info,
                                  _( "You cannot read, and don't understand the screen or the buttons!" ) );
            return 0;
        }
        if( p->has_effect( effect_hallu ) || p->has_effect( effect_visuals ) ) {
            if( multicooker_hallu( *p ) ) {
                return 0;
            }
        }
        if( p->has_trait( trait_HYPEROPIC ) && !p->worn_with_flag( "FIX_FARSIGHT" ) &&
            !p->has_effect( effect_contacts ) ) {
            p->add_msg_if_player( m_info,
                                  _( "You'll need to put on reading glasses before you can see the screen." ) );
            return 0;
        }
        uilist menu;
        menu.text = _( "Welcome to the RobotChef3000.  Choose option:" );
        item *dish_it = it->contents.get_item_with(
        []( const item & it ) {
            return !( it.is_toolmod() || it.is_magazine() );
        } );
        if( it->active ) {
            menu.addentry( mc_stop, true, 's', _( "Stop cooking" ) );
        } else {
            if( dish_it == nullptr ) {
                if( it->ammo_remaining() < charges_to_start ) {
                    p->add_msg_if_player( _( "Batteries are low." ) );
                    return 0;
                }
                menu.addentry( mc_start, true, 's', _( "Start cooking" ) );
                /** @EFFECT_ELECTRONICS >3 allows multicooker upgrade */
                /** @EFFECT_FABRICATION >3 allows multicooker upgrade */
                if( p->get_skill_level( skill_electronics ) > 3 && p->get_skill_level( skill_fabrication ) > 3 ) {
                    const auto upgr = it->get_var( "MULTI_COOK_UPGRADE" );
                    if( upgr.empty() ) {
                        menu.addentry( mc_upgrade, true, 'u', _( "Upgrade multi-cooker" ) );
                    } else {
                        if( upgr == "UPGRADE" ) {
                            menu.addentry( mc_upgrade, false, 'u', _( "Multi-cooker already upgraded" ) );
                        } else {
                            menu.addentry( mc_upgrade, false, 'u', _( "Multi-cooker unable to upgrade" ) );
                        }
                    }
                }
            } else {
                menu.addentry( mc_take, true, 't', _( "Take out dish" ) );
            }
        }
        menu.query();
        int choice = menu.ret;
        if( choice < 0 ) {
            return 0;
        }
        if( mc_stop == choice ) {
            if( query_yn( _( "Really stop cooking?" ) ) ) {
                it->active = false;
                it->erase_var( "DISH" );
                it->erase_var( "COOKTIME" );
                it->erase_var( "RECIPE" );
            }
            return 0;
        }
        if( mc_take == choice ) {
            item &dish = *dish_it;
            const std::string dish_name = dish.tname( dish.charges, false );
            if( dish.made_of( LIQUID ) ) {
                if( !p->check_eligible_containers_for_crafting( *recipe_id( it->get_var( "RECIPE" ) ), 1 ) ) {
                    p->add_msg_if_player( m_info, _( "You don't have a suitable container to store your %s." ),
                                          dish_name );
                    return 0;
                }
                liquid_handler::handle_all_liquid( dish, PICKUP_RANGE );
            } else {
                p->i_add( dish );
            }
            it->remove_item( *dish_it );
            it->erase_var( "RECIPE" );
            it->convert( itype_multi_cooker );
            p->add_msg_if_player( m_good, _( "You got the %s from the multi-cooker." ),
                                  dish_name );
            return 0;
        }
        if( mc_start == choice ) {
            uilist dmenu;
            dmenu.text = _( "Choose desired meal:" );
            std::vector<const recipe *> dishes;
            inventory crafting_inv = g->u.crafting_inventory();
            //add some tools and qualities. we can't add this qualities to json, because multicook must be used only by activating, not as component other crafts.
            const time_point bday = calendar::start_of_cataclysm;
            crafting_inv.push_back( item( "hotplate", bday ) ); //hotplate inside
            crafting_inv.push_back( item( "tongs", bday ) ); //some recipes requires tongs
            crafting_inv.push_back( item( "toolset", bday ) ); //toolset with CUT and other qualities inside
            crafting_inv.push_back( item( "pot", bday ) ); //good COOK, BOIL, CONTAIN qualities inside
            int counter = 0;
            for( const auto &r : g->u.get_learned_recipes().in_category( "CC_FOOD" ) ) {
                if( multicooked_subcats.count( r->subcategory ) > 0 ) {
                    dishes.push_back( r );
                    const bool can_make = r->deduped_requirements().can_make_with_inventory(
                                              crafting_inv, r->get_component_filter() );
                    dmenu.addentry( counter++, can_make, -1, r->result_name() );
                }
            }
            dmenu.query();
            int choice = dmenu.ret;
            if( choice < 0 ) {
                return 0;
            } else {
                const recipe *meal = dishes[choice];
                int mealtime;
                if( it->get_var( "MULTI_COOK_UPGRADE" ) == "UPGRADE" ) {
                    mealtime = meal->time;
                } else {
                    mealtime = meal->time * 2;
                }
                const int all_charges = charges_to_start + mealtime / ( it->type->tool->power_draw / 10000 );
                if( it->ammo_remaining() < all_charges ) {
                    p->add_msg_if_player( m_warning,
                                          _( "The multi-cooker needs %d charges to cook this dish." ),
                                          all_charges );
                    return 0;
                }
                const auto filter = is_crafting_component;
                const requirement_data *reqs =
                    meal->deduped_requirements().select_alternative( *p, filter );
                if( !reqs ) {
                    return 0;
                }
                for( auto component : reqs->get_components() ) {
                    p->consume_items( component, 1, filter );
                }
                it->set_var( "RECIPE", meal->ident().str() );
                it->set_var( "DISH", meal->result().str() );
                it->set_var( "COOKTIME", mealtime );
                p->add_msg_if_player( m_good,
                                      _( "The screen flashes blue symbols and scales as the multi-cooker begins to shake." ) );
                it->convert( itype_multi_cooker_filled ).active = true;
                it->ammo_consume( charges_to_start, pos );
                p->practice( skill_cooking, meal->difficulty * 3 ); //little bonus
                return 0;
            }
        }
        if( mc_upgrade == choice ) {
            if( !p->has_morale_to_craft() ) {
                p->add_msg_if_player( m_info, _( "Your morale is too low to craft" ) );
                return 0;
            }
            bool has_tools = true;
            const inventory &cinv = g->u.crafting_inventory();
            if( !cinv.has_amount( itype_soldering_iron, 1 ) ) {
                p->add_msg_if_player( m_warning, _( "You need a %s." ),
                                      item::nname( itype_soldering_iron ) );
                has_tools = false;
            }
            static const quality_id SCREW_FINE( "SCREW_FINE" );
            if( !cinv.has_quality( SCREW_FINE ) ) {
                p->add_msg_if_player( m_warning, _( "You need an item with %s of 1 or more to disassemble this." ),
                                      SCREW_FINE.obj().name );
                has_tools = false;
            }
            if( !has_tools ) {
                return 0;
            }
            p->practice( skill_electronics, rng( 5, 10 ) );
            p->practice( skill_fabrication, rng( 5, 10 ) );
            p->moves -= to_moves<int>( 7_seconds );
            /** @EFFECT_INT increases chance to successfully upgrade multi-cooker */
            /** @EFFECT_ELECTRONICS increases chance to successfully upgrade multi-cooker */
            /** @EFFECT_FABRICATION increases chance to successfully upgrade multi-cooker */
            if( p->get_skill_level( skill_electronics ) + p->get_skill_level( skill_fabrication ) + p->int_cur >
                rng( 20, 35 ) ) {
                p->practice( skill_electronics, rng( 5, 20 ) );
                p->practice( skill_fabrication, rng( 5, 20 ) );
                p->add_msg_if_player( m_good,
                                      _( "You've successfully upgraded the multi-cooker, master tinkerer!  Now it cooks faster!" ) );
                it->set_var( "MULTI_COOK_UPGRADE", "UPGRADE" );
                return 0;
            } else {
                if( !one_in( 5 ) ) {
                    p->add_msg_if_player( m_neutral,
                                          _( "You sagely examine and analyze the multi-cooker, but don't manage to accomplish anything." ) );
                } else {
                    p->add_msg_if_player( m_bad,
                                          _( "Your tinkering nearly breaks the multi-cooker!  Fortunately, it still works, but best to stop messing with it." ) );
                    it->set_var( "MULTI_COOK_UPGRADE", "DAMAGED" );
                }
                return 0;
            }
        }
    }
    return 0;
}
References _, item::active, add_msg(), player::add_msg_if_player(), uilist::addentry(), sounds::alarm, item::ammo_consume(), item::ammo_remaining(), item::charges, player::check_eligible_containers_for_crafting(), player::consume_items(), item::contents, item::convert(), recipe::deduped_requirements(), recipe::difficulty, effect_contacts, effect_hallu, effect_visuals, item::erase_var(), g, requirement_data::get_components(), item_contents::get_item_with(), Character::get_skill_level(), item::get_var(), liquid_handler::handle_all_liquid(), visitable< T >::has_amount(), Creature::has_effect(), Character::has_morale_to_craft(), visitable< T >::has_quality(), Character::has_trait(), Character::i_add(), recipe::ident(), Character::int_cur, is_crafting_component(), item::is_magazine(), item::is_toolmod(), Creature::is_underwater(), itype_multi_cooker, itype_multi_cooker_filled, itype_soldering_iron, LIQUID, m_bad, m_good, m_info, m_neutral, m_warning, item::made_of(), Creature::moves, multicooker_hallu(), quality::name, item::nname(), string_id< T >::obj(), one_in(), PICKUP_RANGE, player::practice(), inventory::push_back(), item::put_in(), uilist::query(), query_yn(), visitable< T >::remove_item(), recipe::result(), uilist::ret, rng(), deduped_requirement_data::select_alternative(), item::set_var(), skill_cooking, skill_electronics, skill_fabrication, skill_survival, sounds::sound(), calendar::start_of_cataclysm, string_id< T >::str(), uilist::text, recipe::time, item::tname(), itype::tool, trait_HYPEROPIC, trait_ILLITERATE, item::type, item::units_sufficient(), and Character::worn_with_flag().
Referenced by Item_factory::init().
mycus()
int iuse::mycus (player * p, item * it, bool t, const tripoint & pos)
Intelligence slightly reduces sleep duration when eating mycus
Definition at line 1433 of file iuse.cpp.
{
    if( p->is_npc() ) {
        return it->type->charges_to_use();
    }
    // Welcome our guide.  Welcome.  To. The Mycus.
    if( p->has_trait( trait_THRESH_MARLOSS ) ) {
        g->events().send<event_type::crosses_mycus_threshold>( p->getID() );
        p->add_msg_if_player( m_neutral,
                              _( "It tastes amazing, and you finish it quickly." ) );
        p->add_msg_if_player( m_good, _( "You feel better all over." ) );
        p->mod_painkiller( 30 );
        purifier( p, it, t, pos ); // Clear out some of that goo you may have floating around
        p->set_rad( 0 );
        p->healall( 4 ); // Can't make you a whole new person, but not for lack of trying
        p->add_msg_if_player( m_good,
                              _( "As it settles in, you feel ecstasy radiating through every part of your body" ) );
        p->add_morale( MORALE_MARLOSS, 1000, 1000 ); // Last time you'll ever have it this good.  So enjoy.
        p->add_msg_if_player( m_good,
                              _( "Your eyes roll back in your head.  Everything dissolves into a blissful haze" ) );
        /** @EFFECT_INT slightly reduces sleep duration when eating mycus */
        p->fall_asleep( 5_hours - p->int_cur * 1_minutes );
        p->unset_mutation( trait_THRESH_MARLOSS );
        p->set_mutation( trait_THRESH_MYCUS );
        g->invalidate_main_ui_adaptor();
        //~ The Mycus does not use the term (or encourage the concept of) "you".  The PC is a local/native organism, but is now the Mycus.
        //~ It still understands the concept, but uninitelligent fungaloids and mind-bent symbiotes should not need it.
        //~ We are the Mycus.
        popup( _( "We welcome into us.  We have endured long in this forbidding world." ) );
        p->add_msg_if_player( " " );
        p->add_msg_if_player( m_good,
                              _( "A sea of white caps, waving gently.  A haze of spores wafting silently over a forest." ) );
        g->invalidate_main_ui_adaptor();
        popup( _( "The natives have a saying: \"E Pluribus Unum.\"  Out of many, one." ) );
        p->add_msg_if_player( " " );
        p->add_msg_if_player( m_good,
                              _( "The blazing pink redness of the berry.  The juices spreading across your tongue, the warmth draping over us like a lover's embrace." ) );
        g->invalidate_main_ui_adaptor();
        popup( _( "We welcome the union of our lines in our local guide.  We will prosper, and unite this world.  Even now, our fruits adapt to better serve local physiology." ) );
        p->add_msg_if_player( " " );
        p->add_msg_if_player( m_good,
                              _( "The sky-blue of the seed.  The nutty, creamy flavors intermingling with the berry, a memory that will never leave us." ) );
        g->invalidate_main_ui_adaptor();
        popup( _( "As, in time, shall we adapt to better welcome those who have not received us." ) );
        p->add_msg_if_player( " " );
        p->add_msg_if_player( m_good,
                              _( "The amber-yellow of the sap.  Feel it flowing through our veins, taking the place of the strange, thin red gruel called \"blood.\"" ) );
        g->invalidate_main_ui_adaptor();
        popup( _( "We are the Mycus." ) );
        /*p->add_msg_if_player( m_good,
                              _( "We welcome into us.  We have endured long in this forbidding world." ) );
        p->add_msg_if_player( m_good,
                              _( "The natives have a saying: \"E Pluribus Unum\"  Out of many, one." ) );
        p->add_msg_if_player( m_good,
                              _( "We welcome the union of our lines in our local guide.  We will prosper, and unite this world." ) );
        p->add_msg_if_player( m_good, _( "Even now, our fruits adapt to better serve local physiology." ) );
        p->add_msg_if_player( m_good,
                              _( "As, in time, shall we adapt to better welcome those who have not received us." ) );*/
        fungal_effects fe( *g, g->m );
        for( const tripoint &nearby_pos : g->m.points_in_radius( p->pos(), 3 ) ) {
            fe.marlossify( nearby_pos );
        }
        p->rem_addiction( add_type::MARLOSS_R );
        p->rem_addiction( add_type::MARLOSS_B );
        p->rem_addiction( add_type::MARLOSS_Y );
    } else if( p->has_trait( trait_THRESH_MYCUS ) &&
               !p->has_trait( trait_M_DEPENDENT ) ) { // OK, now set the hook.
        if( !one_in( 3 ) ) {
            p->mutate_category( "MYCUS" );
            p->mod_stored_nutr( 10 );
            p->mod_thirst( 10 );
            p->mod_fatigue( 5 );
            p->add_morale( MORALE_MARLOSS, 25, 200 ); // still covers up mutation pain
        }
    } else if( p->has_trait( trait_THRESH_MYCUS ) ) {
        p->mod_painkiller( 5 );
        p->mod_stim( 5 );
    } else { // In case someone gets one without having been adapted first.
        // Marloss is the Mycus' method of co-opting humans.  Mycus fruit is for symbiotes' maintenance and development.
        p->add_msg_if_player(
            _( "This tastes really weird!  You're not sure it's good for you" ) );
        p->mutate();
        p->mod_pain( 2 * rng( 1, 5 ) );
        p->mod_stored_nutr( 10 );
        p->mod_thirst( 10 );
        p->mod_fatigue( 5 );
        p->vomit(); // no hunger/quench benefit for you
        p->mod_healthy_mod( -8, -50 );
    }
    return it->type->charges_to_use();
}
References _, Character::add_morale(), player::add_msg_if_player(), itype::charges_to_use(), crosses_mycus_threshold, Character::fall_asleep(), g, Character::getID(), Character::has_trait(), Character::healall(), Character::int_cur, player::is_npc(), m_good, m_neutral, MARLOSS_B, MARLOSS_R, MARLOSS_Y, fungal_effects::marlossify(), Character::mod_fatigue(), Character::mod_healthy_mod(), player::mod_pain(), Character::mod_painkiller(), Character::mod_stim(), Character::mod_stored_nutr(), Character::mod_thirst(), MORALE_MARLOSS, Character::mutate(), Character::mutate_category(), one_in(), popup(), Character::pos(), purifier(), Character::rem_addiction(), rng(), Character::set_mutation(), Character::set_rad(), trait_M_DEPENDENT, trait_THRESH_MARLOSS, trait_THRESH_MYCUS, item::type, Character::unset_mutation(), and Character::vomit().
Referenced by mattack::fungus_fortify(), Item_factory::init(), and Character::update_stomach().
noise_emitter_off()
int iuse::noise_emitter_off (player * p, item * it, bool , const tripoint &)
Definition at line 2249 of file iuse.cpp.
{
    if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( _( "It's dead." ) );
    } else {
        p->add_msg_if_player( _( "You turn the noise emitter on." ) );
        it->convert( itype_noise_emitter_on ).active = true;
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), itype_noise_emitter_on, item::type, and item::units_sufficient().
Referenced by Item_factory::init().
noise_emitter_on()
int iuse::noise_emitter_on (player * p, item * it, bool t, const tripoint & pos)
Definition at line 2260 of file iuse.cpp.
{
    if( t ) { // Normal use
        //~ the sound of a noise emitter when turned on
        sounds::sound( pos, 30, sounds::sound_t::alarm, _( "KXSHHHHRRCRKLKKK!" ), true, "tool",
                       "noise_emitter" );
    } else { // Turning it off
        p->add_msg_if_player( _( "The infernal racket dies as the noise emitter turns off." ) );
        it->convert( itype_noise_emitter ).active = false;
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), sounds::alarm, itype::charges_to_use(), item::convert(), itype_noise_emitter, sounds::sound(), and item::type.
Referenced by Item_factory::init().
note_bionics()
int iuse::note_bionics (player * p, item * it, bool t, const tripoint & pos)
Definition at line 2274 of file iuse.cpp.
{
    const bool possess = p->has_item( *it );
    if( !t ) {
        it->deactivate( p, true );
        return 0;
    }
    if( !p->is_avatar() ) {
        // Not supported at the moment
        return 0;
    }
    map &here = get_map();
    if( !p->has_enough_charges( *it, false ) ) {
        it->deactivate( p, true );
        return 0;
    }
    for( const tripoint &pt : here.points_in_radius( pos, PICKUP_RANGE ) ) {
        if( !here.has_items( pt ) || !p->sees( pt ) ) {
            continue;
        }
        for( item &corpse : here.i_at( pt ) ) {
            if( !corpse.is_corpse() ||
                corpse.get_var( "bionics_scanned_by", -1 ) == p->getID().get_value() ) {
                continue;
            }
            std::vector<const item *> cbms;
            for( const item &maybe_cbm : corpse.components ) {
                if( maybe_cbm.is_bionic() ) {
                    cbms.push_back( &maybe_cbm );
                }
            }
            int charges = static_cast<int>( cbms.size() );
            charges -= it->ammo_consume( charges, pos );
            if( possess && it->has_flag( "USE_UPS" ) ) {
                if( p->use_charges_if_avail( itype_UPS, charges ) ) {
                    charges = 0;
                }
            }
            if( charges > 0 ) {
                it->deactivate( p, true );
                return 0;
            }
            corpse.set_var( "bionics_scanned_by", p->getID().get_value() );
            if( !cbms.empty() ) {
                corpse.set_flag( "CBM_SCANNED" );
                std::string bionics_string =
                    enumerate_as_string( cbms.begin(), cbms.end(),
                []( const item * entry ) -> std::string {
                    return entry->display_name();
                }, enumeration_conjunction::none );
                //~ %1 is corpse name, %2 is direction, %3 is bionic name
                p->add_msg_if_player( m_good, _( "A %1$s located %2$s contains %3$s." ),
                                      corpse.display_name().c_str(),
                                      direction_name( direction_from( p->pos(), pt ) ).c_str(),
                                      bionics_string.c_str()
                                    );
            }
        }
    }
    return 0;
}
References _, player::add_msg_if_player(), item::ammo_consume(), corpse, item::deactivate(), direction_from(), direction_name(), enumerate_as_string(), get_map(), character_id::get_value(), Character::getID(), Character::has_enough_charges(), item::has_flag(), visitable< T >::has_item(), map::has_items(), map::i_at(), Creature::is_avatar(), item::is_bionic(), itype_UPS, m_good, none, PICKUP_RANGE, map::points_in_radius(), Character::pos(), Character::sees(), and Character::use_charges_if_avail().
Referenced by Item_factory::init().
oxygen_bottle()
int iuse::oxygen_bottle (player * p, item * it, bool , const tripoint &)
Definition at line 1002 of file iuse.cpp.
{
    p->moves -= to_moves<int>( 10_seconds );
    p->add_msg_player_or_npc( m_neutral, string_format( _( "You breathe deeply from the %s" ),
                              it->tname() ),
                              string_format( _( "<npcname> breathes from the %s" ),
                                      it->tname() ) );
    if( p->has_effect( effect_smoke ) ) {
        p->remove_effect( effect_smoke );
    } else if( p->has_effect( effect_teargas ) ) {
        p->remove_effect( effect_teargas );
    } else if( p->has_effect( effect_asthma ) ) {
        p->remove_effect( effect_asthma );
    } else if( p->get_stim() < 16 ) {
        p->mod_stim( 8 );
        p->mod_painkiller( 2 );
    }
    p->mod_painkiller( 2 );
    return it->type->charges_to_use();
}
References _, player::add_msg_player_or_npc(), itype::charges_to_use(), effect_asthma, effect_smoke, effect_teargas, Character::get_stim(), Creature::has_effect(), m_neutral, Character::mod_painkiller(), Character::mod_stim(), Creature::moves, Creature::remove_effect(), string_format(), item::tname(), and item::type.
Referenced by Item_factory::init().
oxytorch()
int iuse::oxytorch (player * p, item * it, bool , const tripoint &)
Definition at line 4855 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Long action
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    static const quality_id GLARE( "GLARE" );
    if( !p->has_quality( GLARE, 2 ) ) {
        p->add_msg_if_player( m_info, _( "You need welding goggles to do that." ) );
        return 0;
    }
    const std::set<ter_id> allowed_ter_id {
        t_chainfence_posts,
        t_window_enhanced,
        t_window_enhanced_noglass,
        t_chainfence,
        t_chaingate_c,
        t_chaingate_l,
        t_bars,
        t_window_bars_alarm,
        t_window_bars,
        t_reb_cage,
        t_door_metal_locked,
        t_door_metal_c,
        t_door_bar_c,
        t_door_bar_locked,
        t_door_metal_pickable
    };
    const std::set<furn_id> allowed_furn_id {
        f_rack
    };
    const std::function<bool( const tripoint & )> f = [&allowed_ter_id,
    &allowed_furn_id]( const tripoint & pnt ) {
        if( pnt == g->u.pos() ) {
            return false;
        }
        const ter_id ter = g->m.ter( pnt );
        const auto furn = g->m.furn( pnt );
        const bool is_allowed = ( allowed_ter_id.find( ter ) != allowed_ter_id.end() ) ||
                                ( allowed_furn_id.find( furn ) != allowed_furn_id.end() );
        return is_allowed;
    };
    const cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
            _( "Cut up metal where?" ), _( "There is no metal to cut up nearby." ), f, false );
    if( !pnt_ ) {
        return 0;
    }
    const tripoint &pnt = *pnt_;
    const ter_id ter = g->m.ter( pnt );
    const furn_id furn = g->m.furn( pnt );
    if( !f( pnt ) ) {
        if( pnt == p->pos() ) {
            p->add_msg_if_player( m_info, _( "Yuck.  Acetylene gas smells weird." ) );
        } else {
            p->add_msg_if_player( m_info, _( "You can't cut that." ) );
        }
        return 0;
    }
    int turns = 0;
    if( furn == f_rack || ter == t_chainfence_posts ) {
        turns = to_turns<int>( 2_seconds );
    } else if( ter == t_window_enhanced || ter == t_window_enhanced_noglass ) {
        turns = to_turns<int>( 5_seconds );
    } else if( ter == t_chainfence || ter == t_chaingate_c ||
               ter == t_chaingate_l  || ter == t_bars || ter == t_window_bars_alarm ||
               ter == t_window_bars || ter == t_reb_cage ) {
        turns = to_turns<int>( 10_seconds );
    } else if( ter == t_door_metal_locked || ter == t_door_metal_c || ter == t_door_bar_c ||
               ter == t_door_bar_locked || ter == t_door_metal_pickable ) {
        turns = to_turns<int>( 15_seconds );
    } else {
        return 0;
    }
    const int charges = turns * it->ammo_required();
    int moves = to_moves<int>( time_duration::from_turns( turns ) );
    if( charges > it->ammo_remaining() ) {
        p->add_msg_if_player( m_info, _( "Your torch doesn't have enough acetylene to cut that." ) );
        return 0;
    }
    // placing ter here makes resuming tasks work better
    p->assign_activity( ACT_OXYTORCH, moves, static_cast<int>( ter ) );
    p->activity.targets.push_back( item_location( *p, it ) );
    p->activity.placement = pnt;
    p->activity.values.push_back( charges );
    // charges will be consumed in oxytorch_do_turn, not here
    return 0;
}
References _, ACT_OXYTORCH, Character::activity, player::add_msg_if_player(), item::ammo_remaining(), item::ammo_required(), Character::assign_activity(), choose_adjacent_highlight(), f_rack, time_duration::from_turns(), g, visitable< T >::has_quality(), Character::is_mounted(), player::is_npc(), m_info, player_activity::placement, Character::pos(), t_bars, t_chainfence, t_chainfence_posts, t_chaingate_c, t_chaingate_l, t_door_bar_c, t_door_bar_locked, t_door_metal_c, t_door_metal_locked, t_door_metal_pickable, t_reb_cage, t_window_bars, t_window_bars_alarm, t_window_enhanced, t_window_enhanced_noglass, player_activity::targets, and player_activity::values.
Referenced by Item_factory::init().
pack_cbm()
int iuse::pack_cbm (player * p, item * it, bool , const tripoint &)
Definition at line 2032 of file iuse.cpp.
{
    item_location bionic = g->inv_map_splice( []( const item & e ) {
        return e.is_bionic() && e.has_flag( "NO_PACKED" );
    }, _( "Choose CBM to pack" ), PICKUP_RANGE, _( "You don't have any CBMs." ) );
    if( !bionic ) {
        return 0;
    }
    if( !bionic.get_item()->faults.empty() ) {
        if( p->query_yn( _( "This CBM is faulty.  You should mend it first.  Do you want to try?" ) ) ) {
            p->mend_item( std::move( bionic ) );
        }
        return 0;
    }
    const int success = p->get_skill_level( skill_firstaid ) - rng( 0, 6 );
    if( success > 0 ) {
        p->add_msg_if_player( m_good, _( "You carefully prepare the CBM for sterilization." ) );
        bionic.get_item()->unset_flag( "NO_PACKED" );
    } else {
        p->add_msg_if_player( m_bad, _( "You fail to properly prepare the CBM." ) );
    }
    std::vector<item_comp> comps;
    comps.push_back( item_comp( it->typeId(), 1 ) );
    p->consume_items( comps, 1, is_crafting_component );
    return 0;
}
References _, player::add_msg_if_player(), player::consume_items(), g, Character::get_skill_level(), item::has_flag(), item::is_bionic(), is_crafting_component(), m_bad, m_good, player::mend_item(), avatar_action::move(), PICKUP_RANGE, player::query_yn(), rng(), skill_firstaid, behavior::success, and item::typeId().
Referenced by Item_factory::init().
pack_item()
int iuse::pack_item (player * p, item * it, bool t, const tripoint &)
Definition at line 2063 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( t ) { // Normal use
        // Numbers below -1 are reserved for worn items
    } else if( p->get_item_position( it ) < -1 ) {
        p->add_msg_if_player( m_info, _( "You can't pack your %s until you take it off." ),
                              it->tname() );
        return 0;
    } else { // Turning it off
        std::string oname = it->typeId().str();
        if( string_ends_with( oname, "_on" ) ) {
            oname.erase( oname.length() - 3, 3 );
        } else {
            debugmsg( "no item type to turn it into (%s)!", oname );
            return 0;
        }
        p->moves -= to_moves<int>( 10_seconds );
        p->add_msg_if_player( _( "You pack your %s for storage." ), it->tname() );
        it->convert( itype_id( oname ) ).active = false;
    }
    return 0;
}
References _, item::active, player::add_msg_if_player(), item::convert(), debugmsg, Character::get_item_position(), Creature::is_underwater(), m_info, Creature::moves, string_id< T >::str(), string_ends_with(), item::tname(), and item::typeId().
Referenced by Item_factory::init().
pheromone()
int iuse::pheromone (player * p, item * it, bool , const tripoint & pos)
Definition at line 3916 of file iuse.cpp.
{
    if( !it->ammo_sufficient() ) {
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    }
    p->add_msg_player_or_npc( _( "You squeeze the pheromone ball" ),
                              _( "<npcname> squeezes the pheromone ball" ) );
    p->moves -= 15;
    int converts = 0;
    for( const tripoint &dest : g->m.points_in_radius( pos, 4 ) ) {
        monster *const mon_ptr = g->critter_at<monster>( dest, true );
        if( !mon_ptr ) {
            continue;
        }
        monster &critter = *mon_ptr;
        if( critter.type->in_species( ZOMBIE ) && critter.friendly == 0 &&
            rng( 0, 500 ) > critter.get_hp() ) {
            converts++;
            critter.anger = 0;
        }
    }
    if( g->u.sees( *p ) ) {
        if( converts == 0 ) {
            add_msg( _( "but nothing happens." ) );
        } else if( converts == 1 ) {
            add_msg( m_good, _( "and a nearby zombie becomes passive!" ) );
        } else {
            add_msg( m_good, _( "and several nearby zombies become passive!" ) );
        }
    }
    return it->type->charges_to_use();
}
References _, add_msg(), player::add_msg_if_player(), player::add_msg_player_or_npc(), item::ammo_sufficient(), monster::anger, itype::charges_to_use(), monster::friendly, g, monster::get_hp(), mtype::in_species(), Creature::is_underwater(), m_good, m_info, Creature::moves, rng(), item::type, monster::type, tripoint::x, tripoint::y, and ZOMBIE.
Referenced by Item_factory::init(), monexamine::kill_zslave(), and monexamine::pet_menu().
pickaxe()
int iuse::pickaxe (player * p, item * it, bool , const tripoint & pos)
Definition at line 3288 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Long action
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    tripoint pnt = pos;
    if( pos == p->pos() ) {
        const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Mine where?" ) );
        if( !pnt_ ) {
            return 0;
        }
        pnt = *pnt_;
    }
    if( !g->m.has_flag( "MINEABLE", pnt ) ) {
        p->add_msg_if_player( m_info, _( "You can't mine there." ) );
        return 0;
    }
    if( g->m.veh_at( pnt ) ) {
        p->add_msg_if_player( _( "There's a vehicle in the way!" ) );
        return 0;
    }
    int moves = to_moves<int>( 20_minutes );
    moves += ( ( MAX_STAT + 4 ) - std::min( p->str_cur, MAX_STAT ) ) * to_moves<int>( 5_minutes );
    if( g->m.move_cost( pnt ) == 2 ) {
        // We're breaking up some flat surface like pavement, which is much easier
        moves /= 2;
    }
    const std::vector<npc *> helpers = g->u.get_crafting_helpers( 3 );
    for( const npc *np : helpers ) {
        add_msg( m_info, _( "%s helps with this task" ), np->name );
    }
    moves = moves * ( 10 - helpers.size() ) / 10;
    p->assign_activity( ACT_PICKAXE, moves, -1 );
    p->activity.targets.push_back( item_location( *p, it ) );
    p->activity.placement = g->m.getabs( pnt );
    p->add_msg_if_player( _( "You strike the %1$s with your %2$s." ),
                          g->m.tername( pnt ), it->tname() );
    return 0; // handled when the activity finishes
}
References _, ACT_PICKAXE, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), choose_adjacent(), g, Character::is_mounted(), player::is_npc(), Creature::is_underwater(), m_info, MAX_STAT, player_activity::placement, Character::pos(), Character::str_cur, player_activity::targets, and item::tname().
Referenced by Item_factory::init().
plantblech()
int iuse::plantblech (player * p, item * it, bool , const tripoint & pos)
Definition at line 1073 of file iuse.cpp.
{
    if( p->has_trait( trait_THRESH_PLANT ) ) {
        double multiplier = -1;
        if( p->has_trait( trait_CHLOROMORPH ) ) {
            multiplier = -3;
            p->add_msg_if_player( m_good, _( "The meal is revitalizing." ) );
        } else {
            p->add_msg_if_player( m_good, _( "Oddly enough, this doesn't taste so bad." ) );
        }
        //reverses the harmful values of drinking fertilizer
        p->mod_stored_kcal( -10 * p->nutrition_for( *it ) * multiplier );
        p->mod_thirst( -it->get_comestible()->quench * multiplier );
        p->mod_healthy_mod( it->get_comestible()->healthy * multiplier,
                            it->get_comestible()->healthy * multiplier );
        p->add_morale( MORALE_FOOD_GOOD, -10 * multiplier, 60, 1_hours, 30_minutes, false, it->type );
        return it->type->charges_to_use();
    } else {
        return blech( p, it, true, pos );
    }
}
References _, Character::add_morale(), player::add_msg_if_player(), blech(), itype::charges_to_use(), item::get_comestible(), Character::has_trait(), m_good, Character::mod_healthy_mod(), Character::mod_stored_kcal(), Character::mod_thirst(), MORALE_FOOD_GOOD, Character::nutrition_for(), trait_CHLOROMORPH, trait_THRESH_PLANT, and item::type.
Referenced by Item_factory::init().
play_game()
int iuse::play_game (player * p, item * it, bool t, const tripoint &)
Definition at line 9635 of file iuse.cpp.
{
    if( t ) {
        return 0;
    }
    if( query_yn( _( "Play a game with the %s?" ), it->tname() ) ) {
        p->add_msg_if_player( _( "You start playing." ) );
        p->assign_activity( ACT_GENERIC_GAME, to_moves<int>( 30_minutes ), -1,
                            p->get_item_position( it ), "gaming" );
    }
    return 0;
}
References _, ACT_GENERIC_GAME, player::add_msg_if_player(), Character::assign_activity(), Character::get_item_position(), query_yn(), and item::tname().
Referenced by Item_factory::init().
play_music()
void iuse::play_music (player & p, const tripoint & source, int volume, int max_morale)
Definition at line 4165 of file iuse.cpp.
{
    // TODO: what about other "player", e.g. when a NPC is listening or when the PC is listening,
    // the other characters around should be able to profit as well.
    const bool do_effects = p.can_hear( source, volume );
    std::string sound = "music";
    if( calendar::once_every( 5_minutes ) ) {
        // Every 5 minutes, describe the music
        const std::string music = get_music_description();
        if( !music.empty() ) {
            sound = music;
            // descriptions aren't printed for sounds at our position
            if( p.pos() == source && p.can_hear( source, volume ) ) {
                p.add_msg_if_player( _( "You listen to %s" ), music );
            }
        }
    }
    // do not process mp3 player
    if( volume != 0 ) {
        sounds::ambient_sound( source, volume, sounds::sound_t::music, sound );
    }
    if( do_effects ) {
        p.add_effect( effect_music, 1_turns );
        p.add_morale( MORALE_MUSIC, 1, max_morale, 5_minutes, 2_minutes, true );
        // mp3 player reduces hearing
        if( volume == 0 ) {
            p.add_effect( effect_earphones, 1_turns );
        }
    }
}
References _, Creature::add_effect(), Character::add_morale(), player::add_msg_if_player(), sounds::ambient_sound(), Character::can_hear(), effect_earphones, effect_music, get_music_description(), MORALE_MUSIC, sounds::music, calendar::once_every(), Character::pos(), and sounds::sound().
Referenced by vehicle::play_music().
poison()
int iuse::poison (player * p, item * it, bool , const tripoint &)
Definition at line 875 of file iuse.cpp.
{
    if( ( p->has_trait( trait_EATDEAD ) ) ) {
        return it->type->charges_to_use();
    }
    // NPCs have a magical sense of what is inedible
    // Players can abuse the crafting menu instead...
    if( !it->has_flag( "HIDDEN_POISON" ) &&
        ( p->is_npc() ||
          !p->query_yn( _( "Are you sure you want to eat this?  It looks poisonous" ) ) ) ) {
        return 0;
    }
    if( !p->has_trait( trait_POISRESIST ) ) {
        p->add_effect( effect_poison, 1_hours );
    }
    p->add_effect( effect_foodpoison, 3_hours );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), itype::charges_to_use(), effect_foodpoison, effect_poison, item::has_flag(), Character::has_trait(), player::is_npc(), player::query_yn(), trait_EATDEAD, trait_POISRESIST, and item::type.
Referenced by Item_factory::init(), and item::io().
portable_game()
int iuse::portable_game (player * p, item * it, bool t, const tripoint &)
Definition at line 4376 of file iuse.cpp.
{
    if( t ) {
        return 0;
    }
    if( p->is_npc() ) {
        // Long action
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( p->has_trait( trait_ILLITERATE ) ) {
        p->add_msg_if_player( m_info, _( "You're illiterate!" ) );
        return 0;
    } else if( it->units_remaining( *p ) < ( it->ammo_required() * 15 ) ) {
        p->add_msg_if_player( m_info, _( "You don't have enough charges to play." ) );
        return 0;
    } else {
        std::string loaded_software = "robot_finds_kitten";
        uilist as_m;
        as_m.text = _( "What do you want to play?" );
        as_m.entries.emplace_back( 1, true, '1', _( "Robot finds Kitten" ) );
        as_m.entries.emplace_back( 2, true, '2', _( "S N A K E" ) );
        as_m.entries.emplace_back( 3, true, '3', _( "Sokoban" ) );
        as_m.entries.emplace_back( 4, true, '4', _( "Minesweeper" ) );
        as_m.entries.emplace_back( 5, true, '5', _( "Lights on!" ) );
        as_m.entries.emplace_back( 6, true, '6', _( "Play anything for a while" ) );
        as_m.query();
        switch( as_m.ret ) {
            case 1:
                loaded_software = "robot_finds_kitten";
                break;
            case 2:
                loaded_software = "snake_game";
                break;
            case 3:
                loaded_software = "sokoban_game";
                break;
            case 4:
                loaded_software = "minesweeper_game";
                break;
            case 5:
                loaded_software = "lightson_game";
                break;
            case 6:
                loaded_software = "null";
                break;
            default:
                //Cancel
                return 0;
        }
        //Play in 15-minute chunks
        const int moves = to_moves<int>( 15_minutes );
        p->add_msg_if_player( _( "You play on your %s for a while." ), it->tname() );
        p->assign_activity( ACT_GAME, moves, -1, 0, "gaming" );
        p->activity.targets.push_back( item_location( *p, it ) );
        std::string end_message;
        end_message.clear();
        int game_score = 0;
        play_videogame( loaded_software, end_message, game_score );
        if( !end_message.empty() ) {
            p->add_msg_if_player( end_message );
        }
        if( game_score != 0 ) {
            p->add_morale( MORALE_GAME, game_score, 60, 2_hours, 30_minutes, true );
        }
    }
    return 0;
}
References _, ACT_GAME, Character::activity, Character::add_morale(), player::add_msg_if_player(), item::ammo_required(), Character::assign_activity(), uilist::entries, Character::has_trait(), Character::is_mounted(), player::is_npc(), Creature::is_underwater(), m_info, MORALE_GAME, play_videogame(), uilist::query(), uilist::ret, player_activity::targets, uilist::text, item::tname(), trait_ILLITERATE, and item::units_remaining().
Referenced by Item_factory::init().
portal()
int iuse::portal (player * p, item * it, bool , const tripoint &)
Definition at line 3961 of file iuse.cpp.
{
    if( !it->ammo_sufficient() ) {
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    tripoint t( p->posx() + rng( -2, 2 ), p->posy() + rng( -2, 2 ), p->posz() );
    g->m.trap_set( t, tr_portal );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), item::ammo_sufficient(), itype::charges_to_use(), g, Character::is_mounted(), m_info, Character::posx(), Character::posy(), Character::posz(), rng(), tr_portal, and item::type.
Referenced by Item_factory::init().
prozac()
int iuse::prozac (player * p, item * it, bool , const tripoint &)
Definition at line 937 of file iuse.cpp.
{
    if( !p->has_effect( effect_took_prozac ) ) {
        p->add_effect( effect_took_prozac, 12_hours );
    } else {
        p->mod_stim( 3 );
    }
    if( one_in( 16 ) ) { // adverse reaction, same duration as prozac effect.
        p->add_msg_if_player( m_warning, _( "You suddenly feel hollow inside." ) );
        p->add_effect( effect_took_prozac_bad, p->get_effect_dur( effect_took_prozac ) );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_took_prozac, effect_took_prozac_bad, Creature::get_effect_dur(), Creature::has_effect(), m_warning, Character::mod_stim(), one_in(), and item::type.
Referenced by Item_factory::init().
purifier()
int iuse::purifier (player * p, item * it, bool , const tripoint &)
Definition at line 1129 of file iuse.cpp.
{
    mutagen_attempt checks =
        mutagen_common_checks( *p, *it, false, mutagen_technique::consumed_purifier );
    if( !checks.allowed ) {
        return checks.charges_used;
    }
    do_purify( *p );
    return it->type->charges_to_use();
}
References mutagen_attempt::allowed, itype::charges_to_use(), mutagen_attempt::charges_used, consumed_purifier, do_purify(), mutagen_common_checks(), and item::type.
Referenced by Item_factory::init(), marloss_common(), and mycus().
purify_iv()
int iuse::purify_iv (player * p, item * it, bool , const tripoint &)
Definition at line 1141 of file iuse.cpp.
{
    mutagen_attempt checks =
        mutagen_common_checks( *p, *it, false, mutagen_technique::injected_purifier );
    if( !checks.allowed ) {
        return checks.charges_used;
    }
    std::vector<trait_id> valid; // Which flags the player has
    for( auto &traits_iter : mutation_branch::get_all() ) {
        if( p->has_trait( traits_iter.id ) && !p->has_base_trait( traits_iter.id ) ) {
            //Looks for active mutation
            valid.push_back( traits_iter.id );
        }
    }
    if( valid.empty() ) {
        p->add_msg_if_player( _( "You feel cleansed." ) );
        return it->type->charges_to_use();
    }
    int num_cured = rng( 4,
                         valid.size() ); //Essentially a double-strength purifier, but guaranteed at least 4.  Double-edged and all
    if( num_cured > 8 ) {
        num_cured = 8;
    }
    for( int i = 0; i < num_cured && !valid.empty(); i++ ) {
        const trait_id id = random_entry_removed( valid );
        if( id->purifiable ) {
            p->remove_mutation( id );
        } else {
            p->add_msg_if_player( m_warning, _( "You feel a distinct burning inside, but it passes." ) );
        }
        if( !( p->has_trait( trait_NOPAIN ) ) ) {
            p->mod_pain( 2 * num_cured ); //Hurts worse as it fixes more
            p->add_msg_if_player( m_warning, _( "Feels like you're on fire, but you're OK." ) );
        }
        p->mod_stored_nutr( 2 * num_cured );
        p->mod_thirst( 2 * num_cured );
        p->mod_fatigue( 2 * num_cured );
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), mutagen_attempt::allowed, itype::charges_to_use(), mutagen_attempt::charges_used, mutation_branch::get_all(), Character::has_base_trait(), Character::has_trait(), int_id< T >::id(), injected_purifier, m_warning, Character::mod_fatigue(), player::mod_pain(), Character::mod_stored_nutr(), Character::mod_thirst(), mutagen_common_checks(), random_entry_removed(), Character::remove_mutation(), rng(), trait_NOPAIN, and item::type.
Referenced by Item_factory::init().
purify_smart()
int iuse::purify_smart (player * p, item * it, bool , const tripoint &)
Definition at line 1183 of file iuse.cpp.
{
    mutagen_attempt checks =
        mutagen_common_checks( *p, *it, false, mutagen_technique::injected_smart_purifier );
    if( !checks.allowed ) {
        return checks.charges_used;
    }
    std::vector<trait_id> valid; // Which flags the player has
    std::vector<std::string> valid_names; // Which flags the player has
    for( auto &traits_iter : mutation_branch::get_all() ) {
        if( p->has_trait( traits_iter.id ) &&
            !p->has_base_trait( traits_iter.id ) &&
            traits_iter.id->purifiable ) {
            //Looks for active mutation
            valid.push_back( traits_iter.id );
            valid_names.push_back( traits_iter.id->name() );
        }
    }
    if( valid.empty() ) {
        p->add_msg_if_player( _( "You don't have any mutations to purify." ) );
        return 0;
    }
    int mutation_index = uilist( _( "Choose a mutation to purify" ), valid_names );
    if( mutation_index < 0 ) {
        return 0;
    }
    p->add_msg_if_player(
        _( "You inject the purifier.  The liquid thrashes inside the tube and goes down reluctantly." ) );
    p->remove_mutation( valid[mutation_index] );
    valid.erase( valid.begin() + mutation_index );
    // and one or two more untargeted purifications.
    if( !valid.empty() ) {
        p->remove_mutation( random_entry_removed( valid ) );
    }
    if( !valid.empty() && one_in( 2 ) ) {
        p->remove_mutation( random_entry_removed( valid ) );
    }
    p->mod_pain( 3 );
    item syringe( "syringe", it->birthday() );
    p->i_add( syringe );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), mutagen_attempt::allowed, item::birthday(), itype::charges_to_use(), mutagen_attempt::charges_used, mutation_branch::get_all(), Character::has_base_trait(), Character::has_trait(), Character::i_add(), injected_smart_purifier, player::mod_pain(), mutagen_common_checks(), one_in(), random_entry_removed(), Character::remove_mutation(), and item::type.
Referenced by Item_factory::init().
radglove()
int iuse::radglove (player * p, item * it, bool , const tripoint &)
Definition at line 5754 of file iuse.cpp.
{
    if( p->get_item_position( it ) >= -1 ) {
        p->add_msg_if_player( m_info,
                              _( "You must wear the radiation biomonitor before you can activate it." ) );
        return 0;
    } else if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( m_info, _( "The radiation biomonitor needs batteries to function." ) );
        return 0;
    } else {
        p->add_msg_if_player( _( "You activate your radiation biomonitor." ) );
        if( p->get_rad() >= 1 ) {
            p->add_msg_if_player( m_warning, _( "You are currently irradiated." ) );
            p->add_msg_player_or_say( m_info,
                                      _( "Your radiation level: %d mSv." ),
                                      _( "It says here that my radiation level is %d mSv." ),
                                      p->get_rad() );
        } else {
            p->add_msg_player_or_say( m_info,
                                      _( "You are not currently irradiated." ),
                                      _( "It says I'm not irradiated" ) );
        }
        p->add_msg_if_player( _( "Have a nice day!" ) );
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), player::add_msg_player_or_say(), itype::charges_to_use(), Character::get_item_position(), Character::get_rad(), m_info, m_warning, item::type, and item::units_sufficient().
Referenced by Item_factory::init().
radio_mod()
int iuse::radio_mod (player * p, item * , bool , const tripoint &)
Definition at line 1647 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Now THAT would be kinda cruel
        return 0;
    }
    auto filter = []( const item & itm ) {
        return itm.has_flag( "RADIO_MODABLE" );
    };
    // note: if !p->is_npc() then p is avatar
    item_location loc = game_menus::inv::titled_filter_menu(
                            filter, *p->as_avatar(), _( "Modify what?" ) );
    if( !loc ) {
        p->add_msg_if_player( _( "You do not have that item!" ) );
        return 0;
    }
    item &modded = *loc;
    int choice = uilist( _( "Which signal should activate the item?" ), {
        _( "\"Red\"" ), _( "\"Blue\"" ), _( "\"Green\"" )
    } );
    std::string newtag;
    std::string colorname;
    switch( choice ) {
        case 0:
            newtag = "RADIOSIGNAL_1";
            colorname = _( "\"Red\"" );
            break;
        case 1:
            newtag = "RADIOSIGNAL_2";
            colorname = _( "\"Blue\"" );
            break;
        case 2:
            newtag = "RADIOSIGNAL_3";
            colorname = _( "\"Green\"" );
            break;
        default:
            return 0;
    }
    if( modded.has_flag( "RADIO_MOD" ) && modded.has_flag( newtag ) ) {
        p->add_msg_if_player( _( "This item has been modified this way already." ) );
        return 0;
    }
    remove_radio_mod( modded, *p );
    p->add_msg_if_player(
        _( "You modify your %1$s to listen for %2$s activation signal on the radio." ),
        modded.tname(), colorname );
    modded.set_flag( "RADIO_ACTIVATION" );
    modded.set_flag( "RADIOCARITEM" );
    modded.set_flag( "RADIO_MOD" );
    modded.set_flag( newtag );
    return 1;
}
References _, player::add_msg_if_player(), Creature::as_avatar(), item::has_flag(), player::is_npc(), remove_radio_mod(), item::set_flag(), game_menus::inv::titled_filter_menu(), and item::tname().
Referenced by Item_factory::init().
radio_off()
int iuse::radio_off (player * p, item * it, bool , const tripoint &)
Definition at line 2117 of file iuse.cpp.
{
    if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( _( "It's dead." ) );
    } else {
        p->add_msg_if_player( _( "You turn the radio on." ) );
        it->convert( itype_radio_on ).active = true;
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), itype_radio_on, item::type, and item::units_sufficient().
Referenced by Item_factory::init().
radio_on()
int iuse::radio_on (player * p, item * it, bool t, const tripoint & pos)
Definition at line 2162 of file iuse.cpp.
{
    if( t ) {
        // Normal use
        std::string message = _( "Radio: Kssssssssssssh." );
        const auto tref = overmap_buffer.find_radio_station( it->frequency );
        if( tref ) {
            const auto selected_tower = tref.tower;
            if( selected_tower->type == radio_type::MESSAGE_BROADCAST ) {
                message = selected_tower->message;
            } else if( selected_tower->type == radio_type::WEATHER_RADIO ) {
                message = weather_forecast( tref.abs_sm_pos );
            }
            message = obscure_message( message, [&]()->int {
                int signal_roll = dice( 10, tref.signal_strength * 3 );
                int static_roll = dice( 10, 100 );
                if( static_roll > signal_roll )
                {
                    if( static_roll < signal_roll * 1.1 && one_in( 4 ) ) {
                        return 0;
                    } else {
                        return '#';
                    }
                } else
                {
                    return -1;
                }
            } );
            std::vector<std::string> segments = foldstring( message, RADIO_PER_TURN );
            int index = to_turn<int>( calendar::turn ) % segments.size();
            message = string_format( _( "radio: %s" ), segments[index] );
        }
        sounds::ambient_sound( pos, 6, sounds::sound_t::electronic_speech, message );
        if( !sfx::is_channel_playing( sfx::channel::radio ) ) {
            if( one_in( 10 ) ) {
                sfx::play_ambient_variant_sound( "radio", "static", 100, sfx::channel::radio, 300, -1, 0 );
            } else if( one_in( 10 ) ) {
                sfx::play_ambient_variant_sound( "radio", "inaudible_chatter", 100, sfx::channel::radio, 300, -1,
                                                 0 );
            }
        }
    } else { // Activated
        int ch = 1;
        if( it->ammo_remaining() > 0 ) {
            ch = uilist( _( "Radio:" ), {
                _( "Scan" ), _( "Turn off" )
            } );
        }
        switch( ch ) {
            case 0: {
                const int old_frequency = it->frequency;
                const radio_tower *lowest_tower = nullptr;
                const radio_tower *lowest_larger_tower = nullptr;
                for( auto &tref : overmap_buffer.find_all_radio_stations() ) {
                    const auto new_frequency = tref.tower->frequency;
                    if( new_frequency == old_frequency ) {
                        continue;
                    }
                    if( new_frequency > old_frequency &&
                        ( lowest_larger_tower == nullptr || new_frequency < lowest_larger_tower->frequency ) ) {
                        lowest_larger_tower = tref.tower;
                    } else if( lowest_tower == nullptr || new_frequency < lowest_tower->frequency ) {
                        lowest_tower = tref.tower;
                    }
                }
                if( lowest_larger_tower != nullptr ) {
                    it->frequency = lowest_larger_tower->frequency;
                } else if( lowest_tower != nullptr ) {
                    it->frequency = lowest_tower->frequency;
                }
            }
            break;
            case 1:
                p->add_msg_if_player( _( "The radio dies." ) );
                it->convert( itype_radio ).active = false;
                sfx::fade_audio_channel( sfx::channel::radio, 300 );
                break;
            default:
                break;
        }
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), sounds::ambient_sound(), item::ammo_remaining(), itype::charges_to_use(), item::convert(), dice(), sounds::electronic_speech, sfx::fade_audio_channel(), overmapbuffer::find_all_radio_stations(), overmapbuffer::find_radio_station(), foldstring(), item::frequency, radio_tower::frequency, sfx::is_channel_playing(), itype_radio, mapgen_defer::message, MESSAGE_BROADCAST, obscure_message(), one_in(), overmap_buffer, sfx::play_ambient_variant_sound(), sfx::radio, RADIO_PER_TURN, string_format(), radio_tower_reference::tower, calendar::turn, item::type, weather_forecast(), and WEATHER_RADIO.
Referenced by Item_factory::init().
radiocar()
int iuse::radiocar (player * p, item * it, bool , const tripoint &)
Definition at line 7891 of file iuse.cpp.
{
    int choice = -1;
    item *bomb_it = it->contents.get_item_with( []( const item & c ) {
        return c.has_flag( "RADIOCARITEM" );
    } );
    if( bomb_it == nullptr ) {
        choice = uilist( _( "Using RC car:" ), {
            _( "Turn on" ), _( "Put a bomb to car" )
        } );
    } else {
        choice = uilist( _( "Using RC car:" ), {
            _( "Turn on" ), bomb_it->tname()
        } );
    }
    if( choice < 0 ) {
        return 0;
    }
    if( choice == 0 ) { //Turn car ON
        if( !it->ammo_sufficient() ) {
            p->add_msg_if_player( _( "The RC car's batteries seem to be dead." ) );
            return 0;
        }
        it->convert( itype_radio_car_on ).active = true;
        p->add_msg_if_player(
            _( "You turned on your RC car, now place it on ground, and use radio control to play." ) );
        return 0;
    }
    if( choice == 1 ) {
        if( bomb_it == nullptr ) { //arming car with bomb
            avatar *you = p->as_avatar();
            item_location loc;
            if( you != nullptr ) {
                loc = game_menus::inv::titled_filter_menu( []( const item & it ) {
                    return it.has_flag( "RADIOCARITEM" );
                }, *you, _( "Arm what?" ) );
            }
            if( !loc ) {
                p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
                return 0;
            }
            item &put = *loc;
            if( put.has_flag( "RADIOCARITEM" ) && ( put.volume() <= 1250_ml ||
                                                    ( put.weight() <= 2_kilogram ) ) ) {
                p->moves -= to_moves<int>( 3_seconds );
                p->add_msg_if_player( _( "You armed your RC car with %s." ),
                                      put.tname() );
                it->put_in( p->i_rem( &put ) );
            } else if( !put.has_flag( "RADIOCARITEM" ) ) {
                p->add_msg_if_player( _( "RC car with %s?  How?" ),
                                      put.tname() );
            } else {
                p->add_msg_if_player( _( "Your %s is too heavy or bulky for this RC car." ),
                                      put.tname() );
            }
        } else { // Disarm the car
            p->moves -= to_moves<int>( 2_seconds );
            p->inv.assign_empty_invlet( *bomb_it, *p, true ); // force getting an invlet.
            p->i_add( *bomb_it );
            it->remove_item( *bomb_it );
            p->add_msg_if_player( _( "You disarmed your RC car." ) );
        }
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::ammo_sufficient(), Creature::as_avatar(), inventory::assign_empty_invlet(), c, itype::charges_to_use(), item::contents, item::convert(), item_contents::get_item_with(), item::has_flag(), Character::i_add(), Character::i_rem(), Character::inv, itype_radio_car_on, m_info, Creature::moves, item::put_in(), visitable< T >::remove_item(), game_menus::inv::titled_filter_menu(), item::tname(), item::type, item::volume(), and item::weight().
Referenced by Item_factory::init().
radiocaron()
int iuse::radiocaron (player * p, item * it, bool t, const tripoint & pos)
Definition at line 7968 of file iuse.cpp.
{
    if( t ) {
        //~Sound of a radio controlled car moving around
        sounds::sound( pos, 6, sounds::sound_t::movement, _( "buzzz" ), true, "misc", "rc_car_drives" );
        return it->type->charges_to_use();
    } else if( !it->ammo_sufficient() ) {
        // Deactivate since other mode has an iuse too.
        it->active = false;
        return 0;
    }
    int choice = uilist( _( "What to do with activated RC car?" ), {
        _( "Turn off" )
    } );
    if( choice < 0 ) {
        return it->type->charges_to_use();
    }
    if( choice == 0 ) {
        it->convert( itype_radio_car ).active = false;
        p->add_msg_if_player( _( "You turned off your RC car." ) );
        return it->type->charges_to_use();
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), item::ammo_sufficient(), itype::charges_to_use(), item::convert(), itype_radio_car, sounds::movement, sounds::sound(), and item::type.
Referenced by Item_factory::init().
radiocontrol()
int iuse::radiocontrol (player * p, item * it, bool t, const tripoint &)
Definition at line 8062 of file iuse.cpp.
{
    if( t ) {
        if( !it->units_sufficient( *p ) ) {
            it->active = false;
            p->remove_value( "remote_controlling" );
        } else if( p->get_value( "remote_controlling" ).empty() ) {
            it->active = false;
        }
        return it->type->charges_to_use();
    }
    const char *car_action = nullptr;
    if( !it->active ) {
        car_action = _( "Take control of RC car" );
    } else {
        car_action = _( "Stop controlling RC car" );
    }
    int choice = uilist( _( "What to do with radio control?" ), {
        car_action,
        _( "Press red button" ), _( "Press blue button" ), _( "Press green button" )
    } );
    if( choice < 0 ) {
        return 0;
    } else if( choice == 0 ) {
        if( it->active ) {
            it->active = false;
            p->remove_value( "remote_controlling" );
        } else {
            std::vector<std::pair<tripoint, item *>> rc_pairs;
            for( tripoint pt : g->m.points_on_zlevel( p->posz() ) ) {
                map_cursor mc( pt );
                std::vector<item *> rc_items_here = mc.items_with( [&]( const item & it ) {
                    return it.has_flag( "RADIO_CONTROLLED" );
                } );
                for( item *it : rc_items_here ) {
                    rc_pairs.emplace_back( pt, it );
                }
            }
            if( rc_pairs.empty() ) {
                p->add_msg_if_player( _( "No active RC cars on ground and in range." ) );
                return it->type->charges_to_use();
            }
            std::vector<tripoint> locations;
            uilist pick_rc;
            pick_rc.text = _( "Choose car to control." );
            for( size_t i = 0; i < rc_pairs.size(); i++ ) {
                pick_rc.addentry( i, true, MENU_AUTOASSIGN, rc_pairs[i].second->display_name() );
                locations.push_back( rc_pairs[i].first );
            }
            pointmenu_cb callback( locations );
            pick_rc.callback = &callback;
            pick_rc.query();
            if( pick_rc.ret < 0 || static_cast<size_t>( pick_rc.ret ) >= rc_pairs.size() ) {
                p->add_msg_if_player( m_info, _( "Never mind." ) );
                return it->type->charges_to_use();
            }
            tripoint rc_loc = locations[pick_rc.ret];
            p->add_msg_if_player( m_good, _( "You take control of the RC car." ) );
            p->set_value( "remote_controlling", serialize_wrapper( [&]( JsonOut & jo ) {
                rc_loc.serialize( jo );
            } ) );
            it->active = true;
        }
    } else if( choice > 0 ) {
        const std::string signal = "RADIOSIGNAL_" + std::to_string( choice );
        std::vector<item *> bombs = p->items_with( [&]( const item & it ) -> bool {
            return it.has_flag( "RADIO_ACTIVATION" ) && it.has_flag( "BOMB" ) && it.has_flag( signal );
        } );
        if( !bombs.empty() ) {
            p->add_msg_if_player( m_warning,
                                  _( "The %s in your inventory would explode on this signal.  Place it down before sending the signal." ),
                                  bombs.front()->display_name() );
            return 0;
        }
        p->add_msg_if_player( _( "Click." ) );
        emit_radio_signal( *p, signal );
        p->moves -= to_moves<int>( 2_seconds );
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), uilist::addentry(), uilist::callback, itype::charges_to_use(), emit_radio_signal(), g, Creature::get_value(), item::has_flag(), visitable< T >::items_with(), anonymous_namespace{overmap_location.cpp}::locations, m_good, m_info, m_warning, MENU_AUTOASSIGN, Creature::moves, Character::posz(), uilist::query(), Creature::remove_value(), uilist::ret, second, tripoint::serialize(), serialize_wrapper(), Creature::set_value(), uilist::text, to_string(), item::type, and item::units_sufficient().
Referenced by Item_factory::init().
remoteveh()
int iuse::remoteveh (player * p, item * it, bool t, const tripoint & pos)
Definition at line 8253 of file iuse.cpp.
{
    vehicle *remote = g->remoteveh();
    if( t ) {
        bool stop = false;
        if( !it->units_sufficient( *p ) ) {
            p->add_msg_if_player( m_bad, _( "The remote control's battery goes dead." ) );
            stop = true;
        } else if( remote == nullptr ) {
            p->add_msg_if_player( _( "Lost contact with the vehicle." ) );
            stop = true;
        } else if( remote->fuel_left( itype_battery, true ) == 0 ) {
            p->add_msg_if_player( m_bad, _( "The vehicle's battery died." ) );
            stop = true;
        }
        if( stop ) {
            it->active = false;
            g->setremoteveh( nullptr );
        }
        return it->type->charges_to_use();
    }
    bool controlling = it->active && remote != nullptr;
    int choice = uilist( _( "What to do with remote vehicle control:" ), {
        controlling ? _( "Stop controlling the vehicle." ) : _( "Take control of a vehicle." ),
        _( "Execute one vehicle action" )
    } );
    if( choice < 0 || choice > 1 ) {
        return 0;
    }
    if( choice == 0 && controlling ) {
        it->active = false;
        g->setremoteveh( nullptr );
        return 0;
    }
    point p2( g->u.view_offset.xy() );
    vehicle *veh = pickveh( pos, choice == 0 );
    if( veh == nullptr ) {
        return 0;
    }
    if( !hackveh( *p, *it, *veh ) ) {
        return 0;
    }
    if( choice == 0 ) {
        if( g->u.has_trait( trait_WAYFARER ) ) {
            add_msg( m_info,
                     _( "Despite using a controller, you still refuse to take control of this vehicle." ) );
        } else {
            it->active = true;
            g->setremoteveh( veh );
            p->add_msg_if_player( m_good, _( "You take control of the vehicle." ) );
            if( !veh->engine_on ) {
                veh->start_engines();
            }
        }
    } else if( choice == 1 ) {
        const auto rctrl_parts = veh->get_avail_parts( "REMOTE_CONTROLS" );
        // Revert to original behavior if we can't find remote controls.
        if( empty( rctrl_parts ) ) {
            veh->use_controls( pos );
        } else {
            veh->use_controls( rctrl_parts.begin()->pos() );
        }
    }
    g->u.view_offset.x = p2.x;
    g->u.view_offset.y = p2.y;
    return it->type->charges_to_use();
}
References _, item::active, add_msg(), player::add_msg_if_player(), itype::charges_to_use(), vehicle::engine_on, vehicle::fuel_left(), g, vehicle::get_avail_parts(), hackveh(), itype_battery, m_bad, m_good, m_info, pickveh(), vehicle::start_engines(), trait_WAYFARER, item::type, item::units_sufficient(), vehicle::use_controls(), point::x, and point::y.
Referenced by Item_factory::init(), and map::shift().
remove_all_mods()
int iuse::remove_all_mods (player * p, item * , bool , const tripoint &)
Definition at line 1708 of file iuse.cpp.
{
    if( !p ) {
        return 0;
    }
    item_location loc = g->inv_map_splice( []( const item & e ) {
        for( const item *it : e.toolmods() ) {
            if( !it->is_irremovable() ) {
                return true;
            }
        }
        return false;
    },
    _( "Remove mods from tool?" ), 1,
    _( "You don't have any modified tools." ) );
    if( !loc ) {
        add_msg( m_info, _( "Never mind." ) );
        return 0;
    }
    if( !loc->ammo_remaining() || p->unload( loc ) ) {
        item *mod = loc->contents.get_item_with(
        []( const item & e ) {
            return e.is_toolmod() && !e.is_irremovable();
        } );
        add_msg( m_info, _( "You remove the %s from the tool." ), mod->tname() );
        p->i_add_or_drop( *mod );
        loc->remove_item( *mod );
        remove_radio_mod( *loc, *p );
    }
    return 0;
}
References g, and item::toolmods().
Referenced by Item_factory::init().
report_grid_charge()
int iuse::report_grid_charge (player * p, item * , bool , const tripoint & pos)
Definition at line 9702 of file iuse.cpp.
{
    tripoint_abs_ms pos_abs( get_map().getabs( pos ) );
    const distribution_grid &gr = get_distribution_grid_tracker().grid_at( pos_abs );
    int amt = gr.get_resource();
    p->add_msg_if_player( _( "This electric grid stores %d kJ of electric power." ), amt );
    return 0;
}
References _, player::add_msg_if_player(), get_distribution_grid_tracker(), get_map(), distribution_grid::get_resource(), and distribution_grid_tracker::grid_at().
Referenced by Item_factory::init().
report_grid_connections()
int iuse::report_grid_connections (player * p, item * , bool , const tripoint & pos)
Definition at line 9713 of file iuse.cpp.
{
    tripoint_abs_omt pos_abs = project_to<coords::omt>( tripoint_abs_ms( get_map().getabs( pos ) ) );
    std::vector<tripoint_rel_omt> connections = overmap_buffer.electric_grid_connectivity_at( pos_abs );
    std::vector<std::string> connection_names;
    for( const tripoint_rel_omt &delta : connections ) {
        connection_names.push_back( direction_name( direction_from( delta.raw() ) ) );
    }
    std::string msg;
    if( connection_names.empty() ) {
        msg = _( "This electric grid has no connections." );
    } else {
        //~ %s is list of directions
        msg = string_format( _( "This electric grid has connections: %s." ),
                             enumerate_as_string( connection_names ) );
    }
    p->add_msg_if_player( msg );
    return 0;
}
References _, player::add_msg_if_player(), anonymous_namespace{overmap_connection.cpp}::connections, direction_from(), direction_name(), overmapbuffer::electric_grid_connectivity_at(), enumerate_as_string(), get_map(), overmap_buffer, and string_format().
Referenced by Item_factory::init().
rm13armor_off()
int iuse::rm13armor_off (player * p, item * it, bool , const tripoint &)
Definition at line 1977 of file iuse.cpp.
{
    // This allows it to turn on for a turn, because ammo_sufficient assumes non-tool non-weapons need zero ammo, for some reason.
    if( !it->ammo_sufficient() ) {
        p->add_msg_if_player( m_info, _( "The RM13 combat armor's fuel cells are dead." ) );
        return 0;
    } else {
        std::string oname = it->typeId().str() + "_on";
        p->add_msg_if_player( _( "You activate your RM13 combat armor." ) );
        p->add_msg_if_player( _( "Rivtech Model 13 RivOS v2.19:   ONLINE." ) );
        p->add_msg_if_player( _( "CBRN defense system:            ONLINE." ) );
        p->add_msg_if_player( _( "Acoustic dampening system:      ONLINE." ) );
        p->add_msg_if_player( _( "Thermal regulation system:      ONLINE." ) );
        p->add_msg_if_player( _( "Vision enhancement system:      ONLINE." ) );
        p->add_msg_if_player( _( "Electro-reactive armor system:  ONLINE." ) );
        p->add_msg_if_player( _( "All systems nominal." ) );
        it->convert( itype_id( oname ) ).active = true;
        p->reset_encumbrance();
        return it->type->charges_to_use();
    }
}
References _, item::active, player::add_msg_if_player(), item::ammo_sufficient(), itype::charges_to_use(), item::convert(), m_info, Character::reset_encumbrance(), string_id< T >::str(), item::type, and item::typeId().
Referenced by Item_factory::init().
rm13armor_on()
int iuse::rm13armor_on (player * p, item * it, bool t, const tripoint &)
Definition at line 1999 of file iuse.cpp.
{
    if( t ) { // Normal use
    } else { // Turning it off
        std::string oname = it->typeId().str();
        if( string_ends_with( oname, "_on" ) ) {
            oname.erase( oname.length() - 3, 3 );
        } else {
            debugmsg( "no item type to turn it into (%s)!", oname );
            return 0;
        }
        p->add_msg_if_player( _( "RivOS v2.19 shutdown sequence initiated." ) );
        p->add_msg_if_player( _( "Shutting down." ) );
        p->add_msg_if_player( _( "Your RM13 combat armor turns off." ) );
        it->convert( itype_id( oname ) ).active = false;
        p->reset_encumbrance();
    }
    return it->type->charges_to_use();
}
References _, item::active, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), debugmsg, Character::reset_encumbrance(), string_id< T >::str(), string_ends_with(), item::type, and item::typeId().
Referenced by Item_factory::init().
robotcontrol()
int iuse::robotcontrol (player * p, item * it, bool , const tripoint &)
Intelligence speeds up hacking preperation Computer speeds up hacking preperation
Definition at line 6016 of file iuse.cpp.
{
    if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( _( "The %s's batteries are dead." ), it->tname() );
        return 0;
    }
    if( p->has_trait( trait_ILLITERATE ) ) {
        p->add_msg_if_player( _( "You cannot read a computer screen." ) );
        return 0;
    }
    if( p->has_trait( trait_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
        !p->has_effect( effect_contacts ) && !p->has_bionic( bio_eye_optic ) ) {
        p->add_msg_if_player( m_info,
                              _( "You'll need to put on reading glasses before you can see the screen." ) );
        return 0;
    }
    int choice = uilist( _( "Welcome to hackPRO!:" ), {
        _( "Prepare IFF protocol override" ),
        _( "Set friendly robots to passive mode" ),
        _( "Set friendly robots to combat mode" )
    } );
    switch( choice ) {
        case 0: { // attempt to make a robot friendly
            uilist pick_robot;
            pick_robot.text = _( "Choose an endpoint to hack." );
            // Build a list of all unfriendly robots in range.
            // TODO: change into vector<Creature*>
            std::vector< shared_ptr_fast< monster> > mons;
            std::vector< tripoint > locations;
            int entry_num = 0;
            for( const monster &candidate : g->all_monsters() ) {
                if( robotcontrol_can_target( p, candidate ) ) {
                    mons.push_back( g->shared_from( candidate ) );
                    pick_robot.addentry( entry_num++, true, MENU_AUTOASSIGN, candidate.name() );
                    tripoint seen_loc;
                    // Show locations of seen robots, center on player if robot is not seen
                    if( p->sees( candidate ) ) {
                        seen_loc = candidate.pos();
                    } else {
                        seen_loc = p->pos();
                    }
                    locations.push_back( seen_loc );
                }
            }
            if( mons.empty() ) {
                p->add_msg_if_player( m_info, _( "No enemy robots in range." ) );
                return it->type->charges_to_use();
            }
            pointmenu_cb callback( locations );
            pick_robot.callback = &callback;
            pick_robot.query();
            if( pick_robot.ret < 0 || static_cast<size_t>( pick_robot.ret ) >= mons.size() ) {
                p->add_msg_if_player( m_info, _( "Never mind" ) );
                return it->type->charges_to_use();
            }
            const size_t mondex = pick_robot.ret;
            shared_ptr_fast< monster > z = mons[mondex];
            p->add_msg_if_player( _( "You start reprogramming the %s into an ally." ), z->name() );
            /** @EFFECT_INT speeds up hacking preperation */
            /** @EFFECT_COMPUTER speeds up hacking preperation */
            int move_cost = std::max( 100, 1000 - p->int_cur * 10 - p->get_skill_level( skill_computer ) * 10 );
            player_activity act( ACT_ROBOT_CONTROL, move_cost );
            act.monsters.emplace_back( z );
            p->assign_activity( act );
            return it->type->charges_to_use();
        }
        case 1: { //make all friendly robots stop their purposeless extermination of (un)life.
            p->moves -= to_moves<int>( 1_seconds );
            int f = 0; //flag to check if you have robotic allies
            for( monster &critter : g->all_monsters() ) {
                if( critter.friendly != 0 && critter.type->in_species( ROBOT ) ) {
                    p->add_msg_if_player( _( "A following %s goes into passive mode." ),
                                          critter.name() );
                    critter.add_effect( effect_docile, 1_turns, num_bp );
                    f = 1;
                }
            }
            if( f == 0 ) {
                p->add_msg_if_player( _( "You are not commanding any robots." ) );
                return 0;
            }
            return it->type->charges_to_use();
        }
        case 2: { //make all friendly robots terminate (un)life with extreme prejudice
            p->moves -= to_moves<int>( 1_seconds );
            int f = 0; //flag to check if you have robotic allies
            for( monster &critter : g->all_monsters() ) {
                if( critter.friendly != 0 && critter.has_flag( MF_ELECTRONIC ) ) {
                    p->add_msg_if_player( _( "A following %s goes into combat mode." ),
                                          critter.name() );
                    critter.remove_effect( effect_docile );
                    f = 1;
                }
            }
            if( f == 0 ) {
                p->add_msg_if_player( _( "You are not commanding any robots." ) );
                return 0;
            }
            return it->type->charges_to_use();
        }
    }
    return 0;
}
References _, act, ACT_ROBOT_CONTROL, player::add_msg_if_player(), uilist::addentry(), Character::assign_activity(), bio_eye_optic, uilist::callback, itype::charges_to_use(), effect_contacts, effect_docile, flag_FIX_FARSIGHT(), g, Character::get_skill_level(), Character::has_bionic(), Creature::has_effect(), Character::has_trait(), Character::int_cur, anonymous_namespace{overmap_location.cpp}::locations, m_info, MENU_AUTOASSIGN, MF_ELECTRONIC, move_cost(), Creature::moves, num_bp, Character::pos(), uilist::query(), uilist::ret, ROBOT, robotcontrol_can_target(), Character::sees(), skill_computer, uilist::text, item::tname(), trait_HYPEROPIC, trait_ILLITERATE, item::type, item::units_sufficient(), and Character::worn_with_flag().
Referenced by Item_factory::init().
robotcontrol_can_target()
bool iuse::robotcontrol_can_target (player * p, const monster & m)
Definition at line 6008 of file iuse.cpp.
{
    return !m.is_dead()
           && m.type->in_species( ROBOT )
           && m.friendly == 0
           && rl_dist( p->pos(), m.pos() ) <= 10;
}
References monster::friendly, mtype::in_species(), monster::is_dead(), Character::pos(), monster::pos(), rl_dist(), ROBOT, and monster::type.
Referenced by activity_handlers::robot_control_do_turn(), activity_handlers::robot_control_finish(), and robotcontrol().
rpgdie()
int iuse::rpgdie (player * you, item * die, bool , const tripoint &)
Definition at line 4222 of file iuse.cpp.
{
    if( you->is_mounted() ) {
        you->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    int num_sides = die->get_var( "die_num_sides", 0 );
    if( num_sides == 0 ) {
        const std::vector<int> sides_options = { 4, 6, 8, 10, 12, 20, 50 };
        const int sides = sides_options[ rng( 0, sides_options.size() - 1 ) ];
        num_sides = sides;
        die->set_var( "die_num_sides", sides );
    }
    const int roll = rng( 1, num_sides );
    //~ %1$d: roll number, %2$d: side number of a die, %3$s: die item name
    you->add_msg_if_player( pgettext( "dice", "You roll a %1$d on your %2$d sided %3$s" ), roll,
                            num_sides, die->tname() );
    if( roll == num_sides ) {
        add_msg( m_good, _( "Critical!" ) );
    }
    return roll;
}
References _, add_msg(), player::add_msg_if_player(), item::get_var(), Character::is_mounted(), m_good, m_info, num_sides, pgettext(), rng(), item::set_var(), and item::tname().
Referenced by Item_factory::init().
seed()
int iuse::seed (player * p, item * it, bool , const tripoint &)
Definition at line 5998 of file iuse.cpp.
{
    if( p->is_npc() ||
        query_yn( _( "Sure you want to eat the %s?  You could plant it in a mound of dirt." ),
                  colorize( it->tname(), it->color_in_inventory() ) ) ) {
        return it->type->charges_to_use(); //This eats the seed object.
    }
    return 0;
}
References _, itype::charges_to_use(), item::color_in_inventory(), colorize(), player::is_npc(), query_yn(), item::tname(), and item::type.
Referenced by computer_session::action_research(), iexamine::aggie_plant(), cata::tuple_hash_detail::Impl< Tuple, Index >::apply(), cata::tuple_hash_detail::Impl< Tuple, 0 >::apply(), can_do_activity_there(), farm_action(), iexamine::fertilize_plant(), talk_function::field_harvest(), talk_function::field_plant(), map::furnname(), generic_multi_activity_do(), get_common_data(), iexamine::get_seed_entries(), weather_generator::get_water_temperature(), weather_generator::get_weather(), weather_generator::get_weather_conditions(), weather_generator::get_weather_temperature(), map::grow_plant(), iexamine::harvest_plant(), cata::hash_combine(), Item_factory::init(), main(), vehicle::operate_reaper(), cata::range_hash::operator()(), cata::tuple_hash::operator()(), item::process_rot(), snippet_library::random_from_category(), rng_set_engine_seed(), fungal_effects::spread_fungus_one_tile(), and weather_generator::test_weather().
sewage()
int iuse::sewage (player * p, item * it, bool , const tripoint &)
Definition at line 451 of file iuse.cpp.
{
    if( !p->query_yn( _( "Are you sure you want to drink this?" ) ) ) {
        return 0;
    }
    g->events().send<event_type::eats_sewage>();
    p->vomit();
    if( one_in( 4 ) ) {
        p->mutate();
    }
    return it->type->charges_to_use();
}
References _, itype::charges_to_use(), eats_sewage, g, Character::mutate(), one_in(), player::query_yn(), item::type, and Character::vomit().
Referenced by computer_session::action_sample(), and Item_factory::init().
shavekit()
int iuse::shavekit (player * p, item * it, bool , const tripoint &)
Definition at line 9072 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( !it->ammo_sufficient() ) {
        p->add_msg_if_player( _( "You need soap to use this." ) );
    } else {
        const int moves = to_moves<int>( 5_minutes );
        p->assign_activity( ACT_SHAVE, moves );
    }
    return it->type->charges_to_use();
}
References _, ACT_SHAVE, player::add_msg_if_player(), item::ammo_sufficient(), Character::assign_activity(), itype::charges_to_use(), Character::is_mounted(), m_info, and item::type.
Referenced by Item_factory::init().
shocktonfa_off()
int iuse::shocktonfa_off (player * p, item * it, bool t, const tripoint & pos)
Definition at line 4059 of file iuse.cpp.
{
    int choice = uilist( _( "tactical tonfa" ), {
        _( "Zap something" ), _( "Turn on light" )
    } );
    switch( choice ) {
        case 0: {
            return iuse::tazer2( p, it, t, pos );
        }
        case 1: {
            if( !it->units_sufficient( *p ) ) {
                p->add_msg_if_player( m_info, _( "The batteries are dead." ) );
                return 0;
            } else {
                p->add_msg_if_player( _( "You turn the light on." ) );
                it->convert( itype_shocktonfa_on ).active = true;
                return it->type->charges_to_use();
            }
        }
    }
    return 0;
}
References _, item::active, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), itype_shocktonfa_on, m_info, tazer2(), item::type, and item::units_sufficient().
Referenced by Item_factory::init().
shocktonfa_on()
int iuse::shocktonfa_on (player * p, item * it, bool t, const tripoint & pos)
Definition at line 4083 of file iuse.cpp.
{
    if( t ) { // Effects while simply on
    } else {
        if( !it->units_sufficient( *p ) ) {
            p->add_msg_if_player( m_info, _( "Your tactical tonfa is out of power." ) );
            it->convert( itype_shocktonfa_off ).active = false;
        } else {
            int choice = uilist( _( "tactical tonfa" ), {
                _( "Zap something" ), _( "Turn off light" )
            } );
            switch( choice ) {
                case 0: {
                    return iuse::tazer2( p, it, t, pos );
                }
                case 1: {
                    p->add_msg_if_player( _( "You turn off the light." ) );
                    it->convert( itype_shocktonfa_off ).active = false;
                }
            }
        }
    }
    return 0;
}
References _, item::active, player::add_msg_if_player(), item::convert(), itype_shocktonfa_off, m_info, tazer2(), and item::units_sufficient().
Referenced by Item_factory::init().
siphon()
int iuse::siphon (player * p, item * it, bool , const tripoint &)
Definition at line 2979 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    const std::function<bool( const tripoint & )> f = []( const tripoint & pnt ) {
        const optional_vpart_position vp = g->m.veh_at( pnt );
        return !!vp;
    };
    vehicle *v = nullptr;
    bool found_more_than_one = false;
    for( const tripoint &pos : g->m.points_in_radius( g->u.pos(), 1 ) ) {
        const optional_vpart_position vp = g->m.veh_at( pos );
        if( !vp ) {
            continue;
        }
        vehicle *vfound = &vp->vehicle();
        if( v == nullptr ) {
            v = vfound;
        } else {
            //found more than one vehicle?
            if( v != vfound ) {
                v = nullptr;
                found_more_than_one = true;
                break;
            }
        }
    }
    if( found_more_than_one ) {
        cata::optional<tripoint> pnt_ = choose_adjacent_highlight(
                                            _( "Siphon from where?" ), _( "There is nothing to siphon nearby." ), f, false );
        if( !pnt_ ) {
            return 0;
        }
        const optional_vpart_position vp = g->m.veh_at( *pnt_ );
        if( vp ) {
            v = &vp->vehicle();
        }
    }
    if( v == nullptr ) {
        p->add_msg_if_player( m_info, _( "There's no vehicle there." ) );
        return 0;
    }
    act_vehicle_siphon( v );
    return it->type->charges_to_use();
}
References _, act_vehicle_siphon(), player::add_msg_if_player(), itype::charges_to_use(), choose_adjacent_highlight(), g, Character::is_mounted(), m_info, and item::type.
Referenced by Item_factory::init().
sleep()
int iuse::sleep (player * p, item * it, bool , const tripoint &)
Definition at line 951 of file iuse.cpp.
{
    p->mod_fatigue( 40 );
    p->add_msg_if_player( m_warning, _( "You feel very sleepy" ) );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), m_warning, Character::mod_fatigue(), and item::type.
Referenced by Item_factory::init().
smoking()
int iuse::smoking (player * p, item * it, bool , const tripoint &)
Entry point for intentional bodily intake of smoke via paper wrapped one time use items: cigars, cigarettes, etc.
Parameters
p Player doing the smoking
it the item to be smoked.
Returns
Charges used in item smoked
Definition at line 530 of file iuse.cpp.
{
    bool hasFire = ( p->has_charges( itype_fire, 1 ) );
    // make sure we're not already smoking something
    if( !check_litcig( *p ) ) {
        return 0;
    }
    if( !hasFire ) {
        p->add_msg_if_player( m_info, _( "You don't have anything to light it with!" ) );
        return 0;
    }
    item cig;
    if( it->typeId() == itype_cig ) {
        cig = item( "cig_lit", calendar::turn );
        cig.item_counter = to_turns<int>( 4_minutes );
        p->mod_stored_kcal( 30 );
        p->mod_thirst( 2 );
    } else if( it->typeId() == itype_handrolled_cig ) {
        // This transforms the hand-rolled into a normal cig, which isn't exactly
        // what I want, but leaving it for now.
        cig = item( "cig_lit", calendar::turn );
        cig.item_counter = to_turns<int>( 4_minutes );
        p->mod_thirst( 2 );
        p->mod_stored_kcal( 30 );
    } else if( it->typeId() == itype_cigar ) {
        cig = item( "cigar_lit", calendar::turn );
        cig.item_counter = to_turns<int>( 12_minutes );
        p->mod_thirst( 3 );
        p->mod_stored_kcal( 40 );
    } else if( it->typeId() == itype_joint ) {
        cig = item( "joint_lit", calendar::turn );
        cig.item_counter = to_turns<int>( 4_minutes );
        p->mod_stored_kcal( -40 );
        p->mod_thirst( 6 );
        if( p->get_painkiller() < 5 ) {
            p->set_painkiller( ( p->get_painkiller() + 3 ) * 2 );
        }
    } else {
        p->add_msg_if_player( m_bad,
                              _( "Please let the devs know you should be able to smoke a %s but the smoking code does not know how." ),
                              it->tname() );
        return 0;
    }
    // If we're here, we better have a cig to light.
    p->use_charges_if_avail( itype_fire, 1 );
    cig.active = true;
    p->inv.add_item( cig, false, true );
    p->add_msg_if_player( m_neutral, _( "You light a %s." ), cig.tname() );
    // Parting messages
    if( it->typeId() == itype_joint ) {
        // Would group with the joint, but awkward to mutter before lighting up.
        if( one_in( 5 ) ) {
            weed_msg( *p );
        }
    }
    if( p->get_effect_dur( effect_cig ) > 10_minutes * ( p->addiction_level(
                add_type::CIG ) + 1 ) ) {
        p->add_msg_if_player( m_bad, _( "Ugh, too much smoke you feel nasty." ) );
    }
    return it->type->charges_to_use();
}
References _, item::active, inventory::add_item(), player::add_msg_if_player(), Character::addiction_level(), itype::charges_to_use(), check_litcig(), CIG, effect_cig, Creature::get_effect_dur(), Character::get_painkiller(), Character::has_charges(), Character::inv, item::item_counter, itype_cig, itype_cigar, itype_fire, itype_handrolled_cig, itype_joint, m_bad, m_info, m_neutral, Character::mod_stored_kcal(), Character::mod_thirst(), one_in(), Character::set_painkiller(), item::tname(), calendar::turn, item::type, item::typeId(), Character::use_charges_if_avail(), and weed_msg().
Referenced by Item_factory::init().
solarpack()
int iuse::solarpack (player * p, item * it, bool , const tripoint &)
Definition at line 4293 of file iuse.cpp.
{
    const bionic_id rem_bid = p->get_remote_fueled_bionic();
    if( rem_bid.is_empty() ) {  // Cable CBM required
        p->add_msg_if_player(
            _( "You have no cable charging system to plug it in, so you leave it alone." ) );
        return 0;
    } else if( !p->has_active_bionic( rem_bid ) ) {  // when OFF it takes no effect
        p->add_msg_if_player( _( "Activate your cable charging system to take advantage of it." ) );
    }
    if( it->is_armor() && !( p->is_worn( *it ) ) ) {
        p->add_msg_if_player( m_neutral, _( "You need to wear the %1$s before you can unfold it." ),
                              it->tname() );
        return 0;
    }
    // no doubled sources of power
    if( p->worn_with_flag( "SOLARPACK_ON" ) ) {
        p->add_msg_if_player( m_neutral, _( "You cannot use the %1$s with another of it's kind." ),
                              it->tname() );
        return 0;
    }
    p->add_msg_if_player(
        _( "You unfold solar array from the pack.  You still need to connect it with a cable." ) );
    it->convert( itype_id( it->typeId().str() + "_on" ) );
    return 0;
}
References _, player::add_msg_if_player(), item::convert(), Character::get_remote_fueled_bionic(), Character::has_active_bionic(), item::is_armor(), string_id< T >::is_empty(), Character::is_worn(), m_neutral, string_id< T >::str(), item::tname(), item::typeId(), and Character::worn_with_flag().
Referenced by Item_factory::init().
solarpack_off()
int iuse::solarpack_off (player * p, item * it, bool , const tripoint &)
Definition at line 4322 of file iuse.cpp.
{
    if( !p->is_worn( *it ) ) {  // folding when not worn
        p->add_msg_if_player( _( "You fold your portable solar array into the pack." ) );
    } else {
        p->add_msg_if_player( _( "You unplug and fold your portable solar array into the pack." ) );
    }
    // 3 = "_on"
    it->convert( itype_id( it->typeId().str().substr( 0,
                           it->typeId().str().size() - 3 ) ) ).active = false;
    return 0;
}
References _, item::active, player::add_msg_if_player(), item::convert(), Character::is_worn(), string_id< T >::str(), and item::typeId().
Referenced by Item_factory::init().
spray_can()
int iuse::spray_can (player * p, item * it, bool , const tripoint &)
Definition at line 5506 of file iuse.cpp.
{
    const cata::optional<tripoint> dest_ = choose_adjacent( _( "Spray where?" ) );
    if( !dest_ ) {
        return 0;
    }
    return handle_ground_graffiti( *p, it, _( "Spray what?" ), dest_.value() );
}
References _, choose_adjacent(), handle_ground_graffiti(), and cata::optional< T >::value().
Referenced by Item_factory::init().
stimpack()
int iuse::stimpack (player * p, item * it, bool , const tripoint &)
Definition at line 5731 of file iuse.cpp.
{
    if( p->get_item_position( it ) >= -1 ) {
        p->add_msg_if_player( m_info,
                              _( "You must wear the stimulant delivery system before you can activate it." ) );
        return 0;
    }
    if( !it->ammo_sufficient() ) {
        p->add_msg_if_player( m_info, _( "The stimulant delivery system is empty." ) );
        return 0;
    } else {
        p->add_msg_if_player( _( "You inject yourself with the stimulants." ) );
        // Intensity is 2 here because intensity = 1 is the comedown
        p->add_effect( effect_stimpack, 25_minutes, num_bp, 2 );
        p->mod_painkiller( 2 );
        p->mod_stim( 20 );
        p->mod_fatigue( -100 );
        p->set_stamina( p->get_stamina_max() );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), item::ammo_sufficient(), itype::charges_to_use(), effect_stimpack, Character::get_item_position(), Character::get_stamina_max(), m_info, Character::mod_fatigue(), Character::mod_painkiller(), Character::mod_stim(), num_bp, Character::set_stamina(), and item::type.
Referenced by Item_factory::init().
strong_antibiotic()
int iuse::strong_antibiotic (player * p, item * it, bool , const tripoint &)
Definition at line 9525 of file iuse.cpp.
{
    p->add_msg_player_or_npc( m_neutral,
                              _( "You take some strong antibiotics." ),
                              _( "<npcname> takes some strong antibiotics." ) );
    if( p->has_effect( effect_infected ) && !p->has_effect( effect_strong_antibiotic ) ) {
        p->add_msg_if_player( m_good, _( "You feel much better - almost entirely." ) );
    }
    p->add_effect( effect_strong_antibiotic, 12_hours );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), player::add_msg_player_or_npc(), itype::charges_to_use(), effect_infected, effect_strong_antibiotic, Creature::has_effect(), m_good, m_neutral, and item::type.
Referenced by Item_factory::init().
talking_doll()
int iuse::talking_doll (player * p, item * it, bool , const tripoint &)
Definition at line 5812 of file iuse.cpp.
{
    if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
        return 0;
    }
    const SpeechBubble &speech = get_speech( it->typeId().str() );
    sounds::sound( p->pos(), speech.volume, sounds::sound_t::electronic_speech,
                   speech.text.translated(), true, "speech", it->typeId().str() );
    // Sound code doesn't describe noises at the player position
    if( p->can_hear( p->pos(), speech.volume ) ) {
        p->add_msg_if_player( _( "You hear \"%s\"" ), speech.text );
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), Character::can_hear(), itype::charges_to_use(), sounds::electronic_speech, get_speech(), m_info, Character::pos(), sounds::sound(), speech, string_id< T >::str(), item::tname(), item::type, item::typeId(), and item::units_sufficient().
Referenced by Item_factory::init().
tazer()
int iuse::tazer (player * p, item * it, bool , const tripoint & pos)
Dexterity slightly increases chance of successfully using tazer Melee increases chance of successfully using a tazer Dodge increases chance of dodging a tazer attack
Definition at line 3975 of file iuse.cpp.
{
    if( !it->units_sufficient( *p ) ) {
        return 0;
    }
    tripoint pnt = pos;
    if( pos == p->pos() ) {
        const cata::optional<tripoint> pnt_ = choose_adjacent( _( "Shock where?" ) );
        if( !pnt_ ) {
            return 0;
        }
        pnt = *pnt_;
    }
    if( pnt == p->pos() ) {
        p->add_msg_if_player( m_info, _( "Umm.  No." ) );
        return 0;
    }
    Creature *target = g->critter_at( pnt, true );
    if( target == nullptr ) {
        p->add_msg_if_player( _( "There's nothing to zap there!" ) );
        return 0;
    }
    npc *foe = dynamic_cast<npc *>( target );
    if( foe != nullptr &&
        !foe->is_enemy() &&
        !p->query_yn( _( "Really shock %s?" ), target->disp_name() ) ) {
        return 0;
    }
    /** @EFFECT_DEX slightly increases chance of successfully using tazer */
    /** @EFFECT_MELEE increases chance of successfully using a tazer */
    int numdice = 3 + ( p->dex_cur / 2.5 ) + p->get_skill_level( skill_melee ) * 2;
    p->moves -= to_moves<int>( 1_seconds );
    /** @EFFECT_DODGE increases chance of dodging a tazer attack */
    const bool tazer_was_dodged = dice( numdice, 10 ) < dice( target->get_dodge(), 10 );
    if( tazer_was_dodged ) {
        p->add_msg_player_or_npc( _( "You attempt to shock %s, but miss." ),
                                  _( "<npcname> attempts to shock %s, but misses." ),
                                  target->disp_name() );
    } else {
        // TODO: Maybe - Execute an attack and maybe zap something other than torso
        // Maybe, because it's torso (heart) that fails when zapped with electricity
        int dam = target->deal_damage( p, bodypart_id( "torso" ), damage_instance( DT_ELECTRIC, rng( 5,
                                       25 ) ) ).total_damage();
        if( dam > 0 ) {
            p->add_msg_player_or_npc( m_good,
                                      _( "You shock %s!" ),
                                      _( "<npcname> shocks %s!" ),
                                      target->disp_name() );
        } else {
            p->add_msg_player_or_npc( m_warning,
                                      _( "You unsuccessfully attempt to shock %s!" ),
                                      _( "<npcname> unsuccessfully attempts to shock %s!" ),
                                      target->disp_name() );
        }
    }
    if( foe != nullptr ) {
        foe->on_attacked( *p );
    }
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), player::add_msg_player_or_npc(), itype::charges_to_use(), choose_adjacent(), Creature::deal_damage(), Character::dex_cur, dice(), Creature::disp_name(), DT_ELECTRIC, g, Creature::get_dodge(), Character::get_skill_level(), npc::is_enemy(), m_good, m_info, m_warning, Creature::moves, npc::on_attacked(), Character::pos(), player::query_yn(), rng(), skill_melee, dealt_damage_instance::total_damage(), item::type, and item::units_sufficient().
Referenced by Item_factory::init(), and tazer2().
tazer2()
int iuse::tazer2 (player * p, item * it, bool b, const tripoint & pos)
Definition at line 4044 of file iuse.cpp.
{
    if( it->ammo_remaining() >= 100 ) {
        // Instead of having a ctrl+c+v of the function above, spawn a fake tazer and use it
        // Ugly, but less so than copied blocks
        item fake( "tazer", calendar::start_of_cataclysm );
        fake.charges = 100;
        return tazer( p, &fake, b, pos );
    } else {
        p->add_msg_if_player( m_info, _( "Insufficient power" ) );
    }
    return 0;
}
References _, player::add_msg_if_player(), item::ammo_remaining(), b, item::charges, m_info, calendar::start_of_cataclysm, and tazer().
Referenced by Item_factory::init(), shocktonfa_off(), and shocktonfa_on().
teleport()
int iuse::teleport (player * p, item * it, bool , const tripoint &)
Definition at line 3473 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // That would be evil
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( !it->ammo_sufficient() ) {
        return 0;
    }
    p->moves -= to_moves<int>( 1_seconds );
    teleport::teleport( *p );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), item::ammo_sufficient(), itype::charges_to_use(), Character::is_mounted(), player::is_npc(), m_info, Creature::moves, teleport::teleport(), and item::type.
Referenced by Item_factory::init().
thorazine()
int iuse::thorazine (player * p, item * it, bool , const tripoint &)
Definition at line 915 of file iuse.cpp.
{
    if( p->has_effect( effect_took_thorazine ) ) {
        p->remove_effect( effect_took_thorazine );
        p->mod_fatigue( 15 );
    }
    p->add_effect( effect_took_thorazine, 12_hours );
    p->mod_fatigue( 5 );
    p->remove_effect( effect_hallu );
    p->remove_effect( effect_visuals );
    if( !p->has_effect( effect_dermatik ) ) {
        p->remove_effect( effect_formication );
    }
    if( one_in( 50 ) ) { // adverse reaction
        p->add_msg_if_player( m_bad, _( "You feel completely exhausted." ) );
        p->mod_fatigue( 50 );
    } else {
        p->add_msg_if_player( m_warning, _( "You feel a bit wobbly." ) );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_dermatik, effect_formication, effect_hallu, effect_took_thorazine, effect_visuals, Creature::has_effect(), m_bad, m_warning, Character::mod_fatigue(), one_in(), Creature::remove_effect(), and item::type.
Referenced by Item_factory::init().
throwable_extinguisher_act()
int iuse::throwable_extinguisher_act (player * , item * it, bool , const tripoint & pos)
Definition at line 3544 of file iuse.cpp.
{
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    }
    if( g->m.get_field( pos, fd_fire ) != nullptr ) {
        sounds::sound( pos, 50, sounds::sound_t::combat, _( "Bang!" ), false, "explosion", "small" );
        // Reduce the strength of fire (if any) in the target tile.
        g->m.mod_field_intensity( pos, fd_fire, 0 - 2 );
        // Slightly reduce the strength of fire around and in the target tile.
        for( const tripoint &dest : g->m.points_in_radius( pos, 1 ) ) {
            if( g->m.passable( dest ) && dest != pos ) {
                g->m.mod_field_intensity( dest, fd_fire, 0 - rng( 0, 2 ) );
            }
        }
        it->charges = -1;
        return 1;
    }
    it->active = false;
    return 0;
}
References _, item::active, item::charges, sounds::combat, fd_fire, g, rng(), sounds::sound(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
toggle_heats_food()
int iuse::toggle_heats_food (player * p, item * it, bool , const tripoint &)
Definition at line 9687 of file iuse.cpp.
{
    if( it->item_tags.count( flag_HEATS_FOOD ) == 0 ) {
        it->item_tags.insert( flag_HEATS_FOOD );
        p->add_msg_if_player(
            _( "You will try to use %s to heat food next time you eat something that should be eaten hot." ),
            it->tname().c_str() );
    } else {
        it->item_tags.erase( flag_HEATS_FOOD );
        p->add_msg_if_player( _( "You will no longer use %s to heat food." ), it->tname().c_str() );
    }
    return 0;
}
References _, player::add_msg_if_player(), cata::flat_set< T, Compare, Data >::count(), cata::flat_set< T, Compare, Data >::erase(), flag_HEATS_FOOD(), cata::flat_set< T, Compare, Data >::insert(), item::item_tags, and item::tname().
Referenced by Item_factory::finalize_pre(), and Item_factory::init().
toolmod_attach()
int iuse::toolmod_attach (player * p, item * it, bool , const tripoint &)
Definition at line 5931 of file iuse.cpp.
{
    if( !it || !it->is_toolmod() ) {
        debugmsg( "tried to attach non-toolmod" );
        return 0;
    }
    if( !p ) {
        return 0;
    }
    auto filter = [&it]( const item & e ) {
        // don't allow ups battery mods on a UPS or UPS-powered tools
        if( it->has_flag( "USE_UPS" ) &&
            ( e.typeId() == itype_UPS_off || e.typeId() == itype_adv_UPS_off ||
              e.has_flag( "USE_UPS" ) ) ) {
            return false;
        }
        // can only attach to unmodified tools that use compatible ammo
        return e.is_tool() && e.toolmods().empty() && !e.magazine_current() &&
               std::any_of( it->type->mod->acceptable_ammo.begin(),
        it->type->mod->acceptable_ammo.end(), [&]( const ammotype & at ) {
            return e.ammo_types( false ).count( at );
        } );
    };
    auto loc = g->inv_map_splice( filter, _( "Select tool to modify" ), 1,
                                  _( "You don't have compatible tools." ) );
    if( !loc ) {
        add_msg( m_info, _( "Never mind." ) );
        return 0;
    }
    if( loc->ammo_remaining() ) {
        if( !p->unload( loc ) ) {
            p->add_msg_if_player( m_info, _( "You cancel unloading the tool." ) );
            return 0;
        }
    }
    p->toolmod_add( std::move( loc ), item_location( *p, it ) );
    return 0;
}
References _, add_msg(), player::add_msg_if_player(), debugmsg, g, item::has_flag(), item::is_tool(), item::is_toolmod(), itype_adv_UPS_off, itype_UPS_off, m_info, item::magazine_current(), itype::mod, avatar_action::move(), player::toolmod_add(), item::toolmods(), item::type, item::typeId(), and player::unload().
Referenced by Item_factory::init().
tow_attach()
int iuse::tow_attach (player * p, item * it, bool , const tripoint &)
Definition at line 8689 of file iuse.cpp.
{
    std::string initial_state = it->get_var( "state", "attach_first" );
    if( !p ) {
        return 0;
    }
    const auto set_cable_active = []( player * p, item * it, const std::string & state ) {
        it->set_var( "state", state );
        it->active = true;
        it->process( p, p->pos(), false );
        p->moves -= 15;
    };
    if( initial_state == "attach_first" ) {
        const cata::optional<tripoint> posp_ = choose_adjacent(
                _( "Attach cable to the vehicle that will do the towing." ) );
        if( !posp_ ) {
            return 0;
        }
        const tripoint posp = *posp_;
        const optional_vpart_position vp = g->m.veh_at( posp );
        if( !vp ) {
            p->add_msg_if_player( _( "There's no vehicle there." ) );
            return 0;
        } else {
            vehicle *const source_veh = veh_pointer_or_null( vp );
            if( source_veh ) {
                if( source_veh->has_tow_attached() || source_veh->is_towed() ||
                    source_veh->is_towing() ) {
                    p->add_msg_if_player( _( "That vehicle already has a tow-line attached." ) );
                    return 0;
                }
                if( !source_veh->is_external_part( posp ) ) {
                    p->add_msg_if_player( _( "You can't attach the tow-line to an internal part." ) );
                    return 0;
                }
            }
            const tripoint &abspos = g->m.getabs( posp );
            it->set_var( "source_x", abspos.x );
            it->set_var( "source_y", abspos.y );
            it->set_var( "source_z", g->get_levz() );
            set_cable_active( p, it, "pay_out_cable" );
        }
    } else {
        const auto confirm_source_vehicle = []( player * p, item * it, const bool detach_if_missing ) {
            tripoint source_global( it->get_var( "source_x", 0 ),
                                    it->get_var( "source_y", 0 ),
                                    it->get_var( "source_z", 0 ) );
            tripoint source_local = g->m.getlocal( source_global );
            const optional_vpart_position source_vp = g->m.veh_at( source_local );
            vehicle *const source_veh = veh_pointer_or_null( source_vp );
            if( detach_if_missing && source_veh == nullptr ) {
                if( p->has_item( *it ) ) {
                    p->add_msg_if_player( m_bad, _( "You notice the cable has come loose!" ) );
                }
                it->reset_cable( p );
            }
            return source_vp;
        };
        const bool paying_out = initial_state == "pay_out_cable";
        uilist kmenu;
        kmenu.text = _( "Using cable:" );
        kmenu.addentry( 0, true, -1, _( "Detach and re-spool the cable" ) );
        kmenu.addentry( 1, paying_out, -1, _( "Attach loose end to vehicle" ) );
        kmenu.query();
        int choice = kmenu.ret;
        if( choice < 0 ) {
            return 0; // we did nothing.
        } else if( choice == 0 ) { // unconnect & respool
            it->reset_cable( p );
            return 0;
        }
        const optional_vpart_position source_vp = confirm_source_vehicle( p, it, paying_out );
        vehicle *const source_veh = veh_pointer_or_null( source_vp );
        if( source_veh == nullptr && paying_out ) {
            return 0;
        }
        const cata::optional<tripoint> vpos_ = choose_adjacent(
                _( "Attach cable to vehicle that will be towed." ) );
        if( !vpos_ ) {
            return 0;
        }
        const tripoint vpos = *vpos_;
        const optional_vpart_position target_vp = g->m.veh_at( vpos );
        if( !target_vp ) {
            p->add_msg_if_player( _( "There's no vehicle there." ) );
            return 0;
        } else {
            vehicle *const target_veh = &target_vp->vehicle();
            if( target_veh && ( target_veh->has_tow_attached() || target_veh->is_towed() ||
                                target_veh->is_towing() ) ) {
                p->add_msg_if_player( _( "That vehicle already has a tow-line attached." ) );
                return 0;
            }
            if( source_veh == target_veh ) {
                if( p->has_item( *it ) ) {
                    p->add_msg_if_player( m_warning, _( "You cannot set a vehicle to tow itself!" ) );
                }
                return 0;
            }
            if( !target_veh->is_external_part( vpos ) ) {
                p->add_msg_if_player( _( "You can't attach the tow-line to an internal part." ) );
                return 0;
            }
            const vpart_id vpid( it->typeId().str() );
            point vcoords = source_vp->mount();
            vehicle_part source_part( vpid, vcoords, item( *it ) );
            source_veh->install_part( vcoords, source_part );
            vcoords = target_vp->mount();
            vehicle_part target_part( vpid, vcoords, item( *it ) );
            target_veh->install_part( vcoords, target_part );
            if( p->has_item( *it ) ) {
                p->add_msg_if_player( m_good, _( "You link up the %1$s and the %2$s." ),
                                      source_veh->name, target_veh->name );
            }
            source_veh->tow_data.set_towing( source_veh, target_veh );
            return 1; // Let the cable be destroyed.
        }
    }
    return 0;
}
References _, item::active, player::add_msg_if_player(), uilist::addentry(), choose_adjacent(), g, item::get_var(), visitable< T >::has_item(), vehicle::has_tow_attached(), vehicle::install_part(), vehicle::is_external_part(), vehicle::is_towed(), vehicle::is_towing(), m_bad, m_good, m_warning, Creature::moves, vehicle::name, Character::pos(), item::process(), uilist::query(), uilist::ret, towing_data::set_towing(), item::set_var(), uilist::text, vehicle::tow_data, veh_pointer_or_null(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
towel()
int iuse::towel (player * p, item * it, bool t, const tripoint &)
Definition at line 5559 of file iuse.cpp.
{
    return towel_common( p, it, t );
}
References towel_common().
Referenced by Item_factory::init().
towel_common()
int iuse::towel_common (player * p, item * it, bool t)
Definition at line 5564 of file iuse.cpp.
{
    if( t ) {
        // Continuous usage, do nothing as not initiated by the player, this is for
        // wet towels only as they are active items.
        return 0;
    }
    bool slime = p->has_effect( effect_slimed );
    bool boom = p->has_effect( effect_boomered );
    bool glow = p->has_effect( effect_glowing );
    int mult = slime + boom + glow; // cleaning off more than one at once makes it take longer
    bool towelUsed = false;
    const std::string name = it ? it->tname() : _( "towel" );
    // can't use an already wet towel!
    if( it && it->has_flag( "WET" ) ) {
        p->add_msg_if_player( m_info, _( "That %s is too wet to soak up any more liquid!" ),
                              it->tname() );
        // clean off the messes first, more important
    } else if( slime || boom || glow ) {
        p->remove_effect( effect_slimed ); // able to clean off all at once
        p->remove_effect( effect_boomered );
        p->remove_effect( effect_glowing );
        p->add_msg_if_player( _( "You use the %s to clean yourself off, saturating it with slime!" ),
                              name );
        towelUsed = true;
        if( it && it->typeId() == itype_towel ) {
            it->convert( itype_towel_soiled );
        }
        // dry off from being wet
    } else if( p->has_morale( MORALE_WET ) ) {
        p->rem_morale( MORALE_WET );
        p->body_wetness.fill( 0 );
        p->add_msg_if_player( _( "You use the %s to dry off, saturating it with water!" ),
                              name );
        towelUsed = true;
        if( it ) {
            it->item_counter = to_turns<int>( 30_minutes );
        }
        // default message
    } else {
        p->add_msg_if_player( _( "You are already dry, the %s does nothing." ), name );
    }
    // towel was used
    if( towelUsed ) {
        if( mult == 0 ) {
            mult = 1;
        }
        p->moves -= 50 * mult;
        if( it ) {
            // change "towel" to a "towel_wet" (different flavor text/color)
            if( it->typeId() == itype_towel ) {
                it->convert( itype_towel_wet );
            }
            // WET, active items have their timer decremented every turn
            it->set_flag( "WET" );
            it->active = true;
        }
    }
    return it ? it->type->charges_to_use() : 0;
}
References _, item::active, player::add_msg_if_player(), Character::body_wetness, itype::charges_to_use(), item::convert(), effect_boomered, effect_glowing, effect_slimed, trapfunc::glow(), Creature::has_effect(), item::has_flag(), Character::has_morale(), item::item_counter, itype_towel, itype_towel_soiled, itype_towel_wet, m_info, MORALE_WET, Creature::moves, om_direction::name(), Character::rem_morale(), Creature::remove_effect(), item::set_flag(), item::tname(), item::type, and item::typeId().
Referenced by vehicle::interact_with(), and towel().
trimmer_off()
int iuse::trimmer_off (player * p, item * it, bool , const tripoint &)
Definition at line 3123 of file iuse.cpp.
{
    return toolweapon_off( *p, *it,
                           false,
                           rng( 0, 10 ) - it->damage_level( 4 ) > 3,
                           15, _( "With a roar, the hedge trimmer leaps to life!" ),
                           _( "You yank the cord, but nothing happens." ) );
}
References _, item::damage_level(), rng(), and toolweapon_off().
Referenced by Item_factory::init().
trimmer_on()
int iuse::trimmer_on (player * p, item * it, bool t, const tripoint &)
Definition at line 3219 of file iuse.cpp.
{
    return toolweapon_on( *p, *it, t, _( "hedge trimmer" ),
                          true,
                          15, 10, _( "Your hedge trimmer rumbles." ) );
}
References _, and toolweapon_on().
Referenced by Item_factory::init().
unfold_generic()
int iuse::unfold_generic (player * p, item * it, bool , const tripoint &)
Definition at line 5632 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    map &here = get_map();
    vehicle *veh = here.add_vehicle( vproto_id( "none" ), p->pos(), 0_degrees, 0, 0, false );
    if( veh == nullptr ) {
        p->add_msg_if_player( m_info, _( "There's no room to unfold the %s." ), it->tname() );
        return 0;
    }
    veh->name = it->get_var( "vehicle_name" );
    if( !veh->restore( it->get_var( "folding_bicycle_parts" ) ) ) {
        g->m.destroy_vehicle( veh );
        return 0;
    }
    const bool can_float = size( veh->get_avail_parts( "FLOATS" ) ) > 2;
    const auto invalid_pos = []( const tripoint & pp, bool can_float ) {
        return ( g->m.has_flag_ter( TFLAG_DEEP_WATER, pp ) && !can_float ) ||
               g->m.veh_at( pp ) || g->m.impassable( pp );
    };
    for( const vpart_reference &vp : veh->get_all_parts() ) {
        if( vp.info().location != "structure" ) {
            continue;
        }
        const tripoint pp = vp.pos();
        if( invalid_pos( pp, can_float ) ) {
            p->add_msg_if_player( m_info, _( "There's no room to unfold the %s." ), it->tname() );
            g->m.destroy_vehicle( veh );
            return 0;
        }
    }
    g->m.add_vehicle_to_cache( veh );
    std::string unfold_msg = it->get_var( "unfold_msg" );
    if( unfold_msg.empty() ) {
        unfold_msg = _( "You painstakingly unfold the %s and make it ready to ride." );
    } else {
        unfold_msg = _( unfold_msg );
    }
    veh->set_owner( *p );
    p->add_msg_if_player( m_neutral, unfold_msg, veh->name );
    p->moves -= it->get_var( "moves", to_turns<int>( 5_seconds ) );
    return 1;
}
References _, player::add_msg_if_player(), map::add_vehicle(), g, vehicle::get_all_parts(), vehicle::get_avail_parts(), get_map(), item::get_var(), Character::is_mounted(), Creature::is_underwater(), m_info, m_neutral, Creature::moves, vehicle::name, Character::pos(), vehicle::restore(), vehicle::set_owner(), om_direction::size, TFLAG_DEEP_WATER, and item::tname().
Referenced by Item_factory::init().
unpack_item()
int iuse::unpack_item (player * p, item * it, bool , const tripoint &)
Definition at line 2019 of file iuse.cpp.
{
    if( p->is_underwater() ) {
        p->add_msg_if_player( m_info, _( "You can't do that while underwater." ) );
        return 0;
    }
    std::string oname = it->typeId().str() + "_on";
    p->moves -= to_moves<int>( 10_seconds );
    p->add_msg_if_player( _( "You unpack your %s for use." ), it->tname() );
    it->convert( itype_id( oname ) ).active = false;
    return 0;
}
References _, item::active, player::add_msg_if_player(), item::convert(), Creature::is_underwater(), m_info, Creature::moves, string_id< T >::str(), item::tname(), and item::typeId().
Referenced by Item_factory::init().
vaccine()
int iuse::vaccine (player * p, item * it, bool , const tripoint &)
Definition at line 856 of file iuse.cpp.
{
    p->add_msg_if_player( _( "You inject the vaccine." ) );
    p->add_msg_if_player( m_good, _( "You feel tough." ) );
    p->mod_healthy_mod( 200, 200 );
    p->mod_pain( 3 );
    item syringe( "syringe", it->birthday() );
    p->i_add( syringe );
    return it->type->charges_to_use();
}
References _, player::add_msg_if_player(), item::birthday(), itype::charges_to_use(), Character::i_add(), m_good, Character::mod_healthy_mod(), player::mod_pain(), and item::type.
Referenced by Item_factory::init().
vibe()
int iuse::vibe (player * p, item * it, bool , const tripoint &)
Definition at line 4493 of file iuse.cpp.
{
    if( p->is_npc() ) {
        // Long action
        // Also, that would be creepy as fuck, seriously
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    if( ( p->is_underwater() ) && ( !( ( p->has_trait( trait_GILLS ) ) ||
                                       ( p->has_trait( trait_GILLS_CEPH ) ) ||
                                       ( p->is_wearing( itype_rebreather_on ) ) ||
                                       ( p->is_wearing( itype_rebreather_xl_on ) ) ||
                                       ( p->is_wearing( itype_mask_h20survivor_on ) ) ) ) ) {
        p->add_msg_if_player( m_info, _( "It's waterproof, but oxygen maybe?" ) );
        return 0;
    }
    if( !it->units_sufficient( *p ) ) {
        p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
        return 0;
    }
    if( p->get_fatigue() >= fatigue_levels::dead_tired ) {
        p->add_msg_if_player( m_info, _( "*Your* batteries are dead." ) );
        return 0;
    } else {
        int moves = to_moves<int>( 20_minutes );
        if( it->ammo_remaining() > 0 ) {
            p->add_msg_if_player( _( "You fire up your %s and start getting the tension out." ),
                                  it->tname() );
        } else {
            p->add_msg_if_player( _( "You whip out your %s and start getting the tension out." ),
                                  it->tname() );
        }
        p->assign_activity( ACT_VIBE, moves, -1, 0, "de-stressing" );
        p->activity.targets.push_back( item_location( *p, it ) );
    }
    return it->type->charges_to_use();
}
References _, ACT_VIBE, Character::activity, player::add_msg_if_player(), item::ammo_remaining(), Character::assign_activity(), itype::charges_to_use(), dead_tired, Character::get_fatigue(), Character::has_trait(), Character::is_mounted(), player::is_npc(), Creature::is_underwater(), Character::is_wearing(), itype_mask_h20survivor_on, itype_rebreather_on, itype_rebreather_xl_on, m_info, player_activity::targets, item::tname(), trait_GILLS, trait_GILLS_CEPH, item::type, and item::units_sufficient().
Referenced by Item_factory::init().
vortex()
int iuse::vortex (player * p, item * it, bool , const tripoint &)
Definition at line 4534 of file iuse.cpp.
{
    std::vector<point> spawn;
    for( int i = -3; i <= 3; i++ ) {
        spawn.emplace_back( -3, i );
        spawn.emplace_back( +3, i );
        spawn.emplace_back( i, -3 );
        spawn.emplace_back( i, +3 );
    }
    while( !spawn.empty() ) {
        const tripoint offset( random_entry_removed( spawn ), 0 );
        monster *const mon = g->place_critter_at( mon_vortex, offset + p->pos() );
        if( !mon ) {
            continue;
        }
        p->add_msg_if_player( m_warning, _( "Air swirls all over" ) );
        p->moves -= to_moves<int>( 1_seconds );
        it->convert( itype_spiral_stone );
        mon->friendly = -1;
        return it->type->charges_to_use();
    }
    // Only reachable when no monster has been spawned.
    p->add_msg_if_player( m_warning, _( "Air swirls around you for a moment." ) );
    return it->convert( itype_spiral_stone ).type->charges_to_use();
}
References _, player::add_msg_if_player(), itype::charges_to_use(), item::convert(), monster::friendly, g, itype_spiral_stone, m_warning, mon_vortex, Creature::moves, Character::pos(), random_entry_removed(), and item::type.
Referenced by Item_factory::init().
wash_all_items()
int iuse::wash_all_items (player * p, item * , bool , const tripoint &)
Definition at line 9431 of file iuse.cpp.
{
    if( !character_funcs::can_see_fine_details( *p ) ) {
        p->add_msg_if_player( _( "You can't see to do that!" ) );
        return 0;
    }
    // Check that player isn't over volume limit as this might cause it to break... this is a hack.
    // TODO: find a better solution.
    if( p->volume_capacity() < p->volume_carried() ) {
        p->add_msg_if_player( _( "You're carrying too much to clean anything." ) );
        return 0;
    }
    wash_items( p, true, true );
    return 0;
}
References _, player::add_msg_if_player(), character_funcs::can_see_fine_details(), Character::volume_capacity(), Character::volume_carried(), and wash_items().
Referenced by Item_factory::init().
wash_hard_items()
int iuse::wash_hard_items (player * p, item * , bool , const tripoint &)
Definition at line 9410 of file iuse.cpp.
{
    if( !character_funcs::can_see_fine_details( *p ) ) {
        p->add_msg_if_player( _( "You can't see to do that!" ) );
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    // Check that player isn't over volume limit as this might cause it to break... this is a hack.
    // TODO: find a better solution.
    if( p->volume_capacity() < p->volume_carried() ) {
        p->add_msg_if_player( _( "You're carrying too much to clean anything." ) );
        return 0;
    }
    wash_items( p, false, true );
    return 0;
}
References _, player::add_msg_if_player(), character_funcs::can_see_fine_details(), Character::is_mounted(), m_info, Character::volume_capacity(), Character::volume_carried(), and wash_items().
Referenced by Item_factory::init().
wash_soft_items()
int iuse::wash_soft_items (player * p, item * , bool , const tripoint &)
Definition at line 9389 of file iuse.cpp.
{
    if( !character_funcs::can_see_fine_details( *p ) ) {
        p->add_msg_if_player( _( "You can't see to do that!" ) );
        return 0;
    }
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    // Check that player isn't over volume limit as this might cause it to break... this is a hack.
    // TODO: find a better solution.
    if( p->volume_capacity() < p->volume_carried() ) {
        p->add_msg_if_player( _( "You're carrying too much to clean anything." ) );
        return 0;
    }
    wash_items( p, true, false );
    return 0;
}
References _, player::add_msg_if_player(), character_funcs::can_see_fine_details(), Character::is_mounted(), m_info, Character::volume_capacity(), Character::volume_carried(), and wash_items().
Referenced by Item_factory::init().
water_purifier()
int iuse::water_purifier (player * p, item * it, bool , const tripoint &)
Definition at line 2090 of file iuse.cpp.
{
    if( p->is_mounted() ) {
        p->add_msg_if_player( m_info, _( "You cannot do that while mounted." ) );
        return 0;
    }
    auto obj = g->inv_map_splice( []( const item & e ) {
        return !e.contents.empty() && e.contents.front().typeId() == itype_water;
    }, _( "Purify what?" ), 1, _( "You don't have water to purify." ) );
    if( !obj ) {
        p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
        return 0;
    }
    item &liquid = obj->contents.front();
    if( !it->units_sufficient( *p, liquid.charges ) ) {
        p->add_msg_if_player( m_info, _( "That volume of water is too large to purify." ) );
        return 0;
    }
    p->moves -= to_moves<int>( 2_seconds );
    liquid.convert( itype_water_clean ).poison = 0;
    return liquid.charges;
}
References _, player::add_msg_if_player(), item::charges, item::contents, item::convert(), item_contents::empty(), item_contents::front(), g, Character::is_mounted(), itype_water, itype_water_clean, m_info, Creature::moves, int_id< T >::obj(), item::poison, item::typeId(), and item::units_sufficient().
Referenced by Item_factory::init().
weak_antibiotic()
int iuse::weak_antibiotic (player * p, item * it, bool , const tripoint &)
Definition at line 9513 of file iuse.cpp.
{
    p->add_msg_player_or_npc( m_neutral,
                              _( "You take some weak antibiotics." ),
                              _( "<npcname> takes some weak antibiotics." ) );
    if( p->has_effect( effect_infected ) && !p->has_effect( effect_weak_antibiotic ) ) {
        p->add_msg_if_player( m_good, _( "The throbbing of the infection diminishes.  Slightly." ) );
    }
    p->add_effect( effect_weak_antibiotic, 12_hours );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), player::add_msg_player_or_npc(), itype::charges_to_use(), effect_infected, effect_weak_antibiotic, Creature::has_effect(), m_good, m_neutral, and item::type.
Referenced by Item_factory::init().
weather_tool()
int iuse::weather_tool (player * p, item * it, bool , const tripoint &)
Definition at line 9098 of file iuse.cpp.
{
    const weather_manager &weather = get_weather();
    const w_point &weatherPoint = get_weather().get_precise();
    /* Possibly used twice. Worth spending the time to precalculate. */
    const auto player_local_temp = weather.get_temperature( p->pos() );
    map &here = get_map();
    if( it->typeId() == itype_weather_reader ) {
        p->add_msg_if_player( m_neutral, _( "The %s's monitor slowly outputs the data" ),
                              it->tname() );
    }
    if( it->has_flag( "THERMOMETER" ) ) {
        if( it->typeId() == itype_thermometer ) {
            p->add_msg_if_player( m_neutral, _( "The %1$s reads %2$s." ), it->tname(),
                                  print_temperature( player_local_temp ) );
        } else {
            p->add_msg_if_player( m_neutral, _( "Temperature: %s." ),
                                  print_temperature( player_local_temp ) );
        }
        // TODO: Don't output air temp if we aren't near air
        if( g->m.has_flag( TFLAG_SWIMMABLE, p->pos() ) ) {
            const units::temperature water_temp = weather.get_cur_weather_gen().get_water_temperature(
                    tripoint_abs_ms( here.getabs( p->pos() ) ),
                    calendar::turn, calendar::config, g->get_seed() );
            p->add_msg_if_player( m_neutral, _( "Water temperature: %s." ),
                                  print_temperature( water_temp ) );
        }
    }
    if( it->has_flag( "HYGROMETER" ) ) {
        if( it->typeId() == itype_hygrometer ) {
            p->add_msg_if_player(
                m_neutral, _( "The %1$s reads %2$s." ), it->tname(),
                print_humidity( get_local_humidity( weatherPoint.humidity, get_weather().weather_id,
                                                    g->is_sheltered( p->pos() ) ) ) );
        } else {
            p->add_msg_if_player(
                m_neutral, _( "Relative Humidity: %s." ),
                print_humidity( get_local_humidity( weatherPoint.humidity, get_weather().weather_id,
                                                    g->is_sheltered( p->pos() ) ) ) );
        }
    }
    if( it->has_flag( "BAROMETER" ) ) {
        if( it->typeId() == itype_barometer ) {
            p->add_msg_if_player(
                m_neutral, _( "The %1$s reads %2$s." ), it->tname(),
                print_pressure( static_cast<int>( weatherPoint.pressure ) ) );
        } else {
            p->add_msg_if_player( m_neutral, _( "Pressure: %s." ),
                                  print_pressure( static_cast<int>( weatherPoint.pressure ) ) );
        }
    }
    if( it->typeId() == itype_weather_reader ) {
        int vehwindspeed = 0;
        if( optional_vpart_position vp = g->m.veh_at( p->pos() ) ) {
            vehwindspeed = std::abs( vp->vehicle().velocity / 100 ); // For mph
        }
        const oter_id &cur_om_ter = overmap_buffer.ter( p->global_omt_location() );
        /* windpower defined in internal velocity units (=.01 mph) */
        const double windpower = 100 * get_local_windpower( weather.windspeed + vehwindspeed, cur_om_ter,
                                 p->pos(), weather.winddirection, g->is_sheltered( p->pos() ) );
        p->add_msg_if_player( m_neutral, _( "Wind Speed: %.1f %s." ),
                              convert_velocity( windpower, VU_WIND ),
                              velocity_units( VU_WIND ) );
        p->add_msg_if_player(
            m_neutral, _( "Feels Like: %s." ),
            print_temperature(
                get_local_windchill( units::to_fahrenheit( weatherPoint.temperature ),
                                     weatherPoint.humidity,
                                     windpower / 100 ) +
                player_local_temp ) );
        std::string dirstring = get_dirstring( weather.winddirection );
        p->add_msg_if_player( m_neutral, _( "Wind Direction: From the %s." ), dirstring );
    }
    return 0;
}
References _, player::add_msg_if_player(), calendar::config, convert_velocity(), g, get_dirstring(), get_local_humidity(), get_local_windchill(), get_local_windpower(), get_map(), weather_manager::get_precise(), get_weather(), map::getabs(), Character::global_omt_location(), item::has_flag(), w_point::humidity, itype_barometer, itype_hygrometer, itype_thermometer, itype_weather_reader, m_neutral, overmap_buffer, Character::pos(), w_point::pressure, print_humidity(), print_pressure(), print_temperature(), w_point::temperature, overmapbuffer::ter(), TFLAG_SWIMMABLE, item::tname(), units::to_fahrenheit(), calendar::turn, item::typeId(), velocity_units(), and VU_WIND.
Referenced by Item_factory::init().
weed_cake()
int iuse::weed_cake (player * p, item * it, bool , const tripoint &)
Definition at line 795 of file iuse.cpp.
{
    p->add_msg_if_player(
        _( "You start scarfing down the delicious cake.  It tastes a little funny though" ) );
    time_duration duration = 12_minutes;
    if( p->has_trait( trait_TOLERANCE ) ) {
        duration = 9_minutes;
    }
    if( p->has_trait( trait_LIGHTWEIGHT ) ) {
        duration = 15_minutes;
    }
    p->mod_stored_kcal( -20 );
    p->mod_thirst( 6 );
    if( p->get_painkiller() < 5 ) {
        p->set_painkiller( ( p->get_painkiller() + 3 ) * 2 );
    }
    p->add_effect( effect_weed_high, duration );
    p->moves -= 100;
    if( one_in( 5 ) ) {
        weed_msg( *p );
    }
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_weed_high, Character::get_painkiller(), Character::has_trait(), Character::mod_stored_kcal(), Character::mod_thirst(), Creature::moves, one_in(), Character::set_painkiller(), trait_LIGHTWEIGHT, trait_TOLERANCE, item::type, and weed_msg().
Referenced by Item_factory::init().
xanax()
int iuse::xanax (player * p, item * it, bool , const tripoint &)
Definition at line 471 of file iuse.cpp.
{
    p->add_msg_if_player( _( "You take some %s." ), it->tname() );
    p->add_effect( effect_took_xanax, 90_minutes );
    return it->type->charges_to_use();
}
References _, Creature::add_effect(), player::add_msg_if_player(), itype::charges_to_use(), effect_took_xanax, item::tname(), and item::type.
Referenced by Item_factory::init().