Cataclysm BN: CellularAutomata Namespace Reference
CellularAutomata Namespace Reference
Functions
int neighbor_count (const std::vector< std::vector< int > > &cells, const point &size, const point &p)
Calculates the number of alive neighbors by looking at the Moore neighborhood (3x3 grid of cells).
std::vector< std::vector< int > > generate_cellular_automaton (const point &size, const int alive, const int iterations, const int birth_limit, const int stasis_limit)
Generate a cellular automaton using the provided parameters.
Function Documentation
generate_cellular_automaton()
std::vector< std::vector< int > > CellularAutomata::generate_cellular_automaton (const point & size, const int alive, const int iterations, const int birth_limit, const int stasis_limit) inline
Generate a cellular automaton using the provided parameters.
Basic rules are as follows:
alive% of cells start alive
Run for specified number of iterations
Dead cells with > birth_limit neighbors become alive
Alive cells with > statis_limit neighbors stay alive
The rest die
Parameters
size Dimensions of the grid.
alive Number between 0 and 100, used to roll an x_in_y check for the cell to start alive.
iterations Number of iterations to run the cellular automaton.
birth_limit Dead cells with > birth_limit neighbors become alive.
stasis_limit Alive cells with > statis_limit neighbors stay alive
Returns
The width x height grid of cells. Each cell is a 0 if dead or a 1 if alive.
Definition at line 57 of file cellular_automata.h.
{
    std::vector<std::vector<int>> current( size.x, std::vector<int>( size.y, 0 ) );
    std::vector<std::vector<int>> next( size.x, std::vector<int>( size.y, 0 ) );
    // Initialize our initial set of cells.
    for( int i = 0; i < size.x; i++ ) {
        for( int j = 0; j < size.y; j++ ) {
            current[i][j] = x_in_y( alive, 100 );
        }
    }
    for( int iteration = 0; iteration < iterations; iteration++ ) {
        for( int i = 0; i < size.x; i++ ) {
            for( int j = 0; j < size.y; j++ ) {
                // Skip the edges--no need to complicate this with more complex neighbor
                // calculations, just keep them constant.
                if( i == 0 || i == size.x - 1 || j == 0 || j == size.y - 1 ) {
                    next[i][j] = 0;
                    continue;
                }
                // Count our neighors.
                const int neighbors = neighbor_count( current, size, point( i, j ) );
                // Dead and > birth_limit neighbors, so become alive.
                if( ( current[i][j] == 0 ) && ( neighbors > birth_limit ) ) {
                    next[i][j] = 1;
                }
                // Alive and > statis_limit neighbors, so stay alive.
                else if( ( current[i][j] == 1 ) && ( neighbors > stasis_limit ) ) {
                    next[i][j] = 1;
                }
                // Else, die.
                else {
                    next[i][j] = 0;
                }
            }
        }
        // Swap our current and next vectors and repeat.
        std::swap( current, next );
    }
    return current;
}
References neighbor_count(), om_direction::size, cata::swap(), and x_in_y().
Referenced by MapExtras::mx_clay_deposit(), MapExtras::mx_point_burned_ground(), MapExtras::mx_point_dead_vegetation(), and MapExtras::mx_pond().
neighbor_count()
int CellularAutomata::neighbor_count (const std::vector< std::vector< int > > & cells, const point & size, const point & p) inline
Calculates the number of alive neighbors by looking at the Moore neighborhood (3x3 grid of cells).
Parameters
cells The cells to look at. Assumed to be of a consistent width/height equal to the specified values.
size The width+height of the cells. Specified up front to avoid checked it each time.
p
Returns
The number of neighbors that are alive, a value between 0 and 8.
Definition at line 20 of file cellular_automata.h.
{
    int neighbors = 0;
    for( int ni = -1; ni <= 1; ni++ ) {
        for( int nj = -1; nj <= 1; nj++ ) {
            const point n( p + point( ni, nj ) );
            // These neighbors are outside the bounds, so they can't contribute.
            if( n.x < 0 || n.x >= size.x || n.y < 0 || n.y >= size.y ) {
                continue;
            }
            neighbors += cells[n.x][n.y];
        }
    }
    // Because we included ourself in the loop above, subtract ourselves back out.
    neighbors -= cells[p.x][p.y];
    return neighbors;
}
References om_direction::size, point::x, and point::y.
Referenced by generate_cellular_automaton(), and MapExtras::mx_pond().