Cataclysm BN: ammo_effects Namespace Reference
ammo_effects Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize_all ()
void check_consistency ()
void reset ()
const std::vector< ammo_effect > & get_all ()
Function Documentation
check_consistency()
void ammo_effects::check_consistency ()
Definition at line 160 of file ammo_effect.cpp.
{
    all_ammo_effects.check();
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by DynamicDataLoader::check_consistency().
finalize_all()
void ammo_effects::finalize_all ()
Definition at line 152 of file ammo_effect.cpp.
{
    all_ammo_effects.finalize();
    for( const ammo_effect &ae : all_ammo_effects.get_all() ) {
        const_cast<ammo_effect &>( ae ).finalize();
    }
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects, and behavior::finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< ammo_effect > & ammo_effects::get_all ()
Definition at line 170 of file ammo_effect.cpp.
{
    return all_ammo_effects.get_all();
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by auto_notes::auto_note_manager_gui::auto_note_manager_gui(), auto_notes::auto_note_settings::default_initialize(), ammo_effect::finalize(), clothing_mods::get_all_with(), materials::get_compactable(), materials::get_rotting(), and mapgen_factory::get_usages().
load()
void ammo_effects::load (const JsonObject & jo, const std::string & src)
Definition at line 147 of file ammo_effect.cpp.
{
    all_ammo_effects.load( jo, src );
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by vehicle::consume_fuel(), DynamicDataLoader::initialize(), io::JsonObjectOutputArchive::io(), io::JsonObjectInputArchive::io(), vehicle::noise_and_smoke(), and vehicle::thrust().
reset()
void ammo_effects::reset ()
Definition at line 165 of file ammo_effect.cpp.
{
    all_ammo_effects.reset();
}
References anonymous_namespace{ammo_effect.cpp}::all_ammo_effects.
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::atm_menu(), cata::poly_serialized< T >::deserialize(), cata::value_ptr< T >::deserialize(), cata::list< element_type, element_allocator_type >::emplace(), cata::list< element_type, element_allocator_type >::insert(), cata::list< element_type, element_allocator_type >::reserve(), cata::list< element_type, element_allocator_type >::shrink_to_fit(), and DynamicDataLoader::unload_data().