Cataclysm BN: anonymous_namespace{diary_ui.cpp} Namespace Reference
anonymous_namespace{diary_ui.cpp} Namespace Reference
Functions
void print_list_scrollable (catacurses::window *win, std::vector< std::string > list, int *selection, int entries_per_page, int xoffset, int width, bool active, bool border, const report_color_error color_error)
print a scrollable list, printed std::vector<std::string> as list with scrollbar
void print_list_scrollable (catacurses::window *win, std::vector< std::string > list, int *selection, bool active, bool border, const report_color_error color_error)
void print_list_scrollable (catacurses::window *win, std::string text, int *selection, int entries_per_page, int xoffset, int width, bool active, bool border, const report_color_error color_error)
void print_list_scrollable (catacurses::window *win, std::string text, int *selection, bool active, bool border, const report_color_error color_error)
void draw_diary_border (catacurses::window *win, const nc_color &color=c_white)
Variables
const int MAX_DAIRY_UI_WIDTH = 150
Function Documentation
draw_diary_border()
void anonymous_namespace{diary_ui.cpp}::draw_diary_border (catacurses::window * win, const nc_color & color = c_white)
Definition at line 97 of file diary_ui.cpp.
{
    wattron( *win, color );
    const point max( getmaxx( *win ) - 1, getmaxy( *win ) - 1 );
    const int midx = max.x / 2;
    for( int i = 4; i <= max.y - 4; i++ ) {
        mvwprintw( *win, point( 0, i ), "||||" );
        mvwprintw( *win, point( max.x - 3, i ), "||||" );
        mvwprintw( *win, point( midx, i ), " | " );
    }
    for( int i = 4; i <= max.x - 4; i++ ) {
        if( !( i >= midx && i <= midx + 2 ) ) {
            mvwprintw( *win, point( i, 0 ), "____" );
            mvwprintw( *win, point( i, max.y - 2 ), "____" );
            mvwprintw( *win, point( i, max.y - 1 ), "====" );
            mvwprintw( *win, point( i, max.y ), "----" );
        }
    }
    // top left corner
    mvwprintw( *win, point_zero, "    " );
    mvwprintw( *win, point_south, ".-/|" );
    mvwprintw( *win, point( 0, 2 ), "||||" );
    mvwprintw( *win, point( 0, 3 ), "||||" );
    // bottom left corner
    mvwprintw( *win, point( 0, max.y - 3 ), "||||" );
    mvwprintw( *win, point( 0, max.y - 2 ), "||||" );
    mvwprintw( *win, point( 0, max.y - 1 ), "||/=" );
    mvwprintw( *win, point( 0, max.y - 0 ), "`'--" );
    // top right corner
    mvwprintw( *win, point( max.x - 3, 0 ), "    " );
    mvwprintw( *win, point( max.x - 3, 1 ), "|\\-." );
    mvwprintw( *win, point( max.x - 3, 2 ), "||||" );
    mvwprintw( *win, point( max.x - 3, 3 ), "||||" );
    // bottom right corner
    mvwprintw( *win, max + point( -3, -3 ), "||||" );
    mvwprintw( *win, max + point( -3, -2 ), "||||" );
    mvwprintw( *win, max + point( -3, -1 ), "=\\||" );
    mvwprintw( *win, max + point( -3, 0 ), "--''" );
    // mid top
    mvwprintw( *win, point( midx, 0 ), "   " );
    mvwprintw( *win, point( midx, 1 ), "\\ /" );
    mvwprintw( *win, point( midx, 2 ), " | " );
    mvwprintw( *win, point( midx, 3 ), " | " );
    // mid bottom
    mvwprintw( *win, point( midx, max.y - 3 ), " | " );
    mvwprintw( *win, point( midx, max.y - 2 ), " | " );
    mvwprintw( *win, point( midx, max.y - 1 ), "\\|/" );
    mvwprintw( *win, point( midx, max.y - 0 ), "___" );
    wattroff( *win, color );
}
References color(), catacurses::getmaxx(), catacurses::getmaxy(), catacurses::mvwprintw(), point_south, point_zero, catacurses::wattroff(), catacurses::wattron(), point::x, and point::y.
Referenced by diary::show_diary_ui().
print_list_scrollable() [1/4]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, std::string text, int * selection, bool active, bool border, const report_color_error color_error)
Definition at line 90 of file diary_ui.cpp.
{
    print_list_scrollable( win, text, selection, getmaxy( *win ), 0, getmaxx( *win ), active, border,
                           color_error );
}
References active, catacurses::getmaxx(), catacurses::getmaxy(), and print_list_scrollable().
Referenced by print_list_scrollable(), and diary::show_diary_ui().
print_list_scrollable() [2/4]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, std::string text, int * selection, int entries_per_page, int xoffset, int width, bool active, bool border, const report_color_error color_error)
Definition at line 79 of file diary_ui.cpp.
{
    int border_space = border ? 1 : 0;
    // -1 on the left for scroll bar and another -1 on the right reserved for cursor
    std::vector<std::string> list = foldstring( text, width - 2 - border_space * 2 );
    print_list_scrollable( win, list, selection, entries_per_page, xoffset, width, active, border,
                           color_error );
}
References active, foldstring(), and print_list_scrollable().
print_list_scrollable() [3/4]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, std::vector< std::string > list, int * selection, bool active, bool border, const report_color_error color_error)
Definition at line 72 of file diary_ui.cpp.
{
    print_list_scrollable( win, list, selection, getmaxy( *win ), 0, getmaxx( *win ), active, border,
                           color_error );
}
References active, catacurses::getmaxx(), catacurses::getmaxy(), and print_list_scrollable().
print_list_scrollable() [4/4]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, std::vector< std::string > list, int * selection, int entries_per_page, int xoffset, int width, bool active, bool border, const report_color_error color_error)
print a scrollable list, printed std::vector<std::string> as list with scrollbar
Definition at line 30 of file diary_ui.cpp.
{
    if( *selection < 0 && !list.empty() ) {
        *selection = static_cast<int>( list.size() ) - 1;
    } else if( *selection >= static_cast<int>( list.size() ) ) {
        *selection = 0;
    }
    const int borderspace = border ? 1 : 0;
    entries_per_page = entries_per_page - borderspace * 2;
    const int top_of_page = entries_per_page * ( *selection / entries_per_page );
    const int bottom_of_page = std::min<int>( top_of_page + entries_per_page, list.size() );
    const int line_width = width - 1 - borderspace;
    for( int i = top_of_page; i < bottom_of_page; i++ ) {
        const nc_color col = c_white;
        const int y = i - top_of_page;
        const bool highlight = *selection == i && active;
        const nc_color line_color = highlight ? hilite( col ) : col;
        std::string line_str = list[i];
        if( highlight ) {
            line_str = left_justify( remove_color_tags( line_str ), line_width );
        }
        trim_and_print( *win, point( xoffset + 1, y + borderspace ), line_width,
                        line_color, line_str, color_error );
    }
    if( border ) {
        draw_border( *win );
    }
    if( active && entries_per_page < static_cast<int>( list.size() ) ) {
        draw_scrollbar( *win, *selection, entries_per_page, list.size(), point( xoffset,
                        0 + borderspace ) );
    }
}
References active, c_white, draw_border(), draw_scrollbar(), hilite(), left_justify(), remove_color_tags(), and trim_and_print().
Variable Documentation
MAX_DAIRY_UI_WIDTH
const int anonymous_namespace{diary_ui.cpp}::MAX_DAIRY_UI_WIDTH = 150
Definition at line 27 of file diary_ui.cpp.
Referenced by diary::show_diary_ui(), and uis_padding().