Cataclysm BN: monfactions Namespace Reference
monfactions Namespace Reference
Functions
void reset ()
void finalize ()
void load_monster_faction (const JsonObject &jo)
mfaction_id get_or_add_faction (const mfaction_str_id &id)
Function Documentation
finalize()
void monfactions::finalize ()
Definition at line 130 of file monfaction.cpp.
{
    if( faction_list.empty() ) {
        debugmsg( "No monster factions found." );
        return;
    }
    // Create a tree of faction dependence
    std::multimap< mfaction_id, mfaction_id > child_map;
    std::set< mfaction_id > unloaded; // To check if cycles exist
    std::queue< mfaction_id > queue;
    for( auto &faction : faction_list ) {
        unloaded.insert( faction.loadid );
        if( faction.loadid == faction.base_faction ) {
            // No parent = root of the (a?) tree
            queue.push( faction.loadid );
            continue;
        }
        // Point parent to children
        if( faction.base_faction.to_i() >= 0 ) {
            child_map.insert( std::make_pair( faction.base_faction, faction.loadid ) );
        }
        // Set faction as friendly to itself if not explicitly set to anything
        if( faction.attitude_map.count( faction.loadid ) == 0 ) {
            faction.attitude_map[faction.loadid] = MFA_FRIENDLY;
        }
    }
    if( queue.empty() && !faction_list.empty() ) {
        debugmsg( "No valid root monster faction!" );
        return;
    }
    // Set uninitialized factions to be children of the root.
    // If more than one root exists, use the first one.
    const auto root = queue.front();
    for( auto &faction : faction_list ) {
        if( faction.base_faction.to_i() < 0 ) {
            faction.base_faction = root;
            // If it is the (new) root, connecting it to own parent (self) would create a cycle.
            // So only try to connect it to the parent if it isn't own parent.
            if( faction.base_faction != faction.loadid ) {
                child_map.insert( std::make_pair( faction.base_faction, faction.loadid ) );
            }
        }
    }
    // Traverse the tree (breadth-first), starting from root
    while( !queue.empty() ) {
        mfaction_id cur = queue.front();
        queue.pop();
        if( unloaded.count( cur ) != 0 ) {
            unloaded.erase( cur );
        } else {
            debugmsg( "Tried to load monster faction %s more than once", cur.obj().id.c_str() );
            continue;
        }
        auto children = child_map.equal_range( cur );
        for( auto &it = children.first; it != children.second; ++it ) {
            // Copy attributes to child
            apply_base_faction( cur, it->second );
            queue.push( it->second );
        }
    }
    // Bad json
    if( !unloaded.empty() ) {
        std::string names;
        for( auto &fac : unloaded ) {
            names.append( fac.id().str() );
            names.append( " " );
            auto &the_faction = faction_list[fac.to_i()];
            the_faction.base_faction = root;
        }
        debugmsg( "Cycle encountered when processing monster factions.  Bad factions:\n %s",
                  names.c_str() );
    }
    faction_list.shrink_to_fit(); // Save a couple of bytes
}
References apply_base_faction(), string_id< T >::c_str(), debugmsg, faction_list, monfaction::id, MFA_FRIENDLY, Name::names, and int_id< T >::obj().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_or_add_faction()
mfaction_id monfactions::get_or_add_faction (const mfaction_str_id & id)
Definition at line 76 of file monfaction.cpp.
{
    auto found = faction_map.find( id );
    if( found == faction_map.end() ) {
        monfaction mfact;
        mfact.id = id;
        mfact.loadid = mfaction_id( faction_map.size() );
        // -1 base faction marks this faction as not initialized.
        // If it is not changed before validation, it will become a child of
        // the root of the faction tree.
        mfact.base_faction = mfaction_id( -1 );
        faction_map[mfact.id] = mfact.loadid;
        faction_list.push_back( mfact );
        found = faction_map.find( mfact.id );
    }
    return found->second;
}
References monfaction::base_faction, faction_list, faction_map, int_id< T >::id(), monfaction::id, and monfaction::loadid.
Referenced by mtype::load(), load_monster_faction(), and prealloc().
load_monster_faction()
void monfactions::load_monster_faction (const JsonObject & jo)
Definition at line 232 of file monfaction.cpp.
{
    // Factions inherit values from their parent factions - this is set during finalization
    std::set< std::string > by_mood = jo.get_tags( "by_mood" );
    std::set< std::string > neutral = jo.get_tags( "neutral" );
    std::set< std::string > friendly = jo.get_tags( "friendly" );
    std::set< std::string > hate = jo.get_tags( "hate" );
    // Need to make sure adding new factions won't invalidate our current faction's reference
    // That +1 is for base faction
    faction_list.reserve( faction_list.size() + by_mood.size() + neutral.size() + friendly.size() +
                          hate.size() + 1 );
    prealloc( by_mood );
    prealloc( neutral );
    prealloc( friendly );
    prealloc( hate );
    std::string name = jo.get_string( "name" );
    mfaction_id cur_id = get_or_add_faction( mfaction_str_id( name ) );
    std::string base_faction = jo.get_string( "base_faction", "" );
    mfaction_id base_id = get_or_add_faction( mfaction_str_id( base_faction ) );
    // Don't get the reference until here (to avoid vector reallocation messing it up)
    monfaction &faction = faction_list[cur_id.to_i()];
    faction.base_faction = base_id;
    add_to_attitude_map( by_mood, faction.attitude_map, MFA_BY_MOOD );
    add_to_attitude_map( neutral, faction.attitude_map, MFA_NEUTRAL );
    add_to_attitude_map( friendly, faction.attitude_map, MFA_FRIENDLY );
    add_to_attitude_map( hate, faction.attitude_map, MFA_HATE );
}
References add_to_attitude_map(), faction_list, friendly, get_or_add_faction(), JsonObject::get_string(), JsonObject::get_tags(), MFA_BY_MOOD, MFA_FRIENDLY, MFA_HATE, MFA_NEUTRAL, om_direction::name(), neutral, prealloc(), and int_id< T >::to_i().
Referenced by DynamicDataLoader::initialize().
reset()
void monfactions::reset ()
Definition at line 124 of file monfaction.cpp.
{
    faction_list.clear();
    faction_map.clear();
}
References faction_list, and faction_map.
Referenced by DynamicDataLoader::unload_data().