Cataclysm BN: warmth Namespace Reference
warmth Namespace Reference
Functions
std::map< bodypart_id, int > wind_resistance_from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
Returns wind resistance provided by armor, etc.
template<typename Acc = int const&(int const &, int const &)>
static std::map< bodypart_id, int > acc_clothing_warmth (const std::map< bodypart_id, std::vector< const item * > > &clothing_map, Acc accumulation_function)
std::map< bodypart_id, int > from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
std::map< bodypart_id, int > bonus_from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
std::map< bodypart_id, int > from_effects (const Character &c)
Function Documentation
acc_clothing_warmth()
template<typename Acc = int const&(int const &, int const &)> static std::map< bodypart_id, int > warmth::acc_clothing_warmth (const std::map< bodypart_id, std::vector< const item * > > & clothing_map, Acc accumulation_function) static
Definition at line 9358 of file character.cpp.
{
    std::map<bodypart_id, int> ret;
    for( const std::pair<const bodypart_id, std::vector<const item *>> &pr : clothing_map ) {
        ret[pr.first] = std::accumulate( pr.second.begin(), pr.second.end(), 0,
        [accumulation_function]( int acc, const item * it ) {
            return accumulation_function( acc, it->get_warmth() );
        } );
    }
    return ret;
}
References cata::hash64_detail::ret.
Referenced by bonus_from_clothing(), and from_clothing().
bonus_from_clothing()
std::map< bodypart_id, int > warmth::bonus_from_clothing (const std::map< bodypart_id, std::vector< const item * > > & clothing_map)
Definition at line 9379 of file character.cpp.
{
    return acc_clothing_warmth( clothing_map, std::max<int> );
}
References acc_clothing_warmth().
Referenced by Character::update_bodytemp().
from_clothing()
std::map< bodypart_id, int > warmth::from_clothing (const std::map< bodypart_id, std::vector< const item * > > & clothing_map)
Definition at line 9373 of file character.cpp.
{
    return acc_clothing_warmth( clothing_map, std::plus<int>() );
}
References acc_clothing_warmth().
Referenced by Character::update_bodytemp().
from_effects()
std::map< bodypart_id, int > warmth::from_effects (const Character & c)
Definition at line 9385 of file character.cpp.
{
    std::map<bodypart_id, int> ret;
    for( const effect *e : c.get_all_effects_of_type( effect_heating_bionic ) ) {
        ret[e->get_bp()] += e->get_intensity();
    }
    return ret;
}
References c, effect_heating_bionic, and cata::hash64_detail::ret.
Referenced by Character::update_bodytemp().
wind_resistance_from_clothing()
std::map< bodypart_id, int > warmth::wind_resistance_from_clothing (const std::map< bodypart_id, std::vector< const item * > > & clothing_map)
Returns wind resistance provided by armor, etc.
Definition at line 3872 of file character.cpp.
{
    std::map<bodypart_id, int> ret;
    for( const std::pair<const bodypart_id, std::vector<const item *>> &on_bp : clothing_map ) {
        ret[on_bp.first] = wind_resistance_from_item_list( on_bp.second );
    }
    return ret;
}
References cata::hash64_detail::ret, and wind_resistance_from_item_list().
Referenced by Character::update_bodytemp().