Cataclysm BN: detail Namespace Reference
detail Namespace Reference
Namespaces
namespace digits
namespace dragonbox
Classes
struct accumulator
class arg_converter
struct arg_data
struct arg_data< T, Char, NUM_ARGS, 0 >
class arg_formatter
The default argument formatter.
class arg_formatter_base
struct arg_mapper
struct arg_ref
struct auto_id
struct basic_data
struct big_decimal_fp
class bigint
struct bits
struct boundaries
class buffer
\rst A contiguous memory buffer with an optional growing ability.
class buffer_appender
struct buffer_traits
class char_converter
class char_specs_checker
struct char_t_impl
struct char_t_impl< S, enable_if_t< is_string< S >::value > >
class compile_parse_context
struct converter
class counting_buffer
class counting_iterator
class cstring_type_checker
class custom_formatter
struct custom_value
struct data
class DebugLogGuard
Debug log guard.
struct default_arg_formatter
struct divtest_table_entry
class dynamic_arg_list
struct dynamic_format_specs
class dynamic_specs_handler
struct error_handler
struct fallback_formatter
struct fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >
struct fallback_uintptr
struct fill_t
class fixed_buffer_traits
struct fixed_handler
struct float_specs
struct format_decimal_result
struct format_handler
class format_string_checker
class formatbuf
class fp
struct get_cstring
struct id_adapter
struct int128_t
struct int_checker
struct int_checker< true >
class int_type_checker
struct int_writer
struct is_back_insert_iterator
struct is_back_insert_iterator< std::back_insert_iterator< Container > >
struct is_contiguous_back_insert_iterator
struct is_contiguous_back_insert_iterator< buffer_appender< Char > >
struct is_contiguous_back_insert_iterator< std::back_insert_iterator< Container > >
struct is_integral
struct is_integral< int128_t >
struct is_integral< uint128_t >
struct is_named_arg
struct is_named_arg< named_arg< Char, T > >
class is_optional_helper
class is_optional_helper< cata::optional< T > >
struct is_output_iterator
struct is_output_iterator< It, T, void_t< typename std::iterator_traits< It >::iterator_category, decltype(*std::declval< It >()=std::declval< T >()) > >
struct is_reference_wrapper
struct is_reference_wrapper< std::reference_wrapper< T > >
class is_streamable
struct is_string
class is_zero_int
class iterator_buffer
class iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >
class iterator_buffer< T *, T >
class local_translation_cache
class local_translation_cache< const char * >
class local_translation_cache< std::string >
class locale_ref
struct make_unsigned_or_bool
struct make_unsigned_or_bool< bool >
struct mutations_ui_result
struct named_arg
struct named_arg_info
struct named_arg_value
struct null
class numeric_specs_checker
struct precision_adapter
class precision_checker
class printf_precision_handler
class printf_width_handler
class specs_checker
class specs_handler
class specs_setter
struct std_string_view
struct string_value
struct stringifier
struct test_stream
class truncating_iterator
class truncating_iterator< OutputIt, std::false_type >
class truncating_iterator< OutputIt, std::true_type >
class truncating_iterator_base
struct type_constant
struct uint128_t
struct uint128_wrapper
struct unformattable
class utf8_to_utf16
class value
struct view
struct void_t_impl
struct width_adapter
class width_checker
struct write_int_data
Typedefs
template<typename T , typename Context >
using has_fallback_formatter = std::is_constructible< fallback_formatter< T, typename Context::char_type > >
using long_type = conditional_t< long_short, int, long long >
using ulong_type = conditional_t< long_short, unsigned, unsigned long long >
template<typename T , typename Context >
using mapped_type_constant = type_constant< decltype(arg_mapper< Context >().map(std::declval< const T & >())), typename Context::char_type >
template<typename... Ts>
using void_t = typename detail::void_t_impl< Ts... >::type
using uintptr_t = fallback_uintptr
template<typename T >
using iterator_t = decltype(std::begin(std::declval< T & >()))
template<typename T >
using sentinel_t = decltype(std::end(std::declval< T & >()))
template<typename T >
using checked_ptr = T *
template<typename InputIt , typename OutChar >
using needs_conversion = bool_constant< std::is_same< typename std::iterator_traits< InputIt >::value_type, char >::value &&std::is_same< OutChar, char8_type >::value >
template<typename T >
using is_fast_float = bool_constant< std::numeric_limits< T >::is_iec559 &&sizeof(T)<=sizeof(double) >
template<typename T >
using is_signed = std::integral_constant< bool, std::numeric_limits< T >::is_signed||std::is_same< T, int128_t >::value >
template<typename T >
using uint32_or_64_or_128_t = conditional_t< num_bits< T >()<=32 &&!FMT_REDUCE_INT_INSTANTIATIONS, uint32_t, conditional_t< num_bits< T >()<=64, uint64_t, uint128_t > >
template<typename T >
using is_integer = bool_constant< is_integral< T >::value &&!std::is_same< T, bool >::value &&!std::is_same< T, char >::value &&!std::is_same< T, wchar_t >::value >
using format_func = void(*)(detail::buffer< char > &, int, string_view)
Enumerations
enum char8_type : unsigned char
enum class type {
none_type , int_type , uint_type , long_long_type ,
ulong_long_type , int128_type , uint128_type , bool_type ,
char_type , last_integer_type = char_type , float_type , double_type ,
long_double_type , last_numeric_type = long_double_type , cstring_type , string_type ,
pointer_type , custom_type
}
enum { long_short = sizeof(long) == sizeof(int) }
enum { packed_arg_bits = 4 }
enum { max_packed_args = 62 / packed_arg_bits }
enum : unsigned long long { is_unpacked_bit = 1ULL << 63 }
enum : unsigned long long { has_named_args_bit = 1ULL << 62 }
enum class round_direction { unknown , up , down }
enum class float_format : unsigned char { general , exp , fixed , hex }
enum class arg_id_kind { none , index , name }
enum class mutations_ui_cmd { exit , activate , deactivate }
Functions
DebugLogGuard realDebugLog (DL lev, DC cl, const char *filename, const char *line, const char *funcname)
template<typename T >
constexpr T const_check (T value)
FMT_NORETURN FMT_API void assert_fail (const char *file, int line, const char *message)
template<typename Int >
FMT_CONSTEXPR std::make_unsigned< Int >::type to_unsigned (Int value)
FMT_SUPPRESS_MSC_WARNING (4566) const expr unsigned char micro[]
template<typename Char >
constexpr bool is_unicode ()
void to_string_view (...)
template<typename... , typename S , FMT_ENABLE_IF(!is_compile_string< S >::value) >
FMT_INLINE void check_format_string (const S &)
template<typename... , typename S , FMT_ENABLE_IF(is_compile_string< S >::value) >
void check_format_string (S)
template<typename Container >
Container & get_container (std::back_insert_iterator< Container > it)
template<typename T , typename OutputIt >
iterator_buffer< OutputIt, T > get_buffer (OutputIt)
template<typename T >
buffer< T > & get_buffer (buffer_appender< T >)
template<typename OutputIt >
OutputIt get_buffer_init (OutputIt out)
template<typename T >
buffer< T > & get_buffer_init (buffer_appender< T > out)
template<typename Buffer >
auto get_iterator (Buffer &buf) -> decltype(buf.out())
template<typename T >
buffer_appender< T > get_iterator (buffer< T > &buf)
template<typename Char >
void init_named_args (named_arg_info< Char > *, int, int)
template<typename Char , typename T , typename... Tail>
void init_named_args (named_arg_info< Char > *named_args, int arg_count, int named_arg_count, const T &, const Tail &... args)
template<typename Char , typename T , typename... Tail>
void init_named_args (named_arg_info< Char > *named_args, int arg_count, int named_arg_count, const named_arg< Char, T > &arg, const Tail &... args)
template<typename... Args>
FMT_INLINE void init_named_args (std::nullptr_t, int, int, const Args &...)
template<bool B = false>
constexpr size_t count ()
template<bool B1, bool B2, bool... Tail>
constexpr size_t count ()
template<typename... Args>
constexpr size_t count_named_args ()
FMT_TYPE_CONSTANT (int, int_type)
FMT_TYPE_CONSTANT (unsigned, uint_type)
FMT_TYPE_CONSTANT (long long, long_long_type)
FMT_TYPE_CONSTANT (unsigned long long, ulong_long_type)
FMT_TYPE_CONSTANT (int128_t, int128_type)
FMT_TYPE_CONSTANT (uint128_t, uint128_type)
FMT_TYPE_CONSTANT (bool, bool_type)
FMT_TYPE_CONSTANT (Char, char_type)
FMT_TYPE_CONSTANT (float, float_type)
FMT_TYPE_CONSTANT (double, double_type)
FMT_TYPE_CONSTANT (long double, long_double_type)
FMT_TYPE_CONSTANT (const Char *, cstring_type)
FMT_TYPE_CONSTANT (basic_string_view< Char >, string_type)
FMT_TYPE_CONSTANT (const void *, pointer_type)
constexpr bool is_integral_type (type t)
constexpr bool is_arithmetic_type (type t)
template<typename Context , typename T >
FMT_CONSTEXPR basic_format_arg< Context > make_arg (const T &value)
template<typename >
constexpr unsigned long long encode_types ()
template<typename Context , typename Arg , typename... Args>
constexpr unsigned long long encode_types ()
template<typename T >
int check (unformattable)
template<typename T , typename U >
const U & check (const U &val)
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(IS_PACKED) >
value< Context > make_arg (const T &val)
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(!IS_PACKED) >
basic_format_arg< Context > make_arg (const T &value)
template<typename T >
const T & unwrap (const T &v)
template<typename T >
const T & unwrap (const std::reference_wrapper< T > &v)
template<typename Char , FMT_ENABLE_IF(!std::is_same< Char, char >::value) >
std::basic_string< Char > vformat (basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char > > > args)
FMT_API std::string vformat (string_view format_str, format_args args)
template<typename Char >
void vformat_to (buffer< Char > &buf, basic_string_view< Char > format_str, basic_format_args< FMT_BUFFER_CONTEXT(type_identity_t< Char >)> args, detail::locale_ref loc={})
template<typename Char , typename Args , FMT_ENABLE_IF(!std::is_same< Char, char >::value) >
void vprint_mojibake (std::FILE *, basic_string_view< Char >, const Args &)
FMT_API void vprint_mojibake (std::FILE *, string_view, format_args)
int safe_strerror (int error_code, char *&buffer, size_t buffer_size) FMT_NOEXCEPT
FMT_FUNC void format_error_code (detail::buffer< char > &out, int error_code, string_view message) FMT_NOEXCEPT
FMT_FUNC void report_error (format_func func, int error_code, string_view message) FMT_NOEXCEPT
void fwrite_fully (const void *ptr, size_t size, size_t count, FILE *stream)
template<typename Char >
FMT_FUNC std::string grouping_impl (locale_ref loc)
template<typename Char >
FMT_FUNC Char thousands_sep_impl (locale_ref loc)
template<typename Char >
FMT_FUNC Char decimal_point_impl (locale_ref loc)
template<>
FMT_FUNC int count_digits< 4 > (detail::fallback_uintptr n)
template<int SHIFT = 0>
fp normalize (fp value)
bool operator== (fp x, fp y)
uint64_t multiply (uint64_t lhs, uint64_t rhs)
fp operator* (fp x, fp y)
fp get_cached_power (int min_exponent, int &pow10_exponent)
round_direction get_round_direction (uint64_t divisor, uint64_t remainder, uint64_t error)
template<typename Handler >
FMT_ALWAYS_INLINE digits::result grisu_gen_digits (fp value, uint64_t error, int &exp, Handler &handler)
template<typename Double >
void fallback_format (Double d, int num_digits, bool binary32, buffer< char > &buf, int &exp10)
template<typename T >
int format_float (T value, int precision, float_specs specs, buffer< char > &buf)
template<typename T >
int snprintf_float (T value, int precision, float_specs specs, buffer< char > &buf)
const char * utf8_decode (const char *buf, uint32_t *c, int *e)
template<typename T >
int format_float (char *buf, std::size_t size, const char *format, int precision, T value)
template<typename Char >
basic_format_context< std::back_insert_iterator< buffer< Char > >, Char >::iterator vformat_to (buffer< Char > &buf, basic_string_view< Char > format_str, basic_format_args< basic_format_context< std::back_insert_iterator< buffer< type_identity_t< Char > > >, type_identity_t< Char > > > args)
template basic_format_context< std::back_insert_iterator< buffer< char > >, char >::iterator vformat_to (buffer< char > &, string_view, basic_format_args< basic_format_context< std::back_insert_iterator< buffer< type_identity_t< char > > >, type_identity_t< char > > >)
template<typename Dest , typename Source >
Dest bit_cast (const Source &source)
bool is_big_endian ()
fallback_uintptr to_uintptr (const void *p)
template<typename T >
constexpr T max_value ()
template<typename T >
constexpr int num_bits ()
template<>
constexpr int num_bits< int128_t > ()
template<>
constexpr int num_bits< uint128_t > ()
template<>
constexpr int num_bits< fallback_uintptr > ()
FMT_INLINE void assume (bool condition)
template<typename Char >
Char * get_data (std::basic_string< Char > &s)
template<typename Container >
Container::value_type * get_data (Container &c)
template<typename T >
T * make_checked (T *p, size_t)
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) >
checked_ptr< typename Container::value_type > reserve (std::back_insert_iterator< Container > it, size_t n)
template<typename T >
buffer_appender< T > reserve (buffer_appender< T > it, size_t n)
template<typename Iterator >
Iterator & reserve (Iterator &it, size_t)
template<typename T , typename OutputIt >
constexpr T * to_pointer (OutputIt, size_t)
template<typename T >
T * to_pointer (buffer_appender< T > it, size_t n)
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) >
std::back_insert_iterator< Container > base_iterator (std::back_insert_iterator< Container > &it, checked_ptr< typename Container::value_type >)
template<typename Iterator >
Iterator base_iterator (Iterator, Iterator it)
template<typename Char >
size_t count_code_points (basic_string_view< Char > s)
size_t count_code_points (basic_string_view< char > s)
size_t count_code_points (basic_string_view< char8_type > s)
template<typename Char >
size_t code_point_index (basic_string_view< Char > s, size_t n)
size_t code_point_index (basic_string_view< char8_type > s, size_t n)
template<typename OutChar , typename InputIt , typename OutputIt , FMT_ENABLE_IF(!needs_conversion< InputIt, OutChar >::value) >
OutputIt copy_str (InputIt begin, InputIt end, OutputIt it)
template<typename Char , typename InputIt >
counting_iterator copy_str (InputIt begin, InputIt end, counting_iterator it)
template<typename T , FMT_ENABLE_IF(is_signed< T >::value) >
FMT_CONSTEXPR bool is_negative (T value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
FMT_CONSTEXPR bool is_supported_floating_point (T)
FMT_INLINE uint16_t bsr2log10 (int bsr)
int count_digits (uint64_t n)
template<unsigned BITS, typename UInt >
int count_digits (UInt n)
template<typename Int >
constexpr int digits10 () FMT_NOEXCEPT
template<>
constexpr int digits10< int128_t > () FMT_NOEXCEPT
template<>
constexpr int digits10< uint128_t > () FMT_NOEXCEPT
template<typename Char >
FMT_API std::string grouping_impl (locale_ref loc)
template<typename Char >
std::string grouping (locale_ref loc)
template<>
std::string grouping< wchar_t > (locale_ref loc)
template<typename Char >
FMT_API Char thousands_sep_impl (locale_ref loc)
template<typename Char >
Char thousands_sep (locale_ref loc)
template<>
wchar_t thousands_sep (locale_ref loc)
template<typename Char >
FMT_API Char decimal_point_impl (locale_ref loc)
template<typename Char >
Char decimal_point (locale_ref loc)
template<>
wchar_t decimal_point (locale_ref loc)
template<typename Char >
bool equal2 (const Char *lhs, const char *rhs)
bool equal2 (const char *lhs, const char *rhs)
template<typename Char >
void copy2 (Char *dst, const char *src)
FMT_INLINE void copy2 (char *dst, const char *src)
template<typename Char , typename UInt >
format_decimal_result< Char * > format_decimal (Char *out, UInt value, int size)
template<typename Char , typename UInt , typename Iterator , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< Iterator > >::value) >
format_decimal_result< Iterator > format_decimal (Iterator out, UInt value, int size)
template<unsigned BASE_BITS, typename Char , typename UInt >
Char * format_uint (Char *buffer, UInt value, int num_digits, bool upper=false)
template<unsigned BASE_BITS, typename Char >
Char * format_uint (Char *buffer, detail::fallback_uintptr n, int num_digits, bool=false)
template<unsigned BASE_BITS, typename Char , typename It , typename UInt >
It format_uint (It out, UInt value, int num_digits, bool upper=false)
template<typename T >
constexpr dragonbox::float_info< T >::carrier_uint exponent_mask ()
template<typename Char , typename It >
It write_exponent (int exp, It it)
template<typename T >
T promote_float (T value)
double promote_float (float value)
template<typename Handler >
FMT_CONSTEXPR void handle_int_type_spec (char spec, Handler &&handler)
template<typename ErrorHandler = error_handler, typename Char >
FMT_CONSTEXPR float_specs parse_float_type_spec (const basic_format_specs< Char > &specs, ErrorHandler &&eh={})
template<typename Char , typename Handler >
FMT_CONSTEXPR void handle_char_specs (const basic_format_specs< Char > *specs, Handler &&handler)
template<typename Char , typename Handler >
FMT_CONSTEXPR void handle_cstring_type_spec (Char spec, Handler &&handler)
template<typename Char , typename ErrorHandler >
FMT_CONSTEXPR void check_string_type_spec (Char spec, ErrorHandler &&eh)
template<typename Char , typename ErrorHandler >
FMT_CONSTEXPR void check_pointer_type_spec (Char spec, ErrorHandler &&eh)
template<typename OutputIt , typename Char >
FMT_NOINLINE OutputIt fill (OutputIt it, size_t n, const fill_t< Char > &fill)
template<align::type align = align::left, typename OutputIt , typename Char , typename F >
OutputIt write_padded (OutputIt out, const basic_format_specs< Char > &specs, size_t size, size_t width, F &&f)
template<align::type align = align::left, typename OutputIt , typename Char , typename F >
OutputIt write_padded (OutputIt out, const basic_format_specs< Char > &specs, size_t size, F &&f)
template<typename Char , typename OutputIt >
OutputIt write_bytes (OutputIt out, string_view bytes, const basic_format_specs< Char > &specs)
template<typename OutputIt , typename Char , typename F >
OutputIt write_int (OutputIt out, int num_digits, string_view prefix, const basic_format_specs< Char > &specs, F f)
template<typename StrChar , typename Char , typename OutputIt >
OutputIt write (OutputIt out, basic_string_view< StrChar > s, const basic_format_specs< Char > &specs)
template<typename Char , typename OutputIt >
OutputIt write_nonfinite (OutputIt out, bool isinf, const basic_format_specs< Char > &specs, const float_specs &fspecs)
int get_significand_size (const big_decimal_fp &fp)
template<typename T >
int get_significand_size (const dragonbox::decimal_fp< T > &fp)
template<typename Char , typename OutputIt >
OutputIt write_significand (OutputIt out, const char *significand, int &significand_size)
template<typename Char , typename OutputIt , typename UInt >
OutputIt write_significand (OutputIt out, UInt significand, int significand_size)
template<typename Char , typename UInt , FMT_ENABLE_IF(std::is_integral< UInt >::value) >
Char * write_significand (Char *out, UInt significand, int significand_size, int integral_size, Char decimal_point)
template<typename OutputIt , typename UInt , typename Char , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< OutputIt > >::value) >
OutputIt write_significand (OutputIt out, UInt significand, int significand_size, int integral_size, Char decimal_point)
template<typename OutputIt , typename Char >
OutputIt write_significand (OutputIt out, const char *significand, int significand_size, int integral_size, Char decimal_point)
template<typename OutputIt , typename DecimalFP , typename Char >
OutputIt write_float (OutputIt out, const DecimalFP &fp, const basic_format_specs< Char > &specs, float_specs fspecs, Char decimal_point)
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
OutputIt write (OutputIt out, T value, basic_format_specs< Char > specs, locale_ref loc={})
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_fast_float< T >::value) >
OutputIt write (OutputIt out, T value)
template<typename Char , typename OutputIt >
OutputIt write_char (OutputIt out, Char value, const basic_format_specs< Char > &specs)
template<typename Char , typename OutputIt , typename UIntPtr >
OutputIt write_ptr (OutputIt out, UIntPtr value, const basic_format_specs< Char > *specs)
template<typename Char , typename OutputIt >
OutputIt write (OutputIt out, monostate)
template<typename Char , typename OutputIt , FMT_ENABLE_IF(!std::is_same< Char, char >::value) >
OutputIt write (OutputIt out, string_view value)
template<typename Char , typename OutputIt >
OutputIt write (OutputIt out, basic_string_view< Char > value)
template<typename Char >
buffer_appender< Char > write (buffer_appender< Char > out, basic_string_view< Char > value)
template<typename Char , typename OutputIt >
OutputIt write (OutputIt out, bool value)
template<typename Char , typename OutputIt >
OutputIt write (OutputIt out, Char value)
template<typename Char , typename OutputIt >
OutputIt write (OutputIt out, const Char *value)
template<typename Char , typename OutputIt >
OutputIt write (OutputIt out, const void *value)
template<typename Char , typename OutputIt , typename T >
auto write (OutputIt out, const T &value) -> typename std::enable_if< mapped_type_constant< T, basic_format_context< OutputIt, Char > >::value==type::custom_type, OutputIt >::type
template<typename Char >
FMT_CONSTEXPR bool is_name_start (Char c)
template<typename Char , typename ErrorHandler >
FMT_CONSTEXPR int parse_nonnegative_int (const Char *&begin, const Char *end, ErrorHandler &&eh)
template<template< typename > class Handler, typename FormatArg , typename ErrorHandler >
FMT_CONSTEXPR int get_dynamic_spec (FormatArg arg, ErrorHandler eh)
template<typename Context , typename ID >
FMT_CONSTEXPR Context::format_arg get_arg (Context &ctx, ID id)
template<typename Char , typename IDHandler >
FMT_CONSTEXPR const Char * parse_arg_id (const Char *begin, const Char *end, IDHandler &&handler)
template<typename Char >
FMT_CONSTEXPR int code_point_length (const Char *begin)
template<typename Char >
constexpr bool is_ascii_letter (Char c)
template<typename Char , FMT_ENABLE_IF(std::is_integral< Char >::value) >
constexpr Char to_ascii (Char value)
template<typename Char , FMT_ENABLE_IF(std::is_enum< Char >::value) >
constexpr std::underlying_type< Char >::type to_ascii (Char value)
template<typename Char , typename Handler >
FMT_CONSTEXPR const Char * parse_align (const Char *begin, const Char *end, Handler &&handler)
template<typename Char , typename Handler >
FMT_CONSTEXPR const Char * parse_width (const Char *begin, const Char *end, Handler &&handler)
template<typename Char , typename Handler >
FMT_CONSTEXPR const Char * parse_precision (const Char *begin, const Char *end, Handler &&handler)
template<typename Char , typename SpecHandler >
FMT_CONSTEXPR const Char * parse_format_specs (const Char *begin, const Char *end, SpecHandler &&handler)
template<bool IS_CONSTEXPR, typename T , typename Ptr = const T *>
FMT_CONSTEXPR bool find (Ptr first, Ptr last, T value, Ptr &out)
template<>
bool find< false, char > (const char *first, const char *last, char value, const char *&out)
template<typename Char , typename Handler >
FMT_CONSTEXPR const Char * parse_replacement_field (const Char *begin, const Char *end, Handler &&handler)
template<bool IS_CONSTEXPR, typename Char , typename Handler >
FMT_CONSTEXPR_DECL FMT_INLINE void parse_format_string (basic_string_view< Char > format_str, Handler &&handler)
template<typename T , typename ParseContext >
FMT_CONSTEXPR const ParseContext::char_type * parse_format_specs (ParseContext &ctx)
template<typename Char , size_t N>
FMT_CONSTEXPR basic_string_view< Char > compile_string_to_view (const Char(&s)[N])
template<typename Char >
FMT_CONSTEXPR basic_string_view< Char > compile_string_to_view (const std_string_view< Char > &s)
template<template< typename > class Handler, typename Context >
void handle_dynamic_spec (int &value, arg_ref< typename Context::char_type > ref, Context &ctx)
template FMT_API std::string grouping_impl< char > (locale_ref loc)
template FMT_API std::string grouping_impl< wchar_t > (locale_ref loc)
template FMT_API char thousands_sep_impl< char > (locale_ref loc)
template FMT_API wchar_t thousands_sep_impl< wchar_t > (locale_ref loc)
template int format_float< double > (double value, int precision, float_specs specs, buffer< char > &buf)
template int format_float< long double > (long double value, int precision, float_specs specs, buffer< char > &buf)
int snprintf_float (float value, int precision, float_specs specs, buffer< char > &buf)=delete
template int snprintf_float< double > (double value, int precision, float_specs specs, buffer< char > &buf)
template int snprintf_float< long double > (long double value, int precision, float_specs specs, buffer< char > &buf)
template<typename Char , typename Traits >
void_t operator<< (std::basic_ostream< Char, Traits > &, Char)
template<typename Char , typename Traits >
void_t operator<< (std::basic_ostream< Char, Traits > &, char)
template<typename Traits >
void_t operator<< (std::basic_ostream< char, Traits > &, char)
template<typename Traits >
void_t operator<< (std::basic_ostream< char, Traits > &, signed char)
template<typename Traits >
void_t operator<< (std::basic_ostream< char, Traits > &, unsigned char)
template<typename Char >
void write_buffer (std::basic_ostream< Char > &os, buffer< Char > &buf)
template<typename Char , typename T >
void format_value (buffer< Char > &buf, const T &value, locale_ref loc=locale_ref())
template<typename T , typename Context , typename Char >
void convert_arg (basic_format_arg< Context > &arg, Char type)
template<typename Char , typename Context >
void vprintf (buffer< Char > &buf, basic_string_view< Char > format, basic_format_args< Context > args)
mutations_ui_result show_mutations_ui_internal (Character &who)
int get_current_language_version ()
const char * _translate_internal (const char *msg) ATTRIBUTE_FORMAT_ARG(1)
std::string _translate_internal (const std::string &msg)
static local_translation_cache< const char * > get_local_translation_cache (const char *)
static local_translation_cache< std::string > get_local_translation_cache (const std::string &)
Variables
FMT_EXTERN template struct basic_data< void >
Typedef Documentation
checked_ptr
template<typename T > using detail::checked_ptr = typedef T*
Definition at line 399 of file fmtlib_format.h.
format_func
using detail::format_func = typedef void (*)(detail::buffer<char> &, int, string_view)
Definition at line 3719 of file fmtlib_format.h.
has_fallback_formatter
template<typename T , typename Context > using detail::has_fallback_formatter = typedef std::is_constructible<fallback_formatter<T, typename Context::char_type> >
Definition at line 997 of file fmtlib_core.h.
is_fast_float
template<typename T > using detail::is_fast_float = typedef bool_constant < std::numeric_limits<T>::is_iec559 && sizeof(T) <= sizeof(double) >
Definition at line 673 of file fmtlib_format.h.
is_integer
template<typename T > using detail::is_integer = typedef bool_constant < is_integral<T>::value && !std::is_same<T, bool>::value && !std::is_same<T, char>::value && !std::is_same<T, wchar_t>::value >
Definition at line 2733 of file fmtlib_format.h.
is_signed
template<typename T > using detail::is_signed = typedef std::integral_constant < bool, std::numeric_limits<T>::is_signed || std::is_same<T, int128_t>::value >
Definition at line 892 of file fmtlib_format.h.
iterator_t
template<typename T > using detail::iterator_t = typedef decltype(std::begin(std::declval<T &>()))
Definition at line 377 of file fmtlib_format.h.
long_type
using detail::long_type = typedef conditional_t<long_short, int, long long>
Definition at line 1235 of file fmtlib_core.h.
mapped_type_constant
template<typename T , typename Context > using detail::mapped_type_constant = typedef type_constant<decltype(arg_mapper<Context>().map(std::declval<const T &>())), typename Context::char_type>
Definition at line 1405 of file fmtlib_core.h.
needs_conversion
template<typename InputIt , typename OutChar > using detail::needs_conversion = typedef bool_constant < std::is_same<typename std::iterator_traits<InputIt>::value_type, char>::value && std::is_same<OutChar, char8_type>::value >
Definition at line 643 of file fmtlib_format.h.
sentinel_t
template<typename T > using detail::sentinel_t = typedef decltype(std::end(std::declval<T &>()))
Definition at line 378 of file fmtlib_format.h.
uint32_or_64_or_128_t
template<typename T > using detail::uint32_or_64_or_128_t = typedef conditional_t < num_bits<T>() <= 32 && !FMT_REDUCE_INT_INSTANTIATIONS, uint32_t, conditional_t<num_bits<T>() <= 64, uint64_t, uint128_t> >
Definition at line 920 of file fmtlib_format.h.
uintptr_t
using detail::uintptr_t = typedef fallback_uintptr
Definition at line 335 of file fmtlib_format.h.
ulong_type
using detail::ulong_type = typedef conditional_t<long_short, unsigned, unsigned long long>
Definition at line 1236 of file fmtlib_core.h.
void_t
template<typename... Ts> using detail::void_t = typedef typename detail::void_t_impl<Ts...>::type
Definition at line 1545 of file fmtlib_core.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
long_short
Definition at line 1234 of file fmtlib_core.h.
{ long_short = sizeof(long) == sizeof(int) };
anonymous enum
anonymous enum
Enumerator
packed_arg_bits
Definition at line 1409 of file fmtlib_core.h.
{ packed_arg_bits = 4 };
anonymous enum
anonymous enum
Enumerator
max_packed_args
Definition at line 1411 of file fmtlib_core.h.
{ max_packed_args = 62 / packed_arg_bits };
anonymous enum
anonymous enum : unsigned long long
Enumerator
is_unpacked_bit
Definition at line 1412 of file fmtlib_core.h.
: unsigned long long { is_unpacked_bit = 1ULL << 63 };
anonymous enum
anonymous enum : unsigned long long
Enumerator
has_named_args_bit
Definition at line 1413 of file fmtlib_core.h.
: unsigned long long { has_named_args_bit = 1ULL << 62 };
arg_id_kind
enum class detail::arg_id_kind strong
Enumerator
none
index
name
Definition at line 2993 of file fmtlib_format.h.
{ none, index, name };
char8_type
enum detail::char8_type : unsigned char
Definition at line 349 of file fmtlib_core.h.
: unsigned char {};
float_format
enum class detail::float_format : unsigned char strong
Enumerator
general
exp
fixed
hex
Definition at line 1465 of file fmtlib_format.h.
                        : unsigned char {
    general,  // General: exponent notation or fixed point based on magnitude.
    exp,      // Exponent notation with the default precision of 6, e.g. 1.2e-3.
    fixed,    // Fixed point with the default precision of 6, e.g. 0.0012.
    hex
};
mutations_ui_cmd
enum class detail::mutations_ui_cmd strong
Enumerator
exit
activate
deactivate
Definition at line 11 of file mutation_ui.h.
{
    exit,
    activate,
    deactivate,
};
round_direction
enum class detail::round_direction strong
Enumerator
unknown
up
down
Definition at line 1600 of file fmtlib_format-inl.h.
{ unknown, up, down };
type
enum class detail::type strong
Enumerator
none_type
int_type
uint_type
long_long_type
ulong_long_type
int128_type
uint128_type
bool_type
char_type
last_integer_type
float_type
double_type
long_double_type
last_numeric_type
cstring_type
string_type
pointer_type
custom_type
Definition at line 1087 of file fmtlib_core.h.
                {
    none_type,
    // Integer types should go first,
    int_type,
    uint_type,
    long_long_type,
    ulong_long_type,
    int128_type,
    uint128_type,
    bool_type,
    char_type,
    last_integer_type = char_type,
    // followed by floating-point types.
    float_type,
    double_type,
    long_double_type,
    last_numeric_type = long_double_type,
    cstring_type,
    string_type,
    pointer_type,
    custom_type
};
Function Documentation
_translate_internal() [1/2]
const char * detail::_translate_internal (const char * msg)
Definition at line 31 of file translations.cpp.
{
    return l10n_data::get_library().get( msg );
}
References l10n_data::get_library().
Referenced by _translate_internal(), detail::local_translation_cache< const char * >::operator()(), detail::local_translation_cache< std::string >::operator()(), and translation::translated().
_translate_internal() [2/2]
std::string detail::_translate_internal (const std::string & msg) inline
Definition at line 53 of file translations.h.
{
    return _translate_internal( msg.c_str() );
}
References _translate_internal().
assert_fail()
FMT_FUNC void detail::assert_fail (const char * file, int line, const char * message)
Definition at line 48 of file fmtlib_format-inl.h.
{
    // Use unchecked std::fprintf to avoid triggering another assertion when
    // writing to stderr fails
    std::fprintf( stderr, "%s:%d: assertion failed: %s", file, line, message );
    // Chosen instead of std::abort to satisfy Clang in CUDA mode during device
    // code pass.
    std::terminate();
}
References file, fprintf(), line(), and mapgen_defer::message.
assume()
FMT_INLINE void detail::assume (bool condition)
Definition at line 367 of file fmtlib_format.h.
{
    ( void )condition;
#if FMT_HAS_BUILTIN(__builtin_assume)
    __builtin_assume( condition );
#endif
}
Referenced by to_string().
base_iterator() [1/2]
template<typename Iterator > Iterator detail::base_iterator (Iterator , Iterator it) inline
Definition at line 457 of file fmtlib_format.h.
{
    return it;
}
Referenced by write(), write_float(), write_padded(), and write_ptr().
base_iterator() [2/2]
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) > std::back_insert_iterator< Container > detail::base_iterator (std::back_insert_iterator< Container > & it, checked_ptr< typename Container::value_type >) inline
Definition at line 449 of file fmtlib_format.h.
{
    return it;
}
bit_cast()
template<typename Dest , typename Source > Dest detail::bit_cast (const Source & source) inline
Definition at line 297 of file fmtlib_format.h.
{
    static_assert( sizeof( Dest ) == sizeof( Source ), "size mismatch" );
    Dest dest;
    std::memcpy( &dest, &source, sizeof( dest ) );
    return dest;
}
bsr2log10()
FMT_INLINE uint16_t detail::bsr2log10 (int bsr)
Definition at line 1024 of file fmtlib_format.h.
{
    static constexpr uint16_t data[] = {
        1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,
        6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  9,  9,  9,  10, 10, 10,
        10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 15, 15,
        15, 16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 19, 20
    };
    return data[bsr];
}
check() [1/2]
template<typename T , typename U > const U & detail::check (const U & val) inline
Definition at line 1618 of file fmtlib_core.h.
{
    return val;
}
check() [2/2]
template<typename T > int detail::check (unformattable)
Definition at line 1610 of file fmtlib_core.h.
{
    static_assert(
        formattable<T>(),
        "Cannot format an argument.  To make type T formattable provide a "
        "formatter<T> specialization: https://fmt.dev/latest/api.html#udt" );
    return 0;
}
Referenced by cast_zlight(), cast_zlight_segment(), castLight(), castLightAll(), vehicle::check_rotated_intervening(), talk_function::field_harvest(), mission_start::find_safety(), dependency_node::get_dependencies_as_nodes(), dependency_node::get_dependents_as_nodes(), dependency_node::inherit_errors(), robot_finds_kitten::process_input(), map::shoot(), and text_style_check().
check_format_string() [1/2]
template<typename... , typename S , FMT_ENABLE_IF(!is_compile_string< S >::value) > FMT_INLINE void detail::check_format_string (const S &)
Definition at line 551 of file fmtlib_core.h.
{
#ifdef FMT_ENFORCE_COMPILE_STRING
    static_assert( is_compile_string<S>::value,
                   "FMT_ENFORCE_COMPILE_STRING requires all format strings to use "
                   "FMT_STRING." );
#endif
}
Referenced by make_args_checked().
check_format_string() [2/2]
template<typename... , typename S , FMT_ENABLE_IF(is_compile_string< S >::value) > void detail::check_format_string (S format_str)
Definition at line 3691 of file fmtlib_format.h.
{
    FMT_CONSTEXPR_DECL auto s = to_string_view( format_str );
    using checker = format_string_checker<typename S::char_type, error_handler,
          remove_cvref_t<Args>...>;
    FMT_CONSTEXPR_DECL bool invalid_format =
        ( parse_format_string<true>( s, checker( s, {} ) ), true );
    ( void )invalid_format;
}
References FMT_CONSTEXPR_DECL, and to_string_view().
check_pointer_type_spec()
template<typename Char , typename ErrorHandler > FMT_CONSTEXPR void detail::check_pointer_type_spec (Char spec, ErrorHandler && eh)
Definition at line 1644 of file fmtlib_format.h.
{
    if( spec != 0 && spec != 'p' ) {
        eh.on_error( "invalid type specifier" );
    }
}
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), and formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
check_string_type_spec()
template<typename Char , typename ErrorHandler > FMT_CONSTEXPR void detail::check_string_type_spec (Char spec, ErrorHandler && eh)
Definition at line 1636 of file fmtlib_format.h.
{
    if( spec != 0 && spec != 's' ) {
        eh.on_error( "invalid type specifier" );
    }
}
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), and formatter< bytes >::parse().
code_point_index() [1/2]
template<typename Char > size_t detail::code_point_index (basic_string_view< Char > s, size_t n) inline
Definition at line 623 of file fmtlib_format.h.
{
    size_t size = s.size();
    return n < size ? n : size;
}
References basic_string_view< Char >::size(), and om_direction::size.
code_point_index() [2/2]
size_t detail::code_point_index (basic_string_view< char8_type > s, size_t n) inline
Definition at line 630 of file fmtlib_format.h.
{
    const char8_type *data = s.data();
    size_t num_code_points = 0;
    for( size_t i = 0, size = s.size(); i != size; ++i ) {
        if( ( data[i] & 0xc0 ) != 0x80 && ++num_code_points > n ) {
            return i;
        }
    }
    return s.size();
}
References basic_string_view< Char >::data(), basic_string_view< Char >::size(), and om_direction::size.
Referenced by write().
code_point_length()
template<typename Char > FMT_CONSTEXPR int detail::code_point_length (const Char * begin)
Definition at line 3161 of file fmtlib_format.h.
{
    if( const_check( sizeof( Char ) != 1 ) ) {
        return 1;
    }
    constexpr char lengths[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 3, 4, 0
                               };
    int len = lengths[static_cast<unsigned char>( *begin ) >> 3];
    // Compute the pointer to the next character early so that the next
    // iteration can start working on the next character. Neither Clang
    // nor GCC figure out this reordering on their own.
    return len + !len;
}
References const_check().
Referenced by parse_align(), and utf8_decode().
compile_string_to_view() [1/2]
template<typename Char , size_t N> FMT_CONSTEXPR basic_string_view< Char > detail::compile_string_to_view (const Char(&) s[N])
Definition at line 3645 of file fmtlib_format.h.
{
    // Remove trailing null character if needed. Won't be present if this is used
    // with raw character array (i.e. not defined as a string).
    return {s,
            N - ( ( std::char_traits<Char>::to_int_type( s[N - 1] ) == 0 ) ? 1 : 0 )};
}
compile_string_to_view() [2/2]
template<typename Char > FMT_CONSTEXPR basic_string_view< Char > detail::compile_string_to_view (const std_string_view< Char > & s)
Definition at line 3656 of file fmtlib_format.h.
{
    return {s.data(), s.size()};
}
const_check()
template<typename T > constexpr T detail::const_check (T value) constexpr
Definition at line 286 of file fmtlib_core.h.
{
    return value;
}
Referenced by code_point_length(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), detail::arg_converter< T, Context >::operator()(), formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), dynamic_format_arg_store< Context >::push_back(), and write().
convert_arg()
template<typename T , typename Context , typename Char > void detail::convert_arg (basic_format_arg< Context > & arg, Char type)
Definition at line 136 of file fmtlib_printf.h.
{
    visit_format_arg( arg_converter<T, Context>( arg, type ), arg );
}
References arg(), and visit_format_arg().
Referenced by basic_printf_context< OutputIt, Char >::format().
copy2() [1/2]
template<typename Char > void detail::copy2 (Char * dst, const char * src)
Definition at line 1187 of file fmtlib_format.h.
{
    *dst++ = static_cast<Char>( *src++ );
    *dst = static_cast<Char>( *src );
}
copy2() [2/2]
FMT_INLINE void detail::copy2 (char * dst, const char * src)
Definition at line 1192 of file fmtlib_format.h.
{
    memcpy( dst, src, 2 );
}
Referenced by format_decimal().
copy_str() [1/2]
template<typename Char , typename InputIt > counting_iterator detail::copy_str (InputIt begin, InputIt end, counting_iterator it) inline
Definition at line 666 of file fmtlib_format.h.
{
    return it + ( end - begin );
}
copy_str() [2/2]
template<typename OutChar , typename InputIt , typename OutputIt , FMT_ENABLE_IF(!needs_conversion< InputIt, OutChar >::value) > OutputIt detail::copy_str (InputIt begin, InputIt end, OutputIt it)
Definition at line 650 of file fmtlib_format.h.
{
    return std::copy( begin, end, it );
}
count() [1/2]
template<bool B = false> constexpr size_t detail::count () constexpr
Definition at line 1073 of file fmtlib_core.h.
{
    return B ? 1 : 0;
}
Referenced by map::add_spawn(), turret_data::ammo_select(), detail::buffer< T >::append(), vehicle::basic_consumption(), map::batter(), overmap::build_lab(), start_location::burn(), iuse::capture_monster_act(), enchantment::check(), jmapgen_sealed_item::check(), vehicle::check_heli_descend(), craft_command::check_item_components_missing(), craft_command::check_tool_components_missing(), convert_to_items(), count(), count_digits(), player::craft_consume_tools(), salvage_actor::cut_up(), debug_menu::debug(), scent_map::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), map::destroy(), map::destroy_furn(), game::display_lighting(), inventory_column::draw(), overmap_ui::draw_ascii(), editmap::edit_feature(), debug_menu::effect_edit_menu(), iuse::einktabletpc(), vehicle::engine_cold_factor(), inventory_iuse_selector::execute(), inventory_drop_selector::execute(), npc::faction_display(), vehicle_part::fault_set(), color_manager::finalize(), crafting::find_tool_component(), vehicle::fuel_usage(), fwrite_fully(), get_build_reqs_for_furn_ter_ids(), inventory_selector_preset::get_caption(), iexamine::get_harvest_items(), anonymous_namespace{messages.cpp}::game_message::get_with_count(), Character::hardcoded_effects(), input_manager::init(), npc_trading::init_buying(), basecamp::job_assignment_ui(), profession::load(), WORLD::load_legacy_options(), make_args_checked(), mill_load_food(), game::mon_info(), advanced_inventory::move_all_items(), talk_effect_t::parse_sub_effect(), pickup::pick_up(), start_location::prepare_map(), game::debug_hour_timer::print_time(), map::process_fields_in_submap(), inventory_drop_selector::process_selected(), advanced_inventory::query_charges(), iexamine::query_seed(), snippet_library::random_from_category(), Messages::recent_messages(), anonymous_namespace{messages.cpp}::messages_impl::recent_messages(), iexamine::recycle_compactor(), vehicle::reload_seeds(), remove_from_item_valptr(), item_contents::remove_internal(), visitable< T >::remove_items_with(), rng_get_engine(), select_crafting_recipe(), player::select_item_component(), anonymous_namespace{messages.cpp}::game_message::serialize(), overmap::serialize(), serialize_array_to_compacted_sequence(), inventory_iuse_selector::set_chosen_count(), inventory_drop_selector::set_chosen_count(), talk_effect_fun_t::set_consume_item(), conditional_t< T >::set_has_item_category(), conditional_t< T >::set_has_items(), talk_effect_fun_t::set_u_buy_item(), talk_effect_fun_t::set_u_buy_monster(), talk_effect_fun_t::set_u_sell_item(), npc::shop_restock(), std::this_thread::sleep_for(), smoker_load_food(), map::spread_gas(), salvage_actor::time_to_cut_up(), vehicle::total_power_w(), npc_trading::transfer_items(), detail::buffer< T >::try_resize(), overmap::unserialize(), unserialize_array_from_compacted_sequence(), submap::update_lum_rem(), event_statistic_count::value(), map::vehmove(), iexamine::vending(), and detail::formatbuf< Char >::xsputn().
count() [2/2]
template<bool B1, bool B2, bool... Tail> constexpr size_t detail::count () constexpr
Definition at line 1077 of file fmtlib_core.h.
{
    return ( B1 ? 1 : 0 ) + count<B2, Tail...>();
}
References count().
Referenced by detail::iterator_buffer< OutputIt, T, Traits >::count().
count_code_points() [1/3]
template<typename Char > size_t detail::count_code_points (basic_string_view< Char > s) inline
Definition at line 598 of file fmtlib_format.h.
{
    return s.size();
}
References basic_string_view< Char >::size().
Referenced by count_code_points().
count_code_points() [2/3]
size_t detail::count_code_points (basic_string_view< char > s) inline
Definition at line 604 of file fmtlib_format.h.
{
    const char *data = s.data();
    size_t num_code_points = 0;
    for( size_t i = 0, size = s.size(); i != size; ++i ) {
        if( ( data[i] & 0xc0 ) != 0x80 ) {
            ++num_code_points;
        }
    }
    return num_code_points;
}
References basic_string_view< Char >::data(), basic_string_view< Char >::size(), and om_direction::size.
count_code_points() [3/3]
size_t detail::count_code_points (basic_string_view< char8_type > s) inline
Definition at line 616 of file fmtlib_format.h.
{
    return count_code_points( basic_string_view<char>(
                                  reinterpret_cast<const char *>( s.data() ), s.size() ) );
}
References count_code_points(), basic_string_view< Char >::data(), and basic_string_view< Char >::size().
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), and write().
count_digits() [1/2]
template<unsigned BITS, typename UInt > int detail::count_digits (UInt n) inline
Definition at line 1105 of file fmtlib_format.h.
{
    int num_digits = 0;
    do {
        ++num_digits;
    } while( ( n >>= BITS ) != 0 );
    return num_digits;
}
Referenced by format_decimal(), get_significand_size(), detail::int_writer< OutputIt, Char, UInt >::on_dec(), and detail::int_writer< OutputIt, Char, UInt >::on_num().
count_digits() [2/2]
int detail::count_digits (uint64_t n) inline
Definition at line 1053 of file fmtlib_format.h.
{
    int count = 1;
    for( ;; ) {
        // Integer division is slow so do it for a group of four digits instead
        // of for every digit. The idea comes from the talk by Alexandrescu
        // "Three Optimization Tips for C++". See speed-test for a comparison.
        if( n < 10 ) {
            return count;
        }
        if( n < 100 ) {
            return count + 1;
        }
        if( n < 1000 ) {
            return count + 2;
        }
        if( n < 10000 ) {
            return count + 3;
        }
        n /= 10000u;
        count += 4;
    }
}
References count().
Referenced by format_error_code(), and grisu_gen_digits().
count_digits< 4 >()
template<> int detail::count_digits< 4 > (detail::fallback_uintptr n)
Definition at line 266 of file fmtlib_format-inl.h.
{
    // fallback_uintptr is always stored in little endian.
    int i = static_cast<int>( sizeof( void * ) ) - 1;
    while( i > 0 && n.value[i] == 0 ) {
        --i;
    }
    auto char_digits = std::numeric_limits<unsigned char>::digits / 4;
    return i >= 0 ? i * char_digits + count_digits<4, unsigned>( n.value[i] ) : 1;
}
References detail::fallback_uintptr::value.
Referenced by detail::int_writer< OutputIt, Char, UInt >::on_hex(), and write_ptr().
count_named_args()
template<typename... Args> constexpr size_t detail::count_named_args () constexpr
Definition at line 1082 of file fmtlib_core.h.
{
    return count<is_named_arg<Args>::value...>();
}
decimal_point() [1/2]
template<typename Char > Char detail::decimal_point (locale_ref loc) inline
Definition at line 1167 of file fmtlib_format.h.
{
    return Char( decimal_point_impl<char>( loc ) );
}
decimal_point() [2/2]
template<> wchar_t detail::decimal_point (locale_ref loc) inline
Definition at line 1171 of file fmtlib_format.h.
{
    return decimal_point_impl<wchar_t>( loc );
}
Referenced by write_float(), and write_significand().
decimal_point_impl() [1/2]
template<typename Char > template FMT_API wchar_t detail::decimal_point_impl (locale_ref loc)
Definition at line 224 of file fmtlib_format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>( loc.get<std::locale>() )
           .decimal_point();
}
References detail::locale_ref::get().
decimal_point_impl() [2/2]
template<typename Char > FMT_API Char detail::decimal_point_impl (locale_ref loc)
Definition at line 224 of file fmtlib_format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>( loc.get<std::locale>() )
           .decimal_point();
}
References detail::locale_ref::get().
digits10()
template<typename Int > constexpr int detail::digits10 () constexpr
Definition at line 1140 of file fmtlib_format.h.
{
    return std::numeric_limits<Int>::digits10;
}
References digits10().
Referenced by digits10().
digits10< int128_t >()
template<> constexpr int detail::digits10< int128_t > () constexpr
Definition at line 1143 of file fmtlib_format.h.
{ return 38; }
digits10< uint128_t >()
template<> constexpr int detail::digits10< uint128_t > () constexpr
Definition at line 1144 of file fmtlib_format.h.
{ return 38; }
encode_types() [1/2]
template<typename > constexpr unsigned long long detail::encode_types () constexpr
Definition at line 1589 of file fmtlib_core.h.
{
    return 0;
}
encode_types() [2/2]
template<typename Context , typename Arg , typename... Args> constexpr unsigned long long detail::encode_types () constexpr
Definition at line 1595 of file fmtlib_core.h.
{
    return static_cast<unsigned>( mapped_type_constant<Arg, Context>::value ) |
           ( encode_types<Context, Args...>() << packed_arg_bits );
}
References packed_arg_bits.
equal2() [1/2]
template<typename Char > bool detail::equal2 (const Char * lhs, const char * rhs)
Definition at line 1177 of file fmtlib_format.h.
{
    return lhs[0] == rhs[0] && lhs[1] == rhs[1];
}
Referenced by vformat().
equal2() [2/2]
bool detail::equal2 (const char * lhs, const char * rhs) inline
Definition at line 1181 of file fmtlib_format.h.
{
    return memcmp( lhs, rhs, 2 ) == 0;
}
exponent_mask()
template<typename T > constexpr dragonbox::float_info< T >::carrier_uint detail::exponent_mask () constexpr
Definition at line 1457 of file fmtlib_format.h.
{
    using uint = typename dragonbox::float_info<T>::carrier_uint;
    return ( ( uint( 1 ) << dragonbox::float_info<T>::exponent_bits ) - 1 )
           << dragonbox::float_info<T>::significand_bits;
}
Referenced by detail::fp::assign().
fallback_format()
template<typename Double > void detail::fallback_format (Double d, int num_digits, bool binary32, buffer< char > & buf, int & exp10)
Definition at line 2525 of file fmtlib_format-inl.h.
{
    bigint numerator;    // 2 * R in (FPP)^2.
    bigint denominator;  // 2 * S in (FPP)^2.
    // lower and upper are differences between value and corresponding boundaries.
    bigint lower;             // (M^- in (FPP)^2).
    bigint upper_store;       // upper's value if different from lower.
    bigint *upper = nullptr;  // (M^+ in (FPP)^2).
    fp value;
    // Shift numerator and denominator by an extra bit or two (if lower boundary
    // is closer) to make lower and upper integers. This eliminates multiplication
    // by 2 during later computations.
    const bool is_predecessor_closer =
        binary32 ? value.assign( static_cast<float>( d ) ) : value.assign( d );
    int shift = is_predecessor_closer ? 2 : 1;
    uint64_t significand = value.f << shift;
    if( value.e >= 0 ) {
        numerator.assign( significand );
        numerator <<= value.e;
        lower.assign( 1 );
        lower <<= value.e;
        if( shift != 1 ) {
            upper_store.assign( 1 );
            upper_store <<= value.e + 1;
            upper = &upper_store;
        }
        denominator.assign_pow10( exp10 );
        denominator <<= shift;
    } else if( exp10 < 0 ) {
        numerator.assign_pow10( -exp10 );
        lower.assign( numerator );
        if( shift != 1 ) {
            upper_store.assign( numerator );
            upper_store <<= 1;
            upper = &upper_store;
        }
        numerator *= significand;
        denominator.assign( 1 );
        denominator <<= shift - value.e;
    } else {
        numerator.assign( significand );
        denominator.assign_pow10( exp10 );
        denominator <<= shift - value.e;
        lower.assign( 1 );
        if( shift != 1 ) {
            upper_store.assign( 1ULL << 1 );
            upper = &upper_store;
        }
    }
    // Invariant: value == (numerator / denominator) * pow(10, exp10).
    if( num_digits < 0 ) {
        // Generate the shortest representation.
        if( !upper ) {
            upper = &lower;
        }
        bool even = ( value.f & 1 ) == 0;
        num_digits = 0;
        char *data = buf.data();
        for( ;; ) {
            int digit = numerator.divmod_assign( denominator );
            bool low = compare( numerator, lower ) - even < 0; // numerator <[=] lower.
            // numerator + upper >[=] pow10:
            bool high = add_compare( numerator, *upper, denominator ) + even > 0;
            data[num_digits++] = static_cast<char>( '0' + digit );
            if( low || high ) {
                if( !low ) {
                    ++data[num_digits - 1];
                } else if( high ) {
                    int result = add_compare( numerator, numerator, denominator );
                    // Round half to even.
                    if( result > 0 || ( result == 0 && ( digit % 2 ) != 0 ) ) {
                        ++data[num_digits - 1];
                    }
                }
                buf.try_resize( to_unsigned( num_digits ) );
                exp10 -= num_digits - 1;
                return;
            }
            numerator *= 10;
            lower *= 10;
            if( upper != &lower ) {
                *upper *= 10;
            }
        }
    }
    // Generate the given number of digits.
    exp10 -= num_digits - 1;
    if( num_digits == 0 ) {
        buf.try_resize( 1 );
        denominator *= 10;
        buf[0] = add_compare( numerator, numerator, denominator ) > 0 ? '1' : '0';
        return;
    }
    buf.try_resize( to_unsigned( num_digits ) );
    for( int i = 0; i < num_digits - 1; ++i ) {
        int digit = numerator.divmod_assign( denominator );
        buf[i] = static_cast<char>( '0' + digit );
        numerator *= 10;
    }
    int digit = numerator.divmod_assign( denominator );
    auto result = add_compare( numerator, numerator, denominator );
    if( result > 0 || ( result == 0 && ( digit % 2 ) != 0 ) ) {
        if( digit == 9 ) {
            const auto overflow = '0' + 10;
            buf[num_digits - 1] = overflow;
            // Propagate the carry.
            for( int i = num_digits - 1; i > 0 && buf[i] == overflow; --i ) {
                buf[i] = '0';
                ++buf[i - 1];
            }
            if( buf[0] == overflow ) {
                buf[0] = '1';
                ++exp10;
            }
            return;
        }
        ++digit;
    }
    buf[num_digits - 1] = static_cast<char>( '0' + digit );
}
References detail::bigint::assign(), detail::bigint::assign_pow10(), game_menus::inv::compare(), detail::buffer< T >::data(), detail::bigint::divmod_assign(), high, to_unsigned(), and detail::buffer< T >::try_resize().
Referenced by format_float().
fill()
template<typename OutputIt , typename Char > FMT_NOINLINE OutputIt detail::fill (OutputIt it, size_t n, const fill_t< Char > & fill)
Definition at line 1696 of file fmtlib_format.h.
{
    auto fill_size = fill.size();
    if( fill_size == 1 ) {
        return std::fill_n( it, n, fill[0] );
    }
    for( size_t i = 0; i < n; ++i ) {
        it = std::copy_n( fill.data(), fill_size, it );
    }
    return it;
}
References fill().
Referenced by map::build_map_cache(), debug_menu::debug(), fill(), Character::item_encumb(), level_cache::level_cache(), game::mon_info_update(), detail::specs_setter< Char >::on_fill(), lightson_game::reset_level(), and write_padded().
find()
template<bool IS_CONSTEXPR, typename T , typename Ptr = const T *> FMT_CONSTEXPR bool detail::find (Ptr first, Ptr last, T value, Ptr & out)
Definition at line 3355 of file fmtlib_format.h.
{
    for( out = first; out != last; ++out ) {
        if( *out == value ) {
            return true;
        }
    }
    return false;
}
References last.
Referenced by input_context::action_uses_input(), mapgen_basic_container::add(), add_boardable(), dependency_node::add_conflict(), inventory_column::add_entry(), mtype::add_special_attack(), scenario::allowed_start(), map::apply_vision_transparency_cache(), inventory::assign_empty_invlet(), talk_function::assign_mission(), diary::bionic_changes(), talk_function::bionic_remove(), board_up(), options_manager::build_tilesets_list(), map::build_vision_transparency_cache(), iuse::camera(), can_do_activity_there(), holster_actor::can_holster(), player_activity::can_resume_with(), mod_ui::can_shift_down(), mod_ui::can_shift_up(), check_conflict(), scenario::check_definition(), iexamine::choose_fertilizer(), game::cleanup_at_end(), talk_function::clear_mission(), contains_trait(), Single_item_creator::create(), Trait_group_creator::create(), Single_item_creator::create_single(), target_ui::cycle_targets(), draw_tabs(), ensure_unifont_loaded(), invlet_favorites::erase(), craft_command::execute(), talk_function::field_plant(), overmap_lake_settings::finalize(), scen_blacklist::finalize(), Item_factory::finalize_pre(), game::find_nearby_items(), weather_generator::forecast_priority(), basic_printf_context< OutputIt, Char >::format(), iexamine::fvat_empty(), lightson_game::generate_change_coords(), generic_multi_activity_check_requirement(), dependency_node::get_dependencies_as_nodes(), dependency_node::get_dependents_as_nodes(), requirement_data::get_folded_list(), mission_type::get_random_id(), SkillLevelMap::get_skill_level_object(), weather_generator::get_weather_conditions(), gettext_gendered(), Character::has_activity(), item::has_effect_when_carried(), item::has_effect_when_wielded(), item::has_effect_when_worn(), character_martial_arts::has_martialart(), hflesh_to_flesh(), dependency_node::inherit_errors(), is_cqb_skill(), bionic_data::is_included(), profession::is_locked_trait(), bionic::is_this_fuel_powered(), iexamine::keg(), diary::kill_changes(), avatar::load(), main_menu::load_character_tab(), load_languages(), mod_management::load_modfile(), load_recipe_category(), Character::made_of(), item::made_of(), mtype::made_of(), mapgen_lake_shore(), mapgen_parking_lot(), diary::martial_art_changes(), json_item_substitution::trait_requirements::meets_condition(), mill_load_food(), diary::mission_changes(), inventory_column::move_entries_to(), Character::mutate_towards(), selection_column::on_change(), avatar::on_mission_finished(), ContainsPredicate< T1, T2 >::operator()(), inventory_column::page_of(), scenario::permitted_professions(), selection_column::prepare_paging(), activity_handlers::pulp_do_turn(), npc::recharge_cbm(), vehicle::refresh(), vehicle::remove_remote_part(), mtype::remove_special_attacks(), map::remove_trap(), requirements_map(), WORLD::save_exists(), overmap_ui::search(), avatar::set_active_mission(), Item_factory::set_allergy_flags(), set_traits(), worldfactory::show_modselection_window(), smoker_load_food(), basecamp::start_fortifications(), holster_actor::store(), map::ter_set(), inventory_compare_selector::toggle_entry(), diary::trait_changes(), mod_ui::try_add(), mod_ui::try_rem(), event_bus::unsubscribe(), sew_advanced_actor::use(), vehicle::use_washing_machine(), invlet_wrapper::valid(), and basecamp::validate_assignees().
find< false, char >()
template<> bool detail::find< false, char > (const char * first, const char * last, char value, const char *& out) inline
Definition at line 3366 of file fmtlib_format.h.
{
    out = static_cast<const char *>(
              std::memchr( first, value, detail::to_unsigned( last - first ) ) );
    return out != nullptr;
}
References last, and to_unsigned().
FMT_SUPPRESS_MSC_WARNING()
detail::FMT_SUPPRESS_MSC_WARNING (4566) const
FMT_TYPE_CONSTANT() [1/14]
detail::FMT_TYPE_CONSTANT (basic_string_view< Char > , string_type)
FMT_TYPE_CONSTANT() [2/14]
detail::FMT_TYPE_CONSTANT (bool , bool_type)
FMT_TYPE_CONSTANT() [3/14]
detail::FMT_TYPE_CONSTANT (Char , char_type)
FMT_TYPE_CONSTANT() [4/14]
detail::FMT_TYPE_CONSTANT (const Char * , cstring_type)
FMT_TYPE_CONSTANT() [5/14]
detail::FMT_TYPE_CONSTANT (const void * , pointer_type)
FMT_TYPE_CONSTANT() [6/14]
detail::FMT_TYPE_CONSTANT (double , double_type)
FMT_TYPE_CONSTANT() [7/14]
detail::FMT_TYPE_CONSTANT (float , float_type)
FMT_TYPE_CONSTANT() [8/14]
detail::FMT_TYPE_CONSTANT (int , int_type)
FMT_TYPE_CONSTANT() [9/14]
detail::FMT_TYPE_CONSTANT (int128_t , int128_type)
FMT_TYPE_CONSTANT() [10/14]
detail::FMT_TYPE_CONSTANT (long double , long_double_type)
FMT_TYPE_CONSTANT() [11/14]
detail::FMT_TYPE_CONSTANT (long long , long_long_type)
FMT_TYPE_CONSTANT() [12/14]
detail::FMT_TYPE_CONSTANT (uint128_t , uint128_type)
FMT_TYPE_CONSTANT() [13/14]
detail::FMT_TYPE_CONSTANT (unsigned long long , ulong_long_type)
FMT_TYPE_CONSTANT() [14/14]
detail::FMT_TYPE_CONSTANT (unsigned , uint_type)
format_decimal() [1/2]
template<typename Char , typename UInt > format_decimal_result< Char * > detail::format_decimal (Char * out, UInt value, int size) inline
Definition at line 1206 of file fmtlib_format.h.
{
    FMT_ASSERT( size >= count_digits( value ), "invalid digit count" );
    out += size;
    Char *end = out;
    while( value >= 100 ) {
        // Integer division is slow so do it for a group of two digits instead
        // of for every digit. The idea comes from the talk by Alexandrescu
        // "Three Optimization Tips for C++". See speed-test for a comparison.
        out -= 2;
        copy2( out, data::digits[value % 100] );
        value /= 100;
    }
    if( value < 10 ) {
        *--out = static_cast<Char>( '0' + value );
        return {out, end};
    }
    out -= 2;
    copy2( out, data::digits[value] );
    return {out, end};
}
References copy2(), count_digits(), FMT_ASSERT, and om_direction::size.
Referenced by format_int::format_unsigned().
format_decimal() [2/2]
template<typename Char , typename UInt , typename Iterator , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< Iterator > >::value) > format_decimal_result< Iterator > detail::format_decimal (Iterator out, UInt value, int size) inline
Definition at line 1231 of file fmtlib_format.h.
{
    // Buffer is large enough to hold all digits (digits10 + 1).
    Char buffer[digits10<UInt>() + 1];
    auto end = format_decimal( buffer, value, size ).end;
    return {out, detail::copy_str<Char>( buffer, end, out )};
}
References format_decimal(), and om_direction::size.
Referenced by format_decimal(), detail::int_writer< OutputIt, Char, UInt >::on_num(), and write_significand().
format_error_code()
FMT_API void detail::format_error_code (detail::buffer< char > & out, int error_code, string_view message)
Definition at line 152 of file fmtlib_format-inl.h.
{
    // Report error code making sure that the output fits into
    // inline_buffer_size to avoid dynamic memory allocation and potential
    // bad_alloc.
    out.try_resize( 0 );
    static const char SEP[] = ": ";
    static const char ERROR_STR[] = "error ";
    // Subtract 2 to account for terminating null characters in SEP and ERROR_STR.
    size_t error_code_size = sizeof( SEP ) + sizeof( ERROR_STR ) - 2;
    auto abs_value = static_cast<uint32_or_64_or_128_t<int>>( error_code );
    if( detail::is_negative( error_code ) )
    {
        abs_value = 0 - abs_value;
        ++error_code_size;
    }
    error_code_size += detail::to_unsigned( detail::count_digits( abs_value ) );
    auto it = buffer_appender<char>( out );
    if( message.size() <= inline_buffer_size - error_code_size )
    {
        format_to( it, "{}{}", message, SEP );
    }
    format_to( it, "{}{}", ERROR_STR, error_code );
    assert( out.size() <= inline_buffer_size );
}
References count_digits(), format_to(), inline_buffer_size, is_negative(), mapgen_defer::message, and to_unsigned().
Referenced by format_system_error().
format_float() [1/2]
template<typename T > int detail::format_float (char * buf, std::size_t size, const char * format, int precision, T value)
Definition at line 15 of file fmtlib_format.cpp.
{
#ifdef FMT_FUZZ
    if( precision > 100000 )
        throw std::runtime_error(
            "fuzz mode - avoid large allocation inside snprintf" );
#endif
    // Suppress the warning about nonliteral format string.
    int ( *snprintf_ptr )( char *, size_t, const char *, ... ) = FMT_SNPRINTF;
    return precision < 0 ? snprintf_ptr( buf, size, format, value )
           : snprintf_ptr( buf, size, format, precision, value );
}
References FMT_SNPRINTF, format(), and om_direction::size.
format_float() [2/2]
template<typename T > int detail::format_float (T value, int precision, float_specs specs, buffer< char > & buf)
Definition at line 2648 of file fmtlib_format-inl.h.
{
    static_assert( !std::is_same<T, float>::value, "" );
    FMT_ASSERT( value >= 0, "value is negative" );
    const bool fixed = specs.format == float_format::fixed;
    if( value <= 0 ) { // <= instead of == to silence a warning.
        if( precision <= 0 || !fixed ) {
            buf.push_back( '0' );
            return 0;
        }
        buf.try_resize( to_unsigned( precision ) );
        std::uninitialized_fill_n( buf.data(), precision, '0' );
        return -precision;
    }
    if( !specs.use_grisu ) {
        return snprintf_float( value, precision, specs, buf );
    }
    if( precision < 0 ) {
        // Use Dragonbox for the shortest format.
        if( specs.binary32 ) {
            auto dec = dragonbox::to_decimal( static_cast<float>( value ) );
            write<char>( buffer_appender<char>( buf ), dec.significand );
            return dec.exponent;
        }
        auto dec = dragonbox::to_decimal( static_cast<double>( value ) );
        write<char>( buffer_appender<char>( buf ), dec.significand );
        return dec.exponent;
    }
    // Use Grisu + Dragon4 for the given precision:
    // https://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf.
    int exp = 0;
    const int min_exp = -60;  // alpha in Grisu.
    int cached_exp10 = 0;     // K in Grisu.
    fp normalized = normalize( fp( value ) );
    const auto cached_pow = get_cached_power(
                                min_exp - ( normalized.e + fp::significand_size ), cached_exp10 );
    normalized = normalized * cached_pow;
    // Limit precision to the maximum possible number of significant digits in an
    // IEEE754 double because we don't need to generate zeros.
    const int max_double_digits = 767;
    if( precision > max_double_digits ) {
        precision = max_double_digits;
    }
    fixed_handler handler{buf.data(), 0, precision, -cached_exp10, fixed};
    if( grisu_gen_digits( normalized, 1, exp, handler ) == digits::error ) {
        exp += handler.size - cached_exp10 - 1;
        fallback_format( value, handler.precision, specs.binary32, buf, exp );
    } else {
        exp += handler.exp10;
        buf.try_resize( to_unsigned( handler.size ) );
    }
    if( !fixed && !specs.showpoint ) {
        // Remove trailing zeros.
        auto num_digits = buf.size();
        while( num_digits > 0 && buf[num_digits - 1] == '0' ) {
            --num_digits;
            ++exp;
        }
        buf.try_resize( num_digits );
    }
    return exp;
}  // namespace detail
References detail::float_specs::binary32, detail::buffer< T >::data(), detail::fp::e, detail::digits::error, exp, fallback_format(), fixed, FMT_ASSERT, detail::float_specs::format, get_cached_power(), grisu_gen_digits(), normalize(), detail::buffer< T >::push_back(), detail::float_specs::showpoint, detail::fp::significand_size, detail::buffer< T >::size(), snprintf_float(), detail::dragonbox::to_decimal(), to_unsigned(), detail::buffer< T >::try_resize(), and detail::float_specs::use_grisu.
format_float< double >()
template int detail::format_float< double > (double value, int precision, float_specs specs, buffer< char > & buf)
format_float< long double >()
template int detail::format_float< long double > (long double value, int precision, float_specs specs, buffer< char > & buf)
format_uint() [1/3]
template<unsigned BASE_BITS, typename Char > Char * detail::format_uint (Char * buffer, detail::fallback_uintptr n, int num_digits, bool = false)
Definition at line 1256 of file fmtlib_format.h.
{
    auto char_digits = std::numeric_limits<unsigned char>::digits / 4;
    int start = ( num_digits + char_digits - 1 ) / char_digits - 1;
    if( int start_digits = num_digits % char_digits ) {
        unsigned value = n.value[start--];
        buffer = format_uint<BASE_BITS>( buffer, value, start_digits );
    }
    for( ; start >= 0; --start ) {
        unsigned value = n.value[start];
        buffer += char_digits;
        auto p = buffer;
        for( int i = 0; i < char_digits; ++i ) {
            unsigned digit = ( value & ( ( 1 << BASE_BITS ) - 1 ) );
            *--p = static_cast<Char>( data::hex_digits[digit] );
            value >>= BASE_BITS;
        }
    }
    return buffer;
}
References detail::fallback_uintptr::value.
format_uint() [2/3]
template<unsigned BASE_BITS, typename Char , typename UInt > Char * detail::format_uint (Char * buffer, UInt value, int num_digits, bool upper = false) inline
Definition at line 1241 of file fmtlib_format.h.
{
    buffer += num_digits;
    Char *end = buffer;
    do {
        const char *digits = upper ? "0123456789ABCDEF" : data::hex_digits;
        unsigned digit = ( value & ( ( 1 << BASE_BITS ) - 1 ) );
        *--buffer = static_cast<Char>( BASE_BITS < 4 ? static_cast<char>( '0' + digit )
                                       : digits[digit] );
    } while( ( value >>= BASE_BITS ) != 0 );
    return end;
}
format_uint() [3/3]
template<unsigned BASE_BITS, typename Char , typename It , typename UInt > It detail::format_uint (It out, UInt value, int num_digits, bool upper = false) inline
Definition at line 1279 of file fmtlib_format.h.
{
    if( auto ptr = to_pointer<Char>( out, to_unsigned( num_digits ) ) ) {
        format_uint<BASE_BITS>( ptr, value, num_digits, upper );
        return out;
    }
    // Buffer should be large enough to hold all digits (digits / BASE_BITS + 1).
    char buffer[num_bits<UInt>() / BASE_BITS + 1];
    format_uint<BASE_BITS>( buffer, value, num_digits, upper );
    return detail::copy_str<Char>( buffer, buffer + num_digits, out );
}
References ptr(), and to_unsigned().
format_value()
template<typename Char , typename T > void detail::format_value (buffer< Char > & buf, const T & value, locale_ref loc = locale_ref())
Definition at line 113 of file fmtlib_ostream.h.
{
    formatbuf<Char> format_buf( buf );
    std::basic_ostream<Char> output( &format_buf );
#if !defined(FMT_STATIC_THOUSANDS_SEPARATOR)
    if( loc ) {
        output.imbue( loc.get<std::locale>() );
    }
#endif
    output << value;
    output.exceptions( std::ios_base::failbit | std::ios_base::badbit );
    buf.try_resize( buf.size() );
}
References detail::buffer< T >::size(), and detail::buffer< T >::try_resize().
Referenced by detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format(), and printf_formatter< T >::format().
fwrite_fully()
void detail::fwrite_fully (const void * ptr, size_t size, size_t count, FILE * stream) inline
Definition at line 189 of file fmtlib_format-inl.h.
{
    size_t written = std::fwrite( ptr, size, count, stream );
    if( written < count ) {
        FMT_THROW( system_error( errno, "cannot write to file" ) );
    }
}
References count(), FMT_THROW, ptr(), and om_direction::size.
Referenced by vprint().
get_arg()
template<typename Context , typename ID > FMT_CONSTEXPR Context::format_arg detail::get_arg (Context & ctx, ID id)
Definition at line 2935 of file fmtlib_format.h.
{
    auto arg = ctx.arg( id );
    if( !arg ) {
        ctx.on_error( "argument not found" );
    }
    return arg;
}
References arg().
Referenced by basic_printf_context< OutputIt, Char >::format(), detail::specs_handler< ParseContext, Context >::get_arg(), basic_printf_context< OutputIt, Char >::get_arg(), detail::specs_handler< ParseContext, Context >::on_dynamic_precision(), detail::specs_handler< ParseContext, Context >::on_dynamic_width(), detail::format_handler< OutputIt, Char, Context >::on_format_specs(), detail::format_handler< OutputIt, Char, Context >::on_replacement_field(), and basic_printf_context< OutputIt, Char >::parse_header().
get_buffer() [1/2]
template<typename T > buffer< T > & detail::get_buffer (buffer_appender< T >)
get_buffer() [2/2]
template<typename T , typename OutputIt > iterator_buffer< OutputIt, T > detail::get_buffer (OutputIt)
get_buffer_init() [1/2]
template<typename T > buffer< T > & detail::get_buffer_init (buffer_appender< T > out)
Definition at line 975 of file fmtlib_core.h.
{
    return get_container( out );
}
References get_container().
get_buffer_init() [2/2]
template<typename OutputIt > OutputIt detail::get_buffer_init (OutputIt out)
Definition at line 971 of file fmtlib_core.h.
{
    return out;
}
Referenced by vformat_to().
get_cached_power()
fp detail::get_cached_power (int min_exponent, int & pow10_exponent) inline
Definition at line 1270 of file fmtlib_format-inl.h.
{
    const int shift = 32;
    const auto significand = static_cast<int64_t>( data::log10_2_significand );
    int index = static_cast<int>(
                    ( ( min_exponent + fp::significand_size - 1 ) * ( significand >> shift ) +
                      ( ( int64_t( 1 ) << shift ) - 1 ) ) // ceil
                    >> 32                          // arithmetic shift
                );
    // Decimal exponent of the first (smallest) cached power of 10.
    const int first_dec_exp = -348;
    // Difference between 2 consecutive decimal exponents in cached powers of 10.
    const int dec_exp_step = 8;
    index = ( index - first_dec_exp - 1 ) / dec_exp_step + 1;
    pow10_exponent = first_dec_exp + index * dec_exp_step;
    return {data::grisu_pow10_significands[index],
            data::grisu_pow10_exponents[index]};
}
References detail::basic_data< T >::grisu_pow10_exponents, detail::basic_data< T >::grisu_pow10_significands, index, detail::basic_data< T >::log10_2_significand, and detail::fp::significand_size.
Referenced by format_float(), detail::dragonbox::shorter_interval_case(), and detail::dragonbox::to_decimal().
get_container()
template<typename Container > Container & detail::get_container (std::back_insert_iterator< Container > it) inline
Definition at line 693 of file fmtlib_core.h.
{
    using bi_iterator = std::back_insert_iterator<Container>;
    struct accessor : bi_iterator {
        accessor( bi_iterator iter ) : bi_iterator( iter ) {}
        using bi_iterator::container;
    };
    return *accessor( it ).container;
}
Referenced by printf_formatter< T >::format(), get_buffer_init(), reserve(), to_pointer(), and write().
get_current_language_version()
int detail::get_current_language_version ()
Definition at line 18 of file translations.cpp.
{
    return current_language_version;
}
References current_language_version.
Referenced by translatable_mod_info::description(), translatable_mod_info::name(), detail::local_translation_cache< const char * >::operator()(), detail::local_translation_cache< std::string >::operator()(), and translatable_mod_info::update().
get_data() [1/2]
template<typename Container > Container::value_type * detail::get_data (Container & c) inline
Definition at line 386 of file fmtlib_format.h.
{
    return c.data();
}
References c.
get_data() [2/2]
template<typename Char > Char * detail::get_data (std::basic_string< Char > & s) inline
Definition at line 381 of file fmtlib_format.h.
{
    return &s[0];
}
Referenced by reserve().
get_dynamic_spec()
template<template< typename > class Handler, typename FormatArg , typename ErrorHandler > FMT_CONSTEXPR int detail::get_dynamic_spec (FormatArg arg, ErrorHandler eh)
Definition at line 2923 of file fmtlib_format.h.
{
    unsigned long long value = visit_format_arg( Handler<ErrorHandler>( eh ), arg );
    if( value > to_unsigned( max_value<int>() ) ) {
        eh.on_error( "number is too big" );
    }
    return static_cast<int>( value );
}
References arg(), to_unsigned(), and visit_format_arg().
get_iterator() [1/2]
template<typename Buffer > auto detail::get_iterator (Buffer & buf) -> decltype(buf.out())
Definition at line 981 of file fmtlib_core.h.
{
    return buf.out();
}
Referenced by vformat_to().
get_iterator() [2/2]
template<typename T > buffer_appender< T > detail::get_iterator (buffer< T > & buf)
Definition at line 985 of file fmtlib_core.h.
{
    return buffer_appender<T>( buf );
}
get_local_translation_cache() [1/2]
static local_translation_cache< const char * > detail::get_local_translation_cache (const char *) inline static
Definition at line 103 of file translations.h.
{
    return local_translation_cache<const char *>();
}
get_local_translation_cache() [2/2]
static local_translation_cache< std::string > detail::get_local_translation_cache (const std::string &) inline static
Definition at line 107 of file translations.h.
{
    return local_translation_cache<std::string>();
}
get_round_direction()
round_direction detail::get_round_direction (uint64_t divisor, uint64_t remainder, uint64_t error) inline
Definition at line 1606 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( remainder < divisor, "" ); // divisor - remainder won't overflow.
    FMT_ASSERT( error < divisor, "" );    // divisor - error won't overflow.
    FMT_ASSERT( error < divisor - error, "" ); // error * 2 won't overflow.
    // Round down if (remainder + error) * 2 <= divisor.
    if( remainder <= divisor - remainder && error * 2 <= divisor - remainder * 2 ) {
        return round_direction::down;
    }
    // Round up if (remainder - error) * 2 >= divisor.
    if( remainder >= error &&
        remainder - error >= divisor - ( remainder - error ) ) {
        return round_direction::up;
    }
    return round_direction::unknown;
}
References down, detail::digits::error, FMT_ASSERT, unknown, and up.
Referenced by detail::fixed_handler::on_digit(), and detail::fixed_handler::on_start().
get_significand_size() [1/2]
int detail::get_significand_size (const big_decimal_fp & fp) inline
Definition at line 1986 of file fmtlib_format.h.
{
    return fp.significand_size;
}
References detail::fp::significand_size.
get_significand_size() [2/2]
template<typename T > int detail::get_significand_size (const dragonbox::decimal_fp< T > & fp) inline
Definition at line 1991 of file fmtlib_format.h.
{
    return count_digits( fp.significand );
}
References count_digits().
Referenced by write_float().
grisu_gen_digits()
template<typename Handler > FMT_ALWAYS_INLINE digits::result detail::grisu_gen_digits (fp value, uint64_t error, int & exp, Handler & handler)
Definition at line 1637 of file fmtlib_format-inl.h.
{
    const fp one( 1ULL << -value.e, value.e );
    // The integral part of scaled value (p1 in Grisu) = value / one. It cannot be
    // zero because it contains a product of two 64-bit numbers with MSB set (due
    // to normalization) - 1, shifted right by at most 60 bits.
    auto integral = static_cast<uint32_t>( value.f >> -one.e );
    FMT_ASSERT( integral != 0, "" );
    FMT_ASSERT( integral == value.f >> -one.e, "" );
    // The fractional part of scaled value (p2 in Grisu) c = value % one.
    uint64_t fractional = value.f & ( one.f - 1 );
    exp = count_digits( integral ); // kappa in Grisu.
    // Divide by 10 to prevent overflow.
    auto result = handler.on_start( data::powers_of_10_64[exp - 1] << -one.e,
                                    value.f / 10, error * 10, exp );
    if( result != digits::more ) {
        return result;
    }
    // Generate digits for the integral part. This can produce up to 10 digits.
    do {
        uint32_t digit = 0;
        auto divmod_integral = [&]( uint32_t divisor ) {
            digit = integral / divisor;
            integral %= divisor;
        };
        // This optimization by Milo Yip reduces the number of integer divisions by
        // one per iteration.
        switch( exp ) {
            case 10:
                divmod_integral( 1000000000 );
                break;
            case 9:
                divmod_integral( 100000000 );
                break;
            case 8:
                divmod_integral( 10000000 );
                break;
            case 7:
                divmod_integral( 1000000 );
                break;
            case 6:
                divmod_integral( 100000 );
                break;
            case 5:
                divmod_integral( 10000 );
                break;
            case 4:
                divmod_integral( 1000 );
                break;
            case 3:
                divmod_integral( 100 );
                break;
            case 2:
                divmod_integral( 10 );
                break;
            case 1:
                digit = integral;
                integral = 0;
                break;
            default:
                FMT_ASSERT( false, "invalid number of digits" );
        }
        --exp;
        auto remainder = ( static_cast<uint64_t>( integral ) << -one.e ) + fractional;
        result = handler.on_digit( static_cast<char>( '0' + digit ),
                                   data::powers_of_10_64[exp] << -one.e, remainder,
                                   error, exp, true );
        if( result != digits::more ) {
            return result;
        }
    } while( exp > 0 );
    // Generate digits for the fractional part.
    for( ;; ) {
        fractional *= 10;
        error *= 10;
        char digit = static_cast<char>( '0' + ( fractional >> -one.e ) );
        fractional &= one.f - 1;
        --exp;
        result = handler.on_digit( digit, one.f, fractional, error, exp, false );
        if( result != digits::more ) {
            return result;
        }
    }
}
References count_digits(), detail::fp::e, detail::digits::error, exp, detail::fp::f, FMT_ASSERT, detail::digits::more, and detail::basic_data< T >::powers_of_10_64.
Referenced by format_float().
grouping()
template<typename Char > std::string detail::grouping (locale_ref loc) inline
Definition at line 1147 of file fmtlib_format.h.
{
    return grouping_impl<char>( loc );
}
References grouping_impl< char >().
grouping< wchar_t >()
template<> std::string detail::grouping< wchar_t > (locale_ref loc) inline
Definition at line 1151 of file fmtlib_format.h.
{
    return grouping_impl<wchar_t>( loc );
}
References grouping_impl< wchar_t >().
grouping_impl() [1/2]
template<typename Char > FMT_FUNC std::string detail::grouping_impl (locale_ref loc)
Definition at line 215 of file fmtlib_format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>( loc.get<std::locale>() ).grouping();
}
References detail::locale_ref::get().
grouping_impl() [2/2]
template<typename Char > FMT_API std::string detail::grouping_impl (locale_ref loc)
Definition at line 215 of file fmtlib_format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>( loc.get<std::locale>() ).grouping();
}
References detail::locale_ref::get().
grouping_impl< char >()
template FMT_API std::string detail::grouping_impl< char > (locale_ref loc)
Referenced by grouping().
grouping_impl< wchar_t >()
template FMT_API std::string detail::grouping_impl< wchar_t > (locale_ref loc)
Referenced by grouping< wchar_t >().
handle_char_specs()
template<typename Char , typename Handler > FMT_CONSTEXPR void detail::handle_char_specs (const basic_format_specs< Char > * specs, Handler && handler)
Definition at line 1608 of file fmtlib_format.h.
{
    if( !specs ) {
        return handler.on_char();
    }
    if( specs->type && specs->type != 'c' ) {
        return handler.on_int();
    }
    if( specs->align == align::numeric || specs->sign != sign::none || specs->alt ) {
        handler.on_error( "invalid format specifier for char" );
    }
    handler.on_char();
}
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, sign::none, align::numeric, basic_format_specs< Char >::sign, and basic_format_specs< Char >::type.
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), and formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
handle_cstring_type_spec()
template<typename Char , typename Handler > FMT_CONSTEXPR void detail::handle_cstring_type_spec (Char spec, Handler && handler)
Definition at line 1624 of file fmtlib_format.h.
{
    if( spec == 0 || spec == 's' ) {
        handler.on_string();
    } else if( spec == 'p' ) {
        handler.on_pointer();
    } else {
        handler.on_error( "invalid type specifier" );
    }
}
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), and formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
handle_dynamic_spec()
template<template< typename > class Handler, typename Context > void detail::handle_dynamic_spec (int & value, arg_ref< typename Context::char_type > ref, Context & ctx)
Definition at line 3702 of file fmtlib_format.h.
{
    switch( ref.kind ) {
        case arg_id_kind::none:
            break;
        case arg_id_kind::index:
            value = detail::get_dynamic_spec<Handler>( ctx.arg( ref.val.index ),
                    ctx.error_handler() );
            break;
        case arg_id_kind::name:
            value = detail::get_dynamic_spec<Handler>( ctx.arg( ref.val.name ),
                    ctx.error_handler() );
            break;
    }
}
References detail::arg_ref< Char >::value::index, detail::arg_ref< Char >::kind, detail::arg_ref< Char >::value::name, om_direction::name(), sign::none, and detail::arg_ref< Char >::val.
handle_int_type_spec()
template<typename Handler > FMT_CONSTEXPR void detail::handle_int_type_spec (char spec, Handler && handler)
Definition at line 1525 of file fmtlib_format.h.
{
    switch( spec ) {
        case 0:
        case 'd':
            handler.on_dec();
            break;
        case 'x':
        case 'X':
            handler.on_hex();
            break;
        case 'b':
        case 'B':
            handler.on_bin();
            break;
        case 'o':
            handler.on_oct();
            break;
#ifdef FMT_DEPRECATED_N_SPECIFIER
        case 'n':
#endif
        case 'L':
            handler.on_num();
            break;
        case 'c':
            handler.on_chr();
            break;
        default:
            handler.on_error();
    }
}
Referenced by detail::char_specs_checker< ErrorHandler >::on_int(), formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write_int().
init_named_args() [1/4]
template<typename Char > void detail::init_named_args (named_arg_info< Char > * , int , int) inline
Definition at line 1047 of file fmtlib_core.h.
{}
Referenced by format_arg_store< Context, Args >::format_arg_store(), and init_named_args().
init_named_args() [2/4]
template<typename Char , typename T , typename... Tail> void detail::init_named_args (named_arg_info< Char > * named_args, int arg_count, int named_arg_count, const named_arg< Char, T > & arg, const Tail &... args)
Definition at line 1057 of file fmtlib_core.h.
{
    named_args[named_arg_count++] = {arg.name, arg_count};
    init_named_args( named_args, arg_count + 1, named_arg_count, args... );
}
References arg(), and init_named_args().
init_named_args() [3/4]
template<typename Char , typename T , typename... Tail> void detail::init_named_args (named_arg_info< Char > * named_args, int arg_count, int named_arg_count, const T & , const Tail &... args)
Definition at line 1050 of file fmtlib_core.h.
{
    init_named_args( named_args, arg_count + 1, named_arg_count, args... );
}
References init_named_args().
init_named_args() [4/4]
template<typename... Args> FMT_INLINE void detail::init_named_args (std::nullptr_t , int , int , const Args & ...)
Definition at line 1066 of file fmtlib_core.h.
{}
is_arithmetic_type()
constexpr bool detail::is_arithmetic_type (type t) constexpr
Definition at line 1139 of file fmtlib_core.h.
{
    return t > type::none_type && t <= type::last_numeric_type;
}
References last_numeric_type, and none_type.
Referenced by basic_format_arg< Context >::is_arithmetic(), and detail::numeric_specs_checker< ErrorHandler >::require_numeric_argument().
is_ascii_letter()
template<typename Char > constexpr bool detail::is_ascii_letter (Char c) constexpr
Definition at line 3177 of file fmtlib_format.h.
{
    return ( c >= 'a' && c <= 'z' ) || ( c >= 'A' && c <= 'Z' );
}
References c.
Referenced by detail::format_handler< OutputIt, Char, Context >::on_format_specs().
is_big_endian()
bool detail::is_big_endian () inline
Definition at line 305 of file fmtlib_format.h.
{
    const auto u = 1u;
    struct bytes {
        char data[sizeof( u )];
    };
    return bit_cast<bytes>( u ).data[0] == 0;
}
Referenced by detail::fallback_uintptr::fallback_uintptr().
is_integral_type()
constexpr bool detail::is_integral_type (type t) constexpr
Definition at line 1134 of file fmtlib_core.h.
{
    return t > type::none_type && t <= type::last_integer_type;
}
References last_integer_type, and none_type.
Referenced by detail::numeric_specs_checker< ErrorHandler >::check_precision(), detail::numeric_specs_checker< ErrorHandler >::check_sign(), and basic_format_arg< Context >::is_integral().
is_name_start()
template<typename Char > FMT_CONSTEXPR bool detail::is_name_start (Char c)
Definition at line 2681 of file fmtlib_format.h.
{
    return ( 'a' <= c && c <= 'z' ) || ( 'A' <= c && c <= 'Z' ) || '_' == c;
}
References c.
Referenced by parse_arg_id().
is_negative()
template<typename T , FMT_ENABLE_IF(is_signed< T >::value) > FMT_CONSTEXPR bool detail::is_negative (T value)
Definition at line 899 of file fmtlib_format.h.
{
    return value < 0;
}
Referenced by format_error_code(), detail::int_writer< OutputIt, Char, UInt >::int_writer(), detail::width_checker< ErrorHandler >::operator()(), detail::precision_checker< ErrorHandler >::operator()(), and detail::printf_width_handler< Char >::operator()().
is_supported_floating_point()
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > FMT_CONSTEXPR bool detail::is_supported_floating_point (T)
Definition at line 910 of file fmtlib_format.h.
{
    return ( std::is_same<T, float>::value && FMT_USE_FLOAT ) ||
           ( std::is_same<T, double>::value && FMT_USE_DOUBLE ) ||
           ( std::is_same<T, long double>::value && FMT_USE_LONG_DOUBLE );
}
References FMT_USE_DOUBLE, FMT_USE_FLOAT, and FMT_USE_LONG_DOUBLE.
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), and write().
is_unicode()
template<typename Char > constexpr bool detail::is_unicode () constexpr
Definition at line 340 of file fmtlib_core.h.
{
    return FMT_UNICODE || sizeof( Char ) != 1 ||
           ( sizeof( micro ) == 3 && micro[0] == 0xC2 && micro[1] == 0xB5 );
}
References FMT_UNICODE.
make_arg() [1/3]
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(IS_PACKED) > value< Context > detail::make_arg (const T & val) inline
Definition at line 1628 of file fmtlib_core.h.
{
    return check<T>( arg_mapper<Context>().map( val ) );
}
make_arg() [2/3]
template<typename Context , typename T > FMT_CONSTEXPR basic_format_arg< Context > detail::make_arg (const T & value)
Definition at line 1602 of file fmtlib_core.h.
{
    basic_format_arg<Context> arg;
    arg.type_ = mapped_type_constant<T, Context>::value;
    arg.value_ = arg_mapper<Context>().map( value );
    return arg;
}
References arg(), and detail::arg_mapper< Context >::map().
make_arg() [3/3]
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(!IS_PACKED) > basic_format_arg< Context > detail::make_arg (const T & value) inline
Definition at line 1635 of file fmtlib_core.h.
{
    return make_arg<Context>( value );
}
make_checked()
template<typename T > T * detail::make_checked (T * p, size_t) inline
Definition at line 400 of file fmtlib_format.h.
{
    return p;
}
Referenced by detail::buffer< T >::append(), detail::bigint::assign(), basic_memory_buffer< T, SIZE, Allocator >::grow(), basic_memory_buffer< T, SIZE, Allocator >::move(), detail::int_writer< OutputIt, Char, UInt >::on_num(), and reserve().
max_value()
template<typename T > constexpr T detail::max_value () constexpr
Definition at line 344 of file fmtlib_format.h.
{
    return ( std::numeric_limits<T>::max )();
}
Referenced by display_stat(), and item::food_info().
multiply()
uint64_t detail::multiply (uint64_t lhs, uint64_t rhs) inline
Definition at line 1245 of file fmtlib_format-inl.h.
{
#if FMT_USE_INT128
    auto product = static_cast<__uint128_t>( lhs ) * rhs;
    auto f = static_cast<uint64_t>( product >> 64 );
    return ( static_cast<uint64_t>( product ) & ( 1ULL << 63 ) ) != 0 ? f + 1 : f;
#else
    // Multiply 32-bit parts of significands.
    uint64_t mask = ( 1ULL << 32 ) - 1;
    uint64_t a = lhs >> 32, b = lhs & mask;
    uint64_t c = rhs >> 32, d = rhs & mask;
    uint64_t ac = a * c, bc = b * c, ad = a * d, bd = b * d;
    // Compute mid 64-bit of result and round.
    uint64_t mid = ( bd >> 32 ) + ( ad & mask ) + ( bc & mask ) + ( 1U << 31 );
    return ac + ( ad >> 32 ) + ( bc >> 32 ) + ( mid >> 32 );
#endif
}
References a, b, and c.
Referenced by operator*().
normalize()
template<int SHIFT = 0> fp detail::normalize (fp value)
Definition at line 1223 of file fmtlib_format-inl.h.
{
    // Handle subnormals.
    const auto shifted_implicit_bit = fp::implicit_bit << SHIFT;
    while( ( value.f & shifted_implicit_bit ) == 0 ) {
        value.f <<= 1;
        --value.e;
    }
    // Subtract 1 to account for hidden bit.
    const auto offset =
        fp::significand_size - fp::double_significand_size - SHIFT - 1;
    value.f <<= offset;
    value.e -= offset;
    return value;
}
References detail::fp::double_significand_size, detail::fp::implicit_bit, and detail::fp::significand_size.
Referenced by format_float().
num_bits()
template<typename T > constexpr int detail::num_bits () constexpr
Definition at line 348 of file fmtlib_format.h.
{
    return std::numeric_limits<T>::digits;
}
num_bits< fallback_uintptr >()
template<> constexpr int detail::num_bits< fallback_uintptr > () constexpr
Definition at line 361 of file fmtlib_format.h.
{
    return static_cast<int>( sizeof( void * ) *
                             std::numeric_limits<unsigned char>::digits );
}
num_bits< int128_t >()
template<> constexpr int detail::num_bits< int128_t > () constexpr
Definition at line 353 of file fmtlib_format.h.
{
    return 128;
}
num_bits< uint128_t >()
template<> constexpr int detail::num_bits< uint128_t > () constexpr
Definition at line 357 of file fmtlib_format.h.
{
    return 128;
}
operator*()
fp detail::operator* (fp x, fp y) inline
Definition at line 1263 of file fmtlib_format-inl.h.
{
    return {multiply( x.f, y.f ), x.e + y.e + 64};
}
References detail::fp::e, detail::fp::f, and multiply().
operator<<() [1/5]
template<typename Char , typename Traits > void_t detail::operator<< (std::basic_ostream< Char, Traits > & , Char)
operator<<() [2/5]
template<typename Char , typename Traits > void_t detail::operator<< (std::basic_ostream< Char, Traits > & , char)
operator<<() [3/5]
template<typename Traits > void_t detail::operator<< (std::basic_ostream< char, Traits > & , char)
operator<<() [4/5]
template<typename Traits > void_t detail::operator<< (std::basic_ostream< char, Traits > & , signed char)
operator<<() [5/5]
template<typename Traits > void_t detail::operator<< (std::basic_ostream< char, Traits > & , unsigned char)
operator==()
bool detail::operator== (fp x, fp y) inline
Definition at line 1239 of file fmtlib_format-inl.h.
{
    return x.f == y.f && x.e == y.e;
}
References detail::fp::e, and detail::fp::f.
parse_align()
template<typename Char , typename Handler > FMT_CONSTEXPR const Char * detail::parse_align (const Char * begin, const Char * end, Handler && handler)
Definition at line 3196 of file fmtlib_format.h.
{
    FMT_ASSERT( begin != end, "" );
    auto align = align::none;
    auto p = begin + code_point_length( begin );
    if( p >= end ) {
        p = begin;
    }
    for( ;; ) {
        switch( to_ascii( *p ) ) {
            case '<':
                align = align::left;
                break;
            case '>':
                align = align::right;
                break;
#if FMT_DEPRECATED_NUMERIC_ALIGN
            case '=':
                align = align::numeric;
                break;
#endif
            case '^':
                align = align::center;
                break;
        }
        if( align != align::none ) {
            if( p != begin ) {
                auto c = *begin;
                if( c == '{' ) {
                    return handler.on_error( "invalid fill character '{'" ), begin;
                }
                handler.on_fill( basic_string_view<Char>( begin, to_unsigned( p - begin ) ) );
                begin = p + 1;
            } else {
                ++begin;
            }
            handler.on_align( align );
            break;
        } else if( p == begin ) {
            break;
        }
        p = begin;
    }
    return begin;
}
References c, align::center, code_point_length(), FMT_ASSERT, align::left, align::none, align::numeric, align::right, to_ascii(), and to_unsigned().
Referenced by parse_format_specs().
parse_arg_id()
template<typename Char , typename IDHandler > FMT_CONSTEXPR const Char * detail::parse_arg_id (const Char * begin, const Char * end, IDHandler && handler)
Definition at line 3083 of file fmtlib_format.h.
{
    FMT_ASSERT( begin != end, "" );
    Char c = *begin;
    if( c == '}' || c == ':' ) {
        handler();
        return begin;
    }
    if( c >= '0' && c <= '9' ) {
        int index = 0;
        if( c != '0' ) {
            index = parse_nonnegative_int( begin, end, handler );
        } else {
            ++begin;
        }
        if( begin == end || ( *begin != '}' && *begin != ':' ) ) {
            handler.on_error( "invalid format string" );
        } else {
            handler( index );
        }
        return begin;
    }
    if( !is_name_start( c ) ) {
        handler.on_error( "invalid format string" );
        return begin;
    }
    auto it = begin;
    do {
        ++it;
    } while( it != end && ( is_name_start( c = *it ) || ( '0' <= c && c <= '9' ) ) );
    handler( basic_string_view<Char>( begin, to_unsigned( it - begin ) ) );
    return it;
}
References c, FMT_ASSERT, index, is_name_start(), parse_nonnegative_int(), and to_unsigned().
Referenced by parse_precision(), parse_replacement_field(), and parse_width().
parse_float_type_spec()
template<typename ErrorHandler = error_handler, typename Char > FMT_CONSTEXPR float_specs detail::parse_float_type_spec (const basic_format_specs< Char > & specs, ErrorHandler && eh = {})
Definition at line 1558 of file fmtlib_format.h.
                                                                {} )
{
    auto result = float_specs();
    result.showpoint = specs.alt;
    switch( specs.type ) {
        case 0:
            result.format = float_format::general;
            result.showpoint |= specs.precision > 0;
            break;
        case 'G':
            result.upper = true;
            FMT_FALLTHROUGH;
        case 'g':
            result.format = float_format::general;
            break;
        case 'E':
            result.upper = true;
            FMT_FALLTHROUGH;
        case 'e':
            result.format = float_format::exp;
            result.showpoint |= specs.precision != 0;
            break;
        case 'F':
            result.upper = true;
            FMT_FALLTHROUGH;
        case 'f':
            result.format = float_format::fixed;
            result.showpoint |= specs.precision != 0;
            break;
        case 'A':
            result.upper = true;
            FMT_FALLTHROUGH;
        case 'a':
            result.format = float_format::hex;
            break;
#ifdef FMT_DEPRECATED_N_SPECIFIER
        case 'n':
#endif
        case 'L':
            result.locale = true;
            break;
        default:
            eh.on_error( "invalid type specifier" );
            break;
    }
    return result;
}
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
parse_format_specs() [1/2]
template<typename Char , typename SpecHandler > FMT_CONSTEXPR const Char * detail::parse_format_specs (const Char * begin, const Char * end, SpecHandler && handler)
Definition at line 3290 of file fmtlib_format.h.
{
    if( begin == end ) {
        return begin;
    }
    begin = parse_align( begin, end, handler );
    if( begin == end ) {
        return begin;
    }
    // Parse sign.
    switch( to_ascii( *begin ) ) {
        case '+':
            handler.on_plus();
            ++begin;
            break;
        case '-':
            handler.on_minus();
            ++begin;
            break;
        case ' ':
            handler.on_space();
            ++begin;
            break;
    }
    if( begin == end ) {
        return begin;
    }
    if( *begin == '#' ) {
        handler.on_hash();
        if( ++begin == end ) {
            return begin;
        }
    }
    // Parse zero flag.
    if( *begin == '0' ) {
        handler.on_zero();
        if( ++begin == end ) {
            return begin;
        }
    }
    begin = parse_width( begin, end, handler );
    if( begin == end ) {
        return begin;
    }
    // Parse precision.
    if( *begin == '.' ) {
        begin = parse_precision( begin, end, handler );
    }
    // Parse type.
    if( begin != end && *begin != '}' ) {
        handler.on_type( *begin++ );
    }
    return begin;
}
References parse_align(), parse_precision(), parse_width(), and to_ascii().
parse_format_specs() [2/2]
template<typename T , typename ParseContext > FMT_CONSTEXPR const ParseContext::char_type * detail::parse_format_specs (ParseContext & ctx)
Definition at line 3481 of file fmtlib_format.h.
{
    using char_type = typename ParseContext::char_type;
    using context = buffer_context<char_type>;
    using mapped_type =
        conditional_t < detail::mapped_type_constant<T, context>::value !=
        type::custom_type,
        decltype( arg_mapper<context>().map( std::declval<T>() ) ), T >;
    auto f = conditional_t<has_formatter<mapped_type, context>::value,
         formatter<mapped_type, char_type>,
         detail::fallback_formatter<T, char_type>>();
    return f.parse( ctx );
}
References char_type, and detail::arg_mapper< Context >::map().
Referenced by detail::format_handler< OutputIt, Char, Context >::on_format_specs(), formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), dynamic_formatter< Char >::parse(), and formatter< bytes >::parse().
parse_format_string()
template<bool IS_CONSTEXPR, typename Char , typename Handler > FMT_CONSTEXPR_DECL FMT_INLINE void detail::parse_format_string (basic_string_view< Char > format_str, Handler && handler)
Definition at line 3424 of file fmtlib_format.h.
{
    auto begin = format_str.data();
    auto end = begin + format_str.size();
    if( end - begin < 32 ) {
        // Use a simple loop instead of memchr for small strings.
        const Char *p = begin;
        while( p != end ) {
            auto c = *p++;
            if( c == '{' ) {
                handler.on_text( begin, p - 1 );
                begin = p = parse_replacement_field( p - 1, end, handler );
            } else if( c == '}' ) {
                if( p == end || *p != '}' ) {
                    return handler.on_error( "unmatched '}' in format string" );
                }
                handler.on_text( begin, p );
                begin = ++p;
            }
        }
        handler.on_text( begin, end );
        return;
    }
    struct writer {
        FMT_CONSTEXPR void operator()( const Char *pbegin, const Char *pend ) {
            if( pbegin == pend ) {
                return;
            }
            for( ;; ) {
                const Char *p = nullptr;
                if( !find<IS_CONSTEXPR>( pbegin, pend, '}', p ) ) {
                    return handler_.on_text( pbegin, pend );
                }
                ++p;
                if( p == pend || *p != '}' ) {
                    return handler_.on_error( "unmatched '}' in format string" );
                }
                handler_.on_text( pbegin, p );
                pbegin = p + 1;
            }
        }
        Handler &handler_;
    } write{handler};
    while( begin != end ) {
        // Doing two passes with memchr (one for '{' and another for '}') is up to
        // 2.5x faster than the naive one-pass implementation on big format strings.
        const Char *p = begin;
        if( *begin != '{' && !find<IS_CONSTEXPR>( begin + 1, end, '{', p ) ) {
            return write( begin, end );
        }
        write( begin, p );
        begin = parse_replacement_field( p, end, handler );
    }
}
References c, basic_string_view< Char >::data(), FMT_CONSTEXPR, parse_replacement_field(), basic_string_view< Char >::size(), and write().
parse_nonnegative_int()
template<typename Char , typename ErrorHandler > FMT_CONSTEXPR int detail::parse_nonnegative_int (const Char *& begin, const Char * end, ErrorHandler && eh)
Definition at line 2689 of file fmtlib_format.h.
{
    FMT_ASSERT( begin != end && '0' <= *begin && *begin <= '9', "" );
    unsigned value = 0;
    // Convert to unsigned to prevent a warning.
    constexpr unsigned max_int = max_value<int>();
    unsigned big = max_int / 10;
    do {
        // Check for overflow.
        if( value > big ) {
            value = max_int + 1;
            break;
        }
        value = value * 10 + unsigned( *begin - '0' );
        ++begin;
    } while( begin != end && '0' <= *begin && *begin <= '9' );
    if( value > max_int ) {
        eh.on_error( "number is too big" );
    }
    return static_cast<int>( value );
}
References FMT_ASSERT.
Referenced by basic_printf_context< OutputIt, Char >::format(), parse_arg_id(), basic_printf_context< OutputIt, Char >::parse_header(), parse_precision(), and parse_width().
parse_precision()
template<typename Char , typename Handler > FMT_CONSTEXPR const Char * detail::parse_precision (const Char * begin, const Char * end, Handler && handler)
Definition at line 3264 of file fmtlib_format.h.
{
    ++begin;
    auto c = begin != end ? *begin : Char();
    if( '0' <= c && c <= '9' ) {
        handler.on_precision( parse_nonnegative_int( begin, end, handler ) );
    } else if( c == '{' ) {
        ++begin;
        if( begin != end ) {
            begin =
                parse_arg_id( begin, end, precision_adapter<Handler, Char>( handler ) );
        }
        if( begin == end || *begin++ != '}' ) {
            return handler.on_error( "invalid format string" ), begin;
        }
    } else {
        return handler.on_error( "missing precision specifier" ), begin;
    }
    handler.end_precision();
    return begin;
}
References c, parse_arg_id(), and parse_nonnegative_int().
Referenced by parse_format_specs().
parse_replacement_field()
template<typename Char , typename Handler > FMT_CONSTEXPR const Char * detail::parse_replacement_field (const Char * begin, const Char * end, Handler && handler)
Definition at line 3393 of file fmtlib_format.h.
{
    ++begin;
    if( begin == end ) {
        return handler.on_error( "invalid format string" ), end;
    }
    if( *begin == '}' ) {
        handler.on_replacement_field( handler.on_arg_id(), begin );
    } else if( *begin == '{' ) {
        handler.on_text( begin, begin + 1 );
    } else {
        auto adapter = id_adapter<Handler, Char> {handler, 0};
        begin = parse_arg_id( begin, end, adapter );
        Char c = begin != end ? *begin : Char();
        if( c == '}' ) {
            handler.on_replacement_field( adapter.arg_id, begin );
        } else if( c == ':' ) {
            begin = handler.on_format_specs( adapter.arg_id, begin + 1, end );
            if( begin == end || *begin != '}' ) {
                return handler.on_error( "unknown format specifier" ), end;
            }
        } else {
            return handler.on_error( "missing '}' in format string" ), end;
        }
    }
    return begin + 1;
}
References c, and parse_arg_id().
Referenced by parse_format_string().
parse_width()
template<typename Char , typename Handler > FMT_CONSTEXPR const Char * detail::parse_width (const Char * begin, const Char * end, Handler && handler)
Definition at line 3244 of file fmtlib_format.h.
{
    FMT_ASSERT( begin != end, "" );
    if( '0' <= *begin && *begin <= '9' ) {
        handler.on_width( parse_nonnegative_int( begin, end, handler ) );
    } else if( *begin == '{' ) {
        ++begin;
        if( begin != end ) {
            begin = parse_arg_id( begin, end, width_adapter<Handler, Char>( handler ) );
        }
        if( begin == end || *begin != '}' ) {
            return handler.on_error( "invalid format string" ), begin;
        }
        ++begin;
    }
    return begin;
}
References FMT_ASSERT, parse_arg_id(), and parse_nonnegative_int().
Referenced by parse_format_specs().
promote_float() [1/2]
double detail::promote_float (float value) inline
Definition at line 1519 of file fmtlib_format.h.
{
    return static_cast<double>( value );
}
promote_float() [2/2]
template<typename T > T detail::promote_float (T value)
Definition at line 1515 of file fmtlib_format.h.
{
    return value;
}
realDebugLog()
detail::DebugLogGuard detail::realDebugLog (DL lev, DC cl, const char * filename, const char * line, const char * funcname)
Definition at line 1158 of file debug.cpp.
{
    if( lev == DL::Error ) {
        error_observed = true;
    }
    if( checkDebugLevelClass( lev, cl ) ) {
        std::ostream &out = debugFile().get_file();
        output_repetitions( out );
        out << get_time() << " ";
        out << io::enum_to_string<DL>( lev ) << " ";
        if( cl != DC::Main ) {
            out << io::enum_to_string<DC>( cl ) << " ";
        }
        out << ": ";
        if( filename ) {
            out << filename;
            if( line ) {
                out << ":" << line;
            }
            if( funcname ) {
                out << " ";
            } else {
                out << ": ";
            }
        }
        if( funcname ) {
            out << "[" << funcname << "] ";
        }
        // Backtrace on error.
#if defined(BACKTRACE)
        // Push the first retrieved value back by a second so it won't match.
        static time_t next_backtrace = time( nullptr ) - 1;
        time_t now = time( nullptr );
        if( lev == DL::Error && now >= next_backtrace ) {
            out << "(error message will follow backtrace)";
            debug_write_backtrace( out );
            time_t after = time( nullptr );
            // Cool down for 60s between backtrace emissions.
            next_backtrace = after + 60;
            out << "Backtrace emission took " << after - now << " seconds." << std::endl;
        }
#endif
        return DebugLogGuard( out );
    }
    static NullBuf nullBuf;
    static std::ostream nullStream( &nullBuf );
    return DebugLogGuard( nullStream );
}
References checkDebugLevelClass(), debugFile(), io::enum_to_string< DC >(), io::enum_to_string< DL >(), Error, error_observed, DebugFile::get_file(), get_time(), line(), Main, output_repetitions(), and time.
Referenced by realDebugmsg().
report_error()
FMT_API void detail::report_error (format_func func, int error_code, string_view message)
Definition at line 179 of file fmtlib_format-inl.h.
{
    memory_buffer full_message;
    func( full_message, error_code, message );
    // Don't use fwrite_fully because the latter may throw.
    ( void )std::fwrite( full_message.data(), full_message.size(), 1, stderr );
    std::fputc( '\n', stderr );
}
References detail::buffer< T >::data(), mapgen_defer::message, and detail::buffer< T >::size().
Referenced by report_system_error().
reserve() [1/3]
template<typename T > buffer_appender< T > detail::reserve (buffer_appender< T > it, size_t n) inline
Definition at line 420 of file fmtlib_format.h.
{
    buffer<T> &buf = get_container( it );
    buf.try_reserve( buf.size() + n );
    return it;
}
References get_container(), detail::buffer< T >::size(), and detail::buffer< T >::try_reserve().
reserve() [2/3]
template<typename Iterator > Iterator & detail::reserve (Iterator & it, size_t) inline
Definition at line 427 of file fmtlib_format.h.
{
    return it;
}
Referenced by detail::format_handler< OutputIt, Char, Context >::on_text(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), write(), write_bytes(), write_char(), write_float(), write_int(), write_nonfinite(), write_padded(), and write_ptr().
reserve() [3/3]
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) > checked_ptr< typename Container::value_type > detail::reserve (std::back_insert_iterator< Container > it, size_t n) inline
Definition at line 411 of file fmtlib_format.h.
{
    Container &c = get_container( it );
    size_t size = c.size();
    c.resize( size + n );
    return make_checked( get_data( c ) + size, n );
}
References c, get_container(), get_data(), make_checked(), and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::assign(), cata::list< element_type, element_allocator_type >::list(), cata::list< element_type, element_allocator_type >::operator=(), and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::reserve().
safe_strerror()
int detail::safe_strerror (int error_code, char *& buffer, size_t buffer_size) inline
Definition at line 81 of file fmtlib_format-inl.h.
{
    FMT_ASSERT( buffer != nullptr &&buffer_size != 0, "invalid buffer" );
    class dispatcher {
        private:
            int error_code_;
            char *&buffer_;
            size_t buffer_size_;
            // A noop assignment operator to avoid bogus warnings.
            void operator=( const dispatcher & ) {}
            // Handle the result of XSI-compliant version of strerror_r.
            int handle( int result )
            {
                // glibc versions before 2.13 return result in errno.
                return result == -1 ? errno : result;
            }
            // Handle the result of GNU-specific version of strerror_r.
            FMT_MAYBE_UNUSED
            int handle( char *message )
            {
                // If the buffer is full then the message is probably truncated.
                if( message == buffer_ && strlen( buffer_ ) == buffer_size_ - 1 ) {
                    return ERANGE;
                }
                buffer_ = message;
                return 0;
            }
            // Handle the case when strerror_r is not available.
            FMT_MAYBE_UNUSED
            int handle( detail::null<> )
            {
                return fallback( strerror_s( buffer_, buffer_size_, error_code_ ) );
            }
            // Fallback to strerror_s when strerror_r is not available.
            FMT_MAYBE_UNUSED
            int fallback( int result )
            {
                // If the buffer is full then the message is probably truncated.
                return result == 0 && strlen( buffer_ ) == buffer_size_ - 1 ? ERANGE
                       : result;
            }
#if !FMT_MSC_VER
            // Fallback to strerror if strerror_r and strerror_s are not available.
            int fallback( detail::null<> )
            {
                errno = 0;
                buffer_ = strerror( error_code_ );
                return errno;
            }
#endif
        public:
            dispatcher( int err_code, char *&buf, size_t buf_size )
                : error_code_( err_code ), buffer_( buf ), buffer_size_( buf_size ) {}
            int run()
            {
                return handle( strerror_r( error_code_, buffer_, buffer_size_ ) );
            }
    };
    return dispatcher( error_code, buffer, buffer_size ).run();
}
References FMT_ASSERT, FMT_MAYBE_UNUSED, mapgen_defer::message, examine_item_menu::run(), strerror_r(), and strerror_s().
Referenced by format_system_error().
show_mutations_ui_internal()
detail::mutations_ui_result detail::show_mutations_ui_internal (Character & who)
Total required height is: top frame line: + 1 height of title window: + TITLE_HEIGHT line after the title: + 1 line with active/passive mutation captions: + 1 height of the biggest list of active/passive mutations: + mutations_count line before mutation description: + 1 height of description window: + DESCRIPTION_HEIGHT bottom frame line: + 1 TOTAL: TITLE_HEIGHT + mutations_count + DESCRIPTION_HEIGHT + 5
Definition at line 124 of file mutation_ui.cpp.
{
    std::vector<trait_id> passive;
    std::vector<trait_id> active;
    for( std::pair<const trait_id, char_trait_data> &mut : who.my_mutations ) {
        if( !mut.first->activated && ! mut.first->transform ) {
            passive.push_back( mut.first );
        } else {
            active.push_back( mut.first );
        }
        // New mutations are initialized with no key at all, so we have to do this here.
        if( mut.second.key == ' ' ) {
            for( const auto &letter : mutation_chars ) {
                if( !trait_by_invlet( who.my_mutations, letter ) ) {
                    mut.second.key = letter;
                    break;
                }
            }
        }
    }
    // maximal number of rows in both columns
    const int mutations_count = std::max( passive.size(), active.size() );
    const int TITLE_HEIGHT = 2;
    const int DESCRIPTION_HEIGHT = 5;
    // + lines with text in titlebar, local
    const int HEADER_LINE_Y = TITLE_HEIGHT + 1;
    const int list_start_y = HEADER_LINE_Y + 2;
    // Main window
    /** Total required height is:
    * top frame line:                                         + 1
    * height of title window:                                 + TITLE_HEIGHT
    * line after the title:                                   + 1
    * line with active/passive mutation captions:               + 1
    * height of the biggest list of active/passive mutations:   + mutations_count
    * line before mutation description:                         + 1
    * height of description window:                           + DESCRIPTION_HEIGHT
    * bottom frame line:                                      + 1
    * TOTAL: TITLE_HEIGHT + mutations_count + DESCRIPTION_HEIGHT + 5
    */
    int HEIGHT = 0;
    int WIDTH = 0;
    catacurses::window wBio;
    int DESCRIPTION_LINE_Y = 0;
    catacurses::window w_description;
    catacurses::window w_title;
    int second_column = 0;
    int scroll_position = 0;
    int cursor = 0;
    int max_scroll_position = 0;
    int list_height = 0;
    int half_list_view_location = 0;
    mutation_menu_mode menu_mode = mutation_menu_mode::activating;
    mutation_tab_mode tab_mode;
    if( !passive.empty() ) {
        tab_mode = mutation_tab_mode::passive;
    } else if( !active.empty() ) {
        tab_mode = mutation_tab_mode::active;
    } else {
        tab_mode = mutation_tab_mode::none;
    }
    const auto recalc_max_scroll_position = [&]() {
        list_height = ( menu_mode == mutation_menu_mode::examining ?
                        DESCRIPTION_LINE_Y : HEIGHT - 1 ) - list_start_y;
        max_scroll_position = mutations_count - list_height;
        half_list_view_location = list_height / 2;
        if( max_scroll_position < 0 ) {
            scroll_position = 0;
        } else if( scroll_position > max_scroll_position ) {
            scroll_position = max_scroll_position;
        }
    };
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        HEIGHT = std::min( TERMY, std::max( FULL_SCREEN_HEIGHT,
                                            TITLE_HEIGHT + mutations_count + DESCRIPTION_HEIGHT + 5 ) );
        WIDTH = FULL_SCREEN_WIDTH + ( TERMX - FULL_SCREEN_WIDTH ) / 2;
        const point START( ( TERMX - WIDTH ) / 2, ( TERMY - HEIGHT ) / 2 );
        wBio = catacurses::newwin( HEIGHT, WIDTH, START );
        // Description window @ the bottom of the bionic window
        const int DESCRIPTION_START_Y = START.y + HEIGHT - DESCRIPTION_HEIGHT - 1;
        DESCRIPTION_LINE_Y = DESCRIPTION_START_Y - START.y - 1;
        w_description = catacurses::newwin( DESCRIPTION_HEIGHT, WIDTH - 2,
                                            point( START.x + 1, DESCRIPTION_START_Y ) );
        // Title window
        const int TITLE_START_Y = START.y + 1;
        w_title = catacurses::newwin( TITLE_HEIGHT, WIDTH - 2,
                                      point( START.x + 1, TITLE_START_Y ) );
        recalc_max_scroll_position();
        // X-coordinate of the list of active mutations
        second_column = 32 + ( TERMX - FULL_SCREEN_WIDTH ) / 4;
        ui.position_from_window( wBio );
    } );
    ui.mark_resize();
    input_context ctxt( "MUTATIONS" );
    ctxt.register_updown();
    ctxt.register_action( "ANY_INPUT" );
    ctxt.register_action( "TOGGLE_EXAMINE" );
    ctxt.register_action( "REASSIGN" );
    ctxt.register_action( "NEXT_TAB" );
    ctxt.register_action( "PREV_TAB" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ctxt.register_action( "QUIT" );
#if defined(__ANDROID__)
    for( const auto &p : passive ) {
        ctxt.register_manual_key( who.my_mutations[p].key, p.obj().name() );
    }
    for( const auto &a : active ) {
        ctxt.register_manual_key( who.my_mutations[a].key, a.obj().name() );
    }
#endif
    cata::optional<trait_id> examine_id;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( wBio );
        draw_border( wBio, BORDER_COLOR, _( " MUTATIONS " ) );
        // Draw line under title
        mvwhline( wBio, point( 1, HEADER_LINE_Y ), LINE_OXOX, WIDTH - 2 );
        // Draw symbols to connect additional lines to border
        mvwputch( wBio, point( 0, HEADER_LINE_Y ), BORDER_COLOR, LINE_XXXO ); // |-
        mvwputch( wBio, point( WIDTH - 1, HEADER_LINE_Y ), BORDER_COLOR, LINE_XOXX ); // -|
        // Captions
        mvwprintz( wBio, point( 2, HEADER_LINE_Y + 1 ), c_light_blue, _( "Passive:" ) );
        mvwprintz( wBio, point( second_column, HEADER_LINE_Y + 1 ), c_light_blue, _( "Active:" ) );
        if( menu_mode == mutation_menu_mode::examining ) {
            draw_exam_window( wBio, DESCRIPTION_LINE_Y );
        }
        nc_color type;
        if( passive.empty() ) {
            mvwprintz( wBio, point( 2, list_start_y ), c_light_gray, _( "None" ) );
        } else {
            for( int i = scroll_position; static_cast<size_t>( i ) < passive.size(); i++ ) {
                const mutation_branch &md = passive[i].obj();
                const char_trait_data &td = who.my_mutations[passive[i]];
                const bool is_highlighted = cursor == static_cast<int>( i );
                if( i - scroll_position == list_height ) {
                    break;
                }
                if( is_highlighted && tab_mode == mutation_tab_mode::passive ) {
                    type = who.has_base_trait( passive[i] ) ? c_cyan_yellow : c_light_cyan_yellow;
                } else {
                    type = who.has_base_trait( passive[i] ) ? c_cyan : c_light_cyan;
                }
                mvwprintz( wBio, point( 2, list_start_y + i - scroll_position ),
                           type, "%c %s", td.key, md.name() );
            }
        }
        if( active.empty() ) {
            mvwprintz( wBio, point( second_column, list_start_y ), c_light_gray, _( "None" ) );
        } else {
            for( int i = scroll_position; static_cast<size_t>( i ) < active.size(); i++ ) {
                const mutation_branch &md = active[i].obj();
                const char_trait_data &td = who.my_mutations[active[i]];
                const bool is_highlighted = cursor == static_cast<int>( i );
                if( i - scroll_position == list_height ) {
                    break;
                }
                if( td.powered ) {
                    if( is_highlighted && tab_mode == mutation_tab_mode::active ) {
                        type = who.has_base_trait( active[i] ) ? c_green_yellow : c_light_green_yellow;
                    } else {
                        type = who.has_base_trait( active[i] ) ? c_green : c_light_green;
                    }
                } else {
                    if( is_highlighted && tab_mode == mutation_tab_mode::active ) {
                        type = who.has_base_trait( active[i] ) ? c_red_yellow : c_light_red_yellow;
                    } else {
                        type = who.has_base_trait( active[i] ) ? c_red : c_light_red;
                    }
                }
                // TODO: track resource(s) used and specify
                mvwputch( wBio, point( second_column, list_start_y + i - scroll_position ),
                          type, td.key );
                std::string mut_desc;
                mut_desc += md.name();
                if( md.cost > 0 && md.cooldown > 0 ) {
                    //~ RU means Resource Units
                    mut_desc += string_format( _( " - %d RU / %d turns" ),
                                               md.cost, md.cooldown );
                } else if( md.cost > 0 ) {
                    //~ RU means Resource Units
                    mut_desc += string_format( _( " - %d RU" ), md.cost );
                } else if( md.cooldown > 0 ) {
                    mut_desc += string_format( _( " - %d turns" ), md.cooldown );
                }
                if( td.powered ) {
                    mut_desc += _( " - Active" );
                }
                mvwprintz( wBio, point( second_column + 2, list_start_y + i - scroll_position ),
                           type, mut_desc );
            }
        }
        draw_scrollbar( wBio, scroll_position, list_height, mutations_count,
                        point( 0, list_start_y ), c_white, true );
        wnoutrefresh( wBio );
        show_mutations_titlebar( w_title, menu_mode, ctxt );
        if( menu_mode == mutation_menu_mode::examining && examine_id.has_value() ) {
            werase( w_description );
            fold_and_print( w_description, point_zero, WIDTH - 2, c_light_blue, examine_id.value()->desc() );
            wnoutrefresh( w_description );
        }
    } );
    mutations_ui_result ret;
    bool exit = false;
    while( !exit ) {
        recalc_max_scroll_position();
        ui_manager::redraw();
        bool handled = false;
        const std::string action = ctxt.handle_input();
        const input_event evt = ctxt.get_raw_input();
        if( evt.type == CATA_INPUT_KEYBOARD && !evt.sequence.empty() ) {
            const int ch = evt.get_first_input();
            if( ch == ' ' ) { //skip if space is pressed (space is used as an empty hotkey)
                continue;
            }
            cata::optional<trait_id> mut_id = trait_by_invlet( who.my_mutations, ch );
            if( mut_id ) {
                const mutation_branch &mut_data = mut_id->obj();
                switch( menu_mode ) {
                    case mutation_menu_mode::reassigning: {
                        query_popup pop;
                        pop.message( _( "%s; enter new letter." ),
                                     mutation_branch::get_name( *mut_id ) )
                        .context( "POPUP_WAIT" )
                        .allow_cancel( true )
                        .allow_anykey( true );
                        bool pop_exit = false;
                        while( !pop_exit ) {
                            const query_popup::result ret = pop.query();
                            bool pop_handled = false;
                            if( ret.evt.type == CATA_INPUT_KEYBOARD && !ret.evt.sequence.empty() ) {
                                const int newch = ret.evt.get_first_input();
                                if( mutation_chars.valid( newch ) ) {
                                    const cata::optional<trait_id> other_mut_id = trait_by_invlet( who.my_mutations, newch );
                                    if( other_mut_id ) {
                                        std::swap( who.my_mutations[*mut_id].key, who.my_mutations[*other_mut_id].key );
                                    } else {
                                        who.my_mutations[*mut_id].key = newch;
                                    }
                                    pop_exit = true;
                                    pop_handled = true;
                                }
                            }
                            if( !pop_handled ) {
                                if( ret.action == "QUIT" ) {
                                    pop_exit = true;
                                } else if( ret.action != "HELP_KEYBINDINGS" &&
                                           ret.evt.type == CATA_INPUT_KEYBOARD ) {
                                    popup( _( "Invalid mutation letter.  Only those characters are valid:\n\n%s" ),
                                           mutation_chars.get_allowed_chars() );
                                }
                            }
                        }
                        menu_mode = mutation_menu_mode::activating;
                        examine_id = cata::nullopt;
                        // TODO: show a message like when reassigning a key to an item?
                        break;
                    }
                    case mutation_menu_mode::activating: {
                        const cata::value_ptr<mut_transform> &trans = mut_data.transform;
                        if( mut_data.activated || trans ) {
                            if( who.my_mutations[*mut_id].powered ) {
                                if( trans && !trans->msg_transform.empty() ) {
                                    who.add_msg_if_player( m_neutral, trans->msg_transform );
                                } else {
                                    who.add_msg_if_player( m_neutral, _( "You stop using your %s." ), mut_data.name() );
                                }
                                ret.cmd = mutations_ui_cmd::deactivate;
                                ret.mut = *mut_id;
                                exit = true;
                            } else if( can_use_mutation_warn( *mut_id, who ) ) {
                                if( trans && !trans->msg_transform.empty() ) {
                                    who.add_msg_if_player( m_neutral, trans->msg_transform );
                                } else {
                                    who.add_msg_if_player( m_neutral, _( "You activate your %s." ), mut_data.name() );
                                }
                                ret.cmd = mutations_ui_cmd::activate;
                                ret.mut = *mut_id;
                                exit = true;
                            } else {
                                popup( _( "You feel like using your %s would kill you!" ),
                                       mut_data.name() );
                            }
                        } else {
                            popup( _( "You cannot activate %s!  To read a description of "
                                      "%s, press '!', then '%c'." ),
                                   mut_data.name(), mut_data.name(), who.my_mutations[*mut_id].key );
                        }
                        break;
                    }
                    case mutation_menu_mode::examining:
                        // Describing mutations, not activating them!
                        examine_id = mut_id;
                        break;
                }
                handled = true;
            } else if( mutation_chars.valid( ch ) ) {
                handled = true;
            }
        }
        if( !handled ) {
            // Essentially, up-down navigation adapted from the bionics_ui.cpp, with a bunch of extra workarounds to keep functionality
            if( action == "DOWN" ) {
                int lowerlim;
                if( tab_mode == mutation_tab_mode::passive ) {
                    lowerlim = static_cast<int>( passive.size() ) - 1;
                } else if( tab_mode == mutation_tab_mode::active ) {
                    lowerlim = static_cast<int>( active.size() ) - 1;
                } else {
                    continue;
                }
                if( cursor < lowerlim ) {
                    cursor++;
                } else {
                    cursor = 0;
                }
                if( scroll_position < max_scroll_position &&
                    cursor - scroll_position > list_height - half_list_view_location ) {
                    scroll_position++;
                }
                if( scroll_position > 0 && cursor - scroll_position < half_list_view_location ) {
                    scroll_position = std::max( cursor - half_list_view_location, 0 );
                }
                // Draw the description, shabby workaround
                examine_id = GetTrait( active, passive, cursor, tab_mode );
            } else if( action == "UP" ) {
                int lim;
                if( tab_mode == mutation_tab_mode::passive ) {
                    lim = passive.size() - 1;
                } else if( tab_mode == mutation_tab_mode::active ) {
                    lim = active.size() - 1;
                } else {
                    continue;
                }
                if( cursor > 0 ) {
                    cursor--;
                } else {
                    cursor = lim;
                }
                if( scroll_position > 0 && cursor - scroll_position < half_list_view_location ) {
                    scroll_position--;
                }
                if( scroll_position < max_scroll_position &&
                    cursor - scroll_position > list_height - half_list_view_location ) {
                    scroll_position =
                        std::max( std::min<int>( lim + 1 - list_height,
                                                 cursor - half_list_view_location ), 0 );
                }
                examine_id = GetTrait( active, passive, cursor, tab_mode );
            } else if( action == "NEXT_TAB" || action == "PREV_TAB" ) {
                if( tab_mode == mutation_tab_mode::active && !passive.empty() ) {
                    tab_mode = mutation_tab_mode::passive;
                } else if( tab_mode == mutation_tab_mode::passive && !active.empty() ) {
                    tab_mode = mutation_tab_mode::active;
                } else {
                    continue;
                }
                examine_id = GetTrait( active, passive, cursor, tab_mode );
                scroll_position = 0;
                cursor = 0;
            } else if( action == "CONFIRM" ) {
                trait_id mut_id;
                if( tab_mode == mutation_tab_mode::active ) {
                    mut_id = active[cursor];
                } else if( tab_mode == mutation_tab_mode::passive ) {
                    mut_id = passive[cursor];
                } else {
                    continue;
                }
                if( !mut_id.is_null() ) {
                    const mutation_branch &mut_data = mut_id.obj();
                    switch( menu_mode ) {
                        case mutation_menu_mode::reassigning: {
                            query_popup pop;
                            pop.message( _( "%s; enter new letter." ),
                                         mutation_branch::get_name( mut_id ) )
                            .context( "POPUP_WAIT" )
                            .allow_cancel( true )
                            .allow_anykey( true );
                            bool pop_exit = false;
                            while( !pop_exit ) {
                                const query_popup::result ret = pop.query();
                                bool pop_handled = false;
                                if( ret.evt.type == CATA_INPUT_KEYBOARD && !ret.evt.sequence.empty() ) {
                                    const int newch = ret.evt.get_first_input();
                                    if( mutation_chars.valid( newch ) ) {
                                        const cata::optional<trait_id> other_mut_id = trait_by_invlet( who.my_mutations, newch );
                                        if( other_mut_id ) {
                                            std::swap( who.my_mutations[mut_id].key, who.my_mutations[*other_mut_id].key );
                                        } else {
                                            who.my_mutations[mut_id].key = newch;
                                        }
                                        pop_exit = true;
                                        pop_handled = true;
                                    } else if( newch == ' ' ) {
                                        who.my_mutations[mut_id].key = newch;
                                        pop_exit = true;
                                        pop_handled = true;
                                    }
                                }
                                if( !pop_handled ) {
                                    if( ret.action == "QUIT" ) {
                                        pop_exit = true;
                                    } else if( ret.action != "HELP_KEYBINDINGS" &&
                                               ret.evt.type == CATA_INPUT_KEYBOARD ) {
                                        popup( _( "Invalid mutation letter.  Only those characters are valid:\n\n%s" ),
                                               mutation_chars.get_allowed_chars() );
                                    }
                                }
                            }
                            menu_mode = mutation_menu_mode::activating;
                            examine_id = cata::nullopt;
                            // TODO: show a message like when reassigning a key to an item?
                            break;
                        }
                        case mutation_menu_mode::activating: {
                            if( mut_data.activated ) {
                                if( who.my_mutations[mut_id].powered ) {
                                    who.add_msg_if_player( m_neutral, _( "You stop using your %s." ), mut_data.name() );
                                    who.deactivate_mutation( mut_id );
                                    // Action done, leave screen
                                    exit = true;
                                } else if( ( !mut_data.hunger || who.get_kcal_percent() >= 0.8f ) &&
                                           ( !mut_data.thirst || who.get_thirst() <= 400 ) &&
                                           ( !mut_data.fatigue || who.get_fatigue() <= 400 ) ) {
                                    who.add_msg_if_player( m_neutral, _( "You activate your %s." ), mut_data.name() );
                                    who.activate_mutation( mut_id );
                                    // Action done, leave screen
                                    exit = true;
                                } else {
                                    popup( _( "You don't have enough in you to activate your %s!" ), mut_data.name() );
                                }
                            } else {
                                popup( _( "You cannot activate %s!  To read a description of "
                                          "%s, press '!', then '%c'." ),
                                       mut_data.name(), mut_data.name(), who.my_mutations[mut_id].key );
                            }
                            break;
                        }
                        case mutation_menu_mode::examining:
                            // Describing mutations, not activating them!
                            examine_id = mut_id;
                            break;
                    }
                }
            } else if( action == "REASSIGN" ) {
                menu_mode = mutation_menu_mode::reassigning;
                examine_id = cata::nullopt;
            } else if( action == "TOGGLE_EXAMINE" ) {
                // switches between activation and examination
                menu_mode = menu_mode == mutation_menu_mode::activating ?
                            mutation_menu_mode::examining : mutation_menu_mode::activating;
                examine_id = cata::nullopt;
            } else if( action == "QUIT" ) {
                ret.cmd = mutations_ui_cmd::exit;
                exit = true;
            }
        }
    }
    return ret;
}
References _, a, action, Character::activate_mutation(), mutation_branch::activated, activating, active, Creature::add_msg_if_player(), query_popup::allow_anykey(), query_popup::allow_cancel(), BORDER_COLOR, c_cyan, c_cyan_yellow, c_green, c_green_yellow, c_light_blue, c_light_cyan, c_light_cyan_yellow, c_light_gray, c_light_green, c_light_green_yellow, c_light_red, c_light_red_yellow, c_red, c_red_yellow, c_white, can_use_mutation_warn(), CATA_INPUT_KEYBOARD, query_popup::context(), mutation_branch::cooldown, mutation_branch::cost, Messages::deactivate(), Character::deactivate_mutation(), draw_border(), draw_exam_window(), draw_scrollbar(), examining, exit, mutation_branch::fatigue, fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, invlet_wrapper::get_allowed_chars(), Character::get_fatigue(), input_event::get_first_input(), Character::get_kcal_percent(), mutation_branch::get_name(), input_context::get_raw_input(), Character::get_thirst(), GetTrait(), input_context::handle_input(), Character::has_base_trait(), cata::optional< T >::has_value(), char_creation::HEIGHT, mutation_branch::hunger, string_id< T >::is_null(), char_trait_data::key, LINE_OXOX, LINE_XOXX, LINE_XXXO, m_neutral, query_popup::message(), mutation_chars, catacurses::mvwhline(), mvwprintz(), mvwputch(), Character::my_mutations, mutation_branch::name(), catacurses::newwin(), none, cata::nullopt, string_id< T >::obj(), passive, point_zero, popup(), char_trait_data::powered, query_popup::query(), reassigning, ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), cata::hash64_detail::ret, input_event::sequence, show_mutations_titlebar(), string_format(), cata::swap(), TERMX, TERMY, mutation_branch::thirst, trait_by_invlet(), mutation_branch::transform, type, input_event::type, invlet_wrapper::valid(), cata::optional< T >::value(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by show_mutations_ui().
snprintf_float() [1/2]
int detail::snprintf_float (float value, int precision, float_specs specs, buffer< char > & buf) delete
snprintf_float() [2/2]
template<typename T > int detail::snprintf_float (T value, int precision, float_specs specs, buffer< char > & buf)
Definition at line 2716 of file fmtlib_format-inl.h.
{
    // Buffer capacity must be non-zero, otherwise MSVC's vsnprintf_s will fail.
    FMT_ASSERT( buf.capacity() > buf.size(), "empty buffer" );
    static_assert( !std::is_same<T, float>::value, "" );
    // Subtract 1 to account for the difference in precision since we use %e for
    // both general and exponent format.
    if( specs.format == float_format::general ||
        specs.format == float_format::exp ) {
        precision = ( precision >= 0 ? precision : 6 ) - 1;
    }
    // Build the format string.
    enum { max_format_size = 7 };  // The longest format is "%#.*Le".
    char format[max_format_size];
    char *format_ptr = format;
    *format_ptr++ = '%';
    if( specs.showpoint && specs.format == float_format::hex ) {
        *format_ptr++ = '#';
    }
    if( precision >= 0 ) {
        *format_ptr++ = '.';
        *format_ptr++ = '*';
    }
    if( std::is_same<T, long double>() ) {
        *format_ptr++ = 'L';
    }
    *format_ptr++ = specs.format != float_format::hex
                    ? ( specs.format == float_format::fixed ? 'f' : 'e' )
                    : ( specs.upper ? 'A' : 'a' );
    *format_ptr = '\0';
    // Format using snprintf.
    auto offset = buf.size();
    for( ;; ) {
        auto begin = buf.data() + offset;
        auto capacity = buf.capacity() - offset;
#ifdef FMT_FUZZ
        if( precision > 100000 )
            throw std::runtime_error(
                "fuzz mode - avoid large allocation inside snprintf" );
#endif
        // Suppress the warning about a nonliteral format string.
        // Cannot use auto because of a bug in MinGW (#1532).
        int ( *snprintf_ptr )( char *, size_t, const char *, ... ) = FMT_SNPRINTF;
        int result = precision >= 0
                     ? snprintf_ptr( begin, capacity, format, precision, value )
                     : snprintf_ptr( begin, capacity, format, value );
        if( result < 0 ) {
            // The buffer will grow exponentially.
            buf.try_reserve( buf.capacity() + 1 );
            continue;
        }
        auto size = to_unsigned( result );
        // Size equal to capacity means that the last character was truncated.
        if( size >= capacity ) {
            buf.try_reserve( size + offset + 1 ); // Add 1 for the terminating '\0'.
            continue;
        }
        auto is_digit = []( char c ) {
            return c >= '0' && c <= '9';
        };
        if( specs.format == float_format::fixed ) {
            if( precision == 0 ) {
                buf.try_resize( size );
                return 0;
            }
            // Find and remove the decimal point.
            auto end = begin + size, p = end;
            do {
                --p;
            } while( is_digit( *p ) );
            int fraction_size = static_cast<int>( end - p - 1 );
            std::memmove( p, p + 1, to_unsigned( fraction_size ) );
            buf.try_resize( size - 1 );
            return -fraction_size;
        }
        if( specs.format == float_format::hex ) {
            buf.try_resize( size + offset );
            return 0;
        }
        // Find and parse the exponent.
        auto end = begin + size, exp_pos = end;
        do {
            --exp_pos;
        } while( *exp_pos != 'e' );
        char sign = exp_pos[1];
        assert( sign == '+' || sign == '-' );
        int exp = 0;
        auto p = exp_pos + 2;  // Skip 'e' and sign.
        do {
            assert( is_digit( *p ) );
            exp = exp * 10 + ( *p++ - '0' );
        } while( p != end );
        if( sign == '-' ) {
            exp = -exp;
        }
        int fraction_size = 0;
        if( exp_pos != begin + 1 ) {
            // Remove trailing zeros.
            auto fraction_end = exp_pos - 1;
            while( *fraction_end == '0' ) {
                --fraction_end;
            }
            // Move the fractional part left to get rid of the decimal point.
            fraction_size = static_cast<int>( fraction_end - begin - 1 );
            std::memmove( begin + 1, begin + 2, to_unsigned( fraction_size ) );
        }
        buf.try_resize( to_unsigned( fraction_size ) + offset + 1 );
        return exp - fraction_size;
    }
}
References c, detail::buffer< T >::capacity(), detail::buffer< T >::data(), exp, fixed, FMT_ASSERT, FMT_SNPRINTF, format(), detail::float_specs::format, general, hex, detail::float_specs::showpoint, detail::buffer< T >::size(), om_direction::size, to_unsigned(), detail::buffer< T >::try_reserve(), detail::buffer< T >::try_resize(), and detail::float_specs::upper.
Referenced by format_float().
snprintf_float< double >()
template int detail::snprintf_float< double > (double value, int precision, float_specs specs, buffer< char > & buf)
snprintf_float< long double >()
template int detail::snprintf_float< long double > (long double value, int precision, float_specs specs, buffer< char > & buf)
thousands_sep() [1/2]
template<typename Char > Char detail::thousands_sep (locale_ref loc) inline
Definition at line 1157 of file fmtlib_format.h.
{
    return Char( thousands_sep_impl<char>( loc ) );
}
References thousands_sep_impl< char >().
thousands_sep() [2/2]
template<> wchar_t detail::thousands_sep (locale_ref loc) inline
Definition at line 1161 of file fmtlib_format.h.
{
    return thousands_sep_impl<wchar_t>( loc );
}
References thousands_sep_impl< wchar_t >().
thousands_sep_impl() [1/2]
template<typename Char > template FMT_API wchar_t detail::thousands_sep_impl (locale_ref loc)
Definition at line 219 of file fmtlib_format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>( loc.get<std::locale>() )
           .thousands_sep();
}
References detail::locale_ref::get().
thousands_sep_impl() [2/2]
template<typename Char > FMT_API Char detail::thousands_sep_impl (locale_ref loc)
Definition at line 219 of file fmtlib_format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>( loc.get<std::locale>() )
           .thousands_sep();
}
References detail::locale_ref::get().
thousands_sep_impl< char >()
template FMT_API char detail::thousands_sep_impl< char > (locale_ref loc)
Referenced by thousands_sep().
thousands_sep_impl< wchar_t >()
template FMT_API wchar_t detail::thousands_sep_impl< wchar_t > (locale_ref loc)
Referenced by thousands_sep().
to_ascii() [1/2]
template<typename Char , FMT_ENABLE_IF(std::is_integral< Char >::value) > constexpr Char detail::to_ascii (Char value) constexpr
Definition at line 3184 of file fmtlib_format.h.
{
    return value;
}
to_ascii() [2/2]
template<typename Char , FMT_ENABLE_IF(std::is_enum< Char >::value) > constexpr std::underlying_type< Char >::type detail::to_ascii (Char value) constexpr
Definition at line 3189 of file fmtlib_format.h.
{
    return value;
}
Referenced by parse_align(), and parse_format_specs().
to_pointer() [1/2]
template<typename T > T * detail::to_pointer (buffer_appender< T > it, size_t n)
Definition at line 437 of file fmtlib_format.h.
{
    buffer<T> &buf = get_container( it );
    auto size = buf.size();
    if( buf.capacity() < size + n ) {
        return nullptr;
    }
    buf.try_resize( size + n );
    return buf.data() + size;
}
References detail::buffer< T >::capacity(), detail::buffer< T >::data(), get_container(), detail::buffer< T >::size(), om_direction::size, and detail::buffer< T >::try_resize().
to_pointer() [2/2]
template<typename T , typename OutputIt > constexpr T * detail::to_pointer (OutputIt , size_t) constexpr
Definition at line 433 of file fmtlib_format.h.
{
    return nullptr;
}
to_string_view()
void detail::to_string_view (...)
Referenced by detail::arg_mapper< Context >::map().
to_uintptr()
fallback_uintptr detail::to_uintptr (const void * p) inline
Definition at line 336 of file fmtlib_format.h.
{
    return fallback_uintptr( p );
}
Referenced by write(), and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write_pointer().
to_unsigned()
template<typename Int > FMT_CONSTEXPR std::make_unsigned< Int >::type detail::to_unsigned (Int value)
Definition at line 332 of file fmtlib_core.h.
{
    FMT_ASSERT( value >= 0, "negative value" );
    return static_cast<typename std::make_unsigned<Int>::type>( value );
}
References FMT_ASSERT, and type.
Referenced by basic_format_parse_context< Char, ErrorHandler >::advance_to(), detail::bigint::align(), detail::buffer< T >::append(), fallback_format(), find< false, char >(), basic_printf_context< OutputIt, Char >::format(), format_error_code(), format_float(), format_uint(), get_dynamic_spec(), detail::dynamic_specs_handler< ParseContext >::make_arg_ref(), detail::int_writer< OutputIt, Char, UInt >::on_num(), detail::format_handler< OutputIt, Char, Context >::on_text(), detail::bigint::operator[](), parse_align(), parse_arg_id(), detail::bigint::remove_leading_zeros(), format_int::size(), snprintf_float(), detail::bigint::square(), detail::utf8_to_utf16::utf8_to_utf16(), write(), write_buffer(), write_float(), detail::write_int_data< Char >::write_int_data(), write_padded(), and write_ptr().
unwrap() [1/2]
template<typename T > const T & detail::unwrap (const std::reference_wrapper< T > & v)
Definition at line 1648 of file fmtlib_core.h.
{
    return static_cast<const T &>( v );
}
unwrap() [2/2]
template<typename T > const T & detail::unwrap (const T & v)
Definition at line 1644 of file fmtlib_core.h.
{
    return v;
}
Referenced by dynamic_format_arg_store< Context >::emplace_arg(), and dynamic_format_arg_store< Context >::push_back().
utf8_decode()
const char * detail::utf8_decode (const char * buf, uint32_t * c, int * e) inline
Definition at line 2848 of file fmtlib_format-inl.h.
{
    static const int masks[] = {0x00, 0x7f, 0x1f, 0x0f, 0x07};
    static const uint32_t mins[] = {4194304, 0, 128, 2048, 65536};
    static const int shiftc[] = {0, 18, 12, 6, 0};
    static const int shifte[] = {0, 6, 4, 2, 0};
    int len = code_point_length( buf );
    const char *next = buf + len;
    // Assume a four-byte character and load four bytes. Unused bits are
    // shifted out.
    auto s = reinterpret_cast<const unsigned char *>( buf );
    *c = uint32_t( s[0] & masks[len] ) << 18;
    *c |= uint32_t( s[1] & 0x3f ) << 12;
    *c |= uint32_t( s[2] & 0x3f ) << 6;
    *c |= uint32_t( s[3] & 0x3f ) << 0;
    *c >>= shiftc[len];
    // Accumulate the various error conditions.
    *e = ( *c < mins[len] ) << 6;     // non-canonical encoding
    *e |= ( ( *c >> 11 ) == 0x1b ) << 7; // surrogate half?
    *e |= ( *c > 0x10FFFF ) << 8;     // out of range?
    *e |= ( s[1] & 0xc0 ) >> 2;
    *e |= ( s[2] & 0xc0 ) >> 4;
    *e |= ( s[3] ) >> 6;
    *e ^= 0x2a;  // top two bits of each tail byte correct?
    *e >>= shifte[len];
    return next;
}
References c, and code_point_length().
Referenced by detail::utf8_to_utf16::utf8_to_utf16().
vformat() [1/2]
template<typename Char , FMT_ENABLE_IF(!std::is_same< Char, char >::value) > std::basic_string< Char > detail::vformat (basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char > > > args)
Definition at line 4363 of file fmtlib_format.h.
{
    basic_memory_buffer<Char> buffer;
    detail::vformat_to( buffer, format_str, args );
    return to_string( buffer );
}
References to_string(), and vformat_to().
Referenced by format(), and vformat().
vformat() [2/2]
FMT_FUNC std::string detail::vformat (string_view format_str, format_args args)
Definition at line 2995 of file fmtlib_format-inl.h.
{
    if( format_str.size() == 2 && equal2( format_str.data(), "{}" ) ) {
        auto arg = args.get( 0 );
        if( !arg ) {
            error_handler().on_error( "argument not found" );
        }
        return visit_format_arg( stringifier(), arg );
    }
    memory_buffer buffer;
    detail::vformat_to( buffer, format_str, args );
    return to_string( buffer );
}
References arg(), basic_string_view< Char >::data(), equal2(), basic_format_args< Context >::get(), detail::error_handler::on_error(), basic_string_view< Char >::size(), to_string(), vformat_to(), and visit_format_arg().
vformat_to() [1/3]
template basic_format_context< std::back_insert_iterator< buffer< char > >, char >::iterator detail::vformat_to (buffer< char > & , string_view , basic_format_args< basic_format_context< std::back_insert_iterator< buffer< type_identity_t< char > > >, type_identity_t< char > > >)
vformat_to() [2/3]
template<typename Char > basic_format_context< std::back_insert_iterator< buffer< Char > >, Char >::iterator detail::vformat_to (buffer< Char > & buf, basic_string_view< Char > format_str, basic_format_args< basic_format_context< std::back_insert_iterator< buffer< type_identity_t< Char > > >, type_identity_t< Char > > > args)
Definition at line 38 of file fmtlib_format.cpp.
{
    using iterator = std::back_insert_iterator<buffer<char>>;
    using context = basic_format_context <
                    std::back_insert_iterator<buffer<type_identity_t<Char>>>,
                    type_identity_t<Char >>;
    auto out = iterator( buf );
    format_handler<iterator, Char, context> h( out, format_str, args, {} );
    parse_format_string<false>( format_str, h );
    return out;
}
vformat_to() [3/3]
template<typename Char > void detail::vformat_to (buffer< Char > & buf, basic_string_view< Char > format_str, basic_format_args< FMT_BUFFER_CONTEXT(type_identity_t< Char >)> args, detail::locale_ref loc = {})
Referenced by format_to(), formatted_size(), vformat(), vformat_to(), vformat_to_n(), and vprint().
vprint_mojibake() [1/2]
template<typename Char , typename Args , FMT_ENABLE_IF(!std::is_same< Char, char >::value) > void detail::vprint_mojibake (std::FILE * , basic_string_view< Char > , const Args &) inline
Definition at line 2203 of file fmtlib_core.h.
{}
Referenced by print().
vprint_mojibake() [2/2]
void detail::vprint_mojibake (std::FILE * , string_view , format_args) inline
Definition at line 2207 of file fmtlib_core.h.
{}
vprintf()
template<typename Char , typename Context > void detail::vprintf (buffer< Char > & buf, basic_string_view< Char > format, basic_format_args< Context > args)
Definition at line 205 of file fmtlib_printf.h.
{
    Context( buffer_appender<Char>( buf ), format, args ).format();
}
References format().
Referenced by printf().
write() [1/12]
template<typename Char > buffer_appender< Char > detail::write (buffer_appender< Char > out, basic_string_view< Char > value)
Definition at line 2331 of file fmtlib_format.h.
{
    get_container( out ).append( value.begin(), value.end() );
    return out;
}
References get_container().
write() [2/12]
template<typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, basic_string_view< Char > value)
Definition at line 2323 of file fmtlib_format.h.
{
    auto it = reserve( out, value.size() );
    it = std::copy( value.begin(), value.end(), it );
    return base_iterator( out, it );
}
References base_iterator(), and reserve().
write() [3/12]
template<typename StrChar , typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, basic_string_view< StrChar > s, const basic_format_specs< Char > & specs)
Definition at line 1791 of file fmtlib_format.h.
{
    auto data = s.data();
    auto size = s.size();
    if( specs.precision >= 0 && to_unsigned( specs.precision ) < size ) {
        size = code_point_index( s, to_unsigned( specs.precision ) );
    }
    auto width = specs.width != 0
                 ? count_code_points( basic_string_view<StrChar>( data, size ) )
                 : 0;
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    return write_padded( out, specs, size, width, [ = ]( iterator it ) {
        return copy_str<Char>( data, data + size, it );
    } );
}
References code_point_index(), count_code_points(), basic_string_view< Char >::data(), basic_format_specs< Char >::precision, reserve(), basic_string_view< Char >::size(), om_direction::size, to_unsigned(), basic_format_specs< Char >::width, and write_padded().
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()().
write() [4/12]
template<typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, bool value)
Definition at line 2368 of file fmtlib_format.h.
{
    return write<Char>( out, string_view( value ? "true" : "false" ) );
}
write() [5/12]
template<typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, Char value)
Definition at line 2374 of file fmtlib_format.h.
{
    auto it = reserve( out, 1 );
    *it++ = value;
    return base_iterator( out, it );
}
References base_iterator(), and reserve().
write() [6/12]
template<typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, const Char * value)
Definition at line 2382 of file fmtlib_format.h.
{
    if( !value ) {
        FMT_THROW( format_error( "string pointer is null" ) );
    } else {
        auto length = std::char_traits<Char>::length( value );
        out = write( out, basic_string_view<Char>( value, length ) );
    }
    return out;
}
References FMT_THROW, and write().
write() [7/12]
template<typename Char , typename OutputIt , typename T > auto detail::write (OutputIt out, const T & value) -> typename std::enable_if < mapped_type_constant<T, basic_format_context<OutputIt, Char>>::value == type::custom_type, OutputIt >::type
Definition at line 2400 of file fmtlib_format.h.
{
    using context_type = basic_format_context<OutputIt, Char>;
    using formatter_type =
        conditional_t<has_formatter<T, context_type>::value,
        typename context_type::template formatter_type<T>,
                 fallback_formatter<T, Char>>;
    context_type ctx( out, {}, {} );
    return formatter_type().format( value, ctx );
}
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()(), parse_format_string(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), write(), write_float(), and write_ptr().
write() [8/12]
template<typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, const void * value)
Definition at line 2394 of file fmtlib_format.h.
{
    return write_ptr<Char>( out, to_uintptr( value ), nullptr );
}
References to_uintptr().
write() [9/12]
template<typename Char , typename OutputIt > OutputIt detail::write (OutputIt out, monostate)
Definition at line 2307 of file fmtlib_format.h.
{
    FMT_ASSERT( false, "" );
    return out;
}
References FMT_ASSERT.
write() [10/12]
template<typename Char , typename OutputIt , FMT_ENABLE_IF(!std::is_same< Char, char >::value) > OutputIt detail::write (OutputIt out, string_view value)
Definition at line 2315 of file fmtlib_format.h.
{
    auto it = reserve( out, value.size() );
    it = copy_str<Char>( value.begin(), value.end(), it );
    return base_iterator( out, it );
}
References base_iterator(), and reserve().
write() [11/12]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_fast_float< T >::value) > OutputIt detail::write (OutputIt out, T value) inline
Definition at line 2239 of file fmtlib_format.h.
{
    if( const_check( !is_supported_floating_point( value ) ) ) {
        return out;
    }
    using floaty = conditional_t<std::is_same<T, long double>::value, double, T>;
    using uint = typename dragonbox::float_info<floaty>::carrier_uint;
    auto bits = bit_cast<uint>( value );
    auto fspecs = float_specs();
    auto sign_bit = bits & ( uint( 1 ) << ( num_bits<uint>() - 1 ) );
    if( sign_bit != 0 ) {
        fspecs.sign = sign::minus;
        value = -value;
    }
    static const auto specs = basic_format_specs<Char>();
    uint mask = exponent_mask<floaty>();
    if( ( bits & mask ) == mask ) {
        return write_nonfinite( out, std::isinf( value ), specs, fspecs );
    }
    auto dec = dragonbox::to_decimal( static_cast<floaty>( value ) );
    return write_float( out, dec, specs, fspecs, static_cast<Char>( '.' ) );
}
References const_check(), is_supported_floating_point(), sign::minus, detail::dragonbox::to_decimal(), write_float(), and write_nonfinite().
write() [12/12]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > OutputIt detail::write (OutputIt out, T value, basic_format_specs< Char > specs, locale_ref loc = {})
Definition at line 2180 of file fmtlib_format.h.
                                 {} )
{
    if( const_check( !is_supported_floating_point( value ) ) ) {
        return out;
    }
    float_specs fspecs = parse_float_type_spec( specs );
    fspecs.sign = specs.sign;
    if( std::signbit( value ) ) { // value < 0 is false for NaN so use signbit.
        fspecs.sign = sign::minus;
        value = -value;
    } else if( fspecs.sign == sign::minus ) {
        fspecs.sign = sign::none;
    }
    if( !std::isfinite( value ) ) {
        return write_nonfinite( out, std::isinf( value ), specs, fspecs );
    }
    if( specs.align == align::numeric && fspecs.sign ) {
        auto it = reserve( out, 1 );
        *it++ = static_cast<Char>( data::signs[fspecs.sign] );
        out = base_iterator( out, it );
        fspecs.sign = sign::none;
        if( specs.width != 0 ) {
            --specs.width;
        }
    }
    memory_buffer buffer;
    if( fspecs.format == float_format::hex ) {
        if( fspecs.sign ) {
            buffer.push_back( data::signs[fspecs.sign] );
        }
        snprintf_float( promote_float( value ), specs.precision, fspecs, buffer );
        return write_bytes( out, {buffer.data(), buffer.size()}, specs );
    }
    int precision = specs.precision >= 0 || !specs.type ? specs.precision : 6;
    if( fspecs.format == float_format::exp ) {
        if( precision == max_value<int>() ) {
            FMT_THROW( format_error( "number is too big" ) );
        } else {
            ++precision;
        }
    }
    if( const_check( std::is_same<T, float>() ) ) {
        fspecs.binary32 = true;
    }
    fspecs.use_grisu = is_fast_float<T>();
    int exp = format_float( promote_float( value ), precision, fspecs, buffer );
    fspecs.precision = precision;
    Char point =
        fspecs.locale ? decimal_point<Char>( loc ) : static_cast<Char>( '.' );
    auto fp = big_decimal_fp{buffer.data(), static_cast<int>( buffer.size() ), exp};
    return write_float( out, fp, specs, fspecs, point );
}
write_buffer()
template<typename Char > void detail::write_buffer (std::basic_ostream< Char > & os, buffer< Char > & buf)
Definition at line 98 of file fmtlib_ostream.h.
{
    const Char *buf_data = buf.data();
    using unsigned_streamsize = std::make_unsigned<std::streamsize>::type;
    unsigned_streamsize size = buf.size();
    unsigned_streamsize max_size = to_unsigned( max_value<std::streamsize>() );
    do {
        unsigned_streamsize n = size <= max_size ? size : max_size;
        os.write( buf_data, static_cast<std::streamsize>( n ) );
        buf_data += n;
        size -= n;
    } while( size != 0 );
}
References detail::buffer< T >::data(), detail::buffer< T >::size(), om_direction::size, to_unsigned(), and type.
Referenced by vfprintf(), and vprint().
write_bytes()
template<typename Char , typename OutputIt > OutputIt detail::write_bytes (OutputIt out, string_view bytes, const basic_format_specs< Char > & specs)
Definition at line 1740 of file fmtlib_format.h.
{
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    return write_padded( out, specs, bytes.size(), [bytes]( iterator it ) {
        const char *data = bytes.data();
        return copy_str<Char>( data, data + bytes.size(), it );
    } );
}
References reserve(), and write_padded().
Referenced by formatter< bytes >::format().
write_char()
template<typename Char , typename OutputIt > OutputIt detail::write_char (OutputIt out, Char value, const basic_format_specs< Char > & specs)
Definition at line 2275 of file fmtlib_format.h.
{
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    return write_padded( out, specs, 1, [ = ]( iterator it ) {
        *it++ = value;
        return it;
    } );
}
References reserve(), and write_padded().
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::char_spec_handler::on_char().
write_exponent()
template<typename Char , typename It > It detail::write_exponent (int exp, It it)
Definition at line 1484 of file fmtlib_format.h.
{
    FMT_ASSERT( -10000 < exp && exp < 10000, "exponent out of range" );
    if( exp < 0 ) {
        *it++ = static_cast<Char>( '-' );
        exp = -exp;
    } else {
        *it++ = static_cast<Char>( '+' );
    }
    if( exp >= 100 ) {
        const char *top = data::digits[exp / 100];
        if( exp >= 1000 ) {
            *it++ = static_cast<Char>( top[0] );
        }
        *it++ = static_cast<Char>( top[1] );
        exp %= 100;
    }
    const char *d = data::digits[exp];
    *it++ = static_cast<Char>( d[0] );
    *it++ = static_cast<Char>( d[1] );
    return it;
}
References exp, and FMT_ASSERT.
write_float()
template<typename OutputIt , typename DecimalFP , typename Char > OutputIt detail::write_float (OutputIt out, const DecimalFP & fp, const basic_format_specs< Char > & specs, float_specs fspecs, Char decimal_point)
Definition at line 2056 of file fmtlib_format.h.
{
    auto significand = fp.significand;
    int significand_size = get_significand_size( fp );
    static const Char zero = static_cast<Char>( '0' );
    auto sign = fspecs.sign;
    size_t size = to_unsigned( significand_size ) + ( sign ? 1 : 0 );
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    int output_exp = fp.exponent + significand_size - 1;
    auto use_exp_format = [ = ]() {
        if( fspecs.format == float_format::exp ) {
            return true;
        }
        if( fspecs.format != float_format::general ) {
            return false;
        }
        // Use the fixed notation if the exponent is in [exp_lower, exp_upper),
        // e.g. 0.0001 instead of 1e-04. Otherwise use the exponent notation.
        const int exp_lower = -4, exp_upper = 16;
        return output_exp < exp_lower ||
               output_exp >= ( fspecs.precision > 0 ? fspecs.precision : exp_upper );
    };
    if( use_exp_format() ) {
        int num_zeros = 0;
        if( fspecs.showpoint ) {
            num_zeros = ( std::max )( fspecs.precision - significand_size, 0 );
            size += to_unsigned( num_zeros );
        } else if( significand_size == 1 ) {
            decimal_point = Char();
        }
        auto abs_output_exp = output_exp >= 0 ? output_exp : -output_exp;
        int exp_digits = 2;
        if( abs_output_exp >= 100 ) {
            exp_digits = abs_output_exp >= 1000 ? 4 : 3;
        }
        size += to_unsigned( ( decimal_point ? 1 : 0 ) + 2 + exp_digits );
        char exp_char = fspecs.upper ? 'E' : 'e';
        auto write = [ = ]( iterator it ) {
            if( sign ) {
                *it++ = static_cast<Char>( data::signs[sign] );
            }
            // Insert a decimal point after the first digit and add an exponent.
            it = write_significand( it, significand, significand_size, 1,
                                    decimal_point );
            if( num_zeros > 0 ) {
                it = std::fill_n( it, num_zeros, zero );
            }
            *it++ = static_cast<Char>( exp_char );
            return write_exponent<Char>( output_exp, it );
        };
        return specs.width > 0 ? write_padded<align::right>( out, specs, size, write )
               : base_iterator( out, write( reserve( out, size ) ) );
    }
    int exp = fp.exponent + significand_size;
    if( fp.exponent >= 0 ) {
        // 1234e5 -> 123400000[.0+]
        size += to_unsigned( fp.exponent );
        int num_zeros = fspecs.precision - exp;
#ifdef FMT_FUZZ
        if( num_zeros > 5000 ) {
            throw std::runtime_error( "fuzz mode - avoiding excessive cpu use" );
        }
#endif
        if( fspecs.showpoint ) {
            if( num_zeros <= 0 && fspecs.format != float_format::fixed ) {
                num_zeros = 1;
            }
            if( num_zeros > 0 ) {
                size += to_unsigned( num_zeros );
            }
        }
        return write_padded<align::right>( out, specs, size, [&]( iterator it ) {
            if( sign ) {
                *it++ = static_cast<Char>( data::signs[sign] );
            }
            it = write_significand<Char>( it, significand, significand_size );
            it = std::fill_n( it, fp.exponent, zero );
            if( !fspecs.showpoint ) {
                return it;
            }
            *it++ = decimal_point;
            return num_zeros > 0 ? std::fill_n( it, num_zeros, zero ) : it;
        } );
    } else if( exp > 0 ) {
        // 1234e-2 -> 12.34[0+]
        int num_zeros = fspecs.showpoint ? fspecs.precision - significand_size : 0;
        size += 1 + to_unsigned( num_zeros > 0 ? num_zeros : 0 );
        return write_padded<align::right>( out, specs, size, [&]( iterator it ) {
            if( sign ) {
                *it++ = static_cast<Char>( data::signs[sign] );
            }
            it = write_significand( it, significand, significand_size, exp,
                                    decimal_point );
            return num_zeros > 0 ? std::fill_n( it, num_zeros, zero ) : it;
        } );
    }
    // 1234e-6 -> 0.001234
    int num_zeros = -exp;
    if( significand_size == 0 && fspecs.precision >= 0 &&
        fspecs.precision < num_zeros ) {
        num_zeros = fspecs.precision;
    }
    size += 2 + to_unsigned( num_zeros );
    return write_padded<align::right>( out, specs, size, [&]( iterator it ) {
        if( sign ) {
            *it++ = static_cast<Char>( data::signs[sign] );
        }
        *it++ = zero;
        if( num_zeros == 0 && significand_size == 0 && !fspecs.showpoint ) {
            return it;
        }
        *it++ = decimal_point;
        it = std::fill_n( it, num_zeros, zero );
        return write_significand<Char>( it, significand, significand_size );
    } );
}
References base_iterator(), decimal_point(), exp, detail::float_specs::format, get_significand_size(), detail::float_specs::precision, reserve(), detail::float_specs::showpoint, detail::float_specs::sign, sign(), om_direction::size, to_unsigned(), detail::float_specs::upper, basic_format_specs< Char >::width, write(), and write_significand().
Referenced by write().
write_int()
template<typename OutputIt , typename Char , typename F > OutputIt detail::write_int (OutputIt out, int num_digits, string_view prefix, const basic_format_specs< Char > & specs, F f)
Definition at line 1776 of file fmtlib_format.h.
{
    auto data = write_int_data<Char>( num_digits, prefix, specs );
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    return write_padded<align::right>( out, specs, data.size, [ = ]( iterator it ) {
        if( prefix.size() != 0 ) {
            it = copy_str<Char>( prefix.begin(), prefix.end(), it );
        }
        it = std::fill_n( it, data.padding, static_cast<Char>( '0' ) );
        return f( it );
    } );
}
References prefix, and reserve().
Referenced by detail::int_writer< OutputIt, Char, UInt >::on_bin(), detail::int_writer< OutputIt, Char, UInt >::on_dec(), detail::int_writer< OutputIt, Char, UInt >::on_hex(), detail::int_writer< OutputIt, Char, UInt >::on_oct(), and detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::operator()().
write_nonfinite()
template<typename Char , typename OutputIt > OutputIt detail::write_nonfinite (OutputIt out, bool isinf, const basic_format_specs< Char > & specs, const float_specs & fspecs)
Definition at line 1961 of file fmtlib_format.h.
{
    auto str =
        isinf ? ( fspecs.upper ? "INF" : "inf" ) : ( fspecs.upper ? "NAN" : "nan" );
    constexpr size_t str_size = 3;
    auto sign = fspecs.sign;
    auto size = str_size + ( sign ? 1 : 0 );
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    return write_padded( out, specs, size, [ = ]( iterator it ) {
        if( sign ) {
            *it++ = static_cast<Char>( data::signs[sign] );
        }
        return copy_str<Char>( str, str + str_size, it );
    } );
}
References reserve(), detail::float_specs::sign, sign(), om_direction::size, detail::float_specs::upper, and write_padded().
Referenced by write().
write_padded() [1/2]
template<align::type align = align::left, typename OutputIt , typename Char , typename F > OutputIt detail::write_padded (OutputIt out, const basic_format_specs< Char > & specs, size_t size, F && f) inline
Definition at line 1732 of file fmtlib_format.h.
{
    return write_padded<align>( out, specs, size, size, f );
}
References om_direction::size.
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), write(), write_bytes(), write_char(), and write_nonfinite().
write_padded() [2/2]
template<align::type align = align::left, typename OutputIt , typename Char , typename F > OutputIt detail::write_padded (OutputIt out, const basic_format_specs< Char > & specs, size_t size, size_t width, F && f) inline
Definition at line 1713 of file fmtlib_format.h.
{
    static_assert( align == align::left || align == align::right, "" );
    unsigned spec_width = to_unsigned( specs.width );
    size_t padding = spec_width > width ? spec_width - width : 0;
    auto *shifts = align == align::left ? data::left_padding_shifts
                   : data::right_padding_shifts;
    size_t left_padding = padding >> shifts[specs.align];
    auto it = reserve( out, size + padding * specs.fill.size() );
    it = fill( it, left_padding, specs.fill );
    it = f( it );
    it = fill( it, padding - left_padding, specs.fill );
    return base_iterator( out, it );
}
References basic_format_specs< Char >::align, base_iterator(), basic_format_specs< Char >::fill, fill(), align::left, reserve(), align::right, om_direction::size, to_unsigned(), and basic_format_specs< Char >::width.
write_ptr()
template<typename Char , typename OutputIt , typename UIntPtr > OutputIt detail::write_ptr (OutputIt out, UIntPtr value, const basic_format_specs< Char > * specs)
Definition at line 2286 of file fmtlib_format.h.
{
    int num_digits = count_digits<4>( value );
    auto size = to_unsigned( num_digits ) + size_t( 2 );
    using iterator = remove_reference_t<decltype( reserve( out, 0 ) )>;
    auto write = [ = ]( iterator it ) {
        *it++ = static_cast<Char>( '0' );
        *it++ = static_cast<Char>( 'x' );
        // NOLINTNEXTLINE(cata-no-long)
        return format_uint<4, Char>( it, value, num_digits );
    };
    return specs ? write_padded<align::right>( out, *specs, size, write )
           : base_iterator( out, write( reserve( out, size ) ) );
}
References base_iterator(), count_digits< 4 >(), reserve(), om_direction::size, to_unsigned(), and write().
write_significand() [1/5]
template<typename Char , typename UInt , FMT_ENABLE_IF(std::is_integral< UInt >::value) > Char * detail::write_significand (Char * out, UInt significand, int significand_size, int integral_size, Char decimal_point) inline
Definition at line 2011 of file fmtlib_format.h.
{
    if( !decimal_point ) {
        return format_decimal( out, significand, significand_size ).end;
    }
    auto end = format_decimal( out + 1, significand, significand_size ).end;
    if( integral_size == 1 ) {
        out[0] = out[1];
    } else {
        std::copy_n( out + 1, integral_size, out );
    }
    out[integral_size] = decimal_point;
    return end;
}
References decimal_point(), and format_decimal().
write_significand() [2/5]
template<typename Char , typename OutputIt > OutputIt detail::write_significand (OutputIt out, const char * significand, int & significand_size) inline
Definition at line 1997 of file fmtlib_format.h.
{
    return copy_str<Char>( significand, significand + significand_size, out );
}
write_significand() [3/5]
template<typename OutputIt , typename Char > OutputIt detail::write_significand (OutputIt out, const char * significand, int significand_size, int integral_size, Char decimal_point) inline
Definition at line 2042 of file fmtlib_format.h.
{
    out = detail::copy_str<Char>( significand, significand + integral_size, out );
    if( !decimal_point ) {
        return out;
    }
    *out++ = decimal_point;
    return detail::copy_str<Char>( significand + integral_size,
                                   significand + significand_size, out );
}
References decimal_point().
Referenced by write_float(), and write_significand().
write_significand() [4/5]
template<typename Char , typename OutputIt , typename UInt > OutputIt detail::write_significand (OutputIt out, UInt significand, int significand_size) inline
Definition at line 2003 of file fmtlib_format.h.
{
    return format_decimal<Char>( out, significand, significand_size ).end;
}
write_significand() [5/5]
template<typename OutputIt , typename UInt , typename Char , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< OutputIt > >::value) > OutputIt detail::write_significand (OutputIt out, UInt significand, int significand_size, int integral_size, Char decimal_point) inline
Definition at line 2030 of file fmtlib_format.h.
{
    // Buffer is large enough to hold digits (digits10 + 1) and a decimal point.
    Char buffer[digits10<UInt>() + 2];
    auto end = write_significand( buffer, significand, significand_size,
                                  integral_size, decimal_point );
    return detail::copy_str<Char>( buffer, end, out );
}
References decimal_point(), and write_significand().
Variable Documentation
basic_data< void >
FMT_EXTERN template struct detail::basic_data< void >
Definition at line 1036 of file fmtlib_format.h.