Cataclysm BN: constructions Namespace Reference
constructions Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void reset ()
void check_consistency ()
void finalize ()
const std::vector< construction_id > & get_all_sorted ()
void override_build_times (time_duration time)
Function Documentation
check_consistency()
void constructions::check_consistency ()
Definition at line 196 of file construction.cpp.
{
    // Legacy migration from when single string was used for both terrain
    // and furniture id.
    // TODO: remove this after reaching BN equivalent of 0.F (or 0.G)
    for( const construction &c_it : all_constructions.get_all() ) {
        construction &c = const_cast<construction &>( c_it );
        bool did_migrate = false;
        if( string_starts_with( c.pre_terrain.str(), "f_" ) ) {
            c.pre_furniture = furn_str_id( c.pre_terrain.str() );
            c.pre_terrain = ter_str_id();
            did_migrate = true;
        }
        if( string_starts_with( c.post_terrain.str(), "f_" ) ) {
            c.post_furniture = furn_str_id( c.post_terrain.str() );
            c.post_terrain = ter_str_id();
            did_migrate = true;
        }
        if( did_migrate && json_report_strict ) {
            debugmsg( "Construction '%s' uses pre_/post_terrain to set furniture id.  Use pre_/post_furniture instead.",
                      c.id );
        }
    }
    all_constructions.check();
}
References anonymous_namespace{construction.cpp}::all_constructions, c, debugmsg, json_report_strict, and string_starts_with().
Referenced by DynamicDataLoader::check_consistency().
finalize()
void constructions::finalize ()
Definition at line 223 of file construction.cpp.
{
    all_constructions.finalize();
    for( const construction &c_it : all_constructions.get_all() ) {
        construction &c = const_cast<construction &>( c_it );
        c.finalize();
        inp_mngr.pump_events();
    }
    constructions_sorted.resize( all_constructions.get_all().size() );
    for( const construction &c : all_constructions.get_all() ) {
        if( c.is_blacklisted() ) {
            continue;
        }
        constructions_sorted.push_back( c.id.id() );
    }
    std::sort( constructions_sorted.begin(), constructions_sorted.end(),
    [&]( const construction_id & l, const construction_id & r ) -> bool {
        lexicographic<construction> cmp;
        return cmp( l->id, r->id );
    } );
}
References anonymous_namespace{construction.cpp}::all_constructions, c, anonymous_namespace{construction.cpp}::constructions_sorted, inp_mngr, and input_manager::pump_events().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all_sorted()
const std::vector< construction_id > & constructions::get_all_sorted ()
Definition at line 247 of file construction.cpp.
{
    if( !all_constructions.is_finalized() ) {
        debugmsg( "constructions_sorted called before finalization" );
    }
    return constructions_sorted;
}
References anonymous_namespace{construction.cpp}::all_constructions, anonymous_namespace{construction.cpp}::constructions_sorted, and debugmsg.
Referenced by can_do_activity_there(), constructions_by_group(), construction_sequences::finalize(), list_available_constructions(), and blueprint_options::query_con().
load()
void constructions::load (const JsonObject & jo, const std::string & src)
Definition at line 185 of file construction.cpp.
{
    all_constructions.load( jo, src );
}
References anonymous_namespace{construction.cpp}::all_constructions.
Referenced by DynamicDataLoader::initialize().
override_build_times()
void constructions::override_build_times (time_duration time)
Definition at line 255 of file construction.cpp.
{
    for( const construction &it : all_constructions.get_all() ) {
        // HACK: const cast is ugly, but allowed here
        construction &c = const_cast<construction &>( it );
        c.time = time;
    }
}
References anonymous_namespace{construction.cpp}::all_constructions, and c.
Referenced by defense_game::init_constructions().
reset()
void constructions::reset ()
Definition at line 190 of file construction.cpp.
{
    all_constructions.reset();
    constructions_sorted.clear();
}
References anonymous_namespace{construction.cpp}::all_constructions, and anonymous_namespace{construction.cpp}::constructions_sorted.
Referenced by DynamicDataLoader::unload_data().