Cataclysm BN: om_direction Namespace Reference
om_direction Namespace Reference
Direction on the overmap.
Enumerations
enum class type : int {
invalid = -1 , none , north = none , east ,
south , west
}
Basic enum for directions.
Functions
constexpr const std::string & get_suffix (type dir)
Returns directional suffix associated with the value, e.g.
constexpr int get_num_cw_rotations (type dir)
Returns number of clockwise rotations needed to reach this direction from 'north'.
constexpr int get_num_ccw_rotations (type dir)
Returns number of counterclockwise rotations needed to reach this direction from 'north'.
const std::string & id (type dir)
Identifier for serialization purposes.
std::string name (type dir)
Get Human readable name of a direction.
point rotate (const point &p, type dir)
Various rotations.
tripoint rotate (const tripoint &p, type dir)
uint32_t rotate_symbol (uint32_t sym, type dir)
point displace (type dir, int dist=1)
Returns point(0, 0) displaced in specified direction by a specified distance.
type add (type dir1, type dir2)
Returns a sum of two numbers.
type turn_left (type dir)
Turn by 90 degrees to the left, to the right, or randomly (either left or right).
type turn_right (type dir)
type turn_random (type dir)
type opposite (type dir)
Returns an opposite direction.
type random ()
Returns a random direction.
bool are_parallel (type dir1, type dir2)
Whether these directions are parallel.
Variables
const std::array< type, 4 > all = {{ type::north, type::east, type::south, type::west }}
For the purposes of iteration.
const size_t size = all.size()
const std::array< std::string, 4 > all_suffixes = {{ "_north", "_east", "_south", "_west" }}
const std::string invalid_dir_suffix
const std::array< int, 4 > all_cw_rotations = {{ 0, 1, 2, 3 }}
const std::array< int, 4 > all_ccw_rotations = { { 0, 3, 2, 1 } }
const int invalid_dir_rotations = 0
const size_t bits = static_cast<size_t>(-1) >> (CHAR_BIT *sizeof(size_t) - size)
Number of bits needed to store directions.
Detailed Description
Direction on the overmap.
Enumeration Type Documentation
type
enum class om_direction::type : int strong
Basic enum for directions.
Enumerator
invalid
none
north
east
south
west
Definition at line 16 of file om_direction.h.
                : int {
    invalid = -1,
    none,
    north = none,
    east,
    south,
    west,
};
Function Documentation
add()
om_direction::type om_direction::add (type dir1, type dir2)
Returns a sum of two numbers.
Parameters
dir1 first number
dir2 second number
Definition at line 4193 of file overmap.cpp.
{
    return rotate_internal( dir1, static_cast<int>( dir2 ) );
}
References rotate_internal().
Referenced by addict_effect(), assign(), assign_map_from_array(), item::bonus_from_enchantments(), item::bonus_from_enchantments_wielded(), map::features(), iexamine::get_harvest_items(), oter_t::get_rotated(), Character::i_add_or_drop(), overmap::place_special(), map::update_lum(), and update_lum().
are_parallel()
bool om_direction::are_parallel (type dir1, type dir2)
Whether these directions are parallel.
Definition at line 4223 of file overmap.cpp.
{
    return dir1 == dir2 || dir1 == opposite( dir2 );
}
References opposite().
Referenced by overmap::build_connection(), and overmap::lay_out_connection().
displace()
point om_direction::displace (type dir, int dist = 1)
Returns point(0, 0) displaced in specified direction by a specified distance.
Parameters
dir Direction of displacement
dist Distance of displacement
Definition at line 4178 of file overmap.cpp.
{
    return rotate( { 0, -dist }, dir );
}
References rotate().
Referenced by overmap::build_anthill(), overmap::build_connection(), overmap::build_tunnel(), elevate_bridges(), pf::greedy_path(), overmap::lay_out_street(), overmap::place_building(), overmap::place_forest_trailheads(), straight_path(), and game::vertical_move().
get_num_ccw_rotations()
constexpr int om_direction::get_num_ccw_rotations (type dir) constexpr
Returns number of counterclockwise rotations needed to reach this direction from 'north'.
Definition at line 56 of file om_direction.h.
{
    if( dir == type::invalid ) {
        return invalid_dir_rotations;
    } else {
        return all_ccw_rotations[static_cast<size_t>( dir )];
    }
}
References all_ccw_rotations, invalid, and invalid_dir_rotations.
Referenced by oter_t::get_rotation_and_subtile().
get_num_cw_rotations()
constexpr int om_direction::get_num_cw_rotations (type dir) constexpr
Returns number of clockwise rotations needed to reach this direction from 'north'.
Definition at line 46 of file om_direction.h.
{
    if( dir == type::invalid ) {
        return invalid_dir_rotations;
    } else {
        return all_cw_rotations[static_cast<size_t>( dir )];
    }
}
References all_cw_rotations, invalid, and invalid_dir_rotations.
Referenced by oter_get_rotations().
get_suffix()
constexpr const std::string & om_direction::get_suffix (type dir) constexpr
Returns directional suffix associated with the value, e.g.
_north or _west.
Definition at line 36 of file om_direction.h.
{
    if( dir == type::invalid ) {
        return invalid_dir_suffix;
    } else {
        return all_suffixes[static_cast<size_t>( dir )];
    }
}
References all_suffixes, invalid, and invalid_dir_suffix.
Referenced by oter_get_rotation_dir(), and oter_get_rotation_string().
id()
const std::string & om_direction::id (type dir)
Identifier for serialization purposes.
Definition at line 4115 of file overmap.cpp.
{
    static const std::array < std::string, size + 1 > ids = {{
            "", "north", "east", "south", "west"
        }
    };
    if( dir == om_direction::type::invalid ) {
        debugmsg( "Invalid direction cannot have an id." );
    }
    return ids[static_cast<size_t>( dir ) + 1];
}
References debugmsg, and invalid.
Referenced by jmapgen_nested::neighborhood_check::neighborhood_check().
name()
std::string om_direction::name (type dir)
Get Human readable name of a direction.
Definition at line 4127 of file overmap.cpp.
{
    static const std::array < std::string, size + 1 > names = {{
            translate_marker( "invalid" ), translate_marker( "north" ),
            translate_marker( "east" ), translate_marker( "south" ),
            translate_marker( "west" )
        }
    };
    return _( names[static_cast<size_t>( dir ) + 1] );
}
References _, Name::names, and translate_marker.
Referenced by computer_session::action_list_bionics(), advanced_inventory::action_move_item(), zone_manager::add(), add_array_to_set(), color_manager::add_color(), input_manager::add_gamepad_keycode_pair(), input_manager::add_keycode_pair(), inventory_selector::add_map_items(), WORLD::add_save(), inventory_selector::add_vehicle_items(), MAP_SHARING::addAdmin(), MAP_SHARING::addDebugger(), addiction_type(), options_manager::addOptionToPage(), item::ammo_info(), basic_format_context< OutputIt, Char >::arg(), arg(), basic_format_context< OutputIt, Char >::arg_id(), assign(), assign_dmg_proportional(), assign_map_from_array(), assign_unit_common(), item::basic_info(), item::book_info(), game::chat(), event_transformation_impl::check(), event_statistic_total::check(), event_statistic_maximum::check(), event_statistic_minimum::check(), event_statistic_unique_value::check(), value_constraint::check(), check_assigned_dmg(), colorized_ter_name_flags_at(), colorized_trap_name_at(), talk_function::companion_choose_return(), item::components_to_string(), decorate_panel(), basecamp::deserialize(), color_manager::deserialize(), faction::deserialize(), help::deserialize(), teleporter_list::deserialize(), options_manager::deserialize(), panel_manager::deserialize(), vehicle::deserialize(), mongroup::deserialize_legacy(), character_display::disp_info(), game::disp_NPCs(), faction_manager::display(), input_context::display_menu(), item::display_name(), veh_interact::do_install(), generic_typed_reader< Derived >::do_relative(), veh_interact::do_rename(), construct::done_vehicle(), draw_bionics_tab(), draw_stats_tab(), dt_by_name(), editmap::edit_feature(), item::erase_var(), game::find_nearby_items(), query_popup::fold_query(), basic_format_args< Context >::get(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_enum_value(), JsonObject::get_float(), inventory_selector::get_footer(), basic_format_args< Context >::get_id(), JsonObject::get_int(), JsonObject::get_int_array(), input_manager::get_keycode(), JsonObject::get_member(), JsonObject::get_object(), options_manager::get_option(), get_option(), JsonObject::get_raw(), JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::get_tags(), item::get_var(), worldfactory::get_world(), options_manager::cOpt::getDefaultText(), options_manager::cOpt::getValueName(), game::handle_action(), detail::handle_dynamic_spec(), handle_main_menu(), handle_proportional(), handle_relative(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_float(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_null(), JsonObject::has_number(), JsonObject::has_object(), options_manager::has_option(), JsonObject::has_string(), item::has_var(), worldfactory::has_world(), color_manager::highlight_from_names(), learn_spell_actor::info(), input_manager::init_keycode_mapping(), place_trap_actor::is_allowed(), is_ot_match(), item_save_monsters(), lcmatch(), JsonIn::line_number(), diary::load(), scenario::load(), game::load(), input_manager::load(), submap::load(), load_distribution(), load_external_option(), WORLD::load_legacy_options(), load_min_max(), monfactions::load_monster_faction(), WORLD::load_options(), Item_factory::load_string(), Item_factory::load_sub_ref(), MonsterGroupManager::LoadMonsterGroup(), item::make_corpse(), mandatory(), JsonObject::mark_visited(), item::med_info(), JsonOut::member(), JsonOut::member_as_string(), options_manager::migrateOptionName(), options_manager::migrateOptionValue(), diary::mission_changes(), game::mon_info(), msg_type_from_name(), name_and_value(), color_manager::name_to_color(), color_manager::name_to_id(), inventory_selector::naturalize_category(), iexamine::none(), memorial_logger::notify(), npc_select_menu(), safemode::npc_type_name(), JsonOut::null_member(), open(), optional(), talk_effect_t::parse_sub_effect(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), iexamine::portable_structure(), dialogue_window::print_header(), prompt_select_lang_on_startup(), JsonObject::read(), generic_typed_reader< Derived >::read_normal(), read_with_factor(), input_context::register_action(), replace_city_tag(), report_strict_violation(), JsonObject::report_unvisited(), recipe::result_name(), WORLD::save_exists(), character_funcs::select_ammo(), known_magic::select_spell(), basecamp::serialize(), faction::serialize(), vehicle::serialize(), set_description(), set_scenario(), talk_effect_fun_t::set_u_buy_monster(), item::set_var(), MAP_SHARING::setUsername(), options_manager::show(), panel_manager::show_adm(), worldfactory::show_modselection_window(), overmap_ui::show_notes_manager(), JsonObject::show_warning(), defense_game::special_wave_message(), game::start_game(), talk_function::start_training(), diary::store(), JsonObject::throw_error(), to_lower_case(), to_upper_case(), iuse::towel_common(), overmap::unserialize(), game::unserialize_master(), overmap::unserialize_view(), worldfactory::valid_worldname(), iexamine::vending(), JsonObject::verify_position(), game::vertical_move(), and game::zones_manager().
opposite()
om_direction::type om_direction::opposite (type dir)
Returns an opposite direction.
Definition at line 4213 of file overmap.cpp.
{
    return rotate_internal( dir, static_cast<int>( size ) / 2 );
}
References rotate_internal(), and om_lines::size.
Referenced by are_parallel(), overmap::build_city_street(), overmap::build_connection(), elevate_bridges(), overmap::lay_out_street(), mapgen_rotate(), and overmap::place_building().
random()
om_direction::type om_direction::random ()
Returns a random direction.
Definition at line 4218 of file overmap.cpp.
{
    return static_cast<type>( rng( 0, size - 1 ) );
}
References rng(), and om_lines::size.
Referenced by Character::bonus_damage(), and overmap::place_cities().
rotate() [1/2]
point om_direction::rotate (const point & p, type dir)
Various rotations.
Definition at line 4150 of file overmap.cpp.
{
    switch( dir ) {
        case om_direction::type::invalid:
            debugmsg( "Invalid overmap rotation (%d).", static_cast<int>( dir ) );
        // Intentional fallthrough.
        case om_direction::type::north:
            break;  // No need to do anything.
        case om_direction::type::east:
            return point( -p.y, p.x );
        case om_direction::type::south:
            return point( -p.x, -p.y );
        case om_direction::type::west:
            return point( p.y, -p.x );
    }
    return p;
}
References debugmsg, east, invalid, north, south, west, point::x, and point::y.
Referenced by overmap_ui::draw_ascii(), overmap::place_special(), overmap_ui::place_ter_or_special(), and overmap::random_special_rotation().
rotate() [2/2]
tripoint om_direction::rotate (const tripoint & p, type dir)
Definition at line 4168 of file overmap.cpp.
{
    return tripoint( rotate( { p.xy() }, dir ), p.z );
}
References rotate(), tripoint::xy(), and tripoint::z.
rotate_symbol()
uint32_t om_direction::rotate_symbol (uint32_t sym, type dir)
Definition at line 4173 of file overmap.cpp.
{
    return rotatable_symbols::get( sym, static_cast<int>( dir ) );
}
References rotatable_symbols::get().
turn_left()
om_direction::type om_direction::turn_left (type dir)
Turn by 90 degrees to the left, to the right, or randomly (either left or right).
Definition at line 4198 of file overmap.cpp.
{
    return rotate_internal( dir, -static_cast<int>( size ) / 4 );
}
References rotate_internal(), and om_lines::size.
Referenced by overmap::build_city_street(), and turn_random().
turn_random()
om_direction::type om_direction::turn_random (type dir)
Definition at line 4208 of file overmap.cpp.
{
    return rng( 0, 1 ) ? turn_left( dir ) : turn_right( dir );
}
References rng(), turn_left(), and turn_right().
Referenced by overmap::build_city_street().
turn_right()
om_direction::type om_direction::turn_right (type dir)
Definition at line 4203 of file overmap.cpp.
{
    return rotate_internal( dir, static_cast<int>( size ) / 4 );
}
References rotate_internal(), and om_lines::size.
Referenced by overmap::build_city_street(), overmap::place_cities(), overmap_ui::place_ter_or_special(), and turn_random().
Variable Documentation
all
const std::array<type, 4> om_direction::all = {{ type::north, type::east, type::south, type::west }}
For the purposes of iteration.
Definition at line 26 of file om_direction.h.
Referenced by overmap::build_anthill(), overmap::build_connection(), overmap::build_tunnel(), player::check_eligible_containers_for_crafting(), oter_type_t::finalize(), find_all_effect_types(), materials::get_compactable(), materials::get_rotting(), pf::greedy_path(), overmap_connections::guess_for(), jmapgen_nested::neighborhood_check::neighborhood_check(), oter_get_rotation_dir(), scenario::permitted_professions(), Character::pick_technique(), overmap_ui::place_ter_or_special(), overmap::random_special_rotation(), terrain_type_to_nesw_array(), and jmapgen_nested::neighborhood_check::test().
all_ccw_rotations
const std::array<int, 4> om_direction::all_ccw_rotations = { { 0, 3, 2, 1 } }
Definition at line 32 of file om_direction.h.
Referenced by get_num_ccw_rotations().
all_cw_rotations
const std::array<int, 4> om_direction::all_cw_rotations = {{ 0, 1, 2, 3 }}
Definition at line 31 of file om_direction.h.
Referenced by get_num_cw_rotations().
all_suffixes
const std::array<std::string, 4> om_direction::all_suffixes = {{ "_north", "_east", "_south", "_west" }}
Definition at line 29 of file om_direction.h.
Referenced by elevate_bridges(), and get_suffix().
bits
const size_t om_direction::bits = static_cast<size_t>(-1) >> (CHAR_BIT *sizeof(size_t) - size)
Number of bits needed to store directions.
Definition at line 66 of file om_direction.h.
Referenced by om_lines::rotate().
invalid_dir_rotations
const int om_direction::invalid_dir_rotations = 0
Definition at line 33 of file om_direction.h.
Referenced by get_num_ccw_rotations(), and get_num_cw_rotations().
invalid_dir_suffix
const std::string om_direction::invalid_dir_suffix
Definition at line 30 of file om_direction.h.
Referenced by get_suffix().
size
const size_t om_direction::size = all.size()
Definition at line 27 of file om_direction.h.
Referenced by cata::list< element_type, element_allocator_type >::group_vector::add_new(), map::add_vehicle_to_map(), cata::list< element_type, element_allocator_type >::group_vector::append(), detail::bigint::assign(), best_installer(), cata::list< element_type, element_allocator_type >::group_vector::blank(), overmap::build_tunnel(), defense_game::caravan(), game::cleanup_at_end(), detail::code_point_index(), construction_menu(), detail::count_code_points(), string_editor_window::cursor_leftright(), string_editor_window::cursor_updown(), faction::deserialize(), cata::list< element_type, element_allocator_type >::group_vector::destroy_all_data(), distribution::dice_roll(), anonymous_namespace{line.cpp}::direction_name_impl(), talk_function::draw_camp_tabs(), cata::list< element_type, element_allocator_type >::group_vector::expand_capacity(), mdeath::explode(), fac_wealth_text(), oter_type_t::finalize(), overmap_connection::finalize(), find_minimum_fold_width(), detail::iterator_buffer< OutputIt, T, Traits >::flush(), fmt_mask(), detail::format_decimal(), detail::format_float(), detail::fwrite_fully(), CellularAutomata::generate_cellular_automaton(), lightson_game::generate_change_coords(), anatomy::get_part_with_cumulative_hit_size(), get_random_index(), oter_type_t::get_rotated(), inventory_selector::get_stats(), pf::greedy_path(), basic_memory_buffer< T, SIZE, Allocator >::grow(), cata::list< element_type, element_allocator_type >::group_vector::initialize(), detail::buffer_traits::limit(), detail::fixed_buffer_traits::limit(), cata::event::make(), mapgen_parking_lot(), veh_interact::move_in_list(), cata::list< element_type, element_allocator_type >::group_vector::move_to_back(), MapExtras::mx_crater(), CellularAutomata::neighbor_count(), detail::int_writer< OutputIt, Char, UInt >::on_num(), detail::format_handler< OutputIt, Char, Context >::on_text(), detail::utf8_to_utf16::operator wstring_view(), detail::fill_t< Char >::operator=(), cata::list< element_type, element_allocator_type >::group_vector::operator=(), pickup::pick_up(), worldfactory::pick_world(), ui_adaptor::position(), advanced_inventory::query_destination(), overmap::random_special_rotation(), range_with_even_chance_of_good_hit(), cata::list< element_type, element_allocator_type >::group_vector::remove(), detail::reserve(), om_lines::rotate(), rotate_internal(), faction::serialize(), border_helper::border_info::set(), achievement_tracker::set_requirement(), worldfactory::show_modselection_window(), size_factor_in_time_to_cut(), detail::snprintf_float(), detail::utf8_to_utf16::str(), vehicle::sufficient_wheel_config(), cata::list< element_type, element_allocator_type >::group_vector::swap(), detail::to_pointer(), to_string(), cata::list< element_type, element_allocator_type >::group_vector::trim_trailing_groups(), iuse::unfold_generic(), npc::vehicle_danger(), vfprintf(), monster::will_join_horde(), detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write(), detail::write(), detail::write_buffer(), detail::write_float(), detail::write_int_data< Char >::write_int_data(), detail::write_nonfinite(), detail::write_padded(), and detail::write_ptr().