Cataclysm BN: map_funcs Namespace Reference
map_funcs Namespace Reference
Functions
int climbing_cost (const map &m, const tripoint &from, const tripoint &to)
Checks both the neighborhoods of from and to for climbable surfaces, returns move cost of climbing from from to to.
void migo_nerve_cage_removal (map &m, const tripoint &p, bool spawn_damaged)
Function Documentation
climbing_cost()
int map_funcs::climbing_cost (const map & m, const tripoint & from, const tripoint & to)
Checks both the neighborhoods of from and to for climbable surfaces, returns move cost of climbing from from to to.
0 means climbing is not possible. Return value can depend on the orientation of the terrain.
Definition at line 16 of file map_functions.cpp.
{
    // TODO: All sorts of mutations, equipment weight etc. for characters
    if( !m.valid_move( from, to, false, true ) ) {
        return 0;
    }
    const int diff = m.climb_difficulty( from );
    if( diff > 5 ) {
        return 0;
    }
    return 50 + diff * 100;
}
References map::climb_difficulty(), and map::valid_move().
Referenced by iexamine::ledge(), and game::vertical_move().
migo_nerve_cage_removal()
void map_funcs::migo_nerve_cage_removal (map & m, const tripoint & p, bool spawn_damaged)
Definition at line 29 of file map_functions.cpp.
{
    bool open = false;
    for( const tripoint &tmp : m.points_in_radius( p, 12 ) ) {
        if( m.ter( tmp ) == ter_id( "t_wall_resin_cage" ) ) {
            m.ter_set( tmp, ter_id( "t_floor_resin" ) );
            open = true;
        }
    }
    if( open ) {
        add_msg( m_good, _( "The nerve cluster collapses in on itself, and the nearby cages open!" ) );
    } else {
        add_msg( _( "The nerve cluster collapses in on itself, to no discernible effect." ) );
    }
    sounds::sound( p, 120, sounds::sound_t::combat,
                   _( "a loud alien shriek reverberating through the structure!" ), true,
                   "shout", "scream_tortured" );
    monster *const spawn = g->place_critter_around( mon_mi_go_myrmidon, p, 1 );
    if( spawn_damaged ) {
        spawn->set_hp( spawn->get_hp_max() / 2 );
    }
    if( get_player_character().sees( p ) ) {
        add_msg( m_bad, _( "Something stirs and clambers out of the ruined mass of flesh and nerves!" ) );
    }
}
References _, add_msg(), sounds::combat, g, monster::get_hp_max(), get_player_character(), m_bad, m_good, mon_mi_go_myrmidon, open(), map::points_in_radius(), monster::set_hp(), sounds::sound(), map::ter(), and map::ter_set().
Referenced by map::bash_furn_success(), and iexamine::migo_nerve_cluster().