Cataclysm BN: charge_removal_blacklist Namespace Reference
charge_removal_blacklist Namespace Reference
Functions
const std::set< itype_id > & get ()
void load (const JsonObject &jo)
void reset ()
Variables
static std::set< itype_id > removal_list
Function Documentation
get()
const std::set< itype_id > & charge_removal_blacklist::get ()
Definition at line 2096 of file savegame_json.cpp.
{
    return removal_list;
}
References removal_list.
Referenced by jmapgen_setmap::apply(), cata::poly_serialized< T >::deserialize(), cata::value_ptr< T >::deserialize(), jmapgen_setmap::has_vehicle_collision(), worldfactory::init(), item::io(), cata::poly_serialized< T >::serialize(), cata::value_ptr< T >::serialize(), and game::zones_manager().
load()
void charge_removal_blacklist::load (const JsonObject & jo)
Definition at line 2100 of file savegame_json.cpp.
{
    std::set<std::string> d = jo.get_tags( "list" );
    for( const std::string &s : d ) {
        removal_list.insert( itype_id( s ) );
    }
}
References JsonObject::get_tags(), itype_id, and removal_list.
Referenced by DynamicDataLoader::initialize().
reset()
void charge_removal_blacklist::reset ()
Definition at line 2107 of file savegame_json.cpp.
{
    removal_list.clear();
}
References removal_list.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
removal_list
std::set<itype_id> charge_removal_blacklist::removal_list static
Definition at line 2094 of file savegame_json.cpp.
Referenced by get(), load(), and reset().