Cataclysm BN: weather Namespace Reference
weather Namespace Reference
"Weather and its implications."
Functions
bool is_sheltered (const map &m, const tripoint &p)
bool is_in_sunlight (const map &m, const tripoint &p, const weather_type_id &weather)
Function Documentation
is_in_sunlight()
bool weather::is_in_sunlight (const map & m, const tripoint & p, const weather_type_id & weather)
Definition at line 1162 of file weather.cpp.
{
    // TODO: Remove that game reference and include light in weather data
    return m.is_outside( p ) && g->light_level( p.z ) >= 40 && !is_night( calendar::turn ) &&
           weather->sun_intensity >= sun_intensity_type::normal;
}
References g, is_night(), map::is_outside(), normal, calendar::turn, and tripoint::z.
Referenced by game::is_in_sunlight(), and Character::update_bodytemp().
is_sheltered()
bool weather::is_sheltered (const map & m, const tripoint & p)
Definition at line 1153 of file weather.cpp.
{
    const optional_vpart_position vp = m.veh_at( p );
    return ( !m.is_outside( p ) ||
             p.z < 0 ||
             ( vp && vp->is_inside() ) );
}
References map::is_outside(), map::veh_at(), and tripoint::z.
Referenced by game::is_sheltered(), firestarter_actor::light_mod(), and Character::update_bodytemp().