Cataclysm BN: anonymous_namespace{armor_layers.cpp} Namespace Reference
anonymous_namespace{armor_layers.cpp} Namespace Reference
Classes
struct item_penalties
Functions
std::string clothing_layer (const item &worn_item)
std::vector< std::string > clothing_properties (const item &worn_item, int width, const Character &)
std::vector< std::string > clothing_protection (const item &worn_item, int width)
std::vector< std::string > clothing_flags_description (const item &worn_item)
item_penalties get_item_penalties (std::list< item >::const_iterator worn_item_it, const Character &c, int tabindex)
std::string body_part_names (const std::vector< body_part > &parts)
void draw_mid_pane (const catacurses::window &w_sort_middle, std::list< item >::const_iterator const worn_item_it, const Character &c, int tabindex)
Function Documentation
body_part_names()
std::string anonymous_namespace{armor_layers.cpp}::body_part_names (const std::vector< body_part > & parts)
Definition at line 144 of file armor_layers.cpp.
{
    if( parts.empty() ) {
        debugmsg( "Asked for names of empty list" );
        return {};
    }
    std::vector<std::string> names;
    names.reserve( parts.size() );
    for( size_t i = 0; i < parts.size(); ++i ) {
        const body_part part = parts[i];
        if( i + 1 < parts.size() && parts[i + 1] == static_cast<body_part>( bp_aiOther[part] ) ) {
            // Can combine two body parts (e.g. arms)
            names.push_back( body_part_name_accusative( part, 2 ) );
            ++i;
        } else {
            names.push_back( body_part_name_accusative( part ) );
        }
    }
    return enumerate_as_string( names );
}
References body_part_name_accusative(), bp_aiOther, debugmsg, enumerate_as_string(), and Name::names.
Referenced by draw_mid_pane().
clothing_flags_description()
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_flags_description (const item & worn_item)
Definition at line 337 of file armor_layers.cpp.
{
    std::vector<std::string> description_stack;
    if( worn_item.has_flag( flag_FIT ) ) {
        description_stack.push_back( _( "It fits you well." ) );
    } else if( worn_item.has_flag( "VARSIZE" ) ) {
        description_stack.push_back( _( "It could be refitted." ) );
    }
    if( worn_item.has_flag( flag_HOOD ) ) {
        description_stack.push_back( _( "It has a hood." ) );
    }
    if( worn_item.has_flag( flag_POCKETS ) ) {
        description_stack.push_back( _( "It has pockets." ) );
    }
    if( worn_item.has_flag( flag_WATERPROOF ) ) {
        description_stack.push_back( _( "It is waterproof." ) );
    }
    if( worn_item.has_flag( flag_WATER_FRIENDLY ) ) {
        description_stack.push_back( _( "It is water friendly." ) );
    }
    if( worn_item.has_flag( flag_FANCY ) ) {
        description_stack.push_back( _( "It looks fancy." ) );
    }
    if( worn_item.has_flag( flag_SUPER_FANCY ) ) {
        description_stack.push_back( _( "It looks really fancy." ) );
    }
    if( worn_item.has_flag( flag_FLOTATION ) ) {
        description_stack.push_back( _( "You will not drown today." ) );
    }
    if( worn_item.has_flag( flag_OVERSIZE ) ) {
        description_stack.push_back( _( "It is very bulky." ) );
    }
    if( worn_item.has_flag( flag_SWIM_GOGGLES ) ) {
        description_stack.push_back( _( "It helps you to see clearly underwater." ) );
    }
    if( worn_item.has_flag( flag_SEMITANGIBLE ) ) {
        description_stack.push_back( _( "It can occupy the same space as other things." ) );
    }
    if( worn_item.has_flag( flag_COMPACT ) ) {
        description_stack.push_back( _( "It won't encumber you when worn with other things." ) );
    }
    return description_stack;
}
References _, flag_COMPACT(), flag_FANCY(), flag_FIT(), flag_FLOTATION(), flag_HOOD(), flag_OVERSIZE(), flag_POCKETS(), flag_SEMITANGIBLE(), flag_SUPER_FANCY(), flag_SWIM_GOGGLES(), flag_WATER_FRIENDLY(), flag_WATERPROOF(), and item::has_flag().
Referenced by draw_mid_pane().
clothing_layer()
std::string anonymous_namespace{armor_layers.cpp}::clothing_layer (const item & worn_item)
Definition at line 274 of file armor_layers.cpp.
{
    std::string layer;
    if( worn_item.has_flag( flag_PERSONAL ) ) {
        layer = _( "This is in your personal aura." );
    } else if( worn_item.has_flag( flag_SKINTIGHT ) ) {
        layer = _( "This is worn next to the skin." );
    } else if( worn_item.has_flag( flag_WAIST ) ) {
        layer = _( "This is worn on or around your waist." );
    } else if( worn_item.has_flag( flag_OUTER ) ) {
        layer = _( "This is worn over your other clothes." );
    } else if( worn_item.has_flag( flag_BELTED ) ) {
        layer = _( "This is strapped onto you." );
    } else if( worn_item.has_flag( flag_AURA ) ) {
        layer = _( "This is an aura around you." );
    }
    return layer;
}
References _, flag_AURA(), flag_BELTED(), flag_OUTER(), flag_PERSONAL(), flag_SKINTIGHT(), flag_WAIST(), and item::has_flag().
Referenced by draw_mid_pane().
clothing_properties()
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_properties (const item & worn_item, int width, const Character & c)
Definition at line 295 of file armor_layers.cpp.
{
    std::vector<std::string> props;
    props.reserve( 5 );
    const std::string space = "  ";
    props.push_back( string_format( "<color_c_green>[%s]</color>", _( "Properties" ) ) );
    props.push_back( name_and_value( space + _( "Coverage:" ),
                                     string_format( "%3d", worn_item.get_coverage() ), width ) );
    props.push_back( name_and_value( space + _( "Encumbrance:" ),
                                     string_format( "%3d", worn_item.get_encumber( c ) ),
                                     width ) );
    props.push_back( name_and_value( space + _( "Warmth:" ),
                                     string_format( "%3d", worn_item.get_warmth() ), width ) );
    props.push_back( name_and_value( space + string_format( _( "Storage (%s):" ), volume_units_abbr() ),
                                     format_volume( worn_item.get_storage() ), width ) );
    return props;
}
References _, c, format_volume(), item::get_coverage(), item::get_encumber(), item::get_storage(), item::get_warmth(), name_and_value(), sign::space, string_format(), and volume_units_abbr().
Referenced by draw_mid_pane().
clothing_protection()
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_protection (const item & worn_item, int width)
Definition at line 315 of file armor_layers.cpp.
{
    std::vector<std::string> prot;
    prot.reserve( 6 );
    const std::string space = "  ";
    prot.push_back( string_format( "<color_c_green>[%s]</color>", _( "Protection" ) ) );
    prot.push_back( name_and_value( space + _( "Bash:" ),
                                    string_format( "%3d", static_cast<int>( worn_item.bash_resist() ) ), width ) );
    prot.push_back( name_and_value( space + _( "Cut:" ),
                                    string_format( "%3d", static_cast<int>( worn_item.cut_resist() ) ), width ) );
    prot.push_back( name_and_value( space + _( "Ballistic:" ),
                                    string_format( "%3d", static_cast<int>( worn_item.bullet_resist() ) ), width ) );
    prot.push_back( name_and_value( space + _( "Acid:" ),
                                    string_format( "%3d", static_cast<int>( worn_item.acid_resist() ) ), width ) );
    prot.push_back( name_and_value( space + _( "Fire:" ),
                                    string_format( "%3d", static_cast<int>( worn_item.fire_resist() ) ), width ) );
    prot.push_back( name_and_value( space + _( "Environmental:" ),
                                    string_format( "%3d", static_cast<int>( worn_item.get_env_resist() ) ), width ) );
    return prot;
}
References _, item::acid_resist(), item::bash_resist(), item::bullet_resist(), item::cut_resist(), item::fire_resist(), item::get_env_resist(), name_and_value(), sign::space, and string_format().
Referenced by draw_mid_pane().
draw_mid_pane()
void anonymous_namespace{armor_layers.cpp}::draw_mid_pane (const catacurses::window & w_sort_middle, std::list< item >::const_iterator const worn_item_it, const Character & c, int tabindex)
Definition at line 167 of file armor_layers.cpp.
{
    const int win_width = getmaxx( w_sort_middle );
    const size_t win_height = static_cast<size_t>( getmaxy( w_sort_middle ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    size_t i = fold_and_print( w_sort_middle, point( 1, 0 ), win_width - 1, c_white,
                               worn_item_it->type_name( 1 ) ) - 1;
    std::vector<std::string> props = clothing_properties( *worn_item_it, win_width - 3, c );
    nc_color color = c_light_gray;
    for( std::string &iter : props ) {
        print_colored_text( w_sort_middle, point( 2, ++i ), color, c_light_gray, iter );
    }
    std::vector<std::string> prot = clothing_protection( *worn_item_it, win_width - 3 );
    if( i + prot.size() < win_height ) {
        for( std::string &iter : prot ) {
            print_colored_text( w_sort_middle, point( 2, ++i ), color, c_light_gray, iter );
        }
    } else {
        return;
    }
    i++;
    std::vector<std::string> layer_desc = foldstring( clothing_layer( *worn_item_it ), win_width );
    if( i + layer_desc.size() < win_height && !clothing_layer( *worn_item_it ).empty() ) {
        for( std::string &iter : layer_desc ) {
            mvwprintz( w_sort_middle, point( 0, ++i ), c_light_blue, iter );
        }
    }
    i++;
    std::vector<std::string> desc = clothing_flags_description( *worn_item_it );
    if( !desc.empty() ) {
        for( size_t j = 0; j < desc.size() && i + j < win_height; ++j ) {
            i += fold_and_print( w_sort_middle, point( 0, i ), win_width, c_light_blue, desc[j] );
        }
    }
    const item_penalties penalties = get_item_penalties( worn_item_it, c, tabindex );
    if( !penalties.body_parts_with_stacking_penalty.empty() ) {
        std::string layer_description = [&]() {
            switch( worn_item_it->get_layer() ) {
                case PERSONAL_LAYER:
                    return _( "in your <color_light_blue>personal aura</color>" );
                case UNDERWEAR_LAYER:
                    return _( "<color_light_blue>close to your skin</color>" );
                case REGULAR_LAYER:
                    return _( "of <color_light_blue>normal</color> clothing" );
                case WAIST_LAYER:
                    return _( "on your <color_light_blue>waist</color>" );
                case OUTER_LAYER:
                    return _( "of <color_light_blue>outer</color> clothing" );
                case BELTED_LAYER:
                    return _( "<color_light_blue>strapped</color> to you" );
                case AURA_LAYER:
                    return _( "an <color_light_blue>aura</color> around you" );
                default:
                    return _( "Unexpected layer" );
            }
        }
        ();
        std::string body_parts =
            body_part_names( penalties.body_parts_with_stacking_penalty );
        std::string message =
            string_format(
                vgettext( "Wearing multiple items %s on your "
                          "<color_light_red>%s</color> is adding encumbrance there.",
                          "Wearing multiple items %s on your "
                          "<color_light_red>%s</color> is adding encumbrance there.",
                          penalties.body_parts_with_stacking_penalty.size() ),
                layer_description, body_parts
            );
        i += fold_and_print( w_sort_middle, point( 0, i ), win_width, c_light_gray, message );
    }
    if( !penalties.body_parts_with_out_of_order_penalty.empty() ) {
        std::string body_parts =
            body_part_names( penalties.body_parts_with_out_of_order_penalty );
        std::string message;
        if( penalties.bad_items_within.empty() ) {
            message = string_format(
                          vgettext( "Wearing this outside items it would normally be beneath "
                                    "is adding encumbrance to your <color_light_red>%s</color>.",
                                    "Wearing this outside items it would normally be beneath "
                                    "is adding encumbrance to your <color_light_red>%s</color>.",
                                    penalties.body_parts_with_out_of_order_penalty.size() ),
                          body_parts
                      );
        } else {
            std::string bad_item_name = *penalties.bad_items_within.begin();
            message = string_format(
                          vgettext( "Wearing this outside your <color_light_blue>%s</color> "
                                    "is adding encumbrance to your <color_light_red>%s</color>.",
                                    "Wearing this outside your <color_light_blue>%s</color> "
                                    "is adding encumbrance to your <color_light_red>%s</color>.",
                                    penalties.body_parts_with_out_of_order_penalty.size() ),
                          bad_item_name, body_parts
                      );
        }
        fold_and_print( w_sort_middle, point( 0, i ), win_width, c_light_gray, message );
    }
}
References _, AURA_LAYER, anonymous_namespace{armor_layers.cpp}::item_penalties::bad_items_within, BELTED_LAYER, body_part_names(), anonymous_namespace{armor_layers.cpp}::item_penalties::body_parts_with_out_of_order_penalty, anonymous_namespace{armor_layers.cpp}::item_penalties::body_parts_with_stacking_penalty, c, c_light_blue, c_light_gray, c_white, clothing_flags_description(), clothing_layer(), clothing_properties(), clothing_protection(), color(), fold_and_print(), foldstring(), get_item_penalties(), catacurses::getmaxx(), catacurses::getmaxy(), mapgen_defer::message, mvwprintz(), OUTER_LAYER, PERSONAL_LAYER, print_colored_text(), REGULAR_LAYER, string_format(), UNDERWEAR_LAYER, vgettext(), and WAIST_LAYER.
Referenced by player::sort_armor().
get_item_penalties()
item_penalties anonymous_namespace{armor_layers.cpp}::get_item_penalties (std::list< item >::const_iterator worn_item_it, const Character & c, int tabindex)
Definition at line 84 of file armor_layers.cpp.
{
    layer_level layer = worn_item_it->get_layer();
    std::vector<body_part> body_parts_with_stacking_penalty;
    std::vector<body_part> body_parts_with_out_of_order_penalty;
    std::vector<std::set<std::string>> lists_of_bad_items_within;
    for( body_part bp : all_body_parts ) {
        if( bp != tabindex && num_bp != tabindex ) {
            continue;
        }
        if( !worn_item_it->covers( bp ) ) {
            continue;
        }
        const int num_items = std::count_if( c.worn.begin(), c.worn.end(),
        [layer, bp]( const item & i ) {
            return i.get_layer() == layer && i.covers( bp ) && !( i.has_flag( flag_SEMITANGIBLE ) ||
                    i.has_flag( flag_COMPACT ) );
        } );
        if( num_items > 1 ) {
            body_parts_with_stacking_penalty.push_back( bp );
        }
        std::set<std::string> bad_items_within;
        for( auto it = c.worn.begin(); it != worn_item_it; ++it ) {
            if( it->get_layer() > layer && it->covers( bp ) ) {
                bad_items_within.insert( it->type_name() );
            }
        }
        if( !bad_items_within.empty() ) {
            body_parts_with_out_of_order_penalty.push_back( bp );
            lists_of_bad_items_within.push_back( bad_items_within );
        }
    }
    // We intersect all the lists_of_bad_items_within so that if there is one
    // common bad item we're wearing this one over it can be mentioned in the
    // message explaining the penalty.
    while( lists_of_bad_items_within.size() > 1 ) {
        std::set<std::string> intersection_of_first_two;
        std::set_intersection(
            lists_of_bad_items_within[0].begin(), lists_of_bad_items_within[0].end(),
            lists_of_bad_items_within[1].begin(), lists_of_bad_items_within[1].end(),
            std::inserter( intersection_of_first_two, intersection_of_first_two.begin() )
        );
        lists_of_bad_items_within.erase( lists_of_bad_items_within.begin() );
        lists_of_bad_items_within[0] = std::move( intersection_of_first_two );
    }
    if( lists_of_bad_items_within.empty() ) {
        lists_of_bad_items_within.emplace_back();
    }
    return { std::move( body_parts_with_stacking_penalty ),
             std::move( body_parts_with_out_of_order_penalty ),
             std::move( lists_of_bad_items_within[0] ) };
}
References all_body_parts, c, avatar_action::move(), and num_bp.
Referenced by draw_mid_pane(), items_cover_bp(), and player::sort_armor().