Cataclysm BN: mdeath Namespace Reference
mdeath Namespace Reference
Functions
void normal (monster &z)
void splatter (monster &z)
void acid (monster &z)
void boomer (monster &z)
void boomer_glow (monster &z)
void kill_vines (monster &z)
void vine_cut (monster &z)
void triffid_heart (monster &z)
void fungus (monster &z)
void disintegrate (monster &z)
void shriek (monster &z)
void howl (monster &z)
void rattle (monster &z)
void worm (monster &z)
void disappear (monster &z)
void guilt (monster &z)
void brainblob (monster &z)
void blobsplit (monster &z)
void jackson (monster &z)
void melt (monster &z)
void amigara (monster &z)
void thing (monster &z)
void explode (monster &z)
void focused_beam (monster &z)
void broken (monster &z)
void ratking (monster &z)
void darkman (monster &z)
void gas (monster &z)
void kill_breathers (monster &z)
void smokeburst (monster &z)
void fungalburst (monster &z)
void jabberwock (monster &z)
void detonate (monster &z)
void broken_ammo (monster &z)
void preg_roach (monster &z)
void fireball (monster &z)
void conflagration (monster &z)
void gameover (monster &z)
Function Documentation
acid()
void mdeath::acid (monster & z)
Definition at line 257 of file mondeath.cpp.
{
    if( g->u.sees( z ) ) {
        if( z.type->dies.size() ==
            1 ) { //If this death function is the only function. The corpse gets dissolved.
            add_msg( m_mixed, _( "The %s's body dissolves into acid." ), z.name() );
        } else {
            add_msg( m_warning, _( "The %s's body leaks acid." ), z.name() );
        }
    }
    g->m.add_field( z.pos(), fd_acid, 3 );
}
References _, add_msg(), mtype::dies, fd_acid, g, m_mixed, m_warning, monster::name(), monster::pos(), and monster::type.
Referenced by MonsterGenerator::init_death().
amigara()
void mdeath::amigara (monster & z)
Definition at line 553 of file mondeath.cpp.
{
    const bool has_others = g->get_creature_if( [&]( const Creature & critter ) {
        if( const monster *const candidate = dynamic_cast<const monster *>( &critter ) ) {
            return candidate->type == z.type;
        }
        return false;
    } );
    if( has_others ) {
        return;
    }
    // We were the last!
    if( g->u.has_effect( effect_amigara ) ) {
        g->u.remove_effect( effect_amigara );
        add_msg( _( "Your obsession with the fault fades away…" ) );
    }
    g->m.spawn_artifact( z.pos() );
}
References _, add_msg(), effect_amigara, g, monster::pos(), and monster::type.
Referenced by MonsterGenerator::init_death().
blobsplit()
void mdeath::blobsplit (monster & z)
Definition at line 494 of file mondeath.cpp.
{
    int speed = z.get_speed() - rng( 30, 50 );
    g->m.spawn_item( z.pos(), "slime_scrap", 1, 0, calendar::turn );
    if( z.get_speed() <= 0 ) {
        if( g->u.sees( z ) ) {
            // TODO: Add vermin-tagged tiny versions of the splattered blob  :)
            add_msg( m_good, _( "The %s splatters apart." ), z.name() );
        }
        return;
    }
    if( g->u.sees( z ) ) {
        if( z.type->dies.size() == 1 ) {
            add_msg( m_good, _( "The %s splits in two!" ), z.name() );
        } else {
            add_msg( m_bad, _( "Two small blobs slither out of the corpse." ) );
        }
    }
    const mtype_id &child = speed < 50 ? mon_blob_small : mon_blob;
    for( int s = 0; s < 2; s++ ) {
        if( monster *const blob = g->place_critter_around( child, z.pos(), 1 ) ) {
            blob->make_ally( z );
            blob->set_speed_base( speed );
            blob->set_hp( speed );
        }
    }
}
References _, add_msg(), mtype::dies, g, Creature::get_speed(), m_bad, m_good, mon_blob, mon_blob_small, monster::name(), monster::pos(), rng(), calendar::turn, and monster::type.
Referenced by brainblob(), and MonsterGenerator::init_death().
boomer()
void mdeath::boomer (monster & z)
Definition at line 270 of file mondeath.cpp.
{
    std::string explode = string_format( _( "a %s explode!" ), z.name() );
    sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "small" );
    for( const tripoint &dest : g->m.points_in_radius( z.pos(), 1 ) ) { // *NOPAD*
        g->m.bash( dest, 10 );
        if( monster *const target = g->critter_at<monster>( dest ) ) {
            target->stumble();
            target->moves -= 250;
        }
    }
    if( rl_dist( z.pos(), g->u.pos() ) == 1 ) {
        g->u.add_env_effect( effect_boomered, bp_eyes, 2, 24_turns );
    }
    g->m.propagate_field( z.pos(), fd_bile, 15, 1 );
}
References _, bp_eyes, sounds::combat, effect_boomered, explode(), fd_bile, g, monster::name(), monster::pos(), rl_dist(), sounds::sound(), and string_format().
Referenced by MonsterGenerator::init_death().
boomer_glow()
void mdeath::boomer_glow (monster & z)
Definition at line 289 of file mondeath.cpp.
{
    std::string explode = string_format( _( "a %s explode!" ), z.name() );
    sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "small" );
    for( const tripoint &dest : g->m.points_in_radius( z.pos(), 1 ) ) { // *NOPAD*
        g->m.bash( dest, 10 );
        if( monster *const target = g->critter_at<monster>( dest ) ) {
            target->stumble();
            target->moves -= 250;
        }
        if( Creature *const critter = g->critter_at( dest ) ) {
            critter->add_env_effect( effect_boomered, bp_eyes, 5, 25_turns );
            for( int i = 0; i < rng( 2, 4 ); i++ ) {
                body_part bp = random_body_part();
                critter->add_env_effect( effect_glowing, bp, 4, 4_minutes );
                if( critter->has_effect( effect_glowing ) ) {
                    break;
                }
            }
        }
    }
    g->m.propagate_field( z.pos(), fd_bile, 30, 2 );
}
References _, bp_eyes, sounds::combat, effect_boomered, effect_glowing, explode(), fd_bile, g, monster::name(), monster::pos(), random_body_part(), rng(), sounds::sound(), and string_format().
Referenced by MonsterGenerator::init_death().
brainblob()
void mdeath::brainblob (monster & z)
Definition at line 523 of file mondeath.cpp.
{
    for( monster &critter : g->all_monsters() ) {
        if( critter.type->in_species( species_BLOB ) && critter.type->id != mon_blob_brain ) {
            critter.remove_effect( effect_ai_controlled );
        }
    }
    blobsplit( z );
}
References blobsplit(), effect_ai_controlled, g, mon_blob_brain, and species_BLOB.
Referenced by MonsterGenerator::init_death().
broken()
void mdeath::broken (monster & z)
Definition at line 644 of file mondeath.cpp.
{
    // Bail out if flagged (simulates eyebot flying away)
    if( z.no_corpse_quiet ) {
        return;
    }
    std::string item_id = z.type->id.str();
    if( item_id.compare( 0, 4, "mon_" ) == 0 ) {
        item_id.erase( 0, 4 );
    }
    // make "broken_manhack", or "broken_eyebot", ...
    item_id.insert( 0, "broken_" );
    item broken_mon( item_id, calendar::turn );
    const int max_hp = std::max( z.get_hp_max(), 1 );
    const float overflow_damage = std::max( -z.get_hp(), 0 );
    const float corpse_damage = 2.5 * overflow_damage / max_hp;
    broken_mon.set_damage( static_cast<int>( std::floor( corpse_damage * itype::damage_scale ) ) );
    g->m.add_item_or_charges( z.pos(), broken_mon );
    if( z.type->has_flag( MF_DROPS_AMMO ) ) {
        for( const std::pair<const itype_id, int> &ammo_entry : z.type->starting_ammo ) {
            if( z.ammo[ammo_entry.first] > 0 ) {
                bool spawned = false;
                for( const std::pair<const std::string, mtype_special_attack> &attack : z.type->special_attacks ) {
                    if( attack.second->id == "gun" ) {
                        item gun = item( dynamic_cast<const gun_actor *>( attack.second.get() )->gun_type );
                        bool same_ammo = false;
                        for( const ammotype &at : gun.ammo_types() ) {
                            if( at == item( ammo_entry.first ).ammo_type() ) {
                                same_ammo = true;
                                break;
                            }
                        }
                        const bool uses_mags = !gun.magazine_compatible().empty();
                        if( same_ammo && uses_mags ) {
                            std::vector<item> mags;
                            int ammo_count = z.ammo[ammo_entry.first];
                            while( ammo_count > 0 ) {
                                item mag = item( gun.type->magazine_default.find( item( ammo_entry.first ).ammo_type() )->second );
                                mag.ammo_set( ammo_entry.first,
                                              std::min( ammo_count, mag.type->magazine->capacity ) );
                                mags.insert( mags.end(), mag );
                                ammo_count -= mag.type->magazine->capacity;
                            }
                            g->m.spawn_items( z.pos(), mags );
                            spawned = true;
                            break;
                        }
                    }
                }
                if( !spawned ) {
                    g->m.spawn_item( z.pos(), ammo_entry.first, z.ammo[ammo_entry.first], 1,
                                     calendar::turn );
                }
            }
        }
    }
    // TODO: make mdeath::splatter work for robots
    if( ( broken_mon.damage() >= broken_mon.max_damage() ) && g->u.sees( z.pos() ) ) {
        add_msg( m_good, _( "The %s is destroyed!" ), z.name() );
    } else if( g->u.sees( z.pos() ) ) {
        add_msg( m_good, _( "The %s collapses!" ), z.name() );
    }
}
References _, add_msg(), monster::ammo, item::ammo_set(), item::ammo_type(), item::ammo_types(), item::damage(), itype::damage_scale, g, monster::get_hp(), monster::get_hp_max(), gun_actor::gun_type, mtype::has_flag(), mtype::id, m_good, itype::magazine, item::magazine_compatible(), itype::magazine_default, item::max_damage(), MF_DROPS_AMMO, monster::name(), monster::no_corpse_quiet, monster::pos(), item::set_damage(), mtype::special_attacks, mtype::starting_ammo, string_id< T >::str(), calendar::turn, item::type, and monster::type.
Referenced by broken_ammo(), and MonsterGenerator::init_death().
broken_ammo()
void mdeath::broken_ammo (monster & z)
Definition at line 869 of file mondeath.cpp.
{
    if( g->u.sees( z.pos() ) ) {
        //~ %s is the possessive form of the monster's name
        add_msg( m_info, _( "The %s's interior compartment sizzles with destructive energy." ),
                 z.name() );
    }
    mdeath::broken( z );
}
References _, add_msg(), broken(), g, m_info, monster::name(), and monster::pos().
Referenced by MonsterGenerator::init_death().
conflagration()
void mdeath::conflagration (monster & z)
Definition at line 966 of file mondeath.cpp.
{
    for( const auto &dest : g->m.points_in_radius( z.pos(), 1 ) ) {
        g->m.propagate_field( dest, fd_fire, 18, 3 );
    }
    const std::string explode = string_format( _( "a %s explode!" ), z.name() );
    sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "small" );
}
References _, sounds::combat, explode(), fd_fire, g, monster::name(), monster::pos(), sounds::sound(), and string_format().
Referenced by MonsterGenerator::init_death().
darkman()
void mdeath::darkman (monster & z)
Definition at line 723 of file mondeath.cpp.
{
    g->u.remove_effect( effect_darkness );
    if( g->u.sees( z ) ) {
        add_msg( m_good, _( "The %s melts away." ), z.name() );
    }
}
References _, add_msg(), effect_darkness, g, m_good, and monster::name().
Referenced by MonsterGenerator::init_death().
detonate()
void mdeath::detonate (monster & z)
Definition at line 797 of file mondeath.cpp.
{
    weighted_int_list<itype_id> amm_list;
    for( const auto &amm : z.ammo ) {
        amm_list.add( amm.first, amm.second );
    }
    std::vector<itype_id> pre_dets;
    for( int i = 0; i < 3; i++ ) {
        if( amm_list.get_weight() <= 0 ) {
            break;
        }
        // Grab one item
        itype_id tmp = *amm_list.pick();
        // and reduce its weight by 1
        amm_list.add_or_replace( tmp, amm_list.get_specific_weight( tmp ) - 1 );
        // and stash it for use
        pre_dets.push_back( tmp );
    }
    // Update any hardcoded explosion equivalencies
    std::vector<std::pair<std::string, long>> dets;
    for( const itype_id &bomb_id : pre_dets ) {
        if( bomb_id.str() == "bot_grenade_hack" ) {
            dets.push_back( std::make_pair( "grenade_act", 5 ) );
        } else if( bomb_id.str() == "bot_flashbang_hack" ) {
            dets.push_back( std::make_pair( "flashbang_act", 5 ) );
        } else if( bomb_id.str() == "bot_gasbomb_hack" ) {
            dets.push_back( std::make_pair( "gasbomb_act", 20 ) );
        } else if( bomb_id.str() == "bot_c4_hack" ) {
            dets.push_back( std::make_pair( "c4armed", 10 ) );
        } else if( bomb_id.str() == "bot_mininuke_hack" ) {
            dets.push_back( std::make_pair( "mininuke_act", 20 ) );
        } else {
            // Get the transformation item
            const iuse_transform *actor = dynamic_cast<const iuse_transform *>(
                                              bomb_id->get_use( "transform" )->get_actor_ptr() );
            if( actor == nullptr ) {
                // Invalid bomb item, move to the next ammo item
                add_msg( m_debug, "Invalid bomb type in detonate mondeath for %s.", z.name() );
                continue;
            }
            dets.emplace_back( actor->target.str(), actor->ammo_qty );
        }
    }
    if( g->u.sees( z ) ) {
        if( dets.empty() ) {
            add_msg( m_info,
                     //~ %s is the possessive form of the monster's name
                     _( "The %s's hands fly to its pockets, but there's nothing left in them." ),
                     z.name() );
        } else {
            //~ %s is the possessive form of the monster's name
            add_msg( m_bad, _( "The %s's hands fly to its remaining pockets, opening them!" ),
                     z.name() );
        }
    }
    // HACK, used to stop them from having ammo on respawn
    z.add_effect( effect_no_ammo, 1_turns, num_bp );
    // First die normally
    mdeath::normal( z );
    // Then detonate our suicide bombs
    for( const auto &bombs : dets ) {
        item bomb_item( bombs.first, calendar::start_of_cataclysm );
        bomb_item.charges = bombs.second;
        bomb_item.active = true;
        g->m.add_item_or_charges( z.pos(), bomb_item );
    }
}
References _, item::active, weighted_list< W, T >::add(), monster::add_effect(), add_msg(), weighted_list< W, T >::add_or_replace(), monster::ammo, iuse_transform::ammo_qty, item::charges, effect_no_ammo, g, weighted_list< W, T >::get_specific_weight(), weighted_list< W, T >::get_weight(), m_bad, m_debug, m_info, monster::name(), normal(), num_bp, weighted_list< W, T >::pick(), monster::pos(), calendar::start_of_cataclysm, string_id< T >::str(), and iuse_transform::target.
Referenced by MonsterGenerator::init_death().
disappear()
void mdeath::disappear (monster & z)
Definition at line 420 of file mondeath.cpp.
{
    if( g->u.sees( z ) ) {
        add_msg( m_good, _( "The %s disappears." ), z.name() );
    }
}
References _, add_msg(), g, m_good, and monster::name().
Referenced by monster::die(), and MonsterGenerator::init_death().
disintegrate()
void mdeath::disintegrate (monster & z)
Definition at line 397 of file mondeath.cpp.
{
    if( g->u.sees( z ) ) {
        add_msg( m_good, _( "The %s disintegrates!" ), z.name() );
    }
}
References _, add_msg(), g, m_good, and monster::name().
Referenced by MonsterGenerator::init_death().
explode()
void mdeath::explode (monster & z)
Definition at line 579 of file mondeath.cpp.
{
    int size = 0;
    switch( z.type->size ) {
        case MS_TINY:
            size = 4;
            break;
        case MS_SMALL:
            size = 8;
            break;
        case MS_MEDIUM:
            size = 14;
            break;
        case MS_LARGE:
            size = 20;
            break;
        case MS_HUGE:
            size = 26;
            break;
        default:
            size = 15;
            break;
    }
    explosion_handler::explosion( z.pos(), size );
}
References explosion_handler::explosion(), MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, monster::pos(), mtype::size, om_direction::size, and monster::type.
Referenced by boomer(), boomer_glow(), conflagration(), fireball(), fungalburst(), gas(), MonsterGenerator::init_death(), and smokeburst().
fireball()
void mdeath::fireball (monster & z)
Definition at line 953 of file mondeath.cpp.
{
    if( one_in( 10 ) ) {
        g->m.propagate_field( z.pos(), fd_fire, 15, 3 );
        std::string explode = string_format( _( "an explosion of tank of the %s's flamethrower!" ),
                                             z.name() );
        sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "default" );
        add_msg( m_good, _( "I love the smell of burning zed in the morning." ) );
    } else {
        normal( z );
    }
}
References _, add_msg(), sounds::combat, explode(), fd_fire, g, m_good, monster::name(), one_in(), monster::pos(), sounds::sound(), and string_format().
Referenced by iuse::artifact(), and MonsterGenerator::init_death().
focused_beam()
void mdeath::focused_beam (monster & z)
Definition at line 605 of file mondeath.cpp.
{
    map_stack items = g->m.i_at( z.pos() );
    for( map_stack::iterator it = items.begin(); it != items.end(); ) {
        if( it->typeId() == itype_processor ) {
            it = items.erase( it );
        } else {
            ++it;
        }
    }
    if( !z.inv.empty() ) {
        if( g->u.sees( z ) ) {
            add_msg( m_warning, _( "As the final light is destroyed, it erupts in a blinding flare!" ) );
        }
        item &settings = z.inv[0];
        point p2( z.posx() + settings.get_var( "SL_SPOT_X", 0 ), z.posy() + settings.get_var( "SL_SPOT_Y",
                  0 ) );
        tripoint p( p2, z.posz() );
        std::vector <tripoint> traj = line_to( z.pos(), p, 0, 0 );
        tripoint last_point = z.pos();
        for( auto &elem : traj ) {
            if( !g->m.is_transparent( elem ) || get_map().obscured_by_vehicle_rotation( last_point, elem ) ) {
                break;
            }
            g->m.add_field( elem, fd_dazzling, 2 );
            last_point = elem;
        }
    }
    z.inv.clear();
    explosion_handler::explosion( z.pos(), 8 );
}
References _, add_msg(), item_stack::begin(), item_stack::end(), map_stack::erase(), explosion_handler::explosion(), fd_dazzling, g, get_map(), item::get_var(), monster::inv, itype_processor, line_to(), m_warning, monster::pos(), monster::posx(), monster::posy(), and monster::posz().
Referenced by MonsterGenerator::init_death().
fungalburst()
void mdeath::fungalburst (monster & z)
Definition at line 745 of file mondeath.cpp.
{
    // If the fungus died from anti-fungal poison, don't pouf
    if( g->m.get_field_intensity( z.pos(), fd_fungicidal_gas ) ) {
        if( g->u.sees( z ) ) {
            add_msg( m_good, _( "The %s inflates and melts away." ), z.name() );
        }
        return;
    }
    std::string explode = string_format( _( "a %s explodes!" ), z.name() );
    sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "small" );
    g->m.emit_field( z.pos(), emit_id( "emit_fungal_blast" ) );
}
References _, add_msg(), sounds::combat, explode(), fd_fungicidal_gas, g, m_good, monster::name(), monster::pos(), sounds::sound(), and string_format().
Referenced by MonsterGenerator::init_death().
fungus()
void mdeath::fungus (monster & z)
Definition at line 381 of file mondeath.cpp.
{
    //~ the sound of a fungus dying
    sounds::sound( z.pos(), 10, sounds::sound_t::combat, _( "Pouf!" ), false, "misc", "puff" );
    fungal_effects fe( *g, g->m );
    for( const tripoint &sporep : g->m.points_in_radius( z.pos(), 1 ) ) { // *NOPAD*
        if( g->m.impassable( sporep ) && !get_map().obstructed_by_vehicle_rotation( z.pos(), sporep ) ) {
            continue;
        }
        // z is dead, don't credit it with the kill
        // Maybe credit z's killer?
        fe.fungalize( sporep, nullptr, 0.25 );
    }
}
References _, sounds::combat, fungal_effects::fungalize(), g, get_map(), monster::pos(), and sounds::sound().
Referenced by MonsterGenerator::init_death().
gameover()
void mdeath::gameover (monster & z)
Definition at line 781 of file mondeath.cpp.
{
    add_msg( m_bad, _( "The %s was destroyed!  GAME OVER!" ), z.name() );
    g->u.set_part_hp_cur( bodypart_id( "torso" ), 0 );
}
References _, add_msg(), g, m_bad, and monster::name().
Referenced by MonsterGenerator::init_death().
gas()
void mdeath::gas (monster & z)
Definition at line 731 of file mondeath.cpp.
{
    std::string explode = string_format( _( "a %s explode!" ), z.name() );
    sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "small" );
    g->m.emit_field( z.pos(), emit_id( "emit_toxic_blast" ) );
}
References _, sounds::combat, explode(), g, monster::name(), monster::pos(), sounds::sound(), and string_format().
Referenced by MonsterGenerator::init_death().
guilt()
void mdeath::guilt (monster & z)
Definition at line 427 of file mondeath.cpp.
{
    const int MAX_GUILT_DISTANCE = 5;
    int kill_count = g->get_kill_tracker().kill_count( z.type->id );
    int maxKills = 100; // this is when the player stop caring altogether.
    // different message as we kill more of the same monster
    std::string msg = _( "You feel guilty for killing %s." ); // default guilt message
    game_message_type msgtype = m_bad; // default guilt message type
    std::map<int, std::string> guilt_tresholds;
    guilt_tresholds[75] = _( "You feel ashamed for killing %s." );
    guilt_tresholds[50] = _( "You regret killing %s." );
    guilt_tresholds[25] = _( "You feel remorse for killing %s." );
    if( g->u.has_trait( trait_PSYCHOPATH ) || g->u.has_trait_flag( "PRED3" ) ||
        g->u.has_trait_flag( "PRED4" ) || g->u.has_trait( trait_KILLER ) ) {
        return;
    }
    if( rl_dist( z.pos(), g->u.pos() ) > MAX_GUILT_DISTANCE ) {
        // Too far away, we can deal with it.
        return;
    }
    if( z.get_hp() >= 0 ) {
        // We probably didn't kill it
        return;
    }
    if( kill_count >= maxKills ) {
        // player no longer cares
        if( kill_count == maxKills ) {
            //~ Message after killing a lot of monsters which would normally affect the morale negatively. %s is the monster name, it will be pluralized with a number of 100.
            add_msg( m_good, _( "After killing so many bloody %s you no longer care "
                                "about their deaths anymore." ), z.name( maxKills ) );
        }
        return;
    } else if( ( g->u.has_trait_flag( "PRED1" ) ) || ( g->u.has_trait_flag( "PRED2" ) ) ) {
        msg = ( _( "Culling the weak is distasteful, but necessary." ) );
        msgtype = m_neutral;
    } else {
        msgtype = m_bad;
        for( auto &guilt_treshold : guilt_tresholds ) {
            if( kill_count >= guilt_treshold.first ) {
                msg = guilt_treshold.second;
                break;
            }
        }
    }
    add_msg( msgtype, msg, z.name() );
    int moraleMalus = -50 * ( 1.0 - ( static_cast<float>( kill_count ) / maxKills ) );
    int maxMalus = -250 * ( 1.0 - ( static_cast<float>( kill_count ) / maxKills ) );
    time_duration duration = 30_minutes * ( 1.0 - ( static_cast<float>( kill_count ) / maxKills ) );
    time_duration decayDelay = 3_minutes * ( 1.0 - ( static_cast<float>( kill_count ) / maxKills ) );
    if( z.type->in_species( ZOMBIE ) ) {
        moraleMalus /= 10;
        if( g->u.has_trait( trait_PACIFIST ) ) {
            moraleMalus *= 5;
        } else if( g->u.has_trait_flag( "PRED1" ) ) {
            moraleMalus /= 4;
        } else if( g->u.has_trait_flag( "PRED2" ) ) {
            moraleMalus /= 5;
        }
    }
    g->u.add_morale( MORALE_KILLED_MONSTER, moraleMalus, maxMalus, duration, decayDelay );
}
References _, add_msg(), g, monster::get_hp(), mtype::id, mtype::in_species(), m_bad, m_good, m_neutral, MORALE_KILLED_MONSTER, monster::name(), monster::pos(), rl_dist(), trait_KILLER, trait_PACIFIST, trait_PSYCHOPATH, monster::type, and ZOMBIE.
Referenced by monster::die(), and MonsterGenerator::init_death().
howl()
void mdeath::howl (monster & z)
jabberwock()
void mdeath::jabberwock (monster & z)
Definition at line 760 of file mondeath.cpp.
{
    player *ch = dynamic_cast<player *>( z.get_killer() );
    bool vorpal = ch && ch->is_player() &&
                  ch->weapon.has_flag( "DIAMOND" ) &&
                  ch->weapon.volume() > 750_ml;
    if( vorpal && !ch->weapon.has_technique( matec_id( "VORPAL" ) ) ) {
        if( ch->sees( z ) ) {
            ch->add_msg_if_player( m_info,
                                   //~ %s is the possessive form of the monster's name
                                   _( "As the flames in %s eyes die out, your weapon seems to shine slightly brighter." ),
                                   z.disp_name( true ) );
        }
        ch->weapon.add_technique( matec_id( "VORPAL" ) );
    }
    mdeath::normal( z );
}
References _, player::add_msg_if_player(), item::add_technique(), monster::disp_name(), Creature::get_killer(), item::has_flag(), item::has_technique(), player::is_player(), m_info, normal(), Character::sees(), item::volume(), and Character::weapon.
Referenced by MonsterGenerator::init_death().
jackson()
void mdeath::jackson (monster & z)
Definition at line 533 of file mondeath.cpp.
{
    for( monster &critter : g->all_monsters() ) {
        if( critter.type->id == mon_zombie_dancer ) {
            critter.poly( mon_zombie_hulk );
            critter.remove_effect( effect_ai_controlled );
        }
        if( g->u.sees( z ) ) {
            add_msg( m_warning, _( "The music stops!" ) );
        }
    }
}
References _, add_msg(), effect_ai_controlled, g, m_warning, mon_zombie_dancer, and mon_zombie_hulk.
Referenced by MonsterGenerator::init_death().
kill_breathers()
void mdeath::kill_breathers (monster & z)
Definition at line 787 of file mondeath.cpp.
{
    for( monster &critter : g->all_monsters() ) {
        const mtype_id &monID = critter.type->id;
        if( monID == mon_breather_hub || monID == mon_breather ) {
            critter.die( nullptr );
        }
    }
}
References g, mtype::id, mon_breather, and mon_breather_hub.
Referenced by MonsterGenerator::init_death().
kill_vines()
void mdeath::kill_vines (monster & z)
Definition at line 315 of file mondeath.cpp.
{
    const std::vector<Creature *> vines = g->get_creatures_if( [&]( const Creature & critter ) {
        const monster *const mon = dynamic_cast<const monster *>( &critter );
        return mon && mon->type->id == mon_creeper_vine;
    } );
    const std::vector<Creature *> hubs = g->get_creatures_if( [&]( const Creature & critter ) {
        const monster *const mon = dynamic_cast<const monster *>( &critter );
        return mon && mon != &z && mon->type->id == mon_creeper_hub;
    } );
    for( Creature *const vine : vines ) {
        int dist = rl_dist( vine->pos(), z.pos() );
        bool closer = false;
        for( auto &j : hubs ) {
            if( rl_dist( vine->pos(), j->pos() ) < dist ) {
                break;
            }
        }
        if( !closer ) { // TODO: closer variable is not being updated and is always false!
            vine->die( &z );
        }
    }
}
References g, mtype::id, mon_creeper_hub, mon_creeper_vine, monster::pos(), rl_dist(), monster::type, and mattack::vine().
Referenced by MonsterGenerator::init_death().
melt()
void mdeath::melt (monster & z)
Definition at line 546 of file mondeath.cpp.
{
    if( g->u.sees( z ) ) {
        add_msg( m_good, _( "The %s melts away." ), z.name() );
    }
}
References _, add_msg(), g, m_good, and monster::name().
Referenced by MonsterGenerator::init_death().
normal()
void mdeath::normal (monster & z)
Definition at line 88 of file mondeath.cpp.
{
    if( z.no_corpse_quiet ) {
        return;
    }
    if( z.type->in_species( ZOMBIE ) ) {
        sfx::play_variant_sound( "mon_death", "zombie_death", sfx::get_heard_volume( z.pos() ) );
    }
    if( g->u.sees( z ) ) {
        //Currently it is possible to get multiple messages that a monster died.
        add_msg( m_good, _( "The %s dies!" ), z.name() );
    }
    const int max_hp = std::max( z.get_hp_max(), 1 );
    const float overflow_damage = std::max( -z.get_hp(), 0 );
    const float corpse_damage = 2.5 * overflow_damage / max_hp;
    const bool pulverized = corpse_damage > 5 && overflow_damage > z.get_hp_max();
    z.bleed(); // leave some blood if we have to
    if( !pulverized ) {
        make_mon_corpse( z, static_cast<int>( std::floor( corpse_damage * itype::damage_scale ) ) );
    }
    // if mdeath::splatter was set along normal makes sure it is not called twice
    bool splatt = false;
    for( const auto &deathfunction : z.type->dies ) {
        if( deathfunction == mdeath::splatter ) {
            splatt = true;
        }
    }
    if( !splatt ) {
        splatter( z );
    }
}
References _, add_msg(), Creature::bleed(), itype::damage_scale, mtype::dies, g, sfx::get_heard_volume(), monster::get_hp(), monster::get_hp_max(), mtype::in_species(), m_good, make_mon_corpse(), monster::name(), monster::no_corpse_quiet, sfx::play_variant_sound(), monster::pos(), splatter(), monster::type, and ZOMBIE.
Referenced by detonate(), MonsterGenerator::init_death(), jabberwock(), mtype::load(), and mtype::mtype().
preg_roach()
void mdeath::preg_roach (monster & z)
Definition at line 942 of file mondeath.cpp.
{
    int num_roach = rng( 1, 3 );
    while( num_roach > 0 && g->place_critter_around( mon_giant_cockroach_nymph, z.pos(), 1 ) ) {
        num_roach--;
        if( g->u.sees( z ) ) {
            add_msg( m_warning, _( "A cockroach nymph crawls out of the pregnant giant cockroach corpse." ) );
        }
    }
}
References _, add_msg(), g, m_warning, mon_giant_cockroach_nymph, monster::pos(), and rng().
Referenced by MonsterGenerator::init_death().
ratking()
void mdeath::ratking (monster & z)
Definition at line 711 of file mondeath.cpp.
{
    g->u.remove_effect( effect_rat );
    if( g->u.sees( z ) ) {
        add_msg( m_warning, _( "Rats suddenly swarm into view." ) );
    }
    for( int rats = 0; rats < 7; rats++ ) {
        g->place_critter_around( mon_sewer_rat, z.pos(), 1 );
    }
}
References _, add_msg(), effect_rat, g, m_warning, mon_sewer_rat, and monster::pos().
Referenced by MonsterGenerator::init_death().
rattle()
void mdeath::rattle (monster & z)
shriek()
void mdeath::shriek (monster & z)
smokeburst()
void mdeath::smokeburst (monster & z)
Definition at line 738 of file mondeath.cpp.
{
    std::string explode = string_format( _( "a %s explode!" ), z.name() );
    sounds::sound( z.pos(), 24, sounds::sound_t::combat, explode, false, "explosion", "small" );
    g->m.emit_field( z.pos(), emit_id( "emit_smoke_blast" ) );
}
References _, sounds::combat, explode(), g, monster::name(), monster::pos(), sounds::sound(), and string_format().
Referenced by MonsterGenerator::init_death().
splatter()
void mdeath::splatter (monster & z)
Definition at line 186 of file mondeath.cpp.
{
    map &here = get_map();
    const bool gibbable = !z.type->has_flag( MF_NOGIB );
    const int max_hp = std::max( z.get_hp_max(), 1 );
    const float overflow_damage = std::max( -z.get_hp(), 0 );
    const float corpse_damage = 2.5 * overflow_damage / max_hp;
    bool pulverized = corpse_damage > 5 && overflow_damage > z.get_hp_max();
    // make sure that full splatter happens when this is a set death function, not part of normal
    for( const auto &deathfunction : z.type->dies ) {
        if( deathfunction == mdeath::splatter ) {
            pulverized = true;
        }
    }
    const field_type_id type_blood = z.bloodType();
    const field_type_id type_gib = z.gibType();
    if( gibbable ) {
        const auto area = here.points_in_radius( z.pos(), 1 );
        int number_of_gibs = std::min( std::floor( corpse_damage ) - 1, 1 + max_hp / 5.0f );
        if( pulverized && z.type->size >= MS_MEDIUM ) {
            number_of_gibs += rng( 1, 6 );
            sfx::play_variant_sound( "mon_death", "zombie_gibbed", sfx::get_heard_volume( z.pos() ) );
        }
        for( int i = 0; i < number_of_gibs; ++i ) {
            if( type_blood ) {
                here.add_splatter( type_gib, random_entry( area ), rng( 1, i + 1 ) );
            }
            if( type_gib ) {
                here.add_splatter( type_gib, random_entry( area ) );
            }
        }
    }
    // 1% of the weight of the monster is the base, with overflow damage as a multiplier
    int gibbed_weight = rng( 0, std::round( to_gram( z.get_weight() ) / 100.0 *
                                            ( overflow_damage / max_hp + 1 ) ) );
    const int z_weight = to_gram( z.get_weight() );
    // limit gibbing to 15%
    gibbed_weight = std::min( gibbed_weight, z_weight * 15 / 100 );
    if( pulverized && gibbable ) {
        float overflow_ratio = overflow_damage / max_hp + 1;
        int gib_distance = std::round( rng( 2, 4 ) );
        for( const auto &entry : *z.type->harvest ) {
            // only flesh and bones survive.
            if( entry.type == "flesh" || entry.type == "bone" ) {
                // the larger the overflow damage, the less you get
                itype_id item_id( entry.drop );
                const int chunk_amt = entry.mass_ratio / overflow_ratio / 10 * z_weight /
                                      to_gram( item_id->weight );
                scatter_chunks( item_id, chunk_amt, z, gib_distance,
                                chunk_amt / ( gib_distance - 1 ) );
                gibbed_weight -= entry.mass_ratio / overflow_ratio / 20 * z_weight;
            }
        }
        // add corpse with gib flag
        item corpse = item::make_corpse( z.type->id, calendar::turn, z.unique_name, z.get_upgrade_time() );
        // Set corpse to damage that aligns with being pulped
        corpse.set_damage( 4000 );
        corpse.set_flag( "GIBBED" );
        if( z.has_effect( effect_no_ammo ) ) {
            corpse.set_var( "no_ammo", "no_ammo" );
        }
        here.add_item_or_charges( z.pos(), corpse );
    }
}
References map::add_item_or_charges(), map::add_splatter(), monster::bloodType(), corpse, mtype::dies, effect_no_ammo, sfx::get_heard_volume(), monster::get_hp(), monster::get_hp_max(), get_map(), monster::get_upgrade_time(), monster::get_weight(), monster::gibType(), mtype::harvest, Creature::has_effect(), mtype::has_flag(), mtype::id, item::make_corpse(), MF_NOGIB, MS_MEDIUM, sfx::play_variant_sound(), map::points_in_radius(), monster::pos(), random_entry(), rng(), scatter_chunks(), mtype::size, splatter(), units::to_gram(), calendar::turn, monster::type, monster::unique_name, and itype::weight.
Referenced by MonsterGenerator::init_death(), normal(), and splatter().
thing()
void mdeath::thing (monster & z)
Definition at line 574 of file mondeath.cpp.
{
    g->place_critter_at( mon_thing, z.pos() );
}
References g, mon_thing, and monster::pos().
Referenced by MonsterGenerator::init_death(), Character::is_worn(), JsonIn::read(), and JsonOut::write().
triffid_heart()
void mdeath::triffid_heart (monster & z)
Definition at line 373 of file mondeath.cpp.
{
    if( g->u.sees( z ) ) {
        add_msg( m_warning, _( "The surrounding roots begin to crack and crumble." ) );
    }
    g->timed_events.add( TIMED_EVENT_ROOTS_DIE, calendar::turn + 10_minutes );
}
References _, add_msg(), g, m_warning, TIMED_EVENT_ROOTS_DIE, and calendar::turn.
Referenced by MonsterGenerator::init_death().
vine_cut()
void mdeath::vine_cut (monster & z)
Definition at line 340 of file mondeath.cpp.
{
    std::vector<monster *> vines;
    for( const tripoint &tmp : g->m.points_in_radius( z.pos(), 1 ) ) {
        if( tmp == z.pos() ) {
            continue; // Skip ourselves
        }
        if( monster *const neighbor = g->critter_at<monster>( tmp ) ) {
            if( neighbor->type->id == mon_creeper_vine ) {
                vines.push_back( neighbor );
            }
        }
    }
    for( auto &vine : vines ) {
        bool found_neighbor = false;
        for( const tripoint &dest : g->m.points_in_radius( vine->pos(), 1 ) ) {
            if( dest != z.pos() ) {
                // Not the dying vine
                if( monster *const v = g->critter_at<monster>( dest ) ) {
                    if( v->type->id == mon_creeper_hub || v->type->id == mon_creeper_vine ) {
                        found_neighbor = true;
                        break;
                    }
                }
            }
        }
        if( !found_neighbor ) {
            vine->die( &z );
        }
    }
}
References g, mtype::id, mon_creeper_hub, mon_creeper_vine, monster::pos(), and mattack::vine().
Referenced by MonsterGenerator::init_death().
worm()
void mdeath::worm (monster & z)
Definition at line 404 of file mondeath.cpp.
{
    if( g->u.sees( z ) ) {
        if( z.type->dies.size() == 1 ) {
            add_msg( m_good, _( "The %s splits in two!" ), z.name() );
        } else {
            add_msg( m_warning, _( "Two worms crawl out of the %s's corpse." ), z.name() );
        }
    }
    int worms = 2;
    while( worms > 0 && g->place_critter_around( mon_halfworm, z.pos(), 1 ) ) {
        worms--;
    }
}
References _, add_msg(), mtype::dies, g, m_good, m_warning, mon_halfworm, monster::name(), monster::pos(), and monster::type.
Referenced by MonsterGenerator::init_death().