Cataclysm BN: character_effects Namespace Reference
character_effects Namespace Reference
Functions
stat_mod get_pain_penalty (const Character &ch)
Returns the effect of pain on stats.
int get_kcal_speed_penalty (float kcal_percent)
Returns the penalty to speed from starvation.
int get_thirst_speed_penalty (int thirst)
Returns the penalty to speed from thirst.
int calc_morale_fatigue_cap (int fatigue)
Calculates character's morale cap due to fatigue.
double vomit_mod (const Character &ch)
Returns the modifier value used for vomiting effects.
int talk_skill (const Character &ch)
Returns a value used when attempting to convince NPC's of something.
int intimidation (const Character &ch)
Returns a value used when attempting to intimidate NPC's.
int calc_focus_equilibrium (const Character &who)
Uses morale, pain and fatigue to return the player's focus target goto value.
int calc_focus_change (const Character &who)
Calculates actual focus gain/loss value from focus equilibrium.
Function Documentation
calc_focus_change()
int character_effects::calc_focus_change (const Character & who)
Calculates actual focus gain/loss value from focus equilibrium.
Definition at line 248 of file character_effects.cpp.
{
    int focus_gap = calc_focus_equilibrium( who ) - who.focus_pool;
    // handle negative gain rates in a symmetric manner
    int base_change = 1;
    if( focus_gap < 0 ) {
        base_change = -1;
        focus_gap = -focus_gap;
    }
    // for every 100 points, we have a flat gain of 1 focus.
    // for every n points left over, we have an n% chance of 1 focus
    int gain = focus_gap / 100;
    if( rng( 1, 100 ) <= focus_gap % 100 ) {
        gain++;
    }
    gain *= base_change;
    return gain;
}
References calc_focus_equilibrium(), Character::focus_pool, and rng().
Referenced by character_funcs::update_mental_focus().
calc_focus_equilibrium()
int character_effects::calc_focus_equilibrium (const Character & who)
Uses morale, pain and fatigue to return the player's focus target goto value.
Definition at line 177 of file character_effects.cpp.
{
    int focus_equilibrium = 100;
    if( who.activity.id() == ACT_READ ) {
        item_location loc = who.activity.targets[0];
        if( loc && loc->is_book() ) {
            auto &bt = *loc->type->book;
            // apply a penalty when we're actually learning something
            const SkillLevel &skill_level = who.get_skill_level_object( bt.skill );
            if( skill_level.can_train() && skill_level < bt.level ) {
                focus_equilibrium -= 50;
            }
        }
    }
    int eff_morale = who.get_morale_level();
    // Factor in perceived pain, since it's harder to rest your mind while your body hurts.
    // Cenobites don't mind, though
    if( !who.has_trait( trait_CENOBITE ) ) {
        eff_morale = eff_morale - who.get_perceived_pain();
    }
    // as baseline morale is 100, calc_fatigue_cap() has to -100 to apply accurate penalties.
    if( calc_morale_fatigue_cap( who.get_fatigue() ) != 0 &&
        eff_morale > calc_morale_fatigue_cap( who.get_fatigue() ) - 100 ) {
        eff_morale = calc_morale_fatigue_cap( who.get_fatigue() ) - 100;
    }
    if( eff_morale < -99 ) {
        // At very low morale, focus is at it's minimum
        focus_equilibrium = 1;
    } else if( eff_morale <= 50 ) {
        // At -99 to +50 morale, each point of morale gives or takes 1 point of focus
        focus_equilibrium += eff_morale;
    } else {
        /* Above 50 morale, we apply strong diminishing returns.
        * Each block of 50 takes twice as many morale points as the previous one:
        * 150 focus at 50 morale (as before)
        * 200 focus at 150 morale (100 more morale)
        * 250 focus at 350 morale (200 more morale)
        * ...
        * Cap out at 400% focus gain with 3,150+ morale, mostly as a sanity check.
        */
        int block_multiplier = 1;
        int morale_left = eff_morale;
        while( focus_equilibrium < 400 ) {
            if( morale_left > 50 * block_multiplier ) {
                // We can afford the entire block.  Get it and continue.
                morale_left -= 50 * block_multiplier;
                focus_equilibrium += 50;
                block_multiplier *= 2;
            } else {
                // We can't afford the entire block.  Each block_multiplier morale
                // points give 1 focus, and then we're done.
                focus_equilibrium += morale_left / block_multiplier;
                break;
            }
        }
    }
    // This should be redundant, but just in case...
    if( focus_equilibrium < 1 ) {
        focus_equilibrium = 1;
    } else if( focus_equilibrium > 400 ) {
        focus_equilibrium = 400;
    }
    return focus_equilibrium;
}
References ACT_READ, Character::activity, itype::book, calc_morale_fatigue_cap(), SkillLevel::can_train(), Character::get_fatigue(), Character::get_morale_level(), Character::get_perceived_pain(), Character::get_skill_level_object(), Character::has_trait(), player_activity::id(), item::is_book(), SkillLevel::level(), player_activity::targets, trait_CENOBITE, and item::type.
Referenced by calc_focus_change(), avatar::disp_morale(), and draw_char_narrow().
calc_morale_fatigue_cap()
int character_effects::calc_morale_fatigue_cap (int fatigue)
Calculates character's morale cap due to fatigue.
Definition at line 103 of file character_effects.cpp.
{
    if( fatigue >= fatigue_levels::massive ) {
        return 20;
    } else if( fatigue >= fatigue_levels::exhausted ) {
        return 40;
    } else if( fatigue >= fatigue_levels::dead_tired ) {
        return 60;
    } else if( fatigue >= fatigue_levels::tired ) {
        return 80;
    }
    return 0;
}
References dead_tired, exhausted, fatigue, massive, and tired.
Referenced by calc_focus_equilibrium(), and avatar::disp_morale().
get_kcal_speed_penalty()
int character_effects::get_kcal_speed_penalty (float kcal_percent)
Returns the penalty to speed from starvation.
Definition at line 73 of file character_effects.cpp.
{
    static const std::vector<std::pair<float, float>> starv_thresholds = { {
            std::make_pair( 0.0f, -90.0f ),
            std::make_pair( 0.1f, -50.f ),
            std::make_pair( 0.3f, -25.0f ),
            std::make_pair( 0.5f, 0.0f )
        }
    };
    if( kcal_percent > 0.95f ) {
        return 0;
    } else {
        return std::round( multi_lerp( starv_thresholds, kcal_percent ) );
    }
}
References multi_lerp().
Referenced by draw_speed_tab(), and Character::recalc_speed_bonus().
get_pain_penalty()
stat_mod character_effects::get_pain_penalty (const Character & ch)
Returns the effect of pain on stats.
Definition at line 40 of file character_effects.cpp.
{
    stat_mod ret;
    int pain = ch.get_perceived_pain();
    if( pain <= 0 ) {
        return ret;
    }
    int stat_penalty = std::floor( std::pow( pain, 0.8f ) / 10.0f );
    bool ceno = ch.has_trait( trait_CENOBITE );
    if( !ceno ) {
        ret.strength = stat_penalty;
        ret.dexterity = stat_penalty;
    }
    if( !ch.has_trait( trait_INT_SLIME ) ) {
        ret.intelligence = stat_penalty;
    } else {
        ret.intelligence = pain / 5;
    }
    ret.perception = stat_penalty * 2 / 3;
    ret.speed = std::pow( pain, 0.7f );
    if( ceno ) {
        ret.speed /= 2;
    }
    ret.speed = std::min( ret.speed, 30 );
    return ret;
}
References Character::get_perceived_pain(), Character::has_trait(), pain, cata::hash64_detail::ret, trait_CENOBITE, and trait_INT_SLIME.
Referenced by character_display::disp_info(), draw_speed_tab(), Character::recalc_speed_bonus(), and Character::reset_stats().
get_thirst_speed_penalty()
int character_effects::get_thirst_speed_penalty (int thirst)
Returns the penalty to speed from thirst.
Definition at line 89 of file character_effects.cpp.
{
    // We die at 1200 thirst
    // Start by dropping speed really fast, but then level it off a bit
    static const std::vector<std::pair<float, float>> thirst_thresholds = {{
            std::make_pair( static_cast<float>( thirst_levels::very_thirsty ), 0.0f ),
            std::make_pair( static_cast<float>( thirst_levels::dehydrated ), -25.0f ),
            std::make_pair( static_cast<float>( thirst_levels::parched ), -50.0f ),
            std::make_pair( static_cast<float>( thirst_levels::dead ), -75.0f )
        }
    };
    return static_cast<int>( multi_lerp( thirst_thresholds, thirst ) );
}
References dead, dehydrated, multi_lerp(), parched, and very_thirsty.
Referenced by draw_speed_tab(), and Character::recalc_speed_bonus().
intimidation()
int character_effects::intimidation (const Character & ch)
Returns a value used when attempting to intimidate NPC's.
Strength increases intimidation factor
Definition at line 154 of file character_effects.cpp.
{
    /** @EFFECT_STR increases intimidation factor */
    int ret = ch.get_str() * 2;
    if( ch.weapon.is_gun() ) {
        ret += 10;
    }
    if( ch.weapon.damage_melee( DT_BASH ) >= 12 ||
        ch.weapon.damage_melee( DT_CUT ) >= 12 ||
        ch.weapon.damage_melee( DT_STAB ) >= 12 ) {
        ret += 5;
    }
    if( ch.get_stim() > 20 ) {
        ret += 2;
    }
    if( ch.has_effect( effect_drunk ) ) {
        ret -= 4;
    }
    return ret;
}
References item::damage_melee(), DT_BASH, DT_CUT, DT_STAB, effect_drunk, Character::get_stim(), Character::get_str(), Creature::has_effect(), item::is_gun(), cata::hash64_detail::ret, and Character::weapon.
Referenced by talk_trial::calc_chance(), and parse_mod().
talk_skill()
int character_effects::talk_skill (const Character & ch)
Returns a value used when attempting to convince NPC's of something.
Intelligence slightly increases talking skill Perception slightly increases talking skill Speech increases talking skill
Definition at line 143 of file character_effects.cpp.
{
    /** @EFFECT_INT slightly increases talking skill */
    /** @EFFECT_PER slightly increases talking skill */
    /** @EFFECT_SPEECH increases talking skill */
    int ret = ch.get_int() + ch.get_per() + ch.get_skill_level( skill_id( "speech" ) ) * 3;
    return ret;
}
References Character::get_int(), Character::get_per(), Character::get_skill_level(), and cata::hash64_detail::ret.
Referenced by talk_trial::calc_chance().
vomit_mod()
double character_effects::vomit_mod (const Character & ch)
Returns the modifier value used for vomiting effects.
Definition at line 117 of file character_effects.cpp.
{
    double mod = 1;
    if( ch.has_effect( effect_weed_high ) ) {
        mod *= .1;
    }
    if( ch.has_trait( trait_STRONGSTOMACH ) ) {
        mod *= .5;
    }
    if( ch.has_trait( trait_WEAKSTOMACH ) ) {
        mod *= 2;
    }
    if( ch.has_trait( trait_NAUSEA ) ) {
        mod *= 3;
    }
    if( ch.has_trait( trait_VOMITOUS ) ) {
        mod *= 3;
    }
    // If you're already nauseous, any food in your stomach greatly
    // increases chance of vomiting. Water doesn't provoke vomiting, though.
    if( ch.stomach.get_calories() > 0 && ch.has_effect( effect_nausea ) ) {
        mod *= 5 * ch.get_effect_int( effect_nausea );
    }
    return mod;
}
References effect_nausea, effect_weed_high, stomach_contents::get_calories(), Creature::get_effect_int(), Creature::has_effect(), Character::has_trait(), Character::stomach, trait_NAUSEA, trait_STRONGSTOMACH, trait_VOMITOUS, and trait_WEAKSTOMACH.
Referenced by eff_fun_fungus(), eff_fun_hallu(), Character::hardcoded_effects(), and Character::process_one_effect().