Cataclysm BN: l10n_data Namespace Reference
l10n_data Namespace Reference
Functions
const trans_library & get_library ()
static void set_library (trans_library lib)
static void add_cat_if_exists (std::vector< trans_catalogue > &list, const std::string &lang_id, const std::string &path_start, const std::string &path_end)
static void add_mod_catalogue_if_exists (std::vector< trans_catalogue > &list, const std::string &lang_id, const std::string &mod_path)
static void add_base_catalogue (std::vector< trans_catalogue > &list, const std::string &lang_id)
static bool add_mod_catalogues (std::vector< trans_catalogue > &list, const std::string &lang_id)
void reload_catalogues ()
void unload_catalogues ()
void load_mod_catalogues ()
void unload_mod_catalogues ()
Variables
static trans_library trans_lib_singleton
static bool mod_catalogues_loaded = false
Function Documentation
add_base_catalogue()
static void l10n_data::add_base_catalogue (std::vector< trans_catalogue > & list, const std::string & lang_id) static
Definition at line 492 of file language.cpp.
{
    // TODO: split source code strings from data strings
    //       and load data translations from separate file(s)
    add_cat_if_exists( list, lang_id,
                       PATH_INFO::base_path() + "lang/mo/",
                       "/LC_MESSAGES/cataclysm-bn.mo"
                     );
}
References add_cat_if_exists(), and PATH_INFO::base_path().
Referenced by load_mod_catalogues(), reload_catalogues(), and unload_mod_catalogues().
add_cat_if_exists()
static void l10n_data::add_cat_if_exists (std::vector< trans_catalogue > & list, const std::string & lang_id, const std::string & path_start, const std::string & path_end) static
Definition at line 468 of file language.cpp.
{
    std::vector<std::string> opts = get_lang_path_substring( lang_id );
    for( const std::string &s : opts ) {
        std::string path = path_start + s + path_end;
        if( !file_exist( path ) ) {
            continue;
        }
        try {
            list.push_back( trans_catalogue::load_from_file( path ) );
        } catch( const std::runtime_error &err ) {
            debugmsg( "Failed to load translation catalogue '%s': %s", path, err.what() );
        }
        break;
    }
}
References debugmsg, file_exist(), get_lang_path_substring(), and Name::load_from_file().
Referenced by add_base_catalogue(), and add_mod_catalogue_if_exists().
add_mod_catalogue_if_exists()
static void l10n_data::add_mod_catalogue_if_exists (std::vector< trans_catalogue > & list, const std::string & lang_id, const std::string & mod_path) static
Definition at line 486 of file language.cpp.
{
    add_cat_if_exists( list, lang_id, mod_path + "/lang/", ".mo" );
}
References add_cat_if_exists().
Referenced by add_mod_catalogues(), and translatable_mod_info::update().
add_mod_catalogues()
static bool l10n_data::add_mod_catalogues (std::vector< trans_catalogue > & list, const std::string & lang_id) static
Definition at line 502 of file language.cpp.
{
    if( !world_generator || !world_generator->active_world ) {
        return false;
    }
    const std::vector<mod_id> &mods = world_generator->active_world->active_mod_order;
    for( const mod_id &mod : mods ) {
        add_mod_catalogue_if_exists( list, lang_id, mod->path );
    }
    return true;
}
References add_mod_catalogue_if_exists(), and world_generator.
Referenced by load_mod_catalogues(), and reload_catalogues().
get_library()
const cata_libintl::trans_library & l10n_data::get_library ()
Definition at line 457 of file language.cpp.
{
    return trans_lib_singleton;
}
References trans_lib_singleton.
Referenced by detail::_translate_internal(), pgettext(), vgettext(), and vpgettext().
load_mod_catalogues()
void l10n_data::load_mod_catalogues ()
Definition at line 531 of file language.cpp.
{
    assert( !mod_catalogues_loaded );
    std::vector<trans_catalogue> list;
    add_base_catalogue( list, get_language().id );
    mod_catalogues_loaded = add_mod_catalogues( list, get_language().id );
    set_library( trans_library::create( std::move( list ) ) );
}
References add_base_catalogue(), add_mod_catalogues(), get_language(), mod_catalogues_loaded, avatar_action::move(), and set_library().
Referenced by DynamicDataLoader::finalize_loaded_data().
reload_catalogues()
void l10n_data::reload_catalogues ()
Definition at line 515 of file language.cpp.
{
    std::vector<trans_catalogue> list;
    add_base_catalogue( list, get_language().id );
    add_mod_catalogues( list, get_language().id );
    set_library( trans_library::create( std::move( list ) ) );
}
References add_base_catalogue(), add_mod_catalogues(), get_language(), avatar_action::move(), and set_library().
Referenced by debug_menu::debug(), and set_language().
set_library()
static void l10n_data::set_library (trans_library lib) static
Definition at line 462 of file language.cpp.
{
    trans_lib_singleton = std::move( lib );
    invalidate_translations();
}
References invalidate_translations(), avatar_action::move(), and trans_lib_singleton.
Referenced by load_mod_catalogues(), reload_catalogues(), unload_catalogues(), and unload_mod_catalogues().
unload_catalogues()
void l10n_data::unload_catalogues ()
Definition at line 525 of file language.cpp.
{
    mod_catalogues_loaded = false;
    set_library( trans_library::create( {} ) );
}
References mod_catalogues_loaded, and set_library().
unload_mod_catalogues()
void l10n_data::unload_mod_catalogues ()
Definition at line 540 of file language.cpp.
{
    if( !mod_catalogues_loaded ) {
        return;
    }
    mod_catalogues_loaded = false;
    std::vector<trans_catalogue> list;
    add_base_catalogue( list, get_language().id );
    set_library( trans_library::create( std::move( list ) ) );
}
References add_base_catalogue(), get_language(), mod_catalogues_loaded, avatar_action::move(), and set_library().
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
mod_catalogues_loaded
bool l10n_data::mod_catalogues_loaded = false static
Definition at line 523 of file language.cpp.
Referenced by load_mod_catalogues(), unload_catalogues(), and unload_mod_catalogues().
trans_lib_singleton
trans_library l10n_data::trans_lib_singleton static
Definition at line 456 of file language.cpp.
Referenced by get_library(), and set_library().