Cataclysm BN: recipe_group Namespace Reference
recipe_group Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check ()
void reset ()
std::map< recipe_id, translation > get_recipes_by_bldg (const std::string &bldg)
std::map< recipe_id, translation > get_recipes_by_id (const std::string &id, const std::string &om_terrain_id="ANY")
Function Documentation
check()
void recipe_group::check ()
Definition at line 114 of file recipe_groups.cpp.
{
    recipe_groups_data.check();
}
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_recipes_by_bldg()
std::map< recipe_id, translation > recipe_group::get_recipes_by_bldg (const std::string & bldg)
Definition at line 65 of file recipe_groups.cpp.
{
    std::map<recipe_id, translation> all_rec;
    if( bldg == "ALL" ) {
        for( const auto &gr : recipe_groups_data.get_all() ) {
            all_rec.insert( gr.recipes.cbegin(), gr.recipes.cend() );
        }
        return all_rec;
    } else {
        for( const auto &gr : recipe_groups_data.get_all() ) {
            if( gr.building_type != bldg ) {
                continue;
            }
            all_rec.insert( gr.recipes.cbegin(), gr.recipes.cend() );
        }
        return all_rec;
    }
}
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by basecamp::recipe_deck().
get_recipes_by_id()
std::map< recipe_id, translation > recipe_group::get_recipes_by_id (const std::string & id, const std::string & om_terrain_id = "ANY")
Definition at line 84 of file recipe_groups.cpp.
{
    std::map<recipe_id, translation> all_rec;
    if( !recipe_groups_data.is_valid( group_id( id ) ) ) {
        return all_rec;
    }
    const recipe_group_data &group = recipe_groups_data.obj( group_id( id ) );
    if( om_terrain_id != "ANY" ) {
        std::string base_om_ter_id = oter_no_dir( oter_id( om_terrain_id ) );
        for( const auto &recp : group.recipes ) {
            const auto &recp_terrain = group.om_terrains.find( recp.first );
            if( recp_terrain == group.om_terrains.end() ) {
                continue;
            }
            if( recp_terrain->second.find( base_om_ter_id ) != recp_terrain->second.end() ) {
                all_rec.emplace( recp );
            }
        }
        return all_rec;
    }
    return group.recipes;
}
References oter_no_dir(), and anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by basecamp::expansion_tab(), basecamp::recipe_deck(), conditional_t< T >::set_at_om_location(), talk_function::start_camp(), and basecamp::survey_return().
load()
void recipe_group::load (const JsonObject & jo, const std::string & src)
Definition at line 109 of file recipe_groups.cpp.
{
    recipe_groups_data.load( jo, src );
}
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by DynamicDataLoader::initialize().
reset()
void recipe_group::reset ()
Definition at line 119 of file recipe_groups.cpp.
{
    recipe_groups_data.reset();
}
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by DynamicDataLoader::unload_data().