Cataclysm BN: construct Namespace Reference
construct Namespace Reference
Functions
bool check_nothing (const tripoint &)
bool check_empty (const tripoint &)
bool check_support (const tripoint &)
bool check_deconstruct (const tripoint &)
bool check_empty_up_OK (const tripoint &)
bool check_up_OK (const tripoint &)
bool check_down_OK (const tripoint &)
bool check_no_trap (const tripoint &)
bool check_ramp_low (const tripoint &)
bool check_ramp_high (const tripoint &)
static void done_nothing (const tripoint &)
void done_trunk_plank (const tripoint &)
void done_grave (const tripoint &)
void done_vehicle (const tripoint &)
void done_deconstruct (const tripoint &)
void done_digormine_stair (const tripoint &, bool)
void done_dig_stair (const tripoint &)
void done_mine_downstair (const tripoint &)
void done_mine_upstair (const tripoint &)
void done_wood_stairs (const tripoint &)
void done_window_curtains (const tripoint &)
void done_extract_maybe_revert_to_dirt (const tripoint &)
void done_mark_firewood (const tripoint &)
void done_mark_practice_target (const tripoint &)
void done_ramp_low (const tripoint &)
void done_ramp_high (const tripoint &)
void failure_standard (const tripoint &)
void failure_deconstruct (const tripoint &)
Function Documentation
check_deconstruct()
bool construct::check_deconstruct (const tripoint & p)
Definition at line 1221 of file construction.cpp.
{
    map &here = get_map();
    if( here.has_furn( p.xy() ) ) {
        return here.furn( p.xy() ).obj().deconstruct.can_do;
    }
    // terrain can only be deconstructed when there is no furniture in the way
    return here.ter( p.xy() ).obj().deconstruct.can_do;
}
References map_deconstruct_info::can_do, map_data_common_t::deconstruct, map::furn(), get_map(), map::has_furn(), int_id< T >::obj(), map::ter(), and tripoint::xy().
Referenced by construction::load().
check_down_OK()
bool construct::check_down_OK (const tripoint &)
Definition at line 1242 of file construction.cpp.
{
    // You're not going below -OVERMAP_DEPTH.
    return ( g->get_levz() > -OVERMAP_DEPTH );
}
References g, and OVERMAP_DEPTH.
Referenced by construction::load().
check_empty()
bool construct::check_empty (const tripoint & p)
Definition at line 1187 of file construction.cpp.
{
    map &here = get_map();
    return ( here.has_flag( flag_FLAT, p ) && !here.has_furn( p ) &&
             g->is_empty( p ) && here.tr_at( p ).is_null() &&
             here.i_at( p ).empty() && !here.veh_at( p ) );
}
References item_stack::empty(), flag_FLAT(), g, get_map(), map::has_flag(), map::has_furn(), map::i_at(), trap::is_null(), map::tr_at(), and map::veh_at().
Referenced by check_empty_up_OK(), and construction::load().
check_empty_up_OK()
bool construct::check_empty_up_OK (const tripoint & p)
Definition at line 1231 of file construction.cpp.
{
    return check_empty( p ) && check_up_OK( p );
}
References check_empty(), and check_up_OK().
Referenced by construction::load().
check_no_trap()
bool construct::check_no_trap (const tripoint & p)
Definition at line 1248 of file construction.cpp.
{
    return get_map().tr_at( p ).is_null();
}
References get_map(), trap::is_null(), and map::tr_at().
Referenced by construction::load().
check_nothing()
bool construct::check_nothing (const tripoint &)
Definition at line 1182 of file construction.cpp.
{
    return true;
}
Referenced by construction::load().
check_ramp_high()
bool construct::check_ramp_high (const tripoint & p)
Definition at line 1253 of file construction.cpp.
{
    if( check_up_OK( p ) && check_up_OK( p + tripoint_above ) ) {
        for( const point &car_d : four_cardinal_directions ) {
            // check adjacent points on the z-level above for a completed down ramp
            if( get_map().has_flag( TFLAG_RAMP_DOWN, p + car_d + tripoint_above ) ) {
                return true;
            }
        }
    }
    return false;
}
References check_up_OK(), four_cardinal_directions, get_map(), TFLAG_RAMP_DOWN, and tripoint_above.
Referenced by construction::load().
check_ramp_low()
bool construct::check_ramp_low (const tripoint & p)
Definition at line 1266 of file construction.cpp.
{
    return check_up_OK( p ) && check_up_OK( p + tripoint_above );
}
References check_up_OK(), and tripoint_above.
Referenced by construction::load().
check_support()
bool construct::check_support (const tripoint & p)
Definition at line 1205 of file construction.cpp.
{
    map &here = get_map();
    // need two or more orthogonally adjacent supports
    if( here.impassable( p ) ) {
        return false;
    }
    int num_supports = 0;
    for( const tripoint &nb : get_orthogonal_neighbors( p ) ) {
        if( here.has_flag( flag_SUPPORTS_ROOF, nb ) ) {
            num_supports++;
        }
    }
    return num_supports >= 2;
}
References flag_SUPPORTS_ROOF(), get_map(), get_orthogonal_neighbors(), map::has_flag(), and map::impassable().
Referenced by construction::load().
check_up_OK()
bool construct::check_up_OK (const tripoint &)
Definition at line 1236 of file construction.cpp.
{
    // You're not going above +OVERMAP_HEIGHT.
    return ( g->get_levz() < OVERMAP_HEIGHT );
}
References g, and OVERMAP_HEIGHT.
Referenced by check_empty_up_OK(), check_ramp_high(), check_ramp_low(), and construction::load().
done_deconstruct()
void construct::done_deconstruct (const tripoint & p)
Definition at line 1375 of file construction.cpp.
{
    map &here = get_map();
    // TODO: Make this the argument
    if( here.has_furn( p ) ) {
        const furn_t &f = here.furn( p ).obj();
        if( !f.deconstruct.can_do ) {
            add_msg( m_info, _( "That %s can not be disassembled!" ), f.name() );
            return;
        }
        if( f.deconstruct.furn_set.str().empty() ) {
            here.furn_set( p, f_null );
        } else {
            here.furn_set( p, f.deconstruct.furn_set );
        }
        add_msg( _( "The %s is disassembled." ), f.name() );
        here.spawn_items( p, item_group::items_from( f.deconstruct.drop_group, calendar::turn ) );
        // HACK: Hack alert.
        // Signs have cosmetics associated with them on the submap since
        // furniture can't store dynamic data to disk. To prevent writing
        // mysteriously appearing for a sign later built here, remove the
        // writing from the submap.
        here.delete_signage( p );
    } else {
        const ter_t &t = here.ter( p ).obj();
        if( !t.deconstruct.can_do ) {
            add_msg( _( "That %s can not be disassembled!" ), t.name() );
            return;
        }
        if( t.deconstruct.deconstruct_above ) {
            const tripoint top = p + tripoint_above;
            if( here.has_furn( top ) ) {
                add_msg( _( "That %s can not be disassembled, since there is furniture above it." ), t.name() );
                return;
            }
            done_deconstruct( top );
        }
        if( t.id == ter_str_id( "t_console_broken" ) )  {
            if( g->u.get_skill_level( skill_electronics ) >= 1 ) {
                g->u.practice( skill_electronics, 20, 4 );
            }
        }
        if( t.id == ter_str_id( "t_console" ) )  {
            if( g->u.get_skill_level( skill_electronics ) >= 1 ) {
                g->u.practice( skill_electronics, 40, 8 );
            }
        }
        here.ter_set( p, t.deconstruct.ter_set );
        add_msg( _( "The %s is disassembled." ), t.name() );
        here.spawn_items( p, item_group::items_from( t.deconstruct.drop_group, calendar::turn ) );
    }
}
References _, add_msg(), map_deconstruct_info::can_do, map_data_common_t::deconstruct, map_deconstruct_info::deconstruct_above, map::delete_signage(), done_deconstruct(), map_deconstruct_info::drop_group, f_null, map::furn(), map::furn_set(), map_deconstruct_info::furn_set, g, get_map(), map::has_furn(), ter_t::id, item_group::items_from(), m_info, map_data_common_t::name(), int_id< T >::obj(), skill_electronics, map::spawn_items(), string_id< T >::str(), map::ter(), map::ter_set(), map_deconstruct_info::ter_set, tripoint_above, and calendar::turn.
Referenced by done_deconstruct(), and construction::load().
done_dig_stair()
void construct::done_dig_stair (const tripoint & p)
Definition at line 1483 of file construction.cpp.
{
    done_digormine_stair( p, true );
}
References done_digormine_stair().
Referenced by construction::load().
done_digormine_stair()
void construct::done_digormine_stair (const tripoint & p, bool dig)
Definition at line 1438 of file construction.cpp.
{
    map &here = get_map();
    const tripoint abs_pos = here.getabs( p );
    const tripoint pos_sm = ms_to_sm_copy( abs_pos );
    tinymap tmpmap;
    tmpmap.load( tripoint( pos_sm.xy(), pos_sm.z - 1 ), false );
    const tripoint local_tmp = tmpmap.getlocal( abs_pos );
    bool dig_muts = g->u.has_trait( trait_PAINRESIST_TROGLO ) || g->u.has_trait( trait_STOCKY_TROGLO );
    int no_mut_penalty = dig_muts ? 10 : 0;
    int mine_penalty = dig ? 0 : 10;
    g->u.mod_stored_nutr( 5 + mine_penalty + no_mut_penalty );
    g->u.mod_thirst( 5 + mine_penalty + no_mut_penalty );
    g->u.mod_fatigue( 10 + mine_penalty + no_mut_penalty );
    if( tmpmap.ter( local_tmp ) == t_lava ) {
        if( !( query_yn( _( "The rock feels much warmer than normal.  Proceed?" ) ) ) ) {
            here.ter_set( p, t_pit ); // You dug down a bit before detecting the problem
            unroll_digging( dig ? 8 : 12 );
        } else {
            add_msg( m_warning, _( "You just tunneled into lava!" ) );
            g->events().send<event_type::digs_into_lava>();
            here.ter_set( p, t_open_air );
        }
        return;
    }
    bool impassable = tmpmap.impassable( local_tmp );
    if( !impassable ) {
        add_msg( _( "You dig into a preexisting space, and improvise a ladder." ) );
    } else if( dig ) {
        add_msg( _( "You dig a stairway, adding sturdy timbers and a rope for safety." ) );
    } else {
        add_msg( _( "You drill out a passage, heading deeper underground." ) );
    }
    here.ter_set( p, t_stairs_down ); // There's the top half
    // Again, need to use submap-local coordinates.
    tmpmap.ter_set( local_tmp, impassable ? t_stairs_up : t_ladder_up ); // and there's the bottom half.
    // And save to the center coordinate of the current active map.
    tmpmap.save();
}
References _, add_msg(), iuse::dig(), digs_into_lava, g, get_map(), map::getabs(), map::getlocal(), map::impassable(), map::load(), m_warning, ms_to_sm_copy(), query_yn(), map::save(), t_ladder_up, t_lava, t_open_air, t_pit, t_stairs_down, t_stairs_up, map::ter(), map::ter_set(), trait_PAINRESIST_TROGLO, trait_STOCKY_TROGLO, unroll_digging(), tripoint::xy(), and tripoint::z.
Referenced by done_dig_stair(), and done_mine_downstair().
done_extract_maybe_revert_to_dirt()
void construct::done_extract_maybe_revert_to_dirt (const tripoint & p)
Definition at line 1555 of file construction.cpp.
{
    map &here = get_map();
    if( one_in( 10 ) ) {
        here.ter_set( p, t_dirt );
    }
    if( here.ter( p ) == t_clay ) {
        add_msg( _( "You gather some clay." ) );
    } else if( here.ter( p ) == t_sand ) {
        add_msg( _( "You gather some sand." ) );
    } else {
        // Fall through to an undefined material.
        add_msg( _( "You gather some materials." ) );
    }
}
References _, add_msg(), get_map(), one_in(), t_clay, t_dirt, t_sand, map::ter(), and map::ter_set().
Referenced by construction::load().
done_grave()
void construct::done_grave (const tripoint & p)
Definition at line 1279 of file construction.cpp.
{
    map &here = get_map();
    map_stack its = here.i_at( p );
    for( item it : its ) {
        if( it.is_corpse() ) {
            if( it.get_corpse_name().empty() ) {
                if( it.get_mtype()->has_flag( MF_HUMAN ) ) {
                    if( g->u.has_trait( trait_SPIRITUAL ) ) {
                        g->u.add_morale( MORALE_FUNERAL, 50, 75, 1_days, 1_hours );
                        add_msg( m_good,
                                 _( "You feel relieved after providing last rites for this human being, whose name is lost in the Cataclysm." ) );
                    } else {
                        add_msg( m_neutral, _( "You bury remains of a human, whose name is lost in the Cataclysm." ) );
                    }
                }
            } else {
                if( g->u.has_trait( trait_SPIRITUAL ) ) {
                    g->u.add_morale( MORALE_FUNERAL, 50, 75, 1_days, 1_hours );
                    add_msg( m_good,
                             _( "You feel sadness, but also relief after providing last rites for %s, whose name you will keep in your memory." ),
                             it.get_corpse_name() );
                } else {
                    add_msg( m_neutral,
                             _( "You bury remains of %s, who joined uncounted masses perished in the Cataclysm." ),
                             it.get_corpse_name() );
                }
            }
            g->events().send<event_type::buries_corpse>(
                g->u.getID(), it.get_mtype()->id, it.get_corpse_name() );
        }
    }
    if( g->u.has_quality( qual_CUT ) ) {
        iuse::handle_ground_graffiti( g->u, nullptr, _( "Inscribe something on the grave?" ), p );
    } else {
        add_msg( m_neutral,
                 _( "Unfortunately you don't have anything sharp to place an inscription on the grave." ) );
    }
    here.destroy_furn( p, true );
}
References _, add_msg(), buries_corpse, map::destroy_furn(), g, get_map(), iuse::handle_ground_graffiti(), map::i_at(), m_good, m_neutral, MF_HUMAN, MORALE_FUNERAL, qual_CUT, and trait_SPIRITUAL.
Referenced by construction::load().
done_mark_firewood()
void construct::done_mark_firewood (const tripoint & p)
Definition at line 1572 of file construction.cpp.
{
    get_map().trap_set( p, tr_firewood_source );
}
References get_map(), tr_firewood_source, and map::trap_set().
Referenced by construction::load().
done_mark_practice_target()
void construct::done_mark_practice_target (const tripoint & p)
Definition at line 1577 of file construction.cpp.
{
    get_map().trap_set( p, tr_practice_target );
}
References get_map(), tr_practice_target, and map::trap_set().
Referenced by construction::load().
done_mine_downstair()
void construct::done_mine_downstair (const tripoint & p)
Definition at line 1488 of file construction.cpp.
{
    done_digormine_stair( p, false );
}
References done_digormine_stair().
Referenced by construction::load().
done_mine_upstair()
void construct::done_mine_upstair (const tripoint & p)
Definition at line 1493 of file construction.cpp.
{
    map &here = get_map();
    const tripoint abs_pos = here.getabs( p );
    const tripoint pos_sm = ms_to_sm_copy( abs_pos );
    tinymap tmpmap;
    tmpmap.load( tripoint( pos_sm.xy(), pos_sm.z + 1 ), false );
    const tripoint local_tmp = tmpmap.getlocal( abs_pos );
    if( tmpmap.ter( local_tmp ) == t_lava ) {
        here.ter_set( p.xy(), t_rock_floor ); // You dug a bit before discovering the problem
        add_msg( m_warning, _( "The rock overhead feels hot.  You decide *not* to mine magma." ) );
        unroll_digging( 12 );
        return;
    }
    static const std::set<ter_id> liquids = {{
            t_water_sh, t_sewage, t_water_dp, t_water_pool, t_water_moving_sh, t_water_moving_dp,
        }
    };
    if( liquids.count( tmpmap.ter( local_tmp ) ) > 0 ) {
        here.ter_set( p.xy(), t_rock_floor ); // You dug a bit before discovering the problem
        add_msg( m_warning, _( "The rock above is rather damp.  You decide *not* to mine water." ) );
        unroll_digging( 12 );
        return;
    }
    bool dig_muts = g->u.has_trait( trait_PAINRESIST_TROGLO ) || g->u.has_trait( trait_STOCKY_TROGLO );
    int no_mut_penalty = dig_muts ? 15 : 0;
    g->u.mod_stored_nutr( 20 + no_mut_penalty );
    g->u.mod_thirst( 20 + no_mut_penalty );
    g->u.mod_fatigue( 25 + no_mut_penalty );
    add_msg( _( "You drill out a passage, heading for the surface." ) );
    here.ter_set( p.xy(), t_stairs_up ); // There's the bottom half
    // We need to write to submap-local coordinates.
    // TODO: Add roof above
    tmpmap.ter_set( local_tmp, t_stairs_down ); // and there's the top half.
    tmpmap.save();
}
References _, add_msg(), g, get_map(), map::getabs(), map::getlocal(), map::load(), m_warning, ms_to_sm_copy(), map::save(), t_lava, t_rock_floor, t_sewage, t_stairs_down, t_stairs_up, t_water_dp, t_water_moving_dp, t_water_moving_sh, t_water_pool, t_water_sh, map::ter(), map::ter_set(), trait_PAINRESIST_TROGLO, trait_STOCKY_TROGLO, unroll_digging(), tripoint::xy(), and tripoint::z.
Referenced by construction::load().
done_nothing()
static void construct::done_nothing (const tripoint &) static
Definition at line 115 of file construction.cpp.
{}
Referenced by construction::load().
done_ramp_high()
void construct::done_ramp_high (const tripoint & p)
Definition at line 1588 of file construction.cpp.
{
    const tripoint top = p + tripoint_above;
    get_map().ter_set( top, ter_id( "t_ramp_down_high" ) );
}
References get_map(), map::ter_set(), and tripoint_above.
Referenced by construction::load().
done_ramp_low()
void construct::done_ramp_low (const tripoint & p)
Definition at line 1582 of file construction.cpp.
{
    const tripoint top = p + tripoint_above;
    get_map().ter_set( top, ter_id( "t_ramp_down_low" ) );
}
References get_map(), map::ter_set(), and tripoint_above.
Referenced by construction::load().
done_trunk_plank()
void construct::done_trunk_plank (const tripoint &)
Definition at line 1271 of file construction.cpp.
{
    int num_logs = rng( 2, 3 );
    for( int i = 0; i < num_logs; ++i ) {
        iuse::cut_log_into_planks( g->u );
    }
}
References iuse::cut_log_into_planks(), g, and rng().
Referenced by construction::load().
done_vehicle()
void construct::done_vehicle (const tripoint & p)
Definition at line 1343 of file construction.cpp.
{
    std::string name = string_input_popup()
                       .title( _( "Enter new vehicle name:" ) )
                       .width( 20 )
                       .query_string();
    if( name.empty() ) {
        name = _( "Car" );
    }
    map &m = get_map();
    avatar &u = get_avatar();
    vehicle *veh = m.add_vehicle( vproto_id( "none" ), p, 270_degrees, 0, 0 );
    if( !veh ) {
        debugmsg( "error constructing vehicle" );
        return;
    }
    veh->name = name;
    if( u.has_trait( trait_DEBUG_HS ) ) {
        // TODO: Allow DEBUG_HS to consume items that don't exist
        veh->install_part( point_zero, vpart_id( "frame_vertical_2" ) );
    } else {
        veh->install_part( point_zero, vpart_from_item( u.lastconsumed ) );
    }
    // Update the vehicle cache immediately,
    // or the vehicle will be invisible for the first couple of turns.
    m.add_vehicle_to_cache( veh );
}
References _, map::add_vehicle(), map::add_vehicle_to_cache(), debugmsg, get_avatar(), get_map(), Character::has_trait(), vehicle::install_part(), player::lastconsumed, om_direction::name(), vehicle::name, point_zero, string_input_popup::query_string(), string_input_popup::title(), trait_DEBUG_HS, vpart_from_item(), and string_input_popup::width().
Referenced by construction::load().
done_window_curtains()
void construct::done_window_curtains (const tripoint &)
Definition at line 1543 of file construction.cpp.
{
    map &here = get_map();
    // copied from iexamine::curtains
    here.spawn_item( g->u.pos(), itype_nail, 1, 4 );
    here.spawn_item( g->u.pos(), itype_sheet, 2 );
    here.spawn_item( g->u.pos(), itype_stick );
    here.spawn_item( g->u.pos(), itype_string_36 );
    g->u.add_msg_if_player(
        _( "After boarding up the window the curtains and curtain rod are left." ) );
}
References _, g, get_map(), itype_nail, itype_sheet, itype_stick, itype_string_36, and map::spawn_item().
Referenced by construction::load().
done_wood_stairs()
void construct::done_wood_stairs (const tripoint & p)
Definition at line 1536 of file construction.cpp.
{
    const tripoint top = p + tripoint_above;
    // TODO: Add roof above
    get_map().ter_set( top, ter_id( "t_wood_stairs_down" ) );
}
References get_map(), map::ter_set(), and tripoint_above.
Referenced by construction::load().
failure_deconstruct()
void construct::failure_deconstruct (const tripoint &)
Definition at line 1599 of file construction.cpp.
{
    add_msg( m_info, _( "You cannot deconstruct this!" ) );
}
References _, add_msg(), and m_info.
Referenced by construction::load().
failure_standard()
void construct::failure_standard (const tripoint &)
Definition at line 1594 of file construction.cpp.
{
    add_msg( m_info, _( "You cannot build there!" ) );
}
References _, add_msg(), and m_info.
Referenced by construction::load().