Cataclysm BN: anonymous_namespace{field_type.cpp} Namespace Reference
anonymous_namespace{field_type.cpp} Namespace Reference
Variables
generic_factory< field_type > all_field_types ("field types")
Variable Documentation
all_field_types
generic_factory< field_type > anonymous_namespace{field_type.cpp}::all_field_types("field types") ("field types")
Referenced by field_types::check_consistency(), field_type::count(), field_types::finalize_all(), field_types::get_all(), field_types::get_field_type_by_legacy_enum(), string_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), field_types::load(), int_id< T >::obj(), string_id< T >::obj(), and field_types::reset().