Cataclysm BN: character_funcs Namespace Reference
character_funcs Namespace Reference
Classes
struct comfort_response_t
Enumerations
enum class comfort_level {
impossible = -999 , uncomfortable = -7 , neutral = 0 , slightly_comfortable = 3 ,
comfortable = 5 , very_comfortable = 10
}
Functions
time_duration estimate_effect_dur (int skill_lvl, const efftype_id &effect, const time_duration &error_magnitude, int threshold, const Creature &target)
Estimate effect duration based on relevant skill.
void siphon (Character &ch, vehicle &veh, const itype_id &desired_liquid)
Siphons fuel (if available) from the specified vehicle into container or similar via game::handle_liquid.
bool is_fun_to_read (const Character &ch, const item &book)
Returns whether character considers it fun to read the book.
int get_book_fun_for (const Character &ch, const item &book)
Returns enjoyability value of a book for given character.
comfort_response_t base_comfort_value (const Character &who, const tripoint &p)
Rate point's ability to serve as a bed.
int rate_sleep_spot (const Character &who, const tripoint &p)
Rate point's ability to serve as a bed.
bool roll_can_sleep (Character &who)
Checked each turn during "lying_down", returns true if the avatar falls asleep.
bool can_interface_armor (const Character &who)
Check whether character has an active bionic capable of interfacing with power armor.
std::string fmt_wielded_weapon (const Character &who)
Get the formatted name of the currently wielded item (if any) with current gun mode (if gun)
void add_pain_msg (const Character &who, int val, body_part bp)
Add message describing how character feels pain.
void normalize (Character &who)
Reset Character's weapon and body state (limb hp, stamina, active martial art)
void store_in_container (Character &who, item &container, item &put, bool penalties, int base_cost)
Stores an item inside another consuming moves proportional to weapon skill and volume.
bool try_wield_contents (Character &who, item &container, item *internal_item, bool penalties, int base_cost)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
bool try_uncanny_dodge (Character &who)
Try to execute an uncanny dodge bionic ability.
cata::optional< tripoint > pick_safe_adjacent_tile (const Character &who)
Returns an unoccupied, safe adjacent point.
bool is_bp_immune_to (const Character &who, body_part bp, damage_unit dam)
Check if character's body part is immune to given damage.
std::vector< npc * > get_crafting_helpers (const Character &who, int max=-1)
Returns nearby NPCs ready and willing to help with crafting or some other manual task.
int get_lift_strength (const Character &who)
Returns Character lift strength unassisted by helpers or equipment.
int get_lift_strength_with_helpers (const Character &who)
Returns Character lift strength without equipment including bonus from nearby helpers.
bool can_lift_with_helpers (const Character &who, int lift_required)
Returns whether character can lift given value (includes bonus from helpers).
bool list_ammo (const Character &who, const item &base, std::vector< item_reload_option > &ammo_list, bool include_empty_mags, bool include_potential)
List ammo suitable for given item.
item_reload_option select_ammo (const Character &who, const item &base, std::vector< item_reload_option > opts)
Select ammo from the provided options.
item_reload_option select_ammo (const Character &who, const item &base, bool prompt=false, bool include_empty_mags=true, bool include_potential=false)
Select suitable ammo with which to reload the item.
std::vector< const item * > get_ammo_items (const Character &who, const ammotype &at)
Returns character's items that are ammo and have the matching ammo type.
template<typename T , typename Output >
void find_ammo_helper (T &src, const item &obj, bool empty, Output out, bool nested)
std::vector< item_location > find_ammo_items_or_mags (const Character &who, const item &obj, bool empty=true, int radius=1)
Searches for ammo or magazines that can be used to reload given item.
std::vector< item_location > find_reloadables (const Character &who)
Searches for weapons and magazines that can be reloaded.
int ammo_count_for (const Character &who, const item &gun)
Counts ammo and UPS charges (lower of) for a given gun on the character.
void show_skill_capped_notice (const Character &who, const skill_id &id)
This shows warning to the player that their current activity will not give them xp.
void update_body_wetness (Character &who, const w_point &weather)
Maintains body wetness and handles the rate at which the player dries.
void do_pause (Character &who)
Do pause action ('.
void search_surroundings (Character &who)
Search surrounding squares for traps (and maybe other things in the future).
void update_mental_focus (Character &who)
Uses calc_focus_change to update the player's current focus.
float fine_detail_vision_mod (const Character &who)
Calculates multiplier for the time taken to perform tasks that require detail vision (reading, crafting, etc.).
float fine_detail_vision_mod (const Character &who, const tripoint &p)
bool can_see_fine_details (const Character &who)
Checks whether character vision at given pos is good enough to see fine details.
bool can_see_fine_details (const Character &who, const tripoint &p)
Variables
constexpr float FINE_VISION_THRESHOLD = 4.0f
Threshold for fine detail vision mod.
constexpr float FINE_VISION_PERFECT = 1.0f
Value for perfect fine detail vision.
Enumeration Type Documentation
comfort_level
enum class character_funcs::comfort_level strong
Enumerator
impossible
uncomfortable
neutral
slightly_comfortable
comfortable
very_comfortable
Definition at line 82 of file character_functions.h.
{
    impossible = -999,
    uncomfortable = -7,
    neutral = 0,
    slightly_comfortable = 3,
    comfortable = 5,
    very_comfortable = 10
};
Function Documentation
add_pain_msg()
void character_funcs::add_pain_msg (const Character & who, int val, body_part bp)
Add message describing how character feels pain.
Parameters
who Character that feels the pain
val Amount of pain
bp Target body part, use num_bp if no specific body part.
Definition at line 449 of file character_functions.cpp.
{
    if( who.has_trait( trait_NOPAIN ) ) {
        return;
    }
    if( bp == num_bp ) {
        if( val > 20 ) {
            who.add_msg_if_player( _( "Your body is wracked with excruciating pain!" ) );
        } else if( val > 10 ) {
            who.add_msg_if_player( _( "Your body is wracked with terrible pain!" ) );
        } else if( val > 5 ) {
            who.add_msg_if_player( _( "Your body is wracked with pain!" ) );
        } else if( val > 1 ) {
            who.add_msg_if_player( _( "Your body pains you!" ) );
        } else {
            who.add_msg_if_player( _( "Your body aches." ) );
        }
    } else {
        if( val > 20 ) {
            who.add_msg_if_player( _( "Your %s is wracked with excruciating pain!" ),
                                   body_part_name_accusative( bp ) );
        } else if( val > 10 ) {
            who.add_msg_if_player( _( "Your %s is wracked with terrible pain!" ),
                                   body_part_name_accusative( bp ) );
        } else if( val > 5 ) {
            who.add_msg_if_player( _( "Your %s is wracked with pain!" ),
                                   body_part_name_accusative( bp ) );
        } else if( val > 1 ) {
            who.add_msg_if_player( _( "Your %s pains you!" ),
                                   body_part_name_accusative( bp ) );
        } else {
            who.add_msg_if_player( _( "Your %s aches." ),
                                   body_part_name_accusative( bp ) );
        }
    }
}
References _, Creature::add_msg_if_player(), body_part_name_accusative(), Character::has_trait(), num_bp, and trait_NOPAIN.
Referenced by Character::process_one_effect().
ammo_count_for()
int character_funcs::ammo_count_for (const Character & who, const item & gun)
Counts ammo and UPS charges (lower of) for a given gun on the character.
Definition at line 1180 of file character_functions.cpp.
{
    int ret = item::INFINITE_CHARGES;
    if( !gun.is_gun() ) {
        return ret;
    }
    int required = gun.ammo_required();
    if( required > 0 ) {
        int total_ammo = 0;
        total_ammo += gun.ammo_remaining();
        bool has_mag = gun.magazine_integral();
        const auto found_ammo = find_ammo_items_or_mags( who, gun, true, -1 );
        int loose_ammo = 0;
        for( const auto &ammo : found_ammo ) {
            if( ammo->is_magazine() ) {
                has_mag = true;
                total_ammo += ammo->ammo_remaining();
            } else if( ammo->is_ammo() ) {
                loose_ammo += ammo->charges;
            }
        }
        if( has_mag ) {
            total_ammo += loose_ammo;
        }
        ret = std::min( ret, total_ammo / required );
    }
    int ups_drain = gun.get_gun_ups_drain();
    if( ups_drain > 0 ) {
        ret = std::min( ret, who.charges_of( itype_UPS ) / ups_drain );
    }
    return ret;
}
References item::ammo_remaining(), item::ammo_required(), item::charges, visitable< T >::charges_of(), find_ammo_items_or_mags(), item::get_gun_ups_drain(), item::INFINITE_CHARGES, item::is_ammo(), item::is_gun(), item::is_magazine(), itype_UPS, item::magazine_integral(), and cata::hash64_detail::ret.
Referenced by give_item_to().
base_comfort_value()
comfort_response_t character_funcs::base_comfort_value (const Character & who, const tripoint & p)
Rate point's ability to serve as a bed.
Only takes certain mutations into account, and not fatigue nor stimulants.
Definition at line 182 of file character_functions.cpp.
{
    // Comfort of sleeping spots is "objective", while sleep_spot( p ) is "subjective"
    // As in the latter also checks for fatigue and other variables while this function
    // only looks at the base comfyness of something. It's still subjective, in a sense,
    // as arachnids who sleep in webs will find most places comfortable for instance.
    int comfort = 0;
    comfort_response_t comfort_response;
    bool plantsleep = who.has_trait( trait_CHLOROMORPH );
    bool fungaloid_cosplay = who.has_trait( trait_M_SKIN3 );
    bool websleep = who.has_trait( trait_WEB_WALKER );
    bool webforce = who.has_trait( trait_THRESH_SPIDER ) && ( who.has_trait( trait_WEB_SPINNER ) ||
                    ( who.has_trait( trait_WEB_WEAVER ) ) );
    bool in_shell = who.has_active_mutation( trait_SHELL2 );
    bool watersleep = who.has_trait( trait_WATERSLEEP );
    map &here = get_map();
    const optional_vpart_position vp = here.veh_at( p );
    const maptile tile = here.maptile_at( p );
    const trap &trap_at_pos = tile.get_trap_t();
    const ter_id ter_at_pos = tile.get_ter();
    const furn_id furn_at_pos = tile.get_furn();
    int web = here.get_field_intensity( p, fd_web );
    // Some mutants have different comfort needs
    if( !plantsleep && !webforce ) {
        if( in_shell ) {
            comfort += 1 + static_cast<int>( comfort_level::slightly_comfortable );
            // Note: shelled individuals can still use sleeping aids!
        } else if( vp ) {
            const cata::optional<vpart_reference> carg = vp.part_with_feature( "CARGO", false );
            const cata::optional<vpart_reference> board = vp.part_with_feature( "BOARDABLE", true );
            if( carg ) {
                const vehicle_stack items = vp->vehicle().get_items( carg->part_index() );
                for( const item &items_it : items ) {
                    if( items_it.has_flag( "SLEEP_AID" ) ) {
                        // Note: BED + SLEEP_AID = 9 pts, or 1 pt below very_comfortable
                        comfort += 1 + static_cast<int>( comfort_level::slightly_comfortable );
                        comfort_response.aid = &items_it;
                        break; // prevents using more than 1 sleep aid
                    }
                }
            }
            if( board ) {
                comfort += board->info().comfort;
            } else {
                comfort -= here.move_cost( p );
            }
        }
        // Not in a vehicle, start checking furniture/terrain/traps at this point in decreasing order
        else if( furn_at_pos != f_null ) {
            comfort += 0 + furn_at_pos.obj().comfort;
        }
        // Web sleepers can use their webs if better furniture isn't available
        else if( websleep && web >= 3 ) {
            comfort += 1 + static_cast<int>( comfort_level::slightly_comfortable );
        } else if( ter_at_pos == t_improvised_shelter ) {
            comfort += 0 + static_cast<int>( comfort_level::slightly_comfortable );
        } else if( ter_at_pos == t_floor || ter_at_pos == t_floor_waxed ||
                   ter_at_pos == t_carpet_red || ter_at_pos == t_carpet_yellow ||
                   ter_at_pos == t_carpet_green || ter_at_pos == t_carpet_purple ) {
            comfort += 1 + static_cast<int>( comfort_level::neutral );
        } else if( !trap_at_pos.is_null() ) {
            comfort += 0 + trap_at_pos.comfort;
        } else {
            // Not a comfortable sleeping spot
            comfort -= here.move_cost( p );
        }
        if( comfort_response.aid == nullptr ) {
            const map_stack items = here.i_at( p );
            for( const item &items_it : items ) {
                if( items_it.has_flag( "SLEEP_AID" ) ) {
                    // Note: BED + SLEEP_AID = 9 pts, or 1 pt below very_comfortable
                    comfort += 1 + static_cast<int>( comfort_level::slightly_comfortable );
                    comfort_response.aid = &items_it;
                    break; // prevents using more than 1 sleep aid
                }
            }
        }
        if( fungaloid_cosplay && here.has_flag_ter_or_furn( flag_FUNGUS, p ) ) {
            comfort += static_cast<int>( comfort_level::very_comfortable );
        } else if( watersleep && here.has_flag_ter( flag_SWIMMABLE, p ) ) {
            comfort += static_cast<int>( comfort_level::very_comfortable );
        }
    } else if( plantsleep ) {
        if( vp || furn_at_pos != f_null ) {
            // Sleep ain't happening in a vehicle or on furniture
            comfort = static_cast<int>( comfort_level::impossible );
        } else {
            // It's very easy for Chloromorphs to get to sleep on soil!
            if( ter_at_pos == t_dirt || ter_at_pos == t_pit || ter_at_pos == t_dirtmound ||
                ter_at_pos == t_pit_shallow ) {
                comfort += static_cast<int>( comfort_level::very_comfortable );
            }
            // Not as much if you have to dig through stuff first
            else if( ter_at_pos == t_grass ) {
                comfort += static_cast<int>( comfort_level::comfortable );
            }
            // Sleep ain't happening
            else {
                comfort = static_cast<int>( comfort_level::impossible );
            }
        }
        // Has webforce
    } else {
        if( web >= 3 ) {
            // Thick Web and you're good to go
            comfort += static_cast<int>( comfort_level::very_comfortable );
        } else {
            comfort = static_cast<int>( comfort_level::impossible );
        }
    }
    if( comfort > static_cast<int>( comfort_level::comfortable ) ) {
        comfort_response.level = comfort_level::very_comfortable;
    } else if( comfort > static_cast<int>( comfort_level::slightly_comfortable ) ) {
        comfort_response.level = comfort_level::comfortable;
    } else if( comfort > static_cast<int>( comfort_level::neutral ) ) {
        comfort_response.level = comfort_level::slightly_comfortable;
    } else if( comfort == static_cast<int>( comfort_level::neutral ) ) {
        comfort_response.level = comfort_level::neutral;
    } else {
        comfort_response.level = comfort_level::uncomfortable;
    }
    return comfort_response;
}
References character_funcs::comfort_response_t::aid, trapfunc::board(), furn_t::comfort, trap::comfort, comfortable, f_null, fd_web, flag_FUNGUS(), flag_SWIMMABLE(), map::get_field_intensity(), maptile::get_furn(), get_map(), maptile::get_ter(), maptile::get_trap_t(), Character::has_active_mutation(), map::has_flag_ter(), map::has_flag_ter_or_furn(), Character::has_trait(), map::i_at(), impossible, trap::is_null(), character_funcs::comfort_response_t::level, map::maptile_at(), map::move_cost(), neutral, int_id< T >::obj(), optional_vpart_position::part_with_feature(), slightly_comfortable, t_carpet_green, t_carpet_purple, t_carpet_red, t_carpet_yellow, t_dirt, t_dirtmound, t_floor, t_floor_waxed, t_grass, t_improvised_shelter, t_pit, t_pit_shallow, trait_CHLOROMORPH, trait_M_SKIN3, trait_SHELL2, trait_THRESH_SPIDER, trait_WATERSLEEP, trait_WEB_SPINNER, trait_WEB_WALKER, trait_WEB_WEAVER, uncomfortable, map::veh_at(), and very_comfortable.
Referenced by rate_sleep_spot(), and Character::update_needs().
can_interface_armor()
bool character_funcs::can_interface_armor (const Character & who)
Check whether character has an active bionic capable of interfacing with power armor.
Definition at line 401 of file character_functions.cpp.
{
    bool okay = std::any_of( who.my_bionics->begin(), who.my_bionics->end(),
    []( const bionic & b ) {
        return b.powered && b.info().has_flag( STATIC( flag_str_id( "BIONIC_ARMOR_INTERFACE" ) ) );
    } );
    return okay;
}
References b, and Character::my_bionics.
Referenced by Character::consume_charges(), Character::has_enough_charges(), item::process_tool(), item::units_remaining(), iuse_transform::use(), and set_transform_iuse::use().
can_lift_with_helpers()
bool character_funcs::can_lift_with_helpers (const Character & who, int lift_required)
Returns whether character can lift given value (includes bonus from helpers).
Definition at line 701 of file character_functions.cpp.
{
    return get_lift_strength_with_helpers( who ) >= lift_required;
}
References get_lift_strength_with_helpers().
Referenced by can_do_activity_there(), veh_interact::can_remove_part(), and veh_interact::update_part_requirements().
can_see_fine_details() [1/2]
bool character_funcs::can_see_fine_details (const Character & who)
Checks whether character vision at given pos is good enough to see fine details.
Fine vision is required for some interactions (reading, crafting, etc.)
Parameters
who Character to check for
pos Check remote spot as if the character were standing there
Definition at line 172 of file character_functions.cpp.
{
    return can_see_fine_details( who, who.pos() );
}
References can_see_fine_details(), and Character::pos().
Referenced by butcher_submenu(), npc::can_read(), can_see_fine_details(), repair_item_actor::can_use_tool(), veh_interact::cant_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), avatar::get_book_reader(), lighting_crafting_speed_multiplier(), player_can_see_to_build(), activity_handlers::study_spell_do_turn(), iexamine::trap(), reveal_map_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), iuse::wash_all_items(), iuse::wash_hard_items(), and iuse::wash_soft_items().
can_see_fine_details() [2/2]
bool character_funcs::can_see_fine_details (const Character & who, const tripoint & p)
Definition at line 177 of file character_functions.cpp.
{
    return fine_detail_vision_mod( who, p ) <= FINE_VISION_THRESHOLD;
}
References fine_detail_vision_mod(), and FINE_VISION_THRESHOLD.
do_pause()
void character_funcs::do_pause (Character & who)
Do pause action ('.
' key).
Definition at line 962 of file character_turn.cpp.
{
    map &here = get_map();
    who.moves = 0;
    who.recoil = MAX_RECOIL;
    // Train swimming if underwater
    if( !who.in_vehicle ) {
        if( who.is_underwater() ) {
            who.as_player()->practice( skill_swimming, 1 );
            who.drench( 100, { {
                    bp_leg_l, bp_leg_r, bp_torso, bp_arm_l,
                    bp_arm_r, bp_head, bp_eyes, bp_mouth,
                    bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r
                }
            }, true );
        } else if( here.has_flag( TFLAG_DEEP_WATER, who.pos() ) ) {
            who.as_player()->practice( skill_swimming, 1 );
            // Same as above, except no head/eyes/mouth
            who.drench( 100, { {
                    bp_leg_l, bp_leg_r, bp_torso, bp_arm_l,
                    bp_arm_r, bp_foot_l, bp_foot_r, bp_hand_l,
                    bp_hand_r
                }
            }, true );
        } else if( here.has_flag( "SWIMMABLE", who.pos() ) ) {
            who.drench( 40, { { bp_foot_l, bp_foot_r, bp_leg_l, bp_leg_r } }, false );
        }
    }
    // Try to put out clothing/hair fire
    if( who.has_effect( effect_onfire ) ) {
        time_duration total_removed = 0_turns;
        time_duration total_left = 0_turns;
        bool on_ground = who.has_effect( effect_downed );
        for( const body_part bp : all_body_parts ) {
            effect &eff = who.get_effect( effect_onfire, bp );
            if( eff.is_null() ) {
                continue;
            }
            // TODO: Tools and skills
            total_left += eff.get_duration();
            // Being on the ground will smother the fire much faster because you can roll
            const time_duration dur_removed = on_ground ? eff.get_duration() / 2 + 2_turns : 5_turns;
            eff.mod_duration( -dur_removed );
            total_removed += dur_removed;
        }
        // Don't drop on the ground when the ground is on fire
        if( total_left > 3_turns && !who.is_dangerous_fields( here.field_at( who.pos() ) ) ) {
            who.add_effect( effect_downed, 2_turns, num_bp, 0, true );
            who.add_msg_player_or_npc( m_warning,
                                       _( "You roll on the ground, trying to smother the fire!" ),
                                       _( "<npcname> rolls on the ground!" ) );
        } else if( total_removed > 0_turns ) {
            who.add_msg_player_or_npc( m_warning,
                                       _( "You attempt to put out the fire on you!" ),
                                       _( "<npcname> attempts to put out the fire on them!" ) );
        }
    }
    // on-pause effects for martial arts
    who.martial_arts_data->ma_onpause_effects( who );
    if( who.is_npc() ) {
        // The stuff below doesn't apply to NPCs
        // search_surroundings should eventually do, though
        return;
    }
    if( who.in_vehicle && one_in( 8 ) ) {
        VehicleList vehs = here.get_vehicles();
        vehicle *veh = nullptr;
        for( auto &v : vehs ) {
            veh = v.v;
            if( veh && veh->is_moving() && veh->player_in_control( who ) ) {
                double exp_temp = 1 + veh->total_mass() / 400.0_kilogram +
                                  std::abs( veh->velocity / 3200.0 );
                int experience = static_cast<int>( exp_temp );
                if( exp_temp - experience > 0 && x_in_y( exp_temp - experience, 1.0 ) ) {
                    experience++;
                }
                who.as_player()->practice( skill_id( "driving" ), experience );
                break;
            }
        }
    }
    search_surroundings( who );
    who.wait_effects();
}
References _, Creature::add_effect(), Creature::add_msg_player_or_npc(), all_body_parts, Creature::as_player(), bp_arm_l, bp_arm_r, bp_eyes, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_mouth, bp_torso, Character::drench(), effect_downed, effect_onfire, map::field_at(), effect::get_duration(), Creature::get_effect(), get_map(), map::get_vehicles(), Creature::has_effect(), map::has_flag(), Character::in_vehicle, Creature::is_dangerous_fields(), vehicle::is_moving(), Creature::is_npc(), effect::is_null(), Creature::is_underwater(), m_warning, Character::martial_arts_data, MAX_RECOIL, effect::mod_duration(), Creature::moves, num_bp, one_in(), vehicle::player_in_control(), Character::pos(), Character::practice(), Character::recoil, search_surroundings(), skill_swimming, TFLAG_DEEP_WATER, vehicle::total_mass(), vehicle::velocity, Character::wait_effects(), and x_in_y().
Referenced by player_activity::do_turn(), game::handle_action(), and npc::move_pause().
estimate_effect_dur()
time_duration character_funcs::estimate_effect_dur (int skill_lvl, const efftype_id & target_effect, const time_duration & error_magnitude, int threshold, const Creature & target)
Estimate effect duration based on relevant skill.
Definition at line 72 of file character_functions.cpp.
{
    const time_duration zero_duration = 0_turns;
    time_duration estimate = std::max( zero_duration, target.get_effect_dur( target_effect ) +
                                       rng( -1, 1 ) * error_magnitude *
                                       rng( 0, std::max( 0, threshold - skill_lvl ) ) );
    return estimate;
}
References Creature::get_effect_dur(), and rng().
Referenced by dialogue::dynamic_line().
find_ammo_helper()
template<typename T , typename Output > void character_funcs::find_ammo_helper (T & src, const item & obj, bool empty, Output out, bool nested)
Definition at line 1051 of file character_functions.cpp.
{
    if( obj.is_watertight_container() ) {
        if( !obj.is_container_empty() ) {
            auto contents_id = obj.contents.front().typeId();
            // Look for containers with the same type of liquid as that already in our container
            src.visit_items( [&src, &nested, &out, &contents_id, &obj]( item * node ) {
                if( node == &obj ) {
                    // This stops containers and magazines counting *themselves* as ammo sources.
                    return VisitResponse::SKIP;
                }
                if( node->is_container() && !node->is_container_empty() &&
                    node->contents.front().typeId() == contents_id ) {
                    out = item_location( src, node );
                }
                return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
            } );
        } else {
            // Look for containers with any liquid
            src.visit_items( [&src, &nested, &out]( item * node ) {
                if( node->is_container() && node->contents_made_of( LIQUID ) ) {
                    out = item_location( src, node );
                }
                return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
            } );
        }
    }
    if( obj.magazine_integral() ) {
        // find suitable ammo excluding that already loaded in magazines
        const std::set<ammotype> &ammo = obj.ammo_types();
        const auto mags = obj.magazine_compatible();
        src.visit_items( [&src, &nested, &out, &mags, ammo]( item * node ) {
            if( node->is_gun() || node->is_tool() ) {
                // guns/tools never contain usable ammo so most efficient to skip them now
                return VisitResponse::SKIP;
            }
            if( !node->made_of( SOLID ) ) {
                // some liquids are ammo but we can't reload with them unless within a container or frozen
                return VisitResponse::SKIP;
            }
            if( node->is_ammo_container() && !node->contents.empty() &&
                !node->contents_made_of( SOLID ) ) {
                for( const ammotype &at : ammo ) {
                    if( node->contents.front().ammo_type() == at ) {
                        out = item_location( src, node );
                    }
                }
                return VisitResponse::SKIP;
            }
            for( const ammotype &at : ammo ) {
                if( node->ammo_type() == at ) {
                    out = item_location( src, node );
                }
            }
            if( node->is_magazine() && node->has_flag( flag_SPEEDLOADER ) ) {
                if( mags.count( node->typeId() ) && node->ammo_remaining() ) {
                    out = item_location( src, node );
                }
            }
            return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
        } );
    } else {
        // find compatible magazines excluding those already loaded in tools/guns
        const auto mags = obj.magazine_compatible();
        src.visit_items( [&src, &nested, &out, mags, empty]( item * node ) {
            if( node->is_gun() || node->is_tool() ) {
                return VisitResponse::SKIP;
            }
            if( node->is_magazine() ) {
                if( mags.count( node->typeId() ) && ( node->ammo_remaining() || empty ) ) {
                    out = item_location( src, node );
                }
                return VisitResponse::SKIP;
            }
            return nested ? VisitResponse::NEXT : VisitResponse::SKIP;
        } );
    }
}
References item::ammo_type(), item::contents, item::contents_made_of(), item_contents::empty(), flag_SPEEDLOADER(), item_contents::front(), item::has_flag(), item::is_ammo_container(), item::is_container(), item::is_container_empty(), item::is_gun(), item::is_magazine(), item::is_tool(), LIQUID, item::made_of(), NEXT, int_id< T >::obj(), SKIP, SOLID, and item::typeId().
Referenced by find_ammo_items_or_mags().
find_ammo_items_or_mags()
std::vector< item_location > character_funcs::find_ammo_items_or_mags (const Character & who, const item & obj, bool empty = true, int radius = 1)
Searches for ammo or magazines that can be used to reload given item.
Parameters
who Character looking for ammo
obj item to be reloaded. By design any currently loaded ammunition or magazine is ignored
empty whether empty magazines should be considered as possible ammo
radius adjacent map/vehicle tiles to search. 0 for only character tile, -1 for only inventory
Definition at line 1135 of file character_functions.cpp.
{
    std::vector<item_location> res;
    find_ammo_helper( const_cast<Character &>( who ), obj, empty, std::back_inserter( res ), true );
    if( radius >= 0 ) {
        for( auto &cursor : map_selector( who.pos(), radius ) ) {
            find_ammo_helper( cursor, obj, empty, std::back_inserter( res ), false );
        }
        for( auto &cursor : vehicle_selector( who.pos(), radius ) ) {
            find_ammo_helper( cursor, obj, empty, std::back_inserter( res ), false );
        }
    }
    return res;
}
References find_ammo_helper(), int_id< T >::obj(), and Character::pos().
Referenced by ammo_count_for(), item::color_in_inventory(), and list_ammo().
find_reloadables()
std::vector< item_location > character_funcs::find_reloadables (const Character & who)
Searches for weapons and magazines that can be reloaded.
Definition at line 1154 of file character_functions.cpp.
{
    std::vector<item_location> reloadables;
    who.visit_items( [&]( const item * node ) {
        if( node->is_holster() ) {
            return VisitResponse::NEXT;
        }
        bool reloadable = false;
        if( node->is_gun() && !node->magazine_compatible().empty() ) {
            reloadable = node->magazine_current() == nullptr ||
                         node->ammo_remaining() < node->ammo_capacity();
        } else {
            reloadable = ( node->is_magazine() || node->is_bandolier() ||
                           ( node->is_gun() && node->magazine_integral() ) ) &&
                         node->ammo_remaining() < node->ammo_capacity();
        }
        if( reloadable ) {
            reloadables.push_back( item_location( const_cast<Character &>( who ),
                                                  const_cast<item *>( node ) ) );
        }
        return VisitResponse::SKIP;
    } );
    return reloadables;
}
References item::is_gun(), item::is_holster(), item::magazine_compatible(), SKIP, and visitable< T >::visit_items().
Referenced by avatar_action::reload_weapon().
fine_detail_vision_mod() [1/2]
float character_funcs::fine_detail_vision_mod (const Character & who)
Calculates multiplier for the time taken to perform tasks that require detail vision (reading, crafting, etc.).
Parameters
who Character to check for
pos Check remote spot as if the character were standing there
Returns
A value from 1.0 (unimpeded vision) to 11.0 (totally blind).
Examples of produced values: 1.0 is LIGHT_AMBIENT_LIT or brighter 4.0 is a dark clear night, barely bright enough for reading and crafting 6.0 is LIGHT_AMBIENT_DIM 7.3 is LIGHT_AMBIENT_MINIMAL, a dark cloudy night, unlit indoors 11.0 is zero light or blindness
Definition at line 146 of file character_functions.cpp.
{
    return fine_detail_vision_mod( who, who.pos() );
}
References fine_detail_vision_mod(), and Character::pos().
Referenced by can_see_fine_details(), draw_env_compact(), draw_lighting_classic(), draw_loc_labels(), fine_detail_vision_mod(), avatar::get_book_reader(), iuse::gun_repair(), lighting_crafting_speed_multiplier(), avatar::read(), activity_handlers::repair_item_do_turn(), npc::time_to_read(), avatar::time_to_read(), and sew_advanced_actor::use().
fine_detail_vision_mod() [2/2]
float character_funcs::fine_detail_vision_mod (const Character & who, const tripoint & p)
Definition at line 151 of file character_functions.cpp.
{
    // PER_SLIME_OK implies you can get enough eyes around the bile
    // that you can generally see.  There still will be the haze, but
    // it's annoying rather than limiting.
    if( who.is_blind() ||
        ( ( who.has_effect( effect_boomered ) || who.has_effect( effect_darkness ) ) &&
          !who.has_trait( trait_PER_SLIME_OK ) ) ) {
        return 11.0;
    }
    // Scale linearly as light level approaches LIGHT_AMBIENT_LIT.
    // If we're actually a source of light, assume we can direct it where we need it.
    // Therefore give a hefty bonus relative to ambient light.
    float own_light = std::max( 1.0f, LIGHT_AMBIENT_LIT - who.active_light() - 2.0f );
    // Same calculation as above, but with a result 3 lower.
    float ambient_light = std::max( 1.0f, LIGHT_AMBIENT_LIT - get_map().ambient_light_at( p ) + 1.0f );
    return std::min( own_light, ambient_light );
}
References Character::active_light(), effect_boomered, effect_darkness, get_map(), Creature::has_effect(), Character::has_trait(), Character::is_blind(), LIGHT_AMBIENT_LIT, and trait_PER_SLIME_OK.
fmt_wielded_weapon()
std::string character_funcs::fmt_wielded_weapon (const Character & who)
Get the formatted name of the currently wielded item (if any) with current gun mode (if gun)
Definition at line 410 of file character_functions.cpp.
{
    if( !who.is_armed() ) {
        return _( "fists" );
    }
    const item &weapon = who.weapon;
    if( weapon.is_gun() ) {
        std::string str = string_format( "(%d) [%s] %s", weapon.ammo_remaining(),
                                         weapon.gun_current_mode().tname(), weapon.type_name() );
        // Is either the base item or at least one auxiliary gunmod loaded (includes empty magazines)
        bool base = weapon.ammo_capacity() > 0 && !weapon.has_flag( "RELOAD_AND_SHOOT" );
        const auto mods = weapon.gunmods();
        bool aux = std::any_of( mods.begin(), mods.end(), [&]( const item * e ) {
            return e->is_gun() && e->ammo_capacity() > 0 && !e->has_flag( "RELOAD_AND_SHOOT" );
        } );
        if( base || aux ) {
            for( auto e : mods ) {
                if( e->is_gun() && e->ammo_capacity() > 0 && !e->has_flag( "RELOAD_AND_SHOOT" ) ) {
                    str += " (" + std::to_string( e->ammo_remaining() );
                    if( e->magazine_integral() ) {
                        str += "/" + std::to_string( e->ammo_capacity() );
                    }
                    str += ")";
                }
            }
        }
        return str;
    } else if( weapon.is_container() && weapon.contents.num_item_stacks() == 1 ) {
        return string_format( "%s (%d)", weapon.tname(),
                              weapon.contents.front().charges );
    } else {
        return weapon.tname();
    }
}
References _, item::ammo_capacity(), item::ammo_remaining(), item::charges, item::contents, item_contents::front(), item::gun_current_mode(), item::gunmods(), item::has_flag(), Character::is_armed(), item::is_container(), item::is_gun(), item::magazine_integral(), item_contents::num_item_stacks(), string_format(), gun_mode::tname(), item::tname(), to_string(), item::type_name(), and Character::weapon.
Referenced by Character::can_wield(), draw_env_compact(), draw_weapon_classic(), draw_weapon_classic_alt(), and draw_weapon_labels().
get_ammo_items()
std::vector< const item * > character_funcs::get_ammo_items (const Character & who, const ammotype & at)
Returns character's items that are ammo and have the matching ammo type.
Definition at line 1043 of file character_functions.cpp.
{
    return who.items_with( [at]( const item & it ) {
        return it.ammo_type() == at;
    } );
}
References item::ammo_type(), and visitable< T >::items_with().
Referenced by item::color_in_inventory(), and npc::decide_needs().
get_book_fun_for()
int character_funcs::get_book_fun_for (const Character & ch, const item & book)
Returns enjoyability value of a book for given character.
Definition at line 117 of file character_functions.cpp.
{
    int fun_bonus = book.type->book->fun;
    if( !book.is_book() ) {
        debugmsg( "called avatar::book_fun_for with non-book" );
        return 0;
    }
    // If you don't have a problem with eating humans, To Serve Man becomes rewarding
    if( ( ch.has_trait( trait_CANNIBAL ) ||
          ch.has_trait( trait_PSYCHOPATH ) ||
          ch.has_trait( trait_SAPIOVORE ) ) &&
        book.typeId() == itype_cookbook_human ) {
        fun_bonus = std::abs( fun_bonus );
    } else if( ch.has_trait( trait_SPIRITUAL ) && book.has_flag( "INSPIRATIONAL" ) ) {
        fun_bonus = std::abs( fun_bonus * 3 );
    }
    if( ch.has_trait( trait_LOVES_BOOKS ) ) {
        fun_bonus++;
    }
    if( fun_bonus > 1 && book.get_chapters() > 0 && book.get_remaining_chapters( ch ) == 0 ) {
        fun_bonus /= 2;
    }
    return fun_bonus;
}
References itype::book, debugmsg, item::get_chapters(), item::get_remaining_chapters(), item::has_flag(), Character::has_trait(), item::is_book(), itype_cookbook_human, trait_CANNIBAL, trait_LOVES_BOOKS, trait_PSYCHOPATH, trait_SAPIOVORE, trait_SPIRITUAL, item::type, and item::typeId().
Referenced by item::book_info(), avatar::do_read(), npc::finish_read(), is_fun_to_read(), avatar::read(), read_inventory_preset::read_inventory_preset(), and skim_book_msg().
get_crafting_helpers()
std::vector< npc * > character_funcs::get_crafting_helpers (const Character & who, int max = -1)
Returns nearby NPCs ready and willing to help with crafting or some other manual task.
Parameters
who Character to be assited
max If set, limits number of helpers to that value
Definition at line 654 of file character_functions.cpp.
{
    if( max == 0 || !who.is_avatar() ) {
        // TODO: NPCs assisting other NPCs
        return {};
    }
    int n = 0;
    return g->get_npcs_if( [&]( const npc & guy ) {
        // NPCs can help craft if awake, taking orders, within pickup range and have clear path
        if( max > 0 && n >= max ) {
            return false;
        }
        bool ok = !guy.in_sleep_state() && guy.is_obeying( who ) &&
                  rl_dist( guy.pos(), who.pos() ) < PICKUP_RANGE &&
                  get_map().clear_path( who.pos(), guy.pos(), PICKUP_RANGE, 1, 100 );
        if( ok ) {
            n += 1;
        }
        return ok;
    } );
}
References g, get_map(), Character::in_sleep_state(), Creature::is_avatar(), npc::is_obeying(), ok, PICKUP_RANGE, Character::pos(), and rl_dist().
Referenced by construction::adjusted_time(), player::available_assistant_count(), game::butcher(), butcher_time_to_cut(), player::can_make(), veh_interact::can_remove_part(), iuse::chop_logs(), iuse::chop_tree(), iuse::clear_rubble(), complete_construction(), complete_craft(), iuse::craft(), player::craft_skill_gain(), player::crafting_success_roll(), iuse::dig(), iuse::dig_channel(), veh_interact::do_remove(), veh_interact::do_repair(), iuse::fill_pit(), activity_handlers::fill_pit_finish(), dig_activity_actor::finish(), avatar::get_book_reader(), get_lift_strength_with_helpers(), iuse::jackhammer(), activity_handlers::jackhammer_finish(), iuse::pickaxe(), activity_handlers::pickaxe_finish(), avatar::read(), scale_time(), select_crafting_recipe(), veh_interact::update_part_requirements(), and wash_items().
get_lift_strength()
int character_funcs::get_lift_strength (const Character & who)
Returns Character lift strength unassisted by helpers or equipment.
Definition at line 676 of file character_functions.cpp.
{
    int str = who.get_str();
    if( who.mounted_creature ) {
        auto mons = who.mounted_creature.get();
        str = mons->mech_str_addition() == 0 ? str : mons->mech_str_addition();
    }
    if( who.has_trait( trait_STRONGBACK ) ) {
        str *= 1.35;
    } else if( who.has_trait( trait_BADBACK ) ) {
        str /= 1.35;
    }
    return str;
}
References Character::get_str(), Character::has_trait(), Character::mounted_creature, trait_BADBACK, and trait_STRONGBACK.
Referenced by get_lift_strength_with_helpers().
get_lift_strength_with_helpers()
int character_funcs::get_lift_strength_with_helpers (const Character & who)
Returns Character lift strength without equipment including bonus from nearby helpers.
Definition at line 691 of file character_functions.cpp.
{
    int result = get_lift_strength( who );
    const std::vector<npc *> helpers = get_crafting_helpers( who );
    for( const npc *np : helpers ) {
        result += get_lift_strength( *np );
    }
    return result;
}
References get_crafting_helpers(), and get_lift_strength().
Referenced by can_lift_with_helpers().
is_bp_immune_to()
bool character_funcs::is_bp_immune_to (const Character & who, body_part bp, damage_unit dam)
Check if character's body part is immune to given damage.
Note that this refers only to reduction of hp on the body part, it does not account for clothing damage, pain, status effects, etc.
Parameters
who Character to check for
bp Body part to perform the check on
dam Damage unit to check for
Returns
true if given damage can not reduce hp of given body part
Definition at line 637 of file character_functions.cpp.
{
    if( who.has_trait( trait_DEBUG_NODMG ) || who.is_immune_damage( dam.type ) ) {
        return true;
    }
    who.passive_absorb_hit( convert_bp( bp ).id(), dam );
    for( const item &cloth : who.worn ) {
        if( cloth.get_coverage() == 100 && cloth.covers( bp ) ) {
            cloth.mitigate_damage( dam );
        }
    }
    return dam.amount <= 0;
}
References damage_unit::amount, convert_bp(), item::covers(), item::get_coverage(), Character::has_trait(), Character::is_immune_damage(), item::mitigate_damage(), Character::passive_absorb_hit(), trait_DEBUG_NODMG, damage_unit::type, and Character::worn.
Referenced by game::get_dangerous_tile().
is_fun_to_read()
bool character_funcs::is_fun_to_read (const Character & ch, const item & book)
Returns whether character considers it fun to read the book.
Definition at line 103 of file character_functions.cpp.
{
    // If you don't have a problem with eating humans, To Serve Man becomes rewarding
    if( ( ch.has_trait( trait_CANNIBAL ) || ch.has_trait( trait_PSYCHOPATH ) ||
          ch.has_trait( trait_SAPIOVORE ) ) &&
        book.typeId() == itype_cookbook_human ) {
        return true;
    } else if( ch.has_trait( trait_SPIRITUAL ) && book.has_flag( "INSPIRATIONAL" ) ) {
        return true;
    } else {
        return get_book_fun_for( ch, book ) > 0;
    }
}
References get_book_fun_for(), item::has_flag(), Character::has_trait(), itype_cookbook_human, trait_CANNIBAL, trait_PSYCHOPATH, trait_SAPIOVORE, trait_SPIRITUAL, and item::typeId().
Referenced by avatar::get_book_reader(), avatar::read(), npc::time_to_read(), and avatar::time_to_read().
list_ammo()
bool character_funcs::list_ammo (const Character & who, const item & base, std::vector< item_reload_option > & ammo_list, bool include_empty_mags, bool include_potential)
List ammo suitable for given item.
Parameters
who Character who looks for ammo
base Item to select ammo for
[out] ammo_list Output
include_empty_mags Whether to include empty magazines
include_potential Include ammo that can potentially be used, but not right now
Definition at line 706 of file character_functions.cpp.
{
    auto opts = base.gunmods();
    opts.push_back( &base );
    if( base.magazine_current() ) {
        opts.push_back( base.magazine_current() );
    }
    for( const auto mod : base.gunmods() ) {
        if( mod->magazine_current() ) {
            opts.push_back( mod->magazine_current() );
        }
    }
    bool ammo_match_found = false;
    int ammo_search_range = who.is_mounted() ? -1 : 1;
    for( const auto e : opts ) {
        for( const item_location &ammo : find_ammo_items_or_mags( who, *e, include_empty_mags,
                ammo_search_range ) ) {
            // don't try to unload frozen liquids
            if( ammo->is_watertight_container() && ammo->contents_made_of( SOLID ) ) {
                continue;
            }
            auto id = ( ammo->is_ammo_container() || ammo->is_container() )
                      ? ammo->contents.front().typeId()
                      : ammo->typeId();
            const bool can_reload_with = e->can_reload_with( id );
            if( can_reload_with ) {
                // Speedloaders require an empty target.
                if( include_potential || !ammo->has_flag( "SPEEDLOADER" ) || e->ammo_remaining() < 1 ) {
                    ammo_match_found = true;
                }
            }
            if( ( include_potential && can_reload_with )
                || who.as_player()->can_reload( *e, id ) || e->has_flag( "RELOAD_AND_SHOOT" ) ) {
                ammo_list.emplace_back( who.as_player(), e, &base, ammo );
            }
        }
    }
    return ammo_match_found;
}
References Creature::as_player(), Character::can_reload(), find_ammo_items_or_mags(), item::gunmods(), Character::is_mounted(), item::magazine_current(), and SOLID.
Referenced by favorite_ammo_or_select(), and select_ammo().
normalize()
void character_funcs::normalize (Character & who)
Reset Character's weapon and body state (limb hp, stamina, active martial art)
Definition at line 486 of file character_functions.cpp.
{
    who.martial_arts_data->reset_style();
    who.weapon = item();
    who.set_body();
    who.recalc_hp();
    who.temp_cur.fill( BODYTEMP_NORM );
    who.temp_conv.fill( BODYTEMP_NORM );
    who.set_stamina( who.get_stamina_max() );
}
References BODYTEMP_NORM, Character::get_stamina_max(), Character::martial_arts_data, Character::recalc_hp(), Creature::set_body(), Character::set_stamina(), Character::temp_conv, Character::temp_cur, and Character::weapon.
Referenced by veh_interact::complete_vehicle(), debug_menu::debug(), vehicle::immediate_path(), tutorial_game::init(), tileray::init(), vehicle_movement::is_on_rails(), vehicle::merge_rackable_vehicle(), npc::npc(), vehicle_movement::process_movement_on_rails(), target_ui::recalc_aim_turning_penalty(), vehicle::remove_carried_vehicle(), and vehicle::turn().
pick_safe_adjacent_tile()
cata::optional< tripoint > character_funcs::pick_safe_adjacent_tile (const Character & who)
Returns an unoccupied, safe adjacent point.
Definition at line 605 of file character_functions.cpp.
{
    std::vector<tripoint> ret;
    int dangerous_fields = 0;
    map &here = get_map();
    for( const tripoint &p : here.points_in_radius( who.pos(), 1 ) ) {
        if( p == who.pos() ) {
            // Don't consider player position
            continue;
        }
        const trap &curtrap = here.tr_at( p );
        if( g->critter_at( p ) == nullptr && here.passable( p ) &&
            ( curtrap.is_null() || curtrap.is_benign() ) ) {
            // Only consider tile if unoccupied, passable and has no traps
            dangerous_fields = 0;
            auto &tmpfld = here.field_at( p );
            for( auto &fld : tmpfld ) {
                const field_entry &cur = fld.second;
                if( cur.is_dangerous() ) {
                    dangerous_fields++;
                }
            }
            if( dangerous_fields == 0 && ! get_map().obstructed_by_vehicle_rotation( who.pos(), p ) ) {
                ret.push_back( p );
            }
        }
    }
    return random_entry( ret );
}
References map::field_at(), g, get_map(), trap::is_benign(), field_entry::is_dangerous(), trap::is_null(), map::passable(), map::points_in_radius(), Character::pos(), random_entry(), cata::hash64_detail::ret, and map::tr_at().
Referenced by try_uncanny_dodge(), and Character::vomit().
rate_sleep_spot()
int character_funcs::rate_sleep_spot (const Character & who, const tripoint & p)
Rate point's ability to serve as a bed.
Takes all mutations, fatigue and stimulants into account.
Definition at line 313 of file character_functions.cpp.
{
    const int current_stim = who.get_stim();
    const comfort_response_t comfort_info = base_comfort_value( who, p );
    if( comfort_info.aid != nullptr ) {
        who.add_msg_if_player( m_info, _( "You use your %s for comfort." ), comfort_info.aid->tname() );
    }
    int sleepy = static_cast<int>( comfort_info.level );
    bool watersleep = who.has_trait( trait_WATERSLEEP );
    if( who.has_addiction( add_type::SLEEP ) ) {
        sleepy -= 4;
    }
    if( who.has_trait( trait_INSOMNIA ) ) {
        // 12.5 points is the difference between "tired" and "dead tired"
        sleepy -= 12;
    }
    if( who.has_trait( trait_EASYSLEEPER ) ) {
        // Low fatigue (being rested) has a much stronger effect than high fatigue
        // so it's OK for the value to be that much higher
        sleepy += 40;
    }
    if( who.has_active_bionic( bio_soporific ) ) {
        sleepy += 30;
    }
    if( who.has_trait( trait_EASYSLEEPER2 ) ) {
        // At this point, the only limit to sleep is tiredness
        sleepy += 100;
    }
    if( watersleep && get_map().has_flag_ter( "SWIMMABLE", p ) ) {
        sleepy += 10; //comfy water!
    }
    if( who.get_fatigue() < fatigue_levels::tired + 1 ) {
        sleepy -= static_cast<int>( ( fatigue_levels::tired + 1 - who.get_fatigue() ) / 4 );
    } else {
        sleepy += static_cast<int>( ( who.get_fatigue() - fatigue_levels::tired + 1 ) / 16 );
    }
    if( current_stim > 0 || !who.has_trait( trait_INSOMNIA ) ) {
        sleepy -= 2 * current_stim;
    } else {
        // Make it harder for insomniac to get around the trait
        sleepy -= current_stim;
    }
    return sleepy;
}
References _, Creature::add_msg_if_player(), character_funcs::comfort_response_t::aid, base_comfort_value(), bio_soporific, Character::get_fatigue(), get_map(), Character::get_stim(), Character::has_active_bionic(), Character::has_addiction(), map::has_flag_ter(), Character::has_trait(), character_funcs::comfort_response_t::level, m_info, SLEEP, tired, item::tname(), trait_EASYSLEEPER, trait_EASYSLEEPER2, trait_INSOMNIA, and trait_WATERSLEEP.
Referenced by npc::execute_action(), and roll_can_sleep().
roll_can_sleep()
bool character_funcs::roll_can_sleep (Character & who)
Checked each turn during "lying_down", returns true if the avatar falls asleep.
Definition at line 363 of file character_functions.cpp.
{
    if( who.has_effect( effect_meth ) ) {
        // Sleep ain't happening until that meth wears off completely.
        return false;
    }
    // Since there's a bit of randomness to falling asleep, we want to
    // prevent exploiting this if can_sleep() gets called over and over.
    // Only actually check if we can fall asleep no more frequently than
    // every 30 minutes.  We're assuming that if we return true, we'll
    // immediately be falling asleep after that.
    //
    // Also if player debug menu'd time backwards this breaks, just do the
    // check anyway, this will reset the timer if 'dur' is negative.
    const time_point now = calendar::turn;
    const time_duration dur = now - who.last_sleep_check;
    if( dur >= 0_turns && dur < 30_minutes ) {
        return false;
    }
    who.last_sleep_check = now;
    int sleepy = character_funcs::rate_sleep_spot( who, who.pos() );
    sleepy += rng( -8, 8 );
    bool result = sleepy > 0;
    if( who.has_active_bionic( bio_soporific ) ) {
        if( who.bio_soporific_powered_at_last_sleep_check && !who.has_power() ) {
            who.add_msg_if_player( m_bad, _( "Your soporific inducer runs out of power!" ) );
        } else if( !who.bio_soporific_powered_at_last_sleep_check && who.has_power() ) {
            who.add_msg_if_player( m_good, _( "Your soporific inducer starts back up." ) );
        }
        who.bio_soporific_powered_at_last_sleep_check = who.has_power();
    }
    return result;
}
References _, Creature::add_msg_if_player(), bio_soporific, Character::bio_soporific_powered_at_last_sleep_check, effect_meth, Character::has_active_bionic(), Creature::has_effect(), Character::has_power(), Character::last_sleep_check, m_bad, m_good, Character::pos(), rate_sleep_spot(), rng(), and calendar::turn.
Referenced by Character::hardcoded_effects(), and activity_handlers::try_sleep_do_turn().
search_surroundings()
void character_funcs::search_surroundings (Character & who)
Search surrounding squares for traps (and maybe other things in the future).
Definition at line 1056 of file character_turn.cpp.
{
    if( who.controlling_vehicle ) {
        return;
    }
    const map &here = get_map();
    // Search for traps in a larger area than before because this is the only
    // way we can "find" traps that aren't marked as visible.
    // Detection formula takes care of likelihood of seeing within this range.
    for( const tripoint &tp : here.points_in_radius( who.pos(), 5 ) ) {
        const trap &tr = here.tr_at( tp );
        if( tr.is_null() || tp == who.pos() ) {
            continue;
        }
        if( who.has_active_bionic( bio_ground_sonar ) && !who.knows_trap( tp ) &&
            ( tr.loadid == tr_beartrap_buried ||
              tr.loadid == tr_landmine_buried || tr.loadid == tr_sinkhole ) ) {
            const std::string direction = direction_name( direction_from( who.pos(), tp ) );
            who.add_msg_if_player( m_warning, _( "Your ground sonar detected a %1$s to the %2$s!" ),
                                   tr.name(), direction );
            who.add_known_trap( tp, tr );
        }
        if( !who.sees( tp ) ) {
            continue;
        }
        if( tr.is_always_invisible() || tr.can_see( tp, who ) ) {
            // Already seen, or can never be seen
            continue;
        }
        // Chance to detect traps we haven't yet seen.
        if( tr.detect_trap( tp, who ) ) {
            if( tr.get_visibility() > 0 ) {
                // Only bug player about traps that aren't trivial to spot.
                const std::string direction = direction_name(
                                                  direction_from( who.pos(), tp ) );
                who.add_msg_if_player( _( "You've spotted a %1$s to the %2$s!" ),
                                       tr.name(), direction );
            }
            who.add_known_trap( tp, tr );
        }
    }
}
References _, Character::add_known_trap(), Creature::add_msg_if_player(), bio_ground_sonar, trap::can_see(), Character::controlling_vehicle, trap::detect_trap(), direction_from(), direction_name(), get_map(), trap::get_visibility(), Character::has_active_bionic(), trap::is_always_invisible(), trap::is_null(), Character::knows_trap(), trap::loadid, m_warning, trap::name(), map::points_in_radius(), Character::pos(), Character::sees(), map::tr_at(), tr_beartrap_buried, tr_landmine_buried, and tr_sinkhole.
Referenced by do_pause(), and game::place_player().
select_ammo() [1/2]
item_reload_option character_funcs::select_ammo (const Character & who, const item & base, bool prompt = false, bool include_empty_mags = true, bool include_potential = false)
Select suitable ammo with which to reload the item.
Parameters
who Character who looks for ammo
base Item to select ammo for
prompt Force display of the menu even if only one choice
include_empty_mags Allow selection of empty magazines
include_potential Include ammo that can potentially be used, but not right now
Definition at line 987 of file character_functions.cpp.
{
    std::vector<item_reload_option> ammo_list;
    const bool ammo_match_found = list_ammo( who, base, ammo_list, include_empty_mags,
                                  include_potential );
    if( ammo_list.empty() ) {
        if( !who.is_npc() ) {
            if( !base.is_magazine() && !base.magazine_integral() && !base.magazine_current() ) {
                who.add_msg_if_player( m_info, _( "You need a compatible magazine to reload the %s!" ),
                                       base.tname() );
            } else if( ammo_match_found ) {
                who.add_msg_if_player( m_info, _( "Nothing to reload!" ) );
            } else {
                std::string name;
                if( base.ammo_data() ) {
                    name = base.ammo_data()->nname( 1 );
                } else if( base.is_watertight_container() ) {
                    name = base.is_container_empty() ? "liquid" : base.contents.front().tname();
                } else {
                    name = enumerate_as_string( base.ammo_types().begin(),
                    base.ammo_types().end(), []( const ammotype & at ) {
                        return at->name();
                    }, enumeration_conjunction::none );
                }
                who.add_msg_if_player( m_info, _( "You don't have any %s to reload your %s!" ),
                                       name, base.tname() );
            }
        }
        return item_reload_option();
    }
    // sort in order of move cost (ascending), then remaining ammo (descending) with empty magazines always last
    std::stable_sort( ammo_list.begin(), ammo_list.end(), []( const item_reload_option & lhs,
    const item_reload_option & rhs ) {
        return lhs.ammo->ammo_remaining() > rhs.ammo->ammo_remaining();
    } );
    std::stable_sort( ammo_list.begin(), ammo_list.end(), []( const item_reload_option & lhs,
    const item_reload_option & rhs ) {
        return lhs.moves() < rhs.moves();
    } );
    std::stable_sort( ammo_list.begin(), ammo_list.end(), []( const item_reload_option & lhs,
    const item_reload_option & rhs ) {
        return ( lhs.ammo->ammo_remaining() != 0 ) > ( rhs.ammo->ammo_remaining() != 0 );
    } );
    if( !prompt && ammo_list.size() == 1 ) {
        // unconditionally suppress the prompt if there's only one option
        return ammo_list[ 0 ];
    }
    return select_ammo( who, base, std::move( ammo_list ) );
}
References _, Creature::add_msg_if_player(), item::ammo_data(), item::ammo_types(), item::contents, enumerate_as_string(), item_contents::front(), item::is_container_empty(), item::is_magazine(), Creature::is_npc(), item::is_watertight_container(), list_ammo(), m_info, item::magazine_current(), item::magazine_integral(), avatar_action::move(), om_direction::name(), itype::nname(), none, pickup::prompt, select_ammo(), and item::tname().
Referenced by select_ammo().
select_ammo() [2/2]
item_reload_option character_funcs::select_ammo (const Character & who, const item & base, std::vector< item_reload_option > opts)
Select ammo from the provided options.
Definition at line 750 of file character_functions.cpp.
{
    if( opts.empty() ) {
        who.add_msg_if_player( m_info, _( "Never mind." ) );
        return item_reload_option();
    }
    if( who.is_npc() ) {
        return opts[ 0 ];
    }
    uilist menu;
    menu.text = string_format( base.is_watertight_container() ? _( "Refill %s" ) :
                               base.has_flag( "RELOAD_AND_SHOOT" ) ? _( "Select ammo for %s" ) : _( "Reload %s" ),
                               base.tname() );
    // Construct item names
    std::vector<std::string> names;
    std::transform( opts.begin(), opts.end(),
    std::back_inserter( names ), [&]( const item_reload_option & e ) {
        if( e.ammo->is_magazine() && e.ammo->ammo_data() ) {
            if( e.ammo->ammo_current() == itype_battery ) {
                // This battery ammo is not a real object that can be recovered but pseudo-object that represents charge
                //~ battery storage (charges)
                return string_format( pgettext( "magazine", "%1$s (%2$d)" ), e.ammo->type_name(),
                                      e.ammo->ammo_remaining() );
            } else {
                //~ magazine with ammo (count)
                return string_format( pgettext( "magazine", "%1$s with %2$s (%3$d)" ), e.ammo->type_name(),
                                      e.ammo->ammo_data()->nname( e.ammo->ammo_remaining() ), e.ammo->ammo_remaining() );
            }
        } else if( e.ammo->is_watertight_container() ||
                   ( e.ammo->is_ammo_container() && who.is_worn( *e.ammo ) ) ) {
            // worn ammo containers should be named by their contents with their location also updated below
            return e.ammo->contents.front().display_name();
        } else {
            const_cast<item_location &>( who.ammo_location ).make_dirty();
            return ( who.ammo_location && who.ammo_location == e.ammo ? "* " : "" ) + e.ammo->display_name();
        }
    } );
    // Get location descriptions
    std::vector<std::string> where;
    std::transform( opts.begin(), opts.end(),
    std::back_inserter( where ), [&]( const item_reload_option & e ) {
        bool is_ammo_container = e.ammo->is_ammo_container();
        if( is_ammo_container || e.ammo->is_container() ) {
            if( is_ammo_container && who.is_worn( *e.ammo ) ) {
                return e.ammo->type_name();
            }
            return string_format( _( "%s, %s" ), e.ammo->type_name(), e.ammo.describe( who.as_player() ) );
        }
        return e.ammo.describe( who.as_player() );
    } );
    // Pads elements to match longest member and return length
    auto pad = []( std::vector<std::string> &vec, int n, int t ) -> int {
        for( const auto &e : vec )
        {
            n = std::max( n, utf8_width( e, true ) + t );
        }
        for( auto &e : vec )
        {
            e += std::string( n - utf8_width( e, true ), ' ' );
        }
        return n;
    };
    // Pad the first column including 4 trailing spaces
    int w = pad( names, utf8_width( menu.text, true ), 6 );
    menu.text.insert( 0, 2, ' ' ); // add space for UI hotkeys
    menu.text += std::string( w + 2 - utf8_width( menu.text, true ), ' ' );
    // Pad the location similarly (excludes leading "| " and trailing " ")
    w = pad( where, utf8_width( _( "| Location " ) ) - 3, 6 );
    menu.text += _( "| Location " );
    menu.text += std::string( w + 3 - utf8_width( _( "| Location " ) ), ' ' );
    menu.text += _( "| Amount  " );
    menu.text += _( "| Moves   " );
    // We only show ammo statistics for guns and magazines
    if( base.is_gun() || base.is_magazine() ) {
        menu.text += _( "| Damage   | Pierce   " );
    }
    auto draw_row = [&]( int idx ) {
        const auto &sel = opts[ idx ];
        std::string row = string_format( "%s| %s |", names[ idx ], where[ idx ] );
        row += string_format( ( sel.ammo->is_ammo() ||
                                sel.ammo->is_ammo_container() ) ? " %-7d |" : "         |", sel.qty() );
        row += string_format( " %-7d ", sel.moves() );
        if( base.is_gun() || base.is_magazine() ) {
            const itype *ammo = sel.ammo->is_ammo_container() ? sel.ammo->contents.front().ammo_data() :
                                sel.ammo->ammo_data();
            if( ammo ) {
                const damage_instance &dam = ammo->ammo->damage;
                const damage_unit &du = dam.damage_units.front();
                if( du.damage_multiplier != 1.0f ) {
                    float dam_amt = du.amount;
                    row += string_format( "| %-3d*%3d%% ", static_cast<int>( dam_amt ),
                                          clamp( static_cast<int>( du.damage_multiplier * 100 ), 0, 999 ) );
                } else {
                    float dam_amt = dam.total_damage();
                    row += string_format( "| %-8d ", static_cast<int>( dam_amt ) );
                }
                if( du.res_mult != 1.0f ) {
                    row += string_format( "| %-3d/%3d%%",
                                          static_cast<int>( du.res_pen ), static_cast<int>( 100 * du.res_mult ) );
                } else {
                    row += string_format( "| %-8d", static_cast<int>( du.res_pen ) );
                }
            } else {
                row += "|          |          ";
            }
        }
        return row;
    };
    const ammotype base_ammotype( base.ammo_default().str() );
    itype_id last = uistate.lastreload[ base_ammotype ];
    // We keep the last key so that pressing the key twice (for example, r-r for reload)
    // will always pick the first option on the list.
    int last_key = inp_mngr.get_previously_pressed_key();
    bool last_key_bound = false;
    // This is the entry that has out default
    int default_to = 0;
    // If last_key is RETURN, don't use that to override hotkey
    if( last_key == '\n' ) {
        last_key_bound = true;
        default_to = -1;
    }
    for( auto i = 0; i < static_cast<int>( opts.size() ); ++i ) {
        const item &ammo = opts[ i ].ammo->is_ammo_container() ? opts[ i ].ammo->contents.front() :
                           *opts[ i ].ammo;
        char hotkey = -1;
        if( who.has_item( ammo ) ) {
            // if ammo in player possession and either it or any container has a valid invlet use this
            if( ammo.invlet ) {
                hotkey = ammo.invlet;
            } else {
                for( const auto obj : who.parents( ammo ) ) {
                    if( obj->invlet ) {
                        hotkey = obj->invlet;
                        break;
                    }
                }
            }
        }
        if( last == ammo.typeId() ) {
            if( !last_key_bound && hotkey == -1 ) {
                // If this is the first occurrence of the most recently used type of ammo and the hotkey
                // was not already set above then set it to the keypress that opened this prompt
                hotkey = last_key;
                last_key_bound = true;
            }
            if( !last_key_bound ) {
                // Pressing the last key defaults to the first entry of compatible type
                default_to = i;
                last_key_bound = true;
            }
        }
        if( hotkey == last_key ) {
            last_key_bound = true;
            // Prevent the default from being used: key is bound to something already
            default_to = -1;
        }
        menu.addentry( i, true, hotkey, draw_row( i ) );
    }
    struct reload_callback : public uilist_callback {
        public:
            std::vector<item_reload_option> &opts;
            const std::function<std::string( int )> draw_row;
            int last_key;
            const int default_to;
            const bool can_partial_reload;
            reload_callback( std::vector<item_reload_option> &_opts,
                             std::function<std::string( int )> _draw_row,
                             int _last_key, int _default_to, bool _can_partial_reload ) :
                opts( _opts ), draw_row( _draw_row ),
                last_key( _last_key ), default_to( _default_to ),
                can_partial_reload( _can_partial_reload )
            {}
            bool key( const input_context &, const input_event &event, int idx, uilist *menu ) override {
                auto cur_key = event.get_first_input();
                if( default_to != -1 && cur_key == last_key ) {
                    // Select the first entry on the list
                    menu->ret = default_to;
                    return true;
                }
                if( idx < 0 || idx >= static_cast<int>( opts.size() ) ) {
                    return false;
                }
                auto &sel = opts[ idx ];
                switch( cur_key ) {
                    case KEY_LEFT:
                        if( can_partial_reload ) {
                            sel.qty( sel.qty() - 1 );
                            menu->entries[ idx ].txt = draw_row( idx );
                        }
                        return true;
                    case KEY_RIGHT:
                        if( can_partial_reload ) {
                            sel.qty( sel.qty() + 1 );
                            menu->entries[ idx ].txt = draw_row( idx );
                        }
                        return true;
                }
                return false;
            }
    } cb( opts, draw_row, last_key, default_to, !base.has_flag( "RELOAD_ONE" ) );
    menu.callback = &cb;
    menu.query();
    if( menu.ret < 0 || static_cast<size_t>( menu.ret ) >= opts.size() ) {
        who.add_msg_if_player( m_info, _( "Never mind." ) );
        return item_reload_option();
    }
    const item_location &sel = opts[ menu.ret ].ammo;
    uistate.lastreload[ ammotype( base.ammo_default().str() ) ] = sel->is_ammo_container() ?
            sel->contents.front().typeId() :
            sel->typeId();
    return opts[ menu.ret ];
}
References _, Creature::add_msg_if_player(), item_reload_option::ammo, item::has_flag(), item::is_ammo_container(), Creature::is_npc(), item::is_watertight_container(), Character::is_worn(), m_info, Name::names, string_format(), uilist::text, item::tname(), and iexamine::transform().
Referenced by npc::do_reload(), favorite_ammo_or_select(), npc::find_reloadable(), npc::find_usable_ammo(), vehicle::interact_with(), aim_activity_actor::load_RAS_weapon(), ranged::prompt_select_default_ammo_for(), bandolier_actor::reload(), and ammobelt_actor::use().
show_skill_capped_notice()
void character_funcs::show_skill_capped_notice (const Character & who, const skill_id & id)
This shows warning to the player that their current activity will not give them xp.
Definition at line 1221 of file character_functions.cpp.
{
    if( !who.is_avatar() ) {
        return;
    }
    const SkillLevel &level = who.get_skill_level_object( id );
    const Skill &skill = id.obj();
    std::string skill_name = skill.name();
    int curLevel = level.level();
    add_msg( m_info, _( "This task is too simple to train your %s beyond %d." ),
             skill_name, curLevel );
}
References _, add_msg(), Character::get_skill_level_object(), Creature::is_avatar(), SkillLevel::level(), m_info, and Skill::name().
Referenced by Character::practice(), and player::start_craft().
siphon()
void character_funcs::siphon (Character & ch, vehicle & veh, const itype_id & desired_liquid)
Siphons fuel (if available) from the specified vehicle into container or similar via game::handle_liquid.
May start a character activity.
Definition at line 83 of file character_functions.cpp.
{
    if( !ch.is_avatar() ) {
        // TODO: implement for NPCs
        debugmsg( "Siphoning not implemented for NPCs." );
        return;
    }
    auto qty = veh.fuel_left( desired_liquid );
    if( qty <= 0 ) {
        ch.add_msg_if_player( m_bad, _( "There is not enough %s left to siphon it." ),
                              item::nname( desired_liquid ) );
        return;
    }
    item liquid( desired_liquid, calendar::turn, qty );
    if( liquid_handler::handle_liquid( liquid, nullptr, 1, nullptr, &veh ) ) {
        veh.drain( desired_liquid, qty - liquid.charges );
    }
}
References _, Creature::add_msg_if_player(), item::charges, debugmsg, vehicle::drain(), vehicle::fuel_left(), liquid_handler::handle_liquid(), Creature::is_avatar(), m_bad, item::nname(), and calendar::turn.
Referenced by vehicle::interact_with().
store_in_container()
void character_funcs::store_in_container (Character & who, item & container, item & put, bool penalties, int base_cost)
Stores an item inside another consuming moves proportional to weapon skill and volume.
Parameters
who Character doing the storing
container Container in which to store the item
put Item to add to the container
penalties Whether item volume and temporary effects (e.g. GRABBED, DOWNED) should be considered
base_cost Cost due to storage type
Definition at line 499 of file character_functions.cpp.
{
    who.moves -= who.item_store_cost( put, container, penalties, base_cost );
    container.put_in( who.i_rem( &put ) );
    who.reset_encumbrance();
}
References Character::i_rem(), Character::item_store_cost(), Creature::moves, item::put_in(), and Character::reset_encumbrance().
Referenced by holster_actor::store().
try_uncanny_dodge()
bool character_funcs::try_uncanny_dodge (Character & who)
Try to execute an uncanny dodge bionic ability.
Parameters
who Character doing the dodging
Definition at line 578 of file character_functions.cpp.
{
    const units::energy trigger_cost = bio_uncanny_dodge->power_trigger;
    if( who.get_power_level() < trigger_cost || !who.has_active_bionic( bio_uncanny_dodge ) ) {
        return false;
    }
    who.mod_power_level( -trigger_cost );
    bool is_u = who.is_avatar();
    bool seen = is_u || get_player_character().sees( who );
    cata::optional<tripoint> adjacent = pick_safe_adjacent_tile( who );
    if( adjacent ) {
        if( is_u ) {
            add_msg( _( "Time seems to slow down and you instinctively dodge!" ) );
        } else if( seen ) {
            add_msg( _( "%s dodges so fast!" ), who.disp_name() );
        }
        return true;
    } else {
        if( is_u ) {
            add_msg( _( "You try to dodge but there's no room!" ) );
        } else if( seen ) {
            add_msg( _( "%s tries to dodge but there's no room!" ), who.disp_name() );
        }
        return false;
    }
}
References _, add_msg(), bio_uncanny_dodge, Character::disp_name(), get_player_character(), Character::get_power_level(), Character::has_active_bionic(), Creature::is_avatar(), Character::mod_power_level(), pick_safe_adjacent_tile(), bionic_data::power_trigger, and Character::sees().
Referenced by Character::uncanny_dodge().
try_wield_contents()
bool character_funcs::try_wield_contents (Character & who, item & container, item * internal_item, bool penalties, int base_cost)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
Parameters
who Character doing the wielding
container Container containing the item to be wielded
internal_item Reference to contained item to wield
penalties Whether item volume and temporary effects (e.g. GRABBED, DOWNED) should be considered
base_cost Cost due to storage type
Pistol decreases time taken to draw pistols from holsters Smg decreases time taken to draw smgs from holsters Rifle decreases time taken to draw rifles from holsters Shotgun decreases time taken to draw shotguns from holsters Launcher decreases time taken to draw launchers from holsters Stabbing decreases time taken to draw stabbing weapons from sheathes Cutting decreases time taken to draw cutting weapons from scabbards Bashing decreases time taken to draw bashing weapons from holsters
Definition at line 506 of file character_functions.cpp.
{
    // if index not specified and container has multiple items then ask the player to choose one
    if( internal_item == nullptr ) {
        std::vector<std::string> opts;
        std::list<item *> container_contents = container.contents.all_items_top();
        std::transform( container_contents.begin(), container_contents.end(),
        std::back_inserter( opts ), []( const item * elem ) {
            return elem->display_name();
        } );
        if( opts.size() > 1 ) {
            int pos = uilist( _( "Wield what?" ), opts );
            if( pos < 0 ) {
                return false;
            }
            internal_item = *std::next( container_contents.begin(), pos );
        } else {
            internal_item = &container.contents.front();
        }
    }
    if( !container.has_item( *internal_item ) ) {
        debugmsg( "Tried to wield non-existent item from container (player::wield_contents)" );
        return false;
    }
    const ret_val<bool> ret = who.as_player()->can_wield( *internal_item );
    if( !ret.success() ) {
        who.add_msg_if_player( m_info, "%s", ret.c_str() );
        return false;
    }
    int mv = 0;
    if( who.is_armed() ) {
        if( !who.as_player()->unwield() ) {
            return false;
        }
        who.inv.unsort();
    }
    who.weapon = std::move( *internal_item );
    container.remove_item( *internal_item );
    container.on_contents_changed();
    item &weapon = who.weapon;
    who.inv.update_invlet( weapon );
    who.inv.update_cache_with_item( weapon );
    who.last_item = weapon.typeId();
    /**
     * @EFFECT_PISTOL decreases time taken to draw pistols from holsters
     * @EFFECT_SMG decreases time taken to draw smgs from holsters
     * @EFFECT_RIFLE decreases time taken to draw rifles from holsters
     * @EFFECT_SHOTGUN decreases time taken to draw shotguns from holsters
     * @EFFECT_LAUNCHER decreases time taken to draw launchers from holsters
     * @EFFECT_STABBING decreases time taken to draw stabbing weapons from sheathes
     * @EFFECT_CUTTING decreases time taken to draw cutting weapons from scabbards
     * @EFFECT_BASHING decreases time taken to draw bashing weapons from holsters
     */
    int lvl = who.get_skill_level( weapon.is_gun() ? weapon.gun_skill() : weapon.melee_skill() );
    mv += who.item_handling_cost( weapon, penalties, base_cost ) / ( ( lvl + 10.0f ) / 10.0f );
    who.moves -= mv;
    weapon.on_wield( *who.as_player(), mv );
    return true;
}
References _, Creature::add_msg_if_player(), item_contents::all_items_top(), Creature::as_player(), Character::can_wield(), item::contents, debugmsg, item_contents::front(), Character::get_skill_level(), item::gun_skill(), visitable< T >::has_item(), Character::inv, Character::is_armed(), item::is_gun(), Character::item_handling_cost(), Character::last_item, m_info, item::melee_skill(), avatar_action::move(), Creature::moves, item::on_contents_changed(), item::on_wield(), visitable< T >::remove_item(), cata::hash64_detail::ret, iexamine::transform(), item::typeId(), inventory::unsort(), Character::unwield(), inventory::update_cache_with_item(), inventory::update_invlet(), and Character::weapon.
Referenced by holster_actor::use().
update_body_wetness()
void character_funcs::update_body_wetness (Character & who, const w_point & weather)
Maintains body wetness and handles the rate at which the player dries.
Definition at line 892 of file character_turn.cpp.
{
    // Average number of turns to go from completely soaked to fully dry
    // assuming average temperature and humidity
    constexpr time_duration average_drying = 2_hours;
    // A modifier on drying time
    double delay = 1.0;
    // Weather slows down drying
    delay += ( ( weather.humidity - 66 ) - ( units::to_fahrenheit( weather.temperature ) - 65 ) ) / 100;
    delay = std::max( 0.1, delay );
    // Fur/slime retains moisture
    if( who.has_trait( trait_LIGHTFUR ) ||
        who.has_trait( trait_FUR ) ||
        who.has_trait( trait_FELINE_FUR ) ||
        who.has_trait( trait_LUPINE_FUR ) ||
        who.has_trait( trait_CHITIN_FUR ) ||
        who.has_trait( trait_CHITIN_FUR2 ) ||
        who.has_trait( trait_CHITIN_FUR3 ) ) {
        delay = delay * 6 / 5;
    }
    if( who.has_trait( trait_URSINE_FUR ) || who.has_trait( trait_SLIMY ) ) {
        delay *= 1.5;
    }
    if( !x_in_y( 1, to_turns<int>( average_drying * delay / 100.0 ) ) ) {
        // No drying this turn
        return;
    }
    // Now per-body-part stuff
    // To make drying uniform, make just one roll and reuse it
    const int drying_roll = rng( 1, 80 );
    for( const body_part bp : all_body_parts ) {
        if( who.body_wetness[bp] == 0 ) {
            continue;
        }
        // This is to normalize drying times
        int drying_chance = who.drench_capacity[bp];
        // Body temperature affects duration of wetness
        // Note: Using temp_conv rather than temp_cur, to better approximate environment
        if( who.temp_conv[bp] >= BODYTEMP_SCORCHING ) {
            drying_chance *= 2;
        } else if( who.temp_conv[bp] >= BODYTEMP_VERY_HOT ) {
            drying_chance = drying_chance * 3 / 2;
        } else if( who.temp_conv[bp] >= BODYTEMP_HOT ) {
            drying_chance = drying_chance * 4 / 3;
        } else if( who.temp_conv[bp] > BODYTEMP_COLD ) {
            // Comfortable, doesn't need any changes
        } else {
            // Evaporation doesn't change that much at lower temp
            drying_chance = drying_chance * 3 / 4;
        }
        if( drying_chance < 1 ) {
            drying_chance = 1;
        }
        // TODO: Make evaporation reduce body heat
        if( drying_chance >= drying_roll ) {
            who.body_wetness[bp] -= 1;
            if( who.body_wetness[bp] < 0 ) {
                who.body_wetness[bp] = 0;
            }
        }
    }
    // TODO: Make clothing slow down drying
}
References all_body_parts, Character::body_wetness, BODYTEMP_COLD, BODYTEMP_HOT, BODYTEMP_SCORCHING, BODYTEMP_VERY_HOT, Character::drench_capacity, Character::has_trait(), rng(), Character::temp_conv, units::to_fahrenheit(), trait_CHITIN_FUR, trait_CHITIN_FUR2, trait_CHITIN_FUR3, trait_FELINE_FUR, trait_FUR, trait_LIGHTFUR, trait_LUPINE_FUR, trait_SLIMY, trait_URSINE_FUR, and x_in_y().
Referenced by game::do_turn().
update_mental_focus()
void character_funcs::update_mental_focus (Character & who)
Uses calc_focus_change to update the player's current focus.
Definition at line 1099 of file character_turn.cpp.
{
    who.focus_pool += character_effects::calc_focus_change( who );
}
References character_effects::calc_focus_change(), and Character::focus_pool.
Referenced by Character::reset_stats().
Variable Documentation
FINE_VISION_PERFECT
constexpr float character_funcs::FINE_VISION_PERFECT = 1.0f constexpr
Value for perfect fine detail vision.
Definition at line 44 of file character_functions.h.
Referenced by avatar::read().
FINE_VISION_THRESHOLD
constexpr float character_funcs::FINE_VISION_THRESHOLD = 4.0f constexpr
Threshold for fine detail vision mod.
Definition at line 42 of file character_functions.h.
Referenced by can_see_fine_details(), and lighting_crafting_speed_multiplier().