Cataclysm BN: character_display Namespace Reference
character_display Namespace Reference
Functions
void print_encumbrance (const catacurses::window &win, const Character &ch, int line=-1, const item *selected_clothing=nullptr)
Formats and prints encumbrance info to specified window.
void disp_info (Character &ch)
Handles and displays detailed character info for the '@' screen.
void upgrade_stat_prompt (avatar &you, const character_stat &stat)
Handles upgrade of avatar stats.
Function Documentation
disp_info()
void character_display::disp_info (Character & ch)
Handles and displays detailed character info for the '@' screen.
Parameters
ch Character to display info for. Has to be non-const reference to allow toggling skills and upgrading stats for stats-through-x mods.
Definition at line 1063 of file character_display.cpp.
{
    std::vector<std::pair<std::string, std::string>> effect_name_and_text;
    for( auto &elem : ch.get_all_effects() ) {
        for( auto &_effect_it : elem.second ) {
            const std::string tmp = _effect_it.second.disp_name();
            if( _effect_it.second.is_removed() || tmp.empty() ) {
                continue;
            }
            effect_name_and_text.push_back( { tmp, _effect_it.second.disp_desc() } );
        }
    }
    if( ch.get_perceived_pain() > 0 ) {
        const auto ppen = character_effects::get_pain_penalty( ch );
        std::string pain_text;
        const auto add_if = [&]( const int amount, const char *const name ) {
            if( amount > 0 ) {
                pain_text += string_format( name, amount ) + "   ";
            }
        };
        add_if( ppen.strength, _( "Strength -%d" ) );
        add_if( ppen.dexterity, _( "Dexterity -%d" ) );
        add_if( ppen.intelligence, _( "Intelligence -%d" ) );
        add_if( ppen.perception, _( "Perception -%d" ) );
        add_if( ppen.speed, _( "Speed -%d %%" ) );
        effect_name_and_text.push_back( { _( "Pain" ), pain_text } );
    }
    const float bmi = ch.bmi();
    if( bmi < character_weight_category::underweight ) {
        std::string starvation_name;
        std::string starvation_text;
        if( bmi < character_weight_category::emaciated ) {
            starvation_name = _( "Severely Malnourished" );
            starvation_text =
                _( "Your body is severely weakened by starvation.  You might die if you don't start eating regular meals!\n\n" );
        } else {
            starvation_name = _( "Malnourished" );
            starvation_text =
                _( "Your body is weakened by starvation.  Only time and regular meals will help you recover.\n\n" );
        }
        if( bmi < character_weight_category::underweight ) {
            const float str_penalty = 1.0f - ( ( bmi - 13.0f ) / 3.0f );
            starvation_text += std::string( _( "Strength" ) ) + " -" + string_format( "%2.0f%%\n",
                               str_penalty * 100.0f );
            starvation_text += std::string( _( "Dexterity" ) ) + " -" + string_format( "%2.0f%%\n",
                               str_penalty * 50.0f );
            starvation_text += std::string( _( "Intelligence" ) ) + " -" + string_format( "%2.0f%%",
                               str_penalty * 50.0f );
        }
        effect_name_and_text.push_back( { starvation_name, starvation_text } );
    }
    if( ( ch.has_trait( trait_id( "TROGLO" ) ) && g->is_in_sunlight( ch.pos() ) &&
          get_weather().weather_id->sun_intensity >= sun_intensity_type::high ) ||
        ( ch.has_trait( trait_id( "TROGLO2" ) ) && g->is_in_sunlight( ch.pos() ) &&
          get_weather().weather_id->sun_intensity < sun_intensity_type::high )
      ) {
        effect_name_and_text.push_back( { _( "In Sunlight" ),
                                          _( "The sunlight irritates you.\n"
                                             "Strength - 1;    Dexterity - 1;    Intelligence - 1;    Perception - 1" )
                                        } );
    } else if( ch.has_trait( trait_id( "TROGLO2" ) ) && g->is_in_sunlight( ch.pos() ) ) {
        effect_name_and_text.push_back( { _( "In Sunlight" ),
                                          _( "The sunlight irritates you badly.\n"
                                             "Strength - 2;    Dexterity - 2;    Intelligence - 2;    Perception - 2" )
                                        } );
    } else if( ch.has_trait( trait_id( "TROGLO3" ) ) && g->is_in_sunlight( ch.pos() ) ) {
        effect_name_and_text.push_back( { _( "In Sunlight" ),
                                          _( "The sunlight irritates you terribly.\n"
                                             "Strength - 4;    Dexterity - 4;    Intelligence - 4;    Perception - 4" )
                                        } );
    }
    for( auto &elem : ch.addictions ) {
        if( elem.sated < 0_turns && elem.intensity >= MIN_ADDICTION_LEVEL ) {
            effect_name_and_text.push_back( { addiction_name( elem ), addiction_text( elem ) } );
        }
    }
    const unsigned int effect_win_size_y = 1 + static_cast<unsigned>( effect_name_and_text.size() );
    std::vector<trait_id> traitslist = ch.get_mutations( false );
    std::sort( traitslist.begin(), traitslist.end(), trait_display_sort );
    const unsigned int trait_win_size_y_max = 1 + static_cast<unsigned>( traitslist.size() );
    std::vector<bionic> bionicslist = *ch.my_bionics;
    const unsigned int bionics_win_size_y_max = 2 + bionicslist.size();
    const std::vector<const Skill *> player_skill = Skill::get_skills_sorted_by(
    [&]( const Skill & a, const Skill & b ) {
        skill_displayType_id type_a = a.display_category();
        skill_displayType_id type_b = b.display_category();
        return localized_compare( std::make_pair( type_a, a.name() ),
                                  std::make_pair( type_b, b.name() ) );
    } );
    std::vector<HeaderSkill> skillslist;
    skill_displayType_id prev_type = skill_displayType_id::NULL_ID();
    for( auto &s : player_skill ) {
        if( s->display_category() != prev_type ) {
            prev_type = s->display_category();
            skillslist.emplace_back( s, true );
        }
        skillslist.emplace_back( s, false );
    }
    const unsigned int skill_win_size_y_max = 1 + skillslist.size();
    const unsigned int info_win_size_y = 6;
    const unsigned int grid_width = 26;
    const unsigned int grid_height = 9;
    const unsigned int infooffsetytop = grid_height + 2;
    unsigned int infooffsetybottom = infooffsetytop + 1 + info_win_size_y;
    const auto calculate_trait_and_bionic_height = [&]() {
        const unsigned int maxy = static_cast<unsigned>( TERMY );
        unsigned int trait_win_size_y = trait_win_size_y_max;
        unsigned int bionics_win_size_y = bionics_win_size_y_max;
        if( ( bionics_win_size_y_max + 1 + trait_win_size_y_max + infooffsetybottom ) > maxy ) {
            // maximum space for either window if they're both the same size
            unsigned max_shared_y = ( maxy - infooffsetybottom - 1 ) / 2;
            if( std::min( bionics_win_size_y_max, trait_win_size_y_max ) > max_shared_y ) {
                // both are larger than the shared size
                bionics_win_size_y = max_shared_y;
                trait_win_size_y = maxy - infooffsetybottom - 1 - bionics_win_size_y;
            } else if( trait_win_size_y_max <= max_shared_y ) {
                // trait window is less than the shared size, so give space to bionics
                bionics_win_size_y = maxy - infooffsetybottom - 1 - trait_win_size_y_max;
            } else {
                // bionics window is less than the shared size
                trait_win_size_y = maxy - infooffsetybottom - 1 - bionics_win_size_y;
            }
        }
        return std::make_pair( trait_win_size_y, bionics_win_size_y );
    };
    // Print name and header
    // Post-humanity trumps your pre-Cataclysm life
    // Unless you have a custom profession.
    std::string race;
    if( ch.custom_profession.empty() ) {
        if( ch.crossed_threshold() ) {
            for( const trait_id &mut : ch.get_mutations() ) {
                const mutation_branch &mdata = mut.obj();
                if( mdata.threshold ) {
                    race = mdata.name();
                    break;
                }
            }
        }
    }
    input_context ctxt( "PLAYER_INFO" );
    ctxt.register_updown();
    ctxt.register_action( "NEXT_TAB", to_translation( "Cycle to next category" ) );
    ctxt.register_action( "PREV_TAB", to_translation( "Cycle to previous category" ) );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "CONFIRM", to_translation( "Toggle skill training / Upgrade stat" ) );
    ctxt.register_action( "CHANGE_PROFESSION_NAME", to_translation( "Change profession name" ) );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    std::map<std::string, int> speed_effects;
    for( auto &elem : ch.get_all_effects() ) {
        for( std::pair<const bodypart_str_id, effect> &_effect_it : elem.second ) {
            effect &it = _effect_it.second;
            bool reduced = ch.resists_effect( it );
            int move_adjust = it.get_mod( "SPEED", reduced );
            if( move_adjust != 0 ) {
                const std::string dis_text = it.get_speed_name();
                speed_effects[dis_text] += move_adjust;
            }
        }
    }
    border_helper borders;
    player_display_tab curtab = player_display_tab::stats;
    unsigned int line = 0;
    catacurses::window w_tip;
    ui_adaptor ui_tip;
    ui_tip.on_screen_resize( [&]( ui_adaptor & ui_tip ) {
        w_tip = catacurses::newwin( 1, FULL_SCREEN_WIDTH + 1, point_zero );
        ui_tip.position_from_window( w_tip );
    } );
    ui_tip.mark_resize();
    ui_tip.on_redraw( [&]( const ui_adaptor & ) {
        draw_tip( w_tip, ch, race, ctxt );
    } );
    catacurses::window w_stats;
    catacurses::window w_stats_border;
    border_helper::border_info &border_stats = borders.add_border();
    ui_adaptor ui_stats;
    ui_stats.on_screen_resize( [&]( ui_adaptor & ui_stats ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        w_stats = catacurses::newwin( grid_height, grid_width, point( 0, 1 ) );
        // Every grid draws the bottom and right borders. The top and left borders
        // are either not displayed or drawn by another grid.
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        w_stats_border = catacurses::newwin( grid_height + 1, grid_width + 1, point( 0, 1 ) );
        // But we need to specify the full border for border_helper to calculate the
        // border connection.
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        border_stats.set( point( -1, 0 ), point( grid_width + 2, grid_height + 2 ) );
        ui_stats.position_from_window( w_stats_border );
    } );
    ui_stats.mark_resize();
    ui_stats.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_stats_border );
        wnoutrefresh( w_stats_border );
        draw_stats_tab( w_stats, ch, line, curtab );
    } );
    unsigned int trait_win_size_y = 0;
    catacurses::window w_traits;
    catacurses::window w_traits_border;
    border_helper::border_info &border_traits = borders.add_border();
    ui_adaptor ui_traits;
    ui_traits.on_screen_resize( [&]( ui_adaptor & ui_traits ) {
        trait_win_size_y = calculate_trait_and_bionic_height().first;
        w_traits = catacurses::newwin( trait_win_size_y, grid_width,
                                       point( grid_width + 1, infooffsetybottom ) );
        w_traits_border = catacurses::newwin( trait_win_size_y + 1, grid_width + 1,
                                              point( grid_width + 1, infooffsetybottom ) );
        border_traits.set( point( grid_width, infooffsetybottom - 1 ),
                           point( grid_width + 2, trait_win_size_y + 2 ) );
        ui_traits.position_from_window( w_traits_border );
    } );
    ui_traits.mark_resize();
    ui_traits.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_traits_border );
        wnoutrefresh( w_traits_border );
        draw_traits_tab( w_traits, line, curtab, traitslist, trait_win_size_y );
    } );
    unsigned int bionics_win_size_y = 0;
    catacurses::window w_bionics;
    catacurses::window w_bionics_border;
    border_helper::border_info &border_bionics = borders.add_border();
    ui_adaptor ui_bionics;
    ui_bionics.on_screen_resize( [&]( ui_adaptor & ui_bionics ) {
        bionics_win_size_y = calculate_trait_and_bionic_height().second;
        w_bionics = catacurses::newwin( bionics_win_size_y, grid_width,
                                        point( grid_width + 1,
                                               infooffsetybottom + trait_win_size_y + 1 ) );
        w_bionics_border = catacurses::newwin( bionics_win_size_y + 1, grid_width + 1,
                                               point( grid_width + 1,
                                                       infooffsetybottom + trait_win_size_y + 1 ) );
        border_bionics.set( point( grid_width, infooffsetybottom + trait_win_size_y ),
                            point( grid_width + 2, bionics_win_size_y + 2 ) );
        ui_bionics.position_from_window( w_bionics_border );
    } );
    ui_bionics.mark_resize();
    ui_bionics.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_bionics_border );
        wnoutrefresh( w_bionics_border );
        draw_bionics_tab( w_bionics, ch, line, curtab, bionicslist, bionics_win_size_y );
    } );
    catacurses::window w_encumb;
    catacurses::window w_encumb_border;
    border_helper::border_info &border_encumb = borders.add_border();
    ui_adaptor ui_encumb;
    ui_encumb.on_screen_resize( [&]( ui_adaptor & ui_encumb ) {
        w_encumb = catacurses::newwin( grid_height, grid_width, point( grid_width + 1, 1 ) );
        w_encumb_border = catacurses::newwin( grid_height + 1, grid_width + 1, point( grid_width + 1, 1 ) );
        border_encumb.set( point( grid_width, 0 ), point( grid_width + 2, grid_height + 2 ) );
        ui_encumb.position_from_window( w_encumb_border );
    } );
    ui_encumb.mark_resize();
    ui_encumb.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_encumb_border );
        wnoutrefresh( w_encumb_border );
        draw_encumbrance_tab( w_encumb, ch, line, curtab );
    } );
    catacurses::window w_effects;
    catacurses::window w_effects_border;
    border_helper::border_info &border_effects = borders.add_border();
    ui_adaptor ui_effects;
    ui_effects.on_screen_resize( [&]( ui_adaptor & ui_effects ) {
        w_effects = catacurses::newwin( effect_win_size_y, grid_width,
                                        point( grid_width * 2 + 2, infooffsetybottom ) );
        w_effects_border = catacurses::newwin( effect_win_size_y + 1, grid_width + 1,
                                               point( grid_width * 2 + 2, infooffsetybottom ) );
        border_effects.set( point( grid_width * 2 + 1, infooffsetybottom - 1 ),
                            point( grid_width + 2, effect_win_size_y + 2 ) );
        ui_effects.position_from_window( w_effects_border );
    } );
    ui_effects.mark_resize();
    ui_effects.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_effects_border );
        wnoutrefresh( w_effects_border );
        draw_effects_tab( w_effects, line, curtab, effect_name_and_text, effect_win_size_y );
    } );
    catacurses::window w_speed;
    catacurses::window w_speed_border;
    border_helper::border_info &border_speed = borders.add_border();
    ui_adaptor ui_speed;
    ui_speed.on_screen_resize( [&]( ui_adaptor & ui_speed ) {
        w_speed = catacurses::newwin( grid_height, grid_width, point( grid_width * 2 + 2, 1 ) );
        w_speed_border = catacurses::newwin( grid_height + 1, grid_width + 1,
                                             point( grid_width * 2 + 2, 1 ) );
        border_speed.set( point( grid_width * 2 + 1, 0 ),
                          point( grid_width + 2, grid_height + 2 ) );
        ui_speed.position_from_window( w_speed_border );
    } );
    ui_speed.mark_resize();
    ui_speed.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_speed_border );
        wnoutrefresh( w_speed_border );
        draw_speed_tab( w_speed, ch, speed_effects );
    } );
    unsigned int skill_win_size_y = 0;
    catacurses::window w_skills;
    catacurses::window w_skills_border;
    border_helper::border_info &border_skills = borders.add_border();
    ui_adaptor ui_skills;
    ui_skills.on_screen_resize( [&]( ui_adaptor & ui_skills ) {
        const unsigned int maxy = static_cast<unsigned>( TERMY );
        skill_win_size_y = skill_win_size_y_max;
        if( skill_win_size_y + infooffsetybottom > maxy ) {
            skill_win_size_y = maxy - infooffsetybottom;
        }
        w_skills = catacurses::newwin( skill_win_size_y, grid_width,
                                       point( 0, infooffsetybottom ) );
        w_skills_border = catacurses::newwin( skill_win_size_y + 1, grid_width + 1,
                                              point( 0, infooffsetybottom ) );
        border_skills.set( point( -1, infooffsetybottom - 1 ),
                           point( grid_width + 2, skill_win_size_y + 2 ) );
        ui_skills.position_from_window( w_skills_border );
    } );
    ui_skills.mark_resize();
    ui_skills.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_skills_border );
        wnoutrefresh( w_skills_border );
        draw_skills_tab( w_skills, ch, line, curtab, skillslist, skill_win_size_y );
    } );
    catacurses::window w_info;
    catacurses::window w_info_border;
    border_helper::border_info &border_info = borders.add_border();
    ui_adaptor ui_info;
    ui_info.on_screen_resize( [&]( ui_adaptor & ui_info ) {
        w_info = catacurses::newwin( info_win_size_y, FULL_SCREEN_WIDTH,
                                     point( 0, infooffsetytop ) );
        w_info_border = catacurses::newwin( info_win_size_y + 1, FULL_SCREEN_WIDTH + 1,
                                            point( 0, infooffsetytop ) );
        border_info.set( point( -1, infooffsetytop - 1 ),
                         point( FULL_SCREEN_WIDTH + 2, info_win_size_y + 2 ) );
        ui_info.position_from_window( w_info_border );
    } );
    ui_info.mark_resize();
    ui_info.on_redraw( [&]( const ui_adaptor & ) {
        borders.draw_border( w_info_border );
        wnoutrefresh( w_info_border );
        draw_info_window( w_info, ch, line, curtab,
                          traitslist, bionicslist, effect_name_and_text, skillslist );
    } );
    bool done = false;
    do {
        ui_manager::redraw_invalidated();
        done = handle_player_display_action( ch, line, curtab, ctxt, ui_tip, ui_info,
                                             ui_stats, ui_encumb, ui_traits, ui_bionics, ui_effects, ui_skills,
                                             traitslist, bionicslist, effect_name_and_text, skillslist );
    } while( !done );
}
References _, a, border_helper::add_border(), addiction_name(), addiction_text(), Character::addictions, b, Character::bmi(), Character::crossed_threshold(), Character::custom_profession, detail::digits::done, draw_bionics_tab(), border_helper::draw_border(), draw_effects_tab(), draw_encumbrance_tab(), draw_info_window(), draw_skills_tab(), draw_speed_tab(), draw_stats_tab(), draw_tip(), draw_traits_tab(), character_weight_category::emaciated, FULL_SCREEN_WIDTH, g, Creature::get_all_effects(), effect::get_mod(), Character::get_mutations(), character_effects::get_pain_penalty(), Character::get_perceived_pain(), Skill::get_skills_sorted_by(), effect::get_speed_name(), get_weather(), handle_player_display_action(), Character::has_trait(), high, line(), localized_compare, ui_adaptor::mark_resize(), MIN_ADDICTION_LEVEL, Character::my_bionics, mutation_branch::name(), om_direction::name(), catacurses::newwin(), string_id< SkillDisplayType >::NULL_ID(), ui_adaptor::on_redraw(), ui_adaptor::on_screen_resize(), point_zero, Character::pos(), ui_adaptor::position_from_window(), ui_manager::redraw_invalidated(), input_context::register_action(), input_context::register_updown(), Creature::resists_effect(), border_helper::border_info::set(), string_format(), TERMY, mutation_branch::threshold, to_translation(), trait_display_sort(), character_weight_category::underweight, and catacurses::wnoutrefresh().
Referenced by debug_menu::character_edit_menu(), game::handle_action(), game::handle_key_blocking_activity(), and talk_function::reveal_stats().
print_encumbrance()
void character_display::print_encumbrance (const catacurses::window & win, const Character & ch, int line = -1, const item * selected_clothing = nullptr)
Formats and prints encumbrance info to specified window.
Definition at line 96 of file character_display.cpp.
{
    // bool represents whether the part has been combined with its other half
    const std::vector<std::pair<body_part, bool>> bps = list_and_combine_bps( ch, selected_clothing );
    // width/height excluding title & scrollbar
    const int height = getmaxy( win ) - 1;
    bool draw_scrollbar = height < static_cast<int>( bps.size() );
    const int width = getmaxx( win ) - ( draw_scrollbar ? 1 : 0 );
    // index of the first printed bodypart from `bps`
    const int firstline = clamp( line - height / 2, 0, std::max( 0,
                                 static_cast<int>( bps.size() ) - height ) );
    /*** I chose to instead only display X+Y instead of X+Y=Z. More room was needed ***
     *** for displaying triple digit encumbrance, due to new encumbrance system.    ***
     *** If the player wants to see the total without having to do them maths, the  ***
     *** armor layers ui shows everything they want :-) -Davek                      ***/
    const char_encumbrance_data enc_data = ch.get_encumbrance();
    for( int i = 0; i < height; ++i ) {
        int thisline = firstline + i;
        if( thisline < 0 ) {
            continue;
        }
        if( static_cast<size_t>( thisline ) >= bps.size() ) {
            break;
        }
        const body_part bp = bps[thisline].first;
        const bool combine = bps[thisline].second;
        const encumbrance_data &e = enc_data.elems[bp];
        const bool highlighted = selected_clothing ? selected_clothing->covers( bp ) : false;
        std::string out = body_part_name_as_heading( bp, combine ? 2 : 1 );
        if( utf8_width( out ) > 7 ) {
            out = utf8_truncate( out, 7 );
        }
        // Two different highlighting schemes, highlight if the line is selected as per line being set.
        // Make the text green if this part is covered by the passed in item.
        nc_color limb_color = thisline == line ?
                              ( highlighted ? h_green : h_light_gray ) :
                              ( highlighted ? c_green : c_light_gray );
        mvwprintz( win, point( 1, 1 + i ), limb_color, "%s", out );
        // accumulated encumbrance from clothing, plus extra encumbrance from layering
        mvwprintz( win, point( 8, 1 + i ), encumb_color( e.encumbrance ), "%3d",
                   e.encumbrance - e.layer_penalty );
        // separator in low toned color
        mvwprintz( win, point( 11, 1 + i ), c_light_gray, "+" );
        // take into account the new encumbrance system for layers
        mvwprintz( win, point( 12, 1 + i ), encumb_color( e.encumbrance ), "%-3d", e.layer_penalty );
        // print warmth, tethered to right hand side of the window
        mvwprintz( win, point( width - 6, 1 + i ), ch.bodytemp_color( bp ), "(% 3d)",
                   temperature_print_rescaling( ch.temp_conv[bp] ) );
    }
    if( draw_scrollbar ) {
        scrollbar().
        offset_x( width ).
        offset_y( 1 ).
        content_size( bps.size() ).
        viewport_pos( firstline ).
        viewport_size( height ).
        scroll_to_last( false ).
        apply( win );
    }
}
References apply(), body_part_name_as_heading(), Character::bodytemp_color(), c_green, c_light_gray, clamp(), item::covers(), draw_scrollbar(), char_encumbrance_data::elems, encumb_color(), encumbrance_data::encumbrance, Character::get_encumbrance(), catacurses::getmaxx(), catacurses::getmaxy(), h_green, h_light_gray, encumbrance_data::layer_penalty, line(), list_and_combine_bps(), mvwprintz(), Character::temp_conv, temperature_print_rescaling(), utf8_truncate(), and utf8_width().
Referenced by draw_encumbrance_tab(), and show_armor_layers_ui().
upgrade_stat_prompt()
void character_display::upgrade_stat_prompt (avatar & you, const character_stat & stat)
Handles upgrade of avatar stats.
Definition at line 1443 of file character_display.cpp.
{
    const int free_points = you.free_upgrade_points();
    if( free_points <= 0 ) {
        cata::optional<int> xp_remains = you.kill_xp_for_next_point();
        if( !xp_remains ) {
            popup( _( "You've already reached maximum level." ) );
        } else {
            popup( _( "Needs %d more experience to gain next level." ), *xp_remains );
        }
        return;
    }
    std::string stat_string;
    switch( stat ) {
        case character_stat::STRENGTH:
            stat_string = _( "strength" );
            break;
        case character_stat::DEXTERITY:
            stat_string = _( "dexterity" );
            break;
        case character_stat::INTELLIGENCE:
            stat_string = _( "intelligence" );
            break;
        case character_stat::PERCEPTION:
            stat_string = _( "perception" );
            break;
        case character_stat::DUMMY_STAT:
            stat_string = _( "invalid stat" );
            debugmsg( "Tried to use invalid stat" );
            break;
        default:
            return;
    }
    if( query_yn( _( "Are you sure you want to raise %s?  %d points available." ), stat_string,
                  free_points ) ) {
        you.upgrade_stat( stat );
    }
}
References _, debugmsg, DEXTERITY, DUMMY_STAT, avatar::free_upgrade_points(), INTELLIGENCE, avatar::kill_xp_for_next_point(), PERCEPTION, popup(), query_yn(), STRENGTH, and avatar::upgrade_stat().
Referenced by handle_player_display_action().