Cataclysm BN: item_funcs Namespace Reference
item_funcs Namespace Reference
Functions
bool can_be_unloaded (const item &itm)
Returns whether given item (or one of its gunmods) can be unloaded.
Function Documentation
can_be_unloaded()
bool item_funcs::can_be_unloaded (const item & itm)
Returns whether given item (or one of its gunmods) can be unloaded.
Definition at line 10 of file item_functions.cpp.
{
    if( ( itm.is_container() || itm.is_bandolier() ) && !itm.contents.empty() &&
        itm.can_unload_liquid() ) {
        return true;
    }
    if( itm.has_flag( flag_NO_UNLOAD ) ) {
        return false;
    }
    if( itm.magazine_current() ) {
        return true;
    }
    for( const item *mod : itm.gunmods() ) {
        if( can_be_unloaded( *mod ) ) {
            return true;
        }
    }
    if( itm.ammo_types().empty() ) {
        return false;
    }
    return itm.ammo_remaining() > 0 || itm.casings_count() > 0;
}
References item::ammo_remaining(), item::ammo_types(), can_be_unloaded(), item::can_unload_liquid(), item::casings_count(), item::contents, item_contents::empty(), flag_NO_UNLOAD, item::gunmods(), item::has_flag(), item::is_bandolier(), item::is_container(), and item::magazine_current().
Referenced by can_be_unloaded(), examine_item_menu::rate_action_unload(), and avatar_action::unload().