Cataclysm BN: PATH_INFO Namespace Reference
PATH_INFO Namespace Reference
Functions
void init_base_path (std::string path)
void init_user_dir (std::string dir)
void set_standard_filenames ()
std::string autopickup ()
std::string base_colors ()
std::string base_path ()
std::string colors ()
std::string color_templates ()
std::string config_dir ()
std::string custom_colors ()
std::string datadir ()
std::string debug ()
std::string defaultsounddir ()
std::string defaulttilejson ()
std::string defaulttilepng ()
std::string fontconfig ()
std::string user_fontconfig ()
std::string fontdir ()
std::string user_fontdir ()
std::string language_defs_file ()
std::string graveyarddir ()
std::string help ()
std::string keybindings ()
std::string keybindings_vehicle ()
std::string keybindings_edit_creature ()
std::string main_menu_tips ()
std::string lastworld ()
std::string memorialdir ()
std::string moddir ()
std::string options ()
std::string panel_options ()
std::string safemode ()
std::string distraction ()
std::string savedir ()
std::string sokoban ()
std::string templatedir ()
std::string user_dir ()
std::string user_keybindings ()
std::string user_moddir ()
std::string worldoptions ()
std::string crash ()
std::string tileset_conf ()
std::string gfxdir ()
std::string user_gfx ()
std::string data_sound ()
std::string user_sound ()
std::string mods_replacements ()
std::string mods_dev_default ()
std::string mods_user_default ()
std::string soundpack_conf ()
std::string credits ()
std::string motd ()
std::string title (holiday current_holiday)
std::string names ()
void set_datadir (const std::string &datadir)
void set_config_dir (const std::string &config_dir)
void set_savedir (const std::string &savedir)
void set_memorialdir (const std::string &memorialdir)
void set_options (const std::string &options)
void set_autopickup (const std::string &autopickup)
void set_motd (const std::string &motd)
Function Documentation
autopickup()
std::string PATH_INFO::autopickup ()
Definition at line 134 of file path_info.cpp.
{
    return autopickup_value;
}
References autopickup_value.
Referenced by pickup::do_pickup(), pickup_activity_actor::do_turn(), auto_pickup::player_settings::load(), pick_one_up(), auto_pickup::player_settings::save(), and set_autopickup().
base_colors()
std::string PATH_INFO::base_colors ()
Definition at line 138 of file path_info.cpp.
{
    return config_dir_value + "base_colors.json";
}
References config_dir_value.
Referenced by color_loader< ColorType >::load().
base_path()
std::string PATH_INFO::base_path ()
Definition at line 142 of file path_info.cpp.
{
    return base_path_value;
}
References base_path_value.
Referenced by l10n_data::add_base_catalogue(), find_translated_file(), DynamicDataLoader::load_all_from_json(), DynamicDataLoader::load_object(), and translations_exists_for_lang().
color_templates()
std::string PATH_INFO::color_templates ()
Definition at line 150 of file path_info.cpp.
{
    return datadir_value + "raw/" + "color_templates/";
}
References datadir_value.
Referenced by color_manager::show_gui().
colors()
std::string PATH_INFO::colors ()
Definition at line 146 of file path_info.cpp.
{
    return datadir_value + "raw/" + "colors.json";
}
References datadir_value.
Referenced by Character::conduct_blood_analysis(), explosion_handler::do_blast(), get_bar(), color_loader< ColorType >::load(), msgtype_to_color(), and sev().
config_dir()
std::string PATH_INFO::config_dir ()
Definition at line 154 of file path_info.cpp.
{
    return config_dir_value;
}
References config_dir_value.
Referenced by main(), main_menu::opening_screen(), and set_config_dir().
crash()
std::string PATH_INFO::crash ()
Definition at line 290 of file path_info.cpp.
{
    return config_dir_value + "crash.log";
}
References config_dir_value.
credits()
std::string PATH_INFO::credits ()
Definition at line 323 of file path_info.cpp.
{
    return find_translated_file( datadir_value + "credits/", ".credits",
                                 datadir_value + "credits/" + "en.credits" );
}
References datadir_value, and find_translated_file().
Referenced by main_menu::init_strings().
custom_colors()
std::string PATH_INFO::custom_colors ()
Definition at line 158 of file path_info.cpp.
{
    return config_dir_value + "custom_colors.json";
}
References config_dir_value.
Referenced by color_manager::load_custom(), and color_manager::save_custom().
data_sound()
std::string PATH_INFO::data_sound ()
Definition at line 318 of file path_info.cpp.
{
    return datadir_value + "sound";
}
References datadir_value.
Referenced by options_manager::build_soundpacks_list().
datadir()
std::string PATH_INFO::datadir ()
Definition at line 162 of file path_info.cpp.
{
    return datadir_value;
}
References datadir_value.
Referenced by main(), and set_datadir().
debug()
std::string PATH_INFO::debug ()
Definition at line 166 of file path_info.cpp.
{
    return config_dir_value + "debug.log";
}
References config_dir_value.
Referenced by debug_error_prompt(), and setupDebug().
defaultsounddir()
std::string PATH_INFO::defaultsounddir ()
Definition at line 170 of file path_info.cpp.
{
    return datadir_value + "sound";
}
References datadir_value.
defaulttilejson()
std::string PATH_INFO::defaulttilejson ()
Definition at line 174 of file path_info.cpp.
{
    return "tile_config.json";
}
defaulttilepng()
std::string PATH_INFO::defaulttilepng ()
Definition at line 178 of file path_info.cpp.
{
    return "tinytile.png";
}
distraction()
std::string PATH_INFO::distraction ()
Definition at line 250 of file path_info.cpp.
{
    return config_dir_value + "distraction.json";
}
References config_dir_value.
Referenced by distraction_manager::distraction_manager_gui::load(), and distraction_manager::distraction_manager_gui::save().
fontconfig()
std::string PATH_INFO::fontconfig ()
Definition at line 182 of file path_info.cpp.
{
    return datadir_value + "raw/" + "fonts.json";
}
References datadir_value.
Referenced by font_loader::load().
fontdir()
std::string PATH_INFO::fontdir ()
Definition at line 190 of file path_info.cpp.
{
    return datadir_value + "font/";
}
References datadir_value.
Referenced by ensure_unifont_loaded().
gfxdir()
std::string PATH_INFO::gfxdir ()
Definition at line 314 of file path_info.cpp.
{
    return gfxdir_value;
}
References gfxdir_value.
Referenced by options_manager::build_tilesets_list().
graveyarddir()
std::string PATH_INFO::graveyarddir ()
Definition at line 202 of file path_info.cpp.
{
    return user_dir_value + "graveyard/";
}
References user_dir_value.
Referenced by game::move_save_to_graveyard().
help()
std::string PATH_INFO::help ()
Definition at line 206 of file path_info.cpp.
{
    return datadir_value + "help/" + "texts.json";
}
References datadir_value.
Referenced by help::load(), and trading_window::show_item_data().
init_base_path()
void PATH_INFO::init_base_path (std::string path)
Definition at line 39 of file path_info.cpp.
{
    if( !path.empty() ) {
        const char ch = path.back();
        if( ch != '/' && ch != '\\' ) {
            path.push_back( '/' );
        }
    }
    base_path_value = path;
}
References base_path_value.
Referenced by main().
init_user_dir()
void PATH_INFO::init_user_dir (std::string dir)
Definition at line 51 of file path_info.cpp.
{
    if( dir.empty() ) {
        const char *user_dir;
#if defined(_WIN32)
        user_dir = getenv( "LOCALAPPDATA" );
        // On Windows userdir without dot
        dir = std::string( user_dir ) + "/cataclysm-bn/";
#elif defined(MACOSX)
        user_dir = getenv( "HOME" );
        dir = std::string( user_dir ) + "/Library/Application Support/Cataclysm-BN/";
#elif defined(USE_XDG_DIR)
        if( ( user_dir = getenv( "XDG_DATA_HOME" ) ) ) {
            dir = std::string( user_dir ) + "/cataclysm-bn/";
        } else {
            user_dir = getenv( "HOME" );
            dir = std::string( user_dir ) + "/.local/share/cataclysm-bn/";
        }
#else
        user_dir = getenv( "HOME" );
        dir = std::string( user_dir ) + "/.cataclysm-bn/";
#endif
    }
    user_dir_value = dir;
}
References user_dir(), and user_dir_value.
Referenced by main().
keybindings()
std::string PATH_INFO::keybindings ()
Definition at line 210 of file path_info.cpp.
{
    return datadir_value + "raw/" + "keybindings.json";
}
References datadir_value.
Referenced by input_manager::init().
keybindings_edit_creature()
std::string PATH_INFO::keybindings_edit_creature ()
Definition at line 218 of file path_info.cpp.
{
    return datadir_value + "raw/" + "keybindings/edit_creature_effects.json";
}
References datadir_value.
Referenced by input_manager::init().
keybindings_vehicle()
std::string PATH_INFO::keybindings_vehicle ()
Definition at line 214 of file path_info.cpp.
{
    return datadir_value + "raw/" + "keybindings/vehicle.json";
}
References datadir_value.
Referenced by input_manager::init().
language_defs_file()
std::string PATH_INFO::language_defs_file ()
Definition at line 198 of file path_info.cpp.
{
    return datadir_value + "raw/" + "languages.json";
}
References datadir_value.
Referenced by init_language_system().
lastworld()
std::string PATH_INFO::lastworld ()
Definition at line 226 of file path_info.cpp.
{
    return config_dir_value + "lastworld.json";
}
References config_dir_value.
Referenced by worldfactory::load_last_world_info(), and worldfactory::save_last_world_info().
main_menu_tips()
std::string PATH_INFO::main_menu_tips ()
Definition at line 222 of file path_info.cpp.
{
    return datadir_value + "raw/" + "tips.json";
}
References datadir_value.
Referenced by get_random_tip_of_the_day().
memorialdir()
std::string PATH_INFO::memorialdir ()
Definition at line 230 of file path_info.cpp.
{
    return memorialdir_value;
}
References memorialdir_value.
Referenced by diary::export_to_md(), set_memorialdir(), and game::write_memorial_file().
moddir()
std::string PATH_INFO::moddir ()
Definition at line 234 of file path_info.cpp.
{
    return datadir_value + "mods/";
}
References datadir_value.
Referenced by mod_manager::refresh_mod_list().
mods_dev_default()
std::string PATH_INFO::mods_dev_default ()
Definition at line 302 of file path_info.cpp.
{
    return datadir_value + "mods/" + "default.json";
}
References datadir_value.
Referenced by mod_manager::refresh_mod_list().
mods_replacements()
std::string PATH_INFO::mods_replacements ()
Definition at line 298 of file path_info.cpp.
{
    return datadir_value + "mods/" + "replacements.json";
}
References datadir_value.
Referenced by mod_manager::mod_manager().
mods_user_default()
std::string PATH_INFO::mods_user_default ()
Definition at line 306 of file path_info.cpp.
{
    return config_dir_value + "default_mods.json";
}
References config_dir_value.
Referenced by mod_manager::refresh_mod_list(), and mod_manager::set_default_mods().
motd()
std::string PATH_INFO::motd ()
Definition at line 329 of file path_info.cpp.
{
    return find_translated_file( datadir_value + "motd/", ".motd", motd_value );
}
References datadir_value, find_translated_file(), and motd_value.
Referenced by main_menu::init_strings(), and set_motd().
names()
std::string PATH_INFO::names ()
Definition at line 342 of file path_info.cpp.
{
    return find_translated_file( datadir_value + "names/", ".json",
                                 datadir_value + "names/" + "en.json" );
}
References datadir_value, and find_translated_file().
Referenced by reload_names().
options()
std::string PATH_INFO::options ()
Definition at line 238 of file path_info.cpp.
{
    return options_value;
}
References options_value.
Referenced by zone_manager::add(), vehicle::add_toggle_to_opts(), iexamine::autodoc(), leap_actor::call(), can_do_activity_there(), construction_menu(), vehicle::control_electronics(), zone_manager::custom_loot_has(), fire(), iexamine::fvat_empty(), plot_options::get_descriptions(), blueprint_options::get_descriptions(), loot_options::get_descriptions(), zone_options::is_valid(), iexamine::keg(), options_manager::load(), map::random_outdoor_tile(), options_manager::save(), crafting::select_tool_component(), vehicle::set_electronics_menu_options(), set_options(), iexamine::tree_maple_tapped(), vehicle::turrets_aim_and_fire_single(), vehicle::use_controls(), and game::zones_manager().
panel_options()
std::string PATH_INFO::panel_options ()
Definition at line 242 of file path_info.cpp.
{
    return config_dir_value + "panel_options.json";
}
References config_dir_value.
Referenced by panel_manager::load(), and panel_manager::save().
safemode()
std::string PATH_INFO::safemode ()
Definition at line 246 of file path_info.cpp.
{
    return config_dir_value + "safemode.json";
}
References config_dir_value.
Referenced by safemode::load(), and safemode::save().
savedir()
std::string PATH_INFO::savedir ()
Definition at line 254 of file path_info.cpp.
{
    return savedir_value;
}
References savedir_value.
Referenced by WORLD::folder_path(), game::get_world_base_save_path(), worldfactory::init(), main(), main_menu::opening_screen(), and set_savedir().
set_autopickup()
void PATH_INFO::set_autopickup (const std::string & autopickup)
Definition at line 380 of file path_info.cpp.
{
    autopickup_value = autopickup;
}
References autopickup(), and autopickup_value.
Referenced by main().
set_config_dir()
void PATH_INFO::set_config_dir (const std::string & config_dir)
Definition at line 358 of file path_info.cpp.
{
    config_dir_value = config_dir;
    options_value = config_dir_value + "options.json";
    autopickup_value = config_dir_value + "auto_pickup.json";
}
References autopickup_value, config_dir(), config_dir_value, and options_value.
Referenced by main().
set_datadir()
void PATH_INFO::set_datadir (const std::string & datadir)
Definition at line 348 of file path_info.cpp.
{
    datadir_value = datadir;
    // Shared dirs
    gfxdir_value = datadir_value + "gfx/";
    // Shared files
    motd_value = datadir_value + "motd/" + "en.motd";
}
References datadir(), datadir_value, gfxdir_value, and motd_value.
Referenced by main().
set_memorialdir()
void PATH_INFO::set_memorialdir (const std::string & memorialdir)
Definition at line 370 of file path_info.cpp.
{
    memorialdir_value = memorialdir;
}
References memorialdir(), and memorialdir_value.
Referenced by main().
set_motd()
void PATH_INFO::set_motd (const std::string & motd)
Definition at line 385 of file path_info.cpp.
{
    motd_value = motd;
}
References motd(), and motd_value.
Referenced by main().
set_options()
void PATH_INFO::set_options (const std::string & options)
Definition at line 375 of file path_info.cpp.
{
    options_value = options;
}
References options(), and options_value.
Referenced by main().
set_savedir()
void PATH_INFO::set_savedir (const std::string & savedir)
Definition at line 365 of file path_info.cpp.
{
    savedir_value = savedir;
}
References savedir(), and savedir_value.
Referenced by main().
set_standard_filenames()
void PATH_INFO::set_standard_filenames ()
Definition at line 78 of file path_info.cpp.
{
    // Special: data_dir and gfx_dir
    if( !base_path_value.empty() ) {
#if defined(DATA_DIR_PREFIX)
        datadir_value = base_path_value + "share/cataclysm-bn/";
        gfxdir_value = datadir_value + "gfx/";
#else
        datadir_value = base_path_value + "data/";
        gfxdir_value = base_path_value + "gfx/";
#endif
    } else {
        datadir_value = "data/";
        gfxdir_value = "gfx/";
    }
    // Shared dirs
    // Shared files
    motd_value = datadir_value + "motd/" + "en.motd";
    savedir_value = user_dir_value + "save/";
    memorialdir_value = user_dir_value + "memorial/";
#if defined(USE_XDG_DIR)
    const char *user_dir;
    std::string dir;
    if( ( user_dir = getenv( "XDG_CONFIG_HOME" ) ) ) {
        dir = std::string( user_dir ) + "/cataclysm-bn/";
    } else {
        user_dir = getenv( "HOME" );
        dir = std::string( user_dir ) + "/.config/cataclysm-bn/";
    }
    config_dir_value = dir;
#else
    config_dir_value = user_dir_value + "config/";
#endif
    options_value = config_dir_value + "options.json";
    autopickup_value = config_dir_value + "auto_pickup.json";
}
References autopickup_value, base_path_value, config_dir_value, datadir_value, gfxdir_value, memorialdir_value, motd_value, options_value, savedir_value, user_dir(), and user_dir_value.
Referenced by main().
sokoban()
std::string PATH_INFO::sokoban ()
Definition at line 258 of file path_info.cpp.
{
    return datadir_value + "raw/" + "sokoban.txt";
}
References datadir_value.
Referenced by sokoban_game::start_game().
soundpack_conf()
std::string PATH_INFO::soundpack_conf ()
Definition at line 310 of file path_info.cpp.
{
    return "soundpack.txt";
}
Referenced by options_manager::load_soundpack_from().
templatedir()
std::string PATH_INFO::templatedir ()
Definition at line 262 of file path_info.cpp.
{
    return user_dir_value + "templates/";
}
References user_dir_value.
Referenced by main_menu::load_char_templates(), avatar::load_template(), main_menu::new_character_tab(), main_menu::opening_screen(), and avatar::save_template().
tileset_conf()
std::string PATH_INFO::tileset_conf ()
Definition at line 294 of file path_info.cpp.
{
    return "tileset.txt";
}
Referenced by options_manager::load_tilesets_from().
title()
std::string PATH_INFO::title (holiday current_holiday)
Definition at line 334 of file path_info.cpp.
{
    std::string theme_basepath = datadir_value + "title/";
    std::string theme_extension = ".title";
    std::string theme_fallback = theme_basepath + "en.title";
    return find_translated_file( theme_basepath, theme_extension, theme_fallback );
}
References datadir_value, and find_translated_file().
Referenced by act_vehicle_siphon(), teleporter_list::activate_teleporter(), anonymous_namespace{iexamine.cpp}::atm_menu::add_choice(), anonymous_namespace{iexamine.cpp}::atm_menu::add_info(), inventory_selector_preset::append_cell(), talk_function::basecamp_mission(), iexamine::bulletin_board(), talk_function::companion_mission(), overmap_ui::create_note(), decorate_panel(), talk_function::display_and_choose_opts(), main_menu::display_text(), draw_border(), iuse::einktabletpc(), inventory_selector_preset::get_cell_text(), trading_window::get_var_trade(), handle_action_menu(), game_menus::inv::holster(), main_menu::init_strings(), vehicle::interact_with(), inv_internal(), game::inv_map_splice(), ma_style_callback::key(), json_item_substitution::load(), popup_string(), Character::pour_into(), prompt_disassemble_in_seq(), query_for_template_name(), activity_handlers::repair_item_finish(), repeat_menu(), scrollable_text(), vehicle::select_engine(), safemode::show(), basecamp::start_crafting(), game_menus::inv::titled_filter_menu(), game_menus::inv::titled_menu(), and editmap::update_view_with_help().
user_dir()
std::string PATH_INFO::user_dir ()
Definition at line 266 of file path_info.cpp.
{
    return user_dir_value;
}
References user_dir_value.
Referenced by init_user_dir(), main(), and set_standard_filenames().
user_fontconfig()
std::string PATH_INFO::user_fontconfig ()
Definition at line 186 of file path_info.cpp.
{
    return config_dir_value + "fonts.json";
}
References config_dir_value.
Referenced by font_loader::load().
user_fontdir()
std::string PATH_INFO::user_fontdir ()
Definition at line 194 of file path_info.cpp.
{
    return user_dir_value + "font/";
}
References user_dir_value.
Referenced by main_menu::opening_screen().
user_gfx()
std::string PATH_INFO::user_gfx ()
Definition at line 270 of file path_info.cpp.
{
    return user_dir_value + "gfx/";
}
References user_dir_value.
Referenced by options_manager::build_tilesets_list(), and main_menu::opening_screen().
user_keybindings()
std::string PATH_INFO::user_keybindings ()
Definition at line 274 of file path_info.cpp.
{
    return config_dir_value + "keybindings.json";
}
References config_dir_value.
Referenced by input_manager::init(), and input_manager::save().
user_moddir()
std::string PATH_INFO::user_moddir ()
Definition at line 278 of file path_info.cpp.
{
    return user_dir_value + "mods/";
}
References user_dir_value.
Referenced by mod_manager::refresh_mod_list().
user_sound()
std::string PATH_INFO::user_sound ()
Definition at line 282 of file path_info.cpp.
{
    return user_dir_value + "sound/";
}
References user_dir_value.
Referenced by options_manager::build_soundpacks_list(), and main_menu::opening_screen().
worldoptions()
std::string PATH_INFO::worldoptions ()
Definition at line 286 of file path_info.cpp.
{
    return "worldoptions.json";
}
Referenced by worldfactory::init(), isForbidden(), WORLD::load_options(), and WORLD::save().