Cataclysm BN: cata_libintl Namespace Reference
cata_libintl Namespace Reference
Runtime localization system for Cataclysm: Bright Nights.
Classes
struct ParseRet
struct PlfNode
Plural forms AST node.
struct PlfToken
struct PlfTStream
class trans_catalogue
Translation catalogue.
class trans_library
Translation library.
Typedefs
using ParserPtr = ParseRet(*)(const PlfTStream &ts)
using u8 = uint8_t
using u32 = uint32_t
using PlfNodePtr = std::unique_ptr< PlfNode >
Enumerations
enum class PlfOp : int {
Mod , Eq , NotEq , GreaterEq ,
Greater , LessEq , Less , And ,
Or , TerCond , Literal , Variable ,
BrOpen , BrClose , TerDelim , NumOps
}
Plural forms AST node type.
Functions
ParseRet plf_get_expr (const PlfTStream &ts)
ParseRet plf_get_or (const PlfTStream &ts)
ParseRet plf_get_and (const PlfTStream &ts)
ParseRet plf_get_eq (const PlfTStream &ts)
ParseRet plf_get_cmp (const PlfTStream &ts)
ParseRet plf_get_mod (const PlfTStream &ts)
ParseRet plf_get_value (const PlfTStream &ts)
PlfNodePtr parse_plural_rules (const std::string &s)
Parse plural rules expression and build AST.
static bool plf_try_binary_op (ParseRet &left, PlfOp op, ParserPtr parser)
Variables
static const std::array< std::pair< std::string, PlfOp >, 14 > simple_tokens
constexpr u32 MO_STRING_DESCR_SIZE = 8
constexpr u8 PLF_SEPARATOR = 0
Detailed Description
Runtime localization system for Cataclysm: Bright Nights.
Implements translated string lookup within gettext MO files with full support for integer plural forms.
Key differences from GNU libintl:
Does not support translation domains
Does not support encoding conversion, operates on UTF-8 only
Does not depend on locale / environment variables
Supports loading MO files from arbitrary paths
Supports loading multiple MO files into a single "domain"
For MO file structure, see GNU gettext manual: https://www.gnu.org/software/gettext/manual/
Typedef Documentation
ParserPtr
using cata_libintl::ParserPtr = typedef ParseRet(*)(const PlfTStream &ts)
Definition at line 164 of file cata_libintl.cpp.
PlfNodePtr
using cata_libintl::PlfNodePtr = typedef std::unique_ptr<PlfNode>
Definition at line 58 of file cata_libintl.h.
u32
using cata_libintl::u32 = typedef uint32_t
Definition at line 29 of file cata_libintl.h.
u8
using cata_libintl::u8 = typedef uint8_t
Definition at line 28 of file cata_libintl.h.
Enumeration Type Documentation
PlfOp
enum class cata_libintl::PlfOp : int strong
Plural forms AST node type.
Also used for token identification during parsing.
Enumerator
Mod
Eq
NotEq
GreaterEq
Greater
LessEq
Less
And
Or
TerCond
Literal
Variable
BrOpen
BrClose
TerDelim
NumOps
Definition at line 35 of file cata_libintl.h.
                 : int {
    Mod,       // a % b
    Eq,        // a == b
    NotEq,     // a != b
    GreaterEq, // a >= b
    Greater,   // a > b
    LessEq,    // a <= b
    Less,      // a < b
    And,       // a && b
    Or,        // a || b
    TerCond,   // ?
    Literal,   // numeric literal
    Variable,  // the variable (n)
    BrOpen,    // (
    BrClose,   // )
    TerDelim,  // :
    NumOps,
};
Function Documentation
parse_plural_rules()
PlfNodePtr cata_libintl::parse_plural_rules (const std::string & s)
Parse plural rules expression and build AST.
Exceptions
std::runtime_error on failure.
Definition at line 174 of file cata_libintl.cpp.
{
    PlfTStream tokstr( &s );
    ParseRet ret = plf_get_expr( tokstr );
    if( ret.ts.has_tokens() ) {
        PlfToken tok = ret.ts.peek();
        std::string e = string_format( "unexpected token at pos %d", tok.start );
        throw std::runtime_error( e );
    }
    return std::move( ret.expr );
}
References avatar_action::move(), plf_get_expr(), cata::hash64_detail::ret, cata_libintl::PlfToken::start, and string_format().
Referenced by cata_libintl::trans_catalogue::parse_plf_header().
plf_get_and()
ParseRet cata_libintl::plf_get_and (const PlfTStream & ts)
Definition at line 227 of file cata_libintl.cpp.
{
    ParseRet ret = plf_get_eq( ts );
    plf_try_binary_op( ret, PlfOp::And, plf_get_and );
    return ret;
}
References And, plf_get_and(), plf_get_eq(), plf_try_binary_op(), and cata::hash64_detail::ret.
Referenced by plf_get_and(), and plf_get_or().
plf_get_cmp()
ParseRet cata_libintl::plf_get_cmp (const PlfTStream & ts)
Definition at line 244 of file cata_libintl.cpp.
{
    ParseRet ret = plf_get_mod( ts );
    if( plf_try_binary_op( ret, PlfOp::GreaterEq, plf_get_mod ) ) {
        return ret;
    }
    if( plf_try_binary_op( ret, PlfOp::Greater, plf_get_mod ) ) {
        return ret;
    }
    if( plf_try_binary_op( ret, PlfOp::LessEq, plf_get_mod ) ) {
        return ret;
    }
    plf_try_binary_op( ret, PlfOp::Less, plf_get_mod );
    return ret;
}
References Greater, GreaterEq, Less, LessEq, plf_get_mod(), plf_try_binary_op(), and cata::hash64_detail::ret.
Referenced by plf_get_eq().
plf_get_eq()
ParseRet cata_libintl::plf_get_eq (const PlfTStream & ts)
Definition at line 234 of file cata_libintl.cpp.
{
    ParseRet ret = plf_get_cmp( ts );
    if( plf_try_binary_op( ret, PlfOp::Eq, plf_get_cmp ) ) {
        return ret;
    }
    plf_try_binary_op( ret, PlfOp::NotEq, plf_get_cmp );
    return ret;
}
References Eq, NotEq, plf_get_cmp(), plf_try_binary_op(), and cata::hash64_detail::ret.
Referenced by plf_get_and().
plf_get_expr()
ParseRet cata_libintl::plf_get_expr (const PlfTStream & ts)
Definition at line 201 of file cata_libintl.cpp.
{
    ParseRet e1 = plf_get_or( ts );
    if( e1.ts.peek().kind != PlfOp::TerCond ) {
        return e1;
    }
    ParseRet e2 = plf_get_expr( e1.ts.cloned().skip() );
    if( e2.ts.peek().kind != PlfOp::TerDelim ) {
        PlfToken tok = e2.ts.peek();
        std::string e = string_format( "expected ternary delimiter at pos %d", tok.start );
        throw std::runtime_error( e );
    }
    ParseRet e3 = plf_get_expr( e2.ts.cloned().skip() );
    return ParseRet( std::make_unique<PlfNode>( PlfNode{
        0, std::move( e1.expr ), std::move( e2.expr ), std::move( e3.expr ), PlfOp::TerCond,
    } ),
    e3.ts );
}
References cata_libintl::PlfTStream::cloned(), cata_libintl::ParseRet::expr, cata_libintl::PlfToken::kind, avatar_action::move(), cata_libintl::PlfTStream::peek(), plf_get_expr(), plf_get_or(), cata_libintl::PlfTStream::skip(), cata_libintl::PlfToken::start, string_format(), TerCond, TerDelim, and cata_libintl::ParseRet::ts.
Referenced by parse_plural_rules(), plf_get_expr(), and plf_get_value().
plf_get_mod()
ParseRet cata_libintl::plf_get_mod (const PlfTStream & ts)
Definition at line 260 of file cata_libintl.cpp.
{
    ParseRet ret = plf_get_value( ts );
    plf_try_binary_op( ret, PlfOp::Mod, plf_get_value );
    return ret;
}
References Mod, plf_get_value(), plf_try_binary_op(), and cata::hash64_detail::ret.
Referenced by plf_get_cmp().
plf_get_or()
ParseRet cata_libintl::plf_get_or (const PlfTStream & ts)
Definition at line 220 of file cata_libintl.cpp.
{
    ParseRet ret = plf_get_and( ts );
    plf_try_binary_op( ret, PlfOp::Or, plf_get_or );
    return ret;
}
References Or, plf_get_and(), plf_get_or(), plf_try_binary_op(), and cata::hash64_detail::ret.
Referenced by plf_get_expr(), and plf_get_or().
plf_get_value()
ParseRet cata_libintl::plf_get_value (const PlfTStream & ts)
Definition at line 267 of file cata_libintl.cpp.
{
    PlfToken next = ts.peek();
    if( next.kind == PlfOp::BrOpen ) {
        // '(' expr ')'
        ParseRet e = plf_get_expr( ts.cloned().skip() );
        if( e.ts.peek().kind != PlfOp::BrClose ) {
            PlfToken tok = e.ts.peek();
            std::string e = string_format( "expected closing bracket at pos %d", tok.start );
            throw std::runtime_error( e );
        }
        return ParseRet( std::move( e.expr ), e.ts.cloned().skip() );
    } else if( next.kind == PlfOp::Literal ) {
        // number
        return ParseRet( std::make_unique<PlfNode>( PlfNode{
            next.num, nullptr, nullptr, nullptr, PlfOp::Literal,
        } ), ts.cloned().skip() );
    } else if( next.kind == PlfOp::Variable ) {
        // the variable
        return ParseRet( std::make_unique<PlfNode>( PlfNode{
            0, nullptr, nullptr, nullptr, PlfOp::Variable,
        } ), ts.cloned().skip() );
    } else {
        std::string e = string_format( "expected expression at pos %d", next.start );
        throw std::runtime_error( e );
    }
}
References BrClose, BrOpen, cata_libintl::PlfTStream::cloned(), cata_libintl::ParseRet::expr, cata_libintl::PlfToken::kind, Literal, avatar_action::move(), cata_libintl::PlfToken::num, cata_libintl::PlfTStream::peek(), plf_get_expr(), cata_libintl::PlfTStream::skip(), cata_libintl::PlfToken::start, string_format(), cata_libintl::ParseRet::ts, and Variable.
Referenced by plf_get_mod().
plf_try_binary_op()
static bool cata_libintl::plf_try_binary_op (ParseRet & left, PlfOp op, ParserPtr parser) static
Definition at line 186 of file cata_libintl.cpp.
{
    const PlfTStream &ts = left.ts;
    if( ts.peek().kind != op ) {
        // not found
        return false;
    }
    ParseRet e = parser( ts.cloned().skip() );
    left = ParseRet( std::make_unique<PlfNode>( PlfNode{
        0, std::move( left.expr ), std::move( e.expr ), nullptr, op,
    } ),
    e.ts );
    return true;
}
References cata_libintl::PlfTStream::cloned(), cata_libintl::ParseRet::expr, cata_libintl::PlfToken::kind, avatar_action::move(), cata_libintl::PlfTStream::peek(), cata_libintl::PlfTStream::skip(), and cata_libintl::ParseRet::ts.
Referenced by plf_get_and(), plf_get_cmp(), plf_get_eq(), plf_get_mod(), and plf_get_or().
Variable Documentation
MO_STRING_DESCR_SIZE
constexpr u32 cata_libintl::MO_STRING_DESCR_SIZE = 8 constexpr
Definition at line 361 of file cata_libintl.cpp.
Referenced by cata_libintl::trans_catalogue::check_nth_translation_has_plf(), cata_libintl::trans_catalogue::check_string_plurals(), cata_libintl::trans_catalogue::check_string_terminators(), cata_libintl::trans_catalogue::get_nth_orig_string(), cata_libintl::trans_catalogue::get_nth_pl_translation(), and cata_libintl::trans_catalogue::get_nth_translation().
PLF_SEPARATOR
constexpr u8 cata_libintl::PLF_SEPARATOR = 0 constexpr
Definition at line 362 of file cata_libintl.cpp.
Referenced by cata_libintl::trans_catalogue::check_nth_translation_has_plf(), cata_libintl::trans_catalogue::check_string_plurals(), and cata_libintl::trans_catalogue::get_nth_pl_translation().
simple_tokens
const std::array<std::pair<std::string, PlfOp>, 14> cata_libintl::simple_tokens static
Initial value:
= {{
        { "?", PlfOp::TerCond },
        { ":", PlfOp::TerDelim },
        { "(", PlfOp::BrOpen },
        { ")", PlfOp::BrClose },
        { "n", PlfOp::Variable },
        { "%", PlfOp::Mod },
        { "==", PlfOp::Eq },
        { "!=", PlfOp::NotEq },
        { ">=", PlfOp::GreaterEq },
        { ">", PlfOp::Greater },
        { "<=", PlfOp::LessEq },
        { "<", PlfOp::Less },
        { "&&", PlfOp::And },
        { "||", PlfOp::Or },
    }
}
Definition at line 61 of file cata_libintl.cpp.
Referenced by cata_libintl::PlfNode::debug_dump(), and cata_libintl::PlfTStream::peek_internal().