Cataclysm BN: io Namespace Reference
io Namespace Reference
Namespaces
namespace detail
The namespace contains classes that do write/read to/from JSON via either the Json classes in "json.h" or via the io function of the object to be written/read.
Classes
struct array_archive_tag
Tag that indicates the class is stored in a JSON array.
struct default_tag
Tag that indicates the default value for io should be the default value of the type itself, i.e.
struct empty_default_tag
Tag that indicates the value of the io is some kind of container and its default value is to be empty.
class InvalidEnumString
class JsonArrayInputArchive
Input archive reading data from a Json array.
class JsonArrayOutputArchive
Output archive matching the input archive JsonArrayInputArchive.
class JsonObjectInputArchive
Input archive reading data from a Json object.
class JsonObjectOutputArchive
Output archive matching the input archive JsonObjectInputArchive.
struct object_archive_tag
Tag that indicates the class is stored in a JSON object.
struct required_tag
Tag that indicates the value is required and must exists in the JSON data.
Functions
template<>
std::string enum_to_string< achievement_comparison > (achievement_comparison data)
template<>
std::string enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
template<>
std::string enum_to_string< achievement_completion > (achievement_completion data)
template<>
std::string enum_to_string< add_type > (add_type data)
template<>
std::string enum_to_string< art_effect_passive > (art_effect_passive data)
template<>
std::string enum_to_string< art_effect_active > (art_effect_active data)
template<>
std::string enum_to_string< art_charge > (art_charge data)
template<>
std::string enum_to_string< art_charge_req > (art_charge_req data)
template<>
std::string enum_to_string< bionic_ui_sort_mode > (bionic_ui_sort_mode mode)
template<>
std::string enum_to_string< side > (side data)
template<>
std::string enum_to_string< hp_part > (hp_part data)
template<>
std::string enum_to_string< cata_variant_type > (cata_variant_type type)
template<>
std::string enum_to_string< character_movemode > (character_movemode data)
template<>
std::string enum_to_string< character_stat > (character_stat data)
template<>
std::string enum_to_string< clothing_mod_type > (clothing_mod_type data)
template<>
std::string enum_to_string< computer_action > (const computer_action act)
template<>
std::string enum_to_string< computer_failure_type > (const computer_failure_type fail)
template<>
std::string enum_to_string< usage > (usage data)
template<>
std::string enum_to_string< DL > (DL x)
template<>
std::string enum_to_string< DC > (DC x)
template<>
std::string enum_to_string< distraction_type > (distraction_type data)
template<>
std::string enum_to_string< event_type > (event_type data)
template<>
std::string enum_to_string< game_message_type > (game_message_type data)
template<>
std::string enum_to_string< description_affix > (description_affix data)
template<>
std::string enum_to_string< fields::stacking_type > (fields::stacking_type data)
template<>
std::string enum_to_string< tut_lesson > (tut_lesson data)
template<>
std::string enum_to_string< phase_id > (phase_id data)
template<>
std::string enum_to_string< condition_type > (condition_type data)
template<>
std::string enum_to_string< valid_target > (valid_target data)
template<>
std::string enum_to_string< body_part > (body_part data)
template<>
std::string enum_to_string< spell_flag > (spell_flag data)
template<>
std::string enum_to_string< enchantment::has > (enchantment::has data)
template<>
std::string enum_to_string< enchantment::condition > (enchantment::condition data)
template<>
std::string enum_to_string< enchant_vals::mod > (enchant_vals::mod data)
template<>
std::string enum_to_string< map_extra_method > (map_extra_method data)
template<>
std::string enum_to_string< season_type > (season_type data)
template<>
std::string enum_to_string< mission::mission_status > (mission::mission_status data)
template<>
std::string enum_to_string< mission_origin > (mission_origin data)
template<>
std::string enum_to_string< mission_goal > (mission_goal data)
template<>
std::string enum_to_string< mon_trigger > (mon_trigger data)
template<>
std::string enum_to_string< m_flag > (m_flag data)
template<>
std::string enum_to_string< morale_subtype_t > (morale_subtype_t data)
template<>
std::string enum_to_string< mutagen_technique > (mutagen_technique data)
template<>
std::string enum_to_string< m_size > (m_size data)
template<>
std::string enum_to_string< lab_type > (lab_type data)
template<>
std::string enum_to_string< ot_match_type > (ot_match_type data)
template<>
std::string enum_to_string< relic_recharge_type > (relic_recharge_type data)
template<>
std::string enum_to_string< relic_recharge_req > (relic_recharge_req data)
template<>
std::string enum_to_string< sounds::sound_t > (sounds::sound_t data)
template<>
std::string enum_to_string< vitamin_type > (vitamin_type data)
template<>
std::string enum_to_string< precip_class > (precip_class data)
template<>
std::string enum_to_string< sun_intensity_type > (sun_intensity_type data)
template<>
std::string enum_to_string< weather_time_requirement_type > (weather_time_requirement_type data)
template<>
std::string enum_to_string< weather_sound_category > (weather_sound_category data)
Enumeration (de)serialization to/from string.
enum_to_string converts an enumeration value to a string (which can be written to JSON).
The result must be an non-empty string.
This function must be implemented somewhere for each enumeration type for which conversion is required.
Such enums must also specialize enum_traits to specify their 'last' member.
string_to_enum converts the string value back into an enumeration value. The input is expected to be one of the outputs of enum_to_string. If the given string does not match an enumeration, an InvalidEnumString is thrown.
string_to_enum<E>(enum_to_string<E>(X)) == X
must yield true for all values of the enumeration E.
template<typename E >
std::string enum_to_string (E)
template<typename E >
std::unordered_map< std::string, E > build_enum_lookup_map ()
template<typename C , typename E = typename C::mapped_type>
E string_to_enum_look_up (const C &container, const std::string &data)
template<typename E >
E string_to_enum (const std::string &data)
Function Documentation
build_enum_lookup_map()
template<typename E > std::unordered_map< std::string, E > io::build_enum_lookup_map ()
Definition at line 42 of file enum_conversions.h.
{
    static_assert( std::is_enum<E>::value, "E should be an enum type" );
    static_assert( has_enum_traits<E>::value, "enum E needs a specialization of enum_traits" );
    std::unordered_map<std::string, E> result;
    using Int = std::underlying_type_t<E>;
    constexpr Int max = static_cast<Int>( enum_traits<E>::last );
    for( Int i = 0; i < max; ++i ) {
        E e = static_cast<E>( i );
        auto inserted = result.emplace( enum_to_string( e ), e );
        if( !inserted.second ) {
            debugmsg( "repeated enum string %s (%d and %d)", inserted.first->first,
                      static_cast<Int>( inserted.first->second ), i );
            abort();
        }
    }
    return result;
}
References abort, debugmsg, and enum_to_string().
enum_to_string()
template<typename E > std::string io::enum_to_string (E)
Referenced by build_enum_lookup_map(), new_field::check(), value_constraint::check(), event_type_event_source::debug_description(), spell::enumerate_targets(), cata_variant::get(), Character::get_overlay_ids(), cata::event::get_variant(), comp_selection< CompType >::serialize(), and cata_variant_detail::convert_enum< T >::to_string().
enum_to_string< achievement::time_bound::epoch >()
template<> std::string io::enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
Definition at line 90 of file achievement.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case achievement::time_bound::epoch::cataclysm: return "cataclysm";
        case achievement::time_bound::epoch::game_start: return "game_start";
        // *INDENT-ON*
        case achievement::time_bound::epoch::last:
            break;
    }
    debugmsg( "Invalid epoch" );
    abort();
}
References abort, achievement::time_bound::cataclysm, debugmsg, achievement::time_bound::game_start, and achievement::time_bound::last.
enum_to_string< achievement_comparison >()
template<> std::string io::enum_to_string< achievement_comparison > (achievement_comparison data)
Definition at line 74 of file achievement.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case achievement_comparison::less_equal: return "<=";
        case achievement_comparison::greater_equal: return ">=";
        case achievement_comparison::anything: return "anything";
        // *INDENT-ON*
        case achievement_comparison::last:
            break;
    }
    debugmsg( "Invalid achievement_comparison" );
    abort();
}
References abort, anything, debugmsg, greater_equal, last, and less_equal.
enum_to_string< achievement_completion >()
template<> std::string io::enum_to_string< achievement_completion > (achievement_completion data)
Definition at line 417 of file achievement.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case achievement_completion::pending: return "pending";
        case achievement_completion::completed: return "completed";
        case achievement_completion::failed: return "failed";
        // *INDENT-ON*
        case achievement_completion::last:
            break;
    }
    debugmsg( "Invalid achievement_completion" );
    abort();
}
References abort, completed, debugmsg, failed, last, and pending.
enum_to_string< add_type >()
template<> std::string io::enum_to_string< add_type > (add_type data)
Definition at line 27 of file addiction.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case add_type::NONE: return "NONE";
        case add_type::CAFFEINE: return "CAFFEINE";
        case add_type::ALCOHOL: return "ALCOHOL";
        case add_type::SLEEP: return "SLEEP";
        case add_type::PKILLER: return "PKILLER";
        case add_type::SPEED: return "SPEED";
        case add_type::CIG: return "CIG";
        case add_type::COKE: return "COKE";
        case add_type::CRACK: return "CRACK";
        case add_type::MUTAGEN: return "MUTAGEN";
        case add_type::DIAZEPAM: return "DIAZEPAM";
        case add_type::MARLOSS_R: return "MARLOSS_R";
        case add_type::MARLOSS_B: return "MARLOSS_B";
        case add_type::MARLOSS_Y: return "MARLOSS_Y";
        // *INDENT-ON*
        case add_type::NUM_ADD_TYPES:
            break;
    }
    debugmsg( "Invalid add_type" );
    abort();
}
References abort, ALCOHOL, CAFFEINE, CIG, COKE, CRACK, debugmsg, DIAZEPAM, MARLOSS_B, MARLOSS_R, MARLOSS_Y, MUTAGEN, NONE, NUM_ADD_TYPES, PKILLER, SLEEP, and SPEED.
enum_to_string< art_charge >()
template<> std::string io::enum_to_string< art_charge > (art_charge data)
Definition at line 1518 of file artifact.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        PAIR( ARTC_NULL )
        PAIR( ARTC_TIME )
        PAIR( ARTC_SOLAR )
        PAIR( ARTC_PAIN )
        PAIR( ARTC_HP )
        PAIR( ARTC_FATIGUE )
        PAIR( ARTC_PORTAL )
        // *INDENT-ON*
        case NUM_ARTCS:
            break;
    }
    debugmsg( "Invalid ARTC" );
    abort();
}
References abort, ARTC_FATIGUE, ARTC_HP, ARTC_NULL, ARTC_PAIN, ARTC_PORTAL, ARTC_SOLAR, ARTC_TIME, debugmsg, NUM_ARTCS, and PAIR.
enum_to_string< art_charge_req >()
template<> std::string io::enum_to_string< art_charge_req > (art_charge_req data)
Definition at line 1538 of file artifact.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        PAIR( ACR_NULL )
        PAIR( ACR_EQUIP )
        PAIR( ACR_SKIN )
        PAIR( ACR_SLEEP )
        PAIR( ACR_RAD )
        PAIR( ACR_WET )
        PAIR( ACR_SKY )
        // *INDENT-ON*
        case NUM_ACRS:
            break;
    }
    debugmsg( "Invalid ACR" );
    abort();
}
References abort, ACR_EQUIP, ACR_NULL, ACR_RAD, ACR_SKIN, ACR_SKY, ACR_SLEEP, ACR_WET, debugmsg, NUM_ACRS, and PAIR.
enum_to_string< art_effect_active >()
template<> std::string io::enum_to_string< art_effect_active > (art_effect_active data)
Definition at line 1472 of file artifact.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        PAIR( AEA_NULL )
        PAIR( AEA_STORM )
        PAIR( AEA_FIREBALL )
        PAIR( AEA_ADRENALINE )
        PAIR( AEA_MAP )
        PAIR( AEA_BLOOD )
        PAIR( AEA_FATIGUE )
        PAIR( AEA_ACIDBALL )
        PAIR( AEA_PULSE )
        PAIR( AEA_HEAL )
        PAIR( AEA_CONFUSED )
        PAIR( AEA_ENTRANCE )
        PAIR( AEA_BUGS )
        PAIR( AEA_TELEPORT )
        PAIR( AEA_LIGHT )
        PAIR( AEA_GROWTH )
        PAIR( AEA_HURTALL )
        PAIR( AEA_FUN )
        PAIR( AEA_SPLIT )
        PAIR( AEA_RADIATION )
        PAIR( AEA_PAIN )
        PAIR( AEA_MUTATE )
        PAIR( AEA_PARALYZE )
        PAIR( AEA_FIRESTORM )
        PAIR( AEA_ATTENTION )
        PAIR( AEA_TELEGLOW )
        PAIR( AEA_NOISE )
        PAIR( AEA_SCREAM )
        PAIR( AEA_DIM )
        PAIR( AEA_FLASH )
        PAIR( AEA_VOMIT )
        PAIR( AEA_SHADOWS )
        PAIR( AEA_STAMINA_EMPTY )
        // *INDENT-ON*
        case NUM_AEAS:
            break;
    }
    debugmsg( "Invalid AEA" );
    abort();
}
References abort, AEA_ACIDBALL, AEA_ADRENALINE, AEA_ATTENTION, AEA_BLOOD, AEA_BUGS, AEA_CONFUSED, AEA_DIM, AEA_ENTRANCE, AEA_FATIGUE, AEA_FIREBALL, AEA_FIRESTORM, AEA_FLASH, AEA_FUN, AEA_GROWTH, AEA_HEAL, AEA_HURTALL, AEA_LIGHT, AEA_MAP, AEA_MUTATE, AEA_NOISE, AEA_NULL, AEA_PAIN, AEA_PARALYZE, AEA_PULSE, AEA_RADIATION, AEA_SCREAM, AEA_SHADOWS, AEA_SPLIT, AEA_STAMINA_EMPTY, AEA_STORM, AEA_TELEGLOW, AEA_TELEPORT, AEA_VOMIT, debugmsg, NUM_AEAS, and PAIR.
enum_to_string< art_effect_passive >()
template<> std::string io::enum_to_string< art_effect_passive > (art_effect_passive data)
Definition at line 1420 of file artifact.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        PAIR( AEP_NULL )
        PAIR( AEP_STR_UP )
        PAIR( AEP_DEX_UP )
        PAIR( AEP_PER_UP )
        PAIR( AEP_INT_UP )
        PAIR( AEP_ALL_UP )
        PAIR( AEP_SPEED_UP )
        PAIR( AEP_PBLUE )
        PAIR( AEP_SNAKES )
        PAIR( AEP_INVISIBLE )
        PAIR( AEP_CLAIRVOYANCE )
        PAIR( AEP_CLAIRVOYANCE_PLUS )
        PAIR( AEP_SUPER_CLAIRVOYANCE )
        PAIR( AEP_STEALTH )
        PAIR( AEP_EXTINGUISH )
        PAIR( AEP_GLOW )
        PAIR( AEP_PSYSHIELD )
        PAIR( AEP_RESIST_ELECTRICITY )
        PAIR( AEP_CARRY_MORE )
        PAIR( AEP_SAP_LIFE )
        PAIR( AEP_FUN )
        PAIR( AEP_SPLIT )
        PAIR( AEP_HUNGER )
        PAIR( AEP_THIRST )
        PAIR( AEP_SMOKE )
        PAIR( AEP_EVIL )
        PAIR( AEP_SCHIZO )
        PAIR( AEP_RADIOACTIVE )
        PAIR( AEP_MUTAGENIC )
        PAIR( AEP_ATTENTION )
        PAIR( AEP_STR_DOWN )
        PAIR( AEP_DEX_DOWN )
        PAIR( AEP_PER_DOWN )
        PAIR( AEP_INT_DOWN )
        PAIR( AEP_ALL_DOWN )
        PAIR( AEP_SPEED_DOWN )
        PAIR( AEP_FORCE_TELEPORT )
        PAIR( AEP_MOVEMENT_NOISE )
        PAIR( AEP_BAD_WEATHER )
        PAIR( AEP_SICK )
        // *INDENT-ON*
        case NUM_AEPS:
            break;
    }
    debugmsg( "Invalid AEP" );
    abort();
}
References abort, AEP_ALL_DOWN, AEP_ALL_UP, AEP_ATTENTION, AEP_BAD_WEATHER, AEP_CARRY_MORE, AEP_CLAIRVOYANCE, AEP_CLAIRVOYANCE_PLUS, AEP_DEX_DOWN, AEP_DEX_UP, AEP_EVIL, AEP_EXTINGUISH, AEP_FORCE_TELEPORT, AEP_FUN, AEP_GLOW, AEP_HUNGER, AEP_INT_DOWN, AEP_INT_UP, AEP_INVISIBLE, AEP_MOVEMENT_NOISE, AEP_MUTAGENIC, AEP_NULL, AEP_PBLUE, AEP_PER_DOWN, AEP_PER_UP, AEP_PSYSHIELD, AEP_RADIOACTIVE, AEP_RESIST_ELECTRICITY, AEP_SAP_LIFE, AEP_SCHIZO, AEP_SICK, AEP_SMOKE, AEP_SNAKES, AEP_SPEED_DOWN, AEP_SPEED_UP, AEP_SPLIT, AEP_STEALTH, AEP_STR_DOWN, AEP_STR_UP, AEP_SUPER_CLAIRVOYANCE, AEP_THIRST, debugmsg, NUM_AEPS, and PAIR.
enum_to_string< bionic_ui_sort_mode >()
template<> std::string io::enum_to_string< bionic_ui_sort_mode > (bionic_ui_sort_mode mode)
Definition at line 144 of file bionics_ui.cpp.
{
    switch( mode ) {
        case bionic_ui_sort_mode::nsort:
        case bionic_ui_sort_mode::NONE:
            return "none";
        case bionic_ui_sort_mode::POWER:
            return "power";
        case bionic_ui_sort_mode::NAME:
            return "name";
        case bionic_ui_sort_mode::INVLET:
            return "invlet";
    }
    return "error";
}
References INVLET, NAME, NONE, nsort, and POWER.
enum_to_string< body_part >()
template<> std::string io::enum_to_string< body_part > (body_part data)
Definition at line 73 of file magic.cpp.
{
    switch( data ) {
        case body_part::bp_torso: return "TORSO";
        case body_part::bp_head: return "HEAD";
        case body_part::bp_eyes: return "EYES";
        case body_part::bp_mouth: return "MOUTH";
        case body_part::bp_arm_l: return "ARM_L";
        case body_part::bp_arm_r: return "ARM_R";
        case body_part::bp_hand_l: return "HAND_L";
        case body_part::bp_hand_r: return "HAND_R";
        case body_part::bp_leg_l: return "LEG_L";
        case body_part::bp_leg_r: return "LEG_R";
        case body_part::bp_foot_l: return "FOOT_L";
        case body_part::bp_foot_r: return "FOOT_R";
        case body_part::num_bp: break;
    }
    debugmsg( "Invalid body_part" );
    abort();
}
References abort, bp_arm_l, bp_arm_r, bp_eyes, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_mouth, bp_torso, debugmsg, and num_bp.
enum_to_string< cata_variant_type >()
template<> std::string io::enum_to_string< cata_variant_type > (cata_variant_type type)
Definition at line 7 of file cata_variant.cpp.
{
    switch( type ) {
        // *INDENT-OFF*
        case cata_variant_type::void_: return "void";
        case cata_variant_type::add_type: return "add_type";
        case cata_variant_type::bionic_id: return "bionic_id";
        case cata_variant_type::body_part: return "body_part";
        case cata_variant_type::bool_: return "bool";
        case cata_variant_type::character_id: return "character_id";
        case cata_variant_type::character_movemode: return "character_movemode";
        case cata_variant_type::efftype_id: return "efftype_id";
        case cata_variant_type::hp_part: return "hp_part";
        case cata_variant_type::int_: return "int";
        case cata_variant_type::itype_id: return "itype_id";
        case cata_variant_type::matype_id: return "matype_id";
        case cata_variant_type::mtype_id: return "mtype_id";
        case cata_variant_type::mutagen_technique: return "mutagen_technique";
        case cata_variant_type::mutation_category_id: return "mutation_category_id";
        case cata_variant_type::oter_id: return "oter_id";
        case cata_variant_type::skill_id: return "skill_id";
        case cata_variant_type::species_id: return "species_id";
        case cata_variant_type::spell_id: return "spell_id";
        case cata_variant_type::string: return "string";
        case cata_variant_type::ter_id: return "ter_id";
        case cata_variant_type::trait_id: return "trait_id";
        case cata_variant_type::trap_str_id: return "trap_str_id";
        // *INDENT-ON*
        case cata_variant_type::num_types:
            break;
    }
    debugmsg( "unknown cata_variant_type %d", static_cast<int>( type ) );
    return "";
}
References add_type, bionic_id, body_part, bool_, character_id, character_movemode, debugmsg, efftype_id, hp_part, int_, itype_id, matype_id, mtype_id, mutagen_technique, mutation_category_id, num_types, oter_id, skill_id, species_id, spell_id, string, ter_id, trait_id, trap_str_id, type, and void_.
enum_to_string< character_movemode >()
template<> std::string io::enum_to_string< character_movemode > (character_movemode data)
Definition at line 376 of file character.cpp.
{
    switch( data ) {
            // *INDENT-OFF*
        case character_movemode::CMM_WALK: return "walk";
        case character_movemode::CMM_RUN: return "run";
        case character_movemode::CMM_CROUCH: return "crouch";
            // *INDENT-ON*
        case character_movemode::CMM_COUNT:
            break;
    }
    debugmsg( "Invalid character_movemode" );
    abort();
}
References abort, CMM_COUNT, CMM_CROUCH, CMM_RUN, CMM_WALK, and debugmsg.
enum_to_string< character_stat >()
template<> std::string io::enum_to_string< character_stat > (character_stat data)
Definition at line 4213 of file character.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
    case character_stat::STRENGTH:     return "STR";
    case character_stat::DEXTERITY:    return "DEX";
    case character_stat::INTELLIGENCE: return "INT";
    case character_stat::PERCEPTION:   return "PER";
        // *INDENT-ON*
        case character_stat::DUMMY_STAT:
            break;
    }
    abort();
}
References abort, DEXTERITY, DUMMY_STAT, INTELLIGENCE, PERCEPTION, and STRENGTH.
enum_to_string< clothing_mod_type >()
template<> std::string io::enum_to_string< clothing_mod_type > (clothing_mod_type data)
Definition at line 44 of file clothing_mod.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case clothing_mod_type_acid: return "acid";
        case clothing_mod_type_fire: return "fire";
        case clothing_mod_type_bash: return "bash";
        case clothing_mod_type_cut: return "cut";
        case clothing_mod_type_bullet: return "bullet";
        case clothing_mod_type_encumbrance: return "encumbrance";
        case clothing_mod_type_warmth: return "warmth";
        case clothing_mod_type_storage: return "storage";
        case clothing_mod_type_invalid: return "invalid";
        // *INDENT-ON*
        case num_clothing_mod_types:
            break;
    }
    debugmsg( "Invalid mod type value '%d'.", data );
    return "invalid";
}
References clothing_mod_type_acid, clothing_mod_type_bash, clothing_mod_type_bullet, clothing_mod_type_cut, clothing_mod_type_encumbrance, clothing_mod_type_fire, clothing_mod_type_invalid, clothing_mod_type_storage, clothing_mod_type_warmth, debugmsg, and num_clothing_mod_types.
Referenced by clothing_mods::string_from_clothing_mod_type().
enum_to_string< computer_action >()
template<> std::string io::enum_to_string< computer_action > (const computer_action act)
Definition at line 287 of file computer.cpp.
{
    switch( act ) {
        // *INDENT-OFF*
        case COMPACT_NULL: return "null";
        case COMPACT_AMIGARA_LOG: return "amigara_log";
        case COMPACT_AMIGARA_START: return "amigara_start";
        case COMPACT_BLOOD_ANAL: return "blood_anal";
        case COMPACT_CASCADE: return "cascade";
        case COMPACT_COMPLETE_DISABLE_EXTERNAL_POWER: return "complete_disable_external_power";
        case COMPACT_CONVEYOR: return "conveyor";
        case COMPACT_DATA_ANAL: return "data_anal";
        case COMPACT_DEACTIVATE_SHOCK_VENT: return "deactivate_shock_vent";
        case COMPACT_DISCONNECT: return "disconnect";
        case COMPACT_DOWNLOAD_SOFTWARE: return "download_software";
        case COMPACT_ELEVATOR_ON: return "elevator_on";
        case COMPACT_EMERG_MESS: return "emerg_mess";
        case COMPACT_EMERG_REF_CENTER: return "emerg_ref_center";
        case COMPACT_EXTRACT_RAD_SOURCE: return "extract_rad_source";
        case COMPACT_GEIGER: return "geiger";
        case COMPACT_IRRADIATOR: return "irradiator";
        case COMPACT_LIST_BIONICS: return "list_bionics";
        case COMPACT_LOCK: return "lock";
        case COMPACT_MAP_SEWER: return "map_sewer";
        case COMPACT_MAP_SUBWAY: return "map_subway";
        case COMPACT_MAPS: return "maps";
        case COMPACT_MISS_DISARM: return "miss_disarm";
        case COMPACT_OPEN: return "open";
        case COMPACT_OPEN_DISARM: return "open_disarm";
        case COMPACT_PORTAL: return "portal";
        case COMPACT_RADIO_ARCHIVE: return "radio_archive";
        case COMPACT_RELEASE: return "release";
        case COMPACT_RELEASE_BIONICS: return "release_bionics";
        case COMPACT_RELEASE_DISARM: return "release_disarm";
        case COMPACT_REPEATER_MOD: return "repeater_mod";
        case COMPACT_RESEARCH: return "research";
        case COMPACT_SAMPLE: return "sample";
        case COMPACT_SHUTTERS: return "shutters";
        case COMPACT_SR1_MESS: return "sr1_mess";
        case COMPACT_SR2_MESS: return "sr2_mess";
        case COMPACT_SR3_MESS: return "sr3_mess";
        case COMPACT_SR4_MESS: return "sr4_mess";
        case COMPACT_SRCF_1_MESS: return "srcf_1_mess";
        case COMPACT_SRCF_2_MESS: return "srcf_2_mess";
        case COMPACT_SRCF_3_MESS: return "srcf_3_mess";
        case COMPACT_SRCF_ELEVATOR: return "srcf_elevator";
        case COMPACT_SRCF_SEAL: return "srcf_seal";
        case COMPACT_SRCF_SEAL_ORDER: return "srcf_seal_order";
        case COMPACT_TERMINATE: return "terminate";
        case COMPACT_TOLL: return "toll";
        case COMPACT_TOWER_UNRESPONSIVE: return "tower_unresponsive";
        case COMPACT_UNLOCK: return "unlock";
        case COMPACT_UNLOCK_DISARM: return "unlock_disarm";
        // *INDENT-OFF*
        case NUM_COMPUTER_ACTIONS:
            break;
    }
    debugmsg( "Invalid computer_action" );
    abort();
}
References abort, act, COMPACT_AMIGARA_LOG, COMPACT_AMIGARA_START, COMPACT_BLOOD_ANAL, COMPACT_CASCADE, COMPACT_COMPLETE_DISABLE_EXTERNAL_POWER, COMPACT_CONVEYOR, COMPACT_DATA_ANAL, COMPACT_DEACTIVATE_SHOCK_VENT, COMPACT_DISCONNECT, COMPACT_DOWNLOAD_SOFTWARE, COMPACT_ELEVATOR_ON, COMPACT_EMERG_MESS, COMPACT_EMERG_REF_CENTER, COMPACT_EXTRACT_RAD_SOURCE, COMPACT_GEIGER, COMPACT_IRRADIATOR, COMPACT_LIST_BIONICS, COMPACT_LOCK, COMPACT_MAP_SEWER, COMPACT_MAP_SUBWAY, COMPACT_MAPS, COMPACT_MISS_DISARM, COMPACT_NULL, COMPACT_OPEN, COMPACT_OPEN_DISARM, COMPACT_PORTAL, COMPACT_RADIO_ARCHIVE, COMPACT_RELEASE, COMPACT_RELEASE_BIONICS, COMPACT_RELEASE_DISARM, COMPACT_REPEATER_MOD, COMPACT_RESEARCH, COMPACT_SAMPLE, COMPACT_SHUTTERS, COMPACT_SR1_MESS, COMPACT_SR2_MESS, COMPACT_SR3_MESS, COMPACT_SR4_MESS, COMPACT_SRCF_1_MESS, COMPACT_SRCF_2_MESS, COMPACT_SRCF_3_MESS, COMPACT_SRCF_ELEVATOR, COMPACT_SRCF_SEAL, COMPACT_SRCF_SEAL_ORDER, COMPACT_TERMINATE, COMPACT_TOLL, COMPACT_TOWER_UNRESPONSIVE, COMPACT_UNLOCK, COMPACT_UNLOCK_DISARM, debugmsg, and NUM_COMPUTER_ACTIONS.
enum_to_string< computer_failure_type >()
template<> std::string io::enum_to_string< computer_failure_type > (const computer_failure_type fail)
Definition at line 349 of file computer.cpp.
{
    switch( fail ){
        // *INDENT-OFF*
        case COMPFAIL_NULL: return "null";
        case COMPFAIL_ALARM: return "alarm";
        case COMPFAIL_AMIGARA: return "amigara";
        case COMPFAIL_DAMAGE: return "damage";
        case COMPFAIL_DESTROY_BLOOD: return "destroy_blood";
        case COMPFAIL_DESTROY_DATA: return "destroy_data";
        case COMPFAIL_MANHACKS: return "manhacks";
        case COMPFAIL_PUMP_EXPLODE: return "pump_explode";
        case COMPFAIL_PUMP_LEAK: return "pump_leak";
        case COMPFAIL_SECUBOTS: return "secubots";
        case COMPFAIL_SHUTDOWN: return "shutdown";
        // *INDENT-ON*
        case NUM_COMPUTER_FAILURES:
            break;
    }
    debugmsg( "Invalid computer_failure_type" );
    abort();
}
References abort, COMPFAIL_ALARM, COMPFAIL_AMIGARA, COMPFAIL_DAMAGE, COMPFAIL_DESTROY_BLOOD, COMPFAIL_DESTROY_DATA, COMPFAIL_MANHACKS, COMPFAIL_NULL, COMPFAIL_PUMP_EXPLODE, COMPFAIL_PUMP_LEAK, COMPFAIL_SECUBOTS, COMPFAIL_SHUTDOWN, debugmsg, and NUM_COMPUTER_FAILURES.
enum_to_string< condition_type >()
template<> std::string io::enum_to_string< condition_type > (condition_type data)
Definition at line 24 of file itype.cpp.
{
    switch( data ) {
        case condition_type::FLAG:
            return "FLAG";
        case condition_type::COMPONENT_ID:
            return "COMPONENT_ID";
        case condition_type::num_condition_types:
            break;
    }
    debugmsg( "Invalid condition_type" );
    abort();
}
References abort, COMPONENT_ID, debugmsg, FLAG, and num_condition_types.
enum_to_string< DC >()
template<> std::string io::enum_to_string< DC > (DC x)
Definition at line 668 of file debug.cpp.
{
    switch( x ) {
        // *INDENT-OFF*
        case DC::DebugMsg: return "DEBUGMSG";
        case DC::DebugModeMsg: return "DMODE";
        case DC::Game: return "GAME";
        case DC::Main: return "MAIN";
        case DC::Map: return "MAP";
        case DC::MapGen: return "MAPGEN";
        case DC::MapMem: return "MAPMEM";
        case DC::NPC: return "NPC";
        case DC::SDL: return "SDL";
        // *INDENT-ON*
        case DC::Num:
            break;
    }
    debugmsg( "Invalid debug class" );
    abort();
}
References abort, DebugModeMsg, debugmsg, DebugMsg, Game, Main, Map, MapGen, MapMem, NPC, Num, and SDL.
Referenced by output_repetitions(), and detail::realDebugLog().
enum_to_string< description_affix >()
template<> std::string io::enum_to_string< description_affix > (description_affix data)
Definition at line 41 of file field_type.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case description_affix::DESCRIPTION_AFFIX_IN: return "in";
        case description_affix::DESCRIPTION_AFFIX_COVERED_IN: return "covered_in";
        case description_affix::DESCRIPTION_AFFIX_ON: return "on";
        case description_affix::DESCRIPTION_AFFIX_UNDER: return "under";
        case description_affix::DESCRIPTION_AFFIX_ILLUMINTED_BY: return "illuminated_by";
        // *INDENT-ON*
        case description_affix::DESCRIPTION_AFFIX_NUM:
            break;
    }
    debugmsg( "Invalid description affix value '%d'.", data );
    return "invalid";
}
References debugmsg, DESCRIPTION_AFFIX_COVERED_IN, DESCRIPTION_AFFIX_ILLUMINTED_BY, DESCRIPTION_AFFIX_IN, DESCRIPTION_AFFIX_NUM, DESCRIPTION_AFFIX_ON, and DESCRIPTION_AFFIX_UNDER.
enum_to_string< distraction_type >()
template<> std::string io::enum_to_string< distraction_type > (distraction_type data)
Definition at line 24 of file distraction_manager.cpp.
{
    switch( data ) {
            // *INDENT-OFF*
        case distraction_type::alert: return "Alert";
        case distraction_type::noise: return "Noise";
        case distraction_type::pain: return "Pain";
        case distraction_type::attacked: return "Attacked";
        case distraction_type::hostile_spotted_far: return "Hostile Far";
        case distraction_type::hostile_spotted_near: return "Hostile Near";
        case distraction_type::talked_to: return "Talk";
        case distraction_type::asthma: return "Asthma";
        case distraction_type::weather_change: return "Weather Change";
            // *INDENT-ON*
        case distraction_type::num_distraction_type:
            break;
    }
    debugmsg( "Invalid distraction_type" );
    abort();
}
References abort, alert, asthma, attacked, debugmsg, hostile_spotted_far, hostile_spotted_near, noise, num_distraction_type, pain, talked_to, and weather_change.
Referenced by distraction_manager::distraction_manager_gui::serialize().
enum_to_string< DL >()
template<> std::string io::enum_to_string< DL > (DL x)
Definition at line 651 of file debug.cpp.
{
    switch( x ) {
        // *INDENT-OFF*
        case DL::Info: return "INFO";
        case DL::Warn: return "WARNING";
        case DL::Error: return "ERROR";
        case DL::Debug: return "DEBUG";
        // *INDENT-ON*
        case DL::Num:
            break;
    }
    debugmsg( "Invalid debug level" );
    abort();
}
References abort, Debug, debugmsg, Error, Info, Num, and Warn.
Referenced by output_repetitions(), and detail::realDebugLog().
enum_to_string< enchant_vals::mod >()
template<> std::string io::enum_to_string< enchant_vals::mod > (enchant_vals::mod data)
Definition at line 71 of file magic_enchantment.cpp.
    {
        switch ( data ) {
            case enchant_vals::mod::STRENGTH: return "STRENGTH";
            case enchant_vals::mod::DEXTERITY: return "DEXTERITY";
            case enchant_vals::mod::PERCEPTION: return "PERCEPTION";
            case enchant_vals::mod::INTELLIGENCE: return "INTELLIGENCE";
            case enchant_vals::mod::SPEED: return "SPEED";
            case enchant_vals::mod::ATTACK_COST: return "ATTACK_COST";
            case enchant_vals::mod::MOVE_COST: return "MOVE_COST";
            case enchant_vals::mod::METABOLISM: return "METABOLISM";
            case enchant_vals::mod::MANA_CAP: return "MANA_CAP";
            case enchant_vals::mod::MANA_REGEN: return "MANA_REGEN";
            case enchant_vals::mod::STAMINA_CAP: return "STAMINA_CAP";
            case enchant_vals::mod::STAMINA_REGEN: return "STAMINA_REGEN";
            case enchant_vals::mod::THIRST: return "THIRST";
            case enchant_vals::mod::FATIGUE: return "FATIGUE";
            case enchant_vals::mod::BONUS_DODGE: return "BONUS_DODGE";
            case enchant_vals::mod::ARMOR_ACID: return "ARMOR_ACID";
            case enchant_vals::mod::ARMOR_BASH: return "ARMOR_BASH";
            case enchant_vals::mod::ARMOR_BIO: return "ARMOR_BIO";
            case enchant_vals::mod::ARMOR_COLD: return "ARMOR_COLD";
            case enchant_vals::mod::ARMOR_CUT: return "ARMOR_CUT";
            case enchant_vals::mod::ARMOR_ELEC: return "ARMOR_ELEC";
            case enchant_vals::mod::ARMOR_HEAT: return "ARMOR_HEAT";
            case enchant_vals::mod::ARMOR_STAB: return "ARMOR_STAB";
            case enchant_vals::mod::ARMOR_BULLET: return "ARMOR_BULLET";
            case enchant_vals::mod::ITEM_DAMAGE_BASH: return "ITEM_DAMAGE_BASH";
            case enchant_vals::mod::ITEM_DAMAGE_CUT: return "ITEM_DAMAGE_CUT";
            case enchant_vals::mod::ITEM_DAMAGE_STAB: return "ITEM_DAMAGE_STAB";
            case enchant_vals::mod::ITEM_ARMOR_BASH: return "ITEM_ARMOR_BASH";
            case enchant_vals::mod::ITEM_ARMOR_CUT: return "ITEM_ARMOR_CUT";
            case enchant_vals::mod::ITEM_ARMOR_STAB: return "ITEM_ARMOR_STAB";
            case enchant_vals::mod::ITEM_ARMOR_BULLET: return "ITEM_ARMOR_BULLET";
            case enchant_vals::mod::ITEM_ARMOR_HEAT: return "ITEM_ARMOR_HEAT";
            case enchant_vals::mod::ITEM_ARMOR_COLD: return "ITEM_ARMOR_COLD";
            case enchant_vals::mod::ITEM_ARMOR_ELEC: return "ITEM_ARMOR_ELEC";
            case enchant_vals::mod::ITEM_ARMOR_ACID: return "ITEM_ARMOR_ACID";
            case enchant_vals::mod::ITEM_ARMOR_BIO: return "ITEM_ARMOR_BIO";
            case enchant_vals::mod::ITEM_ATTACK_COST: return "ITEM_ATTACK_COST";
            case enchant_vals::mod::NUM_MOD: break;
        }
        debugmsg( "Invalid enchant_vals::mod" );
        abort();
    }
References abort, enchant_vals::ARMOR_ACID, enchant_vals::ARMOR_BASH, enchant_vals::ARMOR_BIO, enchant_vals::ARMOR_BULLET, enchant_vals::ARMOR_COLD, enchant_vals::ARMOR_CUT, enchant_vals::ARMOR_ELEC, enchant_vals::ARMOR_HEAT, enchant_vals::ARMOR_STAB, enchant_vals::ATTACK_COST, enchant_vals::BONUS_DODGE, debugmsg, enchant_vals::DEXTERITY, enchant_vals::FATIGUE, enchant_vals::INTELLIGENCE, enchant_vals::ITEM_ARMOR_ACID, enchant_vals::ITEM_ARMOR_BASH, enchant_vals::ITEM_ARMOR_BIO, enchant_vals::ITEM_ARMOR_BULLET, enchant_vals::ITEM_ARMOR_COLD, enchant_vals::ITEM_ARMOR_CUT, enchant_vals::ITEM_ARMOR_ELEC, enchant_vals::ITEM_ARMOR_HEAT, enchant_vals::ITEM_ARMOR_STAB, enchant_vals::ITEM_ATTACK_COST, enchant_vals::ITEM_DAMAGE_BASH, enchant_vals::ITEM_DAMAGE_CUT, enchant_vals::ITEM_DAMAGE_STAB, enchant_vals::MANA_CAP, enchant_vals::MANA_REGEN, enchant_vals::METABOLISM, enchant_vals::MOVE_COST, enchant_vals::NUM_MOD, enchant_vals::PERCEPTION, enchant_vals::SPEED, enchant_vals::STAMINA_CAP, enchant_vals::STAMINA_REGEN, enchant_vals::STRENGTH, and enchant_vals::THIRST.
enum_to_string< enchantment::condition >()
template<> std::string io::enum_to_string< enchantment::condition > (enchantment::condition data)
Definition at line 57 of file magic_enchantment.cpp.
    {
        switch ( data ) {
        case enchantment::condition::ALWAYS: return "ALWAYS";
        case enchantment::condition::UNDERGROUND: return "UNDERGROUND";
        case enchantment::condition::UNDERWATER: return "UNDERWATER";
        case enchantment::condition::ACTIVE: return "ACTIVE";
        case enchantment::condition::NUM_CONDITION: break;
        }
        debugmsg( "Invalid enchantment::condition" );
        abort();
    }
References abort, and debugmsg.
enum_to_string< enchantment::has >()
template<> std::string io::enum_to_string< enchantment::has > (enchantment::has data)
Definition at line 44 of file magic_enchantment.cpp.
    {
        switch ( data ) {
        case enchantment::has::HELD: return "HELD";
        case enchantment::has::WIELD: return "WIELD";
        case enchantment::has::WORN: return "WORN";
        case enchantment::has::NUM_HAS: break;
        }
        debugmsg( "Invalid enchantment::has" );
        abort();
    }
References abort, debugmsg, and WIELD.
enum_to_string< event_type >()
template<> std::string io::enum_to_string< event_type > (event_type data)
Definition at line 7 of file event.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case event_type::activates_artifact: return "activates_artifact";
        case event_type::activates_mininuke: return "activates_mininuke";
        case event_type::administers_mutagen: return "administers_mutagen";
        case event_type::angers_amigara_horrors: return "angers_amigara_horrors";
        case event_type::avatar_moves: return "avatar_moves";
        case event_type::awakes_dark_wyrms: return "awakes_dark_wyrms";
        case event_type::becomes_wanted: return "becomes_wanted";
        case event_type::broken_bone_mends: return "broken_bone_mends";
        case event_type::buries_corpse: return "buries_corpse";
        case event_type::causes_resonance_cascade: return "causes_resonance_cascade";
        case event_type::character_gains_effect: return "character_gains_effect";
        case event_type::character_gets_headshot: return "character_gets_headshot";
        case event_type::character_heals_damage: return "character_heals_damage";
        case event_type::character_kills_character: return "character_kills_character";
        case event_type::character_kills_monster: return "character_kills_monster";
        case event_type::character_loses_effect: return "character_loses_effect";
        case event_type::character_takes_damage: return "character_takes_damage";
        case event_type::character_triggers_trap: return "character_triggers_trap";
        case event_type::character_wakes_up: return "character_wakes_up";
        case event_type::consumes_marloss_item: return "consumes_marloss_item";
        case event_type::crosses_marloss_threshold: return "crosses_marloss_threshold";
        case event_type::crosses_mutation_threshold: return "crosses_mutation_threshold";
        case event_type::crosses_mycus_threshold: return "crosses_mycus_threshold";
        case event_type::dermatik_eggs_hatch: return "dermatik_eggs_hatch";
        case event_type::dermatik_eggs_injected: return "dermatik_eggs_injected";
        case event_type::destroys_triffid_grove: return "destroys_triffid_grove";
        case event_type::dies_from_asthma_attack: return "dies_from_asthma_attack";
        case event_type::dies_from_drug_overdose: return "dies_from_drug_overdose";
        case event_type::dies_of_infection: return "dies_of_infection";
        case event_type::dies_of_starvation: return "dies_of_starvation";
        case event_type::dies_of_thirst: return "dies_of_thirst";
        case event_type::digs_into_lava: return "digs_into_lava";
        case event_type::disarms_nuke: return "disarms_nuke";
        case event_type::eats_sewage: return "eats_sewage";
        case event_type::evolves_mutation: return "evolves_mutation";
        case event_type::exhumes_grave: return "exhumes_grave";
        case event_type::fails_to_install_cbm: return "fails_to_install_cbm";
        case event_type::fails_to_remove_cbm: return "fails_to_remove_cbm";
        case event_type::falls_asleep_from_exhaustion: return "falls_asleep_from_exhaustion";
        case event_type::fuel_tank_explodes: return "fuel_tank_explodes";
        case event_type::gains_addiction: return "gains_addiction";
        case event_type::gains_mutation: return "gains_mutation";
        case event_type::gains_skill_level: return "gains_skill_level";
        case event_type::game_over: return "game_over";
        case event_type::game_start: return "game_start";
        case event_type::installs_cbm: return "installs_cbm";
        case event_type::installs_faulty_cbm: return "installs_faulty_cbm";
        case event_type::learns_martial_art: return "learns_martial_art";
        case event_type::loses_addiction: return "loses_addiction";
        case event_type::npc_becomes_hostile: return "npc_becomes_hostile";
        case event_type::opens_portal: return "opens_portal";
        case event_type::opens_temple: return "opens_temple";
        case event_type::player_levels_spell: return "player_levels_spell";
        case event_type::releases_subspace_specimens: return "releases_subspace_specimens";
        case event_type::removes_cbm: return "removes_cbm";
        case event_type::seals_hazardous_material_sarcophagus: return "seals_hazardous_material_sarcophagus";
        case event_type::telefrags_creature: return "telefrags_creature";
        case event_type::teleglow_teleports: return "teleglow_teleports";
        case event_type::teleports_into_wall: return "teleports_into_wall";
        case event_type::terminates_subspace_specimens: return "terminates_subspace_specimens";
        case event_type::throws_up: return "throws_up";
        case event_type::triggers_alarm: return "triggers_alarm";
        // *INDENT-ON*
        case event_type::num_event_types:
            break;
    }
    debugmsg( "Invalid event_type" );
    abort();
}
References abort, activates_artifact, activates_mininuke, administers_mutagen, angers_amigara_horrors, avatar_moves, awakes_dark_wyrms, becomes_wanted, broken_bone_mends, buries_corpse, causes_resonance_cascade, character_gains_effect, character_gets_headshot, character_heals_damage, character_kills_character, character_kills_monster, character_loses_effect, character_takes_damage, character_triggers_trap, character_wakes_up, consumes_marloss_item, crosses_marloss_threshold, crosses_mutation_threshold, crosses_mycus_threshold, debugmsg, dermatik_eggs_hatch, dermatik_eggs_injected, destroys_triffid_grove, dies_from_asthma_attack, dies_from_drug_overdose, dies_of_infection, dies_of_starvation, dies_of_thirst, digs_into_lava, disarms_nuke, eats_sewage, evolves_mutation, exhumes_grave, fails_to_install_cbm, fails_to_remove_cbm, falls_asleep_from_exhaustion, fuel_tank_explodes, gains_addiction, gains_mutation, gains_skill_level, game_over, game_start, installs_cbm, installs_faulty_cbm, learns_martial_art, loses_addiction, npc_becomes_hostile, num_event_types, opens_portal, opens_temple, player_levels_spell, releases_subspace_specimens, removes_cbm, seals_hazardous_material_sarcophagus, telefrags_creature, teleglow_teleports, teleports_into_wall, terminates_subspace_specimens, throws_up, and triggers_alarm.
enum_to_string< fields::stacking_type >()
template<> std::string io::enum_to_string< fields::stacking_type > (fields::stacking_type data)
Definition at line 59 of file field_type.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case fields::stacking_type::intensity: return "intensity";
        case fields::stacking_type::duration: return "duration";
        // *INDENT-ON*
        case fields::stacking_type::stacking_type_num:
            break;
    }
    debugmsg( "Invalid field stacking type value '%d'.", data );
    return "invalid";
}
References debugmsg, fields::duration, fields::intensity, and fields::stacking_type_num.
enum_to_string< game_message_type >()
template<> std::string io::enum_to_string< game_message_type > (game_message_type data)
Definition at line 18 of file field_type.cpp.
{
    switch( data ) {
            // *INDENT-OFF*
        case game_message_type::m_good: return "good";
        case game_message_type::m_bad: return "bad";
        case game_message_type::m_mixed: return "mixed";
        case game_message_type::m_warning: return "warning";
        case game_message_type::m_info: return "info";
        case game_message_type::m_neutral: return "neutral";
        case game_message_type::m_debug: return "debug";
        case game_message_type::m_headshot: return "headshot";
        case game_message_type::m_critical: return "critical";
        case game_message_type::m_grazing: return "grazing";
            // *INDENT-ON*
        case game_message_type::num_game_message_type:
            break;
    }
    debugmsg( "Invalid game_message_type" );
    abort();
}
References abort, debugmsg, m_bad, m_critical, m_debug, m_good, m_grazing, m_headshot, m_info, m_mixed, m_neutral, m_warning, and num_game_message_type.
enum_to_string< hp_part >()
template<> std::string io::enum_to_string< hp_part > (hp_part data)
Definition at line 67 of file bodypart.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case hp_part::hp_head: return "head";
        case hp_part::hp_torso: return "torso";
        case hp_part::hp_arm_l: return "arm_l";
        case hp_part::hp_arm_r: return "arm_r";
        case hp_part::hp_leg_l: return "leg_l";
        case hp_part::hp_leg_r: return "leg_r";
        // *INDENT-ON*
        case hp_part::num_hp_parts:
            break;
    }
    debugmsg( "Invalid hp_part" );
    abort();
}
References abort, debugmsg, hp_arm_l, hp_arm_r, hp_head, hp_leg_l, hp_leg_r, hp_torso, and num_hp_parts.
enum_to_string< lab_type >()
template<> std::string io::enum_to_string< lab_type > (lab_type data)
Definition at line 341 of file overmap.cpp.
{
    switch( data ) {
        case lab_type::standard:
            return "standard";
        case lab_type::ice:
            return "ice";
        case lab_type::central:
            return "central";
        case lab_type::invalid:
            return "invalid";
    }
    return "BUGGED";
}
References central, ice, invalid, and standard.
enum_to_string< m_flag >()
template<> std::string io::enum_to_string< m_flag > (m_flag data)
Definition at line 63 of file monstergenerator.cpp.
{
    // see mtype.h for commentary
    switch( data ) {
        // *INDENT-OFF*
        case MF_SEES: return "SEES";
        case MF_HEARS: return "HEARS";
        case MF_GOODHEARING: return "GOODHEARING";
        case MF_SMELLS: return "SMELLS";
        case MF_KEENNOSE: return "KEENNOSE";
        case MF_STUMBLES: return "STUMBLES";
        case MF_WARM: return "WARM";
        case MF_NOHEAD: return "NOHEAD";
        case MF_HARDTOSHOOT: return "HARDTOSHOOT";
        case MF_GRABS: return "GRABS";
        case MF_BASHES: return "BASHES";
        case MF_GROUP_BASH: return "GROUP_BASH";
        case MF_DESTROYS: return "DESTROYS";
        case MF_BORES: return "BORES";
        case MF_POISON: return "POISON";
        case MF_VENOM: return "VENOM";
        case MF_BADVENOM: return "BADVENOM";
        case MF_PARALYZE: return "PARALYZEVENOM";
        case MF_BLEED: return "BLEED";
        case MF_WEBWALK: return "WEBWALK";
        case MF_DIGS: return "DIGS";
        case MF_CAN_DIG: return "CAN_DIG";
        case MF_CAN_OPEN_DOORS: return "CAN_OPEN_DOORS";
        case MF_FLIES: return "FLIES";
        case MF_AQUATIC: return "AQUATIC";
        case MF_SWIMS: return "SWIMS";
        case MF_FISHABLE: return "FISHABLE";
        case MF_ATTACKMON: return "ATTACKMON";
        case MF_ANIMAL: return "ANIMAL";
        case MF_PLASTIC: return "PLASTIC";
        case MF_SUNDEATH: return "SUNDEATH";
        case MF_ELECTRIC: return "ELECTRIC";
        case MF_ACIDPROOF: return "ACIDPROOF";
        case MF_ACIDTRAIL: return "ACIDTRAIL";
        case MF_SHORTACIDTRAIL: return "SHORTACIDTRAIL";
        case MF_FIREPROOF: return "FIREPROOF";
        case MF_SLUDGEPROOF: return "SLUDGEPROOF";
        case MF_SLUDGETRAIL: return "SLUDGETRAIL";
        case MF_COLDPROOF: return "COLDPROOF";
        case MF_FIREY: return "FIREY";
        case MF_QUEEN: return "QUEEN";
        case MF_ELECTRONIC: return "ELECTRONIC";
        case MF_FUR: return "FUR";
        case MF_LEATHER: return "LEATHER";
        case MF_WOOL: return "WOOL";
        case MF_FEATHER: return "FEATHER";
        case MF_CBM_CIV: return "CBM_CIV";
        case MF_BONES: return "BONES";
        case MF_FAT: return "FAT";
        case MF_CONSOLE_DESPAWN: return "CONSOLE_DESPAWN";
        case MF_IMMOBILE: return "IMMOBILE";
        case MF_ID_CARD_DESPAWN: return "ID_CARD_DESPAWN";
        case MF_RIDEABLE_MECH: return "RIDEABLE_MECH";
        case MF_MILITARY_MECH: return "MILITARY_MECH";
        case MF_MECH_RECON_VISION: return "MECH_RECON_VISION";
        case MF_MECH_DEFENSIVE: return "MECH_DEFENSIVE";
        case MF_HIT_AND_RUN: return "HIT_AND_RUN";
        case MF_GUILT: return "GUILT";
        case MF_PAY_BOT: return "PAY_BOT";
        case MF_HUMAN: return "HUMAN";
        case MF_NO_BREATHE: return "NO_BREATHE";
        case MF_FLAMMABLE: return "FLAMMABLE";
        case MF_REVIVES: return "REVIVES";
        case MF_CHITIN: return "CHITIN";
        case MF_VERMIN: return "VERMIN";
        case MF_NOGIB: return "NOGIB";
        case MF_ABSORBS: return "ABSORBS";
        case MF_ABSORBS_SPLITS: return "ABSORBS_SPLITS";
        case MF_LARVA: return "LARVA";
        case MF_ARTHROPOD_BLOOD: return "ARTHROPOD_BLOOD";
        case MF_ACID_BLOOD: return "ACID_BLOOD";
        case MF_BILE_BLOOD: return "BILE_BLOOD";
        case MF_CBM_POWER: return "CBM_POWER";
        case MF_CBM_SCI: return "CBM_SCI";
        case MF_CBM_OP: return "CBM_OP";
        case MF_CBM_TECH: return "CBM_TECH";
        case MF_CBM_SUBS: return "CBM_SUBS";
        case MF_FILTHY: return "FILTHY";
        case MF_SWARMS: return "SWARMS";
        case MF_CLIMBS: return "CLIMBS";
        case MF_GROUP_MORALE: return "GROUP_MORALE";
        case MF_INTERIOR_AMMO: return "INTERIOR_AMMO";
        case MF_NIGHT_INVISIBILITY: return "NIGHT_INVISIBILITY";
        case MF_REVIVES_HEALTHY: return "REVIVES_HEALTHY";
        case MF_NO_NECRO: return "NO_NECRO";
        case MF_PACIFIST: return "PACIFIST";
        case MF_PUSH_MON: return "PUSH_MON";
        case MF_PUSH_VEH: return "PUSH_VEH";
        case MF_AVOID_DANGER_1: return "PATH_AVOID_DANGER_1";
        case MF_AVOID_DANGER_2: return "PATH_AVOID_DANGER_2";
        case MF_AVOID_FALL: return "PATH_AVOID_FALL";
        case MF_AVOID_FIRE: return "PATH_AVOID_FIRE";
        case MF_PRIORITIZE_TARGETS: return "PRIORITIZE_TARGETS";
        case MF_NOT_HALLU: return "NOT_HALLUCINATION";
        case MF_CATFOOD: return "CATFOOD";
        case MF_CANPLAY: return "CANPLAY";
        case MF_CATTLEFODDER: return "CATTLEFODDER";
        case MF_BIRDFOOD: return "BIRDFOOD";
        case MF_PET_MOUNTABLE: return "PET_MOUNTABLE";
        case MF_PET_HARNESSABLE: return "PET_HARNESSABLE";
        case MF_DOGFOOD: return "DOGFOOD";
        case MF_MILKABLE: return "MILKABLE";
        case MF_SHEARABLE: return "SHEARABLE";
        case MF_NO_BREED: return "NO_BREED";
        case MF_NO_FUNG_DMG: return "NO_FUNG_DMG";
        case MF_PET_WONT_FOLLOW: return "PET_WONT_FOLLOW";
        case MF_DRIPS_NAPALM: return "DRIPS_NAPALM";
        case MF_DRIPS_GASOLINE: return "DRIPS_GASOLINE";
        case MF_ELECTRIC_FIELD: return "ELECTRIC_FIELD";
        case MF_STUN_IMMUNE: return "STUN_IMMUNE";
        case MF_LOUDMOVES: return "LOUDMOVES";
        case MF_DROPS_AMMO: return "DROPS_AMMO";
        // *INDENT-ON*
        case m_flag::MF_MAX:
            break;
    }
    debugmsg( "Invalid m_flag" );
    abort();
}
References abort, debugmsg, MF_ABSORBS, MF_ABSORBS_SPLITS, MF_ACID_BLOOD, MF_ACIDPROOF, MF_ACIDTRAIL, MF_ANIMAL, MF_AQUATIC, MF_ARTHROPOD_BLOOD, MF_ATTACKMON, MF_AVOID_DANGER_1, MF_AVOID_DANGER_2, MF_AVOID_FALL, MF_AVOID_FIRE, MF_BADVENOM, MF_BASHES, MF_BILE_BLOOD, MF_BIRDFOOD, MF_BLEED, MF_BONES, MF_BORES, MF_CAN_DIG, MF_CAN_OPEN_DOORS, MF_CANPLAY, MF_CATFOOD, MF_CATTLEFODDER, MF_CBM_CIV, MF_CBM_OP, MF_CBM_POWER, MF_CBM_SCI, MF_CBM_SUBS, MF_CBM_TECH, MF_CHITIN, MF_CLIMBS, MF_COLDPROOF, MF_CONSOLE_DESPAWN, MF_DESTROYS, MF_DIGS, MF_DOGFOOD, MF_DRIPS_GASOLINE, MF_DRIPS_NAPALM, MF_DROPS_AMMO, MF_ELECTRIC, MF_ELECTRIC_FIELD, MF_ELECTRONIC, MF_FAT, MF_FEATHER, MF_FILTHY, MF_FIREPROOF, MF_FIREY, MF_FISHABLE, MF_FLAMMABLE, MF_FLIES, MF_FUR, MF_GOODHEARING, MF_GRABS, MF_GROUP_BASH, MF_GROUP_MORALE, MF_GUILT, MF_HARDTOSHOOT, MF_HEARS, MF_HIT_AND_RUN, MF_HUMAN, MF_ID_CARD_DESPAWN, MF_IMMOBILE, MF_INTERIOR_AMMO, MF_KEENNOSE, MF_LARVA, MF_LEATHER, MF_LOUDMOVES, MF_MAX, MF_MECH_DEFENSIVE, MF_MECH_RECON_VISION, MF_MILITARY_MECH, MF_MILKABLE, MF_NIGHT_INVISIBILITY, MF_NO_BREATHE, MF_NO_BREED, MF_NO_FUNG_DMG, MF_NO_NECRO, MF_NOGIB, MF_NOHEAD, MF_NOT_HALLU, MF_PACIFIST, MF_PARALYZE, MF_PAY_BOT, MF_PET_HARNESSABLE, MF_PET_MOUNTABLE, MF_PET_WONT_FOLLOW, MF_PLASTIC, MF_POISON, MF_PRIORITIZE_TARGETS, MF_PUSH_MON, MF_PUSH_VEH, MF_QUEEN, MF_REVIVES, MF_REVIVES_HEALTHY, MF_RIDEABLE_MECH, MF_SEES, MF_SHEARABLE, MF_SHORTACIDTRAIL, MF_SLUDGEPROOF, MF_SLUDGETRAIL, MF_SMELLS, MF_STUMBLES, MF_STUN_IMMUNE, MF_SUNDEATH, MF_SWARMS, MF_SWIMS, MF_VENOM, MF_VERMIN, MF_WARM, MF_WEBWALK, and MF_WOOL.
Referenced by debug_menu::debug().
enum_to_string< m_size >()
template<> std::string io::enum_to_string< m_size > (m_size data)
Definition at line 36 of file mutation_data.cpp.
{
    switch( data ) {
        case m_size::MS_TINY:
            return "TINY";
        case m_size::MS_SMALL:
            return "SMALL";
        case m_size::MS_MEDIUM:
            return "MEDIUM";
        case m_size::MS_LARGE:
            return "LARGE";
        case m_size::MS_HUGE:
            return "HUGE";
        case m_size::num_m_size:
            return "num_m_size";
            break;
    }
    debugmsg( "Invalid body_size value for mutation: %d", static_cast<int>( data ) );
    abort();
}
References abort, debugmsg, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, and num_m_size.
enum_to_string< map_extra_method >()
template<> std::string io::enum_to_string< map_extra_method > (map_extra_method data)
Definition at line 164 of file map_extras.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case map_extra_method::null: return "null";
        case map_extra_method::map_extra_function: return "map_extra_function";
        case map_extra_method::mapgen: return "mapgen";
        case map_extra_method::update_mapgen: return "update_mapgen";
        case map_extra_method::num_map_extra_methods: break;
        // *INDENT-ON*
    }
    debugmsg( "Invalid map_extra_method" );
    abort();
}
References abort, debugmsg, map_extra_function, mapgen, null, num_map_extra_methods, and update_mapgen.
enum_to_string< mission::mission_status >()
template<> std::string io::enum_to_string< mission::mission_status > (mission::mission_status data)
Definition at line 708 of file mission.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case mission::mission_status::yet_to_start: return "yet_to_start";
        case mission::mission_status::in_progress: return "in_progress";
        case mission::mission_status::success: return "success";
        case mission::mission_status::failure: return "failure";
        // *INDENT-ON*
        case mission::mission_status::num_mission_status:
            break;
    }
    debugmsg( "Invalid mission_status" );
    abort();
}
References abort, debugmsg, mission::failure, mission::in_progress, mission::num_mission_status, mission::success, and mission::yet_to_start.
enum_to_string< mission_goal >()
template<> std::string io::enum_to_string< mission_goal > (mission_goal data)
Definition at line 165 of file missiondef.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case MGOAL_NULL: return "MGOAL_NULL";
        case MGOAL_GO_TO: return "MGOAL_GO_TO";
        case MGOAL_GO_TO_TYPE: return "MGOAL_GO_TO_TYPE";
        case MGOAL_FIND_ITEM: return "MGOAL_FIND_ITEM";
        case MGOAL_FIND_ANY_ITEM: return "MGOAL_FIND_ANY_ITEM";
        case MGOAL_FIND_ITEM_GROUP: return "MGOAL_FIND_ITEM_GROUP";
        case MGOAL_FIND_MONSTER: return "MGOAL_FIND_MONSTER";
        case MGOAL_FIND_NPC: return "MGOAL_FIND_NPC";
        case MGOAL_ASSASSINATE: return "MGOAL_ASSASSINATE";
        case MGOAL_KILL_MONSTER: return "MGOAL_KILL_MONSTER";
        case MGOAL_KILL_MONSTER_TYPE: return "MGOAL_KILL_MONSTER_TYPE";
        case MGOAL_KILL_MONSTER_SPEC: return "MGOAL_KILL_MONSTER_SPEC";
        case MGOAL_RECRUIT_NPC: return "MGOAL_RECRUIT_NPC";
        case MGOAL_RECRUIT_NPC_CLASS: return "MGOAL_RECRUIT_NPC_CLASS";
        case MGOAL_COMPUTER_TOGGLE: return "MGOAL_COMPUTER_TOGGLE";
        case MGOAL_TALK_TO_NPC: return "MGOAL_TALK_TO_NPC";
        case MGOAL_CONDITION: return "MGOAL_CONDITION";
        // *INDENT-ON*
        case mission_goal::NUM_MGOAL:
            break;
    }
    debugmsg( "Invalid mission_goal" );
    abort();
}
References abort, debugmsg, MGOAL_ASSASSINATE, MGOAL_COMPUTER_TOGGLE, MGOAL_CONDITION, MGOAL_FIND_ANY_ITEM, MGOAL_FIND_ITEM, MGOAL_FIND_ITEM_GROUP, MGOAL_FIND_MONSTER, MGOAL_FIND_NPC, MGOAL_GO_TO, MGOAL_GO_TO_TYPE, MGOAL_KILL_MONSTER, MGOAL_KILL_MONSTER_SPEC, MGOAL_KILL_MONSTER_TYPE, MGOAL_NULL, MGOAL_RECRUIT_NPC, MGOAL_RECRUIT_NPC_CLASS, MGOAL_TALK_TO_NPC, and NUM_MGOAL.
enum_to_string< mission_origin >()
template<> std::string io::enum_to_string< mission_origin > (mission_origin data)
Definition at line 146 of file missiondef.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case ORIGIN_NULL: return "ORIGIN_NULL";
        case ORIGIN_GAME_START: return "ORIGIN_GAME_START";
        case ORIGIN_OPENER_NPC: return "ORIGIN_OPENER_NPC";
        case ORIGIN_ANY_NPC: return "ORIGIN_ANY_NPC";
        case ORIGIN_SECONDARY: return "ORIGIN_SECONDARY";
        case ORIGIN_COMPUTER: return "ORIGIN_COMPUTER";
        // *INDENT-ON*
        case mission_origin::NUM_ORIGIN:
            break;
    }
    debugmsg( "Invalid mission_origin" );
    abort();
}
References abort, debugmsg, NUM_ORIGIN, ORIGIN_ANY_NPC, ORIGIN_COMPUTER, ORIGIN_GAME_START, ORIGIN_NULL, ORIGIN_OPENER_NPC, and ORIGIN_SECONDARY.
enum_to_string< mon_trigger >()
template<> std::string io::enum_to_string< mon_trigger > (mon_trigger data)
Definition at line 39 of file monstergenerator.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case mon_trigger::STALK: return "STALK";
        case mon_trigger::MEAT: return "MEAT";
        case mon_trigger::HOSTILE_WEAK: return "PLAYER_WEAK";
        case mon_trigger::HOSTILE_CLOSE: return "PLAYER_CLOSE";
        case mon_trigger::HURT: return "HURT";
        case mon_trigger::FIRE: return "FIRE";
        case mon_trigger::FRIEND_DIED: return "FRIEND_DIED";
        case mon_trigger::FRIEND_ATTACKED: return "FRIEND_ATTACKED";
        case mon_trigger::SOUND: return "SOUND";
        case mon_trigger::PLAYER_NEAR_BABY: return "PLAYER_NEAR_BABY";
        case mon_trigger::MATING_SEASON: return "MATING_SEASON";
        // *INDENT-ON*
        case mon_trigger::_LAST:
            break;
    }
    debugmsg( "Invalid mon_trigger" );
    abort();
}
References _LAST, abort, debugmsg, FIRE, FRIEND_ATTACKED, FRIEND_DIED, HOSTILE_CLOSE, HOSTILE_WEAK, HURT, MATING_SEASON, MEAT, PLAYER_NEAR_BABY, SOUND, and STALK.
enum_to_string< morale_subtype_t >()
template<> std::string io::enum_to_string< morale_subtype_t > (morale_subtype_t data)
Definition at line 54 of file morale.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case morale_subtype_t::single: return "single";
        case morale_subtype_t::by_item: return "by_item";
        case morale_subtype_t::by_effect: return "by_effect";
        // *INDENT-ON*
        case morale_subtype_t::last:
            break;
    }
    debugmsg( "Invalid morale_subtype_t" );
    abort();
}
References abort, by_effect, by_item, debugmsg, last, and single.
Referenced by player_morale::morale_subtype::describe().
enum_to_string< mutagen_technique >()
template<> std::string io::enum_to_string< mutagen_technique > (mutagen_technique data)
Definition at line 84 of file mutation.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case mutagen_technique::consumed_mutagen: return "consumed_mutagen";
        case mutagen_technique::injected_mutagen: return "injected_mutagen";
        case mutagen_technique::consumed_purifier: return "consumed_purifier";
        case mutagen_technique::injected_purifier: return "injected_purifier";
        case mutagen_technique::injected_smart_purifier: return "injected_smart_purifier";
        // *INDENT-ON*
        case mutagen_technique::num_mutagen_techniques:
            break;
    }
    debugmsg( "Invalid mutagen_technique" );
    abort();
}
References abort, consumed_mutagen, consumed_purifier, debugmsg, injected_mutagen, injected_purifier, injected_smart_purifier, and num_mutagen_techniques.
enum_to_string< ot_match_type >()
template<> std::string io::enum_to_string< ot_match_type > (ot_match_type data)
Definition at line 4991 of file overmap.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case exact: return "EXACT";
        case type: return "TYPE";
        case prefix: return "PREFIX";
        case contains: return "CONTAINS";
        // *INDENT-ON*
        case num_ot_match_type:
            break;
    }
    debugmsg( "Invalid ot_match_type" );
    abort();
}
References abort, contains, debugmsg, exact, num_ot_match_type, prefix, and type.
enum_to_string< phase_id >()
template<> std::string io::enum_to_string< phase_id > (phase_id data)
Definition at line 3129 of file item_factory.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case PNULL: return "null";
        case LIQUID: return "liquid";
        case SOLID: return "solid";
        case GAS: return "gas";
        case PLASMA: return "plasma";
        // *INDENT-ON*
        case num_phases:
            break;
    }
    debugmsg( "Invalid phase" );
    abort();
}
References abort, debugmsg, GAS, LIQUID, num_phases, PLASMA, PNULL, and SOLID.
enum_to_string< precip_class >()
template<> std::string io::enum_to_string< precip_class > (precip_class data)
Definition at line 16 of file weather_type.cpp.
{
    switch( data ) {
        case precip_class::none:
            return "none";
        case precip_class::very_light:
            return "very_light";
        case precip_class::light:
            return "light";
        case precip_class::heavy:
            return "heavy";
        case precip_class::last:
            break;
    }
    debugmsg( "Invalid precip_class" );
    abort();
}
References abort, debugmsg, heavy, last, light, none, and very_light.
enum_to_string< relic_recharge_req >()
template<> std::string io::enum_to_string< relic_recharge_req > (relic_recharge_req data)
Definition at line 48 of file relic.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case relic_recharge_req::none: return "none";
        case relic_recharge_req::equipped: return "equipped";
        case relic_recharge_req::close_to_skin: return "close_to_skin";
        case relic_recharge_req::sleep: return "sleep";
        case relic_recharge_req::rad: return "rad";
        case relic_recharge_req::wet: return "wet";
        case relic_recharge_req::sky: return "sky";
        case relic_recharge_req::num:
            break;
        // *INDENT-ON*
    }
    debugmsg( "Invalid relic_recharge_req" );
    abort();
}
References abort, close_to_skin, debugmsg, equipped, none, num, rad, sky, sleep, and wet.
enum_to_string< relic_recharge_type >()
template<> std::string io::enum_to_string< relic_recharge_type > (relic_recharge_type data)
Definition at line 28 of file relic.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case relic_recharge_type::time: return "time";
        case relic_recharge_type::solar: return "solar";
        case relic_recharge_type::pain: return "pain";
        case relic_recharge_type::hp: return "hp";
        case relic_recharge_type::fatigue: return "fatigue";
        case relic_recharge_type::field: return "field";
        case relic_recharge_type::trap: return "trap";
        case relic_recharge_type::num:
            break;
        // *INDENT-ON*
    }
    debugmsg( "Invalid relic_recharge_type" );
    abort();
}
References abort, debugmsg, fatigue, field, hp, num, pain, solar, time, and trap.
enum_to_string< season_type >()
template<> std::string io::enum_to_string< season_type > (season_type data)
Definition at line 1269 of file mapdata.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case season_type::SPRING: return "spring";
        case season_type::SUMMER: return "summer";
        case season_type::AUTUMN: return "autumn";
        case season_type::WINTER: return "winter";
        // *INDENT-ON*
        case season_type::NUM_SEASONS:
            break;
    }
    debugmsg( "Invalid season_type" );
    abort();
}
References abort, AUTUMN, debugmsg, NUM_SEASONS, SPRING, SUMMER, and WINTER.
enum_to_string< side >()
template<> std::string io::enum_to_string< side > (side data)
Definition at line 51 of file bodypart.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case side::LEFT: return "left";
        case side::RIGHT: return "right";
        case side::BOTH: return "both";
        // *INDENT-ON*
        case side::num_sides:
            break;
    }
    debugmsg( "Invalid side" );
    abort();
}
References abort, BOTH, debugmsg, LEFT, num_sides, and RIGHT.
enum_to_string< sounds::sound_t >()
template<> std::string io::enum_to_string< sounds::sound_t > (sounds::sound_t data)
Definition at line 116 of file sounds.cpp.
{
    switch ( data ) {
    case sounds::sound_t::background: return "background";
    case sounds::sound_t::weather: return "weather";
    case sounds::sound_t::music: return "music";
    case sounds::sound_t::movement: return "movement";
    case sounds::sound_t::speech: return "speech";
    case sounds::sound_t::electronic_speech: return "electronic_speech";
    case sounds::sound_t::activity: return "activity";
    case sounds::sound_t::destructive_activity: return "destructive_activity";
    case sounds::sound_t::alarm: return "alarm";
    case sounds::sound_t::combat: return "combat";
    case sounds::sound_t::alert: return "alert";
    case sounds::sound_t::order: return "order";
    case sounds::sound_t::_LAST: break;
    }
    debugmsg( "Invalid valid_target" );
    abort();
}
References sounds::_LAST, abort, sounds::activity, sounds::alarm, sounds::alert, sounds::background, sounds::combat, debugmsg, sounds::destructive_activity, sounds::electronic_speech, sounds::movement, sounds::music, sounds::order, sounds::speech, and sounds::weather.
enum_to_string< spell_flag >()
template<> std::string io::enum_to_string< spell_flag > (spell_flag data)
Definition at line 94 of file magic.cpp.
{
    switch( data ) {
        case spell_flag::PERMANENT: return "PERMANENT";
        case spell_flag::IGNORE_WALLS: return "IGNORE_WALLS";
        case spell_flag::HOSTILE_SUMMON: return "HOSTILE_SUMMON";
        case spell_flag::HOSTILE_50: return "HOSTILE_50";
        case spell_flag::SILENT: return "SILENT";
        case spell_flag::LOUD: return "LOUD";
        case spell_flag::VERBAL: return "VERBAL";
        case spell_flag::SOMATIC: return "SOMATIC";
        case spell_flag::NO_HANDS: return "NO_HANDS";
        case spell_flag::NO_LEGS: return "NO_LEGS";
        case spell_flag::UNSAFE_TELEPORT: return "UNSAFE_TELEPORT";
        case spell_flag::SWAP_POS: return "SWAP_POS";
        case spell_flag::CONCENTRATE: return "CONCENTRATE";
        case spell_flag::RANDOM_AOE: return "RANDOM_AOE";
        case spell_flag::RANDOM_DAMAGE: return "RANDOM_DAMAGE";
        case spell_flag::RANDOM_DURATION: return "RANDOM_DURATION";
        case spell_flag::RANDOM_TARGET: return "RANDOM_TARGET";
        case spell_flag::MUTATE_TRAIT: return "MUTATE_TRAIT";
        case spell_flag::PAIN_NORESIST: return "PAIN_NORESIST";
        case spell_flag::NO_FAIL: return "NO_FAIL";
        case spell_flag::WONDER: return "WONDER";
        case spell_flag::LAST: break;
    }
    debugmsg( "Invalid spell_flag" );
    abort();
}
References abort, CONCENTRATE, debugmsg, HOSTILE_50, HOSTILE_SUMMON, IGNORE_WALLS, LAST, LOUD, MUTATE_TRAIT, NO_FAIL, NO_HANDS, NO_LEGS, PAIN_NORESIST, PERMANENT, RANDOM_AOE, RANDOM_DAMAGE, RANDOM_DURATION, RANDOM_TARGET, SILENT, SOMATIC, SWAP_POS, UNSAFE_TELEPORT, VERBAL, and WONDER.
enum_to_string< sun_intensity_type >()
template<> std::string io::enum_to_string< sun_intensity_type > (sun_intensity_type data)
Definition at line 35 of file weather_type.cpp.
{
    switch( data ) {
        case sun_intensity_type::none:
            return "none";
        case sun_intensity_type::light:
            return "light";
        case sun_intensity_type::normal:
            return "normal";
        case sun_intensity_type::high:
            return "high";
        case sun_intensity_type::last:
            break;
    }
    debugmsg( "Invalid sun_intensity_type" );
    abort();
}
References abort, debugmsg, high, last, light, none, and normal.
enum_to_string< tut_lesson >()
template<> std::string io::enum_to_string< tut_lesson > (tut_lesson data)
Definition at line 54 of file gamemode_tutorial.cpp.
{
    switch( data ) {
            // *INDENT-OFF*
        case tut_lesson::LESSON_INTRO: return "LESSON_INTRO";
        case tut_lesson::LESSON_MOVE: return "LESSON_MOVE";
        case tut_lesson::LESSON_LOOK: return "LESSON_LOOK";
        case tut_lesson::LESSON_OPEN: return "LESSON_OPEN";
        case tut_lesson::LESSON_CLOSE: return "LESSON_CLOSE";
        case tut_lesson::LESSON_SMASH: return "LESSON_SMASH";
        case tut_lesson::LESSON_WINDOW: return "LESSON_WINDOW";
        case tut_lesson::LESSON_PICKUP: return "LESSON_PICKUP";
        case tut_lesson::LESSON_EXAMINE: return "LESSON_EXAMINE";
        case tut_lesson::LESSON_INTERACT: return "LESSON_INTERACT";
        case tut_lesson::LESSON_FULL_INV: return "LESSON_FULL_INV";
        case tut_lesson::LESSON_WIELD_NO_SPACE: return "LESSON_WIELD_NO_SPACE";
        case tut_lesson::LESSON_AUTOWIELD: return "LESSON_AUTOWIELD";
        case tut_lesson::LESSON_ITEM_INTO_INV: return "LESSON_ITEM_INTO_INV";
        case tut_lesson::LESSON_GOT_ARMOR: return "LESSON_GOT_ARMOR";
        case tut_lesson::LESSON_GOT_WEAPON: return "LESSON_GOT_WEAPON";
        case tut_lesson::LESSON_GOT_FOOD: return "LESSON_GOT_FOOD";
        case tut_lesson::LESSON_GOT_TOOL: return "LESSON_GOT_TOOL";
        case tut_lesson::LESSON_GOT_GUN: return "LESSON_GOT_GUN";
        case tut_lesson::LESSON_GOT_AMMO: return "LESSON_GOT_AMMO";
        case tut_lesson::LESSON_WORE_ARMOR: return "LESSON_WORE_ARMOR";
        case tut_lesson::LESSON_WORE_STORAGE: return "LESSON_WORE_STORAGE";
        case tut_lesson::LESSON_WORE_MASK: return "LESSON_WORE_MASK";
        case tut_lesson::LESSON_WEAPON_INFO: return "LESSON_WEAPON_INFO";
        case tut_lesson::LESSON_HIT_MONSTER: return "LESSON_HIT_MONSTER";
        case tut_lesson::LESSON_PAIN: return "LESSON_PAIN";
        case tut_lesson::LESSON_BUTCHER: return "LESSON_BUTCHER";
        case tut_lesson::LESSON_TOOK_PAINKILLER: return "LESSON_TOOK_PAINKILLER";
        case tut_lesson::LESSON_TOOK_CIG: return "LESSON_TOOK_CIG";
        case tut_lesson::LESSON_DRANK_WATER: return "LESSON_DRANK_WATER";
        case tut_lesson::LESSON_ACT_GRENADE: return "LESSON_ACT_GRENADE";
        case tut_lesson::LESSON_ACT_BUBBLEWRAP: return "LESSON_ACT_BUBBLEWRAP";
        case tut_lesson::LESSON_OVERLOADED: return "LESSON_OVERLOADED";
        case tut_lesson::LESSON_GUN_LOAD: return "LESSON_GUN_LOAD";
        case tut_lesson::LESSON_GUN_FIRE: return "LESSON_GUN_FIRE";
        case tut_lesson::LESSON_RECOIL: return "LESSON_RECOIL";
        case tut_lesson::LESSON_STAIRS: return "LESSON_STAIRS";
        case tut_lesson::LESSON_DARK_NO_FLASH: return "LESSON_DARK_NO_FLASH";
        case tut_lesson::LESSON_DARK: return "LESSON_DARK";
        case tut_lesson::LESSON_PICKUP_WATER: return "LESSON_PICKUP_WATER";
            // *INDENT-ON*
        case tut_lesson::NUM_LESSONS:
            break;
    }
    debugmsg( "Invalid tut_lesson" );
    abort();
}
References abort, debugmsg, LESSON_ACT_BUBBLEWRAP, LESSON_ACT_GRENADE, LESSON_AUTOWIELD, LESSON_BUTCHER, LESSON_CLOSE, LESSON_DARK, LESSON_DARK_NO_FLASH, LESSON_DRANK_WATER, LESSON_EXAMINE, LESSON_FULL_INV, LESSON_GOT_AMMO, LESSON_GOT_ARMOR, LESSON_GOT_FOOD, LESSON_GOT_GUN, LESSON_GOT_TOOL, LESSON_GOT_WEAPON, LESSON_GUN_FIRE, LESSON_GUN_LOAD, LESSON_HIT_MONSTER, LESSON_INTERACT, LESSON_INTRO, LESSON_ITEM_INTO_INV, LESSON_LOOK, LESSON_MOVE, LESSON_OPEN, LESSON_OVERLOADED, LESSON_PAIN, LESSON_PICKUP, LESSON_PICKUP_WATER, LESSON_RECOIL, LESSON_SMASH, LESSON_STAIRS, LESSON_TOOK_CIG, LESSON_TOOK_PAINKILLER, LESSON_WEAPON_INFO, LESSON_WIELD_NO_SPACE, LESSON_WINDOW, LESSON_WORE_ARMOR, LESSON_WORE_MASK, LESSON_WORE_STORAGE, and NUM_LESSONS.
Referenced by tutorial_game::add_message().
enum_to_string< usage >()
template<> std::string io::enum_to_string< usage > (usage data)
Definition at line 49 of file craft_command.cpp.
{
    switch( data ) {
        // *INDENT-OFF*
        case usage::use_from_map: return "map";
        case usage::use_from_player: return "player";
        case usage::use_from_both: return "both";
        case usage::use_from_none: return "none";
        case usage::cancel: return "cancel";
        // *INDENT-ON*
        case usage::num_usages:
            break;
    }
    debugmsg( "Invalid usage" );
    abort();
}
References abort, cancel, debugmsg, num_usages, use_from_both, use_from_map, use_from_none, and use_from_player.
enum_to_string< valid_target >()
template<> std::string io::enum_to_string< valid_target > (valid_target data)
Definition at line 56 of file magic.cpp.
{
    switch( data ) {
        case valid_target::target_ally: return "ally";
        case valid_target::target_hostile: return "hostile";
        case valid_target::target_self: return "self";
        case valid_target::target_ground: return "ground";
        case valid_target::target_none: return "none";
        case valid_target::target_item: return "item";
        case valid_target::target_fd_fire: return "fd_fire";
        case valid_target::target_fd_blood: return "fd_blood";
        case valid_target::_LAST: break;
    }
    debugmsg( "Invalid valid_target" );
    abort();
}
References _LAST, abort, debugmsg, target_ally, target_fd_blood, target_fd_fire, target_ground, target_hostile, target_item, target_none, and target_self.
enum_to_string< vitamin_type >()
template<> std::string io::enum_to_string< vitamin_type > (vitamin_type data)
Definition at line 130 of file vitamin.cpp.
{
    switch( data ) {
        case vitamin_type::VITAMIN:
            return "vitamin";
        case vitamin_type::TOXIN:
            return "toxin";
        case vitamin_type::DRUG:
            return "drug";
        case vitamin_type::COUNTER:
            return "counter";
        case vitamin_type::num_vitamin_types:
            break;
    }
    debugmsg( "Invalid vitamin_type" );
    abort();
}
References abort, COUNTER, debugmsg, DRUG, num_vitamin_types, TOXIN, and VITAMIN.
enum_to_string< weather_sound_category >()
template<> std::string io::enum_to_string< weather_sound_category > (weather_sound_category data)
Definition at line 71 of file weather_type.cpp.
{
    switch( data ) {
        case weather_sound_category::drizzle:
            return "drizzle";
        case weather_sound_category::flurries:
            return "flurries";
        case weather_sound_category::rainy:
            return "rainy";
        case weather_sound_category::snow:
            return "snow";
        case weather_sound_category::snowstorm:
            return "snowstorm";
        case weather_sound_category::thunder:
            return "thunder";
        case weather_sound_category::silent:
            return "silent";
        case weather_sound_category::last:
            break;
    }
    debugmsg( "Invalid time_requirement_type" );
    abort();
}
References abort, debugmsg, drizzle, flurries, last, rainy, silent, snow, snowstorm, and thunder.
enum_to_string< weather_time_requirement_type >()
template<> std::string io::enum_to_string< weather_time_requirement_type > (weather_time_requirement_type data)
Definition at line 54 of file weather_type.cpp.
{
    switch( data ) {
        case weather_time_requirement_type::day:
            return "day";
        case weather_time_requirement_type::night:
            return "night";
        case weather_time_requirement_type::both:
            return "both";
        case weather_time_requirement_type::last:
            break;
    }
    debugmsg( "Invalid time_requirement_type" );
    abort();
}
References abort, both, day, debugmsg, last, and night.
string_to_enum()
template<typename E > E io::string_to_enum (const std::string & data)
Definition at line 77 of file enum_conversions.h.
{
    static const std::unordered_map<std::string, E> string_to_enum_map =
        build_enum_lookup_map<E>();
    return string_to_enum_look_up( string_to_enum_map, data );
}
References string_to_enum_look_up().
string_to_enum_look_up()
template<typename C , typename E = typename C::mapped_type> E io::string_to_enum_look_up (const C & container, const std::string & data) inline
Definition at line 66 of file enum_conversions.h.
{
    const auto iter = container.find( data );
    if( iter == container.end() ) {
        throw InvalidEnumString( "Invalid enum string '" + data + "' for '" +
                                 typeid( E ).name() + "'" );
    }
    return iter->second;
}
Referenced by activity_type::load(), and string_to_enum().