Cataclysm BN: units Namespace Reference
units Namespace Reference
Classes
class angle_in_radians_tag
class energy_in_joule_tag
class mass_in_milligram_tag
class money_in_cent_tag
class probability_in_one_in_million_tag
class quantity
struct quantity_details
struct quantity_details< temperature_in_millidegree_celsius_tag >
class temperature_in_millidegree_celsius_tag
class volume_in_milliliter_tag
Typedefs
using angle = quantity< double, angle_in_radians_tag >
using energy = quantity< int, energy_in_joule_tag >
using mass = quantity< std::int64_t, mass_in_milligram_tag >
using money = quantity< int, money_in_cent_tag >
using probability = quantity< int, probability_in_one_in_million_tag >
using temperature = quantity< int, temperature_in_millidegree_celsius_tag >
using volume = quantity< int, volume_in_milliliter_tag >
Functions
std::string display (const units::energy v)
std::ostream & operator<< (std::ostream &o, mass_in_milligram_tag)
std::ostream & operator<< (std::ostream &o, volume_in_milliliter_tag)
std::ostream & operator<< (std::ostream &o, energy_in_joule_tag)
std::ostream & operator<< (std::ostream &o, money_in_cent_tag)
std::ostream & operator<< (std::ostream &o, angle_in_radians_tag)
std::ostream & operator<< (std::ostream &o, temperature_in_millidegree_celsius_tag)
std::ostream & operator<< (std::ostream &o, probability_in_one_in_million_tag)
template<typename value_type , typename tag_type >
std::ostream & operator<< (std::ostream &o, const quantity< value_type, tag_type > &v)
template<typename value_type >
constexpr quantity< value_type, angle_in_radians_tag > from_radians (const value_type v)
constexpr double to_radians (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > from_degrees (const value_type v)
constexpr double to_degrees (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > from_arcmin (const value_type v)
constexpr double to_arcmin (const units::angle v)
double sin (angle a)
double cos (angle a)
double tan (angle a)
units::angle atan2 (double y, double x)
template<typename V , typename U >
quantity< V, U > fabs (quantity< V, U > q)
template<typename V , typename U >
quantity< V, U > fmod (quantity< V, U > num, quantity< V, U > den)
template<typename value_type >
constexpr quantity< value_type, energy_in_joule_tag > from_joule (const value_type v)
template<typename value_type >
constexpr quantity< value_type, energy_in_joule_tag > from_kilojoule (const value_type v)
template<typename value_type >
constexpr value_type to_joule (const quantity< value_type, energy_in_joule_tag > &v)
template<typename value_type >
constexpr value_type to_kilojoule (const quantity< value_type, energy_in_joule_tag > &v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_milligram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_gram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_kilogram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_newton (const value_type v)
template<typename value_type >
constexpr value_type to_milligram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type to_gram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type to_kilogram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type to_newton (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > from_cent (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > from_usd (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > from_kusd (const value_type v)
template<typename value_type >
constexpr value_type to_cent (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type to_usd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type to_kusd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr quantity< value_type, probability_in_one_in_million_tag > from_one_in_million (const value_type v)
template<typename value_type >
constexpr quantity< value_type, probability_in_one_in_million_tag > from_percent (const value_type v)
template<typename value_type >
constexpr value_type to_one_in_million (const quantity< value_type, probability_in_one_in_million_tag > &v)
constexpr double fahrenheit_to_celsius (double fahrenheit)
constexpr double fahrenheit_to_kelvin (double fahrenheit)
Convert a temperature from degrees Fahrenheit to Kelvin.
constexpr double kelvin_to_fahrenheit (double kelvin)
Convert a temperature from Kelvin to degrees Fahrenheit.
constexpr double celsius_to_fahrenheit (double celsius)
Convert a temperature from Celsius to degrees Fahrenheit.
constexpr double celsius_to_kelvin (double celsius)
Convert a temperature from Celsius to kelvins.
template<typename value_type >
constexpr quantity< value_type, temperature_in_millidegree_celsius_tag > from_millidegree_celsius (const value_type v)
template<typename value_type >
constexpr quantity< value_type, temperature_in_millidegree_celsius_tag > from_celsius (const value_type v)
template<typename value_type >
constexpr quantity< value_type, temperature_in_millidegree_celsius_tag > from_fahrenheit (const value_type v)
template<typename value_type >
constexpr value_type to_millidegree_celsius (const quantity< value_type, temperature_in_millidegree_celsius_tag > &v)
template<typename value_type >
constexpr value_type to_celsius (const quantity< value_type, temperature_in_millidegree_celsius_tag > &v)
template<typename value_type >
constexpr value_type to_fahrenheit (const quantity< value_type, temperature_in_millidegree_celsius_tag > &v)
template<typename value_type >
constexpr value_type to_kelvins (const quantity< value_type, temperature_in_millidegree_celsius_tag > &v)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > from_milliliter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > from_liter (const value_type v)
template<typename value_type >
constexpr value_type to_milliliter (const quantity< value_type, volume_in_milliliter_tag > &v)
constexpr double to_liter (const volume &v)
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type>
constexpr quantity< decltype(std::declval< lvt >() *std::declval< st >()), ut > operator* (const st &factor, const quantity< lvt, ut > &rhs)
Multiplication and division with scalars.
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type>
constexpr quantity< decltype(std::declval< st >() *std::declval< lvt >()), ut > operator* (const quantity< lvt, ut > &lhs, const st &factor)
template<typename lvt , typename ut , typename st >
constexpr quantity< decltype(std::declval< st >() *std::declval< lvt >()), ut > multiply_any_unit (const quantity< lvt, ut > &lhs, const st &factor)
template<typename t , typename st >
constexpr decltype(std::declval< st >() *std::declval< t >()) multiply_any_unit (const t &lhs, const st &factor)
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<lvt>::value>::type>
void operator* (quantity< lvt, ut >, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type>
quantity< lvt, ut > & operator*= (quantity< lvt, ut > &lhs, const st &factor)
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<rvt>::value>::type>
constexpr quantity< decltype(std::declval< lvt >() *std::declval< rvt >()), ut > operator/ (const quantity< lvt, ut > &lhs, const rvt &divisor)
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<lvt>::value>::type>
void operator/ (lvt, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename rvt >
constexpr decltype(std::declval< lvt >()/std::declval< rvt >()) operator/ (const quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type>
quantity< lvt, ut > & operator/= (quantity< lvt, ut > &lhs, const st &divisor)
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<rvt>::value>::type>
constexpr quantity< decltype(std::declval< lvt >() % std::declval< rvt >()), ut > operator% (const quantity< lvt, ut > &lhs, const rvt &divisor)
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<lvt>::value>::type>
void operator% (lvt, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename rvt >
constexpr quantity< decltype(std::declval< lvt >() % std::declval< rvt >()), ut > operator% (const quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type>
quantity< lvt, ut > & operator%= (quantity< lvt, ut > &lhs, const st &divisor)
template<typename lvt , typename ut , typename rvt >
quantity< lvt, ut > & operator%= (quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
Variables
static const std::vector< std::pair< std::string, energy > > energy_units
static const std::vector< std::pair< std::string, mass > > mass_units
static const std::vector< std::pair< std::string, money > > money_units
static const std::vector< std::pair< std::string, volume > > volume_units
static const std::vector< std::pair< std::string, angle > > angle_units
static const std::vector< std::pair< std::string, temperature > > temperature_units
static const std::vector< std::pair< std::string, probability > > probability_units
const energy energy_min
const energy energy_max
constexpr mass mass_min
constexpr mass mass_max
const money money_min
const money money_max
const probability probability_min
const probability probability_max
const temperature temperature_min
const temperature temperature_max
const volume volume_min
const volume volume_max
static constexpr volume legacy_volume_factor = from_milliliter(250)
Typedef Documentation
angle
using units::angle = typedef quantity<double, angle_in_radians_tag>
Definition at line 17 of file units_angle.h.
energy
using units::energy = typedef quantity<int, energy_in_joule_tag>
Definition at line 16 of file units_energy.h.
mass
using units::mass = typedef quantity<std::int64_t, mass_in_milligram_tag>
Definition at line 22 of file units_mass.h.
money
using units::money = typedef quantity<int, money_in_cent_tag>
Definition at line 16 of file units_money.h.
probability
using units::probability = typedef quantity<int, probability_in_one_in_million_tag>
Definition at line 14 of file units_probability.h.
temperature
using units::temperature = typedef quantity<int, temperature_in_millidegree_celsius_tag>
Definition at line 61 of file units_temperature.h.
volume
using units::volume = typedef quantity<int, volume_in_milliliter_tag>
Definition at line 16 of file units_volume.h.
Function Documentation
atan2()
units::angle units::atan2 (double y, double x) inline
Definition at line 67 of file units_angle.h.
{
    return from_radians( std::atan2( y, x ) );
}
References atan2(), and from_radians().
Referenced by atan2(), atan2(), coord_to_angle(), cone_factory::create(), explosion_handler::do_blast_new(), vehicle::get_angle_from_targ(), and projectile_attack().
celsius_to_fahrenheit()
constexpr double units::celsius_to_fahrenheit (double celsius) constexpr
Convert a temperature from Celsius to degrees Fahrenheit.
Returns
Temperature in degrees F.
Definition at line 42 of file units_temperature.h.
{
    return celsius * 9 / 5 + 32;
}
Referenced by from_fahrenheit(), and to_fahrenheit().
celsius_to_kelvin()
constexpr double units::celsius_to_kelvin (double celsius) constexpr
Convert a temperature from Celsius to kelvins.
Returns
Temperature in degrees F.
Definition at line 52 of file units_temperature.h.
{
    return celsius + 273.15;
}
Referenced by to_kelvins().
cos()
double units::cos (angle a) inline
Definition at line 57 of file units_angle.h.
{
    return std::cos( to_radians( a ) );
}
References a, cos(), and to_radians().
Referenced by angle_to_vec(), map::apply_light_arc(), calc_ray_end(), cos(), get_common_data(), tileray::init(), iso_tangent(), vehicle::part_vpower_w(), projectile_attack(), rl_vec2d::rotated(), rl_vec3d::rotated(), matrices::rotation_z_axis(), teleport::teleport(), npc::vehicle_danger(), and weather_temperature_from_common_data().
display()
std::string units::display (const units::energy v)
Definition at line 59 of file units.cpp.
{
    const int kj = units::to_kilojoule( v );
    const int j = units::to_joule( v );
    // at least 1 kJ and there is no fraction
    if( kj >= 1 && float( j ) / kj == 1000 ) {
        return std::to_string( kj ) + ' ' + pgettext( "energy unit: kilojoule", "kJ" );
    }
    return std::to_string( j ) + ' ' + pgettext( "energy unit: joule", "J" );
}
References pgettext(), to_joule(), to_kilojoule(), and to_string().
Referenced by build_bionic_poweronly_string(), and game::phasing_move().
fabs()
template<typename V , typename U > quantity< V, U > units::fabs (quantity< V, U > q) inline
Definition at line 136 of file units_def.h.
{
    return quantity<V, U>( std::fabs( q.value() ), U{} );
}
References fabs(), and units::quantity< V, U >::value().
Referenced by Character::apply_wetness_morale(), Creature::auto_find_hostile_target(), game::calc_driving_offset(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), fabs(), vehicle::noise_and_smoke(), vehicle::part_collision(), vehicle::possibly_recover_from_skid(), mattack::shriek_stun(), and npc::wont_hit_friend().
fahrenheit_to_celsius()
constexpr double units::fahrenheit_to_celsius (double fahrenheit) constexpr
Definition at line 12 of file units_temperature.h.
{
    return ( ( fahrenheit - 32.0 ) * 5.0 / 9.0 );
}
Referenced by fahrenheit_to_kelvin(), from_fahrenheit(), local_windchill_hightemp(), and Character::update_bodytemp().
fahrenheit_to_kelvin()
constexpr double units::fahrenheit_to_kelvin (double fahrenheit) constexpr
Convert a temperature from degrees Fahrenheit to Kelvin.
Returns
Temperature in degrees K.
Definition at line 22 of file units_temperature.h.
{
    return fahrenheit_to_celsius( fahrenheit ) + 273.15;
}
References fahrenheit_to_celsius().
fmod()
template<typename V , typename U > quantity< V, U > units::fmod (quantity< V, U > num, quantity< V, U > den) inline
Definition at line 142 of file units_def.h.
{
    return quantity<V, U>( std::fmod( num.value(), den.value() ), U{} );
}
References fmod(), num, and units::quantity< V, U >::value().
Referenced by map::apply_light_arc(), VehicleSpawnFunction::builtin_jackknifed_semi(), calc_ray_end(), fmod(), vehicle::merge_rackable_vehicle(), and normalize().
from_arcmin()
template<typename value_type > constexpr quantity< double, angle_in_radians_tag > units::from_arcmin (const value_type v) inline constexpr
Definition at line 42 of file units_angle.h.
{
    return from_degrees( v / 60.0 );
}
References from_degrees().
Referenced by confidence_estimate(), ranged::fire_gun(), operator""_arcmin(), projectile_attack(), and projectile_attack_roll().
from_celsius()
template<typename value_type > constexpr quantity< value_type, temperature_in_millidegree_celsius_tag > units::from_celsius (const value_type v) inline constexpr
Definition at line 88 of file units_temperature.h.
{
    const value_type max_temperature_celsius = std::numeric_limits<value_type>::max() / 1000;
    const value_type temperature = v > max_temperature_celsius ? max_temperature_celsius : v;
    return from_millidegree_celsius<value_type>( temperature * 1000 );
}
Referenced by weather_generator::load(), maybe_temperature_reader(), and weather_temperature_from_common_data().
from_cent()
template<typename value_type > constexpr quantity< value_type, money_in_cent_tag > units::from_cent (const value_type v) inline constexpr
Definition at line 25 of file units_money.h.
{
    return quantity<value_type, money_in_cent_tag>( v, money_in_cent_tag{} );
}
Referenced by assign(), and operator""_cent().
from_degrees()
template<typename value_type > constexpr quantity< double, angle_in_radians_tag > units::from_degrees (const value_type v) inline constexpr
Definition at line 31 of file units_angle.h.
{
    return from_radians( v * M_PI / 180 );
}
References from_radians(), and M_PI.
Referenced by Creature::auto_find_hostile_target(), debug_menu::debug(), vehicle_part::deserialize(), vehicle::deserialize(), cone_factory::deserialize(), from_arcmin(), item::getlight(), vehicle_movement::is_on_rails(), jmapgen_vehicle::jmapgen_vehicle(), operator""_degrees(), vehicle::part_collision(), vehicle_movement::process_movement_on_rails(), vehicle::remove_carried_vehicle(), spell_effect::spell_effect_cone(), to_angle(), and VehicleFacings::VehicleFacings().
from_fahrenheit()
template<typename value_type > constexpr quantity< value_type, temperature_in_millidegree_celsius_tag > units::from_fahrenheit (const value_type v) inline constexpr
Definition at line 97 of file units_temperature.h.
{
    // Explicit casts to silence warnings about lossy conversions
    constexpr value_type max_temperature_fahrenheit = static_cast<value_type>( celsius_to_fahrenheit(
                // NOLINTNEXTLINE(bugprone-integer-division)
                static_cast<double>( std::numeric_limits<value_type>::max() / 1000 ) ) );
    const value_type temperature = v > max_temperature_fahrenheit ? max_temperature_fahrenheit : v;
    return from_millidegree_celsius<value_type>(
               static_cast<value_type>( fahrenheit_to_celsius( temperature ) * 1000 ) );
}
References celsius_to_fahrenheit(), and fahrenheit_to_celsius().
Referenced by print_temperature(), and item::process_rot().
from_gram()
template<typename value_type > constexpr quantity< value_type, mass_in_milligram_tag > units::from_gram (const value_type v) inline constexpr
Definition at line 40 of file units_mass.h.
{
    return from_milligram( v * 1000 );
}
References from_milligram().
Referenced by npc::drop_items(), from_kilogram(), inventory_selector::get_weight_and_volume_stats(), operator""_gram(), and item::weight().
from_joule()
template<typename value_type > constexpr quantity< value_type, energy_in_joule_tag > units::from_joule (const value_type v) inline constexpr
Definition at line 25 of file units_energy.h.
{
    return quantity<value_type, energy_in_joule_tag>( v, energy_in_joule_tag{} );
}
Referenced by Character::activate_mutation(), activity_handlers::operation_do_turn(), and operator""_J().
from_kilogram()
template<typename value_type > constexpr quantity< value_type, mass_in_milligram_tag > units::from_kilogram (const value_type v) inline constexpr
Definition at line 47 of file units_mass.h.
{
    return from_gram( v * 1000 );
}
References from_gram().
Referenced by Character::bodyweight(), from_newton(), and operator""_kilogram().
from_kilojoule()
template<typename value_type > constexpr quantity< value_type, energy_in_joule_tag > units::from_kilojoule (const value_type v) inline constexpr
Definition at line 32 of file units_energy.h.
{
    const value_type max_energy_joules = std::numeric_limits<value_type>::max() / 1000;
    value_type energy = v * 1000 > max_energy_joules ? max_energy_joules : v * 1000;
    return from_joule<value_type>( energy );
}
Referenced by Character::activate_bionic(), item::ammo_consume(), assign(), Character::bionics_install_failure(), Character::burn_fuel(), spell::can_cast(), comestible_inventory_preset::comestible_inventory_preset(), vehicle::consume_fuel(), explosion_handler::emp_blast(), Character::feed_furnace_with(), ranged::gunmode_checks_weapon(), hack_attempt(), Character::has_charges(), known_magic::has_enough_energy(), Character::modify_morale(), game::on_move_effects(), operator""_kJ(), Character::passive_power_gen(), spell_effect::recover_energy(), activity_handlers::spellcasting_finish(), Character::suffer_from_radiation(), Character::update_stamina(), and Character::use_charges().
from_kusd()
template<typename value_type > constexpr quantity< value_type, money_in_cent_tag > units::from_kusd (const value_type v) inline constexpr
Definition at line 38 of file units_money.h.
{
    return from_usd<value_type>( v * 1000 );
}
Referenced by operator""_kUSD().
from_liter()
template<typename value_type > constexpr quantity< value_type, volume_in_milliliter_tag > units::from_liter (const value_type v) inline constexpr
Definition at line 32 of file units_volume.h.
{
    return from_milliliter<value_type>( v * 1000 );
}
Referenced by npc::drop_items(), activity_handlers::fill_liquid_do_turn(), iexamine::fvat_empty(), iexamine::gaspump(), tutorial_game::post_action(), and npc::shop_restock().
from_millidegree_celsius()
template<typename value_type > constexpr quantity< value_type, temperature_in_millidegree_celsius_tag > units::from_millidegree_celsius (const value_type v) inline constexpr
Definition at line 80 of file units_temperature.h.
{
    return quantity<value_type, temperature_in_millidegree_celsius_tag>( v,
            temperature_in_millidegree_celsius_tag{} );
}
from_milligram()
template<typename value_type > constexpr quantity< value_type, mass_in_milligram_tag > units::from_milligram (const value_type v) inline constexpr
Definition at line 33 of file units_mass.h.
{
    return quantity<value_type, mass_in_milligram_tag>( v, mass_in_milligram_tag{} );
}
Referenced by from_gram(), operator""_milligram(), and item::weight().
from_milliliter()
template<typename value_type > constexpr quantity< value_type, volume_in_milliliter_tag > units::from_milliliter (const value_type v) inline constexpr
Definition at line 25 of file units_volume.h.
{
    return quantity<value_type, volume_in_milliliter_tag>( v, volume_in_milliliter_tag{} );
}
Referenced by vehicle_part::ammo_set(), assign(), Item_factory::finalize_pre(), item::get_encumber(), inventory_selector::get_weight_and_volume_stats(), operator""_liter(), operator""_ml(), and select_autopickup_items().
from_newton()
template<typename value_type > constexpr quantity< value_type, mass_in_milligram_tag > units::from_newton (const value_type v) inline constexpr
Definition at line 54 of file units_mass.h.
{
    return from_kilogram( v / GRAVITY_OF_EARTH );
}
References from_kilogram(), and GRAVITY_OF_EARTH.
Referenced by veh_interact::display_stats(), and operator""_newton().
from_one_in_million()
template<typename value_type > constexpr quantity< value_type, probability_in_one_in_million_tag > units::from_one_in_million (const value_type v) inline constexpr
Definition at line 26 of file units_probability.h.
{
    return quantity<value_type, probability_in_one_in_million_tag>( v,
            probability_in_one_in_million_tag{} );
}
Referenced by assign().
from_percent()
template<typename value_type > constexpr quantity< value_type, probability_in_one_in_million_tag > units::from_percent (const value_type v) inline constexpr
Definition at line 35 of file units_probability.h.
{
    return quantity<value_type, probability_in_one_in_million_tag>( 10000 * v,
            probability_in_one_in_million_tag{} );
}
Referenced by assign().
from_radians()
template<typename value_type > constexpr quantity< value_type, angle_in_radians_tag > units::from_radians (const value_type v) inline constexpr
Definition at line 20 of file units_angle.h.
{
    return quantity<value_type, angle_in_radians_tag>( v, angle_in_radians_tag{} );
}
Referenced by approx_orientation(), atan2(), from_degrees(), operator""_pi_radians(), and operator""_radians().
from_usd()
template<typename value_type > constexpr quantity< value_type, money_in_cent_tag > units::from_usd (const value_type v) inline constexpr
Definition at line 32 of file units_money.h.
{
    return from_cent<value_type>( v * 100 );
}
Referenced by operator""_USD().
kelvin_to_fahrenheit()
constexpr double units::kelvin_to_fahrenheit (double kelvin) constexpr
Convert a temperature from Kelvin to degrees Fahrenheit.
Returns
Temperature in degrees C.
Definition at line 32 of file units_temperature.h.
{
    return 1.8 * ( kelvin - 273.15 ) + 32;
}
multiply_any_unit() [1/2]
template<typename lvt , typename ut , typename st > constexpr quantity< decltype(std::declval< st >() *std::declval< lvt >()), ut > units::multiply_any_unit (const quantity< lvt, ut > & lhs, const st & factor) inline constexpr
Definition at line 211 of file units_def.h.
{
    return { lhs.value() *factor, ut{} };
}
References units::quantity< V, U >::value().
Referenced by weather_generator::get_water_temperature(), read_from_json_string(), and season_temp().
multiply_any_unit() [2/2]
template<typename t , typename st > constexpr decltype(std::declval< st >() *std::declval< t >()) units::multiply_any_unit (const t & lhs, const st & factor) inline constexpr
Definition at line 218 of file units_def.h.
{
    return lhs * factor;
}
operator%() [1/3]
template<typename lvt , typename ut , typename rvt > constexpr quantity< decltype(std::declval< lvt >() % std::declval< rvt >()), ut > units::operator% (const quantity< lvt, ut > & lhs, const quantity< rvt, ut > & rhs) inline constexpr
Definition at line 282 of file units_def.h.
{
    return { lhs.value() % rhs.value(), ut{} };
}
References units::quantity< V, U >::value().
operator%() [2/3]
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<rvt>::value>::type> constexpr quantity< decltype(std::declval< lvt >() % std::declval< rvt >()), ut > units::operator% (const quantity< lvt, ut > & lhs, const rvt & divisor) inline constexpr
Definition at line 270 of file units_def.h.
{
    return { lhs.value() % divisor, ut{} };
}
References units::quantity< V, U >::value().
operator%() [3/3]
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<lvt>::value>::type> void units::operator% (lvt , quantity< rvt, ut >) inline delete
operator%=() [1/2]
template<typename lvt , typename ut , typename rvt > quantity< lvt, ut > & units::operator%= (quantity< lvt, ut > & lhs, const quantity< rvt, ut > & rhs) inline
Definition at line 297 of file units_def.h.
{
    lhs = lhs % rhs;
    return lhs;
}
operator%=() [2/2]
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type> quantity< lvt, ut > & units::operator%= (quantity< lvt, ut > & lhs, const st & divisor) inline
Definition at line 290 of file units_def.h.
{
    lhs = lhs % divisor;
    return lhs;
}
operator*() [1/3]
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type> constexpr quantity< decltype(std::declval< st >() *std::declval< lvt >()), ut > units::operator* (const quantity< lvt, ut > & lhs, const st & factor) inline constexpr
Definition at line 201 of file units_def.h.
{
    static_assert( quantity_details<ut>::common_zero_point::value,
                   "Units with multiple scales with different zero should not be multiplied/divided/etc.  directly." );
    return { lhs.value() *factor, ut{} };
}
References units::quantity< V, U >::value().
operator*() [2/3]
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type> constexpr quantity< decltype(std::declval< lvt >() *std::declval< st >()), ut > units::operator* (const st & factor, const quantity< lvt, ut > & rhs) inline constexpr
Multiplication and division with scalars.
Result is a quantity with the same unit as the input. Functions are templated to allow scaling with different types:
quantity<int, foo> a{ 10, foo{} };
auto b = a * 4.52;
static_assert(std::is_same<decltype(b), quantity<double, foo>>::value);
Note that the result for *= and /= is calculated using the given types, but is implicitly converted back to value_type as it is stored in the operand.
quantity<int, foo> a{ 10, foo{} };
a *= 4.52;
assert(a == quantity<int, foo>(10 * 4.52, foo{}));
assert(a != quantity<int, foo>(10 * (int)4.52, foo{}));
assert(a == quantity<int, foo>(45, foo{}));
Division of a quantity with a quantity of the same unit yields a dimensionless scalar value, with the same type as the division of the contained value_types:
quantity<int, foo> a{ 10, foo{} };
quantity<double, foo> b{ 20, foo{} };
auto proportion = a / b;
static_assert(std::is_same<decltype(proportion), double>::value);
assert(proportion == 10 / 20.0);
Definition at line 191 of file units_def.h.
{
    static_assert( quantity_details<ut>::common_zero_point::value,
                   "Units with multiple scales with different zero should not be multiplied/divided/etc.  directly." );
    return { factor * rhs.value(), ut{} };
}
References units::quantity< V, U >::value().
Referenced by monster::get_volume(), and monster::get_weight().
operator*() [3/3]
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<lvt>::value>::type> void units::operator* (quantity< lvt, ut > , quantity< rvt, ut >) inline delete
operator*=()
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type> quantity< lvt, ut > & units::operator*= (quantity< lvt, ut > & lhs, const st & factor) inline
Definition at line 230 of file units_def.h.
{
    lhs = lhs * factor;
    return lhs;
}
operator/() [1/3]
template<typename lvt , typename ut , typename rvt > constexpr decltype(std::declval< lvt >()/std::declval< rvt >()) units::operator/ (const quantity< lvt, ut > & lhs, const quantity< rvt, ut > & rhs) inline constexpr
Definition at line 252 of file units_def.h.
{
    return lhs.value() / rhs.value();
}
References units::quantity< V, U >::value().
operator/() [2/3]
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<rvt>::value>::type> constexpr quantity< decltype(std::declval< lvt >() *std::declval< rvt >()), ut > units::operator/ (const quantity< lvt, ut > & lhs, const rvt & divisor) inline constexpr
Definition at line 240 of file units_def.h.
{
    return { lhs.value() / divisor, ut{} };
}
References units::quantity< V, U >::value().
operator/() [3/3]
template<typename lvt , typename ut , typename rvt , typename = typename std::enable_if<std::is_arithmetic<lvt>::value>::type> void units::operator/ (lvt , quantity< rvt, ut >) inline delete
operator/=()
template<typename lvt , typename ut , typename st , typename = typename std::enable_if<std::is_arithmetic<st>::value>::type> quantity< lvt, ut > & units::operator/= (quantity< lvt, ut > & lhs, const st & divisor) inline
Definition at line 260 of file units_def.h.
{
    lhs = lhs / divisor;
    return lhs;
}
operator<<() [1/8]
std::ostream & units::operator<< (std::ostream & o, angle_in_radians_tag) inline
Definition at line 47 of file units.h.
{
    return o << "rad";
}
operator<<() [2/8]
template<typename value_type , typename tag_type > std::ostream & units::operator<< (std::ostream & o, const quantity< value_type, tag_type > & v) inline
Definition at line 63 of file units.h.
{
    return o << v.value() << tag_type{};
}
References units::quantity< V, U >::value().
operator<<() [3/8]
std::ostream & units::operator<< (std::ostream & o, energy_in_joule_tag) inline
Definition at line 37 of file units.h.
{
    return o << "J";
}
operator<<() [4/8]
std::ostream & units::operator<< (std::ostream & o, mass_in_milligram_tag) inline
Definition at line 27 of file units.h.
{
    return o << "mg";
}
operator<<() [5/8]
std::ostream & units::operator<< (std::ostream & o, money_in_cent_tag) inline
Definition at line 42 of file units.h.
{
    return o << "cent";
}
operator<<() [6/8]
std::ostream & units::operator<< (std::ostream & o, probability_in_one_in_million_tag) inline
Definition at line 57 of file units.h.
{
    return o << "pm";
}
operator<<() [7/8]
std::ostream & units::operator<< (std::ostream & o, temperature_in_millidegree_celsius_tag) inline
Definition at line 52 of file units.h.
{
    return o << "mC";
}
operator<<() [8/8]
std::ostream & units::operator<< (std::ostream & o, volume_in_milliliter_tag) inline
Definition at line 32 of file units.h.
{
    return o << "ml";
}
sin()
double units::sin (angle a) inline
Definition at line 52 of file units_angle.h.
{
    return std::sin( to_radians( a ) );
}
References a, sin(), and to_radians().
Referenced by angle_to_vec(), map::apply_light_arc(), calc_ray_end(), tileray::init(), vehicle::part_vpower_w(), projectile_attack(), rl_vec2d::rotated(), rl_vec3d::rotated(), matrices::rotation_z_axis(), sin(), vehicle::slowdown(), teleport::teleport(), and npc::vehicle_danger().
tan()
double units::tan (angle a) inline
Definition at line 62 of file units_angle.h.
{
    return std::tan( to_radians( a ) );
}
References a, tan(), and to_radians().
Referenced by calc_ray_end(), and tan().
to_arcmin()
constexpr double units::to_arcmin (const units::angle v) inline constexpr
Definition at line 47 of file units_angle.h.
{
    return to_degrees( v ) * 60;
}
References to_degrees().
to_celsius()
template<typename value_type > constexpr value_type units::to_celsius (const quantity< value_type, temperature_in_millidegree_celsius_tag > & v) inline constexpr
Definition at line 117 of file units_temperature.h.
{
    return to_millidegree_celsius( v ) / 1000.0;
}
References to_millidegree_celsius().
to_cent()
template<typename value_type > constexpr value_type units::to_cent (const quantity< value_type, money_in_cent_tag > & v) inline constexpr
Definition at line 44 of file units_money.h.
{
    return v / from_cent<value_type>( 1 );
}
Referenced by item::price(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), and to_usd().
to_degrees()
constexpr double units::to_degrees (const units::angle v) inline constexpr
Definition at line 36 of file units_angle.h.
{
    return to_radians( v ) * 180 / M_PI;
}
References M_PI, and to_radians().
Referenced by map::add_vehicle(), vehicle::angle_to_increment(), VehicleSpawnFunction::builtin_jackknifed_semi(), cone_factory::get_description(), vehicle_movement::is_on_rails(), vehicle::merge_rackable_vehicle(), vehicle_movement::process_movement_on_rails(), target_ui::recalc_aim_turning_penalty(), vehicle::remove_carried_vehicle(), vehicle_part::serialize(), vehicle::serialize(), cone_factory::serialize(), to_arcmin(), to_orientation(), and tileray::to_string_azimuth_from_north().
to_fahrenheit()
template<typename value_type > constexpr value_type units::to_fahrenheit (const quantity< value_type, temperature_in_millidegree_celsius_tag > & v) inline constexpr
Definition at line 124 of file units_temperature.h.
{
    return celsius_to_fahrenheit( to_millidegree_celsius( v ) / 1000.0 );
}
References celsius_to_fahrenheit(), and to_millidegree_celsius().
Referenced by Character::activate_bionic(), calc_hourly_rotpoints_at_temp(), weather_manager::get_temperature(), weather_generator::get_weather_conditions(), temperature_flag_to_highest_temperature(), character_funcs::update_body_wetness(), weather_manager::update_weather(), and iuse::weather_tool().
to_gram()
template<typename value_type > constexpr value_type units::to_gram (const quantity< value_type, mass_in_milligram_tag > & v) inline constexpr
Definition at line 67 of file units_mass.h.
{
    return v.value() / 1000.0;
}
References units::quantity< V, U >::value().
Referenced by butchery_drops_harvest(), convert_weight(), pickup::cost_to_move_item(), explosion_handler::do_blast_new(), game::dump_stats(), funnel_charges_per_turn(), mtype::get_meat_chunks_count(), inventory_selector::get_weight_and_volume_stats(), item::lift_strength(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), mdeath::splatter(), and ranged::throwing_dispersion().
to_joule()
template<typename value_type > constexpr value_type units::to_joule (const quantity< value_type, energy_in_joule_tag > & v) inline constexpr
Definition at line 40 of file units_energy.h.
{
    return v / from_joule<value_type>( 1 );
}
Referenced by item::battery_info(), item::bionic_info(), display(), item::display_name(), draw_bionics_titlebar(), Character::install_bionics(), power_stat(), Character::store(), and to_kilojoule().
to_kelvins()
template<typename value_type > constexpr value_type units::to_kelvins (const quantity< value_type, temperature_in_millidegree_celsius_tag > & v) inline constexpr
Definition at line 131 of file units_temperature.h.
{
    return celsius_to_kelvin( to_millidegree_celsius( v ) / 1000.0 );
}
References celsius_to_kelvin(), and to_millidegree_celsius().
to_kilogram()
template<typename value_type > constexpr value_type units::to_kilogram (const quantity< value_type, mass_in_milligram_tag > & v) inline constexpr
Definition at line 73 of file units_mass.h.
{
    return v.value() / 1000000.0;
}
References units::quantity< V, U >::value().
Referenced by vehicle::coeff_rolling_drag(), vehicle::coeff_water_drag(), npc::drop_items(), vehicle::ground_acceleration(), vehicle::k_traction(), map::move_vehicle(), vehicle::part_collision(), vehicle::rotor_acceleration(), map::shake_vehicle(), vehicle::slowdown(), to_newton(), map::vehicle_vehicle_collision(), and vehicle::water_acceleration().
to_kilojoule()
template<typename value_type > constexpr value_type units::to_kilojoule (const quantity< value_type, energy_in_joule_tag > & v) inline constexpr
Definition at line 46 of file units_energy.h.
{
    return to_joule( v ) / 1000.0;
}
References to_joule().
Referenced by Character::absorb_hit(), Character::activate_bionic(), Character::add_bionic(), item::ammo_consume(), item::ammo_remaining(), assign(), item::battery_info(), Character::bionics_install_failure(), Character::crafting_inventory(), display(), draw_bionics_tab(), draw_bionics_titlebar(), explosion_handler::emp_blast(), spell::energy_cur_string(), Character::feed_furnace_with(), Character::find_remote_fuel(), hack_attempt(), diary::max_power_level_changes(), power_stat(), Character::process_items(), Character::store(), Character::uninstall_bionic(), Character::update_stamina(), Character::use_charges(), and memorial_logger::write().
to_kusd()
template<typename value_type > constexpr value_type units::to_kusd (const quantity< value_type, money_in_cent_tag > & v) inline constexpr
Definition at line 56 of file units_money.h.
{
    return to_usd( v ) / 1000.0;
}
References to_usd().
to_liter()
constexpr double units::to_liter (const volume & v) inline constexpr
Definition at line 43 of file units_volume.h.
{
    return v.value() / 1000.0;
}
References units::quantity< V, U >::value().
Referenced by mattack::absorb_meat(), veh_interact::calc_overview(), npc::drop_items(), get_charcoal_charges(), Character::pour_into(), vehicle::print_part_list(), and item::simulate_burn().
to_millidegree_celsius()
template<typename value_type > constexpr value_type units::to_millidegree_celsius (const quantity< value_type, temperature_in_millidegree_celsius_tag > & v) inline constexpr
Definition at line 110 of file units_temperature.h.
{
    return v / from_millidegree_celsius<value_type>( 1 );
}
Referenced by weather_generator::get_water_temperature(), to_celsius(), to_fahrenheit(), and to_kelvins().
to_milligram()
template<typename value_type > constexpr value_type units::to_milligram (const quantity< value_type, mass_in_milligram_tag > & v) inline constexpr
Definition at line 61 of file units_mass.h.
{
    return v.value();
}
References units::quantity< V, U >::value().
Referenced by item::contain_monster(), and vehicle::fold_up().
to_milliliter()
template<typename value_type > constexpr value_type units::to_milliliter (const quantity< value_type, volume_in_milliliter_tag > & v) inline constexpr
Definition at line 38 of file units_volume.h.
{
    return v / from_milliliter<value_type>( 1 );
}
Referenced by carry_volume_string(), inventory_selector::get_weight_and_volume_stats(), vehicle::init_state(), move_cost_cart(), move_cost_inv(), ranged::throw_item(), ranged::throwing_dispersion(), and item::weight().
to_newton()
template<typename value_type > constexpr value_type units::to_newton (const quantity< value_type, mass_in_milligram_tag > & v) inline constexpr
Definition at line 79 of file units_mass.h.
{
    return to_kilogram( v ) * GRAVITY_OF_EARTH;
}
References GRAVITY_OF_EARTH, and to_kilogram().
Referenced by vehicle::has_sufficient_rotorlift().
to_one_in_million()
template<typename value_type > constexpr value_type units::to_one_in_million (const quantity< value_type, probability_in_one_in_million_tag > & v) inline constexpr
Definition at line 43 of file units_probability.h.
{
    return v / from_one_in_million<value_type>( 1 );
}
Referenced by check().
to_radians()
constexpr double units::to_radians (const units::angle v) inline constexpr
Definition at line 25 of file units_angle.h.
{
    return v.value();
}
References units::quantity< V, U >::value().
Referenced by cos(), ranged::fire_gun(), sin(), tan(), and to_degrees().
to_usd()
template<typename value_type > constexpr value_type units::to_usd (const quantity< value_type, money_in_cent_tag > & v) inline constexpr
Definition at line 50 of file units_money.h.
{
    return to_cent( v ) / 100.0;
}
References to_cent().
Referenced by to_kusd().
Variable Documentation
angle_units
const std::vector<std::pair<std::string, angle> > units::angle_units static
Initial value:
= { {
        { "arcmin", 1_arcmin },
        { "", 1_degrees },
        { "rad", 1_radians },
    }
}
Definition at line 97 of file units.h.
energy_max
const energy units::energy_max
Initial value:
= units::energy(std::numeric_limits<units::energy::value_type>::max(),
                          units::energy::unit_type{} )
Definition at line 21 of file units_energy.h.
Referenced by assign(), install_bionic_actor::can_use(), and bionic_install_preset::get_denial().
energy_min
const energy units::energy_min
Initial value:
= units::energy(std::numeric_limits<units::energy::value_type>::min(),
                          units::energy::unit_type{} )
Definition at line 18 of file units_energy.h.
energy_units
const std::vector<std::pair<std::string, energy> > units::energy_units static
Initial value:
= { {
        { "mJ", 1_J },
        { "J", 1_J },
        { "kJ", 1_kJ },
    }
}
Definition at line 74 of file units.h.
Referenced by assign(), units::quantity< V, U >::deserialize(), and Item_factory::load().
legacy_volume_factor
constexpr volume units::legacy_volume_factor = from_milliliter(250) static constexpr
Definition at line 50 of file units_volume.h.
Referenced by vehicle_part::ammo_set(), assign(), item::burn(), veh_interact::calc_overview(), iexamine::cvdmachine(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), game::dump_stats(), item::flammable(), vehicle::fold_up(), item::get_storage(), vehicle::init_state(), inventory::leak_level(), legacy_volume_reader(), item::on_wield(), vehicle::operate_scoop(), Character::pour_into(), vehicle::print_part_list(), item::process_corpse(), activity_handlers::pulp_do_turn(), select_autopickup_items(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), smash(), vehicle::update_time(), and item::volume().
mass_max
constexpr mass units::mass_max constexpr
Initial value:
= units::mass(std::numeric_limits<units::mass::value_type>::max(),
                                       units::mass::unit_type{} )
Definition at line 27 of file units_mass.h.
Referenced by Character::can_pick_weight(), advanced_inventory::query_charges(), and Character::weight_capacity().
mass_min
constexpr mass units::mass_min constexpr
Initial value:
= units::mass(std::numeric_limits<units::mass::value_type>::min(),
                                       units::mass::unit_type{} )
Definition at line 24 of file units_mass.h.
mass_units
const std::vector<std::pair<std::string, mass> > units::mass_units static
Initial value:
= { {
        { "mg", 1_milligram },
        { "g", 1_gram },
        { "kg", 1_kilogram },
    }
}
Definition at line 80 of file units.h.
Referenced by assign().
money_max
const money units::money_max
Initial value:
= units::money(std::numeric_limits<units::money::value_type>::max(),
                                      units::money::unit_type{} )
Definition at line 21 of file units_money.h.
money_min
const money units::money_min
Initial value:
= units::money(std::numeric_limits<units::money::value_type>::min(),
                                      units::money::unit_type{} )
Definition at line 18 of file units_money.h.
money_units
const std::vector<std::pair<std::string, money> > units::money_units static
Initial value:
= { {
        { "cent", 1_cent },
        { "USD", 1_USD },
        { "kUSD", 1_kUSD },
    }
}
Definition at line 86 of file units.h.
Referenced by assign().
probability_max
const probability units::probability_max
Initial value:
= units::probability(
                                        1000000,
                                        units::probability::unit_type{} )
Definition at line 20 of file units_probability.h.
probability_min
const probability units::probability_min
Initial value:
= units::probability(
                                        0,
                                        units::probability::unit_type{} )
Definition at line 16 of file units_probability.h.
probability_units
const std::vector<std::pair<std::string, probability> > units::probability_units static
Initial value:
= { {
        { "pm", 1_pm },
        { "pct", 1_pct },
        { "%", 1_pct }
    }
}
Definition at line 110 of file units.h.
temperature_max
const temperature units::temperature_max
Initial value:
= units::temperature(
                                        std::numeric_limits<units::temperature::value_type>::max(),
                                        units::temperature::unit_type{} )
Definition at line 74 of file units_temperature.h.
temperature_min
const temperature units::temperature_min
Initial value:
= units::temperature(
                                        std::numeric_limits<units::temperature::value_type>::min(),
                                        units::temperature::unit_type{} )
Definition at line 70 of file units_temperature.h.
temperature_units
const std::vector<std::pair<std::string, temperature> > units::temperature_units static
Initial value:
= { {
        { "mC", 1_mc },
        { "C", 1_c },
    }
}
Definition at line 103 of file units.h.
Referenced by assign().
volume_max
const volume units::volume_max
Initial value:
= units::volume(std::numeric_limits<units::volume::value_type>::max(),
                          units::volume::unit_type{} )
Definition at line 21 of file units_volume.h.
Referenced by Character::volume_capacity_reduced_by().
volume_min
const volume units::volume_min
Initial value:
= units::volume(std::numeric_limits<units::volume::value_type>::min(),
                          units::volume::unit_type{} )
Definition at line 18 of file units_volume.h.
volume_units
const std::vector<std::pair<std::string, volume> > units::volume_units static
Initial value:
= { {
        { "ml", 1_ml },
        { "L", 1_liter }
    }
}
Definition at line 92 of file units.h.