Cataclysm BN: anonymous_namespace{magic_enchantment.cpp} Namespace Reference
anonymous_namespace{magic_enchantment.cpp} Namespace Reference
Functions
template<float mutation_branch::* First>
bool is_set_value (const trait_id &mut, float val)
template<float mutation_branch::* First, float mutation_branch::*... Rest, typename std::enable_if<(sizeof...(Rest) > 0), bool >::type NonEmpty = false>
bool is_set_value (const trait_id &mut, float val)
Variables
generic_factory< enchantment > enchant_factory ("enchantment")
Function Documentation
is_set_value() [1/2]
template<float mutation_branch::* First> bool anonymous_namespace{magic_enchantment.cpp}::is_set_value (const trait_id & mut, float val)
Definition at line 552 of file magic_enchantment.cpp.
{
    return ( *mut ).*First == val;
}
is_set_value() [2/2]
template<float mutation_branch::* First, float mutation_branch::*... Rest, typename std::enable_if<(sizeof...(Rest) > 0), bool >::type NonEmpty = false> bool anonymous_namespace{magic_enchantment.cpp}::is_set_value (const trait_id & mut, float val)
Definition at line 559 of file magic_enchantment.cpp.
{
    return ( *mut ).*First == val && is_set_value<Rest...>( mut, val );
}
Variable Documentation
enchant_factory
generic_factory< enchantment > anonymous_namespace{magic_enchantment.cpp}::enchant_factory("enchantment") ("enchantment")
Referenced by enchantment::check_consistency(), enchantment::load_enchantment(), and enchantment::reset().