Cataclysm BN: char_creation Namespace Reference
char_creation Namespace Reference
Enumerations
enum description_selector { NAME , HEIGHT , AGE }
Functions
static void draw_height (const catacurses::window &w_height, const avatar &you, const bool highlight)
static void draw_age (const catacurses::window &w_age, const avatar &you, const bool highlight)
Enumeration Type Documentation
description_selector
enum char_creation::description_selector
Enumerator
NAME
HEIGHT
AGE
Definition at line 2351 of file newcharacter.cpp.
{
    NAME,
    HEIGHT,
    AGE
};
Function Documentation
draw_age()
static void char_creation::draw_age (const catacurses::window & w_age, const avatar & you, const bool highlight) static
Definition at line 2368 of file newcharacter.cpp.
{
    werase( w_age );
    mvwprintz( w_age, point_zero, highlight ? h_light_gray : c_light_gray, _( "Age:" ) );
    unsigned age_pos = 1 + utf8_width( _( "Age:" ) );
    mvwprintz( w_age, point( age_pos, 0 ), c_white, string_format( "%d", you.base_age() ) );
    wnoutrefresh( w_age );
}
References _, Character::base_age(), c_light_gray, c_white, h_light_gray, mvwprintz(), point_zero, string_format(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_height()
static void char_creation::draw_height (const catacurses::window & w_height, const avatar & you, const bool highlight) static
Definition at line 2357 of file newcharacter.cpp.
{
    werase( w_height );
    mvwprintz( w_height, point_zero, highlight ? h_light_gray : c_light_gray, _( "Height:" ) );
    unsigned height_pos = 1 + utf8_width( _( "Height:" ) );
    mvwprintz( w_height, point( height_pos, 0 ), c_white, string_format( "%d cm",
               you.base_height() ) );
    wnoutrefresh( w_height );
}
References _, Character::base_height(), c_light_gray, c_white, h_light_gray, mvwprintz(), point_zero, string_format(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().