Cataclysm BN: avatar_funcs Namespace Reference
avatar_funcs Namespace Reference
Functions
void try_to_sleep (avatar &you, const time_duration &dur=30_minutes)
Handles sleep attempts by the player, starts ACT_TRY_SLEEP activity.
void mend_item (avatar &you, item_location &&obj, bool interactive=true)
Attempt to start an activity to mend an item (fix any current faults)
static bool has_mod (const item &gun, const item &mod)
void gunmod_add (avatar &you, item &gun, item &mod)
Starts activity to install gunmod having warned user about any risk of failure or irremovable mods.
bool gunmod_remove (avatar &you, item &gun, item &mod)
Removes gunmod after first unloading any contained ammo and returns true on success.
std::pair< int, int > gunmod_installation_odds (const avatar &you, const item &gun, const item &mod)
Returns odds for success (pair.first) and gunmod damage (pair.second)
void toolmod_add (avatar &you, item_location tool, item_location mod)
Starts activity to install toolmod.
static bool is_pet_food (const item &itm)
void use_item (avatar &you, item_location loc)
Use a tool at given location.
static bool add_or_drop_with_msg (avatar &you, item &it, bool unloading)
bool unload_item (avatar &you, item_location loc)
Unload an item at given location.
std::vector< npc * > list_potential_theft_witnesses (avatar &you, const faction_id &owners)
List potential theft witnesses.
bool handle_theft_witnesses (avatar &you, const faction_id &owners)
Handle NPCs witnessing theft of their stuff.
void try_disarm_npc (avatar &you, npc &target)
Try to disarm the NPC.
void try_steal_from_npc (avatar &you, npc &target)
Try to steal an item from the NPC's inventory.
Function Documentation
add_or_drop_with_msg()
static bool avatar_funcs::add_or_drop_with_msg (avatar & you, item & it, bool unloading) static
Definition at line 610 of file avatar_functions.cpp.
{
    if( it.made_of( LIQUID ) ) {
        liquid_handler::consume_liquid( it, 1 );
        return it.charges <= 0;
    }
    it.charges = you.i_add_to_container( it, unloading );
    if( it.is_ammo() && it.charges == 0 ) {
        return true;
    } else if( !you.can_pick_volume( it ) ) {
        put_into_vehicle_or_drop( you, item_drop_reason::too_large, { it } );
    } else if( !you.can_pick_weight( it, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
        put_into_vehicle_or_drop( you, item_drop_reason::too_heavy, { it } );
    } else {
        auto &ni = you.i_add( it );
        add_msg( _( "You put the %s in your inventory." ), ni.tname() );
        add_msg( m_info, "%c - %s", ni.invlet == 0 ? ' ' : ni.invlet, ni.tname() );
    }
    return true;
}
References _, add_msg(), Character::can_pick_volume(), Character::can_pick_weight(), item::charges, liquid_handler::consume_liquid(), Character::i_add(), Character::i_add_to_container(), item::is_ammo(), LIQUID, m_info, item::made_of(), put_into_vehicle_or_drop(), too_heavy, and too_large.
Referenced by unload_item().
gunmod_add()
void avatar_funcs::gunmod_add (avatar & you, item & gun, item & mod)
Starts activity to install gunmod having warned user about any risk of failure or irremovable mods.
Definition at line 340 of file avatar_functions.cpp.
{
    if( !gun.is_gunmod_compatible( mod ).success() ) {
        debugmsg( "Tried to add incompatible gunmod" );
        return;
    }
    if( !you.has_item( gun ) && !you.has_item( mod ) ) {
        debugmsg( "Tried gunmod installation but mod/gun not in player possession" );
        return;
    }
    // first check at least the minimum requirements are met
    if( !you.has_trait( trait_DEBUG_HS ) && !you.can_use( mod, gun ) ) {
        return;
    }
    // any (optional) tool charges that are used during installation
    auto odds = gunmod_installation_odds( you, gun, mod );
    int roll = odds.first;
    int risk = odds.second;
    std::string tool;
    int qty = 0;
    bool requery = false;
    item modded = gun;
    modded.put_in( mod );
    bool no_magazines = modded.common_ammo_default().is_null();
    std::string query_msg = mod.is_irremovable()
                            ? _( "<color_yellow>Permanently</color> install your %1$s in your %2$s?" )
                            : _( "Attach your %1$s to your %2$s?" );
    if( no_magazines ) {
        query_msg += "\n";
        query_msg += colorize(
                         _( "Warning: after installing this mod, a magazine adapter mod will be required to load it!" ),
                         c_red );
    }
    uilist prompt;
    prompt.text = string_format( query_msg,
                                 colorize( mod.tname(), mod.color_in_inventory() ),
                                 colorize( gun.tname(), gun.color_in_inventory() ) );
    std::vector<std::function<void()>> actions;
    if( roll < 100 ) {
        prompt.addentry( -1, true, 'w',
                         string_format( _( "Try without tools (%i%%) risking damage (%i%%)" ), roll, risk ) );
        actions.emplace_back( [&] {} );
        prompt.addentry( -1, you.has_charges( itype_small_repairkit, 100 ), 'f',
                         string_format( _( "Use 100 charges of firearm repair kit (%i%%)" ), std::min( roll * 2, 100 ) ) );
        actions.emplace_back( [&] {
            tool = "small_repairkit";
            qty = 100;
            roll *= 2; // firearm repair kit improves success...
            risk /= 2; // ...and reduces the risk of damage upon failure
        } );
        prompt.addentry( -1, you.has_charges( itype_large_repairkit, 25 ), 'g',
                         string_format( _( "Use 25 charges of gunsmith repair kit (%i%%)" ), std::min( roll * 3, 100 ) ) );
        actions.emplace_back( [&] {
            tool = "large_repairkit";
            qty = 25;
            roll *= 3; // gunsmith repair kit improves success markedly...
            risk = 0;  // ...and entirely prevents damage upon failure
        } );
    } else {
        prompt.addentry( -1, true, 'w', _( "Install without tools" ) );
        actions.emplace_back( [&] {} );
    }
    prompt.addentry( -1, true, 'c', _( "Compare before/after installation" ) );
    actions.emplace_back( [&] {
        requery = true;
        game_menus::inv::compare( gun, modded );
    } );
    do {
        requery = false;
        prompt.query();
        if( prompt.ret < 0 ) {
            you.add_msg_if_player( _( "Never mind." ) );
            return; // player canceled installation
        }
        actions[ prompt.ret ]();
    } while( requery );
    const int moves = !you.has_trait( trait_DEBUG_HS ) ? mod.type->gunmod->install_time : 0;
    you.assign_activity( activity_id( "ACT_GUNMOD_ADD" ), moves, -1, 0, tool );
    you.activity.targets.push_back( item_location( you, &gun ) );
    you.activity.targets.push_back( item_location( you, &mod ) );
    you.activity.values.push_back( 0 ); // dummy value
    you.activity.values.push_back( roll ); // chance of success (%)
    you.activity.values.push_back( risk ); // chance of damage (%)
    you.activity.values.push_back( qty ); // tool charges
}
References _, Character::activity, player::add_msg_if_player(), Character::assign_activity(), c_red, Character::can_use(), item::color_in_inventory(), colorize(), item::common_ammo_default(), game_menus::inv::compare(), debugmsg, gunmod_installation_odds(), Character::has_charges(), visitable< T >::has_item(), Character::has_trait(), item::is_gunmod_compatible(), string_id< T >::is_null(), itype_large_repairkit, itype_small_repairkit, pickup::prompt, item::put_in(), string_format(), player_activity::targets, item::tname(), tool, trait_DEBUG_HS, and player_activity::values.
Referenced by iuse::gunmod_attach().
gunmod_installation_odds()
std::pair< int, int > avatar_funcs::gunmod_installation_odds (const avatar & you, const item & gun, const item & mod)
Returns odds for success (pair.first) and gunmod damage (pair.second)
Definition at line 496 of file avatar_functions.cpp.
{
    // Mods with INSTALL_DIFFICULT have a chance to fail, potentially damaging the gun
    if( !mod.has_flag( "INSTALL_DIFFICULT" ) || you.has_trait( trait_DEBUG_HS ) ) {
        return std::make_pair( 100, 0 );
    }
    int roll = 100; // chance of success (%)
    int risk = 0;   // chance of failure (%)
    int chances = 1; // start with 1 in 6 (~17% chance)
    for( const auto &e : mod.type->min_skills ) {
        // gain an additional chance for every level above the minimum requirement
        skill_id sk = e.first == skill_weapon ? gun.gun_skill() : e.first;
        chances += std::max( you.get_skill_level( sk ) - e.second, 0 );
    }
    // cap success from skill alone to 1 in 5 (~83% chance)
    roll = std::min( static_cast<double>( chances ), 5.0 ) / 6.0 * 100;
    // focus is either a penalty or bonus of at most +/-10%
    roll += ( std::max( std::min( you.focus_pool, 140 ), 60 ) - 100 ) / 4;
    // dexterity and intelligence give +/-2% for each point above or below 12
    roll += ( you.get_dex() - 12 ) * 2;
    roll += ( you.get_int() - 12 ) * 2;
    // each level of damage to the base gun reduces success by 10%
    roll -= std::max( gun.damage_level( 4 ), 0 ) * 10;
    roll = std::min( std::max( roll, 0 ), 100 );
    // risk of causing damage on failure increases with less durable guns
    risk = ( 100 - roll ) * ( ( 10.0 - std::min( gun.type->gun->durability, 9 ) ) / 10.0 );
    return std::make_pair( roll, risk );
}
References item::damage_level(), Character::focus_pool, Character::get_dex(), Character::get_int(), Character::get_skill_level(), itype::gun, item::gun_skill(), Character::has_trait(), skill_weapon, trait_DEBUG_HS, and item::type.
Referenced by gunmod_inventory_preset::get_odds(), and gunmod_add().
gunmod_remove()
bool avatar_funcs::gunmod_remove (avatar & you, item & gun, item & mod)
Removes gunmod after first unloading any contained ammo and returns true on success.
Definition at line 443 of file avatar_functions.cpp.
{
    if( !has_mod( gun, mod ) ) {
        debugmsg( "Cannot remove non-existent gunmod" );
        return false;
    }
    item_location loc = item_location( you, &mod );
    if( mod.ammo_remaining() && !avatar_funcs::unload_item( you, loc ) ) {
        return false;
    }
    gun.gun_set_mode( gun_mode_id( "DEFAULT" ) );
    //TODO: add activity for removing gunmods
    if( mod.typeId() == itype_brass_catcher ) {
        gun.casings_handle( [&]( item & e ) {
            return you.i_add_or_drop( e );
        } );
    }
    const itype *modtype = mod.type;
    you.i_add_or_drop( mod );
    gun.remove_item( mod );
    //If the removed gunmod added mod locations, check to see if any mods are in invalid locations
    if( !modtype->gunmod->add_mod.empty() ) {
        std::map<gunmod_location, int> mod_locations = gun.get_mod_locations();
        for( const auto &slot : mod_locations ) {
            int free_slots = gun.get_free_mod_locations( slot.first );
            for( auto the_mod : gun.gunmods() ) {
                if( the_mod->type->gunmod->location == slot.first && free_slots < 0 ) {
                    gunmod_remove( you, gun, *the_mod );
                    free_slots++;
                } else if( mod_locations.find( the_mod->type->gunmod->location ) ==
                           mod_locations.end() ) {
                    gunmod_remove( you, gun, *the_mod );
                }
            }
        }
    }
    you.add_msg_if_player(
        //~ %1$s - gunmod, %2$s - gun.
        _( "You remove your %1$s from your %2$s." ),
        modtype->nname( 1 ), gun.tname()
    );
    return true;
}
References _, player::add_msg_if_player(), item::casings_handle(), debugmsg, item::get_free_mod_locations(), item::get_mod_locations(), item::gun_set_mode(), itype::gunmod, gunmod_remove(), item::gunmods(), has_mod(), Character::i_add_or_drop(), itype_brass_catcher, itype::nname(), visitable< T >::remove_item(), item::tname(), and unload_item().
Referenced by gunmod_remove(), and detach_gunmods_actor::use().
handle_theft_witnesses()
bool avatar_funcs::handle_theft_witnesses (avatar & you, const faction_id & owners)
Handle NPCs witnessing theft of their stuff.
Parameters
you The dirty thief
owners Object owners
Returns
Whether there were any witnesses
Definition at line 828 of file avatar_functions.cpp.
{
    std::vector<npc *> witnesses = list_potential_theft_witnesses( you, owners );
    for( npc *guy : witnesses ) {
        guy->say( "<witnessed_thievery>", 7 );
    }
    if( !witnesses.empty() ) {
        if( you.add_faction_warning( owners ) ) {
            for( npc *guy : witnesses ) {
                guy->make_angry();
            }
        }
        return true;
    } else {
        return false;
    }
}
References avatar::add_faction_warning(), and list_potential_theft_witnesses().
Referenced by vehicle::handle_potential_theft(), prompt_disassemble_in_seq(), and query_consume_ownership().
has_mod()
static bool avatar_funcs::has_mod (const item & gun, const item & mod) static
Definition at line 330 of file avatar_functions.cpp.
{
    for( const item *toolmod : gun.gunmods() ) {
        if( &mod == toolmod ) {
            return true;
        }
    }
    return false;
}
References item::gunmods().
Referenced by gunmod_remove().
is_pet_food()
static bool avatar_funcs::is_pet_food (const item & itm) static
Definition at line 553 of file avatar_functions.cpp.
{
    return itm.type->can_use( "DOGFOOD" ) ||
           itm.type->can_use( "CATFOOD" ) ||
           itm.type->can_use( "BIRDFOOD" ) ||
           itm.type->can_use( "CATTLEFODDER" );
}
References itype::can_use(), and item::type.
Referenced by use_item().
list_potential_theft_witnesses()
std::vector< npc * > avatar_funcs::list_potential_theft_witnesses (avatar & you, const faction_id & owners)
List potential theft witnesses.
Definition at line 812 of file avatar_functions.cpp.
{
    std::vector<npc *> witnesses;
    for( npc &guy : g->all_npcs() ) {
        // Only owners care about theft of their property
        if( guy.get_faction() &&
            guy.get_faction()->id == owners &&
            rl_dist( guy.pos(), you.pos() ) < MAX_VIEW_DISTANCE &&
            guy.sees( you.pos() )
          ) {
            witnesses.push_back( &guy );
        }
    }
    return witnesses;
}
References g, MAX_VIEW_DISTANCE, Character::pos(), and rl_dist().
Referenced by vehicle::handle_potential_theft(), and handle_theft_witnesses().
mend_item()
void avatar_funcs::mend_item (avatar & you, item_location && obj, bool interactive = true)
Attempt to start an activity to mend an item (fix any current faults)
Parameters
obj Object to mend
interactive If true prompts player when there are multiple faults, otherwise mends the first
Definition at line 173 of file avatar_functions.cpp.
{
    if( you.has_trait( trait_DEBUG_HS ) ) {
        uilist menu;
        menu.text = _( "Toggle which fault?" );
        std::vector<std::pair<fault_id, bool>> opts;
        for( const auto &f : obj->faults_potential() ) {
            opts.emplace_back( f, !!obj->faults.count( f ) );
            menu.addentry( -1, true, -1, string_format(
                               opts.back().second ? pgettext( "fault", "Mend: %s" ) : pgettext( "fault", "Set: %s" ),
                               f.obj().name() ) );
        }
        if( opts.empty() ) {
            add_msg( m_info, _( "The %s doesn't have any faults to toggle." ), obj->tname() );
            return;
        }
        menu.query();
        if( menu.ret >= 0 ) {
            if( opts[ menu.ret ].second ) {
                obj->faults.erase( opts[ menu.ret ].first );
            } else {
                obj->faults.insert( opts[ menu.ret ].first );
            }
        }
        return;
    }
    auto inv = you.crafting_inventory();
    struct mending_option {
        fault_id fault;
        std::reference_wrapper<const mending_method> method;
        bool doable;
    };
    std::vector<mending_option> mending_options;
    for( const fault_id &f : obj->faults ) {
        for( const auto &m : f->mending_methods() ) {
            mending_option opt { f, m.second, true };
            for( const auto &sk : m.second.skills ) {
                if( you.get_skill_level( sk.first ) < sk.second ) {
                    opt.doable = false;
                    break;
                }
            }
            opt.doable = opt.doable &&
                         m.second.requirements->can_make_with_inventory( inv, is_crafting_component );
            mending_options.emplace_back( opt );
        }
    }
    if( mending_options.empty() ) {
        if( interactive ) {
            add_msg( m_info, _( "The %s doesn't have any faults to mend." ), obj->tname() );
            if( obj->damage() > 0 ) {
                const std::set<itype_id> &rep = obj->repaired_with();
                if( !rep.empty() ) {
                    const std::string repair_options =
                    enumerate_as_string( rep.begin(), rep.end(), []( const itype_id & e ) {
                        return item::nname( e );
                    }, enumeration_conjunction::or_ );
                    add_msg( m_info, _( "It is damaged, and could be repaired with %s.  "
                                        "%s to use one of those items." ),
                             repair_options, press_x( ACTION_USE ) );
                }
            }
        }
        return;
    }
    int sel = 0;
    if( interactive ) {
        uilist menu;
        menu.text = _( "Mend which fault?" );
        menu.desc_enabled = true;
        menu.desc_lines_hint = 0; // Let uilist handle description height
        constexpr int fold_width = 80;
        for( const mending_option &opt : mending_options ) {
            const mending_method &method = opt.method;
            const nc_color col = opt.doable ? c_white : c_light_gray;
            auto reqs = method.requirements.obj();
            auto tools = reqs.get_folded_tools_list( fold_width, col, inv );
            auto comps = reqs.get_folded_components_list( fold_width, col, inv, is_crafting_component );
            std::string descr;
            if( method.turns_into ) {
                descr += string_format( _( "Turns into: <color_cyan>%s</color>\n" ),
                                        method.turns_into->obj().name() );
            }
            if( method.also_mends ) {
                descr += string_format( _( "Also mends: <color_cyan>%s</color>\n" ),
                                        method.also_mends->obj().name() );
            }
            descr += string_format( _( "Time required: <color_cyan>%s</color>\n" ),
                                    to_string_approx( method.time ) );
            if( method.skills.empty() ) {
                descr += string_format( _( "Skills: <color_cyan>none</color>\n" ) );
            } else {
                descr += string_format( _( "Skills: %s\n" ),
                                        enumerate_as_string( method.skills.begin(), method.skills.end(),
                [&]( const std::pair<skill_id, int> &sk ) -> std::string {
                    if( you.get_skill_level( sk.first ) >= sk.second )
                    {
                        return string_format( pgettext( "skill requirement",
                                                        //~ %1$s: skill name, %2$s: current skill level, %3$s: required skill level
                                                        "<color_cyan>%1$s</color> <color_green>(%2$d/%3$d)</color>" ),
                                              sk.first->name(), you.get_skill_level( sk.first ), sk.second );
                    } else
                    {
                        return string_format( pgettext( "skill requirement",
                                                        //~ %1$s: skill name, %2$s: current skill level, %3$s: required skill level
                                                        "<color_cyan>%1$s</color> <color_yellow>(%2$d/%3$d)</color>" ),
                                              sk.first->name(), you.get_skill_level( sk.first ), sk.second );
                    }
                } ) );
            }
            for( const std::string &line : tools ) {
                descr += line + "\n";
            }
            for( const std::string &line : comps ) {
                descr += line + "\n";
            }
            const std::string desc = method.description + "\n\n" + colorize( descr, col );
            menu.addentry_desc( -1, true, -1, method.name.translated(), desc );
        }
        menu.query();
        if( menu.ret < 0 ) {
            add_msg( _( "Never mind." ) );
            return;
        }
        sel = menu.ret;
    }
    if( sel >= 0 ) {
        const mending_option &opt = mending_options[sel];
        if( !opt.doable ) {
            if( interactive ) {
                add_msg( m_info, _( "You are currently unable to mend the %s this way." ), obj->tname() );
            }
            return;
        }
        const mending_method &method = opt.method;
        you.assign_activity( activity_id( "ACT_MEND_ITEM" ), to_moves<int>( method.time ) );
        you.activity.name = opt.fault.str();
        you.activity.str_values.emplace_back( method.id );
        you.activity.targets.push_back( std::move( obj ) );
    }
}
References _, ACTION_USE, add_msg(), uilist::addentry(), uilist::addentry_desc(), mending_method::also_mends, c_light_gray, c_white, colorize(), Character::crafting_inventory(), uilist::desc_enabled, uilist::desc_lines_hint, enumerate_as_string(), iexamine::fault(), requirement_data::get_folded_tools_list(), Character::get_skill_level(), Character::has_trait(), is_crafting_component(), line(), m_info, fault::mending_methods(), string_id< T >::obj(), or_, pgettext(), press_x(), uilist::query(), mending_method::requirements, uilist::ret, mending_method::skills, string_format(), uilist::text, mending_method::time, to_string_approx(), trait_DEBUG_HS, and mending_method::turns_into.
Referenced by iexamine::autoclave_empty(), veh_interact::do_mend(), avatar_action::mend(), and iuse::pack_cbm().
toolmod_add()
void avatar_funcs::toolmod_add (avatar & you, item_location tool, item_location mod)
Starts activity to install toolmod.
Definition at line 530 of file avatar_functions.cpp.
{
    if( !tool && !mod ) {
        debugmsg( "Tried toolmod installation but mod/tool not available" );
        return;
    }
    // first check at least the minimum requirements are met
    if( !you.has_trait( trait_DEBUG_HS ) && !you.can_use( *mod, *tool ) ) {
        return;
    }
    if( !query_yn( _( "Permanently install your %1$s in your %2$s?" ),
                   colorize( mod->tname(), mod->color_in_inventory() ),
                   colorize( tool->tname(), tool->color_in_inventory() ) ) ) {
        you.add_msg_if_player( _( "Never mind." ) );
        return; // player canceled installation
    }
    you.assign_activity( activity_id( "ACT_TOOLMOD_ADD" ), 1, -1 );
    you.activity.targets.emplace_back( std::move( tool ) );
    you.activity.targets.emplace_back( std::move( mod ) );
}
References _, Character::activity, player::add_msg_if_player(), Character::assign_activity(), Character::can_use(), colorize(), debugmsg, Character::has_trait(), avatar_action::move(), query_yn(), player_activity::targets, tool, and trait_DEBUG_HS.
Referenced by iuse::toolmod_attach().
try_disarm_npc()
void avatar_funcs::try_disarm_npc (avatar & you, npc & target)
Try to disarm the NPC.
May result in fail attempt, you receiving the wepon and instantly wielding it, or the weapon falling down on the floor nearby. NPC is always getting angry with you.
Parameters
target Target NPC to disarm
Strength increases chance to disarm, primary stat Dexterity increases chance to disarm, secondary stat Melee increases chance to disarm Unarmed increases chance to disarm, bonus when nothing wielded
Definition at line 2319 of file melee.cpp.
{
    if( !target.is_armed() ) {
        return;
    }
    if( target.is_hallucination() ) {
        target.on_attacked( you );
        return;
    }
    /** @EFFECT_STR increases chance to disarm, primary stat */
    /** @EFFECT_DEX increases chance to disarm, secondary stat */
    int my_roll = dice( 3, 2 * you.get_str() + you.get_dex() );
    /** @EFFECT_MELEE increases chance to disarm */
    my_roll += dice( 3, you.get_skill_level( skill_melee ) );
    int their_roll = dice( 3, 2 * target.get_str() + target.get_dex() );
    their_roll += dice( 3, target.get_per() );
    their_roll += dice( 3, target.get_skill_level( skill_melee ) );
    item &it = target.weapon;
    // roll your melee and target's dodge skills to check if grab/smash attack succeeds
    int hitspread = target.deal_melee_attack( &you, you.hit_roll() );
    if( hitspread < 0 ) {
        add_msg( _( "You lunge for the %s, but miss!" ), it.tname() );
        you.mod_moves( -100 - stumble( you, you.weapon ) - you.attack_cost( you.weapon ) );
        target.on_attacked( you );
        return;
    }
    // hitspread >= 0, which means we are going to disarm by grabbing target by their weapon
    if( !you.is_armed() ) {
        /** @EFFECT_UNARMED increases chance to disarm, bonus when nothing wielded */
        my_roll += dice( 3, you.get_skill_level( skill_unarmed ) );
        if( my_roll >= their_roll ) {
            //~ %s: weapon name
            add_msg( _( "You grab at %s and pull with all your force!" ), it.tname() );
            //~ %1$s: weapon name, %2$s: NPC name
            add_msg( _( "You forcefully take %1$s from %2$s!" ), it.tname(), target.name );
            // wield() will deduce our moves, consider to deduce more/less moves for balance
            item rem_it = target.i_rem( &it );
            you.wield( rem_it );
        } else if( my_roll >= their_roll / 2 ) {
            add_msg( _( "You grab at %s and pull with all your force, but it drops nearby!" ),
                     it.tname() );
            const tripoint tp = target.pos() + tripoint( rng( -1, 1 ), rng( -1, 1 ), 0 );
            g->m.add_item_or_charges( tp, target.i_rem( &it ) );
            you.mod_moves( -100 );
        } else {
            add_msg( _( "You grab at %s and pull with all your force, but in vain!" ), it.tname() );
            you.mod_moves( -100 );
        }
        target.on_attacked( you );
        return;
    }
    // Make their weapon fall on floor if we've rolled enough.
    you.mod_moves( -100 - you.attack_cost( you.weapon ) );
    if( my_roll >= their_roll ) {
        add_msg( _( "You smash %s with all your might forcing their %s to drop down nearby!" ),
                 target.name, it.tname() );
        const tripoint tp = target.pos() + tripoint( rng( -1, 1 ), rng( -1, 1 ), 0 );
        g->m.add_item_or_charges( tp, target.i_rem( &it ) );
    } else {
        add_msg( _( "You smash %s with all your might but %s remains in their hands!" ),
                 target.name, it.tname() );
    }
    target.on_attacked( you );
}
References _, add_msg(), Character::attack_cost(), Creature::deal_melee_attack(), dice(), g, Character::get_dex(), Character::get_per(), Character::get_skill_level(), Character::get_str(), Character::hit_roll(), Character::i_rem(), Character::is_armed(), npc::is_hallucination(), Creature::mod_moves(), Character::name, npc::on_attacked(), Character::pos(), rng(), skill_melee, skill_unarmed, stumble(), item::tname(), Character::weapon, and avatar::wield().
Referenced by game::npc_menu().
try_steal_from_npc()
void avatar_funcs::try_steal_from_npc (avatar & you, npc & target)
Try to steal an item from the NPC's inventory.
May result in fail attempt, when NPC not notices you, notices your steal attempt and getting angry with you, and you successfully stealing the item.
Parameters
target Target NPC to steal from
Dexterity defines the chance to steal Unarmed adds bonus to stealing when wielding nothing
Definition at line 2395 of file melee.cpp.
{
    if( target.is_enemy() ) {
        add_msg( _( "%s is hostile!" ), target.name );
        return;
    }
    item_location loc = game_menus::inv::steal( you, target );
    if( !loc ) {
        return;
    }
    /** @EFFECT_DEX defines the chance to steal */
    int my_roll = dice( 3, you.get_dex() );
    /** @EFFECT_UNARMED adds bonus to stealing when wielding nothing */
    if( !you.is_armed() ) {
        my_roll += dice( 4, 3 );
    }
    if( you.has_trait( trait_DEFT ) ) {
        my_roll += dice( 2, 6 );
    }
    int their_roll = dice( 5, target.get_per() );
    const item *it = loc.get_item();
    if( my_roll >= their_roll ) {
        add_msg( _( "You sneakily steal %1$s from %2$s!" ),
                 it->tname(), target.name );
        you.i_add( target.i_rem( it ) );
    } else if( my_roll >= their_roll / 2 ) {
        add_msg( _( "You failed to steal %1$s from %2$s, but did not attract attention." ),
                 it->tname(), target.name );
    } else {
        add_msg( _( "You failed to steal %1$s from %2$s." ),
                 it->tname(), target.name );
        target.on_attacked( you );
    }
    // consider to deduce less/more moves for balance
    you.mod_moves( -200 );
}
References _, add_msg(), dice(), Character::get_dex(), item_location::get_item(), Character::get_per(), Character::has_trait(), Character::i_add(), Character::i_rem(), Character::is_armed(), npc::is_enemy(), Creature::mod_moves(), Character::name, npc::on_attacked(), game_menus::inv::steal(), item::tname(), and trait_DEFT.
Referenced by game::npc_menu().
try_to_sleep()
void avatar_funcs::try_to_sleep (avatar & you, const time_duration & dur)
Handles sleep attempts by the player, starts ACT_TRY_SLEEP activity.
Definition at line 48 of file avatar_functions.cpp.
{
    map &here = get_map();
    const optional_vpart_position vp = here.veh_at( you.pos() );
    const trap &trap_at_pos = here.tr_at( you.pos() );
    const ter_id ter_at_pos = here.ter( you.pos() );
    const furn_id furn_at_pos = here.furn( you.pos() );
    bool plantsleep = false;
    bool fungaloid_cosplay = false;
    bool websleep = false;
    bool webforce = false;
    bool websleeping = false;
    bool in_shell = false;
    bool watersleep = false;
    if( you.has_trait( trait_CHLOROMORPH ) ) {
        plantsleep = true;
        if( ( ter_at_pos == t_dirt || ter_at_pos == t_pit ||
              ter_at_pos == t_dirtmound || ter_at_pos == t_pit_shallow ||
              ter_at_pos == t_grass ) && !vp &&
            furn_at_pos == f_null ) {
            you.add_msg_if_player( m_good, _( "You relax as your roots embrace the soil." ) );
        } else if( vp ) {
            you.add_msg_if_player( m_bad, _( "It's impossible to sleep in this wheeled pot!" ) );
        } else if( furn_at_pos != f_null ) {
            you.add_msg_if_player( m_bad,
                                   _( "The humans' furniture blocks your roots.  You can't get comfortable." ) );
        } else { // Floor problems
            you.add_msg_if_player( m_bad, _( "Your roots scrabble ineffectively at the unyielding surface." ) );
        }
    } else if( you.has_trait( trait_M_SKIN3 ) ) {
        fungaloid_cosplay = true;
        if( here.has_flag_ter_or_furn( "FUNGUS", you.pos() ) ) {
            you.add_msg_if_player( m_good,
                                   _( "Our fibers meld with the ground beneath us.  The gills on our neck begin to seed the air with spores as our awareness fades." ) );
        }
    }
    if( you.has_trait( trait_WEB_WALKER ) ) {
        websleep = true;
    }
    // Not sure how one would get Arachnid w/o web-making, but Just In Case
    if( you.has_trait( trait_THRESH_SPIDER ) && ( you.has_trait( trait_WEB_SPINNER ) ||
            ( you.has_trait( trait_WEB_WEAVER ) ) ) ) {
        webforce = true;
    }
    if( websleep || webforce ) {
        int web = here.get_field_intensity( you.pos(), fd_web );
        if( !webforce ) {
            // At this point, it's kinda weird, but surprisingly comfy...
            if( web >= 3 ) {
                you.add_msg_if_player( m_good,
                                       _( "These thick webs support your weight, and are strangely comfortable" ) );
                websleeping = true;
            } else if( web > 0 ) {
                you.add_msg_if_player( m_info,
                                       _( "You try to sleep, but the webs get in the way.  You brush them aside." ) );
                here.remove_field( you.pos(), fd_web );
            }
        } else {
            // Here, you're just not comfortable outside a nice thick web.
            if( web >= 3 ) {
                you.add_msg_if_player( m_good, _( "You relax into your web." ) );
                websleeping = true;
            } else {
                you.add_msg_if_player( m_bad,
                                       _( "You try to sleep, but you feel exposed and your spinnerets keep twitching." ) );
                you.add_msg_if_player( m_info, _( "Maybe a nice thick web would help you sleep." ) );
            }
        }
    }
    if( you.has_active_mutation( trait_SHELL2 ) ) {
        // Your shell's interior is a comfortable place to sleep.
        in_shell = true;
    }
    if( you.has_trait( trait_WATERSLEEP ) ) {
        if( you.is_underwater() ) {
            you.add_msg_if_player( m_good,
                                   _( "You lay beneath the waves' embrace, gazing up through the water's surface" ) );
            watersleep = true;
        } else if( here.has_flag_ter( "SWIMMABLE", you.pos() ) ) {
            you.add_msg_if_player( m_good, _( "You settle into the water and begin to drowse" ) );
            watersleep = true;
        }
    }
    constexpr int confort_level_neutral = static_cast<int>( character_funcs::comfort_level::neutral );
    if( !plantsleep && ( furn_at_pos.obj().comfort > confort_level_neutral ||
                         ter_at_pos == t_improvised_shelter ||
                         trap_at_pos.comfort > confort_level_neutral ||
                         in_shell || websleeping || watersleep ||
                         vp.part_with_feature( "SEAT", true ) ||
                         vp.part_with_feature( "BED", true ) ) ) {
        you.add_msg_if_player( m_good, _( "This is a comfortable place to sleep." ) );
    } else if( !plantsleep && !fungaloid_cosplay && !watersleep ) {
        if( !vp && ter_at_pos != t_floor ) {
            you.add_msg_if_player( ter_at_pos.obj().movecost <= 2 ?
                                   _( "It's a little hard to get to sleep on this %s." ) :
                                   _( "It's hard to get to sleep on this %s." ),
                                   ter_at_pos.obj().name() );
        } else if( vp ) {
            if( vp->part_with_feature( VPFLAG_AISLE, true ) ) {
                you.add_msg_if_player(
                    //~ %1$s: vehicle name, %2$s: vehicle part name
                    _( "It's a little hard to get to sleep on this %2$s in %1$s." ),
                    vp->vehicle().disp_name(),
                    vp->part_with_feature( VPFLAG_AISLE, true )->part().name( false ) );
            } else {
                you.add_msg_if_player(
                    //~ %1$s: vehicle name
                    _( "It's hard to get to sleep in %1$s." ),
                    vp->vehicle().disp_name() );
            }
        }
    }
    you.add_msg_if_player( _( "You start trying to fall asleep." ) );
    if( you.has_active_bionic( bio_soporific ) ) {
        you.bio_soporific_powered_at_last_sleep_check = you.has_power();
        if( you.bio_soporific_powered_at_last_sleep_check ) {
            // The actual bonus is applied in sleep_spot( p ).
            you.add_msg_if_player( m_good, _( "Your soporific inducer starts working its magic." ) );
        } else {
            you.add_msg_if_player( m_bad, _( "Your soporific inducer doesn't have enough power to operate." ) );
        }
    }
    you.assign_activity( activity_id( "ACT_TRY_SLEEP" ), to_moves<int>( dur ) );
}
References _, player::add_msg_if_player(), Character::assign_activity(), bio_soporific, Character::bio_soporific_powered_at_last_sleep_check, furn_t::comfort, trap::comfort, f_null, fd_web, map::furn(), map::get_field_intensity(), get_map(), Character::has_active_bionic(), Character::has_active_mutation(), map::has_flag_ter(), map::has_flag_ter_or_furn(), Character::has_power(), Character::has_trait(), Creature::is_underwater(), m_bad, m_good, m_info, map_data_common_t::movecost, map_data_common_t::name(), character_funcs::neutral, int_id< T >::obj(), optional_vpart_position::part_with_feature(), Character::pos(), map::remove_field(), t_dirt, t_dirtmound, t_floor, t_grass, t_improvised_shelter, t_pit, t_pit_shallow, map::ter(), map::tr_at(), trait_CHLOROMORPH, trait_M_SKIN3, trait_SHELL2, trait_THRESH_SPIDER, trait_WATERSLEEP, trait_WEB_SPINNER, trait_WEB_WALKER, trait_WEB_WEAVER, map::veh_at(), and VPFLAG_AISLE.
Referenced by sleep().
unload_item()
bool avatar_funcs::unload_item (avatar & you, item_location loc)
Unload an item at given location.
Definition at line 631 of file avatar_functions.cpp.
{
    item &it = *loc.get_item();
    // Unload a container consuming moves per item successfully removed
    if( it.is_container() || it.is_bandolier() ) {
        if( it.contents.empty() ) {
            add_msg( m_info, _( "The %s is already empty!" ), it.tname() );
            return false;
        }
        if( !it.can_unload_liquid() ) {
            add_msg( m_info, _( "The liquid can't be unloaded in its current state!" ) );
            return false;
        }
        bool changed = false;
        for( item *contained : it.contents.all_items_top() ) {
            int old_charges = contained->charges;
            const bool consumed = add_or_drop_with_msg( you, *contained, true );
            changed = changed || consumed || contained->charges != old_charges;
            if( consumed ) {
                you.mod_moves( -you.item_handling_cost( *contained ) );
                it.remove_item( *contained );
            }
        }
        if( changed ) {
            it.on_contents_changed();
        }
        return true;
    }
    // If item can be unloaded more than once (currently only guns) prompt user to choose
    std::vector<std::string> msgs( 1, it.tname() );
    std::vector<item *> opts( 1, &it );
    for( auto e : it.gunmods() ) {
        if( e->is_gun() && !e->has_flag( "NO_UNLOAD" ) &&
            ( e->magazine_current() || e->ammo_remaining() > 0 || e->casings_count() > 0 ) ) {
            msgs.emplace_back( e->tname() );
            opts.emplace_back( e );
        }
    }
    item *target = nullptr;
    if( opts.size() > 1 ) {
        const int ret = uilist( _( "Unload what?" ), msgs );
        if( ret >= 0 ) {
            target = opts[ret];
        }
    } else {
        target = &it;
    }
    if( target == nullptr ) {
        return false;
    }
    // Next check for any reasons why the item cannot be unloaded
    if( target->ammo_types().empty() || target->ammo_capacity() <= 0 ) {
        add_msg( m_info, _( "You can't unload a %s!" ), target->tname() );
        return false;
    }
    if( target->has_flag( "NO_UNLOAD" ) ) {
        if( target->has_flag( "RECHARGE" ) || target->has_flag( "USE_UPS" ) ) {
            add_msg( m_info, _( "You can't unload a rechargeable %s!" ), target->tname() );
        } else {
            add_msg( m_info, _( "You can't unload a %s!" ), target->tname() );
        }
        return false;
    }
    if( !target->magazine_current() && target->ammo_remaining() <= 0 && target->casings_count() <= 0 ) {
        if( target->is_tool() ) {
            add_msg( m_info, _( "Your %s isn't charged." ), target->tname() );
        } else {
            add_msg( m_info, _( "Your %s isn't loaded." ), target->tname() );
        }
        return false;
    }
    target->casings_handle( [&]( item & e ) {
        return you.i_add_or_drop( e );
    } );
    if( target->is_magazine() ) {
        // Calculate the time to remove the contained ammo (consuming half as much time as required to load the magazine)
        int mv = 0;
        int qty = 0;
        std::vector<item *> remove_contained;
        for( item *contained : it.contents.all_items_top() ) {
            mv += you.item_reload_cost( it, *contained, contained->charges ) / 2;
            if( add_or_drop_with_msg( you, *contained, true ) ) {
                qty += contained->charges;
                remove_contained.push_back( contained );
            }
        }
        // remove the ammo leads in the belt
        for( item *remove : remove_contained ) {
            it.remove_item( *remove );
        }
        // remove the belt linkage
        if( it.is_ammo_belt() ) {
            if( it.type->magazine->linkage ) {
                item link( *it.type->magazine->linkage, calendar::turn, qty );
                add_or_drop_with_msg( you, link, true );
            }
            add_msg( _( "You disassemble your %s." ), it.tname() );
        } else {
            add_msg( _( "You unload your %s." ), it.tname() );
        }
        you.mod_moves( -std::min( 200, mv ) );
        if( loc->has_flag( "MAG_DESTROY" ) && loc->ammo_remaining() == 0 ) {
            loc.remove_item();
        }
        return true;
    } else if( target->magazine_current() ) {
        if( !add_or_drop_with_msg( you, *target->magazine_current(), true ) ) {
            return false;
        }
        // Eject magazine consuming half as much time as required to insert it
        you.moves -= you.item_reload_cost( *target, *target->magazine_current(), -1 ) / 2;
        target->remove_items_with( [&target]( const item & e ) {
            return target->magazine_current() == &e;
        } );
    } else if( target->ammo_remaining() ) {
        int qty = target->ammo_remaining();
        if( target->ammo_current() == itype_plut_cell ) {
            qty = target->ammo_remaining() / PLUTONIUM_CHARGES;
            if( qty > 0 ) {
                add_msg( _( "You recover %i unused plutonium." ), qty );
            } else {
                add_msg( m_info, _( "You can't remove partially depleted plutonium!" ) );
                return false;
            }
        }
        // Construct a new ammo item and try to drop it
        item ammo( target->ammo_current(), calendar::turn, qty );
        if( target->is_filthy() ) {
            ammo.set_flag( "FILTHY" );
        }
        if( ammo.made_of( LIQUID ) ) {
            if( !add_or_drop_with_msg( you, ammo, false ) ) {
                qty -= ammo.charges; // only handled part (or none) of the liquid
            }
            if( qty <= 0 ) {
                return false; // no liquid was moved
            }
        } else if( !add_or_drop_with_msg( you, ammo, qty > 1 ) ) {
            return false;
        }
        // If successful remove appropriate qty of ammo consuming half as much time as required to load it
        you.moves -= you.item_reload_cost( *target, ammo, qty ) / 2;
        if( target->ammo_current() == itype_plut_cell ) {
            qty *= PLUTONIUM_CHARGES;
        }
        target->ammo_set( target->ammo_current(), target->ammo_remaining() - qty );
    }
    // Turn off any active tools
    if( target->is_tool() && target->active && target->ammo_remaining() == 0 ) {
        target->type->invoke( you, *target, you.pos() );
    }
    add_msg( _( "You unload your %s." ), target->tname() );
    return true;
}
References _, item::active, add_msg(), add_or_drop_with_msg(), item_contents::all_items_top(), item::ammo_capacity(), item::ammo_current(), item::ammo_remaining(), item::ammo_set(), item::ammo_types(), item::can_unload_liquid(), item::casings_count(), item::casings_handle(), item::charges, item::contents, item_contents::empty(), item_location::get_item(), item::gunmods(), item::has_flag(), Character::i_add_or_drop(), itype::invoke(), item::is_ammo_belt(), item::is_bandolier(), item::is_container(), item::is_filthy(), item::is_magazine(), item::is_tool(), Character::item_handling_cost(), Character::item_reload_cost(), itype_plut_cell, LIQUID, m_info, item::made_of(), itype::magazine, item::magazine_current(), Creature::mod_moves(), Creature::moves, item::on_contents_changed(), PLUTONIUM_CHARGES, Character::pos(), item_location::remove_item(), visitable< T >::remove_item(), visitable< T >::remove_items_with(), cata::hash64_detail::ret, item::set_flag(), item::tname(), calendar::turn, and item::type.
Referenced by gunmod_remove(), vehicle::interact_with(), examine_item_menu::run(), iuse::toolmod_attach(), avatar_action::unload(), aim_activity_actor::unload_RAS_weapon(), and use_item().
use_item()
void avatar_funcs::use_item (avatar & you, item_location loc)
Use a tool at given location.
Definition at line 561 of file avatar_functions.cpp.
{
    item &used = *loc.get_item();
    if( used.is_null() ) {
        add_msg( m_info, _( "You do not have that item." ) );
        return;
    }
    you.last_item = used.typeId();
    if( used.is_tool() ) {
        if( !used.type->has_use() ) {
            add_msg( _( "You can't do anything interesting with your %s." ), used.tname() );
            return;
        }
        you.invoke_item( &used, loc.position() );
    } else if( is_pet_food( used ) ) {
        you.invoke_item( &used, loc.position() );
    } else if( !used.is_container_empty() && is_pet_food( used.get_contained() ) ) {
        unload_item( you, loc );
    } else if( !used.is_craft() && ( used.is_medication() || ( !used.type->has_use() &&
                                     ( used.is_food() ||
                                       used.get_contained().is_food() ||
                                       used.get_contained().is_medication() ) ) ) ) {
        you.consume( loc );
    } else if( used.is_book() ) {
        you.read( loc );
    } else if( used.type->has_use() ) {
        you.invoke_item( &used, loc.position() );
    } else if( used.has_flag( flag_SPLINT ) ) {
        ret_val<bool> need_splint = you.can_wear( used );
        if( need_splint.success() ) {
            you.wear_item( used );
            loc.remove_item();
        } else {
            add_msg( m_info, need_splint.str() );
        }
    } else {
        add_msg( m_info, _( "You can't do anything interesting with your %s." ),
                 used.tname() );
    }
    you.recalculate_enchantment_cache();
}
References _, add_msg(), Character::can_wear(), Character::consume(), flag_SPLINT(), item::get_contained(), item_location::get_item(), item::has_flag(), itype::has_use(), avatar::invoke_item(), item::is_book(), item::is_container_empty(), item::is_craft(), item::is_food(), item::is_medication(), item::is_null(), is_pet_food(), item::is_tool(), Character::last_item, m_info, item_location::position(), avatar::read(), Character::recalculate_enchantment_cache(), item_location::remove_item(), ret_val< T >::str(), ret_val< T >::success(), item::tname(), item::type, item::typeId(), unload_item(), and Character::wear_item().
Referenced by game::handle_action(), and avatar_action::use_item().