Cataclysm BN: spell_detail Namespace Reference
spell_detail Namespace Reference
Classes
struct line_iterable
Functions
static int side_of (const point &a, const point &b, const point &c)
static bool between_or_on (const point &a0, const point &a1, const point &d, const point &c)
static void build_line (spell_detail::line_iterable line, const tripoint &source, const point &delta, const point &delta_perp, bool(*test)(const tripoint &, const tripoint &), std::set< tripoint > &result)
Function Documentation
between_or_on()
static bool spell_detail::between_or_on (const point & a0, const point & a1, const point & d, const point & c) static
Definition at line 94 of file magic_spell_effect.cpp.
{
    return side_of( a0, a0 + d, c ) != 1 && side_of( a1, a1 + d, c ) != -1;
}
References c, and side_of().
Referenced by build_line().
build_line()
static void spell_detail::build_line (spell_detail::line_iterable line, const tripoint & source, const point & delta, const point & delta_perp, bool(*)(const tripoint &, const tripoint &) test, std::set< tripoint > & result) static
Definition at line 99 of file magic_spell_effect.cpp.
{
    tripoint last_point = source;
    while( between_or_on( point_zero, delta, delta_perp, line.get() ) ) {
        if( !test( source + line.get(), last_point ) ) {
            break;
        }
        result.emplace( source + line.get() );
        last_point = source + line.get();
        line.next();
    }
}
References between_or_on(), line(), and point_zero.
Referenced by spell_effect::spell_effect_line().
side_of()
static int spell_detail::side_of (const point & a, const point & b, const point & c) static
Definition at line 88 of file magic_spell_effect.cpp.
{
    int cross = ( ( b.x - a.x ) * ( c.y - a.y ) - ( b.y - a.y ) * ( c.x - a.x ) );
    return ( cross > 0 ) - ( cross < 0 );
}
References a, b, and c.
Referenced by between_or_on(), and spell_effect::spell_effect_line().