Cataclysm BN: overmap_connections Namespace Reference
overmap_connections Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check_consistency ()
void reset ()
overmap_connection_id guess_for (const oter_id &oter)
overmap_connection_id guess_for (const oter_type_id &oter)
Function Documentation
check_consistency()
void overmap_connections::check_consistency ()
Definition at line 147 of file overmap_connection.cpp.
{
    connections.check();
}
References anonymous_namespace{overmap_connection.cpp}::connections.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void overmap_connections::finalize ()
Definition at line 139 of file overmap_connection.cpp.
{
    connections.finalize();
    for( const auto &elem : connections.get_all() ) {
        const_cast<overmap_connection &>( elem ).finalize(); // This cast is ugly, but safe.
    }
}
References anonymous_namespace{overmap_connection.cpp}::connections, and overmap_connection::finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
guess_for() [1/2]
overmap_connection_id overmap_connections::guess_for (const oter_id & oter)
Definition at line 157 of file overmap_connection.cpp.
{
    const auto &all = connections.get_all();
    const auto iter = std::find_if( all.cbegin(),
    all.cend(), [&oter]( const overmap_connection & elem ) {
        return elem.pick_subtype_for( oter ) != nullptr;
    } );
    return iter != all.cend() ? iter->id : overmap_connection_id::NULL_ID();
}
References om_direction::all, anonymous_namespace{overmap_connection.cpp}::connections, and string_id< overmap_connection >::NULL_ID().
Referenced by overmapbuffer::reveal_route().
guess_for() [2/2]
overmap_connection_id overmap_connections::guess_for (const oter_type_id & oter)
Definition at line 168 of file overmap_connection.cpp.
{
    return guess_for( oter->get_first() );
}
References guess_for().
Referenced by guess_for().
load()
void overmap_connections::load (const JsonObject & jo, const std::string & src)
Definition at line 134 of file overmap_connection.cpp.
{
    connections.load( jo, src );
}
References anonymous_namespace{overmap_connection.cpp}::connections.
Referenced by DynamicDataLoader::initialize().
reset()
void overmap_connections::reset ()
Definition at line 152 of file overmap_connection.cpp.
{
    connections.reset();
}
References anonymous_namespace{overmap_connection.cpp}::connections.
Referenced by DynamicDataLoader::unload_data().