Cataclysm BN: VehicleSpawnFunction Namespace Reference
VehicleSpawnFunction Namespace Reference
Functions
static void builtin_no_vehicles (map &, const std::string &)
static void builtin_jackknifed_semi (map &m, const std::string &terrainid)
static void builtin_pileup (map &m, const std::string &, const std::string &vg)
static void builtin_citypileup (map &m, const std::string &t)
static void builtin_policepileup (map &m, const std::string &t)
static void builtin_parkinglot (map &m, const std::string &)
Function Documentation
builtin_citypileup()
static void VehicleSpawnFunction::builtin_citypileup (map & m, const std::string & t) static
Definition at line 277 of file vehicle_group.cpp.
{
    builtin_pileup( m, t, "city_pileup" );
}
References builtin_pileup().
builtin_jackknifed_semi()
static void VehicleSpawnFunction::builtin_jackknifed_semi (map & m, const std::string & terrainid) static
Definition at line 221 of file vehicle_group.cpp.
{
    const VehicleLocation *loc = vplacement_id( terrainid + "_semi" ).obj().pick();
    if( !loc ) {
        debugmsg( "builtin_jackknifed_semi unable to get location to place vehicle.  placement %s_semi",
                  terrainid );
        return;
    }
    const units::angle facing = loc->pick_facing();
    int facing_degrees = std::lround( to_degrees( facing ) );
    const point semi_p = loc->pick_point();
    point trailer_p;
    if( facing_degrees == 0 ) {
        trailer_p.x = semi_p.x + 4;
        trailer_p.y = semi_p.y - 10;
    } else if( facing_degrees == 90 ) {
        trailer_p.x = semi_p.x + 12;
        trailer_p.y = semi_p.y + 1;
    } else if( facing_degrees == 180 ) {
        trailer_p.x = semi_p.x - 4;
        trailer_p.y = semi_p.y + 10;
    } else {
        trailer_p.x = semi_p.x - 12;
        trailer_p.y = semi_p.y - 1;
    }
    m.add_vehicle( vgroup_id( "semi_truck" ), semi_p,
                   units::fmod( facing + 135_degrees, 360_degrees ), -1, 1 );
    m.add_vehicle( vgroup_id( "truck_trailer" ), trailer_p,
                   units::fmod( facing + 90_degrees, 360_degrees ), -1, 1 );
}
References map::add_vehicle(), debugmsg, units::fmod(), VehicleLocation::pick_facing(), VehicleLocation::pick_point(), units::to_degrees(), point::x, and point::y.
builtin_no_vehicles()
static void VehicleSpawnFunction::builtin_no_vehicles (map & , const std::string &) static
Definition at line 218 of file vehicle_group.cpp.
{}
builtin_parkinglot()
static void VehicleSpawnFunction::builtin_parkinglot (map & m, const std::string &) static
Definition at line 287 of file vehicle_group.cpp.
{
    for( int v = 0; v < rng( 1, 4 ); v++ ) {
        tripoint pos_p;
        pos_p.x = rng( 0, 1 ) * 15 + rng( 4, 5 );
        pos_p.y = rng( 0, 4 ) * 4 + rng( 2, 4 );
        pos_p.z = m.get_abs_sub().z;
        if( !m.veh_at( pos_p ) ) {
            units::angle facing;
            if( one_in( 10 ) ) {
                facing = random_direction();
            } else {
                facing = one_in( 2 ) ? 0_degrees : 180_degrees;
            }
            m.add_vehicle( vgroup_id( "parkinglot" ), pos_p, facing, -1, -1 );
        }
    }
}
References map::add_vehicle(), map::get_abs_sub(), one_in(), random_direction(), rng(), map::veh_at(), tripoint::x, tripoint::y, and tripoint::z.
builtin_pileup()
static void VehicleSpawnFunction::builtin_pileup (map & m, const std::string & , const std::string & vg) static
Definition at line 255 of file vehicle_group.cpp.
{
    vehicle *last_added_car = nullptr;
    const int num_cars = rng( 5, 12 );
    for( int i = 0; i < num_cars; i++ ) {
        const VehicleLocation *loc = vplacement_id( "pileup" ).obj().pick();
        if( !loc ) {
            debugmsg( "builtin_pileup unable to get location to place vehicle." );
            return;
        }
        last_added_car = m.add_vehicle( vgroup_id( vg ), loc->pick_point(),
                                        loc->pick_facing(), -1, 1 );
        if( last_added_car != nullptr ) {
            last_added_car->name = _( "pile-up" );
        } else {
            break;
        }
    }
}
References _, map::add_vehicle(), debugmsg, vehicle::name, VehicleLocation::pick_facing(), VehicleLocation::pick_point(), and rng().
Referenced by builtin_citypileup(), and builtin_policepileup().
builtin_policepileup()
static void VehicleSpawnFunction::builtin_policepileup (map & m, const std::string & t) static
Definition at line 282 of file vehicle_group.cpp.
{
    builtin_pileup( m, t, "police_pileup" );
}
References builtin_pileup().