var namespacecata_1_1event__detail =
[
    [ "event_spec", "structcata_1_1event__detail_1_1event__spec.html", null ],
    [ "event_spec< event_type::activates_artifact >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1activates__artifact_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1activates__artifact_01_4" ],
    [ "event_spec< event_type::activates_mininuke >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1activates__mininuke_01_4.html", null ],
    [ "event_spec< event_type::administers_mutagen >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1administers__mutagen_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1administers__mutagen_01_4" ],
    [ "event_spec< event_type::angers_amigara_horrors >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1angers__amigara__horrors_01_4.html", null ],
    [ "event_spec< event_type::avatar_moves >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1avatar__moves_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1avatar__moves_01_4" ],
    [ "event_spec< event_type::awakes_dark_wyrms >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1awakes__dark__wyrms_01_4.html", null ],
    [ "event_spec< event_type::becomes_wanted >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1becomes__wanted_01_4.html", null ],
    [ "event_spec< event_type::broken_bone_mends >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1broken__bone__mends_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1broken__bone__mends_01_4" ],
    [ "event_spec< event_type::buries_corpse >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1buries__corpse_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1buries__corpse_01_4" ],
    [ "event_spec< event_type::causes_resonance_cascade >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1causes__resonance__cascade_01_4.html", null ],
    [ "event_spec< event_type::character_gains_effect >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__gains__effect_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__gains__effect_01_4" ],
    [ "event_spec< event_type::character_gets_headshot >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__gets__headshot_01_4.html", null ],
    [ "event_spec< event_type::character_heals_damage >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__heals__damage_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__heals__damage_01_4" ],
    [ "event_spec< event_type::character_kills_character >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__kills__character_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__kills__character_01_4" ],
    [ "event_spec< event_type::character_kills_monster >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__kills__monster_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__kills__monster_01_4" ],
    [ "event_spec< event_type::character_loses_effect >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__loses__effect_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__loses__effect_01_4" ],
    [ "event_spec< event_type::character_takes_damage >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__takes__damage_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__takes__damage_01_4" ],
    [ "event_spec< event_type::character_triggers_trap >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__triggers__trap_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__triggers__trap_01_4" ],
    [ "event_spec< event_type::character_wakes_up >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__wakes__up_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1character__wakes__up_01_4" ],
    [ "event_spec< event_type::consumes_marloss_item >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1consumes__marloss__item_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1consumes__marloss__item_01_4" ],
    [ "event_spec< event_type::crosses_marloss_threshold >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1crosses__marloss__threshold_01_4.html", null ],
    [ "event_spec< event_type::crosses_mutation_threshold >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1crosses__mutation__threshold_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1crosses__mutation__threshold_01_4" ],
    [ "event_spec< event_type::crosses_mycus_threshold >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1crosses__mycus__threshold_01_4.html", null ],
    [ "event_spec< event_type::dermatik_eggs_hatch >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dermatik__eggs__hatch_01_4.html", null ],
    [ "event_spec< event_type::dermatik_eggs_injected >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dermatik__eggs__injected_01_4.html", null ],
    [ "event_spec< event_type::destroys_triffid_grove >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1destroys__triffid__grove_01_4.html", null ],
    [ "event_spec< event_type::dies_from_asthma_attack >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dies__from__asthma__attack_01_4.html", null ],
    [ "event_spec< event_type::dies_from_drug_overdose >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dies__from__drug__overdose_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dies__from__drug__overdose_01_4" ],
    [ "event_spec< event_type::dies_of_infection >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dies__of__infection_01_4.html", null ],
    [ "event_spec< event_type::dies_of_starvation >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dies__of__starvation_01_4.html", null ],
    [ "event_spec< event_type::dies_of_thirst >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1dies__of__thirst_01_4.html", null ],
    [ "event_spec< event_type::digs_into_lava >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1digs__into__lava_01_4.html", null ],
    [ "event_spec< event_type::disarms_nuke >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1disarms__nuke_01_4.html", null ],
    [ "event_spec< event_type::eats_sewage >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1eats__sewage_01_4.html", null ],
    [ "event_spec< event_type::evolves_mutation >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1evolves__mutation_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1evolves__mutation_01_4" ],
    [ "event_spec< event_type::exhumes_grave >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1exhumes__grave_01_4.html", null ],
    [ "event_spec< event_type::fails_to_install_cbm >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1fails__to__install__cbm_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1fails__to__install__cbm_01_4" ],
    [ "event_spec< event_type::fails_to_remove_cbm >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1fails__to__remove__cbm_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1fails__to__remove__cbm_01_4" ],
    [ "event_spec< event_type::falls_asleep_from_exhaustion >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1falls__asleep__from__exhaustion_01_4.html", null ],
    [ "event_spec< event_type::fuel_tank_explodes >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1fuel__tank__explodes_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1fuel__tank__explodes_01_4" ],
    [ "event_spec< event_type::gains_addiction >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1gains__addiction_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1gains__addiction_01_4" ],
    [ "event_spec< event_type::gains_mutation >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1gains__mutation_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1gains__mutation_01_4" ],
    [ "event_spec< event_type::gains_skill_level >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1gains__skill__level_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1gains__skill__level_01_4" ],
    [ "event_spec< event_type::game_over >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1game__over_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1game__over_01_4" ],
    [ "event_spec< event_type::game_start >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1game__start_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1game__start_01_4" ],
    [ "event_spec< event_type::installs_cbm >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1installs__cbm_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1installs__cbm_01_4" ],
    [ "event_spec< event_type::installs_faulty_cbm >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1installs__faulty__cbm_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1installs__faulty__cbm_01_4" ],
    [ "event_spec< event_type::learns_martial_art >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1learns__martial__art_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1learns__martial__art_01_4" ],
    [ "event_spec< event_type::loses_addiction >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1loses__addiction_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1loses__addiction_01_4" ],
    [ "event_spec< event_type::npc_becomes_hostile >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1npc__becomes__hostile_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1npc__becomes__hostile_01_4" ],
    [ "event_spec< event_type::opens_portal >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1opens__portal_01_4.html", null ],
    [ "event_spec< event_type::opens_temple >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1opens__temple_01_4.html", null ],
    [ "event_spec< event_type::player_levels_spell >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1player__levels__spell_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1player__levels__spell_01_4" ],
    [ "event_spec< event_type::releases_subspace_specimens >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1releases__subspace__specimens_01_4.html", null ],
    [ "event_spec< event_type::removes_cbm >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1removes__cbm_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1removes__cbm_01_4" ],
    [ "event_spec< event_type::seals_hazardous_material_sarcophagus >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1seals__hazardous__material__sarcophagus_01_4.html", null ],
    [ "event_spec< event_type::telefrags_creature >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1telefrags__creature_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1telefrags__creature_01_4" ],
    [ "event_spec< event_type::teleglow_teleports >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1teleglow__teleports_01_4.html", null ],
    [ "event_spec< event_type::teleports_into_wall >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1teleports__into__wall_01_4.html", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1teleports__into__wall_01_4" ],
    [ "event_spec< event_type::terminates_subspace_specimens >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1terminates__subspace__specimens_01_4.html", null ],
    [ "event_spec< event_type::throws_up >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1throws__up_01_4.html", null ],
    [ "event_spec< event_type::triggers_alarm >", "structcata_1_1event__detail_1_1event__spec_3_01event__type_1_1triggers__alarm_01_4.html", null ],
    [ "event_spec_character", "structcata_1_1event__detail_1_1event__spec__character.html", "structcata_1_1event__detail_1_1event__spec__character" ],
    [ "event_spec_empty", "structcata_1_1event__detail_1_1event__spec__empty.html", "structcata_1_1event__detail_1_1event__spec__empty" ],
    [ "make_event_helper", "structcata_1_1event__detail_1_1make__event__helper.html", null ],
    [ "make_event_helper< Type, std::index_sequence< I... > >", "structcata_1_1event__detail_1_1make__event__helper_3_01Type_00_01std_1_1index__sequence_3_01I_8_8_8_01_4_01_4.html", "structcata_1_1event__detail_1_1make__event__helper_3_01Type_00_01std_1_1index__sequence_3_01I_8_8_8_01_4_01_4" ]
];