Cataclysm BN: debug_menu Namespace Reference
debug_menu Namespace Reference
Namespaces
namespace anonymous_namespace{wisheffect.cpp}
Classes
class bodypart_select_callback
class effect_edit_callback
class effect_select_callback
class mission_debug
Enumerations
enum debug_menu_index {
DEBUG_WISH , DEBUG_SHORT_TELEPORT , DEBUG_LONG_TELEPORT , DEBUG_REVEAL_MAP ,
DEBUG_SPAWN_NPC , DEBUG_SPAWN_MON , DEBUG_GAME_STATE , DEBUG_KILL_AREA ,
DEBUG_KILL_NPCS , DEBUG_MUTATE , DEBUG_SPAWN_VEHICLE , DEBUG_EDIT_PLAYER ,
DEBUG_SPAWN_ARTIFACT , DEBUG_SPAWN_CLAIRVOYANCE , DEBUG_MAP_EDITOR , DEBUG_CHANGE_WEATHER ,
DEBUG_WIND_DIRECTION , DEBUG_WIND_SPEED , DEBUG_GEN_SOUND , DEBUG_KILL_MONS ,
DEBUG_DISPLAY_HORDES , DEBUG_TEST_IT_GROUP , DEBUG_DAMAGE_SELF , DEBUG_SHOW_SOUND ,
DEBUG_DISPLAY_WEATHER , DEBUG_DISPLAY_SCENTS , DEBUG_DISPLAY_DISTRIBUTION_GRIDS , DEBUG_CHANGE_TIME ,
DEBUG_SET_AUTOMOVE , DEBUG_SHOW_MUT_CAT , DEBUG_SHOW_MUT_CHANCES , DEBUG_OM_EDITOR ,
DEBUG_BENCHMARK , DEBUG_BENCHMARK_FPS , DEBUG_OM_TELEPORT , DEBUG_OM_TELEPORT_COORDINATES ,
DEBUG_TRAIT_GROUP , DEBUG_SHOW_MSG , DEBUG_CRASH_GAME , DEBUG_RELOAD_TRANSLATIONS ,
DEBUG_MAP_EXTRA , DEBUG_DISPLAY_NPC_PATH , DEBUG_PRINT_FACTION_INFO , DEBUG_PRINT_NPC_MAGIC ,
DEBUG_QUIT_NOSAVE , DEBUG_TEST_WEATHER , DEBUG_SAVE_SCREENSHOT , DEBUG_BUG_REPORT ,
DEBUG_GAME_REPORT , DEBUG_DISPLAY_SCENTS_LOCAL , DEBUG_DISPLAY_SCENTS_TYPE_LOCAL , DEBUG_DISPLAY_TEMP ,
DEBUG_DISPLAY_VEHICLE_AI , DEBUG_DISPLAY_VISIBILITY , DEBUG_DISPLAY_LIGHTING , DEBUG_DISPLAY_RADIATION ,
DEBUG_DISPLAY_TRANSPARENCY , DEBUG_DISPLAY_SUBMAP_GRID , DEBUG_TEST_MAP_EXTRA_DISTRIBUTION , DEBUG_VEHICLE_BATTERY_CHARGE ,
DEBUG_HOUR_TIMER , DEBUG_NESTED_MAPGEN , DEBUG_RESET_IGNORED_MESSAGES , DEBUG_RELOAD_TILES
}
enum bench_kind { DRAW , FPS }
Functions
static int info_uilist (bool display_all_entries=true)
static int vehicle_uilist ()
static int teleport_uilist ()
static int spawning_uilist ()
static int map_uilist ()
static int debug_menu_uilist (bool display_all_entries=true)
Create the debug menu UI list.
void teleport_short ()
void teleport_long ()
void teleport_overmap (bool specific_coordinates)
void spawn_nested_mapgen ()
static Character & pick_character (Character &preselected)
void character_edit_menu (Character &c)
static std::string mission_status_string (mission::mission_status status)
static void add_header (uilist &mmenu, const std::string &str)
static bool remove_from_vec (std::vector< mission * > &vec, mission *m)
void benchmark (const int max_difference, bench_kind kind)
void debug ()
void effect_edit_menu (Creature &c)
void wishitem (player *p=nullptr)
void wishitem (player *p, const tripoint &)
void wishmonster (const cata::optional< tripoint > &p)
void wishmutate (player *p)
void wishskill (player *p)
void mutation_wish ()
Enumeration Type Documentation
bench_kind
enum debug_menu::bench_kind
Enumerator
DRAW
FPS
Definition at line 19 of file debug_menu.h.
                {
    DRAW,
    FPS
};
debug_menu_index
enum debug_menu::debug_menu_index
Enumerator
DEBUG_WISH
DEBUG_SHORT_TELEPORT
DEBUG_LONG_TELEPORT
DEBUG_REVEAL_MAP
DEBUG_SPAWN_NPC
DEBUG_SPAWN_MON
DEBUG_GAME_STATE
DEBUG_KILL_AREA
DEBUG_KILL_NPCS
DEBUG_MUTATE
DEBUG_SPAWN_VEHICLE
DEBUG_EDIT_PLAYER
DEBUG_SPAWN_ARTIFACT
DEBUG_SPAWN_CLAIRVOYANCE
DEBUG_MAP_EDITOR
DEBUG_CHANGE_WEATHER
DEBUG_WIND_DIRECTION
DEBUG_WIND_SPEED
DEBUG_GEN_SOUND
DEBUG_KILL_MONS
DEBUG_DISPLAY_HORDES
DEBUG_TEST_IT_GROUP
DEBUG_DAMAGE_SELF
DEBUG_SHOW_SOUND
DEBUG_DISPLAY_WEATHER
DEBUG_DISPLAY_SCENTS
DEBUG_DISPLAY_DISTRIBUTION_GRIDS
DEBUG_CHANGE_TIME
DEBUG_SET_AUTOMOVE
DEBUG_SHOW_MUT_CAT
DEBUG_SHOW_MUT_CHANCES
DEBUG_OM_EDITOR
DEBUG_BENCHMARK
DEBUG_BENCHMARK_FPS
DEBUG_OM_TELEPORT
DEBUG_OM_TELEPORT_COORDINATES
DEBUG_TRAIT_GROUP
DEBUG_SHOW_MSG
DEBUG_CRASH_GAME
DEBUG_RELOAD_TRANSLATIONS
DEBUG_MAP_EXTRA
DEBUG_DISPLAY_NPC_PATH
DEBUG_PRINT_FACTION_INFO
DEBUG_PRINT_NPC_MAGIC
DEBUG_QUIT_NOSAVE
DEBUG_TEST_WEATHER
DEBUG_SAVE_SCREENSHOT
DEBUG_BUG_REPORT
DEBUG_GAME_REPORT
DEBUG_DISPLAY_SCENTS_LOCAL
DEBUG_DISPLAY_SCENTS_TYPE_LOCAL
DEBUG_DISPLAY_TEMP
DEBUG_DISPLAY_VEHICLE_AI
DEBUG_DISPLAY_VISIBILITY
DEBUG_DISPLAY_LIGHTING
DEBUG_DISPLAY_RADIATION
DEBUG_DISPLAY_TRANSPARENCY
DEBUG_DISPLAY_SUBMAP_GRID
DEBUG_TEST_MAP_EXTRA_DISTRIBUTION
DEBUG_VEHICLE_BATTERY_CHARGE
DEBUG_HOUR_TIMER
DEBUG_NESTED_MAPGEN
DEBUG_RESET_IGNORED_MESSAGES
DEBUG_RELOAD_TILES
Definition at line 120 of file debug_menu.cpp.
                      {
    DEBUG_WISH,
    DEBUG_SHORT_TELEPORT,
    DEBUG_LONG_TELEPORT,
    DEBUG_REVEAL_MAP,
    DEBUG_SPAWN_NPC,
    DEBUG_SPAWN_MON,
    DEBUG_GAME_STATE,
    DEBUG_KILL_AREA,
    DEBUG_KILL_NPCS,
    DEBUG_MUTATE,
    DEBUG_SPAWN_VEHICLE,
    DEBUG_EDIT_PLAYER,
    DEBUG_SPAWN_ARTIFACT,
    DEBUG_SPAWN_CLAIRVOYANCE,
    DEBUG_MAP_EDITOR,
    DEBUG_CHANGE_WEATHER,
    DEBUG_WIND_DIRECTION,
    DEBUG_WIND_SPEED,
    DEBUG_GEN_SOUND,
    DEBUG_KILL_MONS,
    DEBUG_DISPLAY_HORDES,
    DEBUG_TEST_IT_GROUP,
    DEBUG_DAMAGE_SELF,
    DEBUG_SHOW_SOUND,
    DEBUG_DISPLAY_WEATHER,
    DEBUG_DISPLAY_SCENTS,
    DEBUG_DISPLAY_DISTRIBUTION_GRIDS,
    DEBUG_CHANGE_TIME,
    DEBUG_SET_AUTOMOVE,
    DEBUG_SHOW_MUT_CAT,
    DEBUG_SHOW_MUT_CHANCES,
    DEBUG_OM_EDITOR,
    DEBUG_BENCHMARK,
    DEBUG_BENCHMARK_FPS,
    DEBUG_OM_TELEPORT,
    DEBUG_OM_TELEPORT_COORDINATES,
    DEBUG_TRAIT_GROUP,
    DEBUG_SHOW_MSG,
    DEBUG_CRASH_GAME,
    DEBUG_RELOAD_TRANSLATIONS,
    DEBUG_MAP_EXTRA,
    DEBUG_DISPLAY_NPC_PATH,
    DEBUG_PRINT_FACTION_INFO,
    DEBUG_PRINT_NPC_MAGIC,
    DEBUG_QUIT_NOSAVE,
    DEBUG_TEST_WEATHER,
    DEBUG_SAVE_SCREENSHOT,
    DEBUG_BUG_REPORT,
    DEBUG_GAME_REPORT,
    DEBUG_DISPLAY_SCENTS_LOCAL,
    DEBUG_DISPLAY_SCENTS_TYPE_LOCAL,
    DEBUG_DISPLAY_TEMP,
    DEBUG_DISPLAY_VEHICLE_AI,
    DEBUG_DISPLAY_VISIBILITY,
    DEBUG_DISPLAY_LIGHTING,
    DEBUG_DISPLAY_RADIATION,
    DEBUG_DISPLAY_TRANSPARENCY,
    DEBUG_DISPLAY_SUBMAP_GRID,
    DEBUG_TEST_MAP_EXTRA_DISTRIBUTION,
    DEBUG_VEHICLE_BATTERY_CHARGE,
    DEBUG_HOUR_TIMER,
    DEBUG_NESTED_MAPGEN,
    DEBUG_RESET_IGNORED_MESSAGES,
    DEBUG_RELOAD_TILES,
};
Function Documentation
add_header()
static void debug_menu::add_header (uilist & mmenu, const std::string & str) static
Definition at line 1134 of file debug_menu.cpp.
{
    if( !mmenu.entries.empty() ) {
        mmenu.addentry( -1, false, -1, "" );
    }
    uilist_entry header( -1, false, -1, str, c_yellow, c_yellow );
    header.force_color = true;
    mmenu.entries.push_back( header );
}
References uilist::addentry(), c_yellow, uilist::entries, and uilist_entry::force_color.
Referenced by debug_menu::mission_debug::edit_npc(), debug_menu::mission_debug::edit_player(), and avatar::read().
benchmark()
void debug_menu::benchmark (const int max_difference, bench_kind kind)
Definition at line 1277 of file debug_menu.cpp.
{
    std::string bench_name;
    switch( kind ) {
        case bench_kind::FPS:
            bench_name = _( "FPS benchmark" );
            break;
        case bench_kind::DRAW:
            bench_name = _( "Draw benchmark" );
            break;
    }
    static_popup popup;
    //~ %s is benchmark name
    popup.on_top( true ).message( _( "%s in progress" ), bench_name );
    ui_manager::redraw();
    refresh_display(); // Show the popup
    // call the draw procedure as many times as possible in max_difference milliseconds
    auto start_tick = std::chrono::steady_clock::now();
    auto end_tick = start_tick;
    int64_t difference = 0;
    int draw_counter = 0;
    while( true ) {
        end_tick = std::chrono::steady_clock::now();
        difference = std::chrono::duration_cast<std::chrono::milliseconds>( end_tick - start_tick ).count();
        if( difference >= max_difference ) {
            break;
        }
        g->invalidate_main_ui_adaptor();
        inp_mngr.pump_events();
        ui_manager::redraw_invalidated();
        if( kind == bench_kind::FPS ) {
            refresh_display();
        }
        draw_counter++;
    }
    DebugLog( DL::Info, DC::Main ) << bench_name << ":\n" <<
                                   "\n| USE_TILES |  RENDERER | FRAMEBUFFER_ACCEL | USE_COLOR_MODULATED_TEXTURES | FPS |" <<
                                   "\n|:---:|:---:|:---:|:---:|:---:|\n| " <<
                                   get_option<bool>( "USE_TILES" ) << " | " <<
#if !defined(__ANDROID__)
                                   get_option<std::string>( "RENDERER" ) << " | " <<
#else
                                   get_option<bool>( "SOFTWARE_RENDERING" ) << " | " <<
#endif
                                   get_option<bool>( "FRAMEBUFFER_ACCEL" ) << " | " <<
                                   get_option<bool>( "USE_COLOR_MODULATED_TEXTURES" ) << " | " <<
                                   static_cast<int>( 1000.0 * draw_counter / static_cast<double>( difference ) ) << " |\n";
    std::string msg_txt;
    switch( kind ) {
        case bench_kind::FPS:
            //~ 'Refresh' here means draw + display, i.e. includes OS display delay.
            //~ This is the actual "FPS" people often measure in games.
            msg_txt = _( "Refreshed %1$d times in %2$.3f seconds.  (%3$.3f fps average)" );
            break;
        case bench_kind::DRAW:
            //~ 'Draw' here means time taken to draw the scene without displaying it.
            //~ It's a separate thing from "FPS", and is mostly useful for profiling
            //~ draw calls and measuring OS display delay caused by UI sync.
            msg_txt = _( "Drew %1$d times in %2$.3f seconds.  (%3$.3f per second average)" );
            break;
    }
    add_msg( m_info, msg_txt, draw_counter,
             difference / 1000.0, 1000.0 * draw_counter / static_cast<double>( difference ) );
}
References _, add_msg(), DebugLog, DRAW, FPS, g, Info, inp_mngr, m_info, Main, popup(), input_manager::pump_events(), ui_manager::redraw(), ui_manager::redraw_invalidated(), and refresh_display().
Referenced by debug().
character_edit_menu()
void debug_menu::character_edit_menu (Character & c)
Definition at line 501 of file debug_menu.cpp.
{
    npc *np = c.is_npc() ? static_cast<npc *>( &c ) : nullptr;
    player &p = static_cast<player &>( c );
    const tripoint start_view_offset = get_avatar().view_offset;
    std::string nmenu_label;
    if( np != nullptr ) {
        std::stringstream data;
        data << np->name << " " << ( np->male ? _( "Male" ) : _( "Female" ) ) << std::endl;
        data << np->myclass.obj().get_name() << "; " <<
             npc_attitude_name( np->get_attitude() ) << "; " <<
             ( np->get_faction() ? np->get_faction()->name : _( "no faction" ) ) << "; " <<
             ( np->get_faction() ? np->get_faction()->currency->nname( 1 ) : _( "no currency" ) )
             << "; " <<
             "api: " << np->get_faction_ver() << std::endl;
        if( np->has_destination() ) {
            data << string_format(
                     _( "Destination: %s %s" ), np->goal.to_string(),
                     overmap_buffer.ter( np->goal )->get_name() ) << std::endl;
        } else {
            data << _( "No destination." ) << std::endl;
        }
        data << string_format( _( "Trust: %d" ), np->op_of_u.trust ) << " "
             << string_format( _( "Fear: %d" ), np->op_of_u.fear ) << " "
             << string_format( _( "Value: %d" ), np->op_of_u.value ) << " "
             << string_format( _( "Anger: %d" ), np->op_of_u.anger ) << " "
             << string_format( _( "Owed: %d" ), np->op_of_u.owed ) << std::endl;
        data << string_format( _( "Aggression: %d" ),
                               static_cast<int>( np->personality.aggression ) ) << " "
             << string_format( _( "Bravery: %d" ), static_cast<int>( np->personality.bravery ) ) << " "
             << string_format( _( "Collector: %d" ), static_cast<int>( np->personality.collector ) ) << " "
             << string_format( _( "Altruism: %d" ), static_cast<int>( np->personality.altruism ) ) << std::endl;
        data << _( "Needs:" ) << std::endl;
        for( const auto &need : np->needs ) {
            data << need << std::endl;
        }
        data << string_format( _( "Total morale: %d" ), np->get_morale_level() ) << std::endl;
        nmenu_label = data.str();
    } else {
        nmenu_label = _( "Player" );
    }
    enum edit_character {
        pick, desc, skills, stats, items, delete_items, item_worn,
        hp, stamina, morale, pain, needs, healthy, status, mission_add, mission_edit,
        tele, mutate, npc_class, attitude, opinion, effects,
        learn_ma, unlock_recipes, learn_spells, level_spells
    };
    // Maybe TODO: this could actually be static if not for translations
    const std::vector<uilist_entry> static_entries = {{
            uilist_entry( edit_character::pick, true, 'p', _( "[p]ick different character" ) ),
            uilist_entry( edit_character::desc, true, 'D',  _( "Edit [D]escription - Name, Age, Height" ) ),
            uilist_entry( edit_character::skills, true, 's',  _( "Edit [s]kills" ) ),
            uilist_entry( edit_character::stats, true, 't',  _( "Edit s[t]ats" ) ),
            uilist_entry( edit_character::items, true, 'i',  _( "Grant [i]tems" ) ),
            uilist_entry( edit_character::delete_items, true, 'd',  _( "[d]elete (all) items" ) ),
            uilist_entry( edit_character::item_worn, true, 'w',  _( "[w]ear/[w]ield an item from player's inventory" ) ),
            uilist_entry( edit_character::hp, true, 'h',  _( "Set [h]it points" ) ),
            uilist_entry( edit_character::stamina, true, 'S',  _( "Set [S]tamina" ) ),
            uilist_entry( edit_character::morale, true, 'o',  _( "Set m[o]rale" ) ),
            uilist_entry( edit_character::pain, true, 'P',  _( "Cause [P]ain" ) ),
            uilist_entry( edit_character::healthy, true, 'a',  _( "Set he[a]lth" ) ),
            uilist_entry( edit_character::needs, true, 'n',  _( "Set [n]eeds" ) ),
            uilist_entry( edit_character::mutate, true, 'u',  _( "M[u]tate" ) ),
            uilist_entry( edit_character::status, true, '@',  _( "Status Window [@]" ) ),
            uilist_entry( edit_character::tele, true, 'e',  _( "t[e]leport" ) ),
            uilist_entry( edit_character::mission_edit, true, 'M',  _( "Edit [M]issions (WARNING: Unstable!)" ) ),
            uilist_entry( edit_character::effects, true, 'E',  _( "Edit [E]ffects" ) ),
            uilist_entry( edit_character::learn_ma, true, 'l', _( "[l]earn all melee styles" ) ),
            uilist_entry( edit_character::unlock_recipes, true, 'r', _( "Unlock all [r]ecipes" ) )
        }
    };
    std::vector<uilist_entry> menu_entries = static_entries;
    if( !spell_type::get_all().empty() ) {
        menu_entries.emplace_back( edit_character::learn_spells, true, 'L', _( "[L]earn all Spells" ) );
        menu_entries.emplace_back( edit_character::level_spells, true, 'v', _( "Le[v]el a spell" ) );
    }
    if( p.is_npc() ) {
        menu_entries.emplace_back( edit_character::mission_add, true, 'm',  _( "Add [m]ission" ) );
        menu_entries.emplace_back( edit_character::npc_class, true, 'c',
                                   _( "Randomize with [c]lass" ) );
        menu_entries.emplace_back( edit_character::attitude, true, 'A',  _( "Set [A]ttitude" ) );
        menu_entries.emplace_back( edit_character::opinion, true, 'O',  _( "Set [O]pinion" ) );
    }
    uilist nmenu( nmenu_label, menu_entries );
    switch( nmenu.ret ) {
        case edit_character::pick: {
            Character &other = pick_character( c );
            get_avatar().view_offset = other.pos() - get_avatar().pos();
            // TODO: Make it not able to cause a stack overflow
            character_edit_menu( other );
            get_avatar().view_offset = start_view_offset;
        }
        return;
        case edit_character::skills:
            wishskill( &p );
            break;
        case edit_character::stats: {
            uilist smenu;
            smenu.addentry( 0, true, 'S', "%s: %d", _( "Maximum strength" ), p.str_max );
            smenu.addentry( 1, true, 'D', "%s: %d", _( "Maximum dexterity" ), p.dex_max );
            smenu.addentry( 2, true, 'I', "%s: %d", _( "Maximum intelligence" ), p.int_max );
            smenu.addentry( 3, true, 'P', "%s: %d", _( "Maximum perception" ), p.per_max );
            smenu.query();
            int *bp_ptr = nullptr;
            switch( smenu.ret ) {
                case 0:
                    bp_ptr = &p.str_max;
                    break;
                case 1:
                    bp_ptr = &p.dex_max;
                    break;
                case 2:
                    bp_ptr = &p.int_max;
                    break;
                case 3:
                    bp_ptr = &p.per_max;
                    break;
                default:
                    break;
            }
            if( bp_ptr != nullptr ) {
                int value;
                if( query_int( value, _( "Set the stat to?  Currently: %d" ), *bp_ptr ) && value >= 0 ) {
                    *bp_ptr = value;
                    p.reset_stats();
                }
            }
        }
        break;
        case edit_character::items:
            wishitem( &p );
            break;
        case edit_character::delete_items:
            if( !query_yn( _( "Delete all items from the target?" ) ) ) {
                break;
            }
            for( auto &it : p.worn ) {
                it.on_takeoff( p );
            }
            p.worn.clear();
            p.inv.clear();
            p.weapon = item();
            break;
        case edit_character::item_worn: {
            item_location loc = game_menus::inv::titled_menu( g->u, _( "Make target equip" ) );
            if( !loc ) {
                break;
            }
            item &to_wear = *loc;
            if( to_wear.is_armor() ) {
                p.on_item_wear( to_wear );
                p.worn.push_back( to_wear );
            } else if( !to_wear.is_null() ) {
                p.weapon = to_wear;
            }
        }
        break;
        case edit_character::hp: {
            const int torso_hp = p.get_part_hp_cur( bodypart_id( "torso" ) );
            const int head_hp = p.get_part_hp_cur( bodypart_id( "head" ) );
            const int arm_l_hp = p.get_part_hp_cur( bodypart_id( "arm_l" ) );
            const int arm_r_hp = p.get_part_hp_cur( bodypart_id( "arm_r" ) );
            const int leg_l_hp = p.get_part_hp_cur( bodypart_id( "leg_l" ) );
            const int leg_r_hp = p.get_part_hp_cur( bodypart_id( "leg_r" ) );
            uilist smenu;
            smenu.addentry( 0, true, 'q', "%s: %d", _( "Torso" ), torso_hp );
            smenu.addentry( 1, true, 'w', "%s: %d", _( "Head" ), head_hp );
            smenu.addentry( 2, true, 'a', "%s: %d", _( "Left arm" ), arm_l_hp );
            smenu.addentry( 3, true, 's', "%s: %d", _( "Right arm" ), arm_r_hp );
            smenu.addentry( 4, true, 'z', "%s: %d", _( "Left leg" ), leg_l_hp );
            smenu.addentry( 5, true, 'x', "%s: %d", _( "Right leg" ), leg_r_hp );
            smenu.addentry( 6, true, 'e', "%s: %d", _( "All" ), p.get_lowest_hp() );
            smenu.query();
            bodypart_str_id bp = bodypart_str_id( "no_a_real_part" );
            int bp_ptr = -1;
            bool all_select = false;
            switch( smenu.ret ) {
                case 0:
                    bp = bodypart_str_id( "torso" );
                    bp_ptr = torso_hp;
                    break;
                case 1:
                    bp = bodypart_str_id( "head" );
                    bp_ptr = head_hp;
                    break;
                case 2:
                    bp = bodypart_str_id( "arm_l" );
                    bp_ptr = arm_l_hp;
                    break;
                case 3:
                    bp = bodypart_str_id( "arm_r" );
                    bp_ptr = arm_r_hp;
                    break;
                case 4:
                    bp = bodypart_str_id( "leg_l" );
                    bp_ptr = leg_l_hp;
                    break;
                case 5:
                    bp = bodypart_str_id( "leg_r" );
                    bp_ptr = leg_r_hp;
                    break;
                case 6:
                    all_select = true;
                    break;
                default:
                    break;
            }
            if( bp.is_valid() ) {
                int value;
                if( query_int( value, _( "Set the hitpoints to?  Currently: %d" ), bp_ptr ) && value >= 0 ) {
                    p.set_part_hp_cur( bp.id(), value );
                    p.reset_stats();
                }
            } else if( all_select ) {
                int value;
                if( query_int( value, _( "Set the hitpoints to?  Currently: %d" ), p.get_lowest_hp() ) &&
                    value >= 0 ) {
                    p.set_all_parts_hp_cur( value );
                    p.reset_stats();
                }
            }
        }
        break;
        case edit_character::stamina:
            int value;
            if( query_int( value, _( "Set stamina to?  Current: %d. Max: %d." ), p.get_stamina(),
                           p.get_stamina_max() ) ) {
                if( value >= 0 && value <= p.get_stamina_max() ) {
                    p.set_stamina( value );
                } else {
                    add_msg( m_bad, _( "Target stamina value out of bounds!" ) );
                }
            }
            break;
        case edit_character::morale: {
            int current_morale_level = p.get_morale_level();
            int value;
            if( query_int( value, _( "Set the morale to?  Currently: %d" ), current_morale_level ) ) {
                int morale_level_delta = value - current_morale_level;
                p.add_morale( MORALE_PERM_DEBUG, morale_level_delta );
                p.apply_persistent_morale();
            }
        }
        break;
        case edit_character::opinion: {
            if( np == nullptr ) {
                // HACK: For some reason, tidy is not satisfied with simple assert(np)
                std::abort();
            }
            uilist smenu;
            smenu.addentry( 0, true, 'h', "%s: %d", _( "trust" ), np->op_of_u.trust );
            smenu.addentry( 1, true, 's', "%s: %d", _( "fear" ), np->op_of_u.fear );
            smenu.addentry( 2, true, 't', "%s: %d", _( "value" ), np->op_of_u.value );
            smenu.addentry( 3, true, 'f', "%s: %d", _( "anger" ), np->op_of_u.anger );
            smenu.addentry( 4, true, 'd', "%s: %d", _( "owed" ), np->op_of_u.owed );
            smenu.query();
            int value;
            switch( smenu.ret ) {
                case 0:
                    if( query_int( value, _( "Set trust to?  Currently: %d" ),
                                   np->op_of_u.trust ) ) {
                        np->op_of_u.trust = value;
                    }
                    break;
                case 1:
                    if( query_int( value, _( "Set fear to?  Currently: %d" ), np->op_of_u.fear ) ) {
                        np->op_of_u.fear = value;
                    }
                    break;
                case 2:
                    if( query_int( value, _( "Set value to?  Currently: %d" ),
                                   np->op_of_u.value ) ) {
                        np->op_of_u.value = value;
                    }
                    break;
                case 3:
                    if( query_int( value, _( "Set anger to?  Currently: %d" ),
                                   np->op_of_u.anger ) ) {
                        np->op_of_u.anger = value;
                    }
                    break;
                case 4:
                    if( query_int( value, _( "Set owed to?  Currently: %d" ), np->op_of_u.owed ) ) {
                        np->op_of_u.owed = value;
                    }
                    break;
            }
        }
        break;
        case edit_character::desc: {
            uilist smenu;
            smenu.text = _( "Select a value and press enter to change it." );
            smenu.addentry( 0, true, 'n', "%s: %s", _( "Current name" ), p.get_name() );
            smenu.addentry( 1, true, 'a', "%s: %d", _( "Current age" ), p.base_age() );
            smenu.addentry( 2, true, 'h', "%s: %d", _( "Current height in cm" ), p.base_height() );
            smenu.query();
            switch( smenu.ret ) {
                case 0: {
                    std::string buf = p.name;
                    string_input_popup popup;
                    popup
                    .title( _( "Rename:" ) )
                    .width( 85 )
                    .edit( buf );
                    if( popup.confirmed() ) {
                        p.name = buf;
                    }
                }
                break;
                case 1: {
                    string_input_popup popup;
                    popup
                    .title( _( "Enter age in years.  Minimum 16, maximum 55" ) )
                    .text( string_format( "%d", p.base_age() ) )
                    .only_digits( true );
                    const int result = popup.query_int();
                    if( result != 0 ) {
                        p.set_base_age( clamp( result, 16, 55 ) );
                    }
                }
                break;
                case 2: {
                    string_input_popup popup;
                    popup
                    .title( _( "Enter height in centimeters.  Minimum 145, maximum 200" ) )
                    .text( string_format( "%d", p.base_height() ) )
                    .only_digits( true );
                    const int result = popup.query_int();
                    if( result != 0 ) {
                        p.set_base_height( clamp( result, 145, 200 ) );
                    }
                }
                break;
            }
        }
        break;
        case edit_character::pain: {
            int value;
            if( query_int( value, _( "Cause how much pain?  pain: %d" ), p.get_pain() ) ) {
                p.mod_pain( value );
            }
        }
        break;
        case edit_character::needs: {
            uilist smenu;
            smenu.addentry( 0, true, 's', "%s: %d", _( "Stored kCal" ), p.get_stored_kcal() );
            smenu.addentry( 1, true, 't', "%s: %d", _( "Thirst" ), p.get_thirst() );
            smenu.addentry( 2, true, 'f', "%s: %d", _( "Fatigue" ), p.get_fatigue() );
            smenu.addentry( 3, true, 'd', "%s: %d", _( "Sleep Deprivation" ), p.get_sleep_deprivation() );
            smenu.addentry( 4, true, 'a', _( "Reset all basic needs" ) );
            const auto &vits = vitamin::all();
            for( const auto &v : vits ) {
                smenu.addentry( -1, true, 0, "%s: %d", v.second.name(), p.vitamin_get( v.first ) );
            }
            smenu.query();
            int value;
            switch( smenu.ret ) {
                case 0:
                    if( query_int( value, _( "Set stored kCal to?  Currently: %d" ), p.get_stored_kcal() ) ) {
                        p.set_stored_kcal( value );
                    }
                    break;
                case 1:
                    if( query_int( value, _( "Set thirst to?  Currently: %d" ), p.get_thirst() ) ) {
                        p.set_thirst( value );
                    }
                    break;
                case 2:
                    if( query_int( value, _( "Set fatigue to?  Currently: %d" ), p.get_fatigue() ) ) {
                        p.set_fatigue( value );
                    }
                    break;
                case 3:
                    if( query_int( value, _( "Set sleep deprivation to?  Currently: %d" ),
                                   p.get_sleep_deprivation() ) ) {
                        p.set_sleep_deprivation( value );
                    }
                    break;
                case 4:
                    p.set_thirst( 0 );
                    p.set_fatigue( 0 );
                    p.set_sleep_deprivation( 0 );
                    p.set_stored_kcal( p.max_stored_kcal() );
                    break;
                default:
                    const int non_vitamin_entries = smenu.entries.size() - vits.size();
                    if( smenu.ret >= non_vitamin_entries &&
                        smenu.ret < static_cast<int>( vits.size() + non_vitamin_entries ) ) {
                        auto iter = std::next( vits.begin(), smenu.ret - non_vitamin_entries );
                        if( query_int( value, _( "Set %s to?  Currently: %d" ),
                                       iter->second.name(), p.vitamin_get( iter->first ) ) ) {
                            p.vitamin_set( iter->first, value );
                        }
                    }
            }
        }
        break;
        case edit_character::mutate:
            wishmutate( &p );
            break;
        case edit_character::healthy: {
            uilist smenu;
            smenu.addentry( 0, true, 'h', "%s: %d", _( "Health" ), p.get_healthy() );
            smenu.addentry( 1, true, 'm', "%s: %d", _( "Health modifier" ), p.get_healthy_mod() );
            smenu.addentry( 2, true, 'r', "%s: %d", _( "Radiation" ), p.get_rad() );
            smenu.query();
            int value;
            switch( smenu.ret ) {
                case 0:
                    if( query_int( value, _( "Set the value to?  Currently: %d" ), p.get_healthy() ) ) {
                        p.set_healthy( value );
                    }
                    break;
                case 1:
                    if( query_int( value, _( "Set the value to?  Currently: %d" ), p.get_healthy_mod() ) ) {
                        p.set_healthy_mod( value );
                    }
                    break;
                case 2:
                    if( query_int( value, _( "Set the value to?  Currently: %d" ), p.get_rad() ) ) {
                        p.set_rad( value );
                    }
                    break;
                default:
                    break;
            }
        }
        break;
        case edit_character::status:
            character_display::disp_info( p );
            break;
        case edit_character::mission_add: {
            uilist types;
            types.text = _( "Choose mission type" );
            const auto all_missions = mission_type::get_all();
            std::vector<const mission_type *> mts;
            for( size_t i = 0; i < all_missions.size(); i++ ) {
                types.addentry( i, true, -1, all_missions[i].tname() );
                mts.push_back( &all_missions[i] );
            }
            types.query();
            if( types.ret >= 0 && types.ret < static_cast<int>( mts.size() ) ) {
                np->add_new_mission( mission::reserve_new( mts[types.ret]->id, np->getID() ) );
            }
        }
        break;
        case edit_character::mission_edit:
            mission_debug::edit( p );
            break;
        case edit_character::tele: {
            if( const cata::optional<tripoint> newpos = g->look_around( true ) ) {
                p.setpos( *newpos );
                if( p.is_player() ) {
                    if( p.is_mounted() ) {
                        p.mounted_creature->setpos( *newpos );
                    }
                    g->update_map( g->u );
                }
            }
        }
        break;
        case edit_character::npc_class: {
            uilist classes;
            classes.text = _( "Choose new class" );
            std::vector<npc_class_id> ids;
            size_t i = 0;
            for( auto &cl : npc_class::get_all() ) {
                ids.push_back( cl.id );
                classes.addentry( i, true, -1, cl.get_name() );
                i++;
            }
            classes.query();
            if( classes.ret < static_cast<int>( ids.size() ) && classes.ret >= 0 ) {
                np->randomize( ids[classes.ret] );
            }
        }
        break;
        case edit_character::attitude: {
            uilist attitudes_ui;
            attitudes_ui.text = _( "Choose new attitude" );
            std::vector<npc_attitude> attitudes;
            for( int i = NPCATT_NULL; i < NPCATT_END; i++ ) {
                npc_attitude att_id = static_cast<npc_attitude>( i );
                std::string att_name = npc_attitude_name( att_id );
                attitudes.push_back( att_id );
                if( att_name == _( "Unknown attitude" ) ) {
                    continue;
                }
                attitudes_ui.addentry( i, true, -1, att_name );
            }
            attitudes_ui.query();
            if( attitudes_ui.ret < static_cast<int>( attitudes.size() ) && attitudes_ui.ret >= 0 ) {
                np->set_attitude( attitudes[attitudes_ui.ret] );
            }
        }
        break;
        case edit_character::learn_ma:
            add_msg( m_info, _( "Martial arts debug." ) );
            add_msg( _( "Your eyes blink rapidly as knowledge floods your brain." ) );
            for( auto &style : all_martialart_types() ) {
                if( style != matype_id( "style_none" ) ) {
                    c.martial_arts_data->add_martialart( style );
                }
            }
            add_msg( m_good, _( "You now know a lot more than just 10 styles of kung fu." ) );
            break;
        case edit_character::effects:
            effect_edit_menu( c );
            break;
        case edit_character::unlock_recipes: {
            add_msg( m_info, _( "Recipe debug." ) );
            add_msg( _( "Your eyes blink rapidly as knowledge floods your brain." ) );
            for( const auto &e : recipe_dict ) {
                p.learn_recipe( &e.second );
            }
            add_msg( m_good, _( "You know how to craft that now." ) );
        }
        break;
        case edit_character::learn_spells:
            if( spell_type::get_all().empty() ) {
                add_msg( m_bad, _( "There are no spells to learn.  You must install a mod that adds some." ) );
            } else {
                for( const spell_type &learn : spell_type::get_all() ) {
                    c.magic->learn_spell( &learn, g->u, true );
                }
                add_msg( m_good,
                         _( "You have become an Archwizardpriest!  What will you do with your newfound power?" ) );
            }
            break;
        case edit_character::level_spells: {
            std::vector<spell *> spells = c.magic->get_spells();
            if( spells.empty() ) {
                add_msg( m_bad, _( "Try learning some spells first." ) );
                return;
            }
            std::vector<uilist_entry> uiles;
            {
                uilist_entry uile( _( "Spell" ) );
                uile.ctxt = string_format( "%s %s",
                                           //~ translation should not exceed 4 console cells
                                           right_justify( _( "LVL" ), 4 ),
                                           //~ translation should not exceed 4 console cells
                                           right_justify( _( "MAX" ), 4 ) );
                uile.enabled = false;
                uile.force_color = c_light_blue;
                uiles.emplace_back( uile );
            }
            int retval = 0;
            for( spell *sp : spells ) {
                uilist_entry uile( sp->name() );
                uile.ctxt = string_format( "%4d %4d", sp->get_level(), sp->get_max_level() );
                uile.retval = retval++;
                uile.enabled = !sp->is_max_level();
                uiles.emplace_back( uile );
            }
            int action = uilist( _( "Debug level spell:" ), uiles );
            if( action < 0 ) {
                break;
            }
            int desired_level = 0;
            int cur_level = spells[action]->get_level();
            query_int( desired_level, _( "Desired Spell Level: (Current %d)" ), cur_level );
            desired_level = std::min( desired_level, spells[action]->get_max_level() );
            while( cur_level < desired_level ) {
                spells[action]->gain_level();
                cur_level = spells[action]->get_level();
            }
            add_msg( m_good, _( "%s is now level %d!" ), spells[action]->name(), spells[action]->get_level() );
            break;
        }
        case UILIST_CANCEL:
            return;
    }
    // TODO: Stack overflow possibility
    character_edit_menu( c );
}
References _, action, Character::add_morale(), add_msg(), npc::add_new_mission(), uilist::addentry(), npc_personality::aggression, vitamin::all(), all_martialart_types(), npc_personality::altruism, npc_opinion::anger, Character::apply_persistent_morale(), Character::base_age(), Character::base_height(), npc_personality::bravery, c, c_light_blue, character_edit_menu(), clamp(), inventory::clear(), npc_personality::collector, uilist_entry::ctxt, faction_template::currency, Character::dex_max, character_display::disp_info(), debug_menu::mission_debug::edit(), effect_edit_menu(), uilist_entry::enabled, uilist::entries, npc_opinion::fear, uilist_entry::force_color, g, spell_type::get_all(), mission_type::get_all(), npc_class::get_all(), npc::get_attitude(), get_avatar(), npc::get_faction(), npc::get_faction_ver(), Character::get_fatigue(), Character::get_healthy(), Character::get_healthy_mod(), Character::get_lowest_hp(), Character::get_morale_level(), npc_class::get_name(), oter_t::get_name(), Character::get_name(), Creature::get_pain(), Creature::get_part_hp_cur(), Character::get_rad(), Character::get_sleep_deprivation(), Character::get_stamina(), Character::get_stamina_max(), Character::get_stored_kcal(), Character::get_thirst(), Character::getID(), npc::goal, Character::has_destination(), hp, string_id< T >::id(), Character::int_max, Character::inv, item::is_armor(), Character::is_mounted(), player::is_npc(), item::is_null(), player::is_player(), string_id< T >::is_valid(), Character::learn_recipe(), learn_spells(), m_bad, m_good, m_info, Character::male, Character::max_stored_kcal(), Character::mod_pain(), spell_effect::morale(), MORALE_PERM_DEBUG, Character::mounted_creature, spell_effect::mutate(), npc::myclass, Character::name, faction_template::name, npc::needs, itype::nname(), npc_attitude_name(), NPCATT_END, NPCATT_NULL, string_id< T >::obj(), Character::on_item_wear(), npc::op_of_u, other, overmap_buffer, npc_opinion::owed, pain, Character::per_max, npc::personality, pick_character(), popup(), Character::pos(), uilist::query(), query_int(), query_yn(), npc::randomize(), recipe_dict, mission::reserve_new(), Character::reset_stats(), uilist::ret, uilist_entry::retval, right_justify(), Creature::set_all_parts_hp_cur(), npc::set_attitude(), Character::set_base_age(), Character::set_base_height(), Character::set_fatigue(), Character::set_healthy(), Character::set_healthy_mod(), Creature::set_part_hp_cur(), Character::set_rad(), Character::set_sleep_deprivation(), Character::set_stamina(), Character::set_stored_kcal(), Character::set_thirst(), Character::setpos(), Character::str_max, string_format(), overmapbuffer::ter(), uilist::text, game_menus::inv::titled_menu(), coords::coord_point< Point, Origin, Scale >::to_string(), npc_opinion::trust, UILIST_CANCEL, npc_opinion::value, player::view_offset, Character::vitamin_get(), Character::vitamin_set(), Character::weapon, wishitem(), wishmutate(), wishskill(), and Character::worn.
Referenced by character_edit_menu(), and debug_menu_uilist().
debug()
void debug_menu::debug ()
Definition at line 1347 of file debug_menu.cpp.
{
    bool debug_menu_has_hotkey = hotkey_for_action( ACTION_DEBUG, false ) != -1;
    int action = debug_menu_uilist( debug_menu_has_hotkey );
    avatar &u = g->u;
    map &m = g->m;
    switch( action ) {
        case DEBUG_WISH:
            debug_menu::wishitem( &u );
            break;
        case DEBUG_SHORT_TELEPORT:
            debug_menu::teleport_short();
            break;
        case DEBUG_LONG_TELEPORT:
            debug_menu::teleport_long();
            break;
        case DEBUG_REVEAL_MAP: {
            auto &cur_om = g->get_cur_om();
            for( int i = 0; i < OMAPX; i++ ) {
                for( int j = 0; j < OMAPY; j++ ) {
                    for( int k = -OVERMAP_DEPTH; k <= OVERMAP_HEIGHT; k++ ) {
                        cur_om.seen( { i, j, k } ) = true;
                    }
                }
            }
            add_msg( m_good, _( "Current overmap revealed." ) );
        }
        break;
        case DEBUG_SPAWN_NPC: {
            shared_ptr_fast<npc> temp = make_shared_fast<npc>();
            temp->randomize();
            temp->spawn_at_precise( { g->get_levx(), g->get_levy() }, u.pos() + point( -4, -4 ) );
            overmap_buffer.insert_npc( temp );
            temp->form_opinion( u );
            temp->mission = NPC_MISSION_NULL;
            temp->add_new_mission( mission::reserve_random( ORIGIN_ANY_NPC, temp->global_omt_location(),
                                   temp->getID() ) );
            std::string new_fac_id = "solo_";
            new_fac_id += temp->name;
            // create a new "lone wolf" faction for this one NPC
            faction *new_solo_fac = g->faction_manager_ptr->add_new_faction( temp->name,
                                    faction_id( new_fac_id ), faction_id( "no_faction" ) );
            temp->set_fac( new_solo_fac ? new_solo_fac->id : faction_id( "no_faction" ) );
            g->load_npcs();
        }
        break;
        case DEBUG_SPAWN_MON:
            debug_menu::wishmonster( cata::nullopt );
            break;
        case DEBUG_GAME_STATE: {
            std::string mfus;
            std::vector<std::pair<m_flag, int>> sorted;
            for( int f = 0; f < m_flag::MF_MAX; f++ ) {
                sorted.push_back( {static_cast<m_flag>( f ), MonsterGenerator::generator().m_flag_usage_stats[f]} );
            }
            std::sort( sorted.begin(), sorted.end(), []( std::pair<m_flag, int> a, std::pair<m_flag, int> b ) {
                return a.second != b.second ? a.second > b.second : a.first < b.first;
            } );
            for( auto &m_flag_stat : sorted ) {
                mfus += string_format( "%s;%d\n", io::enum_to_string<m_flag>( m_flag_stat.first ),
                                       m_flag_stat.second );
            }
            DebugLog( DL::Info, DC::Main ) << "Monster flag usage statistics:\nFLAG;COUNT\n" << mfus;
            std::fill( MonsterGenerator::generator().m_flag_usage_stats.begin(),
                       MonsterGenerator::generator().m_flag_usage_stats.end(), 0 );
            popup_top( "Monster flag usage statistics were dumped to debug.log and cleared." );
            std::string s = _( "Location %d:%d in %d:%d, %s\n" );
            s += _( "Current turn: %d.\n%s\n" );
            s += vgettext( "%d creature exists.\n", "%d creatures exist.\n", g->num_creatures() );
            popup_top(
                s.c_str(),
                u.posx(), g->u.posy(), g->get_levx(), g->get_levy(),
                overmap_buffer.ter( g->u.global_omt_location() )->get_name(),
                to_turns<int>( calendar::turn - calendar::turn_zero ),
                get_option<bool>( "RANDOM_NPC" ) ? _( "NPCs are going to spawn." ) :
                _( "NPCs are NOT going to spawn." ),
                g->num_creatures() );
            for( const npc &guy : g->all_npcs() ) {
                tripoint t = guy.global_sm_location();
                add_msg( m_info, _( "%s: map ( %d:%d ) pos ( %d:%d )" ), guy.name, t.x,
                         t.y, guy.posx(), guy.posy() );
            }
            add_msg( m_info, _( "(you: %d:%d)" ), u.posx(), u.posy() );
            add_msg( m_info, _( "Thirst: %d, kCal: %d / %d" ), u.get_thirst(), u.get_stored_kcal(),
                     u.max_stored_kcal() );
            add_msg( m_info, _( "Body Mass Index: %.0f\nBasal Metabolic Rate: %i" ), u.bmi(), u.bmr() );
            if( get_option<bool>( "STATS_THROUGH_KILLS" ) ) {
                add_msg( m_info, _( "Kill xp: %d" ), u.kill_xp() );
            }
            g->invalidate_main_ui_adaptor();
            g->disp_NPCs();
            break;
        }
        case DEBUG_KILL_AREA: {
            static_popup popup;
            popup.on_top( true );
            popup.message( "%s", _( "Select first point." ) );
            tripoint initial_pos = g->u.pos();
            const look_around_result first = g->look_around( false, initial_pos, initial_pos,
                                             false, true, false, false, tripoint_zero, true );
            if( !first.position ) {
                break;
            }
            popup.message( "%s", _( "Select second point." ) );
            const look_around_result second = g->look_around( false, initial_pos, *first.position,
                                              true, true, false, false, tripoint_zero, true );
            if( !second.position ) {
                break;
            }
            const tripoint_range<tripoint> points = get_map().points_in_rectangle(
                    first.position.value(), second.position.value() );
            std::vector<Creature *> creatures = g->get_creatures_if(
            [&points]( const Creature & critter ) -> bool {
                return !critter.is_avatar() && points.is_point_inside( critter.pos() );
            } );
            for( Creature *critter : creatures ) {
                critter->die( nullptr );
            }
            g->cleanup_dead();
        }
        break;
        case DEBUG_KILL_NPCS:
            for( npc &guy : g->all_npcs() ) {
                add_msg( _( "%s's head implodes!" ), guy.name );
                guy.set_part_hp_cur( bodypart_id( "head" ), 0 );
            }
            break;
        case DEBUG_MUTATE:
            debug_menu::wishmutate( &u );
            break;
        case DEBUG_SPAWN_VEHICLE:
            if( m.veh_at( u.pos() ) ) {
                add_msg( m_bad, "There's already vehicle here." );
            } else {
                // Vector of name, id so that we can sort by name
                std::vector<std::pair<std::string, vproto_id>> veh_strings;
                for( auto &elem : vehicle_prototype::get_all() ) {
                    if( elem == vproto_id( "custom" ) ) {
                        continue;
                    }
                    veh_strings.emplace_back( _( elem->name ), elem );
                }
                std::sort( veh_strings.begin(), veh_strings.end(), localized_compare );
                uilist veh_menu;
                veh_menu.text = _( "Choose vehicle to spawn" );
                int menu_ind = 0;
                for( auto &elem : veh_strings ) {
                    //~ Menu entry in vehicle wish menu: 1st string: displayed name, 2nd string: internal name of vehicle
                    veh_menu.addentry( menu_ind, true, MENU_AUTOASSIGN, _( "%1$s (%2$s)" ),
                                       elem.first, elem.second.c_str() );
                    ++menu_ind;
                }
                veh_menu.query();
                if( veh_menu.ret >= 0 && veh_menu.ret < static_cast<int>( veh_strings.size() ) ) {
                    // Didn't cancel
                    const vproto_id &selected_opt = veh_strings[veh_menu.ret].second;
                    tripoint dest = u.pos();
                    uilist veh_cond_menu;
                    veh_cond_menu.text = _( "Vehicle condition" );
                    veh_cond_menu.addentry( 0, true, MENU_AUTOASSIGN, _( "Light damage" ) );
                    veh_cond_menu.addentry( 1, true, MENU_AUTOASSIGN, _( "Undamaged" ) );
                    veh_cond_menu.addentry( 2, true, MENU_AUTOASSIGN, _( "Disabled (tires or engine)" ) );
                    veh_cond_menu.query();
                    if( veh_cond_menu.ret >= 0 && veh_cond_menu.ret < 3 ) {
                        int dir = 0;
                        if( query_int( dir, -90, _( "Vehicle direction (in degrees): " ) ) ) {
                            vehicle *veh = m.add_vehicle( selected_opt, dest,
                                                          normalize( units::from_degrees( dir ) ),
                                                          100, veh_cond_menu.ret - 1 );
                            if( veh != nullptr ) {
                                m.board_vehicle( dest, &u );
                            }
                        }
                    }
                }
            }
            break;
        case DEBUG_SPAWN_ARTIFACT:
            if( const cata::optional<tripoint> center = g->look_around( true ) ) {
                artifact_natural_property prop = static_cast<artifact_natural_property>( rng( ARTPROP_NULL + 1,
                                                 ARTPROP_MAX - 1 ) );
                m.create_anomaly( *center, prop );
                m.spawn_natural_artifact( *center, prop );
            }
            break;
        case DEBUG_SPAWN_CLAIRVOYANCE:
            u.i_add( item( "architect_cube", calendar::turn ) );
            break;
        case DEBUG_MAP_EDITOR:
            g->look_debug();
            break;
        case DEBUG_CHANGE_WEATHER: {
            weather_manager &weather = get_weather();
            uilist weather_menu;
            weather_menu.text = _( "Select new weather pattern:" );
            weather_menu.addentry( 0, true, MENU_AUTOASSIGN, !weather.weather_override ?
                                   _( "Keep normal weather patterns" ) : _( "Disable weather forcing" ) );
            for( size_t i = 0; i < weather_types::get_all().size(); i++ ) {
                weather_menu.addentry( i, true, MENU_AUTOASSIGN,
                                       weather_types::get_all()[i].name.translated() );
            }
            weather_menu.query();
            if( weather_menu.ret >= 0 &&
                static_cast<size_t>( weather_menu.ret ) < weather_types::get_all().size() ) {
                const weather_type_id selected_weather = weather_types::get_all()[weather_menu.ret].id;
                weather.weather_override = selected_weather;
                weather.set_nextweather( calendar::turn );
            }
        }
        break;
        case DEBUG_WIND_DIRECTION: {
            weather_manager &weather = get_weather();
            uilist wind_direction_menu;
            wind_direction_menu.text = _( "Select new wind direction:" );
            wind_direction_menu.addentry( 0, true, MENU_AUTOASSIGN, weather.wind_direction_override ?
                                          _( "Disable direction forcing" ) : _( "Keep normal wind direction" ) );
            int count = 1;
            for( int angle = 0; angle <= 315; angle += 45 ) {
                wind_direction_menu.addentry( count, true, MENU_AUTOASSIGN, get_wind_arrow( angle ) );
                count += 1;
            }
            wind_direction_menu.query();
            if( wind_direction_menu.ret == 0 ) {
                weather.wind_direction_override = cata::nullopt;
            } else if( wind_direction_menu.ret >= 0 && wind_direction_menu.ret < 9 ) {
                weather.wind_direction_override = ( wind_direction_menu.ret - 1 ) * 45;
                weather.set_nextweather( calendar::turn );
            }
        }
        break;
        case DEBUG_WIND_SPEED: {
            weather_manager &weather = get_weather();
            uilist wind_speed_menu;
            wind_speed_menu.text = _( "Select new wind speed:" );
            wind_speed_menu.addentry( 0, true, MENU_AUTOASSIGN, weather.wind_direction_override ?
                                      _( "Disable speed forcing" ) : _( "Keep normal wind speed" ) );
            int count = 1;
            for( int speed = 0; speed <= 100; speed += 10 ) {
                std::string speedstring = std::to_string( speed ) + " " + velocity_units( VU_WIND );
                wind_speed_menu.addentry( count, true, MENU_AUTOASSIGN, speedstring );
                count += 1;
            }
            wind_speed_menu.query();
            if( wind_speed_menu.ret == 0 ) {
                weather.windspeed_override = cata::nullopt;
            } else if( wind_speed_menu.ret >= 0 && wind_speed_menu.ret < 12 ) {
                int selected_wind_speed = ( wind_speed_menu.ret - 1 ) * 10;
                weather.windspeed_override = selected_wind_speed;
                weather.set_nextweather( calendar::turn );
            }
        }
        break;
        case DEBUG_GEN_SOUND: {
            const cata::optional<tripoint> where = g->look_around( true );
            if( !where ) {
                return;
            }
            int volume;
            if( !query_int( volume, _( "Volume of sound: " ) ) ) {
                return;
            }
            if( volume < 0 ) {
                return;
            }
            sounds::sound( *where, volume, sounds::sound_t::order, string_format( _( "DEBUG SOUND ( %d )" ),
                           volume ) );
        }
        break;
        case DEBUG_KILL_MONS: {
            for( monster &critter : g->all_monsters() ) {
                // Use the normal death functions, useful for testing death
                // and for getting a corpse.
                if( critter.type->id != mon_generator ) {
                    critter.die( nullptr );
                }
            }
            g->cleanup_dead();
        }
        break;
        case DEBUG_DISPLAY_HORDES:
            ui::omap::display_hordes();
            break;
        case DEBUG_TEST_IT_GROUP: {
            item_group::debug_spawn();
        }
        break;
        // Damage Self
        case DEBUG_DAMAGE_SELF: {
            const int torso_hp = u.get_part_hp_cur( bodypart_id( "torso" ) );
            const int head_hp = u.get_part_hp_cur( bodypart_id( "head" ) );
            const int arm_l_hp = u.get_part_hp_cur( bodypart_id( "arm_l" ) );
            const int arm_r_hp = u.get_part_hp_cur( bodypart_id( "arm_r" ) );
            const int leg_l_hp = u.get_part_hp_cur( bodypart_id( "leg_l" ) );
            const int leg_r_hp = u.get_part_hp_cur( bodypart_id( "leg_r" ) );
            uilist smenu;
            smenu.addentry( 0, true, 'q', "%s: %d", _( "Torso" ), torso_hp );
            smenu.addentry( 1, true, 'w', "%s: %d", _( "Head" ), head_hp );
            smenu.addentry( 2, true, 'a', "%s: %d", _( "Left arm" ), arm_l_hp );
            smenu.addentry( 3, true, 's', "%s: %d", _( "Right arm" ), arm_r_hp );
            smenu.addentry( 4, true, 'z', "%s: %d", _( "Left leg" ), leg_l_hp );
            smenu.addentry( 5, true, 'x', "%s: %d", _( "Right leg" ), leg_r_hp );
            smenu.query();
            bodypart_id part;
            int dbg_damage;
            switch( smenu.ret ) {
                case 0:
                    part = bodypart_id( "torso" );
                    break;
                case 1:
                    part = bodypart_id( "head" );
                    break;
                case 2:
                    part = bodypart_id( "arm_l" );
                    break;
                case 3:
                    part = bodypart_id( "arm_r" );
                    break;
                case 4:
                    part = bodypart_id( "leg_l" );
                    break;
                case 5:
                    part = bodypart_id( "leg_r" );
                    break;
                default:
                    break;
            }
            if( query_int( dbg_damage, _( "Damage self for how much?  hp: %s" ), part.id().c_str() ) ) {
                u.apply_damage( nullptr, part, dbg_damage );
                u.die( nullptr );
            }
        }
        break;
        case DEBUG_SHOW_SOUND: {
#if defined(TILES)
            const auto &sounds_to_draw = sounds::get_monster_sounds();
            shared_ptr_fast<game::draw_callback_t> sound_cb = make_shared_fast<game::draw_callback_t>( [&]() {
                const point offset {
                    u.view_offset.xy() + point( POSX - u.posx(), POSY - u.posy() )
                };
                for( const auto &sound : sounds_to_draw.first ) {
                    mvwputch( g->w_terrain, offset + sound.xy(), c_yellow, '?' );
                }
                for( const auto &sound : sounds_to_draw.second ) {
                    mvwputch( g->w_terrain, offset + sound.xy(), c_red, '?' );
                }
            } );
            g->add_draw_callback( sound_cb );
            ui_manager::redraw();
            inp_mngr.wait_for_any_key();
#else
            popup( _( "This binary was not compiled with tiles support." ) );
#endif
        }
        break;
        case DEBUG_DISPLAY_WEATHER:
            ui::omap::display_weather();
            break;
        case DEBUG_DISPLAY_SCENTS:
            ui::omap::display_scents();
            break;
        case DEBUG_DISPLAY_DISTRIBUTION_GRIDS:
            ui::omap::display_distribution_grids();
            break;
        case DEBUG_DISPLAY_SCENTS_LOCAL:
            g->display_toggle_overlay( ACTION_DISPLAY_SCENT );
            break;
        case DEBUG_DISPLAY_SCENTS_TYPE_LOCAL:
            g->display_toggle_overlay( ACTION_DISPLAY_SCENT_TYPE );
            break;
        case DEBUG_DISPLAY_TEMP:
            g->display_toggle_overlay( ACTION_DISPLAY_TEMPERATURE );
            break;
        case DEBUG_DISPLAY_VEHICLE_AI:
            g->display_toggle_overlay( ACTION_DISPLAY_VEHICLE_AI );
            break;
        case DEBUG_DISPLAY_VISIBILITY:
            g->display_toggle_overlay( ACTION_DISPLAY_VISIBILITY );
            break;
        case DEBUG_DISPLAY_LIGHTING:
            g->display_toggle_overlay( ACTION_DISPLAY_LIGHTING );
            break;
        case DEBUG_DISPLAY_RADIATION:
            g->display_toggle_overlay( ACTION_DISPLAY_RADIATION );
            break;
        case DEBUG_DISPLAY_TRANSPARENCY:
            g->display_toggle_overlay( ACTION_DISPLAY_TRANSPARENCY );
            break;
        case DEBUG_DISPLAY_SUBMAP_GRID:
            g->debug_submap_grid_overlay = !g->debug_submap_grid_overlay;
            break;
        case DEBUG_HOUR_TIMER:
            g->toggle_debug_hour_timer();
            break;
        case DEBUG_CHANGE_TIME: {
            auto set_turn = [&]( const int initial, const time_duration & factor, const char *const msg ) {
                const auto text = string_input_popup()
                                  .title( msg )
                                  .width( 20 )
                                  .text( std::to_string( initial ) )
                                  .only_digits( true )
                                  .query_string();
                if( text.empty() ) {
                    return;
                }
                const int new_value = std::atoi( text.c_str() );
                const time_duration offset = ( new_value - initial ) * factor;
                // Arbitrary maximal value.
                const time_point max = calendar::turn_zero + time_duration::from_turns(
                                           std::numeric_limits<int>::max() / 2 );
                calendar::turn = std::max( std::min( max, calendar::turn + offset ), calendar::turn_zero );
            };
            uilist smenu;
            static const auto years = []( const time_point & p ) {
                return static_cast<int>( ( p - calendar::turn_zero ) / calendar::year_length() );
            };
            do {
                const int iSel = smenu.ret;
                smenu.reset();
                smenu.addentry( 0, true, 'y', "%s: %d", _( "year" ), years( calendar::turn ) );
                smenu.addentry( 1, true, 's', "%s: %d", _( "season" ),
                                static_cast<int>( season_of_year( calendar::turn ) ) );
                smenu.addentry( 2, true, 'd', "%s: %d", _( "day" ), day_of_season<int>( calendar::turn ) );
                smenu.addentry( 3, true, 'h', "%s: %d", _( "hour" ), hour_of_day<int>( calendar::turn ) );
                smenu.addentry( 4, true, 'm', "%s: %d", _( "minute" ), minute_of_hour<int>( calendar::turn ) );
                smenu.addentry( 5, true, 't', "%s: %d", pgettext( "point in time", "turn" ),
                                to_turns<int>( calendar::turn - calendar::turn_zero ) );
                smenu.selected = iSel;
                smenu.query();
                switch( smenu.ret ) {
                    case 0:
                        set_turn( years( calendar::turn ), calendar::year_length(), _( "Set year to?" ) );
                        break;
                    case 1:
                        set_turn( static_cast<int>( season_of_year( calendar::turn ) ), calendar::season_length(),
                                  calendar::eternal_season() ?
                                  _( "Set eternal season to?  Warning: modifies initial season!" ) :
                                  _( "Set season to?  (0 = spring)" ) );
                        if( calendar::eternal_season() ) {
                            // Can't use season_of_year because it checks for eternal
                            season_type new_initial_season = static_cast<season_type>(
                                                                 to_turn<int>( calendar::turn ) / to_turns<int>( calendar::season_length() ) % 4
                                                             );
                            season_of_year( calendar::before_time_starts );
                            calendar::set_calendar_config( {
                                calendar::config.start_of_cataclysm(),
                                calendar::config.start_of_game(),
                                new_initial_season,
                                calendar::config.eternal_season()
                            } );
                        }
                        break;
                    case 2:
                        set_turn( day_of_season<int>( calendar::turn ), 1_days, _( "Set days to?" ) );
                        break;
                    case 3:
                        set_turn( hour_of_day<int>( calendar::turn ), 1_hours, _( "Set hour to?" ) );
                        break;
                    case 4:
                        set_turn( minute_of_hour<int>( calendar::turn ), 1_minutes, _( "Set minute to?" ) );
                        break;
                    case 5:
                        set_turn( to_turns<int>( calendar::turn - calendar::turn_zero ), 1_turns,
                                  string_format( _( "Set turn to?  (One day is %i turns)" ), to_turns<int>( 1_days ) ).c_str() );
                        break;
                    default:
                        break;
                }
            } while( smenu.ret != UILIST_CANCEL );
        }
        break;
        case DEBUG_SHOW_MUT_CAT:
            for( const auto &elem : u.mutation_category_level ) {
                add_msg( "%s: %d", elem.first.c_str(), elem.second );
            }
            break;
        case DEBUG_SHOW_MUT_CHANCES:
            for( const auto &elem : u.mutation_chances() ) {
                add_msg( "%s: %.2f", elem.first.c_str(), elem.second );
            }
            break;
        case DEBUG_OM_EDITOR:
            ui::omap::display_editor();
            break;
        case DEBUG_BENCHMARK:
        case DEBUG_BENCHMARK_FPS: {
            bench_kind kind;
            switch( action ) {
                case DEBUG_BENCHMARK:
                    kind = bench_kind::DRAW;
                    break;
                case DEBUG_BENCHMARK_FPS:
                    kind = bench_kind::FPS;
                    break;
                default:
                    debugmsg( "Not implemented" );
                    return;
            }
            const int ms = string_input_popup()
                           .title( _( "Enter benchmark length (in milliseconds):" ) )
                           .width( 20 )
                           .text( "5000" )
                           .query_int();
            debug_menu::benchmark( ms, kind );
        }
        break;
        case DEBUG_OM_TELEPORT:
            debug_menu::teleport_overmap();
            break;
        case DEBUG_OM_TELEPORT_COORDINATES:
            debug_menu::teleport_overmap( true );
            break;
        case DEBUG_TRAIT_GROUP:
            trait_group::debug_spawn();
            break;
        case DEBUG_SHOW_MSG:
            debugmsg( "Test debugmsg" );
            break;
        case DEBUG_CRASH_GAME:
            raise( SIGSEGV );
            break;
        case DEBUG_RELOAD_TRANSLATIONS:
            l10n_data::reload_catalogues();
            break;
        case DEBUG_MAP_EXTRA: {
            const std::vector<std::string> &mx_str = MapExtras::get_all_function_names();
            uilist mx_menu;
            for( const std::string &extra : mx_str ) {
                mx_menu.addentry( -1, true, -1, extra );
            }
            mx_menu.query();
            int mx_choice = mx_menu.ret;
            if( mx_choice >= 0 && mx_choice < static_cast<int>( mx_str.size() ) ) {
                const tripoint_abs_omt where_omt( ui::omap::choose_point() );
                if( where_omt != overmap::invalid_tripoint ) {
                    tripoint_abs_sm where_sm = project_to<coords::sm>( where_omt );
                    tinymap mx_map;
                    // TODO: fix point types
                    mx_map.load( where_sm.raw(), false );
                    MapExtras::apply_function( mx_str[mx_choice], mx_map, where_sm.raw() );
                    g->load_npcs();
                    m.invalidate_map_cache( g->get_levz() );
                }
            }
            break;
        }
        case DEBUG_NESTED_MAPGEN:
            debug_menu::spawn_nested_mapgen();
            break;
        case DEBUG_DISPLAY_NPC_PATH:
            g->debug_pathfinding = !g->debug_pathfinding;
            break;
        case DEBUG_PRINT_FACTION_INFO: {
            int count = 0;
            for( const auto &elem : g->faction_manager_ptr->all() ) {
                std::cout << std::to_string( count ) << " Faction_id key in factions map = " << elem.first.str() <<
                          std::endl;
                std::cout << std::to_string( count ) << " Faction name associated with this id is " <<
                          elem.second.name << std::endl;
                std::cout << std::to_string( count ) << " the id of that faction object is " << elem.second.id.str()
                          << std::endl;
                count++;
            }
            std::cout << "Player faction is " << g->u.get_faction()->id.str() << std::endl;
            break;
        }
        case DEBUG_PRINT_NPC_MAGIC: {
            for( npc &guy : g->all_npcs() ) {
                const std::vector<spell_id> spells = guy.magic->spells();
                if( spells.empty() ) {
                    std::cout << guy.disp_name() << " does not know any spells." << std::endl;
                    continue;
                }
                std::cout << guy.disp_name() << "knows : ";
                int counter = 1;
                for( const spell_id &sp : spells ) {
                    std::cout << sp->name.translated() << " ";
                    if( counter < static_cast<int>( spells.size() ) ) {
                        std::cout << "and ";
                    } else {
                        std::cout << "." << std::endl;
                    }
                    counter++;
                }
            }
            break;
        }
        case DEBUG_QUIT_NOSAVE:
            if( query_yn(
                    _( "Quit without saving?  This may cause issues such as duplicated or missing items and vehicles!" ) ) ) {
                u.moves = 0;
                g->uquit = QUIT_NOSAVED;
            }
            break;
        case DEBUG_TEST_WEATHER: {
            get_weather().get_cur_weather_gen().test_weather( g->get_seed() );
        }
        break;
        case DEBUG_SAVE_SCREENSHOT:
            g->queue_screenshot = true;
            break;
        case DEBUG_BUG_REPORT: {
            constexpr const char *const bug_report_url =
                "https://github.com/cataclysmbnteam/Cataclysm-BN/issues/new"
                "?labels=bug"
                "&template=bug_report.yml"
                "&versions-and-configuration=";
            const std::string report = game_info::game_report();
            const std::string url = bug_report_url + encode_url( report );
            open_url( url );
            DebugLog( DL::Info, DC::Main ) << " GAME REPORT:\n" << report;
            popup( _( "Opened a link to Bug Report on github." ) );
            break;
        }
        case DEBUG_GAME_REPORT: {
            // generate a game report, useful for bug reporting.
            const std::string report = game_info::game_report();
            // write to log
            DebugLog( DL::Info, DC::Main ) << " GAME REPORT:\n" << report;
            std::string popup_msg = _( "Report written to debug.log" );
#if defined(TILES)
            // copy to clipboard
            int clipboard_result = SDL_SetClipboardText( report.c_str() );
            printErrorIf( clipboard_result != 0, "Error while copying the game report to the clipboard." );
            if( clipboard_result == 0 ) {
                popup_msg += _( " and to the clipboard." );
            }
#endif
            popup( popup_msg );
        }
        break;
        case DEBUG_VEHICLE_BATTERY_CHARGE: {
            optional_vpart_position v_part_pos = g->m.veh_at( u.pos() );
            if( !v_part_pos ) {
                add_msg( m_bad, _( "There's no vehicle there." ) );
                break;
            }
            int amount = 0;
            string_input_popup popup;
            popup
            .title( _( "By how much?  (in kJ, negative to discharge)" ) )
            .width( 30 )
            .edit( amount );
            if( !popup.canceled() ) {
                vehicle &veh = v_part_pos->vehicle();
                if( amount >= 0 ) {
                    veh.charge_battery( amount, false );
                } else {
                    veh.discharge_battery( -amount, false );
                }
            }
            break;
        }
        case DEBUG_TEST_MAP_EXTRA_DISTRIBUTION:
            MapExtras::debug_spawn_test();
            break;
        case DEBUG_RESET_IGNORED_MESSAGES:
            debug_reset_ignored_messages();
            break;
        case DEBUG_RELOAD_TILES:
            std::ostringstream ss;
            g->reload_tileset( [&ss]( std::string str ) {
                ss << str << std::endl;
            } );
            add_msg( ss.str() );
            break;
    }
    m.invalidate_map_cache( g->get_levz() );
}
References _, a, action, ACTION_DEBUG, ACTION_DISPLAY_LIGHTING, ACTION_DISPLAY_RADIATION, ACTION_DISPLAY_SCENT, ACTION_DISPLAY_SCENT_TYPE, ACTION_DISPLAY_TEMPERATURE, ACTION_DISPLAY_TRANSPARENCY, ACTION_DISPLAY_VEHICLE_AI, ACTION_DISPLAY_VISIBILITY, add_msg(), map::add_vehicle(), uilist::addentry(), Character::apply_damage(), MapExtras::apply_function(), ARTPROP_MAX, ARTPROP_NULL, b, calendar::before_time_starts, benchmark(), Character::bmi(), Character::bmr(), map::board_vehicle(), center, vehicle::charge_battery(), ui::omap::choose_point(), calendar::config, detail::count(), map::create_anomaly(), DEBUG_BENCHMARK, DEBUG_BENCHMARK_FPS, DEBUG_BUG_REPORT, DEBUG_CHANGE_TIME, DEBUG_CHANGE_WEATHER, DEBUG_CRASH_GAME, DEBUG_DAMAGE_SELF, DEBUG_DISPLAY_DISTRIBUTION_GRIDS, DEBUG_DISPLAY_HORDES, DEBUG_DISPLAY_LIGHTING, DEBUG_DISPLAY_NPC_PATH, DEBUG_DISPLAY_RADIATION, DEBUG_DISPLAY_SCENTS, DEBUG_DISPLAY_SCENTS_LOCAL, DEBUG_DISPLAY_SCENTS_TYPE_LOCAL, DEBUG_DISPLAY_SUBMAP_GRID, DEBUG_DISPLAY_TEMP, DEBUG_DISPLAY_TRANSPARENCY, DEBUG_DISPLAY_VEHICLE_AI, DEBUG_DISPLAY_VISIBILITY, DEBUG_DISPLAY_WEATHER, DEBUG_GAME_REPORT, DEBUG_GAME_STATE, DEBUG_GEN_SOUND, DEBUG_HOUR_TIMER, DEBUG_KILL_AREA, DEBUG_KILL_MONS, DEBUG_KILL_NPCS, DEBUG_LONG_TELEPORT, DEBUG_MAP_EDITOR, DEBUG_MAP_EXTRA, debug_menu_uilist(), DEBUG_MUTATE, DEBUG_NESTED_MAPGEN, DEBUG_OM_EDITOR, DEBUG_OM_TELEPORT, DEBUG_OM_TELEPORT_COORDINATES, DEBUG_PRINT_FACTION_INFO, DEBUG_PRINT_NPC_MAGIC, DEBUG_QUIT_NOSAVE, DEBUG_RELOAD_TILES, DEBUG_RELOAD_TRANSLATIONS, debug_reset_ignored_messages(), DEBUG_RESET_IGNORED_MESSAGES, DEBUG_REVEAL_MAP, DEBUG_SAVE_SCREENSHOT, DEBUG_SHORT_TELEPORT, DEBUG_SHOW_MSG, DEBUG_SHOW_MUT_CAT, DEBUG_SHOW_MUT_CHANCES, DEBUG_SHOW_SOUND, item_group::debug_spawn(), trait_group::debug_spawn(), DEBUG_SPAWN_ARTIFACT, DEBUG_SPAWN_CLAIRVOYANCE, DEBUG_SPAWN_MON, DEBUG_SPAWN_NPC, MapExtras::debug_spawn_test(), DEBUG_SPAWN_VEHICLE, DEBUG_TEST_IT_GROUP, DEBUG_TEST_MAP_EXTRA_DISTRIBUTION, DEBUG_TEST_WEATHER, DEBUG_TRAIT_GROUP, DEBUG_VEHICLE_BATTERY_CHARGE, DEBUG_WIND_DIRECTION, DEBUG_WIND_SPEED, DEBUG_WISH, DebugLog, debugmsg, Creature::die(), Character::die(), vehicle::discharge_battery(), ui::omap::display_distribution_grids(), ui::omap::display_editor(), ui::omap::display_hordes(), ui::omap::display_scents(), ui::omap::display_weather(), DRAW, encode_url(), io::enum_to_string< m_flag >(), calendar::eternal_season(), detail::fill(), FPS, units::from_degrees(), time_duration::from_turns(), g, game_info::game_report(), MonsterGenerator::generator(), vehicle_prototype::get_all(), weather_types::get_all(), MapExtras::get_all_function_names(), weather_manager::get_cur_weather_gen(), get_map(), sounds::get_monster_sounds(), oter_t::get_name(), Creature::get_part_hp_cur(), Character::get_stored_kcal(), Character::get_thirst(), get_weather(), get_wind_arrow(), hotkey_for_action(), Character::i_add(), faction_template::id, int_id< T >::id(), Info, inp_mngr, overmapbuffer::insert_npc(), overmap::invalid_tripoint, map::invalidate_map_cache(), Creature::is_avatar(), tripoint_range< Tripoint >::is_point_inside(), avatar::kill_xp(), map::load(), localized_compare, m_bad, MonsterGenerator::m_flag_usage_stats, m_good, m_info, Main, Character::max_stored_kcal(), MENU_AUTOASSIGN, MF_MAX, mon_generator, Creature::moves, coords::ms, Character::mutation_category_level, Character::mutation_chances(), character_funcs::normalize(), NPC_MISSION_NULL, cata::nullopt, OMAPX, OMAPY, string_input_popup::only_digits(), open_url(), sounds::order, ORIGIN_ANY_NPC, overmap_buffer, OVERMAP_DEPTH, OVERMAP_HEIGHT, pgettext(), map::points_in_rectangle(), popup(), popup_top(), Creature::pos(), Character::pos(), look_around_result::position, Character::posx(), POSX, Character::posy(), POSY, uilist::query(), string_input_popup::query_int(), query_int(), string_input_popup::query_string(), query_yn(), QUIT_NOSAVED, coords::coord_point< Point, Origin, Scale >::raw(), ui_manager::redraw(), l10n_data::reload_catalogues(), mission::reserve_random(), uilist::reset(), uilist::ret, rng(), calendar::season_length(), season_of_year(), second, uilist::selected, calendar::set_calendar_config(), sounds::sound(), map::spawn_natural_artifact(), spawn_nested_mapgen(), calendar_config::start_of_cataclysm(), calendar::start_of_game, string_format(), teleport_long(), teleport_overmap(), teleport_short(), overmapbuffer::ter(), weather_generator::test_weather(), string_input_popup::text(), uilist::text, string_input_popup::title(), to_string(), tripoint_zero, calendar::turn, calendar::turn_zero, UILIST_CANCEL, map::veh_at(), velocity_units(), vgettext(), player::view_offset, VU_WIND, input_manager::wait_for_any_key(), string_input_popup::width(), wishitem(), wishmonster(), wishmutate(), tripoint::x, tripoint::xy(), tripoint::y, and calendar::year_length().
Referenced by item::animal_armor_info(), item::armor_info(), item::basic_info(), item::final_info(), item::food_info(), game::handle_action(), and item::info().
debug_menu_uilist()
static int debug_menu::debug_menu_uilist (bool display_all_entries = true) static
Create the debug menu UI list.
Parameters
display_all_entries true if all entries should be displayed, false is some entries should be hidden (for ex. when the debug menu is called from the main menu). This allows to have some menu elements at the same time in the main menu and in the debug menu.
Returns
The chosen action.
Definition at line 315 of file debug_menu.cpp.
{
    std::vector<uilist_entry> menu = {
        { uilist_entry( 1, true, 'i', _( "Info" ) ) },
    };
    if( display_all_entries ) {
        const std::vector<uilist_entry> debug_menu = {
            { uilist_entry( DEBUG_QUIT_NOSAVE, true, 'Q', _( "Quit to main menu" ) )  },
            { uilist_entry( 2, true, 's', _( "Spawning" ) ) },
            { uilist_entry( 3, true, 'p', _( "Player" ) ) },
            { uilist_entry( 6, true, 'v', _( "Vehicle" ) ) },
            { uilist_entry( 4, true, 't', _( "Teleport" ) ) },
            { uilist_entry( 5, true, 'm', _( "Map" ) ) },
        };
        // insert debug-only menu right after "Info".
        menu.insert( menu.begin() + 1, debug_menu.begin(), debug_menu.end() );
    }
    std::string msg;
    if( display_all_entries ) {
        msg = _( "Debug Functions - Manipulate the fabric of reality!\nYou can use them to fix a bug or test something.\nBe careful, as some of them may potentially break things." );
    } else {
        msg = _( "Debug Functions" );
    }
    while( true ) {
        const int group = uilist( msg, menu );
        int action;
        switch( group ) {
            case DEBUG_QUIT_NOSAVE:
                action = DEBUG_QUIT_NOSAVE;
                break;
            case 1:
                action = info_uilist( display_all_entries );
                break;
            case 2:
                action = spawning_uilist();
                break;
            case 3:
                action = -1;
                debug_menu::character_edit_menu( get_player_character() );
                break;
            case 4:
                action = teleport_uilist();
                break;
            case 5:
                action = map_uilist();
                break;
            case 6:
                action = vehicle_uilist();
                break;
            default:
                return group;
        }
        if( action >= 0 ) {
            return action;
        }
    }
}
References _, action, character_edit_menu(), DEBUG_QUIT_NOSAVE, get_player_character(), info_uilist(), map_uilist(), spawning_uilist(), teleport_uilist(), and vehicle_uilist().
Referenced by debug().
effect_edit_menu()
void debug_menu::effect_edit_menu (Creature & c)
Definition at line 420 of file wisheffect.cpp.
{
    bool not_dirty = false;
    bool stay_in_menu = true;
    int last_selected = 0;
    while( stay_in_menu ) {
        const effects_map &em = c.get_all_effects();
        uilist menu;
        menu.input_category = "edit_creature_effects";
        std::map<bodypart_str_id, std::vector<const effect *>> bp_effects;
        const std::vector<bodypart_id> &all_bps = c.get_all_body_parts();
        for( const auto &pr : em ) {
            for( const auto &inner : pr.second ) {
                bp_effects[inner.first].push_back( &inner.second );
                if( !inner.first.is_null() &&
                    std::count( all_bps.begin(), all_bps.end(), inner.first ) == 0 ) {
                    debugmsg( "Creature %s has effect on body part %s, not in anatomy",
                              c.get_name(), inner.first.str() );
                }
            }
        }
        std::vector<entry_data> meta;
        size_t i = 0;
        const auto add_effect_entry = [&menu, &i]( const effect & eff ) {
            // TODO: Columns
            std::string effect_description = string_format(
                                                 "- %s %d, %d s",
                                                 eff.get_id().str(),
                                                 eff.get_intensity(),
                                                 to_seconds<int>( eff.get_duration() ) );
            menu.addentry( i++, true, 0, effect_description );
        };
        menu.addentry( i++, true, -1, _( "Global" ) );
        auto global_iter = bp_effects.find( bodypart_str_id::NULL_ID() );
        meta.emplace_back( bodypart_str_id::NULL_ID() );
        if( global_iter != bp_effects.end() ) {
            for( const effect *eff : global_iter->second ) {
                add_effect_entry( *eff );
                meta.emplace_back( bodypart_str_id::NULL_ID(), *eff );
            }
        }
        for( const bodypart_id &bp : all_bps ) {
            menu.addentry( i++, true, -1, bp.id().str() );
            meta.emplace_back( bp.id() );
            auto iter = bp_effects.find( bp.id() );
            if( iter != bp_effects.end() ) {
                for( const effect *eff : iter->second ) {
                    add_effect_entry( *eff );
                    meta.emplace_back( bp.id(), *eff );
                }
            }
        }
        const auto on_creature_changed = [&not_dirty]() {
            not_dirty = false;
        };
        effect_edit_callback callback( c, meta, on_creature_changed );
        register_callback( menu, callback );
        not_dirty = true;
        while( not_dirty ) {
            // Have to do this because menus don't support entry removal
            menu.set_selected( last_selected );
            menu.query( false );
            if( menu.ret == UILIST_CANCEL ) {
                stay_in_menu = false;
                break;
            }
            last_selected = menu.selected;
        }
    }
}
References _, uilist::addentry(), c, detail::count(), debugmsg, uilist::input_category, string_id< body_part_type >::NULL_ID(), uilist::query(), debug_menu::anonymous_namespace{wisheffect.cpp}::register_callback(), uilist::ret, uilist::selected, uilist::set_selected(), string_format(), and UILIST_CANCEL.
Referenced by character_edit_menu().
info_uilist()
static int debug_menu::info_uilist (bool display_all_entries = true) static
Definition at line 200 of file debug_menu.cpp.
{
    // always displayed
    std::vector<uilist_entry> uilist_initializer = {
        { uilist_entry( DEBUG_SAVE_SCREENSHOT, true, 'H', _( "Take screenshot" ) ) },
        { uilist_entry( DEBUG_BUG_REPORT, true, 'U', _( "Submit a bug report on github" ) ) },
        { uilist_entry( DEBUG_GAME_REPORT, true, 'r', _( "Generate game report" ) ) },
    };
    if( display_all_entries ) {
        const std::vector<uilist_entry> debug_only_options = {
            { uilist_entry( DEBUG_GAME_STATE, true, 'g', _( "Check game state" ) ) },
            { uilist_entry( DEBUG_DISPLAY_HORDES, true, 'h', _( "Display hordes" ) ) },
            { uilist_entry( DEBUG_TEST_IT_GROUP, true, 'i', _( "Test item group" ) ) },
            { uilist_entry( DEBUG_SHOW_SOUND, true, 'c', _( "Show sound clustering" ) ) },
            { uilist_entry( DEBUG_DISPLAY_WEATHER, true, 'w', _( "Display weather" ) ) },
            { uilist_entry( DEBUG_DISPLAY_SCENTS, true, 'S', _( "Display overmap scents" ) ) },
            { uilist_entry( DEBUG_DISPLAY_DISTRIBUTION_GRIDS, true, 'G', _( "Display overmap distribution grids" ) ) },
            { uilist_entry( DEBUG_DISPLAY_SCENTS_LOCAL, true, 's', _( "Toggle display local scents" ) ) },
            { uilist_entry( DEBUG_DISPLAY_SCENTS_TYPE_LOCAL, true, 'y', _( "Toggle display local scents type" ) ) },
            { uilist_entry( DEBUG_DISPLAY_TEMP, true, 'T', _( "Toggle display temperature" ) ) },
            { uilist_entry( DEBUG_DISPLAY_VEHICLE_AI, true, 'V', _( "Toggle display vehicle autopilot overlay" ) ) },
            { uilist_entry( DEBUG_DISPLAY_VISIBILITY, true, 'v', _( "Toggle display visibility" ) ) },
            { uilist_entry( DEBUG_DISPLAY_LIGHTING, true, 'l', _( "Toggle display lighting" ) ) },
            { uilist_entry( DEBUG_DISPLAY_TRANSPARENCY, true, 'p', _( "Toggle display transparency" ) ) },
            { uilist_entry( DEBUG_DISPLAY_RADIATION, true, 'R', _( "Toggle display radiation" ) ) },
            { uilist_entry( DEBUG_DISPLAY_SUBMAP_GRID, true, 'o', _( "Toggle display submap grid" ) ) },
            { uilist_entry( DEBUG_SHOW_MUT_CAT, true, 'm', _( "Show mutation category levels" ) ) },
            { uilist_entry( DEBUG_SHOW_MUT_CHANCES, true, 'u', _( "Show mutation trait chances" ) ) },
            { uilist_entry( DEBUG_BENCHMARK, true, 'b', _( "Draw benchmark" ) ) },
            { uilist_entry( DEBUG_BENCHMARK_FPS, true, 'B', _( "FPS benchmark" ) ) },
            { uilist_entry( DEBUG_HOUR_TIMER, true, 'E', _( "Toggle hour timer" ) ) },
            { uilist_entry( DEBUG_TRAIT_GROUP, true, 't', _( "Test trait group" ) ) },
            { uilist_entry( DEBUG_SHOW_MSG, true, 'd', _( "Show debug message" ) ) },
            { uilist_entry( DEBUG_CRASH_GAME, true, 'C', _( "Crash game (test crash handling)" ) ) },
            { uilist_entry( DEBUG_RELOAD_TRANSLATIONS, true, 'L', _( "Reload translations" ) ) },
            { uilist_entry( DEBUG_DISPLAY_NPC_PATH, true, 'n', _( "Toggle NPC pathfinding on map" ) ) },
            { uilist_entry( DEBUG_PRINT_FACTION_INFO, true, 'f', _( "Print faction info to console" ) ) },
            { uilist_entry( DEBUG_PRINT_NPC_MAGIC, true, 'M', _( "Print NPC magic info to console" ) ) },
            { uilist_entry( DEBUG_TEST_WEATHER, true, 'W', _( "Test weather" ) ) },
            { uilist_entry( DEBUG_TEST_MAP_EXTRA_DISTRIBUTION, true, 'e', _( "Test map extra list" ) ) },
            { uilist_entry( DEBUG_RESET_IGNORED_MESSAGES, true, 'I', _( "Reset ignored debug messages" ) ) },
#if defined(TILES)
            { uilist_entry( DEBUG_RELOAD_TILES, true, 'D', _( "Reload tileset and show missing tiles" ) ) },
#endif
        };
        uilist_initializer.insert( uilist_initializer.begin(), debug_only_options.begin(),
                                   debug_only_options.end() );
    }
    return uilist( _( "Info" ), uilist_initializer );
}
References _, DEBUG_BENCHMARK, DEBUG_BENCHMARK_FPS, DEBUG_BUG_REPORT, DEBUG_CRASH_GAME, DEBUG_DISPLAY_DISTRIBUTION_GRIDS, DEBUG_DISPLAY_HORDES, DEBUG_DISPLAY_LIGHTING, DEBUG_DISPLAY_NPC_PATH, DEBUG_DISPLAY_RADIATION, DEBUG_DISPLAY_SCENTS, DEBUG_DISPLAY_SCENTS_LOCAL, DEBUG_DISPLAY_SCENTS_TYPE_LOCAL, DEBUG_DISPLAY_SUBMAP_GRID, DEBUG_DISPLAY_TEMP, DEBUG_DISPLAY_TRANSPARENCY, DEBUG_DISPLAY_VEHICLE_AI, DEBUG_DISPLAY_VISIBILITY, DEBUG_DISPLAY_WEATHER, DEBUG_GAME_REPORT, DEBUG_GAME_STATE, DEBUG_HOUR_TIMER, DEBUG_PRINT_FACTION_INFO, DEBUG_PRINT_NPC_MAGIC, DEBUG_RELOAD_TILES, DEBUG_RELOAD_TRANSLATIONS, DEBUG_RESET_IGNORED_MESSAGES, DEBUG_SAVE_SCREENSHOT, DEBUG_SHOW_MSG, DEBUG_SHOW_MUT_CAT, DEBUG_SHOW_MUT_CHANCES, DEBUG_SHOW_SOUND, DEBUG_TEST_IT_GROUP, DEBUG_TEST_MAP_EXTRA_DISTRIBUTION, DEBUG_TEST_WEATHER, and DEBUG_TRAIT_GROUP.
Referenced by debug_menu_uilist().
map_uilist()
static int debug_menu::map_uilist () static
Definition at line 288 of file debug_menu.cpp.
{
    const std::vector<uilist_entry> uilist_initializer = {
        { uilist_entry( DEBUG_REVEAL_MAP, true, 'r', _( "Reveal map" ) ) },
        { uilist_entry( DEBUG_KILL_AREA, true, 'a', _( "Kill in Area" ) ) },
        { uilist_entry( DEBUG_KILL_NPCS, true, 'k', _( "Kill NPCs" ) ) },
        { uilist_entry( DEBUG_MAP_EDITOR, true, 'M', _( "Map editor" ) ) },
        { uilist_entry( DEBUG_CHANGE_WEATHER, true, 'w', _( "Change weather" ) ) },
        { uilist_entry( DEBUG_WIND_DIRECTION, true, 'd', _( "Change wind direction" ) ) },
        { uilist_entry( DEBUG_WIND_SPEED, true, 's', _( "Change wind speed" ) ) },
        { uilist_entry( DEBUG_GEN_SOUND, true, 'S', _( "Generate sound" ) ) },
        { uilist_entry( DEBUG_KILL_MONS, true, 'K', _( "Kill all monsters" ) ) },
        { uilist_entry( DEBUG_CHANGE_TIME, true, 't', _( "Change time" ) ) },
        { uilist_entry( DEBUG_OM_EDITOR, true, 'O', _( "Overmap editor" ) ) },
        { uilist_entry( DEBUG_MAP_EXTRA, true, 'm', _( "Spawn map extra" ) ) },
        { uilist_entry( DEBUG_NESTED_MAPGEN, true, 'n', _( "Spawn nested mapgen" ) ) },
    };
    return uilist( _( "Map" ), uilist_initializer );
}
References _, DEBUG_CHANGE_TIME, DEBUG_CHANGE_WEATHER, DEBUG_GEN_SOUND, DEBUG_KILL_AREA, DEBUG_KILL_MONS, DEBUG_KILL_NPCS, DEBUG_MAP_EDITOR, DEBUG_MAP_EXTRA, DEBUG_NESTED_MAPGEN, DEBUG_OM_EDITOR, DEBUG_REVEAL_MAP, DEBUG_WIND_DIRECTION, and DEBUG_WIND_SPEED.
Referenced by debug_menu_uilist().
mission_status_string()
static std::string debug_menu::mission_status_string (mission::mission_status status) static
Definition at line 1103 of file debug_menu.cpp.
{
    static const std::map<mission::mission_status, std::string> desc{ {
            { mission::mission_status::yet_to_start, translate_marker( "Yet to start" ) },
            { mission::mission_status::in_progress, translate_marker( "In progress" ) },
            { mission::mission_status::success, translate_marker( "Success" ) },
            { mission::mission_status::failure, translate_marker( "Failure" ) }
        }
    };
    const auto &iter = desc.find( status );
    if( iter != desc.end() ) {
        return _( iter->second );
    }
    return _( "Bugged" );
}
References _, mission::failure, mission::in_progress, mission::success, translate_marker, and mission::yet_to_start.
Referenced by debug_menu::mission_debug::describe().
mutation_wish()
void debug_menu::mutation_wish ()
pick_character()
static Character & debug_menu::pick_character (Character & preselected) static
Definition at line 470 of file debug_menu.cpp.
{
    std::vector< tripoint > locations;
    uilist charmenu;
    int charnum = 0;
    charmenu.addentry( charnum++, true, MENU_AUTOASSIGN, "%s", _( "You" ) );
    locations.emplace_back( g->u.pos() );
    for( const npc &guy : g->all_npcs() ) {
        charmenu.addentry( charnum++, true, MENU_AUTOASSIGN, guy.name );
        locations.emplace_back( guy.pos() );
    }
    avatar &u = get_avatar();
    u.view_offset = u.pos() - preselected.pos();
    auto iter = std::find_if( locations.begin(), locations.end(), [&preselected]( const tripoint & p ) {
        return p == preselected.pos();
    } );
    size_t preselect_index = iter != locations.end() ? std::distance( locations.begin(), iter ) : 0;
    pointmenu_cb callback( locations );
    charmenu.callback = &callback;
    charmenu.w_y_setup = 0;
    charmenu.set_selected( preselect_index );
    charmenu.query();
    if( charmenu.ret < 0 || static_cast<size_t>( charmenu.ret ) >= locations.size() ) {
        return preselected;
    }
    const size_t index = charmenu.ret;
    Character *c = g->critter_at<Character>( locations[index] );
    return c != nullptr ? *c : preselected;
}
References _, uilist::addentry(), c, uilist::callback, g, get_avatar(), anonymous_namespace{overmap_location.cpp}::locations, MENU_AUTOASSIGN, Character::pos(), uilist::query(), uilist::ret, uilist::set_selected(), player::view_offset, and uilist::w_y_setup.
Referenced by character_edit_menu().
remove_from_vec()
static bool debug_menu::remove_from_vec (std::vector< mission * > & vec, mission * m) static
Definition at line 1214 of file debug_menu.cpp.
{
    auto iter = std::remove( vec.begin(), vec.end(), m );
    bool ret = iter != vec.end();
    vec.erase( iter, vec.end() );
    return ret;
}
References cata::hash64_detail::ret.
Referenced by debug_menu::mission_debug::remove_mission().
spawn_nested_mapgen()
void debug_menu::spawn_nested_mapgen ()
Definition at line 433 of file debug_menu.cpp.
{
    uilist nest_menu;
    std::vector<std::string> nest_str;
    for( auto &nested : nested_mapgen ) {
        nest_menu.addentry( -1, true, -1, nested.first );
        nest_str.push_back( nested.first );
    }
    nest_menu.query();
    const int nest_choice = nest_menu.ret;
    if( nest_choice >= 0 && nest_choice < static_cast<int>( nest_str.size() ) ) {
        const cata::optional<tripoint> where = g->look_around( true );
        if( !where ) {
            return;
        }
        map &here = get_map();
        const tripoint_abs_ms abs_ms( here.getabs( *where ) );
        const tripoint_abs_omt abs_omt = project_to<coords::omt>( abs_ms );
        const tripoint_abs_sm abs_sub = project_to<coords::sm>( abs_ms );
        map target_map;
        target_map.load( abs_sub, true );
        // TODO: fix point types
        const tripoint local_ms = target_map.getlocal( abs_ms.raw() );
        mapgendata md( abs_omt, target_map, 0.0f, calendar::turn, nullptr );
        const auto &ptr = nested_mapgen[nest_str[nest_choice]].pick();
        if( ptr == nullptr ) {
            return;
        }
        ( *ptr )->nest( md, local_ms.xy() );
        target_map.save();
        g->load_npcs();
        here.invalidate_map_cache( g->get_levz() );
    }
}
References uilist::addentry(), g, get_map(), map::getabs(), map::getlocal(), map::invalidate_map_cache(), map::load(), nested_mapgen, ptr(), uilist::query(), coords::coord_point< Point, Origin, Scale >::raw(), uilist::ret, map::save(), calendar::turn, and tripoint::xy().
Referenced by debug().
spawning_uilist()
static int debug_menu::spawning_uilist () static
Definition at line 274 of file debug_menu.cpp.
{
    const std::vector<uilist_entry> uilist_initializer = {
        { uilist_entry( DEBUG_WISH, true, 'w', _( "Spawn an item" ) ) },
        { uilist_entry( DEBUG_SPAWN_NPC, true, 'n', _( "Spawn NPC" ) ) },
        { uilist_entry( DEBUG_SPAWN_MON, true, 'm', _( "Spawn monster" ) ) },
        { uilist_entry( DEBUG_SPAWN_VEHICLE, true, 'v', _( "Spawn a vehicle" ) ) },
        { uilist_entry( DEBUG_SPAWN_ARTIFACT, true, 'a', _( "Spawn artifact" ) ) },
        { uilist_entry( DEBUG_SPAWN_CLAIRVOYANCE, true, 'c', _( "Spawn clairvoyance artifact" ) ) },
    };
    return uilist( _( "Spawning" ), uilist_initializer );
}
References _, DEBUG_SPAWN_ARTIFACT, DEBUG_SPAWN_CLAIRVOYANCE, DEBUG_SPAWN_MON, DEBUG_SPAWN_NPC, DEBUG_SPAWN_VEHICLE, and DEBUG_WISH.
Referenced by debug_menu_uilist().
teleport_long()
void debug_menu::teleport_long ()
Definition at line 391 of file debug_menu.cpp.
{
    const tripoint_abs_omt where( ui::omap::choose_point() );
    if( where == overmap::invalid_tripoint ) {
        return;
    }
    g->place_player_overmap( where );
    add_msg( _( "You teleport to submap %s." ), where.to_string() );
}
References _, add_msg(), ui::omap::choose_point(), g, overmap::invalid_tripoint, and coords::coord_point< Point, Origin, Scale >::to_string().
Referenced by debug().
teleport_overmap()
void debug_menu::teleport_overmap (bool specific_coordinates)
Definition at line 401 of file debug_menu.cpp.
{
    tripoint_abs_omt where;
    if( specific_coordinates ) {
        const std::string text = string_input_popup()
                                 .title( "Teleport where?" )
                                 .width( 20 )
                                 .query_string();
        if( text.empty() ) {
            return;
        }
        const std::vector<std::string> coord_strings = string_split( text, ',' );
        tripoint coord;
        coord.x = !coord_strings.empty() ? std::atoi( coord_strings[0].c_str() ) : 0;
        coord.y = coord_strings.size() >= 2 ? std::atoi( coord_strings[1].c_str() ) : 0;
        coord.z = coord_strings.size() >= 3 ? std::atoi( coord_strings[2].c_str() ) : 0;
        where = tripoint_abs_omt( OMAPX * coord.x, OMAPY * coord.y, coord.z );
    } else {
        const cata::optional<tripoint> dir_ = choose_direction( _( "Where is the desired overmap?" ) );
        if( !dir_ ) {
            return;
        }
        const tripoint offset = tripoint( OMAPX * dir_->x, OMAPY * dir_->y, dir_->z );
        where = g->u.global_omt_location() + offset;
    }
    g->place_player_overmap( where );
    const tripoint_abs_om new_pos = project_to<coords::om>( g->u.global_omt_location() );
    add_msg( _( "You teleport to overmap %s." ), new_pos.to_string() );
}
References _, add_msg(), choose_direction(), g, OMAPX, OMAPY, string_input_popup::query_string(), string_split(), string_input_popup::title(), coords::coord_point< Point, Origin, Scale >::to_string(), string_input_popup::width(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by debug().
teleport_short()
void debug_menu::teleport_short ()
Definition at line 380 of file debug_menu.cpp.
{
    const cata::optional<tripoint> where = g->look_around( true );
    if( !where || *where == g->u.pos() ) {
        return;
    }
    g->place_player( *where );
    const tripoint new_pos( g->u.pos() );
    add_msg( _( "You teleport to point (%d,%d,%d)." ), new_pos.x, new_pos.y, new_pos.z );
}
References _, add_msg(), g, tripoint::x, tripoint::y, and tripoint::z.
Referenced by debug().
teleport_uilist()
static int debug_menu::teleport_uilist () static
Definition at line 262 of file debug_menu.cpp.
{
    const std::vector<uilist_entry> uilist_initializer = {
        { uilist_entry( DEBUG_SHORT_TELEPORT, true, 's', _( "Teleport - short range" ) ) },
        { uilist_entry( DEBUG_LONG_TELEPORT, true, 'l', _( "Teleport - long range" ) ) },
        { uilist_entry( DEBUG_OM_TELEPORT, true, 'o', _( "Teleport - adjacent overmap" ) ) },
        { uilist_entry( DEBUG_OM_TELEPORT_COORDINATES, true, 'p', _( "Teleport - specific overmap coordinates" ) ) },
    };
    return uilist( _( "Teleport" ), uilist_initializer );
}
References _, DEBUG_LONG_TELEPORT, DEBUG_OM_TELEPORT, DEBUG_OM_TELEPORT_COORDINATES, and DEBUG_SHORT_TELEPORT.
Referenced by debug_menu_uilist().
vehicle_uilist()
static int debug_menu::vehicle_uilist () static
Definition at line 253 of file debug_menu.cpp.
{
    std::vector<uilist_entry> uilist_initializer = {
        { uilist_entry( DEBUG_VEHICLE_BATTERY_CHARGE, true, 'b', _( "Change [b]attery charge" ) ) },
    };
    return uilist( _( "Vehicle" ), uilist_initializer );
}
References _, and DEBUG_VEHICLE_BATTERY_CHARGE.
Referenced by debug_menu_uilist().
wishitem() [1/2]
void debug_menu::wishitem (player * p, const tripoint & pos)
Definition at line 546 of file wish.cpp.
{
    if( p == nullptr && pos.x <= 0 ) {
        debugmsg( "game::wishitem(): invalid parameters" );
        return;
    }
    std::vector<std::pair<std::string, const itype *>> opts;
    for( const itype *i : item_controller->all() ) {
        opts.emplace_back( item( i, calendar::start_of_cataclysm ).tname( 1, false ), i );
    }
    std::sort( opts.begin(), opts.end(), localized_compare );
    std::vector<const itype *> itypes;
    std::transform( opts.begin(), opts.end(), std::back_inserter( itypes ),
    []( const auto & pair ) {
        return pair.second;
    } );
    int prev_amount = 1;
    int amount = 1;
    uilist wmenu;
    wmenu.w_x_setup = 0;
    wmenu.w_width_setup = []() -> int {
        return TERMX;
    };
    wmenu.pad_right_setup = []() -> int {
        return std::max( TERMX / 2, TERMX - 50 );
    };
    wmenu.selected = uistate.wishitem_selected;
    wish_item_callback cb( itypes );
    wmenu.callback = &cb;
    for( size_t i = 0; i < opts.size(); i++ ) {
        item ity( opts[i].second, calendar::start_of_cataclysm );
        wmenu.addentry( i, true, 0, opts[i].first );
        mvwzstr &entry_extra_text = wmenu.entries[i].extratxt;
        entry_extra_text.txt = ity.symbol();
        entry_extra_text.color = ity.color();
        entry_extra_text.left = 1;
    }
    do {
        wmenu.query();
        if( cb.spawn_everything && wmenu.ret != UILIST_CANCEL ) {
            wmenu.ret = opts.size() - 1;
        }
        bool did_amount_prompt = false;
        while( wmenu.ret >= 0 ) {
            item granted( opts[wmenu.ret].second );
            if( cb.incontainer ) {
                granted = granted.in_its_container();
            }
            if( cb.has_flag ) {
                granted.item_tags.insert( cb.flag );
            }
            // If the item has an ammunition, this loads it to capacity, including magazines.
            if( !granted.ammo_default().is_null() ) {
                granted.ammo_set( granted.ammo_default(), -1 );
            }
            granted.set_birthday( calendar::turn );
            prev_amount = amount;
            bool canceled = false;
            if( p != nullptr && !did_amount_prompt ) {
                string_input_popup popup;
                if( cb.spawn_everything ) {
                    popup.title( _( "How many of each?" ) );
                    if( cb.incontainer ) {
                        popup.description( "Spawning items in containers." );
                    } else {
                        popup.description( "Spawning items without containers." );
                    }
                } else {
                    popup
                    .title( _( "How many?" ) )
                    .description( granted.tname() );
                }
                popup.width( 20 )
                .edit( amount );
                canceled = popup.canceled();
            }
            if( !canceled ) {
                did_amount_prompt = true;
                if( p != nullptr ) {
                    if( granted.count_by_charges() ) {
                        if( amount > 0 ) {
                            granted.charges = amount;
                            p->i_add_or_drop( granted );
                        }
                    } else {
                        for( int i = 0; i < amount; i++ ) {
                            p->i_add_or_drop( granted );
                        }
                    }
                    p->invalidate_crafting_inventory();
                } else if( pos.x >= 0 && pos.y >= 0 ) {
                    g->m.add_item_or_charges( pos, granted );
                    wmenu.ret = -1;
                }
                if( amount > 0 ) {
                    input_context ctxt( wmenu.input_category );
                    cb.msg = string_format( _( "Wish granted.  Wish for more or hit [%s] to quit." ),
                                            ctxt.get_desc( "QUIT" ) );
                }
            }
            uistate.wishitem_selected = wmenu.selected;
            if( canceled || amount <= 0 ) {
                amount = prev_amount;
            }
            if( cb.spawn_everything ) {
                wmenu.ret--;
            } else {
                break;
            }
        }
    } while( wmenu.ret >= 0 );
}
References _, uilist::addentry(), item::ammo_default(), item::ammo_set(), uilist::callback, item::charges, item::color(), mvwzstr::color, item::count_by_charges(), debugmsg, uilist::entries, wish_item_callback::flag, g, input_context::get_desc(), wish_item_callback::has_flag, Character::i_add_or_drop(), item::in_its_container(), wish_item_callback::incontainer, uilist::input_category, cata::flat_set< T, Compare, Data >::insert(), Character::invalidate_crafting_inventory(), string_id< T >::is_null(), item_controller, item::item_tags, mvwzstr::left, localized_compare, wish_item_callback::msg, uilist::pad_right_setup, popup(), uilist::query(), uilist::ret, second, uilist::selected, item::set_birthday(), wish_item_callback::spawn_everything, calendar::start_of_cataclysm, string_format(), item::symbol(), TERMX, item::tname(), iexamine::transform(), calendar::turn, mvwzstr::txt, UILIST_CANCEL, uistate, uilist::w_width_setup, uilist::w_x_setup, uistatedata::wishitem_selected, tripoint::x, and tripoint::y.
wishitem() [2/2]
void debug_menu::wishitem (player * p = nullptr)
Definition at line 541 of file wish.cpp.
{
    wishitem( p, tripoint( -1, -1, -1 ) );
}
References wishitem().
Referenced by character_edit_menu(), debug(), editmap::edit_itm(), and wishitem().
wishmonster()
void debug_menu::wishmonster (const cata::optional< tripoint > & p)
Definition at line 404 of file wish.cpp.
{
    std::vector<const mtype *> mtypes;
    uilist wmenu;
    wmenu.w_x_setup = 0;
    wmenu.w_width_setup = []() -> int {
        return TERMX;
    };
    wmenu.pad_right_setup = []() -> int {
        return TERMX - 30;
    };
    wmenu.selected = uistate.wishmonster_selected;
    wish_monster_callback cb( mtypes );
    wmenu.callback = &cb;
    int i = 0;
    for( const mtype &montype : MonsterGenerator::generator().get_all_mtypes() ) {
        wmenu.addentry( i, true, 0, montype.nname() );
        wmenu.entries[i].extratxt.txt = montype.sym;
        wmenu.entries[i].extratxt.color = montype.color;
        wmenu.entries[i].extratxt.left = 1;
        ++i;
        mtypes.push_back( &montype );
    }
    do {
        wmenu.query();
        if( wmenu.ret >= 0 ) {
            const mtype_id &mon_type = mtypes[ wmenu.ret ]->id;
            if( cata::optional<tripoint> spawn = p ? p : g->look_around( true ) ) {
                int num_spawned = 0;
                for( const tripoint &destination : closest_points_first( *spawn, cb.group ) ) {
                    monster *const mon = g->place_critter_at( mon_type, destination );
                    if( !mon ) {
                        continue;
                    }
                    if( cb.friendly ) {
                        mon->friendly = -1;
                    }
                    if( cb.hallucination ) {
                        mon->hallucination = true;
                    }
                    ++num_spawned;
                }
                input_context ctxt( wmenu.input_category );
                cb.msg = string_format( _( "Spawned %d monsters, choose another or [%s] to quit." ),
                                        num_spawned, ctxt.get_desc( "QUIT" ) );
                if( num_spawned == 0 ) {
                    cb.msg += _( "\nTarget location is not suitable for placing this kind of monster.  Choose a different target or [i]ncrease the groups size." );
                }
                uistate.wishmonster_selected = wmenu.selected;
            }
        }
    } while( wmenu.ret >= 0 );
}
References _, uilist::addentry(), uilist::callback, closest_points_first(), uilist::entries, monster::friendly, wish_monster_callback::friendly, g, MonsterGenerator::generator(), input_context::get_desc(), wish_monster_callback::group, monster::hallucination, wish_monster_callback::hallucination, mtype::id, uilist::input_category, wish_monster_callback::msg, uilist::pad_right_setup, uilist::query(), uilist::ret, uilist::selected, string_format(), TERMX, uistate, uilist::w_width_setup, uilist::w_x_setup, and uistatedata::wishmonster_selected.
Referenced by debug().
wishmutate()
void debug_menu::wishmutate (player * p)
Definition at line 231 of file wish.cpp.
{
    uilist wmenu;
    int c = 0;
    for( auto &traits_iter : mutation_branch::get_all() ) {
        wmenu.addentry( -1, true, -2, traits_iter.name() );
        wmenu.entries[ c ].extratxt.left = 1;
        wmenu.entries[ c ].extratxt.txt.clear();
        wmenu.entries[ c ].extratxt.color = c_light_green;
        wmenu.entries[ c ].hilite_color = h_light_green;
        if( p->has_trait( traits_iter.id ) ) {
            wmenu.entries[ c ].text_color = c_green;
            wmenu.entries[ c ].override_hilite_color = true;
            if( p->has_base_trait( traits_iter.id ) ) {
                wmenu.entries[ c ].extratxt.txt = "T";
            }
        }
        c++;
    }
    wmenu.w_x_setup = 0;
    wmenu.w_width_setup = []() -> int {
        return TERMX;
    };
    wmenu.pad_right_setup = []() -> int {
        return TERMX - 40;
    };
    wmenu.selected = uistate.wishmutate_selected;
    wish_mutate_callback cb;
    cb.p = p;
    wmenu.callback = &cb;
    do {
        wmenu.query();
        if( wmenu.ret >= 0 ) {
            int rc = 0;
            const trait_id mstr = cb.vTraits[ wmenu.ret ];
            const auto &mdata = mstr.obj();
            const bool threshold = mdata.threshold;
            const bool profession = mdata.profession;
            // Manual override for the threshold-gaining
            if( threshold || profession ) {
                if( p->has_trait( mstr ) ) {
                    do {
                        p->remove_mutation( mstr );
                        rc++;
                    } while( p->has_trait( mstr ) && rc < 10 );
                } else {
                    do {
                        p->set_mutation( mstr );
                        rc++;
                    } while( !p->has_trait( mstr ) && rc < 10 );
                }
            } else if( p->has_trait( mstr ) ) {
                do {
                    p->remove_mutation( mstr );
                    rc++;
                } while( p->has_trait( mstr ) && rc < 10 );
            } else {
                do {
                    p->mutate_towards( mstr );
                    rc++;
                } while( !p->has_trait( mstr ) && rc < 10 );
            }
            cb.msg = string_format( _( "%s Mutation changes: %d" ), mstr.c_str(), rc );
            uistate.wishmutate_selected = wmenu.selected;
            if( rc != 0 ) {
                for( size_t i = 0; i < cb.vTraits.size(); i++ ) {
                    uilist_entry &entry = wmenu.entries[ i ];
                    entry.extratxt.txt.clear();
                    if( p->has_trait( cb.vTraits[ i ] ) ) {
                        entry.text_color = c_green;
                        entry.override_hilite_color = true;
                        cb.pTraits[ cb.vTraits[ i ] ] = true;
                        if( p->has_base_trait( cb.vTraits[ i ] ) ) {
                            entry.extratxt.txt = "T";
                        }
                    } else {
                        entry.text_color = wmenu.text_color;
                        entry.override_hilite_color = false;
                        cb.pTraits[ cb.vTraits[ i ] ] = false;
                    }
                }
            }
        }
    } while( wmenu.ret >= 0 );
}
References _, uilist::addentry(), c, c_green, c_light_green, string_id< T >::c_str(), uilist::callback, uilist::entries, uilist_entry::extratxt, mutation_branch::get_all(), h_light_green, Character::has_base_trait(), Character::has_trait(), wish_mutate_callback::msg, Character::mutate_towards(), string_id< T >::obj(), uilist_entry::override_hilite_color, wish_mutate_callback::p, uilist::pad_right_setup, profession::profession(), wish_mutate_callback::pTraits, uilist::query(), Character::remove_mutation(), uilist::ret, uilist::selected, Character::set_mutation(), string_format(), TERMX, uilist_entry::text_color, uilist::text_color, mutation_branch::threshold, mvwzstr::txt, uistate, wish_mutate_callback::vTraits, uilist::w_width_setup, uilist::w_x_setup, and uistatedata::wishmutate_selected.
Referenced by character_edit_menu(), and debug().
wishskill()
void debug_menu::wishskill (player * p)
Definition at line 665 of file wish.cpp.
{
    const int skoffset = 1;
    uilist skmenu;
    skmenu.text = _( "Select a skill to modify" );
    skmenu.allow_anykey = true;
    skmenu.addentry( 0, true, '1', _( "Modify all skills" ) );
    auto sorted_skills = Skill::get_skills_sorted_by( []( const Skill & a, const Skill & b ) {
        return localized_compare( a.name(), b.name() );
    } );
    std::vector<int> origskills;
    origskills.reserve( sorted_skills.size() );
    for( const auto &s : sorted_skills ) {
        const int level = p->get_skill_level( s->ident() );
        skmenu.addentry( origskills.size() + skoffset, true, -2, _( "@ %d: %s  " ), level,
                         s->name() );
        origskills.push_back( level );
    }
    shared_ptr_fast<ui_adaptor> skmenu_ui = skmenu.create_or_get_ui_adaptor();
    do {
        skmenu.query();
        int skill_id = -1;
        int skset = -1;
        const int sksel = skmenu.selected - skoffset;
        if( skmenu.ret == UILIST_UNBOUND && ( skmenu.keypress == KEY_LEFT ||
                                              skmenu.keypress == KEY_RIGHT ) ) {
            if( sksel >= 0 && sksel < static_cast<int>( sorted_skills.size() ) ) {
                skill_id = sksel;
                skset = p->get_skill_level( sorted_skills[skill_id]->ident() ) +
                        ( skmenu.keypress == KEY_LEFT ? -1 : 1 );
            }
        } else if( skmenu.ret >= 0 && sksel >= 0 &&
                   sksel < static_cast<int>( sorted_skills.size() ) ) {
            skill_id = sksel;
            const Skill &skill = *sorted_skills[skill_id];
            const int NUM_SKILL_LVL = 21;
            uilist sksetmenu;
            sksetmenu.w_height_setup = NUM_SKILL_LVL + 4;
            sksetmenu.w_x_setup = [&]( int ) -> int {
                return skmenu.w_x + skmenu.w_width + 1;
            };
            sksetmenu.w_y_setup = [&]( const int height ) {
                return std::max( 0, skmenu.w_y + ( skmenu.w_height - height ) / 2 );
            };
            sksetmenu.settext( string_format( _( "Set '%s' to" ), skill.name() ) );
            const int skcur = p->get_skill_level( skill.ident() );
            sksetmenu.selected = skcur;
            for( int i = 0; i < NUM_SKILL_LVL; i++ ) {
                sksetmenu.addentry( i, true, i + 48, "%d%s", i, skcur == i ? _( " (current)" ) : "" );
            }
            sksetmenu.query();
            skset = sksetmenu.ret;
        }
        if( skill_id >= 0 && skset >= 0 ) {
            const Skill &skill = *sorted_skills[skill_id];
            p->set_skill_level( skill.ident(), skset );
            skmenu.textformatted[0] = string_format( _( "%s set to %d             " ),
                                      skill.name(),
                                      p->get_skill_level( skill.ident() ) ).substr( 0, skmenu.w_width - 4 );
            skmenu.entries[skill_id + skoffset].txt = string_format( _( "@ %d: %s  " ),
                    p->get_skill_level( skill.ident() ),
                    skill.name() );
            skmenu.entries[skill_id + skoffset].text_color =
                p->get_skill_level( skill.ident() ) == origskills[skill_id] ?
                skmenu.text_color : c_yellow;
        } else if( skmenu.ret == 0 && sksel == -1 ) {
            const int ret = uilist( _( "Alter all skill values" ), {
                _( "Add 3" ), _( "Add 1" ),
                _( "Subtract 1" ), _( "Subtract 3" ), _( "Set to 0" ),
                _( "Set to 5" ), _( "Set to 10" ), _( "(Reset changes)" )
            } );
            if( ret >= 0 ) {
                int skmod = 0;
                int skset = -1;
                if( ret < 4 ) {
                    skmod = 3 - ret * 2;
                } else if( ret < 7 ) {
                    skset = ( ret - 4 ) * 5;
                }
                for( size_t skill_id = 0; skill_id < sorted_skills.size(); skill_id++ ) {
                    const Skill &skill = *sorted_skills[skill_id];
                    int changeto = skmod != 0 ? p->get_skill_level( skill.ident() ) + skmod :
                                   skset != -1 ? skset : origskills[skill_id];
                    p->set_skill_level( skill.ident(), std::max( 0, changeto ) );
                    skmenu.entries[skill_id + skoffset].txt = string_format( _( "@ %d: %s  " ),
                            p->get_skill_level( skill.ident() ),
                            skill.name() );
                    p->get_skill_level_object( skill.ident() ).practice();
                    skmenu.entries[skill_id + skoffset].text_color =
                        p->get_skill_level( skill.ident() ) == origskills[skill_id] ? skmenu.text_color : c_yellow;
                }
            }
        }
    } while( skmenu.ret != UILIST_CANCEL );
}
References _, a, uilist::addentry(), uilist::allow_anykey, b, c_yellow, uilist::create_or_get_ui_adaptor(), uilist::entries, Character::get_skill_level(), Character::get_skill_level_object(), Skill::get_skills_sorted_by(), Skill::ident(), KEY_LEFT, KEY_RIGHT, uilist::keypress, localized_compare, Skill::name(), SkillLevel::practice(), uilist::query(), cata::hash64_detail::ret, uilist::ret, uilist::selected, Character::set_skill_level(), uilist::settext(), string_format(), uilist::text, uilist::text_color, uilist::textformatted, UILIST_CANCEL, UILIST_UNBOUND, uilist::w_height, uilist::w_height_setup, uilist::w_width, uilist::w_x, uilist::w_x_setup, uilist::w_y, and uilist::w_y_setup.
Referenced by character_edit_menu().