Cataclysm BN: ranged Namespace Reference
ranged Namespace Reference
Classes
struct aim_type
Enumerations
enum class hit_tier : int { grazing = 0 , normal , critical }
Functions
void draw_cone_aoe (const tripoint &origin, const std::map< tripoint, double > &aoe)
double hit_chance (const dispersion_sources &dispersion, double range, double target_size, double missed_by=1.0)
The chance that a fired shot reaches required accuracy - by default grazing shot.
void print_dmg_msg (Creature &target, Creature *source, const dealt_damage_instance &dealt_dam, hit_tier ht)
dealt_damage_instance hit_with_aoe (Creature &target, Creature *source, const damage_instance &di)
int throw_cost (const Character &c, const item &to_throw)
float get_str_draw_penalty (const item &it, const Character &p)
Penalties potentially incurred by STR_DRAW weapons.
float str_draw_damage_modifier (const item &it, const Character &p)
float str_draw_dispersion_modifier (const item &it, const Character &p)
float str_draw_range_modifier (const item &it, const Character &p)
int throw_dispersion_per_dodge (const Character &c, bool add_encumbrance)
How much dispersion does one point of target's dodge add when throwing at said target?
int throwing_dispersion (const Character &c, const item &to_throw, Creature *critter, bool is_blind_throw)
Dispersion of a thrown item, against a given target, taking into account whether or not the throw was blind.
dealt_projectile_attack throw_item (Character &who, const tripoint &target, const item &to_throw, cata::optional< tripoint > blind_throw_from_pos)
Execute a throw.
std::vector< Creature * > targetable_creatures (const Character &c, const int range)
std::vector< Creature * > targetable_creatures (const Character &c, const int range, const turret_data &turret)
int burst_penalty (const Character &p, const item &gun, int gun_recoil)
bool gunmode_checks_common (avatar &you, const map &m, std::vector< std::string > &messages, const gun_mode &gmode)
Common checks for gunmode (when firing a weapon / manually firing turret)
bool gunmode_checks_weapon (avatar &you, const map &m, std::vector< std::string > &messages, const gun_mode &gmode)
Various checks for gunmode when firing a weapon.
void execute_shaped_attack (const shape &sh, const projectile &proj, Creature &attacker)
AoE attack, with area given by shape.
std::map< tripoint, double > expected_coverage (const shape &sh, const map &here, int bash_power)
void prompt_select_default_ammo_for (avatar &u, const item &w)
Prompts to select default ammo compatible with provided gun.
bool handle_gun_damage (Character &shooter, item &it)
Returns true if a gun misfires, jams, or has other problems, else returns false.
int effective_dispersion (const Character &who, int dispersion)
dispersion_sources get_weapon_dispersion (const Character &who, const item &obj)
Get weapon's dispersion value modified accoring to character stats.
std::vector< aim_type > get_aim_types (const Character &who, const item &gun)
std::pair< int, int > get_fastest_sight (const Character &who, const item &gun, double recoil)
int get_most_accurate_sight (const Character &who, const item &gun)
double aim_speed_skill_modifier (const Character &who, const skill_id &gun_skill)
double aim_speed_dex_modifier (const Character &who)
double aim_speed_encumbrance_modifier (const Character &who)
double aim_cap_from_volume (const item &gun)
double aim_per_move (const Character &who, const item &gun, double recoil)
Calculates aim improvement per move spent aiming at a given.
double recoil_vehicle (const Character &who)
Get maximum recoil penalty due to vehicle motion.
double recoil_total (const Character &who)
Current total maximum recoil penalty from all sources.
int gun_engagement_moves (const Character &who, const item &gun, int target=0, int start=MAX_RECOIL)
How many moves does it take to aim gun to the target accuracy.
void make_gun_sound_effect (const Character &who, bool burst, const item &gun)
int fire_gun (Character &who, const tripoint &target, int shots=1)
Fire wielded gun or auxiliary gunmod (ignoring any current mode)
int fire_gun (Character &who, const tripoint &target, int shots, item &gun)
Fire a gun or auxiliary gunmod (ignoring any current mode)
Enumeration Type Documentation
hit_tier
enum class ranged::hit_tier : int strong
Enumerator
grazing
normal
critical
Definition at line 112 of file ranged.h.
                    : int {
    grazing = 0,
    normal,
    critical
};
Function Documentation
aim_cap_from_volume()
double ranged::aim_cap_from_volume (const item & gun)
Definition at line 3854 of file ranged.cpp.
{
    skill_id gun_skill = gun.gun_skill();
    double aim_cap = std::min( 49.0, 49.0 - static_cast<float>( gun.volume() / 75_ml ) );
    // TODO: also scale with skill level.
    if( gun_skill == skill_smg ) {
        aim_cap = std::max( 12.0, aim_cap );
    } else if( gun_skill == skill_shotgun ) {
        aim_cap = std::max( 12.0, aim_cap );
    } else if( gun_skill == skill_pistol ) {
        aim_cap = std::max( 15.0, aim_cap * 1.25 );
    } else if( gun_skill == skill_rifle ) {
        aim_cap = std::max( 7.0, aim_cap - 5.0 );
    } else if( gun_skill == skill_archery ) {
        aim_cap = std::max( 13.0, aim_cap );
    } else { // Launchers, etc.
        aim_cap = std::max( 10.0, aim_cap );
    }
    return aim_cap;
}
References item::gun_skill(), skill_archery, skill_pistol, skill_rifle, skill_shotgun, skill_smg, and item::volume().
Referenced by aim_per_move().
aim_per_move()
double ranged::aim_per_move (const Character & who, const item & gun, double recoil)
Calculates aim improvement per move spent aiming at a given.
Parameters
recoil
Dexterity increases aiming speed
Definition at line 3875 of file ranged.cpp.
{
    if( !gun.is_gun() ) {
        return 0.0;
    }
    std::pair<int, int> best_sight = get_fastest_sight( who, gun, recoil );
    int sight_speed_modifier = best_sight.first;
    int limit = best_sight.second;
    if( sight_speed_modifier == INT_MIN ) {
        // No suitable sights (already at maximum aim).
        return 0;
    }
    // Overall strategy for determining aim speed is to sum the factors that contribute to it,
    // then scale that speed by current recoil level.
    // Player capabilities make aiming faster, and aim speed slows down as it approaches 0.
    // Base speed is non-zero to prevent extreme rate changes as aim speed approaches 0.
    double aim_speed = 10.0;
    skill_id gun_skill = gun.gun_skill();
    // Ranges [0 - 10]
    aim_speed += aim_speed_skill_modifier( who, gun_skill );
    // Range [0 - 12]
    /** @EFFECT_DEX increases aiming speed */
    aim_speed += aim_speed_dex_modifier( who );
    // Range [0 - 10]
    aim_speed += sight_speed_modifier;
    // Each 5 points (combined) of hand encumbrance decreases aim speed by one unit.
    aim_speed -= aim_speed_encumbrance_modifier( who );
    aim_speed = std::min( aim_speed, aim_cap_from_volume( gun ) );
    // Just a raw scaling factor.
    aim_speed *= 6.5;
    // Scale rate logistically as recoil goes from MAX_RECOIL to 0.
    aim_speed *= 1.0 - logarithmic_range( 0, MAX_RECOIL, recoil );
    // Minimum improvement is 5MoA.  This mostly puts a cap on how long aiming for sniping takes.
    aim_speed = std::max( aim_speed, 5.0 );
    // Never improve by more than the currently used sights permit.
    return std::min( aim_speed, recoil - limit );
}
References aim_cap_from_volume(), aim_speed_dex_modifier(), aim_speed_encumbrance_modifier(), aim_speed_skill_modifier(), get_fastest_sight(), item::gun_skill(), item::is_gun(), logarithmic_range(), and MAX_RECOIL.
Referenced by npc::aim(), do_aim(), gun_engagement_moves(), item::gun_info(), npc::method_of_attack(), and target_ui::panel_fire_mode_aim().
aim_speed_dex_modifier()
double ranged::aim_speed_dex_modifier (const Character & who)
Definition at line 3844 of file ranged.cpp.
{
    return who.get_dex() - 8;
}
References Character::get_dex().
Referenced by aim_per_move().
aim_speed_encumbrance_modifier()
double ranged::aim_speed_encumbrance_modifier (const Character & who)
Definition at line 3849 of file ranged.cpp.
{
    return ( who.encumb( bp_hand_l ) + who.encumb( bp_hand_r ) ) / 10.0;
}
References bp_hand_l, bp_hand_r, and Character::encumb().
Referenced by aim_per_move(), and get_encumbrance_description().
aim_speed_skill_modifier()
double ranged::aim_speed_skill_modifier (const Character & who, const skill_id & gun_skill)
Pistol increases aiming speed for pistols Smg increases aiming speed for SMGs Rifle increases aiming speed for rifles Shotgun increases aiming speed for shotguns Launcher increases aiming speed for launchers
Definition at line 3828 of file ranged.cpp.
{
    double skill_mult = 1.0;
    if( gun_skill == skill_pistol ) {
        skill_mult = 2.0;
    } else if( gun_skill == skill_rifle ) {
        skill_mult = 0.9;
    }
    /** @EFFECT_PISTOL increases aiming speed for pistols */
    /** @EFFECT_SMG increases aiming speed for SMGs */
    /** @EFFECT_RIFLE increases aiming speed for rifles */
    /** @EFFECT_SHOTGUN increases aiming speed for shotguns */
    /** @EFFECT_LAUNCHER increases aiming speed for launchers */
    return skill_mult * std::min( MAX_SKILL, who.get_skill_level( gun_skill ) );
}
References Character::get_skill_level(), MAX_SKILL, skill_pistol, and skill_rifle.
Referenced by aim_per_move().
burst_penalty()
int ranged::burst_penalty (const Character & p, const item & gun, int gun_recoil)
Dexterity reduces burst penalty by flat amount Strength reduces burst fire penalty Pistol reduces burst fire penalty Smg reduces burst fire penalty Rifle reduces burst fire penalty Shotgun reduces burst fire penalty
Definition at line 2138 of file ranged.cpp.
{
    ///\EFFECT_DEX reduces burst penalty by flat amount
    int dex_effect = p.get_dex() * 10;
    ///\EFFECT_STR reduces burst fire penalty
    float str_effect = p.get_str() * 0.5f;
    /** @EFFECT_PISTOL reduces burst fire penalty */
    /** @EFFECT_SMG reduces burst fire penalty */
    /** @EFFECT_RIFLE reduces burst fire penalty */
    /** @EFFECT_SHOTGUN reduces burst fire penalty */
    int skill_lvl = std::min( p.get_skill_level( gun.gun_skill() ), MAX_SKILL );
    return std::max<int>( 0, 3 * ( gun_recoil - dex_effect ) / std::max( 1.0f,
                          str_effect + skill_lvl ) );
}
References Character::get_dex(), Character::get_skill_level(), Character::get_str(), item::gun_skill(), and MAX_SKILL.
Referenced by calculate_dispersion(), and item::gun_info().
draw_cone_aoe()
void ranged::draw_cone_aoe (const tripoint & origin, const std::map< tripoint, double > & aoe)
Definition at line 1084 of file animation.cpp.
{
    if( test_mode ) {
        return;
    }
    bucketed_points buckets = bucket_by_distance( origin, aoe );
    // That hardcoded value could be improved... Not sure about the name
    size_t max_bucket_count = std::min<size_t>( 10, aoe.size() );
    bucketed_points waves = optimal_bucketing( buckets, max_bucket_count );
#if defined(TILES)
    if( !use_tiles ) {
        draw_cone_aoe_curses( origin, waves );
        return;
    }
    // This is copied from explosion code
    // Not sure if it couldn't be cleaner, without that lambda capture thing
    one_bucket combined_layer;
    combined_layer.reserve( aoe.size() );
    wave_animation anim;
    shared_ptr_fast<game::draw_callback_t> wave_cb =
    make_shared_fast<game::draw_callback_t>( [&]() {
        tilecontext->init_draw_cone_aoe( origin, combined_layer );
    } );
    g->add_draw_callback( wave_cb );
    for( const one_bucket &layer : waves ) {
        // Older layers get a fade effect
        for( point_with_value &pv : combined_layer ) {
            pv.val *= 1.0 - ( 2.0 / max_bucket_count );
        }
        combined_layer.insert( combined_layer.end(), layer.begin(), layer.end() );
        if( std::any_of( combined_layer.begin(), combined_layer.end(),
        []( const point_with_value & element ) {
        return is_point_visible( element.pt );
        } ) ) {
            anim.progress();
        }
    }
    tilecontext->void_cone_aoe();
#else
    draw_cone_aoe_curses( origin, waves );
#endif
}
References bucket_by_distance(), draw_cone_aoe_curses(), g, optimal_bucketing(), test_mode, and use_tiles.
Referenced by execute_shaped_attack().
effective_dispersion()
int ranged::effective_dispersion (const Character & who, int dispersion)
Perception penalizes sight dispersion when low.
Definition at line 3776 of file ranged.cpp.
{
    /** @EFFECT_PER penalizes sight dispersion when low. */
    dispersion += who.ranged_per_mod();
    dispersion += who.encumb( bp_eyes ) / 2;
    return std::max( dispersion, 0 );
}
References bp_eyes, Character::encumb(), and Character::ranged_per_mod().
Referenced by get_aim_types(), get_fastest_sight(), get_most_accurate_sight(), item::gun_info(), npc_ai::gun_value(), target_ui::panel_recoil(), print_aim(), and target_ui::run().
execute_shaped_attack()
void ranged::execute_shaped_attack (const shape & sh, const projectile & proj, Creature & attacker)
AoE attack, with area given by shape.
Definition at line 44 of file ranged_aoe.cpp.
{
    map &here = get_map();
    const auto sigdist_to_coverage = []( const double sigdist ) {
        return std::min( 1.0, -sigdist );
    };
    const auto aoe_permeable = [&here]( const tripoint & p ) {
        return here.passable( p ) ||
               // Necessary evil. TODO: Make map::shoot not evil.
               ( here.is_transparent( p ) && here.has_flag_furn( TFLAG_PERMEABLE, p ) );
    };
    const tripoint &origin = sh.get_origin();
    std::priority_queue<tripoint_distance> queue;
    std::map<tripoint, aoe_flood_node> open;
    std::set<tripoint> closed;
    for( const tripoint &child : here.points_in_radius( origin, 1 ) ) {
        double coverage = sigdist_to_coverage( sh.distance_at( child ) );
        if( coverage > 0.0 && !get_map().obstructed_by_vehicle_rotation( origin, child ) ) {
            open[child] = aoe_flood_node( origin, 1.0 );
            queue.emplace( child, trig_dist_squared( origin, child ) );
        }
    }
    open[origin] = aoe_flood_node( origin, 1.0 );
    std::map<tripoint, double> final_coverage;
    while( !queue.empty() ) {
        tripoint p = queue.top().p;
        queue.pop();
        if( closed.count( p ) != 0 || !here.inbounds( p ) ) {
            continue;
        }
        closed.insert( p );
        double parent_coverage = open.at( p ).parent_coverage;
        if( parent_coverage <= 0.0 ) {
            continue;
        }
        double current_coverage = parent_coverage;
        if( aoe_permeable( p ) ) {
            // noop
        } else {
            projectile proj_copy = proj;
            here.shoot( p, proj_copy, false );
            // There should be a nicer way than rechecking after shoot
            if( !aoe_permeable( p ) ) {
                continue;
            }
            float total_dmg = proj_copy.impact.total_damage();
            float old_total_dmg = proj.impact.total_damage();
            if( old_total_dmg != total_dmg ) {
                current_coverage *= std::min( 1.0f, old_total_dmg / total_dmg );
            }
        }
        if( current_coverage > 0.0 ) {
            for( const tripoint &child : here.points_in_radius( p, 1 ) ) {
                double coverage = sigdist_to_coverage( sh.distance_at( child ) );
                if( coverage > 0.0 && !get_map().obstructed_by_vehicle_rotation( p, child ) &&
                    closed.count( child ) == 0 &&
                    ( open.count( child ) == 0 || open.at( child ).parent_coverage < current_coverage ) ) {
                    open[child] = aoe_flood_node( p, current_coverage );
                    queue.emplace( child, trig_dist_squared( origin, child ) );
                }
            }
            final_coverage[p] = current_coverage;
        }
    }
    draw_cone_aoe( origin, final_coverage );
    // Here and not above because we want the animation first
    // Terrain will be shown damaged, but having it in unknown state would complicate timing the animation
    for( const std::pair<const tripoint, double> &pr : final_coverage ) {
        Creature *critter = g->critter_at( pr.first );
        if( critter != nullptr ) {
            ranged::hit_with_aoe( *critter, &attacker, proj.impact );
        }
    }
}
References shape::distance_at(), draw_cone_aoe(), g, get_map(), shape::get_origin(), map::has_flag_furn(), hit_with_aoe(), projectile::impact, map::inbounds(), map::is_transparent(), open(), map::passable(), map::points_in_radius(), map::shoot(), TFLAG_PERMEABLE, damage_instance::total_damage(), and trig_dist_squared().
Referenced by fire_gun().
expected_coverage()
std::map< tripoint, double > ranged::expected_coverage (const shape & sh, const map & here, int bash_power)
Definition at line 129 of file ranged_aoe.cpp.
{
    const auto sigdist_to_coverage = []( const double sigdist ) {
        return std::min( 1.0, -sigdist );
    };
    const tripoint &origin = sh.get_origin();
    std::priority_queue<tripoint_distance> queue;
    std::map<tripoint, aoe_flood_node> open;
    std::set<tripoint> closed;
    for( const tripoint &child : here.points_in_radius( origin, 1 ) ) {
        double coverage = sigdist_to_coverage( sh.distance_at( child ) );
        if( coverage > 0.0 && !get_map().obstructed_by_vehicle_rotation( origin, child ) ) {
            open[child] = aoe_flood_node( origin, 1.0 );
            queue.emplace( child, trig_dist_squared( origin, child ) );
        }
    }
    open[origin] = aoe_flood_node( origin, 1.0 );
    std::map<tripoint, double> final_coverage;
    while( !queue.empty() ) {
        tripoint p = queue.top().p;
        queue.pop();
        if( closed.count( p ) != 0 ) {
            continue;
        }
        closed.insert( p );
        double parent_coverage = open.at( p ).parent_coverage;
        if( parent_coverage <= 0.0 ) {
            continue;
        }
        double current_coverage = parent_coverage;
        if( here.passable( p ) ||
            // Necessary evil. TODO: Make map::shoot not evil.
            ( here.is_transparent( p ) && here.has_flag_furn( TFLAG_PERMEABLE, p ) ) ) {
            // noop
        } else {
            int bash_str = here.bash_strength( p );
            int bash_res = here.bash_resistance( p );
            if( bash_power < bash_res ) {
                continue;
            }
            int range_width = bash_str - bash_res + 1;
            int fail_width = bash_str - bash_power;
            double fail_chance = static_cast<double>( fail_width ) / ( range_width );
            current_coverage *= 1.0 - std::max( 0.0, fail_chance );
        }
        if( here.veh_at( p ) ) {
            // If a vehicle part is blocking, assume it's indestructible
            continue;
        }
        if( current_coverage > 0.0 ) {
            for( const tripoint &child : here.points_in_radius( p, 1 ) ) {
                double coverage = sigdist_to_coverage( sh.distance_at( child ) );
                if( coverage > 0.0 && !get_map().obstructed_by_vehicle_rotation( p, child ) &&
                    closed.count( child ) == 0 &&
                    ( open.count( child ) == 0 || open.at( child ).parent_coverage < current_coverage ) ) {
                    open[child] = aoe_flood_node( p, current_coverage );
                    queue.emplace( child, trig_dist_squared( origin, child ) );
                }
            }
            final_coverage[p] = current_coverage;
        }
    }
    final_coverage.erase( origin );
    return final_coverage;
}
References map::bash_resistance(), map::bash_strength(), shape::distance_at(), get_map(), shape::get_origin(), map::has_flag_furn(), map::is_transparent(), open(), map::passable(), map::points_in_radius(), TFLAG_PERMEABLE, trig_dist_squared(), and map::veh_at().
Referenced by target_ui::set_cursor_pos().
fire_gun() [1/2]
int ranged::fire_gun (Character & who, const tripoint & target, int shots, item & gun)
Fire a gun or auxiliary gunmod (ignoring any current mode)
Parameters
who Character whose stats to use
target Where the first shot is aimed at (may vary for later shots)
shots Maximum number of shots to fire (less may be fired in some circumstances)
gun Item to fire (which does not necessary have to be in the characters possession)
Returns
Number of shots actually fired
Definition at line 817 of file ranged.cpp.
{
    if( !gun.is_gun() ) {
        debugmsg( "%s tried to fire non-gun (%s).", who.name, gun.tname() );
        return 0;
    }
    bool is_mech_weapon = false;
    if( who.is_mounted() && who.mounted_creature->has_flag( MF_RIDEABLE_MECH ) ) {
        is_mech_weapon = true;
    }
    int shots = max_shots;
    // Number of shots to fire is limited by the amount of remaining ammo
    if( gun.ammo_required() ) {
        shots = std::min( shots, static_cast<int>( gun.ammo_remaining() / gun.ammo_required() ) );
    }
    // cap our maximum burst size by the amount of UPS power left
    if( !gun.has_flag( flag_VEHICLE ) && gun.get_gun_ups_drain() > 0 ) {
        shots = std::min( shots, static_cast<int>( who.charges_of( itype_UPS ) /
                          gun.get_gun_ups_drain() ) );
    }
    if( shots <= 0 ) {
        debugmsg( "Attempted to fire zero or negative shots using %s", gun.tname() );
    }
    cata::optional<shape_factory> shape;
    if( gun.ammo_current() && gun.ammo_current()->ammo ) {
        shape = gun.ammo_current()->ammo->shape;
    }
    map &here = get_map();
    // Shaped attacks don't allow aiming, so they don't suffer from lack of aim either
    int character_recoil = shape ? recoil_vehicle( who ) : recoil_total( who );
    // Penalty is (intentionally) based off mode shots, not ammo-limited.
    dispersion_sources dispersion = calculate_dispersion( here, who, gun, character_recoil,
                                    max_shots > 1 );
    bool aoe_attack = gun.gun_skill() == skill_launcher || shape;
    tripoint aim = target;
    int curshot = 0;
    int hits = 0; // total shots on target
    while( curshot != shots ) {
        if( gun.faults.count( fault_gun_chamber_spent ) && curshot == 0 ) {
            who.moves -= 50;
            gun.faults.erase( fault_gun_chamber_spent );
            who.add_msg_if_player( _( "You cycle your %s manually." ), gun.tname() );
        }
        if( !ranged::handle_gun_damage( who, gun ) ) {
            break;
        }
        // If this is a vehicle mounted turret, which vehicle is it mounted on?
        const vehicle *in_veh = who.has_effect( effect_on_roof )
                                ? veh_pointer_or_null( here.veh_at( who.pos() ) )
                                : nullptr;
        projectile projectile = make_gun_projectile( gun );
        // Damage reduction from insufficient strength, if using a STR_DRAW weapon.
        projectile.impact.mult_damage( ranged::str_draw_damage_modifier( gun, who ) );
        if( who.has_trait( trait_NORANGEDCRIT ) ) {
            projectile.add_effect( ammo_effect_NO_CRIT );
        }
        if( !shape ) {
            auto shot = projectile_attack( projectile, who.pos(), aim, dispersion, &who, in_veh );
            if( shot.missed_by <= .1 ) {
                // TODO: check head existence for headshot
                g->events().send<event_type::character_gets_headshot>( who.getID() );
            }
            if( shot.hit_critter ) {
                hits++;
            }
        } else {
            // 30 degree cap, like for projectiles
            double angle_offset_arcmin = std::min( dispersion.roll(), 1800.0 ) * ( one_in( 2 ) ? 1 : -1 );
            double angle_offset = units::to_radians( units::from_arcmin( angle_offset_arcmin ) );
            double dx = aim.x - who.posx();
            double dy = aim.y - who.posy();
            double new_angle = atan2( dy, dx ) + angle_offset;
            // Always using trig here, rotations in maximum metric are weird
            double length = trig_dist( who.pos(), aim );
            rl_vec3d vec_pos( who.pos() );
            rl_vec3d new_aim = vec_pos + rl_vec3d( length, 0, 0 ).rotated( new_angle );
            ranged::execute_shaped_attack( *shape->create( vec_pos, new_aim ), projectile, who );
        }
        curshot++;
        ranged::make_gun_sound_effect( who, shots > 1, gun );
        cycle_action( gun, who.pos() );
        if( who.has_trait( trait_PYROMANIA ) &&
            !who.has_morale( MORALE_PYROMANIA_STARTFIRE ) &&
            gun.has_flag( flag_PYROMANIAC_WEAPON ) ) {
            who.add_msg_if_player( m_good, _( "You feel a surge of euphoria as flames roar out of the %s!" ),
                                   gun.tname() );
            who.add_morale( MORALE_PYROMANIA_STARTFIRE, 15, 15, 8_hours, 6_hours );
            who.rem_morale( MORALE_PYROMANIA_NOFIRE );
        }
        if( gun.ammo_consume( gun.ammo_required(), who.pos() ) != gun.ammo_required() ) {
            debugmsg( "Unexpected shortage of ammo whilst firing %s", gun.tname() );
            break;
        }
        if( !gun.has_flag( flag_VEHICLE ) ) {
            who.use_charges( itype_UPS, gun.get_gun_ups_drain() );
        }
        if( aoe_attack ) {
            continue; // skip retargeting for launchers
        }
    }
    if( gun.has_flag( flag_RELOAD_AND_SHOOT ) ) {
        // Reset aim for bows and other reload-and-shoot weapons.
        who.recoil = MAX_RECOIL;
    } else {
        // Now actually apply recoil for the future shots
        // But only for one shot, because bursts kinda suck
        int gun_recoil = gun.gun_recoil( can_use_bipod( here, who.pos() ) );
        // If user is currently able to fire a mounted gun freely, penalize recoil based on size class.
        if( gun.has_flag( flag_MOUNTED_GUN ) && !can_use_bipod( here, who.pos() ) ) {
            if( who.get_size() == MS_HUGE ) {
                gun_recoil = gun_recoil * 2;
            } else {
                gun_recoil = gun_recoil * 3;
            }
        }
        who.recoil += gun_recoil;
        if( is_mech_weapon ) {
            // mechs can handle recoil far better. they are built around their main gun.
            who.recoil = who.recoil / 2;
        }
        who.recoil = std::min( MAX_RECOIL, who.recoil );
    }
    // Use different amounts of time depending on the type of gun and our skill
    who.moves -= time_to_attack( who, *gun.type );
    // Practice the base gun skill proportionally to number of hits, but always by one.
    who.as_player()->practice( skill_gun, ( hits + 1 ) * 5 );
    // launchers train weapon skill for both hits and misses.
    int practice_units = aoe_attack ? curshot : hits;
    who.as_player()->practice( gun.gun_skill(), ( practice_units + 1 ) * 5 );
    return curshot;
}
References _, projectile::add_effect(), Character::add_morale(), Creature::add_msg_if_player(), itype::ammo, item::ammo_consume(), item::ammo_current(), ammo_effect_NO_CRIT, item::ammo_remaining(), item::ammo_required(), Creature::as_player(), atan2(), calculate_dispersion(), can_use_bipod(), character_gets_headshot, visitable< T >::charges_of(), cycle_action(), debugmsg, effect_on_roof, execute_shaped_attack(), fault_gun_chamber_spent, item::faults, flag_MOUNTED_GUN(), flag_PYROMANIAC_WEAPON(), flag_RELOAD_AND_SHOOT(), flag_VEHICLE(), units::from_arcmin(), g, item::get_gun_ups_drain(), get_map(), Character::get_size(), Character::getID(), item::gun_recoil(), item::gun_skill(), handle_gun_damage(), Creature::has_effect(), item::has_flag(), Character::has_morale(), Character::has_trait(), projectile::impact, item::is_gun(), Character::is_mounted(), itype_UPS, m_good, make_gun_projectile(), make_gun_sound_effect(), MAX_RECOIL, MF_RIDEABLE_MECH, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, Character::mounted_creature, Creature::moves, MS_HUGE, damage_instance::mult_damage(), Character::name, one_in(), Character::pos(), Character::posx(), Character::posy(), Character::practice(), projectile_attack(), Character::recoil, recoil_total(), recoil_vehicle(), Character::rem_morale(), dispersion_sources::roll(), rl_vec3d::rotated(), skill_gun, skill_launcher, str_draw_damage_modifier(), time_to_attack(), item::tname(), units::to_radians(), trait_NORANGEDCRIT, trait_PYROMANIA, trig_dist(), item::type, Character::use_charges(), map::veh_at(), veh_pointer_or_null(), tripoint::x, and tripoint::y.
fire_gun() [2/2]
int ranged::fire_gun (Character & who, const tripoint & target, int shots = 1)
Fire wielded gun or auxiliary gunmod (ignoring any current mode)
Parameters
who Character whose stats to use (must be wielding a gun)
target Where the first shot is aimed at (may vary for later shots)
shots Maximum number of shots to fire (less may be fired in some circumstances)
Returns
Number of shots actually fired
Definition at line 812 of file ranged.cpp.
{
    return fire_gun( who, target, shots, who.weapon );
}
References fire_gun(), and Character::weapon.
Referenced by npc::execute_action(), aim_activity_actor::finish(), turret_data::fire(), fire_gun(), mattack::frag(), mattack::rifle(), gun_actor::shoot(), and mattack::tankgun().
get_aim_types()
std::vector< ranged::aim_type > ranged::get_aim_types (const Character & who, const item & gun)
Definition at line 1633 of file ranged.cpp.
{
    std::vector<aim_type> aim_types = get_default_aim_type();
    if( !gun.is_gun() ) {
        return aim_types;
    }
    int sight_dispersion = effective_dispersion( who, gun.sight_dispersion() );
    // Aiming thresholds are dependent on weapon sight dispersion, attempting to place thresholds
    // at 10%, 5% and 0% of the difference between MAX_RECOIL and sight dispersion.
    std::vector<int> thresholds = {
        static_cast<int>( ( ( MAX_RECOIL - sight_dispersion ) / 10.0 ) + sight_dispersion ),
        static_cast<int>( ( ( MAX_RECOIL - sight_dispersion ) / 20.0 ) + sight_dispersion ),
        static_cast<int>( sight_dispersion )
    };
    // Remove duplicate thresholds.
    std::vector<int>::iterator thresholds_it = std::adjacent_find( thresholds.begin(),
            thresholds.end() );
    while( thresholds_it != thresholds.end() ) {
        thresholds.erase( thresholds_it );
        thresholds_it = std::adjacent_find( thresholds.begin(), thresholds.end() );
    }
    thresholds_it = thresholds.begin();
    aim_types.push_back( aim_type { _( "Regular" ), "AIMED_SHOT", _( "[%c] to aim and fire." ),
                                    true, *thresholds_it } );
    thresholds_it++;
    if( thresholds_it != thresholds.end() ) {
        aim_types.push_back( aim_type { _( "Careful" ), "CAREFUL_SHOT",
                                        _( "[%c] to take careful aim and fire." ), true,
                                        *thresholds_it } );
        thresholds_it++;
    }
    if( thresholds_it != thresholds.end() ) {
        aim_types.push_back( aim_type { _( "Precise" ), "PRECISE_SHOT",
                                        _( "[%c] to take precise aim and fire." ), true,
                                        *thresholds_it } );
    }
    return aim_types;
}
References _, effective_dispersion(), get_default_aim_type(), item::is_gun(), MAX_RECOIL, and item::sight_dispersion().
Referenced by item::gun_info(), target_ui::init_window_and_input(), and print_aim().
get_fastest_sight()
std::pair< int, int > ranged::get_fastest_sight (const Character & who, const item & gun, double recoil)
Definition at line 3786 of file ranged.cpp.
{
    // Get fastest sight that can be used to improve aim further below @ref recoil.
    int sight_speed_modifier = INT_MIN;
    int limit = 0;
    if( effective_dispersion( who, gun.type->gun->sight_dispersion ) < recoil ) {
        sight_speed_modifier = gun.has_flag( flag_DISABLE_SIGHTS ) ? 0 : 6;
        limit = effective_dispersion( who, gun.type->gun->sight_dispersion );
    }
    for( const auto e : gun.gunmods() ) {
        const islot_gunmod &mod = *e->type->gunmod;
        if( mod.sight_dispersion < 0 || mod.aim_speed < 0 ) {
            continue; // skip gunmods which don't provide a sight
        }
        if( effective_dispersion( who, mod.sight_dispersion ) < recoil &&
            mod.aim_speed > sight_speed_modifier ) {
            sight_speed_modifier = mod.aim_speed;
            limit = effective_dispersion( who, mod.sight_dispersion );
        }
    }
    return std::make_pair( sight_speed_modifier, limit );
}
References effective_dispersion(), flag_DISABLE_SIGHTS(), itype::gun, item::gunmods(), item::has_flag(), and item::type.
Referenced by aim_per_move().
get_most_accurate_sight()
int ranged::get_most_accurate_sight (const Character & who, const item & gun)
Definition at line 3811 of file ranged.cpp.
{
    if( !gun.is_gun() ) {
        return 0;
    }
    int limit = effective_dispersion( who, gun.type->gun->sight_dispersion );
    for( const auto e : gun.gunmods() ) {
        const islot_gunmod &mod = *e->type->gunmod;
        if( mod.aim_speed >= 0 ) {
            limit = std::min( limit, effective_dispersion( who, mod.sight_dispersion ) );
        }
    }
    return limit;
}
References effective_dispersion(), itype::gun, item::gunmods(), item::is_gun(), and item::type.
Referenced by npc::invalidate_range_cache(), and npc::method_of_attack().
get_str_draw_penalty()
float ranged::get_str_draw_penalty (const item & it, const Character & p)
Penalties potentially incurred by STR_DRAW weapons.
Definition at line 1004 of file ranged.cpp.
{
    // We only care if weapon has STR_DRAW, and that the user is weaker than required strength.
    // Also avoid dividing by zero, and skip if we'd just get a result of 1 anyway.
    if( !it.has_flag( flag_STR_DRAW ) || p.get_str() >= it.get_min_str() || it.get_min_str() <= 1 ) {
        return 1.0f;
    }
    // We also don't want to actually reduce values to zero, even if user is debuffed to zero strength.
    float archer_str = std::max( 1, p.get_str() );
    return ( archer_str / it.get_min_str() );
}
References flag_STR_DRAW(), item::get_min_str(), Character::get_str(), and item::has_flag().
Referenced by item::basic_info(), gunmode_checks_common(), str_draw_damage_modifier(), str_draw_dispersion_modifier(), and str_draw_range_modifier().
get_weapon_dispersion()
dispersion_sources ranged::get_weapon_dispersion (const Character & who, const item & obj)
Get weapon's dispersion value modified accoring to character stats.
Driving reduces the inaccuracy penalty when using guns whilst driving Gun improves usage of accurate weapons and sights
Definition at line 1889 of file ranged.cpp.
{
    int weapon_dispersion = obj.gun_dispersion();
    dispersion_sources dispersion( weapon_dispersion );
    dispersion.add_range( who.ranged_dex_mod() );
    dispersion.add_range( ( who.encumb( bp_arm_l ) + who.encumb( bp_arm_r ) ) / 5.0 );
    if( is_driving( who ) ) {
        // get volume of gun (or for auxiliary gunmods the parent gun)
        const item *parent = who.has_item( obj ) ? who.find_parent( obj ) : nullptr;
        const int vol = ( parent ? parent->volume() : obj.volume() ) / 250_ml;
        /** @EFFECT_DRIVING reduces the inaccuracy penalty when using guns whilst driving */
        dispersion.add_range( std::max( vol - who.get_skill_level( skill_driving ), 1 ) * 20 );
    }
    /** @EFFECT_GUN improves usage of accurate weapons and sights */
    double avgSkill = static_cast<double>( who.get_skill_level( skill_gun ) +
                                           who.get_skill_level( obj.gun_skill() ) ) / 2.0;
    avgSkill = std::min( avgSkill, static_cast<double>( MAX_SKILL ) );
    dispersion.add_range( dispersion_from_skill( avgSkill, weapon_dispersion ) );
    if( who.has_bionic( bio_targeting ) ) {
        dispersion.add_multiplier( 0.75 );
    }
    // If using a bow you lack the strength for, increase based on how much weaker shooter is.
    dispersion.add_multiplier( 1 / ranged::str_draw_dispersion_modifier( obj, who ) );
    // Range is effectively four times longer when shooting unflagged/flagged guns underwater/out of water.
    if( who.is_underwater() != obj.has_flag( flag_UNDERWATER_GUN ) ) {
        // Adding dispersion for additional debuff
        dispersion.add_range( 150 );
        dispersion.add_multiplier( 4 );
    }
    // If user is currently able to fire a mounted gun freely, penalize dispersion based on size class.
    if( obj.has_flag( flag_MOUNTED_GUN ) && !can_use_bipod( get_map(), who.pos() ) ) {
        if( who.get_size() == MS_HUGE ) {
            dispersion.add_multiplier( 2 );
        } else {
            dispersion.add_multiplier( 3 );
        }
    }
    return dispersion;
}
References dispersion_sources::add_multiplier(), dispersion_sources::add_range(), bio_targeting, bp_arm_l, bp_arm_r, can_use_bipod(), dispersion_from_skill(), Character::encumb(), visitable< T >::find_parent(), flag_MOUNTED_GUN(), flag_UNDERWATER_GUN(), get_map(), Character::get_size(), Character::get_skill_level(), Character::has_bionic(), visitable< T >::has_item(), is_driving(), Creature::is_underwater(), MAX_SKILL, MS_HUGE, int_id< T >::obj(), Character::pos(), Character::ranged_dex_mod(), skill_driving, skill_gun, str_draw_dispersion_modifier(), and item::volume().
Referenced by calculate_dispersion(), npc::confident_gun_mode_range(), item::gun_info(), npc_ai::gun_value(), and print_aim().
gun_engagement_moves()
int ranged::gun_engagement_moves (const Character & who, const item & gun, int target = 0, int start = MAX_RECOIL)
How many moves does it take to aim gun to the target accuracy.
Definition at line 578 of file ranged.cpp.
{
    int mv = 0;
    double penalty = start;
    while( penalty > target ) {
        double adj = ranged::aim_per_move( who, gun, penalty );
        if( adj <= 0 ) {
            break;
        }
        penalty -= adj;
        mv++;
    }
    return mv;
}
References aim_per_move().
Referenced by game::dump_stats(), item::gun_info(), and print_aim().
gunmode_checks_common()
bool ranged::gunmode_checks_common (avatar & you, const map & m, std::vector< std::string > & messages, const gun_mode & gmode)
Common checks for gunmode (when firing a weapon / manually firing turret)
Parameters
messages Used to store messages describing failed checks
Returns
True if all conditions are true
Definition at line 3665 of file ranged.cpp.
{
    bool result = true;
    // Check that passed gun mode is valid and we are able to use it
    if( !( gmode && you.can_use( *gmode ) ) ) {
        messages.push_back( string_format( _( "You can't currently fire your %s." ),
                                           gmode->tname() ) );
        result = false;
    }
    const optional_vpart_position vp = m.veh_at( you.pos() );
    if( vp && vp->vehicle().player_in_control( you ) && ( gmode->is_two_handed( you ) ||
            gmode->has_flag( flag_FIRE_TWOHAND ) ) ) {
        messages.push_back( string_format( _( "You can't fire your %s while driving." ),
                                           gmode->tname() ) );
        result = false;
    }
    if( gmode->has_flag( flag_FIRE_TWOHAND ) && ( !you.has_two_arms() ||
            you.worn_with_flag( flag_RESTRICT_HANDS ) ) ) {
        messages.push_back( string_format( _( "You need two free hands to fire your %s." ),
                                           gmode->tname() ) );
        result = false;
    }
    if( ranged::get_str_draw_penalty( *gmode, you ) < 0.5f ) {
        messages.push_back( string_format( _( "You don't have enough strength to fire your %s." ),
                                           gmode->tname() ) );
        result = false;
    }
    return result;
}
References _, Character::can_use(), flag_FIRE_TWOHAND(), flag_RESTRICT_HANDS(), get_str_draw_penalty(), item::has_flag(), Character::has_two_arms(), item::is_two_handed(), Character::pos(), string_format(), item::tname(), map::veh_at(), and Character::worn_with_flag().
Referenced by can_fire_turret(), avatar_action::can_fire_weapon(), and target_ui::update_status().
gunmode_checks_weapon()
bool ranged::gunmode_checks_weapon (avatar & you, const map & m, std::vector< std::string > & messages, const gun_mode & gmode)
Various checks for gunmode when firing a weapon.
Parameters
messages Used to store messages describing failed checks
Returns
True if all conditions are true
Definition at line 3701 of file ranged.cpp.
{
    bool result = true;
    if( !gmode->ammo_sufficient() && !gmode->has_flag( flag_RELOAD_AND_SHOOT ) ) {
        if( !gmode->ammo_remaining() ) {
            messages.push_back( string_format( _( "Your %s is empty!" ), gmode->tname() ) );
        } else {
            messages.push_back( string_format( _( "Your %s needs %i charges to fire!" ),
                                               gmode->tname(), gmode->ammo_required() ) );
        }
        result = false;
    }
    if( gmode->get_gun_ups_drain() > 0 ) {
        const int ups_drain = gmode->get_gun_ups_drain();
        const int adv_ups_drain = std::max( 1, ups_drain * 3 / 5 );
        bool is_mech_weapon = false;
        if( you.is_mounted() ) {
            monster *mons = get_player_character().mounted_creature.get();
            if( !mons->type->mech_weapon.is_empty() ) {
                is_mech_weapon = true;
            }
        }
        if( !is_mech_weapon ) {
            if( !( you.has_charges( itype_UPS_off, ups_drain ) ||
                   you.has_charges( itype_adv_UPS_off, adv_ups_drain ) ||
                   ( you.has_active_bionic( bio_ups ) &&
                     you.get_power_level() >= units::from_kilojoule( ups_drain ) ) ) ) {
                messages.push_back( string_format(
                                        _( "You need a UPS with at least %2$d charges or an advanced UPS with at least %3$d charges to fire the %1$s!" ),
                                        gmode->tname(), ups_drain, adv_ups_drain ) );
                result = false;
            }
        } else {
            if( !you.has_charges( itype_UPS, ups_drain ) ) {
                messages.push_back( string_format( _( "Your mech has an empty battery, its %s will not fire." ),
                                                   gmode->tname() ) );
                result = false;
            }
        }
    }
    if( gmode->has_flag( flag_MOUNTED_GUN ) ) {
        const bool v_mountable = static_cast<bool>( m.veh_at( you.pos() ).part_with_feature( "MOUNTABLE",
                                 true ) );
        bool t_mountable = m.has_flag_ter_or_furn( flag_MOUNTABLE, you.pos() );
        if( !t_mountable && !v_mountable && !( you.get_size() > MS_MEDIUM ) ) {
            messages.push_back( string_format(
                                    _( "You must stand near acceptable terrain or furniture to fire the %s.  A table, a mound of dirt, a broken window, etc." ),
                                    gmode->tname() ) );
            result = false;
        }
    }
    return result;
}
References _, item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), bio_ups, flag_MOUNTABLE(), flag_MOUNTED_GUN(), flag_RELOAD_AND_SHOOT(), units::from_kilojoule(), item::get_gun_ups_drain(), get_player_character(), Character::get_power_level(), Character::get_size(), Character::has_active_bionic(), Character::has_charges(), item::has_flag(), map::has_flag_ter_or_furn(), string_id< T >::is_empty(), Character::is_mounted(), itype_adv_UPS_off, itype_UPS, itype_UPS_off, mtype::mech_weapon, Character::mounted_creature, MS_MEDIUM, optional_vpart_position::part_with_feature(), Character::pos(), string_format(), item::tname(), monster::type, and map::veh_at().
Referenced by avatar_action::can_fire_weapon(), and target_ui::update_status().
handle_gun_damage()
bool ranged::handle_gun_damage (Character & shooter, item & it)
Returns true if a gun misfires, jams, or has other problems, else returns false.
Definition at line 595 of file ranged.cpp.
{
    // Below item (maximum dirt possible) should be greater than or equal to dirt range in item_group.cpp. Also keep in mind that monster drops can have specific ranges and these should be below the max!
    const double dirt_max_dbl = 10000;
    if( !it.is_gun() ) {
        debugmsg( "Tried to handle_gun_damage of a non-gun %s", it.tname() );
        return false;
    }
    int dirt = it.get_var( "dirt", 0 );
    int dirtadder = 0;
    double dirt_dbl = static_cast<double>( dirt );
    if( it.faults.count( fault_gun_chamber_spent ) ) {
        return false;
    }
    const auto &curammo_effects = it.ammo_effects();
    const islot_gun &firing = *it.type->gun;
    // misfire chance based on dirt accumulation. Formula is designed to make chance of jam highly unlikely at low dirt levels, but levels increase geometrically as the dirt level reaches max (10,000). The number used is just a figure I found reasonable after plugging the number into excel and changing it until the probability made sense at high, medium, and low levels of dirt.
    if( !it.has_flag( flag_NEVER_JAMS ) &&
        x_in_y( dirt_dbl * dirt_dbl * dirt_dbl,
                1000000000000.0 ) ) {
        shooter.add_msg_player_or_npc(
            _( "Your %s misfires with a muffled click!" ),
            _( "<npcname>'s %s misfires with a muffled click!" ),
            it.tname() );
        // at high dirt levels the chance to misfire gets to significant levels. 10,000 is max and 7800 is quite high so above that the player gets some relief in the form of exchanging time for some dirt reduction. Basically jiggling the parts loose to remove some dirt and get a few more shots out.
        if( dirt_dbl >
            7800 ) {
            shooter.add_msg_player_or_npc(
                _( "Perhaps taking the ammo out of your %s and reloading will help." ),
                _( "Perhaps taking the ammo out of <npcname>'s %s and reloading will help." ),
                it.tname() );
        }
        return false;
    }
    // Here we check if we're underwater and whether we should misfire.
    // As a result this causes no damage to the firearm, note that some guns are waterproof
    // and so are immune to this effect, note also that WATERPROOF_GUN status does not
    // mean the gun will actually be accurate underwater.
    int effective_durability = firing.durability;
    if( shooter.is_underwater() && !it.has_flag( "WATERPROOF_GUN" ) &&
        one_in( effective_durability ) ) {
        shooter.add_msg_player_or_npc( _( "Your %s misfires with a wet click!" ),
                                       _( "<npcname>'s %s misfires with a wet click!" ),
                                       it.tname() );
        return false;
        // Here we check for a chance for the weapon to suffer a mechanical malfunction.
        // Note that some weapons never jam up 'NEVER_JAMS' and thus are immune to this
        // effect as current guns have a durability between 5 and 9 this results in
        // a chance of mechanical failure between 1/(64*3) and 1/(1024*3) on any given shot.
        // the malfunction can't cause damage
    } else if( one_in( ( 2 << effective_durability ) * 3 ) && !it.has_flag( flag_NEVER_JAMS ) ) {
        shooter.add_msg_player_or_npc( _( "Your %s malfunctions!" ),
                                       _( "<npcname>'s %s malfunctions!" ),
                                       it.tname() );
        return false;
        // Here we check for a chance for the weapon to suffer a misfire due to
        // using player-made 'RECYCLED' bullets. Note that not all forms of
        // player-made ammunition have this effect.
    } else if( curammo_effects.count( ammo_effect_RECYCLED ) && one_in( 256 ) ) {
        shooter.add_msg_player_or_npc( _( "Your %s misfires with a muffled click!" ),
                                       _( "<npcname>'s %s misfires with a muffled click!" ),
                                       it.tname() );
        return false;
        // Here we check for a chance for attached mods to get damaged if they are flagged as 'CONSUMABLE'.
        // This is mostly for crappy handmade expedient stuff  or things that rarely receive damage during normal usage.
        // Default chance is 1/10000 unless set via json, damage is proportional to caliber(see below).
        // Can be toned down with 'consume_divisor.'
    } else if( it.has_flag( flag_CONSUMABLE ) && !curammo_effects.count( ammo_effect_LASER ) &&
               !curammo_effects.count( ammo_effect_PLASMA ) && !curammo_effects.count( ammo_effect_EMP ) ) {
        int uncork = ( ( 10 * it.ammo_data()->ammo->loudness )
                       + ( it.ammo_data()->ammo->recoil / 2 ) ) / 100;
        uncork = std::pow( uncork, 3 ) * 6.5;
        for( auto mod : it.gunmods() ) {
            if( mod->has_flag( flag_CONSUMABLE ) ) {
                int dmgamt = uncork / mod->type->gunmod->consume_divisor;
                int modconsume = mod->type->gunmod->consume_chance;
                int initstate = it.damage();
                // fuzz damage if it's small
                if( dmgamt < 1000 ) {
                    dmgamt = rng( dmgamt, dmgamt + 200 );
                    // ignore damage if inconsequential.
                }
                if( dmgamt < 800 ) {
                    dmgamt = 0;
                }
                if( one_in( modconsume ) ) {
                    if( mod->mod_damage( dmgamt ) ) {
                        shooter.add_msg_player_or_npc( m_bad, _( "Your attached %s is destroyed by your shot!" ),
                                                       _( "<npcname>'s attached %s is destroyed by their shot!" ),
                                                       mod->tname() );
                        shooter.i_rem( mod );
                    } else if( it.damage() > initstate ) {
                        shooter.add_msg_player_or_npc( m_bad, _( "Your attached %s is damaged by your shot!" ),
                                                       _( "<npcname>'s %s is damaged by their shot!" ),
                                                       mod->tname() );
                    }
                }
            }
        }
    }
    if( it.has_fault( fault_gun_unlubricated ) &&
        x_in_y( dirt_dbl, dirt_max_dbl ) ) {
        shooter.add_msg_player_or_npc( m_bad, _( "Your %s emits a grimace-inducing screech!" ),
                                       _( "<npcname>'s %s emits a grimace-inducing screech!" ),
                                       it.tname() );
        it.inc_damage();
    }
    if( ( ( !curammo_effects.count( ammo_effect_NON_FOULING ) && !it.has_flag( flag_NON_FOULING ) ) ||
          ( it.has_fault( fault_gun_unlubricated ) ) ) &&
        !it.has_flag( flag_PRIMITIVE_RANGED_WEAPON ) ) {
        if( curammo_effects.count( ammo_effect_BLACKPOWDER ) ||
            it.has_fault( fault_gun_unlubricated ) ) {
            if( ( ( it.ammo_data()->ammo->recoil < firing.min_cycle_recoil ) ||
                  ( it.has_fault( fault_gun_unlubricated ) && one_in( 16 ) ) ) &&
                it.faults_potential().count( fault_gun_chamber_spent ) ) {
                shooter.add_msg_player_or_npc( m_bad, _( "Your %s fails to cycle!" ),
                                               _( "<npcname>'s %s fails to cycle!" ),
                                               it.tname() );
                it.faults.insert( fault_gun_chamber_spent );
                // Don't return false in this case; this shot happens, follow-up ones won't.
            }
        }
        // These are the dirtying/fouling mechanics
        if( !curammo_effects.count( ammo_effect_NON_FOULING ) && !it.has_flag( flag_NON_FOULING ) ) {
            if( dirt < static_cast<int>( dirt_max_dbl ) ) {
                dirtadder = curammo_effects.count( ammo_effect_BLACKPOWDER ) * ( 200 -
                            ( firing.blackpowder_tolerance *
                              2 ) );
                // dirtadder is the dirt-increasing number for shots fired with gunpowder-based ammo. Usually dirt level increases by 1, unless it's blackpowder, in which case it increases by a higher number, but there is a reduction for blackpowder resistance of a weapon.
                if( dirtadder < 0 ) {
                    dirtadder = 0;
                }
                // in addition to increasing dirt level faster, regular gunpowder fouling is also capped at 7,150, not 10,000. So firing with regular gunpowder can never make the gun quite as bad as firing it with black gunpowder. At 7,150 the chance to jam is significantly lower (though still significant) than it is at 10,000, the absolute cap.
                if( curammo_effects.count( ammo_effect_BLACKPOWDER ) ||
                    dirt < 7150 ) {
                    it.set_var( "dirt", std::min( static_cast<int>( dirt_max_dbl ), dirt + dirtadder + 1 ) );
                }
            }
            dirt = it.get_var( "dirt", 0 );
            dirt_dbl = static_cast<double>( dirt );
            if( dirt > 0 && !it.faults.count( fault_gun_blackpowder ) ) {
                it.faults.insert( fault_gun_dirt );
            }
            if( dirt > 0 && curammo_effects.count( ammo_effect_BLACKPOWDER ) ) {
                it.faults.erase( fault_gun_dirt );
                it.faults.insert( fault_gun_blackpowder );
            }
            // end fouling mechanics
        }
    }
    // chance to damage gun due to high levels of dirt. Very unlikely, especially at lower levels and impossible below 5,000. Lower than the chance of a jam at the same levels. 555555... is an arbitrary number that I came up with after playing with the formula in excel. It makes sense at low, medium, and high levels of dirt.
    if( dirt_dbl > 5000 &&
        x_in_y( dirt_dbl * dirt_dbl * dirt_dbl,
                5555555555555 ) ) {
        shooter.add_msg_player_or_npc( m_bad, _( "Your %s is damaged by the high pressure!" ),
                                       _( "<npcname>'s %s is damaged by the high pressure!" ),
                                       it.tname() );
        // Don't increment until after the message
        it.inc_damage();
    }
    return true;
}
References _, Creature::add_msg_player_or_npc(), itype::ammo, item::ammo_data(), ammo_effect_BLACKPOWDER, ammo_effect_EMP, ammo_effect_LASER, ammo_effect_NON_FOULING, ammo_effect_PLASMA, ammo_effect_RECYCLED, item::ammo_effects(), islot_gun::blackpowder_tolerance, item::damage(), debugmsg, islot_gun::durability, fault_gun_blackpowder, fault_gun_chamber_spent, fault_gun_dirt, fault_gun_unlubricated, item::faults, item::faults_potential(), flag_CONSUMABLE(), flag_NEVER_JAMS(), flag_NON_FOULING(), flag_PRIMITIVE_RANGED_WEAPON(), item::get_var(), itype::gun, item::gunmods(), item::has_fault(), item::has_flag(), Character::i_rem(), item::inc_damage(), item::is_gun(), Creature::is_underwater(), m_bad, islot_gun::min_cycle_recoil, one_in(), rng(), item::set_var(), item::tname(), item::type, and x_in_y().
Referenced by fire_gun().
hit_chance()
double ranged::hit_chance (const dispersion_sources & dispersion, double range, double target_size, double missed_by = 1.0)
The chance that a fired shot reaches required accuracy - by default grazing shot.
Parameters
dispersion accuracy of the shot. Must be a purely normal distribution.
range distance between the shooter and the target.
target_size size of the target, in the range (0, 1].
missed_by maximum degree of miss, in the range (0, 1]. Effectively a multiplier on
target_size.
Definition at line 514 of file ballistics.cpp.
{
    if( range <= 0 ) {
        return 1.0;
    }
    double missed_by_tiles = missed_by * target_size;
    //          T = (2*D**2 * (1 - cos V)) ** 0.5   (from iso_tangent)
    //      cos V = 1 - T**2 / (2*D**2)
    double cosV = 1 - missed_by_tiles * missed_by_tiles / ( 2 * range * range );
    double needed_dispersion = ( cosV < -1.0 ? M_PI : acos( cosV ) ) * 180 * 60 / M_PI;
    return normal_cdf( needed_dispersion, dispersion.avg(), dispersion.avg() / 2 );
}
References dispersion_sources::avg(), M_PI, and normal_cdf().
hit_with_aoe()
dealt_damage_instance ranged::hit_with_aoe (Creature & target, Creature * source, const damage_instance & di)
Definition at line 616 of file creature.cpp.
{
    const auto all_body_parts = target.get_body();
    float hit_size_sum = std::accumulate( all_body_parts.begin(), all_body_parts.end(), 0.0f,
    []( float acc, const std::pair<bodypart_str_id, bodypart> &pr ) {
        return acc + pr.first->hit_size;
    } );
    dealt_damage_instance dealt_damage;
    for( const std::pair<const bodypart_str_id, bodypart> &pr : all_body_parts ) {
        damage_instance impact = di;
        impact.mult_damage( pr.first->hit_size / hit_size_sum );
        dealt_damage_instance bp_damage = target.deal_damage( source, pr.first.id(), impact );
        for( size_t i = 0; i < dealt_damage.dealt_dams.size(); i++ ) {
            dealt_damage.dealt_dams[i] += bp_damage.dealt_dams[i];
        }
    }
    dealt_damage.bp_hit = bodypart_str_id::NULL_ID()->token;
    if( get_player_character().sees( target ) ) {
        ranged::print_dmg_msg( target, source, dealt_damage );
    }
    if( target.has_effect( effect_ridden ) ) {
        monster *mons = dynamic_cast<monster *>( &target );
        if( mons && mons->mounted_player && !mons->has_flag( MF_MECH_DEFENSIVE ) ) {
            // TODO: Return value
            hit_with_aoe( *mons->mounted_player, source, di );
        }
    }
    return dealt_damage;
}
References all_body_parts, dealt_damage_instance::bp_hit, Creature::deal_damage(), dealt_damage_instance::dealt_dams, effect_ridden, Creature::get_body(), get_player_character(), Creature::has_effect(), monster::has_flag(), MF_MECH_DEFENSIVE, monster::mounted_player, damage_instance::mult_damage(), string_id< body_part_type >::NULL_ID(), print_dmg_msg(), and body_part_type::token.
Referenced by execute_shaped_attack().
make_gun_sound_effect()
void ranged::make_gun_sound_effect (const Character & who, bool burst, const item & gun)
Definition at line 1774 of file ranged.cpp.
{
    const item::sound_data data = gun.gun_noise( burst );
    if( data.volume > 0 ) {
        sounds::sound( who.pos(), data.volume, sounds::sound_t::combat,
                       data.sound.empty() ? _( "Bang!" ) : data.sound );
    }
    sfx::generate_gun_sound( who.pos(), gun );
}
References _, sounds::combat, sfx::generate_gun_sound(), item::gun_noise(), Character::pos(), item::sound_data::sound, sounds::sound(), and item::sound_data::volume.
Referenced by fire_gun().
print_dmg_msg()
void ranged::print_dmg_msg (Creature & target, Creature * source, const dealt_damage_instance & dealt_dam, hit_tier ht)
Definition at line 554 of file creature.cpp.
{
    std::string message;
    game_message_type sct_color = m_neutral;
    switch( ht ) {
        case hit_tier::grazing:
            message = _( "Grazing hit." );
            sct_color = m_grazing;
        case hit_tier::normal:
            break;
        case hit_tier::critical:
            message = _( "Critical!" );
            sct_color = m_critical;
            break;
    }
    if( source != nullptr && !message.empty() ) {
        source->add_msg_if_player( m_good, message );
    }
    if( dealt_dam.total_damage() == 0 ) {
        //~ 1$ - monster name, 2$ - character's bodypart or monster's skin/armor
        add_msg( _( "The shot reflects off %1$s %2$s!" ), target.disp_name( true ),
                 ( target.is_monster() || dealt_dam.bp_hit == num_bp ) ?
                 target.skin_name() :
                 body_part_name_accusative( dealt_dam.bp_hit ) );
    } else if( target.is_player() ) {
        //monster hits player ranged
        //~ Hit message. 1$s is bodypart name in accusative. 2$d is damage value.
        target.add_msg_if_player( m_bad, _( "You were hit in the %1$s for %2$d damage." ),
                                  body_part_name_accusative( dealt_dam.bp_hit ),
                                  dealt_dam.total_damage() );
    } else if( source != nullptr ) {
        if( source->is_player() ) {
            //player hits monster ranged
            SCT.add( target.pos().xy(),
                     direction_from( point_zero, target.pos().xy() - source->pos().xy() ),
                     get_hp_bar( dealt_dam.total_damage(), target.get_hp_max(), true ).first,
                     m_good, message, sct_color );
            if( target.get_hp() > 0 ) {
                SCT.add( target.pos().xy(),
                         direction_from( point_zero, target.pos().xy() - source->pos().xy() ),
                         get_hp_bar( target.get_hp(), target.get_hp_max(), true ).first, m_good,
                         //~ "hit points", used in scrolling combat text
                         _( "hp" ), m_neutral, "hp" );
            } else {
                SCT.removeCreatureHP();
            }
            //~ %1$s: creature name, %2$d: damage value
            add_msg( m_good, _( "You hit %1$s for %2$d damage." ),
                     target.disp_name(), dealt_dam.total_damage() );
        } else {
            //~ 1$ - shooter, 2$ - target
            add_msg( _( "%1$s shoots %2$s." ),
                     source->disp_name(), target.disp_name() );
        }
    }
}
References _, scrollingcombattext::add(), add_msg(), Creature::add_msg_if_player(), body_part_name_accusative(), dealt_damage_instance::bp_hit, critical, direction_from(), Creature::disp_name(), Creature::get_hp(), get_hp_bar(), Creature::get_hp_max(), grazing, Creature::is_monster(), Creature::is_player(), m_bad, m_critical, m_good, m_grazing, m_neutral, mapgen_defer::message, normal, num_bp, point_zero, Creature::pos(), scrollingcombattext::removeCreatureHP(), SCT, Creature::skin_name(), dealt_damage_instance::total_damage(), and tripoint::xy().
Referenced by hit_with_aoe().
prompt_select_default_ammo_for()
void ranged::prompt_select_default_ammo_for (avatar & u, const item & w)
Prompts to select default ammo compatible with provided gun.
Definition at line 3760 of file ranged.cpp.
{
    item_reload_option opt = character_funcs::select_ammo( u, w, false, true, true );
    if( opt ) {
        if( u.ammo_location && opt.ammo == u.ammo_location ) {
            u.add_msg_if_player( _( "Cleared ammo preferences for %s." ), w.tname() );
            u.ammo_location = item_location();
        } else if( u.has_item( *opt.ammo ) ) {
            u.add_msg_if_player( _( "Selected %s as default ammo for %s." ), opt.ammo->tname(), w.tname() );
            u.ammo_location = opt.ammo;
        } else {
            u.add_msg_if_player( _( "You don't have that ammo on you." ) );
        }
    }
}
References _, player::add_msg_if_player(), item_reload_option::ammo, player::ammo_location, visitable< T >::has_item(), character_funcs::select_ammo(), and item::tname().
Referenced by game::handle_action(), and avatar_action::reload().
recoil_total()
double ranged::recoil_total (const Character & who)
Current total maximum recoil penalty from all sources.
Definition at line 2068 of file ranged.cpp.
{
    return who.recoil + recoil_vehicle( who );
}
References Character::recoil, and recoil_vehicle().
Referenced by fire_gun(), npc::method_of_attack(), npc::move(), target_ui::panel_recoil(), and npc::wont_hit_friend().
recoil_vehicle()
double ranged::recoil_vehicle (const Character & who)
Get maximum recoil penalty due to vehicle motion.
Definition at line 2056 of file ranged.cpp.
{
    // TODO: vary penalty dependent upon vehicle part on which player is boarded
    if( who.in_vehicle ) {
        if( const optional_vpart_position vp = get_map().veh_at( who.pos() ) ) {
            return static_cast<double>( std::abs( vp->vehicle().velocity ) ) * 3 / 100;
        }
    }
    return 0;
}
References get_map(), Character::in_vehicle, and Character::pos().
Referenced by fire_gun(), print_aim(), and recoil_total().
str_draw_damage_modifier()
float ranged::str_draw_damage_modifier (const item & it, const Character & p)
Definition at line 1016 of file ranged.cpp.
{
    if( !it.has_flag( flag_STR_DRAW ) || p.get_str() >= it.get_min_str() || it.get_min_str() <= 1 ) {
        return 1.0f;
    }
    if( ranged::get_str_draw_penalty( it, p ) < 0.75f ) {
        return 0.5f;
    } else if( ranged::get_str_draw_penalty( it, p ) < 1.0f ) {
        return 0.75f;
    } else {
        return 1.0f;
    }
}
References flag_STR_DRAW(), item::get_min_str(), Character::get_str(), get_str_draw_penalty(), and item::has_flag().
Referenced by fire_gun(), and item::gun_info().
str_draw_dispersion_modifier()
float ranged::str_draw_dispersion_modifier (const item & it, const Character & p)
Definition at line 1030 of file ranged.cpp.
{
    if( !it.has_flag( flag_STR_DRAW ) || p.get_str() >= it.get_min_str() || it.get_min_str() <= 1 ) {
        return 1.0f;
    }
    if( ranged::get_str_draw_penalty( it, p ) < 0.75f ) {
        return 0.5f;
    } else {
        return 1.0f;
    }
}
References flag_STR_DRAW(), item::get_min_str(), Character::get_str(), get_str_draw_penalty(), and item::has_flag().
Referenced by get_weapon_dispersion().
str_draw_range_modifier()
float ranged::str_draw_range_modifier (const item & it, const Character & p)
Definition at line 1042 of file ranged.cpp.
{
    if( !it.has_flag( flag_STR_DRAW ) || p.get_str() >= it.get_min_str() || it.get_min_str() <= 1 ) {
        return 1.0f;
    }
    if( ranged::get_str_draw_penalty( it, p ) < 0.75f ) {
        return 0.5f;
    } else if( ranged::get_str_draw_penalty( it, p ) < 1.0f ) {
        return 0.75f;
    } else {
        return 1.0f;
    }
}
References flag_STR_DRAW(), item::get_min_str(), Character::get_str(), get_str_draw_penalty(), and item::has_flag().
Referenced by item::gun_range().
targetable_creatures() [1/2]
std::vector< Creature * > ranged::targetable_creatures (const Character & c, const int range)
Definition at line 2076 of file ranged.cpp.
{
    return targetable_creatures( c, range, turret_data() );
}
References c, and targetable_creatures().
Referenced by avatar_action::autoattack(), targetable_creatures(), and target_ui::update_target_list().
targetable_creatures() [2/2]
std::vector< Creature * > ranged::targetable_creatures (const Character & c, const int range, const turret_data & turret)
Definition at line 2081 of file ranged.cpp.
{
    const vehicle *veh_from_turret = turret ? turret.get_veh() : nullptr;
    return g->get_creatures_if( [&c, range, veh_from_turret]( const Creature & critter ) -> bool {
        if( std::round( rl_dist_exact( c.pos(), critter.pos() ) ) > range )
        {
            return false;
        }
        if( !c.sees( critter ) && !c.sees_with_infrared( critter ) )
        {
            return false;
        }
        // TODO: get rid of fake npcs (pos() check)
        if( &c == &critter || c.pos() == critter.pos() || c.attitude_to( critter ) == Creature::Attitude::A_FRIENDLY )
        {
            return false;
        }
        map &here = get_map();
        // TODO: It should use projectile passability checks when finding path, not vision checks.
        std::vector<tripoint> path = here.find_clear_path( c.pos(), critter.pos() );
        tripoint prev_point = c.pos();
        for( const tripoint &point : path )
        {
            if( here.obstructed_by_vehicle_rotation( prev_point, point ) ) {
                //Blocked by a rotated vehicle's walls
                return false;
            }
            prev_point = point;
            if( here.passable( point ) ) {
                // If it's passable, it doesn't block bullets
                continue;
            }
            const vehicle *veh_at_point = veh_pointer_or_null( here.veh_at( point ) );
            if( veh_at_point && veh_at_point != veh_from_turret ) {
                // Vehicles don't have impassable-but-shootable-through parts
                return false;
            }
            if( !here.has_flag_ter( TFLAG_TRANSPARENT, point ) ) {
                // If it's transparent, it's either glass (fine) or reinforced glass (not fine)
                // Hack it with the more common case for now
                // TODO: Handle armored glass
                return false;
            }
        }
        return true;
    } );
}
References c, map::find_clear_path(), g, get_map(), turret_data::get_veh(), Creature::pos(), rl_dist_exact(), TFLAG_TRANSPARENT, and veh_pointer_or_null().
throw_cost()
int ranged::throw_cost (const Character & c, const item & to_throw)
Throw increases throwing speed Dexterity increases throwing speed
Definition at line 975 of file ranged.cpp.
{
    // Very similar to player::attack_cost
    // TODO: Extract into a function?
    // Differences:
    // Dex is more (2x) important for throwing speed
    // At 10 skill, the cost is down to 0.75%, not 0.66%
    const int base_move_cost = to_throw.attack_cost() / 2;
    const int throw_skill = std::min( MAX_SKILL, c.get_skill_level( skill_throw ) );
    ///\EFFECT_THROW increases throwing speed
    const int skill_cost = static_cast<int>( ( base_move_cost * ( 20 - throw_skill ) / 20 ) );
    ///\EFFECT_DEX increases throwing speed
    const int dexbonus = c.get_dex();
    const int encumbrance_penalty = c.encumb( bp_torso ) +
                                    ( c.encumb( bp_hand_l ) + c.encumb( bp_hand_r ) ) / 2;
    const float stamina_ratio = static_cast<float>( c.get_stamina() ) / c.get_stamina_max();
    const float stamina_penalty = 1.0 + std::max( ( 0.25f - stamina_ratio ) * 4.0f, 0.0f );
    int move_cost = base_move_cost;
    // Stamina penalty only affects base/2 and encumbrance parts of the cost
    move_cost += encumbrance_penalty;
    move_cost *= stamina_penalty;
    move_cost += skill_cost;
    move_cost -= dexbonus;
    move_cost *= c.mutation_value( "attackcost_modifier" );
    return std::max( 25, move_cost );
}
References item::attack_cost(), bp_hand_l, bp_hand_r, bp_torso, c, MAX_SKILL, move_cost(), and skill_throw.
Referenced by draw_throw_aim(), and throw_item().
throw_dispersion_per_dodge()
int ranged::throw_dispersion_per_dodge (const Character & c, bool add_encumbrance)
How much dispersion does one point of target's dodge add when throwing at said target?
Dexterity increases throwing accuracy against targets with good dodge stat
Definition at line 1056 of file ranged.cpp.
{
    // +200 per dodge point at 0 dexterity
    // +100 at 8, +80 at 12, +66.6 at 16, +57 at 20, +50 at 24
    // Each 10 encumbrance on either hand is like -1 dex (can bring penalty to +400 per dodge)
    // Maybe TODO: Only use one hand
    const int encumbrance = add_encumbrance ? c.encumb( bp_hand_l ) + c.encumb( bp_hand_r ) : 0;
    ///\EFFECT_DEX increases throwing accuracy against targets with good dodge stat
    float effective_dex = 2 + c.get_dex() / 4.0f - ( encumbrance ) / 40.0f;
    return static_cast<int>( 100.0f / std::max( 1.0f, effective_dex ) );
}
References bp_hand_l, bp_hand_r, and c.
Referenced by draw_stats_info(), set_stats(), and throwing_dispersion().
throw_item()
dealt_projectile_attack ranged::throw_item (Character & who, const tripoint & target, const item & to_throw, cata::optional< tripoint > blind_throw_from_pos)
Execute a throw.
Parameters
who Character whose stats to use
to_throw Item being thrown
blind_throw_from_pos Position of blind throw (if blind throwing)
Strength increases throwing damage Strength increases chance of shattering thrown glass items (NEGATIVE)
Definition at line 1115 of file ranged.cpp.
{
    // Copy the item, we may alter it before throwing
    item thrown = to_throw;
    const int move_cost = ranged::throw_cost( who, to_throw );
    who.mod_moves( -move_cost );
    const int throwing_skill = who.get_skill_level( skill_throw );
    units::volume volume = to_throw.volume();
    units::mass weight = to_throw.weight();
    // Previously calculated as 2_gram * std::max( 1, str_cur )
    // using 16_gram normalizes it to 8 str. Same effort expenditure
    // for being able to throw farther.
    const int weight_cost = weight / ( 16_gram );
    const int encumbrance_cost = roll_remainder( ( who.encumb( bp_arm_l ) + who.encumb(
                                     bp_arm_r ) ) * 2.0f );
    const int stamina_cost = ( weight_cost + encumbrance_cost - throwing_skill + 50 ) * -1;
    bool throw_assist = false;
    int throw_assist_str = 0;
    if( who.is_mounted() ) {
        monster *mons = who.mounted_creature.get();
        if( mons->mech_str_addition() != 0 ) {
            throw_assist = true;
            throw_assist_str = mons->mech_str_addition();
            mons->use_mech_power( -3 );
        }
    }
    if( !throw_assist ) {
        who.mod_stamina( stamina_cost );
    }
    const skill_id &skill_used = skill_throw;
    int skill_level = std::min( MAX_SKILL, who.get_skill_level( skill_throw ) );
    // if you are lying on the floor, you can't really throw that well
    if( who.has_effect( effect_downed ) ) {
        skill_level = std::max( 0, skill_level - 5 );
    }
    // We'll be constructing a projectile
    projectile proj;
    proj.impact = thrown.base_damage_thrown();
    proj.speed = 10 + skill_level;
    auto &impact = proj.impact;
    static const std::set<material_id> ferric = { material_id( "iron" ), material_id( "steel" ) };
    bool do_railgun = who.has_active_bionic( bio_railgun ) && thrown.made_of_any( ferric ) &&
                      !throw_assist;
    // The damage dealt due to item's weight, player's strength, and skill level
    // Up to str/2 or weight/100g (lower), so 10 str is 5 damage before multipliers
    // Railgun doubles the effective strength
    ///\EFFECT_STR increases throwing damage
    double stats_mod = do_railgun ? who.get_str() : ( who.get_str() / 2.0 );
    stats_mod = throw_assist ? throw_assist_str / 2.0 : stats_mod;
    // modify strength impact based on skill level, clamped to [0.15 - 1]
    // mod = mod * [ ( ( skill / max_skill ) * 0.85 ) + 0.15 ]
    stats_mod *= ( std::min( MAX_SKILL,
                             who.get_skill_level( skill_throw ) ) /
                   static_cast<double>( MAX_SKILL ) ) * 0.85 + 0.15;
    impact.add_damage( DT_BASH, std::min( weight / 100.0_gram, stats_mod ) );
    if( thrown.has_flag( "ACT_ON_RANGED_HIT" ) ) {
        proj.add_effect( ammo_effect_ACT_ON_RANGED_HIT );
        thrown.active = true;
    }
    // Item will shatter upon landing, destroying the item, dealing damage, and making noise
    /** @EFFECT_STR increases chance of shattering thrown glass items (NEGATIVE) */
    const bool shatter = !thrown.active && thrown.made_of( material_id( "glass" ) ) &&
                         rng( 0, units::to_milliliter( 2_liter - volume ) ) < who.get_str() * 100;
    // Item will burst upon landing, destroying the item, and spilling its contents
    const bool burst = thrown.has_property( "burst_when_filled" ) && thrown.is_container() &&
                       thrown.get_property_int64_t( "burst_when_filled" ) <= static_cast<double>
                       ( thrown.get_contained().volume().value() ) / thrown.get_container_capacity().value() * 100;
    // Add some flags to the projectile
    if( weight > 500_gram ) {
        proj.add_effect( ammo_effect_HEAVY_HIT );
    }
    proj.add_effect( ammo_effect_NO_ITEM_DAMAGE );
    if( thrown.active ) {
        // Can't have Molotovs embed into monsters
        // Monsters don't have inventory processing
        proj.add_effect( ammo_effect_NO_EMBED );
    }
    if( do_railgun ) {
        proj.add_effect( ammo_effect_LIGHTNING );
    }
    if( volume > 500_ml ) {
        proj.add_effect( ammo_effect_WIDE );
    }
    // Deal extra cut damage if the item breaks
    if( shatter ) {
        impact.add_damage( DT_CUT, units::to_milliliter( volume ) / 500.0f );
        proj.add_effect( ammo_effect_SHATTER_SELF );
    }
    // TODO: Add wet effect if other things care about that
    if( burst ) {
        proj.add_effect( ammo_effect_BURST );
    }
    // Some minor (skill/2) armor piercing for skillful throws
    // Not as much as in melee, though
    for( damage_unit &du : impact.damage_units ) {
        du.res_pen += skill_level / 2.0f;
    }
    // handling for tangling thrown items
    if( thrown.has_flag( "TANGLE" ) ) {
        proj.add_effect( ammo_effect_TANGLE );
    }
    Creature *critter = g->critter_at( target, true );
    const dispersion_sources dispersion( ranged::throwing_dispersion( who, thrown, critter,
                                         blind_throw_from_pos.has_value() ) );
    const itype *thrown_type = thrown.type;
    // Put the item into the projectile
    proj.set_drop( std::move( thrown ) );
    if( thrown_type->has_flag( "CUSTOM_EXPLOSION" ) ) {
        proj.set_custom_explosion( thrown_type->explosion );
    }
    // Throw from the player's position, unless we're blind throwing, in which case
    // throw from the the blind throw position instead.
    const tripoint throw_from = blind_throw_from_pos ? *blind_throw_from_pos : who.pos();
    float range = rl_dist( throw_from, target );
    proj.range = range;
    int skill_lvl = who.get_skill_level( skill_used );
    // Avoid awarding tons of xp for lucky throws against hard to hit targets
    const float range_factor = std::min<float>( range, skill_lvl + 3 );
    // We're aiming to get a damaging hit, not just an accurate one - reward proper weapons
    const float damage_factor = 5.0f * std::sqrt( proj.impact.total_damage() / 5.0f );
    // This should generally have values below ~20*sqrt(skill_lvl)
    const float final_xp_mult = range_factor * damage_factor;
    auto dealt_attack = projectile_attack( proj, throw_from, target, dispersion, &who );
    const double missed_by = dealt_attack.missed_by;
    if( missed_by <= 0.1 && dealt_attack.hit_critter != nullptr ) {
        who.as_player()->practice( skill_used, final_xp_mult, MAX_SKILL );
        // TODO: Check target for existence of head
        g->events().send<event_type::character_gets_headshot>( who.getID() );
    } else if( dealt_attack.hit_critter != nullptr && missed_by > 0.0f ) {
        who.as_player()->practice( skill_used, final_xp_mult / ( 1.0f + missed_by ), MAX_SKILL );
    } else {
        // Pure grindy practice - cap gain at lvl 2
        who.as_player()->practice( skill_used, 5, 2 );
    }
    // Reset last target pos
    who.last_target_pos = cata::nullopt;
    who.recoil = MAX_RECOIL;
    return dealt_attack;
}
References item::active, projectile::add_effect(), ammo_effect_ACT_ON_RANGED_HIT, ammo_effect_BURST, ammo_effect_HEAVY_HIT, ammo_effect_LIGHTNING, ammo_effect_NO_EMBED, ammo_effect_NO_ITEM_DAMAGE, ammo_effect_SHATTER_SELF, ammo_effect_TANGLE, ammo_effect_WIDE, Creature::as_player(), item::base_damage_thrown(), bio_railgun, bp_arm_l, bp_arm_r, character_gets_headshot, DT_BASH, DT_CUT, effect_downed, Character::encumb(), itype::explosion, g, item::get_contained(), item::get_container_capacity(), item::get_property_int64_t(), Character::get_skill_level(), Character::get_str(), Character::getID(), Character::has_active_bionic(), Creature::has_effect(), item::has_flag(), itype::has_flag(), item::has_property(), cata::optional< T >::has_value(), projectile::impact, item::is_container(), Character::is_mounted(), Character::last_target_pos, item::made_of(), item::made_of_any(), MAX_RECOIL, MAX_SKILL, monster::mech_str_addition(), Creature::mod_moves(), Character::mod_stamina(), Character::mounted_creature, avatar_action::move(), move_cost(), cata::nullopt, Character::pos(), Character::practice(), projectile_attack(), projectile::range, Character::recoil, damage_unit::res_pen, rl_dist(), rng(), roll_remainder(), projectile::set_custom_explosion(), projectile::set_drop(), skill_throw, projectile::speed, throw_cost(), throwing_dispersion(), units::to_milliliter(), damage_instance::total_damage(), item::type, monster::use_mech_power(), units::quantity< V, U >::value(), item::volume(), and item::weight().
Referenced by throw_activity_actor::do_turn(), and npc_throw().
throwing_dispersion()
int ranged::throwing_dispersion (const Character & c, const item & to_throw, Creature * critter, bool is_blind_throw)
Dispersion of a thrown item, against a given target, taking into account whether or not the throw was blind.
Strength decreases throwing dispersion when throwing heavy objects Throw increases throwing accuracy Perception decreases throwing accuracy penalty from eye encumbrance
Definition at line 1070 of file ranged.cpp.
{
    units::mass weight = to_throw.weight();
    units::volume volume = to_throw.volume();
    if( to_throw.count_by_charges() && to_throw.charges > 1 ) {
        weight /= to_throw.charges;
        volume /= to_throw.charges;
    }
    int throw_difficulty = 1000;
    // 1000 penalty for every liter after the first
    // TODO: Except javelin type items
    throw_difficulty += std::max<int>( 0, units::to_milliliter( volume - 1_liter ) );
    // 1 penalty for gram above str*100 grams (at 0 skill)
    ///\EFFECT_STR decreases throwing dispersion when throwing heavy objects
    const int weight_in_gram = units::to_gram( weight );
    throw_difficulty += std::max( 0, weight_in_gram - c.get_str() * 100 );
    // Dispersion from difficult throws goes from 100% at lvl 0 to 20% at lvl 10
    ///\EFFECT_THROW increases throwing accuracy
    const int throw_skill = std::min( MAX_SKILL, c.get_skill_level( skill_throw ) );
    int dispersion = 10 * throw_difficulty / ( 6 * throw_skill + 20 );
    // If the target is a creature, it moves around and ruins aim
    // TODO: Inform projectile functions if the attacker actually aims for the critter or just the tile
    if( critter != nullptr ) {
        // It's easier to dodge at close range (thrower needs to adjust more)
        // Dodge x10 at point blank, x5 at 1 dist, then flat
        float effective_dodge = critter->get_dodge() * std::max( 1, 10 - 5 * rl_dist( c.pos(),
                                critter->pos() ) );
        dispersion += throw_dispersion_per_dodge( c, true ) * effective_dodge;
    }
    // 1 perception per 1 eye encumbrance
    ///\EFFECT_PER decreases throwing accuracy penalty from eye encumbrance
    dispersion += std::max( 0, ( c.encumb( bp_eyes ) - c.get_per() ) * 10 );
    // If throwing blind, we're assuming they mechanically can't achieve the
    // accuracy of a normal throw.
    if( is_blind_throw ) {
        dispersion *= 4;
    }
    return std::max( 0, dispersion );
}
References bp_eyes, c, item::charges, item::count_by_charges(), Creature::get_dodge(), MAX_SKILL, Creature::pos(), rl_dist(), skill_throw, throw_dispersion_per_dodge(), units::to_gram(), units::to_milliliter(), item::volume(), and item::weight().
Referenced by npc::confident_throw_range(), draw_throw_aim(), and throw_item().