Cataclysm BN: spell_effect Namespace Reference
spell_effect Namespace Reference
Functions
void teleport_random (const spell &sp, Creature &caster, const tripoint &)
void pain_split (const spell &, Creature &, const tripoint &)
void target_attack (const spell &sp, Creature &caster, const tripoint &epicenter)
void projectile_attack (const spell &sp, Creature &caster, const tripoint &target)
void cone_attack (const spell &sp, Creature &caster, const tripoint &target)
void line_attack (const spell &sp, Creature &caster, const tripoint &target)
void area_pull (const spell &sp, Creature &caster, const tripoint &center)
void area_push (const spell &sp, Creature &caster, const tripoint &center)
std::set< tripoint > spell_effect_blast (const spell &, const tripoint &, const tripoint &target, int aoe_radius, bool ignore_walls)
std::set< tripoint > spell_effect_cone (const spell &sp, const tripoint &source, const tripoint &target, int aoe_radius, bool ignore_walls)
std::set< tripoint > spell_effect_line (const spell &, const tripoint &source, const tripoint &target, int aoe_radius, bool ignore_walls)
void spawn_ethereal_item (const spell &sp, Creature &, const tripoint &)
void recover_energy (const spell &sp, Creature &, const tripoint &target)
void spawn_summoned_monster (const spell &sp, Creature &caster, const tripoint &target)
void spawn_summoned_vehicle (const spell &sp, Creature &caster, const tripoint &target)
void translocate (const spell &sp, Creature &caster, const tripoint &target)
void timed_event (const spell &sp, Creature &caster, const tripoint &)
void transform_blast (const spell &sp, Creature &caster, const tripoint &target)
void noise (const spell &sp, Creature &, const tripoint &target)
void vomit (const spell &sp, Creature &caster, const tripoint &target)
void explosion (const spell &sp, Creature &caster, const tripoint &target)
void flashbang (const spell &sp, Creature &caster, const tripoint &target)
void mod_moves (const spell &sp, Creature &caster, const tripoint &target)
void map_area (const spell &sp, Creature &caster, const tripoint &)
void morale (const spell &sp, Creature &caster, const tripoint &target)
void charm_monster (const spell &sp, Creature &caster, const tripoint &target)
void mutate (const spell &sp, Creature &caster, const tripoint &target)
void bash (const spell &sp, Creature &caster, const tripoint &target)
void none (const spell &sp, Creature &, const tripoint &target)
Function Documentation
area_pull()
void spell_effect::area_pull (const spell & sp, Creature & caster, const tripoint & center)
Definition at line 692 of file magic_spell_effect.cpp.
{
    area_expander expander;
    expander.max_range = sp.aoe();
    expander.run( center );
    expander.sort_ascending();
    for( const auto &node : expander.area ) {
        if( node.from == node.position ) {
            continue;
        }
        spell_move( sp, caster, node.position, node.from );
    }
    sp.make_sound( caster.pos() );
}
References spell::aoe(), area_expander::area, center, spell::make_sound(), area_expander::max_range, Creature::pos(), area_expander::run(), area_expander::sort_ascending(), and spell_move().
Referenced by spell_type::load().
area_push()
void spell_effect::area_push (const spell & sp, Creature & caster, const tripoint & center)
Definition at line 710 of file magic_spell_effect.cpp.
{
    area_expander expander;
    expander.max_range = sp.aoe();
    expander.run( center );
    expander.sort_descending();
    for( const auto &node : expander.area ) {
        if( node.from == node.position ) {
            continue;
        }
        spell_move( sp, caster, node.from, node.position );
    }
    sp.make_sound( caster.pos() );
}
References spell::aoe(), area_expander::area, center, spell::make_sound(), area_expander::max_range, Creature::pos(), area_expander::run(), area_expander::sort_descending(), and spell_move().
Referenced by spell_type::load().
bash()
void spell_effect::bash (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 1061 of file magic_spell_effect.cpp.
{
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), true );
    for( const tripoint &potential_target : area ) {
        if( !sp.is_valid_target( caster, potential_target ) ) {
            continue;
        }
        // the bash already makes noise, so no need for spell::make_sound()
        get_map().bash( potential_target, sp.damage(), sp.has_flag( spell_flag::SILENT ) );
    }
}
References spell::aoe(), map::bash(), spell::damage(), get_map(), spell::has_flag(), spell::is_valid_target(), Creature::pos(), SILENT, and spell_effect_blast().
Referenced by get_sound_volume(), Character::impact(), spell_type::load(), talk_function::loot_building(), melee_train(), Character::perform_technique(), damage_instance::physical(), and start_location::place_player().
charm_monster()
void spell_effect::charm_monster (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 1013 of file magic_spell_effect.cpp.
{
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), false );
    for( const tripoint &potential_target : area ) {
        if( !sp.is_valid_target( caster, potential_target ) ) {
            continue;
        }
        monster *mon = g->critter_at<monster>( potential_target );
        if( !mon ) {
            continue;
        }
        sp.make_sound( potential_target );
        if( mon->friendly == 0 && mon->get_hp() <= sp.damage() ) {
            mon->unset_dest();
            mon->friendly += sp.duration() / 100;
        }
    }
}
References spell::aoe(), spell::damage(), spell::duration(), monster::friendly, g, monster::get_hp(), spell::is_valid_target(), spell::make_sound(), Creature::pos(), spell_effect_blast(), and monster::unset_dest().
Referenced by spell_type::load().
cone_attack()
void spell_effect::cone_attack (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 528 of file magic_spell_effect.cpp.
{
    damage_targets( sp, caster, spell_effect_area( sp, target, spell_effect_cone, caster,
                    sp.has_flag( spell_flag::IGNORE_WALLS ) ) );
}
References damage_targets(), spell::has_flag(), IGNORE_WALLS, spell_effect_area(), and spell_effect_cone().
Referenced by spell_type::load().
explosion()
void spell_effect::explosion (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 945 of file magic_spell_effect.cpp.
{
    explosion_handler::explosion( target, &caster, sp.damage(), sp.aoe() / 10.0, true );
}
References spell::aoe(), spell::damage(), and explosion_handler::explosion().
Referenced by spell_type::load().
flashbang()
void spell_effect::flashbang (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 950 of file magic_spell_effect.cpp.
{
    if( sp.id()->sprite.length() > 0 ) {
        explosion_handler::flashbang( target, caster.is_avatar() &&
                                      !sp.is_valid_target( valid_target::target_self ), sp.id()->sprite );
    } else {
        explosion_handler::flashbang( target, caster.is_avatar() &&
                                      !sp.is_valid_target( valid_target::target_self ), "explosion" );
    }
}
References explosion_handler::flashbang(), spell::id(), Creature::is_avatar(), spell::is_valid_target(), spell_type::sprite, and target_self.
Referenced by spell_type::load().
line_attack()
void spell_effect::line_attack (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 535 of file magic_spell_effect.cpp.
{
    damage_targets( sp, caster, spell_effect_area( sp, target, spell_effect_line, caster,
                    sp.has_flag( spell_flag::IGNORE_WALLS ) ) );
}
References damage_targets(), spell::has_flag(), IGNORE_WALLS, spell_effect_area(), and spell_effect_line().
Referenced by spell_type::load().
map_area()
void spell_effect::map_area (const spell & sp, Creature & caster, const tripoint &)
Definition at line 977 of file magic_spell_effect.cpp.
{
    const avatar *you = caster.as_avatar();
    if( !you ) {
        // revealing the map only makes sense for the avatar
        return;
    }
    const tripoint_abs_omt center = you->global_omt_location();
    overmap_buffer.reveal( center.xy(), sp.aoe(), center.z() );
}
References spell::aoe(), Creature::as_avatar(), center, Character::global_omt_location(), overmap_buffer, and overmapbuffer::reveal().
Referenced by spell_type::load().
mod_moves()
void spell_effect::mod_moves (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 961 of file magic_spell_effect.cpp.
{
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), false );
    for( const tripoint &potential_target : area ) {
        if( !sp.is_valid_target( caster, potential_target ) ) {
            continue;
        }
        Creature *critter = g->critter_at<Creature>( potential_target );
        if( !critter ) {
            continue;
        }
        sp.make_sound( potential_target );
        critter->moves += sp.damage();
    }
}
References spell::aoe(), spell::damage(), g, spell::is_valid_target(), spell::make_sound(), Creature::moves, Creature::pos(), and spell_effect_blast().
Referenced by spell_type::load().
morale()
void spell_effect::morale (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 988 of file magic_spell_effect.cpp.
{
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), false );
    if( sp.effect_data().empty() ) {
        debugmsg( "ERROR: %s must have a valid morale_type as effect_str.  None specified.",
                  sp.id().c_str() );
        return;
    }
    if( !morale_type( sp.effect_data() ).is_valid() ) {
        debugmsg( "ERROR: %s must have a valid morale_type as effect_str.  %s is invalid.", sp.id().c_str(),
                  sp.effect_data() );
        return;
    }
    for( const tripoint &potential_target : area ) {
        player *player_target;
        if( !( sp.is_valid_target( caster, potential_target ) &&
               ( player_target = g->critter_at<player>( potential_target ) ) ) ) {
            continue;
        }
        player_target->add_morale( morale_type( sp.effect_data() ), sp.damage(), 0, sp.duration_turns(),
                                   sp.duration_turns() / 10, false );
        sp.make_sound( potential_target );
    }
}
References Character::add_morale(), spell::aoe(), string_id< T >::c_str(), spell::damage(), debugmsg, spell::duration_turns(), spell::effect_data(), g, spell::id(), string_id< T >::is_valid(), spell::is_valid_target(), spell::make_sound(), Creature::pos(), and spell_effect_blast().
Referenced by debug_menu::character_edit_menu(), player_morale::consistent_with(), spell_type::load(), morale_crafting_speed_multiplier(), operator*(), and operator*=().
mutate()
void spell_effect::mutate (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 1032 of file magic_spell_effect.cpp.
{
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), false );
    for( const tripoint &potential_target : area ) {
        if( !sp.is_valid_target( caster, potential_target ) ) {
            continue;
        }
        Character *guy = g->critter_at<Character>( potential_target );
        if( !guy ) {
            continue;
        }
        // 10000 represents 100.00% to increase granularity without swapping everything to a float
        if( sp.damage() < rng( 1, 10000 ) ) {
            // chance failure! but keep trying for other targets
            continue;
        }
        if( sp.effect_data().empty() ) {
            guy->mutate();
        } else {
            if( sp.has_flag( spell_flag::MUTATE_TRAIT ) ) {
                guy->mutate_towards( trait_id( sp.effect_data() ) );
            } else {
                guy->mutate_category( sp.effect_data() );
            }
        }
        sp.make_sound( potential_target );
    }
}
References spell::aoe(), spell::damage(), spell::effect_data(), g, spell::has_flag(), spell::is_valid_target(), spell::make_sound(), Character::mutate(), Character::mutate_category(), Character::mutate_towards(), MUTATE_TRAIT, Creature::pos(), rng(), and spell_effect_blast().
Referenced by debug_menu::character_edit_menu(), mattack::gene_sting(), and spell_type::load().
noise()
void spell_effect::noise (const spell & sp, Creature & , const tripoint & target)
Definition at line 924 of file magic_spell_effect.cpp.
{
    sp.make_sound( target, sp.damage() );
}
References spell::damage(), and spell::make_sound().
Referenced by spell_type::load().
none()
void spell_effect::none (const spell & sp, Creature & , const tripoint & target)
Definition at line 906 of file magic_spell_effect.cpp.
{
    debugmsg( "ERROR: %s has invalid spell effect.", sp.name() );
}
References debugmsg, and spell::name().
Referenced by spell_type::load().
pain_split()
void spell_effect::pain_split (const spell & sp, Creature & caster, const tripoint &)
Definition at line 136 of file magic_spell_effect.cpp.
{
    player *p = caster.as_player();
    if( p == nullptr ) {
        return;
    }
    sp.make_sound( caster.pos() );
    add_msg( m_info, _( "Your injuries even out." ) );
    int num_limbs = 0; // number of limbs effected (broken don't count)
    int total_hp = 0; // total hp among limbs
    for( const std::pair<const bodypart_str_id, bodypart> &elem : p->get_body() ) {
        if( elem.first == bodypart_str_id( "num_bp" ) ) {
            continue;
        }
        num_limbs++;
        total_hp += elem.second.get_hp_cur();
    }
    const int hp_each = total_hp / num_limbs;
    p->set_all_parts_hp_cur( hp_each );
}
References _, add_msg(), Creature::as_player(), Creature::get_body(), m_info, spell::make_sound(), Creature::pos(), and Creature::set_all_parts_hp_cur().
Referenced by spell_type::load().
projectile_attack()
void spell_effect::projectile_attack (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 497 of file magic_spell_effect.cpp.
{
    std::vector<tripoint> trajectory = line_to( caster.pos(), target );
    tripoint prev_point = caster.pos();
    map &here = get_map();
    for( std::vector<tripoint>::iterator iter = trajectory.begin(); iter != trajectory.end(); iter++ ) {
        if( ( here.impassable( *iter ) && !here.has_flag( "THIN_OBSTACLE", *iter ) ) ||
            here.obstructed_by_vehicle_rotation( prev_point, *iter ) ) {
            if( iter != trajectory.begin() ) {
                target_attack( sp, caster, *( iter - 1 ) );
            } else {
                target_attack( sp, caster, *iter );
            }
            return;
        }
        prev_point = *iter;
    }
    target_attack( sp, caster, trajectory.back() );
}
References get_map(), map::has_flag(), map::impassable(), line_to(), map::obstructed_by_vehicle_rotation(), Creature::pos(), and target_attack().
Referenced by spell_type::load().
recover_energy()
void spell_effect::recover_energy (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 755 of file magic_spell_effect.cpp.
{
    // this spell is not appropriate for healing
    const int healing = sp.damage();
    const std::string energy_source = sp.effect_data();
    // TODO: Change to Character
    // current limitation is that Character does not have stamina or power_level members
    player *p = g->critter_at<player>( target );
    if( !p ) {
        return;
    }
    if( energy_source == "MANA" ) {
        p->magic->mod_mana( *p, healing );
    } else if( energy_source == "STAMINA" ) {
        p->mod_stamina( healing );
    } else if( energy_source == "FATIGUE" ) {
        // fatigue is backwards
        p->mod_fatigue( -healing );
    } else if( energy_source == "BIONIC" ) {
        if( healing > 0 ) {
            p->mod_power_level( units::from_kilojoule( healing ) );
        } else {
            p->mod_stamina( healing );
        }
    } else if( energy_source == "PAIN" ) {
        // pain is backwards
        if( sp.has_flag( PAIN_NORESIST ) ) {
            p->mod_pain_noresist( -healing );
        } else {
            p->mod_pain( -healing );
        }
    } else if( energy_source == "HEALTH" ) {
        p->mod_healthy( healing );
    } else {
        debugmsg( "Invalid effect_str %s for spell %s", energy_source, sp.name() );
    }
    sp.make_sound( caster.pos() );
}
References spell::damage(), debugmsg, spell::effect_data(), units::from_kilojoule(), g, spell::has_flag(), Character::magic, spell::make_sound(), Character::mod_fatigue(), Character::mod_healthy(), Character::mod_pain(), Creature::mod_pain_noresist(), Character::mod_power_level(), Character::mod_stamina(), spell::name(), PAIN_NORESIST, and Creature::pos().
Referenced by spell_type::load().
spawn_ethereal_item()
void spell_effect::spawn_ethereal_item (const spell & sp, Creature & caster, const tripoint &)
Definition at line 728 of file magic_spell_effect.cpp.
{
    item granted( sp.effect_data(), calendar::turn );
    if( !granted.is_comestible() && !( sp.has_flag( spell_flag::PERMANENT ) && sp.is_max_level() ) ) {
        granted.set_var( "ethereal", to_turns<int>( sp.duration_turns() ) );
        granted.set_flag( "ETHEREAL_ITEM" );
    }
    if( granted.count_by_charges() && sp.damage() > 0 ) {
        granted.charges = sp.damage();
    }
    avatar &you = get_avatar();
    if( you.can_wear( granted ).success() ) {
        granted.set_flag( "FIT" );
        you.wear_item( granted, false );
    } else if( !you.is_armed() ) {
        you.weapon = granted;
    } else {
        you.i_add( granted );
    }
    if( !granted.count_by_charges() ) {
        for( int i = 1; i < sp.damage(); i++ ) {
            you.i_add( granted );
        }
    }
    sp.make_sound( caster.pos() );
}
References Character::can_wear(), item::charges, item::count_by_charges(), spell::damage(), spell::duration_turns(), spell::effect_data(), get_avatar(), spell::has_flag(), Character::i_add(), Character::is_armed(), item::is_comestible(), spell::is_max_level(), spell::make_sound(), PERMANENT, Creature::pos(), item::set_flag(), item::set_var(), calendar::turn, Character::weapon, and Character::wear_item().
Referenced by spell_type::load().
spawn_summoned_monster()
void spell_effect::spawn_summoned_monster (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 853 of file magic_spell_effect.cpp.
{
    const mtype_id mon_id( sp.effect_data() );
    std::set<tripoint> area = spell_effect_area( sp, target, spell_effect_blast, caster );
    // this should never be negative, but this'll keep problems from happening
    size_t num_mons = std::abs( sp.damage() );
    const time_duration summon_time = sp.duration_turns();
    while( num_mons > 0 && !area.empty() ) {
        const size_t mon_spot = rng( 0, area.size() - 1 );
        auto iter = area.begin();
        std::advance( iter, mon_spot );
        if( add_summoned_mon( mon_id, *iter, summon_time, sp ) ) {
            num_mons--;
            sp.make_sound( *iter );
        } else {
            add_msg( m_bad, "failed to place monster" );
        }
        // whether or not we succeed in spawning a monster, we don't want to try this tripoint again
        area.erase( iter );
    }
}
References add_msg(), add_summoned_mon(), spell::damage(), spell::duration_turns(), spell::effect_data(), m_bad, spell::make_sound(), rng(), spell_effect_area(), and spell_effect_blast().
Referenced by spell_type::load().
spawn_summoned_vehicle()
void spell_effect::spawn_summoned_vehicle (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 876 of file magic_spell_effect.cpp.
{
    map &here = get_map();
    if( here.veh_at( target ) ) {
        caster.add_msg_if_player( m_bad, _( "There is already a vehicle there." ) );
        return;
    }
    if( vehicle *veh = here.add_vehicle( sp.summon_vehicle_id(), target, -90_degrees, 100, 0 ) ) {
        veh->magic = true;
        const time_duration summon_time = sp.duration_turns();
        if( !sp.has_flag( spell_flag::PERMANENT ) ) {
            veh->summon_time_limit = summon_time;
        }
        if( caster.as_character() ) {
            veh->set_owner( *caster.as_character() );
        }
    }
}
References _, Creature::add_msg_if_player(), map::add_vehicle(), Creature::as_character(), spell::duration_turns(), get_map(), spell::has_flag(), m_bad, PERMANENT, spell::summon_vehicle_id(), and map::veh_at().
Referenced by spell_type::load().
spell_effect_blast()
std::set< tripoint > spell_effect::spell_effect_blast (const spell & , const tripoint & , const tripoint & target, int aoe_radius, bool ignore_walls)
Definition at line 180 of file magic_spell_effect.cpp.
{
    std::set<tripoint> targets;
    // TODO: Make this breadth-first
    for( const tripoint &potential_target : get_map().points_in_radius( target, aoe_radius ) ) {
        if( in_spell_aoe( target, potential_target, aoe_radius, ignore_walls ) ) {
            targets.emplace( potential_target );
        }
    }
    return targets;
}
References get_map(), in_spell_aoe(), and points_in_radius().
Referenced by bash(), charm_monster(), mod_moves(), morale(), mutate(), spell::random_valid_target(), target_ui::set_cursor_pos(), spawn_summoned_monster(), target_attack(), transform_blast(), translocate(), and vomit().
spell_effect_cone()
std::set< tripoint > spell_effect::spell_effect_cone (const spell & sp, const tripoint & source, const tripoint & target, int aoe_radius, bool ignore_walls)
Definition at line 193 of file magic_spell_effect.cpp.
{
    std::set<tripoint> targets;
    // cones go all the way to end (if they don't hit an obstacle)
    const int range = sp.range() + 1;
    const units::angle initial_angle = coord_to_angle( source, target );
    const units::angle half_width = units::from_degrees( aoe_radius / 2.0 );
    const units::angle start_angle = initial_angle - half_width;
    const units::angle end_angle = initial_angle + half_width;
    std::set<tripoint> end_points;
    for( units::angle angle = start_angle; angle <= end_angle; angle += 1_degrees ) {
        tripoint potential;
        calc_ray_end( angle, range, source, potential );
        end_points.emplace( potential );
    }
    map &here = get_map();
    for( const tripoint &ep : end_points ) {
        std::vector<tripoint> trajectory = line_to( source, ep );
        tripoint last_point = source;
        for( const tripoint &tp : trajectory ) {
            if( ignore_walls || ( !here.obstructed_by_vehicle_rotation( tp, last_point ) &&
                                  ( here.passable( tp ) || here.has_flag( "THIN_OBSTACLE", tp ) ) ) ) {
                targets.emplace( tp );
            } else {
                break;
            }
            last_point = tp;
        }
    }
    // we don't want to hit ourselves in the blast!
    targets.erase( source );
    return targets;
}
References calc_ray_end(), coord_to_angle(), units::from_degrees(), get_map(), map::has_flag(), line_to(), map::obstructed_by_vehicle_rotation(), map::passable(), and spell::range().
Referenced by cone_attack(), and target_ui::set_cursor_pos().
spell_effect_line()
std::set< tripoint > spell_effect::spell_effect_line (const spell & , const tripoint & source, const tripoint & target, int aoe_radius, bool ignore_walls)
Definition at line 239 of file magic_spell_effect.cpp.
{
    const point delta = ( target - source ).xy();
    const int dist = square_dist( point_zero, delta );
    // Early out to prevent unnecessary calculations
    if( dist == 0 ) {
        return std::set<tripoint>();
    }
    // Clockwise Perpendicular of Delta vector
    const point delta_perp( -delta.y, delta.x );
    const point abs_delta = delta.abs();
    // Primary axis of delta vector
    const point axis_delta = abs_delta.x > abs_delta.y ? point( delta.x, 0 ) : point( 0, delta.y );
    // Clockwise Perpendicular of axis vector
    const point cw_perp_axis( -axis_delta.y, axis_delta.x );
    const point unit_cw_perp_axis( sgn( cw_perp_axis.x ), sgn( cw_perp_axis.y ) );
    // bias leg length toward cw side if uneven
    int ccw_len = aoe_radius / 2;
    int cw_len = aoe_radius - ccw_len;
    if( !trigdist ) {
        ccw_len = ( ccw_len * ( abs_delta.x + abs_delta.y ) ) / dist;
        cw_len = ( cw_len * ( abs_delta.x + abs_delta.y ) ) / dist;
    }
    // is delta aligned with, cw, or ccw of primary axis
    int delta_side = spell_detail::side_of( point_zero, axis_delta, delta );
    bool ( *test )( const tripoint &,
                    const tripoint & ) = ignore_walls ? test_always_true : test_passable;
    // Canonical path from source to target, offset to local space
    std::vector<point> path_to_target = line_to( point_zero, delta );
    // Remove endpoint,
    path_to_target.pop_back();
    // and insert startpoint. Path is now prepared for wrapped iteration
    path_to_target.insert( path_to_target.begin(), point_zero );
    spell_detail::line_iterable base_line( point_zero, delta, path_to_target );
    std::set<tripoint> result;
    // Add midline points (source -> target )
    spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
    // Add cw and ccw legs
    if( delta_side == 0 ) { // delta is already axis aligned, only need straight lines
        // cw leg
        point prev_point;
        for( const point &p : line_to( point_zero, unit_cw_perp_axis * cw_len ) ) {
            base_line.reset( p );
            if( !test( source + p, source + prev_point ) ) {
                break;
            }
            spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
            prev_point = p;
        }
        // ccw leg
        prev_point = point_zero;
        for( const point &p : line_to( point_zero, unit_cw_perp_axis * -ccw_len ) ) {
            base_line.reset( p );
            if( !test( source + p, source + prev_point ) ) {
                break;
            }
            spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
            prev_point = p;
        }
    } else if( delta_side == 1 ) { // delta is cw of primary axis
        // ccw leg is behind perp axis
        point prev_point;
        for( const point &p : line_to( point_zero, unit_cw_perp_axis * -ccw_len ) ) {
            base_line.reset( p );
            // forward until in
            while( spell_detail::side_of( point_zero, delta_perp, base_line.get() ) == 1 ) {
                base_line.next();
            }
            if( !test( source + p, source + prev_point ) ) {
                break;
            }
            spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
            prev_point = p;
        }
        prev_point = point_zero;
        // cw leg is before perp axis
        for( const point &p : line_to( point_zero, unit_cw_perp_axis * cw_len ) ) {
            base_line.reset( p );
            // move back
            while( spell_detail::side_of( point_zero, delta_perp, base_line.get() ) != 1 ) {
                base_line.prev();
            }
            base_line.next();
            if( !test( source + p, source + prev_point ) ) {
                break;
            }
            spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
            prev_point = p;
        }
    } else if( delta_side == -1 ) { // delta is ccw of primary axis
        // ccw leg is before perp axis
        point prev_point;
        for( const point &p : line_to( point_zero, unit_cw_perp_axis * -ccw_len ) ) {
            base_line.reset( p );
            // move back
            while( spell_detail::side_of( point_zero, delta_perp, base_line.get() ) != 1 ) {
                base_line.prev();
            }
            base_line.next();
            if( !test( source + p, source + prev_point ) ) {
                break;
            }
            spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
            prev_point = p;
        }
        prev_point = point_zero;
        // cw leg is behind perp axis
        for( const point &p : line_to( point_zero, unit_cw_perp_axis * cw_len ) ) {
            base_line.reset( p );
            // forward until in
            while( spell_detail::side_of( point_zero, delta_perp, base_line.get() ) == 1 ) {
                base_line.next();
            }
            if( !test( source + p, source + prev_point ) ) {
                break;
            }
            spell_detail::build_line( base_line, source, delta, delta_perp, test, result );
            prev_point = p;
        }
    }
    result.erase( source );
    return result;
}
References point::abs(), spell_detail::build_line(), spell_detail::line_iterable::get(), line_to(), spell_detail::line_iterable::next(), point_zero, spell_detail::line_iterable::prev(), spell_detail::line_iterable::reset(), sgn(), spell_detail::side_of(), square_dist(), test_always_true(), test_passable(), trigdist, point::x, and point::y.
Referenced by line_attack(), and target_ui::set_cursor_pos().
target_attack()
void spell_effect::target_attack (const spell & sp, Creature & caster, const tripoint & epicenter)
Definition at line 518 of file magic_spell_effect.cpp.
{
    damage_targets( sp, caster, spell_effect_area( sp, epicenter, spell_effect_blast, caster,
                    sp.has_flag( spell_flag::IGNORE_WALLS ) ) );
    if( sp.has_flag( spell_flag::SWAP_POS ) ) {
        swap_pos( caster, epicenter );
    }
}
References damage_targets(), spell::has_flag(), IGNORE_WALLS, spell_effect_area(), spell_effect_blast(), SWAP_POS, and swap_pos().
Referenced by spell_type::load(), and projectile_attack().
teleport_random()
void spell_effect::teleport_random (const spell & sp, Creature & caster, const tripoint &)
Definition at line 115 of file magic_spell_effect.cpp.
{
    bool safe = !sp.has_flag( spell_flag::UNSAFE_TELEPORT );
    const int min_distance = sp.range();
    const int max_distance = sp.range() + sp.aoe();
    if( min_distance > max_distance || min_distance < 0 || max_distance < 0 ) {
        debugmsg( "ERROR: Teleport argument(s) invalid" );
        return;
    }
    teleport::teleport( caster, min_distance, max_distance, safe, false );
}
References spell::aoe(), debugmsg, spell::has_flag(), spell::range(), iexamine::safe(), teleport::teleport(), and UNSAFE_TELEPORT.
Referenced by spell_type::load().
timed_event()
void spell_effect::timed_event (const spell & sp, Creature & caster, const tripoint &)
Definition at line 795 of file magic_spell_effect.cpp.
{
    const std::map<std::string, timed_event_type> timed_event_map{
        { "help", timed_event_type::TIMED_EVENT_HELP },
        { "wanted", timed_event_type::TIMED_EVENT_WANTED },
        { "robot_attack", timed_event_type::TIMED_EVENT_ROBOT_ATTACK },
        { "spawn_wyrms", timed_event_type::TIMED_EVENT_SPAWN_WYRMS },
        { "amigara", timed_event_type::TIMED_EVENT_AMIGARA },
        { "roots_die", timed_event_type::TIMED_EVENT_ROOTS_DIE },
        { "temple_open", timed_event_type::TIMED_EVENT_TEMPLE_OPEN },
        { "temple_flood", timed_event_type::TIMED_EVENT_TEMPLE_FLOOD },
        { "temple_spawn", timed_event_type::TIMED_EVENT_TEMPLE_SPAWN },
        { "dim", timed_event_type::TIMED_EVENT_DIM },
        { "artifact_light", timed_event_type::TIMED_EVENT_ARTIFACT_LIGHT }
    };
    timed_event_type spell_event = timed_event_type::TIMED_EVENT_NULL;
    const auto iter = timed_event_map.find( sp.effect_data() );
    if( iter != timed_event_map.cend() ) {
        spell_event = iter->second;
    }
    sp.make_sound( caster.pos() );
    g->timed_events.add( spell_event, calendar::turn + sp.duration_turns() );
}
References spell::duration_turns(), spell::effect_data(), g, spell::make_sound(), Creature::pos(), TIMED_EVENT_AMIGARA, TIMED_EVENT_ARTIFACT_LIGHT, TIMED_EVENT_DIM, TIMED_EVENT_HELP, TIMED_EVENT_NULL, TIMED_EVENT_ROBOT_ATTACK, TIMED_EVENT_ROOTS_DIE, TIMED_EVENT_SPAWN_WYRMS, TIMED_EVENT_TEMPLE_FLOOD, TIMED_EVENT_TEMPLE_OPEN, TIMED_EVENT_TEMPLE_SPAWN, TIMED_EVENT_WANTED, and calendar::turn.
Referenced by spell_type::load().
transform_blast()
void spell_effect::transform_blast (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 911 of file magic_spell_effect.cpp.
{
    ter_furn_transform_id transform( sp.effect_data() );
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), true );
    for( const tripoint &location : area ) {
        if( one_in( sp.damage() ) ) {
            transform->transform( location );
            transform->add_all_messages( caster, location );
        }
    }
}
References spell::aoe(), spell::damage(), spell::effect_data(), one_in(), Creature::pos(), spell_effect_blast(), and iexamine::transform().
Referenced by spell_type::load().
translocate()
void spell_effect::translocate (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 896 of file magic_spell_effect.cpp.
{
    avatar *you = caster.as_avatar();
    if( you == nullptr ) {
        return;
    }
    you->translocators->translocate( spell_effect_area( sp, target, spell_effect_blast, caster,
                                     true ) );
}
References Creature::as_avatar(), spell_effect_area(), spell_effect_blast(), and avatar::translocators.
Referenced by spell_type::load().
vomit()
void spell_effect::vomit (const spell & sp, Creature & caster, const tripoint & target)
Definition at line 929 of file magic_spell_effect.cpp.
{
    const std::set<tripoint> area = spell_effect_blast( sp, caster.pos(), target, sp.aoe(), true );
    for( const tripoint &potential_target : area ) {
        if( !sp.is_valid_target( caster, potential_target ) ) {
            continue;
        }
        Character *const ch = g->critter_at<Character>( potential_target );
        if( !ch ) {
            continue;
        }
        sp.make_sound( target );
        ch->vomit();
    }
}
References spell::aoe(), g, spell::is_valid_target(), spell::make_sound(), Creature::pos(), spell_effect_blast(), and Character::vomit().
Referenced by spell_type::load().