Cataclysm BN: distribution_graph Namespace Reference
distribution_graph Namespace Reference
Classes
struct vehicle_or_grid
Enumerations
enum class traverse_visitor_result { stop , continue_further }
Functions
template<typename VehFunc , typename GridFunc , typename StartPoint >
void traverse (StartPoint &start, VehFunc veh_action, GridFunc grid_action)
Traverses the graph of connected vehicles and grids.
constexpr traverse_visitor_result noop_visitor_grid (const distribution_grid &)
constexpr traverse_visitor_result noop_visitor_veh (const vehicle &)
Enumeration Type Documentation
traverse_visitor_result
enum class distribution_graph::traverse_visitor_result strong
Enumerator
stop
continue_further
Definition at line 186 of file distribution_grid.h.
{
    stop,
    continue_further,
};
Function Documentation
noop_visitor_grid()
constexpr traverse_visitor_result distribution_graph::noop_visitor_grid (const distribution_grid &) inline constexpr
Definition at line 206 of file distribution_grid.h.
{
    return traverse_visitor_result::continue_further;
}
References continue_further.
Referenced by vehicle::enumerate_vehicles(), and vehicle::gain_moves().
noop_visitor_veh()
constexpr traverse_visitor_result distribution_graph::noop_visitor_veh (const vehicle &) inline constexpr
Definition at line 212 of file distribution_grid.h.
{
    return traverse_visitor_result::continue_further;
}
References continue_further.
Referenced by vehicle::gain_moves().
traverse()
template<typename VehFunc , typename GridFunc , typename StartPoint > void distribution_graph::traverse (StartPoint & start, VehFunc veh_action, GridFunc grid_action)
Traverses the graph of connected vehicles and grids.
Runs Breadth-First over all vehicles and grids calling passed actions on each of them until any visitor action return traverse_visitor_result::stop. Connected vehicles checked by all POWER_TRANSFER part and grids by vehicle connectors.
Parameters
start Reference to the start node of the graph. Assumed to be already visited.
veh_action Visitor function which accepts vehicle& or const & then returns traverse_visitor_result.
grid_action Visitor function which accepts distribution_grid& or const & then returns traverse_visitor_result.
Definition at line 4982 of file vehicle.cpp.
{
    using tvr = traverse_visitor_result;
    constexpr bool IsConst = std::is_const<StartPoint>::value;
    struct hash {
        const std::hash<char> char_hash = std::hash<char>();
        const std::hash<size_t> ptr_hash = std::hash<size_t>();
        auto operator()( const vehicle_or_grid<IsConst> &elem ) const {
            return char_hash( static_cast<char>( elem.type ) ) ^
                   ptr_hash(
                       // Because only one of pointers is not nullptr, binary OR would get value of set pointer.
                       reinterpret_cast<size_t>( elem.veh ) | reinterpret_cast<size_t>( elem.grid )
                   );
        }
    };
    // Actually, they are visited elements with unvisited neighbours.
    // Not all connected elements are here.
    std::queue<vehicle_or_grid<IsConst>> connected_elements;
    // For fast checking if we should visit some neighbour.
    std::unordered_set<vehicle_or_grid<IsConst>, hash> visited_elements;
    connected_elements.emplace( &start );
    visited_elements.insert( &start );
    auto &grid_tracker = get_distribution_grid_tracker();
    auto enqueue = [&connected_elements, &visited_elements]( vehicle_or_grid<IsConst> newly_visited ) {
        connected_elements.push( newly_visited );
        visited_elements.insert( newly_visited );
    };
    auto was_already_visited = [&visited_elements]( vehicle_or_grid<IsConst> to_visit ) {
        return visited_elements.count( to_visit ) != 0;
    };
    auto process_vehicle = [&]( const tripoint_abs_ms & target_pos ) {
        auto *veh = vehicle::find_vehicle( target_pos );
        if( veh == nullptr ) {
            debugmsg( "lost vehicle at %s", target_pos.to_string() );
            return tvr::continue_further;
        }
        if( was_already_visited( veh ) ) {
            return tvr::continue_further;
        }
        const tvr result = veh_action( *veh );
        g->u.add_msg_if_player( m_debug, "After remote veh %p",
                                static_cast<void *>( veh ) );
        // We do not need to check neighbours if we stop.
        if( result == tvr::continue_further ) {
            enqueue( veh );
        }
        return result;
    };
    auto process_grid = [&]( const tripoint_abs_ms & target_pos ) {
        auto &grid = grid_tracker.grid_at( target_pos );
        if( !grid ) {
            debugmsg( "lost grid at %s", target_pos.to_string() );
            return tvr::continue_further;
        }
        if( was_already_visited( &grid ) ) {
            return tvr::continue_further;
        }
        const tvr result = grid_action( grid );
        g->u.add_msg_if_player( m_debug, "After remote grid %p",
                                static_cast<void *>( &grid ) );
        // We do not need to check neighbours if we stop.
        if( result == tvr::continue_further ) {
            enqueue( &grid );
        }
        return result;
    };
    while( !connected_elements.empty() ) {
        auto current = connected_elements.front();
        connected_elements.pop();
        if( current.type == vehicle_or_grid<IsConst>::type_t::vehicle ) {
            const vehicle &current_veh = *current.veh;
            for( auto &p : current_veh.loose_parts ) {
                if( !current_veh.part_info( p ).has_flag( "POWER_TRANSFER" ) ) {
                    // Ignore loose parts that aren't power transfer cables
                    continue;
                }
                const tripoint_abs_ms target_pos( current_veh.cpart( p ).target.second );
                if( current_veh.cpart( p ).has_flag( vehicle_part::targets_grid ) ) {
                    if( process_grid( target_pos ) == tvr::stop ) {
                        return;
                    }
                } else {
                    if( process_vehicle( target_pos ) == tvr::stop ) {
                        return;
                    }
                }
            }
        } else {
            // Grids can only be connected to vehicles at the moment
            auto &current_grid = *current.grid;
            for( auto &p : current_grid.get_contents() ) {
                const vehicle_connector_tile *connector = active_tiles::furn_at<vehicle_connector_tile>( p );
                if( connector == nullptr ) {
                    continue;
                }
                for( const tripoint_abs_ms &target_pos : connector->connected_vehicles ) {
                    if( process_vehicle( target_pos ) == tvr::stop ) {
                        return;
                    }
                }
            }
        }
    }
}
References vehicle_connector_tile::connected_vehicles, vehicle::cpart(), debugmsg, vehicle::find_vehicle(), active_tiles::furn_at< vehicle_connector_tile >(), g, get_distribution_grid_tracker(), distribution_graph::vehicle_or_grid< IsConst, Vehicle, Grid >::grid, vehicle_part::has_flag(), vpart_info::has_flag(), vehicle::loose_parts, m_debug, vehicle::part_info(), vehicle_part::target, vehicle_part::targets_grid, distribution_graph::vehicle_or_grid< IsConst, Vehicle, Grid >::type, and distribution_graph::vehicle_or_grid< IsConst, Vehicle, Grid >::veh.
Referenced by vehicle::charge_battery(), vehicle::discharge_battery(), vehicle::enumerate_vehicles(), vehicle::fuel_left(), and vehicle::gain_moves().