Cataclysm BN: vehicle_movement Namespace Reference
vehicle_movement Namespace Reference
Classes
struct rail_processing_result
Functions
static bool scan_rails_from_veh_internal (const map &m, const vehicle &veh, tripoint scan_initial_pos, point veh_plus_y_vec, point scan_vec)
static int get_num_cw_rots_of_ray_delta (const point &v)
static bool scan_rails_at_shift (const map &m, const vehicle &veh, int velocity_sign, units::angle dir, int shift_sign, tripoint *shift_amt=nullptr)
static rail_processing_result make_none ()
static rail_processing_result make_turn (units::angle a)
static rail_processing_result make_shift (tripoint dp)
rail_processing_result process_movement_on_rails (const map &m, const vehicle &veh)
Decides how the vehicle should move in order to follow rails, or get on rails.
bool is_on_rails (const map &m, const vehicle &veh)
Returns whether the vehicle is currently on rails.
Function Documentation
get_num_cw_rots_of_ray_delta()
static int vehicle_movement::get_num_cw_rots_of_ray_delta (const point & v) inline static
Definition at line 1754 of file vehicle_move.cpp.
{
    if( v == point_north_east ) {
        return 0;
    } else if( v == point_south_east ) {
        return 1;
    } else if( v == point_south_west ) {
        return 2;
    } else {
        return 3;
    }
}
References point_north_east, point_south_east, and point_south_west.
Referenced by scan_rails_at_shift().
is_on_rails()
bool vehicle_movement::is_on_rails (const map & m, const vehicle & veh)
Returns whether the vehicle is currently on rails.
Definition at line 1930 of file vehicle_move.cpp.
{
    if( !veh.can_use_rails() ) {
        // Must be rail-worthy
        return false;
    }
    int face_dir_degrees = std::round( units::to_degrees( veh.face.dir() ) );
    int face_dir_snapped = ( face_dir_degrees / 45 ) * 45;
    if( face_dir_degrees != face_dir_snapped ) {
        // When moving on rails, can only rotate in 45-degree increment
        return false;
    }
    // Must have valid rail segment in front of or behind us
    units::angle dir_straight = normalize( units::from_degrees( face_dir_snapped ) );
    return scan_rails_at_shift( m, veh, 1, dir_straight, 0 ) ||
           scan_rails_at_shift( m, veh, -1, dir_straight, 0 );
}
References vehicle::can_use_rails(), tileray::dir(), vehicle::face, units::from_degrees(), character_funcs::normalize(), scan_rails_at_shift(), and units::to_degrees().
Referenced by vehicle::act_on_map(), handbrake(), process_movement_on_rails(), vehicle::slowdown(), and map::vehicle_wheel_traction().
make_none()
static rail_processing_result vehicle_movement::make_none () inline static
Definition at line 1827 of file vehicle_move.cpp.
{
    return rail_processing_result();
}
Referenced by process_movement_on_rails().
make_shift()
static rail_processing_result vehicle_movement::make_shift (tripoint dp) inline static
Definition at line 1840 of file vehicle_move.cpp.
{
    rail_processing_result res;
    res.do_shift = true;
    res.shift_amount = dp;
    return res;
}
References vehicle_movement::rail_processing_result::do_shift, and vehicle_movement::rail_processing_result::shift_amount.
Referenced by process_movement_on_rails().
make_turn()
static rail_processing_result vehicle_movement::make_turn (units::angle a) inline static
Definition at line 1832 of file vehicle_move.cpp.
{
    rail_processing_result res;
    res.do_turn = true;
    res.turn_dir = a;
    return res;
}
References a, vehicle_movement::rail_processing_result::do_turn, and vehicle_movement::rail_processing_result::turn_dir.
Referenced by process_movement_on_rails().
process_movement_on_rails()
rail_processing_result vehicle_movement::process_movement_on_rails (const map & m, const vehicle & veh)
Decides how the vehicle should move in order to follow rails, or get on rails.
Definition at line 1848 of file vehicle_move.cpp.
{
    int face_dir_degrees = std::round( units::to_degrees( veh.face.dir() ) );
    int face_dir_snapped = ( face_dir_degrees / 45 ) * 45;
    units::angle dir_straight = normalize( units::from_degrees( face_dir_snapped ) );
    units::angle dir_left = normalize( dir_straight - 45_degrees );
    units::angle dir_right = normalize( dir_straight + 45_degrees );
    int vel_sign = veh.velocity > 0 ? 1 : -1;
    bool can_go_straight = scan_rails_at_shift( m, veh, vel_sign, dir_straight, 0 );
    bool can_turn_left = scan_rails_at_shift( m, veh, vel_sign, dir_left, 0 );
    bool can_turn_right = scan_rails_at_shift( m, veh, vel_sign, dir_right, 0 );
    bool can_go_backwards = scan_rails_at_shift( m, veh, -vel_sign, dir_straight, 0 );
    tripoint shift_amount_right;
    tripoint shift_amount_left;
    bool can_shift_right = scan_rails_at_shift( m, veh, vel_sign, dir_straight, vel_sign,
                           &shift_amount_right );
    bool can_shift_left = scan_rails_at_shift( m, veh, vel_sign, dir_straight, -vel_sign,
                          &shift_amount_left );
    bool is_on_rails = face_dir_degrees == face_dir_snapped && ( can_go_straight || can_go_backwards );
    // Appraise possible vehicle orientations
    if( !is_on_rails ) {
        // The vehicle is derailed, attempt to get back on rails
        if( can_go_straight ) {
            return make_turn( dir_straight );
        }
    } else {
        if( veh.face.dir() == veh.turn_dir ) {
            // Automatic movement - prefer going straight.
            if( can_go_straight ) {
                return make_none();
            } else if( can_turn_left ) {
                return make_turn( dir_left );
            } else if( can_shift_left ) {
                return make_shift( shift_amount_left );
            } else if( can_turn_right ) {
                return make_turn( dir_right );
            } else if( can_shift_right ) {
                return make_shift( shift_amount_right );
            }
        } else {
            // Manual movement - prefer going in turn direction.
            units::angle dir_delta = normalize( veh.turn_dir - veh.face.dir() );
            if( dir_delta < 180_degrees ) {
                // Trying to turn right
                if( can_turn_right ) {
                    return make_turn( dir_right );
                } else if( can_shift_right ) {
                    return make_shift( shift_amount_right );
                } else if( can_go_straight ) {
                    return make_none();
                } else if( can_turn_left ) {
                    return make_turn( dir_left );
                } else if( can_shift_left ) {
                    return make_shift( shift_amount_left );
                }
            } else {
                // Trying to turn left
                if( can_turn_left ) {
                    return make_turn( dir_left );
                } else if( can_shift_left ) {
                    return make_shift( shift_amount_left );
                } else if( can_go_straight ) {
                    return make_none();
                } else if( can_turn_right ) {
                    return make_turn( dir_right );
                } else if( can_shift_right ) {
                    return make_shift( shift_amount_right );
                }
            }
        }
    }
    return make_none();
}
References tileray::dir(), vehicle::face, units::from_degrees(), is_on_rails(), make_none(), make_shift(), make_turn(), character_funcs::normalize(), scan_rails_at_shift(), units::to_degrees(), vehicle::turn_dir, and vehicle::velocity.
Referenced by vehicle::act_on_map().
scan_rails_at_shift()
static bool vehicle_movement::scan_rails_at_shift (const map & m, const vehicle & veh, int velocity_sign, units::angle dir, int shift_sign, tripoint * shift_amt = nullptr) static
Definition at line 1767 of file vehicle_move.cpp.
{
    point ray_delta;
    {
        tileray ray( dir );
        ray.advance( 1 );
        ray_delta.x = ray.dx();
        ray_delta.y = ray.dy();
    }
    if( ray_delta.x != 0 && ray_delta.y != 0 ) {
        // We can't cleanly map diagonally oriented vehicles to rail turns.
        // As such, treat the vehicle as if it can have either skew at the same time.
        int num_cw_rots = get_num_cw_rots_of_ray_delta( ray_delta );
        point rd_l = point_north.rotate( num_cw_rots );
        point rd_r = point_east.rotate( num_cw_rots );
        point vyp_l = point_east.rotate( num_cw_rots );
        point vyp_r = point_south.rotate( num_cw_rots );
        tripoint scan_start = veh.global_pos3();
        if( shift_sign > 0 ) {
            scan_start += rd_r * velocity_sign;
        } else if( shift_sign < 0 ) {
            scan_start += rd_l * velocity_sign;
        }
        point scan_vec = ray_delta * velocity_sign;
        bool scan_res_l = scan_rails_from_veh_internal( m, veh, scan_start, vyp_l, scan_vec );
        bool scan_res_r = scan_rails_from_veh_internal( m, veh, scan_start, vyp_r, scan_vec );
        if( scan_res_l || scan_res_r ) {
            if( shift_amt ) {
                *shift_amt = scan_start - veh.global_pos3();
            }
            return true;
        }
    } else {
        point veh_plus_y_vec = ray_delta.rotate( 1 );
        point scan_vec = ray_delta * velocity_sign;
        tripoint scan_start = veh.global_pos3();
        if( shift_sign != 0 ) {
            scan_start += scan_vec + veh_plus_y_vec * shift_sign;
        }
        if( scan_rails_from_veh_internal( m, veh, scan_start, veh_plus_y_vec, scan_vec ) ) {
            if( shift_amt ) {
                *shift_amt = scan_start - veh.global_pos3();
            }
            return true;
        }
    }
    return false;
}
References tileray::advance(), tileray::dx(), tileray::dy(), get_num_cw_rots_of_ray_delta(), vehicle::global_pos3(), point_east, point_north, point_south, point::rotate(), scan_rails_from_veh_internal(), point::x, and point::y.
Referenced by is_on_rails(), and process_movement_on_rails().
scan_rails_from_veh_internal()
static bool vehicle_movement::scan_rails_from_veh_internal (const map & m, const vehicle & veh, tripoint scan_initial_pos, point veh_plus_y_vec, point scan_vec) static
Definition at line 1731 of file vehicle_move.cpp.
{
    for( size_t rail_id = 0; rail_id < veh.rail_profile.size(); rail_id++ ) {
        int rail_y_rel_to_pivot = veh.rail_profile[rail_id] - veh.pivot_point().y;
        tripoint scan_pos = scan_initial_pos + rail_y_rel_to_pivot * veh_plus_y_vec;
        for( int step = 0; step < 3; step++ ) {
            tripoint p = scan_pos + scan_vec * step;
            bool rail_here = m.has_flag_ter_or_furn( TFLAG_RAIL, p );
            if( !rail_here ) {
                // Terrain is not a rail
                return false;
            }
        }
    }
    return true;
}
References map::has_flag_ter_or_furn(), vehicle::pivot_point(), vehicle::rail_profile, TFLAG_RAIL, and point::y.
Referenced by scan_rails_at_shift().