Cataclysm BN: ui_manager Namespace Reference
ui_manager Namespace Reference
Functions
void invalidate (const rectangle< point > &rect, bool reenable_uis_below)
Invalidate a portion of the screen when a UI is resized, closed, etc.
void redraw ()
Invalidate the top window and redraw all invalidated windows.
void redraw_invalidated ()
Redraw all invalidated windows without invalidating the top window.
void screen_resized ()
Handle resize of the game window.
Function Documentation
invalidate()
void ui_manager::invalidate (const rectangle< point > & rect, bool reenable_uis_below)
Invalidate a portion of the screen when a UI is resized, closed, etc.
Not supposed to be directly called by the user. rect is the pixel dimensions in tiles or console cell dimensions in curses
Definition at line 384 of file ui_manager.cpp.
{
    ui_adaptor::invalidate( rect, reenable_uis_below );
}
References ui_adaptor::invalidate().
Referenced by vehicle::do_towing_move(), ui_adaptor::position(), ui_adaptor::position_from_window(), and ui_adaptor::~ui_adaptor().
redraw()
void ui_manager::redraw ()
Invalidate the top window and redraw all invalidated windows.
Note that ui_manager may redraw multiple times when a ui_adaptor callback calls debugmsg, the game window is resized, or the system requests a redraw, so any data that may change after a resize or on each redraw should be calculated within the respective callbacks.
Definition at line 389 of file ui_manager.cpp.
{
    ui_adaptor::redraw();
}
References ui_adaptor::redraw().
Referenced by computer_session::action_emerg_ref_center(), debug_menu::benchmark(), game::cancel_activity_or_ignore_query(), defense_game::caravan(), choose_direction(), game_menus::inv::compare(), Character::conduct_blood_analysis(), debug_menu::debug(), debug_error_prompt(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), help::display_help(), input_context::display_menu(), game::display_scent(), veh_interact::do_install(), veh_interact::do_main_loop(), veh_interact::do_remove(), veh_interact::do_repair(), game::do_turn(), draw_item_info(), editmap::edit(), inventory_pick_selector::execute(), inventory_compare_selector::execute(), inventory_iuse_selector::execute(), inventory_drop_selector::execute(), game::extended_description(), game::handle_key_blocking_activity(), game::handle_mouseview(), anonymous_namespace{animation.cpp}::hit_animation(), defense_game::init_map(), uilist::inputfilter(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_missions(), game::list_monsters(), game::load(), main_menu::load_character_tab(), game::look_around(), worldfactory::make_new_world(), editmap::mapgen_retarget(), main_menu::new_character_tab(), main_menu::opening_screen(), dialogue::opt(), veh_interact::overview(), trading_window::perform_trade(), pickup::pick_up(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), player::power_bionics(), player::power_mutations_ui(), uilist::query(), computer_session::query_any(), query_popup::query_once(), string_editor_window::query_string(), string_input_popup::query_string(), computer_session::query_ynq(), game::quicksave(), throbber_popup::refresh(), robot_finds_kitten::robot_finds_kitten(), Messages::dialog::run(), target_ui::run(), examine_item_menu::run(), mapbuffer::save(), scrollable_text(), overmap_ui::search(), select_crafting_recipe(), editmap::select_shape(), set_description(), inventory_selector::set_filter(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), game::setup(), defense_game::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), loading_ui::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), game::start_game(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), game::unserialize_master(), computer_session::use(), iexamine::vending(), basecamp::worker_assignment_ui(), main_menu::world_tab(), and game::zones_manager().
redraw_invalidated()
void ui_manager::redraw_invalidated ()
Redraw all invalidated windows without invalidating the top window.
Definition at line 394 of file ui_manager.cpp.
{
    ui_adaptor::redraw_invalidated();
}
References ui_adaptor::redraw_invalidated().
Referenced by debug_menu::benchmark(), character_display::disp_info(), anonymous_namespace{animation.cpp}::basic_animation::draw(), game::fling_creature(), game::get_player_input(), map::move_vehicle(), mattack::ranged_pull(), diary::show_diary_ui(), and signal_handler().
screen_resized()
void ui_manager::screen_resized ()
Handle resize of the game window.
Not supposed to be directly called by the user.
Definition at line 399 of file ui_manager.cpp.
{
    ui_adaptor::screen_resized();
}
References ui_adaptor::screen_resized().
Referenced by catacurses::resizeterm().