Cataclysm BN: anonymous_namespace{mapdata.cpp} Namespace Reference
anonymous_namespace{mapdata.cpp} Namespace Reference
Functions
bool is_json_check_strict (const std::string &src)
Variables
const units::volume DEFAULT_MAX_VOLUME_IN_SQUARE = units::from_liter(1000)
generic_factory< ter_t > terrain_data ("terrain")
generic_factory< furn_t > furniture_data ("furniture")
Function Documentation
is_json_check_strict()
bool anonymous_namespace{mapdata.cpp}::is_json_check_strict (const std::string & src)
Definition at line 44 of file mapdata.cpp.
{
    return json_report_strict || is_strict_enabled( src );
}
References is_strict_enabled(), and json_report_strict.
Referenced by ter_t::load().
Variable Documentation
DEFAULT_MAX_VOLUME_IN_SQUARE
const units::volume anonymous_namespace{mapdata.cpp}::DEFAULT_MAX_VOLUME_IN_SQUARE = units::from_liter(1000)
Definition at line 39 of file mapdata.cpp.
Referenced by furn_t::load().
furniture_data
generic_factory< furn_t > anonymous_namespace{mapdata.cpp}::furniture_data("furniture") ("furniture")
Referenced by check_furniture_and_terrain(), furn_t::count(), finalize_furn(), furn_t::get_all(), string_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), load_furniture(), int_id< T >::obj(), string_id< T >::obj(), and reset_furn_ter().
terrain_data
generic_factory< ter_t > anonymous_namespace{mapdata.cpp}::terrain_data("terrain") ("terrain")
Referenced by check_furniture_and_terrain(), ter_t::count(), ter_t::get_all(), int_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), load_terrain(), int_id< T >::obj(), string_id< T >::obj(), reset_furn_ter(), and set_ter_ids().