Cataclysm BN: construction_sequences Namespace Reference
construction_sequences Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void reset ()
static bool is_valid_first_step (const construction &c)
static bool has_valid_result (const construction &c)
static bool has_valid_category (const construction &c)
void finalize ()
void check_consistency ()
const construction_sequence * lookup_sequence (const ter_str_id &id)
const construction_sequence * lookup_sequence (const furn_str_id &id)
Function Documentation
check_consistency()
void construction_sequences::check_consistency ()
Definition at line 247 of file construction_sequence.cpp.
{
    for( const construction_sequence &seq : all_sequences.get_all() ) {
        seq.check();
    }
}
References anonymous_namespace{construction_sequence.cpp}::all_sequences.
finalize()
void construction_sequences::finalize ()
Definition at line 82 of file construction_sequence.cpp.
{
    all_sequences.finalize();
    // Validate explicit sequences
    for( const construction_sequence &seq : all_sequences.get_all() ) {
        if( seq.blacklisted ) {
            continue;
        }
        if( !seq.post_furniture.is_empty() && !seq.post_furniture.is_valid() ) {
            debugmsg( R"(Construction sequence "%s" defines invalid post_furniture "%s".)",
                      seq.id, seq.post_furniture );
            continue;
        }
        if( !seq.post_terrain.is_empty() && !seq.post_terrain.is_valid() ) {
            debugmsg( R"(Construction sequence "%s" defines invalid post_terrain "%s".)",
                      seq.id, seq.post_terrain );
            continue;
        }
        if( seq.post_furniture.is_empty() == seq.post_terrain.is_empty() ) {
            debugmsg( R"(Construction sequence "%s" must define post_furniture OR post_terrain.)",
                      seq.id );
            continue;
        }
        if( !seq.elems.empty() ) {
            bool constr_ok = true;
            for( const construction_str_id &c_id : seq.elems ) {
                if( !c_id.is_valid() ) {
                    debugmsg( R"(Construction sequence "%s" contains invalid construction id "%s".)",
                              seq.id, c_id );
                    constr_ok = false;
                    break;
                }
                if( c_id->is_blacklisted() ) {
                    debugmsg( R"(Construction sequence "%s" contains blacklisted construction id "%s".)",
                              seq.id, c_id );
                    constr_ok = false;
                    break;
                }
                if( !has_valid_category( *c_id ) ) {
                    debugmsg( R"(Construction sequence "%s" should no contain constructions from REPAIR category ("%s").)",
                              seq.id, c_id );
                    constr_ok = false;
                    break;
                }
                if( !has_valid_result( *c_id ) ) {
                    debugmsg( R"(In construction sequence "%s" step "%s" produces no furniture or terrain.)",
                              seq.id, c_id
                            );
                    constr_ok = false;
                    break;
                }
            }
            if( !constr_ok ) {
                continue;
            }
            const construction &first = *seq.elems.front();
            if( !is_valid_first_step( first ) ) {
                debugmsg( R"(First entry "%s" in construction sequence "%s" )"
                          R"(must have t_dirt as valid prerequisite.)",
                          first.id, seq.id );
                continue;
            }
            const construction &last = *seq.elems.back();
            if( last.post_terrain != seq.post_terrain || last.post_furniture != seq.post_furniture ) {
                debugmsg( R"(Last entry "%s" in construction sequence "%s" )"
                          R"(must produce terrain or furniture specified by the sequence.)",
                          last.id, seq.id );
            }
            for( size_t i = 1; i < seq.elems.size(); i++ ) {
                const construction &c1 = *seq.elems[i - 1];
                const construction &c2 = *seq.elems[i];
                if( c1.post_furniture != c2.pre_furniture ) {
                    debugmsg( R"(In construction sequence "%s" post_furniture and pre_furniture )"
                              R"(don't match when going from "%s" to "%s".)",
                              seq.id, c1.id, c2.id
                            );
                    constr_ok = false;
                    break;
                }
                if( c1.post_terrain != c2.pre_terrain ) {
                    debugmsg( R"(In construction sequence "%s" post_terrain and pre_terrain )"
                              R"(don't match when going from "%s" to "%s".)",
                              seq.id, c1.id, c2.id
                            );
                    constr_ok = false;
                    break;
                }
            }
            if( !constr_ok ) {
                continue;
            }
        }
        cata::optional<construction_sequence_id> conflict_id;
        if( !seq.post_terrain.is_empty() ) {
            auto res = sequences_for_ter.emplace( seq.post_terrain, seq.id.id() );
            if( !res.second ) {
                conflict_id = res.first->second.id();
            }
        } else {
            auto res = sequences_for_furn.emplace( seq.post_furniture, seq.id.id() );
            if( !res.second ) {
                conflict_id = res.first->second.id();
            }
        }
        if( conflict_id ) {
            debugmsg( R"(Construction sequence "%s" defines same result as another existing sequence "%s".)",
                      seq.id, *conflict_id
                    );
        }
    }
    // Generate auto 1-element sequences
    std::map<ter_str_id, std::vector<construction_sequence>> ter_map;
    std::map<furn_str_id, std::vector<construction_sequence>> furn_map;
    for( const construction_id &c_id : constructions::get_all_sorted() ) {
        const construction &c = *c_id;
        if( !is_valid_first_step( c ) || !has_valid_result( c ) || !has_valid_category( c ) ) {
            // Recipe must be a valid first construction step to be turned into sequence
            continue;
        }
        std::vector<construction_sequence> *seq_vec = nullptr;
        if( !c.post_terrain.is_empty() ) {
            auto it = ter_map.emplace( c.post_terrain, std::vector<construction_sequence>() );
            seq_vec = &it.first->second;
        } else {
            auto it = furn_map.emplace( c.post_furniture, std::vector<construction_sequence>() );
            seq_vec = &it.first->second;
        }
        construction_sequence seq;
        seq.was_loaded = true;
        seq.id = construction_sequence_id( "#auto#_" + c.id.str() );
        seq.elems.push_back( c.id );
        seq_vec->push_back( seq );
    }
    for( const auto &it : ter_map ) {
        if( it.second.size() != 1 ) {
            // Don't autogenerate sequence if multiple constructions
            // can be turned into a sequence, let user solve conflict.
            continue;
        }
        // Don't autogenerate sequence if there is already an explicitly defined sequence
        if( lookup_sequence( it.first ) ) {
            continue;
        }
        const construction_sequence &ref = all_sequences.insert( it.second.front() );
        sequences_for_ter.emplace( it.first, ref.id.id() );
    }
    for( const auto &it : furn_map ) {
        if( it.second.size() != 1 ) {
            // Don't autogenerate sequence if multiple constructions
            // can be turned into a sequence, let user solve conflict.
            continue;
        }
        // Don't autogenerate sequence if there is already an explicitly defined sequence
        if( lookup_sequence( it.first ) ) {
            continue;
        }
        const construction_sequence &ref = all_sequences.insert( it.second.front() );
        sequences_for_furn.emplace( it.first, ref.id.id() );
    }
}
References anonymous_namespace{construction_sequence.cpp}::all_sequences, c, debugmsg, construction_sequence::elems, constructions::get_all_sorted(), has_valid_category(), has_valid_result(), construction::id, construction_sequence::id, string_id< T >::id(), construction::is_blacklisted(), string_id< T >::is_valid(), is_valid_first_step(), last, lookup_sequence(), construction::post_furniture, construction::post_terrain, construction::pre_furniture, construction::pre_terrain, anonymous_namespace{construction_sequence.cpp}::sequences_for_furn, anonymous_namespace{construction_sequence.cpp}::sequences_for_ter, and construction_sequence::was_loaded.
Referenced by DynamicDataLoader::finalize_loaded_data().
has_valid_category()
static bool construction_sequences::has_valid_category (const construction & c) static
Definition at line 76 of file construction_sequence.cpp.
{
    static const construction_category_id construction_category_REPAIR( "REPAIR" );
    return c.category != construction_category_REPAIR;
}
References c.
Referenced by finalize().
has_valid_result()
static bool construction_sequences::has_valid_result (const construction & c) static
Definition at line 71 of file construction_sequence.cpp.
{
    return !c.post_furniture.is_empty() || !c.post_terrain.is_empty();
}
References c.
Referenced by finalize().
is_valid_first_step()
static bool construction_sequences::is_valid_first_step (const construction & c) static
Definition at line 59 of file construction_sequence.cpp.
{
    static const ter_str_id t_dirt( "t_dirt" );
    return ( c.pre_terrain.is_empty() || c.pre_terrain == t_dirt ) &&
           c.pre_furniture.is_empty() &&
           c.pre_special_is_valid_for_dirt &&
    std::all_of( c.pre_flags.begin(), c.pre_flags.end(), []( const std::string & flag ) {
        return t_dirt->has_flag( flag );
    } );
}
References c, and t_dirt.
Referenced by finalize().
load()
void construction_sequences::load (const JsonObject & jo, const std::string & src)
Definition at line 47 of file construction_sequence.cpp.
{
    all_sequences.load( jo, src );
}
References anonymous_namespace{construction_sequence.cpp}::all_sequences.
Referenced by DynamicDataLoader::initialize().
lookup_sequence() [1/2]
const construction_sequence * construction_sequences::lookup_sequence (const furn_str_id & id)
Definition at line 260 of file construction_sequence.cpp.
{
    auto it = sequences_for_furn.find( id );
    return it == sequences_for_furn.end() ? nullptr : &*it->second;
}
References anonymous_namespace{construction_sequence.cpp}::sequences_for_furn.
lookup_sequence() [2/2]
const construction_sequence * construction_sequences::lookup_sequence (const ter_str_id & id)
Definition at line 254 of file construction_sequence.cpp.
{
    auto it = sequences_for_ter.find( id );
    return it == sequences_for_ter.end() ? nullptr : &*it->second;
}
References anonymous_namespace{construction_sequence.cpp}::sequences_for_ter.
Referenced by finalize(), and get_build_reqs_for_furn_ter_ids().
reset()
void construction_sequences::reset ()
Definition at line 52 of file construction_sequence.cpp.
{
    all_sequences.reset();
    sequences_for_ter.clear();
    sequences_for_furn.clear();
}
References anonymous_namespace{construction_sequence.cpp}::all_sequences, anonymous_namespace{construction_sequence.cpp}::sequences_for_furn, and anonymous_namespace{construction_sequence.cpp}::sequences_for_ter.
Referenced by DynamicDataLoader::unload_data().