Cataclysm BN: anonymous_namespace{filesystem.cpp} Namespace Reference
anonymous_namespace{filesystem.cpp} Namespace Reference
Functions
template<typename T , size_t N>
size_t sizeof_array (T const(&)[N]) noexcept
template<typename Function >
void for_each_dir_entry (const std::string &path, Function function)
std::string resolve_path (const std::string &full_path)
bool is_directory_stat (const std::string &full_path)
bool is_directory (const dirent &entry, const std::string &full_path)
bool is_special_dir (const dirent &entry)
bool name_contains (const dirent &entry, const std::string &match, const bool at_end)
template<typename Predicate >
std::vector< std::string > find_file_if_bfs (const std::string &root_path, const bool recursive_search, Predicate predicate)
Function Documentation
find_file_if_bfs()
template<typename Predicate > std::vector< std::string > anonymous_namespace{filesystem.cpp}::find_file_if_bfs (const std::string & root_path, const bool recursive_search, Predicate predicate)
Definition at line 301 of file filesystem.cpp.
{
    std::deque<std::string>  directories;
    if( root_path.empty() ) {
        directories.emplace_back( "./" );
    } else if( string_ends_with( root_path, "/" ) ) {
        directories.emplace_back( root_path );
    } else {
        directories.emplace_back( root_path + "/" );
    }
    std::vector<std::string> results;
    if( !dir_exist( *directories.begin() ) ) {
        return results;
    }
    while( !directories.empty() ) {
        const auto path = std::move( directories.front() );
        directories.pop_front();
        const auto n_dirs    = static_cast<std::ptrdiff_t>( directories.size() );
        const auto n_results = static_cast<std::ptrdiff_t>( results.size() );
        for_each_dir_entry( path, [&]( const dirent & entry ) {
            // exclude special directories.
            if( is_special_dir( entry ) ) {
                return;
            }
            const auto full_path = path + entry.d_name;
            // don't add files ending in '~'.
            if( full_path.back() == '~' ) {
                return;
            }
            // add sub directories to recursive_search if requested
            const auto is_dir = is_directory( entry, full_path );
            if( recursive_search && is_dir ) {
                directories.emplace_back( full_path + "/" );
            }
            // check the file
            if( !predicate( entry, is_dir ) ) {
                return;
            }
            results.emplace_back( full_path );
        } );
        // Keep files and directories to recurse ordered consistently
        // by sorting from the old end to the new end.
        // NOLINTNEXTLINE(cata-use-localized-sorting)
        std::sort( std::begin( directories ) + n_dirs,    std::end( directories ) );
        // NOLINTNEXTLINE(cata-use-localized-sorting)
        std::sort( std::begin( results )     + n_results, std::end( results ) );
    }
    return results;
}
References dirent::d_name, dir_exist(), for_each_dir_entry(), is_directory(), is_special_dir(), avatar_action::move(), and string_ends_with().
Referenced by get_directories_with(), and get_files_from_path().
for_each_dir_entry()
template<typename Function > void anonymous_namespace{filesystem.cpp}::for_each_dir_entry (const std::string & path, Function function)
Definition at line 160 of file filesystem.cpp.
{
    using dir_ptr = DIR*;
    if( path.empty() ) {
        return;
    }
    const dir_ptr root = opendir( path.c_str() );
    if( !root ) {
        const auto e_str = strerror( errno );
        dbg( DL::Warn ) << "opendir [" << path << "] failed with \"" << e_str << "\".";
        return;
    }
    while( const auto entry = readdir( root ) ) {
        function( *entry );
    }
    closedir( root );
}
References closedir(), dbg, opendir(), readdir(), and Warn.
Referenced by find_file_if_bfs().
is_directory()
bool anonymous_namespace{filesystem.cpp}::is_directory (const dirent & entry, const std::string & full_path)
Definition at line 242 of file filesystem.cpp.
{
    if( entry.d_type == DT_DIR ) {
        return true;
    }
#if !defined(_WIN32)
    if( entry.d_type == DT_LNK ) {
        return is_directory_stat( resolve_path( full_path ) );
    }
#endif
    if( entry.d_type == DT_UNKNOWN ) {
        return is_directory_stat( full_path );
    }
    return false;
}
References dirent::d_type, DT_DIR, DT_LNK, DT_UNKNOWN, is_directory_stat(), and resolve_path().
Referenced by find_file_if_bfs().
is_directory_stat()
bool anonymous_namespace{filesystem.cpp}::is_directory_stat (const std::string & full_path)
Definition at line 199 of file filesystem.cpp.
{
    if( full_path.empty() ) {
        return false;
    }
#if defined(_WIN32)
    struct _stat result;
    int stat_ret = _wstat( utf8_to_wstr( full_path ).c_str(), &result );
#else
    struct stat result;
    int stat_ret = stat( full_path.c_str(), &result );
#endif
    if( stat_ret != 0 ) {
        const auto e_str = strerror( errno );
        dbg( DL::Warn ) << "stat [" << full_path << "] failed with \"" << e_str << "\".";
        return false;
    }
    if( S_ISDIR( result.st_mode ) ) {
        // NOLINTNEXTLINE(readability-simplify-boolean-expr)
        return true;
    }
#if !defined(_WIN32)
    if( S_ISLNK( result.st_mode ) ) {
        return is_directory_stat( resolve_path( full_path ) );
    }
#endif
    return false;
}
References dbg, is_directory_stat(), resolve_path(), S_ISDIR, S_ISLNK, utf8_to_wstr(), and Warn.
Referenced by is_directory(), and is_directory_stat().
is_special_dir()
bool anonymous_namespace{filesystem.cpp}::is_special_dir (const dirent & entry)
Definition at line 265 of file filesystem.cpp.
{
    return !strncmp( entry.d_name, ".",  sizeof( entry.d_name ) - 1 ) ||
           !strncmp( entry.d_name, "..", sizeof( entry.d_name ) - 1 );
}
References dirent::d_name.
Referenced by find_file_if_bfs().
name_contains()
bool anonymous_namespace{filesystem.cpp}::name_contains (const dirent & entry, const std::string & match, const bool at_end)
Definition at line 275 of file filesystem.cpp.
{
    const size_t len_fname = strlen( entry.d_name );
    const size_t len_match = match.length();
    if( len_match > len_fname ) {
        return false;
    }
    const size_t offset = at_end ? ( len_fname - len_match ) : 0;
    return strstr( entry.d_name + offset, match.c_str() ) != nullptr;
}
References dirent::d_name.
Referenced by get_directories_with(), and get_files_from_path().
resolve_path()
std::string anonymous_namespace{filesystem.cpp}::resolve_path (const std::string & full_path)
Definition at line 183 of file filesystem.cpp.
{
    const auto result_str = realpath( full_path.c_str(), nullptr );
    if( !result_str ) {
        const auto e_str = strerror( errno );
        dbg( DL::Warn ) << "realpath [" << full_path << "] failed with \"" << e_str << "\".";
        return {};
    }
    std::string result( result_str );
    free( result_str );
    return result;
}
References dbg, and Warn.
Referenced by is_directory(), and is_directory_stat().
sizeof_array()
template<typename T , size_t N> size_t anonymous_namespace{filesystem.cpp}::sizeof_array (T const (&)[N]) inline noexcept
Definition at line 151 of file filesystem.cpp.
{
    return N;
}