Cataclysm BN: iexamine Namespace Reference
iexamine Namespace Reference
Functions
void egg_sack_generic (player &p, const tripoint &examp, const mtype_id &montype)
Spawn spiders from a spider egg sack in radius 1 around the egg sack.
void none (player &p, const tripoint &examp)
Nothing player can interact with here.
void gaspump (player &p, const tripoint &examp)
Use "gas pump." Will pump any liquids on tile.
void atm (player &p, const tripoint &examp)
launches the atm menu class which then handles all the atm interactions.
void vending (player &p, const tripoint &examp)
Generates vending machine UI and allows players to purchase contained items with a cash card.
void toilet (player &p, const tripoint &examp)
If there's water, allow its usage but add chance of poison.
void elevator (player &p, const tripoint &examp)
If underground, move 2 levels up else move 2 levels down.
void nanofab (player &p, const tripoint &examp)
UI FOR LAB_FINALE NANO FABRICATOR.
void controls_gate (player &p, const tripoint &examp)
Open or close gate.
void cardreader (player &p, const tripoint &examp)
Use id/hack reader.
void cardreader_robofac (player &p, const tripoint &examp)
void cardreader_foodplace (player &p, const tripoint &examp)
void intercom (player &p, const tripoint &examp)
void cvdmachine (player &p, const tripoint &examp)
Pick an appropriate item and apply diamond coating if possible.
void rubble (player &p, const tripoint &examp)
Prompt removal of rubble.
void chainfence (player &p, const tripoint &examp)
Prompt climbing over fence.
void bars (player &p, const tripoint &examp)
If player has amorphous trait, slip through the bars.
void deployed_furniture (player &p, const tripoint &pos)
void portable_structure (player &p, const tripoint &examp)
Determine structure's type and prompts its removal.
void pit (player &p, const tripoint &examp)
If there is a 2x4 around, prompt placing it across pit.
void pit_covered (player &p, const tripoint &examp)
Prompt removing the 2x4 placed across the pit.
void slot_machine (player &p, const tripoint &examp)
Loop prompt to bet $10.
void safe (player &p, const tripoint &examp)
Attempt to crack safe through audio-feedback manual lock manipulation.
void gunsafe_el (player &p, const tripoint &examp)
Attempt to "hack" the gunsafe's electronic lock and open it.
void harvest_furn_nectar (player &p, const tripoint &examp)
void harvest_furn (player &p, const tripoint &examp)
void harvest_ter_nectar (player &p, const tripoint &examp)
void harvest_ter (player &p, const tripoint &examp)
void harvested_plant (player &p, const tripoint &examp)
Only harvest a plant once per season.
void locked_object (player &p, const tripoint &examp)
Checks whether PC has a crowbar then calls iuse.crowbar.
void locked_object_pickable (player &p, const tripoint &examp)
Checks whether PC has picklocks then calls pick_lock_actor.
void bulletin_board (player &p, const tripoint &examp)
void fault (player &p, const tripoint &examp)
Display popup with reference to "The Enigma of Amigara Fault.".
void notify (player &p, const tripoint &pos)
Display popup message pulled from the object's message property.
void transform (player &p, const tripoint &pos)
Transform the examined object into the object specified by its transforms_into property.
void pedestal_wyrm (player &p, const tripoint &examp)
Spawn 1d4 wyrms and sink pedestal into ground.
void pedestal_temple (player &p, const tripoint &examp)
Put petrified eye on pedestal causing it to sink into ground and open temple.
void door_peephole (player &p, const tripoint &examp)
Unlock/open door or attempt to peek through peephole.
void fswitch (player &p, const tripoint &examp)
void flower_tulip (player &p, const tripoint &examp)
void flower_spurge (player &p, const tripoint &examp)
void flower_poppy (player &p, const tripoint &examp)
Prompt pick (or drink nectar if able) poppy bud.
void flower_cactus (player &p, const tripoint &examp)
Prompt pick cactus pad.
void flower_bluebell (player &p, const tripoint &examp)
void flower_dahlia (player &p, const tripoint &examp)
Dig up its roots or drink its nectar if you can.
void flower_marloss (player &p, const tripoint &examp)
void egg_sackbw (player &p, const tripoint &examp)
void egg_sackcs (player &p, const tripoint &examp)
void egg_sackws (player &p, const tripoint &examp)
void fungus (player &p, const tripoint &examp)
Remove furniture.
void dirtmound (player &p, const tripoint &examp)
If it's warm enough, pick one of the player's seeds and plant it.
void aggie_plant (player &p, const tripoint &examp)
void tree_hickory (player &p, const tripoint &examp)
void tree_maple (player &p, const tripoint &examp)
void tree_maple_tapped (player &p, const tripoint &examp)
void shrub_marloss (player &p, const tripoint &examp)
void tree_marloss (player &p, const tripoint &examp)
void shrub_wildveggies (player &p, const tripoint &examp)
void recycle_compactor (player &p, const tripoint &examp)
void trap (player &p, const tripoint &examp)
void water_source (player &p, const tripoint &examp)
void clean_water_source (player &, const tripoint &examp)
void kiln_empty (player &p, const tripoint &examp)
void kiln_full (player &p, const tripoint &examp)
void arcfurnace_empty (player &p, const tripoint &examp)
void arcfurnace_full (player &p, const tripoint &examp)
void autoclave_empty (player &p, const tripoint &)
void autoclave_full (player &, const tripoint &examp)
void fireplace (player &p, const tripoint &examp)
void fvat_empty (player &p, const tripoint &examp)
void fvat_full (player &p, const tripoint &examp)
void keg (player &p, const tripoint &examp)
void reload_furniture (player &p, const tripoint &examp)
void use_furn_fake_item (player &p, const tripoint &examp)
void curtains (player &p, const tripoint &examp)
void sign (player &p, const tripoint &examp)
void pay_gas (player &p, const tripoint &examp)
void ledge (player &p, const tripoint &examp)
void autodoc (player &p, const tripoint &examp)
void translocator (player &p, const tripoint &examp)
void on_smoke_out (const tripoint &examp, const time_point &start_time)
void mill_finalize (player &, const tripoint &examp, const time_point &start_time)
void quern_examine (player &p, const tripoint &examp)
void smoker_options (player &p, const tripoint &examp)
void open_safe (player &p, const tripoint &examp)
void workbench (player &p, const tripoint &examp)
void dimensional_portal (player &p, const tripoint &examp)
void check_power (player &p, const tripoint &examp)
void migo_nerve_cluster (player &p, const tripoint &examp)
bool pour_into_keg (const tripoint &pos, item &liquid)
Pour liquid into a keg (furniture) on the map.
cata::optional< tripoint > getGasPumpByNumber (const tripoint &p, int number)
bool toPumpFuel (const tripoint &src, const tripoint &dst, int units)
cata::optional< tripoint > getNearFilledGasTank (const tripoint &center, int &gas_units)
bool has_keg (const tripoint &pos)
Check whether there is a keg on the map that can be filled via pour_into_keg.
std::list< item > get_harvest_items (const itype &type, int plant_count, int seed_count, bool byproducts)
Items that appear when a generic plant is harvested.
std::vector< seed_tuple > get_seed_entries (const std::vector< item * > &seed_inv)
Make lists of unique seed types and names for the menu(no multiple hemp seeds etc)
int query_seed (const std::vector< seed_tuple > &seed_entries)
Choose seed for planting.
void plant_seed (player &p, const tripoint &examp, const itype_id &seed_id)
Actual planting of selected seed.
void harvest_plant (player &p, const tripoint &examp, bool from_activity=false)
Actual harvesting of selected plant.
void fertilize_plant (player &p, const tripoint &tile, const itype_id &fertilizer)
itype_id choose_fertilizer (player &p, const std::string &pname, bool ask_player)
ret_val< bool > can_fertilize (player &p, const tripoint &tile, const itype_id &fertilizer)
void practice_survival_while_foraging (player *p)
Function Documentation
aggie_plant()
void iexamine::aggie_plant (player & p, const tripoint & examp)
Definition at line 2552 of file iexamine.cpp.
{
    map &here = get_map();
    // Can't use item_stack::only_item() since there might be fertilizer
    map_stack items = here.i_at( examp );
    const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
        return it.is_seed();
    } );
    if( seed == items.end() ) {
        debugmsg( "Missing seed for plant at (%d, %d, %d)", examp.x, examp.y, examp.z );
        here.i_clear( examp );
        here.furn_set( examp, f_null );
        return;
    }
    const std::string pname = seed->get_plant_name();
    if( here.has_flag_furn( flag_GROWTH_HARVEST, examp ) &&
        query_yn( _( "Harvest the %s?" ), pname ) ) {
        harvest_plant( p, examp );
    } else if( !here.has_flag_furn( flag_GROWTH_HARVEST, examp ) ) {
        if( here.i_at( examp ).size() > 1 ) {
            add_msg( m_info, _( "This %s has already been fertilized." ), pname );
            return;
        }
        itype_id fertilizer = choose_fertilizer( p, pname, true /*ask player for confirmation */ );
        if( !fertilizer.is_empty() ) {
            fertilize_plant( p, examp, fertilizer );
        }
    }
}
References _, add_msg(), item_stack::begin(), choose_fertilizer(), debugmsg, item_stack::end(), f_null, fertilize_plant(), flag_GROWTH_HARVEST(), map::furn_set(), get_map(), harvest_plant(), map::has_flag_furn(), map::i_at(), map::i_clear(), string_id< T >::is_empty(), m_info, query_yn(), iuse::seed(), item_stack::size(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by iexamine_function_from_string().
arcfurnace_empty()
void iexamine::arcfurnace_empty (player & p, const tripoint & examp)
Fabrication decreases loss when firing a furnace
Definition at line 2719 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_arcfurnace_type = here.furn( examp );
    furn_id next_arcfurnace_type = f_null;
    if( cur_arcfurnace_type == f_arcfurnace_empty ) {
        next_arcfurnace_type = f_arcfurnace_full;
    } else {
        debugmsg( "Examined furniture has action arcfurnace_empty, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    static const std::set<material_id> arcfurnaceable{ material_id( "cac2powder" ) };
    bool fuel_present = false;
    auto items = here.i_at( examp );
    for( const item &i : items ) {
        if( i.typeId() == itype_chem_carbide ) {
            add_msg( _( "This furnace already contains calcium carbide." ) );
            add_msg( _( "Remove it before activating the arc furnace again." ) );
            return;
        } else if( i.made_of_any( arcfurnaceable ) ) {
            fuel_present = true;
        } else {
            add_msg( m_bad, _( "This furnace contains %s, which can't be made into calcium carbide!" ),
                     i.tname( 1, false ) );
            return;
        }
    }
    if( !fuel_present ) {
        add_msg( _( "This furance is empty.  Fill it with powdered coke and lime mix, and try again." ) );
        return;
    }
    ///\EFFECT_FABRICATION decreases loss when firing a furnace
    const int skill = p.get_skill_level( skill_fabrication );
    int loss = 60 - 2 *
               skill; // Inefficency is still fine, coal and limestone is abundant
    // Burn stuff that should get charred, leave out the rest
    units::volume total_volume = 0_ml;
    for( const item &i : items ) {
        total_volume += i.volume();
    }
    units::volume char_volume = ( 100 - loss ) * total_volume / 100;
    int char_charges = itype_unfinished_cac2->charges_per_volume( char_volume );
    if( char_charges < 1 ) {
        add_msg( _( "The batch in this furance is too small to yield usable calcium carbide." ) );
        return;
    }
    //arc furnaces require a huge amount of current, so 1 full storage battery would work as a stand in
    if( !p.has_charges( itype_UPS, 1250 ) ) {
        add_msg( _( "This furnace is ready to be turned on, but you lack a UPS with sufficient power." ) );
        return;
    } else {
        add_msg( _( "This furnace contains %s %s of material, and is ready to be turned on." ),
                 format_volume( total_volume ), volume_units_abbr() );
        if( !query_yn( _( "Turn on the furnace?" ) ) ) {
            return;
        }
    }
    p.use_charges( itype_UPS, 1250 );
    here.i_clear( examp );
    here.furn_set( examp, next_arcfurnace_type );
    item result( itype_unfinished_cac2, calendar::turn );
    result.charges = char_charges;
    here.add_item( examp, result );
    add_msg( _( "You turn on the furnace." ) );
}
References _, map::add_item(), add_msg(), string_id< T >::c_str(), itype::charges_per_volume(), debugmsg, f_arcfurnace_empty, f_arcfurnace_full, f_null, format_volume(), map::furn(), map::furn_set(), get_map(), Character::get_skill_level(), Character::has_charges(), map::i_at(), map::i_clear(), int_id< T >::id(), itype_chem_carbide, itype_unfinished_cac2, itype_UPS, m_bad, query_yn(), skill_fabrication, calendar::turn, Character::use_charges(), and volume_units_abbr().
Referenced by iexamine_function_from_string().
arcfurnace_full()
void iexamine::arcfurnace_full (player & p, const tripoint & examp)
Definition at line 2792 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_arcfurnace_type = here.furn( examp );
    furn_id next_arcfurnace_type = f_null;
    if( cur_arcfurnace_type == f_arcfurnace_full ) {
        next_arcfurnace_type = f_arcfurnace_empty;
    } else {
        debugmsg( "Examined furniture has action arcfurnace_full, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    map_stack items = here.i_at( examp );
    if( items.empty() ) {
        add_msg( _( "This furnace is empty" ) );
        here.furn_set( examp, next_arcfurnace_type );
        return;
    }
    add_msg( _( "There's an arc furnace there." ) );
    const time_duration firing_time = 2_hours; // Arc furnaces work really fast in reality
    const time_duration time_left = firing_time - items.only_item().age();
    if( time_left > 0_turns ) {
        int hours = to_hours<int>( time_left );
        int minutes = to_minutes<int>( time_left ) + 1;
        if( minutes > 60 ) {
            add_msg( vgettext( "It will finish burning in about %d hour.",
                               "It will finish burning in about %d hours.",
                               hours ), hours );
        } else if( minutes > 30 ) {
            add_msg( _( "It will finish burning in less than an hour." ) );
        } else {
            add_msg( _( "It should take about %d minutes to finish burning." ), minutes );
        }
        return;
    }
    units::volume total_volume = 0_ml;
    // Burn stuff that should get charred, leave out the rest
    for( auto item_it = items.begin(); item_it != items.end(); ) {
        if( item_it->typeId() == itype_unfinished_cac2 || item_it->typeId() == itype_chem_carbide ) {
            total_volume += item_it->volume();
            item_it = items.erase( item_it );
        } else {
            item_it++;
        }
    }
    item result( itype_chem_carbide, calendar::turn );
    result.charges = itype_chem_carbide->charges_per_volume( total_volume );
    here.add_item( examp, result );
    here.furn_set( examp, next_arcfurnace_type );
    add_msg( _( "It has finished burning, yielding %d calcium carbide." ), result.charges );
}
References _, map::add_item(), add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), itype::charges_per_volume(), debugmsg, item_stack::empty(), item_stack::end(), map_stack::erase(), f_arcfurnace_empty, f_arcfurnace_full, f_null, map::furn(), map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), itype_chem_carbide, itype_unfinished_cac2, item_stack::only_item(), calendar::turn, and vgettext().
Referenced by iexamine_function_from_string().
atm()
void iexamine::atm (player & p, const tripoint & examp)
launches the atm menu class which then handles all the atm interactions.
Definition at line 666 of file iexamine.cpp.
{
    atm_menu {p} .start();
}
Referenced by activity_handlers::atm_do_turn(), and iexamine_function_from_string().
autoclave_empty()
void iexamine::autoclave_empty (player & p, const tripoint &)
Definition at line 2848 of file iexamine.cpp.
{
    item_location bionic = game_menus::inv::sterilize_cbm( p );
    if( bionic ) {
        avatar_funcs::mend_item( *p.as_avatar(), item_location( bionic ) );
    } else {
        add_msg( _( "Never mind." ) );
    }
}
References _, add_msg(), Creature::as_avatar(), avatar_funcs::mend_item(), and game_menus::inv::sterilize_cbm().
Referenced by iuse::autoclave(), iexamine_function_from_string(), and vehicle::interact_with().
autoclave_full()
void iexamine::autoclave_full (player & , const tripoint & examp)
Definition at line 2858 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_autoclave_type = here.furn( examp );
    furn_id next_autoclave_type = f_null;
    if( cur_autoclave_type == furn_id( "f_autoclave_full" ) ) {
        next_autoclave_type = furn_id( "f_autoclave" );
    } else {
        debugmsg( "Examined furniture has action autoclave_full, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    map_stack items = here.i_at( examp );
    bool cbms = std::all_of( items.begin(), items.end(), []( const item & i ) {
        return i.is_bionic();
    } );
    bool cbms_not_packed = std::all_of( items.begin(), items.end(), []( const item & i ) {
        return i.is_bionic() && i.has_flag( flag_NO_PACKED );
    } );
    if( items.empty() ) {
        add_msg( _( "This autoclave is empty" ) );
        here.furn_set( examp, next_autoclave_type );
        return;
    }
    if( !cbms ) {
        add_msg( m_bad,
                 _( "ERROR Autoclave can't process non CBM items." ) );
        return;
    }
    add_msg( _( "The autoclave is running." ) );
    const item &clock = *items.begin();
    const time_duration Cycle_time = 90_minutes;
    const time_duration time_left = Cycle_time - clock.age();
    if( time_left > 0_turns ) {
        add_msg( _( "The cycle will be complete in %s." ), to_string( time_left ) );
        return;
    }
    here.furn_set( examp, next_autoclave_type );
    for( item &it : items ) {
        if( !it.has_flag( flag_NO_PACKED ) ) {
            it.unset_flag( flag_NO_STERILE );
        }
    }
    add_msg( m_good, _( "The cycle is complete, the CBMs are now sterile." ) );
    if( cbms_not_packed ) {
        add_msg( m_info,
                 _( "CBMs in direct contact with the environment will almost immediately become contaminated." ) );
    }
    here.furn_set( examp, next_autoclave_type );
}
References _, add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), debugmsg, item_stack::empty(), item_stack::end(), f_null, flag_NO_PACKED(), flag_NO_STERILE(), map::furn(), map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), m_bad, m_good, m_info, and to_string().
Referenced by iexamine_function_from_string().
autodoc()
void iexamine::autodoc (player & p, const tripoint & examp)
Definition at line 4870 of file iexamine.cpp.
{
    enum options {
        INSTALL_CBM,
        UNINSTALL_CBM,
        BONESETTING,
        TREAT_WOUNDS,
        RAD_AWAY,
        BLOOD_ANALYSIS,
    };
    bool adjacent_couch = false;
    static avatar null_player;
    tripoint couch_pos;
    player &patient = player_on_couch( p, examp, null_player, adjacent_couch, couch_pos );
    Character &Operator = operator_present( p, examp, null_player );
    static item null_cyborg;
    item &cyborg = cyborg_on_couch( couch_pos, null_cyborg );
    if( !adjacent_couch ) {
        popup( _( "No connected couches found.  Operation impossible.  Exiting." ) );
        return;
    }
    if( &patient == &null_player ) {
        if( &cyborg != &null_cyborg ) {
            if( cyborg.typeId() == itype_corpse && !cyborg.active ) {
                popup( _( "Patient is dead.  Please remove corpse to proceed.  Exiting." ) );
                return;
            } else if( cyborg.typeId() == itype_bot_broken_cyborg || cyborg.typeId() == itype_corpse ) {
                popup( _( "ERROR Bionic Level Assessement: FULL CYBORG.  Autodoc Mk. XI can't opperate.  Please move patient to appropriate facility.  Exiting." ) );
                return;
            }
            uilist cmenu;
            cmenu.text = _( "Autodoc Mk. XI.  Status: Online.  Please choose operation." );
            cmenu.addentry( 1, true, 'i', _( "Choose Compact Bionic Module to install." ) );
            cmenu.addentry( 2, true, 'u', _( "Choose installed bionic to uninstall." ) );
            cmenu.query();
            switch( cmenu.ret ) {
                case 1: {
                    popup( _( "ERROR NO SPACE AVAILABLE.  Operation impossible.  Exiting." ) );
                    break;
                }
                case 2: {
                    std::vector<std::string> choice_names;
                    choice_names.push_back( _( "Personality_Override" ) );
                    for( size_t i = 0; i < 6; i++ ) {
                        choice_names.push_back( _( "C0RR#PTED?D#TA" ) );
                    }
                    int choice_index = uilist( _( "Choose bionic to uninstall" ), choice_names );
                    if( choice_index == 0 ) {
                        g->save_cyborg( &cyborg, couch_pos, p );
                    } else {
                        popup( _( "UNKNOWN COMMAND.  Autodoc Mk. XI. Crashed." ) );
                        return;
                    }
                    break;
                }
                default:
                    return;
            }
            return;
        } else {
            popup( _( "No patient found located on the connected couches.  Operation impossible.  Exiting." ) );
            return;
        }
    } else if( patient.activity.id() == activity_id( "ACT_OPERATION" ) ) {
        popup( _( "Operation underway.  Please wait until the end of the current procedure.  Estimated time remaining: %s." ),
               to_string( time_duration::from_turns( patient.activity.moves_left / 100 ) ) );
        p.add_msg_if_player( m_info, _( "The autodoc is working on %s." ), patient.disp_name() );
        return;
    }
    const bool unsafe_usage = &Operator == &null_player || ( &Operator == &p && &patient == &p );
    std::string autodoc_header = _( "Autodoc Mk. XI.  Status: Online.  Please choose operation" );
    if( unsafe_usage ) {
        const std::string &warning_sign = colorize( " /", c_yellow ) + colorize( "!",
                                          c_red ) + colorize( "\\", c_yellow );
        const std::string &warning = warning_sign + colorize( _( " WARNING: Operator missing" ),
                                     c_red ) + warning_sign;
        autodoc_header = warning +
                         _( "\n Using the Autodoc without an operator can lead to <color_light_cyan>serious injuries</color> and <color_light_cyan>various internal bionic malfunctions</color>.\n Manufacturer <color_light_green>guarantees automated bionic installation in functional condition</color>.\n Manufacturer <color_light_cyan>does not guarantee automated bionic uninstallation</color>.\n By continuing with the operation you accept the risks and acknowledge that you will not take any legal actions against this facility in case of an accident.\n\nThe following skills affect autodoc installation: Computers, First Aid, and Electronics." );
    }
    std::vector<item> arm_splints;
    std::vector<item> leg_splints;
    // find splints on the ground
    for( const item &supplies : get_map().i_at( examp ) ) {
        if( supplies.typeId() == itype_arm_splint ) {
            arm_splints.push_back( supplies );
        }
        if( supplies.typeId() == itype_leg_splint ) {
            leg_splints.push_back( supplies );
        }
    }
    // find splints in vehicle
    if( const cata::optional<vpart_reference> vp = get_map().veh_at( examp ).part_with_feature(
                flag_AUTODOC, false ) ) {
        auto dest_veh = &vp->vehicle();
        int dest_part = vp->part_index();
        for( item &it : dest_veh->get_items( dest_part ) ) {
            if( it.typeId() == itype_arm_splint ) {
                arm_splints.push_back( it );
            }
            if( it.typeId() == itype_leg_splint ) {
                leg_splints.push_back( it );
            }
        }
    }
    autodoc_header +=
        string_format(
            _( "\n\n<color_white>Internal supplies:</color>\n Arm splints: %d\n Leg splints: %d" ),
            arm_splints.size(), leg_splints.size() );
    uilist amenu;
    amenu.text = autodoc_header;
    amenu.addentry( INSTALL_CBM, true, 'i', _( "Choose Compact Bionic Module to install" ) );
    amenu.addentry( UNINSTALL_CBM, true, 'u', _( "Choose installed bionic to uninstall" ) );
    amenu.addentry( BONESETTING, true, 's', _( "Splint broken limbs" ) );
    amenu.addentry( TREAT_WOUNDS, true, 'w', _( "Treat wounds" ) );
    amenu.addentry( RAD_AWAY, true, 'r', _( "Check radiation level" ) );
    amenu.addentry( BLOOD_ANALYSIS, true, 'b', _( "Conduct blood analysis" ) );
    amenu.query();
    bool needs_anesthesia = true;
    std::vector<tool_comp> anesth_kit;
    if( patient.has_trait( trait_NOPAIN ) || patient.has_bionic( bio_painkiller ) ||
        amenu.ret > 1 ) {
        needs_anesthesia = false;
    } else {
        const inventory &crafting_inv = p.crafting_inventory();
        std::vector<const item *> a_filter = crafting_inv.items_with( []( const item & it ) {
            return it.has_quality( qual_ANESTHESIA );
        } );
        for( const item *anesthesia_item : a_filter ) {
            if( anesthesia_item->ammo_remaining() >= 1 ) {
                anesth_kit.push_back( tool_comp( anesthesia_item->typeId(), 1 ) );
            }
        }
    }
    switch( amenu.ret ) {
        case INSTALL_CBM: {
            item_location bionic = game_menus::inv::install_bionic( p, patient );
            if( !bionic ) {
                return;
            }
            const itype *itemtype = bionic.get_item()->type;
            player &installer = best_installer( p, null_player, itemtype->bionic->difficulty );
            if( &installer == &null_player ) {
                return;
            }
            std::vector<item_comp> progs;
            bool has_install_program = false;
            std::vector<const item *> install_programs = p.crafting_inventory().items_with( [itemtype](
                        const item & it ) -> bool { return it.typeId() == itemtype->bionic->installation_data; } );
            if( !install_programs.empty() ) {
                has_install_program = true;
                progs.emplace_back( install_programs[0]->typeId(), 1 );
            }
            const int weight = 7;
            const int surgery_duration = itemtype->bionic->difficulty * 2;
            const requirement_data req_anesth = *requirement_id( "anesthetic" ) *
                                                surgery_duration * weight;
            if( patient.can_install_bionics( ( *itemtype ), installer, true, has_install_program ? 10 : -1 ) ) {
                const time_duration duration = itemtype->bionic->difficulty * 20_minutes;
                patient.introduce_into_anesthesia( duration, installer, needs_anesthesia );
                bionic.remove_item();
                if( needs_anesthesia ) {
                    for( const auto &e : req_anesth.get_components() ) {
                        p.consume_items( e, 1, is_crafting_component );
                    }
                    for( const auto &e : req_anesth.get_tools() ) {
                        p.consume_tools( e );
                    }
                    p.invalidate_crafting_inventory();
                }
                installer.mod_moves( -to_moves<int>( 1_minutes ) );
                patient.install_bionics( ( *itemtype ), installer, true, has_install_program ? 10 : -1 );
                if( has_install_program ) {
                    patient.consume_items( progs );
                }
            }
            break;
        }
        case UNINSTALL_CBM: {
            const bionic_collection &installed_bionics = *patient.my_bionics;
            if( installed_bionics.empty() ) {
                popup_player_or_npc( patient, _( "You don't have any bionics installed." ),
                                     _( "<npcname> doesn't have any bionics installed." ) );
                return;
            }
            for( const bionic &bio : installed_bionics ) {
                if( bio.id != bio_power_storage ||
                    bio.id != bio_power_storage_mkII ) {
                    if( bio.info().itype().is_valid() ) {
                        // put cbm items in your inventory
                        item bionic_to_uninstall( bio.id.str(), calendar::turn );
                        bionic_to_uninstall.set_flag( flag_IN_CBM );
                        bionic_to_uninstall.set_flag( flag_NO_STERILE );
                        bionic_to_uninstall.set_flag( flag_NO_PACKED );
                        g->u.i_add( bionic_to_uninstall );
                    }
                }
            }
            const item_location bionic = game_menus::inv::uninstall_bionic( p, patient );
            if( !bionic ) {
                g->u.remove_items_with( []( const item & it ) {// remove cbm items from inventory
                    return it.has_flag( flag_IN_CBM );
                } );
                return;
            }
            const item *it = bionic.get_item();
            const itype *itemtype = it->type;
            const bionic_id &bid = itemtype->bionic->id;
            g->u.remove_items_with( []( const item & it ) {// remove cbm items from inventory
                return it.has_flag( flag_IN_CBM );
            } );
            // Malfunctioning bionics that don't have associated items and get a difficulty of 12
            const int difficulty = itemtype->bionic ? itemtype->bionic->difficulty : 12;
            const float volume_anesth = difficulty * 20 * 2; // 2ml/min
            player &installer = best_installer( p, null_player, difficulty );
            if( &installer == &null_player ) {
                return;
            }
            if( patient.can_uninstall_bionic( bid, installer, true ) ) {
                const time_duration duration = difficulty * 20_minutes;
                patient.introduce_into_anesthesia( duration, installer, needs_anesthesia );
                if( needs_anesthesia ) {
                    p.consume_tools( anesth_kit, volume_anesth );
                }
                installer.mod_moves( -to_moves<int>( 1_minutes ) );
                patient.uninstall_bionic( bid, installer, true );
            }
            break;
        }
        case BONESETTING: {
            if( arm_splints.empty() && leg_splints.empty() ) {
                popup( _( "Internal supply of splints exhausted.  Operation impossible.  Exiting." ) );
                return;
            }
            int broken_limbs_count = 0;
            for( int i = 0; i < num_hp_parts; i++ ) {
                const bodypart_id &part = convert_bp( player::hp_to_bp( static_cast<hp_part>( i ) ) ).id();
                const bool broken = patient.is_limb_broken( part );
                effect &existing_effect = patient.get_effect( effect_mending, part->token );
                // Skip part if not broken or already healed 50%
                if( !broken || ( !existing_effect.is_null() &&
                                 existing_effect.get_duration() >
                                 existing_effect.get_max_duration() - 5_days - 1_turns ) ) {
                    continue;
                }
                broken_limbs_count++;
                patient.moves -= 500;
                // TODO: fail here if unable to perform the action, i.e. can't wear more, trait mismatch.
                int quantity = 1;
                if( part == bodypart_id( "arm_l" ) || part == bodypart_id( "arm_r" ) ) {
                    if( !arm_splints.empty() ) {
                        for( const item &it : get_map().use_amount( examp, 1, itype_arm_splint, quantity ) ) {
                            patient.wear_item( it, false );
                        }
                    } else {
                        popup( _( "Internal supply of arm splints exhausted.  Splinting broken arms impossible.  Exiting." ) );
                        continue;
                    }
                } else if( part == bodypart_id( "leg_l" ) || part == bodypart_id( "leg_r" ) ) {
                    if( !leg_splints.empty() ) {
                        for( const item &it : get_map().use_amount( examp, 1, itype_leg_splint, quantity ) ) {
                            patient.wear_item( it, false );
                        }
                    } else {
                        popup( _( "Internal supply of leg splints exhausted.  Splinting broken legs impossible.  Exiting." ) );
                        continue;
                    }
                }
                if( patient.worn_with_flag( flag_SPLINT, part ) ) {
                    patient.add_msg_player_or_npc( m_good, _( "The machine rapidly sets and splints your broken %s." ),
                                                   _( "The machine rapidly sets and splints <npcname>'s broken %s." ),
                                                   body_part_name( part ) );
                    patient.add_effect( effect_mending, 0_turns, part->token );
                    effect &mending_effect = patient.get_effect( effect_mending, part->token );
                    mending_effect.set_duration( mending_effect.get_max_duration() - 5_days );
                }
            }
            if( broken_limbs_count == 0 ) {
                popup_player_or_npc( patient, _( "You have no limbs that require splinting." ),
                                     _( "<npcname> doesn't have limbs that require splinting." ) );
            }
            break;
        }
        case TREAT_WOUNDS: {
            if( !patient.has_effect( effect_bleed ) && !patient.has_effect( effect_infected ) &&
                !patient.has_effect( effect_bite ) ) {
                p.add_msg_player_or_npc( m_info, _( "You don't have any wounds that need treatment." ),
                                         _( "<npcname> doesn't have any wounds that need treatment." ) );
                return;
            }
            if( patient.has_effect( effect_infected ) ) {
                if( patient.has_effect( effect_strong_antibiotic ) ||
                    patient.has_effect( effect_antibiotic ) ||
                    patient.has_effect( effect_weak_antibiotic ) ) {
                    patient.add_msg_player_or_npc( m_info,
                                                   _( "The autodoc detected a bacterial infection in your body, but as it also detected you've already taken antibiotics, it decided not to apply another dose right now." ),
                                                   _( "The autodoc detected a bacterial infection in <npcname>'s body, but as it also detected they've already taken antibiotics, it decided not to apply another dose right now." ) );
                } else {
                    patient.add_effect( effect_strong_antibiotic, 12_hours );
                    patient.mod_pain( 3 );
                    patient.add_msg_player_or_npc( m_good,
                                                   _( "The autodoc detected a bacterial infection in your body and injected antibiotics to treat it." ),
                                                   _( "The autodoc detected a bacterial infection in <npcname>'s body and injected antibiotics to treat it." ) );
                }
            }
            for( int i = 0; i < num_hp_parts; i++ ) {
                const bodypart_id &bp_healed = convert_bp( player::hp_to_bp( static_cast<hp_part>( i ) ) ).id();
                if( patient.has_effect( effect_bleed, bp_healed.id() ) ) {
                    patient.remove_effect( effect_bleed, bp_healed->token );
                    patient.add_msg_player_or_npc( m_good,
                                                   _( "The autodoc detected a bleeding on your %s and applied a hemostatic drug to stop it." ),
                                                   _( "The autodoc detected a bleeding on <npcname>'s %s and applied a hemostatic drug to stop it." ),
                                                   body_part_name( bp_healed ) );
                }
                if( patient.has_effect( effect_bite, bp_healed.id() ) ) {
                    patient.remove_effect( effect_bite, bp_healed->token );
                    patient.add_msg_player_or_npc( m_good,
                                                   _( "The autodoc detected an open wound on your %s and applied a disinfectant to clean it." ),
                                                   _( "The autodoc detected an open wound on <npcname>'s %s and applied a disinfectant to clean it." ),
                                                   body_part_name( bp_healed ) );
                    // Fixed disinfectant intensity of 4 disinfectant_power + 10 first aid skill level of autodoc.
                    const int disinfectant_intensity = 14;
                    patient.add_effect( effect_disinfected, 1_turns, bp_healed->token );
                    effect &e = patient.get_effect( effect_disinfected, bp_healed->token );
                    e.set_duration( e.get_int_dur_factor() * disinfectant_intensity );
                    hp_part target_part = player::bp_to_hp( bp_healed->token );
                    patient.damage_disinfected[target_part] =
                        patient.get_part_hp_max( bp_healed ) - patient.get_part_hp_cur( bp_healed );
                }
            }
            patient.moves -= 500;
            break;
        }
        case RAD_AWAY: {
            patient.moves -= 500;
            patient.add_msg_player_or_npc( m_info,
                                           _( "The autodoc scanned you and detected a radiation level of %d mSv." ),
                                           _( "The autodoc scanned <npcname> and detected a radiation level of %d mSv." ),
                                           patient.get_rad() );
            if( patient.get_rad() ) {
                if( patient.has_effect( effect_pblue ) ) {
                    patient.add_msg_player_or_npc( m_info,
                                                   _( "The autodoc detected an anti-radiation drug in your bloodstream, so it decided not to administer another dose right now." ),
                                                   _( "The autodoc detected an anti-radiation drug in <npcname>'s bloodstream, so it decided not to administer another dose right now." ) );
                } else {
                    add_msg( m_good,
                             _( "The autodoc administered an anti-radiation drug to treat radiation poisoning." ) );
                    patient.mod_pain( 3 );
                    patient.add_effect( effect_pblue, 1_hours );
                }
            }
            if( patient.leak_level( "RADIOACTIVE" ) ) {
                popup( _( "Warning!  Autodoc detected a radiation leak of %d mSv from items in patient's possession.  Urgent decontamination procedures highly recommended." ),
                       patient.leak_level( "RADIOACTIVE" ) );
            }
            break;
        }
        case BLOOD_ANALYSIS: {
            patient.moves -= 500;
            patient.conduct_blood_analysis();
            patient.add_msg_player_or_npc( m_info,
                                           _( "The autodoc analyzed your blood." ),
                                           _( "The autodoc analyzed <npcname>'s blood." ) );
            break;
        }
        default:
            return;
    }
}
References _, item::active, Character::activity, Creature::add_effect(), add_msg(), player::add_msg_if_player(), player::add_msg_player_or_npc(), uilist::addentry(), best_installer(), bio_painkiller, bio_power_storage, bio_power_storage_mkII, itype::bionic, body_part_name(), Character::bp_to_hp(), broken, c_red, c_yellow, Character::can_install_bionics(), Character::can_uninstall_bionic(), colorize(), Character::conduct_blood_analysis(), player::consume_items(), player::consume_tools(), convert_bp(), Character::crafting_inventory(), cyborg_on_couch(), Character::damage_disinfected, Character::disp_name(), effect_antibiotic, effect_bite, effect_bleed, effect_disinfected, effect_infected, effect_mending, effect_pblue, effect_strong_antibiotic, effect_weak_antibiotic, flag_AUTODOC(), flag_IN_CBM(), flag_NO_PACKED(), flag_NO_STERILE(), flag_SPLINT(), time_duration::from_turns(), g, requirement_data::get_components(), effect::get_duration(), Creature::get_effect(), effect::get_int_dur_factor(), get_map(), effect::get_max_duration(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Character::get_rad(), requirement_data::get_tools(), Character::has_bionic(), Creature::has_effect(), item::has_flag(), visitable< T >::has_quality(), Character::has_trait(), Character::hp_to_bp(), int_id< T >::id(), player_activity::id(), string_id< T >::id(), game_menus::inv::install_bionic(), Character::install_bionics(), Character::introduce_into_anesthesia(), Character::invalidate_crafting_inventory(), is_crafting_component(), Character::is_limb_broken(), effect::is_null(), visitable< T >::items_with(), itype_arm_splint, itype_bot_broken_cyborg, itype_corpse, itype_leg_splint, Character::leak_level(), m_good, m_info, Creature::mod_moves(), Character::mod_pain(), Creature::moves, player_activity::moves_left, Character::my_bionics, num_hp_parts, operator_present(), PATH_INFO::options(), player_on_couch(), popup(), popup_player_or_npc(), qual_ANESTHESIA, uilist::query(), Creature::remove_effect(), uilist::ret, effect::set_duration(), item::set_flag(), string_format(), uilist::text, to_string(), trait_NOPAIN, calendar::turn, item::type, item::typeId(), Character::uninstall_bionic(), game_menus::inv::uninstall_bionic(), Character::wear_item(), and Character::worn_with_flag().
Referenced by Character::can_install_bionics(), Character::can_uninstall_bionic(), iexamine_function_from_string(), Character::install_bionics(), vehicle::interact_with(), activity_handlers::operation_do_turn(), and Character::uninstall_bionic().
bars()
void iexamine::bars (player & p, const tripoint & examp)
If player has amorphous trait, slip through the bars.
Definition at line 1213 of file iexamine.cpp.
{
    if( !( p.has_trait( trait_AMORPHOUS ) ) ) {
        none( p, examp );
        return;
    }
    map &here = get_map();
    if( ( ( p.encumb( bp_torso ) ) >= 10 ) && ( ( p.encumb( bp_head ) ) >= 10 ) &&
        ( p.encumb( bp_foot_l ) >= 10 ||
          p.encumb( bp_foot_r ) >= 10 ) ) { // Most likely places for rigid gear that would catch on the bars.
        add_msg( m_info,
                 _( "Your amorphous body could slip though the %s, but your cumbersome gear can't." ),
                 here.tername( examp ) );
        return;
    }
    if( !query_yn( _( "Slip through the %s?" ), here.tername( examp ) ) ) {
        none( p, examp );
        return;
    }
    p.moves -= to_turns<int>( 2_seconds );
    add_msg( _( "You slide right between the bars." ) );
    p.setpos( examp );
}
References _, add_msg(), bp_foot_l, bp_foot_r, bp_head, bp_torso, Character::encumb(), get_map(), Character::has_trait(), m_info, Creature::moves, none, query_yn(), Character::setpos(), map::tername(), and trait_AMORPHOUS.
Referenced by iexamine_function_from_string().
bulletin_board()
void iexamine::bulletin_board (player & p, const tripoint & examp)
Definition at line 1586 of file iexamine.cpp.
{
    g->validate_camps();
    map &here = get_map();
    // TODO: fix point types
    point_abs_omt omt( ms_to_omt_copy( here.getabs( examp.xy() ) ) );
    cata::optional<basecamp *> bcp = overmap_buffer.find_camp( omt );
    if( bcp ) {
        basecamp *temp_camp = *bcp;
        temp_camp->validate_bb_pos( here.getabs( examp ) );
        temp_camp->validate_assignees();
        temp_camp->validate_sort_points();
        const std::string title = ( "Base Missions" );
        mission_data mission_key;
        temp_camp->set_by_radio( false );
        temp_camp->get_available_missions( mission_key );
        if( talk_function::display_and_choose_opts( mission_key, temp_camp->camp_omt_pos(),
                "FACTION_CAMP", title ) ) {
            temp_camp->handle_mission( mission_key.cur_key.id, mission_key.cur_key.dir );
        }
    } else {
        p.add_msg_if_player( _( "This bulletin board is not inside a camp" ) );
    }
}
References _, player::add_msg_if_player(), basecamp::camp_omt_pos(), mission_data::cur_key, mission_entry::dir, talk_function::display_and_choose_opts(), overmapbuffer::find_camp(), g, basecamp::get_available_missions(), get_map(), map::getabs(), basecamp::handle_mission(), mission_entry::id, ms_to_omt_copy(), coords::omt, overmap_buffer, basecamp::set_by_radio(), PATH_INFO::title(), basecamp::validate_assignees(), basecamp::validate_bb_pos(), basecamp::validate_sort_points(), and tripoint::xy().
Referenced by iexamine_function_from_string().
can_fertilize()
ret_val< bool > iexamine::can_fertilize (player & p, const tripoint & tile, const itype_id & fertilizer)
Definition at line 2457 of file iexamine.cpp.
{
    map &here = get_map();
    if( !here.has_flag_furn( "PLANT", tile ) ) {
        return ret_val<bool>::make_failure( _( "Tile isn't a plant" ) );
    }
    if( here.i_at( tile ).size() > 1 ) {
        return ret_val<bool>::make_failure( _( "Tile is already fertilized" ) );
    }
    if( !p.has_charges( fertilizer, 1 ) ) {
        return ret_val<bool>::make_failure(
                   _( "Tried to fertilize with %s, but player doesn't have any." ),
                   fertilizer.c_str() );
    }
    return ret_val<bool>::make_success();
}
References _, string_id< T >::c_str(), get_map(), Character::has_charges(), map::has_flag_furn(), map::i_at(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and item_stack::size().
Referenced by fertilize_plant(), and activity_handlers::fertilize_plot_do_turn().
cardreader()
void iexamine::cardreader (player & p, const tripoint & examp)
Use id/hack reader.
Using an id despawns turrets.
Definition at line 1021 of file iexamine.cpp.
{
    bool open = false;
    map &here = get_map();
    itype_id card_type = ( here.ter( examp ) == t_card_science ? itype_id_science :
                           here.ter( examp ) == t_card_military ? itype_id_military :
                           itype_id_industrial );
    if( p.has_amount( card_type, 1 ) && query_yn( _( "Swipe your ID card?" ) ) ) {
        p.mod_moves( -to_turns<int>( 1_seconds ) );
        for( const tripoint &tmp : here.points_in_radius( examp, 3 ) ) {
            if( here.ter( tmp ) == t_door_metal_locked ) {
                here.ter_set( tmp, t_door_metal_c );
                open = true;
            }
        }
        for( monster &critter : g->all_monsters() ) {
            // Check 1) same overmap coords, 2) turret, 3) hostile
            if( ms_to_omt_copy( here.getabs( critter.pos() ) ) == ms_to_omt_copy( here.getabs( examp ) ) &&
                critter.has_flag( MF_ID_CARD_DESPAWN ) &&
                critter.attitude_to( p ) == Creature::Attitude::A_HOSTILE ) {
                g->remove_zombie( critter );
            }
        }
        if( open ) {
            add_msg( _( "You insert your ID card." ) );
            add_msg( m_good, _( "The nearby doors unlock." ) );
            p.use_amount( card_type, 1 );
        } else {
            add_msg( _( "The nearby doors are already opened." ) );
        }
    } else if( query_yn( _( "Attempt to hack this card-reader?" ) ) ) {
        try_start_hacking( p, examp );
    }
}
References _, add_msg(), g, get_map(), map::getabs(), visitable< T >::has_amount(), itype_id_industrial, itype_id_military, itype_id_science, m_good, MF_ID_CARD_DESPAWN, Creature::mod_moves(), ms_to_omt_copy(), open(), map::points_in_radius(), query_yn(), t_card_military, t_card_science, t_door_metal_c, t_door_metal_locked, map::ter(), map::ter_set(), try_start_hacking(), and Character::use_amount().
Referenced by get_hack_type(), and iexamine_function_from_string().
cardreader_foodplace()
void iexamine::cardreader_foodplace (player & p, const tripoint & examp)
Definition at line 1070 of file iexamine.cpp.
{
    bool open = false;
    if( ( p.is_wearing( itype_id( "foodperson_mask" ) ) ||
          p.is_wearing( itype_id( "foodperson_mask_on" ) ) ) &&
        query_yn( _( "Press mask on the reader?" ) ) ) {
        p.mod_moves( -100 );
        map &here = get_map();
        for( const tripoint &tmp : here.points_in_radius( examp, 3 ) ) {
            if( here.ter( tmp ) == t_door_metal_locked ) {
                here.ter_set( tmp, t_door_metal_c );
                open = true;
            }
        }
        if( open ) {
            add_msg( _( "You press your face on the reader." ) );
            add_msg( m_good, _( "The nearby doors are unlocked." ) );
            sounds::sound( examp, 6, sounds::sound_t::electronic_speech,
                           _( "\"Hello Foodperson.  Welcome home.\"" ), true, "speech", "welcome" );
        } else {
            add_msg( _( "The nearby doors are already unlocked." ) );
            if( query_yn( _( "Lock doors?" ) ) ) {
                for( const tripoint &tmp : here.points_in_radius( examp, 3 ) ) {
                    if( here.ter( tmp ) == t_door_metal_o || here.ter( tmp ) == t_door_metal_c ) {
                        if( p.pos() == tmp ) {
                            p.add_msg_if_player( m_bad, _( "You are in the way of the door, move before trying again." ) );
                        } else {
                            here.ter_set( tmp, t_door_metal_locked );
                        }
                    }
                }
            }
        }
    } else if( p.has_amount( itype_id( "foodperson_mask" ), 1 ) ||
               p.has_amount( itype_id( "foodperson_mask_on" ), 1 ) ) {
        sounds::sound( examp, 6, sounds::sound_t::electronic_speech,
                       _( "\"FOODPERSON DETECTED.  Please make yourself presentable.\"" ), true,
                       "speech", "welcome" );
    } else {
        sounds::sound( examp, 6, sounds::sound_t::electronic_speech,
                       _( "\"Your face is inadequate.  Please go away.\"" ), true,
                       "speech", "welcome" );
        if( query_yn( _( "Attempt to hack this card-reader?" ) ) ) {
            try_start_hacking( p, examp );
        }
    }
}
References _, add_msg(), player::add_msg_if_player(), sounds::electronic_speech, get_map(), visitable< T >::has_amount(), Character::is_wearing(), m_bad, m_good, Creature::mod_moves(), open(), map::points_in_radius(), Character::pos(), query_yn(), sounds::sound(), t_door_metal_c, t_door_metal_locked, t_door_metal_o, map::ter(), map::ter_set(), and try_start_hacking().
Referenced by iexamine_function_from_string().
cardreader_robofac()
void iexamine::cardreader_robofac (player & p, const tripoint & examp)
Definition at line 1056 of file iexamine.cpp.
{
    itype_id card_type = itype_id_science;
    if( p.has_amount( card_type, 1 ) && query_yn( _( "Swipe your ID card?" ) ) ) {
        p.mod_moves( -100 );
        p.use_amount( card_type, 1 );
        add_msg( m_bad, _( "The card reader short circuits!" ) );
        get_map().ter_set( examp, t_card_reader_broken );
        intercom( p, examp );
    } else {
        add_msg( _( "You have never seen this card reader model before.  Hacking it seems impossible." ) );
    }
}
References _, add_msg(), get_map(), visitable< T >::has_amount(), intercom(), itype_id_science, m_bad, Creature::mod_moves(), query_yn(), t_card_reader_broken, map::ter_set(), and Character::use_amount().
Referenced by iexamine_function_from_string().
chainfence()
void iexamine::chainfence (player & p, const tripoint & examp)
Prompt climbing over fence.
Calculates move cost, applies it to player and, moves them.
Dexterity decreases chances of slipping while climbing
Definition at line 1158 of file iexamine.cpp.
{
    // We're not going to do anything if we're already on that point.
    // Also prompt the player before taking an action.
    if( p.pos() == examp || !query_yn( _( "Climb obstacle?" ) ) ) {
        none( p, examp );
        return;
    }
    map &here = get_map();
    if( here.has_flag( flag_CLIMB_SIMPLE, examp ) && p.has_trait( trait_PARKOUR ) ) {
        add_msg( _( "You vault over the obstacle with ease." ) );
        p.moves -= 100; // Not tall enough to warrant spider-climbing, so only relevant trait.
    } else if( here.has_flag( flag_CLIMB_SIMPLE, examp ) ) {
        add_msg( _( "You vault over the obstacle." ) );
        p.moves -= 300; // Most common move cost for barricades pre-change.
    } else if( p.has_trait( trait_ARACHNID_ARMS_OK ) &&
               !p.wearing_something_on( bodypart_id( "torso" ) ) ) {
        add_msg( _( "Climbing this obstacle is trivial for one such as you." ) );
        p.moves -= 75; // Yes, faster than walking.  6-8 limbs are impressive.
    } else if( p.has_trait( trait_INSECT_ARMS_OK ) &&
               !p.wearing_something_on( bodypart_id( "torso" ) ) ) {
        add_msg( _( "You quickly scale the fence." ) );
        p.moves -= 90;
    } else if( p.has_trait( trait_PARKOUR ) ) {
        add_msg( _( "This obstacle is no match for your freerunning abilities." ) );
        p.moves -= 100;
    } else {
        p.moves -= 400;
        ///\EFFECT_DEX decreases chances of slipping while climbing
        int climb = p.dex_cur;
        if( p.has_trait( trait_BADKNEES ) ) {
            climb = climb / 2;
        }
        if( g->slip_down() ) {
            return;
        }
        p.moves += climb * 10;
        sfx::play_variant_sound( "plmove", "clear_obstacle", sfx::get_heard_volume( g->u.pos() ) );
    }
    if( p.in_vehicle ) {
        here.unboard_vehicle( p.pos() );
    }
    p.setpos( examp );
    if( examp.x < HALF_MAPSIZE_X || examp.y < HALF_MAPSIZE_Y ||
        examp.x >= HALF_MAPSIZE_X + SEEX || examp.y >= HALF_MAPSIZE_Y + SEEY ) {
        if( p.is_player() ) {
            g->update_map( p );
        }
    }
}
References _, add_msg(), Character::dex_cur, flag_CLIMB_SIMPLE(), g, sfx::get_heard_volume(), get_map(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, map::has_flag(), Character::has_trait(), Character::in_vehicle, player::is_player(), Creature::moves, none, sfx::play_variant_sound(), Character::pos(), query_yn(), SEEX, SEEY, Character::setpos(), trait_ARACHNID_ARMS_OK, trait_BADKNEES, trait_INSECT_ARMS_OK, trait_PARKOUR, map::unboard_vehicle(), Character::wearing_something_on(), tripoint::x, and tripoint::y.
Referenced by iexamine_function_from_string().
check_power()
void iexamine::check_power (player & p, const tripoint & examp)
Definition at line 6239 of file iexamine.cpp.
{
    tripoint_abs_ms abspos( g->m.getabs( examp ) );
    battery_tile *battery = active_tiles::furn_at<battery_tile>( abspos );
    if( battery != nullptr ) {
        add_msg( m_info, _( "This battery stores %d kJ of electric power." ), battery->get_resource() );
    }
    int amt = get_distribution_grid_tracker().grid_at( abspos ).get_resource();
    add_msg( m_info, _( "This electric grid stores %d kJ of electric power." ), amt );
}
References _, add_msg(), active_tiles::furn_at< battery_tile >(), g, get_distribution_grid_tracker(), battery_tile::get_resource(), distribution_grid::get_resource(), distribution_grid_tracker::grid_at(), and m_info.
Referenced by iexamine_function_from_string().
choose_fertilizer()
itype_id iexamine::choose_fertilizer (player & p, const std::string & pname, bool ask_player)
Definition at line 2519 of file iexamine.cpp.
{
    std::vector<const item *> f_inv = p.all_items_with_flag( flag_FERTILIZER );
    if( f_inv.empty() ) {
        add_msg( m_info, _( "You have no fertilizer for the %s." ), pname );
        return itype_id();
    }
    std::vector<itype_id> f_types;
    std::vector<std::string> f_names;
    for( auto &f : f_inv ) {
        if( std::find( f_types.begin(), f_types.end(), f->typeId() ) == f_types.end() ) {
            f_types.push_back( f->typeId() );
            f_names.push_back( f->tname() );
        }
    }
    if( ask_player && !query_yn( _( "Fertilize the %s" ), pname ) ) {
        return itype_id();
    }
    // Choose fertilizer from list
    int f_index = 0;
    if( f_types.size() > 1 ) {
        f_index = uilist( _( "Use which fertilizer?" ), f_names );
    }
    if( f_index < 0 ) {
        return itype_id();
    }
    return f_types[f_index];
}
References _, add_msg(), Character::all_items_with_flag(), detail::find(), flag_FERTILIZER(), m_info, and query_yn().
Referenced by aggie_plant(), and activity_handlers::fertilize_plot_do_turn().
clean_water_source()
void iexamine::clean_water_source (player & , const tripoint & examp)
Definition at line 3878 of file iexamine.cpp.
{
    item water = item( "water_clean", calendar::start_of_cataclysm, item::INFINITE_CHARGES );
    liquid_handler::handle_liquid( water, nullptr, 0, &examp );
}
References liquid_handler::handle_liquid(), item::INFINITE_CHARGES, and calendar::start_of_cataclysm.
Referenced by iexamine_function_from_string().
controls_gate()
void iexamine::controls_gate (player & p, const tripoint & examp)
Open or close gate.
Definition at line 967 of file iexamine.cpp.
{
    if( !query_yn( _( "Use the %s?" ), get_map().tername( examp ) ) ) {
        none( p, examp );
        return;
    }
    g->toggle_gate( examp );
}
References _, g, get_map(), none, and query_yn().
Referenced by anonymous_namespace{gates.cpp}::gate_data::check(), and iexamine_function_from_string().
curtains()
void iexamine::curtains (player & p, const tripoint & examp)
Definition at line 4138 of file iexamine.cpp.
{
    map &here = get_map();
    const bool closed_window_with_curtains = here.has_flag( flag_BARRICADABLE_WINDOW_CURTAINS, examp );
    if( here.is_outside( p.pos() ) && ( here.has_flag( flag_WALL, examp ) ||
                                        closed_window_with_curtains ) ) {
        locked_object( p, examp );
        return;
    }
    const ter_id ter = here.ter( examp );
    // Peek through the curtains, or tear them down.
    uilist window_menu;
    window_menu.text = _( "Do what with the curtains?" );
    window_menu.addentry( 0, ( !ter.obj().close &&
                               closed_window_with_curtains ), 'p', _( "Peek through the closed curtains." ) );
    window_menu.addentry( 1, true, 't', _( "Tear down the curtains." ) );
    window_menu.query();
    const int choice = window_menu.ret;
    if( choice == 0 ) {
        // Peek
        g->peek( examp );
        p.add_msg_if_player( _( "You carefully peek through the curtains." ) );
    } else if( choice == 1 ) {
        // Mr. Gorbachev, tear down those curtains!
        if( here.ter( examp )->has_curtains() ) {
            here.ter_set( examp, here.ter( examp )->curtain_transform );
        }
        here.spawn_item( p.pos(), itype_nail, 1, 4, calendar::turn );
        here.spawn_item( p.pos(), itype_sheet, 2, 0, calendar::turn );
        here.spawn_item( p.pos(), itype_stick, 1, 0, calendar::turn );
        here.spawn_item( p.pos(), itype_string_36, 1, 0, calendar::turn );
        p.moves -= to_moves<int>( 10_seconds );
        p.add_msg_if_player( _( "You tear the curtains and curtain rod off the windowframe." ) );
    } else {
        p.add_msg_if_player( _( "Never mind." ) );
    }
}
References _, player::add_msg_if_player(), uilist::addentry(), ter_t::close, map_data_common_t::curtain_transform, flag_BARRICADABLE_WINDOW_CURTAINS(), flag_WALL(), g, get_map(), map_data_common_t::has_curtains(), map::has_flag(), map::is_outside(), itype_nail, itype_sheet, itype_stick, itype_string_36, locked_object(), Creature::moves, int_id< T >::obj(), Character::pos(), uilist::query(), uilist::ret, map::spawn_item(), map::ter(), map::ter_set(), uilist::text, and calendar::turn.
Referenced by iexamine_function_from_string(), and vehicle::part_color().
cvdmachine()
void iexamine::cvdmachine (player & p, const tripoint & examp)
Pick an appropriate item and apply diamond coating if possible.
Definition at line 260 of file iexamine.cpp.
{
    // Select an item to which it is possible to apply a diamond coating
    auto loc = g->inv_map_splice( []( const item & e ) {
        return ( e.is_melee( DT_CUT ) || e.is_melee( DT_STAB ) ) && e.made_of( material_id( "steel" ) ) &&
               !e.has_flag( flag_DIAMOND ) && !e.has_flag( flag_NO_CVD );
    }, _( "Apply diamond coating" ), 1, _( "You don't have a suitable item to coat with diamond" ) );
    if( !loc ) {
        return;
    }
    // Require materials proportional to selected item volume
    auto qty = loc->volume() / units::legacy_volume_factor;
    qty = std::max( 1, qty );
    auto reqs = *requirement_id( "cvd_diamond" ) * qty;
    if( !reqs.can_make_with_inventory( p.crafting_inventory(), is_crafting_component ) ) {
        popup( "%s", reqs.list_missing() );
        return;
    }
    // Consume materials
    for( const auto &e : reqs.get_components() ) {
        p.consume_items( e, 1, is_crafting_component );
    }
    for( const auto &e : reqs.get_tools() ) {
        p.consume_tools( e );
    }
    p.invalidate_crafting_inventory();
    // Apply flag to item
    loc->set_flag( "DIAMOND" );
    add_msg( m_good, _( "You apply a diamond coating to your %s" ), loc->type_name() );
    p.mod_moves( -to_turns<int>( 10_seconds ) );
}
References _, add_msg(), player::consume_items(), player::consume_tools(), Character::crafting_inventory(), DT_CUT, DT_STAB, flag_DIAMOND(), flag_NO_CVD(), g, item::has_flag(), Character::invalidate_crafting_inventory(), is_crafting_component(), item::is_melee(), units::legacy_volume_factor, m_good, item::made_of(), Creature::mod_moves(), and popup().
Referenced by iexamine_function_from_string().
deployed_furniture()
void iexamine::deployed_furniture (player & p, const tripoint & pos)
Definition at line 1237 of file iexamine.cpp.
{
    map &here = get_map();
    if( !query_yn( _( "Take down the %s?" ), here.furn( pos ).obj().name() ) ) {
        return;
    }
    p.add_msg_if_player( m_info, _( "You take down the %s." ),
                         here.furn( pos ).obj().name() );
    const auto furn_item = here.furn( pos ).obj().deployed_item;
    here.add_item_or_charges( pos, item( furn_item, calendar::turn ) );
    here.furn_set( pos, f_null );
}
References _, map::add_item_or_charges(), player::add_msg_if_player(), furn_t::deployed_item, f_null, map::furn(), map::furn_set(), get_map(), m_info, map_data_common_t::name(), int_id< T >::obj(), query_yn(), and calendar::turn.
Referenced by finalize_furn(), iexamine_function_from_string(), and smoker_options().
dimensional_portal()
void iexamine::dimensional_portal (player & p, const tripoint & examp)
Definition at line 6199 of file iexamine.cpp.
{
    uilist menu;
    menu.text = _( "What to do with the portal:" );
    menu.desc_enabled = true;
    std::vector<const item *> nukes = p.all_items_with_flag( flag_CLOSES_PORTAL );
    menu.addentry_desc( 0, !nukes.empty(), 'e', _( "Close from here" ),
                        _( "Requires a nuclear explosive" ) );
    menu.addentry_desc( 1, true, 'Q', _( "Sacrifice yourself" ),
                        _( "This will kill you, but close the portal" ) );
    menu.query();
    switch( menu.ret ) {
        case 0: {
            item_location the_nuke = game_menus::inv::titled_filter_menu( []( const item & it ) {
                return it.has_flag( flag_CLOSES_PORTAL );
            }, static_cast<avatar &>( p ), _( "What to use to close the portal?" ) );
            if( !the_nuke ) {
                add_msg( m_info, _( "Never mind." ) );
                break;
            }
            add_msg( m_good, _( "You throw the armed %s into the portal!" ), the_nuke->tname() );
            the_nuke.remove_item();
            g->m.translate_radius( t_dimensional_portal, t_thconc_floor, 5, examp, true );
            g->win();
            break;
        }
        case 1:
            p.set_all_parts_hp_cur( 0 );
            g->m.translate_radius( t_dimensional_portal, t_thconc_floor, 5, examp, true );
            g->win();
            break;
        default:
            add_msg( m_info, _( "Never mind." ) );
    }
}
References _, add_msg(), uilist::addentry_desc(), Character::all_items_with_flag(), uilist::desc_enabled, flag_CLOSES_PORTAL(), g, item::has_flag(), m_good, m_info, uilist::query(), item_location::remove_item(), uilist::ret, Creature::set_all_parts_hp_cur(), t_dimensional_portal, t_thconc_floor, uilist::text, game_menus::inv::titled_filter_menu(), and item::tname().
Referenced by iexamine_function_from_string().
dirtmound()
void iexamine::dirtmound (player & p, const tripoint & examp)
If it's warm enough, pick one of the player's seeds and plant it.
Definition at line 2299 of file iexamine.cpp.
{
    if( !warm_enough_to_plant( g->u.pos() ) ) {
        add_msg( m_info, _( "It is too cold to plant anything now." ) );
        return;
    }
    map &here = get_map();
    /* ambient_light_at() not working?
    if (here.ambient_light_at(examp) < LIGHT_AMBIENT_LOW) {
        add_msg(m_info, _("It is too dark to plant anything now."));
        return;
    }*/
    std::vector<item *> seed_inv = p.items_with( []( const item & itm ) {
        return itm.is_seed();
    } );
    if( seed_inv.empty() ) {
        add_msg( m_info, _( "You have no seeds to plant." ) );
        return;
    }
    if( !here.i_at( examp ).empty() ) {
        add_msg( _( "Something's lying there" ) );
        return;
    }
    auto seed_entries = get_seed_entries( seed_inv );
    int seed_index = query_seed( seed_entries );
    // Did we cancel?
    if( seed_index < 0 || seed_index >= static_cast<int>( seed_entries.size() ) ) {
        add_msg( _( "You saved your seeds for later." ) );
        return;
    }
    const auto &seed_id = std::get<0>( seed_entries[seed_index] );
    plant_seed( p, examp, seed_id );
}
References _, add_msg(), item_stack::empty(), g, get_map(), get_seed_entries(), map::i_at(), item::is_seed(), visitable< T >::items_with(), m_info, plant_seed(), query_seed(), and warm_enough_to_plant().
Referenced by colorized_ter_name_flags_at(), and iexamine_function_from_string().
door_peephole()
void iexamine::door_peephole (player & p, const tripoint & examp)
Unlock/open door or attempt to peek through peephole.
Definition at line 1746 of file iexamine.cpp.
{
    map &here = get_map();
    if( here.is_outside( p.pos() ) ) {
        // if door is a locked type attempt to open
        if( here.has_flag( flag_OPENCLOSE_INSIDE, examp ) ) {
            locked_object( p, examp );
        } else {
            p.add_msg_if_player( _( "You cannot look through the peephole from the outside." ) );
        }
        return;
    }
    // Peek through the peephole, or open the door.
    const int choice = uilist( _( "Do what with the door?" ), {
        _( "Peek through peephole." ),
        _( "Open door." )
    } );
    if( choice == 0 ) {
        // Peek
        g->peek( examp );
        p.add_msg_if_player( _( "You peek through the peephole." ) );
    } else if( choice == 1 ) {
        here.open_door( examp, true, false );
        p.add_msg_if_player( _( "You open the door." ) );
    } else {
        p.add_msg_if_player( _( "Never mind." ) );
    }
}
References _, player::add_msg_if_player(), flag_OPENCLOSE_INSIDE(), g, get_map(), map::has_flag(), map::is_outside(), locked_object(), map::open_door(), and Character::pos().
Referenced by iexamine_function_from_string().
egg_sack_generic()
void iexamine::egg_sack_generic (player & p, const tripoint & examp, const mtype_id & montype)
Spawn spiders from a spider egg sack in radius 1 around the egg sack.
Transforms the egg sack furniture into a ruptured egg sack (f_egg_sacke). Also spawns eggs.
Parameters
p The player
examp Location of egg sack
montype The monster type of the created spiders.
Definition at line 2172 of file iexamine.cpp.
{
    map &here = get_map();
    const std::string old_furn_name = here.furnname( examp );
    if( !query_yn( _( "Harvest the %s?" ), old_furn_name ) ) {
        none( p, examp );
        return;
    }
    here.furn_set( examp, f_egg_sacke );
    int monster_count = 0;
    if( one_in( 2 ) ) {
        for( const tripoint &nearby_pos : closest_points_first( examp, 1 ) ) {
            if( !one_in( 3 ) ) {
                continue;
            } else if( g->place_critter_at( montype, nearby_pos ) ) {
                monster_count++;
            }
        }
    }
    int roll = rng( 4, 20 );
    bool drop_eggs = monster_count >= 1;
    for( int i = 0; i < roll; i++ ) {
        handle_harvest( p, "spider_egg", drop_eggs );
    }
    if( monster_count == 1 ) {
        add_msg( m_warning, _( "A spiderling bursts from the %s!" ), old_furn_name );
    } else if( monster_count >= 1 ) {
        add_msg( m_warning, _( "Spiderlings burst from the %s!" ), old_furn_name );
    }
}
References _, add_msg(), closest_points_first(), f_egg_sacke, map::furn_set(), map::furnname(), g, get_map(), handle_harvest(), m_warning, none, one_in(), query_yn(), and rng().
Referenced by egg_sackbw(), egg_sackcs(), and egg_sackws().
egg_sackbw()
void iexamine::egg_sackbw (player & p, const tripoint & examp)
Definition at line 2204 of file iexamine.cpp.
{
    egg_sack_generic( p, examp, mon_spider_widow_giant_s );
}
References egg_sack_generic(), and mon_spider_widow_giant_s.
Referenced by iexamine_function_from_string().
egg_sackcs()
void iexamine::egg_sackcs (player & p, const tripoint & examp)
Definition at line 2209 of file iexamine.cpp.
{
    egg_sack_generic( p, examp, mon_spider_cellar_giant_s );
}
References egg_sack_generic(), and mon_spider_cellar_giant_s.
Referenced by iexamine_function_from_string().
egg_sackws()
void iexamine::egg_sackws (player & p, const tripoint & examp)
Definition at line 2214 of file iexamine.cpp.
{
    egg_sack_generic( p, examp, mon_spider_web_s );
}
References egg_sack_generic(), and mon_spider_web_s.
Referenced by iexamine_function_from_string().
elevator()
void iexamine::elevator (player & p, const tripoint & examp)
If underground, move 2 levels up else move 2 levels down.
Stable movement between levels 0 and -2.
Definition at line 882 of file iexamine.cpp.
{
    map &here = get_map();
    if( !query_yn( _( "Use the %s?" ), here.tername( examp ) ) ) {
        return;
    }
    int movez = ( examp.z < 0 ? 2 : -2 );
    tripoint original_floor_omt = ms_to_omt_copy( here.getabs( examp ) );
    tripoint new_floor_omt = original_floor_omt + tripoint( point_zero, movez );
    // first find critters in the destination elevator and move them out of the way
    for( Creature &critter : g->all_creatures() ) {
        if( critter.is_player() ) {
            continue;
        } else if( here.has_flag( flag_ELEVATOR, critter.pos() ) ) {
            tripoint critter_omt = ms_to_omt_copy( here.getabs( critter.pos() ) );
            if( critter_omt == new_floor_omt ) {
                for( const tripoint &candidate : closest_points_first( critter.pos(), 10 ) ) {
                    if( !here.has_flag( flag_ELEVATOR, candidate ) &&
                        here.passable( candidate ) &&
                        !g->critter_at( candidate ) ) {
                        critter.setpos( candidate );
                        break;
                    }
                }
            }
        }
    }
    // TODO: do we have struct or pair to indicate from -> to?
    const auto move_item = [&]( map_stack & items, const tripoint & src, const tripoint & dest ) {
        for( auto it = items.begin(); it != items.end(); ) {
            here.add_item_or_charges( dest, *it );
            it = here.i_rem( src, it );
        }
    };
    const auto first_elevator_tile = [&]( const tripoint & pos ) -> tripoint {
        for( const tripoint &candidate : closest_points_first( pos, 10 ) )
        {
            if( here.has_flag( flag_ELEVATOR, candidate ) ) {
                return candidate;
            }
        }
        return pos;
    };
    // move along every item in the elevator
    for( const tripoint &pos : closest_points_first( p.pos(), 10 ) ) {
        if( here.has_flag( flag_ELEVATOR, pos ) ) {
            map_stack items = here.i_at( pos );
            tripoint dest = first_elevator_tile( pos + tripoint( 0, 0, movez ) );
            move_item( items, pos, dest );
        }
    }
    // move the player
    g->vertical_move( movez, false );
    // finally, bring along everyone who was in the elevator with the player
    for( Creature &critter : g->all_creatures() ) {
        if( critter.is_player() ) {
            continue;
        } else if( here.has_flag( flag_ELEVATOR, critter.pos() ) ) {
            tripoint critter_omt = ms_to_omt_copy( here.getabs( critter.pos() ) );
            if( critter_omt == original_floor_omt ) {
                for( const tripoint &candidate : closest_points_first( p.pos(), 10 ) ) {
                    if( here.has_flag( flag_ELEVATOR, candidate ) &&
                        candidate != p.pos() &&
                        !g->critter_at( candidate ) ) {
                        critter.setpos( candidate );
                        break;
                    }
                }
            }
        }
    }
}
References _, map::add_item_or_charges(), item_stack::begin(), closest_points_first(), item_stack::end(), flag_ELEVATOR(), g, get_map(), map::getabs(), map::has_flag(), map::i_at(), map::i_rem(), move_item(), ms_to_omt_copy(), map::passable(), point_zero, Character::pos(), query_yn(), map::tername(), and tripoint::z.
Referenced by iexamine_function_from_string().
fault()
void iexamine::fault (player & p, const tripoint & examp)
Display popup with reference to "The Enigma of Amigara Fault.".
Definition at line 1615 of file iexamine.cpp.
{
    popup( _( "This wall is perfectly vertical.  Odd, twisted holes are set in it, leading\n"
              "as far back into the solid rock as you can see.  The holes are humanoid in\n"
              "shape, but with long, twisted, distended limbs." ) );
}
References _, and popup().
Referenced by iexamine_function_from_string(), and avatar_funcs::mend_item().
fertilize_plant()
void iexamine::fertilize_plant (player & p, const tripoint & tile, const itype_id & fertilizer)
Definition at line 2476 of file iexamine.cpp.
{
    ret_val<bool> can_fert = can_fertilize( p, tile, fertilizer );
    if( !can_fert.success() ) {
        debugmsg( can_fert.str() );
        return;
    }
    std::list<item> planted = p.use_charges( fertilizer, 1 );
    // Reduce the amount of time it takes until the next stage of the plant by
    // 20% of a seasons length. (default 2.8 days).
    const time_duration fertilizerEpoch = calendar::season_length() * 0.2;
    map &here = get_map();
    // Can't use item_stack::only_item() since there might be fertilizer
    map_stack items = here.i_at( tile );
    const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
        return it.is_seed();
    } );
    if( seed == items.end() ) {
        debugmsg( "Missing seed for plant at (%d, %d, %d)", tile.x, tile.y, tile.z );
        here.i_clear( tile );
        here.furn_set( tile, f_null );
        return;
    }
    // TODO: item should probably clamp the value on its own
    seed->set_birthday( seed->birthday() - fertilizerEpoch );
    // The plant furniture has the NOITEM token which prevents adding items on that square,
    // spawned items are moved to an adjacent field instead, but the fertilizer token
    // must be on the square of the plant, therefore this hack:
    const auto old_furn = here.furn( tile );
    here.furn_set( tile, f_null );
    here.spawn_item( tile, itype_fertilizer, 1, 1, calendar::turn );
    here.furn_set( tile, old_furn );
    p.mod_moves( -to_moves<int>( 10_seconds ) );
    //~ %1$s: plant name, %2$s: fertilizer name
    add_msg( m_info, _( "You fertilize the %1$s with the %2$s." ), seed->get_plant_name(),
             planted.front().tname() );
}
References _, add_msg(), item_stack::begin(), can_fertilize(), debugmsg, item_stack::end(), f_null, map::furn(), map::furn_set(), get_map(), map::i_at(), map::i_clear(), itype_fertilizer, m_info, Creature::mod_moves(), calendar::season_length(), iuse::seed(), map::spawn_item(), ret_val< T >::str(), ret_val< T >::success(), calendar::turn, Character::use_charges(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by aggie_plant(), and activity_handlers::fertilize_plot_do_turn().
fireplace()
void iexamine::fireplace (player & p, const tripoint & examp)
Definition at line 2916 of file iexamine.cpp.
{
    map &here = get_map();
    const bool already_on_fire = here.has_nearby_fire( examp, 0 );
    const bool furn_is_deployed = !here.furn( examp ).obj().deployed_item.is_empty();
    std::multimap<int, item *> firestarters;
    for( item *it : p.items_with( []( const item & it ) {
    return it.has_flag( flag_FIRESTARTER ) || it.has_flag( flag_FIRE );
    } ) ) {
        const auto usef = it->type->get_use( "firestarter" );
        if( usef != nullptr && usef->get_actor_ptr() != nullptr ) {
            const auto actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
            if( actor->can_use( p, *it, false, examp ).success() ) {
                firestarters.insert( std::pair<int, item *>( actor->moves_cost_fast, it ) );
            }
        }
    }
    const bool has_firestarter = !firestarters.empty();
    const bool has_bionic_firestarter = p.has_bionic( bio_lighter ) &&
                                        p.enough_power_for( bio_lighter );
    uilist selection_menu;
    selection_menu.text = _( "Select an action" );
    selection_menu.addentry( 0, true, 'g', _( "Get items" ) );
    if( !already_on_fire ) {
        selection_menu.addentry( 1, has_firestarter, 'f',
                                 has_firestarter ? _( "Start a fire" ) : _( "Start a fire you'll need a fire source." ) );
        if( has_bionic_firestarter ) {
            selection_menu.addentry( 2, true, 'b', _( "Use a CBM to start a fire" ) );
        }
    } else {
        selection_menu.addentry( 4, true, 'e', _( "Extinguish fire" ) );
    }
    if( furn_is_deployed ) {
        selection_menu.addentry( 3, true, 't', _( "Take down the %s" ), here.furnname( examp ) );
    }
    selection_menu.query();
    switch( selection_menu.ret ) {
        case 0:
            none( p, examp );
            pickup::pick_up( examp, 0 );
            return;
        case 1: {
            for( auto &firestarter : firestarters ) {
                item *it = firestarter.second;
                const auto usef = it->type->get_use( "firestarter" );
                const auto actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
                p.add_msg_if_player( _( "You attempt to start a fire with your %s" ), it->tname() );
                const ret_val<bool> can_use = actor->can_use( p, *it, false, examp );
                if( can_use.success() ) {
                    const int charges = actor->use( p, *it, false, examp );
                    p.use_charges( it->typeId(), charges );
                    return;
                } else {
                    p.add_msg_if_player( m_bad, can_use.str() );
                }
            }
            p.add_msg_if_player( _( "You weren't able to start a fire." ) );
            return;
        }
        case 2: {
            if( !here.get_field( examp, fd_fire ) && here.add_field( examp, fd_fire, 1 ) ) {
                p.mod_power_level( -bio_lighter->power_activate );
                p.mod_moves( -to_moves<int>( 1_seconds ) );
            } else {
                p.add_msg_if_player( m_info, _( "You can't light a fire there." ) );
            }
            return;
        }
        case 3: {
            if( already_on_fire ) {
                if( !query_yn( _( "Really take down the %s while it's on fire?" ), here.furnname( examp ) ) ) {
                    return;
                }
            }
            p.add_msg_if_player( m_info, _( "You take down the %s." ),
                                 here.furnname( examp ) );
            const auto furn_item = here.furn( examp ).obj().deployed_item;
            here.add_item_or_charges( examp, item( furn_item, calendar::turn ) );
            here.furn_set( examp, f_null );
            return;
        }
        case 4: {
            here.remove_field( examp, fd_fire );
            p.mod_moves( -200 );
            p.add_msg_if_player( m_info, _( "With a few determined moves you put out the fire in the %s." ),
                                 here.furnname( examp ) );
            return;
        }
        default:
            none( p, examp );
            return;
    }
}
References _, map::add_field(), map::add_item_or_charges(), player::add_msg_if_player(), uilist::addentry(), bio_lighter, furn_t::deployed_item, Character::enough_power_for(), f_null, fd_fire, map::furn(), map::furn_set(), map::furnname(), map::get_field(), get_map(), itype::get_use(), Character::has_bionic(), map::has_nearby_fire(), string_id< T >::is_empty(), visitable< T >::items_with(), m_bad, m_info, Creature::mod_moves(), Character::mod_power_level(), none, int_id< T >::obj(), pickup::pick_up(), bionic_data::power_activate, uilist::query(), query_yn(), map::remove_field(), uilist::ret, ret_val< T >::str(), ret_val< T >::success(), uilist::text, item::tname(), calendar::turn, item::type, item::typeId(), and Character::use_charges().
Referenced by game::examine(), and iexamine_function_from_string().
flower_bluebell()
void iexamine::flower_bluebell (player & p, const tripoint & examp)
flower_cactus()
void iexamine::flower_cactus (player & p, const tripoint & examp)
Prompt pick cactus pad.
Not safe for player.
Definition at line 1971 of file iexamine.cpp.
{
    if( dead_plant( true, p, examp ) ) {
        return;
    }
    map &here = get_map();
    if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
        none( p, examp );
        return;
    }
    if( one_in( 6 ) ) {
        add_msg( m_bad, _( "The cactus' nettles sting you!" ) );
        p.apply_damage( nullptr, bodypart_id( "arm_l" ), 4 );
        p.apply_damage( nullptr, bodypart_id( "arm_r" ), 4 );
    }
    here.furn_set( examp, f_null );
    handle_harvest( p, "cactus_pad", false );
    handle_harvest( p, "seed_cactus", false );
}
References _, add_msg(), Character::apply_damage(), dead_plant(), f_null, map::furn_set(), map::furnname(), get_map(), handle_harvest(), m_bad, none, one_in(), and query_yn().
Referenced by iexamine_function_from_string().
flower_dahlia()
void iexamine::flower_dahlia (player & p, const tripoint & examp)
Dig up its roots or drink its nectar if you can.
Definition at line 1998 of file iexamine.cpp.
{
    if( dead_plant( true, p, examp ) ) {
        return;
    }
    if( drink_nectar( p ) ) {
        return;
    }
    map &here = get_map();
    bool can_get_root = p.has_quality( qual_DIG ) || p.has_trait( trait_BURROW );
    if( can_get_root ) {
        if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
            none( p, examp );
            return;
        }
    } else {
        if( !query_yn( _( "You don't have a digging tool to dig up roots.  Pick %s anyway?" ),
                       here.furnname( examp ) ) ) {
            none( p, examp );
            return;
        }
    }
    here.furn_set( examp, f_null );
    if( can_get_root ) {
        handle_harvest( p, "dahlia_root", false );
    }
    handle_harvest( p, "seed_dahlia", false );
    handle_harvest( p, "withered", false );
    // There was a bud and flower spawn here
    // But those were useless, don't re-add until they get useful
}
References _, dead_plant(), drink_nectar(), f_null, map::furn_set(), map::furnname(), get_map(), handle_harvest(), visitable< T >::has_quality(), Character::has_trait(), none, qual_DIG, query_yn(), and trait_BURROW.
Referenced by iexamine_function_from_string().
flower_marloss()
void iexamine::flower_marloss (player & p, const tripoint & examp)
Definition at line 2138 of file iexamine.cpp.
{
    if( season_of_year( calendar::turn ) == WINTER ) {
        add_msg( m_info, _( "This flower is still alive, despite the harsh conditions" ) );
    }
    map &here = get_map();
    item nectar( "nectar" );
    if( can_drink_nectar( p, nectar ) ) {
        if( !query_yn( _( "You feel out of place as you explore the %s. Drink?" ),
                       here.furnname( examp ) ) ) {
            return;
        }
        p.moves -= to_moves<int>( 30_seconds ); // Takes 30 seconds
        add_msg( m_bad, _( "This flower tastes very wrong" ) );
        // If you can drink flowers, you're post-thresh and the Mycus does not want you.
        p.add_effect( effect_teleglow, 10_minutes );
    }
    if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
        none( p, examp );
        return;
    }
    here.furn_set( examp, f_null );
    here.spawn_item( p.pos(), itype_marloss_seed, 1, 3, calendar::turn );
    handle_harvest( p, "withered", false );
}
References _, Creature::add_effect(), add_msg(), can_drink_nectar(), effect_teleglow, f_null, map::furn_set(), map::furnname(), get_map(), handle_harvest(), itype_marloss_seed, m_bad, m_info, Creature::moves, none, Character::pos(), query_yn(), season_of_year(), map::spawn_item(), calendar::turn, and WINTER.
Referenced by iexamine_function_from_string().
flower_poppy()
void iexamine::flower_poppy (player & p, const tripoint & examp)
Prompt pick (or drink nectar if able) poppy bud.
Not safe for player.
Drinking causes: -25 hunger, +20 fatigue, pkill2-70 effect and, 1 in 20 pkiller-1 addiction. Picking w/ env_resist < 5 causes 1 in 3 sleep for 12 min and 4 dmg to each leg
Definition at line 1912 of file iexamine.cpp.
{
    if( dead_plant( true, p, examp ) ) {
        return;
    }
    map &here = get_map();
    // TODO: Get rid of this section and move it to eating
    // Two y/n prompts is just too much
    item poppy( "nectar", calendar::turn, 1 );
    if( can_drink_nectar( p, poppy ) ) {
        if( !query_yn( _( "You feel woozy as you explore the %s. Drink?" ),
                       here.furnname( examp ) ) ) {
            return;
        }
        p.moves -= to_moves<int>( 30_seconds ); // You take your time...
        add_msg( _( "You slowly suck up the nectar." ) );
        p.eat( poppy );
        p.mod_fatigue( 20 );
        p.add_effect( effect_pkill2, 7_minutes );
        // Please drink poppy nectar responsibly.
        if( one_in( 20 ) ) {
            p.add_addiction( add_type::PKILLER, 1 );
        }
    }
    if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
        none( p, examp );
        return;
    }
    int resist = p.get_env_resist( bodypart_id( "mouth" ) );
    if( resist < 10 ) {
        // Can't smell the flowers with a gas mask on!
        add_msg( m_warning, _( "This flower has a heady aroma." ) );
    }
    auto recentWeather = sum_conditions( calendar::turn - 10_minutes, calendar::turn, p.pos() );
    // If it has been raining recently, then this event is twice less likely.
    if( ( ( recentWeather.rain_amount > 1 ) ? one_in( 6 ) : one_in( 3 ) ) && resist < 5 ) {
        // Should user player::infect, but can't!
        // player::infect needs to be restructured to return a bool indicating success.
        add_msg( m_bad, _( "You fall asleep" ) );
        p.fall_asleep( 2_hours );
        add_msg( m_bad, _( "Your legs are covered in the poppy's roots!" ) );
        p.apply_damage( nullptr, bodypart_id( "leg_l" ), 4 );
        p.apply_damage( nullptr, bodypart_id( "leg_r" ), 4 );
        p.moves -= 50;
    }
    here.furn_set( examp, f_null );
    handle_harvest( p, "poppy_bud", false );
    handle_harvest( p, "withered", false );
}
References _, Character::add_addiction(), Creature::add_effect(), add_msg(), Character::apply_damage(), can_drink_nectar(), dead_plant(), Character::eat(), effect_pkill2, f_null, Character::fall_asleep(), map::furn_set(), map::furnname(), Character::get_env_resist(), get_map(), handle_harvest(), m_bad, m_warning, Character::mod_fatigue(), Creature::moves, none, one_in(), PKILLER, Character::pos(), query_yn(), sum_conditions(), and calendar::turn.
Referenced by iexamine_function_from_string().
flower_spurge()
void iexamine::flower_spurge (player & p, const tripoint & examp)
flower_tulip()
void iexamine::flower_tulip (player & p, const tripoint & examp)
fswitch()
void iexamine::fswitch (player & p, const tripoint & examp)
Definition at line 1777 of file iexamine.cpp.
{
    map &here = get_map();
    if( !query_yn( _( "Flip the %s?" ), here.tername( examp ) ) ) {
        none( p, examp );
        return;
    }
    ter_id terid = here.ter( examp );
    p.moves -= to_moves<int>( 1_seconds );
    tripoint tmp;
    tmp.z = examp.z;
    for( tmp.y = examp.y; tmp.y <= examp.y + 5; tmp.y++ ) {
        for( tmp.x = 0; tmp.x < MAPSIZE_X; tmp.x++ ) {
            if( terid == t_switch_rg ) {
                if( here.ter( tmp ) == t_rock_red ) {
                    here.ter_set( tmp, t_floor_red );
                } else if( here.ter( tmp ) == t_floor_red ) {
                    here.ter_set( tmp, t_rock_red );
                } else if( here.ter( tmp ) == t_rock_green ) {
                    here.ter_set( tmp, t_floor_green );
                } else if( here.ter( tmp ) == t_floor_green ) {
                    here.ter_set( tmp, t_rock_green );
                }
            } else if( terid == t_switch_gb ) {
                if( here.ter( tmp ) == t_rock_blue ) {
                    here.ter_set( tmp, t_floor_blue );
                } else if( here.ter( tmp ) == t_floor_blue ) {
                    here.ter_set( tmp, t_rock_blue );
                } else if( here.ter( tmp ) == t_rock_green ) {
                    here.ter_set( tmp, t_floor_green );
                } else if( here.ter( tmp ) == t_floor_green ) {
                    here.ter_set( tmp, t_rock_green );
                }
            } else if( terid == t_switch_rb ) {
                if( here.ter( tmp ) == t_rock_blue ) {
                    here.ter_set( tmp, t_floor_blue );
                } else if( here.ter( tmp ) == t_floor_blue ) {
                    here.ter_set( tmp, t_rock_blue );
                } else if( here.ter( tmp ) == t_rock_red ) {
                    here.ter_set( tmp, t_floor_red );
                } else if( here.ter( tmp ) == t_floor_red ) {
                    here.ter_set( tmp, t_rock_red );
                }
            } else if( terid == t_switch_even ) {
                if( ( tmp.y - examp.y ) % 2 == 1 ) {
                    if( here.ter( tmp ) == t_rock_red ) {
                        here.ter_set( tmp, t_floor_red );
                    } else if( here.ter( tmp ) == t_floor_red ) {
                        here.ter_set( tmp, t_rock_red );
                    } else if( here.ter( tmp ) == t_rock_green ) {
                        here.ter_set( tmp, t_floor_green );
                    } else if( here.ter( tmp ) == t_floor_green ) {
                        here.ter_set( tmp, t_rock_green );
                    } else if( here.ter( tmp ) == t_rock_blue ) {
                        here.ter_set( tmp, t_floor_blue );
                    } else if( here.ter( tmp ) == t_floor_blue ) {
                        here.ter_set( tmp, t_rock_blue );
                    }
                }
            }
        }
    }
    add_msg( m_warning, _( "You hear the rumble of rock shifting." ) );
    g->timed_events.add( TIMED_EVENT_TEMPLE_SPAWN, calendar::turn + 3_turns );
}
References _, add_msg(), g, get_map(), m_warning, MAPSIZE_X, Creature::moves, none, query_yn(), t_floor_blue, t_floor_green, t_floor_red, t_rock_blue, t_rock_green, t_rock_red, t_switch_even, t_switch_gb, t_switch_rb, t_switch_rg, map::ter(), map::ter_set(), map::tername(), TIMED_EVENT_TEMPLE_SPAWN, calendar::turn, tripoint::x, tripoint::y, and tripoint::z.
Referenced by iexamine_function_from_string().
fungus()
void iexamine::fungus (player & p, const tripoint & examp)
Remove furniture.
Add spore effect.
Definition at line 2222 of file iexamine.cpp.
{
    map &here = get_map();
    add_msg( _( "The %s crumbles into spores!" ), here.furnname( examp ) );
    fungal_effects( *g, here ).create_spores( examp, &p );
    here.furn_set( examp, f_null );
    p.moves -= 50;
}
References _, add_msg(), fungal_effects::create_spores(), f_null, map::furn_set(), map::furnname(), g, get_map(), and Creature::moves.
Referenced by colorized_ter_name_flags_at(), mattack::fungus_corporate(), harvest_plant(), iexamine_function_from_string(), and game::walk_move().
fvat_empty()
void iexamine::fvat_empty (player & p, const tripoint & examp)
Definition at line 3014 of file iexamine.cpp.
{
    itype_id brew_type;
    std::string brew_nname;
    bool to_deposit = false;
    static const auto vat_volume = units::from_liter( 50 );
    bool vat_full = false;
    bool ferment = false;
    bool brew_present = false;
    int charges_on_ground = 0;
    map &here = get_map();
    auto items = here.i_at( examp );
    for( auto item_it = items.begin(); item_it != items.end(); ) {
        if( !item_it->is_brewable() || brew_present ) {
            // This isn't a brew or there was already another kind of brew inside,
            // so this has to be moved.
            items.insert( *item_it );
            // This will add items to a space near the vat, because it's flagged as NOITEM.
            item_it = items.erase( item_it );
        } else {
            item_it++;
            brew_present = true;
        }
    }
    if( !brew_present ) {
        add_msg( _( "This keg is empty." ) );
        // TODO: Allow using brews from crafting inventory
        const auto b_inv = p.items_with( []( const item & it ) {
            return it.is_brewable();
        } );
        if( b_inv.empty() ) {
            add_msg( m_info, _( "You have no brew to ferment." ) );
            return;
        }
        // Make lists of unique typeids and names for the menu
        // Code shamelessly stolen from the crop planting function!
        std::vector<itype_id> b_types;
        std::vector<std::string> b_names;
        for( auto &b : b_inv ) {
            if( std::find( b_types.begin(), b_types.end(), b->typeId() ) == b_types.end() ) {
                b_types.push_back( b->typeId() );
                b_names.push_back( item::nname( b->typeId() ) );
            }
        }
        // Choose brew from list
        int b_index = 0;
        if( b_types.size() > 1 ) {
            b_index = uilist( _( "Use which brew?" ), b_names );
        } else { //Only one brew type was in inventory, so it's automatically used
            if( !query_yn( _( "Set %s in the vat?" ), b_names[0] ) ) {
                b_index = -1;
            }
        }
        if( b_index < 0 ) {
            return;
        }
        to_deposit = true;
        brew_type = b_types[b_index];
        brew_nname = item::nname( brew_type );
    } else {
        item &brew = here.i_at( examp ).only_item();
        brew_type = brew.typeId();
        brew_nname = item::nname( brew_type );
        charges_on_ground = brew.charges;
        add_msg( _( "This keg contains %s (%d), %0.f%% full." ),
                 brew.tname(), brew.charges, brew.volume() * 100.0 / vat_volume );
        enum options { ADD_BREW, REMOVE_BREW, START_FERMENT };
        uilist selectmenu;
        selectmenu.text = _( "Select an action" );
        selectmenu.addentry( ADD_BREW, ( p.charges_of( brew_type ) > 0 ), MENU_AUTOASSIGN,
                             _( "Add more %s to the vat" ), brew_nname );
        selectmenu.addentry( REMOVE_BREW, brew.made_of( LIQUID ), MENU_AUTOASSIGN,
                             _( "Remove %s from the vat" ), brew.tname() );
        selectmenu.addentry( START_FERMENT, true, MENU_AUTOASSIGN, _( "Start fermenting cycle" ) );
        selectmenu.query();
        switch( selectmenu.ret ) {
            case ADD_BREW: {
                to_deposit = true;
                break;
            }
            case REMOVE_BREW: {
                liquid_handler::handle_liquid_from_ground( here.i_at( examp ).begin(), examp );
                return;
            }
            case START_FERMENT: {
                ferment = true;
                break;
            }
            default:
                add_msg( _( "Never mind." ) );
                return;
        }
    }
    if( to_deposit ) {
        item brew( brew_type, calendar::start_of_cataclysm );
        int charges_held = p.charges_of( brew_type );
        brew.charges = charges_on_ground;
        for( int i = 0; i < charges_held && !vat_full; i++ ) {
            p.use_charges( brew_type, 1 );
            brew.charges++;
            if( brew.volume() >= vat_volume ) {
                vat_full = true;
            }
        }
        add_msg( _( "Set %s in the vat." ), brew_nname );
        add_msg( _( "The keg now contains %s (%d), %0.f%% full." ),
                 brew.tname(), brew.charges, brew.volume() * 100.0 / vat_volume );
        here.i_clear( examp );
        //This is needed to bypass NOITEM
        here.add_item( examp, brew );
        p.moves -= to_moves<int>( 20_seconds );
        if( !vat_full ) {
            ferment = query_yn( _( "Start fermenting cycle?" ) );
        }
    }
    if( vat_full || ferment ) {
        here.i_at( examp ).only_item().set_age( 0_turns );
        here.furn_set( examp, f_fvat_full );
        if( vat_full ) {
            add_msg( _( "The vat is full, so you close the lid and start the fermenting cycle." ) );
        } else {
            add_msg( _( "You close the lid and start the fermenting cycle." ) );
        }
    }
}
References _, map::add_item(), add_msg(), uilist::addentry(), b, item_stack::begin(), item::charges, visitable< T >::charges_of(), f_fvat_full, detail::find(), units::from_liter(), map::furn_set(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), map::i_clear(), map_stack::insert(), item::is_brewable(), visitable< T >::items_with(), LIQUID, m_info, item::made_of(), MENU_AUTOASSIGN, Creature::moves, item::nname(), item_stack::only_item(), PATH_INFO::options(), uilist::query(), query_yn(), uilist::ret, item::set_age(), calendar::start_of_cataclysm, uilist::text, item::tname(), item::typeId(), Character::use_charges(), and item::volume().
Referenced by iexamine_function_from_string().
fvat_full()
void iexamine::fvat_full (player & p, const tripoint & examp)
Definition at line 3140 of file iexamine.cpp.
{
    map &here = get_map();
    map_stack items_here = here.i_at( examp );
    if( items_here.empty() ) {
        debugmsg( "fvat_full was empty!" );
        here.furn_set( examp, f_fvat_empty );
        return;
    }
    for( item &it : items_here ) {
        if( !it.made_of( LIQUID ) ) {
            add_msg( _( "You remove %s from the vat." ), it.tname() );
            here.add_item_or_charges( p.pos(), it );
            here.i_rem( examp, &it );
        }
    }
    if( items_here.empty() ) {
        here.furn_set( examp, f_fvat_empty );
        return;
    }
    item &brew_i = *items_here.begin();
    // Does the vat contain unfermented brew, or already fermented booze?
    // TODO: Allow "recursive brewing" to continue without player having to check on it
    if( brew_i.is_brewable() ) {
        add_msg( _( "There's a vat of %s set to ferment there." ), brew_i.tname() );
        // TODO: change brew_time to return time_duration
        const time_duration brew_time = brew_i.brewing_time();
        const time_duration progress = brew_i.age();
        if( progress < brew_time ) {
            int hours = to_hours<int>( brew_time - progress );
            if( hours < 1 ) {
                add_msg( _( "It will finish brewing in less than an hour." ) );
            } else {
                add_msg( vgettext( "It will finish brewing in about %d hour.",
                                   "It will finish brewing in about %d hours.",
                                   hours ), hours );
            }
            return;
        }
        if( query_yn( _( "Finish brewing?" ) ) ) {
            const auto results = brew_i.brewing_results();
            here.i_clear( examp );
            for( const auto &result : results ) {
                // TODO: Different age based on settings
                item booze( result, brew_i.birthday(), brew_i.charges );
                here.add_item( examp, booze );
                if( booze.made_of( LIQUID ) ) {
                    add_msg( _( "The %s is now ready for bottling." ), booze.tname() );
                }
            }
            p.moves -= to_moves<int>( 5_seconds );
            p.practice( skill_cooking, std::min( to_minutes<int>( brew_time ) / 10, 100 ) );
        }
        return;
    } else {
        add_msg( _( "There's a vat of fermented %s there." ), brew_i.tname() );
    }
    const std::string booze_name = brew_i.tname();
    if( liquid_handler::handle_liquid_from_ground( items_here.begin(), examp ) ) {
        here.furn_set( examp, f_fvat_empty );
        add_msg( _( "You squeeze the last drops of %s from the vat." ), booze_name );
    }
}
References _, map::add_item(), map::add_item_or_charges(), add_msg(), item::age(), item_stack::begin(), item::birthday(), item::brewing_results(), item::brewing_time(), item::charges, debugmsg, item_stack::empty(), f_fvat_empty, map::furn_set(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), map::i_clear(), map::i_rem(), item::is_brewable(), LIQUID, item::made_of(), Creature::moves, Character::pos(), Character::practice(), query_yn(), skill_cooking, item::tname(), and vgettext().
Referenced by activity_handlers::fill_liquid_do_turn(), and iexamine_function_from_string().
gaspump()
void iexamine::gaspump (player & p, const tripoint & examp)
Use "gas pump." Will pump any liquids on tile.
Dexterity decreases chance of spilling gas from a pump Dexterity decreases amount of gas spilled from a pump
Definition at line 355 of file iexamine.cpp.
{
    map &here = get_map();
    if( !query_yn( _( "Use the %s?" ), here.tername( examp ) ) ) {
        none( p, examp );
        return;
    }
    auto items = here.i_at( examp );
    for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
        if( item_it->made_of( LIQUID ) ) {
            ///\EFFECT_DEX decreases chance of spilling gas from a pump
            if( one_in( 10 + p.get_dex() ) ) {
                add_msg( m_bad, _( "You accidentally spill the %s." ), item_it->type_name() );
                static const auto max_spill_volume = units::from_liter( 1 );
                const int max_spill_charges = std::max( 1, item_it->charges_per_volume( max_spill_volume ) );
                ///\EFFECT_DEX decreases amount of gas spilled from a pump
                const int qty = rng( 1, max_spill_charges * 8.0 / std::max( 1, p.get_dex() ) );
                item spill = item_it->split( qty );
                if( spill.is_null() ) {
                    here.add_item_or_charges( p.pos(), *item_it );
                    items.erase( item_it );
                } else {
                    here.add_item_or_charges( p.pos(), spill );
                }
            } else {
                liquid_handler::handle_liquid_from_ground( item_it, examp, 1 );
            }
            return;
        }
    }
    add_msg( m_info, _( "Out of order." ) );
}
References _, map::add_item_or_charges(), add_msg(), units::from_liter(), Character::get_dex(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), item::is_null(), LIQUID, m_bad, m_info, none, one_in(), Character::pos(), query_yn(), rng(), item::split(), and map::tername().
Referenced by activity_handlers::fill_liquid_do_turn(), and iexamine_function_from_string().
get_harvest_items()
std::list< item > iexamine::get_harvest_items (const itype & type, int plant_count, int seed_count, bool byproducts)
Items that appear when a generic plant is harvested.
Seed islot_seed.
Parameters
type The seed type, must have a itype::seed slot.
plant_count Number of fruits to generate. For charge-based items, this specifies multiples of the default charge.
seed_count Number of seeds to generate.
byproducts If true, byproducts (like straw, withered plants, see islot_seed::byproducts) are included.
Definition at line 2347 of file iexamine.cpp.
{
    std::list<item> result;
    if( !type.seed ) {
        return result;
    }
    const islot_seed &seed_data = *type.seed;
    // This is a temporary measure, itype should instead provide appropriate accessors
    // to expose data about the seed item to allow harvesting to function.
    const itype_id &seed_type = type.get_id();
    const auto add = [&]( const itype_id & id, const int count ) {
        item new_item( id, calendar::turn );
        if( new_item.count_by_charges() && count > 0 ) {
            new_item.charges *= count;
            new_item.charges /= seed_data.fruit_div;
            if( new_item.charges <= 0 ) {
                new_item.charges = 1;
            }
            result.push_back( new_item );
        } else if( count > 0 ) {
            result.insert( result.begin(), count, new_item );
        }
    };
    if( seed_data.spawn_seeds ) {
        add( seed_type, seed_count );
    }
    add( seed_data.fruit_id, plant_count );
    if( byproducts ) {
        for( auto &b : seed_data.byproducts ) {
            add( b, 1 );
        }
    }
    return result;
}
References om_direction::add(), b, islot_seed::byproducts, item::charges, detail::count(), item::count_by_charges(), islot_seed::fruit_div, islot_seed::fruit_id, int_id< T >::id(), islot_seed::spawn_seeds, calendar::turn, and type.
Referenced by farm_action(), harvest_plant(), and vehicle::operate_reaper().
get_seed_entries()
std::vector< seed_tuple > iexamine::get_seed_entries (const std::vector< item * > & seed_inv)
Make lists of unique seed types and names for the menu(no multiple hemp seeds etc)
Definition at line 2234 of file iexamine.cpp.
{
    std::map<itype_id, int> seed_map;
    for( auto &seed : seed_inv ) {
        seed_map[seed->typeId()] += ( seed->charges > 0 ? seed->charges : 1 );
    }
    std::vector<seed_tuple> seed_entries;
    seed_entries.reserve( seed_map.size() );
    for( const auto &pr : seed_map ) {
        seed_entries.emplace_back(
            pr.first, item::nname( pr.first, pr.second ), pr.second );
    }
    // Sort by name
    std::sort( seed_entries.begin(), seed_entries.end(),
    []( const seed_tuple & l, const seed_tuple & r ) {
        return std::get<1>( l ).compare( std::get<1>( r ) ) < 0;
    } );
    return seed_entries;
}
References item::nname(), and iuse::seed().
Referenced by dirtmound(), plot_options::query_seed(), and vehicle::reload_seeds().
getGasPumpByNumber()
cata::optional< tripoint > iexamine::getGasPumpByNumber (const tripoint & p, int number)
Definition at line 4354 of file iexamine.cpp.
{
    map &here = get_map();
    int k = 0;
    for( const tripoint &tmp : here.points_in_radius( p, 12 ) ) {
        const auto t = here.ter( tmp );
        if( ( t == ter_str_id( "t_gas_pump" ) || t == ter_str_id( "t_gas_pump_a" ) ) && number == k++ ) {
            return tmp;
        }
    }
    return cata::nullopt;
}
References get_map(), cata::nullopt, map::points_in_radius(), and map::ter().
Referenced by hacking_activity_actor::finish(), and pay_gas().
getNearFilledGasTank()
cata::optional< tripoint > iexamine::getNearFilledGasTank (const tripoint & center, int & gas_units)
Definition at line 4245 of file iexamine.cpp.
{
    map &here = get_map();
    cata::optional<tripoint> tank_loc;
    int distance = INT_MAX;
    gas_units = 0;
    for( const tripoint &tmp : here.points_in_radius( center, SEEX * 2 ) ) {
        if( here.ter( tmp ) != ter_str_id( "t_gas_tank" ) ) {
            continue;
        }
        const int new_distance = rl_dist( center, tmp );
        if( new_distance >= distance ) {
            continue;
        }
        if( !tank_loc ) {
            // Return a potentially empty tank, but only if we don't find a closer full one.
            tank_loc.emplace( tmp );
        }
        for( auto &k : here.i_at( tmp ) ) {
            if( k.made_of( LIQUID ) ) {
                distance = new_distance;
                tank_loc.emplace( tmp );
                gas_units = k.charges;
                break;
            }
        }
    }
    return tank_loc;
}
References center, cata::optional< T >::emplace(), get_map(), map::i_at(), LIQUID, map::points_in_radius(), rl_dist(), SEEX, and map::ter().
Referenced by hacking_activity_actor::finish(), and pay_gas().
gunsafe_el()
void iexamine::gunsafe_el (player & p, const tripoint & examp)
Attempt to "hack" the gunsafe's electronic lock and open it.
Definition at line 1461 of file iexamine.cpp.
{
    if( query_yn( _( "Attempt to hack this safe?" ) ) ) {
        try_start_hacking( p, examp );
    }
}
References _, query_yn(), and try_start_hacking().
Referenced by get_hack_type(), and iexamine_function_from_string().
harvest_furn()
void iexamine::harvest_furn (player & p, const tripoint & examp)
Definition at line 2097 of file iexamine.cpp.
{
    bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                       get_option<std::string>( "AUTO_FORAGING" ) == "both";
    if( harvest_common( p, examp, true, false, auto_forage ) ) {
        get_map().furn_set( examp, f_null );
    }
}
References f_null, map::furn_set(), get_map(), and harvest_common().
Referenced by iexamine_function_from_string(), and game::place_player().
harvest_furn_nectar()
void iexamine::harvest_furn_nectar (player & p, const tripoint & examp)
Definition at line 2088 of file iexamine.cpp.
{
    bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                       get_option<std::string>( "AUTO_FORAGING" ) == "both";
    if( harvest_common( p, examp, true, true, auto_forage ) ) {
        get_map().furn_set( examp, f_null );
    }
}
References f_null, map::furn_set(), get_map(), and harvest_common().
Referenced by iexamine_function_from_string(), and game::place_player().
harvest_plant()
void iexamine::harvest_plant (player & p, const tripoint & examp, bool from_activity = false)
Actual harvesting of selected plant.
Survival increases number of plants harvested from a seed
Definition at line 2391 of file iexamine.cpp.
{
    map &here = get_map();
    // Can't use item_stack::only_item() since there might be fertilizer
    map_stack items = here.i_at( examp );
    const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
        return it.is_seed();
    } );
    if( seed == items.end() ) {
        debugmsg( "Missing seed for plant at (%d, %d, %d)", examp.x, examp.y, examp.z );
        here.i_clear( examp );
        here.furn_set( examp, f_null );
        return;
    }
    const itype_id &seedType = seed->typeId();
    if( seedType == itype_fungal_seeds ) {
        fungus( p, examp );
        here.i_clear( examp );
    } else if( seedType == itype_marloss_seed ) {
        fungus( p, examp );
        here.i_clear( examp );
        if( p.has_trait( trait_M_DEPENDENT ) && ( p.get_kcal_percent() < 0.8f ||
                p.get_thirst() > thirst_levels::very_thirsty ) ) {
            here.ter_set( examp, t_marloss );
            add_msg( m_info,
                     _( "We have altered this unit's configuration to extract and provide local nutriment.  The Mycus provides." ) );
        } else if( ( p.has_trait( trait_M_DEFENDER ) ) || ( ( p.has_trait( trait_M_SPORES ) ||
                   p.has_trait( trait_M_FERTILE ) ) &&
                   one_in( 2 ) ) ) {
            g->place_critter_at( mon_fungal_blossom, examp );
            add_msg( m_info, _( "The seed blooms forth!  We have brought true beauty to this world." ) );
        } else if( ( p.has_trait( trait_THRESH_MYCUS ) ) || one_in( 4 ) ) {
            here.furn_set( examp, f_flower_marloss );
            add_msg( m_info, _( "The seed blossoms rather rapidly" ) );
        } else {
            here.furn_set( examp, f_flower_fungal );
            add_msg( m_info, _( "The seed blossoms into a flower-looking fungus." ) );
        }
    } else { // Generic seed, use the seed item data
        const itype &type = *seed->type;
        here.i_clear( examp );
        int skillLevel = p.get_skill_level( skill_survival );
        ///\EFFECT_SURVIVAL increases number of plants harvested from a seed
        int plant_count = rng( skillLevel / 2, skillLevel );
        plant_count *= here.furn( examp )->plant->harvest_multiplier;
        const int max_harvest_count = get_option<int>( "MAX_HARVEST_COUNT" );
        if( plant_count >= max_harvest_count ) {
            plant_count = max_harvest_count;
        } else if( plant_count <= 0 ) {
            plant_count = 1;
        }
        const int seedCount = std::max( 1, rng( plant_count / 4, plant_count / 2 ) );
        for( auto &i : get_harvest_items( type, plant_count, seedCount, true ) ) {
            if( from_activity ) {
                i.set_var( "activity_var", p.name );
            }
            here.add_item_or_charges( examp, i );
        }
        here.furn_set( examp, furn_str_id( here.furn( examp )->plant->transform ) );
        p.moves -= to_moves<int>( 10_seconds );
    }
}
References _, map::add_item_or_charges(), add_msg(), item_stack::begin(), debugmsg, item_stack::end(), f_flower_fungal, f_flower_marloss, f_null, fungus(), map::furn(), map::furn_set(), g, get_harvest_items(), Character::get_kcal_percent(), get_map(), Character::get_skill_level(), Character::get_thirst(), Character::has_trait(), map::i_at(), map::i_clear(), itype_fungal_seeds, itype_marloss_seed, m_info, mon_fungal_blossom, Creature::moves, Character::name, one_in(), furn_t::plant, rng(), iuse::seed(), skill_survival, t_marloss, map::ter_set(), trait_M_DEFENDER, trait_M_DEPENDENT, trait_M_FERTILE, trait_M_SPORES, trait_THRESH_MYCUS, type, very_thirsty, tripoint::x, tripoint::y, and tripoint::z.
Referenced by aggie_plant(), and generic_multi_activity_do().
harvest_ter()
void iexamine::harvest_ter (player & p, const tripoint & examp)
Definition at line 2118 of file iexamine.cpp.
{
    bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                       ( get_option<std::string>( "AUTO_FORAGING" ) == "both" ||
                         get_option<std::string>( "AUTO_FORAGING" ) == "trees" );
    if( harvest_common( p, examp, false, false, auto_forage ) ) {
        map &here = get_map();
        here.ter_set( examp, here.get_ter_transforms_into( examp ) );
    }
}
References get_map(), map::get_ter_transforms_into(), harvest_common(), and map::ter_set().
Referenced by iexamine_function_from_string(), and game::place_player().
harvest_ter_nectar()
void iexamine::harvest_ter_nectar (player & p, const tripoint & examp)
Definition at line 2106 of file iexamine.cpp.
{
    bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                       ( get_option<std::string>( "AUTO_FORAGING" ) == "both" ||
                         get_option<std::string>( "AUTO_FORAGING" ) == "bushes" ||
                         get_option<std::string>( "AUTO_FORAGING" ) == "trees" );
    if( harvest_common( p, examp, false, true, auto_forage ) ) {
        map &here = get_map();
        here.ter_set( examp, here.get_ter_transforms_into( examp ) );
    }
}
References get_map(), map::get_ter_transforms_into(), harvest_common(), and map::ter_set().
Referenced by iexamine_function_from_string(), and game::place_player().
harvested_plant()
void iexamine::harvested_plant (player & p, const tripoint & examp)
Only harvest a plant once per season.
Display message and call iexamine::none.
Definition at line 2132 of file iexamine.cpp.
{
    p.add_msg_if_player( m_info, _( "Nothing can be harvested from this plant in current season" ) );
    iexamine::none( p, examp );
}
References _, player::add_msg_if_player(), m_info, and none().
Referenced by iexamine_function_from_string().
has_keg()
bool iexamine::has_keg (const tripoint & pos)
Check whether there is a keg on the map that can be filled via pour_into_keg.
Definition at line 3222 of file iexamine.cpp.
{
    return get_keg_capacity( pos ) > 0_ml;
}
References get_keg_capacity().
Referenced by activity_handlers::fill_liquid_do_turn(), and liquid_handler::get_liquid_target().
intercom()
void iexamine::intercom (player & p, const tripoint & examp)
Definition at line 1118 of file iexamine.cpp.
{
    const std::vector<npc *> intercom_npcs = g->get_npcs_if( [examp]( const npc & guy ) {
        return guy.myclass == npc_class_id( "NC_ROBOFAC_INTERCOM" ) && rl_dist( guy.pos(), examp ) < 10;
    } );
    if( intercom_npcs.empty() ) {
        p.add_msg_if_player( m_info, _( "No one responds." ) );
    } else {
        intercom_npcs.front()->talk_to_u( false );
    }
}
References _, player::add_msg_if_player(), g, m_info, npc::myclass, Character::pos(), and rl_dist().
Referenced by cardreader_robofac(), and iexamine_function_from_string().
keg()
void iexamine::keg (player & p, const tripoint & examp)
Definition at line 3253 of file iexamine.cpp.
{
    none( p, examp );
    map &here = get_map();
    const auto keg_name = here.name( examp );
    units::volume keg_cap = get_keg_capacity( examp );
    const bool has_container_with_liquid = map_cursor( examp ).has_item_with( []( const item & it ) {
        return !it.is_container_empty() && it.can_unload_liquid();
    } );
    const bool liquid_present = map_cursor( examp ).has_item_with( []( const item & it ) {
        return it.made_of( LIQUID );
    } );
    if( !liquid_present || has_container_with_liquid ) {
        add_msg( m_info, _( "It is empty." ) );
        // Get list of all drinks
        auto drinks_inv = p.items_with( []( const item & it ) {
            return it.made_of( LIQUID );
        } );
        if( drinks_inv.empty() ) {
            add_msg( m_info, _( "You don't have any drinks to fill the %s with." ), keg_name );
            return;
        }
        // Make lists of unique drinks... about third time we do this, maybe we ought to make a function next time
        std::vector<itype_id> drink_types;
        std::vector<std::string> drink_names;
        std::vector<double> drink_rot;
        for( auto &drink : drinks_inv ) {
            auto found_drink = std::find( drink_types.begin(), drink_types.end(), drink->typeId() );
            if( found_drink == drink_types.end() ) {
                drink_types.push_back( drink->typeId() );
                drink_names.push_back( item::nname( drink->typeId() ) );
                drink_rot.push_back( drink->get_relative_rot() );
            } else {
                auto rot_iter = std::next( drink_rot.begin(), std::distance( drink_types.begin(), found_drink ) );
                // Yep, worst rot wins.
                *rot_iter = std::max( *rot_iter, drink->get_relative_rot() );
            }
        }
        // Choose drink to store in keg from list
        int drink_index = 0;
        if( drink_types.size() > 1 ) {
            drink_index = uilist( _( "Store which drink?" ), drink_names );
            if( drink_index < 0 || static_cast<size_t>( drink_index ) >= drink_types.size() ) {
                drink_index = -1;
            }
        } else { //Only one drink type was in inventory, so it's automatically used
            if( !query_yn( _( "Fill the %1$s with %2$s?" ),
                           keg_name, drink_names[0].c_str() ) ) {
                drink_index = -1;
            }
        }
        if( drink_index < 0 ) {
            return;
        }
        // First empty the keg of foreign objects
        displace_items_except_one_liquid( examp );
        //Store liquid chosen in the keg
        itype_id drink_type = drink_types[ drink_index ];
        int charges_held = p.charges_of( drink_type );
        item drink( drink_type, calendar::start_of_cataclysm );
        drink.set_relative_rot( drink_rot[ drink_index ] );
        drink.charges = 0;
        bool keg_full = false;
        for( int i = 0; i < charges_held && !keg_full; i++ ) {
            g->u.use_charges( drink.typeId(), 1 );
            drink.charges++;
            keg_full = drink.volume() >= keg_cap;
        }
        if( keg_full ) {
            add_msg( _( "You completely fill the %1$s with %2$s." ),
                     keg_name, item::nname( drink_type ) );
        } else {
            add_msg( _( "You fill the %1$s with %2$s." ),
                     keg_name, item::nname( drink_type ) );
        }
        p.moves -= to_moves<int>( 10_seconds );
        here.i_clear( examp );
        here.add_item( examp, drink );
        return;
    } else {
        // First empty the keg of foreign objects
        displace_items_except_one_liquid( examp );
        map_stack items = here.i_at( examp );
        item &drink = items.only_item();
        const std::string drink_tname = drink.tname();
        const std::string drink_nname = item::nname( drink.typeId() );
        enum options {
            DISPENSE,
            HAVE_A_DRINK,
            REFILL,
            EXAMINE,
        };
        uilist selectmenu;
        selectmenu.addentry( DISPENSE, drink.made_of( LIQUID ), MENU_AUTOASSIGN,
                             _( "Dispense or dump %s" ), drink_tname );
        selectmenu.addentry( HAVE_A_DRINK, drink.is_food() && drink.made_of( LIQUID ),
                             MENU_AUTOASSIGN, _( "Have a drink" ) );
        selectmenu.addentry( REFILL, true, MENU_AUTOASSIGN, _( "Refill" ) );
        selectmenu.addentry( EXAMINE, true, MENU_AUTOASSIGN, _( "Examine" ) );
        selectmenu.text = _( "Select an action" );
        selectmenu.query();
        switch( selectmenu.ret ) {
            case DISPENSE:
                if( liquid_handler::handle_liquid_from_ground( items.begin(), examp ) ) {
                    add_msg( _( "You squeeze the last drops of %1$s from the %2$s." ),
                             drink_tname, keg_name );
                }
                return;
            case HAVE_A_DRINK:
                if( !p.eat( drink ) ) {
                    return; // They didn't actually drink
                }
                if( drink.charges == 0 ) {
                    add_msg( _( "You squeeze the last drops of %1$s from the %2$s." ),
                             drink_tname, keg_name );
                    here.i_clear( examp );
                }
                p.moves -= to_moves<int>( 5_seconds );
                return;
            case REFILL: {
                if( drink.volume() >= keg_cap ) {
                    add_msg( _( "The %s is completely full." ), keg_name );
                    return;
                }
                int charges_held = p.charges_of( drink.typeId() );
                if( charges_held < 1 ) {
                    add_msg( m_info, _( "You don't have any %1$s to fill the %2$s with." ),
                             drink_nname, keg_name );
                    return;
                }
                item tmp( drink.typeId(), calendar::turn, charges_held );
                pour_into_keg( examp, tmp );
                p.use_charges( drink.typeId(), charges_held - tmp.charges );
                add_msg( _( "You fill the %1$s with %2$s." ), keg_name, drink_nname );
                p.moves -= to_moves<int>( 10_seconds );
                return;
            }
            case EXAMINE: {
                add_msg( m_info, _( "It contains %s (%d), %0.f%% full." ),
                         drink_tname, drink.charges, drink.volume() * 100.0 / keg_cap );
                return;
            }
            default:
                return;
        }
    }
}
References _, map::add_item(), add_msg(), uilist::addentry(), item_stack::begin(), item::can_unload_liquid(), item::charges, visitable< T >::charges_of(), displace_items_except_one_liquid(), Character::eat(), detail::find(), g, get_keg_capacity(), get_map(), liquid_handler::handle_liquid_from_ground(), visitable< T >::has_item_with(), map::i_at(), map::i_clear(), item::is_container_empty(), item::is_food(), visitable< T >::items_with(), LIQUID, m_info, item::made_of(), MENU_AUTOASSIGN, Creature::moves, map::name(), item::nname(), none, item_stack::only_item(), PATH_INFO::options(), pour_into_keg(), uilist::query(), query_yn(), uilist::ret, item::set_relative_rot(), calendar::start_of_cataclysm, uilist::text, item::tname(), calendar::turn, item::typeId(), Character::use_charges(), and item::volume().
Referenced by iexamine_function_from_string().
kiln_empty()
void iexamine::kiln_empty (player & p, const tripoint & examp)
Fabrication decreases loss when firing a kiln
Definition at line 2587 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_kiln_type = here.furn( examp );
    furn_id next_kiln_type = f_null;
    if( cur_kiln_type == f_kiln_empty ) {
        next_kiln_type = f_kiln_full;
    } else if( cur_kiln_type == f_kiln_metal_empty ) {
        next_kiln_type = f_kiln_metal_full;
    } else {
        debugmsg( "Examined furniture has action kiln_empty, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    static const std::set<material_id> kilnable{ material_id( "wood" ), material_id( "bone" ) };
    bool fuel_present = false;
    auto items = here.i_at( examp );
    for( const item &i : items ) {
        if( i.typeId() == itype_charcoal ) {
            add_msg( _( "This kiln already contains charcoal." ) );
            add_msg( _( "Remove it before firing the kiln again." ) );
            return;
        } else if( i.made_of_any( kilnable ) ) {
            fuel_present = true;
        } else {
            add_msg( m_bad, _( "This kiln contains %s, which can't be made into charcoal!" ), i.tname( 1,
                     false ) );
            return;
        }
    }
    if( !fuel_present ) {
        add_msg( _( "This kiln is empty.  Fill it with wood or bone and try again." ) );
        return;
    }
    ///\EFFECT_FABRICATION decreases loss when firing a kiln
    const int skill = p.get_skill_level( skill_fabrication );
    int loss = 60 - 2 *
               skill; // We can afford to be inefficient - logs and skeletons are cheap, charcoal isn't
    // Burn stuff that should get charred, leave out the rest
    units::volume total_volume = 0_ml;
    for( const item &i : items ) {
        total_volume += i.volume();
    }
    units::volume char_volume = ( 100 - loss ) * total_volume / 100;
    int char_charges = itype_unfinished_charcoal->charges_per_volume( char_volume );
    if( char_charges < 1 ) {
        add_msg( _( "The batch in this kiln is too small to yield any charcoal." ) );
        return;
    }
    if( !p.has_charges( itype_fire, 1 ) ) {
        add_msg( _( "This kiln is ready to be fired, but you have no fire source." ) );
        return;
    } else {
        add_msg( _( "This kiln contains %s %s of material, and is ready to be fired." ),
                 format_volume( total_volume ), volume_units_abbr() );
        if( !query_yn( _( "Fire the kiln?" ) ) ) {
            return;
        }
    }
    p.use_charges( itype_fire, 1 );
    here.i_clear( examp );
    here.furn_set( examp, next_kiln_type );
    item result( itype_unfinished_charcoal, calendar::turn );
    result.charges = char_charges;
    here.add_item( examp, result );
    add_msg( _( "You fire the charcoal kiln." ) );
}
References _, map::add_item(), add_msg(), string_id< T >::c_str(), itype::charges_per_volume(), debugmsg, f_kiln_empty, f_kiln_full, f_kiln_metal_empty, f_kiln_metal_full, f_null, format_volume(), map::furn(), map::furn_set(), get_map(), Character::get_skill_level(), Character::has_charges(), map::i_at(), map::i_clear(), int_id< T >::id(), itype_charcoal, itype_fire, itype_unfinished_charcoal, m_bad, query_yn(), skill_fabrication, calendar::turn, Character::use_charges(), and volume_units_abbr().
Referenced by iexamine_function_from_string().
kiln_full()
void iexamine::kiln_full (player & p, const tripoint & examp)
Definition at line 2662 of file iexamine.cpp.
{
    map &here = get_map();
    furn_id cur_kiln_type = here.furn( examp );
    furn_id next_kiln_type = f_null;
    if( cur_kiln_type == f_kiln_full ) {
        next_kiln_type = f_kiln_empty;
    } else if( cur_kiln_type == f_kiln_metal_full ) {
        next_kiln_type = f_kiln_metal_empty;
    } else {
        debugmsg( "Examined furniture has action kiln_full, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    map_stack items = here.i_at( examp );
    if( items.empty() ) {
        add_msg( _( "This kiln is empty" ) );
        here.furn_set( examp, next_kiln_type );
        return;
    }
    add_msg( _( "There's a charcoal kiln there." ) );
    const time_duration firing_time = 6_hours; // 5 days in real life
    const time_duration time_left = firing_time - items.only_item().age();
    if( time_left > 0_turns ) {
        int hours = to_hours<int>( time_left );
        int minutes = to_minutes<int>( time_left ) + 1;
        if( minutes > 60 ) {
            add_msg( vgettext( "It will finish burning in about %d hour.",
                               "It will finish burning in about %d hours.",
                               hours ), hours );
        } else if( minutes > 30 ) {
            add_msg( _( "It will finish burning in less than an hour." ) );
        } else {
            add_msg( _( "It should take about %d minutes to finish burning." ), minutes );
        }
        return;
    }
    units::volume total_volume = 0_ml;
    // Burn stuff that should get charred, leave out the rest
    for( auto item_it = items.begin(); item_it != items.end(); ) {
        if( item_it->typeId() == itype_unfinished_charcoal || item_it->typeId() == itype_charcoal ) {
            total_volume += item_it->volume();
            item_it = items.erase( item_it );
        } else {
            item_it++;
        }
    }
    item result( itype_charcoal, calendar::turn );
    result.charges = itype_charcoal->charges_per_volume( total_volume );
    here.add_item( examp, result );
    here.furn_set( examp, next_kiln_type );
    add_msg( _( "It has finished burning, yielding %d charcoal." ), result.charges );
}
References _, map::add_item(), add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), itype::charges_per_volume(), debugmsg, item_stack::empty(), item_stack::end(), map_stack::erase(), f_kiln_empty, f_kiln_full, f_kiln_metal_empty, f_kiln_metal_full, f_null, map::furn(), map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), itype_charcoal, itype_unfinished_charcoal, item_stack::only_item(), calendar::turn, and vgettext().
Referenced by iexamine_function_from_string().
ledge()
void iexamine::ledge (player & p, const tripoint & examp)
Definition at line 4607 of file iexamine.cpp.
{
    uilist cmenu;
    cmenu.text = _( "There is a ledge here.  What do you want to do?" );
    cmenu.addentry( 1, true, 'j', _( "Jump over." ) );
    cmenu.addentry( 2, true, 'c', _( "Climb down." ) );
    if( p.has_trait( trait_WEB_BRDIGE ) ) {
        cmenu.addentry( 3, true, 'w', _( "Spin Web Bridge." ) );
    }
    cmenu.query();
    map &here = get_map();
    switch( cmenu.ret ) {
        case 1: {
            tripoint dest( p.posx() + 2 * sgn( examp.x - p.posx() ), p.posy() + 2 * sgn( examp.y - p.posy() ),
                           p.posz() );
            if( p.get_str() < 4 ) {
                add_msg( m_warning, _( "You are too weak to jump over an obstacle." ) );
            } else if( 100 * p.weight_carried() / p.weight_capacity() > 25 ) {
                add_msg( m_warning, _( "You are too burdened to jump over an obstacle." ) );
            } else if( !here.valid_move( examp, dest, false, true ) ) {
                add_msg( m_warning, _( "You cannot jump over an obstacle - something is blocking the way." ) );
            } else if( g->critter_at( dest ) ) {
                add_msg( m_warning, _( "You cannot jump over an obstacle - there is %s blocking the way." ),
                         g->critter_at( dest )->disp_name() );
            } else if( here.ter( dest ).obj().trap == tr_ledge ) {
                add_msg( m_warning, _( "You are not going to jump over an obstacle only to fall down." ) );
            } else {
                add_msg( m_info, _( "You jump over an obstacle." ) );
                p.setpos( dest );
            }
            break;
        }
        case 2: {
            tripoint where = examp;
            tripoint below = examp;
            below.z--;
            while( here.valid_move( where, below, false, true ) ) {
                where.z--;
                below.z--;
            }
            const int height = examp.z - where.z;
            if( height == 0 ) {
                p.add_msg_if_player( _( "You can't climb down there." ) );
                return;
            }
            const bool has_grapnel = p.has_amount( itype_grapnel, 1 );
            const int climb_cost = map_funcs::climbing_cost( here, where, examp );
            const auto fall_mod = p.fall_damage_mod();
            std::string query_str = vgettext( "Looks like %d story.  Jump down?",
                                              "Looks like %d stories.  Jump down?",
                                              height );
            if( height > 1 && !query_yn( query_str.c_str(), height ) ) {
                return;
            } else if( height == 1 ) {
                std::string query;
                if( !has_grapnel ) {
                    if( climb_cost <= 0 && fall_mod > 0.8 ) {
                        query = _( "You probably won't be able to get up and jumping down may hurt.  Jump?" );
                    } else if( climb_cost <= 0 ) {
                        query = _( "You probably won't be able to get back up.  Climb down?" );
                    } else if( climb_cost < 200 ) {
                        query = _( "You should be able to climb back up easily if you climb down there.  Climb down?" );
                    } else {
                        query = _( "You may have problems climbing back up.  Climb down?" );
                    }
                } else {
                    query = _( "Use your grappling hook to climb down?" );
                }
                if( !query_yn( query.c_str() ) ) {
                    return;
                }
            }
            p.moves -= to_moves<int>( 1_seconds + 1_seconds * fall_mod );
            p.setpos( examp );
            if( has_grapnel ) {
                p.add_msg_if_player( _( "You tie the rope around your waist and begin to climb down." ) );
            }
            if( climb_cost > 0 || rng_float( 0.8, 1.0 ) > fall_mod ) {
                // One tile of falling less (possibly zero)
                g->vertical_move( -1, true );
            }
            here.creature_on_trap( p );
            break;
        }
        case 3: {
            if( !can_use_mutation_warn( trait_WEB_BRDIGE, p ) ) {
                break;
            }
            const int range = 6; //this means we could web across a gap of 5.
            int success_range = 0;
            bool success = false;
            for( int i = 2; i <= range; i++ ) {
                //break at the first non empty space encountered
                if( g->m.ter( tripoint( p.posx() + i * sgn( examp.x - p.posx() ),
                                        p.posy() + i * sgn( examp.y - p.posy() ), p.posz() ) ) != t_open_air ) {
                    success_range = i;
                    success = true;
                    break;
                }
            }
            if( !success ) {
                p.add_msg_if_player( _( "There is nothing for your to attach your web to!" ) );
            } else {
                for( int i = 1; i < success_range; i++ ) {
                    tripoint dest( p.posx() + i * sgn( examp.x - p.posx() ), p.posy() + i * sgn( examp.y - p.posy() ),
                                   p.posz() );
                    g->m.ter_set( dest, t_web_bridge );
                }
                p.mutation_spend_resources( trait_WEB_BRDIGE );
            }
            break;
        }
        default:
            popup( _( "You decided to step back from the ledge." ) );
            break;
    }
}
References _, add_msg(), player::add_msg_if_player(), uilist::addentry(), can_use_mutation_warn(), map_funcs::climbing_cost(), map::creature_on_trap(), Character::fall_damage_mod(), g, get_map(), Character::get_str(), visitable< T >::has_amount(), Character::has_trait(), itype_grapnel, m_info, m_warning, Creature::moves, Character::mutation_spend_resources(), int_id< T >::obj(), popup(), Character::posx(), Character::posy(), Character::posz(), uilist::query(), query_yn(), uilist::ret, rng_float(), Character::setpos(), sgn(), behavior::success, t_open_air, t_web_bridge, map::ter(), uilist::text, tr_ledge, trait_WEB_BRDIGE, ter_t::trap, map::valid_move(), vgettext(), Character::weight_capacity(), Character::weight_carried(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by iexamine_function_from_string().
locked_object()
void iexamine::locked_object (player & p, const tripoint & examp)
Checks whether PC has a crowbar then calls iuse.crowbar.
Definition at line 1543 of file iexamine.cpp.
{
    map &here = get_map();
    safe_reference<item> prying_tool = find_best_prying_tool( p );
    if( prying_tool ) {
        apply_prying_tool( p, prying_tool.get(), examp );
        return;
    }
    // if the furniture/terrain is also lockpickable
    if( here.has_flag_ter_or_furn( "LOCKED", examp ) ) {
        safe_reference<item> lock_picking_tool = find_best_lock_picking_tool( p );
        if( lock_picking_tool ) {
            apply_lock_picking_tool( p, lock_picking_tool.get(), examp );
        } else {
            add_msg( m_info, _( "The %s is locked.  If only you had something to pry it or pick its lock" ),
                     here.has_furn( examp ) ? here.furnname( examp ) : here.tername( examp ) );
        }
        return;
    }
    add_msg( m_info, _( "The %s is locked.  If only you had something to pry it" ),
             here.has_furn( examp ) ? here.furnname( examp ) : here.tername( examp ) );
}
References _, add_msg(), apply_lock_picking_tool(), apply_prying_tool(), find_best_lock_picking_tool(), find_best_prying_tool(), map::furnname(), safe_reference< T >::get(), get_map(), map::has_flag_ter_or_furn(), map::has_furn(), m_info, and map::tername().
Referenced by curtains(), door_peephole(), and iexamine_function_from_string().
locked_object_pickable()
void iexamine::locked_object_pickable (player & p, const tripoint & examp)
Checks whether PC has picklocks then calls pick_lock_actor.
Definition at line 1572 of file iexamine.cpp.
{
    map &here = get_map();
    safe_reference<item> lock_picking_tool = find_best_lock_picking_tool( p );
    if( lock_picking_tool ) {
        apply_lock_picking_tool( p, lock_picking_tool.get(), examp );
        return;
    }
    add_msg( m_info, _( "The %s is locked.  If only you had something to pick its lock" ),
             here.has_furn( examp ) ? here.furnname( examp ) : here.tername( examp ) );
}
References _, add_msg(), apply_lock_picking_tool(), find_best_lock_picking_tool(), map::furnname(), safe_reference< T >::get(), get_map(), map::has_furn(), m_info, and map::tername().
Referenced by iexamine_function_from_string().
migo_nerve_cluster()
void iexamine::migo_nerve_cluster (player & p, const tripoint & examp)
Definition at line 6250 of file iexamine.cpp.
{
    map &here = get_map();
    if( query_yn( _( "This looks important.  Tear open nerve cluster?" ) ) ) {
        p.mod_moves( -200 );
        add_msg( _( "You grab hold of a sinewy tendril and wrench it loose!" ) );
        map_funcs::migo_nerve_cage_removal( here, examp, false );
        here.furn_set( examp, furn_id( "f_alien_scar" ) );
    }
}
References _, add_msg(), map::furn_set(), get_map(), map_funcs::migo_nerve_cage_removal(), Creature::mod_moves(), and query_yn().
Referenced by iexamine_function_from_string().
mill_finalize()
void iexamine::mill_finalize (player & , const tripoint & examp, const time_point & start_time)
Definition at line 5467 of file iexamine.cpp.
{
    map &here = get_map();
    const furn_id cur_mill_type = here.furn( examp );
    furn_id next_mill_type = f_null;
    if( cur_mill_type == f_wind_mill_active ) {
        next_mill_type = f_wind_mill;
    } else if( cur_mill_type == f_water_mill_active ) {
        next_mill_type = f_water_mill;
    } else {
        debugmsg( "Furniture executed action mill_finalize, but is of type %s",
                  here.furn( examp ).id().c_str() );
        return;
    }
    map_stack items = here.i_at( examp );
    if( items.empty() ) {
        here.furn_set( examp, next_mill_type );
        return;
    }
    for( item &it : items ) {
        if( it.type->milling_data ) {
            it.mod_last_rot_check( milling_time );
            const islot_milling &mdata = *it.type->milling_data;
            item result( mdata.into_, start_time + milling_time, it.count() * mdata.conversion_rate_ );
            result.components.push_back( it );
            // copied from item::inherit_flags, which can not be called here because it requires a recipe.
            for( const std::string &f : it.type->item_tags ) {
                if( json_flag::get( f ).craft_inherit() ) {
                    result.set_flag( f );
                }
            }
            result.recipe_charges = result.charges;
            // Set flag to tell set_relative_rot() to calc from bday not now
            result.set_flag( flag_PROCESSING_RESULT );
            result.set_relative_rot( it.get_relative_rot() );
            result.unset_flag( flag_PROCESSING_RESULT );
            it = result;
        }
    }
    here.furn_set( examp, next_mill_type );
}
References string_id< T >::c_str(), islot_milling::conversion_rate_, debugmsg, item_stack::empty(), f_null, f_water_mill, f_water_mill_active, f_wind_mill, f_wind_mill_active, flag_PROCESSING_RESULT(), map::furn(), map::furn_set(), json_flag::get(), get_map(), map::i_at(), int_id< T >::id(), islot_milling::into_, and milling_time.
Referenced by item::process_fake_mill().
nanofab()
void iexamine::nanofab (player & p, const tripoint & examp)
UI FOR LAB_FINALE NANO FABRICATOR.
Definition at line 300 of file iexamine.cpp.
{
    bool table_exists = false;
    tripoint spawn_point;
    map &here = get_map();
    for( const auto &valid_location : here.points_in_radius( examp, 1 ) ) {
        if( here.ter( valid_location ) == ter_str_id( "t_nanofab_body" ) ) {
            spawn_point = valid_location;
            table_exists = true;
            break;
        }
    }
    if( !table_exists ) {
        return;
    }
    auto nanofab_template = g->inv_map_splice( []( const item & e ) {
        return e.has_var( "NANOFAB_ITEM_ID" );
    }, _( "Introduce Nanofabricator template" ), PICKUP_RANGE,
    _( "You don't have any usable templates." ) );
    if( !nanofab_template ) {
        return;
    }
    item new_item( nanofab_template->get_var( "NANOFAB_ITEM_ID" ), calendar::turn );
    auto qty = std::max( 1, new_item.volume() / 250_ml );
    auto reqs = *requirement_id( "nanofabricator" ) * qty;
    if( !reqs.can_make_with_inventory( p.crafting_inventory(), is_crafting_component ) ) {
        popup( "%s", reqs.list_missing() );
        return;
    }
    // Consume materials
    for( const auto &e : reqs.get_components() ) {
        p.consume_items( e, 1, is_crafting_component );
    }
    for( const auto &e : reqs.get_tools() ) {
        p.consume_tools( e );
    }
    p.invalidate_crafting_inventory();
    if( new_item.is_armor() && new_item.has_flag( flag_VARSIZE ) ) {
        new_item.set_flag( "FIT" );
    }
    here.add_item_or_charges( spawn_point, new_item );
}
References _, map::add_item_or_charges(), player::consume_items(), player::consume_tools(), Character::crafting_inventory(), flag_VARSIZE(), g, get_map(), item::has_flag(), item::has_var(), Character::invalidate_crafting_inventory(), item::is_armor(), is_crafting_component(), PICKUP_RANGE, map::points_in_radius(), popup(), item::set_flag(), map::ter(), calendar::turn, and item::volume().
Referenced by iexamine_function_from_string().
none()
void iexamine::none (player & p, const tripoint & examp)
Nothing player can interact with here.
Definition at line 252 of file iexamine.cpp.
{
    add_msg( _( "That is a %s." ), get_map().name( examp ) );
}
References _, add_msg(), get_map(), and om_direction::name().
Referenced by can_examine_at(), map_data_common_t::check(), colorized_ter_name_flags_at(), dead_plant(), map::examine(), game::examine(), finalize_furn(), map::get_harvest(), map::get_harvest_names(), harvest_common(), harvested_plant(), iexamine_function_from_string(), pick_plant(), and game::place_player().
notify()
void iexamine::notify (player & p, const tripoint & pos)
Display popup message pulled from the object's message property.
Definition at line 1625 of file iexamine.cpp.
{
    std::string message = g->m.has_furn( pos ) ?
                          g->m.furn( pos ).obj().message :
                          g->m.ter( pos ).obj().message;
    if( !message.empty() ) {
        popup( _( message ) );
    }
}
References _, g, mapgen_defer::message, and popup().
Referenced by iexamine_function_from_string().
on_smoke_out()
void iexamine::on_smoke_out (const tripoint & examp, const time_point & start_time)
Definition at line 5783 of file iexamine.cpp.
{
    map &here = get_map();
    if( here.furn( examp ) == furn_str_id( "f_smoking_rack_active" ) ||
        here.furn( examp ) == furn_str_id( "f_metal_smoking_rack_active" ) ) {
        smoker_finalize( g->u, examp, start_time );
    }
}
References map::furn(), g, get_map(), and smoker_finalize().
Referenced by item::process_fake_smoke().
open_safe()
void iexamine::open_safe (player & p, const tripoint & examp)
Definition at line 6188 of file iexamine.cpp.
{
    add_msg( m_info, _( "You open the unlocked safe." ) );
    get_map().furn_set( examp, f_safe_o );
}
References _, add_msg(), f_safe_o, map::furn_set(), get_map(), and m_info.
Referenced by iexamine_function_from_string().
pay_gas()
void iexamine::pay_gas (player & p, const tripoint & examp)
Definition at line 4437 of file iexamine.cpp.
{
    int choice = -1;
    const int buy_gas = 1;
    const int choose_pump = 2;
    const int hack = 3;
    const int refund = 4;
    if( p.has_trait( trait_ILLITERATE ) ) {
        popup( _( "You're illiterate, and can't read the screen." ) );
    }
    int pumpCount = getNearPumpCount( examp );
    if( pumpCount == 0 ) {
        popup( str_to_illiterate_str( _( "Failure!  No gas pumps found!" ) ) );
        return;
    }
    int tankGasUnits;
    const cata::optional<tripoint> pTank_ = getNearFilledGasTank( examp, tankGasUnits );
    if( !pTank_ ) {
        popup( str_to_illiterate_str( _( "Failure!  No gas tank found!" ) ) );
        return;
    }
    const tripoint pTank = *pTank_;
    if( tankGasUnits == 0 ) {
        popup( str_to_illiterate_str(
                   _( "This station is out of fuel.  We apologize for the inconvenience." ) ) );
        return;
    }
    if( uistate.ags_pay_gas_selected_pump + 1 > pumpCount ) {
        uistate.ags_pay_gas_selected_pump = 0;
    }
    int discount = findBestGasDiscount( p );
    std::string discountName = getGasDiscountName( discount );
    int pricePerUnit = getGasPricePerLiter( discount );
    bool can_hack = ( !p.has_trait( trait_ILLITERATE ) &&
                      ( ( p.has_charges( itype_electrohack, 25 ) ) ||
                        ( p.has_bionic( bio_fingerhack ) && p.get_power_level() > 24_kJ ) ) );
    uilist amenu;
    amenu.selected = 1;
    amenu.text = str_to_illiterate_str( _( "Welcome to AutoGas!" ) );
    amenu.addentry( 0, false, -1, str_to_illiterate_str( _( "What would you like to do?" ) ) );
    amenu.addentry( buy_gas, true, 'b', str_to_illiterate_str( _( "Buy gas." ) ) );
    amenu.addentry( refund, true, 'r', str_to_illiterate_str( _( "Refund cash." ) ) );
    std::string gaspumpselected = str_to_illiterate_str( _( "Current gas pump: " ) ) +
                                  std::to_string( uistate.ags_pay_gas_selected_pump + 1 );
    amenu.addentry( 0, false, -1, gaspumpselected );
    amenu.addentry( choose_pump, true, 'p', str_to_illiterate_str( _( "Choose a gas pump." ) ) );
    amenu.addentry( 0, false, -1, str_to_illiterate_str( _( "Your discount: " ) ) + discountName );
    amenu.addentry( 0, false, -1, str_to_illiterate_str( _( "Your price per gasoline unit: " ) ) +
                    format_money( pricePerUnit ) );
    if( can_hack ) {
        amenu.addentry( hack, true, 'h', _( "Hack console." ) );
    }
    amenu.query();
    choice = amenu.ret;
    if( choose_pump == choice ) {
        uilist amenu;
        amenu.selected = uistate.ags_pay_gas_selected_pump;
        amenu.text = str_to_illiterate_str( _( "Please choose gas pump:" ) );
        for( int i = 0; i < pumpCount; i++ ) {
            amenu.addentry( i, true, -1,
                            str_to_illiterate_str( _( "Pump " ) ) + std::to_string( i + 1 ) );
        }
        amenu.query();
        choice = amenu.ret;
        if( choice < 0 ) {
            return;
        }
        uistate.ags_pay_gas_selected_pump = choice;
        turnOnSelectedPump( examp, uistate.ags_pay_gas_selected_pump );
        return;
    }
    if( buy_gas == choice ) {
        int money = p.charges_of( itype_cash_card );
        if( money < pricePerUnit ) {
            popup( str_to_illiterate_str(
                       _( "Not enough money, please refill your cash card." ) ) ); //or ride on a solar car, ha ha ha
            return;
        }
        int maximum_liters = std::min( money / pricePerUnit, tankGasUnits / 1000 );
        std::string popupmsg = string_format(
                                   _( "How many liters of gasoline to buy?  Max: %d L.  (0 to cancel)" ), maximum_liters );
        int liters = string_input_popup()
                     .title( popupmsg )
                     .width( 20 )
                     .text( std::to_string( maximum_liters ) )
                     .only_digits( true )
                     .query_int();
        if( liters <= 0 ) {
            return;
        }
        if( liters > maximum_liters ) {
            liters = maximum_liters;
        }
        const cata::optional<tripoint> pGasPump = getGasPumpByNumber( examp,
                uistate.ags_pay_gas_selected_pump );
        if( !pGasPump || !toPumpFuel( pTank, *pGasPump, liters * 1000 ) ) {
            return;
        }
        sounds::sound( p.pos(), 6, sounds::sound_t::activity, _( "Glug Glug Glug" ), true, "tool",
                       "gaspump" );
        int cost = liters * pricePerUnit;
        money -= cost;
        p.use_charges( itype_cash_card, cost );
        add_msg( m_info, _( "Your cash cards now hold %s." ), format_money( money ) );
        p.moves -= to_moves<int>( 5_seconds );
        return;
    }
    if( hack == choice ) {
        try_start_hacking( p, examp );
    }
    if( refund == choice ) {
        const int pos = p.inv.position_by_type( itype_id( "cash_card" ) );
        if( pos == INT_MIN ) {
            add_msg( _( "Never mind." ) );
            return;
        }
        item *cashcard = &( p.i_at( pos ) );
        // Okay, we have a cash card. Now we need to know what's left in the pump.
        const cata::optional<tripoint> pGasPump = getGasPumpByNumber( examp,
                uistate.ags_pay_gas_selected_pump );
        int amount = pGasPump ? fromPumpFuel( pTank, *pGasPump ) : 0;
        if( amount >= 0 ) {
            sounds::sound( p.pos(), 6, sounds::sound_t::activity, _( "Glug Glug Glug" ), true, "tool",
                           "gaspump" );
            cashcard->charges += amount * pricePerUnit / 1000.0f;
            add_msg( m_info, _( "Your cash cards now hold %s." ),
                     format_money( p.charges_of( itype_cash_card ) ) );
            p.moves -= to_moves<int>( 5_seconds );
            return;
        } else {
            popup( _( "Unable to refund, no fuel in pump." ) );
            return;
        }
    }
}
References _, sounds::activity, add_msg(), uilist::addentry(), uistatedata::ags_pay_gas_selected_pump, bio_fingerhack, item::charges, visitable< T >::charges_of(), findBestGasDiscount(), format_money(), fromPumpFuel(), Character::get_power_level(), getGasDiscountName(), getGasPricePerLiter(), getGasPumpByNumber(), getNearFilledGasTank(), getNearPumpCount(), Character::has_bionic(), Character::has_charges(), Character::has_trait(), Character::i_at(), Character::inv, itype_cash_card, itype_electrohack, m_info, Creature::moves, string_input_popup::only_digits(), popup(), Character::pos(), inventory::position_by_type(), uilist::query(), string_input_popup::query_int(), uilist::ret, uilist::selected, sounds::sound(), str_to_illiterate_str(), string_format(), string_input_popup::text(), uilist::text, string_input_popup::title(), to_string(), toPumpFuel(), trait_ILLITERATE, try_start_hacking(), turnOnSelectedPump(), uistate, Character::use_charges(), and string_input_popup::width().
Referenced by get_hack_type(), and iexamine_function_from_string().
pedestal_temple()
void iexamine::pedestal_temple (player & p, const tripoint & examp)
Put petrified eye on pedestal causing it to sink into ground and open temple.
Definition at line 1722 of file iexamine.cpp.
{
    map &here = get_map();
    map_stack items = here.i_at( examp );
    if( !items.empty() && items.only_item().typeId() == itype_petrified_eye ) {
        add_msg( _( "The pedestal sinks into the ground" ) );
        here.ter_set( examp, t_dirt );
        here.i_clear( examp );
        g->timed_events.add( TIMED_EVENT_TEMPLE_OPEN, calendar::turn + 10_seconds );
    } else if( p.has_amount( itype_petrified_eye, 1 ) &&
               query_yn( _( "Place your petrified eye on the pedestal?" ) ) ) {
        p.use_amount( itype_petrified_eye, 1 );
        add_msg( _( "The pedestal sinks into the ground" ) );
        here.ter_set( examp, t_dirt );
        g->timed_events.add( TIMED_EVENT_TEMPLE_OPEN, calendar::turn + 10_seconds );
    } else {
        add_msg( _( "This pedestal is engraved in eye-shaped diagrams, and has a "
                    "large semi-spherical indentation at the top." ) );
    }
}
References _, add_msg(), item_stack::empty(), g, get_map(), visitable< T >::has_amount(), map::i_at(), map::i_clear(), itype_petrified_eye, item_stack::only_item(), query_yn(), t_dirt, map::ter_set(), TIMED_EVENT_TEMPLE_OPEN, calendar::turn, item::typeId(), and Character::use_amount().
Referenced by iexamine_function_from_string().
pedestal_wyrm()
void iexamine::pedestal_wyrm (player & p, const tripoint & examp)
Spawn 1d4 wyrms and sink pedestal into ground.
Definition at line 1686 of file iexamine.cpp.
{
    map &here = get_map();
    map_stack items = here.i_at( examp );
    if( !items.empty() ) {
        if( items.only_item().typeId() == itype_petrified_eye &&
            query_yn( _( "Remove the petrified eye from the pedestal?" ) ) ) {
            here.i_clear( examp );
            item eye( itype_petrified_eye );
            p.i_add_or_drop( eye );
            // Send in a few wyrms to start things off.
            get_event_bus().send<event_type::awakes_dark_wyrms>();
            for( const tripoint &p : here.points_on_zlevel() ) {
                if( here.ter( p ) == ter_id( "t_orifice" ) ) {
                    g->place_critter_around( mon_dark_wyrm, p, 1 );
                }
            }
            sounds::sound( examp, 80, sounds::sound_t::combat, _( "an ominous grinding noise" ), true,
                           "misc", "stones_grinding" );
            add_msg( _( "The pedestal sinks into the ground" ) );
            here.ter_set( examp, t_rock_floor );
            g->timed_events.add( TIMED_EVENT_SPAWN_WYRMS, calendar::turn + rng( 30_seconds, 60_seconds ) );
        } else {
            none( p, examp );
            add_msg( _( "You decided to leave the petrified eye on the pedestal" ) );
            return;
        }
    }
}
References _, add_msg(), awakes_dark_wyrms, sounds::combat, item_stack::empty(), g, get_event_bus(), get_map(), Character::i_add_or_drop(), map::i_at(), map::i_clear(), itype_petrified_eye, mon_dark_wyrm, none, item_stack::only_item(), map::points_on_zlevel(), query_yn(), rng(), event_bus::send(), sounds::sound(), t_rock_floor, map::ter(), map::ter_set(), TIMED_EVENT_SPAWN_WYRMS, calendar::turn, and item::typeId().
Referenced by iexamine_function_from_string().
pit()
void iexamine::pit (player & p, const tripoint & examp)
If there is a 2x4 around, prompt placing it across pit.
Definition at line 1319 of file iexamine.cpp.
{
    const inventory &crafting_inv = p.crafting_inventory();
    if( !crafting_inv.has_amount( itype_2x4, 1 ) ) {
        none( p, examp );
        return;
    }
    std::vector<item_comp> planks;
    planks.push_back( item_comp( itype_2x4, 1 ) );
    map &here = get_map();
    if( query_yn( _( "Place a plank over the pit?" ) ) ) {
        p.consume_items( planks, 1, is_crafting_component );
        if( here.ter( examp ) == t_pit ) {
            here.ter_set( examp, t_pit_covered );
        } else if( here.ter( examp ) == t_pit_spiked ) {
            here.ter_set( examp, t_pit_spiked_covered );
        } else if( here.ter( examp ) == t_pit_glass ) {
            here.ter_set( examp, t_pit_glass_covered );
        }
        add_msg( _( "You place a plank of wood over the pit." ) );
        p.mod_moves( -to_turns<int>( 1_seconds ) );
    }
}
References _, add_msg(), player::consume_items(), Character::crafting_inventory(), get_map(), visitable< T >::has_amount(), is_crafting_component(), itype_2x4, Creature::mod_moves(), none, query_yn(), t_pit, t_pit_covered, t_pit_glass, t_pit_glass_covered, t_pit_spiked, t_pit_spiked_covered, map::ter(), and map::ter_set().
Referenced by iexamine_function_from_string(), and trapfunc::sinkhole().
pit_covered()
void iexamine::pit_covered (player & p, const tripoint & examp)
Prompt removing the 2x4 placed across the pit.
Definition at line 1347 of file iexamine.cpp.
{
    if( !query_yn( _( "Remove cover?" ) ) ) {
        none( p, examp );
        return;
    }
    map &here = get_map();
    item plank( "2x4", calendar::turn );
    add_msg( _( "You remove the plank." ) );
    here.add_item_or_charges( p.pos(), plank );
    if( here.ter( examp ) == t_pit_covered ) {
        here.ter_set( examp, t_pit );
    } else if( here.ter( examp ) == t_pit_spiked_covered ) {
        here.ter_set( examp, t_pit_spiked );
    } else if( here.ter( examp ) == t_pit_glass_covered ) {
        here.ter_set( examp, t_pit_glass );
    }
    p.mod_moves( -to_turns<int>( 1_seconds ) );
}
References _, map::add_item_or_charges(), add_msg(), get_map(), Creature::mod_moves(), none, Character::pos(), query_yn(), t_pit, t_pit_covered, t_pit_glass, t_pit_glass_covered, t_pit_spiked, t_pit_spiked_covered, map::ter(), map::ter_set(), and calendar::turn.
Referenced by iexamine_function_from_string().
plant_seed()
void iexamine::plant_seed (player & p, const tripoint & examp, const itype_id & seed_id)
Actual planting of selected seed.
Definition at line 2288 of file iexamine.cpp.
{
    player_activity act( ACT_PLANT_SEED, to_moves<int>( 30_seconds ) );
    act.placement = get_map().getabs( examp );
    act.str_values.emplace_back( seed_id );
    p.assign_activity( act );
}
References act, ACT_PLANT_SEED, Character::assign_activity(), get_map(), and map::getabs().
Referenced by dirtmound(), and generic_multi_activity_do().
portable_structure()
void iexamine::portable_structure (player & p, const tripoint & examp)
Determine structure's type and prompts its removal.
Definition at line 1272 of file iexamine.cpp.
{
    map &here = get_map();
    const furn_str_id fid = here.furn( examp ).id();
    const std::pair<itype_id, const deploy_tent_actor *> tent_item_type = find_tent_itype( fid );
    if( tent_item_type.first.is_null() ) {
        debugmsg( "unknown furniture %s: don't know how to transform it into an item", fid.str() );
        return;
    }
    itype_id dropped = tent_item_type.first;
    std::string name = item::nname( dropped );
    int radius;
    if( tent_item_type.second ) {
        const deploy_tent_actor &actor = *tent_item_type.second;
        if( !actor.check_intact( examp ) ) {
            if( !actor.broken_type ) {
                add_msg( _( "The %s is broken and can not be picked up." ), name );
                none( p, examp );
                return;
            }
            dropped = *actor.broken_type;
            name = string_format( _( "damaged %s" ), name );
        }
        radius = actor.radius;
    } else {
        radius = std::max( 1, fid->bash.collapse_radius );
    }
    if( !query_yn( _( "Take down the %s?" ), name ) ) {
        none( p, examp );
        return;
    }
    p.moves -= to_turns<int>( 2_seconds );
    for( const tripoint &pt : here.points_in_radius( examp, radius ) ) {
        here.furn_set( pt, f_null );
    }
    here.add_item_or_charges( examp, item( dropped, calendar::turn ) );
}
References _, map::add_item_or_charges(), add_msg(), map_data_common_t::bash, deploy_tent_actor::broken_type, deploy_tent_actor::check_intact(), map_bash_info::collapse_radius, debugmsg, f_null, find_tent_itype(), map::furn(), map::furn_set(), get_map(), int_id< T >::id(), Creature::moves, om_direction::name(), item::nname(), none, map::points_in_radius(), query_yn(), deploy_tent_actor::radius, string_id< T >::str(), string_format(), and calendar::turn.
Referenced by iexamine_function_from_string().
pour_into_keg()
bool iexamine::pour_into_keg (const tripoint & pos, item & liquid)
Pour liquid into a keg (furniture) on the map.
The transferred charges (if any) will be removed from the liquid item.
Returns
Whether any charges have been transferred at all.
Definition at line 3418 of file iexamine.cpp.
{
    const units::volume keg_cap = get_keg_capacity( pos );
    if( keg_cap <= 0_ml ) {
        return false;
    }
    map &here = get_map();
    const auto keg_name = here.name( pos );
    map_stack stack = here.i_at( pos );
    if( stack.empty() ) {
        here.add_item( pos, liquid );
        here.i_at( pos ).only_item().charges = 0; // Will be set later
    } else if( stack.only_item().typeId() != liquid.typeId() ) {
        add_msg( _( "The %s already contains some %s, you can't add a different liquid to it." ),
                 keg_name, item::nname( stack.only_item().typeId() ) );
        return false;
    }
    item &drink = stack.only_item();
    if( drink.volume() >= keg_cap ) {
        add_msg( _( "The %s is full." ), keg_name );
        return false;
    }
    add_msg( _( "You pour %1$s into the %2$s." ), liquid.tname(), keg_name );
    while( liquid.charges > 0 && drink.volume() < keg_cap ) {
        drink.charges++;
        liquid.charges--;
    }
    return true;
}
References _, map::add_item(), add_msg(), item::charges, item_stack::empty(), get_keg_capacity(), get_map(), map::i_at(), map::name(), item::nname(), item_stack::only_item(), item::tname(), item::typeId(), and item::volume().
Referenced by activity_handlers::fill_liquid_do_turn(), keg(), and liquid_handler::perform_liquid_transfer().
practice_survival_while_foraging()
void iexamine::practice_survival_while_foraging (player * p)
Intelligence Intelligence caps survival skill gains from foraging Survival decreases survival skill gain from foraging (NEGATIVE)
Definition at line 6367 of file iexamine.cpp.
{
    ///\EFFECT_INT Intelligence caps survival skill gains from foraging
    const int max_forage_skill = p->int_cur / 3 + 1;
    ///\EFFECT_SURVIVAL decreases survival skill gain from foraging (NEGATIVE)
    const int max_exp = 2 * ( max_forage_skill - p->get_skill_level( skill_survival ) );
    // Award experience for foraging attempt regardless of success
    p->practice( skill_survival, rng( 1, max_exp ), max_forage_skill );
}
References Character::get_skill_level(), Character::int_cur, Character::practice(), rng(), and skill_survival.
Referenced by activity_handlers::forage_finish(), and harvest_common().
quern_examine()
void iexamine::quern_examine (player & p, const tripoint & examp)
Definition at line 5792 of file iexamine.cpp.
{
    map &here = get_map();
    if( here.furn( examp ) == furn_str_id( "f_water_mill" ) ) {
        if( !here.is_water_shallow_current( examp ) ) {
            add_msg( _( "The water mill needs to be over shallow flowing water to work." ) );
            return;
        }
    }
    if( here.furn( examp ) == furn_str_id( "f_wind_mill" ) ) {
        if( g->is_sheltered( examp ) ) {
            add_msg( _( "The wind mill needs to be outside in the wind to work." ) );
            return;
        }
    }
    const bool active = here.furn( examp ) == furn_str_id( "f_water_mill_active" ) ||
                        here.furn( examp ) == furn_str_id( "f_wind_mill_active" );
    map_stack items_here = here.i_at( examp );
    if( items_here.empty() && active ) {
        debugmsg( "active mill was empty!" );
        if( here.furn( examp ) == furn_str_id( "f_water_mill_active" ) ) {
            here.furn_set( examp, f_water_mill );
        } else if( here.furn( examp ) == furn_str_id( "f_wind_mill_active" ) ) {
            here.furn_set( examp, f_wind_mill );
        }
        return;
    }
    if( items_here.size() == 1 && items_here.begin()->typeId() == itype_fake_milling_item ) {
        debugmsg( "f_mill_active was empty, and had fake_milling_item!" );
        if( here.furn( examp ) == furn_str_id( "f_water_mill_active" ) ) {
            here.furn_set( examp, f_water_mill );
        } else if( here.furn( examp ) == furn_str_id( "f_wind_mill_active" ) ) {
            here.furn_set( examp, f_wind_mill );
        }
        items_here.erase( items_here.begin() );
        return;
    }
    time_duration time_left = 0_turns;
    units::volume f_volume = 0_ml;
    bool f_check = false;
    for( const item &it : items_here ) {
        if( it.typeId() != itype_fake_milling_item ) {
            f_check = true;
            f_volume += it.volume();
        }
        if( active && it.typeId() == itype_fake_milling_item ) {
            time_left = time_duration::from_turns( it.item_counter );
        }
    }
    const bool empty = f_volume == 0_ml;
    const bool full = f_volume >= sm_rack::MAX_FOOD_VOLUME;
    const auto remaining_capacity = sm_rack::MAX_FOOD_VOLUME - f_volume;
    uilist smenu;
    smenu.text = _( "What to do with the mill?" );
    smenu.desc_enabled = true;
    smenu.addentry( 0, true, 'i', _( "Inspect mill" ) );
    if( !active ) {
        smenu.addentry_desc( 1, !empty, 'r',
                             empty ?  _( "Remove brake and start milling insert some products for milling first" ) :
                             _( "Remove brake and start milling" ),
                             string_format( _( "Remove brake and start milling, milling will take about %s." ),
                                            to_string( milling_time ) ) );
        smenu.addentry_desc( 2, !full, 'p',
                             full ? _( "Insert products for milling mill is full" ) :
                             string_format( _( "Insert products for milling remaining capacity is %s %s" ),
                                            format_volume( remaining_capacity ), volume_units_abbr() ),
                             _( "Fill the mill with starchy products such as wheat, barley or oats." ) );
        if( f_check ) {
            smenu.addentry( 3, f_check, 'e', _( "Remove products from mill" ) );
        }
    } else {
        smenu.addentry_desc( 4, true, 'x',
                             _( "Apply brake to mill" ),
                             _( "Applying the brake will stop milling process." ) );
    }
    smenu.query();
    switch( smenu.ret ) {
        case 0: { //inspect mill
            std::string pop;
            if( active ) {
                pop = colorize( _( "There's a mill here.  It is turning and milling." ), c_green ) + "\n";
                if( time_left > 0_turns ) {
                    pop += string_format( _( "It should take about %s to finish milling." ),
                                          to_string_clipped( time_left ) ) + "\n";
                }
            } else {
                pop += colorize( _( "There's a mill here." ), c_green ) + "\n";
            }
            pop += colorize( _( "You inspect its contents and find: " ), c_green ) + "\n\n";
            if( items_here.empty() ) {
                pop += _( "that it is empty." );
            } else {
                std::map<item, int> mill_list;
                for( const item &it : items_here ) {
                    if( it.typeId() == itype_fake_milling_item ) {
                        pop += "\n" + colorize( _( "You see that the milling process is not yet complete." ),
                                                c_red ) + "\n";
                        continue;
                    }
                    mill_list[it] += it.count();
                }
                for( auto it_mill : mill_list ) {
                    pop += "-> " + item::nname( it_mill.first.typeId(),
                                                it_mill.first.count() ) + ( ( it_mill.second > 1 ) ? " (" + std::to_string(
                                                            it_mill.second ) + ")\n" : "\n" );
                }
            }
            popup( pop, PF_NONE );
            break;
        }
        case 1:
            //activate
            if( active ) {
                add_msg( _( "It is already milling." ) );
            } else {
                mill_activate( p, examp );
            }
            break;
        case 2:
            // load food
            mill_load_food( p, examp, remaining_capacity );
            break;
        case 3:
            // remove food
            for( map_stack::iterator it = items_here.begin(); it != items_here.end(); ) {
                if( it->typeId() != itype_fake_milling_item ) {
                    // get handling cost before the item reference is invalidated
                    const int handling_cost = -p.item_handling_cost( *it );
                    add_msg( _( "You remove %s from the mill." ), it->tname() );
                    here.add_item_or_charges( p.pos(), *it );
                    it = items_here.erase( it );
                    p.mod_moves( handling_cost );
                } else {
                    ++it;
                }
            }
            if( active ) {
                if( here.furn( examp ) == furn_str_id( "f_water_mill_active" ) ) {
                    here.furn_set( examp, f_water_mill );
                } else if( here.furn( examp ) == furn_str_id( "f_wind_mill_active" ) ) {
                    here.furn_set( examp, f_wind_mill );
                }
                add_msg( m_info, _( "You stop the milling process." ) );
            }
            break;
        default:
            add_msg( m_info, _( "Never mind." ) );
            break;
        case 4:
            if( here.furn( examp ) == furn_str_id( "f_water_mill_active" ) ) {
                here.furn_set( examp, f_water_mill );
            } else if( here.furn( examp ) == furn_str_id( "f_wind_mill_active" ) ) {
                here.furn_set( examp, f_wind_mill );
            }
            add_msg( m_info, _( "You stop the milling process." ) );
            break;
    }
}
References _, active, map::add_item_or_charges(), add_msg(), uilist::addentry(), uilist::addentry_desc(), item_stack::begin(), c_green, c_red, colorize(), debugmsg, uilist::desc_enabled, item_stack::empty(), item_stack::end(), map_stack::erase(), f_water_mill, f_wind_mill, format_volume(), time_duration::from_turns(), map::furn(), map::furn_set(), g, get_map(), map::i_at(), map::is_water_shallow_current(), Character::item_handling_cost(), itype_fake_milling_item, m_info, sm_rack::MAX_FOOD_VOLUME, mill_activate(), mill_load_food(), milling_time, Creature::mod_moves(), item::nname(), PF_NONE, popup(), Character::pos(), uilist::query(), uilist::ret, item_stack::size(), string_format(), uilist::text, to_string(), to_string_clipped(), and volume_units_abbr().
Referenced by iexamine_function_from_string().
query_seed()
int iexamine::query_seed (const std::vector< seed_tuple > & seed_entries)
Choose seed for planting.
Definition at line 2260 of file iexamine.cpp.
{
    uilist smenu;
    smenu.text = _( "Use which seed?" );
    int count = 0;
    for( const auto &entry : seed_entries ) {
        const std::string &seed_name = std::get<1>( entry );
        int seed_count = std::get<2>( entry );
        std::string format = seed_count > 0 ? "%s (%d)" : "%s";
        smenu.addentry( count++, true, MENU_AUTOASSIGN, format.c_str(),
                        seed_name, seed_count );
    }
    smenu.query();
    if( smenu.ret >= 0 ) {
        return smenu.ret;
    } else {
        return seed_entries.size();
    }
}
References _, uilist::addentry(), detail::count(), format(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, and uilist::text.
Referenced by dirtmound(), plot_options::query_seed(), and vehicle::reload_seeds().
recycle_compactor()
void iexamine::recycle_compactor (player & p, const tripoint & examp)
Definition at line 3705 of file iexamine.cpp.
{
    // choose what metal to recycle
    auto metals = materials::get_compactable();
    uilist choose_metal;
    choose_metal.text = _( "Recycle what metal?" );
    for( auto &m : metals ) {
        choose_metal.addentry( m.name() );
    }
    choose_metal.query();
    int m_idx = choose_metal.ret;
    if( m_idx < 0 || m_idx >= static_cast<int>( metals.size() ) ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    material_type m = metals.at( m_idx );
    map &here = get_map();
    // check inputs and tally total mass
    auto inputs = here.i_at( examp );
    units::mass sum_weight = 0_gram;
    auto ca = m.compact_accepts();
    std::set<material_id> accepts( ca.begin(), ca.end() );
    accepts.insert( m.id );
    for( auto &input : inputs ) {
        if( !input.only_made_of( accepts ) ) {
            //~ %1$s: an item in the compactor , %2$s: desired compactor output material
            add_msg( _( "You realize this isn't going to work because %1$s is not made purely of %2$s." ),
                     input.tname(), m.name() );
            return;
        }
        if( input.is_container() && !input.is_container_empty() ) {
            //~ %1$s: an item in the compactor
            add_msg( _( "You realize this isn't going to work because %1$s has not been emptied of its contents." ),
                     input.tname() );
            return;
        }
        sum_weight += input.weight();
    }
    if( sum_weight <= 0_gram ) {
        //~ %1$s: desired compactor output material
        add_msg( _( "There is no %1$s in the compactor.  Drop some metal items onto it and try again." ),
                 m.name() );
        return;
    }
    // See below for recover_factor (rng(6,9)/10), this
    // is the normal value of that recover factor.
    static const double norm_recover_factor = 8.0 / 10.0;
    const units::mass norm_recover_weight = sum_weight * norm_recover_factor;
    // choose output
    uilist choose_output;
    //~ %1$.3f: total mass of material in compactor, %2$s: weight units , %3$s: compactor output material
    choose_output.text = string_format( _( "Compact %1$.3f %2$s of %3$s into:" ),
                                        convert_weight( sum_weight ), weight_units(), m.name() );
    for( auto &ci : m.compacts_into() ) {
        auto it = item( ci, calendar::start_of_cataclysm, item::solitary_tag{} );
        const int amount = norm_recover_weight / it.weight();
        //~ %1$d: number of, %2$s: output item
        choose_output.addentry( string_format( _( "about %1$d %2$s" ), amount,
                                               it.tname( amount ) ) );
    }
    choose_output.query();
    int o_idx = choose_output.ret;
    if( o_idx < 0 || o_idx >= static_cast<int>( m.compacts_into().size() ) ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    // remove items
    for( auto it = inputs.begin(); it != inputs.end(); ) {
        it = inputs.erase( it );
    }
    // produce outputs
    double recover_factor = rng( 6, 9 ) / 10.0;
    sum_weight = sum_weight * recover_factor;
    sounds::sound( examp, 80, sounds::sound_t::combat, _( "Ka-klunk!" ), true, "tool", "compactor" );
    bool out_desired = false;
    bool out_any = false;
    for( auto it = m.compacts_into().begin() + o_idx; it != m.compacts_into().end(); ++it ) {
        const units::mass ow = item( *it, calendar::start_of_cataclysm, item::solitary_tag{} ).weight();
        int count = sum_weight / ow;
        sum_weight -= count * ow;
        if( count > 0 ) {
            here.spawn_item( examp, *it, count, 1, calendar::turn );
            if( !out_any ) {
                out_any = true;
                if( it == m.compacts_into().begin() + o_idx ) {
                    out_desired = true;
                }
            }
        }
    }
    // feedback to user
    if( !out_any ) {
        add_msg( _( "The compactor chews up all the items in its hopper." ) );
        //~ %1$s: compactor output material
        add_msg( _( "The compactor beeps: \"No %1$s to process!\"" ), m.name() );
        return;
    }
    if( !out_desired ) {
        //~ %1$s: compactor output material
        add_msg( _( "The compactor beeps: \"Insufficient %1$s!\"" ), m.name() );
        add_msg( _( "It spits out an assortment of smaller pieces instead." ) );
    }
}
References _, add_msg(), uilist::addentry(), sounds::combat, material_type::compact_accepts(), material_type::compacts_into(), convert_weight(), detail::count(), materials::get_compactable(), get_map(), map::i_at(), material_type::id, material_type::name(), uilist::query(), uilist::ret, rng(), sounds::sound(), map::spawn_item(), calendar::start_of_cataclysm, string_format(), uilist::text, calendar::turn, and weight_units().
Referenced by iexamine_function_from_string().
reload_furniture()
void iexamine::reload_furniture (player & p, const tripoint & examp)
Definition at line 3919 of file iexamine.cpp.
{
    map &here = get_map();
    const furn_t &f = here.furn( examp ).obj();
    const std::vector<itype> ammo_types = f.crafting_ammo_item_types();
    // No fake item, no ammo, something is wrong here.
    if( ammo_types.empty() ) {
        debugmsg( ( "The %s has no crafting_pseudo_items or no defined ammo!" ), f.name() );
        return;
    }
    map_stack items_here = here.i_at( examp );
    std::vector<std::string> ammo_names;
    std::vector<itype> ammo_filtered;
    int ammo_index = 0;
    for( const itype &at : ammo_types ) {
        if( at.get_id() != itype_battery ) {
            ammo_names.emplace_back( at.nname( 1 ) );
            ammo_filtered.emplace_back( at );
        }
    }
    if( ammo_filtered.empty() ) {
        debugmsg( "Furniture %s has no valid ammo to reload!", f.name() );
        return;
    } else if( ammo_names.size() > 1 ) {
        ammo_index = uilist( _( "What would you like to change?" ), ammo_names );
        if( ammo_index < 0 || static_cast<size_t>( ammo_index ) >= ammo_names.size() ) {
            ammo_index = -1;
        }
    }
    if( ammo_index < 0 ) {
        return;
    }
    // HACK: Yes I know I'm converting from itype to itype_id and back again into a pointer.
    // It seems to be needed to make the appropriate connections?
    // Otherwise the part where it queries for the amount doesn't seem to work right.
    const itype *cur_ammo = &*ammo_types.at( ammo_index ).get_id();
    const int amount_in_furn = count_charges_in_list( cur_ammo, items_here );
    const int amount_in_inv = p.charges_of( cur_ammo->get_id() );
    if( amount_in_furn > 0 ) {
        if( p.query_yn( _( "The %1$s contains %2$d %3$s.  Unload?" ), f.name(), amount_in_furn,
                        cur_ammo->nname( amount_in_furn ) ) ) {
            auto items = here.i_at( examp );
            for( auto &itm : items ) {
                if( itm.type == cur_ammo ) {
                    g->u.assign_activity( player_activity( pickup_activity_actor(
                    { { item_location( map_cursor( examp ), &itm ), cata::nullopt, {} } }, g->u.pos() ) ) );
                    return;
                }
            }
        }
    }
    // Note that this can lead to hammerspace as each ammo type doesn't take other items on the tile into account.
    const int max_amount_in_furn = cur_ammo->charges_per_volume( f.max_volume );
    const int max_reload_amount = max_amount_in_furn - amount_in_furn;
    if( max_reload_amount <= 0 ) {
        return;
    }
    if( amount_in_inv == 0 ) {
        //~ Reloading or restocking a piece of furniture, for example a forge.
        add_msg( m_info, _( "You need some %1$s to reload this %2$s." ),
                 cur_ammo->nname( 2 ),
                 f.name() );
        return;
    }
    const int max_amount = std::min( amount_in_inv, max_reload_amount );
    //~ Loading fuel or other items into a piece of furniture.
    const std::string popupmsg = string_format( _( "Put how many of the %1$s into the %2$s?" ),
                                 cur_ammo->nname( max_amount ), f.name() );
    int amount = string_input_popup()
                 .title( popupmsg )
                 .width( 20 )
                 .text( std::to_string( max_amount ) )
                 .only_digits( true )
                 .query_int();
    if( amount <= 0 || amount > max_amount ) {
        return;
    }
    p.use_charges( cur_ammo->get_id(), amount );
    auto items = here.i_at( examp );
    for( auto &itm : items ) {
        if( itm.type == cur_ammo ) {
            itm.charges += amount;
            amount = 0;
            break;
        }
    }
    if( amount != 0 ) {
        item it( cur_ammo->get_id(), calendar::turn, amount );
        here.add_item( examp, it );
    }
    const int amount_in_furn_after_placing = count_charges_in_list( &ammo_types.at( ammo_index ),
            items );
    //~ %1$s - furniture, %2$d - number, %3$s items.
    add_msg( _( "The %1$s contains %2$d %3$s." ), f.name(), amount_in_furn_after_placing,
             cur_ammo->nname( amount_in_furn_after_placing ) );
    add_msg( _( "You reload the %s." ), here.furnname( examp ) );
    p.moves -= to_moves<int>( 5_seconds );
}
References _, map::add_item(), add_msg(), visitable< T >::charges_of(), itype::charges_per_volume(), count_charges_in_list(), furn_t::crafting_ammo_item_types(), debugmsg, map::furn(), map::furnname(), g, itype::get_id(), get_map(), map::i_at(), itype_battery, m_info, map_data_common_t::max_volume, Creature::moves, map_data_common_t::name(), itype::nname(), cata::nullopt, int_id< T >::obj(), string_input_popup::only_digits(), string_input_popup::query_int(), player::query_yn(), string_format(), string_input_popup::text(), string_input_popup::title(), to_string(), calendar::turn, Character::use_charges(), and string_input_popup::width().
Referenced by iexamine_function_from_string(), and smoker_options().
rubble()
void iexamine::rubble (player & p, const tripoint & examp)
Prompt removal of rubble.
Select best shovel and invoke "CLEAR_RUBBLE" on tile.
Definition at line 1133 of file iexamine.cpp.
{
    int moves;
    if( p.has_quality( qual_DIG, 3 ) || p.has_trait( trait_BURROW ) ) {
        moves = to_moves<int>( 1_minutes );
    } else if( p.has_quality( qual_DIG, 2 ) ) {
        moves = to_moves<int>( 2_minutes );
    } else {
        add_msg( m_info, _( "If only you had a shovel" ) );
        return;
    }
    map &here = get_map();
    if( ( here.veh_at( examp ) || !here.tr_at( examp ).is_null() ||
          g->critter_at( examp ) != nullptr ) &&
        !query_yn( _( "Clear up that %s?" ), here.furnname( examp ) ) ) {
        return;
    }
    p.assign_activity( ACT_CLEAR_RUBBLE, moves, -1, 0 );
    p.activity.placement = examp;
    return;
}
References _, ACT_CLEAR_RUBBLE, Character::activity, add_msg(), Character::assign_activity(), map::furnname(), g, get_map(), visitable< T >::has_quality(), Character::has_trait(), trap::is_null(), m_info, player_activity::placement, qual_DIG, query_yn(), map::tr_at(), trait_BURROW, and map::veh_at().
Referenced by iexamine_function_from_string().
safe()
void iexamine::safe (player & p, const tripoint & examp)
Attempt to crack safe through audio-feedback manual lock manipulation.
Try to unlock the safe by moving the dial and listening for the mechanism to "click into place." Time per attempt affected by perception and mechanics. 30 minutes per attempt minimum. Small chance of just guessing the combo without listening device.
Perception speeds up safe cracking Mechanics speeds up safe cracking
Definition at line 1417 of file iexamine.cpp.
{
    auto cracking_tool = p.crafting_inventory().items_with( []( const item & it ) -> bool {
        item temporary_item( it.type );
        return temporary_item.has_flag( flag_SAFECRACK );
    } );
    if( !( !cracking_tool.empty() || p.has_bionic( bio_ears ) ) ) {
        p.moves -= to_turns<int>( 10_seconds );
        // one_in(30^3) chance of guessing
        if( one_in( 27000 ) ) {
            p.add_msg_if_player( m_good, _( "You mess with the dial for a little bit and it opens!" ) );
            get_map().furn_set( examp, f_safe_o );
            return;
        } else {
            p.add_msg_if_player( m_info, _( "You mess with the dial for a little bit." ) );
            return;
        }
    }
    if( p.is_deaf() ) {
        add_msg( m_info, _( "You can't crack a safe while deaf!" ) );
        return;
    } else if( p.has_effect( effect_earphones ) ) {
        add_msg( m_info, _( "You can't crack a safe while listening to music!" ) );
        return;
    } else if( query_yn( _( "Attempt to crack the safe?" ) ) ) {
        add_msg( m_info, _( "You start cracking the safe." ) );
        // 150 minutes +/- 20 minutes per mechanics point away from 3 +/- 10 minutes per
        // perception point away from 8; capped at 30 minutes minimum. *100 to convert to moves
        ///\EFFECT_PER speeds up safe cracking
        ///\EFFECT_MECHANICS speeds up safe cracking
        const time_duration time = std::max( 150_minutes - 20_minutes * ( p.get_skill_level(
                skill_mechanics ) - 3 ) - 10_minutes * ( p.get_per() - 8 ), 30_minutes );
        p.assign_activity( ACT_CRACKING, to_moves<int>( time ) );
        p.activity.placement = examp;
    }
}
References _, ACT_CRACKING, Character::activity, add_msg(), player::add_msg_if_player(), Character::assign_activity(), bio_ears, Character::crafting_inventory(), effect_earphones, f_safe_o, flag_SAFECRACK(), map::furn_set(), get_map(), Character::get_per(), Character::get_skill_level(), Character::has_bionic(), Creature::has_effect(), item::has_flag(), Character::is_deaf(), visitable< T >::items_with(), m_good, m_info, Creature::moves, one_in(), player_activity::placement, query_yn(), skill_mechanics, time, and item::type.
Referenced by Character::can_pick_weight(), iexamine_function_from_string(), vehicle::lift_thrust_of_rotorcraft(), sinkhole_safety_roll(), teleport::teleport(), spell_effect::teleport_random(), vehicle::total_power_w(), and try_reject_mutagen().
shrub_marloss()
void iexamine::shrub_marloss (player & p, const tripoint & examp)
Definition at line 3646 of file iexamine.cpp.
{
    if( p.has_trait( trait_THRESH_MYCUS ) ) {
        pick_plant( p, examp, itype_mycus_fruit, t_shrub_fungal );
    } else if( p.has_trait( trait_THRESH_MARLOSS ) ) {
        map &here = get_map();
        here.spawn_item( p.pos(), itype_mycus_fruit, 1, 0, calendar::turn );
        here.ter_set( examp, t_fungus );
        add_msg( m_info, _( "The shrub offers up a fruit, then crumbles into a fungal bed." ) );
    } else {
        pick_plant( p, examp, itype_marloss_berry, t_shrub_fungal );
    }
}
References _, add_msg(), get_map(), Character::has_trait(), itype_marloss_berry, itype_mycus_fruit, m_info, pick_plant(), Character::pos(), map::spawn_item(), t_fungus, t_shrub_fungal, map::ter_set(), trait_THRESH_MARLOSS, trait_THRESH_MYCUS, and calendar::turn.
Referenced by iexamine_function_from_string(), and game::place_player().
shrub_wildveggies()
void iexamine::shrub_wildveggies (player & p, const tripoint & examp)
Survival speeds up foraging Perception randomly speeds up foraging
Definition at line 3681 of file iexamine.cpp.
{
    map &here = get_map();
    // Ask if there's something possibly more interesting than this shrub here
    if( ( !here.i_at( examp ).empty() ||
          here.veh_at( examp ) ||
          !here.tr_at( examp ).is_null() ||
          g->critter_at( examp ) != nullptr ) &&
        !query_yn( _( "Forage through %s?" ), here.tername( examp ) ) ) {
        none( p, examp );
        return;
    }
    add_msg( _( "You forage through the %s." ), here.tername( examp ) );
    ///\EFFECT_SURVIVAL speeds up foraging
    int move_cost = 100000 / ( 2 * p.get_skill_level( skill_survival ) + 5 );
    ///\EFFECT_PER randomly speeds up foraging
    move_cost /= rng( std::max( 4, p.per_cur ), 4 + p.per_cur * 2 );
    p.assign_activity( ACT_FORAGE, move_cost, 0 );
    p.activity.placement = here.getabs( examp );
    p.activity.auto_resume = true;
    return;
}
References _, ACT_FORAGE, Character::activity, add_msg(), Character::assign_activity(), player_activity::auto_resume, item_stack::empty(), g, get_map(), Character::get_skill_level(), map::getabs(), map::i_at(), trap::is_null(), move_cost(), none, Character::per_cur, player_activity::placement, query_yn(), rng(), skill_survival, map::tername(), map::tr_at(), and map::veh_at().
Referenced by iexamine_function_from_string(), and game::place_player().
sign()
void iexamine::sign (player & p, const tripoint & examp)
Definition at line 4179 of file iexamine.cpp.
{
    map &here = get_map();
    std::string existing_signage = here.get_signage( examp );
    bool previous_signage_exists = !existing_signage.empty();
    // Display existing message, or lack thereof.
    if( p.has_trait( trait_ILLITERATE ) ) {
        popup( _( "You're illiterate, and can't read the message on the sign." ) );
    } else if( previous_signage_exists ) {
        popup( existing_signage.c_str() );
    } else {
        p.add_msg_if_player( m_neutral, _( "Nothing legible on the sign." ) );
    }
    // Allow chance to modify message.
    std::vector<tool_comp> tools;
    std::vector<const item *> filter = p.crafting_inventory().items_with( []( const item & it ) {
        return it.has_flag( flag_WRITE_MESSAGE ) && it.charges > 0;
    } );
    tools.reserve( filter.size() );
    for( const item *writing_item : filter ) {
        tools.push_back( tool_comp( writing_item->typeId(), 1 ) );
    }
    if( !tools.empty() ) {
        // Different messages if the sign already has writing associated with it.
        std::string query_message = previous_signage_exists ?
                                    _( "Overwrite the existing message on the sign?" ) :
                                    _( "Add a message to the sign?" );
        std::string ignore_message = _( "You leave the sign alone." );
        if( query_yn( query_message ) ) {
            std::string signage = string_input_popup()
                                  .title( _( "Write what?" ) )
                                  .identifier( "signage" )
                                  .query_string();
            if( signage.empty() ) {
                p.add_msg_if_player( m_neutral, ignore_message );
            } else {
                std::string spray_painted_message = previous_signage_exists ?
                                                    _( "You overwrite the previous message on the sign with your graffiti." ) :
                                                    _( "You graffiti a message onto the sign." );
                here.set_signage( examp, signage );
                p.add_msg_if_player( m_info, spray_painted_message );
                p.mod_moves( - 20 * signage.length() );
                p.consume_tools( tools, 1 );
            }
        } else {
            p.add_msg_if_player( m_neutral, ignore_message );
        }
    }
}
References _, player::add_msg_if_player(), item::charges, player::consume_tools(), Character::crafting_inventory(), flag_WRITE_MESSAGE(), get_map(), map::get_signage(), item::has_flag(), Character::has_trait(), string_input_popup::identifier(), visitable< T >::items_with(), m_info, m_neutral, Creature::mod_moves(), popup(), string_input_popup::query_string(), query_yn(), map::set_signage(), string_input_popup::title(), and trait_ILLITERATE.
Referenced by iexamine_function_from_string().
slot_machine()
void iexamine::slot_machine (player & p, const tripoint & examp)
Loop prompt to bet $10.
Definition at line 1372 of file iexamine.cpp.
{
    const int price = 10;
    auto cents = []( int x ) {
        return x * 100;
    };
    bool played = false;
    while( true ) {
        if( p.cash < cents( price ) ) {
            add_msg( m_info, _( "You need $%d to play." ), price );
            break;
        }
        if( !query_yn( played ? _( "Play again for $%d?" ) : _( "Insert $%d?" ), price ) ) {
            break;
        }
        p.cash -= cents( price );
        played = true;
        int won;
        if( one_in( 5 ) ) {
            won = price;
            popup( _( "Three cherries you get your money back!" ) );
        } else if( one_in( 20 ) ) {
            won = 50;
            popup( _( "Three bells you win $%d!" ), won );
        } else if( one_in( 50 ) ) {
            won = 200;
            popup( _( "Three stars you win $%d!" ), won );
        } else if( one_in( 1000 ) ) {
            won = 3000;
            popup( _( "JACKPOT!  You win $%d!" ), won );
        } else {
            won = 0;
            popup( _( "No win." ) );
        }
        p.cash += cents( won );
    }
}
References _, add_msg(), player::cash, m_info, one_in(), popup(), and query_yn().
Referenced by iexamine_function_from_string().
smoker_options()
void iexamine::smoker_options (player & p, const tripoint & examp)
Definition at line 5966 of file iexamine.cpp.
{
    map &here = get_map();
    const bool active = here.furn( examp ) == furn_str_id( "f_smoking_rack_active" ) ||
                        here.furn( examp ) == furn_str_id( "f_metal_smoking_rack_active" );
    const bool portable = here.furn( examp ) == furn_str_id( "f_metal_smoking_rack" ) ||
                          here.furn( examp ) == furn_str_id( "f_metal_smoking_rack_active" );
    map_stack items_here = here.i_at( examp );
    if( portable && items_here.empty() && active ) {
        debugmsg( "f_metal_smoking_rack_active was empty!" );
        here.furn_set( examp, f_metal_smoking_rack );
        return;
    } else if( items_here.empty() && active ) {
        debugmsg( "f_smoking_rack_active was empty!" );
        here.furn_set( examp, f_smoking_rack );
        return;
    }
    if( portable && items_here.size() == 1 && items_here.begin()->typeId() == itype_fake_smoke_plume ) {
        debugmsg( "f_metal_smoking_rack_active was empty, and had fake_smoke_plume!" );
        here.furn_set( examp, f_metal_smoking_rack );
        items_here.erase( items_here.begin() );
        return;
    } else if( items_here.size() == 1 && items_here.begin()->typeId() == itype_fake_smoke_plume ) {
        debugmsg( "f_smoking_rack_active was empty, and had fake_smoke_plume!" );
        here.furn_set( examp, f_smoking_rack );
        items_here.erase( items_here.begin() );
        return;
    }
    bool rem_f_opt = false;
    time_duration time_left = 0_turns;
    int hours_left = 0;
    int minutes_left = 0;
    units::volume f_volume = 0_ml;
    bool f_check = false;
    for( const item &it : items_here ) {
        if( it.is_food() ) {
            f_check = true;
            f_volume += it.volume();
        }
        if( active && it.typeId() == itype_fake_smoke_plume ) {
            time_left = time_duration::from_turns( it.item_counter );
            hours_left = to_hours<int>( time_left );
            minutes_left = to_minutes<int>( time_left ) + 1;
        }
    }
    const bool empty = f_volume == 0_ml;
    const bool full = f_volume >= sm_rack::MAX_FOOD_VOLUME;
    const bool full_portable = f_volume >= sm_rack::MAX_FOOD_VOLUME_PORTABLE;
    const auto remaining_capacity = sm_rack::MAX_FOOD_VOLUME - f_volume;
    const auto remaining_capacity_portable = sm_rack::MAX_FOOD_VOLUME_PORTABLE - f_volume;
    const auto has_coal_in_inventory = p.charges_of( itype_charcoal ) > 0;
    const auto coal_charges = count_charges_in_list( &*itype_charcoal, items_here );
    const auto need_charges = get_charcoal_charges( f_volume );
    const bool has_coal = coal_charges > 0;
    const bool has_enough_coal = coal_charges >= need_charges;
    uilist smenu;
    smenu.text = _( "What to do with the smoking rack:" );
    smenu.desc_enabled = true;
    smenu.addentry( 0, true, 'i', _( "Inspect smoking rack" ) );
    if( !active ) {
        smenu.addentry_desc( 1, !empty && has_enough_coal, 'l',
                             empty ?  _( "Light up and smoke food insert some food for smoking first" ) :
                             !has_enough_coal ? string_format(
                                 _( "Light up and smoke food need extra %d charges of charcoal" ),
                                 need_charges - coal_charges ) :
                             _( "Light up and smoke food" ),
                             _( "Light up the smoking rack and start smoking.  Smoking will take about 6 hours." ) );
        if( portable ) {
            smenu.addentry_desc( 2, !full_portable, 'f',
                                 full_portable ? _( "Insert food for smoking smoking rack is full" ) :
                                 string_format( _( "Insert food for smoking remaining capacity is %s %s" ),
                                                format_volume( remaining_capacity_portable ), volume_units_abbr() ),
                                 _( "Fill the smoking rack with raw meat, fish or sausages for smoking or fruit or vegetable or smoked meat for drying." ) );
            smenu.addentry_desc( 8, !active, 'z',
                                 active ? _( "You cannot disassemble this smoking rack while it is active!" ) :
                                 _( "Disassemble the smoking rack" ), "" );
        } else {
            smenu.addentry_desc( 2, !full, 'f',
                                 full ? _( "Insert food for smoking smoking rack is full" ) :
                                 string_format( _( "Insert food for smoking remaining capacity is %s %s" ),
                                                format_volume( remaining_capacity ), volume_units_abbr() ),
                                 _( "Fill the smoking rack with raw meat, fish or sausages for smoking or fruit or vegetable or smoked meat for drying." ) );
        }
        if( f_check ) {
            smenu.addentry( 4, f_check, 'e', _( "Remove food from smoking rack" ) );
        }
        smenu.addentry_desc( 3, has_coal_in_inventory, 'r',
                             !has_coal_in_inventory ? _( "Reload with charcoal you don't have any" ) :
                             _( "Reload with charcoal" ),
                             string_format(
                                 _( "You need %d charges of charcoal for %s %s of food.  Minimal amount of charcoal is %d charges." ),
                                 sm_rack::CHARCOAL_PER_LITER, format_volume( 1_liter ), volume_units_long(),
                                 sm_rack::MIN_CHARCOAL ) );
    } else {
        smenu.addentry_desc( 7, true, 'x',
                             _( "Quench burning charcoal" ),
                             _( "Quenching will stop smoking process, but also destroy all used charcoal." ) );
    }
    if( has_coal ) {
        smenu.addentry( 5, true, 'c',
                        active ? string_format( _( "Rake out %d excess charges of charcoal from smoking rack" ),
                                                coal_charges ) :
                        string_format( _( "Remove %d charges of charcoal from smoking rack" ), coal_charges ) );
    }
    smenu.query();
    switch( smenu.ret ) {
        case 0: { //inspect smoking rack
            std::string pop;
            if( active ) {
                pop += colorize( _( "There's a smoking rack here.  It is lit and smoking." ), c_green ) + "\n";
                if( time_left > 0_turns ) {
                    if( minutes_left > 60 ) {
                        pop += string_format( vgettext( "It will finish smoking in about %d hour.",
                                                        "It will finish smoking in about %d hours.",
                                                        hours_left ), hours_left ) + "\n\n";
                    } else if( minutes_left > 30 ) {
                        pop += _( "It will finish smoking in less than an hour." ) + std::string( "\n" );
                    } else {
                        pop += string_format( _( "It should take about %d minutes to finish smoking." ),
                                              minutes_left ) + "\n ";
                    }
                }
            } else {
                pop += colorize( _( "There's a smoking rack here." ), c_green ) + "\n";
            }
            pop += colorize( _( "You inspect its contents and find: " ), c_green ) + "\n";
            if( items_here.empty() ) {
                pop += _( "that it is empty." );
            } else {
                for( const item &it : items_here ) {
                    if( it.typeId() == itype_fake_smoke_plume ) {
                        pop += "\n" + colorize( _( "You see some smoldering embers there." ), c_red ) + "\n";
                        continue;
                    }
                    pop += "-> " + item::nname( it.typeId(), it.charges ) + " (" + std::to_string( it.charges ) + ")\n";
                }
            }
            popup( pop, PF_NONE );
            break;
        }
        case 1:
            //activate
            if( active ) {
                add_msg( _( "It is already lit and smoking." ) );
            } else {
                smoker_activate( p, examp );
            }
            break;
        case 2:
            // load food
            if( portable ) {
                smoker_load_food( p, examp, remaining_capacity_portable );
            } else {
                smoker_load_food( p, examp, remaining_capacity );
            }
            break;
        case 3:
            // load charcoal
            reload_furniture( p, examp );
            break;
        case 4:
            // remove food
            rem_f_opt = true;
        /* fallthrough */
        case 5: {
            //remove charcoal
            for( map_stack::iterator it = items_here.begin(); it != items_here.end(); ) {
                if( ( rem_f_opt && it->is_food() ) || ( !rem_f_opt && ( it->typeId() == itype_charcoal ) ) ) {
                    // get handling cost before the item reference is invalidated
                    const int handling_cost = -p.item_handling_cost( *it );
                    add_msg( _( "You remove %s from the rack." ), it->tname() );
                    here.add_item_or_charges( p.pos(), *it );
                    it = items_here.erase( it );
                    p.mod_moves( handling_cost );
                } else {
                    ++it;
                }
            }
            if( portable && active && rem_f_opt ) {
                here.furn_set( examp, f_metal_smoking_rack );
                add_msg( m_info, _( "You stop the smoking process." ) );
            } else if( active && rem_f_opt ) {
                here.furn_set( examp, f_smoking_rack );
                add_msg( m_info, _( "You stop the smoking process." ) );
            }
        }
        break;
        default:
            add_msg( m_info, _( "Never mind." ) );
            break;
        case 7:
            if( portable ) {
                here.furn_set( examp, f_metal_smoking_rack );
                add_msg( m_info, _( "You stop the smoking process." ) );
            } else {
                here.furn_set( examp, f_smoking_rack );
                add_msg( m_info, _( "You stop the smoking process." ) );
            }
            break;
        case 8:
            here.furn_set( examp, f_metal_smoking_rack );
            deployed_furniture( p, examp );
            break;
    }
}
References _, active, map::add_item_or_charges(), add_msg(), uilist::addentry(), uilist::addentry_desc(), item_stack::begin(), c_green, c_red, sm_rack::CHARCOAL_PER_LITER, visitable< T >::charges_of(), colorize(), count_charges_in_list(), debugmsg, deployed_furniture(), uilist::desc_enabled, item_stack::empty(), item_stack::end(), map_stack::erase(), f_metal_smoking_rack, f_smoking_rack, format_volume(), time_duration::from_turns(), map::furn(), map::furn_set(), get_charcoal_charges(), get_map(), map::i_at(), Character::item_handling_cost(), itype_charcoal, itype_fake_smoke_plume, m_info, sm_rack::MAX_FOOD_VOLUME, sm_rack::MAX_FOOD_VOLUME_PORTABLE, sm_rack::MIN_CHARCOAL, Creature::mod_moves(), item::nname(), PF_NONE, popup(), Character::pos(), uilist::query(), reload_furniture(), uilist::ret, item_stack::size(), smoker_activate(), smoker_load_food(), string_format(), uilist::text, to_string(), vgettext(), volume_units_abbr(), and volume_units_long().
Referenced by iexamine_function_from_string().
toilet()
void iexamine::toilet (player & p, const tripoint & examp)
If there's water, allow its usage but add chance of poison.
Definition at line 855 of file iexamine.cpp.
{
    auto items = get_map().i_at( examp );
    auto water = items.begin();
    for( ; water != items.end(); ++water ) {
        if( water->typeId() == itype_water ) {
            break;
        }
    }
    if( water == items.end() ) {
        add_msg( m_info, _( "This toilet is empty." ) );
    } else if( !water->made_of( LIQUID ) ) {
        add_msg( m_info, _( "The toilet water is frozen solid!" ) );
    } else {
        // Use a different poison value each time water is drawn from the toilet.
        water->poison = one_in( 3 ) ? 0 : rng( 1, 3 );
        // TODO: use me
        ( void ) p;
        liquid_handler::handle_liquid_from_ground( water, examp );
    }
}
References _, add_msg(), item_stack::begin(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), itype_water, LIQUID, m_info, one_in(), and rng().
Referenced by inventory::form_from_map(), and iexamine_function_from_string().
toPumpFuel()
bool iexamine::toPumpFuel (const tripoint & src, const tripoint & dst, int units)
Definition at line 4367 of file iexamine.cpp.
{
    map &here = get_map();
    auto items = here.i_at( src );
    for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
        if( item_it->made_of( LIQUID ) ) {
            if( item_it->charges < units ) {
                return false;
            }
            item_it->charges -= units;
            item liq_d( item_it->type, calendar::turn, units );
            const auto backup_pump = here.ter( dst );
            here.ter_set( dst, ter_str_id::NULL_ID() );
            here.add_item_or_charges( dst, liq_d );
            here.ter_set( dst, backup_pump );
            if( item_it->charges < 1 ) {
                items.erase( item_it );
            }
            return true;
        }
    }
    return false;
}
References map::add_item_or_charges(), get_map(), map::i_at(), LIQUID, string_id< ter_t >::NULL_ID(), map::ter(), map::ter_set(), and calendar::turn.
Referenced by hacking_activity_actor::finish(), and pay_gas().
transform()
void iexamine::transform (player & p, const tripoint & pos)
Transform the examined object into the object specified by its transforms_into property.
If the new object has a message property, it is displayed as if the notify examine_action was used.
Definition at line 1639 of file iexamine.cpp.
{
    std::string message;
    std::string prompt;
    if( g->m.has_furn( pos ) ) {
        message = g->m.furn( pos ).obj().message;
        prompt = g->m.furn( pos ).obj().prompt;
    } else {
        message = g->m.ter( pos ).obj().message;
        prompt = g->m.ter( pos ).obj().prompt;
    }
    uilist selection_menu;
    selection_menu.text = _( "Select an action" );
    selection_menu.addentry( 0, true, 'g', _( "Get items" ) );
    selection_menu.addentry( 1, true, 't', !prompt.empty() ? _( prompt ) : _( "Transform furniture" ) );
    selection_menu.query();
    switch( selection_menu.ret ) {
        case 0:
            none( p, pos );
            pickup::pick_up( pos, 0 );
            return;
        case 1: {
            if( g->m.has_furn( pos ) ) {
                if( !message.empty() ) {
                    add_msg( _( message ) );
                }
                g->m.furn_set( pos, g->m.get_furn_transforms_into( pos ) );
            } else {
                if( !message.empty() ) {
                    add_msg( _( message ) );
                }
                g->m.ter_set( pos, g->m.get_ter_transforms_into( pos ) );
            }
            return;
        }
        default:
            none( p, pos );
            return;
    }
}
References _, add_msg(), uilist::addentry(), g, mapgen_defer::message, none, pickup::pick_up(), pickup::prompt, uilist::query(), uilist::ret, and uilist::text.
Referenced by inventory_selector::add_items(), mod_manager::all_mods(), closest_points_first(), deduped_requirement_data::deduped_requirement_data(), help::display_help(), draw_tabs(), game::dump_stats(), ensure_valid_file_name(), game::examine(), item::final_info(), harvest_list::finalize(), find_all_effect_types(), get_achievements_text(), mission::get_all_item_group_matches(), crafting::get_books_for_recipe(), overmapbuffer::get_camps_near(), overmapbuffer::get_cities_near(), input_context::get_direction(), Skill::get_skills_sorted_by(), inventory_selector::get_stats(), item::gun_all_modes(), iexamine_function_from_string(), game::item_action_menu(), inscribe_actor::item_inscription(), ma_style_callback::key(), lcmatch(), line_to(), map_data_common_t::load(), holster_actor::load(), game_info::mods_loaded(), normalized_map(), item::on_wear(), overmap_special_batch::overmap_special_batch(), requirement_data::print_all_objs(), print_ranged_chance(), anonymous_namespace{messages.cpp}::messages_impl::recent_messages(), bandolier_actor::reload(), pickup::reorder_for_dropping(), character_funcs::select_ammo(), select_crafting_recipe(), Character::shout(), cata::sort_by_rating(), to_lower_case(), to_upper_case(), spell_effect::transform_blast(), character_funcs::try_wield_contents(), holster_actor::use(), and debug_menu::wishitem().
translocator()
void iexamine::translocator (player & p, const tripoint & examp)
Definition at line 391 of file iexamine.cpp.
{
    // TODO: fix point types
    const tripoint_abs_omt omt_loc( ms_to_omt_copy( get_map().getabs( examp ) ) );
    avatar &player_character = get_avatar();
    const bool activated = player_character.translocators->knows_translocator( omt_loc );
    if( !activated ) {
        g->u.translocators->activate_teleporter( omt_loc, examp );
        add_msg( m_info, _( "Translocator gate active." ) );
    } else {
        if( query_yn( _( "Do you want to deactivate this active Translocator?" ) ) ) {
            g->u.translocators->deactivate_teleporter( omt_loc, examp );
        }
    }
}
References _, add_msg(), g, get_avatar(), get_map(), m_info, ms_to_omt_copy(), query_yn(), and avatar::translocators.
Referenced by iexamine_function_from_string().
trap()
void iexamine::trap (player & p, const tripoint & examp)
Definition at line 3815 of file iexamine.cpp.
{
    map &here = get_map();
    const auto &tr = here.tr_at( examp );
    if( !p.is_player() || tr.is_null() ) {
        return;
    }
    const int possible = tr.get_difficulty();
    bool seen = tr.can_see( examp, p );
    if( tr.loadid == tr_unfinished_construction || here.partial_con_at( examp ) ) {
        partial_con *pc = here.partial_con_at( examp );
        if( pc ) {
            if( !character_funcs::can_see_fine_details( p ) && !p.has_trait( trait_DEBUG_HS ) ) {
                add_msg( m_info, _( "It is too dark to construct right now." ) );
                return;
            }
            const construction &built = pc->id.obj();
            if( !query_yn( _( "Unfinished task: %s, %d%% complete here, continue construction?" ),
                           built.group->name(), pc->counter / 100000 ) ) {
                if( query_yn( _( "Cancel construction?" ) ) ) {
                    here.disarm_trap( examp );
                    for( const item &it : pc->components ) {
                        here.add_item_or_charges( p.pos(), it );
                    }
                    here.partial_con_remove( examp );
                    return;
                } else {
                    return;
                }
            } else {
                p.assign_activity( ACT_BUILD );
                p.activity.placement = here.getabs( examp );
                return;
            }
        } else {
            return;
        }
    }
    if( seen && possible >= 99 ) {
        add_msg( m_info, _( "That %s looks too dangerous to mess with.  Best leave it alone." ),
                 tr.name() );
        return;
    }
    // Some traps are not actual traps. Those should get a different query.
    if( seen && possible == 0 &&
        tr.get_avoidance() == 0 ) { // Separated so saying no doesn't trigger the other query.
        if( query_yn( _( "There is a %s there.  Take down?" ), tr.name() ) ) {
            here.disarm_trap( examp );
        }
    } else if( seen && query_yn( _( "There is a %s there.  Disarm?" ), tr.name() ) ) {
        here.disarm_trap( examp );
    }
}
References _, ACT_BUILD, Character::activity, map::add_item_or_charges(), add_msg(), Character::assign_activity(), character_funcs::can_see_fine_details(), partial_con::components, partial_con::counter, map::disarm_trap(), trap::get_difficulty(), get_map(), map::getabs(), construction::group, Character::has_trait(), partial_con::id, player::is_player(), m_info, construction_group::name(), int_id< T >::obj(), map::partial_con_at(), map::partial_con_remove(), player_activity::placement, Character::pos(), query_yn(), map::tr_at(), tr_unfinished_construction, and trait_DEBUG_HS.
Referenced by game::examine(), and iexamine_function_from_string().
tree_hickory()
void iexamine::tree_hickory (player & p, const tripoint & examp)
Survival increases hickory root number per tree Survival speeds up hickory root digging
Definition at line 3482 of file iexamine.cpp.
{
    map &here = get_map();
    if( harvest_common( p, examp, false, false ) ) {
        here.ter_set( examp, here.get_ter_transforms_into( examp ) );
    }
    if( !p.has_quality( qual_DIG ) ) {
        p.add_msg_if_player( m_info, _( "You have no tool to dig with" ) );
        return;
    }
    if( p.is_player() &&
        !query_yn( _( "Dig up %s?  This kills the tree!" ), here.tername( examp ) ) ) {
        return;
    }
    ///\EFFECT_SURVIVAL increases hickory root number per tree
    here.spawn_item( p.pos(), itype_hickory_root, rng( 1, 3 + p.get_skill_level( skill_survival ) ), 0,
                     calendar::turn );
    here.ter_set( examp, t_tree_hickory_dead );
    ///\EFFECT_SURVIVAL speeds up hickory root digging
    p.moves -= to_moves<int>( 20_seconds ) / ( p.get_skill_level( skill_survival ) + 1 ) + 100;
}
References _, player::add_msg_if_player(), get_map(), Character::get_skill_level(), map::get_ter_transforms_into(), harvest_common(), visitable< T >::has_quality(), player::is_player(), itype_hickory_root, m_info, Creature::moves, Character::pos(), qual_DIG, query_yn(), rng(), skill_survival, map::spawn_item(), t_tree_hickory_dead, map::ter_set(), map::tername(), and calendar::turn.
Referenced by iexamine_function_from_string().
tree_maple()
void iexamine::tree_maple (player & p, const tripoint & examp)
Definition at line 3513 of file iexamine.cpp.
{
    if( !p.has_quality( quality_id( "DRILL" ) ) ) {
        add_msg( m_info, _( "You need a tool to drill the crust to tap this maple tree." ) );
        return;
    }
    if( !p.has_quality( quality_id( "HAMMER" ) ) ) {
        add_msg( m_info,
                 _( "You need a tool to hammer the spile into the crust to tap this maple tree." ) );
        return;
    }
    const inventory &crafting_inv = p.crafting_inventory();
    if( !crafting_inv.has_amount( itype_tree_spile, 1 ) ) {
        add_msg( m_info, _( "You need a %s to tap this maple tree." ),
                 item::nname( itype_tree_spile ) );
        return;
    }
    std::vector<item_comp> comps;
    comps.push_back( item_comp( itype_tree_spile, 1 ) );
    p.consume_items( comps, 1, is_crafting_component );
    p.mod_moves( -to_moves<int>( 20_seconds ) );
    map &here = get_map();
    here.ter_set( examp, t_tree_maple_tapped );
    auto cont_loc = maple_tree_sap_container();
    item *container = cont_loc.get_item();
    if( container ) {
        here.add_item_or_charges( examp, *container, false );
        cont_loc.remove_item();
    } else {
        add_msg( m_info, _( "No container added.  The sap will just spill on the ground." ) );
    }
}
References _, map::add_item_or_charges(), add_msg(), player::consume_items(), Character::crafting_inventory(), get_map(), visitable< T >::has_amount(), visitable< T >::has_quality(), is_crafting_component(), itype_tree_spile, m_info, maple_tree_sap_container(), Creature::mod_moves(), item::nname(), visitable< T >::remove_item(), t_tree_maple_tapped, and map::ter_set().
Referenced by iexamine_function_from_string().
tree_maple_tapped()
void iexamine::tree_maple_tapped (player & p, const tripoint & examp)
Definition at line 3554 of file iexamine.cpp.
{
    bool has_sap = false;
    item *container = nullptr;
    int charges = 0;
    const std::string maple_sap_name = item::nname( itype_maple_sap );
    map &here = get_map();
    map_stack items = here.i_at( examp );
    if( !items.empty() ) {
        item &it = items.only_item();
        if( it.is_bucket() || it.is_watertight_container() ) {
            container = &it;
            if( !it.is_container_empty() && it.contents.front().typeId() == itype_maple_sap ) {
                has_sap = true;
                charges = it.contents.front().charges;
            }
        }
    }
    enum options {
        REMOVE_TAP,
        ADD_CONTAINER,
        HARVEST_SAP,
        REMOVE_CONTAINER,
    };
    uilist selectmenu;
    selectmenu.addentry( REMOVE_TAP, true, MENU_AUTOASSIGN, _( "Remove tap" ) );
    selectmenu.addentry( ADD_CONTAINER, !container, MENU_AUTOASSIGN,
                         _( "Add a container to receive the %s" ), maple_sap_name );
    selectmenu.addentry( HARVEST_SAP, has_sap, MENU_AUTOASSIGN, _( "Harvest current %s (%d)" ),
                         maple_sap_name, charges );
    selectmenu.addentry( REMOVE_CONTAINER, container, MENU_AUTOASSIGN, _( "Remove container" ) );
    selectmenu.text = _( "Select an action" );
    selectmenu.query();
    switch( selectmenu.ret ) {
        case REMOVE_TAP: {
            if( !p.has_quality( quality_id( "HAMMER" ) ) ) {
                add_msg( m_info, _( "You need a hammering tool to remove the spile from the crust." ) );
                return;
            }
            item tree_spile( "tree_spile" );
            add_msg( _( "You remove the %s." ), tree_spile.tname( 1 ) );
            here.add_item_or_charges( p.pos(), tree_spile );
            if( container ) {
                here.add_item_or_charges( p.pos(), *container );
            }
            here.i_clear( examp );
            p.mod_moves( -to_moves<int>( 20_seconds ) );
            here.ter_set( examp, t_tree_maple );
            return;
        }
        case ADD_CONTAINER: {
            auto cont_loc = maple_tree_sap_container();
            container = cont_loc.get_item();
            if( container ) {
                here.add_item_or_charges( examp, *container, false );
                cont_loc.remove_item();
            } else {
                add_msg( m_info, _( "No container added.  The sap will just spill on the ground." ) );
            }
            return;
        }
        case HARVEST_SAP: {
            liquid_handler::handle_liquid_from_container( *container, PICKUP_RANGE );
            return;
        }
        case REMOVE_CONTAINER: {
            g->u.assign_activity( player_activity( pickup_activity_actor(
            { { item_location( map_cursor( examp ), container ), cata::nullopt, {} } }, g->u.pos() ) ) );
            return;
        }
        default:
            return;
    }
}
References _, map::add_item_or_charges(), add_msg(), uilist::addentry(), item::charges, item::contents, item_stack::empty(), item_contents::front(), g, get_map(), liquid_handler::handle_liquid_from_container(), visitable< T >::has_quality(), map::i_at(), map::i_clear(), item::is_bucket(), item::is_container_empty(), item::is_watertight_container(), itype_maple_sap, m_info, maple_tree_sap_container(), MENU_AUTOASSIGN, Creature::mod_moves(), item::nname(), cata::nullopt, item_stack::only_item(), PATH_INFO::options(), PICKUP_RANGE, Character::pos(), uilist::query(), visitable< T >::remove_item(), uilist::ret, t_tree_maple, map::ter_set(), uilist::text, item::tname(), and item::typeId().
Referenced by iexamine_function_from_string().
tree_marloss()
void iexamine::tree_marloss (player & p, const tripoint & examp)
Definition at line 3660 of file iexamine.cpp.
{
    map &here = get_map();
    if( p.has_trait( trait_THRESH_MYCUS ) ) {
        pick_plant( p, examp, itype_mycus_fruit, t_tree_fungal );
        if( p.has_trait( trait_M_DEPENDENT ) && one_in( 3 ) ) {
            // Folks have a better shot at keeping fed.
            add_msg( m_info,
                     _( "We have located a particularly vital nutrient deposit underneath this location." ) );
            add_msg( m_good, _( "Additional nourishment is available." ) );
            here.ter_set( examp, t_marloss_tree );
        }
    } else if( p.has_trait( trait_THRESH_MARLOSS ) ) {
        here.spawn_item( p.pos(), itype_mycus_fruit, 1, 0, calendar::turn );
        here.ter_set( examp, t_tree_fungal );
        add_msg( m_info, _( "The tree offers up a fruit, then shrivels into a fungal tree." ) );
    } else {
        pick_plant( p, examp, itype_marloss_berry, t_tree_fungal );
    }
}
References _, add_msg(), get_map(), Character::has_trait(), itype_marloss_berry, itype_mycus_fruit, m_good, m_info, one_in(), pick_plant(), Character::pos(), map::spawn_item(), t_marloss_tree, t_tree_fungal, map::ter_set(), trait_M_DEPENDENT, trait_THRESH_MARLOSS, trait_THRESH_MYCUS, and calendar::turn.
Referenced by iexamine_function_from_string(), and game::place_player().
use_furn_fake_item()
void iexamine::use_furn_fake_item (player & p, const tripoint & examp)
Definition at line 4027 of file iexamine.cpp.
{
    map &m = get_map();
    const tripoint_abs_ms abspos( m.getabs( examp ) );
    if( !m.has_furn( examp ) ) {
        debugmsg( "lost furniture at %s", examp.to_string() );
        return;
    }
    const furn_t &furniture = m.furn( examp ).obj();
    const std::vector<itype> item_type_list = furniture.crafting_pseudo_item_types();
    std::vector<itype> usable_item_types;
    std::vector<std::string> usable_item_names;
    if( item_type_list.empty() ) {
        debugmsg(
            "Furniture ( %s ) with use_furn_fake_item does not have fake item to use.",
            furniture.id.c_str()
        );
        return;
    }
    for( const itype &itt : item_type_list ) {
        if( !itt.has_use() ) {
            continue;
        }
        usable_item_types.push_back( itt );
        usable_item_names.push_back( itt.nname( 1 ) );
    }
    if( usable_item_types.empty() ) {
        debugmsg(
            "Furniture ( %s ) with use_furn_fake_item has no fake item with uses",
            furniture.id.c_str() );
        return;
    }
    int tool_index = 0;
    if( usable_item_types.size() > 1 ) {
        tool_index = uilist( _( "Which tool do you want to use?" ), usable_item_names );
        if( tool_index < 0 || static_cast<size_t>( tool_index ) >= usable_item_types.size() ) {
            tool_index = -1;
        }
    }
    if( tool_index < 0 ) {
        return;
    }
    const itype &cur_tool = usable_item_types.at( tool_index );
    item fake_item( cur_tool.get_id(), calendar::turn, 0 );
    const itype_id ammo = fake_item.ammo_default();
    fake_item.set_flag( "PSEUDO" );
    enum class charges_type {
        grid, ammo_from_map, none
    };
    charges_type charge_type = charges_type::none;
    fake_item.charges = 0;
    if( fake_item.has_flag( "USES_GRID_POWER" ) ) {
        const distribution_grid &grid = get_distribution_grid_tracker().grid_at( abspos );
        fake_item.charges = grid.get_resource();
        charge_type = charges_type::grid;
    } else if( ammo != itype_id::NULL_ID() ) {
        fake_item.charges = count_charges_in_list( &*ammo, m.i_at( examp ) );
        charge_type = charges_type::ammo_from_map;
    }
    const int original_charges = fake_item.charges;
    p.invoke_item( &fake_item );
    // HACK: Evil hack incoming
    activity_handlers::repair_activity_hack::patch_activity_for_furniture( g->u.activity, examp,
            cur_tool.get_id() );
    const int discharged_ammo = original_charges - fake_item.charges;
    if( discharged_ammo == 0 ) {
        return;
    }
    switch( charge_type ) {
        case charges_type::grid: {
            distribution_grid &grid = get_distribution_grid_tracker().grid_at( abspos );
            const int remainder = grid.mod_resource( -discharged_ammo );
            if( remainder != 0 ) {
                debugmsg( "Fake item %s discharged more charges than have in grid at %s.",
                          cur_tool.get_id().c_str(), abspos.to_string() );
            }
            return;
        }
        case charges_type::ammo_from_map: {
            int by_ref = discharged_ammo;
            m.use_charges( examp, 0, ammo->get_id(), by_ref );
            if( by_ref != 0 ) {
                debugmsg( "Discharged fake item %s more ammo than %s has at %s.",
                          cur_tool.get_id().c_str(),
                          furniture.id.c_str(),
                          examp.to_string()
                        );
            }
            return;
        }
        case charges_type::none:
            debugmsg( "Somehow changed charges of fake item %s without ammo type to %d.",
                      cur_tool.get_id().c_str(),
                      fake_item.charges
                    );
            return;
    }
}
References _, item::ammo_default(), string_id< T >::c_str(), item::charges, count_charges_in_list(), debugmsg, map::furn(), g, get_distribution_grid_tracker(), itype::get_id(), get_map(), distribution_grid::get_resource(), map::getabs(), distribution_grid_tracker::grid_at(), item::has_flag(), map::has_furn(), map::i_at(), Character::invoke_item(), distribution_grid::mod_resource(), none, string_id< itype >::NULL_ID(), int_id< T >::obj(), activity_handlers::repair_activity_hack::patch_activity_for_furniture(), item::set_flag(), coords::coord_point< Point, Origin, Scale >::to_string(), tripoint::to_string(), calendar::turn, and map::use_charges().
Referenced by iexamine_function_from_string().
vending()
void iexamine::vending (player & p, const tripoint & examp)
Generates vending machine UI and allows players to purchase contained items with a cash card.
Definition at line 674 of file iexamine.cpp.
{
    constexpr int moves_cost = to_turns<int>( 5_seconds );
    int money = p.charges_of( itype_cash_card );
    auto vend_items = get_map().i_at( examp );
    if( vend_items.empty() ) {
        add_msg( m_info, _( "The vending machine is empty." ) );
        return;
    }
    if( !money ) {
        popup( _( "You need some money on a cash card to buy things." ) );
    }
    int w_items_w = 0;
    int w_info_w = 0;
    int list_lines = 0;
    int lines_above = 0;
    int lines_below = 0;
    constexpr int first_item_offset = 3; // header size
    catacurses::window w;
    catacurses::window w_item_info;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const point padding( std::max( 0, TERMX - FULL_SCREEN_WIDTH ) / 4, std::max( 0,
                             TERMY - FULL_SCREEN_HEIGHT ) / 6 );
        const int window_h   = FULL_SCREEN_HEIGHT + std::max( 0, TERMY - FULL_SCREEN_HEIGHT ) * 2 / 3;
        const int window_w   = FULL_SCREEN_WIDTH + std::max( 0, TERMX - FULL_SCREEN_WIDTH ) / 2;
        w_items_w  = window_w / 2;
        w_info_w   = window_w - w_items_w;
        list_lines = window_h - 4; // minus for header and footer
        lines_above = list_lines / 2;                  // lines above the selector
        lines_below = list_lines / 2 + list_lines % 2; // lines below the selector
        w = catacurses::newwin( window_h, w_items_w,
                                padding );
        w_item_info = catacurses::newwin( window_h, w_info_w,
                                          padding + point( w_items_w, 0 ) );
        ui.position( padding, point( window_w, window_h ) );
    } );
    ui.mark_resize();
    bool used_machine = false;
    input_context ctxt( "VENDING_MACHINE" );
    ctxt.register_updown();
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    // Collate identical items.
    // First, build a map {item::tname} => {item_it, item_it, item_it...}
    using iterator_t = decltype( std::begin( vend_items ) ); // map_stack::iterator doesn't exist.
    std::map<std::string, std::vector<iterator_t>> item_map;
    for( auto it = std::begin( vend_items ); it != std::end( vend_items ); ++it ) {
        // |# {name}|
        // 123      4
        item_map[it->tname()].push_back( it );
    }
    // Next, put pointers to the pairs in the map in a vector to allow indexing.
    std::vector<std::map<std::string, std::vector<iterator_t>>::value_type *> item_list;
    item_list.reserve( item_map.size() );
    for( auto &pair : item_map ) {
        item_list.emplace_back( &pair );
    }
    int cur_pos = 0;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        const int num_items = item_list.size();
        const int page_size = std::min( num_items, list_lines );
        werase( w );
        wborder( w, LINE_XOXO, LINE_XOXO, LINE_OXOX, LINE_OXOX,
                 LINE_OXXO, LINE_OOXX, LINE_XXOO, LINE_XOOX );
        mvwhline( w, point( 1, first_item_offset - 1 ), LINE_OXOX, w_items_w - 2 );
        mvwaddch( w, point( 0, first_item_offset - 1 ), LINE_XXXO ); // |-
        mvwaddch( w, point( w_items_w - 1, first_item_offset - 1 ), LINE_XOXX ); // -|
        trim_and_print( w, point( 2, 1 ), w_items_w - 3, c_light_gray,
                        _( "Money left: %s" ), format_money( money ) );
        // Keep the item selector centered in the page.
        int page_beg;
        if( cur_pos < num_items - cur_pos ) {
            page_beg = std::max( 0, cur_pos - lines_above );
        } else {
            int page_end = std::min( num_items, cur_pos + lines_below );
            page_beg = std::max( 0, page_end - list_lines );
        }
        for( int line = 0; line < page_size; ++line ) {
            const int i = page_beg + line;
            const auto color = ( i == cur_pos ) ? h_light_gray : c_light_gray;
            const auto &elem = item_list[i];
            const int count = elem->second.size();
            const char c = ( count < 10 ) ? ( '0' + count ) : '*';
            trim_and_print( w, point( 1, first_item_offset + line ), w_items_w - 3, color, "%c %s", c,
                            elem->first.c_str() );
        }
        draw_scrollbar( w, cur_pos, list_lines, num_items, point( 0, first_item_offset ) );
        wnoutrefresh( w );
        // Item info
        auto &cur_items = item_list[static_cast<size_t>( cur_pos )]->second;
        auto &cur_item  = cur_items.back();
        werase( w_item_info );
        // | {line}|
        // 12      3
        fold_and_print( w_item_info, point( 2, 1 ), w_info_w - 3, c_light_gray, cur_item->info_string() );
        wborder( w_item_info, LINE_XOXO, LINE_XOXO, LINE_OXOX, LINE_OXOX,
                 LINE_OXXO, LINE_OOXX, LINE_XXOO, LINE_XOOX );
        //+<{name}>+
        //12      34
        const std::string name = utf8_truncate( cur_item->display_name(),
                                                static_cast<size_t>( w_info_w - 4 ) );
        mvwprintw( w_item_info, point_east, "<%s>", name );
        wnoutrefresh( w_item_info );
    } );
    for( ;; ) {
        ui_manager::redraw();
        const int num_items = item_list.size();
        // Item info
        auto &cur_items = item_list[static_cast<size_t>( cur_pos )]->second;
        auto &cur_item  = cur_items.back();
        const std::string &action = ctxt.handle_input();
        if( action == "DOWN" ) {
            cur_pos = ( cur_pos + 1 ) % num_items;
        } else if( action == "UP" ) {
            cur_pos = ( cur_pos + num_items - 1 ) % num_items;
        } else if( action == "CONFIRM" ) {
            const int iprice = cur_item->price( false );
            if( iprice > money ) {
                popup( _( "You can't afford that item." ) );
                continue;
            }
            if( !used_machine ) {
                used_machine = true;
                p.moves -= moves_cost;
            }
            money -= iprice;
            p.use_charges( itype_cash_card, iprice );
            p.i_add_or_drop( *cur_item );
            vend_items.erase( cur_item );
            cur_items.pop_back();
            if( !cur_items.empty() ) {
                continue;
            }
            item_list.erase( std::begin( item_list ) + cur_pos );
            if( item_list.empty() ) {
                add_msg( _( "With a beep, the empty vending machine shuts down." ) );
                return;
            } else if( cur_pos == num_items - 1 ) {
                cur_pos--;
            }
        } else if( action == "QUIT" ) {
            break;
        }
    }
}
References _, action, add_msg(), c, c_light_gray, visitable< T >::charges_of(), color(), detail::count(), draw_scrollbar(), fold_and_print(), format_money(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_map(), h_light_gray, input_context::handle_input(), Character::i_add_or_drop(), map::i_at(), itype_cash_card, line(), LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XOXX, LINE_XXOO, LINE_XXXO, m_info, Creature::moves, catacurses::mvwaddch(), catacurses::mvwhline(), catacurses::mvwprintw(), om_direction::name(), catacurses::newwin(), point_east, popup(), ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), second, TERMX, TERMY, trim_and_print(), Character::use_charges(), utf8_truncate(), catacurses::wborder(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by iexamine_function_from_string().
water_source()
void iexamine::water_source (player & p, const tripoint & examp)
Definition at line 3869 of file iexamine.cpp.
{
    map &here = get_map();
    item water = here.water_from( examp );
    // TODO: use me
    ( void ) p;
    liquid_handler::handle_liquid( water, nullptr, 0, &examp );
}
References get_map(), liquid_handler::handle_liquid(), and map::water_from().
Referenced by colorized_ter_name_flags_at(), iexamine_function_from_string(), and map::water_from().
workbench()
void iexamine::workbench (player & p, const tripoint & examp)
Definition at line 6194 of file iexamine.cpp.
{
    // Dummied out and only used for function equality check
}
Referenced by game::examine(), finalize_furn(), iexamine_function_from_string(), and set_item_map_or_vehicle().