Cataclysm BN: avatar_action Namespace Reference
avatar_action Namespace Reference
Functions
void eat (avatar &you)
Eat food or fuel 'E' (or 'a')
void eat (avatar &you, item_location loc)
bool eat_here (avatar &you)
bool move (avatar &you, map &m, const tripoint &d)
bool move (avatar &you, map &m, const point &d)
bool ramp_move (avatar &you, map &m, const tripoint &dest)
void swim (map &m, avatar &you, const tripoint &p)
Handles swimming by the player.
void autoattack (avatar &you, map &m)
void mend (avatar &you, item_location loc)
void wield ()
Prompt to wield some item.
void wield (item_location &loc)
Wield specified item.
void reload (item_location &loc, bool prompt=false, bool empty=true)
Reload specified item.
void reload_item ()
Prompt to reload some item.
void reload_wielded (bool prompt=false)
Reload wielded item.
void reload_weapon (bool try_everything=true)
Reload a wielded gun/tool.
void unload (avatar &you)
Prompts to unload some item.
bool can_fire_weapon (avatar &you, const map &m, const item &weapon)
Checks if the weapon is valid and if the player meets certain conditions for firing it.
void fire_wielded_weapon (avatar &you)
Checks if the wielded weapon is a gun and can be fired then starts interactive aiming.
void fire_ranged_mutation (avatar &you, const item &fake_gun)
Stores fake gun specified by the mutation and starts interactive aiming.
void fire_ranged_bionic (avatar &you, const item &fake_gun, const units::energy &cost_per_shot)
Stores fake gun specified by the bionic and starts interactive aiming.
void fire_turret_manual (avatar &you, map &m, turret_data &turret)
Checks if the player can manually (with their 2 hands, not via vehicle controls) fire a turret and then starts interactive aiming.
void plthrow (avatar &you, item_location loc, const cata::optional< tripoint > &blind_throw_from_pos=cata::nullopt)
void use_item (avatar &you, item_location &loc)
void use_item (avatar &you)
Function Documentation
autoattack()
void avatar_action::autoattack (avatar & you, map & m)
Definition at line 586 of file avatar_action.cpp.
{
    int reach = you.weapon.reach_range( you );
    std::vector<Creature *> critters = ranged::targetable_creatures( you, reach );
    critters.erase( std::remove_if( critters.begin(), critters.end(), []( const Creature * c ) {
        if( !c->is_npc() ) {
            return false;
        }
        return !dynamic_cast<const npc *>( c )->is_enemy();
    } ), critters.end() );
    if( critters.empty() ) {
        add_msg( m_info, _( "No hostile creature in reach.  Waiting a turn." ) );
        if( g->check_safe_mode_allowed() ) {
            character_funcs::do_pause( you );
        }
        return;
    }
    Creature &best = **std::max_element( critters.begin(), critters.end(),
    []( const Creature * l, const Creature * r ) {
        return rate_critter( *l ) > rate_critter( *r );
    } );
    const tripoint diff = best.pos() - you.pos();
    if( std::abs( diff.x ) <= 1 && std::abs( diff.y ) <= 1 && diff.z == 0 ) {
        move( you, m, tripoint( diff.xy(), 0 ) );
        return;
    }
    you.reach_attack( best.pos() );
}
References c, npc::is_enemy(), item::reach_range(), ranged::targetable_creatures(), and Character::weapon.
Referenced by game::handle_action().
can_fire_weapon()
bool avatar_action::can_fire_weapon (avatar & you, const map & m, const item & weapon)
Checks if the weapon is valid and if the player meets certain conditions for firing it.
Used for validating ACT_AIM and turret weapon
Returns
True if all conditions are true, otherwise false.
Definition at line 618 of file avatar_action.cpp.
{
    if( !weapon.is_gun() ) {
        debugmsg( "Expected item to be a gun" );
        return false;
    }
    if( you.has_effect( effect_relax_gas ) ) {
        if( one_in( 5 ) ) {
            add_msg( m_good, _( "Your eyes steel, and you raise your weapon!" ) );
        } else {
            you.moves -= rng( 2, 5 ) * 10;
            add_msg( m_bad, _( "You can't fire your weapon, it's too heavy…" ) );
            return false;
        }
    }
    std::vector<std::string> messages;
    const gun_mode &mode = weapon.gun_current_mode();
    bool check_common = ranged::gunmode_checks_common( you, m, messages, mode );
    bool check_weapon = ranged::gunmode_checks_weapon( you, m, messages, mode );
    bool can_use_mode = check_common && check_weapon;
    if( can_use_mode ) {
        return true;
    }
    for( const std::string &message : messages ) {
        add_msg( m_info, message );
    }
    return false;
}
References _, add_msg(), debugmsg, effect_relax_gas, item::gun_current_mode(), ranged::gunmode_checks_common(), ranged::gunmode_checks_weapon(), Creature::has_effect(), item::is_gun(), m_bad, m_good, m_info, mapgen_defer::message, Creature::moves, one_in(), rng(), and Character::weapon.
Referenced by aim_activity_actor::do_turn().
eat() [1/2]
void avatar_action::eat (avatar & you)
Eat food or fuel 'E' (or 'a')
Definition at line 823 of file avatar_action.cpp.
{
    item_location loc = game_menus::inv::consume( you );
    avatar_action::eat( you, loc );
}
References game_menus::inv::consume(), and eat().
Referenced by activity_handlers::consume_drink_menu_do_turn(), activity_handlers::consume_food_menu_do_turn(), activity_handlers::consume_meds_menu_do_turn(), eat(), activity_handlers::eat_menu_do_turn(), find_auto_consume(), game::handle_action(), game::open_consume_item_menu(), and examine_item_menu::run().
eat() [2/2]
void avatar_action::eat (avatar & you, item_location loc)
Definition at line 829 of file avatar_action.cpp.
{
    if( !loc ) {
        you.cancel_activity();
        add_msg( _( "Never mind." ) );
        return;
    }
    item *it = loc.get_item();
    if( loc.where() == item_location::type::character ) {
        you.consume( loc );
    } else if( you.consume_item( *it ) ) {
        if( it->is_food_container() || !you.can_consume_as_is( *it ) ) {
            it->remove_item( it->contents.front() );
            add_msg( _( "You leave the empty %s." ), it->tname() );
        } else {
            loc.remove_item();
        }
    }
    if( g->u.get_value( "THIEF_MODE_KEEP" ) != "YES" ) {
        g->u.set_value( "THIEF_MODE", "THIEF_ASK" );
    }
}
References _, add_msg(), Character::can_consume_as_is(), Character::cancel_activity(), item_location::character, Character::consume(), Character::consume_item(), item::contents, item_contents::front(), g, item_location::get_item(), item::is_food_container(), item_location::remove_item(), visitable< T >::remove_item(), item::tname(), and item_location::where().
eat_here()
bool avatar_action::eat_here (avatar & you)
Definition at line 769 of file avatar_action.cpp.
{
    map &here = get_map();
    if( ( you.has_active_mutation( trait_RUMINANT ) || you.has_active_mutation( trait_GRAZER ) ) &&
        ( here.ter( you.pos() ) == t_underbrush || here.ter( you.pos() ) == t_shrub ) ) {
        item food( itype_underbrush, calendar::turn, 1 );
        if( you.get_stored_kcal() > you.max_stored_kcal() -
            food.get_comestible()->default_nutrition.kcal ) {
            add_msg( _( "You're too full to eat the leaves from the %s." ), here.ter( you.pos() )->name() );
            return true;
        } else {
            you.moves -= 400;
            here.ter_set( you.pos(), t_grass );
            add_msg( _( "You eat the underbrush." ) );
            you.eat( food );
            return true;
        }
    }
    if( you.has_active_mutation( trait_GRAZER ) && ( here.ter( you.pos() ) == t_grass ||
            here.ter( you.pos() ) == t_grass_long || here.ter( you.pos() ) == t_grass_tall ) ) {
        item food( item( itype_grass, calendar::turn, 1 ) );
        if( you.get_stored_kcal() > you.max_stored_kcal() -
            food.get_comestible()->default_nutrition.kcal ) {
            add_msg( _( "You're too full to graze." ) );
            return true;
        } else {
            you.moves -= 400;
            add_msg( _( "You eat the grass." ) );
            you.eat( food );
            if( here.ter( you.pos() ) == t_grass_tall ) {
                here.ter_set( you.pos(), t_grass_long );
            } else if( here.ter( you.pos() ) == t_grass_long ) {
                here.ter_set( you.pos(), t_grass );
            } else {
                here.ter_set( you.pos(), t_dirt );
            }
            return true;
        }
    }
    if( you.has_active_mutation( trait_GRAZER ) ) {
        if( here.ter( you.pos() ) == t_grass_golf ) {
            add_msg( _( "This grass is too short to graze." ) );
            return true;
        } else if( here.ter( you.pos() ) == t_grass_dead ) {
            add_msg( _( "This grass is dead and too mangled for you to graze." ) );
            return true;
        } else if( here.ter( you.pos() ) == t_grass_white ) {
            add_msg( _( "This grass is tainted with paint and thus inedible." ) );
            return true;
        }
    }
    return false;
}
References _, add_msg(), Character::eat(), item::get_comestible(), get_map(), Character::get_stored_kcal(), Character::has_active_mutation(), itype_grass, itype_underbrush, Character::max_stored_kcal(), Creature::moves, map_data_common_t::name(), Character::pos(), t_dirt, t_grass, t_grass_dead, t_grass_golf, t_grass_long, t_grass_tall, t_grass_white, t_shrub, t_underbrush, map::ter(), map::ter_set(), trait_GRAZER, trait_RUMINANT, and calendar::turn.
Referenced by game::handle_action().
fire_ranged_bionic()
void avatar_action::fire_ranged_bionic (avatar & you, const item & fake_gun, const units::energy & cost_per_shot)
Stores fake gun specified by the bionic and starts interactive aiming.
Definition at line 732 of file avatar_action.cpp.
{
    you.assign_activity( aim_activity_actor::use_bionic( fake_gun, cost_per_shot ), false );
}
References Character::assign_activity(), and aim_activity_actor::use_bionic().
Referenced by Character::activate_bionic().
fire_ranged_mutation()
void avatar_action::fire_ranged_mutation (avatar & you, const item & fake_gun)
Stores fake gun specified by the mutation and starts interactive aiming.
Definition at line 727 of file avatar_action.cpp.
{
    you.assign_activity( aim_activity_actor::use_mutation( fake_gun ), false );
}
References Character::assign_activity(), and aim_activity_actor::use_mutation().
Referenced by Character::activate_mutation().
fire_turret_manual()
void avatar_action::fire_turret_manual (avatar & you, map & m, turret_data & turret)
Checks if the player can manually (with their 2 hands, not via vehicle controls) fire a turret and then starts interactive aiming.
Assumes that the turret is on player position.
Definition at line 738 of file avatar_action.cpp.
{
    if( !can_fire_turret( you, m, turret ) ) {
        return;
    }
    g->temp_exit_fullscreen();
    target_handler::trajectory trajectory = target_handler::mode_turret_manual( you, turret );
    if( !trajectory.empty() ) {
        turret.fire( you, trajectory.back() );
    }
    g->reenter_fullscreen();
}
References can_fire_turret(), turret_data::fire(), g, and target_handler::mode_turret_manual().
Referenced by fire().
fire_wielded_weapon()
void avatar_action::fire_wielded_weapon (avatar & you)
Checks if the wielded weapon is a gun and can be fired then starts interactive aiming.
Definition at line 706 of file avatar_action.cpp.
{
    item &weapon = you.weapon;
    if( weapon.is_gunmod() ) {
        add_msg( m_info,
                 _( "The %s must be attached to a gun, it can not be fired separately." ),
                 weapon.tname() );
        return;
    } else if( !weapon.is_gun() ) {
        return;
    } else if( weapon.ammo_data() && weapon.type->gun &&
               !weapon.ammo_types().count( weapon.ammo_data()->ammo->type ) ) {
        std::string ammoname = weapon.ammo_current()->nname( 1 );
        add_msg( m_info, _( "The %s can't be fired while loaded with incompatible ammunition %s" ),
                 weapon.tname(), ammoname );
        return;
    }
    you.assign_activity( aim_activity_actor::use_wielded(), false );
}
References _, add_msg(), itype::ammo, item::ammo_current(), item::ammo_data(), item::ammo_types(), Character::assign_activity(), itype::gun, item::is_gun(), item::is_gunmod(), m_info, itype::nname(), item::tname(), item::type, aim_activity_actor::use_wielded(), and Character::weapon.
Referenced by Character::activate_bionic(), fire(), game::handle_action(), and game::list_items_monsters().
mend()
void avatar_action::mend (avatar & you, item_location loc)
Definition at line 753 of file avatar_action.cpp.
{
    if( !loc ) {
        if( you.is_armed() ) {
            loc = item_location( you, &you.weapon );
        } else {
            add_msg( m_info, _( "You're not wielding anything." ) );
            return;
        }
    }
    if( you.has_item( *loc ) ) {
        avatar_funcs::mend_item( you, item_location( loc ) );
    }
}
References _, add_msg(), visitable< T >::has_item(), Character::is_armed(), m_info, avatar_funcs::mend_item(), and Character::weapon.
Referenced by game::handle_action(), and examine_item_menu::run().
move() [1/2]
bool avatar_action::move (avatar & you, map & m, const point & d) inline
Definition at line 29 of file avatar_action.h.
{
    return move( you, m, tripoint( d, 0 ) );
}
References move().
move() [2/2]
bool avatar_action::move (avatar & you, map & m, const tripoint & d)
Definition at line 96 of file avatar_action.cpp.
{
    if( ( !g->check_safe_mode_allowed() ) || you.has_active_mutation( trait_SHELL2 ) ) {
        if( you.has_active_mutation( trait_SHELL2 ) ) {
            add_msg( m_warning, _( "You can't move while in your shell.  Deactivate it to go mobile." ) );
        }
        return false;
    }
    const bool is_riding = you.is_mounted();
    tripoint dest_loc;
    if( d.z == 0 && you.has_effect( effect_stunned ) ) {
        dest_loc.x = rng( you.posx() - 1, you.posx() + 1 );
        dest_loc.y = rng( you.posy() - 1, you.posy() + 1 );
        dest_loc.z = you.posz();
    } else {
        dest_loc.x = you.posx() + d.x;
        dest_loc.y = you.posy() + d.y;
        dest_loc.z = you.posz() + d.z;
    }
    if( dest_loc == you.pos() ) {
        // Well that sure was easy
        return true;
    }
    bool via_ramp = false;
    if( m.has_flag( TFLAG_RAMP_UP, dest_loc ) ) {
        dest_loc.z += 1;
        via_ramp = true;
    } else if( m.has_flag( TFLAG_RAMP_DOWN, dest_loc ) ) {
        dest_loc.z -= 1;
        via_ramp = true;
    }
    if( m.has_flag( TFLAG_MINEABLE, dest_loc ) && g->mostseen == 0 &&
        get_option<bool>( "AUTO_FEATURES" ) && get_option<bool>( "AUTO_MINING" ) &&
        !m.veh_at( dest_loc ) && !you.is_underwater() && !you.has_effect( effect_stunned ) &&
        !is_riding ) {
        if( you.weapon.has_flag( flag_DIG_TOOL ) ) {
            if( you.weapon.type->can_use( "JACKHAMMER" ) && you.weapon.ammo_sufficient() ) {
                you.invoke_item( &you.weapon, "JACKHAMMER", dest_loc );
                // don't move into the tile until done mining
                you.defer_move( dest_loc );
                return true;
            } else if( you.weapon.type->can_use( "PICKAXE" ) ) {
                you.invoke_item( &you.weapon, "PICKAXE", dest_loc );
                // don't move into the tile until done mining
                you.defer_move( dest_loc );
                return true;
            }
        }
        if( you.has_trait( trait_BURROW ) ) {
            item burrowing_item( itype_id( "fake_burrowing" ) );
            you.invoke_item( &burrowing_item, "BURROW", dest_loc );
            // don't move into the tile until done mining
            you.defer_move( dest_loc );
            return true;
        }
    }
    // If the player is *attempting to* move on the X axis, update facing direction of their sprite to match.
    point new_d( dest_loc.xy() + point( -you.posx(), -you.posy() ) );
    if( !tile_iso ) {
        if( new_d.x > 0 ) {
            you.facing = FD_RIGHT;
            if( is_riding ) {
                you.mounted_creature->facing = FD_RIGHT;
            }
        } else if( new_d.x < 0 ) {
            you.facing = FD_LEFT;
            if( is_riding ) {
                you.mounted_creature->facing = FD_LEFT;
            }
        }
    } else {
        //
        // iso:
        //
        // right key            =>  +x -y       FD_RIGHT
        // left key             =>  -x +y       FD_LEFT
        // up key               =>  +x +y       ______
        // down key             =>  -x -y       ______
        // y: left-up key       =>  __ +y       FD_LEFT
        // u: right-up key      =>  +x __       FD_RIGHT
        // b: left-down key     =>  -x __       FD_LEFT
        // n: right-down key    =>  __ -y       FD_RIGHT
        //
        // right key            =>  +x -y       FD_RIGHT
        // u: right-up key      =>  +x __       FD_RIGHT
        // n: right-down key    =>  __ -y       FD_RIGHT
        // up key               =>  +x +y       ______
        // down key             =>  -x -y       ______
        // left key             =>  -x +y       FD_LEFT
        // y: left-up key       =>  __ +y       FD_LEFT
        // b: left-down key     =>  -x __       FD_LEFT
        //
        // right key            =>  +x +y       FD_RIGHT
        // u: right-up key      =>  +x __       FD_RIGHT
        // n: right-down key    =>  __ +y       FD_RIGHT
        // up key               =>  +x -y       ______
        // left key             =>  -x -y       FD_LEFT
        // b: left-down key     =>  -x __       FD_LEFT
        // y: left-up key       =>  __ -y       FD_LEFT
        // down key             =>  -x +y       ______
        //
        if( new_d.x >= 0 && new_d.y >= 0 ) {
            you.facing = FD_RIGHT;
            if( is_riding ) {
                auto mons = you.mounted_creature.get();
                mons->facing = FD_RIGHT;
            }
        }
        if( new_d.y <= 0 && new_d.x <= 0 ) {
            you.facing = FD_LEFT;
            if( is_riding ) {
                auto mons = you.mounted_creature.get();
                mons->facing = FD_LEFT;
            }
        }
    }
    if( you.has_effect( effect_amigara ) ) {
        int curdist = INT_MAX;
        int newdist = INT_MAX;
        const tripoint minp = tripoint( 0, 0, you.posz() );
        const tripoint maxp = tripoint( MAPSIZE_X, MAPSIZE_Y, you.posz() );
        for( const tripoint &pt : m.points_in_rectangle( minp, maxp ) ) {
            if( m.ter( pt ) == t_fault ) {
                int dist = rl_dist( pt, you.pos() );
                if( dist < curdist ) {
                    curdist = dist;
                }
                dist = rl_dist( pt, dest_loc );
                if( dist < newdist ) {
                    newdist = dist;
                }
            }
        }
        if( newdist > curdist ) {
            add_msg( m_info, _( "You cannot pull yourself away from the faultline…" ) );
            return false;
        }
    }
    dbg( DL::Debug ) << "game:plmove: From " << you.pos() << " to " << dest_loc;
    // Check if our movement is actually an attack on a monster or npc
    // Are we displacing a monster?
    bool attacking = false;
    if( g->critter_at( dest_loc ) ) {
        attacking = true;
    }
    if( !you.move_effects( attacking ) ) {
        you.moves -= 100;
        return false;
    }
    if( m.obstructed_by_vehicle_rotation( you.pos(), dest_loc ) ) {
        add_msg( _( "You can't walk through that vehicle's wall." ) );
        return false;
    }
    if( monster *const mon_ptr = g->critter_at<monster>( dest_loc, true ) ) {
        monster &critter = *mon_ptr;
        if( critter.friendly == 0 &&
            !critter.has_effect( effect_pet ) ) {
            if( you.is_auto_moving() ) {
                add_msg( m_warning, _( "Monster in the way.  Auto-move canceled." ) );
                add_msg( m_info, _( "Move into the monster to attack." ) );
                you.clear_destination();
                return false;
            } else {
            }
            if( you.has_effect( effect_relax_gas ) ) {
                if( one_in( 8 ) ) {
                    add_msg( m_good, _( "Your willpower asserts itself, and so do you!" ) );
                } else {
                    you.moves -= rng( 2, 8 ) * 10;
                    add_msg( m_bad, _( "You're too pacified to strike anything…" ) );
                    return false;
                }
            }
            you.melee_attack( critter, true );
            if( critter.is_hallucination() ) {
                critter.die( &you );
            }
            g->draw_hit_mon( dest_loc, critter, critter.is_dead() );
            return false;
        } else if( critter.has_flag( MF_IMMOBILE ) || critter.has_effect( effect_harnessed ) ||
                   critter.has_effect( effect_ridden ) ) {
            add_msg( m_info, _( "You can't displace your %s." ), critter.name() );
            return false;
        }
        // Successful displacing is handled (much) later
    }
    // If not a monster, maybe there's an NPC there
    if( npc *const np_ = g->critter_at<npc>( dest_loc ) ) {
        npc &np = *np_;
        if( you.is_auto_moving() ) {
            add_msg( _( "NPC in the way, Auto-move canceled." ) );
            add_msg( m_info, _( "Move into the NPC to interact or attack." ) );
            you.clear_destination();
            return false;
        }
        if( !np.is_enemy() ) {
            g->npc_menu( np );
            return false;
        }
        you.melee_attack( np, true );
        np.make_angry();
        return false;
    }
    // GRAB: pre-action checking.
    int dpart = -1;
    const optional_vpart_position vp0 = m.veh_at( you.pos() );
    vehicle *const veh0 = veh_pointer_or_null( vp0 );
    const optional_vpart_position vp1 = m.veh_at( dest_loc );
    vehicle *const veh1 = veh_pointer_or_null( vp1 );
    bool veh_closed_door = false;
    bool outside_vehicle = ( veh0 == nullptr || veh0 != veh1 );
    if( veh1 != nullptr ) {
        dpart = veh1->next_part_to_open( vp1->part_index(), outside_vehicle );
        veh_closed_door = dpart >= 0 && !veh1->part( dpart ).open;
    }
    if( veh0 != nullptr && std::abs( veh0->velocity ) > 100 ) {
        if( veh1 == nullptr ) {
            if( query_yn( _( "Dive from moving vehicle?" ) ) ) {
                g->moving_vehicle_dismount( dest_loc );
            }
            return false;
        } else if( veh1 != veh0 ) {
            add_msg( m_info, _( "There is another vehicle in the way." ) );
            return false;
        } else if( !vp1.part_with_feature( "BOARDABLE", true ) ) {
            add_msg( m_info, _( "That part of the vehicle is currently unsafe." ) );
            return false;
        }
    }
    bool toSwimmable = m.has_flag( flag_SWIMMABLE, dest_loc );
    bool toDeepWater = m.has_flag( TFLAG_DEEP_WATER, dest_loc );
    bool fromSwimmable = m.has_flag( flag_SWIMMABLE, you.pos() );
    bool fromDeepWater = m.has_flag( TFLAG_DEEP_WATER, you.pos() );
    bool fromBoat = veh0 != nullptr && veh0->is_in_water();
    bool toBoat = veh1 != nullptr && veh1->is_in_water();
    if( is_riding ) {
        if( !you.check_mount_will_move( dest_loc ) ) {
            if( you.is_auto_moving() ) {
                you.clear_destination();
            }
            you.moves -= 20;
            return false;
        }
    }
    // Dive into water!
    if( toSwimmable && toDeepWater && !toBoat ) {
        // Requires confirmation if we were on dry land previously
        if( is_riding ) {
            auto mon = you.mounted_creature.get();
            if( !mon->swims() || mon->get_size() < you.get_size() + 2 ) {
                add_msg( m_warning, _( "The %s cannot swim while it is carrying you!" ), mon->get_name() );
                return false;
            }
        }
        if( ( fromSwimmable && fromDeepWater && !fromBoat ) || query_yn( _( "Dive into the water?" ) ) ) {
            if( ( !fromDeepWater || fromBoat ) && you.swim_speed() < 500 ) {
                add_msg( _( "You start swimming." ) );
                add_msg( m_info, _( "%s to dive underwater." ),
                         press_x( ACTION_MOVE_DOWN ) );
            }
            avatar_action::swim( get_map(), get_avatar(), dest_loc );
        }
        g->on_move_effects();
        return true;
    }
    //Wooden Fence Gate (or equivalently walkable doors):
    // open it if we are walking
    // vault over it if we are running
    if( m.passable_ter_furn( dest_loc )
        && you.movement_mode_is( CMM_WALK )
        && m.open_door( dest_loc, !m.is_outside( you.pos() ) ) ) {
        you.moves -= 100;
        // if auto-move is on, continue moving next turn
        if( you.is_auto_moving() ) {
            you.defer_move( dest_loc );
        }
        return true;
    }
    if( g->walk_move( dest_loc, via_ramp ) ) {
        return true;
    }
    if( veh_closed_door ) {
        if( !veh1->handle_potential_theft( you ) ) {
            return true;
        } else {
            if( outside_vehicle ) {
                veh1->open_all_at( dpart );
            } else {
                veh1->open( dpart );
                add_msg( _( "You open the %1$s's %2$s." ), veh1->name,
                         veh1->part_info( dpart ).name() );
            }
        }
        you.moves -= 100;
        // if auto-move is on, continue moving next turn
        if( you.is_auto_moving() ) {
            you.defer_move( dest_loc );
        }
        return true;
    }
    if( m.furn( dest_loc ) != f_safe_c && m.open_door( dest_loc, !m.is_outside( you.pos() ) ) ) {
        you.moves -= 100;
        // if auto-move is on, continue moving next turn
        if( you.is_auto_moving() ) {
            you.defer_move( dest_loc );
        }
        return true;
    }
    // Invalid move
    const bool waste_moves = you.is_blind() || you.has_effect( effect_stunned );
    if( waste_moves || dest_loc.z != you.posz() ) {
        add_msg( _( "You bump into the %s!" ), m.obstacle_name( dest_loc ) );
        // Only lose movement if we're blind
        if( waste_moves ) {
            you.moves -= 100;
        }
    } else if( m.ter( dest_loc ) == t_door_locked || m.ter( dest_loc ) == t_door_locked_peep ||
               m.ter( dest_loc ) == t_door_locked_alarm || m.ter( dest_loc ) == t_door_locked_interior ) {
        // Don't drain move points for learning something you could learn just by looking
        add_msg( _( "That door is locked!" ) );
    } else if( m.ter( dest_loc ) == t_door_bar_locked ) {
        add_msg( _( "You rattle the bars but the door is locked!" ) );
    }
    return false;
}
References _, ACTION_MOVE_DOWN, add_msg(), item::ammo_sufficient(), itype::can_use(), Character::check_mount_will_move(), Character::clear_destination(), CMM_WALK, dbg, Debug, Character::defer_move(), monster::die(), effect_amigara, effect_harnessed, effect_pet, effect_relax_gas, effect_ridden, effect_stunned, f_safe_c, Creature::facing, FD_LEFT, FD_RIGHT, flag_DIG_TOOL(), flag_SWIMMABLE(), monster::friendly, map::furn(), g, get_avatar(), get_map(), Character::get_size(), vehicle::handle_potential_theft(), Character::has_active_mutation(), Creature::has_effect(), item::has_flag(), map::has_flag(), monster::has_flag(), Character::has_trait(), avatar::invoke_item(), Character::is_auto_moving(), Character::is_blind(), monster::is_dead(), npc::is_enemy(), monster::is_hallucination(), vehicle::is_in_water(), Character::is_mounted(), map::is_outside(), Creature::is_underwater(), m_bad, m_good, m_info, m_warning, npc::make_angry(), MAPSIZE_X, MAPSIZE_Y, Character::melee_attack(), MF_IMMOBILE, Character::mounted_creature, Character::move_effects(), Character::movement_mode_is(), Creature::moves, vpart_info::name(), monster::name(), vehicle::name, vehicle::next_part_to_open(), map::obstacle_name(), map::obstructed_by_vehicle_rotation(), one_in(), vehicle_part::open, vehicle::open(), vehicle::open_all_at(), map::open_door(), vehicle::part(), vehicle::part_info(), optional_vpart_position::part_with_feature(), map::passable_ter_furn(), map::points_in_rectangle(), Character::pos(), Character::posx(), Character::posy(), Character::posz(), press_x(), query_yn(), rl_dist(), rng(), swim(), Character::swim_speed(), t_door_bar_locked, t_door_locked, t_door_locked_alarm, t_door_locked_interior, t_door_locked_peep, t_fault, map::ter(), TFLAG_DEEP_WATER, TFLAG_MINEABLE, TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, tile_iso, trait_BURROW, trait_SHELL2, item::type, map::veh_at(), veh_pointer_or_null(), vehicle::velocity, Character::weapon, point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, and tripoint::z.
Referenced by activity_on_turn_wear(), explosion_handler::explosion_queue::add(), Item_factory::add_actor(), MonsterGenerator::add_attack(), Item_factory::add_entry(), Item_group::add_entry(), Trait_group_collection::add_entry(), Trait_group_distribution::add_entry(), mutation_branch::add_entry(), MapgenRemovePartHandler::add_item_or_charges(), DefaultRemovePartHandler::add_item_or_charges(), inventory_selector::add_items(), mod_manager::add_mods(), add_msg(), Messages::add_msg(), anonymous_namespace{messages.cpp}::messages_impl::add_msg_string(), overmap::add_note(), map::add_vehicle(), map::add_vehicle_to_map(), worldfactory::add_world(), assign_map_from_array(), buy_helper(), cata_ifstream::cata_ifstream(), cata_ofstream::cata_ofstream(), veh_interact::complete_vehicle(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::consolidate(), copy_file(), cata_libintl::trans_library::create(), MonsterGenerator::create_actor(), diary::deserialize(), vehicle::deserialize(), map::detach_vehicle(), crafting::disassemble_all(), map::displace_vehicle(), basecamp::distribute_food(), veh_interact::do_install(), pickup::do_pickup(), npc::do_reload(), move_items_activity_actor::do_turn(), target_ui::draw_controls_list(), explosion_handler::draw_custom_explosion(), map::draw_triffid(), edit_json(), event_transformation_impl::state::event_added(), explosion_handler::explosion_queue::execute(), explosion_handler::explosion(), fake_map::fake_map(), anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), explosion_handler::flashbang(), clothing_mods::get_all_with(), vehicle::get_any_parts(), vehicle::get_avail_parts(), read_inventory_preset::get_denial(), vehicle::get_enabled_parts(), anonymous_namespace{armor_layers.cpp}::get_item_penalties(), vehicle::get_parts_including_carried(), disassemble_activity_actor::get_progress_message(), game::grabbed_furn_move(), game::handle_action(), worldfactory::init(), npc_trading::init_buying(), cata::list< element_type, element_allocator_type >::insert(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), cata::flat_set< T, Compare, Data >::insert(), vehicle::install_part(), vehicle::interact_with(), vehicle_prototype::load(), recipe_dictionary::load(), npc_template::load(), submap::load(), DynamicDataLoader::load_data_from_path(), cata_libintl::trans_catalogue::load_from_file(), cata_libintl::trans_catalogue::load_from_memory(), worldfactory::load_last_world_info(), l10n_data::load_mod_catalogues(), mod_management::load_mod_list(), mod_management::load_modfile(), aim_activity_actor::load_RAS_weapon(), font_loader::load_throws(), act_progress_message::make_extra_info(), act_progress_message::make_full(), worldfactory::make_new_world(), event_transformation_impl::match_and_transform(), cata::list< element_type, element_allocator_type >::merge(), move(), basic_memory_buffer< T, SIZE, Allocator >::move(), cata::list< element_type, element_allocator_type >::group_vector::move_to_back(), diary::new_page(), ofstream_wrapper::open(), cata_ifstream::operator=(), cata_ofstream::operator=(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::colony_iterator< is_const >::operator=(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::colony_reverse_iterator< r_is_const >::operator=(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::operator=(), cata::list< element_type, element_allocator_type >::group::operator=(), cata::list< element_type, element_allocator_type >::group_vector::operator=(), cata::list< element_type, element_allocator_type >::operator=(), cata::list< element_type, element_allocator_type >::list_iterator< is_const >::operator=(), cata::list< element_type, element_allocator_type >::list_reverse_iterator< is_const >::operator=(), cata::optional< T >::operator=(), pimpl< T >::operator=(), cata::poly_serialized< T >::operator=(), cata::value_ptr< T >::operator=(), cata::optional< T >::optional(), iuse::pack_cbm(), cata_libintl::parse_plural_rules(), pick_one_up(), cata_libintl::plf_get_expr(), cata_libintl::plf_get_value(), cata_libintl::plf_try_binary_op(), map::process_falling(), detail::dynamic_arg_list::push(), cata::list< element_type, element_allocator_type >::push_back(), cata::list< element_type, element_allocator_type >::push_front(), ramp_move(), random_entry_removed(), JsonIn::read(), read_from_file(), mod_manager::refresh_mod_list(), reload(), bandolier_actor::reload(), l10n_data::reload_catalogues(), activity_handlers::reload_finish(), cata::list< element_type, element_allocator_type >::group_vector::remove(), inventory::remove_randomly_by_volume(), veh_utils::repair_part(), replace_all(), Creature::replace_with_npc_name(), restore_on_out_of_scope< T >::restore_on_out_of_scope(), examine_item_menu::run(), character_funcs::select_ammo(), vehicle::serialize(), veh_interact::serialize_activity(), cata_libintl::trans_catalogue::set_buffer(), projectile::set_drop(), l10n_data::set_library(), MOD_INFORMATION::set_translatable_info(), shift_tripoint_map(), shift_tripoint_set(), map::shift_vehicle_z(), explosion_handler::shockwave(), Character::shout(), overmap_ui::show_notes_manager(), cata::list< element_type, element_allocator_type >::shrink_to_fit(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::sort(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::splice(), cata::list< element_type, element_allocator_type >::splice(), detail::bigint::square(), string_format(), string_identity_static::string_id_intern(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::swap(), cata::list< element_type, element_allocator_type >::swap(), cata::optional< T >::swap(), ranged::throw_item(), avatar_funcs::toolmod_add(), iuse::toolmod_attach(), cata_libintl::trans_catalogue::trans_catalogue(), character_funcs::try_wield_contents(), l10n_data::unload_mod_catalogues(), overmap::unserialize(), translatable_mod_info::update(), npc::update_path(), ammobelt_actor::use(), vehicle_activity(), uilist_entry::with_ctxt(), and uilist_entry::with_descr().
plthrow()
void avatar_action::plthrow (avatar & you, item_location loc, const cata::optional< tripoint > & blind_throw_from_pos = cata::nullopt)
Definition at line 853 of file avatar_action.cpp.
{
    if( you.has_active_mutation( trait_SHELL2 ) ) {
        add_msg( m_info, _( "You can't effectively throw while you're in your shell." ) );
        return;
    }
    if( you.is_mounted() ) {
        monster *mons = get_player_character().mounted_creature.get();
        if( mons->has_flag( MF_RIDEABLE_MECH ) ) {
            if( !mons->check_mech_powered() ) {
                add_msg( m_bad, _( "Your %s refuses to move as its batteries have been drained." ),
                         mons->get_name() );
                return;
            }
        }
    }
    if( !loc ) {
        loc = game_menus::inv::titled_menu( you,  _( "Throw item" ),
                                            _( "You don't have any items to throw." ) );
    }
    if( !loc ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    // make a copy and get the original.
    // the copy is thrown and has its and the originals charges set appropiately
    // or deleted from inventory if its charges(1) or not stackable.
    item thrown = *loc.get_item();
    int range = you.throw_range( thrown );
    if( range < 0 ) {
        add_msg( m_info, _( "You don't have that item." ) );
        return;
    } else if( range == 0 ) {
        add_msg( m_info, _( "That is too heavy to throw." ) );
        return;
    }
    if( you.is_wielding( *loc ) && loc->has_flag( flag_NO_UNWIELD ) ) {
        // pos == -1 is the weapon, NO_UNWIELD is used for bio_claws_weapon
        add_msg( m_info, _( "That's part of your body, you can't throw that!" ) );
        return;
    }
    if( you.has_effect( effect_relax_gas ) ) {
        if( one_in( 5 ) ) {
            add_msg( m_good, _( "You concentrate mightily, and your body obeys!" ) );
        } else {
            you.moves -= rng( 2, 5 ) * 10;
            add_msg( m_bad, _( "You can't muster up the effort to throw anything…" ) );
            return;
        }
    }
    // if you're wearing the item you need to be able to take it off
    if( you.is_wearing( loc->typeId() ) ) {
        ret_val<bool> ret = you.can_takeoff( *loc );
        if( !ret.success() ) {
            add_msg( m_info, "%s", ret.c_str() );
            return;
        }
    }
    // you must wield the item to throw it
    // But only if you don't have enough free hands
    int usable_hands = you.get_working_arm_count() -
                       ( you.is_armed() ? 1 : 0 ) -
                       ( you.weapon.is_two_handed( you ) ? 1 : 0 );
    if( !you.is_wielding( *loc ) &&
        ( usable_hands < ( loc->is_two_handed( you ) ? 2 : 1 ) ) ) {
        if( !you.wield( *loc ) ) {
            add_msg( m_info, _( "You do not have enough free hands to throw %s without wielding it." ),
                     loc->tname() );
            return;
        }
        loc = item_location( you, &you.weapon );
    }
    throw_activity_actor actor( loc, blind_throw_from_pos );
    you.assign_activity( actor, false );
}
References _, add_msg(), Character::assign_activity(), Character::can_takeoff(), monster::check_mech_powered(), effect_relax_gas, flag_NO_UNWIELD(), item_location::get_item(), monster::get_name(), get_player_character(), Character::get_working_arm_count(), Character::has_active_mutation(), Creature::has_effect(), item::has_flag(), monster::has_flag(), Character::is_armed(), Character::is_mounted(), item::is_two_handed(), Character::is_wearing(), Character::is_wielding(), m_bad, m_good, m_info, MF_RIDEABLE_MECH, Character::mounted_creature, Creature::moves, one_in(), cata::hash64_detail::ret, rng(), Character::throw_range(), game_menus::inv::titled_menu(), item::tname(), trait_SHELL2, item::typeId(), Character::weapon, and avatar::wield().
Referenced by game::handle_action(), game::peek(), and examine_item_menu::run().
ramp_move()
bool avatar_action::ramp_move (avatar & you, map & m, const tripoint & dest)
Definition at line 442 of file avatar_action.cpp.
{
    if( dest_loc.z != you.posz() ) {
        // No recursive ramp_moves
        return false;
    }
    // We're moving onto a tile with no support, check if it has a ramp below
    if( !m.has_floor_or_support( dest_loc ) ) {
        tripoint below( dest_loc.xy(), dest_loc.z - 1 );
        if( m.has_flag( TFLAG_RAMP, below ) ) {
            // But we're moving onto one from above
            const tripoint dp = dest_loc - you.pos();
            move( you, m, tripoint( dp.xy(), -1 ) );
            // No penalty for misaligned stairs here
            // Also cheaper than climbing up
            return true;
        }
        return false;
    }
    if( !m.has_flag( TFLAG_RAMP, you.pos() ) ||
        m.passable( dest_loc ) ) {
        return false;
    }
    // Try to find an aligned end of the ramp that will make our climb faster
    // Basically, finish walking on the stairs instead of pulling self up by hand
    bool aligned_ramps = false;
    for( const tripoint &pt : m.points_in_radius( you.pos(), 1 ) ) {
        if( rl_dist( pt, dest_loc ) < 2 && m.has_flag( flag_RAMP_END, pt ) ) {
            aligned_ramps = true;
            break;
        }
    }
    const tripoint above_u( you.posx(), you.posy(), you.posz() + 1 );
    if( m.has_floor_or_support( above_u ) ) {
        add_msg( m_warning, _( "You can't climb here - there's a ceiling above." ) );
        return false;
    }
    const tripoint dp = dest_loc - you.pos();
    const tripoint old_pos = you.pos();
    move( you, m, tripoint( dp.xy(), 1 ) );
    // We can't just take the result of the above function here
    if( you.pos() != old_pos ) {
        you.moves -= 50 + ( aligned_ramps ? 0 : 50 );
    }
    return true;
}
References _, add_msg(), flag_RAMP_END(), map::has_flag(), map::has_floor_or_support(), m_warning, move(), Creature::moves, map::passable(), map::points_in_radius(), Character::pos(), Character::posx(), Character::posy(), Character::posz(), rl_dist(), TFLAG_RAMP, tripoint::xy(), and tripoint::z.
reload()
void avatar_action::reload (item_location & loc, bool prompt = false, bool empty = true)
Reload specified item.
Definition at line 1143 of file avatar_action.cpp.
{
    avatar &u = get_avatar();
    u.ammo_location.make_dirty();
    item *it = loc.get_item();
    // bows etc. do not need to reload. select favorite ammo for them instead
    if( it->has_flag( "RELOAD_AND_SHOOT" ) ) {
        ranged::prompt_select_default_ammo_for( u, *it );
        return;
    }
    if( !can_reload_item_or_mods( u, *it ) ) {
        if( ( it->is_ammo_container() || it->is_magazine() ) && it->ammo_remaining() > 0 &&
            it->ammo_remaining() == it->ammo_capacity() ) {
            add_msg( m_info, _( "The %s is already fully loaded!" ), it->tname() );
            return;
        }
        if( it->is_ammo_belt() ) {
            const auto &linkage = it->type->magazine->linkage;
            if( linkage && !u.has_charges( *linkage, 1 ) ) {
                add_msg( m_info, _( "You need at least one %s to reload the %s!" ),
                         item::nname( *linkage, 1 ), it->tname() );
                return;
            }
        }
        if( it->is_watertight_container() && it->is_container_full() ) {
            add_msg( m_info, _( "The %s is already full!" ), it->tname() );
            return;
        }
        add_msg( m_info, _( "You can't reload a %s!" ), it->tname() );
        return;
    }
    bool use_loc = true;
    if( !it->has_flag( "ALLOWS_REMOTE_USE" ) ) {
        it = loc.obtain( u ).get_item();
        use_loc = false;
    }
    // for holsters and ammo pouches try to reload any contained item
    if( it->type->can_use( "holster" ) && !it->contents.empty() ) {
        it = &it->contents.front();
    }
    // for bandoliers we currently defer to iuse_actor methods
    if( it->is_bandolier() ) {
        auto ptr = dynamic_cast<const bandolier_actor *>
                   ( it->type->get_use( "bandolier" )->get_actor_ptr() );
        ptr->reload( u, *it );
        return;
    }
    item_reload_option opt = favorite_ammo_or_select( u, *it, empty, prompt );
    if( opt.ammo.get_item() == nullptr ) {
        return;
    }
    if( opt ) {
        int moves = opt.moves();
        if( it->get_var( "dirt", 0 ) > 7800 ) {
            add_msg( m_warning, _( "You struggle to reload the fouled %s." ), it->tname() );
            moves += 2500;
        }
        u.assign_activity( activity_id( "ACT_RELOAD" ), moves, opt.qty() );
        if( use_loc ) {
            u.activity.targets.emplace_back( loc );
        } else {
            u.activity.targets.emplace_back( u, const_cast<item *>( opt.target ) );
        }
        u.activity.targets.push_back( std::move( opt.ammo ) );
    }
}
References _, Character::activity, add_msg(), item_reload_option::ammo, item::ammo_capacity(), player::ammo_location, item::ammo_remaining(), Character::assign_activity(), can_reload_item_or_mods(), itype::can_use(), item::contents, item_contents::empty(), favorite_ammo_or_select(), item_contents::front(), use_function::get_actor_ptr(), get_avatar(), item_location::get_item(), itype::get_use(), item::get_var(), Character::has_charges(), item::has_flag(), item::is_ammo_belt(), item::is_ammo_container(), item::is_bandolier(), item::is_container_full(), item::is_magazine(), item::is_watertight_container(), m_info, m_warning, itype::magazine, item_location::make_dirty(), move(), Creature::moves, item_reload_option::moves(), item::nname(), item_location::obtain(), pickup::prompt, ranged::prompt_select_default_ammo_for(), ptr(), item_reload_option::qty(), item_reload_option::target, player_activity::targets, item::tname(), and item::type.
Referenced by reload_item(), reload_wielded(), and examine_item_menu::run().
reload_item()
void avatar_action::reload_item ()
Prompt to reload some item.
Definition at line 1219 of file avatar_action.cpp.
{
    item_location item_loc = g->inv_map_splice( []( const item & it ) {
        return can_reload_item_or_mods( get_avatar(), it );
    }, _( "Reload item" ), 1, _( "You have nothing to reload." ) );
    if( !item_loc ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    reload( item_loc );
}
References _, add_msg(), can_reload_item_or_mods(), g, get_avatar(), and reload().
Referenced by game::handle_action().
reload_weapon()
void avatar_action::reload_weapon (bool try_everything = true)
Reload a wielded gun/tool.
Definition at line 1244 of file avatar_action.cpp.
{
    // As a special streamlined activity, hitting reload repeatedly should:
    // Reload wielded gun
    // First reload a magazine if necessary.
    // Then load said magazine into gun.
    // Reload magazines that are compatible with the current gun.
    // Reload other guns in inventory.
    // Reload misc magazines in inventory.
    avatar &u = get_avatar();
    map &here = get_map();
    std::vector<item_location> reloadables = character_funcs::find_reloadables( u );
    std::sort( reloadables.begin(), reloadables.end(),
    [&u]( const item_location & a, const item_location & b ) {
        const item *ap = a.get_item();
        const item *bp = b.get_item();
        // Current wielded weapon comes first.
        if( u.is_wielding( *bp ) ) {
            return false;
        }
        if( u.is_wielding( *ap ) ) {
            return true;
        }
        // Second sort by affiliation with wielded gun
        const std::set<itype_id> compatible_magazines = u.weapon.magazine_compatible();
        const bool mag_ap = compatible_magazines.count( ap->typeId() ) > 0;
        const bool mag_bp = compatible_magazines.count( bp->typeId() ) > 0;
        if( mag_ap != mag_bp ) {
            return mag_ap;
        }
        // Third sort by gun vs magazine,
        if( ap->is_gun() != bp->is_gun() ) {
            return ap->is_gun();
        }
        // Finally sort by speed to reload.
        return ( ap->get_reload_time() * ( ap->ammo_capacity() - ap->ammo_remaining() ) ) <
               ( bp->get_reload_time() * ( bp->ammo_capacity() - bp->ammo_remaining() ) );
    } );
    for( item_location &candidate : reloadables ) {
        std::vector<item_reload_option> ammo_list;
        character_funcs::list_ammo( u, *candidate.get_item(), ammo_list, false, false );
        if( !ammo_list.empty() ) {
            reload( candidate, false, false );
            return;
        }
    }
    // Just for testing, bail out here to avoid unwanted side effects.
    if( !try_everything ) {
        return;
    }
    // If we make it here and haven't found anything to reload, start looking elsewhere.
    vehicle *veh = veh_pointer_or_null( here.veh_at( u.pos() ) );
    turret_data turret;
    if( veh && ( turret = veh->turret_query( u.pos() ) ) && turret.can_reload() ) {
        item_reload_option opt = character_funcs::select_ammo( u, *turret.base(), true );
        if( opt ) {
            u.assign_activity( activity_id( "ACT_RELOAD" ), opt.moves(), opt.qty() );
            u.activity.targets.emplace_back( turret.base() );
            u.activity.targets.push_back( std::move( opt.ammo ) );
        }
        return;
    }
    reload_item();
}
References a, b, character_funcs::find_reloadables(), get_avatar(), get_map(), Character::is_wielding(), item::magazine_compatible(), and Character::weapon.
Referenced by game::handle_action().
reload_wielded()
void avatar_action::reload_wielded (bool prompt = false)
Reload wielded item.
Definition at line 1233 of file avatar_action.cpp.
{
    avatar &u = get_avatar();
    if( u.weapon.is_null() || !u.weapon.is_reloadable() ) {
        add_msg( _( "You aren't holding something you can reload." ) );
        return;
    }
    item_location item_loc = item_location( u, &u.weapon );
    reload( item_loc, prompt );
}
References _, add_msg(), get_avatar(), item::is_null(), item::is_reloadable(), pickup::prompt, reload(), and Character::weapon.
Referenced by aim_activity_actor::finish(), and game::handle_action().
swim()
void avatar_action::swim (map & m, avatar & you, const tripoint & p)
Handles swimming by the player.
Called by avatar_action::move().
Strength increases breath-holding capacity while sinking
Definition at line 496 of file avatar_action.cpp.
{
    if( !m.has_flag( flag_SWIMMABLE, p ) ) {
        debugmsg( "Tried to swim in %s!", m.tername( p ) );
        return;
    }
    if( you.has_effect( effect_onfire ) ) {
        add_msg( _( "The water puts out the flames!" ) );
        you.remove_effect( effect_onfire );
        if( you.is_mounted() ) {
            monster *mon = you.mounted_creature.get();
            if( mon->has_effect( effect_onfire ) ) {
                mon->remove_effect( effect_onfire );
            }
        }
    }
    if( you.has_effect( effect_glowing ) ) {
        add_msg( _( "The water washes off the glowing goo!" ) );
        you.remove_effect( effect_glowing );
    }
    int movecost = you.swim_speed();
    you.practice( skill_swimming, you.is_underwater() ? 2 : 1 );
    if( movecost >= 500 ) {
        if( !you.is_underwater() &&
            !( you.shoe_type_count( itype_swim_fins ) == 2 ||
               ( you.shoe_type_count( itype_swim_fins ) == 1 && one_in( 2 ) ) ) ) {
            add_msg( m_bad, _( "You sink like a rock!" ) );
            you.set_underwater( true );
            ///\EFFECT_STR increases breath-holding capacity while sinking
            you.oxygen = 30 + 2 * you.str_cur;
        }
    }
    if( you.oxygen <= 5 && you.is_underwater() ) {
        if( movecost < 500 ) {
            popup( _( "You need to breathe!  (%s to surface.)" ), press_x( ACTION_MOVE_UP ) );
        } else {
            popup( _( "You need to breathe but you can't swim!  Get to dry land, quick!" ) );
        }
    }
    bool diagonal = ( p.x != you.posx() && p.y != you.posy() );
    if( you.in_vehicle ) {
        m.unboard_vehicle( you.pos() );
    }
    if( you.is_mounted() && m.veh_at( you.pos() ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
        add_msg( m_warning, _( "You cannot board a vehicle while mounted." ) );
        return;
    }
    if( const auto vp = m.veh_at( p ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
        if( !vp->vehicle().handle_potential_theft( you ) ) {
            return;
        }
    }
    you.setpos( p );
    g->update_map( you );
    cata_event_dispatch::avatar_moves( you, m, p );
    if( m.veh_at( you.pos() ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
        m.board_vehicle( you.pos(), &you );
    }
    you.moves -= ( movecost > 200 ? 200 : movecost ) * ( trigdist && diagonal ? M_SQRT2 : 1 );
    you.inv.rust_iron_items();
    if( !you.is_mounted() ) {
        you.burn_move_stamina( movecost );
    }
    body_part_set drenchFlags{ {
            bp_leg_l, bp_leg_r, bp_torso, bp_arm_l,
            bp_arm_r, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r
        }
    };
    if( you.is_underwater() ) {
        drenchFlags |= { { bp_head, bp_eyes, bp_mouth, bp_hand_l, bp_hand_r } };
    }
    you.drench( 100, drenchFlags, true );
}
References _, ACTION_MOVE_UP, add_msg(), cata_event_dispatch::avatar_moves(), map::board_vehicle(), bp_arm_l, bp_arm_r, bp_eyes, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_mouth, bp_torso, Character::burn_move_stamina(), debugmsg, Character::drench(), effect_glowing, effect_onfire, flag_SWIMMABLE(), g, Creature::has_effect(), map::has_flag(), Character::in_vehicle, Character::inv, Character::is_mounted(), Creature::is_underwater(), itype_swim_fins, m_bad, M_SQRT2, m_warning, Character::mounted_creature, Creature::moves, one_in(), Character::oxygen, optional_vpart_position::part_with_feature(), popup(), Character::pos(), Character::posx(), Character::posy(), Character::practice(), press_x(), Creature::remove_effect(), inventory::rust_iron_items(), Character::set_underwater(), Character::setpos(), Character::shoe_type_count(), skill_swimming, Character::str_cur, Character::swim_speed(), map::tername(), trigdist, map::unboard_vehicle(), map::veh_at(), VPFLAG_BOARDABLE, tripoint::x, and tripoint::y.
Referenced by timed_event::actualize(), basecamp::combat_mission_return(), Character::knock_back_to(), game::knockback(), and move().
unload()
void avatar_action::unload (avatar & you)
Prompts to unload some item.
The item can be a container, gun or tool. If it's a gun, some gunmods can also be loaded.
Definition at line 1310 of file avatar_action.cpp.
{
    item_location loc = g->inv_map_splice( []( const item & it ) {
        return item_funcs::can_be_unloaded( it );
    }, _( "Unload item" ), 1, _( "You have nothing to unload." ) );
    if( !loc ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    avatar_funcs::unload_item( you, loc );
}
References _, add_msg(), item_funcs::can_be_unloaded(), g, and avatar_funcs::unload_item().
Referenced by game::handle_action().
use_item() [1/2]
void avatar_action::use_item (avatar & you)
Definition at line 962 of file avatar_action.cpp.
{
    item_location loc;
    avatar_action::use_item( you, loc );
}
References use_item().
use_item() [2/2]
void avatar_action::use_item (avatar & you, item_location & loc)
Definition at line 968 of file avatar_action.cpp.
{
    // Some items may be used without being picked up first
    bool use_in_place = false;
    if( !loc ) {
        loc = game_menus::inv::use( you );
        if( !loc ) {
            add_msg( _( "Never mind." ) );
            return;
        }
        if( loc->has_flag( flag_ALLOWS_REMOTE_USE ) ) {
            use_in_place = true;
        } else {
            const int obtain_cost = loc.obtain_cost( you );
            loc = loc.obtain( you );
            if( !loc ) {
                debugmsg( "Failed to obtain target item" );
                return;
            }
            // TODO: the following comment is inaccurate and this mechanic needs to be rexamined
            // This method only handles items in the inventory, so refund the obtain cost.
            you.mod_moves( obtain_cost );
        }
    }
    if( use_in_place ) {
        update_lum( loc, false );
        avatar_funcs::use_item( you, loc );
        update_lum( loc, true );
        make_active( loc );
    } else {
        avatar_funcs::use_item( you, loc );
    }
    you.invalidate_crafting_inventory();
}
References _, add_msg(), debugmsg, flag_ALLOWS_REMOTE_USE(), item::has_flag(), Character::invalidate_crafting_inventory(), make_active(), Creature::mod_moves(), item_location::obtain(), item_location::obtain_cost(), update_lum(), game_menus::inv::use(), and avatar_funcs::use_item().
Referenced by game::handle_action(), game::npc_menu(), examine_item_menu::run(), and use_item().
wield() [1/2]
void avatar_action::wield ()
Prompt to wield some item.
Definition at line 1010 of file avatar_action.cpp.
{
    item_location loc = game_menus::inv::wield( get_avatar() );
    if( loc ) {
        wield( loc );
    } else {
        add_msg( _( "Never mind." ) );
    }
}
References _, add_msg(), get_avatar(), wield(), and game_menus::inv::wield().
Referenced by game::handle_action(), examine_item_menu::run(), and wield().
wield() [2/2]
void avatar_action::wield (item_location & loc)
Wield specified item.
Definition at line 1021 of file avatar_action.cpp.
{
    avatar &u = get_avatar();
    map &here = get_map();
    if( u.is_armed() ) {
        const bool is_unwielding = u.is_wielding( *loc );
        const auto ret = u.can_unwield( *loc );
        if( !ret.success() ) {
            add_msg( m_info, "%s", ret.c_str() );
        }
        u.unwield();
        if( is_unwielding ) {
            if( !u.martial_arts_data->selected_is_none() ) {
                u.martial_arts_data->martialart_use_message( u );
            }
            return;
        }
    }
    const auto ret = u.can_wield( *loc );
    if( !ret.success() ) {
        add_msg( m_info, "%s", ret.c_str() );
    }
    // Need to do this here because holster_actor::use() checks if/where the item is worn
    item &target = *loc.get_item();
    if( target.get_use( "holster" ) && !target.contents.empty() ) {
        //~ %1$s: weapon name, %2$s: holster name
        if( query_yn( pgettext( "holster", "Draw %1$s from %2$s?" ), target.get_contained().tname(),
                      target.tname() ) ) {
            u.invoke_item( &target );
            return;
        }
    }
    // Can't use loc.obtain() here because that would cause things to spill.
    item to_wield = *loc.get_item();
    item_location::type location_type = loc.where();
    tripoint pos = loc.position();
    int worn_index = INT_MIN;
    if( u.is_worn( *loc.get_item() ) ) {
        auto ret = u.can_takeoff( *loc.get_item() );
        if( !ret.success() ) {
            add_msg( m_info, "%s", ret.c_str() );
            return;
        }
        int item_pos = u.get_item_position( loc.get_item() );
        if( item_pos != INT_MIN ) {
            worn_index = Character::worn_position_to_index( item_pos );
        }
    }
    loc.remove_item();
    if( !u.wield( to_wield ) ) {
        switch( location_type ) {
            case item_location::type::container:
                // this will not cause things to spill, as it is inside another item
                loc = loc.obtain( u );
                wield( loc );
                break;
            case item_location::type::character:
                if( worn_index != INT_MIN ) {
                    auto it = u.worn.begin();
                    std::advance( it, worn_index );
                    u.worn.insert( it, to_wield );
                } else {
                    u.i_add( to_wield );
                }
                break;
            case item_location::type::map:
                here.add_item( pos, to_wield );
                break;
            case item_location::type::vehicle: {
                const cata::optional<vpart_reference> vp = here.veh_at( pos ).part_with_feature( "CARGO", false );
                // If we fail to return the item to the vehicle for some reason, add it to the map instead.
                if( !vp || !( vp->vehicle().add_item( vp->part_index(), to_wield ) ) ) {
                    here.add_item( pos, to_wield );
                }
                break;
            }
            case item_location::type::invalid:
                debugmsg( "Failed wield from invalid item location" );
                break;
        }
        return;
    }
}
References map::add_item(), add_msg(), Character::can_takeoff(), Character::can_unwield(), Character::can_wield(), item_location::character, item_location::container, item::contents, debugmsg, item_contents::empty(), get_avatar(), item::get_contained(), item_location::get_item(), Character::get_item_position(), get_map(), item::get_use(), Character::i_add(), item_location::invalid, avatar::invoke_item(), Character::is_armed(), Character::is_wielding(), Character::is_worn(), m_info, item_location::map, Character::martial_arts_data, item_location::obtain(), optional_vpart_position::part_with_feature(), pgettext(), Character::pos(), item_location::position(), query_yn(), item_location::remove_item(), cata::hash64_detail::ret, item::tname(), Character::unwield(), map::veh_at(), item_location::vehicle, item_location::where(), wield(), avatar::wield(), Character::worn, and Character::worn_position_to_index().