Cataclysm BN: anonymous_namespace{martialarts.cpp} Namespace Reference
anonymous_namespace{martialarts.cpp} Namespace Reference
Variables
generic_factory< ma_technique > ma_techniques ("martial art technique")
generic_factory< martialart > martialarts ("martial art style")
generic_factory< ma_buff > ma_buffs ("martial art buff")
Variable Documentation
ma_buffs
generic_factory< ma_buff > anonymous_namespace{martialarts.cpp}::ma_buffs("martial art buff") ("martial art buff")
Referenced by check_martialarts(), clear_techniques_and_martial_arts(), finialize_martial_arts(), and ma_buff_reader::get_next().
ma_techniques
generic_factory< ma_technique > anonymous_namespace{martialarts.cpp}::ma_techniques("martial art technique") ("martial art technique")
Referenced by check_martialarts(), clear_techniques_and_martial_arts(), and load_technique().
martialarts
generic_factory< martialart > anonymous_namespace{martialarts.cpp}::martialarts("martial art style") ("martial art style")
Referenced by all_martialart_types(), autolearn_martialart_types(), check_martialarts(), clear_techniques_and_martial_arts(), and load_martial_art().