Cataclysm BN: to_cbc_migration Namespace Reference
to_cbc_migration Namespace Reference
Functions
void load (const JsonObject &jo)
void reset ()
static bool migration_required (const item &i)
static void migrate (cata::colony< item > &stack)
Merge old individual items into new count-by-charges items with same id.
Variables
static std::set< itype_id > the_list
Function Documentation
load()
void to_cbc_migration::load (const JsonObject & jo)
Definition at line 2111 of file savegame_json.cpp.
{
    std::set<std::string> d = jo.get_tags( "list" );
    for( const std::string &s : d ) {
        the_list.insert( itype_id( s ) );
    }
}
References JsonObject::get_tags(), itype_id, and the_list.
Referenced by DynamicDataLoader::initialize().
migrate()
static void to_cbc_migration::migrate (cata::colony< item > & stack) static
Merge old individual items into new count-by-charges items with same id.
Definition at line 2135 of file savegame_json.cpp.
{
    for( auto it_src = stack.begin(); it_src != stack.end(); ) {
        if( !migration_required( *it_src ) ) {
            it_src++;
            continue;
        }
        auto it_dst = it_src;
        it_dst++;
        bool merged = false;
        for( ; it_dst != stack.end(); it_dst++ ) {
            const item &src = *it_src;
            if( it_dst->merge_charges( src ) ) {
                it_src = stack.erase( it_src );
                merged = true;
                break;
            }
        }
        if( !merged ) {
            it_src++;
        }
    }
}
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::begin(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::end(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::erase(), and migration_required().
Referenced by vehicle::deserialize(), Item_factory::finalize_item_blacklist(), and submap::load().
migration_required()
static bool to_cbc_migration::migration_required (const item & i) static
Definition at line 2124 of file savegame_json.cpp.
{
    if( !i.count_by_charges() ) {
        return false;
    }
    return the_list.count( i.typeId() ) > 0;
}
References item::count_by_charges(), the_list, and item::typeId().
Referenced by migrate().
reset()
void to_cbc_migration::reset ()
Definition at line 2119 of file savegame_json.cpp.
{
    the_list.clear();
}
References the_list.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
the_list
std::set<itype_id> to_cbc_migration::the_list static
Definition at line 2109 of file savegame_json.cpp.
Referenced by load(), migration_required(), and reset().