Cataclysm BN: mod_management Namespace Reference
mod_management Namespace Reference
Typedefs
using t_mod_list = std::vector< mod_id >
Functions
std::vector< MOD_INFORMATION > load_mods_from (const std::string &path)
Load all modinfo.json files (recursively) from the given root.
cata::optional< MOD_INFORMATION > load_modfile (const JsonObject &jo, const std::string &path)
Load mod info from a json object.
void load_mod_info (const std::string &info_file_path, std::vector< MOD_INFORMATION > &out)
Load all mod information from a json file.
bool save_mod_list (const t_mod_list &list, const std::string &path)
Save mod list to file.
cata::optional< t_mod_list > load_mod_list (const std::string &path)
Load mod list from file.
Typedef Documentation
t_mod_list
using mod_management::t_mod_list = typedef std::vector<mod_id>
Definition at line 91 of file mod_manager.h.
Function Documentation
load_mod_info()
void mod_management::load_mod_info (const std::string & info_file_path, std::vector< MOD_INFORMATION > & out)
Load all mod information from a json file.
(
See also
load_modfile)
Definition at line 306 of file mod_manager.cpp.
{
    const std::string main_path = info_file_path.substr( 0, info_file_path.find_last_of( "/\\" ) );
    read_from_file_optional_json( info_file_path, [&]( JsonIn & jsin ) {
        if( jsin.test_object() ) {
            // find type and dispatch single object
            JsonObject jo = jsin.get_object();
            cata::optional<MOD_INFORMATION> mf = load_modfile( jo, main_path );
            if( mf ) {
                mf->path_full = info_file_path;
                out.push_back( std::move( *mf ) );
            }
            jo.finish();
        } else if( jsin.test_array() ) {
            jsin.start_array();
            // find type and dispatch each object until array close
            while( !jsin.end_array() ) {
                JsonObject jo = jsin.get_object();
                cata::optional<MOD_INFORMATION> mf = load_modfile( jo, main_path );
                if( mf ) {
                    mf->path_full = info_file_path;
                    out.push_back( std::move( *mf ) );
                }
                jo.finish();
            }
        } else {
            // not an object or an array?
            jsin.error( "expected array or object" );
        }
    } );
}
References read_from_file_optional_json(), JsonIn::test_array(), and JsonIn::test_object().
Referenced by load_mods_from().
load_mod_list()
cata::optional< t_mod_list > mod_management::load_mod_list (const std::string & path)
Load mod list from file.
Returns
cata::nullopt on error.
Definition at line 346 of file mod_manager.cpp.
{
    t_mod_list res;
    auto reader = [&]( JsonIn & jsin ) {
        jsin.read( res, true );
    };
    if( read_from_file_optional_json( path, reader ) ) {
        return { std::move( res ) };
    } else {
        return cata::nullopt;
    }
}
References avatar_action::move(), cata::nullopt, and read_from_file_optional_json().
Referenced by mod_manager::refresh_mod_list().
load_modfile()
cata::optional< MOD_INFORMATION > mod_management::load_modfile (const JsonObject & jo, const std::string & path)
Load mod info from a json object.
Exceptions
JsonError on all kind of errors.
Definition at line 235 of file mod_manager.cpp.
{
    if( !jo.has_string( "type" ) || jo.get_string( "type" ) != "MOD_INFO" ) {
        // Ignore anything that is not a mod-info
        jo.allow_omitted_members();
        return cata::nullopt;
    }
    // TEMPORARY until 0.G: Remove "ident" support
    const mod_id m_ident( jo.has_string( "ident" ) ? jo.get_string( "ident" ) : jo.get_string( "id" ) );
    std::string m_cat = jo.get_string( "category", "" );
    std::pair<int, std::string> p_cat = { -1, "" };
    bool bCatFound = false;
    do {
        for( size_t i = 0; i < get_mod_list_categories().size(); ++i ) {
            if( get_mod_list_categories()[i].first == m_cat ) {
                p_cat = { static_cast<int>( i ), get_mod_list_categories()[i].second };
                bCatFound = true;
                break;
            }
        }
        if( !bCatFound && !m_cat.empty() ) {
            m_cat.clear();
        } else {
            break;
        }
    } while( !bCatFound );
    MOD_INFORMATION modfile;
    modfile.ident = m_ident;
    modfile.category = p_cat;
    if( assign( jo, "path", modfile.path ) ) {
        modfile.path = path + "/" + modfile.path;
    } else {
        modfile.path = path;
    }
    const std::string m_name = jo.get_string( "name", "" );
    const std::string m_descr = jo.get_string( "description", "" );
    modfile.set_translatable_info( translatable_mod_info( m_name, m_descr, modfile.path ) );
    assign( jo, "authors", modfile.authors );
    assign( jo, "maintainers", modfile.maintainers );
    assign( jo, "version", modfile.version );
    assign( jo, "dependencies", modfile.dependencies );
    assign( jo, "conflicts", modfile.conflicts );
    assign( jo, "core", modfile.core );
    assign( jo, "obsolete", modfile.obsolete );
    if( std::find( modfile.dependencies.begin(), modfile.dependencies.end(),
                   modfile.ident ) != modfile.dependencies.end() ) {
        jo.throw_error( "mod specifies self as a dependency", "dependencies" );
    }
    for( const auto &conf : modfile.conflicts ) {
        if( conf == modfile.ident ) {
            jo.throw_error( "mod specifies self as a conflict", "conflicts" );
        }
        if( std::find( modfile.dependencies.begin(), modfile.dependencies.end(),
                       conf ) != modfile.dependencies.end() ) {
            jo.throw_error( string_format( "mod specifies \"%s\" as both a dependency and a conflict", conf ),
                            "conflicts" );
        }
    }
    return { std::move( modfile ) };
}
References JsonObject::allow_omitted_members(), assign(), MOD_INFORMATION::authors, MOD_INFORMATION::category, MOD_INFORMATION::conflicts, MOD_INFORMATION::core, MOD_INFORMATION::dependencies, detail::find(), get_mod_list_categories(), JsonObject::get_string(), JsonObject::has_string(), MOD_INFORMATION::ident, MOD_INFORMATION::maintainers, avatar_action::move(), cata::nullopt, MOD_INFORMATION::obsolete, MOD_INFORMATION::path, MOD_INFORMATION::set_translatable_info(), string_format(), JsonObject::throw_error(), and MOD_INFORMATION::version.
load_mods_from()
std::vector< MOD_INFORMATION > mod_management::load_mods_from (const std::string & path)
Load all modinfo.json files (recursively) from the given root.
Parameters
path The root folder from which the modinfo files are searched.
Definition at line 192 of file mod_manager.cpp.
{
    std::vector<MOD_INFORMATION> out;
    for( auto &mod_file : get_files_from_path( MOD_SEARCH_FILE, path, true ) ) {
        load_mod_info( mod_file, out );
    }
    std::set<mod_id> idents;
    std::set<mod_id> has_dupes;
    for( const MOD_INFORMATION &it : out ) {
        if( idents.count( it.ident ) > 0 ) {
            has_dupes.emplace( it.ident );
        } else {
            idents.emplace( it.ident );
        }
    }
    for( const mod_id &ident : has_dupes ) {
        std::string msg = string_format(
                              _( "The are multiple mods with same id [%s] found in folder \"%s\":\n" ),
                              ident, path );
        for( auto it = out.begin(); it != out.end(); ) {
            if( it->ident == ident ) {
                msg += "  - ";
                msg += it->path_full;
                msg += "\n";
                it = out.erase( it );
            } else {
                it++;
            }
        }
        msg += _( "None of them will be loaded to avoid data corruption." );
        debugmsg( msg );
    }
    return out;
}
References _, debugmsg, get_files_from_path(), load_mod_info(), MOD_SEARCH_FILE(), and string_format().
Referenced by mod_manager::refresh_mod_list().
save_mod_list()
bool mod_management::save_mod_list (const t_mod_list & list, const std::string & path)
Save mod list to file.
Returns
true on success.
Definition at line 338 of file mod_manager.cpp.
{
    return write_to_file( path, [&]( std::ostream & fout ) {
        JsonOut json( fout, true ); // pretty-print
        json.write( list );
    }, _( "list of default mods" ) );
}
References _, JsonOut::write(), and write_to_file().
Referenced by mod_manager::set_default_mods().