Cataclysm BN: crafting Namespace Reference
crafting Namespace Reference
Functions
static std::vector< avail_tool_comp > find_tool_component (const Character *player_with_inv, const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, cost_adjustment charge_mod)
static comp_selection< tool_comp > query_tool_selection (const std::vector< avail_tool_comp > &available_tools, const std::string &hotkeys, bool can_cancel, bool is_npc)
comp_selection< tool_comp > select_tool_component (const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, const Character *player_with_inv, bool can_cancel, const std::string &hotkeys, cost_adjustment adjustment)
Returns selected tool component that matches one of the expected ones.
comp_selection< tool_comp > select_tool_component (const std::vector< tool_comp > &tools, int batch, const inventory &map_inv, const Character *player_with_inv, bool can_cancel)
std::set< itype_id > get_books_for_recipe (const Character &c, const inventory &crafting_inv, const recipe *r)
Returns the set of book types in crafting_inv that provide the given recipe.
std::set< itype_id > get_books_for_recipe (const recipe *r)
Returns the set of book types that provide the given recipe.
int charges_for_complete (int full_charges)
int charges_for_starting (int full_charges)
int charges_for_continuing (int full_charges)
ret_val< bool > can_disassemble (const Character &who, const item &obj, const inventory &inv)
Check if character can disassemble an item using the given crafting inventory.
bool disassemble (avatar &you)
Prompt for an item to disassemble, then start activity.
bool disassemble (avatar &you, item_location target)
Prompt to disassemble given item, then start activity.
bool disassemble_all (avatar &you, bool recursively)
Start an activity to disassemble all items in avatar's square.
void complete_disassemble (Character &who, iuse_location target, const tripoint &pos)
Complete disassembly of target item.
Function Documentation
can_disassemble()
ret_val< bool > crafting::can_disassemble (const Character & who, const item & obj, const inventory & inv)
Check if character can disassemble an item using the given crafting inventory.
Definition at line 1875 of file crafting.cpp.
{
    const auto &r = recipe_dictionary::get_uncraft( obj.typeId() );
    if( !r || obj.has_flag( flag_ETHEREAL_ITEM ) ) {
        return ret_val<bool>::make_failure( _( "You cannot disassemble this." ) );
    }
    // check sufficient light
    if( lighting_crafting_speed_multiplier( who, r ) == 0.0f ) {
        return ret_val<bool>::make_failure( _( "You can't see to craft!" ) );
    }
    // refuse to disassemble rotten items
    const item *food = obj.get_food();
    if( ( obj.goes_bad() && obj.rotten() ) || ( food && food->goes_bad() && food->rotten() ) ) {
        return ret_val<bool>::make_failure( _( "It's rotten, I'm not taking that apart." ) );
    }
    // refuse to disassemble items containing monsters/pets
    std::string monster = obj.get_var( "contained_name" );
    if( !monster.empty() ) {
        return ret_val<bool>::make_failure( _( "You must remove the %s before you can disassemble this." ),
                                            monster );
    }
    if( obj.count_by_charges() ) {
        int batch_size = r.disassembly_batch_size();
        if( obj.charges < batch_size ) {
            auto msg = vgettext( "You need at least %d charge of %s.",
                                 "You need at least %d charges of %s.", batch_size );
            return ret_val<bool>::make_failure( msg, batch_size, obj.tname() );
        }
    }
    const auto &dis = r.disassembly_requirements();
    for( const auto &opts : dis.get_qualities() ) {
        for( const auto &qual : opts ) {
            if( !qual.has( inv, return_true<item> ) ) {
                // Here should be no dot at the end of the string as 'to_string()' provides it.
                return ret_val<bool>::make_failure( _( "You need %s" ), qual.to_string() );
            }
        }
    }
    for( const auto &opts : dis.get_tools() ) {
        const bool found = std::any_of( opts.begin(), opts.end(),
        [&]( const tool_comp & tool ) {
            return ( tool.count <= 0 && inv.has_tools( tool.type, 1 ) ) ||
                   ( tool.count  > 0 && inv.has_charges( tool.type, tool.count ) );
        } );
        if( !found ) {
            const tool_comp &tool_required = opts.front();
            if( tool_required.count <= 0 ) {
                return ret_val<bool>::make_failure( _( "You need %s." ),
                                                    item::nname( tool_required.type ) );
            } else {
                //~ %1$s: tool name, %2$d: needed charges
                return ret_val<bool>::make_failure( vgettext( "You need a %1$s with %2$d charge.",
                                                    "You need a %1$s with %2$d charges.", tool_required.count ),
                                                    item::nname( tool_required.type ),
                                                    tool_required.count );
            }
        }
    }
    return ret_val<bool>::make_success();
}
References _, component::count, flag_ETHEREAL_ITEM(), recipe_dictionary::get_uncraft(), item::goes_bad(), lighting_crafting_speed_multiplier(), ret_val< T >::make_failure(), ret_val< T >::make_success(), item::nname(), int_id< T >::obj(), item::rotten(), tool, component::type, and vgettext().
Referenced by game::butcher(), can_butcher_at(), disassemble_inventory_preset::get_denial(), prompt_disassemble_in_seq(), examine_item_menu::rate_action_disassemble(), and disassemble_activity_actor::try_start_single().
charges_for_complete()
int crafting::charges_for_complete (int full_charges)
Definition at line 2421 of file crafting.cpp.
{
    return full_charges;
}
Referenced by find_tool_component().
charges_for_continuing()
int crafting::charges_for_continuing (int full_charges)
Definition at line 2429 of file crafting.cpp.
{
    return full_charges / 20;
}
Referenced by player::can_continue_craft(), player::craft_consume_tools(), find_tool_component(), and tool_comp::has().
charges_for_starting()
int crafting::charges_for_starting (int full_charges)
Definition at line 2425 of file crafting.cpp.
{
    return full_charges / 20 + full_charges % 20;
}
Referenced by player::craft_consume_tools(), find_tool_component(), and tool_comp::has().
complete_disassemble()
void crafting::complete_disassemble (Character & who, iuse_location target, const tripoint & pos)
Complete disassembly of target item.
Intelligence increases success rate for disassembling items
Definition at line 2111 of file crafting.cpp.
{
    item &org_item = *target.loc;
    const recipe &dis = recipe_dictionary::get_uncraft( org_item.typeId() );
    // Get the proper recipe - the one for disassembly, not assembly
    const auto dis_requirements = dis.disassembly_requirements();
    const bool filthy = org_item.is_filthy();
    // Make a copy to keep its data (damage/components) even after it
    // has been removed.
    item dis_item = org_item;
    float component_success_chance = std::min( std::pow( 0.8, dis_item.damage_level( 4 ) ), 1.0 );
    add_msg( _( "You disassemble the %s into its components." ), dis_item.tname() );
    // Remove any batteries, ammo and mods first
    remove_ammo( dis_item, who );
    remove_radio_mod( dis_item, *who.as_player() );
    if( org_item.count_by_charges() ) {
        int batch_size = dis.disassembly_batch_size();
        org_item.charges -= batch_size * target.count;
    }
    // remove the item, except when it's counted by charges and still has some
    if( !org_item.count_by_charges() || org_item.charges <= 0 ) {
        target.loc.remove_item();
    }
    // Consume tool charges
    for( const auto &it : dis_requirements.get_tools() ) {
        who.as_player()->consume_tools( it );
    }
    // add the components to the map
    // Player skills should determine how many components are returned
    int skill_dice = 2 + who.get_skill_level( dis.skill_used ) * 3;
    skill_dice += who.get_skill_level( dis.skill_used );
    // Sides on dice is 16 plus your current intelligence
    ///\EFFECT_INT increases success rate for disassembling items
    int skill_sides = 16 + who.int_cur;
    int diff_dice = dis.difficulty;
    int diff_sides = 24; // 16 + 8 (default intelligence)
    // disassembly only nets a bit of practice
    if( dis.skill_used ) {
        who.as_player()->practice( dis.skill_used, ( dis.difficulty ) * 2, dis.difficulty );
    }
    // If the components aren't empty, we want items exactly identical to them
    // Even if the best-fit recipe does not involve those items
    std::list<item> components = dis_item.components;
    // If the components are empty, item is the default kind and made of default components
    if( components.empty() ) {
        const bool uncraft_liquids_contained = dis.has_flag( flag_UNCRAFT_LIQUIDS_CONTAINED );
        for( const auto &altercomps : dis_requirements.get_components() ) {
            const item_comp &comp = altercomps.front();
            int compcount = comp.count * target.count;
            item newit( comp.type, calendar::turn );
            const bool is_liquid = newit.made_of( LIQUID );
            if( uncraft_liquids_contained && is_liquid && newit.charges != 0 ) {
                // Spawn liquid item in its default container
                compcount = compcount / newit.charges;
                if( compcount != 0 ) {
                    newit = newit.in_its_container();
                }
            } else {
                // Compress liquids and counted-by-charges items into one item,
                // they are added together on the map anyway and handle_liquid
                // should only be called once to put it all into a container at once.
                if( newit.count_by_charges() || is_liquid ) {
                    newit.charges = compcount;
                    compcount = 1;
                } else if( !newit.craft_has_charges() && newit.charges > 0 ) {
                    // tools that can be unloaded should be created unloaded,
                    // tools that can't be unloaded will keep their default charges.
                    newit.charges = 0;
                }
            }
            // If the recipe has a `FULL_MAGAZINE` flag, spawn any magazines full of ammo
            if( newit.is_magazine() && dis.has_flag( flag_FULL_MAGAZINE ) ) {
                newit.ammo_set( newit.ammo_default(), newit.ammo_capacity() );
            }
            for( ; compcount > 0; compcount-- ) {
                components.emplace_back( newit );
            }
        }
    }
    std::list<item> drop_items;
    for( const item &newit : components ) {
        const bool comp_success = ( dice( skill_dice, skill_sides ) > dice( diff_dice,  diff_sides ) );
        if( dis.difficulty != 0 && !comp_success ) {
            add_msg( m_bad, _( "You fail to recover %s." ), newit.tname() );
            continue;
        }
        const bool dmg_success = component_success_chance > rng_float( 0, 1 );
        if( !dmg_success ) {
            // Show reason for failure (damaged item, tname contains the damage adjective)
            //~ %1s - material, %2$s - disassembled item
            add_msg( m_bad, _( "You fail to recover %1$s from the %2$s." ), newit.tname(),
                     dis_item.tname() );
            continue;
        }
        // Use item from components list, or (if not contained)
        // use newit, the default constructed.
        item act_item = newit;
        // Refitted clothing disassembles into refitted components (when applicable)
        if( dis_item.has_flag( flag_FIT ) && act_item.has_flag( flag_VARSIZE ) ) {
            act_item.set_flag( flag_FIT );
        }
        if( filthy ) {
            act_item.set_flag( "FILTHY" );
        }
        for( std::list<item>::iterator a = dis_item.components.begin(); a != dis_item.components.end();
             ++a ) {
            if( a->type == newit.type ) {
                act_item = *a;
                dis_item.components.erase( a );
                break;
            }
        }
        if( act_item.made_of( LIQUID ) ) {
            liquid_handler::handle_all_liquid( act_item, PICKUP_RANGE );
        } else {
            drop_items.push_back( act_item );
        }
    }
    put_into_vehicle_or_drop( who, item_drop_reason::deliberate, drop_items );
    if( !dis.learn_by_disassembly.empty() && !who.knows_recipe( &dis ) ) {
        if( who.can_learn_by_disassembly( dis ) ) {
            // TODO: make this depend on intelligence
            if( one_in( 4 ) ) {
                // TODO: change to forward an id or a reference
                who.learn_recipe( &dis.ident().obj() );
                add_msg( m_good, _( "You learned a recipe for %s from disassembling it!" ),
                         dis_item.tname() );
            } else {
                add_msg( m_info, _( "You might be able to learn a recipe for %s if you disassemble another." ),
                         dis_item.tname() );
            }
        } else {
            add_msg( m_info, _( "If you had better skills, you might learn a recipe next time." ) );
        }
    }
}
References _, a, add_msg(), item::ammo_capacity(), item::ammo_default(), item::ammo_set(), Creature::as_player(), Character::can_learn_by_disassembly(), item::charges, item::components, player::consume_tools(), iuse_location::count, component::count, item::count_by_charges(), item::craft_has_charges(), item::damage_level(), deliberate, dice(), recipe::difficulty, recipe::disassembly_batch_size(), recipe::disassembly_requirements(), flag_FIT(), flag_FULL_MAGAZINE(), flag_UNCRAFT_LIQUIDS_CONTAINED(), flag_VARSIZE(), Character::get_skill_level(), recipe_dictionary::get_uncraft(), liquid_handler::handle_all_liquid(), item::has_flag(), recipe::has_flag(), recipe::ident(), item::in_its_container(), Character::int_cur, item::is_filthy(), item::is_magazine(), Character::knows_recipe(), recipe::learn_by_disassembly, Character::learn_recipe(), LIQUID, iuse_location::loc, m_bad, m_good, m_info, item::made_of(), string_id< T >::obj(), one_in(), PICKUP_RANGE, player::practice(), put_into_vehicle_or_drop(), remove_ammo(), item_location::remove_item(), remove_radio_mod(), rng_float(), item::set_flag(), recipe::skill_used, item::tname(), calendar::turn, component::type, and item::typeId().
Referenced by disassemble_activity_actor::finish().
disassemble() [1/2]
bool crafting::disassemble (avatar & you)
Prompt for an item to disassemble, then start activity.
Definition at line 2074 of file crafting.cpp.
{
    item_location target = game_menus::inv::disassemble( you );
    return prompt_disassemble_single( you, target, false );
}
References game_menus::inv::disassemble(), and prompt_disassemble_single().
Referenced by game::butcher(), iuse::disassemble(), game::handle_action(), and examine_item_menu::run().
disassemble() [2/2]
bool crafting::disassemble (avatar & you, item_location target)
Prompt to disassemble given item, then start activity.
Definition at line 2080 of file crafting.cpp.
{
    return prompt_disassemble_single( you, target, true );
}
References prompt_disassemble_single().
disassemble_all()
bool crafting::disassemble_all (avatar & you, bool recursively)
Start an activity to disassemble all items in avatar's square.
Definition at line 2085 of file crafting.cpp.
{
    std::vector<iuse_location> targets;
    tripoint pos = you.pos();
    for( item &itm : get_map().i_at( pos ) ) {
        disass_prompt_result res = prompt_disassemble_in_seq( you, itm, false, true );
        if( res.success ) {
            iuse_location loc;
            loc.loc = item_location( map_cursor( pos ), &itm );
            loc.count = res.batches ? *res.batches : 1;
            targets.push_back( std::move( loc ) );
        }
    }
    if( !targets.empty() ) {
        tripoint_abs_ms pos_abs( get_map().getabs( you.pos() ) );
        you.assign_activity( disassemble_activity_actor( std::move( targets ), pos_abs, recursively ) );
        return true;
    } else {
        return false;
    }
}
References Character::assign_activity(), disass_prompt_result::batches, iuse_location::count, get_map(), iuse_location::loc, avatar_action::move(), Character::pos(), prompt_disassemble_in_seq(), and disass_prompt_result::success.
Referenced by game::butcher(), and disassemble_activity_actor::finish().
find_tool_component()
static std::vector< avail_tool_comp > crafting::find_tool_component (const Character * player_with_inv, const std::vector< tool_comp > & tools, int batch, const inventory & map_inv, cost_adjustment charge_mod) static
Definition at line 1593 of file crafting.cpp.
{
    std::vector<avail_tool_comp> available_tools;
    auto calc_charges = [&]( const tool_comp & t ) {
        const int full_craft_charges = std::max( 1, t.count * batch );
        switch( charge_mod ) {
            case cost_adjustment::none:
                return std::make_pair( charges_for_complete( full_craft_charges ),
                                       charges_for_complete( full_craft_charges ) );
            case cost_adjustment::start_only:
                return std::make_pair( charges_for_starting( full_craft_charges ),
                                       charges_for_complete( full_craft_charges ) );
            case cost_adjustment::continue_only:
                return std::make_pair( charges_for_continuing( full_craft_charges ),
                                       charges_for_complete( full_craft_charges ) );
        }
        debugmsg( "Invalid tool_charge_mod" );
        return std::make_pair( INT_MAX, INT_MAX );
    };
    bool found_nocharge = false;
    // Use charges of any tools that require charges used
    for( auto it = tools.begin(); it != tools.end() && !found_nocharge; ++it ) {
        itype_id type = it->type;
        if( it->count > 0 ) {
            const std::pair<int, int> &expected_count = calc_charges( *it );
            const int count = expected_count.first;
            const int ideal = expected_count.second;
            if( player_with_inv ) {
                if( player_with_inv->has_charges( type, count ) ) {
                    int total_charges = player_with_inv->charges_of( type );
                    comp_selection<tool_comp> sel( use_from_player, *it );
                    available_tools.emplace_back( sel, total_charges, ideal );
                }
            }
            if( map_inv.has_charges( type, count ) ) {
                int total_charges = map_inv.charges_of( type );
                comp_selection<tool_comp> sel( use_from_map, *it );
                available_tools.emplace_back( sel, total_charges, ideal );
            }
        } else if( ( player_with_inv && player_with_inv->has_amount( type, 1 ) )
                   || map_inv.has_tools( type, 1 ) ) {
            comp_selection<tool_comp> sel( use_from_none, *it );
            available_tools.emplace_back( sel, 0, 0 );
        }
    }
    std::sort( available_tools.begin(), available_tools.end(),
    []( const avail_tool_comp & lhs, const avail_tool_comp & rhs ) {
        if( lhs.comp.use_from == use_from_none && rhs.comp.use_from != use_from_none ) {
            return true;
        }
        if( rhs.comp.use_from == use_from_none ) {
            return false;
        }
        if( lhs.charges >= lhs.ideal && rhs.charges < rhs.ideal ) {
            return true;
        }
        if( lhs.charges < lhs.ideal && rhs.charges >= rhs.ideal ) {
            return false;
        }
        // We want "bigger" tools first because those are likely to be vehicle mounted
        return static_cast<float>( lhs.ideal ) / lhs.charges > static_cast<float>
               ( rhs.ideal ) / rhs.charges;
    } );
    return available_tools;
}
References avail_tool_comp::charges, charges_for_complete(), charges_for_continuing(), charges_for_starting(), visitable< T >::charges_of(), avail_tool_comp::comp, continue_only, detail::count(), debugmsg, visitable< T >::has_amount(), Character::has_charges(), inventory::has_charges(), inventory::has_tools(), avail_tool_comp::ideal, none, start_only, type, use_from_map, use_from_none, and use_from_player.
Referenced by select_tool_component().
get_books_for_recipe() [1/2]
std::set< itype_id > crafting::get_books_for_recipe (const Character & c, const inventory & crafting_inv, const recipe * r)
Returns the set of book types in crafting_inv that provide the given recipe.
Parameters
c Character whose skills are used to limit the available recipes
crafting_inv Current available items that may contain readable books
r Recipe to search for in the available books
Definition at line 2396 of file crafting.cpp.
{
    std::set<itype_id> book_ids;
    const int skill_level = c.get_skill_level( r->skill_used );
    for( auto &book_lvl : r->booksets ) {
        itype_id book_id = book_lvl.first;
        int required_skill_level = book_lvl.second;
        if( skill_level >= required_skill_level && crafting_inv.amount_of( book_id ) > 0 ) {
            book_ids.insert( book_id );
        }
    }
    return book_ids;
}
References visitable< T >::amount_of(), recipe::booksets, c, and recipe::skill_used.
Referenced by select_crafting_recipe().
get_books_for_recipe() [2/2]
std::set< itype_id > crafting::get_books_for_recipe (const recipe * r)
Returns the set of book types that provide the given recipe.
Definition at line 2411 of file crafting.cpp.
{
    std::set<itype_id> book_ids;
    std::transform( r->booksets.begin(), r->booksets.end(), std::inserter( book_ids, book_ids.end() ),
    []( const std::pair<itype_id, int> &pr ) {
        return pr.first;
    } );
    return book_ids;
}
References recipe::booksets, and iexamine::transform().
query_tool_selection()
static comp_selection< tool_comp > crafting::query_tool_selection (const std::vector< avail_tool_comp > & available_tools, const std::string & hotkeys, bool can_cancel, bool is_npc) static
Definition at line 1666 of file crafting.cpp.
{
    if( available_tools.empty() ) {
        // This SHOULD only happen if cooking with a fire,
        // and the fire goes out.
        return comp_selection<tool_comp>( use_from_none );
    }
    if( available_tools.front().comp.use_from == use_from_none ) {
        // Default to using a tool that doesn't require charges
        return available_tools.front().comp;
    }
    if( available_tools.size() == 1 ) {
        return available_tools.front().comp;
    }
    if( is_npc ) {
        auto iter = std::find_if( available_tools.begin(), available_tools.end(),
        []( const avail_tool_comp & tool ) {
            return tool.comp.use_from == use_from_player;
        } );
        if( iter != available_tools.end() ) {
            return iter->comp;
        }
        return available_tools.front().comp;
    }
    // Variety of options, list them and pick one
    // Populate the list
    uilist tmenu( hotkeys );
    for( const avail_tool_comp &tool : available_tools ) {
        const itype_id &comp_type = tool.comp.comp.type;
        if( tool.ideal > 1 ) {
            const char *format = tool.comp.use_from == use_from_map
                                 ? _( "%s (%d/%d charges nearby)" )
                                 : _( "%s (%d/%d charges on person)" );
            std::string str = string_format( format,
                                             item::nname( comp_type ), tool.ideal,
                                             tool.charges );
            tmenu.addentry( str );
        } else {
            std::string str = tool.comp.use_from == use_from_map
                              ? item::nname( comp_type ) + _( " (nearby)" )
                              : item::nname( comp_type );
            tmenu.addentry( str );
        }
    }
    tmenu.allow_cancel = can_cancel;
    // Get selection via a popup menu
    tmenu.title = _( "Use which tool?" );
    tmenu.query();
    if( tmenu.ret < 0 || static_cast<size_t>( tmenu.ret ) >= available_tools.size() ) {
        return comp_selection<tool_comp>( cancel );
    }
    return available_tools.at( static_cast<size_t>( tmenu.ret ) ).comp;
}
References _, uilist::addentry(), uilist::allow_cancel, cancel, format(), item::nname(), uilist::query(), uilist::ret, string_format(), uilist::title, tool, use_from_map, and use_from_none.
Referenced by select_tool_component().
select_tool_component() [1/2]
comp_selection< tool_comp > crafting::select_tool_component (const std::vector< tool_comp > & tools, int batch, const inventory & map_inv, const Character * player_with_inv, bool can_cancel)
Definition at line 1740 of file crafting.cpp.
{
    return select_tool_component( tools, batch, map_inv, player_with_inv, can_cancel, DEFAULT_HOTKEYS,
                                  cost_adjustment::none );
}
References DEFAULT_HOTKEYS(), none, and select_tool_component().
Referenced by select_tool_component().
select_tool_component() [2/2]
comp_selection< tool_comp > crafting::select_tool_component (const std::vector< tool_comp > & tools, int batch, const inventory & map_inv, const Character * player_with_inv, bool can_cancel, const std::string & hotkeys, cost_adjustment adjustment)
Returns selected tool component that matches one of the expected ones.
Parameters
tools tools to match
batch size of batch to craft, multiplier on expected charges
map_inv map inventory to select from
player_with_inv if not null, character who provides additional inventory
hotkeys hotkeys available to the menu
can_cancel can the selection be aborted with no result
adjustment affects required charges, see cost_adjustment
Definition at line 1727 of file crafting.cpp.
{
    std::vector<avail_tool_comp> options = find_tool_component( player_with_inv, tools, batch, map_inv,
                                           adjustment );
    bool is_npc = player_with_inv ? player_with_inv->is_npc() : false;
    return query_tool_selection( options, hotkeys, can_cancel, is_npc );
}
References find_tool_component(), Creature::is_npc(), PATH_INFO::options(), and query_tool_selection().
Referenced by player::can_continue_craft(), basecamp_action_components::choose_components(), player::consume_tools(), craft_command::execute(), and veh_utils::repair_part().