Cataclysm BN: active_tiles Namespace Reference
active_tiles Namespace Reference
Classes
struct furn_transform
Functions
template<typename T >
T * furn_at (const tripoint_abs_ms &p)
template active_tile_data * furn_at< active_tile_data > (const tripoint_abs_ms &)
template vehicle_connector_tile * furn_at< vehicle_connector_tile > (const tripoint_abs_ms &)
template battery_tile * furn_at< battery_tile > (const tripoint_abs_ms &)
template steady_consumer_tile * furn_at< steady_consumer_tile > (const tripoint_abs_ms &)
template charge_watcher_tile * furn_at< charge_watcher_tile > (const tripoint_abs_ms &)
Function Documentation
furn_at()
template<typename T > T * active_tiles::furn_at (const tripoint_abs_ms & p)
Definition at line 29 of file active_tile_data.cpp.
{
    tripoint_abs_sm p_abs_sm;
    point_sm_ms p_within_sm;
    std::tie( p_abs_sm, p_within_sm ) = project_remain<coords::sm>( p );
    submap *sm = MAPBUFFER.lookup_submap( p_abs_sm );
    if( sm == nullptr ) {
        return nullptr;
    }
    auto iter = sm->active_furniture.find( p_within_sm );
    if( iter == sm->active_furniture.end() ) {
        return nullptr;
    }
    return dynamic_cast<T *>( &*iter->second );
}
References mapbuffer::lookup_submap(), MAPBUFFER, and coords::sm.
furn_at< active_tile_data >()
template active_tile_data * active_tiles::furn_at< active_tile_data > (const tripoint_abs_ms &)
Referenced by complete_construction(), and game::grabbed_furn_move().
furn_at< battery_tile >()
template battery_tile * active_tiles::furn_at< battery_tile > (const tripoint_abs_ms &)
Referenced by iexamine::check_power(), distribution_grid::get_resource(), and distribution_grid::mod_resource().
furn_at< charge_watcher_tile >()
template charge_watcher_tile * active_tiles::furn_at< charge_watcher_tile > (const tripoint_abs_ms &)
furn_at< steady_consumer_tile >()
template steady_consumer_tile * active_tiles::furn_at< steady_consumer_tile > (const tripoint_abs_ms &)
furn_at< vehicle_connector_tile >()
template vehicle_connector_tile * active_tiles::furn_at< vehicle_connector_tile > (const tripoint_abs_ms &)
Referenced by iuse::cable_attach(), distribution_grid::get_resource(), distribution_grid::mod_resource(), vehicle::remove_remote_part(), and distribution_graph::traverse().