Cataclysm BN: game_menus::inv Namespace Reference
game_menus::inv Namespace Reference
Functions
item_location titled_menu (avatar &you, const std::string &title, const std::string &none_message="")
item_location titled_filter_menu (item_filter filter, avatar &you, const std::string &title, const std::string &none_message="")
Customized inventory menus
The functions here execute customized inventory menus for specific game situations.
Each menu displays only related inventory (or nearby) items along with context dependent information. More functions will follow. TODO: update all 'inv_for...()' functions to return item_location instead of plain int and move them here.
Returns
Either location of the selected item or null location if none was selected.
void common (avatar &you)
void compare (player &p, const cata::optional< tripoint > &offset)
void compare (const item &left, const item &right)
void reassign_letter (player &p, item &it)
void swap_letters (player &p)
drop_locations multidrop (player &p)
Select items to drop.
iuse_locations multiwash (Character &ch, int water, int cleanser, bool do_soft, bool do_hard)
Select items to wash.
item_location consume (player &p)
Consuming an item.
item_location consume_food (player &p)
Consuming a food item via a custom menu.
item_location consume_drink (player &p)
Consuming a drink item via a custom menu.
item_location consume_meds (player &p)
Consuming a medication item via a custom menu.
item_location container_for (avatar &you, const item &liquid, int radius=0)
Choosing a container for liquid.
item_location disassemble (player &p)
Item disassembling menu.
item_location gun_to_modify (player &p, const item &gunmod)
Gunmod installation menu.
item_location read (player &pl)
Book reading menu.
item_location steal (avatar &you, player &victim)
Menu for stealing stuff.
item_location use (avatar &you)
Item activation menu.
item_location wield (avatar &you)
Item wielding/unwielding menu.
item_location holster (player &p, item &holster)
Item wielding/unwielding menu.
item_location saw_barrel (player &p, item &tool)
Choosing a gun to saw down it's barrel.
item_location wear (player &p)
Choose item to wear.
item_location take_off (avatar &you)
Choose item to take off.
item_location salvage (player &p, const salvage_actor *actor)
Item cut up menu.
item_location repair (player &p, const repair_item_actor *actor, const item *main_tool)
Repair menu.
item_location install_bionic (player &p, player &patient, bool surgeon=false)
Bionic install menu.
item_location uninstall_bionic (player &p, player &patient)
Bionic uninstall menu.
item_location sterilize_cbm (player &p)
Autoclave sterilize menu.
Function Documentation
common()
void game_menus::inv::common (avatar & you)
Definition at line 233 of file game_inventory.cpp.
{
    inventory_pick_selector inv_s( you );
    inv_s.set_title( _( "Inventory" ) );
    inv_s.set_hint( string_format(
                        _( "Item hotkeys assigned: <color_light_gray>%d</color>/<color_light_gray>%d</color>" ),
                        you.allocated_invlets().count(), inv_chars.size() ) );
    bool started_action = false;
    do {
        you.inv.restack( you );
        inv_s.clear_items();
        inv_s.add_character_items( you );
        const item_location &location = inv_s.execute();
        if( location == item_location::nowhere ) {
            if( inv_s.keep_open ) {
                inv_s.keep_open = false;
                continue;
            } else {
                break;
            }
        }
        const auto func_pos_x = []() {
            return 0;
        };
        const auto func_width = []() {
            return 50;
        };
        started_action = examine_item_menu::run( location, func_pos_x, func_width,
                         examine_item_menu::menu_pos_t::right );
    } while( !started_action );
}
References _, inventory_selector::add_character_items(), Character::allocated_invlets(), inventory_selector::clear_items(), inventory_pick_selector::execute(), Character::inv, inv_chars, inventory_selector::keep_open, item_location::nowhere, inventory::restack(), examine_item_menu::right, examine_item_menu::run(), inventory_selector::set_hint(), inventory_selector::set_title(), and string_format().
Referenced by weather_generator::get_weather(), game::handle_action(), overmap::populate(), and weather_temperature_from_common_data().
compare() [1/2]
void game_menus::inv::compare (const item & left, const item & right)
Definition at line 1582 of file game_inventory.cpp.
{
    std::string action;
    input_context ctxt;
    ctxt.register_action( "HELP_KEYBINDINGS" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "UP" );
    ctxt.register_action( "DOWN" );
    ctxt.register_action( "PAGE_UP" );
    ctxt.register_action( "PAGE_DOWN" );
    std::vector<iteminfo> vItemLastCh;
    std::vector<iteminfo> vItemCh;
    std::string sItemLastCh;
    std::string sItemCh;
    std::string sItemLastTn;
    std::string sItemTn;
    l.info( true, vItemLastCh );
    sItemLastCh = l.tname();
    sItemLastTn = l.type_name();
    r.info( true, vItemCh );
    sItemCh = r.tname();
    sItemTn = r.type_name();
    int iScrollPos = 0;
    int iScrollPosLast = 0;
    item_info_data last_item_info( sItemLastCh, sItemLastTn, vItemLastCh, vItemCh, iScrollPosLast );
    last_item_info.without_getch = true;
    item_info_data cur_item_info( sItemCh, sItemTn, vItemCh, vItemLastCh, iScrollPos );
    cur_item_info.without_getch = true;
    catacurses::window w_last_item_info;
    catacurses::window w_cur_item_info;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const int half_width = TERMX / 2;
        const int height = TERMY;
        w_last_item_info = catacurses::newwin( height, half_width, point_zero );
        w_cur_item_info = catacurses::newwin( height, half_width, point( half_width, 0 ) );
        ui.position( point_zero, point( half_width * 2, height ) );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        draw_item_info( w_last_item_info, last_item_info );
        draw_item_info( w_cur_item_info, cur_item_info );
    } );
    do {
        ui_manager::redraw();
        action = ctxt.handle_input();
        if( action == "UP" || action == "PAGE_UP" ) {
            iScrollPos--;
            iScrollPosLast--;
        } else if( action == "DOWN" || action == "PAGE_DOWN" ) {
            iScrollPos++;
            iScrollPosLast++;
        }
    } while( action != "QUIT" );
}
References action, draw_item_info(), input_context::handle_input(), item::info(), catacurses::newwin(), point_zero, ui_manager::redraw(), input_context::register_action(), TERMX, TERMY, item::tname(), item::type_name(), and item_info_data::without_getch.
compare() [2/2]
void game_menus::inv::compare (player & p, const cata::optional< tripoint > & offset)
Definition at line 1549 of file game_inventory.cpp.
{
    p.inv.restack( p );
    inventory_compare_selector inv_s( p );
    inv_s.add_character_items( p );
    inv_s.set_title( _( "Compare" ) );
    inv_s.set_hint( _( "Select two items to compare them." ) );
    if( offset ) {
        inv_s.add_map_items( p.pos() + *offset );
        inv_s.add_vehicle_items( p.pos() + *offset );
    } else {
        inv_s.add_nearby_items();
    }
    if( inv_s.empty() ) {
        popup( std::string( _( "There are no items to compare." ) ), PF_GET_KEY );
        return;
    }
    do {
        const auto to_compare = inv_s.execute();
        if( to_compare.first == nullptr || to_compare.second == nullptr ) {
            break;
        }
        compare( *to_compare.first, *to_compare.second );
    } while( true );
}
References _, inventory_selector::add_character_items(), inventory_selector::add_map_items(), inventory_selector::add_nearby_items(), inventory_selector::add_vehicle_items(), compare(), inventory_selector::empty(), inventory_compare_selector::execute(), Character::inv, PF_GET_KEY, popup(), Character::pos(), inventory::restack(), inventory_selector::set_hint(), and inventory_selector::set_title().
Referenced by basic_string_view< Char >::compare(), compare(), detail::fallback_format(), ma_buff::from_effect(), player::gunmod_add(), game::handle_action(), game::list_items(), cata::list< element_type, element_allocator_type >::merge(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::sort(), cata::list< element_type, element_allocator_type >::sort(), and cata::list< element_type, element_allocator_type >::unique().
consume()
item_location game_menus::inv::consume (player & p)
Consuming an item.
Definition at line 758 of file game_inventory.cpp.
{
    if( !g->u.has_activity( ACT_EAT_MENU ) ) {
        g->u.assign_activity( ACT_EAT_MENU );
    }
    return inv_internal( p, comestible_inventory_preset( p ),
                         _( "Consume item" ), 1,
                         _( "You have nothing to consume." ),
                         get_consume_needs_hint( p ) );
}
References _, ACT_EAT_MENU, g, get_consume_needs_hint(), and inv_internal().
Referenced by avatar_action::eat().
consume_drink()
item_location game_menus::inv::consume_drink (player & p)
Consuming a drink item via a custom menu.
Definition at line 800 of file game_inventory.cpp.
{
    if( !g->u.has_activity( ACT_CONSUME_DRINK_MENU ) ) {
        g->u.assign_activity( ACT_CONSUME_DRINK_MENU );
    }
    return inv_internal( p, comestible_filtered_inventory_preset( p, []( const item & it ) {
        return it.is_comestible() && it.get_comestible()->comesttype == "DRINK" &&
               !it.has_flag( flag_USE_EAT_VERB );
    } ),
    _( "Consume drink" ), 1,
    _( "You have no drink to consume." ),
    get_consume_needs_hint( p ) );
}
References _, ACT_CONSUME_DRINK_MENU, flag_USE_EAT_VERB(), g, item::get_comestible(), get_consume_needs_hint(), item::has_flag(), inv_internal(), and item::is_comestible().
Referenced by activity_handlers::consume_drink_menu_do_turn(), and game::open_consume_item_menu().
consume_food()
item_location game_menus::inv::consume_food (player & p)
Consuming a food item via a custom menu.
Definition at line 785 of file game_inventory.cpp.
{
    if( !g->u.has_activity( ACT_CONSUME_FOOD_MENU ) ) {
        g->u.assign_activity( ACT_CONSUME_FOOD_MENU );
    }
    return inv_internal( p, comestible_filtered_inventory_preset( p, []( const item & it ) {
        return ( it.is_comestible() && it.get_comestible()->comesttype == "FOOD" ) ||
               it.has_flag( flag_USE_EAT_VERB );
    } ),
    _( "Consume food" ), 1,
    _( "You have no food to consume." ),
    get_consume_needs_hint( p ) );
}
References _, ACT_CONSUME_FOOD_MENU, flag_USE_EAT_VERB(), g, item::get_comestible(), get_consume_needs_hint(), item::has_flag(), inv_internal(), and item::is_comestible().
Referenced by activity_handlers::consume_food_menu_do_turn(), and game::open_consume_item_menu().
consume_meds()
item_location game_menus::inv::consume_meds (player & p)
Consuming a medication item via a custom menu.
Definition at line 815 of file game_inventory.cpp.
{
    if( !g->u.has_activity( ACT_CONSUME_MEDS_MENU ) ) {
        g->u.assign_activity( ACT_CONSUME_MEDS_MENU );
    }
    return inv_internal( p, comestible_filtered_inventory_preset( p, []( const item & it ) {
        return it.is_medication();
    } ),
    _( "Consume medication" ), 1,
    _( "You have no medication to consume." ),
    get_consume_needs_hint( p ) );
}
References _, ACT_CONSUME_MEDS_MENU, g, get_consume_needs_hint(), inv_internal(), and item::is_medication().
Referenced by activity_handlers::consume_meds_menu_do_turn(), and game::open_consume_item_menu().
container_for()
item_location game_menus::inv::container_for (avatar & you, const item & liquid, int radius = 0)
Choosing a container for liquid.
Definition at line 404 of file game_inventory.cpp.
{
    const auto filter = [ &liquid ]( const item_location & location ) {
        if( location.where() == item_location::type::character ) {
            Character *character = g->critter_at<Character>( location.position() );
            if( character == nullptr ) {
                debugmsg( "Invalid location supplied to the liquid filter: no character found." );
                return false;
            }
            return location->get_remaining_capacity_for_liquid( liquid, *character ) > 0;
        }
        const bool allow_buckets = location.where() == item_location::type::map;
        return location->get_remaining_capacity_for_liquid( liquid, allow_buckets ) > 0;
    };
    return inv_internal( you, inventory_filter_preset( filter ),
                         string_format( _( "Container for %s" ), liquid.display_name( liquid.charges ) ), radius,
                         string_format( _( "You don't have a suitable container for carrying %s." ),
                                        liquid.tname() ) );
}
References _, item_location::character, item::charges, debugmsg, item::display_name(), g, inv_internal(), item_location::map, string_format(), and item::tname().
Referenced by liquid_handler::get_liquid_target().
disassemble()
item_location game_menus::inv::disassemble (player & p)
Item disassembling menu.
Definition at line 497 of file game_inventory.cpp.
{
    return inv_internal( p, disassemble_inventory_preset( p, p.crafting_inventory() ),
                         _( "Disassemble item" ), 1,
                         _( "You don't have any items you could disassemble." ) );
}
References _, Character::crafting_inventory(), and inv_internal().
Referenced by crafting::disassemble().
gun_to_modify()
item_location game_menus::inv::gun_to_modify (player & p, const item & gunmod)
Gunmod installation menu.
Definition at line 968 of file game_inventory.cpp.
{
    return inv_internal( p, gunmod_inventory_preset( p, gunmod ),
                         _( "Select gun to modify" ), -1,
                         _( "You don't have any guns to modify." ) );
}
References _, and inv_internal().
Referenced by iuse::gunmod_attach().
holster()
item_location game_menus::inv::holster (player & p, item & holster)
Item wielding/unwielding menu.
Definition at line 1356 of file game_inventory.cpp.
{
    const std::string holster_name = holster.tname( 1, false );
    const auto actor = dynamic_cast<const holster_actor *>
                       ( holster.type->get_use( "holster" )->get_actor_ptr() );
    if( !actor ) {
        const std::string msg = string_format( _( "You can't put anything into your %s." ),
                                               holster_name );
        popup( msg, PF_GET_KEY );
        return item_location();
    }
    const std::string title = actor->holster_prompt.empty()
                              ? _( "Holster item" )
                              : _( actor->holster_prompt );
    const std::string hint = string_format( _( "Choose an item to put into your %s" ),
                                            holster_name );
    return inv_internal( p, holster_inventory_preset( p, *actor ), title, 1,
                         string_format( _( "You have no items you could put into your %s." ),
                                        holster_name ),
                         hint );
}
References _, holster(), inv_internal(), PF_GET_KEY, popup(), string_format(), and PATH_INFO::title().
Referenced by holster(), holster_actor::store(), and holster_actor::use().
install_bionic()
item_location game_menus::inv::install_bionic (player & p, player & patient, bool surgeon = false)
Bionic install menu.
Definition at line 1972 of file game_inventory.cpp.
{
    if( surgeon ) {
        return autodoc_internal( p, patient, bionic_install_surgeon_preset( p, patient ), 5, false,
                                 surgeon );
    } else {
        return autodoc_internal( p, patient, bionic_install_preset( p, patient ), 5 );
    }
}
References autodoc_internal().
Referenced by iexamine::autodoc(), and talk_function::bionic_install().
multidrop()
drop_locations game_menus::inv::multidrop (player & p)
Select items to drop.
Returns
A list of pairs of item_location, quantity.
Definition at line 1480 of file game_inventory.cpp.
{
    p.inv.restack( p );
    const inventory_filter_preset preset( [ &p ]( const item_location & location ) {
        const item &itm = *location;
        if( p.is_wielding( itm ) ) {
            return p.can_unwield( itm ).success();
        } else if( p.is_wearing( itm ) ) {
            return p.can_takeoff( itm ).success();
        } else {
            return true;
        }
    } );
    inventory_drop_selector inv_s( p, preset );
    inv_s.add_character_items( p );
    inv_s.set_title( _( "Multidrop" ) );
    inv_s.set_hint( _( "To drop x items, type a number before selecting." ) );
    if( inv_s.empty() ) {
        popup( std::string( _( "You have nothing to drop." ) ), PF_GET_KEY );
        return drop_locations();
    }
    return inv_s.execute();
}
References _, Character::inv, Character::is_wearing(), Character::is_wielding(), PF_GET_KEY, popup(), and inventory::restack().
Referenced by game::drop(), game::drop_in_direction(), and monexamine::give_items_to().
multiwash()
iuse_locations game_menus::inv::multiwash (Character & ch, int water, int cleanser, bool do_soft, bool do_hard)
Select items to wash.
Parameters
water Available water
cleanser Available cleanser
do_soft Whether to allow soft items
do_hard Whether to allow hard items
Returns
A list of selected item_locations with quantities.
Definition at line 1509 of file game_inventory.cpp.
{
    const inventory_filter_preset preset( [do_soft, do_hard]( const item_location & location ) {
        return location->has_flag( "FILTHY" ) && ( ( do_soft && location->is_soft() ) ||
                ( do_hard && !location->is_soft() ) );
    } );
    auto make_raw_stats = [water, cleanser](
                              const std::map<const item *, int> &items
    ) {
        units::volume total_volume = 0_ml;
        for( const auto &it : items ) {
            total_volume += it.first->volume() * it.second / it.first->count();
        }
        washing_requirements required = washing_requirements_for_volume( total_volume );
        auto to_string = []( int val ) -> std::string {
            if( val == INT_MAX )
            {
                return "inf";
            }
            return string_format( "%3d", val );
        };
        using stats = inventory_selector::stats;
        return stats{ {
                display_stat( _( "Water" ), required.water, water, to_string ),
                display_stat( _( "Cleanser" ), required.cleanser, cleanser, to_string )
            } };
    };
    inventory_iuse_selector inv_s( *ch.as_player(), _( "ITEMS TO CLEAN" ), preset, make_raw_stats );
    inv_s.add_character_items( ch );
    inv_s.add_nearby_items( PICKUP_RANGE );
    inv_s.set_title( _( "Multiclean" ) );
    inv_s.set_hint( _( "To clean x items, type a number before selecting." ) );
    if( inv_s.empty() ) {
        popup( std::string( _( "You have nothing to clean." ) ), PF_GET_KEY );
        return {};
    }
    return inv_s.execute();
}
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), Creature::as_player(), washing_requirements::cleanser, display_stat(), inventory_selector::empty(), inventory_iuse_selector::execute(), item::has_flag(), item::is_soft(), PF_GET_KEY, PICKUP_RANGE, popup(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), to_string(), washing_requirements_for_volume(), and washing_requirements::water.
Referenced by wash_items().
read()
item_location game_menus::inv::read (player & pl)
Book reading menu.
Definition at line 1221 of file game_inventory.cpp.
{
    const std::string none_msg = pl.is_player() ? _( "You have nothing to read." ) :
                                 string_format( _( "%s has nothing to read." ), pl.disp_name() );
    return inv_internal( pl, read_inventory_preset( pl ), _( "Read" ), 1, none_msg );
}
References _, Character::disp_name(), inv_internal(), player::is_player(), and string_format().
Referenced by npc::do_npc_read(), and read().
reassign_letter()
void game_menus::inv::reassign_letter (player & p, item & it)
Definition at line 1650 of file game_inventory.cpp.
{
    while( true ) {
        const int invlet = popup_getkey(
                               _( "Enter new letter.  Press SPACE to clear a manually assigned letter, ESCAPE to cancel." ) );
        if( invlet == KEY_ESCAPE ) {
            break;
        } else if( invlet == ' ' ) {
            p.reassign_item( it, 0 );
            const std::string auto_setting = get_option<std::string>( "AUTO_INV_ASSIGN" );
            if( auto_setting == "enabled" || ( auto_setting == "favorites" && it.is_favorite ) ) {
                popup_getkey(
                    _( "Note: The Auto Inventory Letters setting might still reassign a letter to this item.\n"
                       "If this is undesired, you may wish to change the setting in Options." ) );
            }
            break;
        } else if( inv_chars.valid( invlet ) ) {
            p.reassign_item( it, invlet );
            break;
        }
    }
}
References _, inv_chars, item::is_favorite, KEY_ESCAPE, popup_getkey(), player::reassign_item(), and invlet_wrapper::valid().
Referenced by examine_item_menu::run(), and swap_letters().
repair()
item_location game_menus::inv::repair (player & p, const repair_item_actor * actor, const item * main_tool)
Repair menu.
Definition at line 1452 of file game_inventory.cpp.
{
    return inv_internal( p, repair_inventory_preset( actor, main_tool ),
                         _( "Repair what?" ), 1,
                         string_format( _( "You have no items that could be repaired with a %s." ),
                                        main_tool->type_name( 1 ) ) );
}
References _, inv_internal(), string_format(), and item::type_name().
Referenced by activity_handlers::repair_item_finish().
salvage()
item_location game_menus::inv::salvage (player & p, const salvage_actor * actor)
Item cut up menu.
Definition at line 1428 of file game_inventory.cpp.
{
    return inv_internal( p, salvage_inventory_preset( actor ),
                         _( "Cut up what?" ), 1,
                         _( "You have nothing to cut up." ) );
}
References _, and inv_internal().
Referenced by salvage_actor::use().
saw_barrel()
item_location game_menus::inv::saw_barrel (player & p, item & tool)
Choosing a gun to saw down it's barrel.
Definition at line 1461 of file game_inventory.cpp.
{
    const auto actor = dynamic_cast<const saw_barrel_actor *>
                       ( tool.type->get_use( "saw_barrel" )->get_actor_ptr() );
    if( !actor ) {
        debugmsg( "Tried to use a wrong item." );
        return item_location();
    }
    return inv_internal( p, saw_barrel_inventory_preset( p, tool, *actor ),
                         _( "Saw barrel" ), 1,
                         _( "You don't have any guns." ),
                         string_format( _( "Choose a weapon to use your %s on" ),
                                        tool.tname( 1, false )
                                      )
                       );
}
References _, debugmsg, inv_internal(), string_format(), and tool.
Referenced by saw_barrel_actor::use().
steal()
item_location game_menus::inv::steal (avatar & you, player & victim)
Menu for stealing stuff.
Definition at line 1242 of file game_inventory.cpp.
{
    return inv_internal( victim, steal_inventory_preset( you, victim ),
                         string_format( _( "Steal from %s" ), victim.name ), -1,
                         string_format( _( "%s's inventory is empty." ), victim.name ) );
}
References _, inv_internal(), Character::name, and string_format().
Referenced by game::npc_menu(), and avatar::steal().
sterilize_cbm()
item_location game_menus::inv::sterilize_cbm (player & p)
Autoclave sterilize menu.
Definition at line 2120 of file game_inventory.cpp.
{
    return autoclave_internal( p, bionic_sterilize_preset( p ), 6 );
}
References autoclave_internal().
Referenced by iexamine::autoclave_empty().
swap_letters()
void game_menus::inv::swap_letters (player & p)
Definition at line 1674 of file game_inventory.cpp.
{
    p.inv.restack( p );
    inventory_pick_selector inv_s( p );
    inv_s.add_character_items( p );
    inv_s.set_title( _( "Swap Inventory Letters" ) );
    inv_s.set_display_stats( false );
    if( inv_s.empty() ) {
        popup( std::string( _( "Your inventory is empty." ) ), PF_GET_KEY );
        return;
    }
    while( true ) {
        const std::string invlets = colorize_symbols( inv_chars.get_allowed_chars(),
        [ &p ]( const std::string::value_type & elem ) {
            if( p.inv.assigned_invlet.count( elem ) ) {
                return c_yellow;
            } else if( p.invlet_to_item( elem ) != nullptr ) {
                return c_white;
            } else {
                return c_dark_gray;
            }
        } );
        inv_s.set_hint( invlets );
        auto loc = inv_s.execute();
        if( !loc ) {
            break;
        }
        reassign_letter( p, *loc );
    }
}
References _, inventory_selector::add_character_items(), colorize_symbols(), inventory_selector::empty(), inventory_pick_selector::execute(), invlet_wrapper::get_allowed_chars(), Character::inv, inv_chars, Character::invlet_to_item(), PF_GET_KEY, popup(), reassign_letter(), inventory::restack(), inventory_selector::set_display_stats(), inventory_selector::set_hint(), and inventory_selector::set_title().
Referenced by game::handle_action().
take_off()
item_location game_menus::inv::take_off (avatar & you)
Choose item to take off.
Definition at line 391 of file game_inventory.cpp.
{
    return inv_internal( you, take_off_inventory_preset( you, "color_red" ), _( "Take off item" ), 1,
                         _( "You don't wear anything." ) );
}
References _, and inv_internal().
Referenced by takeoff().
titled_filter_menu()
item_location game_menus::inv::titled_filter_menu (item_filter filter, avatar & you, const std::string & title, const std::string & none_message = "")
Definition at line 270 of file game_inventory.cpp.
{
    return inv_internal( you, inventory_filter_preset( convert_filter( filter ) ),
                         title, -1, none_message );
}
References convert_filter(), inv_internal(), and PATH_INFO::title().
Referenced by monexamine::attach_bag_to(), iuse::cable_attach(), iuse::camera(), iexamine::dimensional_portal(), iuse::einktabletpc(), iuse::lumber(), iuse::mind_splicer(), game::npc_menu(), pet_armor_loc(), pick_usb(), iuse::radio_mod(), iuse::radiocar(), tack_loc(), and sew_advanced_actor::use().
titled_menu()
item_location game_menus::inv::titled_menu (avatar & you, const std::string & title, const std::string & none_message = "")
Definition at line 277 of file game_inventory.cpp.
{
    const std::string msg = none_message.empty() ? _( "Your inventory is empty." ) : none_message;
    return inv_internal( you, inventory_selector_preset(), title, -1, msg );
}
References _, inv_internal(), and PATH_INFO::title().
Referenced by debug_menu::character_edit_menu(), give_item_to(), iuse::gun_repair(), avatar_action::plthrow(), and inscribe_actor::use().
uninstall_bionic()
item_location game_menus::inv::uninstall_bionic (player & p, player & patient)
Bionic uninstall menu.
Definition at line 2058 of file game_inventory.cpp.
{
    return autodoc_internal( p, patient, bionic_uninstall_preset( p, patient ), 0, true );
}
References autodoc_internal().
Referenced by iexamine::autodoc().
use()
item_location game_menus::inv::use (avatar & you)
Item activation menu.
Definition at line 897 of file game_inventory.cpp.
{
    return inv_internal( you, activatable_inventory_preset( you ),
                         _( "Use item" ), 1,
                         _( "You don't have any items you can use." ) );
}
References _, and inv_internal().
Referenced by itype::invoke(), mattack::kamikaze(), item_action_generator::map_actions_to_items(), and avatar_action::use_item().
wear()
item_location game_menus::inv::wear (player & p)
Choose item to wear.
Definition at line 363 of file game_inventory.cpp.
{
    return inv_internal( p, wear_inventory_preset( p, "color_yellow" ), _( "Wear item" ), 1,
                         _( "You have nothing to wear." ) );
}
References _, and inv_internal().
Referenced by player::sort_armor(), and wear().
wield()
item_location game_menus::inv::wield (avatar & you)
Item wielding/unwielding menu.
Definition at line 1335 of file game_inventory.cpp.
{
    return inv_internal( you, weapon_inventory_preset( you ), _( "Wield item" ), 1,
                         _( "You have nothing to wield." ) );
}
References _, and inv_internal().
Referenced by avatar_action::wield().