Cataclysm BN: src/ncurses_def.cpp File Reference
ncurses_def.cpp File Reference
#include "input.h"
#include <curses.h>
#include <cstring>
#include <langinfo.h>
#include <stdexcept>
#include "cursesdef.h"
#include "catacharset.h"
#include "color.h"
#include "game_ui.h"
#include "output.h"
#include "ui_manager.h"
Macros
#define NCURSES_NOMACROS
Functions
static void curses_check_result (const int result, const int expected, const char *const)
void refresh_display ()
Make changes made to the display visible to the user immediately.
void ensure_term_size ()
void check_encoding ()
Macro Definition Documentation
NCURSES_NOMACROS
#define NCURSES_NOMACROS
Definition at line 9 of file ncurses_def.cpp.
Function Documentation
check_encoding()
void check_encoding ()
Definition at line 425 of file ncurses_def.cpp.
{
    // Check whether LC_CTYPE supports the UTF-8 encoding
    // and show a warning if it doesn't
    if( std::strcmp( nl_langinfo( CODESET ), "UTF-8" ) != 0 ) {
        // do not use ui_adaptor here to avoid re-entry
        int key = ERR;
        do {
            const char *unicode_error_msg =
                _( "You don't seem to have a valid Unicode locale.  You may see some weird "
                   "characters (e.g. empty boxes or question marks). You have been warned." );
            catacurses::erase();
            const int maxx = getmaxx( catacurses::stdscr );
            fold_and_print( catacurses::stdscr, point_zero, maxx, c_white, unicode_error_msg );
            catacurses::refresh();
            // do not use input_manager or input_context here to avoid re-entry
            key = getch();
        } while( key == KEY_RESIZE || key == KEY_MOUSE );
    }
}
References _, c_white, catacurses::erase(), fold_and_print(), catacurses::getmaxx(), point_zero, catacurses::refresh(), and catacurses::stdscr.
Referenced by game_ui::init_ui().
curses_check_result()
static void curses_check_result (const int result, const int expected, const char * const) static
Definition at line 27 of file ncurses_def.cpp.
{
    if( result != expected ) {
        // TODO: debug message
    }
}
Referenced by catacurses::clear(), catacurses::curs_set(), catacurses::doupdate(), catacurses::endwin(), catacurses::erase(), catacurses::init_pair(), catacurses::mvwaddch(), catacurses::mvwhline(), catacurses::mvwprintw(), catacurses::mvwvline(), catacurses::newwin(), catacurses::refresh(), catacurses::waddch(), catacurses::wattroff(), catacurses::wattron(), catacurses::wborder(), catacurses::wclear(), catacurses::werase(), catacurses::wmove(), catacurses::wnoutrefresh(), catacurses::wprintw(), catacurses::wredrawln(), and catacurses::wrefresh().
ensure_term_size()
void ensure_term_size ()
Definition at line 389 of file ncurses_def.cpp.
{
    // do not use ui_adaptor here to avoid re-entry
    const int minHeight = FULL_SCREEN_HEIGHT;
    const int minWidth = FULL_SCREEN_WIDTH;
    int maxy = getmaxy( catacurses::stdscr );
    int maxx = getmaxx( catacurses::stdscr );
    while( maxy < minHeight || maxx < minWidth ) {
        catacurses::erase();
        if( maxy < minHeight && maxx < minWidth ) {
            fold_and_print( catacurses::stdscr, point_zero, maxx, c_white,
                            _( "Whoa!  Your terminal is tiny!  This game requires a minimum terminal size of "
                               "%dx%d to work properly.  %dx%d just won't do.  Maybe a smaller font would help?" ),
                            minWidth, minHeight, maxx, maxy );
        } else if( maxx < minWidth ) {
            fold_and_print( catacurses::stdscr, point_zero, maxx, c_white,
                            _( "Oh!  Hey, look at that.  Your terminal is just a little too narrow.  This game "
                               "requires a minimum terminal size of %dx%d to function.  It just won't work "
                               "with only %dx%d.  Can you stretch it out sideways a bit?" ),
                            minWidth, minHeight, maxx, maxy );
        } else {
            fold_and_print( catacurses::stdscr, point_zero, maxx, c_white,
                            _( "Woah, woah, we're just a little short on space here.  The game requires a "
                               "minimum terminal size of %dx%d to run.  %dx%d isn't quite enough!  Can you "
                               "make the terminal just a smidgen taller?" ),
                            minWidth, minHeight, maxx, maxy );
        }
        catacurses::refresh();
        // do not use input_manager or input_context here to avoid re-entry
        getch();
        maxy = getmaxy( catacurses::stdscr );
        maxx = getmaxx( catacurses::stdscr );
    }
}
References _, c_white, catacurses::erase(), fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, catacurses::getmaxx(), catacurses::getmaxy(), point_zero, catacurses::refresh(), and catacurses::stdscr.
Referenced by game_ui::init_ui().
refresh_display()
void refresh_display ()
Make changes made to the display visible to the user immediately.
In curses mode, this is a no-op. In SDL mode, this refreshes the real display from the backing buffer immediately, rather than delaying the update until the next time we are waiting for user input.
Definition at line 120 of file ncurses_def.cpp.
{
    catacurses::doupdate();
}
References catacurses::doupdate().
Referenced by computer_session::action_emerg_ref_center(), debug_menu::benchmark(), game::cancel_activity_or_ignore_query(), game::do_turn(), anonymous_namespace{animation.cpp}::basic_animation::draw(), game::fling_creature(), game::handle_key_blocking_activity(), defense_game::init_map(), game::load(), map::move_vehicle(), robot_finds_kitten::process_input(), game::quicksave(), mattack::ranged_pull(), throbber_popup::refresh(), mapbuffer::save(), game::setup(), loading_ui::show(), options_manager::show(), game::start_game(), and game::unserialize_master().