Cataclysm BN: src/npc.cpp File Reference
npc.cpp File Reference
#include "npc.h"
#include <algorithm>
#include <cassert>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <limits>
#include <memory>
#include "auto_pickup.h"
#include "avatar.h"
#include "basecamp.h"
#include "bodypart.h"
#include "character.h"
#include "character_id.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "clzones.h"
#include "coordinate_conversions.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "int_id.h"
#include "item.h"
#include "item_contents.h"
#include "item_group.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "json.h"
#include "magic.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "math_defines.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc_class.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pathfinding.h"
#include "player_activity.h"
#include "pldata.h"
#include "ranged.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_utils.h"
#include "text_snippets.h"
#include "tileray.h"
#include "trait_group.h"
#include "translations.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
#include "vpart_range.h"
Functions
static const std::string flag_NPC_SAFE ("NPC_SAFE")
void starting_clothes (npc &who, const npc_class_id &type, bool male)
void starting_inv (npc &who, const npc_class_id &type)
static item random_item_from (const npc_class_id &type, const std::string &what, const item_group_id &fallback)
static item random_item_from (const npc_class_id &type, const std::string &what)
static item get_clothing_item (const npc_class_id &type, const std::string &what, bool male)
static void maybe_shift (cata::optional< tripoint > &pos, const point &d)
static void maybe_shift (tripoint &pos, const point &d)
std::string npc_attitude_id (npc_attitude att)
std::string npc_attitude_name (npc_attitude att)
std::ostream & operator<< (std::ostream &os, const npc_need &need)
Variables
static const activity_id ACT_READ ("ACT_READ")
static const efftype_id effect_ai_waiting ("ai_waiting")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_infection ("infection")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_npc_flee_player ("npc_flee_player")
static const efftype_id effect_npc_suspend ("npc_suspend")
static const efftype_id effect_pkill_l ("pkill_l")
static const efftype_id effect_pkill1 ("pkill1")
static const efftype_id effect_pkill2 ("pkill2")
static const efftype_id effect_pkill3 ("pkill3")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_riding ("riding")
static const itype_id itype_UPS_off ("UPS_off")
static const skill_id skill_archery ("archery")
static const skill_id skill_barter ("barter")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_pistol ("pistol")
static const skill_id skill_rifle ("rifle")
static const skill_id skill_shotgun ("shotgun")
static const skill_id skill_smg ("smg")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_throw ("throw")
static const bionic_id bio_eye_optic ("bio_eye_optic")
static const bionic_id bio_memory ("bio_memory")
static const trait_id trait_BEE ("BEE")
static const trait_id trait_CANNIBAL ("CANNIBAL")
static const trait_id trait_DEBUG_MIND_CONTROL ("DEBUG_MIND_CONTROL")
static const trait_id trait_HALLUCINATION ("HALLUCINATION")
static const trait_id trait_HYPEROPIC ("HYPEROPIC")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_MUTE ("MUTE")
static const trait_id trait_PROF_DICEMASTER ("PROF_DICEMASTER")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_SAPIOVORE ("SAPIOVORE")
static const trait_id trait_SCHIZOPHRENIC ("SCHIZOPHRENIC")
static const trait_id trait_TERRIFYING ("TERRIFYING")
static std::map< string_id< npc_template >, npc_template > npc_templates
Function Documentation
flag_NPC_SAFE()
static const std::string flag_NPC_SAFE ("NPC_SAFE") static
Referenced by npc::will_accept_from_player().
get_clothing_item()
static item get_clothing_item (const npc_class_id & type, const std::string & what, bool male) static
Definition at line 529 of file npc.cpp.
{
    item result;
    //Check if class has gendered clothing
    //Then check if it has an ungendered version
    //Only if all that fails, grab from the default class.
    if( male ) {
        result = random_item_from( type, what + "_male", item_group_id::NULL_ID() );
    } else {
        result = random_item_from( type, what + "_female", item_group_id::NULL_ID() );
    }
    if( result.is_null() ) {
        if( male ) {
            result = random_item_from( type, what, item_group_id( "npc_" + what + "_male" ) );
        } else {
            result = random_item_from( type, what, item_group_id( "npc_" + what + "_female" ) );
        }
    }
    return result;
}
References male, string_id< Item_group >::NULL_ID(), random_item_from(), and type.
Referenced by starting_clothes().
maybe_shift() [1/2]
static void maybe_shift (cata::optional< tripoint > & pos, const point & d) static
Definition at line 2389 of file npc.cpp.
{
    if( pos ) {
        *pos += d;
    }
}
Referenced by npc::shift().
maybe_shift() [2/2]
static void maybe_shift (tripoint & pos, const point & d) static
Definition at line 2396 of file npc.cpp.
{
    if( pos != tripoint_min ) {
        pos += d;
    }
}
References tripoint_min.
npc_attitude_id()
std::string npc_attitude_id (npc_attitude att)
Definition at line 2529 of file npc.cpp.
{
    static const std::map<npc_attitude, std::string> npc_attitude_ids = {
        { NPCATT_NULL, "NPCATT_NULL" },
        { NPCATT_TALK, "NPCATT_TALK" },
        { NPCATT_FOLLOW, "NPCATT_FOLLOW" },
        { NPCATT_LEAD, "NPCATT_LEAD" },
        { NPCATT_WAIT, "NPCATT_WAIT" },
        { NPCATT_MUG, "NPCATT_MUG" },
        { NPCATT_WAIT_FOR_LEAVE, "NPCATT_WAIT_FOR_LEAVE" },
        { NPCATT_KILL, "NPCATT_KILL" },
        { NPCATT_FLEE, "NPCATT_FLEE" },
        { NPCATT_FLEE_TEMP, "NPCATT_FLEE_TEMP" },
        { NPCATT_HEAL, "NPCATT_HEAL" },
        { NPCATT_ACTIVITY, "NPCATT_ACTIVITY" },
        { NPCATT_RECOVER_GOODS, "NPCATT_RECOVER_GOODS" },
        { NPCATT_LEGACY_1, "NPCATT_LEGACY_1" },
        { NPCATT_LEGACY_2, "NPCATT_LEGACY_2" },
        { NPCATT_LEGACY_3, "NPCATT_LEGACY_3" },
        { NPCATT_LEGACY_4, "NPCATT_LEGACY_4" },
        { NPCATT_LEGACY_5, "NPCATT_LEGACY_5" },
        { NPCATT_LEGACY_6, "NPCATT_LEGACY_6" },
    };
    const auto &iter = npc_attitude_ids.find( att );
    if( iter == npc_attitude_ids.end() ) {
        debugmsg( "Invalid attitude: %d", att );
        return "NPCATT_INVALID";
    }
    return iter->second;
}
References debugmsg, NPCATT_ACTIVITY, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_FOLLOW, NPCATT_HEAL, NPCATT_KILL, NPCATT_LEAD, NPCATT_LEGACY_1, NPCATT_LEGACY_2, NPCATT_LEGACY_3, NPCATT_LEGACY_4, NPCATT_LEGACY_5, NPCATT_LEGACY_6, NPCATT_MUG, NPCATT_NULL, NPCATT_RECOVER_GOODS, NPCATT_TALK, NPCATT_WAIT, and NPCATT_WAIT_FOR_LEAVE.
Referenced by npc::form_opinion(), and npc::set_attitude().
npc_attitude_name()
std::string npc_attitude_name (npc_attitude att)
Definition at line 2561 of file npc.cpp.
{
    switch( att ) {
        // Don't care/ignoring player
        case NPCATT_NULL:
            return _( "Ignoring" );
        // Move to and talk to player
        case NPCATT_TALK:
            return _( "Wants to talk" );
        // Follow the player
        case NPCATT_FOLLOW:
            return _( "Following" );
        // Lead the player, wait for them if they're behind
        case NPCATT_LEAD:
            return _( "Leading" );
        // Waiting for the player
        case NPCATT_WAIT:
            return _( "Waiting for you" );
        // Mug the player
        case NPCATT_MUG:
            return _( "Mugging you" );
        // Attack the player if our patience runs out
        case NPCATT_WAIT_FOR_LEAVE:
            return _( "Waiting for you to leave" );
        // Kill the player
        case NPCATT_KILL:
            return _( "Attacking to kill" );
        // Get away from the player
        case NPCATT_FLEE:
        case NPCATT_FLEE_TEMP:
            return _( "Fleeing" );
        // Get to the player and heal them
        case NPCATT_HEAL:
            return _( "Healing you" );
        case NPCATT_ACTIVITY:
            return _( "Performing a task" );
        case NPCATT_RECOVER_GOODS:
            return _( "Trying to recover stolen goods" );
        case NPCATT_LEGACY_1:
        case NPCATT_LEGACY_2:
        case NPCATT_LEGACY_3:
        case NPCATT_LEGACY_4:
        case NPCATT_LEGACY_5:
        case NPCATT_LEGACY_6:
            return _( "NPC Legacy Attitude" );
        default:
            break;
    }
    debugmsg( "Invalid attitude: %d", att );
    return _( "Unknown attitude" );
}
References _, debugmsg, NPCATT_ACTIVITY, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_FOLLOW, NPCATT_HEAL, NPCATT_KILL, NPCATT_LEAD, NPCATT_LEGACY_1, NPCATT_LEGACY_2, NPCATT_LEGACY_3, NPCATT_LEGACY_4, NPCATT_LEGACY_5, NPCATT_LEGACY_6, NPCATT_MUG, NPCATT_NULL, NPCATT_RECOVER_GOODS, NPCATT_TALK, NPCATT_WAIT, and NPCATT_WAIT_FOR_LEAVE.
Referenced by debug_menu::character_edit_menu(), and game::list_monsters().
operator<<()
std::ostream & operator<< (std::ostream & os, const npc_need & need)
Definition at line 2894 of file npc.cpp.
{
    return os << npc::get_need_str_id( need );
}
References npc::get_need_str_id().
random_item_from() [1/2]
static item random_item_from (const npc_class_id & type, const std::string & what) static
Definition at line 523 of file npc.cpp.
{
    return random_item_from( type, what, item_group_id( "npc_" + what ) );
}
References random_item_from(), and type.
random_item_from() [2/2]
static item random_item_from (const npc_class_id & type, const std::string & what, const item_group_id & fallback) static
Definition at line 512 of file npc.cpp.
{
    auto result = item_group::item_from( item_group_id( type.str() + "_" + what ), calendar::turn );
    if( result.is_null() ) {
        result = item_group::item_from( fallback, calendar::turn );
    }
    return result;
}
References item_group::item_from(), calendar::turn, and type.
Referenced by get_clothing_item(), random_item_from(), starting_clothes(), starting_inv(), and npc::starting_weapon().
starting_clothes()
void starting_clothes (npc & who, const npc_class_id & type, bool male)
Definition at line 551 of file npc.cpp.
{
    std::vector<item> ret;
    if( item_group::group_is_defined( type->worn_override ) ) {
        ret = item_group::items_from( type->worn_override );
    } else {
        ret.push_back( get_clothing_item( type, "pants", male ) );
        ret.push_back( get_clothing_item( type, "shirt", male ) );
        ret.push_back( get_clothing_item( type, "underwear_top", male ) );
        ret.push_back( get_clothing_item( type, "underwear_bottom", male ) );
        ret.push_back( get_clothing_item( type, "underwear_feet", male ) );
        ret.push_back( get_clothing_item( type, "shoes", male ) );
        ret.push_back( random_item_from( type, "gloves" ) );
        ret.push_back( random_item_from( type, "coat" ) );
        ret.push_back( random_item_from( type, "vest" ) );
        ret.push_back( random_item_from( type, "masks" ) );
        // Why is the alternative group not named "npc_glasses" but "npc_eyes"?
        ret.push_back( random_item_from( type, "glasses", item_group_id( "npc_eyes" ) ) );
        ret.push_back( random_item_from( type, "hat" ) );
        ret.push_back( random_item_from( type, "scarf" ) );
        ret.push_back( random_item_from( type, "storage" ) );
        ret.push_back( random_item_from( type, "holster" ) );
        ret.push_back( random_item_from( type, "belt" ) );
        ret.push_back( random_item_from( type, "wrist" ) );
        ret.push_back( random_item_from( type, "extra" ) );
    }
    for( item &it : who.worn ) {
        it.on_takeoff( who );
    }
    who.worn.clear();
    for( item &it : ret ) {
        if( it.has_flag( "VARSIZE" ) ) {
            it.set_flag( "FIT" );
        }
        if( who.can_wear( it ).success() ) {
            it.on_wear( who );
            who.worn.push_back( it );
            it.set_owner( who );
        }
    }
}
References Character::can_wear(), get_clothing_item(), item_group::group_is_defined(), item::has_flag(), item_group::items_from(), male, item::on_takeoff(), item::on_wear(), random_item_from(), cata::hash64_detail::ret, item::set_flag(), item::set_owner(), type, and Character::worn.
Referenced by npc::randomize().
starting_inv()
void starting_inv (npc & who, const npc_class_id & type)
Definition at line 594 of file npc.cpp.
{
    std::list<item> res;
    who.inv.clear();
    if( item_group::group_is_defined( type->carry_override ) ) {
        who.inv += item_group::items_from( type->carry_override );
        return;
    }
    res.emplace_back( "lighter" );
    // If wielding a gun, get some additional ammo for it
    if( who.weapon.is_gun() ) {
        item ammo( who.weapon.ammo_default() );
        ammo = ammo.in_its_container();
        if( ammo.made_of( LIQUID ) ) {
            item container( "bottle_plastic" );
            container.put_in( ammo );
            ammo = container;
        }
        // TODO: Move to npc_class
        // NC_COWBOY and NC_BOUNTY_HUNTER get 5-15 whilst all others get 3-6
        int qty = 1 + ( type == NC_COWBOY ||
                        type == NC_BOUNTY_HUNTER );
        qty = rng( qty, qty * 2 );
        while( qty-- != 0 && who.can_pick_volume( ammo ) ) {
            // TODO: give NPC a default magazine instead
            res.push_back( ammo );
        }
    }
    if( type == NC_ARSONIST ) {
        res.emplace_back( "molotov" );
    }
    int qty = ( type == NC_EVAC_SHOPKEEP ||
                type == NC_TRADER ) ? 5 : 2;
    qty = rng( qty, qty * 3 );
    while( qty-- != 0 ) {
        item tmp = random_item_from( type, "misc" ).in_its_container();
        if( !tmp.is_null() ) {
            if( !one_in( 3 ) && tmp.has_flag( "VARSIZE" ) ) {
                tmp.set_flag( "FIT" );
            }
            if( who.can_pick_volume( tmp ) ) {
                res.push_back( tmp );
            }
        }
    }
    res.erase( std::remove_if( res.begin(), res.end(), [&]( const item & e ) {
        return e.has_flag( "TRADER_AVOID" );
    } ), res.end() );
    for( auto &it : res ) {
        it.set_owner( who );
    }
    who.inv += res;
}
References item::ammo_default(), Character::can_pick_volume(), inventory::clear(), item_group::group_is_defined(), item::has_flag(), item::in_its_container(), Character::inv, item::is_gun(), item::is_null(), item_group::items_from(), LIQUID, item::made_of(), NC_ARSONIST, NC_BOUNTY_HUNTER, NC_COWBOY, NC_EVAC_SHOPKEEP, NC_TRADER, one_in(), item::put_in(), random_item_from(), rng(), item::set_flag(), item::set_owner(), type, and Character::weapon.
Referenced by npc::randomize().
Variable Documentation
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
Referenced by npc::start_read().
bio_eye_optic
const bionic_id bio_eye_optic("bio_eye_optic") ("bio_eye_optic") static
Referenced by npc::can_read().
bio_memory
const bionic_id bio_memory("bio_memory") ("bio_memory") static
Referenced by npc::finish_read().
effect_ai_waiting
const efftype_id effect_ai_waiting("ai_waiting") ("ai_waiting") static
Referenced by npc::npc_dismount().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by npc::on_load().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by npc::can_read().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by npc::form_opinion().
effect_infection
const efftype_id effect_infection("infection") ("infection") static
Referenced by npc::is_stationary().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by npc::wear_if_wanted().
effect_npc_flee_player
const efftype_id effect_npc_flee_player("npc_flee_player") ("npc_flee_player") static
Referenced by npc::set_attitude().
effect_npc_suspend
const efftype_id effect_npc_suspend("npc_suspend") ("npc_suspend") static
Referenced by npc::reboot().
effect_pkill1
const efftype_id effect_pkill1("pkill1") ("pkill1") static
Referenced by npc::took_painkiller().
effect_pkill2
const efftype_id effect_pkill2("pkill2") ("pkill2") static
Referenced by npc::took_painkiller().
effect_pkill3
const efftype_id effect_pkill3("pkill3") ("pkill3") static
Referenced by npc::took_painkiller().
effect_pkill_l
const efftype_id effect_pkill_l("pkill_l") ("pkill_l") static
Referenced by npc::took_painkiller().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by npc::die(), and npc::npc_dismount().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by npc::npc_dismount(), and npc::on_load().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by npc::decide_needs().
npc_templates
std::map<string_id<npc_template>, npc_template> npc_templates static
Definition at line 214 of file npc.cpp.
Referenced by npc_template::check_consistency(), string_id< T >::is_valid(), npc_template::load(), npc::load_npc_template(), string_id< T >::obj(), and npc_template::reset().
skill_archery
const skill_id skill_archery("archery") ("archery") static
Referenced by item::is_gunmod_compatible(), and npc::starting_weapon().
skill_barter
const skill_id skill_barter("barter") ("barter") static
Referenced by npc::randomize().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by npc::starting_weapon().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by npc::starting_weapon().
skill_pistol
const skill_id skill_pistol("pistol") ("pistol") static
Referenced by npc::starting_weapon().
skill_rifle
const skill_id skill_rifle("rifle") ("rifle") static
Referenced by npc::starting_weapon().
skill_shotgun
const skill_id skill_shotgun("shotgun") ("shotgun") static
Referenced by npc::starting_weapon().
skill_smg
const skill_id skill_smg("smg") ("smg") static
Referenced by npc::starting_weapon().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by npc::starting_weapon().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by npc::starting_weapon().
trait_BEE
const trait_id trait_BEE("BEE") ("BEE") static
Referenced by npc::get_monster_faction().
trait_CANNIBAL
const trait_id trait_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by npc::die().
trait_DEBUG_MIND_CONTROL
const trait_id trait_DEBUG_MIND_CONTROL("DEBUG_MIND_CONTROL") ("DEBUG_MIND_CONTROL") static
Referenced by npc::will_accept_from_player().
trait_HALLUCINATION
const trait_id trait_HALLUCINATION("HALLUCINATION") ("HALLUCINATION") static
Referenced by npc::on_load().
trait_HYPEROPIC
const trait_id trait_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by npc::can_read().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by npc::can_read().
trait_MUTE
const trait_id trait_MUTE("MUTE") ("MUTE") static
Referenced by npc::say().
trait_PROF_DICEMASTER
const trait_id trait_PROF_DICEMASTER("PROF_DICEMASTER") ("PROF_DICEMASTER") static
Referenced by npc::time_to_read().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by npc::die().
trait_SAPIOVORE
const trait_id trait_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by npc::die(), and npc::form_opinion().
trait_SCHIZOPHRENIC
const trait_id trait_SCHIZOPHRENIC("SCHIZOPHRENIC") ("SCHIZOPHRENIC") static
Referenced by npc::finish_read().
trait_TERRIFYING
const trait_id trait_TERRIFYING("TERRIFYING") ("TERRIFYING") static
Referenced by npc::form_opinion().