Cataclysm BN: src/npc_class.cpp File Reference
npc_class.cpp File Reference
#include "npc_class.h"
#include <cstddef>
#include <list>
#include <algorithm>
#include <array>
#include <iterator>
#include <set>
#include <utility>
#include "debug.h"
#include "generic_factory.h"
#include "item_group.h"
#include "mutation.h"
#include "rng.h"
#include "skill.h"
#include "trait_group.h"
#include "json.h"
Functions
template<typename T >
void apply_all_to_unassigned (T &skills)
static distribution load_distribution (const JsonObject &jo)
static distribution load_distribution (const JsonObject &jo, const std::string &name)
Variables
static const std::array< npc_class_id, 19 > legacy_ids
npc_class_id NC_NONE ("NC_NONE")
npc_class_id NC_EVAC_SHOPKEEP ("NC_EVAC_SHOPKEEP")
npc_class_id NC_SHOPKEEP ("NC_SHOPKEEP")
npc_class_id NC_HACKER ("NC_HACKER")
npc_class_id NC_CYBORG ("NC_CYBORG")
npc_class_id NC_DOCTOR ("NC_DOCTOR")
npc_class_id NC_TRADER ("NC_TRADER")
npc_class_id NC_NINJA ("NC_NINJA")
npc_class_id NC_COWBOY ("NC_COWBOY")
npc_class_id NC_SCIENTIST ("NC_SCIENTIST")
npc_class_id NC_BOUNTY_HUNTER ("NC_BOUNTY_HUNTER")
npc_class_id NC_THUG ("NC_THUG")
npc_class_id NC_SCAVENGER ("NC_SCAVENGER")
npc_class_id NC_ARSONIST ("NC_ARSONIST")
npc_class_id NC_HUNTER ("NC_HUNTER")
npc_class_id NC_SOLDIER ("NC_SOLDIER")
npc_class_id NC_BARTENDER ("NC_BARTENDER")
npc_class_id NC_JUNK_SHOPKEEP ("NC_JUNK_SHOPKEEP")
npc_class_id NC_HALLU ("NC_HALLU")
generic_factory< npc_class > npc_class_factory ("npc_class")
Function Documentation
apply_all_to_unassigned()
template<typename T > void apply_all_to_unassigned (T & skills)
Definition at line 95 of file npc_class.cpp.
{
    auto iter = std::find_if( skills.begin(), skills.end(),
    []( decltype( *begin( skills ) ) &pr ) {
        return pr.first.str() == "ALL";
    } );
    if( iter != skills.end() ) {
        distribution dis = iter->second;
        skills.erase( iter );
        for( const auto &sk : Skill::skills ) {
            if( skills.count( sk.ident() ) == 0 ) {
                skills[ sk.ident() ] = dis;
            }
        }
    }
}
References Skill::skills.
Referenced by npc_class::finalize_all().
load_distribution() [1/2]
static distribution load_distribution (const JsonObject & jo) static
Definition at line 167 of file npc_class.cpp.
{
    if( jo.has_float( "constant" ) ) {
        return distribution::constant( jo.get_float( "constant" ) );
    }
    if( jo.has_float( "one_in" ) ) {
        return distribution::one_in( jo.get_float( "one_in" ) );
    }
    if( jo.has_array( "dice" ) ) {
        JsonArray jarr = jo.get_array( "dice" );
        return distribution::dice_roll( jarr.get_int( 0 ), jarr.get_int( 1 ) );
    }
    if( jo.has_array( "rng" ) ) {
        JsonArray jarr = jo.get_array( "rng" );
        return distribution::rng_roll( jarr.get_int( 0 ), jarr.get_int( 1 ) );
    }
    if( jo.has_array( "sum" ) ) {
        JsonArray jarr = jo.get_array( "sum" );
        JsonObject obj = jarr.next_object();
        distribution ret = load_distribution( obj );
        while( jarr.has_more() ) {
            obj = jarr.next_object();
            ret = ret + load_distribution( obj );
        }
        return ret;
    }
    if( jo.has_array( "mul" ) ) {
        JsonArray jarr = jo.get_array( "mul" );
        JsonObject obj = jarr.next_object();
        distribution ret = load_distribution( obj );
        while( jarr.has_more() ) {
            obj = jarr.next_object();
            ret = ret * load_distribution( obj );
        }
        return ret;
    }
    jo.throw_error( "Invalid distribution" );
    return distribution();
}
References distribution::constant(), distribution::dice_roll(), JsonObject::get_array(), JsonObject::get_float(), JsonArray::get_int(), JsonObject::has_array(), JsonObject::has_float(), JsonArray::has_more(), load_distribution(), JsonArray::next_object(), int_id< T >::obj(), distribution::one_in(), cata::hash64_detail::ret, distribution::rng_roll(), and JsonObject::throw_error().
Referenced by npc_class::load(), and load_distribution().
load_distribution() [2/2]
static distribution load_distribution (const JsonObject & jo, const std::string & name) static
Definition at line 215 of file npc_class.cpp.
{
    if( !jo.has_member( name ) ) {
        return distribution();
    }
    if( jo.has_float( name ) ) {
        return distribution::constant( jo.get_float( name ) );
    }
    if( jo.has_object( name ) ) {
        JsonObject obj = jo.get_object( name );
        return load_distribution( obj );
    }
    jo.throw_error( "Invalid distribution type", name );
    return distribution();
}
References distribution::constant(), JsonObject::get_float(), JsonObject::get_object(), JsonObject::has_float(), JsonObject::has_member(), JsonObject::has_object(), load_distribution(), om_direction::name(), int_id< T >::obj(), and JsonObject::throw_error().
Variable Documentation
legacy_ids
const std::array<npc_class_id, 19> legacy_ids static
Initial value:
= {{
        npc_class_id( "NC_NONE" ),
        npc_class_id( "NC_EVAC_SHOPKEEP" ),
        npc_class_id( "NC_SHOPKEEP" ),
        npc_class_id( "NC_HACKER" ),
        npc_class_id( "NC_CYBORG" ),
        npc_class_id( "NC_DOCTOR" ),
        npc_class_id( "NC_TRADER" ),
        npc_class_id( "NC_NINJA" ),
        npc_class_id( "NC_COWBOY" ),
        npc_class_id( "NC_SCIENTIST" ),
        npc_class_id( "NC_BOUNTY_HUNTER" ),
        npc_class_id( "NC_THUG" ),
        npc_class_id( "NC_SCAVENGER" ),
        npc_class_id( "NC_ARSONIST" ),
        npc_class_id( "NC_HUNTER" ),
        npc_class_id( "NC_SOLDIER" ),
        npc_class_id( "NC_BARTENDER" ),
        npc_class_id( "NC_JUNK_SHOPKEEP" ),
        npc_class_id( "NC_HALLU" )
    }
}
Definition at line 20 of file npc_class.cpp.
Referenced by npc_class::check_consistency(), and npc_class::from_legacy_int().
NC_ARSONIST
npc_class_id NC_ARSONIST("NC_ARSONIST") ("NC_ARSONIST")
Referenced by npc::randomize(), and starting_inv().
NC_BARTENDER
npc_class_id NC_BARTENDER("NC_BARTENDER") ("NC_BARTENDER")
Referenced by npc::randomize().
NC_BOUNTY_HUNTER
npc_class_id NC_BOUNTY_HUNTER("NC_BOUNTY_HUNTER") ("NC_BOUNTY_HUNTER")
Referenced by npc::randomize(), and starting_inv().
NC_COWBOY
npc_class_id NC_COWBOY("NC_COWBOY") ("NC_COWBOY")
Referenced by npc::randomize(), and starting_inv().
NC_CYBORG
npc_class_id NC_CYBORG("NC_CYBORG") ("NC_CYBORG")
NC_DOCTOR
npc_class_id NC_DOCTOR("NC_DOCTOR") ("NC_DOCTOR")
Referenced by game::create_starting_npcs(), mission_start::place_npc_software(), and npc::randomize().
NC_EVAC_SHOPKEEP
npc_class_id NC_EVAC_SHOPKEEP("NC_EVAC_SHOPKEEP") ("NC_EVAC_SHOPKEEP")
Referenced by npc::randomize(), and starting_inv().
NC_HACKER
npc_class_id NC_HACKER("NC_HACKER") ("NC_HACKER")
Referenced by mission_start::place_npc_software(), and npc::randomize().
NC_HALLU
npc_class_id NC_HALLU("NC_HALLU") ("NC_HALLU")
Referenced by game::spawn_hallucination().
NC_HUNTER
npc_class_id NC_HUNTER("NC_HUNTER") ("NC_HUNTER")
NC_JUNK_SHOPKEEP
npc_class_id NC_JUNK_SHOPKEEP("NC_JUNK_SHOPKEEP") ("NC_JUNK_SHOPKEEP")
Referenced by npc::randomize().
NC_NINJA
npc_class_id NC_NINJA("NC_NINJA") ("NC_NINJA")
Referenced by npc::randomize().
NC_NONE
npc_class_id NC_NONE("NC_NONE") ("NC_NONE")
Referenced by game::create_starting_npcs(), mission::mission(), and npc_class::random_common().
NC_SCAVENGER
npc_class_id NC_SCAVENGER("NC_SCAVENGER") ("NC_SCAVENGER")
Referenced by npc::randomize().
NC_SCIENTIST
npc_class_id NC_SCIENTIST("NC_SCIENTIST") ("NC_SCIENTIST")
Referenced by mission_start::place_npc_software(), and npc::randomize().
NC_SHOPKEEP
npc_class_id NC_SHOPKEEP("NC_SHOPKEEP") ("NC_SHOPKEEP")
NC_SOLDIER
npc_class_id NC_SOLDIER("NC_SOLDIER") ("NC_SOLDIER")
Referenced by npc::randomize().
NC_THUG
npc_class_id NC_THUG("NC_THUG") ("NC_THUG")
Referenced by npc::randomize().
NC_TRADER
npc_class_id NC_TRADER("NC_TRADER") ("NC_TRADER")
Referenced by npc::randomize(), and starting_inv().
npc_class_factory
generic_factory< npc_class > npc_class_factory("npc_class") ("npc_class")
Referenced by npc_class::check_consistency(), npc_class::finalize_all(), npc_class::get_all(), npc_class::load_npc_class(), npc_class::random_common(), and npc_class::reset_npc_classes().