Cataclysm BN: src/npctalk.h File Reference
npctalk.h File Reference
#include "type_id.h"
Namespaces
namespace talk_function
Macros
#define CATA_SRC_NPCTALK_H
Functions
void talk_function::nothing (npc &)
void talk_function::assign_mission (npc &)
void talk_function::mission_success (npc &)
void talk_function::mission_failure (npc &)
void talk_function::clear_mission (npc &)
void talk_function::mission_reward (npc &)
void talk_function::mission_favor (npc &)
void talk_function::give_equipment (npc &)
void talk_function::give_aid (npc &)
void talk_function::give_all_aid (npc &)
void talk_function::buy_horse (npc &)
void talk_function::buy_cow (npc &)
void talk_function::buy_chicken (npc &)
void talk_function::bionic_install (npc &)
void talk_function::bionic_remove (npc &)
void talk_function::dismount (npc &)
void talk_function::find_mount (npc &)
void talk_function::barber_beard (npc &)
void talk_function::barber_hair (npc &)
void talk_function::buy_haircut (npc &)
void talk_function::buy_shave (npc &)
void talk_function::morale_chat (npc &)
void talk_function::morale_chat_activity (npc &)
void talk_function::buy_10_logs (npc &)
void talk_function::buy_100_logs (npc &)
void talk_function::start_trade (npc &)
void talk_function::sort_loot (npc &)
void talk_function::do_construction (npc &)
void talk_function::do_mining (npc &)
void talk_function::do_read (npc &)
void talk_function::do_chop_plank (npc &)
void talk_function::do_vehicle_deconstruct (npc &)
void talk_function::do_vehicle_repair (npc &)
void talk_function::do_chop_trees (npc &)
void talk_function::do_fishing (npc &)
void talk_function::do_farming (npc &)
void talk_function::do_butcher (npc &)
void talk_function::revert_activity (npc &)
void talk_function::goto_location (npc &)
void talk_function::assign_base (npc &)
void talk_function::assign_guard (npc &)
void talk_function::assign_camp (npc &)
void talk_function::abandon_camp (npc &)
void talk_function::stop_guard (npc &)
void talk_function::end_conversation (npc &)
void talk_function::insult_combat (npc &)
void talk_function::reveal_stats (npc &)
void talk_function::follow (npc &)
void talk_function::follow_only (npc &)
void talk_function::deny_follow (npc &)
void talk_function::deny_lead (npc &)
void talk_function::deny_equipment (npc &)
void talk_function::deny_train (npc &)
void talk_function::deny_personal_info (npc &)
void talk_function::hostile (npc &)
void talk_function::flee (npc &)
void talk_function::leave (npc &)
void talk_function::stop_following (npc &)
void talk_function::stranger_neutral (npc &)
void talk_function::start_mugging (npc &)
void talk_function::player_leaving (npc &)
void talk_function::remove_stolen_status (npc &)
void talk_function::drop_weapon (npc &)
void talk_function::player_weapon_away (npc &)
void talk_function::player_weapon_drop (npc &)
void talk_function::drop_stolen_item (npc &)
void talk_function::lead_to_safety (npc &)
void talk_function::start_training (npc &)
void talk_function::wake_up (npc &)
void talk_function::copy_npc_rules (npc &p)
void talk_function::set_npc_pickup (npc &p)
void talk_function::npc_die (npc &p)
void talk_function::npc_thankful (npc &p)
void talk_function::clear_overrides (npc &p)
time_duration calc_skill_training_time (const npc &p, const skill_id &skill)
Time (in turns) and cost (in cent) for training:
int calc_skill_training_cost (const npc &p, const skill_id &skill)
time_duration calc_ma_style_training_time (const npc &, const matype_id &)
int calc_ma_style_training_cost (const npc &p, const matype_id &)
Macro Definition Documentation
CATA_SRC_NPCTALK_H
#define CATA_SRC_NPCTALK_H
Definition at line 3 of file npctalk.h.
Function Documentation
calc_ma_style_training_cost()
int calc_ma_style_training_cost (const npc & p, const matype_id &)
Definition at line 162 of file npctalk.cpp.
{
    if( p.is_player_ally() ) {
        return 0;
    }
    return 800;
}
References npc::is_player_ally().
Referenced by dialogue::gen_responses(), and talk_function::start_training().
calc_ma_style_training_time()
time_duration calc_ma_style_training_time (const npc & , const matype_id &)
Definition at line 157 of file npctalk.cpp.
{
    return 30_minutes;
}
Referenced by talk_function::start_training().
calc_skill_training_cost()
int calc_skill_training_cost (const npc & p, const skill_id & skill)
Definition at line 145 of file npctalk.cpp.
{
    if( p.is_player_ally() ) {
        return 0;
    }
    avatar &you = get_avatar();
    return 1000 * ( 1 + you.get_skill_level( skill ) ) * ( 1 + you.get_skill_level( skill ) );
}
References get_avatar(), Character::get_skill_level(), and npc::is_player_ally().
Referenced by dialogue::gen_responses(), and talk_function::start_training().
calc_skill_training_time()
time_duration calc_skill_training_time (const npc & p, const skill_id & skill)
Time (in turns) and cost (in cent) for training:
Definition at line 139 of file npctalk.cpp.
{
    return 1_minutes + 30_seconds * get_avatar().get_skill_level( skill ) -
           1_seconds * p.get_skill_level( skill );
}
References get_avatar(), and Character::get_skill_level().
Referenced by talk_function::start_training().