Cataclysm BN: src/npctrade.cpp File Reference
npctrade.cpp File Reference
#include "npctrade.h"
#include <algorithm>
#include <cstdlib>
#include <list>
#include <memory>
#include <ostream>
#include <set>
#include <string>
#include <vector>
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "faction.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "item.h"
#include "item_category.h"
#include "item_contents.h"
#include "map_selector.h"
#include "npc.h"
#include "optional.h"
#include "output.h"
#include "player.h"
#include "point.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "vehicle_selector.h"
#include "visitable.h"
Functions
template<typename T , typename Callback >
void buy_helper (T &src, Callback cb)
Variables
static const skill_id skill_barter ("barter")
Function Documentation
buy_helper()
template<typename T , typename Callback > void buy_helper (T & src, Callback cb)
Definition at line 139 of file npctrade.cpp.
{
    src.visit_items( [&src, &cb]( item * node ) {
        cb( std::move( item_location( src, node ) ), 1 );
        return VisitResponse::SKIP;
    } );
}
References avatar_action::move(), and SKIP.
Referenced by npc_trading::init_buying().
Variable Documentation
skill_barter
const skill_id skill_barter("barter") ("barter") static
Referenced by npc_trading::net_price_adjustment(), and npc_trading::trade().