Cataclysm BN: src/npctalk.cpp File Reference
npctalk.cpp File Reference
#include "dialogue.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <ostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include "activity_type.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_functions.h"
#include "character_id.h"
#include "clzones.h"
#include "color.h"
#include "condition.h"
#include "debug.h"
#include "enums.h"
#include "faction.h"
#include "faction_camp.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "help.h"
#include "input.h"
#include "item.h"
#include "item_category.h"
#include "item_contents.h"
#include "item_location.h"
#include "itype.h"
#include "json.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "mapgen_functions.h"
#include "martialarts.h"
#include "messages.h"
#include "mission.h"
#include "mission_companion.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "npc_class.h"
#include "npctalk.h"
#include "npctrade.h"
#include "output.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "effect.h"
Macros
#define OWED_VAL 1000
#define WRAP(value) { #value, TALK_TRIAL_##value }
#define WRAP(function) { #function, &talk_function::function }
Enumerations
enum npc_chat_menu {
NPC_CHAT_DONE , NPC_CHAT_TALK , NPC_CHAT_YELL , NPC_CHAT_SENTENCE ,
NPC_CHAT_GUARD , NPC_CHAT_FOLLOW , NPC_CHAT_AWAKE , NPC_CHAT_MOUNT ,
NPC_CHAT_DISMOUNT , NPC_CHAT_DANGER , NPC_CHAT_ORDERS , NPC_CHAT_NO_GUNS ,
NPC_CHAT_PULP , NPC_CHAT_FOLLOW_CLOSE , NPC_CHAT_MOVE_FREELY , NPC_CHAT_SLEEP ,
NPC_CHAT_FORBID_ENGAGE , NPC_CHAT_CLEAR_OVERRIDES , NPC_CHAT_ANIMAL_VEHICLE_FOLLOW , NPC_CHAT_ANIMAL_VEHICLE_STOP_FOLLOW ,
NPC_CHAT_COMMAND_MAGIC_VEHICLE_FOLLOW , NPC_CHAT_COMMAND_MAGIC_VEHICLE_STOP_FOLLOW
}
enum consumption_result { REFUSED = 0 , CONSUMED_SOME , CONSUMED_ALL }
Functions
int topic_category (const talk_topic &the_topic)
const talk_topic & special_talk (char ch)
std::string give_item_to (npc &p, bool allow_use)
time_duration calc_skill_training_time (const npc &p, const skill_id &skill)
Time (in turns) and cost (in cent) for training:
int calc_skill_training_cost (const npc &p, const skill_id &skill)
time_duration calc_ma_style_training_time (const npc &, const matype_id &)
int calc_ma_style_training_cost (const npc &p, const matype_id &)
static int npc_select_menu (const std::vector< npc * > &npc_list, const std::string &prompt, const bool everyone=true)
static void npc_batch_override_toggle (const std::vector< npc * > &npc_list, ally_rule rule, bool state)
static void npc_temp_orders_menu (const std::vector< npc * > &npc_list)
static void tell_veh_stop_following ()
static void assign_veh_to_follow ()
static void tell_magic_veh_to_follow ()
static void tell_magic_veh_stop_following ()
static int parse_mod (const dialogue &d, const std::string &attribute, const int factor)
void parse_tags (std::string &phrase, const Character &u, const Character &me, const itype_id &item_type)
static talk_topic load_inline_topic (const JsonObject &jo)
static std::string translate_gendered_line (const std::string &line, const std::vector< std::string > &relevant_genders, const dialogue &d)
void unload_talk_topics ()
void load_talk_topic (const JsonObject &jo)
static consumption_result try_consume (npc &p, item &it, std::string &reason)
Variables
static const activity_id ACT_AIM ("ACT_AIM")
static const activity_id ACT_SOCIALIZE ("ACT_SOCIALIZE")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_WAIT_NPC ("ACT_WAIT_NPC")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_npc_suspend ("npc_suspend")
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_under_op ("under_operation")
static const itype_id fuel_type_animal ("animal")
static const zone_type_id zone_type_npc_investigate_only ("NPC_INVESTIGATE_ONLY")
static const zone_type_id zone_type_npc_no_investigate ("NPC_NO_INVESTIGATE")
static const skill_id skill_speech ("speech")
static const bionic_id bio_armor_eyes ("bio_armor_eyes")
static const bionic_id bio_deformity ("bio_deformity")
static const bionic_id bio_face_mask ("bio_face_mask")
static const bionic_id bio_voice ("bio_voice")
static const trait_id trait_DEBUG_MIND_CONTROL ("DEBUG_MIND_CONTROL")
static const trait_id trait_PROF_FOODP ("PROF_FOODP")
static std::map< std::string, json_talk_topic > json_talk_topics
Macro Definition Documentation
OWED_VAL
#define OWED_VAL 1000
Definition at line 116 of file npctalk.cpp.
WRAP [1/2]
#define WRAP (function) { #function, &talk_function::function }
WRAP [2/2]
#define WRAP (value) { #value, TALK_TRIAL_##value }
Enumeration Type Documentation
consumption_result
enum consumption_result
Enumerator
REFUSED
CONSUMED_SOME
CONSUMED_ALL
Definition at line 3259 of file npctalk.cpp.
{
    REFUSED = 0,
    CONSUMED_SOME, // Consumption didn't fail, but don't delete the item
    CONSUMED_ALL   // Consumption succeeded, delete the item
};
npc_chat_menu
enum npc_chat_menu
Enumerator
NPC_CHAT_DONE
NPC_CHAT_TALK
NPC_CHAT_YELL
NPC_CHAT_SENTENCE
NPC_CHAT_GUARD
NPC_CHAT_FOLLOW
NPC_CHAT_AWAKE
NPC_CHAT_MOUNT
NPC_CHAT_DISMOUNT
NPC_CHAT_DANGER
NPC_CHAT_ORDERS
NPC_CHAT_NO_GUNS
NPC_CHAT_PULP
NPC_CHAT_FOLLOW_CLOSE
NPC_CHAT_MOVE_FREELY
NPC_CHAT_SLEEP
NPC_CHAT_FORBID_ENGAGE
NPC_CHAT_CLEAR_OVERRIDES
NPC_CHAT_ANIMAL_VEHICLE_FOLLOW
NPC_CHAT_ANIMAL_VEHICLE_STOP_FOLLOW
NPC_CHAT_COMMAND_MAGIC_VEHICLE_FOLLOW
NPC_CHAT_COMMAND_MAGIC_VEHICLE_STOP_FOLLOW
Definition at line 192 of file npctalk.cpp.
                   {
    NPC_CHAT_DONE,
    NPC_CHAT_TALK,
    NPC_CHAT_YELL,
    NPC_CHAT_SENTENCE,
    NPC_CHAT_GUARD,
    NPC_CHAT_FOLLOW,
    NPC_CHAT_AWAKE,
    NPC_CHAT_MOUNT,
    NPC_CHAT_DISMOUNT,
    NPC_CHAT_DANGER,
    NPC_CHAT_ORDERS,
    NPC_CHAT_NO_GUNS,
    NPC_CHAT_PULP,
    NPC_CHAT_FOLLOW_CLOSE,
    NPC_CHAT_MOVE_FREELY,
    NPC_CHAT_SLEEP,
    NPC_CHAT_FORBID_ENGAGE,
    NPC_CHAT_CLEAR_OVERRIDES,
    NPC_CHAT_ANIMAL_VEHICLE_FOLLOW,
    NPC_CHAT_ANIMAL_VEHICLE_STOP_FOLLOW,
    NPC_CHAT_COMMAND_MAGIC_VEHICLE_FOLLOW,
    NPC_CHAT_COMMAND_MAGIC_VEHICLE_STOP_FOLLOW
};
Function Documentation
assign_veh_to_follow()
static void assign_veh_to_follow () static
Definition at line 351 of file npctalk.cpp.
{
    for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
        vehicle *v = veh.v;
        if( v->has_engine_type( fuel_type_animal, false ) && v->is_owned_by( get_avatar() ) ) {
            v->activate_animal_follow();
        }
    }
}
References vehicle::activate_animal_follow(), fuel_type_animal, get_avatar(), get_map(), vehicle::has_engine_type(), and vehicle::is_owned_by().
Referenced by game::chat().
calc_ma_style_training_cost()
int calc_ma_style_training_cost (const npc & p, const matype_id &)
Definition at line 161 of file npctalk.cpp.
{
    if( p.is_player_ally() ) {
        return 0;
    }
    return 800;
}
References npc::is_player_ally().
Referenced by dialogue::gen_responses(), and talk_function::start_training().
calc_ma_style_training_time()
time_duration calc_ma_style_training_time (const npc & , const matype_id &)
Definition at line 156 of file npctalk.cpp.
{
    return 30_minutes;
}
Referenced by talk_function::start_training().
calc_skill_training_cost()
int calc_skill_training_cost (const npc & p, const skill_id & skill)
Definition at line 144 of file npctalk.cpp.
{
    if( p.is_player_ally() ) {
        return 0;
    }
    avatar &you = get_avatar();
    return 1000 * ( 1 + you.get_skill_level( skill ) ) * ( 1 + you.get_skill_level( skill ) );
}
References get_avatar(), Character::get_skill_level(), and npc::is_player_ally().
Referenced by dialogue::gen_responses(), and talk_function::start_training().
calc_skill_training_time()
time_duration calc_skill_training_time (const npc & p, const skill_id & skill)
Time (in turns) and cost (in cent) for training:
Definition at line 138 of file npctalk.cpp.
{
    return 1_minutes + 30_seconds * get_avatar().get_skill_level( skill ) -
           1_seconds * p.get_skill_level( skill );
}
References get_avatar(), and Character::get_skill_level().
Referenced by talk_function::start_training().
give_item_to()
std::string give_item_to (npc & p, bool allow_use)
Definition at line 3334 of file npctalk.cpp.
{
    if( p.is_hallucination() ) {
        return _( "No thanks, I'm good." );
    }
    avatar &you = get_avatar();
    item_location loc = game_menus::inv::titled_menu( you, _( "Offer what?" ),
                        _( "You have no items to offer." ) );
    if( !loc ) {
        return _( "Changed your mind?" );
    }
    item &given = *loc;
    if( ( &given == &you.weapon && given.has_flag( "NO_UNWIELD" ) ) || ( you.is_worn( given ) &&
            given.has_flag( "NO_TAKEOFF" ) ) ) {
        // Bionic weapon or shackles
        return _( "How?" );
    }
    if( given.is_dangerous() && !you.has_trait( trait_DEBUG_MIND_CONTROL ) ) {
        return _( "Are you <swear> insane!?" );
    }
    bool taken = false;
    std::string reason = _( "Nope." );
    int our_ammo = p.ammo_count_for( p.weapon );
    int new_ammo = p.ammo_count_for( given );
    const double new_weapon_value = p.weapon_value( given, new_ammo );
    const double cur_weapon_value = p.weapon_value( p.weapon, our_ammo );
    add_msg( m_debug, "NPC evaluates own %s (%d ammo): %0.1f",
             p.weapon.typeId().str(), our_ammo, cur_weapon_value );
    add_msg( m_debug, "NPC evaluates your %s (%d ammo): %0.1f",
             given.typeId().str(), new_ammo, new_weapon_value );
    if( allow_use ) {
        // Eating first, to avoid evaluating bread as a weapon
        const auto consume_res = try_consume( p, given, reason );
        if( consume_res != REFUSED ) {
            if( consume_res == CONSUMED_ALL ) {
                you.i_rem( &given );
            }
            you.moves -= 100;
            if( given.is_container() ) {
                given.on_contents_changed();
            }
        }// wield it if its a weapon
        else if( new_weapon_value > cur_weapon_value ) {
            p.wield( given );
            reason = _( "Thanks, I'll wield that now." );
            taken = true;
        }// HACK: is_gun here is a hack to prevent NPCs wearing guns if they don't want to use them
        else if( !given.is_gun() && given.is_armor() ) {
            //if it is impossible to wear return why
            ret_val<bool> can_wear = p.can_wear( given, true );
            if( !can_wear.success() ) {
                reason = can_wear.str();
            } else {
                //if we can wear it with equip changes prompt first
                can_wear = p.can_wear( given );
                if( ( can_wear.success() ||
                      query_yn( can_wear.str() + _( " Should I take something off?" ) ) )
                    && p.wear_if_wanted( given, reason ) ) {
                    taken = true;
                } else {
                    reason = can_wear.str();
                }
            }
        } else {
            reason += string_format(
                          _( "My current weapon is better than this.\n(new weapon value: %.1f vs %.1f)." ), new_weapon_value,
                          cur_weapon_value );
        }
    } else {//allow_use is false so try to carry instead
        if( p.can_pick_volume( given ) && p.can_pick_weight( given ) ) {
            reason = _( "Thanks, I'll carry that now." );
            taken = true;
            p.i_add( given );
        } else {
            if( !p.can_pick_volume( given ) ) {
                const units::volume free_space = p.volume_capacity() - p.volume_carried();
                reason += "\n" + std::string( _( "I have no space to store it." ) ) + "\n";
                if( free_space > 0_ml ) {
                    reason += string_format( _( "I can only store %s %s more." ),
                                             format_volume( free_space ), volume_units_long() );
                } else {
                    reason += _( "or to store anything else for that matter." );
                }
            }
            if( !p.can_pick_weight( given ) ) {
                reason += std::string( "\n" ) + _( "It is too heavy for me to carry." );
            }
        }
    }
    if( taken ) {
        you.i_rem( &given );
        you.moves -= 100;
        p.has_new_items = true;
    }
    return reason;
}
References _, add_msg(), Character::ammo_count_for(), Character::can_pick_volume(), Character::can_pick_weight(), Character::can_wear(), CONSUMED_ALL, format_volume(), get_avatar(), item::has_flag(), npc::has_new_items, Character::has_trait(), Character::i_add(), Character::i_rem(), item::is_armor(), item::is_container(), item::is_dangerous(), item::is_gun(), npc::is_hallucination(), Character::is_worn(), m_debug, Creature::moves, item::on_contents_changed(), query_yn(), REFUSED, ret_val< T >::str(), string_id< T >::str(), string_format(), ret_val< T >::success(), game_menus::inv::titled_menu(), trait_DEBUG_MIND_CONTROL, try_consume(), item::typeId(), Character::volume_capacity(), Character::volume_carried(), volume_units_long(), Character::weapon, player::weapon_value(), npc::wear_if_wanted(), and npc::wield().
Referenced by talk_effect_fun_t::set_npc_gets_item().
load_inline_topic()
static talk_topic load_inline_topic (const JsonObject & jo) static
Definition at line 1886 of file npctalk.cpp.
{
    const std::string id = jo.get_string( "id" );
    json_talk_topics[id].load( jo );
    return talk_topic( id );
}
References JsonObject::get_string(), int_id< T >::id(), and json_talk_topics.
Referenced by talk_effect_t::talk_effect_t(), and talk_response::talk_response().
load_talk_topic()
void load_talk_topic (const JsonObject & jo)
Definition at line 3217 of file npctalk.cpp.
{
    if( jo.has_array( "id" ) ) {
        for( auto &id : jo.get_string_array( "id" ) ) {
            json_talk_topics[id].load( jo );
        }
    } else {
        const std::string id = jo.get_string( "id" );
        json_talk_topics[id].load( jo );
    }
}
References JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::has_array(), int_id< T >::id(), and json_talk_topics.
Referenced by DynamicDataLoader::initialize().
npc_batch_override_toggle()
static void npc_batch_override_toggle (const std::vector< npc * > & npc_list, ally_rule rule, bool state) static
Definition at line 244 of file npctalk.cpp.
{
    for( npc *p : npc_list ) {
        p->rules.toggle_specific_override_state( rule, state );
    }
}
Referenced by npc_temp_orders_menu().
npc_select_menu()
static int npc_select_menu (const std::vector< npc * > & npc_list, const std::string & prompt, const bool everyone = true) static
Definition at line 220 of file npctalk.cpp.
{
    if( npc_list.empty() ) {
        return -1;
    }
    const int npc_count = npc_list.size();
    if( npc_count == 1 ) {
        return 0;
    } else {
        uilist nmenu;
        nmenu.text = prompt;
        for( auto &elem : npc_list ) {
            nmenu.addentry( -1, true, MENU_AUTOASSIGN, ( elem )->name );
        }
        if( npc_count > 1 && everyone ) {
            nmenu.addentry( -1, true, MENU_AUTOASSIGN, _( "Everyone" ) );
        }
        nmenu.query();
        return nmenu.ret;
    }
}
References _, uilist::addentry(), MENU_AUTOASSIGN, om_direction::name(), pickup::prompt, uilist::query(), uilist::ret, and uilist::text.
Referenced by game::chat().
npc_temp_orders_menu()
static void npc_temp_orders_menu (const std::vector< npc * > & npc_list) static
Definition at line 252 of file npctalk.cpp.
{
    if( npc_list.empty() ) {
        return;
    }
    npc *guy = npc_list.front();
    bool done = false;
    uilist nmenu;
    while( !done ) {
        int override_count = 0;
        std::string output_string = string_format( _( "%s currently has these temporary orders:" ),
                                    guy->name );
        for( const auto &rule : ally_rule_strs ) {
            if( guy->rules.has_override_enable( rule.second.rule ) ) {
                override_count++;
                output_string += "\n  ";
                output_string += ( guy->rules.has_override( rule.second.rule ) ? rule.second.rule_true_text :
                                   rule.second.rule_false_text );
            }
        }
        if( override_count == 0 ) {
            output_string += std::string( "\n  " ) + _( "None." ) + "\n";
        }
        if( npc_list.size() > 1 ) {
            output_string += std::string( "\n" ) +
                             _( "Other followers might have different temporary orders." );
        }
        nmenu.reset();
        nmenu.text = _( "Issue what temporary order?" );
        nmenu.desc_enabled = true;
        parse_tags( output_string, get_avatar(), *guy );
        nmenu.footer_text = output_string;
        nmenu.addentry( NPC_CHAT_DONE, true, 'd', _( "Done issuing orders" ) );
        nmenu.addentry( NPC_CHAT_FORBID_ENGAGE, true, 'f',
                        guy->rules.has_override_enable( ally_rule::forbid_engage ) ?
                        _( "Go back to your usual engagement habits" ) : _( "Don't engage hostiles for the time being" ) );
        nmenu.addentry( NPC_CHAT_NO_GUNS, true, 'g', guy->rules.has_override_enable( ally_rule::use_guns ) ?
                        _( "Use whatever weapon you normally would" ) : _( "Don't use ranged weapons for a while" ) );
        nmenu.addentry( NPC_CHAT_PULP, true, 'p', guy->rules.has_override_enable( ally_rule::allow_pulp ) ?
                        _( "Pulp zombies if you like" ) : _( "Hold off on pulping zombies for a while" ) );
        nmenu.addentry( NPC_CHAT_FOLLOW_CLOSE, true, 'c',
                        guy->rules.has_override_enable( ally_rule::follow_close ) &&
                        guy->rules.has_override( ally_rule::follow_close ) ?
                        _( "Go back to keeping your usual distance" ) : _( "Stick close to me for now" ) );
        nmenu.addentry( NPC_CHAT_MOVE_FREELY, true, 'm',
                        guy->rules.has_override_enable( ally_rule::follow_close ) &&
                        !guy->rules.has_override( ally_rule::follow_close ) ?
                        _( "Go back to keeping your usual distance" ) : _( "Move farther from me if you need to" ) );
        nmenu.addentry( NPC_CHAT_SLEEP, true, 's',
                        guy->rules.has_override_enable( ally_rule::allow_sleep ) ?
                        _( "Go back to your usual sleeping habits" ) : _( "Take a nap if you need it" ) );
        nmenu.addentry( NPC_CHAT_CLEAR_OVERRIDES, true, 'o', _( "Let's go back to your usual behaviors" ) );
        nmenu.query();
        switch( nmenu.ret ) {
            case NPC_CHAT_FORBID_ENGAGE:
                npc_batch_override_toggle( npc_list, ally_rule::forbid_engage, true );
                break;
            case NPC_CHAT_NO_GUNS:
                npc_batch_override_toggle( npc_list, ally_rule::use_guns, false );
                break;
            case NPC_CHAT_PULP:
                npc_batch_override_toggle( npc_list, ally_rule::allow_pulp, false );
                break;
            case NPC_CHAT_FOLLOW_CLOSE:
                npc_batch_override_toggle( npc_list, ally_rule::follow_close, true );
                break;
            case NPC_CHAT_MOVE_FREELY:
                npc_batch_override_toggle( npc_list, ally_rule::follow_close, false );
                break;
            case NPC_CHAT_SLEEP:
                npc_batch_override_toggle( npc_list, ally_rule::allow_sleep, true );
                break;
            case NPC_CHAT_CLEAR_OVERRIDES:
                for( npc *p : npc_list ) {
                    p->rules.clear_overrides();
                }
                break;
            default:
                done = true;
                break;
        }
    }
}
References _, uilist::addentry(), allow_pulp, allow_sleep, ally_rule_strs, uilist::desc_enabled, detail::digits::done, follow_close, uilist::footer_text, forbid_engage, get_avatar(), npc_follower_rules::has_override(), npc_follower_rules::has_override_enable(), Character::name, npc_batch_override_toggle(), NPC_CHAT_CLEAR_OVERRIDES, NPC_CHAT_DONE, NPC_CHAT_FOLLOW_CLOSE, NPC_CHAT_FORBID_ENGAGE, NPC_CHAT_MOVE_FREELY, NPC_CHAT_NO_GUNS, NPC_CHAT_PULP, NPC_CHAT_SLEEP, parse_tags(), uilist::query(), uilist::reset(), uilist::ret, npc::rules, string_format(), uilist::text, and use_guns.
Referenced by game::chat().
parse_mod()
static int parse_mod (const dialogue & d, const std::string & attribute, const int factor) static
Definition at line 1371 of file npctalk.cpp.
{
    player &u = *d.alpha;
    npc &p = *d.beta;
    int modifier = 0;
    if( attribute == "ANGER" ) {
        modifier = p.op_of_u.anger;
    } else if( attribute == "FEAR" ) {
        modifier = p.op_of_u.fear;
    } else if( attribute == "TRUST" ) {
        modifier = p.op_of_u.trust;
    } else if( attribute == "VALUE" ) {
        modifier = p.op_of_u.value;
    } else if( attribute == "POS_FEAR" ) {
        modifier = std::max( 0, p.op_of_u.fear );
    } else if( attribute == "AGGRESSION" ) {
        modifier = p.personality.aggression;
    } else if( attribute == "ALTRUISM" ) {
        modifier = p.personality.altruism;
    } else if( attribute == "BRAVERY" ) {
        modifier = p.personality.bravery;
    } else if( attribute == "COLLECTOR" ) {
        modifier = p.personality.collector;
    } else if( attribute == "MISSIONS" ) {
        modifier = p.assigned_missions_value() / OWED_VAL;
    } else if( attribute == "U_INTIMIDATE" ) {
        modifier = u.intimidation();
    } else if( attribute == "NPC_INTIMIDATE" ) {
        modifier = p.intimidation();
    }
    modifier *= factor;
    return modifier;
}
References npc_personality::aggression, dialogue::alpha, npc_personality::altruism, npc_opinion::anger, npc::assigned_missions_value(), dialogue::beta, npc_personality::bravery, npc_personality::collector, npc_opinion::fear, player::intimidation(), npc::op_of_u, OWED_VAL, npc::personality, npc_opinion::trust, and npc_opinion::value.
Referenced by talk_trial::calc_chance(), and talk_effect_fun_t::set_add_debt().
parse_tags()
void parse_tags (std::string & phrase, const Character & u, const Character & me, const itype_id & item_type)
Definition at line 1577 of file npctalk.cpp.
{
    phrase = SNIPPET.expand( remove_color_tags( phrase ) );
    size_t fa;
    size_t fb;
    std::string tag;
    do {
        fa = phrase.find( '<' );
        fb = phrase.find( '>' );
        int l = fb - fa + 1;
        if( fa != std::string::npos && fb != std::string::npos ) {
            tag = phrase.substr( fa, fb - fa + 1 );
        } else {
            return;
        }
        // Special, dynamic tags go here
        if( tag == "<yrwp>" ) {
            phrase.replace( fa, l, remove_color_tags( u.weapon.tname() ) );
        } else if( tag == "<mywp>" ) {
            if( !me.is_armed() ) {
                phrase.replace( fa, l, _( "fists" ) );
            } else {
                phrase.replace( fa, l, remove_color_tags( me.weapon.tname() ) );
            }
        } else if( tag == "<ammo>" ) {
            if( !me.weapon.is_gun() ) {
                phrase.replace( fa, l, _( "BADAMMO" ) );
            } else {
                phrase.replace( fa, l, me.weapon.ammo_current()->nname( 1 ) );
            }
        } else if( tag == "<current_activity>" ) {
            std::string activity_name;
            const npc *guy = dynamic_cast<const npc *>( &me );
            if( guy->current_activity_id ) {
                activity_name = guy->current_activity_id.obj().verb().translated();
            } else {
                activity_name = _( "doing this and that" );
            }
            phrase.replace( fa, l, activity_name );
        } else if( tag == "<punc>" ) {
            switch( rng( 0, 2 ) ) {
                case 0:
                    phrase.replace( fa, l, pgettext( "punctuation", "." ) );
                    break;
                case 1:
                    phrase.replace( fa, l, pgettext( "punctuation", "" ) );
                    break;
                case 2:
                    phrase.replace( fa, l, pgettext( "punctuation", "!" ) );
                    break;
            }
        } else if( tag == "<mypronoun>" ) {
            std::string npcstr = me.male ? pgettext( "npc", "He" ) : pgettext( "npc", "She" );
            phrase.replace( fa, l, npcstr );
        } else if( tag == "<topic_item>" ) {
            phrase.replace( fa, l, item::nname( item_type, 2 ) );
        } else if( tag == "<topic_item_price>" ) {
            item tmp( item_type );
            phrase.replace( fa, l, format_money( tmp.price( true ) ) );
        } else if( tag == "<topic_item_my_total_price>" ) {
            item tmp( item_type );
            tmp.charges = me.charges_of( item_type );
            phrase.replace( fa, l, format_money( tmp.price( true ) ) );
        } else if( tag == "<topic_item_your_total_price>" ) {
            item tmp( item_type );
            tmp.charges = u.charges_of( item_type );
            phrase.replace( fa, l, format_money( tmp.price( true ) ) );
        } else if( !tag.empty() ) {
            debugmsg( "Bad tag.  '%s' (%d - %d)", tag.c_str(), fa, fb );
            phrase.replace( fa, fb - fa + 1, "????" );
        }
    } while( fa != std::string::npos && fb != std::string::npos );
}
References _, item::ammo_current(), item::charges, visitable< T >::charges_of(), npc::current_activity_id, debugmsg, snippet_library::expand(), format_money(), Character::is_armed(), item::is_gun(), Character::male, item::nname(), itype::nname(), string_id< T >::obj(), pgettext(), item::price(), remove_color_tags(), rng(), SNIPPET, item::tname(), translation::translated(), activity_type::verb(), and Character::weapon.
Referenced by talk_response::create_option_line(), npc_temp_orders_menu(), dialogue::opt(), npc::say(), and Character::suffer_from_schizophrenia().
special_talk()
const talk_topic & special_talk (char ch)
Definition at line 1715 of file npctalk.cpp.
{
    static const std::map<char, talk_topic> key_map = {{
            { 'L', talk_topic( "TALK_LOOK_AT" ) },
            { 'S', talk_topic( "TALK_SIZE_UP" ) },
            { 'O', talk_topic( "TALK_OPINION" ) },
            { 'Y', talk_topic( "TALK_SHOUT" ) },
        }
    };
    const auto iter = key_map.find( ch );
    if( iter != key_map.end() ) {
        return iter->second;
    }
    static const talk_topic no_topic = talk_topic( "TALK_NONE" );
    return no_topic;
}
Referenced by dialogue::opt().
tell_magic_veh_stop_following()
static void tell_magic_veh_stop_following () static
Definition at line 377 of file npctalk.cpp.
{
    for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
        vehicle *v = veh.v;
        if( v->magic ) {
            for( const vpart_reference &vp : v->get_all_parts() ) {
                const vpart_info &vpi = vp.info();
                if( vpi.has_flag( "MAGIC_FOLLOW" ) ) {
                    v->is_following = false;
                    v->engine_on = false;
                    break;
                }
            }
        }
    }
}
References vehicle::engine_on, vehicle::get_all_parts(), get_map(), vpart_info::has_flag(), vehicle::is_following, and vehicle::magic.
Referenced by game::chat().
tell_magic_veh_to_follow()
static void tell_magic_veh_to_follow () static
Definition at line 361 of file npctalk.cpp.
{
    for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
        vehicle *v = veh.v;
        if( v->magic ) {
            for( const vpart_reference &vp : v->get_all_parts() ) {
                const vpart_info &vpi = vp.info();
                if( vpi.has_flag( "MAGIC_FOLLOW" ) && v->is_owned_by( get_avatar() ) ) {
                    v->activate_magical_follow();
                    break;
                }
            }
        }
    }
}
References vehicle::activate_magical_follow(), vehicle::get_all_parts(), get_avatar(), get_map(), vpart_info::has_flag(), vehicle::is_owned_by(), and vehicle::magic.
Referenced by game::chat().
tell_veh_stop_following()
static void tell_veh_stop_following () static
Definition at line 340 of file npctalk.cpp.
{
    for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
        vehicle *v = veh.v;
        if( v->has_engine_type( fuel_type_animal, false ) && v->is_owned_by( get_avatar() ) ) {
            v->is_following = false;
            v->engine_on = false;
        }
    }
}
References vehicle::engine_on, fuel_type_animal, get_avatar(), get_map(), vehicle::has_engine_type(), vehicle::is_following, and vehicle::is_owned_by().
Referenced by game::chat().
topic_category()
int topic_category (const talk_topic & the_topic)
Definition at line 1494 of file npctalk.cpp.
{
    const auto &topic = the_topic.id;
    // TODO: ideally, this would be a property of the topic itself.
    // How this works: each category has a set of topics that belong to it, each set is checked
    // for the given topic and if a set contains, the category number is returned.
    static const std::unordered_set<std::string> topic_1 = { {
            "TALK_MISSION_START", "TALK_MISSION_DESCRIBE", "TALK_MISSION_OFFER",
            "TALK_MISSION_ACCEPTED", "TALK_MISSION_REJECTED", "TALK_MISSION_ADVICE",
            "TALK_MISSION_INQUIRE", "TALK_MISSION_SUCCESS", "TALK_MISSION_SUCCESS_LIE",
            "TALK_MISSION_FAILURE", "TALK_MISSION_REWARD", "TALK_MISSION_END",
            "TALK_MISSION_DESCRIBE_URGENT"
        }
    };
    if( topic_1.count( topic ) > 0 ) {
        return 1;
    }
    static const std::unordered_set<std::string> topic_2 = { {
            "TALK_SHARE_EQUIPMENT", "TALK_GIVE_EQUIPMENT", "TALK_DENY_EQUIPMENT"
        }
    };
    if( topic_2.count( topic ) > 0 ) {
        return 2;
    }
    static const std::unordered_set<std::string> topic_3 = { {
            "TALK_SUGGEST_FOLLOW", "TALK_AGREE_FOLLOW", "TALK_DENY_FOLLOW",
        }
    };
    if( topic_3.count( topic ) > 0 ) {
        return 3;
    }
    static const std::unordered_set<std::string> topic_4 = { {
            "TALK_COMBAT_ENGAGEMENT",
        }
    };
    if( topic_4.count( topic ) > 0 ) {
        return 4;
    }
    static const std::unordered_set<std::string> topic_5 = { {
            "TALK_COMBAT_COMMANDS",
        }
    };
    if( topic_5.count( topic ) > 0 ) {
        return 5;
    }
    static const std::unordered_set<std::string> topic_6 = { {
            "TALK_TRAIN", "TALK_TRAIN_START", "TALK_TRAIN_FORCE"
        }
    };
    if( topic_6.count( topic ) > 0 ) {
        return 6;
    }
    static const std::unordered_set<std::string> topic_7 = { {
            "TALK_MISC_RULES",
        }
    };
    if( topic_7.count( topic ) > 0 ) {
        return 7;
    }
    static const std::unordered_set<std::string> topic_8 = { {
            "TALK_AIM_RULES",
        }
    };
    if( topic_8.count( topic ) > 0 ) {
        return 8;
    }
    static const std::unordered_set<std::string> topic_9 = { {
            "TALK_FRIEND", "TALK_GIVE_ITEM", "TALK_USE_ITEM",
        }
    };
    if( topic_9.count( topic ) > 0 ) {
        return 9;
    }
    static const std::unordered_set<std::string> topic_99 = { {
            "TALK_SIZE_UP", "TALK_LOOK_AT", "TALK_OPINION", "TALK_SHOUT"
        }
    };
    if( topic_99.count( topic ) > 0 ) {
        return 99;
    }
    return -1; // Not grouped with other topics
}
References talk_topic::id.
Referenced by npc::talk_to_u().
translate_gendered_line()
static std::string translate_gendered_line (const std::string & line, const std::vector< std::string > & relevant_genders, const dialogue & d) static
Definition at line 2943 of file npctalk.cpp.
{
    GenderMap gender_map;
    for( const std::string &subject : relevant_genders ) {
        if( subject == "npc" ) {
            gender_map[subject] = d.beta->get_grammatical_genders();
        } else if( subject == "u" ) {
            gender_map[subject] = d.alpha->get_grammatical_genders();
        } else {
            debugmsg( "Unsupported subject '%s' for grammatical gender in dialogue", subject );
        }
    }
    return gettext_gendered( gender_map, line );
}
References dialogue::alpha, dialogue::beta, debugmsg, Character::get_grammatical_genders(), gettext_gendered(), and line().
Referenced by dynamic_line_t::dynamic_line_t().
try_consume()
static consumption_result try_consume (npc & p, item & it, std::string & reason) static
Definition at line 3266 of file npctalk.cpp.
{
    // TODO: Unify this with 'player::consume_item()'
    bool consuming_contents = it.is_container() && !it.contents.empty();
    item &to_eat = consuming_contents ? it.contents.front() : it;
    const auto &comest = to_eat.get_comestible();
    if( !comest ) {
        // Don't inform the player that we don't want to eat the lighter
        return REFUSED;
    }
    if( !p.will_accept_from_player( it ) ) {
        reason = _( "I don't <swear> trust you enough to eat THIS" );
        return REFUSED;
    }
    // TODO: Make it not a copy+paste from player::consume_item
    int amount_used = 1;
    if( to_eat.is_food() ) {
        if( !p.eat( to_eat ) ) {
            reason = _( "It doesn't look like a good idea to consume this" );
            return REFUSED;
        } else {
            reason = _( "Thanks, that hit the spot." );
        }
    } else if( to_eat.is_medication() || to_eat.get_contained().is_medication() ) {
        if( comest->tool ) {
            bool has = p.has_amount( comest->tool, 1 );
            if( item::count_by_charges( comest->tool ) ) {
                has = p.has_charges( comest->tool, 1 );
            }
            if( !has ) {
                reason = string_format( _( "I need a %s to consume that!" ),
                                        item::nname( comest->tool ) );
                return REFUSED;
            }
            p.use_charges( comest->tool, 1 );
            reason = _( "Thanks, I feel better already." );
        }
        if( to_eat.type->has_use() ) {
            amount_used = to_eat.type->invoke( p, to_eat, p.pos() );
            if( amount_used <= 0 ) {
                reason = _( "It doesn't look like a good idea to consume this" );
                return REFUSED;
            }
            reason = _( "Thanks, I used it." );
        }
        to_eat.charges -= amount_used;
        p.consume_effects( to_eat );
        p.moves -= 250;
    } else {
        debugmsg( "Unknown comestible type of item: %s\n", to_eat.tname() );
    }
    if( to_eat.charges > 0 ) {
        return CONSUMED_SOME;
    }
    if( consuming_contents ) {
        it.remove_item( it.contents.front() );
        return CONSUMED_SOME;
    }
    // If not consuming contents and charge <= 0, we just ate the last charge from the stack
    return CONSUMED_ALL;
}
References _, item::charges, Character::consume_effects(), CONSUMED_ALL, CONSUMED_SOME, item::contents, item::count_by_charges(), debugmsg, player::eat(), item_contents::empty(), item_contents::front(), item::get_comestible(), item::get_contained(), visitable< T >::has_amount(), Character::has_charges(), itype::has_use(), itype::invoke(), item::is_container(), item::is_food(), item::is_medication(), Creature::moves, item::nname(), Character::pos(), REFUSED, visitable< T >::remove_item(), string_format(), item::tname(), item::type, Character::use_charges(), and npc::will_accept_from_player().
Referenced by give_item_to().
unload_talk_topics()
void unload_talk_topics ()
Definition at line 3212 of file npctalk.cpp.
{
    json_talk_topics.clear();
}
References json_talk_topics.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
ACT_AIM
const activity_id ACT_AIM("ACT_AIM") ("ACT_AIM") static
Referenced by npc::talk_to_u().
ACT_SOCIALIZE
const activity_id ACT_SOCIALIZE("ACT_SOCIALIZE") ("ACT_SOCIALIZE") static
Referenced by npc::talk_to_u().
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
Referenced by dialogue::dynamic_line(), dialogue::gen_responses(), and npc::talk_to_u().
ACT_WAIT_NPC
const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC") ("ACT_WAIT_NPC") static
Referenced by npc::talk_to_u().
bio_armor_eyes
const bionic_id bio_armor_eyes("bio_armor_eyes") ("bio_armor_eyes") static
Referenced by talk_trial::calc_chance().
bio_deformity
const bionic_id bio_deformity("bio_deformity") ("bio_deformity") static
Referenced by talk_trial::calc_chance().
bio_face_mask
const bionic_id bio_face_mask("bio_face_mask") ("bio_face_mask") static
Referenced by talk_trial::calc_chance().
bio_voice
const bionic_id bio_voice("bio_voice") ("bio_voice") static
Referenced by talk_trial::calc_chance().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by npc::talk_to_u().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by dialogue::dynamic_line(), and npc::talk_to_u().
effect_npc_suspend
const efftype_id effect_npc_suspend("npc_suspend") ("npc_suspend") static
Referenced by npc::talk_to_u().
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by talk_effect_fun_t::set_u_buy_monster().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by talk_effect_fun_t::set_u_buy_monster().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by game::chat().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by npc::talk_to_u().
effect_under_op
const efftype_id effect_under_op("under_operation") ("under_operation") static
Referenced by npc::talk_to_u().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by assign_veh_to_follow(), game::chat(), game::control_vehicle(), pldrive(), and tell_veh_stop_following().
json_talk_topics
std::map<std::string, json_talk_topic> json_talk_topics static
Definition at line 113 of file npctalk.cpp.
Referenced by dialogue::apply_speaker_effects(), dialogue::dynamic_line(), dialogue::gen_responses(), load_inline_topic(), load_talk_topic(), and unload_talk_topics().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by talk_trial::roll().
trait_DEBUG_MIND_CONTROL
const trait_id trait_DEBUG_MIND_CONTROL("DEBUG_MIND_CONTROL") ("DEBUG_MIND_CONTROL") static
Referenced by talk_trial::calc_chance(), dialogue::gen_responses(), give_item_to(), talk_trial::roll(), and npc::talk_to_u().
trait_PROF_FOODP
const trait_id trait_PROF_FOODP("PROF_FOODP") ("PROF_FOODP") static
Referenced by game::chat(), and npc::talk_to_u().
zone_type_npc_investigate_only
const zone_type_id zone_type_npc_investigate_only("NPC_INVESTIGATE_ONLY") ("NPC_INVESTIGATE_ONLY") static
Referenced by npc::handle_sound().
zone_type_npc_no_investigate
const zone_type_id zone_type_npc_no_investigate("NPC_NO_INVESTIGATE") ("NPC_NO_INVESTIGATE") static
Referenced by npc::handle_sound().