Cataclysm BN: src/omdata.h File Reference
omdata.h File Reference
#include <climits>
#include <cstddef>
#include <cstdint>
#include <bitset>
#include <list>
#include <set>
#include <vector>
#include <array>
#include <string>
#include "cuboid_rectangle.h"
#include "catacharset.h"
#include "color.h"
#include "numeric_interval.h"
#include "coordinates.h"
#include "int_id.h"
#include "overmap_location.h"
#include "point.h"
#include "string_id.h"
#include "translations.h"
#include "type_id.h"
#include "optional.h"
Classes
class overmap_land_use_code
struct overmap_spawns
struct overmap_static_spawns
struct oter_type_t
struct oter_t
struct overmap_special_spawns
struct overmap_special_terrain
struct overmap_special_connection
class overmap_special
Namespaces
namespace om_direction
Direction on the overmap.
namespace overmap_terrains
namespace overmap_land_use_codes
namespace overmap_specials
namespace city_buildings
Macros
#define CATA_SRC_OMDATA_H
Typedefs
using overmap_land_use_code_id = string_id< overmap_land_use_code >
using overmap_special_id = string_id< overmap_special >
Enumerations
enum class om_direction::type : int {
om_direction::invalid = -1 , om_direction::none , om_direction::north = none , om_direction::east ,
om_direction::south , om_direction::west
}
Basic enum for directions.
enum oter_flags {
known_down = 0 , known_up , no_rotate , river_tile ,
has_sidewalk , line_drawing , subway_connection , lake ,
lake_shore , generic_loot , risk_high , risk_low ,
source_ammo , source_animals , source_books , source_chemistry ,
source_clothing , source_construction , source_cooking , source_drink ,
source_electronics , source_fabrication , source_farming , source_food ,
source_forage , source_fuel , source_gun , source_luxury ,
source_medicine , source_people , source_safety , source_tailoring ,
source_vehicles , source_weapon , num_oter_flags
}
Functions
static const overmap_land_use_code_id land_use_code_forest ("forest")
static const overmap_land_use_code_id land_use_code_wetland ("wetland")
static const overmap_land_use_code_id land_use_code_wetland_forest ("wetland_forest")
static const overmap_land_use_code_id land_use_code_wetland_saltwater ("wetland_saltwater")
const std::string & om_direction::id (type dir)
Identifier for serialization purposes.
std::string om_direction::name (type dir)
Get Human readable name of a direction.
point om_direction::rotate (const point &p, type dir)
Various rotations.
tripoint om_direction::rotate (const tripoint &p, type dir)
uint32_t om_direction::rotate_symbol (uint32_t sym, type dir)
point om_direction::displace (type dir, int dist=1)
Returns point(0, 0) displaced in specified direction by a specified distance.
type om_direction::add (type dir1, type dir2)
Returns a sum of two numbers.
type om_direction::turn_left (type dir)
Turn by 90 degrees to the left, to the right, or randomly (either left or right).
type om_direction::turn_right (type dir)
type om_direction::turn_random (type dir)
type om_direction::opposite (type dir)
Returns an opposite direction.
type om_direction::random ()
Returns a random direction.
bool om_direction::are_parallel (type dir1, type dir2)
Whether these directions are parallel.
bool operator== (const oter_id &lhs, const char *rhs)
bool operator!= (const oter_id &lhs, const char *rhs)
void overmap_terrains::load (const JsonObject &jo, const std::string &src)
void overmap_terrains::check_consistency ()
void overmap_terrains::finalize ()
void overmap_terrains::reset ()
const std::vector< oter_t > & overmap_terrains::get_all ()
void overmap_land_use_codes::load (const JsonObject &jo, const std::string &src)
void overmap_land_use_codes::finalize ()
void overmap_land_use_codes::check_consistency ()
void overmap_land_use_codes::reset ()
const std::vector< overmap_land_use_code > & overmap_land_use_codes::get_all ()
void overmap_specials::load (const JsonObject &jo, const std::string &src)
void overmap_specials::finalize ()
void overmap_specials::check_consistency ()
void overmap_specials::reset ()
const std::vector< overmap_special > & overmap_specials::get_all ()
overmap_special_batch overmap_specials::get_default_batch (const point_abs_om &origin)
overmap_special_id overmap_specials::create_building_from (const string_id< oter_type_t > &base)
Generates a simple special from a building id.
void city_buildings::load (const JsonObject &jo, const std::string &src)
Variables
const std::array< type, 4 > om_direction::all = {{ type::north, type::east, type::south, type::west }}
For the purposes of iteration.
const size_t om_direction::size = all.size()
const size_t om_direction::bits = static_cast<size_t>(-1) >> (CHAR_BIT *sizeof(size_t) - size)
Number of bits needed to store directions.
static constexpr int OMSPEC_FREQ = 15
Macro Definition Documentation
CATA_SRC_OMDATA_H
#define CATA_SRC_OMDATA_H
Definition at line 3 of file omdata.h.
Typedef Documentation
overmap_land_use_code_id
using overmap_land_use_code_id = string_id<overmap_land_use_code>
Definition at line 32 of file omdata.h.
overmap_special_id
using overmap_special_id = string_id<overmap_special>
Definition at line 40 of file omdata.h.
Enumeration Type Documentation
oter_flags
enum oter_flags
Enumerator
known_down
known_up
no_rotate
river_tile
has_sidewalk
line_drawing
subway_connection
lake
lake_shore
generic_loot
risk_high
risk_low
source_ammo
source_animals
source_books
source_chemistry
source_clothing
source_construction
source_cooking
source_drink
source_electronics
source_fabrication
source_farming
source_food
source_forage
source_fuel
source_gun
source_luxury
source_medicine
source_people
source_safety
source_tailoring
source_vehicles
source_weapon
num_oter_flags
Definition at line 159 of file omdata.h.
                {
    known_down = 0,
    known_up,
    no_rotate,    // this tile doesn't have four rotated versions (north, east, south, west)
    river_tile,
    has_sidewalk,
    line_drawing, // does this tile have 8 versions, including straights, bends, tees, and a fourway?
    subway_connection,
    lake,
    lake_shore,
    generic_loot,
    risk_high,
    risk_low,
    source_ammo,
    source_animals,
    source_books,
    source_chemistry,
    source_clothing,
    source_construction,
    source_cooking,
    source_drink,
    source_electronics,
    source_fabrication,
    source_farming,
    source_food,
    source_forage,
    source_fuel,
    source_gun,
    source_luxury,
    source_medicine,
    source_people,
    source_safety,
    source_tailoring,
    source_vehicles,
    source_weapon,
    num_oter_flags
};
Function Documentation
land_use_code_forest()
static const overmap_land_use_code_id land_use_code_forest ("forest") static
Referenced by oter_t::is_wooded().
land_use_code_wetland()
static const overmap_land_use_code_id land_use_code_wetland ("wetland") static
Referenced by oter_t::is_wooded().
land_use_code_wetland_forest()
static const overmap_land_use_code_id land_use_code_wetland_forest ("wetland_forest") static
Referenced by oter_t::is_wooded().
land_use_code_wetland_saltwater()
static const overmap_land_use_code_id land_use_code_wetland_saltwater ("wetland_saltwater") static
Referenced by oter_t::is_wooded().
operator!=()
bool operator!= (const oter_id & lhs, const char * rhs)
Definition at line 333 of file overmap.cpp.
{
    return !( lhs == rhs );
}
operator==()
bool operator== (const oter_id & lhs, const char * rhs)
Definition at line 328 of file overmap.cpp.
{
    return lhs.id().str() == rhs;
}
References int_id< T >::id(), and string_id< T >::str().
Variable Documentation
OMSPEC_FREQ
constexpr int OMSPEC_FREQ = 15 static constexpr
Definition at line 387 of file omdata.h.
Referenced by overmap_specials::check_consistency(), overmapbuffer::place_special(), and overmap::place_specials().