Cataclysm BN: src/options.cpp File Reference
options.cpp File Reference
#include "options.h"
#include <locale>
#include <cfloat>
#include <climits>
#include <iterator>
#include <stdexcept>
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "cursesport.h"
#include "debug.h"
#include "enum_bitset.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "json.h"
#include "language.h"
#include "line.h"
#include "mapsharing.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "popup.h"
#include "sdlsound.h"
#include "sdltiles.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "translations.h"
#include "ui_manager.h"
#include "worldfactory.h"
#include <algorithm>
#include <cstdlib>
#include <exception>
#include <memory>
#include <sstream>
#include <string>
Classes
struct debug_log_level
struct debug_log_class
struct string_col
String with color.
Functions
options_manager & get_options ()
static const std::string blank_value (1, 001)
static options_manager::cOpt::COPT_VALUE_TYPE get_value_type (const std::string &sType)
template<>
std::string options_manager::cOpt::value_as< std::string > () const
static std::vector< options_manager::id_and_option > build_resource_list (std::map< std::string, std::string > &resource_option, const std::string &operation_name, const std::string &dirname, const std::string &filename)
Fill a mapping with values.
static void refresh_tiles (bool, bool, bool, bool)
static void draw_borders_external (const catacurses::window &w, int horizontal_level, const std::set< int > &vert_lines, const bool world_options_only)
static void draw_borders_internal (const catacurses::window &w, std::set< int > &vert_lines)
Variables
std::map< std::string, std::string > TILESETS
A mapping(string:string) that stores all tileset values.
std::map< std::string, std::string > SOUNDPACKS
A mapping(string:string) that stores all soundpack values.
static const std::vector< debug_log_level > debug_log_levels
static const std::vector< debug_log_class > debug_log_classes
Function Documentation
blank_value()
static const std::string blank_value (1 , 001) static
Referenced by options_manager::add_retry(), and options_manager::enable_json().
build_resource_list()
static std::vector< options_manager::id_and_option > build_resource_list (std::map< std::string, std::string > & resource_option, const std::string & operation_name, const std::string & dirname, const std::string & filename) static
Fill a mapping with values.
Scans all directories in dirname directory for a file named filename. All found values added to resource_option as name, resource_dir. Furthermore, it builds possible values list for cOpt class.
Definition at line 1019 of file options.cpp.
{
    std::vector<options_manager::id_and_option> resource_names;
    resource_option.clear();
    const auto resource_dirs = get_directories_with( filename, dirname, true );
    for( auto &resource_dir : resource_dirs ) {
        read_from_file( resource_dir + "/" + filename, [&]( std::istream & fin ) {
            std::string resource_name;
            std::string view_name;
            // should only have 2 values inside it, otherwise is going to only load the last 2 values
            while( !fin.eof() ) {
                std::string sOption;
                fin >> sOption;
                if( sOption.empty() ) {
                    getline( fin, sOption );    // Empty line, chomp it
                } else if( sOption[0] == '#' ) { // # indicates a comment
                    getline( fin, sOption );
                } else {
                    if( sOption.find( "NAME" ) != std::string::npos ) {
                        resource_name.clear();
                        getline( fin, resource_name );
                        resource_name = trim( resource_name );
                    } else if( sOption.find( "VIEW" ) != std::string::npos ) {
                        view_name.clear();
                        getline( fin, view_name );
                        view_name = trim( view_name );
                        break;
                    }
                }
            }
            resource_names.emplace_back( resource_name,
                                         view_name.empty() ? no_translation( resource_name ) : to_translation( view_name ) );
            if( resource_option.count( resource_name ) != 0 ) {
                debugmsg( "Found \"%s\" duplicate with name \"%s\" (new definition will be ignored)",
                          operation_name, resource_name );
            } else {
                resource_option.insert( std::pair<std::string, std::string>( resource_name, resource_dir ) );
            }
        } );
    }
    return resource_names;
}
References get_directories_with(), no_translation(), read_from_file(), and to_translation().
Referenced by options_manager::load_soundpack_from(), and options_manager::load_tilesets_from().
draw_borders_external()
static void draw_borders_external (const catacurses::window & w, int horizontal_level, const std::set< int > & vert_lines, const bool world_options_only) static
Definition at line 2682 of file options.cpp.
{
    if( !world_options_only ) {
        draw_border( w, BORDER_COLOR, _( " OPTIONS " ) );
    }
    // intersections
    mvwputch( w, point( 0, horizontal_level ), BORDER_COLOR, LINE_XXXO ); // |-
    mvwputch( w, point( getmaxx( w ) - 1, horizontal_level ), BORDER_COLOR, LINE_XOXX ); // -|
    for( auto &x : vert_lines ) {
        mvwputch( w, point( x + 1, getmaxy( w ) - 1 ), BORDER_COLOR, LINE_XXOX ); // _|_
    }
    wnoutrefresh( w );
}
References _, BORDER_COLOR, draw_border(), catacurses::getmaxx(), catacurses::getmaxy(), LINE_XOXX, LINE_XXOX, LINE_XXXO, mvwputch(), and catacurses::wnoutrefresh().
Referenced by options_manager::show().
draw_borders_internal()
static void draw_borders_internal (const catacurses::window & w, std::set< int > & vert_lines) static
Definition at line 2698 of file options.cpp.
{
    for( int i = 0; i < getmaxx( w ); ++i ) {
        if( vert_lines.count( i ) != 0 ) {
            // intersection
            mvwputch( w, point( i, 0 ), BORDER_COLOR, LINE_OXXX );
        } else {
            // regular line
            mvwputch( w, point( i, 0 ), BORDER_COLOR, LINE_OXOX );
        }
    }
    wnoutrefresh( w );
}
References BORDER_COLOR, catacurses::getmaxx(), LINE_OXOX, LINE_OXXX, mvwputch(), and catacurses::wnoutrefresh().
Referenced by options_manager::show().
get_options()
options_manager & get_options ()
Definition at line 142 of file options.cpp.
{
    static options_manager single_instance;
    return single_instance;
}
Referenced by auto_pickup::player_settings::add_rule(), safemode::add_rule(), regional_settings::finalize(), get_option(), game::handle_action(), worldfactory::init(), game_ui::init_ui(), load_external_option(), WORLD::load_legacy_options(), WORLD::load_options(), load_world_option(), main(), main_menu::opening_screen(), prompt_select_lang_on_startup(), worldfactory::remove_world(), worldfactory::set_active_world(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), safemode::show(), worldfactory::show_worldgen_tab_options(), and WORLD::WORLD().
get_value_type()
static options_manager::cOpt::COPT_VALUE_TYPE get_value_type (const std::string & sType) static
Definition at line 233 of file options.cpp.
{
    using CVT = options_manager::cOpt::COPT_VALUE_TYPE;
    static std::unordered_map<std::string, CVT> vt_map = {
        { "float", CVT::CVT_FLOAT },
        { "bool", CVT::CVT_BOOL },
        { "int", CVT::CVT_INT },
        { "int_map", CVT::CVT_INT },
        { "string_select", CVT::CVT_STRING },
        { "string_input", CVT::CVT_STRING },
        { "VOID", CVT::CVT_VOID }
    };
    auto result = vt_map.find( sType );
    return result != vt_map.end() ? result->second : options_manager::cOpt::CVT_UNKNOWN;
}
References options_manager::cOpt::CVT_UNKNOWN.
Referenced by options_manager::add(), and options_manager::add_external().
options_manager::cOpt::value_as< std::string >()
template<> std::string options_manager::cOpt::value_as< std::string > () const
Definition at line 714 of file options.cpp.
{
    if( eType != CVT_STRING ) {
        debugmsg( "%s tried to get string value from option of type %s", sName, sType );
    }
    return sSet;
}
References debugmsg.
refresh_tiles()
static void refresh_tiles (bool , bool , bool , bool) static
Definition at line 2677 of file options.cpp.
{
}
Referenced by options_manager::show().
Variable Documentation
debug_log_classes
const std::vector<debug_log_class> debug_log_classes static
Definition at line 96 of file options.cpp.
Referenced by options_manager::add_options_debug(), and options_manager::cache_to_globals().
debug_log_levels
const std::vector<debug_log_level> debug_log_levels static
Initial value:
= { {
        {
            DL::Debug, "DEBUGLOG_LEV_DEBUG", translate_marker( "Debug" ),
            translate_marker( "Debug information" ),
            false
        },
        {
            DL::Info, "DEBUGLOG_LEV_INFO", translate_marker( "Info" ),
            translate_marker( "General information" ),
            true
        },
        {
            DL::Warn, "DEBUGLOG_LEV_WARNING", translate_marker( "Warning" ),
            translate_marker( "Warnings" ),
            true
        },
    }
}
Definition at line 76 of file options.cpp.
Referenced by options_manager::add_options_debug(), and options_manager::cache_to_globals().
SOUNDPACKS
std::map<std::string, std::string> SOUNDPACKS
A mapping(string:string) that stores all soundpack values.
Firsts string is soundpack NAME from config. Second string is directory that contains soundpack.
Definition at line 57 of file options.cpp.
Referenced by options_manager::build_soundpacks_list(), and options_manager::load_soundpack_from().
TILESETS
std::map<std::string, std::string> TILESETS
A mapping(string:string) that stores all tileset values.
Firsts string is tileset NAME from config. Second string is directory that contain tileset.
Definition at line 56 of file options.cpp.
Referenced by options_manager::build_tilesets_list(), and options_manager::load_tilesets_from().