Cataclysm BN: src/options.h File Reference
options.h File Reference
#include <functional>
#include <map>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include <tuple>
#include "translations.h"
#include "optional.h"
Classes
class options_manager
class options_manager::id_and_option
class options_manager::cOpt
class options_manager::Group
Option group.
class options_manager::PageItem
Single page item (entry).
class options_manager::Page
A page (or tab) to be displayed in the options UI.
Macros
#define CATA_SRC_OPTIONS_H
Functions
bool use_narrow_sidebar ()
options_manager & get_options ()
template<typename T >
T get_option (const std::string &name)
Variables
std::map< std::string, std::string > TILESETS
A mapping(string:string) that stores all tileset values.
std::map< std::string, std::string > SOUNDPACKS
A mapping(string:string) that stores all soundpack values.
Macro Definition Documentation
CATA_SRC_OPTIONS_H
#define CATA_SRC_OPTIONS_H
Definition at line 3 of file options.h.
Function Documentation
get_option()
template<typename T > T get_option (const std::string & name) inline
Definition at line 368 of file options.h.
{
    return get_options().get_option( name ).value_as<T>();
}
References options_manager::get_option(), get_options(), om_direction::name(), and options_manager::cOpt::value_as().
Referenced by game::handle_action(), and safemode::show().
get_options()
options_manager & get_options ()
Definition at line 47 of file options.cpp.
{
    static options_manager single_instance;
    return single_instance;
}
Referenced by auto_pickup::player_settings::add_rule(), safemode::add_rule(), regional_settings::finalize(), get_option(), game::handle_action(), worldfactory::init(), game_ui::init_ui(), load_external_option(), WORLD::load_legacy_options(), WORLD::load_options(), load_world_option(), main(), main_menu::opening_screen(), prompt_select_lang_on_startup(), worldfactory::remove_world(), worldfactory::set_active_world(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), safemode::show(), worldfactory::show_worldgen_tab_options(), and WORLD::WORLD().
use_narrow_sidebar()
bool use_narrow_sidebar ()
Variable Documentation
SOUNDPACKS
std::map<std::string, std::string> SOUNDPACKS extern
A mapping(string:string) that stores all soundpack values.
Firsts string is soundpack NAME from config. Second string is directory that contains soundpack.
Definition at line 57 of file options.cpp.
Referenced by options_manager::build_soundpacks_list(), and options_manager::load_soundpack_from().
TILESETS
std::map<std::string, std::string> TILESETS extern
A mapping(string:string) that stores all tileset values.
Firsts string is tileset NAME from config. Second string is directory that contain tileset.
Definition at line 56 of file options.cpp.
Referenced by options_manager::build_tilesets_list(), and options_manager::load_tilesets_from().