Cataclysm BN: src/output.h File Reference
output.h File Reference
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <forward_list>
#include <functional>
#include <iterator>
#include <stack>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "catacharset.h"
#include "color.h"
#include "debug.h"
#include "enums.h"
#include "line.h"
#include "point.h"
#include "string_formatter.h"
#include "translations.h"
#include "units.h"
Classes
class border_helper
class border_helper::border_info
struct border_helper::border_connection
struct item_info_data
class scrollbar
class scrolling_text_view
class scrollingcombattext
class scrollingcombattext::cSCT
Namespaces
namespace catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_OUTPUT_H
#define LINE_XOXO 4194424
#define LINE_OXOX 4194417
#define LINE_XXOO 4194413
#define LINE_OXXO 4194412
#define LINE_OOXX 4194411
#define LINE_XOOX 4194410
#define LINE_XXXO 4194420
#define LINE_XXOX 4194422
#define LINE_XOXX 4194421
#define LINE_OXXX 4194423
#define LINE_XXXX 4194414
#define LINE_XOXO_C 0xa0
#define LINE_OXOX_C 0xa1
#define LINE_XXOO_C 0xa2
#define LINE_OXXO_C 0xa3
#define LINE_OOXX_C 0xa4
#define LINE_XOOX_C 0xa5
#define LINE_XXXO_C 0xa6
#define LINE_XXOX_C 0xa7
#define LINE_XOXX_C 0xa8
#define LINE_OXXX_C 0xa9
#define LINE_XXXX_C 0xaa
#define LINE_XOXO_S "│"
#define LINE_OXOX_S "─"
#define LINE_XXOO_S "└"
#define LINE_OXXO_S "┌"
#define LINE_OOXX_S "┐"
#define LINE_XOOX_S "┘"
#define LINE_XXXO_S "├"
#define LINE_XXOX_S "┴"
#define LINE_XOXX_S "┤"
#define LINE_OXXX_S "┬"
#define LINE_XXXX_S "┼"
#define LINE_XOXO_UNICODE 0x2502
#define LINE_OXOX_UNICODE 0x2500
#define LINE_XXOO_UNICODE 0x2514
#define LINE_OXXO_UNICODE 0x250C
#define LINE_OOXX_UNICODE 0x2510
#define LINE_XOOX_UNICODE 0x2518
#define LINE_XXXO_UNICODE 0x251C
#define LINE_XXOX_UNICODE 0x2534
#define LINE_XOXX_UNICODE 0x2524
#define LINE_OXXX_UNICODE 0x252C
#define LINE_XXXX_UNICODE 0x253C
#define BORDER_COLOR c_light_gray
Functions
std::string string_from_int (const catacurses::chtype ch)
nc_color msgtype_to_color (game_message_type type, bool bOldMsg=false)
color tags
Most print function have only one color parameter (or none at all), therefor they would print the whole text in one color. To print some parts of a text in a different color, one would have to write separate calls to the print functions.
Color tags allow embedding coloring instructions directly into the text, which allows a single call to the print function with the full text. The color tags are removed (not printed), but the text inside the tags is printed with a specific color.
Example: Print "You need a tool to do this." in white and the word "tool" in red.
wprintz(w, c_white, "You need a ");
wprintz(w, c_red, "tool");
wprintz(w, c_white, " to do this.");
Same code with color tags:
print_colored_text(w, c_white, "You need a <color_red>tool</color> to do this.");
Color tags must appear in pairs, first <color_XXX>, followed by text, followed by </color>. The text in between is colored according to the color XXX. XXX must be a valid color name, see color_from_string. Color tags do not stack, the text inside the color tags should not contain any other color tags.
Functions that handle color tags should contain a note about this in their documentation. If they have no such note, they probably don't handle color tags (which means they just print the string as is).
Note: use colorize to add color tags to a string.
nc_color color = ...;
text = colorize("some text", color);
One can use utf8_width with the second parameter set to true to determine the printed length of a string containing color tags. The parameter instructs utf8_width to ignore the color tags. For example utf8_width("<color_red>text</color>") would return 23, but utf8_width("<color_red>text</color>", true) returns 4 (the length of "text").
std::string rm_prefix (std::string str, char c1='<', char c2='>')
Removes the prefix starting at the first occurrence of c1 until the first occurrence of c2.
color_tag_parse_result::tag_type update_color_stack (std::stack< nc_color > &color_stack, const std::string &seg, report_color_error color_error=report_color_error::yes)
Adds the color represented by the next color tag found in the string to the top of the stack.
std::string remove_color_tags (const std::string &s)
Removes the color tags from the input string.
std::vector< std::string > foldstring (const std::string &str, int width, char split=' ')
Split the input text into separate lines and wrap long lines.
void print_colored_text (const catacurses::window &w, const point &p, nc_color &cur_color, const nc_color &base_color, const std::string &text, report_color_error color_error=report_color_error::yes)
Print text with embedded color_tags, x, y are in curses system.
int print_scrollable (const catacurses::window &w, int begin_line, const std::string &text, const nc_color &base_color, const std::string &scroll_msg)
Print word wrapped text (with color_tags) into the window.
int fold_and_print (const catacurses::window &w, const point &begin, int width, const nc_color &base_color, const std::string &text, char split=' ')
Fold and print text in the given window.
template<typename ... Args>
int fold_and_print (const catacurses::window &w, const point &begin, const int width, const nc_color &base_color, const char *const mes, Args &&... args)
Same as other fold_and_print, but does string formatting via string_format.
int fold_and_print_from (const catacurses::window &w, const point &begin, int width, int begin_line, const nc_color &base_color, const std::string &text)
Like fold_and_print, but starts the output with the N-th line of the folded string.
template<typename ... Args>
int fold_and_print_from (const catacurses::window &w, const point &begin, const int width, const int begin_line, const nc_color &base_color, const char *const mes, Args &&... args)
Same as other fold_and_print_from, but does formatting via string_format.
void trim_and_print (const catacurses::window &w, const point &begin, int width, const nc_color &base_color, const std::string &text, report_color_error color_error=report_color_error::yes)
Prints a single line of text.
std::string trim_by_length (const std::string &text, int width)
template<typename ... Args>
void trim_and_print (const catacurses::window &w, const point &begin, const int width, const nc_color &base_color, const char *const mes, Args &&... args)
template<typename ... Args>
void trim_and_print (const catacurses::window &w, const point &begin, const int width, const nc_color &base_color, const report_color_error color_error, const char *const mes, Args &&... args)
void center_print (const catacurses::window &w, int y, const nc_color &FG, const std::string &text)
int right_print (const catacurses::window &w, int line, int right_indent, const nc_color &FG, const std::string &text)
void insert_table (const catacurses::window &w, int pad, int line, int columns, const nc_color &FG, const std::string &divider, bool r_align, const std::vector< std::string > &data)
Inserts a table into a window, with data right-aligned.
void scrollable_text (const std::function< catacurses::window()> &init_window, const std::string &title, const std::string &text)
std::string name_and_value (const std::string &name, int value, int field_width)
std::string name_and_value (const std::string &name, const std::string &value, int field_width)
void wputch (const catacurses::window &w, nc_color FG, int ch)
void mvwputch (const catacurses::window &w, const point &p, nc_color FG, int ch)
void mvwputch (const catacurses::window &w, const point &p, nc_color FG, const std::string &ch)
void mvwputch_inv (const catacurses::window &w, const point &p, nc_color FG, int ch)
void mvwputch_inv (const catacurses::window &w, const point &p, nc_color FG, const std::string &ch)
void mvwputch_hi (const catacurses::window &w, const point &p, nc_color FG, int ch)
void mvwputch_hi (const catacurses::window &w, const point &p, nc_color FG, const std::string &ch)
void mvwprintz (const catacurses::window &w, const point &p, const nc_color &FG, const std::string &text)
template<typename ... Args>
void mvwprintz (const catacurses::window &w, const point &p, const nc_color &FG, const char *const mes, Args &&... args)
void wprintz (const catacurses::window &w, const nc_color &FG, const std::string &text)
template<typename ... Args>
void wprintz (const catacurses::window &w, const nc_color &FG, const char *const mes, Args &&... args)
void draw_custom_border (const catacurses::window &w, catacurses::chtype ls=1, catacurses::chtype rs=1, catacurses::chtype ts=1, catacurses::chtype bs=1, catacurses::chtype tl=1, catacurses::chtype tr=1, catacurses::chtype bl=1, catacurses::chtype br=1, nc_color FG=BORDER_COLOR, const point &pos=point_zero, int height=0, int width=0)
void draw_border (const catacurses::window &w, nc_color border_color=BORDER_COLOR, const std::string &title="", nc_color title_color=c_light_red)
void draw_border_below_tabs (const catacurses::window &w, nc_color border_color=BORDER_COLOR)
std::string word_rewrap (const std::string &ins, int width, uint32_t split=' ')
std::vector< size_t > get_tag_positions (const std::string &s)
std::vector< std::string > split_by_color (const std::string &s)
bool query_yn (const std::string &text)
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args)
bool query_int (int &result, int default_val, const std::string &text)
template<typename ... Args>
bool query_int (int &result, int default_val, const char *const msg, Args &&... args)
bool query_int (int &result, const std::string &text)
template<typename ... Args>
bool query_int (int &result, const char *const msg, Args &&... args)
std::vector< std::string > get_hotkeys (const std::string &s)
Variables
int TERMX
int TERMY
int POSX
int POSY
int TERRAIN_WINDOW_WIDTH
int TERRAIN_WINDOW_HEIGHT
int TERRAIN_WINDOW_TERM_WIDTH
int TERRAIN_WINDOW_TERM_HEIGHT
int FULL_SCREEN_WIDTH
int FULL_SCREEN_HEIGHT
int OVERMAP_WINDOW_WIDTH
int OVERMAP_WINDOW_HEIGHT
int OVERMAP_WINDOW_TERM_WIDTH
int OVERMAP_WINDOW_TERM_HEIGHT
int OVERMAP_LEGEND_WIDTH
Popup windows
Each function displays a popup (above all other windows) with the given (formatted) text.
The popup function with the flags parameters does all the work, the other functions call it with specific flags. The function can be called with a bitwise combination of flags.
The functions return the key (taken from getch) that was entered by the user.
The message is a printf-like string. It may contain color_tags, which are used while printing.
PF_GET_KEY (ignored when combined with PF_NO_WAIT) cancels the popup on any user input. Without the flag the popup is only canceled when the user enters new-line, Space and Escape. This flag is passed by popup_getkey.
PF_ON_TOP makes the window appear on the top of the screen (at the upper most row). Without this flag, the popup is centered on the screen. The flag is passed by popup_top.
PF_FULLSCREEN makes the popup window as big as the whole screen. This flag is passed by full_screen_popup.
PF_NONE is a placeholder for none of the above flags.
enum PopupFlags { PF_NONE = 0 , PF_GET_KEY = 1 << 0 , PF_ON_TOP = 1 << 2 , PF_FULLSCREEN = 1 << 3 }
enum class item_filter_type : int { FIRST = 1 , FILTER = 1 , LOW_PRIORITY = 2 , HIGH_PRIORITY = 3 }
enum class enumeration_conjunction {
none , and_ , or_ , newline ,
arrow
}
scrollingcombattext SCT
template<typename ... Args>
int popup_getkey (const char *const mes, Args &&... args)
template<typename ... Args>
void popup_top (const char *const mes, Args &&... args)
template<typename ... Args>
void popup (const char *mes, Args &&... args)
int popup (const std::string &text, PopupFlags flags=PF_NONE)
template<typename ... Args>
void full_screen_popup (const char *mes, Args &&... args)
std::string format_item_info (const std::vector< iteminfo > &vItemDisplay, const std::vector< iteminfo > &vItemCompare)
input_event draw_item_info (const catacurses::window &win, item_info_data &data)
input_event draw_item_info (int iLeft, int iWidth, int iTop, int iHeight, item_info_data &data)
input_event draw_item_info (const std::function< catacurses::window()> &init_window, item_info_data &data)
void draw_item_filter_rules (const catacurses::window &win, int starty, int height, item_filter_type type)
Write some tips (such as precede items with - to exclude them) onto the window.
char rand_char ()
int special_symbol (int sym)
size_t shortcut_print (const catacurses::window &w, const point &p, nc_color text_color, nc_color shortcut_color, const std::string &fmt)
size_t shortcut_print (const catacurses::window &w, nc_color text_color, nc_color shortcut_color, const std::string &fmt)
std::string shortcut_text (nc_color shortcut_color, const std::string &fmt)
std::pair< std::string, nc_color > get_bar (float cur, float max, int width=5, bool extra_resolution=true, const std::vector< nc_color > &colors={ c_green, c_light_green, c_yellow, c_light_red, c_red })
std::pair< std::string, nc_color > get_hp_bar (int cur_hp, int max_hp, bool is_mon=false)
std::pair< std::string, nc_color > get_stamina_bar (int cur_stam, int max_stam)
std::pair< std::string, nc_color > get_light_level (float light)
template<typename RatingIterator >
std::string get_labeled_bar (const double val, const int width, const std::string &label, RatingIterator begin, RatingIterator end)
template<typename _Container >
std::string enumerate_as_string (const _Container &values, enumeration_conjunction conj=enumeration_conjunction::and_)
template<typename _FIter , typename F >
std::string enumerate_as_string (_FIter first, _FIter last, F string_for, enumeration_conjunction conj=enumeration_conjunction::and_)
std::string get_labeled_bar (double val, int width, const std::string &label, char c)
void draw_tab (const catacurses::window &w, int iOffsetX, const std::string &sText, bool bSelected)
void draw_subtab (const catacurses::window &w, int iOffsetX, const std::string &sText, bool bSelected, bool bDecorate=true, bool bDisabled=false)
void draw_tabs (const catacurses::window &, const std::vector< std::string > &tab_texts, size_t current_tab)
void draw_tabs (const catacurses::window &, const std::vector< std::string > &tab_texts, const std::string &current_tab)
template<typename TabList , typename CurrentTab , typename = std::enable_if_t< std::is_same<CurrentTab, std::remove_const_t<typename TabList::value_type::first_type>>::value>>
void draw_tabs (const catacurses::window &w, const TabList &tab_list, const CurrentTab &current_tab)
template<typename TabList , typename TabKeys , typename CurrentTab , typename = std::enable_if_t< std::is_same<CurrentTab, std::remove_const_t<typename TabList::value_type::first_type>>::value>>
void draw_tabs (const catacurses::window &w, const TabList &tab_list, const TabKeys &keys, const CurrentTab &current_tab)
void draw_scrollbar (const catacurses::window &window, int iCurrentLine, int iContentHeight, int iNumLines, const point &offset=point_zero, nc_color bar_color=c_white, bool bDoNotScrollToEnd=false)
Draw a scrollbar (Legacy function, use class scrollbar instead!)
void calcStartPos (int &iStartPos, int iCurrentLine, int iContentHeight, int iNumEntries)
std::string format_volume (const units::volume &volume)
Convert, round up and format a volume.
std::string format_volume (const units::volume &volume, int width, bool *out_truncated, double *out_value)
Convert, clamp, round up and format a volume, taking into account the specified width (0 for unlimited space), optionally returning a flag that indicate if the value was truncated to fit the width, optionally returning the formatted value as double.
std::string format_money (int cents)
int get_terminal_width ()
Get the width in font glyphs of the drawing screen.
int get_terminal_height ()
Get the height in font glyphs of the drawing screen.
bool is_draw_tiles_mode ()
Check whether we're in tile drawing mode.
void refresh_display ()
Make changes made to the display visible to the user immediately.
template<typename F >
std::string colorize_symbols (const std::string &str, F color_of)
Assigns a custom color to each symbol.
Macro Definition Documentation
BORDER_COLOR
#define BORDER_COLOR c_light_gray
Definition at line 135 of file output.h.
CATA_SRC_OUTPUT_H
#define CATA_SRC_OUTPUT_H
Definition at line 3 of file output.h.
LINE_OOXX
#define LINE_OOXX 4194411
Definition at line 43 of file output.h.
LINE_OOXX_C
#define LINE_OOXX_C 0xa4
Definition at line 55 of file output.h.
LINE_OOXX_S
#define LINE_OOXX_S "┐"
Definition at line 67 of file output.h.
LINE_OOXX_UNICODE
#define LINE_OOXX_UNICODE 0x2510
Definition at line 79 of file output.h.
LINE_OXOX
#define LINE_OXOX 4194417
Definition at line 40 of file output.h.
LINE_OXOX_C
#define LINE_OXOX_C 0xa1
Definition at line 52 of file output.h.
LINE_OXOX_S
#define LINE_OXOX_S "─"
Definition at line 64 of file output.h.
LINE_OXOX_UNICODE
#define LINE_OXOX_UNICODE 0x2500
Definition at line 76 of file output.h.
LINE_OXXO
#define LINE_OXXO 4194412
Definition at line 42 of file output.h.
LINE_OXXO_C
#define LINE_OXXO_C 0xa3
Definition at line 54 of file output.h.
LINE_OXXO_S
#define LINE_OXXO_S "┌"
Definition at line 66 of file output.h.
LINE_OXXO_UNICODE
#define LINE_OXXO_UNICODE 0x250C
Definition at line 78 of file output.h.
LINE_OXXX
#define LINE_OXXX 4194423
Definition at line 48 of file output.h.
LINE_OXXX_C
#define LINE_OXXX_C 0xa9
Definition at line 60 of file output.h.
LINE_OXXX_S
#define LINE_OXXX_S "┬"
Definition at line 72 of file output.h.
LINE_OXXX_UNICODE
#define LINE_OXXX_UNICODE 0x252C
Definition at line 84 of file output.h.
LINE_XOOX
#define LINE_XOOX 4194410
Definition at line 44 of file output.h.
LINE_XOOX_C
#define LINE_XOOX_C 0xa5
Definition at line 56 of file output.h.
LINE_XOOX_S
#define LINE_XOOX_S "┘"
Definition at line 68 of file output.h.
LINE_XOOX_UNICODE
#define LINE_XOOX_UNICODE 0x2518
Definition at line 80 of file output.h.
LINE_XOXO
#define LINE_XOXO 4194424
Definition at line 39 of file output.h.
LINE_XOXO_C
#define LINE_XOXO_C 0xa0
Definition at line 51 of file output.h.
LINE_XOXO_S
#define LINE_XOXO_S "│"
Definition at line 63 of file output.h.
LINE_XOXO_UNICODE
#define LINE_XOXO_UNICODE 0x2502
Definition at line 75 of file output.h.
LINE_XOXX
#define LINE_XOXX 4194421
Definition at line 47 of file output.h.
LINE_XOXX_C
#define LINE_XOXX_C 0xa8
Definition at line 59 of file output.h.
LINE_XOXX_S
#define LINE_XOXX_S "┤"
Definition at line 71 of file output.h.
LINE_XOXX_UNICODE
#define LINE_XOXX_UNICODE 0x2524
Definition at line 83 of file output.h.
LINE_XXOO
#define LINE_XXOO 4194413
Definition at line 41 of file output.h.
LINE_XXOO_C
#define LINE_XXOO_C 0xa2
Definition at line 53 of file output.h.
LINE_XXOO_S
#define LINE_XXOO_S "└"
Definition at line 65 of file output.h.
LINE_XXOO_UNICODE
#define LINE_XXOO_UNICODE 0x2514
Definition at line 77 of file output.h.
LINE_XXOX
#define LINE_XXOX 4194422
Definition at line 46 of file output.h.
LINE_XXOX_C
#define LINE_XXOX_C 0xa7
Definition at line 58 of file output.h.
LINE_XXOX_S
#define LINE_XXOX_S "┴"
Definition at line 70 of file output.h.
LINE_XXOX_UNICODE
#define LINE_XXOX_UNICODE 0x2534
Definition at line 82 of file output.h.
LINE_XXXO
#define LINE_XXXO 4194420
Definition at line 45 of file output.h.
LINE_XXXO_C
#define LINE_XXXO_C 0xa6
Definition at line 57 of file output.h.
LINE_XXXO_S
#define LINE_XXXO_S "├"
Definition at line 69 of file output.h.
LINE_XXXO_UNICODE
#define LINE_XXXO_UNICODE 0x251C
Definition at line 81 of file output.h.
LINE_XXXX
#define LINE_XXXX 4194414
Definition at line 49 of file output.h.
LINE_XXXX_C
#define LINE_XXXX_C 0xaa
Definition at line 61 of file output.h.
LINE_XXXX_S
#define LINE_XXXX_S "┼"
Definition at line 73 of file output.h.
LINE_XXXX_UNICODE
#define LINE_XXXX_UNICODE 0x253C
Definition at line 85 of file output.h.
Enumeration Type Documentation
enumeration_conjunction
enum class enumeration_conjunction strong
Enumerator
none
and_
or_
newline
arrow
Definition at line 666 of file output.h.
{
    none,
    and_,
    or_,
    newline,
    arrow
};
item_filter_type
enum class item_filter_type : int strong
Enumerator
FIRST
FILTER
LOW_PRIORITY
HIGH_PRIORITY
Definition at line 574 of file output.h.
                            : int {
    FIRST = 1, // used for indexing into tables
    FILTER = 1,
    LOW_PRIORITY = 2,
    HIGH_PRIORITY = 3
};
PopupFlags
enum PopupFlags
Enumerator
PF_NONE
PF_GET_KEY
PF_ON_TOP
PF_FULLSCREEN
Definition at line 492 of file output.h.
                {
    PF_NONE        = 0,
    PF_GET_KEY     = 1 << 0,
    PF_ON_TOP      = 1 << 2,
    PF_FULLSCREEN  = 1 << 3,
};
Function Documentation
calcStartPos()
void calcStartPos (int & iStartPos, int iCurrentLine, int iContentHeight, int iNumEntries)
Definition at line 1507 of file output.cpp.
{
    if( iNumEntries <= iContentHeight ) {
        iStartPos = 0;
    } else if( get_option<bool>( "MENU_SCROLL" ) ) {
        iStartPos = iCurrentLine - ( iContentHeight - 1 ) / 2;
        if( iStartPos < 0 ) {
            iStartPos = 0;
        } else if( iStartPos + iContentHeight > iNumEntries ) {
            iStartPos = iNumEntries - iContentHeight;
        }
    } else {
        if( iCurrentLine < iStartPos ) {
            iStartPos = iCurrentLine;
        } else if( iCurrentLine >= iStartPos + iContentHeight ) {
            iStartPos = 1 + iCurrentLine - iContentHeight;
        }
    }
}
Referenced by talk_function::display_and_choose_opts(), worldfactory::draw_mod_list(), game::list_items(), game::list_monsters(), select_crafting_recipe(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), uilist::show(), options_manager::show(), safemode::show(), color_manager::show_gui(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and game::zones_manager().
center_print()
void center_print (const catacurses::window & w, int y, const nc_color & FG, const std::string & text)
Definition at line 446 of file output.cpp.
{
    int window_width = getmaxx( w );
    int string_width = utf8_width( text, true );
    int x;
    if( string_width >= window_width ) {
        x = 0;
    } else {
        x = ( window_width - string_width ) / 2;
    }
    const int available_width = std::max( 1, window_width - x );
    trim_and_print( w, point( x, y ), available_width, FG, text );
}
References catacurses::getmaxx(), trim_and_print(), and utf8_width().
Referenced by game::cleanup_at_end(), draw_bionics_tab(), draw_bionics_titlebar(), draw_border(), inventory_selector::draw_columns(), draw_effects_tab(), draw_encumbrance_tab(), worldfactory::draw_mod_list(), draw_skills_tab(), draw_speed_tab(), draw_stats_tab(), draw_traits_tab(), game::look_around(), main_menu::new_character_tab(), pickup::pick_up(), main_menu::print_menu(), live_view::show(), diary::show_diary_ui(), snake_game::snake_over(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and editmap::update_view_with_help().
colorize_symbols()
template<typename F > std::string colorize_symbols (const std::string & str, F color_of)
Assigns a custom color to each symbol.
Parameters
str String to colorize symbols in
color_of Function that accepts symbols (std::string::value_type) and returns colors.
Returns
Colorized string.
Definition at line 1022 of file output.h.
{
    std::string res;
    nc_color prev_color = c_unset;
    const auto closing_tag = [ &res, prev_color ]() {
        if( prev_color != c_unset ) {
            res += "</color>";
        }
    };
    for( const auto &elem : str ) {
        const nc_color new_color = color_of( elem );
        if( prev_color != new_color ) {
            closing_tag();
            res += "<color_" + get_all_colors().get_name( new_color ) + ">";
            prev_color = new_color;
        }
        res += elem;
    }
    closing_tag();
    return res;
}
References c_unset, get_all_colors(), and color_manager::get_name().
Referenced by game_menus::inv::swap_letters().
draw_border()
void draw_border (const catacurses::window & w, nc_color border_color = BORDER_COLOR, const std::string & title = "", nc_color title_color = c_light_red)
Definition at line 575 of file output.cpp.
{
    wattron( w, border_color );
    wborder( w, LINE_XOXO, LINE_XOXO, LINE_OXOX, LINE_OXOX,
             LINE_OXXO, LINE_OOXX, LINE_XXOO, LINE_XOOX );
    wattroff( w, border_color );
    if( !title.empty() ) {
        center_print( w, 0, title_color, title );
    }
}
References center_print(), LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, PATH_INFO::title(), catacurses::wattroff(), catacurses::wattron(), and catacurses::wborder().
Referenced by game::cleanup_at_end(), Character::conduct_blood_analysis(), decorate_panel(), player_morale::display(), talk_function::display_and_choose_opts(), veh_interact::display_grid(), help::display_help(), input_context::display_menu(), main_menu::display_text(), string_input_popup::draw(), draw_borders_external(), inventory_selector::draw_frame(), draw_grid(), lightson_game::draw_level(), game::draw_minimap(), target_ui::draw_ui_window(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::look_around(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), player::power_bionics(), player::power_mutations_ui(), snake_game::print_header(), dialogue_window::print_header(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), computer_session::refresh(), advanced_inventory::refresh_minimap(), defense_game::refresh_setup(), scrollable_text(), overmap_ui::search(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), Messages::dialog::show(), uilist::show(), robot_finds_kitten::show(), query_popup::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), color_manager::show_gui(), trading_window::show_item_data(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), trading_window::update_win(), and basecamp::worker_assignment_ui().
draw_border_below_tabs()
void draw_border_below_tabs (const catacurses::window & w, nc_color border_color = BORDER_COLOR)
Definition at line 587 of file output.cpp.
{
    int width = getmaxx( w );
    int height = getmaxy( w );
    for( int i = 1; i < width - 1; i++ ) {
        mvwputch( w, point( i, height - 1 ), border_color, LINE_OXOX );
    }
    for( int i = 3; i < height - 1; i++ ) {
        mvwputch( w, point( 0, i ), border_color, LINE_XOXO );
        mvwputch( w, point( width - 1, i ), border_color, LINE_XOXO );
    }
    mvwputch( w, point( 0, height - 1 ), border_color, LINE_XXOO ); // |_
    mvwputch( w, point( width - 1, height - 1 ), border_color, LINE_XOOX ); // _|
}
References catacurses::getmaxx(), catacurses::getmaxy(), LINE_OXOX, LINE_XOOX, LINE_XOXO, LINE_XXOO, and mvwputch().
Referenced by faction_manager::display(), draw_character_tabs(), worldfactory::draw_empty_worldgen_tabs(), worldfactory::draw_worldgen_tabs(), game::list_missions(), and show_scores_ui().
draw_custom_border()
void draw_custom_border (const catacurses::window & w, catacurses::chtype ls = 1, catacurses::chtype rs = 1, catacurses::chtype ts = 1, catacurses::chtype bs = 1, catacurses::chtype tl = 1, catacurses::chtype tr = 1, catacurses::chtype bl = 1, catacurses::chtype br = 1, nc_color FG = BORDER_COLOR, const point & pos = point_zero, int height = 0, int width = 0)
Definition at line 524 of file output.cpp.
{
    wattron( w, FG );
    height = ( height == 0 ) ? getmaxy( w ) - pos.y : height;
    width = ( width == 0 ) ? getmaxx( w ) - pos.x : width;
    for( int j = pos.y; j < height + pos.y - 1; j++ ) {
        if( ls > 0 ) {
            mvwputch( w, point( pos.x, j ), c_light_gray, ( ls > 1 ) ? ls : LINE_XOXO ); // |
        }
        if( rs > 0 ) {
            mvwputch( w, point( pos.x + width - 1, j ), c_light_gray, ( rs > 1 ) ? rs : LINE_XOXO ); // |
        }
    }
    for( int j = pos.x; j < width + pos.x - 1; j++ ) {
        if( ts > 0 ) {
            mvwputch( w, point( j, pos.y ), c_light_gray, ( ts > 1 ) ? ts : LINE_OXOX ); // --
        }
        if( bs > 0 ) {
            mvwputch( w, point( j, pos.y + height - 1 ), c_light_gray, ( bs > 1 ) ? bs : LINE_OXOX ); // --
        }
    }
    if( tl > 0 ) {
        mvwputch( w, pos, c_light_gray, ( tl > 1 ) ? tl : LINE_OXXO ); // |^
    }
    if( tr > 0 ) {
        mvwputch( w, pos + point( -1 + width, 0 ), c_light_gray, ( tr > 1 ) ? tr : LINE_OOXX ); // ^|
    }
    if( bl > 0 ) {
        mvwputch( w, pos + point( 0, -1 + height ), c_light_gray, ( bl > 1 ) ? bl : LINE_XXOO ); // |_
    }
    if( br > 0 ) {
        mvwputch( w, pos + point( -1 + width, -1 + height ), c_light_gray,
                  ( br > 1 ) ? br : LINE_XOOX ); // _|
    }
    wattroff( w, FG );
}
References c_light_gray, catacurses::getmaxx(), catacurses::getmaxy(), LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, mvwputch(), catacurses::wattroff(), catacurses::wattron(), point::x, and point::y.
Referenced by draw_item_info(), game::list_items(), game::list_monsters(), pickup::pick_up(), and minesweeper_game::start_game().
draw_item_filter_rules()
void draw_item_filter_rules (const catacurses::window & win, int starty, int height, item_filter_type type)
Write some tips (such as precede items with - to exclude them) onto the window.
Parameters
win Window we are drawing in
starty Where to start relative to the top of the window.
height Every row from starty to starty + height - 1 will be cleared before printing the rules.
type Filter to use when drawing
Definition at line 810 of file output.cpp.
{
    // Clear every row, but the leftmost/rightmost pixels intact.
    const int len = getmaxx( win ) - 2;
    for( int i = 0; i < height; i++ ) {
        mvwprintz( win, point( 1, starty + i ), c_black, std::string( len, ' ' ) );
    }
    // Not static so that language changes are correctly handled
    const std::array<std::string, 3> intros = {{
            _( "Type part of an item's name to filter it." ),
            _( "Type part of an item's name to move nearby items to the bottom." ),
            _( "Type part of an item's name to move nearby items to the top." )
        }
    };
    const int tab_idx = static_cast<int>( type ) - static_cast<int>( item_filter_type::FIRST );
    starty += 1 + fold_and_print( win, point( 1, starty ), len, c_white, intros[tab_idx] );
    starty += fold_and_print( win, point( 1, starty ), len, c_white,
                              // NOLINTNEXTLINE(cata-text-style): literal comma
                              _( "Separate multiple items with [<color_yellow>,</color>]." ) );
    starty += 1 + fold_and_print( win, point( 1, starty ), len, c_white,
                                  //~ An example of how to separate multiple items with a comma when filtering items.
                                  _( "Example: back,flash,aid, ,band" ) ); // NOLINT(cata-text-style): literal comma
    if( type == item_filter_type::FILTER ) {
        starty += fold_and_print( win, point( 1, starty ), len, c_white,
                                  _( "To exclude items, place [<color_yellow>-</color>] in front." ) );
        starty += 1 + fold_and_print( win, point( 1, starty ), len, c_white,
                                      //~ An example of how to exclude items with - when filtering items.
                                      _( "Example: -pipe,-chunk,-steel" ) );
    }
    starty += fold_and_print( win, point( 1, starty ), len, c_white,
                              _( "Search [<color_yellow>c</color>]ategory, [<color_yellow>m</color>]aterial, "
                                 "[<color_yellow>q</color>]uality, [<color_yellow>n</color>]otes or "
                                 "[<color_yellow>d</color>]isassembled components." ) );
    fold_and_print( win, point( 1, starty ), len, c_white,
                    //~ An example of how to filter items based on category or material.
                    _( "Examples: c:food,m:iron,q:hammering,n:toolshelf,d:pipe" ) );
    wnoutrefresh( win );
}
References _, c_black, c_white, FILTER, FIRST, fold_and_print(), catacurses::getmaxx(), mvwprintz(), type, and catacurses::wnoutrefresh().
Referenced by advanced_inventory::display(), game::list_items(), and loot_options::query_loot().
draw_item_info() [1/3]
input_event draw_item_info (const catacurses::window & win, item_info_data & data)
Definition at line 944 of file output.cpp.
{
    return draw_item_info( [&]() -> catacurses::window {
        return win;
    }, data );
}
References draw_item_info().
draw_item_info() [2/3]
input_event draw_item_info (const std::function< catacurses::window()> & init_window, item_info_data & data)
Definition at line 951 of file output.cpp.
{
    std::string buffer;
    int line_num = data.use_full_win || data.without_border ? 0 : 1;
    if( !data.get_item_name().empty() ) {
        buffer += data.get_item_name() + "\n";
    }
    // If type name is set, and not already contained in item name, output it too
    if( !data.get_type_name().empty() &&
        data.get_item_name().find( data.get_type_name() ) == std::string::npos ) {
        buffer += data.get_type_name() + "\n";
    }
    for( unsigned int i = 0; i < data.padding; i++ ) {
        buffer += "\n";
    }
    buffer += format_item_info( data.get_item_display(), data.get_item_compare() );
    const int b = data.use_full_win ? 0 : ( data.without_border ? 1 : 2 );
    catacurses::window win;
    int width = 0;
    int height = 0;
    std::vector<std::string> folded;
    const auto init = [&]() {
        win = init_window();
        width = getmaxx( win ) - ( data.use_full_win ? 1 : b * 2 );
        height = getmaxy( win ) - ( data.use_full_win ? 0 : 2 );
        folded = foldstring( buffer, width - 1 );
        if( *data.ptr_selected < 0 ) {
            *data.ptr_selected = 0;
        } else if( height < 0 || folded.size() < static_cast<size_t>( height ) ) {
            *data.ptr_selected = 0;
        } else if( static_cast<size_t>( *data.ptr_selected + height ) >= folded.size() ) {
            *data.ptr_selected = static_cast<int>( folded.size() ) - height;
        }
    };
    const auto redraw = [&]() {
        werase( win );
        for( int line = 0; line < height; ++line ) {
            const int idx = *data.ptr_selected + line;
            if( idx >= 0 && static_cast<size_t>( idx ) < folded.size() ) {
                if( folded[idx] == "--" ) {
                    for( int x = 0; x < width; x++ ) {
                        mvwputch( win, point( b + x, line_num + line ), c_dark_gray, LINE_OXOX );
                    }
                } else {
                    trim_and_print( win, point( b, line_num + line ), width - 1, c_light_gray, folded[idx] );
                }
            }
        }
        draw_scrollbar( win, *data.ptr_selected, height, folded.size(),
                        point( data.scrollbar_left ? 0 : getmaxx( win ) - 1,
                               ( data.without_border && data.use_full_win ? 0 : 1 ) ), BORDER_COLOR, true );
        if( !data.without_border ) {
            draw_custom_border( win, buffer.empty() );
        }
        wnoutrefresh( win );
    };
    if( data.without_getch ) {
        init();
        redraw();
        return input_event();
    }
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        init();
        ui.position_from_window( win );
    } );
    ui.mark_resize();
    ui.on_redraw( [&]( const ui_adaptor & ) {
        redraw();
    } );
    input_context ctxt;
    if( data.handle_scrolling ) {
        ctxt.register_action( "PAGE_UP" );
        ctxt.register_action( "PAGE_DOWN" );
    }
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    if( data.any_input ) {
        ctxt.register_action( "ANY_INPUT" );
    }
    std::string action;
    bool exit = false;
    while( !exit ) {
        ui_manager::redraw();
        action = ctxt.handle_input();
        if( data.handle_scrolling && action == "PAGE_UP" ) {
            if( *data.ptr_selected > 0 ) {
                --*data.ptr_selected;
            }
        } else if( data.handle_scrolling && action == "PAGE_DOWN" ) {
            if( *data.ptr_selected < 0 ||
                ( height > 0 && static_cast<size_t>( *data.ptr_selected + height ) < folded.size() ) ) {
                ++*data.ptr_selected;
            }
        } else if( action == "CONFIRM" || action == "QUIT" ) {
            exit = true;
        } else if( data.any_input && action == "ANY_INPUT" && !ctxt.get_raw_input().sequence.empty() ) {
            exit = true;
        }
    }
    return ctxt.get_raw_input();
}
References action, item_info_data::any_input, b, BORDER_COLOR, c_dark_gray, c_light_gray, draw_custom_border(), draw_scrollbar(), foldstring(), format_item_info(), item_info_data::get_item_compare(), item_info_data::get_item_display(), item_info_data::get_item_name(), input_context::get_raw_input(), item_info_data::get_type_name(), catacurses::getmaxx(), catacurses::getmaxy(), input_context::handle_input(), item_info_data::handle_scrolling, init_window(), line(), LINE_OXOX, mvwputch(), item_info_data::padding, item_info_data::ptr_selected, ui_manager::redraw(), input_context::register_action(), item_info_data::scrollbar_left, input_event::sequence, trim_and_print(), item_info_data::use_full_win, catacurses::werase(), item_info_data::without_border, item_info_data::without_getch, and catacurses::wnoutrefresh().
draw_item_info() [3/3]
input_event draw_item_info (int iLeft, int iWidth, int iTop, int iHeight, item_info_data & data)
Definition at line 793 of file output.cpp.
{
    catacurses::window win =
        catacurses::newwin( iHeight, iWidth,
                            point( iLeft, iTop ) );
#if defined(TILES)
    clear_window_area( win );
#endif // TILES
    wclear( win );
    wnoutrefresh( win );
    const input_event result = draw_item_info( win, data );
    return result;
}
References draw_item_info(), catacurses::newwin(), catacurses::wclear(), and catacurses::wnoutrefresh().
Referenced by advanced_inventory::action_examine(), game_menus::inv::compare(), draw_item_info(), game::list_items(), pickup::pick_up(), examine_item_menu::run(), select_crafting_recipe(), and trading_window::show_item_data().
draw_scrollbar()
void draw_scrollbar (const catacurses::window & window, const int iCurrentLine, const int iContentHeight, const int iNumLines, const point & offset, nc_color bar_color, const bool bDoNotScrollToEnd)
Draw a scrollbar (Legacy function, use class scrollbar instead!)
Parameters
window Pointer of window to draw on
iCurrentLine The starting line or currently selected line out of the iNumLines lines
iContentHeight Height of the scrollbar
iNumLines Total number of lines
offset Point indicating drawing offset
bar_color Default line color
bDoNotScrollToEnd True if the last (iContentHeight-1) lines cannot be a start position or be selected If false, iCurrentLine can be from 0 to iNumLines - 1. If true, iCurrentLine can be at most iNumLines - iContentHeight.
Definition at line 1314 of file output.cpp.
{
    scrollbar()
    .offset_x( offset.x )
    .offset_y( offset.y )
    .content_size( iNumLines )
    .viewport_pos( iCurrentLine )
    .viewport_size( iContentHeight )
    .slot_color( bar_color )
    .scroll_to_last( !bDoNotScrollToEnd )
    .apply( window );
}
References scrollbar::apply(), scrollbar::content_size(), scrollbar::offset_x(), scrollbar::offset_y(), scrollbar::scroll_to_last(), scrollbar::slot_color(), scrollbar::viewport_pos(), scrollbar::viewport_size(), point::x, and point::y.
Referenced by faction_manager::display(), player_morale::display(), input_context::display_menu(), main_menu::display_text(), draw_item_info(), worldfactory::draw_mod_list(), draw_skills_tab(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_missions(), game::list_monsters(), player::power_bionics(), player::power_mutations_ui(), character_display::print_encumbrance(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), select_crafting_recipe(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), color_manager::show_gui(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
draw_subtab()
void draw_subtab (const catacurses::window & w, int iOffsetX, const std::string & sText, bool bSelected, bool bDecorate = true, bool bDisabled = false)
Definition at line 1247 of file output.cpp.
{
    int iOffsetXRight = iOffsetX + utf8_width( sText ) + 1;
    if( !bDisabled ) {
        mvwprintz( w, point( iOffsetX + 1, 0 ), ( bSelected ) ? h_light_gray : c_light_gray, sText );
    } else {
        mvwprintz( w, point( iOffsetX + 1, 0 ), ( bSelected ) ? h_dark_gray : c_dark_gray, sText );
    }
    if( bSelected ) {
        if( !bDisabled ) {
            mvwputch( w, point( iOffsetX - bDecorate, 0 ),      h_light_gray, '<' );
            mvwputch( w, point( iOffsetXRight + bDecorate, 0 ), h_light_gray, '>' );
        } else {
            mvwputch( w, point( iOffsetX - bDecorate, 0 ),      h_dark_gray, '<' );
            mvwputch( w, point( iOffsetXRight + bDecorate, 0 ), h_dark_gray, '>' );
        }
        for( int i = iOffsetX + 1; bDecorate && i < iOffsetXRight; i++ ) {
            mvwputch( w, point( i, 1 ), c_black, ' ' );
        }
    }
}
References c_black, c_dark_gray, c_light_gray, h_dark_gray, h_light_gray, mvwprintz(), mvwputch(), and utf8_width().
Referenced by veh_interact::display_list(), talk_function::draw_camp_tabs(), and draw_recipe_subtabs().
draw_tab()
void draw_tab (const catacurses::window & w, int iOffsetX, const std::string & sText, bool bSelected)
Definition at line 1215 of file output.cpp.
{
    int iOffsetXRight = iOffsetX + utf8_width( sText ) + 1;
    mvwputch( w, point( iOffsetX, 0 ),      c_light_gray, LINE_OXXO ); // |^
    mvwputch( w, point( iOffsetXRight, 0 ), c_light_gray, LINE_OOXX ); // ^|
    mvwputch( w, point( iOffsetX, 1 ),      c_light_gray, LINE_XOXO ); // |
    mvwputch( w, point( iOffsetXRight, 1 ), c_light_gray, LINE_XOXO ); // |
    mvwprintz( w, point( iOffsetX + 1, 1 ), ( bSelected ) ? h_light_gray : c_light_gray, sText );
    for( int i = iOffsetX + 1; i < iOffsetXRight; i++ ) {
        mvwputch( w, point( i, 0 ), c_light_gray, LINE_OXOX );  // -
    }
    if( bSelected ) {
        mvwputch( w, point( iOffsetX - 1, 1 ),      h_light_gray, '<' );
        mvwputch( w, point( iOffsetXRight + 1, 1 ), h_light_gray, '>' );
        for( int i = iOffsetX + 1; i < iOffsetXRight; i++ ) {
            mvwputch( w, point( i, 2 ), c_black, ' ' );
        }
        mvwputch( w, point( iOffsetX, 2 ),      c_light_gray, LINE_XOOX ); // _|
        mvwputch( w, point( iOffsetXRight, 2 ), c_light_gray, LINE_XXOO ); // |_
    } else {
        mvwputch( w, point( iOffsetX, 2 ),      c_light_gray, LINE_XXOX ); // _|_
        mvwputch( w, point( iOffsetXRight, 2 ), c_light_gray, LINE_XXOX ); // _|_
    }
}
References c_black, c_light_gray, h_light_gray, LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, LINE_XXOX, mvwprintz(), mvwputch(), and utf8_width().
Referenced by draw_recipe_tabs(), and draw_tabs().
draw_tabs() [1/4]
void draw_tabs (const catacurses::window & w, const std::vector< std::string > & tab_texts, const std::string & current_tab)
Definition at line 1294 of file output.cpp.
{
    auto it = std::find( tab_texts.begin(), tab_texts.end(), current_tab );
    assert( it != tab_texts.end() );
    draw_tabs( w, tab_texts, it - tab_texts.begin() );
}
References draw_tabs(), and detail::find().
draw_tabs() [2/4]
void draw_tabs (const catacurses::window & w, const std::vector< std::string > & tab_texts, size_t current_tab)
Definition at line 1274 of file output.cpp.
{
    int width = getmaxx( w );
    for( int i = 0; i < width; i++ ) {
        mvwputch( w, point( i, 2 ), BORDER_COLOR, LINE_OXOX ); // -
    }
    mvwputch( w, point( 0, 2 ), BORDER_COLOR, LINE_OXXO ); // |^
    mvwputch( w, point( width - 1, 2 ), BORDER_COLOR, LINE_OOXX ); // ^|
    const int tab_step = 3;
    int x = 2;
    for( size_t i = 0; i < tab_texts.size(); ++i ) {
        const std::string &tab_text = tab_texts[i];
        draw_tab( w, x, tab_text, i == current_tab );
        x += utf8_width( tab_text ) + tab_step;
    }
}
References BORDER_COLOR, draw_tab(), catacurses::getmaxx(), LINE_OOXX, LINE_OXOX, LINE_OXXO, mvwputch(), and utf8_width().
Referenced by faction_manager::display(), draw_bionics_tabs(), draw_character_tabs(), worldfactory::draw_empty_worldgen_tabs(), draw_recipe_tabs(), draw_tabs(), worldfactory::draw_worldgen_tabs(), game::list_missions(), and show_scores_ui().
draw_tabs() [3/4]
template<typename TabList , typename CurrentTab , typename = std::enable_if_t< std::is_same<CurrentTab, std::remove_const_t<typename TabList::value_type::first_type>>::value>> void draw_tabs (const catacurses::window & w, const TabList & tab_list, const CurrentTab & current_tab)
Definition at line 789 of file output.h.
{
    std::vector<std::string> tab_text;
    std::transform( tab_list.begin(), tab_list.end(), std::back_inserter( tab_text ),
    []( const typename TabList::value_type & pair ) {
        return pair.second;
    } );
    auto current_tab_it = std::find_if( tab_list.begin(), tab_list.end(),
    [&current_tab]( const typename TabList::value_type & pair ) {
        return pair.first == current_tab;
    } );
    assert( current_tab_it != tab_list.end() );
    draw_tabs( w, tab_text, std::distance( tab_list.begin(), current_tab_it ) );
}
References draw_tabs(), and iexamine::transform().
draw_tabs() [4/4]
template<typename TabList , typename TabKeys , typename CurrentTab , typename = std::enable_if_t< std::is_same<CurrentTab, std::remove_const_t<typename TabList::value_type::first_type>>::value>> void draw_tabs (const catacurses::window & w, const TabList & tab_list, const TabKeys & keys, const CurrentTab & current_tab)
Definition at line 810 of file output.h.
{
    std::vector<typename TabList::value_type> ordered_tab_list;
    for( const auto &key : keys ) {
        auto it = tab_list.find( key );
        assert( it != tab_list.end() );
        ordered_tab_list.push_back( *it );
    }
    draw_tabs( w, ordered_tab_list, current_tab );
}
References draw_tabs().
enumerate_as_string() [1/2]
template<typename _FIter , typename F > std::string enumerate_as_string (_FIter first, _FIter last, F string_for, enumeration_conjunction conj = enumeration_conjunction::and_)
Returns
String containing enumerated elements in format: "a, b, c, ..., and z". Uses the Oxford comma.
Parameters
first Iterator pointing to the first element.
last Iterator pointing to the last element.
string_for Function that accepts an element and returns a representing string. May return an empty string to omit the element.
conj Choose how to separate the last elements.
Definition at line 734 of file output.h.
{
    std::vector<std::string> values;
    values.reserve( static_cast<size_t>( std::distance( first, last ) ) );
    for( _FIter iter = first; iter != last; ++iter ) {
        const std::string str( string_for( *iter ) );
        if( !str.empty() ) {
            values.push_back( str );
        }
    }
    return enumerate_as_string( values, conj );
}
References enumerate_as_string(), and last.
enumerate_as_string() [2/2]
template<typename _Container > std::string enumerate_as_string (const _Container & values, enumeration_conjunction conj = enumeration_conjunction::and_)
Returns
String containing enumerated elements in format: "a, b, c, ..., and z". Uses the Oxford comma.
Parameters
values A vector of strings
conj Choose how to separate the last elements.
Definition at line 680 of file output.h.
{
    const std::string final_separator = [&]() {
        switch( conj ) {
            case enumeration_conjunction::none:
                return _( ", " );
            case enumeration_conjunction::and_:
                return ( values.size() > 2 ? _( ", and " ) : _( " and " ) );
            case enumeration_conjunction::or_:
                return ( values.size() > 2 ? _( ", or " ) : _( " or " ) );
            case enumeration_conjunction::newline:
                return "\n";
            case enumeration_conjunction::arrow:
                return _( " > " );
        }
        debugmsg( "Unexpected conjunction" );
        return _( ", " );
    }
    ();
    const std::string separator = [&conj]() {
        switch( conj ) {
            case enumeration_conjunction::arrow:
                return _( " > " );
            default:
                return _( ", " );
        }
    }
    ();
    std::string res;
    for( auto iter = values.begin(); iter != values.end(); ++iter ) {
        if( iter != values.begin() ) {
            if( conj == enumeration_conjunction::newline ) {
                res += "\n";
            } else if( std::next( iter ) == values.end() ) {
                res += final_separator;
            } else {
                res += separator;
            }
        }
        res += *iter;
    }
    return res;
}
References _, and_, arrow, debugmsg, newline, none, and or_.
Referenced by item::basic_info(), item::bionic_info(), anonymous_namespace{armor_layers.cpp}::body_part_names(), item::book_info(), build_bionic_poweronly_string(), iuse::camera(), Character::can_install_bionics(), iuse_transform::can_use(), vpart_info::check(), enchantment::check(), map_bash_info::check(), harvest_list::check_consistency(), item::combat_info(), item::component_info(), component_list_string(), item::components_to_string(), construction_menu(), item::contents_info(), harvest_list::describe(), disassemble_inventory_preset::disassemble_inventory_preset(), item::disassembly_info(), effect::disp_desc(), avatar::do_read(), game::dump_stats(), enumerate_as_string(), character_martial_arts::enumerate_known_styles(), enumerate_objects_around_point(), enumerate_spell_data(), Character::enumerate_unmet_requirements(), map_data_common_t::extended_description(), Character::extended_description(), monster::extended_description(), game::extended_description(), item::final_info(), item::food_info(), input_context::get_conflicts(), ma_requirements::get_description(), monster::get_effect_status(), mod_ui::get_information(), repair_item_actor::get_name(), options_manager::cOpt::getDefaultText(), item::gun_info(), item::gunmod_info(), consume_drug_iuse::info(), deploy_furn_actor::info(), bandolier_actor::info(), ma_style_callback::key(), spell::list_targeted_monster_names(), player::mend_item(), iuse::note_bionics(), item_stack::only_item(), photo_def_for_camera_point(), npc::print_info(), monster::print_info(), print_ranged_chance(), game::prompt_dangerous_tile(), avatar::read(), item::repair_info(), iuse::report_grid_connections(), required_skills_as_string(), dependency_node::s_errors(), player::select_ammo(), select_crafting_recipe(), set_skills(), set_traits(), Character::short_description_parts(), skim_book_msg(), item::tool_info(), Character::visible_mutations(), and game::walk_move().
fold_and_print() [1/2]
template<typename ... Args> int fold_and_print (const catacurses::window & w, const point & begin, const int width, const nc_color & base_color, const char *const mes, Args &&... args) inline
Same as other fold_and_print, but does string formatting via string_format.
Definition at line 282 of file output.h.
{
    return fold_and_print( w, begin, width, base_color, string_format( mes,
                           std::forward<Args>( args )... ) );
}
References fold_and_print(), and string_format().
fold_and_print() [2/2]
int fold_and_print (const catacurses::window & w, const point & begin, int width, const nc_color & base_color, const std::string & text, char split = ' ')
Fold and print text in the given window.
The function handles color_tags and uses them while printing.
Parameters
w Window we are printing in
begin The (row, column) index on which to start.
width The width used to fold the text (see foldstring). width + begin_y should be less than the window width, otherwise the lines will be wrapped by the curses system, which defeats the purpose of using foldstring.
base_color The initially used color. This can be overridden using color tags.
text Actual message to print
split Character after string is folded
Returns
The number of lines of the formatted text (after folding). This may be larger than the height of the window.
Definition at line 299 of file output.cpp.
{
    nc_color color = base_color;
    std::vector<std::string> textformatted = foldstring( text, width, split );
    for( int line_num = 0; static_cast<size_t>( line_num ) < textformatted.size(); line_num++ ) {
        print_colored_text( w, begin + point( 0, line_num ), color, base_color,
                            textformatted[line_num] );
    }
    return textformatted.size();
}
References color(), foldstring(), and print_colored_text().
Referenced by check_encoding(), veh_interact::create_or_get_ui_adaptor(), debug_error_prompt(), veh_interact::display_details(), input_context::display_menu(), veh_interact::display_stats(), draw_bionics_info(), draw_bionics_titlebar(), draw_caravan_items(), draw_description(), draw_effects_info(), draw_encumbrance_info(), inventory_selector::draw_header(), draw_item_filter_rules(), help::draw_menu(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), draw_skills_info(), draw_sorting_indicator(), spellcasting_callback::draw_spell_info(), draw_spellbook_info(), draw_stats_info(), draw_traits_info(), ensure_term_size(), basecamp::faction_display(), faction::faction_display(), npc::faction_display(), fold_and_print(), game::list_missions(), main_menu::new_character_tab(), target_ui::panel_spell_info(), worldfactory::pick_world(), player::power_bionics(), player::power_mutations_ui(), game::print_fields_info(), game::print_graffiti_info(), monster::print_info(), main_menu::print_menu_items(), print_ranged_chance(), game::print_terrain_info(), construction::print_time(), vehicle::print_vparts_descs(), wish_item_callback::refresh(), overmap_ui::search(), select_crafting_recipe(), set_description(), set_points(), set_profession(), set_scenario(), set_stats(), set_traits(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), uilist::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), diary::show_diary_ui(), worldfactory::show_modselection_window(), show_mutations_titlebar(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), lightson_game::start_game(), trading_window::update_win(), and iexamine::vending().
fold_and_print_from() [1/2]
template<typename ... Args> int fold_and_print_from (const catacurses::window & w, const point & begin, const int width, const int begin_line, const nc_color & base_color, const char *const mes, Args &&... args) inline
Same as other fold_and_print_from, but does formatting via string_format.
Definition at line 312 of file output.h.
{
    return fold_and_print_from( w, begin, width, begin_line, base_color,
                                string_format( mes, std::forward<Args>( args )... ) );
}
References fold_and_print_from(), and string_format().
fold_and_print_from() [2/2]
int fold_and_print_from (const catacurses::window & w, const point & begin, int width, int begin_line, const nc_color & base_color, const std::string & text)
Like fold_and_print, but starts the output with the N-th line of the folded string.
This can be used for scrolling large texts. Parameters have the same meaning as for fold_and_print, the function therefor handles color_tags correctly.
Parameters
w Window we are printing in
begin The (row,column) index on which to start.
width The width used to fold the text (see foldstring). width + begin_y should be
begin_line The index of the first line (of the folded string) that is to be printed. The function basically removes all lines before this one and prints the remaining lines with fold_and_print.
base_color The initially used color. This can be overridden using color tags.
text Actual message to print
Returns
Same as fold_and_print: the number of lines of the text (after folding). This is always the same value, regardless of begin_line, it can be used to determine the maximal value for begin_line.
Definition at line 311 of file output.cpp.
{
    const int iWinHeight = getmaxy( w );
    std::stack<nc_color> color_stack;
    std::vector<std::string> textformatted = foldstring( text, width );
    for( int line_num = 0; static_cast<size_t>( line_num ) < textformatted.size(); line_num++ ) {
        if( line_num + begin.y - begin_line == iWinHeight ) {
            break;
        }
        if( line_num >= begin_line ) {
            wmove( w, begin + point( 0, -begin_line + line_num ) );
        }
        // split into colorable sections
        std::vector<std::string> color_segments = split_by_color( textformatted[line_num] );
        // for each section, get the color, and print it
        std::vector<std::string>::iterator it;
        for( it = color_segments.begin(); it != color_segments.end(); ++it ) {
            color_tag_parse_result::tag_type type = color_tag_parse_result::non_color_tag;
            if( !it->empty() && it->at( 0 ) == '<' ) {
                type = update_color_stack( color_stack, *it );
            }
            if( line_num >= begin_line ) {
                std::string l = *it;
                if( type != color_tag_parse_result::non_color_tag ) {
                    l = rm_prefix( l );
                }
                if( l != "--" ) { // -- is a separation line!
                    nc_color color = color_stack.empty() ? base_color : color_stack.top();
                    wprintz( w, color, l );
                } else {
                    for( int i = 0; i < width; i++ ) {
                        wputch( w, c_dark_gray, LINE_OXOX );
                    }
                }
            }
        }
    }
    return textformatted.size();
}
References c_dark_gray, color(), foldstring(), catacurses::getmaxy(), LINE_OXOX, color_tag_parse_result::non_color_tag, rm_prefix(), split_by_color(), type, update_color_stack(), catacurses::wmove(), wprintz(), wputch(), and point::y.
Referenced by main_menu::display_text(), game::extended_description(), fold_and_print_from(), insert_table(), ma_style_callback::key(), main_menu::print_menu(), print_ranged_chance(), debug_menu::effect_select_callback::refresh(), and set_skills().
foldstring()
std::vector< std::string > foldstring (const std::string & str, int width, char split = ' ')
Split the input text into separate lines and wrap long lines.
Each resulting line is at most width console cells long. The functions handles color_tags. Color tags are added to the resulting lines so each line can be independently printed.
Returns
A vector of lines, it may contain empty strings. Each entry is at most width console cells width.
Definition at line 68 of file output.cpp.
{
    std::vector<std::string> lines;
    if( width < 1 ) {
        lines.push_back( str );
        return lines;
    }
    std::stringstream sstr( str );
    std::string strline;
    std::vector<std::string> tags;
    while( std::getline( sstr, strline, '\n' ) ) {
        if( strline.empty() ) {
            // Special case empty lines as std::getline() sets failbit immediately
            // if the line is empty.
            lines.emplace_back();
        } else {
            std::string wrapped = word_rewrap( strline, width, split );
            std::stringstream swrapped( wrapped );
            std::string wline;
            while( std::getline( swrapped, wline, '\n' ) ) {
                // Ensure that each line is independently color-tagged
                // Re-add tags closed in the previous line
                const std::string rawwline = wline;
                if( !tags.empty() ) {
                    std::string swline;
                    for( const std::string &tag : tags ) {
                        swline += tag;
                    }
                    swline += wline;
                    wline = swline;
                }
                // Process the additional tags in the current line
                const std::vector<size_t> tags_pos = get_tag_positions( rawwline );
                for( const size_t tag_pos : tags_pos ) {
                    if( tag_pos + 1 < rawwline.size() && rawwline[tag_pos + 1] == '/' ) {
                        if( !tags.empty() ) {
                            tags.pop_back();
                        }
                    } else {
                        auto tag_end = rawwline.find( '>', tag_pos );
                        if( tag_end != std::string::npos ) {
                            tags.emplace_back( rawwline.substr( tag_pos, tag_end + 1 - tag_pos ) );
                        }
                    }
                }
                // Close any unclosed tags
                if( !tags.empty() ) {
                    std::string swline;
                    swline += wline;
                    for( auto it = tags.rbegin(); it != tags.rend(); ++it ) {
                        // currently the only closing tag is </color>
                        swline += "</color>";
                    }
                    wline = swline;
                }
                // The resulting line can be printed independently and have the correct color
                lines.emplace_back( wline );
            }
        }
    }
    return lines;
}
References get_tag_positions(), and word_rewrap().
Referenced by dialogue_window::cache_msg(), construction_menu(), string_input_popup::create_window(), talk_function::display_and_choose_opts(), Messages::display_messages(), main_menu::display_text(), draw_item_info(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), diary::export_to_md(), Messages::dialog::filter_help_text(), find_minimum_fold_width(), fold_and_print(), fold_and_print_from(), vpart_info::format_description(), requirement_data::get_folded_list(), construction::get_folded_time_string(), query_popup::init(), Messages::dialog::init(), ma_style_callback::key(), computer_session::print_indented_line(), npc::print_info(), monster::print_info(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), print_scrollable(), iuse::radio_on(), wish_mutate_callback::refresh(), scrollable_text(), select_crafting_recipe(), set_skills(), scrolling_text_view::set_text(), uilist::setup(), robot_finds_kitten::show(), split_to_pages(), and editmap::update_view_with_help().
format_item_info()
std::string format_item_info (const std::vector< iteminfo > & vItemDisplay, const std::vector< iteminfo > & vItemCompare)
Definition at line 854 of file output.cpp.
{
    std::string buffer;
    bool bIsNewLine = true;
    for( const auto &i : vItemDisplay ) {
        if( i.sType == "DESCRIPTION" ) {
            // Always start a new line for sType == "DESCRIPTION"
            if( !bIsNewLine ) {
                buffer += "\n";
            }
            if( i.bDrawName ) {
                buffer += i.sName;
            }
            // Always end with a linebreak for sType == "DESCRIPTION"
            buffer += "\n";
            bIsNewLine = true;
        } else {
            if( i.bDrawName ) {
                buffer += i.sName;
            }
            std::string sFmt = i.sFmt;
            std::string sPost;
            //A bit tricky, find %d and split the string
            size_t pos = sFmt.find( "<num>" );
            if( pos != std::string::npos ) {
                buffer += sFmt.substr( 0, pos );
                sPost = sFmt.substr( pos + 5 );
            } else {
                buffer += sFmt;
            }
            if( i.sValue != "-999" ) {
                nc_color thisColor = c_yellow;
                for( auto &k : vItemCompare ) {
                    if( k.sValue != "-999" ) {
                        if( i.sName == k.sName && i.sType == k.sType ) {
                            if( i.dValue > k.dValue - .1 &&
                                i.dValue < k.dValue + .1 ) {
                                thisColor = c_light_gray;
                            } else if( i.dValue > k.dValue ) {
                                if( i.bLowerIsBetter ) {
                                    thisColor = c_light_red;
                                } else {
                                    thisColor = c_light_green;
                                }
                            } else if( i.dValue < k.dValue ) {
                                if( i.bLowerIsBetter ) {
                                    thisColor = c_light_green;
                                } else {
                                    thisColor = c_light_red;
                                }
                            }
                            break;
                        }
                    }
                }
                buffer += colorize( i.sValue, thisColor );
            }
            buffer += sPost;
            // Set bIsNewLine in case the next line should always start in a new line
            if( ( bIsNewLine = i.bNewLine ) ) {
                buffer += "\n";
            }
        }
    }
    return buffer;
}
References c_light_gray, c_light_green, c_light_red, c_yellow, and colorize().
Referenced by draw_item_info(), and item::info().
format_money()
std::string format_money (int cents) inline
Definition at line 975 of file output.h.
{
    return string_format( _( "$%.2f" ), cents / 100.0 );
}
References _, and string_format().
Referenced by talk_function::bionic_remove(), defense_game::caravan(), item::display_money(), draw_caravan_categories(), draw_caravan_items(), anonymous_namespace{iexamine.cpp}::atm_menu::finish_interaction(), dialogue::gen_responses(), bionic_install_surgeon_preset::get_money_amount(), parse_tags(), iexamine::pay_gas(), trading_window::perform_trade(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), trading_window::update_win(), iexamine::vending(), and memorial_logger::write().
format_volume() [1/2]
std::string format_volume (const units::volume & volume)
Convert, round up and format a volume.
Definition at line 1974 of file output.cpp.
{
    return format_volume( volume, 0, nullptr, nullptr );
}
References format_volume().
Referenced by iexamine::arcfurnace_empty(), armor_inventory_preset::armor_inventory_preset(), anonymous_namespace{armor_layers.cpp}::clothing_properties(), item::container_info(), veh_interact::display_details(), veh_interact::display_stats(), format_volume(), inventory_selector::get_weight_and_volume_stats(), give_item_to(), iexamine::kiln_empty(), mill_activate(), pickup::pick_up(), advanced_inventory::print_items(), vehicle::print_part_list(), iexamine::quern_examine(), smoker_activate(), iexamine::smoker_options(), player::sort_armor(), trading_window::update_win(), and sew_advanced_actor::use().
format_volume() [2/2]
std::string format_volume (const units::volume & volume, int width, bool * out_truncated, double * out_value)
Convert, clamp, round up and format a volume, taking into account the specified width (0 for unlimited space), optionally returning a flag that indicate if the value was truncated to fit the width, optionally returning the formatted value as double.
Definition at line 1985 of file output.cpp.
{
    // convert and get the units preferred scale
    int scale = 0;
    double value = convert_volume( volume.value(), &scale );
    // clamp to the specified width
    if( width != 0 ) {
        value = clamp_to_width( value, std::abs( width ), scale, out_truncated );
    }
    // round up
    value = round_up( value, scale );
    if( out_value != nullptr ) {
        *out_value = value;
    }
    // format
    if( width < 0 ) {
        // left-justify the specified width
        return string_format( "%-*.*f", std::abs( width ), scale, value );
    } else if( width > 0 ) {
        // right-justify the specified width
        return string_format( "%*.*f", width, scale, value );
    } else {
        // no width
        return string_format( "%.*f", scale, value );
    }
}
References clamp_to_width(), convert_volume(), round_up(), and string_format().
full_screen_popup()
template<typename ... Args> void full_screen_popup (const char * mes, Args &&... args) inline
Definition at line 516 of file output.h.
{
    popup( string_format( mes, std::forward<Args>( args )... ), PF_FULLSCREEN );
}
References PF_FULLSCREEN, popup(), and string_format().
get_bar()
std::pair< std::string, nc_color > get_bar (float cur, float max, int width = 5, bool extra_resolution = true, const std::vector< nc_color > & colors = { c_green, c_light_green, c_yellow, c_light_red, c_red })
Returns
Pair of a string containing the bar, and its color
Parameters
cur Current value being formatted
max Maximum possible value, e.g. a full bar
extra_resolution Double the resolution of displayed values with \ symbols.
colors A vector containing N colors with which to color the bar at different values
Definition at line 1580 of file output.cpp.
{
    std::string result;
    float status = cur / max;
    status = status > 1 ? 1 : status;
    status = status < 0 ? 0 : status;
    float sw = status * width;
    nc_color col = colors[static_cast<int>( ( 1 - status ) * colors.size() )];
    if( status == 0 ) {
        col = colors.back();
    } else if( ( sw < 0.5 ) && ( sw > 0 ) ) {
        result = ":";
    } else {
        result += std::string( sw, '|' );
        if( extra_resolution && ( sw - static_cast<int>( sw ) >= 0.5 ) ) {
            result += "\\";
        }
    }
    return std::make_pair( result, col );
}
References PATH_INFO::colors().
Referenced by get_hp_bar(), and get_stamina_bar().
get_hotkeys()
std::vector< std::string > get_hotkeys (const std::string & s)
Definition at line 745 of file output.cpp.
{
    std::vector<std::string> hotkeys;
    size_t start = s.find_first_of( '<' );
    size_t end = s.find_first_of( '>' );
    if( start != std::string::npos && end != std::string::npos ) {
        // hotkeys separated by '|' inside '<' and '>', for example "<e|E|?>"
        size_t lastsep = start;
        size_t sep = s.find_first_of( '|', start );
        while( sep < end ) {
            hotkeys.push_back( s.substr( lastsep + 1, sep - lastsep - 1 ) );
            lastsep = sep;
            sep = s.find_first_of( '|', sep + 1 );
        }
        hotkeys.push_back( s.substr( lastsep + 1, end - lastsep - 1 ) );
    }
    return hotkeys;
}
Referenced by help::deserialize(), main_menu::init_strings(), and main_menu::new_character_tab().
get_hp_bar()
std::pair< std::string, nc_color > get_hp_bar (int cur_hp, int max_hp, bool is_mon = false)
Definition at line 1604 of file output.cpp.
{
    if( cur_hp == 0 ) {
        return std::make_pair( "-----", c_light_gray );
    }
    return get_bar( cur_hp, max_hp, 5, !is_mon );
}
References c_light_gray, and get_bar().
Referenced by blood_magic(), Character::body_window(), Character::deal_damage(), draw_char_narrow(), draw_char_wide(), draw_health_classic(), draw_limb2(), draw_limb_health(), spell::energy_cost_string(), spell::energy_cur_string(), Character::extended_description(), monster::get_HP_Bar(), game::list_monsters(), player_hit_message(), and ranged::print_dmg_msg().
get_labeled_bar() [1/2]
template<typename RatingIterator > std::string get_labeled_bar (const double val, const int width, const std::string & label, RatingIterator begin, RatingIterator end) inline
Returns
String containing the bar. Example: "Label [******** ]".
Parameters
val Value to display. Can be unclipped.
width Width of the entire string.
label Label before the bar. Can be empty.
begin Iterator over pairs <double p, char c> (see below).
end Iterator over pairs <double p, char c> (see below). Where: p - percentage of the entire bar which can be filled with c. c - character to fill the segment of the bar with
Definition at line 634 of file output.h.
{
    std::string result;
    result.reserve( width );
    if( !label.empty() ) {
        result += label;
        result += ' ';
    }
    const int bar_width = width - utf8_width( result ) - 2; // - 2 for the brackets
    result += '[';
    if( bar_width > 0 ) {
        int used_width = 0;
        for( RatingIterator it( begin ); it != end; ++it ) {
            const double factor = std::min( 1.0, std::max( 0.0, it->first * val ) );
            const int seg_width = static_cast<int>( factor * bar_width ) - used_width;
            if( seg_width <= 0 ) {
                continue;
            }
            used_width += seg_width;
            result.insert( result.end(), seg_width, it->second );
        }
        result.insert( result.end(), bar_width - used_width, ' ' );
    }
    result += ']';
    return result;
}
References utf8_width().
get_labeled_bar() [2/2]
std::string get_labeled_bar (double val, int width, const std::string & label, char c)
Returns
String containing the bar. Example: "Label [******** ]".
Parameters
val Value to display. Can be unclipped.
width Width of the entire string.
label Label before the bar. Can be empty.
c Character to fill the bar with.
Definition at line 1641 of file output.cpp.
{
    const std::array<std::pair<double, char>, 1> ratings =
    {{ std::make_pair( 1.0, c ) }};
    return get_labeled_bar( val, width, label, ratings.begin(), ratings.end() );
}
References c, and get_labeled_bar().
Referenced by get_labeled_bar(), and print_steadiness().
get_light_level()
std::pair< std::string, nc_color > get_light_level (float light)
Definition at line 1621 of file output.cpp.
{
    using pair_t = std::pair<std::string, nc_color>;
    static const std::array<pair_t, 6> strings {
        {
            pair_t {translate_marker( "unknown" ), c_pink},
            pair_t {translate_marker( "bright" ), c_yellow},
            pair_t {translate_marker( "cloudy" ), c_white},
            pair_t {translate_marker( "shady" ), c_light_gray},
            pair_t {translate_marker( "dark" ), c_dark_gray},
            pair_t {translate_marker( "very dark" ), c_black_white}
        }
    };
    // Avoid magic number
    static const int maximum_light_level = static_cast< int >( strings.size() ) - 1;
    const int light_level = clamp( static_cast< int >( std::ceil( light ) ), 0, maximum_light_level );
    const size_t array_index = static_cast< size_t >( light_level );
    return pair_t{ _( strings[array_index].first ), strings[array_index].second };
}
References _, c_black_white, c_dark_gray, c_light_gray, c_pink, c_white, c_yellow, clamp(), light, and translate_marker.
Referenced by draw_env_compact(), draw_lighting_classic(), draw_loc_labels(), and game::print_terrain_info().
get_stamina_bar()
std::pair< std::string, nc_color > get_stamina_bar (int cur_stam, int max_stam)
Definition at line 1613 of file output.cpp.
{
    if( cur_stam == 0 ) {
        return std::make_pair( "-----", c_light_gray );
    }
    return get_bar( cur_stam, max_stam, 5, true, { c_cyan, c_light_cyan, c_yellow, c_light_red, c_red } );
}
References c_cyan, c_light_cyan, c_light_gray, c_light_red, c_red, c_yellow, and get_bar().
get_tag_positions()
std::vector< size_t > get_tag_positions (const std::string & s)
Definition at line 1118 of file output.cpp.
{
    std::vector<size_t> ret;
    size_t pos = s.find( "<color_", 0, 7 );
    while( pos != std::string::npos ) {
        ret.push_back( pos );
        pos = s.find( "<color_", pos + 1, 7 );
    }
    pos = s.find( "</color>", 0, 8 );
    while( pos != std::string::npos ) {
        ret.push_back( pos );
        pos = s.find( "</color>", pos + 1, 8 );
    }
    std::sort( ret.begin(), ret.end() );
    return ret;
}
References cata::hash64_detail::ret.
Referenced by foldstring(), remove_color_tags(), split_by_color(), and word_rewrap().
get_terminal_height()
int get_terminal_height ()
Get the height in font glyphs of the drawing screen.
May differ from OPTIONS["TERMINAL_Y"], for instance in SDL FULLSCREEN mode, the user setting is overridden.
Definition at line 2023 of file output.cpp.
{
    return get_option<int>( "TERMINAL_Y" );
}
Referenced by game_ui::init_ui().
get_terminal_width()
int get_terminal_width ()
Get the width in font glyphs of the drawing screen.
May differ from OPTIONS["TERMINAL_X"], for instance in SDL FULLSCREEN mode, the user setting is overridden.
Definition at line 2017 of file output.cpp.
{
    int width = get_option<int>( "TERMINAL_X" );
    return width < FULL_SCREEN_WIDTH ? FULL_SCREEN_WIDTH : width;
}
References FULL_SCREEN_WIDTH.
Referenced by game_ui::init_ui().
insert_table()
void insert_table (const catacurses::window & w, int pad, int line, int columns, const nc_color & FG, const std::string & divider, bool r_align, const std::vector< std::string > & data)
Inserts a table into a window, with data right-aligned.
Parameters
pad Reduce table width by padding left side.
line Line to insert table.
columns Number of columns. Can be 1.
nc_color &FG Default color of table text.
divider To insert a character separating table entries. Can be blank.
r_align true for right aligned, false for left aligned.
data Text data to fill. Make sure each entry of the data vector fits into one cell, including divider if any.
Definition at line 1659 of file output.cpp.
{
    const int width = getmaxx( w );
    const int rows = getmaxy( w );
    const int col_width = ( ( width - pad ) / columns );
    int indent = 1;  // 1 for right window border
    if( r_align ) {
        indent = ( col_width * columns ) + 1;
    }
    int div = columns - 1;
    int offset = 0;
#if defined(__ANDROID__)
    input_context ctxt( "INSERT_TABLE" );
#endif
    wattron( w, FG );
    for( int i = 0; i < rows * columns; i++ ) {
        if( i + offset * columns >= static_cast<int>( data.size() ) ) {
            break;
        }
        int y = line + ( i / columns );
        if( r_align ) {
            indent -= col_width;
        }
        if( div != 0 ) {
            if( r_align ) {
                right_print( w, y, indent - utf8_width( divider ), FG, divider );
            } else {
                fold_and_print_from( w, point( indent + col_width - utf8_width( divider ), y ),
                                     utf8_width( divider ), 0, FG, divider );
            }
            div--;
        } else {
            div = columns - 1;
        }
        if( r_align ) {
            right_print( w, y, indent, c_white, data[i + offset * columns] );
            if( indent == 1 ) {
                indent = ( col_width * columns ) + 1;
            }
        } else {
            fold_and_print_from( w, point( indent, y ), col_width, 0, c_white, data[i + offset * columns] );
            indent += col_width;
            if( indent == ( col_width * columns ) + 1 ) {
                indent = 1;
            }
        }
    }
    wattroff( w, FG );
}
References c_white, fold_and_print_from(), catacurses::getmaxx(), catacurses::getmaxy(), line(), right_print(), utf8_width(), catacurses::wattroff(), and catacurses::wattron().
Referenced by print_ranged_chance().
is_draw_tiles_mode()
bool is_draw_tiles_mode ()
Check whether we're in tile drawing mode.
The most important effect of this is that we don't need to draw to the ASCII window.
Ideally, of course, we'd have a unified tile drawing and ASCII drawing API and use polymorphy, but for the time being there will be a lot of switching around in the map drawing code.
Definition at line 2029 of file output.cpp.
{
    return false;
}
Referenced by map::draw(), Creature::draw(), game::draw_look_around_cursor(), and map::drawsq().
msgtype_to_color()
nc_color msgtype_to_color (game_message_type type, bool bOldMsg = false)
Definition at line 1948 of file output.cpp.
{
    static const std::map<game_message_type, std::pair<nc_color, nc_color>> colors {
        {m_good,     {c_light_green, c_green}},
        {m_bad,      {c_light_red,   c_red}},
        {m_mixed,    {c_pink,    c_magenta}},
        {m_warning,  {c_yellow,  c_brown}},
        {m_info,     {c_light_blue,  c_blue}},
        {m_neutral,  {c_white,   c_light_gray}},
        {m_debug,    {c_white,   c_light_gray}},
        {m_headshot, {c_pink,    c_magenta}},
        {m_critical, {c_yellow,  c_brown}},
        {m_grazing,  {c_light_blue,  c_blue}}
    };
    const auto it = colors.find( type );
    if( it == std::end( colors ) ) {
        return bOldMsg ? c_light_gray : c_white;
    }
    return bOldMsg ? it->second.second : it->second.first;
}
References c_blue, c_brown, c_green, c_light_blue, c_light_gray, c_light_green, c_light_red, c_magenta, c_pink, c_red, c_white, c_yellow, PATH_INFO::colors(), m_bad, m_critical, m_debug, m_good, m_grazing, m_headshot, m_info, m_mixed, m_neutral, m_warning, and type.
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses(), Messages::dialog::filter_help_text(), anonymous_namespace{messages.cpp}::game_message::get_color(), and Messages::dialog::show().
mvwprintz() [1/2]
template<typename ... Args> void mvwprintz (const catacurses::window & w, const point & p, const nc_color & FG, const char *const mes, Args &&... args) inline
Definition at line 378 of file output.h.
{
    mvwprintz( w, p, FG, string_format( mes, std::forward<Args>( args )... ) );
}
References mvwprintz(), and string_format().
mvwprintz() [2/2]
void mvwprintz (const catacurses::window & w, const point & p, const nc_color & FG, const std::string & text)
Definition at line 2035 of file output.cpp.
{
    wattron( w, FG );
    mvwprintw( w, p, text );
    wattroff( w, FG );
}
References catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
Referenced by game::cleanup_at_end(), decorate_panel(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), talk_function::display_and_choose_opts(), input_context::display_menu(), veh_interact::display_name(), dialogue_window::display_responses(), veh_interact::display_stats(), veh_interact::display_veh(), scent_map::draw(), string_input_popup::draw(), char_creation::draw_age(), draw_ai_goal(), draw_armor(), draw_armor_padding(), overmap_ui::draw_ascii(), overmap_ui::draw_camp_labels(), draw_caravan_borders(), draw_caravan_categories(), draw_caravan_items(), draw_char_narrow(), draw_char_wide(), overmap_ui::draw_city_labels(), draw_connectors(), draw_env_compact(), inventory_selector::draw_footer(), draw_grid(), draw_header(), draw_health_classic(), char_creation::draw_height(), target_ui::draw_help_notice(), draw_hint(), draw_item_filter_rules(), sokoban_game::draw_level(), draw_lighting_classic(), draw_limb2(), draw_loc_labels(), draw_location_classic(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), worldfactory::draw_mod_list(), draw_moon_narrow(), draw_moon_wide(), draw_needs_compact(), draw_needs_labels(), draw_needs_narrow(), overmap_ui::draw_om_sidebar(), game::draw_panels(), draw_points(), anonymous_namespace{animation.cpp}::draw_sct_curses(), draw_skills_tab(), draw_sound_labels(), draw_sound_narrow(), draw_speed_tab(), draw_spellbook_info(), query_destination_callback::draw_squares(), draw_stat_narrow(), draw_stat_wide(), draw_stats(), draw_stats_tab(), draw_stealth(), draw_subtab(), draw_tab(), draw_time(), draw_time_classic(), draw_tip(), draw_veh_compact(), draw_veh_padding(), draw_weapon_classic(), draw_weapon_classic_alt(), draw_weapon_labels(), draw_weather_classic(), draw_weightvolume_classic(), draw_weightvolume_compact(), draw_weightvolume_labels(), draw_weightvolume_narrow(), target_ui::draw_window_title(), anonymous_namespace{animation.cpp}::draw_zones_curses(), game::extended_description(), basecamp::faction_display(), faction::faction_display(), npc::faction_display(), anonymous_namespace{animation.cpp}::hit_animation(), basecamp::job_assignment_ui(), game::list_items(), game::list_missions(), game::list_monsters(), main_menu::load_character_tab(), game::look_around(), game::mon_info(), mvwprintz(), main_menu::new_character_tab(), target_ui::panel_gun_info(), target_ui::panel_spell_info(), pickup::pick_up(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), player::power_bionics(), player::power_mutations_ui(), string_editor_window::print_editor(), character_display::print_encumbrance(), game::print_fields_info(), vehicle::print_fuel_indicator(), vehicle::print_fuel_indicators(), advanced_inventory::print_header(), dialogue_window::print_header(), dialogue_window::print_history(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), print_items(), game::print_items_info(), print_keybindings(), vehicle::print_part_list(), print_responses(), snake_game::print_score(), sokoban_game::print_score(), game::print_trap_info(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), spellcasting_callback::refresh(), teleporter_callback::refresh(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), advanced_inventory::refresh_minimap(), defense_game::refresh_setup(), render_wind(), game::reset_item_list_state(), overmap_ui::search(), select_crafting_recipe(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), defense_game::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), Messages::dialog::show(), uilist::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), panel_manager::show_adm(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), worldfactory::show_worldgen_tab_confirm(), snake_game::snake_over(), player::sort_armor(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), trading_window::update_win(), basecamp::worker_assignment_ui(), main_menu::world_tab(), game::zones_manager(), and zones_manager_draw_borders().
mvwputch() [1/2]
void mvwputch (const catacurses::window & w, const point & p, nc_color FG, const std::string & ch)
Definition at line 484 of file output.cpp.
{
    wattron( w, FG );
    mvwprintw( w, p, ch );
    wattroff( w, FG );
}
References catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
mvwputch() [2/2]
void mvwputch (const catacurses::window & w, const point & p, nc_color FG, int ch)
Definition at line 477 of file output.cpp.
{
    wattron( w, FG );
    mvwaddch( w, p, ch );
    wattroff( w, FG );
}
References catacurses::mvwaddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by scrollbar::apply(), game::cleanup_at_end(), faction_manager::display(), veh_interact::display_grid(), veh_interact::display_list(), veh_interact::display_veh(), Creature::draw(), inventory_column::draw(), scrolling_text_view::draw(), editmap_hilight::draw(), overmap_ui::draw_ascii(), draw_bionics_tabs(), draw_bionics_titlebar(), border_helper::draw_border(), draw_border_below_tabs(), draw_borders_external(), draw_borders_internal(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), draw_caravan_borders(), draw_character_tabs(), draw_connectors(), draw_critter_internal(), draw_custom_border(), draw_exam_window(), anonymous_namespace{animation.cpp}::draw_explosion_curses(), inventory_selector::draw_footer(), draw_footsteps(), draw_grid(), draw_header(), draw_item_info(), lightson_game::draw_level(), sokoban_game::draw_level(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), game::draw_minimap(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), game::draw_panels(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_subtab(), draw_tab(), draw_tabs(), game::draw_ter(), draw_trail(), target_ui::draw_ui_window(), game::draw_veh_dir_indicator(), anonymous_namespace{animation.cpp}::draw_weather_curses(), game::extended_description(), basecamp::job_assignment_ui(), game::list_missions(), pickup::pick_up(), worldfactory::pick_world(), player::power_bionics(), player::power_mutations_ui(), dialogue_window::print_header(), main_menu::print_menu(), spellcasting_callback::refresh(), spellbook_callback::refresh(), teleporter_callback::refresh(), game::reset_item_list_state(), select_crafting_recipe(), set_description(), set_profession(), set_scenario(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), uilist::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), color_manager::show_gui(), worldfactory::show_modselection_window(), snake_game::snake_over(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), editmap::uber_draw_ter(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), trading_window::update_win(), basecamp::worker_assignment_ui(), and zones_manager_draw_borders().
mvwputch_hi() [1/2]
void mvwputch_hi (const catacurses::window & w, const point & p, nc_color FG, const std::string & ch)
Definition at line 516 of file output.cpp.
{
    nc_color HC = hilite( FG );
    wattron( w, HC );
    mvwprintw( w, p, ch );
    wattroff( w, HC );
}
References hilite(), catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
mvwputch_hi() [2/2]
void mvwputch_hi (const catacurses::window & w, const point & p, nc_color FG, int ch)
Definition at line 508 of file output.cpp.
{
    nc_color HC = hilite( FG );
    wattron( w, HC );
    mvwaddch( w, p, ch );
    wattroff( w, HC );
}
References hilite(), catacurses::mvwaddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by Creature::draw(), overmap_ui::draw_ascii(), game::draw_minimap(), and overmap_ui::draw_overmap_chunk().
mvwputch_inv() [1/2]
void mvwputch_inv (const catacurses::window & w, const point & p, nc_color FG, const std::string & ch)
Definition at line 499 of file output.cpp.
{
    nc_color HC = invert_color( FG );
    wattron( w, HC );
    mvwprintw( w, p, ch );
    wattroff( w, HC );
}
References invert_color(), catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
mvwputch_inv() [2/2]
void mvwputch_inv (const catacurses::window & w, const point & p, nc_color FG, int ch)
Definition at line 491 of file output.cpp.
{
    nc_color HC = invert_color( FG );
    wattron( w, HC );
    mvwaddch( w, p, ch );
    wattroff( w, HC );
}
References invert_color(), catacurses::mvwaddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by Creature::draw(), and game::draw_cursor().
name_and_value() [1/2]
std::string name_and_value (const std::string & name, const std::string & value, int field_width)
Definition at line 434 of file output.cpp.
{
    const int text_width = utf8_width( name ) + utf8_width( value );
    const int spacing = std::max( field_width, text_width ) - text_width;
    return name + std::string( spacing, ' ' ) + value;
}
References om_direction::name(), and utf8_width().
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_properties(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), and name_and_value().
name_and_value() [2/2]
std::string name_and_value (const std::string & name, int value, int field_width)
Definition at line 441 of file output.cpp.
{
    return name_and_value( name, string_format( "%d", value ), field_width );
}
References om_direction::name(), name_and_value(), and string_format().
popup() [1/2]
template<typename ... Args> void popup (const char * mes, Args &&... args) inline
Definition at line 510 of file output.h.
{
    popup( string_format( mes, std::forward<Args>( args )... ), PF_NONE );
}
References PF_NONE, popup(), and string_format().
Referenced by full_screen_popup(), popup(), popup_getkey(), and popup_top().
popup() [2/2]
int popup (const std::string & text, PopupFlags flags = PF_NONE)
Definition at line 764 of file output.cpp.
{
    query_popup pop;
    pop.message( "%s", text );
    if( flags & PF_GET_KEY ) {
        pop.allow_anykey( true );
    } else {
        pop.allow_cancel( true );
    }
    if( flags & PF_FULLSCREEN ) {
        pop.full_screen( true );
    } else if( flags & PF_ON_TOP ) {
        pop.on_top( true );
    }
    pop.context( "POPUP_WAIT" );
    const auto &res = pop.query();
    if( res.evt.type == CATA_INPUT_KEYBOARD ) {
        return res.evt.get_first_input();
    } else {
        return UNKNOWN_UNICODE;
    }
}
References query_popup::allow_anykey(), query_popup::allow_cancel(), CATA_INPUT_KEYBOARD, query_popup::context(), query_popup::result::evt, query_popup::full_screen(), input_event::get_first_input(), query_popup::message(), query_popup::on_top(), PF_FULLSCREEN, PF_GET_KEY, PF_ON_TOP, query_popup::query(), and UNKNOWN_UNICODE.
Referenced by advanced_inventory::action_move_item(), zone_manager::add(), tutorial_game::add_message(), autoclave_internal(), iexamine::autodoc(), autodoc_internal(), debug_menu::benchmark(), talk_function::bionic_remove(), iuse::camera(), player::can_continue_craft(), Character::can_install_bionics(), Character::can_uninstall_bionic(), defense_game::caravan(), talk_function::caravan_depart(), talk_function::caravan_return(), talk_function::carpenter_return(), advanced_inventory::change_square(), debug_menu::character_edit_menu(), game::chat(), choose_direction(), game::cleanup_at_end(), basecamp::combat_mission_return(), talk_function::companion_choose(), talk_function::companion_choose_return(), game_menus::inv::compare(), veh_interact::complete_vehicle(), construction_menu(), iexamine::cvdmachine(), debug_menu::debug(), debug_drop_list(), debug_tokens(), advanced_inventory::display(), faction_manager::display(), talk_function::display_and_choose_opts(), input_context::display_menu(), basecamp::distribute_food(), anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), veh_interact::do_main_loop(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), anonymous_namespace{animation.cpp}::basic_animation::draw(), editmap::edit_itm(), edit_json(), iuse::einktabletpc(), iexamine::fault(), talk_function::field_build_1(), talk_function::field_build_2(), talk_function::field_harvest(), talk_function::field_plant(), game::find_or_make_stairs(), start_location::find_player_initial_location(), basecamp::finish_return(), talk_function::forage_return(), defense_game::game_over(), talk_function::give_equipment(), iuse::handle_ground_graffiti(), handle_player_display_action(), game_menus::inv::holster(), talk_function::individual_mission(), defense_game::init_map(), inv_internal(), game::item_action_menu(), inscribe_actor::item_inscription(), spellcasting_callback::key(), actmenu_cb::key(), talk_function::labor_return(), iexamine::ledge(), game::load(), player::making_would_work(), trapfunc::map_regen(), editmap::mapgen_preview(), editmap::mapgen_veh_query(), advanced_inventory::move_all_items(), advanced_inventory::move_content(), game_menus::inv::multidrop(), game_menus::inv::multiwash(), iuse::mycus(), iexamine::nanofab(), main_menu::new_character_tab(), iexamine::notify(), om_target_tile(), main_menu::opening_screen(), monexamine::pay_bot(), iexamine::pay_gas(), defense_game::per_turn(), trading_window::perform_trade(), pickup::pick_up(), popup_player_or_npc(), popup_string(), player::power_bionics(), player::power_mutations_ui(), tutorial_game::pre_action(), iexamine::quern_examine(), advanced_inventory::query_charges(), advanced_inventory::query_destination(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration(), query_int(), zone_manager::query_name(), basecamp::query_new_name(), game::quicksave(), talk_function::recover_camp(), player::recraft(), basecamp::recruit_return(), game::reload_tileset(), game::save(), mapbuffer::save(), game::save_cyborg(), game::save_maps(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), overmap_ui::search(), base_camps::select_camp_option(), select_crafting_recipe(), talk_effect_fun_t::set_bulk_trade_accept(), talk_effect_fun_t::set_consume_item(), set_description(), set_profession(), set_scenario(), basecamp::set_sort_points(), set_traits(), talk_effect_fun_t::set_u_buy_item(), talk_effect_fun_t::set_u_buy_monster(), talk_effect_fun_t::set_u_learn_recipe(), talk_effect_fun_t::set_u_sell_item(), game::setup(), defense_game::setup(), options_manager::show(), worldfactory::show_modselection_window(), show_photo_selection(), iexamine::sign(), iexamine::slot_machine(), iexamine::smoker_options(), player::sort_armor(), talk_function::start_camp(), basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_crafting(), basecamp::start_cut_logs(), basecamp::start_farm_op(), basecamp::start_fortifications(), game::start_game(), basecamp::start_menial_labor(), basecamp::start_mission(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), basecamp::start_upgrade(), basecamp::survey_return(), survive_random_encounter(), zone_manager::swap(), game_menus::inv::swap_letters(), avatar_action::swim(), game::take_screenshot(), safemode::test_pattern(), debug_menu::anonymous_namespace{wisheffect.cpp}::try_read_time_string(), game::unserialize_master(), basecamp::upgrade_return(), character_display::upgrade_stat_prompt(), weigh_self_actor::use(), worldfactory::valid_worldname(), iexamine::vending(), wait(), game::win_screen(), debug_menu::wishitem(), main_menu::world_tab(), write_to_file(), and game::zones_manager().
popup_getkey()
template<typename ... Args> int popup_getkey (const char *const mes, Args &&... args) inline
Definition at line 500 of file output.h.
{
    return popup( string_format( mes, std::forward<Args>( args )... ), PF_GET_KEY );
}
References PF_GET_KEY, popup(), and string_format().
Referenced by input_context::display_menu(), inventory_compare_selector::execute(), inventory_iuse_selector::execute(), inventory_drop_selector::execute(), spellcasting_callback::key(), player::power_bionics(), game::quickload(), game_menus::inv::reassign_letter(), and player::sort_armor().
popup_top()
template<typename ... Args> void popup_top (const char *const mes, Args &&... args) inline
Definition at line 505 of file output.h.
{
    popup( string_format( mes, std::forward<Args>( args )... ), PF_ON_TOP );
}
References PF_ON_TOP, popup(), and string_format().
Referenced by defense_game::caravan(), debug_menu::debug(), lightson_game::start_game(), and minesweeper_game::start_game().
print_colored_text()
void print_colored_text (const catacurses::window & w, const point & p, nc_color & cur_color, const nc_color & base_color, const std::string & text, report_color_error color_error = report_color_error::yes)
Print text with embedded color_tags, x, y are in curses system.
The text is not word wrapped, but may automatically be wrapped on new line characters or when it reaches the border of the window (both is done by the curses system). If the text contains no color tags, it's equivalent to a simple mvprintz.
Parameters
w Window we are drawing in
p Curses-style coordinates to print text at.
text The text to print.
cur_color The current color (could have been set by a previously encountered color tag), change to a color according to the color tags that are in the text.
base_color Base color that is used outside of any color tag.
Definition at line 185 of file output.cpp.
{
    if( p.y > -1 && p.x > -1 ) {
        wmove( w, p );
    }
    const auto color_segments = split_by_color( text );
    std::stack<nc_color> color_stack;
    color_stack.push( color );
    for( auto seg : color_segments ) {
        if( seg.empty() ) {
            continue;
        }
        if( seg[0] == '<' ) {
            const color_tag_parse_result::tag_type type = update_color_stack(
                        color_stack, seg, color_error );
            if( type != color_tag_parse_result::non_color_tag ) {
                seg = rm_prefix( seg );
            }
        }
        color = color_stack.empty() ? base_color : color_stack.top();
        wprintz( w, color, seg );
    }
}
References color(), color_tag_parse_result::non_color_tag, rm_prefix(), coords::seg, split_by_color(), type, update_color_stack(), catacurses::wmove(), wprintz(), point::x, and point::y.
Referenced by talk_function::display_and_choose_opts(), Messages::display_messages(), veh_interact::display_mode(), scrolling_text_view::draw(), draw_armor(), draw_armor_padding(), overmap_ui::draw_ascii(), target_ui::draw_controls_list(), draw_limb_wide(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), draw_points(), spellcasting_callback::draw_spell_info(), draw_spellbook_info(), draw_stats_info(), draw_time(), draw_weather_classic(), fold_and_print(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_recoil(), target_ui::panel_spell_info(), target_ui::panel_turret_list(), print_mana(), main_menu::print_menu(), print_ranged_chance(), print_scrollable(), computer_session::refresh(), scrollable_text(), select_crafting_recipe(), shortcut_print(), Messages::dialog::show(), query_popup::show(), worldfactory::show_modselection_window(), trim_and_print(), overmap_ui::update_note_preview(), and editmap::update_view_with_help().
print_scrollable()
int print_scrollable (const catacurses::window & w, int begin_line, const std::string & text, const nc_color & base_color, const std::string & scroll_msg)
Print word wrapped text (with color_tags) into the window.
Parameters
w Window we are printing in
begin_line Line in the word wrapped text that is printed first (lines before that are not printed at all).
text Text to print
base_color Color used outside of any color tags.
scroll_msg Optional, can be empty. If not empty and the text does not fit the window, the string is printed on the last line (in light green), it should show how to scroll the text.
Returns
The maximal scrollable offset ([number of lines to be printed] - [lines available in the window]). This allows the caller to restrict the begin_line number on future calls / when modified by the user.
Definition at line 271 of file output.cpp.
{
    const size_t wwidth = getmaxx( w );
    const auto text_lines = foldstring( text, wwidth );
    size_t wheight = getmaxy( w );
    const auto print_scroll_msg = text_lines.size() > wheight;
    if( print_scroll_msg && !scroll_msg.empty() ) {
        // keep the last line free for a message to the player
        wheight--;
    }
    if( begin_line < 0 || text_lines.size() <= wheight ) {
        begin_line = 0;
    } else if( begin_line + wheight >= text_lines.size() ) {
        begin_line = text_lines.size() - wheight;
    }
    nc_color color = base_color;
    for( size_t i = 0; i + begin_line < text_lines.size() && i < wheight; ++i ) {
        print_colored_text( w, point( 0, i ), color, base_color, text_lines[i + begin_line] );
    }
    if( print_scroll_msg && !scroll_msg.empty() ) {
        color = c_white;
        print_colored_text( w, point( 0, wheight ), color, color, scroll_msg );
    }
    return std::max<int>( 0, text_lines.size() - wheight );
}
References c_white, color(), foldstring(), catacurses::getmaxx(), catacurses::getmaxy(), and print_colored_text().
Referenced by set_profession().
query_int() [1/4]
template<typename ... Args> bool query_int (int & result, const char *const msg, Args &&... args) inline
Definition at line 462 of file output.h.
{
    return query_int( result, string_format( msg, std::forward<Args>( args )... ) );
}
References query_int(), and string_format().
query_int() [2/4]
bool query_int (int & result, const std::string & text)
Definition at line 732 of file output.cpp.
{
    string_input_popup popup;
    popup.title( text );
    popup.text( "" ).only_digits( true );
    popup.query();
    if( popup.canceled() ) {
        return false;
    }
    result = atoi( popup.text().c_str() );
    return true;
}
References popup().
query_int() [3/4]
template<typename ... Args> bool query_int (int & result, int default_val, const char *const msg, Args &&... args) inline
Definition at line 455 of file output.h.
{
    return query_int( result, default_val, string_format( msg, std::forward<Args>( args )... ) );
}
References query_int(), and string_format().
query_int() [4/4]
bool query_int (int & result, int default_val, const std::string & text)
Definition at line 718 of file output.cpp.
{
    string_input_popup popup;
    popup.title( text );
    popup.text( std::to_string( default_val ) );
    popup.only_digits( true );
    popup.query();
    if( popup.canceled() ) {
        return false;
    }
    result = atoi( popup.text().c_str() );
    return true;
}
References popup(), and to_string().
Referenced by Character::activate_mutation(), iuse::c4(), debug_menu::character_edit_menu(), debug_menu::debug(), game::display_scent(), editmap::edit_itm(), iuse::mininuke(), and query_int().
query_yn() [1/2]
template<typename ... Args> bool query_yn (const char *const msg, Args &&... args) inline
Definition at line 448 of file output.h.
{
    return query_yn( string_format( msg, std::forward<Args>( args )... ) );
}
References query_yn(), and string_format().
query_yn() [2/2]
bool query_yn (const std::string & text)
Definition at line 698 of file output.cpp.
{
    // TODO: Queries are often opened in test_mode, shouldn't it be an error?
    const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
    const auto &allow_key = force_uc ? input_context::disallow_lower_case
                            : input_context::allow_all_keys;
    return query_popup()
           .context( "YESNO" )
           .message( force_uc ?
                     pgettext( "query_yn", "%s (Case Sensitive)" ) :
                     pgettext( "query_yn", "%s" ), text )
           .option( "YES", allow_key )
           .option( "NO", allow_key )
           .cursor( 1 )
           .default_color( c_light_red )
           .query()
           .action == "YES";
}
References query_popup::result::action, input_context::allow_all_keys, c_light_red, query_popup::context(), query_popup::cursor(), query_popup::default_color(), input_context::disallow_lower_case, query_popup::message(), query_popup::option(), pgettext(), and query_popup::query().
Referenced by computer_session::action_extract_rad_source(), computer_session::action_miss_disarm(), zone_manager::add(), auto_pickup::player_settings::add_rule(), safemode::add_rule(), iexamine::aggie_plant(), iexamine::arcfurnace_empty(), iexamine::bars(), iuse::blood_draw(), game::butcher(), iuse::camera(), game::cancel_activity_query(), cancel_auto_move(), defense_game::caravan(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), debug_menu::character_edit_menu(), iexamine::choose_fertilizer(), choose_ma_style(), game::cleanup_at_end(), target_ui::confirm_non_enemy_target(), iuse::contacts(), iexamine::controls_gate(), overmap_ui::create_note(), diary::death_entry(), debug_menu::debug(), iexamine::deployed_furniture(), game::disable_robot(), overmap_ui::display(), input_context::display_menu(), veh_interact::do_install(), anonymous_namespace{iexamine.cpp}::atm_menu::do_purchase_card(), construct::done_digormine_stair(), worldfactory::edit_active_world_mods(), iexamine::egg_sack_generic(), iexamine::elevator(), craft_command::execute(), talk_function::field_harvest(), talk_function::field_plant(), game::find_or_make_stairs(), iexamine::fireplace(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), iexamine::fswitch(), mattack::fungus_fortify(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), give_item_to(), iexamine::gunsafe_el(), hackveh(), game::handle_action(), vehicle::handle_potential_theft(), harvest_common(), vehicle::interact_vehicle_locked(), game::is_game_over(), iexamine::keg(), overmap_ui::map_notes_callback::key(), iexamine::kiln_empty(), known_magic::learn_spell(), iexamine::ledge(), worldfactory::make_new_world(), iuse::marloss_seed(), monexamine::mech_hack(), monexamine::mfriend_menu(), iexamine::migo_nerve_cluster(), iuse::mind_splicer(), avatar_action::move(), advanced_inventory::move_all_items(), iuse::multicooker(), main_menu::new_character_tab(), game::npc_menu(), om_target_tile(), main_menu::opening_screen(), dialogue::opt(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), trading_window::perform_trade(), monexamine::pet_menu(), petfood(), pick_plant(), iexamine::pit(), iexamine::pit_covered(), iuse::play_game(), iexamine::portable_structure(), firestarter_actor::prep_firestarter_use(), game::prompt_dangerous_tile(), prompt_disassemble_in_seq(), target_ui::prompt_friendlies_in_lof(), craft_command::query_continue(), query_for_item(), query_yn(), player::query_yn(), iexamine::rubble(), iexamine::safe(), iuse::seed(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), set_up_butchery_activity(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_modselection_window(), worldfactory::show_worldgen_tab_confirm(), iexamine::shrub_wildveggies(), iexamine::sign(), signal_handler(), trapfunc::sinkhole(), iexamine::slot_machine(), smash(), smoker_activate(), activity_handlers::spellcasting_finish(), talk_function::start_camp(), basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_garage_chop(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), iexamine::translocator(), iexamine::trap(), iexamine::tree_hickory(), salvage_actor::try_to_cut_up(), character_display::upgrade_stat_prompt(), cauterize_actor::use(), place_trap_actor::use(), sew_advanced_actor::use(), vehicle::use_controls(), basecamp::validate_sort_points(), game::vertical_move(), avatar_action::wield(), main_menu::world_tab(), and game::zones_manager().
rand_char()
char rand_char ()
Definition at line 1066 of file output.cpp.
{
    switch( rng( 0, 9 ) ) {
        case 0:
            return '|';
        case 1:
            return '-';
        case 2:
            return '#';
        case 3:
            return '?';
        case 4:
            return '&';
        case 5:
            return '.';
        case 6:
            return '%';
        case 7:
            return '{';
        case 8:
            return '*';
        case 9:
            return '^';
    }
    return '?';
}
References rng().
refresh_display()
void refresh_display ()
Make changes made to the display visible to the user immediately.
In curses mode, this is a no-op. In SDL mode, this refreshes the real display from the backing buffer immediately, rather than delaying the update until the next time we are waiting for user input.
Definition at line 120 of file ncurses_def.cpp.
{
    catacurses::doupdate();
}
References catacurses::doupdate().
Referenced by computer_session::action_emerg_ref_center(), debug_menu::benchmark(), game::cancel_activity_or_ignore_query(), game::do_turn(), anonymous_namespace{animation.cpp}::basic_animation::draw(), game::fling_creature(), game::handle_key_blocking_activity(), defense_game::init_map(), game::load(), map::move_vehicle(), robot_finds_kitten::process_input(), game::quicksave(), mattack::ranged_pull(), throbber_popup::refresh(), mapbuffer::save(), game::setup(), loading_ui::show(), options_manager::show(), game::start_game(), and game::unserialize_master().
remove_color_tags()
std::string remove_color_tags (const std::string & s)
Removes the color tags from the input string.
This might be required when the string is to be used for functions that don't handle color tags.
Definition at line 145 of file output.cpp.
{
    std::string ret;
    std::vector<size_t> tag_positions = get_tag_positions( s );
    size_t next_pos = 0;
    if( !tag_positions.empty() ) {
        for( size_t tag_position : tag_positions ) {
            ret += s.substr( next_pos, tag_position - next_pos );
            next_pos = s.find( ">", tag_position, 1 ) + 1;
        }
        ret += s.substr( next_pos, std::string::npos );
    } else {
        return s;
    }
    return ret;
}
References get_tag_positions(), and cata::hash64_detail::ret.
Referenced by Character::absorb_hit(), inventory_selector::add_vehicle_items(), Character::armor_absorb(), string_input_popup::create_window(), Messages::display_messages(), Messages::dialog::do_filter(), inventory_column::draw(), draw_points(), diary::export_to_md(), input_context::filter_strings_by_phrase(), game::list_items(), ascii_art::load(), parse_tags(), pickup::pick_up(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu_items(), set_description(), set_profession(), set_scenario(), uilist::setup(), shortcut_print(), uilist::show(), overmap_ui::show_notes_manager(), trim_by_length(), and utf8_width().
right_print()
int right_print (const catacurses::window & w, int line, int right_indent, const nc_color & FG, const std::string & text)
Definition at line 461 of file output.cpp.
{
    const int available_width = std::max( 1, getmaxx( w ) - right_indent );
    const int x = std::max( 0, available_width - utf8_width( text, true ) );
    trim_and_print( w, point( x, line ), available_width, FG, text );
    return x;
}
References catacurses::getmaxx(), line(), trim_and_print(), and utf8_width().
Referenced by veh_interact::calc_overview(), player_morale::display(), string_input_popup::draw(), draw_bionics_titlebar(), draw_can_craft_indicator(), inventory_selector::draw_header(), draw_hidden_amount(), draw_tip(), insert_table(), game::look_around(), pickup::pick_up(), print_ranged_chance(), advanced_inventory::redraw_sidebar(), Messages::dialog::show(), and player::sort_armor().
rm_prefix()
std::string rm_prefix (std::string str, char c1 = '<', char c2 = '>')
Removes the prefix starting at the first occurrence of c1 until the first occurrence of c2.
Definition at line 1529 of file output.cpp.
{
    if( !str.empty() && str[0] == c1 ) {
        size_t pos = str.find_first_of( c2 );
        if( pos != std::string::npos ) {
            str = str.substr( pos + 1 );
        }
    }
    return str;
}
Referenced by fold_and_print_from(), print_colored_text(), and trim_by_length().
scrollable_text()
void scrollable_text (const std::function< catacurses::window()> & init_window, const std::string & title, const std::string & text)
Definition at line 352 of file output.cpp.
{
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    constexpr point text2( 1, 1 );
    input_context ctxt( "SCROLLABLE_TEXT" );
    ctxt.register_action( "UP" );
    ctxt.register_action( "DOWN" );
    ctxt.register_action( "PAGE_UP" );
    ctxt.register_action( "PAGE_DOWN" );
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    catacurses::window w;
    int width = 0;
    int height = 0;
    int text_w = 0;
    int text_h = 0;
    std::vector<std::string> lines;
    int beg_line = 0;
    int max_beg_line = 0;
    ui_adaptor ui;
    const auto screen_resize_cb = [&]( ui_adaptor & ui ) {
        w = init_window();
        width = getmaxx( w );
        height = getmaxy( w );
        text_w = std::max( 0, width - 2 );
        text_h = std::max( 0, height - 2 );
        lines = foldstring( text, text_w );
        max_beg_line = std::max( 0, static_cast<int>( lines.size() ) - text_h );
        ui.position_from_window( w );
    };
    screen_resize_cb( ui );
    ui.on_screen_resize( screen_resize_cb );
    ui.on_redraw( [&]( const ui_adaptor & ) {
        werase( w );
        draw_border( w, BORDER_COLOR, title, c_black_white );
        for( int line = beg_line, pos_y = text2.y; line < std::min<int>( beg_line + text_h, lines.size() );
             ++line, ++pos_y ) {
            nc_color dummy = c_white;
            print_colored_text( w, point( text2.x, pos_y ), dummy, dummy, lines[line] );
        }
        scrollbar().offset_x( width - 1 ).offset_y( text2.y ).content_size( lines.size() )
        .viewport_pos( std::min( beg_line, max_beg_line ) ).viewport_size( text_h ).apply( w );
        wnoutrefresh( w );
    } );
    std::string action;
    do {
        ui_manager::redraw();
        action = ctxt.handle_input();
        if( action == "UP" ) {
            if( beg_line > 0 ) {
                --beg_line;
            }
        } else if( action == "DOWN" ) {
            if( beg_line < max_beg_line ) {
                ++beg_line;
            }
        } else if( action == "PAGE_UP" ) {
            if( beg_line > text_h ) {
                beg_line -= text_h;
            } else {
                beg_line = 0;
            }
        } else if( action == "PAGE_DOWN" ) {
            // always scroll an entire page's length
            if( beg_line < max_beg_line ) {
                beg_line += text_h;
            }
        }
    } while( action != "CONFIRM" && action != "QUIT" );
}
References action, scrollbar::apply(), BORDER_COLOR, c_black_white, c_white, scrollbar::content_size(), draw_border(), foldstring(), catacurses::getmaxx(), catacurses::getmaxy(), input_context::handle_input(), init_window(), line(), scrollbar::offset_x(), scrollbar::offset_y(), print_colored_text(), ui_manager::redraw(), input_context::register_action(), PATH_INFO::title(), scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by game::disp_NPC_epilogues(), game::display_faction_epilogues(), and help::display_help().
shortcut_print() [1/2]
size_t shortcut_print (const catacurses::window & w, const point & p, nc_color text_color, nc_color shortcut_color, const std::string & fmt)
Definition at line 1543 of file output.cpp.
{
    wmove( w, p );
    return shortcut_print( w, text_color, shortcut_color, fmt );
}
References shortcut_print(), and catacurses::wmove().
Referenced by veh_interact::display_esc(), veh_interact::display_mode(), draw_header(), help::draw_menu(), game::list_monsters(), snake_game::print_header(), game::reset_item_list_state(), shortcut_print(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), safemode::show(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), main_menu::world_tab(), and zones_manager_shortcuts().
shortcut_print() [2/2]
size_t shortcut_print (const catacurses::window & w, nc_color text_color, nc_color shortcut_color, const std::string & fmt)
Definition at line 1551 of file output.cpp.
{
    std::string text = shortcut_text( shortcut_color, fmt );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    print_colored_text( w, point( -1, -1 ), text_color, text_color, text );
    return utf8_width( remove_color_tags( text ) );
}
References print_colored_text(), remove_color_tags(), shortcut_text(), and utf8_width().
shortcut_text()
std::string shortcut_text (nc_color shortcut_color, const std::string & fmt)
Definition at line 1562 of file output.cpp.
{
    size_t pos = fmt.find_first_of( '<' );
    size_t pos_end = fmt.find_first_of( '>' );
    if( pos_end != std::string::npos && pos < pos_end ) {
        size_t sep = std::min( fmt.find_first_of( '|', pos ), pos_end );
        std::string prestring = fmt.substr( 0, pos );
        std::string poststring = fmt.substr( pos_end + 1, std::string::npos );
        std::string shortcut = fmt.substr( pos + 1, sep - pos - 1 );
        return prestring + colorize( shortcut, shortcut_color ) + poststring;
    }
    // no shortcut?
    return fmt;
}
References colorize().
Referenced by main_menu::opening_screen(), main_menu::print_menu_items(), and shortcut_print().
special_symbol()
int special_symbol (int sym)
Definition at line 1095 of file output.cpp.
{
    switch( sym ) {
        case 'j':
            return LINE_XOXO;
        case 'h':
            return LINE_OXOX;
        case 'c':
            return LINE_XXXX;
        case 'y':
            return LINE_OXXO;
        case 'u':
            return LINE_OOXX;
        case 'n':
            return LINE_XOOX;
        case 'b':
            return LINE_XXOO;
        default:
            return sym;
    }
}
References LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, and LINE_XXXX.
Referenced by veh_interact::display_list(), veh_interact::display_veh(), veh_interact::do_change_shape(), veh_interact::do_install(), map::draw_from_above(), and map::draw_maptile().
split_by_color()
std::vector< std::string > split_by_color (const std::string & s)
Definition at line 131 of file output.cpp.
{
    std::vector<std::string> ret;
    std::vector<size_t> tag_positions = get_tag_positions( s );
    size_t last_pos = 0;
    for( size_t tag_position : tag_positions ) {
        ret.push_back( s.substr( last_pos, tag_position - last_pos ) );
        last_pos = tag_position;
    }
    // and the last (or only) one
    ret.push_back( s.substr( last_pos, std::string::npos ) );
    return ret;
}
References get_tag_positions(), and cata::hash64_detail::ret.
Referenced by fold_and_print_from(), print_colored_text(), and trim_by_length().
string_from_int()
std::string string_from_int (const catacurses::chtype ch) inline
Definition at line 88 of file output.h.
{
    catacurses::chtype charcode = ch;
    // LINE_NESW  - X for on, O for off
    switch( ch ) {
        case LINE_XOXO:
            charcode = LINE_XOXO_C;
            break;
        case LINE_OXOX:
            charcode = LINE_OXOX_C;
            break;
        case LINE_XXOO:
            charcode = LINE_XXOO_C;
            break;
        case LINE_OXXO:
            charcode = LINE_OXXO_C;
            break;
        case LINE_OOXX:
            charcode = LINE_OOXX_C;
            break;
        case LINE_XOOX:
            charcode = LINE_XOOX_C;
            break;
        case LINE_XXOX:
            charcode = LINE_XXOX_C;
            break;
        case LINE_XXXO:
            charcode = LINE_XXXO_C;
            break;
        case LINE_XOXX:
            charcode = LINE_XOXX_C;
            break;
        case LINE_OXXX:
            charcode = LINE_OXXX_C;
            break;
        case LINE_XXXX:
            charcode = LINE_XXXX_C;
            break;
        default:
            charcode = ch;
            break;
    }
    char buffer[2] = { static_cast<char>( charcode ), '\0' };
    return buffer;
}
References LINE_OOXX, LINE_OOXX_C, LINE_OXOX, LINE_OXOX_C, LINE_OXXO, LINE_OXXO_C, LINE_OXXX, LINE_OXXX_C, LINE_XOOX, LINE_XOOX_C, LINE_XOXO, LINE_XOXO_C, LINE_XOXX, LINE_XOXX_C, LINE_XXOO, LINE_XXOO_C, LINE_XXOX, LINE_XXOX_C, LINE_XXXO, LINE_XXXO_C, LINE_XXXX, and LINE_XXXX_C.
Referenced by unicode_codepoint_from_symbol_reader().
trim_and_print() [1/3]
template<typename ... Args> void trim_and_print (const catacurses::window & w, const point & begin, const int width, const nc_color & base_color, const char *const mes, Args &&... args) inline
Definition at line 334 of file output.h.
{
    return trim_and_print( w, begin, width, base_color,
                           string_format( mes, std::forward<Args>( args )... ) );
}
References string_format(), and trim_and_print().
trim_and_print() [2/3]
template<typename ... Args> void trim_and_print (const catacurses::window & w, const point & begin, const int width, const nc_color & base_color, const report_color_error color_error, const char *const mes, Args &&... args) inline
Definition at line 342 of file output.h.
{
    return trim_and_print( w, begin, width, base_color,
                           string_format( mes, std::forward<Args>( args )... ),
                           color_error );
}
References string_format(), and trim_and_print().
trim_and_print() [3/3]
void trim_and_print (const catacurses::window & w, const point & begin, int width, const nc_color & base_color, const std::string & text, report_color_error color_error = report_color_error::yes)
Prints a single line of text.
The text is automatically trimmed to fit into the given width. The function handles color_tags correctly.
Parameters
w Window we are printing in
begin The coordinates of line start (curses coordinates)
width Maximal width of the printed line, if the text is longer, it is cut off.
base_color The initially used color. This can be overridden using color tags.
text Actual message to print
Definition at line 214 of file output.cpp.
{
    std::string sText = trim_by_length( text, width );
    nc_color dummy = base_color;
    print_colored_text( w, begin, dummy, base_color, sText, color_error );
}
References print_colored_text(), and trim_by_length().
Referenced by veh_interact::calc_overview(), center_print(), Character::conduct_blood_analysis(), faction_manager::display(), player_morale::display(), veh_interact::display_list(), veh_interact::display_overview(), inventory_column::draw(), string_input_popup::draw(), draw_bionics_tab(), draw_effects_tab(), draw_env_compact(), inventory_selector::draw_header(), target_ui::draw_help_notice(), draw_item_info(), worldfactory::draw_mod_list(), draw_traits_tab(), draw_weapon_classic(), draw_weapon_classic_alt(), draw_weapon_labels(), target_ui::draw_window_title(), basecamp::job_assignment_ui(), game::list_items(), game::list_missions(), game::list_monsters(), pickup::pick_up(), player::power_bionics(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), game::print_items_info(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), vehicle::print_part_list(), game::print_terrain_info(), advanced_inventory::redraw_pane(), right_print(), set_description(), uilist::show(), player::sort_armor(), trim_and_print(), editmap::update_view_with_help(), trading_window::update_win(), iexamine::vending(), and basecamp::worker_assignment_ui().
trim_by_length()
std::string trim_by_length (const std::string & text, int width)
Definition at line 224 of file output.cpp.
{
    std::string sText;
    if( utf8_width( remove_color_tags( text ) ) > width ) {
        int iLength = 0;
        std::string sTempText;
        std::string sColor;
        const auto color_segments = split_by_color( text );
        for( const std::string &seg : color_segments ) {
            sColor.clear();
            if( !seg.empty() && ( seg.substr( 0, 7 ) == "<color_" || seg.substr( 0, 7 ) == "</color" ) ) {
                sTempText = rm_prefix( seg );
                if( seg.substr( 0, 7 ) == "<color_" ) {
                    sColor = seg.substr( 0, seg.find( '>' ) + 1 );
                }
            } else {
                sTempText = seg;
            }
            const int iTempLen = utf8_width( sTempText );
            iLength += iTempLen;
            if( iLength > width ) {
                int pos = 0;
                cursorx_to_position( sTempText.c_str(), iTempLen - ( iLength - width ) - 1, &pos, -1 );
                sTempText = sTempText.substr( 0, pos ) + "\u2026";
            }
            sText += sColor + sTempText;
            if( !sColor.empty() ) {
                sText += "</color>";
            }
            if( iLength > width ) {
                break;
            }
        }
    } else {
        sText = text;
    }
    return sText;
}
References cursorx_to_position(), remove_color_tags(), rm_prefix(), coords::seg, split_by_color(), and utf8_width().
Referenced by disassemble_activity_actor::get_progress_message(), ascii_art::load(), select_crafting_recipe(), trim_and_print(), and game::zones_manager().
update_color_stack()
color_tag_parse_result::tag_type update_color_stack (std::stack< nc_color > & color_stack, const std::string & seg, report_color_error color_error = report_color_error::yes)
Adds the color represented by the next color tag found in the string to the top of the stack.
If color_error == report_color_error::yes a debugmsg will be shown when the tag is not valid.
Definition at line 164 of file output.cpp.
{
    color_tag_parse_result tag = get_color_from_tag( seg, color_error );
    switch( tag.type ) {
        case color_tag_parse_result::open_color_tag:
            color_stack.push( tag.color );
            break;
        case color_tag_parse_result::close_color_tag:
            if( !color_stack.empty() ) {
                color_stack.pop();
            }
            break;
        case color_tag_parse_result::non_color_tag:
            // Do nothing
            break;
    }
    return tag.type;
}
References color_tag_parse_result::close_color_tag, color_tag_parse_result::color, get_color_from_tag(), color_tag_parse_result::non_color_tag, color_tag_parse_result::open_color_tag, coords::seg, and color_tag_parse_result::type.
Referenced by fold_and_print_from(), and print_colored_text().
word_rewrap()
std::string word_rewrap (const std::string & ins, int width, uint32_t split = ' ')
Definition at line 1136 of file output.cpp.
{
    std::string o;
    // find non-printing tags
    std::vector<size_t> tag_positions = get_tag_positions( in );
    int lastwb  = 0; //last word break
    int lastout = 0;
    const char *instr = in.c_str();
    bool skipping_tag = false;
    bool just_wrapped = false;
    for( int j = 0, x = 0; j < static_cast<int>( in.size() ); ) {
        const char *ins = instr + j;
        int len = ANY_LENGTH;
        uint32_t uc = UTF8_getch( &ins, &len );
        if( uc == '<' ) { // maybe skip non-printing tag
            std::vector<size_t>::iterator it;
            for( it = tag_positions.begin(); it != tag_positions.end(); ++it ) {
                if( static_cast<int>( *it ) == j ) {
                    skipping_tag = true;
                    break;
                }
            }
        }
        const int old_j = j;
        j += ANY_LENGTH - len;
        if( skipping_tag ) {
            if( uc == '>' ) {
                skipping_tag = false;
            }
            continue;
        }
        if( just_wrapped && uc == ' ' ) { // ignore spaces after wrapping
            lastwb = lastout = j;
            continue;
        }
        x += mk_wcwidth( uc );
        if( uc == split || uc >= 0x2E80 ) { // param split (default ' ') or CJK characters
            if( x <= width ) {
                lastwb = j; // break after character
            } else {
                lastwb = old_j; // break before character
            }
        }
        if( x > width ) {
            if( lastwb == lastout ) {
                lastwb = old_j;
            }
            // old_j may equal to lastout, this checks it and ensures there's at least one character in the line.
            if( lastwb == lastout ) {
                lastwb = j;
            }
            for( int k = lastout; k < lastwb; k++ ) {
                o += in[k];
            }
            o += '\n';
            x = 0;
            lastout = j = lastwb;
            just_wrapped = true;
        } else {
            just_wrapped = false;
        }
    }
    for( int k = lastout; k < static_cast<int>( in.size() ); k++ ) {
        o += in[k];
    }
    return o;
}
References ANY_LENGTH, get_tag_positions(), mk_wcwidth(), and UTF8_getch().
Referenced by foldstring().
wprintz() [1/2]
template<typename ... Args> void wprintz (const catacurses::window & w, const nc_color & FG, const char *const mes, Args &&... args) inline
Definition at line 386 of file output.h.
{
    wprintz( w, FG, string_format( mes, std::forward<Args>( args )... ) );
}
References string_format(), and wprintz().
wprintz() [2/2]
void wprintz (const catacurses::window & w, const nc_color & FG, const std::string & text)
Definition at line 2043 of file output.cpp.
{
    wattron( w, FG );
    wprintw( w, text );
    wattroff( w, FG );
}
References catacurses::wattroff(), catacurses::wattron(), and catacurses::wprintw().
Referenced by game::cleanup_at_end(), decorate_panel(), draw_caravan_categories(), draw_caravan_items(), inventory_selector::draw_footer(), draw_health_classic(), target_ui::draw_help_notice(), draw_limb2(), draw_limb_health(), draw_limb_narrow(), draw_loc_labels(), map::draw_maptile(), anonymous_namespace{animation.cpp}::draw_sct_curses(), query_destination_callback::draw_squares(), draw_time_graphic(), target_ui::draw_window_title(), fold_and_print_from(), game::list_items(), game::list_monsters(), pickup::pick_up(), worldfactory::pick_world(), print_colored_text(), vehicle::print_fuel_indicator(), vehicle::print_fuel_indicators(), advanced_inventory::print_header(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), vehicle::print_part_list(), game::print_terrain_info(), game::reset_item_list_state(), set_description(), set_scenario(), set_skills(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), uilist::show(), robot_finds_kitten::show(), options_manager::show(), worldfactory::show_modselection_window(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), main_menu::world_tab(), and wprintz().
wputch()
void wputch (const catacurses::window & w, nc_color FG, int ch)
Definition at line 470 of file output.cpp.
{
    wattron( w, FG );
    waddch( w, ch );
    wattroff( w, FG );
}
References catacurses::waddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by map::draw(), map::draw_from_above(), robot_finds_kitten::draw_kitten(), map::draw_maptile(), robot_finds_kitten::draw_robot(), draw_time_graphic(), fold_and_print_from(), worldfactory::pick_world(), set_description(), options_manager::show(), and worldfactory::show_modselection_window().
Variable Documentation
FULL_SCREEN_HEIGHT
int FULL_SCREEN_HEIGHT extern
Definition at line 56 of file output.cpp.
Referenced by defense_game::caravan(), game::cleanup_at_end(), game::disp_NPC_epilogues(), game::disp_NPCs(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), input_context::display_menu(), main_menu::display_text(), draw_caravan_borders(), draw_caravan_items(), sokoban_game::draw_level(), ensure_term_size(), query_popup::init(), Messages::dialog::init(), game_ui::init_ui(), init_window(), main_menu::init_windows(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_missions(), main(), player::power_bionics(), player::power_mutations_ui(), inventory_selector::prepare_layout(), dialogue_window::resize_dialogue(), select_crafting_recipe(), defense_game::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), color_manager::show_gui(), trading_window::show_item_data(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), and basecamp::worker_assignment_ui().
FULL_SCREEN_WIDTH
int FULL_SCREEN_WIDTH extern
Definition at line 55 of file output.cpp.
Referenced by defense_game::caravan(), game::cleanup_at_end(), basecamp::craft_description(), string_input_popup::create_window(), character_display::disp_info(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), input_context::display_menu(), dialogue_window::display_responses(), veh_interact::display_stats(), main_menu::display_text(), draw_bionics_info(), draw_caravan_borders(), draw_effects_info(), draw_encumbrance_info(), sokoban_game::draw_level(), worldfactory::draw_modselection_borders(), draw_skills_info(), draw_stats_info(), draw_traits_info(), worldfactory::edit_active_world_mods(), ensure_term_size(), get_terminal_width(), query_popup::init(), Messages::dialog::init(), init_window(), main_menu::init_windows(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_missions(), main(), worldfactory::make_new_world(), basecamp::om_upgrade_description(), worldfactory::pick_world(), player::power_bionics(), player::power_mutations_ui(), snake_game::print_header(), main_menu::print_menu(), query_for_template_name(), dialogue_window::resize_dialogue(), select_crafting_recipe(), defense_game::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), and basecamp::worker_assignment_ui().
OVERMAP_LEGEND_WIDTH
int OVERMAP_LEGEND_WIDTH extern
Definition at line 63 of file output.cpp.
Referenced by overmap_ui::display(), and overmap_ui::search().
OVERMAP_WINDOW_HEIGHT
int OVERMAP_WINDOW_HEIGHT extern
Definition at line 58 of file output.cpp.
Referenced by overmap_ui::display(), and overmap_ui::draw_ascii().
OVERMAP_WINDOW_TERM_HEIGHT
int OVERMAP_WINDOW_TERM_HEIGHT extern
Definition at line 61 of file output.cpp.
Referenced by overmap_ui::display().
OVERMAP_WINDOW_TERM_WIDTH
int OVERMAP_WINDOW_TERM_WIDTH extern
Definition at line 60 of file output.cpp.
Referenced by overmap_ui::display().
OVERMAP_WINDOW_WIDTH
int OVERMAP_WINDOW_WIDTH extern
Definition at line 59 of file output.cpp.
Referenced by overmap_ui::display(), and overmap_ui::draw_ascii().
POSX
int POSX extern
Definition at line 49 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), debug_menu::debug(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), draw_critter_internal(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), game::draw_ter(), draw_trail(), game::draw_veh_dir_indicator(), game::mon_info_update(), and anonymous_namespace{animation.cpp}::relative_view_pos().
POSY
int POSY extern
Definition at line 50 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), debug_menu::debug(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), draw_critter_internal(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), game::draw_ter(), draw_trail(), game::draw_veh_dir_indicator(), game::mon_info_update(), and anonymous_namespace{animation.cpp}::relative_view_pos().
SCT
scrollingcombattext SCT extern
Definition at line 65 of file output.cpp.
Referenced by Character::absorb_hit(), Character::armor_absorb(), Character::deal_damage(), anonymous_namespace{animation.cpp}::draw_sct_curses(), game::get_player_input(), player_hit_message(), ranged::print_dmg_msg(), and game::setup().
TERMX
int TERMX extern
Definition at line 47 of file output.cpp.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), veh_interact::allocate_windows(), defense_game::caravan(), game::cleanup_at_end(), game_menus::inv::compare(), Character::conduct_blood_analysis(), game::create_or_get_main_ui_adaptor(), string_input_popup::create_window(), diary_window_position(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), veh_interact::display_grid(), help::display_help(), input_context::display_menu(), veh_interact::display_stats(), main_menu::display_text(), draw_character_tabs(), worldfactory::draw_modselection_borders(), game::draw_panels(), draw_sorting_indicator(), worldfactory::edit_active_world_mods(), edit_json(), game::extended_description(), generate_weather_anim_frame(), query_popup::init(), Messages::dialog::init(), game_ui::init_ui(), init_window(), target_ui::init_window_and_input(), main_menu::init_windows(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), worldfactory::make_new_world(), new_centered_win(), pickup::pick_up(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), player::power_bionics(), player::power_mutations_ui(), inventory_selector::prepare_layout(), advanced_inventory::print_items(), loot_options::query_loot(), game::reset_item_list_state(), dialogue_window::resize_dialogue(), inventory_selector::resize_window(), robot_finds_kitten::robot_finds_kitten(), overmap_ui::search(), select_crafting_recipe(), player::select_requirements(), known_magic::select_spell(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), defense_game::setup(), uilist::setup(), trading_window::setup_win(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), diary::show_diary_ui(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), uis_padding(), trading_window::update_win(), computer_session::use(), iexamine::vending(), debug_menu::wishitem(), debug_menu::wishmonster(), debug_menu::wishmutate(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_draw_borders().
TERMY
int TERMY extern
Definition at line 48 of file output.cpp.
Referenced by computer_session::action_list_bionics(), veh_interact::allocate_windows(), defense_game::caravan(), game::cleanup_at_end(), game_menus::inv::compare(), Character::conduct_blood_analysis(), game::create_or_get_main_ui_adaptor(), editmap::create_or_get_ui_adaptor(), string_input_popup::create_window(), diary_window_position(), character_display::disp_info(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), input_context::display_menu(), main_menu::display_text(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), game::draw_panels(), worldfactory::edit_active_world_mods(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), game::extended_description(), generate_weather_anim_frame(), query_popup::init(), Messages::dialog::init(), game_ui::init_ui(), init_window(), target_ui::init_window_and_input(), main_menu::init_windows(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), worldfactory::make_new_world(), editmap::mapgen_preview(), new_centered_win(), pickup::pick_up(), worldfactory::pick_world(), player::power_bionics(), player::power_mutations_ui(), inventory_selector::prepare_layout(), loot_options::query_loot(), game::reset_item_list_state(), dialogue_window::resize_dialogue(), inventory_selector::resize_window(), robot_finds_kitten::robot_finds_kitten(), examine_item_menu::run(), select_crafting_recipe(), known_magic::select_spell(), set_description(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), defense_game::setup(), uilist::setup(), trading_window::setup_win(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), diary::show_diary_ui(), color_manager::show_gui(), trading_window::show_item_data(), worldfactory::show_modselection_window(), show_scores_ui(), worldfactory::show_worldgen_tab_confirm(), player::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), computer_session::use(), iexamine::vending(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_draw_borders().
TERRAIN_WINDOW_HEIGHT
int TERRAIN_WINDOW_HEIGHT extern
Definition at line 52 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), generate_weather_anim_frame(), and is_valid_in_w_terrain().
TERRAIN_WINDOW_TERM_HEIGHT
int TERRAIN_WINDOW_TERM_HEIGHT extern
Definition at line 54 of file output.cpp.
Referenced by game::create_or_get_main_ui_adaptor().
TERRAIN_WINDOW_TERM_WIDTH
int TERRAIN_WINDOW_TERM_WIDTH extern
Definition at line 53 of file output.cpp.
Referenced by game::create_or_get_main_ui_adaptor().
TERRAIN_WINDOW_WIDTH
int TERRAIN_WINDOW_WIDTH extern
Definition at line 51 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), generate_weather_anim_frame(), and is_valid_in_w_terrain().