Cataclysm BN: src/overmap.cpp File Reference
overmap.cpp File Reference
#include "om_direction.h"
#include "omdata.h"
#include "overmap_special.h"
#include "overmap.h"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstring>
#include <exception>
#include <memory>
#include <numeric>
#include <ostream>
#include <set>
#include <unordered_set>
#include <vector>
#include "assign.h"
#include "basecamp.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_id.h"
#include "coordinate_conversions.h"
#include "debug.h"
#include "flood_fill.h"
#include "fstream_utils.h"
#include "game.h"
#include "generic_factory.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapbuffer.h"
#include "mapgen.h"
#include "math_defines.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "name.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "overmap_connection.h"
#include "overmap_location.h"
#include "overmap_noise.h"
#include "overmap_types.h"
#include "overmapbuffer.h"
#include "regional_settings.h"
#include "rng.h"
#include "rotatable_symbols.h"
#include "simple_pathfinding.h"
#include "string_formatter.h"
#include "string_utils.h"
#include "text_snippets.h"
#include "translations.h"
Classes
struct om_lines::type
Namespaces
namespace om_lines
namespace anonymous_namespace{overmap.cpp}
namespace io
Macros
#define dbg(x) DebugLogFL((x),DC::MapGen)
#define BUILDINGCHANCE 4
#define MIN_ANT_SIZE 8
#define MAX_ANT_SIZE 20
#define MIN_GOO_SIZE 1
#define MAX_GOO_SIZE 2
Functions
constexpr size_t om_lines::rotate (size_t line, om_direction::type dir)
constexpr size_t om_lines::set_segment (size_t line, om_direction::type dir)
constexpr bool om_lines::has_segment (size_t line, om_direction::type dir)
constexpr bool om_lines::is_straight (size_t line)
static size_t om_lines::from_dir (om_direction::type dir)
bool operator== (const int_id< oter_t > &lhs, const char *rhs)
bool operator!= (const int_id< oter_t > &lhs, const char *rhs)
template<>
std::string io::enum_to_string< lab_type > (lab_type data)
static void set_oter_ids ()
bool is_river (const oter_id &ter)
bool is_river_or_lake (const oter_id &ter)
bool is_ot_match (const std::string &name, const oter_id &oter, const ot_match_type match_type)
Determine if the provided name is a match with the provided overmap terrain based on the specified match type.
static void load_overmap_terrain_mapgens (const JsonObject &jo, const std::string &id_base, const std::string &suffix="")
static void fixup_labs (overmap &om)
static void elevate_bridges (overmap &om, const std::vector< point_om_omt > &bridge_points, const std::string &bridge_overpass_id, const std::string &bridge_under_id, const std::string &bridgehead_ground_id, const std::string &bridgehead_ramp_id, const std::string &bridge_flat_ew_id, const std::string &bridge_flat_ns_id)
static pf::directed_path< point_om_omt > straight_path (const point_om_omt &source, om_direction::type dir, size_t len)
om_direction::type rotate_internal (om_direction::type dir, int step)
om_special_sectors get_sectors (const int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
template<>
std::string io::enum_to_string< ot_match_type > (ot_match_type data)
std::string oter_no_dir (const oter_id &oter)
Returns the string of oter without any directional suffix.
om_direction::type oter_get_rotation_dir (const oter_id &oter)
Returns oter rotation direction value.
int oter_get_rotations (const oter_id &oter)
Returns number of clockwise rotations 0, 1, 2, 3 respectively if the suffix is _north, _east, _south, _west.
const std::string & oter_get_rotation_string (const oter_id &oter)
Returns the directional suffix or "" if there isn't one.
bool belongs_to_connection (const overmap_connection_id &id, const oter_id &oter)
Determine whether provided tile belongs to overmap connection.
Variables
static const efftype_id effect_pet ("pet")
static const species_id ZOMBIE ("ZOMBIE")
static const mongroup_id GROUP_CHUD ("GROUP_CHUD")
static const mongroup_id GROUP_DIMENSIONAL_SURFACE ("GROUP_DIMENSIONAL_SURFACE")
static const mongroup_id GROUP_RIVER ("GROUP_RIVER")
static const mongroup_id GROUP_SEWER ("GROUP_SEWER")
static const mongroup_id GROUP_SWAMP ("GROUP_SWAMP")
static const mongroup_id GROUP_WORM ("GROUP_WORM")
static const mongroup_id GROUP_ZOMBIE ("GROUP_ZOMBIE")
oter_id ot_null
oter_id ot_crater
oter_id ot_field
oter_id ot_forest
oter_id ot_forest_thick
oter_id ot_forest_water
oter_id ot_river_center
const std::array< std::string, 5 > om_lines::mapgen_suffixes
const std::array< type, 1+om_direction::bits > om_lines::all
const size_t om_lines::size = all.size()
const size_t om_lines::invalid = 0
t_regional_settings_map region_settings_map
generic_factory< overmap_land_use_code > anonymous_namespace{overmap.cpp}::land_use_codes ("overmap land use codes")
generic_factory< oter_type_t > anonymous_namespace{overmap.cpp}::terrain_types ("overmap terrain type")
generic_factory< oter_t > anonymous_namespace{overmap.cpp}::terrains ("overmap terrain")
generic_factory< overmap_special > anonymous_namespace{overmap.cpp}::specials ("overmap special")
std::map< enum radio_type, std::string > radio_type_names
Macro Definition Documentation
BUILDINGCHANCE
#define BUILDINGCHANCE 4
Definition at line 75 of file overmap.cpp.
dbg
#define dbg (x) DebugLogFL((x),DC::MapGen)
Definition at line 73 of file overmap.cpp.
MAX_ANT_SIZE
#define MAX_ANT_SIZE 20
Definition at line 77 of file overmap.cpp.
MAX_GOO_SIZE
#define MAX_GOO_SIZE 2
Definition at line 79 of file overmap.cpp.
MIN_ANT_SIZE
#define MIN_ANT_SIZE 8
Definition at line 76 of file overmap.cpp.
MIN_GOO_SIZE
#define MIN_GOO_SIZE 1
Definition at line 78 of file overmap.cpp.
Function Documentation
belongs_to_connection()
bool belongs_to_connection (const overmap_connection_id & id, const oter_id & oter)
Determine whether provided tile belongs to overmap connection.
Definition at line 5051 of file overmap.cpp.
{
    return is_ot_match( id->default_terrain.str(), oter, ot_match_type::type );
}
References int_id< T >::id(), is_ot_match(), and type.
Referenced by overmap::random_special_rotation().
elevate_bridges()
static void elevate_bridges (overmap & om, const std::vector< point_om_omt > & bridge_points, const std::string & bridge_overpass_id, const std::string & bridge_under_id, const std::string & bridgehead_ground_id, const std::string & bridgehead_ramp_id, const std::string & bridge_flat_ew_id, const std::string & bridge_flat_ns_id) static
Definition at line 1962 of file overmap.cpp.
{
    // Check bridgeheads and 1-tile-long bridges
    std::vector<std::pair<point_om_omt, om_direction::type>> bridgehead_points;
    std::set<point_om_omt> flatten_points;
    for( const point_om_omt &bp : bridge_points ) {
        tripoint_om_omt bp_om( bp, 0 );
        const oter_id &ot_here = om.ter( bp_om );
        const std::string &type_here = ot_here->get_type_id().str();
        const om_direction::type dir = oter_get_rotation_dir( ot_here );
        if( dir == om_direction::type::invalid ) {
            // Shouldn't happen
            debugmsg( "Potential bridgehead %s at %s has invalid rotation.", ot_here.id(), bp_om.to_string() );
            continue;
        }
        point vec = om_direction::displace( dir );
        const bool is_bridge_fwd = is_ot_match( type_here, om.ter( bp_om + vec ), ot_match_type::type );
        const bool is_bridge_bck = is_ot_match( type_here, om.ter( bp_om - vec ), ot_match_type::type );
        if( is_bridge_fwd ^ is_bridge_bck ) {
            om_direction::type ramp_facing = is_bridge_fwd ? om_direction::opposite( dir ) : dir;
            bridgehead_points.emplace_back( bp, ramp_facing );
        } else if( !is_bridge_fwd && !is_bridge_bck ) {
            flatten_points.emplace( bp );
        }
    }
    // Flatten 1-tile-long bridges
    for( const point_om_omt &bp : flatten_points ) {
        tripoint_om_omt p( bp, 0 );
        om_direction::type rot = oter_get_rotation_dir( om.ter( p ) );
        if( rot == om_direction::type::east || rot == om_direction::type::west ) {
            om.ter_set( p, oter_id( bridge_flat_ew_id ) );
        } else {
            om.ter_set( p, oter_id( bridge_flat_ns_id ) );
        }
    }
    // Put bridge points
    for( const point_om_omt &bp : bridge_points ) {
        if( flatten_points.count( bp ) != 0 ) {
            continue;
        }
        tripoint_om_omt p( bp, 0 );
        const std::string &rot_sfx = oter_get_rotation_string( om.ter( p ) );
        om.ter_set( p + tripoint_above, oter_id( bridge_overpass_id + rot_sfx ) );
        om.ter_set( p, oter_id( bridge_under_id + rot_sfx ) );
    }
    // Put bridgeheads
    for( const std::pair<point_om_omt, om_direction::type> &bhp : bridgehead_points ) {
        tripoint_om_omt p( bhp.first, 0 );
        const std::string &dir_suffix = om_direction::all_suffixes[static_cast<int>( bhp.second )];
        om.ter_set( p, oter_id( bridgehead_ground_id + dir_suffix ) );
        om.ter_set( p + tripoint_above, oter_id( bridgehead_ramp_id + dir_suffix ) );
    }
}
References om_direction::all_suffixes, debugmsg, om_direction::displace(), om_direction::east, oter_t::get_type_id(), int_id< T >::id(), om_direction::invalid, is_ot_match(), coords::om, om_direction::opposite(), oter_get_rotation_dir(), oter_get_rotation_string(), string_id< T >::str(), coords::coord_point< Point, Origin, Scale >::to_string(), tripoint_above, type, and om_direction::west.
Referenced by overmap::generate_over().
fixup_labs()
static void fixup_labs (overmap & om) static
Definition at line 1586 of file overmap.cpp.
{
    if( om.pos() != point_abs_om( point_zero ) ) {
        return;
    }
    bool has_endgame = false;
    for( lab &l : om.labs ) {
        if( l.type != lab_type::central ) {
            continue;
        }
        auto lowest = std::min_element( l.finales.begin(), l.finales.end(),
        []( const tripoint_om_omt & l, const tripoint_om_omt & r ) {
            return l.z() < r.z();
        } );
        if( lowest == l.finales.end() ) {
            auto lowest_regular = std::min_element( l.tiles.begin(), l.tiles.end(),
            []( const tripoint_om_omt & l, const tripoint_om_omt & r ) {
                return l.z() < r.z();
            } );
            debugmsg( "Endgame lab was generated with no finales.  Lowest tile: (%s).",
                      lowest_regular->to_string() );
            continue;
        }
        om.ter_set( *lowest, oter_id( "central_lab_endgame" ) );
        has_endgame = true;
    }
    if( !has_endgame ) {
        debugmsg( _( "No endgame lab was generated." ) );
    }
}
References _, central, debugmsg, lab::finales, coords::om, point_zero, and lab::type.
Referenced by overmap::generate().
get_sectors()
om_special_sectors get_sectors (int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
Parameters
sector_width used to divide the OMAPX by OMAPY map into sectors.
Definition at line 4417 of file overmap.cpp.
{
    std::vector<point_om_omt> res;
    res.reserve( ( OMAPX / sector_width ) * ( OMAPY / sector_width ) );
    for( int x = 0; x < OMAPX; x += sector_width ) {
        for( int y = 0; y < OMAPY; y += sector_width ) {
            res.emplace_back( x, y );
        }
    }
    std::shuffle( res.begin(), res.end(), rng_get_engine() );
    return om_special_sectors{ res, sector_width };
}
References OMAPX, OMAPY, and rng_get_engine().
Referenced by overmapbuffer::place_special(), and overmap::place_specials().
is_ot_match()
bool is_ot_match (const std::string & name, const oter_id & oter, ot_match_type match_type)
Determine if the provided name is a match with the provided overmap terrain based on the specified match type.
Parameters
name is the name we're looking for.
oter is the overmap terrain id we're comparing our name with.
match_type is the matching rule to use when comparing the two values.
Definition at line 568 of file overmap.cpp.
{
    static const auto is_ot = []( const std::string & otype, const oter_id & oter ) {
        return otype == oter.id().str();
    };
    static const auto is_ot_type = []( const std::string & otype, const oter_id & oter ) {
        // Is a match if the base type is the same which will allow for handling rotations/linear features
        // but won't incorrectly match other locations that happen to contain the substring.
        return otype == oter->get_type_id().str();
    };
    static const auto is_ot_prefix = []( const std::string & otype, const oter_id & oter ) {
        const size_t oter_size = oter.id().str().size();
        const size_t compare_size = otype.size();
        if( compare_size > oter_size ) {
            return false;
        }
        const auto &oter_str = oter.id();
        if( oter_str.str().compare( 0, compare_size, otype ) != 0 ) {
            return false;
        }
        // check if it's a full match
        if( compare_size == oter_size ) {
            return true;
        }
        // only okay for partial if next char is an underscore
        return oter_str.str()[compare_size] == '_';
    };
    static const auto is_ot_subtype = []( const std::string & otype, const oter_id & oter ) {
        // Checks for any partial match.
        return strstr( oter.id().c_str(), otype.c_str() );
    };
    switch( match_type ) {
        case ot_match_type::exact:
            return is_ot( name, oter );
        case ot_match_type::type:
            return is_ot_type( name, oter );
        case ot_match_type::prefix:
            return is_ot_prefix( name, oter );
        case ot_match_type::contains:
            return is_ot_subtype( name, oter );
        default:
            return false;
    }
}
References string_id< T >::c_str(), contains, exact, oter_t::get_type_id(), int_id< T >::id(), om_direction::name(), prefix, string_id< T >::str(), and type.
Referenced by computer_session::action_map_sewer(), computer_session::action_map_subway(), belongs_to_connection(), overmap::build_lab(), overmap::build_tunnel(), overmap::check_ot(), overmap_ui::draw_ascii(), map::draw_connections(), map::draw_lab(), map::draw_map(), map::draw_mine(), map::draw_slimepit(), elevate_bridges(), overmap::find_random_omt(), overmap::generate_over(), overmap::generate_sub(), get_local_windpower(), get_terrain_cost(), overmap::good_river(), mission::is_complete(), is_ramp(), overmap::lay_out_street(), mapgen_ants_generic(), mapgen_lake_shore(), MapExtras::mx_bandits_block(), MapExtras::mx_minefield(), MapExtras::mx_roadblock(), MapExtras::mx_roadworks(), overmap::place_forest_trailheads(), overmap::place_forest_trails(), mission_start::place_npc_software(), overmap::place_radios(), overmap::place_special(), overmap::place_swamps(), talk_function::start_camp(), and jmapgen_nested::neighborhood_check::test().
is_river()
bool is_river (const oter_id & ter)
Definition at line 558 of file overmap.cpp.
{
    return ter->is_river();
}
References oter_t::is_river().
Referenced by basecamp::combat_mission_return(), companion_travel_time_calc(), overmap::place_lakes(), overmap::place_rivers(), overmap::place_roads(), and overmapbuffer::reveal_route().
is_river_or_lake()
bool is_river_or_lake (const oter_id & ter)
Definition at line 563 of file overmap.cpp.
{
    return ter->is_river() || ter->is_lake() || ter->is_lake_shore();
}
References oter_t::is_lake(), oter_t::is_lake_shore(), and oter_t::is_river().
Referenced by overmap_ui::get_overmap_path_to(), overmap::good_river(), game::perhaps_add_random_npc(), and overmap::place_mongroups().
load_overmap_terrain_mapgens()
static void load_overmap_terrain_mapgens (const JsonObject & jo, const std::string & id_base, const std::string & suffix = "") static
Definition at line 625 of file overmap.cpp.
{
    const std::string fmapkey( id_base + suffix );
    const std::string jsonkey( "mapgen" + suffix );
    register_mapgen_function( fmapkey );
    if( jo.has_array( jsonkey ) ) {
        for( JsonObject jio : jo.get_array( jsonkey ) ) {
            load_mapgen_function( jio, fmapkey, point_zero );
        }
    }
}
References JsonObject::get_array(), JsonObject::has_array(), load_mapgen_function(), point_zero, and register_mapgen_function().
Referenced by oter_type_t::load().
operator!=()
bool operator!= (const int_id< oter_t > & lhs, const char * rhs)
Definition at line 332 of file overmap.cpp.
{
    return !( lhs == rhs );
}
operator==()
bool operator== (const int_id< oter_t > & lhs, const char * rhs)
Definition at line 327 of file overmap.cpp.
{
    return lhs.id().str() == rhs;
}
References int_id< T >::id(), and string_id< T >::str().
oter_get_rotation_dir()
om_direction::type oter_get_rotation_dir (const oter_id & oter)
Returns oter rotation direction value.
Definition at line 5030 of file overmap.cpp.
{
    for( const om_direction::type &rot : om_direction::all ) {
        const std::string &rot_s = om_direction::get_suffix( rot );
        if( string_ends_with( oter.id().str(), rot_s ) ) {
            return rot;
        }
    }
    return om_direction::type::invalid;
}
References om_direction::all, om_direction::get_suffix(), int_id< T >::id(), om_direction::invalid, string_id< T >::str(), and string_ends_with().
Referenced by elevate_bridges(), oter_get_rotation_string(), and oter_get_rotations().
oter_get_rotation_string()
const std::string & oter_get_rotation_string (const oter_id & oter)
Returns the directional suffix or "" if there isn't one.
Returned reference is kept alive during the whole program execution.
Definition at line 5046 of file overmap.cpp.
{
    return om_direction::get_suffix( oter_get_rotation_dir( oter ) );
}
References om_direction::get_suffix(), and oter_get_rotation_dir().
Referenced by basecamp::define_camp(), and elevate_bridges().
oter_get_rotations()
int oter_get_rotations (const oter_id & oter)
Returns number of clockwise rotations 0, 1, 2, 3 respectively if the suffix is _north, _east, _south, _west.
Returns 0 if there's no suffix.
Definition at line 5041 of file overmap.cpp.
{
    return om_direction::get_num_cw_rotations( oter_get_rotation_dir( oter ) );
}
References om_direction::get_num_cw_rotations(), and oter_get_rotation_dir().
Referenced by update_mapgen_function_json::update_map().
oter_no_dir()
std::string oter_no_dir (const oter_id & oter)
Returns the string of oter without any directional suffix.
Definition at line 5009 of file overmap.cpp.
{
    std::string base_oter_id = oter.id().c_str();
    size_t oter_len = base_oter_id.size();
    if( oter_len > 7 ) {
        if( base_oter_id.substr( oter_len - 6, 6 ) == "_south" ) {
            return base_oter_id.substr( 0, oter_len - 6 );
        } else if( base_oter_id.substr( oter_len - 6, 6 ) == "_north" ) {
            return base_oter_id.substr( 0, oter_len - 6 );
        }
    }
    if( oter_len > 6 ) {
        if( base_oter_id.substr( oter_len - 5, 5 ) == "_west" ) {
            return base_oter_id.substr( 0, oter_len - 5 );
        } else if( base_oter_id.substr( oter_len - 5, 5 ) == "_east" ) {
            return base_oter_id.substr( 0, oter_len - 5 );
        }
    }
    return base_oter_id;
}
References string_id< T >::c_str(), and int_id< T >::id().
Referenced by recipe_group::get_recipes_by_id(), and conditional_t< T >::set_at_om_location().
rotate_internal()
om_direction::type rotate_internal (om_direction::type dir, int step) inline
Definition at line 4182 of file overmap.cpp.
{
    if( dir == om_direction::type::invalid ) {
        debugmsg( "Can't rotate an invalid overmap rotation." );
        return dir;
    }
    step = step % om_direction::size;
    return static_cast<om_direction::type>( ( static_cast<int>( dir ) + step ) % om_direction::size );
}
References debugmsg, om_direction::invalid, and om_direction::size.
Referenced by om_direction::add(), om_direction::opposite(), om_direction::turn_left(), and om_direction::turn_right().
set_oter_ids()
static void set_oter_ids () static
Definition at line 358 of file overmap.cpp.
{
    ot_null         = oter_str_id::NULL_ID();
    // NOT required.
    ot_crater       = oter_id( "crater" );
    ot_field        = oter_id( "field" );
    ot_forest       = oter_id( "forest" );
    ot_forest_thick = oter_id( "forest_thick" );
    ot_forest_water = oter_id( "forest_water" );
    ot_river_center = oter_id( "river_center" );
}
References string_id< oter_t >::NULL_ID(), ot_crater, ot_field, ot_forest, ot_forest_thick, ot_forest_water, ot_null, and ot_river_center.
Referenced by overmap_terrains::finalize().
straight_path()
static pf::directed_path< point_om_omt > straight_path (const point_om_omt & source, om_direction::type dir, size_t len) static
Definition at line 3775 of file overmap.cpp.
{
    pf::directed_path<point_om_omt> res;
    if( len == 0 ) {
        return res;
    }
    point_om_omt p = source;
    res.nodes.reserve( len );
    for( size_t i = 0; i + 1 < len; ++i ) {
        res.nodes.emplace_back( p, dir );
        p += om_direction::displace( dir );
    }
    res.nodes.emplace_back( p, om_direction::type::invalid );
    return res;
}
References om_direction::displace(), om_direction::invalid, and pf::directed_path< Point >::nodes.
Referenced by overmap::lay_out_street().
Variable Documentation
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by overmap::move_hordes().
GROUP_CHUD
const mongroup_id GROUP_CHUD("GROUP_CHUD") ("GROUP_CHUD") static
Referenced by overmap::generate_sub().
GROUP_DIMENSIONAL_SURFACE
const mongroup_id GROUP_DIMENSIONAL_SURFACE("GROUP_DIMENSIONAL_SURFACE") ("GROUP_DIMENSIONAL_SURFACE") static
Referenced by overmap::place_mongroups().
GROUP_RIVER
const mongroup_id GROUP_RIVER("GROUP_RIVER") ("GROUP_RIVER") static
Referenced by overmap::place_mongroups().
GROUP_SEWER
const mongroup_id GROUP_SEWER("GROUP_SEWER") ("GROUP_SEWER") static
Referenced by overmap::generate_sub().
GROUP_SWAMP
const mongroup_id GROUP_SWAMP("GROUP_SWAMP") ("GROUP_SWAMP") static
Referenced by overmap::place_mongroups().
GROUP_WORM
const mongroup_id GROUP_WORM("GROUP_WORM") ("GROUP_WORM") static
Referenced by overmap::place_mongroups().
GROUP_ZOMBIE
const mongroup_id GROUP_ZOMBIE("GROUP_ZOMBIE") ("GROUP_ZOMBIE") static
Referenced by overmap::move_hordes(), and overmap::place_mongroups().
ot_crater
oter_id ot_crater
Definition at line 83 of file overmap.cpp.
Referenced by set_oter_ids().
ot_field
oter_id ot_field
Definition at line 84 of file overmap.cpp.
Referenced by set_oter_ids().
ot_forest
oter_id ot_forest
Definition at line 85 of file overmap.cpp.
Referenced by overmap::move_hordes(), and set_oter_ids().
ot_forest_thick
oter_id ot_forest_thick
Definition at line 86 of file overmap.cpp.
Referenced by overmap::move_hordes(), and set_oter_ids().
ot_forest_water
oter_id ot_forest_water
Definition at line 87 of file overmap.cpp.
Referenced by overmap::move_hordes(), and set_oter_ids().
ot_null
oter_id ot_null
Definition at line 82 of file overmap.cpp.
Referenced by oter_type_t::get_linear(), oter_type_t::get_rotated(), set_oter_ids(), overmap::ter(), and overmapbuffer::ter_existing().
ot_river_center
oter_id ot_river_center
Definition at line 88 of file overmap.cpp.
Referenced by overmap::move_hordes(), and set_oter_ids().
radio_type_names
std::map<enum radio_type, std::string> radio_type_names
Initial value:
=
{{ {radio_type::MESSAGE_BROADCAST, "broadcast"}, {radio_type::WEATHER_RADIO, "weather"} }}
Definition at line 234 of file overmap.cpp.
Referenced by overmap::serialize(), and overmap::unserialize().
region_settings_map
t_regional_settings_map region_settings_map
Definition at line 186 of file overmap.cpp.
Referenced by MapExtras::debug_spawn_test(), overmap_terrains::finalize(), map::generate(), load_region_overlay(), load_region_settings(), overmap::overmap(), reset_region_settings(), and overmap::unserialize().
ZOMBIE
const species_id ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by overmap::move_hordes().