Cataclysm BN: src/overmap_special.h File Reference
overmap_special.h File Reference
#include <climits>
#include <cstddef>
#include <cstdint>
#include <bitset>
#include <list>
#include <set>
#include <vector>
#include <array>
#include <string>
#include "omdata.h"
#include "point.h"
#include "type_id.h"
Classes
struct overmap_special_spawns
struct overmap_special_terrain
struct overmap_special_connection
class overmap_special
struct om_special_sectors
struct overmap_special_placement
class overmap_special_batch
Namespaces
namespace overmap_specials
namespace city_buildings
Macros
#define CATA_SRC_OVERMAP_SPECIAL_H
Functions
void overmap_specials::load (const JsonObject &jo, const std::string &src)
void overmap_specials::finalize ()
void overmap_specials::check_consistency ()
void overmap_specials::reset ()
const std::vector< overmap_special > & overmap_specials::get_all ()
overmap_special_batch overmap_specials::get_default_batch (const point_abs_om &origin)
overmap_special_id overmap_specials::create_building_from (const oter_type_str_id &base)
Generates a simple special from a building id.
void city_buildings::load (const JsonObject &jo, const std::string &src)
om_special_sectors get_sectors (int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
Variables
static constexpr int OMSPEC_FREQ = 15
Macro Definition Documentation
CATA_SRC_OVERMAP_SPECIAL_H
#define CATA_SRC_OVERMAP_SPECIAL_H
Definition at line 3 of file overmap_special.h.
Function Documentation
get_sectors()
om_special_sectors get_sectors (int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
Parameters
sector_width used to divide the OMAPX by OMAPY map into sectors.
Definition at line 4418 of file overmap.cpp.
{
    std::vector<point_om_omt> res;
    res.reserve( ( OMAPX / sector_width ) * ( OMAPY / sector_width ) );
    for( int x = 0; x < OMAPX; x += sector_width ) {
        for( int y = 0; y < OMAPY; y += sector_width ) {
            res.emplace_back( x, y );
        }
    }
    std::shuffle( res.begin(), res.end(), rng_get_engine() );
    return om_special_sectors{ res, sector_width };
}
References OMAPX, OMAPY, and rng_get_engine().
Referenced by overmapbuffer::place_special(), and overmap::place_specials().
Variable Documentation
OMSPEC_FREQ
constexpr int OMSPEC_FREQ = 15 static constexpr
Definition at line 36 of file overmap_special.h.
Referenced by overmap_specials::check_consistency(), overmapbuffer::place_special(), and overmap::place_specials().