Cataclysm BN: src/panels.h File Reference
panels.h File Reference
#include <functional>
#include <map>
#include <string>
#include <vector>
#include "coordinates.h"
Classes
class window_panel
class panel_manager
Namespaces
namespace catacurses
Contains the curses interface used by the whole game.
namespace overmap_ui
Macros
#define CATA_SRC_PANELS_H
Enumerations
enum face_type : int {
face_human = 0 , face_bird , face_bear , face_cat ,
num_face_types
}
Functions
void overmap_ui::draw_overmap_chunk (const catacurses::window &w_minimap, const avatar &you, const tripoint_abs_omt &global_omt, const point &start, int width, int height)
bool default_render ()
Macro Definition Documentation
CATA_SRC_PANELS_H
#define CATA_SRC_PANELS_H
Definition at line 3 of file panels.h.
Enumeration Type Documentation
face_type
enum face_type : int
Enumerator
face_human
face_bird
face_bear
face_cat
num_face_types
Definition at line 22 of file panels.h.
               : int {
    face_human = 0,
    face_bird,
    face_bear,
    face_cat,
    num_face_types
};
Function Documentation
default_render()
bool default_render ()
Definition at line 2011 of file panels.cpp.
{
    return true;
}
Referenced by initialize_default_classic_panels(), initialize_default_compact_panels(), initialize_default_label_narrow_panels(), and initialize_default_label_panels().