Cataclysm BN: src/panels.cpp File Reference
panels.cpp File Reference
#include "panels.h"
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <iosfwd>
#include <iterator>
#include <list>
#include <memory>
#include <string>
#include <utility>
#include "action.h"
#include "avatar.h"
#include "behavior.h"
#include "bodypart.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_functions.h"
#include "character_martial_arts.h"
#include "character_oracle.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "effect.h"
#include "fstream_utils.h"
#include "game.h"
#include "game_constants.h"
#include "game_ui.h"
#include "input.h"
#include "item.h"
#include "json.h"
#include "magic.h"
#include "map.h"
#include "messages.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "path_info.h"
#include "player.h"
#include "pldata.h"
#include "point.h"
#include "string_formatter.h"
#include "string_id.h"
#include "tileray.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather.h"
Functions
static std::string trunc_ellipse (const std::string &input, unsigned int trunc)
static void draw_rectangle (const catacurses::window &w, nc_color, point top_left, point bottom_right)
static std::pair< nc_color, std::string > str_string (const avatar &p)
static std::pair< nc_color, std::string > dex_string (const avatar &p)
static std::pair< nc_color, std::string > int_string (const avatar &p)
static std::pair< nc_color, std::string > per_string (const avatar &p)
static nc_color focus_color (int focus)
static void draw_minimap (const avatar &u, const catacurses::window &w_minimap)
static void decorate_panel (const std::string &name, const catacurses::window &w)
static std::string get_temp (const avatar &u)
static std::string get_moon_graphic ()
static std::string get_moon ()
static std::string time_approx ()
static nc_color value_color (int stat)
static std::pair< nc_color, int > morale_stat (const avatar &u)
static std::pair< int, int > temp_delta (const avatar &u)
static int define_temp_level (const int lvl)
static std::string temp_delta_string (const avatar &u)
static std::pair< nc_color, std::string > temp_delta_arrows (const avatar &u)
static std::pair< nc_color, std::string > temp_stat (const avatar &u)
static std::string get_armor (const avatar &u, body_part bp, unsigned int truncate=0)
static face_type get_face_type (const avatar &u)
static std::string morale_emotion (const int morale_cur, const face_type face, const bool horizontal_style)
static std::pair< nc_color, std::string > power_stat (const avatar &u)
static std::pair< nc_color, std::string > mana_stat (const player &u)
static nc_color safe_color ()
static int get_int_digits (const int &digits)
static void draw_limb_health (avatar &u, const catacurses::window &w, int limb_index)
static void draw_limb2 (avatar &u, const catacurses::window &w)
static void draw_stats (avatar &u, const catacurses::window &w)
static nc_color move_mode_color (avatar &u)
static std::string move_mode_string (avatar &u)
static void draw_stealth (avatar &u, const catacurses::window &w)
static void draw_time_graphic (const catacurses::window &w)
static void draw_time (const avatar &u, const catacurses::window &w)
static void draw_needs_compact (const avatar &u, const catacurses::window &w)
static std::string carry_weight_string (const avatar &u)
static std::string carry_volume_string (const avatar &u)
static void draw_weightvolume_compact (const avatar &u, const catacurses::window &w)
static void draw_weightvolume_narrow (const avatar &u, const catacurses::window &w)
static void draw_limb_narrow (avatar &u, const catacurses::window &w)
static void draw_limb_wide (avatar &u, const catacurses::window &w)
static void draw_char_narrow (avatar &u, const catacurses::window &w)
static void draw_char_wide (avatar &u, const catacurses::window &w)
static void draw_stat_narrow (avatar &u, const catacurses::window &w)
static void draw_stat_wide (avatar &u, const catacurses::window &w)
static void draw_loc_labels (const avatar &u, const catacurses::window &w, bool minimap)
static void draw_loc_narrow (const avatar &u, const catacurses::window &w)
static void draw_loc_wide (const avatar &u, const catacurses::window &w)
static void draw_loc_wide_map (const avatar &u, const catacurses::window &w)
static void draw_moon_narrow (const avatar &u, const catacurses::window &w)
static void draw_moon_wide (const avatar &u, const catacurses::window &w)
static void draw_weapon_labels (const avatar &u, const catacurses::window &w)
static void draw_weightvolume_labels (const avatar &u, const catacurses::window &w)
static void draw_needs_narrow (const avatar &u, const catacurses::window &w)
static void draw_needs_labels (const avatar &u, const catacurses::window &w)
static void draw_sound_labels (const avatar &u, const catacurses::window &w)
static void draw_sound_narrow (const avatar &u, const catacurses::window &w)
static void draw_env_compact (avatar &u, const catacurses::window &w)
static void render_wind (avatar &u, const catacurses::window &w, const std::string &formatstr)
static void draw_wind (avatar &u, const catacurses::window &w)
static void draw_wind_padding (avatar &u, const catacurses::window &w)
static void draw_health_classic (avatar &u, const catacurses::window &w)
static void draw_armor_padding (const avatar &u, const catacurses::window &w)
static void draw_armor (const avatar &u, const catacurses::window &w)
static void draw_messages (avatar &, const catacurses::window &w)
static void draw_messages_classic (avatar &, const catacurses::window &w)
static void draw_compass (avatar &, const catacurses::window &w)
static void draw_compass_padding (avatar &, const catacurses::window &w)
static void draw_veh_compact (const avatar &u, const catacurses::window &w)
static void draw_veh_padding (const avatar &u, const catacurses::window &w)
static void draw_ai_goal (const avatar &u, const catacurses::window &w)
static void draw_location_classic (const avatar &u, const catacurses::window &w)
static void draw_weather_classic (avatar &, const catacurses::window &w)
static void draw_lighting_classic (const avatar &u, const catacurses::window &w)
static void draw_weapon_classic (const avatar &u, const catacurses::window &w)
static void draw_weapon_classic_alt (const avatar &u, const catacurses::window &w)
static void draw_weightvolume_classic (const avatar &u, const catacurses::window &w)
static void draw_time_classic (const avatar &u, const catacurses::window &w)
static void draw_hint (const avatar &, const catacurses::window &w)
static void print_mana (const player &u, const catacurses::window &w, const std::string &fmt_string, const int j1, const int j2, const int j3, const int j4)
static void draw_mana_classic (const player &u, const catacurses::window &w)
static void draw_mana_compact (const player &u, const catacurses::window &w)
static void draw_mana_narrow (const player &u, const catacurses::window &w)
static void draw_mana_wide (const player &u, const catacurses::window &w)
static bool spell_panel ()
bool default_render ()
static std::vector< window_panel > initialize_default_classic_panels ()
static std::vector< window_panel > initialize_default_compact_panels ()
static std::vector< window_panel > initialize_default_label_narrow_panels ()
static std::vector< window_panel > initialize_default_label_panels ()
static std::map< std::string, std::vector< window_panel > > initialize_default_panel_layouts ()
Variables
static const trait_id trait_SELFAWARE ("SELFAWARE")
static const trait_id trait_THRESH_FELINE ("THRESH_FELINE")
static const trait_id trait_THRESH_BIRD ("THRESH_BIRD")
static const trait_id trait_THRESH_URSINE ("THRESH_URSINE")
static const efftype_id effect_got_checked ("got_checked")
Function Documentation
carry_volume_string()
static std::string carry_volume_string (const avatar & u) static
Definition at line 1136 of file panels.cpp.
{
    double volume_carried = round_up( convert_volume( to_milliliter( u.volume_carried() ) ),
                                      2 );
    double volume_capacity = round_up( convert_volume( to_milliliter( u.volume_capacity() ) ),
                                       2 ); // In liters/cups/wolf paws or whatever burger units
    return string_format( "%.2f/%.2f", volume_carried, volume_capacity );
}
References convert_volume(), round_up(), string_format(), units::to_milliliter(), Character::volume_capacity(), and Character::volume_carried().
Referenced by draw_weightvolume_classic(), draw_weightvolume_compact(), draw_weightvolume_labels(), and draw_weightvolume_narrow().
carry_weight_string()
static std::string carry_weight_string (const avatar & u) static
Definition at line 1129 of file panels.cpp.
{
    double weight_carried = round_up( convert_weight( u.weight_carried() ), 1 ); // In kg/lbs
    double weight_capacity = round_up( convert_weight( u.weight_capacity() ), 1 );
    return string_format( "%.1f/%.1f", weight_carried, weight_capacity );
}
References convert_weight(), round_up(), string_format(), Character::weight_capacity(), and Character::weight_carried().
Referenced by draw_weightvolume_classic(), draw_weightvolume_compact(), draw_weightvolume_labels(), and draw_weightvolume_narrow().
decorate_panel()
static void decorate_panel (const std::string & name, const catacurses::window & w) static
Definition at line 423 of file panels.cpp.
{
    werase( w );
    draw_border( w );
    static const char *title_prefix = " ";
    const std::string &title = name;
    static const char *title_suffix = " ";
    static const std::string full_title = string_format( "%s%s%s",
                                          title_prefix, title, title_suffix );
    const int start_pos = center_text_pos( full_title, 0, getmaxx( w ) - 1 );
    mvwprintz( w, point( start_pos, 0 ), c_white, title_prefix );
    wprintz( w, c_light_red, title );
    wprintz( w, c_white, title_suffix );
}
References c_light_red, c_white, center_text_pos(), draw_border(), catacurses::getmaxx(), mvwprintz(), om_direction::name(), string_format(), PATH_INFO::title(), catacurses::werase(), and wprintz().
Referenced by panel_manager::show_adm().
default_render()
bool default_render ()
Definition at line 2130 of file panels.cpp.
{
    return true;
}
Referenced by initialize_default_classic_panels(), initialize_default_compact_panels(), initialize_default_label_narrow_panels(), and initialize_default_label_panels().
define_temp_level()
static int define_temp_level (const int lvl) static
Definition at line 565 of file panels.cpp.
{
    if( lvl > BODYTEMP_SCORCHING ) {
        return 7;
    } else if( lvl > BODYTEMP_VERY_HOT ) {
        return 6;
    } else if( lvl > BODYTEMP_HOT ) {
        return 5;
    } else if( lvl > BODYTEMP_COLD ) {
        return 4;
    } else if( lvl > BODYTEMP_VERY_COLD ) {
        return 3;
    } else if( lvl > BODYTEMP_FREEZING ) {
        return 2;
    }
    return 1;
}
References BODYTEMP_COLD, BODYTEMP_FREEZING, BODYTEMP_HOT, BODYTEMP_SCORCHING, BODYTEMP_VERY_COLD, and BODYTEMP_VERY_HOT.
Referenced by temp_delta_arrows(), and temp_delta_string().
dex_string()
static std::pair< nc_color, std::string > dex_string (const avatar & p) static
Definition at line 130 of file panels.cpp.
{
    nc_color clr;
    if( p.get_dex() == p.get_dex_base() ) {
        clr = c_white;
    } else if( p.get_dex() > p.get_dex_base() ) {
        clr = c_green;
    } else if( p.get_dex() < p.get_dex_base() ) {
        clr = c_red;
    }
    return std::make_pair( clr, _( "Dex " ) + ( p.get_dex() < 100 ? std::to_string(
                               p.get_dex() ) : "++" ) );
}
References _, c_green, c_red, c_white, Character::get_dex(), avatar::get_dex_base(), and to_string().
Referenced by draw_health_classic(), draw_stat_narrow(), draw_stat_wide(), and draw_stats().
draw_ai_goal()
static void draw_ai_goal (const avatar & u, const catacurses::window & w) static
Definition at line 1916 of file panels.cpp.
{
    werase( w );
    behavior::tree needs;
    needs.add( &string_id<behavior::node_t>( "npc_needs" ).obj() );
    behavior::character_oracle_t player_oracle( &u );
    std::string current_need = needs.tick( &player_oracle );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Goal: %s" ), current_need );
    wnoutrefresh( w );
}
References _, behavior::tree::add(), c_light_gray, mvwprintz(), int_id< T >::obj(), behavior::tree::tick(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels(), initialize_default_compact_panels(), initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_armor()
static void draw_armor (const avatar & u, const catacurses::window & w) static
Definition at line 1791 of file panels.cpp.
{
    werase( w );
    nc_color color = c_light_gray;
    mvwprintz( w, point_zero, color, _( "Head :" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 0, 1 ), color, _( "Torso:" ) );
    mvwprintz( w, point( 0, 2 ), color, _( "Arms :" ) );
    mvwprintz( w, point( 0, 3 ), color, _( "Legs :" ) );
    mvwprintz( w, point( 0, 4 ), color, _( "Feet :" ) );
    unsigned int max_length = getmaxx( w ) - 7;
    print_colored_text( w, point( 7, 0 ), color, color, get_armor( u, bp_head, max_length ) );
    print_colored_text( w, point( 7, 1 ), color, color, get_armor( u, bp_torso, max_length ) );
    print_colored_text( w, point( 7, 2 ), color, color, get_armor( u, bp_arm_r, max_length ) );
    print_colored_text( w, point( 7, 3 ), color, color, get_armor( u, bp_leg_r, max_length ) );
    print_colored_text( w, point( 7, 4 ), color, color, get_armor( u, bp_foot_r, max_length ) );
    wnoutrefresh( w );
}
References _, bp_arm_r, bp_foot_r, bp_head, bp_leg_r, bp_torso, c_light_gray, color(), get_armor(), catacurses::getmaxx(), mvwprintz(), point_zero, print_colored_text(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels(), and initialize_default_compact_panels().
draw_armor_padding()
static void draw_armor_padding (const avatar & u, const catacurses::window & w) static
Definition at line 1770 of file panels.cpp.
{
    werase( w );
    nc_color color = c_light_gray;
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), color, _( "Head :" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), color, _( "Torso:" ) );
    mvwprintz( w, point( 1, 2 ), color, _( "Arms :" ) );
    mvwprintz( w, point( 1, 3 ), color, _( "Legs :" ) );
    mvwprintz( w, point( 1, 4 ), color, _( "Feet :" ) );
    unsigned int max_length = getmaxx( w ) - 8;
    print_colored_text( w, point( 8, 0 ), color, color, get_armor( u, bp_head, max_length ) );
    print_colored_text( w, point( 8, 1 ), color, color, get_armor( u, bp_torso, max_length ) );
    print_colored_text( w, point( 8, 2 ), color, color, get_armor( u, bp_arm_r, max_length ) );
    print_colored_text( w, point( 8, 3 ), color, color, get_armor( u, bp_leg_r, max_length ) );
    print_colored_text( w, point( 8, 4 ), color, color, get_armor( u, bp_foot_r, max_length ) );
    wnoutrefresh( w );
}
References _, bp_arm_r, bp_foot_r, bp_head, bp_leg_r, bp_torso, c_light_gray, color(), get_armor(), catacurses::getmaxx(), mvwprintz(), print_colored_text(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_char_narrow()
static void draw_char_narrow (avatar & u, const catacurses::window & w) static
Definition at line 1266 of file panels.cpp.
{
    werase( w );
    std::pair<nc_color, int> morale_pair = morale_stat( u );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Sound:" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Stam :" ) );
    mvwprintz( w, point( 1, 2 ), c_light_gray, _( "Focus:" ) );
    mvwprintz( w, point( 19, 0 ), c_light_gray, _( "Mood :" ) );
    mvwprintz( w, point( 19, 1 ), c_light_gray, _( "Speed:" ) );
    mvwprintz( w, point( 19, 2 ), c_light_gray, _( "Move :" ) );
    nc_color move_color =  move_mode_color( u );
    std::string move_char = move_mode_string( u );
    std::string movecost = std::to_string( u.movecounter ) + "(" + move_char + ")";
    bool m_style = get_option<std::string>( "MORALE_STYLE" ) == "horizontal";
    std::string smiley = morale_emotion( morale_pair.second, get_face_type( u ), m_style );
    mvwprintz( w, point( 8, 0 ), c_light_gray, "%s", u.volume );
    // print stamina
    auto needs_pair = std::make_pair( get_hp_bar( u.get_stamina(), u.get_stamina_max() ).second,
                                      get_hp_bar( u.get_stamina(), u.get_stamina_max() ).first );
    mvwprintz( w, point( 8, 1 ), needs_pair.first, needs_pair.second );
    const int width = utf8_width( needs_pair.second );
    for( int i = 0; i < 5 - width; i++ ) {
        mvwprintz( w, point( 12 - i, 1 ), c_white, "." );
    }
    mvwprintz( w, point( 8, 2 ), focus_color( u.focus_pool ), "%s", u.focus_pool );
    if( u.focus_pool < u.calc_focus_equilibrium() ) {
        mvwprintz( w, point( 11, 2 ), c_light_green, "" );
    } else if( u.focus_pool > u.calc_focus_equilibrium() ) {
        mvwprintz( w, point( 11, 2 ), c_light_red, "" );
    }
    mvwprintz( w, point( 26, 0 ), morale_pair.first, "%s", smiley );
    mvwprintz( w, point( 26, 1 ), focus_color( u.get_speed() ), "%s", u.get_speed() );
    mvwprintz( w, point( 26, 2 ), move_color, "%s", movecost );
    wnoutrefresh( w );
}
References _, c_light_gray, c_light_green, c_light_red, c_white, player::calc_focus_equilibrium(), focus_color(), Character::focus_pool, get_face_type(), get_hp_bar(), Character::get_speed(), Character::get_stamina(), Character::get_stamina_max(), morale_emotion(), morale_stat(), move_mode_color(), move_mode_string(), player::movecounter, mvwprintz(), to_string(), utf8_width(), player::volume, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels().
draw_char_wide()
static void draw_char_wide (avatar & u, const catacurses::window & w) static
Definition at line 1307 of file panels.cpp.
{
    werase( w );
    std::pair<nc_color, int> morale_pair = morale_stat( u );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Sound:" ) );
    mvwprintz( w, point( 16, 0 ), c_light_gray, _( "Mood :" ) );
    mvwprintz( w, point( 31, 0 ), c_light_gray, _( "Focus:" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Stam :" ) );
    mvwprintz( w, point( 16, 1 ), c_light_gray, _( "Speed:" ) );
    mvwprintz( w, point( 31, 1 ), c_light_gray, _( "Move :" ) );
    nc_color move_color =  move_mode_color( u );
    std::string move_char = move_mode_string( u );
    std::string movecost = std::to_string( u.movecounter ) + "(" + move_char + ")";
    bool m_style = get_option<std::string>( "MORALE_STYLE" ) == "horizontal";
    std::string smiley = morale_emotion( morale_pair.second, get_face_type( u ), m_style );
    mvwprintz( w, point( 8, 0 ), c_light_gray, "%s", u.volume );
    mvwprintz( w, point( 23, 0 ), morale_pair.first, "%s", smiley );
    mvwprintz( w, point( 38, 0 ), focus_color( u.focus_pool ), "%s", u.focus_pool );
    // print stamina
    auto needs_pair = std::make_pair( get_hp_bar( u.get_stamina(), u.get_stamina_max() ).second,
                                      get_hp_bar( u.get_stamina(), u.get_stamina_max() ).first );
    mvwprintz( w, point( 8, 1 ), needs_pair.first, needs_pair.second );
    const int width = utf8_width( needs_pair.second );
    for( int i = 0; i < 5 - width; i++ ) {
        mvwprintz( w, point( 12 - i, 1 ), c_white, "." );
    }
    mvwprintz( w, point( 23, 1 ), focus_color( u.get_speed() ), "%s", u.get_speed() );
    mvwprintz( w, point( 38, 1 ), move_color, "%s", movecost );
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, focus_color(), Character::focus_pool, get_face_type(), get_hp_bar(), Character::get_speed(), Character::get_stamina(), Character::get_stamina_max(), morale_emotion(), morale_stat(), move_mode_color(), move_mode_string(), player::movecounter, mvwprintz(), to_string(), utf8_width(), player::volume, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_compass()
static void draw_compass (avatar & , const catacurses::window & w) static
Definition at line 1838 of file panels.cpp.
{
    werase( w );
    g->mon_info( w );
    wnoutrefresh( w );
}
References g, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_compass_padding()
static void draw_compass_padding (avatar & , const catacurses::window & w) static
Definition at line 1845 of file panels.cpp.
{
    werase( w );
    g->mon_info( w, 1 );
    wnoutrefresh( w );
}
References g, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels(), initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_env_compact()
static void draw_env_compact (avatar & u, const catacurses::window & w) static
Definition at line 1591 of file panels.cpp.
{
    werase( w );
    draw_minimap( u, w );
    // wielded item
    trim_and_print( w, point( 8, 0 ), getmaxx( w ) - 8, c_light_gray, u.weapname() );
    // style
    mvwprintz( w, point( 8, 1 ), c_light_gray, "%s", u.martial_arts_data->selected_style_name( u ) );
    // location
    mvwprintz( w, point( 8, 2 ), c_white, utf8_truncate( overmap_buffer.ter(
                   u.global_omt_location() )->get_name(), getmaxx( w ) - 8 ) );
    // weather
    const weather_manager &weather = get_weather();
    if( g->get_levz() < 0 ) {
        mvwprintz( w, point( 8, 3 ), c_light_gray, _( "Underground" ) );
    } else {
        mvwprintz( w, point( 8, 3 ), get_weather().weather_id->color,
                   get_weather().weather_id->name.translated() );
    }
    // display lighting
    const std::pair<std::string, nc_color> ll = get_light_level(
                character_funcs::fine_detail_vision_mod( get_avatar() ) );
    mvwprintz( w, point( 8, 4 ), ll.second, ll.first );
    // wind
    const oter_id &cur_om_ter = overmap_buffer.ter( u.global_omt_location() );
    double windpower = get_local_windpower( weather.windspeed, cur_om_ter,
                                            u.pos(), weather.winddirection, g->is_sheltered( u.pos() ) );
    mvwprintz( w, point( 8, 5 ), get_wind_color( windpower ),
               get_wind_desc( windpower ) + " " + get_wind_arrow( weather.winddirection ) );
    if( u.has_item_with_flag( "THERMOMETER" ) || u.has_bionic( bionic_id( "bio_meteorologist" ) ) ) {
        std::string temp = print_temperature( weather.get_temperature( u.pos() ) );
        mvwprintz( w, point( 31 - utf8_width( temp ), 5 ), c_light_gray, temp );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, draw_minimap(), character_funcs::fine_detail_vision_mod(), g, get_avatar(), get_light_level(), get_local_windpower(), oter_t::get_name(), get_weather(), get_wind_arrow(), get_wind_color(), get_wind_desc(), catacurses::getmaxx(), Character::global_omt_location(), Character::has_bionic(), Character::has_item_with_flag(), Character::martial_arts_data, mvwprintz(), overmap_buffer, Character::pos(), print_temperature(), overmapbuffer::ter(), trim_and_print(), utf8_truncate(), utf8_width(), player::weapname(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_health_classic()
static void draw_health_classic (avatar & u, const catacurses::window & w) static
Definition at line 1655 of file panels.cpp.
{
    static std::array<bodypart_id, 6> part = { {
            bodypart_id( "head" ), bodypart_id( "torso" ), bodypart_id( "arm_l" ), bodypart_id( "arm_r" ), bodypart_id( "leg_l" ), bodypart_id( "leg_r" )
        }
    };
    vehicle *veh = g->remoteveh();
    if( veh == nullptr && u.in_vehicle ) {
        veh = veh_pointer_or_null( get_map().veh_at( u.pos() ) );
    }
    werase( w );
    draw_minimap( u, w );
    draw_rectangle( w, c_light_gray, point_zero, point( 6, 6 ) );
    // print limb health
    for( int i = 0; i < num_hp_parts; i++ ) {
        const std::string str = body_part_hp_bar_ui_text( part[i] );
        wmove( w, point( 8, i ) );
        wprintz( w, u.limb_color( part[i], true, true, true ), str );
        wmove( w, point( 14, i ) );
        draw_limb_health( u, w, i );
    }
    // needs
    auto needs_pair = u.get_hunger_description();
    mvwprintz( w, point( 21, 1 ), needs_pair.second, needs_pair.first );
    needs_pair = u.get_thirst_description();
    mvwprintz( w, point( 21, 2 ), needs_pair.second, needs_pair.first );
    mvwprintz( w, point( 21, 4 ), c_white, _( "Focus" ) );
    mvwprintz( w, point( 27, 4 ), c_white, std::to_string( u.focus_pool ) );
    needs_pair = u.get_fatigue_description();
    mvwprintz( w, point( 21, 3 ), needs_pair.second, needs_pair.first );
    auto pain_pair = u.get_pain_description();
    mvwprintz( w, point( 21, 0 ), pain_pair.second, pain_pair.first );
    // print mood
    std::pair<nc_color, int> morale_pair = morale_stat( u );
    bool m_style = get_option<std::string>( "MORALE_STYLE" ) == "horizontal";
    std::string smiley = morale_emotion( morale_pair.second, get_face_type( u ), m_style );
    mvwprintz( w, point( 34, 1 ), morale_pair.first, smiley );
    if( !veh ) {
        // stats
        auto pair = str_string( u );
        mvwprintz( w, point( 38, 0 ), pair.first, pair.second );
        pair = dex_string( u );
        mvwprintz( w, point( 38, 1 ), pair.first, pair.second );
        pair = int_string( u );
        mvwprintz( w, point( 38, 2 ), pair.first, pair.second );
        pair = per_string( u );
        mvwprintz( w, point( 38, 3 ), pair.first, pair.second );
    }
    // print safe mode// print safe mode
    std::string safe_str;
    if( g->safe_mode || get_option<bool>( "AUTOSAFEMODE" ) ) {
        safe_str = "SAFE";
    }
    mvwprintz( w, point( 40, 4 ), safe_color(), safe_str );
    // print stamina
    auto pair = std::make_pair( get_hp_bar( u.get_stamina(), u.get_stamina_max() ).second,
                                get_hp_bar( u.get_stamina(), u.get_stamina_max() ).first );
    mvwprintz( w, point( 35, 5 ), c_light_gray, _( "Stm" ) );
    mvwprintz( w, point( 39, 5 ), pair.first, pair.second );
    const int width = utf8_width( pair.second );
    for( int i = 0; i < 5 - width; i++ ) {
        mvwprintz( w, point( 43 - i, 5 ), c_white, "." );
    }
    // speed
    if( !veh ) {
        mvwprintz( w, point( 21, 5 ), u.get_speed() < 100 ? c_red : c_white,
                   _( "Spd " ) + std::to_string( u.get_speed() ) );
        nc_color move_color = u.movement_mode_is( CMM_WALK ) ? c_white : move_mode_color( u );
        std::string move_string = std::to_string( u.movecounter ) + " " + move_mode_string( u );
        mvwprintz( w, point( 29, 5 ), move_color, move_string );
    }
    // temperature
    pair = temp_stat( u );
    mvwprintz( w, point( 21, 6 ), pair.first, pair.second + temp_delta_string( u ) );
    // power
    pair = power_stat( u );
    mvwprintz( w, point( 8, 6 ), c_light_gray, _( "POWER" ) );
    mvwprintz( w, point( 14, 6 ), pair.first, pair.second );
    // vehicle display
    if( veh ) {
        veh->print_fuel_indicators( w, point( 39, 2 ) );
        mvwprintz( w, point( 35, 4 ), c_light_gray, veh->face.to_string_azimuth_from_north() );
        // target speed > current speed
        const float strain = veh->strain();
        if( veh->cruise_on ) {
            nc_color col_vel = strain <= 0 ? c_light_blue :
                               ( strain <= 0.2 ? c_yellow :
                                 ( strain <= 0.4 ? c_light_red : c_red ) );
            int t_speed = static_cast<int>( convert_velocity( veh->cruise_velocity, VU_VEHICLE ) );
            int c_speed = static_cast<int>( convert_velocity( veh->velocity, VU_VEHICLE ) );
            int offset = get_int_digits( t_speed );
            const std::string type = get_option<std::string>( "USE_METRIC_SPEEDS" );
            mvwprintz( w, point( 21, 5 ), c_light_gray, type );
            mvwprintz( w, point( 26, 5 ), col_vel, "%d", c_speed );
            mvwprintz( w, point( 26 + offset, 5 ), c_light_gray, ">" );
            mvwprintz( w, point( 28 + offset, 5 ), c_light_green, "%d", t_speed );
        }
    }
    wnoutrefresh( w );
}
References _, body_part_hp_bar_ui_text(), c_light_blue, c_light_gray, c_light_green, c_light_red, c_red, c_white, c_yellow, CMM_WALK, convert_velocity(), vehicle::cruise_on, vehicle::cruise_velocity, dex_string(), draw_limb_health(), draw_minimap(), draw_rectangle(), vehicle::face, Character::focus_pool, g, get_face_type(), Character::get_fatigue_description(), get_hp_bar(), Character::get_hunger_description(), get_int_digits(), get_map(), Character::get_pain_description(), Character::get_speed(), Character::get_stamina(), Character::get_stamina_max(), Character::get_thirst_description(), Character::in_vehicle, int_string(), Character::limb_color(), morale_emotion(), morale_stat(), move_mode_color(), move_mode_string(), player::movecounter, Character::movement_mode_is(), mvwprintz(), num_hp_parts, per_string(), point_zero, Character::pos(), power_stat(), vehicle::print_fuel_indicators(), safe_color(), str_string(), vehicle::strain(), temp_delta_string(), temp_stat(), to_string(), tileray::to_string_azimuth_from_north(), type, utf8_width(), veh_pointer_or_null(), vehicle::velocity, VU_VEHICLE, catacurses::werase(), catacurses::wmove(), catacurses::wnoutrefresh(), and wprintz().
Referenced by initialize_default_classic_panels().
draw_hint()
static void draw_hint (const avatar & , const catacurses::window & w) static
Definition at line 2071 of file panels.cpp.
{
    werase( w );
    std::string press = press_x( ACTION_TOGGLE_PANEL_ADM );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_green, press );
    mvwprintz( w, point( 2 + utf8_width( press ), 0 ), c_white, _( "to open sidebar options" ) );
    wnoutrefresh( w );
}
References _, ACTION_TOGGLE_PANEL_ADM, c_light_green, c_white, mvwprintz(), press_x(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_lighting_classic()
static void draw_lighting_classic (const avatar & u, const catacurses::window & w) static
Definition at line 1957 of file panels.cpp.
{
    werase( w );
    const std::pair<std::string, nc_color> ll = get_light_level(
                character_funcs::fine_detail_vision_mod( get_avatar() ) );
    mvwprintz( w, point_zero, c_light_gray, _( "Lighting:" ) );
    mvwprintz( w, point( 10, 0 ), ll.second, ll.first );
    if( !u.is_deaf() ) {
        mvwprintz( w, point( 31, 0 ), c_light_gray, _( "Sound:" ) );
        mvwprintz( w, point( 38, 0 ), c_yellow, std::to_string( u.volume ) );
    } else {
        mvwprintz( w, point( 31, 0 ), c_red, _( "Deaf!" ) );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, character_funcs::fine_detail_vision_mod(), get_avatar(), get_light_level(), Character::is_deaf(), mvwprintz(), point_zero, to_string(), player::volume, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_limb2()
static void draw_limb2 (avatar & u, const catacurses::window & w) static
Definition at line 918 of file panels.cpp.
{
    static std::array<bodypart_id, 6> part = { {
            bodypart_id( "head" ), bodypart_id( "torso" ), bodypart_id( "arm_l" ), bodypart_id( "arm_r" ), bodypart_id( "leg_l" ), bodypart_id( "leg_r" )
        }
    };
    werase( w );
    // print limb health
    for( int i = 0; i < num_hp_parts; i++ ) {
        const std::string str = body_part_hp_bar_ui_text( part[i] );
        if( i % 2 == 0 ) {
            wmove( w, point( 0, i / 2 ) );
        } else {
            wmove( w, point( 11, i / 2 ) );
        }
        wprintz( w, u.limb_color( part[i], true, true, true ), str );
        if( i % 2 == 0 ) {
            wmove( w, point( 5, i / 2 ) );
        } else {
            wmove( w, point( 16, i / 2 ) );
        }
        draw_limb_health( u, w, i );
    }
    // print mood
    std::pair<nc_color, int> morale_pair = morale_stat( u );
    bool m_style = get_option<std::string>( "MORALE_STYLE" ) == "horizontal";
    std::string smiley = morale_emotion( morale_pair.second, get_face_type( u ), m_style );
    // print safe mode
    std::string safe_str;
    if( g->safe_mode || get_option<bool>( "AUTOSAFEMODE" ) ) {
        safe_str = _( "SAFE" );
    }
    mvwprintz( w, point( 22, 2 ), safe_color(), safe_str );
    mvwprintz( w, point( 27, 2 ), morale_pair.first, smiley );
    // print stamina
    const auto &stamina = get_hp_bar( u.get_stamina(), u.get_stamina_max() );
    mvwprintz( w, point( 22, 0 ), c_light_gray, _( "STM" ) );
    mvwprintz( w, point( 26, 0 ), stamina.second, stamina.first );
    mvwprintz( w, point( 22, 1 ), c_light_gray, _( "PWR" ) );
    const auto pwr = power_stat( u );
    mvwprintz( w, point( 31 - utf8_width( pwr.second ), 1 ), pwr.first, pwr.second );
    wnoutrefresh( w );
}
References _, body_part_hp_bar_ui_text(), c_light_gray, draw_limb_health(), g, get_face_type(), get_hp_bar(), Character::get_stamina(), Character::get_stamina_max(), Character::limb_color(), morale_emotion(), morale_stat(), mvwprintz(), num_hp_parts, power_stat(), safe_color(), utf8_width(), catacurses::werase(), catacurses::wmove(), catacurses::wnoutrefresh(), and wprintz().
Referenced by initialize_default_compact_panels().
draw_limb_health()
static void draw_limb_health (avatar & u, const catacurses::window & w, int limb_index) static
Definition at line 868 of file panels.cpp.
{
    const bool is_self_aware = u.has_trait( trait_SELFAWARE );
    static auto print_symbol_num = []( const catacurses::window & w, int num, const std::string & sym,
    const nc_color & color ) {
        while( num-- > 0 ) {
            wprintz( w, color, sym );
        }
    };
    const bodypart_id bp = convert_bp( avatar::hp_to_bp( static_cast<hp_part>( limb_index ) ) ).id();
    if( u.is_limb_broken( bp.id() ) && ( limb_index >= hp_arm_l &&
                                         limb_index <= hp_leg_r ) ) {
        //Limb is broken
        std::string limb = "~~%~~";
        nc_color color = c_light_red;
        if( u.worn_with_flag( "SPLINT",  bp ) ) {
            static const efftype_id effect_mending( "mending" );
            const auto &eff = u.get_effect( effect_mending, bp->token );
            const int mend_perc = eff.is_null() ? 0.0 : 100 * eff.get_duration() / eff.get_max_duration();
            if( is_self_aware || u.has_effect( effect_got_checked ) ) {
                limb = string_format( "=%2d%%=", mend_perc );
                color = c_blue;
            } else {
                const int num = mend_perc / 20;
                print_symbol_num( w, num, "#", c_blue );
                print_symbol_num( w, 5 - num, "=", c_blue );
                return;
            }
        }
        wprintz( w, color, limb );
        return;
    }
    const int hp_cur = u.get_part_hp_cur( bp );
    const int hp_max = u.get_part_hp_max( bp );
    std::pair<std::string, nc_color> hp = get_hp_bar( hp_cur, hp_max );
    if( is_self_aware || u.has_effect( effect_got_checked ) ) {
        wprintz( w, hp.second, "%3d  ", hp_cur );
    } else {
        wprintz( w, hp.second, hp.first );
        //Add the trailing symbols for a not-quite-full health bar
        print_symbol_num( w, 5 - utf8_width( hp.first ), ".", c_white );
    }
}
References c_blue, c_light_red, c_white, color(), convert_bp(), effect_got_checked, effect_mending, Creature::get_effect(), get_hp_bar(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Creature::has_effect(), Character::has_trait(), hp_arm_l, hp_leg_r, Character::hp_to_bp(), int_id< T >::id(), string_id< T >::id(), Character::is_limb_broken(), effect::is_null(), num, string_format(), trait_SELFAWARE, utf8_width(), Character::worn_with_flag(), and wprintz().
Referenced by draw_health_classic(), draw_limb2(), draw_limb_narrow(), and draw_limb_wide().
draw_limb_narrow()
static void draw_limb_narrow (avatar & u, const catacurses::window & w) static
Definition at line 1199 of file panels.cpp.
{
    werase( w );
    int ny2 = 0;
    for( int i = 0; i < num_hp_parts; i++ ) {
        int ny;
        int nx;
        if( i < 3 ) {
            ny = i;
            nx = 8;
        } else {
            ny = ny2++;
            nx = 26;
        }
        wmove( w, point( nx, ny ) );
        draw_limb_health( u, w, i );
    }
    // display limbs status
    static std::array<bodypart_id, 6> part = { {
            bodypart_id( "head" ), bodypart_id( "torso" ), bodypart_id( "arm_l" ), bodypart_id( "arm_r" ), bodypart_id( "leg_l" ), bodypart_id( "leg_r" )
        }
    };
    ny2 = 0;
    for( size_t i = 0; i < part.size(); i++ ) {
        int ny;
        int nx;
        if( i < 3 ) {
            ny = i;
            nx = 1;
        } else {
            ny = ny2++;
            nx = 19;
        }
        std::string str = body_part_hp_bar_ui_text( part[i] );
        wmove( w, point( nx, ny ) );
        str = left_justify( str, 5 );
        wprintz( w, u.limb_color( part[i], true, true, true ), str + ":" );
    }
    wnoutrefresh( w );
}
References body_part_hp_bar_ui_text(), draw_limb_health(), left_justify(), Character::limb_color(), num_hp_parts, catacurses::werase(), catacurses::wmove(), catacurses::wnoutrefresh(), and wprintz().
Referenced by initialize_default_label_narrow_panels().
draw_limb_wide()
static void draw_limb_wide (avatar & u, const catacurses::window & w) static
Definition at line 1242 of file panels.cpp.
{
    const std::vector<std::pair<bodypart_id, int>> parts = {
        {bodypart_id( "arm_l" ), 2},
        {bodypart_id( "head" ), 0},
        {bodypart_id( "arm_r" ), 3},
        {bodypart_id( "leg_l" ), 4},
        {bodypart_id( "torso" ), 1},
        {bodypart_id( "leg_r" ), 5}
    };
    werase( w );
    for( int i = 0; i < num_hp_parts; i++ ) {
        int offset = i * 15;
        int ny = offset / 45;
        int nx = offset % 45;
        std::string str = string_format( " %s: ",
                                         left_justify( body_part_hp_bar_ui_text( parts[i].first ), 5 ) );
        nc_color part_color = u.limb_color( parts[i].first, true, true, true );
        print_colored_text( w, point( nx, ny ), part_color, c_white, str );
        draw_limb_health( u, w, parts[i].second );
    }
    wnoutrefresh( w );
}
References body_part_hp_bar_ui_text(), c_white, draw_limb_health(), left_justify(), Character::limb_color(), num_hp_parts, print_colored_text(), second, string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_loc_labels()
static void draw_loc_labels (const avatar & u, const catacurses::window & w, bool minimap) static
Definition at line 1398 of file panels.cpp.
{
    werase( w );
    // display location
    const oter_id &cur_ter = overmap_buffer.ter( u.global_omt_location() );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Place: " ) );
    wprintz( w, c_white, utf8_truncate( cur_ter->get_name(), getmaxx( w ) - 13 ) );
    // display weather
    if( g->get_levz() < 0 ) {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Sky  : Underground" ) );
    } else {
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Sky  :" ) );
        wprintz( w, get_weather().weather_id->color, " %s", get_weather().weather_id->name.translated() );
    }
    // display lighting
    const std::pair<std::string, nc_color> ll = get_light_level(
                character_funcs::fine_detail_vision_mod( get_avatar() ) );
    mvwprintz( w, point( 1, 2 ), c_light_gray, "%s ", _( "Light:" ) );
    wprintz( w, ll.second, ll.first );
    // display date
    mvwprintz( w, point( 1, 3 ), c_light_gray, _( "Date : %s, day %d" ),
               calendar::name_season( season_of_year( calendar::turn ) ),
               day_of_season<int>( calendar::turn ) + 1 );
    // display time
    if( u.has_watch() ) {
        mvwprintz( w, point( 1, 4 ), c_light_gray, _( "Time : %s" ),
                   to_string_time_of_day( calendar::turn ) );
    } else if( g->get_levz() >= 0 ) {
        mvwprintz( w, point( 1, 4 ), c_light_gray, _( "Time : %s" ), time_approx() );
    } else {
        // NOLINTNEXTLINE(cata-text-style): the question mark does not end a sentence
        mvwprintz( w, point( 1, 4 ), c_light_gray, _( "Time : ???" ) );
    }
    if( minimap ) {
        const int offset = getmaxx( w ) - 6;
        const tripoint_abs_omt curs = u.global_omt_location();
        overmap_ui::draw_overmap_chunk( w, u, curs, point( offset, -1 ), 5, 5 );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, overmap_ui::draw_overmap_chunk(), character_funcs::fine_detail_vision_mod(), g, get_avatar(), get_light_level(), oter_t::get_name(), get_weather(), catacurses::getmaxx(), Character::global_omt_location(), Character::has_watch(), mvwprintz(), calendar::name_season(), overmap_buffer, season_of_year(), overmapbuffer::ter(), time_approx(), to_string_time_of_day(), calendar::turn, utf8_truncate(), catacurses::werase(), catacurses::wnoutrefresh(), and wprintz().
Referenced by draw_loc_narrow(), draw_loc_wide(), and draw_loc_wide_map().
draw_loc_narrow()
static void draw_loc_narrow (const avatar & u, const catacurses::window & w) static
Definition at line 1444 of file panels.cpp.
{
    draw_loc_labels( u, w, false );
}
References draw_loc_labels().
Referenced by initialize_default_label_narrow_panels().
draw_loc_wide()
static void draw_loc_wide (const avatar & u, const catacurses::window & w) static
Definition at line 1449 of file panels.cpp.
{
    draw_loc_labels( u, w, false );
}
References draw_loc_labels().
Referenced by initialize_default_label_panels().
draw_loc_wide_map()
static void draw_loc_wide_map (const avatar & u, const catacurses::window & w) static
Definition at line 1454 of file panels.cpp.
{
    draw_loc_labels( u, w, true );
}
References draw_loc_labels().
Referenced by initialize_default_label_panels().
draw_location_classic()
static void draw_location_classic (const avatar & u, const catacurses::window & w) static
Definition at line 1928 of file panels.cpp.
{
    werase( w );
    mvwprintz( w, point_zero, c_light_gray, _( "Location:" ) );
    mvwprintz( w, point( 10, 0 ), c_white, utf8_truncate( overmap_buffer.ter(
                   u.global_omt_location() )->get_name(), getmaxx( w ) - 13 ) );
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, oter_t::get_name(), catacurses::getmaxx(), Character::global_omt_location(), mvwprintz(), overmap_buffer, point_zero, overmapbuffer::ter(), utf8_truncate(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_mana_classic()
static void draw_mana_classic (const player & u, const catacurses::window & w) static
Definition at line 2101 of file panels.cpp.
{
    print_mana( u, w, "%s: %s %s: %s", -8, -5, 20, -5 );
}
References print_mana().
Referenced by initialize_default_classic_panels().
draw_mana_compact()
static void draw_mana_compact (const player & u, const catacurses::window & w) static
Definition at line 2106 of file panels.cpp.
{
    print_mana( u, w, "%s %s %s %s", 4, -5, 12, -5 );
}
References print_mana().
Referenced by initialize_default_compact_panels().
draw_mana_narrow()
static void draw_mana_narrow (const player & u, const catacurses::window & w) static
Definition at line 2111 of file panels.cpp.
{
    print_mana( u, w, " %s: %s %s : %s", -5, -5, 9, -5 );
}
References print_mana().
Referenced by initialize_default_label_narrow_panels().
draw_mana_wide()
static void draw_mana_wide (const player & u, const catacurses::window & w) static
Definition at line 2116 of file panels.cpp.
{
    print_mana( u, w, " %s: %s %s : %s", -5, -5, 13, -5 );
}
References print_mana().
Referenced by initialize_default_label_panels().
draw_messages()
static void draw_messages (avatar & , const catacurses::window & w) static
Definition at line 1811 of file panels.cpp.
{
    werase( w );
    int line = getmaxy( w ) - 2;
    int maxlength = getmaxx( w );
    Messages::display_messages( w, 1, 0 /*topline*/, maxlength - 1, line );
    wnoutrefresh( w );
}
References Messages::display_messages(), catacurses::getmaxx(), catacurses::getmaxy(), line(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_messages_classic()
static void draw_messages_classic (avatar & , const catacurses::window & w) static
Definition at line 1820 of file panels.cpp.
{
    werase( w );
    int line = getmaxy( w ) - 2;
    int maxlength = getmaxx( w );
    Messages::display_messages( w, 0, 0 /*topline*/, maxlength, line );
    wnoutrefresh( w );
}
References Messages::display_messages(), catacurses::getmaxx(), catacurses::getmaxy(), line(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels(), and initialize_default_compact_panels().
draw_minimap()
static void draw_minimap (const avatar & u, const catacurses::window & w_minimap) static
Definition at line 417 of file panels.cpp.
{
    const tripoint_abs_omt curs = u.global_omt_location();
    overmap_ui::draw_overmap_chunk( w_minimap, u, curs, point_zero, 5, 5 );
}
References overmap_ui::draw_overmap_chunk(), Character::global_omt_location(), and point_zero.
Referenced by draw_env_compact(), and draw_health_classic().
draw_moon_narrow()
static void draw_moon_narrow (const avatar & u, const catacurses::window & w) static
Definition at line 1459 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Moon : %s" ), get_moon() );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Temp : %s" ), get_temp( u ) );
    wnoutrefresh( w );
}
References _, c_light_gray, get_moon(), get_temp(), mvwprintz(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels().
draw_moon_wide()
static void draw_moon_wide (const avatar & u, const catacurses::window & w) static
Definition at line 1469 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Moon : %s" ), get_moon() );
    mvwprintz( w, point( 23, 0 ), c_light_gray, _( "Temp : %s" ), get_temp( u ) );
    wnoutrefresh( w );
}
References _, c_light_gray, get_moon(), get_temp(), mvwprintz(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_needs_compact()
static void draw_needs_compact (const avatar & u, const catacurses::window & w) static
Definition at line 1104 of file panels.cpp.
{
    werase( w );
    auto hunger_pair = u.get_hunger_description();
    mvwprintz( w, point_zero, hunger_pair.second, hunger_pair.first );
    hunger_pair = u.get_fatigue_description();
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 0, 1 ), hunger_pair.second, hunger_pair.first );
    auto pain_pair = u.get_pain_description();
    mvwprintz( w, point( 0, 2 ), pain_pair.second, pain_pair.first );
    hunger_pair = u.get_thirst_description();
    mvwprintz( w, point( 17, 0 ), hunger_pair.second, hunger_pair.first );
    auto pair = temp_stat( u );
    mvwprintz( w, point( 17, 1 ), pair.first, pair.second );
    const auto arrow = temp_delta_arrows( u );
    mvwprintz( w, point( 17 + utf8_width( pair.second ), 1 ), arrow.first, arrow.second );
    mvwprintz( w, point( 17, 2 ), c_light_gray, _( "Focus" ) );
    mvwprintz( w, point( 24, 2 ), focus_color( u.focus_pool ), std::to_string( u.focus_pool ) );
    wnoutrefresh( w );
}
References _, c_light_gray, focus_color(), Character::focus_pool, Character::get_fatigue_description(), Character::get_hunger_description(), Character::get_pain_description(), Character::get_thirst_description(), mvwprintz(), point_zero, temp_delta_arrows(), temp_stat(), to_string(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_needs_labels()
static void draw_needs_labels (const avatar & u, const catacurses::window & w) static
Definition at line 1541 of file panels.cpp.
{
    werase( w );
    std::pair<std::string, nc_color> hunger_pair = u.get_hunger_description();
    std::pair<std::string, nc_color> thirst_pair = u.get_thirst_description();
    std::pair<std::string, nc_color> rest_pair = u.get_fatigue_description();
    std::pair<nc_color, std::string> temp_pair = temp_stat( u );
    std::pair<std::string, nc_color> pain_pair = u.get_pain_description();
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Pain :" ) );
    mvwprintz( w, point( 8, 0 ), pain_pair.second, pain_pair.first );
    mvwprintz( w, point( 23, 0 ), c_light_gray, _( "Thirst:" ) );
    mvwprintz( w, point( 30, 0 ), thirst_pair.second, thirst_pair.first );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Rest :" ) );
    mvwprintz( w, point( 8, 1 ), rest_pair.second, rest_pair.first );
    mvwprintz( w, point( 23, 1 ), c_light_gray, _( "Hunger:" ) );
    mvwprintz( w, point( 30, 1 ), hunger_pair.second, hunger_pair.first );
    mvwprintz( w, point( 1, 2 ), c_light_gray, _( "Heat :" ) );
    mvwprintz( w, point( 8, 2 ), temp_pair.first, temp_pair.second );
    wnoutrefresh( w );
}
References _, c_light_gray, Character::get_fatigue_description(), Character::get_hunger_description(), Character::get_pain_description(), Character::get_thirst_description(), mvwprintz(), temp_stat(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_needs_narrow()
static void draw_needs_narrow (const avatar & u, const catacurses::window & w) static
Definition at line 1518 of file panels.cpp.
{
    werase( w );
    std::pair<std::string, nc_color> hunger_pair = u.get_hunger_description();
    std::pair<std::string, nc_color> thirst_pair = u.get_thirst_description();
    std::pair<std::string, nc_color> rest_pair = u.get_fatigue_description();
    std::pair<nc_color, std::string> temp_pair = temp_stat( u );
    std::pair<std::string, nc_color> pain_pair = u.get_pain_description();
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Hunger:" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Thirst:" ) );
    mvwprintz( w, point( 1, 2 ), c_light_gray, _( "Rest :" ) );
    mvwprintz( w, point( 1, 3 ), c_light_gray, _( "Pain :" ) );
    mvwprintz( w, point( 1, 4 ), c_light_gray, _( "Heat :" ) );
    mvwprintz( w, point( 8, 0 ), hunger_pair.second, hunger_pair.first );
    mvwprintz( w, point( 8, 1 ), thirst_pair.second, thirst_pair.first );
    mvwprintz( w, point( 8, 2 ), rest_pair.second, rest_pair.first );
    mvwprintz( w, point( 8, 3 ), pain_pair.second, pain_pair.first );
    mvwprintz( w, point( 8, 4 ), temp_pair.first, temp_pair.second );
    wnoutrefresh( w );
}
References _, c_light_gray, Character::get_fatigue_description(), Character::get_hunger_description(), Character::get_pain_description(), Character::get_thirst_description(), mvwprintz(), temp_stat(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels().
draw_rectangle()
static void draw_rectangle (const catacurses::window & w, nc_color , point top_left, point bottom_right) static
Definition at line 95 of file panels.cpp.
{
    // corners
    mvwaddch( w, top_left, LINE_OXXO );
    mvwaddch( w, point( top_left.x, bottom_right.y ), LINE_XXOO );
    mvwaddch( w, point( bottom_right.x, top_left.y ), LINE_OOXX );
    mvwaddch( w, bottom_right, LINE_XOOX );
    for( int i = 1; i < bottom_right.x; i++ ) {
        mvwaddch( w, point( i, top_left.y ), LINE_OXOX );
        mvwaddch( w, point( i, bottom_right.y ), LINE_OXOX );
    }
    for( int i = 1; i < bottom_right.y; i++ ) {
        mvwaddch( w, point( top_left.x, i ), LINE_XOXO );
        mvwaddch( w, point( bottom_right.x, i ), LINE_XOXO );
    }
}
References LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, catacurses::mvwaddch(), point::x, and point::y.
Referenced by draw_health_classic().
draw_sound_labels()
static void draw_sound_labels (const avatar & u, const catacurses::window & w) static
Definition at line 1565 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Sound:" ) );
    if( !u.is_deaf() ) {
        mvwprintz( w, point( 8, 0 ), c_yellow, std::to_string( u.volume ) );
    } else {
        mvwprintz( w, point( 8, 0 ), c_red, _( "Deaf!" ) );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, Character::is_deaf(), mvwprintz(), to_string(), player::volume, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_sound_narrow()
static void draw_sound_narrow (const avatar & u, const catacurses::window & w) static
Definition at line 1578 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Sound:" ) );
    if( !u.is_deaf() ) {
        mvwprintz( w, point( 8, 0 ), c_yellow, std::to_string( u.volume ) );
    } else {
        mvwprintz( w, point( 8, 0 ), c_red, _( "Deaf!" ) );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, Character::is_deaf(), mvwprintz(), to_string(), player::volume, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels().
draw_stat_narrow()
static void draw_stat_narrow (avatar & u, const catacurses::window & w) static
Definition at line 1344 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Str  :" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Int  :" ) );
    mvwprintz( w, point( 19, 0 ), c_light_gray, _( "Dex  :" ) );
    mvwprintz( w, point( 19, 1 ), c_light_gray, _( "Per  :" ) );
    nc_color stat_clr = str_string( u ).first;
    mvwprintz( w, point( 8, 0 ), stat_clr, "%s", u.get_str() );
    stat_clr = int_string( u ).first;
    mvwprintz( w, point( 8, 1 ), stat_clr, "%s", u.get_int() );
    stat_clr = dex_string( u ).first;
    mvwprintz( w, point( 26, 0 ), stat_clr, "%s", u.get_dex() );
    stat_clr = per_string( u ).first;
    mvwprintz( w, point( 26, 1 ), stat_clr, "%s", u.get_per() );
    std::pair<nc_color, std::string> pwr_pair = power_stat( u );
    mvwprintz( w, point( 1, 2 ), c_light_gray, _( "Power:" ) );
    mvwprintz( w, point( 19, 2 ), c_light_gray, _( "Safe :" ) );
    mvwprintz( w, point( 8, 2 ), pwr_pair.first, "%s", pwr_pair.second );
    mvwprintz( w, point( 26, 2 ), safe_color(), g->safe_mode ? _( "On" ) : _( "Off" ) );
    wnoutrefresh( w );
}
References _, c_light_gray, dex_string(), g, Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_str(), int_string(), mvwprintz(), per_string(), power_stat(), safe_color(), str_string(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels().
draw_stat_wide()
static void draw_stat_wide (avatar & u, const catacurses::window & w) static
Definition at line 1372 of file panels.cpp.
{
    werase( w );
    mvwprintz( w, point_east, c_light_gray, _( "Str  :" ) );
    mvwprintz( w, point_south_east, c_light_gray, _( "Int  :" ) );
    mvwprintz( w, point( 16, 0 ), c_light_gray, _( "Dex  :" ) );
    mvwprintz( w, point( 16, 1 ), c_light_gray, _( "Per  :" ) );
    nc_color stat_clr = str_string( u ).first;
    mvwprintz( w, point( 8, 0 ), stat_clr, "%s", u.get_str() );
    stat_clr = int_string( u ).first;
    mvwprintz( w, point( 8, 1 ), stat_clr, "%s", u.get_int() );
    stat_clr = dex_string( u ).first;
    mvwprintz( w, point( 23, 0 ), stat_clr, "%s", u.get_dex() );
    stat_clr = per_string( u ).first;
    mvwprintz( w, point( 23, 1 ), stat_clr, "%s", u.get_per() );
    std::pair<nc_color, std::string> pwr_pair = power_stat( u );
    mvwprintz( w, point( 31, 0 ), c_light_gray, _( "Power:" ) );
    mvwprintz( w, point( 31, 1 ), c_light_gray, _( "Safe :" ) );
    mvwprintz( w, point( 38, 0 ), pwr_pair.first, "%s", pwr_pair.second );
    mvwprintz( w, point( 38, 1 ), safe_color(), g->safe_mode ? _( "On" ) : _( "Off" ) );
    wnoutrefresh( w );
}
References _, c_light_gray, dex_string(), g, Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_str(), int_string(), mvwprintz(), per_string(), point_east, point_south_east, power_stat(), safe_color(), str_string(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_stats()
static void draw_stats (avatar & u, const catacurses::window & w) static
Definition at line 968 of file panels.cpp.
{
    werase( w );
    nc_color stat_clr = str_string( u ).first;
    mvwprintz( w, point_zero, c_light_gray, _( "STR" ) );
    int stat = u.get_str();
    mvwprintz( w, point( stat < 10 ? 5 : 4, 0 ), stat_clr,
               stat < 100 ? std::to_string( stat ) : "99+" );
    stat_clr = dex_string( u ).first;
    stat = u.get_dex();
    mvwprintz( w, point( 9, 0 ), c_light_gray, _( "DEX" ) );
    mvwprintz( w, point( stat < 10 ? 14 : 13, 0 ), stat_clr,
               stat < 100 ? std::to_string( stat ) : "99+" );
    stat_clr = int_string( u ).first;
    stat = u.get_int();
    mvwprintz( w, point( 17, 0 ), c_light_gray, _( "INT" ) );
    mvwprintz( w, point( stat < 10 ? 22 : 21, 0 ), stat_clr,
               stat < 100 ? std::to_string( stat ) : "99+" );
    stat_clr = per_string( u ).first;
    stat = u.get_per();
    mvwprintz( w, point( 25, 0 ), c_light_gray, _( "PER" ) );
    mvwprintz( w, point( stat < 10 ? 30 : 29, 0 ), stat_clr,
               stat < 100 ? std::to_string( stat ) : "99+" );
    wnoutrefresh( w );
}
References _, c_light_gray, dex_string(), Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_str(), int_string(), mvwprintz(), per_string(), point_zero, str_string(), to_string(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_stealth()
static void draw_stealth (avatar & u, const catacurses::window & w) static
Definition at line 1016 of file panels.cpp.
{
    werase( w );
    mvwprintz( w, point_zero, c_light_gray, _( "Speed" ) );
    mvwprintz( w, point( 7, 0 ), value_color( u.get_speed() ), "%s", u.get_speed() );
    nc_color move_color = move_mode_color( u );
    std::string move_string = std::to_string( u.movecounter ) + move_mode_string( u );
    mvwprintz( w, point( 15 - utf8_width( move_string ), 0 ), move_color, move_string );
    if( u.is_deaf() ) {
        mvwprintz( w, point( 22, 0 ), c_red, _( "DEAF" ) );
    } else {
        mvwprintz( w, point( 20, 0 ), c_light_gray, _( "Sound:" ) );
        const std::string snd = std::to_string( u.volume );
        mvwprintz( w, point( 30 - utf8_width( snd ), 0 ), u.volume != 0 ? c_yellow : c_light_gray, snd );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, Character::get_speed(), Character::is_deaf(), move_mode_color(), move_mode_string(), player::movecounter, mvwprintz(), point_zero, to_string(), utf8_width(), value_color(), player::volume, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_time()
static void draw_time (const avatar & u, const catacurses::window & w) static
Definition at line 1079 of file panels.cpp.
{
    werase( w );
    // display date
    mvwprintz( w, point_zero, c_light_gray, calendar::name_season( season_of_year( calendar::turn ) ) );
    std::string day = std::to_string( day_of_season<int>( calendar::turn ) + 1 );
    mvwprintz( w, point( 10 - utf8_width( day ), 0 ), c_light_gray, day );
    // display time
    if( u.has_watch() ) {
        mvwprintz( w, point( 11, 0 ), c_light_gray, to_string_time_of_day( calendar::turn ) );
    } else if( g->get_levz() >= 0 ) {
        wmove( w, point( 11, 0 ) );
        draw_time_graphic( w );
    } else {
        // NOLINTNEXTLINE(cata-text-style): the question mark does not end a sentence
        mvwprintz( w, point( 11, 0 ), c_light_gray, _( "Time: ???" ) );
    }
    //display moon
    mvwprintz( w, point( 22, 0 ), c_white, _( "Moon" ) );
    nc_color clr = c_white;
    print_colored_text( w, point( 27, 0 ), clr, c_white, get_moon_graphic() );
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, day, draw_time_graphic(), g, get_moon_graphic(), Character::has_watch(), mvwprintz(), calendar::name_season(), point_zero, print_colored_text(), season_of_year(), to_string(), to_string_time_of_day(), calendar::turn, utf8_width(), catacurses::werase(), catacurses::wmove(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_time_classic()
static void draw_time_classic (const avatar & u, const catacurses::window & w) static
Definition at line 2043 of file panels.cpp.
{
    werase( w );
    // display date
    mvwprintz( w, point_zero, c_white,
               calendar::name_season( season_of_year( calendar::turn ) ) + "," );
    std::string day = std::to_string( day_of_season<int>( calendar::turn ) + 1 );
    mvwprintz( w, point( 8, 0 ), c_white, _( "Day " ) + day );
    // display time
    if( u.has_watch() ) {
        mvwprintz( w, point( 15, 0 ), c_light_gray, to_string_time_of_day( calendar::turn ) );
    } else if( g->get_levz() >= 0 ) {
        wmove( w, point( 15, 0 ) );
        draw_time_graphic( w );
    } else {
        // NOLINTNEXTLINE(cata-text-style): the question mark does not end a sentence
        mvwprintz( w, point( 15, 0 ), c_light_gray, _( "Time: ???" ) );
    }
    if( u.has_item_with_flag( "THERMOMETER" ) || u.has_bionic( bionic_id( "bio_meteorologist" ) ) ) {
        std::string temp = print_temperature( get_weather().get_temperature( u.pos() ) );
        mvwprintz( w, point( 31, 0 ), c_light_gray, _( "Temp : " ) + temp );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, day, draw_time_graphic(), g, get_weather(), Character::has_bionic(), Character::has_item_with_flag(), Character::has_watch(), mvwprintz(), calendar::name_season(), point_zero, Character::pos(), print_temperature(), season_of_year(), to_string(), to_string_time_of_day(), calendar::turn, catacurses::werase(), catacurses::wmove(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_time_graphic()
static void draw_time_graphic (const catacurses::window & w) static
Definition at line 1035 of file panels.cpp.
{
    std::vector<std::pair<char, nc_color> > vGlyphs;
    vGlyphs.push_back( std::make_pair( '_', c_red ) );
    vGlyphs.push_back( std::make_pair( '_', c_cyan ) );
    vGlyphs.push_back( std::make_pair( '.', c_brown ) );
    vGlyphs.push_back( std::make_pair( ',', c_blue ) );
    vGlyphs.push_back( std::make_pair( '+', c_yellow ) );
    vGlyphs.push_back( std::make_pair( 'c', c_light_blue ) );
    vGlyphs.push_back( std::make_pair( '*', c_yellow ) );
    vGlyphs.push_back( std::make_pair( 'C', c_white ) );
    vGlyphs.push_back( std::make_pair( '+', c_yellow ) );
    vGlyphs.push_back( std::make_pair( 'c', c_light_blue ) );
    vGlyphs.push_back( std::make_pair( '.', c_brown ) );
    vGlyphs.push_back( std::make_pair( ',', c_blue ) );
    vGlyphs.push_back( std::make_pair( '_', c_red ) );
    vGlyphs.push_back( std::make_pair( '_', c_cyan ) );
    const int iHour = hour_of_day<int>( calendar::turn );
    wprintz( w, c_white, "[" );
    bool bAddTrail = false;
    for( int i = 0; i < 14; i += 2 ) {
        if( iHour >= 8 + i && iHour <= 13 + ( i / 2 ) ) {
            wputch( w, hilite( c_white ), ' ' );
        } else if( iHour >= 6 + i && iHour <= 7 + i ) {
            wputch( w, hilite( vGlyphs[i].second ), vGlyphs[i].first );
            bAddTrail = true;
        } else if( iHour >= ( 18 + i ) % 24 && iHour <= ( 19 + i ) % 24 ) {
            wputch( w, vGlyphs[i + 1].second, vGlyphs[i + 1].first );
        } else if( bAddTrail && iHour >= 6 + ( i / 2 ) ) {
            wputch( w, hilite( c_white ), ' ' );
        } else {
            wputch( w, c_white, ' ' );
        }
    }
    wprintz( w, c_white, "]" );
}
References c_blue, c_brown, c_cyan, c_light_blue, c_red, c_white, c_yellow, hilite(), second, calendar::turn, wprintz(), and wputch().
Referenced by draw_time(), and draw_time_classic().
draw_veh_compact()
static void draw_veh_compact (const avatar & u, const catacurses::window & w) static
Definition at line 1852 of file panels.cpp.
{
    werase( w );
    // vehicle display
    vehicle *veh = g->remoteveh();
    if( veh == nullptr && u.in_vehicle ) {
        veh = veh_pointer_or_null( get_map().veh_at( u.pos() ) );
    }
    if( veh ) {
        veh->print_fuel_indicators( w, point_zero );
        mvwprintz( w, point( 6, 0 ), c_light_gray, veh->face.to_string_azimuth_from_north() );
        // target speed > current speed
        const float strain = veh->strain();
        if( veh->cruise_on ) {
            nc_color col_vel = strain <= 0 ? c_light_blue :
                               ( strain <= 0.2 ? c_yellow :
                                 ( strain <= 0.4 ? c_light_red : c_red ) );
            int t_speed = static_cast<int>( convert_velocity( veh->cruise_velocity, VU_VEHICLE ) );
            int c_speed = static_cast<int>( convert_velocity( veh->velocity, VU_VEHICLE ) );
            int offset = get_int_digits( t_speed );
            const std::string type = get_option<std::string>( "USE_METRIC_SPEEDS" );
            mvwprintz( w, point( 12, 0 ), c_light_gray, "%s :", type );
            mvwprintz( w, point( 19, 0 ), c_light_green, "%d", t_speed );
            mvwprintz( w, point( 20 + offset, 0 ), c_light_gray, "%s", ">" );
            mvwprintz( w, point( 22 + offset, 0 ), col_vel, "%d", c_speed );
        }
    }
    wnoutrefresh( w );
}
References c_light_blue, c_light_gray, c_light_green, c_light_red, c_red, c_yellow, convert_velocity(), vehicle::cruise_on, vehicle::cruise_velocity, vehicle::face, g, get_int_digits(), get_map(), Character::in_vehicle, mvwprintz(), point_zero, Character::pos(), vehicle::print_fuel_indicators(), vehicle::strain(), tileray::to_string_azimuth_from_north(), type, veh_pointer_or_null(), vehicle::velocity, VU_VEHICLE, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_veh_padding()
static void draw_veh_padding (const avatar & u, const catacurses::window & w) static
Definition at line 1884 of file panels.cpp.
{
    werase( w );
    // vehicle display
    vehicle *veh = g->remoteveh();
    if( veh == nullptr && u.in_vehicle ) {
        veh = veh_pointer_or_null( get_map().veh_at( u.pos() ) );
    }
    if( veh ) {
        veh->print_fuel_indicators( w, point_east );
        mvwprintz( w, point( 7, 0 ), c_light_gray, veh->face.to_string_azimuth_from_north() );
        // target speed > current speed
        const float strain = veh->strain();
        nc_color col_vel = strain <= 0 ? c_light_blue :
                           ( strain <= 0.2 ? c_yellow :
                             ( strain <= 0.4 ? c_light_red : c_red ) );
        if( veh->cruise_on ) {
            int t_speed = static_cast<int>( convert_velocity( veh->cruise_velocity, VU_VEHICLE ) );
            int c_speed = static_cast<int>( convert_velocity( veh->velocity, VU_VEHICLE ) );
            int offset = get_int_digits( t_speed );
            const std::string type = get_option<std::string>( "USE_METRIC_SPEEDS" );
            mvwprintz( w, point( 13, 0 ), c_light_gray, "%s :", type );
            mvwprintz( w, point( 20, 0 ), c_light_green, "%d", t_speed );
            mvwprintz( w, point( 21 + offset, 0 ), c_light_gray, "%s", ">" );
            mvwprintz( w, point( 23 + offset, 0 ), col_vel, "%d", c_speed );
        }
    }
    wnoutrefresh( w );
}
References c_light_blue, c_light_gray, c_light_green, c_light_red, c_red, c_yellow, convert_velocity(), vehicle::cruise_on, vehicle::cruise_velocity, vehicle::face, g, get_int_digits(), get_map(), Character::in_vehicle, mvwprintz(), point_east, Character::pos(), vehicle::print_fuel_indicators(), vehicle::strain(), tileray::to_string_azimuth_from_north(), type, veh_pointer_or_null(), vehicle::velocity, VU_VEHICLE, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_weapon_classic()
static void draw_weapon_classic (const avatar & u, const catacurses::window & w) static
Definition at line 1976 of file panels.cpp.
{
    werase( w );
    mvwprintz( w, point_zero, c_light_gray, _( "Weapon  :" ) );
    trim_and_print( w, point( 10, 0 ), getmaxx( w ) - 24, c_light_gray, u.weapname() );
    // Print in sidebar currently used martial style.
    const std::string style = u.martial_arts_data->selected_style_name( u );
    if( !style.empty() ) {
        const auto style_color = u.is_armed() ? c_red : c_blue;
        mvwprintz( w, point( 31, 0 ), style_color, style );
    }
    wnoutrefresh( w );
}
References _, c_blue, c_light_gray, c_red, catacurses::getmaxx(), Character::is_armed(), Character::martial_arts_data, mvwprintz(), point_zero, trim_and_print(), player::weapname(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_weapon_classic_alt()
static void draw_weapon_classic_alt (const avatar & u, const catacurses::window & w) static
Definition at line 1995 of file panels.cpp.
{
    werase( w );
    mvwprintz( w, point_zero, c_light_gray, _( "Weapon:" ) );
    trim_and_print( w, point( 8, 0 ), getmaxx( w ) - 2, c_light_gray, u.weapname() );
    // Print in sidebar currently used martial style.
    const std::string style = u.martial_arts_data->selected_style_name( u );
    if( !style.empty() ) {
        const auto style_color = u.is_armed() ? c_red : c_blue;
        // NOLINTNEXTLINE(cata-use-named-point-constants)
        mvwprintz( w, point( 0, 1 ), c_light_gray, _( "Style :" ) );
        mvwprintz( w, point( 8, 1 ), style_color, style );
    }
    wnoutrefresh( w );
}
References _, c_blue, c_light_gray, c_red, catacurses::getmaxx(), Character::is_armed(), Character::martial_arts_data, mvwprintz(), point_zero, trim_and_print(), player::weapname(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_weapon_labels()
static void draw_weapon_labels (const avatar & u, const catacurses::window & w) static
Definition at line 1478 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Wield:" ) );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Style:" ) );
    trim_and_print( w, point( 8, 0 ), getmaxx( w ) - 8, c_light_gray, u.weapname() );
    mvwprintz( w, point( 8, 1 ), c_light_gray, "%s", u.martial_arts_data->selected_style_name( u ) );
    wnoutrefresh( w );
}
References _, c_light_gray, catacurses::getmaxx(), Character::martial_arts_data, mvwprintz(), trim_and_print(), player::weapname(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels(), and initialize_default_label_panels().
draw_weather_classic()
static void draw_weather_classic (avatar & , const catacurses::window & w) static
Definition at line 1939 of file panels.cpp.
{
    werase( w );
    if( g->get_levz() < 0 ) {
        mvwprintz( w, point_zero, c_light_gray, _( "Underground" ) );
    } else {
        mvwprintz( w, point_zero, c_light_gray, _( "Weather :" ) );
        mvwprintz( w, point( 10, 0 ), get_weather().weather_id->color,
                   get_weather().weather_id->name.translated() );
    }
    mvwprintz( w, point( 31, 0 ), c_light_gray, _( "Moon :" ) );
    nc_color clr = c_white;
    print_colored_text( w, point( 38, 0 ), clr, c_white, get_moon_graphic() );
    wnoutrefresh( w );
}
References _, c_light_gray, c_white, g, get_moon_graphic(), get_weather(), mvwprintz(), point_zero, print_colored_text(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_weightvolume_classic()
static void draw_weightvolume_classic (const avatar & u, const catacurses::window & w) static
Definition at line 2016 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point_zero, c_light_gray, _( "Weight:" ) );
    std::string weight_string = carry_weight_string( u );
    if( u.weight_carried() > u.weight_capacity() ) {
        mvwprintz( w, point( 8, 0 ), c_red, weight_string );
    } else if( u.weight_carried() > u.weight_capacity() * 0.75 ) {
        mvwprintz( w, point( 8, 0 ), c_yellow, weight_string );
    } else {
        mvwprintz( w, point( 8, 0 ), c_light_gray, weight_string );
    }
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 23, 0 ), c_light_gray, _( "Volume:" ) );
    std::string volume_string = carry_volume_string( u );
    if( u.volume_carried() > u.volume_capacity() * 0.85 ) {
        mvwprintz( w, point( 30, 0 ), c_red, volume_string );
    } else if( u.volume_carried() > u.volume_capacity() * 0.65 ) {
        mvwprintz( w, point( 30, 0 ), c_yellow, volume_string );
    } else {
        mvwprintz( w, point( 30, 0 ), c_light_gray, volume_string );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, carry_volume_string(), carry_weight_string(), mvwprintz(), point_zero, Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), Character::weight_carried(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_classic_panels().
draw_weightvolume_compact()
static void draw_weightvolume_compact (const avatar & u, const catacurses::window & w) static
Definition at line 1145 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point_zero, c_light_gray, _( "Weight:" ) );
    std::string weight_string = carry_weight_string( u );
    if( u.weight_carried() > u.weight_capacity() ) {
        mvwprintz( w, point( 8, 0 ), c_red, weight_string );
    } else if( u.weight_carried() > u.weight_capacity() * 0.75 ) {
        mvwprintz( w, point( 8, 0 ), c_yellow, weight_string );
    } else {
        mvwprintz( w, point( 8, 0 ), c_light_gray, weight_string );
    }
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 0, 1 ), c_light_gray, _( "Volume:" ) );
    std::string volume_string = carry_volume_string( u );
    if( u.volume_carried() > u.volume_capacity() * 0.85 ) {
        mvwprintz( w, point( 8, 1 ), c_red, volume_string );
    } else if( u.volume_carried() > u.volume_capacity() * 0.65 ) {
        mvwprintz( w, point( 8, 1 ), c_yellow, volume_string );
    } else {
        mvwprintz( w, point( 8, 1 ), c_light_gray, volume_string );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, carry_volume_string(), carry_weight_string(), mvwprintz(), point_zero, Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), Character::weight_carried(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_compact_panels().
draw_weightvolume_labels()
static void draw_weightvolume_labels (const avatar & u, const catacurses::window & w) static
Definition at line 1490 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Wgt  :" ) );
    std::string weight_string = carry_weight_string( u );
    if( u.weight_carried() > u.weight_capacity() ) {
        mvwprintz( w, point( 8, 0 ), c_red, weight_string );
    } else if( u.weight_carried() > u.weight_capacity() * 0.75 ) {
        mvwprintz( w, point( 8, 0 ), c_yellow, weight_string );
    } else {
        mvwprintz( w, point( 8, 0 ), c_light_gray, weight_string );
    }
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 23, 0 ), c_light_gray, _( "Volume:" ) );
    std::string volume_string = carry_volume_string( u );
    if( u.volume_carried() > u.volume_capacity() * 0.85 ) {
        mvwprintz( w, point( 30, 0 ), c_red, volume_string );
    } else if( u.volume_carried() > u.volume_capacity() * 0.65 ) {
        mvwprintz( w, point( 30, 0 ), c_yellow, volume_string );
    } else {
        mvwprintz( w, point( 30, 0 ), c_light_gray, volume_string );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, carry_volume_string(), carry_weight_string(), mvwprintz(), Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), Character::weight_carried(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_panels().
draw_weightvolume_narrow()
static void draw_weightvolume_narrow (const avatar & u, const catacurses::window & w) static
Definition at line 1172 of file panels.cpp.
{
    werase( w );
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 0 ), c_light_gray, _( "Wgt  :" ) );
    std::string weight_string = carry_weight_string( u );
    if( u.weight_carried() > u.weight_capacity() ) {
        mvwprintz( w, point( 8, 0 ), c_red, weight_string );
    } else if( u.weight_carried() > u.weight_capacity() * 0.75 ) {
        mvwprintz( w, point( 8, 0 ), c_yellow, weight_string );
    } else {
        mvwprintz( w, point( 8, 0 ), c_light_gray, weight_string );
    }
    // NOLINTNEXTLINE(cata-use-named-point-constants)
    mvwprintz( w, point( 1, 1 ), c_light_gray, _( "Vol  :" ) );
    std::string volume_string = carry_volume_string( u );
    if( u.volume_carried() > u.volume_capacity() * 0.85 ) {
        mvwprintz( w, point( 8, 1 ), c_red, volume_string );
    } else if( u.volume_carried() > u.volume_capacity() * 0.65 ) {
        mvwprintz( w, point( 8, 1 ), c_yellow, volume_string );
    } else {
        mvwprintz( w, point( 8, 1 ), c_light_gray, volume_string );
    }
    wnoutrefresh( w );
}
References _, c_light_gray, c_red, c_yellow, carry_volume_string(), carry_weight_string(), mvwprintz(), Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), Character::weight_carried(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_label_narrow_panels().
draw_wind()
static void draw_wind (avatar & u, const catacurses::window & w) static
Definition at line 1645 of file panels.cpp.
{
    render_wind( u, w, "%s: " );
}
References render_wind().
Referenced by initialize_default_classic_panels().
draw_wind_padding()
static void draw_wind_padding (avatar & u, const catacurses::window & w) static
Definition at line 1650 of file panels.cpp.
{
    render_wind( u, w, " %s: " );
}
References render_wind().
Referenced by initialize_default_label_narrow_panels(), and initialize_default_label_panels().
focus_color()
static nc_color focus_color (int focus) static
Definition at line 175 of file panels.cpp.
{
    if( focus < 25 ) {
        return c_red;
    } else if( focus < 50 ) {
        return c_light_red;
    } else if( focus < 75 ) {
        return c_yellow;
    } else if( focus < 100 ) {
        return c_light_gray;
    } else if( focus < 125 ) {
        return c_white;
    } else {
        return c_green;
    }
}
References c_green, c_light_gray, c_light_red, c_red, c_white, and c_yellow.
Referenced by draw_char_narrow(), draw_char_wide(), and draw_needs_compact().
get_armor()
static std::string get_armor (const avatar & u, body_part bp, unsigned int truncate = 0) static
Definition at line 683 of file panels.cpp.
{
    for( std::list<item>::const_iterator it = u.worn.end(); it != u.worn.begin(); ) {
        --it;
        if( it->covers( bp ) ) {
            return it->tname( 1, true, truncate );
        }
    }
    return "-";
}
References Character::worn.
Referenced by draw_armor(), and draw_armor_padding().
get_face_type()
static face_type get_face_type (const avatar & u) static
Definition at line 694 of file panels.cpp.
{
    face_type fc = face_human;
    if( u.has_trait( trait_THRESH_FELINE ) ) {
        fc = face_cat;
    } else if( u.has_trait( trait_THRESH_URSINE ) ) {
        fc = face_bear;
    } else if( u.has_trait( trait_THRESH_BIRD ) ) {
        fc = face_bird;
    }
    return fc;
}
References face_bear, face_bird, face_cat, face_human, Character::has_trait(), trait_THRESH_BIRD, trait_THRESH_FELINE, and trait_THRESH_URSINE.
Referenced by draw_char_narrow(), draw_char_wide(), draw_health_classic(), and draw_limb2().
get_int_digits()
static int get_int_digits (const int & digits) static
Definition at line 853 of file panels.cpp.
{
    int temp = std::abs( digits );
    if( digits > 0 ) {
        return static_cast<int>( std::log10( static_cast<double>( temp ) ) ) + 1;
    } else if( digits < 0 ) {
        return static_cast<int>( std::log10( static_cast<double>( temp ) ) ) + 2;
    }
    return 1;
}
Referenced by draw_health_classic(), draw_veh_compact(), and draw_veh_padding().
get_moon()
static std::string get_moon () static
Definition at line 468 of file panels.cpp.
{
    const int iPhase = static_cast<int>( get_moon_phase( calendar::turn ) );
    switch( iPhase ) {
        case 0:
            return _( "New moon" );
        case 1:
            return _( "Waxing crescent" );
        case 2:
            return _( "Half moon" );
        case 3:
            return _( "Waxing gibbous" );
        case 4:
            return _( "Full moon" );
        case 5:
            return _( "Waning gibbous" );
        case 6:
            return _( "Half moon" );
        case 7:
            return _( "Waning crescent" );
        case 8:
            return _( "Dark moon" );
        default:
            return "";
    }
}
References _, get_moon_phase(), and calendar::turn.
Referenced by draw_moon_narrow(), and draw_moon_wide().
get_moon_graphic()
static std::string get_moon_graphic () static
Definition at line 452 of file panels.cpp.
{
    //moon phase display
    static std::vector<std::string> vMoonPhase = { "(   )", "(  ))", "( | )", "((  )" };
    const int iPhase = static_cast<int>( get_moon_phase( calendar::turn ) );
    std::string sPhase = vMoonPhase[iPhase % 4];
    if( iPhase > 0 ) {
        sPhase.insert( 5 - ( ( iPhase > 4 ) ? iPhase % 4 : 0 ), "</color>" );
        sPhase.insert( 5 - ( ( iPhase < 4 ) ? iPhase + 1 : 5 ),
                       "<color_" + string_from_color( i_black ) + ">" );
    }
    return sPhase;
}
References get_moon_phase(), i_black, string_from_color(), and calendar::turn.
Referenced by draw_time(), and draw_weather_classic().
get_temp()
static std::string get_temp (const avatar & u) static
Definition at line 439 of file panels.cpp.
{
    std::string temp;
    if( u.has_item_with_flag( "THERMOMETER" ) ||
        u.has_bionic( bionic_id( "bio_meteorologist" ) ) ) {
        temp = print_temperature( get_weather().get_temperature( u.pos() ) );
    }
    if( temp.empty() ) {
        return "-";
    }
    return temp;
}
References get_weather(), Character::has_bionic(), Character::has_item_with_flag(), Character::pos(), and print_temperature().
Referenced by draw_moon_narrow(), and draw_moon_wide().
initialize_default_classic_panels()
static std::vector< window_panel > initialize_default_classic_panels () static
Definition at line 2135 of file panels.cpp.
{
    std::vector<window_panel> ret;
    ret.emplace_back( window_panel( draw_health_classic, translate_marker( "Health" ), 7, 44, true ) );
    ret.emplace_back( window_panel( draw_location_classic, translate_marker( "Location" ), 1, 44,
                                    true ) );
    ret.emplace_back( window_panel( draw_mana_classic, translate_marker( "Mana" ), 1, 44, true,
                                    spell_panel ) );
    ret.emplace_back( window_panel( draw_weather_classic, translate_marker( "Weather" ), 1, 44,
                                    true ) );
    ret.emplace_back( window_panel( draw_lighting_classic, translate_marker( "Lighting" ), 1, 44,
                                    true ) );
    ret.emplace_back( window_panel( draw_weapon_classic, translate_marker( "Weapon" ), 1, 44, true ) );
    ret.emplace_back( window_panel( draw_weapon_classic_alt, translate_marker( "Weapon_alt" ), 2, 44,
                                    false ) );
    ret.emplace_back( window_panel( draw_weightvolume_classic, translate_marker( "Wgt/Vol" ), 1, 44,
                                    true ) );
    ret.emplace_back( window_panel( draw_time_classic, translate_marker( "Time" ), 1, 44, true ) );
    ret.emplace_back( window_panel( draw_wind, translate_marker( "Wind" ), 1, 44, false ) );
    ret.emplace_back( window_panel( draw_armor, translate_marker( "Armor" ), 5, 44, false ) );
    ret.emplace_back( window_panel( draw_compass_padding, translate_marker( "Compass" ), 8, 44,
                                    true ) );
    ret.emplace_back( window_panel( draw_messages_classic, translate_marker( "Log" ), -2, 44, true ) );
#if defined(TILES)
    ret.emplace_back( window_panel( draw_mminimap, translate_marker( "Map" ), -1, 44, true,
                                    default_render, true ) );
#endif // TILES
    ret.emplace_back( window_panel( draw_ai_goal, "AI Needs", 1, 44, false ) );
    return ret;
}
References default_render(), draw_ai_goal(), draw_armor(), draw_compass_padding(), draw_health_classic(), draw_lighting_classic(), draw_location_classic(), draw_mana_classic(), draw_messages_classic(), draw_time_classic(), draw_weapon_classic(), draw_weapon_classic_alt(), draw_weather_classic(), draw_weightvolume_classic(), draw_wind(), cata::hash64_detail::ret, spell_panel(), and translate_marker.
Referenced by initialize_default_panel_layouts().
initialize_default_compact_panels()
static std::vector< window_panel > initialize_default_compact_panels () static
Definition at line 2167 of file panels.cpp.
{
    std::vector<window_panel> ret;
    ret.emplace_back( window_panel( draw_limb2, translate_marker( "Limbs" ), 3, 32, true ) );
    ret.emplace_back( window_panel( draw_stealth, translate_marker( "Sound" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_stats, translate_marker( "Stats" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_mana_compact, translate_marker( "Mana" ), 1, 32, true,
                                    spell_panel ) );
    ret.emplace_back( window_panel( draw_time, translate_marker( "Time" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_needs_compact, translate_marker( "Needs" ), 3, 32, true ) );
    ret.emplace_back( window_panel( draw_env_compact, translate_marker( "Env" ), 6, 32, true ) );
    ret.emplace_back( window_panel( draw_veh_compact, translate_marker( "Vehicle" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_weightvolume_compact, translate_marker( "Wgt/Vol" ), 2, 32,
                                    true ) );
    ret.emplace_back( window_panel( draw_armor, translate_marker( "Armor" ), 5, 32, false ) );
    ret.emplace_back( window_panel( draw_messages_classic, translate_marker( "Log" ), -2, 32, true ) );
    ret.emplace_back( window_panel( draw_compass, translate_marker( "Compass" ), 8, 32, true ) );
#if defined(TILES)
    ret.emplace_back( window_panel( draw_mminimap, translate_marker( "Map" ), -1, 32, true,
                                    default_render, true ) );
#endif // TILES
    ret.emplace_back( window_panel( draw_ai_goal, "AI Needs", 1, 32, false ) );
    return ret;
}
References default_render(), draw_ai_goal(), draw_armor(), draw_compass(), draw_env_compact(), draw_limb2(), draw_mana_compact(), draw_messages_classic(), draw_needs_compact(), draw_stats(), draw_stealth(), draw_time(), draw_veh_compact(), draw_weightvolume_compact(), cata::hash64_detail::ret, spell_panel(), and translate_marker.
Referenced by initialize_default_panel_layouts().
initialize_default_label_narrow_panels()
static std::vector< window_panel > initialize_default_label_narrow_panels () static
Definition at line 2194 of file panels.cpp.
{
    std::vector<window_panel> ret;
    ret.emplace_back( window_panel( draw_hint, translate_marker( "Hint" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_limb_narrow, translate_marker( "Limbs" ), 3, 32, true ) );
    ret.emplace_back( window_panel( draw_char_narrow, translate_marker( "Movement" ), 3, 32, true ) );
    ret.emplace_back( window_panel( draw_mana_narrow, translate_marker( "Mana" ), 1, 32, true,
                                    spell_panel ) );
    ret.emplace_back( window_panel( draw_stat_narrow, translate_marker( "Stats" ), 3, 32, true ) );
    ret.emplace_back( window_panel( draw_veh_padding, translate_marker( "Vehicle" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_loc_narrow, translate_marker( "Location" ), 5, 32, true ) );
    ret.emplace_back( window_panel( draw_wind_padding, translate_marker( "Wind" ), 1, 32, false ) );
    ret.emplace_back( window_panel( draw_weapon_labels, translate_marker( "Weapon" ), 2, 32, true ) );
    ret.emplace_back( window_panel( draw_weightvolume_narrow, translate_marker( "Wgt/Vol" ), 2, 32,
                                    true ) );
    ret.emplace_back( window_panel( draw_needs_narrow, translate_marker( "Needs" ), 5, 32, true ) );
    ret.emplace_back( window_panel( draw_sound_narrow, translate_marker( "Sound" ), 1, 32, true ) );
    ret.emplace_back( window_panel( draw_messages, translate_marker( "Log" ), -2, 32, true ) );
    ret.emplace_back( window_panel( draw_moon_narrow, translate_marker( "Moon" ), 2, 32, false ) );
    ret.emplace_back( window_panel( draw_armor_padding, translate_marker( "Armor" ), 5, 32, false ) );
    ret.emplace_back( window_panel( draw_compass_padding, translate_marker( "Compass" ), 8, 32,
                                    true ) );
#if defined(TILES)
    ret.emplace_back( window_panel( draw_mminimap, translate_marker( "Map" ), -1, 32, true,
                                    default_render, true ) );
#endif // TILES
    ret.emplace_back( window_panel( draw_ai_goal, "AI Needs", 1, 32, false ) );
    return ret;
}
References default_render(), draw_ai_goal(), draw_armor_padding(), draw_char_narrow(), draw_compass_padding(), draw_hint(), draw_limb_narrow(), draw_loc_narrow(), draw_mana_narrow(), draw_messages(), draw_moon_narrow(), draw_needs_narrow(), draw_sound_narrow(), draw_stat_narrow(), draw_veh_padding(), draw_weapon_labels(), draw_weightvolume_narrow(), draw_wind_padding(), cata::hash64_detail::ret, spell_panel(), and translate_marker.
Referenced by initialize_default_panel_layouts().
initialize_default_label_panels()
static std::vector< window_panel > initialize_default_label_panels () static
Definition at line 2226 of file panels.cpp.
{
    std::vector<window_panel> ret;
    ret.emplace_back( window_panel( draw_hint, translate_marker( "Hint" ), 1, 44, true ) );
    ret.emplace_back( window_panel( draw_limb_wide, translate_marker( "Limbs" ), 2, 44, true ) );
    ret.emplace_back( window_panel( draw_char_wide, translate_marker( "Movement" ), 2, 44, true ) );
    ret.emplace_back( window_panel( draw_mana_wide, translate_marker( "Mana" ), 1, 44, true,
                                    spell_panel ) );
    ret.emplace_back( window_panel( draw_stat_wide, translate_marker( "Stats" ), 2, 44, true ) );
    ret.emplace_back( window_panel( draw_veh_padding, translate_marker( "Vehicle" ), 1, 44, true ) );
    ret.emplace_back( window_panel( draw_loc_wide_map, translate_marker( "Location" ), 5, 44, true ) );
    ret.emplace_back( window_panel( draw_wind_padding, translate_marker( "Wind" ), 1, 44, false ) );
    ret.emplace_back( window_panel( draw_loc_wide, translate_marker( "Location Alt" ), 5, 44, false ) );
    ret.emplace_back( window_panel( draw_weapon_labels, translate_marker( "Weapon" ), 2, 44, true ) );
    ret.emplace_back( window_panel( draw_weightvolume_labels, translate_marker( "Wgt/Vol" ), 1, 44,
                                    true ) );
    ret.emplace_back( window_panel( draw_needs_labels, translate_marker( "Needs" ), 3, 44, true ) );
    ret.emplace_back( window_panel( draw_sound_labels, translate_marker( "Sound" ), 1, 44, true ) );
    ret.emplace_back( window_panel( draw_messages, translate_marker( "Log" ), -2, 44, true ) );
    ret.emplace_back( window_panel( draw_moon_wide, translate_marker( "Moon" ), 1, 44, false ) );
    ret.emplace_back( window_panel( draw_armor_padding, translate_marker( "Armor" ), 5, 44, false ) );
    ret.emplace_back( window_panel( draw_compass_padding, translate_marker( "Compass" ), 8, 44,
                                    true ) );
#if defined(TILES)
    ret.emplace_back( window_panel( draw_mminimap, translate_marker( "Map" ), -1, 44, true,
                                    default_render, true ) );
#endif // TILES
    ret.emplace_back( window_panel( draw_ai_goal, "AI Needs", 1, 44, false ) );
    return ret;
}
References default_render(), draw_ai_goal(), draw_armor_padding(), draw_char_wide(), draw_compass_padding(), draw_hint(), draw_limb_wide(), draw_loc_wide(), draw_loc_wide_map(), draw_mana_wide(), draw_messages(), draw_moon_wide(), draw_needs_labels(), draw_sound_labels(), draw_stat_wide(), draw_veh_padding(), draw_weapon_labels(), draw_weightvolume_labels(), draw_wind_padding(), cata::hash64_detail::ret, spell_panel(), and translate_marker.
Referenced by initialize_default_panel_layouts().
initialize_default_panel_layouts()
static std::map< std::string, std::vector< window_panel > > initialize_default_panel_layouts () static
Definition at line 2259 of file panels.cpp.
{
    std::map<std::string, std::vector<window_panel>> ret;
    ret.emplace( std::make_pair( translate_marker( "classic" ), initialize_default_classic_panels() ) );
    ret.emplace( std::make_pair( translate_marker( "compact" ), initialize_default_compact_panels() ) );
    ret.emplace( std::make_pair( translate_marker( "labels-narrow" ),
                                 initialize_default_label_narrow_panels() ) );
    ret.emplace( std::make_pair( translate_marker( "labels" ), initialize_default_label_panels() ) );
    return ret;
}
References initialize_default_classic_panels(), initialize_default_compact_panels(), initialize_default_label_narrow_panels(), initialize_default_label_panels(), cata::hash64_detail::ret, and translate_marker.
Referenced by panel_manager::panel_manager().
int_string()
static std::pair< nc_color, std::string > int_string (const avatar & p) static
Definition at line 145 of file panels.cpp.
{
    nc_color clr;
    if( p.get_int() == p.get_int_base() ) {
        clr = c_white;
    } else if( p.get_int() > p.get_int_base() ) {
        clr = c_green;
    } else if( p.get_int() < p.get_int_base() ) {
        clr = c_red;
    }
    return std::make_pair( clr, _( "Int " ) + ( p.get_int() < 100 ? std::to_string(
                               p.get_int() ) : "++" ) );
}
References _, c_green, c_red, c_white, Character::get_int(), avatar::get_int_base(), and to_string().
Referenced by draw_health_classic(), draw_stat_narrow(), draw_stat_wide(), and draw_stats().
mana_stat()
static std::pair< nc_color, std::string > mana_stat (const player & u) static
Definition at line 816 of file panels.cpp.
{
    nc_color c_mana = c_red;
    std::string s_mana;
    if( u.magic->max_mana( u ) <= 0 ) {
        s_mana = "--";
        c_mana = c_light_gray;
    } else {
        if( u.magic->available_mana() >= u.magic->max_mana( u ) / 2 ) {
            c_mana = c_light_blue;
        } else if( u.magic->available_mana() >= u.magic->max_mana( u ) / 3 ) {
            c_mana = c_yellow;
        }
        s_mana = std::to_string( u.magic->available_mana() );
    }
    return std::make_pair( c_mana, s_mana );
}
References c_light_blue, c_light_gray, c_red, c_yellow, Character::magic, and to_string().
Referenced by print_mana().
morale_emotion()
static std::string morale_emotion (const int morale_cur, const face_type face, const bool horizontal_style) static
Definition at line 707 of file panels.cpp.
{
    if( horizontal_style ) {
        if( face == face_bear || face == face_cat ) {
            if( morale_cur >= 200 ) {
                return "@W@";
            } else if( morale_cur >= 100 ) {
                return "OWO";
            } else if( morale_cur >= 50 ) {
                return "owo";
            } else if( morale_cur >= 10 ) {
                return "^w^";
            } else if( morale_cur >= -10 ) {
                return "-w-";
            } else if( morale_cur >= -50 ) {
                return "-m-";
            } else if( morale_cur >= -100 ) {
                return "TmT";
            } else if( morale_cur >= -200 ) {
                return "XmX";
            } else {
                return "@m@";
            }
        } else if( face == face_bird ) {
            if( morale_cur >= 200 ) {
                return "@v@";
            } else if( morale_cur >= 100 ) {
                return "OvO";
            } else if( morale_cur >= 50 ) {
                return "ovo";
            } else if( morale_cur >= 10 ) {
                return "^v^";
            } else if( morale_cur >= -10 ) {
                return "-v-";
            } else if( morale_cur >= -50 ) {
                return ".v.";
            } else if( morale_cur >= -100 ) {
                return "TvT";
            } else if( morale_cur >= -200 ) {
                return "XvX";
            } else {
                return "@v@";
            }
        } else if( morale_cur >= 200 ) {
            return "@U@";
        } else if( morale_cur >= 100 ) {
            return "OuO";
        } else if( morale_cur >= 50 ) {
            return "^u^";
        } else if( morale_cur >= 10 ) {
            return "n_n";
        } else if( morale_cur >= -10 ) {
            return "-_-";
        } else if( morale_cur >= -50 ) {
            return "-n-";
        } else if( morale_cur >= -100 ) {
            return "TnT";
        } else if( morale_cur >= -200 ) {
            return "XnX";
        } else {
            return "@n@";
        }
    } else if( morale_cur >= 100 ) {
        return "8D";
    } else if( morale_cur >= 50 ) {
        return ":D";
    } else if( face == face_cat && morale_cur >= 10 ) {
        return ":3";
    } else if( face != face_cat && morale_cur >= 10 ) {
        return ":)";
    } else if( morale_cur >= -10 ) {
        return ":|";
    } else if( morale_cur >= -50 ) {
        return "):";
    } else if( morale_cur >= -100 ) {
        return "D:";
    } else {
        return "D8";
    }
}
References face_bear, face_bird, and face_cat.
Referenced by draw_char_narrow(), draw_char_wide(), draw_health_classic(), and draw_limb2().
morale_stat()
static std::pair< nc_color, int > morale_stat (const avatar & u) static
Definition at line 536 of file panels.cpp.
{
    const int morale_int = u.get_morale_level();
    nc_color morale_color = c_white;
    if( morale_int >= 10 ) {
        morale_color = c_green;
    } else if( morale_int <= -10 ) {
        morale_color = c_red;
    }
    return std::make_pair( morale_color, morale_int );
}
References c_green, c_red, c_white, and Character::get_morale_level().
Referenced by draw_char_narrow(), draw_char_wide(), draw_health_classic(), and draw_limb2().
move_mode_color()
static nc_color move_mode_color (avatar & u) static
Definition at line 994 of file panels.cpp.
{
    if( u.movement_mode_is( CMM_RUN ) ) {
        return c_red;
    } else if( u.movement_mode_is( CMM_CROUCH ) ) {
        return c_light_blue;
    } else {
        return c_light_gray;
    }
}
References c_light_blue, c_light_gray, c_red, CMM_CROUCH, CMM_RUN, and Character::movement_mode_is().
Referenced by draw_char_narrow(), draw_char_wide(), draw_health_classic(), and draw_stealth().
move_mode_string()
static std::string move_mode_string (avatar & u) static
Definition at line 1005 of file panels.cpp.
{
    if( u.movement_mode_is( CMM_RUN ) ) {
        return pgettext( "movement-type", "R" );
    } else if( u.movement_mode_is( CMM_CROUCH ) ) {
        return pgettext( "movement-type", "C" );
    } else {
        return pgettext( "movement-type", "W" );
    }
}
References CMM_CROUCH, CMM_RUN, Character::movement_mode_is(), and pgettext().
Referenced by draw_char_narrow(), draw_char_wide(), draw_health_classic(), and draw_stealth().
per_string()
static std::pair< nc_color, std::string > per_string (const avatar & p) static
Definition at line 160 of file panels.cpp.
{
    nc_color clr;
    if( p.get_per() == p.get_per_base() ) {
        clr = c_white;
    } else if( p.get_per() > p.get_per_base() ) {
        clr = c_green;
    } else if( p.get_per() < p.get_per_base() ) {
        clr = c_red;
    }
    return std::make_pair( clr, _( "Per " ) + ( p.get_per() < 100 ? std::to_string(
                               p.get_per() ) : "++" ) );
}
References _, c_green, c_red, c_white, Character::get_per(), avatar::get_per_base(), and to_string().
Referenced by draw_health_classic(), draw_stat_narrow(), draw_stat_wide(), and draw_stats().
power_stat()
static std::pair< nc_color, std::string > power_stat (const avatar & u) static
Definition at line 789 of file panels.cpp.
{
    nc_color c_pwr = c_red;
    std::string s_pwr;
    if( !u.has_max_power() ) {
        s_pwr = "--";
        c_pwr = c_light_gray;
    } else {
        if( u.get_power_level() >= u.get_max_power_level() / 2 ) {
            c_pwr = c_light_blue;
        } else if( u.get_power_level() >= u.get_max_power_level() / 3 ) {
            c_pwr = c_yellow;
        } else if( u.get_power_level() >= u.get_max_power_level() / 4 ) {
            c_pwr = c_red;
        }
        if( u.get_power_level() < 1_kJ ) {
            s_pwr = std::to_string( units::to_joule( u.get_power_level() ) ) +
                    pgettext( "energy unit: joule", "J" );
        } else {
            s_pwr = std::to_string( units::to_kilojoule( u.get_power_level() ) ) +
                    pgettext( "energy unit: kilojoule", "kJ" );
        }
    }
    return std::make_pair( c_pwr, s_pwr );
}
References c_light_blue, c_light_gray, c_red, c_yellow, Character::get_max_power_level(), Character::get_power_level(), Character::has_max_power(), pgettext(), units::to_joule(), units::to_kilojoule(), and to_string().
Referenced by draw_health_classic(), draw_limb2(), draw_stat_narrow(), and draw_stat_wide().
print_mana()
static void print_mana (const player & u, const catacurses::window & w, const std::string & fmt_string, const int j1, const int j2, const int j3, const int j4) static
Definition at line 2082 of file panels.cpp.
{
    werase( w );
    auto mana_pair = mana_stat( u );
    const std::string mana_string = string_format( fmt_string,
                                    //~ translation should not exceed 4 console cells
                                    utf8_justify( _( "Mana" ), j1 ),
                                    colorize( utf8_justify( mana_pair.second, j2 ), mana_pair.first ),
                                    //~ translation should not exceed 9 console cells
                                    utf8_justify( _( "Max Mana" ), j3 ),
                                    colorize( utf8_justify( std::to_string( u.magic->max_mana( u ) ), j4 ), c_light_blue ) );
    nc_color gray = c_light_gray;
    print_colored_text( w, point_zero, gray, gray, mana_string );
    wnoutrefresh( w );
}
References _, c_light_blue, c_light_gray, colorize(), Character::magic, mana_stat(), point_zero, print_colored_text(), string_format(), to_string(), utf8_justify(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_mana_classic(), draw_mana_compact(), draw_mana_narrow(), and draw_mana_wide().
render_wind()
static void render_wind (avatar & u, const catacurses::window & w, const std::string & formatstr) static
Definition at line 1630 of file panels.cpp.
{
    werase( w );
    mvwprintz( w, point_zero, c_light_gray,
               //~ translation should not exceed 5 console cells
               string_format( formatstr, left_justify( _( "Wind" ), 5 ) ) );
    const oter_id &cur_om_ter = overmap_buffer.ter( u.global_omt_location() );
    const weather_manager &weather = get_weather();
    double windpower = get_local_windpower( weather.windspeed, cur_om_ter,
                                            u.pos(), weather.winddirection, g->is_sheltered( u.pos() ) );
    mvwprintz( w, point( 8, 0 ), get_wind_color( windpower ),
               get_wind_desc( windpower ) + " " + get_wind_arrow( weather.winddirection ) );
    wnoutrefresh( w );
}
References _, c_light_gray, g, get_local_windpower(), get_weather(), get_wind_arrow(), get_wind_color(), get_wind_desc(), Character::global_omt_location(), left_justify(), mvwprintz(), overmap_buffer, point_zero, Character::pos(), string_format(), overmapbuffer::ter(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_wind(), and draw_wind_padding().
safe_color()
static nc_color safe_color () static
Definition at line 834 of file panels.cpp.
{
    nc_color s_color = g->safe_mode ? c_green : c_red;
    if( g->safe_mode == SAFE_MODE_OFF && get_option<bool>( "AUTOSAFEMODE" ) ) {
        int s_return = get_option<int>( "AUTOSAFEMODETURNS" );
        int iPercent = g->turnssincelastmon * 100 / s_return;
        if( iPercent >= 100 ) {
            s_color = c_green;
        } else if( iPercent >= 75 ) {
            s_color = c_yellow;
        } else if( iPercent >= 50 ) {
            s_color = c_light_red;
        } else if( iPercent >= 25 ) {
            s_color = c_red;
        }
    }
    return s_color;
}
References c_green, c_light_red, c_red, c_yellow, g, and SAFE_MODE_OFF.
Referenced by draw_health_classic(), draw_limb2(), draw_stat_narrow(), and draw_stat_wide().
spell_panel()
static bool spell_panel () static
Definition at line 2125 of file panels.cpp.
{
    return get_avatar().magic->knows_spell();
}
References get_avatar(), and Character::magic.
Referenced by initialize_default_classic_panels(), initialize_default_compact_panels(), initialize_default_label_narrow_panels(), and initialize_default_label_panels().
str_string()
static std::pair< nc_color, std::string > str_string (const avatar & p) static
Definition at line 115 of file panels.cpp.
{
    nc_color clr;
    if( p.get_str() == p.get_str_base() ) {
        clr = c_white;
    } else if( p.get_str() > p.get_str_base() ) {
        clr = c_green;
    } else if( p.get_str() < p.get_str_base() ) {
        clr = c_red;
    }
    return std::make_pair( clr, _( "Str " ) + ( p.get_str() < 100 ? std::to_string(
                               p.get_str() ) : "++" ) );
}
References _, c_green, c_red, c_white, Character::get_str(), avatar::get_str_base(), and to_string().
Referenced by veh_interact::can_remove_part(), draw_health_classic(), draw_stat_narrow(), draw_stat_wide(), draw_stats(), and veh_interact::update_part_requirements().
temp_delta()
static std::pair< int, int > temp_delta (const avatar & u) static
Definition at line 548 of file panels.cpp.
{
    int current_bp_extreme = 0;
    int conv_bp_extreme = 0;
    for( int i = 0; i < num_bp; i++ ) {
        if( std::abs( u.temp_cur[i] - BODYTEMP_NORM ) >
            std::abs( u.temp_cur[current_bp_extreme] - BODYTEMP_NORM ) ) {
            current_bp_extreme = i;
        }
        if( std::abs( u.temp_conv[i] - BODYTEMP_NORM ) >
            std::abs( u.temp_conv[conv_bp_extreme] - BODYTEMP_NORM ) ) {
            conv_bp_extreme = i;
        }
    }
    return std::make_pair( current_bp_extreme, conv_bp_extreme );
}
References BODYTEMP_NORM, num_bp, Character::temp_conv, and Character::temp_cur.
Referenced by temp_delta_arrows(), temp_delta_string(), and temp_stat().
temp_delta_arrows()
static std::pair< nc_color, std::string > temp_delta_arrows (const avatar & u) static
Definition at line 612 of file panels.cpp.
{
    std::string temp_message;
    nc_color temp_color = c_white;
    std::pair<int, int> temp_pair = temp_delta( u );
    // Assign zones for comparisons
    const int cur_zone = define_temp_level( u.temp_cur[temp_pair.first] );
    const int conv_zone = define_temp_level( u.temp_conv[temp_pair.second] );
    // delta will be positive if temp_cur is rising
    const int delta = conv_zone - cur_zone;
    // Decide if temp_cur is rising or falling
    if( delta > 2 ) {
        temp_message = " ";
        temp_color = c_red;
    } else if( delta == 2 ) {
        temp_message = " ";
        temp_color = c_light_red;
    } else if( delta == 1 ) {
        temp_message = " ";
        temp_color = c_yellow;
    } else if( delta == 0 ) {
        temp_message = "-";
        temp_color = c_green;
    } else if( delta == -1 ) {
        temp_message = " ";
        temp_color = c_light_blue;
    } else if( delta == -2 ) {
        temp_message = " ";
        temp_color = c_cyan;
    } else {
        temp_message = " ";
        temp_color = c_blue;
    }
    return std::make_pair( temp_color, temp_message );
}
References c_blue, c_cyan, c_green, c_light_blue, c_light_red, c_red, c_white, c_yellow, define_temp_level(), Character::temp_conv, Character::temp_cur, and temp_delta().
Referenced by draw_needs_compact().
temp_delta_string()
static std::string temp_delta_string (const avatar & u) static
Definition at line 583 of file panels.cpp.
{
    std::string temp_message;
    std::pair<int, int> temp_pair = temp_delta( u );
    // Assign zones for comparisons
    const int cur_zone = define_temp_level( u.temp_cur[temp_pair.first] );
    const int conv_zone = define_temp_level( u.temp_conv[temp_pair.second] );
    // delta will be positive if temp_cur is rising
    const int delta = conv_zone - cur_zone;
    // Decide if temp_cur is rising or falling
    if( delta > 2 ) {
        temp_message = _( " (Rising!!)" );
    } else if( delta == 2 ) {
        temp_message = _( " (Rising!)" );
    } else if( delta == 1 ) {
        temp_message = _( " (Rising)" );
    } else if( delta == 0 ) {
        temp_message.clear();
    } else if( delta == -1 ) {
        temp_message = _( " (Falling)" );
    } else if( delta == -2 ) {
        temp_message = _( " (Falling!)" );
    } else {
        temp_message = _( " (Falling!!)" );
    }
    return temp_message;
}
References _, define_temp_level(), Character::temp_conv, Character::temp_cur, and temp_delta().
Referenced by draw_health_classic().
temp_stat()
static std::pair< nc_color, std::string > temp_stat (const avatar & u) static
Find hottest/coldest bodypart
Definition at line 649 of file panels.cpp.
{
    /// Find hottest/coldest bodypart
    // Calculate the most extreme body temperatures
    int current_bp_extreme = temp_delta( u ).first;
    // printCur the hottest/coldest bodypart
    std::string temp_string;
    nc_color temp_color = c_yellow;
    if( u.temp_cur[current_bp_extreme] > BODYTEMP_SCORCHING ) {
        temp_color = c_red;
        temp_string = _( "Scorching!" );
    } else if( u.temp_cur[current_bp_extreme] > BODYTEMP_VERY_HOT ) {
        temp_color = c_light_red;
        temp_string = _( "Very hot!" );
    } else if( u.temp_cur[current_bp_extreme] > BODYTEMP_HOT ) {
        temp_color = c_yellow;
        temp_string = _( "Warm" );
    } else if( u.temp_cur[current_bp_extreme] > BODYTEMP_COLD ) {
        temp_color = c_green;
        temp_string = _( "Comfortable" );
    } else if( u.temp_cur[current_bp_extreme] > BODYTEMP_VERY_COLD ) {
        temp_color = c_light_blue;
        temp_string = _( "Chilly" );
    } else if( u.temp_cur[current_bp_extreme] > BODYTEMP_FREEZING ) {
        temp_color = c_cyan;
        temp_string = _( "Very cold!" );
    } else if( u.temp_cur[current_bp_extreme] <= BODYTEMP_FREEZING ) {
        temp_color = c_blue;
        temp_string = _( "Freezing!" );
    }
    return std::make_pair( temp_color, temp_string );
}
References _, BODYTEMP_COLD, BODYTEMP_FREEZING, BODYTEMP_HOT, BODYTEMP_SCORCHING, BODYTEMP_VERY_COLD, BODYTEMP_VERY_HOT, c_blue, c_cyan, c_green, c_light_blue, c_light_red, c_red, c_yellow, Character::temp_cur, and temp_delta().
Referenced by draw_health_classic(), draw_needs_compact(), draw_needs_labels(), and draw_needs_narrow().
time_approx()
static std::string time_approx () static
Definition at line 495 of file panels.cpp.
{
    const int iHour = hour_of_day<int>( calendar::turn );
    if( iHour >= 23 || iHour <= 1 ) {
        return _( "Around midnight" );
    } else if( iHour <= 4 ) {
        return _( "Dead of night" );
    } else if( iHour <= 6 ) {
        return _( "Around dawn" );
    } else if( iHour <= 8 ) {
        return _( "Early morning" );
    } else if( iHour <= 10 ) {
        return _( "Morning" );
    } else if( iHour <= 13 ) {
        return _( "Around noon" );
    } else if( iHour <= 16 ) {
        return _( "Afternoon" );
    } else if( iHour <= 18 ) {
        return _( "Early evening" );
    } else if( iHour <= 20 ) {
        return _( "Around dusk" );
    }
    return _( "Night" );
}
References _, and calendar::turn.
Referenced by draw_loc_labels().
trunc_ellipse()
static std::string trunc_ellipse (const std::string & input, unsigned int trunc) static
Definition at line 87 of file panels.cpp.
{
    if( utf8_width( input ) > static_cast<int>( trunc ) ) {
        return utf8_truncate( input, trunc - 1 ) + "";
    }
    return input;
}
References utf8_truncate(), and utf8_width().
Referenced by panel_manager::show_adm().
value_color()
static nc_color value_color (int stat) static
Definition at line 520 of file panels.cpp.
{
    nc_color valuecolor = c_light_gray;
    if( stat >= 75 ) {
        valuecolor = c_green;
    } else if( stat >= 50 ) {
        valuecolor = c_yellow;
    } else if( stat >= 25 ) {
        valuecolor = c_red;
    } else {
        valuecolor = c_magenta;
    }
    return valuecolor;
}
References c_green, c_light_gray, c_magenta, c_red, and c_yellow.
Referenced by draw_stealth().
Variable Documentation
effect_got_checked
const efftype_id effect_got_checked("got_checked") ("got_checked") static
Referenced by draw_limb_health().
trait_SELFAWARE
const trait_id trait_SELFAWARE("SELFAWARE") ("SELFAWARE") static
Referenced by draw_limb_health().
trait_THRESH_BIRD
const trait_id trait_THRESH_BIRD("THRESH_BIRD") ("THRESH_BIRD") static
Referenced by get_face_type().
trait_THRESH_FELINE
const trait_id trait_THRESH_FELINE("THRESH_FELINE") ("THRESH_FELINE") static
Referenced by get_face_type().
trait_THRESH_URSINE
const trait_id trait_THRESH_URSINE("THRESH_URSINE") ("THRESH_URSINE") static
Referenced by get_face_type().