Cataclysm BN: src/panels_utility.h File Reference
panels_utility.h File Reference
#include <string>
#include "color.h"
Macros
#define CATA_SRC_PANELS_UTILITY_H
Functions
std::string trunc_ellipse (const std::string &input, unsigned int trunc)
nc_color color_compare_base (int base, int value)
std::string value_trimmed (int value, int maximum=100)
nc_color focus_color (int focus)
Macro Definition Documentation
CATA_SRC_PANELS_UTILITY_H
#define CATA_SRC_PANELS_UTILITY_H
Definition at line 3 of file panels_utility.h.
Function Documentation
color_compare_base()
nc_color color_compare_base (int base, int value)
Definition at line 14 of file panels_utility.cpp.
{
    if( base < value ) {
        return c_green;
    } else if( value < base ) {
        return c_red;
    } else {
        return c_white;
    }
}
References c_green, c_red, and c_white.
Referenced by dex_string(), int_string(), per_string(), and str_string().
focus_color()
nc_color focus_color (int focus)
Definition at line 34 of file panels_utility.cpp.
{
    if( focus < 25 ) {
        return c_red;
    } else if( focus < 50 ) {
        return c_light_red;
    } else if( focus < 75 ) {
        return c_yellow;
    } else if( focus < 100 ) {
        return c_light_gray;
    } else if( focus < 125 ) {
        return c_white;
    } else {
        return c_green;
    }
}
References c_green, c_light_gray, c_light_red, c_red, c_white, and c_yellow.
Referenced by draw_char_narrow(), draw_char_wide(), and draw_needs_compact().
trunc_ellipse()
std::string trunc_ellipse (const std::string & input, unsigned int trunc)
Definition at line 6 of file panels_utility.cpp.
{
    if( utf8_width( input ) > static_cast<int>( trunc ) ) {
        return utf8_truncate( input, trunc - 1 ) + "…";
    }
    return input;
}
References utf8_truncate(), and utf8_width().
Referenced by panel_manager::show_adm().
value_trimmed()
std::string value_trimmed (int value, int maximum = 100)
Definition at line 25 of file panels_utility.cpp.
{
    if( value > maximum ) {
        return "++";
    } else {
        return std::to_string( value );
    }
}
References to_string().
Referenced by dex_string(), int_string(), per_string(), and str_string().