Cataclysm BN: src/pathfinding.cpp File Reference
pathfinding.cpp File Reference
#include "pathfinding.h"
#include <cstdlib>
#include <algorithm>
#include <queue>
#include <set>
#include <array>
#include <memory>
#include <utility>
#include <vector>
#include "cata_utility.h"
#include "coordinates.h"
#include "debug.h"
#include "map.h"
#include "mapdata.h"
#include "optional.h"
#include "submap.h"
#include "trap.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "line.h"
#include "type_id.h"
#include "point.h"
Classes
struct path_data_layer
struct pathfinder
Enumerations
enum astar_state { ASL_NONE , ASL_OPEN , ASL_CLOSED }
Functions
constexpr int flat_index (const tripoint &p)
template<ter_bitflags flag>
bool vertical_move_destination (const map &m, tripoint &t)
template<class Set1 , class Set2 >
bool is_disjoint (const Set1 &set1, const Set2 &set2)
Enumeration Type Documentation
astar_state
enum astar_state
Enumerator
ASL_NONE
ASL_OPEN
ASL_CLOSED
Definition at line 27 of file pathfinding.cpp.
                 {
    ASL_NONE,
    ASL_OPEN,
    ASL_CLOSED
};
Function Documentation
flat_index()
constexpr int flat_index (const tripoint & p) constexpr
Definition at line 34 of file pathfinding.cpp.
{
    return ( p.x * MAPSIZE_Y ) + p.y;
}
References MAPSIZE_Y, tripoint::x, and tripoint::y.
Referenced by pathfinder::add_point(), pathfinder::close_point(), path_data_layer::init(), map::route(), and pathfinder::unclose_point().
is_disjoint()
template<class Set1 , class Set2 > bool is_disjoint (const Set1 & set1, const Set2 & set2)
Definition at line 164 of file pathfinding.cpp.
{
    if( set1.empty() || set2.empty() ) {
        return true;
    }
    typename Set1::const_iterator it1 = set1.begin();
    typename Set1::const_iterator it1_end = set1.end();
    typename Set2::const_iterator it2 = set2.begin();
    typename Set2::const_iterator it2_end = set2.end();
    if( *set2.rbegin() < *it1 || *set1.rbegin() < *it2 ) {
        return true;
    }
    while( it1 != it1_end && it2 != it2_end ) {
        if( *it1 == *it2 ) {
            return false;
        }
        if( *it1 < *it2 ) {
            it1++;
        } else {
            it2++;
        }
    }
    return true;
}
Referenced by map::route().
vertical_move_destination()
template<ter_bitflags flag> bool vertical_move_destination (const map & m, tripoint & t)
Definition at line 121 of file pathfinding.cpp.
{
    if( !m.has_zlevels() ) {
        return false;
    }
    real_coords rc( m.getabs( t.xy() ) );
    // Align to OMT boundaries
    point start = m.getlocal( rc.begin_om_pos() );
    point end = start + point( SEEX * 2, SEEY * 2 );
    // Exclude submaps not loaded into bubble
    if( start.x < 0 ) {
        start.x = 0;
    }
    if( start.y < 0 ) {
        start.y = 0;
    }
    if( end.x >= MAPSIZE_X ) {
        end.x = MAPSIZE_X - 1;
    }
    if( end.y >= MAPSIZE_Y ) {
        end.y = MAPSIZE_Y - 1;
    }
    const auto &pf_cache = m.get_pathfinding_cache_ref( t.z );
    for( int x = start.x; x < end.x; x++ ) {
        for( int y = start.y; y < end.y; y++ ) {
            if( pf_cache.special[x][y] & PF_UPDOWN ) {
                const tripoint p( x, y, t.z );
                if( m.has_flag( flag, p ) ) {
                    t = p;
                    return true;
                }
            }
        }
    }
    return false;
}
References real_coords::begin_om_pos(), map::get_pathfinding_cache_ref(), map::getabs(), map::getlocal(), map::has_flag(), map::has_zlevels(), MAPSIZE_X, MAPSIZE_Y, PF_UPDOWN, SEEX, SEEY, point::x, tripoint::xy(), point::y, and tripoint::z.