Cataclysm BN: src/pickup.cpp File Reference
pickup.cpp File Reference
#include "pickup.h"
#include <algorithm>
#include <cstddef>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor.h"
#include "activity_actor_definitions.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "colony.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "drop_token.h"
#include "enums.h"
#include "game.h"
#include "input.h"
#include "int_id.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_search.h"
#include "item_stack.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_selector.h"
#include "mapdata.h"
#include "messages.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "panels.h"
#include "pickup_token.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "popup.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
Classes
struct pickup_count
struct pickup::parent_child_check_t
struct pickup::unstacked_items
Namespaces
namespace pickup
Typedefs
using item_count = std::pair< item, int >
using pickup_map = std::map< std::string, item_count >
Enumerations
enum pickup_answer : int {
CANCEL = -1 , WIELD , WEAR , SPILL ,
EMPTY , STASH , NUM_ANSWERS
}
Functions
static void show_pickup_message (const pickup_map &mapPickup)
static bool select_autopickup_items (const std::vector< std::list< item_stack::iterator > > &here, std::vector< pickup_count > &getitem)
static pickup_answer handle_problematic_pickup (const item &it, bool &offered_swap, bool has_children, const std::string &explain)
static bool pick_one_up (pickup::pick_drop_selection &selection, bool &got_water, bool &offered_swap, pickup_map &map_pickup, bool autopickup)
bool pickup::do_pickup (std::vector< pick_drop_selection > &targets, bool autopickup)
Returns false if the player was presented a prompt and decided to cancel the pickup.
static std::vector< cata::optional< size_t > > pickup::calculate_parents (const std::vector< std::list< item_stack::iterator > > &stacked_here)
std::vector< stacked_items > pickup::stack_for_pickup_ui (const std::vector< item_stack::iterator > &unstacked)
std::vector< std::list< item_stack::iterator > > pickup::flatten (const std::vector< stacked_items > &stacked)
std::vector< pick_drop_selection > pickup::optimize_pickup (const std::vector< item_location > &targets, const std::vector< int > &quantities)
Finds possible parent-child relations in picked up items to save moves.
Typedef Documentation
item_count
using item_count = std::pair<item, int>
Definition at line 63 of file pickup.cpp.
pickup_map
using pickup_map = std::map<std::string, item_count>
Definition at line 64 of file pickup.cpp.
Enumeration Type Documentation
pickup_answer
enum pickup_answer : int
Enumerator
CANCEL
WIELD
WEAR
SPILL
EMPTY
STASH
NUM_ANSWERS
Definition at line 130 of file pickup.cpp.
                   : int {
    CANCEL = -1,
    WIELD,
    WEAR,
    SPILL,
    EMPTY,
    STASH,
    NUM_ANSWERS
};
Function Documentation
handle_problematic_pickup()
static pickup_answer handle_problematic_pickup (const item & it, bool & offered_swap, bool has_children, const std::string & explain) static
Definition at line 140 of file pickup.cpp.
{
    if( offered_swap ) {
        return CANCEL;
    }
    player &u = g->u;
    uilist amenu;
    amenu.text = explain;
    offered_swap = true;
    // TODO: Gray out if not enough hands
    if( u.is_armed() ) {
        amenu.addentry( WIELD, !u.weapon.has_flag( "NO_UNWIELD" ), 'w',
                        _( "Dispose of %s and wield %s" ), u.weapon.display_name(),
                        it.display_name() );
    } else {
        amenu.addentry( WIELD, true, 'w', _( "Wield %s" ), it.display_name() );
    }
    if( it.is_armor() ) {
        amenu.addentry( WEAR, u.can_wear( it ).success(), 'W', _( "Wear %s" ), it.display_name() );
    }
    if( has_children ) {
        // TODO: Fix problematic pickup due to child weight when parent alone is also too heavy
        // Maybe-TODO: A short summary of contained items
        amenu.addentry( EMPTY, u.can_pick_volume( it ), 'e', _( "Pick up just %s, without contents" ),
                        it.display_name() );
    }
    if( it.is_bucket_nonempty() ) {
        amenu.addentry( SPILL, u.can_pick_volume( it ), 's', _( "Spill %s, then pick up %s" ),
                        it.contents.front().tname(), it.display_name() );
    }
    amenu.query();
    int choice = amenu.ret;
    if( choice <= CANCEL || choice >= NUM_ANSWERS ) {
        return CANCEL;
    }
    return static_cast<pickup_answer>( choice );
}
References _, uilist::addentry(), Character::can_pick_volume(), Character::can_wear(), CANCEL, item::contents, item::display_name(), EMPTY, item_contents::front(), g, item::has_flag(), Character::is_armed(), item::is_armor(), item::is_bucket_nonempty(), NUM_ANSWERS, uilist::query(), uilist::ret, SPILL, uilist::text, item::tname(), Character::weapon, WEAR, and WIELD.
Referenced by pick_one_up().
pick_one_up()
static bool pick_one_up (pickup::pick_drop_selection & selection, bool & got_water, bool & offered_swap, pickup_map & map_pickup, bool autopickup) static
Definition at line 229 of file pickup.cpp.
{
    player &u = get_avatar();
    int moves_taken = 100;
    bool picked_up = false;
    pickup_answer option = CANCEL;
    item_location &loc = selection.target;
    // We already checked in do_pickup if this was a nullptr
    // Make copies so the original remains untouched if we bail out
    item_location newloc = loc;
    //original item reference
    item &it = *newloc.get_item();
    //new item (copy)
    item newit = it;
    item leftovers = newit;
    const cata::optional<int> &quantity = selection.quantity;
    std::vector<item_location> &children = selection.children;
    if( !newit.is_owned_by( g->u, true ) ) {
        // Has the player given input on if stealing is ok?
        if( u.get_value( "THIEF_MODE" ) == "THIEF_ASK" ) {
            pickup::query_thief();
        }
        if( u.get_value( "THIEF_MODE" ) == "THIEF_HONEST" ) {
            return true; // Since we are honest, return no problem before picking up
        }
    }
    if( newit.invlet != '\0' &&
        u.invlet_to_item( newit.invlet ) != nullptr ) {
        // Existing invlet is not re-usable, remove it and let the code in player.cpp/inventory.cpp
        // add a new invlet, otherwise keep the (usable) invlet.
        newit.invlet = '\0';
    }
    // Handle charges, quantity == 0 means move all
    if( quantity && newit.count_by_charges() ) {
        leftovers.charges = newit.charges - *quantity;
        if( leftovers.charges > 0 ) {
            newit.charges = *quantity;
        }
    } else {
        leftovers.charges = 0;
    }
    const auto wield_check = u.can_wield( newit );
    bool did_prompt = false;
    newit.charges = u.i_add_to_container( newit, false );
    units::volume children_volume = std::accumulate( children.begin(), children.end(), 0_ml,
    []( units::volume acc, const item_location & c ) {
        return acc + c->volume();
    } );
    units::mass children_weight = std::accumulate( children.begin(), children.end(), 0_gram,
    []( units::mass acc, const item_location & c ) {
        return acc + c->weight();
    } );
    if( newit.is_ammo() && newit.charges == 0 ) {
        picked_up = true;
        option = NUM_ANSWERS; //Skip the options part
    } else if( newit.made_of( LIQUID ) ) {
        got_water = true;
    } else if( !u.can_pick_weight( newit.weight() + children_weight, false ) ) {
        if( !autopickup ) {
            const std::string &explain = string_format( _( "The %s is too heavy!" ),
                                         newit.display_name() );
            option = handle_problematic_pickup( newit, offered_swap, !children.empty(), explain );
            did_prompt = true;
        } else {
            option = CANCEL;
        }
    } else if( newit.is_bucket() && !newit.is_container_empty() ) {
        if( !autopickup ) {
            const std::string &explain = string_format( _( "Can't stash %s while it's not empty" ),
                                         newit.display_name() );
            option = handle_problematic_pickup( newit, offered_swap, !children.empty(), explain );
            did_prompt = true;
        } else {
            option = CANCEL;
        }
    } else if( !u.can_pick_volume( newit.volume() + children_volume ) ) {
        if( !autopickup ) {
            const std::string &explain = string_format( _( "Not enough capacity to stash %s" ),
                                         newit.display_name() );
            option = handle_problematic_pickup( newit, offered_swap, !children.empty(), explain );
            did_prompt = true;
        } else {
            option = CANCEL;
        }
    } else {
        option = STASH;
    }
    switch( option ) {
        case NUM_ANSWERS:
            // Some other option
            break;
        case CANCEL:
            picked_up = false;
            break;
        case WEAR:
            picked_up = !!u.wear_item( newit );
            break;
        case WIELD:
            if( wield_check.success() ) {
                //using original item, possibly modifying it
                picked_up = u.wield( it );
                if( picked_up ) {
                    u.weapon.charges = newit.charges;
                }
                if( u.weapon.invlet ) {
                    add_msg( m_info, _( "Wielding %c - %s" ), u.weapon.invlet,
                             u.weapon.display_name() );
                } else {
                    add_msg( m_info, _( "Wielding - %s" ), u.weapon.display_name() );
                }
            } else {
                add_msg( m_neutral, "%s", wield_check.c_str() );
            }
            break;
        case SPILL:
            if( newit.is_container_empty() ) {
                debugmsg( "Tried to spill contents from an empty container" );
                break;
            }
            //using original item, possibly modifying it
            picked_up = it.spill_contents( u );
            if( !picked_up ) {
                break;
            }
        // Intentional fallthrough
        case EMPTY:
        // Handled later
        case STASH:
            auto &entry = map_pickup[newit.tname()];
            entry.second += newit.count();
            entry.first = u.i_add( newit );
            picked_up = true;
            break;
    }
    if( picked_up ) {
        // Children have to be picked up first, since removing parent would re-index the stack
        if( option != EMPTY ) {
            for( item_location &child_loc : children ) {
                item &added = u.i_add( *child_loc );
                auto &pickup_entry = map_pickup[added.tname()];
                pickup_entry.first = added;
                pickup_entry.second += added.count();
                child_loc.remove_item();
            }
        }
        // If we picked up a whole stack, remove the original item
        // Otherwise, replace the item with the leftovers
        if( leftovers.charges > 0 ) {
            *loc.get_item() = std::move( leftovers );
        } else {
            loc.remove_item();
        }
        u.moves -= moves_taken;
    }
    return picked_up || !did_prompt;
}
References _, add_msg(), PATH_INFO::autopickup(), c, Character::can_pick_volume(), Character::can_pick_weight(), player::can_wield(), CANCEL, item::charges, pickup::pick_drop_selection::children, item::count(), item::count_by_charges(), debugmsg, item::display_name(), EMPTY, g, get_avatar(), item_location::get_item(), Creature::get_value(), handle_problematic_pickup(), Character::i_add(), Character::i_add_to_container(), item::invlet, Character::invlet_to_item(), item::is_ammo(), item::is_bucket(), item::is_container_empty(), item::is_owned_by(), LIQUID, m_info, m_neutral, item::made_of(), avatar_action::move(), Creature::moves, NUM_ANSWERS, pickup::pick_drop_selection::quantity, pickup::query_thief(), item_location::remove_item(), SPILL, item::spill_contents(), STASH, string_format(), pickup::pick_drop_selection::target, item::tname(), item::volume(), Character::weapon, WEAR, Character::wear_item(), item::weight(), Character::wield(), and WIELD.
Referenced by pickup::do_pickup().
select_autopickup_items()
static bool select_autopickup_items (const std::vector< std::list< item_stack::iterator > > & here, std::vector< pickup_count > & getitem) static
Definition at line 77 of file pickup.cpp.
{
    bool found_something = false;
    //Loop through Items lowest Volume first
    bool do_pickup = false;
    for( size_t rounded_volume = 0, num_checked = 0; num_checked < here.size(); rounded_volume++ ) {
        for( size_t i = 0; i < here.size(); i++ ) {
            do_pickup = false;
            item_stack::const_iterator begin_iterator = here[i].front();
            if( begin_iterator->volume() / units::legacy_volume_factor == static_cast<int>( rounded_volume ) ) {
                num_checked++;
                const std::string item_name = begin_iterator->tname( 1, false );
                //Check the Pickup Rules
                if( get_auto_pickup().check_item( item_name ) == RULE_WHITELISTED ) {
                    do_pickup = true;
                } else if( get_auto_pickup().check_item( item_name ) != RULE_BLACKLISTED ) {
                    //No prematched pickup rule found
                    //check rules in more detail
                    get_auto_pickup().create_rule( &*begin_iterator );
                    if( get_auto_pickup().check_item( item_name ) == RULE_WHITELISTED ) {
                        do_pickup = true;
                    }
                }
                //Auto Pickup all items with Volume <= AUTO_PICKUP_VOL_LIMIT * 50 and Weight <= AUTO_PICKUP_ZERO * 50
                //items will either be in the autopickup list ("true") or unmatched ("")
                if( !do_pickup ) {
                    int weight_limit = get_option<int>( "AUTO_PICKUP_WEIGHT_LIMIT" );
                    int volume_limit = get_option<int>( "AUTO_PICKUP_VOL_LIMIT" );
                    if( weight_limit && volume_limit ) {
                        if( begin_iterator->volume() <= units::from_milliliter( volume_limit * 50 ) &&
                            begin_iterator->weight() <= weight_limit * 50_gram &&
                            get_auto_pickup().check_item( item_name ) != RULE_BLACKLISTED ) {
                            do_pickup = true;
                        }
                    }
                }
            }
            if( do_pickup ) {
                getitem[i].pick = true;
                found_something = true;
            }
        }
    }
    return found_something;
}
References auto_pickup::player_settings::create_rule(), pickup::do_pickup(), units::from_milliliter(), get_auto_pickup(), units::legacy_volume_factor, RULE_BLACKLISTED, and RULE_WHITELISTED.
Referenced by pickup::pick_up().
show_pickup_message()
void show_pickup_message (const pickup_map & mapPickup) static
Definition at line 1225 of file pickup.cpp.
{
    for( auto &entry : mapPickup ) {
        if( entry.second.first.invlet != 0 ) {
            add_msg( _( "You pick up: %d %s [%c]" ), entry.second.second,
                     entry.second.first.display_name( entry.second.second ), entry.second.first.invlet );
        } else {
            add_msg( _( "You pick up: %d %s" ), entry.second.second,
                     entry.second.first.display_name( entry.second.second ) );
        }
    }
}
References _, and add_msg().
Referenced by pickup::do_pickup().