Cataclysm BN: src/player_hardcoded_effects.cpp File Reference
player_hardcoded_effects.cpp File Reference
#include "player.h"
#include <array>
#include <cstdlib>
#include <memory>
#include "activity_handlers.h"
#include "avatar.h"
#include "character.h"
#include "character_effects.h"
#include "character_functions.h"
#include "damage.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "field_type.h"
#include "game.h"
#include "int_id.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "martialarts.h"
#include "messages.h"
#include "morale_types.h"
#include "mongroup.h"
#include "monster.h"
#include "mutation_data.h"
#include "player_activity.h"
#include "pldata.h"
#include "rng.h"
#include "sdl_wrappers.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "teleport.h"
#include "text_snippets.h"
#include "translations.h"
#include "weather.h"
#include "vitamin.h"
#include <algorithm>
#include <functional>
Classes
struct temperature_effect
Functions
static void eff_fun_onfire (player &u, effect &it)
static void eff_fun_spores (player &u, effect &it)
static void eff_fun_fungus (player &u, effect &it)
static void eff_fun_rat (player &u, effect &it)
static void eff_fun_bleed (player &u, effect &it)
static void eff_fun_hallu (player &u, effect &it)
static void eff_fun_cold (player &u, effect &it)
static void eff_fun_hot (player &u, effect &it)
static void eff_fun_frostbite (player &u, effect &it)
static void eff_fun_bloated (player &u, effect &it)
static void eff_fun_toxin_buildup (player &u, effect &it)
static void eff_fun_mutating (player &u, effect &it)
Variables
static const activity_id ACT_FIRSTAID ("ACT_FIRSTAID")
static const efftype_id effect_accumulated_mutagen ("accumulated_mutagen")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_alarm_clock ("alarm_clock")
static const efftype_id effect_antibiotic ("antibiotic")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_attention ("attention")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bloated ("bloated")
static const efftype_id effect_bloodworms ("bloodworms")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_brainworms ("brainworms")
static const efftype_id effect_cold ("cold")
static const efftype_id effect_datura ("datura")
static const efftype_id effect_dazed ("dazed")
static const efftype_id effect_dermatik ("dermatik")
static const efftype_id effect_disabled ("disabled")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_evil ("evil")
static const efftype_id effect_fearparalyze ("fearparalyze")
static const efftype_id effect_formication ("formication")
static const efftype_id effect_frostbite ("frostbite")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_grabbing ("grabbing")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_hot ("hot")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_mutating ("mutating")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_paincysts ("paincysts")
static const efftype_id effect_panacea ("panacea")
static const efftype_id effect_rat ("rat")
static const efftype_id effect_recover ("recover")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_slept_through_alarm ("slept_through_alarm")
static const efftype_id effect_spores ("spores")
static const efftype_id effect_strong_antibiotic ("strong_antibiotic")
static const efftype_id effect_tapeworm ("tapeworm")
static const efftype_id effect_teleglow ("teleglow")
static const efftype_id effect_toxin_buildup ("toxin_buildup")
static const efftype_id effect_visuals ("visuals")
static const efftype_id effect_weak_antibiotic ("weak_antibiotic")
const vitamin_id vitamin_iron ("iron")
const vitamin_id vitamin_mutant_toxin ("mutant_toxin")
static const mongroup_id GROUP_NETHER ("GROUP_NETHER")
static const mtype_id mon_dermatik_larva ("mon_dermatik_larva")
static const bionic_id bio_watch ("bio_watch")
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_HEAVYSLEEPER2 ("HEAVYSLEEPER2")
static const trait_id trait_HIBERNATE ("HIBERNATE")
static const trait_id trait_INFRESIST ("INFRESIST")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_SEESLEEP ("SEESLEEP")
static const trait_id trait_SCHIZOPHRENIC ("SCHIZOPHRENIC")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
Function Documentation
eff_fun_bleed()
static void eff_fun_bleed (player & u, effect & it) static
Definition at line 208 of file player_hardcoded_effects.cpp.
{
    // Presuming that during the first-aid process you're putting pressure
    // on the wound or otherwise suppressing the flow. (Kits contain either
    // QuikClot or bandages per the recipe.)
    const int intense = it.get_intensity();
    if( one_in( 36 / intense ) && u.activity.id() != ACT_FIRSTAID ) {
        u.add_msg_player_or_npc( m_bad, _( "You lose some blood." ),
                                 _( "<npcname> loses some blood." ) );
        // Prolonged hemorrhage is a significant risk for developing anemia
        u.vitamin_mod( vitamin_iron, rng( -1, -4 ) );
        u.mod_pain( 1 );
        u.apply_damage( nullptr, it.get_bp(), 1 );
        u.bleed();
    }
}
References _, ACT_FIRSTAID, Character::activity, player::add_msg_player_or_npc(), Character::apply_damage(), Creature::bleed(), effect::get_bp(), effect::get_intensity(), player_activity::id(), m_bad, Character::mod_pain(), one_in(), rng(), vitamin_iron, and Character::vitamin_mod().
Referenced by Character::hardcoded_effects().
eff_fun_bloated()
static void eff_fun_bloated (player & u, effect & it) static
Definition at line 431 of file player_hardcoded_effects.cpp.
{
    if( u.get_stored_kcal() > u.max_stored_kcal() || u.get_thirst() < 0 ) {
        it.set_duration( 5_minutes );
    }
}
References Character::get_stored_kcal(), Character::get_thirst(), Character::max_stored_kcal(), and effect::set_duration().
Referenced by Character::hardcoded_effects().
eff_fun_cold()
static void eff_fun_cold (player & u, effect & it) static
Definition at line 337 of file player_hardcoded_effects.cpp.
{
    // { body_part, intensity }, { str_pen, dex_pen, int_pen, per_pen, msg, msg_chance, miss_msg }
    static const std::map<std::pair<body_part, int>, temperature_effect> effs = {{
            { { bp_head, 3 }, { 0, 0, 3, 0, translate_marker( "Your thoughts are unclear." ), 2400, "" } },
            { { bp_head, 2 }, { 0, 0, 1, 0, "", 0, "" } },
            { { bp_mouth, 3 }, { 0, 0, 0, 3, translate_marker( "Your face is stiff from the cold." ), 2400, "" } },
            { { bp_mouth, 2 }, { 0, 0, 0, 1, "", 0, "" } },
            { { bp_torso, 3 }, { 0, 4, 0, 0, translate_marker( "Your torso is freezing cold.  You should put on a few more layers." ), 400, translate_marker( "You quiver from the cold." ) } },
            { { bp_torso, 2 }, { 0, 2, 0, 0, "", 0, translate_marker( "Your shivering makes you unsteady." ) } },
            { { bp_arm_l, 3 }, { 0, 2, 0, 0, translate_marker( "Your left arm is shivering." ), 4800, translate_marker( "Your left arm trembles from the cold." ) } },
            { { bp_arm_l, 2 }, { 0, 1, 0, 0, translate_marker( "Your left arm is shivering." ), 4800, translate_marker( "Your left arm trembles from the cold." ) } },
            { { bp_arm_r, 3 }, { 0, 2, 0, 0, translate_marker( "Your right arm is shivering." ), 4800, translate_marker( "Your right arm trembles from the cold." ) } },
            { { bp_arm_r, 2 }, { 0, 1, 0, 0, translate_marker( "Your right arm is shivering." ), 4800, translate_marker( "Your right arm trembles from the cold." ) } },
            { { bp_hand_l, 3 }, { 0, 2, 0, 0, translate_marker( "Your left hand feels like ice." ), 4800, translate_marker( "Your left hand quivers in the cold." ) } },
            { { bp_hand_l, 2 }, { 0, 1, 0, 0, translate_marker( "Your left hand feels like ice." ), 4800, translate_marker( "Your left hand quivers in the cold." ) } },
            { { bp_hand_r, 3 }, { 0, 2, 0, 0, translate_marker( "Your right hand feels like ice." ), 4800, translate_marker( "Your right hand quivers in the cold." ) } },
            { { bp_hand_r, 2 }, { 0, 1, 0, 0, translate_marker( "Your right hand feels like ice." ), 4800, translate_marker( "Your right hand quivers in the cold." ) } },
            { { bp_leg_l, 3 }, { 2, 2, 0, 0, translate_marker( "Your left leg trembles against the relentless cold." ), 4800, translate_marker( "Your legs uncontrollably shake from the cold." ) } },
            { { bp_leg_l, 2 }, { 1, 1, 0, 0, translate_marker( "Your left leg trembles against the relentless cold." ), 4800, translate_marker( "Your legs uncontrollably shake from the cold." ) } },
            { { bp_leg_r, 3 }, { 2, 2, 0, 0, translate_marker( "Your right leg trembles against the relentless cold." ), 4800, translate_marker( "Your legs uncontrollably shake from the cold." ) } },
            { { bp_leg_r, 2 }, { 1, 1, 0, 0, translate_marker( "Your right leg trembles against the relentless cold." ), 4800, translate_marker( "Your legs uncontrollably shake from the cold." ) } },
            { { bp_foot_l, 3 }, { 2, 2, 0, 0, translate_marker( "Your left foot feels frigid." ), 4800, translate_marker( "Your left foot is as nimble as a block of ice." ) } },
            { { bp_foot_l, 2 }, { 1, 1, 0, 0, translate_marker( "Your left foot feels frigid." ), 4800, translate_marker( "Your freezing left foot messes up your balance." ) } },
            { { bp_foot_r, 3 }, { 2, 2, 0, 0, translate_marker( "Your right foot feels frigid." ), 4800, translate_marker( "Your right foot is as nimble as a block of ice." ) } },
            { { bp_foot_r, 2 }, { 1, 1, 0, 0, translate_marker( "Your right foot feels frigid." ), 4800, translate_marker( "Your freezing right foot messes up your balance." ) } },
        }
    };
    const auto iter = effs.find( { it.get_bp()->token, it.get_intensity() } );
    if( iter != effs.end() ) {
        iter->second.apply( u );
    }
}
References bp_arm_l, bp_arm_r, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_mouth, bp_torso, effect::get_bp(), effect::get_intensity(), and translate_marker.
Referenced by Character::hardcoded_effects().
eff_fun_frostbite()
static void eff_fun_frostbite (player & u, effect & it) static
Definition at line 411 of file player_hardcoded_effects.cpp.
{
    // { body_part, intensity }, { str_pen, dex_pen, int_pen, per_pen, msg, msg_chance, miss_msg }
    static const std::map<std::pair<body_part, int>, temperature_effect> effs = {{
            { { bp_hand_l, 2 }, { 0, 2, 0, 0, "", 0, translate_marker( "You have trouble grasping with your numb fingers." ) } },
            { { bp_hand_r, 2 }, { 0, 2, 0, 0, "", 0, translate_marker( "You have trouble grasping with your numb fingers." ) } },
            { { bp_foot_l, 2 }, { 0, 0, 0, 0, translate_marker( "Your foot has gone numb." ), 4800, "" } },
            { { bp_foot_l, 1 }, { 0, 0, 0, 0, translate_marker( "Your foot has gone numb." ), 4800, "" } },
            { { bp_foot_r, 2 }, { 0, 0, 0, 0, translate_marker( "Your foot has gone numb." ), 4800, "" } },
            { { bp_foot_r, 1 }, { 0, 0, 0, 0, translate_marker( "Your foot has gone numb." ), 4800, "" } },
            { { bp_mouth, 2 }, { 0, 0, 0, 3, translate_marker( "Your face feels numb." ), 4800, "" } },
            { { bp_mouth, 1 }, { 0, 0, 0, 1, translate_marker( "Your face feels numb." ), 4800, "" } },
        }
    };
    const auto iter = effs.find( { it.get_bp()->token, it.get_intensity() } );
    if( iter != effs.end() ) {
        iter->second.apply( u );
    }
}
References bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_mouth, effect::get_bp(), effect::get_intensity(), and translate_marker.
Referenced by Character::hardcoded_effects().
eff_fun_fungus()
static void eff_fun_fungus (player & u, effect & it) static
Definition at line 131 of file player_hardcoded_effects.cpp.
{
    const time_duration dur = it.get_duration();
    const int intense = it.get_intensity();
    const int bonus = u.get_healthy() / 10 + ( u.resists_effect( it ) ? 100 : 0 );
    switch( intense ) {
        case 1:
            // First hour symptoms
            if( one_in( 960 + bonus * 6 ) ) {
                u.cough( true );
            }
            if( one_in( 600 ) ) {
                u.add_msg_if_player( m_warning, _( "You feel nauseous." ) );
            }
            if( calendar::once_every( 10_minutes ) ) {
                u.add_msg_if_player( m_warning, _( "You smell and taste mushrooms." ) );
            }
            it.mod_duration( 1_turns );
            if( dur > 1_hours ) {
                it.mod_intensity( 1 );
            }
            break;
        case 2:
            // Five hours of worse symptoms
            if( one_in( 3600 + bonus * 18 ) ) {
                u.add_msg_if_player( m_bad,  _( "You spasm suddenly!" ) );
                u.moves -= 100;
                u.apply_damage( nullptr, bodypart_id( "torso" ), 5 );
            }
            if( x_in_y( character_effects::vomit_mod( u ), ( 4800 + bonus * 24 ) ) ||
                one_in( 12000 + bonus * 60 ) ) {
                u.add_msg_player_or_npc( m_bad, _( "You vomit a thick, gray goop." ),
                                         _( "<npcname> vomits a thick, gray goop." ) );
                const int awfulness = rng( 0, 10 );
                u.moves = -200;
                u.mod_stored_kcal( -10 * awfulness );
                u.mod_thirst( awfulness );
                u.apply_damage( nullptr, bodypart_id( "torso" ), 1 );
            }
            it.mod_duration( 1_turns );
            if( dur > 6_hours ) {
                it.mod_intensity( 1 );
            }
            break;
        case 3: {
            // Permanent symptoms
            bool is_fungal_ter = g->m.has_flag_ter( "FUNGUS", u.pos() );
            if( !is_fungal_ter && one_in( 600 + 4 * bonus ) ) {
                u.add_effect( effect_nausea, 5_minutes );
            }
        }
        break;
    }
}
References _, Creature::add_effect(), player::add_msg_if_player(), player::add_msg_player_or_npc(), Character::apply_damage(), Character::cough(), effect_nausea, g, effect::get_duration(), Character::get_healthy(), effect::get_intensity(), m_bad, m_warning, effect::mod_duration(), effect::mod_intensity(), Character::mod_stored_kcal(), Character::mod_thirst(), Creature::moves, calendar::once_every(), one_in(), Character::pos(), Creature::resists_effect(), rng(), character_effects::vomit_mod(), and x_in_y().
Referenced by Character::hardcoded_effects().
eff_fun_hallu()
static void eff_fun_hallu (player & u, effect & it) static
NPC Strength increases volume of hallucination sounds (NEGATIVE) NPC Intelligence decreases volume of hallucination sounds
Definition at line 224 of file player_hardcoded_effects.cpp.
{
    // TODO: Redo this to allow for variable durations
    // Time intervals are drawn from the old ones based on 3600 (6-hour) duration.
    constexpr int maxDuration = 21600;
    constexpr int comeupTime = static_cast<int>( maxDuration * 0.9 );
    constexpr int noticeTime = static_cast<int>( comeupTime + ( maxDuration - comeupTime ) / 2 );
    constexpr int peakTime = static_cast<int>( maxDuration * 0.8 );
    constexpr int comedownTime = static_cast<int>( maxDuration * 0.3 );
    const int dur = to_turns<int>( it.get_duration() );
    // Baseline
    if( dur == noticeTime ) {
        u.add_msg_if_player( m_warning, _( "You feel a little strange." ) );
    } else if( dur == comeupTime ) {
        // Coming up
        if( one_in( 2 ) ) {
            u.add_msg_if_player( m_warning, _( "The world takes on a dreamlike quality." ) );
        } else if( one_in( 3 ) ) {
            u.add_msg_if_player( m_warning, _( "You have a sudden nostalgic feeling." ) );
        } else if( one_in( 5 ) ) {
            u.add_msg_if_player( m_warning, _( "Everything around you is starting to breathe." ) );
        } else {
            u.add_msg_if_player( m_warning, _( "Something feels very, very wrong." ) );
        }
    } else if( dur > peakTime && dur < comeupTime ) {
        if( u.stomach.get_calories() > 0 &&
            ( one_in( 1200 ) || x_in_y( character_effects::vomit_mod( u ), 300 ) ) ) {
            u.add_msg_if_player( m_bad, _( "You feel sick to your stomach." ) );
            u.mod_stored_kcal( 20 );
            if( one_in( 6 ) ) {
                u.vomit();
            }
        }
        if( u.is_npc() && one_in( 1200 ) ) {
            static const std::array<std::string, 4> npc_hallu = {{
                    translate_marker( "\"I think it's starting to kick in.\"" ),
                    translate_marker( "\"Oh God, what's happening?\"" ),
                    translate_marker( "\"Of course it's all fractals!\"" ),
                    translate_marker( "\"Huh?  What was that?\"" )
                }
            };
            ///\EFFECT_STR_NPC increases volume of hallucination sounds (NEGATIVE)
            ///\EFFECT_INT_NPC decreases volume of hallucination sounds
            int loudness = 20 + u.str_cur - u.int_cur;
            loudness = ( loudness > 5 ? loudness : 5 );
            loudness = ( loudness < 30 ? loudness : 30 );
            sounds::sound( u.pos(), loudness, sounds::sound_t::speech, _( random_entry_ref( npc_hallu ) ),
                           false, "speech",
                           loudness < 15 ? ( u.male ? "NPC_m" : "NPC_f" ) : ( u.male ? "NPC_m_loud" : "NPC_f_loud" ) );
        }
    } else if( dur == peakTime ) {
        // Visuals start
        u.add_msg_if_player( m_bad, _( "Fractal patterns dance across your vision." ) );
        u.add_effect( effect_visuals, time_duration::from_turns( peakTime - comedownTime ) );
    } else if( dur > comedownTime && dur < peakTime ) {
        // Full symptoms
        u.mod_per_bonus( -2 );
        u.mod_int_bonus( -1 );
        u.mod_dex_bonus( -2 );
        u.add_miss_reason( _( "Dancing fractals distract you." ), 2 );
        u.mod_str_bonus( -1 );
        if( u.is_player() && one_in( 50 ) ) {
            g->spawn_hallucination( u.pos() + tripoint( rng( -10, 10 ), rng( -10, 10 ), 0 ) );
        }
    } else if( dur == comedownTime ) {
        if( one_in( 42 ) ) {
            u.add_msg_if_player( _( "Everything looks SO boring now." ) );
        } else {
            u.add_msg_if_player( _( "Things are returning to normal." ) );
        }
    }
}
References _, Creature::add_effect(), Character::add_miss_reason(), player::add_msg_if_player(), effect_visuals, time_duration::from_turns(), g, stomach_contents::get_calories(), effect::get_duration(), Character::int_cur, player::is_npc(), player::is_player(), m_bad, m_warning, Character::male, Character::mod_dex_bonus(), Character::mod_int_bonus(), Character::mod_per_bonus(), Character::mod_stored_kcal(), Character::mod_str_bonus(), one_in(), Character::pos(), random_entry_ref(), rng(), sounds::sound(), sounds::speech, Character::stomach, Character::str_cur, translate_marker, Character::vomit(), character_effects::vomit_mod(), and x_in_y().
Referenced by Character::hardcoded_effects().
eff_fun_hot()
static void eff_fun_hot (player & u, effect & it) static
Definition at line 371 of file player_hardcoded_effects.cpp.
{
    // { body_part, intensity }, { str_pen, dex_pen, int_pen, per_pen, msg, msg_chance, miss_msg }
    static const std::map<std::pair<body_part, int>, temperature_effect> effs = {{
            { { bp_head, 3 }, { 0, 0, 0, 0, translate_marker( "Your head is pounding from the heat." ), 2400, "" } },
            { { bp_head, 2 }, { 0, 0, 0, 0, "", 0, "" } },
            { { bp_torso, 3 }, { 2, 0, 0, 0, translate_marker( "You are sweating profusely." ), 2400, "" } },
            { { bp_torso, 2 }, { 1, 0, 0, 0, "", 0, "" } },
            { { bp_hand_l, 3 }, { 0, 2, 0, 0, "", 0, translate_marker( "Your left hand's too sweaty to grip well." ) } },
            { { bp_hand_l, 2 }, { 0, 1, 0, 0, "", 0, translate_marker( "Your left hand's too sweaty to grip well." ) } },
            { { bp_hand_r, 3 }, { 0, 2, 0, 0, "", 0, translate_marker( "Your right hand's too sweaty to grip well." ) } },
            { { bp_hand_r, 2 }, { 0, 1, 0, 0, "", 0, translate_marker( "Your right hand's too sweaty to grip well." ) } },
            { { bp_leg_l, 3 }, { 0, 0, 0, 0, translate_marker( "Your left leg is cramping up." ), 4800, "" } },
            { { bp_leg_l, 2 }, { 0, 0, 0, 0, "", 0, "" } },
            { { bp_leg_r, 3 }, { 0, 0, 0, 0, translate_marker( "Your right leg is cramping up." ), 4800, "" } },
            { { bp_leg_r, 2 }, { 0, 0, 0, 0, "", 0, "" } },
            { { bp_foot_l, 3 }, { 0, 0, 0, 0, translate_marker( "Your left foot is swelling in the heat." ), 4800, "" } },
            { { bp_foot_l, 2 }, { 0, 0, 0, 0, "", 0, "" } },
            { { bp_foot_r, 3 }, { 0, 0, 0, 0, translate_marker( "Your right foot is swelling in the heat." ), 4800, "" } },
            { { bp_foot_r, 2 }, { 0, 0, 0, 0, "", 0, "" } },
        }
    };
    const body_part bp = it.get_bp()->token;
    const int intense = it.get_intensity();
    const auto iter = effs.find( { it.get_bp()->token, it.get_intensity() } );
    if( iter != effs.end() ) {
        iter->second.apply( u );
    }
    // Hothead effects are a special snowflake
    if( bp == bp_head && intense >= 2 ) {
        if( one_in( std::max( 25, std::min( 89500, 90000 - u.temp_cur[bp_head] ) ) ) ) {
            u.vomit();
        }
        if( !u.has_effect( effect_sleep ) && one_in( 2400 ) ) {
            u.add_msg_if_player( m_bad, _( "The heat is making you see things." ) );
        }
    }
}
References _, player::add_msg_if_player(), bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_torso, effect_sleep, effect::get_bp(), effect::get_intensity(), Creature::has_effect(), m_bad, one_in(), Character::temp_cur, body_part_type::token, translate_marker, and Character::vomit().
Referenced by Character::hardcoded_effects().
eff_fun_mutating()
static void eff_fun_mutating (player & u, effect & it) static
Definition at line 446 of file player_hardcoded_effects.cpp.
{
    if( it.get_intensity() > 1 ) {
        // "Activate" toxins that would otherwise need to accumulate first
        // There is some loss
        const vitamin &tox = *vitamin_mutant_toxin;
        int vit_amt = u.vitamin_get( vitamin_mutant_toxin );
        time_duration extra_duration = it.get_max_duration() / 2 * vit_amt / tox.max();
        it.mod_duration( extra_duration );
        u.vitamin_set( vitamin_mutant_toxin, 0 );
    }
    // At intensity 1
    constexpr time_duration base_time_per_mut = 2_days;
    int mutation_mult = it.get_intensity() * it.get_intensity();
    float muts_per_second = mutation_mult / to_seconds<float>( base_time_per_mut );
    float mgen_per_mut = to_seconds<float>( effect_accumulated_mutagen->get_int_dur_factor() );
    float mgen_per_second = mgen_per_mut * muts_per_second;
    // How much accumulated mutagen effect do we add per second
    time_duration mgen_time_mult = 1_seconds * roll_remainder( mgen_per_second );
    u.add_effect( effect_accumulated_mutagen, mgen_time_mult );
    if( u.get_effect_int( effect_accumulated_mutagen ) > 1 ) {
        u.mutate();
    }
}
References Creature::add_effect(), effect_accumulated_mutagen, Creature::get_effect_int(), effect_type::get_int_dur_factor(), effect::get_intensity(), effect::get_max_duration(), vitamin::max(), effect::mod_duration(), Character::mutate(), roll_remainder(), Character::vitamin_get(), vitamin_mutant_toxin, and Character::vitamin_set().
Referenced by Character::hardcoded_effects().
eff_fun_onfire()
static void eff_fun_onfire (player & u, effect & it) static
Definition at line 116 of file player_hardcoded_effects.cpp.
{
    const int intense = it.get_intensity();
    u.deal_damage( nullptr, it.get_bp(), damage_instance( DT_HEAT, rng( intense,
                   intense * 2 ) ) );
}
References Character::deal_damage(), DT_HEAT, effect::get_bp(), effect::get_intensity(), and rng().
Referenced by Character::hardcoded_effects().
eff_fun_rat()
static void eff_fun_rat (player & u, effect & it) static
Definition at line 186 of file player_hardcoded_effects.cpp.
{
    const int dur = to_turns<int>( it.get_duration() );
    it.set_intensity( dur / 10 );
    if( rng( 0, 100 ) < dur / 10 ) {
        if( !one_in( 5 ) ) {
            u.mutate_category( "RAT" );
            it.mult_duration( .2 );
        } else {
            u.mutate_category( "TROGLOBITE" );
            it.mult_duration( .33 );
        }
    } else if( rng( 0, 100 ) < dur / 8 ) {
        if( one_in( 3 ) ) {
            u.vomit();
            it.mod_duration( -1_minutes );
        } else {
            u.add_msg_if_player( m_bad, _( "You feel nauseous!" ) );
            it.mod_duration( 3_turns );
        }
    }
}
References _, player::add_msg_if_player(), effect::get_duration(), m_bad, effect::mod_duration(), effect::mult_duration(), Character::mutate_category(), one_in(), rng(), effect::set_intensity(), and Character::vomit().
Referenced by Character::hardcoded_effects().
eff_fun_spores()
static void eff_fun_spores (player & u, effect & it) static
Definition at line 122 of file player_hardcoded_effects.cpp.
{
    // Equivalent to X in 150000 + health * 100
    const int intense = it.get_intensity();
    if( ( !u.has_trait( trait_M_IMMUNE ) ) && ( one_in( 100 ) &&
            x_in_y( intense, 900 + u.get_healthy() * 0.6 ) ) ) {
        u.add_effect( effect_fungus, 1_turns, num_bp );
    }
}
References Creature::add_effect(), effect_fungus, Character::get_healthy(), effect::get_intensity(), Character::has_trait(), num_bp, one_in(), trait_M_IMMUNE, and x_in_y().
Referenced by Character::hardcoded_effects().
eff_fun_toxin_buildup()
static void eff_fun_toxin_buildup (player & u, effect & it) static
Definition at line 438 of file player_hardcoded_effects.cpp.
{
    if( it.get_intensity() > 3 ) {
        u.vitamin_set( vitamin_mutant_toxin, 0 );
        u.add_effect( effect_mutating, effect_mutating->get_max_duration() / 2 );
    }
}
References Creature::add_effect(), effect_mutating, effect::get_intensity(), effect_type::get_max_duration(), vitamin_mutant_toxin, and Character::vitamin_set().
Referenced by Character::hardcoded_effects().
Variable Documentation
ACT_FIRSTAID
const activity_id ACT_FIRSTAID("ACT_FIRSTAID") ("ACT_FIRSTAID") static
Referenced by eff_fun_bleed().
bio_watch
const bionic_id bio_watch("bio_watch") ("bio_watch") static
Referenced by Character::hardcoded_effects().
effect_accumulated_mutagen
const efftype_id effect_accumulated_mutagen("accumulated_mutagen") ("accumulated_mutagen") static
Referenced by eff_fun_mutating().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by Character::hardcoded_effects().
effect_alarm_clock
const efftype_id effect_alarm_clock("alarm_clock") ("alarm_clock") static
Referenced by Character::hardcoded_effects().
effect_antibiotic
const efftype_id effect_antibiotic("antibiotic") ("antibiotic") static
Referenced by Character::hardcoded_effects().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by Character::hardcoded_effects().
effect_attention
const efftype_id effect_attention("attention") ("attention") static
Referenced by Character::hardcoded_effects().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by Character::hardcoded_effects().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::hardcoded_effects().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by Character::hardcoded_effects().
effect_bloated
const efftype_id effect_bloated("bloated") ("bloated") static
Referenced by Character::hardcoded_effects().
effect_bloodworms
const efftype_id effect_bloodworms("bloodworms") ("bloodworms") static
Referenced by Character::hardcoded_effects().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by Character::hardcoded_effects().
effect_brainworms
const efftype_id effect_brainworms("brainworms") ("brainworms") static
Referenced by Character::hardcoded_effects().
effect_cold
const efftype_id effect_cold("cold") ("cold") static
Referenced by Character::hardcoded_effects().
effect_datura
const efftype_id effect_datura("datura") ("datura") static
Referenced by Character::hardcoded_effects().
effect_dazed
const efftype_id effect_dazed("dazed") ("dazed") static
Referenced by Character::hardcoded_effects().
effect_dermatik
const efftype_id effect_dermatik("dermatik") ("dermatik") static
Referenced by Character::hardcoded_effects().
effect_disabled
const efftype_id effect_disabled("disabled") ("disabled") static
Referenced by Character::hardcoded_effects().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by Character::hardcoded_effects().
effect_evil
const efftype_id effect_evil("evil") ("evil") static
Referenced by Character::hardcoded_effects().
effect_fearparalyze
const efftype_id effect_fearparalyze("fearparalyze") ("fearparalyze") static
Referenced by Character::hardcoded_effects().
effect_formication
const efftype_id effect_formication("formication") ("formication") static
Referenced by Character::hardcoded_effects().
effect_frostbite
const efftype_id effect_frostbite("frostbite") ("frostbite") static
Referenced by Character::hardcoded_effects().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by eff_fun_spores(), and Character::hardcoded_effects().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by Character::hardcoded_effects().
effect_grabbing
const efftype_id effect_grabbing("grabbing") ("grabbing") static
Referenced by Character::hardcoded_effects().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by Character::hardcoded_effects().
effect_hot
const efftype_id effect_hot("hot") ("hot") static
Referenced by Character::hardcoded_effects().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by Character::hardcoded_effects().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by Character::hardcoded_effects().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by Character::hardcoded_effects().
effect_mutating
const efftype_id effect_mutating("mutating") ("mutating") static
Referenced by eff_fun_toxin_buildup(), and Character::hardcoded_effects().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::hardcoded_effects().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by eff_fun_fungus(), and Character::hardcoded_effects().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by Character::hardcoded_effects().
effect_paincysts
const efftype_id effect_paincysts("paincysts") ("paincysts") static
Referenced by Character::hardcoded_effects().
effect_panacea
const efftype_id effect_panacea("panacea") ("panacea") static
Referenced by Character::hardcoded_effects().
effect_rat
const efftype_id effect_rat("rat") ("rat") static
Referenced by Character::hardcoded_effects().
effect_recover
const efftype_id effect_recover("recover") ("recover") static
Referenced by Character::hardcoded_effects().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by temperature_effect::apply(), eff_fun_hot(), and Character::hardcoded_effects().
effect_slept_through_alarm
const efftype_id effect_slept_through_alarm("slept_through_alarm") ("slept_through_alarm") static
Referenced by Character::hardcoded_effects().
effect_spores
const efftype_id effect_spores("spores") ("spores") static
Referenced by Character::hardcoded_effects().
effect_strong_antibiotic
const efftype_id effect_strong_antibiotic("strong_antibiotic") ("strong_antibiotic") static
Referenced by Character::hardcoded_effects().
effect_tapeworm
const efftype_id effect_tapeworm("tapeworm") ("tapeworm") static
Referenced by Character::hardcoded_effects().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by Character::hardcoded_effects().
effect_toxin_buildup
const efftype_id effect_toxin_buildup("toxin_buildup") ("toxin_buildup") static
Referenced by Character::hardcoded_effects().
effect_visuals
const efftype_id effect_visuals("visuals") ("visuals") static
Referenced by eff_fun_hallu(), and Character::hardcoded_effects().
effect_weak_antibiotic
const efftype_id effect_weak_antibiotic("weak_antibiotic") ("weak_antibiotic") static
Referenced by Character::hardcoded_effects().
GROUP_NETHER
const mongroup_id GROUP_NETHER("GROUP_NETHER") ("GROUP_NETHER") static
Referenced by Character::hardcoded_effects().
mon_dermatik_larva
const mtype_id mon_dermatik_larva("mon_dermatik_larva") ("mon_dermatik_larva") static
Referenced by Character::hardcoded_effects().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by Character::hardcoded_effects().
trait_HEAVYSLEEPER2
const trait_id trait_HEAVYSLEEPER2("HEAVYSLEEPER2") ("HEAVYSLEEPER2") static
Referenced by Character::hardcoded_effects().
trait_HIBERNATE
const trait_id trait_HIBERNATE("HIBERNATE") ("HIBERNATE") static
Referenced by Character::hardcoded_effects().
trait_INFRESIST
const trait_id trait_INFRESIST("INFRESIST") ("INFRESIST") static
Referenced by Character::hardcoded_effects().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by eff_fun_spores(), and Character::hardcoded_effects().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by Character::hardcoded_effects().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by Character::hardcoded_effects().
trait_SCHIZOPHRENIC
const trait_id trait_SCHIZOPHRENIC("SCHIZOPHRENIC") ("SCHIZOPHRENIC") static
Referenced by Character::hardcoded_effects().
trait_SEESLEEP
const trait_id trait_SEESLEEP("SEESLEEP") ("SEESLEEP") static
Referenced by Character::hardcoded_effects().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by Character::hardcoded_effects().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by Character::hardcoded_effects().
vitamin_iron
const vitamin_id vitamin_iron("iron") ("iron")
Referenced by eff_fun_bleed().
vitamin_mutant_toxin
const vitamin_id vitamin_mutant_toxin("mutant_toxin") ("mutant_toxin")
Referenced by eff_fun_mutating(), and eff_fun_toxin_buildup().