Cataclysm BN: src/player.h File Reference
player.h File Reference
#include <climits>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "character.h"
#include "character_id.h"
#include "color.h"
#include "creature.h"
#include "cursesdef.h"
#include "enums.h"
#include "game_constants.h"
#include "item.h"
#include "item_location.h"
#include "optional.h"
#include "pimpl.h"
#include "point.h"
#include "ret_val.h"
#include "safe_reference.h"
#include "string_id.h"
#include "type_id.h"
Classes
struct ret_val< T >::default_success
struct ret_val< T >::default_failure
struct needs_rates
class player
struct player::power_mut_ui_result
Macros
#define CATA_SRC_PLAYER_H
Typedefs
using recipe_filter = std::function< bool(const recipe &r)>
Functions
static const std::string DEFAULT_HOTKEYS ("1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
nc_color encumb_color (int level)
int calc_fatigue_cap (int fatigue)
Calculates the player's morale cap due to fatigue.
Macro Definition Documentation
CATA_SRC_PLAYER_H
#define CATA_SRC_PLAYER_H
Definition at line 3 of file player.h.
Typedef Documentation
recipe_filter
using recipe_filter = std::function<bool(const recipe &r)>
Definition at line 71 of file player.h.
Function Documentation
calc_fatigue_cap()
int calc_fatigue_cap (int fatigue)
Calculates the player's morale cap due to fatigue.
Definition at line 4015 of file player.cpp.
{
    if( fatigue >= fatigue_levels::massive ) {
        return 20;
    } else if( fatigue >= fatigue_levels::exhausted ) {
        return 40;
    } else if( fatigue >= fatigue_levels::dead_tired ) {
        return 60;
    } else if( fatigue >= fatigue_levels::tired ) {
        return 80;
    }
    return 0;
}
References dead_tired, exhausted, massive, and tired.
Referenced by player::calc_focus_equilibrium(), and avatar::disp_morale().
DEFAULT_HOTKEYS()
static const std::string DEFAULT_HOTKEYS ("1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") static
Referenced by player::can_continue_craft(), craft_command::execute(), uilist::init(), and crafting::select_tool_component().
encumb_color()
nc_color encumb_color (int level)
Definition at line 3901 of file player.cpp.
{
    if( level < 0 ) {
        return c_green;
    }
    if( level < 10 ) {
        return c_light_gray;
    }
    if( level < 40 ) {
        return c_yellow;
    }
    if( level < 70 ) {
        return c_light_red;
    }
    return c_red;
}
References c_green, c_light_gray, c_light_red, c_red, and c_yellow.
Referenced by character_display::print_encumbrance().