Cataclysm BN: src/player.cpp File Reference
player.cpp File Reference
#include "player.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include "action.h"
#include "activity_handlers.h"
#include "ammo.h"
#include "avatar.h"
#include "avatar_action.h"
#include "bionics.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_effects.h"
#include "character_martial_arts.h"
#include "clzones.h"
#include "craft_command.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "faction.h"
#include "fault.h"
#include "flag.h"
#include "field_type.h"
#include "game.h"
#include "game_inventory.h"
#include "gun_mode.h"
#include "handle_liquid.h"
#include "input.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "itype.h"
#include "lightmap.h"
#include "line.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "martialarts.h"
#include "messages.h"
#include "monster.h"
#include "morale.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmap_types.h"
#include "overmapbuffer.h"
#include "pickup.h"
#include "player_activity.h"
#include "pldata.h"
#include "profession.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "rng.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "visitable.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
Functions
static const std::string flag_SPLINT ("SPLINT")
static const std::string flag_RESTRICT_HAND ("RESTRICT_HANDS")
static bool query_consume_ownership (item &target, player &p)
static bool is_pet_food (const item &itm)
static bool has_mod (const item &gun, const item &mod)
nc_color encumb_color (int level)
int calc_fatigue_cap (int fatigue)
Calculates the player's morale cap due to fatigue.
Variables
static const activity_id ACT_READ ("ACT_READ")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bloodworms ("bloodworms")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_brainworms ("brainworms")
static const efftype_id effect_darkness ("darkness")
static const efftype_id effect_depressants ("depressants")
static const efftype_id effect_dermatik ("dermatik")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_happy ("happy")
static const efftype_id effect_irradiated ("irradiated")
static const efftype_id effect_masked_scent ("masked_scent")
static const efftype_id effect_meth ("meth")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_paincysts ("paincysts")
static const efftype_id effect_pkill ("pkill")
static const efftype_id effect_sad ("sad")
static const efftype_id effect_sleep_deprived ("sleep_deprived")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_stim_overdose ("stim_overdose")
static const efftype_id effect_stim ("stim")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_tapeworm ("tapeworm")
static const efftype_id effect_thirsty ("thirsty")
static const efftype_id effect_weed_high ("weed_high")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_battery ("battery")
static const itype_id itype_brass_catcher ("brass_catcher")
static const itype_id itype_large_repairkit ("large_repairkit")
static const itype_id itype_plut_cell ("plut_cell")
static const itype_id itype_small_repairkit ("small_repairkit")
static const itype_id itype_syringe ("syringe")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_UPS_off ("UPS_off")
static const trait_id trait_ACIDBLOOD ("ACIDBLOOD")
static const trait_id trait_DEBUG_NODMG ("DEBUG_NODMG")
static const trait_id trait_ARACHNID_ARMS ("ARACHNID_ARMS")
static const trait_id trait_ARACHNID_ARMS_OK ("ARACHNID_ARMS_OK")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_CF_HAIR ("CF_HAIR")
static const trait_id trait_CHITIN2 ("CHITIN2")
static const trait_id trait_CHITIN3 ("CHITIN3")
static const trait_id trait_CHITIN_FUR2 ("CHITIN_FUR2")
static const trait_id trait_CHITIN_FUR3 ("CHITIN_FUR3")
static const trait_id trait_CHITIN_FUR ("CHITIN_FUR")
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_COLDBLOOD4 ("COLDBLOOD4")
static const trait_id trait_COMPOUND_EYES ("COMPOUND_EYES")
static const trait_id trait_DEBUG_BIONIC_POWER ("DEBUG_BIONIC_POWER")
static const trait_id trait_DEBUG_CLOAK ("DEBUG_CLOAK")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_DEFT ("DEFT")
static const trait_id trait_EASYSLEEPER2 ("EASYSLEEPER2")
static const trait_id trait_EASYSLEEPER ("EASYSLEEPER")
static const trait_id trait_EATHEALTH ("EATHEALTH")
static const trait_id trait_FAT ("FAT")
static const trait_id trait_FELINE_FUR ("FELINE_FUR")
static const trait_id trait_FUR ("FUR")
static const trait_id trait_INSECT_ARMS ("INSECT_ARMS")
static const trait_id trait_INSECT_ARMS_OK ("INSECT_ARMS_OK")
static const trait_id trait_INSOMNIA ("INSOMNIA")
static const trait_id trait_LIGHTFUR ("LIGHTFUR")
static const trait_id trait_LUPINE_FUR ("LUPINE_FUR")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_MOREPAIN2 ("MORE_PAIN2")
static const trait_id trait_MOREPAIN3 ("MORE_PAIN3")
static const trait_id trait_MOREPAIN ("MORE_PAIN")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_NAUSEA ("NAUSEA")
static const trait_id trait_NOMAD2 ("NOMAD2")
static const trait_id trait_NOMAD3 ("NOMAD3")
static const trait_id trait_NOMAD ("NOMAD")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PACIFIST ("PACIFIST")
static const trait_id trait_PAINRESIST ("PAINRESIST")
static const trait_id trait_PAINRESIST_TROGLO ("PAINRESIST_TROGLO")
static const trait_id trait_PARAIMMUNE ("PARAIMMUNE")
static const trait_id trait_PARKOUR ("PARKOUR")
static const trait_id trait_PROF_SKATER ("PROF_SKATER")
static const trait_id trait_QUILLS ("QUILLS")
static const trait_id trait_SAVANT ("SAVANT")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SLIMY ("SLIMY")
static const trait_id trait_SPINES ("SPINES")
static const trait_id trait_STIMBOOST ("STIMBOOST")
static const trait_id trait_STRONGSTOMACH ("STRONGSTOMACH")
static const trait_id trait_SUNLIGHT_DEPENDENT ("SUNLIGHT_DEPENDENT")
static const trait_id trait_THICK_SCALES ("THICK_SCALES")
static const trait_id trait_THORNS ("THORNS")
static const trait_id trait_THRESH_SPIDER ("THRESH_SPIDER")
static const trait_id trait_URSINE_FUR ("URSINE_FUR")
static const trait_id trait_VOMITOUS ("VOMITOUS")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
static const trait_id trait_WEAKSTOMACH ("WEAKSTOMACH")
static const trait_id trait_WEBBED ("WEBBED")
static const trait_id trait_WEB_SPINNER ("WEB_SPINNER")
static const trait_id trait_WEB_WALKER ("WEB_WALKER")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
static const trait_id trait_WHISKERS_RAT ("WHISKERS_RAT")
static const trait_id trait_WHISKERS ("WHISKERS")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_gun ("gun")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_weapon ("weapon")
static const bionic_id bio_cloak ("bio_cloak")
static const bionic_id bio_cqb ("bio_cqb")
static const bionic_id bio_ground_sonar ("bio_ground_sonar")
static const bionic_id bio_soporific ("bio_soporific")
static const bionic_id bio_speed ("bio_speed")
static const bionic_id bio_syringe ("bio_syringe")
static const bionic_id bio_uncanny_dodge ("bio_uncanny_dodge")
static const std::vector< matype_id > bio_cqb_styles
Function Documentation
calc_fatigue_cap()
int calc_fatigue_cap (int fatigue)
Calculates the player's morale cap due to fatigue.
Definition at line 4146 of file player.cpp.
{
    if( fatigue >= fatigue_levels::massive ) {
        return 20;
    } else if( fatigue >= fatigue_levels::exhausted ) {
        return 40;
    } else if( fatigue >= fatigue_levels::dead_tired ) {
        return 60;
    } else if( fatigue >= fatigue_levels::tired ) {
        return 80;
    }
    return 0;
}
References dead_tired, exhausted, massive, and tired.
Referenced by player::calc_focus_equilibrium(), and avatar::disp_morale().
encumb_color()
nc_color encumb_color (int level)
Definition at line 4032 of file player.cpp.
{
    if( level < 0 ) {
        return c_green;
    }
    if( level < 10 ) {
        return c_light_gray;
    }
    if( level < 40 ) {
        return c_yellow;
    }
    if( level < 70 ) {
        return c_light_red;
    }
    return c_red;
}
References c_green, c_light_gray, c_light_red, c_red, and c_yellow.
Referenced by character_display::print_encumbrance().
flag_RESTRICT_HAND()
static const std::string flag_RESTRICT_HAND ("RESTRICT_HANDS") static
Referenced by player::can_wield().
flag_SPLINT()
static const std::string flag_SPLINT ("SPLINT") static
Referenced by player::use().
has_mod()
static bool has_mod (const item & gun, const item & mod) static
Definition at line 3286 of file player.cpp.
{
    for( const item *toolmod : gun.gunmods() ) {
        if( &mod == toolmod ) {
            return true;
        }
    }
    return false;
}
References item::gunmods().
Referenced by player::gunmod_remove().
is_pet_food()
static bool is_pet_food (const item & itm) static
Definition at line 3202 of file player.cpp.
{
    return itm.type->can_use( "DOGFOOD" ) ||
           itm.type->can_use( "CATFOOD" ) ||
           itm.type->can_use( "BIRDFOOD" ) ||
           itm.type->can_use( "CATTLEFODDER" );
}
References itype::can_use(), and item::type.
Referenced by player::use().
query_consume_ownership()
static bool query_consume_ownership (item & target, player & p) static
Definition at line 1838 of file player.cpp.
{
    if( !target.is_owned_by( p, true ) ) {
        bool choice = true;
        if( p.get_value( "THIEF_MODE" ) == "THIEF_ASK" ) {
            choice = pickup::query_thief();
        }
        if( p.get_value( "THIEF_MODE" ) == "THIEF_HONEST" || !choice ) {
            return false;
        }
        std::vector<npc *> witnesses;
        for( npc &elem : g->all_npcs() ) {
            if( rl_dist( elem.pos(), p.pos() ) < MAX_VIEW_DISTANCE && elem.sees( p.pos() ) ) {
                witnesses.push_back( &elem );
            }
        }
        for( npc *elem : witnesses ) {
            elem->say( "<witnessed_thievery>", 7 );
        }
        if( !witnesses.empty() && target.is_owned_by( p, true ) ) {
            if( p.add_faction_warning( target.get_owner() ) ) {
                for( npc *elem : witnesses ) {
                    elem->make_angry();
                }
            }
        }
    }
    return true;
}
References player::add_faction_warning(), g, item::get_owner(), Creature::get_value(), item::is_owned_by(), MAX_VIEW_DISTANCE, Character::pos(), pickup::query_thief(), and rl_dist().
Referenced by player::consume_item().
Variable Documentation
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
Referenced by player::calc_focus_equilibrium().
bio_cloak
const bionic_id bio_cloak("bio_cloak") ("bio_cloak") static
Referenced by player::basic_symbol_color().
bio_cqb
const bionic_id bio_cqb("bio_cqb") ("bio_cqb") static
Referenced by character_martial_arts::pick_style().
bio_cqb_styles
const std::vector<matype_id> bio_cqb_styles static
Initial value:
{ {
        matype_id{ "style_aikido" },
        matype_id{ "style_biojutsu" },
        matype_id{ "style_boxing" },
        matype_id{ "style_capoeira" },
        matype_id{ "style_crane" },
        matype_id{ "style_dragon" },
        matype_id{ "style_judo" },
        matype_id{ "style_karate" },
        matype_id{ "style_krav_maga" },
        matype_id{ "style_leopard" },
        matype_id{ "style_muay_thai" },
        matype_id{ "style_ninjutsu" },
        matype_id{ "style_pankration" },
        matype_id{ "style_snake" },
        matype_id{ "style_taekwondo" },
        matype_id{ "style_tai_chi" },
        matype_id{ "style_tiger" },
        matype_id{ "style_wingchun" },
        matype_id{ "style_zui_quan" }
    }}
Definition at line 2405 of file player.cpp.
Referenced by character_martial_arts::pick_style().
bio_ground_sonar
const bionic_id bio_ground_sonar("bio_ground_sonar") ("bio_ground_sonar") static
Referenced by player::search_surroundings().
bio_soporific
const bionic_id bio_soporific("bio_soporific") ("bio_soporific") static
Referenced by player::can_sleep(), player::sleep_spot(), and player::try_to_sleep().
bio_speed
const bionic_id bio_speed("bio_speed") ("bio_speed") static
Referenced by player::recalc_speed_bonus().
bio_syringe
const bionic_id bio_syringe("bio_syringe") ("bio_syringe") static
Referenced by player::consume_med().
bio_uncanny_dodge
const bionic_id bio_uncanny_dodge("bio_uncanny_dodge") ("bio_uncanny_dodge") static
Referenced by player::uncanny_dodge().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by player::get_perceived_pain().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by player::on_hit().
effect_bloodworms
const efftype_id effect_bloodworms("bloodworms") ("bloodworms") static
Referenced by player::process_effects_internal().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by player::basic_symbol_color().
effect_brainworms
const efftype_id effect_brainworms("brainworms") ("brainworms") static
Referenced by player::process_effects_internal().
effect_darkness
const efftype_id effect_darkness("darkness") ("darkness") static
Referenced by player::process_effects_internal().
effect_depressants
const efftype_id effect_depressants("depressants") ("depressants") static
Referenced by player::reset_stats().
effect_dermatik
const efftype_id effect_dermatik("dermatik") ("dermatik") static
Referenced by player::process_effects_internal().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by npc::add_msg_player_or_say(), player::impact(), player::on_hit(), and player::pause().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by player::intimidation().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by player::process_effects_internal().
effect_happy
const efftype_id effect_happy("happy") ("happy") static
Referenced by player::reset_stats().
effect_irradiated
const efftype_id effect_irradiated("irradiated") ("irradiated") static
Referenced by player::reset_stats().
effect_masked_scent
const efftype_id effect_masked_scent("masked_scent") ("masked_scent") static
Referenced by player::process_turn().
effect_meth
const efftype_id effect_meth("meth") ("meth") static
Referenced by player::can_sleep().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by player::mod_pain(), and player::process_turn().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by player::vomit_mod().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by player::basic_symbol_color(), and player::pause().
effect_paincysts
const efftype_id effect_paincysts("paincysts") ("paincysts") static
Referenced by player::process_effects_internal().
effect_pkill
const efftype_id effect_pkill("pkill") ("pkill") static
Referenced by player::reset_stats().
effect_sad
const efftype_id effect_sad("sad") ("sad") static
Referenced by player::reset_stats().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by player::process_turn().
effect_sleep_deprived
const efftype_id effect_sleep_deprived("sleep_deprived") ("sleep_deprived") static
Referenced by player::reset_stats().
effect_stim
const efftype_id effect_stim("stim") ("stim") static
Referenced by player::reset_stats().
effect_stim_overdose
const efftype_id effect_stim_overdose("stim_overdose") ("stim_overdose") static
Referenced by player::reset_stats().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by player::basic_symbol_color(), player::knock_back_to(), and player::on_hit().
effect_tapeworm
const efftype_id effect_tapeworm("tapeworm") ("tapeworm") static
Referenced by player::process_effects_internal().
effect_thirsty
const efftype_id effect_thirsty("thirsty") ("thirsty") static
Referenced by player::reset_stats().
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by player::vomit_mod().
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
Referenced by player::process_items().
itype_battery
const itype_id itype_battery("battery") ("battery") static
itype_brass_catcher
const itype_id itype_brass_catcher("brass_catcher") ("brass_catcher") static
Referenced by player::gunmod_remove().
itype_large_repairkit
const itype_id itype_large_repairkit("large_repairkit") ("large_repairkit") static
Referenced by player::gunmod_add().
itype_plut_cell
const itype_id itype_plut_cell("plut_cell") ("plut_cell") static
Referenced by player::unload().
itype_small_repairkit
const itype_id itype_small_repairkit("small_repairkit") ("small_repairkit") static
Referenced by player::gunmod_add().
itype_syringe
const itype_id itype_syringe("syringe") ("syringe") static
Referenced by player::consume_med().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by player::process_items().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by player::process_items().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by player::avoid_trap(), player::fall_damage_mod(), and player::on_dodge().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by player::item_reload_cost(), and player::rate_action_use().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by player::pause().
skill_weapon
const skill_id skill_weapon("weapon") ("weapon") static
Referenced by player::gunmod_installation_odds().
trait_ACIDBLOOD
const trait_id trait_ACIDBLOOD("ACIDBLOOD") ("ACIDBLOOD") static
Referenced by player::process_effects_internal().
trait_ARACHNID_ARMS
const trait_id trait_ARACHNID_ARMS("ARACHNID_ARMS") ("ARACHNID_ARMS") static
Referenced by player::reset_stats().
trait_ARACHNID_ARMS_OK
const trait_id trait_ARACHNID_ARMS_OK("ARACHNID_ARMS_OK") ("ARACHNID_ARMS_OK") static
Referenced by player::reset_stats().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by player::calc_focus_equilibrium().
trait_CF_HAIR
const trait_id trait_CF_HAIR("CF_HAIR") ("CF_HAIR") static
Referenced by player::on_hit().
trait_CHITIN2
const trait_id trait_CHITIN2("CHITIN2") ("CHITIN2") static
Referenced by player::reset_stats().
trait_CHITIN3
const trait_id trait_CHITIN3("CHITIN3") ("CHITIN3") static
Referenced by player::reset_stats().
trait_CHITIN_FUR
const trait_id trait_CHITIN_FUR("CHITIN_FUR") ("CHITIN_FUR") static
Referenced by player::update_body_wetness().
trait_CHITIN_FUR2
const trait_id trait_CHITIN_FUR2("CHITIN_FUR2") ("CHITIN_FUR2") static
Referenced by player::update_body_wetness().
trait_CHITIN_FUR3
const trait_id trait_CHITIN_FUR3("CHITIN_FUR3") ("CHITIN_FUR3") static
Referenced by player::reset_stats(), and player::update_body_wetness().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by player::try_to_sleep().
trait_COLDBLOOD4
const trait_id trait_COLDBLOOD4("COLDBLOOD4") ("COLDBLOOD4") static
Referenced by player::recalc_speed_bonus().
trait_COMPOUND_EYES
const trait_id trait_COMPOUND_EYES("COMPOUND_EYES") ("COMPOUND_EYES") static
Referenced by player::reset_stats().
trait_DEBUG_BIONIC_POWER
const trait_id trait_DEBUG_BIONIC_POWER("DEBUG_BIONIC_POWER") ("DEBUG_BIONIC_POWER") static
Referenced by player::process_turn().
trait_DEBUG_CLOAK
const trait_id trait_DEBUG_CLOAK("DEBUG_CLOAK") ("DEBUG_CLOAK") static
Referenced by player::basic_symbol_color().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by player::gunmod_add(), player::gunmod_installation_odds(), player::mend_item(), and player::toolmod_add().
trait_DEBUG_NODMG
const trait_id trait_DEBUG_NODMG("DEBUG_NODMG") ("DEBUG_NODMG") static
Referenced by player::immune_to().
trait_DEFT
const trait_id trait_DEFT("DEFT") ("DEFT") static
Referenced by player::on_hit().
trait_EASYSLEEPER
const trait_id trait_EASYSLEEPER("EASYSLEEPER") ("EASYSLEEPER") static
Referenced by player::sleep_spot().
trait_EASYSLEEPER2
const trait_id trait_EASYSLEEPER2("EASYSLEEPER2") ("EASYSLEEPER2") static
Referenced by player::sleep_spot().
trait_EATHEALTH
const trait_id trait_EATHEALTH("EATHEALTH") ("EATHEALTH") static
Referenced by player::process_effects_internal().
trait_FAT
const trait_id trait_FAT("FAT") ("FAT") static
Referenced by player::process_one_effect().
trait_FELINE_FUR
const trait_id trait_FELINE_FUR("FELINE_FUR") ("FELINE_FUR") static
Referenced by player::update_body_wetness().
trait_FUR
const trait_id trait_FUR("FUR") ("FUR") static
Referenced by player::update_body_wetness().
trait_INSECT_ARMS
const trait_id trait_INSECT_ARMS("INSECT_ARMS") ("INSECT_ARMS") static
Referenced by player::reset_stats().
trait_INSECT_ARMS_OK
const trait_id trait_INSECT_ARMS_OK("INSECT_ARMS_OK") ("INSECT_ARMS_OK") static
Referenced by player::reset_stats().
trait_INSOMNIA
const trait_id trait_INSOMNIA("INSOMNIA") ("INSOMNIA") static
Referenced by player::sleep_spot().
trait_LIGHTFUR
const trait_id trait_LIGHTFUR("LIGHTFUR") ("LIGHTFUR") static
Referenced by player::update_body_wetness().
trait_LUPINE_FUR
const trait_id trait_LUPINE_FUR("LUPINE_FUR") ("LUPINE_FUR") static
Referenced by player::update_body_wetness().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by player::process_effects_internal().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by player::try_to_sleep().
trait_MOREPAIN
const trait_id trait_MOREPAIN("MORE_PAIN") ("MORE_PAIN") static
Referenced by player::mod_pain().
trait_MOREPAIN2
const trait_id trait_MOREPAIN2("MORE_PAIN2") ("MORE_PAIN2") static
Referenced by player::mod_pain().
trait_MOREPAIN3
const trait_id trait_MOREPAIN3("MORE_PAIN3") ("MORE_PAIN3") static
Referenced by player::mod_pain().
trait_NAUSEA
const trait_id trait_NAUSEA("NAUSEA") ("NAUSEA") static
Referenced by player::vomit_mod().
trait_NOMAD
const trait_id trait_NOMAD("NOMAD") ("NOMAD") static
Referenced by player::process_turn().
trait_NOMAD2
const trait_id trait_NOMAD2("NOMAD2") ("NOMAD2") static
Referenced by player::process_turn().
trait_NOMAD3
const trait_id trait_NOMAD3("NOMAD3") ("NOMAD3") static
Referenced by player::process_turn().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by player::add_pain_msg(), and player::mod_pain().
trait_PACIFIST
const trait_id trait_PACIFIST("PACIFIST") ("PACIFIST") static
Referenced by player::practice().
trait_PAINRESIST
const trait_id trait_PAINRESIST("PAINRESIST") ("PAINRESIST") static
Referenced by player::mod_pain().
trait_PAINRESIST_TROGLO
const trait_id trait_PAINRESIST_TROGLO("PAINRESIST_TROGLO") ("PAINRESIST_TROGLO") static
Referenced by player::mod_pain().
trait_PARAIMMUNE
const trait_id trait_PARAIMMUNE("PARAIMMUNE") ("PARAIMMUNE") static
Referenced by player::process_effects_internal().
trait_PARKOUR
const trait_id trait_PARKOUR("PARKOUR") ("PARKOUR") static
Referenced by player::fall_damage_mod().
trait_PROF_SKATER
const trait_id trait_PROF_SKATER("PROF_SKATER") ("PROF_SKATER") static
Referenced by player::on_hit().
trait_QUILLS
const trait_id trait_QUILLS("QUILLS") ("QUILLS") static
Referenced by player::on_hit().
trait_SAVANT
const trait_id trait_SAVANT("SAVANT") ("SAVANT") static
Referenced by player::practice().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by player::try_to_sleep().
trait_SLIMY
const trait_id trait_SLIMY("SLIMY") ("SLIMY") static
Referenced by player::update_body_wetness().
trait_SPINES
const trait_id trait_SPINES("SPINES") ("SPINES") static
Referenced by player::on_hit().
trait_STIMBOOST
const trait_id trait_STIMBOOST("STIMBOOST") ("STIMBOOST") static
Referenced by player::reset_stats().
trait_STRONGSTOMACH
const trait_id trait_STRONGSTOMACH("STRONGSTOMACH") ("STRONGSTOMACH") static
Referenced by player::vomit_mod().
trait_SUNLIGHT_DEPENDENT
const trait_id trait_SUNLIGHT_DEPENDENT("SUNLIGHT_DEPENDENT") ("SUNLIGHT_DEPENDENT") static
Referenced by player::recalc_speed_bonus().
trait_THICK_SCALES
const trait_id trait_THICK_SCALES("THICK_SCALES") ("THICK_SCALES") static
Referenced by player::reset_stats().
trait_THORNS
const trait_id trait_THORNS("THORNS") ("THORNS") static
Referenced by player::on_hit().
trait_THRESH_SPIDER
const trait_id trait_THRESH_SPIDER("THRESH_SPIDER") ("THRESH_SPIDER") static
Referenced by player::try_to_sleep().
trait_URSINE_FUR
const trait_id trait_URSINE_FUR("URSINE_FUR") ("URSINE_FUR") static
Referenced by player::update_body_wetness().
trait_VOMITOUS
const trait_id trait_VOMITOUS("VOMITOUS") ("VOMITOUS") static
Referenced by player::vomit_mod().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by player::consume_item(), player::sleep_spot(), and player::try_to_sleep().
trait_WEAKSTOMACH
const trait_id trait_WEAKSTOMACH("WEAKSTOMACH") ("WEAKSTOMACH") static
Referenced by player::vomit_mod().
trait_WEB_SPINNER
const trait_id trait_WEB_SPINNER("WEB_SPINNER") ("WEB_SPINNER") static
Referenced by player::try_to_sleep().
trait_WEB_WALKER
const trait_id trait_WEB_WALKER("WEB_WALKER") ("WEB_WALKER") static
Referenced by player::try_to_sleep().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by player::try_to_sleep().
trait_WEBBED
const trait_id trait_WEBBED("WEBBED") ("WEBBED") static
Referenced by player::reset_stats().
trait_WHISKERS
const trait_id trait_WHISKERS("WHISKERS") ("WHISKERS") static
Referenced by player::reset_stats().
trait_WHISKERS_RAT
const trait_id trait_WHISKERS_RAT("WHISKERS_RAT") ("WHISKERS_RAT") static
Referenced by player::reset_stats().