Cataclysm BN: src/player_activity.cpp File Reference
player_activity.cpp File Reference
#include "player_activity.h"
#include <algorithm>
#include <array>
#include <map>
#include <memory>
#include <utility>
#include "activity_actor.h"
#include "activity_handlers.h"
#include "activity_type.h"
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "color.h"
#include "construction.h"
#include "construction_partial.h"
#include "crafting.h"
#include "distraction_manager.h"
#include "item.h"
#include "itype.h"
#include "map.h"
#include "player.h"
#include "recipe.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "value_ptr.h"
Functions
static std::string craft_progress_message (const avatar &u, const player_activity &act)
template<typename T >
bool containers_equal (const T &left, const T &right)
Variables
static const activity_id ACT_FIRSTAID ("ACT_FIRSTAID")
static const activity_id ACT_GAME ("ACT_GAME")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_START_FIRE ("ACT_START_FIRE")
static const activity_id ACT_HAND_CRANK ("ACT_HAND_CRANK")
static const activity_id ACT_VIBE ("ACT_VIBE")
static const activity_id ACT_OXYTORCH ("ACT_OXYTORCH")
static const activity_id ACT_FISH ("ACT_FISH")
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_GUNMOD_ADD ("ACT_GUNMOD_ADD")
Function Documentation
containers_equal()
template<typename T > bool containers_equal (const T & left, const T & right)
Definition at line 382 of file player_activity.cpp.
{
    if( left.size() != right.size() ) {
        return false;
    }
    return std::equal( left.begin(), left.end(), right.begin() );
}
References align::right.
craft_progress_message()
static std::string craft_progress_message (const avatar & u, const player_activity & act) static
Definition at line 121 of file player_activity.cpp.
{
    const item *craft = act.targets.front().get_item();
    if( craft == nullptr ) {
        // Should never happen (?)
        return string_format( _( "%s…" ), act.get_verb().translated() );
    }
    // Horrid copypaste warning! TODO: Functions
    const recipe &rec = craft->get_making();
    const tripoint bench_pos = act.coords.front();
    // Ugly
    bench_type bench_t = bench_type( act.values[1] );
    const bench_location bench{bench_t, bench_pos};
    const float light_mult = lighting_crafting_speed_multiplier( u, rec );
    const float bench_mult = workbench_crafting_speed_multiplier( *craft, bench );
    const float morale_mult = morale_crafting_speed_multiplier( u, rec );
    const int assistants = u.available_assistant_count( craft->get_making() );
    const float base_total_moves = std::max( 1, rec.batch_time( craft->charges, 1.0f, 0 ) );
    const float assist_total_moves = std::max( 1, rec.batch_time( craft->charges, 1.0f, assistants ) );
    const float assist_mult = base_total_moves / assist_total_moves;
    const float speed_mult = u.get_speed() / 100.0f;
    const float total_mult = light_mult * bench_mult * morale_mult * assist_mult * speed_mult;
    const double remaining_percentage = 1.0 - craft->item_counter / 10'000'000.0;
    int remaining_turns = remaining_percentage * base_total_moves / 100 / std::max( 0.01f, total_mult );
    std::string time_desc = string_format( _( "Time left: %s" ),
                                           to_string( time_duration::from_turns( remaining_turns ) ) );
    const std::array<std::pair<float, std::string>, 6> mults_with_data = {{
            { total_mult, _( "Total" ) },
            { speed_mult, _( "Speed" ) },
            { light_mult, _( "Light" ) },
            { bench_mult, _( "Workbench" ) },
            { morale_mult, _( "Morale" ) },
            { assist_mult, _( "Assistants" ) },
        }
    };
    std::string mults_desc = _( "Crafting speed multipliers:\n" );
    // Hack to make sure total always shows
    bool first = true;
    for( const std::pair<float, std::string> &p : mults_with_data ) {
        int percent = static_cast<int>( p.first * 100 );
        if( first || percent != 100 ) {
            nc_color col = percent > 100 ? c_green : c_red;
            std::string colorized = colorize( std::to_string( percent ) + '%', col );
            mults_desc += string_format( _( "%s: %s\n" ), p.second, colorized );
        }
        first = false;
    }
    return string_format( _( "%s: %s\n\n%s\n\n%s" ), act.get_verb().translated(), craft->tname(),
                          time_desc,
                          mults_desc );
}
References _, act, player::available_assistant_count(), recipe::batch_time(), c_green, c_red, colorize(), iuse::craft(), time_duration::from_turns(), Character::get_speed(), lighting_crafting_speed_multiplier(), morale_crafting_speed_multiplier(), string_format(), to_string(), and workbench_crafting_speed_multiplier().
Referenced by player_activity::get_progress_message().
Variable Documentation
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
Referenced by player_activity::migrate_item_position().
ACT_FIRSTAID
const activity_id ACT_FIRSTAID("ACT_FIRSTAID") ("ACT_FIRSTAID") static
Referenced by player_activity::migrate_item_position().
ACT_FISH
const activity_id ACT_FISH("ACT_FISH") ("ACT_FISH") static
Referenced by player_activity::migrate_item_position().
ACT_GAME
const activity_id ACT_GAME("ACT_GAME") ("ACT_GAME") static
Referenced by player_activity::migrate_item_position().
ACT_GUNMOD_ADD
const activity_id ACT_GUNMOD_ADD("ACT_GUNMOD_ADD") ("ACT_GUNMOD_ADD") static
Referenced by player_activity::migrate_item_position().
ACT_HAND_CRANK
const activity_id ACT_HAND_CRANK("ACT_HAND_CRANK") ("ACT_HAND_CRANK") static
Referenced by player_activity::migrate_item_position().
ACT_OXYTORCH
const activity_id ACT_OXYTORCH("ACT_OXYTORCH") ("ACT_OXYTORCH") static
Referenced by player_activity::migrate_item_position().
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
Referenced by player_activity::migrate_item_position().
ACT_START_FIRE
const activity_id ACT_START_FIRE("ACT_START_FIRE") ("ACT_START_FIRE") static
Referenced by player_activity::migrate_item_position().
ACT_VIBE
const activity_id ACT_VIBE("ACT_VIBE") ("ACT_VIBE") static
Referenced by player_activity::migrate_item_position().