Cataclysm BN: src/point.cpp File Reference
point.cpp File Reference
#include "point.h"
#include <algorithm>
#include <sstream>
#include <utility>
#include "cata_utility.h"
Functions
std::ostream & operator<< (std::ostream &os, const point &pos)
std::ostream & operator<< (std::ostream &os, const tripoint &pos)
std::vector< tripoint > closest_points_first (const tripoint &center, int max_dist)
Following functions return points in a spiral pattern starting at center_x/center_y until it hits the radius.
std::vector< tripoint > closest_points_first (const tripoint &center, int min_dist, int max_dist)
std::vector< point > closest_points_first (const point &center, int max_dist)
std::vector< point > closest_points_first (const point &center, int min_dist, int max_dist)
Function Documentation
closest_points_first() [1/4]
std::vector< point > closest_points_first (const point & center, int max_dist)
Definition at line 52 of file point.cpp.
{
    return closest_points_first( center, 0, max_dist );
}
References center, and closest_points_first().
closest_points_first() [2/4]
std::vector< point > closest_points_first (const point & center, int min_dist, int max_dist)
Definition at line 57 of file point.cpp.
{
    min_dist = std::max( min_dist, 0 );
    max_dist = std::max( max_dist, 0 );
    if( min_dist > max_dist ) {
        return {};
    }
    const int min_edge = min_dist * 2 + 1;
    const int max_edge = max_dist * 2 + 1;
    const int n = max_edge * max_edge - ( min_edge - 2 ) * ( min_edge - 2 );
    const bool is_center_included = min_dist == 0;
    std::vector<point> result;
    result.reserve( n + ( is_center_included ? 1 : 0 ) );
    if( is_center_included ) {
        result.push_back( center );
    }
    int x = std::max( min_dist, 1 );
    int y = 1 - x;
    int dx = 1;
    int dy = 0;
    for( int i = 0; i < n; i++ ) {
        result.push_back( center + point{ x, y } );
        if( x == y || ( x < 0 && x == -y ) || ( x > 0 && x == 1 - y ) ) {
            std::swap( dx, dy );
            dx = -dx;
        }
        x += dx;
        y += dy;
    }
    return result;
}
References center, and cata::swap().
closest_points_first() [3/4]
std::vector< tripoint > closest_points_first (const tripoint & center, int max_dist)
Following functions return points in a spiral pattern starting at center_x/center_y until it hits the radius.
Clockwise fashion. Credit to Tom J Nowell; http://stackoverflow.com/a/1555236/1269969
Definition at line 33 of file point.cpp.
{
    return closest_points_first( center, 0, max_dist );
}
References center, and closest_points_first().
Referenced by closest_points_first().
closest_points_first() [4/4]
std::vector< tripoint > closest_points_first (const tripoint & center, int min_dist, int max_dist)
Definition at line 38 of file point.cpp.
{
    const std::vector<point> points = closest_points_first( center.xy(), min_dist, max_dist );
    std::vector<tripoint> result;
    result.reserve( points.size() );
    for( const point &p : points ) {
        result.emplace_back( p, center.z );
    }
    return result;
}
References center, and closest_points_first().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const point & pos)
Definition at line 23 of file point.cpp.
{
    return os << "(" << pos.x << "," << pos.y << ")";
}
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const tripoint & pos)
Definition at line 28 of file point.cpp.
{
    return os << "(" << pos.x << "," << pos.y << "," << pos.z << ")";
}