Cataclysm BN: src/projectile.cpp File Reference
projectile.cpp File Reference
#include "projectile.h"
#include <algorithm>
#include <memory>
#include <utility>
#include <vector>
#include "ammo_effect.h"
#include "explosion.h"
#include "game.h"
#include "json.h"
#include "item.h"
#include "map.h"
#include "map_iterator.h"
#include "rng.h"
#include "string_id.h"
Functions
void apply_ammo_effects (const tripoint &p, const std::set< ammo_effect_str_id > &effects, Creature *source)
void apply_ammo_effects (const tripoint &p, const std::set< std::string > &effects, Creature *source)
static int aoe_of (const ammo_effect_str_id &ae_id)
static int aoe_of (const std::string &s)
int max_aoe_size (const std::set< ammo_effect_str_id > &tags)
int max_aoe_size (const std::set< std::string > &tags)
Function Documentation
aoe_of() [1/2]
static int aoe_of (const ammo_effect_str_id & ae_id) static
Definition at line 150 of file projectile.cpp.
{
    return std::max( ae_id->aoe_size, ae_id->aoe_explosion_data.safe_range() - 1 );
}
Referenced by max_aoe_size().
aoe_of() [2/2]
static int aoe_of (const std::string & s) static
Definition at line 155 of file projectile.cpp.
{
    ammo_effect_str_id ae_id( s );
    if( ae_id.is_valid() ) {
        return std::max( ae_id->aoe_size, ae_id->aoe_explosion_data.safe_range() - 1 );
    } else {
        return 0;
    }
}
References string_id< T >::is_valid().
apply_ammo_effects() [1/2]
void apply_ammo_effects (const tripoint & p, const std::set< ammo_effect_str_id > & effects, Creature * source)
Definition at line 110 of file projectile.cpp.
{
    map &here = get_map();
    for( const ammo_effect_str_id &ae_id : effects ) {
        const ammo_effect &ae = *ae_id;
        if( ae.aoe_field_type )
            for( auto &pt : g->m.points_in_radius( p, ae.aoe_radius, ae.aoe_radius_z ) ) {
                if( x_in_y( ae.aoe_chance, 100 ) ) {
                    const bool check_sees = !ae.aoe_check_sees || here.sees( p, pt, ae.aoe_check_sees_radius );
                    const bool check_passable = !ae.aoe_check_passable || here.passable( pt );
                    if( check_sees && check_passable ) {
                        here.add_field( pt, ae.aoe_field_type, rng( ae.aoe_intensity_min, ae.aoe_intensity_max ) );
                    }
                }
            }
        if( ae.aoe_explosion_data ) {
            explosion_handler::explosion( p, ae.aoe_explosion_data, source );
        }
        if( ae.do_flashbang ) {
            explosion_handler::flashbang( p, false, "explosion" );
        }
        if( ae.do_emp_blast ) {
            explosion_handler::emp_blast( p );
        }
    }
}
References map::add_field(), ammo_effect::aoe_chance, ammo_effect::aoe_check_passable, ammo_effect::aoe_check_sees, ammo_effect::aoe_check_sees_radius, ammo_effect::aoe_explosion_data, ammo_effect::aoe_field_type, ammo_effect::aoe_intensity_max, ammo_effect::aoe_intensity_min, ammo_effect::aoe_radius, ammo_effect::aoe_radius_z, ammo_effect::do_emp_blast, ammo_effect::do_flashbang, explosion_handler::emp_blast(), explosion_handler::explosion(), explosion_handler::flashbang(), g, get_map(), map::passable(), rng(), map::sees(), and x_in_y().
Referenced by apply_ammo_effects(), item::detonate(), and projectile_attack().
apply_ammo_effects() [2/2]
void apply_ammo_effects (const tripoint & p, const std::set< std::string > & effects, Creature * source)
Definition at line 138 of file projectile.cpp.
{
    std::set<ammo_effect_str_id> effect_ids;
    for( const std::string &s : effects ) {
        ammo_effect_str_id id( s );
        if( id.is_valid() ) {
            effect_ids.emplace( id );
        }
    }
    apply_ammo_effects( p, effect_ids, source );
}
References apply_ammo_effects(), int_id< T >::id(), and int_id< T >::is_valid().
max_aoe_size() [1/2]
int max_aoe_size (const std::set< ammo_effect_str_id > & tags)
Definition at line 165 of file projectile.cpp.
{
    int ret = 0;
    for( const ammo_effect_str_id &ae_id : tags ) {
        ret = std::max( ret, aoe_of( ae_id ) );
    }
    return ret;
}
References aoe_of(), and cata::hash64_detail::ret.
Referenced by vehicle::automatic_fire_turret().
max_aoe_size() [2/2]
int max_aoe_size (const std::set< std::string > & tags)
Definition at line 174 of file projectile.cpp.
{
    int aoe_size = 0;
    for( const std::string &s : tags ) {
        aoe_size = std::max( aoe_size, aoe_of( s ) );
    }
    return aoe_size;
}
References aoe_of().