Cataclysm BN: src/ranged.cpp File Reference
ranged.cpp File Reference
#include "ranged.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "avatar.h"
#include "ballistics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "creature.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "game.h"
#include "game_constants.h"
#include "gun_mode.h"
#include "input.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "material.h"
#include "math_defines.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "output.h"
#include "panels.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "projectile.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui_manager.h"
#include "units.h"
#include "units_angle.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
class target_ui
struct target_ui::turret_with_lof
struct confidence_rating
Namespaces
namespace ranged
Typedefs
using ammo_effect_str_id = string_id< ammo_effect >
using RatingVector = std::vector< std::tuple< double, char, std::string > >
Functions
static const std::string flag_CONSUMABLE ("CONSUMABLE")
static const std::string flag_FIRE_TWOHAND ("FIRE_TWOHAND")
static const std::string flag_MOUNTABLE ("MOUNTABLE")
static const std::string flag_MOUNTED_GUN ("MOUNTED_GUN")
static const std::string flag_NEVER_JAMS ("NEVER_JAMS")
static const std::string flag_NON_FOULING ("NON-FOULING")
static const std::string flag_PRIMITIVE_RANGED_WEAPON ("PRIMITIVE_RANGED_WEAPON")
static const std::string flag_PYROMANIAC_WEAPON ("PYROMANIAC_WEAPON")
static const std::string flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT")
static const std::string flag_RESTRICT_HANDS ("RESTRICT_HANDS")
static const std::string flag_STR_DRAW ("STR_DRAW")
static const std::string flag_UNDERWATER_GUN ("UNDERWATER_GUN")
static const std::string flag_VEHICLE ("VEHICLE")
static projectile make_gun_projectile (const item &gun)
int time_to_attack (const Character &p, const itype &firing)
static void cycle_action (item &weap, const tripoint &pos)
void make_gun_sound_effect (const player &p, bool burst, item *weapon)
bool can_use_bipod (const map &m, const tripoint &pos)
dispersion_sources calculate_dispersion (const map &m, const player &p, const item &gun, int at_recoil, bool burst)
static double occupied_tile_fraction (m_size target_size)
int range_with_even_chance_of_good_hit (int dispersion)
int ranged::throw_cost (const player &c, const item &to_throw)
float ranged::get_str_draw_penalty (const item &it, const Character &p)
Penalties potentially incurred by STR_DRAW weapons.
float ranged::str_draw_damage_modifier (const item &it, const Character &p)
float ranged::str_draw_dispersion_modifier (const item &it, const Character &p)
float ranged::str_draw_range_modifier (const item &it, const Character &p)
int ranged::throw_dispersion_per_dodge (const Character &c, bool add_encumbrance)
How much dispersion does one point of target's dodge add when throwing at said target?
int ranged::throwing_dispersion (const Character &c, const item &to_throw, Creature *critter, bool is_blind_throw)
Dispersion of a thrown item, against a given target, taking into account whether or not the throw was blind.
static void do_aim (player &p, const item &relevant, const double min_recoil)
static int print_steadiness (const catacurses::window &w, int line_number, double steadiness)
static double confidence_estimate (int range, double target_size, const dispersion_sources &dispersion)
static std::vector< aim_type > get_default_aim_type ()
static std::string get_colored_bar (const double val, const int width, const std::string &label, RatingVector::iterator begin, RatingVector::iterator end)
static int print_ranged_chance (const player &, const catacurses::window &w, int line_number, input_context &ctxt, const item &, const std::vector< aim_type > &aim_types, const std::function< dispersion_sources(const aim_type &)> &dispersion_fun, const std::function< int(const aim_type &)> &cost_fun, const std::vector< confidence_rating > &confidence_config, double range, double target_size)
static bool pl_sees (const Creature &cr)
static double calculate_aim_cap (const player &p, const tripoint &target)
static int print_aim (const player &p, const catacurses::window &w, int line_number, input_context &ctxt, const item &weapon, const double target_size, const tripoint &pos, double predicted_recoil)
static int draw_throw_aim (const player &p, const catacurses::window &w, int line_number, input_context &ctxt, const item &weapon, const tripoint &target_pos, bool is_blind_throw)
static bool is_driving (const player &p)
static double dispersion_from_skill (double skill, double weapon_dispersion)
std::vector< Creature * > ranged::targetable_creatures (const Character &c, const int range)
std::vector< Creature * > ranged::targetable_creatures (const Character &c, const int range, const turret_data &turret)
int ranged::burst_penalty (const Character &p, const item &gun, int gun_recoil)
Variables
static const ammo_effect_str_id ammo_effect_ACT_ON_RANGED_HIT ("ACT_ON_RANGED_HIT")
static const ammo_effect_str_id ammo_effect_BLACKPOWDER ("BLACKPOWDER")
static const ammo_effect_str_id ammo_effect_BOUNCE ("BOUNCE")
static const ammo_effect_str_id ammo_effect_BURST ("BURST")
static const ammo_effect_str_id ammo_effect_CUSTOM_EXPLOSION ("CUSTOM_EXPLOSION")
static const ammo_effect_str_id ammo_effect_EMP ("EMP")
static const ammo_effect_str_id ammo_effect_EXPLOSIVE ("EXPLOSIVE")
static const ammo_effect_str_id ammo_effect_HEAVY_HIT ("HEAVY_HIT")
static const ammo_effect_str_id ammo_effect_IGNITE ("IGNITE")
static const ammo_effect_str_id ammo_effect_LASER ("LASER")
static const ammo_effect_str_id ammo_effect_LIGHTNING ("LIGHTNING")
static const ammo_effect_str_id ammo_effect_NO_CRIT ("NO_CRIT")
static const ammo_effect_str_id ammo_effect_NO_EMBED ("NO_EMBED")
static const ammo_effect_str_id ammo_effect_NO_ITEM_DAMAGE ("NO_ITEM_DAMAGE")
static const ammo_effect_str_id ammo_effect_NON_FOULING ("NON-FOULING")
static const ammo_effect_str_id ammo_effect_PLASMA ("PLASMA")
static const ammo_effect_str_id ammo_effect_RECYCLED ("RECYCLED")
static const ammo_effect_str_id ammo_effect_SHATTER_SELF ("SHATTER_SELF")
static const ammo_effect_str_id ammo_effect_SHOT ("SHOT")
static const ammo_effect_str_id ammo_effect_TANGLE ("TANGLE")
static const ammo_effect_str_id ammo_effect_WHIP ("WHIP")
static const ammo_effect_str_id ammo_effect_WIDE ("WIDE")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_on_roof ("on_roof")
static const itype_id itype_12mm ("12mm")
static const itype_id itype_40x46mm ("40x46mm")
static const itype_id itype_40x53mm ("40x53mm")
static const itype_id itype_66mm ("66mm")
static const itype_id itype_84x246mm ("84x246mm")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_arrow ("arrow")
static const itype_id itype_bolt ("bolt")
static const itype_id itype_brass_catcher ("brass_catcher")
static const itype_id itype_flammable ("flammable")
static const itype_id itype_m235 ("m235")
static const itype_id itype_metal_rail ("metal_rail")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_UPS_off ("UPS_off")
static const trap_str_id tr_practice_target ("tr_practice_target")
static const fault_id fault_gun_blackpowder ("fault_gun_blackpowder")
static const fault_id fault_gun_chamber_spent ("fault_gun_chamber_spent")
static const fault_id fault_gun_dirt ("fault_gun_dirt")
static const fault_id fault_gun_unlubricated ("fault_gun_unlubricated")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_driving ("driving")
static const skill_id skill_gun ("gun")
static const skill_id skill_launcher ("launcher")
static const skill_id skill_throw ("throw")
static const bionic_id bio_railgun ("bio_railgun")
static const bionic_id bio_targeting ("bio_targeting")
static const bionic_id bio_ups ("bio_ups")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_NORANGEDCRIT ("NO_RANGED_CRIT")
static constexpr int AIF_DURATION_LIMIT = 10
Typedef Documentation
ammo_effect_str_id
using ammo_effect_str_id = string_id<ammo_effect>
Definition at line 75 of file ranged.cpp.
RatingVector
using RatingVector = std::vector<std::tuple<double, char, std::string> >
Definition at line 1336 of file ranged.cpp.
Function Documentation
calculate_aim_cap()
static double calculate_aim_cap (const player & p, const tripoint & target) static
Definition at line 1526 of file ranged.cpp.
{
    double min_recoil = 0.0;
    const Creature *victim = g->critter_at( target, true );
    // No p.sees_with_specials() here because special senses are not precise enough
    // to give creature's exact size & position, only which tile it occupies
    if( victim == nullptr || ( !p.sees( *victim ) && !p.sees_with_infrared( *victim ) ) ) {
        const int range = rl_dist( p.pos(), target );
        // Get angle of triangle that spans the target square.
        const double angle = atan2( 1, range );
        // Convert from radians to arcmin.
        min_recoil = 60 * 180 * angle / M_PI;
    }
    return min_recoil;
}
References atan2(), g, M_PI, Character::pos(), rl_dist(), Character::sees(), and Character::sees_with_infrared().
Referenced by target_ui::action_aim(), target_ui::action_aim_and_shoot(), and print_aim().
calculate_dispersion()
dispersion_sources calculate_dispersion (const map & m, const player & p, const item & gun, int at_recoil, bool burst)
Definition at line 794 of file ranged.cpp.
{
    bool bipod = can_use_bipod( m, p.pos() );
    int gun_recoil = gun.gun_recoil( bipod );
    int eff_recoil = at_recoil + ( burst ? ranged::burst_penalty( p, gun, gun_recoil ) : 0 );
    dispersion_sources dispersion( p.get_weapon_dispersion( gun ) );
    dispersion.add_range( eff_recoil );
    return dispersion;
}
References ranged::burst_penalty(), can_use_bipod(), player::get_weapon_dispersion(), item::gun_recoil(), and Character::pos().
Referenced by player::fire_gun(), and print_aim().
can_use_bipod()
bool can_use_bipod (const map & m, const tripoint & pos)
Definition at line 780 of file ranged.cpp.
{
    // usage of any attached bipod is dependent upon terrain
    if( m.has_flag_ter_or_furn( "MOUNTABLE", pos ) ) {
        return true;
    }
    if( const optional_vpart_position vp = m.veh_at( pos ) ) {
        return vp->vehicle().has_part( pos, "MOUNTABLE" );
    }
    return false;
}
References map::has_flag_ter_or_furn(), and map::veh_at().
Referenced by calculate_dispersion(), player::fire_gun(), and player::get_weapon_dispersion().
confidence_estimate()
static double confidence_estimate (int range, double target_size, const dispersion_sources & dispersion) static
Definition at line 1314 of file ranged.cpp.
{
    // This is a rough estimate of accuracy based on a linear distribution across min and max
    // dispersion.  It is highly inaccurate probability-wise.  The result gives the player
    // correct relative measures of chance to hit, and corresponds with the actual distribution at
    // min, max, and mean.
    if( range == 0 ) {
        return 2 * target_size;
    }
    const double max_lateral_offset =
        iso_tangent( range, units::from_arcmin( dispersion.max() ) );
    return 1 / ( max_lateral_offset / target_size );
}
References units::from_arcmin(), iso_tangent(), and dispersion_sources::max().
Referenced by print_ranged_chance().
cycle_action()
static void cycle_action (item & weap, const tripoint & pos) static
Definition at line 1722 of file ranged.cpp.
{
    map &here = get_map();
    // eject casings and linkages in random direction avoiding walls using player position as fallback
    std::vector<tripoint> tiles = closest_points_first( pos, 1 );
    tiles.erase( tiles.begin() );
    tiles.erase( std::remove_if( tiles.begin(), tiles.end(), [&pos, &here]( const tripoint & e ) {
        return !here.passable( e ) || here.obstructed_by_vehicle_rotation( pos, e );
    } ), tiles.end() );
    tripoint eject = tiles.empty() ? pos : random_entry( tiles );
    // for turrets try and drop casings or linkages directly to any CARGO part on the same tile
    const optional_vpart_position vp = here.veh_at( pos );
    std::vector<vehicle_part *> cargo;
    if( vp && weap.has_flag( "VEHICLE" ) ) {
        cargo = vp->vehicle().get_parts_at( pos, "CARGO", part_status_flag::any );
    }
    if( weap.ammo_data() && weap.ammo_data()->ammo->casing ) {
        const itype_id casing = *weap.ammo_data()->ammo->casing;
        if( weap.has_flag( "RELOAD_EJECT" ) || weap.gunmod_find( itype_brass_catcher ) ) {
            weap.put_in( item( casing ).set_flag( "CASING" ) );
        } else {
            if( cargo.empty() ) {
                here.add_item_or_charges( eject, item( casing ) );
            } else {
                vp->vehicle().add_item( *cargo.front(), item( casing ) );
            }
            sfx::play_variant_sound( "fire_gun", "brass_eject", sfx::get_heard_volume( eject ),
                                     sfx::get_heard_angle( eject ) );
        }
    }
    // some magazines also eject disintegrating linkages
    const auto mag = weap.magazine_current();
    if( mag && mag->type->magazine->linkage ) {
        item linkage( *mag->type->magazine->linkage, calendar::turn, 1 );
        if( weap.gunmod_find( itype_brass_catcher ) ) {
            linkage.set_flag( "CASING" );
            weap.put_in( linkage );
        } else if( cargo.empty() ) {
            here.add_item_or_charges( eject, linkage );
        } else {
            vp->vehicle().add_item( *cargo.front(), linkage );
        }
    }
}
References map::add_item_or_charges(), itype::ammo, item::ammo_data(), any, closest_points_first(), sfx::get_heard_angle(), sfx::get_heard_volume(), get_map(), item::gunmod_find(), item::has_flag(), itype_brass_catcher, item::magazine_current(), sfx::play_variant_sound(), item::put_in(), random_entry(), item::set_flag(), calendar::turn, and map::veh_at().
Referenced by player::fire_gun().
dispersion_from_skill()
static double dispersion_from_skill (double skill, double weapon_dispersion) static
Definition at line 1862 of file ranged.cpp.
{
    if( skill >= MAX_SKILL ) {
        return 0.0;
    }
    double skill_shortfall = double( MAX_SKILL ) - skill;
    double dispersion_penalty = 3 * skill_shortfall;
    double skill_threshold = 5;
    if( skill >= skill_threshold ) {
        double post_threshold_skill_shortfall = double( MAX_SKILL ) - skill;
        // Lack of mastery multiplies the dispersion of the weapon.
        return dispersion_penalty + ( weapon_dispersion * post_threshold_skill_shortfall * 1.25 ) /
               ( double( MAX_SKILL ) - skill_threshold );
    }
    // Unskilled shooters suffer greater penalties, still scaling with weapon penalties.
    double pre_threshold_skill_shortfall = skill_threshold - skill;
    dispersion_penalty += weapon_dispersion *
                          ( 1.25 + pre_threshold_skill_shortfall * 3.75 / skill_threshold );
    return dispersion_penalty;
}
References MAX_SKILL.
Referenced by player::get_weapon_dispersion().
do_aim()
static void do_aim (player & p, const item & relevant, const double min_recoil) static
Definition at line 1277 of file ranged.cpp.
{
    const double aim_amount = p.aim_per_move( relevant, p.recoil );
    if( aim_amount > 0 && p.recoil > min_recoil ) {
        // Increase aim at the cost of moves
        p.mod_moves( -1 );
        p.recoil = std::max( min_recoil, p.recoil - aim_amount );
    } else {
        // If aim is already maxed, we're just waiting, so pass the turn.
        p.set_moves( 0 );
    }
}
References Character::aim_per_move(), Creature::mod_moves(), Character::recoil, and Creature::set_moves().
Referenced by target_ui::action_aim(), and target_ui::action_aim_and_shoot().
draw_throw_aim()
static int draw_throw_aim (const player & p, const catacurses::window & w, int line_number, input_context & ctxt, const item & weapon, const tripoint & target_pos, bool is_blind_throw) static
Definition at line 1590 of file ranged.cpp.
{
    Creature *target = g->critter_at( target_pos, true );
    if( target != nullptr && !p.sees( *target ) ) {
        target = nullptr;
    }
    const dispersion_sources dispersion(
        ranged::throwing_dispersion( p, weapon, target, is_blind_throw ) );
    const double range = rl_dist( p.pos(), target_pos );
    const double target_size = target != nullptr ? target->ranged_target_size() : 1.0f;
    static const std::vector<confidence_rating> confidence_config_critter = {{
            { accuracy_critical, '*', "green", translate_marker_context( "aim_confidence", "Great" ) },
            { accuracy_standard, '+', "light_gray", translate_marker_context( "aim_confidence", "Normal" ) },
            { accuracy_grazing, '|', "magenta", translate_marker_context( "aim_confidence", "Graze" ) }
        }
    };
    static const std::vector<confidence_rating> confidence_config_object = {{
            { accuracy_grazing, '*', "white", translate_marker_context( "aim_confidence", "Hit" ) }
        }
    };
    const auto &confidence_config = target != nullptr ?
                                    confidence_config_critter : confidence_config_object;
    const auto dispersion_fun = [&]( const aim_type & ) {
        return dispersion;
    };
    const auto cost_fun = [&]( const aim_type & ) {
        return ranged::throw_cost( p, weapon );
    };
    return print_ranged_chance( p, w, line_number, ctxt,  weapon, get_default_aim_type(),
                                dispersion_fun, cost_fun,
                                confidence_config,
                                range, target_size );
}
References accuracy_critical, accuracy_grazing, accuracy_standard, g, get_default_aim_type(), Character::pos(), print_ranged_chance(), Creature::ranged_target_size(), rl_dist(), Character::sees(), ranged::throw_cost(), ranged::throwing_dispersion(), and translate_marker_context.
Referenced by target_ui::draw_ui_window().
flag_CONSUMABLE()
static const std::string flag_CONSUMABLE ("CONSUMABLE") static
Referenced by ranged::handle_gun_damage().
flag_FIRE_TWOHAND()
static const std::string flag_FIRE_TWOHAND ("FIRE_TWOHAND") static
Referenced by ranged::gunmode_checks_common().
flag_MOUNTABLE()
static const std::string flag_MOUNTABLE ("MOUNTABLE") static
Referenced by ranged::gunmode_checks_weapon().
flag_MOUNTED_GUN()
static const std::string flag_MOUNTED_GUN ("MOUNTED_GUN") static
Referenced by player::fire_gun(), player::get_weapon_dispersion(), and ranged::gunmode_checks_weapon().
flag_NEVER_JAMS()
static const std::string flag_NEVER_JAMS ("NEVER_JAMS") static
Referenced by ranged::handle_gun_damage().
flag_NON_FOULING()
static const std::string flag_NON_FOULING ("NON-FOULING") static
Referenced by ranged::handle_gun_damage().
flag_PRIMITIVE_RANGED_WEAPON()
static const std::string flag_PRIMITIVE_RANGED_WEAPON ("PRIMITIVE_RANGED_WEAPON") static
Referenced by ranged::handle_gun_damage().
flag_PYROMANIAC_WEAPON()
static const std::string flag_PYROMANIAC_WEAPON ("PYROMANIAC_WEAPON") static
Referenced by player::fire_gun().
flag_RELOAD_AND_SHOOT()
static const std::string flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT") static
Referenced by player::fire_gun(), ranged::gunmode_checks_weapon(), and target_ui::init_window_and_input().
flag_RESTRICT_HANDS()
static const std::string flag_RESTRICT_HANDS ("RESTRICT_HANDS") static
Referenced by ranged::gunmode_checks_common().
flag_STR_DRAW()
static const std::string flag_STR_DRAW ("STR_DRAW") static
Referenced by ranged::get_str_draw_penalty(), ranged::str_draw_damage_modifier(), ranged::str_draw_dispersion_modifier(), and ranged::str_draw_range_modifier().
flag_UNDERWATER_GUN()
static const std::string flag_UNDERWATER_GUN ("UNDERWATER_GUN") static
Referenced by player::get_weapon_dispersion().
flag_VEHICLE()
static const std::string flag_VEHICLE ("VEHICLE") static
Referenced by player::fire_gun().
get_colored_bar()
static std::string get_colored_bar (const double val, const int width, const std::string & label, RatingVector::iterator begin, RatingVector::iterator end) static
Definition at line 1337 of file ranged.cpp.
{
    std::string result;
    result.reserve( width );
    if( !label.empty() ) {
        result += label;
        result += ' ';
    }
    const int bar_width = width - utf8_width( result ) - 2; // - 2 for the brackets
    result += '[';
    if( bar_width > 0 ) {
        int used_width = 0;
        for( auto it( begin ); it != end; ++it ) {
            const double factor = std::min( 1.0, std::max( 0.0, std::get<0>( *it ) * val ) );
            const int seg_width = static_cast<int>( factor * bar_width ) - used_width;
            if( seg_width <= 0 ) {
                continue;
            }
            used_width += seg_width;
            result += string_format( "<color_%s>", std::get<2>( *it ) );
            result.insert( result.end(), seg_width, std::get<1>( *it ) );
            result += "</color>";
        }
        result.insert( result.end(), bar_width - used_width, ' ' );
    }
    result += ']';
    return result;
}
References string_format(), and utf8_width().
Referenced by print_ranged_chance().
get_default_aim_type()
static std::vector< aim_type > get_default_aim_type () static
Definition at line 1329 of file ranged.cpp.
{
    std::vector<aim_type> aim_types;
    aim_types.push_back( aim_type { "", "", "", false, 0 } ); // dummy aim type for unaimed shots
    return aim_types;
}
Referenced by draw_throw_aim(), and Character::get_aim_types().
is_driving()
static bool is_driving (const player & p) static
Definition at line 1856 of file ranged.cpp.
{
    const optional_vpart_position vp = get_map().veh_at( p.pos() );
    return vp && vp->vehicle().is_moving() && vp->vehicle().player_in_control( p );
}
References get_map(), Character::pos(), and map::veh_at().
Referenced by player::get_weapon_dispersion().
make_gun_projectile()
static projectile make_gun_projectile (const item & gun) static
Definition at line 1669 of file ranged.cpp.
{
    projectile proj;
    proj.speed  = 1000;
    proj.impact = gun.gun_damage();
    proj.range = gun.gun_range();
    for( const ammo_effect_str_id &ae_id : gun.ammo_effects() ) {
        proj.add_effect( ae_id );
    }
    auto &fx = proj;
    if( ( gun.ammo_data() && gun.ammo_data()->phase == LIQUID ) ||
        fx.has_effect( ammo_effect_SHOT ) || fx.has_effect( ammo_effect_BOUNCE ) ) {
        fx.add_effect( ammo_effect_WIDE );
    }
    if( gun.ammo_data() ) {
        assert( gun.ammo_data()->ammo );
        const islot_ammo &ammo = *gun.ammo_data()->ammo;
        // Some projectiles have a chance of being recoverable
        bool recover = !one_in( ammo.dont_recover_one_in );
        if( recover && !fx.has_effect( ammo_effect_IGNITE ) && !fx.has_effect( ammo_effect_EXPLOSIVE ) ) {
            item drop( gun.ammo_current(), calendar::turn, 1 );
            drop.active = fx.has_effect( ammo_effect_ACT_ON_RANGED_HIT );
            proj.set_drop( drop );
        }
        if( ammo.drop ) {
            item drop( ammo.drop );
            if( ammo.drop_active ) {
                drop.activate();
            }
            proj.set_drop( drop );
        }
        if( fx.has_effect( ammo_effect_CUSTOM_EXPLOSION ) ) {
            proj.set_custom_explosion( gun.ammo_data()->explosion );
        }
    }
    return proj;
}
References item::activate(), item::active, projectile::add_effect(), itype::ammo, item::ammo_current(), item::ammo_data(), ammo_effect_ACT_ON_RANGED_HIT, ammo_effect_BOUNCE, ammo_effect_CUSTOM_EXPLOSION, ammo_effect_EXPLOSIVE, ammo_effect_IGNITE, ammo_effect_SHOT, ammo_effect_WIDE, item::ammo_effects(), islot_ammo::dont_recover_one_in, islot_ammo::drop, islot_ammo::drop_active, itype::explosion, item::gun_damage(), item::gun_range(), projectile::impact, LIQUID, one_in(), itype::phase, projectile::range, projectile::set_custom_explosion(), projectile::set_drop(), projectile::speed, and calendar::turn.
Referenced by player::fire_gun(), and target_ui::set_cursor_pos().
make_gun_sound_effect()
void make_gun_sound_effect (const player & p, bool burst, item * weapon)
Definition at line 1771 of file ranged.cpp.
{
    const auto data = weapon->gun_noise( burst );
    if( data.volume > 0 ) {
        sounds::sound( p.pos(), data.volume, sounds::sound_t::combat,
                       data.sound.empty() ? _( "Bang!" ) : data.sound );
    }
}
References _, sounds::combat, item::gun_noise(), Character::pos(), and sounds::sound().
Referenced by player::fire_gun().
occupied_tile_fraction()
static double occupied_tile_fraction (m_size target_size) static
Definition at line 521 of file ranged.cpp.
{
    switch( target_size ) {
        case MS_TINY:
            return 0.1;
        case MS_SMALL:
            return 0.25;
        case MS_MEDIUM:
            return 0.5;
        case MS_LARGE:
            return 0.75;
        case MS_HUGE:
            return 1.0;
        default:
            break;
    }
    return 0.5;
}
References MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, and MS_TINY.
Referenced by target_ui::panel_fire_mode_aim(), and Creature::ranged_target_size().
pl_sees()
static bool pl_sees (const Creature & cr) static
Definition at line 1519 of file ranged.cpp.
{
    Character &u = get_player_character();
    return u.sees( cr ) || u.sees_with_infrared( cr ) || u.sees_with_specials( cr );
}
References get_player_character(), Character::sees(), Character::sees_with_infrared(), and Character::sees_with_specials().
Referenced by target_ui::choose_initial_target(), target_ui::set_cursor_pos(), and target_ui::try_reacquire_target().
print_aim()
static int print_aim (const player & p, const catacurses::window & w, int line_number, input_context & ctxt, const item & weapon, const double target_size, const tripoint & pos, double predicted_recoil) static
Definition at line 1542 of file ranged.cpp.
{
    // This is absolute accuracy for the player.
    // TODO: push the calculations duplicated from Creature::deal_projectile_attack() and
    // Creature::projectile_attack() into shared methods.
    // Dodge doesn't affect gun attacks
    dispersion_sources dispersion = p.get_weapon_dispersion( weapon );
    dispersion.add_range( p.recoil_vehicle() );
    const double min_recoil = calculate_aim_cap( p, pos );
    const double effective_recoil = p.effective_dispersion( p.weapon.sight_dispersion() );
    const double min_dispersion = std::max( min_recoil, effective_recoil );
    const double steadiness_range = MAX_RECOIL - min_dispersion;
    // This is a relative measure of how steady the player's aim is,
    // 0 is the best the player can do.
    const double steady_score = std::max( 0.0, predicted_recoil - min_dispersion );
    // Fairly arbitrary cap on steadiness...
    const double steadiness = 1.0 - ( steady_score / steadiness_range );
    // This could be extracted, to allow more/less verbose displays
    static const std::vector<confidence_rating> confidence_config = {{
            { accuracy_critical, '*', "green", translate_marker_context( "aim_confidence", "Great" ) },
            { accuracy_standard, '+', "light_gray", translate_marker_context( "aim_confidence", "Normal" ) },
            { accuracy_grazing, '|', "magenta", translate_marker_context( "aim_confidence", "Graze" ) }
        }
    };
    int shots = std::max( 1, weapon.gun_current_mode().qty );
    const auto dispersion_fun = [&]( const aim_type & at ) {
        int at_recoil = at.has_threshold ? at.threshold : static_cast<int>( predicted_recoil );
        return calculate_dispersion( get_map(), p, weapon, at_recoil, shots > 1 );
    };
    const auto cost_fun = [&]( const aim_type & at ) {
        int at_recoil = at.has_threshold ? at.threshold : static_cast<int>( predicted_recoil );
        return p.gun_engagement_moves( weapon, at_recoil, p.recoil ) + time_to_attack( p,
                *weapon.type );
    };
    const double range = rl_dist( p.pos(), pos );
    line_number = print_steadiness( w, line_number, steadiness );
    return print_ranged_chance( p, w, line_number, ctxt, weapon, p.get_aim_types( weapon ),
                                dispersion_fun, cost_fun,
                                confidence_config,
                                range, target_size );
}
References accuracy_critical, accuracy_grazing, accuracy_standard, dispersion_sources::add_range(), calculate_aim_cap(), calculate_dispersion(), Character::effective_dispersion(), Character::get_aim_types(), get_map(), player::get_weapon_dispersion(), item::gun_current_mode(), player::gun_engagement_moves(), MAX_RECOIL, Character::pos(), print_ranged_chance(), print_steadiness(), gun_mode::qty, Character::recoil, Character::recoil_vehicle(), rl_dist(), item::sight_dispersion(), time_to_attack(), translate_marker_context, item::type, and Character::weapon.
Referenced by target_ui::panel_fire_mode_aim().
print_ranged_chance()
static int print_ranged_chance (const player & , const catacurses::window & w, int line_number, input_context & ctxt, const item & , const std::vector< aim_type > & aim_types, const std::function< dispersion_sources(const aim_type &)> & dispersion_fun, const std::function< int(const aim_type &)> & cost_fun, const std::vector< confidence_rating > & confidence_config, double range, double target_size) static
Definition at line 1371 of file ranged.cpp.
{
    int window_width = getmaxx( w ) - 2; // Window width minus borders.
    std::string display_type = get_option<std::string>( "ACCURACY_DISPLAY" );
    std::string panel_type = panel_manager::get_manager().get_current_layout_id();
    const int bars_pad = 3; // Padding for "bars" to fit moves_to_fire value.
    if( ( panel_type == "compact" || panel_type == "labels-narrow" ) && display_type != "numbers" ) {
        window_width -= bars_pad;
    }
    std::string label_m = _( "Moves" );
    std::vector<std::string> t_aims( 4 ), t_confidence( 16 );
    int aim_iter = 0, conf_iter = 0;
    nc_color col = c_dark_gray;
    if( display_type != "numbers" ) {
        std::string symbols;
        int column_number = 1;
        if( !( panel_type == "compact" || panel_type == "labels-narrow" ) ) {
            std::string label = _( "Symbols:" );
            mvwprintw( w, point( column_number, line_number ), label );
            column_number += utf8_width( label ) + 1; // 1 for whitespace after 'Symbols:'
        }
        for( const confidence_rating &cr : confidence_config ) {
            std::string label = pgettext( "aim_confidence", cr.label.c_str() );
            std::string symbols = string_format( "<color_%s>%s</color> = %s", cr.color, cr.symbol,
                                                 label );
            int line_len = utf8_width( label ) + 5; // 5 for '# = ' and whitespace at end
            if( ( window_width + bars_pad - column_number ) < line_len ) {
                column_number = 1;
                line_number++;
            }
            print_colored_text( w, point( column_number, line_number ), col, col, symbols );
            column_number += line_len;
        }
        line_number++;
    }
    if( ( panel_type == "compact" || panel_type == "labels-narrow" ) && display_type == "numbers" ) {
        std::string symbols = _( " <color_green>Great</color> - <color_light_gray>Normal</color>"
                                 " - <color_magenta>Graze</color> - <color_light_blue>Moves</color>" );
        fold_and_print( w, point( 1, line_number++ ), window_width + bars_pad,
                        c_dark_gray, symbols );
        int len = utf8_width( symbols ) - 96; // 96 to subtract color codes
        if( len > window_width + bars_pad ) {
            line_number++;
        }
        for( int i = 0; i < window_width; i++ ) {
            mvwprintw( w, point( i + 1, line_number ), "-" );
        }
    }
    const auto front_or = [&]( const std::string & s, const char fallback ) {
        const auto keys = ctxt.keys_bound_to( s );
        return keys.empty() ? fallback : keys.front();
    };
    for( const aim_type &type : aim_types ) {
        dispersion_sources current_dispersion = dispersion_fun( type );
        std::string label = _( "Current" );
        std::string aim_l = _( "Aim" );
        if( type.has_threshold ) {
            label = type.name;
        }
        int moves_to_fire = cost_fun( type );
        auto hotkey = front_or( type.action.empty() ? "FIRE" : type.action, ' ' );
        if( ( panel_type == "compact" || panel_type == "labels-narrow" ) ) {
            if( display_type == "numbers" ) {
                t_aims[aim_iter] = string_format( "<color_dark_gray>%s:</color>", label );
                t_confidence[( aim_iter * 4 ) + 3] = string_format( "<color_light_blue>%d</color>", moves_to_fire );
            } else {
                print_colored_text( w, point( 1, line_number ), col, col, string_format( _( "%s %s:" ), label,
                                    aim_l ) );
                right_print( w, line_number++, 1, c_light_blue, _( "Moves" ) );
                right_print( w, line_number, 1, c_light_blue, string_format( "%d", moves_to_fire ) );
            }
        } else {
            print_colored_text( w, point( 1, line_number++ ), col, col,
                                string_format( _( "<color_white>[%s]</color> %s %s: Moves to fire: "
                                                  "<color_light_blue>%d</color>" ),
                                               hotkey, label, aim_l, moves_to_fire ) );
        }
        double confidence = confidence_estimate( range, target_size, current_dispersion );
        if( display_type == "numbers" ) {
            if( panel_type == "compact" || panel_type == "labels-narrow" ) {
                int last_chance = 0;
                for( const confidence_rating &cr : confidence_config ) {
                    int chance = std::min<int>( 100, 100.0 * ( cr.aim_level ) * confidence ) - last_chance;
                    last_chance += chance;
                    t_confidence[conf_iter] = string_format( "<color_%s>%3d%%</color>", cr.color, chance );
                    conf_iter++;
                    if( conf_iter == ( aim_iter * 4 ) + 3 ) {
                        conf_iter++;
                    }
                }
                aim_iter++;
            } else {
                int last_chance = 0;
                std::string confidence_s = enumerate_as_string( confidence_config.begin(), confidence_config.end(),
                [&]( const confidence_rating & config ) {
                    // TODO: Consider not printing 0 chances, but only if you can print something (at least miss 100% or so)
                    int chance = std::min<int>( 100, 100.0 * ( config.aim_level * confidence ) ) - last_chance;
                    last_chance += chance;
                    return string_format( "%s: <color_%s>%3d%%</color>", pgettext( "aim_confidence",
                                          config.label.c_str() ), config.color, chance );
                }, enumeration_conjunction::none );
                line_number += fold_and_print_from( w, point( 1, line_number ), window_width, 0,
                                                    c_dark_gray, confidence_s );
            }
        } else {
            std::vector<std::tuple<double, char, std::string>> confidence_ratings;
            std::transform( confidence_config.begin(), confidence_config.end(),
                            std::back_inserter( confidence_ratings ),
            [&]( const confidence_rating & config ) {
                return std::make_tuple( config.aim_level, config.symbol, config.color );
            }
                          );
            const std::string &confidence_bar = get_colored_bar( confidence, window_width, "",
                                                confidence_ratings.begin(),
                                                confidence_ratings.end() );
            print_colored_text( w, point( 1, line_number++ ), col, col, confidence_bar );
        }
    }
    // Draw tables for compact Numbers display
    if( ( panel_type == "compact" || panel_type == "labels-narrow" )
        && display_type == "numbers" ) {
        const std::string divider = "|";
        int left_pad = 10, columns = 4;
        insert_table( w, left_pad, ++line_number, columns, c_light_gray, divider, true, t_confidence );
        insert_table( w, 0, line_number, 1, c_light_gray, "", false, t_aims );
        line_number = line_number + 4; // 4 to account for the tables
    }
    return line_number;
}
References _, c_dark_gray, c_light_blue, c_light_gray, confidence_estimate(), calendar::config, enumerate_as_string(), fold_and_print(), fold_and_print_from(), get_colored_bar(), panel_manager::get_current_layout_id(), panel_manager::get_manager(), catacurses::getmaxx(), insert_table(), input_context::keys_bound_to(), catacurses::mvwprintw(), none, pgettext(), print_colored_text(), right_print(), string_format(), anonymous_namespace{rotatable_symbols.cpp}::symbols, iexamine::transform(), type, and utf8_width().
Referenced by draw_throw_aim(), and print_aim().
print_steadiness()
static int print_steadiness (const catacurses::window & w, int line_number, double steadiness) static
Definition at line 1297 of file ranged.cpp.
{
    const int window_width = getmaxx( w ) - 2; // Window width minus borders.
    if( get_option<std::string>( "ACCURACY_DISPLAY" ) == "numbers" ) {
        std::string steadiness_s = string_format( "%s: %d%%", _( "Steadiness" ),
                                   static_cast<int>( 100.0 * steadiness ) );
        mvwprintw( w, point( 1, line_number++ ), steadiness_s );
    } else {
        const std::string &steadiness_bar = get_labeled_bar( steadiness, window_width,
                                            _( "Steadiness" ), '*' );
        mvwprintw( w, point( 1, line_number++ ), steadiness_bar );
    }
    return line_number;
}
References _, get_labeled_bar(), catacurses::getmaxx(), catacurses::mvwprintw(), and string_format().
Referenced by print_aim().
range_with_even_chance_of_good_hit()
int range_with_even_chance_of_good_hit (int dispersion)
Definition at line 561 of file ranged.cpp.
{
    int even_chance_range = 0;
    while( static_cast<unsigned>( even_chance_range ) <
           Creature::dispersion_for_even_chance_of_good_hit.size() &&
           dispersion < Creature::dispersion_for_even_chance_of_good_hit[ even_chance_range ] ) {
        even_chance_range++;
    }
    return even_chance_range;
}
References Creature::dispersion_for_even_chance_of_good_hit, and om_direction::size.
Referenced by npc::confident_gun_mode_range(), and item::gun_info().
time_to_attack()
int time_to_attack (const Character & p, const itype & firing)
Definition at line 1714 of file ranged.cpp.
{
    const skill_id &skill_used = firing.gun->skill_used;
    const time_info_t &info = skill_used->time_to_attack();
    return std::max( info.min_time,
                     info.base_time - info.time_reduction_per_level * p.get_skill_level( skill_used ) );
}
References time_info_t::base_time, Character::get_skill_level(), itype::gun, time_info_t::min_time, time_info_t::time_reduction_per_level, and Skill::time_to_attack().
Referenced by player::fire_gun(), player::gun_value(), and print_aim().
Variable Documentation
AIF_DURATION_LIMIT
constexpr int AIF_DURATION_LIMIT = 10 static constexpr
Definition at line 154 of file ranged.cpp.
Referenced by target_ui::run().
ammo_effect_ACT_ON_RANGED_HIT
const ammo_effect_str_id ammo_effect_ACT_ON_RANGED_HIT("ACT_ON_RANGED_HIT") ("ACT_ON_RANGED_HIT") static
Referenced by make_gun_projectile(), and player::throw_item().
ammo_effect_BLACKPOWDER
const ammo_effect_str_id ammo_effect_BLACKPOWDER("BLACKPOWDER") ("BLACKPOWDER") static
Referenced by ranged::handle_gun_damage().
ammo_effect_BOUNCE
const ammo_effect_str_id ammo_effect_BOUNCE("BOUNCE") ("BOUNCE") static
Referenced by make_gun_projectile().
ammo_effect_BURST
const ammo_effect_str_id ammo_effect_BURST("BURST") ("BURST") static
Referenced by player::throw_item().
ammo_effect_CUSTOM_EXPLOSION
const ammo_effect_str_id ammo_effect_CUSTOM_EXPLOSION("CUSTOM_EXPLOSION") ("CUSTOM_EXPLOSION") static
Referenced by make_gun_projectile().
ammo_effect_EMP
const ammo_effect_str_id ammo_effect_EMP("EMP") ("EMP") static
Referenced by ranged::handle_gun_damage().
ammo_effect_EXPLOSIVE
const ammo_effect_str_id ammo_effect_EXPLOSIVE("EXPLOSIVE") ("EXPLOSIVE") static
Referenced by make_gun_projectile().
ammo_effect_HEAVY_HIT
const ammo_effect_str_id ammo_effect_HEAVY_HIT("HEAVY_HIT") ("HEAVY_HIT") static
Referenced by player::throw_item().
ammo_effect_IGNITE
const ammo_effect_str_id ammo_effect_IGNITE("IGNITE") ("IGNITE") static
Referenced by make_gun_projectile().
ammo_effect_LASER
const ammo_effect_str_id ammo_effect_LASER("LASER") ("LASER") static
Referenced by item::gun_noise(), and ranged::handle_gun_damage().
ammo_effect_LIGHTNING
const ammo_effect_str_id ammo_effect_LIGHTNING("LIGHTNING") ("LIGHTNING") static
Referenced by item::gun_noise(), and player::throw_item().
ammo_effect_NO_CRIT
const ammo_effect_str_id ammo_effect_NO_CRIT("NO_CRIT") ("NO_CRIT") static
Referenced by player::fire_gun().
ammo_effect_NO_EMBED
const ammo_effect_str_id ammo_effect_NO_EMBED("NO_EMBED") ("NO_EMBED") static
Referenced by player::throw_item().
ammo_effect_NO_ITEM_DAMAGE
const ammo_effect_str_id ammo_effect_NO_ITEM_DAMAGE("NO_ITEM_DAMAGE") ("NO_ITEM_DAMAGE") static
Referenced by player::throw_item().
ammo_effect_NON_FOULING
const ammo_effect_str_id ammo_effect_NON_FOULING("NON-FOULING") ("NON-FOULING") static
Referenced by ranged::handle_gun_damage().
ammo_effect_PLASMA
const ammo_effect_str_id ammo_effect_PLASMA("PLASMA") ("PLASMA") static
Referenced by item::gun_noise(), and ranged::handle_gun_damage().
ammo_effect_RECYCLED
const ammo_effect_str_id ammo_effect_RECYCLED("RECYCLED") ("RECYCLED") static
Referenced by ranged::handle_gun_damage().
ammo_effect_SHATTER_SELF
const ammo_effect_str_id ammo_effect_SHATTER_SELF("SHATTER_SELF") ("SHATTER_SELF") static
Referenced by player::throw_item().
ammo_effect_SHOT
const ammo_effect_str_id ammo_effect_SHOT("SHOT") ("SHOT") static
Referenced by make_gun_projectile().
ammo_effect_TANGLE
const ammo_effect_str_id ammo_effect_TANGLE("TANGLE") ("TANGLE") static
Referenced by player::throw_item().
ammo_effect_WHIP
const ammo_effect_str_id ammo_effect_WHIP("WHIP") ("WHIP") static
Referenced by item::gun_noise().
ammo_effect_WIDE
const ammo_effect_str_id ammo_effect_WIDE("WIDE") ("WIDE") static
Referenced by make_gun_projectile(), and player::throw_item().
bio_railgun
const bionic_id bio_railgun("bio_railgun") ("bio_railgun") static
Referenced by player::throw_item().
bio_targeting
const bionic_id bio_targeting("bio_targeting") ("bio_targeting") static
Referenced by player::get_weapon_dispersion().
bio_ups
const bionic_id bio_ups("bio_ups") ("bio_ups") static
Referenced by ranged::gunmode_checks_weapon().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by player::throw_item().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by target_ui::on_target_accepted().
effect_on_roof
const efftype_id effect_on_roof("on_roof") ("on_roof") static
Referenced by player::fire_gun().
fault_gun_blackpowder
const fault_id fault_gun_blackpowder("fault_gun_blackpowder") ("fault_gun_blackpowder") static
Referenced by ranged::handle_gun_damage().
fault_gun_chamber_spent
const fault_id fault_gun_chamber_spent("fault_gun_chamber_spent") ("fault_gun_chamber_spent") static
Referenced by player::fire_gun(), and ranged::handle_gun_damage().
fault_gun_dirt
const fault_id fault_gun_dirt("fault_gun_dirt") ("fault_gun_dirt") static
Referenced by ranged::handle_gun_damage().
fault_gun_unlubricated
const fault_id fault_gun_unlubricated("fault_gun_unlubricated") ("fault_gun_unlubricated") static
Referenced by ranged::handle_gun_damage().
itype_12mm
const itype_id itype_12mm("12mm") ("12mm") static
Referenced by item::gun_noise().
itype_40x46mm
const itype_id itype_40x46mm("40x46mm") ("40x46mm") static
Referenced by item::gun_noise().
itype_40x53mm
const itype_id itype_40x53mm("40x53mm") ("40x53mm") static
Referenced by item::gun_noise().
itype_66mm
const itype_id itype_66mm("66mm") ("66mm") static
Referenced by item::gun_noise().
itype_84x246mm
const itype_id itype_84x246mm("84x246mm") ("84x246mm") static
Referenced by item::gun_noise().
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
Referenced by ranged::gunmode_checks_weapon().
itype_arrow
const itype_id itype_arrow("arrow") ("arrow") static
Referenced by item::gun_noise().
itype_bolt
const itype_id itype_bolt("bolt") ("bolt") static
Referenced by item::gun_noise().
itype_brass_catcher
const itype_id itype_brass_catcher("brass_catcher") ("brass_catcher") static
Referenced by cycle_action().
itype_flammable
const itype_id itype_flammable("flammable") ("flammable") static
Referenced by item::gun_noise().
itype_m235
const itype_id itype_m235("m235") ("m235") static
Referenced by item::gun_noise().
itype_metal_rail
const itype_id itype_metal_rail("metal_rail") ("metal_rail") static
Referenced by item::gun_noise().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by player::fire_gun(), and ranged::gunmode_checks_weapon().
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
Referenced by ranged::gunmode_checks_weapon().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by player::gun_value().
skill_driving
const skill_id skill_driving("driving") ("driving") static
Referenced by player::get_weapon_dispersion().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by player::fire_gun(), and player::get_weapon_dispersion().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by player::fire_gun().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by ranged::throw_cost(), player::throw_item(), and ranged::throwing_dispersion().
tr_practice_target
const trap_str_id tr_practice_target("tr_practice_target") ("tr_practice_target") static
trait_NORANGEDCRIT
const trait_id trait_NORANGEDCRIT("NO_RANGED_CRIT") ("NO_RANGED_CRIT") static
Referenced by player::fire_gun().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by player::fire_gun().