Cataclysm BN: src/recipe_dictionary.h File Reference
recipe_dictionary.h File Reference
#include <cstddef>
#include <algorithm>
#include <functional>
#include <map>
#include <set>
#include <string>
#include <unordered_set>
#include <vector>
#include "recipe.h"
#include "type_id.h"
Classes
class recipe_dictionary
class recipe_subset
Macros
#define CATA_SRC_RECIPE_DICTIONARY_H
Typedefs
using recipe_filter = std::function< bool(const recipe &r)>
Functions
recipe_filter recipe_filter_by_component (const itype_id &c)
void serialize (const recipe_subset &value, JsonOut &jsout)
void deserialize (recipe_subset &value, JsonIn &jsin)
Variables
recipe_dictionary recipe_dict
Macro Definition Documentation
CATA_SRC_RECIPE_DICTIONARY_H
#define CATA_SRC_RECIPE_DICTIONARY_H
Definition at line 3 of file recipe_dictionary.h.
Typedef Documentation
recipe_filter
using recipe_filter = std::function<bool(const recipe &r)>
Definition at line 75 of file recipe_dictionary.h.
Function Documentation
deserialize()
void deserialize (recipe_subset & value, JsonIn & jsin)
Definition at line 3424 of file savegame_json.cpp.
{
    value.clear();
    jsin.start_array();
    while( !jsin.end_array() ) {
        value.include( &recipe_id( jsin.get_string() ).obj() );
    }
}
References recipe_subset::clear(), JsonIn::end_array(), JsonIn::get_string(), recipe_subset::include(), string_id< T >::obj(), and JsonIn::start_array().
recipe_filter_by_component()
recipe_filter recipe_filter_by_component (const itype_id & c)
Definition at line 81 of file recipe_dictionary.cpp.
{
    return [c]( const recipe & r ) {
        for( const auto &opts : r.simple_requirements().get_components() ) {
            for( const item_comp &comp : opts ) {
                if( comp.type == c ) {
                    return true;
                }
            }
        }
        return false;
    };
}
References c.
Referenced by item::final_info().
serialize()
void serialize (const recipe_subset & value, JsonOut & jsout)
Definition at line 3415 of file savegame_json.cpp.
{
    jsout.start_array();
    for( const auto &entry : value ) {
        jsout.write( entry->ident() );
    }
    jsout.end_array();
}
References JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
Variable Documentation
recipe_dict
recipe_dictionary recipe_dict extern
Definition at line 29 of file recipe_dictionary.cpp.
Referenced by basecamp::available_upgrades(), debug_menu::character_edit_menu(), Character::compute_nutrient_range(), avatar::create(), recipe_dictionary::delete_if(), game::dump_stats(), einkpc_download_memory_card(), Item_factory::finalize(), recipe_dictionary::finalize(), find_repair_difficulty(), item::food_info(), Character::get_learned_recipes(), recipe_dictionary::get_uncraft(), recipe_dictionary::load_recipe(), recipe_dictionary::load_uncraft(), recipe_dictionary::reset(), select_crafting_recipe(), and set_skills().