Cataclysm BN: src/recipe.cpp File Reference
recipe.cpp File Reference
#include "recipe.h"
#include <algorithm>
#include <cmath>
#include <iterator>
#include <numeric>
#include <sstream>
#include "assign.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "construction.h"
#include "debug.h"
#include "flat_set.h"
#include "game_constants.h"
#include "item.h"
#include "itype.h"
#include "json.h"
#include "mapgen_functions.h"
#include "optional.h"
#include "output.h"
#include "player.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_id_utils.h"
#include "translations.h"
#include "type_id.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
Functions
static const std::string flag_ALLOW_FILTHY ("ALLOW_FILTHY")
static const std::string flag_FIT ("FIT")
static const std::string flag_VARSIZE ("VARSIZE")
template<typename Iter >
std::string required_skills_as_string (Iter first, Iter last, const Character *c, const bool print_skill_level)
template<typename Iter >
std::string required_skills_as_string (Iter first, Iter last)
static std::string dump_requirements (const requirement_data &reqs, int move_cost, const std::map< skill_id, int > &skills)
Variables
static const itype_id itype_hotplate ("hotplate")
Function Documentation
dump_requirements()
static std::string dump_requirements (const requirement_data & reqs, int move_cost, const std::map< skill_id, int > & skills) static
Definition at line 715 of file recipe.cpp.
{
    std::ostringstream os;
    JsonOut jsout( os, /*pretty_print=*/true );
    jsout.start_object();
    jsout.member( "time" );
    if( move_cost % 100 == 0 ) {
        dump_to_json_string( time_duration::from_turns( move_cost / 100 ),
                             jsout, time_duration::units );
    } else {
        // cannot precisely represent the value using time_duration format,
        // write integer instead.
        jsout.write( move_cost );
    }
    jsout.member( "skills" );
    jsout.start_array( /*wrap=*/!skills.empty() );
    for( const std::pair<const skill_id, int> &p : skills ) {
        jsout.start_array();
        jsout.write( p.first );
        jsout.write( p.second );
        jsout.end_array();
    }
    jsout.end_array();
    jsout.member( "inline" );
    reqs.dump( jsout );
    jsout.end_object();
    return os.str();
}
References requirement_data::dump(), dump_to_json_string(), JsonOut::end_array(), JsonOut::end_object(), time_duration::from_turns(), JsonOut::member(), move_cost(), JsonOut::start_array(), JsonOut::start_object(), time_duration::units, and JsonOut::write().
Referenced by recipe::check_blueprint_requirements().
flag_ALLOW_FILTHY()
static const std::string flag_ALLOW_FILTHY ("ALLOW_FILTHY") static
Referenced by recipe::get_component_filter().
flag_FIT()
static const std::string flag_FIT ("FIT") static
Referenced by recipe::create_result().
flag_VARSIZE()
static const std::string flag_VARSIZE ("VARSIZE") static
Referenced by recipe::create_result().
required_skills_as_string() [1/2]
template<typename Iter > std::string required_skills_as_string (Iter first, Iter last)
Definition at line 556 of file recipe.cpp.
{
    if( first == last ) {
        return _( "<color_cyan>none</color>" );
    }
    return enumerate_as_string( first, last,
    [&]( const std::pair<skill_id, int> &skill ) {
        return string_format( "<color_white>%s (%d)</color>", skill.first.obj().name(),
                              skill.second );
    } );
}
References _, enumerate_as_string(), last, and string_format().
required_skills_as_string() [2/2]
template<typename Iter > std::string required_skills_as_string (Iter first, Iter last, const Character * c, const bool print_skill_level)
Definition at line 535 of file recipe.cpp.
{
    if( first == last ) {
        return _( "<color_cyan>none</color>" );
    }
    return enumerate_as_string( first, last,
    [&]( const std::pair<skill_id, int> &skill ) {
        const int player_skill = c ? c->get_skill_level( skill.first ) : 0;
        std::string difficulty_color = skill.second > player_skill ? "yellow" : "green";
        std::string skill_level_string = print_skill_level ? "" : ( std::to_string( player_skill ) + "/" );
        skill_level_string += std::to_string( skill.second );
        return string_format( "<color_cyan>%s</color> <color_%s>(%s)</color>",
                              skill.first.obj().name(), difficulty_color, skill_level_string );
    } );
}
References _, c, enumerate_as_string(), last, string_format(), and to_string().
Referenced by recipe::primary_skill_string(), recipe::required_all_skills_string(), and recipe::required_skills_string().
Variable Documentation
itype_hotplate
const itype_id itype_hotplate("hotplate") ("hotplate") static
Referenced by recipe::hot_result().