Cataclysm BN: src/regional_settings.h File Reference
regional_settings.h File Reference
#include <map>
#include <memory>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>
#include "enums.h"
#include "mapdata.h"
#include "memory_fast.h"
#include "string_id.h"
#include "type_id.h"
#include "weather_gen.h"
#include "weighted_list.h"
Classes
class building_bin
struct city_settings
struct ter_furn_id
struct groundcover_extra
struct forest_biome_component
struct forest_biome_terrain_dependent_furniture
struct forest_biome
struct forest_mapgen_settings
struct forest_trail_settings
struct overmap_feature_flag_settings
struct overmap_forest_settings
struct shore_extendable_overmap_terrain_alias
struct overmap_lake_settings
struct map_extras
struct region_terrain_and_furniture_settings
struct regional_settings
Macros
#define CATA_SRC_REGIONAL_SETTINGS_H
Typedefs
using t_regional_settings_map = std::unordered_map< std::string, regional_settings >
using t_regional_settings_map_citr = t_regional_settings_map::const_iterator
Functions
void load_region_settings (const JsonObject &jo)
void reset_region_settings ()
void load_region_overlay (const JsonObject &jo)
void apply_region_overlay (const JsonObject &jo, regional_settings &region)
Variables
t_regional_settings_map region_settings_map
Macro Definition Documentation
CATA_SRC_REGIONAL_SETTINGS_H
#define CATA_SRC_REGIONAL_SETTINGS_H
Definition at line 3 of file regional_settings.h.
Typedef Documentation
t_regional_settings_map
using t_regional_settings_map = std::unordered_map<std::string, regional_settings>
Definition at line 245 of file regional_settings.h.
t_regional_settings_map_citr
using t_regional_settings_map_citr = t_regional_settings_map::const_iterator
Definition at line 246 of file regional_settings.h.
Function Documentation
apply_region_overlay()
void apply_region_overlay (const JsonObject & jo, regional_settings & region)
Definition at line 613 of file regional_settings.cpp.
{
    jo.read( "default_oter", region.default_oter );
    jo.read( "river_scale", region.river_scale );
    if( jo.has_array( "default_groundcover" ) ) {
        region.default_groundcover_str.reset( new weighted_int_list<ter_str_id> );
        for( JsonArray inner : jo.get_array( "default_groundcover" ) ) {
            if( region.default_groundcover_str->add( ter_str_id( inner.get_string( 0 ) ),
                    inner.get_int( 1 ) ) == nullptr ) {
                jo.throw_error( "'default_groundcover' must be a weighted list: an array of pairs [ \"id\", weight ]" );
            }
        }
    }
    JsonObject fieldjo = jo.get_object( "field_coverage" );
    double tmpval = 0.0f;
    if( fieldjo.read( "percent_coverage", tmpval ) ) {
        region.field_coverage.mpercent_coverage = static_cast<int>( tmpval * 10000.0 );
    }
    fieldjo.read( "default_ter", region.field_coverage.default_ter_str );
    for( const JsonMember member : fieldjo.get_object( "other" ) ) {
        if( member.is_comment() ) {
            continue;
        }
        region.field_coverage.percent_str[member.name()] = member.get_float();
    }
    if( fieldjo.read( "boost_chance", tmpval ) ) {
        region.field_coverage.boost_chance = static_cast<int>( tmpval * 10000.0 );
    }
    if( fieldjo.read( "boosted_percent_coverage", tmpval ) ) {
        if( region.field_coverage.boost_chance > 0.0f && tmpval == 0.0f ) {
            fieldjo.throw_error( "boost_chance > 0 requires boosted_percent_coverage" );
        }
        region.field_coverage.boosted_mpercent_coverage = static_cast<int>( tmpval * 10000.0 );
    }
    if( fieldjo.read( "boosted_other_percent", tmpval ) ) {
        if( region.field_coverage.boost_chance > 0.0f && tmpval == 0.0f ) {
            fieldjo.throw_error( "boost_chance > 0 requires boosted_other_percent" );
        }
        region.field_coverage.boosted_other_mpercent = static_cast<int>( tmpval * 10000.0 );
    }
    for( const JsonMember member : fieldjo.get_object( "boosted_other" ) ) {
        if( member.is_comment() ) {
            continue;
        }
        region.field_coverage.boosted_percent_str[member.name()] = member.get_float();
    }
    if( region.field_coverage.boost_chance > 0.0f &&
        region.field_coverage.boosted_percent_str.empty() ) {
        fieldjo.throw_error( "boost_chance > 0 requires boosted_other { … }" );
    }
    load_forest_mapgen_settings( jo, region.forest_composition, false, true );
    load_forest_trail_settings( jo, region.forest_trail, false, true );
    for( const JsonMember zone : jo.get_object( "map_extras" ) ) {
        if( zone.is_comment() ) {
            continue;
        }
        JsonObject zonejo = zone.get_object();
        int tmpval = 0;
        if( zonejo.read( "chance", tmpval ) ) {
            region.region_extras[zone.name()].chance = tmpval;
        }
        for( const JsonMember member : zonejo.get_object( "extras" ) ) {
            if( member.is_comment() ) {
                continue;
            }
            region.region_extras[zone.name()].values.add_or_replace( member.name(), member.get_int() );
        }
    }
    JsonObject cityjo = jo.get_object( "city" );
    cityjo.read( "shop_radius", region.city_spec.shop_radius );
    cityjo.read( "shop_sigma", region.city_spec.shop_sigma );
    cityjo.read( "park_radius", region.city_spec.park_radius );
    cityjo.read( "park_sigma", region.city_spec.park_sigma );
    const auto load_building_types = [&cityjo]( const std::string & type, building_bin & dest ) {
        for( const JsonMember member : cityjo.get_object( type ) ) {
            if( member.is_comment() ) {
                continue;
            }
            dest.add( overmap_special_id( member.name() ), member.get_int() );
        }
    };
    load_building_types( "houses", region.city_spec.houses );
    load_building_types( "shops", region.city_spec.shops );
    load_building_types( "parks", region.city_spec.parks );
    load_overmap_feature_flag_settings( jo, region.overmap_feature_flag, false, true );
    load_overmap_forest_settings( jo, region.overmap_forest, false, true );
    load_overmap_lake_settings( jo, region.overmap_lake, false, true );
    load_region_terrain_and_furniture_settings( jo, region.region_terrain_and_furniture, false, true );
}
References groundcover_extra::boost_chance, groundcover_extra::boosted_mpercent_coverage, groundcover_extra::boosted_other_mpercent, groundcover_extra::boosted_percent_str, regional_settings::city_spec, regional_settings::default_groundcover_str, regional_settings::default_oter, groundcover_extra::default_ter_str, regional_settings::field_coverage, regional_settings::forest_composition, regional_settings::forest_trail, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), city_settings::houses, load_forest_mapgen_settings(), load_forest_trail_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_region_terrain_and_furniture_settings(), mapgen_defer::member, groundcover_extra::mpercent_coverage, regional_settings::overmap_feature_flag, regional_settings::overmap_forest, regional_settings::overmap_lake, city_settings::park_radius, city_settings::park_sigma, city_settings::parks, groundcover_extra::percent_str, JsonObject::read(), regional_settings::region_extras, regional_settings::region_terrain_and_furniture, regional_settings::river_scale, city_settings::shop_radius, city_settings::shop_sigma, city_settings::shops, JsonObject::throw_error(), and type.
Referenced by load_region_overlay().
load_region_overlay()
void load_region_overlay (const JsonObject & jo)
Definition at line 586 of file regional_settings.cpp.
{
    if( jo.has_array( "regions" ) ) {
        JsonArray regions = jo.get_array( "regions" );
        for( const std::string regionid : regions ) {
            if( regionid == "all" ) {
                if( regions.size() != 1 ) {
                    jo.throw_error( "regions: More than one region is not allowed when \"all\" is used" );
                }
                for( auto &itr : region_settings_map ) {
                    apply_region_overlay( jo, itr.second );
                }
            } else {
                auto itr = region_settings_map.find( regionid );
                if( itr == region_settings_map.end() ) {
                    jo.throw_error( "region: " + regionid + " not found in region_settings_map" );
                } else {
                    apply_region_overlay( jo, itr->second );
                }
            }
        }
    } else {
        jo.throw_error( "\"regions\" is required and must be an array" );
    }
}
References apply_region_overlay(), JsonObject::get_array(), JsonObject::has_array(), region_settings_map, JsonArray::size(), and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
load_region_settings()
void load_region_settings (const JsonObject & jo)
Definition at line 412 of file regional_settings.cpp.
{
    regional_settings new_region;
    if( !jo.read( "id", new_region.id ) ) {
        jo.throw_error( "No 'id' field." );
    }
    bool strict = new_region.id == "default";
    if( !jo.read( "default_oter", new_region.default_oter ) && strict ) {
        jo.throw_error( "default_oter required for default ( though it should probably remain 'field' )" );
    }
    if( !jo.read( "river_scale", new_region.river_scale ) && strict ) {
        jo.throw_error( "river_scale required for default" );
    }
    if( jo.has_array( "default_groundcover" ) ) {
        new_region.default_groundcover_str.reset( new weighted_int_list<ter_str_id> );
        for( JsonArray inner : jo.get_array( "default_groundcover" ) ) {
            if( new_region.default_groundcover_str->add( ter_str_id( inner.get_string( 0 ) ),
                    inner.get_int( 1 ) ) == nullptr ) {
                jo.throw_error( "'default_groundcover' must be a weighted list: an array of pairs [ \"id\", weight ]" );
            }
        }
    } else if( strict ) {
        jo.throw_error( "Weighted list 'default_groundcover' required for 'default'" );
    }
    if( !jo.has_object( "field_coverage" ) ) {
        if( strict ) {
            jo.throw_error( "\"field_coverage\": { … } required for default" );
        }
    } else {
        JsonObject pjo = jo.get_object( "field_coverage" );
        double tmpval = 0.0f;
        if( !pjo.read( "percent_coverage", tmpval ) ) {
            pjo.throw_error( "field_coverage: percent_coverage required" );
        }
        new_region.field_coverage.mpercent_coverage = static_cast<int>( tmpval * 10000.0 );
        if( !pjo.read( "default_ter", new_region.field_coverage.default_ter_str ) ) {
            pjo.throw_error( "field_coverage: default_ter required" );
        }
        tmpval = 0.0f;
        if( pjo.has_object( "other" ) ) {
            for( const JsonMember member : pjo.get_object( "other" ) ) {
                if( member.is_comment() ) {
                    continue;
                }
                new_region.field_coverage.percent_str[member.name()] = member.get_float();
            }
        }
        if( pjo.read( "boost_chance", tmpval ) && tmpval != 0.0f ) {
            new_region.field_coverage.boost_chance = static_cast<int>( tmpval * 10000.0 );
            if( !pjo.read( "boosted_percent_coverage", tmpval ) ) {
                pjo.throw_error( "boost_chance > 0 requires boosted_percent_coverage" );
            }
            new_region.field_coverage.boosted_mpercent_coverage = static_cast<int>( tmpval * 10000.0 );
            if( !pjo.read( "boosted_other_percent", tmpval ) ) {
                pjo.throw_error( "boost_chance > 0 requires boosted_other_percent" );
            }
            new_region.field_coverage.boosted_other_mpercent = static_cast<int>( tmpval * 10000.0 );
            if( pjo.has_object( "boosted_other" ) ) {
                for( const JsonMember member : pjo.get_object( "boosted_other" ) ) {
                    if( member.is_comment() ) {
                        continue;
                    }
                    new_region.field_coverage.boosted_percent_str[member.name()] = member.get_float();
                }
            } else {
                pjo.throw_error( "boost_chance > 0 requires boosted_other { … }" );
            }
        }
    }
    load_forest_mapgen_settings( jo, new_region.forest_composition, strict, false );
    load_forest_trail_settings( jo, new_region.forest_trail, strict, false );
    if( !jo.has_object( "map_extras" ) ) {
        if( strict ) {
            jo.throw_error( "\"map_extras\": { … } required for default" );
        }
    } else {
        for( const JsonMember zone : jo.get_object( "map_extras" ) ) {
            if( zone.is_comment() ) {
                continue;
            }
            JsonObject zjo = zone.get_object();
            map_extras extras( 0 );
            if( !zjo.read( "chance", extras.chance ) && strict ) {
                zjo.throw_error( "chance required for default" );
            }
            if( !zjo.has_object( "extras" ) ) {
                if( strict ) {
                    zjo.throw_error( "\"extras\": { … } required for default" );
                }
            } else {
                for( const JsonMember member : zjo.get_object( "extras" ) ) {
                    if( member.is_comment() ) {
                        continue;
                    }
                    extras.values.add( member.name(), member.get_int() );
                }
            }
            new_region.region_extras[zone.name()] = extras;
        }
    }
    if( !jo.has_object( "city" ) ) {
        if( strict ) {
            jo.throw_error( "\"city\": { … } required for default" );
        }
    } else {
        JsonObject cjo = jo.get_object( "city" );
        if( !cjo.read( "shop_radius", new_region.city_spec.shop_radius ) && strict ) {
            jo.throw_error( "city: shop_radius required for default" );
        }
        if( !cjo.read( "shop_sigma", new_region.city_spec.shop_sigma ) && strict ) {
            jo.throw_error( "city: shop_sigma required for default" );
        }
        if( !cjo.read( "park_radius", new_region.city_spec.park_radius ) && strict ) {
            jo.throw_error( "city: park_radius required for default" );
        }
        if( !cjo.read( "park_sigma", new_region.city_spec.park_sigma ) && strict ) {
            jo.throw_error( "city: park_sigma required for default" );
        }
        const auto load_building_types = [&jo, &cjo, strict]( const std::string & type,
        building_bin & dest ) {
            if( !cjo.has_object( type ) && strict ) {
                jo.throw_error( "city: \"" + type + "\": { … } required for default" );
            } else {
                for( const JsonMember member : cjo.get_object( type ) ) {
                    if( member.is_comment() ) {
                        continue;
                    }
                    dest.add( overmap_special_id( member.name() ), member.get_int() );
                }
            }
        };
        load_building_types( "houses", new_region.city_spec.houses );
        load_building_types( "shops", new_region.city_spec.shops );
        load_building_types( "parks", new_region.city_spec.parks );
    }
    if( !jo.has_object( "weather" ) ) {
        if( strict ) {
            jo.throw_error( "\"weather\": { … } required for default" );
        }
    } else {
        JsonObject wjo = jo.get_object( "weather" );
        new_region.weather = weather_generator::load( wjo );
    }
    load_overmap_feature_flag_settings( jo, new_region.overmap_feature_flag, strict, false );
    load_overmap_forest_settings( jo, new_region.overmap_forest, strict, false );
    load_overmap_lake_settings( jo, new_region.overmap_lake, strict, false );
    load_region_terrain_and_furniture_settings( jo, new_region.region_terrain_and_furniture, strict,
            false );
    region_settings_map[new_region.id] = new_region;
}
References groundcover_extra::boost_chance, groundcover_extra::boosted_mpercent_coverage, groundcover_extra::boosted_other_mpercent, groundcover_extra::boosted_percent_str, regional_settings::city_spec, regional_settings::default_groundcover_str, regional_settings::default_oter, groundcover_extra::default_ter_str, anonymous_namespace{map_extras.cpp}::extras, regional_settings::field_coverage, regional_settings::forest_composition, regional_settings::forest_trail, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), city_settings::houses, regional_settings::id, weather_generator::load(), load_forest_mapgen_settings(), load_forest_trail_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_region_terrain_and_furniture_settings(), mapgen_defer::member, groundcover_extra::mpercent_coverage, regional_settings::overmap_feature_flag, regional_settings::overmap_forest, regional_settings::overmap_lake, city_settings::park_radius, city_settings::park_sigma, city_settings::parks, groundcover_extra::percent_str, JsonObject::read(), regional_settings::region_extras, region_settings_map, regional_settings::region_terrain_and_furniture, regional_settings::river_scale, city_settings::shop_radius, city_settings::shop_sigma, city_settings::shops, JsonObject::throw_error(), type, and regional_settings::weather.
Referenced by DynamicDataLoader::initialize().
reset_region_settings()
void reset_region_settings ()
Definition at line 577 of file regional_settings.cpp.
{
    region_settings_map.clear();
}
References region_settings_map.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
region_settings_map
t_regional_settings_map region_settings_map extern
Definition at line 186 of file overmap.cpp.
Referenced by MapExtras::debug_spawn_test(), overmap_terrains::finalize(), map::generate(), load_region_overlay(), load_region_settings(), overmap::overmap(), reset_region_settings(), and overmap::unserialize().