Cataclysm BN: src/rng.h File Reference
rng.h File Reference
#include <array>
#include <functional>
#include <iosfwd>
#include <random>
#include <type_traits>
#include "optional.h"
#include "units_angle.h"
#include "units_probability.h"
Classes
class is_std_array_helper< T >
class is_std_array_helper< std::array< T, N > >
class is_std_array< T >
Macros
#define CATA_SRC_RNG_H
Typedefs
using cata_default_random_engine = std::minstd_rand0
Functions
void rng_set_engine_seed (unsigned int seed)
cata_default_random_engine & rng_get_engine ()
unsigned int rng_bits ()
int rng (int lo, int hi)
double rng_float (double lo, double hi)
template<typename U >
units::quantity< double, U > rng_float (units::quantity< double, U > lo, units::quantity< double, U > hi)
units::angle random_direction ()
bool one_in (int chance)
bool one_turn_in (const time_duration &duration)
bool x_in_y (double x, double y)
bool check (units::probability p)
int dice (int number, int sides)
int roll_remainder (double value)
int roll_remainder (float value)
int djb2_hash (const unsigned char *input)
double rng_normal (double lo, double hi)
double rng_normal (double hi)
double normal_roll (double mean, double stddev)
double rng_exponential (double min, double mean)
double rng_exponential (double mean)
double exponential_roll (double lambda)
template<typename C , typename D , typename V = typename C::value_type>
V random_entry (const C &container, D default_value)
Returns a random entry in the container.
template<typename C >
auto random_entry_opt (C &container) -> cata::optional< decltype(std::ref(*container.begin()))>
Same as above but returns a reference to the chosen entry (if the container is not empty) or an empty optional object (if the container is empty).
template<typename C , typename V = typename C::value_type>
V random_entry (const C &container)
Same as above, but returns a default constructed value if the container is empty.
template<typename C , typename V = typename C::value_type>
std::enable_if<!is_std_array< C >::value, constV & >::type random_entry_ref (const C &container)
Same as above, but with a statically allocated default value (using the default constructor).
template<typename V , std::size_t N>
const V & random_entry_ref (const std::array< V, N > &container)
template<typename C , typename V = typename C::value_type>
V random_entry_removed (C &container)
Returns a random entry in the container and removes it from the container.
tripoint_range< tripoint > points_in_range (const map &m)
Returns a range enclosing all valid points of the map.
cata::optional< tripoint > random_point (const tripoint_range< tripoint > &range, const std::function< bool(const tripoint &)> &predicate)
Returns a random point in the given range that satisfies the given predicate (if any).
cata::optional< tripoint > random_point (const map &m, const std::function< bool(const tripoint &)> &predicate)
Same as other random_point with a range enclosing all valid points of the map.
Macro Definition Documentation
CATA_SRC_RNG_H
#define CATA_SRC_RNG_H
Definition at line 3 of file rng.h.
Typedef Documentation
cata_default_random_engine
using cata_default_random_engine = std::minstd_rand0
Definition at line 27 of file rng.h.
Function Documentation
check()
bool check (units::probability p)
Definition at line 80 of file rng.cpp.
{
    return rng( 0, 1000000 - 1 ) < units::to_one_in_million( p );
}
References rng(), and units::to_one_in_million().
dice()
int dice (int number, int sides)
Definition at line 85 of file rng.cpp.
{
    int ret = 0;
    for( int i = 0; i < number; i++ ) {
        ret += rng( 1, sides );
    }
    return ret;
}
References cata::hash64_detail::ret, and rng().
Referenced by Creature::add_env_effect(), addict_effect(), Character::avoid_trap(), monster::avoid_trap(), mattack::bio_op_disarm(), npc::bravery_check(), melee_actor::call(), crafting::complete_disassemble(), player::crafting_success_roll(), iuse::crowbar(), salvage_actor::cut_up(), Creature::deal_projectile_attack(), mattack::dermatik(), distribution::dice_roll(), map::draw_lab(), explosion_handler::emp_blast(), mattack::evolve_kill_strike(), activity_handlers::fish_do_turn(), mattack::grab_drag(), game::grabbed_veh_move(), computer_session::hack_attempt(), hackveh(), vehicle::init_state(), activity_handlers::lockpicking_finish(), monster::melee_attack(), monster::monster(), monster::move_effects(), MapExtras::mx_collegekids(), MapExtras::mx_drugdeal(), MapExtras::mx_helicopter(), MapExtras::mx_military(), MapExtras::mx_roadblock(), MapExtras::mx_science(), Character::on_hit(), vehicle::possibly_recover_from_skid(), map::process_fields_in_submap(), sounds::process_sound_markers(), iuse::radio_on(), npc_class::roll_dexterity(), npc_class::roll_intelligence(), npc_class::roll_perception(), npc_class::roll_strength(), vehicle::smash(), monster::stability_roll(), basecamp::start_garage_chop(), Character::suffer_without_sleep(), iuse::tazer(), avatar_funcs::try_disarm_npc(), try_remove_grab(), avatar_funcs::try_steal_from_npc(), sew_advanced_actor::use(), and game::vertical_move().
djb2_hash()
int djb2_hash (const unsigned char * input)
Definition at line 111 of file rng.cpp.
{
    unsigned int hash = 5381;
    unsigned char c = *input++;
    while( c != '\0' ) {
        hash = ( ( hash << 5 ) + hash ) + c; /* hash * 33 + c */
        c = *input++;
    }
    return hash;
}
References c.
Referenced by translation::legacy_hash(), and main().
exponential_roll()
double exponential_roll (double lambda)
Definition at line 48 of file rng.cpp.
{
    static std::exponential_distribution<double> rng_exponential_dist;
    return rng_exponential_dist( rng_get_engine(),
                                 std::exponential_distribution<>::param_type( lambda ) );
}
References rng_get_engine().
Referenced by rng_exponential().
normal_roll()
double normal_roll (double mean, double stddev)
Definition at line 42 of file rng.cpp.
{
    static std::normal_distribution<double> rng_normal_dist;
    return rng_normal_dist( rng_get_engine(), std::normal_distribution<>::param_type( mean, stddev ) );
}
References rng_get_engine().
Referenced by activity_handlers::chop_planks_finish(), hack_attempt(), melee::melee_hit_range(), overmap::pick_random_building_to_place(), and rng_normal().
one_in()
bool one_in (int chance)
Definition at line 65 of file rng.cpp.
{
    return ( chance <= 1 || rng( 0, chance - 1 ) == 0 );
}
References rng().
Referenced by weather_effect::acid(), mattack::acid(), mdefense::acidsplash(), vehicle::act_on_map(), computer_session::action_radio_archive(), Character::activate_bionic(), Character::activate_mutation(), enchantment::activate_passive(), timed_event::actualize(), scrollingcombattext::add(), map::add_corpse(), item::add_rain_to_container(), map::add_splash(), map::add_splatter_trail(), addict_effect(), npc::address_needs(), npc::address_player(), vehicle::alarm(), npc::alt_attack(), Character::amount_of_storage_bionics(), jmapgen_liquid_item::apply(), jmapgen_setmap::apply(), temperature_effect::apply(), Character::armor_absorb(), iuse::artifact(), monster::bash_at(), map::bash_items(), trapfunc::beartrap(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::block_hit(), iuse::blood_draw(), body_part_hit_by_plant(), mattack::boomer(), mattack::boomer_glow(), overmap::build_city_street(), overmap::build_lab(), overmap::build_mine(), overmap::build_slimepit(), overmap::build_tunnel(), VehicleSpawnFunction::builtin_parkinglot(), Character::burn_move_stamina(), MapExtras::burned_ground_parser(), activity_handlers::butcher_finish(), butchery_drops_harvest(), iuse::camera(), can_fire_turret(), avatar_action::can_fire_weapon(), iuse::capture_monster_act(), defense_game::caravan(), talk_function::caravan_return(), talk_function::carpenter_return(), enchantment::cast_enchantment_spell(), monster::check_mech_powered(), Character::check_needs_extremes(), mattack::chickenbot(), clay_or_sand(), iuse::coin_flip(), map::collapse_at(), crafting::complete_disassemble(), vehicle::consume_fuel(), mattack::copbot(), Character::cough(), player::craft_skill_gain(), map::create_anomaly(), spell::create_field(), Single_item_creator::create_single(), game::create_starting_npcs(), map::creature_in_field(), trapfunc::crossbow(), MapExtras::dead_vegetation_parser(), Character::deal_damage(), Creature::deal_melee_hit(), Creature::deal_projectile_attack(), monster::deal_projectile_attack(), MapExtras::debug_spawn_test(), mission_end::deposit_box(), describe_sound(), monster::die(), monster::die_if_drowning(), iuse::dig(), game::disable_robot(), iuse::dive_tank(), vehicle::do_engine_damage(), character_funcs::do_pause(), avatar::do_read(), Character::do_skill_rust(), player_activity::do_turn(), mattack::dogthing(), construct::done_extract_maybe_revert_to_dirt(), mattack::doot(), overmap_ui::draw_ascii(), map::draw_lab(), map::draw_mine(), map::draw_office_tower(), map::draw_slimepit(), map::draw_temple(), map::draw_triffid(), Character::eat(), mattack::eat_crop(), eff_fun_bleed(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_hot(), eff_fun_rat(), eff_fun_spores(), iexamine::egg_sack_generic(), iuse::ehandcuffs(), einkpc_download_memory_card(), iuse::einktabletpc(), explosion_handler::emp_blast(), vehicle::explode_fuel(), iuse::extinguisher(), Character::fall_asleep(), fill_funnels(), dig_activity_actor::finish(), npc::finish_read(), fire(), ranged::fire_gun(), mdeath::fireball(), iuse::fish_trap(), mattack::flame(), explosion_handler::explosion_funcs::flashbang(), mattack::flesh_golem(), mattack::flesh_tendril(), game::fling_creature(), iexamine::flower_cactus(), iexamine::flower_poppy(), activity_handlers::forage_finish(), talk_function::forage_return(), game::forced_door_closing(), mattack::frag(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_bristle(), mattack::fungus_inject(), iexamine::gaspump(), basecamp::gathering_return(), Name::generate(), map::generate(), overmap::generate_sub(), get_music_description(), weather_generator::get_weather(), trapfunc::glow(), trapfunc::goo(), game::grabbed_furn_move(), game::grabbed_veh_move(), iuse::granade_act(), grass_or_dirt(), mattack::growplants(), computer_session::hack_attempt(), ranged::handle_gun_damage(), Character::handle_melee_wear(), Character::hardcoded_effects(), iexamine::harvest_plant(), has_psy_protection(), map::hit_with_acid(), mattack::howl(), mattack::impale(), iuse::inhaler(), init_memory_card_with_random_stuff(), vehicle::init_state(), monexamine::kill_zslave(), Character::knock_back_to(), game::knockback(), talk_function::labor_return(), trapfunc::ledge(), mattack::leech_spawner(), weather_effect::light_acid(), weather_effect::lightning(), mattack::longswipe(), talk_function::loot_building(), mattack::lunge(), item::make_corpse(), make_gun_projectile(), make_mon_corpse(), map::make_rubble(), activity_handlers::make_zlave_finish(), mapgen_ants_curved(), mapgen_cavern(), mapgen_forest(), mapgen_hive(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), mapgen_road(), marloss_add(), fungal_effects::marlossify(), Character::melee_attack(), monster::melee_attack(), Item_modifier::modify(), Character::modify_morale(), iuse::molotov_lit(), map::monster_in_field(), iuse::mop(), monster::move(), avatar_action::move(), npc::move_away_from(), monster::move_effects(), overmap::move_hordes(), monster::move_to(), npc::move_to(), map::move_vehicle(), npc::mug_player(), iuse::multicooker(), multicooker_hallu(), Character::mutate_category(), MapExtras::mx_bandits_block(), MapExtras::mx_casings(), MapExtras::mx_collegekids(), MapExtras::mx_corpses(), MapExtras::mx_drugdeal(), MapExtras::mx_grave(), MapExtras::mx_helicopter(), MapExtras::mx_house_spider(), MapExtras::mx_house_wasp(), MapExtras::mx_looters(), MapExtras::mx_marloss_pilgrimage(), MapExtras::mx_mayhem(), MapExtras::mx_military(), MapExtras::mx_minefield(), MapExtras::mx_portal_in(), MapExtras::mx_roadblock(), MapExtras::mx_roadworks(), MapExtras::mx_science(), MapExtras::mx_shia(), MapExtras::mx_spider(), iuse::mycus(), new_artifact(), new_natural_artifact(), monster::next_upgrade_time(), vehicle::noise_and_smoke(), mattack::nurse_assist(), mattack::nurse_operate(), Character::old_mutate(), bite_actor::on_damage(), Character::on_damage_of_type(), Character::on_hit(), one_turn_in(), map::open_door(), vehicle::operate_scoop(), mattack::parrot(), mattack::parrot_at_danger(), vehicle::part_collision(), timed_event::per_turn(), Character::perform_technique(), petfood(), mattack::photograph(), forest_biome::pick(), Character::pick_technique(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), overmap::place_cities(), overmap::place_forest_trailheads(), overmap::place_forest_trails(), MapExtras::place_fumarole(), map::place_gas_pump(), overmap::place_mongroups(), game::place_player(), overmap::place_radios(), overmap::place_river(), overmap::place_rivers(), vehicle::place_spawn_items(), map::place_spawns(), overmap::place_special(), overmap::place_swamps(), map::place_vending(), monster::plan(), mattack::plant(), vehicle::play_chimes(), map::player_in_field(), vehicle::pldrive(), avatar_action::plthrow(), Character::practice(), npc::pretend_fire(), game::process_artifact(), item::process_blackpowder_fouling(), monster::process_effects_internal(), item::process_extinguish(), map::process_fields_in_submap(), item::process_litcig(), monster::process_triggers(), monster::process_turn(), map::produce_sap(), projectile_attack(), iuse::prozac(), activity_handlers::pulp_do_turn(), iuse::purify_smart(), monexamine::push(), iuse::radio_on(), npc_class::random_common(), avatar::randomize(), npc::randomize(), Character::reach_attack(), activity_handlers::read_do_turn(), item::ready_to_revive(), firestarter_actor::resolve_firestarter_use(), explosion_handler::explosion_funcs::resonance_cascade(), mattack::resurrect(), reveal_target(), mattack::rifle(), mattack::riotbot(), activity_handlers::robot_control_finish(), Character::rooted(), SkillLevel::rust(), inventory::rust_iron_items(), iexamine::safe(), scatter_chunks(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), mattack::science(), science_room(), mattack::searchlight(), npc::see_item_say_smth(), set_description(), iuse::sewage(), trapfunc::shadow(), map::shake_vehicle(), mattack::shockstorm(), explosion_handler::explosion_funcs::shockwave(), map::shoot(), npc::shop_restock(), trapfunc::shotgun(), mattack::shriek_stun(), mattack::slimespring(), game::slip_down(), iexamine::slot_machine(), smash(), iuse::smoking(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), Character::sound_hallu(), game::spawn_hallucination(), map::spawn_item(), spawn_spores(), defense_game::spawn_wave(), defense_game::spawn_wave_monster(), fungal_effects::spread_fungus(), fungal_effects::spread_fungus_one_tile(), map::spread_gas(), vehicle::start_engine(), starting_inv(), mattack::stretch_attack(), mattack::stretch_bite(), monster::stumble(), Character::suffer_from_asthma(), Character::suffer_from_chemimbalance(), Character::suffer_from_other_mutations(), Character::suffer_from_radiation(), Character::suffer_from_schizophrenia(), Character::suffer_while_awake(), Character::suffer_without_sleep(), survive_random_encounter(), monexamine::swap(), avatar_action::swim(), mattack::tankgun(), iuse::thorazine(), mattack::thrown_by_judo(), weather_effect::thunder(), mattack::tindalos_teleport(), iexamine::toilet(), toolweapon_on(), spell_effect::transform_blast(), activity_handlers::tree_communion_do_turn(), iexamine::tree_marloss(), mattack::triffid_heartbeat(), try_remove_grab(), monster::try_reproduce(), activity_handlers::try_sleep_do_turn(), gun_actor::try_target(), Character::update_bodytemp(), game::update_stair_monsters(), fireweapon_on_actor::use(), mutagen_actor::use(), mutagen_iv_actor::use(), mattack::vine(), game::walk_move(), map::water_from(), iuse::weed_cake(), weed_msg(), scenario::weighted_random(), scenario::weighted_random_profession(), weather_effect::wet_player(), and npc::worker_downtime().
one_turn_in()
bool one_turn_in (const time_duration & duration)
Definition at line 70 of file rng.cpp.
{
    return one_in( to_turns<int>( duration ) );
}
References one_in().
Referenced by Character::hardcoded_effects(), Character::suffer_from_artifacts(), Character::suffer_from_bad_bionics(), Character::suffer_from_chemimbalance(), Character::suffer_from_other_mutations(), Character::suffer_from_schizophrenia(), Character::suffer_from_stimulants(), Character::suffer_from_sunburn(), Character::suffer_while_awake(), and Character::suffer_without_sleep().
points_in_range()
tripoint_range< tripoint > points_in_range (const map & m)
Returns a range enclosing all valid points of the map.
Definition at line 24 of file map_selector.cpp.
{
    const int z = m.get_abs_sub().z;
    const bool hasz = m.has_zlevels();
    return tripoint_range<tripoint>(
               tripoint( 0, 0, hasz ? -OVERMAP_DEPTH : z ),
               tripoint( SEEX * m.getmapsize() - 1, SEEY * m.getmapsize() - 1, hasz ? OVERMAP_HEIGHT : z ) );
}
References map::get_abs_sub(), map::getmapsize(), map::has_zlevels(), OVERMAP_DEPTH, OVERMAP_HEIGHT, SEEX, SEEY, and tripoint::z.
Referenced by random_point().
random_direction()
units::angle random_direction ()
Definition at line 37 of file rng.cpp.
{
    return rng_float( 0_pi_radians, 2_pi_radians );
}
References rng_float().
Referenced by VehicleSpawnFunction::builtin_parkinglot(), weather_effect::lightning(), MapExtras::mx_helicopter(), MapExtras::mx_roadworks(), and weather_effect::thunder().
random_entry() [1/2]
template<typename C , typename V = typename C::value_type> V random_entry (const C & container) inline
Same as above, but returns a default constructed value if the container is empty.
Definition at line 119 of file rng.h.
{
    if( container.empty() ) {
        return V();
    }
    auto iter = container.begin();
    std::advance( iter, rng( 0, container.size() - 1 ) );
    return *iter;
}
References rng().
random_entry() [2/2]
template<typename C , typename D , typename V = typename C::value_type> V random_entry (const C & container, D default_value) inline
Returns a random entry in the container.
The container must have a size() function and must support iterators as usual. For empty containers it returns the given default object. C is the container type, D is the type of the default value (which may differ from the return type) V is the type of the elements in the container. Note that this function does not return a reference because the default value could be a temporary object that is not valid after this function has left:
random_entry(vect, std::string("default"));
Definition at line 88 of file rng.h.
{
    if( container.empty() ) {
        return default_value;
    }
    auto iter = container.begin();
    std::advance( iter, rng( 0, container.size() - 1 ) );
    return *iter;
}
References rng().
Referenced by mdefense::acidsplash(), computer_session::action_cascade(), computer_session::activate_random_failure(), timed_event::actualize(), game::add_artifact_dreams(), mattack::antqueen(), jmapgen_vehicle::apply(), Character::best_quality_item(), Character::bionics_install_failure(), vehicle::break_off(), overmap::build_anthill(), overmap::build_lab(), overmap::build_mine(), activity_handlers::butcher_finish(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), leap_actor::call(), choose_ma_style(), activity_handlers::chop_tree_finish(), complete_construction(), cycle_action(), vehicle::damage(), map::draw_lab(), map::draw_mine(), map::draw_temple(), map::draw_triffid(), einkpc_download_memory_card(), computer_session::failure_pump_leak(), overmapbuffer::find_closest(), find_potential_computer_point(), overmapbuffer::find_random(), overmap::find_random_omt(), dig_activity_actor::finish(), iuse::fish_trap(), Character::forced_dismount(), generic_multi_activity_locations(), color_manager::get_random(), dreams::get_random_for_category(), mission_type::get_random_id(), item::get_random_material(), overmap_location::get_random_terrain(), MonsterGenerator::get_valid_hallucination(), npc::good_escape_direction(), item::handle_pickup_ownership(), vehicle::init_state(), vehicle::leak_fuel(), trapfunc::ledge(), MapExtras::mx_casings(), MapExtras::mx_looters(), MapExtras::mx_mayhem(), MapExtras::mx_portal_in(), obscure_message(), Character::old_mutate(), Character::perform_technique(), VehicleFacings::pick(), defense_game::pick_monster_wave(), character_funcs::pick_safe_adjacent_tile(), Character::pick_technique(), mission_start::place_deposit_box(), game::place_player(), mission_start::place_priest_diary(), overmap::place_rivers(), vehicle::place_spawn_items(), game::place_vehicle_nearby(), map::process_fields_in_submap(), sounds::process_sound_markers(), newcharacter::random_bad_trait(), npc_class::random_common(), newcharacter::random_good_trait(), random_house_in_city(), snippet_library::random_id_from_category(), map::random_outdoor_tile(), random_point(), scenario::random_start_location(), start_location::random_target(), spell::random_valid_target(), avatar::randomize(), mattack::resurrect(), reveal_any_target(), rod_fish(), monster::scent_move(), science_room(), sinkhole_safety_roll(), defense_game::spawn_wave(), mdeath::splatter(), map::spread_gas(), mission_util::target_om_ter_random(), trapfunc::tripwire(), mattack::upgrade(), musical_instrument_actor::use(), and npc::worker_downtime().
random_entry_opt()
template<typename C > auto random_entry_opt (C & container) -> cata::optional<decltype(std::ref(*container.begin()))> inline
Same as above but returns a reference to the chosen entry (if the container is not empty) or an empty optional object (if the container is empty).
This function handles empty containers without requiring an instance of the contained type when container is empty.
Definition at line 104 of file rng.h.
{
    if( container.empty() ) {
        return cata::nullopt;
    }
    auto iter = container.begin();
    std::advance( iter, rng( 0, container.size() - 1 ) );
    return std::ref( *iter );
}
References cata::nullopt, and rng().
Referenced by jmapgen_alternativly< PieceType >::apply(), and VehiclePlacement::pick().
random_entry_ref() [1/2]
template<typename C , typename V = typename C::value_type> std::enable_if<!is_std_array< C >::value, constV & >::type random_entry_ref (const C & container) inline
Same as above, but with a statically allocated default value (using the default constructor).
This allows to return a reference, either into the given container or to the default value.
Definition at line 149 of file rng.h.
{
    if( container.empty() ) {
        static const V default_value = V();
        return default_value;
    }
    auto iter = container.begin();
    std::advance( iter, rng( 0, container.size() - 1 ) );
    return *iter;
}
References rng().
Referenced by vehicle::alarm(), artifact_name(), dynamic_line_t::dynamic_line_t(), eff_fun_hallu(), iuse::fish_trap(), get_speech(), Character::modify_stimulation(), MapExtras::mx_grave(), new_artifact(), new_natural_artifact(), vehicle::operate_scoop(), Skill::random_skill(), rod_fish(), Character::suffer_from_schizophrenia(), game::update_stair_monsters(), scenario::weighted_random(), and scenario::weighted_random_profession().
random_entry_ref() [2/2]
template<typename V , std::size_t N> const V & random_entry_ref (const std::array< V, N > & container) inline
Definition at line 160 of file rng.h.
{
    static_assert( N > 0, "Need a non-empty array to get a random value from it" );
    return container[rng( 0, N - 1 )];
}
References rng().
random_entry_removed()
template<typename C , typename V = typename C::value_type> V random_entry_removed (C & container) inline
Returns a random entry in the container and removes it from the container.
The container must not be empty!
Definition at line 170 of file rng.h.
{
    auto iter = container.begin();
    std::advance( iter, rng( 0, container.size() - 1 ) );
    const V result = std::move( *iter ); // Copy because the original is removed and thereby destroyed
    container.erase( iter );
    return result;
}
References avatar_action::move(), and rng().
Referenced by iuse::artifact(), board_up(), destroy_random_component(), do_purify(), map::draw_temple(), new_artifact(), overmap::place_rivers(), overmap::place_roads(), map::process_fields_in_submap(), map::propagate_field(), iuse::purify_iv(), iuse::purify_smart(), map::spawn_monsters_submap_group(), monster::stumble(), and iuse::vortex().
random_point() [1/2]
cata::optional< tripoint > random_point (const map & m, const std::function< bool(const tripoint &)> & predicate)
Same as other random_point with a range enclosing all valid points of the map.
Definition at line 33 of file map_selector.cpp.
{
    return random_point( points_in_range( m ), predicate );
}
References points_in_range(), and random_point().
Referenced by choose_where_to_place_monster(), map::draw_connections(), map::draw_lab(), map::draw_mine(), game::forced_door_closing(), map::generate(), MapExtras::mx_collegekids(), MapExtras::mx_looters(), MapExtras::mx_marloss_pilgrimage(), MapExtras::mx_military(), MapExtras::mx_portal(), MapExtras::mx_roadblock(), MapExtras::mx_science(), MapExtras::mx_supplydrop(), overmap::place_forest_trails(), map::process_fields_in_submap(), random_point(), map::spawn_monsters_submap(), and place_npc_iuse::use().
random_point() [2/2]
cata::optional< tripoint > random_point (const tripoint_range< tripoint > & range, const std::function< bool(const tripoint &)> & predicate)
Returns a random point in the given range that satisfies the given predicate (if any).
Definition at line 39 of file map_selector.cpp.
{
    // Optimist approach: just assume there are plenty of suitable places and a randomly
    // chosen point will have a good chance to hit one of them.
    // If there are only few suitable places, we have to find them all, otherwise this loop may never finish.
    for( int tries = 0; tries < 10; ++tries ) {
        const tripoint p( rng( range.min().x, range.max().x ), rng( range.min().y, range.max().y ),
                          rng( range.min().z, range.max().z ) );
        if( predicate( p ) ) {
            return p;
        }
    }
    std::vector<tripoint> suitable;
    for( const auto &p : range ) {
        if( predicate( p ) ) {
            suitable.push_back( p );
        }
    }
    if( suitable.empty() ) {
        return {};
    }
    return random_entry( suitable );
}
References tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::min(), random_entry(), and rng().
rng()
int rng (int lo, int hi)
Definition at line 19 of file rng.cpp.
{
    static std::uniform_int_distribution<int> rng_int_dist;
    if( lo > hi ) {
        std::swap( lo, hi );
    }
    return rng_int_dist( rng_get_engine(), std::uniform_int_distribution<>::param_type( lo, hi ) );
}
References cata::hash64_detail::lo, rng_get_engine(), and cata::swap().
Referenced by check(), dice(), one_in(), random_entry(), random_entry_opt(), random_entry_ref(), and random_entry_removed().
rng_bits()
unsigned int rng_bits ()
Definition at line 12 of file rng.cpp.
{
    // Whole uint range.
    static std::uniform_int_distribution<unsigned int> rng_uint_dist;
    return rng_uint_dist( rng_get_engine() );
}
References rng_get_engine().
Referenced by weighted_list_detail::gen_rand_i(), snippet_library::random_from_category(), and game::start_game().
rng_exponential() [1/2]
double rng_exponential (double mean) inline
Definition at line 69 of file rng.h.
{
    return rng_exponential( 0.0, mean );
}
References rng_exponential().
rng_exponential() [2/2]
double rng_exponential (double min, double mean)
Definition at line 55 of file rng.cpp.
{
    const double adjusted_mean = mean - min;
    if( adjusted_mean <= 0.0 ) {
        return 0.0;
    }
    // lambda = 1 / mean
    return min + exponential_roll( 1.0 / adjusted_mean );
}
References exponential_roll().
Referenced by item::handle_craft_failure(), and rng_exponential().
rng_float() [1/2]
double rng_float (double lo, double hi)
Definition at line 28 of file rng.cpp.
{
    static std::uniform_real_distribution<double> rng_real_dist;
    if( lo > hi ) {
        std::swap( lo, hi );
    }
    return rng_real_dist( rng_get_engine(), std::uniform_real_distribution<>::param_type( lo, hi ) );
}
References cata::hash64_detail::lo, rng_get_engine(), and cata::swap().
Referenced by computer_session::action_irradiator(), map::bash(), Character::bonus_damage(), activity_handlers::butcher_finish(), butchery_drops_harvest(), melee_actor::call(), talk_function::caravan_depart(), crafting::complete_disassemble(), salvage_actor::cut_up(), explosion_handler::do_blast(), explosion_handler::do_blast_new(), monster::drop_items_on_death(), talk_function::forage_return(), iuse::granade_act(), harvest_common(), iexamine::ledge(), lightson_game::new_level(), vehicle::part_collision(), map::place_spawns(), vehicle::pldrive(), projectile_attack(), anatomy::random_body_part(), random_direction(), repair_item_actor::repair(), rng_float(), dispersion_sources::roll(), Character::roll_bash_damage(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), Character::scored_crit(), map::shake_vehicle(), vehicle::smash(), map::smash_items(), activity_handlers::spellcasting_finish(), and x_in_y().
rng_float() [2/2]
template<typename U > units::quantity< double, U > rng_float (units::quantity< double, U > lo, units::quantity< double, U > hi)
Definition at line 35 of file rng.h.
{
    return { rng_float( lo.value(), hi.value() ), U{} };
}
References cata::hash64_detail::lo, rng_float(), and units::quantity< V, U >::value().
rng_get_engine()
cata_default_random_engine & rng_get_engine ()
Definition at line 136 of file rng.cpp.
{
    // NOLINTNEXTLINE(cata-determinism)
    static cata_default_random_engine eng(
        std::chrono::high_resolution_clock::now().time_since_epoch().count() );
    return eng;
}
References detail::count().
Referenced by overmap::build_lab(), start_location::burn(), exponential_roll(), start_location::find_player_initial_location(), get_sectors(), weather_generator::get_wind_direction(), normal_roll(), overmap::place_forest_trails(), overmap::place_roads(), overmap::place_special_attempt(), overmap::place_specials(), overmap::place_specials_pass(), overmap::random_special_rotation(), rng(), rng_bits(), rng_float(), rng_set_engine_seed(), and npc::set_omt_destination().
rng_normal() [1/2]
double rng_normal (double hi) inline
Definition at line 60 of file rng.h.
{
    return rng_normal( 0.0, hi );
}
References rng_normal().
rng_normal() [2/2]
double rng_normal (double lo, double hi)
Definition at line 122 of file rng.cpp.
{
    if( lo > hi ) {
        std::swap( lo, hi );
    }
    const double stddev = ( hi - lo ) / 4;
    if( stddev == 0.0 ) {
        return hi;
    }
    double val = normal_roll( ( hi + lo ) / 2, stddev );
    return clamp( val, lo, hi );
}
References clamp(), cata::hash64_detail::lo, normal_roll(), and cata::swap().
Referenced by rng_normal(), and dispersion_sources::roll().
rng_set_engine_seed()
void rng_set_engine_seed (unsigned int seed)
Definition at line 144 of file rng.cpp.
{
    if( seed != 0 ) {
        rng_get_engine().seed( seed );
    }
}
References rng_get_engine(), and iuse::seed().
Referenced by main().
roll_remainder() [1/2]
int roll_remainder (double value)
Definition at line 96 of file rng.cpp.
{
    double integ;
    double frac = modf( value, &integ );
    if( value > 0.0 && value > integ && x_in_y( frac, 1.0 ) ) {
        integ++;
    } else if( value < 0.0 && value < integ && x_in_y( -frac, 1.0 ) ) {
        integ--;
    }
    return integ;
}
References x_in_y().
Referenced by Character::absorb_hit(), Character::adjust_for_focus(), jmapgen_monster::apply(), jmapgen_spawn_item::apply(), Character::apply_damage(), item::burn(), npc_trading::cash_to_favor(), Character::consume_effects(), Character::consume_remote_fuel(), player::craft_skill_gain(), Creature::deal_damage_handle_type(), eff_fun_mutating(), map::emit_field(), map::generate(), Character::get_miss_reason(), repair_item_actor::handle_components(), vehicle::handle_trap(), Character::irradiate(), magic_train(), Character::melee_attack(), Character::mend(), Character::mod_pain(), Character::mutate(), monster::on_load(), overmap::place_cities(), map::place_items(), map::place_spawns(), map::process_fields_in_submap(), map::produce_sap(), projectile_attack(), Character::regen(), retroactively_fill_from_funnel(), roll_remainder(), activity_handlers::study_spell_do_turn(), start_location::surround_with_monsters(), ranged::throw_item(), weather_effect::thunder(), SkillLevel::train(), Character::update_needs(), Character::update_stamina(), Character::update_stomach(), and vehicle::update_time().
roll_remainder() [2/2]
int roll_remainder (float value) inline
Definition at line 51 of file rng.h.
{
    return roll_remainder( static_cast<double>( value ) );
}
References roll_remainder().
x_in_y()
bool x_in_y (double x, double y)
Definition at line 75 of file rng.cpp.
{
    return rng_float( 0.0, 1.0 ) <= x / y;
}
References rng_float().
Referenced by roll_remainder().