Cataclysm BN: src/runtime_handlers.cpp File Reference
runtime_handlers.cpp File Reference
#include "runtime_handlers.h"
#include "cursesdef.h"
#include "debug.h"
#include "game.h"
Functions
void exit_handler (int status)
Function Documentation
exit_handler()
void exit_handler (int status)
Definition at line 7 of file runtime_handlers.cpp.
{
    deinitDebug();
    g.reset();
    catacurses::endwin();
    exit( status );
}
References deinitDebug(), catacurses::endwin(), and g.
Referenced by main(), and signal_handler().