Cataclysm BN: src/savegame_json.cpp File Reference
savegame_json.cpp File Reference
#include "enums.h"
#include "npc_favor.h"
#include "pldata.h"
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <set>
#include <sstream>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "active_item_cache.h"
#include "activity_actor.h"
#include "assign.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_io.h"
#include "cata_variant.h"
#include "cata_utility.h"
#include "character.h"
#include "character_encumbrance.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "clone_ptr.h"
#include "clzones.h"
#include "colony.h"
#include "computer.h"
#include "construction.h"
#include "consumption.h"
#include "craft_command.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "drop_token.h"
#include "effect.h"
#include "enum_conversions.h"
#include "event.h"
#include "faction.h"
#include "field.h"
#include "field_type.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_factory.h"
#include "item_location.h"
#include "itype.h"
#include "json.h"
#include "kill_tracker.h"
#include "lru_cache.h"
#include "magic.h"
#include "magic_teleporter_list.h"
#include "map_memory.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "mission.h"
#include "monster.h"
#include "morale.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "npc_class.h"
#include "optional.h"
#include "options.h"
#include "overmapbuffer.h"
#include "pickup_token.h"
#include "pimpl.h"
#include "player.h"
#include "player_activity.h"
#include "point.h"
#include "profession.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "relic.h"
#include "requirements.h"
#include "rng.h"
#include "scenario.h"
#include "skill.h"
#include "stats_tracker.h"
#include "stomach.h"
#include "string_id.h"
#include "submap.h"
#include "text_snippets.h"
#include "tileray.h"
#include "units.h"
#include "uistate.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "flag.h"
Classes
struct mm_elem
Namespaces
namespace charge_removal_blacklist
namespace to_cbc_migration
Functions
static void serialize (const weak_ptr_fast< monster > &obj, JsonOut &jsout)
static void deserialize (weak_ptr_fast< monster > &obj, JsonIn &jsin)
template<typename T >
static void load_legacy_craft_data (io::JsonObjectInputArchive &archive, T &value)
template<typename T >
static void load_legacy_craft_data (io::JsonObjectOutputArchive &, T &)
const std::set< itype_id > & charge_removal_blacklist::get ()
void charge_removal_blacklist::load (const JsonObject &jo)
void charge_removal_blacklist::reset ()
void to_cbc_migration::load (const JsonObject &jo)
void to_cbc_migration::reset ()
static bool to_cbc_migration::migration_required (const item &i)
static void to_cbc_migration::migrate (cata::colony< item > &stack)
Merge old individual items into new count-by-charges items with same id.
void serialize (const recipe_subset &value, JsonOut &jsout)
void deserialize (recipe_subset &value, JsonIn &jsin)
static void serialize (const item_comp &value, JsonOut &jsout)
static void serialize (const tool_comp &value, JsonOut &jsout)
static void deserialize (item_comp &value, JsonIn &jsin)
static void deserialize (tool_comp &value, JsonIn &jsin)
static void serialize (const quality_requirement &value, JsonOut &jsout)
static void deserialize (quality_requirement &value, JsonIn &jsin)
Variables
static const efftype_id effect_riding ("riding")
static const itype_id itype_battery ("battery")
static const itype_id itype_rad_badge ("rad_badge")
static const itype_id itype_radio ("radio")
static const itype_id itype_radio_on ("radio_on")
static const std::array< std::string, NUM_OBJECTS > obj_type_name
static std::set< itype_id > charge_removal_blacklist::removal_list
static std::set< itype_id > to_cbc_migration::the_list
Function Documentation
deserialize() [1/5]
static void deserialize (item_comp & value, JsonIn & jsin) static
Definition at line 3455 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "type", value.type );
    jo.read( "count", value.count );
    jo.read( "recoverable", value.recoverable );
}
References JsonObject::allow_omitted_members(), component::count, JsonIn::get_object(), JsonObject::read(), component::recoverable, and component::type.
deserialize() [2/5]
static void deserialize (quality_requirement & value, JsonIn & jsin) static
Definition at line 3484 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "type", value.type );
    jo.read( "count", value.count );
    jo.read( "level", value.level );
}
References JsonObject::allow_omitted_members(), quality_requirement::count, JsonIn::get_object(), quality_requirement::level, JsonObject::read(), and quality_requirement::type.
deserialize() [3/5]
void deserialize (recipe_subset & value, JsonIn & jsin)
Definition at line 3424 of file savegame_json.cpp.
{
    value.clear();
    jsin.start_array();
    while( !jsin.end_array() ) {
        value.include( &recipe_id( jsin.get_string() ).obj() );
    }
}
References recipe_subset::clear(), JsonIn::end_array(), JsonIn::get_string(), recipe_subset::include(), string_id< T >::obj(), and JsonIn::start_array().
deserialize() [4/5]
static void deserialize (tool_comp & value, JsonIn & jsin) static
Definition at line 3464 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "type", value.type );
    jo.read( "count", value.count );
    jo.read( "recoverable", value.recoverable );
}
References JsonObject::allow_omitted_members(), component::count, JsonIn::get_object(), JsonObject::read(), component::recoverable, and component::type.
deserialize() [5/5]
static void deserialize (weak_ptr_fast< monster > & obj, JsonIn & jsin) static
Definition at line 150 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    tripoint temp_pos;
    obj.reset();
    if( data.read( "monster_at", temp_pos ) ) {
        const auto monp = g->critter_tracker->find( temp_pos );
        if( monp == nullptr ) {
            debugmsg( "no monster found at %d,%d,%d", temp_pos.x, temp_pos.y, temp_pos.z );
            return;
        }
        obj = monp;
    }
    // TODO: if monsters/Creatures ever get unique ids,
    // look for a differently named member, e.g.
    //     data.read( "unique_id", unique_id );
    //     obj = g->id_registry->from_id( unique_id)
    //    }
}
References JsonObject::allow_omitted_members(), debugmsg, g, JsonIn::get_object(), int_id< T >::obj(), JsonObject::read(), tripoint::x, tripoint::y, and tripoint::z.
load_legacy_craft_data() [1/2]
template<typename T > static void load_legacy_craft_data (io::JsonObjectInputArchive & archive, T & value) static
Definition at line 2071 of file savegame_json.cpp.
{
    archive.allow_omitted_members();
    if( archive.has_member( "making" ) ) {
        value = cata::make_value<typename T::element_type>();
        value->deserialize( archive );
    }
}
References JsonObject::allow_omitted_members(), and JsonObject::has_member().
Referenced by item::io().
load_legacy_craft_data() [2/2]
template<typename T > static void load_legacy_craft_data (io::JsonObjectOutputArchive & , T &) static
Definition at line 2082 of file savegame_json.cpp.
{
}
serialize() [1/5]
static void serialize (const item_comp & value, JsonOut & jsout) static
Definition at line 3433 of file savegame_json.cpp.
{
    jsout.start_object();
    jsout.member( "type", value.type );
    jsout.member( "count", value.count );
    jsout.member( "recoverable", value.recoverable );
    jsout.end_object();
}
References component::count, JsonOut::end_object(), JsonOut::member(), component::recoverable, JsonOut::start_object(), and component::type.
serialize() [2/5]
static void serialize (const quality_requirement & value, JsonOut & jsout) static
Definition at line 3473 of file savegame_json.cpp.
{
    jsout.start_object();
    jsout.member( "type", value.type );
    jsout.member( "count", value.count );
    jsout.member( "level", value.level );
    jsout.end_object();
}
References quality_requirement::count, JsonOut::end_object(), quality_requirement::level, JsonOut::member(), JsonOut::start_object(), and quality_requirement::type.
serialize() [3/5]
void serialize (const recipe_subset & value, JsonOut & jsout)
Definition at line 3415 of file savegame_json.cpp.
{
    jsout.start_array();
    for( const auto &entry : value ) {
        jsout.write( entry->ident() );
    }
    jsout.end_array();
}
References JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
serialize() [4/5]
static void serialize (const tool_comp & value, JsonOut & jsout) static
Definition at line 3444 of file savegame_json.cpp.
{
    jsout.start_object();
    jsout.member( "type", value.type );
    jsout.member( "count", value.count );
    jsout.member( "recoverable", value.recoverable );
    jsout.end_object();
}
References component::count, JsonOut::end_object(), JsonOut::member(), component::recoverable, JsonOut::start_object(), and component::type.
serialize() [5/5]
static void serialize (const weak_ptr_fast< monster > & obj, JsonOut & jsout) static
Definition at line 134 of file savegame_json.cpp.
{
    if( const auto monster_ptr = obj.lock() ) {
        jsout.start_object();
        jsout.member( "monster_at", monster_ptr->pos() );
        // TODO: if monsters/Creatures ever get unique ids,
        // create a differently named member, e.g.
        //     jsout.member("unique_id", monster_ptr->getID());
        jsout.end_object();
    } else {
        // Monster went away. It's up the activity handler to detect this.
        jsout.write_null();
    }
}
References JsonOut::end_object(), JsonOut::member(), int_id< T >::obj(), JsonOut::start_object(), and JsonOut::write_null().
Variable Documentation
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by Character::load().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by vehicle_part::deserialize().
itype_rad_badge
const itype_id itype_rad_badge("rad_badge") ("rad_badge") static
Referenced by item::io().
itype_radio
const itype_id itype_radio("radio") ("radio") static
Referenced by item::io().
itype_radio_on
const itype_id itype_radio_on("radio_on") ("radio_on") static
Referenced by item::io().
obj_type_name
const std::array<std::string, NUM_OBJECTS> obj_type_name static
Initial value:
= { { "OBJECT_NONE", "OBJECT_ITEM", "OBJECT_ACTOR", "OBJECT_PLAYER",
        "OBJECT_NPC", "OBJECT_MONSTER", "OBJECT_VEHICLE", "OBJECT_TRAP", "OBJECT_FIELD",
        "OBJECT_TERRAIN", "OBJECT_FURNITURE"
    }
}
Definition at line 127 of file savegame_json.cpp.
Referenced by avatar::load(), and avatar::store().