Cataclysm BN: src/savegame.cpp File Reference
savegame.cpp File Reference
#include "game.h"
#include <algorithm>
#include <map>
#include <sstream>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "achievement.h"
#include "avatar.h"
#include "basecamp.h"
#include "cata_io.h"
#include "coordinate_conversions.h"
#include "creature_tracker.h"
#include "debug.h"
#include "drop_token.h"
#include "enum_conversions.h"
#include "faction.h"
#include "hash_utils.h"
#include "int_id.h"
#include "json.h"
#include "kill_tracker.h"
#include "map.h"
#include "messages.h"
#include "mission.h"
#include "mongroup.h"
#include "monster.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmap_types.h"
#include "popup.h"
#include "regional_settings.h"
#include "scent_map.h"
#include "stats_tracker.h"
#include "string_id.h"
#include "translations.h"
#include "ui_manager.h"
#include "weather.h"
Classes
struct mongroup_bin_eq
struct mongroup_hash
Functions
static void chkversion (std::istream &fin)
static void unserialize_array_from_compacted_sequence (JsonIn &jsin, bool(&array)[OMAPX][OMAPY])
static void serialize_array_to_compacted_sequence (JsonOut &json, const bool(&array)[OMAPX][OMAPY])
Variables
const int savegame_version = 28
int savegame_loading_version = savegame_version
std::unordered_set< std::string > obsolete_terrains
Function Documentation
chkversion()
static void chkversion (std::istream & fin) static
Definition at line 148 of file savegame.cpp.
{
    if( fin.peek() == '#' ) {
        std::string vline;
        getline( fin, vline );
        std::string tmphash;
        std::string tmpver;
        int savedver = -1;
        std::stringstream vliness( vline );
        vliness >> tmphash >> tmpver >> savedver;
        if( tmpver == "version" && savedver != -1 ) {
            savegame_loading_version = savedver;
        }
    }
}
References savegame_loading_version.
Referenced by game::unserialize(), overmap::unserialize(), game::unserialize_master(), and overmap::unserialize_view().
serialize_array_to_compacted_sequence()
static void serialize_array_to_compacted_sequence (JsonOut & json, const bool(&) array[OMAPX][OMAPY]) static
Definition at line 762 of file savegame.cpp.
{
    int count = 0;
    int lastval = -1;
    for( int j = 0; j < OMAPY; j++ ) {
        for( const auto &array_col : array ) {
            const int value = array_col[j];
            if( value != lastval ) {
                if( count ) {
                    json.write( count );
                    json.end_array();
                }
                lastval = value;
                json.start_array();
                json.write( static_cast<bool>( value ) );
                count = 1;
            } else {
                count++;
            }
        }
    }
    json.write( count );
    json.end_array();
}
References detail::count(), JsonOut::end_array(), OMAPY, JsonOut::start_array(), and JsonOut::write().
Referenced by overmap::serialize_view().
unserialize_array_from_compacted_sequence()
static void unserialize_array_from_compacted_sequence (JsonIn & jsin, bool(&) array[OMAPX][OMAPY]) static
Definition at line 682 of file savegame.cpp.
{
    int count = 0;
    bool value = false;
    for( int j = 0; j < OMAPY; j++ ) {
        for( auto &array_col : array ) {
            if( count == 0 ) {
                jsin.start_array();
                jsin.read( value );
                jsin.read( count );
                jsin.end_array();
            }
            count--;
            array_col[j] = value;
        }
    }
}
References detail::count(), JsonIn::end_array(), OMAPY, JsonIn::read(), and JsonIn::start_array().
Referenced by overmap::unserialize_view().
Variable Documentation
obsolete_terrains
std::unordered_set<std::string> obsolete_terrains
Definition at line 333 of file savegame.cpp.
Referenced by overmap::is_obsolete_terrain(), overmap::load_obsolete_terrains(), and overmap::reset_obsolete_terrains().
savegame_loading_version
int savegame_loading_version = savegame_version
Definition at line 64 of file savegame.cpp.
Referenced by chkversion(), item::deserialize(), npc_chatbin::deserialize(), vehicle::deserialize(), avatar::load(), submap::load(), game::unserialize(), and game::unserialize_master().
savegame_version
const int savegame_version = 28
Definition at line 57 of file savegame.cpp.
Referenced by mapbuffer::save_quad(), game::serialize(), overmap::serialize(), game::serialize_master(), overmap::serialize_view(), and game::unserialize_master().