Cataclysm BN: src/shadowcasting.h File Reference
shadowcasting.h File Reference
#include <algorithm>
#include <array>
#include <functional>
#include <string>
#include "game_constants.h"
#include "lightmap.h"
Classes
struct four_quadrants
Macros
#define CATA_SRC_SHADOWCASTING_H
Typedefs
template<typename T >
using array_of_grids_of = std::array< T(*)[MAPSIZE_X][MAPSIZE_Y], OVERMAP_LAYERS >
Enumerations
enum class quadrant {
NE , SE , SW , NW ,
default_ = NE
}
Functions
float sight_calc (const float &numerator, const float &transparency, const int &distance)
bool sight_check (const float &transparency, const float &)
void update_light (float &update, const float &new_value, quadrant)
void update_light_quadrants (four_quadrants &update, const float &new_value, quadrant q)
float accumulate_transparency (const float &cumulative_transparency, const float &current_transparency, const int &distance)
float sight_from_lookup (const float &numerator, const float &transparency, const int &)
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate>
void castLightAll (Out(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const T(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance=0, T numerator=1.0)
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, T(*)(const T &, const T &, const int &) lookup_calc>
void castLightAllWithLookup (Out(&output_cache)[MAPSIZE_X][MAPSIZE_Y], const T(&input_array)[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&blocked_array)[MAPSIZE_X][MAPSIZE_Y], const point &offset, int offsetDistance=0, T numerator=1.0)
template<typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate>
void cast_zlight (const array_of_grids_of< T > &output_caches, const array_of_grids_of< const T > &input_arrays, const array_of_grids_of< const bool > &floor_caches, const array_of_grids_of< const diagonal_blocks > &blocked_caches, const tripoint &origin, int offset_distance, T numerator)
Macro Definition Documentation
CATA_SRC_SHADOWCASTING_H
#define CATA_SRC_SHADOWCASTING_H
Definition at line 3 of file shadowcasting.h.
Typedef Documentation
array_of_grids_of
template<typename T > using array_of_grids_of = std::array<T(*)[MAPSIZE_X][MAPSIZE_Y], OVERMAP_LAYERS>
Definition at line 134 of file shadowcasting.h.
Enumeration Type Documentation
quadrant
enum class quadrant strong
Enumerator
NE
SE
SW
NW
default_
Definition at line 22 of file shadowcasting.h.
                    {
    NE, SE, SW, NW,
    default_ = NE
};
Function Documentation
accumulate_transparency()
float accumulate_transparency (const float & cumulative_transparency, const float & current_transparency, const int & distance) inline
Definition at line 101 of file shadowcasting.h.
{
    return ( ( distance - 1 ) * cumulative_transparency + current_transparency ) / distance;
}
Referenced by map::apply_directional_light(), and map::apply_light_source().
cast_zlight()
template<typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate> void cast_zlight (const array_of_grids_of< T > & output_caches, const array_of_grids_of< const T > & input_arrays, const array_of_grids_of< const bool > & floor_caches, const array_of_grids_of< const diagonal_blocks > & blocked_caches, const tripoint & origin, int offset_distance, T numerator)
Definition at line 1116 of file lightmap.cpp.
{
    // Down
    cast_zlight_segment < 0, 1, 0, 1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 1, 0, 0, 0, 1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, 1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, 1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, 1, 0, -1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 1, 0, 0, 0, -1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, -1, 0, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, -1, 0, -1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    // Up
    cast_zlight_segment<0, 1, 0, 1, 0, 0, 1, T, calc, check, accumulate>(
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment<1, 0, 0, 0, 1, 0, 1, T, calc, check, accumulate>(
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, 1, 0, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, 1, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, 1, 0, -1, 0, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 1, 0, 0, 0, -1, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < 0, -1, 0, -1, 0, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
    cast_zlight_segment < -1, 0, 0, 0, -1, 0, 1, T, calc, check, accumulate > (
        output_caches, input_arrays, floor_caches, blocked_caches, origin, offset_distance, numerator );
}
References cast_zlight_segment(), and detail::check().
castLightAll()
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate> void castLightAll (Out(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const T(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], point offset, int offsetDistance = 0, T numerator = 1.0)
Definition at line 1423 of file lightmap.cpp.
{
    castLight< 0, 1, 1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight< 1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 0, -1, 1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < -1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 0, 1, -1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < 0, -1, -1, 0, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLight < -1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, nullptr, nullptr > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
}
References castLight(), and detail::check().
Referenced by explosion_handler::shrapnel().
castLightAllWithLookup()
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate, T(*)(const T &, const T &, const int &) lookup_calc> void castLightAllWithLookup (Out(&) output_cache[MAPSIZE_X][MAPSIZE_Y], const T(&) input_array[MAPSIZE_X][MAPSIZE_Y], const diagonal_blocks(&) blocked_array[MAPSIZE_X][MAPSIZE_Y], const point & offset, int offsetDistance = 0, T numerator = 1.0)
Definition at line 1538 of file lightmap.cpp.
{
    castLightWithLookup< 0, 1, 1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup< 1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, lookup_calc>(
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 0, -1, 1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < -1, 0, 0, 1, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 0, 1, -1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < 0, -1, -1, 0, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
    castLightWithLookup < -1, 0, 0, -1, T, Out, calc, check, update_output, accumulate, lookup_calc > (
        output_cache, input_array, blocked_array, offset, offsetDistance, numerator );
}
References castLightWithLookup(), and detail::check().
sight_calc()
float sight_calc (const float & numerator, const float & transparency, const int & distance) inline
Definition at line 85 of file shadowcasting.h.
{
    return numerator / std::exp( transparency * distance );
}
sight_check()
bool sight_check (const float & transparency, const float &) inline
Definition at line 89 of file shadowcasting.h.
{
    return transparency > LIGHT_TRANSPARENCY_SOLID;
}
References LIGHT_TRANSPARENCY_SOLID.
sight_from_lookup()
float sight_from_lookup (const float & numerator, const float & transparency, const int &) inline
Definition at line 107 of file shadowcasting.h.
{
    return numerator * transparency;
}
update_light()
void update_light (float & update, const float & new_value, quadrant) inline
Definition at line 93 of file shadowcasting.h.
{
    update = std::max( update, new_value );
}
update_light_quadrants()
void update_light_quadrants (four_quadrants & update, const float & new_value, quadrant q) inline
Definition at line 97 of file shadowcasting.h.
{
    update[q] = std::max( update[q], new_value );
}
Referenced by map::apply_directional_light(), map::apply_light_source(), and map::generate_lightmap().