Cataclysm BN: src/shape_impl.h File Reference
shape_impl.h File Reference
#include <algorithm>
#include <cmath>
#include <memory>
#include <set>
#include <vector>
#include "cata_utility.h"
#include "cuboid_rectangle.h"
#include "line.h"
#include "matrix_math.h"
#include "shape.h"
#include "point.h"
#include "point_float.h"
#include "map_iterator.h"
#include "make_static.h"
#include "json.h"
#include "units_angle.h"
Classes
class shape_impl
class cone
Cone centered along y axis.
class cylinder
class empty_shape
class offset_shape
Offsets a shape by a point.
class rotate_z_shape
Rotates a shape around z axis by a given angle.
class shape_min
class shape_exclude_circle
class shape_factory_impl
class cone_factory
Macros
#define CATA_SRC_SHAPE_IMPL_H
Functions
template<typename T >
constexpr T sign (T x)
Macro Definition Documentation
CATA_SRC_SHAPE_IMPL_H
#define CATA_SRC_SHAPE_IMPL_H
Definition at line 3 of file shape_impl.h.
Function Documentation
sign()
template<typename T > constexpr T sign (T x) constexpr
Definition at line 23 of file shape_impl.h.
{
    return x > 0 ? 1 : ( x < 0 ? -1 : 0 );
}
Referenced by vehicle::power_to_energy_bat(), player_morale::set_worn(), cone::signed_distance(), detail::write_float(), and detail::write_nonfinite().