Cataclysm BN: src/start_location.cpp File Reference
start_location.cpp File Reference
#include "start_location.h"
#include <algorithm>
#include <climits>
#include <memory>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "debug.h"
#include "enum_conversions.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "int_id.h"
#include "json.h"
#include "map.h"
#include "map_extras.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "player.h"
#include "pldata.h"
#include "point.h"
#include "rng.h"
#include "string_id.h"
Namespaces
namespace anonymous_namespace{start_location.cpp}
Functions
static void add_boardable (const map &m, const tripoint &p, std::vector< tripoint > &vec)
static void board_up (map &m, const tripoint_range< tripoint > &range)
static int rate_location (map &m, const tripoint &p, const bool must_be_inside, const int bash_str, const int attempt, int(&checked)[MAPSIZE_X][MAPSIZE_Y])
Helper for place_player Flood-fills the area from a given point, then returns the area it found.
static void add_monsters (const tripoint_abs_omt &omtstart, const mongroup_id &type, float expected_points)
Variables
static const efftype_id effect_bleed ("bleed")
generic_factory< start_location > anonymous_namespace{start_location.cpp}::all_start_locations ("start locations")
Function Documentation
add_boardable()
static void add_boardable (const map & m, const tripoint & p, std::vector< tripoint > & vec) static
Definition at line 110 of file start_location.cpp.
{
    if( m.has_furn( p ) ) {
        // Don't need to board this up, is already occupied
        return;
    }
    if( m.ter( p ) != t_floor ) {
        // Other terrain (door, wall, ...), not boarded either
        return;
    }
    if( m.is_outside( p ) ) {
        // Don't board up the outside
        return;
    }
    if( std::find( vec.begin(), vec.end(), p ) != vec.end() ) {
        // Already registered to be boarded
        return;
    }
    vec.push_back( p );
}
References detail::find(), map::has_furn(), map::is_outside(), t_floor, and map::ter().
Referenced by board_up().
add_monsters()
static void add_monsters (const tripoint_abs_omt & omtstart, const mongroup_id & type, float expected_points) static
Definition at line 435 of file start_location.cpp.
{
    const tripoint_abs_sm spawn_location = project_to<coords::sm>( omtstart );
    tinymap m;
    m.load( spawn_location, false );
    // map::place_spawns internally multiplies density by rng(10, 50)
    const float density = expected_points / ( ( 10 + 50 ) / 2.0 );
    m.place_spawns( type, 1, point_zero, point( SEEX * 2 - 1, SEEY * 2 - 1 ), density );
    m.save();
}
References map::load(), map::place_spawns(), point_zero, map::save(), SEEX, SEEY, and type.
Referenced by start_location::surround_with_monsters().
board_up()
static void board_up (map & m, const tripoint_range< tripoint > & range) static
Strength determines what furniture might be used as a starting area barricade
Definition at line 131 of file start_location.cpp.
{
    std::vector<tripoint> furnitures1;
    std::vector<tripoint> furnitures2;
    std::vector<tripoint> boardables;
    for( const tripoint &p : range ) {
        bool must_board_around = false;
        const ter_id t = m.ter( p );
        if( t == t_window_domestic || t == t_window || t == t_window_no_curtains ) {
            // Windows are always to the outside and must be boarded
            must_board_around = true;
            m.ter_set( p, t_window_boarded );
        } else if( t == t_door_c || t == t_door_locked || t == t_door_c_peep ) {
            // Only board up doors that lead to the outside
            if( m.is_outside( p + tripoint_north ) || m.is_outside( p + tripoint_south ) ||
                m.is_outside( p + tripoint_east ) || m.is_outside( p + tripoint_west ) ) {
                m.ter_set( p, t_door_boarded );
                must_board_around = true;
            } else {
                // internal doors are opened instead
                m.ter_set( p, t_door_o );
            }
        }
        if( must_board_around ) {
            // Board up the surroundings of the door/window
            for( const tripoint &neigh : points_in_radius( p, 1 ) ) {
                if( neigh == p ) {
                    continue;
                }
                add_boardable( m, neigh, boardables );
            }
        }
    }
    // Find all furniture that can be used to board up some place
    for( const tripoint &p : range ) {
        if( std::find( boardables.begin(), boardables.end(), p ) != boardables.end() ) {
            continue;
        }
        if( !m.has_furn( p ) ) {
            continue;
        }
        // If the furniture is movable and the character can move it, use it to barricade
        // g->u is workable here as NPCs by definition are not starting the game.  (Let's hope.)
        ///\EFFECT_STR determines what furniture might be used as a starting area barricade
        if( m.furn( p ).obj().is_movable() && m.furn( p ).obj().move_str_req < g->u.get_str() ) {
            if( m.furn( p ).obj().movecost == 0 ) {
                // Obstacles are better, prefer them
                furnitures1.push_back( p );
            } else {
                furnitures2.push_back( p );
            }
        }
    }
    while( ( !furnitures1.empty() || !furnitures2.empty() ) && !boardables.empty() ) {
        const tripoint fp = random_entry_removed( furnitures1.empty() ? furnitures2 : furnitures1 );
        const tripoint bp = random_entry_removed( boardables );
        m.furn_set( bp, m.furn( fp ) );
        m.furn_set( fp, f_null );
        auto destination_items = m.i_at( bp );
        for( const item &moved_item : m.i_at( fp ) ) {
            destination_items.insert( moved_item );
        }
        m.i_clear( fp );
    }
}
References add_boardable(), f_null, detail::find(), map::furn(), map::furn_set(), g, map::has_furn(), map::i_at(), map::i_clear(), map_stack::insert(), furn_t::is_movable(), map::is_outside(), furn_t::move_str_req, map_data_common_t::movecost, int_id< T >::obj(), points_in_radius(), random_entry_removed(), t_door_boarded, t_door_c, t_door_c_peep, t_door_locked, t_door_o, t_window, t_window_boarded, t_window_domestic, t_window_no_curtains, map::ter(), map::ter_set(), tripoint_east, tripoint_north, tripoint_south, and tripoint_west.
Referenced by start_location::prepare_map().
rate_location()
static int rate_location (map & m, const tripoint & p, const bool must_be_inside, const int bash_str, const int attempt, int(&) checked[MAPSIZE_X][MAPSIZE_Y]) static
Helper for place_player Flood-fills the area from a given point, then returns the area it found.
Considers unpassable tiles passable if they can be bashed down or opened. Will return INT_MAX if it reaches upstairs or map edge. We can't really use map::route here, because it expects a destination Maybe TODO: Allow "picking up" items or parts of bashable furniture and using them to help with bash attempts.
Definition at line 250 of file start_location.cpp.
{
    if( ( must_be_inside && m.is_outside( p ) ) ||
        m.impassable( p ) ||
        checked[p.x][p.y] > 0 ) {
        return 0;
    }
    // Vector that will be used as a stack
    std::vector<tripoint> st;
    st.reserve( MAPSIZE_X * MAPSIZE_Y );
    st.push_back( p );
    // If not checked yet and either can be moved into, can be bashed down or opened,
    // add it on the top of the stack.
    const auto maybe_add = [&]( const tripoint & pt, const tripoint & from ) {
        if( checked[pt.x][pt.y] >= attempt ) {
            return;
        }
        if( m.passable( pt ) ||
            m.bash_resistance( pt ) <= bash_str ||
            m.open_door( pt, !m.is_outside( from ), true ) ) {
            st.push_back( pt );
        }
    };
    int area = 0;
    while( !st.empty() ) {
        area++;
        const tripoint cur = st.back();
        st.pop_back();
        checked[cur.x][cur.y] = attempt;
        if( cur.x == 0 || cur.x == MAPSIZE_X - 1 ||
            cur.y == 0 || cur.y == MAPSIZE_Y - 1 ||
            m.has_flag( "GOES_UP", cur ) ) {
            return INT_MAX;
        }
        for( const tripoint &delta : eight_horizontal_neighbors ) {
            tripoint pt = cur + delta;
            pt.z = p.z;
            maybe_add( pt, cur );
        }
    }
    return area;
}
References map::bash_resistance(), eight_horizontal_neighbors, map::has_flag(), map::impassable(), map::is_outside(), MAPSIZE_X, MAPSIZE_Y, map::open_door(), map::passable(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by start_location::place_player().
Variable Documentation
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by start_location::handle_heli_crash().