Cataclysm BN: src/string_formatter.h File Reference
string_formatter.h File Reference
#include <cstddef>
#include <string>
#include <type_traits>
#include <typeinfo>
#include <utility>
#include "optional.h"
Classes
struct cata::is_instance_of< typename, class >
struct cata::is_instance_of< TMPL< T >, TMPL >
class cata::string_formatter
Type-safe and undefined-behavior free wrapper over sprintf.
Namespaces
namespace cata
Macros
#define CATA_SRC_STRING_FORMATTER_H
Typedefs
template<typename T >
using cata::is_numeric = typename std::conditional< std::is_arithmetic< typename std::decay< T >::type >::value &&!std::is_same< typename std::decay< T >::type, bool >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_integer = typename std::conditional< is_numeric< T >::value &&!std::is_floating_point< typename std::decay< T >::type >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_char = typename std::conditional< std::is_same< typename std::decay< T >::type, char >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_string = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_cstring = typename std::conditional< std::is_same< typename std::decay< T >::type, const char * >::value||std::is_same< typename std::decay< T >::type, char * >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_translation = typename std::conditional< std::is_same< typename std::decay< T >::type, translation >::value, std::true_type, std::false_type >::type
template<typename T >
using cata::is_string_id = typename std::conditional< is_instance_of< typename std::decay< T >::type, string_id >::value, std::true_type, std::false_type >::type
Functions
void cata::throw_error (const string_formatter &, const std::string &)
const char * cata::string_formatter_set_temp_buffer (const string_formatter &, const std::string &)
std::string cata::handle_string_format_error ()
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&is_integer< T >::value, RT >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&std::is_enum< typenamestd::decay< T >::type >::value, RT >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_floating_point< RT >::value &&is_numeric< T >::value &&!is_integer< T >::value, RT >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, void * >::value &&std::is_pointer< typenamestd::decay< T >::type >::value, void * >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, constchar * >::value &&is_string< T >::value, constchar * >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, constchar * >::value &&is_cstring< T >::value, constchar * >::type cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, constchar * >::value &&is_translation< T >::value, constchar * >::type cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, constchar * >::value &&is_string_id< T >::value, constchar * >::type cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, constchar * >::value &&is_numeric< T >::value &&!is_char< T >::value, constchar * >::type cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, constchar * >::value &&is_numeric< T >::value &&is_char< T >::value, constchar * >::type cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
RT cata::convert (RT *, const string_formatter &sf, T &&,...)
void cata_print_stdout (const std::string &s)
Print string to stdout.
void cata_print_stderr (const std::string &s)
Print string to stderr.
template<typename ... Args>
std::string string_format (std::string format, Args &&...args)
Simple wrapper over string_formatter::parse.
template<typename ... Args>
std::string string_format (const char *const format, Args &&...args)
template<typename T , typename ... Args>
std::enable_if< cata::is_translation< T >::value, std::string >::type string_format (T &&format, Args &&...args)
template<typename ... Args>
void cata_printf (std::string format, Args &&...args)
Same as string_format, but prints its result to stdout.
template<typename ... Args>
void cata_printf (const char *const format, Args &&...args)
Macro Definition Documentation
CATA_SRC_STRING_FORMATTER_H
#define CATA_SRC_STRING_FORMATTER_H
Definition at line 3 of file string_formatter.h.
Function Documentation
cata_print_stderr()
void cata_print_stderr (const std::string & s)
Print string to stderr.
Definition at line 171 of file string_formatter.cpp.
{
    fputs( s.c_str(), stderr );
}
cata_print_stdout()
void cata_print_stdout (const std::string & s)
Print string to stdout.
Definition at line 166 of file string_formatter.cpp.
{
    fputs( s.c_str(), stdout );
}
Referenced by cata_printf().
cata_printf() [1/2]
template<typename ... Args> void cata_printf (const char *const format, Args &&... args) inline
Definition at line 456 of file string_formatter.h.
{
    cata_printf( std::string( format ), std::forward<Args>( args )... );
}
References cata_printf(), and format().
cata_printf() [2/2]
template<typename ... Args> void cata_printf (std::string format, Args &&... args) inline
Same as string_format, but prints its result to stdout.
Definition at line 449 of file string_formatter.h.
{
    std::string s = string_format( std::move( format ), std::forward<Args>( args )... );
    cata_print_stdout( s );
}
References cata_print_stdout(), format(), avatar_action::move(), and string_format().
Referenced by cata_printf(), main(), and anonymous_namespace{main.cpp}::printHelpMessage().
string_format() [1/3]
template<typename ... Args> std::string string_format (const char *const format, Args &&... args) inline
Definition at line 429 of file string_formatter.h.
{
    return string_format( std::string( format ), std::forward<Args>( args )... );
}
References format(), and string_format().
string_format() [2/3]
template<typename ... Args> std::string string_format (std::string format, Args &&... args) inline
Simple wrapper over string_formatter::parse.
It catches any exceptions and returns some error string. Otherwise it just returns the formatted string.
These functions perform string formatting according to the rules of the printf function, see man 3 printf or any other documentation.
In short: the format parameter is a string with optional placeholders, which will be replaced with formatted data from the further arguments. The further arguments must have a type that matches the type expected by the placeholder. The placeholders look like this:
s expects an argument of type const char* or std::string or numeric (which is converted to a string via std::to_string), which is inserted as is.
d expects an argument of an integer type (int, short, ...), which is formatted as decimal number.
f expects a numeric argument (integer / floating point), which is formatted as decimal number.
There are more placeholders and options to them (see documentation of printf). Note that this wrapper (via string_formatter) automatically converts the arguments to match the given format specifier (if possible) - see Convert functions for string_formatter.
Definition at line 418 of file string_formatter.h.
{
    try {
        cata::string_formatter formatter( std::move( format ) );
        formatter.parse( std::forward<Args>( args )... );
        return formatter.get_output();
    } catch( ... ) {
        return cata::handle_string_format_error();
    }
}
References format(), cata::handle_string_format_error(), and avatar_action::move().
Referenced by activatable_inventory_preset::activatable_inventory_preset(), Character::activate_bionic(), memorial_logger::add(), game::add_artifact_dreams(), game::add_artifact_messages(), add_disassemblables(), monexamine::add_leash(), mod_manager::add_mods(), add_msg(), Creature::add_msg_if_npc(), Creature::add_msg_if_player(), Creature::add_msg_player_or_npc(), Creature::add_msg_player_or_say(), add_salvagables(), vehicle::add_toggle_to_opts(), map::add_vehicle(), uilist::addentry(), Character::age_string(), item::already_used_by_player(), item::ammo_info(), item::animal_armor_info(), spell::aoe_string(), MapExtras::apply_function(), item::armor_fit_info(), item::armor_info(), armor_inventory_preset::armor_inventory_preset(), iuse::artifact(), artifact_name(), iexamine::autodoc(), autodoc_internal(), vehicle::automatic_fire_turret(), vehicle::backfire(), item::basic_info(), recipe::batch_savings_string(), item::battery_info(), item::bionic_info(), basecamp::board_name(), Character::body_window(), item::book_info(), mdeath::boomer(), mdeath::boomer_glow(), build_bionic_poweronly_string(), butcher_submenu(), veh_interact::calc_overview(), camp_car_description(), camp_trip_description(), Character::can_eat(), Character::can_install_bionics(), npc::can_read(), veh_interact::can_remove_part(), vehicle::can_unmount(), Character::can_wear(), iuse::capture_monster_act(), carry_volume_string(), carry_weight_string(), cata_printf(), debug_menu::character_edit_menu(), game::chat(), enchantment::check(), weather_type::check(), jmapgen_sealed_item::check(), Item_factory::check_ammo_type(), recipe::check_blueprint_requirements(), harvest_list::check_consistency(), Item_factory::check_definitions(), cata_libintl::trans_catalogue::check_encoding(), dependency_tree::check_for_conflicting_dependencies(), check_martialarts(), game::check_safe_mode_allowed(), cata_libintl::trans_catalogue::check_string_plurals(), cata_libintl::trans_catalogue::check_string_terminators(), choose_ma_style(), game::cleanup_at_end(), anonymous_namespace{armor_layers.cpp}::clothing_properties(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), color_number(), spell::colorized_fail_percent(), colorized_feature_description_at(), colorized_field_description_at(), colorized_ter_name_flags_at(), item::combat_info(), comestible_inventory_preset::comestible_inventory_preset(), game_menus::inv::common(), talk_function::companion_choose(), npc::complain(), item::component_info(), Character::conduct_blood_analysis(), mdeath::conflagration(), construction_menu(), item::contain_monster(), game_menus::inv::container_for(), item::container_info(), item::contents_info(), basecamp::craft_description(), craft_progress_message(), Item_factory::create_artifact_id(), it_artifact_tool::create_name(), overmap_ui::create_note(), talk_response::create_option_line(), spell::damage_string(), debug_menu::debug(), debug_drop_list(), cata_libintl::PlfNode::debug_dump(), debug_error_prompt(), item_group::debug_spawn(), trait_group::debug_spawn(), MapExtras::debug_spawn_test(), decorate_panel(), morale_type_data::describe(), item_location::impl::item_in_container::describe(), describe(), harvest_list::describe(), Creature::describe_infrared(), score::description(), new_field::deserialize(), mission::dialogue_for_topic(), direction_suffix(), item::disassembly_info(), effect::disp_desc(), character_display::disp_info(), effect::disp_name(), vehicle::disp_name(), Character::disp_name(), monster::disp_name(), map::disp_name(), player_morale::display(), item::display_money(), veh_interact::display_name(), item::display_name(), Character::dispose_item(), npc::do_player_activity(), veh_interact::do_refill(), dodge_skill_text(), char_creation::draw_age(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), draw_can_craft_indicator(), draw_connectors(), target_ui::draw_controls_list(), inventory_selector::draw_footer(), char_creation::draw_height(), target_ui::draw_help_notice(), draw_hidden_amount(), draw_limb_health(), draw_limb_wide(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), worldfactory::draw_mod_list(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), draw_sorting_indicator(), spellcasting_callback::draw_spell_info(), draw_spellbook_info(), draw_stats_info(), draw_tip(), draw_traits_info(), vehicle::drive_to_local_target(), item::durability_indicator(), spell::duration_string(), dialogue::dynamic_line(), editmap::edit(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), debug_menu::effect_edit_menu(), effects_description_for_creature(), einkpc_download_memory_card(), enumerate_objects_around_point(), spell::enumerate_targets(), Character::enumerate_unmet_requirements(), cata_libintl::PlfNode::eval(), spell::exp_progress(), map_data_common_t::extended_description(), Character::extended_description(), monster::extended_description(), game::extended_description(), basecamp::faction_display(), npc::faction_display(), Messages::dialog::filter_help_text(), item::final_info(), find_dirname(), find_mm_dir(), game::find_or_make_stairs(), find_quad_path(), find_region_path(), Item_factory::find_template(), fire(), mdeath::fireball(), fmt_conflicts(), overmap_ui::fmt_omt_coords(), options_manager::PageItem::fmt_tooltip(), fold_and_print(), fold_and_print_from(), vehicle::fold_up(), item::food_info(), consistency_report::format(), vpart_info::format_description(), format_money(), format_object_pair(), veh_interact::format_reqs(), format_volume(), full_screen_popup(), mdeath::fungalburst(), map::furnname(), mdeath::gas(), basecamp::gathering_return(), dialogue::gen_responses(), Name::generate(), bionic_install_preset::get_anesth_amount(), bionic_uninstall_preset::get_anesth_amount(), basecamp::get_available_missions(), basecamp::get_available_missions_by_dir(), avatar::get_book_reader(), inventory_selector_preset::get_caption(), selection_column_preset::get_caption(), get_colored_bar(), get_consume_needs_hint(), weapon_inventory_preset::get_damage_string(), comestible_inventory_preset::get_denial(), activatable_inventory_preset::get_denial(), gunmod_inventory_preset::get_denial(), bionic_install_preset::get_denial(), bionic_uninstall_preset::get_denial(), input_context::get_desc(), bonus_container::get_description(), ma_technique::get_description(), cone_factory::get_description(), ma_requirements::get_description(), ma_buff::get_description(), overmapbuffer::get_description_at(), help::get_dir_grid(), get_encumbrance_description(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), bionic_uninstall_preset::get_failure_chance(), get_fire_fuel_string(), get_freshness_description(), diary::get_head_text(), Character::get_hunger_description(), input_manager::get_keyname(), kill_tracker::get_kills_text(), liquid_handler::get_liquid_target(), cata_libintl::trans_catalogue::get_metadata(), repair_item_actor::get_name(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), help::get_note_colors(), armor_inventory_preset::get_number_string(), Character::get_pain_description(), player_activity::get_progress_message(), disassemble_activity_actor::get_progress_message(), item::get_remaining_capacity_for_liquid(), item::get_remaining_chapters(), inventory_selector::get_stats(), vehicle::get_targeting_npc(), cata_libintl::trans_catalogue::get_u32(), cata_libintl::trans_catalogue::get_u8(), trading_window::get_var_trade(), inventory_selector::get_weight_and_volume_stats(), anonymous_namespace{messages.cpp}::game_message::get_with_count(), loot_options::get_zone_name_suggestion(), options_manager::cOpt::getDefaultText(), options_manager::cOpt::getValue(), options_manager::cOpt::getValueName(), give_item_to(), anonymous_namespace{game_inventory.cpp}::good_bad_none(), item::gun_info(), player::gunmod_add(), item::gunmod_info(), gunmod_inventory_preset::gunmod_inventory_preset(), ranged::gunmode_checks_common(), ranged::gunmode_checks_weapon(), game::handle_action(), generic_factory< T >::handle_inheritance(), Character::height_string(), anonymous_namespace{game_inventory.cpp}::highlight_good_bad_none(), game_menus::inv::holster(), hp_description(), iuse_transform::info(), consume_drug_iuse::info(), deploy_furn_actor::info(), cast_spell_actor::info(), holster_actor::info(), bandolier_actor::info(), ammobelt_actor::info(), item::info(), input_manager::init_keycode_mapping(), monexamine::insert_battery(), vehicle::interact_with(), avatar::invoke_item(), veh_interact::is_drive_conflict(), inscribe_actor::item_inscription(), item_save_monsters(), basecamp::job_assignment_ui(), ma_style_callback::key(), diary::kill_changes(), Creature_tracker::kill_marked_for_death(), known_magic::learn_spell(), game::list_items(), game::list_missions(), list_occupied_bps(), generic_factory< T >::load(), map_data_common_t::load(), rotatable_symbols::load(), DynamicDataLoader::load_all_from_json(), Item_factory::load_basic_info(), load_languages(), mod_management::load_modfile(), mod_management::load_mods_from(), npc::load_npc_template(), Item_factory::load_sub_ref(), vpart_info::load_wheel(), game::look_around(), item::magazine_info(), main(), ret_val< T >::make_failure(), make_group_or_throw(), ret_val< T >::make_success(), editmap::mapgen_preview(), editmap::mapgen_retarget(), item::mark_as_used_by_player(), item::mark_chapter_as_read(), diary::max_power_level_changes(), item::med_info(), melee_cost_text(), Character::melee_special_effects(), melee_stamina_cost_text(), player::mend_item(), vehicle::merge_rackable_vehicle(), query_popup::message(), monexamine::mfriend_menu(), mill_load_food(), game::mon_info(), game::mon_info_update(), game::monmove(), mouth_stamina_cost_text(), map::move_vehicle(), moves_to_string(), game_menus::inv::multiwash(), Character::mutation_attacks(), catacurses::mvwprintw(), mvwprintz(), MOD_INFORMATION::name(), vehicle_part::name(), monster::name(), name_and_value(), monster::name_with_armor(), inventory_selector::naturalize_category(), new_artifact(), minesweeper_game::new_level(), new_natural_artifact(), game::npc_menu(), npc_temp_orders_menu(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), basecamp::om_upgrade_description(), Character::on_hurt(), npc::opinion_text(), dialogue::opt(), iuse::oxygen_bottle(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_recoil(), target_ui::panel_turret_list(), cata_libintl::trans_catalogue::parse_plf_header(), cata_libintl::parse_plural_rules(), parse_vp_reqs(), monexamine::pay_bot(), iexamine::pay_gas(), cata_libintl::PlfTStream::peek_internal(), monexamine::pet_menu(), petfood(), photo_def_for_camera_point(), mattack::photograph(), pick_one_up(), character_martial_arts::pick_style(), pickup::pick_up(), mission_start::place_npc_software(), game::place_player(), overmap::place_radios(), overmap_ui::place_ter_or_special(), overmapbuffer::player_filename(), player_hit_message(), cata_libintl::plf_get_expr(), cata_libintl::plf_get_value(), popup(), popup_getkey(), popup_player_or_npc(), popup_top(), iexamine::portable_structure(), Character::pour_into(), player::power_bionics(), player::power_mutations_ui(), defense_game::pre_action(), computer_session::print_error(), print_humidity(), computer_session::print_indented_line(), monster::print_info(), advanced_inventory::print_items(), print_items(), print_mana(), main_menu::print_menu(), main_menu::print_menu_items(), vehicle::print_part_list(), print_pressure(), print_ranged_chance(), snake_game::print_score(), print_steadiness(), print_temperature(), game::print_terrain_info(), print_time_just_hour(), game::print_trap_info(), vehicle::print_vparts_descs(), cata_libintl::trans_catalogue::process_file_header(), sounds::process_sound_markers(), game::process_voluntary_act_interrupt(), prompt_disassemble_in_seq(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), item::qualities_info(), iexamine::quern_examine(), advanced_inventory::query_charges(), advanced_inventory::query_destination(), query_int(), crafting::query_tool_selection(), query_yn(), Character::query_yn(), computer_session::query_ynq(), iuse::radio_on(), ranged_cost_text(), avatar::read(), game_menus::inv::read(), read_and_set_or_throw(), read_inventory_preset::read_inventory_preset(), realDebugmsg(), basecamp::recruit_description(), basecamp::recruit_return(), iexamine::recycle_compactor(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), spellcasting_callback::refresh(), teleporter_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), debug_menu::effect_select_callback::refresh(), explosion_handler::explosion_funcs::regular(), item::reload(), reload_cost_text(), iexamine::reload_furniture(), vehicle::reload_seeds(), render_wind(), game_menus::inv::repair(), item::repair_info(), activity_handlers::repair_item_finish(), iuse::report_grid_connections(), JsonObject::report_unvisited(), required_skills_as_string(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), run_cost_text(), map_memory::save(), game_menus::inv::saw_barrel(), npc::say(), player::select_ammo(), select_crafting_recipe(), player::select_item_component(), editmap::select_shape(), units::quantity< V, U >::serialize(), set_description(), set_profession(), set_scenario(), set_skills(), set_traits(), item::set_var(), mapgen_function_json_base::setup_common(), mapgen_function_json_base::setup_setmap(), auto_pickup::npc_settings::show(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_modselection_window(), overmap_ui::show_notes_manager(), diary::skill_changes(), skim_book_msg(), sleep(), mdeath::smokeburst(), smoker_load_food(), iexamine::smoker_options(), snake_game::snake_over(), player::sort_armor(), defense_game::special_wave_message(), diary::spell_changes(), split_to_pages(), basecamp::start_crafting(), vehicle::start_engine(), diary::stat_changes(), game_menus::inv::steal(), activity_type::stop_phrase(), string_format(), Character::suffer_from_schizophrenia(), swim_cost_text(), npc::talk_to_u(), overmapbuffer::terrain_filename(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), text_for_requirement(), item::tname(), quality_requirement::to_colored_string(), points_left::to_string(), grid_furn_transform_queue::to_string(), four_quadrants::to_string(), to_string(), tool_comp::to_string(), item_comp::to_string(), quality_requirement::to_string(), to_string_approx(), to_string_clipped(), to_string_time_of_day(), game::debug_hour_timer::toggle(), vehicle::toggle_autopilot(), item::tool_info(), trim_and_print(), try_consume(), item::type_name(), achievement::time_bound::ui_text(), achievement_state::ui_text(), target_ui::uitext_title(), player::unwield(), veh_interact::update_part_requirements(), game::update_stair_monsters(), editmap::update_view_with_help(), weather_manager::update_weather(), trading_window::update_win(), computer_session::use(), place_monster_iuse::use(), inscribe_actor::use(), musical_instrument_actor::use(), holster_actor::use(), place_trap_actor::use(), deploy_tent_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), vehicle::use_bike_rack(), vehicle::use_controls(), heal_actor::use_healing_item(), worldfactory::valid_worldname(), game::vertical_notes(), wait(), query_popup::wait_message(), query_popup::wait_text(), consistency_report::warn(), npc::warn_about(), player::weapname(), weather_forecast(), wheel_state_description(), Character::will_eat(), game::win_screen(), debug_menu::wishitem(), debug_menu::wishmonster(), debug_menu::wishmutate(), debug_menu::wishskill(), catacurses::wprintw(), wprintz(), and memorial_logger::write().
string_format() [3/3]
template<typename T , typename ... Args> std::enable_if< cata::is_translation< T >::value, std::string >::type string_format (T && format, Args &&... args) inline
Definition at line 435 of file string_formatter.h.
{
    return string_format( format.translated(), std::forward<Args>( args )... );
}
References format(), and string_format().