Cataclysm BN: src/string_utils.cpp File Reference
string_utils.cpp File Reference
#include "string_utils.h"
#include "catacharset.h"
#include "color.h"
#include "name.h"
#include "translations.h"
#include <algorithm>
#include <locale>
#include <sstream>
Typedefs
using char_t = std::string::value_type
Functions
bool lcmatch (const std::string &str, const std::string &qry)
Perform case insensitive search for a query string inside a subject string.
bool lcmatch (const translation &str, const std::string &qry)
bool lcequal (const std::string &str1, const std::string &str2)
Perform case insensitive comparison of 2 strings.
bool match_include_exclude (const std::string &text, std::string filter)
Matches text case insensitive with the include/exclude rules of the filter.
bool string_starts_with (const std::string &s1, const std::string &s2)
Returns true if s1 starts with s2.
bool string_ends_with (const std::string &s1, const std::string &s2)
Returns true if s1 ends with s2.
std::string join (const std::vector< std::string > &strings, const std::string &joiner)
Joins a vector of std::strings into a single string with a delimiter/joiner.
std::vector< std::string > string_split (const std::string &text_in, char delim_in)
Split string by delimiter.
int ci_find_substr (const std::string &str1, const std::string &str2)
Find position of str2 within str1 (case-insensitive)
bool wildcard_match (const std::string &text_in, const std::string &pattern_in)
Match text containing wildcards (*)
std::string wildcard_trim_rule (const std::string &pattern_in)
Remove excessive '*' in wildcard rule.
template<typename Prep >
std::string trim (const std::string &s, Prep prep)
std::string trim (const std::string &s)
Remove spaces from the start and the end of a string.
std::string trim_punctuation_marks (const std::string &s)
Removes punctuation marks from the start and the end of a string.
std::string to_upper_case (const std::string &s)
Converts the string to upper case.
std::string to_lower_case (const std::string &s)
Converts the string to lower case.
void replace_name_tags (std::string &input)
Replace name tags with actual names.
void replace_city_tag (std::string &input, const std::string &name)
Replace city tag with given name.
void replace_first (std::string &input, const std::string &what, const std::string &with)
Replace first occurence of 'what' within 'input' with 'with'.
std::string replace_all (std::string input, const std::string &what, const std::string &with)
Replace all occurences of 'what' within 'input' with 'with'.
std::string replace_colors (std::string text)
Replace special color tags (e.g.
std::string & capitalize_letter (std::string &str, size_t n)
Capitalize nth ASCII letter.
std::string trim_whitespaces (const std::string &str)
Remove leading and trailing whitespaces.
Typedef Documentation
char_t
using char_t = std::string::value_type
Definition at line 225 of file string_utils.cpp.
Function Documentation
capitalize_letter()
std::string & capitalize_letter (std::string & str, size_t n = 0)
Capitalize nth ASCII letter.
Don't use for Unicode strings!
Definition at line 333 of file string_utils.cpp.
{
    char c = str[n];
    if( !str.empty() && c >= 'a' && c <= 'z' ) {
        c += 'A' - 'a';
        str[n] = c;
    }
    return str;
}
References c.
Referenced by handle_action_menu(), dialogue::opt(), and defense_game::special_wave_message().
ci_find_substr()
int ci_find_substr (const std::string & str1, const std::string & str2)
Find position of str2 within str1 (case-insensitive)
Definition at line 124 of file string_utils.cpp.
{
    std::locale loc = std::locale();
    std::string::const_iterator it = std::search( str1.begin(), str1.end(), str2.begin(), str2.end(),
    [&]( const char str1_in, const char str2_in ) {
        return std::toupper( str1_in, loc ) == std::toupper( str2_in, loc );
    } );
    if( it != str1.end() ) {
        return it - str1.begin();
    } else {
        return -1;    // not found
    }
}
References overmap_ui::search().
Referenced by Messages::dialog::do_filter(), input_context::get_desc(), auto_pickup::player_settings::has_rule(), safemode::has_rule(), auto_pickup::player_settings::remove_rule(), safemode::remove_rule(), and wildcard_match().
join()
std::string join (const std::vector< std::string > & strings, const std::string & joiner)
Joins a vector of std::strings into a single string with a delimiter/joiner.
Definition at line 90 of file string_utils.cpp.
{
    std::ostringstream buffer;
    for( auto a = strings.begin(); a != strings.end(); ++a ) {
        if( a != strings.begin() ) {
            buffer << joiner;
        }
        buffer << *a;
    }
    return buffer.str();
}
References a.
lcequal()
bool lcequal (const std::string & str1, const std::string & str2)
Perform case insensitive comparison of 2 strings.
Definition at line 40 of file string_utils.cpp.
{
    return to_lower_case( str1 ) == to_lower_case( str2 );
}
References to_lower_case().
lcmatch() [1/2]
bool lcmatch (const std::string & str, const std::string & qry)
Perform case insensitive search for a query string inside a subject string.
Searches for string given by qry inside a subject string given by str.
Parameters
str Subject to search for occurrence of the query string.
qry Query string to search for in str
Returns
true if the query string is found at least once within the subject string, otherwise returns false
Definition at line 12 of file string_utils.cpp.
{
    if( std::locale().name() != "en_US.UTF-8" && std::locale().name() != "C" ) {
        auto &f = std::use_facet<std::ctype<wchar_t>>( std::locale() );
        std::wstring wneedle = utf8_to_wstr( qry );
        std::wstring whaystack = utf8_to_wstr( str );
        f.tolower( &whaystack[0], &whaystack[0] + whaystack.size() );
        f.tolower( &wneedle[0], &wneedle[0] + wneedle.size() );
        return whaystack.find( wneedle ) != std::wstring::npos;
    }
    std::string needle;
    needle.reserve( qry.size() );
    std::transform( qry.begin(), qry.end(), std::back_inserter( needle ), tolower );
    std::string haystack;
    haystack.reserve( str.size() );
    std::transform( str.begin(), str.end(), std::back_inserter( haystack ), tolower );
    return haystack.find( needle ) != std::string::npos;
}
References om_direction::name(), iexamine::transform(), and utf8_to_wstr().
Referenced by basic_item_filter(), veh_interact::do_install(), input_context::filter_strings_by_phrase(), uilist::filterlist(), overmap::find_terrain(), overmapbuffer::get_extras(), requirement_data::get_folded_list(), overmapbuffer::get_notes(), lcmatch(), lcmatch_any(), match_include_exclude(), set_scenario(), and worldfactory::show_modselection_window().
lcmatch() [2/2]
bool lcmatch (const translation & str, const std::string & qry)
Definition at line 35 of file string_utils.cpp.
{
    return lcmatch( str.translated(), qry );
}
References lcmatch(), and translation::translated().
match_include_exclude()
bool match_include_exclude (const std::string & text, std::string filter)
Matches text case insensitive with the include/exclude rules of the filter.
Multiple includes/excludes are possible
Examle: bank,-house,tank,-car Will match text containing tank or bank while not containing house or car
Parameters
text String to be matched
filter String with include/exclude rules
Returns
true if include/exclude rules pass. See Example.
Definition at line 45 of file string_utils.cpp.
{
    size_t iPos;
    bool found = false;
    if( filter.empty() ) {
        return false;
    }
    do {
        iPos = filter.find( ',' );
        std::string term = iPos == std::string::npos ? filter : filter.substr( 0, iPos );
        const bool exclude = term.substr( 0, 1 ) == "-";
        if( exclude ) {
            term = term.substr( 1 );
        }
        if( ( !found || exclude ) && lcmatch( text, term ) ) {
            if( exclude ) {
                return false;
            }
            found = true;
        }
        if( iPos != std::string::npos ) {
            filter = filter.substr( iPos + 1, filter.size() );
        }
    } while( iPos != std::string::npos );
    return found;
}
References lcmatch().
Referenced by overmap::find_extras(), overmap::find_notes(), and overmap_ui::search().
replace_all()
std::string replace_all (std::string input, const std::string & what, const std::string & with)
Replace all occurences of 'what' within 'input' with 'with'.
Definition at line 290 of file string_utils.cpp.
{
    std::string text = std::move( input );
    // Check if there's something to replace (mandatory) and it's necessary (optional)
    // Second condition assumes that text is much longer than both &before and &after.
    if( what.empty() || what == with ) {
        return text;
    }
    const size_t what_len = what.length();
    const size_t with_len = with.length();
    size_t pos = 0;
    while( ( pos = text.find( what, pos ) ) != std::string::npos ) {
        text.replace( pos, what_len, with );
        pos += with_len;
    }
    return text;
}
References avatar_action::move().
Referenced by overmap_ui::create_note(), help::deserialize(), help::get_dir_grid(), game::list_missions(), computer::load_legacy_data(), replace_city_tag(), replace_colors(), and Creature::replace_with_npc_name().
replace_city_tag()
void replace_city_tag (std::string & input, const std::string & name)
Replace city tag with given name.
Definition at line 273 of file string_utils.cpp.
{
    input = replace_all( input, "<city>", name );
}
References om_direction::name(), and replace_all().
Referenced by jmapgen_graffiti::apply_all_tags(), and jmapgen_sign::apply_all_tags().
replace_colors()
std::string replace_colors (std::string text)
Replace special color tags (e.g.
info, bold, bad) with actual color tags.
Definition at line 312 of file string_utils.cpp.
{
    static const std::vector<std::pair<std::string, std::string>> info_colors = {
        {"info", get_all_colors().get_name( c_cyan )},
        {"stat", get_all_colors().get_name( c_light_blue )},
        {"header", get_all_colors().get_name( c_magenta )},
        {"bold", get_all_colors().get_name( c_white )},
        {"dark", get_all_colors().get_name( c_dark_gray )},
        {"good", get_all_colors().get_name( c_green )},
        {"bad", get_all_colors().get_name( c_red )},
        {"neutral", get_all_colors().get_name( c_yellow )}
    };
    for( auto &elem : info_colors ) {
        text = replace_all( text, "<" + elem.first + ">", "<color_" + elem.second + ">" );
        text = replace_all( text, "</" + elem.first + ">", "</color>" );
    }
    return text;
}
References c_cyan, c_dark_gray, c_green, c_light_blue, c_magenta, c_red, c_white, c_yellow, get_all_colors(), color_manager::get_name(), and replace_all().
Referenced by Character::extended_description(), monster::extended_description(), npc::extended_description(), inventory_selector_preset::get_cell_text(), inventory_selector_preset::cell_t::get_text(), iteminfo::iteminfo(), ma_style_callback::key(), and debug_menu::effect_select_callback::refresh().
replace_first()
void replace_first (std::string & input, const std::string & what, const std::string & with)
Replace first occurence of 'what' within 'input' with 'with'.
Definition at line 278 of file string_utils.cpp.
{
    if( what.empty() || what == with ) {
        return;
    }
    size_t len = what.length();
    size_t offset = input.find( what );
    if( offset != std::string::npos ) {
        input.replace( offset, len, with );
    }
}
Referenced by replace_name_tags().
replace_name_tags()
void replace_name_tags (std::string & input)
Replace name tags with actual names.
Definition at line 256 of file string_utils.cpp.
{
    // these need to replace each tag with a new randomly generated name
    while( input.find( "<full_name>" ) != std::string::npos ) {
        replace_first( input, "<full_name>", Name::get( nameIsFullName ) );
    }
    while( input.find( "<family_name>" ) != std::string::npos ) {
        replace_first( input, "<family_name>", Name::get( nameIsFamilyName ) );
    }
    while( input.find( "<given_name>" ) != std::string::npos ) {
        replace_first( input, "<given_name>", Name::get( nameIsGivenName ) );
    }
    while( input.find( "<town_name>" ) != std::string::npos ) {
        replace_first( input, "<town_name>", Name::get( nameIsTownName ) );
    }
}
References Name::get(), nameIsFamilyName, nameIsFullName, nameIsGivenName, nameIsTownName, and replace_first().
Referenced by jmapgen_graffiti::apply_all_tags(), and jmapgen_sign::apply_all_tags().
string_ends_with()
bool string_ends_with (const std::string & s1, const std::string & s2)
Returns true if s1 ends with s2.
TODO: Switch to ends_with method of std::string when we move to C++20
Definition at line 84 of file string_utils.cpp.
{
    return s1.size() >= s2.size() &&
           s1.compare( s1.size() - s2.size(), s2.size(), s2 ) == 0;
}
Referenced by can_write_to_dir(), anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), oter_get_rotation_dir(), iuse::pack_item(), iuse::rm13armor_on(), and item::tname().
string_split()
std::vector< std::string > string_split (const std::string & text_in, char delim_in)
Split string by delimiter.
Definition at line 103 of file string_utils.cpp.
{
    std::vector<std::string> elems;
    if( text_in.empty() ) {
        return elems; // Well, that was easy.
    }
    std::stringstream ss( text_in );
    std::string item;
    while( std::getline( ss, item, delim_in ) ) {
        elems.push_back( item );
    }
    if( text_in.back() == delim_in ) {
        elems.push_back( "" );
    }
    return elems;
}
Referenced by check_special_rule(), item::get_var(), cata_libintl::trans_catalogue::parse_plf_header(), debug_menu::teleport_overmap(), cata_libintl::trans_catalogue::trans_catalogue(), and wildcard_match().
string_starts_with()
bool string_starts_with (const std::string & s1, const std::string & s2)
Returns true if s1 starts with s2.
TODO: Switch to starts_with method of std::string when we move to C++20
Definition at line 79 of file string_utils.cpp.
{
    return s1.compare( 0, s2.size(), s2 ) == 0;
}
Referenced by constructions::check_consistency(), cata_libintl::trans_catalogue::check_encoding(), Item_factory::finalize_pre(), getSystemUILang(), cata_libintl::trans_catalogue::parse_plf_header(), cata_libintl::PlfTStream::peek_internal(), JsonObject::report_unvisited(), and to_valid_language().
to_lower_case()
std::string to_lower_case (const std::string & s)
Converts the string to lower case.
Definition at line 241 of file string_utils.cpp.
{
    if( std::locale().name() != "en_US.UTF-8" && std::locale().name() != "C" ) {
        const auto &f = std::use_facet<std::ctype<wchar_t>>( std::locale() );
        std::wstring wstr = utf8_to_wstr( s );
        f.tolower( &wstr[0], &wstr[0] + wstr.size() );
        return wstr_to_utf8( wstr );
    }
    std::string res;
    std::transform( s.begin(), s.end(), std::back_inserter( res ), []( char_t ch ) {
        return std::use_facet<std::ctype<char_t>>( std::locale() ).tolower( ch );
    } );
    return res;
}
References om_direction::name(), iexamine::transform(), utf8_to_wstr(), and wstr_to_utf8().
Referenced by assign_coverage_from_json(), and lcequal().
to_upper_case()
std::string to_upper_case (const std::string & s)
Converts the string to upper case.
Definition at line 226 of file string_utils.cpp.
{
    if( std::locale().name() != "en_US.UTF-8" && std::locale().name() != "C" ) {
        const auto &f = std::use_facet<std::ctype<wchar_t>>( std::locale() );
        std::wstring wstr = utf8_to_wstr( s );
        f.toupper( &wstr[0], &wstr[0] + wstr.size() );
        return wstr_to_utf8( wstr );
    }
    std::string res;
    std::transform( s.begin(), s.end(), std::back_inserter( res ), []( char_t ch ) {
        return std::use_facet<std::ctype<char_t>>( std::locale() ).toupper( ch );
    } );
    return res;
}
References om_direction::name(), iexamine::transform(), utf8_to_wstr(), and wstr_to_utf8().
Referenced by inventory_selector::add_map_items(), and inventory_selector::add_vehicle_items().
trim() [1/2]
std::string trim (const std::string & s)
Remove spaces from the start and the end of a string.
Definition at line 211 of file string_utils.cpp.
{
    return trim( s, []( int c ) {
        return isspace( c );
    } );
}
References c, and trim().
trim() [2/2]
template<typename Prep > std::string trim (const std::string & s, Prep prep)
Definition at line 200 of file string_utils.cpp.
{
    auto wsfront = std::find_if_not( s.begin(), s.end(), [&prep]( int c ) {
        return prep( c );
    } );
    return std::string( wsfront, std::find_if_not( s.rbegin(),
    std::string::const_reverse_iterator( wsfront ), [&prep]( int c ) {
        return prep( c );
    } ).base() );
}
References c.
Referenced by direction_suffix(), filter_from_string(), lru_cache< Key, Value >::insert(), select_crafting_recipe(), trim(), and trim_punctuation_marks().
trim_punctuation_marks()
std::string trim_punctuation_marks (const std::string & s)
Removes punctuation marks from the start and the end of a string.
Definition at line 218 of file string_utils.cpp.
{
    return trim( s, []( int c ) {
        return ispunct( c );
    } );
}
References c, and trim().
Referenced by wear_inventory_preset::get_denial(), take_off_inventory_preset::get_denial(), activatable_inventory_preset::get_denial(), weapon_inventory_preset::get_denial(), and saw_barrel_inventory_preset::get_denial().
trim_whitespaces()
std::string trim_whitespaces (const std::string & str)
Remove leading and trailing whitespaces.
Definition at line 344 of file string_utils.cpp.
{
    // Source: https://stackoverflow.com/a/1798170
    // NOLINTNEXTLINE(cata-text-style)
    const std::string whitespace = "\t ";
    const auto str_begin = str.find_first_not_of( whitespace );
    if( str_begin == std::string::npos ) {
        return "";    // no content
    }
    const auto str_end = str.find_last_not_of( whitespace );
    const auto str_range = str_end - str_begin + 1;
    return str.substr( str_begin, str_range );
}
Referenced by overmap_ui::show_notes_manager().
wildcard_match()
bool wildcard_match (const std::string & text_in, const std::string & pattern_in)
Match text containing wildcards (*)
Parameters
text_in Text to check
pattern_in Pattern to check text_in against Case insensitive search Possible patterns:
wooD wood* wood Wood*aRrOW wood*arrow wood*arrow *wood*hard x*y*z*arrow
Definition at line 139 of file string_utils.cpp.
{
    std::string text = text_in;
    if( text.empty() ) {
        return false;
    } else if( text == "*" ) {
        return true;
    }
    std::vector<std::string> pattern = string_split( wildcard_trim_rule( pattern_in ), '*' );
    if( pattern.size() == 1 ) { // no * found
        return ( text.length() == pattern[0].length() && ci_find_substr( text, pattern[0] ) != -1 );
    }
    for( auto it = pattern.begin(); it != pattern.end(); ++it ) {
        if( it == pattern.begin() && !it->empty() ) {
            if( text.length() < it->length() ||
                ci_find_substr( text.substr( 0, it->length() ), *it ) == -1 ) {
                return false;
            }
            text = text.substr( it->length(), text.length() - it->length() );
        } else if( it == pattern.end() - 1 && !it->empty() ) {
            if( text.length() < it->length() ||
                ci_find_substr( text.substr( text.length() - it->length(),
                                             it->length() ), *it ) == -1 ) {
                return false;
            }
        } else {
            if( !( *it ).empty() ) {
                int pos = ci_find_substr( text, *it );
                if( pos == -1 ) {
                    return false;
                }
                text = text.substr( pos + static_cast<int>( it->length() ),
                                    static_cast<int>( text.length() ) - pos );
            }
        }
    }
    return true;
}
References ci_find_substr(), string_split(), and wildcard_trim_rule().
Referenced by auto_pickup::rule_list::create_rule(), safemode::is_sound_safe(), auto_pickup::rule_list::refresh_map_items(), safemode::set_rule(), auto_pickup::rule::test_pattern(), and safemode::test_pattern().
wildcard_trim_rule()
std::string wildcard_trim_rule (const std::string & pattern_in)
Remove excessive '*' in wildcard rule.
Definition at line 185 of file string_utils.cpp.
{
    std::string pattern = pattern_in;
    size_t pos = pattern.find( "**" );
    //Remove all double ** in pattern
    while( pos != std::string::npos ) {
        pattern = pattern.substr( 0, pos ) + pattern.substr( pos + 1, pattern.length() - pos - 1 );
        pos = pattern.find( "**" );
    }
    return pattern;
}
Referenced by auto_pickup::user_interface::show(), safemode::show(), and wildcard_match().