Cataclysm BN: points_left Struct Reference
points_left Struct Reference
#include <newcharacter.h>
Public Types
enum point_limit : int { FREEFORM = 0 , ONE_POOL , MULTI_POOL , TRANSFER }
Public Member Functions
points_left ()
void init_from_options ()
int stat_points_left () const
int trait_points_left () const
int skill_points_left () const
bool is_freeform ()
bool is_valid ()
bool has_spare ()
std::string to_string ()
Public Attributes
int stat_points = 0
int trait_points = 0
int skill_points = 0
point_limit limit = point_limit::FREEFORM
Detailed Description
Definition at line 11 of file newcharacter.h.
Member Enumeration Documentation
point_limit
enum points_left::point_limit : int
Enumerator
FREEFORM
ONE_POOL
MULTI_POOL
TRANSFER
Definition at line 16 of file newcharacter.h.
                     : int {
        FREEFORM = 0,
        ONE_POOL,
        MULTI_POOL,
        TRANSFER,
    };
Constructor & Destructor Documentation
points_left()
points_left::points_left ()
Definition at line 3083 of file newcharacter.cpp.
{
    limit = MULTI_POOL;
    init_from_options();
}
References init_from_options(), limit, and MULTI_POOL.
Member Function Documentation
has_spare()
bool points_left::has_spare ()
Definition at line 3145 of file newcharacter.cpp.
{
    return !is_freeform() && is_valid() && skill_points_left() > 0;
}
References is_freeform(), is_valid(), and skill_points_left().
Referenced by avatar::randomize(), and set_description().
init_from_options()
void points_left::init_from_options ()
Definition at line 3089 of file newcharacter.cpp.
{
    stat_points = get_option<int>( "INITIAL_STAT_POINTS" );
    trait_points = get_option<int>( "INITIAL_TRAIT_POINTS" );
    skill_points = get_option<int>( "INITIAL_SKILL_POINTS" );
}
References skill_points, stat_points, and trait_points.
Referenced by points_left(), set_description(), and set_scenario().
is_freeform()
bool points_left::is_freeform ()
Definition at line 3133 of file newcharacter.cpp.
{
    return limit == FREEFORM;
}
References FREEFORM, and limit.
Referenced by has_spare(), is_valid(), avatar::randomize(), set_stats(), and set_traits().
is_valid()
bool points_left::is_valid ()
Definition at line 3138 of file newcharacter.cpp.
{
    return is_freeform() ||
           ( stat_points_left() >= 0 && trait_points_left() >= 0 &&
             skill_points_left() >= 0 );
}
References is_freeform(), skill_points_left(), stat_points_left(), and trait_points_left().
Referenced by has_spare(), avatar::randomize(), set_description(), and to_string().
skill_points_left()
int points_left::skill_points_left () const
Definition at line 3128 of file newcharacter.cpp.
{
    return stat_points + trait_points + skill_points;
}
References skill_points, stat_points, and trait_points.
Referenced by has_spare(), is_valid(), avatar::randomize(), set_description(), set_profession(), set_scenario(), set_skills(), and to_string().
stat_points_left()
int points_left::stat_points_left () const
Definition at line 3097 of file newcharacter.cpp.
{
    switch( limit ) {
        case FREEFORM:
        case ONE_POOL:
            return stat_points + trait_points + skill_points;
        case MULTI_POOL:
            return std::min( trait_points_left(),
                             stat_points + std::min( 0, trait_points + skill_points ) );
        case TRANSFER:
            return 0;
    }
    return 0;
}
References FREEFORM, limit, MULTI_POOL, ONE_POOL, skill_points, stat_points, trait_points, trait_points_left(), and TRANSFER.
Referenced by is_valid(), avatar::randomize(), set_description(), and to_string().
to_string()
std::string points_left::to_string ()
Definition at line 3150 of file newcharacter.cpp.
{
    if( limit == MULTI_POOL ) {
        return string_format(
                   _( "Points left: <color_%s>%d</color>%c<color_%s>%d</color>%c<color_%s>%d</color>=<color_%s>%d</color>" ),
                   stat_points_left() >= 0 ? "light_gray" : "red", stat_points,
                   trait_points >= 0 ? '+' : '-',
                   trait_points_left() >= 0 ? "light_gray" : "red", std::abs( trait_points ),
                   skill_points >= 0 ? '+' : '-',
                   skill_points_left() >= 0 ? "light_gray" : "red", std::abs( skill_points ),
                   is_valid() ? "light_gray" : "red", stat_points + trait_points + skill_points );
    } else if( limit == ONE_POOL ) {
        return string_format( _( "Points left: %4d" ), skill_points_left() );
    } else if( limit == TRANSFER ) {
        return _( "Character Transfer: No changes can be made." );
    } else {
        return _( "Freeform" );
    }
}
References _, is_valid(), limit, MULTI_POOL, ONE_POOL, skill_points, skill_points_left(), stat_points, stat_points_left(), string_format(), trait_points, trait_points_left(), and TRANSFER.
Referenced by draw_points(), set_profession(), set_scenario(), set_skills(), set_stats(), and set_traits().
trait_points_left()
int points_left::trait_points_left () const
Definition at line 3113 of file newcharacter.cpp.
{
    switch( limit ) {
        case FREEFORM:
        case ONE_POOL:
            return stat_points + trait_points + skill_points;
        case MULTI_POOL:
            return stat_points + trait_points + std::min( 0, skill_points );
        case TRANSFER:
            return 0;
    }
    return 0;
}
References FREEFORM, limit, MULTI_POOL, ONE_POOL, skill_points, stat_points, trait_points, and TRANSFER.
Referenced by is_valid(), avatar::randomize(), set_description(), stat_points_left(), and to_string().
Member Data Documentation
limit
point_limit points_left::limit = point_limit::FREEFORM
Definition at line 22 of file newcharacter.h.
Referenced by avatar::create(), is_freeform(), avatar::load_template(), points_left(), avatar::save_template(), set_description(), set_points(), stat_points_left(), to_string(), trait_points_left(), and main_menu::world_tab().
skill_points
int points_left::skill_points = 0
Definition at line 14 of file newcharacter.h.
Referenced by init_from_options(), avatar::load_template(), avatar::randomize(), avatar::save_template(), set_profession(), set_scenario(), set_skills(), skill_points_left(), stat_points_left(), to_string(), trait_points_left(), and main_menu::world_tab().
stat_points
int points_left::stat_points = 0
Definition at line 12 of file newcharacter.h.
Referenced by init_from_options(), avatar::load_template(), avatar::randomize(), avatar::save_template(), set_stats(), skill_points_left(), stat_points_left(), to_string(), trait_points_left(), and main_menu::world_tab().
trait_points
int points_left::trait_points = 0
Definition at line 13 of file newcharacter.h.
Referenced by newcharacter::add_traits(), init_from_options(), avatar::load_template(), avatar::randomize(), avatar::save_template(), set_traits(), skill_points_left(), stat_points_left(), to_string(), trait_points_left(), and main_menu::world_tab().
The documentation for this struct was generated from the following files:
src/newcharacter.h
src/newcharacter.cpp