Cataclysm BN: scent_block Struct Reference
scent_block Struct Reference
#include <scent_block.h>
Classes
struct datum
Public Types
enum data_mode { NONE = 0 , SET = 1 , MAX = 2 }
template<typename T >
using data_block = std::array< std::array< T, SEEY+2 >, SEEX+2 >
Public Member Functions
scent_block (const tripoint &sub, scent_map &scents)
void commit_modifications ()
point index (const tripoint &p) const
void apply_gas (const tripoint &p, const int nintensity=0)
void apply_slime (const tripoint &p, int intensity)
Public Attributes
data_block< datum > assignment
tripoint origin
scent_map & scents
int modification_count
Detailed Description
Definition at line 12 of file scent_block.h.
Member Typedef Documentation
data_block
template<typename T > using scent_block::data_block = std::array < std::array < T, SEEY + 2 >, SEEX + 2 >
Definition at line 14 of file scent_block.h.
Member Enumeration Documentation
data_mode
enum scent_block::data_mode
Enumerator
NONE
SET
MAX
Definition at line 16 of file scent_block.h.
                   {
        NONE = 0,
        SET = 1,
        MAX = 2
    };
Constructor & Destructor Documentation
scent_block()
scent_block::scent_block (const tripoint & sub, scent_map & scents) inline
Definition at line 32 of file scent_block.h.
        : origin( sm_to_ms_copy( sub ) + point( -1, -1 ) )
        , scents( scents )
        , modification_count( 0 ) {
        for( int x = 0; x < SEEX + 2; ++x ) {
            for( int y = 0; y < SEEY + 2; ++y ) {
                assignment[x][y] = { NONE, 0 };
            }
        }
    }
References assignment, NONE, SEEX, and SEEY.
Member Function Documentation
apply_gas()
void scent_block::apply_gas (const tripoint & p, const int nintensity = 0) inline
Definition at line 77 of file scent_block.h.
{
        const point ndx = index( p );
        assignment[ndx.x][ndx.y].mode = SET;
        assignment[ndx.x][ndx.y].intensity = std::max( 0, assignment[ndx.x][ndx.y].intensity - nintensity );
        ++modification_count;
    }
References assignment, index(), modification_count, SET, point::x, and point::y.
Referenced by map::spread_gas().
apply_slime()
void scent_block::apply_slime (const tripoint & p, int intensity) inline
Definition at line 83 of file scent_block.h.
{
        const point ndx = index( p );
        datum &dat = assignment[ndx.x][ndx.y];
        switch( dat.mode ) {
            case NONE: {
                // we don't know what the current intensity is, so we must do a max operation
                dat.mode = MAX;
                dat.intensity = intensity;
                break;
            }
            case SET: {
                // new intensity is going to be dat.intensity, so we just need to make it larger
                // but cannot change
                dat.intensity = std::max( dat.intensity, intensity );
                break;
            }
            case MAX: {
                // Already max for some reason, shouldn't occur. If it does we want to grow if possible
                dat.intensity = std::max( dat.intensity, intensity );
                break;
            }
        }
        ++modification_count;
    }
References assignment, index(), scent_block::datum::intensity, MAX, scent_block::datum::mode, modification_count, NONE, SET, point::x, and point::y.
Referenced by map::process_fields_in_submap().
commit_modifications()
void scent_block::commit_modifications () inline
Definition at line 44 of file scent_block.h.
{
        if( modification_count == 0 ) {
            return;
        }
        for( int x = 0; x < SEEX + 2; ++x ) {
            for( int y = 0; y < SEEY + 2; ++y ) {
                switch( assignment[x][y].mode ) {
                    case NONE:
                        break;
                    case SET: {
                        tripoint p = origin + tripoint( x, y, 0 );
                        if( scents.inbounds( p ) ) {
                            scents.set_unsafe( p, assignment[x][y].intensity );
                        }
                        break;
                    }
                    case MAX: {
                        tripoint p = origin + tripoint( x, y, 0 );
                        if( scents.inbounds( p ) ) {
                            scents.set_unsafe( p, std::max( assignment[x][y].intensity, scents.get_unsafe( p ) ) );
                        }
                        break;
                    }
                }
            }
        }
    }
References assignment, scent_map::get_unsafe(), scent_map::inbounds(), MAX, modification_count, NONE, origin, scents, SEEX, SEEY, SET, and scent_map::set_unsafe().
Referenced by map::process_fields_in_submap().
index()
point scent_block::index (const tripoint & p) const inline
Definition at line 72 of file scent_block.h.
{
        return -origin.xy() + p.xy();
    }
References origin, and tripoint::xy().
Referenced by apply_gas(), and apply_slime().
Member Data Documentation
assignment
data_block<datum> scent_block::assignment
Definition at line 26 of file scent_block.h.
Referenced by apply_gas(), apply_slime(), commit_modifications(), and scent_block().
modification_count
int scent_block::modification_count
Definition at line 30 of file scent_block.h.
Referenced by apply_gas(), apply_slime(), and commit_modifications().
origin
tripoint scent_block::origin
Definition at line 28 of file scent_block.h.
Referenced by commit_modifications(), and index().
scents
scent_map& scent_block::scents
Definition at line 29 of file scent_block.h.
Referenced by commit_modifications().
The documentation for this struct was generated from the following file:
src/scent_block.h