Cataclysm BN: mutation_branch Struct Reference
mutation_branch Struct Reference
#include <mutation.h>
Public Member Functions
std::string spawn_item_message () const
std::string ranged_mutation_message () const
std::string name () const
std::string desc () const
nc_color get_display_color () const
Returns the color to display the mutation name with.
bool conflicts_with_item (const item &it) const
Returns true if a character with this mutation shouldn't be able to wear given item.
const resistances & damage_resistance (body_part bp) const
Returns damage resistance on a given body part granted by this mutation.
void load (const JsonObject &jo, const std::string &src)
Static Public Member Functions
static std::string get_name (const trait_id &mutation_id)
Shortcut for getting the name of a (translated) mutation, same as.
static const std::vector< mutation_branch > & get_all ()
All known mutations.
static void reset_all ()
static void load_trait (const JsonObject &jo, const std::string &src)
static void check_consistency ()
static void load_trait_blacklist (const JsonObject &jsobj)
Load a trait blacklist specified by the given JSON object.
static bool trait_is_blacklisted (const trait_id &tid)
Check if the trait with the given ID is blacklisted.
static void finalize ()
called after all JSON has been read and performs any necessary cleanup tasks
static void finalize_trait_blacklist ()
Trait groups
Trait groups are used to generate a randomized set of traits.
You usually only need the Trait_group::traits_from function to create traits from a group.
static void load_trait_group (const JsonObject &jsobj)
Callback for the init system (DynamicDataLoader), loads a trait group definitions.
static void load_trait_group (const JsonObject &jsobj, const trait_group::Trait_group_tag &gid, const std::string &subtype)
Load a trait group from json.
static void load_trait_group (const JsonArray &entries, const trait_group::Trait_group_tag &gid, bool is_collection)
Like the above function, except this function assumes that the given array is the "entries" member of the trait group.
static void add_entry (Trait_group &tg, const JsonObject &obj)
Create a new trait group as specified by the given JSON object and register it as part of the given trait group.
static shared_ptr_fast< Trait_group > get_group (const trait_group::Trait_group_tag &gid)
Get the trait group object specified by the given ID, or null if no such group exists.
static std::vector< trait_group::Trait_group_tag > get_all_group_names ()
Return the idents of all trait groups that are known.
Public Attributes
trait_id id
bool was_loaded = false
bool valid = false
bool purifiable = false
bool threshold = false
bool profession = false
bool debug = false
bool player_display = true
bool mixed_effect = false
bool startingtrait = false
bool activated = false
bool starts_active = false
bool allow_soft_gear = false
bool fatigue = false
bool hunger = false
bool thirst = false
int points = 0
int visibility = 0
int ugliness = 0
int cost = 0
int cooldown = 0
int bodytemp_min = 0
int bodytemp_max = 0
int bodytemp_sleep = 0
float pain_recovery = 0.0f
float healing_awake = 0.0f
float healing_resting = 0.0f
float mending_modifier = 1.0f
float hp_modifier = 0.0f
float hp_modifier_secondary = 0.0f
float hp_adjustment = 0.0f
float str_modifier = 0.0f
int cut_dmg_bonus = 0
float pierce_dmg_bonus = 0.0
std::pair< int, int > rand_cut_bonus
int bash_dmg_bonus = 0
std::pair< int, int > rand_bash_bonus
float dodge_modifier = 0.0f
float speed_modifier = 1.0f
float movecost_modifier = 1.0f
float movecost_flatground_modifier = 1.0f
float movecost_obstacle_modifier = 1.0f
float attackcost_modifier = 1.0f
float max_stamina_modifier = 1.0f
float weight_capacity_modifier = 1.0f
float hearing_modifier = 1.0f
float movecost_swim_modifier = 1.0f
float noise_modifier = 1.0f
float scent_modifier = 1.0f
float bleed_resist = 0
cata::optional< int > scent_intensity
cata::optional< int > scent_mask
int butchering_quality = 0
cata::value_ptr< mut_transform > transform
std::map< skill_id, int > craft_skill_bonus
Map of crafting skills modifiers, can be negative.
cata::optional< scenttype_id > scent_typeid
What do you smell like.
std::map< body_part, float > lumination
Map of glowing body parts and their glow intensity.
float healthy_rate = 1.0f
How fast does healthy tends toward healthy_mod.
int weakness_to_water = 0
maximum damage dealt by water every minute when wet.
float stealth_modifier = 0.0f
float night_vision_range = 0.0f
Night vision range (in tiles), added to NV from stats.
float temperature_speed_modifier = 0.0f
float metabolism_modifier = 0.0f
float thirst_modifier = 0.0f
float fatigue_modifier = 0.0f
float fatigue_regen_modifier = 0.0f
float stamina_regen_modifier = 0.0f
float overmap_sight = 0.0f
float overmap_multiplier = 1.0f
float reading_speed_multiplier = 1.0f
float skill_rust_multiplier = 1.0f
social_modifiers social_mods
itype_id spawn_item
The item, if any, spawned by the mutation.
std::vector< species_id > ignored_by
Species ignoring character with the mutation.
std::map< species_id, int > anger_relations
Map of angered species and there intensity.
std::set< material_id > can_only_eat
List of material required for food to be be edible.
std::set< itype_id > can_only_heal_with
List of healing items allowed.
std::set< itype_id > can_heal_with
std::set< std::string > allowed_category
List of allowed mutatrion category.
std::set< bodypart_str_id > no_cbm_on_bp
List of body parts locked out of bionics.
cata::optional< m_size > body_size
float mana_modifier = 0.0f
float mana_multiplier = 1.0f
float mana_regen_multiplier = 1.0f
std::map< spell_id, int > spells_learned
std::vector< enchantment_id > enchantments
mutation enchantments
itype_id ranged_mutation
The fake gun, if any, spawned and fired by the ranged mutation.
std::vector< mut_attack > attacks_granted
Attacks granted by this mutation.
std::map< vitamin_id, time_duration > vitamin_rates
Mutations may adjust one or more of the default vitamin usage rates.
std::map< material_id, std::map< vitamin_id, double > > vitamin_absorb_multi
std::vector< trait_id > prereqs
std::vector< trait_id > prereqs2
std::vector< trait_id > threshreq
std::set< std::string > types
std::vector< trait_id > cancels
std::vector< trait_id > replacements
std::vector< trait_id > additions
std::vector< std::string > category
std::set< std::string > flags
std::map< body_part, tripoint > protection
std::map< body_part, int > encumbrance_always
std::map< body_part, int > encumbrance_covered
std::set< body_part > restricts_gear
std::unordered_map< std::pair< bool, std::string >, int, cata::tuple_hash > mods
Key pair is <active: bool, mod type: "STR">
std::map< body_part, resistances > armor
std::vector< matype_id > initial_ma_styles
Private Attributes
std::string raw_spawn_item_message
std::string raw_ranged_mutation_message
translation raw_name
translation raw_desc
Detailed Description
Definition at line 75 of file mutation.h.
Member Function Documentation
add_entry()
void mutation_branch::add_entry (Trait_group & tg, const JsonObject & obj) static
Create a new trait group as specified by the given JSON object and register it as part of the given trait group.
Definition at line 839 of file mutation_data.cpp.
{
    std::unique_ptr<Trait_creation_data> ptr;
    int probability = obj.get_int( "prob", 100 );
    JsonArray jarr;
    if( obj.has_member( "collection" ) ) {
        ptr = std::make_unique<Trait_group_collection>( probability );
        jarr = obj.get_array( "collection" );
    } else if( obj.has_member( "distribution" ) ) {
        ptr = std::make_unique<Trait_group_distribution>( probability );
        jarr = obj.get_array( "distribution" );
    }
    if( ptr ) {
        Trait_group &tg2 = dynamic_cast<Trait_group &>( *ptr );
        for( const JsonObject job2 : jarr ) {
            add_entry( tg2, job2 );
        }
        tg.add_entry( std::move( ptr ) );
        return;
    }
    if( obj.has_member( "trait" ) ) {
        trait_id id( obj.get_string( "trait" ) );
        ptr = std::make_unique<Single_trait_creator>( id, probability );
    } else if( obj.has_member( "group" ) ) {
        ptr = std::make_unique<Trait_group_creator>( trait_group::Trait_group_tag(
                    obj.get_string( "group" ) ),
                probability );
    }
    if( !ptr ) {
        return;
    }
    tg.add_entry( std::move( ptr ) );
}
References Trait_group::add_entry(), add_entry(), JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_member(), id, avatar_action::move(), and ptr().
Referenced by add_entry(), and load_trait_group().
check_consistency()
void mutation_branch::check_consistency () static
Definition at line 579 of file mutation_data.cpp.
{
    for( const auto &mdata : get_all() ) {
        const auto &mid = mdata.id;
        const cata::optional<scenttype_id> &s_id = mdata.scent_typeid;
        const std::map<species_id, int> &an_id = mdata.anger_relations;
        for( const auto &style : mdata.initial_ma_styles ) {
            if( !style.is_valid() ) {
                debugmsg( "mutation %s refers to undefined martial art style %s", mid.c_str(), style.c_str() );
            }
        }
        for( const std::string &type : mdata.types ) {
            if( !mutation_type_exists( type ) ) {
                debugmsg( "mutation %s refers to undefined mutation type %s", mid.c_str(), type );
            }
        }
        if( mid->transform ) {
            const trait_id tid = mid->transform->target;
            if( !tid.is_valid() ) {
                debugmsg( "mutation %s transform uses undefined target %s", mid.c_str(), tid.c_str() );
            }
        }
        for( const std::pair<species_id, int> elem : an_id ) {
            if( !elem.first.is_valid() ) {
                debugmsg( "mutation %s refers to undefined species id %s", mid.c_str(), elem.first.c_str() );
            }
        }
        if( s_id && !s_id.value().is_valid() ) {
            debugmsg( "mutation %s refers to undefined scent type %s", mid.c_str(), s_id.value().c_str() );
        }
        for( const enchantment_id &ench : mdata.enchantments ) {
            ench->check();
        }
        ::check_consistency( mdata.prereqs, mid, "prereq" );
        ::check_consistency( mdata.prereqs2, mid, "prereqs2" );
        ::check_consistency( mdata.threshreq, mid, "threshreq" );
        ::check_consistency( mdata.cancels, mid, "cancels" );
        ::check_consistency( mdata.replacements, mid, "replacements" );
        ::check_consistency( mdata.additions, mid, "additions" );
    }
}
References string_id< T >::c_str(), enchantment::check(), check_consistency(), debugmsg, get_all(), string_id< T >::is_valid(), mutation_type_exists(), transform, type, and cata::optional< T >::value().
Referenced by check_consistency(), and DynamicDataLoader::check_consistency().
conflicts_with_item()
bool mutation_branch::conflicts_with_item (const item & it) const
Returns true if a character with this mutation shouldn't be able to wear given item.
Definition at line 220 of file mutation.cpp.
{
    if( allow_soft_gear && it.is_soft() ) {
        return false;
    }
    for( body_part bp : restricts_gear ) {
        if( it.covers( bp ) ) {
            return true;
        }
    }
    return false;
}
References allow_soft_gear, item::covers(), item::is_soft(), and restricts_gear.
damage_resistance()
const resistances & mutation_branch::damage_resistance (body_part bp) const
Returns damage resistance on a given body part granted by this mutation.
Definition at line 235 of file mutation.cpp.
{
    const auto iter = armor.find( bp );
    if( iter == armor.end() ) {
        static const resistances nulres;
        return nulres;
    }
    return iter->second;
}
References armor.
desc()
std::string mutation_branch::desc () const
Definition at line 564 of file mutation_data.cpp.
{
    return raw_desc.translated();
}
References raw_desc, and translation::translated().
Referenced by Character::add_bionic(), known_magic::learn_spell(), wish_mutate_callback::refresh(), and set_traits().
finalize()
void mutation_branch::finalize () static
called after all JSON has been read and performs any necessary cleanup tasks
Definition at line 718 of file mutation_data.cpp.
{
    for( const mutation_branch &branch : get_all() ) {
        for( const std::string &cat : branch.category ) {
            mutations_category[cat].push_back( trait_id( branch.id ) );
        }
    }
    finalize_trait_blacklist();
}
References finalize_trait_blacklist(), get_all(), mutations_category, and trait_id.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_trait_blacklist()
void mutation_branch::finalize_trait_blacklist () static
Definition at line 728 of file mutation_data.cpp.
{
    for( auto &trait : trait_blacklist ) {
        if( !trait.is_valid() ) {
            debugmsg( "trait on blacklist %s does not exist", trait.c_str() );
        }
    }
}
References debugmsg, and trait_blacklist.
Referenced by finalize().
get_all()
const std::vector< mutation_branch > & mutation_branch::get_all () static
All known mutations.
Key is the mutation id, value is the mutation_branch that you would also get by calling get.
Definition at line 643 of file mutation_data.cpp.
{
    return trait_factory.get_all();
}
References anonymous_namespace{mutation_data.cpp}::trait_factory.
Referenced by check_consistency(), do_purify(), finalize(), get_mutations_in_type(), Character::mutation_chances(), Character::old_mutate(), iuse::purify_iv(), iuse::purify_smart(), newcharacter::random_bad_trait(), newcharacter::random_good_trait(), wish_mutate_callback::refresh(), Character::remove_mutation(), set_traits(), and debug_menu::wishmutate().
get_all_group_names()
std::vector< trait_group::Trait_group_tag > mutation_branch::get_all_group_names () static
Return the idents of all trait groups that are known.
Definition at line 885 of file mutation_data.cpp.
{
    std::vector<trait_group::Trait_group_tag> rval;
    for( auto &group : trait_groups ) {
        rval.push_back( group.first );
    }
    return rval;
}
References trait_groups.
Referenced by trait_group::debug_spawn().
get_display_color()
nc_color mutation_branch::get_display_color () const
Returns the color to display the mutation name with.
Definition at line 621 of file mutation_data.cpp.
{
    if( threshold || profession ) {
        return c_white;
    } else if( debug ) {
        return c_light_cyan;
    } else if( mixed_effect ) {
        return c_pink;
    } else if( points > 0 ) {
        return c_light_green;
    } else if( points < 0 ) {
        return c_light_red;
    } else {
        return c_yellow;
    }
}
References c_light_cyan, c_light_green, c_light_red, c_pink, c_white, c_yellow, debug, mixed_effect, points, and threshold.
get_group()
shared_ptr_fast< Trait_group > mutation_branch::get_group (const trait_group::Trait_group_tag & gid) static
Get the trait group object specified by the given ID, or null if no such group exists.
Definition at line 878 of file mutation_data.cpp.
{
    auto found = trait_groups.find( gid );
    return found != trait_groups.end() ? found->second : nullptr;
}
References trait_groups.
Referenced by Trait_group_creator::create(), trait_group::group_contains_trait(), Trait_group_creator::has_trait(), Trait_group_creator::remove_trait(), and trait_group::traits_from().
get_name()
std::string mutation_branch::get_name (const trait_id & mutation_id) static
Shortcut for getting the name of a (translated) mutation, same as.
get(mutation_id).name
Definition at line 638 of file mutation_data.cpp.
{
    return mutation_id->name();
}
References name().
Referenced by trait_group::debug_spawn(), player::power_mutations_ui(), wish_mutate_callback::refresh(), set_profession(), and memorial_logger::write().
load()
void mutation_branch::load (const JsonObject & jo, const std::string & src)
Definition at line 307 of file mutation_data.cpp.
{
    mandatory( jo, was_loaded, "id", id );
    mandatory( jo, was_loaded, "name", raw_name );
    mandatory( jo, was_loaded, "description", raw_desc );
    mandatory( jo, was_loaded, "points", points );
    optional( jo, was_loaded, "visibility", visibility, 0 );
    optional( jo, was_loaded, "ugliness", ugliness, 0 );
    optional( jo, was_loaded, "starting_trait", startingtrait, false );
    optional( jo, was_loaded, "mixed_effect", mixed_effect, false );
    optional( jo, was_loaded, "active", activated, false );
    optional( jo, was_loaded, "starts_active", starts_active, false );
    optional( jo, was_loaded, "allow_soft_gear", allow_soft_gear, false );
    optional( jo, was_loaded, "cost", cost, 0 );
    optional( jo, was_loaded, "time", cooldown, 0 );
    optional( jo, was_loaded, "hunger", hunger, false );
    optional( jo, was_loaded, "thirst", thirst, false );
    optional( jo, was_loaded, "fatigue", fatigue, false );
    optional( jo, was_loaded, "valid", valid, true );
    optional( jo, was_loaded, "purifiable", purifiable, true );
    if( jo.has_object( "spawn_item" ) ) {
        auto si = jo.get_object( "spawn_item" );
        optional( si, was_loaded, "type", spawn_item );
        optional( si, was_loaded, "message", raw_spawn_item_message );
    }
    if( jo.has_object( "ranged_mutation" ) ) {
        auto si = jo.get_object( "ranged_mutation" );
        optional( si, was_loaded, "type", ranged_mutation );
        optional( si, was_loaded, "message", raw_ranged_mutation_message );
    }
    if( jo.has_object( "transform" ) ) {
        transform = cata::make_value<mut_transform>();
        transform->load( jo, "transform" );
    }
    optional( jo, was_loaded, "initial_ma_styles", initial_ma_styles );
    if( jo.has_array( "bodytemp_modifiers" ) ) {
        auto bodytemp_array = jo.get_array( "bodytemp_modifiers" );
        bodytemp_min = bodytemp_array.get_int( 0 );
        bodytemp_max = bodytemp_array.get_int( 1 );
        if( bodytemp_max < bodytemp_min ) {
            std::swap( bodytemp_min, bodytemp_max );
            jo.throw_error( _( "First temperature modifier can't be higher than the second" ),
                            "bodytemp_modifiers" );
        }
    }
    optional( jo, was_loaded, "bodytemp_sleep", bodytemp_sleep, 0 );
    optional( jo, was_loaded, "threshold", threshold, false );
    optional( jo, was_loaded, "profession", profession, false );
    optional( jo, was_loaded, "debug", debug, false );
    optional( jo, was_loaded, "player_display", player_display, true );
    for( JsonArray pair : jo.get_array( "vitamin_rates" ) ) {
        vitamin_rates.emplace( vitamin_id( pair.get_string( 0 ) ),
                               time_duration::from_turns( pair.get_int( 1 ) ) );
    }
    for( JsonArray pair : jo.get_array( "vitamins_absorb_multi" ) ) {
        std::map<vitamin_id, double> vit;
        // fill the inner map with vitamins
        for( JsonArray vitamins : pair.get_array( 1 ) ) {
            vit.emplace( vitamin_id( vitamins.get_string( 0 ) ), vitamins.get_float( 1 ) );
        }
        // assign the inner vitamin map to the material_id key
        vitamin_absorb_multi.emplace( material_id( pair.get_string( 0 ) ), vit );
    }
    optional( jo, was_loaded, "pain_recovery", pain_recovery, 0.0f );
    optional( jo, was_loaded, "healing_awake", healing_awake, 0.0f );
    optional( jo, was_loaded, "healing_resting", healing_resting, 0.0f );
    optional( jo, was_loaded, "mending_modifier", mending_modifier, 1.0f );
    optional( jo, was_loaded, "hp_modifier", hp_modifier, 0.0f );
    optional( jo, was_loaded, "hp_modifier_secondary", hp_modifier_secondary, 0.0f );
    optional( jo, was_loaded, "hp_adjustment", hp_adjustment, 0.0f );
    optional( jo, was_loaded, "stealth_modifier", stealth_modifier, 0.0f );
    optional( jo, was_loaded, "str_modifier", str_modifier, 0.0f );
    optional( jo, was_loaded, "cut_dmg_bonus", cut_dmg_bonus, 0 );
    optional( jo, was_loaded, "pierce_dmg_bonus", pierce_dmg_bonus, 0.0f );
    optional( jo, was_loaded, "bash_dmg_bonus", bash_dmg_bonus, 0 );
    optional( jo, was_loaded, "dodge_modifier", dodge_modifier, 0.0f );
    optional( jo, was_loaded, "speed_modifier", speed_modifier, 1.0f );
    optional( jo, was_loaded, "movecost_modifier", movecost_modifier, 1.0f );
    optional( jo, was_loaded, "movecost_flatground_modifier", movecost_flatground_modifier, 1.0f );
    optional( jo, was_loaded, "movecost_obstacle_modifier", movecost_obstacle_modifier, 1.0f );
    optional( jo, was_loaded, "movecost_swim_modifier", movecost_swim_modifier, 1.0f );
    optional( jo, was_loaded, "attackcost_modifier", attackcost_modifier, 1.0f );
    optional( jo, was_loaded, "max_stamina_modifier", max_stamina_modifier, 1.0f );
    optional( jo, was_loaded, "weight_capacity_modifier", weight_capacity_modifier, 1.0f );
    optional( jo, was_loaded, "hearing_modifier", hearing_modifier, 1.0f );
    optional( jo, was_loaded, "noise_modifier", noise_modifier, 1.0f );
    optional( jo, was_loaded, "temperature_speed_modifier", temperature_speed_modifier, 0.0f );
    optional( jo, was_loaded, "metabolism_modifier", metabolism_modifier, 0.0f );
    optional( jo, was_loaded, "thirst_modifier", thirst_modifier, 0.0f );
    optional( jo, was_loaded, "fatigue_modifier", fatigue_modifier, 0.0f );
    optional( jo, was_loaded, "fatigue_regen_modifier", fatigue_regen_modifier, 0.0f );
    optional( jo, was_loaded, "stamina_regen_modifier", stamina_regen_modifier, 0.0f );
    optional( jo, was_loaded, "overmap_sight", overmap_sight, 0.0f );
    optional( jo, was_loaded, "overmap_multiplier", overmap_multiplier, 1.0f );
    optional( jo, was_loaded, "night_vision_range", night_vision_range, 0.0f );
    optional( jo, was_loaded, "reading_speed_multiplier", reading_speed_multiplier, 1.0f );
    optional( jo, was_loaded, "skill_rust_multiplier", skill_rust_multiplier, 1.0f );
    optional( jo, was_loaded, "scent_modifier", scent_modifier, 1.0f );
    optional( jo, was_loaded, "scent_intensity", scent_intensity, cata::nullopt );
    optional( jo, was_loaded, "scent_mask", scent_mask, cata::nullopt );
    optional( jo, was_loaded, "scent_type", scent_typeid, cata::nullopt );
    optional( jo, was_loaded, "bleed_resist", bleed_resist, 0 );
    optional( jo, was_loaded, "healthy_rate", healthy_rate, 1.0f );
    optional( jo, was_loaded, "weakness_to_water", weakness_to_water, 0 );
    optional( jo, was_loaded, "ignored_by", ignored_by );
    optional( jo, was_loaded, "can_only_eat", can_only_eat );
    optional( jo, was_loaded, "can_only_heal_with", can_only_heal_with );
    optional( jo, was_loaded, "can_heal_with", can_heal_with );
    optional( jo, was_loaded, "butchering_quality", butchering_quality, 0 );
    optional( jo, was_loaded, "allowed_category", allowed_category );
    optional( jo, was_loaded, "mana_modifier", mana_modifier, 0 );
    optional( jo, was_loaded, "mana_multiplier", mana_multiplier, 1.0f );
    optional( jo, was_loaded, "mana_regen_multiplier", mana_regen_multiplier, 1.0f );
    if( jo.has_object( "rand_cut_bonus" ) ) {
        JsonObject sm = jo.get_object( "rand_cut_bonus" );
        rand_cut_bonus.first = sm.get_int( "min" );
        rand_cut_bonus.second = sm.get_int( "max" );
    }
    if( jo.has_object( "rand_bash_bonus" ) ) {
        JsonObject sm = jo.get_object( "rand_bash_bonus" );
        rand_bash_bonus.first = sm.get_int( "min" );
        rand_bash_bonus.second = sm.get_int( "max" );
    }
    if( jo.has_object( "social_modifiers" ) ) {
        JsonObject sm = jo.get_object( "social_modifiers" );
        social_mods = load_mutation_social_mods( sm );
    }
    load_mutation_mods( jo, "passive_mods", mods );
    /* Not currently supported due to inability to save active mutation state
    load_mutation_mods(jsobj, "active_mods", new_mut.mods); */
    optional( jo, was_loaded, "prereqs", prereqs, trait_reader{} );
    optional( jo, was_loaded, "prereqs2", prereqs2, trait_reader{} );
    optional( jo, was_loaded, "threshreq", threshreq, trait_reader{} );
    optional( jo, was_loaded, "cancels", cancels, trait_reader{} );
    optional( jo, was_loaded, "changes_to", replacements, trait_reader{} );
    optional( jo, was_loaded, "leads_to", additions, trait_reader{} );
    optional( jo, was_loaded, "flags", flags, string_reader{} );
    optional( jo, was_loaded, "types", types, string_reader{} );
    optional( jo, was_loaded, "enchantments", enchantments );
    for( const std::string s : jo.get_array( "no_cbm_on_bp" ) ) {
        no_cbm_on_bp.emplace( bodypart_str_id( s ) );
    }
    optional( jo, was_loaded, "body_size", body_size );
    optional( jo, was_loaded, "category", category, string_reader{} );
    for( JsonArray ja : jo.get_array( "spells_learned" ) ) {
        const spell_id sp( ja.next_string() );
        spells_learned.emplace( sp, ja.next_int() );
    }
    for( JsonArray ja : jo.get_array( "craft_skill_bonus" ) ) {
        const skill_id skid( ja.next_string() );
        if( skid.is_valid() ) {
            craft_skill_bonus.emplace( skid, ja.next_int() );
        } else {
            jo.throw_error( "invalid skill_id" );
        }
    }
    for( JsonArray ja : jo.get_array( "lumination" ) ) {
        const body_part bp = get_body_part_token( ja.next_string() );
        lumination.emplace( bp, static_cast<float>( ja.next_float() ) );
    }
    for( JsonArray ja : jo.get_array( "anger_relations" ) ) {
        const species_id spe = species_id( ja.next_string() );
        anger_relations.emplace( spe, ja.next_int() );
    }
    for( JsonObject wp : jo.get_array( "wet_protection" ) ) {
        std::string part_id = wp.get_string( "part" );
        int ignored = wp.get_int( "ignored", 0 );
        int neutral = wp.get_int( "neutral", 0 );
        int good = wp.get_int( "good", 0 );
        tripoint protect = tripoint( ignored, neutral, good );
        protection[get_body_part_token( part_id )] = protect;
    }
    for( JsonArray ea : jo.get_array( "encumbrance_always" ) ) {
        std::string part_id = ea.next_string();
        int enc = ea.next_int();
        encumbrance_always[get_body_part_token( part_id )] = enc;
    }
    for( JsonArray ec : jo.get_array( "encumbrance_covered" ) ) {
        std::string part_id = ec.next_string();
        int enc = ec.next_int();
        encumbrance_covered[get_body_part_token( part_id )] = enc;
    }
    for( const std::string line : jo.get_array( "restricts_gear" ) ) {
        restricts_gear.insert( get_body_part_token( line ) );
    }
    for( JsonObject ao : jo.get_array( "armor" ) ) {
        auto parts = ao.get_tags( "parts" );
        std::set<body_part> bps;
        for( const std::string &part_string : parts ) {
            if( part_string == "ALL" ) {
                // Shorthand, since many mutations protect whole body
                bps.insert( all_body_parts.begin(), all_body_parts.end() );
            } else {
                bps.insert( get_body_part_token( part_string ) );
            }
        }
        resistances res = load_resistances_instance( ao );
        for( body_part bp : bps ) {
            armor[ bp ] = res;
        }
    }
    if( jo.has_array( "attacks" ) ) {
        for( JsonObject ao : jo.get_array( "attacks" ) ) {
            attacks_granted.emplace_back( load_mutation_attack( ao ) );
        }
    } else if( jo.has_object( "attacks" ) ) {
        JsonObject attack = jo.get_object( "attacks" );
        attacks_granted.emplace_back( load_mutation_attack( attack ) );
    }
}
References _, activated, additions, all_body_parts, allow_soft_gear, allowed_category, anger_relations, armor, attackcost_modifier, attacks_granted, bash_dmg_bonus, bleed_resist, body_size, bodytemp_max, bodytemp_min, bodytemp_sleep, butchering_quality, can_heal_with, can_only_eat, can_only_heal_with, cancels, category, cooldown, cost, craft_skill_bonus, cut_dmg_bonus, debug, dodge_modifier, enchantments, encumbrance_always, encumbrance_covered, fatigue, fatigue_modifier, fatigue_regen_modifier, flags, time_duration::from_turns(), JsonObject::get_array(), JsonArray::get_array(), get_body_part_token(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), healing_awake, healing_resting, healthy_rate, hearing_modifier, hp_adjustment, hp_modifier, hp_modifier_secondary, hunger, ignored_by, initial_ma_styles, string_id< T >::is_valid(), line(), load_mutation_attack(), load_mutation_mods(), load_mutation_social_mods(), load_resistances_instance(), lumination, mana_modifier, mana_multiplier, mana_regen_multiplier, mandatory(), max_stamina_modifier, mending_modifier, metabolism_modifier, mixed_effect, mods, movecost_flatground_modifier, movecost_modifier, movecost_obstacle_modifier, movecost_swim_modifier, neutral, night_vision_range, no_cbm_on_bp, noise_modifier, cata::nullopt, optional(), overmap_multiplier, overmap_sight, pain_recovery, pierce_dmg_bonus, player_display, points, prereqs, prereqs2, protection, purifiable, rand_bash_bonus, rand_cut_bonus, ranged_mutation, raw_desc, raw_name, raw_ranged_mutation_message, raw_spawn_item_message, reading_speed_multiplier, replacements, restricts_gear, scent_intensity, scent_mask, scent_modifier, scent_typeid, skill_rust_multiplier, coords::sm, social_mods, spawn_item, species_id, speed_modifier, spells_learned, stamina_regen_modifier, startingtrait, starts_active, stealth_modifier, str_modifier, cata::swap(), temperature_speed_modifier, thirst, thirst_modifier, threshold, threshreq, JsonObject::throw_error(), transform, types, ugliness, valid, visibility, vitamin_absorb_multi, vitamin_rates, was_loaded, weakness_to_water, and weight_capacity_modifier.
load_trait()
void mutation_branch::load_trait (const JsonObject & jo, const std::string & src) static
Definition at line 288 of file mutation_data.cpp.
{
    trait_factory.load( jo, src );
}
References anonymous_namespace{mutation_data.cpp}::trait_factory.
Referenced by DynamicDataLoader::initialize().
load_trait_blacklist()
void mutation_branch::load_trait_blacklist (const JsonObject & jsobj) static
Load a trait blacklist specified by the given JSON object.
Definition at line 706 of file mutation_data.cpp.
{
    for( const std::string line : jsobj.get_array( "traits" ) ) {
        trait_blacklist.insert( trait_id( line ) );
    }
}
References JsonObject::get_array(), line(), trait_blacklist, and trait_id.
Referenced by DynamicDataLoader::initialize().
load_trait_group() [1/3]
void mutation_branch::load_trait_group (const JsonArray & entries, const trait_group::Trait_group_tag & gid, bool is_collection) static
Like the above function, except this function assumes that the given array is the "entries" member of the trait group.
For each element in the array, mutation_branch::add_entry is called.
Assuming the input array looks like [ x, y, z ], this function loads it like the above would load this object:
{
     "subtype": "depends on is_collection parameter",
     "id": "identfier",
     "entries": [ x, y, z ]
}
Note that each entry in the array has to be a JSON object. The other function above can also load data from arrays of strings, where the strings are item or group ids.
Definition at line 766 of file mutation_data.cpp.
{
    Trait_group &tg = make_group_or_throw( gid, is_collection );
    for( const JsonValue entry : entries ) {
        // Backwards-compatibility with old format ["TRAIT", 100]
        if( entry.test_array() ) {
            JsonArray subarr = entry.get_array();
            trait_id id( subarr.get_string( 0 ) );
            tg.add_entry( std::make_unique<Single_trait_creator>( id, subarr.get_int( 1 ) ) );
            // Otherwise load new format {"trait": ... } or {"group": ...}
        } else {
            JsonObject subobj = entry.get_object();
            add_entry( tg, subobj );
        }
    }
}
References Trait_group::add_entry(), add_entry(), JsonArray::get_array(), JsonArray::get_int(), JsonObject::get_object(), JsonArray::get_string(), id, and make_group_or_throw().
load_trait_group() [2/3]
void mutation_branch::load_trait_group (const JsonObject & jsobj) static
Callback for the init system (DynamicDataLoader), loads a trait group definitions.
Parameters
jsobj The json object to load from.
Exceptions
JsonError if the json object contains invalid data.
Definition at line 737 of file mutation_data.cpp.
{
    const trait_group::Trait_group_tag group_id( jsobj.get_string( "id" ) );
    const std::string subtype = jsobj.get_string( "subtype", "old" );
    load_trait_group( jsobj, group_id, subtype );
}
References JsonObject::get_string(), and load_trait_group().
Referenced by DynamicDataLoader::initialize(), load_trait_group(), and trait_group::load_trait_group().
load_trait_group() [3/3]
void mutation_branch::load_trait_group (const JsonObject & jsobj, const trait_group::Trait_group_tag & gid, const std::string & subtype) static
Load a trait group from json.
It differs from the other load_trait_group function as it uses the group ID and subtype given as parameters, and does not look them up in the json data (i.e. the given json object does not need to have them).
This is intended for inline definitions of trait groups, e.g. in NPC class definitions: the trait group there is embedded into the class type definition.
Parameters
jsobj The json object to load from.
gid The ID of the group that is to be loaded.
subtype The type of the trait group, either "collection", "distribution" or "old" (i.e. the old list-based format, [ ["TRAIT", 100] ]).
Exceptions
JsonError if the json object contains invalid data.
Definition at line 786 of file mutation_data.cpp.
{
    if( subtype != "distribution" && subtype != "collection" && subtype != "old" ) {
        jsobj.throw_error( "unknown trait group type", "subtype" );
    }
    Trait_group &tg = make_group_or_throw( gid, subtype == "collection" || subtype == "old" );
    // TODO: (sm) Looks like this makes the new code backwards-compatible with the old format. Great if so!
    if( subtype == "old" ) {
        for( JsonArray pair : jsobj.get_array( "traits" ) ) {
            tg.add_trait_entry( trait_id( pair.get_string( 0 ) ), pair.get_int( 1 ) );
        }
        return;
    }
    // TODO: (sm) Taken from item_factory.cpp almost verbatim. Ensure that these work!
    if( jsobj.has_member( "entries" ) ) {
        for( JsonObject subobj : jsobj.get_array( "entries" ) ) {
            add_entry( tg, subobj );
        }
    }
    if( jsobj.has_member( "traits" ) ) {
        for( const JsonValue entry : jsobj.get_array( "traits" ) ) {
            if( entry.test_string() ) {
                tg.add_trait_entry( trait_id( entry.get_string() ), 100 );
            } else if( entry.test_array() ) {
                JsonArray subtrait = entry.get_array();
                tg.add_trait_entry( trait_id( subtrait.get_string( 0 ) ), subtrait.get_int( 1 ) );
            } else {
                JsonObject subobj = entry.get_object();
                add_entry( tg, subobj );
            }
        }
    }
    if( jsobj.has_member( "groups" ) ) {
        for( const JsonValue entry : jsobj.get_array( "groups" ) ) {
            if( entry.test_string() ) {
                tg.add_group_entry( trait_group::Trait_group_tag( entry.get_string() ), 100 );
            } else if( entry.test_array() ) {
                JsonArray subtrait = entry.get_array();
                tg.add_group_entry( trait_group::Trait_group_tag( subtrait.get_string( 0 ) ),
                                    subtrait.get_int( 1 ) );
            } else {
                JsonObject subobj = entry.get_object();
                add_entry( tg, subobj );
            }
        }
    }
}
References add_entry(), Trait_group::add_group_entry(), Trait_group::add_trait_entry(), JsonObject::get_array(), JsonArray::get_array(), JsonArray::get_int(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_member(), make_group_or_throw(), JsonObject::throw_error(), and trait_id.
name()
std::string mutation_branch::name () const
Definition at line 559 of file mutation_data.cpp.
{
    return raw_name.translated();
}
References raw_name, and translation::translated().
Referenced by Character::can_install_bionics(), can_use_mutation_warn(), character_display::disp_info(), spellcasting_callback::draw_spell_info(), draw_spellbook_info(), get_name(), known_magic::learn_spell(), Character::mutate(), Character::mutate_towards(), memorial_logger::notify(), player::power_mutations_ui(), set_traits(), and Character::suffer_mutation_power().
ranged_mutation_message()
std::string mutation_branch::ranged_mutation_message () const
Definition at line 554 of file mutation_data.cpp.
{
    return _( raw_ranged_mutation_message );
}
References _, and raw_ranged_mutation_message.
Referenced by Character::activate_mutation().
reset_all()
void mutation_branch::reset_all () static
Definition at line 648 of file mutation_data.cpp.
{
    mutations_category.clear();
    trait_factory.reset();
    trait_blacklist.clear();
    trait_groups.clear();
    trait_groups.emplace( trait_group::Trait_group_tag( "EMPTY_GROUP" ),
                          make_shared_fast<Trait_group_collection>( 100 ) );
}
References mutations_category, trait_blacklist, anonymous_namespace{mutation_data.cpp}::trait_factory, and trait_groups.
Referenced by DynamicDataLoader::unload_data().
spawn_item_message()
std::string mutation_branch::spawn_item_message () const
Definition at line 549 of file mutation_data.cpp.
{
    return _( raw_spawn_item_message );
}
References _, and raw_spawn_item_message.
Referenced by Character::activate_mutation().
trait_is_blacklisted()
bool mutation_branch::trait_is_blacklisted (const trait_id & tid) static
Check if the trait with the given ID is blacklisted.
Definition at line 713 of file mutation_data.cpp.
{
    return trait_blacklist.count( tid );
}
References trait_blacklist.
Referenced by Character::mutation_ok(), and set_traits().
Member Data Documentation
activated
bool mutation_branch::activated = false
Definition at line 93 of file mutation.h.
Referenced by load(), and player::power_mutations_ui().
additions
std::vector<trait_id> mutation_branch::additions
Definition at line 264 of file mutation.h.
Referenced by load(), Character::mutation_chances(), Character::old_mutate(), and wish_mutate_callback::refresh().
allow_soft_gear
bool mutation_branch::allow_soft_gear = false
Definition at line 97 of file mutation.h.
Referenced by conflicts_with_item(), and load().
allowed_category
std::set<std::string> mutation_branch::allowed_category
List of allowed mutatrion category.
Definition at line 221 of file mutation.h.
Referenced by load().
anger_relations
std::map<species_id, int> mutation_branch::anger_relations
Map of angered species and there intensity.
Definition at line 211 of file mutation.h.
Referenced by load().
armor
std::map<body_part, resistances> mutation_branch::armor
Definition at line 276 of file mutation.h.
Referenced by damage_resistance(), and load().
attackcost_modifier
float mutation_branch::attackcost_modifier = 1.0f
Definition at line 140 of file mutation.h.
Referenced by load().
attacks_granted
std::vector<mut_attack> mutation_branch::attacks_granted
Attacks granted by this mutation.
Definition at line 250 of file mutation.h.
Referenced by load(), and Character::mutation_attacks().
bash_dmg_bonus
int mutation_branch::bash_dmg_bonus = 0
Definition at line 132 of file mutation.h.
Referenced by load().
bleed_resist
float mutation_branch::bleed_resist = 0
Definition at line 147 of file mutation.h.
Referenced by load().
body_size
cata::optional<m_size> mutation_branch::body_size
Definition at line 227 of file mutation.h.
Referenced by load().
bodytemp_max
int mutation_branch::bodytemp_max = 0
Definition at line 111 of file mutation.h.
Referenced by load().
bodytemp_min
int mutation_branch::bodytemp_min = 0
Definition at line 110 of file mutation.h.
Referenced by load().
bodytemp_sleep
int mutation_branch::bodytemp_sleep = 0
Definition at line 112 of file mutation.h.
Referenced by load().
butchering_quality
int mutation_branch::butchering_quality = 0
Definition at line 151 of file mutation.h.
Referenced by load().
can_heal_with
std::set<itype_id> mutation_branch::can_heal_with
Definition at line 218 of file mutation.h.
Referenced by load().
can_only_eat
std::set<material_id> mutation_branch::can_only_eat
List of material required for food to be be edible.
Definition at line 214 of file mutation.h.
Referenced by load().
can_only_heal_with
std::set<itype_id> mutation_branch::can_only_heal_with
List of healing items allowed.
Definition at line 217 of file mutation.h.
Referenced by load().
cancels
std::vector<trait_id> mutation_branch::cancels
Definition at line 262 of file mutation.h.
Referenced by are_opposite_traits(), Character::has_opposite_trait(), known_magic::learn_spell(), load(), Character::mutate_towards(), and wish_mutate_callback::refresh().
category
std::vector<std::string> mutation_branch::category
Definition at line 265 of file mutation.h.
Referenced by load(), Character::mutation_ok(), wish_mutate_callback::refresh(), and Character::set_highest_cat_level().
cooldown
int mutation_branch::cooldown = 0
Definition at line 108 of file mutation.h.
Referenced by load(), Character::mutation_spend_resources(), player::power_mutations_ui(), mon_special_attack::serialize(), and Character::suffer_mutation_power().
cost
int mutation_branch::cost = 0
Definition at line 106 of file mutation.h.
Referenced by load(), Character::mutation_spend_resources(), player::power_mutations_ui(), and Character::suffer_mutation_power().
craft_skill_bonus
std::map<skill_id, int> mutation_branch::craft_skill_bonus
Map of crafting skills modifiers, can be negative.
Definition at line 156 of file mutation.h.
Referenced by load().
cut_dmg_bonus
int mutation_branch::cut_dmg_bonus = 0
Definition at line 129 of file mutation.h.
Referenced by load().
debug
bool mutation_branch::debug = false
Definition at line 87 of file mutation.h.
Referenced by get_display_color(), and load().
dodge_modifier
float mutation_branch::dodge_modifier = 0.0f
Definition at line 135 of file mutation.h.
Referenced by load().
enchantments
std::vector<enchantment_id> mutation_branch::enchantments
mutation enchantments
Definition at line 236 of file mutation.h.
Referenced by Character::activate_mutation(), Character::deactivate_mutation(), and load().
encumbrance_always
std::map<body_part, int> mutation_branch::encumbrance_always
Definition at line 268 of file mutation.h.
Referenced by apply_mut_encumbrance(), and load().
encumbrance_covered
std::map<body_part, int> mutation_branch::encumbrance_covered
Definition at line 270 of file mutation.h.
Referenced by apply_mut_encumbrance(), and load().
fatigue
bool mutation_branch::fatigue = false
Definition at line 99 of file mutation.h.
Referenced by can_use_mutation(), load(), Character::mutation_spend_resources(), player::power_mutations_ui(), and Character::suffer_mutation_power().
fatigue_modifier
float mutation_branch::fatigue_modifier = 0.0f
Definition at line 183 of file mutation.h.
Referenced by load().
fatigue_regen_modifier
float mutation_branch::fatigue_regen_modifier = 0.0f
Definition at line 185 of file mutation.h.
Referenced by load().
flags
std::set<std::string> mutation_branch::flags
Definition at line 266 of file mutation.h.
Referenced by Character::has_trait_flag(), load(), and Character::set_highest_cat_level().
healing_awake
float mutation_branch::healing_awake = 0.0f
Definition at line 116 of file mutation.h.
Referenced by load().
healing_resting
float mutation_branch::healing_resting = 0.0f
Definition at line 117 of file mutation.h.
Referenced by load().
healthy_rate
float mutation_branch::healthy_rate = 1.0f
How fast does healthy tends toward healthy_mod.
Definition at line 165 of file mutation.h.
Referenced by load().
hearing_modifier
float mutation_branch::hearing_modifier = 1.0f
Definition at line 143 of file mutation.h.
Referenced by load().
hp_adjustment
float mutation_branch::hp_adjustment = 0.0f
Definition at line 125 of file mutation.h.
Referenced by load().
hp_modifier
float mutation_branch::hp_modifier = 0.0f
Definition at line 121 of file mutation.h.
Referenced by load().
hp_modifier_secondary
float mutation_branch::hp_modifier_secondary = 0.0f
Definition at line 123 of file mutation.h.
Referenced by load().
hunger
bool mutation_branch::hunger = false
Definition at line 100 of file mutation.h.
Referenced by can_use_mutation(), load(), Character::mutation_spend_resources(), player::power_mutations_ui(), and Character::suffer_mutation_power().
id
trait_id mutation_branch::id
Definition at line 76 of file mutation.h.
Referenced by add_entry(), load_trait_group(), Character::mutate_towards(), wish_mutate_callback::refresh(), set_traits(), and Character::suffer_mutation_power().
ignored_by
std::vector<species_id> mutation_branch::ignored_by
Species ignoring character with the mutation.
Definition at line 208 of file mutation.h.
Referenced by load().
initial_ma_styles
std::vector<matype_id> mutation_branch::initial_ma_styles
Definition at line 278 of file mutation.h.
Referenced by load().
lumination
std::map<body_part, float> mutation_branch::lumination
Map of glowing body parts and their glow intensity.
Definition at line 162 of file mutation.h.
Referenced by load().
mana_modifier
float mutation_branch::mana_modifier = 0.0f
Definition at line 230 of file mutation.h.
Referenced by load().
mana_multiplier
float mutation_branch::mana_multiplier = 1.0f
Definition at line 231 of file mutation.h.
Referenced by load().
mana_regen_multiplier
float mutation_branch::mana_regen_multiplier = 1.0f
Definition at line 232 of file mutation.h.
Referenced by load().
max_stamina_modifier
float mutation_branch::max_stamina_modifier = 1.0f
Definition at line 141 of file mutation.h.
Referenced by load().
mending_modifier
float mutation_branch::mending_modifier = 1.0f
Definition at line 119 of file mutation.h.
Referenced by load().
metabolism_modifier
float mutation_branch::metabolism_modifier = 0.0f
Definition at line 179 of file mutation.h.
Referenced by load().
mixed_effect
bool mutation_branch::mixed_effect = false
Definition at line 91 of file mutation.h.
Referenced by get_display_color(), load(), and Character::mutate_towards().
mods
std::unordered_map<std::pair<bool, std::string>, int, cata::tuple_hash> mutation_branch::mods
Key pair is <active: bool, mod type: "STR">
Definition at line 275 of file mutation.h.
Referenced by Character::get_mod(), and load().
movecost_flatground_modifier
float mutation_branch::movecost_flatground_modifier = 1.0f
Definition at line 138 of file mutation.h.
Referenced by load().
movecost_modifier
float mutation_branch::movecost_modifier = 1.0f
Definition at line 137 of file mutation.h.
Referenced by load().
movecost_obstacle_modifier
float mutation_branch::movecost_obstacle_modifier = 1.0f
Definition at line 139 of file mutation.h.
Referenced by load().
movecost_swim_modifier
float mutation_branch::movecost_swim_modifier = 1.0f
Definition at line 144 of file mutation.h.
Referenced by load().
night_vision_range
float mutation_branch::night_vision_range = 0.0f
Night vision range (in tiles), added to NV from stats.
Only the highest value from all mutations applies.
Definition at line 174 of file mutation.h.
Referenced by load().
no_cbm_on_bp
std::set<bodypart_str_id> mutation_branch::no_cbm_on_bp
List of body parts locked out of bionics.
Definition at line 224 of file mutation.h.
Referenced by load().
noise_modifier
float mutation_branch::noise_modifier = 1.0f
Definition at line 145 of file mutation.h.
Referenced by load().
overmap_multiplier
float mutation_branch::overmap_multiplier = 1.0f
Definition at line 193 of file mutation.h.
Referenced by load().
overmap_sight
float mutation_branch::overmap_sight = 0.0f
Definition at line 190 of file mutation.h.
Referenced by load().
pain_recovery
float mutation_branch::pain_recovery = 0.0f
Definition at line 114 of file mutation.h.
Referenced by load().
pierce_dmg_bonus
float mutation_branch::pierce_dmg_bonus = 0.0
Definition at line 130 of file mutation.h.
Referenced by load().
player_display
bool mutation_branch::player_display = true
Definition at line 89 of file mutation.h.
Referenced by load().
points
int mutation_branch::points = 0
Definition at line 103 of file mutation.h.
Referenced by get_display_color(), load(), Character::mutate_towards(), Character::mutation_ok(), avatar::randomize(), wish_mutate_callback::refresh(), and set_traits().
prereqs
std::vector<trait_id> mutation_branch::prereqs
Definition at line 258 of file mutation.h.
Referenced by b_is_lower_trait_of_a(), Character::build_mut_dependency_map(), newcharacter::has_lower_trait(), load(), Character::mutate_towards(), and wish_mutate_callback::refresh().
prereqs2
std::vector<trait_id> mutation_branch::prereqs2
Definition at line 259 of file mutation.h.
Referenced by Character::build_mut_dependency_map(), load(), Character::mutate_towards(), and wish_mutate_callback::refresh().
profession
bool mutation_branch::profession = false
Definition at line 85 of file mutation.h.
Referenced by Character::mutate_towards(), Character::mutation_chances(), Character::old_mutate(), and avatar::randomize().
protection
std::map<body_part, tripoint> mutation_branch::protection
Definition at line 267 of file mutation.h.
Referenced by Character::drench_mut_calc(), and load().
purifiable
bool mutation_branch::purifiable = false
Definition at line 81 of file mutation.h.
Referenced by load(), Character::mutation_chances(), and Character::old_mutate().
rand_bash_bonus
std::pair<int, int> mutation_branch::rand_bash_bonus
Definition at line 133 of file mutation.h.
Referenced by load().
rand_cut_bonus
std::pair<int, int> mutation_branch::rand_cut_bonus
Definition at line 131 of file mutation.h.
Referenced by load().
ranged_mutation
itype_id mutation_branch::ranged_mutation
The fake gun, if any, spawned and fired by the ranged mutation.
Definition at line 243 of file mutation.h.
Referenced by Character::activate_mutation(), and load().
raw_desc
translation mutation_branch::raw_desc private
Definition at line 281 of file mutation.h.
Referenced by desc(), and load().
raw_name
translation mutation_branch::raw_name private
Definition at line 280 of file mutation.h.
Referenced by load(), and name().
raw_ranged_mutation_message
std::string mutation_branch::raw_ranged_mutation_message private
Definition at line 245 of file mutation.h.
Referenced by load(), and ranged_mutation_message().
raw_spawn_item_message
std::string mutation_branch::raw_spawn_item_message private
Definition at line 238 of file mutation.h.
Referenced by load(), and spawn_item_message().
reading_speed_multiplier
float mutation_branch::reading_speed_multiplier = 1.0f
Definition at line 196 of file mutation.h.
Referenced by load().
replacements
std::vector<trait_id> mutation_branch::replacements
Definition at line 263 of file mutation.h.
Referenced by b_is_higher_trait_of_a(), Character::build_mut_dependency_map(), Character::has_child_flag(), newcharacter::has_higher_trait(), load(), Character::mutation_chances(), Character::old_mutate(), wish_mutate_callback::refresh(), and Character::remove_child_flag().
restricts_gear
std::set<body_part> mutation_branch::restricts_gear
Definition at line 272 of file mutation.h.
Referenced by conflicts_with_item(), and load().
scent_intensity
cata::optional<int> mutation_branch::scent_intensity
Definition at line 148 of file mutation.h.
Referenced by load().
scent_mask
cata::optional<int> mutation_branch::scent_mask
Definition at line 149 of file mutation.h.
Referenced by load().
scent_modifier
float mutation_branch::scent_modifier = 1.0f
Definition at line 146 of file mutation.h.
Referenced by load().
scent_typeid
cata::optional<scenttype_id> mutation_branch::scent_typeid
What do you smell like.
Definition at line 159 of file mutation.h.
Referenced by load(), and Character::update_type_of_scent().
skill_rust_multiplier
float mutation_branch::skill_rust_multiplier = 1.0f
Definition at line 199 of file mutation.h.
Referenced by load().
social_mods
social_modifiers mutation_branch::social_mods
Definition at line 202 of file mutation.h.
Referenced by load().
spawn_item
itype_id mutation_branch::spawn_item
The item, if any, spawned by the mutation.
Definition at line 205 of file mutation.h.
Referenced by Character::activate_mutation(), and load().
speed_modifier
float mutation_branch::speed_modifier = 1.0f
Definition at line 136 of file mutation.h.
Referenced by load().
spells_learned
std::map<spell_id, int> mutation_branch::spells_learned
Definition at line 234 of file mutation.h.
Referenced by load(), and known_magic::on_mutation_gain().
stamina_regen_modifier
float mutation_branch::stamina_regen_modifier = 0.0f
Definition at line 187 of file mutation.h.
Referenced by load().
startingtrait
bool mutation_branch::startingtrait = false
Definition at line 92 of file mutation.h.
Referenced by load(), and scenario::traitquery().
starts_active
bool mutation_branch::starts_active = false
Definition at line 95 of file mutation.h.
Referenced by load().
stealth_modifier
float mutation_branch::stealth_modifier = 0.0f
Definition at line 171 of file mutation.h.
Referenced by load().
str_modifier
float mutation_branch::str_modifier = 0.0f
Definition at line 127 of file mutation.h.
Referenced by load().
temperature_speed_modifier
float mutation_branch::temperature_speed_modifier = 0.0f
Definition at line 177 of file mutation.h.
Referenced by load().
thirst
bool mutation_branch::thirst = false
Definition at line 101 of file mutation.h.
Referenced by can_use_mutation(), load(), Character::mutation_spend_resources(), player::power_mutations_ui(), and Character::suffer_mutation_power().
thirst_modifier
float mutation_branch::thirst_modifier = 0.0f
Definition at line 181 of file mutation.h.
Referenced by load().
threshold
bool mutation_branch::threshold = false
Definition at line 83 of file mutation.h.
Referenced by Character::crossed_threshold(), character_display::disp_info(), get_display_color(), load(), Character::mutate_towards(), Character::mutation_chances(), Character::old_mutate(), and debug_menu::wishmutate().
threshreq
std::vector<trait_id> mutation_branch::threshreq
Definition at line 260 of file mutation.h.
Referenced by load(), Character::mutate_towards(), and wish_mutate_callback::refresh().
transform
cata::value_ptr<mut_transform> mutation_branch::transform
Definition at line 153 of file mutation.h.
Referenced by Character::activate_mutation(), check_consistency(), Character::deactivate_mutation(), load(), and player::power_mutations_ui().
types
std::set<std::string> mutation_branch::types
Definition at line 261 of file mutation.h.
Referenced by are_same_type_traits(), newcharacter::has_same_type_trait(), load(), Character::mutate_towards(), and wish_mutate_callback::refresh().
ugliness
int mutation_branch::ugliness = 0
Definition at line 105 of file mutation.h.
Referenced by load(), and wish_mutate_callback::refresh().
valid
bool mutation_branch::valid = false
Definition at line 79 of file mutation.h.
Referenced by load(), Character::mutation_chances(), Character::old_mutate(), and wish_mutate_callback::refresh().
visibility
int mutation_branch::visibility = 0
Definition at line 104 of file mutation.h.
Referenced by load(), and wish_mutate_callback::refresh().
vitamin_absorb_multi
std::map<material_id, std::map<vitamin_id, double> > mutation_branch::vitamin_absorb_multi
Definition at line 256 of file mutation.h.
Referenced by load().
vitamin_rates
std::map<vitamin_id, time_duration> mutation_branch::vitamin_rates
Mutations may adjust one or more of the default vitamin usage rates.
Definition at line 253 of file mutation.h.
Referenced by load().
was_loaded
bool mutation_branch::was_loaded = false
Definition at line 77 of file mutation.h.
Referenced by load().
weakness_to_water
int mutation_branch::weakness_to_water = 0
maximum damage dealt by water every minute when wet.
Can be negative and regen hit points.
Definition at line 168 of file mutation.h.
Referenced by load(), and Character::suffer_water_damage().
weight_capacity_modifier
float mutation_branch::weight_capacity_modifier = 1.0f
Definition at line 142 of file mutation.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation.cpp
src/mutation_data.cpp