Cataclysm BN: temperature_effect Struct Reference
temperature_effect Struct Reference
Public Member Functions
temperature_effect (int sp, int dp, int ip, int pp, const std::string &ms, int mc, const char *mm)
void apply (player &u) const
Public Attributes
int str_pen
int dex_pen
int int_pen
int per_pen
std::string msg
int msg_chance
const char * miss_msg
Detailed Description
Definition at line 295 of file player_hardcoded_effects.cpp.
Constructor & Destructor Documentation
temperature_effect()
temperature_effect::temperature_effect (int sp, int dp, int ip, int pp, const std::string & ms, int mc, const char * mm) inline
Definition at line 307 of file player_hardcoded_effects.cpp.
                                         :
        str_pen( sp ), dex_pen( dp ), int_pen( ip ), per_pen( pp ), msg( ms ),
        msg_chance( mc ), miss_msg( mm ) {
    }
Member Function Documentation
apply()
void temperature_effect::apply (player & u) const inline
Definition at line 313 of file player_hardcoded_effects.cpp.
{
        if( str_pen > 0 ) {
            u.mod_str_bonus( -str_pen );
        }
        if( dex_pen > 0 ) {
            u.mod_dex_bonus( -dex_pen );
            u.add_miss_reason( _( miss_msg ), dex_pen );
        }
        if( int_pen > 0 ) {
            u.mod_int_bonus( -int_pen );
        }
        if( per_pen > 0 ) {
            u.mod_per_bonus( -per_pen );
        }
        if( !msg.empty() && !u.has_effect( effect_sleep ) && one_in( msg_chance ) ) {
            u.add_msg_if_player( m_warning, "%s", _( msg ) );
        }
    }
References _, Character::add_miss_reason(), player::add_msg_if_player(), dex_pen, effect_sleep, Creature::has_effect(), int_pen, m_warning, miss_msg, Character::mod_dex_bonus(), Character::mod_int_bonus(), Character::mod_per_bonus(), Character::mod_str_bonus(), msg, msg_chance, one_in(), per_pen, and str_pen.
Member Data Documentation
dex_pen
int temperature_effect::dex_pen
Definition at line 297 of file player_hardcoded_effects.cpp.
Referenced by apply().
int_pen
int temperature_effect::int_pen
Definition at line 298 of file player_hardcoded_effects.cpp.
Referenced by apply().
miss_msg
const char* temperature_effect::miss_msg
Definition at line 305 of file player_hardcoded_effects.cpp.
Referenced by apply().
msg
std::string temperature_effect::msg
Definition at line 301 of file player_hardcoded_effects.cpp.
Referenced by apply().
msg_chance
int temperature_effect::msg_chance
Definition at line 302 of file player_hardcoded_effects.cpp.
Referenced by apply().
per_pen
int temperature_effect::per_pen
Definition at line 299 of file player_hardcoded_effects.cpp.
Referenced by apply().
str_pen
int temperature_effect::str_pen
Definition at line 296 of file player_hardcoded_effects.cpp.
Referenced by apply().
The documentation for this struct was generated from the following file:
src/player_hardcoded_effects.cpp