Cataclysm BN: construction_category Struct Reference
construction_category Struct Reference
#include <construction_category.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
std::string name () const
Static Public Member Functions
static size_t count ()
Public Attributes
construction_category_id id
bool was_loaded = false
Private Attributes
translation _name
Detailed Description
Definition at line 14 of file construction_category.h.
Member Function Documentation
count()
size_t construction_category::count () static
Definition at line 26 of file construction_category.cpp.
{
    return all_construction_categories.size();
}
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
Referenced by construction_menu().
load()
void construction_category::load (const JsonObject & jo, const std::string & src)
Definition at line 21 of file construction_category.cpp.
{
    mandatory( jo, was_loaded, "name", _name );
}
References mandatory().
name()
std::string construction_category::name () const inline
Definition at line 20 of file construction_category.h.
{
            return _name.translated();
        }
References _name, and translation::translated().
Member Data Documentation
_name
translation construction_category::_name private
Definition at line 26 of file construction_category.h.
Referenced by name().
id
construction_category_id construction_category::id
Definition at line 17 of file construction_category.h.
was_loaded
bool construction_category::was_loaded = false
Definition at line 18 of file construction_category.h.
The documentation for this struct was generated from the following files:
src/construction_category.h
src/construction_category.cpp