Cataclysm BN: ma_requirements Struct Reference
ma_requirements Struct Reference
#include <martialarts.h>
Public Member Functions
ma_requirements ()
std::string get_description (bool buff=false) const
bool is_valid_character (const Character &u) const
bool is_valid_weapon (const item &i) const
void load (const JsonObject &jo, const std::string &src)
Public Attributes
bool was_loaded = false
bool unarmed_allowed
bool melee_allowed
bool unarmed_weapons_allowed
bool strictly_unarmed
bool wall_adjacent
std::vector< std::pair< skill_id, int > > min_skill
Minimum amount of given skill to trigger this bonus.
std::vector< std::pair< damage_type, int > > min_damage
Minimum amount of given damage type on the weapon Note: DT_FIRE currently won't work, not even on flaming weapons!
std::set< mabuff_id > req_buffs
std::set< std::string > req_flags
Detailed Description
Definition at line 27 of file martialarts.h.
Constructor & Destructor Documentation
ma_requirements()
ma_requirements::ma_requirements () inline
Definition at line 47 of file martialarts.h.
                      {
        unarmed_allowed = false;
        melee_allowed = false;
        unarmed_weapons_allowed = true;
        strictly_unarmed = false;
        wall_adjacent = false;
    }
References melee_allowed, strictly_unarmed, unarmed_allowed, unarmed_weapons_allowed, and wall_adjacent.
Member Function Documentation
get_description()
std::string ma_requirements::get_description (bool buff = false) const
Definition at line 500 of file martialarts.cpp.
{
    std::string dump;
    if( std::any_of( min_skill.begin(), min_skill.end(), []( const std::pair<skill_id, int> &pr ) {
    return pr.second > 0;
})) {
        dump += string_format( _( "<bold>%s required: </bold>" ),
                               vgettext( "Skill", "Skills", min_skill.size() ) );
        dump += enumerate_as_string( min_skill.begin(),
        min_skill.end(), []( const std::pair<skill_id, int>  &pr ) {
            int player_skill = get_player_character().get_skill_level( skill_id( pr.first ) );
            if( get_player_character().has_active_bionic( bio_cqb ) ) {
                player_skill = BIO_CQB_LEVEL;
            }
            return string_format( "%s: <stat>%d</stat>/<stat>%d</stat>", pr.first->name(), player_skill,
                                  pr.second );
        }, enumeration_conjunction::none ) + "\n";
    }
    if( std::any_of( min_damage.begin(),
    min_damage.end(), []( const std::pair<damage_type, int>  &pr ) {
    return pr.second > 0;
})) {
        dump += vgettext( "<bold>Damage type required: </bold>",
                          "<bold>Damage types required: </bold>", min_damage.size() );
        dump += enumerate_as_string( min_damage.begin(),
        min_damage.end(), []( const std::pair<damage_type, int>  &pr ) {
            return string_format( _( "%s: <stat>%d</stat>" ), name_by_dt( pr.first ), pr.second );
        }, enumeration_conjunction::none ) + "\n";
    }
    if( !req_buffs.empty() ) {
        dump += _( "<bold>Requires:</bold> " );
        dump += enumerate_as_string( req_buffs.begin(), req_buffs.end(), []( const mabuff_id & bid ) {
            return _( bid->name );
        }, enumeration_conjunction::none ) + "\n";
    }
    const std::string type = buff ? _( "activate" ) : _( "be used" );
    if( unarmed_allowed && melee_allowed ) {
        dump += string_format( _( "* Can %s while <info>armed</info> or <info>unarmed</info>" ),
                               type ) + "\n";
        if( unarmed_weapons_allowed ) {
            dump += string_format( _( "* Can %s while using <info>any unarmed weapon</info>" ),
                                   type ) + "\n";
        }
    } else if( unarmed_allowed ) {
        dump += string_format( _( "* Can <info>only</info> %s while <info>unarmed</info>" ),
                               type ) + "\n";
        if( unarmed_weapons_allowed ) {
            dump += string_format( _( "* Can %s while using <info>any unarmed weapon</info>" ),
                                   type ) + "\n";
        }
    } else if( melee_allowed ) {
        dump += string_format( _( "* Can <info>only</info> %s while <info>armed</info>" ),
                               type ) + "\n";
    }
    if( wall_adjacent ) {
        dump += string_format( _( "* Can %s while <info>near</info> to a <info>wall</info>" ),
                               type ) + "\n";
    }
    return dump;
}
References _, enumerate_as_string(), min_skill, none, string_format(), and vgettext().
Referenced by ma_technique::get_description(), and ma_buff::get_description().
is_valid_character()
bool ma_requirements::is_valid_character (const Character & u) const
Definition at line 438 of file martialarts.cpp.
{
    for( const mabuff_id &buff_id : req_buffs ) {
        if( !u.has_mabuff( buff_id ) ) {
            return false;
        }
    }
    //A technique is valid if it applies to unarmed strikes, if it applies generally
    //to all weapons (such as Ninjutsu sneak attacks or innate weapon techniques like RAPID)
    //or if the weapon is flagged as being compatible with the style. Some techniques have
    //further restrictions on required weapon properties (is_valid_weapon).
    bool cqb = u.has_active_bionic( bio_cqb );
    // There are 4 different cases of "armedness":
    // Truly unarmed, unarmed weapon, style-allowed weapon, generic weapon
    bool melee_style = u.martial_arts_data->selected_strictly_melee();
    bool is_armed = u.is_armed();
    bool unarmed_weapon = is_armed && u.used_weapon().has_flag( flag_UNARMED_WEAPON );
    bool forced_unarmed = u.martial_arts_data->selected_force_unarmed();
    bool weapon_ok = is_valid_weapon( u.weapon );
    bool style_weapon = u.martial_arts_data->selected_has_weapon( u.weapon.typeId() );
    bool all_weapons = u.martial_arts_data->selected_allow_melee();
    bool unarmed_ok = !is_armed || ( unarmed_weapon && unarmed_weapons_allowed );
    bool melee_ok = melee_allowed && weapon_ok && ( style_weapon || all_weapons );
    bool valid_unarmed = !melee_style && unarmed_allowed && unarmed_ok;
    bool valid_melee = !strictly_unarmed && ( forced_unarmed || melee_ok );
    if( !valid_unarmed && !valid_melee ) {
        return false;
    }
    if( wall_adjacent && !get_map().is_wall_adjacent( u.pos() ) ) {
        return false;
    }
    for( const auto &pr : min_skill ) {
        if( ( cqb ? 5 : u.get_skill_level( pr.first ) ) < pr.second ) {
            return false;
        }
    }
    return true;
}
References bio_cqb, flag_UNARMED_WEAPON(), get_map(), Character::get_skill_level(), Character::has_active_bionic(), item::has_flag(), Character::has_mabuff(), Character::is_armed(), is_valid_weapon(), map::is_wall_adjacent(), Character::martial_arts_data, melee_allowed, min_skill, Character::pos(), req_buffs, strictly_unarmed, item::typeId(), unarmed_allowed, unarmed_weapons_allowed, Character::used_weapon(), wall_adjacent, and Character::weapon.
Referenced by ma_technique::is_valid_character(), and ma_buff::is_valid_character().
is_valid_weapon()
bool ma_requirements::is_valid_weapon (const item & i) const
Definition at line 484 of file martialarts.cpp.
{
    for( const std::string &flag : req_flags ) {
        if( !i.has_flag( flag ) ) {
            return false;
        }
    }
    for( const auto &pr : min_damage ) {
        if( i.damage_melee( pr.first ) < pr.second ) {
            return false;
        }
    }
    return true;
}
References item::damage_melee(), item::has_flag(), min_damage, and req_flags.
Referenced by is_valid_character().
load()
void ma_requirements::load (const JsonObject & jo, const std::string & src)
Definition at line 131 of file martialarts.cpp.
{
    optional( jo, was_loaded, "unarmed_allowed", unarmed_allowed, false );
    optional( jo, was_loaded, "melee_allowed", melee_allowed, false );
    optional( jo, was_loaded, "unarmed_weapons_allowed", unarmed_weapons_allowed, true );
    optional( jo, was_loaded, "strictly_unarmed", strictly_unarmed, false );
    optional( jo, was_loaded, "wall_adjacent", wall_adjacent, false );
    optional( jo, was_loaded, "req_buffs", req_buffs, auto_flags_reader<mabuff_id> {} );
    optional( jo, was_loaded, "req_flags", req_flags, auto_flags_reader<> {} );
    optional( jo, was_loaded, "skill_requirements", min_skill, ma_skill_reader {} );
    optional( jo, was_loaded, "weapon_damage_requirements", min_damage, ma_weapon_damage_reader {} );
}
References melee_allowed, min_damage, min_skill, optional(), req_buffs, req_flags, strictly_unarmed, unarmed_allowed, unarmed_weapons_allowed, wall_adjacent, and was_loaded.
Referenced by ma_technique::load(), and ma_buff::load().
Member Data Documentation
melee_allowed
bool ma_requirements::melee_allowed
Definition at line 31 of file martialarts.h.
Referenced by is_valid_character(), load(), and ma_requirements().
min_damage
std::vector<std::pair<damage_type, int> > ma_requirements::min_damage
Minimum amount of given damage type on the weapon Note: DT_FIRE currently won't work, not even on flaming weapons!
Definition at line 42 of file martialarts.h.
Referenced by is_valid_weapon(), and load().
min_skill
std::vector<std::pair<skill_id, int> > ma_requirements::min_skill
Minimum amount of given skill to trigger this bonus.
Definition at line 37 of file martialarts.h.
Referenced by get_description(), is_valid_character(), and load().
req_buffs
std::set<mabuff_id> ma_requirements::req_buffs
Definition at line 44 of file martialarts.h.
Referenced by check(), is_valid_character(), and load().
req_flags
std::set<std::string> ma_requirements::req_flags
Definition at line 45 of file martialarts.h.
Referenced by is_valid_weapon(), and load().
strictly_unarmed
bool ma_requirements::strictly_unarmed
Definition at line 33 of file martialarts.h.
Referenced by is_valid_character(), load(), and ma_requirements().
unarmed_allowed
bool ma_requirements::unarmed_allowed
Definition at line 30 of file martialarts.h.
Referenced by is_valid_character(), load(), and ma_requirements().
unarmed_weapons_allowed
bool ma_requirements::unarmed_weapons_allowed
Definition at line 32 of file martialarts.h.
Referenced by is_valid_character(), load(), and ma_requirements().
wall_adjacent
bool ma_requirements::wall_adjacent
Definition at line 34 of file martialarts.h.
Referenced by is_valid_character(), load(), and ma_requirements().
was_loaded
bool ma_requirements::was_loaded = false
Definition at line 28 of file martialarts.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/martialarts.h
src/martialarts.cpp