Cataclysm BN: pickup::act_item Struct Reference
pickup::act_item Struct Reference
Activity-associated item.
#include <pickup_token.h>
Public Member Functions
act_item ()=default
act_item (const item_location &loc, int count, int consumed_moves)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Public Attributes
item_location loc
inventory item
int count = 0
How many items need to be processed.
int consumed_moves = 0
Amount of moves that processing will consume.
Detailed Description
Activity-associated item.
Definition at line 19 of file pickup_token.h.
Constructor & Destructor Documentation
act_item() [1/2]
pickup::act_item::act_item () default
act_item() [2/2]
pickup::act_item::act_item (const item_location & loc, int count, int consumed_moves) inline
Definition at line 28 of file pickup_token.h.
        : loc( loc ),
          count( count ),
          consumed_moves( consumed_moves ) {}
Member Function Documentation
deserialize()
void pickup::act_item::deserialize (JsonIn & jsin)
Definition at line 3518 of file savegame_json.cpp.
{
    jsin.start_array();
    jsin.read( loc );
    jsin.read( count );
    jsin.read( consumed_moves );
    jsin.end_array();
}
References item::count(), JsonIn::end_array(), JsonIn::read(), and JsonIn::start_array().
serialize()
void pickup::act_item::serialize (JsonOut & jsout) const
Definition at line 3509 of file savegame_json.cpp.
{
    jsout.start_array();
    jsout.write( loc );
    jsout.write( count );
    jsout.write( consumed_moves );
    jsout.end_array();
}
References item::count(), JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
Member Data Documentation
consumed_moves
int pickup::act_item::consumed_moves = 0
Amount of moves that processing will consume.
Definition at line 25 of file pickup_token.h.
Referenced by pickup::obtain_and_tokenize_items().
count
int pickup::act_item::count = 0
How many items need to be processed.
Definition at line 23 of file pickup_token.h.
Referenced by pickup::obtain_and_tokenize_items().
loc
item_location pickup::act_item::loc
inventory item
Definition at line 21 of file pickup_token.h.
Referenced by pickup::obtain_and_tokenize_items(), and pickup::reorder_for_dropping().
The documentation for this struct was generated from the following files:
src/pickup_token.h
src/savegame_json.cpp