Cataclysm BN: partial_con Struct Reference
partial_con Struct Reference
#include <construction.h>
Public Attributes
int counter = 0
std::list< item > components = {}
construction_id id = construction_id(-1)
Detailed Description
Definition at line 30 of file construction.h.
Member Data Documentation
components
std::list<item> partial_con::components = {}
Definition at line 32 of file construction.h.
Referenced by construction_activity(), submap::load(), place_construction(), and iexamine::trap().
counter
int partial_con::counter = 0
Definition at line 31 of file construction.h.
Referenced by activity_handlers::build_do_turn(), construction_activity(), player_activity::get_progress_message(), submap::load(), place_construction(), game::print_trap_info(), and iexamine::trap().
id
construction_id partial_con::id = construction_id(-1)
Definition at line 33 of file construction.h.
Referenced by activity_handlers::build_do_turn(), can_do_activity_there(), complete_construction(), construction_activity(), submap::load(), place_construction(), game::print_trap_info(), and iexamine::trap().
The documentation for this struct was generated from the following file:
src/construction.h