Cataclysm BN: wisheffect_state Struct Reference
wisheffect_state Struct Reference
#include <uistate.h>
Public Member Functions
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Public Attributes
int last_type_selected_index = 0
bodypart_str_id bodypart = bodypart_str_id::NULL_ID()
time_duration duration = 0_seconds
int intensity = -1
bool force = false
Detailed Description
Definition at line 54 of file uistate.h.
Member Function Documentation
deserialize()
void wisheffect_state::deserialize (const JsonObject & jo)
Definition at line 4240 of file savegame_json.cpp.
{
    // Empty for now
    jo.allow_omitted_members();
}
References JsonObject::allow_omitted_members().
serialize()
void wisheffect_state::serialize (JsonOut & json) const
Definition at line 4233 of file savegame_json.cpp.
{
    // Empty for now
    json.start_object();
    json.end_object();
}
References JsonOut::end_object(), and JsonOut::start_object().
Member Data Documentation
bodypart
bodypart_str_id wisheffect_state::bodypart = bodypart_str_id::NULL_ID()
Definition at line 57 of file uistate.h.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_body_part(), and debug_menu::effect_select_callback::refresh().
duration
time_duration wisheffect_state::duration = 0_seconds
Definition at line 58 of file uistate.h.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration(), and debug_menu::effect_select_callback::refresh().
force
bool wisheffect_state::force = false
Definition at line 60 of file uistate.h.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), debug_menu::effect_select_callback::refresh(), and debug_menu::anonymous_namespace{wisheffect.cpp}::toggle_effect_force().
intensity
int wisheffect_state::intensity = -1
Definition at line 59 of file uistate.h.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), and debug_menu::effect_select_callback::refresh().
last_type_selected_index
int wisheffect_state::last_type_selected_index = 0
Definition at line 56 of file uistate.h.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu().
The documentation for this struct was generated from the following files:
src/uistate.h
src/savegame_json.cpp