Cataclysm BN: cata_ifstream Struct Reference
cata_ifstream Struct Reference
Wrapper around std::ifstream that provides cross-platform support for UTF-8 paths.
#include <fstream_utils.h>
Public Member Functions
cata_ifstream ()
cata_ifstream (const cata_ifstream &)=delete
cata_ifstream (cata_ifstream &&x)
~cata_ifstream ()
cata_ifstream & operator= (const cata_ifstream &)=delete
cata_ifstream & operator= (cata_ifstream &&)
cata_ifstream & mode (cata_ios_mode m)
cata_ifstream & open (const std::string &path)
bool is_open ()
bool fail ()
bool bad ()
void close ()
std::istream & operator* ()
std::istream * operator-> ()
Private Attributes
cata_ios_mode _mode = cata_ios_mode::none
std::unique_ptr< std::ifstream > _stream
Detailed Description
Wrapper around std::ifstream that provides cross-platform support for UTF-8 paths.
Definition at line 68 of file fstream_utils.h.
Constructor & Destructor Documentation
cata_ifstream() [1/3]
cata_ifstream::cata_ifstream () default
cata_ifstream() [2/3]
cata_ifstream::cata_ifstream (const cata_ifstream &) delete
cata_ifstream() [3/3]
cata_ifstream::cata_ifstream (cata_ifstream && x)
Definition at line 423 of file cata_utility.cpp.
{
    *this = std::move( x );
}
References avatar_action::move().
~cata_ifstream()
cata_ifstream::~cata_ifstream ()
Definition at line 428 of file cata_utility.cpp.
{
    close();
}
References close().
Member Function Documentation
bad()
bool cata_ifstream::bad ()
Definition at line 438 of file cata_utility.cpp.
{
    return !_stream || _stream->bad();
}
References _stream.
Referenced by read_from_file().
close()
void cata_ifstream::close ()
Definition at line 411 of file cata_utility.cpp.
{
    if( _stream ) {
        _stream->close();
        _stream.reset();
    }
}
References _stream.
Referenced by ~cata_ifstream().
fail()
bool cata_ifstream::fail ()
Definition at line 433 of file cata_utility.cpp.
{
    return !_stream || _stream->fail();
}
References _stream.
Referenced by copy_file(), and read_entire_file().
is_open()
bool cata_ifstream::is_open ()
Definition at line 406 of file cata_utility.cpp.
{
    return _stream && _stream->is_open();
}
References _stream.
Referenced by copy_file(), read_entire_file(), and read_from_file().
mode()
cata_ifstream & cata_ifstream::mode (cata_ios_mode m) inline
Definition at line 77 of file fstream_utils.h.
{
            _mode = m;
            return *this;
        }
References _mode.
Referenced by open(), and read_entire_file().
open()
cata_ifstream & cata_ifstream::open (const std::string & path)
Definition at line 394 of file cata_utility.cpp.
{
    std::ios_base::openmode mode = cata_ios_mode_to_std( std::ios_base::in, _mode );
#if defined (_MSC_VER)
    _stream = std::make_unique<std::ifstream>( utf8_to_wstr( path ), mode );
#else
    _stream = std::make_unique<std::ifstream>( path, mode );
#endif
    return *this;
}
References _mode, _stream, cata_ios_mode_to_std(), mode(), and utf8_to_wstr().
Referenced by read_entire_file().
operator*()
std::istream & cata_ifstream::operator* ()
Definition at line 443 of file cata_utility.cpp.
{
    return *_stream;
}
References _stream.
operator->()
std::istream * cata_ifstream::operator-> ()
Definition at line 448 of file cata_utility.cpp.
{
    return &*_stream;
}
References _stream.
operator=() [1/2]
cata_ifstream & cata_ifstream::operator= (cata_ifstream && x)
Definition at line 387 of file cata_utility.cpp.
{
    _stream = std::move( x._stream );
    _mode = x._mode;
    return *this;
}
References _mode, _stream, and avatar_action::move().
operator=() [2/2]
cata_ifstream & cata_ifstream::operator= (const cata_ifstream &) delete
Member Data Documentation
_mode
cata_ios_mode cata_ifstream::_mode = cata_ios_mode::none private
Definition at line 91 of file fstream_utils.h.
Referenced by mode(), open(), and operator=().
_stream
std::unique_ptr<std::ifstream> cata_ifstream::_stream private
Definition at line 97 of file fstream_utils.h.
Referenced by bad(), close(), fail(), is_open(), open(), operator*(), operator->(), and operator=().
The documentation for this struct was generated from the following files:
src/fstream_utils.h
src/cata_utility.cpp