Cataclysm BN: maptile Struct Reference
maptile Struct Reference
A wrapper for a submap point.
#include <submap.h>
Public Member Functions
trap_id get_trap () const
furn_id get_furn () const
ter_id get_ter () const
const trap & get_trap_t () const
const furn_t & get_furn_t () const
const ter_t & get_ter_t () const
const field & get_field () const
field_entry * find_field (const field_type_id &field_to_find)
int get_radiation () const
bool has_graffiti () const
const std::string & get_graffiti () const
bool has_signage () const
std::string get_signage () const
size_t get_item_count () const
const item & get_uppermost_item () const
Private Member Functions
const point & pos () const
maptile (submap *sub, const point &p)
Private Attributes
friend map
friend submap
submap *const sm
point pos_
Detailed Description
A wrapper for a submap point.
Allows getting multiple map features (terrain, furniture etc.) without directly accessing submaps or doing multiple bounds checks and submap gets.
Definition at line 238 of file submap.h.
Constructor & Destructor Documentation
maptile()
maptile::maptile (submap * sub, const point & p) inline private
Definition at line 249 of file submap.h.
                                               :
            sm( sub ), pos_( p ) { }
Member Function Documentation
find_field()
field_entry * maptile::find_field (const field_type_id & field_to_find) inline
Definition at line 279 of file submap.h.
{
            return sm->get_field( pos() ).find_field( field_to_find );
        }
References field::find_field(), submap::get_field(), pos(), and sm.
Referenced by map::gas_spread_to(), maptile_field_intensity(), and map::process_fields_in_submap().
get_field()
const field & maptile::get_field () const inline
Definition at line 275 of file submap.h.
{
            return sm->get_field( pos() );
        }
References submap::get_field(), pos(), and sm.
Referenced by map::draw_maptile(), map::gas_can_spread_to(), and map::update_pathfinding_cache().
get_furn()
furn_id maptile::get_furn () const inline
Definition at line 256 of file submap.h.
{
            return sm->get_furn( pos() );
        }
References submap::get_furn(), pos(), and sm.
Referenced by character_funcs::base_comfort_value(), and map::supports_above().
get_furn_t()
const furn_t & maptile::get_furn_t () const inline
Definition at line 268 of file submap.h.
{
            return sm->get_furn( pos() ).obj();
        }
References submap::get_furn(), int_id< T >::obj(), pos(), and sm.
Referenced by map::draw_from_above(), map::draw_maptile(), map::gas_can_spread_to(), map::process_fields_in_submap(), map::route(), and map::update_pathfinding_cache().
get_graffiti()
const std::string & maptile::get_graffiti () const inline
Definition at line 291 of file submap.h.
{
            return sm->get_graffiti( pos() );
        }
References submap::get_graffiti(), pos(), and sm.
get_item_count()
size_t maptile::get_item_count () const inline
Definition at line 304 of file submap.h.
{
            return sm->get_items( pos() ).size();
        }
References submap::get_items(), pos(), and sm.
Referenced by editmap::draw_main_ui_overlay(), map::draw_maptile(), and map::process_fields_in_submap().
get_radiation()
int maptile::get_radiation () const inline
Definition at line 283 of file submap.h.
{
            return sm->get_radiation( pos() );
        }
References submap::get_radiation(), pos(), and sm.
get_signage()
std::string maptile::get_signage () const inline
Definition at line 299 of file submap.h.
{
            return sm->get_signage( pos() );
        }
References submap::get_signage(), pos(), and sm.
get_ter()
ter_id maptile::get_ter () const inline
Definition at line 260 of file submap.h.
{
            return sm->get_ter( pos() );
        }
References submap::get_ter(), pos(), and sm.
Referenced by character_funcs::base_comfort_value(), get_heat_radiation(), and map::process_fields_in_submap().
get_ter_t()
const ter_t & maptile::get_ter_t () const inline
Definition at line 271 of file submap.h.
{
            return sm->get_ter( pos() ).obj();
        }
References submap::get_ter(), int_id< T >::obj(), pos(), and sm.
Referenced by map::draw_from_above(), map::draw_maptile(), map::gas_can_spread_to(), map::process_fields_in_submap(), map::route(), map::supports_above(), and map::update_pathfinding_cache().
get_trap()
trap_id maptile::get_trap () const inline
Definition at line 252 of file submap.h.
{
            return sm->get_trap( pos() );
        }
References submap::get_trap(), pos(), and sm.
Referenced by map::draw_maptile().
get_trap_t()
const trap & maptile::get_trap_t () const inline
Definition at line 264 of file submap.h.
{
            return sm->get_trap( pos() ).obj();
        }
References submap::get_trap(), int_id< T >::obj(), pos(), and sm.
Referenced by character_funcs::base_comfort_value(), map::route(), and map::update_pathfinding_cache().
get_uppermost_item()
const item & maptile::get_uppermost_item () const inline
Definition at line 309 of file submap.h.
{
            return *std::prev( sm->get_items( pos() ).cend() );
        }
References submap::get_items(), pos(), and sm.
Referenced by editmap::draw_main_ui_overlay(), and map::draw_maptile().
has_graffiti()
bool maptile::has_graffiti () const inline
Definition at line 287 of file submap.h.
{
            return sm->has_graffiti( pos() );
        }
References submap::has_graffiti(), pos(), and sm.
Referenced by map::draw_maptile().
has_signage()
bool maptile::has_signage () const inline
Definition at line 295 of file submap.h.
{
            return sm->has_signage( pos() );
        }
References submap::has_signage(), pos(), and sm.
pos()
const point & maptile::pos () const inline private
Definition at line 245 of file submap.h.
{
            return pos_;
        }
References pos_.
Referenced by find_field(), get_field(), get_furn(), get_furn_t(), get_graffiti(), get_item_count(), get_radiation(), get_signage(), get_ter(), get_ter_t(), get_trap(), get_trap_t(), get_uppermost_item(), has_graffiti(), and has_signage().
Member Data Documentation
map
friend maptile::map private
Definition at line 240 of file submap.h.
pos_
point maptile::pos_ private
Definition at line 243 of file submap.h.
Referenced by pos(), map::process_fields_in_submap(), and map::spread_gas().
sm
submap* const maptile::sm private
Definition at line 242 of file submap.h.
Referenced by find_field(), get_field(), get_furn(), get_furn_t(), get_graffiti(), get_item_count(), get_radiation(), get_signage(), get_ter(), get_ter_t(), get_trap(), get_trap_t(), get_uppermost_item(), has_graffiti(), and has_signage().
submap
friend maptile::submap private
Definition at line 241 of file submap.h.
The documentation for this struct was generated from the following file:
src/submap.h