Cataclysm BN: anonymous_namespace{messages.cpp}::game_message Struct Reference
anonymous_namespace{messages.cpp}::game_message Struct Reference
Public Member Functions
game_message ()=default
game_message (std::string &&msg, game_message_type const t)
const time_point & turn () const
std::string get_with_count () const
bool is_in_cooldown () const
Get whether or not a message should not be displayed (hidden) in the side bar because it's in a cooldown period.
bool is_new (const time_point &current) const
bool is_recent (const time_point &current) const
nc_color get_color (const time_point &current) const
void deserialize (JsonIn &jsin) override
void serialize (JsonOut &jsout) const override
Public Member Functions inherited from JsonDeserializer
virtual ~JsonDeserializer ()=default
JsonDeserializer ()=default
JsonDeserializer (JsonDeserializer &&)=default
JsonDeserializer (const JsonDeserializer &)=default
JsonDeserializer & operator= (JsonDeserializer &&)=default
JsonDeserializer & operator= (const JsonDeserializer &)=default
Public Member Functions inherited from JsonSerializer
virtual ~JsonSerializer ()=default
JsonSerializer ()=default
JsonSerializer (JsonSerializer &&)=default
JsonSerializer (const JsonSerializer &)=default
JsonSerializer & operator= (JsonSerializer &&)=default
JsonSerializer & operator= (const JsonSerializer &)=default
Public Attributes
std::string message
time_point timestamp_in_turns = calendar::start_of_cataclysm
int timestamp_in_user_actions = 0
int count = 1
unsigned cooldown_seen = 1
bool cooldown_hidden = false
game_message_type type = m_neutral
Detailed Description
Definition at line 34 of file messages.cpp.
Constructor & Destructor Documentation
game_message() [1/2]
anonymous_namespace{messages.cpp}::game_message::game_message () default
game_message() [2/2]
anonymous_namespace{messages.cpp}::game_message::game_message (std::string && msg, game_message_type const t) inline
Definition at line 46 of file messages.cpp.
                                                               :
        message( std::move( msg ) ),
        timestamp_in_turns( calendar::turn ),
        timestamp_in_user_actions( g->get_user_action_counter() ),
        type( t ) {
    }
Member Function Documentation
deserialize()
void anonymous_namespace{messages.cpp}::game_message::deserialize (JsonIn & jsin) inline override virtual
Implements JsonDeserializer.
Definition at line 94 of file messages.cpp.
{
        JsonObject obj = jsin.get_object();
        obj.read( "turn", timestamp_in_turns );
        message = obj.get_string( "message" );
        count = obj.get_int( "count" );
        type = static_cast<game_message_type>( obj.get_int( "type" ) );
    }
References detail::count(), JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), mapgen_defer::message, JsonObject::read(), and type.
get_color()
nc_color anonymous_namespace{messages.cpp}::game_message::get_color (const time_point & current) const inline
Definition at line 80 of file messages.cpp.
{
        if( is_new( current ) ) {
            // color for new messages
            return msgtype_to_color( type, false );
        } else if( is_recent( current ) ) {
            // color for slightly old messages
            return msgtype_to_color( type, true );
        }
        // color for old messages
        return c_dark_gray;
    }
References c_dark_gray, msgtype_to_color(), and type.
get_with_count()
std::string anonymous_namespace{messages.cpp}::game_message::get_with_count () const inline
Definition at line 57 of file messages.cpp.
{
        if( count <= 1 ) {
            return message;
        }
        //~ Message %s on the message log was repeated %d times, e.g. "You hear a whack! x 12"
        return string_format( _( "%s x %d" ), message, count );
    }
References _, detail::count(), mapgen_defer::message, and string_format().
Referenced by anonymous_namespace{messages.cpp}::messages_impl::recent_messages().
is_in_cooldown()
bool anonymous_namespace{messages.cpp}::game_message::is_in_cooldown () const inline
Get whether or not a message should not be displayed (hidden) in the side bar because it's in a cooldown period.
Returns
true if the message should not be displayed, false otherwise.
Definition at line 68 of file messages.cpp.
{
        return cooldown_hidden;
    }
is_new()
bool anonymous_namespace{messages.cpp}::game_message::is_new (const time_point & current) const inline
Definition at line 72 of file messages.cpp.
{
        return turn() >= current;
    }
References calendar::turn.
is_recent()
bool anonymous_namespace{messages.cpp}::game_message::is_recent (const time_point & current) const inline
Definition at line 76 of file messages.cpp.
{
        return turn() + 5_turns >= current;
    }
References calendar::turn.
serialize()
void anonymous_namespace{messages.cpp}::game_message::serialize (JsonOut & jsout) const inline override virtual
Implements JsonSerializer.
Definition at line 102 of file messages.cpp.
{
        jsout.start_object();
        jsout.member( "turn", timestamp_in_turns );
        jsout.member( "message", message );
        jsout.member( "count", count );
        jsout.member( "type", static_cast<int>( type ) );
        jsout.end_object();
    }
References detail::count(), JsonOut::end_object(), JsonOut::member(), mapgen_defer::message, JsonOut::start_object(), and type.
turn()
const time_point & anonymous_namespace{messages.cpp}::game_message::turn () const inline
Definition at line 53 of file messages.cpp.
{
        return timestamp_in_turns;
    }
Member Data Documentation
cooldown_hidden
bool anonymous_namespace{messages.cpp}::game_message::cooldown_hidden = false
Definition at line 42 of file messages.cpp.
cooldown_seen
unsigned anonymous_namespace{messages.cpp}::game_message::cooldown_seen = 1
Definition at line 40 of file messages.cpp.
count
int anonymous_namespace{messages.cpp}::game_message::count = 1
Definition at line 38 of file messages.cpp.
message
std::string anonymous_namespace{messages.cpp}::game_message::message
Definition at line 35 of file messages.cpp.
Referenced by anonymous_namespace{messages.cpp}::messages_impl::coalesce_messages().
timestamp_in_turns
time_point anonymous_namespace{messages.cpp}::game_message::timestamp_in_turns = calendar::start_of_cataclysm
Definition at line 36 of file messages.cpp.
Referenced by anonymous_namespace{messages.cpp}::messages_impl::recent_messages().
timestamp_in_user_actions
int anonymous_namespace{messages.cpp}::game_message::timestamp_in_user_actions = 0
Definition at line 37 of file messages.cpp.
type
game_message_type anonymous_namespace{messages.cpp}::game_message::type = m_neutral
Definition at line 43 of file messages.cpp.
Referenced by anonymous_namespace{messages.cpp}::messages_impl::coalesce_messages().
The documentation for this struct was generated from the following file:
src/messages.cpp