Cataclysm BN: projectile Struct Reference
projectile Struct Reference
#include <projectile.h>
Public Member Functions
const item & get_drop () const
Returns an item that should be dropped or an item for which is_null() is true when item to drop is unset.
void set_drop (const item &it)
Copies item it as a drop for this projectile.
void set_drop (item &&it)
void unset_drop ()
const explosion_data & get_custom_explosion () const
void set_custom_explosion (const explosion_data &ex)
void unset_custom_explosion ()
const std::set< ammo_effect_str_id > & get_ammo_effects ()
projectile ()
projectile (const projectile &)
projectile (projectile &&)
projectile & operator= (const projectile &)
~projectile ()
void deserialize (JsonIn &jsin)
void load (JsonObject &jo)
bool has_effect (const ammo_effect_str_id &id) const
void add_effect (const ammo_effect_str_id &id)
Public Attributes
damage_instance impact
int speed = 0
int range = 0
Private Attributes
std::unique_ptr< item > drop
std::unique_ptr< explosion_data > custom_explosion
std::set< ammo_effect_str_id > proj_effects
Detailed Description
Definition at line 20 of file projectile.h.
Constructor & Destructor Documentation
projectile() [1/3]
projectile::projectile ()
Definition at line 18 of file projectile.cpp.
                       :
    drop( nullptr ), custom_explosion( nullptr )
{ }
projectile() [2/3]
projectile::projectile (const projectile & other)
Definition at line 26 of file projectile.cpp.
{
    *this = other;
}
References other.
projectile() [3/3]
projectile::projectile (projectile &&) default
~projectile()
projectile::~projectile () default
Member Function Documentation
add_effect()
void projectile::add_effect (const ammo_effect_str_id & id) inline
Definition at line 58 of file projectile.h.
{
            proj_effects.insert( id );
        }
References proj_effects.
Referenced by mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), Character::activate_bionic(), damage_targets(), player::fire_gun(), make_gun_projectile(), explosion_handler::shrapnel(), mattack::spit_sap(), sting_shoot(), and player::throw_item().
deserialize()
void projectile::deserialize (JsonIn & jsin)
Definition at line 96 of file projectile.cpp.
{
    JsonObject jo = jsin.get_object();
    load( jo );
}
References JsonIn::get_object(), and load().
get_ammo_effects()
const std::set< ammo_effect_str_id > & projectile::get_ammo_effects () inline
Definition at line 42 of file projectile.h.
{
            return proj_effects;
        }
References proj_effects.
Referenced by projectile_attack(), and map::shoot().
get_custom_explosion()
const explosion_data & projectile::get_custom_explosion () const
Definition at line 76 of file projectile.cpp.
{
    if( custom_explosion != nullptr ) {
        return *custom_explosion;
    }
    static const explosion_data null_explosion{};
    return null_explosion;
}
References custom_explosion.
Referenced by projectile_attack().
get_drop()
const item & projectile::get_drop () const
Returns an item that should be dropped or an item for which is_null() is true when item to drop is unset.
Definition at line 43 of file projectile.cpp.
{
    if( drop != nullptr ) {
        return *drop;
    }
    static const item null_drop;
    return null_drop;
}
References drop.
has_effect()
bool projectile::has_effect (const ammo_effect_str_id & id) const inline
Definition at line 55 of file projectile.h.
{
            return proj_effects.count( id ) > 0;
        }
References proj_effects.
Referenced by Creature::deal_projectile_attack(), projectile_attack(), and map::shoot().
load()
void projectile::load (JsonObject & jo)
Definition at line 102 of file projectile.cpp.
{
    jo.read( "impact", impact );
    range = jo.get_int( "range" );
    speed = jo.get_int( "speed", 1000 );
    jo.read( "proj_effects", proj_effects );
}
References JsonObject::get_int(), impact, proj_effects, range, JsonObject::read(), and speed.
Referenced by deserialize().
operator=()
projectile & projectile::operator= (const projectile & other)
Definition at line 31 of file projectile.cpp.
{
    impact = other.impact;
    speed = other.speed;
    range = other.range;
    proj_effects = other.proj_effects;
    set_drop( other.get_drop() );
    set_custom_explosion( other.get_custom_explosion() );
    return *this;
}
References impact, other, proj_effects, range, set_custom_explosion(), set_drop(), and speed.
set_custom_explosion()
void projectile::set_custom_explosion (const explosion_data & ex)
Definition at line 86 of file projectile.cpp.
{
    custom_explosion = std::make_unique<explosion_data>( ex );
}
References custom_explosion.
Referenced by make_gun_projectile(), operator=(), and player::throw_item().
set_drop() [1/2]
void projectile::set_drop (const item & it)
Copies item it as a drop for this projectile.
Definition at line 53 of file projectile.cpp.
{
    if( it.is_null() ) {
        unset_drop();
    } else {
        drop = std::make_unique<item>( it );
    }
}
References drop, item::is_null(), and unset_drop().
Referenced by make_gun_projectile(), operator=(), and player::throw_item().
set_drop() [2/2]
void projectile::set_drop (item && it)
Definition at line 62 of file projectile.cpp.
{
    if( it.is_null() ) {
        unset_drop();
    } else {
        drop = std::make_unique<item>( std::move( it ) );
    }
}
References drop, avatar_action::move(), and unset_drop().
unset_custom_explosion()
void projectile::unset_custom_explosion ()
Definition at line 91 of file projectile.cpp.
{
    custom_explosion.reset();
}
References custom_explosion.
unset_drop()
void projectile::unset_drop ()
Definition at line 71 of file projectile.cpp.
{
    drop.reset( nullptr );
}
References drop.
Referenced by set_drop().
Member Data Documentation
custom_explosion
std::unique_ptr<explosion_data> projectile::custom_explosion private
Definition at line 66 of file projectile.h.
Referenced by get_custom_explosion(), set_custom_explosion(), and unset_custom_explosion().
drop
std::unique_ptr<item> projectile::drop private
Definition at line 65 of file projectile.h.
Referenced by get_drop(), set_drop(), and unset_drop().
impact
damage_instance projectile::impact
Definition at line 21 of file projectile.h.
Referenced by mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), Character::activate_bionic(), damage_targets(), ranged::execute_shaped_attack(), player::fire_gun(), get_basic_explosion_data(), load(), make_gun_projectile(), operator=(), projectile_attack(), target_ui::set_cursor_pos(), map::shoot(), explosion_handler::shrapnel(), explosion_handler::shrapnel_from_legacy(), mattack::spit_sap(), sting_shoot(), and player::throw_item().
proj_effects
std::set<ammo_effect_str_id> projectile::proj_effects private
Definition at line 67 of file projectile.h.
Referenced by add_effect(), get_ammo_effects(), has_effect(), load(), and operator=().
range
int projectile::range = 0
Definition at line 26 of file projectile.h.
Referenced by mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), Character::activate_bionic(), get_basic_explosion_data(), load(), make_gun_projectile(), operator=(), projectile_attack(), explosion_handler::shrapnel(), explosion_handler::shrapnel_from_legacy(), mattack::spit_sap(), sting_shoot(), and player::throw_item().
speed
int projectile::speed = 0
Definition at line 25 of file projectile.h.
Referenced by mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), Character::activate_bionic(), damage_targets(), get_basic_explosion_data(), load(), make_gun_projectile(), operator=(), projectile_attack(), explosion_handler::shrapnel_from_legacy(), mattack::spit_sap(), sting_shoot(), and player::throw_item().
The documentation for this struct was generated from the following files:
src/projectile.h
src/projectile.cpp