Cataclysm BN: four_quadrants Struct Reference
four_quadrants Struct Reference
#include <shadowcasting.h>
Public Member Functions
four_quadrants ()=default
constexpr four_quadrants (float v)
float & operator[] (quadrant q)
float operator[] (quadrant q) const
void fill (float v)
float max () const
std::string to_string () const
Public Attributes
std::array< float, 4 > values
Friends
four_quadrants operator* (const four_quadrants &l, const four_quadrants &r)
four_quadrants elementwise_max (const four_quadrants &l, const four_quadrants &r)
four_quadrants elementwise_max (const four_quadrants &l, const float r)
Detailed Description
Definition at line 27 of file shadowcasting.h.
Constructor & Destructor Documentation
four_quadrants() [1/2]
four_quadrants::four_quadrants () default
four_quadrants() [2/2]
constexpr four_quadrants::four_quadrants (float v) inline explicit constexpr
Definition at line 29 of file shadowcasting.h.
: values{{v, v, v, v}} {}
Member Function Documentation
fill()
void four_quadrants::fill (float v) inline
Definition at line 39 of file shadowcasting.h.
{
        values[0] = v;
        values[1] = v;
        values[2] = v;
        values[3] = v;
    }
max()
float four_quadrants::max () const inline
Definition at line 45 of file shadowcasting.h.
                      {
        return *std::max_element( values.begin(), values.end() );
    }
Referenced by map::ambient_light_at(), map::apparent_light_helper(), and map::update_visibility_cache().
operator[]() [1/2]
float & four_quadrants::operator[] (quadrant q) inline
Definition at line 33 of file shadowcasting.h.
{
        return values[static_cast<int>( q )];
    }
operator[]() [2/2]
float four_quadrants::operator[] (quadrant q) const inline
Definition at line 36 of file shadowcasting.h.
{
        return values[static_cast<int>( q )];
    }
to_string()
std::string four_quadrants::to_string () const
Definition at line 57 of file lightmap.cpp.
{
    return string_format( "(%.2f,%.2f,%.2f,%.2f)",
                          ( *this )[quadrant::NE], ( *this )[quadrant::SE],
                          ( *this )[quadrant::SW], ( *this )[quadrant::NW] );
}
References NE, NW, SE, string_format(), and SW.
Friends And Related Function Documentation
elementwise_max [1/2]
four_quadrants elementwise_max (const four_quadrants & l, const float r) friend
Definition at line 66 of file shadowcasting.h.
{
        four_quadrants result( l );
        for( float &v : result.values ) {
            // This looks like it should be v = std::max( v, r ) doesn't it?
            // It turns out this is one simple trick that mingw-w64 HATES,
            // triggering constant crashes when the above code was used.
            if( v < r ) {
                v = r;
            }
        }
        return result;
    }
elementwise_max [2/2]
four_quadrants elementwise_max (const four_quadrants & l, const four_quadrants & r) friend
Definition at line 57 of file shadowcasting.h.
{
        four_quadrants result;
        std::transform( l.values.begin(), l.values.end(), r.values.begin(),
        result.values.begin(), []( float l, float r ) {
            return std::max( l, r );
        } );
        return result;
    }
operator*
four_quadrants operator* (const four_quadrants & l, const four_quadrants & r) friend
Definition at line 50 of file shadowcasting.h.
{
        four_quadrants result;
        std::transform( l.values.begin(), l.values.end(), r.values.begin(),
                        result.values.begin(), std::multiplies<float>() );
        return result;
    }
Member Data Documentation
values
std::array<float, 4> four_quadrants::values
Definition at line 31 of file shadowcasting.h.
The documentation for this struct was generated from the following files:
src/shadowcasting.h
src/lightmap.cpp