Cataclysm BN: comp_selection< CompType > Struct Template Reference
comp_selection< CompType > Struct Template Reference
Struct that represents a selection of a component for crafting.
#include <craft_command.h>
Public Member Functions
comp_selection ()=default
comp_selection (usage use_from, const CompType &comp=CompType())
comp_selection (const comp_selection &)=default
comp_selection & operator= (const comp_selection &)=default
std::string nname () const
provides a translated name for 'comp', suffixed with it's location e.g '(nearby)'.
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Public Attributes
usage use_from = use_from_none
Tells us where the selected component should be used from.
CompType comp
Detailed Description
template<typename CompType>
struct comp_selection< CompType >
Struct that represents a selection of a component for crafting.
Definition at line 41 of file craft_command.h.
Constructor & Destructor Documentation
comp_selection() [1/3]
template<typename CompType > comp_selection< CompType >::comp_selection () default
comp_selection() [2/3]
template<typename CompType > comp_selection< CompType >::comp_selection (usage use_from, const CompType & comp = CompType()) inline
Definition at line 43 of file craft_command.h.
        : use_from( use_from ), comp( comp )
    {}
comp_selection() [3/3]
template<typename CompType > comp_selection< CompType >::comp_selection (const comp_selection< CompType > &) default
Member Function Documentation
deserialize()
template<typename CompType > template void comp_selection< CompType >::deserialize (JsonIn & jsin)
Definition at line 81 of file craft_command.cpp.
{
    JsonObject data = jsin.get_object();
    std::string use_from_str;
    data.read( "use_from", use_from_str );
    use_from = io::string_to_enum<usage>( use_from_str );
    data.read( "type", comp.type );
    data.read( "count", comp.count );
}
References JsonIn::get_object(), and JsonObject::read().
nname()
template<typename CompType > std::string comp_selection< CompType >::nname
provides a translated name for 'comp', suffixed with it's location e.g '(nearby)'.
Definition at line 27 of file craft_command.cpp.
{
    switch( use_from ) {
        case use_from_map:
            return item::nname( comp.type, comp.count ) + _( " (nearby)" );
        case use_from_both:
            return item::nname( comp.type, comp.count ) + _( " (person & nearby)" );
        case use_from_player:
        // Is the same as the default return;
        case use_from_none:
        case cancel:
        case num_usages:
            break;
    }
    return item::nname( comp.type, comp.count );
}
References _, cancel, item::nname(), num_usages, use_from_both, use_from_map, use_from_none, and use_from_player.
operator=()
template<typename CompType > comp_selection & comp_selection< CompType >::operator= (const comp_selection< CompType > &) default
serialize()
template<typename CompType > template void comp_selection< CompType >::serialize (JsonOut & jsout) const
Definition at line 69 of file craft_command.cpp.
{
    jsout.start_object();
    jsout.member( "use_from", io::enum_to_string( use_from ) );
    jsout.member( "type", comp.type );
    jsout.member( "count", comp.count );
    jsout.end_object();
}
References JsonOut::end_object(), io::enum_to_string(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
comp
template<typename CompType > CompType comp_selection< CompType >::comp
Definition at line 50 of file craft_command.h.
Referenced by prepared_item_consumption::consume(), player::consume_items(), player::craft_consume_tools(), and player::select_item_component().
use_from
template<typename CompType > usage comp_selection< CompType >::use_from = use_from_none
Tells us where the selected component should be used from.
Definition at line 49 of file craft_command.h.
Referenced by player::can_continue_craft(), basecamp_action_components::choose_components(), prepared_item_consumption::consume(), player::consume_items(), craft_command::execute(), and player::select_item_component().
The documentation for this struct was generated from the following files:
src/craft_command.h
src/craft_command.cpp