Cataclysm BN: Character::trait_data Struct Reference
Character::trait_data Struct Reference
#include <character.h>
Public Member Functions
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Public Attributes
bool powered = false
Whether the mutation is activated.
char key = ' '
Key to select the mutation in the UI.
int charge = 0
Time (in turns) until the mutation increase hunger/thirst/fatigue according to its cost (mutation_branch::cost).
Detailed Description
Definition at line 2033 of file character.h.
Member Function Documentation
deserialize()
void Character::trait_data::deserialize (JsonIn & jsin)
Definition at line 344 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    data.read( "key", key );
    data.read( "charge", charge );
    data.read( "powered", powered );
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and JsonObject::read().
serialize()
void Character::trait_data::serialize (JsonOut & json) const
Definition at line 335 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "key", key );
    json.member( "charge", charge );
    json.member( "powered", powered );
    json.end_object();
}
References charge, JsonOut::end_object(), key, JsonOut::member(), powered, and JsonOut::start_object().
Member Data Documentation
charge
int Character::trait_data::charge = 0
Time (in turns) until the mutation increase hunger/thirst/fatigue according to its cost (mutation_branch::cost).
When those costs have been paid, this is reset to mutation_branch::cooldown.
Definition at line 2043 of file character.h.
Referenced by Character::mutation_spend_resources(), serialize(), and Character::suffer_mutation_power().
key
char Character::trait_data::key = ' '
Key to select the mutation in the UI.
Definition at line 2037 of file character.h.
Referenced by player::power_mutations_ui(), and serialize().
powered
bool Character::trait_data::powered = false
Whether the mutation is activated.
Definition at line 2035 of file character.h.
Referenced by Character::activate_mutation(), Character::mutation_spend_resources(), player::power_mutations_ui(), serialize(), Character::suffer(), and Character::suffer_mutation_power().
The documentation for this struct was generated from the following files:
src/character.h
src/savegame_json.cpp