Cataclysm BN: talk_effect_t Struct Reference
talk_effect_t Struct Reference
Defines what happens when the trial succeeds or fails.
#include <dialogue.h>
Public Member Functions
talk_topic apply (dialogue &d) const
dialogue_consequence get_consequence (const dialogue &d) const
void set_effect (talkfunction_ptr)
Sets an effect and consequence based on function pointer.
void set_effect (const talk_effect_fun_t &)
void set_effect_consequence (const talk_effect_fun_t &fun, dialogue_consequence con)
Sets an effect to a function object and consequence to explicitly given one.
void set_effect_consequence (std::function< void(npc &p)> ptr, dialogue_consequence con)
void load_effect (const JsonObject &jo)
void parse_sub_effect (const JsonObject &jo)
void parse_string_effect (const std::string &effect_id, const JsonObject &jo)
talk_effect_t ()=default
talk_effect_t (const JsonObject &)
Public Attributes
npc_opinion opinion
How (if at all) the NPCs opinion of the player character (npc::op_of_u) will change.
npc_opinion mission_opinion
How (if at all) the NPCs opinion of the player character (npc::op_of_u) will change.
talk_topic next_topic = talk_topic("TALK_NONE")
Topic to switch to.
std::vector< talk_effect_fun_t > effects
Functions that are called when the response is chosen.
Private Attributes
dialogue_consequence guaranteed_consequence = dialogue_consequence::none
Detailed Description
Defines what happens when the trial succeeds or fails.
If trial is TALK_TRIAL_NONE it always succeeds.
Definition at line 141 of file dialogue.h.
Constructor & Destructor Documentation
talk_effect_t() [1/2]
talk_effect_t::talk_effect_t () default
talk_effect_t() [2/2]
talk_effect_t::talk_effect_t (const JsonObject & jo)
Definition at line 2515 of file npctalk.cpp.
{
    load_effect( jo );
    if( jo.has_object( "topic" ) ) {
        next_topic = load_inline_topic( jo.get_object( "topic" ) );
    } else if( jo.has_string( "topic" ) ) {
        next_topic = talk_topic( jo.get_string( "topic" ) );
    }
}
References JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), JsonObject::has_string(), load_effect(), load_inline_topic(), and next_topic.
Member Function Documentation
apply()
talk_topic talk_effect_t::apply (dialogue & d) const
Definition at line 2474 of file npctalk.cpp.
{
    // Need to get a reference to the mission before effects are applied, because effects can remove the mission
    mission *miss = d.beta->chatbin.mission_selected;
    for( const talk_effect_fun_t &effect : effects ) {
        effect( d );
    }
    d.beta->op_of_u += opinion;
    if( miss && ( mission_opinion.trust || mission_opinion.fear ||
                  mission_opinion.value || mission_opinion.anger ) ) {
        int m_value = npc_trading::cash_to_favor( *d.beta, miss->get_value() );
        npc_opinion mod = npc_opinion( mission_opinion.trust ?
                                       m_value / mission_opinion.trust : 0,
                                       mission_opinion.fear ?
                                       m_value / mission_opinion.fear : 0,
                                       mission_opinion.value ?
                                       m_value / mission_opinion.value : 0,
                                       mission_opinion.anger ?
                                       m_value / mission_opinion.anger : 0, 0 );
        d.beta->op_of_u += mod;
    }
    if( d.beta->turned_hostile() ) {
        d.beta->make_angry();
        return talk_topic( "TALK_DONE" );
    }
    // TODO: this is a hack, it should be in clear_mission or so, but those functions have
    // no access to the dialogue object.
    auto &ma = d.missions_assigned;
    ma.clear();
    // Update the missions we can talk about (must only be current, non-complete ones)
    for( auto &mission : d.beta->chatbin.missions_assigned ) {
        if( mission->get_assigned_player_id() == d.alpha->getID() ) {
            ma.push_back( mission );
        }
    }
    return next_topic;
}
References dialogue::alpha, npc_opinion::anger, dialogue::beta, npc_trading::cash_to_favor(), npc::chatbin, effects, npc_opinion::fear, mission::get_assigned_player_id(), mission::get_value(), Character::getID(), npc::make_angry(), mission_opinion, npc_chatbin::mission_selected, dialogue::missions_assigned, npc_chatbin::missions_assigned, next_topic, npc::op_of_u, opinion, npc_opinion::trust, npc::turned_hostile(), and npc_opinion::value.
get_consequence()
dialogue_consequence talk_effect_t::get_consequence (const dialogue & d) const
Definition at line 1704 of file npctalk.cpp.
{
    if( d.beta->op_of_u.anger + opinion.anger >= d.beta->hostile_anger_level() ) {
        return dialogue_consequence::hostile;
    }
    return guaranteed_consequence;
}
References npc_opinion::anger, dialogue::beta, guaranteed_consequence, hostile, npc::hostile_anger_level(), npc::op_of_u, and opinion.
Referenced by talk_response::get_consequences().
load_effect()
void talk_effect_t::load_effect (const JsonObject & jo)
Definition at line 2769 of file npctalk.cpp.
{
    if( jo.has_member( "opinion" ) ) {
        JsonIn *ji = jo.get_raw( "opinion" );
        // Same format as when saving a game (-:
        opinion.deserialize( *ji );
    }
    if( jo.has_member( "mission_opinion" ) ) {
        JsonIn *ji = jo.get_raw( "mission_opinion" );
        // Same format as when saving a game (-:
        mission_opinion.deserialize( *ji );
    }
    static const std::string member_name( "effect" );
    if( !jo.has_member( member_name ) ) {
        return;
    } else if( jo.has_string( member_name ) ) {
        const std::string type = jo.get_string( member_name );
        parse_string_effect( type, jo );
    } else if( jo.has_object( member_name ) ) {
        JsonObject sub_effect = jo.get_object( member_name );
        parse_sub_effect( sub_effect );
    } else if( jo.has_array( member_name ) ) {
        for( const JsonValue entry : jo.get_array( member_name ) ) {
            if( entry.test_string() ) {
                const std::string type = entry.get_string();
                parse_string_effect( type, jo );
            } else if( entry.test_object() ) {
                JsonObject sub_effect = entry.get_object();
                parse_sub_effect( sub_effect );
            } else {
                jo.throw_error( "invalid effect array syntax", member_name );
            }
        }
    } else {
        jo.throw_error( "invalid effect syntax", member_name );
    }
}
References npc_opinion::deserialize(), JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_raw(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), mission_opinion, opinion, parse_string_effect(), parse_sub_effect(), JsonObject::throw_error(), and type.
Referenced by mission_type::parse_funcs(), talk_effect_t(), and talk_response::talk_response().
parse_string_effect()
void talk_effect_t::parse_string_effect (const std::string & effect_id, const JsonObject & jo)
Definition at line 2659 of file npctalk.cpp.
{
    static const std::unordered_map<std::string, void( * )( npc & )> static_functions_map = {
        {
#define WRAP(function) { #function, &talk_function::function }
            WRAP( assign_mission ),
            WRAP( mission_success ),
            WRAP( mission_failure ),
            WRAP( clear_mission ),
            WRAP( mission_reward ),
            WRAP( start_trade ),
            WRAP( sort_loot ),
            WRAP( find_mount ),
            WRAP( dismount ),
            WRAP( do_chop_plank ),
            WRAP( do_vehicle_deconstruct ),
            WRAP( do_vehicle_repair ),
            WRAP( do_chop_trees ),
            WRAP( do_fishing ),
            WRAP( do_construction ),
            WRAP( do_mining ),
            WRAP( do_read ),
            WRAP( do_butcher ),
            WRAP( do_farming ),
            WRAP( assign_guard ),
            WRAP( assign_camp ),
            WRAP( abandon_camp ),
            WRAP( stop_guard ),
            WRAP( start_camp ),
            WRAP( buy_cow ),
            WRAP( buy_chicken ),
            WRAP( buy_horse ),
            WRAP( recover_camp ),
            WRAP( remove_overseer ),
            WRAP( basecamp_mission ),
            WRAP( wake_up ),
            WRAP( reveal_stats ),
            WRAP( end_conversation ),
            WRAP( insult_combat ),
            WRAP( give_equipment ),
            WRAP( give_aid ),
            WRAP( give_all_aid ),
            WRAP( barber_beard ),
            WRAP( barber_hair ),
            WRAP( buy_haircut ),
            WRAP( buy_shave ),
            WRAP( morale_chat ),
            WRAP( morale_chat_activity ),
            WRAP( buy_10_logs ),
            WRAP( buy_100_logs ),
            WRAP( bionic_install ),
            WRAP( bionic_remove ),
            WRAP( follow ),
            WRAP( follow_only ),
            WRAP( deny_follow ),
            WRAP( deny_lead ),
            WRAP( deny_equipment ),
            WRAP( deny_train ),
            WRAP( deny_personal_info ),
            WRAP( hostile ),
            WRAP( flee ),
            WRAP( leave ),
            WRAP( stop_following ),
            WRAP( revert_activity ),
            WRAP( goto_location ),
            WRAP( stranger_neutral ),
            WRAP( start_mugging ),
            WRAP( player_leaving ),
            WRAP( drop_weapon ),
            WRAP( drop_stolen_item ),
            WRAP( remove_stolen_status ),
            WRAP( player_weapon_away ),
            WRAP( player_weapon_drop ),
            WRAP( lead_to_safety ),
            WRAP( start_training ),
            WRAP( copy_npc_rules ),
            WRAP( set_npc_pickup ),
            WRAP( npc_die ),
            WRAP( npc_thankful ),
            WRAP( clear_overrides ),
            WRAP( nothing )
#undef WRAP
        }
    };
    const auto iter = static_functions_map.find( effect_id );
    if( iter != static_functions_map.end() ) {
        set_effect( iter->second );
        return;
    }
    talk_effect_fun_t subeffect_fun;
    if( effect_id == "u_bulk_trade_accept" || effect_id == "npc_bulk_trade_accept" ||
        effect_id == "u_bulk_donate" || effect_id == "npc_bulk_donate" ) {
        bool is_npc = effect_id == "npc_bulk_trade_accept" || effect_id == "npc_bulk_donate";
        bool is_trade = effect_id == "u_bulk_trade_accept" || effect_id == "npc_bulk_trade_accept";
        subeffect_fun.set_bulk_trade_accept( is_trade, is_npc );
        set_effect( subeffect_fun );
        return;
    }
    if( effect_id == "npc_gets_item" || effect_id == "npc_gets_item_to_use" ) {
        bool to_use = effect_id == "npc_gets_item_to_use";
        subeffect_fun.set_npc_gets_item( to_use );
        set_effect( subeffect_fun );
        return;
    }
    jo.throw_error( "unknown effect string", effect_id );
}
References talk_function::abandon_camp(), talk_function::assign_camp(), talk_function::assign_guard(), talk_function::assign_mission(), talk_function::barber_beard(), talk_function::barber_hair(), talk_function::basecamp_mission(), talk_function::bionic_install(), talk_function::bionic_remove(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), talk_function::buy_chicken(), talk_function::buy_cow(), talk_function::buy_haircut(), talk_function::buy_horse(), talk_function::buy_shave(), talk_function::clear_mission(), talk_function::clear_overrides(), talk_function::copy_npc_rules(), talk_function::deny_equipment(), talk_function::deny_follow(), talk_function::deny_lead(), talk_function::deny_personal_info(), talk_function::deny_train(), talk_function::dismount(), talk_function::do_butcher(), talk_function::do_chop_plank(), talk_function::do_chop_trees(), talk_function::do_construction(), talk_function::do_farming(), talk_function::do_fishing(), talk_function::do_mining(), talk_function::do_read(), talk_function::do_vehicle_deconstruct(), talk_function::do_vehicle_repair(), talk_function::drop_stolen_item(), talk_function::drop_weapon(), talk_function::end_conversation(), talk_function::find_mount(), talk_function::flee(), talk_function::follow(), talk_function::follow_only(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::give_equipment(), talk_function::goto_location(), hostile, talk_function::insult_combat(), talk_function::lead_to_safety(), talk_function::leave(), talk_function::mission_failure(), talk_function::mission_reward(), talk_function::mission_success(), talk_function::morale_chat(), talk_function::morale_chat_activity(), talk_function::nothing(), talk_function::npc_die(), talk_function::npc_thankful(), talk_function::player_leaving(), talk_function::player_weapon_away(), talk_function::player_weapon_drop(), talk_function::recover_camp(), talk_function::remove_overseer(), talk_function::remove_stolen_status(), talk_function::reveal_stats(), talk_function::revert_activity(), talk_effect_fun_t::set_bulk_trade_accept(), set_effect(), talk_effect_fun_t::set_npc_gets_item(), talk_function::set_npc_pickup(), talk_function::sort_loot(), talk_function::start_camp(), talk_function::start_mugging(), talk_function::start_trade(), talk_function::start_training(), talk_function::stop_following(), talk_function::stop_guard(), talk_function::stranger_neutral(), JsonObject::throw_error(), talk_function::wake_up(), and WRAP.
Referenced by load_effect().
parse_sub_effect()
void talk_effect_t::parse_sub_effect (const JsonObject & jo)
Definition at line 2525 of file npctalk.cpp.
{
    talk_effect_fun_t subeffect_fun;
    const bool is_npc = true;
    if( jo.has_string( "companion_mission" ) ) {
        std::string role_id = jo.get_string( "companion_mission" );
        subeffect_fun.set_companion_mission( role_id );
    } else if( jo.has_string( "u_add_effect" ) ) {
        subeffect_fun.set_add_effect( jo, "u_add_effect" );
    } else if( jo.has_string( "npc_add_effect" ) ) {
        subeffect_fun.set_add_effect( jo, "npc_add_effect", is_npc );
    } else if( jo.has_string( "u_lose_effect" ) ) {
        subeffect_fun.set_remove_effect( jo, "u_lose_effect" );
    } else if( jo.has_string( "npc_lose_effect" ) ) {
        subeffect_fun.set_remove_effect( jo, "npc_lose_effect", is_npc );
    } else if( jo.has_string( "u_add_var" ) ) {
        subeffect_fun.set_add_var( jo, "u_add_var" );
    } else if( jo.has_string( "npc_add_var" ) ) {
        subeffect_fun.set_add_var( jo, "npc_add_var", is_npc );
    } else if( jo.has_string( "u_lose_var" ) ) {
        subeffect_fun.set_remove_var( jo, "u_lose_var" );
    } else if( jo.has_string( "npc_lose_var" ) ) {
        subeffect_fun.set_remove_var( jo, "npc_lose_var", is_npc );
    } else if( jo.has_string( "u_adjust_var" ) ) {
        subeffect_fun.set_adjust_var( jo, "u_adjust_var" );
    } else if( jo.has_string( "npc_adjust_var" ) ) {
        subeffect_fun.set_adjust_var( jo, "npc_adjust_var", is_npc );
    } else if( jo.has_string( "u_add_trait" ) ) {
        subeffect_fun.set_add_trait( jo, "u_add_trait" );
    } else if( jo.has_string( "npc_add_trait" ) ) {
        subeffect_fun.set_add_trait( jo, "npc_add_trait", is_npc );
    } else if( jo.has_string( "u_lose_trait" ) ) {
        subeffect_fun.set_remove_trait( jo, "u_lose_trait" );
    } else if( jo.has_string( "npc_lose_trait" ) ) {
        subeffect_fun.set_remove_trait( jo, "npc_lose_trait", is_npc );
    } else if( jo.has_int( "u_spend_ecash" ) ) {
        int cash_change = jo.get_int( "u_spend_ecash" );
        subeffect_fun.set_u_spend_ecash( cash_change );
    } else if( jo.has_string( "u_sell_item" ) || jo.has_string( "u_buy_item" ) ||
               jo.has_string( "u_consume_item" ) || jo.has_string( "npc_consume_item" ) ||
               jo.has_string( "u_remove_item_with" ) || jo.has_string( "npc_remove_item_with" ) ) {
        int cost = 0;
        if( jo.has_int( "cost" ) ) {
            cost = jo.get_int( "cost" );
        }
        int count = 1;
        if( jo.has_int( "count" ) ) {
            count = jo.get_int( "count" );
        }
        std::string container_name;
        if( jo.has_string( "container" ) ) {
            container_name = jo.get_string( "container" );
        }
        if( jo.has_string( "u_sell_item" ) ) {
            itype_id item_name;
            jo.read( "u_sell_item", item_name, true );
            subeffect_fun.set_u_sell_item( item_name, cost, count );
        } else if( jo.has_string( "u_buy_item" ) ) {
            itype_id item_name;
            jo.read( "u_buy_item", item_name, true );
            subeffect_fun.set_u_buy_item( item_name, cost, count, container_name );
        } else if( jo.has_string( "u_consume_item" ) ) {
            subeffect_fun.set_consume_item( jo, "u_consume_item", count );
        } else if( jo.has_string( "npc_consume_item" ) ) {
            subeffect_fun.set_consume_item( jo, "npc_consume_item", count, is_npc );
        } else if( jo.has_string( "u_remove_item_with" ) ) {
            subeffect_fun.set_remove_item_with( jo, "u_remove_item_with" );
        } else if( jo.has_string( "npc_remove_item_with" ) ) {
            subeffect_fun.set_remove_item_with( jo, "npc_remove_item_with", is_npc );
        }
    } else if( jo.has_string( "npc_change_class" ) ) {
        std::string class_name = jo.get_string( "npc_change_class" );
        subeffect_fun.set_npc_change_class( class_name );
    } else if( jo.has_string( "add_mission" ) ) {
        std::string mission_id = jo.get_string( "add_mission" );
        subeffect_fun.set_add_mission( mission_id );
    } else if( jo.has_string( "npc_change_faction" ) ) {
        std::string faction_name = jo.get_string( "npc_change_faction" );
        subeffect_fun.set_npc_change_faction( faction_name );
    } else if( jo.has_int( "u_faction_rep" ) ) {
        int faction_rep = jo.get_int( "u_faction_rep" );
        subeffect_fun.set_change_faction_rep( faction_rep );
    } else if( jo.has_array( "add_debt" ) ) {
        std::vector<trial_mod> debt_modifiers;
        for( JsonArray jmod : jo.get_array( "add_debt" ) ) {
            trial_mod this_modifier;
            this_modifier.first = jmod.next_string();
            this_modifier.second = jmod.next_int();
            debt_modifiers.push_back( this_modifier );
        }
        subeffect_fun.set_add_debt( debt_modifiers );
    } else if( jo.has_string( "toggle_npc_rule" ) ) {
        const std::string rule = jo.get_string( "toggle_npc_rule" );
        subeffect_fun.set_toggle_npc_rule( rule );
    } else if( jo.has_string( "set_npc_rule" ) ) {
        const std::string rule = jo.get_string( "set_npc_rule" );
        subeffect_fun.set_set_npc_rule( rule );
    } else if( jo.has_string( "clear_npc_rule" ) ) {
        const std::string rule = jo.get_string( "clear_npc_rule" );
        subeffect_fun.set_clear_npc_rule( rule );
    } else if( jo.has_string( "set_npc_engagement_rule" ) ) {
        const std::string setting = jo.get_string( "set_npc_engagement_rule" );
        subeffect_fun.set_npc_engagement_rule( setting );
    } else if( jo.has_string( "set_npc_aim_rule" ) ) {
        const std::string setting = jo.get_string( "set_npc_aim_rule" );
        subeffect_fun.set_npc_aim_rule( setting );
    } else if( jo.has_string( "set_npc_cbm_reserve_rule" ) ) {
        const std::string setting = jo.get_string( "set_npc_cbm_reserve_rule" );
        subeffect_fun.set_npc_cbm_reserve_rule( setting );
    } else if( jo.has_string( "set_npc_cbm_recharge_rule" ) ) {
        const std::string setting = jo.get_string( "set_npc_cbm_recharge_rule" );
        subeffect_fun.set_npc_cbm_recharge_rule( setting );
    } else if( jo.has_member( "mapgen_update" ) ) {
        subeffect_fun.set_mapgen_update( jo, "mapgen_update" );
    } else if( jo.has_string( "u_buy_monster" ) ) {
        const std::string &monster_type_id = jo.get_string( "u_buy_monster" );
        const int cost = jo.get_int( "cost", 0 );
        const int count = jo.get_int( "count", 1 );
        const bool pacified = jo.get_bool( "pacified", false );
        translation name;
        jo.read( "name", name );
        subeffect_fun.set_u_buy_monster( monster_type_id, cost, count, pacified, name );
    } else if( jo.has_string( "u_learn_recipe" ) ) {
        const std::string recipe_id = jo.get_string( "u_learn_recipe" );
        subeffect_fun.set_u_learn_recipe( recipe_id );
    } else if( jo.has_string( "npc_first_topic" ) ) {
        const std::string chat_topic = jo.get_string( "npc_first_topic" );
        subeffect_fun.set_npc_first_topic( chat_topic );
    } else {
        jo.throw_error( "invalid sub effect syntax: " + jo.str() );
    }
    set_effect( subeffect_fun );
}
References detail::count(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_string(), om_direction::name(), JsonObject::read(), talk_effect_fun_t::set_add_debt(), talk_effect_fun_t::set_add_effect(), talk_effect_fun_t::set_add_mission(), talk_effect_fun_t::set_add_trait(), talk_effect_fun_t::set_add_var(), talk_effect_fun_t::set_adjust_var(), talk_effect_fun_t::set_change_faction_rep(), talk_effect_fun_t::set_clear_npc_rule(), talk_effect_fun_t::set_companion_mission(), talk_effect_fun_t::set_consume_item(), set_effect(), talk_effect_fun_t::set_mapgen_update(), talk_effect_fun_t::set_npc_aim_rule(), talk_effect_fun_t::set_npc_cbm_recharge_rule(), talk_effect_fun_t::set_npc_cbm_reserve_rule(), talk_effect_fun_t::set_npc_change_class(), talk_effect_fun_t::set_npc_change_faction(), talk_effect_fun_t::set_npc_engagement_rule(), talk_effect_fun_t::set_npc_first_topic(), talk_effect_fun_t::set_remove_effect(), talk_effect_fun_t::set_remove_item_with(), talk_effect_fun_t::set_remove_trait(), talk_effect_fun_t::set_remove_var(), talk_effect_fun_t::set_set_npc_rule(), talk_effect_fun_t::set_toggle_npc_rule(), talk_effect_fun_t::set_u_buy_item(), talk_effect_fun_t::set_u_buy_monster(), talk_effect_fun_t::set_u_learn_recipe(), talk_effect_fun_t::set_u_sell_item(), talk_effect_fun_t::set_u_spend_ecash(), JsonObject::str(), and JsonObject::throw_error().
Referenced by load_effect().
set_effect() [1/2]
void talk_effect_t::set_effect (const talk_effect_fun_t & fun)
Definition at line 2452 of file npctalk.cpp.
{
    effects.push_back( fun );
    guaranteed_consequence = std::max( guaranteed_consequence, dialogue_consequence::none );
}
References effects, guaranteed_consequence, and none.
set_effect() [2/2]
void talk_effect_t::set_effect (talkfunction_ptr ptr)
Sets an effect and consequence based on function pointer.
Definition at line 2458 of file npctalk.cpp.
{
    talk_effect_fun_t npctalk_setter( ptr );
    dialogue_consequence response;
    if( ptr == &talk_function::hostile ) {
        response = dialogue_consequence::hostile;
    } else if( ptr == &talk_function::player_weapon_drop ||
               ptr == &talk_function::player_weapon_away ||
               ptr == &talk_function::start_mugging ) {
        response = dialogue_consequence::helpless;
    } else {
        response = dialogue_consequence::none;
    }
    set_effect_consequence( npctalk_setter, response );
}
References helpless, hostile, talk_function::hostile(), none, talk_function::player_weapon_away(), talk_function::player_weapon_drop(), ptr(), set_effect_consequence(), and talk_function::start_mugging().
Referenced by parse_string_effect(), and parse_sub_effect().
set_effect_consequence() [1/2]
void talk_effect_t::set_effect_consequence (const talk_effect_fun_t & fun, dialogue_consequence con)
Sets an effect to a function object and consequence to explicitly given one.
Definition at line 2439 of file npctalk.cpp.
{
    effects.push_back( fun );
    guaranteed_consequence = std::max( guaranteed_consequence, con );
}
References effects, and guaranteed_consequence.
Referenced by set_effect(), and set_effect_consequence().
set_effect_consequence() [2/2]
void talk_effect_t::set_effect_consequence (std::function< void(npc &p)> ptr, dialogue_consequence con)
Definition at line 2445 of file npctalk.cpp.
{
    talk_effect_fun_t npctalk_setter( ptr );
    set_effect_consequence( npctalk_setter, con );
}
References ptr(), and set_effect_consequence().
Member Data Documentation
effects
std::vector<talk_effect_fun_t> talk_effect_t::effects
Functions that are called when the response is chosen.
Definition at line 181 of file dialogue.h.
Referenced by apply(), json_dynamic_line_effect::json_dynamic_line_effect(), mission_type::parse_funcs(), set_effect(), and set_effect_consequence().
guaranteed_consequence
dialogue_consequence talk_effect_t::guaranteed_consequence = dialogue_consequence::none private
Definition at line 183 of file dialogue.h.
Referenced by get_consequence(), set_effect(), and set_effect_consequence().
mission_opinion
npc_opinion talk_effect_t::mission_opinion
How (if at all) the NPCs opinion of the player character (npc::op_of_u) will change.
These values are divisors of the mission value.
Definition at line 151 of file dialogue.h.
Referenced by apply(), and load_effect().
next_topic
talk_topic talk_effect_t::next_topic = talk_topic("TALK_NONE")
Topic to switch to.
TALK_DONE ends the talking, TALK_NONE keeps the current topic.
Definition at line 155 of file dialogue.h.
Referenced by apply(), talk_response::create_option_line(), talk_effect_t(), and talk_response::talk_response().
opinion
npc_opinion talk_effect_t::opinion
How (if at all) the NPCs opinion of the player character (npc::op_of_u) will change.
Definition at line 146 of file dialogue.h.
Referenced by apply(), get_consequence(), and load_effect().
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp