Cataclysm BN: construction_sequence Struct Reference
construction_sequence Struct Reference
#include <construction_sequence.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void check () const
Public Attributes
construction_sequence_id id
bool was_loaded = false
std::vector< construction_str_id > elems
ter_str_id post_terrain
furn_str_id post_furniture
bool blacklisted = false
Detailed Description
Definition at line 12 of file construction_sequence.h.
Member Function Documentation
check()
void construction_sequence::check () const
Definition at line 30 of file construction_sequence.cpp.
{
    consistency_report report;
    for( const construction_str_id &elem : elems ) {
        if( !elem.is_valid() ) {
            report.warn( "invalid construction id \"%s\"", elem );
        }
    }
    if( !report.is_empty() ) {
        std::string s = report.format( "construction sequence", id.str() );
        debugmsg( s );
    }
}
References debugmsg, elems, consistency_report::format(), consistency_report::is_empty(), and consistency_report::warn().
load()
void construction_sequence::load (const JsonObject & jo, const std::string & src)
Definition at line 22 of file construction_sequence.cpp.
{
    mandatory( jo, was_loaded, "elems", elems );
    optional( jo, was_loaded, "post_terrain", post_terrain );
    optional( jo, was_loaded, "post_furniture", post_furniture );
    optional( jo, was_loaded, "blacklisted", blacklisted );
}
References mandatory(), and optional().
Member Data Documentation
blacklisted
bool construction_sequence::blacklisted = false
Definition at line 24 of file construction_sequence.h.
elems
std::vector<construction_str_id> construction_sequence::elems
Definition at line 19 of file construction_sequence.h.
Referenced by check(), construction_sequences::finalize(), and get_build_reqs_for_furn_ter_ids().
id
construction_sequence_id construction_sequence::id
Definition at line 16 of file construction_sequence.h.
Referenced by construction_sequences::finalize().
post_furniture
furn_str_id construction_sequence::post_furniture
Definition at line 22 of file construction_sequence.h.
post_terrain
ter_str_id construction_sequence::post_terrain
Definition at line 21 of file construction_sequence.h.
was_loaded
bool construction_sequence::was_loaded = false
Definition at line 17 of file construction_sequence.h.
Referenced by construction_sequences::finalize().
The documentation for this struct was generated from the following files:
src/construction_sequence.h
src/construction_sequence.cpp