Cataclysm BN: cata_libintl::PlfTStream Struct Reference
cata_libintl::PlfTStream Struct Reference
Public Member Functions
PlfTStream (const std::string *raw)
PlfTStream cloned () const
PlfToken peek_internal () const
PlfToken get ()
PlfToken peek () const
PlfTStream & skip ()
bool has_tokens () const
Public Attributes
const std::string * s
size_t pos
size_t end
Detailed Description
Definition at line 79 of file cata_libintl.cpp.
Constructor & Destructor Documentation
PlfTStream()
cata_libintl::PlfTStream::PlfTStream (const std::string * raw) inline
Definition at line 84 of file cata_libintl.cpp.
{
        s = raw;
        pos = 0;
        if( s ) {
            end = s->size();
        }
    }
References end, pos, and s.
Member Function Documentation
cloned()
PlfTStream cata_libintl::PlfTStream::cloned () const inline
Definition at line 92 of file cata_libintl.cpp.
{
        return *this;
    }
Referenced by cata_libintl::plf_get_expr(), cata_libintl::plf_get_value(), and cata_libintl::plf_try_binary_op().
get()
PlfToken cata_libintl::PlfTStream::get () inline
Definition at line 137 of file cata_libintl.cpp.
                   {
        PlfToken t = peek_internal();
        pos = t.start + t.len;
        return t;
    }
References cata_libintl::PlfToken::len, peek_internal(), pos, and cata_libintl::PlfToken::start.
Referenced by skip().
has_tokens()
bool cata_libintl::PlfTStream::has_tokens () const inline
Definition at line 152 of file cata_libintl.cpp.
{
        return peek().kind != PlfOp::NumOps;
    }
References cata_libintl::PlfToken::kind, cata_libintl::NumOps, and peek().
peek()
PlfToken cata_libintl::PlfTStream::peek () const inline
Definition at line 143 of file cata_libintl.cpp.
{
        return peek_internal();
    }
References peek_internal().
Referenced by has_tokens(), cata_libintl::plf_get_expr(), cata_libintl::plf_get_value(), and cata_libintl::plf_try_binary_op().
peek_internal()
PlfToken cata_libintl::PlfTStream::peek_internal () const inline
Definition at line 96 of file cata_libintl.cpp.
{
        std::string tok;
        size_t pos = this->pos;
        while( pos < end ) {
            char c = ( *s )[pos];
            if( c == ' ' || c == '\t' ) {
                // skip whitespace
                pos++;
                continue;
            } else if( c >= '0' && c <= '9' ) {
                // number
                size_t start_pos = pos;
                while( pos < end && c >= '0' && c <= '9' ) {
                    tok.push_back( c );
                    pos++;
                    c = ( *s )[pos];
                }
                try {
                    size_t ul = std::stoul( tok );
                    if( ul > std::numeric_limits<uint32_t>::max() ) {
                        throw std::out_of_range( "stoul" );
                    }
                    return PlfToken{ PlfOp::Literal, ul, start_pos, pos - start_pos };
                } catch( const std::logic_error &err ) {
                    std::string e = string_format( "invalid number '%s' at pos %d", tok, start_pos );
                    throw std::runtime_error( e );
                }
            }
            std::string ss = s->substr( pos, end - pos );
            for( const auto &t : simple_tokens ) {
                if( string_starts_with( ss, t.first ) ) {
                    return PlfToken{ t.second, 0, pos, t.first.size() };
                }
            }
            pos++;
            std::string e = string_format( "unexpected character '%c' at pos %d", c, pos - 1 );
            throw std::runtime_error( e );
        }
        return PlfToken{ PlfOp::NumOps, 0, pos, 0 };
    }
References c, end, cata_libintl::Literal, cata_libintl::NumOps, pos, s, cata_libintl::simple_tokens, string_format(), and string_starts_with().
Referenced by get(), and peek().
skip()
PlfTStream & cata_libintl::PlfTStream::skip () inline
Definition at line 147 of file cata_libintl.cpp.
                       {
        get();
        return *this;
    }
References get().
Referenced by cata_libintl::plf_get_expr(), cata_libintl::plf_get_value(), and cata_libintl::plf_try_binary_op().
Member Data Documentation
end
size_t cata_libintl::PlfTStream::end
Definition at line 82 of file cata_libintl.cpp.
Referenced by peek_internal(), and PlfTStream().
pos
size_t cata_libintl::PlfTStream::pos
Definition at line 81 of file cata_libintl.cpp.
Referenced by get(), peek_internal(), and PlfTStream().
s
const std::string* cata_libintl::PlfTStream::s
Definition at line 80 of file cata_libintl.cpp.
Referenced by peek_internal(), and PlfTStream().
The documentation for this struct was generated from the following file:
src/cata_libintl.cpp