Cataclysm BN: mm_region Struct Reference
mm_region Struct Reference
Represents a square of mm_submaps.
#include <map_memory.h>
Public Member Functions
mm_region ()
bool is_empty () const
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Public Attributes
shared_ptr_fast< mm_submap > submaps [MM_REG_SIZE][MM_REG_SIZE]
Detailed Description
Represents a square of mm_submaps.
For faster save/load, submaps are collected into regions and each region is saved in its own file.
Definition at line 91 of file map_memory.h.
Constructor & Destructor Documentation
mm_region()
mm_region::mm_region ()
Definition at line 49 of file map_memory.cpp.
: submaps {{ nullptr }} {}
Member Function Documentation
deserialize()
void mm_region::deserialize (JsonIn & jsin)
Definition at line 3295 of file savegame_json.cpp.
{
    jsin.start_array();
    // NOLINTNEXTLINE(modernize-loop-convert): leaving as is for readability
    for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
        // NOLINTNEXTLINE(modernize-loop-convert): leaving as is for readability
        for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
            shared_ptr_fast<mm_submap> &sm = submaps[x][y];
            sm = make_shared_fast<mm_submap>();
            if( jsin.test_null() ) {
                jsin.skip_null();
            } else {
                sm->deserialize( jsin );
            }
        }
    }
    jsin.end_array();
}
References JsonIn::end_array(), MM_REG_SIZE, JsonIn::skip_null(), coords::sm, JsonIn::start_array(), and JsonIn::test_null().
Referenced by map_memory::load_submap().
is_empty()
bool mm_region::is_empty () const
Definition at line 51 of file map_memory.cpp.
{
    for( const auto &itt : submaps ) {
        for( const shared_ptr_fast<mm_submap> &it : itt ) {
            if( !it->is_empty() ) {
                return false;
            }
        }
    }
    return true;
}
References submaps.
Referenced by map_memory::save().
serialize()
void mm_region::serialize (JsonOut & jsout) const
Definition at line 3277 of file savegame_json.cpp.
{
    jsout.start_array();
    // NOLINTNEXTLINE(modernize-loop-convert): leaving as is for readability
    for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
        // NOLINTNEXTLINE(modernize-loop-convert): leaving as is for readability
        for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
            const shared_ptr_fast<mm_submap> &sm = submaps[x][y];
            if( sm->is_empty() ) {
                jsout.write_null();
            } else {
                sm->serialize( jsout );
            }
        }
    }
    jsout.end_array();
}
References JsonOut::end_array(), MM_REG_SIZE, coords::sm, JsonOut::start_array(), and JsonOut::write_null().
Referenced by map_memory::save().
Member Data Documentation
submaps
shared_ptr_fast<mm_submap> mm_region::submaps[MM_REG_SIZE][MM_REG_SIZE]
Definition at line 92 of file map_memory.h.
Referenced by is_empty(), map_memory::load_submap(), and map_memory::save().
The documentation for this struct was generated from the following files:
src/map_memory.h
src/map_memory.cpp
src/savegame_json.cpp