Cataclysm BN: mission_end Struct Reference
mission_end Struct Reference
#include <mission.h>
Static Public Member Functions
static void standard (mission *)
static void deposit_box (mission *)
Detailed Description
Definition at line 127 of file mission.h.
Member Function Documentation
deposit_box()
void mission_end::deposit_box (mission * miss) static
Definition at line 14 of file mission_end.cpp.
{
    npc *p = g->find_npc( miss->get_npc_id() );
    if( p == nullptr ) {
        debugmsg( "could not find mission NPC %d", miss->get_npc_id().get_value() );
        return;
    }
    // Npc leaves your party
    p->set_attitude( NPCATT_NULL );
    std::string itemName = "deagle_44";
    if( one_in( 4 ) ) {
        itemName = "katana";
    } else if( one_in( 3 ) ) {
        itemName = "m4a1";
    }
    g->u.i_add( item( itemName, calendar::start_of_cataclysm ) );
    add_msg( m_good, _( "%s gave you an item from the deposit box." ), p->name );
}
References _, add_msg(), debugmsg, g, mission::get_npc_id(), character_id::get_value(), m_good, Character::name, NPCATT_NULL, one_in(), npc::set_attitude(), and calendar::start_of_cataclysm.
standard()
static void mission_end::standard (mission *) inline static
Definition at line 129 of file mission.h.
{}
The documentation for this struct was generated from the following files:
src/mission.h
src/mission_end.cpp