Cataclysm BN: dream Struct Reference
dream Struct Reference
#include <mutation.h>
Public Member Functions
std::vector< std::string > messages () const
dream ()
Static Public Member Functions
static void load (const JsonObject &jsobj)
Public Attributes
std::string category
int strength
Private Attributes
std::vector< std::string > raw_messages
Detailed Description
Definition at line 39 of file mutation.h.
Constructor & Destructor Documentation
dream()
dream::dream () inline
Definition at line 49 of file mutation.h.
                {
            strength = 0;
        }
References strength.
Member Function Documentation
load()
void dream::load (const JsonObject & jsobj) static
Definition at line 664 of file mutation_data.cpp.
{
    dream newdream;
    newdream.strength = jsobj.get_int( "strength" );
    newdream.category = jsobj.get_string( "category" );
    for( const std::string line : jsobj.get_array( "messages" ) ) {
        newdream.raw_messages.push_back( line );
    }
    dreams.push_back( newdream );
}
References category, dreams, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), line(), raw_messages, and strength.
Referenced by DynamicDataLoader::initialize().
messages()
std::vector< std::string > dream::messages () const
Definition at line 655 of file mutation_data.cpp.
{
    std::vector<std::string> ret;
    for( const auto &msg : raw_messages ) {
        ret.push_back( _( msg ) );
    }
    return ret;
}
References _, raw_messages, and cata::hash64_detail::ret.
Referenced by player::get_category_dream().
Member Data Documentation
category
std::string dream::category
Definition at line 46 of file mutation.h.
Referenced by load().
raw_messages
std::vector<std::string> dream::raw_messages private
Definition at line 41 of file mutation.h.
Referenced by load(), and messages().
strength
int dream::strength
Definition at line 47 of file mutation.h.
Referenced by dream(), and load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation_data.cpp