Cataclysm BN: detail::uint128_wrapper Struct Reference
detail::uint128_wrapper Struct Reference
#include <fmtlib_format.h>
Public Member Functions
uint128_wrapper ()=default
uint128_wrapper (uint64_t high, uint64_t low) FMT_NOEXCEPT
uint64_t high () const FMT_NOEXCEPT
uint64_t low () const FMT_NOEXCEPT
uint128_wrapper & operator+= (uint64_t n) FMT_NOEXCEPT
Public Attributes
uint64_t high_
uint64_t low_
Detailed Description
Definition at line 926 of file fmtlib_format.h.
Constructor & Destructor Documentation
uint128_wrapper() [1/2]
detail::uint128_wrapper::uint128_wrapper () default
References high.
uint128_wrapper() [2/2]
detail::uint128_wrapper::uint128_wrapper (uint64_t high, uint64_t low) inline
Definition at line 954 of file fmtlib_format.h.
                                                            :
    high_{high},
    low_{low} {}
References high.
Member Function Documentation
high()
uint64_t detail::uint128_wrapper::high () const inline
Definition at line 958 of file fmtlib_format.h.
{
        return high_;
    }
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power(), detail::dragonbox::umul128_upper64(), and detail::dragonbox::umul192_upper64().
low()
uint64_t detail::uint128_wrapper::low () const inline
Definition at line 961 of file fmtlib_format.h.
{
        return low_;
    }
Referenced by detail::dragonbox::cache_accessor< double >::get_cached_power().
operator+=()
uint128_wrapper & detail::uint128_wrapper::operator+= (uint64_t n) inline
Definition at line 965 of file fmtlib_format.h.
{
#  if defined(_MSC_VER) && defined(_M_X64)
        unsigned char carry = _addcarry_u64( 0, low_, n, &low_ );
        _addcarry_u64( carry, high_, 0, &high_ );
        return *this;
#  else
        uint64_t sum = low_ + n;
        high_ += ( sum < low_ ? 1 : 0 );
        low_ = sum;
        return *this;
#  endif
    }
Member Data Documentation
high_
uint64_t detail::uint128_wrapper::high_
Definition at line 951 of file fmtlib_format.h.
low_
uint64_t detail::uint128_wrapper::low_
Definition at line 952 of file fmtlib_format.h.
The documentation for this struct was generated from the following file:
src/fmtlib_format.h