Cataclysm BN: consumption_event Struct Reference
consumption_event Struct Reference
#include <consumption.h>
Public Member Functions
consumption_event ()=default
consumption_event (const item &food)
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Public Attributes
time_point time
itype_id type_id
uint64_t component_hash
Detailed Description
Definition at line 14 of file consumption.h.
Constructor & Destructor Documentation
consumption_event() [1/2]
consumption_event::consumption_event () default
consumption_event() [2/2]
consumption_event::consumption_event (const item & food)
Definition at line 1516 of file consumption.cpp.
                                                       : time( calendar::turn )
{
    type_id = food.typeId();
    component_hash = food.make_component_hash();
}
References component_hash, item::make_component_hash(), type_id, and item::typeId().
Member Function Documentation
deserialize()
void consumption_event::deserialize (JsonIn & jsin)
Definition at line 375 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    jo.read( "time", time );
    jo.read( "type_id", type_id );
    jo.read( "component_hash", component_hash );
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and JsonObject::read().
serialize()
void consumption_event::serialize (JsonOut & json) const
Definition at line 366 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "time", time );
    json.member( "type_id", type_id );
    json.member( "component_hash", component_hash );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
component_hash
uint64_t consumption_event::component_hash
Definition at line 17 of file consumption.h.
Referenced by consumption_event(), and Character::fun_for().
time
time_point consumption_event::time
Definition at line 15 of file consumption.h.
Referenced by Character::fun_for().
type_id
itype_id consumption_event::type_id
Definition at line 16 of file consumption.h.
Referenced by consumption_event(), and Character::fun_for().
The documentation for this struct was generated from the following files:
src/consumption.h
src/consumption.cpp
src/savegame_json.cpp