Cataclysm BN: formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > > Struct Template Reference
formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > > Struct Template Reference
#include <fmtlib_format.h>
Public Member Functions
FMT_CONSTEXPR formatter ()=default
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (const T &val, FormatContext &ctx) -> decltype(ctx.out())
Private Attributes
detail::dynamic_format_specs< Char > specs_
Detailed Description
template<typename T, typename Char>
struct formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >
Definition at line 3882 of file fmtlib_format.h.
Constructor & Destructor Documentation
formatter()
template<typename T , typename Char > FMT_CONSTEXPR formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::formatter () default
Member Function Documentation
format()
template<typename T , typename Char > template<typename FormatContext > auto formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::format (const T & val, FormatContext & ctx) -> decltype(ctx.out()) inline
Definition at line 3955 of file fmtlib_format.h.
{
            detail::handle_dynamic_spec<detail::width_checker>( specs_.width,
                    specs_.width_ref, ctx );
            detail::handle_dynamic_spec<detail::precision_checker>(
                specs_.precision, specs_.precision_ref, ctx );
            using af = detail::arg_formatter<typename FormatContext::iterator,
                  typename FormatContext::char_type>;
            return visit_format_arg( af( ctx, nullptr, &specs_ ),
                                     detail::make_arg<FormatContext>( val ) );
        }
References basic_format_specs< Char >::precision, visit_format_arg(), and basic_format_specs< Char >::width.
parse()
template<typename T , typename Char > template<typename ParseContext > FMT_CONSTEXPR auto formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 3890 of file fmtlib_format.h.
{
            using handler_type = detail::dynamic_specs_handler<ParseContext>;
            auto type = detail::type_constant<T, Char>::value;
            detail::specs_checker<handler_type> handler( handler_type( specs_, ctx ),
                    type );
            auto it = parse_format_specs( ctx.begin(), ctx.end(), handler );
            auto eh = ctx.error_handler();
            switch( type ) {
                case detail::type::none_type:
                    FMT_ASSERT( false, "invalid argument type" );
                    break;
                case detail::type::int_type:
                case detail::type::uint_type:
                case detail::type::long_long_type:
                case detail::type::ulong_long_type:
                case detail::type::int128_type:
                case detail::type::uint128_type:
                case detail::type::bool_type:
                    handle_int_type_spec( specs_.type,
                                          detail::int_type_checker<decltype( eh )>( eh ) );
                    break;
                case detail::type::char_type:
                    handle_char_specs(
                        &specs_, detail::char_specs_checker<decltype( eh )>( specs_.type, eh ) );
                    break;
                case detail::type::float_type:
                    if( detail::const_check( FMT_USE_FLOAT ) ) {
                        detail::parse_float_type_spec( specs_, eh );
                    } else {
                        FMT_ASSERT( false, "float support disabled" );
                    }
                    break;
                case detail::type::double_type:
                    if( detail::const_check( FMT_USE_DOUBLE ) ) {
                        detail::parse_float_type_spec( specs_, eh );
                    } else {
                        FMT_ASSERT( false, "double support disabled" );
                    }
                    break;
                case detail::type::long_double_type:
                    if( detail::const_check( FMT_USE_LONG_DOUBLE ) ) {
                        detail::parse_float_type_spec( specs_, eh );
                    } else {
                        FMT_ASSERT( false, "long double support disabled" );
                    }
                    break;
                case detail::type::cstring_type:
                    detail::handle_cstring_type_spec(
                        specs_.type, detail::cstring_type_checker<decltype( eh )>( eh ) );
                    break;
                case detail::type::string_type:
                    detail::check_string_type_spec( specs_.type, eh );
                    break;
                case detail::type::pointer_type:
                    detail::check_pointer_type_spec( specs_.type, eh );
                    break;
                case detail::type::custom_type:
                    // Custom format specifiers should be checked in parse functions of
                    // formatter specializations.
                    break;
            }
            return it;
        }
References detail::bool_type, detail::char_type, detail::check_pointer_type_spec(), detail::check_string_type_spec(), detail::const_check(), detail::cstring_type, detail::custom_type, detail::double_type, detail::float_type, FMT_ASSERT, FMT_USE_DOUBLE, FMT_USE_FLOAT, FMT_USE_LONG_DOUBLE, detail::handle_char_specs(), detail::handle_cstring_type_spec(), detail::handle_int_type_spec(), detail::int128_type, detail::int_type, detail::long_double_type, detail::long_long_type, detail::none_type, detail::parse_float_type_spec(), detail::parse_format_specs(), detail::pointer_type, detail::string_type, type, basic_format_specs< Char >::type, detail::uint128_type, detail::uint_type, and detail::ulong_long_type.
Member Data Documentation
specs_
template<typename T , typename Char > detail::dynamic_format_specs<Char> formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::specs_ private
Definition at line 3967 of file fmtlib_format.h.
The documentation for this struct was generated from the following file:
src/fmtlib_format.h