Cataclysm BN: value_constraint Struct Reference
value_constraint Struct Reference
Public Member Functions
bool permits (const cata_variant &v, stats_tracker &stats) const
void deserialize (JsonIn &jsin)
void check (const std::string &name, const cata_variant_type input_type) const
bool is_constant () const
Public Attributes
cata::optional< cata_variant > equals_
cata::optional< std::string > equals_string_
cata::optional< string_id< event_statistic > > equals_statistic_
Detailed Description
Definition at line 167 of file event_statistics.cpp.
Member Function Documentation
check()
void value_constraint::check (const std::string & name, const cata_variant_type input_type) const inline
Definition at line 212 of file event_statistics.cpp.
{
        if( equals_statistic_ ) {
            if( !equals_statistic_->is_valid() ) {
                debugmsg( "constraint for event_transformation %s refers to invalid statistic %s",
                          name, equals_statistic_->str() );
                return;
            }
            cata_variant_type stat_type = ( *equals_statistic_ )->type();
            if( stat_type != input_type ) {
                debugmsg( "constraint for event_transformation %s matches statistic %s of "
                          "different type.  Statistic has type %s but value compared with it has "
                          "type %s",
                          name, equals_statistic_->str(), io::enum_to_string( stat_type ),
                          io::enum_to_string( input_type ) );
            }
        }
        if( equals_ ) {
            if( input_type != equals_->type() ) {
                debugmsg( "constraint for event_transformation %s matches constant of type %s but "
                          "value compared with it has type %s",
                          name, io::enum_to_string( equals_->type() ),
                          io::enum_to_string( input_type ) );
            }
        }
    }
References debugmsg, io::enum_to_string(), equals_, equals_statistic_, and om_direction::name().
deserialize()
void value_constraint::deserialize (JsonIn & jsin) inline
Definition at line 185 of file event_statistics.cpp.
{
        JsonObject jo = jsin.get_object();
        int equals_int;
        if( jo.read( "equals", equals_int, false ) ) {
            equals_ = cata_variant::make<cata_variant_type::int_>( equals_int );
        }
        bool equals_bool;
        if( jo.read( "equals", equals_bool, false ) ) {
            equals_ = cata_variant::make<cata_variant_type::bool_>( equals_bool );
        }
        std::string equals_string;
        if( jo.read( "equals", equals_string, false ) ) {
            equals_string_ = equals_string;
        }
        string_id<event_statistic> stat;
        if( jo.read( "equals_statistic", stat ) ) {
            equals_statistic_ = stat;
        }
        if( !equals_ && !equals_string_ && !equals_statistic_ ) {
            jo.throw_error( "No valid value constraint found" );
        }
    }
References equals_, equals_statistic_, equals_string_, JsonIn::get_object(), JsonObject::read(), and JsonObject::throw_error().
is_constant()
bool value_constraint::is_constant () const inline
Definition at line 240 of file event_statistics.cpp.
{
        return !equals_statistic_ ||
               ( *equals_statistic_ )->monotonicity() == monotonically::constant;
    }
References constant, and equals_statistic_.
permits()
bool value_constraint::permits (const cata_variant & v, stats_tracker & stats) const inline
Definition at line 172 of file event_statistics.cpp.
{
        if( equals_ && *equals_ != v ) {
            return false;
        }
        if( equals_string_ && *equals_string_ != v.get_string() ) {
            return false;
        }
        if( equals_statistic_ && stats.value_of( *equals_statistic_ ) != v ) {
            return false;
        }
        return true;
    }
References equals_, equals_statistic_, equals_string_, and cata_variant::get_string().
Referenced by event_transformation_impl::match_and_transform().
Member Data Documentation
equals_
cata::optional<cata_variant> value_constraint::equals_
Definition at line 168 of file event_statistics.cpp.
Referenced by check(), deserialize(), and permits().
equals_statistic_
cata::optional<string_id<event_statistic> > value_constraint::equals_statistic_
Definition at line 170 of file event_statistics.cpp.
Referenced by check(), deserialize(), is_constant(), and permits().
equals_string_
cata::optional<std::string> value_constraint::equals_string_
Definition at line 169 of file event_statistics.cpp.
Referenced by deserialize(), and permits().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp