Cataclysm BN: detail::int_writer< OutputIt, Char, UInt > Struct Template Reference
detail::int_writer< OutputIt, Char, UInt > Struct Template Reference
#include <fmtlib_format.h>
Public Types
enum { sep_size = 1 }
using iterator = remove_reference_t< decltype(reserve(std::declval< OutputIt & >(), 0))>
Public Member Functions
string_view get_prefix () const
template<typename Int >
int_writer (OutputIt output, locale_ref loc, Int value, const basic_format_specs< Char > &s)
void on_dec ()
void on_hex ()
void on_bin ()
void on_oct ()
void on_num ()
void on_chr ()
FMT_NORETURN void on_error ()
Public Attributes
OutputIt out
locale_ref locale
const basic_format_specs< Char > & specs
UInt abs_value
char prefix [4]
unsigned prefix_size
Detailed Description
template<typename OutputIt, typename Char, typename UInt>
struct detail::int_writer< OutputIt, Char, UInt >
Definition at line 1809 of file fmtlib_format.h.
Member Typedef Documentation
iterator
template<typename OutputIt , typename Char , typename UInt > using detail::int_writer< OutputIt, Char, UInt >::iterator = remove_reference_t<decltype(reserve(std::declval<OutputIt &>(), 0))>
Definition at line 1818 of file fmtlib_format.h.
Member Enumeration Documentation
anonymous enum
template<typename OutputIt , typename Char , typename UInt > anonymous enum
Enumerator
sep_size
Definition at line 1891 of file fmtlib_format.h.
{ sep_size = 1 };
Constructor & Destructor Documentation
int_writer()
template<typename OutputIt , typename Char , typename UInt > template<typename Int > detail::int_writer< OutputIt, Char, UInt >::int_writer (OutputIt output, locale_ref loc, Int value, const basic_format_specs< Char > & s) inline
Definition at line 1826 of file fmtlib_format.h.
        : out( output ),
          locale( loc ),
          specs( s ),
          // NOLINTNEXTLINE(cata-no-long)
          abs_value( static_cast<UInt>( value ) ),
          prefix_size( 0 ) {
        static_assert( std::is_same<uint32_or_64_or_128_t<Int>, UInt>::value, "" );
        if( is_negative( value ) ) {
            prefix[0] = '-';
            ++prefix_size;
            abs_value = 0 - abs_value;
        } else if( specs.sign != sign::none && specs.sign != sign::minus ) {
            prefix[0] = specs.sign == sign::plus ? '+' : ' ';
            ++prefix_size;
        }
    }
References detail::is_negative(), sign::minus, sign::none, sign::plus, prefix, and basic_format_specs< Char >::sign.
Member Function Documentation
get_prefix()
template<typename OutputIt , typename Char , typename UInt > string_view detail::int_writer< OutputIt, Char, UInt >::get_prefix () const inline
Definition at line 1821 of file fmtlib_format.h.
{
        return string_view( prefix, prefix_size );
    }
References prefix.
on_bin()
template<typename OutputIt , typename Char , typename UInt > void detail::int_writer< OutputIt, Char, UInt >::on_bin () inline
Definition at line 1866 of file fmtlib_format.h.
                  {
        if( specs.alt ) {
            prefix[prefix_size++] = '0';
            prefix[prefix_size++] = static_cast<char>( specs.type );
        }
        int num_digits = count_digits<1>( abs_value );
        out = write_int( out, num_digits, get_prefix(), specs,
        [this, num_digits]( iterator it ) {
            return format_uint<1, Char>( it, abs_value, num_digits );
        } );
    }
References basic_format_specs< Char >::alt, prefix, basic_format_specs< Char >::type, and detail::write_int().
on_chr()
template<typename OutputIt , typename Char , typename UInt > void detail::int_writer< OutputIt, Char, UInt >::on_chr () inline
Definition at line 1951 of file fmtlib_format.h.
                  {
        *out++ = static_cast<Char>( abs_value );
    }
on_dec()
template<typename OutputIt , typename Char , typename UInt > void detail::int_writer< OutputIt, Char, UInt >::on_dec () inline
Definition at line 1845 of file fmtlib_format.h.
                  {
        auto num_digits = count_digits( abs_value );
        out = write_int(
        out, num_digits, get_prefix(), specs, [this, num_digits]( iterator it ) {
            return format_decimal<Char>( it, abs_value, num_digits ).end;
        } );
    }
References detail::count_digits(), and detail::write_int().
on_error()
template<typename OutputIt , typename Char , typename UInt > FMT_NORETURN void detail::int_writer< OutputIt, Char, UInt >::on_error () inline
Definition at line 1955 of file fmtlib_format.h.
{
        FMT_THROW( format_error( "invalid type specifier" ) );
    }
References FMT_THROW.
on_hex()
template<typename OutputIt , typename Char , typename UInt > void detail::int_writer< OutputIt, Char, UInt >::on_hex () inline
Definition at line 1853 of file fmtlib_format.h.
                  {
        if( specs.alt ) {
            prefix[prefix_size++] = '0';
            prefix[prefix_size++] = specs.type;
        }
        int num_digits = count_digits<4>( abs_value );
        out = write_int( out, num_digits, get_prefix(), specs,
        [this, num_digits]( iterator it ) {
            return format_uint<4, Char>( it, abs_value, num_digits,
                                         specs.type != 'x' );
        } );
    }
References basic_format_specs< Char >::alt, detail::count_digits< 4 >(), prefix, basic_format_specs< Char >::type, and detail::write_int().
on_num()
template<typename OutputIt , typename Char , typename UInt > void detail::int_writer< OutputIt, Char, UInt >::on_num () inline
Definition at line 1893 of file fmtlib_format.h.
                  {
        std::string groups = grouping<Char>( locale );
        if( groups.empty() ) {
            return on_dec();
        }
        auto sep = thousands_sep<Char>( locale );
        if( !sep ) {
            return on_dec();
        }
        int num_digits = count_digits( abs_value );
        int size = num_digits, n = num_digits;
        std::string::const_iterator group = groups.cbegin();
        while( group != groups.cend() && n > *group && *group > 0 &&
               *group != max_value<char>() ) {
            size += sep_size;
            n -= *group;
            ++group;
        }
        if( group == groups.cend() ) {
            size += sep_size * ( ( n - 1 ) / groups.back() );
        }
        char digits[40];
        format_decimal( digits, abs_value, num_digits );
        basic_memory_buffer<Char> buffer;
        size += static_cast<int>( prefix_size );
        const auto usize = to_unsigned( size );
        buffer.resize( usize );
        basic_string_view<Char> s( &sep, sep_size );
        // Index of a decimal digit with the least significant digit having index 0.
        int digit_index = 0;
        group = groups.cbegin();
        auto p = buffer.data() + size - 1;
        for( int i = num_digits - 1; i > 0; --i ) {
            *p-- = static_cast<Char>( digits[i] );
            if( *group <= 0 || ++digit_index % *group != 0 ||
                *group == max_value<char>() ) {
                continue;
            }
            if( group + 1 != groups.cend() ) {
                digit_index = 0;
                ++group;
            }
            std::uninitialized_copy( s.data(), s.data() + s.size(),
                                     make_checked( p, s.size() ) );
            p -= s.size();
        }
        *p-- = static_cast<Char>( *digits );
        if( prefix_size != 0 ) {
            *p = static_cast<Char>( '-' );
        }
        auto data = buffer.data();
        out = write_padded<align::right>(
                  out, specs, usize, usize,
        [ = ]( iterator it ) {
            return copy_str<Char>( data, data + size, it );
        } );
    }
References detail::count_digits(), basic_string_view< Char >::data(), detail::buffer< T >::data(), detail::format_decimal(), detail::make_checked(), basic_string_view< Char >::size(), om_direction::size, and detail::to_unsigned().
on_oct()
template<typename OutputIt , typename Char , typename UInt > void detail::int_writer< OutputIt, Char, UInt >::on_oct () inline
Definition at line 1878 of file fmtlib_format.h.
                  {
        int num_digits = count_digits<3>( abs_value );
        if( specs.alt && specs.precision <= num_digits && abs_value != 0 ) {
            // Octal prefix '0' is counted as a digit, so only add it if precision
            // is not greater than the number of digits.
            prefix[prefix_size++] = '0';
        }
        out = write_int( out, num_digits, get_prefix(), specs,
        [this, num_digits]( iterator it ) {
            return format_uint<3, Char>( it, abs_value, num_digits );
        } );
    }
References basic_format_specs< Char >::alt, basic_format_specs< Char >::precision, prefix, and detail::write_int().
Member Data Documentation
abs_value
template<typename OutputIt , typename Char , typename UInt > UInt detail::int_writer< OutputIt, Char, UInt >::abs_value
Definition at line 1814 of file fmtlib_format.h.
locale
template<typename OutputIt , typename Char , typename UInt > locale_ref detail::int_writer< OutputIt, Char, UInt >::locale
Definition at line 1811 of file fmtlib_format.h.
out
template<typename OutputIt , typename Char , typename UInt > OutputIt detail::int_writer< OutputIt, Char, UInt >::out
Definition at line 1810 of file fmtlib_format.h.
Referenced by detail::arg_formatter_base< OutputIt, Char, ErrorHandler >::write_int().
prefix
template<typename OutputIt , typename Char , typename UInt > char detail::int_writer< OutputIt, Char, UInt >::prefix[4]
Definition at line 1815 of file fmtlib_format.h.
prefix_size
template<typename OutputIt , typename Char , typename UInt > unsigned detail::int_writer< OutputIt, Char, UInt >::prefix_size
Definition at line 1816 of file fmtlib_format.h.
specs
template<typename OutputIt , typename Char , typename UInt > const basic_format_specs<Char>& detail::int_writer< OutputIt, Char, UInt >::specs
Definition at line 1812 of file fmtlib_format.h.
The documentation for this struct was generated from the following file:
src/fmtlib_format.h