Cataclysm BN: place_trap_actor::data Struct Reference
place_trap_actor::data Struct Reference
#include <iuse_actor.h>
Public Member Functions
data ()
void load (const JsonObject &obj)
Public Attributes
trap_str_id trap
std::string done_message
The message shown when the trap has been set.
int practice = 0
Amount of practice of the "trap" skill.
int moves = 100
Move points that are used when placing the trap.
Detailed Description
Definition at line 1075 of file iuse_actor.h.
Constructor & Destructor Documentation
data()
place_trap_actor::data::data ()
Definition at line 4051 of file iuse_actor.cpp.
: trap(trap_str_id::NULL_ID()) {}
Member Function Documentation
load()
void place_trap_actor::data::load (const JsonObject & obj)
Definition at line 4053 of file iuse_actor.cpp.
{
    assign( obj, "trap", trap );
    assign( obj, "done_message", done_message );
    assign( obj, "practice", practice );
    assign( obj, "moves", moves );
}
References assign(), Creature::moves, and player::practice().
Referenced by place_trap_actor::load().
Member Data Documentation
done_message
std::string place_trap_actor::data::done_message
The message shown when the trap has been set.
Definition at line 1079 of file iuse_actor.h.
Referenced by place_trap_actor::use().
moves
int place_trap_actor::data::moves = 100
Move points that are used when placing the trap.
Definition at line 1083 of file iuse_actor.h.
Referenced by place_trap_actor::use().
practice
int place_trap_actor::data::practice = 0
Amount of practice of the "trap" skill.
Definition at line 1081 of file iuse_actor.h.
Referenced by place_trap_actor::use().
trap
trap_str_id place_trap_actor::data::trap
Definition at line 1077 of file iuse_actor.h.
Referenced by place_trap_actor::use().
The documentation for this struct was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp