Cataclysm BN: cata_ofstream Struct Reference
cata_ofstream Struct Reference
Wrapper around std::ofstream that provides cross-platform support for UTF-8 paths.
#include <fstream_utils.h>
Public Member Functions
cata_ofstream ()
cata_ofstream (const cata_ofstream &)=delete
cata_ofstream (cata_ofstream &&x)
~cata_ofstream ()
cata_ofstream & operator= (const cata_ofstream &)=delete
cata_ofstream & operator= (cata_ofstream &&)
cata_ofstream & mode (cata_ios_mode m)
cata_ofstream & open (const std::string &path)
bool is_open ()
bool fail ()
bool bad ()
void flush ()
void close ()
std::ostream & operator* ()
std::ostream * operator-> ()
Private Attributes
cata_ios_mode _mode = cata_ios_mode::none
std::unique_ptr< std::ofstream > _stream
Detailed Description
Wrapper around std::ofstream that provides cross-platform support for UTF-8 paths.
Definition at line 30 of file fstream_utils.h.
Constructor & Destructor Documentation
cata_ofstream() [1/3]
cata_ofstream::cata_ofstream () default
cata_ofstream() [2/3]
cata_ofstream::cata_ofstream (const cata_ofstream &) delete
cata_ofstream() [3/3]
cata_ofstream::cata_ofstream (cata_ofstream && x)
Definition at line 303 of file cata_utility.cpp.
{
    *this = std::move( x );
}
References avatar_action::move().
~cata_ofstream()
cata_ofstream::~cata_ofstream ()
Definition at line 308 of file cata_utility.cpp.
{
    close();
}
References close().
Member Function Documentation
bad()
bool cata_ofstream::bad ()
Definition at line 318 of file cata_utility.cpp.
{
    return !_stream || _stream->bad();
}
References _stream.
close()
void cata_ofstream::close ()
Definition at line 291 of file cata_utility.cpp.
{
    if( _stream ) {
        _stream->close();
        _stream.reset();
    }
}
References _stream.
Referenced by ofstream_wrapper::close(), and ~cata_ofstream().
fail()
bool cata_ofstream::fail ()
Definition at line 313 of file cata_utility.cpp.
{
    return !_stream || _stream->fail();
}
References _stream.
Referenced by ofstream_wrapper::close().
flush()
void cata_ofstream::flush ()
Definition at line 323 of file cata_utility.cpp.
{
    _stream->flush();
}
References _stream.
Referenced by ofstream_wrapper::close().
is_open()
bool cata_ofstream::is_open ()
Definition at line 286 of file cata_utility.cpp.
{
    return _stream && _stream->is_open();
}
References _stream.
Referenced by ofstream_wrapper::close(), and ofstream_wrapper::open().
mode()
cata_ofstream & cata_ofstream::mode (cata_ios_mode m) inline
Definition at line 39 of file fstream_utils.h.
{
            _mode = m;
            return *this;
        }
References _mode.
Referenced by open().
open()
cata_ofstream & cata_ofstream::open (const std::string & path)
Definition at line 274 of file cata_utility.cpp.
{
    std::ios_base::openmode mode = cata_ios_mode_to_std( std::ios_base::out, _mode );
#if defined (_MSC_VER)
    _stream = std::make_unique<std::ofstream>( utf8_to_wstr( path ), mode );
#else
    _stream = std::make_unique<std::ofstream>( path, mode );
#endif
    return *this;
}
References _mode, _stream, cata_ios_mode_to_std(), mode(), and utf8_to_wstr().
operator*()
std::ostream & cata_ofstream::operator* ()
Definition at line 328 of file cata_utility.cpp.
{
    return *_stream;
}
References _stream.
operator->()
std::ostream * cata_ofstream::operator-> ()
Definition at line 333 of file cata_utility.cpp.
{
    return &*_stream;
}
References _stream.
operator=() [1/2]
cata_ofstream & cata_ofstream::operator= (cata_ofstream && x)
Definition at line 267 of file cata_utility.cpp.
{
    _stream = std::move( x._stream );
    _mode = x._mode;
    return *this;
}
References _mode, _stream, and avatar_action::move().
operator=() [2/2]
cata_ofstream & cata_ofstream::operator= (const cata_ofstream &) delete
Member Data Documentation
_mode
cata_ios_mode cata_ofstream::_mode = cata_ios_mode::none private
Definition at line 55 of file fstream_utils.h.
Referenced by mode(), open(), and operator=().
_stream
std::unique_ptr<std::ofstream> cata_ofstream::_stream private
Definition at line 61 of file fstream_utils.h.
Referenced by bad(), close(), fail(), flush(), is_open(), open(), operator*(), operator->(), and operator=().
The documentation for this struct was generated from the following files:
src/fstream_utils.h
src/cata_utility.cpp