Cataclysm BN: islot_ammo Struct Reference
islot_ammo Struct Reference
#include <itype.h>
Public Attributes
ammotype type
Ammo type, basically the "form" of the ammo that fits into the gun/tool.
cata::optional< itype_id > casing
Type id of casings, if any.
Public Attributes inherited from common_ranged_data
damage_instance damage
Damage, armor piercing and multipliers for each.
int range = 0
Range bonus from gun.
int dispersion = 0
Dispersion "bonus" from gun.
itype_id drop = itype_id::NULL_ID()
Control chance for and state of any items dropped at ranged target.
bool drop_active = true
int dont_recover_one_in = 1
Chance to fail to recover the ammo used.
int def_charges = 1
Default charges.
std::set< ammo_effect_str_id > ammo_effects
See ammo_effect struct.
int loudness = -1
Base loudness of ammo (possibly modified by gun/gunmods).
int recoil = 0
Recoil (per shot), roughly equivalent to kinetic energy (in Joules)
bool cookoff = false
Should this ammo explode in fire? This value is cached by item_factory based on ammo_effects and item material.
bool special_cookoff = false
Should this ammo apply a special explosion effect when in fire? This value is cached by item_factory based on ammo_effects and item material.
cata::optional< bool > force_stat_display
Some combat ammo might not have a damage value Set this to make it show as combat ammo anyway.
cata::optional< shape_factory > shape
AoE shape or null if it's a projectile.
bool was_loaded
void load (const JsonObject &jo)
void deserialize (JsonIn &jsin)
Detailed Description
Definition at line 672 of file itype.h.
Member Function Documentation
deserialize()
void islot_ammo::deserialize (JsonIn & jsin)
Definition at line 1691 of file item_factory.cpp.
{
    const JsonObject jo = jsin.get_object();
    load( jo );
}
References JsonIn::get_object(), and load().
load()
void islot_ammo::load (const JsonObject & jo)
Definition at line 1672 of file item_factory.cpp.
{
    mandatory( jo, was_loaded, "ammo_type", type );
    optional( jo, was_loaded, "casing", casing, cata::nullopt );
    optional( jo, was_loaded, "drop", drop, itype_id::NULL_ID() );
    optional( jo, was_loaded, "drop_active", drop_active, true );
    optional( jo, was_loaded, "dont_recover_one_in", dont_recover_one_in, 1 );
    // Damage instance assign reader handles pierce and prop_damage
    assign( jo, "damage", damage );
    assign( jo, "range", range );
    assign( jo, "dispersion", dispersion );
    assign( jo, "recoil", recoil );
    optional( jo, was_loaded, "count", def_charges, 1 );
    optional( jo, was_loaded, "loudness", loudness, -1 );
    assign( jo, "effects", ammo_effects );
    optional( jo, was_loaded, "show_stats", force_stat_display, cata::nullopt );
    optional( jo, was_loaded, "shape", shape, cata::nullopt );
}
References assign(), casing, common_ranged_data::damage, def_charges, common_ranged_data::dispersion, dont_recover_one_in, drop, drop_active, force_stat_display, loudness, mandatory(), string_id< itype >::NULL_ID(), cata::nullopt, optional(), common_ranged_data::range, recoil, type, and was_loaded.
Referenced by deserialize().
Member Data Documentation
ammo_effects
std::set<ammo_effect_str_id> islot_ammo::ammo_effects
See ammo_effect struct.
Definition at line 705 of file itype.h.
Referenced by item::ammo_info().
casing
cata::optional<itype_id> islot_ammo::casing
Type id of casings, if any.
Definition at line 680 of file itype.h.
Referenced by load().
cookoff
bool islot_ammo::cookoff = false
Should this ammo explode in fire? This value is cached by item_factory based on ammo_effects and item material.
Warning
It is not read from the json directly.
Definition at line 720 of file itype.h.
def_charges
int islot_ammo::def_charges = 1
Default charges.
Definition at line 700 of file itype.h.
Referenced by load().
dont_recover_one_in
int islot_ammo::dont_recover_one_in = 1
Chance to fail to recover the ammo used.
As in, one_in(this_var) chance of destroying it. For 100% chances, see drop.
Definition at line 695 of file itype.h.
Referenced by load(), and make_gun_projectile().
drop
itype_id islot_ammo::drop = itype_id::NULL_ID()
Control chance for and state of any items dropped at ranged target.
Definition at line 685 of file itype.h.
Referenced by load(), and make_gun_projectile().
drop_active
bool islot_ammo::drop_active = true
Definition at line 687 of file itype.h.
Referenced by load(), and make_gun_projectile().
force_stat_display
cata::optional<bool> islot_ammo::force_stat_display
Some combat ammo might not have a damage value Set this to make it show as combat ammo anyway.
Definition at line 733 of file itype.h.
Referenced by item::ammo_info(), and load().
loudness
int islot_ammo::loudness = -1
Base loudness of ammo (possibly modified by gun/gunmods).
If unspecified an appropriate value is calculated based upon the other properties of the ammo
Definition at line 710 of file itype.h.
Referenced by load().
recoil
int islot_ammo::recoil = 0
Recoil (per shot), roughly equivalent to kinetic energy (in Joules)
Definition at line 713 of file itype.h.
Referenced by item::ammo_info(), and load().
shape
cata::optional<shape_factory> islot_ammo::shape
AoE shape or null if it's a projectile.
Definition at line 738 of file itype.h.
Referenced by item::ammo_info().
special_cookoff
bool islot_ammo::special_cookoff = false
Should this ammo apply a special explosion effect when in fire? This value is cached by item_factory based on ammo_effects and item material.
Warning
It is not read from the json directly.
Definition at line 727 of file itype.h.
type
ammotype islot_ammo::type
Ammo type, basically the "form" of the ammo that fits into the gun/tool.
Definition at line 676 of file itype.h.
Referenced by load().
was_loaded
bool islot_ammo::was_loaded
Definition at line 740 of file itype.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/itype.h
src/item_factory.cpp