Cataclysm BN: detail::format_handler< OutputIt, Char, Context > Struct Template Reference
detail::format_handler< OutputIt, Char, Context > Struct Template Reference
#include <fmtlib_format.h>
Public Member Functions
format_handler (OutputIt out, basic_string_view< Char > str, basic_format_args< Context > format_args, detail::locale_ref loc)
void on_text (const Char *begin, const Char *end)
int on_arg_id ()
int on_arg_id (int id)
int on_arg_id (basic_string_view< Char > id)
FMT_INLINE void on_replacement_field (int id, const Char *)
const Char * on_format_specs (int id, const Char *begin, const Char *end)
Public Member Functions inherited from detail::error_handler
constexpr error_handler ()=default
constexpr error_handler (const error_handler &)=default
FMT_NORETURN FMT_API void on_error (const char *message)
Public Attributes
basic_format_parse_context< Char > parse_context
Context context
Detailed Description
template<typename OutputIt, typename Char, typename Context>
struct detail::format_handler< OutputIt, Char, Context >
Definition at line 3497 of file fmtlib_format.h.
Constructor & Destructor Documentation
format_handler()
template<typename OutputIt , typename Char , typename Context > detail::format_handler< OutputIt, Char, Context >::format_handler (OutputIt out, basic_string_view< Char > str, basic_format_args< Context > format_args, detail::locale_ref loc) inline
Definition at line 3501 of file fmtlib_format.h.
        : parse_context( str ), context( out, format_args, loc ) {}
Member Function Documentation
on_arg_id() [1/3]
template<typename OutputIt , typename Char , typename Context > int detail::format_handler< OutputIt, Char, Context >::on_arg_id () inline
Definition at line 3513 of file fmtlib_format.h.
                    {
        return parse_context.next_arg_id();
    }
References basic_format_parse_context< Char, ErrorHandler >::next_arg_id().
on_arg_id() [2/3]
template<typename OutputIt , typename Char , typename Context > int detail::format_handler< OutputIt, Char, Context >::on_arg_id (basic_string_view< Char > id) inline
Definition at line 3519 of file fmtlib_format.h.
{
        int arg_id = context.arg_id( id );
        if( arg_id < 0 ) {
            on_error( "argument not found" );
        }
        return arg_id;
    }
on_arg_id() [3/3]
template<typename OutputIt , typename Char , typename Context > int detail::format_handler< OutputIt, Char, Context >::on_arg_id (int id) inline
Definition at line 3516 of file fmtlib_format.h.
{
        return parse_context.check_arg_id( id ), id;
    }
References basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), and base_camps::id.
on_format_specs()
template<typename OutputIt , typename Char , typename Context > const Char * detail::format_handler< OutputIt, Char, Context >::on_format_specs (int id, const Char * begin, const Char * end) inline
Definition at line 3536 of file fmtlib_format.h.
{
        auto arg = get_arg( context, id );
        if( arg.type() == type::custom_type ) {
            advance_to( parse_context, begin );
            visit_format_arg( custom_formatter<Context>( parse_context, context ), arg );
            return parse_context.begin();
        }
        auto specs = basic_format_specs<Char>();
        if( begin + 1 < end && begin[1] == '}' && is_ascii_letter( *begin ) ) {
            specs.type = static_cast<char>( *begin++ );
        } else {
            using parse_context_t = basic_format_parse_context<Char>;
            specs_checker<specs_handler<parse_context_t, Context>> handler(
                        specs_handler<parse_context_t, Context>( specs, parse_context,
                                context ),
                        arg.type() );
            begin = parse_format_specs( begin, end, handler );
            if( begin == end || *begin != '}' ) {
                on_error( "missing '}' in format string" );
            }
        }
        context.advance_to( visit_format_arg(
                                arg_formatter<OutputIt, Char>( context, &parse_context, &specs ), arg ) );
        return begin;
    }
References advance_to(), arg(), basic_format_parse_context< Char, ErrorHandler >::begin(), detail::get_arg(), detail::is_ascii_letter(), detail::parse_format_specs(), basic_format_specs< Char >::type, and visit_format_arg().
on_replacement_field()
template<typename OutputIt , typename Char , typename Context > FMT_INLINE void detail::format_handler< OutputIt, Char, Context >::on_replacement_field (int id, const Char *) inline
Definition at line 3527 of file fmtlib_format.h.
{
        auto arg = get_arg( context, id );
        context.advance_to( visit_format_arg(
                                default_arg_formatter<OutputIt, Char> {context.out(), context.args(),
                                        context.locale()
                                                                      },
                                arg ) );
    }
References arg(), detail::get_arg(), detail::default_arg_formatter< OutputIt, Char >::out, and visit_format_arg().
on_text()
template<typename OutputIt , typename Char , typename Context > void detail::format_handler< OutputIt, Char, Context >::on_text (const Char * begin, const Char * end) inline
Definition at line 3505 of file fmtlib_format.h.
{
        auto size = to_unsigned( end - begin );
        auto out = context.out();
        auto &&it = reserve( out, size );
        it = std::copy_n( begin, size, it );
        context.advance_to( out );
    }
References detail::reserve(), om_direction::size, and detail::to_unsigned().
Member Data Documentation
context
template<typename OutputIt , typename Char , typename Context > Context detail::format_handler< OutputIt, Char, Context >::context
Definition at line 3499 of file fmtlib_format.h.
parse_context
template<typename OutputIt , typename Char , typename Context > basic_format_parse_context<Char> detail::format_handler< OutputIt, Char, Context >::parse_context
Definition at line 3498 of file fmtlib_format.h.
The documentation for this struct was generated from the following file:
src/fmtlib_format.h