Cataclysm BN: zone_priority_data Struct Reference
zone_priority_data Struct Reference
#include <item_category.h>
Public Member Functions
void deserialize (JsonIn &jsin)
void load (JsonObject &jo)
Public Attributes
bool was_loaded = false
zone_type_id id
bool filthy = false
cata::flat_set< std::string > flags
Detailed Description
Definition at line 18 of file item_category.h.
Member Function Documentation
deserialize()
void zone_priority_data::deserialize (JsonIn & jsin)
Definition at line 27 of file item_category.cpp.
{
    JsonObject data = jsin.get_object();
    load( data );
}
References JsonIn::get_object(), and load().
load()
void zone_priority_data::load (JsonObject & jo)
Definition at line 33 of file item_category.cpp.
{
    mandatory( jo, was_loaded, "id", id );
    optional( jo, was_loaded, "flags", flags );
    optional( jo, was_loaded, "filthy", filthy, false );
}
References filthy, flags, mandatory(), optional(), and was_loaded.
Referenced by deserialize().
Member Data Documentation
filthy
bool zone_priority_data::filthy = false
Definition at line 21 of file item_category.h.
Referenced by load().
flags
cata::flat_set<std::string> zone_priority_data::flags
Definition at line 22 of file item_category.h.
Referenced by load().
id
zone_type_id zone_priority_data::id
Definition at line 20 of file item_category.h.
was_loaded
bool zone_priority_data::was_loaded = false
Definition at line 19 of file item_category.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/item_category.h
src/item_category.cpp