Cataclysm BN: overmap_path_params Struct Reference
overmap_path_params Struct Reference
#include <overmapbuffer.h>
Static Public Member Functions
static overmap_path_params for_player ()
static overmap_path_params for_npc ()
static overmap_path_params for_land_vehicle (float offroad_coeff, bool tiny, bool amphibious)
static overmap_path_params for_watercraft ()
static overmap_path_params for_aircraft ()
Public Attributes
int road_cost = -1
int field_cost = -1
int dirt_road_cost = -1
int trail_cost = -1
int forest_cost = -1
int small_building_cost = -1
int shore_cost = -1
int swamp_cost = -1
int water_cost = -1
int air_cost = -1
int other_cost = -1
bool avoid_danger = true
bool only_known_by_player = true
Static Public Attributes
static constexpr int standard_cost = 10
Detailed Description
Definition at line 43 of file overmapbuffer.h.
Member Function Documentation
for_aircraft()
overmap_path_params overmap_path_params::for_aircraft () static
Definition at line 759 of file overmapbuffer.cpp.
{
    overmap_path_params ret;
    ret.air_cost = 10;
    return ret;
}
References cata::hash64_detail::ret.
Referenced by overmap_ui::get_overmap_path_to().
for_land_vehicle()
overmap_path_params overmap_path_params::for_land_vehicle (float offroad_coeff, bool tiny, bool amphibious) static
Definition at line 731 of file overmapbuffer.cpp.
{
    const bool can_offroad = offroad_coeff >= 0.05;
    overmap_path_params ret;
    ret.road_cost = 10;
    ret.field_cost = can_offroad ? std::lround( 15 / std::min( 1.0f, offroad_coeff ) ) : -1;
    ret.dirt_road_cost = ret.field_cost;
    ret.forest_cost = -1;
    ret.small_building_cost = ( can_offroad && tiny ) ? ret.field_cost + 30 : -1;
    ret.swamp_cost = -1;
    ret.trail_cost = ( can_offroad && tiny ) ? ret.field_cost + 10 : -1;
    if( amphibious ) {
        const overmap_path_params boat_params = overmap_path_params::for_watercraft();
        ret.water_cost = boat_params.water_cost;
        ret.shore_cost = boat_params.shore_cost;
    }
    return ret;
}
References for_watercraft(), cata::hash64_detail::ret, shore_cost, and water_cost.
Referenced by overmap_ui::get_overmap_path_to().
for_npc()
overmap_path_params overmap_path_params::for_npc () static
Definition at line 723 of file overmapbuffer.cpp.
{
    overmap_path_params ret = overmap_path_params::for_player();
    ret.only_known_by_player = false;
    ret.avoid_danger = false;
    return ret;
}
References for_player(), and cata::hash64_detail::ret.
Referenced by talk_function::goto_location(), game::overmap_npc_move(), and npc::set_omt_destination().
for_player()
overmap_path_params overmap_path_params::for_player () static
Definition at line 708 of file overmapbuffer.cpp.
{
    overmap_path_params ret;
    ret.road_cost = 10;
    ret.dirt_road_cost = 10;
    ret.field_cost = 15;
    ret.trail_cost = 18;
    ret.shore_cost = 20;
    ret.small_building_cost = 20;
    ret.forest_cost = 30;
    ret.swamp_cost = 100;
    ret.other_cost = 30;
    return ret;
}
References cata::hash64_detail::ret.
Referenced by for_npc(), and overmap_ui::get_overmap_path_to().
for_watercraft()
overmap_path_params overmap_path_params::for_watercraft () static
Definition at line 751 of file overmapbuffer.cpp.
{
    overmap_path_params ret;
    ret.water_cost = 10;
    ret.shore_cost = 20;
    return ret;
}
References cata::hash64_detail::ret.
Referenced by for_land_vehicle(), and overmap_ui::get_overmap_path_to().
Member Data Documentation
air_cost
int overmap_path_params::air_cost = -1
Definition at line 53 of file overmapbuffer.h.
Referenced by get_terrain_cost().
avoid_danger
bool overmap_path_params::avoid_danger = true
Definition at line 55 of file overmapbuffer.h.
Referenced by get_terrain_cost().
dirt_road_cost
int overmap_path_params::dirt_road_cost = -1
Definition at line 46 of file overmapbuffer.h.
Referenced by get_terrain_cost().
field_cost
int overmap_path_params::field_cost = -1
Definition at line 45 of file overmapbuffer.h.
Referenced by get_terrain_cost().
forest_cost
int overmap_path_params::forest_cost = -1
Definition at line 48 of file overmapbuffer.h.
Referenced by get_terrain_cost().
only_known_by_player
bool overmap_path_params::only_known_by_player = true
Definition at line 56 of file overmapbuffer.h.
Referenced by get_terrain_cost().
other_cost
int overmap_path_params::other_cost = -1
Definition at line 54 of file overmapbuffer.h.
Referenced by get_terrain_cost().
road_cost
int overmap_path_params::road_cost = -1
Definition at line 44 of file overmapbuffer.h.
Referenced by get_terrain_cost().
shore_cost
int overmap_path_params::shore_cost = -1
Definition at line 50 of file overmapbuffer.h.
Referenced by for_land_vehicle(), and get_terrain_cost().
small_building_cost
int overmap_path_params::small_building_cost = -1
Definition at line 49 of file overmapbuffer.h.
standard_cost
constexpr int overmap_path_params::standard_cost = 10 static constexpr
Definition at line 58 of file overmapbuffer.h.
swamp_cost
int overmap_path_params::swamp_cost = -1
Definition at line 51 of file overmapbuffer.h.
Referenced by get_terrain_cost().
trail_cost
int overmap_path_params::trail_cost = -1
Definition at line 47 of file overmapbuffer.h.
Referenced by get_terrain_cost().
water_cost
int overmap_path_params::water_cost = -1
Definition at line 52 of file overmapbuffer.h.
Referenced by for_land_vehicle(), overmap_ui::get_overmap_path_to(), and get_terrain_cost().
The documentation for this struct was generated from the following files:
src/overmapbuffer.h
src/overmapbuffer.cpp