Cataclysm BN: point_traits< Point, typename > Struct Template Reference
point_traits< Point, typename > Struct Template Reference
#include <point_traits.h>
Static Public Member Functions
static int & x (Point &p)
static int x (const Point &p)
static int & y (Point &p)
static int y (const Point &p)
static int & z (Point &p)
static int z (const Point &p)
Detailed Description
template<typename Point, typename = void>
struct point_traits< Point, typename >
Definition at line 12 of file point_traits.h.
Member Function Documentation
x() [1/2]
template<typename Point , typename = void> static int point_traits< Point, typename >::x (const Point & p) inline static
Definition at line 16 of file point_traits.h.
{
        return p.x();
    }
x() [2/2]
template<typename Point , typename = void> static int & point_traits< Point, typename >::x (Point & p) inline static
Definition at line 13 of file point_traits.h.
{
        return p.x();
    }
Referenced by point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::at(), tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::size().
y() [1/2]
template<typename Point , typename = void> static int point_traits< Point, typename >::y (const Point & p) inline static
Definition at line 22 of file point_traits.h.
{
        return p.y();
    }
y() [2/2]
template<typename Point , typename = void> static int & point_traits< Point, typename >::y (Point & p) inline static
Definition at line 19 of file point_traits.h.
{
        return p.y();
    }
Referenced by point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::at(), tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::size().
z() [1/2]
template<typename Point , typename = void> static int point_traits< Point, typename >::z (const Point & p) inline static
Definition at line 28 of file point_traits.h.
{
        return p.z();
    }
z() [2/2]
template<typename Point , typename = void> static int & point_traits< Point, typename >::z (Point & p) inline static
Definition at line 25 of file point_traits.h.
{
        return p.z();
    }
Referenced by point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::at(), tripoint_range< Tripoint >::end(), tripoint_range< Tripoint >::point_generator::operator!=(), tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::size().
The documentation for this struct was generated from the following file:
src/point_traits.h