Cataclysm BN: active_tiles::furn_transform Struct Reference
active_tiles::furn_transform Struct Reference
#include <active_tile_data_def.h>
Public Member Functions
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Public Attributes
furn_str_id id = furn_str_id::NULL_ID()
std::string msg
Detailed Description
Definition at line 11 of file active_tile_data_def.h.
Member Function Documentation
deserialize()
void active_tiles::furn_transform::deserialize (JsonIn & jsin)
Definition at line 61 of file active_tile_data.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.read( "id", id );
    jo.read( "msg", msg );
}
References JsonIn::get_object(), msg, and JsonObject::read().
serialize()
void active_tiles::furn_transform::serialize (JsonOut & jsout) const
Definition at line 53 of file active_tile_data.cpp.
{
    jsout.start_object();
    jsout.member( "id", id );
    jsout.member( "msg", msg );
    jsout.end_object();
}
References JsonOut::end_object(), JsonOut::member(), msg, and JsonOut::start_object().
Member Data Documentation
id
furn_str_id active_tiles::furn_transform::id = furn_str_id::NULL_ID()
Definition at line 12 of file active_tile_data_def.h.
Referenced by charge_watcher_tile::update_internal(), and steady_consumer_tile::update_internal().
msg
std::string active_tiles::furn_transform::msg
Definition at line 13 of file active_tile_data_def.h.
Referenced by deserialize(), serialize(), charge_watcher_tile::update_internal(), and steady_consumer_tile::update_internal().
The documentation for this struct was generated from the following files:
src/active_tile_data_def.h
src/active_tile_data.cpp