Cataclysm BN: ter_t Struct Reference
ter_t Struct Reference
#include <mapdata.h>
Public Member Functions
ter_t ()
void load (const JsonObject &jo, const std::string &src) override
void check () const override
Public Member Functions inherited from map_data_common_t
virtual ~map_data_common_t ()=default
bool has_curtains () const
std::string name () const
void load_symbol (const JsonObject &jo)
const std::set< std::string > & get_flags () const
bool has_flag (const std::string &flag) const
bool has_flag (const ter_bitflags flag) const
void set_flag (const std::string &flag)
void set_connects (const std::string &connect_group_string)
bool connects (int &ret) const
bool connects_to (int test_connect_group) const
int symbol () const
nc_color color () const
const harvest_id & get_harvest () const
const std::set< std::string > & get_harvest_names () const
Returns a set of names of the items that would be dropped.
std::string extended_description () const
Static Public Member Functions
static size_t count ()
static const std::vector< ter_t > & get_all ()
Public Attributes
std::vector< std::pair< ter_str_id, mod_id > > src
ter_str_id id
ter_str_id open
ter_str_id close
std::string trap_id_str
ter_str_id transforms_into
ter_str_id roof
trap_id trap
int heat_radiation = 0
Public Attributes inherited from map_data_common_t
map_bash_info bash
map_deconstruct_info deconstruct
pry_result pry
ter_str_id curtain_transform
std::array< int, NUM_SEASONS > symbol_
int light_emitted = 0
int movecost = 0
int coverage = 0
units::volume max_volume = 1000_liter
translation description
std::array< nc_color, NUM_SEASONS > color_
std::string looks_like
std::string message
std::string prompt
iexamine_function examine
std::array< harvest_id, NUM_SEASONS > harvest_by_season
When will this terrain/furniture get harvested and what will drop? Note: This excludes items that take extra tools to harvest.
bool transparent = false
int connect_group = 0
bool was_loaded = false
Additional Inherited Members
Protected Attributes inherited from map_data_common_t
std::string name_
Detailed Description
Definition at line 461 of file mapdata.h.
Constructor & Destructor Documentation
ter_t()
ter_t::ter_t ()
Definition at line 462 of file mapdata.cpp.
             : open( ter_str_id::NULL_ID() ), close( ter_str_id::NULL_ID() ),
    transforms_into( ter_str_id::NULL_ID() ),
    roof( ter_str_id::NULL_ID() ), trap( tr_null ) {}
Member Function Documentation
check()
void ter_t::check () const override virtual
Reimplemented from map_data_common_t.
Definition at line 1453 of file mapdata.cpp.
{
    map_data_common_t::check();
    check_bash_items( bash, id.str(), true );
    check_decon_items( deconstruct, id.str(), true );
    check_pry_items( pry, id.str(), true );
    if( !transforms_into.is_valid() ) {
        debugmsg( "invalid transforms_into %s for %s", transforms_into.c_str(), id.c_str() );
    }
    if( !open.is_valid() ) {
        debugmsg( "invalid terrain %s for opening %s", open.c_str(), id.c_str() );
    }
    if( id && open == id ) {
        debugmsg( "%s has \"open\" set to itself", id.c_str() );
    }
    if( !close.is_valid() ) {
        debugmsg( "invalid terrain %s for closing %s", close.c_str(), id.c_str() );
    }
    if( id && close == id ) {
        debugmsg( "%s has \"close\" set to itself", id.c_str() );
    }
    if( transforms_into && transforms_into == id ) {
        debugmsg( "%s transforms_into itself", id.c_str() );
    }
    if( bash.ter_set && bash.ter_set == id ) {
        debugmsg( "%s turns into itself when bashed", id.c_str() );
    }
    if( bash.ter_set_bashed_from_above && bash.ter_set_bashed_from_above == id ) {
        debugmsg( "%s turns into itself when bashed from above", id.c_str() );
    }
    if( json_report_strict
        && ( bash.ter_set == t_open_air.id() || bash.ter_set_bashed_from_above == t_open_air.id() ) ) {
        debugmsg( "%s explicitly turns into \"t_open_air\", but \"t_null\" is preferred",
                  id.c_str() );
    }
    if( roof && roof->roof ) {
        debugmsg( "%s has roof %s, which has its own roof %s",
                  id.str(), roof.str(), roof->roof.str() );
    }
    if( roof && !roof->bash.bash_below ) {
        debugmsg( "%s has roof %s, with \"bash_below\": false",
                  id.str(), roof.str() );
    }
    if( bash.ter_set_bashed_from_above && bash.ter_set_bashed_from_above->movecost == 0 &&
        !bash.ter_set_bashed_from_above->roof ) {
        debugmsg( "%s has bash.ter_set_bashed_from_above %s, which is unpassable but has no roof",
                  id.str(), bash.ter_set_bashed_from_above.str() );
    }
    if( json_report_strict && deconstruct.ter_set == t_open_air.id() ) {
        debugmsg( "%s deconstructs into \"t_open_air\", but \"t_null\" is preferred",
                  id.str() );
    }
    if( movecost == 1 || movecost < 0 ) {
        debugmsg( "%s has move_cost %d, but allowed values for terrain are >=2 and 0", id, movecost );
    }
}
References map_data_common_t::bash, map_bash_info::bash_below, string_id< T >::c_str(), map_data_common_t::check(), check_bash_items(), check_decon_items(), check_pry_items(), close, debugmsg, map_data_common_t::deconstruct, int_id< T >::id(), string_id< T >::is_valid(), json_report_strict, map_data_common_t::movecost, open, map_data_common_t::pry, roof, string_id< T >::str(), t_open_air, map_bash_info::ter_set, map_deconstruct_info::ter_set, map_bash_info::ter_set_bashed_from_above, and transforms_into.
count()
size_t ter_t::count () static
Definition at line 1261 of file mapdata.cpp.
{
    return terrain_data.size();
}
References anonymous_namespace{mapdata.cpp}::terrain_data.
get_all()
const std::vector< ter_t > & ter_t::get_all () static
Definition at line 1511 of file mapdata.cpp.
{
    return terrain_data.get_all();
}
References anonymous_namespace{mapdata.cpp}::terrain_data.
load()
void ter_t::load (const JsonObject & jo, const std::string & src) override virtual
Reimplemented from map_data_common_t.
Definition at line 1334 of file mapdata.cpp.
{
    connect_group = TERCONN_NONE;
    map_data_common_t::load( jo, src );
    mandatory( jo, was_loaded, "name", name_ );
    mandatory( jo, was_loaded, "move_cost", movecost );
    assign( jo, "coverage", coverage, is_json_check_strict( src ) );
    assign( jo, "max_volume", max_volume, is_json_check_strict( src ) );
    assign( jo, "trap", trap_id_str, is_json_check_strict( src ) );
    assign( jo, "light_emitted", light_emitted, is_json_check_strict( src ) );
    assign( jo, "heat_radiation", heat_radiation, is_json_check_strict( src ) );
    load_symbol( jo );
    trap = tr_null;
    // connect_group is initialized to none, then terrain flags are set, then finally
    // connections from JSON are set. This is so that wall flags can set wall connections
    // but can be overridden by explicit connections in JSON.
    if( jo.has_member( "connects_to" ) ) {
        set_connects( jo.get_string( "connects_to" ) );
    }
    assign( jo, "open", open, is_json_check_strict( src ) );
    assign( jo, "close", close, is_json_check_strict( src ) );
    assign( jo, "transforms_into", transforms_into, is_json_check_strict( src ) );
    assign( jo, "roof", roof, is_json_check_strict( src ) );
    // Not assign, because we want to overwrite individual fields
    optional( jo, was_loaded, "bash", bash );
    deconstruct.load( jo, "deconstruct", false );
    pry.load( jo, "pry", pry_result::terrain );
}
References assign(), map_data_common_t::bash, close, map_data_common_t::connect_group, map_data_common_t::coverage, map_data_common_t::deconstruct, JsonObject::get_string(), JsonObject::has_member(), heat_radiation, anonymous_namespace{mapdata.cpp}::is_json_check_strict(), map_data_common_t::light_emitted, map_data_common_t::load(), map_deconstruct_info::load(), pry_result::load(), map_data_common_t::load_symbol(), mandatory(), map_data_common_t::max_volume, map_data_common_t::movecost, map_data_common_t::name_, open, optional(), map_data_common_t::pry, roof, map_data_common_t::set_connects(), src, TERCONN_NONE, pry_result::terrain, tr_null, transforms_into, trap_id_str, and map_data_common_t::was_loaded.
Member Data Documentation
close
ter_str_id ter_t::close
Definition at line 467 of file mapdata.h.
Referenced by check(), iexamine::curtains(), load(), and open().
heat_radiation
int ter_t::heat_radiation = 0
Definition at line 475 of file mapdata.h.
Referenced by get_heat_radiation(), and load().
id
ter_str_id ter_t::id
Definition at line 465 of file mapdata.h.
Referenced by ter_furn_transform::add_all_messages(), apply< ter_t >(), map::bash_ter_success(), colorized_ter_name_flags_at(), construct::done_deconstruct(), get_alt_ter(), game::print_terrain_info(), map::process_fields_in_submap(), ter_furn_transform::transform(), and map::valid_move().
open
ter_str_id ter_t::open
Definition at line 466 of file mapdata.h.
Referenced by check(), colorized_ter_name_flags_at(), iuse::crowbar(), and load().
roof
ter_str_id ter_t::roof
Definition at line 471 of file mapdata.h.
Referenced by map::add_roofs(), apply< ter_t >(), map::bash_ter_success(), check(), complete_construction(), map::get_roof(), and load().
src
std::vector<std::pair<ter_str_id, mod_id> > ter_t::src
Definition at line 463 of file mapdata.h.
Referenced by game::extended_description(), and load().
transforms_into
ter_str_id ter_t::transforms_into
Definition at line 470 of file mapdata.h.
Referenced by check(), map::get_ter_transforms_into(), and load().
trap
trap_id ter_t::trap
Definition at line 473 of file mapdata.h.
Referenced by iexamine::ledge(), set_ter_ids(), map::ter_set(), and map::tr_at().
trap_id_str
std::string ter_t::trap_id_str
Definition at line 469 of file mapdata.h.
Referenced by load(), and set_ter_ids().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/mapdata.cpp