Cataclysm BN: jmapgen_int Struct Reference
jmapgen_int Struct Reference
#include <mapgen.h>
Public Member Functions
jmapgen_int (int v)
jmapgen_int (int v, int v2)
jmapgen_int (point p)
jmapgen_int (const JsonObject &jo, const std::string &tag)
Throws as usually if the json is invalid or missing.
jmapgen_int (const JsonObject &jo, const std::string &tag, int def_val, int def_valmax)
Throws is the json is malformed (e.g.
int get () const
Public Attributes
int val
int valmax
Detailed Description
Definition at line 62 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_int() [1/5]
jmapgen_int::jmapgen_int (int v) inline
Definition at line 65 of file mapgen.h.
: val(v), valmax(v) {}
jmapgen_int() [2/5]
jmapgen_int::jmapgen_int (int v, int v2) inline
Definition at line 66 of file mapgen.h.
: val(v), valmax(v2) {}
jmapgen_int() [3/5]
jmapgen_int::jmapgen_int (point p)
Definition at line 630 of file mapgen.cpp.
: val(p.x), valmax(p.y) {}
jmapgen_int() [4/5]
jmapgen_int::jmapgen_int (const JsonObject & jo, const std::string & tag)
Throws as usually if the json is invalid or missing.
Definition at line 632 of file mapgen.cpp.
{
    if( jo.has_array( tag ) ) {
        JsonArray sparray = jo.get_array( tag );
        if( sparray.size() < 1 || sparray.size() > 2 ) {
            jo.throw_error( "invalid data: must be an array of 1 or 2 values", tag );
        }
        val = sparray.get_int( 0 );
        if( sparray.size() == 2 ) {
            valmax = sparray.get_int( 1 );
        } else {
            valmax = val;
        }
    } else {
        val = valmax = jo.get_int( tag );
    }
}
References JsonObject::get_array(), JsonObject::get_int(), JsonArray::get_int(), JsonObject::has_array(), JsonArray::size(), JsonObject::throw_error(), val, and valmax.
jmapgen_int() [5/5]
jmapgen_int::jmapgen_int (const JsonObject & jo, const std::string & tag, int def_val, int def_valmax)
Throws is the json is malformed (e.g.
a string not an integer, but does not throw if the member is just missing (the default values are used instead).
Definition at line 650 of file mapgen.cpp.
    : val( def_val )
    , valmax( def_valmax )
{
    if( jo.has_array( tag ) ) {
        JsonArray sparray = jo.get_array( tag );
        if( sparray.size() > 2 ) {
            jo.throw_error( "invalid data: must be an array of 1 or 2 values", tag );
        }
        if( sparray.size() >= 1 ) {
            val = sparray.get_int( 0 );
        }
        if( sparray.size() >= 2 ) {
            valmax = sparray.get_int( 1 );
        }
    } else if( jo.has_member( tag ) ) {
        val = valmax = jo.get_int( tag );
    }
}
References JsonObject::get_array(), JsonObject::get_int(), JsonArray::get_int(), JsonObject::has_array(), JsonObject::has_member(), JsonArray::size(), JsonObject::throw_error(), val, and valmax.
Member Function Documentation
get()
int jmapgen_int::get () const
Definition at line 671 of file mapgen.cpp.
{
    return val == valmax ? val : rng( val, valmax );
}
References rng(), val, and valmax.
Referenced by VehicleFunction_json::apply(), jmapgen_field::apply(), jmapgen_npc::apply(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_vending_machine::apply(), jmapgen_toilet::apply(), jmapgen_gaspump::apply(), jmapgen_liquid_item::apply(), jmapgen_item_group::apply(), jmapgen_monster_group::apply(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_spawn_item::apply(), jmapgen_trap::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_make_rubble::apply(), jmapgen_computer::apply(), jmapgen_sealed_item::apply(), jmapgen_nested::apply(), jmapgen_setmap::apply(), mapgen_function_json::generate(), jmapgen_setmap::has_vehicle_collision(), and VehicleLocation::pick_point().
Member Data Documentation
val
int jmapgen_int::val
Definition at line 63 of file mapgen.h.
Referenced by jmapgen_faction::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_zone::apply(), common_check_bounds(), get(), jmapgen_int(), jmapgen_objects::load_objects(), jmapgen_place::offset(), and mapgen_function_json_base::setup_setmap().
valmax
int jmapgen_int::valmax
Definition at line 64 of file mapgen.h.
Referenced by jmapgen_faction::apply(), jmapgen_liquid_item::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_zone::apply(), common_check_bounds(), get(), jmapgen_int(), jmapgen_objects::load_objects(), jmapgen_place::offset(), and mapgen_function_json_base::setup_setmap().
The documentation for this struct was generated from the following files:
src/mapgen.h
src/mapgen.cpp