Cataclysm BN: detail::stringifier Struct Reference
detail::stringifier Struct Reference
#include <fmtlib_format-inl.h>
Public Member Functions
template<typename T >
FMT_INLINE std::string operator() (T value) const
std::string operator() (basic_format_arg< format_context >::handle h) const
Detailed Description
Definition at line 2880 of file fmtlib_format-inl.h.
Member Function Documentation
operator()() [1/2]
std::string detail::stringifier::operator() (basic_format_arg< format_context >::handle h) const inline
Definition at line 2884 of file fmtlib_format-inl.h.
{
        memory_buffer buf;
        format_parse_context parse_ctx( {} );
        format_context format_ctx( buffer_appender<char>( buf ), {}, {} );
        h.format( parse_ctx, format_ctx );
        return to_string( buf );
    }
References basic_format_arg< Context >::handle::format(), and to_string().
operator()() [2/2]
template<typename T > FMT_INLINE std::string detail::stringifier::operator() (T value) const inline
Definition at line 2881 of file fmtlib_format-inl.h.
{
        return to_string( value );
    }
References to_string().
The documentation for this struct was generated from the following file:
src/fmtlib_format-inl.h