Cataclysm BN: mongroup Struct Reference
mongroup Struct Reference
#include <mongroup.h>
Public Types
using archive_type_tag = io::object_archive_tag
Public Member Functions
mongroup (const mongroup_id &ptype, const tripoint &ppos, unsigned int prad, unsigned int ppop)
mongroup (const mongroup_id &ptype, const tripoint_om_sm &ppos, unsigned int prad, unsigned int ppop)
mongroup (const std::string &ptype, tripoint ppos, unsigned int prad, unsigned int ppop, tripoint ptarget, int pint, bool pdie, bool phorde, bool pdiff)
mongroup ()=default
bool is_safe () const
bool empty () const
void clear ()
void set_target (const point_om_sm &p)
void wander (const overmap &)
void inc_interest (int inc)
void dec_interest (int dec)
void set_interest (int set)
float avg_speed () const
template<typename Archive >
void io (Archive &)
void deserialize (JsonIn &data)
void deserialize_legacy (JsonIn &json)
void serialize (JsonOut &json) const
Public Attributes
mongroup_id type
tripoint_om_sm pos
unsigned int radius = 1
unsigned int population = 1
tripoint_om_sm target
int interest = 0
bool dying = false
bool horde = false
std::vector< monster > monsters
This property will be ignored if the vector is empty.
std::string horde_behaviour
There are two types of hordes: "city", who try to stick around cities and return to them whenever possible.
bool diffuse = false
Detailed Description
Definition at line 79 of file mongroup.h.
Member Typedef Documentation
archive_type_tag
using mongroup::archive_type_tag = io::object_archive_tag
Definition at line 153 of file mongroup.h.
Constructor & Destructor Documentation
mongroup() [1/4]
mongroup::mongroup (const mongroup_id & ptype, const tripoint & ppos, unsigned int prad, unsigned int ppop) inline
Definition at line 104 of file mongroup.h.
        : type( ptype )
        , pos( ppos )
        , radius( prad )
        , population( ppop ) {
    }
mongroup() [2/4]
mongroup::mongroup (const mongroup_id & ptype, const tripoint_om_sm & ppos, unsigned int prad, unsigned int ppop) inline
Definition at line 111 of file mongroup.h.
                                                     :
        // TODO: fix point types
        mongroup( ptype, ppos.raw(), prad, ppop ) {}
mongroup() [3/4]
mongroup::mongroup (const std::string & ptype, tripoint ppos, unsigned int prad, unsigned int ppop, tripoint ptarget, int pint, bool pdie, bool phorde, bool pdiff) inline
Definition at line 115 of file mongroup.h.
                                                                               :
        type( ptype ), pos( ppos ), radius( prad ), population( ppop ), target( ptarget ),
        interest( pint ), dying( pdie ), horde( phorde ), diffuse( pdiff ) { }
mongroup() [4/4]
mongroup::mongroup () default
Member Function Documentation
avg_speed()
float mongroup::avg_speed () const
Definition at line 60 of file mongroup.cpp.
{
    float avg_speed = 0;
    if( monsters.empty() ) {
        const MonsterGroup &g = type.obj();
        int remaining_frequency = 1000;
        for( auto &elem : g.monsters ) {
            avg_speed += elem.frequency * elem.name.obj().speed;
            remaining_frequency -= elem.frequency;
        }
        if( remaining_frequency > 0 ) {
            avg_speed += g.defaultMonster.obj().speed * remaining_frequency;
        }
        avg_speed /= 1000;
    } else {
        for( auto &it : monsters ) {
            avg_speed += it.type->speed;
        }
        avg_speed /= monsters.size();
    }
    return avg_speed;
}
References avg_speed(), g, monsters, string_id< T >::obj(), and type.
Referenced by avg_speed(), and overmap::move_hordes().
clear()
void mongroup::clear ()
Definition at line 54 of file mongroup.cpp.
{
    population = 0;
    monsters.clear();
}
References monsters, and population.
dec_interest()
void mongroup::dec_interest (int dec) inline
Definition at line 134 of file mongroup.h.
{
        interest -= dec;
        if( interest < 15 ) {
            interest = 15;
        }
    }
References interest.
Referenced by overmap::move_hordes().
deserialize()
void mongroup::deserialize (JsonIn & data)
Definition at line 1127 of file savegame.cpp.
{
    JsonObject jo = data.get_object();
    jo.allow_omitted_members();
    io::JsonObjectInputArchive archive( jo );
    io( archive );
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and io().
Referenced by overmap::load_monster_groups().
deserialize_legacy()
void mongroup::deserialize_legacy (JsonIn & json)
Definition at line 1141 of file savegame.cpp.
{
    json.start_object();
    while( !json.end_object() ) {
        std::string name = json.get_member_name();
        if( name == "type" ) {
            type = mongroup_id( json.get_string() );
        } else if( name == "pos" ) {
            pos.deserialize( json );
        } else if( name == "radius" ) {
            radius = json.get_int();
        } else if( name == "population" ) {
            population = json.get_int();
        } else if( name == "diffuse" ) {
            diffuse = json.get_bool();
        } else if( name == "dying" ) {
            dying = json.get_bool();
        } else if( name == "horde" ) {
            horde = json.get_bool();
        } else if( name == "target" ) {
            target.deserialize( json );
        } else if( name == "interest" ) {
            interest = json.get_int();
        } else if( name == "horde_behaviour" ) {
            horde_behaviour = json.get_string();
        } else if( name == "monsters" ) {
            json.start_array();
            while( !json.end_array() ) {
                monster new_monster;
                new_monster.deserialize( json );
                monsters.push_back( new_monster );
            }
        }
    }
}
References coords::coord_point< Point, Origin, Scale >::deserialize(), monster::deserialize(), diffuse, dying, JsonIn::end_array(), JsonIn::end_object(), JsonIn::get_bool(), JsonIn::get_int(), JsonIn::get_member_name(), JsonIn::get_string(), horde, horde_behaviour, interest, monsters, om_direction::name(), population, pos, radius, JsonIn::start_array(), JsonIn::start_object(), target, and type.
Referenced by overmap::load_legacy_monstergroups().
empty()
bool mongroup::empty () const
Definition at line 49 of file mongroup.cpp.
{
    return population <= 0 && monsters.empty();
}
References monsters, and population.
Referenced by overmapbuffer::groups_at(), and overmap::process_mongroups().
inc_interest()
void mongroup::inc_interest (int inc) inline
Definition at line 128 of file mongroup.h.
{
        interest += inc;
        if( interest > 100 ) {
            interest = 100;
        }
    }
References interest.
Referenced by overmap::signal_hordes().
io()
template<typename Archive > void mongroup::io (Archive & archive)
Definition at line 1112 of file savegame.cpp.
{
    archive.io( "type", type );
    archive.io( "pos", pos, tripoint_om_sm() );
    archive.io( "radius", radius, 1u );
    archive.io( "population", population, 1u );
    archive.io( "diffuse", diffuse, false );
    archive.io( "dying", dying, false );
    archive.io( "horde", horde, false );
    archive.io( "target", target, tripoint_om_sm() );
    archive.io( "interest", interest, 0 );
    archive.io( "horde_behaviour", horde_behaviour, io::empty_default_tag() );
    archive.io( "monsters", monsters, io::empty_default_tag() );
}
References diffuse, dying, horde, horde_behaviour, interest, monsters, population, pos, radius, target, and type.
Referenced by deserialize(), and serialize().
is_safe()
bool mongroup::is_safe () const
Definition at line 44 of file mongroup.cpp.
{
    return type.obj().is_safe;
}
References MonsterGroup::is_safe, string_id< T >::obj(), and type.
serialize()
void mongroup::serialize (JsonOut & json) const
Definition at line 1135 of file savegame.cpp.
{
    io::JsonObjectOutputArchive archive( json );
    const_cast<mongroup *>( this )->io( archive );
}
References io().
set_interest()
void mongroup::set_interest (int set) inline
Definition at line 140 of file mongroup.h.
{
        if( set < 15 ) {
            set = 15;
        }
        if( set > 100 ) {
            set = 100;
        }
        interest = set;
    }
References interest.
Referenced by overmap::signal_hordes().
set_target()
void mongroup::set_target (const point_om_sm & p) inline
Definition at line 123 of file mongroup.h.
{
        target.x() = p.x();
        target.y() = p.y();
    }
References target, coords::coord_point< Point, Origin, Scale >::x(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by overmap::signal_hordes().
wander()
void mongroup::wander (const overmap & om)
Definition at line 2171 of file overmap.cpp.
{
    const city *target_city = nullptr;
    int target_distance = 0;
    if( horde_behaviour == "city" ) {
        // Find a nearby city to return to..
        for( const city &check_city : om.cities ) {
            // Check if this is the nearest city so far.
            int distance = rl_dist( project_to<coords::sm>( check_city.pos ),
                                    pos.xy() );
            if( !target_city || distance < target_distance ) {
                target_distance = distance;
                target_city = &check_city;
            }
        }
    }
    if( target_city ) {
        // TODO: somehow use the same algorithm that distributes zombie
        // density at world gen to spread the hordes over the actual
        // city, rather than the center city tile
        target.x() = target_city->pos.x() * 2 + rng( -target_city->size * 2, target_city->size * 2 );
        target.y() = target_city->pos.y() * 2 + rng( -target_city->size * 2, target_city->size * 2 );
        interest = 100;
    } else {
        target.x() = pos.x() + rng( -10, 10 );
        target.y() = pos.y() + rng( -10, 10 );
        interest = 30;
    }
}
References horde_behaviour, interest, coords::om, pos, city::pos, rl_dist(), rng(), city::size, target, coords::coord_point< Point, Origin, Scale >::x(), coords::coord_point< Point, Origin, Scale >::xy(), and coords::coord_point< Point, Origin, Scale >::y().
Referenced by overmap::move_hordes(), and overmap::place_mongroups().
Member Data Documentation
diffuse
bool mongroup::diffuse = false
Definition at line 103 of file mongroup.h.
Referenced by deserialize_legacy(), io(), and mongroup_hash::operator()().
dying
bool mongroup::dying = false
Definition at line 88 of file mongroup.h.
Referenced by deserialize_legacy(), io(), mongroup_hash::operator()(), and overmap::process_mongroups().
horde
bool mongroup::horde = false
Definition at line 89 of file mongroup.h.
Referenced by deserialize_legacy(), io(), overmap::move_hordes(), mongroup_hash::operator()(), overmap::place_mongroups(), and overmap::signal_hordes().
horde_behaviour
std::string mongroup::horde_behaviour
There are two types of hordes: "city", who try to stick around cities and return to them whenever possible.
And "roam", who roam around the map randomly, not taking care to return anywhere.
Definition at line 102 of file mongroup.h.
Referenced by deserialize_legacy(), io(), overmap::move_hordes(), mongroup_hash::operator()(), and wander().
interest
int mongroup::interest = 0
Definition at line 87 of file mongroup.h.
Referenced by dec_interest(), deserialize_legacy(), inc_interest(), io(), overmap::move_hordes(), mongroup_hash::operator()(), set_interest(), overmap::signal_hordes(), and wander().
monsters
std::vector<monster> mongroup::monsters
This property will be ignored if the vector is empty.
Otherwise it will keep track of the individual monsters that are contained in this horde, and the population property will be ignored instead.
Definition at line 95 of file mongroup.h.
Referenced by avg_speed(), clear(), deserialize_legacy(), empty(), io(), and overmap::move_hordes().
population
unsigned int mongroup::population = 1
Definition at line 85 of file mongroup.h.
Referenced by overmap::add_mon_group(), clear(), deserialize_legacy(), empty(), io(), mongroup_hash::operator()(), and overmap::process_mongroups().
pos
tripoint_om_sm mongroup::pos
Definition at line 83 of file mongroup.h.
Referenced by overmap::add_mon_group(), deserialize_legacy(), io(), overmap::load_monster_groups(), overmap::mongroup_check(), overmap::move_hordes(), overmap::save_monster_groups(), overmap::signal_hordes(), and wander().
radius
unsigned int mongroup::radius = 1
Definition at line 84 of file mongroup.h.
Referenced by overmap::add_mon_group(), deserialize_legacy(), io(), mongroup_hash::operator()(), and overmap::process_mongroups().
target
tripoint_om_sm mongroup::target
Definition at line 86 of file mongroup.h.
Referenced by deserialize_legacy(), overmap_ui::draw_ascii(), io(), overmap::move_hordes(), mongroup_hash::operator()(), set_target(), overmap::signal_hordes(), and wander().
type
mongroup_id mongroup::type
Definition at line 80 of file mongroup.h.
Referenced by avg_speed(), deserialize_legacy(), io(), is_safe(), and mongroup_hash::operator()().
The documentation for this struct was generated from the following files:
src/mongroup.h
src/mongroup.cpp
src/overmap.cpp
src/savegame.cpp