Cataclysm BN: debug_menu_state Struct Reference
debug_menu_state Struct Reference
#include <uistate.h>
Public Member Functions
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Public Attributes
wisheffect_state effect
Detailed Description
Definition at line 66 of file uistate.h.
Member Function Documentation
deserialize()
void debug_menu_state::deserialize (const JsonObject & jo)
Definition at line 4255 of file savegame_json.cpp.
{
    jo.read( "effect", effect );
}
References JsonObject::read().
serialize()
void debug_menu_state::serialize (JsonOut & json) const
Definition at line 4248 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "effect", effect );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
effect
wisheffect_state debug_menu_state::effect
Definition at line 68 of file uistate.h.
Referenced by debug_menu::effect_edit_callback::add_effect_submenu(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_body_part(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_duration(), debug_menu::anonymous_namespace{wisheffect.cpp}::query_intensity(), debug_menu::effect_select_callback::refresh(), and debug_menu::anonymous_namespace{wisheffect.cpp}::toggle_effect_force().
The documentation for this struct was generated from the following files:
src/uistate.h
src/savegame_json.cpp