Cataclysm BN: computer_failure Struct Reference
computer_failure Struct Reference
#include <computer.h>
Public Member Functions
computer_failure ()
computer_failure (computer_failure_type t)
void serialize (JsonOut &jout) const
void deserialize (JsonIn &jin)
Static Public Member Functions
static computer_failure from_json (const JsonObject &jo)
Public Attributes
computer_failure_type type
Detailed Description
Definition at line 96 of file computer.h.
Constructor & Destructor Documentation
computer_failure() [1/2]
computer_failure::computer_failure ()
Definition at line 45 of file computer.cpp.
    : type( COMPFAIL_NULL )
{
}
Referenced by from_json().
computer_failure() [2/2]
computer_failure::computer_failure (computer_failure_type t) inline
Definition at line 100 of file computer.h.
                                                : type( t ) {
    }
Member Function Documentation
deserialize()
void computer_failure::deserialize (JsonIn & jin)
Definition at line 58 of file computer.cpp.
{
    const JsonObject jo = jin.get_object();
    type = jo.get_enum_value<computer_failure_type>( "action" );
}
References JsonObject::get_enum_value(), JsonIn::get_object(), and type.
from_json()
computer_failure computer_failure::from_json (const JsonObject & jo) static
Definition at line 392 of file computer.cpp.
{
    const computer_failure_type type = jo.get_enum_value<computer_failure_type>( "action" );
    return computer_failure( type );
}
References computer_failure(), JsonObject::get_enum_value(), and type.
Referenced by jmapgen_computer::jmapgen_computer().
serialize()
void computer_failure::serialize (JsonOut & jout) const
Definition at line 50 of file computer.cpp.
{
    jout.start_object();
    jout.member( "action" );
    jout.write_as_string( type );
    jout.end_object();
}
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), type, and JsonOut::write_as_string().
Member Data Documentation
type
computer_failure_type computer_failure::type
Definition at line 97 of file computer.h.
Referenced by computer_session::activate_random_failure(), deserialize(), from_json(), and serialize().
The documentation for this struct was generated from the following files:
src/computer.h
src/computer.cpp