Cataclysm BN: formatter< bytes > Struct Reference
formatter< bytes > Struct Reference
#include <fmtlib_format.h>
Public Member Functions
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (bytes b, FormatContext &ctx) -> decltype(ctx.out())
Private Attributes
detail::dynamic_format_specs< char > specs_
Detailed Description
Definition at line 4123 of file fmtlib_format.h.
Member Function Documentation
format()
template<typename FormatContext > auto formatter< bytes >::format (bytes b, FormatContext & ctx) -> decltype(ctx.out()) inline
Definition at line 4139 of file fmtlib_format.h.
{
            detail::handle_dynamic_spec<detail::width_checker>( specs_.width,
                    specs_.width_ref, ctx );
            detail::handle_dynamic_spec<detail::precision_checker>(
                specs_.precision, specs_.precision_ref, ctx );
            return detail::write_bytes( ctx.out(), b.data_, specs_ );
        }
References b, basic_format_specs< Char >::precision, detail::dynamic_format_specs< Char >::precision_ref, basic_format_specs< Char >::width, detail::dynamic_format_specs< Char >::width_ref, and detail::write_bytes().
parse()
template<typename ParseContext > FMT_CONSTEXPR auto formatter< bytes >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 4129 of file fmtlib_format.h.
{
            using handler_type = detail::dynamic_specs_handler<ParseContext>;
            detail::specs_checker<handler_type> handler( handler_type( specs_, ctx ),
                    detail::type::string_type );
            auto it = parse_format_specs( ctx.begin(), ctx.end(), handler );
            detail::check_string_type_spec( specs_.type, ctx.error_handler() );
            return it;
        }
References detail::check_string_type_spec(), detail::parse_format_specs(), detail::string_type, and basic_format_specs< Char >::type.
Member Data Documentation
specs_
detail::dynamic_format_specs<char> formatter< bytes >::specs_ private
Definition at line 4125 of file fmtlib_format.h.
The documentation for this struct was generated from the following file:
src/fmtlib_format.h