Cataclysm BN: extended_photo_def Struct Reference
extended_photo_def Struct Reference
Public Member Functions
extended_photo_def ()=default
void deserialize (JsonIn &jsin) override
void serialize (JsonOut &jsout) const override
Public Member Functions inherited from JsonDeserializer
virtual ~JsonDeserializer ()=default
JsonDeserializer ()=default
JsonDeserializer (JsonDeserializer &&)=default
JsonDeserializer (const JsonDeserializer &)=default
JsonDeserializer & operator= (JsonDeserializer &&)=default
JsonDeserializer & operator= (const JsonDeserializer &)=default
Public Member Functions inherited from JsonSerializer
virtual ~JsonSerializer ()=default
JsonSerializer ()=default
JsonSerializer (JsonSerializer &&)=default
JsonSerializer (const JsonSerializer &)=default
JsonSerializer & operator= (JsonSerializer &&)=default
JsonSerializer & operator= (const JsonSerializer &)=default
Public Attributes
int quality
std::string name
std::string description
Detailed Description
Definition at line 6700 of file iuse.cpp.
Constructor & Destructor Documentation
extended_photo_def()
extended_photo_def::extended_photo_def () default
Member Function Documentation
deserialize()
void extended_photo_def::deserialize (JsonIn & jsin) inline override virtual
Implements JsonDeserializer.
Definition at line 6706 of file iuse.cpp.
{
        JsonObject obj = jsin.get_object();
        quality = obj.get_int( "quality" );
        name = obj.get_string( "name" );
        description = obj.get_string( "description" );
    }
References description, JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), and name.
serialize()
void extended_photo_def::serialize (JsonOut & jsout) const inline override virtual
Implements JsonSerializer.
Definition at line 6713 of file iuse.cpp.
{
        jsout.start_object();
        jsout.member( "quality", quality );
        jsout.member( "name", name );
        jsout.member( "description", description );
        jsout.end_object();
    }
References description, JsonOut::end_object(), JsonOut::member(), name, and JsonOut::start_object().
Member Data Documentation
description
std::string extended_photo_def::description
Definition at line 6703 of file iuse.cpp.
Referenced by deserialize(), photo_def_for_camera_point(), and serialize().
name
std::string extended_photo_def::name
Definition at line 6702 of file iuse.cpp.
Referenced by iuse::camera(), deserialize(), photo_def_for_camera_point(), and serialize().
quality
int extended_photo_def::quality
Definition at line 6701 of file iuse.cpp.
Referenced by iuse::camera().
The documentation for this struct was generated from the following file:
src/iuse.cpp