Cataclysm BN: field_type Struct Reference
field_type Struct Reference
#include <field_type.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check () const
const field_intensity_level & get_intensity_level (int level=0) const
std::string get_name (int level=0) const
uint32_t get_codepoint (int level=0) const
std::string get_symbol (int level=0) const
nc_color get_color (int level=0) const
bool get_dangerous (int level=0) const
bool get_transparent (int level=0) const
int get_move_cost (int level=0) const
int get_extra_radiation_min (int level=0) const
int get_extra_radiation_max (int level=0) const
int get_radiation_hurt_damage_min (int level=0) const
int get_radiation_hurt_damage_max (int level=0) const
std::string get_radiation_hurt_message (int level=0) const
int get_intensity_upgrade_chance (int level=0) const
time_duration get_intensity_upgrade_duration (int level=0) const
int get_monster_spawn_chance (int level=0) const
int get_monster_spawn_count (int level=0) const
int get_monster_spawn_radius (int level=0) const
mongroup_id get_monster_spawn_group (int level=0) const
float get_light_emitted (int level=0) const
float get_local_light_override (int level=0) const
float get_translucency (int level=0) const
int get_convection_temperature_mod (int level=0) const
bool is_dangerous () const
bool is_transparent () const
int get_max_intensity () const
Static Public Member Functions
static size_t count ()
Public Attributes
field_type_str_id id
bool was_loaded = false
std::string wandering_field_id = "fd_null"
int legacy_enum_id = -1
std::vector< field_intensity_level > intensity_levels
time_duration underwater_age_speedup = 0_turns
time_duration outdoor_age_speedup = 0_turns
int decay_amount_factor = 0
int percent_spread = 0
int apply_slime_factor = 0
int gas_absorption_factor = 0
bool is_splattering = false
bool dirty_transparency_cache = false
bool has_fire = false
bool has_acid = false
bool has_elec = false
bool has_fume = false
description_affix desc_affix = description_affix::DESCRIPTION_AFFIX_NUM
map_bash_info bash_info
std::tuple< int, std::string, time_duration, std::string > npc_complain_data
std::vector< trait_id > immunity_data_traits
std::vector< std::pair< body_part, int > > immunity_data_body_part_env_resistance
std::set< mtype_id > immune_mtypes
int priority = 0
time_duration half_life = 0_turns
phase_id phase = PNULL
bool accelerated_decay = false
bool display_items = true
bool display_field = false
field_type_id wandering_field
std::string looks_like
fields::stacking_type stacking_type = fields::stacking_type::intensity
Detailed Description
Definition at line 135 of file field_type.h.
Member Function Documentation
check()
void field_type::check () const
Definition at line 288 of file field_type.cpp.
{
    int i = 0;
    for( auto &intensity_level : intensity_levels ) {
        i++;
        if( intensity_level.name.empty() ) {
            debugmsg( "Intensity level %d defined for field type \"%s\" has empty name.", i, id.c_str() );
        }
    }
    bash_info.check( id.str(), map_bash_info::map_object_type::field );
}
References bash_info, map_bash_info::check(), debugmsg, map_bash_info::field, and intensity_levels.
count()
size_t field_type::count () static
Definition at line 301 of file field_type.cpp.
{
    return all_field_types.size();
}
References anonymous_namespace{field_type.cpp}::all_field_types.
Referenced by editmap::edit_fld(), and editmap::setup_fmenu().
finalize()
void field_type::finalize ()
Definition at line 277 of file field_type.cpp.
{
    wandering_field = field_type_id( wandering_field_id );
    wandering_field_id.clear();
    for( const mtype_id &m_id : immune_mtypes ) {
        if( !m_id.is_valid() ) {
            debugmsg( "Invalid mtype_id %s in immune_mtypes for field %s.", m_id.c_str(), id.c_str() );
        }
    }
}
References debugmsg, immune_mtypes, wandering_field, and wandering_field_id.
get_codepoint()
uint32_t field_type::get_codepoint (int level = 0) const inline
Definition at line 192 of file field_type.h.
{
            return get_intensity_level( level ).symbol;
        }
References get_intensity_level(), and field_intensity_level::symbol.
get_color()
nc_color field_type::get_color (int level = 0) const inline
Definition at line 198 of file field_type.h.
{
            return get_intensity_level( level ).color;
        }
References field_intensity_level::color, and get_intensity_level().
Referenced by field_entry::color(), and editmap::update_fmenu_entry().
get_convection_temperature_mod()
int field_type::get_convection_temperature_mod (int level = 0) const inline
Definition at line 252 of file field_type.h.
{
            return get_intensity_level( level ).convection_temperature_mod;
        }
References field_intensity_level::convection_temperature_mod, and get_intensity_level().
Referenced by field_entry::convection_temperature_mod(), and get_convection_temperature().
get_dangerous()
bool field_type::get_dangerous (int level = 0) const inline
Definition at line 201 of file field_type.h.
{
            return get_intensity_level( level ).dangerous;
        }
References field_intensity_level::dangerous, and get_intensity_level().
get_extra_radiation_max()
int field_type::get_extra_radiation_max (int level = 0) const inline
Definition at line 213 of file field_type.h.
{
            return get_intensity_level( level ).extra_radiation_max;
        }
References field_intensity_level::extra_radiation_max, and get_intensity_level().
Referenced by field_entry::extra_radiation_max().
get_extra_radiation_min()
int field_type::get_extra_radiation_min (int level = 0) const inline
Definition at line 210 of file field_type.h.
{
            return get_intensity_level( level ).extra_radiation_min;
        }
References field_intensity_level::extra_radiation_min, and get_intensity_level().
Referenced by field_entry::extra_radiation_min().
get_intensity_level()
const field_intensity_level & field_type::get_intensity_level (int level = 0) const
Definition at line 130 of file field_type.cpp.
{
    if( level < 0 || static_cast<size_t>( level ) >= intensity_levels.size() ) {
        // level + 1 for the original intensity number
        debugmsg( "Unknown intensity level %d for field type %s.", level + 1, id.str() );
        return intensity_levels.back();
    }
    return intensity_levels[level];
}
References debugmsg, and intensity_levels.
Referenced by field_entry::field_effects(), get_codepoint(), get_color(), get_convection_temperature_mod(), get_dangerous(), get_extra_radiation_max(), get_extra_radiation_min(), get_intensity_upgrade_chance(), get_intensity_upgrade_duration(), get_light_emitted(), get_local_light_override(), get_monster_spawn_chance(), get_monster_spawn_count(), get_monster_spawn_group(), get_monster_spawn_radius(), get_move_cost(), get_name(), get_radiation_hurt_damage_max(), get_radiation_hurt_damage_min(), get_radiation_hurt_message(), get_symbol(), get_translucency(), get_transparent(), and map::spread_gas().
get_intensity_upgrade_chance()
int field_type::get_intensity_upgrade_chance (int level = 0) const inline
Definition at line 225 of file field_type.h.
{
            return get_intensity_level( level ).intensity_upgrade_chance;
        }
References get_intensity_level(), and field_intensity_level::intensity_upgrade_chance.
Referenced by field_entry::intensity_upgrade_chance().
get_intensity_upgrade_duration()
time_duration field_type::get_intensity_upgrade_duration (int level = 0) const inline
Definition at line 228 of file field_type.h.
{
            return get_intensity_level( level ).intensity_upgrade_duration;
        }
References get_intensity_level(), and field_intensity_level::intensity_upgrade_duration.
Referenced by field_entry::intensity_upgrade_duration().
get_light_emitted()
float field_type::get_light_emitted (int level = 0) const inline
Definition at line 243 of file field_type.h.
{
            return get_intensity_level( level ).light_emitted;
        }
References get_intensity_level(), and field_intensity_level::light_emitted.
Referenced by field_entry::light_emitted().
get_local_light_override()
float field_type::get_local_light_override (int level = 0) const inline
Definition at line 246 of file field_type.h.
{
            return get_intensity_level( level ).local_light_override;
        }
References get_intensity_level(), and field_intensity_level::local_light_override.
Referenced by field_entry::local_light_override().
get_max_intensity()
int field_type::get_max_intensity () const inline
Definition at line 268 of file field_type.h.
{
            return intensity_levels.size();
        }
References intensity_levels.
Referenced by map::add_field(), editmap::edit_fld(), field_entry::get_max_field_intensity(), explosion_iuse::load(), and vehicle::noise_and_smoke().
get_monster_spawn_chance()
int field_type::get_monster_spawn_chance (int level = 0) const inline
Definition at line 231 of file field_type.h.
{
            return get_intensity_level( level ).monster_spawn_chance;
        }
References get_intensity_level(), and field_intensity_level::monster_spawn_chance.
Referenced by field_entry::monster_spawn_chance().
get_monster_spawn_count()
int field_type::get_monster_spawn_count (int level = 0) const inline
Definition at line 234 of file field_type.h.
{
            return get_intensity_level( level ).monster_spawn_count;
        }
References get_intensity_level(), and field_intensity_level::monster_spawn_count.
Referenced by field_entry::monster_spawn_count().
get_monster_spawn_group()
mongroup_id field_type::get_monster_spawn_group (int level = 0) const inline
Definition at line 240 of file field_type.h.
{
            return get_intensity_level( level ).monster_spawn_group;
        }
References get_intensity_level(), and field_intensity_level::monster_spawn_group.
Referenced by field_entry::monster_spawn_group().
get_monster_spawn_radius()
int field_type::get_monster_spawn_radius (int level = 0) const inline
Definition at line 237 of file field_type.h.
{
            return get_intensity_level( level ).monster_spawn_radius;
        }
References get_intensity_level(), and field_intensity_level::monster_spawn_radius.
Referenced by field_entry::monster_spawn_radius().
get_move_cost()
int field_type::get_move_cost (int level = 0) const inline
Definition at line 207 of file field_type.h.
{
            return get_intensity_level( level ).move_cost;
        }
References get_intensity_level(), and field_intensity_level::move_cost.
Referenced by field_entry::move_cost().
get_name()
std::string field_type::get_name (int level = 0) const inline
Definition at line 189 of file field_type.h.
{
            return get_intensity_level( level ).name.translated();
        }
References get_intensity_level(), field_intensity_level::name, and translation::translated().
Referenced by editmap::edit_fld(), field_entry::name(), and editmap::update_fmenu_entry().
get_radiation_hurt_damage_max()
int field_type::get_radiation_hurt_damage_max (int level = 0) const inline
Definition at line 219 of file field_type.h.
{
            return get_intensity_level( level ).radiation_hurt_damage_max;
        }
References get_intensity_level(), and field_intensity_level::radiation_hurt_damage_max.
Referenced by field_entry::radiation_hurt_damage_max().
get_radiation_hurt_damage_min()
int field_type::get_radiation_hurt_damage_min (int level = 0) const inline
Definition at line 216 of file field_type.h.
{
            return get_intensity_level( level ).radiation_hurt_damage_min;
        }
References get_intensity_level(), and field_intensity_level::radiation_hurt_damage_min.
Referenced by field_entry::radiation_hurt_damage_min().
get_radiation_hurt_message()
std::string field_type::get_radiation_hurt_message (int level = 0) const inline
Definition at line 222 of file field_type.h.
{
            return get_intensity_level( level ).radiation_hurt_message.translated();
        }
References get_intensity_level(), field_intensity_level::radiation_hurt_message, and translation::translated().
Referenced by field_entry::radiation_hurt_message().
get_symbol()
std::string field_type::get_symbol (int level = 0) const inline
Definition at line 195 of file field_type.h.
{
            return utf32_to_utf8( get_intensity_level( level ).symbol );
        }
References get_intensity_level(), symbol(), and utf32_to_utf8().
Referenced by map::draw_maptile(), field_entry::symbol(), and editmap::update_fmenu_entry().
get_translucency()
float field_type::get_translucency (int level = 0) const inline
Definition at line 249 of file field_type.h.
{
            return get_intensity_level( level ).translucency;
        }
References get_intensity_level(), and field_intensity_level::translucency.
Referenced by field_entry::translucency().
get_transparent()
bool field_type::get_transparent (int level = 0) const inline
Definition at line 204 of file field_type.h.
{
            return get_intensity_level( level ).transparent;
        }
References get_intensity_level(), and field_intensity_level::transparent.
Referenced by field_entry::is_transparent(), and map::process_fields_in_submap().
is_dangerous()
bool field_type::is_dangerous () const inline
Definition at line 256 of file field_type.h.
{
            return std::any_of( intensity_levels.begin(), intensity_levels.end(),
            []( const field_intensity_level & elem ) {
                return elem.dangerous;
            } );
        }
References intensity_levels.
Referenced by map::add_field(), and field_entry::is_dangerous().
is_transparent()
bool field_type::is_transparent () const inline
Definition at line 262 of file field_type.h.
{
            return std::all_of( intensity_levels.begin(), intensity_levels.end(),
            []( const field_intensity_level & elem ) {
                return elem.transparent;
            } );
        }
References intensity_levels.
Referenced by map::add_field().
load()
void field_type::load (const JsonObject & jo, const std::string & src)
Definition at line 140 of file field_type.cpp.
{
    optional( jo, was_loaded, "legacy_enum_id", legacy_enum_id, -1 );
    for( const JsonObject jao : jo.get_array( "intensity_levels" ) ) {
        field_intensity_level intensity_level;
        field_intensity_level fallback_intensity_level = !intensity_levels.empty() ? intensity_levels.back()
                : intensity_level;
        optional( jao, was_loaded, "name", intensity_level.name, fallback_intensity_level.name );
        optional( jao, was_loaded, "sym", intensity_level.symbol, unicode_codepoint_from_symbol_reader,
                  fallback_intensity_level.symbol );
        intensity_level.color = jao.has_member( "color" ) ? color_from_string( jao.get_string( "color" ) ) :
                                fallback_intensity_level.color;
        optional( jao, was_loaded, "transparent", intensity_level.transparent,
                  fallback_intensity_level.transparent );
        optional( jao, was_loaded, "dangerous", intensity_level.dangerous,
                  fallback_intensity_level.dangerous );
        optional( jao, was_loaded, "move_cost", intensity_level.move_cost,
                  fallback_intensity_level.move_cost );
        optional( jao, was_loaded, "extra_radiation_min", intensity_level.extra_radiation_min,
                  fallback_intensity_level.extra_radiation_min );
        optional( jao, was_loaded, "extra_radiation_max", intensity_level.extra_radiation_max,
                  fallback_intensity_level.extra_radiation_max );
        optional( jao, was_loaded, "radiation_hurt_damage_min", intensity_level.radiation_hurt_damage_min,
                  fallback_intensity_level.radiation_hurt_damage_min );
        optional( jao, was_loaded, "radiation_hurt_damage_max", intensity_level.radiation_hurt_damage_max,
                  fallback_intensity_level.radiation_hurt_damage_max );
        optional( jao, was_loaded, "radiation_hurt_message", intensity_level.radiation_hurt_message,
                  fallback_intensity_level.radiation_hurt_message );
        optional( jao, was_loaded, "intensity_upgrade_chance", intensity_level.intensity_upgrade_chance,
                  fallback_intensity_level.intensity_upgrade_chance );
        optional( jao, was_loaded, "intensity_upgrade_duration", intensity_level.intensity_upgrade_duration,
                  fallback_intensity_level.intensity_upgrade_duration );
        optional( jao, was_loaded, "monster_spawn_chance", intensity_level.monster_spawn_chance,
                  fallback_intensity_level.monster_spawn_chance );
        optional( jao, was_loaded, "monster_spawn_count", intensity_level.monster_spawn_count,
                  fallback_intensity_level.monster_spawn_count );
        optional( jao, was_loaded, "monster_spawn_radius", intensity_level.monster_spawn_radius,
                  fallback_intensity_level.monster_spawn_radius );
        optional( jao, was_loaded, "monster_spawn_group", intensity_level.monster_spawn_group,
                  fallback_intensity_level.monster_spawn_group );
        optional( jao, was_loaded, "light_emitted", intensity_level.light_emitted,
                  fallback_intensity_level.light_emitted );
        optional( jao, was_loaded, "light_override", intensity_level.local_light_override,
                  fallback_intensity_level.local_light_override );
        optional( jao, was_loaded, "translucency", intensity_level.translucency,
                  fallback_intensity_level.translucency );
        optional( jao, was_loaded, "convection_temperature_mod", intensity_level.convection_temperature_mod,
                  fallback_intensity_level.convection_temperature_mod );
        if( jao.has_array( "effects" ) ) {
            for( const JsonObject joe : jao.get_array( "effects" ) ) {
                field_effect fe;
                mandatory( joe, was_loaded, "effect_id", fe.id );
                optional( joe, was_loaded, "min_duration", fe.min_duration );
                optional( joe, was_loaded, "max_duration", fe.max_duration );
                optional( joe, was_loaded, "intensity", fe.intensity );
                optional( joe, was_loaded, "body_part", fe.bp );
                optional( joe, was_loaded, "is_environmental", fe.is_environmental );
                optional( joe, was_loaded, "immune_in_vehicle", fe.immune_in_vehicle );
                optional( joe, was_loaded, "immune_inside_vehicle", fe.immune_inside_vehicle );
                optional( joe, was_loaded, "immune_outside_vehicle", fe.immune_outside_vehicle );
                optional( joe, was_loaded, "chance_in_vehicle", fe.chance_in_vehicle );
                optional( joe, was_loaded, "chance_inside_vehicle", fe.chance_inside_vehicle );
                optional( joe, was_loaded, "chance_outside_vehicle", fe.chance_outside_vehicle );
                optional( joe, was_loaded, "message", fe.message );
                optional( joe, was_loaded, "message_npc", fe.message_npc );
                const auto game_message_type_reader = enum_flags_reader<game_message_type> { "game message types" };
                optional( joe, was_loaded, "message_type", fe.env_message_type, game_message_type_reader );
                intensity_level.field_effects.emplace_back( fe );
            }
        } else {
            // Use effects from previous intensity level
            intensity_level.field_effects = fallback_intensity_level.field_effects;
        }
        optional( jao, was_loaded, "scent_neutralization", intensity_level.scent_neutralization,
                  fallback_intensity_level.scent_neutralization );
        intensity_levels.emplace_back( intensity_level );
    }
    if( intensity_levels.empty() ) {
        jo.throw_error( "No intensity levels defined for field type", "id" );
    }
    if( jo.has_object( "npc_complain" ) ) {
        JsonObject joc = jo.get_object( "npc_complain" );
        int chance;
        std::string issue;
        time_duration duration;
        std::string speech;
        optional( joc, was_loaded, "chance", chance, 0 );
        optional( joc, was_loaded, "issue", issue );
        optional( joc, was_loaded, "duration", duration, 0_turns );
        optional( joc, was_loaded, "speech", speech );
        npc_complain_data = std::make_tuple( chance, issue, duration, speech );
    }
    JsonObject jid = jo.get_object( "immunity_data" );
    for( const std::string id : jid.get_array( "traits" ) ) {
        immunity_data_traits.emplace_back( id );
    }
    for( JsonArray jao : jid.get_array( "body_part_env_resistance" ) ) {
        immunity_data_body_part_env_resistance.emplace_back( std::make_pair( get_body_part_token(
                    jao.get_string( 0 ) ), jao.get_int( 1 ) ) );
    }
    optional( jo, was_loaded, "immune_mtypes", immune_mtypes );
    optional( jo, was_loaded, "underwater_age_speedup", underwater_age_speedup, 0_turns );
    optional( jo, was_loaded, "outdoor_age_speedup", outdoor_age_speedup, 0_turns );
    optional( jo, was_loaded, "decay_amount_factor", decay_amount_factor, 0 );
    optional( jo, was_loaded, "percent_spread", percent_spread, 0 );
    optional( jo, was_loaded, "apply_slime_factor", apply_slime_factor, 0 );
    optional( jo, was_loaded, "gas_absorption_factor", gas_absorption_factor, 0 );
    optional( jo, was_loaded, "is_splattering", is_splattering, false );
    optional( jo, was_loaded, "dirty_transparency_cache", dirty_transparency_cache, false );
    optional( jo, was_loaded, "has_fire", has_fire, false );
    optional( jo, was_loaded, "has_acid", has_acid, false );
    optional( jo, was_loaded, "has_elec", has_elec, false );
    optional( jo, was_loaded, "has_fume", has_fume, false );
    optional( jo, was_loaded, "priority", priority, 0 );
    optional( jo, was_loaded, "half_life", half_life, 0_turns );
    const auto description_affix_reader = enum_flags_reader<description_affix> { "description affixes" };
    optional( jo, was_loaded, "description_affix", desc_affix, description_affix_reader,
              description_affix::DESCRIPTION_AFFIX_IN );
    if( jo.has_member( "phase" ) ) {
        phase = jo.get_enum_value<phase_id>( "phase", PNULL );
    }
    const auto stacking_type_reader = enum_flags_reader<fields::stacking_type> { "field stacking types" };
    optional( jo, was_loaded, "stacking_type", stacking_type, stacking_type_reader );
    optional( jo, was_loaded, "accelerated_decay", accelerated_decay, false );
    optional( jo, was_loaded, "display_items", display_items, true );
    optional( jo, was_loaded, "display_field", display_field, false );
    optional( jo, was_loaded, "wandering_field", wandering_field_id, "fd_null" );
    optional( jo, was_loaded, "bash", bash_info );
    if( was_loaded && jo.has_member( "copy-from" ) && looks_like.empty() ) {
        looks_like = jo.get_string( "copy-from" );
    }
    jo.read( "looks_like", looks_like );
}
References accelerated_decay, apply_slime_factor, bash_info, field_effect::bp, field_effect::chance_in_vehicle, field_effect::chance_inside_vehicle, field_effect::chance_outside_vehicle, field_intensity_level::color, color_from_string(), field_intensity_level::convection_temperature_mod, field_intensity_level::dangerous, decay_amount_factor, desc_affix, DESCRIPTION_AFFIX_IN, dirty_transparency_cache, display_field, display_items, field_effect::env_message_type, field_intensity_level::extra_radiation_max, field_intensity_level::extra_radiation_min, field_intensity_level::field_effects, gas_absorption_factor, JsonObject::get_array(), get_body_part_token(), JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), half_life, has_acid, has_elec, has_fire, has_fume, JsonObject::has_member(), JsonObject::has_object(), field_effect::id, field_effect::immune_in_vehicle, field_effect::immune_inside_vehicle, immune_mtypes, field_effect::immune_outside_vehicle, immunity_data_body_part_env_resistance, immunity_data_traits, field_effect::intensity, intensity_levels, field_intensity_level::intensity_upgrade_chance, field_intensity_level::intensity_upgrade_duration, field_effect::is_environmental, is_splattering, legacy_enum_id, field_intensity_level::light_emitted, field_intensity_level::local_light_override, looks_like, mandatory(), field_effect::max_duration, field_effect::message, field_effect::message_npc, field_effect::min_duration, field_intensity_level::monster_spawn_chance, field_intensity_level::monster_spawn_count, field_intensity_level::monster_spawn_group, field_intensity_level::monster_spawn_radius, field_intensity_level::move_cost, field_intensity_level::name, npc_complain_data, optional(), outdoor_age_speedup, percent_spread, phase, PNULL, priority, field_intensity_level::radiation_hurt_damage_max, field_intensity_level::radiation_hurt_damage_min, field_intensity_level::radiation_hurt_message, JsonObject::read(), field_intensity_level::scent_neutralization, speech, stacking_type, field_intensity_level::symbol, JsonObject::throw_error(), field_intensity_level::translucency, field_intensity_level::transparent, underwater_age_speedup, unicode_codepoint_from_symbol_reader(), wandering_field_id, and was_loaded.
Member Data Documentation
accelerated_decay
bool field_type::accelerated_decay = false
Definition at line 179 of file field_type.h.
Referenced by map::add_field(), field_entry::decays_on_actualize(), and load().
apply_slime_factor
int field_type::apply_slime_factor = 0
Definition at line 158 of file field_type.h.
Referenced by load(), and map::process_fields_in_submap().
bash_info
map_bash_info field_type::bash_info
Definition at line 167 of file field_type.h.
Referenced by check(), and load().
decay_amount_factor
int field_type::decay_amount_factor = 0
Definition at line 156 of file field_type.h.
Referenced by load().
desc_affix
description_affix field_type::desc_affix = description_affix::DESCRIPTION_AFFIX_NUM
Definition at line 166 of file field_type.h.
Referenced by field::displayed_description_affix(), and load().
dirty_transparency_cache
bool field_type::dirty_transparency_cache = false
Definition at line 161 of file field_type.h.
Referenced by map::add_field(), load(), and map::process_fields_in_submap().
display_field
bool field_type::display_field = false
Definition at line 181 of file field_type.h.
Referenced by load().
display_items
bool field_type::display_items = true
Definition at line 180 of file field_type.h.
Referenced by load().
gas_absorption_factor
int field_type::gas_absorption_factor = 0
Definition at line 159 of file field_type.h.
Referenced by field_entry::get_gas_absorption_factor(), and load().
half_life
time_duration field_type::half_life = 0_turns
Definition at line 177 of file field_type.h.
Referenced by field::add_field(), and load().
has_acid
bool field_type::has_acid = false
Definition at line 163 of file field_type.h.
Referenced by Character::is_immune_field(), monster::is_immune_field(), load(), and activity_handlers::pulp_do_turn().
has_elec
bool field_type::has_elec = false
Definition at line 164 of file field_type.h.
Referenced by Character::is_immune_field(), monster::is_immune_field(), and load().
has_fire
bool field_type::has_fire = false
Definition at line 162 of file field_type.h.
Referenced by Character::is_immune_field(), monster::is_immune_field(), and load().
has_fume
bool field_type::has_fume = false
Definition at line 165 of file field_type.h.
Referenced by monster::is_immune_field(), and load().
id
field_type_str_id field_type::id
Definition at line 143 of file field_type.h.
Referenced by submap::load().
immune_mtypes
std::set<mtype_id> field_type::immune_mtypes
Definition at line 174 of file field_type.h.
Referenced by finalize(), monster::is_immune_field(), and load().
immunity_data_body_part_env_resistance
std::vector<std::pair<body_part, int> > field_type::immunity_data_body_part_env_resistance
Definition at line 173 of file field_type.h.
Referenced by Character::is_immune_field(), and load().
immunity_data_traits
std::vector<trait_id> field_type::immunity_data_traits
Definition at line 172 of file field_type.h.
Referenced by Character::is_immune_field(), and load().
intensity_levels
std::vector<field_intensity_level> field_type::intensity_levels
Definition at line 152 of file field_type.h.
Referenced by check(), editmap::edit_fld(), get_intensity_level(), get_max_intensity(), is_dangerous(), is_transparent(), and load().
is_splattering
bool field_type::is_splattering = false
Definition at line 160 of file field_type.h.
Referenced by load().
legacy_enum_id
int field_type::legacy_enum_id = -1
Definition at line 150 of file field_type.h.
Referenced by load().
looks_like
std::string field_type::looks_like
Definition at line 183 of file field_type.h.
Referenced by load().
npc_complain_data
std::tuple<int, std::string, time_duration, std::string> field_type::npc_complain_data
Definition at line 170 of file field_type.h.
Referenced by load(), and map::process_fields_in_submap().
outdoor_age_speedup
time_duration field_type::outdoor_age_speedup = 0_turns
Definition at line 155 of file field_type.h.
Referenced by load(), and map::process_fields_in_submap().
percent_spread
int field_type::percent_spread = 0
Definition at line 157 of file field_type.h.
Referenced by field_entry::gas_can_spread(), load(), and map::process_fields_in_submap().
phase
phase_id field_type::phase = PNULL
Definition at line 178 of file field_type.h.
Referenced by field_entry::gas_can_spread(), and load().
priority
int field_type::priority = 0
Definition at line 176 of file field_type.h.
Referenced by field::add_field(), map::draw_maptile(), load(), and field::remove_field().
stacking_type
fields::stacking_type field_type::stacking_type = fields::stacking_type::intensity
Definition at line 185 of file field_type.h.
Referenced by load().
underwater_age_speedup
time_duration field_type::underwater_age_speedup = 0_turns
Definition at line 154 of file field_type.h.
Referenced by field_entry::get_underwater_age_speedup(), and load().
wandering_field
field_type_id field_type::wandering_field
Definition at line 182 of file field_type.h.
Referenced by finalize(), and map::process_fields_in_submap().
wandering_field_id
std::string field_type::wandering_field_id = "fd_null"
Definition at line 147 of file field_type.h.
Referenced by finalize(), and load().
was_loaded
bool field_type::was_loaded = false
Definition at line 144 of file field_type.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/field_type.h
src/field_type.cpp