Cataclysm BN: iuse_location Struct Reference
iuse_location Struct Reference
#include <item_handling_util.h>
Public Member Functions
iuse_location ()=default
~iuse_location ()=default
iuse_location (const item_location &loc, int count)
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Public Attributes
item_location loc
int count = 0
Detailed Description
Definition at line 12 of file item_handling_util.h.
Constructor & Destructor Documentation
iuse_location() [1/2]
iuse_location::iuse_location () default
~iuse_location()
iuse_location::~iuse_location () default
iuse_location() [2/2]
iuse_location::iuse_location (const item_location & loc, int count) inline
Definition at line 15 of file item_handling_util.h.
: loc(loc), count(count) { }
Member Function Documentation
deserialize()
void iuse_location::deserialize (JsonIn & jsin)
Definition at line 3505 of file savegame_json.cpp.
{
    jsin.start_array();
    jsin.read( loc );
    jsin.read( count );
    jsin.end_array();
}
References detail::count(), JsonIn::end_array(), JsonIn::read(), and JsonIn::start_array().
serialize()
void iuse_location::serialize (JsonOut & jsout) const
Definition at line 3497 of file savegame_json.cpp.
{
    jsout.start_array();
    jsout.write( loc );
    jsout.write( count );
    jsout.end_array();
}
References detail::count(), JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
Member Data Documentation
count
int iuse_location::count = 0
Definition at line 18 of file item_handling_util.h.
Referenced by crafting::complete_disassemble(), crafting::disassemble_all(), inventory_iuse_selector::get_raw_stats(), prompt_disassemble_single(), and disassemble_activity_actor::try_start_single().
loc
item_location iuse_location::loc
Definition at line 17 of file item_handling_util.h.
Referenced by crafting::complete_disassemble(), crafting::disassemble_all(), disassemble_activity_actor::finish(), prompt_disassemble_single(), and disassemble_activity_actor::try_start_single().
The documentation for this struct was generated from the following files:
src/item_handling_util.h
src/savegame_json.cpp