Cataclysm BN: dealt_damage_instance Struct Reference
dealt_damage_instance Struct Reference
#include <damage.h>
Public Member Functions
dealt_damage_instance ()
void set_damage (damage_type dt, int amount)
int type_damage (damage_type dt) const
int total_damage () const
Public Attributes
std::array< int, NUM_DT > dealt_dams
body_part bp_hit
Detailed Description
Definition at line 85 of file damage.h.
Constructor & Destructor Documentation
dealt_damage_instance()
dealt_damage_instance::dealt_damage_instance ()
Definition at line 158 of file damage.cpp.
{
    dealt_dams.fill( 0 );
}
References dealt_dams.
Member Function Documentation
set_damage()
void dealt_damage_instance::set_damage (damage_type dt, int amount)
Definition at line 163 of file damage.cpp.
{
    if( dt < 0 || dt >= NUM_DT ) {
        debugmsg( "Tried to set invalid damage type %d. NUM_DT is %d", dt, NUM_DT );
        return;
    }
    dealt_dams[dt] = amount;
}
References dealt_dams, debugmsg, and NUM_DT.
Referenced by spell::get_dealt_damage_instance().
total_damage()
int dealt_damage_instance::total_damage () const
Definition at line 180 of file damage.cpp.
{
    return std::accumulate( dealt_dams.begin(), dealt_dams.end(), 0 );
}
References dealt_dams.
Referenced by mattack::acid_barf(), mdefense::acidsplash(), mattack::bio_op_impale(), map::burn_body_part(), melee_actor::call(), Character::deal_damage(), item::effective_dps(), mattack::evolve_kill_strike(), mattack::fungus_bristle(), Character::hitall(), Character::impact(), mattack::impale(), mattack::longswipe(), mattack::lunge(), Character::melee_attack(), monster::melee_attack(), bite_actor::on_damage(), Character::perform_special_attacks(), map::player_in_field(), ranged::print_dmg_msg(), mdefense::return_fire(), explosion_handler::shrapnel(), sting_shoot(), mattack::stretch_attack(), mattack::stretch_bite(), mattack::taze(), iuse::tazer(), and mattack::tentacle().
type_damage()
int dealt_damage_instance::type_damage (damage_type dt) const
Definition at line 172 of file damage.cpp.
{
    if( static_cast<size_t>( dt ) < dealt_dams.size() ) {
        return dealt_dams[dt];
    }
    return 0;
}
References dealt_dams.
Referenced by Character::deal_damage(), drop_or_embed_projectile(), Character::melee_attack(), monster::melee_attack(), melee_message(), and map::player_in_field().
Member Data Documentation
bp_hit
body_part dealt_damage_instance::bp_hit
Definition at line 87 of file damage.h.
Referenced by melee_actor::call(), Creature::deal_melee_hit(), ranged::hit_with_aoe(), monster::melee_attack(), melee_actor::on_damage(), bite_actor::on_damage(), and ranged::print_dmg_msg().
dealt_dams
std::array<int, NUM_DT> dealt_damage_instance::dealt_dams
Definition at line 86 of file damage.h.
Referenced by Creature::deal_damage(), dealt_damage_instance(), item::effective_dps(), ranged::hit_with_aoe(), set_damage(), total_damage(), and type_damage().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp