Cataclysm BN: detail::arg_mapper< Context > Struct Template Reference
detail::arg_mapper< Context > Struct Template Reference
#include <fmtlib_core.h>
Public Types
using char_type = typename Context::char_type
Public Member Functions
FMT_CONSTEXPR int map (signed char val)
FMT_CONSTEXPR unsigned map (unsigned char val)
FMT_CONSTEXPR int map (short val)
FMT_CONSTEXPR unsigned map (unsigned short val)
FMT_CONSTEXPR int map (int val)
FMT_CONSTEXPR unsigned map (unsigned val)
FMT_CONSTEXPR long_type map (long val)
FMT_CONSTEXPR ulong_type map (unsigned long val)
FMT_CONSTEXPR long long map (long long val)
FMT_CONSTEXPR unsigned long long map (unsigned long long val)
FMT_CONSTEXPR int128_t map (int128_t val)
FMT_CONSTEXPR uint128_t map (uint128_t val)
FMT_CONSTEXPR bool map (bool val)
template<typename T , FMT_ENABLE_IF(is_char< T >::value) >
FMT_CONSTEXPR char_type map (T val)
FMT_CONSTEXPR float map (float val)
FMT_CONSTEXPR double map (double val)
FMT_CONSTEXPR long double map (long double val)
FMT_CONSTEXPR const char_type * map (char_type *val)
FMT_CONSTEXPR const char_type * map (const char_type *val)
template<typename T , FMT_ENABLE_IF(is_string< T >::value) >
FMT_CONSTEXPR basic_string_view< char_type > map (const T &val)
template<typename T , FMT_ENABLE_IF(std::is_constructible< basic_string_view< char_type >, T >::value &&!is_string< T >::value &&!has_formatter< T, Context >::value && !has_fallback_formatter< T, Context >::value) >
FMT_CONSTEXPR basic_string_view< char_type > map (const T &val)
template<typename T , FMT_ENABLE_IF(std::is_constructible< std_string_view< char_type >, T >::value &&!std::is_constructible< basic_string_view< char_type >, T >::value &&!is_string< T >::value &&!has_formatter< T, Context >::value &&!has_fallback_formatter< T, Context >::value) >
FMT_CONSTEXPR basic_string_view< char_type > map (const T &val)
FMT_CONSTEXPR const char * map (const signed char *val)
FMT_CONSTEXPR const char * map (const unsigned char *val)
FMT_CONSTEXPR const char * map (signed char *val)
FMT_CONSTEXPR const char * map (unsigned char *val)
FMT_CONSTEXPR const void * map (void *val)
FMT_CONSTEXPR const void * map (const void *val)
FMT_CONSTEXPR const void * map (std::nullptr_t val)
template<typename T >
FMT_CONSTEXPR int map (const T *)
template<typename T , FMT_ENABLE_IF(std::is_enum< T >::value && !has_formatter< T, Context >::value && !has_fallback_formatter< T, Context >::value) >
FMT_CONSTEXPR auto map (const T &val) -> decltype(std::declval< arg_mapper >().map(static_cast< typename std::underlying_type< T >::type >(val)))
template<typename T , FMT_ENABLE_IF(!is_string< T >::value &&!is_char< T >::value &&(has_formatter< T, Context >::value||has_fallback_formatter< T, Context >::value)) >
FMT_CONSTEXPR const T & map (const T &val)
template<typename T >
FMT_CONSTEXPR auto map (const named_arg< char_type, T > &val) -> decltype(std::declval< arg_mapper >().map(val.value))
unformattable map (...)
Detailed Description
template<typename Context>
struct detail::arg_mapper< Context >
Definition at line 1241 of file fmtlib_core.h.
Member Typedef Documentation
char_type
template<typename Context > using detail::arg_mapper< Context >::char_type = typename Context::char_type
Definition at line 1242 of file fmtlib_core.h.
Member Function Documentation
map() [1/34]
template<typename Context > unformattable detail::arg_mapper< Context >::map (...) inline
Definition at line 1398 of file fmtlib_core.h.
{
        return {};
    }
map() [2/34]
template<typename Context > FMT_CONSTEXPR bool detail::arg_mapper< Context >::map (bool val) inline
Definition at line 1282 of file fmtlib_core.h.
{
        return val;
    }
map() [3/34]
template<typename Context > FMT_CONSTEXPR const char_type * detail::arg_mapper< Context >::map (char_type * val) inline
Definition at line 1304 of file fmtlib_core.h.
{
        return val;
    }
map() [4/34]
template<typename Context > FMT_CONSTEXPR const char_type * detail::arg_mapper< Context >::map (const char_type * val) inline
Definition at line 1307 of file fmtlib_core.h.
{
        return val;
    }
map() [5/34]
template<typename Context > template<typename T > FMT_CONSTEXPR auto detail::arg_mapper< Context >::map (const named_arg< char_type, T > & val) -> decltype(std::declval<arg_mapper>().map(val.value)) inline
Definition at line 1392 of file fmtlib_core.h.
{
        return map( val.value );
    }
References detail::arg_mapper< Context >::map().
map() [6/34]
template<typename Context > FMT_CONSTEXPR const char * detail::arg_mapper< Context >::map (const signed char * val) inline
Definition at line 1336 of file fmtlib_core.h.
{
        static_assert( std::is_same<char_type, char>::value, "invalid string type" );
        return reinterpret_cast<const char *>( val );
    }
map() [7/34]
template<typename Context > template<typename T , FMT_ENABLE_IF(is_string< T >::value) > FMT_CONSTEXPR basic_string_view< char_type > detail::arg_mapper< Context >::map (const T & val) inline
Definition at line 1311 of file fmtlib_core.h.
{
        static_assert( std::is_same<char_type, char_t<T>>::value,
                       "mixing character types is disallowed" );
        return to_string_view( val );
    }
References detail::to_string_view().
map() [8/34]
template<typename Context > template<typename T , FMT_ENABLE_IF(std::is_constructible< basic_string_view< char_type >, T >::value &&!is_string< T >::value &&!has_formatter< T, Context >::value && !has_fallback_formatter< T, Context >::value) > FMT_CONSTEXPR basic_string_view< char_type > detail::arg_mapper< Context >::map (const T & val) inline
Definition at line 1322 of file fmtlib_core.h.
{
        return basic_string_view<char_type>( val );
    }
map() [9/34]
template<typename Context > template<typename T , FMT_ENABLE_IF(std::is_constructible< std_string_view< char_type >, T >::value &&!std::is_constructible< basic_string_view< char_type >, T >::value &&!is_string< T >::value &&!has_formatter< T, Context >::value &&!has_fallback_formatter< T, Context >::value) > FMT_CONSTEXPR basic_string_view< char_type > detail::arg_mapper< Context >::map (const T & val) inline
Definition at line 1333 of file fmtlib_core.h.
{
        return std_string_view<char_type>( val );
    }
map() [10/34]
template<typename Context > template<typename T , FMT_ENABLE_IF(!is_string< T >::value &&!is_char< T >::value &&(has_formatter< T, Context >::value||has_fallback_formatter< T, Context >::value)) > FMT_CONSTEXPR const T & detail::arg_mapper< Context >::map (const T & val) inline
Definition at line 1387 of file fmtlib_core.h.
{
        return val;
    }
map() [11/34]
template<typename Context > template<typename T , FMT_ENABLE_IF(std::is_enum< T >::value && !has_formatter< T, Context >::value && !has_fallback_formatter< T, Context >::value) > FMT_CONSTEXPR auto detail::arg_mapper< Context >::map (const T & val) -> decltype(std::declval<arg_mapper>().map(static_cast<typename std::underlying_type<T>::type>(val))) inline
Definition at line 1377 of file fmtlib_core.h.
{
        return map( static_cast<typename std::underlying_type<T>::type>( val ) );
    }
References detail::arg_mapper< Context >::map(), and type.
map() [12/34]
template<typename Context > template<typename T > FMT_CONSTEXPR int detail::arg_mapper< Context >::map (const T *) inline
Definition at line 1364 of file fmtlib_core.h.
{
        // Formatting of arbitrary pointers is disallowed. If you want to output
        // a pointer cast it to "void *" or "const void *". In particular, this
        // forbids formatting of "[const] volatile char *" which is printed as bool
        // by iostreams.
        static_assert( !sizeof( T ), "formatting of non-void pointers is disallowed" );
        return 0;
    }
map() [13/34]
template<typename Context > FMT_CONSTEXPR const char * detail::arg_mapper< Context >::map (const unsigned char * val) inline
Definition at line 1340 of file fmtlib_core.h.
{
        static_assert( std::is_same<char_type, char>::value, "invalid string type" );
        return reinterpret_cast<const char *>( val );
    }
map() [14/34]
template<typename Context > FMT_CONSTEXPR const void * detail::arg_mapper< Context >::map (const void * val) inline
Definition at line 1358 of file fmtlib_core.h.
{
        return val;
    }
map() [15/34]
template<typename Context > FMT_CONSTEXPR double detail::arg_mapper< Context >::map (double val) inline
Definition at line 1297 of file fmtlib_core.h.
{
        return val;
    }
map() [16/34]
template<typename Context > FMT_CONSTEXPR float detail::arg_mapper< Context >::map (float val) inline
Definition at line 1294 of file fmtlib_core.h.
{
        return val;
    }
map() [17/34]
template<typename Context > FMT_CONSTEXPR int detail::arg_mapper< Context >::map (int val) inline
Definition at line 1256 of file fmtlib_core.h.
{
        return val;
    }
map() [18/34]
template<typename Context > FMT_CONSTEXPR int128_t detail::arg_mapper< Context >::map (int128_t val) inline
Definition at line 1276 of file fmtlib_core.h.
{
        return val;
    }
map() [19/34]
template<typename Context > FMT_CONSTEXPR long double detail::arg_mapper< Context >::map (long double val) inline
Definition at line 1300 of file fmtlib_core.h.
{
        return val;
    }
map() [20/34]
template<typename Context > FMT_CONSTEXPR long long detail::arg_mapper< Context >::map (long long val) inline
Definition at line 1270 of file fmtlib_core.h.
{
        return val;
    }
map() [21/34]
template<typename Context > FMT_CONSTEXPR long_type detail::arg_mapper< Context >::map (long val) inline
Definition at line 1263 of file fmtlib_core.h.
{
        return val;
    }
map() [22/34]
template<typename Context > FMT_CONSTEXPR int detail::arg_mapper< Context >::map (short val) inline
Definition at line 1250 of file fmtlib_core.h.
{
        return val;
    }
map() [23/34]
template<typename Context > FMT_CONSTEXPR const char * detail::arg_mapper< Context >::map (signed char * val) inline
Definition at line 1345 of file fmtlib_core.h.
{
        const auto *const_val = val;
        return map( const_val );
    }
References detail::arg_mapper< Context >::map().
map() [24/34]
template<typename Context > FMT_CONSTEXPR int detail::arg_mapper< Context >::map (signed char val) inline
Definition at line 1244 of file fmtlib_core.h.
{
        return val;
    }
Referenced by detail::make_arg(), detail::arg_mapper< Context >::map(), and detail::parse_format_specs().
map() [25/34]
template<typename Context > FMT_CONSTEXPR const void * detail::arg_mapper< Context >::map (std::nullptr_t val) inline
Definition at line 1361 of file fmtlib_core.h.
{
        return val;
    }
map() [26/34]
template<typename Context > template<typename T , FMT_ENABLE_IF(is_char< T >::value) > FMT_CONSTEXPR char_type detail::arg_mapper< Context >::map (T val) inline
Definition at line 1287 of file fmtlib_core.h.
{
        static_assert(
            std::is_same<T, char>::value || std::is_same<T, char_type>::value,
            "mixing character types is disallowed" );
        return val;
    }
map() [27/34]
template<typename Context > FMT_CONSTEXPR uint128_t detail::arg_mapper< Context >::map (uint128_t val) inline
Definition at line 1279 of file fmtlib_core.h.
{
        return val;
    }
map() [28/34]
template<typename Context > FMT_CONSTEXPR const char * detail::arg_mapper< Context >::map (unsigned char * val) inline
Definition at line 1350 of file fmtlib_core.h.
{
        const auto *const_val = val;
        return map( const_val );
    }
References detail::arg_mapper< Context >::map().
map() [29/34]
template<typename Context > FMT_CONSTEXPR unsigned detail::arg_mapper< Context >::map (unsigned char val) inline
Definition at line 1247 of file fmtlib_core.h.
{
        return val;
    }
map() [30/34]
template<typename Context > FMT_CONSTEXPR unsigned long long detail::arg_mapper< Context >::map (unsigned long long val) inline
Definition at line 1273 of file fmtlib_core.h.
{
        return val;
    }
map() [31/34]
template<typename Context > FMT_CONSTEXPR ulong_type detail::arg_mapper< Context >::map (unsigned long val) inline
Definition at line 1267 of file fmtlib_core.h.
{
        return val;
    }
map() [32/34]
template<typename Context > FMT_CONSTEXPR unsigned detail::arg_mapper< Context >::map (unsigned short val) inline
Definition at line 1253 of file fmtlib_core.h.
{
        return val;
    }
map() [33/34]
template<typename Context > FMT_CONSTEXPR unsigned detail::arg_mapper< Context >::map (unsigned val) inline
Definition at line 1259 of file fmtlib_core.h.
{
        return val;
    }
map() [34/34]
template<typename Context > FMT_CONSTEXPR const void * detail::arg_mapper< Context >::map (void * val) inline
Definition at line 1355 of file fmtlib_core.h.
{
        return val;
    }
The documentation for this struct was generated from the following file:
src/fmtlib_core.h