Cataclysm BN: pickup::pick_drop_selection Struct Reference
pickup::pick_drop_selection Struct Reference
#include <pickup_token.h>
Public Member Functions
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jin)
Public Attributes
item_location target
cata::optional< int > quantity
std::vector< item_location > children
Detailed Description
Definition at line 37 of file pickup_token.h.
Member Function Documentation
deserialize()
void pickup::pick_drop_selection::deserialize (JsonIn & jin)
Definition at line 1297 of file pickup.cpp.
{
    JsonObject jo = jin.get_object();
    jo.read( "target", target );
    jo.read( "quantity", quantity );
    jo.read( "children", children );
}
References children, JsonIn::get_object(), quantity, JsonObject::read(), and target.
serialize()
void pickup::pick_drop_selection::serialize (JsonOut & jsout) const
Definition at line 1286 of file pickup.cpp.
{
    jsout.start_object();
    jsout.member( "target", target );
    jsout.member( "quantity", quantity );
    jsout.member( "children", children );
    jsout.end_object();
}
References children, JsonOut::end_object(), JsonOut::member(), quantity, JsonOut::start_object(), and target.
Member Data Documentation
children
std::vector<item_location> pickup::pick_drop_selection::children
Definition at line 40 of file pickup_token.h.
Referenced by deserialize(), pick_one_up(), and serialize().
quantity
cata::optional<int> pickup::pick_drop_selection::quantity
Definition at line 39 of file pickup_token.h.
Referenced by deserialize(), pick_one_up(), and serialize().
target
item_location pickup::pick_drop_selection::target
Definition at line 38 of file pickup_token.h.
Referenced by deserialize(), pickup::do_pickup(), pick_one_up(), and serialize().
The documentation for this struct was generated from the following files:
src/pickup_token.h
src/pickup.cpp