Cataclysm BN: talk_trial Struct Reference
talk_trial Struct Reference
If not TALK_TRIAL_NONE, it defines how to decide whether the responses succeeds (e.g.
#include <dialogue.h>
Public Member Functions
int calc_chance (const dialogue &d) const
std::string name () const
Returns a user-friendly representation of type.
operator bool () const
bool roll (dialogue &d) const
Roll for success or failure of this trial.
talk_trial ()=default
talk_trial (const JsonObject &)
Public Attributes
talk_trial_type type = TALK_TRIAL_NONE
int difficulty = 0
std::function< bool(const dialogue &)> condition
std::vector< trial_mod > modifiers
Detailed Description
If not TALK_TRIAL_NONE, it defines how to decide whether the responses succeeds (e.g.
the NPC believes the lie). The difficulty is a 0...100 percent chance of success (!), 100 means always success, 0 means never. It is however affected by mutations/traits/bionics/etc. of the player character.
Definition at line 50 of file dialogue.h.
Constructor & Destructor Documentation
talk_trial() [1/2]
talk_trial::talk_trial () default
talk_trial() [2/2]
talk_trial::talk_trial (const JsonObject & jo)
Definition at line 1858 of file npctalk.cpp.
{
    static const std::unordered_map<std::string, talk_trial_type> types_map = { {
#define WRAP(value) { #value, TALK_TRIAL_##value }
            WRAP( NONE ),
            WRAP( LIE ),
            WRAP( PERSUADE ),
            WRAP( INTIMIDATE ),
            WRAP( CONDITION )
#undef WRAP
        }
    };
    const auto iter = types_map.find( jo.get_string( "type", "NONE" ) );
    if( iter == types_map.end() ) {
        jo.throw_error( "invalid talk trial type", "type" );
    }
    type = iter->second;
    if( !( type == TALK_TRIAL_NONE || type == TALK_TRIAL_CONDITION ) ) {
        difficulty = jo.get_int( "difficulty" );
    }
    read_condition<dialogue>( jo, "condition", condition, false );
    if( jo.has_member( "mod" ) ) {
        for( JsonArray jmod : jo.get_array( "mod" ) ) {
            trial_mod this_modifier;
            this_modifier.first = jmod.next_string();
            this_modifier.second = jmod.next_int();
            modifiers.push_back( this_modifier );
        }
    }
}
References condition, difficulty, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_member(), modifiers, NONE, read_condition< dialogue >(), TALK_TRIAL_CONDITION, TALK_TRIAL_NONE, JsonObject::throw_error(), type, and WRAP.
Member Function Documentation
calc_chance()
int talk_trial::calc_chance (const dialogue & d) const
Definition at line 1406 of file npctalk.cpp.
{
    player &u = *d.alpha;
    if( u.has_trait( trait_DEBUG_MIND_CONTROL ) ) {
        return 100;
    }
    const social_modifiers &u_mods = u.get_mutation_social_mods();
    npc &p = *d.beta;
    int chance = difficulty;
    switch( type ) {
        case NUM_TALK_TRIALS:
            debugmsg( "Called calc_chance with invalid talk_trial value %d", type );
            break;
        case TALK_TRIAL_LIE:
            chance += character_effects::talk_skill( u ) -
                      character_effects::talk_skill( p ) +
                      p.op_of_u.trust * 3;
            chance += u_mods.lie;
            //come on, who would suspect a robot of lying?
            if( u.has_bionic( bio_voice ) ) {
                chance += 10;
            }
            if( u.has_bionic( bio_face_mask ) ) {
                chance += 20;
            }
            break;
        case TALK_TRIAL_PERSUADE:
            chance += character_effects::talk_skill( u ) -
                      character_effects::talk_skill( p ) / 2 +
                      p.op_of_u.trust * 2 + p.op_of_u.value;
            chance += u_mods.persuade;
            if( u.has_bionic( bio_face_mask ) ) {
                chance += 10;
            }
            if( u.has_bionic( bio_deformity ) ) {
                chance -= 50;
            }
            if( u.has_bionic( bio_voice ) ) {
                chance -= 20;
            }
            break;
        case TALK_TRIAL_INTIMIDATE:
            chance += character_effects::intimidation( u ) -
                      character_effects::intimidation( p ) +
                      p.op_of_u.fear * 2 - p.personality.bravery * 2;
            chance += u_mods.intimidate;
            if( u.has_bionic( bio_face_mask ) ) {
                chance += 10;
            }
            if( u.has_bionic( bio_armor_eyes ) ) {
                chance += 10;
            }
            if( u.has_bionic( bio_deformity ) ) {
                chance += 20;
            }
            if( u.has_bionic( bio_voice ) ) {
                chance += 20;
            }
            break;
        case TALK_TRIAL_NONE:
            chance = 100;
            break;
        case TALK_TRIAL_CONDITION:
            chance = condition( d ) ? 100 : 0;
            break;
    }
    for( const auto &this_mod : modifiers ) {
        chance += parse_mod( d, this_mod.first, this_mod.second );
    }
    return std::max( 0, std::min( 100, chance ) );
}
References dialogue::alpha, dialogue::beta, bio_armor_eyes, bio_deformity, bio_face_mask, bio_voice, npc_personality::bravery, condition, debugmsg, difficulty, npc_opinion::fear, Character::get_mutation_social_mods(), Character::has_bionic(), Character::has_trait(), social_modifiers::intimidate, character_effects::intimidation(), social_modifiers::lie, modifiers, NUM_TALK_TRIALS, npc::op_of_u, parse_mod(), npc::personality, social_modifiers::persuade, character_effects::talk_skill(), TALK_TRIAL_CONDITION, TALK_TRIAL_INTIMIDATE, TALK_TRIAL_LIE, TALK_TRIAL_NONE, TALK_TRIAL_PERSUADE, trait_DEBUG_MIND_CONTROL, npc_opinion::trust, type, and npc_opinion::value.
Referenced by talk_response::create_option_line(), talk_response::get_consequences(), and roll().
name()
std::string talk_trial::name () const
Returns a user-friendly representation of type.
Definition at line 125 of file npctalk.cpp.
{
    static const std::array<std::string, NUM_TALK_TRIALS> texts = { {
            "", translate_marker( "LIE" ), translate_marker( "PERSUADE" ), translate_marker( "INTIMIDATE" ), ""
        }
    };
    if( static_cast<size_t>( type ) >= texts.size() ) {
        debugmsg( "invalid trial type %d", static_cast<int>( type ) );
        return std::string();
    }
    return texts[type].empty() ? std::string() : _( texts[type] );
}
References _, debugmsg, translate_marker, and type.
Referenced by talk_response::create_option_line().
operator bool()
talk_trial::operator bool () const inline
Definition at line 61 of file dialogue.h.
{
        return type != TALK_TRIAL_NONE;
    }
References TALK_TRIAL_NONE, and type.
roll()
bool talk_trial::roll (dialogue & d) const
Roll for success or failure of this trial.
Definition at line 1483 of file npctalk.cpp.
{
    player &u = *d.alpha;
    if( type == TALK_TRIAL_NONE || u.has_trait( trait_DEBUG_MIND_CONTROL ) ) {
        return true;
    }
    const int chance = calc_chance( d );
    const bool success = rng( 0, 99 ) < chance;
    if( success ) {
        u.practice( skill_speech, ( 100 - chance ) / 10 );
    } else {
        u.practice( skill_speech, ( 100 - chance ) / 7 );
    }
    return success;
}
References dialogue::alpha, calc_chance(), Character::has_trait(), player::practice(), rng(), skill_speech, behavior::success, TALK_TRIAL_NONE, trait_DEBUG_MIND_CONTROL, and type.
Referenced by dialogue::opt().
Member Data Documentation
condition
std::function<bool(const dialogue &)> talk_trial::condition
Definition at line 53 of file dialogue.h.
Referenced by calc_chance(), and talk_trial().
difficulty
int talk_trial::difficulty = 0
Definition at line 52 of file dialogue.h.
Referenced by calc_chance(), and talk_trial().
modifiers
std::vector<trial_mod> talk_trial::modifiers
Definition at line 60 of file dialogue.h.
Referenced by calc_chance(), and talk_trial().
type
talk_trial_type talk_trial::type = TALK_TRIAL_NONE
Definition at line 51 of file dialogue.h.
Referenced by calc_chance(), talk_response::create_option_line(), name(), operator bool(), roll(), and talk_trial().
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp