Cataclysm BN: overmap_ui::grids_draw_data Struct Reference
overmap_ui::grids_draw_data Struct Reference
Public Member Functions
cata::optional< char > get_active (const tripoint_abs_omt &omp)
cata::optional< char > get_inactive (const tripoint_abs_omt &omp)
Private Member Functions
template<typename Fn >
cata::optional< char > pick_char (Fn filter_func)
Private Attributes
std::unordered_map< std::uintptr_t, char > list_active
std::unordered_map< std::size_t, std::pair< std::vector< tripoint_abs_omt >, char > > list_inactive
Detailed Description
Definition at line 103 of file overmap_ui.cpp.
Member Function Documentation
get_active()
cata::optional< char > overmap_ui::grids_draw_data::get_active (const tripoint_abs_omt & omp) inline
Definition at line 105 of file overmap_ui.cpp.
{
            // TODO: fix point types
            uintptr_t id = get_distribution_grid_tracker().debug_grid_id( omp );
            if( id == 0 ) {
                return cata::nullopt;
            }
            auto it = list_active.find( id );
            if( it != list_active.end() ) {
                return it->second;
            }
            auto ch = pick_char( [this]( char c ) -> bool {
                for( const auto &it : list_active ) {
                    if( it.second == c ) {
                        return false;
                    }
                }
                return true;
            } );
            char c = ch.has_value() ? *ch : '?';
            list_active.insert( std::make_pair( id, c ) );
            return c;
        }
References c, distribution_grid_tracker::debug_grid_id(), get_distribution_grid_tracker(), list_active, cata::nullopt, and pick_char().
Referenced by overmap_ui::draw_ascii().
get_inactive()
cata::optional< char > overmap_ui::grids_draw_data::get_inactive (const tripoint_abs_omt & omp) inline
Definition at line 131 of file overmap_ui.cpp.
{
            std::set<tripoint_abs_omt> grid = overmap_buffer.electric_grid_at( omp );
            if( grid.size() <= 1 ) {
                return cata::nullopt;
            }
            std::vector<tripoint_abs_omt> sorted( grid.begin(), grid.end() );
            std::sort( sorted.begin(), sorted.end() );
            std::size_t id = cata::range_hash{}( sorted );
            auto it = list_inactive.find( id );
            if( it != list_inactive.end() ) {
                return it->second.second;
            }
            // There may be a lot of grids visible at the same time.
            // We have no choice but to allow repeating symbols,
            // but also have to make sure neighbouring grids don't receive same ones.
            auto ch = pick_char( [omp, this]( char c ) {
                for( const auto &it : list_inactive ) {
                    if( it.second.second != c ) {
                        continue;
                    }
                    for( const tripoint_abs_omt &p : it.second.first ) {
                        tripoint_rel_omt delta = p - omp;
                        if( abs( delta.x() ) < 5 && abs( delta.y() ) < 5 && abs( delta.z() ) < 5 ) {
                            return false;
                        }
                    }
                }
                return true;
            } );
            char c = ch.has_value() ? *ch : '?';
            list_inactive.insert( std::make_pair( id, std::make_pair( sorted, c ) ) );
            return c;
        }
References c, overmapbuffer::electric_grid_at(), list_inactive, cata::nullopt, overmap_buffer, and pick_char().
Referenced by overmap_ui::draw_ascii().
pick_char()
template<typename Fn > cata::optional< char > overmap_ui::grids_draw_data::pick_char (Fn filter_func) inline private
Definition at line 172 of file overmap_ui.cpp.
{
            static std::string candidates( "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" );
            for( char c : candidates ) {
                if( filter_func( c ) ) {
                    return c;
                }
            }
            return cata::nullopt;
        }
References c, and cata::nullopt.
Referenced by get_active(), and get_inactive().
Member Data Documentation
list_active
std::unordered_map<std::uintptr_t, char> overmap_ui::grids_draw_data::list_active private
Definition at line 182 of file overmap_ui.cpp.
Referenced by get_active().
list_inactive
std::unordered_map<std::size_t, std::pair<std::vector<tripoint_abs_omt>, char> > overmap_ui::grids_draw_data::list_inactive private
Definition at line 183 of file overmap_ui.cpp.
Referenced by get_inactive().
The documentation for this struct was generated from the following file:
src/overmap_ui.cpp