Cataclysm BN: formatter< detail::bigint > Struct Reference
formatter< detail::bigint > Struct Reference
#include <fmtlib_format-inl.h>
Public Member Functions
format_parse_context::iterator parse (format_parse_context &ctx)
format_context::iterator format (const detail::bigint &n, format_context &ctx)
Detailed Description
Definition at line 2894 of file fmtlib_format-inl.h.
Member Function Documentation
format()
format_context::iterator formatter< detail::bigint >::format (const detail::bigint & n, format_context & ctx) inline
Definition at line 2899 of file fmtlib_format-inl.h.
{
        auto out = ctx.out();
        bool first = true;
        for( auto i = n.bigits_.size(); i > 0; --i ) {
            auto value = n.bigits_[i - 1u];
            if( first ) {
                out = format_to( out, "{:x}", value );
                first = false;
                continue;
            }
            out = format_to( out, "{:08x}", value );
        }
        if( n.exp_ > 0 ) {
            out = format_to( out, "p{}", n.exp_ * detail::bigint::bigit_bits );
        }
        return out;
    }
References detail::bigint::bigit_bits, detail::bigint::bigits_, detail::bigint::exp_, format_to(), and basic_format_context< OutputIt, Char >::out().
parse()
format_parse_context::iterator formatter< detail::bigint >::parse (format_parse_context & ctx) inline
Definition at line 2895 of file fmtlib_format-inl.h.
{
        return ctx.begin();
    }
References basic_format_parse_context< Char, ErrorHandler >::begin().
The documentation for this struct was generated from the following file:
src/fmtlib_format-inl.h