Cataclysm BN: real_coords Struct Reference
real_coords Struct Reference
#include <coordinates.h>
Public Member Functions
real_coords ()=default
real_coords (point ap)
void fromabs (const point &abs)
void fromomap (const point &rel_om, const point &rel_om_pos)
point_abs_omt abs_omt () const
point begin_sub ()
point begin_om_pos ()
point begin_om ()
Public Attributes
point abs_pos
point abs_sub
point abs_om
point sub_pos
point om_pos
point om_sub
Static Public Attributes
static const int tiles_in_sub = SEEX
static const int tiles_in_sub_n = tiles_in_sub - 1
static const int subs_in_om = OMAPX * 2
static const int subs_in_om_n = subs_in_om - 1
Detailed Description
Definition at line 625 of file coordinates.h.
Constructor & Destructor Documentation
real_coords() [1/2]
real_coords::real_coords () default
real_coords() [2/2]
real_coords::real_coords (point ap) inline
Definition at line 642 of file coordinates.h.
{
        fromabs( ap );
    }
References fromabs().
Member Function Documentation
abs_omt()
point_abs_omt real_coords::abs_omt () const inline
Definition at line 683 of file coordinates.h.
{
        return project_to<coords::omt>( point_abs_sm( abs_sub ) );
    }
References abs_sub.
Referenced by editmap::mapgen_preview().
begin_om()
point real_coords::begin_om () inline
Definition at line 696 of file coordinates.h.
                     {
        return point( abs_om.x * subs_in_om * tiles_in_sub, abs_om.y * subs_in_om * tiles_in_sub );
    }
References abs_om, subs_in_om, tiles_in_sub, point::x, and point::y.
begin_om_pos()
point real_coords::begin_om_pos () inline
Definition at line 692 of file coordinates.h.
{
        return point( ( abs_om.x * subs_in_om * tiles_in_sub ) + ( om_pos.x * 2 * tiles_in_sub ),
                      ( abs_om.y * subs_in_om * tiles_in_sub ) + ( om_pos.y * 2 * tiles_in_sub ) );
    }
References abs_om, om_pos, subs_in_om, tiles_in_sub, point::x, and point::y.
Referenced by editmap::edit_mapgen(), game::find_or_make_stairs(), and vertical_move_destination().
begin_sub()
point real_coords::begin_sub () inline
Definition at line 689 of file coordinates.h.
                      {
        return point( abs_sub.x * tiles_in_sub, abs_sub.y * tiles_in_sub );
    }
References abs_sub, tiles_in_sub, point::x, and point::y.
fromabs()
void real_coords::fromabs (const point & abs) inline
Definition at line 646 of file coordinates.h.
{
        const point norm( std::abs( abs.x ), std::abs( abs.y ) );
        abs_pos = abs;
        if( abs.x < 0 ) {
            abs_sub.x = ( abs.x - SEEX + 1 ) / SEEX;
            sub_pos.x = SEEX - 1 - ( ( norm.x - 1 ) % SEEX );
            abs_om.x = ( abs_sub.x - subs_in_om_n ) / subs_in_om;
            om_sub.x = subs_in_om_n - ( ( ( norm.x - 1 ) / SEEX ) % subs_in_om );
        } else {
            abs_sub.x = norm.x / SEEX;
            sub_pos.x = abs.x % SEEX;
            abs_om.x = abs_sub.x / subs_in_om;
            om_sub.x = abs_sub.x % subs_in_om;
        }
        om_pos.x = om_sub.x / 2;
        if( abs.y < 0 ) {
            abs_sub.y = ( abs.y - SEEY + 1 ) / SEEY;
            sub_pos.y = SEEY - 1 - ( ( norm.y - 1 ) % SEEY );
            abs_om.y = ( abs_sub.y - subs_in_om_n ) / subs_in_om;
            om_sub.y = subs_in_om_n - ( ( ( norm.y - 1 ) / SEEY ) % subs_in_om );
        } else {
            abs_sub.y = norm.y / SEEY;
            sub_pos.y = abs.y % SEEY;
            abs_om.y = abs_sub.y / subs_in_om;
            om_sub.y = abs_sub.y % subs_in_om;
        }
        om_pos.y = om_sub.y / 2;
    }
References abs_om, abs_pos, abs_sub, om_pos, om_sub, SEEX, SEEY, sub_pos, subs_in_om, subs_in_om_n, point::x, and point::y.
Referenced by editmap::edit_mapgen(), fromomap(), real_coords(), and map::rotate().
fromomap()
void real_coords::fromomap (const point & rel_om, const point & rel_om_pos) inline
Definition at line 678 of file coordinates.h.
{
        const point a = om_to_omt_copy( rel_om ) + rel_om_pos;
        fromabs( omt_to_ms_copy( a ) );
    }
References a, fromabs(), om_to_omt_copy(), and omt_to_ms_copy().
Member Data Documentation
abs_om
point real_coords::abs_om
Definition at line 633 of file coordinates.h.
Referenced by begin_om(), begin_om_pos(), and fromabs().
abs_pos
point real_coords::abs_pos
Definition at line 631 of file coordinates.h.
Referenced by fromabs().
abs_sub
point real_coords::abs_sub
Definition at line 632 of file coordinates.h.
Referenced by abs_omt(), begin_sub(), and fromabs().
om_pos
point real_coords::om_pos
Definition at line 637 of file coordinates.h.
Referenced by begin_om_pos(), fromabs(), and map::rotate().
om_sub
point real_coords::om_sub
Definition at line 638 of file coordinates.h.
Referenced by fromabs(), and map::rotate().
sub_pos
point real_coords::sub_pos
Definition at line 635 of file coordinates.h.
Referenced by fromabs(), and map::rotate().
subs_in_om
const int real_coords::subs_in_om = OMAPX * 2 static
Definition at line 628 of file coordinates.h.
Referenced by begin_om(), begin_om_pos(), and fromabs().
subs_in_om_n
const int real_coords::subs_in_om_n = subs_in_om - 1 static
Definition at line 629 of file coordinates.h.
Referenced by fromabs().
tiles_in_sub
const int real_coords::tiles_in_sub = SEEX static
Definition at line 626 of file coordinates.h.
Referenced by begin_om(), begin_om_pos(), and begin_sub().
tiles_in_sub_n
const int real_coords::tiles_in_sub_n = tiles_in_sub - 1 static
Definition at line 627 of file coordinates.h.
The documentation for this struct was generated from the following file:
src/coordinates.h