Cataclysm BN: defense_game Struct Reference
defense_game Struct Reference
#include <gamemode_defense.h>
Public Member Functions
defense_game ()
special_game_id id () override
bool init () override
void per_turn () override
void pre_action (action_id &act) override
void post_action (action_id act) override
void game_over () override
Public Member Functions inherited from special_game
virtual ~special_game ()=default
Private Member Functions
void init_to_style (defense_style new_style)
void setup ()
void refresh_setup (const catacurses::window &w, int selection)
void init_mtypes ()
void init_constructions ()
void init_map ()
void spawn_wave ()
void caravan ()
std::vector< mtype_id > pick_monster_wave ()
void spawn_wave_monster (const mtype_id &type)
std::string special_wave_message (std::string name)
Private Attributes
int current_wave = 0
defense_style style
defense_location location
int initial_difficulty = 0
int wave_difficulty = 0
time_duration time_between_waves = 0_turns
int waves_between_caravans = 0
int initial_cash = 0
int cash_per_wave = 0
int cash_increase = 0
bool zombies = false
bool specials = false
bool spiders = false
bool triffids = false
bool robots = false
bool subspace = false
bool hunger = false
bool thirst = false
bool sleep = false
bool mercenaries = false
bool allow_save = false
tripoint_om_omt defloc_pos
overmap_special_id defloc_special
Detailed Description
Definition at line 54 of file gamemode_defense.h.
Constructor & Destructor Documentation
defense_game()
defense_game::defense_game ()
Definition at line 80 of file gamemode_defense.cpp.
    : time_between_waves( 0_turns )
{
    current_wave = 0;
    hunger = false;
    thirst = false;
    sleep  = false;
    zombies = false;
    specials = false;
    spiders = false;
    triffids = false;
    robots = false;
    subspace = false;
    mercenaries = false;
    init_to_style( DEFENSE_EASY );
}
References current_wave, DEFENSE_EASY, hunger, init_to_style(), mercenaries, robots, sleep, specials, spiders, subspace, thirst, triffids, and zombies.
Member Function Documentation
caravan()
void defense_game::caravan () private
Definition at line 857 of file gamemode_defense.cpp.
{
    std::vector<itype_id> items[NUM_CARAVAN_CATEGORIES];
    std::vector<int> item_count[NUM_CARAVAN_CATEGORIES];
    // Init the items for each category
    for( int i = 0; i < NUM_CARAVAN_CATEGORIES; i++ ) {
        items[i] = caravan_items( static_cast<caravan_category>( i ) );
        for( std::vector<itype_id>::iterator it = items[i].begin();
             it != items[i].end(); ) {
            if( current_wave == 0 || !one_in( 4 ) ) {
                item_count[i].push_back( 0 );  // Init counts to 0 for each item
                it++;
            } else { // Remove the item
                it = items[i].erase( it );
            }
        }
    }
    signed total_price = 0;
    background_pane bg_pane;
    catacurses::window w;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        const int width = FULL_SCREEN_WIDTH;
        const int height = FULL_SCREEN_HEIGHT;
        const point offset( std::max( 0, TERMX - FULL_SCREEN_WIDTH ) / 2, std::max( 0,
                            TERMY - FULL_SCREEN_HEIGHT ) / 2 );
        w = catacurses::newwin( height, width, offset );
        ui.position_from_window( w );
    } );
    ui.mark_resize();
    int offset = 0;
    int item_selected = 0;
    int category_selected = 0;
    int current_window = 0;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        draw_caravan_categories( w, category_selected, total_price, g->u.cash );
        draw_caravan_items( w, &( items[category_selected] ),
                            &( item_count[category_selected] ), offset, item_selected );
        draw_caravan_borders( w, current_window );
    } );
    input_context ctxt( "CARAVAN" );
    ctxt.register_cardinal();
    ctxt.register_action( "CONFIRM" );
    ctxt.register_action( "QUIT" );
    ctxt.register_action( "NEXT_TAB" );
    ctxt.register_action( "HELP" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    bool done = false;
    bool cancel = false;
    while( !done ) {
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "HELP" ) {
            popup_top( _( "CARAVAN:\n"
                          "Start by selecting a category using your favorite up/down keys.\n"
                          "Switch between category selection and item selecting by pressing %s.\n"
                          "Pick an item with the up/down keys, press left/right to buy 1 less/more.\n"
                          "Press %s to buy everything in your cart, %s to buy nothing." ),
                       ctxt.get_desc( "NEXT_TAB" ),
                       ctxt.get_desc( "CONFIRM" ),
                       ctxt.get_desc( "QUIT" )
                     );
        } else if( action == "DOWN" ) {
            if( current_window == 0 ) { // Categories
                category_selected++;
                if( category_selected == NUM_CARAVAN_CATEGORIES ) {
                    category_selected = CARAVAN_CART;
                }
                offset = 0;
                item_selected = 0;
            } else if( !items[category_selected].empty() ) { // Items
                if( item_selected < static_cast<int>( items[category_selected].size() ) - 1 ) {
                    item_selected++;
                } else {
                    item_selected = 0;
                    offset = 0;
                }
                if( item_selected > offset + 12 ) {
                    offset++;
                }
            }
        } else if( action == "UP" ) {
            if( current_window == 0 ) { // Categories
                if( category_selected == 0 ) {
                    category_selected = NUM_CARAVAN_CATEGORIES - 1;
                } else {
                    category_selected--;
                }
                if( category_selected == NUM_CARAVAN_CATEGORIES ) {
                    category_selected = CARAVAN_CART;
                }
                offset = 0;
                item_selected = 0;
            } else if( !items[category_selected].empty() ) { // Items
                if( item_selected > 0 ) {
                    item_selected--;
                } else {
                    item_selected = items[category_selected].size() - 1;
                    offset = item_selected - 12;
                    if( offset < 0 ) {
                        offset = 0;
                    }
                }
                if( item_selected < offset ) {
                    offset--;
                }
            }
        } else if( action == "RIGHT" ) {
            if( current_window == 1 && !items[category_selected].empty() ) {
                item_count[category_selected][item_selected]++;
                itype_id tmp_itm = items[category_selected][item_selected];
                int item_price = item( tmp_itm, calendar::start_of_cataclysm ).price( false );
                total_price += caravan_price( g->u, item_price );
                if( category_selected == CARAVAN_CART ) { // Find the item in its category
                    for( int i = 1; i < NUM_CARAVAN_CATEGORIES; i++ ) {
                        for( size_t j = 0; j < items[i].size(); j++ ) {
                            if( items[i][j] == tmp_itm ) {
                                item_count[i][j]++;
                            }
                        }
                    }
                } else { // Add / increase the item in the shopping cart
                    bool found_item = false;
                    for( unsigned i = 0; i < items[0].size() && !found_item; i++ ) {
                        if( items[0][i] == tmp_itm ) {
                            found_item = true;
                            item_count[0][i]++;
                        }
                    }
                    if( !found_item ) {
                        items[0].push_back( items[category_selected][item_selected] );
                        item_count[0].push_back( 1 );
                    }
                }
            }
        } else if( action == "LEFT" ) {
            if( current_window == 1 && !items[category_selected].empty() &&
                item_count[category_selected][item_selected] > 0 ) {
                item_count[category_selected][item_selected]--;
                itype_id tmp_itm = items[category_selected][item_selected];
                int item_price = item( tmp_itm, calendar::start_of_cataclysm ).price( false );
                total_price -= caravan_price( g->u, item_price );
                if( category_selected == CARAVAN_CART ) { // Find the item in its category
                    for( int i = 1; i < NUM_CARAVAN_CATEGORIES; i++ ) {
                        for( size_t j = 0; j < items[i].size(); j++ ) {
                            if( items[i][j] == tmp_itm ) {
                                item_count[i][j]--;
                            }
                        }
                    }
                } else { // Decrease / remove the item in the shopping cart
                    bool found_item = false;
                    for( unsigned i = 0; i < items[0].size() && !found_item; i++ ) {
                        if( items[0][i] == tmp_itm ) {
                            found_item = true;
                            item_count[0][i]--;
                            if( item_count[0][i] == 0 ) {
                                item_count[0].erase( item_count[0].begin() + i );
                                items[0].erase( items[0].begin() + i );
                            }
                        }
                    }
                }
            }
        } else if( action == "NEXT_TAB" ) {
            current_window = ( current_window + 1 ) % 2;
        } else if( action == "QUIT" ) {
            if( query_yn( _( "Really buy nothing?" ) ) ) {
                cancel = true;
                done = true;
            }
        } else if( action == "CONFIRM" ) {
            if( total_price > g->u.cash ) {
                popup( _( "You can't afford those items!" ) );
            } else if( ( items[0].empty() && query_yn( _( "Really buy nothing?" ) ) ) ||
                       ( !items[0].empty() &&
                         query_yn( vgettext( "Buy %d item, leaving you with %s?",
                                             "Buy %d items, leaving you with %s?",
                                             items[0].size() ),
                                   items[0].size(),
                                   format_money( static_cast<int>( g->u.cash ) - static_cast<int>( total_price ) ) ) ) ) {
                done = true;
            }
        } // "switch" on (action)
    } // while (!done)
    if( !cancel ) {
        g->u.cash -= total_price;
        bool dropped_some = false;
        for( size_t i = 0; i < items[0].size(); i++ ) {
            item tmp( items[0][i] );
            tmp = tmp.in_its_container();
            // Guns bought from the caravan should always come with an empty
            // magazine.
            if( tmp.is_gun() && !tmp.magazine_integral() ) {
                tmp.put_in( item( tmp.magazine_default() ) );
            }
            for( int j = 0; j < item_count[0][i]; j++ ) {
                if( g->u.can_pick_volume( tmp ) && g->u.can_pick_weight( tmp ) ) {
                    g->u.i_add( tmp );
                } else { // Could fit it in the inventory!
                    dropped_some = true;
                    get_map().add_item_or_charges( g->u.pos(), tmp );
                }
            }
        }
        if( dropped_some ) {
            add_msg( _( "You drop some items." ) );
        }
    }
}
References _, action, map::add_item_or_charges(), add_msg(), cancel, CARAVAN_CART, caravan_items(), caravan_price(), current_wave, detail::digits::done, draw_caravan_borders(), draw_caravan_categories(), draw_caravan_items(), format_money(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, input_context::get_desc(), get_map(), input_context::handle_input(), item::in_its_container(), item::is_gun(), item::magazine_default(), item::magazine_integral(), catacurses::newwin(), NUM_CARAVAN_CATEGORIES, one_in(), popup(), popup_top(), item::price(), item::put_in(), query_yn(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), om_direction::size, calendar::start_of_cataclysm, TERMX, TERMY, and vgettext().
Referenced by init(), and per_turn().
game_over()
void defense_game::game_over () override virtual
Reimplemented from special_game.
Definition at line 199 of file gamemode_defense.cpp.
{
    popup( _( "You managed to survive through wave %d!" ), current_wave );
}
References _, current_wave, and popup().
id()
special_game_id defense_game::id () inline override virtual
Reimplemented from special_game.
Definition at line 57 of file gamemode_defense.h.
{
            return SGAME_DEFENSE;
        }
References SGAME_DEFENSE.
init()
bool defense_game::init () override virtual
Reimplemented from special_game.
Definition at line 97 of file gamemode_defense.cpp.
{
    calendar::turn = calendar::turn_zero + 12_hours; // Start at noon
    get_weather().temperature = 65;
    if( !g->u.create( character_type::CUSTOM ) ) {
        return false;
    }
    g->u.str_cur = g->u.str_max;
    g->u.per_cur = g->u.per_max;
    g->u.int_cur = g->u.int_max;
    g->u.dex_cur = g->u.dex_max;
    init_mtypes();
    init_constructions();
    current_wave = 0;
    hunger = false;
    thirst = false;
    sleep  = false;
    zombies = false;
    specials = false;
    spiders = false;
    triffids = false;
    robots = false;
    subspace = false;
    mercenaries = false;
    allow_save = false;
    init_to_style( DEFENSE_EASY );
    setup();
    g->u.cash = initial_cash;
    // TODO: support multiple defense games? clean up old defense game
    defloc_pos = tripoint_om_omt( 50, 50, 0 );
    init_map();
    caravan();
    return true;
}
References allow_save, caravan(), current_wave, CUSTOM, DEFENSE_EASY, defloc_pos, g, get_weather(), hunger, init_constructions(), init_map(), init_mtypes(), init_to_style(), initial_cash, mercenaries, robots, setup(), sleep, specials, spiders, subspace, weather_manager::temperature, thirst, triffids, calendar::turn, calendar::turn_zero, and zombies.
init_constructions()
void defense_game::init_constructions () private
Definition at line 217 of file gamemode_defense.cpp.
{
    standardize_construction_times( 1 ); // Everything takes 1 minute
}
References standardize_construction_times().
Referenced by init().
init_map()
void defense_game::init_map () private
Definition at line 222 of file gamemode_defense.cpp.
{
    background_pane background;
    static_popup popup;
    popup.message( _( "Please wait as the map generates [%2d%%]" ), 0 );
    ui_manager::redraw();
    refresh_display();
    auto &starting_om = overmap_buffer.get( point_abs_om() );
    for( int x = 0; x < OMAPX; x++ ) {
        for( int y = 0; y < OMAPY; y++ ) {
            tripoint_om_omt p( x, y, 0 );
            starting_om.ter_set( p, oter_id( "field" ) );
            starting_om.seen( p ) = true;
        }
    }
    switch( location ) {
        case DEFLOC_NULL:
        case NUM_DEFENSE_LOCATIONS:
            defloc_special = overmap_special_id( "house_two_story_basement" );
            debugmsg( "Invalid defense location %d", location );
            break;
        case DEFLOC_HOSPITAL:
            defloc_special = overmap_special_id( "hospital" );
            break;
        case DEFLOC_WORKS:
            defloc_special = overmap_special_id( "public_works" );
            break;
        case DEFLOC_MALL:
            defloc_special = overmap_special_id( "megastore" );
            break;
        case DEFLOC_BAR:
            defloc_special = overmap_special_id( "bar" );
            break;
        case DEFLOC_MANSION:
            defloc_special = overmap_special_id( "Mansion_Wild" );
            break;
    }
    starting_om.place_special_forced( defloc_special, defloc_pos, om_direction::type::north );
    starting_om.save();
    // Init the map
    int old_percent = 0;
    for( int i = 0; i <= MAPSIZE * 2; i += 2 ) {
        for( int j = 0; j <= MAPSIZE * 2; j += 2 ) {
            int mx = 100 - MAPSIZE + i;
            int my = 100 - MAPSIZE + j;
            int percent = 100 * ( ( j / 2 + MAPSIZE * ( i / 2 ) ) ) /
                          ( ( MAPSIZE ) * ( MAPSIZE + 1 ) );
            if( percent >= old_percent + 1 ) {
                popup.message( _( "Please wait as the map generates [%2d%%]" ), percent );
                ui_manager::redraw();
                refresh_display();
                old_percent = percent;
            }
            // Round down to the nearest even number
            mx -= mx % 2;
            my -= my % 2;
            tinymap tm;
            tm.generate( tripoint( mx, my, 0 ), calendar::turn );
            tm.clear_spawns();
            tm.clear_traps();
            tm.save();
        }
    }
    // For this mode assume we always want overmap zero.
    tripoint_abs_omt abs_defloc_pos = project_combine( point_abs_om(), defloc_pos );
    g->load_map( project_to<coords::sm>( abs_defloc_pos ) );
    Character &player_character = get_player_character();
    player_character.setx( SEEX );
    player_character.sety( SEEY );
    g->update_map( g-> u );
    monster *const generator = g->place_critter_around( mtype_id( "mon_generator" ), g->u.pos(), 2 );
    assert( generator );
    generator->friendly = -1;
}
References _, map::clear_spawns(), map::clear_traps(), debugmsg, DEFLOC_BAR, DEFLOC_HOSPITAL, DEFLOC_MALL, DEFLOC_MANSION, DEFLOC_NULL, defloc_pos, defloc_special, DEFLOC_WORKS, g, map::generate(), mattack::generator(), overmapbuffer::get(), get_player_character(), location, MAPSIZE, mtype_id, om_direction::north, NUM_DEFENSE_LOCATIONS, OMAPX, OMAPY, oter_id, overmap_buffer, popup(), coords::project_combine(), ui_manager::redraw(), refresh_display(), map::save(), SEEX, SEEY, Character::setx(), Character::sety(), and calendar::turn.
Referenced by init().
init_mtypes()
void defense_game::init_mtypes () private
Definition at line 204 of file gamemode_defense.cpp.
{
    for( auto &type : MonsterGenerator::generator().get_all_mtypes() ) {
        mtype *const t = const_cast<mtype *>( &type );
        t->difficulty *= 1.5;
        t->difficulty += static_cast<int>( t->difficulty / 5 );
        t->set_flag( MF_BASHES );
        t->set_flag( MF_SMELLS );
        t->set_flag( MF_HEARS );
        t->set_flag( MF_SEES );
    }
}
References mtype::difficulty, MonsterGenerator::generator(), MF_BASHES, MF_HEARS, MF_SEES, MF_SMELLS, mtype::set_flag(), and type.
Referenced by init().
init_to_style()
void defense_game::init_to_style (defense_style new_style) private
Definition at line 308 of file gamemode_defense.cpp.
{
    style = new_style;
    hunger = false;
    thirst = false;
    sleep  = false;
    zombies = false;
    specials = false;
    spiders = false;
    triffids = false;
    robots = false;
    subspace = false;
    mercenaries = false;
    switch( new_style ) {
        case NUM_DEFENSE_STYLES:
            debugmsg( "invalid defense style: %d", new_style );
            break;
        case DEFENSE_EASY:
        // fall through to custom
        case DEFENSE_CUSTOM:
            location = DEFLOC_HOSPITAL;
            initial_difficulty = 15;
            wave_difficulty = 10;
            time_between_waves = 30_minutes;
            waves_between_caravans = 3;
            initial_cash = 1000000;
            cash_per_wave = 100000;
            cash_increase = 30000;
            specials = true;
            spiders = true;
            triffids = true;
            mercenaries = true;
            break;
        case DEFENSE_MEDIUM:
            location = DEFLOC_MALL;
            initial_difficulty = 30;
            wave_difficulty = 15;
            time_between_waves = 20_minutes;
            waves_between_caravans = 4;
            initial_cash = 600000;
            cash_per_wave = 80000;
            cash_increase = 20000;
            specials = true;
            spiders = true;
            triffids = true;
            robots = true;
            hunger = true;
            mercenaries = true;
            break;
        case DEFENSE_HARD:
            location = DEFLOC_BAR;
            initial_difficulty = 50;
            wave_difficulty = 20;
            time_between_waves = 10_minutes;
            waves_between_caravans = 5;
            initial_cash = 200000;
            cash_per_wave = 60000;
            cash_increase = 10000;
            specials = true;
            spiders = true;
            triffids = true;
            robots = true;
            subspace = true;
            hunger = true;
            thirst = true;
            break;
        case DEFENSE_SHAUN:
            location = DEFLOC_BAR;
            initial_difficulty = 30;
            wave_difficulty = 15;
            time_between_waves = 5_minutes;
            waves_between_caravans = 6;
            initial_cash = 500000;
            cash_per_wave = 50000;
            cash_increase = 10000;
            zombies = true;
            break;
        case DEFENSE_DAWN:
            location = DEFLOC_MALL;
            initial_difficulty = 60;
            wave_difficulty = 20;
            time_between_waves = 30_minutes;
            waves_between_caravans = 4;
            initial_cash = 800000;
            cash_per_wave = 50000;
            cash_increase = 0;
            zombies = true;
            hunger = true;
            thirst = true;
            mercenaries = true;
            break;
        case DEFENSE_SPIDERS:
            location = DEFLOC_MALL;
            initial_difficulty = 60;
            wave_difficulty = 10;
            time_between_waves = 10_minutes;
            waves_between_caravans = 4;
            initial_cash = 600000;
            cash_per_wave = 50000;
            cash_increase = 10000;
            spiders = true;
            break;
        case DEFENSE_TRIFFIDS:
            location = DEFLOC_MANSION;
            initial_difficulty = 60;
            wave_difficulty = 20;
            time_between_waves = 30_minutes;
            waves_between_caravans = 2;
            initial_cash = 1000000;
            cash_per_wave = 60000;
            cash_increase = 10000;
            triffids = true;
            hunger = true;
            thirst = true;
            sleep = true;
            mercenaries = true;
            break;
        case DEFENSE_SKYNET:
            location = DEFLOC_HOSPITAL;
            initial_difficulty = 20;
            wave_difficulty = 20;
            time_between_waves = 20_minutes;
            waves_between_caravans = 6;
            initial_cash = 1200000;
            cash_per_wave = 100000;
            cash_increase = 20000;
            robots = true;
            hunger = true;
            thirst = true;
            mercenaries = true;
            break;
        case DEFENSE_LOVECRAFT:
            location = DEFLOC_MANSION;
            initial_difficulty = 20;
            wave_difficulty = 20;
            time_between_waves = 120_minutes;
            waves_between_caravans = 8;
            initial_cash = 400000;
            cash_per_wave = 100000;
            cash_increase = 10000;
            subspace = true;
            hunger = true;
            thirst = true;
            sleep = true;
            break;
    }
}
References cash_increase, cash_per_wave, debugmsg, DEFENSE_CUSTOM, DEFENSE_DAWN, DEFENSE_EASY, DEFENSE_HARD, DEFENSE_LOVECRAFT, DEFENSE_MEDIUM, DEFENSE_SHAUN, DEFENSE_SKYNET, DEFENSE_SPIDERS, DEFENSE_TRIFFIDS, DEFLOC_BAR, DEFLOC_HOSPITAL, DEFLOC_MALL, DEFLOC_MANSION, hunger, initial_cash, initial_difficulty, location, mercenaries, NUM_DEFENSE_STYLES, robots, sleep, specials, spiders, style, subspace, thirst, time_between_waves, triffids, wave_difficulty, waves_between_caravans, and zombies.
Referenced by defense_game(), init(), and setup().
per_turn()
void defense_game::per_turn () override virtual
Reimplemented from special_game.
Definition at line 132 of file gamemode_defense.cpp.
{
    if( !thirst ) {
        g->u.set_thirst( 0 );
    }
    if( !hunger ) {
        g->u.set_stored_kcal( g->u.max_stored_kcal() );
    }
    if( !sleep ) {
        g->u.set_fatigue( 0 );
    }
    if( calendar::once_every( time_between_waves ) ) {
        current_wave++;
        if( current_wave > 1 && current_wave % waves_between_caravans == 0 ) {
            popup( _( "A caravan approaches!  Press spacebar" ) );
            caravan();
        }
        spawn_wave();
    }
}
References _, caravan(), current_wave, g, hunger, calendar::once_every(), popup(), sleep, spawn_wave(), thirst, time_between_waves, and waves_between_caravans.
pick_monster_wave()
std::vector< mtype_id > defense_game::pick_monster_wave () private
Definition at line 1322 of file gamemode_defense.cpp.
{
    std::vector<mongroup_id> valid;
    std::vector<mtype_id> ret;
    if( zombies || specials ) {
        if( specials ) {
            valid.push_back( GROUP_ZOMBIE );
        } else {
            valid.push_back( GROUP_VANILLA );
        }
    }
    if( spiders ) {
        valid.push_back( GROUP_SPIDER );
    }
    if( triffids ) {
        valid.push_back( GROUP_TRIFFID );
    }
    if( robots ) {
        valid.push_back( GROUP_ROBOT );
    }
    if( subspace ) {
        valid.push_back( GROUP_NETHER );
    }
    if( valid.empty() ) {
        debugmsg( "Couldn't find a valid monster group for defense!" );
    } else {
        ret = MonsterGroupManager::GetMonstersFromGroup( random_entry( valid ) );
    }
    return ret;
}
References debugmsg, MonsterGroupManager::GetMonstersFromGroup(), GROUP_NETHER, GROUP_ROBOT, GROUP_SPIDER, GROUP_TRIFFID, GROUP_VANILLA, GROUP_ZOMBIE, random_entry(), cata::hash64_detail::ret, robots, specials, spiders, subspace, triffids, and zombies.
Referenced by spawn_wave().
post_action()
void defense_game::post_action (action_id act) override virtual
Reimplemented from special_game.
Definition at line 195 of file gamemode_defense.cpp.
{
}
pre_action()
void defense_game::pre_action (action_id & act) override virtual
Reimplemented from special_game.
Definition at line 153 of file gamemode_defense.cpp.
{
    std::string action_error_message;
    switch( act ) {
        case ACTION_SLEEP:
            if( !sleep ) {
                action_error_message = _( "You don't need to sleep!" );
            }
            break;
        case ACTION_SAVE:
        case ACTION_QUICKSAVE:
            if( !allow_save ) {
                action_error_message = _( "You cannot save in defense mode!" );
            }
            break;
        case ACTION_MOVE_FORTH:
        case ACTION_MOVE_FORTH_RIGHT:
        case ACTION_MOVE_RIGHT:
        case ACTION_MOVE_BACK_RIGHT:
        case ACTION_MOVE_BACK:
        case ACTION_MOVE_BACK_LEFT:
        case ACTION_MOVE_LEFT:
        case ACTION_MOVE_FORTH_LEFT: {
            const point delta = get_delta_from_movement_action( act, iso_rotate::yes );
            if( ( delta.y < 0 && g->u.posy() == HALF_MAPSIZE_Y && g->get_levy() <= 93 )
                || ( delta.y > 0 && g->u.posy() == HALF_MAPSIZE_Y + SEEY - 1 && g->get_levy() >= 98 )
                || ( delta.x < 0 && g->u.posx() == HALF_MAPSIZE_X && g->get_levx() <= 93 )
                || ( delta.x > 0 && g->u.posx() == HALF_MAPSIZE_X + SEEX - 1 && g->get_levx() >= 98 ) ) {
                action_error_message = string_format( _( "You cannot leave the %s behind!" ),
                                                      defense_location_name( location ) );
            }
        }
        break;
        default:
            break;
    }
    if( !action_error_message.empty() ) {
        add_msg( m_info, action_error_message );
        act = ACTION_NULL;
    }
}
References _, act, ACTION_MOVE_BACK, ACTION_MOVE_BACK_LEFT, ACTION_MOVE_BACK_RIGHT, ACTION_MOVE_FORTH, ACTION_MOVE_FORTH_LEFT, ACTION_MOVE_FORTH_RIGHT, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_NULL, ACTION_QUICKSAVE, ACTION_SAVE, ACTION_SLEEP, add_msg(), allow_save, defense_location_name(), g, get_delta_from_movement_action(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, location, m_info, SEEX, SEEY, sleep, string_format(), point::x, point::y, and yes.
refresh_setup()
void defense_game::refresh_setup (const catacurses::window & w, int selection) private
Definition at line 699 of file gamemode_defense.cpp.
{
    werase( w );
    draw_border( w, c_light_gray, _( "DEFENSE MODE" ), c_light_red );
    mvwprintz( w, point( 2, 1 ), c_light_red,
               _( "Press direction keys to cycle, ENTER to toggle, S to start" ) );
    mvwprintz( w, point( 2, 2 ), c_white, _( "Scenario:" ) );
    mvwprintz( w, point( 2, 3 ), SELCOL( 1 ), defense_style_name( style ) );
    mvwprintz( w, point( 28, 3 ), c_light_gray, defense_style_description( style ) );
    mvwprintz( w, point( 2, 4 ), c_white, _( "Location:" ) );
    mvwprintz( w, point( 2, 5 ), SELCOL( 2 ), defense_location_name( location ) );
    mvwprintz( w, point( 28, 5 ), c_light_gray, defense_location_description( location ) );
    mvwprintz( w, point( 2, 7 ), c_white, _( "Initial Difficulty:" ) );
    mvwprintz( w, point( NUMALIGN( initial_difficulty ), 7 ), SELCOL( 3 ), "%d", initial_difficulty );
    mvwprintz( w, point( 28, 7 ), c_light_gray, _( "The difficulty of the first wave." ) );
    mvwprintz( w, point( 2, 8 ), c_white, _( "Wave Difficulty:" ) );
    mvwprintz( w, point( NUMALIGN( wave_difficulty ), 8 ), SELCOL( 4 ), "%d", wave_difficulty );
    mvwprintz( w, point( 28, 8 ), c_light_gray, _( "The increase of difficulty with each wave." ) );
    mvwprintz( w, point( 2, 10 ), c_white, _( "Time b/w Waves:" ) );
    mvwprintz( w, point( NUMALIGN( to_minutes<int>( time_between_waves ) ), 10 ), SELCOL( 5 ),
               "%d", to_minutes<int>( time_between_waves ) );
    mvwprintz( w, point( 28, 10 ), c_light_gray, _( "The time, in minutes, between waves." ) );
    mvwprintz( w, point( 2, 11 ), c_white, _( "Waves b/w Caravans:" ) );
    mvwprintz( w, point( NUMALIGN( waves_between_caravans ), 11 ), SELCOL( 6 ), "%d",
               waves_between_caravans );
    mvwprintz( w, point( 28, 11 ), c_light_gray, _( "The number of waves in between caravans." ) );
    mvwprintz( w, point( 2, 13 ), c_white, _( "Initial Cash:" ) );
    mvwprintz( w, point( NUMALIGN( initial_cash ), 13 ), SELCOL( 7 ), "%d", initial_cash / 100 );
    mvwprintz( w, point( 28, 13 ), c_light_gray, _( "The amount of money the player starts with." ) );
    mvwprintz( w, point( 2, 14 ), c_white, _( "Cash for 1st Wave:" ) );
    mvwprintz( w, point( NUMALIGN( cash_per_wave ), 14 ), SELCOL( 8 ), "%d", cash_per_wave / 100 );
    mvwprintz( w, point( 28, 14 ), c_light_gray, _( "The cash awarded for the first wave." ) );
    mvwprintz( w, point( 2, 15 ), c_white, _( "Cash Increase:" ) );
    mvwprintz( w, point( NUMALIGN( cash_increase ), 15 ), SELCOL( 9 ), "%d", cash_increase / 100 );
    mvwprintz( w, point( 28, 15 ), c_light_gray, _( "The increase in the award each wave." ) );
    mvwprintz( w, point( 2, 17 ), c_white, _( "Enemy Selection:" ) );
    mvwprintz( w, point( 2, 18 ), TOGCOL( 10, zombies ), _( "Zombies" ) );
    mvwprintz( w, point( 14, 18 ), TOGCOL( 11, specials ), _( "Special Zombies" ) );
    mvwprintz( w, point( 34, 18 ), TOGCOL( 12, spiders ), _( "Spiders" ) );
    mvwprintz( w, point( 46, 18 ), TOGCOL( 13, triffids ), _( "Triffids" ) );
    mvwprintz( w, point( 59, 18 ), TOGCOL( 14, robots ), _( "Robots" ) );
    mvwprintz( w, point( 70, 18 ), TOGCOL( 15, subspace ), _( "Subspace" ) );
    mvwprintz( w, point( 2, 20 ), c_white, _( "Needs:" ) );
    mvwprintz( w, point( 2, 21 ), TOGCOL( 16, hunger ), _( "Food" ) );
    mvwprintz( w, point( 14, 21 ), TOGCOL( 17, thirst ), _( "Water" ) );
    mvwprintz( w, point( 34, 21 ), TOGCOL( 18, sleep ), _( "Sleep" ) );
    mvwprintz( w, point( 46, 21 ), TOGCOL( 19, mercenaries ), _( "Mercenaries" ) );
    mvwprintz( w, point( 59, 21 ), TOGCOL( 20, allow_save ), _( "Allow save" ) );
    wnoutrefresh( w );
}
References _, allow_save, c_light_gray, c_light_red, c_white, cash_increase, cash_per_wave, defense_location_description(), defense_location_name(), defense_style_description(), defense_style_name(), draw_border(), hunger, initial_cash, initial_difficulty, location, mercenaries, mvwprintz(), NUMALIGN, robots, SELCOL, sleep, specials, spiders, style, subspace, thirst, time_between_waves, TOGCOL, triffids, wave_difficulty, waves_between_caravans, catacurses::werase(), catacurses::wnoutrefresh(), and zombies.
Referenced by setup().
setup()
void defense_game::setup () private
Definition at line 466 of file gamemode_defense.cpp.
{
    background_pane bg_pane;
    catacurses::window w;
    ui_adaptor ui;
    ui.on_screen_resize( [&]( ui_adaptor & ui ) {
        w = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                point( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                                       TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 ) );
        ui.position_from_window( w );
    } );
    ui.mark_resize();
    int selection = 1;
    int selection_max = 20;
    ui.on_redraw( [&]( const ui_adaptor & ) {
        refresh_setup( w, selection );
    } );
    input_context ctxt( "DEFENSE_SETUP" );
    ctxt.register_action( "UP", to_translation( "Previous option" ) );
    ctxt.register_action( "DOWN", to_translation( "Next option" ) );
    ctxt.register_action( "LEFT", to_translation( "Cycle option value" ) );
    ctxt.register_action( "RIGHT", to_translation( "Cycle option value" ) );
    ctxt.register_action( "CONFIRM", to_translation( "Toggle option" ) );
    ctxt.register_action( "NEXT_TAB" );
    ctxt.register_action( "PREV_TAB" );
    ctxt.register_action( "START" );
    ctxt.register_action( "HELP_KEYBINDINGS" );
    while( true ) {
        ui_manager::redraw();
        const std::string action = ctxt.handle_input();
        if( action == "START" ) {
            if( !zombies && !specials && !spiders && !triffids && !robots && !subspace ) {
                popup( _( "You must choose at least one monster group!" ) );
            } else {
                return;
            }
        } else if( action == "DOWN" ) {
            if( selection == selection_max ) {
                selection = 1;
            } else {
                selection++;
            }
        } else if( action == "UP" ) {
            if( selection == 1 ) {
                selection = selection_max;
            } else {
                selection--;
            }
        } else {
            switch( selection ) {
                case 1:
                    // Scenario selection
                    if( action == "RIGHT" ) {
                        if( style == static_cast<defense_style>( NUM_DEFENSE_STYLES - 1 ) ) {
                            style = static_cast<defense_style>( 1 );
                        } else {
                            style = static_cast<defense_style>( style + 1 );
                        }
                    }
                    if( action == "LEFT" ) {
                        if( style == static_cast<defense_style>( 1 ) ) {
                            style = static_cast<defense_style>( NUM_DEFENSE_STYLES - 1 );
                        } else {
                            style = static_cast<defense_style>( style - 1 );
                        }
                    }
                    init_to_style( style );
                    break;
                case 2:
                    // Location selection
                    if( action == "RIGHT" ) {
                        if( location == static_cast<defense_location>( NUM_DEFENSE_LOCATIONS - 1 ) ) {
                            location = static_cast<defense_location>( 1 );
                        } else {
                            location = static_cast<defense_location>( location + 1 );
                        }
                    }
                    if( action == "LEFT" ) {
                        if( location == static_cast<defense_location>( 1 ) ) {
                            location = static_cast<defense_location>( NUM_DEFENSE_LOCATIONS - 1 );
                        } else {
                            location = static_cast<defense_location>( location - 1 );
                        }
                    }
                    break;
                case 3:
                    // Difficulty of the first wave
                    if( action == "LEFT" && initial_difficulty > 10 ) {
                        initial_difficulty -= 5;
                    }
                    if( action == "RIGHT" && initial_difficulty < 995 ) {
                        initial_difficulty += 5;
                    }
                    break;
                case 4:
                    // Wave Difficulty
                    if( action == "LEFT" && wave_difficulty > 10 ) {
                        wave_difficulty -= 5;
                    }
                    if( action == "RIGHT" && wave_difficulty < 995 ) {
                        wave_difficulty += 5;
                    }
                    break;
                case 5:
                    if( action == "LEFT" && time_between_waves > 5_minutes ) {
                        time_between_waves -= 5_minutes;
                    }
                    if( action == "RIGHT" && time_between_waves < 995_minutes ) {
                        time_between_waves += 5_minutes;
                    }
                    break;
                case 6:
                    if( action == "LEFT" && waves_between_caravans > 1 ) {
                        waves_between_caravans -= 1;
                    }
                    if( action == "RIGHT" && waves_between_caravans < 50 ) {
                        waves_between_caravans += 1;
                    }
                    break;
                case 7:
                    if( action == "LEFT" && initial_cash > 0 ) {
                        initial_cash -= 100;
                    }
                    if( action == "RIGHT" && initial_cash < 1000000 ) {
                        initial_cash += 100;
                    }
                    break;
                case 8:
                    if( action == "LEFT" && cash_per_wave > 0 ) {
                        cash_per_wave -= 100;
                    }
                    if( action == "RIGHT" && cash_per_wave < 1000000 ) {
                        cash_per_wave += 100;
                    }
                    break;
                case 9:
                    if( action == "LEFT" && cash_increase > 0 ) {
                        cash_increase -= 50;
                    }
                    if( action == "RIGHT" && cash_increase < 1000000 ) {
                        cash_increase += 50;
                    }
                    break;
                case 10:
                    if( action == "CONFIRM" ) {
                        zombies = !zombies;
                        specials = false;
                    }
                    mvwprintz( w, point( 2, 18 ), ( zombies ? c_light_green : c_yellow ), "Zombies" );
                    mvwprintz( w, point( 14, 18 ), c_yellow, _( "Special Zombies" ) );
                    break;
                case 11:
                    if( action == "CONFIRM" ) {
                        specials = !specials;
                        zombies = false;
                    }
                    break;
                case 12:
                    if( action == "CONFIRM" ) {
                        spiders = !spiders;
                    }
                    break;
                case 13:
                    if( action == "CONFIRM" ) {
                        triffids = !triffids;
                    }
                    break;
                case 14:
                    if( action == "CONFIRM" ) {
                        robots = !robots;
                    }
                    break;
                case 15:
                    if( action == "CONFIRM" ) {
                        subspace = !subspace;
                    }
                    break;
                case 16:
                    if( action == "CONFIRM" ) {
                        hunger = !hunger;
                    }
                    break;
                case 17:
                    if( action == "CONFIRM" ) {
                        thirst = !thirst;
                    }
                    break;
                case 18:
                    if( action == "CONFIRM" ) {
                        sleep = !sleep;
                    }
                    break;
                case 19:
                    if( action == "CONFIRM" ) {
                        mercenaries = !mercenaries;
                    }
                    break;
                case 20:
                    if( action == "CONFIRM" ) {
                        allow_save = !allow_save;
                    }
                    break;
            }
        }
    }
}
References _, action, allow_save, c_light_green, c_yellow, cash_increase, cash_per_wave, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::handle_input(), hunger, init_to_style(), initial_cash, initial_difficulty, location, mercenaries, mvwprintz(), catacurses::newwin(), NUM_DEFENSE_LOCATIONS, NUM_DEFENSE_STYLES, popup(), ui_manager::redraw(), refresh_setup(), input_context::register_action(), robots, sleep, specials, spiders, style, subspace, TERMX, TERMY, thirst, time_between_waves, to_translation(), triffids, wave_difficulty, waves_between_caravans, and zombies.
Referenced by init().
spawn_wave()
void defense_game::spawn_wave () private
Definition at line 1278 of file gamemode_defense.cpp.
{
    add_msg( m_info, "********" );
    int diff = initial_difficulty + current_wave * wave_difficulty;
    bool themed_wave = one_in( SPECIAL_WAVE_CHANCE ); // All a single monster type
    g->u.cash += cash_per_wave + ( current_wave - 1 ) * cash_increase;
    std::vector<mtype_id> valid = pick_monster_wave();
    while( diff > 0 ) {
        // Clear out any monsters that exceed our remaining difficulty
        for( auto it = valid.begin(); it != valid.end(); ) {
            const mtype &mt = it->obj();
            if( mt.difficulty > diff ) {
                it = valid.erase( it );
            } else {
                it++;
            }
        }
        if( valid.empty() ) {
            add_msg( m_info, _( "Welcome to Wave %d!" ), current_wave );
            add_msg( m_info, "********" );
            return;
        }
        const mtype &type = random_entry( valid ).obj();
        if( themed_wave ) {
            int num = diff / type.difficulty;
            if( num >= SPECIAL_WAVE_MIN ) {
                // TODO: Do we want a special message here?
                for( int i = 0; i < num; i++ ) {
                    spawn_wave_monster( type.id );
                }
                add_msg( m_info,  special_wave_message( type.nname( 100 ) ) );
                add_msg( m_info, "********" );
                return;
            } else {
                themed_wave = false;    // No partially-themed waves
            }
        }
        diff -= type.difficulty;
        spawn_wave_monster( type.id );
    }
    add_msg( m_info, _( "Welcome to Wave %d!" ), current_wave );
    add_msg( m_info, "********" );
}
References _, add_msg(), cash_increase, cash_per_wave, current_wave, mtype::difficulty, g, initial_difficulty, m_info, num, one_in(), pick_monster_wave(), random_entry(), spawn_wave_monster(), SPECIAL_WAVE_CHANCE, special_wave_message(), SPECIAL_WAVE_MIN, type, and wave_difficulty.
Referenced by per_turn().
spawn_wave_monster()
void defense_game::spawn_wave_monster (const mtype_id & type) private
Definition at line 1356 of file gamemode_defense.cpp.
{
    for( int tries = 0; tries < 1000; tries++ ) {
        point pnt;
        if( location == DEFLOC_HOSPITAL || location == DEFLOC_MALL ) {
            // Always spawn to the north!
            pnt = point( rng( HALF_MAPSIZE_X, HALF_MAPSIZE_X + SEEX ), SEEY );
        } else if( one_in( 2 ) ) {
            pnt = point( rng( HALF_MAPSIZE_X, HALF_MAPSIZE_X + SEEX ), rng( 1, SEEY ) );
            if( one_in( 2 ) ) {
                pnt = point( pnt.x, -pnt.y ) + point( 0, MAPSIZE_Y - 1 );
            }
        } else {
            pnt = point( rng( 1, SEEX ), rng( HALF_MAPSIZE_Y, HALF_MAPSIZE_Y + SEEY ) );
            if( one_in( 2 ) ) {
                pnt = point( -pnt.x, pnt.y ) + point( MAPSIZE_X - 1, 0 );
            }
        }
        monster *const mon = g->place_critter_at( type, tripoint( pnt, g->get_levz() ) );
        if( !mon ) {
            continue;
        }
        monster &tmp = *mon;
        tmp.wander_pos = g->u.pos();
        tmp.wandf = 150;
        // We want to kill!
        tmp.anger = 100;
        tmp.morale = 100;
        return;
    }
}
References monster::anger, DEFLOC_HOSPITAL, DEFLOC_MALL, g, HALF_MAPSIZE_X, HALF_MAPSIZE_Y, location, MAPSIZE_X, MAPSIZE_Y, monster::morale, one_in(), rng(), SEEX, SEEY, type, monster::wander_pos, monster::wandf, point::x, and point::y.
Referenced by spawn_wave().
special_wave_message()
std::string defense_game::special_wave_message (std::string name) private
Definition at line 1388 of file gamemode_defense.cpp.
{
    std::string ret;
    ret += string_format( _( "Wave %d: " ), current_wave );
    // Capitalize
    capitalize_letter( name );
    for( size_t i = 2; i < name.size(); i++ ) {
        if( name[i - 1] == ' ' ) {
            capitalize_letter( name, i );
        }
    }
    switch( rng( 1, 8 ) ) {
        case 1:
            ret += string_format( _( "Invasion of the %s!" ), name );
            break;
        case 2:
            ret += string_format( _( "Attack of the %s!" ), name );
            break;
        case 3:
            ret += string_format( _( "%s Attack!" ), name );
            break;
        case 4:
            ret += string_format( _( "%s from Hell!" ), name );
            break;
        case 5:
            ret += string_format( _( "Beware!  %s!" ), name );
            break;
        case 6:
            ret += string_format( _( "The Day of the %s!" ), name );
            break;
        case 7:
            ret += string_format( _( "Revenge of the %s!" ), name );
            break;
        case 8:
            ret += string_format( _( "Rise of the %s!" ), name );
            break;
    }
    return ret;
}
References _, capitalize_letter(), current_wave, om_direction::name(), cata::hash64_detail::ret, rng(), and string_format().
Referenced by spawn_wave().
Member Data Documentation
allow_save
bool defense_game::allow_save = false private
Definition at line 124 of file gamemode_defense.h.
Referenced by init(), pre_action(), refresh_setup(), and setup().
cash_increase
int defense_game::cash_increase = 0 private
Definition at line 104 of file gamemode_defense.h.
Referenced by init_to_style(), refresh_setup(), setup(), and spawn_wave().
cash_per_wave
int defense_game::cash_per_wave = 0 private
Definition at line 102 of file gamemode_defense.h.
Referenced by init_to_style(), refresh_setup(), setup(), and spawn_wave().
current_wave
int defense_game::current_wave = 0 private
Definition at line 82 of file gamemode_defense.h.
Referenced by caravan(), defense_game(), game_over(), init(), per_turn(), spawn_wave(), and special_wave_message().
defloc_pos
tripoint_om_omt defense_game::defloc_pos private
Definition at line 127 of file gamemode_defense.h.
Referenced by init(), and init_map().
defloc_special
overmap_special_id defense_game::defloc_special private
Definition at line 130 of file gamemode_defense.h.
Referenced by init_map().
hunger
bool defense_game::hunger = false private
Definition at line 114 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), per_turn(), refresh_setup(), and setup().
initial_cash
int defense_game::initial_cash = 0 private
Definition at line 100 of file gamemode_defense.h.
Referenced by init(), init_to_style(), refresh_setup(), and setup().
initial_difficulty
int defense_game::initial_difficulty = 0 private
Definition at line 90 of file gamemode_defense.h.
Referenced by init_to_style(), refresh_setup(), setup(), and spawn_wave().
location
defense_location defense_game::location private
Definition at line 87 of file gamemode_defense.h.
Referenced by init_map(), init_to_style(), pre_action(), refresh_setup(), setup(), and spawn_wave_monster().
mercenaries
bool defense_game::mercenaries = false private
Definition at line 121 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), refresh_setup(), and setup().
robots
bool defense_game::robots = false private
Definition at line 110 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), pick_monster_wave(), refresh_setup(), and setup().
sleep
bool defense_game::sleep = false private
Definition at line 118 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), per_turn(), pre_action(), refresh_setup(), and setup().
specials
bool defense_game::specials = false private
Definition at line 107 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), pick_monster_wave(), refresh_setup(), and setup().
spiders
bool defense_game::spiders = false private
Definition at line 108 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), pick_monster_wave(), refresh_setup(), and setup().
style
defense_style defense_game::style private
Definition at line 85 of file gamemode_defense.h.
Referenced by init_to_style(), refresh_setup(), and setup().
subspace
bool defense_game::subspace = false private
Definition at line 111 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), pick_monster_wave(), refresh_setup(), and setup().
thirst
bool defense_game::thirst = false private
Definition at line 116 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), per_turn(), refresh_setup(), and setup().
time_between_waves
time_duration defense_game::time_between_waves = 0_turns private
Definition at line 95 of file gamemode_defense.h.
Referenced by init_to_style(), per_turn(), refresh_setup(), and setup().
triffids
bool defense_game::triffids = false private
Definition at line 109 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), pick_monster_wave(), refresh_setup(), and setup().
wave_difficulty
int defense_game::wave_difficulty = 0 private
Definition at line 92 of file gamemode_defense.h.
Referenced by init_to_style(), refresh_setup(), setup(), and spawn_wave().
waves_between_caravans
int defense_game::waves_between_caravans = 0 private
Definition at line 97 of file gamemode_defense.h.
Referenced by init_to_style(), per_turn(), refresh_setup(), and setup().
zombies
bool defense_game::zombies = false private
Definition at line 106 of file gamemode_defense.h.
Referenced by defense_game(), init(), init_to_style(), pick_monster_wave(), refresh_setup(), and setup().
The documentation for this struct was generated from the following files:
src/gamemode_defense.h
src/gamemode_defense.cpp