Cataclysm BN: json_item_substitution::trait_requirements Struct Reference
json_item_substitution::trait_requirements Struct Reference
Public Member Functions
trait_requirements (const JsonObject &obj)
trait_requirements ()=default
bool meets_condition (const std::vector< trait_id > &traits) const
Public Attributes
std::vector< trait_id > present
std::vector< trait_id > absent
Detailed Description
Definition at line 37 of file profession.cpp.
Constructor & Destructor Documentation
trait_requirements() [1/2]
json_item_substitution::trait_requirements::trait_requirements (const JsonObject & obj)
Definition at line 544 of file profession.cpp.
{
    for( const std::string line : obj.get_array( "present" ) ) {
        present.emplace_back( line );
    }
    for( const std::string line : obj.get_array( "absent" ) ) {
        absent.emplace_back( line );
    }
}
References JsonObject::get_array(), and line().
trait_requirements() [2/2]
json_item_substitution::trait_requirements::trait_requirements () default
Member Function Documentation
meets_condition()
bool json_item_substitution::trait_requirements::meets_condition (const std::vector< trait_id > & traits) const
Definition at line 638 of file profession.cpp.
{
    const auto pred = [&traits]( const trait_id & s ) {
        return std::find( traits.begin(), traits.end(), s ) != traits.end();
    };
    return std::all_of( present.begin(), present.end(), pred ) &&
           std::none_of( absent.begin(), absent.end(), pred );
}
References detail::find().
Member Data Documentation
absent
std::vector<trait_id> json_item_substitution::trait_requirements::absent
Definition at line 41 of file profession.cpp.
present
std::vector<trait_id> json_item_substitution::trait_requirements::present
Definition at line 40 of file profession.cpp.
Referenced by json_item_substitution::load().
The documentation for this struct was generated from the following file:
src/profession.cpp