Cataclysm BN: overmap_location Struct Reference
overmap_location Struct Reference
#include <overmap_location.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void check () const
void finalize ()
bool test (const oter_id &oter) const
std::vector< oter_type_id > get_all_terrains () const
oter_type_id get_random_terrain () const
Public Attributes
overmap_location_id id
bool was_loaded = false
Private Attributes
std::vector< oter_type_str_id > terrains
std::vector< std::string > flags
Detailed Description
Definition at line 12 of file overmap_location.h.
Member Function Documentation
check()
void overmap_location::check () const
Definition at line 65 of file overmap_location.cpp.
{
    for( const auto &element : terrains ) {
        if( !element.is_valid() ) {
            debugmsg( "In overmap location \"%s\", terrain \"%s\" is invalid.", id.c_str(), element.c_str() );
        }
    }
}
References debugmsg, and terrains.
finalize()
void overmap_location::finalize ()
Definition at line 74 of file overmap_location.cpp.
{
    for( const std::string &elem : flags ) {
        auto it = oter_flags_map.find( elem );
        if( it == oter_flags_map.end() ) {
            continue;
        }
        oter_flags check_flag = it->second;
        for( const oter_t &ter_elem : overmap_terrains::get_all() ) {
            if( ter_elem.has_flag( check_flag ) ) {
                terrains.push_back( ter_elem.get_type_id() );
            }
        }
    }
}
References flags, overmap_terrains::get_all(), oter_flags_map, and terrains.
get_all_terrains()
std::vector< oter_type_id > overmap_location::get_all_terrains () const
Definition at line 56 of file overmap_location.cpp.
{
    std::vector<oter_type_id> ret;
    for( oter_type_str_id elem : terrains ) {
        ret.push_back( elem );
    }
    return ret;
}
References cata::hash64_detail::ret, and terrains.
Referenced by npc::set_omt_destination().
get_random_terrain()
oter_type_id overmap_location::get_random_terrain () const
Definition at line 42 of file overmap_location.cpp.
{
    return random_entry( terrains );
}
References random_entry(), and terrains.
load()
void overmap_location::load (const JsonObject & jo, const std::string & src)
Definition at line 47 of file overmap_location.cpp.
{
    optional( jo, was_loaded, "flags", flags );
    optional( jo, was_loaded, "terrains", terrains );
    if( flags.empty() && terrains.empty() ) {
        jo.throw_error( "At least one flag or terrain must be specified." );
    }
}
References flags, optional(), terrains, JsonObject::throw_error(), and was_loaded.
test()
bool overmap_location::test (const oter_id & oter) const
Definition at line 34 of file overmap_location.cpp.
{
    return std::any_of( terrains.cbegin(), terrains.cend(),
    [ &oter ]( const oter_type_str_id & type ) {
        return oter->type_is( type );
    } );
}
References terrains, and type.
Member Data Documentation
flags
std::vector<std::string> overmap_location::flags private
Definition at line 30 of file overmap_location.h.
Referenced by finalize(), and load().
id
overmap_location_id overmap_location::id
Definition at line 25 of file overmap_location.h.
terrains
std::vector<oter_type_str_id> overmap_location::terrains private
Definition at line 29 of file overmap_location.h.
Referenced by check(), finalize(), get_all_terrains(), get_random_terrain(), load(), and test().
was_loaded
bool overmap_location::was_loaded = false
Definition at line 26 of file overmap_location.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/overmap_location.h
src/overmap_location.cpp