Cataclysm BN: construction Struct Reference
construction Struct Reference
#include <construction.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void check () const
void finalize ()
int adjusted_time () const
int print_time (const catacurses::window &w, const point &, int width, nc_color col) const
std::vector< std::string > get_folded_time_string (int width) const
float time_scale () const
bool is_blacklisted () const
Public Attributes
construction_str_id id
bool was_loaded = false
construction_category_id category = construction_category_id("OTHER")
construction_group_str_id group
translation pre_note
ter_str_id pre_terrain
furn_str_id pre_furniture
ter_str_id post_terrain
furn_str_id post_furniture
item_group_id byproduct_item_group
std::set< std::string > pre_flags
std::set< std::string > post_flags
std::map< skill_id, int > required_skills
Skill->skill level mapping.
std::vector< std::pair< requirement_id, int > > reqs_using
requirement_id requirements
time_duration time
std::function< bool(const tripoint &)> pre_special
std::function< void(const tripoint &)> post_special
std::function< void(const tripoint &)> explain_failure
bool pre_special_is_valid_for_dirt = true
bool vehicle_start = false
bool on_display = true
bool dark_craftable = false
Private Member Functions
std::string get_time_string () const
Detailed Description
Definition at line 38 of file construction.h.
Member Function Documentation
adjusted_time()
int construction::adjusted_time () const
Definition at line 1816 of file construction.cpp.
{
    int final_time = to_moves<int>( time );
    int assistants = 0;
    for( auto &elem : character_funcs::get_crafting_helpers( get_player_character() ) ) {
        if( elem->meets_skill_requirements( *this ) ) {
            assistants++;
        }
    }
    if( assistants >= 2 ) {
        final_time *= 0.4f;
    } else if( assistants == 1 ) {
        final_time *= 0.75f;
    }
    final_time *= time_scale();
    return final_time;
}
References character_funcs::get_crafting_helpers(), get_player_character(), time, and time_scale().
Referenced by activity_handlers::build_do_turn(), and get_time_string().
check()
void construction::check () const
Definition at line 1713 of file construction.cpp.
{
    consistency_report report;
    for( const auto &pr : required_skills ) {
        if( !pr.first.is_valid() ) {
            report.warn( "Invalid skill '%s'", pr.first );
        }
    }
    if( !requirements.is_valid() ) {
        report.warn( "Invalid requirement data '%s'", requirements );
    }
    if( !pre_terrain.is_empty() && !pre_furniture.is_empty() ) {
        report.warn( "Defines both pre_terrain and pre_furniture" );
    }
    if( !post_terrain.is_empty() && !post_furniture.is_empty() ) {
        report.warn( "Defines both post_terrain and post_furniture" );
    }
    if( !pre_terrain.is_empty() && !pre_terrain.is_valid() ) {
        report.warn( "Defines unknown pre_terrain '%s'", pre_terrain );
    }
    if( !pre_furniture.is_empty() && !pre_furniture.is_valid() ) {
        report.warn( "Defines unknown pre_furniture '%s'", pre_furniture );
    }
    if( !post_terrain.is_empty() && !post_terrain.is_valid() ) {
        report.warn( "Defines unknown post_terrain '%s'", post_terrain );
    }
    if( !post_furniture.is_empty() && !post_furniture.is_valid() ) {
        report.warn( "Defines unknown post_furniture '%s'", post_furniture );
    }
    if( !report.is_empty() ) {
        std::string s = report.format( "construction", id.str() );
        debugmsg( s );
    }
}
References debugmsg, consistency_report::format(), consistency_report::is_empty(), string_id< T >::is_empty(), string_id< T >::is_valid(), post_furniture, post_terrain, pre_furniture, pre_terrain, required_skills, requirements, and consistency_report::warn().
finalize()
void construction::finalize ()
Definition at line 1753 of file construction.cpp.
{
    if( !group.is_valid() ) {
        debugmsg( "Invalid construction group (%s) defiend for construction (%s)", group, id );
    }
    if( vehicle_start ) {
        std::vector<item_comp> frame_items;
        for( const auto &e : vpart_info::all() ) {
            const vpart_info &vp = e.second;
            if( !vp.has_flag( flag_INITIAL_PART ) ) {
                continue;
            }
            frame_items.push_back( item_comp( vp.item, 1 ) );
        }
        if( frame_items.empty() ) {
            debugmsg( "No valid frames detected for vehicle construction" );
        }
        const_cast<requirement_data &>( requirements.obj() ).get_components().push_back( frame_items );
    }
    bool is_valid_construction_category = false;
    for( const construction_category &cc : construction_categories::get_all() ) {
        if( category == cc.id ) {
            is_valid_construction_category = true;
            break;
        }
    }
    if( !is_valid_construction_category ) {
        debugmsg( "Invalid construction category (%s) defined for construction (%s)", category, id );
    }
    requirement_data requirements_ = std::accumulate( reqs_using.begin(), reqs_using.end(),
                                     *requirements,
    []( const requirement_data & lhs, const std::pair<requirement_id, int> &rhs ) {
        return lhs + ( *rhs.first * rhs.second );
    } );
    requirement_data::save_requirement( requirements_, requirements );
    reqs_using.clear();
}
References vpart_info::all(), category, debugmsg, flag_INITIAL_PART(), construction_categories::get_all(), group, vpart_info::has_flag(), string_id< T >::id(), string_id< T >::is_valid(), vpart_info::item, string_id< T >::obj(), reqs_using, requirements, requirement_data::save_requirement(), and vehicle_start.
get_folded_time_string()
std::vector< std::string > construction::get_folded_time_string (int width) const
Definition at line 1844 of file construction.cpp.
{
    std::string time_text = get_time_string();
    std::vector<std::string> folded_time = foldstring( time_text, width );
    return folded_time;
}
References foldstring(), and get_time_string().
get_time_string()
std::string construction::get_time_string () const private
Definition at line 1838 of file construction.cpp.
{
    const time_duration turns = time_duration::from_turns( adjusted_time() / 100 );
    return _( "Time to complete: " ) + colorize( to_string( turns ), color_data );
}
References _, adjusted_time(), color_data, colorize(), time_duration::from_turns(), and to_string().
Referenced by get_folded_time_string(), and print_time().
is_blacklisted()
bool construction::is_blacklisted () const
Definition at line 1811 of file construction.cpp.
{
    return requirements->is_blacklisted();
}
References requirement_data::is_blacklisted(), and requirements.
Referenced by construction_sequences::finalize().
load()
void construction::load (const JsonObject & jo, const std::string & src)
Definition at line 1604 of file construction.cpp.
{
    optional( jo, was_loaded, "group", group );
    assign_map_from_array( jo, "required_skills", required_skills );
    mandatory( jo, was_loaded, "category", category );
    mandatory( jo, was_loaded, "time", time );
    const requirement_id req_id( "inline_construction_" + id.str() );
    requirement_data::load_requirement( jo, req_id );
    if( requirements.is_empty() || !req_id->is_empty() ) {
        requirements = req_id;
    }
    if( jo.has_string( "using" ) ) {
        reqs_using = { { requirement_id( jo.get_string( "using" ) ), 1} };
    } else if( jo.has_array( "using" ) ) {
        for( JsonArray cur : jo.get_array( "using" ) ) {
            reqs_using.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
        }
    }
    optional( jo, was_loaded, "pre_note", pre_note );
    optional( jo, was_loaded, "pre_terrain", pre_terrain );
    optional( jo, was_loaded, "pre_furniture", pre_furniture );
    optional( jo, was_loaded, "post_terrain", post_terrain );
    optional( jo, was_loaded, "post_furniture", post_furniture );
    assign( jo, "pre_flags", pre_flags );
    optional( jo, was_loaded, "post_flags", post_flags );
    if( jo.has_member( "byproducts" ) ) {
        byproduct_item_group = item_group::load_item_group( jo.get_member( "byproducts" ),
                               "collection" );
    }
    static const std::map<std::string, std::function<bool( const tripoint & )>> pre_special_map = { {
            { "", construct::check_nothing },
            { "check_empty", construct::check_empty },
            { "check_support", construct::check_support },
            { "check_deconstruct", construct::check_deconstruct },
            { "check_empty_up_OK", construct::check_empty_up_OK },
            { "check_up_OK", construct::check_up_OK },
            { "check_down_OK", construct::check_down_OK },
            { "check_no_trap", construct::check_no_trap },
            { "check_ramp_low", construct::check_ramp_low },
            { "check_ramp_high", construct::check_ramp_high }
        }
    };
    static const std::map<std::string, std::function<void( const tripoint & )>> post_special_map = { {
            { "", construct::done_nothing },
            { "done_trunk_plank", construct::done_trunk_plank },
            { "done_grave", construct::done_grave },
            { "done_vehicle", construct::done_vehicle },
            { "done_deconstruct", construct::done_deconstruct },
            { "done_dig_stair", construct::done_dig_stair },
            { "done_mine_downstair", construct::done_mine_downstair },
            { "done_mine_upstair", construct::done_mine_upstair },
            { "done_wood_stairs", construct::done_wood_stairs },
            { "done_window_curtains", construct::done_window_curtains },
            { "done_extract_maybe_revert_to_dirt", construct::done_extract_maybe_revert_to_dirt },
            { "done_mark_firewood", construct::done_mark_firewood },
            { "done_mark_practice_target", construct::done_mark_practice_target },
            { "done_ramp_low", construct::done_ramp_low },
            { "done_ramp_high", construct::done_ramp_high }
        }
    };
    if( !explain_failure ) {
        explain_failure = construct::failure_standard;
    }
    {
        std::string s;
        optional( jo, was_loaded, "pre_special", s );
        if( !pre_special || !s.empty() ) {
            auto it = pre_special_map.find( s );
            if( it != pre_special_map.end() ) {
                pre_special = it->second;
                pre_special_is_valid_for_dirt = s.empty() || s == "check_empty" || s == "check_support";
                if( s == "check_deconstruct" ) {
                    explain_failure = construct::failure_deconstruct;
                } else {
                    explain_failure = construct::failure_standard;
                }
            } else {
                debugmsg( "Unknown pre_special function \"%s\"", s );
            }
        }
    }
    {
        std::string s;
        optional( jo, was_loaded, "post_special", s );
        if( !post_special || !s.empty() ) {
            auto it = post_special_map.find( s );
            if( it != post_special_map.end() ) {
                post_special = it->second;
            } else {
                debugmsg( "Unknown post_special function \"%s\"", s );
            }
        }
    }
    optional( jo, was_loaded, "vehicle_start", vehicle_start, false );
    optional( jo, was_loaded, "on_display", on_display, true );
    optional( jo, was_loaded, "dark_craftable", dark_craftable, false );
}
References assign(), assign_map_from_array(), byproduct_item_group, category, construct::check_deconstruct(), construct::check_down_OK(), construct::check_empty(), construct::check_empty_up_OK(), construct::check_no_trap(), construct::check_nothing(), construct::check_ramp_high(), construct::check_ramp_low(), construct::check_support(), construct::check_up_OK(), dark_craftable, debugmsg, construct::done_deconstruct(), construct::done_dig_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_downstair(), construct::done_mine_upstair(), construct::done_nothing(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_trunk_plank(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wood_stairs(), explain_failure, construct::failure_deconstruct(), construct::failure_standard(), JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_string(), group, JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), requirement_data::is_empty(), string_id< T >::is_empty(), item_group::load_item_group(), requirement_data::load_requirement(), mandatory(), on_display, optional(), post_flags, post_furniture, post_special, post_terrain, pre_flags, pre_furniture, pre_note, pre_special, pre_special_is_valid_for_dirt, pre_terrain, reqs_using, required_skills, requirements, time, vehicle_start, and was_loaded.
print_time()
int construction::print_time (const catacurses::window & w, const point & p, int width, nc_color col) const
Definition at line 1794 of file construction.cpp.
{
    std::string text = get_time_string();
    return fold_and_print( w, p, width, col, text );
}
References fold_and_print(), and get_time_string().
time_scale()
float construction::time_scale () const
Definition at line 1801 of file construction.cpp.
{
    //incorporate construction time scaling
    if( get_option<int>( "CONSTRUCTION_SCALING" ) == 0 ) {
        return calendar::season_ratio();
    } else {
        return get_option<int>( "CONSTRUCTION_SCALING" ) / 100.0;
    }
}
References calendar::season_ratio().
Referenced by adjusted_time().
Member Data Documentation
byproduct_item_group
item_group_id construction::byproduct_item_group
Definition at line 63 of file construction.h.
Referenced by complete_construction(), and load().
category
construction_category_id construction::category = construction_category_id("OTHER")
Definition at line 48 of file construction.h.
Referenced by finalize(), and load().
dark_craftable
bool construction::dark_craftable = false
Definition at line 107 of file construction.h.
Referenced by load().
explain_failure
std::function<void(const tripoint &)> construction::explain_failure
Definition at line 86 of file construction.h.
Referenced by load().
group
construction_group_str_id construction::group
Definition at line 50 of file construction.h.
Referenced by complete_construction(), finalize(), find_base_construction(), load(), game::print_trap_info(), blueprint_options::query_con(), and iexamine::trap().
id
construction_str_id construction::id
Definition at line 40 of file construction.h.
Referenced by construction_activity(), construction_sequences::finalize(), and place_construction().
on_display
bool construction::on_display = true
Definition at line 104 of file construction.h.
Referenced by load().
post_flags
std::set<std::string> construction::post_flags
Definition at line 69 of file construction.h.
Referenced by complete_construction(), and load().
post_furniture
furn_str_id construction::post_furniture
Definition at line 60 of file construction.h.
Referenced by can_construct(), check(), complete_construction(), construction_sequences::finalize(), find_base_construction(), load(), and blueprint_options::query_con().
post_special
std::function<void(const tripoint &)> construction::post_special
Definition at line 84 of file construction.h.
Referenced by complete_construction(), and load().
post_terrain
ter_str_id construction::post_terrain
Definition at line 59 of file construction.h.
Referenced by can_construct(), check(), complete_construction(), construction_sequences::finalize(), find_base_construction(), load(), and blueprint_options::query_con().
pre_flags
std::set<std::string> construction::pre_flags
Definition at line 66 of file construction.h.
Referenced by can_construct(), and load().
pre_furniture
furn_str_id construction::pre_furniture
Definition at line 56 of file construction.h.
Referenced by check(), construction_sequences::finalize(), find_base_construction(), has_pre_terrain(), and load().
pre_note
translation construction::pre_note
Definition at line 52 of file construction.h.
Referenced by load().
pre_special
std::function<bool(const tripoint &)> construction::pre_special
Definition at line 82 of file construction.h.
Referenced by can_construct(), find_base_construction(), and load().
pre_special_is_valid_for_dirt
bool construction::pre_special_is_valid_for_dirt = true
Definition at line 88 of file construction.h.
Referenced by load().
pre_terrain
ter_str_id construction::pre_terrain
Definition at line 55 of file construction.h.
Referenced by check(), construction_sequences::finalize(), find_base_construction(), has_pre_terrain(), and load().
reqs_using
std::vector<std::pair<requirement_id, int> > construction::reqs_using
Definition at line 75 of file construction.h.
Referenced by finalize(), and load().
required_skills
std::map<skill_id, int> construction::required_skills
Skill->skill level mapping.
Can be empty.
Definition at line 72 of file construction.h.
Referenced by check(), complete_construction(), construction_color(), get_build_reqs_for_furn_ter_ids(), load(), and Character::meets_skill_requirements().
requirements
requirement_id construction::requirements
Definition at line 76 of file construction.h.
Referenced by check(), construction_activity(), finalize(), generic_multi_activity_check_requirement(), get_build_reqs_for_furn_ter_ids(), is_blacklisted(), load(), place_construction(), and player_can_build().
time
time_duration construction::time
Definition at line 79 of file construction.h.
Referenced by adjusted_time(), activity_handlers::build_do_turn(), complete_construction(), get_build_reqs_for_furn_ter_ids(), and load().
vehicle_start
bool construction::vehicle_start = false
Definition at line 101 of file construction.h.
Referenced by finalize(), and load().
was_loaded
bool construction::was_loaded = false
Definition at line 41 of file construction.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/construction.h
src/construction.cpp