Cataclysm BN: oter_t Struct Reference
oter_t Struct Reference
#include <omdata.h>
Public Member Functions
oter_t ()
oter_t (const oter_type_t &type)
oter_t (const oter_type_t &type, om_direction::type dir)
oter_t (const oter_type_t &type, size_t line)
const oter_type_str_id & get_type_id () const
std::string get_mapgen_id () const
oter_id get_rotated (om_direction::type dir) const
std::string get_name () const
std::string get_symbol (const bool from_land_use_code=false) const
uint32_t get_uint32_symbol () const
nc_color get_color (const bool from_land_use_code=false) const
om_direction::type get_dir () const
size_t get_line () const
void get_rotation_and_subtile (int &rotation, int &subtile) const
unsigned char get_see_cost () const
unsigned char get_travel_cost () const
const std::string & get_extras () const
int get_mondensity () const
const overmap_static_spawns & get_static_spawns () const
overmap_land_use_code_id get_land_use_code () const
bool type_is (const oter_type_id &type_id) const
bool type_is (const oter_type_t &type) const
bool has_connection (om_direction::type dir) const
bool has_flag (oter_flags flag) const
bool is_hardcoded () const
bool is_rotatable () const
bool is_linear () const
bool is_river () const
bool is_wooded () const
bool is_lake () const
bool is_lake_shore () const
Public Attributes
oter_str_id id
Private Attributes
const oter_type_t * type
om_direction::type dir = om_direction::type::none
uint32_t symbol
uint32_t symbol_alt
size_t line = 0
Detailed Description
Definition at line 186 of file omdata.h.
Constructor & Destructor Documentation
oter_t() [1/4]
oter_t::oter_t ()
Definition at line 773 of file overmap.cpp.
: oter_t(oter_type_t::null_type) {}
oter_t() [2/4]
oter_t::oter_t (const oter_type_t & type)
Definition at line 775 of file overmap.cpp.
                                        :
    type( &type ),
    id( type.id.str() ),
    symbol( type.symbol ),
    symbol_alt( type.land_use_code ? type.land_use_code->symbol : symbol ) {}
oter_t() [3/4]
oter_t::oter_t (const oter_type_t & type, om_direction::type dir)
Definition at line 781 of file overmap.cpp.
                                                              :
    type( &type ),
    id( type.id.str() + "_" + om_direction::id( dir ) ),
    dir( dir ),
    symbol( om_direction::rotate_symbol( type.symbol, dir ) ),
    symbol_alt( om_direction::rotate_symbol( type.land_use_code ? type.land_use_code->symbol :
                type.symbol, dir ) ),
    line( om_lines::from_dir( dir ) ) {}
oter_t() [4/4]
oter_t::oter_t (const oter_type_t & type, size_t line)
Definition at line 790 of file overmap.cpp.
                                                     :
    type( &type ),
    id( type.id.str() + om_lines::all[line].suffix ),
    symbol( om_lines::all[line].symbol ),
    symbol_alt( om_lines::all[line].symbol ),
    line( line ) {}
Member Function Documentation
get_color()
nc_color oter_t::get_color (const bool from_land_use_code = false) const inline
Definition at line 217 of file omdata.h.
{
            return from_land_use_code ? type->land_use_code->color : type->color;
        }
References overmap_land_use_code::color, oter_type_t::color, oter_type_t::land_use_code, and type.
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), overmap_ui::get_overmap_neighbors(), and photo_def_for_camera_point().
get_dir()
om_direction::type oter_t::get_dir () const inline
Definition at line 221 of file omdata.h.
{
            return dir;
        }
References dir.
Referenced by overmap::build_connection(), mapgen_function_json::generate(), overmap::generate_sub(), get_rotation_and_subtile(), mapgen_railroad_bridge(), mapgen_rotate(), and overmap::place_forest_trailheads().
get_extras()
const std::string & oter_t::get_extras () const inline
Definition at line 237 of file omdata.h.
{
            return type->extras;
        }
References oter_type_t::extras, and type.
Referenced by map::generate().
get_land_use_code()
overmap_land_use_code_id oter_t::get_land_use_code () const inline
Definition at line 249 of file omdata.h.
{
            return type->land_use_code;
        }
References oter_type_t::land_use_code, and type.
get_line()
size_t oter_t::get_line () const inline
Definition at line 225 of file omdata.h.
{
            return line;
        }
References line.
Referenced by overmap::build_anthill(), overmap::build_city_street(), and overmap::build_connection().
get_mapgen_id()
std::string oter_t::get_mapgen_id () const
Definition at line 797 of file overmap.cpp.
{
    return type->has_flag( line_drawing )
           ? type->id.str() + om_lines::mapgen_suffixes[om_lines::all[line].mapgen]
           : type->id.str();
}
References om_lines::all, oter_type_t::has_flag(), oter_type_t::id, line, line_drawing, om_lines::mapgen_suffixes, string_id< T >::str(), and type.
Referenced by map::draw_map(), is_hardcoded(), map::place_items(), and map::place_spawns().
get_mondensity()
int oter_t::get_mondensity () const inline
Definition at line 241 of file omdata.h.
{
            return type->mondensity;
        }
References oter_type_t::mondensity, and type.
Referenced by map::generate().
get_name()
std::string oter_t::get_name () const inline
Definition at line 205 of file omdata.h.
{
            return _( type->name );
        }
References _, oter_type_t::name, and type.
Referenced by memorial_logger::add(), debug_menu::character_edit_menu(), debug_menu::debug(), draw_env_compact(), draw_loc_labels(), draw_location_classic(), map::draw_map(), editmap::mapgen_preview(), photo_def_for_camera_point(), game::pre_print_all_tile_info(), reveal_target(), and overmap_ui::search().
get_rotated()
oter_id oter_t::get_rotated (om_direction::type dir) const
Definition at line 804 of file overmap.cpp.
{
    return type->has_flag( line_drawing )
           ? type->get_linear( om_lines::rotate( this->line, dir ) )
           : type->get_rotated( om_direction::add( this->dir, dir ) );
}
References om_direction::add(), dir, oter_type_t::get_linear(), oter_type_t::get_rotated(), oter_type_t::has_flag(), line, line_drawing, om_lines::rotate(), and type.
Referenced by overmap_ui::draw_ascii(), overmap::place_special(), and overmap_ui::place_ter_or_special().
get_rotation_and_subtile()
void oter_t::get_rotation_and_subtile (int & rotation, int & subtile) const
Definition at line 811 of file overmap.cpp.
{
    if( is_linear() ) {
        const om_lines::type &t = om_lines::all[line];
        rotation = t.rotation;
        subtile = t.subtile;
    } else if( is_rotatable() ) {
        rotation = om_direction::get_num_ccw_rotations( get_dir() );
        subtile = -1;
    } else {
        rotation = 0;
        subtile = -1;
    }
}
References om_lines::all, get_dir(), om_direction::get_num_ccw_rotations(), is_linear(), is_rotatable(), line, om_lines::type::rotation, and om_lines::type::subtile.
get_see_cost()
unsigned char oter_t::get_see_cost () const inline
Definition at line 230 of file omdata.h.
{
            return type->see_cost;
        }
References oter_type_t::see_cost, and type.
Referenced by Character::overmap_los(), and game::update_overmap_seen().
get_static_spawns()
const overmap_static_spawns & oter_t::get_static_spawns () const inline
Definition at line 245 of file omdata.h.
{
            return type->static_spawns;
        }
References oter_type_t::static_spawns, and type.
Referenced by map::generate().
get_symbol()
std::string oter_t::get_symbol (const bool from_land_use_code = false) const inline
Definition at line 209 of file omdata.h.
{
            return utf32_to_utf8( from_land_use_code ? symbol_alt : symbol );
        }
References symbol, symbol_alt, and utf32_to_utf8().
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), and overmap_ui::get_overmap_neighbors().
get_travel_cost()
unsigned char oter_t::get_travel_cost () const inline
Definition at line 233 of file omdata.h.
{
            return type->travel_cost;
        }
References oter_type_t::travel_cost, and type.
get_type_id()
const oter_type_str_id & oter_t::get_type_id () const inline
Definition at line 198 of file omdata.h.
{
            return type->id;
        }
References oter_type_t::id, and type.
Referenced by overmap::build_anthill(), overmap::build_connection(), overmap_ui::draw_om_sidebar(), elevate_bridges(), is_ot_match(), mapgen_railroad(), mapgen_road(), and mapgen_subway().
get_uint32_symbol()
uint32_t oter_t::get_uint32_symbol () const inline
Definition at line 213 of file omdata.h.
{
            return symbol;
        }
References symbol.
has_connection()
bool oter_t::has_connection (om_direction::type dir) const
Definition at line 836 of file overmap.cpp.
{
    // TODO: It's a DAMN UGLY hack. Remove it as soon as possible.
    static const oter_str_id road_manhole( "road_nesw_manhole" );
    if( id == road_manhole ) {
        return true;
    }
    return om_lines::has_segment( line, dir );
}
References dir, om_lines::has_segment(), and line.
has_flag()
bool oter_t::has_flag (oter_flags flag) const inline
Definition at line 258 of file omdata.h.
{
            return type->has_flag( flag );
        }
References oter_type_t::has_flag(), and type.
Referenced by map::draw_connections(), mapgen_road(), mapgen_subway(), and game::vertical_notes().
is_hardcoded()
bool oter_t::is_hardcoded () const
Definition at line 846 of file overmap.cpp.
{
    // TODO: This set only exists because so does the monstrous 'if-else' statement in @ref map::draw_map(). Get rid of both.
    static const std::set<std::string> hardcoded_mapgen = {
        "acid_anthill",
        "anthill",
        "ants_lab",
        "ants_lab_stairs",
        "ice_lab",
        "ice_lab_stairs",
        "ice_lab_core",
        "ice_lab_finale",
        "central_lab",
        "central_lab_stairs",
        "central_lab_core",
        "central_lab_finale",
        "tower_lab",
        "tower_lab_stairs",
        "tower_lab_finale",
        "lab",
        "lab_core",
        "lab_stairs",
        "lab_finale",
        "looted_building",  // pseudo-terrain
        "mine",
        "mine_down",
        "mine_finale",
        "office_tower_1",
        "office_tower_1_entrance",
        "office_tower_b",
        "office_tower_b_entrance",
        "slimepit",
        "slimepit_down",
        "temple",
        "temple_finale",
        "temple_stairs",
        "triffid_finale",
        "triffid_roots"
    };
    return hardcoded_mapgen.find( get_mapgen_id() ) != hardcoded_mapgen.end();
}
References get_mapgen_id().
is_lake()
bool oter_t::is_lake () const inline
Definition at line 283 of file omdata.h.
{
            return type->has_flag( lake );
        }
References oter_type_t::has_flag(), lake, and type.
Referenced by good_fishing_spot(), and is_river_or_lake().
is_lake_shore()
bool oter_t::is_lake_shore () const inline
Definition at line 287 of file omdata.h.
{
            return type->has_flag( lake_shore );
        }
References oter_type_t::has_flag(), lake_shore, and type.
Referenced by good_fishing_spot(), is_river_or_lake(), and mapgen_lake_shore().
is_linear()
bool oter_t::is_linear () const inline
Definition at line 268 of file omdata.h.
{
            return type->is_linear();
        }
References oter_type_t::is_linear(), and type.
Referenced by overmap::build_connection(), and get_rotation_and_subtile().
is_river()
bool oter_t::is_river () const inline
Definition at line 272 of file omdata.h.
{
            return type->has_flag( river_tile );
        }
References oter_type_t::has_flag(), river_tile, and type.
Referenced by is_river(), is_river_or_lake(), and mapgen_lake_shore().
is_rotatable()
bool oter_t::is_rotatable () const inline
Definition at line 264 of file omdata.h.
{
            return type->is_rotatable();
        }
References oter_type_t::is_rotatable(), and type.
Referenced by overmap::build_connection(), mapgen_function_json::generate(), get_rotation_and_subtile(), and overmap_ui::place_ter_or_special().
is_wooded()
bool oter_t::is_wooded () const inline
Definition at line 276 of file omdata.h.
{
            return type->land_use_code == land_use_code_forest ||
                   type->land_use_code == land_use_code_wetland ||
                   type->land_use_code == land_use_code_wetland_forest ||
                   type->land_use_code == land_use_code_wetland_saltwater;
        }
References oter_type_t::land_use_code, land_use_code_forest(), land_use_code_wetland(), land_use_code_wetland_forest(), land_use_code_wetland_saltwater(), and type.
Referenced by activity_handlers::tree_communion_do_turn().
type_is() [1/2]
bool oter_t::type_is (const oter_type_id & type_id) const
Definition at line 826 of file overmap.cpp.
{
    return type->id.id() == type_id;
}
References oter_type_t::id, string_id< T >::id(), and type.
Referenced by overmap_connection::subtype::allows_terrain(), overmap::build_city_street(), and oter_type_t::register_terrain().
type_is() [2/2]
bool oter_t::type_is (const oter_type_t & type) const
Definition at line 831 of file overmap.cpp.
{
    return this->type == &type;
}
References type.
Member Data Documentation
dir
om_direction::type oter_t::dir = om_direction::type::none private
Definition at line 292 of file omdata.h.
Referenced by get_dir(), get_rotated(), and has_connection().
id
oter_str_id oter_t::id
Definition at line 191 of file omdata.h.
Referenced by overmap_ui::draw_om_sidebar(), overmap_ui::place_ter_or_special(), and oter_type_t::register_terrain().
line
size_t oter_t::line = 0 private
Definition at line 295 of file omdata.h.
Referenced by get_line(), get_mapgen_id(), get_rotated(), get_rotation_and_subtile(), and has_connection().
symbol
uint32_t oter_t::symbol private
Definition at line 293 of file omdata.h.
Referenced by get_symbol(), and get_uint32_symbol().
symbol_alt
uint32_t oter_t::symbol_alt private
Definition at line 294 of file omdata.h.
Referenced by get_symbol().
type
const oter_type_t* oter_t::type private
Definition at line 188 of file omdata.h.
Referenced by get_color(), get_extras(), get_land_use_code(), get_mapgen_id(), get_mondensity(), get_name(), get_rotated(), get_see_cost(), get_static_spawns(), get_travel_cost(), get_type_id(), has_flag(), is_lake(), is_lake_shore(), is_linear(), is_river(), is_rotatable(), is_wooded(), and type_is().
The documentation for this struct was generated from the following files:
src/omdata.h
src/overmap.cpp