Cataclysm BN: prepared_item_consumption Struct Reference
prepared_item_consumption Struct Reference
Public Member Functions
prepared_item_consumption (item_consumption_t type, const item &it)
bool consume (Character &c)
Public Attributes
item_consumption_t type
const item & it
Detailed Description
Definition at line 177 of file consumption.cpp.
Constructor & Destructor Documentation
prepared_item_consumption()
prepared_item_consumption::prepared_item_consumption (item_consumption_t type, const item & it) inline
Definition at line 178 of file consumption.cpp.
        : type( type )
        , it( it )
    { }
Member Function Documentation
consume()
bool prepared_item_consumption::consume (Character & c) inline
Definition at line 185 of file consumption.cpp.
{
        // Ugly
        player &p = dynamic_cast<player &>( c );
        switch( type ) {
            case item_consumption_t::none:
                return true;
            case item_consumption_t::tool: {
                comp_selection<tool_comp> selection = comp_selection<tool_comp>();
                selection.comp = tool_comp( it.typeId(), it.type->charges_to_use() );
                selection.use_from = use_from_both;
                p.consume_tools( selection, it.type->charges_to_use() );
                return true;
            }
            case item_consumption_t::component: {
                comp_selection<item_comp> selection = comp_selection<item_comp>();
                selection.comp = item_comp( it.typeId(), 1 );
                selection.use_from = use_from_both;
                return !p.consume_items( selection, 1, is_crafting_component ).empty();
            }
        }
        return false;
    }
References c, itype::charges_to_use(), comp_selection< CompType >::comp, component, player::consume_items(), player::consume_tools(), is_crafting_component(), it, none, tool, type, item::type, item::typeId(), comp_selection< CompType >::use_from, and use_from_both.
Member Data Documentation
it
const item& prepared_item_consumption::it
Definition at line 183 of file consumption.cpp.
Referenced by consume().
type
item_consumption_t prepared_item_consumption::type
Definition at line 182 of file consumption.cpp.
Referenced by consume().
The documentation for this struct was generated from the following file:
src/consumption.cpp