Cataclysm BN: overmap_lake_settings Struct Reference
overmap_lake_settings Struct Reference
#include <regional_settings.h>
Public Member Functions
void finalize ()
overmap_lake_settings ()=default
Public Attributes
double noise_threshold_lake = 0.25
int lake_size_min = 20
int lake_depth = -5
std::vector< std::string > unfinalized_shore_extendable_overmap_terrain
std::vector< oter_id > shore_extendable_overmap_terrain
std::vector< shore_extendable_overmap_terrain_alias > shore_extendable_overmap_terrain_aliases
Detailed Description
Definition at line 184 of file regional_settings.h.
Constructor & Destructor Documentation
overmap_lake_settings()
overmap_lake_settings::overmap_lake_settings () default
Member Function Documentation
finalize()
void overmap_lake_settings::finalize ()
Definition at line 914 of file regional_settings.cpp.
{
    for( const std::string &oid : unfinalized_shore_extendable_overmap_terrain ) {
        const oter_str_id ot( oid );
        if( !ot.is_valid() ) {
            debugmsg( "Tried to add invalid overmap terrain %s to overmap_lake_settings shore_extendable_overmap_terrain.",
                      ot.c_str() );
            continue;
        }
        shore_extendable_overmap_terrain.emplace_back( ot.id() );
    }
    for( shore_extendable_overmap_terrain_alias &alias : shore_extendable_overmap_terrain_aliases ) {
        if( std::find( shore_extendable_overmap_terrain.begin(), shore_extendable_overmap_terrain.end(),
                       alias.alias ) == shore_extendable_overmap_terrain.end() ) {
            debugmsg( " %s was referenced as an alias in overmap_lake_settings shore_extendable_overmap_terrain_alises, but the value is not present in the shore_extendable_overmap_terrain.",
                      alias.alias.c_str() );
            continue;
        }
    }
}
References string_id< T >::c_str(), debugmsg, detail::find(), string_id< T >::id(), string_id< T >::is_valid(), shore_extendable_overmap_terrain, shore_extendable_overmap_terrain_aliases, and unfinalized_shore_extendable_overmap_terrain.
Referenced by regional_settings::finalize().
Member Data Documentation
lake_depth
int overmap_lake_settings::lake_depth = -5
Definition at line 187 of file regional_settings.h.
Referenced by load_overmap_lake_settings().
lake_size_min
int overmap_lake_settings::lake_size_min = 20
Definition at line 186 of file regional_settings.h.
Referenced by load_overmap_lake_settings().
noise_threshold_lake
double overmap_lake_settings::noise_threshold_lake = 0.25
Definition at line 185 of file regional_settings.h.
Referenced by load_overmap_lake_settings().
shore_extendable_overmap_terrain
std::vector<oter_id> overmap_lake_settings::shore_extendable_overmap_terrain
Definition at line 189 of file regional_settings.h.
Referenced by finalize(), and mapgen_lake_shore().
shore_extendable_overmap_terrain_aliases
std::vector<shore_extendable_overmap_terrain_alias> overmap_lake_settings::shore_extendable_overmap_terrain_aliases
Definition at line 190 of file regional_settings.h.
Referenced by finalize(), load_overmap_lake_settings(), and mapgen_lake_shore().
unfinalized_shore_extendable_overmap_terrain
std::vector<std::string> overmap_lake_settings::unfinalized_shore_extendable_overmap_terrain
Definition at line 188 of file regional_settings.h.
Referenced by finalize(), and load_overmap_lake_settings().
The documentation for this struct was generated from the following files:
src/regional_settings.h
src/regional_settings.cpp