Cataclysm BN: inclusive_cuboid< Tripoint, > Struct Template Reference
inclusive_cuboid< Tripoint, > Struct Template Reference
#include <cuboid_rectangle.h>
Public Types
using base = cuboid< Tripoint >
Public Member Functions
constexpr bool contains (const Tripoint &p) const
Public Member Functions inherited from cuboid< Tripoint, >
constexpr cuboid ()=default
constexpr cuboid (const Tripoint &P_MIN, const Tripoint &P_MAX)
template<typename Rectangle >
constexpr cuboid (const Rectangle &R, int Z1, int Z2)
void shrink (const tripoint &amount)
Public Attributes
Tripoint p_min
Tripoint p_max
Public Attributes inherited from cuboid< Tripoint, >
Tripoint p_min
Tripoint p_max
Detailed Description
template<typename Tripoint, decltype(std::declval< cuboid< Tripoint > >(), int()) = 0>
struct inclusive_cuboid< Tripoint, >
Definition at line 104 of file cuboid_rectangle.h.
Member Typedef Documentation
base
template<typename Tripoint , decltype(std::declval< cuboid< Tripoint > >(), int()) = 0> using inclusive_cuboid< Tripoint, >::base = cuboid<Tripoint>
Definition at line 105 of file cuboid_rectangle.h.
Member Function Documentation
contains()
template<typename Tripoint , decltype(std::declval< cuboid< Tripoint > >(), int()) = 0> constexpr bool inclusive_cuboid< Tripoint, >::contains (const Tripoint & p) const inline constexpr
Definition at line 110 of file cuboid_rectangle.h.
{
        using Traits = point_traits<Tripoint>;
        return Traits::x( p ) >= Traits::x( p_min ) && Traits::x( p ) <= Traits::x( p_max ) &&
               Traits::y( p ) >= Traits::y( p_min ) && Traits::y( p ) <= Traits::y( p_max ) &&
               Traits::z( p ) >= Traits::z( p_min ) && Traits::z( p ) <= Traits::z( p_max );
    }
References inclusive_cuboid< Tripoint, >::p_max, and inclusive_cuboid< Tripoint, >::p_min.
Referenced by map::build_obstacle_cache(), and game::get_fishable_locations().
Member Data Documentation
p_max
template<typename Tripoint , decltype(std::declval< cuboid< Tripoint > >(), int()) = 0> Tripoint cuboid< Tripoint, >::p_max
Definition at line 73 of file cuboid_rectangle.h.
Referenced by shape::bounding_box(), offset_shape::bounding_box(), rotate_z_shape::bounding_box(), inclusive_cuboid< Tripoint, >::contains(), and midpoint().
p_min
template<typename Tripoint , decltype(std::declval< cuboid< Tripoint > >(), int()) = 0> Tripoint cuboid< Tripoint, >::p_min
Definition at line 72 of file cuboid_rectangle.h.
Referenced by shape::bounding_box(), offset_shape::bounding_box(), rotate_z_shape::bounding_box(), inclusive_cuboid< Tripoint, >::contains(), and midpoint().
The documentation for this struct was generated from the following file:
src/cuboid_rectangle.h