Cataclysm BN: cata::tuple_hash Struct Reference
cata::tuple_hash Struct Reference
#include <hash_utils.h>
Public Member Functions
template<typename ... TT>
std::size_t operator() (const std::tuple< TT... > &tt) const
template<class A , class B >
std::size_t operator() (const std::pair< A, B > &v) const
Detailed Description
Definition at line 46 of file hash_utils.h.
Member Function Documentation
operator()() [1/2]
template<class A , class B > std::size_t cata::tuple_hash::operator() (const std::pair< A, B > & v) const inline
Definition at line 55 of file hash_utils.h.
{
        std::size_t seed = 0;
        hash_combine( seed, v.first );
        hash_combine( seed, v.second );
        return seed;
    }
References cata::hash_combine(), and iuse::seed().
operator()() [2/2]
template<typename ... TT> std::size_t cata::tuple_hash::operator() (const std::tuple< TT... > & tt) const inline
Definition at line 48 of file hash_utils.h.
{
        size_t seed = 0;
        tuple_hash_detail::Impl<std::tuple<TT...> >::apply( seed, tt );
        return seed;
    }
References apply(), and iuse::seed().
The documentation for this struct was generated from the following file:
src/hash_utils.h