Cataclysm BN: coord_transformation Struct Reference
coord_transformation Struct Reference
Public Member Functions
point transform (point p) const
tripoint transform (point p, int z) const
orientation transform (orientation dir) const
node_address transform (point p, orientation dir) const
coord_transformation inverse () const
Public Attributes
point pre_offset
quad_rotation rotation
point post_offset
Detailed Description
Definition at line 236 of file vehicle_autodrive.cpp.
Member Function Documentation
inverse()
coord_transformation coord_transformation::inverse () const
Definition at line 549 of file vehicle_autodrive.cpp.
{
    return { post_offset, -rotation, pre_offset };
}
References post_offset, pre_offset, and rotation.
Referenced by vehicle::get_debug_overlay_data().
transform() [1/4]
orientation coord_transformation::transform (orientation dir) const
Definition at line 539 of file vehicle_autodrive.cpp.
{
    return dir + rotation;
}
References rotation.
transform() [2/4]
point coord_transformation::transform (point p) const
Definition at line 529 of file vehicle_autodrive.cpp.
{
    return rotate( p - pre_offset, rotation ) + post_offset;
}
References post_offset, pre_offset, rotate(), and rotation.
Referenced by vehicle::autodrive_controller::compute_goal_zone(), vehicle::autodrive_controller::compute_valid_positions(), vehicle::get_debug_overlay_data(), and transform().
transform() [3/4]
tripoint coord_transformation::transform (point p, int z) const
Definition at line 534 of file vehicle_autodrive.cpp.
{
    return tripoint( transform( p ), z );
}
References transform().
transform() [4/4]
node_address coord_transformation::transform (point p, orientation dir) const
Definition at line 544 of file vehicle_autodrive.cpp.
{
    return make_node_address( transform( p ), transform( dir ) );
}
References make_node_address(), and transform().
Member Data Documentation
post_offset
point coord_transformation::post_offset
Definition at line 239 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), inverse(), and transform().
pre_offset
point coord_transformation::pre_offset
Definition at line 237 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), inverse(), and transform().
rotation
quad_rotation coord_transformation::rotation
Definition at line 238 of file vehicle_autodrive.cpp.
Referenced by inverse(), and transform().
The documentation for this struct was generated from the following file:
src/vehicle_autodrive.cpp