Cataclysm BN: overmap_special_spawns Struct Reference
overmap_special_spawns Struct Reference
#include <overmap_special.h>
Public Member Functions
bool operator== (const overmap_special_spawns &rhs) const
void deserialize (const JsonObject &jo)
Public Member Functions inherited from overmap_spawns
overmap_spawns ()
bool operator== (const overmap_spawns &rhs) const
Public Attributes
numeric_interval< int > radius
Public Attributes inherited from overmap_spawns
string_id< MonsterGroup > group
numeric_interval< int > population
Additional Inherited Members
Protected Member Functions inherited from overmap_spawns
void deserialize (const JsonObject &jo)
Detailed Description
Definition at line 38 of file overmap_special.h.
Member Function Documentation
deserialize()
void overmap_special_spawns::deserialize (const JsonObject & jo)
Definition at line 482 of file overmap.cpp.
{
    overmap_spawns::deserialize( jo );
    jo.read( "radius", radius );
}
References overmap_spawns::deserialize(), radius, and JsonObject::read().
operator==()
bool overmap_special_spawns::operator== (const overmap_special_spawns & rhs) const inline
Definition at line 41 of file overmap_special.h.
{
        return overmap_spawns::operator==( rhs ) && radius == rhs.radius;
    }
References overmap_spawns::operator==(), and radius.
Member Data Documentation
radius
numeric_interval<int> overmap_special_spawns::radius
Definition at line 39 of file overmap_special.h.
Referenced by deserialize(), operator==(), and overmap::place_special().
The documentation for this struct was generated from the following files:
src/overmap_special.h
src/overmap.cpp