Cataclysm BN: act_progress_message Struct Reference
act_progress_message Struct Reference
#include <activity_actor.h>
Static Public Member Functions
static act_progress_message make_full (std::string &&text)
The text will completely overwrite default message.
static act_progress_message make_extra_info (std::string &&text)
The text will be appended to default message.
static act_progress_message make_empty ()
There will be no message shown.
Public Attributes
bool implemented = true
Whether activity actor implements the method.
cata::optional< std::string > msg_extra_info
cata::optional< std::string > msg_full
Detailed Description
Definition at line 18 of file activity_actor.h.
Member Function Documentation
make_empty()
static act_progress_message act_progress_message::make_empty () inline static
There will be no message shown.
Definition at line 49 of file activity_actor.h.
{
        return act_progress_message{};
    }
make_extra_info()
static act_progress_message act_progress_message::make_extra_info (std::string && text) inline static
The text will be appended to default message.
Definition at line 40 of file activity_actor.h.
{
        act_progress_message ret;
        ret.msg_extra_info = std::move( text );
        return ret;
    }
References avatar_action::move(), and cata::hash64_detail::ret.
Referenced by disassemble_activity_actor::get_progress_message().
make_full()
static act_progress_message act_progress_message::make_full (std::string && text) inline static
The text will completely overwrite default message.
Definition at line 31 of file activity_actor.h.
{
        act_progress_message ret;
        ret.msg_full = std::move( text );
        return ret;
    }
References avatar_action::move(), and cata::hash64_detail::ret.
Member Data Documentation
implemented
bool act_progress_message::implemented = true
Whether activity actor implements the method.
TODO: remove once migration to actors is complete.
Definition at line 23 of file activity_actor.h.
Referenced by player_activity::get_progress_message(), and activity_actor::get_progress_message().
msg_extra_info
cata::optional<std::string> act_progress_message::msg_extra_info
Definition at line 25 of file activity_actor.h.
Referenced by player_activity::get_progress_message().
msg_full
cata::optional<std::string> act_progress_message::msg_full
Definition at line 26 of file activity_actor.h.
Referenced by player_activity::get_progress_message().
The documentation for this struct was generated from the following file:
src/activity_actor.h