Cataclysm BN: itype Struct Reference
itype Struct Reference
#include <itype.h>
Public Types
using FlagsSetType = std::set< std::string >
Public Member Functions
itype ()
virtual ~itype ()
int damage_min () const
int damage_max () const
std::string get_item_type_string () const
std::string nname (unsigned int quantity) const
const itype_id & get_id () const
bool count_by_charges () const
int charges_default () const
int charges_to_use () const
int charge_factor () const
int maximum_charges () const
bool can_have_charges () const
int charges_per_volume (const units::volume &vol) const
Number of (charges of) this type of item that fit into the given volume.
bool has_use () const
bool has_flag (const std::string &flag) const
bool has_flag (const flag_str_id &flag) const
const FlagsSetType & get_flags () const
bool can_use (const std::string &iuse_name) const
const use_function * get_use (const std::string &iuse_name) const
int invoke (player &p, item &it, const tripoint &pos) const
int invoke (player &p, item &it, const tripoint &pos, const std::string &iuse_name) const
void tick (player &p, item &it, const tripoint &pos) const
Public Attributes
std::vector< std::pair< itype_id, mod_id > > src
cata::value_ptr< islot_container > container
Slots for various item type properties.
cata::value_ptr< islot_tool > tool
cata::value_ptr< islot_comestible > comestible
cata::value_ptr< islot_brewable > brewable
cata::value_ptr< islot_armor > armor
cata::value_ptr< islot_pet_armor > pet_armor
cata::value_ptr< islot_book > book
cata::value_ptr< islot_mod > mod
cata::value_ptr< islot_engine > engine
cata::value_ptr< islot_wheel > wheel
cata::value_ptr< islot_fuel > fuel
cata::value_ptr< islot_gun > gun
cata::value_ptr< islot_gunmod > gunmod
cata::value_ptr< islot_magazine > magazine
cata::value_ptr< islot_battery > battery
cata::value_ptr< islot_bionic > bionic
cata::value_ptr< islot_ammo > ammo
cata::value_ptr< islot_seed > seed
cata::value_ptr< islot_artifact > artifact
cata::value_ptr< relic > relic_data
cata::value_ptr< islot_milling > milling_data
bool was_loaded = false
itype_id looks_like
itype_id repairs_like
std::string snippet_category
translation description
ascii_art_id picture_id
cata::optional< itype_id > default_container
std::map< quality_id, int > qualities
std::map< std::string, std::string > properties
std::vector< conditional_name > conditional_names
std::vector< material_id > materials
std::map< std::string, use_function > use_methods
Actions an instance can perform (if any) indexed by action type.
use_function drop_action
Action to take BEFORE the item is placed on map.
std::set< emit_id > emits
Fields to emit when item is in active state.
std::set< matec_id > techniques
std::map< skill_id, int > min_skills
int min_str = 0
int min_dex = 0
int min_int = 0
int min_per = 0
phase_id phase = SOLID
explosion_data explosion
bool explode_in_fire = false
bool countdown_destroy = false
Is item destroyed after the countdown action is run?
int countdown_interval = 0
Default countdown interval (if any) for item.
use_function countdown_action
Action to take when countdown expires.
bool rigid = true
std::array< int, NUM_DT > melee
Damage output in melee for zero or more damage types.
damage_instance thrown_damage
Base damage output when thrown.
int m_to_hit = 0
unsigned light_emission = 0
item_category_id category_force
If set via JSON forces item category to this (preventing automatic assignment)
std::string sym
nc_color color = c_white
std::set< itype_id > repair
Damage scale compared to the old float damage value.
std::vector< recipe_id > recipes
What recipes can make this item.
std::set< fault_id > faults
What faults (if any) can occur.
std::map< ammotype, std::set< itype_id > > magazines
Magazine types (if any) for each ammo type that can be used to reload this item.
std::map< ammotype, itype_id > magazine_default
Default magazine for each ammo type that can be used to reload this item.
units::volume magazine_well = 0_ml
Volume above which the magazine starts to protrude from the item and add extra volume.
layer_level layer = layer_level::MAX_CLOTHING_LAYER
float solar_efficiency = 0
Efficiency of solar energy conversion for solarpacks.
FlagsSetType item_tags
Non-negative properties
After loading from JSON these properties guaranteed to be zero or positive
units::mass weight = 0_gram
Weight of item (or each stack member)
units::mass integral_weight = -1_gram
Weight difference with the part it replaces for mods.
units::volume volume = 0_ml
Space occupied by items of this type CAUTION: value given is for a default-sized stack.
units::volume integral_volume = -1_ml
Space consumed when integrated as part of another item (defaults to volume) CAUTION: value given is for a default-sized stack.
int stack_size = 0
Number of items per above volume for count_by_charges items.
units::money price = 0_cent
Value before cataclysm.
units::money price_post = -1_cent
Value after cataclysm, dependent upon practical usages.
Static Public Attributes
static constexpr int damage_scale = 1000
Protected Attributes
itype_id id = itype_id::NULL_ID()
translation name = no_translation("none")
unique string identifier for this type
Private Attributes
bool stackable_ = false
Can item be combined with other identical items?
int damage_min_ = -1000
Minimum and maximum amount of damage to an item (state of maximum repair).
int damage_max_ = +4000
Friends
class Item_factory
Detailed Description
Definition at line 836 of file itype.h.
Member Typedef Documentation
FlagsSetType
using itype::FlagsSetType = std::set<std::string>
Definition at line 839 of file itype.h.
Constructor & Destructor Documentation
itype()
itype::itype ()
Definition at line 39 of file itype.cpp.
{
    melee.fill( 0 );
}
~itype()
itype::~itype () virtual default
Member Function Documentation
can_have_charges()
bool itype::can_have_charges () const
Definition at line 219 of file itype.cpp.
{
    if( count_by_charges() ) {
        return true;
    }
    if( tool && tool->max_charges > 0 ) {
        return true;
    }
    if( gun && gun->clip > 0 ) {
        return true;
    }
    if( has_flag( "CAN_HAVE_CHARGES" ) ) {
        return true;
    }
    return false;
}
References count_by_charges(), gun, has_flag(), and tool.
Referenced by chop_plank_activity(), chop_tree_activity(), item::io(), Item_modifier::modify(), activity_handlers::shear_finish(), and activity_handlers::start_fire_finish().
can_use()
bool itype::can_use (const std::string & iuse_name) const
Definition at line 161 of file itype.cpp.
{
    return get_use( iuse_name ) != nullptr;
}
References get_use().
Referenced by item::armor_protection_info(), item::book_info(), can_do_activity_there(), item::can_holster(), item::color_in_inventory(), Character::consume_effects(), Character::eat(), item::final_info(), Item_factory::finalize_pre(), read_inventory_preset::get_denial(), item::is_bandolier(), item::is_deployable(), item::is_holster(), avatar_funcs::is_pet_food(), mine_activity(), avatar_action::move(), item::on_takeoff(), item::on_wear(), item::process_tool(), read(), read_inventory_preset::read_inventory_preset(), and avatar_action::reload().
charge_factor()
int itype::charge_factor () const
Definition at line 118 of file itype.cpp.
{
    return tool ? tool->charge_factor : 1;
}
References tool.
charges_default()
int itype::charges_default () const
Definition at line 98 of file itype.cpp.
{
    if( tool ) {
        return tool->def_charges;
    } else if( comestible ) {
        return comestible->def_charges;
    } else if( ammo ) {
        return ammo->def_charges;
    }
    return count_by_charges() ? 1 : 0;
}
References ammo, comestible, count_by_charges(), and tool.
Referenced by recipe::disassembly_batch_size(), Item_factory::finalize_pre(), item::item(), recipe::makes_amount(), and print_items().
charges_per_volume()
int itype::charges_per_volume (const units::volume & vol) const
Number of (charges of) this type of item that fit into the given volume.
May return 0 if not even one charge fits into the volume.
Definition at line 131 of file itype.cpp.
{
    if( volume == 0_ml ) {
        // TODO: items should not have 0 volume at all!
        return item::INFINITE_CHARGES;
    }
    return ( count_by_charges() ? stack_size : 1 ) * vol / volume;
}
References count_by_charges(), item::INFINITE_CHARGES, stack_size, and volume.
Referenced by vehicle_part::ammo_capacity(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::kiln_empty(), iexamine::kiln_full(), and iexamine::reload_furniture().
charges_to_use()
int itype::charges_to_use () const
Definition at line 110 of file itype.cpp.
{
    if( tool ) {
        return static_cast<int>( tool->charges_per_use );
    }
    return 1;
}
References tool.
Referenced by iuse::adrenaline_injector(), alcohol(), item::ammo_required(), iuse::antiasthmatic(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antifungal(), iuse::antiparasitic(), iuse::artifact(), iuse::bell(), iuse::blech(), iuse::blech_because_unclean(), iuse::blood_draw(), iuse::boltcutters(), iuse::c4(), iuse::call_of_tindalos(), iuse::camera(), iuse::can_goo(), fireweapon_off_actor::can_use(), manualnoise_actor::can_use(), iuse::chew(), iuse::chop_logs(), chop_plank_activity(), iuse::chop_tree(), chop_tree_activity(), iuse::clear_rubble(), prepared_item_consumption::consume(), iuse::contacts(), iuse::crowbar(), iuse::datura(), iuse::dig(), iuse::dig_channel(), iuse::directional_antenna(), iuse::directional_hologram(), iuse::dive_tank(), iuse::dog_whistle(), iuse::ecig(), iuse::ehandcuffs(), iuse::einktabletpc(), iuse::extinguisher(), iuse::eyedrops(), iuse::fill_pit(), heal_actor::finish_using(), iuse::firecracker(), iuse::flumed(), iuse::flusleep(), iuse::foodperson(), iuse::fungicide(), iuse::gasmask(), iuse::geiger(), iuse::granade(), iuse::granade_act(), iuse::gun_repair(), iuse::hacksaw(), iuse::hairkit(), iuse::hammer(), iuse::handle_ground_graffiti(), iuse::honeycomb(), iuse::inhaler(), vehicle::interact_with(), iuse::jackhammer(), iuse::jet_injector(), iuse::lumber(), iuse::makemound(), iuse::marloss(), iuse::marloss_gel(), iuse::marloss_seed(), iuse::meditate(), iuse::melatonin_tablet(), iuse::meth(), iuse::mind_splicer(), iuse::mininuke(), iuse::modify_grid_connections(), iuse::mop(), iuse::mp3(), iuse::mp3_on(), mutagen_common_checks(), iuse::mycus(), iuse::noise_emitter_off(), iuse::noise_emitter_on(), iuse::oxygen_bottle(), iuse::pheromone(), iuse::plantblech(), iuse::poison(), iuse::portal(), iuse::prozac(), iuse::purifier(), iuse::purify_iv(), iuse::purify_smart(), iuse::radglove(), iuse::radio_off(), iuse::radio_on(), iuse::radiocar(), iuse::radiocaron(), iuse::radiocontrol(), iuse::remoteveh(), iuse::rm13armor_off(), iuse::rm13armor_on(), iuse::robotcontrol(), iuse::seed(), iuse::sewage(), iuse::shavekit(), activity_handlers::shear_finish(), iuse::shocktonfa_off(), iuse::siphon(), iuse::sleep(), iuse::smoking(), activity_handlers::start_fire_finish(), iuse::stimpack(), iuse::strong_antibiotic(), iuse::talking_doll(), iuse::tazer(), iuse::teleport(), iuse::thorazine(), toolweapon_off(), toolweapon_on(), iuse::towel_common(), vehicle::update_time(), consume_drug_iuse::use(), pick_lock_actor::use(), firestarter_actor::use(), fireweapon_off_actor::use(), fireweapon_on_actor::use(), manualnoise_actor::use(), heal_actor::use(), mutagen_actor::use(), mutagen_iv_actor::use(), install_bionic_actor::use(), cast_spell_actor::use(), iuse::vaccine(), iuse::vibe(), iuse::vortex(), iuse::weak_antibiotic(), iuse::weed_cake(), and iuse::xanax().
count_by_charges()
bool itype::count_by_charges () const
Definition at line 93 of file itype.cpp.
{
    return stackable_ || ammo || comestible;
}
References ammo, comestible, and stackable_.
Referenced by butchery_drops_harvest(), can_have_charges(), charges_default(), charges_per_volume(), item::count_by_charges(), damage_max(), damage_min(), recipe::disassembly_batch_size(), recipe::finalize(), Item_factory::finalize_pre(), print_items(), and item_comp::to_string().
damage_max()
int itype::damage_max () const
Definition at line 51 of file itype.cpp.
{
    return count_by_charges() ? 0 : damage_max_;
}
References count_by_charges(), and damage_max_.
Referenced by Item_factory::finalize_pre(), and item::max_damage().
damage_min()
int itype::damage_min () const
Definition at line 46 of file itype.cpp.
{
    return count_by_charges() ? 0 : damage_min_;
}
References count_by_charges(), and damage_min_.
Referenced by Item_factory::finalize_pre(), and item::min_damage().
get_flags()
const itype::FlagsSetType & itype::get_flags () const
Definition at line 156 of file itype.cpp.
{
    return item_tags;
}
References item_tags.
Referenced by item::final_info(), item::get_comestible_fun(), getGasDiscountCardQuality(), item::inherit_flags(), and item::item().
get_id()
const itype_id & itype::get_id () const
Definition at line 88 of file itype.cpp.
{
    return id;
}
References id.
Referenced by item::ammo_current(), turret_data::ammo_options(), item::ammo_set(), item::basic_info(), Character::compute_nutrient_range(), Character::deactivate_bionic(), mattack::eat_food(), recipe_dictionary::finalize(), Item_factory::finalize_pre(), npc_ai::gun_value(), Character::has_enough_anesth(), item::io(), npc_ai::melee_value(), new_artifact(), new_natural_artifact(), item::operator<(), Character::process_items(), iexamine::reload_furniture(), item::typeId(), iexamine::use_furn_fake_item(), and npc_ai::weapon_value().
get_item_type_string()
std::string itype::get_item_type_string () const
Definition at line 56 of file itype.cpp.
{
    if( tool ) {
        return "TOOL";
    } else if( comestible ) {
        return "FOOD";
    } else if( container ) {
        return "CONTAINER";
    } else if( armor ) {
        return "ARMOR";
    } else if( book ) {
        return "BOOK";
    } else if( gun ) {
        return "GUN";
    } else if( bionic ) {
        return "BIONIC";
    } else if( ammo ) {
        return "AMMO";
    }
    return "misc";
}
References ammo, armor, book, comestible, container, gun, and tool.
get_use()
const use_function * itype::get_use (const std::string & iuse_name) const
Definition at line 166 of file itype.cpp.
{
    const auto iter = use_methods.find( iuse_name );
    return iter != use_methods.end() ? &iter->second : nullptr;
}
References use_methods.
Referenced by map::add_item(), item::ammo_capacity(), apply_lock_picking_tool(), item::can_holster(), can_use(), item::final_info(), find_best_lock_picking_tool(), npc::find_dangerous_explosives(), iexamine::fireplace(), npc::get_healing_item(), item::get_total_capacity(), item::get_use_internal(), grenade_helper(), npc::has_healing_options(), invoke(), mattack::kamikaze(), avatar_action::reload(), and activity_handlers::start_fire_do_turn().
has_flag() [1/2]
bool itype::has_flag (const flag_str_id & flag) const
Definition at line 151 of file itype.cpp.
{
    return item_tags.count( flag.str() );
}
References item_tags, and string_id< T >::str().
has_flag() [2/2]
bool itype::has_flag (const std::string & flag) const
Definition at line 146 of file itype.cpp.
{
    return item_tags.count( flag );
}
References item_tags.
Referenced by can_have_charges(), Item_factory::check_definitions(), Character::compute_nutrient_range(), Item_factory::finalize_pre(), item::has_flag(), Item_factory::npc_implied_flags(), and ranged::throw_item().
has_use()
bool itype::has_use () const
Definition at line 141 of file itype.cpp.
{
    return !use_methods.empty();
}
References use_methods.
Referenced by Character::consume_med(), Character::eat(), item::has_use(), invoke(), activatable_inventory_preset::is_shown(), examine_item_menu::rate_action_use(), try_consume(), and avatar_funcs::use_item().
invoke() [1/2]
int itype::invoke (player & p, item & it, const tripoint & pos) const
Definition at line 180 of file itype.cpp.
{
    if( !has_use() ) {
        return 0;
    }
    return invoke( p, it, pos, use_methods.begin()->first );
}
References has_use(), invoke(), and use_methods.
Referenced by npc::activate_item(), Character::consume_med(), Character::eat(), emit_radio_signal(), npc::heal_player(), npc::heal_self(), invoke(), Character::invoke_item(), item::process_extinguish(), item::process_internal(), item::process_tool(), try_consume(), avatar_funcs::unload_item(), and vehicle::use_monster_capture().
invoke() [2/2]
int itype::invoke (player & p, item & it, const tripoint & pos, const std::string & iuse_name) const
Definition at line 188 of file itype.cpp.
{
    const use_function *use = get_use( iuse_name );
    if( use == nullptr ) {
        debugmsg( "Tried to invoke %s on a %s, which doesn't have this use_function",
                  iuse_name, nname( 1 ) );
        return 0;
    }
    const auto ret = use->can_call( p, it, false, pos );
    if( !ret.success() ) {
        p.add_msg_if_player( m_info, ret.str() );
        return 0;
    }
    // used for grenades and such, to increase kill count
    // invoke is called a first time with transform, when the explosive item is activated
    // then a second time with draw explosion
    // the player responsible of the explosion is the one that activated the object
    if( iuse_name == "transform" ) {
        it.activated_by = p.get_safe_reference();
    }
    return use->call( p, it, false, pos );
}
References item::activated_by, player::add_msg_if_player(), debugmsg, Character::get_safe_reference(), get_use(), m_info, nname(), cata::hash64_detail::ret, and game_menus::inv::use().
maximum_charges()
int itype::maximum_charges () const
Definition at line 123 of file itype.cpp.
{
    if( tool ) {
        return tool->max_charges;
    }
    return 0;
}
References tool.
Referenced by iuse::ehandcuffs(), item::process_cable(), Character::process_items(), vehicle_part::properties_to_item(), item::reset_cable(), and mattack::riotbot().
nname()
std::string itype::nname (unsigned int quantity) const
Definition at line 78 of file itype.cpp.
{
    // Always use singular form for liquids.
    // (Maybe gases too?  There are no gases at the moment)
    if( phase == LIQUID ) {
        quantity = 1;
    }
    return name.translated( quantity );
}
References LIQUID, name, phase, and translation::translated().
Referenced by butchery_drops_harvest(), veh_interact::calc_overview(), iuse::capture_monster_act(), debug_menu::character_edit_menu(), Character::consume_med(), item::contain_monster(), item::display_name(), avatar_action::fire_wielded_weapon(), item::gun_info(), avatar_funcs::gunmod_remove(), invoke(), new_artifact(), memorial_logger::notify(), item::operator<(), target_ui::panel_gun_info(), parse_tags(), print_items(), iexamine::reload_furniture(), character_funcs::select_ammo(), item_comp::to_string(), try_start_hacking(), and item::type_name().
tick()
void itype::tick (player & p, item & it, const tripoint & pos) const
Definition at line 172 of file itype.cpp.
{
    // Maybe should move charge decrementing here?
    for( auto &method : use_methods ) {
        method.second.call( p, it, true, pos );
    }
}
References use_methods.
Referenced by item::process_tool().
Friends And Related Function Documentation
Item_factory
friend class Item_factory friend
Definition at line 837 of file itype.h.
Member Data Documentation
ammo
cata::value_ptr<islot_ammo> itype::ammo
Definition at line 864 of file itype.h.
Referenced by item::ammo_info(), turret_data::ammo_options(), item::ammo_set(), item::ammo_type(), charges_default(), Item_factory::check_definitions(), count_by_charges(), cycle_action(), item::detonate(), aim_activity_actor::do_turn(), vehicle_prototype::finalize(), Item_factory::finalize_pre(), ranged::fire_gun(), avatar_action::fire_wielded_weapon(), inventory::form_from_map(), get_item_type_string(), item::gun_dispersion(), item::gun_info(), item::gun_noise(), item::gun_range(), item::gun_recoil(), npc_ai::gun_value(), ranged::handle_gun_damage(), item::is_ammo(), item::is_reloadable_helper(), bandolier_actor::is_valid_ammo_type(), Item_factory::load_ammo(), Item_factory::load_basic_info(), make_gun_projectile(), item_reload_option::qty(), turret_data::range(), and item::will_explode_in_fire().
armor
cata::value_ptr<islot_armor> itype::armor
Definition at line 852 of file itype.h.
Referenced by it_artifact_armor::deserialize(), item::find_armor_data(), get_item_type_string(), item::get_layer(), it_artifact_armor::it_artifact_armor(), Item_factory::load_armor(), Item_factory::load_basic_info(), Item_factory::load_tool_armor(), new_artifact(), and it_artifact_armor::serialize().
artifact
cata::value_ptr<islot_artifact> itype::artifact
Definition at line 866 of file itype.h.
Referenced by game::add_artifact_dreams(), iuse::artifact(), check_art_charge_req(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), item::has_effect_when_carried(), item::has_effect_when_wielded(), item::has_effect_when_worn(), item::is_artifact(), it_artifact_armor::it_artifact_armor(), it_artifact_tool::it_artifact_tool(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), item::on_pickup(), item::on_wear(), item::on_wield(), game::process_artifact(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
battery
cata::value_ptr<islot_battery> itype::battery
Definition at line 862 of file itype.h.
Referenced by item::battery_info(), item::display_name(), item::is_battery(), Item_factory::load_battery(), item::mod_energy(), process_vehicle_items(), and charger_tile::update_internal().
bionic
cata::value_ptr<islot_bionic> itype::bionic
Definition at line 863 of file itype.h.
Referenced by iexamine::autodoc(), item::bionic_info(), butchery_drops_harvest(), install_bionic_actor::can_use(), item::color_in_inventory(), install_bionic_actor::finalize(), bionic_install_preset::get_anesth_amount(), bionic_uninstall_preset::get_anesth_amount(), bionic_install_preset::get_denial(), bionic_install_surgeon_preset::get_denial(), bionic_uninstall_preset::get_denial(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), bionic_uninstall_preset::get_failure_chance(), bionic_install_preset::get_operation_duration(), bionic_install_surgeon_preset::get_operation_duration(), bionic_uninstall_preset::get_operation_duration(), Character::has_enough_anesth(), item::is_bionic(), item::is_upgrade(), Item_factory::load_basic_info(), Item_factory::load_bionic(), and Character::uninstall_bionic().
book
cata::value_ptr<islot_book> itype::book
Definition at line 854 of file itype.h.
Referenced by item::book_info(), character_effects::calc_focus_equilibrium(), npc::can_read(), item::color_in_inventory(), avatar::do_read(), recipe_dictionary::finalize(), Item_factory::finalize_pre(), npc::finish_read(), item::get_available_recipes(), read_inventory_preset::get_book(), character_funcs::get_book_fun_for(), avatar::get_book_reader(), item::get_chapters(), get_item_type_string(), item::is_book(), Item_factory::load_basic_info(), Item_factory::load_book(), item::mark_chapter_as_read(), avatar::read(), skim_book_msg(), player::studied_all_recipes(), npc::time_to_read(), avatar::time_to_read(), and npc::value().
brewable
cata::value_ptr<islot_brewable> itype::brewable
Definition at line 851 of file itype.h.
Referenced by item::brewing_results(), item::brewing_time(), item::is_brewable(), and Item_factory::load_basic_info().
category_force
item_category_id itype::category_force
If set via JSON forces item category to this (preventing automatic assignment)
Definition at line 1001 of file itype.h.
Referenced by Item_factory::finalize_pre(), json_talk_topic::gen_responses(), item::get_category(), and Item_factory::load_basic_info().
color
nc_color itype::color = c_white
Definition at line 1004 of file itype.h.
Referenced by veh_interact::calc_overview(), item::color(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), vehicle::interact_with(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), target_ui::panel_gun_info(), vehicle::print_fuel_indicator(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
comestible
cata::value_ptr<islot_comestible> itype::comestible
Definition at line 850 of file itype.h.
Referenced by alcohol(), charges_default(), Character::compute_nutrient_range(), Character::consume_effects(), count_by_charges(), Item_factory::finalize_pre(), item::get_comestible(), comestible_inventory_preset::get_edible_comestible(), get_item_type_string(), Item_factory::load_comestible(), and item::minimum_freshness_duration().
conditional_names
std::vector<conditional_name> itype::conditional_names
Definition at line 916 of file itype.h.
Referenced by Item_factory::load_basic_info(), and item::type_name().
container
cata::value_ptr<islot_container> itype::container
Slots for various item type properties.
Each slot may contain a valid pointer or null, check this before using it.
Definition at line 848 of file itype.h.
Referenced by item::actualize_rot(), item::can_contain(), vpart_info::check(), item::color_in_inventory(), item::container_info(), item::deserialize(), vehicle_prototype::finalize(), Item_factory::finalize_pre(), item::get_container_capacity(), get_item_type_string(), zone_manager::get_near_zone_type_for_item(), comestible_inventory_preset::get_order(), item::get_remaining_capacity_for_liquid(), item::goes_bad_after_opening(), item::is_bucket(), item::is_container(), item::is_non_resealable_container(), item::is_watertight_container(), Item_factory::load_basic_info(), Item_factory::load_container(), item::on_contents_changed(), item::process(), and item::spoilage_sort_order().
countdown_action
use_function itype::countdown_action
Action to take when countdown expires.
Definition at line 954 of file itype.h.
Referenced by countdown_actor::info(), Item_factory::load_basic_info(), and item::process_internal().
countdown_destroy
bool itype::countdown_destroy = false
Is item destroyed after the countdown action is run?
Definition at line 948 of file itype.h.
Referenced by Item_factory::load_basic_info(), and item::process_internal().
countdown_interval
int itype::countdown_interval = 0
Default countdown interval (if any) for item.
Definition at line 951 of file itype.h.
Referenced by item::activate(), countdown_actor::info(), item::item(), Item_factory::load_basic_info(), iuse_transform::use(), and countdown_actor::use().
damage_max_
int itype::damage_max_ = +4000 private
Definition at line 879 of file itype.h.
Referenced by damage_max(), and Item_factory::load_basic_info().
damage_min_
int itype::damage_min_ = -1000 private
Minimum and maximum amount of damage to an item (state of maximum repair).
Definition at line 878 of file itype.h.
Referenced by damage_min(), and Item_factory::load_basic_info().
damage_scale
constexpr int itype::damage_scale = 1000 static constexpr
Definition at line 1006 of file itype.h.
Referenced by Character::armor_absorb(), mdeath::broken(), vehicle_part::deserialize(), iuse::gun_repair(), item::inc_damage(), item::io(), Item_factory::load_basic_info(), item::mod_damage(), Item_modifier::modify(), mdeath::normal(), vehicle_part::properties_to_item(), repair_item_actor::repair(), and repair_item_actor::repair_chance().
default_container
cata::optional<itype_id> itype::default_container
Definition at line 910 of file itype.h.
Referenced by recipe::finalize(), item::in_its_container(), Item_factory::load_basic_info(), and Item_modifier::modify().
description
translation itype::description
Definition at line 906 of file itype.h.
Referenced by item::basic_info(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Item_factory::find_template(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
drop_action
use_function itype::drop_action
Action to take BEFORE the item is placed on map.
If it returns non-zero, item won't be placed.
Definition at line 926 of file itype.h.
Referenced by Item_factory::finalize_pre(), Item_factory::load_basic_info(), and item::on_drop().
emits
std::set<emit_id> itype::emits
Fields to emit when item is in active state.
Definition at line 929 of file itype.h.
Referenced by Item_factory::load_basic_info(), and item::process_internal().
engine
cata::value_ptr<islot_engine> itype::engine
Definition at line 856 of file itype.h.
Referenced by item::engine_displacement(), item::is_engine(), and Item_factory::load_engine().
explode_in_fire
bool itype::explode_in_fire = false
Definition at line 945 of file itype.h.
Referenced by Item_factory::load_basic_info(), and item::will_explode_in_fire().
explosion
explosion_data itype::explosion
Definition at line 943 of file itype.h.
Referenced by item::detonate(), Item_factory::load_basic_info(), make_gun_projectile(), and ranged::throw_item().
faults
std::set<fault_id> itype::faults
What faults (if any) can occur.
Definition at line 1015 of file itype.h.
Referenced by item::faults_potential(), Item_factory::finalize_pre(), and Item_factory::load_basic_info().
fuel
cata::value_ptr<islot_fuel> itype::fuel
Definition at line 858 of file itype.h.
Referenced by inventory::form_from_map(), item::fuel_energy(), item::fuel_pump_terrain(), item::has_explosion_data(), item::is_fuel(), Item_factory::load_basic_info(), and Item_factory::load_fuel().
gun
cata::value_ptr<islot_gun> itype::gun
Definition at line 859 of file itype.h.
Referenced by item::ammo_capacity(), item::ammo_effects(), item::ammo_types(), can_have_charges(), saw_barrel_actor::can_use_on(), saw_stock_actor::can_use_on(), vpart_info::check(), Item_factory::check_definitions(), npc::decide_needs(), game::dump_stats(), vehicle_prototype::finalize(), detach_gunmods_actor::finalize(), Item_factory::finalize_pre(), avatar_action::fire_wielded_weapon(), ranged::get_fastest_sight(), item::get_gun_ups_drain(), get_item_type_string(), item::get_min_str(), item::get_mod_locations(), ranged::get_most_accurate_sight(), item::get_reload_time(), item::gun_damage(), item::gun_dispersion(), item::gun_noise(), item::gun_range(), item::gun_recoil(), item::gun_recoil_multiplier(), item::gun_skill(), npc_ai::gun_value(), avatar_funcs::gunmod_installation_odds(), ranged::handle_gun_damage(), item::is_gun(), item::item(), Character::item_reload_cost(), Item_factory::load_basic_info(), Item_factory::load_gun(), item::magazine_integral(), activity_handlers::reload_finish(), item::sight_dispersion(), time_to_attack(), item::tname(), item::volume(), and item::weight().
gunmod
cata::value_ptr<islot_gunmod> itype::gunmod
Definition at line 860 of file itype.h.
Referenced by Item_factory::finalize_pre(), item::gunmod_info(), avatar_funcs::gunmod_remove(), item::is_gunmod(), Item_factory::load_basic_info(), and Item_factory::load_gunmod().
id
itype_id itype::id = itype_id::NULL_ID() protected
Definition at line 883 of file itype.h.
Referenced by Item_factory::add_item_type(), Item_factory::finalize_pre(), Item_factory::find_template(), get_id(), item::io(), Item_factory::load_basic_info(), Item_factory::register_cached_uses(), and mission::serialize().
integral_volume
units::volume itype::integral_volume = -1_ml
Space consumed when integrated as part of another item (defaults to volume) CAUTION: value given is for a default-sized stack.
Avoid using this. In general, see item::volume instead.
Definition at line 977 of file itype.h.
Referenced by Item_factory::finalize_pre(), Item_factory::load_basic_info(), and item::volume().
integral_weight
units::mass itype::integral_weight = -1_gram
Weight difference with the part it replaces for mods.
Definition at line 965 of file itype.h.
Referenced by Item_factory::finalize_pre(), Item_factory::load_basic_info(), and item::weight().
item_tags
FlagsSetType itype::item_tags
Definition at line 1033 of file itype.h.
Referenced by it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Item_factory::finalize_post(), Item_factory::finalize_pre(), get_flags(), has_flag(), Item_factory::load_basic_info(), new_artifact(), Item_factory::npc_implied_flags(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), and Item_factory::set_allergy_flags().
layer
layer_level itype::layer = layer_level::MAX_CLOTHING_LAYER
Definition at line 1026 of file itype.h.
Referenced by Item_factory::finalize_pre(), and item::get_layer().
light_emission
unsigned itype::light_emission = 0
Definition at line 998 of file itype.h.
Referenced by Item_factory::finalize_pre(), item::getlight_emit(), and item::is_emissive().
looks_like
itype_id itype::looks_like
Definition at line 900 of file itype.h.
Referenced by Item_factory::load_basic_info(), and Item_factory::load_definition().
m_to_hit
int itype::m_to_hit = 0
Definition at line 996 of file itype.h.
Referenced by item::combat_info(), Character::crit_chance(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Character::get_hit_weapon(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
magazine
cata::value_ptr<islot_magazine> itype::magazine
Definition at line 861 of file itype.h.
Referenced by item::ammo_capacity(), item::ammo_default(), item::ammo_set(), item::ammo_types(), mdeath::broken(), Character::can_reload(), Item_factory::check_definitions(), item::common_ammo_default(), item::detonate(), veh_interact::display_details(), vehicle_prototype::finalize(), Item_factory::finalize_pre(), item::get_reload_time(), item::is_magazine(), item::item(), Character::item_reload_cost(), item_reload_option::item_reload_option(), Item_factory::load_magazine(), item::magazine_info(), monster::monster(), avatar_action::reload(), item::reload(), avatar_funcs::unload_item(), item::weight(), and item::will_explode_in_fire().
magazine_default
std::map< ammotype, itype_id > itype::magazine_default
Default magazine for each ammo type that can be used to reload this item.
Definition at line 1021 of file itype.h.
Referenced by mdeath::broken(), Item_factory::finalize_pre(), Item_factory::load_basic_info(), and item::magazine_default().
magazine_well
units::volume itype::magazine_well = 0_ml
Volume above which the magazine starts to protrude from the item and add extra volume.
Definition at line 1024 of file itype.h.
Referenced by Item_factory::load_basic_info(), and item::volume().
magazines
std::map< ammotype, std::set<itype_id> > itype::magazines
Magazine types (if any) for each ammo type that can be used to reload this item.
Definition at line 1018 of file itype.h.
Referenced by item::ammo_set(), Item_factory::check_definitions(), Item_factory::finalize_pre(), Item_factory::load_basic_info(), item::magazine_compatible(), and item::magazine_integral().
materials
std::vector<material_id> itype::materials
Definition at line 920 of file itype.h.
Referenced by Character::can_eat(), Item_factory::finalize_pre(), hflesh_to_flesh(), Item_factory::load_basic_info(), item::made_of(), new_artifact(), new_natural_artifact(), vehicle::part_collision(), and Item_factory::set_allergy_flags().
melee
std::array<int, NUM_DT> itype::melee
Damage output in melee for zero or more damage types.
Definition at line 992 of file itype.h.
Referenced by item::damage_melee(), Item_factory::finalize_pre(), Item_factory::load_basic_info(), new_artifact(), and new_natural_artifact().
milling_data
cata::value_ptr<islot_milling> itype::milling_data
Definition at line 868 of file itype.h.
Referenced by Item_factory::load_basic_info(), and mill_load_food().
min_dex
int itype::min_dex = 0
Definition at line 936 of file itype.h.
Referenced by item::basic_info(), Character::enumerate_unmet_requirements(), Item_factory::load_basic_info(), and Character::meets_stat_requirements().
min_int
int itype::min_int = 0
Definition at line 937 of file itype.h.
Referenced by item::basic_info(), Character::enumerate_unmet_requirements(), Item_factory::load_basic_info(), and Character::meets_stat_requirements().
min_per
int itype::min_per = 0
Definition at line 938 of file itype.h.
Referenced by item::basic_info(), Character::enumerate_unmet_requirements(), Item_factory::load_basic_info(), and Character::meets_stat_requirements().
min_skills
std::map<skill_id, int> itype::min_skills
Definition at line 934 of file itype.h.
Referenced by item::basic_info(), Character::enumerate_unmet_requirements(), Item_factory::load_basic_info(), and Character::meets_requirements().
min_str
int itype::min_str = 0
Definition at line 935 of file itype.h.
Referenced by item::get_min_str(), and Item_factory::load_basic_info().
mod
cata::value_ptr<islot_mod> itype::mod
Definition at line 855 of file itype.h.
Referenced by Item_factory::finalize_pre(), item::gunmod_info(), item::is_toolmod(), Item_factory::load_basic_info(), Item_factory::load_gunmod(), Item_factory::load_toolmod(), item::magazine_default(), and iuse::toolmod_attach().
name
translation itype::name = no_translation("none") protected
unique string identifier for this type
Definition at line 887 of file itype.h.
Referenced by it_artifact_tool::create_name(), it_artifact_armor::create_name(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Item_factory::find_template(), item::gun_info(), Item_factory::load_basic_info(), nname(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
pet_armor
cata::value_ptr<islot_pet_armor> itype::pet_armor
Definition at line 853 of file itype.h.
Referenced by get_base_env_resist(), item::get_base_env_resist_w_filter(), item::get_env_resist(), item::get_pet_armor_bodytype(), item::get_pet_armor_max_vol(), item::get_pet_armor_min_vol(), item::get_storage(), item::get_thickness(), Item_factory::load_basic_info(), and Item_factory::load_pet_armor().
phase
phase_id itype::phase = SOLID
Definition at line 940 of file itype.h.
Referenced by act_vehicle_unload_fuel(), vehicle_part::ammo_set(), butchery_drops_harvest(), item::can_contain(), veh_interact::cant_do(), item::is_reloadable_helper(), Item_factory::load_basic_info(), item::made_of(), make_gun_projectile(), and nname().
picture_id
ascii_art_id itype::picture_id
Definition at line 907 of file itype.h.
Referenced by Item_factory::load_basic_info().
price
units::money itype::price = 0_cent
Value before cataclysm.
Price given is for a default-sized stack.
Definition at line 983 of file itype.h.
Referenced by talk_function::bionic_install(), talk_function::bionic_remove(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Item_factory::finalize_pre(), talk_function::give_equipment(), it_artifact_armor::it_artifact_armor(), it_artifact_tool::it_artifact_tool(), Item_factory::load_basic_info(), item::price(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
price_post
units::money itype::price_post = -1_cent
Value after cataclysm, dependent upon practical usages.
Price given is for a default-sized stack.
Definition at line 985 of file itype.h.
Referenced by Item_factory::finalize_pre(), Item_factory::load_basic_info(), and item::price().
properties
std::map<std::string, std::string> itype::properties
Definition at line 913 of file itype.h.
Referenced by item::get_property_int64_t(), item::get_property_string(), item::has_property(), and Item_factory::set_properties_from_json().
qualities
std::map<quality_id, int> itype::qualities
Definition at line 912 of file itype.h.
Referenced by requirement_data::check_enough_materials(), Item_factory::delete_qualities_from_json(), Item_factory::extend_qualities_from_json(), Item_factory::finalize_pre(), item::get_qualities(), item::get_quality(), Item_factory::load_basic_info(), item::qualities_info(), item::quality_of(), and Item_factory::set_qualities_from_json().
recipes
std::vector<recipe_id> itype::recipes
What recipes can make this item.
Definition at line 1012 of file itype.h.
Referenced by Character::compute_nutrient_range().
relic_data
cata::value_ptr<relic> itype::relic_data
Definition at line 867 of file itype.h.
Referenced by item::convert(), item::item(), and Item_factory::load_basic_info().
repair
std::set<itype_id> itype::repair
Damage scale compared to the old float damage value.
What items can be used to repair this item?
See also
Item_factory::finalize
Definition at line 1009 of file itype.h.
Referenced by item::repaired_with().
repairs_like
itype_id itype::repairs_like
Definition at line 903 of file itype.h.
Referenced by Item_factory::load_basic_info(), and repair_item_actor::repair_recipe_difficulty().
rigid
bool itype::rigid = true
Definition at line 989 of file itype.h.
Referenced by item::armor_info(), item::final_info(), item::get_encumber_when_containing(), item::get_remaining_capacity_for_liquid(), Item_factory::load_basic_info(), and item::volume().
seed
cata::value_ptr<islot_seed> itype::seed
Definition at line 865 of file itype.h.
Referenced by talk_function::field_harvest(), item::get_plant_epoch(), item::get_plant_name(), plot_options::get_zone_name_suggestion(), item::is_seed(), Item_factory::load_basic_info(), and plot_options::query_seed().
snippet_category
std::string itype::snippet_category
Definition at line 905 of file itype.h.
Referenced by item::io(), item::item(), and Item_factory::load_basic_info().
solar_efficiency
float itype::solar_efficiency = 0
Efficiency of solar energy conversion for solarpacks.
Definition at line 1031 of file itype.h.
Referenced by Character::burn_fuel(), and Item_factory::load_basic_info().
src
std::vector<std::pair<itype_id, mod_id> > itype::src
Definition at line 841 of file itype.h.
Referenced by item::basic_info(), and Item_factory::load_basic_info().
stack_size
int itype::stack_size = 0
Number of items per above volume for count_by_charges items.
Definition at line 980 of file itype.h.
Referenced by vehicle_part::ammo_set(), item::base_volume(), item::burn(), veh_interact::calc_overview(), item::charges_per_volume(), charges_per_volume(), Item_factory::finalize_pre(), Character::get_acquirable_energy(), Item_factory::load_ammo(), Item_factory::load_comestible(), item::mod_damage(), Character::pour_into(), vehicle::print_part_list(), item::simulate_burn(), and item::volume().
stackable_
bool itype::stackable_ = false private
Can item be combined with other identical items?
Definition at line 873 of file itype.h.
Referenced by count_by_charges(), and Item_factory::load_basic_info().
sym
std::string itype::sym
Definition at line 1003 of file itype.h.
Referenced by it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), and item::symbol().
techniques
std::set<matec_id> itype::techniques
Definition at line 931 of file itype.h.
Referenced by item::combat_info(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), item::get_techniques(), item::has_technique(), Item_factory::load_basic_info(), it_artifact_tool::serialize(), and it_artifact_armor::serialize().
thrown_damage
damage_instance itype::thrown_damage
Base damage output when thrown.
Definition at line 994 of file itype.h.
Referenced by item::base_damage_thrown(), and Item_factory::load_basic_info().
tool
cata::value_ptr<islot_tool> itype::tool
Definition at line 849 of file itype.h.
Referenced by item::ammo_capacity(), item::ammo_types(), can_have_charges(), charge_factor(), charges_default(), charges_to_use(), Character::consume_med(), item::deactivate(), it_artifact_tool::deserialize(), Item_factory::finalize_pre(), iuse::foodperson(), get_item_type_string(), item::is_tool(), it_artifact_tool::it_artifact_tool(), item::item(), Item_factory::load_tool(), Item_factory::load_tool_armor(), maximum_charges(), Item_modifier::modify(), iuse::multicooker(), new_artifact(), new_natural_artifact(), item::process_extinguish(), item::process_tool(), item::process_wet(), and it_artifact_tool::serialize().
use_methods
std::map<std::string, use_function> itype::use_methods
Actions an instance can perform (if any) indexed by action type.
Definition at line 923 of file itype.h.
Referenced by item::book_info(), avatar::do_read(), item::final_info(), Item_factory::finalize_pre(), activatable_inventory_preset::get_action_name(), activatable_inventory_preset::get_denial(), get_use(), has_use(), item::info(), invoke(), avatar::invoke_item(), npc::invoke_item(), item::is_transformable(), it_artifact_tool::it_artifact_tool(), item::item_has_uses_recursive(), Item_factory::load_basic_info(), Item_factory::npc_implied_flags(), rate_food(), avatar::read(), Item_factory::register_cached_uses(), skim_book_msg(), npc::start_read(), tick(), and npc::will_accept_from_player().
volume
units::volume itype::volume = 0_ml
Space occupied by items of this type CAUTION: value given is for a default-sized stack.
Avoid using where count_by_charges items may be encountered; see item::volume instead. To determine how many of an item can fit in a given space, use charges_per_volume.
Definition at line 972 of file itype.h.
Referenced by item::base_volume(), item::burn(), item::charges_per_volume(), charges_per_volume(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), Item_factory::finalize_pre(), Character::get_acquirable_energy(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), item::volume(), and item::weight().
was_loaded
bool itype::was_loaded = false
Definition at line 897 of file itype.h.
Referenced by Item_factory::load_ammo(), and Item_factory::load_definition().
weight
units::mass itype::weight = 0_gram
Weight of item (or each stack member)
Definition at line 963 of file itype.h.
Referenced by butchery_drops_harvest(), item::contain_monster(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), veh_interact::display_details(), Item_factory::finalize_pre(), Character::get_acquirable_energy(), Item_factory::load_basic_info(), new_artifact(), new_natural_artifact(), it_artifact_tool::serialize(), it_artifact_armor::serialize(), mdeath::splatter(), and item::weight().
wheel
cata::value_ptr<islot_wheel> itype::wheel
Definition at line 857 of file itype.h.
Referenced by vpart_info::check(), veh_interact::display_details(), item::is_wheel(), Item_factory::load_wheel(), item::tname(), item::wheel_area(), vehicle_part::wheel_diameter(), and vehicle_part::wheel_width().
The documentation for this struct was generated from the following files:
src/itype.h
src/itype.cpp