Cataclysm BN: event_transformation_impl::state Struct Reference
event_transformation_impl::state Struct Reference
Public Member Functions
state (const event_transformation_impl *trans, stats_tracker &stats)
void new_value (const cata_variant &, stats_tracker &stats) override
void event_added (const cata::event &e, stats_tracker &stats) override
void events_reset (const event_multiset &new_value, stats_tracker &stats) override
Public Member Functions inherited from stats_tracker_state
virtual ~stats_tracker_state ()=0
Public Member Functions inherited from base_watcher
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Public Attributes
const event_transformation_impl * transformation_
event_multiset data_
Additional Inherited Members
Protected Member Functions inherited from base_watcher
virtual ~base_watcher ()
Detailed Description
Definition at line 515 of file event_statistics.cpp.
Constructor & Destructor Documentation
state()
event_transformation_impl::state::state (const event_transformation_impl * trans, stats_tracker & stats) inline
Definition at line 516 of file event_statistics.cpp.
                                                                              :
            transformation_( trans ),
            data_( trans->initialize( stats ) ) {
            trans->source_->add_watcher( stats, this );
            for( const auto &p : trans->constraints_ ) {
                if( p.second.equals_statistic_ ) {
                    stats.add_watcher( *p.second.equals_statistic_, this );
                }
            }
        }
References event_transformation_impl::constraints_, and event_transformation_impl::source_.
Member Function Documentation
event_added()
void event_transformation_impl::state::event_added (const cata::event & e, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 532 of file event_statistics.cpp.
{
            EventVector transformed = transformation_->match_and_transform( e.data(), stats );
            for( cata::event::data_type &d : transformed ) {
                cata::event new_event( e.type(), e.time(), std::move( d ) );
                data_.add( new_event );
                stats.transformed_set_changed( transformation_->id_, new_event );
            }
        }
References event_multiset::add(), cata::event::data(), data_, event_transformation_impl::id_, event_transformation_impl::match_and_transform(), avatar_action::move(), cata::event::time(), transformation_, and cata::event::type().
events_reset()
void event_transformation_impl::state::events_reset (const event_multiset & new_value, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 541 of file event_statistics.cpp.
{
            data_ = transformation_->initialize( new_value.counts(), stats );
            stats.transformed_set_changed( transformation_->id_, data_ );
        }
References data_, event_transformation_impl::id_, event_transformation_impl::initialize(), new_value(), and transformation_.
new_value()
void event_transformation_impl::state::new_value (const cata_variant & , stats_tracker & stats) inline override virtual
Implements stat_watcher.
Definition at line 527 of file event_statistics.cpp.
{
            data_ = transformation_->initialize( stats );
            stats.transformed_set_changed( transformation_->id_, data_ );
        }
References data_, event_transformation_impl::id_, event_transformation_impl::initialize(), and transformation_.
Referenced by events_reset().
Member Data Documentation
data_
event_multiset event_transformation_impl::state::data_
Definition at line 547 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), and new_value().
transformation_
const event_transformation_impl* event_transformation_impl::state::transformation_
Definition at line 546 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), and new_value().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp