Cataclysm BN: overmap_special_connection Struct Reference
overmap_special_connection Struct Reference
#include <overmap_special.h>
Public Member Functions
void deserialize (const JsonObject &jo)
Public Attributes
tripoint p
cata::optional< tripoint > from
om_direction::type initial_dir = om_direction::type::invalid
overmap_connection_id connection
bool existing = false
Detailed Description
Definition at line 63 of file overmap_special.h.
Member Function Documentation
deserialize()
void overmap_special_connection::deserialize (const JsonObject & jo)
Definition at line 436 of file overmap.cpp.
{
    mandatory( jo, false, "point", p );
    if( jo.has_string( "terrain" ) ) {
        // Legacy migration.
        // TODO: remove after BN 0.F or 0.E (or whatever it's gonna be)
        if( json_report_strict ) {
            try {
                jo.throw_error( "Defining connection by terrain is deprecated, use explicit 'connection' instead.",
                                "terrain" );
            } catch( const JsonError &e ) {
                debugmsg( "%s", e.what() );
            }
        }
        if( !jo.has_member( "connection" ) ) {
            std::string t = jo.get_string( "terrain" );
            if( t == "sewer" ) {
                connection = overmap_connection_id( "sewer_tunnel" );
            } else if( t == "subway" ) {
                connection = overmap_connection_id( "subway_tunnel" );
            } else if( t == "forest_trail" ) {
                connection = overmap_connection_id( "forest_trail" );
            } else {
                connection = overmap_connection_id( "local_road" );
            }
        }
    } else {
        mandatory( jo, false, "connection", connection );
    }
    optional( jo, false, "existing", existing );
    optional( jo, false, "from", from );
}
References connection, debugmsg, existing, from, JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_string(), json_report_strict, mandatory(), optional(), p, and JsonObject::throw_error().
Member Data Documentation
connection
overmap_connection_id overmap_special_connection::connection
Definition at line 67 of file overmap_special.h.
Referenced by deserialize().
existing
bool overmap_special_connection::existing = false
Definition at line 68 of file overmap_special.h.
Referenced by deserialize().
from
cata::optional<tripoint> overmap_special_connection::from
Definition at line 65 of file overmap_special.h.
Referenced by deserialize().
initial_dir
om_direction::type overmap_special_connection::initial_dir = om_direction::type::invalid
Definition at line 66 of file overmap_special.h.
p
tripoint overmap_special_connection::p
Definition at line 64 of file overmap_special.h.
Referenced by deserialize().
The documentation for this struct was generated from the following files:
src/overmap_special.h
src/overmap.cpp