Cataclysm BN: VehicleLocation Struct Reference
VehicleLocation Struct Reference
#include <vehicle_group.h>
Public Member Functions
VehicleLocation (const jmapgen_int &x, const jmapgen_int &y, const VehicleFacings &facings)
units::angle pick_facing () const
point pick_point () const
Public Attributes
jmapgen_int x
jmapgen_int y
VehicleFacings facings
Detailed Description
Definition at line 62 of file vehicle_group.h.
Constructor & Destructor Documentation
VehicleLocation()
VehicleLocation::VehicleLocation (const jmapgen_int & x, const jmapgen_int & y, const VehicleFacings & facings) inline
Definition at line 63 of file vehicle_group.h.
        : x( x ), y( y ), facings( facings ) {}
Member Function Documentation
pick_facing()
units::angle VehicleLocation::pick_facing () const inline
Definition at line 66 of file vehicle_group.h.
{
        return facings.pick();
    }
References facings, and VehicleFacings::pick().
Referenced by VehicleFunction_json::apply(), VehicleSpawnFunction::builtin_jackknifed_semi(), and VehicleSpawnFunction::builtin_pileup().
pick_point()
point VehicleLocation::pick_point () const
Definition at line 43 of file vehicle_group.cpp.
{
    return point( x.get(), y.get() );
}
References jmapgen_int::get(), x, and y.
Referenced by VehicleFunction_json::apply(), VehicleSpawnFunction::builtin_jackknifed_semi(), and VehicleSpawnFunction::builtin_pileup().
Member Data Documentation
facings
VehicleFacings VehicleLocation::facings
Definition at line 74 of file vehicle_group.h.
Referenced by pick_facing().
x
jmapgen_int VehicleLocation::x
Definition at line 72 of file vehicle_group.h.
Referenced by pick_point().
y
jmapgen_int VehicleLocation::y
Definition at line 73 of file vehicle_group.h.
Referenced by pick_point().
The documentation for this struct was generated from the following files:
src/vehicle_group.h
src/vehicle_group.cpp