Cataclysm BN: map_bash_info Struct Reference
map_bash_info Struct Reference
#include <mapdata.h>
Public Types
enum class map_object_type { furniture = 0 , terrain , field }
Public Member Functions
map_bash_info ()
void deserialize (JsonIn &jsin)
void finalize ()
void check (const std::string &id, map_object_type type) const
Public Attributes
bool was_loaded = false
int str_min = 0
int str_max = 0
int str_min_blocked = -1
int str_max_blocked = -1
int str_min_supported = -1
int str_max_supported = -1
int explosive = -1
cata::optional< int > sound_vol = cata::nullopt
cata::optional< int > sound_fail_vol = cata::nullopt
int collapse_radius = 1
int fd_bash_move_cost = 100
bool destroy_only = false
bool bash_below = false
item_group_id drop_group = item_group_id("EMPTY_GROUP")
translation sound = to_translation("smash!")
translation sound_fail = to_translation("thump!")
translation field_bash_msg_success = translation()
ter_str_id ter_set = ter_str_id::NULL_ID()
ter_str_id ter_set_bashed_from_above = ter_str_id::NULL_ID()
furn_str_id furn_set = furn_str_id::NULL_ID()
std::vector< furn_str_id > tent_centers
cata::optional< ranged_bash_info > ranged
Detailed Description
Definition at line 59 of file mapdata.h.
Member Enumeration Documentation
map_object_type
enum class map_bash_info::map_object_type strong
Enumerator
furniture
terrain
field
Definition at line 103 of file mapdata.h.
{
        furniture = 0,
        terrain,
        field
    };
Constructor & Destructor Documentation
map_bash_info()
map_bash_info::map_bash_info ()
Definition at line 234 of file mapdata.cpp.
                             : str_min( -1 ), str_max( -1 ),
    str_min_blocked( -1 ), str_max_blocked( -1 ),
    str_min_supported( -1 ), str_max_supported( -1 ),
    explosive( 0 ), sound_vol( -1 ), sound_fail_vol( -1 ),
    collapse_radius( 1 ), destroy_only( false ), bash_below( false ),
    drop_group( "EMPTY_GROUP" ),
    ter_set( ter_str_id::NULL_ID() ), furn_set( furn_str_id::NULL_ID() ) {}
References explosive.
Member Function Documentation
check()
void map_bash_info::check (const std::string & id, map_object_type type) const
Definition at line 314 of file mapdata.cpp.
{
    std::vector<std::string> errors;
    if( type != map_bash_info::map_object_type::furniture && furn_set ) {
        errors.emplace_back( _( "\"furn_set\" is set" ) );
    }
    if( type != map_bash_info::map_object_type::terrain && ter_set ) {
        errors.emplace_back( _( "\"ter_set\" is set" ) );
    }
    if( type != map_bash_info::map_object_type::terrain && ter_set_bashed_from_above ) {
        errors.emplace_back( _( "\"ter_set_bashed_from_above\" is set" ) );
    }
    if( !errors.empty() ) {
        const std::string &type_str = map_object_type_to_str( type );
        debugmsg( _( "Errors for \"bash\" field in \"%s\": \"%s\":\n%s" ),
                  type_str, id,
                  enumerate_as_string( errors, enumeration_conjunction::newline ) );
    }
}
References _, debugmsg, enumerate_as_string(), furn_set, furniture, map_object_type_to_str(), newline, ter_set, ter_set_bashed_from_above, terrain, and type.
Referenced by field_type::check(), and check_bash_items().
deserialize()
void map_bash_info::deserialize (JsonIn & jsin)
Definition at line 242 of file mapdata.cpp.
{
    JsonObject jo = jsin.get_object();
    assign( jo, "str_min", str_min );
    assign( jo, "str_max", str_max );
    assign( jo, "str_min_blocked", str_min_blocked );
    assign( jo, "str_max_blocked", str_max_blocked );
    assign( jo, "str_min_supported", str_min_supported );
    assign( jo, "str_max_supported", str_max_supported );
    assign( jo, "explosive", explosive );
    assign( jo, "sound_vol", sound_vol );
    correct_if_magic( sound_vol );
    assign( jo, "sound_fail_vol", sound_fail_vol );
    correct_if_magic( sound_fail_vol );
    assign( jo, "collapse_radius", collapse_radius );
    assign( jo, "destroy_only", destroy_only );
    assign( jo, "bash_below", bash_below );
    assign( jo, "sound", sound );
    assign( jo, "sound_fail", sound_fail );
    assign( jo, "furn_set", furn_set );
    assign( jo, "ter_set", ter_set );
    assign( jo, "ter_set_bashed_from_above", ter_set_bashed_from_above );
    assign( jo, "move_cost", fd_bash_move_cost );
    assign( jo, "msg_success", field_bash_msg_success );
    if( jo.has_member( "items" ) ) {
        drop_group = item_group::load_item_group( jo.get_member( "items" ), "collection" );
    }
    if( jo.has_array( "tent_centers" ) ) {
        load_map_bash_tent_centers( jo.get_array( "tent_centers" ), tent_centers );
    }
    assign( jo, "ranged", ranged );
}
References assign(), bash_below, collapse_radius, correct_if_magic(), destroy_only, drop_group, explosive, fd_bash_move_cost, field_bash_msg_success, furn_set, JsonObject::get_array(), JsonObject::get_member(), JsonIn::get_object(), JsonObject::has_array(), JsonObject::has_member(), item_group::load_item_group(), load_map_bash_tent_centers(), sound, sound_fail, sound_fail_vol, sound_vol, str_max, str_max_blocked, str_max_supported, str_min, str_min_blocked, str_min_supported, tent_centers, ter_set, and ter_set_bashed_from_above.
finalize()
void map_bash_info::finalize ()
Definition at line 291 of file mapdata.cpp.
{
    if( !ter_set_bashed_from_above ) {
        ter_set_bashed_from_above = ter_set;
    }
}
References ter_set, and ter_set_bashed_from_above.
Member Data Documentation
bash_below
bool map_bash_info::bash_below = false
Definition at line 84 of file mapdata.h.
Referenced by ter_t::check(), vehicle::autodrive_controller::check_drivable(), and deserialize().
collapse_radius
int map_bash_info::collapse_radius = 1
Definition at line 78 of file mapdata.h.
Referenced by deserialize(), and iexamine::portable_structure().
destroy_only
bool map_bash_info::destroy_only = false
Definition at line 82 of file mapdata.h.
Referenced by deserialize().
drop_group
item_group_id map_bash_info::drop_group = item_group_id("EMPTY_GROUP")
Definition at line 86 of file mapdata.h.
Referenced by map::bash_furn_success(), check_bash_items(), deserialize(), om_harvest_furn(), om_harvest_ter(), and smash().
explosive
int map_bash_info::explosive = -1
Definition at line 72 of file mapdata.h.
Referenced by deserialize().
fd_bash_move_cost
int map_bash_info::fd_bash_move_cost = 100
Definition at line 80 of file mapdata.h.
Referenced by deserialize(), and smash().
field_bash_msg_success
translation map_bash_info::field_bash_msg_success = translation()
Definition at line 92 of file mapdata.h.
Referenced by deserialize(), and smash().
furn_set
furn_str_id map_bash_info::furn_set = furn_str_id::NULL_ID()
Definition at line 98 of file mapdata.h.
Referenced by map::bash_furn_success(), check(), check_bash_items(), deserialize(), and om_harvest_furn().
ranged
cata::optional<ranged_bash_info> map_bash_info::ranged
Definition at line 102 of file mapdata.h.
sound
translation map_bash_info::sound = to_translation("smash!")
Definition at line 88 of file mapdata.h.
Referenced by deserialize(), and smash().
sound_fail
translation map_bash_info::sound_fail = to_translation("thump!")
Definition at line 90 of file mapdata.h.
Referenced by deserialize(), and smash().
sound_fail_vol
cata::optional<int> map_bash_info::sound_fail_vol = cata::nullopt
Definition at line 76 of file mapdata.h.
Referenced by deserialize(), and smash().
sound_vol
cata::optional<int> map_bash_info::sound_vol = cata::nullopt
Definition at line 74 of file mapdata.h.
Referenced by deserialize(), and smash().
str_max
int map_bash_info::str_max = 0
Definition at line 64 of file mapdata.h.
Referenced by map::bash_strength(), check_bash_items(), vehicle::autodrive_controller::check_drivable(), deserialize(), map::is_bashable(), map::is_bashable_furn(), map::is_bashable_ter(), talk_function::loot_building(), and smash().
str_max_blocked
int map_bash_info::str_max_blocked = -1
Definition at line 67 of file mapdata.h.
Referenced by deserialize().
str_max_supported
int map_bash_info::str_max_supported = -1
Definition at line 70 of file mapdata.h.
Referenced by deserialize().
str_min
int map_bash_info::str_min = 0
Definition at line 62 of file mapdata.h.
Referenced by map::bash_resistance(), deserialize(), om_harvest_furn(), and smash().
str_min_blocked
int map_bash_info::str_min_blocked = -1
Definition at line 66 of file mapdata.h.
Referenced by deserialize().
str_min_supported
int map_bash_info::str_min_supported = -1
Definition at line 69 of file mapdata.h.
Referenced by deserialize().
tent_centers
std::vector<furn_str_id> map_bash_info::tent_centers
Definition at line 100 of file mapdata.h.
Referenced by map::bash_furn_success(), and deserialize().
ter_set
ter_str_id map_bash_info::ter_set = ter_str_id::NULL_ID()
Definition at line 94 of file mapdata.h.
Referenced by ter_t::check(), check(), check_bash_items(), deserialize(), finalize(), and om_harvest_ter().
ter_set_bashed_from_above
ter_str_id map_bash_info::ter_set_bashed_from_above = ter_str_id::NULL_ID()
Definition at line 96 of file mapdata.h.
Referenced by ter_t::check(), check(), deserialize(), and finalize().
was_loaded
bool map_bash_info::was_loaded = false
Definition at line 60 of file mapdata.h.
The documentation for this struct was generated from the following files:
src/mapdata.h
src/mapdata.cpp