Cataclysm BN: quality Struct Reference
quality Struct Reference
#include <requirements.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
Static Public Member Functions
static void reset ()
static void load_static (const JsonObject &jo, const std::string &src)
Public Attributes
bool was_loaded = false
quality_id id
translation name
std::vector< std::pair< int, std::string > > usages
Detailed Description
Definition at line 44 of file requirements.h.
Member Function Documentation
load()
void quality::load (const JsonObject & jo, const std::string & src)
Definition at line 87 of file requirements.cpp.
{
    mandatory( jo, was_loaded, "name", name );
    for( JsonArray levels : jo.get_array( "usages" ) ) {
        const int level = levels.get_int( 0 );
        for( const std::string line : levels.get_array( 1 ) ) {
            usages.emplace_back( level, line );
        }
    }
}
References JsonObject::get_array(), line(), mandatory(), name, usages, and was_loaded.
load_static()
void quality::load_static (const JsonObject & jo, const std::string & src) static
Definition at line 82 of file requirements.cpp.
{
    quality_factory.load( jo, src );
}
References anonymous_namespace{requirements.cpp}::quality_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void quality::reset () static
Definition at line 77 of file requirements.cpp.
{
    quality_factory.reset();
}
References anonymous_namespace{requirements.cpp}::quality_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
id
quality_id quality::id
Definition at line 46 of file requirements.h.
name
translation quality::name
Definition at line 47 of file requirements.h.
Referenced by veh_interact::can_remove_part(), load(), iuse::multicooker(), quality_requirement::to_colored_string(), quality_requirement::to_string(), and veh_interact::update_part_requirements().
usages
std::vector<std::pair<int, std::string> > quality::usages
Definition at line 49 of file requirements.h.
Referenced by load().
was_loaded
bool quality::was_loaded = false
Definition at line 45 of file requirements.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp