Cataclysm BN: overmap_static_spawns Struct Reference
overmap_static_spawns Struct Reference
#include <omdata.h>
Public Member Functions
bool operator== (const overmap_static_spawns &rhs) const
void deserialize (const JsonObject &jo)
Public Member Functions inherited from overmap_spawns
overmap_spawns ()
bool operator== (const overmap_spawns &rhs) const
Public Attributes
int chance = 0
Public Attributes inherited from overmap_spawns
string_id< MonsterGroup > group
numeric_interval< int > population
Additional Inherited Members
Protected Member Functions inherited from overmap_spawns
void deserialize (const JsonObject &jo)
Detailed Description
Definition at line 74 of file omdata.h.
Member Function Documentation
deserialize()
void overmap_static_spawns::deserialize (const JsonObject & jo)
Definition at line 476 of file overmap.cpp.
{
    overmap_spawns::deserialize( jo );
    mandatory( jo, false, "chance", chance );
}
References chance, overmap_spawns::deserialize(), and mandatory().
operator==()
bool overmap_static_spawns::operator== (const overmap_static_spawns & rhs) const inline
Definition at line 77 of file omdata.h.
{
        return overmap_spawns::operator==( rhs ) && chance == rhs.chance;
    }
References chance, and overmap_spawns::operator==().
Member Data Documentation
chance
int overmap_static_spawns::chance = 0
Definition at line 75 of file omdata.h.
Referenced by deserialize(), and operator==().
The documentation for this struct was generated from the following files:
src/omdata.h
src/overmap.cpp