Cataclysm BN: rl_vec2d Struct Reference
rl_vec2d Struct Reference
#include <point_float.h>
Public Member Functions
rl_vec2d (float x=0, float y=0)
template<typename Point , typename Traits = point_traits<Point>>
constexpr rl_vec2d (const Point &p)
float magnitude () const
rl_vec2d normalized () const
rl_vec2d rotated (float angle) const
float dot_product (const rl_vec2d &v) const
bool is_null () const
point as_point () const
rl_vec2d operator* (float rhs) const
rl_vec2d operator/ (float rhs) const
rl_vec2d operator- (const rl_vec2d &rhs) const
rl_vec2d operator- () const
rl_vec2d operator+ (const rl_vec2d &rhs) const
Public Attributes
float x
float y
Static Public Attributes
static constexpr int dimension = 2
Detailed Description
Definition at line 10 of file point_float.h.
Constructor & Destructor Documentation
rl_vec2d() [1/2]
rl_vec2d::rl_vec2d (float x = 0, float y = 0) inline explicit
Definition at line 15 of file point_float.h.
: x(x), y(y) {}
Referenced by rotated().
rl_vec2d() [2/2]
template<typename Point , typename Traits = point_traits<Point>> constexpr rl_vec2d::rl_vec2d (const Point & p) inline explicit constexpr
Definition at line 17 of file point_float.h.
: x(Traits::x(p)), y(Traits::y(p)) {}
Member Function Documentation
as_point()
point rl_vec2d::as_point () const
Definition at line 686 of file line.cpp.
{
    return point(
               std::round( x ),
               std::round( y )
           );
}
References x, and y.
Referenced by map::vehicle_vehicle_collision().
dot_product()
float rl_vec2d::dot_product (const rl_vec2d & v) const
Definition at line 664 of file line.cpp.
{
    return x * v.x + y * v.y;
}
References x, and y.
Referenced by vehicle::forward_velocity(), vehicle::part_vpower_w(), vehicle::possibly_recover_from_skid(), cone::signed_distance(), and map::vehicle_vehicle_collision().
is_null()
bool rl_vec2d::is_null () const
Definition at line 681 of file line.cpp.
{
    return !( x || y );
}
References x, and y.
Referenced by normalized().
magnitude()
float rl_vec2d::magnitude () const
Definition at line 610 of file line.cpp.
{
    return std::sqrt( x * x + y * y );
}
References x, and y.
Referenced by normalized(), and map::vehicle_vehicle_collision().
normalized()
rl_vec2d rl_vec2d::normalized () const
Definition at line 620 of file line.cpp.
{
    rl_vec2d ret;
    if( is_null() ) { // shouldn't happen?
        ret.x = ret.y = 1;
        return ret;
    }
    const float m = magnitude();
    ret.x = x / m;
    ret.y = y / m;
    return ret;
}
References is_null(), magnitude(), cata::hash64_detail::ret, x, and y.
Referenced by vehicle::part_vpower_w(), and map::vehicle_vehicle_collision().
operator*()
rl_vec2d rl_vec2d::operator* (float rhs) const
Definition at line 709 of file line.cpp.
{
    rl_vec2d ret;
    ret.x = x * rhs;
    ret.y = y * rhs;
    return ret;
}
References cata::hash64_detail::ret, x, and y.
operator+()
rl_vec2d rl_vec2d::operator+ (const rl_vec2d & rhs) const
Definition at line 735 of file line.cpp.
{
    rl_vec2d ret;
    ret.x = x + rhs.x;
    ret.y = y + rhs.y;
    return ret;
}
References cata::hash64_detail::ret, x, and y.
operator-() [1/2]
rl_vec2d rl_vec2d::operator- () const
Definition at line 727 of file line.cpp.
{
    rl_vec2d ret;
    ret.x = -x;
    ret.y = -y;
    return ret;
}
References cata::hash64_detail::ret, x, and y.
operator-() [2/2]
rl_vec2d rl_vec2d::operator- (const rl_vec2d & rhs) const
Definition at line 718 of file line.cpp.
{
    rl_vec2d ret;
    ret.x = x - rhs.x;
    ret.y = y - rhs.y;
    return ret;
}
References cata::hash64_detail::ret, x, and y.
operator/()
rl_vec2d rl_vec2d::operator/ (float rhs) const
Definition at line 743 of file line.cpp.
{
    rl_vec2d ret;
    ret.x = x / rhs;
    ret.y = y / rhs;
    return ret;
}
References cata::hash64_detail::ret, x, and y.
rotated()
rl_vec2d rl_vec2d::rotated (float angle) const
Definition at line 647 of file line.cpp.
{
    return rl_vec2d(
               x * std::cos( angle ) - y * std::sin( angle ),
               x * std::sin( angle ) + y * std::cos( angle )
           );
}
References units::cos(), rl_vec2d(), units::sin(), x, and y.
Referenced by map::vehicle_vehicle_collision().
Member Data Documentation
dimension
constexpr int rl_vec2d::dimension = 2 static constexpr
Definition at line 11 of file point_float.h.
x
float rl_vec2d::x
Definition at line 12 of file point_float.h.
Referenced by as_point(), game::calc_driving_offset(), dot_product(), draw_circle(), vehicle::get_angle_from_targ(), get_local_windpower(), game::get_veh_dir_indicator_location(), is_null(), magnitude(), normalized(), operator*(), operator+(), operator-(), operator/(), vehicle::part_vpower_w(), rotated(), cone::signed_distance(), and map::vehicle_vehicle_collision().
y
float rl_vec2d::y
Definition at line 13 of file point_float.h.
Referenced by as_point(), game::calc_driving_offset(), dot_product(), draw_circle(), vehicle::get_angle_from_targ(), get_local_windpower(), game::get_veh_dir_indicator_location(), is_null(), magnitude(), normalized(), operator*(), operator+(), operator-(), operator/(), vehicle::part_vpower_w(), rotated(), cone::signed_distance(), and map::vehicle_vehicle_collision().
The documentation for this struct was generated from the following files:
src/point_float.h
src/line.cpp