Cataclysm BN: dynamic_line_t Struct Reference
dynamic_line_t Struct Reference
A dynamically generated line, spoken by the NPC.
#include <dialogue.h>
Public Member Functions
dynamic_line_t ()=default
dynamic_line_t (const std::string &line)
dynamic_line_t (const JsonObject &jo)
dynamic_line_t (JsonArray ja)
std::string operator() (const dialogue &d) const
Static Public Member Functions
static dynamic_line_t from_member (const JsonObject &jo, const std::string &member_name)
Private Attributes
std::function< std::string(const dialogue &)> function
Detailed Description
A dynamically generated line, spoken by the NPC.
This struct only adds the constructors which will load the data from json into a lambda, stored in the std::function object. Invoking the function operator with a dialog reference (so the function can access the NPC) returns the actual line.
Definition at line 330 of file dialogue.h.
Constructor & Destructor Documentation
dynamic_line_t() [1/4]
dynamic_line_t::dynamic_line_t () default
Referenced by from_member().
dynamic_line_t() [2/4]
dynamic_line_t::dynamic_line_t (const std::string & line)
Definition at line 2972 of file npctalk.cpp.
{
    function = [line]( const dialogue & ) {
        return _( line );
    };
}
References _, and line().
dynamic_line_t() [3/4]
dynamic_line_t::dynamic_line_t (const JsonObject & jo)
Definition at line 2979 of file npctalk.cpp.
{
    if( jo.has_member( "and" ) ) {
        std::vector<dynamic_line_t> lines;
        for( const JsonValue entry : jo.get_array( "and" ) ) {
            if( entry.test_string() ) {
                lines.emplace_back( entry.get_string() );
            } else if( entry.test_array() ) {
                lines.emplace_back( entry.get_array() );
            } else if( entry.test_object() ) {
                lines.emplace_back( entry.get_object() );
            } else {
                entry.throw_error( "invalid format: must be string, array or object" );
            }
        }
        function = [lines]( const dialogue & d ) {
            std::string all_lines;
            for( const dynamic_line_t &line : lines ) {
                all_lines += line( d );
            }
            return all_lines;
        };
    } else if( jo.get_bool( "give_hint", false ) ) {
        function = [&]( const dialogue & ) {
            return get_hint();
        };
    } else if( jo.get_bool( "use_reason", false ) ) {
        function = [&]( const dialogue & d ) {
            std::string tmp = d.reason;
            d.reason.clear();
            return tmp;
        };
    } else if( jo.has_string( "gendered_line" ) ) {
        const std::string line = jo.get_string( "gendered_line" );
        if( !jo.has_array( "relevant_genders" ) ) {
            jo.throw_error(
                R"(dynamic line with "gendered_line" must also have "relevant_genders")" );
        }
        std::vector<std::string> relevant_genders;
        for( const std::string gender : jo.get_array( "relevant_genders" ) ) {
            relevant_genders.push_back( gender );
            if( gender != "npc" && gender != "u" ) {
                jo.throw_error( "Unexpected subject in relevant_genders; expected 'npc' or 'u'" );
            }
        }
        function = [line, relevant_genders]( const dialogue & d ) {
            return translate_gendered_line( line, relevant_genders, d );
        };
    } else {
        conditional_t<dialogue> dcondition;
        const dynamic_line_t yes = from_member( jo, "yes" );
        const dynamic_line_t no = from_member( jo, "no" );
        for( const std::string &sub_member : dialogue_data::simple_string_conds ) {
            if( jo.has_bool( sub_member ) ) {
                // This also marks the member as visited.
                if( !jo.get_bool( sub_member ) ) {
                    jo.throw_error( "value must be true", sub_member );
                }
                dcondition = conditional_t<dialogue>( sub_member );
                function = [dcondition, yes, no]( const dialogue & d ) {
                    return ( dcondition( d ) ? yes : no )( d );
                };
                return;
            } else if( jo.has_member( sub_member ) ) {
                dcondition = conditional_t<dialogue>( sub_member );
                const dynamic_line_t yes_member = from_member( jo, sub_member );
                function = [dcondition, yes_member, no]( const dialogue & d ) {
                    return ( dcondition( d ) ? yes_member : no )( d );
                };
                return;
            }
        }
        for( const std::string &sub_member : dialogue_data::complex_conds ) {
            if( jo.has_member( sub_member ) ) {
                dcondition = conditional_t<dialogue>( jo );
                function = [dcondition, yes, no]( const dialogue & d ) {
                    return ( dcondition( d ) ? yes : no )( d );
                };
                return;
            }
        }
        jo.throw_error( "dynamic line not supported" );
    }
}
References dialogue_data::complex_conds, from_member(), JsonObject::get_array(), JsonObject::get_bool(), get_hint(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_member(), JsonObject::has_string(), line(), no, dialogue_data::simple_string_conds, JsonObject::throw_error(), translate_gendered_line(), and yes.
dynamic_line_t() [4/4]
dynamic_line_t::dynamic_line_t (JsonArray ja)
Definition at line 3064 of file npctalk.cpp.
{
    std::vector<dynamic_line_t> lines;
    for( const JsonValue entry : ja ) {
        if( entry.test_string() ) {
            lines.emplace_back( entry.get_string() );
        } else if( entry.test_array() ) {
            lines.emplace_back( entry.get_array() );
        } else if( entry.test_object() ) {
            lines.emplace_back( entry.get_object() );
        } else {
            entry.throw_error( "invalid format: must be string, array or object" );
        }
    }
    function = [lines]( const dialogue & d ) {
        const dynamic_line_t &line = random_entry_ref( lines );
        return line( d );
    };
}
References line(), and random_entry_ref().
Member Function Documentation
from_member()
dynamic_line_t dynamic_line_t::from_member (const JsonObject & jo, const std::string & member_name) static
Definition at line 2959 of file npctalk.cpp.
{
    if( jo.has_array( member_name ) ) {
        return dynamic_line_t( jo.get_array( member_name ) );
    } else if( jo.has_object( member_name ) ) {
        return dynamic_line_t( jo.get_object( member_name ) );
    } else if( jo.has_string( member_name ) ) {
        return dynamic_line_t( jo.get_string( member_name ) );
    } else {
        return dynamic_line_t{};
    }
}
References dynamic_line_t(), JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), and JsonObject::has_string().
Referenced by dynamic_line_t(), and json_talk_topic::load().
operator()()
std::string dynamic_line_t::operator() (const dialogue & d) const inline
Definition at line 341 of file dialogue.h.
{
            if( !function ) {
                return std::string{};
            }
            return function( d );
        }
Member Data Documentation
function
std::function<std::string(const dialogue &)> dynamic_line_t::function private
Definition at line 332 of file dialogue.h.
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp