Cataclysm BN: conditional_t< T > Struct Template Reference
conditional_t< T > Struct Template Reference
A condition for a response spoken by the player.
#include <condition.h>
Public Member Functions
conditional_t ()=default
conditional_t (const std::string &type)
conditional_t (const JsonObject &jo)
void set_has_any_trait (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_trait (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_trait_flag (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_var (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_compare_var (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_activity (bool is_npc=false)
void set_is_riding (bool is_npc=false)
void set_npc_has_class (const JsonObject &jo)
void set_u_has_mission (const JsonObject &jo)
void set_has_strength (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_dexterity (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_intelligence (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_perception (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_is_wearing (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_item (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_items (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_item_category (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_bionics (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_has_effect (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_need (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_at_om_location (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_npc_role_nearby (const JsonObject &jo)
void set_npc_allies (const JsonObject &jo)
void set_u_has_ecash (const JsonObject &jo)
void set_u_are_owed (const JsonObject &jo)
void set_npc_aim_rule (const JsonObject &jo)
void set_npc_engagement_rule (const JsonObject &jo)
void set_npc_cbm_reserve_rule (const JsonObject &jo)
void set_npc_cbm_recharge_rule (const JsonObject &jo)
void set_npc_rule (const JsonObject &jo)
void set_npc_override (const JsonObject &jo)
void set_days_since (const JsonObject &jo)
void set_is_season (const JsonObject &jo)
void set_mission_goal (const JsonObject &jo)
void set_no_assigned_mission ()
void set_has_assigned_mission ()
void set_has_many_assigned_missions ()
void set_no_available_mission ()
void set_has_available_mission ()
void set_has_many_available_missions ()
void set_mission_complete ()
void set_mission_incomplete ()
void set_npc_available ()
void set_npc_following ()
void set_npc_friend ()
void set_npc_hostile ()
void set_npc_train_skills ()
void set_npc_train_styles ()
void set_at_safe_space ()
void set_can_stow_weapon (bool is_npc=false)
void set_has_weapon (bool is_npc=false)
void set_is_driving (bool is_npc=false)
void set_is_day ()
void set_has_stolen_item (bool is_npc=false)
void set_is_outside ()
void set_is_by_radio ()
void set_u_has_camp ()
void set_has_pickup_list ()
void set_has_reason ()
void set_is_gender (bool is_male, bool is_npc=false)
void set_has_skill (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_u_know_recipe (const JsonObject &jo, const std::string &member)
void set_mission_has_generic_rewards ()
bool operator() (const T &d) const
Private Attributes
std::function< bool(const T &)> condition
Detailed Description
template<class T>
struct conditional_t< T >
A condition for a response spoken by the player.
This struct only adds the constructors which will load the data from json into a lambda, stored in the std::function object. Invoking the function operator with a dialog reference (so the function can access the NPC) returns whether the response is allowed.
Definition at line 64 of file condition.h.
Constructor & Destructor Documentation
conditional_t() [1/3]
template<class T > conditional_t< T >::conditional_t () default
conditional_t() [2/3]
template<class T > conditional_t< T >::conditional_t (const std::string & type)
Definition at line 1097 of file condition.cpp.
{
    const bool is_npc = true;
    if( type == "u_male" ) {
        set_is_gender( true );
    } else if( type == "npc_male" ) {
        set_is_gender( true, is_npc );
    } else if( type == "u_female" ) {
        set_is_gender( false );
    } else if( type == "npc_female" ) {
        set_is_gender( false, is_npc );
    } else if( type == "has_no_assigned_mission" ) {
        set_no_assigned_mission();
    } else if( type == "has_assigned_mission" ) {
        set_has_assigned_mission();
    } else if( type == "has_many_assigned_missions" ) {
        set_has_many_assigned_missions();
    } else if( type == "has_no_available_mission" ) {
        set_no_available_mission();
    } else if( type == "has_available_mission" ) {
        set_has_available_mission();
    } else if( type == "has_many_available_missions" ) {
        set_has_many_available_missions();
    } else if( type == "mission_complete" ) {
        set_mission_complete();
    } else if( type == "mission_incomplete" ) {
        set_mission_incomplete();
    } else if( type == "npc_available" ) {
        set_npc_available();
    } else if( type == "npc_following" ) {
        set_npc_following();
    } else if( type == "npc_friend" ) {
        set_npc_friend();
    } else if( type == "npc_hostile" ) {
        set_npc_hostile();
    } else if( type == "npc_train_skills" ) {
        set_npc_train_skills();
    } else if( type == "npc_train_styles" ) {
        set_npc_train_styles();
    } else if( type == "at_safe_space" ) {
        set_at_safe_space();
    } else if( type == "u_can_stow_weapon" ) {
        set_can_stow_weapon();
    } else if( type == "npc_can_stow_weapon" ) {
        set_can_stow_weapon( is_npc );
    } else if( type == "u_has_weapon" ) {
        set_has_weapon();
    } else if( type == "npc_has_weapon" ) {
        set_has_weapon( is_npc );
    } else if( type == "u_driving" ) {
        set_is_driving();
    } else if( type == "npc_driving" ) {
        set_is_driving( is_npc );
    } else if( type == "npc_has_activity" ) {
        set_has_activity( is_npc );
    } else if( type == "npc_is_riding" ) {
        set_is_riding( is_npc );
    } else if( type == "is_day" ) {
        set_is_day();
    } else if( type == "u_has_stolen_item" ) {
        set_has_stolen_item( is_npc );
    } else if( type == "is_outside" ) {
        set_is_outside();
    } else if( type == "u_has_camp" ) {
        set_u_has_camp();
    } else if( type == "has_pickup_list" ) {
        set_has_pickup_list();
    } else if( type == "is_by_radio" ) {
        set_is_by_radio();
    } else if( type == "has_reason" ) {
        set_has_reason();
    } else if( type == "mission_has_generic_rewards" ) {
        set_mission_has_generic_rewards();
    } else {
        condition = []( const T & ) {
            return false;
        };
    }
}
References type.
conditional_t() [3/3]
template<class T > conditional_t< T >::conditional_t (const JsonObject & jo)
Definition at line 906 of file condition.cpp.
{
    // improve the clarity of NPC setter functions
    const bool is_npc = true;
    bool found_sub_member = false;
    const auto parse_array = []( const JsonObject & jo, const std::string & type ) {
        std::vector<conditional_t> conditionals;
        for( const JsonValue entry : jo.get_array( type ) ) {
            if( entry.test_string() ) {
                conditional_t<T> type_condition( entry.get_string() );
                conditionals.emplace_back( type_condition );
            } else {
                JsonObject cond = entry.get_object();
                conditional_t<T> type_condition( cond );
                conditionals.emplace_back( type_condition );
            }
        }
        return conditionals;
    };
    if( jo.has_array( "and" ) ) {
        std::vector<conditional_t> and_conditionals = parse_array( jo, "and" );
        found_sub_member = true;
        condition = [and_conditionals]( const T & d ) {
            for( const auto &cond : and_conditionals ) {
                if( !cond( d ) ) {
                    return false;
                }
            }
            return true;
        };
    } else if( jo.has_array( "or" ) ) {
        std::vector<conditional_t> or_conditionals = parse_array( jo, "or" );
        found_sub_member = true;
        condition = [or_conditionals]( const T & d ) {
            for( const auto &cond : or_conditionals ) {
                if( cond( d ) ) {
                    return true;
                }
            }
            return false;
        };
    } else if( jo.has_object( "not" ) ) {
        JsonObject cond = jo.get_object( "not" );
        const conditional_t<T> sub_condition = conditional_t<T>( cond );
        found_sub_member = true;
        condition = [sub_condition]( const T & d ) {
            return !sub_condition( d );
        };
    } else if( jo.has_string( "not" ) ) {
        const conditional_t<T> sub_condition = conditional_t<T>( jo.get_string( "not" ) );
        found_sub_member = true;
        condition = [sub_condition]( const T & d ) {
            return !sub_condition( d );
        };
    }
    if( !found_sub_member ) {
        for( const std::string &sub_member : dialogue_data::complex_conds ) {
            if( jo.has_member( sub_member ) ) {
                found_sub_member = true;
                break;
            }
        }
    }
    if( jo.has_member( "u_has_any_trait" ) ) {
        set_has_any_trait( jo, "u_has_any_trait" );
    } else if( jo.has_member( "npc_has_any_trait" ) ) {
        set_has_any_trait( jo, "npc_has_any_trait", true );
    } else if( jo.has_member( "u_has_trait" ) ) {
        set_has_trait( jo, "u_has_trait" );
    } else if( jo.has_member( "npc_has_trait" ) ) {
        set_has_trait( jo, "npc_has_trait", true );
    } else if( jo.has_member( "u_has_trait_flag" ) ) {
        set_has_trait_flag( jo, "u_has_trait_flag" );
    } else if( jo.has_member( "npc_has_trait_flag" ) ) {
        set_has_trait_flag( jo, "npc_has_trait_flag", true );
    } else if( jo.has_member( "npc_has_class" ) ) {
        set_npc_has_class( jo );
    } else if( jo.has_string( "npc_has_activity" ) ) {
        set_has_activity( is_npc );
    } else if( jo.has_string( "npc_is_riding" ) ) {
        set_is_riding( is_npc );
    } else if( jo.has_string( "u_has_mission" ) ) {
        set_u_has_mission( jo );
    } else if( jo.has_int( "u_has_strength" ) ) {
        set_has_strength( jo, "u_has_strength" );
    } else if( jo.has_int( "npc_has_strength" ) ) {
        set_has_strength( jo, "npc_has_strength", is_npc );
    } else if( jo.has_int( "u_has_dexterity" ) ) {
        set_has_dexterity( jo, "u_has_dexterity" );
    } else if( jo.has_int( "npc_has_dexterity" ) ) {
        set_has_dexterity( jo, "npc_has_dexterity", is_npc );
    } else if( jo.has_int( "u_has_intelligence" ) ) {
        set_has_intelligence( jo, "u_has_intelligence" );
    } else if( jo.has_int( "npc_has_intelligence" ) ) {
        set_has_intelligence( jo, "npc_has_intelligence", is_npc );
    } else if( jo.has_int( "u_has_perception" ) ) {
        set_has_perception( jo, "u_has_perception" );
    } else if( jo.has_int( "npc_has_perception" ) ) {
        set_has_perception( jo, "npc_has_perception", is_npc );
    } else if( jo.has_string( "u_is_wearing" ) ) {
        set_is_wearing( jo, "u_is_wearing" );
    } else if( jo.has_string( "npc_is_wearing" ) ) {
        set_is_wearing( jo, "npc_is_wearing", is_npc );
    } else if( jo.has_string( "u_has_item" ) ) {
        set_has_item( jo, "u_has_item" );
    } else if( jo.has_string( "npc_has_item" ) ) {
        set_has_item( jo, "npc_has_item", is_npc );
    } else if( jo.has_member( "u_has_items" ) ) {
        set_has_items( jo, "u_has_items" );
    } else if( jo.has_member( "npc_has_items" ) ) {
        set_has_items( jo, "npc_has_items", is_npc );
    } else if( jo.has_string( "u_has_item_category" ) ) {
        set_has_item_category( jo, "u_has_item_category" );
    } else if( jo.has_string( "npc_has_item_category" ) ) {
        set_has_item_category( jo, "npc_has_item_category", is_npc );
    } else if( jo.has_string( "u_has_bionics" ) ) {
        set_has_bionics( jo, "u_has_bionics" );
    } else if( jo.has_string( "npc_has_bionics" ) ) {
        set_has_bionics( jo, "npc_has_bionics", is_npc );
    } else if( jo.has_string( "u_has_effect" ) ) {
        set_has_effect( jo, "u_has_effect" );
    } else if( jo.has_string( "npc_has_effect" ) ) {
        set_has_effect( jo, "npc_has_effect", is_npc );
    } else if( jo.has_string( "u_need" ) ) {
        set_need( jo, "u_need" );
    } else if( jo.has_string( "npc_need" ) ) {
        set_need( jo, "npc_need", is_npc );
    } else if( jo.has_string( "u_at_om_location" ) ) {
        set_at_om_location( jo, "u_at_om_location" );
    } else if( jo.has_string( "npc_at_om_location" ) ) {
        set_at_om_location( jo, "npc_at_om_location", is_npc );
    } else if( jo.has_string( "u_has_var" ) ) {
        set_has_var( jo, "u_has_var" );
    } else if( jo.has_string( "npc_has_var" ) ) {
        set_has_var( jo, "npc_has_var", is_npc );
    } else if( jo.has_string( "u_compare_var" ) ) {
        set_compare_var( jo, "u_compare_var" );
    } else if( jo.has_string( "npc_compare_var" ) ) {
        set_compare_var( jo, "npc_compare_var", is_npc );
    } else if( jo.has_string( "npc_role_nearby" ) ) {
        set_npc_role_nearby( jo );
    } else if( jo.has_int( "npc_allies" ) ) {
        set_npc_allies( jo );
    } else if( jo.get_bool( "npc_service", false ) ) {
        set_npc_available();
    } else if( jo.has_int( "u_has_ecash" ) ) {
        set_u_has_ecash( jo );
    } else if( jo.has_int( "u_are_owed" ) ) {
        set_u_are_owed( jo );
    } else if( jo.has_string( "npc_aim_rule" ) ) {
        set_npc_aim_rule( jo );
    } else if( jo.has_string( "npc_engagement_rule" ) ) {
        set_npc_engagement_rule( jo );
    } else if( jo.has_string( "npc_cbm_reserve_rule" ) ) {
        set_npc_cbm_reserve_rule( jo );
    } else if( jo.has_string( "npc_cbm_recharge_rule" ) ) {
        set_npc_cbm_recharge_rule( jo );
    } else if( jo.has_string( "npc_rule" ) ) {
        set_npc_rule( jo );
    } else if( jo.has_string( "npc_override" ) ) {
        set_npc_override( jo );
    } else if( jo.has_int( "days_since_cataclysm" ) ) {
        set_days_since( jo );
    } else if( jo.has_string( "is_season" ) ) {
        set_is_season( jo );
    } else if( jo.has_string( "mission_goal" ) ) {
        set_mission_goal( jo );
    } else if( jo.has_member( "u_has_skill" ) ) {
        set_has_skill( jo, "u_has_skill" );
    } else if( jo.has_member( "npc_has_skill" ) ) {
        set_has_skill( jo, "npc_has_skill", is_npc );
    } else if( jo.has_member( "u_know_recipe" ) ) {
        set_u_know_recipe( jo, "u_know_recipe" );
    } else {
        for( const std::string &sub_member : dialogue_data::simple_string_conds ) {
            if( jo.has_string( sub_member ) ) {
                const conditional_t<T> sub_condition( jo.get_string( sub_member ) );
                condition = [sub_condition]( const T & d ) {
                    return sub_condition( d );
                };
                found_sub_member = true;
                break;
            }
        }
    }
    if( !found_sub_member ) {
        jo.throw_error( "unrecognized condition in " + jo.str() );
    }
}
References dialogue_data::complex_conds, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), dialogue_data::simple_string_conds, JsonObject::str(), JsonObject::throw_error(), and type.
Member Function Documentation
operator()()
template<class T > bool conditional_t< T >::operator() (const T & d) const inline
Definition at line 137 of file condition.h.
{
            if( !condition ) {
                return false;
            }
            return condition( d );
        }
References conditional_t< T >::condition.
set_at_om_location()
template<class T > void conditional_t< T >::set_at_om_location (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 376 of file condition.cpp.
{
    const std::string &location = jo.get_string( member );
    condition = [location, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        const tripoint_abs_omt omt_pos = actor->global_omt_location();
        const oter_id &omt_ref = overmap_buffer.ter( omt_pos );
        if( location == "FACTION_CAMP_ANY" ) {
            cata::optional<basecamp *> bcp = overmap_buffer.find_camp( omt_pos.xy() );
            if( bcp ) {
                return true;
            }
            // legacy check
            const std::string &omt_str = omt_ref.id().c_str();
            return omt_str.find( "faction_base_camp" ) != std::string::npos;
        } else if( location == "FACTION_CAMP_START" ) {
            return !recipe_group::get_recipes_by_id( "all_faction_base_types",
                    omt_ref.id().c_str() ).empty();
        } else {
            return omt_ref == oter_id( oter_no_dir( oter_id( location ) ) );
        }
    };
}
References string_id< T >::c_str(), overmapbuffer::find_camp(), recipe_group::get_recipes_by_id(), JsonObject::get_string(), Character::global_omt_location(), int_id< T >::id(), mapgen_defer::member, oter_no_dir(), overmap_buffer, overmapbuffer::ter(), and coords::coord_point< Point, Origin, Scale >::xy().
set_at_safe_space()
template<class T > void conditional_t< T >::set_at_safe_space
Definition at line 748 of file condition.cpp.
{
    condition = []( const T & d ) {
        return overmap_buffer.is_safe( d.beta->global_omt_location() );
    };
}
References overmapbuffer::is_safe(), and overmap_buffer.
set_can_stow_weapon()
template<class T > void conditional_t< T >::set_can_stow_weapon (bool is_npc = false)
Definition at line 756 of file condition.cpp.
{
    condition = [is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return !actor->unarmed_attack() && actor->can_pick_volume( actor->weapon );
    };
}
References Character::can_pick_volume(), Character::unarmed_attack(), and Character::weapon.
set_compare_var()
template<class T > void conditional_t< T >::set_compare_var (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 420 of file condition.cpp.
{
    const std::string var_name = get_talk_varname( jo, member, false );
    const std::string &op = jo.get_string( "op" );
    const int value = jo.get_int( "value" );
    condition = [var_name, op, value, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        int stored_value = 0;
        const std::string &var = actor->get_value( var_name );
        if( !var.empty() ) {
            stored_value = std::stoi( var );
        }
        if( op == "==" ) {
            return stored_value == value;
        } else if( op == "!=" ) {
            return stored_value != value;
        } else if( op == "<=" ) {
            return stored_value <= value;
        } else if( op == ">=" ) {
            return stored_value >= value;
        } else if( op == "<" ) {
            return stored_value < value;
        } else if( op == ">" ) {
            return stored_value > value;
        }
        return false;
    };
}
References JsonObject::get_int(), JsonObject::get_string(), get_talk_varname(), Creature::get_value(), and mapgen_defer::member.
set_days_since()
template<class T > void conditional_t< T >::set_days_since (const JsonObject & jo)
Definition at line 580 of file condition.cpp.
{
    const unsigned int days = jo.get_int( "days_since_cataclysm" );
    condition = [days]( const T & ) {
        return calendar::turn >= calendar::start_of_cataclysm + 1_days * days;
    };
}
References JsonObject::get_int(), calendar::start_of_cataclysm, and calendar::turn.
set_has_activity()
template<class T > void conditional_t< T >::set_has_activity (bool is_npc = false)
Definition at line 142 of file condition.cpp.
{
    condition = [is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            return d.beta->has_activity();
        } else {
            if( !actor->activity.is_null() ) {
                return true;
            }
        }
        return false;
    };
}
References Character::activity, Character::has_activity(), and player_activity::is_null().
set_has_any_trait()
template<class T > void conditional_t< T >::set_has_any_trait (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 90 of file condition.cpp.
{
    std::vector<trait_id> traits_to_check;
    for( auto&& f : jo.get_string_array( member ) ) { // *NOPAD*
        traits_to_check.emplace_back( f );
    }
    condition = [traits_to_check, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        for( const auto &trait : traits_to_check ) {
            if( actor->has_trait( trait ) ) {
                return true;
            }
        }
        return false;
    };
}
References JsonObject::get_string_array(), Character::has_trait(), and mapgen_defer::member.
set_has_assigned_mission()
template<class T > void conditional_t< T >::set_has_assigned_mission
Definition at line 636 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.missions_assigned.size() == 1;
    };
}
set_has_available_mission()
template<class T > void conditional_t< T >::set_has_available_mission
Definition at line 660 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.beta->chatbin.missions.size() == 1;
    };
}
set_has_bionics()
template<class T > void conditional_t< T >::set_has_bionics (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 319 of file condition.cpp.
{
    const std::string bionics_id = jo.get_string( member );
    condition = [bionics_id, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        if( bionics_id == "ANY" ) {
            return actor->has_bionics();
        }
        return actor->has_bionic( bionic_id( bionics_id ) );
    };
}
References JsonObject::get_string(), Character::has_bionic(), Character::has_bionics(), and mapgen_defer::member.
set_has_dexterity()
template<class T > void conditional_t< T >::set_has_dexterity (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 203 of file condition.cpp.
{
    const int min_dexterity = jo.get_int( member );
    condition = [min_dexterity, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->dex_cur >= min_dexterity;
    };
}
References Character::dex_cur, JsonObject::get_int(), and mapgen_defer::member.
set_has_effect()
template<class T > void conditional_t< T >::set_has_effect (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 336 of file condition.cpp.
{
    const std::string &effect_id = jo.get_string( member );
    condition = [effect_id, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->has_effect( efftype_id( effect_id ) );
    };
}
References JsonObject::get_string(), Creature::has_effect(), and mapgen_defer::member.
set_has_intelligence()
template<class T > void conditional_t< T >::set_has_intelligence (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 217 of file condition.cpp.
{
    const int min_intelligence = jo.get_int( member );
    condition = [min_intelligence, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->int_cur >= min_intelligence;
    };
}
References JsonObject::get_int(), Character::int_cur, and mapgen_defer::member.
set_has_item()
template<class T > void conditional_t< T >::set_has_item (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 259 of file condition.cpp.
{
    const itype_id item_id( jo.get_string( member ) );
    condition = [item_id, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->charges_of( item_id ) > 0 || actor->has_amount( item_id, 1 );
    };
}
References visitable< T >::charges_of(), JsonObject::get_string(), visitable< T >::has_amount(), and mapgen_defer::member.
set_has_item_category()
template<class T > void conditional_t< T >::set_has_item_category (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 293 of file condition.cpp.
{
    const item_category_id category_id = item_category_id( jo.get_string( member ) );
    size_t count = 1;
    if( jo.has_int( "count" ) ) {
        int tcount = jo.get_int( "count" );
        if( tcount > 1 && tcount < INT_MAX ) {
            count = static_cast<size_t>( tcount );
        }
    }
    condition = [category_id, count, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        const auto items_with = actor->items_with( [category_id]( const item & it ) {
            return it.get_category().get_id() == category_id;
        } );
        return items_with.size() >= count;
    };
}
References detail::count(), item::get_category(), item_category::get_id(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_int(), visitable< T >::items_with(), and mapgen_defer::member.
set_has_items()
template<class T > void conditional_t< T >::set_has_items (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 272 of file condition.cpp.
{
    JsonObject has_items = jo.get_object( member );
    if( !has_items.has_string( "item" ) || !has_items.has_int( "count" ) ) {
        condition = []( const T & ) {
            return false;
        };
    } else {
        const itype_id item_id( has_items.get_string( "item" ) );
        int count = has_items.get_int( "count" );
        condition = [item_id, count, is_npc]( const T & d ) {
            player *actor = d.alpha;
            if( is_npc ) {
                actor = dynamic_cast<player *>( d.beta );
            }
            return actor->has_charges( item_id, count ) || actor->has_amount( item_id, count );
        };
    }
}
References detail::count(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), visitable< T >::has_amount(), Character::has_charges(), JsonObject::has_int(), JsonObject::has_string(), and mapgen_defer::member.
set_has_many_assigned_missions()
template<class T > void conditional_t< T >::set_has_many_assigned_missions
Definition at line 644 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.missions_assigned.size() >= 2;
    };
}
set_has_many_available_missions()
template<class T > void conditional_t< T >::set_has_many_available_missions
Definition at line 668 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.beta->chatbin.missions.size() >= 2;
    };
}
set_has_perception()
template<class T > void conditional_t< T >::set_has_perception (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 231 of file condition.cpp.
{
    const int min_perception = jo.get_int( member );
    condition = [min_perception, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->per_cur >= min_perception;
    };
}
References JsonObject::get_int(), mapgen_defer::member, and Character::per_cur.
set_has_pickup_list()
template<class T > void conditional_t< T >::set_has_pickup_list
Definition at line 837 of file condition.cpp.
{
    condition = []( const T & d ) {
        return !d.beta->rules.pickup_whitelist->empty();
    };
}
set_has_reason()
template<class T > void conditional_t< T >::set_has_reason
Definition at line 853 of file condition.cpp.
{
    condition = []( const T & d ) {
        return !d.reason.empty();
    };
}
set_has_skill()
template<class T > void conditional_t< T >::set_has_skill (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 861 of file condition.cpp.
{
    JsonObject has_skill = jo.get_object( member );
    if( !has_skill.has_string( "skill" ) || !has_skill.has_int( "level" ) ) {
        condition = []( const T & ) {
            return false;
        };
    } else {
        const skill_id skill( has_skill.get_string( "skill" ) );
        int level = has_skill.get_int( "level" );
        condition = [skill, level, is_npc]( const T & d ) {
            player *actor = d.alpha;
            if( is_npc ) {
                actor = dynamic_cast<player *>( d.beta );
            }
            return actor->get_skill_level( skill ) >= level;
        };
    }
}
References JsonObject::get_int(), JsonObject::get_object(), Character::get_skill_level(), JsonObject::get_string(), JsonObject::has_int(), JsonObject::has_string(), and mapgen_defer::member.
set_has_stolen_item()
template<class T > void conditional_t< T >::set_has_stolen_item (bool is_npc = false)
Definition at line 795 of file condition.cpp.
{
    condition = []( const T & d ) {
        player *actor = d.alpha;
        npc &p = *d.beta;
        bool found_in_inv = false;
        for( auto &elem : actor->inv_dump() ) {
            if( elem->is_old_owner( p, true ) ) {
                found_in_inv = true;
            }
        }
        return found_in_inv;
    };
}
References Character::inv_dump().
set_has_strength()
template<class T > void conditional_t< T >::set_has_strength (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 189 of file condition.cpp.
{
    const int min_strength = jo.get_int( member );
    condition = [min_strength, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->str_cur >= min_strength;
    };
}
References JsonObject::get_int(), mapgen_defer::member, and Character::str_cur.
set_has_trait()
template<class T > void conditional_t< T >::set_has_trait (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 112 of file condition.cpp.
{
    const std::string &trait_to_check = jo.get_string( member );
    condition = [trait_to_check, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->has_trait( trait_id( trait_to_check ) );
    };
}
References JsonObject::get_string(), Character::has_trait(), and mapgen_defer::member.
set_has_trait_flag()
template<class T > void conditional_t< T >::set_has_trait_flag (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 125 of file condition.cpp.
{
    const std::string &trait_flag_to_check = jo.get_string( member );
    condition = [trait_flag_to_check, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        if( trait_flag_to_check == "MUTATION_THRESHOLD" ) {
            return actor->crossed_threshold();
        }
        return actor->has_trait_flag( trait_flag_to_check );
    };
}
References Character::crossed_threshold(), JsonObject::get_string(), Character::has_trait_flag(), and mapgen_defer::member.
set_has_var()
template<class T > void conditional_t< T >::set_has_var (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 406 of file condition.cpp.
{
    const std::string var_name = get_talk_varname( jo, member, false );
    const std::string &value = jo.get_string( "value" );
    condition = [var_name, value, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->get_value( var_name ) == value;
    };
}
References JsonObject::get_string(), get_talk_varname(), Creature::get_value(), and mapgen_defer::member.
set_has_weapon()
template<class T > void conditional_t< T >::set_has_weapon (bool is_npc = false)
Definition at line 768 of file condition.cpp.
{
    condition = [is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return !actor->unarmed_attack();
    };
}
References Character::unarmed_attack().
set_is_by_radio()
template<class T > void conditional_t< T >::set_is_by_radio
Definition at line 845 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.by_radio;
    };
}
set_is_day()
template<class T > void conditional_t< T >::set_is_day
Definition at line 811 of file condition.cpp.
{
    condition = []( const T & ) {
        return !is_night( calendar::turn );
    };
}
References is_night(), and calendar::turn.
set_is_driving()
template<class T > void conditional_t< T >::set_is_driving (bool is_npc = false)
Definition at line 780 of file condition.cpp.
{
    condition = [is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        if( const optional_vpart_position vp = get_map().veh_at( actor->pos() ) ) {
            return vp->vehicle().is_moving() && vp->vehicle().player_in_control( *actor );
        }
        return false;
    };
}
References get_map(), Character::pos(), and map::veh_at().
set_is_gender()
template<class T > void conditional_t< T >::set_is_gender (bool is_male, bool is_npc = false)
Definition at line 616 of file condition.cpp.
{
    condition = [is_male, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->male == is_male;
    };
}
References Character::male.
set_is_outside()
template<class T > void conditional_t< T >::set_is_outside
Definition at line 819 of file condition.cpp.
{
    condition = []( const T & d ) {
        map &here = get_map();
        const tripoint pos = here.getabs( d.beta->pos() );
        return !here.has_flag( TFLAG_INDOORS, pos );
    };
}
References get_map(), map::getabs(), map::has_flag(), and TFLAG_INDOORS.
set_is_riding()
template<class T > void conditional_t< T >::set_is_riding (bool is_npc = false)
Definition at line 158 of file condition.cpp.
{
    condition = [is_npc]( const T & d ) {
        return ( is_npc ? d.beta : d.alpha )->is_mounted();
    };
}
set_is_season()
template<class T > void conditional_t< T >::set_is_season (const JsonObject & jo)
Definition at line 589 of file condition.cpp.
{
    std::string season_name = jo.get_string( "is_season" );
    condition = [season_name]( const T & ) {
        const auto season = season_of_year( calendar::turn );
        return ( season == SPRING && season_name == "spring" ) ||
               ( season == SUMMER && season_name == "summer" ) ||
               ( season == AUTUMN && season_name == "autumn" ) ||
               ( season == WINTER && season_name == "winter" );
    };
}
References AUTUMN, JsonObject::get_string(), season, season_of_year(), SPRING, SUMMER, calendar::turn, and WINTER.
set_is_wearing()
template<class T > void conditional_t< T >::set_is_wearing (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 245 of file condition.cpp.
{
    const itype_id item_id( jo.get_string( member ) );
    condition = [item_id, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        return actor->is_wearing( item_id );
    };
}
References JsonObject::get_string(), Character::is_wearing(), and mapgen_defer::member.
set_mission_complete()
template<class T > void conditional_t< T >::set_mission_complete
Definition at line 676 of file condition.cpp.
{
    condition = []( const T & d ) {
        mission *miss = d.beta->chatbin.mission_selected;
        if( !miss ) {
            return false;
        }
        return miss->is_complete( d.beta->getID() );
    };
}
References mission::is_complete().
set_mission_goal()
template<class T > void conditional_t< T >::set_mission_goal (const JsonObject & jo)
Definition at line 602 of file condition.cpp.
{
    std::string mission_goal_str = jo.get_string( "mission_goal" );
    condition = [mission_goal_str]( const T & d ) {
        mission *miss = d.beta->chatbin.mission_selected;
        if( !miss ) {
            return false;
        }
        const mission_goal mgoal = io::string_to_enum<mission_goal>( mission_goal_str );
        return miss->get_type().goal == mgoal;
    };
}
References JsonObject::get_string(), mission::get_type(), and mission_type::goal.
set_mission_has_generic_rewards()
template<class T > void conditional_t< T >::set_mission_has_generic_rewards
Definition at line 893 of file condition.cpp.
{
    condition = []( const T & d ) {
        mission *miss = d.beta->chatbin.mission_selected;
        if( miss == nullptr ) {
            debugmsg( "mission_has_generic_rewards: mission_selected == nullptr" );
            return true;
        }
        return miss->has_generic_rewards();
    };
}
References debugmsg, and mission::has_generic_rewards().
set_mission_incomplete()
template<class T > void conditional_t< T >::set_mission_incomplete
Definition at line 688 of file condition.cpp.
{
    condition = []( const T & d ) {
        mission *miss = d.beta->chatbin.mission_selected;
        if( !miss ) {
            return false;
        }
        return !miss->is_complete( d.beta->getID() );
    };
}
References mission::is_complete().
set_need()
template<class T > void conditional_t< T >::set_need (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 350 of file condition.cpp.
{
    const std::string &need = jo.get_string( member );
    int amount = 0;
    if( jo.has_int( "amount" ) ) {
        amount = jo.get_int( "amount" );
    } else if( jo.has_string( "level" ) ) {
        const std::string &level = jo.get_string( "level" );
        auto flevel = fatigue_level_strs.find( level );
        if( flevel != fatigue_level_strs.end() ) {
            amount = static_cast<int>( flevel->second );
        }
    }
    condition = [need, amount, is_npc]( const T & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        int effective_hunger = ( actor->max_stored_kcal() - actor->get_stored_kcal() ) / 10;
        return ( actor->get_fatigue() > amount && need == "fatigue" ) ||
               ( effective_hunger > amount && need == "hunger" ) ||
               ( actor->get_thirst() > amount && need == "thirst" );
    };
}
References fatigue_level_strs, Character::get_fatigue(), JsonObject::get_int(), Character::get_stored_kcal(), JsonObject::get_string(), Character::get_thirst(), JsonObject::has_int(), JsonObject::has_string(), Character::max_stored_kcal(), and mapgen_defer::member.
set_no_assigned_mission()
template<class T > void conditional_t< T >::set_no_assigned_mission
Definition at line 628 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.missions_assigned.empty();
    };
}
set_no_available_mission()
template<class T > void conditional_t< T >::set_no_available_mission
Definition at line 652 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.beta->chatbin.missions.empty();
    };
}
set_npc_aim_rule()
template<class T > void conditional_t< T >::set_npc_aim_rule (const JsonObject & jo)
Definition at line 502 of file condition.cpp.
{
    const std::string &setting = jo.get_string( "npc_aim_rule" );
    condition = [setting]( const T & d ) {
        auto rule = aim_rule_strs.find( setting );
        if( rule != aim_rule_strs.end() ) {
            return d.beta->rules.aim == rule->second;
        }
        return false;
    };
}
References aim_rule_strs, and JsonObject::get_string().
set_npc_allies()
template<class T > void conditional_t< T >::set_npc_allies (const JsonObject & jo)
Definition at line 475 of file condition.cpp.
{
    const unsigned int min_allies = jo.get_int( "npc_allies" );
    condition = [min_allies]( const T & ) {
        return g->allies().size() >= min_allies;
    };
}
References g, and JsonObject::get_int().
set_npc_available()
template<class T > void conditional_t< T >::set_npc_available
Definition at line 700 of file condition.cpp.
{
    condition = []( const T & d ) {
        return !d.beta->has_effect( effect_currently_busy );
    };
}
References effect_currently_busy.
set_npc_cbm_recharge_rule()
template<class T > void conditional_t< T >::set_npc_cbm_recharge_rule (const JsonObject & jo)
Definition at line 541 of file condition.cpp.
{
    const std::string &setting = jo.get_string( "npc_cbm_recharge_rule" );
    condition = [setting]( const T & d ) {
        auto rule = cbm_recharge_strs.find( setting );
        if( rule != cbm_recharge_strs.end() ) {
            return d.beta->rules.cbm_recharge == rule->second;
        }
        return false;
    };
}
References cbm_recharge_strs, and JsonObject::get_string().
set_npc_cbm_reserve_rule()
template<class T > void conditional_t< T >::set_npc_cbm_reserve_rule (const JsonObject & jo)
Definition at line 528 of file condition.cpp.
{
    const std::string &setting = jo.get_string( "npc_cbm_reserve_rule" );
    condition = [setting]( const T & d ) {
        auto rule = cbm_reserve_strs.find( setting );
        if( rule != cbm_reserve_strs.end() ) {
            return d.beta->rules.cbm_reserve == rule->second;
        }
        return false;
    };
}
References cbm_reserve_strs, and JsonObject::get_string().
set_npc_engagement_rule()
template<class T > void conditional_t< T >::set_npc_engagement_rule (const JsonObject & jo)
Definition at line 515 of file condition.cpp.
{
    const std::string &setting = jo.get_string( "npc_engagement_rule" );
    condition = [setting]( const T & d ) {
        auto rule = combat_engagement_strs.find( setting );
        if( rule != combat_engagement_strs.end() ) {
            return d.beta->rules.engagement == rule->second;
        }
        return false;
    };
}
References combat_engagement_strs, and JsonObject::get_string().
set_npc_following()
template<class T > void conditional_t< T >::set_npc_following
Definition at line 708 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.beta->is_following();
    };
}
set_npc_friend()
template<class T > void conditional_t< T >::set_npc_friend
Definition at line 716 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.beta->is_friendly( g->u );
    };
}
References g.
set_npc_has_class()
template<class T > void conditional_t< T >::set_npc_has_class (const JsonObject & jo)
Definition at line 166 of file condition.cpp.
{
    const std::string &class_to_check = jo.get_string( "npc_has_class" );
    condition = [class_to_check]( const T & d ) {
        return d.beta->myclass == npc_class_id( class_to_check );
    };
}
References JsonObject::get_string().
set_npc_hostile()
template<class T > void conditional_t< T >::set_npc_hostile
Definition at line 724 of file condition.cpp.
{
    condition = []( const T & d ) {
        return d.beta->is_enemy();
    };
}
set_npc_override()
template<class T > void conditional_t< T >::set_npc_override (const JsonObject & jo)
Definition at line 567 of file condition.cpp.
{
    std::string rule = jo.get_string( "npc_override" );
    condition = [rule]( const T & d ) {
        auto flag = ally_rule_strs.find( rule );
        if( flag != ally_rule_strs.end() ) {
            return d.beta->rules.has_override_enable( flag->second.rule );
        }
        return false;
    };
}
References ally_rule_strs, and JsonObject::get_string().
set_npc_role_nearby()
template<class T > void conditional_t< T >::set_npc_role_nearby (const JsonObject & jo)
Definition at line 462 of file condition.cpp.
{
    const std::string &role = jo.get_string( "npc_role_nearby" );
    condition = [role]( const T & d ) {
        const std::vector<npc *> available = g->get_npcs_if( [&]( const npc & guy ) {
            return d.alpha->posz() == guy.posz() && guy.companion_mission_role_id == role &&
                   ( rl_dist( d.alpha->pos(), guy.pos() ) <= 48 );
        } );
        return !available.empty();
    };
}
References available, npc::companion_mission_role_id, g, JsonObject::get_string(), Character::pos(), Character::posz(), and rl_dist().
set_npc_rule()
template<class T > void conditional_t< T >::set_npc_rule (const JsonObject & jo)
Definition at line 554 of file condition.cpp.
{
    std::string rule = jo.get_string( "npc_rule" );
    condition = [rule]( const T & d ) {
        auto flag = ally_rule_strs.find( rule );
        if( flag != ally_rule_strs.end() ) {
            return d.beta->rules.has_flag( flag->second.rule );
        }
        return false;
    };
}
References ally_rule_strs, and JsonObject::get_string().
set_npc_train_skills()
template<class T > void conditional_t< T >::set_npc_train_skills
Definition at line 732 of file condition.cpp.
{
    condition = []( const T & d ) {
        return !d.beta->skills_offered_to( *d.alpha ).empty();
    };
}
set_npc_train_styles()
template<class T > void conditional_t< T >::set_npc_train_styles
Definition at line 740 of file condition.cpp.
{
    condition = []( const T & d ) {
        return !d.beta->styles_offered_to( *d.alpha ).empty();
    };
}
set_u_are_owed()
template<class T > void conditional_t< T >::set_u_are_owed (const JsonObject & jo)
Definition at line 493 of file condition.cpp.
{
    const int min_debt = jo.get_int( "u_are_owed" );
    condition = [min_debt]( const T & d ) {
        return d.beta->op_of_u.owed >= min_debt;
    };
}
References JsonObject::get_int().
set_u_has_camp()
template<class T > void conditional_t< T >::set_u_has_camp
Definition at line 829 of file condition.cpp.
{
    condition = []( const T & ) {
        return !g->u.camps.empty();
    };
}
References g.
set_u_has_ecash()
template<class T > void conditional_t< T >::set_u_has_ecash (const JsonObject & jo)
Definition at line 484 of file condition.cpp.
{
    const int min_cash = jo.get_int( "u_has_ecash" );
    condition = [min_cash]( const T & d ) {
        return d.alpha->cash >= min_cash;
    };
}
References JsonObject::get_int().
set_u_has_mission()
template<class T > void conditional_t< T >::set_u_has_mission (const JsonObject & jo)
Definition at line 175 of file condition.cpp.
{
    const std::string &mission = jo.get_string( "u_has_mission" );
    condition = [mission]( const T & ) {
        for( auto miss_it : g->u.get_active_missions() ) {
            if( miss_it->mission_id() == mission_type_id( mission ) ) {
                return true;
            }
        }
        return false;
    };
}
References g, and JsonObject::get_string().
set_u_know_recipe()
template<class T > void conditional_t< T >::set_u_know_recipe (const JsonObject & jo, const std::string & member)
Definition at line 882 of file condition.cpp.
{
    const std::string &known_recipe_id = jo.get_string( member );
    condition = [known_recipe_id]( const T & d ) {
        player *actor = d.alpha;
        const recipe &r = recipe_id( known_recipe_id ).obj();
        return actor->knows_recipe( &r );
    };
}
References JsonObject::get_string(), Character::knows_recipe(), mapgen_defer::member, and string_id< T >::obj().
Member Data Documentation
condition
template<class T > std::function<bool(const T &)> conditional_t< T >::condition private
Definition at line 66 of file condition.h.
Referenced by conditional_t< T >::operator()().
The documentation for this struct was generated from the following files:
src/condition.h
src/condition.cpp