Cataclysm BN: damage_instance Struct Reference
damage_instance Struct Reference
#include <damage.h>
Public Member Functions
damage_instance ()
damage_instance (damage_type dt, float amt, float arpen=0.0f, float arpen_mult=1.0f, float dmg_mult=1.0f)
void mult_damage (double multiplier, bool pre_armor=false)
float type_damage (damage_type dt) const
float total_damage () const
void clear ()
bool empty () const
std::vector< damage_unit >::iterator begin ()
std::vector< damage_unit >::const_iterator begin () const
std::vector< damage_unit >::iterator end ()
std::vector< damage_unit >::const_iterator end () const
bool operator== (const damage_instance &other) const
void add_damage (damage_type dt, float amt, float arpen=0.0f, float arpen_mult=1.0f, float dmg_mult=1.0f)
Adds damage to the instance.
void add (const damage_instance &added_di)
void add (const damage_unit &new_du)
void deserialize (JsonIn &)
Static Public Member Functions
static damage_instance physical (float bash, float cut, float stab, float arpen=0.0f)
Public Attributes
std::vector< damage_unit > damage_units
Detailed Description
Definition at line 51 of file damage.h.
Constructor & Destructor Documentation
damage_instance() [1/2]
damage_instance::damage_instance () default
damage_instance() [2/2]
damage_instance::damage_instance (damage_type dt, float amt, float arpen = 0.0f, float arpen_mult = 1.0f, float dmg_mult = 1.0f)
Definition at line 35 of file damage.cpp.
{
    add_damage( dt, amt, arpen, arpen_mult, dmg_mult );
}
References add_damage().
Member Function Documentation
add() [1/2]
void damage_instance::add (const damage_instance & added_di)
Definition at line 93 of file damage.cpp.
{
    for( auto &added_du : added_di.damage_units ) {
        add( added_du );
    }
}
References add(), and damage_units.
Referenced by add(), add_damage(), assign_dmg_proportional(), assign_dmg_relative(), mattack::evolve_kill_strike(), npc_ai::gun_value(), Character::mutation_attacks(), and sting_shoot().
add() [2/2]
void damage_instance::add (const damage_unit & new_du)
Definition at line 100 of file damage.cpp.
{
    auto iter = std::find_if( damage_units.begin(), damage_units.end(),
    [&new_du]( const damage_unit & du ) {
        return du.type == new_du.type;
    } );
    if( iter == damage_units.end() ) {
        damage_units.emplace_back( new_du );
    } else {
        damage_unit &du = *iter;
        // Actually combining two instances of damage is complex and ambiguous
        // So let's just add/multiply the values
        du.amount += new_du.amount;
        du.res_pen += new_du.res_pen;
        du.damage_multiplier *= new_du.damage_multiplier;
        du.res_mult *= new_du.res_mult;
    }
}
References damage_unit::amount, damage_unit::damage_multiplier, damage_units, damage_unit::res_mult, and damage_unit::res_pen.
add_damage()
void damage_instance::add_damage (damage_type dt, float amt, float arpen = 0.0f, float arpen_mult = 1.0f, float dmg_mult = 1.0f)
Adds damage to the instance.
If the damage type already exists in the instance, the old and new instance are normalized. The normalization means that the effective damage can actually decrease (depending on target's armor).
Definition at line 41 of file damage.cpp.
{
    damage_unit du( dt, amt, arpen, arpen_mult, dmg_mult );
    add( du );
}
References add().
Referenced by mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), assign(), trapfunc::beartrap(), trapfunc::blade(), damage_instance(), Character::deal_damage(), mattack::gene_sting(), get_basic_explosion_data(), spell::get_damage_instance(), mtype::load(), Item_factory::load_basic_info(), monster::melee_attack(), Character::melee_special_effects(), player::on_hit(), mattack::para_sting(), physical(), Character::roll_bash_damage(), Character::roll_cut_damage(), Character::roll_stab_damage(), explosion_handler::shrapnel_from_legacy(), trapfunc::snare_heavy(), mattack::spit_sap(), mattack::thrown_by_judo(), and mattack::vine().
begin() [1/2]
std::vector< damage_unit >::iterator damage_instance::begin ()
Definition at line 120 of file damage.cpp.
{
    return damage_units.begin();
}
References damage_units.
Referenced by game::dump_stats(), and target_ui::set_cursor_pos().
begin() [2/2]
std::vector< damage_unit >::const_iterator damage_instance::begin () const
Definition at line 125 of file damage.cpp.
{
    return damage_units.begin();
}
References damage_units.
clear()
void damage_instance::clear ()
Definition at line 83 of file damage.cpp.
{
    damage_units.clear();
}
References damage_units.
Referenced by Item_factory::load_basic_info(), and mult_damage().
deserialize()
void damage_instance::deserialize (JsonIn & jsin)
Definition at line 145 of file damage.cpp.
{
    // TODO: Clean up
    if( jsin.test_object() ) {
        JsonObject jo = jsin.get_object();
        *this = load_damage_instance( jo );
    } else if( jsin.test_array() ) {
        *this = load_damage_instance( jsin.get_array() );
    } else {
        jsin.error( "Expected object or array for damage_instance" );
    }
}
References JsonIn::error(), JsonIn::get_array(), JsonIn::get_object(), load_damage_instance(), JsonIn::test_array(), and JsonIn::test_object().
empty()
bool damage_instance::empty () const
Definition at line 88 of file damage.cpp.
{
    return damage_units.empty();
}
References damage_units.
Referenced by item::ammo_info(), and game::dump_stats().
end() [1/2]
std::vector< damage_unit >::iterator damage_instance::end ()
Definition at line 130 of file damage.cpp.
{
    return damage_units.end();
}
References damage_units.
Referenced by target_ui::set_cursor_pos().
end() [2/2]
std::vector< damage_unit >::const_iterator damage_instance::end () const
Definition at line 135 of file damage.cpp.
{
    return damage_units.end();
}
References damage_units.
mult_damage()
void damage_instance::mult_damage (double multiplier, bool pre_armor = false)
Definition at line 48 of file damage.cpp.
{
    if( multiplier <= 0.0 ) {
        clear();
    }
    if( pre_armor ) {
        for( auto &elem : damage_units ) {
            elem.amount *= multiplier;
        }
    } else {
        for( auto &elem : damage_units ) {
            elem.damage_multiplier *= multiplier;
        }
    }
}
References clear(), and damage_units.
Referenced by Character::absorb_hit(), melee_actor::call(), mattack::evolve_kill_strike(), ranged::fire_gun(), ranged::hit_with_aoe(), Character::melee_attack(), Character::mutation_attacks(), map::shoot(), and explosion_handler::shrapnel().
operator==()
bool damage_instance::operator== (const damage_instance & other) const
Definition at line 140 of file damage.cpp.
{
    return damage_units == other.damage_units;
}
References damage_units, and other.
physical()
damage_instance damage_instance::physical (float bash, float cut, float stab, float arpen = 0.0f) static
Definition at line 27 of file damage.cpp.
{
    damage_instance d;
    d.add_damage( DT_BASH, bash, arpen );
    d.add_damage( DT_CUT, cut, arpen );
    d.add_damage( DT_STAB, stab, arpen );
    return d;
}
References add_damage(), spell_effect::bash(), DT_BASH, DT_CUT, and DT_STAB.
Referenced by Character::activate_bionic(), explosion_handler::do_blast_new(), hardcoded_mutation_attack(), Character::hitall(), melee_actor::melee_actor(), and Character::melee_special_effects().
total_damage()
float damage_instance::total_damage () const
Definition at line 75 of file damage.cpp.
{
    float ret = 0;
    for( const auto &elem : damage_units ) {
        ret += elem.amount * elem.damage_multiplier;
    }
    return ret;
}
References damage_units, and cata::hash64_detail::ret.
Referenced by item::ammo_info(), game::dump_stats(), ranged::execute_shaped_attack(), npc_ai::gun_value(), Character::mutation_attacks(), projectile_attack(), explosion_handler::shrapnel(), ranged::throw_item(), and weapon_inventory_preset::weapon_inventory_preset().
type_damage()
float damage_instance::type_damage (damage_type dt) const
Definition at line 64 of file damage.cpp.
{
    float ret = 0;
    for( const auto &elem : damage_units ) {
        if( elem.type == dt ) {
            ret += elem.amount * elem.damage_multiplier;
        }
    }
    return ret;
}
References damage_units, and cata::hash64_detail::ret.
Referenced by item::combat_info(), print_damage_info(), and map::shoot().
Member Data Documentation
damage_units
std::vector<damage_unit> damage_instance::damage_units
Definition at line 52 of file damage.h.
Referenced by Character::absorb_hit(), monster::absorb_hit(), add(), item::ammo_info(), assign(), assign_dmg_proportional(), assign_dmg_relative(), begin(), Character::block_hit(), check_assigned_dmg(), clear(), Creature::deal_damage(), item::effective_dps(), empty(), end(), item::gun_info(), npc_ai::gun_value(), load_damage_instance_inherit(), load_damage_unit_inherit(), mult_damage(), operator==(), Character::perform_technique(), print_damage_info(), map::shoot(), total_damage(), and type_damage().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp