Cataclysm BN: talk_effect_fun_t Struct Reference
talk_effect_fun_t Struct Reference
#include <dialogue.h>
Public Member Functions
talk_effect_fun_t ()=default
talk_effect_fun_t (talkfunction_ptr)
talk_effect_fun_t (std::function< void(npc &)>)
talk_effect_fun_t (std::function< void(const dialogue &d)>)
void set_companion_mission (const std::string &role_id)
void set_add_effect (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_remove_effect (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_add_trait (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_remove_trait (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_add_var (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_remove_var (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_adjust_var (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_u_buy_item (const itype_id &item_name, int cost, int count, const std::string &container_name)
void set_u_spend_ecash (int amount)
void set_u_sell_item (const itype_id &item_name, int cost, int count)
void set_consume_item (const JsonObject &jo, const std::string &member, int count, bool is_npc=false)
void set_remove_item_with (const JsonObject &jo, const std::string &member, bool is_npc=false)
void set_npc_change_faction (const std::string &faction_name)
void set_npc_change_class (const std::string &class_name)
void set_change_faction_rep (int rep_change)
void set_add_debt (const std::vector< trial_mod > &debt_modifiers)
void set_toggle_npc_rule (const std::string &rule)
void set_set_npc_rule (const std::string &rule)
void set_clear_npc_rule (const std::string &rule)
void set_npc_engagement_rule (const std::string &setting)
void set_npc_aim_rule (const std::string &setting)
void set_npc_cbm_reserve_rule (const std::string &setting)
void set_npc_cbm_recharge_rule (const std::string &setting)
void set_mapgen_update (const JsonObject &jo, const std::string &member)
void set_bulk_trade_accept (bool is_trade, bool is_npc=false)
void set_npc_gets_item (bool to_use)
void set_add_mission (const std::string &mission_id)
const std::vector< std::pair< int, itype_id > > & get_likely_rewards () const
void set_u_buy_monster (const std::string &monster_type_id, int cost, int count, bool pacified, const translation &name)
void set_u_learn_recipe (const std::string &learned_recipe_id)
void set_npc_first_topic (const std::string &chat_topic)
void operator() (const dialogue &d) const
Private Attributes
std::function< void(const dialogue &d)> function
std::vector< std::pair< int, itype_id > > likely_rewards
Detailed Description
Definition at line 83 of file dialogue.h.
Constructor & Destructor Documentation
talk_effect_fun_t() [1/4]
talk_effect_fun_t::talk_effect_fun_t () default
talk_effect_fun_t() [2/4]
talk_effect_fun_t::talk_effect_fun_t (talkfunction_ptr ptr)
Definition at line 1898 of file npctalk.cpp.
{
    function = [ptr]( const dialogue & d ) {
        npc &p = *d.beta;
        ptr( p );
    };
}
References ptr().
talk_effect_fun_t() [3/4]
talk_effect_fun_t::talk_effect_fun_t (std::function< void(npc &)>)
talk_effect_fun_t() [4/4]
talk_effect_fun_t::talk_effect_fun_t (std::function< void(const dialogue &d)> fun)
Definition at line 1914 of file npctalk.cpp.
{
    function = [fun]( const dialogue & d ) {
        fun( d );
    };
}
Member Function Documentation
get_likely_rewards()
const std::vector< std::pair< int, itype_id > > & talk_effect_fun_t::get_likely_rewards () const
Definition at line 2384 of file npctalk.cpp.
{
    return likely_rewards;
}
References likely_rewards.
operator()()
void talk_effect_fun_t::operator() (const dialogue & d) const inline
Definition at line 129 of file dialogue.h.
{
            if( !function ) {
                return;
            }
            return function( d );
        }
set_add_debt()
void talk_effect_fun_t::set_add_debt (const std::vector< trial_mod > & debt_modifiers)
Definition at line 2204 of file npctalk.cpp.
{
    function = [debt_modifiers]( const dialogue & d ) {
        int debt = 0;
        for( const trial_mod &this_mod : debt_modifiers ) {
            if( this_mod.first == "TOTAL" ) {
                debt *= this_mod.second;
            } else {
                debt += parse_mod( d, this_mod.first, this_mod.second );
            }
        }
        d.beta->op_of_u += npc_opinion( 0, 0, 0, 0, debt );
    };
}
References parse_mod().
Referenced by talk_effect_t::parse_sub_effect().
set_add_effect()
void talk_effect_fun_t::set_add_effect (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 1932 of file npctalk.cpp.
{
    efftype_id new_effect( jo.get_string( member ) );
    time_duration duration = 1_turns;
    bool permanent = false;
    if( jo.has_string( "duration" ) ) {
        const std::string dur_string = jo.get_string( "duration" );
        if( dur_string == "PERMANENT" ) {
            permanent = true;
            if( json_report_strict ) {
                // This is immensely ugly, we need json.just_warn_with_context
                try {
                    jo.throw_error( "Effect permanence has been moved to effect_type.  Set permanence there.",
                                    "duration" );
                } catch( const JsonError &e ) {
                    debugmsg( "\n%s", e.what() );
                }
            }
        } else if( !dur_string.empty() && std::stoi( dur_string ) > 0 ) {
            duration = time_duration::from_turns( std::stoi( dur_string ) );
        }
    } else {
        duration = time_duration::from_turns( jo.get_int( "duration", 1 ) );
    }
    function = [is_npc, new_effect, duration, permanent]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        actor->add_effect( new_effect, duration, num_bp );
        if( permanent ) {
            actor->get_effect( new_effect, num_bp ).set_permanent();
        }
    };
}
References Creature::add_effect(), debugmsg, time_duration::from_turns(), Creature::get_effect(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_string(), json_report_strict, mapgen_defer::member, num_bp, effect::set_permanent(), and JsonObject::throw_error().
Referenced by talk_effect_t::parse_sub_effect().
set_add_mission()
void talk_effect_fun_t::set_add_mission (const std::string & mission_id)
Definition at line 2374 of file npctalk.cpp.
{
    function = [mission_id]( const dialogue & d ) {
        npc &p = *d.beta;
        mission *miss = mission::reserve_new( mission_type_id( mission_id ), p.getID() );
        miss->assign( get_avatar() );
        p.chatbin.missions_assigned.push_back( miss );
    };
}
References mission::assign(), npc::chatbin, get_avatar(), Character::getID(), npc_chatbin::missions_assigned, and mission::reserve_new().
Referenced by talk_effect_t::parse_sub_effect().
set_add_trait()
void talk_effect_fun_t::set_add_trait (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 1982 of file npctalk.cpp.
{
    std::string new_trait = jo.get_string( member );
    function = [is_npc, new_trait]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        actor->set_mutation( trait_id( new_trait ) );
    };
}
References JsonObject::get_string(), mapgen_defer::member, Character::set_mutation(), and trait_id.
Referenced by talk_effect_t::parse_sub_effect().
set_add_var()
void talk_effect_fun_t::set_add_var (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 2008 of file npctalk.cpp.
{
    const std::string var_name = get_talk_varname( jo, member );
    const std::string &value = jo.get_string( "value" );
    function = [is_npc, var_name, value]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        actor->set_value( var_name, value );
    };
}
References JsonObject::get_string(), get_talk_varname(), mapgen_defer::member, and Creature::set_value().
Referenced by talk_effect_t::parse_sub_effect().
set_adjust_var()
void talk_effect_fun_t::set_adjust_var (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 2034 of file npctalk.cpp.
{
    const std::string var_name = get_talk_varname( jo, member, false );
    const int value = jo.get_int( "adjustment" );
    function = [is_npc, var_name, value]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        int adjusted_value = value;
        const std::string &var = actor->get_value( var_name );
        if( !var.empty() ) {
            adjusted_value += std::stoi( var );
        }
        actor->set_value( var_name, std::to_string( adjusted_value ) );
    };
}
References JsonObject::get_int(), get_talk_varname(), Creature::get_value(), mapgen_defer::member, Creature::set_value(), and to_string().
Referenced by talk_effect_t::parse_sub_effect().
set_bulk_trade_accept()
void talk_effect_fun_t::set_bulk_trade_accept (bool is_trade, bool is_npc = false)
Definition at line 2320 of file npctalk.cpp.
{
    function = [is_trade, is_npc]( const dialogue & d ) {
        player *seller = d.alpha;
        player *buyer = dynamic_cast<player *>( d.beta );
        if( is_npc ) {
            seller = dynamic_cast<player *>( d.beta );
            buyer = d.alpha;
        }
        int seller_has = seller->charges_of( d.cur_item );
        item tmp( d.cur_item );
        tmp.charges = seller_has;
        if( is_trade ) {
            int price = tmp.price( true ) * ( is_npc ? -1 : 1 ) + d.beta->op_of_u.owed;
            if( d.beta->get_faction() && !d.beta->get_faction()->currency.is_empty() ) {
                const itype_id &pay_in = d.beta->get_faction()->currency;
                item pay( pay_in );
                if( d.beta->value( pay ) > 0 ) {
                    int required = price / d.beta->value( pay );
                    int buyer_has = required;
                    if( is_npc ) {
                        buyer_has = std::min( buyer_has, buyer->charges_of( pay_in ) );
                        buyer->use_charges( pay_in, buyer_has );
                    } else {
                        if( buyer_has == 1 ) {
                            //~ %1%s is the NPC name, %2$s is an item
                            popup( _( "%1$s gives you a %2$s." ), d.beta->disp_name(),
                                   pay.tname() );
                        } else if( buyer_has > 1 ) {
                            //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
                            popup( _( "%1$s gives you %2$d %3$s." ), d.beta->disp_name(), buyer_has,
                                   pay.tname() );
                        }
                    }
                    for( int i = 0; i < buyer_has; i++ ) {
                        seller->i_add( pay );
                        price -= d.beta->value( pay );
                    }
                }
                d.beta->op_of_u.owed = price;
            }
        }
        seller->use_charges( d.cur_item, seller_has );
        buyer->i_add( tmp );
    };
}
References _, item::charges, visitable< T >::charges_of(), Character::i_add(), popup(), item::price(), item::tname(), and Character::use_charges().
Referenced by talk_effect_t::parse_string_effect().
set_change_faction_rep()
void talk_effect_fun_t::set_change_faction_rep (int rep_change)
Definition at line 2193 of file npctalk.cpp.
{
    function = [rep_change]( const dialogue & d ) {
        npc &p = *d.beta;
        if( p.get_faction()->id != faction_id( "no_faction" ) ) {
            p.get_faction()->likes_u += rep_change;
            p.get_faction()->respects_u += rep_change;
        }
    };
}
References npc::get_faction(), faction_template::id, faction_template::likes_u, and faction_template::respects_u.
Referenced by talk_effect_t::parse_sub_effect().
set_clear_npc_rule()
void talk_effect_fun_t::set_clear_npc_rule (const std::string & rule)
Definition at line 2243 of file npctalk.cpp.
{
    function = [rule]( const dialogue & d ) {
        auto flag = ally_rule_strs.find( rule );
        if( flag == ally_rule_strs.end() ) {
            return;
        }
        d.beta->rules.clear_flag( flag->second.rule );
        d.beta->wield_better_weapon();
    };
}
References ally_rule_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_companion_mission()
void talk_effect_fun_t::set_companion_mission (const std::string & role_id)
Definition at line 1921 of file npctalk.cpp.
{
    function = [role_id]( const dialogue & d ) {
        npc &p = *d.beta;
        p.companion_mission_role_id = role_id;
        talk_function::companion_mission( p );
    };
}
References talk_function::companion_mission(), and npc::companion_mission_role_id.
Referenced by talk_effect_t::parse_sub_effect().
set_consume_item()
void talk_effect_fun_t::set_consume_item (const JsonObject & jo, const std::string & member, int count, bool is_npc = false)
Definition at line 2127 of file npctalk.cpp.
{
    itype_id item_name;
    jo.read( member, item_name, true );
    function = [is_npc, item_name, count]( const dialogue & d ) {
        // this is stupid, but I couldn't get the assignment to work
        const auto consume_item = [&]( player & p, const itype_id & item_name, int count ) {
            item old_item( item_name );
            if( p.has_charges( item_name, count ) ) {
                p.use_charges( item_name, count );
            } else if( p.has_amount( item_name, count ) ) {
                p.use_amount( item_name, count );
            } else {
                //~ %1%s is the "You" or the NPC name, %2$s are a translated item name
                popup( _( "%1$s doesn't have a %2$s!" ), p.disp_name(), old_item.tname() );
            }
        };
        if( is_npc ) {
            consume_item( *d.beta, item_name, count );
        } else {
            consume_item( *d.alpha, item_name, count );
        }
    };
}
References _, detail::count(), Character::disp_name(), visitable< T >::has_amount(), Character::has_charges(), mapgen_defer::member, popup(), JsonObject::read(), item::tname(), Character::use_amount(), and Character::use_charges().
Referenced by talk_effect_t::parse_sub_effect().
set_mapgen_update()
void talk_effect_fun_t::set_mapgen_update (const JsonObject & jo, const std::string & member)
Definition at line 2297 of file npctalk.cpp.
{
    mission_target_params target_params = mission_util::parse_mission_om_target( jo );
    std::vector<std::string> update_ids;
    if( jo.has_string( member ) ) {
        update_ids.emplace_back( jo.get_string( member ) );
    } else if( jo.has_array( member ) ) {
        for( const std::string line : jo.get_array( member ) ) {
            update_ids.emplace_back( line );
        }
    }
    function = [target_params, update_ids]( const dialogue & d ) {
        mission_target_params update_params = target_params;
        update_params.guy = d.beta;
        const tripoint_abs_omt omt_pos = mission_util::get_om_terrain_pos( update_params );
        for( const std::string &mapgen_update_id : update_ids ) {
            run_mapgen_update_func( mapgen_update_id, omt_pos, d.beta->chatbin.mission_selected );
        }
    };
}
References JsonObject::get_array(), mission_util::get_om_terrain_pos(), JsonObject::get_string(), mission_target_params::guy, JsonObject::has_array(), JsonObject::has_string(), line(), mapgen_defer::member, mission_util::parse_mission_om_target(), and run_mapgen_update_func().
Referenced by talk_effect_t::parse_sub_effect().
set_npc_aim_rule()
void talk_effect_fun_t::set_npc_aim_rule (const std::string & setting)
Definition at line 2266 of file npctalk.cpp.
{
    function = [setting]( const dialogue & d ) {
        auto rule = aim_rule_strs.find( setting );
        if( rule != aim_rule_strs.end() ) {
            d.beta->rules.aim = rule->second;
            d.beta->invalidate_range_cache();
        }
    };
}
References aim_rule_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_npc_cbm_recharge_rule()
void talk_effect_fun_t::set_npc_cbm_recharge_rule (const std::string & setting)
Definition at line 2287 of file npctalk.cpp.
{
    function = [setting]( const dialogue & d ) {
        auto rule = cbm_recharge_strs.find( setting );
        if( rule != cbm_recharge_strs.end() ) {
            d.beta->rules.cbm_recharge = rule->second;
        }
    };
}
References cbm_recharge_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_npc_cbm_reserve_rule()
void talk_effect_fun_t::set_npc_cbm_reserve_rule (const std::string & setting)
Definition at line 2277 of file npctalk.cpp.
{
    function = [setting]( const dialogue & d ) {
        auto rule = cbm_reserve_strs.find( setting );
        if( rule != cbm_reserve_strs.end() ) {
            d.beta->rules.cbm_reserve = rule->second;
        }
    };
}
References cbm_reserve_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_npc_change_class()
void talk_effect_fun_t::set_npc_change_class (const std::string & class_name)
Definition at line 2185 of file npctalk.cpp.
{
    function = [class_name]( const dialogue & d ) {
        npc &p = *d.beta;
        p.myclass = npc_class_id( class_name );
    };
}
References npc::myclass.
Referenced by talk_effect_t::parse_sub_effect().
set_npc_change_faction()
void talk_effect_fun_t::set_npc_change_faction (const std::string & faction_name)
Definition at line 2177 of file npctalk.cpp.
{
    function = [faction_name]( const dialogue & d ) {
        npc &p = *d.beta;
        p.set_fac( faction_id( faction_name ) );
    };
}
References npc::set_fac().
Referenced by talk_effect_t::parse_sub_effect().
set_npc_engagement_rule()
void talk_effect_fun_t::set_npc_engagement_rule (const std::string & setting)
Definition at line 2255 of file npctalk.cpp.
{
    function = [setting]( const dialogue & d ) {
        auto rule = combat_engagement_strs.find( setting );
        if( rule != combat_engagement_strs.end() ) {
            d.beta->rules.engagement = rule->second;
            d.beta->invalidate_range_cache();
        }
    };
}
References combat_engagement_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_npc_first_topic()
void talk_effect_fun_t::set_npc_first_topic (const std::string & chat_topic)
Definition at line 2440 of file npctalk.cpp.
{
    function = [chat_topic]( const dialogue & d ) {
        d.beta->chatbin.first_topic = chat_topic;
    };
}
Referenced by talk_effect_t::parse_sub_effect().
set_npc_gets_item()
void talk_effect_fun_t::set_npc_gets_item (bool to_use)
Definition at line 2367 of file npctalk.cpp.
{
    function = [to_use]( const dialogue & d ) {
        d.reason = give_item_to( *( d.beta ), to_use );
    };
}
References give_item_to().
Referenced by talk_effect_t::parse_string_effect().
set_remove_effect()
void talk_effect_fun_t::set_remove_effect (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 1969 of file npctalk.cpp.
{
    std::string old_effect = jo.get_string( member );
    function = [is_npc, old_effect]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        actor->remove_effect( efftype_id( old_effect ), num_bp );
    };
}
References efftype_id, JsonObject::get_string(), mapgen_defer::member, num_bp, and Creature::remove_effect().
Referenced by talk_effect_t::parse_sub_effect().
set_remove_item_with()
void talk_effect_fun_t::set_remove_item_with (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 2154 of file npctalk.cpp.
{
    const std::string &item_name = jo.get_string( member );
    function = [is_npc, item_name]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        itype_id item_id = itype_id( item_name );
        actor->remove_items_with( [item_id]( const item & it ) {
            return it.typeId() == item_id;
        } );
    };
}
References JsonObject::get_string(), itype_id, mapgen_defer::member, visitable< T >::remove_items_with(), and item::typeId().
Referenced by talk_effect_t::parse_sub_effect().
set_remove_trait()
void talk_effect_fun_t::set_remove_trait (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 1995 of file npctalk.cpp.
{
    std::string old_trait = jo.get_string( member );
    function = [is_npc, old_trait]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        actor->unset_mutation( trait_id( old_trait ) );
    };
}
References JsonObject::get_string(), mapgen_defer::member, trait_id, and Character::unset_mutation().
Referenced by talk_effect_t::parse_sub_effect().
set_remove_var()
void talk_effect_fun_t::set_remove_var (const JsonObject & jo, const std::string & member, bool is_npc = false)
Definition at line 2021 of file npctalk.cpp.
{
    const std::string var_name = get_talk_varname( jo, member, false );
    function = [is_npc, var_name]( const dialogue & d ) {
        player *actor = d.alpha;
        if( is_npc ) {
            actor = dynamic_cast<player *>( d.beta );
        }
        actor->remove_value( var_name );
    };
}
References get_talk_varname(), mapgen_defer::member, and Creature::remove_value().
Referenced by talk_effect_t::parse_sub_effect().
set_set_npc_rule()
void talk_effect_fun_t::set_set_npc_rule (const std::string & rule)
Definition at line 2231 of file npctalk.cpp.
{
    function = [rule]( const dialogue & d ) {
        auto flag = ally_rule_strs.find( rule );
        if( flag == ally_rule_strs.end() ) {
            return;
        }
        d.beta->rules.set_flag( flag->second.rule );
        d.beta->wield_better_weapon();
    };
}
References ally_rule_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_toggle_npc_rule()
void talk_effect_fun_t::set_toggle_npc_rule (const std::string & rule)
Definition at line 2219 of file npctalk.cpp.
{
    function = [rule]( const dialogue & d ) {
        auto toggle = ally_rule_strs.find( rule );
        if( toggle == ally_rule_strs.end() ) {
            return;
        }
        d.beta->rules.toggle_flag( toggle->second.rule );
        d.beta->wield_better_weapon();
    };
}
References ally_rule_strs.
Referenced by talk_effect_t::parse_sub_effect().
set_u_buy_item()
void talk_effect_fun_t::set_u_buy_item (const itype_id & item_name, int cost, int count, const std::string & container_name)
Definition at line 2056 of file npctalk.cpp.
{
    function = [item_name, cost, count, container_name]( const dialogue & d ) {
        npc &p = *d.beta;
        player &u = *d.alpha;
        if( !npc_trading::pay_npc( p, cost ) ) {
            popup( _( "You can't afford it!" ) );
            return;
        }
        if( container_name.empty() ) {
            item new_item = item( item_name, calendar::turn );
            if( new_item.count_by_charges() ) {
                new_item.mod_charges( count - 1 );
                u.i_add( new_item );
            } else {
                for( int i_cnt = 0; i_cnt < count; i_cnt++ ) {
                    u.i_add( new_item );
                }
            }
            if( count == 1 ) {
                //~ %1%s is the NPC name, %2$s is an item
                popup( _( "%1$s gives you a %2$s." ), p.name, new_item.tname() );
            } else {
                //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
                popup( _( "%1$s gives you %2$d %3$s." ), p.name, count, new_item.tname() );
            }
        } else {
            item container( container_name, calendar::turn );
            container.put_in( item( item_name, calendar::turn, count ) );
            u.i_add( container );
            //~ %1%s is the NPC name, %2$s is an item
            popup( _( "%1$s gives you a %2$s." ), p.name, container.tname() );
        }
    };
    // Update structure used by mission descriptions.
    if( cost <= 0 ) {
        likely_rewards.push_back( std::pair<int, itype_id>( count, item_name ) );
    }
}
References _, detail::count(), item::count_by_charges(), Character::i_add(), likely_rewards, item::mod_charges(), Character::name, npc_trading::pay_npc(), popup(), item::put_in(), item::tname(), and calendar::turn.
Referenced by talk_effect_t::parse_sub_effect().
set_u_buy_monster()
void talk_effect_fun_t::set_u_buy_monster (const std::string & monster_type_id, int cost, int count, bool pacified, const translation & name)
Definition at line 2389 of file npctalk.cpp.
{
    function = [monster_type_id, cost, count, pacified, name]( const dialogue & d ) {
        npc &p = *d.beta;
        player &u = *d.alpha;
        if( !npc_trading::pay_npc( p, cost ) ) {
            popup( _( "You can't afford it!" ) );
            return;
        }
        const mtype_id mtype( monster_type_id );
        for( int i = 0; i < count; i++ ) {
            monster *const mon_ptr = g->place_critter_around( mtype, u.pos(), 3 );
            if( !mon_ptr ) {
                add_msg( m_debug, "Cannot place u_buy_monster, no valid placement locations." );
                break;
            }
            monster &tmp = *mon_ptr;
            // Our monster is always a pet.
            tmp.friendly = -1;
            tmp.add_effect( effect_pet, 1_turns, num_bp );
            if( pacified ) {
                tmp.add_effect( effect_pacified, 1_turns, num_bp );
            }
            if( !name.empty() ) {
                tmp.unique_name = name.translated();
            }
        }
        if( name.empty() ) {
            popup( _( "%1$s gives you %2$d %3$s." ), p.name, count, mtype.obj().nname( count ) );
        } else {
            popup( _( "%1$s gives you %2$s." ), p.name, name );
        }
    };
}
References _, monster::add_effect(), add_msg(), detail::count(), effect_pacified, effect_pet, monster::friendly, g, m_debug, Character::name, om_direction::name(), mtype::nname(), num_bp, npc_trading::pay_npc(), popup(), Character::pos(), and monster::unique_name.
Referenced by talk_effect_t::parse_sub_effect().
set_u_learn_recipe()
void talk_effect_fun_t::set_u_learn_recipe (const std::string & learned_recipe_id)
Definition at line 2431 of file npctalk.cpp.
{
    function = [learned_recipe_id]( const dialogue & d ) {
        const recipe &r = recipe_id( learned_recipe_id ).obj();
        d.alpha->learn_recipe( &r );
        popup( _( "You learn how to craft %s." ), r.result_name() );
    };
}
References _, string_id< T >::obj(), popup(), and recipe::result_name().
Referenced by talk_effect_t::parse_sub_effect().
set_u_sell_item()
void talk_effect_fun_t::set_u_sell_item (const itype_id & item_name, int cost, int count)
Definition at line 2098 of file npctalk.cpp.
{
    function = [item_name, cost, count]( const dialogue & d ) {
        npc &p = *d.beta;
        player &u = *d.alpha;
        if( item::count_by_charges( item_name ) && u.has_charges( item_name, count ) ) {
            for( const item &it : u.use_charges( item_name, count ) ) {
                p.i_add( it );
            }
        } else if( u.has_amount( item_name, count ) ) {
            for( const item &it : u.use_amount( item_name, count ) ) {
                p.i_add( it );
            }
        } else {
            //~ %1$s is a translated item name
            popup( _( "You don't have a %1$s!" ), item::nname( item_name ) );
            return;
        }
        if( count == 1 ) {
            //~ %1%s is the NPC name, %2$s is an item
            popup( _( "You give %1$s a %2$s." ), p.name, item::nname( item_name ) );
        } else {
            //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
            popup( _( "You give %1$s %2$d %3$s." ), p.name, count, item::nname( item_name, count ) );
        }
        p.op_of_u.owed += cost;
    };
}
References _, detail::count(), item::count_by_charges(), visitable< T >::has_amount(), Character::has_charges(), Character::i_add(), Character::name, item::nname(), npc::op_of_u, npc_opinion::owed, popup(), Character::use_amount(), and Character::use_charges().
Referenced by talk_effect_t::parse_sub_effect().
set_u_spend_ecash()
void talk_effect_fun_t::set_u_spend_ecash (int amount)
Definition at line 2170 of file npctalk.cpp.
{
    function = [amount]( const dialogue & d ) {
        d.alpha->cash -= amount;
    };
}
Referenced by talk_effect_t::parse_sub_effect().
Member Data Documentation
function
std::function<void(const dialogue &d)> talk_effect_fun_t::function private
Definition at line 85 of file dialogue.h.
likely_rewards
std::vector<std::pair<int, itype_id> > talk_effect_fun_t::likely_rewards private
Definition at line 86 of file dialogue.h.
Referenced by get_likely_rewards(), and set_u_buy_item().
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp