Cataclysm BN: translatable_mod_info Struct Reference
translatable_mod_info Struct Reference
#include <mod_manager.h>
Public Member Functions
translatable_mod_info ()
translatable_mod_info (std::string name, std::string description, std::string path)
std::string name ()
std::string description ()
Private Member Functions
void update ()
Private Attributes
std::string mod_path
std::string name_raw
std::string name_tr
std::string description_raw
std::string description_tr
int language_version = 0
Detailed Description
Definition at line 27 of file mod_manager.h.
Constructor & Destructor Documentation
translatable_mod_info() [1/2]
translatable_mod_info::translatable_mod_info ()
Definition at line 495 of file mod_manager.cpp.
{
    language_version = INVALID_LANGUAGE_VERSION;
}
References INVALID_LANGUAGE_VERSION, and language_version.
translatable_mod_info() [2/2]
translatable_mod_info::translatable_mod_info (std::string name, std::string description, std::string path)
Definition at line 500 of file mod_manager.cpp.
                                                    :
    mod_path( mod_path ), name_raw( name ), description_raw( description )
{
    language_version = INVALID_LANGUAGE_VERSION;
}
References INVALID_LANGUAGE_VERSION, and language_version.
Member Function Documentation
description()
std::string translatable_mod_info::description ()
Definition at line 518 of file mod_manager.cpp.
{
    if( description_raw.empty() ) {
        return "";
    }
    if( language_version != detail::get_current_language_version() ) {
        update();
    }
    return description_tr;
}
References description_raw, description_tr, detail::get_current_language_version(), language_version, and update().
Referenced by MOD_INFORMATION::description().
name()
std::string translatable_mod_info::name ()
Definition at line 507 of file mod_manager.cpp.
{
    if( name_raw.empty() ) {
        return "";
    }
    if( language_version != detail::get_current_language_version() ) {
        update();
    }
    return name_tr;
}
References detail::get_current_language_version(), language_version, name_raw, name_tr, and update().
Referenced by MOD_INFORMATION::name().
update()
void translatable_mod_info::update () private
Definition at line 554 of file language.cpp.
{
    language_version = detail::get_current_language_version();
    // First, try base game's translation file (for in-repo mods)
    name_tr = _( name_raw );
    description_tr = _( description_raw );
    if( name_tr != name_raw || description_tr != description_raw ) {
        return;
    }
    // For 3rd-party mods, try that mod's translation file
    std::vector<trans_catalogue> list;
    l10n_data::add_mod_catalogue_if_exists( list, get_language().id, mod_path );
    if( list.empty() ) {
        return;
    }
    trans_library lib = trans_library::create( std::move( list ) );
    name_tr = lib.get( name_raw.c_str() );
    description_tr = lib.get( description_raw.c_str() );
}
References _, l10n_data::add_mod_catalogue_if_exists(), description_raw, description_tr, cata_libintl::trans_library::get(), detail::get_current_language_version(), get_language(), language_version, mod_path, avatar_action::move(), name_raw, and name_tr.
Referenced by description(), and name().
Member Data Documentation
description_raw
std::string translatable_mod_info::description_raw private
Definition at line 32 of file mod_manager.h.
Referenced by description(), and update().
description_tr
std::string translatable_mod_info::description_tr private
Definition at line 33 of file mod_manager.h.
Referenced by description(), and update().
language_version
int translatable_mod_info::language_version = 0 private
Definition at line 34 of file mod_manager.h.
Referenced by description(), name(), translatable_mod_info(), and update().
mod_path
std::string translatable_mod_info::mod_path private
Definition at line 29 of file mod_manager.h.
Referenced by update().
name_raw
std::string translatable_mod_info::name_raw private
Definition at line 30 of file mod_manager.h.
Referenced by name(), and update().
name_tr
std::string translatable_mod_info::name_tr private
Definition at line 31 of file mod_manager.h.
Referenced by name(), and update().
The documentation for this struct was generated from the following files:
src/mod_manager.h
src/language.cpp
src/mod_manager.cpp