Cataclysm BN: tutorial_game Struct Reference
tutorial_game Struct Reference
#include <gamemode_tutorial.h>
Public Member Functions
special_game_id id () override
bool init () override
void per_turn () override
void pre_action (action_id &act) override
void post_action (action_id act) override
void game_over () override
Public Member Functions inherited from special_game
virtual ~special_game ()=default
Private Member Functions
void add_message (tut_lesson lesson)
Private Attributes
std::map< tut_lesson, bool > tutorials_seen
Detailed Description
Definition at line 59 of file gamemode_tutorial.h.
Member Function Documentation
add_message()
void tutorial_game::add_message (tut_lesson lesson) private
Definition at line 331 of file gamemode_tutorial.cpp.
{
    if( tutorials_seen[lesson] ) {
        return;
    }
    tutorials_seen[lesson] = true;
    g->invalidate_main_ui_adaptor();
    popup( SNIPPET.get_snippet_by_id( snippet_id( io::enum_to_string<tut_lesson>( lesson ) ) ).value_or(
               translation() ).translated(), PF_ON_TOP );
}
References io::enum_to_string< tut_lesson >(), g, snippet_library::get_snippet_by_id(), PF_ON_TOP, popup(), SNIPPET, and tutorials_seen.
Referenced by per_turn(), and post_action().
game_over()
void tutorial_game::game_over () inline override virtual
Reimplemented from special_game.
Definition at line 67 of file gamemode_tutorial.h.
{ }
id()
special_game_id tutorial_game::id () inline override virtual
Reimplemented from special_game.
Definition at line 60 of file gamemode_tutorial.h.
{
            return SGAME_TUTORIAL;
        }
References SGAME_TUTORIAL.
init()
bool tutorial_game::init () override virtual
Reimplemented from special_game.
Definition at line 107 of file gamemode_tutorial.cpp.
{
    // TODO: clean up old tutorial
    avatar &you = get_avatar();
    // Start at noon
    calendar::turn = calendar::turn_zero + 12_hours;
    tutorials_seen.clear();
    g->scent.reset();
    get_weather().temperature = 65;
    // We use a Z-factor of 10 so that we don't plop down tutorial rooms in the
    // middle of the "real" game world
    character_funcs::normalize( you );
    you.str_cur = you.str_max;
    you.per_cur = you.per_max;
    you.int_cur = you.int_max;
    you.dex_cur = you.dex_max;
    you.set_all_parts_hp_to_max();
    const oter_id rock( "rock" );
    //~ default name for the tutorial
    you.name = _( "John Smith" );
    you.prof = profession::generic();
    // overmap terrain coordinates
    const tripoint_om_omt lp( 50, 50, 0 );
    // Assume overmap zero
    const tripoint_abs_omt lp_abs = project_combine( point_abs_om(), lp );
    auto &starting_om = overmap_buffer.get( point_abs_om() );
    for( int i = 0; i < OMAPX; i++ ) {
        for( int j = 0; j < OMAPY; j++ ) {
            tripoint_om_omt p( i, j, 0 );
            starting_om.ter_set( p + tripoint_below, rock );
            // Start with the overmap revealed
            starting_om.seen( p ) = true;
        }
    }
    starting_om.ter_set( lp, oter_id( "tutorial" ) );
    starting_om.ter_set( lp + tripoint_below, oter_id( "tutorial" ) );
    starting_om.clear_mon_groups();
    you.toggle_trait( trait_QUICK );
    item lighter( "lighter", calendar::start_of_cataclysm );
    lighter.invlet = 'e';
    you.inv.add_item( lighter, true, false );
    you.set_skill_level( skill_gun, 5 );
    you.set_skill_level( skill_melee, 5 );
    g->load_map( project_to<coords::sm>( lp_abs ) );
    you.setx( 2 );
    you.sety( 4 );
    // This shifts the view to center the players pos
    g->update_map( you );
    return true;
}
References _, inventory::add_item(), Character::dex_cur, Character::dex_max, g, profession::generic(), overmapbuffer::get(), get_avatar(), get_weather(), Character::int_cur, Character::int_max, Character::inv, item::invlet, Character::name, character_funcs::normalize(), OMAPX, OMAPY, oter_id, overmap_buffer, Character::per_cur, Character::per_max, Character::prof, coords::project_combine(), Creature::set_all_parts_hp_to_max(), Character::set_skill_level(), Character::setx(), Character::sety(), skill_gun, skill_melee, calendar::start_of_cataclysm, Character::str_cur, Character::str_max, weather_manager::temperature, Character::toggle_trait(), trait_QUICK, tripoint_below, calendar::turn, calendar::turn_zero, and tutorials_seen.
per_turn()
void tutorial_game::per_turn () override virtual
Reimplemented from special_game.
Definition at line 163 of file gamemode_tutorial.cpp.
{
    // note that add_message does nothing if the message was already shown
    add_message( tut_lesson::LESSON_INTRO );
    add_message( tut_lesson::LESSON_MOVE );
    add_message( tut_lesson::LESSON_LOOK );
    if( g->light_level( g->u.posz() ) == 1 ) {
        if( g->u.has_amount( itype_flashlight, 1 ) ) {
            add_message( tut_lesson::LESSON_DARK );
        } else {
            add_message( tut_lesson::LESSON_DARK_NO_FLASH );
        }
    }
    if( g->u.get_pain() > 0 ) {
        add_message( tut_lesson::LESSON_PAIN );
    }
    if( g->u.recoil >= MAX_RECOIL ) {
        add_message( tut_lesson::LESSON_RECOIL );
    }
    map &here = get_map();
    if( !tutorials_seen[tut_lesson::LESSON_BUTCHER] ) {
        for( const item &it : here.i_at( point( g->u.posx(), g->u.posy() ) ) ) {
            if( it.is_corpse() ) {
                add_message( tut_lesson::LESSON_BUTCHER );
                break;
            }
        }
    }
    for( const tripoint &p : here.points_in_radius( g->u.pos(), 1 ) ) {
        if( here.ter( p ) == t_door_o ) {
            add_message( tut_lesson::LESSON_OPEN );
            break;
        } else if( here.ter( p ) == t_door_c ) {
            add_message( tut_lesson::LESSON_CLOSE );
            break;
        } else if( here.ter( p ) == t_window ) {
            add_message( tut_lesson::LESSON_SMASH );
            break;
        } else if( here.furn( p ) == f_rack && !here.i_at( p ).empty() ) {
            add_message( tut_lesson::LESSON_EXAMINE );
            break;
        } else if( here.ter( p ) == t_stairs_down ) {
            add_message( tut_lesson::LESSON_STAIRS );
            break;
        } else if( here.ter( p ) == t_water_sh ) {
            add_message( tut_lesson::LESSON_PICKUP_WATER );
            break;
        }
    }
    if( !here.i_at( point( g->u.posx(), g->u.posy() ) ).empty() ) {
        add_message( tut_lesson::LESSON_PICKUP );
    }
}
References add_message(), item_stack::empty(), f_rack, map::furn(), g, get_map(), map::i_at(), itype_flashlight, LESSON_BUTCHER, LESSON_CLOSE, LESSON_DARK, LESSON_DARK_NO_FLASH, LESSON_EXAMINE, LESSON_INTRO, LESSON_LOOK, LESSON_MOVE, LESSON_OPEN, LESSON_PAIN, LESSON_PICKUP, LESSON_PICKUP_WATER, LESSON_RECOIL, LESSON_SMASH, LESSON_STAIRS, MAX_RECOIL, map::points_in_radius(), t_door_c, t_door_o, t_stairs_down, t_water_sh, t_window, map::ter(), and tutorials_seen.
post_action()
void tutorial_game::post_action (action_id act) override virtual
Reimplemented from special_game.
Definition at line 237 of file gamemode_tutorial.cpp.
{
    switch( act ) {
        case ACTION_RELOAD_WEAPON:
            if( g->u.weapon.is_gun() && !tutorials_seen[tut_lesson::LESSON_GUN_FIRE] ) {
                g->place_critter_at( mon_zombie, tripoint( g->u.posx(), g->u.posy() - 6, g->u.posz() ) );
                g->place_critter_at( mon_zombie, tripoint( g->u.posx() + 2, g->u.posy() - 5, g->u.posz() ) );
                g->place_critter_at( mon_zombie, tripoint( g->u.posx() - 2, g->u.posy() - 5, g->u.posz() ) );
                add_message( tut_lesson::LESSON_GUN_FIRE );
            }
            break;
        case ACTION_OPEN:
            add_message( tut_lesson::LESSON_CLOSE );
            break;
        case ACTION_CLOSE:
            add_message( tut_lesson::LESSON_SMASH );
            break;
        case ACTION_USE: {
            if( g->u.has_amount( itype_grenade_act, 1 ) ) {
                add_message( tut_lesson::LESSON_ACT_GRENADE );
            }
            map &here = get_map();
            for( const tripoint &dest : here.points_in_radius( g->u.pos(), 1 ) ) {
                if( here.tr_at( dest ).id == trap_str_id( "tr_bubblewrap" ) ) {
                    add_message( tut_lesson::LESSON_ACT_BUBBLEWRAP );
                }
            }
        }
        break;
        case ACTION_EAT:
            if( g->u.last_item == itype_codeine ) {
                add_message( tut_lesson::LESSON_TOOK_PAINKILLER );
            } else if( g->u.last_item == itype_cig ) {
                add_message( tut_lesson::LESSON_TOOK_CIG );
            } else if( g->u.last_item == itype_water ) {
                add_message( tut_lesson::LESSON_DRANK_WATER );
            }
            break;
        case ACTION_WEAR: {
            item it( g->u.last_item, calendar::start_of_cataclysm );
            if( it.is_armor() ) {
                if( it.get_coverage() >= 2 || it.get_thickness() >= 2 ) {
                    add_message( tut_lesson::LESSON_WORE_ARMOR );
                }
                if( it.get_storage() >= units::from_liter( 5 ) ) {
                    add_message( tut_lesson::LESSON_WORE_STORAGE );
                }
                if( it.get_env_resist() >= 2 ) {
                    add_message( tut_lesson::LESSON_WORE_MASK );
                }
            }
        }
        break;
        case ACTION_WIELD:
            if( g->u.weapon.is_gun() ) {
                add_message( tut_lesson::LESSON_GUN_LOAD );
            }
            break;
        case ACTION_EXAMINE:
            add_message( tut_lesson::LESSON_INTERACT );
        /* fallthrough */
        case ACTION_PICKUP: {
            item it( g->u.last_item, calendar::start_of_cataclysm );
            if( it.is_armor() ) {
                add_message( tut_lesson::LESSON_GOT_ARMOR );
            } else if( it.is_gun() ) {
                add_message( tut_lesson::LESSON_GOT_GUN );
            } else if( it.is_ammo() ) {
                add_message( tut_lesson::LESSON_GOT_AMMO );
            } else if( it.is_tool() ) {
                add_message( tut_lesson::LESSON_GOT_TOOL );
            } else if( it.is_food() ) {
                add_message( tut_lesson::LESSON_GOT_FOOD );
            } else if( it.is_melee() ) {
                add_message( tut_lesson::LESSON_GOT_WEAPON );
            }
        }
        break;
        default:
            // TODO: add more actions here
            break;
    }
}
References act, ACTION_CLOSE, ACTION_EAT, ACTION_EXAMINE, ACTION_OPEN, ACTION_PICKUP, ACTION_RELOAD_WEAPON, ACTION_USE, ACTION_WEAR, ACTION_WIELD, add_message(), units::from_liter(), g, item::get_coverage(), item::get_env_resist(), get_map(), item::get_storage(), item::get_thickness(), trap::id, item::is_ammo(), item::is_armor(), item::is_food(), item::is_gun(), item::is_melee(), item::is_tool(), itype_cig, itype_codeine, itype_grenade_act, itype_water, LESSON_ACT_BUBBLEWRAP, LESSON_ACT_GRENADE, LESSON_CLOSE, LESSON_DRANK_WATER, LESSON_GOT_AMMO, LESSON_GOT_ARMOR, LESSON_GOT_FOOD, LESSON_GOT_GUN, LESSON_GOT_TOOL, LESSON_GOT_WEAPON, LESSON_GUN_FIRE, LESSON_GUN_LOAD, LESSON_INTERACT, LESSON_SMASH, LESSON_TOOK_CIG, LESSON_TOOK_PAINKILLER, LESSON_WORE_ARMOR, LESSON_WORE_MASK, LESSON_WORE_STORAGE, mon_zombie, map::points_in_radius(), calendar::start_of_cataclysm, map::tr_at(), and tutorials_seen.
pre_action()
void tutorial_game::pre_action (action_id & act) override virtual
Reimplemented from special_game.
Definition at line 223 of file gamemode_tutorial.cpp.
{
    switch( act ) {
        case ACTION_SAVE:
        case ACTION_QUICKSAVE:
            popup( _( "You're saving a tutorial - the tutorial world lacks certain features of normal worlds.  "
                      "Weird things might happen when you load this save.  You have been warned." ) );
            break;
        default:
            // Other actions are fine.
            break;
    }
}
References _, act, ACTION_QUICKSAVE, ACTION_SAVE, and popup().
Member Data Documentation
tutorials_seen
std::map<tut_lesson, bool> tutorial_game::tutorials_seen private
Definition at line 72 of file gamemode_tutorial.h.
Referenced by add_message(), init(), per_turn(), and post_action().
The documentation for this struct was generated from the following files:
src/gamemode_tutorial.h
src/gamemode_tutorial.cpp