Cataclysm BN: computer_option Struct Reference
computer_option Struct Reference
#include <computer.h>
Public Member Functions
computer_option ()
computer_option (const std::string &N, computer_action A, int S)
void serialize (JsonOut &jout) const
void deserialize (JsonIn &jin)
Static Public Member Functions
static computer_option from_json (const JsonObject &jo)
Public Attributes
std::string name
computer_action action
int security
Detailed Description
Definition at line 82 of file computer.h.
Constructor & Destructor Documentation
computer_option() [1/2]
computer_option::computer_option ()
Definition at line 17 of file computer.cpp.
    : name( "Unknown" ), action( COMPACT_NULL ), security( 0 )
{
}
Referenced by from_json().
computer_option() [2/2]
computer_option::computer_option (const std::string & N, computer_action A, int S)
Definition at line 22 of file computer.cpp.
    : name( N ), action( A ), security( S )
{
}
Member Function Documentation
deserialize()
void computer_option::deserialize (JsonIn & jin)
Definition at line 37 of file computer.cpp.
{
    const JsonObject jo = jin.get_object();
    name = jo.get_string( "name" );
    action = jo.get_enum_value<computer_action>( "action" );
    security = jo.get_int( "security" );
}
References action, JsonObject::get_enum_value(), JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), name, and security.
from_json()
computer_option computer_option::from_json (const JsonObject & jo) static
Definition at line 383 of file computer.cpp.
{
    translation name;
    jo.read( "name", name );
    const computer_action action = jo.get_enum_value<computer_action>( "action" );
    const int sec = jo.get_int( "security", 0 );
    return computer_option( name.translated(), action, sec );
}
References action, computer_option(), JsonObject::get_enum_value(), JsonObject::get_int(), name, and JsonObject::read().
Referenced by jmapgen_computer::jmapgen_computer().
serialize()
void computer_option::serialize (JsonOut & jout) const
Definition at line 27 of file computer.cpp.
{
    jout.start_object();
    jout.member( "name", name );
    jout.member( "action" );
    jout.write_as_string( action );
    jout.member( "security", security );
    jout.end_object();
}
References action, JsonOut::end_object(), JsonOut::member(), name, security, JsonOut::start_object(), and JsonOut::write_as_string().
Member Data Documentation
action
computer_action computer_option::action
Definition at line 84 of file computer.h.
Referenced by deserialize(), from_json(), serialize(), and computer_session::use().
name
std::string computer_option::name
Definition at line 83 of file computer.h.
Referenced by deserialize(), from_json(), and serialize().
security
int computer_option::security
Definition at line 85 of file computer.h.
Referenced by deserialize(), serialize(), and computer_session::use().
The documentation for this struct was generated from the following files:
src/computer.h
src/computer.cpp