Cataclysm BN: point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > > Struct Template Reference
point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > > Struct Template Reference
#include <point_traits.h>
Static Public Member Functions
static float & x (Point &p)
static const float & x (const Point &p)
static float & y (Point &p)
static const float & y (const Point &p)
static float & z (Point &p)
static const float & z (const Point &p)
constexpr static float & at (Point &p, size_t i)
constexpr static const float & at (const Point &p, size_t i)
Detailed Description
template<typename Point>
struct point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >
Definition at line 59 of file point_traits.h.
Member Function Documentation
at() [1/2]
template<typename Point > constexpr static const float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::at (const Point & p, size_t i) inline static constexpr
Definition at line 94 of file point_traits.h.
{
        switch( i ) {
            case 0:
                return x( p );
            case 1:
                return y( p );
            case 2:
                return z( p );
        }
        return x( p );
    }
References point_traits< Point, typename >::x(), point_traits< Point, typename >::y(), and point_traits< Point, typename >::z().
at() [2/2]
template<typename Point > constexpr static float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::at (Point & p, size_t i) inline static constexpr
Definition at line 82 of file point_traits.h.
{
        switch( i ) {
            case 0:
                return x( p );
            case 1:
                return y( p );
            case 2:
                return z( p );
        }
        // Template would make this impossible
        return x( p );
    }
References point_traits< Point, typename >::x(), point_traits< Point, typename >::y(), and point_traits< Point, typename >::z().
x() [1/2]
template<typename Point > static const float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::x (const Point & p) inline static
Definition at line 66 of file point_traits.h.
{
        return p.x;
    }
x() [2/2]
template<typename Point > static float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::x (Point & p) inline static
Definition at line 63 of file point_traits.h.
{
        return p.x;
    }
y() [1/2]
template<typename Point > static const float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::y (const Point & p) inline static
Definition at line 72 of file point_traits.h.
{
        return p.y;
    }
y() [2/2]
template<typename Point > static float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::y (Point & p) inline static
Definition at line 69 of file point_traits.h.
{
        return p.y;
    }
z() [1/2]
template<typename Point > static const float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::z (const Point & p) inline static
Definition at line 78 of file point_traits.h.
{
        return p.z;
    }
z() [2/2]
template<typename Point > static float & point_traits< Point, std::enable_if_t< std::is_same< Point, rl_vec2d >::value||std::is_same< Point, rl_vec3d >::value > >::z (Point & p) inline static
Definition at line 75 of file point_traits.h.
{
        return p.z;
    }
The documentation for this struct was generated from the following file:
src/point_traits.h