Cataclysm BN: tool_comp Struct Reference
tool_comp Struct Reference
#include <requirements.h>
Public Member Functions
tool_comp ()=default
tool_comp (const itype_id &TYPE, int COUNT, bool subtype_expanded=false)
void load (const JsonValue &value)
void dump (JsonOut &jsout) const
bool has (const inventory &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, cost_adjustment=cost_adjustment::none, std::function< void(int)> visitor=std::function< void(int)>()) const
std::string to_string (int batch=1, int avail=0) const
nc_color get_color (bool has_one, const inventory &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1) const
bool by_charges () const
component_type get_component_type () const
Public Member Functions inherited from component
bool operator== (const component &rhs) const
bool operator!= (const component &rhs) const
bool operator< (const component &rhs) const
component ()=default
component (const itype_id &TYPE, int COUNT)
component (const itype_id &TYPE, int COUNT, bool RECOVERABLE)
void check_consistency (const std::string &display_name) const
Public Attributes
bool subtype_expanded = false
Public Attributes inherited from component
itype_id type = itype_id::NULL_ID()
int count = 0
available_status available = available_status::a_false
bool recoverable = true
bool requirement = false
Detailed Description
Definition at line 90 of file requirements.h.
Constructor & Destructor Documentation
tool_comp() [1/2]
tool_comp::tool_comp () default
tool_comp() [2/2]
tool_comp::tool_comp (const itype_id & TYPE, int COUNT, bool subtype_expanded = false) inline
Definition at line 92 of file requirements.h.
        : component( TYPE, COUNT )
        , subtype_expanded( subtype_expanded )
    { }
Member Function Documentation
by_charges()
bool tool_comp::by_charges () const
Definition at line 129 of file requirements.cpp.
{
    return count > 0;
}
References component::count.
Referenced by requirement_data::check_enough_materials(), has(), and to_string().
dump()
void tool_comp::dump (JsonOut & jsout) const
Definition at line 227 of file requirements.cpp.
{
    jsout.start_array();
    jsout.write( type );
    jsout.write( count );
    if( requirement ) {
        jsout.write( "LIST" );
    }
    jsout.end_array();
}
References component::count, JsonOut::end_array(), component::requirement, JsonOut::start_array(), component::type, and JsonOut::write().
get_color()
nc_color tool_comp::get_color (bool has_one, const inventory & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1) const
Definition at line 801 of file requirements.cpp.
{
    if( available == available_status::a_insufficent ) {
        return c_brown;
    } else if( has( crafting_inv, filter, batch ) ) {
        return c_green;
    }
    return has_one ? c_dark_gray : c_red;
}
References a_insufficent, component::available, c_brown, c_dark_gray, c_green, c_red, and has().
get_component_type()
component_type tool_comp::get_component_type () const inline
Definition at line 111 of file requirements.h.
{
        return component_type::TOOL;
    }
References TOOL.
has()
bool tool_comp::has (const inventory & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, cost_adjustment flags = cost_adjustment::none, std::function< void(int)> visitor = std::function<void(int)>()) const
Definition at line 778 of file requirements.cpp.
{
    if( g->u.has_trait( trait_DEBUG_HS ) ) {
        return true;
    }
    if( !by_charges() ) {
        return crafting_inv.has_tools( type, std::abs( count ), filter );
    } else {
        int charges_required = count * batch;
        if( flags == cost_adjustment::start_only ) {
            charges_required = crafting::charges_for_starting( charges_required );
        } else if( flags == cost_adjustment::continue_only ) {
            charges_required = crafting::charges_for_continuing( charges_required );
        }
        int charges_found = crafting_inv.charges_of( type, charges_required, filter, visitor );
        return charges_found == charges_required;
    }
}
References by_charges(), crafting::charges_for_continuing(), crafting::charges_for_starting(), visitable< T >::charges_of(), continue_only, component::count, g, inventory::has_tools(), start_only, trait_DEBUG_HS, and component::type.
Referenced by requirement_data::check_enough_materials(), and get_color().
load()
void tool_comp::load (const JsonValue & value)
Definition at line 209 of file requirements.cpp.
{
    if( value.test_string() ) {
        // constructions uses this format: [ "tool", ... ]
        value.read( type, true );
        count = -1;
    } else {
        JsonArray comp = value.get_array();
        comp.read( 0, type, true );
        count = comp.get_int( 1 );
        requirement = comp.size() > 2 && comp.get_string( 2 ) == "LIST";
    }
    if( count == 0 ) {
        value.throw_error( "tool count must not be 0" );
    }
    // Note: negative count means charges (of the tool) should be consumed
}
References component::count, JsonValue::get_array(), JsonArray::get_int(), JsonArray::get_string(), JsonArray::read(), JsonValue::read(), component::requirement, JsonArray::size(), JsonValue::test_string(), JsonValue::throw_error(), and component::type.
to_string()
std::string tool_comp::to_string (int batch = 1, int avail = 0) const
Definition at line 134 of file requirements.cpp.
{
    if( by_charges() ) {
        //~ %1$s: tool name, %2$d: charge requirement
        return string_format( vpgettext( "requirement", "%1$s (%2$d charge)", "%1$s (%2$d charges)",
                                         count * batch ),
                              item::nname( type ), count * batch );
    } else {
        return item::nname( type, std::abs( count ) );
    }
}
References by_charges(), component::count, item::nname(), string_format(), component::type, and vpgettext().
Member Data Documentation
subtype_expanded
bool tool_comp::subtype_expanded = false
Definition at line 100 of file requirements.h.
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp