Cataclysm BN: mission_start Struct Reference
mission_start Struct Reference
#include <mission.h>
Static Public Member Functions
static void standard (mission *)
static void place_dog (mission *)
static void place_zombie_mom (mission *)
static void kill_horde_master (mission *)
static void place_npc_software (mission *)
static void place_priest_diary (mission *)
static void place_deposit_box (mission *)
static void find_safety (mission *)
static void ranch_nurse_1 (mission *)
static void ranch_nurse_2 (mission *)
static void ranch_nurse_3 (mission *)
static void ranch_nurse_4 (mission *)
static void ranch_nurse_5 (mission *)
static void ranch_nurse_6 (mission *)
static void ranch_nurse_7 (mission *)
static void ranch_nurse_8 (mission *)
static void ranch_nurse_9 (mission *)
static void ranch_scavenger_1 (mission *)
static void ranch_scavenger_2 (mission *)
static void ranch_scavenger_3 (mission *)
static void place_book (mission *)
static void reveal_refugee_center (mission *)
static void create_lab_console (mission *)
static void create_hidden_lab_console (mission *)
static void create_ice_lab_console (mission *)
static void reveal_lab_train_depot (mission *)
Detailed Description
Definition at line 97 of file mission.h.
Member Function Documentation
create_hidden_lab_console()
void mission_start::create_hidden_lab_console (mission * miss) static
Definition at line 689 of file mission_start.cpp.
{
    Character &player_character = get_player_character();
    // Pick a hidden lab entrance.
    tripoint_abs_omt loc = player_character.global_omt_location();
    loc.z() = -1;
    tripoint_abs_omt place =
        mission_util::target_om_ter_random( "basement_hidden_lab_stairs", -1, miss, false, 0, loc );
    place.z() = -2;  // then go down 1 z-level to place consoles.
    create_lab_consoles( miss, place, "lab", 3, translate_marker( "Workstation" ),
                         translate_marker( "Download Encryption Routines" ) );
    // Target the lab entrance.
    const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
    mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
}
References create_lab_consoles(), get_player_character(), Character::global_omt_location(), overmap_buffer, mission_util::reveal_road(), mission_util::target_closest_lab_entrance(), mission_util::target_om_ter_random(), translate_marker, and coords::coord_point< Point, Origin, Scale >::z().
create_ice_lab_console()
void mission_start::create_ice_lab_console (mission * miss) static
Definition at line 707 of file mission_start.cpp.
{
    Character &player_character = get_player_character();
    // Pick an ice lab with spaces on z = -4.
    tripoint_abs_omt loc = player_character.global_omt_location();
    loc.z() = -4;
    const tripoint_abs_omt place = overmap_buffer.find_closest( loc, "ice_lab", 0, false );
    create_lab_consoles( miss, place, "ice_lab", 3, translate_marker( "Durable Storage Archive" ),
                         translate_marker( "Download Archives" ) );
    // Target the lab entrance.
    const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
    mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
}
References create_lab_consoles(), overmapbuffer::find_closest(), get_player_character(), Character::global_omt_location(), overmap_buffer, mission_util::reveal_road(), mission_util::target_closest_lab_entrance(), translate_marker, and coords::coord_point< Point, Origin, Scale >::z().
create_lab_console()
void mission_start::create_lab_console (mission * miss) static
Definition at line 673 of file mission_start.cpp.
{
    Character &player_character = get_player_character();
    // Pick a lab that has spaces on z = -1: e.g., in hidden labs.
    tripoint_abs_omt loc = player_character.global_omt_location();
    loc.z() = -1;
    const tripoint_abs_omt place = overmap_buffer.find_closest( loc, "lab", 0, false );
    create_lab_consoles( miss, place, "lab", 2, translate_marker( "Workstation" ),
                         translate_marker( "Download Memory Contents" ) );
    // Target the lab entrance.
    const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
    mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
}
References create_lab_consoles(), overmapbuffer::find_closest(), get_player_character(), Character::global_omt_location(), overmap_buffer, mission_util::reveal_road(), mission_util::target_closest_lab_entrance(), translate_marker, and coords::coord_point< Point, Origin, Scale >::z().
find_safety()
void mission_start::find_safety (mission * miss) static
Definition at line 302 of file mission_start.cpp.
{
    const tripoint_abs_omt place = get_player_character().global_omt_location();
    for( int radius = 0; radius <= 20; radius++ ) {
        for( int dist = 0 - radius; dist <= radius; dist++ ) {
            int offset = rng( 0, 3 ); // Randomizes the direction we check first
            for( int i = 0; i <= 3; i++ ) { // Which direction?
                tripoint_abs_omt check = place;
                switch( ( offset + i ) % 4 ) {
                    case 0:
                        check.x() += dist;
                        check.y() -= radius;
                        break;
                    case 1:
                        check.x() += dist;
                        check.y() += radius;
                        break;
                    case 2:
                        check.y() += dist;
                        check.x() -= radius;
                        break;
                    case 3:
                        check.y() += dist;
                        check.x() += radius;
                        break;
                }
                if( overmap_buffer.is_safe( check ) ) {
                    miss->target = check;
                    return;
                }
            }
        }
    }
    // Couldn't find safety; so just set the target to far away
    switch( rng( 0, 3 ) ) {
        case 0:
            miss->target = place + point( -20, -20 );
            break;
        case 1:
            miss->target = place + point( -20, 20 );
            break;
        case 2:
            miss->target = place + point( 20, -20 );
            break;
        case 3:
            miss->target = place + point( 20, 20 );
            break;
    }
}
References detail::check(), get_player_character(), Character::global_omt_location(), overmapbuffer::is_safe(), overmap_buffer, rng(), and mission::target.
kill_horde_master()
void mission_start::kill_horde_master (mission * miss) static
Definition at line 88 of file mission_start.cpp.
{
    npc *p = g->find_npc( miss->npc_id );
    if( p == nullptr ) {
        debugmsg( "could not find mission NPC %d", miss->npc_id.get_value() );
        return;
    }
    // Npc joins you
    p->set_attitude( NPCATT_FOLLOW );
    // Pick one of the below locations for the horde to haunt
    const tripoint_abs_omt center = p->global_omt_location();
    tripoint_abs_omt site = overmap_buffer.find_closest( center, "office_tower_1", 0, false );
    if( site == overmap::invalid_tripoint ) {
        site = overmap_buffer.find_closest( center, "hotel_tower_1_8", 0, false );
    }
    if( site == overmap::invalid_tripoint ) {
        site = overmap_buffer.find_closest( center, "school_5", 0, false );
    }
    if( site == overmap::invalid_tripoint ) {
        site = overmap_buffer.find_closest( center, "forest_thick", 0, false );
    }
    miss->target = site;
    overmap_buffer.reveal( site, 6 );
    tinymap tile;
    tile.load( project_to<coords::sm>( site ), false );
    tile.add_spawn( mon_zombie_master, 1, { SEEX, SEEY, site.z() }, false, -1, miss->uid,
                    _( "Demonic Soul" ) );
    tile.add_spawn( mon_zombie_brute, 3, { SEEX, SEEY, site.z() } );
    tile.add_spawn( mon_zombie_dog, 3, { SEEX, SEEY, site.z() } );
    for( int x = SEEX - 1; x <= SEEX + 1; x++ ) {
        for( int y = SEEY - 1; y <= SEEY + 1; y++ ) {
            tile.add_spawn( mon_zombie, rng( 3, 10 ), { x, y, site.z() } );
        }
        tile.add_spawn( mon_zombie_dog, rng( 0, 2 ), { SEEX, SEEY, site.z() } );
    }
    tile.add_spawn( mon_zombie_necro, 2, { SEEX, SEEY, site.z() } );
    tile.add_spawn( mon_zombie_hulk, 1, { SEEX, SEEY, site.z() } );
    tile.save();
}
References _, map::add_spawn(), center, debugmsg, overmapbuffer::find_closest(), g, character_id::get_value(), Character::global_omt_location(), overmap::invalid_tripoint, map::load(), mon_zombie, mon_zombie_brute, mon_zombie_dog, mon_zombie_hulk, mon_zombie_master, mon_zombie_necro, mission::npc_id, NPCATT_FOLLOW, overmap_buffer, overmapbuffer::reveal(), rng(), map::save(), SEEX, SEEY, npc::set_attitude(), mission::target, mission::uid, and coords::coord_point< Point, Origin, Scale >::z().
place_book()
void mission_start::place_book (mission *) static
Definition at line 610 of file mission_start.cpp.
{
}
place_deposit_box()
void mission_start::place_deposit_box (mission * miss) static
Definition at line 260 of file mission_start.cpp.
{
    npc *p = g->find_npc( miss->npc_id );
    if( p == nullptr ) {
        debugmsg( "could not find mission NPC %d", miss->npc_id.get_value() );
        return;
    }
    // Npc joins you
    p->set_attitude( NPCATT_FOLLOW );
    tripoint_abs_omt site =
        overmap_buffer.find_closest( p->global_omt_location(), "bank", 0, false );
    if( site == overmap::invalid_tripoint ) {
        site = overmap_buffer.find_closest( p->global_omt_location(), "office_tower_1", 0, false );
    }
    if( site == overmap::invalid_tripoint ) {
        site = p->global_omt_location();
        debugmsg( "Couldn't find a place for deposit box" );
    }
    miss->target = site;
    overmap_buffer.reveal( site, 2 );
    tinymap compmap;
    compmap.load( project_to<coords::sm>( site ), false );
    std::vector<tripoint> valid;
    for( const tripoint &p : compmap.points_on_zlevel() ) {
        if( compmap.ter( p ) == t_floor ) {
            for( const tripoint &p2 : compmap.points_in_radius( p, 1 ) ) {
                if( compmap.ter( p2 ) == t_wall_metal ) {
                    valid.push_back( p );
                    break;
                }
            }
        }
    }
    const tripoint fallback( rng( 6, SEEX * 2 - 7 ), rng( 6, SEEY * 2 - 7 ), site.z() );
    const tripoint comppoint = random_entry( valid, fallback );
    compmap.spawn_item( comppoint, "safe_box" );
    compmap.save();
}
References debugmsg, overmapbuffer::find_closest(), g, character_id::get_value(), Character::global_omt_location(), overmap::invalid_tripoint, map::load(), mission::npc_id, NPCATT_FOLLOW, overmap_buffer, map::points_in_radius(), map::points_on_zlevel(), random_entry(), overmapbuffer::reveal(), rng(), map::save(), SEEX, SEEY, npc::set_attitude(), map::spawn_item(), t_floor, t_wall_metal, mission::target, map::ter(), and coords::coord_point< Point, Origin, Scale >::z().
place_dog()
void mission_start::place_dog (mission * miss) static
Definition at line 54 of file mission_start.cpp.
{
    const tripoint_abs_omt house = mission_util::random_house_in_closest_city();
    npc *dev = g->find_npc( miss->npc_id );
    if( dev == nullptr ) {
        debugmsg( "Couldn't find NPC!  %d", miss->npc_id.get_value() );
        return;
    }
    g->u.i_add( item( "dog_whistle", calendar::start_of_cataclysm ) );
    add_msg( _( "%s gave you a dog whistle." ), dev->name );
    miss->target = house;
    overmap_buffer.reveal( house, 6 );
    tinymap doghouse;
    doghouse.load( project_to<coords::sm>( house ), false );
    doghouse.add_spawn( mon_dog, 1, { SEEX, SEEY, house.z() }, true, -1, miss->uid );
    doghouse.save();
}
References _, add_msg(), map::add_spawn(), debugmsg, g, character_id::get_value(), map::load(), mon_dog, Character::name, mission::npc_id, overmap_buffer, mission_util::random_house_in_closest_city(), overmapbuffer::reveal(), map::save(), SEEX, SEEY, calendar::start_of_cataclysm, mission::target, mission::uid, and coords::coord_point< Point, Origin, Scale >::z().
place_npc_software()
void mission_start::place_npc_software (mission * miss) static
Definition at line 188 of file mission_start.cpp.
{
    npc *dev = g->find_npc( miss->npc_id );
    if( dev == nullptr ) {
        debugmsg( "Couldn't find NPC!  %d", miss->npc_id.get_value() );
        return;
    }
    g->u.i_add( item( "usb_drive", calendar::start_of_cataclysm ) );
    add_msg( _( "%s gave you a USB drive." ), dev->name );
    std::string type = "house";
    if( dev->myclass == NC_HACKER ) {
        miss->item_id = itype_software_hacking;
    } else if( dev->myclass == NC_DOCTOR ) {
        miss->item_id = itype_software_medical;
        type = "s_pharm";
        miss->follow_up = mission_type_id( "MISSION_GET_ZOMBIE_BLOOD_ANAL" );
    } else if( dev->myclass == NC_SCIENTIST ) {
        miss->item_id = itype_software_math;
    } else {
        miss->item_id = itype_software_useless;
    }
    tripoint_abs_omt place;
    if( type == "house" ) {
        place = mission_util::random_house_in_closest_city();
    } else {
        place = overmap_buffer.find_closest( dev->global_omt_location(), type, 0, false );
    }
    miss->target = place;
    overmap_buffer.reveal( place, 6 );
    tinymap compmap;
    compmap.load( project_to<coords::sm>( place ), false );
    tripoint comppoint;
    oter_id oter = overmap_buffer.ter( place );
    if( is_ot_match( "house", oter, ot_match_type::prefix ) ||
        is_ot_match( "s_pharm", oter, ot_match_type::type ) || oter == "" ) {
        comppoint = find_potential_computer_point( compmap );
    }
    compmap.ter_set( comppoint, t_console );
    computer *tmpcomp = compmap.add_computer( comppoint, string_format( _( "%s's Terminal" ),
                        dev->name ), 0 );
    tmpcomp->set_mission( miss->get_id() );
    tmpcomp->add_option( _( "Download Software" ), COMPACT_DOWNLOAD_SOFTWARE, 0 );
    compmap.save();
}
References _, map::add_computer(), add_msg(), computer::add_option(), COMPACT_DOWNLOAD_SOFTWARE, debugmsg, overmapbuffer::find_closest(), find_potential_computer_point(), mission::follow_up, g, mission::get_id(), character_id::get_value(), Character::global_omt_location(), is_ot_match(), mission::item_id, itype_software_hacking, itype_software_math, itype_software_medical, itype_software_useless, map::load(), npc::myclass, Character::name, NC_DOCTOR, NC_HACKER, NC_SCIENTIST, mission::npc_id, overmap_buffer, prefix, mission_util::random_house_in_closest_city(), overmapbuffer::reveal(), map::save(), computer::set_mission(), calendar::start_of_cataclysm, string_format(), t_console, mission::target, overmapbuffer::ter(), map::ter_set(), and type.
place_priest_diary()
void mission_start::place_priest_diary (mission * miss) static
Definition at line 239 of file mission_start.cpp.
{
    const tripoint_abs_omt place = mission_util::random_house_in_closest_city();
    miss->target = place;
    overmap_buffer.reveal( place, 2 );
    tinymap compmap;
    compmap.load( project_to<coords::sm>( place ), false );
    std::vector<tripoint> valid;
    for( const tripoint &p : compmap.points_on_zlevel() ) {
        if( compmap.furn( p ) == f_bed || compmap.furn( p ) == f_dresser ||
            compmap.furn( p ) == f_indoor_plant || compmap.furn( p ) == f_cupboard ) {
            valid.push_back( p );
        }
    }
    const tripoint fallback( rng( 6, SEEX * 2 - 7 ), rng( 6, SEEY * 2 - 7 ), place.z() );
    const tripoint comppoint = random_entry( valid, fallback );
    compmap.spawn_item( comppoint, "priest_diary" );
    compmap.save();
}
References f_bed, f_cupboard, f_dresser, f_indoor_plant, map::furn(), map::load(), overmap_buffer, map::points_on_zlevel(), random_entry(), mission_util::random_house_in_closest_city(), overmapbuffer::reveal(), rng(), map::save(), SEEX, SEEY, map::spawn_item(), mission::target, and coords::coord_point< Point, Origin, Scale >::z().
place_zombie_mom()
void mission_start::place_zombie_mom (mission * miss) static
Definition at line 74 of file mission_start.cpp.
{
    const tripoint_abs_omt house = mission_util::random_house_in_closest_city();
    miss->target = house;
    overmap_buffer.reveal( house, 6 );
    tinymap zomhouse;
    zomhouse.load( project_to<coords::sm>( house ), false );
    zomhouse.add_spawn( mon_zombie, 1, { SEEX, SEEY, house.z() }, false, -1, miss->uid,
                        Name::get( nameIsFemaleName | nameIsGivenName ) );
    zomhouse.save();
}
References map::add_spawn(), Name::get(), map::load(), mon_zombie, nameIsFemaleName, nameIsGivenName, overmap_buffer, mission_util::random_house_in_closest_city(), overmapbuffer::reveal(), map::save(), SEEX, SEEY, mission::target, mission::uid, and coords::coord_point< Point, Origin, Scale >::z().
ranch_nurse_1()
void mission_start::ranch_nurse_1 (mission * miss) static
Definition at line 354 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_furn( f_rack, point( 16, 9 ), point( 17, 9 ) );
    bay.spawn_item( point( 16, 9 ), "bandages", rng( 1, 3 ) );
    bay.spawn_item( point( 17, 9 ), "aspirin", rng( 1, 2 ) );
    bay.save();
}
References map::draw_square_furn(), f_rack, map::load(), RANCH_SIZE, rng(), map::save(), map::spawn_item(), and mission_util::target_om_ter_random().
ranch_nurse_2()
void mission_start::ranch_nurse_2 (mission * miss) static
Definition at line 367 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_furn( f_counter, point( 3, 7 ), point( 5, 7 ) );
    bay.draw_square_furn( f_rack, point( 8, 4 ), point( 8, 5 ) );
    bay.spawn_item( point( 8, 4 ), "manual_first_aid" );
    bay.save();
}
References map::draw_square_furn(), f_counter, f_rack, map::load(), RANCH_SIZE, map::save(), map::spawn_item(), and mission_util::target_om_ter_random().
ranch_nurse_3()
void mission_start::ranch_nurse_3 (mission * miss) static
Definition at line 380 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_ter( t_dirt, point( 2, 16 ), point( 9, 23 ) );
    bay.draw_square_ter( t_dirt, point( 13, 16 ), point( 20, 23 ) );
    bay.draw_square_ter( t_dirt, point( 10, 17 ), point( 12, 23 ) );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_ter( t_dirt, point( 2, 0 ), point( 20, 2 ) );
    bay.draw_square_ter( t_dirt, point( 10, 3 ), point( 12, 4 ) );
    bay.save();
}
References map::draw_square_ter(), map::load(), RANCH_SIZE, map::save(), t_dirt, and mission_util::target_om_ter_random().
ranch_nurse_4()
void mission_start::ranch_nurse_4 (mission * miss) static
Definition at line 399 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_ter( t_wall_half, point( 2, 16 ), point( 9, 23 ) );
    bay.draw_square_ter( t_dirt, point( 3, 17 ), point( 8, 22 ) );
    bay.draw_square_ter( t_wall_half, point( 13, 16 ), point( 20, 23 ) );
    bay.draw_square_ter( t_dirt, point( 14, 17 ), point( 19, 22 ) );
    bay.draw_square_ter( t_wall_half, point( 10, 17 ), point( 12, 23 ) );
    bay.draw_square_ter( t_dirt, point( 10, 18 ), point( 12, 23 ) );
    bay.ter_set( point( 9, 19 ), t_door_frame );
    bay.ter_set( point( 13, 19 ), t_door_frame );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_ter( t_wall_half, point( 4, 0 ), point( 18, 2 ) );
    bay.draw_square_ter( t_wall_half, point( 10, 3 ), point( 12, 4 ) );
    bay.draw_square_ter( t_dirt, point( 5, 0 ), point( 8, 2 ) );
    bay.draw_square_ter( t_dirt, point( 10, 0 ), point( 12, 4 ) );
    bay.draw_square_ter( t_dirt, point( 14, 0 ), point( 17, 2 ) );
    bay.ter_set( point( 9, 1 ), t_door_frame );
    bay.ter_set( point( 13, 1 ), t_door_frame );
    bay.save();
}
References map::draw_square_ter(), map::load(), RANCH_SIZE, map::save(), t_dirt, t_door_frame, t_wall_half, mission_util::target_om_ter_random(), and map::ter_set().
ranch_nurse_5()
void mission_start::ranch_nurse_5 (mission * miss) static
Definition at line 428 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_wall_half, t_wall_wood );
    bay.ter_set( point( 2, 21 ), t_window_frame );
    bay.ter_set( point( 2, 18 ), t_window_frame );
    bay.ter_set( point( 20, 18 ), t_window_frame );
    bay.ter_set( point( 20, 21 ), t_window_frame );
    bay.ter_set( point( 11, 17 ), t_window_frame );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_wall_half, t_wall_wood );
    bay.draw_square_ter( t_dirt, point( 10, 0 ), point( 12, 4 ) );
    bay.save();
}
References map::draw_square_ter(), map::load(), RANCH_SIZE, map::save(), t_dirt, t_wall_half, t_wall_wood, t_window_frame, mission_util::target_om_ter_random(), map::ter_set(), and map::translate().
ranch_nurse_6()
void mission_start::ranch_nurse_6 (mission * miss) static
Definition at line 450 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_window_frame, t_window_boarded_noglass );
    bay.translate( t_door_frame, t_door_c );
    bay.draw_square_ter( t_dirtfloor, point( 3, 17 ), point( 8, 22 ) );
    bay.draw_square_ter( t_dirtfloor, point( 14, 17 ), point( 19, 22 ) );
    bay.draw_square_ter( t_dirtfloor, point( 10, 18 ), point( 12, 23 ) );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_door_frame, t_door_c );
    bay.draw_square_ter( t_dirtfloor, point( 5, 0 ), point( 8, 2 ) );
    bay.draw_square_ter( t_dirtfloor, point( 10, 0 ), point( 12, 4 ) );
    bay.draw_square_ter( t_dirtfloor, point( 14, 0 ), point( 17, 2 ) );
    bay.save();
}
References map::draw_square_ter(), map::load(), RANCH_SIZE, map::save(), t_dirtfloor, t_door_c, t_door_frame, t_window_boarded_noglass, t_window_frame, mission_util::target_om_ter_random(), and map::translate().
ranch_nurse_7()
void mission_start::ranch_nurse_7 (mission * miss) static
Definition at line 473 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_dirtfloor, t_floor );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_dirtfloor, t_floor );
    bay.draw_square_ter( t_floor, point( 10, 5 ), point( 12, 5 ) );
    bay.draw_square_furn( f_rack, point( 17, 0 ), point( 17, 2 ) );
    bay.save();
}
References map::draw_square_furn(), map::draw_square_ter(), f_rack, map::load(), RANCH_SIZE, map::save(), t_dirtfloor, t_floor, mission_util::target_om_ter_random(), and map::translate().
ranch_nurse_8()
void mission_start::ranch_nurse_8 (mission * miss) static
Definition at line 491 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_furn( f_makeshift_bed, point( 4, 21 ), point( 4, 22 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 7, 21 ), point( 7, 22 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 15, 21 ), point( 15, 22 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 18, 21 ), point( 18, 22 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 4, 17 ), point( 4, 18 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 7, 17 ), point( 7, 18 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 15, 17 ), point( 15, 18 ) );
    bay.draw_square_furn( f_makeshift_bed, point( 18, 17 ), point( 18, 18 ) );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_dirtfloor, t_floor );
    bay.place_items( item_group_id( "cleaning" ), 75, point( 17, 0 ), point( 17, 2 ), true,
                     calendar::start_of_cataclysm );
    bay.place_items( item_group_id( "surgery" ), 75, point( 15, 4 ), point( 18, 4 ), true,
                     calendar::start_of_cataclysm );
    bay.save();
}
References map::draw_square_furn(), f_makeshift_bed, map::load(), map::place_items(), RANCH_SIZE, map::save(), calendar::start_of_cataclysm, t_dirtfloor, t_floor, mission_util::target_om_ter_random(), and map::translate().
ranch_nurse_9()
void mission_start::ranch_nurse_9 (mission * miss) static
Definition at line 518 of file mission_start.cpp.
{
    //Improvements to clinic...
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_50", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.furn_set( point( 3, 22 ), f_dresser );
    bay.furn_set( point( 8, 22 ), f_dresser );
    bay.furn_set( point( 14, 22 ), f_dresser );
    bay.furn_set( point( 19, 22 ), f_dresser );
    bay.furn_set( point( 3, 17 ), f_dresser );
    bay.furn_set( point( 8, 17 ), f_dresser );
    bay.furn_set( point( 14, 17 ), f_dresser );
    bay.furn_set( point( 19, 17 ), f_dresser );
    bay.place_npc( point( 16, 19 ), string_id<npc_template>( "ranch_doctor" ) );
    bay.save();
    mission_util::target_om_ter_random( "ranch_camp_59", 1, miss, false, RANCH_SIZE );
}
References f_dresser, map::furn_set(), map::load(), map::place_npc(), RANCH_SIZE, map::save(), and mission_util::target_om_ter_random().
ranch_scavenger_1()
void mission_start::ranch_scavenger_1 (mission * miss) static
Definition at line 539 of file mission_start.cpp.
{
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_48", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.draw_square_ter( t_chainfence, point( 15, 13 ), point( 15, 22 ) );
    bay.draw_square_ter( t_chainfence, point( 16, 13 ), point( 23, 13 ) );
    bay.draw_square_ter( t_chainfence, point( 16, 22 ), point( 23, 22 ) );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_49", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.place_items( item_group_id( "mechanics" ), 65, point( 9, 13 ), point( 10, 16 ), true,
                     calendar::start_of_cataclysm );
    bay.draw_square_ter( t_chainfence, point( 0, 22 ), point( 7, 22 ) );
    bay.draw_square_ter( t_dirt, point( 2, 22 ), point( 3, 22 ) );
    bay.spawn_item( point( 7, 19 ), "30gal_drum" );
    bay.save();
}
References map::draw_square_ter(), map::load(), map::place_items(), RANCH_SIZE, map::save(), map::spawn_item(), calendar::start_of_cataclysm, t_chainfence, t_dirt, and mission_util::target_om_ter_random().
ranch_scavenger_2()
void mission_start::ranch_scavenger_2 (mission * miss) static
Definition at line 560 of file mission_start.cpp.
{
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_48", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.add_vehicle( vproto_id( "car_chassis" ), point( 20, 15 ), 0_degrees );
    bay.draw_square_ter( t_wall_half, point( 18, 19 ), point( 21, 22 ) );
    bay.draw_square_ter( t_dirt, point( 19, 20 ), point( 20, 21 ) );
    bay.ter_set( point( 19, 19 ), t_door_frame );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_49", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.place_items( item_group_id( "mischw" ), 65, point( 12, 13 ), point( 13, 16 ), true,
                     calendar::start_of_cataclysm );
    bay.draw_square_ter( t_chaingate_l, point( 2, 22 ), point( 3, 22 ) );
    bay.spawn_item( point( 7, 20 ), "30gal_drum" );
    bay.save();
}
References map::add_vehicle(), map::draw_square_ter(), map::load(), map::place_items(), RANCH_SIZE, map::save(), map::spawn_item(), calendar::start_of_cataclysm, t_chaingate_l, t_dirt, t_door_frame, t_wall_half, mission_util::target_om_ter_random(), and map::ter_set().
ranch_scavenger_3()
void mission_start::ranch_scavenger_3 (mission * miss) static
Definition at line 581 of file mission_start.cpp.
{
    tripoint_abs_omt site = mission_util::target_om_ter_random(
                                "ranch_camp_48", 1, miss, false, RANCH_SIZE );
    tinymap bay;
    bay.load( project_to<coords::sm>( site ), false );
    bay.translate( t_door_frame, t_door_locked );
    bay.translate( t_wall_half, t_wall_wood );
    bay.draw_square_ter( t_dirtfloor, point( 19, 20 ), point( 20, 21 ) );
    bay.spawn_item( point( 16, 21 ), "wheel_wide" );
    bay.spawn_item( point( 17, 21 ), "wheel_wide" );
    bay.spawn_item( point( 23, 18 ), "v8_combustion" );
    bay.furn_set( point( 23, 17 ), furn_str_id( "f_arcade_machine" ) );
    bay.ter_set( point( 23, 16 ), ter_str_id( "t_machinery_light" ) );
    bay.furn_set( point( 20, 21 ), f_woodstove );
    bay.save();
    site = mission_util::target_om_ter_random( "ranch_camp_49", 1, miss, false, RANCH_SIZE );
    bay.load( project_to<coords::sm>( site ), false );
    bay.place_items( item_group_id( "mischw" ), 65, point( 2, 10 ), point( 4, 10 ), true,
                     calendar::start_of_cataclysm );
    bay.place_items( item_group_id( "mischw" ), 65, point( 2, 13 ), point( 4, 13 ), true,
                     calendar::start_of_cataclysm );
    bay.furn_set( point( 1, 15 ), f_fridge );
    bay.spawn_item( point( 2, 15 ), "hdframe" );
    bay.furn_set( point( 3, 15 ), f_washer );
    bay.save();
}
References map::draw_square_ter(), f_fridge, f_washer, f_woodstove, map::furn_set(), map::load(), map::place_items(), RANCH_SIZE, map::save(), map::spawn_item(), calendar::start_of_cataclysm, t_dirtfloor, t_door_frame, t_door_locked, t_wall_half, t_wall_wood, mission_util::target_om_ter_random(), map::ter_set(), and map::translate().
reveal_lab_train_depot()
void mission_start::reveal_lab_train_depot (mission * miss) static
Definition at line 723 of file mission_start.cpp.
{
    Character &player_character = get_player_character();
    // Find and prepare lab location.
    tripoint_abs_omt loc = player_character.global_omt_location();
    loc.z() = -4;  // tunnels are at z = -4
    const tripoint_abs_omt place = overmap_buffer.find_closest( loc, "lab_train_depot", 0, false );
    tinymap compmap;
    compmap.load( project_to<coords::sm>( place ), false );
    cata::optional<tripoint> comppoint;
    for( const tripoint &point : compmap.points_on_zlevel() ) {
        if( compmap.ter( point ) == t_console ) {
            comppoint = point;
            break;
        }
    }
    if( !comppoint ) {
        debugmsg( "Could not find a computer in the lab train depot, mission will fail." );
        return;
    }
    computer *tmpcomp = compmap.computer_at( *comppoint );
    tmpcomp->set_mission( miss->get_id() );
    tmpcomp->add_option( _( "Download Routing Software" ), COMPACT_DOWNLOAD_SOFTWARE, 0 );
    compmap.save();
    // Target the lab entrance.
    const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
    mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
}
References _, computer::add_option(), COMPACT_DOWNLOAD_SOFTWARE, map::computer_at(), debugmsg, overmapbuffer::find_closest(), mission::get_id(), get_player_character(), Character::global_omt_location(), map::load(), overmap_buffer, map::points_on_zlevel(), mission_util::reveal_road(), map::save(), computer::set_mission(), t_console, mission_util::target_closest_lab_entrance(), map::ter(), and coords::coord_point< Point, Origin, Scale >::z().
reveal_refugee_center()
void mission_start::reveal_refugee_center (mission * miss) static
Definition at line 614 of file mission_start.cpp.
{
    mission_target_params t;
    t.overmap_terrain = "refctr_S3e";
    t.overmap_special = overmap_special_id( "evac_center" );
    t.mission_pointer = miss;
    t.search_range = 0;
    t.reveal_radius = 3;
    const cata::optional<tripoint_abs_omt> target_pos = mission_util::assign_mission_target( t );
    if( !target_pos ) {
        add_msg( _( "You don't know where the address could be" ) );
        return;
    }
    const tripoint_abs_omt source_road = overmap_buffer.find_closest(
            get_player_character().global_omt_location(), "road",
            3, false );
    const tripoint_abs_omt dest_road = overmap_buffer.find_closest( *target_pos, "road", 3, false );
    omt_route_params params;
    params.radius = 1;
    params.road_only = true;
    params.popup = make_shared_fast<throbber_popup>( _( "Please wait" ) );
    if( overmap_buffer.reveal_route( source_road, dest_road, params ) ) {
        add_msg( _( "You mark the refugee center and the road that leads to it" ) );
    } else {
        add_msg( _( "You mark the refugee center, but you have no idea how to get there by road" ) );
    }
}
References _, add_msg(), mission_util::assign_mission_target(), overmapbuffer::find_closest(), get_player_character(), mission_target_params::mission_pointer, overmap_buffer, mission_target_params::overmap_special, mission_target_params::overmap_terrain, omt_route_params::popup, omt_route_params::radius, mission_target_params::reveal_radius, overmapbuffer::reveal_route(), omt_route_params::road_only, and mission_target_params::search_range.
standard()
void mission_start::standard (mission *) static
Definition at line 50 of file mission_start.cpp.
{
}
The documentation for this struct was generated from the following files:
src/mission.h
src/mission_start.cpp