Cataclysm BN: jmapgen_objects Struct Reference
jmapgen_objects Struct Reference
#include <mapgen.h>
Public Member Functions
jmapgen_objects (const point &offset, const point &mapsize, const point &tot_size)
bool check_bounds (const jmapgen_place &place, const JsonObject &jso)
void add (const jmapgen_place &place, shared_ptr_fast< const jmapgen_piece > piece)
template<typename PieceType >
void load_objects (JsonArray parray)
PieceType must be inheriting from jmapgen_piece.
template<typename PieceType >
void load_objects (const JsonObject &jsi, const std::string &member_name)
Loads the mapgen objects from the array inside of jsi.
void check (const std::string &oter_name) const
void apply (mapgendata &dat) const
void apply (mapgendata &dat, const point &offset) const
bool has_vehicle_collision (mapgendata &dat, const point &offset) const
checks if applying these objects to data would cause cause a collision with vehicles on the same map
template<>
void load_objects (JsonArray parray)
Private Types
using jmapgen_obj = std::pair< jmapgen_place, shared_ptr_fast< const jmapgen_piece > >
Combination of where to place something and what to place.
Private Attributes
std::vector< jmapgen_obj > objects
point m_offset
point mapgensize
point total_size
Detailed Description
Definition at line 266 of file mapgen.h.
Member Typedef Documentation
jmapgen_obj
using jmapgen_objects::jmapgen_obj = std::pair<jmapgen_place, shared_ptr_fast<const jmapgen_piece> > private
Combination of where to place something and what to place.
Definition at line 304 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_objects()
jmapgen_objects::jmapgen_objects (const point & offset, const point & mapsize, const point & tot_size)
Definition at line 1907 of file mapgen.cpp.
    : m_offset( offset )
    , mapgensize( mapsize )
    , total_size( tot_size )
{}
Member Function Documentation
add()
void jmapgen_objects::add (const jmapgen_place & place, shared_ptr_fast< const jmapgen_piece > piece)
Definition at line 1918 of file mapgen.cpp.
{
    objects.emplace_back( place, piece );
}
References objects.
Referenced by load_objects(), and mapgen_function_json_base::setup_common().
apply() [1/2]
void jmapgen_objects::apply (mapgendata & dat) const
Definition at line 2865 of file mapgen.cpp.
{
    for( auto &obj : objects ) {
        const auto &where = obj.first;
        const auto &what = *obj.second;
        // The user will only specify repeat once in JSON, but it may get loaded both
        // into the what and where in some cases--we just need the greater value of the two.
        const int repeat = std::max( where.repeat.get(), what.repeat.get() );
        for( int i = 0; i < repeat; i++ ) {
            what.apply( dat, where.x, where.y );
        }
    }
}
References objects.
Referenced by apply(), mapgen_function_json::generate(), mapgen_function_json_nested::nest(), and update_mapgen_function_json::update_map().
apply() [2/2]
void jmapgen_objects::apply (mapgendata & dat, const point & offset) const
Definition at line 2879 of file mapgen.cpp.
{
    if( offset == point_zero ) {
        // It's a bit faster
        apply( dat );
        return;
    }
    for( auto &obj : objects ) {
        auto where = obj.first;
        where.offset( -offset );
        const auto &what = *obj.second;
        // The user will only specify repeat once in JSON, but it may get loaded both
        // into the what and where in some cases--we just need the greater value of the two.
        const int repeat = std::max( where.repeat.get(), what.repeat.get() );
        for( int i = 0; i < repeat; i++ ) {
            what.apply( dat, where.x, where.y );
        }
    }
}
References apply(), objects, and point_zero.
check()
void jmapgen_objects::check (const std::string & oter_name) const
Definition at line 2589 of file mapgen.cpp.
{
    for( const jmapgen_obj &obj : objects ) {
        obj.second->check( oter_name );
    }
}
References objects.
Referenced by mapgen_function_json_base::check_common().
check_bounds()
bool jmapgen_objects::check_bounds (const jmapgen_place & place, const JsonObject & jso)
Definition at line 1913 of file mapgen.cpp.
{
    return common_check_bounds( place.x, place.y, mapgensize, jso );
}
References common_check_bounds(), mapgensize, jmapgen_place::x, and jmapgen_place::y.
Referenced by load_objects().
has_vehicle_collision()
bool jmapgen_objects::has_vehicle_collision (mapgendata & dat, const point & offset) const
checks if applying these objects to data would cause cause a collision with vehicles on the same map
Definition at line 2901 of file mapgen.cpp.
{
    for( auto &obj : objects ) {
        auto where = obj.first;
        where.offset( -offset );
        const auto &what = *obj.second;
        if( what.has_vehicle_collision( dat, point( where.x.get(), where.y.get() ) ) ) {
            return true;
        }
    }
    return false;
}
References objects.
Referenced by mapgen_function_json_base::has_vehicle_collision(), and update_mapgen_function_json::update_map().
load_objects() [1/3]
template<typename PieceType > void jmapgen_objects::load_objects (const JsonObject & jsi, const std::string & member_name)
Loads the mapgen objects from the array inside of jsi.
If jsi has no member of that name, nothing is loaded and the function just returns.
Definition at line 1969 of file mapgen.cpp.
{
    if( !jsi.has_member( member_name ) ) {
        return;
    }
    load_objects<PieceType>( jsi.get_array( member_name ) );
}
References JsonObject::get_array(), JsonObject::has_member(), and mapgen_defer::jsi.
load_objects() [2/3]
template<> void jmapgen_objects::load_objects (JsonArray parray)
Definition at line 1940 of file mapgen.cpp.
{
    for( JsonObject jsi : parray ) {
        jmapgen_place where( jsi );
        where.offset( m_offset );
        if( !check_bounds( where, jsi ) ) {
            jsi.allow_omitted_members();
            continue;
        }
        auto loot = make_shared_fast<jmapgen_loot>( jsi );
        auto rate = get_option<float>( "ITEM_SPAWNRATE" );
        if( where.repeat.valmax != 1 ) {
            // if loot can repeat scale according to rate
            where.repeat.val = std::max( static_cast<int>( where.repeat.val * rate ), 1 );
            where.repeat.valmax = std::max( static_cast<int>( where.repeat.valmax * rate ), 1 );
        } else if( loot->chance != 100 ) {
            // otherwise except where chance is 100% scale probability
            loot->chance = std::max( std::min( static_cast<int>( loot->chance * rate ), 100 ), 1 );
        }
        add( where, loot );
    }
}
References add(), JsonObject::allow_omitted_members(), check_bounds(), mapgen_defer::jsi, loot(), m_offset, jmapgen_place::offset(), jmapgen_place::repeat, jmapgen_int::val, and jmapgen_int::valmax.
load_objects() [3/3]
template<typename PieceType > void jmapgen_objects::load_objects (JsonArray parray)
PieceType must be inheriting from jmapgen_piece.
It must have constructor that accepts a const JsonObject &as parameter. The function loads all objects from the json array and stores them in objects.
Definition at line 1925 of file mapgen.cpp.
{
    for( JsonObject jsi : parray ) {
        jmapgen_place where( jsi );
        where.offset( m_offset );
        if( check_bounds( where, jsi ) ) {
            add( where, make_shared_fast<PieceType>( jsi ) );
        } else {
            jsi.allow_omitted_members();
        }
    }
}
References add(), JsonObject::allow_omitted_members(), check_bounds(), mapgen_defer::jsi, m_offset, and jmapgen_place::offset().
Referenced by mapgen_function_json_base::setup_common().
Member Data Documentation
m_offset
point jmapgen_objects::m_offset private
Definition at line 306 of file mapgen.h.
Referenced by load_objects().
mapgensize
point jmapgen_objects::mapgensize private
Definition at line 307 of file mapgen.h.
Referenced by check_bounds().
objects
std::vector<jmapgen_obj> jmapgen_objects::objects private
Definition at line 305 of file mapgen.h.
Referenced by add(), apply(), check(), and has_vehicle_collision().
total_size
point jmapgen_objects::total_size private
Definition at line 308 of file mapgen.h.
The documentation for this struct was generated from the following files:
src/mapgen.h
src/mapgen.cpp