Cataclysm BN: clothing_mod Struct Reference
clothing_mod Struct Reference
#include <clothing_mod.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
float get_mod_val (const clothing_mod_type &type, const item &it) const
bool has_mod_type (const clothing_mod_type &type) const
Static Public Member Functions
static size_t count ()
Public Attributes
clothing_mod_id id
bool was_loaded = false
std::string flag
itype_id item_string
std::string implement_prompt
std::string destroy_prompt
std::vector< mod_value > mod_values
bool restricted = false
Detailed Description
Definition at line 42 of file clothing_mod.h.
Member Function Documentation
count()
size_t clothing_mod::count () static
Definition at line 129 of file clothing_mod.cpp.
{
    return all_clothing_mods.size();
}
References anonymous_namespace{clothing_mod.cpp}::all_clothing_mods.
get_mod_val()
float clothing_mod::get_mod_val (const clothing_mod_type & type, const item & it) const
Definition at line 96 of file clothing_mod.cpp.
{
    const int thickness = it.get_thickness();
    const int coverage = it.get_coverage();
    float result = 0.0f;
    for( const mod_value &mv : mod_values ) {
        if( mv.type == type ) {
            float tmp = mv.value;
            if( mv.thickness_propotion ) {
                tmp *= thickness;
            }
            if( mv.coverage_propotion ) {
                tmp *= coverage / 100.0f;
            }
            if( mv.round_up ) {
                tmp = std::ceil( tmp );
            }
            result += tmp;
        }
    }
    return result;
}
References item::get_coverage(), item::get_thickness(), mod_values, and type.
has_mod_type()
bool clothing_mod::has_mod_type (const clothing_mod_type & type) const
Definition at line 119 of file clothing_mod.cpp.
{
    for( auto &mv : mod_values ) {
        if( mv.type == type ) {
            return true;
        }
    }
    return false;
}
References mod_values, and type.
load()
void clothing_mod::load (const JsonObject & jo, const std::string & src)
Definition at line 67 of file clothing_mod.cpp.
{
    mandatory( jo, was_loaded, "flag", flag );
    mandatory( jo, was_loaded, "item", item_string );
    mandatory( jo, was_loaded, "implement_prompt", implement_prompt );
    mandatory( jo, was_loaded, "destroy_prompt", destroy_prompt );
    optional( jo, was_loaded, "restricted", restricted, false );
    for( const JsonObject mv_jo : jo.get_array( "mod_value" ) ) {
        mod_value mv;
        std::string temp_str;
        mandatory( mv_jo, was_loaded, "type", temp_str );
        mv.type = io::string_to_enum<clothing_mod_type>( temp_str );
        mandatory( mv_jo, was_loaded, "value", mv.value );
        optional( mv_jo, was_loaded, "round_up", mv.round_up );
        for( const JsonValue entry : mv_jo.get_array( "proportion" ) ) {
            const std::string &str = entry.get_string();
            if( str == "thickness" ) {
                mv.thickness_propotion = true;
            } else if( str == "coverage" ) {
                mv.coverage_propotion = true;
            } else {
                entry.throw_error( R"(Invalid value, valid are: "coverage" and "thickness")" );
            }
        }
        mod_values.push_back( mv );
    }
}
References mod_value::coverage_propotion, destroy_prompt, flag, JsonValue::get_array(), JsonObject::get_array(), implement_prompt, item_string, mandatory(), mod_values, optional(), restricted, mod_value::round_up, mod_value::thickness_propotion, mod_value::type, mod_value::value, and was_loaded.
Member Data Documentation
destroy_prompt
std::string clothing_mod::destroy_prompt
Definition at line 53 of file clothing_mod.h.
Referenced by load().
flag
std::string clothing_mod::flag
Definition at line 50 of file clothing_mod.h.
Referenced by load().
id
clothing_mod_id clothing_mod::id
Definition at line 47 of file clothing_mod.h.
implement_prompt
std::string clothing_mod::implement_prompt
Definition at line 52 of file clothing_mod.h.
Referenced by load().
item_string
itype_id clothing_mod::item_string
Definition at line 51 of file clothing_mod.h.
Referenced by load().
mod_values
std::vector< mod_value > clothing_mod::mod_values
Definition at line 54 of file clothing_mod.h.
Referenced by get_mod_val(), has_mod_type(), and load().
restricted
bool clothing_mod::restricted = false
Definition at line 55 of file clothing_mod.h.
Referenced by load().
was_loaded
bool clothing_mod::was_loaded = false
Definition at line 48 of file clothing_mod.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/clothing_mod.h
src/clothing_mod.cpp