Cataclysm BN: detail::fallback_uintptr Struct Reference
detail::fallback_uintptr Struct Reference
#include <fmtlib_format.h>
Public Member Functions
fallback_uintptr ()=default
fallback_uintptr (const void *p)
Public Attributes
unsigned char value [sizeof(void *)]
Detailed Description
Definition at line 315 of file fmtlib_format.h.
Constructor & Destructor Documentation
fallback_uintptr() [1/2]
detail::fallback_uintptr::fallback_uintptr () default
fallback_uintptr() [2/2]
detail::fallback_uintptr::fallback_uintptr (const void * p) inline explicit
Definition at line 319 of file fmtlib_format.h.
{
        *this = bit_cast<fallback_uintptr>( p );
        if( is_big_endian() ) {
            for( size_t i = 0, j = sizeof( void * ) - 1; i < j; ++i, --j ) {
                std::swap( value[i], value[j] );
            }
        }
    }
References detail::is_big_endian(), and cata::swap().
Member Data Documentation
value
unsigned char detail::fallback_uintptr::value[sizeof(void *)]
Definition at line 316 of file fmtlib_format.h.
Referenced by detail::count_digits< 4 >(), and detail::format_uint().
The documentation for this struct was generated from the following file:
src/fmtlib_format.h