Cataclysm BN: label Struct Reference
label Struct Reference
Struct used for storing labels (easier to json opposed to a std::map<point, std::string>)
#include <vehicle.h>
Public Member Functions
label ()=default
label (const point &p)
label (const point &p, std::string text)
void deserialize (JsonIn &jsin)
void serialize (JsonOut &json) const
Public Member Functions inherited from point
constexpr point ()=default
constexpr point (int X, int Y)
constexpr point operator+ (const point &rhs) const
point & operator+= (const point &rhs)
constexpr point operator- () const
constexpr point operator- (const point &rhs) const
point & operator-= (const point &rhs)
constexpr point operator* (const int rhs) const
point & operator*= (const int rhs)
constexpr point operator/ (const int rhs) const
point abs () const
point rotate (int turns, const point &dim={ 1, 1 }) const
Rotate point clockwise.
std::string to_string () const
void serialize (JsonOut &jsout) const
void deserialize (JsonIn &jsin)
Public Attributes
std::string text
Public Attributes inherited from point
int x = 0
int y = 0
Additional Inherited Members
Static Public Attributes inherited from point
static constexpr int dimension = 2
Detailed Description
Struct used for storing labels (easier to json opposed to a std::map<point, std::string>)
Definition at line 578 of file vehicle.h.
Constructor & Destructor Documentation
label() [1/3]
label::label () default
label() [2/3]
label::label (const point & p) inline explicit
Definition at line 580 of file vehicle.h.
: point(p) {}
label() [3/3]
label::label (const point & p, std::string text) inline
Definition at line 581 of file vehicle.h.
: point(p), text(std::move(text)) {}
Member Function Documentation
deserialize()
void label::deserialize (JsonIn & jsin)
Definition at line 2575 of file savegame_json.cpp.
{
    JsonObject data = jsin.get_object();
    data.allow_omitted_members();
    data.read( "x", x );
    data.read( "y", y );
    data.read( "text", text );
}
References JsonObject::allow_omitted_members(), JsonIn::get_object(), and JsonObject::read().
serialize()
void label::serialize (JsonOut & json) const
Definition at line 2584 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "x", x );
    json.member( "y", y );
    json.member( "text", text );
    json.end_object();
}
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
text
std::string label::text
Definition at line 583 of file vehicle.h.
The documentation for this struct was generated from the following files:
src/vehicle.h
src/savegame_json.cpp