Cataclysm BN: npc_favor Struct Reference
npc_favor Struct Reference
#include <npc_favor.h>
Public Member Functions
npc_favor ()
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Public Attributes
npc_favor_type type
int value
itype_id item_id
skill_id skill
Detailed Description
Definition at line 21 of file npc_favor.h.
Constructor & Destructor Documentation
npc_favor()
npc_favor::npc_favor () inline
Definition at line 27 of file npc_favor.h.
                {
        type = FAVOR_NULL;
        value = 0;
        item_id = itype_id::NULL_ID();
        skill = skill_id::NULL_ID();
    }
References FAVOR_NULL, item_id, string_id< itype >::NULL_ID(), string_id< Skill >::NULL_ID(), skill, type, and value.
Member Function Documentation
deserialize()
void npc_favor::deserialize (JsonIn & jsin)
Definition at line 1361 of file savegame_json.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.allow_omitted_members();
    type = static_cast<npc_favor_type>( jo.get_int( "type" ) );
    jo.read( "value", value );
    jo.read( "itype_id", item_id );
    if( jo.has_int( "skill_id" ) ) {
        skill = Skill::from_legacy_int( jo.get_int( "skill_id" ) );
    } else if( jo.has_string( "skill_id" ) ) {
        skill = skill_id( jo.get_string( "skill_id" ) );
    } else {
        skill = skill_id::NULL_ID();
    }
}
References JsonObject::allow_omitted_members(), Skill::from_legacy_int(), JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), JsonObject::has_int(), JsonObject::has_string(), item_id, string_id< Skill >::NULL_ID(), JsonObject::read(), skill, skill_id, type, and value.
serialize()
void npc_favor::serialize (JsonOut & json) const
Definition at line 1377 of file savegame_json.cpp.
{
    json.start_object();
    json.member( "type", static_cast<int>( type ) );
    json.member( "value", value );
    json.member( "itype_id", static_cast<std::string>( item_id ) );
    json.member( "skill_id", skill );
    json.end_object();
}
References JsonOut::end_object(), item_id, JsonOut::member(), skill, JsonOut::start_object(), type, and value.
Member Data Documentation
item_id
itype_id npc_favor::item_id
Definition at line 24 of file npc_favor.h.
Referenced by deserialize(), npc_favor(), and serialize().
skill
skill_id npc_favor::skill
Definition at line 25 of file npc_favor.h.
Referenced by deserialize(), npc_favor(), and serialize().
type
npc_favor_type npc_favor::type
Definition at line 22 of file npc_favor.h.
Referenced by deserialize(), npc_favor(), and serialize().
value
int npc_favor::value
Definition at line 23 of file npc_favor.h.
Referenced by deserialize(), npc_favor(), and serialize().
The documentation for this struct was generated from the following files:
src/npc_favor.h
src/savegame_json.cpp