Cataclysm BN: src/suffer.cpp File Reference
suffer.cpp File Reference
#include <algorithm>
#include <array>
#include <cctype>
#include <cmath>
#include <cstdlib>
#include <list>
#include <map>
#include <memory>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>
#include "addiction.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "magic_enchantment.h"
#include "map.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "name.h"
#include "npc.h"
#include "optional.h"
#include "options.h"
#include "overmapbuffer.h"
#include "pldata.h"
#include "point.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "teleport.h"
#include "text_snippets.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "weather.h"
Functions
static const std::string flag_BLIND ("BLIND")
static const std::string flag_PLOWABLE ("PLOWABLE")
static const std::string flag_RAD_RESIST ("RAD_RESIST")
static const std::string flag_SUN_GLASSES ("SUN_GLASSES")
static float addiction_scaling (float at_min, float at_max, float add_lvl)
Variables
static const bionic_id bio_advreactor ("bio_advreactor")
static const bionic_id bio_dis_acid ("bio_dis_acid")
static const bionic_id bio_dis_shock ("bio_dis_shock")
static const bionic_id bio_drain ("bio_drain")
static const bionic_id bio_geiger ("bio_geiger")
static const bionic_id bio_gills ("bio_gills")
static const bionic_id bio_glowy ("bio_glowy")
static const bionic_id bio_itchy ("bio_itchy")
static const bionic_id bio_leaky ("bio_leaky")
static const bionic_id bio_noise ("bio_noise")
static const bionic_id bio_plut_filter ("bio_plut_filter")
static const bionic_id bio_power_weakness ("bio_power_weakness")
static const bionic_id bio_reactor ("bio_reactor")
static const bionic_id bio_shakes ("bio_shakes")
static const bionic_id bio_sleepy ("bio_sleepy")
static const bionic_id bio_spasm ("bio_spasm")
static const bionic_id bio_sunglasses ("bio_sunglasses")
static const bionic_id bio_trip ("bio_trip")
static const efftype_id effect_accumulated_mutagen ("accumulated_mutagen")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_attention ("attention")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_datura ("datura")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_disabled ("disabled")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_formication ("formication")
static const efftype_id effect_glowy_led ("glowy_led")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_iodine ("iodine")
static const efftype_id effect_masked_scent ("masked_scent")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_meth ("meth")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_shakes ("shakes")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_took_antiasthmatic ("took_antiasthmatic")
static const efftype_id effect_took_thorazine ("took_thorazine")
static const efftype_id effect_valium ("valium")
static const efftype_id effect_visuals ("visuals")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const itype_id itype_inhaler ("inhaler")
static const itype_id itype_smoxygen_tank ("smoxygen_tank")
static const itype_id itype_oxygen_tank ("oxygen_tank")
static const itype_id itype_rad_badge ("rad_badge")
static const trait_id trait_ADDICTIVE ("ADDICTIVE")
static const trait_id trait_ALBINO ("ALBINO")
static const trait_id trait_ASTHMA ("ASTHMA")
static const trait_id trait_CHAOTIC ("CHAOTIC")
static const trait_id trait_CHAOTIC_BAD ("CHAOTIC_BAD")
static const trait_id trait_CHEMIMBALANCE ("CHEMIMBALANCE")
static const trait_id trait_DEBUG_NOTEMP ("DEBUG_NOTEMP")
static const trait_id trait_DEBUG_STORAGE ("DEBUG_STORAGE")
static const trait_id trait_FRESHWATEROSMOSIS ("FRESHWATEROSMOSIS")
static const trait_id trait_GILLS ("GILLS")
static const trait_id trait_GILLS_CEPH ("GILLS_CEPH")
static const trait_id trait_JITTERY ("JITTERY")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_LEAVES ("LEAVES")
static const trait_id trait_LEAVES2 ("LEAVES2")
static const trait_id trait_LEAVES3 ("LEAVES3")
static const trait_id trait_M_BLOSSOMS ("M_BLOSSOMS")
static const trait_id trait_M_SPORES ("M_SPORES")
static const trait_id trait_MOODSWINGS ("MOODSWINGS")
static const trait_id trait_NARCOLEPTIC ("NARCOLEPTIC")
static const trait_id trait_NONADDICTIVE ("NONADDICTIVE")
static const trait_id trait_NOPAIN ("NOPAIN")
static const trait_id trait_PER_SLIME ("PER_SLIME")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_RADIOACTIVE1 ("RADIOACTIVE1")
static const trait_id trait_RADIOACTIVE2 ("RADIOACTIVE2")
static const trait_id trait_RADIOACTIVE3 ("RADIOACTIVE3")
static const trait_id trait_RADIOGENIC ("RADIOGENIC")
static const trait_id trait_REGEN_LIZ ("REGEN_LIZ")
static const trait_id trait_ROOTS3 ("ROOTS3")
static const trait_id trait_SCHIZOPHRENIC ("SCHIZOPHRENIC")
static const trait_id trait_SHARKTEETH ("SHARKTEETH")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHOUT1 ("SHOUT1")
static const trait_id trait_SHOUT2 ("SHOUT2")
static const trait_id trait_SHOUT3 ("SHOUT3")
static const trait_id trait_SORES ("SORES")
static const trait_id trait_SUNBURN ("SUNBURN")
static const trait_id trait_TROGLO ("TROGLO")
static const trait_id trait_TROGLO2 ("TROGLO2")
static const trait_id trait_TROGLO3 ("TROGLO3")
static const trait_id trait_UNSTABLE ("UNSTABLE")
static const trait_id trait_VOMITOUS ("VOMITOUS")
static const trait_id trait_WEB_SPINNER ("WEB_SPINNER")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
static const trait_id trait_WINGS_INSECT ("WINGS_INSECT")
static const mtype_id mon_zombie ("mon_zombie")
static const mtype_id mon_zombie_cop ("mon_zombie_cop")
static const mtype_id mon_zombie_fat ("mon_zombie_fat")
static const mtype_id mon_zombie_fireman ("mon_zombie_fireman")
static const mtype_id mon_zombie_soldier ("mon_zombie_soldier")
Function Documentation
addiction_scaling()
static float addiction_scaling (float at_min, float at_max, float add_lvl) static
Definition at line 172 of file suffer.cpp.
{
    // Not addicted
    if( add_lvl < MIN_ADDICTION_LEVEL ) {
        return 1.0f;
    }
    return lerp( at_min, at_max, ( add_lvl - MIN_ADDICTION_LEVEL ) / MAX_ADDICTION_LEVEL );
}
References lerp(), MAX_ADDICTION_LEVEL, and MIN_ADDICTION_LEVEL.
Referenced by Character::mend().
flag_BLIND()
static const std::string flag_BLIND ("BLIND") static
Referenced by Character::suffer_from_sunburn().
flag_PLOWABLE()
static const std::string flag_PLOWABLE ("PLOWABLE") static
Referenced by Character::suffer_from_other_mutations().
flag_RAD_RESIST()
static const std::string flag_RAD_RESIST ("RAD_RESIST") static
Referenced by Character::suffer_from_radiation().
flag_SUN_GLASSES()
static const std::string flag_SUN_GLASSES ("SUN_GLASSES") static
Referenced by Character::suffer_from_sunburn().
Variable Documentation
bio_advreactor
const bionic_id bio_advreactor("bio_advreactor") ("bio_advreactor") static
Referenced by Character::suffer_from_radiation().
bio_dis_acid
const bionic_id bio_dis_acid("bio_dis_acid") ("bio_dis_acid") static
Referenced by Character::suffer_from_bad_bionics().
bio_dis_shock
const bionic_id bio_dis_shock("bio_dis_shock") ("bio_dis_shock") static
Referenced by Character::suffer_from_bad_bionics().
bio_drain
const bionic_id bio_drain("bio_drain") ("bio_drain") static
Referenced by Character::suffer_from_bad_bionics().
bio_geiger
const bionic_id bio_geiger("bio_geiger") ("bio_geiger") static
Referenced by Character::suffer_from_radiation().
bio_gills
const bionic_id bio_gills("bio_gills") ("bio_gills") static
Referenced by Character::suffer_from_asthma(), and Character::suffer_while_underwater().
bio_glowy
const bionic_id bio_glowy("bio_glowy") ("bio_glowy") static
Referenced by Character::suffer_from_bad_bionics().
bio_itchy
const bionic_id bio_itchy("bio_itchy") ("bio_itchy") static
Referenced by Character::suffer_from_bad_bionics().
bio_leaky
const bionic_id bio_leaky("bio_leaky") ("bio_leaky") static
Referenced by Character::suffer_from_bad_bionics().
bio_noise
const bionic_id bio_noise("bio_noise") ("bio_noise") static
Referenced by Character::suffer_from_bad_bionics().
bio_plut_filter
const bionic_id bio_plut_filter("bio_plut_filter") ("bio_plut_filter") static
Referenced by Character::suffer_from_radiation().
bio_power_weakness
const bionic_id bio_power_weakness("bio_power_weakness") ("bio_power_weakness") static
Referenced by Character::suffer_from_bad_bionics().
bio_reactor
const bionic_id bio_reactor("bio_reactor") ("bio_reactor") static
Referenced by Character::suffer_from_radiation().
bio_shakes
const bionic_id bio_shakes("bio_shakes") ("bio_shakes") static
Referenced by Character::suffer_from_bad_bionics().
bio_sleepy
const bionic_id bio_sleepy("bio_sleepy") ("bio_sleepy") static
Referenced by Character::suffer_from_bad_bionics().
bio_spasm
const bionic_id bio_spasm("bio_spasm") ("bio_spasm") static
Referenced by Character::suffer_from_bad_bionics().
bio_sunglasses
const bionic_id bio_sunglasses("bio_sunglasses") ("bio_sunglasses") static
Referenced by Character::suffer_from_sunburn().
bio_trip
const bionic_id bio_trip("bio_trip") ("bio_trip") static
Referenced by Character::suffer_from_bad_bionics().
effect_accumulated_mutagen
const efftype_id effect_accumulated_mutagen("accumulated_mutagen") ("accumulated_mutagen") static
Referenced by Character::suffer().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by Character::suffer_from_asthma().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by Character::suffer_from_asthma().
effect_attention
const efftype_id effect_attention("attention") ("attention") static
Referenced by Character::suffer_from_artifacts().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::suffer_from_schizophrenia().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by Character::suffer_from_other_mutations().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by Character::mend().
effect_datura
const efftype_id effect_datura("datura") ("datura") static
Referenced by Character::suffer_from_asthma(), Character::suffer_from_sunburn(), and Character::suffer_in_sunlight().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by Character::suffer_from_other_mutations().
effect_disabled
const efftype_id effect_disabled("disabled") ("disabled") static
Referenced by Character::suffer().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by Character::suffer_from_bad_bionics(), Character::suffer_from_stimulants(), Character::suffer_while_awake(), and Character::suffer_without_sleep().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by Character::mend().
effect_formication
const efftype_id effect_formication("formication") ("formication") static
Referenced by Character::suffer_from_bad_bionics(), and Character::suffer_from_schizophrenia().
effect_glowy_led
const efftype_id effect_glowy_led("glowy_led") ("glowy_led") static
Referenced by Character::suffer_from_bad_bionics().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by Character::suffer_from_schizophrenia(), and Character::suffer_without_sleep().
effect_iodine
const efftype_id effect_iodine("iodine") ("iodine") static
Referenced by Character::irradiate().
effect_masked_scent
const efftype_id effect_masked_scent("masked_scent") ("masked_scent") static
Referenced by Character::drench().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by Character::mend().
effect_meth
const efftype_id effect_meth("meth") ("meth") static
Referenced by Character::suffer_without_sleep().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::suffer_from_asthma(), and Character::suffer_from_bad_bionics().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by Character::suffer_from_stimulants(), and Character::suffer_without_sleep().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by Character::drench().
effect_shakes
const efftype_id effect_shakes("shakes") ("shakes") static
Referenced by Character::suffer_from_bad_bionics(), Character::suffer_from_schizophrenia(), Character::suffer_from_stimulants(), Character::suffer_while_awake(), and Character::suffer_without_sleep().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Character::mend(), Character::suffer_from_asthma(), Character::suffer_from_chemimbalance(), and Character::suffer_from_sunburn().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by Character::suffer_from_bad_bionics().
effect_took_antiasthmatic
const efftype_id effect_took_antiasthmatic("took_antiasthmatic") ("took_antiasthmatic") static
Referenced by Character::suffer_from_asthma().
effect_took_thorazine
const efftype_id effect_took_thorazine("took_thorazine") ("took_thorazine") static
Referenced by Character::suffer_while_awake().
effect_valium
const efftype_id effect_valium("valium") ("valium") static
Referenced by Character::suffer_from_schizophrenia().
effect_visuals
const efftype_id effect_visuals("visuals") ("visuals") static
Referenced by Character::suffer_from_bad_bionics(), Character::suffer_from_other_mutations(), Character::suffer_from_schizophrenia(), and Character::suffer_without_sleep().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by Character::suffer_from_bad_bionics().
itype_inhaler
const itype_id itype_inhaler("inhaler") ("inhaler") static
Referenced by Character::suffer_from_asthma().
itype_oxygen_tank
const itype_id itype_oxygen_tank("oxygen_tank") ("oxygen_tank") static
Referenced by Character::suffer_from_asthma().
itype_rad_badge
const itype_id itype_rad_badge("rad_badge") ("rad_badge") static
Referenced by Character::irradiate().
itype_smoxygen_tank
const itype_id itype_smoxygen_tank("smoxygen_tank") ("smoxygen_tank") static
Referenced by Character::suffer_from_asthma().
mon_zombie
const mtype_id mon_zombie("mon_zombie") ("mon_zombie") static
Referenced by Character::suffer_from_schizophrenia().
mon_zombie_cop
const mtype_id mon_zombie_cop("mon_zombie_cop") ("mon_zombie_cop") static
Referenced by Character::suffer_from_schizophrenia().
mon_zombie_fat
const mtype_id mon_zombie_fat("mon_zombie_fat") ("mon_zombie_fat") static
Referenced by Character::suffer_from_schizophrenia().
mon_zombie_fireman
const mtype_id mon_zombie_fireman("mon_zombie_fireman") ("mon_zombie_fireman") static
Referenced by Character::suffer_from_schizophrenia().
mon_zombie_soldier
const mtype_id mon_zombie_soldier("mon_zombie_soldier") ("mon_zombie_soldier") static
Referenced by Character::suffer_from_schizophrenia().
trait_ADDICTIVE
const trait_id trait_ADDICTIVE("ADDICTIVE") ("ADDICTIVE") static
Referenced by Character::add_addiction(), and Character::suffer_from_addictions().
trait_ALBINO
const trait_id trait_ALBINO("ALBINO") ("ALBINO") static
Referenced by Character::suffer_from_sunburn(), and Character::suffer_in_sunlight().
trait_ASTHMA
const trait_id trait_ASTHMA("ASTHMA") ("ASTHMA") static
Referenced by Character::suffer().
trait_CHAOTIC
const trait_id trait_CHAOTIC("CHAOTIC") ("CHAOTIC") static
Referenced by Character::suffer_from_other_mutations().
trait_CHAOTIC_BAD
const trait_id trait_CHAOTIC_BAD("CHAOTIC_BAD") ("CHAOTIC_BAD") static
Referenced by Character::suffer_from_other_mutations().
trait_CHEMIMBALANCE
const trait_id trait_CHEMIMBALANCE("CHEMIMBALANCE") ("CHEMIMBALANCE") static
Referenced by Character::suffer_while_awake().
trait_DEBUG_NOTEMP
const trait_id trait_DEBUG_NOTEMP("DEBUG_NOTEMP") ("DEBUG_NOTEMP") static
Referenced by Character::drench().
trait_DEBUG_STORAGE
const trait_id trait_DEBUG_STORAGE("DEBUG_STORAGE") ("DEBUG_STORAGE") static
Referenced by Character::suffer_while_awake().
trait_FRESHWATEROSMOSIS
const trait_id trait_FRESHWATEROSMOSIS("FRESHWATEROSMOSIS") ("FRESHWATEROSMOSIS") static
Referenced by Character::suffer_while_underwater().
trait_GILLS
const trait_id trait_GILLS("GILLS") ("GILLS") static
Referenced by Character::suffer_while_underwater().
trait_GILLS_CEPH
const trait_id trait_GILLS_CEPH("GILLS_CEPH") ("GILLS_CEPH") static
Referenced by Character::suffer_while_underwater().
trait_JITTERY
const trait_id trait_JITTERY("JITTERY") ("JITTERY") static
Referenced by Character::suffer_while_awake().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by Character::suffer_from_other_mutations().
trait_LEAVES
const trait_id trait_LEAVES("LEAVES") ("LEAVES") static
Referenced by Character::suffer_in_sunlight().
trait_LEAVES2
const trait_id trait_LEAVES2("LEAVES2") ("LEAVES2") static
Referenced by Character::suffer_in_sunlight().
trait_LEAVES3
const trait_id trait_LEAVES3("LEAVES3") ("LEAVES3") static
Referenced by Character::suffer_in_sunlight().
trait_M_BLOSSOMS
const trait_id trait_M_BLOSSOMS("M_BLOSSOMS") ("M_BLOSSOMS") static
Referenced by Character::suffer_while_awake().
trait_M_SPORES
const trait_id trait_M_SPORES("M_SPORES") ("M_SPORES") static
Referenced by Character::suffer_while_awake().
trait_MOODSWINGS
const trait_id trait_MOODSWINGS("MOODSWINGS") ("MOODSWINGS") static
Referenced by Character::suffer_while_awake().
trait_NARCOLEPTIC
const trait_id trait_NARCOLEPTIC("NARCOLEPTIC") ("NARCOLEPTIC") static
Referenced by Character::suffer_while_awake().
trait_NONADDICTIVE
const trait_id trait_NONADDICTIVE("NONADDICTIVE") ("NONADDICTIVE") static
Referenced by Character::add_addiction(), and Character::suffer_from_addictions().
trait_NOPAIN
const trait_id trait_NOPAIN("NOPAIN") ("NOPAIN") static
Referenced by Character::suffer_from_chemimbalance().
trait_PER_SLIME
const trait_id trait_PER_SLIME("PER_SLIME") ("PER_SLIME") static
Referenced by Character::suffer_from_other_mutations().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by Character::suffer_from_other_mutations().
trait_RADIOACTIVE1
const trait_id trait_RADIOACTIVE1("RADIOACTIVE1") ("RADIOACTIVE1") static
Referenced by Character::irradiate(), and Character::suffer_from_radiation().
trait_RADIOACTIVE2
const trait_id trait_RADIOACTIVE2("RADIOACTIVE2") ("RADIOACTIVE2") static
Referenced by Character::irradiate(), and Character::suffer_from_radiation().
trait_RADIOACTIVE3
const trait_id trait_RADIOACTIVE3("RADIOACTIVE3") ("RADIOACTIVE3") static
Referenced by Character::irradiate(), and Character::suffer_from_radiation().
trait_RADIOGENIC
const trait_id trait_RADIOGENIC("RADIOGENIC") ("RADIOGENIC") static
Referenced by Character::mend(), and Character::suffer_from_radiation().
trait_REGEN_LIZ
const trait_id trait_REGEN_LIZ("REGEN_LIZ") ("REGEN_LIZ") static
Referenced by Character::mend().
trait_ROOTS3
const trait_id trait_ROOTS3("ROOTS3") ("ROOTS3") static
Referenced by Character::suffer_from_other_mutations().
trait_SCHIZOPHRENIC
const trait_id trait_SCHIZOPHRENIC("SCHIZOPHRENIC") ("SCHIZOPHRENIC") static
Referenced by Character::suffer_while_awake().
trait_SHARKTEETH
const trait_id trait_SHARKTEETH("SHARKTEETH") ("SHARKTEETH") static
Referenced by Character::suffer_from_other_mutations().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by Character::drench().
trait_SHOUT1
const trait_id trait_SHOUT1("SHOUT1") ("SHOUT1") static
Referenced by Character::suffer_while_awake().
trait_SHOUT2
const trait_id trait_SHOUT2("SHOUT2") ("SHOUT2") static
Referenced by Character::suffer_while_awake().
trait_SHOUT3
const trait_id trait_SHOUT3("SHOUT3") ("SHOUT3") static
Referenced by Character::suffer_while_awake().
trait_SORES
const trait_id trait_SORES("SORES") ("SORES") static
Referenced by Character::suffer_from_other_mutations().
trait_SUNBURN
const trait_id trait_SUNBURN("SUNBURN") ("SUNBURN") static
Referenced by Character::suffer_from_sunburn(), and Character::suffer_in_sunlight().
trait_TROGLO
const trait_id trait_TROGLO("TROGLO") ("TROGLO") static
Referenced by Character::suffer_in_sunlight().
trait_TROGLO2
const trait_id trait_TROGLO2("TROGLO2") ("TROGLO2") static
Referenced by Character::suffer_in_sunlight().
trait_TROGLO3
const trait_id trait_TROGLO3("TROGLO3") ("TROGLO3") static
Referenced by Character::suffer_in_sunlight().
trait_UNSTABLE
const trait_id trait_UNSTABLE("UNSTABLE") ("UNSTABLE") static
Referenced by Character::suffer_from_other_mutations().
trait_VOMITOUS
const trait_id trait_VOMITOUS("VOMITOUS") ("VOMITOUS") static
Referenced by Character::suffer_while_awake().
trait_WEB_SPINNER
const trait_id trait_WEB_SPINNER("WEB_SPINNER") ("WEB_SPINNER") static
Referenced by Character::suffer_from_other_mutations().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by Character::suffer_from_other_mutations().
trait_WINGS_INSECT
const trait_id trait_WINGS_INSECT("WINGS_INSECT") ("WINGS_INSECT") static
Referenced by Character::suffer_from_other_mutations().