Cataclysm BN: src/translations.h File Reference
translations.h File Reference
#include <map>
#include <ostream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "value_ptr.h"
Classes
class detail::local_translation_cache< std::string >
class detail::local_translation_cache< const char * >
class translation
Class for storing translation context and raw string for deferred translation.
struct translation::plural_tag
struct translation::no_translation_tag
struct localized_comparator
Namespaces
namespace detail
Macros
#define CATA_SRC_TRANSLATIONS_H
#define translate_marker(x) x
Marks a string literal to be extracted for translation.
#define translate_marker_context(c, x) x
Same as translate_marker, but also provides a context (string literal).
#define ATTRIBUTE_FORMAT_ARG(a)
#define _(msg)
Typedefs
using GenderMap = std::map< std::string, std::vector< std::string > >
Functions
int detail::get_current_language_version ()
void invalidate_translations ()
const char * detail::_translate_internal (const char *msg) ATTRIBUTE_FORMAT_ARG(1)
std::string detail::_translate_internal (const std::string &msg)
static local_translation_cache< const char * > detail::get_local_translation_cache (const char *)
static local_translation_cache< std::string > detail::get_local_translation_cache (const std::string &)
const char * vgettext (const char *msgid, const char *msgid_plural, size_t n) ATTRIBUTE_FORMAT_ARG(1)
const char * pgettext (const char *context, const char *msgid) ATTRIBUTE_FORMAT_ARG(2)
const char * vpgettext (const char *context, const char *msgid, const char *msgid_plural, size_t n) ATTRIBUTE_FORMAT_ARG(2)
std::string gettext_gendered (const GenderMap &genders, const std::string &msg)
Translation with a gendered context.
translation to_translation (const std::string &raw)
Shorthands for translation::to_translation.
translation to_translation (const std::string &ctxt, const std::string &raw)
translation pl_translation (const std::string &raw, const std::string &raw_pl)
Shorthands for translation::pl_translation.
translation pl_translation (const std::string &ctxt, const std::string &raw, const std::string &raw_pl)
translation no_translation (const std::string &str)
Shorthand for translation::no_translation.
std::ostream & operator<< (std::ostream &out, const translation &t)
Stream output and concatenation of translations.
std::string operator+ (const translation &lhs, const std::string &rhs)
std::string operator+ (const std::string &lhs, const translation &rhs)
std::string operator+ (const translation &lhs, const translation &rhs)
Variables
constexpr int INVALID_LANGUAGE_VERSION = 0
constexpr localized_comparator localized_compare {}
Macro Definition Documentation
_
#define _ (msg)
Value:
    ( ( []( const auto & arg ) { \
        static auto cache = detail::get_local_translation_cache( arg ); \
        return cache( arg ); \
    } )( msg ) )
Definition at line 116 of file translations.h.
ATTRIBUTE_FORMAT_ARG
#define ATTRIBUTE_FORMAT_ARG (a)
Definition at line 44 of file translations.h.
CATA_SRC_TRANSLATIONS_H
#define CATA_SRC_TRANSLATIONS_H
Definition at line 3 of file translations.h.
translate_marker
#define translate_marker (x) x
Marks a string literal to be extracted for translation.
This is only for running xgettext via "lang/update_pot.sh". Use _ to extract and translate at run time. The macro itself does not do anything, the argument is passed through it without any changes.
Definition at line 30 of file translations.h.
translate_marker_context
#define translate_marker_context (c, x) x
Same as translate_marker, but also provides a context (string literal).
This is similar to pgettext, but it does not translate at run time. Like translate_marker it just passes the second argument through.
Definition at line 38 of file translations.h.
Typedef Documentation
GenderMap
using GenderMap = std::map<std::string, std::vector<std::string> >
Definition at line 132 of file translations.h.
Function Documentation
gettext_gendered()
std::string gettext_gendered (const GenderMap & genders, const std::string & msg)
Translation with a gendered context.
Similar to pgettext, but the context is a collection of genders.
Parameters
genders A map where each key is a subject name (a string which should make sense to the translator in the context of the line to be translated) and the corresponding value is a list of potential genders for that subject. The first gender from the list of genders for the current language will be chosen for each subject (or the language default if there are no genders in common).
Definition at line 52 of file translations.cpp.
{
    const std::vector<std::string> &language_genders = get_language().genders;
    std::vector<std::string> chosen_genders;
    for( const auto &subject_genders : genders ) {
        // default if no match
        std::string chosen_gender = language_genders[0];
        for( const std::string &gender : subject_genders.second ) {
            if( std::find( language_genders.begin(), language_genders.end(), gender ) !=
                language_genders.end() ) {
                chosen_gender = gender;
                break;
            }
        }
        chosen_genders.push_back( subject_genders.first + ":" + chosen_gender );
    }
    std::string context = join( chosen_genders, " " );
    return pgettext( context.c_str(), msg.c_str() );
}
References detail::find(), language_info::genders, get_language(), join(), and pgettext().
Referenced by translate_gendered_line().
invalidate_translations()
void invalidate_translations ()
Definition at line 23 of file translations.cpp.
{
    // increment version to invalidate translation cache
    do {
        current_language_version++;
    } while( current_language_version == INVALID_LANGUAGE_VERSION );
}
References current_language_version, and INVALID_LANGUAGE_VERSION.
Referenced by l10n_data::set_library().
no_translation()
translation no_translation (const std::string & str)
Shorthand for translation::no_translation.
Definition at line 405 of file translations.cpp.
{
    return translation::no_translation( str );
}
References translation::no_translation().
Referenced by inventory_selector::add_map_items(), options_manager::add_options_interface(), dialogue::add_response(), inventory_selector::add_vehicle_items(), build_resource_list(), it_artifact_tool::create_name(), it_artifact_armor::create_name(), it_artifact_tool::deserialize(), it_artifact_armor::deserialize(), regional_settings::finalize(), Item_factory::find_template(), input_manager::get_default_action_name(), item_action_generator::load_item_action(), inventory_selector::naturalize_category(), new_artifact(), and new_natural_artifact().
operator+() [1/3]
std::string operator+ (const std::string & lhs, const translation & rhs)
Definition at line 420 of file translations.cpp.
{
    return lhs + rhs.translated();
}
References translation::translated().
operator+() [2/3]
std::string operator+ (const translation & lhs, const std::string & rhs)
Definition at line 415 of file translations.cpp.
{
    return lhs.translated() + rhs;
}
References translation::translated().
operator+() [3/3]
std::string operator+ (const translation & lhs, const translation & rhs)
Definition at line 425 of file translations.cpp.
{
    return lhs.translated() + rhs.translated();
}
References translation::translated().
operator<<()
std::ostream & operator<< (std::ostream & out, const translation & t)
Stream output and concatenation of translations.
Singular forms are used.
Definition at line 410 of file translations.cpp.
{
    return out << t.translated();
}
References translation::translated().
pgettext()
const char * pgettext (const char * context, const char * msgid)
Definition at line 41 of file translations.cpp.
{
    return l10n_data::get_library().get_ctx( context, msgid );
}
References l10n_data::get_library().
Referenced by timed_event::actualize(), monexamine::add_armor(), add_disassemblables(), add_salvagables(), artifact_name(), vehicle::automatic_fire_turret(), Character::bionics_install_failure(), Character::block_hit(), game::cancel_activity_or_ignore_query(), close(), talk_function::companion_choose(), iuse::craft(), it_artifact_tool::create_name(), talk_response::create_option_line(), debug_menu::debug(), Creature::describe_infrared(), destroyed_armor_msg(), units::display(), item::display_money(), veh_interact::do_install(), draw_bionics_titlebar(), draw_speed_tab(), item::durability_indicator(), editmap::edit(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), edit_json(), editmap::edit_mapgen(), effects_description_for_creature(), enumerate_objects_around_point(), monster::extended_description(), fac_combat_ability_text(), fac_respect_text(), fac_wealth_text(), npc::faction_display(), Character::fall_asleep(), Messages::dialog::filter_help_text(), item::final_info(), fire(), faction::food_supply_text(), format_object_pair_article(), mattack::fungus_fortify(), selection_column_preset::get_caption(), input_context::get_desc(), bonus_container::get_description(), overmapbuffer::get_description_at(), input_manager::get_keyname(), liquid_handler::get_liquid_target(), player_activity::get_progress_message(), get_stat_name(), gettext_gendered(), talk_function::goto_location(), Character::i_add_to_container(), info_title< furn_t >(), info_title< ter_t >(), info_title< trap >(), main_menu::init_strings(), inscribe_actor::item_inscription(), npc::load_npc_template(), editmap::mapgen_preview(), editmap::mapgen_retarget(), marloss_common(), mutation_category_trait::memorial_message_female(), mutation_category_trait::memorial_message_male(), avatar_funcs::mend_item(), mill_activate(), mill_load_food(), game::mon_info(), move_mode_string(), monster::move_to(), msg_type_from_name(), MapExtras::mx_grave(), gun_type_type::name(), name_by_dt(), main_menu::new_character_tab(), new_natural_artifact(), memorial_logger::notify(), open(), dialogue::opt(), target_ui::panel_recoil(), parse_tags(), photo_def_for_camera_point(), power_stat(), print_humidity(), game::print_items_info(), print_pressure(), print_ranged_chance(), print_temperature(), query_yn(), computer_session::query_ynq(), read_inventory_preset::read_inventory_preset(), item::reload(), monexamine::remove_armor(), iuse::rpgdie(), editmap::select_shape(), vehicle::set_electronics_menu_options(), set_item_map_or_vehicle(), set_profession(), safemode::show(), overmap_ui::show_notes_manager(), player::start_craft(), item::tname(), translation::translated(), try_reject_mutagen(), item::type_name(), editmap::update_view_with_help(), heal_actor::use_healing_item(), volume_units_abbr(), weather_forecast(), avatar::wield(), avatar_action::wield(), game::win(), game::win_screen(), and memorial_logger::write().
pl_translation() [1/2]
translation pl_translation (const std::string & ctxt, const std::string & raw, const std::string & raw_pl)
Definition at line 399 of file translations.cpp.
{
    return translation::pl_translation( ctxt, raw, raw_pl );
}
References translation::pl_translation().
pl_translation() [2/2]
translation pl_translation (const std::string & raw, const std::string & raw_pl)
Shorthands for translation::pl_translation.
Definition at line 394 of file translations.cpp.
{
    return translation::pl_translation( raw, raw_pl );
}
References translation::pl_translation().
Referenced by mtype::mtype().
to_translation() [1/2]
translation to_translation (const std::string & ctxt, const std::string & raw)
Definition at line 389 of file translations.cpp.
{
    return translation::to_translation( ctxt, raw );
}
References translation::to_translation().
to_translation() [2/2]
translation to_translation (const std::string & raw)
Shorthands for translation::to_translation.
Definition at line 384 of file translations.cpp.
{
    return translation::to_translation( raw );
}
References translation::to_translation().
Referenced by computer_session::action_research(), options_manager::add_options_debug(), options_manager::add_options_general(), options_manager::add_options_graphics(), build_resource_list(), options_manager::build_soundpacks_list(), options_manager::build_tilesets_list(), construction_menu(), character_display::disp_info(), talk_function::display_and_choose_opts(), input_context::display_menu(), effects_description_for_creature(), Name::generate(), Creature::get_attitude_ui_data(), get_default_mode_input_context(), inventory_selector::get_navigation_data(), game::get_player_input(), Messages::dialog::init(), inventory_multiselector::inventory_multiselector(), inventory_selector::inventory_selector(), game::list_items(), game::list_monsters(), spell_type::load(), species_type::load(), scenario::load(), pry_result::load(), iuse_transform::load(), set_transform_iuse::load(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), ma_buff_effect_type::ma_buff_effect_type(), options_manager::options_manager(), pickup::pick_up(), rad_badge_color(), overmap_ui::search(), defense_game::setup(), worldfactory::show_modselection_window(), and target_ui::uitext_fire().
vgettext()
const char * vgettext (const char * msgid, const char * msgid_plural, size_t n)
Definition at line 36 of file translations.cpp.
{
    return l10n_data::get_library().get_pl( msgid, msgid_plural, n );
}
References l10n_data::get_library().
Referenced by computer_session::action_list_bionics(), iexamine::arcfurnace_full(), vehicle::automatic_fire_turret(), item::bionic_info(), item::book_info(), gun_actor::call(), crafting::can_disassemble(), iuse_transform::can_use(), defense_game::caravan(), mattack::chickenbot(), salvage_actor::cut_up(), debug_menu::debug(), anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), npc::drop_items(), drop_on_map(), dialogue::dynamic_line(), einkpc_download_memory_card(), enumerate_objects_around_point(), Character::feed_furnace_with(), item::final_info(), mattack::flamethrower(), options_manager::PageItem::fmt_tooltip(), Character::fuel_bionic_with(), iexamine::fvat_full(), activatable_inventory_preset::get_denial(), ma_technique::get_description(), ma_requirements::get_description(), ma_buff::get_description(), diary::get_head_text(), mod_ui::get_information(), item::gun_info(), Character::has_enough_charges(), holster_actor::info(), bandolier_actor::info(), ma_style_callback::key(), iexamine::kiln_full(), game::knockback(), trapfunc::ledge(), iexamine::ledge(), item::magazine_info(), mattack::multi_robot(), monexamine::pay_bot(), Character::perform_technique(), photo_def_for_camera_point(), game::place_player(), activity_handlers::pulp_do_turn(), put_into_vehicle(), set_profession(), set_scenario(), set_skills(), set_traits(), skim_book_msg(), iexamine::smoker_options(), activity_handlers::start_engines_finish(), Character::suffer_from_asthma(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), quality_requirement::to_colored_string(), quality_requirement::to_string(), to_string_clipped(), item::tool_info(), translation::translated(), editmap::update_view_with_help(), and place_monster_iuse::use().
vpgettext()
const char * vpgettext (const char * context, const char * msgid, const char * msgid_plural, size_t n)
Definition at line 46 of file translations.cpp.
{
    return l10n_data::get_library().get_ctx_pl( context, msgid, msgid_plural, n );
}
References l10n_data::get_library().
Referenced by item::tname(), tool_comp::to_string(), item_comp::to_string(), translation::translated(), and item::type_name().
Variable Documentation
INVALID_LANGUAGE_VERSION
constexpr int INVALID_LANGUAGE_VERSION = 0 constexpr
Definition at line 14 of file translations.h.
Referenced by translation::add_context(), translation::deserialize(), invalidate_translations(), translation::make_plural(), and translatable_mod_info::translatable_mod_info().
localized_compare
constexpr localized_comparator localized_compare {} constexpr
Definition at line 342 of file translations.h.
Referenced by compare_mod_by_name_and_category(), debug_menu::debug(), character_display::disp_info(), player_morale::display(), npc::faction_display(), item::final_info(), get_achievements_text(), requirement_data::get_folded_list(), npc_trading::init_buying(), ma_style_callback::key(), main_menu::load_char_templates(), advanced_inv_sorter::operator()(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), player::operator()(), item::operator<(), peek_related_recipe(), requirement_data::print_all_objs(), basecamp::recruit_return(), set_description(), set_skills(), read_inventory_preset::sort_compare(), overmap_ui::sortfunc_name(), trait_display_nocolor_sort(), trait_display_sort(), translation::translated_lt(), debug_menu::wishitem(), and debug_menu::wishskill().