Cataclysm BN: src/trap.h File Reference
trap.h File Reference
#include <cstddef>
#include <functional>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "color.h"
#include "magic.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
Classes
struct vehicle_handle_trap_data
struct trap
Namespaces
namespace trapfunc
Macros
#define CATA_SRC_TRAP_H
Typedefs
using trap_function = std::function< bool(const tripoint &, Creature *, item *)>
Functions
bool trapfunc::none (const tripoint &, Creature *, item *)
bool trapfunc::bubble (const tripoint &p, Creature *c, item *i)
bool trapfunc::glass (const tripoint &p, Creature *c, item *i)
bool trapfunc::cot (const tripoint &p, Creature *c, item *i)
bool trapfunc::beartrap (const tripoint &p, Creature *c, item *i)
bool trapfunc::snare_light (const tripoint &p, Creature *c, item *i)
bool trapfunc::snare_heavy (const tripoint &p, Creature *c, item *i)
bool trapfunc::board (const tripoint &p, Creature *c, item *i)
bool trapfunc::caltrops (const tripoint &p, Creature *c, item *i)
bool trapfunc::caltrops_glass (const tripoint &p, Creature *c, item *i)
bool trapfunc::tripwire (const tripoint &p, Creature *c, item *i)
bool trapfunc::crossbow (const tripoint &p, Creature *c, item *i)
bool trapfunc::shotgun (const tripoint &p, Creature *c, item *i)
bool trapfunc::blade (const tripoint &p, Creature *c, item *i)
bool trapfunc::landmine (const tripoint &p, Creature *c, item *i)
bool trapfunc::telepad (const tripoint &p, Creature *c, item *i)
bool trapfunc::goo (const tripoint &p, Creature *c, item *i)
bool trapfunc::dissector (const tripoint &p, Creature *c, item *i)
bool trapfunc::sinkhole (const tripoint &p, Creature *c, item *i)
bool trapfunc::pit (const tripoint &p, Creature *c, item *i)
bool trapfunc::pit_spikes (const tripoint &p, Creature *c, item *i)
bool trapfunc::pit_glass (const tripoint &p, Creature *c, item *i)
bool trapfunc::lava (const tripoint &p, Creature *c, item *i)
bool trapfunc::portal (const tripoint &p, Creature *c, item *i)
bool trapfunc::ledge (const tripoint &p, Creature *c, item *i)
bool trapfunc::boobytrap (const tripoint &p, Creature *c, item *i)
bool trapfunc::temple_flood (const tripoint &p, Creature *c, item *i)
bool trapfunc::temple_toggle (const tripoint &p, Creature *c, item *i)
bool trapfunc::glow (const tripoint &p, Creature *c, item *i)
bool trapfunc::hum (const tripoint &p, Creature *c, item *i)
bool trapfunc::shadow (const tripoint &p, Creature *c, item *i)
bool trapfunc::map_regen (const tripoint &p, Creature *c, item *i)
bool trapfunc::drain (const tripoint &p, Creature *c, item *i)
bool trapfunc::snake (const tripoint &p, Creature *c, item *i)
bool trapfunc::cast_spell (const tripoint &p, Creature *critter, item *)
const trap_function & trap_function_from_string (const std::string &function_name)
Takes the name of a trap function and returns a function pointer to it.
Variables
trap_id tr_null
trap_id tr_bubblewrap
trap_id tr_glass
trap_id tr_cot
trap_id tr_funnel
trap_id tr_metal_funnel
trap_id tr_makeshift_funnel
trap_id tr_leather_funnel
trap_id tr_rollmat
trap_id tr_fur_rollmat
trap_id tr_beartrap
trap_id tr_beartrap_buried
trap_id tr_nailboard
trap_id tr_caltrops
trap_id tr_caltrops_glass
trap_id tr_tripwire
trap_id tr_crossbow
trap_id tr_shotgun_2
trap_id tr_shotgun_2_1
trap_id tr_shotgun_1
trap_id tr_engine
trap_id tr_blade
trap_id tr_landmine
trap_id tr_landmine_buried
trap_id tr_telepad
trap_id tr_goo
trap_id tr_dissector
trap_id tr_sinkhole
trap_id tr_pit
trap_id tr_spike_pit
trap_id tr_glass_pit
trap_id tr_lava
trap_id tr_portal
trap_id tr_ledge
trap_id tr_boobytrap
trap_id tr_temple_flood
trap_id tr_temple_toggle
trap_id tr_glow
trap_id tr_hum
trap_id tr_shadow
trap_id tr_drain
trap_id tr_snake
Macro Definition Documentation
CATA_SRC_TRAP_H
#define CATA_SRC_TRAP_H
Definition at line 3 of file trap.h.
Typedef Documentation
trap_function
using trap_function = std::function<bool(const tripoint &, Creature *, item *)>
Definition at line 84 of file trap.h.
Function Documentation
trap_function_from_string()
const trap_function & trap_function_from_string (const std::string & function_name)
Takes the name of a trap function and returns a function pointer to it.
Parameters
function_name The name of the trapfunc function to find.
Returns
A function object with a pointer to the matched function, or to trapfunc::none if there is no match.
Definition at line 1465 of file trapfunc.cpp.
{
    static const std::unordered_map<std::string, trap_function> funmap = {{
            { "none", trapfunc::none },
            { "bubble", trapfunc::bubble },
            { "glass", trapfunc::glass },
            { "cot", trapfunc::cot },
            { "beartrap", trapfunc::beartrap },
            { "board", trapfunc::board },
            { "caltrops", trapfunc::caltrops },
            { "caltrops_glass", trapfunc::caltrops_glass },
            { "tripwire", trapfunc::tripwire },
            { "crossbow", trapfunc::crossbow },
            { "shotgun", trapfunc::shotgun },
            { "blade", trapfunc::blade },
            { "snare_light", trapfunc::snare_light },
            { "snare_heavy", trapfunc::snare_heavy },
            { "landmine", trapfunc::landmine },
            { "telepad", trapfunc::telepad },
            { "goo", trapfunc::goo },
            { "dissector", trapfunc::dissector },
            { "sinkhole", trapfunc::sinkhole },
            { "pit", trapfunc::pit },
            { "pit_spikes", trapfunc::pit_spikes },
            { "pit_glass", trapfunc::pit_glass },
            { "lava", trapfunc::lava },
            { "portal", trapfunc::portal },
            { "ledge", trapfunc::ledge },
            { "boobytrap", trapfunc::boobytrap },
            { "temple_flood", trapfunc::temple_flood },
            { "temple_toggle", trapfunc::temple_toggle },
            { "glow", trapfunc::glow },
            { "hum", trapfunc::hum },
            { "shadow", trapfunc::shadow },
            { "map_regen", trapfunc::map_regen },
            { "drain", trapfunc::drain },
            { "spell", trapfunc::cast_spell },
            { "snake", trapfunc::snake }
        }
    };
    const auto iter = funmap.find( function_name );
    if( iter != funmap.end() ) {
        return iter->second;
    }
    debugmsg( "Could not find a trapfunc function matching '%s'!", function_name );
    static const trap_function null_fun = trapfunc::none;
    return null_fun;
}
References trapfunc::beartrap(), trapfunc::blade(), trapfunc::board(), trapfunc::boobytrap(), trapfunc::bubble(), trapfunc::caltrops(), trapfunc::caltrops_glass(), trapfunc::cast_spell(), trapfunc::cot(), trapfunc::crossbow(), debugmsg, trapfunc::dissector(), trapfunc::drain(), trapfunc::glass(), trapfunc::glow(), trapfunc::goo(), trapfunc::hum(), trapfunc::landmine(), trapfunc::lava(), trapfunc::ledge(), trapfunc::map_regen(), trapfunc::none(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), trapfunc::portal(), trapfunc::shadow(), trapfunc::shotgun(), trapfunc::sinkhole(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), trapfunc::telepad(), trapfunc::temple_flood(), trapfunc::temple_toggle(), and trapfunc::tripwire().
Referenced by trap::load().
Variable Documentation
tr_beartrap
trap_id tr_beartrap
Definition at line 266 of file trap.h.
tr_beartrap_buried
trap_id tr_beartrap_buried
Definition at line 267 of file trap.h.
tr_blade
trap_id tr_blade
Definition at line 277 of file trap.h.
tr_boobytrap
trap_id tr_boobytrap
Definition at line 290 of file trap.h.
tr_bubblewrap
trap_id tr_bubblewrap
Definition at line 257 of file trap.h.
tr_caltrops
trap_id tr_caltrops
Definition at line 269 of file trap.h.
tr_caltrops_glass
trap_id tr_caltrops_glass
Definition at line 270 of file trap.h.
tr_cot
trap_id tr_cot
Definition at line 259 of file trap.h.
tr_crossbow
trap_id tr_crossbow
Definition at line 272 of file trap.h.
tr_dissector
trap_id tr_dissector
Definition at line 282 of file trap.h.
tr_drain
trap_id tr_drain
Definition at line 296 of file trap.h.
tr_engine
trap_id tr_engine
Definition at line 276 of file trap.h.
tr_funnel
trap_id tr_funnel
Definition at line 260 of file trap.h.
tr_fur_rollmat
trap_id tr_fur_rollmat
Definition at line 265 of file trap.h.
tr_glass
trap_id tr_glass
Definition at line 258 of file trap.h.
tr_glass_pit
trap_id tr_glass_pit
Definition at line 286 of file trap.h.
tr_glow
trap_id tr_glow
Definition at line 293 of file trap.h.
tr_goo
trap_id tr_goo
Definition at line 281 of file trap.h.
tr_hum
trap_id tr_hum
Definition at line 294 of file trap.h.
tr_landmine
trap_id tr_landmine
Definition at line 278 of file trap.h.
tr_landmine_buried
trap_id tr_landmine_buried
Definition at line 279 of file trap.h.
tr_lava
trap_id tr_lava
Definition at line 287 of file trap.h.
tr_leather_funnel
trap_id tr_leather_funnel
Definition at line 263 of file trap.h.
tr_ledge
trap_id tr_ledge
Definition at line 289 of file trap.h.
tr_makeshift_funnel
trap_id tr_makeshift_funnel
Definition at line 262 of file trap.h.
tr_metal_funnel
trap_id tr_metal_funnel
Definition at line 261 of file trap.h.
tr_nailboard
trap_id tr_nailboard
Definition at line 268 of file trap.h.
tr_null
trap_id tr_null extern
Definition at line 276 of file trap.cpp.
Referenced by map::actualize(), map::clear_traps(), construction_activity(), trap::finalize(), get_changed_ids_from_update(), vehicle::handle_trap(), string_id< T >::id(), trap::is_null(), ter_t::load(), place_construction(), map::remove_trap(), set_ter_ids(), submap::submap(), map::ter_set(), map::tr_at(), map::trap_set(), and editmap::update_view_with_help().
tr_pit
trap_id tr_pit
Definition at line 284 of file trap.h.
tr_portal
trap_id tr_portal
Definition at line 288 of file trap.h.
tr_rollmat
trap_id tr_rollmat
Definition at line 264 of file trap.h.
tr_shadow
trap_id tr_shadow
Definition at line 295 of file trap.h.
tr_shotgun_1
trap_id tr_shotgun_1
Definition at line 275 of file trap.h.
tr_shotgun_2
trap_id tr_shotgun_2
Definition at line 273 of file trap.h.
tr_shotgun_2_1
trap_id tr_shotgun_2_1
Definition at line 274 of file trap.h.
tr_sinkhole
trap_id tr_sinkhole
Definition at line 283 of file trap.h.
tr_snake
trap_id tr_snake
Definition at line 297 of file trap.h.
tr_spike_pit
trap_id tr_spike_pit
Definition at line 285 of file trap.h.
tr_telepad
trap_id tr_telepad
Definition at line 280 of file trap.h.
tr_temple_flood
trap_id tr_temple_flood
Definition at line 291 of file trap.h.
tr_temple_toggle
trap_id tr_temple_toggle
Definition at line 292 of file trap.h.
tr_tripwire
trap_id tr_tripwire
Definition at line 271 of file trap.h.