Cataclysm BN: src/ui.cpp File Reference
ui.cpp File Reference
#include "ui.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <climits>
#include <cstdlib>
#include <iterator>
#include <memory>
#include "avatar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "debug.h"
#include "game.h"
#include "ime.h"
#include "input.h"
#include "output.h"
#include "player.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "ui_manager.h"
Classes
struct pointmenu_cb::impl_t
Functions
catacurses::window new_centered_win (int nlines, int ncols)
static int find_minimum_fold_width (const std::string &str, int max_lines, int min_width, int max_width)
Find the minimum width between max(min_width, 1) and max(max_width, min_width, 1) to fold the string to no more than max_lines, or no more than the minimum number of lines possible, assuming that foldstring(width).size() decreases monotonously with width.
Function Documentation
new_centered_win()
catacurses::window new_centered_win (int nlines, int ncols)
Definition at line 30 of file ui.cpp.
{
    int height = std::min( nlines, TERMY );
    int width = std::min( ncols, TERMX );
    point pos( ( TERMX - width ) / 2, ( TERMY - height ) / 2 );
    return catacurses::newwin( height, width, pos );
}
References catacurses::newwin(), TERMX, and TERMY.
Referenced by game::list_missions(), and show_scores_ui().