Cataclysm BN: src/units_volume.h File Reference
units_volume.h File Reference
#include <algorithm>
#include "units_def.h"
Classes
class units::volume_in_milliliter_tag
Namespaces
namespace units
Macros
#define CATA_SRC_UNITS_VOLUME_H
Typedefs
using units::volume = quantity< int, volume_in_milliliter_tag >
Functions
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > units::from_milliliter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > units::from_liter (const value_type v)
template<typename value_type >
constexpr value_type units::to_milliliter (const quantity< value_type, volume_in_milliliter_tag > &v)
constexpr double units::to_liter (const volume &v)
constexpr units::volume operator""_ml (const unsigned long long v)
constexpr units::quantity< double, units::volume_in_milliliter_tag > operator""_ml (const long double v)
constexpr units::volume operator""_liter (const unsigned long long v)
constexpr units::quantity< double, units::volume_in_milliliter_tag > operator""_liter (const long double v)
Variables
const volume units::volume_min
const volume units::volume_max
static constexpr volume units::legacy_volume_factor = from_milliliter(250)
Macro Definition Documentation
CATA_SRC_UNITS_VOLUME_H
#define CATA_SRC_UNITS_VOLUME_H
Definition at line 3 of file units_volume.h.
Function Documentation
operator""_liter() [1/2]
constexpr units::quantity< double, units::volume_in_milliliter_tag > operator""_liter (const long double v) inline constexpr
Definition at line 72 of file units_volume.h.
{
    return units::from_milliliter( v * 1000 );
}
References units::from_milliliter().
operator""_liter() [2/2]
constexpr units::volume operator""_liter (const unsigned long long v) inline constexpr
Definition at line 67 of file units_volume.h.
{
    return units::from_milliliter( v * 1000 );
}
References units::from_milliliter().
operator""_ml() [1/2]
constexpr units::quantity< double, units::volume_in_milliliter_tag > operator""_ml (const long double v) inline constexpr
Definition at line 60 of file units_volume.h.
{
    return units::from_milliliter( v );
}
References units::from_milliliter().
operator""_ml() [2/2]
constexpr units::volume operator""_ml (const unsigned long long v) inline constexpr
Definition at line 55 of file units_volume.h.
{
    return units::from_milliliter( v );
}
References units::from_milliliter().