Cataclysm BN: src/units_mass.h File Reference
units_mass.h File Reference
#include <algorithm>
#include "units_def.h"
Classes
class units::mass_in_milligram_tag
Namespaces
namespace units
Macros
#define CATA_SRC_UNITS_MASS_H
Typedefs
using units::mass = quantity< std::int64_t, mass_in_milligram_tag >
Functions
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_milligram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_gram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_kilogram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_newton (const value_type v)
template<typename value_type >
constexpr value_type units::to_milligram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type units::to_gram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type units::to_kilogram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type units::to_newton (const quantity< value_type, mass_in_milligram_tag > &v)
constexpr units::mass operator""_milligram (const unsigned long long v)
constexpr units::mass operator""_gram (const unsigned long long v)
constexpr units::mass operator""_kilogram (const unsigned long long v)
constexpr units::mass operator""_newton (const unsigned long long v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_milligram (const long double v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_gram (const long double v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_kilogram (const long double v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_newton (const long double v)
Variables
constexpr double GRAVITY_OF_EARTH = 9.81
constexpr mass units::mass_min
constexpr mass units::mass_max
Macro Definition Documentation
CATA_SRC_UNITS_MASS_H
#define CATA_SRC_UNITS_MASS_H
Definition at line 3 of file units_mass.h.
Function Documentation
operator""_gram() [1/2]
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_gram (const long double v) inline constexpr
Definition at line 113 of file units_mass.h.
{
    return units::from_gram( v );
}
References units::from_gram().
operator""_gram() [2/2]
constexpr units::mass operator""_gram (const unsigned long long v) inline constexpr
Definition at line 92 of file units_mass.h.
{
    return units::from_gram( v );
}
References units::from_gram().
operator""_kilogram() [1/2]
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_kilogram (const long double v) inline constexpr
Definition at line 119 of file units_mass.h.
{
    return units::from_kilogram( v );
}
References units::from_kilogram().
operator""_kilogram() [2/2]
constexpr units::mass operator""_kilogram (const unsigned long long v) inline constexpr
Definition at line 97 of file units_mass.h.
{
    return units::from_kilogram( v );
}
References units::from_kilogram().
operator""_milligram() [1/2]
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_milligram (const long double v) inline constexpr
Definition at line 107 of file units_mass.h.
{
    return units::from_milligram( v );
}
References units::from_milligram().
operator""_milligram() [2/2]
constexpr units::mass operator""_milligram (const unsigned long long v) inline constexpr
Definition at line 87 of file units_mass.h.
{
    return units::from_milligram( v );
}
References units::from_milligram().
operator""_newton() [1/2]
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_newton (const long double v) inline constexpr
Definition at line 125 of file units_mass.h.
{
    return units::from_newton( v );
}
References units::from_newton().
operator""_newton() [2/2]
constexpr units::mass operator""_newton (const unsigned long long v) inline constexpr
Definition at line 102 of file units_mass.h.
{
    return units::from_newton( v );
}
References units::from_newton().
Variable Documentation
GRAVITY_OF_EARTH
constexpr double GRAVITY_OF_EARTH = 9.81 constexpr
Definition at line 13 of file units_mass.h.
Referenced by vehicle::act_on_map(), vehicle::coeff_rolling_drag(), units::from_newton(), and units::to_newton().