Cataclysm BN: src/units_money.h File Reference
units_money.h File Reference
#include <algorithm>
#include "units_def.h"
Classes
class units::money_in_cent_tag
Namespaces
namespace units
Macros
#define CATA_SRC_UNITS_MONEY_H
Typedefs
using units::money = quantity< int, money_in_cent_tag >
Functions
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > units::from_cent (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > units::from_usd (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > units::from_kusd (const value_type v)
template<typename value_type >
constexpr value_type units::to_cent (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type units::to_usd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type units::to_kusd (const quantity< value_type, money_in_cent_tag > &v)
constexpr units::money operator""_cent (const unsigned long long v)
constexpr units::quantity< double, units::money_in_cent_tag > operator""_cent (const long double v)
constexpr units::money operator""_USD (const unsigned long long v)
constexpr units::quantity< double, units::money_in_cent_tag > operator""_USD (const long double v)
constexpr units::money operator""_kUSD (const unsigned long long v)
constexpr units::quantity< double, units::money_in_cent_tag > operator""_kUSD (const long double v)
Variables
const money units::money_min
const money units::money_max
Macro Definition Documentation
CATA_SRC_UNITS_MONEY_H
#define CATA_SRC_UNITS_MONEY_H
Definition at line 3 of file units_money.h.
Function Documentation
operator""_cent() [1/2]
constexpr units::quantity< double, units::money_in_cent_tag > operator""_cent (const long double v) inline constexpr
Definition at line 68 of file units_money.h.
{
    return units::from_cent( v );
}
References units::from_cent().
operator""_cent() [2/2]
constexpr units::money operator""_cent (const unsigned long long v) inline constexpr
Definition at line 63 of file units_money.h.
{
    return units::from_cent( v );
}
References units::from_cent().
operator""_kUSD() [1/2]
constexpr units::quantity< double, units::money_in_cent_tag > operator""_kUSD (const long double v) inline constexpr
Definition at line 90 of file units_money.h.
{
    return units::from_kusd( v );
}
References units::from_kusd().
operator""_kUSD() [2/2]
constexpr units::money operator""_kUSD (const unsigned long long v) inline constexpr
Definition at line 85 of file units_money.h.
{
    return units::from_kusd( v );
}
References units::from_kusd().
operator""_USD() [1/2]
constexpr units::quantity< double, units::money_in_cent_tag > operator""_USD (const long double v) inline constexpr
Definition at line 79 of file units_money.h.
{
    return units::from_usd( v );
}
References units::from_usd().
operator""_USD() [2/2]
constexpr units::money operator""_USD (const unsigned long long v) inline constexpr
Definition at line 74 of file units_money.h.
{
    return units::from_usd( v );
}
References units::from_usd().