Cataclysm BN: src/units_utility.h File Reference
units_utility.h File Reference
#include "units.h"
#include <type_traits>
Macros
#define CATA_SRC_UNITS_UTILITY_H
Enumerations
enum units_type { VU_VEHICLE , VU_WIND }
Type of object that a measurement is taken on.
Functions
template<typename T , typename U >
T divide_round_up (units::quantity< T, U > num, units::quantity< T, U > den)
Divide num by den, rounding up.
units::angle normalize (units::angle, units::angle mod=360_degrees)
Given an angle, add or subtract multiples of 360_degrees until it's in the range [0, 360_degrees).
template<typename T , typename U , std::enable_if_t< std::is_floating_point< T >::value > * = nullptr>
units::quantity< T, U > round_to_multiple_of (units::quantity< T, U > val, units::quantity< T, U > of)
const char * velocity_units (units_type vel_units)
Create a units label for a velocity value.
const char * weight_units ()
Create a units label for a weight value.
const char * volume_units_abbr ()
Create an abbreviated units label for a volume value.
const char * volume_units_long ()
Create a units label for a volume value.
double convert_velocity (int velocity, units_type vel_units)
Convert internal velocity units to units defined by user.
double convert_weight (const units::mass &weight)
Convert weight in grams to units defined by user (kg or lbs)
double convert_volume (int volume)
Convert volume from ml to units defined by user.
double convert_volume (int volume, int *out_scale)
Convert volume from ml to units defined by user, optionally returning the units preferred scale.
Macro Definition Documentation
CATA_SRC_UNITS_UTILITY_H
#define CATA_SRC_UNITS_UTILITY_H
Definition at line 3 of file units_utility.h.
Enumeration Type Documentation
units_type
enum units_type
Type of object that a measurement is taken on.
Used, for example, to display wind speed in m/s while displaying vehicle speed in km/h.
Enumerator
VU_VEHICLE
VU_WIND
Definition at line 13 of file units_utility.h.
                {
    VU_VEHICLE,
    VU_WIND
};
Function Documentation
convert_velocity()
double convert_velocity (int velocity, units_type vel_units)
Convert internal velocity units to units defined by user.
Parameters
velocity A velocity value in internal units.
vel_units General type of item this velocity is for (e.g. vehicles or wind)
Returns
Velocity in the user selected measurement system and in appropriate units for the object being measured.
Definition at line 61 of file units_utility.cpp.
{
    const std::string type = get_option<std::string>( "USE_METRIC_SPEEDS" );
    // internal units to mph conversion
    double ret = static_cast<double>( velocity ) / 100;
    if( type == "km/h" ) {
        switch( vel_units ) {
            case VU_VEHICLE:
                // mph to km/h conversion
                ret *= 1.609f;
                break;
            case VU_WIND:
                // mph to m/s conversion
                ret *= 0.447f;
                break;
        }
    } else if( type == "t/t" ) {
        ret /= 4;
    }
    return ret;
}
References cata::hash64_detail::ret, type, VU_VEHICLE, and VU_WIND.
Referenced by Character::activate_bionic(), veh_interact::display_stats(), draw_health_classic(), draw_veh_compact(), draw_veh_padding(), and iuse::weather_tool().
convert_volume() [1/2]
double convert_volume (int volume)
Convert volume from ml to units defined by user.
Definition at line 96 of file units_utility.cpp.
{
    return convert_volume( volume, nullptr );
}
References convert_volume().
Referenced by item::animal_armor_info(), item::armor_info(), item::basic_info(), carry_volume_string(), comestible_inventory_preset::comestible_inventory_preset(), item::contents_info(), convert_volume(), format_volume(), and holster_actor::info().
convert_volume() [2/2]
double convert_volume (int volume, int * out_scale)
Convert volume from ml to units defined by user, optionally returning the units preferred scale.
Definition at line 101 of file units_utility.cpp.
{
    double ret = volume;
    int scale = 0;
    const std::string vol_units = get_option<std::string>( "VOLUME_UNITS" );
    if( vol_units == "c" ) {
        ret *= 0.004;
        scale = 1;
    } else if( vol_units == "l" ) {
        ret *= 0.001;
        scale = 2;
    } else {
        ret *= 0.00105669;
        scale = 2;
    }
    if( out_scale != nullptr ) {
        *out_scale = scale;
    }
    return ret;
}
References cata::hash64_detail::ret.
convert_weight()
double convert_weight (const units::mass & weight)
Convert weight in grams to units defined by user (kg or lbs)
Parameters
weight to be converted.
Returns
Weight converted to user selected unit
Definition at line 85 of file units_utility.cpp.
{
    double ret = to_gram( weight );
    if( get_option<std::string>( "USE_METRIC_WEIGHTS" ) == "kg" ) {
        ret /= 1000;
    } else {
        ret /= 453.6;
    }
    return ret;
}
References cata::hash64_detail::ret, and units::to_gram().
Referenced by item::armor_info(), item::basic_info(), item::bionic_info(), carry_weight_string(), veh_interact::display_details(), veh_interact::display_stats(), draw_stats_info(), vpart_info::format_description(), inventory_selector::get_weight_and_volume_stats(), Character::get_weight_string(), holster_actor::info(), pickup::pick_up(), advanced_inventory::print_items(), item::qualities_info(), iexamine::recycle_compactor(), set_stats(), trading_window::update_win(), and weigh_self_actor::use().
divide_round_up()
template<typename T , typename U > T divide_round_up (units::quantity< T, U > num, units::quantity< T, U > den)
Divide num by den, rounding up.
num must be non-negative, den must be positive, and num+den must not overflow.
Definition at line 23 of file units_utility.h.
{
    T n = num.value();
    T d = den.value();
    return ( n + d - 1 ) / d;
}
References num, and units::quantity< V, U >::value().
normalize()
units::angle normalize (units::angle a, units::angle mod = 360_degrees)
Given an angle, add or subtract multiples of 360_degrees until it's in the range [0, 360_degrees).
With a second argument, can use a different maximum.
Definition at line 23 of file units_utility.cpp.
{
    a = units::fmod( a, mod );
    if( a < 0_degrees ) {
        a += mod;
    }
    return a;
}
References a, and units::fmod().
round_to_multiple_of()
template<typename T , typename U , std::enable_if_t< std::is_floating_point< T >::value > * = nullptr> units::quantity< T, U > round_to_multiple_of (units::quantity< T, U > val, units::quantity< T, U > of)
Definition at line 38 of file units_utility.h.
{
    int multiple = std::lround( val / of );
    return multiple * of;
}
Referenced by vehicle::immediate_path(), and vehicle::turn().
velocity_units()
const char * velocity_units (units_type vel_units)
Create a units label for a velocity value.
Gives the name of the velocity unit in the user selected unit system, either "km/h", "ms/s" or "mph". Used to add abbreviated unit labels to the output of convert_velocity.
Parameters
vel_units type of velocity desired (i.e. wind or vehicle)
Returns
name of unit.
Definition at line 5 of file units_utility.cpp.
{
    if( get_option<std::string>( "USE_METRIC_SPEEDS" ) == "mph" ) {
        return _( "mph" );
    } else if( get_option<std::string>( "USE_METRIC_SPEEDS" ) == "t/t" ) {
        //~ vehicle speed tiles per turn
        return _( "t/t" );
    } else {
        switch( vel_units ) {
            case VU_VEHICLE:
                return _( "km/h" );
            case VU_WIND:
                return _( "m/s" );
        }
    }
    return "error: unknown units!";
}
References _, VU_VEHICLE, and VU_WIND.
Referenced by Character::activate_bionic(), debug_menu::debug(), veh_interact::display_stats(), and iuse::weather_tool().
volume_units_abbr()
const char * volume_units_abbr ()
Create an abbreviated units label for a volume value.
Returns the abbreviated name for the volume unit for the user selected unit system, i.e. "c", "L", or "qt". Used to add unit labels to the output of convert_volume.
Returns
name of unit.
Definition at line 37 of file units_utility.cpp.
{
    const std::string vol_units = get_option<std::string>( "VOLUME_UNITS" );
    if( vol_units == "c" ) {
        return pgettext( "Volume unit", "c" );
    } else if( vol_units == "l" ) {
        return pgettext( "Volume unit", "L" );
    } else {
        return pgettext( "Volume unit", "qt" );
    }
}
References pgettext().
Referenced by item::animal_armor_info(), iexamine::arcfurnace_empty(), item::armor_info(), item::basic_info(), anonymous_namespace{armor_layers.cpp}::clothing_properties(), comestible_inventory_preset::comestible_inventory_preset(), item::contents_info(), veh_interact::display_details(), veh_interact::display_stats(), inventory_selector::get_weight_and_volume_stats(), holster_actor::info(), iexamine::kiln_empty(), advanced_inventory::print_items(), vehicle::print_part_list(), iexamine::quern_examine(), iexamine::smoker_options(), player::sort_armor(), trading_window::update_win(), and sew_advanced_actor::use().
volume_units_long()
const char * volume_units_long ()
Create a units label for a volume value.
Returns the abbreviated name for the volume unit for the user selected unit system, ie "cup", "liter", or "quart". Used to add unit labels to the output of convert_volume.
Returns
name of unit.
Definition at line 49 of file units_utility.cpp.
{
    const std::string vol_units = get_option<std::string>( "VOLUME_UNITS" );
    if( vol_units == "c" ) {
        return _( "cup" );
    } else if( vol_units == "l" ) {
        return _( "liter" );
    } else {
        return _( "quart" );
    }
}
References _.
Referenced by item::container_info(), give_item_to(), mill_activate(), smoker_activate(), and iexamine::smoker_options().
weight_units()
const char * weight_units ()
Create a units label for a weight value.
Gives the name of the weight unit in the user selected unit system, either "kgs" or "lbs". Used to add unit labels to the output of convert_weight.
Returns
name of unit
Definition at line 32 of file units_utility.cpp.
{
    return get_option<std::string>( "USE_METRIC_WEIGHTS" ) == "lbs" ? _( "lbs" ) : _( "kg" );
}
References _.
Referenced by item::armor_info(), item::basic_info(), item::bionic_info(), veh_interact::display_details(), veh_interact::display_stats(), draw_stats_info(), vpart_info::format_description(), inventory_selector::get_weight_and_volume_stats(), Character::get_weight_string(), holster_actor::info(), advanced_inventory::print_items(), item::qualities_info(), iexamine::recycle_compactor(), set_stats(), trading_window::update_win(), and weigh_self_actor::use().