Cataclysm BN: src/units_energy.h File Reference
units_energy.h File Reference
#include <algorithm>
#include "units_def.h"
Classes
class units::energy_in_joule_tag
Namespaces
namespace units
Macros
#define CATA_SRC_UNITS_ENERGY_H
Typedefs
using units::energy = quantity< int, energy_in_joule_tag >
Functions
template<typename value_type >
constexpr quantity< value_type, energy_in_joule_tag > units::from_joule (const value_type v)
template<typename value_type >
constexpr quantity< value_type, energy_in_joule_tag > units::from_kilojoule (const value_type v)
template<typename value_type >
constexpr value_type units::to_joule (const quantity< value_type, energy_in_joule_tag > &v)
template<typename value_type >
constexpr value_type units::to_kilojoule (const quantity< value_type, energy_in_joule_tag > &v)
constexpr units::energy operator""_J (const unsigned long long v)
constexpr units::quantity< double, units::energy_in_joule_tag > operator""_J (const long double v)
constexpr units::energy operator""_kJ (const unsigned long long v)
constexpr units::quantity< double, units::energy_in_joule_tag > operator""_kJ (const long double v)
Variables
const energy units::energy_min
const energy units::energy_max
Macro Definition Documentation
CATA_SRC_UNITS_ENERGY_H
#define CATA_SRC_UNITS_ENERGY_H
Definition at line 3 of file units_energy.h.
Function Documentation
operator""_J() [1/2]
constexpr units::quantity< double, units::energy_in_joule_tag > operator""_J (const long double v) inline constexpr
Definition at line 58 of file units_energy.h.
{
    return units::from_joule( v );
}
References units::from_joule().
operator""_J() [2/2]
constexpr units::energy operator""_J (const unsigned long long v) inline constexpr
Definition at line 53 of file units_energy.h.
{
    return units::from_joule( v );
}
References units::from_joule().
operator""_kJ() [1/2]
constexpr units::quantity< double, units::energy_in_joule_tag > operator""_kJ (const long double v) inline constexpr
Definition at line 69 of file units_energy.h.
{
    return units::from_kilojoule( v );
}
References units::from_kilojoule().
operator""_kJ() [2/2]
constexpr units::energy operator""_kJ (const unsigned long long v) inline constexpr
Definition at line 64 of file units_energy.h.
{
    return units::from_kilojoule( v );
}
References units::from_kilojoule().