Cataclysm BN: src/units_angle.h File Reference
units_angle.h File Reference
#include <algorithm>
#include "units_def.h"
#include "math_defines.h"
Classes
class units::angle_in_radians_tag
Namespaces
namespace units
Macros
#define CATA_SRC_UNITS_ANGLE_H
Typedefs
using units::angle = quantity< double, angle_in_radians_tag >
Functions
template<typename value_type >
constexpr quantity< value_type, angle_in_radians_tag > units::from_radians (const value_type v)
constexpr double units::to_radians (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > units::from_degrees (const value_type v)
constexpr double units::to_degrees (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > units::from_arcmin (const value_type v)
constexpr double units::to_arcmin (const units::angle v)
double units::sin (angle a)
double units::cos (angle a)
double units::tan (angle a)
units::angle units::atan2 (double y, double x)
constexpr units::angle operator""_radians (const long double v)
constexpr units::angle operator""_radians (const unsigned long long v)
constexpr units::angle operator""_pi_radians (const long double v)
constexpr units::angle operator""_pi_radians (const unsigned long long v)
constexpr units::angle operator""_degrees (const long double v)
constexpr units::angle operator""_degrees (const unsigned long long v)
constexpr units::angle operator""_arcmin (const long double v)
constexpr units::angle operator""_arcmin (const unsigned long long v)
Macro Definition Documentation
CATA_SRC_UNITS_ANGLE_H
#define CATA_SRC_UNITS_ANGLE_H
Definition at line 3 of file units_angle.h.
Function Documentation
operator""_arcmin() [1/2]
constexpr units::angle operator""_arcmin (const long double v) inline constexpr
Definition at line 104 of file units_angle.h.
{
    return units::from_arcmin( v );
}
References units::from_arcmin().
operator""_arcmin() [2/2]
constexpr units::angle operator""_arcmin (const unsigned long long v) inline constexpr
Definition at line 109 of file units_angle.h.
{
    return units::from_arcmin( v );
}
References units::from_arcmin().
operator""_degrees() [1/2]
constexpr units::angle operator""_degrees (const long double v) inline constexpr
Definition at line 94 of file units_angle.h.
{
    return units::from_degrees( v );
}
References units::from_degrees().
operator""_degrees() [2/2]
constexpr units::angle operator""_degrees (const unsigned long long v) inline constexpr
Definition at line 99 of file units_angle.h.
{
    return units::from_degrees( v );
}
References units::from_degrees().
operator""_pi_radians() [1/2]
constexpr units::angle operator""_pi_radians (const long double v) inline constexpr
Definition at line 84 of file units_angle.h.
{
    return units::from_radians( v * M_PI );
}
References units::from_radians(), and M_PI.
operator""_pi_radians() [2/2]
constexpr units::angle operator""_pi_radians (const unsigned long long v) inline constexpr
Definition at line 89 of file units_angle.h.
{
    return units::from_radians( v * M_PI );
}
References units::from_radians(), and M_PI.
operator""_radians() [1/2]
constexpr units::angle operator""_radians (const long double v) inline constexpr
Definition at line 74 of file units_angle.h.
{
    return units::from_radians( v );
}
References units::from_radians().
operator""_radians() [2/2]
constexpr units::angle operator""_radians (const unsigned long long v) inline constexpr
Definition at line 79 of file units_angle.h.
{
    return units::from_radians( v );
}
References units::from_radians().