Cataclysm BN: src/veh_type.cpp File Reference
veh_type.cpp File Reference
#include "veh_type.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <memory>
#include <numeric>
#include <unordered_map>
#include <unordered_set>
#include "ammo.h"
#include "assign.h"
#include "cata_utility.h"
#include "color.h"
#include "debug.h"
#include "flag.h"
#include "game_constants.h"
#include "init.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "json.h"
#include "mapdata.h"
#include "output.h"
#include "player.h"
#include "requirements.h"
#include "string_formatter.h"
#include "string_id.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vehicle_group.h"
Functions
static void parse_vp_reqs (const JsonObject &obj, const std::string &id, const std::string &key, std::vector< std::pair< requirement_id, int > > &reqs, std::map< skill_id, int > &skills, int &moves)
static int scale_time (const std::map< skill_id, int > &sk, int mv, const player &p)
Variables
std::unordered_map< vproto_id, vehicle_prototype > vtypes
static const std::unordered_map< std::string, vpart_bitflags > vpart_bitflag_map
static const std::vector< std::pair< std::string, int > > standard_terrain_mod
static const std::vector< std::pair< std::string, int > > rigid_terrain_mod
static const std::vector< std::pair< std::string, int > > racing_terrain_mod
static const std::vector< std::pair< std::string, int > > off_road_terrain_mod
static const std::vector< std::pair< std::string, int > > treads_terrain_mod
static const std::vector< std::pair< std::string, int > > rail_terrain_mod
static std::map< vpart_id, vpart_info > vpart_info_all
static std::map< vpart_id, vpart_info > abstract_parts
static DynamicDataLoader::deferred_json deferred
Function Documentation
parse_vp_reqs()
static void parse_vp_reqs (const JsonObject & obj, const std::string & id, const std::string & key, std::vector< std::pair< requirement_id, int > > & reqs, std::map< skill_id, int > & skills, int & moves) static
Definition at line 160 of file veh_type.cpp.
{
    if( !obj.has_object( key ) ) {
        return;
    }
    JsonObject src = obj.get_object( key );
    auto sk = src.get_array( "skills" );
    if( !sk.empty() ) {
        skills.clear();
    }
    for( JsonArray cur : sk ) {
        skills.emplace( skill_id( cur.get_string( 0 ) ), cur.size() >= 2 ? cur.get_int( 1 ) : 1 );
    }
    if( src.has_int( "time" ) ) {
        moves = src.get_int( "time" );
    } else if( src.has_string( "time" ) ) {
        moves = to_moves<int>( read_from_json_string<time_duration>( *src.get_raw( "time" ),
                               time_duration::units ) );
    }
    if( src.has_string( "using" ) ) {
        reqs = { { requirement_id( src.get_string( "using" ) ), 1 } };
    } else if( src.has_array( "using" ) ) {
        reqs.clear();
        for( JsonArray cur : src.get_array( "using" ) ) {
            reqs.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
        }
    } else {
        reqs.clear();
        // Construct a requirement to capture "components", "qualities", and
        // "tools" that might be listed.
        const requirement_id req_id( string_format( "inline_%s_%s", key.c_str(), id.c_str() ) );
        requirement_data::load_requirement( src, req_id );
        reqs.emplace_back( req_id, 1 );
    }
}
References JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_raw(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_string(), requirement_data::load_requirement(), Creature::moves, int_id< T >::obj(), string_format(), and time_duration::units.
Referenced by vpart_info::load().
scale_time()
static int scale_time (const std::map< skill_id, int > & sk, int mv, const player & p) static
Definition at line 806 of file veh_type.cpp.
{
    if( sk.empty() ) {
        return mv;
    }
    const int lvl = std::accumulate( sk.begin(), sk.end(), 0, [&p]( int lhs,
    const std::pair<skill_id, int> &rhs ) {
        return lhs + std::max( std::min( p.get_skill_level( rhs.first ), MAX_SKILL ) - rhs.second,
                               0 );
    } );
    // 10% per excess level (reduced proportionally if >1 skill required) with max 50% reduction
    // 10% reduction per assisting NPC
    return mv * ( 1.0 - std::min( static_cast<double>( lvl ) / sk.size() / 10.0, 0.5 ) )
           * ( 10 - p.get_crafting_helpers( 3 ).size() ) / 10;
}
References player::get_crafting_helpers().
Referenced by vpart_info::install_time(), vpart_info::removal_time(), and vpart_info::repair_time().
Variable Documentation
abstract_parts
std::map<vpart_id, vpart_info> abstract_parts static
Definition at line 136 of file veh_type.cpp.
Referenced by vpart_info::load(), and vpart_info::reset().
deferred
DynamicDataLoader::deferred_json deferred static
Definition at line 138 of file veh_type.cpp.
Referenced by vpart_info::finalize(), vpart_info::load(), and vpart_info::reset().
off_road_terrain_mod
const std::vector<std::pair<std::string, int> > off_road_terrain_mod static
Initial value:
= {{
        { "FLAT", 3 }, { "ROAD", 1 }
    }
}
Definition at line 121 of file veh_type.cpp.
Referenced by vpart_info::load_wheel().
racing_terrain_mod
const std::vector<std::pair<std::string, int> > racing_terrain_mod static
Initial value:
= {{
        { "FLAT", 5 }, { "ROAD", 2 }
    }
}
Definition at line 117 of file veh_type.cpp.
Referenced by vpart_info::load_wheel().
rail_terrain_mod
const std::vector<std::pair<std::string, int> > rail_terrain_mod static
Initial value:
= {{
        { "RAIL", 8 }
    }
}
Definition at line 129 of file veh_type.cpp.
Referenced by vpart_info::load_wheel().
rigid_terrain_mod
const std::vector<std::pair<std::string, int> > rigid_terrain_mod static
Initial value:
= {{
        { "FLAT", 6 }, { "ROAD", 3 }
    }
}
Definition at line 113 of file veh_type.cpp.
Referenced by vpart_info::load_wheel().
standard_terrain_mod
const std::vector<std::pair<std::string, int> > standard_terrain_mod static
Initial value:
= {{
        { "FLAT", 4 }, { "ROAD", 2 }
    }
}
Definition at line 109 of file veh_type.cpp.
Referenced by vpart_info::load_wheel().
treads_terrain_mod
const std::vector<std::pair<std::string, int> > treads_terrain_mod static
Initial value:
= {{
        { "FLAT", 3 }
    }
}
Definition at line 125 of file veh_type.cpp.
Referenced by vpart_info::load_wheel().
vpart_bitflag_map
const std::unordered_map<std::string, vpart_bitflags> vpart_bitflag_map static
Definition at line 61 of file veh_type.cpp.
Referenced by vpart_info::finalize(), and vpart_info::set_flag().
vpart_info_all
std::map<vpart_id, vpart_info> vpart_info_all static
Definition at line 134 of file veh_type.cpp.
Referenced by vpart_info::all(), vpart_info::check(), vpart_info::finalize(), string_id< T >::is_valid(), vpart_info::load(), and vpart_info::reset().
vtypes
std::unordered_map<vproto_id, vehicle_prototype> vtypes
Definition at line 38 of file veh_type.cpp.
Referenced by vehicle_prototype::finalize(), vehicle_prototype::get_all(), vehicle_prototype::load(), and vehicle_prototype::reset().