Cataclysm BN: src/vehicle_move.cpp File Reference
vehicle_move.cpp File Reference
#include "vehicle.h"
#include "vehicle_move.h"
#include <cassert>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <memory>
#include <ostream>
#include <set>
#include "avatar.h"
#include "bodypart.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "explosion.h"
#include "game.h"
#include "int_id.h"
#include "item.h"
#include "itype.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "math_defines.h"
#include "messages.h"
#include "monster.h"
#include "optional.h"
#include "options.h"
#include "player.h"
#include "point_float.h"
#include "rng.h"
#include "sounds.h"
#include "string_id.h"
#include "translations.h"
#include "trap.h"
#include "units_angle.h"
#include "units_utility.h"
#include "veh_type.h"
#include "vpart_position.h"
#include "vpart_range.h"
Namespaces
namespace vehicle_movement
Macros
#define dbg(x) DebugLogFL((x),DC::Map)
Functions
static const std::string part_location_structure ("structure")
int mps_to_vmiph (double mps)
double vmiph_to_mps (int vmiph)
int cmps_to_vmiph (int cmps)
int vmiph_to_cmps (int vmiph)
static void terrain_collision_data (const tripoint &p, bool bash_floor, float &mass, float &density, float &elastic)
static rl_vec2d angle_to_vec (units::angle angle)
float get_collision_factor (const float delta_v)
static bool vehicle_movement::scan_rails_from_veh_internal (const map &m, const vehicle &veh, tripoint scan_initial_pos, point veh_plus_y_vec, point scan_vec)
static bool vehicle_movement::scan_rails_at_shift (const map &m, const vehicle &veh, int velocity_sign, units::angle dir, int shift_sign, tripoint *shift_amt=nullptr)
static rail_processing_result vehicle_movement::make_none ()
static rail_processing_result vehicle_movement::make_turn (units::angle a)
static rail_processing_result vehicle_movement::make_shift (tripoint dp)
rail_processing_result vehicle_movement::process_movement_on_rails (const map &m, const vehicle &veh)
Decides how the vehicle should move in order to follow rails, or get on rails.
bool vehicle_movement::is_on_rails (const map &m, const vehicle &veh)
Returns whether the vehicle is currently on rails.
Variables
static const itype_id fuel_type_muscle ("muscle")
static const itype_id fuel_type_animal ("animal")
static const itype_id fuel_type_battery ("battery")
static const skill_id skill_driving ("driving")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_stunned ("stunned")
static const float tile_height = 4
static const int mi_to_vmi = 100
static const float mps_to_miph = 2.23694f
Macro Definition Documentation
dbg
#define dbg (x) DebugLogFL((x),DC::Map)
Definition at line 45 of file vehicle_move.cpp.
Function Documentation
angle_to_vec()
static rl_vec2d angle_to_vec (units::angle angle) inline static
Definition at line 1214 of file vehicle_move.cpp.
{
    return rl_vec2d( units::cos( angle ), units::sin( angle ) );
}
References units::cos(), and units::sin().
Referenced by vehicle::dir_vec(), vehicle::face_vec(), and vehicle::move_vec().
cmps_to_vmiph()
int cmps_to_vmiph (int cmps)
Definition at line 78 of file vehicle_move.cpp.
{
    return cmps * mps_to_miph;
}
References mps_to_miph.
Referenced by vehicle::ground_acceleration(), vehicle::rotor_acceleration(), and vehicle::water_acceleration().
get_collision_factor()
float get_collision_factor (const float delta_v)
Definition at line 1236 of file vehicle_move.cpp.
{
    if( std::abs( delta_v ) <= 31 ) {
        return ( 1 - ( 0.9 * std::abs( delta_v ) ) / 31 );
    } else {
        return 0.1;
    }
}
Referenced by map::vehicle_vehicle_collision().
mps_to_vmiph()
int mps_to_vmiph (double mps)
Definition at line 67 of file vehicle_move.cpp.
{
    return mps * mps_to_miph * mi_to_vmi;
}
References mi_to_vmi, and mps_to_miph.
Referenced by vehicle::act_on_map(), vehicle::max_ground_velocity(), vehicle::max_rotor_velocity(), vehicle::max_water_velocity(), vehicle::safe_ground_velocity(), vehicle::safe_rotor_velocity(), vehicle::safe_water_velocity(), and vehicle::slowdown().
part_location_structure()
static const std::string part_location_structure ("structure") static
Referenced by vehicle::collision().
terrain_collision_data()
static void terrain_collision_data (const tripoint & p, bool bash_floor, float & mass, float & density, float & elastic) static
Definition at line 459 of file vehicle_move.cpp.
{
    elastic = 0.30;
    map &here = get_map();
    // Just a rough rescale for now to obtain approximately equal numbers
    const int bash_min = here.bash_resistance( p, bash_floor );
    const int bash_max = here.bash_strength( p, bash_floor );
    mass = ( bash_min + bash_max ) / 2.0;
    density = bash_min;
}
References map::bash_resistance(), map::bash_strength(), and get_map().
Referenced by vehicle::part_collision().
vmiph_to_cmps()
int vmiph_to_cmps (int vmiph)
Definition at line 83 of file vehicle_move.cpp.
{
    return vmiph / mps_to_miph;
}
References mps_to_miph.
Referenced by vehicle::ground_acceleration(), and vehicle::water_acceleration().
vmiph_to_mps()
double vmiph_to_mps (int vmiph)
Definition at line 73 of file vehicle_move.cpp.
{
    return vmiph / mps_to_miph / mi_to_vmi;
}
References mi_to_vmi, and mps_to_miph.
Referenced by vehicle::act_on_map(), and vehicle::slowdown().
Variable Documentation
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by vehicle::has_harnessed_animal(), vehicle::selfdrive(), and vehicle::thrust().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by vehicle::has_harnessed_animal(), and vehicle::selfdrive().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by vehicle::part_collision().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by vehicle::has_harnessed_animal(), vehicle::selfdrive(), and vehicle::thrust().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by vehicle::thrust().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by vehicle::thrust().
mi_to_vmi
const int mi_to_vmi = 100 static
Definition at line 62 of file vehicle_move.cpp.
Referenced by mps_to_vmiph(), and vmiph_to_mps().
mps_to_miph
const float mps_to_miph = 2.23694f static
Definition at line 64 of file vehicle_move.cpp.
Referenced by cmps_to_vmiph(), mps_to_vmiph(), vmiph_to_cmps(), and vmiph_to_mps().
skill_driving
const skill_id skill_driving("driving") ("driving") static
Referenced by vehicle::act_on_map(), vehicle::pldrive(), and map::shake_vehicle().
tile_height
const float tile_height = 4 static
Definition at line 60 of file vehicle_move.cpp.
Referenced by vehicle::act_on_map().