Cataclysm BN: src/visitable.cpp File Reference
visitable.cpp File Reference
#include "visitable.h"
#include <algorithm>
#include <climits>
#include <limits>
#include <map>
#include <memory>
#include <unordered_map>
#include <utility>
#include "active_item_cache.h"
#include "bionics.h"
#include "character.h"
#include "colony.h"
#include "debug.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "map.h"
#include "map_selector.h"
#include "monster.h"
#include "mtype.h"
#include "mutation.h"
#include "pimpl.h"
#include "player.h"
#include "point.h"
#include "submap.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
Functions
template<typename T >
static T sum_no_wrap (T a, T b)
Sums the two terms, being careful to not trigger overflow.
template<typename T >
static int has_quality_internal (const T &self, const quality_id &qual, int level, int limit)
static int has_quality_from_vpart (const vehicle &veh, int part, const quality_id &qual, int level, int limit)
template<typename T >
static int max_quality_internal (const T &self, const quality_id &qual)
static int max_quality_from_vpart (const vehicle &veh, int part, const quality_id &qual)
static VisitResponse visit_internal (const std::function< VisitResponse(item *, item *)> &func, item *node, item *parent=nullptr)
static void remove_from_item_valptr (cata::value_ptr< item > &ptr, const std::function< bool(const item &e)> &filter, int &count, std::list< item > &res)
template<typename T , typename M >
static int charges_of_internal (const T &self, const M &main, const itype_id &id, int limit, const std::function< bool(const item &)> &filter, std::function< void(int)> visitor)
template<typename T >
static int amount_of_internal (const T &self, const itype_id &id, bool pseudo, int limit, const std::function< bool(const item &)> &filter)
Variables
static const itype_id itype_apparatus ("apparatus")
static const itype_id itype_adv_UPS_off ("adv_UPS_off")
static const itype_id itype_toolset ("toolset")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_UPS_off ("UPS_off")
static const itype_id itype_bio_armor ("bio_armor")
static const quality_id qual_BUTCHER ("BUTCHER")
static const bionic_id bio_tools ("bio_tools")
static const bionic_id bio_ups ("bio_ups")
static const flag_str_id flag_BIONIC_ARMOR_INTERFACE ("BIONIC_ARMOR_INTERFACE")
Function Documentation
amount_of_internal()
template<typename T > static int amount_of_internal (const T & self, const itype_id & id, bool pseudo, int limit, const std::function< bool(const item &)> & filter) static
Definition at line 1032 of file visitable.cpp.
{
    int qty = 0;
    self.visit_items( [&qty, &id, &pseudo, &limit, &filter]( const item * e ) {
        if( ( id.str() == "any" || e->typeId() == id ) && filter( *e ) && ( pseudo ||
                !e->has_flag( "PSEUDO" ) ) ) {
            qty = sum_no_wrap( qty, 1 );
        }
        return qty != limit ? VisitResponse::NEXT : VisitResponse::ABORT;
    } );
    return qty;
}
References ABORT, item::has_flag(), NEXT, and item::typeId().
Referenced by visitable< T >::amount_of().
charges_of_internal()
template<typename T , typename M > static int charges_of_internal (const T & self, const M & main, const itype_id & id, int limit, const std::function< bool(const item &)> & filter, std::function< void(int)> visitor) static
Definition at line 900 of file visitable.cpp.
{
    int qty = 0;
    bool found_tool_with_UPS = false;
    self.visit_items( [&]( const item * e ) {
        if( filter( *e ) ) {
            if( e->is_tool() ) {
                if( e->typeId() == id ) {
                    // includes charges from any included magazine.
                    qty = sum_no_wrap( qty, e->ammo_remaining() );
                    if( e->has_flag( "USE_UPS" ) ) {
                        found_tool_with_UPS = true;
                    }
                }
                return qty < limit ? VisitResponse::SKIP : VisitResponse::ABORT;
            } else if( e->count_by_charges() ) {
                if( e->typeId() == id ) {
                    qty = sum_no_wrap( qty, e->charges );
                }
                // items counted by charges are not themselves expected to be containers
                return qty < limit ? VisitResponse::SKIP : VisitResponse::ABORT;
            }
        }
        // recurse through any nested containers
        return qty < limit ? VisitResponse::NEXT : VisitResponse::ABORT;
    } );
    if( qty < limit && found_tool_with_UPS ) {
        qty += main.charges_of( itype_UPS, limit - qty );
        if( visitor ) {
            visitor( qty );
        }
    }
    return std::min( qty, limit );
}
References ABORT, item::count_by_charges(), item::is_tool(), and SKIP.
Referenced by visitable< T >::charges_of().
has_quality_from_vpart()
static int has_quality_from_vpart (const vehicle & veh, int part, const quality_id & qual, int level, int limit) static
Definition at line 146 of file visitable.cpp.
{
    int qty = 0;
    auto pos = veh.cpart( part ).mount;
    for( const auto &n : veh.parts_at_relative( pos, true ) ) {
        // only unbroken parts can provide tool qualities
        if( !veh.cpart( n ).is_broken() ) {
            auto tq = veh.part_info( n ).qualities;
            auto iter = tq.find( qual );
            // does the part provide this quality?
            if( iter != tq.end() && iter->second >= level ) {
                qty = sum_no_wrap( qty, 1 );
            }
        }
    }
    return std::min( qty, limit );
}
References vehicle::cpart(), vehicle_part::is_broken(), vehicle_part::mount, vehicle::part_info(), vehicle::parts_at_relative(), vpart_info::qualities, and sum_no_wrap().
has_quality_internal()
template<typename T > static int has_quality_internal (const T & self, const quality_id & qual, int level, int limit) static
Definition at line 129 of file visitable.cpp.
{
    int qty = 0;
    self.visit_items( [&qual, level, &limit, &qty]( const item * e ) {
        if( e->get_quality( qual ) >= level ) {
            qty = sum_no_wrap( qty, static_cast<int>( e->count() ) );
            if( qty >= limit ) {
                // found sufficient items
                return VisitResponse::ABORT;
            }
        }
        return VisitResponse::NEXT;
    } );
    return std::min( qty, limit );
}
References item::get_quality(), and NEXT.
Referenced by visitable< T >::has_quality().
max_quality_from_vpart()
static int max_quality_from_vpart (const vehicle & veh, int part, const quality_id & qual) static
Definition at line 254 of file visitable.cpp.
{
    int res = INT_MIN;
    auto pos = veh.cpart( part ).mount;
    for( const auto &n : veh.parts_at_relative( pos, true ) ) {
        // only unbroken parts can provide tool qualities
        if( !veh.cpart( n ).is_broken() ) {
            auto tq = veh.part_info( n ).qualities;
            auto iter = tq.find( qual );
            // does the part provide this quality?
            if( iter != tq.end() ) {
                res = std::max( res, iter->second );
            }
        }
    }
    return res;
}
References vehicle::cpart(), vehicle_part::is_broken(), vehicle_part::mount, vehicle::part_info(), vehicle::parts_at_relative(), and vpart_info::qualities.
max_quality_internal()
template<typename T > static int max_quality_internal (const T & self, const quality_id & qual) static
Definition at line 244 of file visitable.cpp.
{
    int res = INT_MIN;
    self.visit_items( [&res, &qual]( const item * e ) {
        res = std::max( res, e->get_quality( qual ) );
        return VisitResponse::NEXT;
    } );
    return res;
}
References item::get_quality(), and NEXT.
Referenced by visitable< T >::max_quality().
remove_from_item_valptr()
static void remove_from_item_valptr (cata::value_ptr< item > & ptr, const std::function< bool(const item &e)> & filter, int & count, std::list< item > & res) static
Definition at line 838 of file visitable.cpp.
{
    if( ptr ) {
        if( filter( *ptr ) ) {
            res.push_back( *ptr );
            ptr.reset();
            count -= 1;
        } else {
            ptr->contents.remove_internal( filter, count, res );
        }
    }
}
References detail::count(), and ptr().
sum_no_wrap()
template<typename T > static T sum_no_wrap (T a, T b) static
Sums the two terms, being careful to not trigger overflow.
Doesn't handle underflow.
Parameters
a The first addend.
b The second addend.
Returns
the sum of the addends, but truncated to std::numeric_limits<int>::max().
Definition at line 119 of file visitable.cpp.
{
    if( a > std::numeric_limits<T>::max() - b ||
        b > std::numeric_limits<T>::max() - a ) {
        return std::numeric_limits<T>::max();
    }
    return a + b;
}
References a, and b.
Referenced by has_quality_from_vpart().
visit_internal()
static VisitResponse visit_internal (const std::function< VisitResponse(item *, item *)> & func, item * node, item * parent = nullptr) static
Definition at line 380 of file visitable.cpp.
{
    switch( func( node, parent ) ) {
        case VisitResponse::ABORT:
            return VisitResponse::ABORT;
        case VisitResponse::NEXT:
            if( node->is_gun() || node->is_magazine() ) {
                // Content of guns and magazines are accessible only via their specific accessors
                return VisitResponse::NEXT;
            }
            if( node->contents.visit_contents( func, node ) == VisitResponse::ABORT ) {
                return VisitResponse::ABORT;
            }
        /* intentional fallthrough */
        case VisitResponse::SKIP:
            return VisitResponse::NEXT;
    }
    /* never reached but suppresses GCC warning */
    return VisitResponse::ABORT;
}
References ABORT, item::contents, item::is_gun(), item::is_magazine(), NEXT, SKIP, and item_contents::visit_contents().
Referenced by item_contents::visit_contents(), and visitable< T >::visit_items().
Variable Documentation
bio_tools
const bionic_id bio_tools("bio_tools") ("bio_tools") static
bio_ups
const bionic_id bio_ups("bio_ups") ("bio_ups") static
flag_BIONIC_ARMOR_INTERFACE
const flag_str_id flag_BIONIC_ARMOR_INTERFACE("BIONIC_ARMOR_INTERFACE") ("BIONIC_ARMOR_INTERFACE") static
itype_adv_UPS_off
const itype_id itype_adv_UPS_off("adv_UPS_off") ("adv_UPS_off") static
itype_apparatus
const itype_id itype_apparatus("apparatus") ("apparatus") static
itype_bio_armor
const itype_id itype_bio_armor("bio_armor") ("bio_armor") static
itype_toolset
const itype_id itype_toolset("toolset") ("toolset") static
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
itype_UPS_off
const itype_id itype_UPS_off("UPS_off") ("UPS_off") static
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static