Cataclysm BN: src/vpart_position.h File Reference
vpart_position.h File Reference
#include <cstddef>
#include <functional>
#include <string>
#include <utility>
#include "optional.h"
Classes
class vpart_position
Reference to a position (a point) of the vehicle.
class optional_vpart_position
Simple wrapper to forward functions that may return a cata::optional to vpart_position.
class vpart_reference
This is a wrapper over a vehicle pointer and a reference to a part of it.
Macros
#define CATA_SRC_VPART_POSITION_H
Functions
vehicle * veh_pointer_or_null (const optional_vpart_position &p)
Macro Definition Documentation
CATA_SRC_VPART_POSITION_H
#define CATA_SRC_VPART_POSITION_H
Definition at line 3 of file vpart_position.h.
Function Documentation
veh_pointer_or_null()
vehicle * veh_pointer_or_null (const optional_vpart_position & p) inline
Definition at line 154 of file vpart_position.h.
{
    return p ? &p->vehicle() : nullptr;
}
Referenced by map::add_vehicle_to_map(), map::apply_faction_ownership(), Creature::auto_find_hostile_target(), map::bash(), iuse::cable_attach(), can_do_activity_there(), can_interact_at(), doors::close_door(), item_location::deserialize(), game::do_turn(), draw_health_classic(), draw_veh_compact(), draw_veh_padding(), npc::execute_action(), activity_handlers::fill_liquid_do_turn(), player::fire_gun(), generic_multi_activity_check_requirement(), liquid_handler::get_liquid_target(), game::grabbed_veh_move(), avatar_action::move(), npc::move_to(), map::move_vehicle(), open(), Character::perform_technique(), pickup::pick_up(), game::print_all_tile_info(), sounds::process_sound_markers(), projectile_attack(), game::remoteveh(), DefaultRemovePartHandler::removed(), smash(), activity_handlers::start_engines_finish(), ranged::targetable_creatures(), iuse::tow_attach(), vehicle::try_to_rack_nearby_vehicle(), Character::update_needs(), vehicle::use_controls(), game::validate_linked_vehicles(), vehicle_activity(), and game::walk_move().