Cataclysm BN: src/wdirent.h File Reference
wdirent.h File Reference
#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <wchar.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <ctype.h>
Classes
struct _wdirent
struct _WDIR
struct dirent
struct DIR
Macros
#define DIRENT_H
#define WIN32_LEAN_AND_MEAN
#define _DIRENT_HAVE_D_TYPE
#define _DIRENT_HAVE_D_NAMLEN
#define FILE_ATTRIBUTE_DEVICE 0x40
#define S_IFMT _S_IFMT
#define S_IFDIR _S_IFDIR
#define S_IFCHR _S_IFCHR
#define S_IFFIFO _S_IFFIFO
#define S_IFREG _S_IFREG
#define S_IREAD _S_IREAD
#define S_IWRITE _S_IWRITE
#define S_IEXEC _S_IEXEC
#define S_IFIFO _S_IFIFO
#define S_IFBLK 0
#define S_IFLNK 0
#define S_IFSOCK 0
#define S_IRUSR S_IREAD
#define S_IWUSR S_IWRITE
#define S_IXUSR 0
#define S_IRGRP 0
#define S_IWGRP 0
#define S_IXGRP 0
#define S_IROTH 0
#define S_IWOTH 0
#define S_IXOTH 0
#define PATH_MAX MAX_PATH
#define FILENAME_MAX MAX_PATH
#define NAME_MAX FILENAME_MAX
#define DT_UNKNOWN 0
#define DT_REG S_IFREG
#define DT_DIR S_IFDIR
#define DT_FIFO S_IFIFO
#define DT_SOCK S_IFSOCK
#define DT_CHR S_IFCHR
#define DT_BLK S_IFBLK
#define DT_LNK S_IFLNK
#define IFTODT(mode) ((mode) & S_IFMT)
#define DTTOIF(type) (type)
#define S_ISFIFO(mode) (((mode) & S_IFMT) == S_IFIFO)
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)
#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)
#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)
#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)
#define _D_EXACT_NAMLEN(p) ((p)->d_namlen)
#define _D_ALLOC_NAMLEN(p) ((PATH_MAX)+1)
#define wdirent _wdirent
#define WDIR _WDIR
#define wopendir _wopendir
#define wreaddir _wreaddir
Typedefs
typedef struct _wdirent _wdirent
typedef struct _WDIR _WDIR
typedef struct dirent dirent
typedef struct DIR DIR
Functions
static DIR * opendir (const char *dirname)
static _WDIR * _wopendir (const wchar_t *dirname)
static struct dirent * readdir (DIR *dirp)
static int readdir_r (DIR *dirp, struct dirent *entry, struct dirent **result)
static int closedir (DIR *dirp)
static int _wclosedir (_WDIR *dirp)
static WIN32_FIND_DATAW * dirent_first (_WDIR *dirp)
static WIN32_FIND_DATAW * dirent_next (_WDIR *dirp)
static int dirent_mbstowcs_s (size_t *pReturnValue, wchar_t *wcstr, size_t sizeInWords, const char *mbstr, size_t count)
static int dirent_wcstombs_s (size_t *pReturnValue, char *mbstr, size_t sizeInBytes, const wchar_t *wcstr, size_t count)
static void dirent_set_errno (int error)
Macro Definition Documentation
_D_ALLOC_NAMLEN
#define _D_ALLOC_NAMLEN (p) ((PATH_MAX)+1)
Definition at line 244 of file wdirent.h.
_D_EXACT_NAMLEN
#define _D_EXACT_NAMLEN (p) ((p)->d_namlen)
Definition at line 241 of file wdirent.h.
_DIRENT_HAVE_D_NAMLEN
#define _DIRENT_HAVE_D_NAMLEN
Definition at line 75 of file wdirent.h.
_DIRENT_HAVE_D_TYPE
#define _DIRENT_HAVE_D_TYPE
Definition at line 72 of file wdirent.h.
DIRENT_H
#define DIRENT_H
Definition at line 40 of file wdirent.h.
DT_BLK
#define DT_BLK S_IFBLK
Definition at line 205 of file wdirent.h.
DT_CHR
#define DT_CHR S_IFCHR
Definition at line 204 of file wdirent.h.
DT_DIR
#define DT_DIR S_IFDIR
Definition at line 201 of file wdirent.h.
DT_FIFO
#define DT_FIFO S_IFIFO
Definition at line 202 of file wdirent.h.
DT_LNK
#define DT_LNK S_IFLNK
Definition at line 206 of file wdirent.h.
DT_REG
#define DT_REG S_IFREG
Definition at line 200 of file wdirent.h.
DT_SOCK
#define DT_SOCK S_IFSOCK
Definition at line 203 of file wdirent.h.
DT_UNKNOWN
#define DT_UNKNOWN 0
Definition at line 199 of file wdirent.h.
DTTOIF
#define DTTOIF (type) (type)
Definition at line 210 of file wdirent.h.
FILE_ATTRIBUTE_DEVICE
#define FILE_ATTRIBUTE_DEVICE 0x40
Definition at line 79 of file wdirent.h.
FILENAME_MAX
#define FILENAME_MAX MAX_PATH
Definition at line 192 of file wdirent.h.
IFTODT
#define IFTODT (mode) ((mode) & S_IFMT)
Definition at line 209 of file wdirent.h.
NAME_MAX
#define NAME_MAX FILENAME_MAX
Definition at line 195 of file wdirent.h.
PATH_MAX
#define PATH_MAX MAX_PATH
Definition at line 189 of file wdirent.h.
S_IEXEC
#define S_IEXEC _S_IEXEC
Definition at line 119 of file wdirent.h.
S_IFBLK
#define S_IFBLK 0
Definition at line 129 of file wdirent.h.
S_IFCHR
#define S_IFCHR _S_IFCHR
Definition at line 94 of file wdirent.h.
S_IFDIR
#define S_IFDIR _S_IFDIR
Definition at line 89 of file wdirent.h.
S_IFFIFO
#define S_IFFIFO _S_IFFIFO
Definition at line 99 of file wdirent.h.
S_IFIFO
#define S_IFIFO _S_IFIFO
Definition at line 124 of file wdirent.h.
S_IFLNK
#define S_IFLNK 0
Definition at line 134 of file wdirent.h.
S_IFMT
#define S_IFMT _S_IFMT
Definition at line 84 of file wdirent.h.
S_IFREG
#define S_IFREG _S_IFREG
Definition at line 104 of file wdirent.h.
S_IFSOCK
#define S_IFSOCK 0
Definition at line 139 of file wdirent.h.
S_IREAD
#define S_IREAD _S_IREAD
Definition at line 109 of file wdirent.h.
S_IRGRP
#define S_IRGRP 0
Definition at line 159 of file wdirent.h.
S_IROTH
#define S_IROTH 0
Definition at line 174 of file wdirent.h.
S_IRUSR
#define S_IRUSR S_IREAD
Definition at line 144 of file wdirent.h.
S_ISBLK
#define S_ISBLK (mode) (((mode) & S_IFMT) == S_IFBLK)
Definition at line 237 of file wdirent.h.
S_ISCHR
#define S_ISCHR (mode) (((mode) & S_IFMT) == S_IFCHR)
Definition at line 234 of file wdirent.h.
S_ISDIR
#define S_ISDIR (mode) (((mode) & S_IFMT) == S_IFDIR)
Definition at line 222 of file wdirent.h.
S_ISFIFO
#define S_ISFIFO (mode) (((mode) & S_IFMT) == S_IFIFO)
Definition at line 219 of file wdirent.h.
S_ISLNK
#define S_ISLNK (mode) (((mode) & S_IFMT) == S_IFLNK)
Definition at line 228 of file wdirent.h.
S_ISREG
#define S_ISREG (mode) (((mode) & S_IFMT) == S_IFREG)
Definition at line 225 of file wdirent.h.
S_ISSOCK
#define S_ISSOCK (mode) (((mode) & S_IFMT) == S_IFSOCK)
Definition at line 231 of file wdirent.h.
S_IWGRP
#define S_IWGRP 0
Definition at line 164 of file wdirent.h.
S_IWOTH
#define S_IWOTH 0
Definition at line 179 of file wdirent.h.
S_IWRITE
#define S_IWRITE _S_IWRITE
Definition at line 114 of file wdirent.h.
S_IWUSR
#define S_IWUSR S_IWRITE
Definition at line 149 of file wdirent.h.
S_IXGRP
#define S_IXGRP 0
Definition at line 169 of file wdirent.h.
S_IXOTH
#define S_IXOTH 0
Definition at line 184 of file wdirent.h.
S_IXUSR
#define S_IXUSR 0
Definition at line 154 of file wdirent.h.
WDIR
#define WDIR _WDIR
Definition at line 335 of file wdirent.h.
wdirent
#define wdirent _wdirent
Definition at line 334 of file wdirent.h.
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 56 of file wdirent.h.
wopendir
#define wopendir _wopendir
Definition at line 336 of file wdirent.h.
wreaddir
#define wreaddir _wreaddir
Definition at line 337 of file wdirent.h.
Typedef Documentation
_WDIR
typedef struct _WDIR _WDIR
Definition at line 290 of file wdirent.h.
_wdirent
typedef struct _wdirent _wdirent
Definition at line 272 of file wdirent.h.
DIR
typedef struct DIR DIR
Definition at line 318 of file wdirent.h.
dirent
typedef struct dirent dirent
Definition at line 312 of file wdirent.h.
Function Documentation
_wclosedir()
static int _wclosedir (_WDIR * dirp) static
Definition at line 464 of file wdirent.h.
{
    if( !dirp ) {
        dirent_set_errno( EBADF );
        return /*failure*/ -1;
    }
    /* Release search handle */
    if( dirp->handle != INVALID_HANDLE_VALUE ) {
        FindClose( dirp->handle );
    }
    /* Release search pattern */
    free( dirp->patt );
    /* Release directory structure */
    free( dirp );
    return /*success*/0;
}
References dirent_set_errno(), _WDIR::handle, and _WDIR::patt.
Referenced by _wopendir(), and closedir().
_wopendir()
static _WDIR * _wopendir (const wchar_t * dirname) static
Definition at line 367 of file wdirent.h.
{
    wchar_t *p;
    /* Must have directory name */
    if( dirname == NULL || dirname[0] == '\0' ) {
        dirent_set_errno( ENOENT );
        return NULL;
    }
    /* Allocate new _WDIR structure */
    _WDIR *dirp = ( _WDIR * ) malloc( sizeof( struct _WDIR ) );
    if( !dirp ) {
        return NULL;
    }
    /* Reset _WDIR structure */
    dirp->handle = INVALID_HANDLE_VALUE;
    dirp->patt = NULL;
    dirp->cached = 0;
    /*
     * Compute the length of full path plus zero terminator
     *
     * Note that on WinRT there's no way to convert relative paths
     * into absolute paths, so just assume it is an absolute path.
     */
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    /* Desktop */
    DWORD n = GetFullPathNameW( dirname, 0, NULL, NULL );
#else
    /* WinRT */
    size_t n = wcslen( dirname );
#endif
    /* Allocate room for absolute directory name and search pattern */
    dirp->patt = ( wchar_t * ) malloc( sizeof( wchar_t ) * n + 16 );
    if( dirp->patt == NULL ) {
        goto exit_closedir;
    }
    /*
     * Convert relative directory name to an absolute one.  This
     * allows rewinddir() to function correctly even when current
     * working directory is changed between opendir() and rewinddir().
     *
     * Note that on WinRT there's no way to convert relative paths
     * into absolute paths, so just assume it is an absolute path.
     */
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    /* Desktop */
    n = GetFullPathNameW( dirname, n, dirp->patt, NULL );
    if( n <= 0 ) {
        goto exit_closedir;
    }
#else
    /* WinRT */
    wcsncpy_s( dirp->patt, n + 1, dirname, n );
#endif
    /* Append search pattern \* to the directory name */
    p = dirp->patt + n;
    switch( p[-1] ) {
        case '\\':
        case '/':
        case ':':
            /* Directory ends in path separator, e.g. c:\temp\ */
            /*NOP*/
            ;
            break;
        default:
            /* Directory name doesn't end in path separator */
            *p++ = '\\';
    }
    *p++ = '*';
    *p = '\0';
    /* Open directory stream and retrieve the first entry */
    if( !dirent_first( dirp ) ) {
        goto exit_closedir;
    }
    /* Success */
    return dirp;
    /* Failure */
exit_closedir:
    _wclosedir( dirp );
    return NULL;
}
References _wclosedir(), _WDIR::cached, dirent_first(), dirent_set_errno(), _WDIR::handle, and _WDIR::patt.
Referenced by opendir().
closedir()
static int closedir (DIR * dirp) static
Definition at line 688 of file wdirent.h.
{
    int ok;
    if( !dirp ) {
        goto exit_failure;
    }
    /* Close wide-character directory stream */
    ok = _wclosedir( dirp->wdirp );
    dirp->wdirp = NULL;
    /* Release multi-byte character version */
    free( dirp );
    return ok;
exit_failure:
    /* Invalid directory stream */
    dirent_set_errno( EBADF );
    return /*failure*/ -1;
}
References _wclosedir(), dirent_set_errno(), ok, and DIR::wdirp.
Referenced by dir_exist(), and anonymous_namespace{filesystem.cpp}::for_each_dir_entry().
dirent_first()
static WIN32_FIND_DATAW * dirent_first (_WDIR * dirp) static
Definition at line 485 of file wdirent.h.
{
    if( !dirp ) {
        return NULL;
    }
    /* Open directory and retrieve the first entry */
    dirp->handle = FindFirstFileExW(
                       dirp->patt, FindExInfoStandard, &dirp->data,
                       FindExSearchNameMatch, NULL, 0 );
    if( dirp->handle == INVALID_HANDLE_VALUE ) {
        goto error;
    }
    /* A directory entry is now waiting in memory */
    dirp->cached = 1;
    return &dirp->data;
error:
    /* Failed to open directory: no directory entry in memory */
    dirp->cached = 0;
    /* Set error code */
    DWORD errorcode = GetLastError();
    switch( errorcode ) {
        case ERROR_ACCESS_DENIED:
            /* No read access to directory */
            dirent_set_errno( EACCES );
            break;
        case ERROR_DIRECTORY:
            /* Directory name is invalid */
            dirent_set_errno( ENOTDIR );
            break;
        case ERROR_PATH_NOT_FOUND:
        default:
            /* Cannot find the file */
            dirent_set_errno( ENOENT );
    }
    return NULL;
}
References _WDIR::cached, _WDIR::data, dirent_set_errno(), detail::digits::error, _WDIR::handle, and _WDIR::patt.
Referenced by _wopendir().
dirent_mbstowcs_s()
static int dirent_mbstowcs_s (size_t * pReturnValue, wchar_t * wcstr, size_t sizeInWords, const char * mbstr, size_t count) static
Definition at line 711 of file wdirent.h.
{
    const int required_size = MultiByteToWideChar( CP_UTF8, 0, mbstr, -1, NULL, 0 ) + 1;
    if( required_size > static_cast<int>( sizeInWords ) ) {
        return 1;
    }
    const int n = MultiByteToWideChar( CP_UTF8, 0, mbstr, -1, wcstr, required_size );
    if( n == 0 ) {
        debugmsg( "MultiByteToWideChar failed!" );
        return 1;
    }
    if( pReturnValue ) {
        *pReturnValue = n;
    }
    return 0;
}
References debugmsg.
Referenced by opendir().
dirent_next()
static WIN32_FIND_DATAW * dirent_next (_WDIR * dirp) static
Definition at line 529 of file wdirent.h.
{
    /* Is the next directory entry already in cache? */
    if( dirp->cached ) {
        /* Yes, a valid directory entry found in memory */
        dirp->cached = 0;
        return &dirp->data;
    }
    /* No directory entry in cache */
    if( dirp->handle == INVALID_HANDLE_VALUE ) {
        return NULL;
    }
    /* Read the next directory entry from stream */
    if( FindNextFileW( dirp->handle, &dirp->data ) == FALSE ) {
        goto exit_close;
    }
    /* Success */
    return &dirp->data;
    /* Failure */
exit_close:
    FindClose( dirp->handle );
    dirp->handle = INVALID_HANDLE_VALUE;
    return NULL;
}
References _WDIR::cached, _WDIR::data, and _WDIR::handle.
Referenced by readdir_r().
dirent_set_errno()
static void dirent_set_errno (int error) static
Definition at line 752 of file wdirent.h.
{
    /* Non-Microsoft compiler or older Microsoft compiler */
    errno = error;
}
References detail::digits::error.
Referenced by _wclosedir(), _wopendir(), closedir(), dirent_first(), and opendir().
dirent_wcstombs_s()
static int dirent_wcstombs_s (size_t * pReturnValue, char * mbstr, size_t sizeInBytes, const wchar_t * wcstr, size_t count) static
Definition at line 731 of file wdirent.h.
{
    const int required_size = WideCharToMultiByte( CP_UTF8, 0, wcstr, -1, NULL, 0, NULL, 0 ) + 1;
    if( required_size > static_cast<int>( sizeInBytes ) ) {
        return 1;
    }
    const int n = WideCharToMultiByte( CP_UTF8, 0, wcstr, -1, mbstr, required_size, NULL, 0 );
    if( n == 0 ) {
        debugmsg( "WideCharToMultiByte failed!" );
        return 1;
    }
    if( pReturnValue ) {
        *pReturnValue = n;
    }
    return 0;
}
References debugmsg.
Referenced by readdir_r().
opendir()
static DIR * opendir (const char * dirname) static
Definition at line 559 of file wdirent.h.
{
    /* Must have directory name */
    if( dirname == NULL || dirname[0] == '\0' ) {
        dirent_set_errno( ENOENT );
        return NULL;
    }
    /* Allocate memory for DIR structure */
    struct DIR *dirp = ( DIR * ) malloc( sizeof( struct DIR ) );
    if( !dirp ) {
        return NULL;
    }
    /* Convert directory name to wide-character string */
    wchar_t wname[PATH_MAX + 1];
    size_t n;
    int error = dirent_mbstowcs_s( &n, wname, PATH_MAX + 1, dirname, PATH_MAX + 1 );
    if( error ) {
        goto exit_failure;
    }
    /* Open directory stream using wide-character name */
    dirp->wdirp = _wopendir( wname );
    if( !dirp->wdirp ) {
        goto exit_failure;
    }
    /* Success */
    return dirp;
    /* Failure */
exit_failure:
    free( dirp );
    return NULL;
}
References _wopendir(), dirent_mbstowcs_s(), dirent_set_errno(), detail::digits::error, PATH_MAX, and DIR::wdirp.
Referenced by dir_exist(), and anonymous_namespace{filesystem.cpp}::for_each_dir_entry().
readdir()
static struct dirent * readdir (DIR * dirp) static
Definition at line 597 of file wdirent.h.
{
    /*
     * Read directory entry to buffer.  We can safely ignore the return
     * value as entry will be set to NULL in case of error.
     */
    struct dirent *entry;
    ( void ) readdir_r( dirp, &dirp->ent, &entry );
    /* Return pointer to statically allocated directory entry */
    return entry;
}
References DIR::ent, and readdir_r().
Referenced by anonymous_namespace{filesystem.cpp}::for_each_dir_entry().
readdir_r()
static int readdir_r (DIR * dirp, struct dirent * entry, struct dirent ** result) static
Definition at line 616 of file wdirent.h.
{
    /* Read next directory entry */
    WIN32_FIND_DATAW *datap = dirent_next( dirp->wdirp );
    if( !datap ) {
        /* No more directory entries */
        *result = NULL;
        return /*OK*/0;
    }
    /* Attempt to convert file name to multi-byte string */
    size_t n;
    int error = dirent_wcstombs_s(
                    &n, entry->d_name, PATH_MAX + 1,
                    datap->cFileName, PATH_MAX + 1 );
    /*
     * If the file name cannot be represented by a multi-byte string, then
     * attempt to use old 8+3 file name.  This allows the program to
     * access files although file names may seem unfamiliar to the user.
     *
     * Be ware that the code below cannot come up with a short file name
     * unless the file system provides one.  At least VirtualBox shared
     * folders fail to do this.
     */
    if( error && datap->cAlternateFileName[0] != '\0' ) {
        error = dirent_wcstombs_s(
                    &n, entry->d_name, PATH_MAX + 1,
                    datap->cAlternateFileName, PATH_MAX + 1 );
    }
    if( !error ) {
        /* Length of file name excluding zero terminator */
        entry->d_namlen = n - 1;
        /* File attributes */
        DWORD attr = datap->dwFileAttributes;
        if( ( attr & FILE_ATTRIBUTE_DEVICE ) != 0 ) {
            entry->d_type = DT_CHR;
        } else if( ( attr & FILE_ATTRIBUTE_DIRECTORY ) != 0 ) {
            entry->d_type = DT_DIR;
        } else {
            entry->d_type = DT_REG;
        }
        /* Reset dummy fields */
        entry->d_ino = 0;
        entry->d_off = 0;
        entry->d_reclen = sizeof( struct dirent );
    } else {
        /*
         * Cannot convert file name to multi-byte string so construct
         * an erroneous directory entry and return that.  Note that
         * we cannot return NULL as that would stop the processing
         * of directory entries completely.
         */
        entry->d_name[0] = '?';
        entry->d_name[1] = '\0';
        entry->d_namlen = 1;
        entry->d_type = DT_UNKNOWN;
        entry->d_ino = 0;
        entry->d_off = -1;
        entry->d_reclen = 0;
    }
    /* Return pointer to directory entry */
    *result = entry;
    return /*OK*/0;
}
References dirent::d_ino, dirent::d_name, dirent::d_namlen, dirent::d_off, dirent::d_reclen, dirent::d_type, dirent_next(), dirent_wcstombs_s(), DT_CHR, DT_DIR, DT_REG, DT_UNKNOWN, detail::digits::error, FILE_ATTRIBUTE_DEVICE, PATH_MAX, and DIR::wdirp.
Referenced by readdir().