Cataclysm BN: src/weather_gen.cpp File Reference
weather_gen.cpp File Reference
#include "weather_gen.h"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <ostream>
#include <random>
#include <string>
#include "assign.h"
#include "cached_options.h"
#include "cata_utility.h"
#include "fstream_utils.h"
#include "game_constants.h"
#include "generic_readers.h"
#include "json.h"
#include "math_defines.h"
#include "point.h"
#include "rng.h"
#include "simplexnoise.h"
#include "weather.h"
Classes
struct weather_gen_common
Namespaces
namespace anonymous_namespace{weather_gen.cpp}
Functions
static weather_gen_common get_common_data (const point_abs_ms &location, const time_point &t, const calendar_config &calendar_config, unsigned seed)
static units::temperature season_temp (const weather_generator &wg, double year_fraction)
static units::temperature weather_temperature_from_common_data (const weather_generator &wg, const weather_gen_common &common, const time_point &t)
bool maybe_temperature_reader (const JsonObject &jo, const std::string &member_name, units::temperature &member, bool was_loaded)
Variables
constexpr double anonymous_namespace{weather_gen.cpp}::tau = M_PI * 2
constexpr double anonymous_namespace{weather_gen.cpp}::coldest_hour = 5
Function Documentation
get_common_data()
static weather_gen_common get_common_data (const point_abs_ms & location, const time_point & t, const calendar_config & calendar_config, unsigned seed) static
Definition at line 45 of file weather_gen.cpp.
{
    weather_gen_common result;
    // Integer x position / widening factor of the Perlin function.
    result.x = location.x() / 2000.0;
    // Integer y position / widening factor of the Perlin function.
    result.y = location.y() / 2000.0;
    // Integer turn / widening factor of the Perlin function.
    result.z = to_days<double>( t - calendar::turn_zero );
    // Limit the random seed during noise calculation, a large value flattens the noise generator to zero
    // Windows has a rand limit of 32768, other operating systems can have higher limits
    result.modSEED = seed % SIMPLEX_NOISE_RANDOM_SEED_LIMIT;
    // Eternal season = midpoint of initial season all the time
    const double year_fraction = calendar_config.eternal_season() ?
                                 ( 0.25 * static_cast<double>( calendar_config.initial_season() ) + 0.125 ) :
                                 ( time_past_new_year( t ) / calendar::year_length() );
    result.year_fraction = year_fraction;
    // We add one-eighth to line it up so that +1 is at
    // midwinter and -1 at midsummer. (Cataclysm years
    // start when spring starts. Gregorian years start when
    // winter starts.)
    result.cosine_of_gregorian_year_fraction = std::cos( tau * ( year_fraction + .125 ) ); // [-1, 1]
    result.season = season_of_year( t );
    return result;
}
References units::cos(), calendar_config::eternal_season(), calendar_config::initial_season(), season_of_year(), iuse::seed(), SIMPLEX_NOISE_RANDOM_SEED_LIMIT, anonymous_namespace{weather_gen.cpp}::tau, time_past_new_year(), calendar::turn_zero, coords::coord_point< Point, Origin, Scale >::x(), coords::coord_point< Point, Origin, Scale >::y(), and calendar::year_length().
Referenced by weather_generator::get_weather(), and weather_generator::get_weather_temperature().
maybe_temperature_reader()
bool maybe_temperature_reader (const JsonObject & jo, const std::string & member_name, units::temperature & member, bool was_loaded) inline
Definition at line 363 of file weather_gen.cpp.
{
    try {
        return temperature_reader()( jo, member_name, member, was_loaded );
    } catch( const JsonError & ) {
        int legacy_value;
        if( !jo.read( member_name, legacy_value ) ) {
            return false;
        }
        member = units::from_celsius( legacy_value );
    }
    return true;
}
References units::from_celsius(), mapgen_defer::member, and JsonObject::read().
Referenced by weather_generator::load().
season_temp()
static units::temperature season_temp (const weather_generator & wg, double year_fraction) static
Definition at line 74 of file weather_gen.cpp.
{
    // Interpolate seasons temperature
    // Scale year_fraction [0, 1) to [0.0, 4.0). So [0.0, 1.0) - spring, [1.0, 2.0) - summer, [2.0, 3.0) - autumn, [3.0, 4.0) - winter.
    const double quadrum = year_fraction * 4;
    const double season_midpoint_quadrum = quadrum - 0.5;
    const size_t current_season = ( static_cast<size_t>( std::floor( season_midpoint_quadrum ) +
                                    NUM_SEASONS ) ) % NUM_SEASONS;
    const size_t next_season = ( current_season + 1 ) % NUM_SEASONS;
    // 0 - current season just started, 1 - season just ended (shouldn't actually happen)
    const double t = season_midpoint_quadrum - std::floor( season_midpoint_quadrum );
    return units::multiply_any_unit( wg.season_stats[current_season].average_temperature, 1.0 - t )
           + units::multiply_any_unit( wg.season_stats[next_season].average_temperature, t );
}
References units::multiply_any_unit(), NUM_SEASONS, and weather_generator::season_stats.
Referenced by weather_temperature_from_common_data().
weather_temperature_from_common_data()
static units::temperature weather_temperature_from_common_data (const weather_generator & wg, const weather_gen_common & common, const time_point & t) static
Definition at line 89 of file weather_gen.cpp.
{
    const double x( common.x );
    const double y( common.y );
    const double z( common.z );
    const unsigned modSEED = common.modSEED;
    const double dayFraction = time_past_midnight( t ) / 1_days;
    // -1 at coldest_hour, +1 twelve hours later
    const double dayv = std::cos( tau * ( dayFraction + .5 - coldest_hour / 24 ) );
    units::temperature season_factor = season_temp( wg, common.year_fraction );
    const double temperature_celsius =
        units::to_celsius<double>( season_factor ) +
        dayv * units::to_celsius<double>( wg.temperature_daily_amplitude ) +
        raw_noise_4d( x, y, z, modSEED ) * units::to_celsius<double>( wg.temperature_noise_amplitude );
    return units::from_celsius( temperature_celsius );
}
References anonymous_namespace{weather_gen.cpp}::coldest_hour, game_menus::inv::common(), units::cos(), units::from_celsius(), raw_noise_4d(), season_temp(), anonymous_namespace{weather_gen.cpp}::tau, weather_generator::temperature_daily_amplitude, weather_generator::temperature_noise_amplitude, and time_past_midnight().
Referenced by weather_generator::get_weather(), and weather_generator::get_weather_temperature().