Cataclysm BN: src/weather.cpp File Reference
weather.cpp File Reference
#include "weather.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <memory>
#include <string>
#include <vector>
#include "assign.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "enums.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "item_contents.h"
#include "map.h"
#include "math_defines.h"
#include "messages.h"
#include "options.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "point_float.h"
#include "regional_settings.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translations.h"
#include "trap.h"
#include "units.h"
#include "units_temperature.h"
#include "vpart_position.h"
#include "weather_gen.h"
Classes
struct forecast_period
Namespaces
namespace weather
Functions
static const std::string flag_SUN_GLASSES ("SUN_GLASSES")
weather_manager & get_weather ()
static bool is_player_outside ()
void glare (const weather_type_id &w)
Glare.
int incident_sunlight (const weather_type_id &wtype, const time_point &t)
Amount of sunlight incident at the ground, taking weather and time of day into account.
void proc_weather_sum (const weather_type_id wtype, weather_sum &data, const time_point &t, const time_duration &tick_size)
const weather_type_id & current_weather (const tripoint &location, const time_point &t)
weather_sum sum_conditions (const time_point &start, const time_point &end, const tripoint &location)
void retroactively_fill_from_funnel (item &it, const trap &tr, const time_point &start, const time_point &end, const tripoint &pos)
Determine what a funnel has filled out of game, using funnelcontainer.bday as a starting point.
double funnel_charges_per_turn (const double surface_area_mm2, const double rain_depth_mm_per_hour)
static void fill_funnels (int rain_depth_mm_per_hour, bool acid, const trap &tr)
Main routine for filling funnels from weather effects.
static void fill_water_collectors (int mmPerHour, bool acid)
Fill funnels and makeshift funnels from weather effects.
double precip_mm_per_hour (precip_class const p)
void handle_weather_effects (const weather_type_id &w)
static std::string to_string (const weekdays &d)
static std::string print_time_just_hour (const time_point &p)
std::string weather_forecast (const point_abs_sm &abs_sm_pos)
Generate textual weather forecast for the specified radio tower.
std::string print_temperature (double fahrenheit, int decimals)
Print temperature (and convert to Celsius if Celsius display is enabled.)
std::string print_temperature (units::temperature temperature, int decimals)
std::string print_humidity (double humidity, int decimals)
Print relative humidity (no conversions.)
std::string print_pressure (double pressure, int decimals)
Print pressure (no conversions.)
static double local_windchill_lowtemp (double temperature_f, double, double wind_mph)
static double local_windchill_hightemp (double temperature_f, double humidity, double wind_mph)
int get_local_windchill (double temperature_f, double humidity, double wind_mph)
nc_color get_wind_color (double windpower)
std::string get_shortdirstring (int angle)
std::string get_dirstring (int angle)
std::string get_wind_arrow (int dirangle)
int get_local_humidity (double humidity, const weather_type_id &weather, bool sheltered)
double get_local_windpower (double windpower, const oter_id &omter, const tripoint &location, const int &winddirection, bool sheltered)
bool is_wind_blocker (const tripoint &location)
std::string get_wind_desc (double windpower)
rl_vec2d convert_wind_to_coord (const int angle)
bool warm_enough_to_plant (const tripoint &pos)
Is it warm enough to plant seeds?
bool warm_enough_to_plant (const tripoint_abs_omt &pos)
bool weather::is_sheltered (const map &m, const tripoint &p)
bool weather::is_in_sunlight (const map &m, const tripoint &p, const weather_type_id &weather)
Variables
static const activity_id ACT_WAIT_WEATHER ("ACT_WAIT_WEATHER")
static const bionic_id bio_sunglasses ("bio_sunglasses")
static const efftype_id effect_glare ("glare")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_snow_glare ("snow_glare")
static const itype_id itype_water ("water")
static const itype_id itype_water_acid ("water_acid")
static const itype_id itype_water_acid_weak ("water_acid_weak")
static const trait_id trait_CEPH_VISION ("CEPH_VISION")
static const trait_id trait_FEATHERS ("FEATHERS")
constexpr int NUM_FORECAST_PERIODS = 6
Function Documentation
flag_SUN_GLASSES()
static const std::string flag_SUN_GLASSES ("SUN_GLASSES") static
Referenced by glare().
Variable Documentation
ACT_WAIT_WEATHER
const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER") ("ACT_WAIT_WEATHER") static
Referenced by weather_manager::update_weather().
bio_sunglasses
const bionic_id bio_sunglasses("bio_sunglasses") ("bio_sunglasses") static
Referenced by glare().
effect_glare
const efftype_id effect_glare("glare") ("glare") static
Referenced by glare().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by weather_effect::thunder().
effect_snow_glare
const efftype_id effect_snow_glare("snow_glare") ("snow_glare") static
Referenced by glare().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by item::add_rain_to_container(), and funnel_charges_per_turn().
itype_water_acid
const itype_id itype_water_acid("water_acid") ("water_acid") static
Referenced by item::add_rain_to_container().
itype_water_acid_weak
const itype_id itype_water_acid_weak("water_acid_weak") ("water_acid_weak") static
Referenced by item::add_rain_to_container().
trait_CEPH_VISION
const trait_id trait_CEPH_VISION("CEPH_VISION") ("CEPH_VISION") static
Referenced by glare().
trait_FEATHERS
const trait_id trait_FEATHERS("FEATHERS") ("FEATHERS") static
Referenced by weather_effect::wet_player().