Cataclysm BN: src/worldfactory.h File Reference
worldfactory.h File Reference
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <map>
#include <memory>
#include <vector>
#include <string>
#include "options.h"
#include "pimpl.h"
#include "type_id.h"
Classes
class save_t
struct WORLD
class worldfactory
Namespaces
namespace catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_WORLDFACTORY_H
Typedefs
using WORLDPTR = WORLD *
Functions
void load_world_option (const JsonObject &jo)
void load_external_option (const JsonObject &jo)
Variables
std::unique_ptr< worldfactory > world_generator
Macro Definition Documentation
CATA_SRC_WORLDFACTORY_H
#define CATA_SRC_WORLDFACTORY_H
Definition at line 3 of file worldfactory.h.
Typedef Documentation
WORLDPTR
using WORLDPTR = WORLD *
Definition at line 85 of file worldfactory.h.
Function Documentation
load_external_option()
void load_external_option (const JsonObject & jo)
Definition at line 1635 of file worldfactory.cpp.
{
    auto name = jo.get_string( "name" );
    auto stype = jo.get_string( "stype" );
    options_manager &opts = get_options();
    if( !opts.has_option( name ) ) {
        auto sinfo = jo.get_string( "info" );
        opts.add_external( name, "external_options", stype, sinfo, sinfo );
    }
    options_manager::cOpt &opt = opts.get_option( name );
    if( stype == "float" ) {
        opt.setValue( static_cast<float>( jo.get_float( "value" ) ) );
    } else if( stype == "int" ) {
        opt.setValue( jo.get_int( "value" ) );
    } else if( stype == "bool" ) {
        if( jo.get_bool( "value" ) ) {
            opt.setValue( "true" );
        } else {
            opt.setValue( "false" );
        }
    } else if( stype == "string" ) {
        opt.setValue( jo.get_string( "value" ) );
    } else {
        jo.throw_error( "Unknown or unsupported stype for external option", "stype" );
    }
    // Just visit this member if it exists
    if( jo.has_member( "info" ) ) {
        jo.get_string( "info" );
    }
}
References options_manager::add_external(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), options_manager::get_option(), get_options(), JsonObject::get_string(), JsonObject::has_member(), options_manager::has_option(), om_direction::name(), options_manager::cOpt::setValue(), and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
load_world_option()
void load_world_option (const JsonObject & jo)
Definition at line 1623 of file worldfactory.cpp.
{
    auto arr = jo.get_array( "options" );
    if( arr.empty() ) {
        jo.throw_error( "no options specified", "options" );
    }
    for( const std::string line : arr ) {
        get_options().get_option( line ).setValue( "true" );
    }
}
References JsonObject::get_array(), options_manager::get_option(), get_options(), line(), options_manager::cOpt::setValue(), and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
Variable Documentation
world_generator
std::unique_ptr<worldfactory> world_generator extern
Definition at line 42 of file worldfactory.cpp.
Referenced by l10n_data::add_mod_catalogues(), game::check_mod_data(), game::cleanup_at_end(), avatar::create(), game::game(), game::get_world_base_save_path(), game::handle_action(), game::list_active_characters(), game::load(), main_menu::load_character_tab(), game::load_world_modfiles(), worldfactory::make_new_world(), game_info::mods_loaded(), main_menu::new_character_tab(), distribution_grid_tracker::on_saved(), main_menu::opening_screen(), game::quickload(), avatar::randomize(), game::reload_tileset(), game::save(), WORLD::save(), worldfactory::set_active_world(), set_scenario(), options_manager::show(), WORLD::WORLD(), main_menu::world_tab(), and game::write_memorial_file().